### PR TITLE
Fix json reexports of different items with same name

### LINKED ISSUE #107677: Rustdoc re-exports only include one item per name across all namespaces
I tried this code:

```rust
//! This crate exports the following:
//! - the function `Foo`, also as `Bar` and `nested::Foo`
//! - the type `Foo`, also as `Bar` and `nested::Foo`

pub mod nested {
    pub struct Foo {}

    #[allow(non_snake_case)]
    pub fn Foo() {}
}

pub use nested::Foo;
pub use Foo as Bar;

// Proof that both the type and the function are visible.
// Not exported.
#[allow(dead_code)]
fn proof() -> Bar {
    Bar();
    Bar {}
}
```

I expected to see this happen: generated rustdoc JSON should include `"import"` items that point to both the function and the type named `Foo`, for each of the re-exported `Foo` and `Bar` names.

Instead, this happened: the rustdoc JSON only one `"import"` item for `Foo` and one for `Bar`, both pointing to the function. No re-export items pointing to the struct were present, as if the struct was not re-exported (even though the `proof()` function shows it is).

These are the only `"kind": "import"` items present in the rustdoc JSON.
```json
{
    // ...
    "kind": "import",
    "inner": {
        "source": "nested::Foo",
        "name": "Foo",
        "id": "0:5:1592",
        "glob": false
    }

    // ...
    "kind": "import",
    "inner": {
        "source": "Foo",
        "name": "Bar",
        "id": "0:5:1592",
        "glob": false
    }
}
```

This is the item those point to:
```json
"0:5:1592": {
    "id": "0:5:1592",
    "crate_id": 0,
    "name": "Foo",
    "span": {
        "filename": "src/lib.rs",
        "begin": [
            18,
            4
        ],
        "end": [
            18,
            19
        ]
    },
    "visibility": "public",
    "docs": null,
    "links": {},
    "attrs": [
        "#[allow(non_snake_case)]"
    ],
    "deprecation": null,
    "kind": "function",
    // ...
}
```

This issue originally came up as https://github.com/obi1kenobi/cargo-semver-checks/issues/343, since `clap v3.2.0` re-exports [a trait](https://github.com/clap-rs/clap/blob/v3.2.0/src/lib.rs#L69-L71) and [a derive macro](https://github.com/clap-rs/clap/blob/v3.1.18/clap_derive/src/lib.rs#L31-L37) that have the same name.

`trustfall-rustdoc-adapter` PR https://github.com/obi1kenobi/trustfall-rustdoc-adapter/pull/72 includes this failing test case.

### Meta

`rustc --version --verbose`:
```
$ rustc --version --verbose
rustc 1.69.0-nightly (d7948c843 2023-01-26)
binary: rustc
commit-hash: d7948c843de94245c794e8c63dd4301a78bb5ba3
commit-date: 2023-01-26
host: x86_64-unknown-linux-gnu
release: 1.69.0-nightly
LLVM version: 15.0.7
```

Also present in 1.67 and 1.68.0-beta.1 (efd27454a 2023-01-25).

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Fixes  #107677.

I renamed `from_item_id*` functions into `id_from_item` instead because it makes more sense now. I also simplified the logic around it a bit so that the `ids` function will now directly pass `&clean::Item` to `id_from_item` and the ID will be consistently generated (it caused an issue when I updated the ID for imports).

So now, the big change of this PR: I changed how imports' ID is generated: it now includes the target item's ID at the end of the ID. It's to prevent two reexported items with the same name (but different types).

r? @aDotInTheVoid

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
Fixed the bad primitive change I made.

File: src/librustdoc/json/conversions.rs [hunk 1]
```diff
@@ -207,18 +208,28 @@ impl FromWithTcx<clean::TypeBindingKind> for TypeBindingKind {
 /// It generates an ID as follows:
 ///
 /// `CRATE_ID:ITEM_ID[:NAME_ID]` (if there is no name, NAME_ID is not generated).
```
Comment (aDotInTheVoid) [inline src/librustdoc/json/conversions.rs:210]: Could this doc comment be updated to the new format (and also document what the `extra` and `name` params are for

File: src/librustdoc/json/conversions.rs [hunk 2]
```diff
@@ -107,7 +108,7 @@ impl JsonRenderer<'_> {
             Some(ty::Visibility::Public) => Visibility::Public,
             Some(ty::Visibility::Restricted(did)) if did.is_crate_root() => Visibility::Crate,
             Some(ty::Visibility::Restricted(did)) => Visibility::Restricted {
-                parent: from_item_id(did.into(), self.tcx),
+                parent: id_from_item_inner(did.into(), self.tcx, None, None),
```
Comment (aDotInTheVoid) [inline src/librustdoc/json/conversions.rs:111]: This seems like a pretty common pattern. I think it's worth writing a helper function, instead of writing `None, None` everywhere .

File: tests/rustdoc-json/reexport/same_name_different_types.rs [hunk 3]
```diff
@@ -0,0 +1,16 @@
...
+#![feature(no_core)]
+#![no_core]
+
+pub mod nested {
+    pub struct Foo {}
+
+    #[allow(non_snake_case)]
+    pub fn Foo() {}
+}
+
```
Comment (aDotInTheVoid) [inline tests/rustdoc-json/reexport/same_name_different_types.rs:12]: Could this test be expanded a bit more? I'd like to see it checking that their are items for both `Foo`s, and that each name imports both of the foo items (instead of just checking that their are two imports with each name).

**Review by aDotInTheVoid — COMMENTED** [review]
@rustbot author

File: tests/rustdoc-json/reexport/same_name_different_types.rs (hunk 3 above)
Comment (aDotInTheVoid) [reply tests/rustdoc-json/reexport/same_name_different_types.rs:12]: Eg:

```rust
#![feature(no_core)]
#![no_core]

pub mod nested {
    // @set foo_struct = "$.index[*][?(@.docs == 'Foo the struct')].id"

    /// Foo the struct
    pub struct Foo {}

    // @set foo_fn = "$.index[*][?(@.docs == 'Foo the function')].id"

    #[allow(non_snake_case)]
    /// Foo the function
    pub fn Foo() {}
}

// @ismany "$.index[*][?(@.inner.name == 'Foo' && @.kind == 'import')].inner.id" $foo_fn $foo_struct
// @ismany "$.index[*][?(@.inner.name == 'Bar' && @.kind == 'import')].inner.id" $foo_fn $foo_struct

// @count "$.index[*][?(@.inner.name == 'Foo' && @.kind == 'import')]" 2
pub use nested::Foo;
// @count "$.index[*][?(@.inner.name == 'Bar' && @.kind == 'import')]" 2
pub use Foo as Bar;
```

**Comment by aDotInTheVoid** [comment]
Looking at the output (of `tests/rustdoc-json/reexport/same_name_different_types.rs`), for some reason it's duplicating ID's in the output:

```json
  "index": {
    "0:0:1588": {
      "crate_id": 0,
      "docs": null,
      "id": "0:0:1588",
      "inner": {
        "is_crate": true,
        "is_stripped": false,
        "items": [
          "0:1:1582",
          "0:4-0:2:1584",
          "0:4-0:3:1584",
          "0:4-0:2:1584",
          "0:4-0:3:1584",
          "0:5-0:2:1584",
          "0:5-0:3:1584",
          "0:5-0:2:1584",
          "0:5-0:3:1584"
        ]
      },
      "kind": "module",
      "name": "same_name_different_types"
    },
```

I'm not really sure whats causing this, but idealy it wouldn't happen, although I'd be willing to merge as is, as long as an issue gets created to follow up.

(Also, jsondoclint should probably catch this)

**Comment by GuillaumeGomez** [comment]
I think it's better to fix it in another PR since this one is already quite big. We can fix it easily by having a `HashSet` but I'd like to investigate why it's needed in the first place.

**Comment by GuillaumeGomez** [comment]
And also: updated.
