### PR TITLE
Fix windows `Socket::connect_timeout` overflow

### LINKED ISSUE #112405: TcpStream::connect_timeout with Duration::MAX never succeeds on Windows
Hello! :wave: 

I tried this code on Windows:

```rust
use std::net::{TcpStream, ToSocketAddrs};
use std::time::Duration;

fn main() {
    let address_result = "google.com:80".to_socket_addrs();
    let address = address_result.unwrap().next().unwrap();
    TcpStream::connect_timeout(&address, Duration::MAX).expect("Google is offline?!");
    println!("Never gets here on Windows (https://github.com/rust-lang/rust/issues/112405).");
}
```

I expected to see this happen: Success for an available address like `google.com:80` and blocking forever (or until TCP timeout) for `hostname.invalid:80` just like on Linux.

Instead, this happened: the call never succeeds, not even for `google.com:80` on Windows.

Related: https://github.com/hartwork/rust-for-it/pull/11/commits/5056e69241ae4a331da346601b3770f91da7a231

### Meta

`rustc --version --verbose`:
```console
# rustc --version --verbose
rustc 1.69.0 (84c898d65 2023-04-16)
binary: rustc
commit-hash: 84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc
commit-date: 2023-04-16
host: x86_64-pc-windows-msvc
release: 1.69.0
LLVM version: 15.0.7
```

### PR DESCRIPTION
**Pull request by eval-exec**
This PR want to close #112405

- [x] add unit test

### CODE REVIEW

File: library/std/src/sys/windows/net.rs [hunk 1]
```diff
@@ -159,7 +159,7 @@ impl Socket {
                 }
 
                 let mut timeout = c::timeval {
-                    tv_sec: timeout.as_secs() as c_long,
+                    tv_sec: cmp::min(timeout.as_secs(), libc::time_t::MAX as u64) as c_long,
```
Comment (ChrisDenton) [inline library/std/src/sys/windows/net.rs:162]: Hm, this should be using `c_long::MAX` to match `tv_sec`'s type.

Comment (eval-exec) [reply library/std/src/sys/windows/net.rs]: Updated

**Comment by ChrisDenton** [comment]
This looks good to me.

> add unit test

This is a bit more tricky but I think the easiest way would be to copy/paste [`connect_error`](https://github.com/rust-lang/rust/blob/4b71d79c972a605959b0a7c82b323fbd8562f070/library/std/src/net/tcp/tests.rs#L34) and then change it to use `connect_timeout(&next_test_ip4(), Duration::MAX)` instead of `connect`.

**Comment by eval-exec** [comment]
> This looks good to me.
> 
> > add unit test
> 
> This is a bit more tricky but I think the easiest way would be to copy/paste [`connect_error`](https://github.com/rust-lang/rust/blob/4b71d79c972a605959b0a7c82b323fbd8562f070/library/std/src/net/tcp/tests.rs#L34) and then change it to use `connect_timeout(&next_test_ip4(), Duration::MAX)` instead of `connect`.

But `connect_timeout(&next_test_ip4(), Duration::MAX)` need to very long time to wait it return an error, it is not suitable to run it on CI.

File: library/std/src/net/tcp/tests.rs [hunk 2]
```diff
@@ -46,6 +46,22 @@ fn connect_error() {
     }
 }
 
+#[test]
+fn connect_timeout_error() {
+    match TcpStream::connect_timeout(&"0.0.0.0:1".parse().unwrap(), Duration::MAX) {
```
Comment (ChrisDenton) [inline library/std/src/net/tcp/tests.rs:51]: Have you confirmed this test fails without the changes in `net.rs`?

Comment (hartwork) [reply library/std/src/net/tcp/tests.rs:51]: @eval-exec for an alternative idea of what a test could do:

1. bind some free port on localhost using `TcpListener::bind`, then
2. connect to that new port with `Duration::MAX` timeout.

Here's a draft in Rust:

```rust
use std::net::TcpListener;

let listener = TcpListener::bind("127.0.0.1:0").unwrap();  // :0 picks some free port
let port = listener.local_addr().unwrap().port();  // obtain the port it picked

[..]

[..] format!("127.0.0.1:{port}").as_str() [..]  // connect to that port
```

I have a real example of something very close at https://github.com/hartwork/rust-for-it/blob/4e51982c4465c3190d92a59747c5d2738baf9e07/src/network.rs#L160-L177 .

What do you think?

**Comment by thomcc** [comment]
Chris seems like he's reviewing this.

r? @ChrisDenton

File: library/std/src/net/tcp/tests.rs (hunk 2 above)
Comment (eval-exec) [reply library/std/src/net/tcp/tests.rs:51]: Thank you, I'm testing it on a win10 virtual machine.

Comment (hartwork) [reply library/std/src/net/tcp/tests.rs:51]: @eval-exec I checked the latest version: `0.0.0.0:1` will only work if you start a TCP listener on port 1. And port 1 only works if its unoccupied and you have privileges because ports up to 1024 are reserved. In a test context you'll probably want a dynamic free port as in my example above.

Comment (eval-exec) [reply library/std/src/net/tcp/tests.rs]: I'm confused, I try to connect to an unreachable address `8.8.8.8:9999`, but it didn't get timeout.

Comment (eval-exec) [reply library/std/src/net/tcp/tests.rs]: I want to follow the test here: https://github.com/bnoordhuis/libuv-chat/blob/master/deps/uv/test/test-tcp-connect-timeout.c

Comment (hartwork) [reply library/std/src/net/tcp/tests.rs]: @eval-exec given that the port is connectable now, the expected result is `Ok(..)` and so I would just assert for `.is_ok()`and all the matching can be dropped and you'll have only three lines for a test body. What do you think?

Comment (eval-exec) [reply library/std/src/net/tcp/tests.rs]: I execute `telnet 8.8.8.8 9999` but did get timeout, because I'm running clash with TUN mode.

after I stop clash TUN mode, `telnet 8.8.8.8 9999` will get timeout.

Comment (eval-exec) [reply library/std/src/net/tcp/tests.rs]: @hartwork Thank you, I think I didn't fully understand you, could you please provide the code?

Comment (hartwork) [reply library/std/src/net/tcp/tests.rs]: > @hartwork Thank you, I think I didn't fully understand you, could you please provide the code?

@eval-exec this is the adjustment that I had in mind:

```rust
use std::net::{TcpListener, TcpStream};
use std::time::Duration;

fn main() {
    let listener = TcpListener::bind("127.0.0.1:0").unwrap(); // :0 picks some free port
    let port = listener.local_addr().unwrap().port(); // obtain the port it picked
    assert!(
        TcpStream::connect_timeout(&format!("0.0.0.0:{port}").parse().unwrap(), Duration::MAX)
            .is_ok()
    );
}
```

Comment (hartwork) [reply library/std/src/net/tcp/tests.rs]: @eval-exec updated twice more (in case you only saw the version sent via notification e-mail)

Comment (eval-exec) [reply library/std/src/net/tcp/tests.rs]: It should be `format!("0.0.0.0:{port}"` or `format!("127.0.0.1:{port}"` for `connect_timeout`?

File: library/std/src/net/tcp/tests.rs [hunk 3]
```diff
@@ -46,6 +46,24 @@ fn connect_error() {
     }
 }
 
+// try to connect to an unreachable address
+#[test]
+fn connect_timeout_ok() {
+    let result =
+        TcpStream::connect_timeout(&format!("8.8.8.8:9999").parse().unwrap(), Duration::MAX);
+    assert!(result.is_ok());
```
Comment (hartwork) [inline library/std/src/net/tcp/tests.rs:54]: @eval-exec I'm nut sure what you are trying to do with this test^^. I'd expect it to never finish even with the fix. That doesn't seem right.

Comment (eval-exec) [reply library/std/src/net/tcp/tests.rs:54]: > @eval-exec I'm not sure what you are trying to do with this test^^. I'd expect it to never finish even with the fix. That doesn't seem right.

I'll remove this.

File: library/std/src/net/tcp/tests.rs (hunk 2 above)
Comment (eval-exec) [reply library/std/src/net/tcp/tests.rs]: I think I should `bind` and `accept` in another thread.

**Comment by eval-exec** [comment]
```bash
PS C:\Users\vagrant\x\rust> ./x test library/std --test-args connect_timeout_ok_bind --test-args --nocapture
x.ps1

Building bootstrap
    Finished dev [unoptimized] target(s) in 0.12s
Building stage0 library artifacts (x86_64-pc-windows-msvc)
    Finished release [optimized] target(s) in 0.43s
Testing stage0  {std} (x86_64-pc-windows-msvc)
   Compiling std v0.0.0 (C:\Users\vagrant\x\rust\library\std)
    Finished release [optimized] target(s) in 8.30s
     Running unittests src\lib.rs (build\x86_64-pc-windows-msvc\stage0-std\x86_64-pc-windows-msvc\release\deps\std-8ebecd817f1c4b19.exe)

running 1 tests
.

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 908 filtered out; finished in 3.05ms

     Running tests\create_dir_all_bare.rs (build\x86_64-pc-windows-msvc\stage0-std\x86_64-pc-windows-msvc\release\deps\create_dir_all_bare-7d5a77121cffe687.exe)

running 0 tests


test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 1 filtered out; finished in 94.60µs

     Running tests\env.rs (build\x86_64-pc-windows-msvc\stage0-std\x86_64-pc-windows-msvc\release\deps\env-739ca63914aea662.exe)

running 0 tests


test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 7 filtered out; finished in 86.30µs

     Running tests\run-time-detect.rs (build\x86_64-pc-windows-msvc\stage0-std\x86_64-pc-windows-msvc\release\deps\run_time_detect-6db7104cef1ef2fb.exe)

running 0 tests


test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 1 filtered out; finished in 255.00µs

     Running tests\thread.rs (build\x86_64-pc-windows-msvc\stage0-std\x86_64-pc-windows-msvc\release\deps\thread-3ad1d7d9f39a63f5.exe)

running 0 tests


test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 1 filtered out; finished in 157.40µs

     Running benches/lib.rs (build\x86_64-pc-windows-msvc\stage0-std\x86_64-pc-windows-msvc\release\deps\stdbenches-511911d8b738dca6.exe)

running 0 tests


test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 12 filtered out; finished in 129.00µs

   Doc-tests std

running 0 tests


test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 1016 filtered out; finished in 518.90ms

        finished in 10.433 seconds
Build completed successfully in 0:00:14
```

The unit test passed on Windows platform. @hartwork

File: library/std/src/net/tcp/tests.rs (hunk 2 above)
Comment (hartwork) [reply library/std/src/net/tcp/tests.rs]: > I think I should `bind` and `accept` in another thread:

@eval-exec that's not necessary, see https://github.com/hartwork/rust-for-it/blob/4e51982c4465c3190d92a59747c5d2738baf9e07/src/network.rs#L160-L177 .

**Comment by eval-exec** [comment]
This unit test passed on `x86_64-pc-windows-msvc` @hartwork 

I think this PR is ready for review.

#rustbot ready

image

**Comment by ChrisDenton** [comment]
Sorry for the delay! This fell off my radar for a bit.

My concern with the test is that it may succeed straight away without blocking. So it'll work with or without the fix in this PR. IIRC, my original thought for a test is something like:

```rust
#[test]
fn connect_timeout_error() {
    let result = TcpStream::connect_timeout(&next_test_ip4(), Duration::MAX);
    assert!(!matches!(result, Err(e) if e.kind() == ErrorKind::TimedOut));
}
```

`connect_timeout` will be unable to connect but that's ok because we make sure it doesn't fail with `TimeOut`.

**Comment by eval-exec** [comment]
> Sorry for the delay! This fell off my radar for a bit.
> 
> My concern with the test is that it may succeed straight away without blocking. So it'll work with or without the fix in this PR. IIRC, my original thought for a test is something like:
> 
> ```rust
> #[test]
> fn connect_timeout_error() {
>     let result = TcpStream::connect_timeout(&next_test_ip4(), Duration::MAX);
>     assert!(!matches!(result, Err(e) if e.kind() == ErrorKind::TimedOut));
> }
> ```
> 
> `connect_timeout` will be unable to connect but that's ok because we make sure it doesn't fail with `TimeOut`.

How about this: @hartwork 
```rust

#[test]
fn connect_timeout_error() {
    let socket_addr = next_test_ip4();
    let result = TcpStream::connect_timeout(&socket_addr, Duration::MAX);
    assert!(!matches!(result, Err(e) if e.kind() == ErrorKind::TimedOut));

    let _listener = TcpListener::bind(&socket_addr).unwrap();
    assert!(TcpStream::connect_timeout(&socket_addr, Duration::MAX).is_ok());
}

```

**Comment by hartwork** [comment]
@ChrisDenton @eval-exec I'm not sure I understand the idea. Bug #112405 is that an _available_ target will produce infinite blocking. To proof that the bug is gone it needs a robustly available target and then the test finishing at all already means that the bug is gone. Any other tests may be nice but also out of context. Please help me understand your idea.

**Comment by ChrisDenton** [comment]
If the test alone finishes with or without the fix in this PR then it's not testing what we think it's testing. To be robust it must fail if this PR didn't exist.

The problem for us is [this branch](https://github.com/rust-lang/rust/blob/fca9e6e706d1b611c81c97ccdff8265f5f1ee638/library/std/src/sys/windows/net.rs#L145) which attempts a non-blocking connect. If that succeeds right away then the code we want to test is never run.

**Comment by hartwork** [comment]
> If the test alone finishes with or without the fix in this PR then it's not testing what we think it's testing. To be robust it must fail if this PR didn't exist.

@ChrisDenton agree 100%.

> The problem for us is [this branch](https://github.com/rust-lang/rust/blob/fca9e6e706d1b611c81c97ccdff8265f5f1ee638/library/std/src/sys/windows/net.rs#L145) which attempts a non-blocking connect. If that succeeds right away then the code we want to test is never run.

Has the `connect_timeout` call been observed anywhere to not block with `Duration::MAX` and succeed right away? It's not something I have seen anywhere just once. Do these lines have test coverage or could it potentially be effectively dead code that always fails? We could force getting past that branch but it will be a complex test (I'm thinking two threats and a channel to communicate the port number, that kind of work).

**Comment by ChrisDenton** [comment]
Have you run this test? I just did so on my machine and it passes regardless of the changes in this PR.

Robustly testing success is indeed complex, which is why I suggested testing a failure case instead.

**Comment by hartwork** [comment]
> Have you run this test? I just did so on my machine and it passes regardless of the changes in this PR.

@ChrisDenton this needs Windows to fail and I have Linux everywhere but in GitHub CI.
Did it succeed for you without a fix on Windows?

> Robustly testing success is indeed complex, which is why I suggested testing a failure case instead.

Please help me understand how a fail-based test case says anything about the bugfix, I don't see it.

**Comment by ChrisDenton** [comment]
Yes I tested on Windows.

The failure mode this PR resolves is `Duration::MAX` being interpreted as a negative integer (I.e. less than zero time). This causes an immediate return with a TimeOut error.

With the bug fixed `Duration::MAX` will be correctly interpreted and a TimeOut error will not be returned. Some other error will be but that is to be expected.

**Comment by hartwork** [comment]
> The failure mode this PR resolves is `Duration::MAX` being interpreted as a negative integer (I.e. less than zero time).

@ChrisDenton yes.

> This causes an immediate return with a TimeOut error.

Cannot confirm, it caused infinite blocking for me as documented at #112405.


> With the bug fixed `Duration::MAX` will be correctly interpreted and a TimeOut error will not be returned. Some other error will be but that is to be expected.

Cannot confirm, no error should be returned but success since this is about available targets.

**Comment by ChrisDenton** [comment]
The failure condition in your issue was "Instead, this happened: the call never succeeds, not even for google.com:80 on Windows."

That is not infinite blocking.

**Comment by hartwork** [comment]
> The failure condition in your issue was "Instead, this happened: the call never succeeds, not even for google.com:80 on Windows."
> 
> That is not infinite blocking.

@ChrisDenton maybe I should have put it more clearly: by "never succeeds" I meant that it should have returned success quickly for google.com:80 but instead it blocked forever and hence never finishes to return with due success. Given your spot-on early analysis at https://github.com/rust-lang/rust/issues/112405#issuecomment-1581983954 I do not understand how we have different understanding now. I'd be happy to learn what I a missing now. Are there two bugs here instead of a single one?

**Comment by hartwork** [comment]
@ChrisDenton PS: The CI at https://github.com/hartwork/rust-for-it/actions/runs/5204380736/jobs/9388510541 was cancelled by GitHub after near-exact 6 hours runtime due to that call while google.com:80 was available.

**Comment by eval-exec** [comment]
> @ChrisDenton PS: The CI at https://github.com/hartwork/rust-for-it/actions/runs/5204380736/jobs/9388510541 was cancelled by GitHub after near-exact 6 hours runtime due to that call while google.com:80 was available.

What's the related code of this canceled CI action?

**Comment by hartwork** [comment]
> > @ChrisDenton PS: The CI at https://github.com/hartwork/rust-for-it/actions/runs/5204380736/jobs/9388510541 was cancelled by GitHub after near-exact 6 hours runtime due to that call while google.com:80 was available.
> 
> What's the related code of this canceled CI action?

@eval-exec that would effectively be https://github.com/hartwork/rust-for-it/tree/4c816e51eb8134cef32571400f5583e3f75cec54 or:

```bash
git clone https://github.com/hartwork/rust-for-it
git checkout 4c816e51eb8134cef32571400f5583e3f75cec54
```

**Comment by eval-exec** [comment]
# connect to a reachable address:
```rust
use std::net::{TcpStream, ToSocketAddrs};
use std::time::Duration;

fn main() {
    let address_result = "8.8.8.8:80".to_socket_addrs();
    let address = address_result.unwrap().next().unwrap();
    TcpStream::connect_timeout(&address, Duration::MAX).expect("connect_timeout");
    println!("main fn returned");
}
```
- On Linux platform, `rustc 1.70.0`, this program returned imediately, and no error.
- On Windows platform, `rustc 1.70.0`, this program panic at an error imediately: `thread 'main' panicked at 'connect_timeout: Error { kind: TimedOut, message: "connection timed out" }', src\main.rs:7:57`

# connect to an unreachable address:
```rust
use std::net::{TcpStream, ToSocketAddrs};
use std::time::Duration;

fn main() {
    let address_result = "8.8.8.8:9999".to_socket_addrs();
    let address = address_result.unwrap().next().unwrap();
    TcpStream::connect_timeout(&address, Duration::MAX).expect("connect_timeout");
    println!("main fn returned");
}
```
- On linux platform, `rustc 1.70.0`, this program running `2minutes and 10second`, and finaly got `thread 'main' panicked at 'connect_timeout: Os { code: 110, kind: TimedOut, message: "Connection timed out" }', src/main.rs:7:57`
- On Windows platform, `rustc 1.70.0`, this program panic at an error imediately: `thread 'main' panicked at 'connect_timeout: Error { kind: TimedOut, message: "connection timed out" }', src\main.rs:7:57`

**Comment by eval-exec** [comment]
Because the [GFW](https://en.wikipedia.org/wiki/Great_Firewall),  I cannot connect to `8.8.8.8 80`, but I can connect to `1.1.1.1 80`, so I redo the above test:

# connect to a reachable address:
```rust
use std::net::{TcpStream, ToSocketAddrs};
use std::time::Duration;

fn main() {
    let address_result = "1.1.1.1:80".to_socket_addrs();
    let address = address_result.unwrap().next().unwrap();
    TcpStream::connect_timeout(&address, Duration::MAX).expect("connect_timeout");
    println!("main fn returned");
}
```
- On Linux platform, `rustc 1.70.0`, this program returned imediately, and no error.
- On Windows platform, `rustc 1.70.0`, this program panic at an error imediately: `thread 'main' panicked at 'connect_timeout: Error { kind: TimedOut, message: "connection timed out" }', src\main.rs:7:57`
- On Windows platfomr, `with this PR's fix`, and I run this program in a unit test, this program returned imediately, and no error

# connect to an unreachable address:
```rust
use std::net::{TcpStream, ToSocketAddrs};
use std::time::Duration;

fn main() {
    let address_result = "1.1.1.1:9999".to_socket_addrs();
    let address = address_result.unwrap().next().unwrap();
    TcpStream::connect_timeout(&address, Duration::MAX).expect("connect_timeout");
    println!("main fn returned");
}
```
- On linux platform, `rustc 1.70.0`, this program running `2minutes and 8second`, and finaly got `thread 'main' panicked at 'connect_timeout: Os { code: 110, kind: TimedOut, message: "Connection timed out" }', src/main.rs:7:57`
- On Windows platform, `rustc 1.70.0`, this program panic at an error imediately: `thread 'main' panicked at 'connect_timeout: Error { kind: TimedOut, message: "connection timed out" }', src\main.rs:7:57`
- On Windows platfomr, `with this PR's fix`, and I run this program in a unit test, this program paniced after `21.04 seconds`:
```
thread 'net::tcp::tests::connect_timeout_example' panicked at 'connect_timeout: Os { code: 10060, kind: TimedOut, message: "A connection attempt failed because the connected p
arty did not properly respond after a period of time, or established connection failed because connected host has failed to respond." }', library\std\src\net\tcp\tests.rs:15:88
```

**Comment by eval-exec** [comment]
# connect to a reachable address:
```rust
use std::net::{TcpStream, ToSocketAddrs};
use std::time::Duration;

fn main() {
    let address_result = "1.1.1.1:80".to_socket_addrs();
    let address = address_result.unwrap().next().unwrap();
    TcpStream::connect_timeout(&address, Duration::MAX).expect("connect_timeout");
    println!("main fn returned");
}
```
- On Linux platform, `rustc 1.70.0`, this program returned imediately, and no error.
- On Windows platform, `rustc 1.70.0`, this program panic at an error imediately: `thread 'main' panicked at 'connect_timeout: Error { kind: TimedOut, message: "connection timed out" }', src\main.rs:7:57`
- On Windows platfomr, `with this PR's fix`, and I run this program in a unit test, this program returned imediately, and no error

# connect to an unreachable address:
```rust
use std::net::{TcpStream, ToSocketAddrs};
use std::time::Duration;

fn main() {
    let address_result = "1.1.1.1:9999".to_socket_addrs();
    let address = address_result.unwrap().next().unwrap();
    TcpStream::connect_timeout(&address, Duration::MAX).expect("connect_timeout");
    println!("main fn returned");
}
```
- On linux platform, `rustc 1.70.0`, this program running `2minutes and 8second`, and finaly got `thread 'main' panicked at 'connect_timeout: Os { code: 110, kind: TimedOut, message: "Connection timed out" }', src/main.rs:7:57`
- On Windows platform, `rustc 1.70.0`, this program panic at an error imediately: `thread 'main' panicked at 'connect_timeout: Error { kind: TimedOut, message: "connection timed out" }', src\main.rs:7:57`
- On Windows platfomr, `with this PR's fix`, and I run this program in a unit test, this program paniced after `21.04 seconds`:
```
thread 'net::tcp::tests::connect_timeout_example' panicked at 'connect_timeout: Os { code: 10060, kind: TimedOut, message: "A connection attempt failed because the connected p
arty did not properly respond after a period of time, or established connection failed because connected host has failed to respond." }', library\std\src\net\tcp\tests.rs:15:88
```

**Comment by eval-exec** [comment]
So, I think I can add a unit test: connect to an unreachable address like `1.1.1.1:9999`. `assert` `connect_timeout(`1.1.1.1:9999`, Duration::MAX)` will get a `TimedOut` error, and assert the action should cost at least 20 seconds.
```rust

#[test]
fn connect_timeout_to_unreachable_address() {
    let now = Instant::now();
    let result =
        TcpStream::connect_timeout(&format!("1.1.1.1:9999").parse().unwrap(), Duration::MAX);
    
    assert!(matches!(result, ErrorKind::TimedOut));
    
    assert!(now.elapsed() < Duration::from_secs(20));
}
```

What do you think? @hartwork @ChrisDenton

**Comment by ChrisDenton** [comment]
@hartwork the reason your CI ran indefinitely is because you have [an infinite loop](https://github.com/hartwork/rust-for-it/blob/4c816e51eb8134cef32571400f5583e3f75cec54/src/network.rs#LL53C5-L53C11). if running only the code in the issue, it [errors immediately](https://github.com/ChrisDenton/connect_timeout/actions/runs/5302368320/jobs/9597247893).

File: library/std/src/net/tcp/tests.rs [hunk 4]
```diff
@@ -46,6 +46,37 @@ fn connect_error() {
     }
 }
 
+#[test]
+fn connect_timeout_to_unreachable_address() {
```
Comment (eval-exec) [inline library/std/src/net/tcp/tests.rs:50]: I tested, this unit test will cost at 2 minutes and 8 seconds on Linux platform, and cost 20 seconds on Windows.

**Comment by hartwork** [comment]
> @hartwork the reason your CI ran indefinitely is because you have [an infinite loop](https://github.com/hartwork/rust-for-it/blob/4c816e51eb8134cef32571400f5583e3f75cec54/src/network.rs#LL53C5-L53C11). if running only the code in the issue, it [errors immediately](https://github.com/ChrisDenton/connect_timeout/actions/runs/5302368320/jobs/9597247893).

@ChrisDenton thanks for clearing this up, you're 100% right, I was able to confirm your results in GitHub Actions now. Sorry :pray:

File: library/std/src/net/tcp/tests.rs (hunk 4 above)
Comment (ChrisDenton) [reply library/std/src/net/tcp/tests.rs:50]: I think we only need one test here. We only need to focus on testing the problematic code path in one way. 2 minutes and 8 secs is a long time for a single unit test so I'd prefer if we just used `connect_timeout_error` test.

File: library/std/src/net/tcp/tests.rs [hunk 5]
```diff
@@ -46,6 +46,37 @@ fn connect_error() {
...
+    let now = Instant::now();
+    match TcpStream::connect_timeout(&format!("1.1.1.1:9999").parse().unwrap(), Duration::MAX) {
+        Ok(..) => panic!("connected to an unreachable address, this is impossible"),
+        Err(e) => assert_eq!(e.kind(), ErrorKind::TimedOut),
+    }
+
+    assert!(now.elapsed() > Duration::from_secs(20));
+}
+
+#[test]
```
Comment (ChrisDenton) [inline library/std/src/net/tcp/tests.rs:60]:
```suggestion
#[test]
#[cfg_attr(target_env = "sgx", ignore)] // FIXME: https://github.com/fortanix/rust-sgx/issues/31
```

Unfortunately the SGX platform does not currently support `connect_timeout`.

File: library/std/src/net/tcp/tests.rs (hunk 4 above)
Comment (eval-exec) [reply library/std/src/net/tcp/tests.rs:50]: Ok, I think 2 minutes and 8 seconds is a long time too.

**Review by ChrisDenton — APPROVED** [review]
This looks great to me, thanks! Sorry testing end up being so involved.

**Comment by eval-exec** [comment]
Thank you.

File: library/std/src/net/tcp/tests.rs [hunk 6]
```diff
@@ -46,6 +46,17 @@ fn connect_error() {
     }
 }
 
+#[test]
+#[cfg_attr(target_env = "sgx", ignore)] // FIXME: https://github.com/fortanix/rust-sgx/issues/31
+fn connect_timeout_error() {
+    let socket_addr = next_test_ip4();
+    let result = TcpStream::connect_timeout(&socket_addr, Duration::MAX);
+    assert!(!matches!(result, Err(e) if e.kind() == ErrorKind::TimedOut));
```
Comment (RalfJung) [inline library/std/src/net/tcp/tests.rs:54]: This is a strange test. It says to only timeout after billions of years, yet apparently it expects the OS to timeout immediately. What is going on here? And why is there no comment explaining this?^^

Context: #156385

*[View changes since the review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/rust/112464/0c2c243342ec2a2427f0624fac5ac59f0ee6fbcd..a0c757a13f5a0090f8cb6e1a7ffba6b94dfc2fbf)*

Comment (RalfJung) [reply library/std/src/net/tcp/tests.rs:54]: Oh, I missed a `!` :)

Comment (eval-exec) [reply library/std/src/net/tcp/tests.rs:54]: Hello, I reviewed your PR. Is there some tasks we can do next for further steps?

Comment (RalfJung) [reply library/std/src/net/tcp/tests.rs:54]: If the comment there makes sense then I think that's all, thanks :)
