### PR TITLE
Remove `[T]::array_chunks(_mut)`

### LINKED ISSUE #74985: Tracking Issue for slice::array_chunks
The feature gate for the issue is `#![feature(array_chunks)]`.

Also tracks `as_(r)chunks(_mut)` in `#![feature(slice_as_chunks)]` -- these were FCPed starting at https://github.com/rust-lang/rust/issues/74985#issuecomment-2769963395 below.

### About tracking issues

Tracking issues are used to record the overall progress of implementation.
They are also uses as hubs connecting to other relevant issues, e.g., bugs or open design questions.
A tracking issue is however *not* meant for large scale discussion, questions, or bug reports about a feature.
Instead, open a dedicated issue for the specific matter and add the relevant feature gate label.

### Steps

- [x] ~~Restrict `N` to values greater than 0 at compile time instead of using a runtime panic.~~ https://github.com/rust-lang/rust/pull/99471
- [x] Support calls where `N == 0` is unreachable due to conditionals https://github.com/rust-lang/rust/issues/74985#issuecomment-2087722186
  - It was decided that a runtime panic is appropriate: https://github.com/rust-lang/rust/issues/74985#issuecomment-2751861090 
- [x] Adjust documentation ([see instructions on rustc-dev-guide][doc-guide])
- [ ] Stabilization PR ([see instructions on rustc-dev-guide][stabilization-guide])
  - [x] slice_as_chunks: #139656
  - [ ] array_chunks

[stabilization-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#stabilization-pr
[doc-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#documentation-prs

### Unresolved Questions

- [ ] Iterator vs slices, https://github.com/rust-lang/rust/issues/76354

### Implementation history

- implemented in #74373
- mut version in #75021
- `as_chunks{_mut}` in #76635
- `as_rchunks{_mut}` and unchecked versions in #78818
- const `as_(r)chunk` in #111453
- https://github.com/rust-lang/rust/pull/139656

### LINKED ISSUE #76354: Does `[T]::array_chunks` really need to be an iterator?
After bit after reviewing the code in https://github.com/rust-lang/rust/pull/75021 I had a thought: if this iterator is mostly just a wrapper on a slice iterator, does it even need to be an iterator at all?

The original `.chunks()` call does (as does `.windows`), because the slices it wants to return don't exist anywhere.

But the arrays returned by `array_chunks` are inline in the original slice allocation, so the API could just return the slice that the method is already creating, instead of hiding it in an iterator.

To be more concrete:
```rust
impl [T] { 
    pub fn array_chunks<const N: usize>(&self) -> (&[[T;N]], &[T]);
    pub fn array_chunks_mut<const N: usize>(&mut self) -> (&mut [[T;N]], &mut [T]);
}
```

Not only would this be more general (the `ArrayChunks` type doesn't currently expose the slice), but I think it would make it less likely that people would forget to correctly handle the `.remainder()`.  (While still being easy to ignore it with `.0` if they insist.)  And returning tuples like this has precedent with `split_*` and `align_to` and such.  (Many other names could work too, like `.as_chunks(_mut)`.)

Also, such a method would be nice to have as the inverse of a hypothetical `flatten: &[[T; N]] -> &[T]`.  (EDIT: No longer as hypothetical, #95629.)

`array_chunks` tracking issue https://github.com/rust-lang/rust/issues/74985

### PR DESCRIPTION
**Pull request by scottmcm**
Since libs-api is proposing as much in https://github.com/rust-lang/rust/issues/74985#issuecomment-3024465102

Closes rust-lang/rust#74985
Closes rust-lang/rust#76354

try-job: dist-various-1
try-job: dist-various-2

### CODE REVIEW

File: library/alloc/src/string.rs [hunk 1]
```diff
@@ -787,12 +787,12 @@ impl String {
...
             return Err(FromUtf16Error(()));
-        }
+        };
         match (cfg!(target_endian = "little"), unsafe { v.align_to::<u16>() }) {
             (true, ([], v, [])) => Self::from_utf16(v),
-            _ => char::decode_utf16(v.array_chunks::<2>().copied().map(u16::from_le_bytes))
+            _ => char::decode_utf16(chunks.iter().copied().map(u16::from_le_bytes))
                 .collect::<Result<_, _>>()
                 .map_err(|_| FromUtf16Error(())),
         }
```
Comment (scottmcm) [inline library/alloc/src/string.rs:798]: Hooray for `let`-`else` and slice patterns meaning this can write "the chunks with no tail", rather than needing to have an explicit `% 2`.

**Comment by Amanieu** [comment]
From https://github.com/rust-lang/rust/issues/74985#issuecomment-3024465102:

> We discussed this again the [@rust-lang/libs-api](https://github.com/orgs/rust-lang/teams/libs-api) meeting and concluded that there is little use for an `array_chunks` iterator when we already have `as_chunks`. As such we would like to remove this unstable API.

@rfcbot merge

**Comment by jhpratt** [comment]
Let me know when CI is passing an I can take a look.

File: compiler/rustc_codegen_cranelift/patches/0027-sysroot_tests-128bit-atomic-operations.patch [hunk 2]
```diff
@@ -19,7 +19,7 @@ index 1e336bf..35e6f54 100644
 -#![cfg_attr(target_has_atomic = "128", feature(integer_atomics))]
  #![cfg_attr(test, feature(cfg_select))]
  #![feature(alloc_layout_extra)]
- #![feature(array_chunks)]
+ #![feature(array_ptr_get)]
```
Comment (scottmcm) [inline compiler/rustc_codegen_cranelift/patches/0027-sysroot_tests-128bit-atomic-operations.patch:22]: Achievement Acquired: first CI failure from a `.patch` file.

**Comment by scottmcm** [comment]
@jhpratt This is passing CI now, if you want to take a look, but no rush since it can't land in less than 10 days anyway.

**Comment by jhpratt** [comment]
LGTM! `r=me` if/when FCP is complete.

**Comment by scottmcm** [comment]
Friendly reminder for the p-FCP here (https://github.com/rust-lang/rust/pull/143289#issuecomment-3024925402), @joshtriplett @m-ou-se @BurntSushi

**Comment by matthiaskrgr** [comment]
@bors r-
https://github.com/rust-lang/rust/pull/144546#issuecomment-3124779406

**Comment by scottmcm** [comment]
Trying the weird platforms that failed in the rollup...
@bors try

**Comment by scottmcm** [comment]
Well the job that failed in the rollup passed, so let's give it another shot
@bors r=jhpratt rollup=maybe (failed before in platform-specific library code)
