### PR TITLE
ast_validation: forbid "nonstandard" literal patterns

### LINKED ISSUE #43250: ICE: "encountered errors lowering pattern: [ConstEval(ConstEvalErr { ... kind: NonConstPath })]"
Following (wrong) code gives an error on beta 1.19 and stable 1.18, but ICEs on current nightly:

```rust
fn main() {
	let mut y;
	macro_rules! m {
		($a:expr) => {
			let $a = 0;
		}
	}
	m!(y);
}
```

The error (expected behaviour):
```
error: expected pattern, found `y`
```

The ICE message (new behaviour):
```
internal compiler error: /checkout/src/librustc_const_eval/pattern.rs:282: encountered errors lowering pattern: [ConstEval(ConstEvalErr { span: src/main.rs:8:5: 8:6, kind: NonConstPath })]
```

Nightly (soon beta) regression. Bisected using rust-bisect to #42964 (7acce3724d6ba5cb84d6eef6d6847f8573a1fe5a).

### PR DESCRIPTION
**Pull request by arielb1**
Since #42886, macros can create "nonstandard" PatKind::Lit patterns,
that contain path expressions instead of the usual literal expr. These
can cause trouble, including ICEs.

We *could* map these nonstandard patterns to PatKind::Path patterns
during HIR lowering, but that would be much effort for little gain, and
I think is too risky for beta. So let's just forbid them during AST
validation.

Fixes #43250.

beta-nominating because regression.
r? @eddyb

### CODE REVIEW

File: src/test/compile-fail/issue-43250.rs [hunk 1]
```diff
@@ -0,0 +1,23 @@
...
+// option. This file may not be copied, modified, or distributed
+// except according to those terms.
+
+fn main() {
+    let mut y;
+    const C: u32 = 0;
+    macro_rules! m {
+	($a:expr) => {
+	    let $a = 0;
+	}
```
Comment (kennytm) [inline src/test/compile-fail/issue-43250.rs]: 🙅 Tabs found by tidy.

```
[00:04:00] tidy error: /checkout/src/test/compile-fail/issue-43250.rs:15: tab character
[00:04:00] tidy error: /checkout/src/test/compile-fail/issue-43250.rs:16: tab character
[00:04:00] tidy error: /checkout/src/test/compile-fail/issue-43250.rs:17: tab character
[00:04:00] tidy error: /checkout/src/librustc_passes/ast_validation.rs:106: tab character
[00:04:00] tidy error: /checkout/src/librustc_passes/ast_validation.rs:107: tab character
[00:04:00] tidy error: /checkout/src/librustc_passes/ast_validation.rs:108: tab character
[00:04:00] some tidy checks failed
```

File: src/librustc_passes/ast_validation.rs [hunk 2]
```diff
@@ -94,10 +94,25 @@ impl<'a> AstValidator<'a> {
...
+    ///
+    /// FIXME: do we want to allow expr -> pattern conversion to create path expressions?
+    /// That means making this work:
+    ///
+    /// ```rust,ignore (FIXME)
+    ///     struct S;
+    ///     macro_rules! m {
+    ///	        ($a:expr) => {
+    ///	            let $a = S;
+    ///	        }
```
Comment (kennytm) [inline src/librustc_passes/ast_validation.rs]: Tabs also found in the 3 lines above.

File: src/test/compile-fail/issue-43250.rs (hunk 1 above)
Comment (eddyb) [inline src/test/compile-fail/issue-43250.rs]: I guess the original testcase was tainted :(.

**Comment by arielb1** [comment]
No more tabs!

@bors r=eddyb

**Comment by nikomatsakis** [comment]
Accepted for beta backport. Small patch, regression.

cc @rust-lang/compiler
