### PR TITLE
compiletest: Don't panic on unknown JSON-like output lines

### LINKED ISSUE #126373: compiletest: Printing process output panics if the output contains unknown JSON-like text
When a process unexpectedly fails/succeeds, compiletest will often print a full dump of its stdout and stderr for diagnostic purposes.

When this happens, `ProcRes::print_info` calls into `extract_rendered`, which has special handling for lines starting with `{`. It tries to parse the line as JSON in one of a few known compiler-specific formats, in order to replace it with a more human-friendly message.

If the line doesn't match any of those formats (or isn't valid JSON), the extractor code will panic, instead of just printing the line as-is. This is awkward in cases where we actually wanted to print the line as-is anyway, because now the error messages are less helpful.

@rustbot label +A-compiletest

### PR DESCRIPTION
**Pull request by Zalathar**
The `json::extract_rendered` function is called for both compiler output and non-compiler output, so it's inappropriate to panic just because a line starting with `{` didn't contain a compiler output message.

It is called from two places: when checking the output of a `ui` test process, and when printing the output of an arbitrary non-passing `ProcRes`. So unfortunately there's currently no easy way to know for sure whether it is seeing compiler output or not. Fortunately, neither call site appears to be relying on this panic; it's just an overzealous internal check.

Fixes #126373.

### CODE REVIEW

**Review by jieyouxu — APPROVED** [review]
The existing code here is *extremely* hacky and fragile, but not panicking here seems okay to me.

File: src/tools/compiletest/src/json.rs [hunk 1]
```diff
@@ -1,5 +1,4 @@
 //! These structs are a subset of the ones found in `rustc_errors::json`.
-//! They are only used for deserialization of JSON output provided by libtest.
```
Comment (jieyouxu) [inline src/tools/compiletest/src/json.rs:2]: Remark: you are right, this is wrong; it's not libtest, it's not just compiler, it's also rustdoc and maybe even more.

**Comment by jieyouxu** [comment]
Thanks for the fix!

r? jieyouxu
@bors r+ rollup
