### PR TITLE
Check for live drops in constants after drop elaboration

### LINKED ISSUE #66753: Can't implement a const `Option::unwrap` because of "destructors cannot be evaluated at compile-time" error.
It's not possible to implement `Option::unwrap` as a const fn like:
https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=8ad0c1cdd371ca0488fab9d872bd6ffe
```rust
#![feature(const_fn)]
#![feature(const_if_match)]
#![feature(const_panic)]

const fn unwrap<T>(opt:Option<T>)->T{
    match opt {
        Some(x)=>x,
        None=>panic!("Trying to unwrap a None"),
    }
}
```

Because the function triggers this error:
```
error[E0493]: destructors cannot be evaluated at compile-time
 --> src/lib.rs:5:20
  |
5 | const fn unwrap<T>(opt:Option<T>)->T{
  |                    ^^^ constant functions cannot evaluate destructors

error: aborting due to previous error
```

### PR DESCRIPTION
**Pull request by ecstatic-morse**
Resolves #66753.

This PR splits the MIR "optimization" pass series in two and introduces a query–`mir_drops_elaborated_and_const_checked`–that holds the result of the `post_borrowck_cleanup` analyses and checks for live drops. This query is invoked in `rustc_interface` for all items requiring const-checking, which means we now do `post_borrowck_cleanup` for items even if they are unused in the crate.

As a result, we are now more precise about when drops are live. This is because drop elaboration can e.g. eliminate drops of a local when all its fields are moved from. This does not mean we are doing value-based analysis on move paths, however; Storing a `Some(CustomDropImpl)` into a field of a local will still set the qualifs for that entire local.

r? @oli-obk

### CODE REVIEW

**Comment by ecstatic-morse** [comment]
Here's an interesting case:
https://github.com/rust-lang/rust/blob/e5f35df2c6944b843b08369c4b2ff3bdb0beb2d2/src/test/ui/check-static-values-constraints.rs#L56-L61

MIR before const-checking
```
// MIR for `STATIC8` after SimplifyCfg-initial

static STATIC8: SafeStruct = {
    let mut _0: SafeStruct;              // return place in scope 0 at src/test/ui/check-static-values-constraints.rs:59:17: 59:27
    let mut _1: SafeEnum;                // in scope 0 at src/test/ui/check-static-values-constraints.rs:59:49: 59:67
    let mut _2: SafeStruct;              // in scope 0 at src/test/ui/check-static-values-constraints.rs:60:43: 61:81
    let mut _3: SafeEnum;                // in scope 0 at src/test/ui/check-static-values-constraints.rs:60:62: 60:80
    let mut _4: SafeEnum;                // in scope 0 at src/test/ui/check-static-values-constraints.rs:61:62: 61:80

    bb0: {
        StorageLive(_1);                 // scope 0 at src/test/ui/check-static-values-constraints.rs:59:49: 59:67
        _1 = SafeEnum::Variant1;         // scope 0 at src/test/ui/check-static-values-constraints.rs:59:49: 59:67
        StorageLive(_2);                 // scope 0 at src/test/ui/check-static-values-constraints.rs:60:43: 61:81
        StorageLive(_3);                 // scope 0 at src/test/ui/check-static-values-constraints.rs:60:62: 60:80
        _3 = SafeEnum::Variant1;         // scope 0 at src/test/ui/check-static-values-constraints.rs:60:62: 60:80
        StorageLive(_4);                 // scope 0 at src/test/ui/check-static-values-constraints.rs:61:62: 61:80
        _4 = SafeEnum::Variant1;         // scope 0 at src/test/ui/check-static-values-constraints.rs:61:62: 61:80
        _2 = SafeStruct { field1: move _3, field2: move _4 }; // scope 0 at src/test/ui/check-static-values-constraints.rs:60:43: 61:81
        _0 = SafeStruct { field1: move _1, field2: move (_2.1: SafeEnum) }; // scope 0 at src/test/ui/check-static-values-constraints.rs:59:30: 61:82
        drop(_2) -> [return: bb2, unwind: bb1]; // scope 0 at src/test/ui/check-static-values-constraints.rs:61:81: 61:82
    }

    bb1 (cleanup): {
        resume;                          // scope 0 at src/test/ui/check-static-values-constraints.rs:59:1: 61:83
    }

    bb2: {
        StorageDead(_2);                 // scope 0 at src/test/ui/check-static-values-constraints.rs:61:81: 61:82
        return;                          // scope 0 at src/test/ui/check-static-values-constraints.rs:59:1: 61:83
    }
}
```

After:
```
// MIR for `STATIC8` after SimplifyCfg-elaborate-drops

static STATIC8: SafeStruct = {
    let mut _0: SafeStruct;              // return place in scope 0 at src/test/ui/check-static-values-constraints.rs:59:17: 59:27
    let mut _1: SafeEnum;                // in scope 0 at src/test/ui/check-static-values-constraints.rs:59:49: 59:67
    let mut _2: SafeStruct;              // in scope 0 at src/test/ui/check-static-values-constraints.rs:60:43: 61:81
    let mut _3: SafeEnum;                // in scope 0 at src/test/ui/check-static-values-constraints.rs:60:62: 60:80
    let mut _4: SafeEnum;                // in scope 0 at src/test/ui/check-static-values-constraints.rs:61:62: 61:80

    bb0: {
        StorageLive(_1);                 // scope 0 at src/test/ui/check-static-values-constraints.rs:59:49: 59:67
        _1 = SafeEnum::Variant1;         // scope 0 at src/test/ui/check-static-values-constraints.rs:59:49: 59:67
        StorageLive(_2);                 // scope 0 at src/test/ui/check-static-values-constraints.rs:60:43: 61:81
        StorageLive(_3);                 // scope 0 at src/test/ui/check-static-values-constraints.rs:60:62: 60:80
        _3 = SafeEnum::Variant1;         // scope 0 at src/test/ui/check-static-values-constraints.rs:60:62: 60:80
        StorageLive(_4);                 // scope 0 at src/test/ui/check-static-values-constraints.rs:61:62: 61:80
        _4 = SafeEnum::Variant1;         // scope 0 at src/test/ui/check-static-values-constraints.rs:61:62: 61:80
        _2 = SafeStruct { field1: move _3, field2: move _4 }; // scope 0 at src/test/ui/check-static-values-constraints.rs:60:43: 61:81
        _0 = SafeStruct { field1: move _1, field2: move (_2.1: SafeEnum) }; // scope 0 at src/test/ui/check-static-values-constraints.rs:59:30: 61:82
        drop((_2.0: SafeEnum)) -> [return: bb2, unwind: bb1]; // scope 0 at src/test/ui/check-static-values-constraints.rs:61:81: 61:82
    }

    bb1 (cleanup): {
        resume;                          // scope 0 at src/test/ui/check-static-values-constraints.rs:59:1: 61:83
    }

    bb2: {
        StorageDead(_2);                 // scope 0 at src/test/ui/check-static-values-constraints.rs:61:81: 61:82
        return;                          // scope 0 at src/test/ui/check-static-values-constraints.rs:59:1: 61:83
    }
}
```

After drop elaboration, we drop only a single field of `SafeStruct`, which we don't realize is composed only of the non-`Drop` variants of `SafeEnum`s because value-based qualification is only used for whole locals. The solution is to still look at the qualifs of the base local when dropping a projection of that local, or alternatively start using move paths as the domain for the qualif dataflow analysis instead of locals.

**Comment by ecstatic-morse** [comment]
Okay, this is ready for review. I think we may want to put this behind a feature gate or at least wait until the next beta to merge. It also could use some new tests of the interaction between the value-based analysis on locals in `CheckLiveDrops` and the type-based analysis on move paths done during drop elaboration. Eventually I think we want to remember qualifs for individual move paths, but I don't think we need to wait.

r? @oli-obk

File: src/librustc_interface/passes.rs [hunk 1]
```diff
@@ -838,7 +838,21 @@ fn analysis(tcx: TyCtxt<'_>, cnum: CrateNum) -> Result<()> {
 
     sess.time("MIR_effect_checking", || {
         for def_id in tcx.body_owners() {
-            mir::transform::check_unsafety::check_unsafety(tcx, def_id.to_def_id())
+            mir::transform::check_unsafety::check_unsafety(tcx, def_id.to_def_id());
+
+            // FIXME: make `requires_const_checking` a query?
```
Comment (oli-obk) [inline src/librustc_interface/passes.rs:843]: a query may be overkill, but a method on `TyCtxt` seems good. I think we need the same logic elsewhere?

File: src/librustc_mir/transform/check_consts/post_drop_elaboration.rs [hunk 2]
```diff
@@ -78,10 +78,10 @@ impl Visitor<'tcx> for CheckLiveDrops<'mir, 'tcx> {
                     return;
                 }
 
-                let needs_drop = if let Some(local) = dropped_place.as_local() {
+                let needs_drop = if !dropped_place.is_indirect() {
```
Comment (oli-obk) [inline src/librustc_mir/transform/check_consts/post_drop_elaboration.rs:81]: the "not indirect" is a bit confusing. Isn't this basically `dropped_place.is_indirect() || {` and eliminating the `else` arm entirely?

File: src/librustc_mir/transform/check_consts/post_drop_elaboration.rs [hunk 3]
```diff
@@ -0,0 +1,108 @@
...
+
+        self.super_basic_block_data(bb, block);
+    }
+
+    fn visit_terminator(&mut self, terminator: &mir::Terminator<'tcx>, location: Location) {
+        trace!("visit_terminator: terminator={:?} location={:?}", terminator, location);
+
+        match &terminator.kind {
+            mir::TerminatorKind::Drop { location: dropped_place, .. }
+            | mir::TerminatorKind::DropAndReplace { location: dropped_place, .. } => {
```
Comment (oli-obk) [inline src/librustc_mir/transform/check_consts/post_drop_elaboration.rs:73]: can `DropAndReplace` still occur at this point?

File: src/librustc_mir/transform/check_consts/post_drop_elaboration.rs [hunk 4]
```diff
@@ -0,0 +1,108 @@
...
+                let mut err_span = terminator.source_info.span;
+
+                let dropped_ty = dropped_place.ty(self.body, self.tcx).ty;
+                if !NeedsDrop::in_any_value_of_ty(self.ccx, dropped_ty) {
+                    return;
+                }
+
+                let needs_drop = if let Some(local) = dropped_place.as_local() {
```
Comment (oli-obk) [inline src/librustc_mir/transform/check_consts/post_drop_elaboration.rs]: Instead of a `needs_drop` variable, you could also early return on the `self.qualifs.needs_drop` invocation.

File: src/librustc_mir/transform/check_consts/validation.rs [hunk 5]
```diff
@@ -600,7 +581,8 @@ impl Visitor<'tcx> for Validator<'mir, 'tcx> {
                 };
 
                 if needs_drop {
-                    self.check_op_spanned(ops::LiveDrop, err_span);
+                    // self.check_op_spanned(ops::LiveDrop, err_span);
```
Comment (oli-obk) [inline src/librustc_mir/transform/check_consts/validation.rs:584]: so... in order to do the feature gating you suggested, all we need is to change this to be run if the feature gate is not active and the better logic you implemented will run, too, but since it won't cause more errors, it basically works as redundancy?

File: src/librustc_mir/transform/check_consts/post_drop_elaboration.rs (hunk 3 above)
Comment (ecstatic-morse) [reply src/librustc_mir/transform/check_consts/post_drop_elaboration.rs:73]: I think not. I'll try making it `unreachable`.

File: src/librustc_interface/passes.rs (hunk 1 above)
Comment (ecstatic-morse) [reply src/librustc_interface/passes.rs:843]: Yep. While doing the HIR const-checking. I'll refactor this.

File: src/librustc_mir/transform/check_consts/validation.rs (hunk 5 above)
Comment (ecstatic-morse) [reply src/librustc_mir/transform/check_consts/validation.rs:584]: I think so yes. Should we still force `mir_drops_elaborated_and_const_checked` even if the feature gate is not enabled?

Comment (oli-obk) [reply src/librustc_mir/transform/check_consts/validation.rs:584]: Running it helps ensure it's equivalent to the old logic, where the old logic doesn't error, but may regress perf to do so. I think it'd be nice to run both, but if you see it's annoying in tests, only force it if the feature gate is enabled.

File: src/librustc_interface/passes.rs (hunk 1 above)
Comment (ecstatic-morse) [reply src/librustc_interface/passes.rs:843]: This is going to go in a separate PR that introduces a single `ConstContext` enum in the `hir` crate.

File: src/librustc_mir/transform/check_consts/validation.rs (hunk 5 above)
Comment (ecstatic-morse) [reply src/librustc_mir/transform/check_consts/validation.rs:584]: So I'm second guessing whether we actually want to put these changes behind a feature flag.

The `post_drop_elaboration` part is pretty trivial; the only thing I'm worried about implementing wrong is the query forcing part. We need to figure out if it's okay for a const-checking pass to depend on the precision of drop elaboration, but a feature gate just allows us to delay that discussion. It doesn't help resolve it.

File: src/librustc_mir/transform/check_consts/post_drop_elaboration.rs [hunk 6]
```diff
@@ -69,28 +69,28 @@ impl Visitor<'tcx> for CheckLiveDrops<'mir, 'tcx> {
...
-                    self.check_live_drop(err_span);
+                if self.qualifs.needs_drop(self.ccx, dropped_place.local, location) {
+                    // Use the span where the dropped local was declared for the error.
+                    let span = self.body.local_decls[dropped_place.local].source_info.span;
+                    self.check_live_drop(span);
                 }
             }
 
+            mir::TerminatorKind::DropAndReplace { .. } => {
+                unreachable!("`DropAndReplace` should be removed by drop elaboration")
```
Comment (oli-obk) [inline src/librustc_mir/transform/check_consts/post_drop_elaboration.rs:90]: Please use `span_bug` instead of `unreachable` where possible

File: src/librustc_mir/transform/check_consts/validation.rs (hunk 5 above)
Comment (oli-obk) [reply src/librustc_mir/transform/check_consts/validation.rs:584]: The reason we should have *some* feature gate is that this does allow stable const fn to do more afaict (well, at least if we consider `if/match` stable :laughing: ) and we should have a test for that, so please add one in case it's not there already.

Comment (ecstatic-morse) [reply src/librustc_mir/transform/check_consts/validation.rs:584]: @nikomatsakis, do you want me to nominate this for lang-team or compiler-team discussion? Specifically the part about depending on drop elaboration to determine whether code compiles?

**Comment by nikomatsakis** [comment]
@ecstatic-morse 

So, I have some reservations about this approach. In borrowck, at least, we do our own computation for which drops are live, precisely so that drop elaboration remains a kind of "optimization" and doesn't define our overall semantics. I am unsure whether that's an important invariant to maintain, but I think it's noteworthy that we are giving it up. 

I think maybe what I'm missing is some content -- ideally in the rustc-dev-guide -- documenting the phases of the pipeline and which sort of safety checks we do and when.

**Comment by ecstatic-morse** [comment]
As I understand the status quo, borrow-checking and const-checking/promotion are done prior to drop elaboration (assuming drop elaboration is where we go from the "analysis MIR" to the "optimized MIR"). We force the generator state transform (which doesn't emit any errors) and const propagation (which does unfortunately, see #70073) to run after drop elaboration even when optimizations are disabled, so I think this change would be novel.

One alternative is to reimplement parts of drop elaboration inside the const-checker, obviously this is bad for code duplication, but would put less pressure on those who refactor the drop elaboration pass to preserve existing optimizations. It seems wasteful to do all the analysis required to perform drop elaboration for const-checking, then throw it away and re-run it a few optimization passes later.

Here's the list of passes that run after borrow/const-checking and promotion:

**Comment by nikomatsakis** [comment]
@ecstatic-morse So, currently, the borrow checker includes a certain amount of duplicated reasoning as well -- in particular, it tracks which values "may be" initialized (as well as those that "must be") at each point, and we can use that to determine when a `Drop` is known to be a no-op. I'd have to review the logic there to say *precisely* what we do and do not handle. It sounds like this may be the same information that you need access to, however, which makes me wonder if const qualification could take advantage of it.

**Comment by ecstatic-morse** [comment]
If I were to implement this on without relying on drop elaboration, I would need only the `MaybeInitializedPlaces` analysis. I don't think this would be too hard for me, although it would be more work than the current approach. The borrow checker uses several others: `MaybeUninitializedPlaces` to detect reads from places that are moved from or never assigned and `EverInitializedPlaces` to detect mutation of immutable variables, but I think you are correct that it is doing something very similar to drop elaboration.

I suppose this aspect of const-checking just seems more tied to drop elaboration than the borrow checking does. The first two are doing very similar things, whereas drop elaboration is sort of a small subset of what the borrow checker is doing. This is why it felt so natural to tie the two together.

In your opinion, how likely is the potential backwards compatibility hazard of relying on drop elaboration to materialize? My thinking is that both const-checking and drop elaboration will rely on the same dataflow analysis anyways, and it's highly unlikely that we will make drop elaboration less precise while `MaybeInitializedPlaces` remains unchanged.

**Comment by nikomatsakis** [comment]
@ecstatic-morse 

> how likely is the potential backwards compatibility hazard of relying on drop elaboration to materialize

Yeah, that's a good question. It doesn't seem very likely for things to diverge, and I feel like drop-elaboration is kind of an "obvious" optimization that doesn't involve any particular heuristics. It just kind of works "as well as it obviously can" and that's the end of it.

I think I'm ok with landing it in this form, but I also would like us to sort of document better the "phase transition" point where we move from "static analysis" to "optimizable, go wild".  I've always had "drop elaboration" in my head as that transition point, but it seems like after this PR lands, the point has moved somewhat forward, to after this check.

Is there a clear query transition? I guess I can skim the diff. I think I'd be happiest if we documented it in the rustc-dev-guide ultimately.

**Comment by ecstatic-morse** [comment]
MIR passes are currently divided into "post-borrowck cleanup" and "optimization passes". This runs immediately after "post-borrowck cleanup".

**Comment by ecstatic-morse** [comment]
@rust-lang/lang, do we want to put these changes behind a feature gate? @oli-obk thinks [we should](https://github.com/rust-lang/rust/pull/71824#discussion_r420942263). My opinion is that this isn't really a "feature" but a refinement to const-checking, and it's kind of non-obvious what the user would be "opting in" to with the feature gate, since drop elaboration is an implementation detail. A relevant precedent is `#![feature(nll)]`, but that was much larger and more fundamental than this change would be.

This is also somewhat relevant to the stabilization of `#![feature(const_if_match)]`. Nothing in this PR is specifically related to branching in constants. For instance, it makes the example below compile as well. However, I expect users will commonly want to move out of `Option::Some` within a `match`, which won't work for `Drop` types without this PR.

**Comment by nikomatsakis** [comment]
To clarify, this PR makes that code compile because previously we were dropping the `vec_tuple` which had type `Option<(Vec<i32>,)>`?

**Comment by nikomatsakis** [comment]
And you're saying that this PR will make that code work on stable?

**Comment by ecstatic-morse** [comment]
> To clarify, this PR makes that code compile because previously we were dropping the vec_tuple which had type Option<(Vec<i32>,)>?

This code is functionally no different from the following, which currently works on stable.

```rust
const X: Option<Vec<i32>> = { let x = Vec::new(); x };
```

Const-checking only considers whole locals for const qualification, but drop elaboration is more precise: It works on projections as well. Because drop elaboration sees that all fields of the tuple have been moved from by the end of the initializer, no `Drop` terminator is left in the MIR, despite the fact that the tuple *itself* is never moved from.

> And you're saying that this PR will make that code work on stable?

Correct.

**Comment by nikomatsakis** [comment]
OK. I'm not really sure what I think about a feature-gate. I guess it seems "prudent" but I'm not sure what additional information we will gain from it. It is certainly possible that we'll realize some unexpected bit of code that is permitted thanks to drop elaboration.

**Comment by ecstatic-morse** [comment]
@oli-obk This is now behind a `const_precise_live_drops` feature gate.

**Comment by oli-obk** [comment]
r=me after another rebase

File: src/librustc_mir/transform/check_consts/post_drop_elaboration.rs [hunk 7]
```diff
@@ -0,0 +1,119 @@
...
+    }
+
+    fn visit_terminator(&mut self, terminator: &mir::Terminator<'tcx>, location: Location) {
+        trace!("visit_terminator: terminator={:?} location={:?}", terminator, location);
+
+        match &terminator.kind {
+            mir::TerminatorKind::Drop { location: dropped_place, .. } => {
+                let dropped_ty = dropped_place.ty(self.body, self.tcx).ty;
+                if !NeedsDrop::in_any_value_of_ty(self.ccx, dropped_ty) {
+                    return;
```
Comment (RalfJung) [inline src/librustc_mir/transform/check_consts/post_drop_elaboration.rs:84]: @oli-obk  Is this even reachable? I'd think we don't emit `Drop` terminators for types that do not need dropping...

File: src/librustc_mir/transform/check_consts/post_drop_elaboration.rs [hunk 8]
```diff
@@ -0,0 +1,119 @@
...
+                }
+
+                if dropped_place.is_indirect() {
+                    self.check_live_drop(terminator.source_info.span);
+                    return;
+                }
+
+                if self.qualifs.needs_drop(self.ccx, dropped_place.local, location) {
```
Comment (RalfJung) [inline src/librustc_mir/transform/check_consts/post_drop_elaboration.rs:92]: Same here, this looks like it second-guessing drop elaboration which already determined that this drop is indeed necessary.

File: src/librustc_mir/transform/check_consts/post_drop_elaboration.rs (hunk 7 above)
Comment (oli-obk) [reply src/librustc_mir/transform/check_consts/post_drop_elaboration.rs:84]: This is indeed not reachable.

File: src/librustc_mir/transform/check_consts/post_drop_elaboration.rs (hunk 8 above)
Comment (oli-obk) [reply src/librustc_mir/transform/check_consts/post_drop_elaboration.rs:92]: This one is reachable. I'm not sure yet why, but I am guessing the reason is that `needs_drop` is its own analysis, while drop elaboration relies on `MaybeInitializedPlaces` and `MaybeUninitializedPlaces` to make a decision. We could probably rewrite drop elaboration in terms of the `NeedsDrop` qualif, which would (afaict) allow `post_drop_elaboration` to not do any checks except for looking for `Drop` terminators.

Of course such a change would insta-stabilize the feature gate from this PR without any reasonable way to avoid said stabilization. So I'm tempted to stabilize the feature but leave a FIXME on this function to merge its qualif checks into `elaborate_drops`

Comment (RalfJung) [reply src/librustc_mir/transform/check_consts/post_drop_elaboration.rs:92]: The alternative would be to ignore qualifs here, and just follow what drop elaboration does.

Comment (RalfJung) [reply src/librustc_mir/transform/check_consts/post_drop_elaboration.rs:92]: If we do keep following the qualifs to get an edge in precision over drop elaboration (maybe we have to, for backwards compat), we should add a test case for a program where the qualifs are more precise than drop elaboration is (i.e. a program that would get rejected if we just always called `check_live_drop`), and reference that testcase from the code here.

File: src/librustc_mir/transform/check_consts/post_drop_elaboration.rs [hunk 9]
```diff
@@ -0,0 +1,119 @@
...
+    type Target = ConstCx<'mir, 'tcx>;
+
+    fn deref(&self) -> &Self::Target {
+        &self.ccx
+    }
+}
+
+impl CheckLiveDrops<'mir, 'tcx> {
+    fn check_live_drop(&self, span: Span) {
+        ops::non_const(self.ccx, ops::LiveDrop, span);
```
Comment (RalfJung) [inline src/librustc_mir/transform/check_consts/post_drop_elaboration.rs:61]: This function name is quite confusing... it doesn't check anything, it just raises an error!

Is it even worth having a function for this, or can we just inline it?

Comment (oli-obk) [reply src/librustc_mir/transform/check_consts/post_drop_elaboration.rs:61]: This is resolved on master

File: src/test/ui/consts/control-flow/drop-fail.rs [hunk 10]
```diff
@@ -1,11 +1,14 @@
+// revisions: stock precise
+
 #![feature(const_if_match)]
 #![feature(const_loop)]
+#![cfg_attr(precise, feature(const_precise_live_drops))]
 
-// `x` is *not* always moved into the final value may be dropped inside the initializer.
+// `x` is *not* always moved into the final value and may be dropped inside the initializer.
 const _: Option<Vec<i32>> = {
     let y: Option<Vec<i32>> = None;
```
Comment (oli-obk) [inline src/test/ui/consts/control-flow/drop-fail.rs:9]: If we unconditionally error on drops, this line will cause an error (meaning: this is the test case you're looking for)

Comment (RalfJung) [reply src/test/ui/consts/control-flow/drop-fail.rs:9]: If I interpret the error annotations correctly, this errors (in the next line) even with `precise` analysis? Doesn't seem terribly useful then to not error here.^^

Isn't there an example where we need this to actually accept more code?

Comment (oli-obk) [reply src/test/ui/consts/control-flow/drop-fail.rs:9]: The next line is completely independent of this line.

File: src/test/ui/consts/control-flow/drop-precise.rs [hunk 11]
```diff
@@ -0,0 +1,20 @@
...
+    vec_tuple.0
+};
+
+const _: Vec<i32> = {
+    let x: Result<_, Vec<i32>> = Ok(Vec::new());
+    match x {
+        Ok(x) | Err(x) => x,
+    }
+};
+
```
Comment (oli-obk) [inline src/test/ui/consts/control-flow/drop-precise.rs:19]: This is an example of a run-pass test that won't compile without precise_live_drops

Comment (oli-obk) [reply src/test/ui/consts/control-flow/drop-precise.rs:19]: right, sorry. This PR has multiple checks. I'll comment on the main question

File: src/test/ui/consts/control-flow/drop-fail.rs (hunk 10 above)
Comment (oli-obk) [reply src/test/ui/consts/control-flow/drop-fail.rs:9]: I think I'll split up the feature gate into two, so we can actually play with examples on the playground.

Comment (RalfJung) [reply src/test/ui/consts/control-flow/drop-fail.rs:9]: I don't think we want this exposed to the user; doesn't just commenting out those lines make some tests fail (in more ways than just moving around the location of the error message)?

Comment (RalfJung) [reply src/test/ui/consts/control-flow/drop-fail.rs:9]: I found examples in the test suite: https://github.com/rust-lang/rust/pull/83351

File: src/librustc_mir/transform/check_consts/post_drop_elaboration.rs (hunk 8 above)
Comment (ecstatic-morse) [reply src/librustc_mir/transform/check_consts/post_drop_elaboration.rs:92]: https://github.com/rust-lang/rust/blob/a985d8e6c7f0519fa1e147854430a381ac4eadf8/src/test/ui/consts/drop_none.rs#L3-L10

Is this what you're looking for? We do have to keep this for back-compat, see #57734

Comment (RalfJung) [reply src/librustc_mir/transform/check_consts/post_drop_elaboration.rs:92]: Sorry, I forgot to post that here: the follow-up to this discussion is at https://github.com/rust-lang/rust/pull/83351.

Comment (ecstatic-morse) [reply src/librustc_mir/transform/check_consts/post_drop_elaboration.rs:92]: Ah, you already found an equivalent one.
