### PR TITLE
remove support for `typeof`

### LINKED ISSUE #148700: Tracking issue for MCP 940: remove support for `typeof`
This is a tracking issue for MCP "remove support for `typeof`" (rust-lang/compiler-team#940).

> [!NOTE]
> Tracking issues are used to record the overall progress of implementation.
> They are also used as hubs connecting to other relevant issues, e.g., bugs or open design questions.
>
> A tracking issue is however *not* meant for large scale discussion, questions, or bug reports.
> Instead, open a dedicated issue for the specific matter, link to this tracking issue and ping the MCP author.
> Alternatively, post in the Zulip stream linked from the MCP.
>
> Discussion comments will get marked as off-topic or deleted.
> Repeated discussions on the tracking issue may lead to the tracking issue getting locked.

### Steps

- [ ] Implement the MCP
- [ ] Adjust documentation
  - [ ] In the [Rust Compiler Development Guide] if applicable (e.g., for refactorings)
  - [ ] In the [Rust Forge] if applicable (e.g., for policy changes)
  - [ ] In the [rustc book] if applicable (e.g., for target tier or CLI changes)

[Rust Compiler Development Guide]: https://rustc-dev-guide.rust-lang.org/
[Rust Forge]: https://forge.rust-lang.org/compiler/index.html
[rustc book]: https://doc.rust-lang.org/rustc/index.html

### Unresolved questions

*None so far.*

### Implementation history

*Empty so far.*

---

@lcnr, consider `@rustbot claim`'ing the work.

### PR DESCRIPTION
**Pull request by lcnr**
see https://github.com/rust-lang/compiler-team/issues/940 closes https://github.com/rust-lang/rust/issues/148700

This also enables checks for invariants previously broken by `typeof` again.

r? types

### CODE REVIEW

File: compiler/rustc_ast/src/token.rs [hunk 1]
```diff
@@ -321,7 +321,7 @@ fn ident_can_begin_type(name: Symbol, span: Span, is_raw: IdentIsRaw) -> bool {
 
     !ident_token.is_reserved_ident()
         || ident_token.is_path_segment_keyword()
-        || [kw::Underscore, kw::For, kw::Impl, kw::Fn, kw::Unsafe, kw::Extern, kw::Typeof, kw::Dyn]
+        || [kw::Underscore, kw::For, kw::Impl, kw::Fn, kw::Unsafe, kw::Extern, kw::Dyn]
```
Comment (WaffleLapkin) [inline compiler/rustc_ast/src/token.rs]: q: is there a chance this affects macros?

File: compiler/rustc_hir_analysis/src/coherence/inherent_impls.rs [hunk 2]
```diff
@@ -195,10 +195,11 @@ impl<'tcx> InherentCollect<'tcx> {
...
             | ty::Coroutine(..)
-            | ty::CoroutineWitness(..) => {
-                Err(self.tcx.dcx().delayed_bug("cannot define inherent `impl` for closure types"))
-            }
-            ty::Alias(ty::Free, _) | ty::Bound(..) | ty::Placeholder(_) | ty::Infer(_) => {
+            | ty::CoroutineWitness(..)
+            | ty::Alias(ty::Free, _)
+            | ty::Bound(..)
+            | ty::Placeholder(_)
+            | ty::Infer(_) => {
```
Comment (WaffleLapkin) [inline compiler/rustc_hir_analysis/src/coherence/inherent_impls.rs:202]: q: How is this related to this PR?

File: compiler/rustc_parse/src/parser/ty.rs [hunk 3]
```diff
@@ -328,8 +328,6 @@ impl<'a> Parser<'a> {
             // Reference
             self.expect_and()?;
             self.parse_borrowed_pointee()?
-        } else if self.eat_keyword_noexpect(kw::Typeof) {
```
Comment (Noratrieb) [inline compiler/rustc_parse/src/parser/ty.rs:330]: It may be nice to keep a precise error message here and recover into an error type

File: compiler/rustc_ast/src/token.rs (hunk 1 above)
Comment (fmease) [reply compiler/rustc_ast/src/token.rs]: Yes, the following artificial snippet will go from pass→fail:

```rs
macro_rules! ck { ($ty:ty) => {}; }
ck!(typeof(0));
```

After this PR it'll fail with ``no rules expected keyword `typeof` `` (and hypothetically if `typeof` were to be demoted to a normal identifier, it would start failing with `` expected type, found `0` ``).

However, it's very unlikely anybody is relying on it. So it's not really a concern. MBE is notoriously forward incompatible.

File: compiler/rustc_hir_analysis/src/coherence/inherent_impls.rs (hunk 2 above)
Comment (fmease) [reply compiler/rustc_hir_analysis/src/coherence/inherent_impls.rs:202]: With the removal of `typeof` inference, it should now be impossible to sneak these unnameable types into an impl (even with TAIT you can't do that IINM). The `typeof` removal is partially motivated by being able to perform this exact change as lcnr alluded to in the MCP. CC https://github.com/rust-lang/rust/pull/147219, https://github.com/rust-lang/rust/issues/146620 https://github.com/rust-lang/rust/issues/147146.

Comment (lcnr) [reply compiler/rustc_hir_analysis/src/coherence/inherent_impls.rs:202]: >With the removal of typeof inference, it should now be impossible to sneak these unnameable types into an impl (even with TAIT you can't do that IINM)
 
 Yes, there's currently no way to get unnameable types into impl headers or encounter them in coherence, and it's nice to be able to reason about that

**Comment by spastorino** [comment]
This looks good to me, `r=me` once the MCP finishes and addressing @Noratrieb's comment.

File: compiler/rustc_parse/src/parser/ty.rs (hunk 3 above)
Comment (lcnr) [reply compiler/rustc_parse/src/parser/ty.rs:330]: how do you do that? It's not immediately obvious to me how to impl that and don't want to spend much time on figuring this out :thinking:

Comment (fmease) [reply compiler/rustc_parse/src/parser/ty.rs:330]: > how do you do that? It's not immediately obvious to me how to impl that

Instead of removing this `eat_keyword_noexpect` branch + fn `parse_typeof_ty`, keep both but change `parse_typeof_ty` to no longer return a `TyKind::Typeof(expr)` but instead a `TyKind::Err(guar)` (this variant already exists) where obv. `let guar = dcx.struct_span_err(…, "…");`.

Comment (fmease) [reply compiler/rustc_parse/src/parser/ty.rs:330]: This made me realize that we do accept this on stable (and have been since ~forever), lol:

```rs
#[cfg(false)]
type X = typeof(0);
```

So forget what I said about MBEs, this is a far more obvious demonstration why removing `typeof` is a theoretical breaking change, not that anybody would care ^^.

Comment (lcnr) [reply compiler/rustc_parse/src/parser/ty.rs:330]: done that I think? @fmease do you think this is relevant enough to do a crater run or sth like that here?

Comment (fmease) [reply compiler/rustc_parse/src/parser/ty.rs:330]: I think the most likely scenario would be something like `#[mydsl] fn f() { … typeof(…) … }` but even that seems farfetched (esp. since this would still compile if `mydsl` is a *proc-macro* attr).

I've also skimmed the results of [GH Search: `/(?-i)\btypeof\([^)"]/` language:Rust](https://github.com/search?q=%2F%28%3F-i%29%5Cbtypeof%5C%28%5B%5E%29%22%5D%2F+language%3ARust&type=code&ref=advsearch) but couldn't find anything that would break.

So, I don't think this warrants a crater run, let's just ship it.

**Review by WaffleLapkin — APPROVED** [review]
