### PR TITLE
Fix `FileType` `PartialEq` implementation on Windows

### LINKED ISSUE #138668: Inconsistent behavior in FileType comparisons on Windows
The `PartialEq`/`Eq` implementation of FileType on Windows is currently comparing more than just the actual file type. It seems to be using **all** file attributes for the comparison instead.

## Steps to reproduce:

1. Create two files, e.g. `a.txt` and `b.txt`
2. Using Windows Explorer:
   - Right click -> Properties -> open the "Advanced" file attributes dialog
   - Enable "Allow this file to have contents indexed in addition to file properties" for only **one** of these files, but not the other

The following test will now fail:

```rust
let type_a = fs::metadata("a.txt").unwrap().file_type();
let type_b = fs::metadata("b.txt").unwrap().file_type();
assert_eq!(type_a, type_b);
```

## Expected behavior:

I would expect the comparison between two `FileType`s to only compare the actual file TYPE (e.g. file, dir, symlink, any platform-specific extensions), but not file attributes.

Another issue in this case is that it isn't obvious why the comparison fails, because `FileType`'s Debug implementation only shows `is_file`, `is_dir`, and `is_symlink`:

```
assertion `left == right` failed
  left: FileType { is_file: true, is_dir: false, is_symlink: false, .. }
 right: FileType { is_file: true, is_dir: false, is_symlink: false, .. }
```

I'm not sure whether this is something that can be easily fixed - I'd argue it should be considered an actual bug occurring in an edge case, but fixing it would technically introduce a breaking change.

## `rustc --version --verbose`:
```
rustc 1.85.0 (4d91de4e4 2025-02-17)
binary: rustc
commit-hash: 4d91de4e48198da2e33413efdcd9cd2cc0c46688
commit-date: 2025-02-17
host: x86_64-pc-windows-msvc
release: 1.85.0
LLVM version: 19.1.7
```

### PR DESCRIPTION
**Pull request by ChrisDenton**
Fixes #138668

On Windows the [`FileType`](https://doc.rust-lang.org/stable/std/fs/struct.FileType.html) struct was deriving `PartialEq` which in turn means it was doing a bit-for-bit comparison on the file attributes and reparse point. This is wrong because `attributes` may contain many things unrelated to file type.

`FileType` on Windows allows for four possible combinations (see also [`FileTypeExt`](https://doc.rust-lang.org/stable/std/os/windows/fs/trait.FileTypeExt.html)): `file`, `dir`, `symlink_file` and `symlink_dir`. So the new implementation makes sure both symlink and directory information match (and only those things).

This could be considered just a bug fix but it is a behaviour change so someone from libs-api might want to FCP this (or might not)...

### CODE REVIEW

**Comment by ChrisDenton** [comment]
@joshtriplett, since you won the dice roll, does this need an FCP?

**Comment by Kyuuhachi** [comment]
Should probably fix the Hash too, because it currently breaks the `a == b -> hash(a) == hash(b)` property.

**Comment by ChrisDenton** [comment]
Good point!

File: library/std/src/sys/fs/windows.rs [hunk 1]
```diff
@@ -1140,6 +1141,18 @@ impl FileType {
...
 
+impl PartialEq for FileType {
+    fn eq(&self, other: &Self) -> bool {
+        self.is_directory() == other.is_directory() && self.is_symlink() == other.is_symlink()
+    }
+}
+
+impl Hash for FileType {
+    fn hash<H: Hasher>(&self, state: &mut H) {
+        state.write(&[self.is_directory() as u8, self.is_symlink() as u8]);
```
Comment (ChrisDenton) [inline library/std/src/sys/fs/windows.rs:1152]: This could be squished into a single byte but not sure if such a micro size optimisation is worth it.

**Comment by ChrisDenton** [comment]
Actually this implementation would be so much simpler if I just calculated `is_directory` and `is_symlink` upfront instead of on-demand. The only reason to call `file_type` is to use one of the `FileType` functions so I doubt it'll impact performance or anything. So I'll do that instead.

**Comment by joshtriplett** [comment]
This seems correct to me. And I think it's a bugfix, not an API change.

@bors r+
