### PR TITLE
Rustdoc: only report broken ref-style links once

### LINKED ISSUE #77681: Rustdoc reports intradoc link errors twice if there are multiple links
I tried this code:

```rust
/// Links to [a] [twice][a]
///
/// [a]: not_found
pub fn f() {}
```
I expected to see this happen: Rustdoc warns once, because there is only one reference link.

Instead, this happened: Rustdoc warns twice, because there are multiple uses of the reference link.

```
warning: unresolved link to `not_found`
 --> tmp.rs:3:10
  |
3 | /// [a]: not_found
  |          ^^^^^^^^^ the module `tmp` contains no item named `not_found`
  |
  = note: `#[warn(broken_intra_doc_links)]` on by default
  = help: to escape `[` and `]` characters, add '\' before them like `\[` or `\]`

warning: unresolved link to `not_found`
 --> tmp.rs:3:10
  |
3 | /// [a]: not_found
  |          ^^^^^^^^^ the module `tmp` contains no item named `not_found`
  |
  = help: to escape `[` and `]` characters, add '\' before them like `\[` or `\]`
```

### Meta

`rustdoc +nightly --version`: rustdoc 1.48.0-nightly (8fe73e80d 2020-10-01)

### PR DESCRIPTION
**Pull request by bugadani**
This PR assigns the markdown `LinkType` to each parsed link and passes this information into the link collector.
If a link can't be resolved in `resolve_with_disambiguator`, the failure is cached for the link types where we only want to report the error once (namely `Shortcut` and `Reference`).

Fixes  #77681

### CODE REVIEW

File: src/librustdoc/html/markdown.rs [hunk 1]
```diff
@@ -1064,7 +1064,7 @@ pub fn plain_text_summary(md: &str) -> String {
     s
 }
 
-pub fn markdown_links(md: &str) -> Vec<(String, Option<Range<usize>>)> {
+pub fn markdown_links(md: &str) -> Vec<(LinkType, String, Option<Range<usize>>)> {
```
Comment (jyn514) [inline src/librustdoc/html/markdown.rs:1067]: Hmm, this is getting large enough it might be worth turning into a `struct MarkdownLink { kind, url, span }`.

File: src/librustdoc/html/markdown.rs [hunk 2]
```diff
@@ -1101,11 +1105,13 @@ pub fn markdown_links(md: &str) -> Vec<(String, Option<Range<usize>>)> {
         let iter = Footnotes::new(HeadingLinks::new(p, None, &mut ids));
 
         for ev in iter {
-            if let Event::Start(Tag::Link(_, dest, _)) = ev {
+            if let Event::Start(Tag::Link(link_ty, dest, _)) = ev {
```
Comment (jyn514) [inline src/librustdoc/html/markdown.rs:1108]: nit: I would call this `kind` to be consistent with the rest of the codebase.

File: src/librustdoc/passes/collect_intra_doc_links.rs [hunk 3]
```diff
@@ -136,11 +163,18 @@ struct LinkCollector<'a, 'tcx> {
     /// because `clean` and the disambiguator code expect them to be different.
     /// See the code for associated items on inherent impls for details.
     kind_side_channel: Cell<Option<(DefKind, DefId)>>,
+    /// Cache the resolved links so we can avoid resolving (and emitting errors for) the same link
+    visited_links: FxHashMap<CacheKey, Option<CachedLink>>,
```
Comment (jyn514) [inline src/librustdoc/passes/collect_intra_doc_links.rs:167]: ~~Hmm, won't this conflict with https://github.com/rust-lang/rust/pull/77700? How will the two interact?~~ never mind, looks like you just cherry-picked all those commits which is fine.

File: src/librustdoc/passes/collect_intra_doc_links.rs [hunk 4]
```diff
@@ -911,14 +946,15 @@ impl<'a, 'tcx> DocFolder for LinkCollector<'a, 'tcx> {
 
 impl LinkCollector<'_, '_> {
     fn resolve_link(
-        &self,
+        &mut self,
```
Comment (jyn514) [inline src/librustdoc/passes/collect_intra_doc_links.rs:949]:
```suggestion
        &self,
```

File: src/librustdoc/passes/collect_intra_doc_links.rs [hunk 5]
```diff
@@ -1178,6 +1220,60 @@ impl LinkCollector<'_, '_> {
...
+    ) -> Option<(Res, Option<String>)> {
+        // Try to look up both the result and the corresponding side channel value
+        if let Some(ref cached) = self.visited_links.get(&key) {
+            if let Some(ref cached) = cached {
+                self.kind_side_channel.set(cached.side_channel.clone());
+                Some(cached.res.clone())
+            } else {
+                // we cached an error
+                None
+            }
```
Comment (jyn514) [inline src/librustdoc/passes/collect_intra_doc_links.rs:1241]:
```suggestion
            cached.map(|item| {
                self.kind_side_channel.set(item.side_channel.clone());
                item.res.clone()
            })
```

File: src/librustdoc/passes/collect_intra_doc_links.rs [hunk 6]
```diff
@@ -1178,6 +1220,60 @@ impl LinkCollector<'_, '_> {
...
+        key: CacheKey,
+        item: &Item,
+        dox: &str,
+        current_item: &Option<String>,
+        ori_link: &str,
+        link_range: Option<Range<usize>>,
+        link_ty: LinkType,
+    ) -> Option<(Res, Option<String>)> {
+        // Try to look up both the result and the corresponding side channel value
+        if let Some(ref cached) = self.visited_links.get(&key) {
```
Comment (jyn514) [inline src/librustdoc/passes/collect_intra_doc_links.rs:1234]: `ref` isn't necessary here since it's already a borrow.
```suggestion
        if let Some(cached) = self.visited_links.get(&key) {
```

File: src/test/rustdoc-ui/reference-link-reports-error-once.rs [hunk 7]
```diff
@@ -0,0 +1,8 @@
+#![deny(broken_intra_doc_links)]
+
+/// Links to [a] [link][a]
+/// And also a [third link][a]
```
Comment (jyn514) [inline src/test/rustdoc-ui/reference-link-reports-error-once.rs:4]: Hmm, I think I remember you having more test cases in https://github.com/rust-lang/rust/pull/77700. Can't remember what they were, though.

File: src/librustdoc/passes/collect_intra_doc_links.rs (hunk 3 above)
Comment (bugadani) [reply src/librustdoc/passes/collect_intra_doc_links.rs:167]: I branched this off of #77700 so it's blocked on that, hence the draft PR.

File: src/librustdoc/passes/collect_intra_doc_links.rs (hunk 4 above)
Comment (bugadani) [reply src/librustdoc/passes/collect_intra_doc_links.rs:949]: I don't see how, since caching in #77700 needs `mut self`, unless I introduce interior mutability which seems unnecessary.

File: src/test/rustdoc-ui/reference-link-reports-error-once.rs (hunk 7 above)
Comment (bugadani) [reply src/test/rustdoc-ui/reference-link-reports-error-once.rs:4]: This kinda belongs on #77700, but I removed the tests when we narrowed the PR's scope, because adding a cache shouldn't change behaviour and they didn't belong there any more.

File: src/librustdoc/passes/collect_intra_doc_links.rs (hunk 5 above)
Comment (bugadani) [reply src/librustdoc/passes/collect_intra_doc_links.rs:1241]: Just an FYI: directly taking this suggestion and the below one (removing `ref`) results in this:

```
error[E0507]: cannot move out of `*cached` which is behind a shared reference
    --> src/librustdoc/passes/collect_intra_doc_links.rs:1235:13
     |
1235 |             cached.map(|cached| {
     |             ^^^^^^
     |             |
     |             move occurs because `*cached` has type `std::option::Option<CachedLink>`, which does not implement the `Copy` trait
     |             help: consider borrowing the `Option`'s content: `cached.as_ref()`
```

File: src/librustdoc/passes/collect_intra_doc_links.rs [hunk 8]
```diff
@@ -1052,15 +1053,25 @@ impl LinkCollector<'_, '_> {
...
-        let (mut res, mut fragment) = self.resolve_with_disambiguator_cached(key, diag)?;
+        let (mut res, mut fragment) = self.resolve_with_disambiguator_cached(
+            ResolutionInfo {
+                module_id,
+                dis: disambiguator,
+                path_str: path_str.to_owned(),
+                extra_fragment,
+                cache_resolution_failure: matches!(
+                    ori_link.kind,
+                    LinkType::Reference | LinkType::Shortcut
```
Comment (bugadani) [inline src/librustdoc/passes/collect_intra_doc_links.rs:1070]: I don't particularly like this, but:
 - LinkType isn't hashable, so it can't be included in the ResolutionInfo struct directly
 - even if LinkType were hashable, including it would result in random test failures (didn't bother investigating)
 - I'm not sure *why* this doesn't break shortcut links completely (maybe because they are parsed as `ShortcutUnknown`?)

File: src/librustdoc/html/markdown.rs [hunk 9]
```diff
@@ -1174,12 +1173,36 @@ crate fn markdown_links(md: &str) -> Vec<(String, Option<Range<usize>>)> {
             } else {
                 None
             }
-        };
+        }
```
Comment (jyn514) [inline src/librustdoc/html/markdown.rs:1176]: Wow this whole thing is just *so* concerning. You don't need to change it here but this should really be fixed to get rid of the unsafe, there's no need at all for it.

File: src/librustdoc/passes/collect_intra_doc_links.rs [hunk 10]
```diff
@@ -201,7 +204,7 @@ struct LinkCollector<'a, 'tcx> {
     /// See the code for associated items on inherent impls for details.
     kind_side_channel: Cell<Option<(DefKind, DefId)>>,
     /// Cache the resolved links so we can avoid resolving (and emitting errors for) the same link
```
Comment (jyn514) [inline src/librustdoc/passes/collect_intra_doc_links.rs:206]:
```suggestion
    /// Cache the resolved links so we can avoid resolving (and emitting errors for) the same link.
    /// The link will be `None` if it could not be resolved (i.e. the error was cached).
```

File: src/librustdoc/passes/collect_intra_doc_links.rs (hunk 8 above)
Comment (jyn514) [reply src/librustdoc/passes/collect_intra_doc_links.rs:1070]: Calculating whether to cache it ahead of time seems fine. The reason you check explicitly for the kind is because inline links shouldn't be cached (things like `[x](Ok)`)? Can you check for those explicitly instead? Or if that's not what you meant, maybe `Collapsed` should also be checked?

Comment (jyn514) [reply src/librustdoc/passes/collect_intra_doc_links.rs:1070]: And I have another question - I don't think this needs to be part of the key, right? It would work if you passed it as a parameter instead? That would avoid having to hash it at all.

File: src/test/rustdoc-ui/reference-link-reports-error-once.rs [hunk 11]
```diff
@@ -0,0 +1,14 @@
...
+///
+/// Other links to the same target should still emit error: [ref] //~ERROR unresolved link to
+/// Duplicate [ref] //~ERROR unresolved link to
+///
+/// Other links to other targets should still emit error: [ref2] //~ERROR unresolved link to
+/// Duplicate [ref2] //~ERROR unresolved link to
+///
+/// [a]: ref
+//~^ ERROR unresolved link to
```
Comment (jyn514) [inline src/test/rustdoc-ui/reference-link-reports-error-once.rs:13]:
```suggestion
//~^ ERROR unresolved link to

/// [ref][]
//~^ ERROR unresolved link
```

File: src/librustdoc/passes/collect_intra_doc_links.rs (hunk 8 above)
Comment (bugadani) [reply src/librustdoc/passes/collect_intra_doc_links.rs:1070]: It has to be, otherwise "normal" links to the same target as a reference-style link would hit the cache. See the test case for exactly this :) Depends on what you expect, I guess, but this patch aims to emit a single error for each incorrect link definition, or at least that was my goal.

Comment (bugadani) [reply src/librustdoc/passes/collect_intra_doc_links.rs:1070]: Ah, it's also not that links don't get cached, but resolution failures don't get cached. Which is only interesting in the reference style links case, where we don't want to emit an error for each usage of the incorrect link. I think :)

File: src/librustdoc/html/markdown.rs (hunk 9 above)
Comment (bugadani) [reply src/librustdoc/html/markdown.rs:1176]: Simple enough, if the goal is only to get rid of the unsafe block.

Also, since we only use this inside "new_with_source", which is in turn only used if we have a borrowed string from the parser, maybe I can just delete 3/4 of this function.

Comment (jyn514) [reply src/librustdoc/html/markdown.rs]: I fixed this in https://github.com/rust-lang/rust/pull/80244.

File: src/librustdoc/passes/collect_intra_doc_links.rs (hunk 8 above)
Comment (jyn514) [reply src/librustdoc/passes/collect_intra_doc_links.rs:1071]: > Ah, it's also not that links don't get cached, but resolution failures don't get cached. 

Right, that's what I meant, thanks.

> It has to be, otherwise "normal" links to the same target as a reference-style link would hit the cache.

Ok, I see the issue: if you have something like

```rust
/// [reference][link] and [inline](link)
```
both `link`s should give an error, but if you don't include `cache_resolution_failure` in the cache key, then the second link will pick up the `None` and be returned.

So I have a further question now - when will you hit the cache and *not* have `cache_resolution_failure` set? That would only happen for `[inline](link)` twice in a row, right? But we explicitly choose *not* to insert it into the cache on error. I think there's an optimization here where you can make the size of the cache smaller by explicitly checking `cache_resolution_failure` on a cache hit, that way you don't need that extra bit of info; and the logic seems more clear to me too.

Comment (bugadani) [reply src/librustdoc/passes/collect_intra_doc_links.rs:1071]: > I think there's an optimization here

Interesting thought, that might be something I missed.

File: src/test/rustdoc-ui/reference-link-reports-error-once.rs [hunk 12]
```diff
@@ -0,0 +1,20 @@
...
+/// [b]: ref2
```
Comment (bugadani) [inline src/test/rustdoc-ui/reference-link-reports-error-once.rs:15]: In the current patch, if this is `[b]: ref`, the error emitted for `[reference link][b]` will point to the definition of `a`. This is because the link cache ignores the name of the reference and handles a and b as if identical. This isn't ideal, but I consider this acceptable: we don't report all errors, but if the user fixes link `a`, we will report an error for link `b`, so eventually, every error can be caught :)

We could fix this by adding the span to `ResolutionInfo` (Optionally, only for Shortcut/Reference links), but I'm not sure if the complexity is worth it.

File: src/librustdoc/html/markdown.rs [hunk 13]
```diff
@@ -1190,10 +1201,20 @@ crate fn markdown_links(md: &str) -> Vec<(String, Range<usize>)> {
...
             debug!("found link: {}", dest);
-            let span = span_for_link(&dest, ev.1);
-            links.push((dest.into_string(), span));
+            let link = dest.into_string();
+            let span = if let LinkType::Shortcut | LinkType::Reference = kind {
+                // NOTE (I'm sorry Joshua):
+                // For reference-style links (where the target is defined in footnote) we want the
+                // span to point to the definition, not the usage in order to generate useful error
+                // messages.
+                let start = link.as_ptr() as usize - md.as_ptr() as usize;
```
Comment (bugadani) [inline src/librustdoc/html/markdown.rs:1212]: This actually doesn't work because the parser may clone the string and the pointer will no longer point into `md`. Sad :(

Comment (jyn514) [reply src/librustdoc/html/markdown.rs:1212]: Can you open an issue for `pulldown`? I think pointing to the usage is fine for now though.

File: src/test/rustdoc-ui/reference-link-reports-error-once.rs (hunk 12 above)
Comment (jyn514) [reply src/test/rustdoc-ui/reference-link-reports-error-once.rs:15]: Wait, I'm confused what those have to do with each other. We never cache the span, so there's nowhere for it to look up the span of `a` in the first place, the only span *available* is that of `b`.

Can you post the error that's wrong?

File: src/librustdoc/html/markdown.rs (hunk 13 above)
Comment (bugadani) [reply src/librustdoc/html/markdown.rs:1212]: To be honest, I don't consider this a bug in `pulldown`. Current behaviour is strange, but unless `pulldown` can provide two spans for a single event, this is at least consistent enough.

Pointing at the usage feels weird, though. This doesn't point me to what I need to modify:
```
+ LL | /// Links to [a] [link][a]
+    |              ^^^ no item named `ref` in scope
```

But I guess we can live with it if we can't fix it.

On the other hand, if it were possible to look up the link's title in the list of definitions, we could maybe point at the definition itself. I guess we can build a collector pass that build a table from footnotes? I need to look into how pulldows actually parses text and which events are relevant here. That will probably have to wait for next year, though.

Comment (jyn514) [reply src/librustdoc/html/markdown.rs:1212]: Hmm, yeah that error is pretty bad. I think I would rather have duplicate errors than an error pointing to the wrong place :/

File: src/test/rustdoc-ui/reference-link-reports-error-once.rs (hunk 12 above)
Comment (bugadani) [reply src/test/rustdoc-ui/reference-link-reports-error-once.rs:15]: Assume the following:

```
[a] [b]

[a]: ref
[b]: ref
```

We would only report an error for `a`.

File: src/librustdoc/html/markdown.rs (hunk 13 above)
Comment (bugadani) [reply src/librustdoc/html/markdown.rs:1212]: You broke it ;)

Comment (jyn514) [reply src/librustdoc/html/markdown.rs:1212]: Oh oof, you're right, this is latest nightly:

```
warning: unresolved link to `std::process::Comman`
 --> link.rs:1:14
  |
1 | //! Links to [a] [link][a]
  |              ^^^ no item named `Comman` in module `process`
  |
  = note: `#[warn(broken_intra_doc_links)]` on by default

warning: unresolved link to `std::process::Comman`
 --> link.rs:1:18
  |
1 | //! Links to [a] [link][a]
  |                  ^^^^^^^^^ no item named `Comman` in module `process`
```

and this is a couple days ago, before the PR removing locate():

```
warning: unresolved link to `std::process::Comman`
 --> link.rs:3:10
  |
3 | //! [a]: std::process::Comman
  |          ^^^^^^^^^^^^^^^^^^^^ no item named `Comman` in module `process`
  |
  = note: `#[warn(broken_intra_doc_links)]` on by default

warning: unresolved link to `std::process::Comman`
 --> link.rs:3:10
  |
3 | //! [a]: std::process::Comman
  |          ^^^^^^^^^^^^^^^^^^^^ no item named `Comman` in module `process`
```

File: src/librustdoc/html/markdown.rs [hunk 14]
```diff
@@ -1123,7 +1123,13 @@ crate fn plain_text_summary(md: &str) -> String {
     s
 }
 
-crate fn markdown_links(md: &str) -> Vec<(String, Range<usize>)> {
+pub struct MarkdownLink {
+    pub kind: LinkType,
+    pub link: String,
+    pub range: Range<usize>,
+}
```
Comment (jyn514) [inline src/librustdoc/html/markdown.rs:1130]: Please make this crate-private so we get warnings if it's unused.
```suggestion
crate struct MarkdownLink {
    pub kind: LinkType,
    pub link: String,
    pub range: Range<usize>,
}
```

File: src/test/rustdoc-ui/reference-link-reports-error-once.rs [hunk 15]
```diff
@@ -0,0 +1,20 @@
+#![deny(broken_intra_doc_links)]
+
+/// Links to [a] [link][a]
+/// And also a [third link][a]
+/// And also a [reference link][b]
+///
+/// Other links to the same target should still emit error: [ref] //~ERROR unresolved link to
```
Comment (jyn514) [inline src/test/rustdoc-ui/reference-link-reports-error-once.rs:7]: Can you include the text of the item that failed so this is easier to read?
```suggestion
/// Other links to the same target should still emit error: [ref] //~ERROR unresolved link to `ref`
```

File: src/test/rustdoc-ui/reference-link-reports-error-once.rs [hunk 16]
```diff
@@ -0,0 +1,20 @@
...
+/// Duplicate [ref] //~ERROR unresolved link to
```
Comment (jyn514) [inline src/test/rustdoc-ui/reference-link-reports-error-once.rs:8]:
```suggestion
/// Duplicate [ref] //~ERROR unresolved link to `ref`
```

File: src/test/rustdoc-ui/reference-link-reports-error-once.rs [hunk 17]
```diff
@@ -0,0 +1,20 @@
...
+///
+/// Other links to other targets should still emit error: [ref2] //~ERROR unresolved link to
```
Comment (jyn514) [inline src/test/rustdoc-ui/reference-link-reports-error-once.rs:10]:
```suggestion
/// Other links to other targets should still emit error: [ref2] //~ERROR unresolved link to `ref2`
```

File: src/test/rustdoc-ui/reference-link-reports-error-once.rs [hunk 18]
```diff
@@ -0,0 +1,20 @@
...
+/// Duplicate [ref2] //~ERROR unresolved link to
```
Comment (jyn514) [inline src/test/rustdoc-ui/reference-link-reports-error-once.rs:11]:
```suggestion
/// Duplicate [ref2] //~ERROR unresolved link to `ref2`
```

File: src/test/rustdoc-ui/reference-link-reports-error-once.rs [hunk 19]
```diff
@@ -0,0 +1,20 @@
...
+///
+/// [a]: ref
+//~^ ERROR unresolved link to
```
Comment (jyn514) [inline src/test/rustdoc-ui/reference-link-reports-error-once.rs:14]:
```suggestion
//~^ ERROR unresolved link to `ref`
```

**Review by jyn514 — APPROVED** [review]
r=me with the nits in the test case fixed. Thanks for sticking with this, I know it's been a journey :laughing:

**Comment by bugadani** [comment]
Sure thing! Want me to squash before merging?

**Comment by jyn514** [comment]
Sure, if you think it makes the git history more clear. My idea of 'more clear' is 'no commits that should have just been in the original' (e.g. fixing typos) and "don't have major rewrites of the same functionality".

**Comment by bugadani** [comment]
Makes sense.

@bors r=jyn514
