### PR TITLE
Fixes rustdoc in stage 0, stage 1

### LINKED ISSUE #52186: bootstrap: stage 0/1 doctests fail because of missing codegen backend
To reproduce, make sure you have an entirely clean checkout -- I did `rm -rf build/`. Then run
```
./x.py --incremental --stage 0 test src/libcore
```
This will go on for a while and ultimately fail with
```
    Finished release [optimized] target(s) in 40.58s
     Running build/x86_64-unknown-linux-gnu/stage0-std/x86_64-unknown-linux-gnu/release/deps/coretests-c81f2af9b50a498c

running 81 tests
.................................................................................
test result: ok. 81 passed; 0 failed; 0 ignored; 0 measured; 795 filtered out

   Doc-tests core
error: failed to find a `codegen-backends` folder in the sysroot candidates:
* /home/r/src/rust/rustc.2/build/x86_64-unknown-linux-gnu/stage0-tools/x86_64-unknown-linux-gnu
* /home/r/src/rust/rustc.2/build/x86_64-unknown-linux-gnu/stage0-sysroot/lib/rustlib/x86_64-unknown-linux-gnu
* /home/r/src/rust/rustc.2/build/x86_64-unknown-linux-gnu/stage0-sysroot

error: test failed, to rerun pass '--doc'


command did not execute successfully: "/home/r/src/rust/rustc.2/build/x86_64-unknown-linux-gnu/stage0/bin/cargo" "test" "--target" "x86_64-unknown-linux-gnu" "-j" "8" "--release" "--features" "panic-unwind jemalloc backtrace" "--manifest-path" "/home/r/src/rust/rustc.2/src/libstd/Cargo.toml" "-p" "core" "--" "slice" "--quiet"
expected success, got: exit code: 101
```

Notably, it doesn't seem to build LLVM at all -- which may be why it can't find a codegen-backend...

### PR DESCRIPTION
**Pull request by Mark-Simulacrum**
When a request for rustdoc is passed for stage 0, x.py build --stage 0
src/tools/rustdoc or ensure(tool::Rustdoc { .. }) with top_stage = 0, we
return the rustdoc for that compiler (i.e., the beta rustdoc).

This fixes stage 0 of https://github.com/rust-lang/rust/issues/52186 as well as being part of general workflow improvements (making stage 0 testing for std work) for rustbuild.

The stage 1 fix (second commit) completely resolves the problem, so this fixes https://github.com/rust-lang/rust/issues/52186.

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
cc @RalfJung

File: src/bootstrap/tool.rs [hunk 1]
```diff
@@ -418,25 +418,26 @@ impl Step for Rustdoc {
...
     fn run(self, builder: &Builder) -> PathBuf {
         let target_compiler = builder.compiler(builder.top_stage, self.host);
+        if target_compiler.stage == 0 {
+            if !target_compiler.is_snapshot(builder) {
+                panic!("rustdoc in stage 0 must be snapshot rustdoc");
+            }
+            return builder.initial_rustc.with_file_name(exe("rustdoc", &target_compiler.host));
+        }
         let target = target_compiler.host;
         let build_compiler = if target_compiler.stage == 0 {
```
Comment (alexcrichton) [inline src/bootstrap/tool.rs]: I think this clause is no longer necessary, right?

**Review by alexcrichton — COMMENTED** [review]
Looks good to me! Could the comments inside `fn rustdoc(...)` also be expanded to explain that the intention is that it returns a rustdoc paired with the rustc specified, not compiled with the rustc specified?

**Comment by Centril** [comment]
Adding space for rollup, @bors p=1

**Comment by o01eg** [comment]
Looks like it break https://github.com/rust-lang/rust/issues/52317 again.
