### PR TITLE
Remove suggestion from importing unstable items on stable channel

### LINKED ISSUE #149402: Don't suggest stuff (that doesn't really exist) from nightly when on stable
### Code

```Rust
fn foo() {
    let x = Vec::new();
    x.push(Complete::Item { name: "hello" });
}
```

### Current output

```Shell
Checking repro v0.1.0 (/home/pacak/tmp/repro)
error[E0433]: failed to resolve: use of undeclared type `Complete`
 --> src/lib.rs:3:12
  |
3 |     x.push(Complete::Item { name: "hello" });
  |            ^^^^^^^^ use of undeclared type `Complete`
  |
help: there is an enum variant `core::ops::CoroutineState::Complete` and 1 other; try using the variant's enum
  |
3 -     x.push(Complete::Item { name: "hello" });
3 +     x.push(core::ops::CoroutineState::Item { name: "hello" });
  |
3 -     x.push(Complete::Item { name: "hello" });
3 +     x.push(std::ops::CoroutineState::Item { name: "hello" });
  |
```

### Desired output

Don't mention `std::ops::CoroutineState` and give up much earlier? Take into account available enum variant names when making a suggestion?

### Rationale and extra context

I renamed enum `Complete` into `CompleteRequest`, on the next check `rustc` suggested me to use `std::ops::CoroutineState`. This is wrong for two reasons: 
1. I'm not using nightly so replacement won't work even if `CoroutineState::Item` existed
2. `CoroutineState::Item { name ... }` doesn't exist 

```rust
pub enum CoroutineState<Y, R> {
    Yielded(Y),
    Complete(R),
}
```

### Other cases

```Rust

```

### Rust Version

```Shell
rustc 1.91.1 (ed61e7d7e 2025-11-07)
binary: rustc
commit-hash: ed61e7d7e242494fb7057f2657300d9e77bb4fcb
commit-date: 2025-11-07
host: x86_64-unknown-linux-gnu
release: 1.91.1
LLVM version: 21.1.2
```

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by chenyukang**
Fixes rust-lang/rust#149402

### CODE REVIEW

File: tests/ui/resolve/suggest-unresolve-nightly-149402.rs [hunk 1]
```diff
@@ -0,0 +1,9 @@
+//@ only-nightly
```
Comment (fee1-dead) [inline tests/ui/resolve/suggest-unresolve-nightly-149402.rs]: Is it possible to use revisions here to avoid duplicating the same file?

**Review by fee1-dead — CHANGES_REQUESTED** [review]
r=me after addressing nit

*[View changes since this review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/rust/149440/cc3eee7fbe17ea4b7238531cb97e1b7b8bd6afce..5b003456246ad18d3141eb748d750f152f51194f)*

File: tests/ui/resolve/suggest-unresolve-nightly-149402.rs (hunk 1 above)
Comment (chenyukang) [reply tests/ui/resolve/suggest-unresolve-nightly-149402.rs]: thanks, fixed in https://github.com/rust-lang/rust/compare/5b003456246ad18d3141eb748d750f152f51194f..34c80e46389304d906fcb50efe4cf32a0270fab7

**Comment by jieyouxu** [comment]
Looks like the problem is that RUSTC_BOOTSTRAP's value now takes unconditional precedence over the `disable_unstable_features`.

https://github.com/rust-lang/rust/blob/34c80e46389304d906fcb50efe4cf32a0270fab7/compiler/rustc_feature/src/lib.rs#L66-L84

I might've regressed this in https://github.com/rust-lang/rust/pull/132993, I'll look into this.

**Comment by jhpratt** [comment]
@bors r-

https://github.com/rust-lang/rust/pull/151285#issuecomment-3765043686
