### PR TITLE
Anonymize binders in tail call sig

### LINKED ISSUE #144826: Can't explicit tail call with HRTB argument
I tried this code:

```rust
#![feature(explicit_tail_calls)]
#![expect(incomplete_features)]

fn foo(x: fn(&i32)) {
    become bar(x);
}

fn bar(_: fn(&i32)) {}
```

I expected the code to compile, but I got this error:

```
error: mismatched signatures
 --> src/lib.rs:5:5
  |
5 |     become bar(x);
  |     ^^^^^^^^^^^^^
  |
  = note: `become` requires caller and callee to have matching signatures
  = note: caller signature: `fn(for<'a> fn(&'a i32))`
  = note: callee signature: `fn(for<'a> fn(&'a i32))`
```

@rustbot labels +F-explicit_tail_calls +requires-incomplete-features

### Meta

Reproducible on the playground with version `1.90.0-nightly (2025-08-01 4b55fe199cfe9c710555)`

### PR DESCRIPTION
**Pull request by compiler-errors**
See the comment for explanation

Fixes rust-lang/rust#144826 

r? WaffleLapkin

### CODE REVIEW

File: compiler/rustc_mir_build/src/check_tail_calls.rs [hunk 1]
```diff
@@ -63,6 +63,10 @@ impl<'tcx> TailCallCkVisitor<'_, 'tcx> {
                 "`become` outside of functions should have been disallowed by hit_typeck"
```
Comment (lqd) [inline compiler/rustc_mir_build/src/check_tail_calls.rs]: (maybe while you're here)

```suggestion
                "`become` outside of functions should have been disallowed by hir_typeck"
```

File: tests/ui/explicit-tail-calls/higher-ranked-arg.rs [hunk 2]
```diff
@@ -0,0 +1,13 @@
+// Regression test for <https://github.com/rust-lang/rust/issues/144826>.
+//@ check-pass
+
+#![feature(explicit_tail_calls)]
+//~^ WARN the feature `explicit_tail_calls` is incomplete
```
Comment (lqd) [inline tests/ui/explicit-tail-calls/higher-ranked-arg.rs]: (while I'm here, maybe a little `#![allow(incomplete_features)]` to remove the unnecessary stderr?!)

Comment (compiler-errors) [reply tests/ui/explicit-tail-calls/higher-ranked-arg.rs]: I personally prefer the warn because it forces it being removed when the feature gets un-incomplete-ified

Comment (lqd) [reply tests/ui/explicit-tail-calls/higher-ranked-arg.rs]: Interesting.

Comment (WaffleLapkin) [reply tests/ui/explicit-tail-calls/higher-ranked-arg.rs]: All other tail call tests use `#![expect(incomplete_features)]`

**Review by WaffleLapkin — APPROVED** [review]
r=me with nits
