### PR TITLE
Recover from mutable variable declaration where `mut` is placed before `let`

### LINKED ISSUE #100197: Recover from mutable variable declaration where ```mut``` is placed before ```let```
Given the following code:

```rust
fn main() {
    mut let x = 123;
}
```

The current output is:

```
   Compiling playground v0.0.1 (/playground)
error: expected expression, found keyword `mut`
 --> src/main.rs:2:5
  |
2 |     mut let x = 123;
  |     ^^^ expected expression

error: could not compile `playground` due to previous error
```

Ideally the output should suggest to move the ```mut``` to behind the ```let```, since the current error message does not identify the problem accurately.

### PR DESCRIPTION
**Pull request by obeis**
Closes #100197

### CODE REVIEW

File: compiler/rustc_parse/src/parser/stmt.rs [hunk 1]
```diff
@@ -55,6 +55,19 @@ impl<'a> Parser<'a> {
             return Ok(Some(stmt.into_inner()));
         }
 
+        if self.token.is_keyword(kw::Mut) && self.is_keyword_ahead(1, &[kw::Let]) {
+            self.bump();
+            let mut_let_span = lo.to(self.token.span);
+            self.struct_span_err(mut_let_span, "invalid variable declaration")
+                .span_suggestion(
+                    mut_let_span,
+                    "move the `mut` to behind the `let`",
```
Comment (mcol) [inline compiler/rustc_parse/src/parser/stmt.rs:64]: Wouldn't "move the `mut` after the `let`" sound better?

Comment (obeis) [reply compiler/rustc_parse/src/parser/stmt.rs:64]: which message looks better?

Comment (Rageking8) [reply compiler/rustc_parse/src/parser/stmt.rs:64]: I think that the current "move the ```mut``` to behind the ```let```" is more clear, since  "move the ```mut``` after the ```let```" may mean to move the ```let``` first then move the ```mut``` (extremely slight ambiguity). But, the current phrasing can be improved but I can't think of a better one currently.

Comment (mcol) [reply compiler/rustc_parse/src/parser/stmt.rs:64]: An alternative to my proposal to address that potential ambiguity could be to use "move the `mut` right after the `let`".

For a different phrasing: "invert the order of `mut` and `let`".

Comment (Rageking8) [reply compiler/rustc_parse/src/parser/stmt.rs:64]: The different phrasing sound good, but I would prefer using "switch" instead of "invert".
