### PR TITLE
Use constraint span when lowering associated types

### LINKED ISSUE #63594: Incorrectly-/Un-spanned error with `type Out = Box<dyn Bar<Assoc: Copy>>;`
With the following, the error appears in the wrong place (1), while it should be at (2).

```rust
//~ ERROR the trait bound `std::string::String: std::marker::Copy` is not satisfied
// (1) --^

#![feature(associated_type_bounds)]

fn main() {}

trait Bar { type Assoc; }

trait Thing {
    type Out;
    fn func() -> Self::Out;
}

struct AssocNoCopy;
impl Bar for AssocNoCopy { type Assoc = String; }

impl Thing for AssocNoCopy {
    type Out = Box<dyn Bar<Assoc: Copy>>;

    fn func() -> Self::Out {
        Box::new(AssocNoCopy)
        //~^ ERROR the trait bound `std::string::String: std::marker::Copy` is not satisfied
        // (2) --^
    }
}
```

cc @alexreg @estebank @varkor

### PR DESCRIPTION
**Pull request by estebank**
Fix #63594.

r? @Centril

### CODE REVIEW

**Comment by estebank** [comment]
cc @alexreg

File: src/test/ui/associated-item/associated-item-type-issue-63594.rs [hunk 1]
```diff
@@ -0,0 +1,22 @@
+#![feature(associated_type_bounds)]
```
Comment (Centril) [inline src/test/ui/associated-item/associated-item-type-issue-63594.rs]:
```suggestion
// This test documents that `type Out = Box<dyn Bar<Assoc: Copy>>;`
// is allowed and will correctly reject an opaque `type Out` which
// does not satisfy the bound `<TheType as Bar>::Assoc: Copy`.
//
// FIXME(rust-lang/lang): I think this behavior is logical if we want to allow
// `dyn Trait<Assoc: Bound>` but we should decide if we want that. // Centril
//
// Additionally, as reported in https://github.com/rust-lang/rust/issues/63594,
// we check that the spans for the error message are sane here.

#![feature(associated_type_bounds)]
```

Also please move this file to `src/test/ui/associated-type-bounds/assoc-type-eq-with-dyn-atb-fail.rs` instead.

I already have this test in one of my branches (with that extra comment ^--) with the wrong spans but correct spans is not the main thing the tests is meant to test. ;)

File: src/librustc/hir/lowering.rs [hunk 2]
```diff
@@ -1095,15 +1095,15 @@ impl<'a> LoweringContext<'a> {
                         impl_trait_node_id,
                         DefPathData::ImplTrait,
                         ExpnId::root(),
-                        DUMMY_SP
+                        c.span,
```
Comment (Centril) [inline src/librustc/hir/lowering.rs]: Preexisting.... But, when reading this I felt it would have been easier to understand (at least the diff) if this was `constraint.span` or `assoc_ty_constraint.span` instead of a one letter name. Mind fixing also?

**Review by Centril — COMMENTED** [review]
Heh; didn't expect anyone to fix this before I had filed my tests (including the one added here) as a PR. =P

**Comment by Centril** [comment]
cc https://github.com/rust-lang/rust/issues/52662

**Comment by Centril** [comment]
r=me with changes ^---

**Comment by alexreg** [comment]
Thanks @estebank!
