### PR TITLE
Expand weak alias types before collecting constrained/referenced late bound regions + refactorings

### LINKED ISSUE #114220: lazy_type_alias: `return type references an anonymous lifetime, which is not constrained by the fn input types`
I tried this code:
`tests/ui/late-bound-lifetimes/late_bound_through_alias.rs` 
```rust
#![feature(lazy_type_alias)]
// check-pass

fn f(_: X) -> X {
    unimplemented!()
}

fn g<'a>(_: X<'a>) -> X<'a> {
    unimplemented!()
}

type X<'a> = &'a ();

fn main() {
    let _: for<'a> fn(X<'a>) -> X<'a> = g;
    let _: for<'a> fn(X<'a>) -> X<'a> = f;
}
```

without  `-Zcrate-attr=feature(lazy_type_alias)` : no warnings

with `-Zcrate-attr=feature(lazy_type_alias)`:

```
error[E0581]: return type references an anonymous lifetime, which is not constrained by the fn input types
 --> tests/ui/late-bound-lifetimes/late_bound_through_alias.rs:3:15
  |
3 | fn f(_: X) -> X {
  |               ^
  |
  = note: lifetimes appearing in an associated or opaque type are not considered constrained
  = note: consider introducing a named lifetime parameter

error[E0581]: return type references lifetime `'a`, which is not constrained by the fn input types
 --> tests/ui/late-bound-lifetimes/late_bound_through_alias.rs:7:23
  |
7 | fn g<'a>(_: X<'a>) -> X<'a> {
  |                       ^^^^^

error: aborting due to 2 previous errors

For more information about this error, try `rustc --explain E0581`.
```

````
rustc 1.73.0-nightly (04abc370b 2023-07-28)
binary: rustc
commit-hash: 04abc370b9f3855b28172b65a7f7d5a433f41412
commit-date: 2023-07-28
host: x86_64-unknown-linux-gnu
release: 1.73.0-nightly
LLVM version: 16.0.5
````

### PR DESCRIPTION
**Pull request by fmease**
Fixes #114220.
Follow-up to #120780.

r? @oli-obk

### CODE REVIEW

File: compiler/rustc_middle/src/ty/util.rs [hunk 1]
```diff
@@ -867,6 +868,63 @@ impl<'tcx> TyCtxt<'tcx> {
...
+    /// <div class="warning">
+    /// This delays a bug on overflow! Therefore you need to be certain that the
+    /// contained types get fully normalized at a later stage. Note that even on
+    /// overflow all well-behaved weak alias types get expanded correctly, so the
+    /// result is still useful.
+    /// </div>
+    ///
+    /// [weak]: ty::Weak
+    pub fn expand_weak_alias_tys<T: TypeFoldable<TyCtxt<'tcx>>>(self, value: T) -> T {
+        value.fold_with(&mut WeakAliasTypeExpander { tcx: self, depth: 0 })
```
Comment (fmease) [inline compiler/rustc_middle/src/ty/util.rs:893]: I wonder if need to track binders. I mean I didn't do that before either when I did the equivalent of `expand_weak_alias_tys` *inline* in an ad hoc fashion but yeah, feels weird to not track binders even though `instantiate` should take care of that (it does at least `shift_bound_vars`).

File: compiler/rustc_middle/src/ty/util.rs [hunk 2]
```diff
@@ -1002,6 +1060,42 @@ impl<'tcx> TypeFolder<TyCtxt<'tcx>> for OpaqueTypeExpander<'tcx> {
     }
 }
 
+struct WeakAliasTypeExpander<'tcx> {
+    tcx: TyCtxt<'tcx>,
+    depth: usize,
```
Comment (fmease) [inline compiler/rustc_middle/src/ty/util.rs:1065]: I'd like to note that I'm still using a plain depth counter over a hash set of `DefId`s to detect overflows since that feels more memory efficient to me.

File: compiler/rustc_middle/src/ty/util.rs [hunk 3]
```diff
@@ -1002,6 +1060,42 @@ impl<'tcx> TypeFolder<TyCtxt<'tcx>> for OpaqueTypeExpander<'tcx> {
...
+
+    fn fold_ty(&mut self, ty: Ty<'tcx>) -> Ty<'tcx> {
+        if !ty.has_type_flags(ty::TypeFlags::HAS_TY_WEAK) {
+            return ty;
+        }
+        let ty::Alias(ty::Weak, alias) = ty.kind() else {
+            return ty.super_fold_with(self);
+        };
+        if !self.tcx.recursion_limit().value_within_limit(self.depth) {
+            let guar = self.tcx.dcx().delayed_bug("overflow expanding weak alias type");
```
Comment (fmease) [inline compiler/rustc_middle/src/ty/util.rs:1081]: I'm still delaying a bug instead of reporting an overflow error since we don't have access to a `Span` and neither do all the callers of `expand_weak_alias_tys` and it would be a bit foolish to use a dummy span for this since it wouldn't get deduplicated with the other overflow errors and would actually show up in the user's stderr.

File: compiler/rustc_trait_selection/src/traits/normalize.rs [hunk 4]
```diff
@@ -355,8 +353,6 @@ impl<'a, 'b, 'tcx> TypeFolder<TyCtxt<'tcx>> for AssocTypeNormalizer<'a, 'b, 'tcx
 
                 let data = data.fold_with(self);
 
-                // FIXME(inherent_associated_types): Do we need to honor `self.eager_inference_replacement`
```
Comment (fmease) [inline compiler/rustc_trait_selection/src/traits/normalize.rs:358]: `eager_inference_replacement` no longer exists since #120463.

File: compiler/rustc_middle/src/ty/util.rs [hunk 5]
```diff
@@ -867,6 +868,63 @@ impl<'tcx> TyCtxt<'tcx> {
...
+    ///
+    /// [weak]: ty::Weak
+    pub fn expand_weak_alias_tys<T: TypeFoldable<TyCtxt<'tcx>>>(self, value: T) -> T {
+        value.fold_with(&mut WeakAliasTypeExpander { tcx: self, depth: 0 })
+    }
+
+    /// Peel off all [weak alias types] in this type until there are none left.
+    ///
+    /// This only expands weak alias types in “head” / outermost positions. It can
+    /// be used over [expand_weak_alias_tys] as an optimization in situations where
```
Comment (fmease) [inline compiler/rustc_middle/src/ty/util.rs:899]: “optimization modulo overflow behavior” I guess

File: compiler/rustc_middle/src/ty/util.rs (hunk 1 above)
Comment (oli-obk) [reply compiler/rustc_middle/src/ty/util.rs:893]: Binders do not matter here. You always instantiate the args from the same level, and you do not invoke the full projection normalizer at all.

File: compiler/rustc_middle/src/ty/visit.rs [hunk 6]
```diff
@@ -258,12 +260,8 @@ struct LateBoundRegionsCollector {
 }
 
 impl LateBoundRegionsCollector {
-    fn new(tcx: TyCtxt<'tcx>, just_constrained: bool) -> Self {
```
Comment (oli-obk) [inline compiler/rustc_middle/src/ty/visit.rs]: huh why did this not cause a lint?

**Comment by oli-obk** [comment]
Yea, I like the way this looks

File: compiler/rustc_middle/src/ty/visit.rs (hunk 6 above)
Comment (fmease) [reply compiler/rustc_middle/src/ty/visit.rs]: Ah because it turns out my commits weren't as cleanly separated as thought ^^' where an earlier commit adds this unused binding and a later one removes it again. Let me fix that real quick.

**Comment by fmease** [comment]
Fixing up the commit history
@bors r-
