### PR TITLE
Properly mark loop as diverging if it has no breaks

### LINKED ISSUE #128434: Awaiting a function returning a never type does not warn for unreachable code after the await
### Code

```Rust
pub async fn endless_async() -> ! {
    loop {
        tokio::time::sleep(tokio::time::Duration::from_secs(1)).await;
    }
}

pub async fn should_warn() {
    endless_async().await;
    println!("This code is unreachable");  // no warning about unreachable code
}

pub fn endless() -> ! {
    loop {
        std::thread::sleep(std::time::Duration::from_secs(1));
    }
}

pub fn warns() {
    endless();
    println!("This code is unreachable");  // warning: unreachable statement
}
```

### Current output

```Shell
warning: unreachable statement
  --> src/lib.rs:20:5
   |
19 |     endless();
   |     --------- any code following this expression is unreachable
20 |     println!("This code is unreachable");
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ unreachable statement
   |
   = note: `#[warn(unreachable_code)]` on by default
   = note: this warning originates in the macro `println` (in Nightly builds, run with -Z macro-backtrace for more info)
```

### Desired output

```Shell
warning: unreachable statement
  --> src/lib.rs:9:5
   |
 8 |     endless_async().await;
   |     --------------------- any code following this expression is unreachable
 9 |     println!("This code is unreachable");
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ unreachable statement
   |
   = note: `#[warn(unreachable_code)]` on by default
   = note: this warning originates in the macro `println` (in Nightly builds, run with -Z macro-backtrace for more info)
warning: unreachable statement
  --> src/lib.rs:20:5
   |
19 |     endless();
   |     --------- any code following this expression is unreachable
20 |     println!("This code is unreachable");
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ unreachable statement
   |
   = note: `#[warn(unreachable_code)]` on by default
   = note: this warning originates in the macro `println` (in Nightly builds, run with -Z macro-backtrace for more info)
```

### Rationale and extra context

_No response_

### Other cases

_No response_

### Rust Version

```Shell
rustc 1.80.0 (051478957 2024-07-21)
binary: rustc
commit-hash: 051478957371ee0084a7c0913941d2a8c4757bb9
commit-date: 2024-07-21
host: x86_64-unknown-linux-gnu
release: 1.80.0
LLVM version: 18.1.7
```

### Anything else?

Same behaviour with the current nightly version:
```
rustc 1.82.0-nightly (f8060d282 2024-07-30)
binary: rustc
commit-hash: f8060d282d42770fadd73905e3eefb85660d3278
commit-date: 2024-07-30
host: x86_64-unknown-linux-gnu
release: 1.82.0-nightly
LLVM version: 18.1.7
```

### PR DESCRIPTION
**Pull request by compiler-errors**
Due to specifics about the desugaring of the `.await` operator, HIR typeck doesn't recognize that `.await`ing an `impl Future<Output = !>` will diverge in the same way as calling a `fn() -> !`.

This is because the await operator desugars to approximately:

```rust
loop {
    match future.poll(...) {
        Poll::Ready(x) => break x,
        Poll::Pending => {}
    }
}
```

We know that the value of `x` is `!`, however since `break` is a coercion site, we coerce `!` to some `?0` (the type of the loop expression). Then since the type of the `loop {...}` expression is `?0`, we will not detect the loop as diverging like we do with other expressions that evaluate to `!`:

https://github.com/rust-lang/rust/blob/0b5eb7ba7bd796fb39c8bb6acd9ef6c140f28b65/compiler/rustc_hir_typeck/src/expr.rs#L240-L243

We can technically fix this in two ways:
1. Make coercion of loop exprs more eagerly result in a type of `!` when the only break expressions have type `!`.
2. Make loops understand that if they have only diverging break values, then the loop diverges as well.

(1.) likely has negative effects on inference, and seems like a weird special case to drill into coercion. However, it turns out that (2.) is very easy to implement, we already record whether a loop has any break expressions, and when we do so, we actually skip over any break expressions with diverging values!:

https://github.com/rust-lang/rust/blob/0b5eb7ba7bd796fb39c8bb6acd9ef6c140f28b65/compiler/rustc_hir_typeck/src/expr.rs#L713-L716

Thus, we can consider the loop as diverging if we see that it has no breaks, which is the change implemented in this PR.

This is not usually a problem in regular code for two reasons:
1. In regular code, we already mark `break diverging()` as unreachable if `diverging()` is unreachable. We don't do this for `.await`, since we suppress unreachable errors within `.await` (#64930). Un-suppressing this code will result in spurious unreachable expression errors pointing to internal await machinery.
3. In loops that truly have no breaks (e.g. `loop {}`), we already evaluate the type of the loop to `!`, so this special case is kinda moot. This only affects loops that have `break`s with values of type `!`.

Thus, this seems like a change that may affect more code than just `.await`, but it likely does not in meaningful ways; if it does, it's certainly correct to apply.

Fixes #128434

### CODE REVIEW

File: compiler/rustc_hir_typeck/src/fn_ctxt/_impl.rs [hunk 1]
```diff
@@ -48,30 +48,42 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
     /// Produces warning on the given node, if the current point in the
     /// function is unreachable, and there hasn't been another warning.
     pub(crate) fn warn_if_unreachable(&self, id: HirId, span: Span, kind: &str) {
```
Comment (compiler-errors) [inline compiler/rustc_hir_typeck/src/fn_ctxt/_impl.rs:50]: I rewrote this method to split up the 3 special cases. No functional changes other than:

```
orig_span.is_desugaring(DesugaringKind::Await)
```

to 

```
span.is_desugaring(DesugaringKind::Await)
```

Since the former suppresses any unreachable warnings originating *from* an await, but we actually want to suppress any unreachable warnings that occur *within* an await.

**Review by fmease — APPROVED** [review]
Very well-written explanation, thanks!

**Comment by compiler-errors** [comment]
I consider this to be strictly a bugfix, and therefore deserves no team approval, but I do think that it's worth mentioning in the relnotes just in case a crate maintainer notices that `f().await` now marks subsequent statements as unused due to more accurately tracking divergence.

@rustbot label +relnotes

**Comment by Kobzol** [comment]
@rust-timer build ffc0e2e4daf197adc9794a3635ffa2e29f1997ac

**Comment by compiler-errors** [comment]
?????????????????

**Comment by compiler-errors** [comment]
Oh wait, I probably know what caused it. I changed the `warn_if_unreachable` function.

**Comment by Kobzol** [comment]
Seems like a bit more time is spent in typeck. Not sure if this was expected, but this seems like a correctness fix, and the regression in primary benchmarks is only in check builds, so nothing that terrible. If you have any ideas how to fix, would be nice to send a PR, otherwise we can probably let it slide.
