### PR TITLE
CFI: Fix error compiling core with LLVM CFI enabled

### LINKED ISSUE #90546: Error compiling `core` with LLVM CFI enabled
### Code

```Rust
fn main() {
    println!("Hello, world!");
}
```

### Meta

`rustc --version --verbose`:
```
rustc 1.58.0-nightly (db062de72 2021-11-01)
binary: rustc
commit-hash: db062de72b0a064f45b6f86894cbdc7c0ec68844
commit-date: 2021-11-01
host: x86_64-unknown-linux-gnu
release: 1.58.0-nightly
LLVM version: 13.0.0
```

### Error output

`~/hello-rust$ RUSTFLAGS="-Cembed-bitcode -Clto -Zsanitizer=cfi" RUSTDOCFLAGS="-Cembed-bitcode -Clto -Zsanitizer=cfi" cargo run -Zbuild-std --target x86_64-unknown-linux-gnu`
```
    Updating crates.io index
  Downloaded addr2line v0.16.0
  Downloaded cc v1.0.69
  Downloaded cfg-if v0.1.10
  Downloaded unicode-width v0.1.8
  Downloaded adler v0.2.3
  Downloaded compiler_builtins v0.1.49
  Downloaded getopts v0.2.21
  Downloaded rustc-demangle v0.1.21
  Downloaded hashbrown v0.11.0
  Downloaded miniz_oxide v0.4.0
  Downloaded object v0.26.2
  Downloaded memchr v2.4.1
  Downloaded libc v0.2.103
  Downloaded gimli v0.25.0
  Downloaded 14 crates (2.0 MB) in 0.68s
   Compiling compiler_builtins v0.1.49
   Compiling core v0.0.0 (/home/rcvalle/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core)
   Compiling libc v0.2.103
   Compiling cc v1.0.69
   Compiling memchr v2.4.1
   Compiling std v0.0.0 (/home/rcvalle/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std)
   Compiling unwind v0.0.0 (/home/rcvalle/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/unwind)
   Compiling rustc-std-workspace-core v1.99.0 (/home/rcvalle/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/rustc-std-workspace-core)
/home/rcvalle/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/../lib/librustc_driver-5edcf0e336ae6d33.so(+0x4c9083)[0x7fb24e347083]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x138e0)[0x7fb24dae68e0]
/home/rcvalle/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/../lib/../lib/libLLVM-13-rust-1.58.0-nightly.so(+0x3520633)[0x7fb24c11b633]
/home/rcvalle/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/../lib/../lib/libLLVM-13-rust-1.58.0-nightly.so(+0x351a701)[0x7fb24c115701]
/home/rcvalle/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/../lib/../lib/libLLVM-13-rust-1.58.0-nightly.so(+0x275552f)[0x7fb24b35052f]
/home/rcvalle/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/../lib/../lib/libLLVM-13-rust-1.58.0-nightly.so(+0x274d4b4)[0x7fb24b3484b4]
/home/rcvalle/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/../lib/../lib/libLLVM-13-rust-1.58.0-nightly.so(_ZN4llvm12SelectionDAG13LegalizeTypesEv+0x33c)[0x7fb24b3422bc]
/home/rcvalle/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/../lib/../lib/libLLVM-13-rust-1.58.0-nightly.so(_ZN4llvm16SelectionDAGISel17CodeGenAndEmitDAGEv+0x80)[0x7fb24b340610]
/home/rcvalle/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/../lib/../lib/libLLVM-13-rust-1.58.0-nightly.so(_ZN4llvm16SelectionDAGISel20SelectAllBasicBlocksERKNS_8FunctionE+0x271c)[0x7fb24b32477c]
/home/rcvalle/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/../lib/../lib/libLLVM-13-rust-1.58.0-nightly.so(_ZN4llvm16SelectionDAGISel20runOnMachineFunctionERNS_15MachineFunctionE+0x4f2)[0x7fb24b31c3e2]
/home/rcvalle/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/../lib/../lib/libLLVM-13-rust-1.58.0-nightly.so(+0x2720ed8)[0x7fb24b31bed8]
/home/rcvalle/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/../lib/../lib/libLLVM-13-rust-1.58.0-nightly.so(_ZN4llvm19MachineFunctionPass13runOnFunctionERNS_8FunctionE+0xaa)[0x7fb24b8f6e1a]
/home/rcvalle/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/../lib/../lib/libLLVM-13-rust-1.58.0-nightly.so(_ZN4llvm13FPPassManager13runOnFunctionERNS_8FunctionE+0x6c7)[0x7fb24b7adf27]
/home/rcvalle/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/../lib/../lib/libLLVM-13-rust-1.58.0-nightly.so(_ZN4llvm13FPPassManager11runOnModuleERNS_6ModuleE+0x2f)[0x7fb24b7ad83f]
/home/rcvalle/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/../lib/../lib/libLLVM-13-rust-1.58.0-nightly.so(_ZN4llvm6legacy15PassManagerImpl3runERNS_6ModuleE+0x289)[0x7fb24bb91219]
/home/rcvalle/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/../lib/librustc_driver-5edcf0e336ae6d33.so(+0x23f5004)[0x7fb250273004]
/home/rcvalle/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/../lib/librustc_driver-5edcf0e336ae6d33.so(+0x23efd5f)[0x7fb25026dd5f]
/home/rcvalle/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/../lib/librustc_driver-5edcf0e336ae6d33.so(+0x23f2960)[0x7fb250270960]
/home/rcvalle/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/../lib/librustc_driver-5edcf0e336ae6d33.so(+0x238526b)[0x7fb25020326b]
/home/rcvalle/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/../lib/librustc_driver-5edcf0e336ae6d33.so(+0x237f8ab)[0x7fb2501fd8ab]
/home/rcvalle/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/../lib/librustc_driver-5edcf0e336ae6d33.so(+0x23c469c)[0x7fb25024269c]
/home/rcvalle/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/../lib/librustc_driver-5edcf0e336ae6d33.so(+0x23d899c)[0x7fb25025699c]
/home/rcvalle/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/../lib/libstd-8adcca4f1427867b.so(rust_metadata_std_fcea40badc263c8f+0xa9513)[0x7fb24dbb8513]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x8eae)[0x7fb24dadbeae]
/lib/x86_64-linux-gnu/libc.so.6(clone+0x3f)[0x7fb24d9f8a5f]
error: could not compile `core`

Caused by:
  process didn't exit successfully: `rustc --crate-name core --edition=2018 /home/rcvalle/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts --crate-type lib --emit=dep-info,metadata,link -C embed-bitcode=no -C debuginfo=2 -C metadata=46c7ed8bd3462e72 -C extra-filename=-46c7ed8bd3462e72 --out-dir /home/rcvalle/hello-rust/target/x86_64-unknown-linux-gnu/debug/deps --target x86_64-unknown-linux-gnu -Z force-unstable-if-unmarked -L dependency=/home/rcvalle/hello-rust/target/x86_64-unknown-linux-gnu/debug/deps -L dependency=/home/rcvalle/hello-rust/target/debug/deps --cap-lints allow -Cembed-bitcode -Clto -Zsanitizer=cfi` (signal: 11, SIGSEGV: invalid memory reference)
warning: build failed, waiting for other jobs to finish...
error: build failed
```

<details><summary><strong>Backtrace</strong></summary>
<p>

`RUSTFLAGS="-Cembed-bitcode -Clto -Zsanitizer=cfi" RUSTDOCFLAGS="-Cembed-bitcode -Clto -Zsanitizer=cfi" RUST_BACKTRACE="1" cargo run -Zbuild-std --target x86_64-unknown-linux-gnu`
```
   Compiling core v0.0.0 (/home/rcvalle/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core)
   Compiling rustc-std-workspace-core v1.99.0 (/home/rcvalle/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/rustc-std-workspace-core)
   Compiling compiler_builtins v0.1.49
   Compiling libc v0.2.103
/home/rcvalle/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/../lib/librustc_driver-5edcf0e336ae6d33.so(+0x4c9083)[0x7fa21a33b083]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x138e0)[0x7fa219ada8e0]
/home/rcvalle/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/../lib/../lib/libLLVM-13-rust-1.58.0-nightly.so(+0x3520633)[0x7fa21810f633]
/home/rcvalle/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/../lib/../lib/libLLVM-13-rust-1.58.0-nightly.so(+0x351a701)[0x7fa218109701]
/home/rcvalle/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/../lib/../lib/libLLVM-13-rust-1.58.0-nightly.so(+0x275552f)[0x7fa21734452f]
/home/rcvalle/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/../lib/../lib/libLLVM-13-rust-1.58.0-nightly.so(+0x274d4b4)[0x7fa21733c4b4]
/home/rcvalle/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/../lib/../lib/libLLVM-13-rust-1.58.0-nightly.so(_ZN4llvm12SelectionDAG13LegalizeTypesEv+0x33c)[0x7fa2173362bc]
/home/rcvalle/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/../lib/../lib/libLLVM-13-rust-1.58.0-nightly.so(_ZN4llvm16SelectionDAGISel17CodeGenAndEmitDAGEv+0x80)[0x7fa217334610]
/home/rcvalle/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/../lib/../lib/libLLVM-13-rust-1.58.0-nightly.so(_ZN4llvm16SelectionDAGISel20SelectAllBasicBlocksERKNS_8FunctionE+0x271c)[0x7fa21731877c]
/home/rcvalle/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/../lib/../lib/libLLVM-13-rust-1.58.0-nightly.so(_ZN4llvm16SelectionDAGISel20runOnMachineFunctionERNS_15MachineFunctionE+0x4f2)[0x7fa2173103e2]
/home/rcvalle/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/../lib/../lib/libLLVM-13-rust-1.58.0-nightly.so(+0x2720ed8)[0x7fa21730fed8]
/home/rcvalle/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/../lib/../lib/libLLVM-13-rust-1.58.0-nightly.so(_ZN4llvm19MachineFunctionPass13runOnFunctionERNS_8FunctionE+0xaa)[0x7fa2178eae1a]
/home/rcvalle/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/../lib/../lib/libLLVM-13-rust-1.58.0-nightly.so(_ZN4llvm13FPPassManager13runOnFunctionERNS_8FunctionE+0x6c7)[0x7fa2177a1f27]
/home/rcvalle/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/../lib/../lib/libLLVM-13-rust-1.58.0-nightly.so(_ZN4llvm13FPPassManager11runOnModuleERNS_6ModuleE+0x2f)[0x7fa2177a183f]
/home/rcvalle/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/../lib/../lib/libLLVM-13-rust-1.58.0-nightly.so(_ZN4llvm6legacy15PassManagerImpl3runERNS_6ModuleE+0x289)[0x7fa217b85219]
/home/rcvalle/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/../lib/librustc_driver-5edcf0e336ae6d33.so(+0x23f5004)[0x7fa21c267004]
/home/rcvalle/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/../lib/librustc_driver-5edcf0e336ae6d33.so(+0x23efd5f)[0x7fa21c261d5f]
/home/rcvalle/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/../lib/librustc_driver-5edcf0e336ae6d33.so(+0x23f2960)[0x7fa21c264960]
/home/rcvalle/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/../lib/librustc_driver-5edcf0e336ae6d33.so(+0x238526b)[0x7fa21c1f726b]
/home/rcvalle/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/../lib/librustc_driver-5edcf0e336ae6d33.so(+0x237f8ab)[0x7fa21c1f18ab]
/home/rcvalle/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/../lib/librustc_driver-5edcf0e336ae6d33.so(+0x23c469c)[0x7fa21c23669c]
/home/rcvalle/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/../lib/librustc_driver-5edcf0e336ae6d33.so(+0x23d899c)[0x7fa21c24a99c]
/home/rcvalle/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/../lib/libstd-8adcca4f1427867b.so(rust_metadata_std_fcea40badc263c8f+0xa9513)[0x7fa219bac513]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x8eae)[0x7fa219acfeae]
/lib/x86_64-linux-gnu/libc.so.6(clone+0x3f)[0x7fa2199eca5f]
error: could not compile `core`

Caused by:
  process didn't exit successfully: `rustc --crate-name core --edition=2018 /home/rcvalle/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts --crate-type lib --emit=dep-info,metadata,link -C embed-bitcode=no -C debuginfo=2 -C metadata=46c7ed8bd3462e72 -C extra-filename=-46c7ed8bd3462e72 --out-dir /home/rcvalle/hello-rust/target/x86_64-unknown-linux-gnu/debug/deps --target x86_64-unknown-linux-gnu -Z force-unstable-if-unmarked -L dependency=/home/rcvalle/hello-rust/target/x86_64-unknown-linux-gnu/debug/deps -L dependency=/home/rcvalle/hello-rust/target/debug/deps --cap-lints allow -Cembed-bitcode -Clto -Zsanitizer=cfi` (signal: 11, SIGSEGV: invalid memory reference)
warning: build failed, waiting for other jobs to finish...
error: build failed
```

</p>
</details>

### PR DESCRIPTION
**Pull request by rcvalle**
Fix #90546 by filtering out global value function pointer types from the type tests, and adding the LowerTypeTests pass to the rustc LTO optimization pipelines.

### CODE REVIEW

File: compiler/rustc_llvm/llvm-wrapper/RustWrapper.cpp [hunk 1]
```diff
@@ -1952,3 +1952,14 @@ extern "C" int32_t LLVMRustGetElementTypeArgIndex(LLVMValueRef CallSite) {
...
   return identify_magic(StringRef(ptr, len)) == file_magic::bitcode;
 }
+
+extern "C" bool LLVMRustIsNonGVFunctionPointerTy(LLVMValueRef V) {
+  if (unwrap<Value>(V)->getType()->isPointerTy()) {
+    if (auto *GV = dyn_cast<GlobalValue>(unwrap<Value>(V))) {
+      if (GV->getValueType()->isFunctionTy())
+        return false;
+    }
+    return true;
```
Comment (wesleywiser) [inline compiler/rustc_llvm/llvm-wrapper/RustWrapper.cpp:1962]: Should the `return true` be moved up one line? The name of this function is also a little confusing to me. The behavior seems to be "true for any pointer type except pointers to functions" and the name reads to me like it's the opposite of that.

File: compiler/rustc_codegen_llvm/src/builder.rs [hunk 2]
```diff
@@ -1563,25 +1563,27 @@ impl<'a, 'll, 'tcx> Builder<'a, 'll, 'tcx> {
...
     ) -> Option<llvm::OperandBundleDef<'ll>> {
-        let is_indirect_call = unsafe { llvm::LLVMIsAFunction(llfn).is_none() };
-        let kcfi_bundle = if is_indirect_call && self.tcx.sess.is_sanitizer_kcfi_enabled() {
-            if fn_attrs.is_some() && fn_attrs.unwrap().no_sanitize.contains(SanitizerSet::KCFI) {
-                return None;
-            }
+        let is_indirect_call = unsafe { llvm::LLVMRustIsNonGVFunctionPointerTy(llfn) };
+        let kcfi_bundle =
+            if is_indirect_call && fn_abi.is_some() && self.tcx.sess.is_sanitizer_kcfi_enabled() {
+                if fn_attrs.is_some() && fn_attrs.unwrap().no_sanitize.contains(SanitizerSet::KCFI)
```
Comment (wesleywiser) [inline compiler/rustc_codegen_llvm/src/builder.rs:1569]: Nit: using `if let Some(fn_abi) = fn_abi` and `if let Some(fn_attrs) = fn_attrs` might be cleaner as you can avoid the later unwraps. Feel free to ignore.

File: compiler/rustc_session/src/session.rs [hunk 3]
```diff
@@ -1623,6 +1623,14 @@ fn validate_commandline_args_with_session_available(sess: &Session) {
         sess.emit_err(errors::SanitizerCfiRequiresLto);
     }
 
+    // LLVM CFI using rustc LTO requires a single codegen unit.
```
[the remark this answers is not in the document]
Comment (rcvalle) [reply compiler/rustc_session/src/session.rs:1626]: The LowerTypeTests pass (which replaces calls to the llvm.type.test intrinsic with code to test type membership) needs full program visibility. Unfortunately, with rustc LTO, it currently doesn't seem to have full program visibility with multiple CGUs.

File: tests/ui/lto/issue-100772.rs [hunk 4]
```diff
@@ -1,6 +1,6 @@
-// run-pass
+// build-pass
```
[the remark this answers is not in the document]
Comment (rcvalle) [reply tests/ui/lto/issue-100772.rs:1]: These tests are for build-time bugs/regressions only, and haven't looked at it in more detail, but the way the test harness is built and implemented doesn't seem to be compatible with CFI, so I just changed them to build-pass. Let me know if it looks good to you.

File: compiler/rustc_llvm/llvm-wrapper/RustWrapper.cpp (hunk 1 above)
Comment (rcvalle) [reply compiler/rustc_llvm/llvm-wrapper/RustWrapper.cpp:1962]: This function tests if a LLVM value is of pointer type and its value isn't a _global value_ function type (i.e., it returns true if it is (a) a pointer type and (b) its value is not a _global value_ function type). We're only interested in  indirect branch targets (i.e., targets that are not known at code generation). Does it make sense to you?

File: compiler/rustc_session/src/session.rs (hunk 3 above)
[the remark this answers is not in the document]
Comment (wesleywiser) [reply compiler/rustc_session/src/session.rs:1626]: Hmm how does this work when you have multiple crates then? I guess this requires LLVM bitcode to be embedded in dependencies and fat LTO to be enabled in order to get full program visibility? 

Oh I see the previous check validates that. I guess that answers my question then 🙂

File: compiler/rustc_llvm/llvm-wrapper/RustWrapper.cpp (hunk 1 above)
Comment (wesleywiser) [reply compiler/rustc_llvm/llvm-wrapper/RustWrapper.cpp:1962]: I guess I'm not sure what the difference between a "global value function type" and a "function pointer" is. Could you explain that more? Is this the difference between a pointer to a specific function vs a pointer an arbitrary function?

File: compiler/rustc_codegen_llvm/src/builder.rs (hunk 2 above)
Comment (rcvalle) [reply compiler/rustc_codegen_llvm/src/builder.rs]: Changed. Thank you! :)

File: compiler/rustc_session/src/session.rs (hunk 3 above)
[the remark this answers is not in the document]
Comment (rcvalle) [reply compiler/rustc_session/src/session.rs:1624]: Yes, that is correct (i.e., it requires the last bullet of https://doc.rust-lang.org/rustc/codegen-options/index.html#lto for when `-Clto` is specified: "`codegen-units=1` + lto: 1 codegen unit, fat LTO across crates."). It also requires `-Z build-std` so the standard library is also rebuilt with CFI enabled, which is what this PR fixes. However, unfortunately CFI currently doesn't work with rustc thin and local thin LTO (see #111183), which I'll also add in the comment below.

File: compiler/rustc_llvm/llvm-wrapper/RustWrapper.cpp (hunk 1 above)
Comment (rcvalle) [reply compiler/rustc_llvm/llvm-wrapper/RustWrapper.cpp:1962]: A LLVM value of pointer type where its value is a *global value* function type as a branch target means that the target destination (address) is known at code generation, resulting in a direct branch, and also causing the error you see in #90546 when used as an argument to the llvm.type.test. Does it make sense?

**Review by wesleywiser — APPROVED** [review]

**Comment by wesleywiser** [comment]
Thanks @rcvalle!

@bors r+ rollup
