### PR TITLE
fix testing Miri with --stage 0

### LINKED ISSUE #78778: error_index_generator stage 0 tests don't work with download-ci-llvm: "error while loading shared libraries: libLLVM-11-rust-1.49.0-nightly.so"
```
command did not execute successfully: "/home/joshua/rustc/build/x86_64-unknown-linux-gnu/stage0-tools-bin/error_index_generator" "markdown" "/home/joshua/rustc/build/x86_64-unknown-linux-gnu/test/error-index.md"
expected success, got: exit code: 127

stdout ----

stderr ----
/home/joshua/rustc/build/x86_64-unknown-linux-gnu/stage0-tools-bin/error_index_generator: error while loading shared libraries: libLLVM-11-rust-1.49.0-nightly.so: cannot open shared object file: No such file or directory

failed to run: /home/joshua/rustc/build/bootstrap/debug/bootstrap test --stage 0 src/tools/error_index_generator/
```

### PR DESCRIPTION
**Pull request by RalfJung**
Fixes https://github.com/rust-lang/rust/issues/78778 for Miri.

The issue remains open for error_index_generator, which has its own dylib logic:
https://github.com/rust-lang/rust/blob/903e369c831d52726a5292f847e384622189d9a0/src/bootstrap/tool.rs#L396-L400
@jyn514 I could just copy the logic from `add_rustc_lib_path`, but that does not seem great. Any other suggestions?

Also I wonder if maybe `prepare_tool_cargo` should already call `add_rustc_lib_path`.

### CODE REVIEW

**Comment by RalfJung** [comment]
@bors rollup=iffy
because bootstrap

File: src/bootstrap/util.rs [hunk 1]
```diff
@@ -45,6 +45,7 @@ pub fn libdir(target: TargetSelection) -> &'static str {
 }
 
 /// Adds a list of lookup paths to `cmd`'s dynamic library lookup path.
+/// If The dylib_path_par is already set for this cmd, the old value will be overwritten!
```
Comment (jyn514) [inline src/bootstrap/util.rs:48]: Can we fix it to not do this? Overwriting the old value seems very confusing.

**Review by jyn514 — COMMENTED** [review]
> @jyn514 I could just copy the logic from add_rustc_lib_path, but that does not seem great. Any other suggestions?

I don't have time to look into it now, but there's a whole mess of things I tried to do to fix it in https://github.com/rust-lang/rust/pull/84776

File: src/bootstrap/util.rs (hunk 1 above)
Comment (RalfJung) [reply src/bootstrap/util.rs:48]: (a) this is pre-existing, I'd rather not touch this since I have no idea what changing this will break,
(b) it requires an unstable feature (https://github.com/rust-lang/rust/issues/44434), which AFAIK bootstrap tries to avoid.

**Comment by RalfJung** [comment]
> I don't have time to look into it now, but there's a whole mess of things I tried to do to fix it in #84776

Okay, so it seems reasonable then to ignore error_index_generator for this PR, I would say.

The main question that remains is if `prepare_tool_cargo` should call `add_rustc_lib_path`, or if we better leave that control to the individual tools.

**Comment by Mark-Simulacrum** [comment]
IMO this is probably fine -- it *should* be ok to have more libraries in the search path, generally speaking, especially for tools which aren't generally linked dynamically (other than to rustc/llvm, and then we just need these libraries in the search path).

So I think this PR is good if it works -- r=me if we've tested that.

**Comment by RalfJung** [comment]
> IMO this is probably fine -- it should be ok to have more libraries in the search path, generally speaking, especially for tools which aren't generally linked dynamically (other than to rustc/llvm, and then we just need these libraries in the search path).

I can't tell if "this" is what the PR does, or the proposal of calling `add_rustc_lib_path` already in `prepare_tool_cargo`.

> So I think this PR is good if it works -- r=me if we've tested that.

What kind of tests are you thinking of? I did verify that `./x.py test src/tools/miri --stage 0` passes with this PR as-is.

**Comment by Mark-Simulacrum** [comment]
Oh, I see -- yeah, this PR as is, or the more invasive patch both seem OK.

That verification seems sufficient for now. I'm not entirely sure this is correct but it does seem like the appropriate start.

@bors r+
