### PR TITLE
re-add --disable-minification to rustdoc

### LINKED ISSUE #135345: using symlinks in rustdoc-js tests static.files to bypass minification causes writes through symlinks, minifying orignal files
with the removal of `--disable-minification`, i was under the impression that the reccommended workflow is to symlink files in the `static.files` directory to their origin locations.

this workaround works completly fine when used on regular docs, however, it causes serious problems when trying to use it for the `static.files` in the `rustdoc-js` dirs.

reproduction steps:
1. ` rm -r build/host/test/rustdoc-js`
2. `./x test --stage 1 tests/rustdoc-js/type-parameters.rs` (any unit test should work)
3. `ln -f src/librustdoc/html/static/js/search.js build/host/test/rustdoc-js/type-parameters/static.files/search-*.js`
4. `./x test --stage 1 tests/rustdoc-js/type-parameters.rs` (again)

this will result in `src/librustdoc/html/static/js/search.js` becoming minified.

personally i think we should just bring back the `--disable-minification` option as perma-unstable.  that or we should have a canonical implementation of this symlink hack integrated into bootstrap.

### PR DESCRIPTION
**Pull request by lolbinarycat**
this also makes the rust.docs-minification option work as advertised in config.toml

nothing fancy this time, this is intended to be perma-unstable. it's only really here for the benefit of rustdoc devs.

mitegates https://github.com/rust-lang/rust/issues/135345

It was removed in https://github.com/rust-lang/rust/commit/f9e1f6ffdf03ec33cb29e20c88fc7bcc938c7f42.

### CODE REVIEW

**Review by notriddle — APPROVED** [review]

File: src/librustdoc/lib.rs [hunk 1]
```diff
@@ -651,8 +651,15 @@ fn opts() -> Vec<RustcOptGroup> {
             "",
             "add arguments to be used when compiling doctests",
         ),
+        opt(
+            Unstable,
+            FlagMulti,
+            "",
+            "disable-minification",
+            "diable the minification of CSS/JS files",
```
Comment (GuillaumeGomez) [inline src/librustdoc/lib.rs:659]:
```suggestion
            "disable the minification of CSS/JS files",
```

**Comment by GuillaumeGomez** [comment]
The rustdoc team discussed about it in the last [zulip meeting](https://rust-lang.zulipchat.com/#narrow/channel/393423-t-rustdoc.2Fmeetings/topic/2025-01-13) and agreed with this re-add.

One thing though: please add a disclaimer to the flag help message to mention it's perma unstable.

**Comment by lolbinarycat** [comment]
yeah, and the disclaimer should also say that it shouldn't be used with services that cache, like docs.rs
