### PR TITLE
Suggest wapping expr in parentheses on invalid unary negation

### LINKED ISSUE #88701: diagnostics when parsing `{ {10} - 1 }` is confusing
Given the following [code](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=291d09b9657643097c2214cc6c5348fe):

```rust
#![allow(unused_braces)]

fn main() {
    let _: usize = { {10} - 1 };
}
```

The current output is:

```
error[E0308]: mismatched types
 --> src/main.rs:4:23
  |
4 |     let _: usize = { {10} - 1 };
  |                       ^^ expected `()`, found integer

error[E0600]: cannot apply unary operator `-` to type `usize`
 --> src/main.rs:4:27
  |
4 |     let _: usize = { {10} - 1 };
  |                           ^^^
  |                           |
  |                           cannot apply unary operator `-`
  |                           help: you may have meant the maximum value of `usize`: `usize::MAX`
  |
  = note: unsigned values cannot be negated
```

Ideally this would give the same diagnostics as `{10} + 1` gives:
```
error: expected expression, found `+`
 --> src/main.rs:4:27
  |
4 |     let _: usize = { {10} + 1 };
  |                           ^ expected expression
  |
help: parentheses are required to parse this as an expression
  |
4 |     let _: usize = { ({10}) + 1 };
  |                      +    +

error[E0308]: mismatched types
 --> src/main.rs:4:23
  |
4 |     let _: usize = { {10} + 1 };
  |                       ^^ expected `()`, found integer
```

### PR DESCRIPTION
**Pull request by andrewhickman**
Fixes #88701

### CODE REVIEW

File: compiler/rustc_typeck/src/check/op.rs [hunk 1]
```diff
@@ -680,42 +680,50 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
...
-                                    &format!(
-                                        "you may have meant the maximum value of `{}`",
-                                        actual
-                                    ),
-                                    format!("{}::MAX", actual),
-                                    Applicability::MaybeIncorrect,
-                                );
+
+                    let sp = self.tcx.sess.source_map().start_point(ex.span);
+                    if let Some(sp) =
```
Comment (jackh726) [inline compiler/rustc_typeck/src/check/op.rs:685]: Can you add a comment here? Just a brief explanation of what we're doing and a reference to the test?

**Review by jackh726 — APPROVED** [review]
Just would like a comment and this is LGTM. It would be nice to not have another layer of nesting, but it's fine.
