### PR TITLE
Fix suggestion to constrain trait for method to be found

### LINKED ISSUE #65044: restrict type parameter `Self` error is unclear.
The following example code yields an error:

```
struct Demo {
    a: String
}

trait GetString {
    fn get_a(&self) -> &String;
}

trait UseString {
    fn use_string(&self) {
        println!("{:?}", self.get_a());
    }
}

impl GetString for Demo {
    fn get_a(&self) -> &String {
        &self.a
    }
}

impl UseString for Demo {}


#[cfg(test)]
mod tests {
    use crate::{Demo, UseString};

    #[test]
    fn it_works() {
        let d = Demo { a: "test".to_string() };
        d.use_string();
    }
}
```

```
warning: build failed, waiting for other jobs to finish...
error[E0599]: no method named `get_a` found for type `&Self` in the current scope
  --> src/lib.rs:12:31
   |
12 |         println!("{:?}", self.get_a());
   |                               ^^^^^
   |
   = help: items from traits can only be used if the type parameter is bounded by the trait
help: the following trait defines an item `get_a`, perhaps you need to restrict type parameter `Self` with it:
   |
10 | Self: GetString
   |

error: aborting due to previous error
```

It's unclear from this error message how to proceed - I'm not sure of the syntax, location, or where I should be putting the "GetString" trait bound. 

It should be shown with a better example or link when this error is presented, as the current message is not sufficient for a resolution to be arrived at.

### PR DESCRIPTION
**Pull request by estebank**
Fix #65044.

### CODE REVIEW

File: src/librustc_typeck/check/method/suggest.rs [hunk 1]
```diff
@@ -757,51 +757,67 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
...
-                                    // We've found `fn foo(x: impl Trait)` instead of
-                                    // `fn foo<T>(x: T)`. We want to suggest the correct
-                                    // `fn foo(x: impl Trait + TraitBound)` instead of
-                                    // `fn foo<T: TraitBound>(x: T)`. (#63706)
-                                    impl_trait = true;
-                                    has_bounds = param.bounds.len() > 1;
-                                }
-                                _ => {
-                                    has_bounds = !param.bounds.is_empty();
+                        debug!("suggest_traits_to_import {:?} {:?}", hir.get(id), generics);
```
Comment (Centril) [inline src/librustc_typeck/check/method/suggest.rs]: The current method is getting rather large; would be good to subdivide things.

File: src/test/ui/suggestions/constrain-trait.stderr [hunk 2]
```diff
@@ -0,0 +1,27 @@
+error[E0599]: no method named `get_a` found for type `&Self` in the current scope
+  --> $DIR/constrain-trait.rs:15:31
+   |
+LL |         println!("{:?}", self.get_a());
+   |                               ^^^^^ method not found in `&Self`
+   |
+   = help: items from traits can only be used if the type parameter is bounded by the trait
+help: the following trait defines an item `get_a`, perhaps you need to restrict type parameter `Self` with it:
```
Comment (Centril) [inline src/test/ui/suggestions/constrain-trait.stderr]: This wording feels ungreat -- I would wonder where the hell the type parameter `Self` came from since it's not in the source. I would say *", perhaps you need to add another super-trait:"*

File: src/librustc_typeck/check/method/suggest.rs (hunk 1 above)
Comment (estebank) [reply src/librustc_typeck/check/method/suggest.rs]: I feel that splitting this method would lead to with smaller methods with too many arguments, beyond the point for to be worth it.

Comment (Centril) [reply src/librustc_typeck/check/method/suggest.rs]: That suggests that a struct should be invented to carry the additional state.

File: src/librustc_typeck/check/method/suggest.rs [hunk 3]
```diff
@@ -757,56 +753,80 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
...
+                                kind: hir::ItemKind::Trait(.., bounds, _), ident, ..
+                            }) => {
+                                let (sp, sep) = if bounds.is_empty() {
+                                    (ident.span.shrink_to_hi(), ":")
+                                } else {
+                                    (bounds.last().unwrap().span().shrink_to_hi(), " +")
+                                };
+                                err.span_suggestions(
+                                    sp,
+                                    &message("add another super-trait for".to_string()),
```
Comment (varkor) [inline src/librustc_typeck/check/method/suggest.rs]: I think the convention is "supertrait", as one word.

**Comment by varkor** [comment]
Looks good. r=me with spelling fix.

**Comment by estebank** [comment]
Rebased.

@bors r=varkor
