### PR TITLE
consider glob imports in cfg suggestion

### LINKED ISSUE #141256: Diagnostic doesn't mention `cfg`-ed item referenced through glob import
### Code

```Rust
pub mod original {
    #[cfg(FALSE)]
    pub mod gated {
        pub fn foo() {}
    }
}

pub mod reexport {
    pub use super::original::*;
}

pub fn main() {
    reexport::gated::foo();

    // A direct reference produces the desired output.
    //original::gated::foo();
}
```

### Current output

```Shell
error[E0433]: failed to resolve: could not find `gated` in `reexport`
  --> <source>:14:15
   |
14 |     reexport::gated::foo();
   |               ^^^^^ could not find `gated` in `reexport`
```

### Desired output

```Shell
error[E0433]: failed to resolve: could not find `gated` in `reexport`
  --> <source>:14:15
   |
17 |     reexport::gated::foo();
   |               ^^^^^ could not find `gated` in `reexport`
   |
note: found an item that was configured out
  --> <source>:3:13
   |
3  |     pub mod gated {
   |             ^^^^^
note: the item is gated here
  --> <source>:2:5
   |
2  |     #[cfg(FALSE)]
   |     ^^^^^^^^^^^^^
```

### Rationale and extra context

If an item in a `cfg` gated module is directly referenced then the diagnostic will mention the gate. This does not happen if the gated module is re-exported through a glob import.

### Other cases

```Rust

```

### Rust Version

```Shell
rustc 1.86.0 (05f9846f8 2025-03-31)
binary: rustc
commit-hash: 05f9846f893b09a1be1fc8560e33fc3c815cfecb
commit-date: 2025-03-31
host: x86_64-unknown-linux-gnu
release: 1.86.0
LLVM version: 19.1.7

Also tested on nightly: 

rustc 1.89.0-nightly (777d37277 2025-05-17)
binary: rustc
commit-hash: 777d372772aa3b39ba7273fcb8208a89f2ab0afd
commit-date: 2025-05-17
host: x86_64-unknown-linux-gnu
release: 1.89.0-nightly
LLVM version: 20.1.4
```

### Anything else?

Compiler Explorer: https://godbolt.org/z/d3rr35G4T

### PR DESCRIPTION
**Pull request by bvanjoi**
Fixes rust-lang/rust#141256 

r? @petrochenkov

### CODE REVIEW

File: compiler/rustc_resolve/src/diagnostics.rs [hunk 1]
```diff
@@ -2623,7 +2623,13 @@ impl<'ra, 'tcx> Resolver<'ra, 'tcx> {
         };
 
         for &StrippedCfgItem { parent_module, ident, ref cfg } in symbols {
-            if parent_module != module || ident.name != *segment {
+            let comes_from_same_module = parent_module == module
+                || self.module_map.get(&parent_module).is_some_and(|m| {
+                    m.glob_importers.borrow().iter().any(|import| {
+                        import.parent_scope.module.opt_def_id().is_some_and(|m| m == module)
+                    })
+                });
```
[the remark this answers is not in the document]
Comment (bvanjoi) [reply compiler/rustc_resolve/src/diagnostics.rs:2631]: > Do you think it would be worth handling more than level of reexport

That makes sense to me. A recursive solution might be more suitable here.

File: compiler/rustc_expand/src/expand.rs [hunk 2]
```diff
@@ -1319,10 +1319,12 @@ impl InvocationCollectorNode for P<ast::Item> {
 
             let mut idents = Vec::new();
             collect_use_tree_leaves(ut, &mut idents);
-            return idents;
+            idents
+        } else if let Some(ident) = self.kind.ident() {
```
Comment (petrochenkov) [inline compiler/rustc_expand/src/expand.rs:1323]:
```suggestion
        } else { self.kind.ident().into_iter().collect() }
```
I think this would also work.

File: compiler/rustc_resolve/src/diagnostics.rs [hunk 3]
```diff
@@ -2623,7 +2623,13 @@ impl<'ra, 'tcx> Resolver<'ra, 'tcx> {
         };
 
         for &StrippedCfgItem { parent_module, ident, ref cfg } in symbols {
-            if parent_module != module || ident.name != *segment {
+            let comes_from_same_module = parent_module == module
+                || self.module_map.get(&parent_module).is_some_and(|m| {
+                    m.glob_importers.borrow().iter().any(|import| {
+                        import.parent_scope.module.opt_def_id().is_some_and(|m| m == module)
```
Comment (petrochenkov) [inline compiler/rustc_resolve/src/diagnostics.rs:2629]:
```suggestion
                        import.parent_scope.module.opt_def_id() == Some(module)
```

File: compiler/rustc_resolve/src/diagnostics.rs [hunk 4]
```diff
@@ -2623,7 +2623,13 @@ impl<'ra, 'tcx> Resolver<'ra, 'tcx> {
         };
 
         for &StrippedCfgItem { parent_module, ident, ref cfg } in symbols {
-            if parent_module != module || ident.name != *segment {
+            let comes_from_same_module = parent_module == module
+                || self.module_map.get(&parent_module).is_some_and(|m| {
```
Comment (petrochenkov) [inline compiler/rustc_resolve/src/diagnostics.rs:2627]: Maybe also makes sense to evaluate the expensive condition last, after both `ident.name != *segment` and `parent_module == module`, but it's a purely diagnostic branch so it's not very important.

**Comment by petrochenkov** [comment]
The current solution looks ok for merging to me.
Do you plan to implement something more recursive?
@rustbot author

File: compiler/rustc_resolve/src/diagnostics.rs [hunk 5]
```diff
@@ -2623,7 +2623,50 @@ impl<'ra, 'tcx> Resolver<'ra, 'tcx> {
...
+            fn comes_from_same_module_for_glob(
+                r: &Resolver<'_, '_>,
+                parent_module: DefId,
+                module: DefId,
+                visited: &mut FxHashMap<DefId, bool>,
+            ) -> bool {
+                if let Some(&cached) = visited.get(&parent_module) {
+                    return cached;
+                }
+                visited.insert(parent_module, false);
```
[the remark this answers is not in the document]
Comment (bvanjoi) [reply compiler/rustc_resolve/src/diagnostics.rs:2639]: I'm not entirely certain this can produce a cycle. Perhaps we could remove this check for now and only implement cycle detection if actual issues are reported?
