### PR TITLE
Fix incorrect span in `&mut` suggestion

### LINKED ISSUE #49859: Incorrect span in `&mut` suggestion
#48914 introduces a suggestion with an incorrect span:

```
error[E0594]: cannot assign to data in a `&` reference
  --> $DIR/issue-47388.rs:18:5
   |
LL |     let fancy_ref = &(&mut fancy);
   |                     ------------- help: consider changing this to be a mutable reference: `&mut`
LL |     fancy_ref.num = 6; //~ ERROR E0594
   |     ^^^^^^^^^^^^^^^^^ `fancy_ref` is a `&` reference, so the data it refers to cannot be written
```

The output should be either

```
LL |     let fancy_ref = &(&mut fancy);
   |                     - help: consider changing this to be a mutable reference: `&mut `
```

or 

```
LL |     let fancy_ref = &(&mut fancy);
   |                     ------------- help: consider changing this to be a mutable reference: `&mut (&mut fancy)`
```

### PR DESCRIPTION
**Pull request by csmoe**
Fixes #49859

### CODE REVIEW

File: src/librustc_mir/borrow_check/mod.rs [hunk 1]
```diff
@@ -1654,7 +1662,7 @@ impl<'cx, 'gcx, 'tcx> MirBorrowckCtxt<'cx, 'gcx, 'tcx> {
 
                     if let Some((err_help_span, err_help_stmt, item_msg, sec_span)) = err_info {
                         let mut err = self.tcx.cannot_assign(span, &item_msg, Origin::Mir);
-                        err.span_suggestion(err_help_span, err_help_stmt, format!(""));
+                        err.span_suggestion(err_help_span, &err_help_stmt, format!(""));
```
Comment (estebank) [inline src/librustc_mir/borrow_check/mod.rs]: If you look [below](https://github.com/rust-lang/rust/pull/49931/files#diff-6ec61eb4b2eddffb0a366aeb761a579eR8), the third argument is the code content that will be suggested. Because here an empty `String` is being passed, the suggestion effectively tells the user to remove the code.

File: src/librustc_mir/borrow_check/mod.rs [hunk 2]
```diff
@@ -1639,10 +1639,18 @@ impl<'cx, 'gcx, 'tcx> MirBorrowckCtxt<'cx, 'gcx, 'tcx> {
                                             } else {
                                                 self.get_default_err_msg(place)
                                             };
+                                            let sp = self.mir.source_info(locations[0]).span;
+                                            let mut help_stmt = String::new();
+                                            if let Ok(src) =
+                                                self.tcx.sess.codemap().span_to_snippet(sp) {
+                                                    help_stmt = format!(
+                                                        "consider changing this to be a \
+                                                        mutable reference: `&mut {}`", &src[1..]);
```
Comment (estebank) [inline src/librustc_mir/borrow_check/mod.rs]: The help message doesn't need to incorporate the suggested code, this is passed as the third argument to `span_suggestion` and the diagnostic machinery deals with this as appropriate.

File: src/librustc_mir/borrow_check/mod.rs [hunk 3]
```diff
@@ -1639,10 +1639,18 @@ impl<'cx, 'gcx, 'tcx> MirBorrowckCtxt<'cx, 'gcx, 'tcx> {
...
+                                            };
                                             err_info = Some((
```
Comment (estebank) [inline src/librustc_mir/borrow_check/mod.rs]: `err_info` will need to include the contents of `&src[1..]` above in order to supply to use it in the suggestion.

File: src/test/ui/nll/issue-47388.stderr [hunk 4]
```diff
@@ -1,10 +1,12 @@
 error[E0594]: cannot assign to data in a `&` reference
   --> $DIR/issue-47388.rs:18:5
    |
-LL |     let fancy_ref = &(&mut fancy);
-   |                     ------------- help: consider changing this to be a mutable reference: `&mut`
 LL |     fancy_ref.num = 6; //~ ERROR E0594
    |     ^^^^^^^^^^^^^^^^^ `fancy_ref` is a `&` reference, so the data it refers to cannot be written
+help: consider changing this to be a mutable reference: `&mut (&mut fancy)`
+   |
+LL |     let fancy_ref = ;
```
Comment (estebank) [inline src/test/ui/nll/issue-47388.stderr]: You can see what I'm referring to in the previous comments here: `let fancy_ref = ;` should be 

```
help: consider changing this to be a mutable reference
   |
LL |     let fancy_ref = &mut (&mut fancy);
```
`span_suggestion` deals with this correctly automatically.

**Review by estebank — CHANGES_REQUESTED** [review]
Thanks for the fix!

Small changes needed before being able to merge it. Once they are addressed, r=me.

**Comment by csmoe** [comment]
Advice addressed. r @estebank

**Comment by estebank** [comment]
```
[00:04:45] tidy error: /checkout/src/librustc_mir/borrow_check/mod.rs:1663: line longer than 100 chars
[00:04:45] tidy error: /checkout/src/librustc_mir/borrow_check/mod.rs:1665: line longer than 100 chars
```

**Review by estebank — APPROVED** [review]
