### PR TITLE
cmse: disallow `impl Trait` in `cmse-nonsecure-entry` return types

### LINKED ISSUE #147242: `cmse-nonsecure-entry` hits query cycle when returning `impl Trait`
Just documenting this so we have a paper trail. I intend to resolve this by disallowing `impl Trait` in return types altogether: we already disallow standard generics on functions with this ABI.

### Code

```Rust
#![feature(cmse_nonsecure_entry)]
#![no_std]

extern "cmse-nonsecure-entry" fn return_impl_trait() -> impl core::marker::Copy {
    0u128
}

#[unsafe(no_mangle)]
fn foo() {
    let _x = return_impl_trait();
}

```

### Meta

`rustc --version --verbose`:
```
cargo 1.92.0-nightly (966f94733 2025-09-16)
release: 1.92.0-nightly
commit-hash: 966f94733bbc94ca51ff9f1e4c49ad250ebbdc50
commit-date: 2025-09-16
host: x86_64-unknown-linux-gnu
libgit2: 1.9.1 (sys:0.20.2 vendored)
libcurl: 8.15.0-DEV (sys:0.4.83+curl-8.15.0 vendored ssl:OpenSSL/3.5.2)
ssl: OpenSSL 3.5.2 5 Aug 2025
os: Linux Mint 22.0.0 (wilma) [64-bit]
```

### Error output

```
warning: `extern` fn uses type `impl core::marker::Copy`, which is not FFI-safe
 --> src/lib.rs:4:57
  |
4 | extern "cmse-nonsecure-entry" fn return_impl_trait() -> impl core::marker::Copy {
  |                                                         ^^^^^^^^^^^^^^^^^^^^^^^ not FFI-safe
  |
  = note: opaque types have no C equivalent
  = note: `#[warn(improper_ctypes_definitions)]` on by default

note: no errors encountered even though delayed bugs were created

note: those delayed bugs will now be shown as internal compiler errors

error: internal compiler error[E0391]: cycle detected when computing function signature of `return_impl_trait`
 --> src/lib.rs:4:1
  |
4 | extern "cmse-nonsecure-entry" fn return_impl_trait() -> impl core::marker::Copy {
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: ...which requires computing layout of `return_impl_trait::{opaque#0}`...
  = note: ...which requires normalizing `return_impl_trait::{opaque#0}`...
note: ...which requires computing type of `return_impl_trait::{opaque#0}`...
 --> src/lib.rs:4:57
  |
4 | extern "cmse-nonsecure-entry" fn return_impl_trait() -> impl core::marker::Copy {
  |                                                         ^^^^^^^^^^^^^^^^^^^^^^^
note: ...which requires computing type of opaque `return_impl_trait::{opaque#0}`...
 --> src/lib.rs:4:57
  |
4 | extern "cmse-nonsecure-entry" fn return_impl_trait() -> impl core::marker::Copy {
  |                                                         ^^^^^^^^^^^^^^^^^^^^^^^
note: ...which requires borrow-checking `return_impl_trait`...
 --> src/lib.rs:4:1
  |
4 | extern "cmse-nonsecure-entry" fn return_impl_trait() -> impl core::marker::Copy {
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
note: ...which requires promoting constants in MIR for `return_impl_trait`...
 --> src/lib.rs:4:1
  |
4 | extern "cmse-nonsecure-entry" fn return_impl_trait() -> impl core::marker::Copy {
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
note: ...which requires checking if `return_impl_trait` contains FFI-unwind calls...
 --> src/lib.rs:4:1
  |
4 | extern "cmse-nonsecure-entry" fn return_impl_trait() -> impl core::marker::Copy {
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
note: ...which requires building MIR for `return_impl_trait`...
 --> src/lib.rs:4:1
  |
4 | extern "cmse-nonsecure-entry" fn return_impl_trait() -> impl core::marker::Copy {
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
note: ...which requires match-checking `return_impl_trait`...
 --> src/lib.rs:4:1
  |
4 | extern "cmse-nonsecure-entry" fn return_impl_trait() -> impl core::marker::Copy {
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
note: ...which requires type-checking `return_impl_trait`...
 --> src/lib.rs:4:1
  |
4 | extern "cmse-nonsecure-entry" fn return_impl_trait() -> impl core::marker::Copy {
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
note: ...which requires computing the opaque types defined by `return_impl_trait`...
 --> src/lib.rs:4:1
  |
4 | extern "cmse-nonsecure-entry" fn return_impl_trait() -> impl core::marker::Copy {
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  = note: ...which again requires computing function signature of `return_impl_trait`, completing the cycle
note: cycle used when checking that `return_impl_trait` is well-formed
 --> src/lib.rs:4:1
  |
4 | extern "cmse-nonsecure-entry" fn return_impl_trait() -> impl core::marker::Copy {
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  = note: see https://rustc-dev-guide.rust-lang.org/overview.html#queries and https://rustc-dev-guide.rust-lang.org/query.html for more information
note: delayed at compiler/rustc_query_system/src/query/job.rs:602:16 - disabled backtrace
 --> src/lib.rs:4:1
  |
4 | extern "cmse-nonsecure-entry" fn return_impl_trait() -> impl core::marker::Copy {
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: internal compiler error[E0391]: cycle detected when computing function signature of `return_impl_trait`
 --> src/lib.rs:4:1
  |
4 | extern "cmse-nonsecure-entry" fn return_impl_trait() -> impl core::marker::Copy {
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: ...which requires computing layout of `return_impl_trait::{opaque#0}`...
  = note: ...which requires normalizing `return_impl_trait::{opaque#0}`...
note: ...which requires computing type of `return_impl_trait::{opaque#0}`...
 --> src/lib.rs:4:57
  |
4 | extern "cmse-nonsecure-entry" fn return_impl_trait() -> impl core::marker::Copy {
  |                                                         ^^^^^^^^^^^^^^^^^^^^^^^
note: ...which requires computing type of opaque `return_impl_trait::{opaque#0}`...
 --> src/lib.rs:4:57
  |
4 | extern "cmse-nonsecure-entry" fn return_impl_trait() -> impl core::marker::Copy {
  |                                                         ^^^^^^^^^^^^^^^^^^^^^^^
note: ...which requires borrow-checking `return_impl_trait`...
 --> src/lib.rs:4:1
  |
4 | extern "cmse-nonsecure-entry" fn return_impl_trait() -> impl core::marker::Copy {
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
note: ...which requires promoting constants in MIR for `return_impl_trait`...
 --> src/lib.rs:4:1
  |
4 | extern "cmse-nonsecure-entry" fn return_impl_trait() -> impl core::marker::Copy {
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
note: ...which requires checking if `return_impl_trait` contains FFI-unwind calls...
 --> src/lib.rs:4:1
  |
4 | extern "cmse-nonsecure-entry" fn return_impl_trait() -> impl core::marker::Copy {
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
note: ...which requires building MIR for `return_impl_trait`...
 --> src/lib.rs:4:1
  |
4 | extern "cmse-nonsecure-entry" fn return_impl_trait() -> impl core::marker::Copy {
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
note: ...which requires match-checking `return_impl_trait`...
 --> src/lib.rs:4:1
  |
4 | extern "cmse-nonsecure-entry" fn return_impl_trait() -> impl core::marker::Copy {
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
note: ...which requires type-checking `return_impl_trait`...
 --> src/lib.rs:4:1
  |
4 | extern "cmse-nonsecure-entry" fn return_impl_trait() -> impl core::marker::Copy {
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  = note: ...which again requires computing function signature of `return_impl_trait`, completing the cycle
note: cycle used when checking that `return_impl_trait` is well-formed
 --> src/lib.rs:4:1
  |
4 | extern "cmse-nonsecure-entry" fn return_impl_trait() -> impl core::marker::Copy {
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  = note: see https://rustc-dev-guide.rust-lang.org/overview.html#queries and https://rustc-dev-guide.rust-lang.org/query.html for more information
note: delayed at compiler/rustc_query_system/src/query/job.rs:602:16 - disabled backtrace
 --> src/lib.rs:4:1
  |
4 | extern "cmse-nonsecure-entry" fn return_impl_trait() -> impl core::marker::Copy {
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: internal compiler error[E0391]: cycle detected when computing function signature of `return_impl_trait`
 --> src/lib.rs:4:1
  |
4 | extern "cmse-nonsecure-entry" fn return_impl_trait() -> impl core::marker::Copy {
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: ...which requires computing layout of `return_impl_trait::{opaque#0}`...
  = note: ...which requires normalizing `return_impl_trait::{opaque#0}`...
note: ...which requires computing type of `return_impl_trait::{opaque#0}`...
 --> src/lib.rs:4:57
  |
4 | extern "cmse-nonsecure-entry" fn return_impl_trait() -> impl core::marker::Copy {
  |                                                         ^^^^^^^^^^^^^^^^^^^^^^^
note: ...which requires computing type of opaque `return_impl_trait::{opaque#0}`...
 --> src/lib.rs:4:57
  |
4 | extern "cmse-nonsecure-entry" fn return_impl_trait() -> impl core::marker::Copy {
  |                                                         ^^^^^^^^^^^^^^^^^^^^^^^
note: ...which requires borrow-checking `return_impl_trait`...
 --> src/lib.rs:4:1
  |
4 | extern "cmse-nonsecure-entry" fn return_impl_trait() -> impl core::marker::Copy {
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
note: ...which requires promoting constants in MIR for `return_impl_trait`...
 --> src/lib.rs:4:1
  |
4 | extern "cmse-nonsecure-entry" fn return_impl_trait() -> impl core::marker::Copy {
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
note: ...which requires checking if `return_impl_trait` contains FFI-unwind calls...
 --> src/lib.rs:4:1
  |
4 | extern "cmse-nonsecure-entry" fn return_impl_trait() -> impl core::marker::Copy {
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
note: ...which requires building MIR for `return_impl_trait`...
 --> src/lib.rs:4:1
  |
4 | extern "cmse-nonsecure-entry" fn return_impl_trait() -> impl core::marker::Copy {
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  = note: ...which again requires computing function signature of `return_impl_trait`, completing the cycle
note: cycle used when checking that `return_impl_trait` is well-formed
 --> src/lib.rs:4:1
  |
4 | extern "cmse-nonsecure-entry" fn return_impl_trait() -> impl core::marker::Copy {
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  = note: see https://rustc-dev-guide.rust-lang.org/overview.html#queries and https://rustc-dev-guide.rust-lang.org/query.html for more information
note: delayed at compiler/rustc_query_system/src/query/job.rs:602:16 - disabled backtrace
 --> src/lib.rs:4:1
  |
4 | extern "cmse-nonsecure-entry" fn return_impl_trait() -> impl core::marker::Copy {
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: internal compiler error[E0391]: cycle detected when computing function signature of `return_impl_trait`
 --> src/lib.rs:4:1
  |
4 | extern "cmse-nonsecure-entry" fn return_impl_trait() -> impl core::marker::Copy {
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: ...which requires computing layout of `return_impl_trait::{opaque#0}`...
  = note: ...which requires normalizing `return_impl_trait::{opaque#0}`...
note: ...which requires computing type of `return_impl_trait::{opaque#0}`...
 --> src/lib.rs:4:57
  |
4 | extern "cmse-nonsecure-entry" fn return_impl_trait() -> impl core::marker::Copy {
  |                                                         ^^^^^^^^^^^^^^^^^^^^^^^
note: ...which requires computing type of opaque `return_impl_trait::{opaque#0}`...
 --> src/lib.rs:4:57
  |
4 | extern "cmse-nonsecure-entry" fn return_impl_trait() -> impl core::marker::Copy {
  |                                                         ^^^^^^^^^^^^^^^^^^^^^^^
note: ...which requires borrow-checking `return_impl_trait`...
 --> src/lib.rs:4:1
  |
4 | extern "cmse-nonsecure-entry" fn return_impl_trait() -> impl core::marker::Copy {
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
note: ...which requires promoting constants in MIR for `return_impl_trait`...
 --> src/lib.rs:4:1
  |
4 | extern "cmse-nonsecure-entry" fn return_impl_trait() -> impl core::marker::Copy {
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
note: ...which requires checking if `return_impl_trait` contains FFI-unwind calls...
 --> src/lib.rs:4:1
  |
4 | extern "cmse-nonsecure-entry" fn return_impl_trait() -> impl core::marker::Copy {
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  = note: ...which again requires computing function signature of `return_impl_trait`, completing the cycle
note: cycle used when checking that `return_impl_trait` is well-formed
 --> src/lib.rs:4:1
  |
4 | extern "cmse-nonsecure-entry" fn return_impl_trait() -> impl core::marker::Copy {
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  = note: see https://rustc-dev-guide.rust-lang.org/overview.html#queries and https://rustc-dev-guide.rust-lang.org/query.html for more information
note: delayed at compiler/rustc_query_system/src/query/job.rs:602:16 - disabled backtrace
 --> src/lib.rs:4:1
  |
4 | extern "cmse-nonsecure-entry" fn return_impl_trait() -> impl core::marker::Copy {
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: please make sure that you have updated to the latest nightly

note: please attach the file at `/home/folkertdev/rust/playground/rustc-ice-2025-10-01T18_43_37-135196.txt` to your bug report

note: compiler flags: --crate-type lib -C opt-level=3 -C panic=abort -C embed-bitcode=no -C debuginfo=2 -Z unstable-options -C llvm-args=-x86-asm-syntax=intel -C debuginfo=2 -C codegen-units=1

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
warning: `playground` (lib) generated 1 warning
error: could not compile `playground` (lib); 1 warning emitted

Caused by:
  process didn't exit successfully: `/home/folkertdev/.rustup/toolchains/stage1/bin/rustc --crate-name playground --edition=2021 src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --diagnostic-width=190 --crate-type lib --emit=dep-info,metadata,link -C opt-level=3 -C panic=abort -C embed-bitcode=no -C debuginfo=2 --check-cfg 'cfg(docsrs,test)' --check-cfg 'cfg(feature, values())' -C metadata=f3bf8d08de02bd06 -C extra-filename=-642b5b0b4127d905 --out-dir /home/folkertdev/rust/playground/target/thumbv8m.main-none-eabi/release/deps --target thumbv8m.main-none-eabi -L dependency=/home/folkertdev/rust/playground/target/thumbv8m.main-none-eabi/release/deps -L dependency=/home/folkertdev/rust/playground/target/release/deps --extern 'noprelude:compiler_builtins=/home/folkertdev/rust/playground/target/thumbv8m.main-none-eabi/release/deps/libcompiler_builtins-eb37b01561e12bc2.rmeta' --extern 'noprelude:core=/home/folkertdev/rust/playground/target/thumbv8m.main-none-eabi/release/deps/libcore-5dcd424cf93dc313.rmeta' -Z unstable-options --emit asm -C llvm-args=-x86-asm-syntax=intel -Cdebuginfo=2 -Ccodegen-units=1` (exit status: 101)
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
<backtrace>
```

</p>
</details>

### PR DESCRIPTION
**Pull request by folkertdev**
tracking issue: https://github.com/rust-lang/rust/issues/75835
fixes https://github.com/rust-lang/rust/issues/147242

Refactors some logic to be more robust in the future, and then disallows `impl Trait` as a return type for the cmse ABIs.

The `is_valid_cmse_output_layout` function disallows `union` values like before. That is not entirely correct, but preserves the current behavior. Some additional logic is needed for `union` values (and any types where parts may be uninitialized) that I'll tackle in a later PR.

can be reviewed commit-by-commit.

r? types

### CODE REVIEW

**Review by davidtwco — APPROVED** [review]

File: compiler/rustc_hir_analysis/src/hir_ty_lowering/cmse.rs [hunk 1]
```diff
@@ -164,44 +164,48 @@ fn is_valid_cmse_output<'tcx>(
...
+    // `impl Trait` is already disallowed with `cmse-nonsecure-call`, because that ABI is only
+    // allowed on function pointers, and function pointers cannot contain `impl Trait` in their
+    // signature.
+    //
+    // Here we explicitly disallow `impl Trait` as a `cmse-nonsecure-entry` return type too, to
+    // prevent query cycles when calculating the layout. This ABI is meant to be used with
+    // `#[no_mangle]` or similar, so generics in the type really don't make sense.
+    //
+    // see also https://github.com/rust-lang/rust/issues/147242.
+    if return_type.is_impl_trait() {
```
Comment (fmease) [inline compiler/rustc_hir_analysis/src/hir_ty_lowering/cmse.rs]: This doesn't catch return types containing impl-Trait like `(impl Copy,)`, `&impl ?Sized`, `Wrap<impl Sized>`, `Wrap<dyn Trait<AssocTy = impl Sized>>` etc.

**Review by fmease — CHANGES_REQUESTED** [review]

File: compiler/rustc_hir_analysis/src/hir_ty_lowering/cmse.rs (hunk 1 above)
Comment (fmease) [reply compiler/rustc_hir_analysis/src/hir_ty_lowering/cmse.rs]: Consider checking the following instead (probably requires importing an extension trait):

```suggestion
    if return_type.has_opaque_types() {
```

File: compiler/rustc_hir_analysis/src/hir_ty_lowering/cmse.rs [hunk 2]
```diff
@@ -164,44 +164,48 @@ fn is_valid_cmse_output<'tcx>(
...
+    let fn_sig = tcx.erase_and_anonymize_regions(fn_sig);
+    let return_type = fn_sig.output();
+
+    // `impl Trait` is already disallowed with `cmse-nonsecure-call`, because that ABI is only
+    // allowed on function pointers, and function pointers cannot contain `impl Trait` in their
+    // signature.
+    //
+    // Here we explicitly disallow `impl Trait` in the `cmse-nonsecure-entry` return type too, to
+    // prevent query cycles when calculating the layout. This ABI is meant to be used with
+    // `#[no_mangle]` or similar, so generics in the type really don't make sense.
```
Comment (BoxyUwU) [inline compiler/rustc_hir_analysis/src/hir_ty_lowering/cmse.rs:176]: for the record opaque types are not generics. `fn foo() -> impl Trait`'s return type is some fully concrete non generic type, its just not explicitly written out. I think you're right that `no_mangle`'d functions with RPITs are silly though

Comment (folkertdev) [reply compiler/rustc_hir_analysis/src/hir_ty_lowering/cmse.rs:176]: really? My intuition is that `-> impl Trait` is polymorphic and that it is roughly equivalent to `fn foo<T: Trait>() -> T`. You'd need to pick a concrete imlementation of the trait in order to actually be able to calculate the layout of the return type (and from that the ABI).

Is there some better word for "the type is not known enough to calculate the layout"?

Comment (BoxyUwU) [reply compiler/rustc_hir_analysis/src/hir_ty_lowering/cmse.rs:176]: the type of RPITs *should* be known enough to calculate the layout of the return type as long as opaque types are able to be properly normalized. `impl Trait` only desugars to a generic parameter in *argument* position, i.e. `fn foo(a: impl Trait)` desugars as you say

Comment (folkertdev) [reply compiler/rustc_hir_analysis/src/hir_ty_lowering/cmse.rs:176]: Oh interesting, it actually looks at the body to figure out the concrete type if it occurs just in return position

https://godbolt.org/z/KhfhrxPG6

Comment (folkertdev) [reply compiler/rustc_hir_analysis/src/hir_ty_lowering/cmse.rs:176]: But at the point where we attempt to generate the layout for these entry functions, somehow there is a loop in the calculation

https://godbolt.org/z/K58sMorf3

(that godbolt only works with current nightly, but the same cycle is in the issue https://github.com/rust-lang/rust/issues/147242)

anyway we're totally fine with just disallowing `impl Trait` entirely, it's a simple rule that doesn't really limit any practical use.

Comment (BoxyUwU) [reply compiler/rustc_hir_analysis/src/hir_ty_lowering/cmse.rs:176]: yeah I would be interested in seeing where the cycle comes from, but it does seem fine to just altogether forbid this as RPITs in no_mangle functions seems like a big footgun/code smell
