### PR TITLE
Fix expected/found order on impl trait projection mismatch error

### LINKED ISSUE #68561: impl Trait error message expected/found order are confusing
@jonas-schievink pointed out that the "expected/found" ordering for `-> impl trait` return types can be quite confusing:

```rust
trait Tr {
    type A;
}

impl<A> Tr for A {
    type A = A;
}

fn f() -> impl Tr<A=u8> {
    ()
}
```

gives

```
error[E0271]: type mismatch resolving `<() as Tr>::A == u8`
 --> src/lib.rs:9:11
  |
9 | fn f() -> impl Tr<A=u8> {
  |           ^^^^^^^^^^^^^ expected (), found u8
  |
  = note: expected type `()`
             found type `u8`
  = note: the return type of a function must have a statically known size
```

Additionally, the second note is wrong (`()` is `Sized`).

This does not happen when changing the code to use a boxed trait instead (expected and found are in the right order).

_Originally posted by @jonas-schievink in https://github.com/rust-lang/rust/issues/54326#issuecomment-578284507_

### PR DESCRIPTION
**Pull request by SNCPlay42**
fixes #68561

This PR adds a new `ObligationCauseCode` used when checking the concrete type of an impl trait satisfies its bounds, and checks for that cause code in the existing test to see if a projection's normalized type should be the "expected" or "found" type.

The second commit adds a `peel_derives` to that test, which appears to be necessary in some cases (see projection-mismatch-in-impl-where-clause.rs, which would still give expected/found in the wrong order otherwise). This caused some other changes in diagnostics not involving impl trait, but they look correct to me.

### CODE REVIEW

File: compiler/rustc_middle/src/ty/error.rs [hunk 1]
```diff
@@ -497,13 +497,18 @@ impl<T> Trait<T> for X {
                             "consider constraining the associated type `{}` to `{}`",
                             values.found, values.expected,
                         );
-                        if !self.suggest_constraint(
+                        if !(self.suggest_constraining_opaque_associated_type(
+                            db,
+                            &msg,
+                            proj_ty,
+                            values.expected,
+                        ) || self.suggest_constraint(
```
Comment (SNCPlay42) [inline compiler/rustc_middle/src/ty/error.rs:505]: I added this to avoid losing a helpful [suggestion](https://github.com/rust-lang/rust/blob/b88e06c82084f81df5a730881d4f52f475d8abc7/src/test/ui/associated-types/impl-trait-return-missing-constraint.stderr#L12) in the impl-trait-return-missing-constraint test.

I wonder how much else of the `expected_projection` function makes sense to run in this case (when the projection type is *found*) as well.

File: src/test/ui/impl-trait/issues/issue-70877.stderr [hunk 2]
```diff
@@ -2,13 +2,13 @@ error[E0271]: type mismatch resolving `<Bar as Iterator>::Item == Box<(dyn for<'
...
+   |               -------------------- the found opaque type
 ...
 LL | type Foo = impl Iterator<Item = FooItem>;
-   |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected opaque type, found enum `Option`
+   |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected enum `Option`, found opaque type
    |
-   = note: expected struct `Box<(dyn for<'r> Fn(&'r (dyn ToString + 'r)) -> impl Debug + 'static)>`
-              found struct `Box<(dyn for<'r> Fn(&'r (dyn ToString + 'r)) -> Option<String> + 'static)>`
+   = note: expected struct `Box<(dyn for<'r> Fn(&'r (dyn ToString + 'r)) -> Option<String> + 'static)>`
+              found struct `Box<(dyn for<'r> Fn(&'r (dyn ToString + 'r)) -> impl Debug + 'static)>`
```
Comment (SNCPlay42) [inline src/test/ui/impl-trait/issues/issue-70877.stderr:11]: This change looks like it might be wrong to me. On the other hand I'm not sure why [this test](https://github.com/rust-lang/rust/blob/b88e06c82084f81df5a730881d4f52f475d8abc7/src/test/ui/impl-trait/issues/issue-70877.rs) doesn't compile. `Bar`'s `Iterator` impl defines its `Item` to be `FooItem`, but the compiler complains `Bar` doesn't satisfy `impl Iterator<Item = FooItem>` because the `Item` type is wrong? It seems the compiler is being inconsistent about whether `ham` gets to see the true type of `FooRet`, or something.

At any rate this test is a complicated setup involving a nightly feature, so I don't think it's a big problem if this pr worsens the diagnostic in such a case.
