### PR TITLE
Fix auto-application of associated generic functions with placeholders

### LINKED ISSUE #101920: Suggestion for using function call instead of method call syntax incorrectly marked machine applicable
```rust
fn main() {
    let b = Box::new(0);
    let ptr = b.into_raw();
}
```

Current output:
```
error[E0599]: no method named `into_raw` found for struct `Box<{integer}>` in the current scope
 --> src/main.rs:3:17
  |
3 |     let ptr = b.into_raw();
  |               --^^^^^^^^
  |               | |
  |               | this is an associated function, not a method
  |               help: use associated function syntax instead: `Box::<{integer}>::into_raw`
  |
  = note: found the following associated functions; to be used as methods, functions must have a `self` parameter
  = note: the candidate is defined in an impl for the type `Box<T, A>`
```

However, the "help: use associated function syntax instead: `Box::<{integer}>::into_raw`" suggestion is internally marked as "machine applicable", even though it contains the `{integer}` placeholder. Running `cargo fix --broken-code` on this code, or using rust-analyzer's check-on-save feature and applying the quickfix thus results in invalid code:

```rust
fn main() {
    let b = Box::new(0);
    let ptr = Box::<{integer}>::into_raw();
}
```

### PR DESCRIPTION
**Pull request by clubby789**
Fixes #101920

### CODE REVIEW

File: compiler/rustc_typeck/src/check/method/suggest.rs [hunk 1]
```diff
@@ -391,28 +391,45 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
...
+                                let placeholders = substs
+                                    .iter()
+                                    .filter_map(|arg| {
+                                        if let GenericArgKind::Type(ty) = arg.unpack() {
+                                            Some(ty)
+                                        } else {
+                                            None
+                                        }
+                                    })
+                                    .any(|ty| matches!(ty.kind(), ty::Infer(_)));
```
Comment (fmease) [inline compiler/rustc_typeck/src/check/method/suggest.rs:414]: Consider making use of `is_suggestable` here instead of only checking for `ty::Infer`.

File: compiler/rustc_typeck/src/check/method/suggest.rs [hunk 2]
```diff
@@ -391,28 +391,45 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
...
+                    };
+                    let applicability = match placeholders {
+                        true => Applicability::HasPlaceholders,
+                        false => Applicability::MachineApplicable,
+                    };
                     if let SelfSource::MethodCall(expr) = source {
                         err.span_suggestion(
                             expr.span.to(span),
                             "use associated function syntax instead",
                             format!("{}::{}", ty_str, item_name),
```
Comment (fmease) [inline compiler/rustc_typeck/src/check/method/suggest.rs:431]: Instead of changing the applicability, we could replace unnameable / non-suggestable types with underscores (inference variables) allowing the diagnostic to stay machine-applicable. Similar to here:

https://github.com/rust-lang/rust/blob/a37499ae66ec5fc52a93d71493b78fb141c32f6b/compiler/rustc_infer/src/infer/error_reporting/need_type_info.rs#L459-L480

**Comment by clubby789** [comment]
I notice that even when the type is known and this isn't an issue (e.g)
```rs
fn main() {
        let b = Box::new("abc");
        let ptr = b.into_raw();
}
```
Applying the fix results in incorrect code: `Box::<&str>::into_raw()`
Should the fix instead transform this to `Box::<&str>::into_raw(b)`?

File: compiler/rustc_typeck/src/check/method/suggest.rs [hunk 3]
```diff
@@ -391,22 +395,53 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
...
+                                                    span: rustc_span::DUMMY_SP,
+                                                    kind: ConstVariableOriginKind::MiscVariable,
+                                                },
+                                            )
+                                            .into(),
+                                    })
+                                    .collect::<Vec<_>>();
+                                format!(
+                                    "{}",
+                                    ty::Instance::new(def_actual.did(), tcx.intern_substs(&substs))
```
Comment (compiler-errors) [inline compiler/rustc_typeck/src/check/method/suggest.rs:437]: I don't think using `Instance` here is right. Can you instead try using something like `tcx.def_path` or [`tcx.def_path_with_substs`](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_middle/ty/context/struct.TyCtxt.html#method.def_path_str_with_substs)?

**Comment by compiler-errors** [comment]
> Should the fix instead transform this to Box::<&str>::into_raw(b)?

I think so, yes.

File: compiler/rustc_typeck/src/check/method/suggest.rs (hunk 3 above)
Comment (clubby789) [reply compiler/rustc_typeck/src/check/method/suggest.rs:437]: `def_path_with_substs` requires that `substs` is borrowed for `'tcx`. Since it's local to the match arm it doesn't live long enough for this

**Comment by clubby789** [comment]
Currently working on automatically adjusting the arguments, but not sure how to handle the case of 
```rs
struct GenericAssocMethod<T>(T);
impl<T> GenericAssocMethod<T> {
  fn default_hello() {}
}
let x = GenericAssocMethod(33);
x.default_hello();
```
Where the generic arguments can't be inferred in the `GenericAssocMethod::<_>::default_hello` form. Applying this or leaving it results in invalid code which causes cargo to print a bug message.

**Comment by clubby789** [comment]
I've temporarily commented out the problematic test case since this seems like incorrect behaviour from Cargo

File: src/test/ui/suggestions/suggest-assoc-fn-call-with-turbofish.fixed [hunk 4]
```diff
@@ -0,0 +1,29 @@
...
+impl<T> GenericAssocMethod<T> {
+    fn default_hello() {}
+    fn self_ty_hello(_: Self) {}
+    fn self_ty_ref_hello(_: &Self) {}
+}
+
+fn main() {
+    // Test for inferred types
+    let x = GenericAssocMethod(33);
+    // This particular case is unfixable without more information by the user,
```
Comment (compiler-errors) [inline src/test/ui/suggestions/suggest-assoc-fn-call-with-turbofish.fixed:14]: Can you be explicit about needing more information? If this isn't a `MachineApplicable` diagnostic, then it shouldn't be marked `MachineApplicable` I think.

**Comment by compiler-errors** [comment]
> Where the generic arguments can't be inferred in the GenericAssocMethod::<_>::default_hello form. Applying this or leaving it results in invalid code which causes cargo to print a bug message.

Then this suggestion should probably not be `MachineApplicable`, and we shouldn't have a test case that has `// run-rustfix` for it, but just a regular error test case for it.

**Comment by compiler-errors** [comment]
Marking this as `S-waiting-on-author` so it can be adjusted to make it not `MachineApplicable` if it doesn't actually fit the criteria for `MachineApplicable`, namely that it should produce code that compiles when applied.

File: src/test/ui/suggestions/suggest-assoc-fn-call-with-turbofish.fixed (hunk 4 above)
Comment (clubby789) [reply src/test/ui/suggestions/suggest-assoc-fn-call-with-turbofish.fixed:14]: The case of `x.default_hello()` (or any case where the type can't be inferred) emits a `HasPlaceholders` diagnostic and suggests `GenericAssocMethod::<_>::default_hello()`

File: compiler/rustc_typeck/src/check/method/suggest.rs [hunk 5]
```diff
@@ -391,28 +396,117 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
...
                         } else {
-                            self.ty_to_value_string(actual.peel_refs())
+                            None
+                        };
+                        let mut applicability = Applicability::MachineApplicable;
+                        let args = if let Some((receiver, args)) = args {
+                            // The first arg is the same kind as the receiver
+                            let it = if first_arg.is_some() {
+                                Box::new(std::iter::once(receiver).chain(args.iter()))
+                                    as Box<dyn Iterator<Item = &Expr<'_>>>
```
Comment (compiler-errors) [inline compiler/rustc_typeck/src/check/method/suggest.rs:479]: Can you just do code duplication here? Or collect into a `Vec<_>`? Coercing into a boxed iterator here is kinda confusing and this is diagnostics code, so it doesn't need to be efficient necessarily.

**Comment by clubby789** [comment]
🤔 Sorry about the ping, I think I might have made a mistake while rebasing

**Review by compiler-errors — APPROVED** [review]

**Comment by compiler-errors** [comment]
Why didn't bors respojnd, lol

@bors r+
