### PR TITLE
Respect --sysroot for rustc -vV and -Cpasses=list

### LINKED ISSUE #135165: --sysroot ignored by -vV
I tried this:

Put a custom codegen backend in a custom sysroot and call `rustc -vV --sysroot /path/to/sysroot -Zcodegen-backend=my_backend`.

I expected to see this happen: Among other things the version of the custom codegen backend is printed.

Instead, this happened: After rustc's own version, it prints ``error: unsupported builtin codegen backend `my_backend` `` and exits with an error code.

This is blocking me from putting a locally built cg_clif in a custom sysroot and then using `profile.dev.codegen-backend = "cranelift"` as opposed to using `RUSTFLAGS="-Zcodegen-backend=/path/to/librustc_codegen_cranelift.so"`. Cargo only supports setting the codegen backend using profiles for codegen backends that are part of a sysroot, but configuring the codegen backend on a per-package basis requires using a cargo profile setting rather than `RUSTFLAGS`.

### Meta

`rustc --version --verbose`:
```
rustc 1.86.0-nightly (b3b368a18 2025-01-05)
binary: rustc
commit-hash: b3b368a1833a26f5d48f51c45159f46e6cd01711
commit-date: 2025-01-05
host: x86_64-unknown-linux-gnu
release: 1.86.0-nightly
error: unsupported builtin codegen backend `my_backend`
```

https://github.com/rust-lang/rust/blob/243d2ca4db6f96d2d18aaf3a2381251d38eb6b0b/compiler/rustc_driver_impl/src/lib.rs#L922 needs to be changed to manually parse the `--sysroot` flag rather than taking `opts.maybe_sysroot` from `Options::default()`.

### PR DESCRIPTION
**Pull request by bjorn3**
This is necessary when the specified codegen backend is in a custom sysroot.

Fixes https://github.com/rust-lang/rust/issues/135165

### CODE REVIEW

File: compiler/rustc_driver_impl/src/lib.rs [hunk 1]
```diff
@@ -1125,19 +1119,26 @@ pub fn describe_flag_categories(early_dcx: &EarlyDiagCtxt, matches: &Matches) ->
...
-
-        get_codegen_backend(early_dcx, &sysroot, backend_name, &target).print_passes();
+        get_backend_from_raw_matches(early_dcx, matches).print_passes();
         return true;
     }
 
     false
 }
 
+fn get_backend_from_raw_matches(
```
Comment (lqd) [inline compiler/rustc_driver_impl/src/lib.rs:1129]: let's add a doc comment explaining why this exists

**Review by lqd — COMMENTED** [review]
r=me with comment and CI green

File: compiler/rustc_driver_impl/src/lib.rs (hunk 1 above)
Comment (bjorn3) [reply compiler/rustc_driver_impl/src/lib.rs:1134]: Added

File: compiler/rustc_driver_impl/src/lib.rs [hunk 2]
```diff
@@ -1125,19 +1119,31 @@ pub fn describe_flag_categories(early_dcx: &EarlyDiagCtxt, matches: &Matches) ->
...
+/// without validating any other arguments and loads the codegen backend based on these arguments.
+fn get_backend_from_raw_matches(
+    early_dcx: &EarlyDiagCtxt,
+    matches: &Matches,
+) -> Box<dyn CodegenBackend> {
+    let debug_flags = matches.opt_strs("Z");
+    let backend_name = debug_flags.iter().find_map(|x| x.strip_prefix("codegen-backend="));
+    let opts = config::Options::default();
+    let sysroot = filesearch::materialize_sysroot(matches.opt_str("sysroot").map(PathBuf::from));
+    let target = config::build_target_config(early_dcx, &opts, &sysroot);
```
Comment (klensy) [inline compiler/rustc_driver_impl/src/lib.rs:1142]: Why build_target_config uses opts that is config::Options::default(), which sets target_triple to `host_tuple`? This looks weird for function named `build_target_config` use some defaulted target.

File: compiler/rustc_driver_impl/src/lib.rs (hunk 1 above)
Comment (lqd) [reply compiler/rustc_driver_impl/src/lib.rs:1134]: Looks good, thank you.

Comment (lqd) [reply compiler/rustc_driver_impl/src/lib.rs:1134]: Err, did you mean "creates a sessions" or "created a session", I assume the latter.

File: compiler/rustc_driver_impl/src/lib.rs (hunk 2 above)
Comment (bjorn3) [reply compiler/rustc_driver_impl/src/lib.rs:1142]: I've thought about inlining `build_target_config` and directly using the host tuple instead, but the function is just a bit too complicated to inline IMO.

File: compiler/rustc_driver_impl/src/lib.rs [hunk 3]
```diff
@@ -1125,19 +1119,31 @@ pub fn describe_flag_categories(early_dcx: &EarlyDiagCtxt, matches: &Matches) ->
...
 
     if cg_flags.iter().any(|x| *x == "passes=list") {
-        let backend_name = debug_flags.iter().find_map(|x| x.strip_prefix("codegen-backend="));
-
-        let opts = config::Options::default();
-        let sysroot = filesearch::materialize_sysroot(opts.maybe_sysroot.clone());
-        let target = config::build_target_config(early_dcx, &opts, &sysroot);
-
-        get_codegen_backend(early_dcx, &sysroot, backend_name, &target).print_passes();
+        get_backend_from_raw_matches(early_dcx, matches).print_passes();
```
Comment (jieyouxu) [inline compiler/rustc_driver_impl/src/lib.rs:1122]: Question: is it possible to add a test for this so we don't regress this in the future?

File: compiler/rustc_driver_impl/src/lib.rs (hunk 2 above)
Comment (klensy) [reply compiler/rustc_driver_impl/src/lib.rs:1142]: I mean, that this will potentially ignore actual `target_triple` and use `host_tuple()` instead when calling `get_codegen_backend`?

Comment (lqd) [reply compiler/rustc_driver_impl/src/lib.rs:1142]: Why would the backend version depend on the target. Same for the pass list I assume, whether they are enabled may be dynamic if there were target-dependent passes.

Comment (klensy) [reply compiler/rustc_driver_impl/src/lib.rs:1142]: For version - yes, but for passes - idk, i'll try to check.

Comment (bjorn3) [reply compiler/rustc_driver_impl/src/lib.rs:1142]: The target can affect the codegen backend we use through the `default_codegen_backend` field in the target spec. We're currently ignoring this already however.

Comment (klensy) [reply compiler/rustc_driver_impl/src/lib.rs:1142]: Okay, can you add comment that using default target in this function is ok?

File: compiler/rustc_driver_impl/src/lib.rs (hunk 3 above)
Comment (lqd) [reply compiler/rustc_driver_impl/src/lib.rs:1122]: @bjorn3 we run cg_clif’s tests on our CI, right? It may be easier to have a simple test there, than in-tree here (unless we have `//@ needs-cranelift` to execute your tests).

Comment (bjorn3) [reply compiler/rustc_driver_impl/src/lib.rs:1122]: I haven't changed cg_clif yet in the way I want precisely because the bug this PR fixes would prevent cargo from working.

File: compiler/rustc_driver_impl/src/lib.rs (hunk 2 above)
Comment (bjorn3) [reply compiler/rustc_driver_impl/src/lib.rs:1142]: It is technically not correct, but it is not a regression from the current state and using `--target` could potentially break things.

File: compiler/rustc_driver_impl/src/lib.rs (hunk 3 above)
Comment (jieyouxu) [reply compiler/rustc_driver_impl/src/lib.rs:1122]: Hm, if this is *very* convoluted to write a test for, then I think it's acceptable to not have one (this is unbreak cg_clif in the first place)

File: compiler/rustc_driver_impl/src/lib.rs (hunk 2 above)
Comment (bjorn3) [reply compiler/rustc_driver_impl/src/lib.rs]: I've added `--target` support too.
