### PR TITLE
Unimplement unsized_locals

### LINKED ISSUE #79409: ICE with unsizing an extern type
### Code

```Rust
#![feature(extern_types)]
#![feature(unsized_locals)]

extern { 
    type Device;
}

unsafe fn make_device() -> Box<Device> {
    Box::from_raw(0 as *mut _)
}

fn main() {
    let d: Device = unsafe { *make_device() };
}
```

### Meta

`rustc --version --verbose`:
```
rustc 1.50.0-nightly (1c389ffef 2020-11-24)
```

### Error output

```
thread 'rustc' panicked at 'assertion failed: `(left == right)`
  left: `false`,
 right: `true`', compiler/rustc_codegen_llvm/src/builder.rs:445:9
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
stack backtrace:
   0: rust_begin_unwind
             at /rustc/1c389ffeff814726dec325f0f2b0c99107df2673/library/std/src/panicking.rs:493:5
   1: core::panicking::panic_fmt
             at /rustc/1c389ffeff814726dec325f0f2b0c99107df2673/library/core/src/panicking.rs:92:14
   2: <rustc_codegen_llvm::builder::Builder as rustc_codegen_ssa::traits::builder::BuilderMethods>::load_operand
   3: rustc_codegen_ssa::mir::operand::<impl rustc_codegen_ssa::mir::FunctionCx<Bx>>::codegen_consume
   4: rustc_codegen_ssa::mir::operand::<impl rustc_codegen_ssa::mir::FunctionCx<Bx>>::codegen_operand
   5: rustc_codegen_ssa::mir::block::<impl rustc_codegen_ssa::mir::FunctionCx<Bx>>::codegen_block
   6: rustc_codegen_ssa::mir::codegen_mir
   7: rustc_codegen_ssa::base::codegen_instance
   8: <rustc_middle::mir::mono::MonoItem as rustc_codegen_ssa::mono_item::MonoItemExt>::define
   9: rustc_codegen_llvm::base::compile_codegen_unit::module_codegen
  10: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task
  11: rustc_codegen_llvm::base::compile_codegen_unit
  12: rustc_codegen_ssa::base::codegen_crate
  13: <rustc_codegen_llvm::LlvmCodegenBackend as rustc_codegen_ssa::traits::backend::CodegenBackend>::codegen_crate
  14: rustc_interface::queries::Queries::ongoing_codegen
  15: rustc_interface::queries::<impl rustc_interface::interface::Compiler>::enter
  16: rustc_span::with_source_map
  17: scoped_tls::ScopedKey<T>::set
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

error: internal compiler error: unexpected panic
```

</p>
</details>

### PR DESCRIPTION
**Pull request by mejrs**
Implements https://github.com/rust-lang/compiler-team/issues/630

Tracking issue here: https://github.com/rust-lang/rust/issues/111942

Note that this just removes the feature, not the implementation, and does not touch `unsized_fn_params`. This is because it is required to support `Box<dyn FnOnce()>: FnOnce()`. 

There may be more that should be removed (possibly in follow up prs)
- the `forget_unsized` function and `forget` intrinsic.
- the `unsized_locals` test directory; I've just fixed up the tests for now
-  rust-lang/rust#142911 various codegen support for unsized values and allocas

cc @JakobDegen @oli-obk @Noratrieb @programmerjake @bjorn3 

@rustbot label F-unsized_locals

Fixes rust-lang/rust#79409

### CODE REVIEW

**Comment by RalfJung** [comment]
> Implements https://github.com/rust-lang/compiler-team/issues/630

That's 2 years ago and so it's not indicative of the team position today. Some stuff happened since then since some people want to preserve the feature.

This will need a new MCP I think.

**Comment by Noratrieb** [comment]
I don't think anything changed about the biggest issues (MIR support being lacking), the unsoundness around alignment was just one small factor I'd say. No one has stepped up to actually resolve any of these issues in two years, which doesn't indicate a lot of interest in the feature to me. That said, if you think a re-MCP should be done, I'd be happy to help drafting that up (I imagine it would mostly just copy from the old MCP).
To me, two years is not that long in this case and I'm not aware of any significant changes in any area that would make the result different now (other than the one fix), so I don't think it warrants a new MCP.

**Comment by RalfJung** [comment]
The MIR representation of unsized locals still needs to be re-done from scratch, that is true.

File: compiler/rustc_feature/src/removed.rs [hunk 1]
```diff
@@ -247,6 +247,8 @@ declare_features! (
     /// Allows unnamed fields of struct and union type
     (removed, unnamed_fields, "1.83.0", Some(49804), Some("feature needs redesign")),
     (removed, unsafe_no_drop_flag, "1.0.0", None, None),
+    /// Allows unsized rvalues at arguments and parameters.
+    (removed, unsized_locals, "CURRENT_RUSTC_VERSION", Some(48055), Some("removed due to soundness issues; see https://github.com/rust-lang/rust/issues/111942")),
```
Comment (Noratrieb) [inline compiler/rustc_feature/src/removed.rs]:
```suggestion
    (removed, unsized_locals, "CURRENT_RUSTC_VERSION", Some(48055), Some("removed due to implementation concerns; see https://github.com/rust-lang/rust/issues/111942")),
```
As pointed out by Ralf, it should be *sound*, just not sufficiently implemented

**Comment by scottmcm** [comment]
> Note that this just removes the feature, not the implementation

Maybe a dumb question, but why not remove the implementation?  If the implementation is going to be there anyway, feels like having the feature is fine.

(My preference would be to remove the implementation too.)

**Comment by Noratrieb** [comment]
The implementation should be removed too but not in this PR^^

File: src/tools/clippy/tests/ui/large_stack_frames.rs [hunk 2]
```diff
@@ -11,10 +11,10 @@ fn generic<T: Default>() {
...
 }
 
-fn unsized_local() {
-    let x: dyn std::fmt::Display = *(Box::new(1) as Box<dyn std::fmt::Display>);
-    black_box(&x);
-}
+
+
+
+
```
Comment (flip1995) [inline src/tools/clippy/tests/ui/large_stack_frames.rs]: Please remove all those newlines and run `x.py test src/tools/clippy --bless` once.

Comment (mejrs) [reply src/tools/clippy/tests/ui/large_stack_frames.rs]: The blank lines are intentional for now, I will address them later. I wanted to check that CI got green but that command is broken and I didn't have the time to debug clippy at the time.

Comment (mejrs) [reply src/tools/clippy/tests/ui/large_stack_frames.rs]: https://rust-lang.zulipchat.com/#narrow/channel/257328-clippy/topic/clippy.20ui.20tests.20broken/with/521708167

**Comment by SparrowLii** [comment]
This change makes sense. I know little about unsized locals, so I'd like to have someone more experienced take a look.
r? compiler

**Comment by compiler-errors** [comment]
Yippee

@bors r+

File: compiler/rustc_feature/src/removed.rs (hunk 1 above)
Comment (compiler-errors) [reply compiler/rustc_feature/src/removed.rs]: Wait yeah, you should apply this change.

**Review by compiler-errors — CHANGES_REQUESTED** [review]

**Comment by compiler-errors** [comment]
r=me after

**Comment by compiler-errors** [comment]
ty

@bors r+

**Comment by mejrs** [comment]
Woops lol. I'll bless it tomorrow.

**Comment by compiler-errors** [comment]
yeah, pls rebase

@bors r- delegate+
