### PR TITLE
Escape combining characters in char::Debug

### LINKED ISSUE #41922: Debug printing of combining characters is wrong
Minimal example:

```
fn main() {
    let s = "e\u{301}";
    println!("str: {:?}", s);
    println!("bytes: {:?}", s.chars().collect::<Vec<_>>());
}
```

[(playground link)](https://is.gd/MVseMd)

Expected output is either:

```
str: "é"
bytes: ['e', '\u{301}']
```

Or:

```
str: "é"
bytes: ['e', '◌́']
```

Actual output:

```
str: "é"
bytes: ['e', '́']
```

Note that the combining accent prints over the single quote. This is confusing and shouldn't happen.

### PR DESCRIPTION
**Pull request by varkor**
Although combining characters are technically printable, they make little sense to print on their own with `Debug`: it'd be better to escape them like non-printable characters.

This is a breaking change, but I imagine the fact `escape_debug` is rare and almost certainly primarily used for debugging that this is an acceptable change.
Resolves #41922.

r? @alexcrichton 
cc @clarcharr

### CODE REVIEW

**Comment by clarcharr** [comment]
LGTM although the character ranges should probably be generated with a script instead of hard-coded, as they can change across unicode versions.

**Comment by varkor** [comment]
@clarcharr: have you got any ideas for how to detect ranges programmatically? Apart from parsing the Unicode symbol names (which does not seem robust), I couldn't find any reasonable suggestion for how to do this automatically.

**Comment by SimonSapin** [comment]
This PR is modifying the `char::escape_debug`. When calling this method directly or through `impl Debug for char`, there is only one code point being printed so the idea of escaping code points that do not make much sense on their own seems fine.

However this method is also used in `impl Debug for str` and in `str::escape_debug`. #41922 itself does not expect the behavior to change there and I agree. However that means making them based on something other than `char::escape_debug`. Should that other thing be exposed in new public API?

----

Regarding this being a breaking change, I think I’d be ok with documenting that the exact set of code points being escaped or not is not stable outside of the ASCII range.

The current doc-comment is already out of sync with the implementation: it claims that anything non-ASCII is escaped, which hasn’t been the case since https://github.com/rust-lang/rust/pull/34485.

----

I also agree with not hard-coding code point ranges, and instead extracting more Unicode data in `src/libstd_unicode/unicode.py`. However it’s unclear to me what exactly should be included. `Canonical_Combining_Class` is about reordering during normalization and probably not what we want. The [`Diacritic`](https://unicode.org/reports/tr44/#Diacritic) property is defined as:

> Characters that linguistically modify the meaning of another character to which they apply. Some diacritics are not combining characters, and some combining characters are not diacritics.

Then there’s the [`*Mark`](https://unicode.org/reports/tr44/#GC_Values_Table) properties:

> | Abbr | Long | Description |
> | -- | -- | -- |
> | Mn | Nonspacing_Mark | a nonspacing combining mark (zero advance width) |
> | Mc | Spacing_Mark | a spacing combining mark (positive advance width) |
> | Me | Enclosing_Mark | an enclosing combining mark |
> | M | Mark | Mn \| Mc \| Me |

However #41922 suggests that only nonspacing marks are problematic?

**Comment by clarcharr** [comment]
I'd be fine with just going for nonspacing marks.

As for `str::escape_debug` goes, I'd personally opt for escaping any combination of nonspacing marks at the beginning of the string, although it's unclear if that would actually solve the problem. I'm fine with just leaving it with the current behaviour for now.

**Comment by varkor** [comment]
> However that means making them based on something other than `char::escape_debug`. Should that other thing be exposed in new public API?

Yeah, I'm not sure about this. It'd be nicer if there was an extra argument (`single: bool`), so the behaviour could be different for individual characters, but we obviously can't change the signature. A specific public extra method that _just_ special-cases non-spacing combining characters seems a little specialised, though.

> The current doc-comment is already out of sync with the implementation: it claims that anything non-ASCII is escaped, which hasn’t been the case since #34485.

Which doc comment are you referring to here?

> I also agree with not hard-coding code point ranges, and instead extracting more Unicode data in `src/libstd_unicode/unicode.py`

I have a change that uses `Mn` instead of hard-coding ranges, pending the decision about the method / effect on `str` impls.

**Comment by varkor** [comment]
@SimonSapin: as far as I can tell, there's an issue using `src/libstd_unicode/unicode.py` here, as it's not available for `core`, which is where the formatting trait is defined. Is it worth moving it, or taking a different approach?

**Comment by clarcharr** [comment]
Wasn't the goal of having `libstd_unicode` separate from `libcore` to avoid having to include Unicode tables in libcore? Which makes it suddenly interesting considering how the changes to `escape_debug` make that less necessary. Or, I'm probably missing something.

Personally I really dislike the `libstd_unicode` façade, as it tends to get way less attention than libcore, liballoc, and libstd, which leads to bugs like #44303. I'm still confused why it exists and I don't think I've actually seen it explained somewhere.

**Comment by SimonSapin** [comment]
https://github.com/rust-lang/rust/pull/49698 merges `std_unicode` into `core`.

It might be interesting to replace `printable.py` (formerly `char_private.py`) and `unicode.py` with something based on https://github.com/BurntSushi/ucd-generate.

**Comment by varkor** [comment]
@SimonSapin: #49698 makes everything much more pleasant :)

I've rebased on top of it (and also cleaned up `unicode.py` whilst I was at it, because it had some slightly annoying behaviour before).

**Comment by SimonSapin** [comment]
@varkor Thanks for your work on this. However I’m still not sure what the right thing to do here is, in terms of what characters exactly to escape or not in which context. Do you know what other languages do for debug-printing Unicode strings and characters?

**Comment by varkor** [comment]
@SimonSapin: [Swift does something similar](https://github.com/rust-lang/rust/issues/41922#issuecomment-375290541) to the proposed change here. I haven't tried working out exactly which characters they choose to escape, but it seems reasonable to assume they choose either the same, or a similar category.

**Comment by varkor** [comment]
Ah, so Swift actually escapes any non-ASCII character, which is what Rust used to do before https://github.com/rust-lang/rust/issues/24588:
https://github.com/apple/swift/blob/c35d508600516b892732e2fd3f0f0a17ca4562ba/stdlib/public/core/UnicodeScalar.swift#L197-L252
So this is new territory, and it makes sense to go with what we think is most sensible: in this case, I think the suggestion of `Mn` is a reasonable choice.

**Comment by TimNN** [comment]
@SimonSapin: Friendly triage ping :)

**Comment by pietroalbini** [comment]
Ping from triage! Can @SimonSapin or someone else from @rust-lang/libs review this?

**Comment by pietroalbini** [comment]
Ping from triage! This PR still needs a review! Can @SimonSapin or someone else from @rust-lang/libs review this?

**Comment by shepmaster** [comment]
Ping from triage, @aturon. This PR has not been reviewed by @rust-lang/libs in multiple weeks.

**Comment by SimonSapin** [comment]
More than code review, this needs a design decision

**Comment by alexcrichton** [comment]
@SimonSapin that's a decision for @rust-lang/libs, right? When you get a chance, could you (or @varkor) summarize the decision that needs to be made?

**Comment by alexcrichton** [comment]
Ok thanks! I'll make sure this comes up at the next libs triage

**Comment by SimonSapin** [comment]
In my mind the question is rather: what is the exact set of code points that should be escaped or not? Unicode has a number of "properties" (see above) that seem relevant, but it’s not clear to me which one (or which combination) is most appropriate.

**Comment by SimonSapin** [comment]
Also, `char::escape_debug` is used both in:

* `impl Debug for char` where we only ever have a single code point, so a combining code point never has anything to combine with. So this change makes sense
* `impl Debug for str` (for each `char` in the string) where we probably do *not* want that same behavior. Maybe?

But then if these two impls want to escape different sets of code points, should there be two methods like `char::escape_debug`?

**Comment by varkor** [comment]
@SimonSapin: note that I changed the implementation so that only the `Debug` impl for `char` is affected — `Debug` for `str` is entirely unchanged. So now this is purely a formatting change. It's unclear what `char::escape_debug` is used for in general though, so we might want to change it too.

**Comment by Manishearth** [comment]
An alternative to escaping them is prepending them with a zero width non breaking space or just a regular non breaking space, which forces them to render as their uncombined form.

**Comment by clarcharr** [comment]
@Manishearth in the original issue I recommended printing a dotted circle (U+25CC) which is generally used for demonstrating combining marks, although it was preferred to just escape them so that the result remains valid Rust.

A zero-width space might help for debug-printing strings, though.

**Comment by Manishearth** [comment]
The dotted circle version of combining chars is what they do in isolation
when they start text (or after any kind of non breaking space), I don't
think it's a good idea to combine them with the dotted circle code point to
get this. That code point won't be rescaled based on the size of the
combiner, it's not very good for rendering combiners. Use non breaking
spaces if you want a dotted circle to show.

(Some fonts don't use dotted circles for combiners but they render
something similarly sensible)

**Comment by SimonSapin** [comment]
The libs team discussed this today, consensus was that we’d prefer to keep `Debug for char`, `Debug for str`, and `escape_debug` all consistent with each other. The way to do that while fixing #41922 is to treat `char` as a one code point string, and escape combining marks when they’re the *first code point* in a string.

@Manishearth mentioned that the `Grapheme_Extend` derived property might be more appropriate to determine which extra code points to escape.

The PR currently adds a public unstable method `char::is_nonspacing_mark`, but I’d prefer to have its users call the crate-private function directly instead.

@varkor Could you make these changes?

**Comment by varkor** [comment]
@SimonSapin: it would be great to finish this off before https://github.com/rust-lang/rust/pull/50922 and friends get merged, to avoid refactoring all over again.

**Comment by clarcharr** [comment]
@vakor I was actually planning to rebase over these changes some time tomorrow so this is going to have to be merged earlier anyway.

**Comment by varkor** [comment]
@clarcharr: ah, that sounds great! :)

File: src/liballoc/str.rs [hunk 1]
```diff
@@ -377,12 +377,15 @@ impl str {
...
+    /// Note: only extended grapheme codepoints that begin the string will be
+    /// escaped.
+    ///
     /// [`char::escape_debug`]: primitive.char.html#method.escape_debug
     #[unstable(feature = "str_escape",
                reason = "return type may change to be an iterator",
                issue = "27791")]
     pub fn escape_debug(&self) -> String {
-        self.chars().flat_map(|c| c.escape_debug()).collect()
+        self.chars().enumerate().flat_map(|(i, c)| c.escape_debug_ext(i == 0)).collect()
```
Comment (SimonSapin) [inline src/liballoc/str.rs]: Please write this as follow to avoid counting code points:

```rust
    let mut string = String::with_capacity(self.len());
    let mut chars = self.chars();
    if let Some(first) = chars.next() {
        string.extend(first.escape_debug_ext(true))
    }
    string.extend(chars.flat_map(|c| c.escape_debug_ext(false)));
    string
```

File: src/liballoc/tests/str.rs [hunk 2]
```diff
@@ -999,6 +999,7 @@ fn test_escape_debug() {
     assert_eq!("\u{10000}\u{10ffff}".escape_debug(), "\u{10000}\\u{10ffff}");
     assert_eq!("ab\u{200b}".escape_debug(), "ab\\u{200b}");
     assert_eq!("\u{10d4ea}\r".escape_debug(), "\\u{10d4ea}\\r");
+    assert_eq!("\u{301}a\u{301}bé\u{e000}".escape_debug(), "\\u{301}a\u{301}bé\\u{e000}");
```
Comment (SimonSapin) [inline src/liballoc/tests/str.rs]: (I’ve had to read this a couple times. Maybe add a comment above to call out the difference between `\u{}` and `\\u{}` in expected results?)

File: src/libcore/unicode/tables.rs [hunk 3]
```diff
@@ -93,7 +93,7 @@ pub mod general_category {
             0x03ff000003ff0000
         ],
         r4: [
-            0, 1, 2, 3, 3, 3, 4, 3, 3, 3, 3, 3, 3, 5, 6, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
+            0, 1, 2, 3, 3, 3, 4, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
```
Comment (SimonSapin) [inline src/libcore/unicode/tables.rs]: It’s very worrying that existing tables change without the Unicode version number changing. Is this a bug in `unicode.py`? Or do you get the same changes by re-running unmodified `unicode.py`?

File: src/libcore/unicode/unicode.py [hunk 4]
```diff
@@ -21,11 +21,14 @@
 # - UnicodeData.txt
 #
 # Since this should not require frequent updates, we just store this
-# out-of-line and check the unicode.rs file into git.
+# out-of-line and check the unicode.py file into git.
```
Comment (SimonSapin) [inline src/libcore/unicode/unicode.py]: I’m pretty sure that the original comment did mean `.rs`, even though the generated file has since been renamed a couple times (now `tables.rs`).

**Review by SimonSapin — CHANGES_REQUESTED** [review]
> Personally, it seems reasonable to me to escape all Grapheme_Extend characters in a string, so maybe that would be acceptable?

That is not acceptable, especially for many non-Latin-based writing systems. But I see that after since that comment you’ve already implementing the special treatment for the first code point.

File: src/libcore/unicode/unicode.py (hunk 4 above)
Comment (varkor) [reply src/libcore/unicode/unicode.py]: Ah, I thought it could have been either. I've updated it to `tables.rs`.

File: src/libcore/unicode/tables.rs (hunk 3 above)
Comment (varkor) [reply src/libcore/unicode/tables.rs]: Turns out that the files I downloaded before were truncated. Rerunning the version of `unicode.py` in the PR fixed it. Whoops.

**Review by SimonSapin — APPROVED** [review]
