### PR TITLE
Avoid collecting associated types for undefined trait

### LINKED ISSUE #137508: ICE: `attempted .def_id() on invalid res: Err`
### Code

```Rust
trait Tr {
    type Item;
}

type A2 = dyn for<'a> Tr + ?foo(b);

fn main() {}
```

<details><summary><strong>Original Code (Fuzzing)</strong></summary>
<p>

```Rust
trait Tr: ?Sized {
    type Item = &usize;
    //~^ ERROR 18:17: 18:18: in the trait associated type is declared without lifetime parameters, so using a borrowed type for them requires that lifetime to come from the implemented type

    fn poke(&mut self, item: Self::Item) {
        self += *item;
    }
}
//~^ ERROR `?Trait` is not permitted in supertraits

type A1 = dyn Tr + (?Sized);
//~^ ERROR `?Trait` is not permitted in trait object types
type A2 = dyn for<'adds_bnd> Tr + (?simd_fexp2(a));
//~^ ERROR `?Trait` is not permitted in trait object types

fn main() {}


// /root/workspace/seeds_250219/tests/ui/maybe-bounds.rs
```

</p>
</details>

### Meta

`rustc --version --verbose`:
```
rustc 1.87.0-nightly (f8a913b13 2025-02-23)
binary: rustc
commit-hash: f8a913b1381e90379c7ca63ac2b88b9518936628
commit-date: 2025-02-23
host: x86_64-apple-darwin
release: 1.87.0-nightly
LLVM version: 20.1.0
```

### Error output

```
error[E0658]: `?Trait` is not permitted in trait object types
 --> 05C5.rs:5:28
  |
5 | type A2 = dyn for<'a> Tr + ?foo(b);
  |                            ^^^^^^^
  |
  = help: add `#![feature(more_maybe_bounds)]` to the crate attributes to enable
  = note: this compiler was built on 2025-02-23; consider upgrading it if it is out of date

error[E0405]: cannot find trait `foo` in this scope
 --> 05C5.rs:5:29
  |
5 | type A2 = dyn for<'a> Tr + ?foo(b);
  |                             ^^^ not found in this scope

error[E0412]: cannot find type `b` in this scope
 --> 05C5.rs:5:33
  |
5 | type A2 = dyn for<'a> Tr + ?foo(b);
  |                                 ^ not found in this scope


thread 'rustc' panicked at /rustc/f8a913b1381e90379c7ca63ac2b88b9518936628/compiler/rustc_hir/src/def.rs:683:45:
attempted .def_id() on invalid res: Err
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
thread 'rustc' panicked at /rustc/f8a913b1381e90379c7ca63ac2b88b9518936628/compiler/rustc_hir/src/def.rs:683:45:
attempted .def_id() on invalid res: Err
stack backtrace:
   0: _rust_begin_unwind
   1: core::panicking::panic_fmt
   2: <dyn rustc_hir_analysis::hir_ty_lowering::HirTyLowerer>::check_for_required_assoc_tys
   3: <dyn rustc_hir_analysis::hir_ty_lowering::HirTyLowerer>::lower_trait_object_ty
   4: <dyn rustc_hir_analysis::hir_ty_lowering::HirTyLowerer>::lower_ty
   5: rustc_hir_analysis::collect::type_of::type_of
      [... omitted 1 frame ...]
   6: rustc_hir_analysis::collect::lower_item
   7: <rustc_hir_analysis::collect::CollectItemTypesVisitor as rustc_hir::intravisit::Visitor>::visit_item
   8: rustc_hir_analysis::check::wfcheck::check_item
   9: rustc_hir_analysis::check::wfcheck::check_well_formed
      [... omitted 1 frame ...]
  10: <rustc_middle::hir::ModuleItems>::par_opaques::<rustc_hir_analysis::check::wfcheck::check_mod_type_wf::{closure#4}>::{closure#0}
  11: rustc_hir_analysis::check::wfcheck::check_mod_type_wf
      [... omitted 1 frame ...]
  12: rustc_hir_analysis::check_crate
  13: rustc_interface::passes::run_required_analyses
  14: rustc_interface::passes::analysis
      [... omitted 1 frame ...]
  15: rustc_interface::passes::create_and_enter_global_ctxt::<core::option::Option<rustc_interface::queries::Linker>, rustc_driver_impl::run_compiler::{closure#0}::{closure#2}>
  16: rustc_interface::interface::run_compiler::<(), rustc_driver_impl::run_compiler::{closure#0}>::{closure#1}
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

error: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: please make sure that you have updated to the latest nightly

note: please attach the file at `/Volumes/T7/workspace/250224 scratch/codes/rustc-ice-2025-02-24T05_09_01-67498.txt` to your bug report

query stack during panic:
#0 [type_of] expanding type alias `A2`
#1 [check_well_formed] checking that `A2` is well-formed
#2 [check_mod_type_wf] checking that types are well-formed in top-level module
#3 [analysis] running analysis passes on this crate
end of query stack
error: aborting due to 3 previous errors

Some errors have detailed explanations: E0405, E0412, E0658.
For more information about an error, try `rustc --explain E0405`.
```

</p>
</details>

### Notes
- ICE location: `compiler/rustc_hir/src/def.rs Line-683`
https://github.com/rust-lang/rust/blob/f8a913b1381e90379c7ca63ac2b88b9518936628/compiler/rustc_hir/src/def.rs#L677-L684

### LINKED ISSUE #137554: ICE: missing `associated_item_or_field_def_ids` for DefId
snippet:
````rust
fn main() -> dyn Iterator + ?Iterator::advance_by(usize) {
    todo!()
}

````

Version information
````
rustc 1.87.0-nightly (e0be1a026 2025-02-24)
binary: rustc
commit-hash: e0be1a02626abef2878cb7f4aaef7ae409477112
commit-date: 2025-02-24
host: x86_64-unknown-linux-gnu
release: 1.87.0-nightly
LLVM version: 20.1.0

````

Possibly related line of code:
https://github.com/rust-lang/rust/blob/e0be1a02626abef2878cb7f4aaef7ae409477112/compiler/rustc_metadata/src/rmeta/decoder.rs#L973-L985

Command:
`/home/matthias/.rustup/toolchains/master/bin/rustc `

<details><summary><strong>Program output</strong></summary>
<p>

```
error[E0658]: `?Trait` is not permitted in trait object types
 --> /tmp/icemaker_global_tempdir.GmrobLH26bcS/rustc_testrunner_tmpdir_reporting.71dArq3UUixW/mvce.rs:1:29
  |
1 | fn main() -> dyn Iterator + ?Iterator::advance_by(usize) {
  |                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = help: add `#![feature(more_maybe_bounds)]` to the crate attributes to enable
  = note: this compiler was built on 2025-02-24; consider upgrading it if it is out of date

error[E0404]: expected trait, found associated function `Iterator::advance_by`
 --> /tmp/icemaker_global_tempdir.GmrobLH26bcS/rustc_testrunner_tmpdir_reporting.71dArq3UUixW/mvce.rs:1:30
  |
1 | fn main() -> dyn Iterator + ?Iterator::advance_by(usize) {
  |                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^ not a trait

error: internal compiler error: compiler/rustc_metadata/src/rmeta/decoder.rs:979:9: missing `associated_item_or_field_def_ids` for DefId(2:9144 ~ core[90b8]::iter::traits::iterator::Iterator::advance_by)


thread 'rustc' panicked at compiler/rustc_metadata/src/rmeta/decoder.rs:979:9:
Box<dyn Any>
stack backtrace:
   0:     0x75161697c124 - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::hd9ec0f3056d90740
   1:     0x75161701632c - core::fmt::write::h0d8376a499e0871d
   2:     0x751618095a51 - std::io::Write::write_fmt::hf688cf9460f28ca2
   3:     0x75161697bf82 - std::sys::backtrace::BacktraceLock::print::h4ca5e45855090a7a
   4:     0x75161697e78e - std::panicking::default_hook::{{closure}}::h181472065423d3d9
   5:     0x75161697e364 - std::panicking::default_hook::h68110b3f28030711
   6:     0x751615adda87 - std[6ca4657e2107f847]::panicking::update_hook::<alloc[a2d81cc64f826ec1]::boxed::Box<rustc_driver_impl[3593385ee6d6136e]::install_ice_hook::{closure#1}>>::{closure#0}
   7:     0x75161697f003 - std::panicking::rust_panic_with_hook::h0802d830fc76ae3f
   8:     0x751615b19b81 - std[6ca4657e2107f847]::panicking::begin_panic::<rustc_errors[db683afb8460ed88]::ExplicitBug>::{closure#0}
   9:     0x751615b0df96 - std[6ca4657e2107f847]::sys::backtrace::__rust_end_short_backtrace::<std[6ca4657e2107f847]::panicking::begin_panic<rustc_errors[db683afb8460ed88]::ExplicitBug>::{closure#0}, !>
  10:     0x751615b0a919 - std[6ca4657e2107f847]::panicking::begin_panic::<rustc_errors[db683afb8460ed88]::ExplicitBug>
  11:     0x751615b23581 - <rustc_errors[db683afb8460ed88]::diagnostic::BugAbort as rustc_errors[db683afb8460ed88]::diagnostic::EmissionGuarantee>::emit_producing_guarantee
  12:     0x7516160f3026 - rustc_middle[d80101abd097f72b]::util::bug::opt_span_bug_fmt::<rustc_span[74cd7f09f1ca77f9]::span_encoding::Span>::{closure#0}
  13:     0x7516160dc58a - rustc_middle[d80101abd097f72b]::ty::context::tls::with_opt::<rustc_middle[d80101abd097f72b]::util::bug::opt_span_bug_fmt<rustc_span[74cd7f09f1ca77f9]::span_encoding::Span>::{closure#0}, !>::{closure#0}
  14:     0x7516160dc3fb - rustc_middle[d80101abd097f72b]::ty::context::tls::with_context_opt::<rustc_middle[d80101abd097f72b]::ty::context::tls::with_opt<rustc_middle[d80101abd097f72b]::util::bug::opt_span_bug_fmt<rustc_span[74cd7f09f1ca77f9]::span_encoding::Span>::{closure#0}, !>::{closure#0}, !>
  15:     0x7516144ccbc0 - rustc_middle[d80101abd097f72b]::util::bug::bug_fmt
  16:     0x751616058fcf - <rustc_metadata[48f9dac3cd275b9a]::creader::CrateMetadataRef>::missing
  17:     0x7516172c1962 - rustc_metadata[48f9dac3cd275b9a]::rmeta::decoder::cstore_impl::provide_extern::associated_item_def_ids
  18:     0x7516172c12e3 - rustc_query_impl[a3e1d005031b8bb]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[a3e1d005031b8bb]::query_impl::associated_item_def_ids::dynamic_query::{closure#2}::{closure#0}, rustc_middle[d80101abd097f72b]::query::erase::Erased<[u8; 16usize]>>
  19:     0x7516172c1289 - <rustc_query_impl[a3e1d005031b8bb]::query_impl::associated_item_def_ids::dynamic_query::{closure#2} as core[90b8396b6039faa7]::ops::function::FnOnce<(rustc_middle[d80101abd097f72b]::ty::context::TyCtxt, rustc_span[74cd7f09f1ca77f9]::def_id::DefId)>>::call_once
  20:     0x7516172bf74f - rustc_query_system[de6c792d11e5b678]::query::plumbing::try_execute_query::<rustc_query_impl[a3e1d005031b8bb]::DynamicConfig<rustc_query_system[de6c792d11e5b678]::query::caches::DefIdCache<rustc_middle[d80101abd097f72b]::query::erase::Erased<[u8; 16usize]>>, false, false, false>, rustc_query_impl[a3e1d005031b8bb]::plumbing::QueryCtxt, false>
  21:     0x7516172bf1e1 - rustc_query_impl[a3e1d005031b8bb]::query_impl::associated_item_def_ids::get_query_non_incr::__rust_end_short_backtrace
  22:     0x7516179ec7a1 - rustc_ty_utils[b051470940286a68]::assoc::associated_items
  23:     0x7516179ec634 - rustc_query_impl[a3e1d005031b8bb]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[a3e1d005031b8bb]::query_impl::associated_items::dynamic_query::{closure#2}::{closure#0}, rustc_middle[d80101abd097f72b]::query::erase::Erased<[u8; 8usize]>>
  24:     0x75161711b272 - rustc_query_system[de6c792d11e5b678]::query::plumbing::try_execute_query::<rustc_query_impl[a3e1d005031b8bb]::DynamicConfig<rustc_query_system[de6c792d11e5b678]::query::caches::DefIdCache<rustc_middle[d80101abd097f72b]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[a3e1d005031b8bb]::plumbing::QueryCtxt, false>
  25:     0x75161711c4a8 - rustc_query_impl[a3e1d005031b8bb]::query_impl::associated_items::get_query_non_incr::__rust_end_short_backtrace
  26:     0x751617858458 - rustc_middle[d80101abd097f72b]::query::plumbing::query_get_at::<rustc_query_system[de6c792d11e5b678]::query::caches::DefIdCache<rustc_middle[d80101abd097f72b]::query::erase::Erased<[u8; 8usize]>>>
  27:     0x751615c22fcf - <core[90b8396b6039faa7]::iter::adapters::flatten::FlattenCompat<_, _> as core[90b8396b6039faa7]::iter::traits::iterator::Iterator>::fold::flatten::<core[90b8396b6039faa7]::iter::adapters::filter_map::FilterMap<core[90b8396b6039faa7]::slice::iter::Iter<rustc_hir[6e224bfe6d508dae]::hir::AssocItemConstraint>, <dyn rustc_hir_analysis[da7d2587c78354bd]::hir_ty_lowering::HirTyLowerer>::check_for_required_assoc_tys::{closure#1}::{closure#0}>, (), core[90b8396b6039faa7]::iter::traits::iterator::Iterator::for_each::call<(rustc_span[74cd7f09f1ca77f9]::symbol::Symbol, &rustc_middle[d80101abd097f72b]::ty::assoc::AssocItem), <hashbrown[ed219d29d174ff2d]::map::HashMap<rustc_span[74cd7f09f1ca77f9]::symbol::Symbol, &rustc_middle[d80101abd097f72b]::ty::assoc::AssocItem, rustc_hash[733386de75a58a40]::FxBuildHasher> as core[90b8396b6039faa7]::iter::traits::collect::Extend<(rustc_span[74cd7f09f1ca77f9]::symbol::Symbol, &rustc_middle[d80101abd097f72b]::ty::assoc::AssocItem)>>::extend<core[90b8396b6039faa7]::iter::adapters::flatten::Flatten<core[90b8396b6039faa7]::iter::adapters::filter_map::FilterMap<core[90b8396b6039faa7]::slice::iter::Iter<rustc_hir[6e224bfe6d508dae]::hir::PolyTraitRef>, <dyn rustc_hir_analysis[da7d2587c78354bd]::hir_ty_lowering::HirTyLowerer>::check_for_required_assoc_tys::{closure#1}>>>::{closure#0}>::{closure#0}>::{closure#0}
  28:     0x751617ee2e84 - <dyn rustc_hir_analysis[da7d2587c78354bd]::hir_ty_lowering::HirTyLowerer>::lower_trait_object_ty
  29:     0x7516178d5786 - <dyn rustc_hir_analysis[da7d2587c78354bd]::hir_ty_lowering::HirTyLowerer>::lower_ty
  30:     0x7516178ce0d5 - <dyn rustc_hir_analysis[da7d2587c78354bd]::hir_ty_lowering::HirTyLowerer>::lower_fn_ty
  31:     0x7516178cd969 - rustc_hir_analysis[da7d2587c78354bd]::collect::lower_fn_sig_recovering_infer_ret_ty
  32:     0x7516178cb8dd - rustc_hir_analysis[da7d2587c78354bd]::collect::fn_sig
  33:     0x7516172c6bad - rustc_query_impl[a3e1d005031b8bb]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[a3e1d005031b8bb]::query_impl::fn_sig::dynamic_query::{closure#2}::{closure#0}, rustc_middle[d80101abd097f72b]::query::erase::Erased<[u8; 24usize]>>
  34:     0x7516172c6b6d - <rustc_query_impl[a3e1d005031b8bb]::query_impl::fn_sig::dynamic_query::{closure#2} as core[90b8396b6039faa7]::ops::function::FnOnce<(rustc_middle[d80101abd097f72b]::ty::context::TyCtxt, rustc_span[74cd7f09f1ca77f9]::def_id::DefId)>>::call_once
  35:     0x7516172c98ba - rustc_query_system[de6c792d11e5b678]::query::plumbing::try_execute_query::<rustc_query_impl[a3e1d005031b8bb]::DynamicConfig<rustc_query_system[de6c792d11e5b678]::query::caches::DefIdCache<rustc_middle[d80101abd097f72b]::query::erase::Erased<[u8; 24usize]>>, false, false, false>, rustc_query_impl[a3e1d005031b8bb]::plumbing::QueryCtxt, false>
  36:     0x7516172c8fad - rustc_query_impl[a3e1d005031b8bb]::query_impl::fn_sig::get_query_non_incr::__rust_end_short_backtrace
  37:     0x7516178884a3 - <rustc_hir_analysis[da7d2587c78354bd]::collect::CollectItemTypesVisitor as rustc_hir[6e224bfe6d508dae]::intravisit::Visitor>::visit_item
  38:     0x75161787b3bb - rustc_hir_analysis[da7d2587c78354bd]::check::wfcheck::check_well_formed
  39:     0x75161787b1cd - rustc_query_impl[a3e1d005031b8bb]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[a3e1d005031b8bb]::query_impl::check_well_formed::dynamic_query::{closure#2}::{closure#0}, rustc_middle[d80101abd097f72b]::query::erase::Erased<[u8; 1usize]>>
  40:     0x75161787ac84 - rustc_query_system[de6c792d11e5b678]::query::plumbing::try_execute_query::<rustc_query_impl[a3e1d005031b8bb]::DynamicConfig<rustc_data_structures[f99b040610e16207]::vec_cache::VecCache<rustc_span[74cd7f09f1ca77f9]::def_id::LocalDefId, rustc_middle[d80101abd097f72b]::query::erase::Erased<[u8; 1usize]>, rustc_query_system[de6c792d11e5b678]::dep_graph::graph::DepNodeIndex>, false, false, false>, rustc_query_impl[a3e1d005031b8bb]::plumbing::QueryCtxt, false>
  41:     0x75161787a73f - rustc_query_impl[a3e1d005031b8bb]::query_impl::check_well_formed::get_query_non_incr::__rust_end_short_backtrace
  42:     0x751617877f5d - rustc_hir_analysis[da7d2587c78354bd]::check::wfcheck::check_mod_type_wf
  43:     0x751617877d5f - rustc_query_impl[a3e1d005031b8bb]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[a3e1d005031b8bb]::query_impl::check_mod_type_wf::dynamic_query::{closure#2}::{closure#0}, rustc_middle[d80101abd097f72b]::query::erase::Erased<[u8; 1usize]>>
  44:     0x751617fd6e16 - rustc_query_system[de6c792d11e5b678]::query::plumbing::try_execute_query::<rustc_query_impl[a3e1d005031b8bb]::DynamicConfig<rustc_query_system[de6c792d11e5b678]::query::caches::DefaultCache<rustc_span[74cd7f09f1ca77f9]::def_id::LocalModDefId, rustc_middle[d80101abd097f72b]::query::erase::Erased<[u8; 1usize]>>, false, false, false>, rustc_query_impl[a3e1d005031b8bb]::plumbing::QueryCtxt, false>
  45:     0x751617fd6bbf - rustc_query_impl[a3e1d005031b8bb]::query_impl::check_mod_type_wf::get_query_non_incr::__rust_end_short_backtrace
  46:     0x7516173256e9 - rustc_hir_analysis[da7d2587c78354bd]::check_crate
  47:     0x7516173a5d5c - rustc_interface[ccf5b96b158150d5]::passes::run_required_analyses
  48:     0x7516180919fa - rustc_interface[ccf5b96b158150d5]::passes::analysis
  49:     0x7516180919d9 - rustc_query_impl[a3e1d005031b8bb]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[a3e1d005031b8bb]::query_impl::analysis::dynamic_query::{closure#2}::{closure#0}, rustc_middle[d80101abd097f72b]::query::erase::Erased<[u8; 0usize]>>
  50:     0x7516180f570b - rustc_query_system[de6c792d11e5b678]::query::plumbing::try_execute_query::<rustc_query_impl[a3e1d005031b8bb]::DynamicConfig<rustc_query_system[de6c792d11e5b678]::query::caches::SingleCache<rustc_middle[d80101abd097f72b]::query::erase::Erased<[u8; 0usize]>>, false, false, false>, rustc_query_impl[a3e1d005031b8bb]::plumbing::QueryCtxt, false>
  51:     0x7516180f53f9 - rustc_query_impl[a3e1d005031b8bb]::query_impl::analysis::get_query_non_incr::__rust_end_short_backtrace
  52:     0x7516180d78bc - rustc_interface[ccf5b96b158150d5]::passes::create_and_enter_global_ctxt::<core[90b8396b6039faa7]::option::Option<rustc_interface[ccf5b96b158150d5]::queries::Linker>, rustc_driver_impl[3593385ee6d6136e]::run_compiler::{closure#0}::{closure#2}>::{closure#2}::{closure#0}
  53:     0x7516180cb160 - rustc_interface[ccf5b96b158150d5]::interface::run_compiler::<(), rustc_driver_impl[3593385ee6d6136e]::run_compiler::{closure#0}>::{closure#1}
  54:     0x751617fa6d48 - std[6ca4657e2107f847]::sys::backtrace::__rust_begin_short_backtrace::<rustc_interface[ccf5b96b158150d5]::util::run_in_thread_with_globals<rustc_interface[ccf5b96b158150d5]::util::run_in_thread_pool_with_globals<rustc_interface[ccf5b96b158150d5]::interface::run_compiler<(), rustc_driver_impl[3593385ee6d6136e]::run_compiler::{closure#0}>::{closure#1}, ()>::{closure#0}, ()>::{closure#0}::{closure#0}, ()>
  55:     0x751617fa7174 - <<std[6ca4657e2107f847]::thread::Builder>::spawn_unchecked_<rustc_interface[ccf5b96b158150d5]::util::run_in_thread_with_globals<rustc_interface[ccf5b96b158150d5]::util::run_in_thread_pool_with_globals<rustc_interface[ccf5b96b158150d5]::interface::run_compiler<(), rustc_driver_impl[3593385ee6d6136e]::run_compiler::{closure#0}>::{closure#1}, ()>::{closure#0}, ()>::{closure#0}::{closure#0}, ()>::{closure#1} as core[90b8396b6039faa7]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  56:     0x751617fa7aeb - std::sys::pal::unix::thread::Thread::new::thread_start::he66ac63033b645ec
  57:     0x7516122a370a - <unknown>
  58:     0x751612327aac - <unknown>
  59:                0x0 - <unknown>

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: please make sure that you have updated to the latest nightly

note: rustc 1.87.0-nightly (e0be1a026 2025-02-24) running on x86_64-unknown-linux-gnu

query stack during panic:
#0 [associated_item_def_ids] collecting associated items or fields of `core::iter::traits::iterator::Iterator::advance_by`
#1 [associated_items] collecting associated items of `core::iter::traits::iterator::Iterator::advance_by`
#2 [fn_sig] computing function signature of `main`
#3 [check_well_formed] checking that `main` is well-formed
#4 [check_mod_type_wf] checking that types are well-formed in top-level module
#5 [analysis] running analysis passes on this crate
end of query stack
error: aborting due to 3 previous errors

Some errors have detailed explanations: E0404, E0658.
For more information about an error, try `rustc --explain E0404`.

```

</p>
</details>

### PR DESCRIPTION
**Pull request by TaKO8Ki**
Fixes #137508
Fixes #137554

### CODE REVIEW

File: tests/ui/associated-types/ice-issue-137508.rs [hunk 1]
```diff
@@ -0,0 +1,10 @@
+trait Tr {
+    type Item;
+}
+
+fn main() {
+    let _: dyn Tr + ?Foo();
```
Comment (compiler-errors) [inline tests/ui/associated-types/ice-issue-137508.rs:6]: This doesn't have to do with parenthesized syntax. This also ICEs: `+ ?Foo<Assoc = ()>`.

Please edit the test name so it's more clear what it's testing, add the issue number as a comment like:

`// Fix for <https://github.com/issues....>`

File: compiler/rustc_hir_analysis/src/hir_ty_lowering/errors.rs [hunk 2]
```diff
@@ -789,13 +789,15 @@ impl<'tcx> dyn HirTyLowerer<'tcx> + '_ {
...
                     let ident = constraint.ident;
-                    let trait_def = path.res.def_id();
-                    let assoc_item = tcx.associated_items(trait_def).find_by_name_and_kind(
-                        tcx,
-                        ident,
-                        ty::AssocKind::Type,
-                        trait_def,
-                    );
+                    let trait_def = path.res.opt_def_id();
+                    let assoc_item = trait_def.and_then(|trait_def_id| {
```
Comment (compiler-errors) [inline compiler/rustc_hir_analysis/src/hir_ty_lowering/errors.rs:793]: Please leave a comment here saying that we don't want to unwrap a trait def id if it resolves incorrectly.

**Review by compiler-errors — CHANGES_REQUESTED** [review]

File: tests/ui/associated-types/ice-issue-137508.rs (hunk 1 above)
Comment (compiler-errors) [reply tests/ui/associated-types/ice-issue-137508.rs:6]: Sorry, I forgot to mention explicitly:

Change the test to use `+ ?Foo<Assoc = ()>` rather than the parentheses syntax.

Comment (TaKO8Ki) [reply tests/ui/associated-types/ice-issue-137508.rs:6]: Ok. Thanks.

**Comment by compiler-errors** [comment]
Actually, https://github.com/rust-lang/rust/issues/137554 is the same issue, but with a different def id.

Instead of calling `opt_def_id`, please match on the `Res::Def(DefKind::Trait, def_id)`. This will avoid ICEing in case the path resolves, but it resolves to the wrong kind of item. Then you can add a regression test for this too.

**Review by compiler-errors — CHANGES_REQUESTED** [review]
Add a test for #137554, and squash this into one commit.

Also no need to click the "request review" button; I'll review the PR when I have free time. All it does is give me an unnecessary notification.

**Review by compiler-errors — APPROVED** [review]
