### PR TITLE
Provide more context on type errors in const context

### LINKED ISSUE #147748: Default field values does not recognize generic param defaults
I expected to be able to write:

```rust
struct Foo<T = String> {
    x: T = String::new(),
}
```

but I got this error:

```text
error[E0308]: mismatched types
 --> src/lib.rs:4:12
  |
3 | struct Foo<T = String> {
  |            ---------- expected this type parameter
4 |     x: T = String::new(),
  |            ^^^^^^^^^^^^^ expected type parameter `T`, found `String`
  |
  = note: expected type parameter `T`
                     found struct `String`
```

It seems like this ought to work. But if not, we should at least improve the error.

### PR DESCRIPTION
**Pull request by estebank**
- On `const` and `static` point at the type (like we do for let bindings)
- On fn calls, point at const parameter in fn definition
- On type, point at const parameter in type definition
- On array type lengths, explain that array length is always `usize`
- On enum variant discriminant, mention `repr`
- On default field value using type parameter, provide more context (Fix rust-lang/rust#147748)

### CODE REVIEW

File: compiler/rustc_hir_typeck/src/lib.rs [hunk 1]
```diff
@@ -274,6 +276,126 @@ fn typeck_with_inspect<'tcx>(
...
+        }
+        hir::Node::AnonConst(anon)
+            if let hir::Node::ConstArg(parent) = tcx.parent_hir_node(anon.hir_id)
+                && let hir::Node::Expr(parent) = tcx.parent_hir_node(parent.hir_id)
+                && let hir::ExprKind::Repeat(_ty, _len) = parent.kind =>
+        {
+            // `[type; len]` in expr context.
+            err.note("array length can only be `usize`");
+        }
+        // FIXME: support method calls too.
```
Comment (Kivooeo) [inline compiler/rustc_hir_typeck/src/lib.rs:317]: do you have any plans to address this in the near future?

**Review by Kivooeo — APPROVED** [review]
looks like a big improvement to me, impl also seems fine

*[View changes since this review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/rust/153881/798a011ace1c2b5be80767ba1d97a4dff0546f93..3ede589dff8db175cf6d5e07a9dad2775c14d9b4)*

File: compiler/rustc_hir_typeck/src/lib.rs (hunk 1 above)
Comment (estebank) [reply compiler/rustc_hir_typeck/src/lib.rs:317]: I wish to. The approach I'd normally use is not available to me in this case (because the typeck hasn't completed, so I need a different way of getting the `DefId` corresponding to the resolved method), so I pushed these changes out while I figure that out.

Comment (Kivooeo) [reply compiler/rustc_hir_typeck/src/lib.rs:317]: yeah, that's fine, there's no rush
