### PR TITLE
rustdoc-json: discard non-local inherent impls for primitives

### LINKED ISSUE #114039: Rustdoc JSON includes unexpected items from `core` and `alloc`
Generated rustdoc JSON for every one of dozens of crates I've looked at seems to contain unexpected inlined items that look like an `impl str` block and its contents.

I expected to see this happen: rustdoc JSON file contains only the items defined or re-exported by the corresponding crate.

Instead, this happened: the rustdoc JSON file contains items like this:
```json
{
    "id": "2:12074",
    "crate_id": 2,
    "name": null,
    "span": null,
    "visibility": "default",
    "docs": null,
    "links": {},
    "attrs": [
        "#[cfg(not(test))]"
    ],
    "deprecation": null,
    "inner": {
        "impl": {
            "is_unsafe": false,
            "generics": {
                "params": [],
                "where_predicates": []
            },
            "provided_trait_methods": [],
            "trait": null,
            "for": {
                "primitive": "str"
            },
            "items": [
                "2:12075:816",
                "2:12076:23700",
                "2:12077:31130",
                "2:12078:31131",
                "2:12080:31132",
                "2:12083:20848",
                "2:12084:31133",
                "2:12085:314",
                "2:12086:24047",
                "2:12087:24043",
                "2:12089:24044",
                "2:12091:24045",
                "2:12093:24046",
                "2:12095:31134",
                "2:12096:31135",
                "2:12097:24069",
                "2:12098:24070",
                "2:12099:28134",
                "2:12100:28060",
                "2:12101:19933",
                "2:12102:28095",
                "2:12103:28078",
                "2:12104:19683",
                "2:12105:31136",
                "2:12106:28135",
                "2:12107:24086",
                "2:12110:24087",
                "2:12113:24088",
                "2:12116:19622",
                "2:12120:19623",
                "2:12124:19682",
                "2:12127:24078",
                "2:12130:24080",
                "2:12133:31137",
                "2:12136:31138",
                "2:12139:24082",
                "2:12142:24084",
                "2:12145:31139",
                "2:12148:31140",
                "2:12151:1866",
                "2:12154:31141",
                "2:12157:31142",
                "2:12160:31143",
                "2:12163:31144",
                "2:12165:31145",
                "2:12167:31146",
                "2:12169:31147",
                "2:12170:31148",
                "2:12171:31149",
                "2:12174:31150",
                "2:12177:20053",
                "2:12180:24089",
                "2:12183:31151",
                "2:12186:31152",
                "2:12189:31153",
                "2:12192:31154",
                "2:12194:23164",
                "2:12195:23856",
                "2:12196:23168",
                "2:12197:23169",
                "2:12198:23170",
                "2:12199:31155",
                "2:12201:1975",
                "2:12202:31156"
            ],
            "negative": false,
            "synthetic": false,
            "blanket_impl": null
        }
    }
}
```
In this example, `crate_id: 2` is `core` and here are the names of the items contained in that impl (also part of the rustdoc JSON):
```json
[
  "as_ptr",
  "parse",
  "strip_suffix",
  "is_ascii",
  "starts_with",
  "provide",
  "trim_end_matches",
  "split_ascii_whitespace",
  "try_from",
  "escape_default",
  "ceil_char_boundary",
  "as_bytes_mut",
  "get_mut",
  "matches",
  "char_indices",
  "into",
  "try_into",
  "slice_unchecked",
  "trim",
  "make_ascii_uppercase",
  "trim_start_matches",
  "trim_left_matches",
  "floor_char_boundary",
  "rsplit",
  "split_at_mut",
  "encode_utf16",
  "lines",
  "escape_unicode",
  "as_ascii",
  "lines_any",
  "split",
  "trim_end",
  "chars",
  "get",
  "split_at",
  "type_id",
  "as_bytes",
  "rmatches",
  "rsplit_once",
  "split_whitespace",
  "trim_right_matches",
  "split_inclusive",
  "trim_right",
  "eq_ignore_ascii_case",
  "get_unchecked",
  "trim_start",
  "get_unchecked_mut",
  "is_empty",
  "borrow_mut",
  "make_ascii_lowercase",
  "is_char_boundary",
  "from",
  "from",
  "strip_prefix",
  "find",
  "split_terminator",
  "match_indices",
  "into_iter",
  "as_mut_ptr",
  "trim_matches",
  "rsplitn",
  "contains",
  "split_once",
  "escape_debug",
  "rmatch_indices",
  "trim_left",
  "splitn",
  "rsplit_terminator",
  "bytes",
  "len",
  "ends_with",
  "borrow",
  "slice_mut_unchecked",
  "rfind"
]
```

Similarly, you can find items from `alloc`: [Trustfall playground](https://play.predr.ag/rustdoc#?f=1&q=cXVlcnkgewogIENyYXRlIHsKICAgICMgRmluZCBhIGZ1bmN0aW9uIGZyb20gYGFsbG9jYCB0byBnZXQgaXRzIGBjcmF0ZV9pZGAuCiAgICBpdGVtIHsKICAgICAgLi4uIG9uIEZ1bmN0aW9uIHsKICAgICAgICBuYW1lIEBmaWx0ZXIob3A6ICI9IiwgdmFsdWU6IFsiJGZuIl0pCiAgICAgICAgY3JhdGVfaWQgQHRhZwogICAgICB9CiAgICB9CgogICAgIyBUaGVuIGxvb2sgZm9yIG90aGVyIGZ1bmN0aW9ucyBmcm9tIGBhbGxvY2AgYnkgbWF0Y2hpbmcgb24gdGhlaXIgYGNyYXRlX2lkYC4KICAgIGl0ZW0gQGZvbGQgewogICAgICAuLi4gb24gRnVuY3Rpb24gewogICAgICAgIGNyYXRlX2lkIEBmaWx0ZXIob3A6ICI9IiwgdmFsdWU6IFsiJWNyYXRlX2lkIl0pCiAgICAgICAgbmFtZSBAb3V0cHV0CiAgICAgIH0KICAgIH0KICB9Cn0%3D&v=ewogICJmbiI6ICJpbnRvX2JveGVkX2J5dGVzIgp9)

Invocation for generating rustdoc JSON:
```
cargo +nightly rustdoc --package <crate_name> --all-features -- --document-private-items -Zunstable-options --output-format json
```

### Meta

`rustc --version --verbose`:
```
rustc 1.73.0-nightly (8771282d4 2023-07-23)
binary: rustc
commit-hash: 8771282d4e7a5c4569e49d1f878fb3ba90a974d0
commit-date: 2023-07-23
host: x86_64-unknown-linux-gnu
release: 1.73.0-nightly
LLVM version: 16.0.5
```

You can find a variety of pre-generated rustdoc JSON files with this issue here: https://github.com/obi1kenobi/crates-rustdoc/tree/main/rustdoc-v26/max-version

Briefly discussed in Zulip: https://rust-lang.zulipchat.com/#narrow/stream/266220-rustdoc/topic/Rustdoc.20JSON.3A.20Unexpected.20.60core.60.20items.20included.20in.20output

I'll have to work around this behavior to shield `cargo-semver-checks`, which uses the same codebase as the playground link above. I can hold off on updating the playground for, say, another week, but at some point I'll need to upgrade it to include my workaround which means those items will cease being shown.

@rustbot label +T-rustdoc +A-rustdoc-json

### PR DESCRIPTION
**Pull request by its-the-shrimp**
Fixes #114039
at least it should
r? @aDotInTheVoid

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
Please add a test (in `tests/rustdoc-json`).

**Comment by aDotInTheVoid** [comment]
1. This needs a test in `test/rustdoc-json`. Using [aux build](https://rustc-dev-guide.rust-lang.org/tests/compiletest.html#building-auxiliary-crates) you can add a 2nd crate, and put an impl there. Ideally this test should be added in it's own commit, and then in a 2nd commit you change rustdoc, and the test. This way it's easy to verify that the test checks the change being made, but if your not comfortable doing that I can just verify it manualy.

2. This seems to have broken the HTML output. When testing changes earlier in the rustdoc pipeline, use `./x test ./test/rustdoc ./tests/rustdoc-json` to check both backends. It looks like not having these impls collected breaks collecting methods availible via `Deref`

3. Out of interest, what does a "hello world" JSON output look like now? How much smaller is it?

@rustbot author

File: tests/rustdoc-json/primitives/no_primitive_impl_pollution.rs [hunk 1]
```diff
@@ -0,0 +1,2 @@
+//@ !has "$.index[*][?(@.inner=='impl')]"
```
Comment (its-the-shrimp) [inline tests/rustdoc-json/primitives/no_primitive_impl_pollution.rs:1]: I'm not sure if I've written this correctly, will this check for the presence of an object key, or just a string literal "impl"?

**Comment by its-the-shrimp** [comment]
>     3. Out of interest, what does a "hello world" JSON output look like now? How much smaller is it?

There's still pollution in `external_crates` & `paths`, but at least the `index` field now contains just 1 item - the crate's module

**Comment by aDotInTheVoid** [comment]
>  but at least the index field now contains just 1 item - the crate's module

Amazing! What sort of size-reduction does that give?

Also: This might be another way to test: `//@ count "$.index[*]" 1` for an empty module.

**Comment by its-the-shrimp** [comment]
All the tests pass, including the tests for docs of primitives with `rustc_doc_primitive`, so it seems like a separate step to add primitive impls isn't needed at all

**Comment by its-the-shrimp** [comment]
> Amazing! What sort of size-reduction does that give?

The size of docs for 1 file containing just `fn main() {}` went down from 320Kb to 192Kb

File: tests/rustdoc-json/primitives/no_primitive_impl_pollution.rs [hunk 2]
```diff
@@ -0,0 +1,2 @@
+//@ count "$.index[*]" 1
```
Comment (aDotInTheVoid) [inline tests/rustdoc-json/primitives/no_primitive_impl_pollution.rs:1]: It'd be nice if this could link back to the original issue, and also add a comment of *what* it's testing. At the moment, the purpose of this test won't be clear when viewed without context.

File: src/librustdoc/formats/renderer.rs [hunk 3]
```diff
@@ -86,8 +86,6 @@ pub(crate) fn run_format<'tcx, T: FormatRenderer<'tcx>>(
             }
 
             cx.mod_item_out()?;
-        // FIXME: checking `item.name.is_some()` is very implicit and leads to lots of special
```
Comment (aDotInTheVoid) [inline src/librustdoc/formats/renderer.rs:89]: This FIXME is still applicable I think. This was changed to be a match in https://github.com/rust-lang/rust/commit/1e55fc124382ab0fde9ac151b437bddb7b280554, but the broader point (about checking if the name is present being bad) still applies

File: src/librustdoc/formats/mod.rs [hunk 4]
```diff
@@ -43,8 +44,7 @@ impl Impl {
     // Returns true if this is an implementation on a "local" type, meaning:
     // the type is in the current crate, or the type and the trait are both
     // re-exported by the current crate.
-    pub(crate) fn is_on_local_type(&self, cx: &Context<'_>) -> bool {
-        let cache = cx.cache();
+    pub(crate) fn is_on_local_type(&self, cache: &Cache, tcx: TyCtxt<'_>) -> bool {
```
Comment (aDotInTheVoid) [inline src/librustdoc/formats/mod.rs:47]: Why make this change? All the call-sites seem to have a `Context`.

File: src/librustdoc/formats/cache.rs [hunk 5]
```diff
@@ -529,33 +527,26 @@ impl<'a, 'tcx> DocFolder for CacheBuilder<'a, 'tcx> {
...
-                            .or_insert_with(Vec::new)
-                            .push(impl_item.clone());
+                    if self.impl_ids.entry(did).or_default().insert(impl_def_id) {
+                        self.cache.impls.entry(did).or_default().push(impl_item.clone());
                     }
                 }
-            } else {
-                let trait_did = impl_item.trait_did().expect("no trait did");
-                self.cache.orphan_trait_impls.push((trait_did, dids, impl_item));
+            } else if let Some(impl_trait_id) = impl_trait_id {
```
Comment (aDotInTheVoid) [inline src/librustdoc/formats/cache.rs:548]: What's the purpose of this change?

**Review by aDotInTheVoid — CHANGES_REQUESTED** [review]
While the changes to `formats/cache.rs` are good, and I'd be happy to approve them, mixing cleanup and semantic changes makes it much more difficult to review (as I have to piece together what behaviour has changes, vs what's just nicer code).

In the future, I'd rather these changes were made in a seperate commit or PR.

File: src/librustdoc/formats/mod.rs (hunk 4 above)
Comment (its-the-shrimp) [reply src/librustdoc/formats/mod.rs:47]: At first I tried to use this function in the JSON logic, so I had to make it output-format-agnostic, but after I got rid of it, I realised keeping it that way might be beneficial in the future

File: src/librustdoc/formats/cache.rs (hunk 5 above)
Comment (its-the-shrimp) [reply src/librustdoc/formats/cache.rs]: Nevermind, forgot to revert that after a previous commit

File: tests/rustdoc-json/primitives/no_primitive_impl_pollution.rs (hunk 2 above)
Comment (its-the-shrimp) [reply tests/rustdoc-json/primitives/no_primitive_impl_pollution.rs]: I also renamed the test to `the_smallest.rs`, but I'm not sure if that's the most fitting name

File: src/librustdoc/formats/mod.rs (hunk 4 above)
Comment (aDotInTheVoid) [reply src/librustdoc/formats/mod.rs:47]: Could you revert this?

File: src/librustdoc/json/mod.rs [hunk 6]
```diff
@@ -217,10 +217,12 @@ impl<'tcx> FormatRenderer<'tcx> for JsonRenderer<'tcx> {
     fn after_krate(&mut self) -> Result<(), Error> {
         debug!("Done with crate");
 
+        /*
```
Comment (aDotInTheVoid) [inline src/librustdoc/json/mod.rs:220]: This can just be removed, there's no point leaving it commented out. If we ever want to change the behaviour back, having this in the git history will be enough.

File: src/librustdoc/formats/mod.rs (hunk 4 above)
Comment (its-the-shrimp) [reply src/librustdoc/formats/mod.rs]: Would you accept such a change in a separate PR? possibly expanded if I find other cases of output-format-agnostic functionality relying on a specific output format

Comment (aDotInTheVoid) [reply src/librustdoc/formats/mod.rs]: I don't think so. As long as this method's only used in the HTML backend, I (personally) think it's fine to rely on HTML-specific helpers.
