### PR TITLE
Fix documentation not showing on localStorage error

### LINKED ISSUE #81928: rustdoc JS does not handle NO_DEVICE_SPACE error
**Problem**

No documented item appear in documentation pages anywhere after a localStorage error.

image

(the page should render [like that](https://docs.rs/serde/1.0.123/serde/ser/trait.Serializer.html) instead)

After localStorage raises a `NS_ERROR_FILE_NO_DEVICE_SPACE` error, all documentation page appear entirely blank. Freeing up space doesn't solve the isssue.

The following appears in the browser console : 

```
Uncaught 
Exception
​
columnNumber: 0
​
data: null
​
filename: "https://docs.rs/storage-20210124-1.51.0-nightly-1d0d76f8d.js"
​
lineNumber: 1
​
message: ""
​
name: "NS_ERROR_FILE_NO_DEVICE_SPACE"
​
result: 2152857616
​
stack: "getCurrentValue@https://docs.rs/storage-20210124-1.51.0-nightly-1d0d76f8d.js:1:1802\ngetSettingValue@https://docs.rs/storage-20210124-1.51.0-nightly-1d0d76f8d.js:1:490\n@https://docs.rs/storage-20210124-1.51.0-nightly-1d0d76f8d.js:1:711\n"
​
<prototype>: ExceptionPrototype { toString: toString(), name: Getter, message: Getter, … }
storage-20210124-1.51.0-nightly-1d0d76f8d.js:1
    getCurrentValue https://docs.rs/storage-20210124-1.51.0-nightly-1d0d76f8d.js:1
    getSettingValue https://docs.rs/storage-20210124-1.51.0-nightly-1d0d76f8d.js:1
    <anonymous> https://docs.rs/storage-20210124-1.51.0-nightly-1d0d76f8d.js:1
```

**Steps**

1. Fill the disk firefox uses for localStorage
2. open any documentation page on docs.rs : the documentation doesn't appear
3. Free up space
4. open any documentation page on docs.rs : the documentation still doesn't appear

**Possible Solution(s)**

Opening the docs in a private browsing window works.

### PR DESCRIPTION
**Pull request by lovasoa**
Fixes https://github.com/rust-lang/rust/issues/81928

The [documentation for setItem](https://developer.mozilla.org/en-US/docs/Web/API/Storage/setItem) specifies:

> developers should make sure to always catch possible exceptions from setItem()

### CODE REVIEW

**Review by GuillaumeGomez — APPROVED** [review]

**Comment by GuillaumeGomez** [comment]
I really like this simplification which allows us to handle all cases. Thanks!

@bors: r+ rollup

File: src/librustdoc/html/static/storage.js [hunk 1]
```diff
@@ -89,35 +89,20 @@ function hasOwnProperty(obj, property) {
...
-
 function updateLocalStorage(name, value) {
-    if (usableLocalStorage()) {
-        localStorage[name] = value;
-    } else {
-        // No Web Storage support so we do nothing
+    try {
+        window.localStorage.setItem(name, value);
+    } catch(e) {
+        // localStorage is not accessible, do nothing
```
Comment (the8472) [inline src/librustdoc/html/static/storage.js:96]: Wouldn't it make sense to attempt to call `localStorage.clear()` here in case enough data accumulated to reach the per-site limit?

Comment (GuillaumeGomez) [reply src/librustdoc/html/static/storage.js:96]: Why would you want to remove all your data if you can't add more?

Comment (the8472) [reply src/librustdoc/html/static/storage.js:96]: That's assuming something filled up the storage to its limit which prevents storing new data, e.g. due to previous iterations of the site.

Comment (GuillaumeGomez) [reply src/librustdoc/html/static/storage.js:96]: We store very little amount of information in the local storage (less than 40 bytes iirc), so we should be fine. ;)

Comment (lovasoa) [reply src/librustdoc/html/static/storage.js:96]: Maybe this can be discussed outside of the context of this pull request ?
If new behavior needs to be introduced, it can be independently of this bug fix.

Comment (the8472) [reply src/librustdoc/html/static/storage.js:96]: No need, if there's nothing that could cause unbounded growth then the limitation is probably due to something else, e.g. a browser simply having localstorage disabled, `clear()` wouldn't help with that.

Comment (lovasoa) [reply src/librustdoc/html/static/storage.js:96]: Are we good to merge, then ?

Comment (GuillaumeGomez) [reply src/librustdoc/html/static/storage.js:96]: I already approved it so it should be merged in the next days.
