### PR TITLE
NLL: bad error message when converting anonymous lifetime to `'static`

### LINKED ISSUE #46983: NLL: bad error message when converting anonymous lifetime to `'static`
UPDATE: [Mentoring instructions here.](https://github.com/rust-lang/rust/issues/46983#issuecomment-356626994)

----

Tested at 5165ee9e209e0e70d89946ccbb7e90b9c0c3a7ac and current playpen

```Rust
#![feature(nll)]

fn foo(x: &u32) -> &'static u32 {
    &*x
}

fn main() {}
```

Error message:

```
error: free region `` does not outlive free region `'static`
 --> src/main.rs:4:5
  |
4 |     &*x
  |     ^^^

error: aborting due to previous error
```

### PR DESCRIPTION
**Pull request by davidtwco**
Contributes to #46983. This PR doesn't introduce fantastic errors, but it should hopefully lay some groundwork for diagnostic improvements.
r? @nikomatsakis

### CODE REVIEW

**Comment by davidtwco** [comment]
This PR isn't ready yet (at time of writing and creating the WIP PR), but it completes the majority of the initial steps for this. A function has been added that computes all the constraint paths from a region - the shortest of these paths is then categorized, sorted and labelled onto an error.

Improvements are required with the categorization, I was unsure what categories were required and how best to work them out. 

Discussion related to this PR can be found [on Zulip](https://rust-lang.zulipchat.com/#narrow/stream/122657-wg-nll/topic/ui.2Funderscore-lifetime.2Fdyn-trait-underscore.2Ers), in `#wg-nll` on topic `ui/underscore-lifetime/dyn-trait-underscore.rs `

**Comment by pietroalbini** [comment]
Ping from triage @nikomatsakis! This PR needs your review.

File: src/librustc_mir/borrow_check/nll/region_infer/mod.rs [hunk 1]
```diff
@@ -147,6 +148,40 @@ pub struct Constraint {
...
+    Other,
+}
+
+impl Ord for ConstraintCategory {
+    fn cmp(&self, other: &Self) -> Ordering {
+        if self == other {
+            return Ordering::Equal;
+        }
+
+        match (self, other) {
```
Comment (nikomatsakis) [inline src/librustc_mir/borrow_check/nll/region_infer/mod.rs]: Can we not just `#[derive(Ord)]` here? I think that would work fine...?

Comment (nikomatsakis) [reply src/librustc_mir/borrow_check/nll/region_infer/mod.rs]: (We would want to comment that the order is significant)

File: src/librustc_mir/borrow_check/nll/region_infer/mod.rs [hunk 2]
```diff
@@ -1096,6 +1136,32 @@ impl<'tcx> RegionInferenceContext<'tcx> {
         }).is_some()
     }
 
+    /// This function classifies a constraint from a location.
+    fn classify_constraint(&self, location: Location, mir: &Mir<'tcx>) -> ConstraintCategory {
```
Comment (nikomatsakis) [inline src/librustc_mir/borrow_check/nll/region_infer/mod.rs]: as an aside, it feels pretty clear we should think about breaking this logic out into its own module at some point. Doesn't have to be in this PR.

File: src/librustc_mir/borrow_check/nll/region_infer/mod.rs [hunk 3]
```diff
@@ -1128,27 +1195,57 @@ impl<'tcx> RegionInferenceContext<'tcx> {
...
+        }).collect::<Vec<(ConstraintCategory, Span)>>();
+        debug!("report_error: categorized_path={:?}", categorized_path);
+
+        categorized_path.sort_by(|p0, p1| p0.0.cmp(&p1.0));
+        debug!("report_error: sorted_path={:?}", categorized_path);
+
+        if categorized_path.len() > 0 {
+            let blame_constraint = &categorized_path[0];
+
+            let mut diag = infcx.tcx.sess.struct_span_err(
```
Comment (nikomatsakis) [inline src/librustc_mir/borrow_check/nll/region_infer/mod.rs]: can I see the output of this code for any of our tests?

**Review by nikomatsakis — APPROVED** [review]
This is looking great so far! I guess the question we have to answer now is to focus in on some specific tests and try to push the output to something we are happy with.

File: src/librustc_mir/borrow_check/nll/region_infer/mod.rs (hunk 3 above)
Comment (davidtwco) [reply src/librustc_mir/borrow_check/nll/region_infer/mod.rs]: For the test we focused on in the pair programming session, this is the current output:
```
error: Cast
  --> src/test/ui/underscore-lifetime/dyn-trait-underscore.rs:18:5
   |
16 |   fn a<T>(items: &[T]) -> Box<dyn Iterator<Item=&T>> {
   |  ____________________________________________________-
17 | |     //                      ^^^^^^^^^^^^^^^^^^^^^ bound *here* defaults to `'static`
18 | |     Box::new(items.iter()) //~ ERROR cannot infer an appropriate lifetime
   | |     ^^^^^^^^^^^^^^^^^^^^^^
   | |     |
   | |     Cast
   | |     Cast
19 | | }
   | |_- Cast
```
I don't know if it's great, because we end up with a lot of `Cast`.

File: src/librustc_mir/borrow_check/nll/region_infer/mod.rs (hunk 1 above)
Comment (davidtwco) [reply src/librustc_mir/borrow_check/nll/region_infer/mod.rs]: I considered doing that, but it would have meant that variants at the top of the definition were considered most significant - which seemed a little too implicit? - so I went with this instead. I'll change it to `#[derive(Ord)]`.

File: src/librustc_mir/borrow_check/nll/region_infer/mod.rs (hunk 2 above)
Comment (davidtwco) [reply src/librustc_mir/borrow_check/nll/region_infer/mod.rs]: I'll make an `error_reporting` module and move relevant functions into it.

**Comment by davidtwco** [comment]
Rebased and addressed the above comments.

**Comment by pietroalbini** [comment]
Ping from triage @davidtwco! There are test failures you should fix.

**Review by nikomatsakis — CHANGES_REQUESTED** [review]
looks good but for the nit that error messages in compiler should begin with lowercase letter

**Review by nikomatsakis — APPROVED** [review]

**Comment by nikomatsakis** [comment]
@davidtwco needs rebase :(
