### PR TITLE
suggest `|` when `,` founds in invalid match value

### LINKED ISSUE #54807: misleading "try adding parentheses" in match with comma
Consider the following (incorrect) code.

```
enum E { A,B,C }

fn x(e:E) -> i32 {
    match e {
        A,B => 1,
        C => 2
    }
}
```

The comma in the match is obviously supposed to be a `|`. However, rustc recommends I rewrite to `(A,B)`, which makes the situation worse, as the compile error becomes `expected enum E, found tuple`.

### PR DESCRIPTION
**Pull request by Krout0n**
Closes #54807 
I get stuck on (what | how) I should implement...

### CODE REVIEW

**Comment by petrochenkov** [comment]
The current behavior is intentional and has reasons, like it was mentioned in https://github.com/rust-lang/rust/issues/54807.
In some very popular languages like Python tuples can be written without parentheses `(A, B)` <=> `A, B`, so it's reasonable to expect that the user actually meant `(A, B)` while writing `A, B`.

**Comment by oli-obk** [comment]
As I mentioned in https://github.com/rust-lang/rust/issues/54807#issuecomment-426960202, I believe it would be cool to suggest *both* `(A, B)` and `A | B`. Do you think doing so will complicate the parser more than it's worth it for such a small suggestion?

**Comment by petrochenkov** [comment]
Suggesting both would be ok, then change will need to be done in `fn parse_top_level_pat` then.
It will give some false positives like recommending `let A | B = expr;`, but that doesn't matter much, it will become legal soon, at least in the parser.

**Comment by Knium** [comment]
Hi, thanks for reviewing! I need solid blocks of time to understand what you mean and implement. So just a moment pls :)

**Comment by Knium** [comment]
@Aaronepower Hi, thank you for reminding! Sorry, I'm busier than I thought... If this issue has hurry deadline or there is anyone who want to solve, I approve that someone takes my place. If no one else, I'm still eager to challenge this.

**Comment by TimNN** [comment]
Ping from triage @Knium:

> Sorry, I'm busier than I thought... If this issue has hurry deadline or there is anyone who want to solve, I approve that someone takes my place.

Don't worry, there is no deadline :). We just like to check in on PRs ~regularly so that we don't have dozens of PRs open that are not being worked on. If you are interested, you can find more information here: https://forge.rust-lang.org/triage-procedure.html

File: src/libsyntax/parse/parser.rs [hunk 1]
```diff
@@ -4381,9 +4381,14 @@ impl<'a> Parser<'a> {
...
                 err.span_suggestion(
                     seq_span,
-                    "try adding parentheses",
+                    "try adding parentheses..",
                     format!("({})", seq_snippet),
                     Applicability::MachineApplicable
+                ).span_suggestion(
+                    seq_span,
+                    "..or a vertical bar",
+                    format!("{}", seq_snippet.replace(",", " | ")),
```
Comment (oli-obk) [inline src/libsyntax/parse/parser.rs]:
```suggestion
                    format!("{}", seq_snippet.replace(",", " |")),
```

This adds one additional space that already correctly formatted code would not need

**Review by oli-obk — CHANGES_REQUESTED** [review]
just a nit, then it lgtm

File: src/libsyntax/parse/parser.rs [hunk 2]
```diff
@@ -4381,9 +4381,14 @@ impl<'a> Parser<'a> {
             if let Ok(seq_snippet) = self.sess.source_map().span_to_snippet(seq_span) {
                 err.span_suggestion(
                     seq_span,
-                    "try adding parentheses",
+                    "try adding parentheses..",
```
Comment (petrochenkov) [inline src/libsyntax/parse/parser.rs]:
```suggestion
                    "try adding parentheses to match on a tuple..",
```

File: src/libsyntax/parse/parser.rs [hunk 3]
```diff
@@ -4381,9 +4381,14 @@ impl<'a> Parser<'a> {
...
                     format!("({})", seq_snippet),
                     Applicability::MachineApplicable
+                ).span_suggestion(
+                    seq_span,
+                    "..or a vertical bar",
```
Comment (petrochenkov) [inline src/libsyntax/parse/parser.rs]:
```suggestion
                    "..or a vertical bar to match on multiple alternatives",
```

Comment (petrochenkov) [reply src/libsyntax/parse/parser.rs]: (Or some similar wording.)

**Review by oli-obk — APPROVED** [review]

**Comment by oli-obk** [comment]
@bors r+ rollup

Thanks!
