### PR TITLE
rustdoc: display sugared return types for async functions

### LINKED ISSUE #58027: Rustdoc renders async fn incorrectly
## Summary

While experimenting with `async fn` and `await!()` on nightly Rust, I noticed that `cargo doc` renders them incorrectly. It displays the following:

```rust
pub async fn foo(&self, bar: Bar) -> impl Future<Output = Option<Baz>> + '_
```

I expected the output to be something like this:

```rust
pub async fn foo(&self, bar: Bar) -> Option<Baz>
```

I believe having `async fn` displayed as returning an `impl Future` like that is misleading because the `async` keyword at the beginning makes it seem like the return value is a nested future, when it really isn't. That is, it erroneously suggests that the desugared form of the `async fn` is:

```rust
pub fn foo(&self, bar: Bar) -> impl Future<Output = impl Future<Output = Option<Baz>> + '_> + '_
```

## Toolchain information

* `rustc 1.33.0-nightly (b43986184 2019-01-11)`
* `rustdoc 1.33.0-nightly (b43986184 2019-01-11)`
* macOS Mojave 10.14.2 (`x86_64-apple-darwin`)

## How to reproduce

The minimal verifiable example for this issue is essentially creating a new Cargo project with some trivial `async fn` code in it, and then running `cargo doc --open`.

### PR DESCRIPTION
**Pull request by euclio**
Fixes #58027.

### CODE REVIEW

File: src/test/rustdoc/async-fn.rs [hunk 1]
```diff
@@ -1,12 +1,24 @@
 // edition:2018
-// compile-flags:-Z unstable-options
-
-// FIXME: once `--edition` is stable in rustdoc, remove that `compile-flags` directive
 
 #![feature(async_await, futures_api)]
 
+// @has async_fn/fn.foo.html '//pre[@class="rust fn"]' 'pub async fn foo() -> Option<S>'
+pub async fn foo() -> Option<S> {
```
Comment (GuillaumeGomez) [inline src/test/rustdoc/async-fn.rs]: I thought that `S` was a type parameter because the name was only one letter. Can you make it at least two letters so people won't struggle on it in the future (haha) please?

**Comment by GuillaumeGomez** [comment]
Please fix my comment and then we're good to go!

**Comment by euclio** [comment]
@GuillaumeGomez Fixed, also added a test case that uses `impl Trait`.

**Comment by GuillaumeGomez** [comment]
Thanks!

@bors: r+ rollup
