### PR TITLE
resolve: Fix #23880, a scoping bug

### LINKED ISSUE #23880: Items with 'lexical' scope have poor scoping
E.g., 

```
struct Foo;

impl Foo {
    fn bar(&self) {}

    fn foo(&self) {
        fn bar(x: &Foo) {}
        
        bar(self);
    }
}

fn main() {}
```

Is an error, but shouldn't be, because the `bar` method hides the locally declared `bar` function inside `foo`.

I think this is a bug, so it shouldn't be on any milestone, but nominating just in case.

### PR DESCRIPTION
**Pull request by jseyfried**
This fixes #23880, a scoping bug in which items in a block are shadowed by local variables and type parameters that are in scope.

After this PR, an item in a block will shadow any local variables or type parameters above the item in the scope hierarchy. Items in a block will continue to be shadowed by local variables in the same block (even if the item is defined after the local variable).

This is a [breaking-change]. For example, the following code breaks:

``` rust
fn foo() {
    let mut f = 1;
    {
        fn f() {}
        f += 1; // This will resolve to the function instead of the local variable
    }
}
```

### CODE REVIEW

**Comment by oli-obk** [comment]
your example code that's broken by your changes could be a compile-fail test

File: src/test/run-pass/lexical-scoping.rs [hunk 1]
```diff
@@ -0,0 +1,27 @@
...
+// file at the top-level directory of this distribution and at
+// http://rust-lang.org/COPYRIGHT.
+//
+// Licensed under the Apache License, Version 2.0 <LICENSE-APACHE or
+// http://www.apache.org/licenses/LICENSE-2.0> or the MIT license
+// <LICENSE-MIT or http://opensource.org/licenses/MIT>, at your
+// option. This file may not be copied, modified, or distributed
+// except according to those terms.
+
+#![allow(unused)]
```
Comment (nrc) [inline src/test/run-pass/lexical-scoping.rs]: Could you add a comment describing what is being tested please?

Comment (jseyfried) [inline src/test/run-pass/lexical-scoping.rs]: Sure

**Comment by jseyfried** [comment]
@oli-obk true, but the run-pass test is testing the same thing

**Comment by jseyfried** [comment]
@nrc I added a comment describing the test and improved the commit message.

**Comment by nrc** [comment]
Could you add [breaking-change] to the commit message please?

**Comment by nrc** [comment]
r+ with the change to the commit message

**Comment by jseyfried** [comment]
I updated the commit message.

**Comment by nrc** [comment]
@jseyfried sorry, I should have been clearer. The subject line can stay the same, but you should add `[breaking-change]` to the body of the commit message. You should add an explanation of the breaking change, perhaps including the example, and any advice for how to fix any bustage.

**Comment by jseyfried** [comment]
@nrc Ok.

I'm a little unclear on what should go in the merge commit message for the PR and what should go in the individual commit message(s).

Sampling past PRs, including ones with breaking changes, it looks pretty common to have a detailed merge commit message and a simple one-liner for the individual commit(s). Is this bad practice?

**Comment by nrc** [comment]
@jseyfried thanks, I am a little confused too - I didn't know bors uses the PR message as the merge commit message, so it would have been fine, I guess. I personally prefer having the breaking-change message in the commit which makes the change so that it is easy to find the relevant code, but I think official policy is just that breaking-change has to be in *a* commit message.
