### PR TITLE
Don't fire `CONST_ITEM_MUTATION` lint when borrowing a deref

### LINKED ISSUE #78819: `const_item_mutation` incorrectly fires when using raw pointers
I tried this code:

```rust
fn main() {
    const PTR: *mut () = 0x8000_0000 as *mut _;
    
    unsafe { &mut *PTR };
}
```

I expected to see this happen: This should compile without warnings, as I am just turning the `0x8000_0000` raw pointer into a mutable reference.

Instead, this happened:

```
warning: taking a mutable reference to a `const` item
 --> src/main.rs:4:14
  |
4 |     unsafe { &mut *PTR };
  |              ^^^^^^^^^
  |
  = note: `#[warn(const_item_mutation)]` on by default
  = note: each usage of a `const` item creates a new temporary
  = note: the mutable reference will refer to this temporary, not the original `const` item
note: `const` item defined here
 --> src/main.rs:2:5
  |
2 |     const PTR: *mut () = 0x8000_0000 as *mut _;
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

The lint claims that I'm "taking a mutable reference to a `const` item", but I'm not – the const item *is* the reference.

This warning started popping up a lot for the [cortex-m](https://github.com/rust-embedded/cortex-m) crate, which uses this pattern heavily.

### Meta

This is on current nightly (2020-11-05).

### PR DESCRIPTION
**Pull request by Aaron1011**
Fixes #78819

This extends the check for dereferences added in PR #77324
to cover mutable borrows, as well as direct writes. If we're operating
on a dereference of a `const` item, we shouldn't be firing the lint.

### CODE REVIEW

File: compiler/rustc_mir/src/transform/check_const_item_mutation.rs [hunk 1]
```diff
@@ -88,15 +101,11 @@ impl<'a, 'tcx> Visitor<'tcx> for ConstMutationChecker<'a, 'tcx> {
...
-                    if !matches!(lhs.projection.last(), Some(PlaceElem::Deref)) {
-                        self.lint_const_item_usage(def_id, loc, |lint| {
-                            let mut lint = lint.build("attempting to modify a `const` item");
-                            lint.note("each usage of a `const` item creates a new temporary - the original `const` item will not be modified");
-                            lint
-                        })
-                    }
+                    self.lint_const_item_usage(&lhs, def_id, loc, |lint| {
+                        let mut lint = lint.build("attempting to modify a `const` item");
+                        lint.note("each usage of a `const` item creates a new temporary - the original `const` item will not be modified");
```
Comment (varkor) [inline compiler/rustc_mir/src/transform/check_const_item_mutation.rs:106]:
```suggestion
                        lint.note("each usage of a `const` item creates a new temporary; the original `const` item will not be modified");
```

**Review by varkor — COMMENTED** [review]
The PR itself looks good. Could you make a quick drive-by fix? The hyphen is incorrect here; a semicolon would be more appropriate.

File: compiler/rustc_mir/src/transform/check_const_item_mutation.rs (hunk 1 above)
Comment (Aaron1011) [reply compiler/rustc_mir/src/transform/check_const_item_mutation.rs]: Fixed

**Comment by Aaron1011** [comment]
@varkor: I've addressed your comment in a separate commit.
