### PR TITLE
Copy stage0 binaries into stage0-sysroot

### LINKED ISSUE #101691: Copy stage0 binaries into stage0-sysroot
Currently, the beta binaries are only present in `build/stage0/bin`; `build/stage0-sysroot` has *only* the standard library, not any binaries. That causes two issues:
1. `rustup toolchain link` doesn't work with stage0-sysroot, meaning there's no way to change the standard library and use those changes at runtime without doing a full stage 1 build
2. `x dist --stage 0` doesn't work. This is very rare to want to do, but can be useful when modifying the `dist` process itself, to avoid long compile times.
 ```
thread 'main' panicked at 'could not read dir "/home/dawn/projects/rust/build/x86_64-unknown-linux-gnu/stage0-sysroot/bin": Os { code: 2, kind: NotFound, message: "No such file or directory" }', lib.rs:1573:25
```
 
Copying the binaries into stage0-sysroot is an easy way to fix both problems at once.

Mentoring instructions: Add a `builder.copy` call in `impl Step for Sysroot` https://github.com/rust-lang/rust/blob/6f0c4a6c5c36f1f8f433a12e10a29918f3d40a31/src/bootstrap/compile.rs#L1146 which copies the whole `bin` directory from `build/stage0`.

### PR DESCRIPTION
**Pull request by chenyukang**
Fixes #101691

### CODE REVIEW

**Review by jyn514 — COMMENTED** [review]
This looks good :) have you tested locally that it fixes the two problems I mentioned in the issue? The rustup one should be easy to test (same way as for the stage 1 sysroot).

File: src/bootstrap/compile.rs [hunk 1]
```diff
@@ -1143,6 +1143,12 @@ impl Step for Sysroot {
             }
         }
 
+        if compiler.stage == 0 {
```
Comment (jyn514) [inline src/bootstrap/compile.rs:1146]: Oh, please also leave a comment explaining why we're special casing stage 0.

File: src/bootstrap/compile.rs [hunk 2]
```diff
@@ -436,6 +436,43 @@ impl Step for StdLink {
...
+            // copy bin files from stage0/bin to stage0-sysroot/bin
+            let sysroot = builder.out.join(&compiler.host.triple).join("stage0-sysroot");
+
+            let host = compiler.host.triple;
+            let stage0_bin_dir = builder.out.join(&host).join("stage0/bin");
+            let sysroot_bin_dir = sysroot.join("bin");
+            t!(fs::create_dir_all(&sysroot_bin_dir));
+            builder.cp_r(&stage0_bin_dir, &sysroot_bin_dir);
+
+            // copy all *.so files from stage0/lib to stage0-sysroot/lib
```
Comment (jyn514) [inline src/bootstrap/compile.rs:453]: Are you sure this is correct? We shouldn't be copying any artifacts at all for libstd, I don't remember whether we distribute it as an .so or not.

**Comment by jyn514** [comment]
@bors r+

Thanks! Can you also make a PR to rustc-dev-guide mentioning you can use this for a rustup toolchain, under "suggested workflows"?
