### PR TITLE
Fix ICE when misplaced visibility cannot be properly parsed

### LINKED ISSUE #86895: internal compiler error: the following error was constructed but not emitted
I'm seeing an internal compiler error on the following input (found by [fuzz-rustc](https://github.com/dwrensha/fuzz-rustc)):

```rust
const pub () {}
pub fn main() {}
```

```
$ rustc bug.rs
error: internal compiler error: the following error was constructed but not emitted

error: expected one of `async`, `extern`, `fn`, or `unsafe`, found keyword `pub`
 --> bug.rs:1:7
  |
1 | const pub () {}
  |       ^^^ expected one of `async`, `extern`, `fn`, or `unsafe`

thread 'rustc' panicked at 'explicit panic', compiler/rustc_errors/src/diagnostic_builder.rs:424:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.55.0-nightly (b3d11f95c 2021-07-04) running on x86_64-unknown-linux-gnu

query stack during panic:
end of query stack
error: aborting due to 2 previous errors
```

### PR DESCRIPTION
**Pull request by rylev**
Fixes #86895 

The issue was that a failure to parse the visibility was causing the original error to be dropped before being emitted. 

The resulting error isn't quite as nice as when the visibility is parsed properly, but I'm not sure which error to prioritize here. Displaying both errors might be too confusing. 

r? @estebank

### CODE REVIEW

**Comment by estebank** [comment]
@bors r+

I want to rework this part of the parser to handle incorrect code more gracefully, but for now this is fine.

File: compiler/rustc_parse/src/parser/item.rs [hunk 1]
```diff
@@ -1791,7 +1791,13 @@ impl<'a> Parser<'a> {
...
                         let sp = sp_start.to(self.prev_token.span);
                         if let Ok(snippet) = self.span_to_snippet(sp) {
-                            let vis = self.parse_visibility(FollowedByType::No)?;
+                            let vis = match self.parse_visibility(FollowedByType::No) {
+                                Ok(v) => v,
+                                Err(mut d) => {
+                                    d.cancel();
+                                    return Err(err);
+                                }
+                            };
```
Comment (estebank) [inline compiler/rustc_parse/src/parser/item.rs:1800]: This kind of code is quite common, it'd be nice if we had some helper for it 🤔
