### PR TITLE
Fix deref impl typedef

### LINKED ISSUE #35295: Rustdoc doesn't follow type aliases in Deref's Target
The `Methods from Deref<Target=...>` will not appear in the documentation if `Deref`'s `Target` is a `type` alias.
This works:

``` rust
pub struct MyVeryLong<AndComplicated<Type>>;
pub type Foo = MyVeryLong<AndComplicated<Type>>;

pub struct Bar;
impl Deref for Bar {
    type Target = MyVeryLong<AndComplicated<Type>>;
    fn deref(&self) -> &Foo { ... }
}
```

This doesn't:

``` rust
pub struct MyVeryLong<AndComplicated<Type>>;
pub type Foo = MyVeryLong<AndComplicated<Type>>;

pub struct Bar;
impl Deref for Bar {
    type Target = Foo;
    fn deref(&self) -> &Foo { ... }
}
```

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Fixes #35295.

r? @kinnison

### CODE REVIEW

**Comment by dns2utf8** [comment]
I like that the unwraps have transitioned to expects.

**Comment by GuillaumeGomez** [comment]
@dns2utf8 This is a side-effect of my debugging (and I hate `unwrap`).

File: src/librustdoc/html/render/cache.rs [hunk 1]
```diff
@@ -574,6 +574,10 @@ fn build_index(krate: &clean::Crate, cache: &mut Cache) -> String {
     // has since been learned.
     for &(did, ref item) in orphan_impl_items {
         if let Some(&(ref fqp, _)) = paths.get(&did) {
+            if item.name.is_none() {
+                // this is most likely from a typedef
+                continue;
+            }
```
Comment (ollie27) [inline src/librustdoc/html/render/cache.rs]: What is this change for? I can't see anything in this PR that would require this.

File: src/librustdoc/html/render/cache.rs [hunk 2]
```diff
@@ -592,19 +596,23 @@ fn build_index(krate: &clean::Crate, cache: &mut Cache) -> String {
...
                 nodeid_to_pathid.insert(nodeid, pathid);
                 lastpathid += 1;
 
-                let &(ref fqp, short) = paths.get(&nodeid).unwrap();
-                crate_paths.push((short, fqp.last().unwrap().clone()));
+                if let Some(&(ref fqp, short)) = paths.get(&nodeid) {
+                    crate_paths.push((short, fqp.last().expect("no fqp").clone()));
+                } else {
+                    continue;
+                }
```
Comment (ollie27) [inline src/librustdoc/html/render/cache.rs]: Again, what is this change for?

**Review by ollie27 — COMMENTED** [review]
This is now only including impls for the inner `item_type` but we actually need the impls for the typedef itself as well. Take for example:

```rust
pub struct FooA;
pub type FooB = FooA;
pub type FooC = FooB;

impl FooA {
    pub fn foo_a(&self) {}
}

impl FooB {
    pub fn foo_b(&self) {}
}

impl FooC {
    pub fn foo_c(&self) {}
}

pub struct Bar;
impl std::ops::Deref for Bar {
    type Target = FooC;
    fn deref(&self) -> &Self::Target { unimplemented!() }
}
```

Currently the docs for `Bar` show only method `foo_c` but with this PR it shows only `foo_a` but what we really need is all of `foo_a`, `foo_b` and `foo_c` to be included.

I'm not sure of the best way to do that but maybe `Typedef` could contain a `Vec<Type>` or `Vec<DefId>` containing each inner type rather than just a single `Option<Type>`.

File: src/librustdoc/html/render/cache.rs (hunk 1 above)
Comment (GuillaumeGomez) [reply src/librustdoc/html/render/cache.rs]: It's not needed anymore, indeed! It was part of my debugging.

File: src/librustdoc/html/render/cache.rs (hunk 2 above)
Comment (GuillaumeGomez) [reply src/librustdoc/html/render/cache.rs]: Same.

**Comment by GuillaumeGomez** [comment]
@ollie27 This is a great point: I didn't think about checking the type alias itself for implementations. I'll need to update the PR to extend it a bit.

**Review by kinnison — COMMENTED** [review]
I also appreciate the `.unwrap()` -> `.expect("...")` changes, and other than wondering about the same points as Ollie did in `cache.rs` I think this is looking quite OK.

I wonder if, in the process of removing that additional debugging code you might fold the formatting fixes into the requisite commits though, to keep the history a bit cleaner?

**Comment by GuillaumeGomez** [comment]
With the last changes:

Screenshot from 2020-01-15 18-14-32

So we currently have `foo_a` and `foo_c` but `foo_b` is missing. More to come soon I guess. :)

**Comment by GuillaumeGomez** [comment]
Ok, fixed all the issues encountered. It now returns all implementations made on the type aliases.

File: src/librustdoc/clean/mod.rs [hunk 3]
```diff
@@ -2112,6 +2116,33 @@ impl Clean<Vec<Item>> for doctree::Impl<'_> {
             })
             .unwrap_or_default();
 
+        let for_ = self.for_.clean(cx);
+        let type_alias = for_.def_id().and_then(|did| match cx.tcx.def_kind(did) {
+            Some(DefKind::TyAlias) => Some(cx.tcx.type_of(did).clean(cx)),
+            _ => None,
+        });
+        if let Some(type_alias) = type_alias {
```
Comment (oli-obk) [inline src/librustdoc/clean/mod.rs]: The above match seems redundant. 

```suggestion
        if let Some(DefKind::TyAlias) = for_.def_id().and_then(|did| match cx.tcx.def_kind(did) {
        let type_alias = cx.tcx.type_of(did).clean(cx);
```

Comment (GuillaumeGomez) [reply src/librustdoc/clean/mod.rs]: If we do it this way, we'll have to clone `trait_`  and `items` one extra time. I'll write something else instead to avoid the duplication of code.

**Comment by GuillaumeGomez** [comment]
Updated!

**Comment by GuillaumeGomez** [comment]
Fixed formatting.
