### PR TITLE
[NLL] Improve "borrow later used here" messages

### LINKED ISSUE #48643: [NLL] Tidy up error messages when borrowing locals
Given this test which is included in https://github.com/rust-lang/rust/pull/48592 and when merged will be located here https://github.com/rust-lang/rust/tree/master/src/test/ui/nll/borrowed-local-error.rs

```
// compile-flags: -Znll-dump-cause

#![feature(nll)]

fn gimme(x: &(u32,)) -> &u32 {
    &x.0
}

fn main() {
    let x = gimme({
        let v = (22,);
        &v
        //~^ ERROR `v` does not live long enough [E0597]
    });
    println!("{:?}", x);
}
```
With https://github.com/rust-lang/rust/pull/48592 merged, the output looks like ...

```
[santiago@archlinux rust1 (borrowed_value_error)]$ RUST_BACKTRACE=1 rustc +stage1 src/test/ui/nll/borrowed-local-error.rs -Znll-dump-cause
error[E0597]: `v` does not live long enough
  --> src/test/ui/nll/borrowed-local-error.rs:22:9
   |
20 |       let x = gimme({
   |  _____________-
21 | |         let v = (22,);
22 | |         &v
   | |         ^^ borrowed value does not live long enough
23 | |         //~^ ERROR `v` does not live long enough [E0597]
24 | |     });
   | |_____-- borrow later used here
   |       |
   |       borrowed value only lives until here

error: aborting due to previous error

If you want more information on this error, try using "rustc --explain E0597"
```

@nikomatsakis said that the output should look like ...

This is what I think it *should* look like:

```
error[E0597]: `v` does not live long enough
  --> borrowed-local-error.rs:20:9
     |
  18 |       let x = gimme({
     |               ----- borrow later used here, during the call
  19 |           let v = (22,);
  20 |           &v
     |           ^^ borrowed value does not live long enough
  21 |       });
     |       - borrowed value only lives until here
```

Previous discussion https://github.com/rust-lang/rust/pull/48592#discussion_r171259913

### PR DESCRIPTION
**Pull request by matthewjasper**
* In the case of two conflicting borrows, the later used message says which borrow it's referring to
* If the later use is a function call (from the users point of view) say that the later use is for the call. Point just to the function.

r? @pnkfelix 
Closes #48643

### CODE REVIEW

**Comment by estebank** [comment]
The "borrow later used by call" messages look much better now!

File: src/librustc_mir/borrow_check/error_reporting.rs [hunk 1]
```diff
@@ -298,9 +300,9 @@ impl<'cx, 'gcx, 'tcx> MirBorrowckCtxt<'cx, 'gcx, 'tcx> {
             "immutable",
             "mutable",
         ) {
-            (BorrowKind::Shared, lft, _, BorrowKind::Mut { .. }, _, rgt)
-            | (BorrowKind::Mut { .. }, _, lft, BorrowKind::Shared, rgt, _) => tcx
```
Comment (pnkfelix) [inline src/librustc_mir/borrow_check/error_reporting.rs]: hmm. If my memory is right, the reason this was structured as a match on a tuple was to allow collapsing multiple cases like these and selecting the right string to use by setting `lft` and `rgt` to the appropriate string literal from the match input.

Reading over the code now, I am thinking that there is potentially no longer *any* instance of two arms being collapsed, which means we really should consider cleaning up the code by getting rid of those string literals in the tuple (and instead just pass the appropriate strings below), I think...

That cleanup doesn't have to be part of this PR, though.

File: src/librustc_mir/borrow_check/nll/explain_borrow/mod.rs [hunk 2]
```diff
@@ -68,7 +84,7 @@ impl<'tcx> BorrowExplanation<'tcx> {
             BorrowExplanation::MustBeValidFor(region) => {
                 tcx.note_and_explain_free_region(
                     err,
-                    "borrowed value must be valid for ",
+                    &(borrow_desc + "borrowed value must be valid for "),
```
Comment (pnkfelix) [inline src/librustc_mir/borrow_check/nll/explain_borrow/mod.rs]: whoa, I barely ever see string concatenation via `+` in Rust code I read...

**Comment by estebank** [comment]
Once this gets rebased it should be given a high priority to avoid more merge conflicts.
