### PR TITLE
Fix an ICE on an invalid `binding @ ...` in a tuple struct pattern

### LINKED ISSUE #74539: ICE with the `@ ..` binding pattern
### Code

```Rust
pub enum Operands {
	Zero,
	One(u8),
	Two(u8, u8),
}

pub fn main() {
	use Operands::*;

	let operands = Zero;

	match operands {
		Zero => println!("Nothing"),
		One(operand) => println!("{:x}", operand),
		Two(operands @ ..) => println!("({:x}, {:x})", operands.0, operands.1),
	};
}
```

### Meta

The bug exists in the beta,

`rustup run beta rustc --version --verbose`
```
rustc 1.46.0-beta.1 (e51b714db 2020-07-15)
binary: rustc
commit-hash: e51b714db8ff82ac38ea7c6742d6f5480e2e77bd
commit-date: 2020-07-15
host: x86_64-unknown-linux-gnu
release: 1.46.0-beta.1
LLVM version: 10.0
```

nightly,

`rustup run nightly rustc --version --verbose`
```
rustc 1.46.0-nightly (346aec9b0 2020-07-11)
binary: rustc
commit-hash: 346aec9b02f3c74f3fce97fd6bda24709d220e49
commit-date: 2020-07-11
host: x86_64-unknown-linux-gnu
release: 1.46.0-nightly
LLVM version: 10.0
```

and stable build channels.

`rustc --version --verbose`:
```
rustc 1.45.0 (5c1f21c3b 2020-07-13)
binary: rustc
commit-hash: 5c1f21c3b82297671ad3ae1e8c942d2ca92e84f2
commit-date: 2020-07-13
host: x86_64-unknown-linux-gnu
release: 1.45.0
LLVM version: 10.0
```

The error and the backtrace provided are produced by the stable build.

### Error output

```
error: `operands @` is not allowed in a tuple struct
  --> ./a.rs:15:7
   |
15 |         Two(operands @ ..) => println!("({:x}, {:x})", operands.0, operands.1),
   |             ^^^^^^^^^^^^^ this is only allowed in slice patterns
   |
   = help: remove this and bind each tuple field independently
help: if you don't need to use the contents of operands, discard the tuple's remaining fields
   |
15 |         Two(..) => println!("({:x}, {:x})", operands.0, operands.1),
   |             ^^

error: internal compiler error: src/librustc_typeck/check/mod.rs:3023: no type for local variable unknown node (hir_id=HirId { owner: DefId(0:13 ~ a[317d]::main[0]), local_id: 9 })
  --> ./a.rs:15:50
   |
15 |         Two(operands @ ..) => println!("({:x}, {:x})", operands.0, operands.1),
   |                                                        ^^^^^^^^

thread 'rustc' panicked at 'Box<Any>', /rustc/5c1f21c3b82297671ad3ae1e8c942d2ca92e84f2/src/libstd/macros.rs:13:23
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
thread 'rustc' panicked at 'Box<Any>', /rustc/5c1f21c3b82297671ad3ae1e8c942d2ca92e84f2/src/libstd/macros.rs:13:23
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:78
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1076
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1537
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:198
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:218
  10: rustc_driver::report_ice
  11: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:490
  12: std::panicking::begin_panic
  13: rustc_errors::HandlerInner::span_bug
  14: rustc_errors::Handler::span_bug
  15: rustc_middle::util::bug::opt_span_bug_fmt::{{closure}}
  16: rustc_middle::ty::context::tls::with_opt::{{closure}}
  17: rustc_middle::ty::context::tls::with_opt
  18: rustc_middle::util::bug::opt_span_bug_fmt
  19: rustc_middle::util::bug::span_bug_fmt
  20: rustc_typeck::check::FnCtxt::local_ty::{{closure}}
  21: rustc_typeck::check::FnCtxt::local_ty
  22: rustc_typeck::check::FnCtxt::instantiate_value_path
  23: rustc_typeck::check::expr::<impl rustc_typeck::check::FnCtxt>::check_expr_kind
  24: rustc_typeck::check::expr::<impl rustc_typeck::check::FnCtxt>::check_expr_with_expectation_and_needs
  25: rustc_typeck::check::expr::<impl rustc_typeck::check::FnCtxt>::check_expr_kind
  26: rustc_typeck::check::expr::<impl rustc_typeck::check::FnCtxt>::check_expr_with_expectation_and_needs
  27: rustc_typeck::check::expr::<impl rustc_typeck::check::FnCtxt>::check_expr_kind
  28: rustc_typeck::check::expr::<impl rustc_typeck::check::FnCtxt>::check_expr_with_expectation_and_needs
  29: <smallvec::SmallVec<A> as core::iter::traits::collect::Extend<<A as smallvec::Array>::Item>>::extend
  30: <T as rustc_middle::ty::context::InternIteratorElement<T,R>>::intern_with
  31: rustc_typeck::check::expr::<impl rustc_typeck::check::FnCtxt>::check_expr_kind
  32: rustc_typeck::check::expr::<impl rustc_typeck::check::FnCtxt>::check_expr_with_expectation_and_needs
  33: rustc_typeck::check::_match::<impl rustc_typeck::check::FnCtxt>::check_match
  34: rustc_typeck::check::expr::<impl rustc_typeck::check::FnCtxt>::check_expr_kind
  35: rustc_typeck::check::expr::<impl rustc_typeck::check::FnCtxt>::check_expr_with_expectation_and_needs
  36: rustc_typeck::check::expr::<impl rustc_typeck::check::FnCtxt>::check_expr_kind
  37: rustc_typeck::check::expr::<impl rustc_typeck::check::FnCtxt>::check_expr_with_expectation_and_needs
  38: rustc_typeck::check::FnCtxt::check_argument_types
  39: rustc_typeck::check::callee::<impl rustc_typeck::check::FnCtxt>::confirm_builtin_call
  40: rustc_typeck::check::callee::<impl rustc_typeck::check::FnCtxt>::check_call
  41: rustc_typeck::check::expr::<impl rustc_typeck::check::FnCtxt>::check_expr_kind
  42: rustc_typeck::check::expr::<impl rustc_typeck::check::FnCtxt>::check_expr_with_expectation_and_needs
  43: rustc_typeck::check::FnCtxt::check_argument_types
  44: rustc_typeck::check::callee::<impl rustc_typeck::check::FnCtxt>::confirm_builtin_call
  45: rustc_typeck::check::callee::<impl rustc_typeck::check::FnCtxt>::check_call
  46: rustc_typeck::check::expr::<impl rustc_typeck::check::FnCtxt>::check_expr_kind
  47: rustc_typeck::check::expr::<impl rustc_typeck::check::FnCtxt>::check_expr_with_expectation_and_needs
  48: rustc_typeck::check::FnCtxt::check_stmt
  49: rustc_typeck::check::FnCtxt::check_block_with_expected
  50: rustc_typeck::check::expr::<impl rustc_typeck::check::FnCtxt>::check_expr_kind
  51: rustc_typeck::check::expr::<impl rustc_typeck::check::FnCtxt>::check_expr_with_expectation_and_needs
  52: rustc_typeck::check::_match::<impl rustc_typeck::check::FnCtxt>::check_match
  53: rustc_typeck::check::expr::<impl rustc_typeck::check::FnCtxt>::check_expr_kind
  54: rustc_typeck::check::expr::<impl rustc_typeck::check::FnCtxt>::check_expr_with_expectation_and_needs
  55: rustc_typeck::check::FnCtxt::check_stmt
  56: rustc_typeck::check::FnCtxt::check_block_with_expected
  57: rustc_typeck::check::expr::<impl rustc_typeck::check::FnCtxt>::check_expr_kind
  58: rustc_typeck::check::expr::<impl rustc_typeck::check::FnCtxt>::check_expr_with_expectation_and_needs
  59: rustc_typeck::check::expr::<impl rustc_typeck::check::FnCtxt>::check_return_expr
  60: rustc_typeck::check::check_fn
  61: rustc_middle::ty::context::GlobalCtxt::enter_local
  62: rustc_typeck::check::typeck_tables_of
  63: rustc_middle::ty::query::<impl rustc_query_system::query::config::QueryAccessors<rustc_middle::ty::context::TyCtxt> for rustc_middle::ty::query::queries::typeck_tables_of>::compute
  64: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl
  65: rustc_query_system::query::plumbing::get_query_impl
  66: rustc_query_system::query::plumbing::ensure_query_impl
  67: rustc_typeck::check::typeck_item_bodies
  68: rustc_middle::ty::query::<impl rustc_query_system::query::config::QueryAccessors<rustc_middle::ty::context::TyCtxt> for rustc_middle::ty::query::queries::typeck_item_bodies>::compute
  69: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl
  70: rustc_query_system::query::plumbing::get_query_impl
  71: rustc_typeck::check_crate
  72: rustc_interface::passes::analysis
  73: rustc_middle::ty::query::<impl rustc_query_system::query::config::QueryAccessors<rustc_middle::ty::context::TyCtxt> for rustc_middle::ty::query::queries::analysis>::compute
  74: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl
  75: rustc_query_system::query::plumbing::get_query_impl
  76: rustc_middle::ty::context::tls::enter_global
  77: rustc_interface::interface::run_compiler_in_existing_thread_pool
  78: rustc_ast::attr::with_globals
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

</p>
</details>

This issue has been assigned to @jakubadamw via [this comment](https://github.com/rust-lang/rust/issues/74539#issuecomment-661038646).

### PR DESCRIPTION
**Pull request by jakubadamw**
Fixes #74539.

### CODE REVIEW

**Comment by jakubadamw** [comment]
@JohnTitor, oh, I see in https://github.com/rust-lang/rust/issues/74539#issuecomment-661031765 that you had another solution in mind? :)

> @jakubadamw Great! You should tweak `src/librustc_ast_lowering/pat.rs` not losing diags. For further reference, you could do `@rustbot claim` when you work on an issue to avoid conflicts.

What do you mean by “not losing diags”? The thing is that AST lowering runs _after_ name resolution. How else could it “poison” that particular invalid binding? Sorry, I don't know the compiler very well, it's been years since. 🙂

File: src/librustc_resolve/late.rs [hunk 1]
```diff
@@ -1500,11 +1500,16 @@ impl<'a, 'b, 'ast> LateResolutionVisitor<'a, 'b, 'ast> {
...
+
         // Visit all direct subpatterns of this pattern.
         pat.walk(&mut |pat| {
             debug!("resolve_pattern pat={:?} node={:?}", pat, pat.kind);
             match pat.kind {
-                PatKind::Ident(bmode, ident, ref sub) => {
+                PatKind::Ident(bmode, ident, ref sub)
+                    // In tuple struct patterns ignore the invalid `ident @ ...`.
+                    // It will be handled as an error by the AST lowering.
+                    if !(is_tuple_struct_pat && sub.as_ref().filter(|p| p.is_rest()).is_some()) => {
```
Comment (nagisa) [inline src/librustc_resolve/late.rs:1512]: Very minor nit: this is indented weird, it took me a couple reads before I realised this is a pattern guard.

File: src/test/ui/issues/issue-74539.rs [hunk 2]
```diff
@@ -0,0 +1,12 @@
+enum E {
+    A(u8, u8),
+}
+
+fn main() {
+    let e = E::A(2, 3);
+    match e {
+        E::A(x @ ..) => {  //~ ERROR `x @` is not allowed in a tuple
+            x //~ ERROR cannot find value `x` in this scope
```
Comment (JohnTitor) [inline src/test/ui/issues/issue-74539.rs:9]: Hmm, `x` should be found here?

Comment (jakubadamw) [reply src/test/ui/issues/issue-74539.rs:9]: @JohnTitor, this is a consequence of the nature of the fix. But I think you're right, this should be done differently.

**Comment by jakubadamw** [comment]
@JohnTitor, right! So I actually tried an alternate approach that would amount to removing the `break` and the `rest` assignment from that case:

```diff
                 PatKind::Ident(ref _bm, ident, Some(ref sub)) if sub.is_rest() => {
-                    rest = Some((idx, pat.span));
                     let sp = pat.span;
                     self.diagnostic()
                         .struct_span_err(
@@ -128,7 +127,6 @@ impl<'a, 'hir> LoweringContext<'a, 'hir> {
                             Applicability::MaybeIncorrect,
                         )
                         .emit();
-                    break;
                 }
```

But this leads to diagnostics that are, in my opinion, degraded compared to the status quo.

```
error: `x @` is not allowed in a tuple struct
  --> $DIR/issue-74539.rs:9:13
   |
LL |             x @ ..
   |             ^^^^^^ this is only allowed in slice patterns
   |
   = help: remove this and bind each tuple field independently
help: if you don't need to use the contents of x, discard the tuple's remaining fields
   |
LL |             ..
   |             ^^

error: `..` patterns are not allowed here
  --> $DIR/issue-74539.rs:9:17
   |
LL |             x @ ..
   |                 ^^
   |
   = note: only allowed in tuple, tuple struct, and slice patterns

error[E0023]: this pattern has 1 field, but the corresponding tuple variant has 2 fields
  --> $DIR/issue-74539.rs:8:9
   |
LL |       A(u8, u8),
   |       --------- tuple variant defined here
...
LL | /         E::A(
LL | |             x @ ..
LL | |         ) => { x }
   | |_________^ expected 2 fields, found 1

error: aborting due to 3 previous errors

For more information about this error, try `rustc --explain E0023`.
```

We end up with two extra diagnostics which are not very useful.

**Comment by JohnTitor** [comment]
@jakubadamw Thanks for investigating more! I like the later diagnostics but let's hear opinion from @nagisa or someone from T-compiler.

**Comment by nagisa** [comment]
I personally like the former slightly more because its not as redundant (and `x` not being found is _fine_ given that its a variable introduced by an error), but ultimately either error seems fine to me as either approach fixes the significantly more important problem – the ICE.

In the end the decision on diagnostics is something that @rust-lang/wg-diagnostics is responsible for and the diagnostics themselves can be iterated further in a separate PR that does not target a backport to beta or stable. If we want this to be backportable it _needs_ to be as simple and obviously correct as it can possibly get.

**Comment by jakubadamw** [comment]
@nagisa, thank you. Looks like I stepped on your toes by pushing after your r+, sorry! 🙂 Yeah, I agree the first solution gives nicer results (although implementation wise it's not as simple as the second one). Should we await input from @rust-lang/wg-diagnostics or go ahead with the first approach? If the latter, then I can take back the redundant commits.

File: src/librustc_ast_lowering/pat.rs [hunk 3]
```diff
@@ -128,7 +127,6 @@ impl<'a, 'hir> LoweringContext<'a, 'hir> {
                             Applicability::MaybeIncorrect,
                         )
                         .emit();
-                    break;
```
Comment (nagisa) [inline src/librustc_ast_lowering/pat.rs:131]: This specific piece of code was conceptually correct – interpreting this pattern as a simple `PatKind::Rest` makes  the most sense.

In that respect, failing to resolve the variable (i.e. using the first iteration of this PR) seems like a better workaround.

The ideal fix would probably be something that ensures users cannot interpret `ddpos` as anything but `PatKind::Rest`. Achieving this might involve reworking the AST representation or something along those lines. Or perhaps something along the lines of the following hack might work:

```rust
            elems.push(self.lower_pat(Pat {
                kind: PatKind::Rest,
                ..pat
            }));
            break;
```

so that the downstream users _also_ end up seeing `..` rather than `x@..` with a potential to mis-interpret it in some way.

**Review by nagisa — CHANGES_REQUESTED** [review]

File: src/librustc_ast_lowering/pat.rs (hunk 3 above)
Comment (jakubadamw) [reply src/librustc_ast_lowering/pat.rs:131]: @nagisa, thanks! I had the same idea, but in this very case that wouldn't help, because we're already past name resolution.

**Comment by jakubadamw** [comment]
@nagisa, okay, I brought back the initial version. 🙂

**Comment by jakubadamw** [comment]
@nagisa, pardon, this will need one more r+, as I had to tidy up the style per the failed build. 🙂

File: src/librustc_resolve/late.rs [hunk 4]
```diff
@@ -1500,11 +1500,17 @@ impl<'a, 'b, 'ast> LateResolutionVisitor<'a, 'b, 'ast> {
...
         // Visit all direct subpatterns of this pattern.
         pat.walk(&mut |pat| {
             debug!("resolve_pattern pat={:?} node={:?}", pat, pat.kind);
             match pat.kind {
-                PatKind::Ident(bmode, ident, ref sub) => {
+                // In tuple struct patterns ignore the invalid `ident @ ...`.
+                // It will be handled as an error by the AST lowering.
+                PatKind::Ident(bmode, ident, ref sub)
+                    if !(is_tuple_struct_pat && sub.as_ref().filter(|p| p.is_rest()).is_some()) =>
+                {
```
Comment (estebank) [inline src/librustc_resolve/late.rs:1513]: **This PR can be merged as is**, _but_ I _think_ we could also add another branch that detects the case with `PatKind::Ident(..)` where `..` is present and record it with a `PartialRes::new(Res::Err)`, which _should_ eliminate the second unnecessary error that complains about `x` not being defined. (Haven't looked at this deeply enough to be sure.)

**Comment by pnkfelix** [comment]
The beta nomination was [discussed](https://zulip-archive.rust-lang.org/238009tcompilermeetings/31818weeklymeeting2020072354818.html#204803012) at weekly T-compiler meeting.

The stable nomination was [also discussed](https://zulip-archive.rust-lang.org/238009tcompilermeetings/31818weeklymeeting2020072354818.html#204805162) at that same meeting.

At the end of both discussions, I noted (and @Mark-Simulacrum agreed) that we'd be more comfortable backporting this if it guarded against the scenario where this guard fires but the AST-lowering code, for whatever reason, *doesn't* signal an error.

In particular, we think that should be implementable via a `delay_span_bug` invocation.

Having said that, adding a `delay_span_bug` invocation is not a strict *prerequisite* for the backport; it is merely something we see as a "nice to have" since it would give us confidence that this change cannot cause a miscompilation down the road.

Having said that: beta backport approved, and stable backport approved.

**Comment by cuviper** [comment]
I've removed the beta backport labels. This was already backported to stable for 1.45.1, then reverted in 1.45.2 due to #74954. We'll let this release naturally with the follow-up fix in #74963.
