### PR TITLE
When archive format is wrong produce an error instead of ICE

### LINKED ISSUE #145624: Potential index out of bounds in `rustc_codegen_ssa::back::archive`
Hi! I am working on `wasmtime` and I have been using the same build methods to run and test. The newest nightly gives the following output. I also make this report while I am trying to figure it out myself too:

```
~/wasmtime$ cargo +nightly fuzz run table_ops -- =runs=1
   Compiling pulley-interpreter v37.0.0 (/users/khan22/wasmtime/pulley)
   Compiling cranelift-assembler-x64 v0.124.0 (/users/khan22/wasmtime/cranelift/assembler-x64)
   Compiling wast v236.0.0
   Compiling wasmi v0.43.1
   Compiling v8 v137.2.0
   Compiling wat v1.236.0
   Compiling json-from-wast v0.236.0
   Compiling wasm-smith v0.236.0

thread 'rustc' (35669) panicked at compiler/rustc_codegen_ssa/src/back/archive.rs:481:29:
range end index 69270030 out of range for slice of length 69173248
stack backtrace:
   0:     0x7f1353028793 - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::hbdbe8f63c4388170
   1:     0x7f1353801abc - core::fmt::write::h7c9d996133c09c4c
   2:     0x7f13530138c3 - std::io::Write::write_fmt::h8b5d91cb0716ac92
   3:     0x7f1353028c02 - std::sys::backtrace::BacktraceLock::print::h7a1c92e005ea0ae7
   4:     0x7f135300af17 - std::panicking::default_hook::{{closure}}::h45e09df88661c95d
   5:     0x7f135300aa43 - std::panicking::default_hook::h0a541c0c26e412a1
   6:     0x7f1352079455 - std[329196bafda325c0]::panicking::update_hook::<alloc[2a86354f952d53f3]::boxed::Box<rustc_driver_impl[c30650361e8f6db4]::install_ice_hook::{closure#1}>>::{closure#0}
   7:     0x7f135300a5f3 - std::panicking::panic_with_hook::h80e20cfe56475828
   8:     0x7f1353028cba - std::panicking::panic_handler::{{closure}}::hf62ab8c5ae80a164
   9:     0x7f1353028c19 - std::sys::backtrace::__rust_end_short_backtrace::h95407abd26228287
  10:     0x7f135300b5cd - __rustc[c13b085bc3ccd426]::rust_begin_unwind
  11:     0x7f134f6d8be0 - core::panicking::panic_fmt::h9b3c3ebe00732244
  12:     0x7f1351a1d797 - core::slice::index::slice_end_index_len_fail::do_panic::runtime::h83a25ef06dac8793
  13:     0x7f1350f3cbca - core::slice::index::slice_end_index_len_fail::h212b8b4a9f378074
  14:     0x7f135497403f - <rustc_codegen_ssa[7a807fb7ad75c85e]::back::archive::ArArchiveBuilder>::build_inner
  15:     0x7f135497162c - <rustc_codegen_ssa[7a807fb7ad75c85e]::back::archive::ArArchiveBuilder as rustc_codegen_ssa[7a807fb7ad75c85e]::back::archive::ArchiveBuilder>::build
  16:     0x7f1354976bee - rustc_codegen_ssa[7a807fb7ad75c85e]::back::link::link_binary
  17:     0x7f1354a94fe8 - <rustc_interface[6d8968059bc7f4aa]::queries::Linker>::link
  18:     0x7f1354a8e218 - rustc_interface[6d8968059bc7f4aa]::interface::run_compiler::<(), rustc_driver_impl[c30650361e8f6db4]::run_compiler::{closure#0}>::{closure#1}
  19:     0x7f135494c2f8 - std[329196bafda325c0]::sys::backtrace::__rust_begin_short_backtrace::<rustc_interface[6d8968059bc7f4aa]::util::run_in_thread_with_globals<rustc_interface[6d8968059bc7f4aa]::util::run_in_thread_pool_with_globals<rustc_interface[6d8968059bc7f4aa]::interface::run_compiler<(), rustc_driver_impl[c30650361e8f6db4]::run_compiler::{closure#0}>::{closure#1}, ()>::{closure#0}, ()>::{closure#0}::{closure#0}, ()>
  20:     0x7f135494bfdc - <<std[329196bafda325c0]::thread::Builder>::spawn_unchecked_<rustc_interface[6d8968059bc7f4aa]::util::run_in_thread_with_globals<rustc_interface[6d8968059bc7f4aa]::util::run_in_thread_pool_with_globals<rustc_interface[6d8968059bc7f4aa]::interface::run_compiler<(), rustc_driver_impl[c30650361e8f6db4]::run_compiler::{closure#0}>::{closure#1}, ()>::{closure#0}, ()>::{closure#0}::{closure#0}, ()>::{closure#1} as core[d0239552f4cfc2f7]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  21:     0x7f135495194b - std::sys::pal::unix::thread::Thread::new::thread_start::hc1a4fde7edfacb97
  22:     0x7f134e26bac3 - start_thread
                               at ./nptl/pthread_create.c:442:8
  23:     0x7f134e2fd850 - __GI___clone3
                               at ./misc/../sysdeps/unix/sysv/linux/x86_64/clone3.S:81:0
  24:                0x0 - <unknown>

error: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: please make sure that you have updated to the latest nightly

note: please attach the file at `/users/khan22/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/v8-137.2.0/rustc-ice-2025-08-19T20_04_14-35658.txt` to your bug report

note: compiler flags: --crate-type lib -C opt-level=3 -C embed-bitcode=no -C debuginfo=line-tables-only -C passes=sancov-module -C llvm-args=-sanitizer-coverage-level=4 -C llvm-args=-sanitizer-coverage-inline-8bit-counters -C llvm-args=-sanitizer-coverage-pc-table -C llvm-args=-sanitizer-coverage-trace-compares -C llvm-args=-simplifycfg-branch-fold-threshold=0 -Z sanitizer=address -C llvm-args=-sanitizer-coverage-stack-depth -C debug-assertions -C codegen-units=1

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
error: could not compile `v8` (lib)

Caused by:
  process didn't exit successfully: `/users/khan22/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/rustc --crate-name v8 --edition=2024 /users/khan22/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/v8-137.2.0/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --diagnostic-width=260 --crate-type lib --emit=dep-info,metadata,link -C opt-level=3 -C embed-bitcode=no -C debuginfo=line-tables-only --cfg 'feature="default"' --cfg 'feature="use_custom_libcxx"' --check-cfg 'cfg(docsrs,test)' --check-cfg 'cfg(feature, values("default", "use_custom_libcxx", "v8_enable_pointer_compression"))' -C metadata=3eafacdf5c6562c2 -C extra-filename=-1bd660b9da1fce87 --out-dir /users/khan22/wasmtime/target/x86_64-unknown-linux-gnu/release/deps --target x86_64-unknown-linux-gnu -L dependency=/users/khan22/wasmtime/target/x86_64-unknown-linux-gnu/release/deps -L dependency=/users/khan22/wasmtime/target/release/deps --extern bitflags=/users/khan22/wasmtime/target/x86_64-unknown-linux-gnu/release/deps/libbitflags-2385c39d2c31e37c.rmeta --extern paste=/users/khan22/wasmtime/target/release/deps/libpaste-4be1c55b718dfb2c.so --cap-lints allow -Cpasses=sancov-module -Cllvm-args=-sanitizer-coverage-level=4 -Cllvm-args=-sanitizer-coverage-inline-8bit-counters -Cllvm-args=-sanitizer-coverage-pc-table -Cllvm-args=-sanitizer-coverage-trace-compares --cfg fuzzing -Cllvm-args=-simplifycfg-branch-fold-threshold=0 -Zsanitizer=address -Cllvm-args=-sanitizer-coverage-stack-depth -Cdebug-assertions -Ccodegen-units=1 -L /users/khan22/wasmtime/target/x86_64-unknown-linux-gnu/release/gn_out/obj -l static=rusty_v8` (exit status: 101)
warning: build failed, waiting for other jobs to finish...
Error: failed to build fuzz script: ASAN_OPTIONS="detect_odr_violation=0" RUSTFLAGS=" -Cpasses=sancov-module -Cllvm-args=-sanitizer-coverage-level=4 -Cllvm-args=-sanitizer-coverage-inline-8bit-counters -Cllvm-args=-sanitizer-coverage-pc-table -Cllvm-args=-sanitizer-coverage-trace-compares --cfg fuzzing -Cllvm-args=-simplifycfg-branch-fold-threshold=0 -Zsanitizer=address -Cllvm-args=-sanitizer-coverage-stack-depth -Cdebug-assertions -Ccodegen-units=1" "cargo" "build" "--manifest-path" "/users/khan22/wasmtime/fuzz/Cargo.toml" "--target" "x86_64-unknown-linux-gnu" "--release" "--config" "profile.release.debug=\"line-tables-only\"" "--bin" "table_ops"
```

```

~/wasmtime$ cargo +nightly -vV
cargo 1.91.0-nightly (71eb84f21 2025-08-17)
release: 1.91.0-nightly
commit-hash: 71eb84f21aef43c07580c6aed6f806a6299f5042
commit-date: 2025-08-17
host: x86_64-unknown-linux-gnu
libgit2: 1.9.1 (sys:0.20.2 vendored)
libcurl: 8.14.1-DEV (sys:0.4.82+curl-8.14.1 vendored ssl:OpenSSL/3.5.0)
ssl: OpenSSL 3.5.0 8 Apr 2025
os: Ubuntu 22.4.0 (jammy) [64-bit]
```

### PR DESCRIPTION
**Pull request by cezarbbb**
*[View all comments](https://triagebot.infra.rust-lang.org/gh-comments/rust-lang/rust/pull/155721)*

Fix rust-lang/rust#145624. Fix rust-lang/rust#147094. Fix rust-lang/rust#148217.
There are now two-step solutions to replace the original ICE：
Step 1: BSD format archive on a GNU/Linux target should emit a format mismatch warning.
Step 2: Corrupt archive with member offset exceeding file boundary should produce an error, not an ICE.

r? @bjorn3

### CODE REVIEW

File: compiler/rustc_codegen_ssa/src/back/archive.rs [hunk 1]
```diff
@@ -320,6 +320,43 @@ pub trait ArchiveBuilder {
...
+        (ObjectArchiveKind::Gnu, ObjectArchiveKind::Gnu)
+        | (ObjectArchiveKind::Bsd, ObjectArchiveKind::Bsd)
+        | (ObjectArchiveKind::Bsd64, ObjectArchiveKind::Bsd64)
+        | (ObjectArchiveKind::Coff, ObjectArchiveKind::Coff)
+        | (ObjectArchiveKind::AixBig, ObjectArchiveKind::AixBig)
+        // 64-bit symbol table variants are compatible with their 32-bit counterparts
+        | (ObjectArchiveKind::Gnu64, ObjectArchiveKind::Gnu)
+        | (ObjectArchiveKind::Bsd64, ObjectArchiveKind::Bsd)
+        | (ObjectArchiveKind::Bsd, ObjectArchiveKind::Bsd64)
+    )
```
Comment (bjorn3) [inline compiler/rustc_codegen_ssa/src/back/archive.rs:353]: An archive file without long filenames and without a symbol table would result in `ObjectArchiveKind::Unknown`, which is compatible with all targets except possibly AIX. I'm not sure if the GNU format is disallowed on Windows.

*[View changes since the review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/rust/155721/d493b7c5ac637ed7edf626128b9f14796a2dad20..2080eff6ddf8ca70136400afa969cabf455aa9cc)*

File: compiler/rustc_codegen_ssa/src/back/archive.rs [hunk 2]
```diff
@@ -320,6 +320,43 @@ pub trait ArchiveBuilder {
...
+}
+
+fn archive_kinds_compatible(actual: ObjectArchiveKind, expected: ObjectArchiveKind) -> bool {
+    matches!(
+        (actual, expected),
+        (ObjectArchiveKind::Gnu, ObjectArchiveKind::Gnu)
+        | (ObjectArchiveKind::Bsd, ObjectArchiveKind::Bsd)
+        | (ObjectArchiveKind::Bsd64, ObjectArchiveKind::Bsd64)
+        | (ObjectArchiveKind::Coff, ObjectArchiveKind::Coff)
+        | (ObjectArchiveKind::AixBig, ObjectArchiveKind::AixBig)
```
Comment (bjorn3) [inline compiler/rustc_codegen_ssa/src/back/archive.rs]: I would collapse this to an `if actual == expected { return true; }`.

*[View changes since the review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/rust/155721/d493b7c5ac637ed7edf626128b9f14796a2dad20..2080eff6ddf8ca70136400afa969cabf455aa9cc)*

**Comment by Zalathar** [comment]
Let’s check that the test doesn’t cause problems on non-Linux hosts:

@bors try jobs=aarch64-apple,x86_64-msvc-1,aarch64-msvc-1

File: compiler/rustc_codegen_ssa/src/back/archive.rs (hunk 1 above)
Comment (cezarbbb) [reply compiler/rustc_codegen_ssa/src/back/archive.rs:353]: I think GNU and COFF archives share the same magic and member header format, only the symbol table layout differs.

File: compiler/rustc_codegen_ssa/src/back/archive.rs (hunk 2 above)
Comment (cezarbbb) [reply compiler/rustc_codegen_ssa/src/back/archive.rs]: Modified. Additionally, I added a match in `archive_kinds_compatible` to consider GNU and COFF as compatible.

File: tests/run-make/archive-format-error/rmake.rs [hunk 3]
```diff
@@ -4,25 +4,30 @@
...
-    llvm_ar().arg("rcus").arg("--format=bsd").output_input(&bsd_archive, "archive/native.o").run();
-    rustc()
-        .input("lib.rs")
-        .crate_type("rlib")
-        .library_search_path("archive")
-        .arg("-lstatic=native_bsd")
-        .run()
-        .assert_stderr_contains("BSD")
-        .assert_stderr_contains("GNU");
+    if target().contains("linux") {
```
Comment (bjorn3) [inline tests/run-make/archive-format-error/rmake.rs]: This should be `//@ only-linux` at the top of the file instead. Also why does this not work outside Linux?

*[View changes since the review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/rust/155721/d493b7c5ac637ed7edf626128b9f14796a2dad20..1bd31345618ac475b64f2fcb629813f31340b934)*

Comment (cezarbbb) [reply tests/run-make/archive-format-error/rmake.rs]: > This should be `//@ only-linux` at the top of the file instead.

If `//@only-linux` is added to the top of the file, the entire test will be skipped on non-Linux platforms, including Test 2. Test 2 is constructed from plain bytes, does not depend on cc() or any specific format, and should run on all platforms. Or would you prefer me to split it into two test files?

Comment (cezarbbb) [reply tests/run-make/archive-format-error/rmake.rs]: > Also why does this not work outside Linux?

On macOS, the target format is darwin (`Bsd64`), and (`Bsd`, `Bsd64`) is treated as compatible in `archive_kinds_compatible`, so no warning is emitted.
On Windows MSVC, the target format is `COFF`, not `GNU`, so the expected warning strings differ.

Comment (Zalathar) [reply tests/run-make/archive-format-error/rmake.rs]: If the two tests are independent and have different levels of portability, then splitting them is probably better.

Comment (cezarbbb) [reply tests/run-make/archive-format-error/rmake.rs]: > If the two tests are independent and have different levels of portability, then splitting them is probably better.

It has already been split.

File: compiler/rustc_codegen_ssa/src/back/archive.rs [hunk 4]
```diff
@@ -320,6 +320,49 @@ pub trait ArchiveBuilder {
...
+    }
+    matches!(
+        (actual, expected),
+        // An archive without long filenames or symbol table is detected as Unknown;
+        // this is compatible with any target format.
+        (ObjectArchiveKind::Unknown, _)
+        // 64-bit symbol table variants are compatible with their 32-bit counterparts
+        | (ObjectArchiveKind::Gnu64, ObjectArchiveKind::Gnu)
+        | (ObjectArchiveKind::Bsd64, ObjectArchiveKind::Bsd)
+        | (ObjectArchiveKind::Bsd, ObjectArchiveKind::Bsd64)
```
Comment (bjorn3) [inline compiler/rustc_codegen_ssa/src/back/archive.rs:347]: Why are 32bit and 64bit bsd considered compatible in both directions, but gnu only in one direction?

*[View changes since the review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/rust/155721/d493b7c5ac637ed7edf626128b9f14796a2dad20..32a9188210a4de8cd4d26538f2a0a650698cec42)*

File: compiler/rustc_codegen_ssa/src/back/archive.rs [hunk 5]
```diff
@@ -320,6 +320,49 @@ pub trait ArchiveBuilder {
...
+    )
+}
+
+fn archive_format_display_name(format: &str) -> String {
+    match format {
+        "gnu" | "Gnu" | "Gnu64" => "GNU".to_string(),
+        "bsd" | "Bsd" => "BSD".to_string(),
+        "darwin" | "Bsd64" => "Darwin".to_string(),
+        "coff" | "Coff" => "COFF".to_string(),
+        "aix_big" | "AixBig" => "AIX big".to_string(),
```
Comment (bjorn3) [inline compiler/rustc_codegen_ssa/src/back/archive.rs]: Why does this accept multiple casings while `target_archive_format_to_object_kind` only accepts a single one?

*[View changes since the review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/rust/155721/d493b7c5ac637ed7edf626128b9f14796a2dad20..32a9188210a4de8cd4d26538f2a0a650698cec42)*

File: compiler/rustc_codegen_ssa/src/back/archive.rs [hunk 6]
```diff
@@ -482,9 +538,25 @@ impl<'a> ArArchiveBuilder<'a> {
                 match entry {
                     ArchiveEntry::FromArchive { archive_index, file_range } => {
                         let src_archive = &self.src_archives[archive_index];
-
-                        let data = &src_archive.1
-                            [file_range.0 as usize..file_range.0 as usize + file_range.1 as usize];
+                        let archive_data = &src_archive.1;
+                        let start = file_range.0 as usize;
+                        let end = start + file_range.1 as usize;
+                        if end > archive_data.len() {
```
Comment (bjorn3) [inline compiler/rustc_codegen_ssa/src/back/archive.rs]: This could be simplified as `let Some(data) = archive_data.get(start..end) else { return Err(...); };`.

*[View changes since the review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/rust/155721/d493b7c5ac637ed7edf626128b9f14796a2dad20..32a9188210a4de8cd4d26538f2a0a650698cec42)*

File: compiler/rustc_codegen_ssa/src/errors.rs [hunk 7]
```diff
@@ -705,6 +705,18 @@ pub(crate) struct UnknownArchiveKind<'a> {
     pub kind: &'a str,
 }
 
+#[derive(Diagnostic)]
+#[diag("archive `{$path}` was built as {$actual} format, but the target expects {$expected}")]
+#[help(
+    "this often occurs when using BSD-format archive tools on a GNU/Linux target; \
```
Comment (bjorn3) [inline compiler/rustc_codegen_ssa/src/errors.rs]:
```suggestion
    "this often occurs when using BSD-format archive tools on a Linux target; \
```

we don't refer to it as GNU/Linux in any public interface anywhere else. Musl and clang are relatively common nowadays and the same problem can occur with Android, which is most certainly not GNU/Linux.

*[View changes since the review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/rust/155721/d493b7c5ac637ed7edf626128b9f14796a2dad20..32a9188210a4de8cd4d26538f2a0a650698cec42)*

File: tests/run-make/archive-corrupt-error/rmake.rs [hunk 8]
```diff
@@ -0,0 +1,52 @@
...
+    create_corrupt_archive(&corrupt_archive);
+    rustc()
+        .input("lib.rs")
+        .crate_type("rlib")
+        .library_search_path("archive")
+        .arg("-lstatic=corrupt")
+        .run_fail()
+        .assert_stderr_not_contains("panicked")
+        .assert_stderr_not_contains("unexpectedly panicked")
+        .assert_stderr_contains("archive");
```
Comment (bjorn3) [inline tests/run-make/archive-corrupt-error/rmake.rs]:
```suggestion
        .assert_stderr_contains("invalid archive member");
```

a bit more specific.

*[View changes since the review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/rust/155721/d493b7c5ac637ed7edf626128b9f14796a2dad20..32a9188210a4de8cd4d26538f2a0a650698cec42)*

File: tests/run-make/archive-corrupt-error/rmake.rs [hunk 9]
```diff
@@ -0,0 +1,52 @@
...
+
+    let mut archive = b"!<arch>\n".to_vec();
+
+    let member_name = "corrupt.o/        ";
+    let mtime = "0           ";
+    let uid = "0     ";
+    let gid = "0     ";
+    let mode = "100644  ";
+    let size = "10000       ";
+    let fmag = "`\n";
```
Comment (bjorn3) [inline tests/run-make/archive-corrupt-error/rmake.rs]: The resulting archive file could be directly checked in, right? It is not a binary file.

*[View changes since the review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/rust/155721/d493b7c5ac637ed7edf626128b9f14796a2dad20..32a9188210a4de8cd4d26538f2a0a650698cec42)*

File: tests/run-make/archive-format-error/rmake.rs [hunk 10]
```diff
@@ -0,0 +1,23 @@
...
+    let bsd_archive = path("archive").join(static_lib_name("native_bsd"));
+    llvm_ar().arg("rcus").arg("--format=bsd").output_input(&bsd_archive, "archive/native.o").run();
+    rustc()
+        .input("lib.rs")
+        .crate_type("rlib")
+        .library_search_path("archive")
+        .arg("-lstatic=native_bsd")
+        .run()
+        .assert_stderr_contains("BSD")
+        .assert_stderr_contains("GNU");
```
Comment (bjorn3) [inline tests/run-make/archive-format-error/rmake.rs]:
```suggestion
        .assert_stderr_contains("was built as BSD format, but the target expects GNU");
```

*[View changes since the review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/rust/155721/d493b7c5ac637ed7edf626128b9f14796a2dad20..32a9188210a4de8cd4d26538f2a0a650698cec42)*

File: compiler/rustc_codegen_ssa/src/back/archive.rs (hunk 4 above)
Comment (cezarbbb) [reply compiler/rustc_codegen_ssa/src/back/archive.rs:347]: The original omission of (`Gnu`, `Gnu64`) was because no current target sets archive_format to a value that maps to `Gnu64` — the only values used by built-in targets are `gnu`, `darwin`, `coff`, and `aix_big` (and no individual target overrides the default). So (`Gnu`, `Gnu64`) is technically unreachable.

However, (`Bsd64`, `Bsd`) is equally unreachable (no target uses plain `bsd` — macOS uses `darwin` which maps to `Bsd64`). For consistency I've added (`Gnu`, `Gnu64`) to make both pairs symmetric.

File: compiler/rustc_codegen_ssa/src/back/archive.rs (hunk 5 above)
Comment (cezarbbb) [reply compiler/rustc_codegen_ssa/src/back/archive.rs]: It was because the function was called with both target format strings (lowercase, like `gnu`) and Debug-formatted `ObjectArchiveKind` (like `Gnu64`). Refactored to `archive_kind_display_name(kind: ObjectArchiveKind)` — both call sites now pass `ObjectArchiveKind` directly, no more string juggling.

File: compiler/rustc_codegen_ssa/src/back/archive.rs (hunk 6 above)
Comment (cezarbbb) [reply compiler/rustc_codegen_ssa/src/back/archive.rs]: Done.

File: compiler/rustc_codegen_ssa/src/errors.rs (hunk 7 above)
Comment (cezarbbb) [reply compiler/rustc_codegen_ssa/src/errors.rs]: Thank you so much for the reminder! I will keep that in mind in my future contributions!

File: tests/run-make/archive-corrupt-error/rmake.rs (hunk 8 above)
Comment (cezarbbb) [reply tests/run-make/archive-corrupt-error/rmake.rs]: Applied.

File: tests/run-make/archive-format-error/rmake.rs (hunk 10 above)
Comment (cezarbbb) [reply tests/run-make/archive-format-error/rmake.rs]: Applied.

File: tests/run-make/archive-corrupt-error/rmake.rs (hunk 9 above)
Comment (cezarbbb) [reply tests/run-make/archive-corrupt-error/rmake.rs]: Yes, checked in as `corrupt.a`. The test now just copies it to the expected static library name at runtime.

**Comment by bjorn3** [comment]
@bors try jobs=aarch64-apple,x86_64-msvc-1,aarch64-msvc-1

r=me if the try run succeeds

**Comment by cezarbbb** [comment]
When the test is successful, I will squash the four commits together into one and then force-push again.
