### PR TITLE
NLL: Limit two-phase borrows to autoref-introduced borrows

### LINKED ISSUE #46747: for initial release, limit two phase borrows to method-call autorefs
@nikomatsakis is concerned that two-phased borrows are a hazard. In particular, they are coupled to MIR code-generation, which means if we are too aggressive in how much code we accept today, it could mean that a later change to MIR construction will inject a regression.

Niko has suggested a simple strategy for fixing this that we should deploy before we stabilize two-phase borrows: We should thread through information about whether a borrow was introduced via method-call autoref, and then *only* do the two-phase borrow system for those autorefs.

That way we will be somewhat conservative in what code is deemed acceptable by two-phase borrows today, and therefore give us more breathing room in the future as we refine the system.

### PR DESCRIPTION
**Pull request by pnkfelix**
This imposes a restriction on two-phase borrows so that it only applies to autoref-introduced borrows.

The goal is to ensure that our initial deployment of two-phase borrows is very conservative. We want it to still cover the `v.push(v.len());` example, but we do not want it to cover cases like `let imm = &v; let mu = &mut v; mu.push(imm.len());`

(Why do we want it to be conservative? Because when you are not conservative, then the results you get, at least with the current analysis, are tightly coupled to details of the MIR construction that we would rather remain invisible to the end user.)

Fix #46747 

I decided, for this PR, to add a debug-flag `-Z two-phase-beyond-autoref`, to re-enable the more general approach. But my intention here is *not* that we would eventually turn on that debugflag by default; the main reason I added it was that I thought it was useful for writing tests to be able to write source that looks like desugared MIR.

### CODE REVIEW

**Comment by pnkfelix** [comment]
> the main reason I added it was that I thought it was useful for writing tests to be able to write source that looks like desugared MIR.

(Incidentally, I keep toying with the idea of adding an opt-in way to write MIR directly, something analogous to how asm.js lets one write low-level operations using Javascript syntax.)

File: src/librustc_mir/hair/cx/expr.rs [hunk 1]
```diff
@@ -111,7 +112,7 @@ fn apply_adjustment<'a, 'gcx, 'tcx>(cx: &mut Cx<'a, 'gcx, 'tcx>,
                 span,
                 kind: ExprKind::Borrow {
                     region: deref.region,
-                    borrow_kind: to_borrow_kind(deref.mutbl),
+                    borrow_kind: to_borrow_kind(deref.mutbl, true),
```
Comment (nikomatsakis) [inline src/librustc_mir/hair/cx/expr.rs]: I think I expected us to push these flags even further back, to type check. I'm a bit wary that we may introduce adjustments for reasons that are not "autoref-autoderef in conjunction with method calls".

For example, does this type-check?

```rust
fn foo(x: &mut u32, y: u32) {
    *x += y;
}

fn bar(x: &mut u32) {
    foo(x, *x)
}
```

I think it might, because we get an implicit `&mut *x`  on the call, and that might be treated as two-phase. Similarly `let x: &mut u32 = x` or something like that.

File: src/librustc/ich/impls_mir.rs [hunk 2]
```diff
@@ -20,7 +20,8 @@ use std::mem;
 impl_stable_hash_for!(struct mir::GeneratorLayout<'tcx> { fields });
 impl_stable_hash_for!(struct mir::SourceInfo { span, scope });
 impl_stable_hash_for!(enum mir::Mutability { Mut, Not });
-impl_stable_hash_for!(enum mir::BorrowKind { Shared, Unique, Mut });
+impl_stable_hash_for!(struct mir::BorrowKind { mut_kind, introduced_via_autoref });
+impl_stable_hash_for!(enum mir::BorrowMutKind { Shared, Unique, Mut });
```
Comment (arielb1) [inline src/librustc/ich/impls_mir.rs]: bikeshed: name looks confusing, I would prefer `BorrowMutability`.

File: src/librustc/ich/impls_mir.rs [hunk 3]
```diff
@@ -20,7 +20,8 @@ use std::mem;
 impl_stable_hash_for!(struct mir::GeneratorLayout<'tcx> { fields });
 impl_stable_hash_for!(struct mir::SourceInfo { span, scope });
 impl_stable_hash_for!(enum mir::Mutability { Mut, Not });
-impl_stable_hash_for!(enum mir::BorrowKind { Shared, Unique, Mut });
+impl_stable_hash_for!(struct mir::BorrowKind { mut_kind, introduced_via_autoref });
```
Comment (arielb1) [inline src/librustc/ich/impls_mir.rs]: bikeshed: I would prefer the "operational" `always_allow_2phi` to the descriptive `introduced_via_autoref`.

File: src/librustc_mir/hair/cx/expr.rs (hunk 1 above)
Comment (nikomatsakis) [reply src/librustc_mir/hair/cx/expr.rs]: (Actually, I suppose we could conceivably thread a bit of state down during HAIR lowering to indicate whether the expression being coerced is in receiver position.)

File: src/librustc/ich/impls_mir.rs (hunk 3 above)
Comment (nikomatsakis) [reply src/librustc/ich/impls_mir.rs]: please call it "two phase", but yes that's a good point. Operational is often better.

File: src/librustc/ich/impls_mir.rs (hunk 2 above)
Comment (pnkfelix) [reply src/librustc/ich/impls_mir.rs]: (Hey look who it is!)

will do!

File: src/librustc/ich/impls_mir.rs (hunk 3 above)
Comment (pnkfelix) [reply src/librustc/ich/impls_mir.rs]: okay, this distinction doesn't matter to me, so I'll make this change.

File: src/librustc_mir/hair/cx/expr.rs (hunk 1 above)
Comment (pnkfelix) [reply src/librustc_mir/hair/cx/expr.rs]: I will figure out how to tighten the restriction. (As you have pointed out there may be different paths to getting there.)

Comment (pnkfelix) [reply src/librustc_mir/hair/cx/expr.rs]: (Though of course the example you give *is sound*; its just code that might surprise some if it passes, right? And anyway I agree that for our first deployment we should reject it)

Comment (nikomatsakis) [reply src/librustc_mir/hair/cx/expr.rs]: Yes, just surprising

**Comment by pnkfelix** [comment]
(sorry this is taking so long; I keep hitting #47381 and so that is slowing my progress

**Comment by kennytm** [comment]
Marking as blocked by #47381.

**Comment by pnkfelix** [comment]
(I'm hoping that now that I've rebased atop a `master` has ThinLTO turned off that I might stop hitting #47381? Though I'm not sure if that change has propagated yet into the betas that are used to build the stage1 `rustc` ...)

**Comment by pnkfelix** [comment]
@shepmaster I assume that you switched it from S-waiting-on-author to S-blocked because of #47381 ?

Just wanted to confirm, as after rebasing atop newer master, that bug is no longer blocking me. (And thus I am now switching it back to S-waiting-on-author)

**Comment by shepmaster** [comment]
> you switched it from S-waiting-on-author to S-blocked because of #47381 ?

That's right!

**Comment by nikomatsakis** [comment]
@pnkfelix at first glance, changes look good but appveyor won't run because of the merge conflict

File: src/librustc_mir/hair/cx/expr.rs [hunk 4]
```diff
@@ -642,10 +643,34 @@ fn method_callee<'a, 'gcx, 'tcx>(cx: &mut Cx<'a, 'gcx, 'tcx>,
...
-        hir::MutMutable => BorrowKind::Mut,
-        hir::MutImmutable => BorrowKind::Shared,
+trait ToBorrowKind { fn to_borrow_kind(&self) -> BorrowKind; }
+
+impl ToBorrowKind for AutoBorrowMutability {
+    fn to_borrow_kind(&self) -> BorrowKind {
+        match *self {
+            AutoBorrowMutability::Mutable { allow_two_phase_borrows } =>
+                BorrowKind { mut_kind: BorrowMutability::Mut,
+                             // FIXME ugh typo/inconsisten pluralization
```
Comment (pnkfelix) [inline src/librustc_mir/hair/cx/expr.rs]: heh I guess I should address this FIXME now that I have this working again

File: src/librustc_typeck/check/mod.rs [hunk 5]
```diff
@@ -2357,8 +2357,18 @@ impl<'a, 'gcx, 'tcx> FnCtxt<'a, 'gcx, 'tcx> {
...
                 let mut adjustments = autoderef.adjust_steps(needs);
                 if let ty::TyRef(region, mt) = method.sig.inputs()[0].sty {
+                    let mutbl = match mt.mutbl {
+                        hir::MutImmutable => AutoBorrowMutability::Immutable,
+                        hir::MutMutable => AutoBorrowMutability::Mutable {
+                            // FIXME: arguably indexing is "just
+                            // another kind of call"; perhaps it would
+                            // be more consistent to allow two-phase
+                            // borrows for .index() receivers here.
+                            allow_two_phase_borrows: false,
```
Comment (pnkfelix) [inline src/librustc_typeck/check/mod.rs]: (I think the test illustrates the kind of code that is being filtered out by not allowing two-phase borrows for index operators... I'll leave another comment with my thoughts on that test itself.)

File: src/test/compile-fail/borrowck/two-phase-nonrecv-autoref.rs [hunk 6]
```diff
@@ -0,0 +1,260 @@
...
+}
+
+fn coerce_unsized() {
+    let mut a = [1, 2, 3];
+
+    // This is not okay.
+    double_access(&mut a, &a);
+    //[lxl]~^   ERROR cannot borrow `a` as immutable because it is also borrowed as mutable [E0502]
+    //[nll]~^^  ERROR cannot borrow `a` as immutable because it is also borrowed as mutable [E0502]
+    //[g2p]~^^^ ERROR cannot borrow `a` as immutable because it is also borrowed as mutable [E0502]
```
Comment (pnkfelix) [inline src/test/compile-fail/borrowck/two-phase-nonrecv-autoref.rs]: Important: even the *generalized* form tested by `g2p`/`-Z two-phase-beyond-autoref` (thus no longer connected to autoref) is still rejecting this example. Compare that against `deref_coercion` above...

File: src/test/compile-fail/borrowck/two-phase-nonrecv-autoref.rs [hunk 7]
```diff
@@ -0,0 +1,260 @@
...
+
+impl IndexMut<i32> for I {
+    fn index_mut(&mut self, _: i32) -> &mut i32 {
+        &mut self.0
+    }
+}
+
+fn coerce_index_op() {
+    let mut i = I(10);
+    i[i[3]] = 4;
```
Comment (pnkfelix) [inline src/test/compile-fail/borrowck/two-phase-nonrecv-autoref.rs]: so the generalized (non-autoref-connected) `g2p` form starts allowing things like `i[i[3]] = ...`

I don't know about others, but I think ... that seems okay to allow...? (As in, it seems like a reasonable extension to consider, if not in the immediate release of two-phase borrows, then at some point in the future?)

Comment (nikomatsakis) [reply src/test/compile-fail/borrowck/two-phase-nonrecv-autoref.rs]: It [works for normal slices](https://play.rust-lang.org/?gist=72daf897f8db39bf6055bfb3efedc780&version=stable), so it seems ok to me.

**Comment by pnkfelix** [comment]
(skimming over the commit series, I realize now that some of the last minute refactorings I did yesterday brought the code into a state where I could get the diff much smaller. I'll take care of that now.)

**Comment by pnkfelix** [comment]
@nikomatsakis okay I am done polishing; you should be safe to do a review without me `push -f`'ing in parallel. :)

**Review by nikomatsakis — APPROVED** [review]
