### PR TITLE
std: Respect formatting flags for str-like OsStr

### LINKED ISSUE #43765: string fmt bug on nightly
I develop [artifact](https://github.com/vitiral/artifact) on nightly and publish using stable, so I am sensitive to changes that happen in nightly but not stable.


Right now the `fmt` functionality seems to be partially broken on nightly. [this commit](https://github.com/vitiral/artifact/commit/6c0f823dd0d8ee9b3a1162cd66e229bddecd8817) fails the unit test (running `cargo test`) `cmd::tests::test_ls::test_cmd_check`:



```
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.                                                                                                                            
stack backtrace:                                                                                                                                                                                                   
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace                                                                                                                                                     
             at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49                                                                                                                                        
   1: std::sys_common::backtrace::_print                                                                                                                                                                           
             at /checkout/src/libstd/sys_common/backtrace.rs:71                                                                                                                                                   
   2: std::panicking::default_hook::{{closure}}                                                                                                                                                                    
             at /checkout/src/libstd/sys_common/backtrace.rs:60                                                                                                                                                    
             at /checkout/src/libstd/panicking.rs:380                                                                                                                                                              
   3: std::panicking::default_hook                                                                                                                                                                                 
             at /checkout/src/libstd/panicking.rs:390                                                                                                                                                             
   4: std::panicking::rust_panic_with_hook                                                                                                                                                                        
             at /checkout/src/libstd/panicking.rs:610                                                    
   5: std::panicking::begin_panic                                                                                                                                                                                  
             at /checkout/src/libstd/panicking.rs:571                                                                                                                                                              
   6: std::panicking::begin_panic_fmt                                                                                                                                                                              
             at /checkout/src/libstd/panicking.rs:521                                                                                                                                                              
   7: artifact_app::cmd::tests::test_ls::test_cmd_check                                                                                                                                                            
             at src/cmd/tests/test_ls.rs:260                                                                                                                                                                      
   8: <F as test::FnBox<T>>::call_box                                                                                                                                                                              
             at /checkout/src/libtest/lib.rs:1477                                                                                                                                                                  
             at /checkout/src/libcore/ops/function.rs:143                                                                                                                                                          
             at /checkout/src/libtest/lib.rs:138                                                                                                                                                                   
   9: __rust_maybe_catch_panic                                                                                                                                                                                     
             at /checkout/src/libpanic_unwind/lib.rs:98                                                                                                                                                            
                                                                                             
                                                                                                                                                                                                                   
failures:                                                                                                                                                                                                          
    cmd::tests::test_ls::test_cmd_check                                                                                                                                                                            
                                                                                                                                                                                                                   
test result: FAILED. 34 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out                                                                                                                                    
                                                                                                                                                                                                                  
error: test failed, to rerun pass '--lib'               
```


The test prints the expected/result. That printout is:
```
Debug Result:                                                                                                                                                                                                      
                                                                                                                                                                                                                  
Found partof names that do not exist:                                                                                                                                                                              
- REQ-invalid-parts [../../reqs/foo.toml]: {REQ-DNE}                                                                                                                                                               
                                                                                                                                                                                                                   
Artifacts partof contains at least one recursive reference:                                                                                                                                                        
- SPC-unresolvable              : [SPC-UNRESOLVABLE-1-1]                                                                                                                                                          
- SPC-unresolvable-1            : [SPC-UNRESOLVABLE]                                                                                                                                                              
- SPC-unresolvable-1-1          : [SPC-UNRESOLVABLE-1]                                                   
                                                                                                                                                                                                                   
Found implementation links in the code that do not exist:                                                                                                                                                          
- ../../fake:                                                                                                                                                                                                      
  - [42] SPC-dne                                                                                                                                                                                                   
                                                                                                                                                                                                                   
Hanging artifacts found (top-level but not partof a higher type):                                                                                                                                                 
- ../../reqs/foo.toml: TST-line                                                                                                                                                                                    
                                                                                                                                                                                                                   
Repr Result:                                                                                                                                                                                                       
\x1b[1;31m\nFound partof names that do not exist:\n\x1b[0m\x1b[31m- REQ-invalid-parts [../../reqs/foo.toml]: {REQ-DNE}\n\x1b[0m\x1b[1;31m\nArtifacts partof contains at least one recursive reference:\n\x1b[0m- SP
C-unresolvable              : [SPC-UNRESOLVABLE-1-1]\n- SPC-unresolvable-1            : [SPC-UNRESOLVABLE]\n- SPC-unresolvable-1-1          : [SPC-UNRESOLVABLE-1]\n\x1b[1;31m\nFound implementation links in the c
ode that do not exist:\n\x1b[0m\x1b[31m- ../../fake:\n\x1b[0m\x1b[31m  - [42]\x1b[0m SPC-dne\n\x1b[1;31m\nHanging artifacts found (top-level but not partof a higher type):\n\x1b[0m- ../../reqs/foo.toml: TST-line
\n\n                                                                                         
--Result Repr DONE
```

```
Debug Expected:                                                                                                                                                                                                    
                                                                                                                                                                                                                   
Found partof names that do not exist:                                                                                                                                                                              
- REQ-invalid-parts [../../reqs/foo.toml]: {REQ-DNE}                                                                                                                                                               
                                                                                                                                                                                                                  
Artifacts partof contains at least one recursive reference:                                                                                                                                                        
- SPC-unresolvable              : [SPC-UNRESOLVABLE-1-1]                                                                                                                                                           
- SPC-unresolvable-1            : [SPC-UNRESOLVABLE]                                                                                                                                                               
- SPC-unresolvable-1-1          : [SPC-UNRESOLVABLE-1]                                                                                                                                                             
                                                                                                                                                                                                                  
Found implementation links in the code that do not exist:                                                                                                                                                         
- ../../fake:                                                                                            
  - [42] SPC-dne                                                                                                                                                                                                   
                                                                                                                                                                                                                   
Hanging artifacts found (top-level but not partof a higher type):                                                                                                                                                  
- ../../reqs/foo.toml           : TST-line                                                                                                                                                                         
                                                                                                                                                                                                                   
Repr Expected:                                                                                                                                                                                                    
\x1b[1;31m\nFound partof names that do not exist:\n\x1b[0m\x1b[31m- REQ-invalid-parts [../../reqs/foo.toml]: {REQ-DNE}\n\x1b[0m\x1b[1;31m\nArtifacts partof contains at least one recursive reference:\n\x1b[0m- SP
C-unresolvable              : [SPC-UNRESOLVABLE-1-1]\n- SPC-unresolvable-1            : [SPC-UNRESOLVABLE]\n- SPC-unresolvable-1-1          : [SPC-UNRESOLVABLE-1]\n\x1b[1;31m\nFound implementation links in the c
ode that do not exist:\n\x1b[0m\x1b[31m- ../../fake:\n\x1b[0m\x1b[31m  - [42]\x1b[0m SPC-dne\n\x1b[1;31m\nHanging artifacts found (top-level but not partof a higher type):\n\x1b[0m- ../../reqs/foo.toml          
 : TST-line\n\n                                                                                                                                                                                                    
--Expected Repr DONE
```

The difference between the two (that I can spot) is these two lines:
```
# result
- ../../reqs/foo.toml: TST-line
# expected                                                                                                                                         
- ../../reqs/foo.toml           : TST-line
```

I went into the code to find what generates this formatting, it is in `src/cmd/check.rs` line 234:
```
            write!(
                msg,
                "- {:<30}: {}\n",
                utils::relative_path(p, cwd).display(),
                h
            ).unwrap();
```

Oddly, there is a very similar line of code that is used to generate the `Artifacts partof contains at least one recursive reference:` section of the output. That line of code is in the same file, line 159:
```
write!(msg, "- {:<30}: {:?}\n", name.to_string(), partof).unwrap();
```

That line works, the other one doesn't. Why? That I have no clue about...

## Meta

This passes (running `cargo test`) on 
```
$ rustc --version --verbose   
rustc 1.19.0 (0ade33941 2017-07-17)                 
binary: rustc             
commit-hash: 0ade339411587887bf01bcfa2e9ae4414c8900d4                                                    
commit-date: 2017-07-17   
host: x86_64-unknown-linux-gnu                      
release: 1.19.0           
LLVM version: 4.0
```

And fails on
```
$ rustc --version --verbose                                                                                                                                                           
rustc 1.21.0-nightly (cbbe17aa7 2017-08-07)                                                                                                                                                                       
binary: rustc
commit-hash: cbbe17aa7f13f9568a652c2180de03fa6881b86a
commit-date: 2017-08-07
host: x86_64-unknown-linux-gnu
release: 1.21.0-nightly
LLVM version: 4.0

# and fails for this as well
$ rustc --version                                                                                                                                                                     
rustc 1.21.0-nightly (b75d1f0ce 2017-08-02)
```

### PR DESCRIPTION
**Pull request by alexcrichton**
Historically many `Display` and `Debug` implementations for `OsStr`-like
abstractions have gone through `String::from_utf8_lossy`, but this was updated
in #42613 to use an internal `Utf8Lossy` abstraction instead. This had the
unfortunate side effect of causing a regression (#43765) in code which relied on
these `fmt` trait implementations respecting the various formatting flags
specified.

This commit opportunistically adds back interpretation of formatting trait flags
in the "common case" where where `OsStr`-like "thing" is all valid utf-8 and can
delegate to the formatting implementation for `str`. This doesn't entirely solve
the regression as non-utf8 paths will format differently than they did before
still (in that they will not respect formatting flags), but this should solve
the regression for all "real world" use cases of paths and such. The door's also
still open for handling these flags in the future!

Closes #43765

### CODE REVIEW

File: src/libstd_unicode/lossy.rs [hunk 1]
```diff
@@ -153,7 +153,21 @@ impl<'a> Iterator for Utf8LossyChunksIter<'a> {
 
 impl fmt::Display for Utf8Lossy {
     fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
+        // If we're the empty string then our iterato won't actually yield
```
Comment (vitiral) [inline src/libstd_unicode/lossy.rs]: `iterato` -> `iterator`

File: src/libstd/path.rs [hunk 2]
```diff
@@ -3953,4 +3953,10 @@ mod tests {
         assert_eq!(path, path_buf);
         assert!(path_buf.into_os_string().capacity() >= 15);
     }
+
+    #[test]
+    fn display_format_flags() {
+        assert_eq!(format!("a{:#<5}b", Path::new("").display()), "a#####b");
```
Comment (vitiral) [inline src/libstd/path.rs]: thanks for adding these tests!

**Review by vitiral — COMMENTED** [review]
this looks like a good stopgap to me. I might want to take a shot at fixing this more thouroughly in the future.

**Comment by vitiral** [comment]
one of the issues with formatting non-utf8 strings (in the future) is what do we even do? Invalid characters are... invalid, so how many "spaces" do they take? (I assume zero)

**Comment by ollie27** [comment]
>one of the issues with formatting non-utf8 strings (in the future) is what do we even do? Invalid characters are... invalid, so how many "spaces" do they take? (I assume zero)

You'd just need to match the behavior of: https://github.com/rust-lang/rust/blob/adbce60d6f131e5b3789f01417dedb05e4489898/src/libcore/fmt/mod.rs#L1111-L1149 when given a string from `to_string_lossy`. So each replacement character just counts as 1.

**Review by ollie27 — COMMENTED** [review]
I believe this will also need to be applied to `Wtf8` for it to work on Windows:

https://github.com/rust-lang/rust/blob/adbce60d6f131e5b3789f01417dedb05e4489898/src/libstd/sys_common/wtf8.rs#L441-L463

**Comment by alexcrichton** [comment]
Fixed typo and updated wtf-8 as well

**Comment by carols10cents** [comment]
actually oops this is libs sooo

r? @aturon

**Comment by alexcrichton** [comment]
@bors: p=1

(beta backport)

**Comment by alexcrichton** [comment]
Discussed and decided for backport today

**Comment by alexcrichton** [comment]
We discussed as well that we should have a tracking bug for support all formatting flags here, so I've opened https://github.com/rust-lang/rust/issues/44048

**Comment by alexcrichton** [comment]
@bors: retry

* https://github.com/rust-lang/rust/issues/43985
