### PR TITLE
Undo an assert causing an ICE until we fix the underlying problem

### LINKED ISSUE #65462: ICE: "Tried to access field 0 of union with 0 fields"
I get the following internal compiler error with rustc nightly:
```
thread 'rustc' panicked at 'Tried to access field 0 of union with 0 fields', src/librustc_target/abi/mod.rs:742:17
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.40.0-nightly (e413dc36a 2019-10-14) running on x86_64-unknown-linux-gnu

note: compiler flags: -C debuginfo=2 -C incremental --crate-type lib

note: some of the compiler flags provided by cargo are hidden
```

To reproduce, just checkout the repo at the following commit: https://github.com/paritytech/polkadot/commit/317411718ce6450923aa2b8ef6ebae4eba9408e5

Run: `BUILD_DUMMY_WASM_BINARY=1 cargo build -p polkadot-service`

### PR DESCRIPTION
**Pull request by oli-obk**
r? @eddyb

fixes #65462

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
Leaving a note here that if we don't beta accept this PR we should make sure to open an issue tracking this regression so we don't forget about it.

**Comment by pnkfelix** [comment]
[beta-accepted](https://zulip-archive.rust-lang.org/131828tcompiler/21461weeklymeeting2019111454818.html#180739560) (last week, sorry for delay!)

File: src/librustc_target/abi/mod.rs [hunk 1]
```diff
@@ -694,11 +694,7 @@ impl FieldPlacement {
 
     pub fn offset(&self, i: usize) -> Size {
         match *self {
-            FieldPlacement::Union(count) => {
-                assert!(i < count,
-                        "Tried to access field {} of union with {} fields", i, count);
```
Comment (RalfJung) [inline src/librustc_target/abi/mod.rs]: Would have been good to at least leave a FIXME in place here so that future readers of this code know there *should* be an assertion. I just had to rediscover this by browsing the rustc source starting somewhere in codegen.
