### PR TITLE
Check stability and feature attributes in rustdoc

### LINKED ISSUE #82588: Rustdoc allows multiple declarations of a feature
I tried this code:

```rust
#![feature(doc_cfg)]
#![feature(doc_cfg)]

fn main() {
    println!("Hello, world!");
}
```

I expected to see this happen: Both `cargo build` and `cargo doc` to fail because of multiple declarations of the `doc_cfg` feature.

Instead, this happened: `cargo build` failed while `cargo doc` succeeded:

```console
> cargo build
   Compiling foo v0.1.0 (/tmp/tmp.NidTpZ70xE/foo)
error[E0636]: the feature `doc_cfg` has already been declared
 --> src/main.rs:2:12
  |
2 | #![feature(doc_cfg)]
  |            ^^^^^^^

error: aborting due to previous error

For more information about this error, try `rustc --explain E0636`.
error: could not compile `foo`

To learn more, run the command again with --verbose.

> cargo doc
 Documenting foo v0.1.0 (/tmp/tmp.NidTpZ70xE/foo)
    Finished dev [unoptimized + debuginfo] target(s) in 0.48s
```

### Meta
`rustc --version --verbose`:
```
rustc 1.52.0-nightly (07194ffcd 2021-02-10)
binary: rustc
commit-hash: 07194ffcd25b0871ce560b9f702e52db27ac9f77
commit-date: 2021-02-10
host: x86_64-unknown-linux-gnu
release: 1.52.0-nightly
LLVM version: 11.0.1
```

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Fixes #82588.

cc @Nemo157 @camelid  
r? @jyn514

### CODE REVIEW

File: src/librustdoc/passes/rustc_checks.rs [hunk 1]
```diff
@@ -0,0 +1,14 @@
...
+use crate::passes::Pass;
+
+crate const RUSTC_CHECKS: Pass = Pass {
+    name: "rustc-checks",
+    run: run_rustc_checks,
+    description: "counts the number of items with and without documentation",
+};
+
+crate fn run_rustc_checks(krate: clean::Crate, ctx: &mut DocContext<'_>) -> clean::Crate {
+    rustc_passes::stability::check_unused_or_stable_features(ctx.tcx);
```
Comment (jyn514) [inline src/librustdoc/passes/rustc_checks.rs:12]: This seems way overkill for a single line of code (and also not great from the behavior difference - I don't think people should be able to turn this off with --no-default-passes). Can you move it to core directly instead?

Comment (GuillaumeGomez) [reply src/librustdoc/passes/rustc_checks.rs:12]: I just thought we could potentially expand this in the future. But I can move it in `core` directly if you prefer.

Comment (jyn514) [reply src/librustdoc/passes/rustc_checks.rs:12]: I think anything like this in the future should also be in core.

Comment (GuillaumeGomez) [reply src/librustdoc/passes/rustc_checks.rs:12]: Fine by me! Gonna move this function then (not calling it directly I will!).

**Comment by GuillaumeGomez** [comment]
Updated!

File: src/librustdoc/core.rs [hunk 2]
```diff
@@ -458,6 +458,11 @@ crate fn create_resolver<'a>(
     resolver.clone()
 }
 
+/// This where the rustc specific passes should be placed.
+fn run_rustc_checks(tcx: TyCtxt<'_>) {
+    rustc_passes::stability::check_unused_or_stable_features(tcx);
+}
```
Comment (jyn514) [inline src/librustdoc/core.rs:464]: I'm not sure why you're still treating this differently. If you're going to group the rustc-specific things together, I would put this near https://github.com/rust-lang/rust/blob/3127a8d9ec95ec11a4cf039305e7bbc54a436b6b/src/librustdoc/core.rs#L486-L499. I would prefer not to make it a separate function so it's easier to see what's going on.

Comment (GuillaumeGomez) [reply src/librustdoc/core.rs]: Moved there!

File: src/librustdoc/core.rs [hunk 3]
```diff
@@ -492,6 +492,9 @@ crate fn run_global_ctxt(
             tcx.ensure().check_mod_attrs(module);
         }
     });
+    tcx.sess.time("rustc_check_passes", || {
```
Comment (jyn514) [inline src/librustdoc/core.rs:495]: I wouldn't expect this to take very long - can you run `-Z time-passes` locally and see if it takes more than, say, 10 milliseconds? If not I don't think it's worth timing.
```suggestion
    tcx.sess.time("check_unused_or_stable_features", || {
```

Comment (GuillaumeGomez) [reply src/librustdoc/core.rs:495]: I'll simply remove it then.

**Comment by GuillaumeGomez** [comment]
As for the libstd feature, I could only reproduce it locally after updating to last commit so I guess it's a very recent change and it was an incomplete one. Lucky us that we found out this early.

**Comment by camelid** [comment]
Heh, I thought the lack of a stability attribute might be an issue! https://github.com/rust-lang/rust/pull/82420#discussion_r580685576

File: library/std/src/os/mod.rs [hunk 4]
```diff
@@ -23,6 +23,7 @@ pub use crate::sys::windows_ext as windows;
 pub mod linux;
 
 #[cfg(doc)]
+#[stable(feature = "rust1", since = "1.0.0")]
 pub use crate::sys::wasi_ext as wasi;
```
Comment (jyn514) [inline library/std/src/os/mod.rs:27]: This is weird. Why is this doc-only? Why would a stability attribute be needed if it's not present when running normally?

Comment (GuillaumeGomez) [reply library/std/src/os/mod.rs:27]: The attribute needs to be applied to the item since we're now checking for it. As for why "doc-only", I think this question is out of the scope of this PR. ;)

Comment (jyn514) [reply library/std/src/os/mod.rs:27]: @sunfishcode do you know why this is `cfg(doc)` only? It seems weird to have stability attributes on things that aren't available when writing your own code.

Comment (jyn514) [reply library/std/src/os/mod.rs:27]: Also @GuillaumeGomez 1.0.0 is wrong I think, wasi was first added in https://github.com/rust-lang/rust/pull/59464 which landed in 1.35.0.

Comment (sunfishcode) [reply library/std/src/os/mod.rs:27]: The reason this is `cfg(doc)` is the same reason the `unix`, and `windows`, modules are `cfg(doc)`.

My understanding of this code is from the comment above, on line 6. This is all a way to include the platform-specific documentation for all the platforms in a single documentation build. These aren't the definitions that get used when doing actual non-doc compilation.

Comment (jyn514) [reply library/std/src/os/mod.rs:27]: Got it, thanks. Is 1.35 the right date for being marked as stable? I think @alexcrichton mentioned in https://github.com/rust-lang/rust/pull/59464 that the module wasn't being stabilized right away, but I couldn't find a PR stabilizing it anywhere.

Comment (GuillaumeGomez) [reply library/std/src/os/mod.rs:27]: I used the same as https://github.com/rust-lang/rust/blob/master/library/std/src/sys/mod.rs#L114

Comment (jyn514) [reply library/std/src/os/mod.rs:27]: That stability attribute also seems wrong.

Comment (GuillaumeGomez) [reply library/std/src/os/mod.rs:27]: Yup, but not sure how to handle this situation...

Comment (sunfishcode) [reply library/std/src/os/mod.rs:27]: The individual inner modules such as [`io`](https://github.com/rust-lang/rust/blob/master/library/std/src/sys/wasi/ext/io.rs#L4) and [`fs`](https://github.com/rust-lang/rust/blob/master/library/std/src/sys/wasi/ext/fs.rs#L4) have `#![unstable(feature = "wasi_ext", issue = "none")]`. So I'd imagine it's ok to mark the outer module as `stable`, because that just contains the inner modules, and the fact that there just exists a module inside it named "fs" and one named "io" is something I think we can consider stable.

Comment (jyn514) [reply library/std/src/os/mod.rs:27]: Ok, then @GuillaumeGomez can you update the attributes to show 1.35? I think this is good to go after that :)

**Comment by GuillaumeGomez** [comment]
Update the version to 1.35 in both attributes.

**Comment by jyn514** [comment]
Thanks. Can you also update https://github.com/rust-lang/rust/blob/e2c175ecdf0207bd34192c292dabd816659b370c/library/std/src/sys/mod.rs#L114 while you're at it?

**Comment by GuillaumeGomez** [comment]
Done as well!

**Comment by jyn514** [comment]
r=me with CI passing, thanks for fixing this!
