### PR TITLE
 [MIR] Fix double-rounding of float constants and ignore NaN sign in tests.

### LINKED ISSUE #32805: MIR is double-rounding f32 literals
## STR

```Rust
#![feature(rustc_attrs)]

#[rustc_mir]
fn const_mir() -> f32 { 9007199791611905.0 }

fn const_old() -> f32 { 9007199791611905.0 }

fn main() {
    let s = "9007199791611905.0"; // (1<<53)+(1<<29)+1
    println!("old: {}", const_old());
    println!("MIR: {}", const_mir());
    println!("single rounding: {}", s.parse::<f32>().unwrap());
    println!("double rounding: {}", s.parse::<f64>().unwrap() as f32);
}
```

## Expected Result

Both MIR and old trans should use a single rounding, that's it
```
old: 9007200000000000
MIR: 9007200000000000
single rounding: 9007200000000000
double rounding: 9007199000000000
```

## Actual Result

old trans is single-rounding as it should, but MIR is doing a double rounding:
```
old: 9007200000000000
MIR: 9007199000000000
single rounding: 9007200000000000
double rounding: 9007199000000000
```

### PR DESCRIPTION
**Pull request by eddyb**
Fixes #32805 by handling f32 and f64 separately in rustc_const_eval.

Also removes `#[rustc_no_mir]` from a couple libstd tests by ignoring NaN sign.
Turns out that runtime evaluation of `0.0 / 0.0` produces a NaN with the sign bit set,
whereas LLVM constant folds it to a NaN with the sign bit unset, which we were testing for.

### CODE REVIEW

File: src/librustc_const_math/float.rs [hunk 1]
```diff
@@ -0,0 +1,171 @@
...
+impl PartialEq for ConstFloat {
+    fn eq(&self, other: &Self) -> bool {
+        match (*self, *other) {
+            (F64(a), F64(b)) |
+            (F64(a), FInfer { f64: b, .. }) |
+            (FInfer { f64: a, .. }, F64(b)) |
+            (FInfer { f64: a, .. }, FInfer { f64: b, .. }) => {
+                unsafe{transmute::<_,u64>(a) == transmute::<_,u64>(b)}
+            }
+            (F32(a), F32(b)) => {
```
Comment (oli-obk) [inline src/librustc_const_math/float.rs]: This also needs the `FInfer` branches for `f32` inference

File: src/librustc_const_math/float.rs [hunk 2]
```diff
@@ -0,0 +1,171 @@
...
+
+impl Eq for ConstFloat {}
+
+impl hash::Hash for ConstFloat {
+    fn hash<H: hash::Hasher>(&self, state: &mut H) {
+        match *self {
+            F64(a) | FInfer { f64: a, .. } => {
+                unsafe { transmute::<_,u64>(a) }.hash(state)
+            }
+            F32(a) => {
```
Comment (oli-obk) [inline src/librustc_const_math/float.rs]: same here (`FInfer` for `f32`)

File: src/librustc_const_math/float.rs (hunk 1 above)
Comment (eddyb) [inline src/librustc_const_math/float.rs]: Oops, thanks for noticing!

File: src/libstd/num/f32.rs [hunk 3]
```diff
@@ -1391,7 +1390,11 @@ mod tests {
         assert_eq!((-0f32).integer_decode(), (0, -150, -1));
         assert_eq!(INFINITY.integer_decode(), (8388608, 105, 1));
         assert_eq!(NEG_INFINITY.integer_decode(), (8388608, 105, -1));
-        assert_eq!(NAN.integer_decode(), (12582912, 105, 1));
+
+        // Ignore the "sign" (quiet / signalling flag) of NAN.
+        // It can vary between runtime operations and LLVM folding.
+        let (nan_m, nan_e, _nan_s) = NAN.integer_decode();
+        assert_eq!((nan_m, nan_e), (12582912, 105));
```
Comment (nagisa) [inline src/libstd/num/f32.rs]: I can’t believe this test worked for so long on all of the platforms we support, because mantissa of NaN is not specified to be anything in particular. The only requirement is that the MSB of the mantissa is set to 1 to differentiate from infinity.

Comment (eddyb) [inline src/libstd/num/f32.rs]: @nagisa Well, LLVM was always doing the folding for us, and it always produces the same result.

**Comment by eddyb** [comment]
@alexcrichton ^^ Spurious?

**Comment by alexcrichton** [comment]
@eddyb hm maybe yeah, I can't really come up with an explanation otherwise. PR definitely doesn't touch Cargo.* anywhere as "cargo" isn't anywhere in the diff, so I'm not really sure how this could happen. Let's retry for now and if it happens again I can try to investigate further.

@bors: retry
