### PR TITLE
macros: allow a `path` fragment to be parsed as a type parameter bound

### LINKED ISSUE #8521: Can't bound types with paths from macros
This code:

``` rust
macro_rules! foo(($t:path) => {
    impl<T:$t> Foo for T {}
})

foo!(A)

fn main() {}
```

fails with

```
foo.rs:2:12: 2:13 error: expected `,` but found `an interpolated path`
foo.rs:2     impl<T:$t> Foo for T {}
                     ^
```

I may be doing something wrong, but this should be allowed, right?

### PR DESCRIPTION
**Pull request by KalitaAlexey**
Allow a `path` fragment to be parsed as a type parameter bound.
Fixes #8521.

### CODE REVIEW

**Comment by KalitaAlexey** [comment]
It has failed. Is it me?

**Comment by bluss** [comment]
It looks like the failure is not related to the PR, it ran all tests successfully.

Unfortunately all PRs fail on travis right now: https://travis-ci.org/rust-lang/rust/builds

**Comment by KalitaAlexey** [comment]
Hi @bluss,

Thank you for the explanation.

Should I just wait or what?

Regards,
Alexey

**Comment by bluss** [comment]
Wait or maybe seek out and ask if someone wants to review your PR. It's not my area, so I will not review it.

**Comment by brson** [comment]
@KalitaAlexey @nrc will review soon, but has been traveling lately.

**Comment by KalitaAlexey** [comment]
Hi @brson,

I'll wait. It's not problem.

Regards,
Alexey

File: src/libsyntax/parse/parser.rs [hunk 1]
```diff
@@ -4173,6 +4174,29 @@ impl<'a> Parser<'a> {
...
+                            } else {
+                                TraitBoundModifier::None
+                            };
+                            result.push(TraitTyParamBound(poly_trait_ref, modifier));
+                            should_bump = true;
+                        }
+                        _ => break,
+                    }
+                }
                 token::ModSep | token::Ident(..) => {
```
Comment (jseyfried) [inline src/libsyntax/parse/parser.rs]: Instead of adding the `token::Interpolated(ref nt) => { ... }` arm, I believe you could just change this pattern to
```rust
        _ if self.token.is_path_start() || self.token.is_keyword(keywords::For) => { ... }
```

File: src/test/ui/macros/macro_path_as_generic_bound.rs [hunk 2]
```diff
@@ -0,0 +1,20 @@
...
+// Licensed under the Apache License, Version 2.0 <LICENSE-APACHE or
+// http://www.apache.org/licenses/LICENSE-2.0> or the MIT license
+// <LICENSE-MIT or http://opensource.org/licenses/MIT>, at your
+// option. This file may not be copied, modified, or distributed
+// except according to those terms.
+
+trait Foo {}
+
+macro_rules! foo(($t:path) => {
+  impl<T: $t> Foo for T {}
```
Comment (jseyfried) [inline src/test/ui/macros/macro_path_as_generic_bound.rs]: nit: indent 4 spaces

File: src/test/ui/macros/macro_path_as_generic_bound.rs [hunk 3]
```diff
@@ -0,0 +1,20 @@
...
+});
+
+foo!(m::m2::A);
+
+fn main() {}
+
```
Comment (jseyfried) [inline src/test/ui/macros/macro_path_as_generic_bound.rs]: nit: trailing newline (in both tests)

**Comment by jseyfried** [comment]
cc @petrochenkov

File: src/libsyntax/parse/parser.rs (hunk 1 above)
Comment (KalitaAlexey) [inline src/libsyntax/parse/parser.rs]: I'll examine your suggestion.

File: src/test/ui/macros/macro_path_as_generic_bound.rs (hunk 2 above)
Comment (KalitaAlexey) [inline src/test/ui/macros/macro_path_as_generic_bound.rs]: I'll fix it.

File: src/test/ui/macros/macro_path_as_generic_bound.rs (hunk 3 above)
Comment (KalitaAlexey) [inline src/test/ui/macros/macro_path_as_generic_bound.rs]: I'll fix it.

**Comment by KalitaAlexey** [comment]
Hi @jseyfried,
My commit somehow breaks src/test/run-pass/issue-28950.rs
I don't understand why.

Could you look at it?

Thanks

**Comment by jseyfried** [comment]
- What commit breaks `run-pass/issue-28950.rs`? The current PR or [my suggestion](https://github.com/rust-lang/rust/pull/38279#discussion_r91881414)?
 - In what way does it break? What is the error message?

**Comment by KalitaAlexey** [comment]
@jseyfried,

I don't know why, but my PR enough to break the test.
I checked it before and it worked.
It should run and pass, but it crashes with segfault.

Thanks

**Comment by jseyfried** [comment]
That sounds unrelated to this PR, but I don't have enough information to help debug further. Could you provide hash of the commit that breaks the test, the exact output when it crashes, and ideally a backtrace?

**Comment by KalitaAlexey** [comment]
Hm. Actually my installed rustc also creates an executable failing with segfault.

**Comment by Mark-Simulacrum** [comment]
@KalitaAlexey Can you attempt to provide a backtrace? Either way, please file a new issue (since this seems unrelated to this PR), with your OS distro and version, as well as rustc version so we can try to diagnose. I just verified locally, and it doesn't segfault for me.

**Comment by Mark-Simulacrum** [comment]
Never mind. I had forgotten to run the produced executable, will post the new issue myself once I get a backtrace if you don't get to it first.

**Comment by Mark-Simulacrum** [comment]
Oh. That tests currently doesn't support non-optimized codegen (no `-O`); @KalitaAlexey are you running without that for some reason?

**Comment by KalitaAlexey** [comment]
Hi @Mark-Simulacrum,

I just ran `./x.py test`.

**Comment by KalitaAlexey** [comment]
Hi @jseyfried,

I applied your suggestions.

Thanks.

File: src/test/run-pass/issue-8521.rs [hunk 4]
```diff
@@ -0,0 +1,35 @@
...
+struct C {}
+
+macro_rules! foo2(($t:path) => {
+    impl<T: $t> Foo2 for T {}
+});
+
+foo2!(B<C>);
+
+fn main() {}
+
```
Comment (jseyfried) [inline src/test/run-pass/issue-8521.rs]: nit: trailing newline

**Review by jseyfried — COMMENTED** [review]
r=me modulo nit

File: src/test/run-pass/issue-8521.rs [hunk 5]
```diff
@@ -0,0 +1,35 @@
+// Copyright 2014 The Rust Project Developers. See the COPYRIGHT
```
Comment (jseyfried) [inline src/test/run-pass/issue-8521.rs]: nit: `2016`, not `2014`

Comment (KalitaAlexey) [inline src/test/run-pass/issue-8521.rs]: I'll fix it.

**Comment by KalitaAlexey** [comment]
@jseyfried, I've done it.

**Comment by jseyfried** [comment]
@KalitaAlexey Thanks!
One last thing -- could you squash the commits so that this PR is a single commit?

**Comment by KalitaAlexey** [comment]
@jseyfried, how should I do it? I don't know right way.

**Comment by jseyfried** [comment]
```
cd rust
git checkout master
git checkout -b tmp
git merge issue-8521 --no-ff
git reset HEAD~
git add src
git commit -m "allow path fragments to be parsed as type parameter bounds"
git branch -D issue-8521
git branch -m issue-8521
git push origin issue-8521 --force
```

**Comment by KalitaAlexey** [comment]
I've done what you had suggested me. Thank you.
