### PR TITLE
Delegation: fix ICE with invalid `MethodCall` generation

### LINKED ISSUE #127916: ICE: delegation: `unexpected parent of trait or impl item or item not found`
auto-reduced (treereduce-rust):
````rust

trait Trait {
    fn foo(&self) -> u32 { 0 }
}

struct F;
struct S;

mod to_reuse {
    pub fn foo(&self) -> u32 {}
}

impl Trait  S {
    reuse to_reuse::foo { self }
}


````

original:
````rust
#![feature(fn_delegation)]
#![allow(incomplete_features)]

trait Trait {
    fn foo(&self) -> u32 { 0 }
}

struct F;
struct S;

mod to_reuse {
    use crate::S;

    pub fn foo(&self) -> u32 {}
}

impl Trait  S {
    reuse to_reuse::foo { self }
    reuse to_reuse::foo;
    //~^ ERROR  duplicate definitions with name `foo`
}

fn main() { 0 }

````

Version information
````
rustc 1.81.0-nightly (52f3c71c8 2024-07-18)
binary: rustc
commit-hash: 52f3c71c8dc4aaed71e3035995fcbdd6d78c98c6
commit-date: 2024-07-18
host: x86_64-unknown-linux-gnu
release: 1.81.0-nightly
LLVM version: 18.1.7

````

Command:
`/home/matthias/.rustup/toolchains/master/bin/rustc `

<details><summary><strong>Program output</strong></summary>
<p>

```
error: missing `for` in a trait impl
  --> /tmp/icemaker_global_tempdir.n4JRPjMXSZEC/rustc_testrunner_tmpdir_reporting.Tsi6i8ZZpYcI/mvce.rs:17:11
   |
17 | impl Trait  S {
   |           ^^
   |
help: add `for` here
   |
17 | impl Trait for S {
   |            +++

error: `self` parameter is only allowed in associated functions
  --> /tmp/icemaker_global_tempdir.n4JRPjMXSZEC/rustc_testrunner_tmpdir_reporting.Tsi6i8ZZpYcI/mvce.rs:14:16
   |
14 |     pub fn foo(&self) -> u32 {}
   |                ^^^^^ not semantically valid as function parameter
   |
   = note: associated functions are those in `impl` or `trait` definitions

error[E0658]: functions delegation is not yet fully implemented
  --> /tmp/icemaker_global_tempdir.n4JRPjMXSZEC/rustc_testrunner_tmpdir_reporting.Tsi6i8ZZpYcI/mvce.rs:18:5
   |
18 |     reuse to_reuse::foo { self }
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: see issue #118212 <https://github.com/rust-lang/rust/issues/118212> for more information
   = help: add `#![feature(fn_delegation)]` to the crate attributes to enable
   = note: this compiler was built on 2024-07-18; consider upgrading it if it is out of date

error[E0601]: `main` function not found in crate `mvce`
  --> /tmp/icemaker_global_tempdir.n4JRPjMXSZEC/rustc_testrunner_tmpdir_reporting.Tsi6i8ZZpYcI/mvce.rs:21:2
   |
21 | }
   |  ^ consider adding a `main` function to `/tmp/icemaker_global_tempdir.n4JRPjMXSZEC/rustc_testrunner_tmpdir_reporting.Tsi6i8ZZpYcI/mvce.rs`

error[E0308]: mismatched types
  --> /tmp/icemaker_global_tempdir.n4JRPjMXSZEC/rustc_testrunner_tmpdir_reporting.Tsi6i8ZZpYcI/mvce.rs:14:26
   |
14 |     pub fn foo(&self) -> u32 {}
   |            ---           ^^^ expected `u32`, found `()`
   |            |
   |            implicitly returns `()` as its body has no tail or `return` expression

error: internal compiler error: compiler/rustc_ty_utils/src/assoc.rs:127:5: unexpected parent of trait or impl item or item not found: Mod(Mod { spans: ModSpans { inner_span: /tmp/icemaker_global_tempdir.n4JRPjMXSZEC/rustc_testrunner_tmpdir_reporting.Tsi6i8ZZpYcI/mvce.rs:14:5: 15:2 (#0), inject_use_span: /tmp/icemaker_global_tempdir.n4JRPjMXSZEC/rustc_testrunner_tmpdir_reporting.Tsi6i8ZZpYcI/mvce.rs:14:5: 14:5 (#0) }, item_ids: [ItemId { owner_id: DefId(0:10 ~ mvce[d169]::to_reuse::foo) }] })
  --> /tmp/icemaker_global_tempdir.n4JRPjMXSZEC/rustc_testrunner_tmpdir_reporting.Tsi6i8ZZpYcI/mvce.rs:11:1
   |
11 | / mod to_reuse {
12 | |     
13 | |
14 | |     pub fn foo(&self) -> u32 {}
15 | | }
   | |_^

thread 'rustc' panicked at compiler/rustc_ty_utils/src/assoc.rs:127:5:
Box<dyn Any>
stack backtrace:
   0:     0x7933ea2a13e5 - std::backtrace_rs::backtrace::libunwind::trace::hc272dcb5eaa8302d
                               at /rustc/52f3c71c8dc4aaed71e3035995fcbdd6d78c98c6/library/std/src/../../backtrace/src/backtrace/libunwind.rs:116:5
   1:     0x7933ea2a13e5 - std::backtrace_rs::backtrace::trace_unsynchronized::h691a0ef10f8dc9a8
                               at /rustc/52f3c71c8dc4aaed71e3035995fcbdd6d78c98c6/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7933ea2a13e5 - std::sys::backtrace::_print_fmt::ha47904fbec98bf60
                               at /rustc/52f3c71c8dc4aaed71e3035995fcbdd6d78c98c6/library/std/src/sys/backtrace.rs:65:5
   3:     0x7933ea2a13e5 - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::h0e7a639705968ce6
                               at /rustc/52f3c71c8dc4aaed71e3035995fcbdd6d78c98c6/library/std/src/sys/backtrace.rs:40:26
   4:     0x7933ea2f0e3b - core::fmt::rt::Argument::fmt::h4d320f08a40785a8
                               at /rustc/52f3c71c8dc4aaed71e3035995fcbdd6d78c98c6/library/core/src/fmt/rt.rs:173:76
   5:     0x7933ea2f0e3b - core::fmt::write::hd7ed7bd021505a5c
                               at /rustc/52f3c71c8dc4aaed71e3035995fcbdd6d78c98c6/library/core/src/fmt/mod.rs:1182:21
   6:     0x7933ea295f4f - std::io::Write::write_fmt::hd51bd05baef3855c
                               at /rustc/52f3c71c8dc4aaed71e3035995fcbdd6d78c98c6/library/std/src/io/mod.rs:1827:15
   7:     0x7933ea2a3bd1 - std::sys::backtrace::BacktraceLock::print::h680bd12acab7503d
                               at /rustc/52f3c71c8dc4aaed71e3035995fcbdd6d78c98c6/library/std/src/sys/backtrace.rs:43:9
   8:     0x7933ea2a3bd1 - std::panicking::default_hook::{{closure}}::h0ef49fd74d19887c
                               at /rustc/52f3c71c8dc4aaed71e3035995fcbdd6d78c98c6/library/std/src/panicking.rs:269:22
   9:     0x7933ea2a38ac - std::panicking::default_hook::h90696ad068a27ec2
                               at /rustc/52f3c71c8dc4aaed71e3035995fcbdd6d78c98c6/library/std/src/panicking.rs:296:9
  10:     0x7933e681c48a - std[3252865f4bda34c5]::panicking::update_hook::<alloc[da3b8f8ba9a896aa]::boxed::Box<rustc_driver_impl[f13dd90190e9dbe1]::install_ice_hook::{closure#0}>>::{closure#0}
  11:     0x7933ea2a459f - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::haab09738ddd9b211
                               at /rustc/52f3c71c8dc4aaed71e3035995fcbdd6d78c98c6/library/alloc/src/boxed.rs:2084:9
  12:     0x7933ea2a459f - std::panicking::rust_panic_with_hook::hffc45dfe647fb2c9
                               at /rustc/52f3c71c8dc4aaed71e3035995fcbdd6d78c98c6/library/std/src/panicking.rs:808:13
  13:     0x7933e68575b1 - std[3252865f4bda34c5]::panicking::begin_panic::<rustc_errors[67cfb45084a69b61]::ExplicitBug>::{closure#0}
  14:     0x7933e684a3b6 - std[3252865f4bda34c5]::sys::backtrace::__rust_end_short_backtrace::<std[3252865f4bda34c5]::panicking::begin_panic<rustc_errors[67cfb45084a69b61]::ExplicitBug>::{closure#0}, !>
  15:     0x7933e6845686 - std[3252865f4bda34c5]::panicking::begin_panic::<rustc_errors[67cfb45084a69b61]::ExplicitBug>
  16:     0x7933e6860a31 - <rustc_errors[67cfb45084a69b61]::diagnostic::BugAbort as rustc_errors[67cfb45084a69b61]::diagnostic::EmissionGuarantee>::emit_producing_guarantee
  17:     0x7933e75c821d - <rustc_errors[67cfb45084a69b61]::DiagCtxtHandle>::span_bug::<rustc_span[dacc065a687a0f9e]::span_encoding::Span, alloc[da3b8f8ba9a896aa]::string::String>
  18:     0x7933e75e4928 - rustc_middle[dd9bfa5285b6d2e6]::util::bug::opt_span_bug_fmt::<rustc_span[dacc065a687a0f9e]::span_encoding::Span>::{closure#0}
  19:     0x7933e75e495a - rustc_middle[dd9bfa5285b6d2e6]::ty::context::tls::with_opt::<rustc_middle[dd9bfa5285b6d2e6]::util::bug::opt_span_bug_fmt<rustc_span[dacc065a687a0f9e]::span_encoding::Span>::{closure#0}, !>::{closure#0}
  20:     0x7933e75d2a5b - rustc_middle[dd9bfa5285b6d2e6]::ty::context::tls::with_context_opt::<rustc_middle[dd9bfa5285b6d2e6]::ty::context::tls::with_opt<rustc_middle[dd9bfa5285b6d2e6]::util::bug::opt_span_bug_fmt<rustc_span[dacc065a687a0f9e]::span_encoding::Span>::{closure#0}, !>::{closure#0}, !>
  21:     0x7933e75d1d07 - rustc_middle[dd9bfa5285b6d2e6]::util::bug::span_bug_fmt::<rustc_span[dacc065a687a0f9e]::span_encoding::Span>
  22:     0x7933e92feb6d - rustc_query_impl[a7dfaff16252b164]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[a7dfaff16252b164]::query_impl::associated_item::dynamic_query::{closure#2}::{closure#0}, rustc_middle[dd9bfa5285b6d2e6]::query::erase::Erased<[u8; 40usize]>>.cold
  23:     0x7933e8108343 - rustc_query_system[d599853b3d31bcb6]::query::plumbing::try_execute_query::<rustc_query_impl[a7dfaff16252b164]::DynamicConfig<rustc_query_system[d599853b3d31bcb6]::query::caches::DefIdCache<rustc_middle[dd9bfa5285b6d2e6]::query::erase::Erased<[u8; 40usize]>>, false, false, false>, rustc_query_impl[a7dfaff16252b164]::plumbing::QueryCtxt, false>
  24:     0x7933e8108023 - rustc_query_impl[a7dfaff16252b164]::query_impl::associated_item::get_query_non_incr::__rust_end_short_backtrace
  25:     0x7933e6a2dab9 - rustc_middle[dd9bfa5285b6d2e6]::query::plumbing::query_get_at::<rustc_query_system[d599853b3d31bcb6]::query::caches::DefIdCache<rustc_middle[dd9bfa5285b6d2e6]::query::erase::Erased<[u8; 40usize]>>>
  26:     0x7933e474a69f - <rustc_hir_typeck[245a4534b1520086]::fn_ctxt::FnCtxt>::lookup_probe
  27:     0x7933e8888d17 - <rustc_hir_typeck[245a4534b1520086]::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
  28:     0x7933e8883023 - <rustc_hir_typeck[245a4534b1520086]::fn_ctxt::FnCtxt>::check_block_with_expected
  29:     0x7933e8888c0b - <rustc_hir_typeck[245a4534b1520086]::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
  30:     0x7933e865be15 - rustc_hir_typeck[245a4534b1520086]::check::check_fn
  31:     0x7933e8651783 - rustc_hir_typeck[245a4534b1520086]::typeck
  32:     0x7933e8651129 - rustc_query_impl[a7dfaff16252b164]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[a7dfaff16252b164]::query_impl::typeck::dynamic_query::{closure#2}::{closure#0}, rustc_middle[dd9bfa5285b6d2e6]::query::erase::Erased<[u8; 8usize]>>
  33:     0x7933e808c3f3 - rustc_query_system[d599853b3d31bcb6]::query::plumbing::try_execute_query::<rustc_query_impl[a7dfaff16252b164]::DynamicConfig<rustc_query_system[d599853b3d31bcb6]::query::caches::VecCache<rustc_span[dacc065a687a0f9e]::def_id::LocalDefId, rustc_middle[dd9bfa5285b6d2e6]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[a7dfaff16252b164]::plumbing::QueryCtxt, false>
  34:     0x7933e808b5cd - rustc_query_impl[a7dfaff16252b164]::query_impl::typeck::get_query_non_incr::__rust_end_short_backtrace
  35:     0x7933e808b1c4 - <rustc_middle[dd9bfa5285b6d2e6]::hir::map::Map>::par_body_owners::<rustc_hir_analysis[cb950f77af301e67]::check_crate::{closure#4}>::{closure#0}
  36:     0x7933e8088ffc - rustc_hir_analysis[cb950f77af301e67]::check_crate
  37:     0x7933e826f095 - rustc_interface[dbb229baa21df1c0]::passes::analysis
  38:     0x7933e826ec47 - rustc_query_impl[a7dfaff16252b164]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[a7dfaff16252b164]::query_impl::analysis::dynamic_query::{closure#2}::{closure#0}, rustc_middle[dd9bfa5285b6d2e6]::query::erase::Erased<[u8; 1usize]>>
  39:     0x7933e8cec225 - rustc_query_system[d599853b3d31bcb6]::query::plumbing::try_execute_query::<rustc_query_impl[a7dfaff16252b164]::DynamicConfig<rustc_query_system[d599853b3d31bcb6]::query::caches::SingleCache<rustc_middle[dd9bfa5285b6d2e6]::query::erase::Erased<[u8; 1usize]>>, false, false, false>, rustc_query_impl[a7dfaff16252b164]::plumbing::QueryCtxt, false>
  40:     0x7933e8cebf8f - rustc_query_impl[a7dfaff16252b164]::query_impl::analysis::get_query_non_incr::__rust_end_short_backtrace
  41:     0x7933e8c0a345 - rustc_interface[dbb229baa21df1c0]::interface::run_compiler::<core[67e71a49bc1f0e88]::result::Result<(), rustc_span[dacc065a687a0f9e]::ErrorGuaranteed>, rustc_driver_impl[f13dd90190e9dbe1]::run_compiler::{closure#0}>::{closure#1}
  42:     0x7933e8ba3189 - std[3252865f4bda34c5]::sys::backtrace::__rust_begin_short_backtrace::<rustc_interface[dbb229baa21df1c0]::util::run_in_thread_with_globals<rustc_interface[dbb229baa21df1c0]::util::run_in_thread_pool_with_globals<rustc_interface[dbb229baa21df1c0]::interface::run_compiler<core[67e71a49bc1f0e88]::result::Result<(), rustc_span[dacc065a687a0f9e]::ErrorGuaranteed>, rustc_driver_impl[f13dd90190e9dbe1]::run_compiler::{closure#0}>::{closure#1}, core[67e71a49bc1f0e88]::result::Result<(), rustc_span[dacc065a687a0f9e]::ErrorGuaranteed>>::{closure#0}, core[67e71a49bc1f0e88]::result::Result<(), rustc_span[dacc065a687a0f9e]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[67e71a49bc1f0e88]::result::Result<(), rustc_span[dacc065a687a0f9e]::ErrorGuaranteed>>
  43:     0x7933e8ba2f3a - <<std[3252865f4bda34c5]::thread::Builder>::spawn_unchecked_<rustc_interface[dbb229baa21df1c0]::util::run_in_thread_with_globals<rustc_interface[dbb229baa21df1c0]::util::run_in_thread_pool_with_globals<rustc_interface[dbb229baa21df1c0]::interface::run_compiler<core[67e71a49bc1f0e88]::result::Result<(), rustc_span[dacc065a687a0f9e]::ErrorGuaranteed>, rustc_driver_impl[f13dd90190e9dbe1]::run_compiler::{closure#0}>::{closure#1}, core[67e71a49bc1f0e88]::result::Result<(), rustc_span[dacc065a687a0f9e]::ErrorGuaranteed>>::{closure#0}, core[67e71a49bc1f0e88]::result::Result<(), rustc_span[dacc065a687a0f9e]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[67e71a49bc1f0e88]::result::Result<(), rustc_span[dacc065a687a0f9e]::ErrorGuaranteed>>::{closure#2} as core[67e71a49bc1f0e88]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  44:     0x7933ea2ae5fb - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h779e14e1cec4b93e
                               at /rustc/52f3c71c8dc4aaed71e3035995fcbdd6d78c98c6/library/alloc/src/boxed.rs:2070:9
  45:     0x7933ea2ae5fb - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h93db42a0f7517b09
                               at /rustc/52f3c71c8dc4aaed71e3035995fcbdd6d78c98c6/library/alloc/src/boxed.rs:2070:9
  46:     0x7933ea2ae5fb - std::sys::pal::unix::thread::Thread::new::thread_start::h450a1bf9a7dd864a
                               at /rustc/52f3c71c8dc4aaed71e3035995fcbdd6d78c98c6/library/std/src/sys/pal/unix/thread.rs:108:17
  47:     0x7933e32a6ded - <unknown>
  48:     0x7933e332a0dc - <unknown>
  49:                0x0 - <unknown>

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: please make sure that you have updated to the latest nightly

note: rustc 1.81.0-nightly (52f3c71c8 2024-07-18) running on x86_64-unknown-linux-gnu

query stack during panic:
#0 [associated_item] computing associated item data for `to_reuse::foo`
#1 [typeck] type-checking `<impl at /tmp/icemaker_global_tempdir.n4JRPjMXSZEC/rustc_testrunner_tmpdir_reporting.Tsi6i8ZZpYcI/mvce.rs:17:1: 17:14>::foo`
end of query stack
error: aborting due to 6 previous errors

Some errors have detailed explanations: E0308, E0601, E0658.
For more information about an error, try `rustc --explain E0308`.

```

</p>
</details>

@rustbot label +F-fn_delegation

### LINKED ISSUE #128119: ICE: delegation: index out of bounds
auto-reduced (treereduce-rust):
````rust
trait Trait {
    reuse to_reuse::foo { self }
}


struct S;

mod to_reuse {
    pub fn foo(&self) -> u32 {}
}

impl Trait  S {
    reuse to_reuse::foo { self }
}


````

original:
````rust
trait Trait {
    reuse to_reuse::foo { self }
}

struct Trait;
struct S;

mod to_reuse {
    pub fn foo(&self) -> u32 {}
}

impl Trait  S {
    reuse to_reuse::foo { self }
}

````

Version information
````
rustc 1.82.0-nightly (84c257ebe 2024-07-23)
binary: rustc
commit-hash: 84c257ebe5319ba68ce9a4ce5bca2d89e7127a14
commit-date: 2024-07-23
host: x86_64-unknown-linux-gnu
release: 1.82.0-nightly
LLVM version: 18.1.7

````

Command:
`/home/matthias/.rustup/toolchains/master/bin/rustc `

<details><summary><strong>Program output</strong></summary>
<p>

```
error: missing `for` in a trait impl
  --> /tmp/icemaker_global_tempdir.HWU1MVIGLwj9/rustc_testrunner_tmpdir_reporting.x2Si1gLufU2j/mvce.rs:12:11
   |
12 | impl Trait  S {
   |           ^^
   |
help: add `for` here
   |
12 | impl Trait for S {
   |            +++

error: `self` parameter is only allowed in associated functions
 --> /tmp/icemaker_global_tempdir.HWU1MVIGLwj9/rustc_testrunner_tmpdir_reporting.x2Si1gLufU2j/mvce.rs:9:16
  |
9 |     pub fn foo(&self) -> u32 {}
  |                ^^^^^ not semantically valid as function parameter
  |
  = note: associated functions are those in `impl` or `trait` definitions

error[E0658]: functions delegation is not yet fully implemented
 --> /tmp/icemaker_global_tempdir.HWU1MVIGLwj9/rustc_testrunner_tmpdir_reporting.x2Si1gLufU2j/mvce.rs:2:5
  |
2 |     reuse to_reuse::foo { self }
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: see issue #118212 <https://github.com/rust-lang/rust/issues/118212> for more information
  = help: add `#![feature(fn_delegation)]` to the crate attributes to enable
  = note: this compiler was built on 2024-07-23; consider upgrading it if it is out of date

error[E0658]: functions delegation is not yet fully implemented
  --> /tmp/icemaker_global_tempdir.HWU1MVIGLwj9/rustc_testrunner_tmpdir_reporting.x2Si1gLufU2j/mvce.rs:13:5
   |
13 |     reuse to_reuse::foo { self }
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: see issue #118212 <https://github.com/rust-lang/rust/issues/118212> for more information
   = help: add `#![feature(fn_delegation)]` to the crate attributes to enable
   = note: this compiler was built on 2024-07-23; consider upgrading it if it is out of date

thread 'rustc' panicked at compiler/rustc_ast_lowering/src/delegation.rs:334:59:
index out of bounds: the len is 0 but the index is 0
stack backtrace:
   0:     0x724bccc77215 - std::backtrace_rs::backtrace::libunwind::trace::h079c5b10617d341d
                               at /rustc/84c257ebe5319ba68ce9a4ce5bca2d89e7127a14/library/std/src/../../backtrace/src/backtrace/libunwind.rs:116:5
   1:     0x724bccc77215 - std::backtrace_rs::backtrace::trace_unsynchronized::hd7f004a4c1ba9b08
                               at /rustc/84c257ebe5319ba68ce9a4ce5bca2d89e7127a14/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x724bccc77215 - std::sys::backtrace::_print_fmt::hc9fcd7a583f53d0e
                               at /rustc/84c257ebe5319ba68ce9a4ce5bca2d89e7127a14/library/std/src/sys/backtrace.rs:68:9
   3:     0x724bccc77215 - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::h0fa110c20a9e6b9b
                               at /rustc/84c257ebe5319ba68ce9a4ce5bca2d89e7127a14/library/std/src/sys/backtrace.rs:41:26
   4:     0x724bcccc6c8b - core::fmt::rt::Argument::fmt::h2fa86b20e267917d
                               at /rustc/84c257ebe5319ba68ce9a4ce5bca2d89e7127a14/library/core/src/fmt/rt.rs:173:76
   5:     0x724bcccc6c8b - core::fmt::write::hc0abd2b87c9c9f9b
                               at /rustc/84c257ebe5319ba68ce9a4ce5bca2d89e7127a14/library/core/src/fmt/mod.rs:1182:21
   6:     0x724bccc6bcef - std::io::Write::write_fmt::h0eab51fe5cc04d2d
                               at /rustc/84c257ebe5319ba68ce9a4ce5bca2d89e7127a14/library/std/src/io/mod.rs:1827:15
   7:     0x724bccc79a01 - std::sys::backtrace::BacktraceLock::print::h73f7904e8c6470c5
                               at /rustc/84c257ebe5319ba68ce9a4ce5bca2d89e7127a14/library/std/src/sys/backtrace.rs:44:9
   8:     0x724bccc79a01 - std::panicking::default_hook::{{closure}}::h5772adf9111786bd
                               at /rustc/84c257ebe5319ba68ce9a4ce5bca2d89e7127a14/library/std/src/panicking.rs:269:22
   9:     0x724bccc796dc - std::panicking::default_hook::h96e37809c3d46f88
                               at /rustc/84c257ebe5319ba68ce9a4ce5bca2d89e7127a14/library/std/src/panicking.rs:296:9
  10:     0x724bc90255e9 - std[5c22d0894761bf95]::panicking::update_hook::<alloc[e548e83657ed7a36]::boxed::Box<rustc_driver_impl[e0a91da34026eb19]::install_ice_hook::{closure#0}>>::{closure#0}
  11:     0x724bccc7a3cf - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h20dc0ffe6bab5b1c
                               at /rustc/84c257ebe5319ba68ce9a4ce5bca2d89e7127a14/library/alloc/src/boxed.rs:2163:9
  12:     0x724bccc7a3cf - std::panicking::rust_panic_with_hook::h8e39c57c8213f108
                               at /rustc/84c257ebe5319ba68ce9a4ce5bca2d89e7127a14/library/std/src/panicking.rs:808:13
  13:     0x724bccc79ff7 - std::panicking::begin_panic_handler::{{closure}}::h3bced104df636721
                               at /rustc/84c257ebe5319ba68ce9a4ce5bca2d89e7127a14/library/std/src/panicking.rs:674:13
  14:     0x724bccc776d9 - std::sys::backtrace::__rust_end_short_backtrace::hd2ecf03e595ba397
                               at /rustc/84c257ebe5319ba68ce9a4ce5bca2d89e7127a14/library/std/src/sys/backtrace.rs:172:18
  15:     0x724bccc79c84 - rust_begin_unwind
                               at /rustc/84c257ebe5319ba68ce9a4ce5bca2d89e7127a14/library/std/src/panicking.rs:665:5
  16:     0x724bcccc3243 - core::panicking::panic_fmt::h035bf8637e3dbe4b
                               at /rustc/84c257ebe5319ba68ce9a4ce5bca2d89e7127a14/library/core/src/panicking.rs:74:14
  17:     0x724bcccc3437 - core::panicking::panic_bounds_check::h14e13ffb87f2f714
                               at /rustc/84c257ebe5319ba68ce9a4ce5bca2d89e7127a14/library/core/src/panicking.rs:276:5
  18:     0x724bc8c39e3f - <rustc_ast_lowering[7fcdca43ed366bd6]::LoweringContext>::lower_delegation
  19:     0x724bcacf1694 - <rustc_ast_lowering[7fcdca43ed366bd6]::LoweringContext>::lower_assoc_item
  20:     0x724bcace1006 - <rustc_ast_lowering[7fcdca43ed366bd6]::item::ItemLowerer>::lower_node
  21:     0x724bcacddd39 - rustc_ast_lowering[7fcdca43ed366bd6]::lower_to_hir
  22:     0x724bcb4eb020 - rustc_query_impl[1c27faad8f8c2359]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[1c27faad8f8c2359]::query_impl::hir_crate::dynamic_query::{closure#2}::{closure#0}, rustc_middle[d55bccc9e833afb]::query::erase::Erased<[u8; 8usize]>>
  23:     0x724bcb4e80c2 - rustc_query_system[e65aa676d33ec03e]::query::plumbing::try_execute_query::<rustc_query_impl[1c27faad8f8c2359]::DynamicConfig<rustc_query_system[e65aa676d33ec03e]::query::caches::SingleCache<rustc_middle[d55bccc9e833afb]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[1c27faad8f8c2359]::plumbing::QueryCtxt, false>
  24:     0x724bcb4e7d5e - rustc_query_impl[1c27faad8f8c2359]::query_impl::hir_crate::get_query_non_incr::__rust_end_short_backtrace
  25:     0x724bcae9f3a4 - rustc_query_impl[1c27faad8f8c2359]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[1c27faad8f8c2359]::query_impl::hir_attrs::dynamic_query::{closure#2}::{closure#0}, rustc_middle[d55bccc9e833afb]::query::erase::Erased<[u8; 8usize]>>
  26:     0x724bcae9e95f - rustc_query_system[e65aa676d33ec03e]::query::plumbing::try_execute_query::<rustc_query_impl[1c27faad8f8c2359]::DynamicConfig<rustc_query_system[e65aa676d33ec03e]::query::caches::VecCache<rustc_hir[b042a47ad172a40e]::hir_id::OwnerId, rustc_middle[d55bccc9e833afb]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[1c27faad8f8c2359]::plumbing::QueryCtxt, false>
  27:     0x724bcae9e6cf - rustc_query_impl[1c27faad8f8c2359]::query_impl::hir_attrs::get_query_non_incr::__rust_end_short_backtrace
  28:     0x724bca83cd86 - <rustc_middle[d55bccc9e833afb]::hir::map::Map>::attrs
  29:     0x724bcb5f13c1 - rustc_passes[87d8bc38134e89b]::entry::entry_fn
  30:     0x724bcb5f1358 - rustc_query_impl[1c27faad8f8c2359]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[1c27faad8f8c2359]::query_impl::entry_fn::dynamic_query::{closure#2}::{closure#0}, rustc_middle[d55bccc9e833afb]::query::erase::Erased<[u8; 12usize]>>
  31:     0x724bcb5f132f - <rustc_query_impl[1c27faad8f8c2359]::query_impl::entry_fn::dynamic_query::{closure#2} as core[b11752a00712c889]::ops::function::FnOnce<(rustc_middle[d55bccc9e833afb]::ty::context::TyCtxt, ())>>::call_once
  32:     0x724bcb5f0c48 - rustc_query_system[e65aa676d33ec03e]::query::plumbing::try_execute_query::<rustc_query_impl[1c27faad8f8c2359]::DynamicConfig<rustc_query_system[e65aa676d33ec03e]::query::caches::SingleCache<rustc_middle[d55bccc9e833afb]::query::erase::Erased<[u8; 12usize]>>, false, false, false>, rustc_query_impl[1c27faad8f8c2359]::plumbing::QueryCtxt, false>
  33:     0x724bcb5f09fd - rustc_query_impl[1c27faad8f8c2359]::query_impl::entry_fn::get_query_non_incr::__rust_end_short_backtrace
  34:     0x724bcae76132 - rustc_interface[ca1eba3031847acc]::passes::analysis
  35:     0x724bcae75f5b - rustc_query_impl[1c27faad8f8c2359]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[1c27faad8f8c2359]::query_impl::analysis::dynamic_query::{closure#2}::{closure#0}, rustc_middle[d55bccc9e833afb]::query::erase::Erased<[u8; 1usize]>>
  36:     0x724bcb4e94e5 - rustc_query_system[e65aa676d33ec03e]::query::plumbing::try_execute_query::<rustc_query_impl[1c27faad8f8c2359]::DynamicConfig<rustc_query_system[e65aa676d33ec03e]::query::caches::SingleCache<rustc_middle[d55bccc9e833afb]::query::erase::Erased<[u8; 1usize]>>, false, false, false>, rustc_query_impl[1c27faad8f8c2359]::plumbing::QueryCtxt, false>
  37:     0x724bcb4e924f - rustc_query_impl[1c27faad8f8c2359]::query_impl::analysis::get_query_non_incr::__rust_end_short_backtrace
  38:     0x724bcb3e2bc5 - rustc_interface[ca1eba3031847acc]::interface::run_compiler::<core[b11752a00712c889]::result::Result<(), rustc_span[5510ed7e96d6ad1b]::ErrorGuaranteed>, rustc_driver_impl[e0a91da34026eb19]::run_compiler::{closure#0}>::{closure#1}
  39:     0x724bcb3c8349 - std[5c22d0894761bf95]::sys::backtrace::__rust_begin_short_backtrace::<rustc_interface[ca1eba3031847acc]::util::run_in_thread_with_globals<rustc_interface[ca1eba3031847acc]::util::run_in_thread_pool_with_globals<rustc_interface[ca1eba3031847acc]::interface::run_compiler<core[b11752a00712c889]::result::Result<(), rustc_span[5510ed7e96d6ad1b]::ErrorGuaranteed>, rustc_driver_impl[e0a91da34026eb19]::run_compiler::{closure#0}>::{closure#1}, core[b11752a00712c889]::result::Result<(), rustc_span[5510ed7e96d6ad1b]::ErrorGuaranteed>>::{closure#0}, core[b11752a00712c889]::result::Result<(), rustc_span[5510ed7e96d6ad1b]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[b11752a00712c889]::result::Result<(), rustc_span[5510ed7e96d6ad1b]::ErrorGuaranteed>>
  40:     0x724bcb3c80fa - <<std[5c22d0894761bf95]::thread::Builder>::spawn_unchecked_<rustc_interface[ca1eba3031847acc]::util::run_in_thread_with_globals<rustc_interface[ca1eba3031847acc]::util::run_in_thread_pool_with_globals<rustc_interface[ca1eba3031847acc]::interface::run_compiler<core[b11752a00712c889]::result::Result<(), rustc_span[5510ed7e96d6ad1b]::ErrorGuaranteed>, rustc_driver_impl[e0a91da34026eb19]::run_compiler::{closure#0}>::{closure#1}, core[b11752a00712c889]::result::Result<(), rustc_span[5510ed7e96d6ad1b]::ErrorGuaranteed>>::{closure#0}, core[b11752a00712c889]::result::Result<(), rustc_span[5510ed7e96d6ad1b]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[b11752a00712c889]::result::Result<(), rustc_span[5510ed7e96d6ad1b]::ErrorGuaranteed>>::{closure#1} as core[b11752a00712c889]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  41:     0x724bccc8442b - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::ha48d6c8806b72121
                               at /rustc/84c257ebe5319ba68ce9a4ce5bca2d89e7127a14/library/alloc/src/boxed.rs:2149:9
  42:     0x724bccc8442b - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::heb92897a6cf54248
                               at /rustc/84c257ebe5319ba68ce9a4ce5bca2d89e7127a14/library/alloc/src/boxed.rs:2149:9
  43:     0x724bccc8442b - std::sys::pal::unix::thread::Thread::new::thread_start::hb52b315b33e9d801
                               at /rustc/84c257ebe5319ba68ce9a4ce5bca2d89e7127a14/library/std/src/sys/pal/unix/thread.rs:108:17
  44:     0x724bcca18ded - <unknown>
  45:     0x724bcca9c0dc - <unknown>
  46:                0x0 - <unknown>

error: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: please make sure that you have updated to the latest nightly

note: rustc 1.82.0-nightly (84c257ebe 2024-07-23) running on x86_64-unknown-linux-gnu

query stack during panic:
#0 [hir_crate] getting the crate HIR
#1 [hir_attrs] getting HIR owner attributes in ``
end of query stack
error: aborting due to 4 previous errors

For more information about this error, try `rustc --explain E0658`.

```

</p>
</details>

### LINKED ISSUE #128190: ICE: `expected item, found (root_crate)`
auto-reduced (treereduce-rust):
````rust
fn a(&self) {
    15
}

reuse a as b {  struct S; }


````

original:
````rust
#![rustc_dummy]
#![allow(as)]

fn a(&self) { 15 }

reuse a as b { #![feature(fn_delegation)] struct S; }

fn main(self) {
    const_fn();
    const_fn_extern();
}

````

Version information
````
rustc 1.82.0-nightly (54be9ad5e 2024-07-25)
binary: rustc
commit-hash: 54be9ad5eb47207d155904f6c912a9526133f75f
commit-date: 2024-07-25
host: x86_64-unknown-linux-gnu
release: 1.82.0-nightly
LLVM version: 18.1.7

````

Command:
`/home/matthias/.rustup/toolchains/master/bin/rustc `

<details><summary><strong>Program output</strong></summary>
<p>

```
error: `self` parameter is only allowed in associated functions
 --> /tmp/icemaker_global_tempdir.Xm44oviEaTg6/rustc_testrunner_tmpdir_reporting.4oFYSg3eBqPr/mvce.rs:1:6
  |
1 | fn a(&self) {
  |      ^^^^^ not semantically valid as function parameter
  |
  = note: associated functions are those in `impl` or `trait` definitions

error[E0658]: functions delegation is not yet fully implemented
 --> /tmp/icemaker_global_tempdir.Xm44oviEaTg6/rustc_testrunner_tmpdir_reporting.4oFYSg3eBqPr/mvce.rs:5:1
  |
5 | reuse a as b {  struct S; }
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: see issue #118212 <https://github.com/rust-lang/rust/issues/118212> for more information
  = help: add `#![feature(fn_delegation)]` to the crate attributes to enable
  = note: this compiler was built on 2024-07-25; consider upgrading it if it is out of date

error[E0601]: `main` function not found in crate `mvce`
 --> /tmp/icemaker_global_tempdir.Xm44oviEaTg6/rustc_testrunner_tmpdir_reporting.4oFYSg3eBqPr/mvce.rs:5:28
  |
5 | reuse a as b {  struct S; }
  |                            ^ consider adding a `main` function to `/tmp/icemaker_global_tempdir.Xm44oviEaTg6/rustc_testrunner_tmpdir_reporting.4oFYSg3eBqPr/mvce.rs`

error[E0308]: mismatched types
 --> /tmp/icemaker_global_tempdir.Xm44oviEaTg6/rustc_testrunner_tmpdir_reporting.4oFYSg3eBqPr/mvce.rs:2:5
  |
1 | fn a(&self) {
  |            - help: try adding a return type: `-> i32`
2 |     15
  |     ^^ expected `()`, found integer

error: internal compiler error: compiler/rustc_middle/src/hir/map/mod.rs:694:18: expected item, found (root_crate)

thread 'rustc' panicked at compiler/rustc_middle/src/hir/map/mod.rs:694:18:
Box<dyn Any>
stack backtrace:
   0:     0x7adb2a44a015 - std::backtrace_rs::backtrace::libunwind::trace::h40979b3cf07e4302
                               at /rustc/54be9ad5eb47207d155904f6c912a9526133f75f/library/std/src/../../backtrace/src/backtrace/libunwind.rs:116:5
   1:     0x7adb2a44a015 - std::backtrace_rs::backtrace::trace_unsynchronized::hc25be74c83b982ea
                               at /rustc/54be9ad5eb47207d155904f6c912a9526133f75f/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7adb2a44a015 - std::sys::backtrace::_print_fmt::he0e7b21c916cf37e
                               at /rustc/54be9ad5eb47207d155904f6c912a9526133f75f/library/std/src/sys/backtrace.rs:68:9
   3:     0x7adb2a44a015 - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::hdae9b4b38b07800f
                               at /rustc/54be9ad5eb47207d155904f6c912a9526133f75f/library/std/src/sys/backtrace.rs:41:26
   4:     0x7adb2a4999eb - core::fmt::rt::Argument::fmt::h23f55724cbf6fed3
                               at /rustc/54be9ad5eb47207d155904f6c912a9526133f75f/library/core/src/fmt/rt.rs:173:76
   5:     0x7adb2a4999eb - core::fmt::write::heb69bd2b65d4670c
                               at /rustc/54be9ad5eb47207d155904f6c912a9526133f75f/library/core/src/fmt/mod.rs:1182:21
   6:     0x7adb2a43e85f - std::io::Write::write_fmt::hb10e609dc145c64e
                               at /rustc/54be9ad5eb47207d155904f6c912a9526133f75f/library/std/src/io/mod.rs:1827:15
   7:     0x7adb2a44c801 - std::sys::backtrace::BacktraceLock::print::h151b0d7b810486c7
                               at /rustc/54be9ad5eb47207d155904f6c912a9526133f75f/library/std/src/sys/backtrace.rs:44:9
   8:     0x7adb2a44c801 - std::panicking::default_hook::{{closure}}::h6076738be33ec9e8
                               at /rustc/54be9ad5eb47207d155904f6c912a9526133f75f/library/std/src/panicking.rs:269:22
   9:     0x7adb2a44c4dc - std::panicking::default_hook::h304663758ec021ea
                               at /rustc/54be9ad5eb47207d155904f6c912a9526133f75f/library/std/src/panicking.rs:296:9
  10:     0x7adb268333da - std[f69981ba459e4be9]::panicking::update_hook::<alloc[5611d3b43b061168]::boxed::Box<rustc_driver_impl[a70ed56c5c805152]::install_ice_hook::{closure#0}>>::{closure#0}
  11:     0x7adb2a44d1cf - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h3898ed4990ae07d7
                               at /rustc/54be9ad5eb47207d155904f6c912a9526133f75f/library/alloc/src/boxed.rs:2163:9
  12:     0x7adb2a44d1cf - std::panicking::rust_panic_with_hook::hb301fa95c486ca11
                               at /rustc/54be9ad5eb47207d155904f6c912a9526133f75f/library/std/src/panicking.rs:808:13
  13:     0x7adb2686d981 - std[f69981ba459e4be9]::panicking::begin_panic::<rustc_errors[3ba03a0031862738]::ExplicitBug>::{closure#0}
  14:     0x7adb26860936 - std[f69981ba459e4be9]::sys::backtrace::__rust_end_short_backtrace::<std[f69981ba459e4be9]::panicking::begin_panic<rustc_errors[3ba03a0031862738]::ExplicitBug>::{closure#0}, !>
  15:     0x7adb268608e6 - std[f69981ba459e4be9]::panicking::begin_panic::<rustc_errors[3ba03a0031862738]::ExplicitBug>
  16:     0x7adb26876fc1 - <rustc_errors[3ba03a0031862738]::diagnostic::BugAbort as rustc_errors[3ba03a0031862738]::diagnostic::EmissionGuarantee>::emit_producing_guarantee
  17:     0x7adb26e21414 - rustc_middle[eb4fa39c1860cd4]::util::bug::opt_span_bug_fmt::<rustc_span[b68f95fc1bdef1eb]::span_encoding::Span>::{closure#0}
  18:     0x7adb26e0707a - rustc_middle[eb4fa39c1860cd4]::ty::context::tls::with_opt::<rustc_middle[eb4fa39c1860cd4]::util::bug::opt_span_bug_fmt<rustc_span[b68f95fc1bdef1eb]::span_encoding::Span>::{closure#0}, !>::{closure#0}
  19:     0x7adb26e06f1b - rustc_middle[eb4fa39c1860cd4]::ty::context::tls::with_context_opt::<rustc_middle[eb4fa39c1860cd4]::ty::context::tls::with_opt<rustc_middle[eb4fa39c1860cd4]::util::bug::opt_span_bug_fmt<rustc_span[b68f95fc1bdef1eb]::span_encoding::Span>::{closure#0}, !>::{closure#0}, !>
  20:     0x7adb24c0ce30 - rustc_middle[eb4fa39c1860cd4]::util::bug::bug_fmt
  21:     0x7adb2816e840 - <rustc_middle[eb4fa39c1860cd4]::hir::map::Map>::expect_item
  22:     0x7adb280fa8d7 - rustc_query_impl[abbe88964be750a7]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[abbe88964be750a7]::query_impl::associated_item::dynamic_query::{closure#2}::{closure#0}, rustc_middle[eb4fa39c1860cd4]::query::erase::Erased<[u8; 40usize]>>
  23:     0x7adb280f9bc2 - rustc_query_system[274de9dac1528dd3]::query::plumbing::try_execute_query::<rustc_query_impl[abbe88964be750a7]::DynamicConfig<rustc_query_system[274de9dac1528dd3]::query::caches::DefIdCache<rustc_middle[eb4fa39c1860cd4]::query::erase::Erased<[u8; 40usize]>>, false, false, false>, rustc_query_impl[abbe88964be750a7]::plumbing::QueryCtxt, false>
  24:     0x7adb280f98a3 - rustc_query_impl[abbe88964be750a7]::query_impl::associated_item::get_query_non_incr::__rust_end_short_backtrace
  25:     0x7adb26a4e47d - rustc_middle[eb4fa39c1860cd4]::query::plumbing::query_get_at::<rustc_query_system[274de9dac1528dd3]::query::caches::DefIdCache<rustc_middle[eb4fa39c1860cd4]::query::erase::Erased<[u8; 40usize]>>>
  26:     0x7adb24759446 - <rustc_hir_typeck[9ad8e17cc0d5c271]::fn_ctxt::FnCtxt>::lookup_probe
  27:     0x7adb28847e69 - <rustc_hir_typeck[9ad8e17cc0d5c271]::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
  28:     0x7adb288416f5 - <rustc_hir_typeck[9ad8e17cc0d5c271]::fn_ctxt::FnCtxt>::check_block_with_expected
  29:     0x7adb28847d5d - <rustc_hir_typeck[9ad8e17cc0d5c271]::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
  30:     0x7adb28062dcf - rustc_hir_typeck[9ad8e17cc0d5c271]::check::check_fn
  31:     0x7adb28059183 - rustc_hir_typeck[9ad8e17cc0d5c271]::typeck
  32:     0x7adb28058b29 - rustc_query_impl[abbe88964be750a7]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[abbe88964be750a7]::query_impl::typeck::dynamic_query::{closure#2}::{closure#0}, rustc_middle[eb4fa39c1860cd4]::query::erase::Erased<[u8; 8usize]>>
  33:     0x7adb2806c2f3 - rustc_query_system[274de9dac1528dd3]::query::plumbing::try_execute_query::<rustc_query_impl[abbe88964be750a7]::DynamicConfig<rustc_query_system[274de9dac1528dd3]::query::caches::VecCache<rustc_span[b68f95fc1bdef1eb]::def_id::LocalDefId, rustc_middle[eb4fa39c1860cd4]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[abbe88964be750a7]::plumbing::QueryCtxt, false>
  34:     0x7adb2806b4cd - rustc_query_impl[abbe88964be750a7]::query_impl::typeck::get_query_non_incr::__rust_end_short_backtrace
  35:     0x7adb2806b0c4 - <rustc_middle[eb4fa39c1860cd4]::hir::map::Map>::par_body_owners::<rustc_hir_analysis[40d7e38617de2bd]::check_crate::{closure#4}>::{closure#0}
  36:     0x7adb28068efc - rustc_hir_analysis[40d7e38617de2bd]::check_crate
  37:     0x7adb28a2a815 - rustc_interface[73e2d76034883eaa]::passes::analysis
  38:     0x7adb28a2a3db - rustc_query_impl[abbe88964be750a7]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[abbe88964be750a7]::query_impl::analysis::dynamic_query::{closure#2}::{closure#0}, rustc_middle[eb4fa39c1860cd4]::query::erase::Erased<[u8; 1usize]>>
  39:     0x7adb28c5f8a5 - rustc_query_system[274de9dac1528dd3]::query::plumbing::try_execute_query::<rustc_query_impl[abbe88964be750a7]::DynamicConfig<rustc_query_system[274de9dac1528dd3]::query::caches::SingleCache<rustc_middle[eb4fa39c1860cd4]::query::erase::Erased<[u8; 1usize]>>, false, false, false>, rustc_query_impl[abbe88964be750a7]::plumbing::QueryCtxt, false>
  40:     0x7adb28c5f60f - rustc_query_impl[abbe88964be750a7]::query_impl::analysis::get_query_non_incr::__rust_end_short_backtrace
  41:     0x7adb28b5e185 - rustc_interface[73e2d76034883eaa]::interface::run_compiler::<core[4b0752be9b74dadf]::result::Result<(), rustc_span[b68f95fc1bdef1eb]::ErrorGuaranteed>, rustc_driver_impl[a70ed56c5c805152]::run_compiler::{closure#0}>::{closure#1}
  42:     0x7adb28b44689 - std[f69981ba459e4be9]::sys::backtrace::__rust_begin_short_backtrace::<rustc_interface[73e2d76034883eaa]::util::run_in_thread_with_globals<rustc_interface[73e2d76034883eaa]::util::run_in_thread_pool_with_globals<rustc_interface[73e2d76034883eaa]::interface::run_compiler<core[4b0752be9b74dadf]::result::Result<(), rustc_span[b68f95fc1bdef1eb]::ErrorGuaranteed>, rustc_driver_impl[a70ed56c5c805152]::run_compiler::{closure#0}>::{closure#1}, core[4b0752be9b74dadf]::result::Result<(), rustc_span[b68f95fc1bdef1eb]::ErrorGuaranteed>>::{closure#0}, core[4b0752be9b74dadf]::result::Result<(), rustc_span[b68f95fc1bdef1eb]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[4b0752be9b74dadf]::result::Result<(), rustc_span[b68f95fc1bdef1eb]::ErrorGuaranteed>>
  43:     0x7adb28b4443a - <<std[f69981ba459e4be9]::thread::Builder>::spawn_unchecked_<rustc_interface[73e2d76034883eaa]::util::run_in_thread_with_globals<rustc_interface[73e2d76034883eaa]::util::run_in_thread_pool_with_globals<rustc_interface[73e2d76034883eaa]::interface::run_compiler<core[4b0752be9b74dadf]::result::Result<(), rustc_span[b68f95fc1bdef1eb]::ErrorGuaranteed>, rustc_driver_impl[a70ed56c5c805152]::run_compiler::{closure#0}>::{closure#1}, core[4b0752be9b74dadf]::result::Result<(), rustc_span[b68f95fc1bdef1eb]::ErrorGuaranteed>>::{closure#0}, core[4b0752be9b74dadf]::result::Result<(), rustc_span[b68f95fc1bdef1eb]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[4b0752be9b74dadf]::result::Result<(), rustc_span[b68f95fc1bdef1eb]::ErrorGuaranteed>>::{closure#1} as core[4b0752be9b74dadf]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  44:     0x7adb2a45711b - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h00bda9a3a6915a28
                               at /rustc/54be9ad5eb47207d155904f6c912a9526133f75f/library/alloc/src/boxed.rs:2149:9
  45:     0x7adb2a45711b - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h3ee855f42fb95cb5
                               at /rustc/54be9ad5eb47207d155904f6c912a9526133f75f/library/alloc/src/boxed.rs:2149:9
  46:     0x7adb2a45711b - std::sys::pal::unix::thread::Thread::new::thread_start::h31514268db3ccba4
                               at /rustc/54be9ad5eb47207d155904f6c912a9526133f75f/library/std/src/sys/pal/unix/thread.rs:108:17
  47:     0x7adb2a1eaded - <unknown>
  48:     0x7adb2a26e0dc - <unknown>
  49:                0x0 - <unknown>

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: please make sure that you have updated to the latest nightly

note: rustc 1.82.0-nightly (54be9ad5e 2024-07-25) running on x86_64-unknown-linux-gnu

query stack during panic:
#0 [associated_item] computing associated item data for `a`
#1 [typeck] type-checking `b`
end of query stack
error: aborting due to 5 previous errors

Some errors have detailed explanations: E0308, E0601, E0658.
For more information about an error, try `rustc --explain E0308`.

```

</p>
</details>

@rustbot label +F-fn_delegation

### PR DESCRIPTION
**Pull request by Bryanskiy**
`ExprKind::MethodCall` is now generated instead of `ExprKind::Call` if 
- the resolved function has a `&self` argument
- the resolved function is an associated item <- was missed before

Fixes https://github.com/rust-lang/rust/issues/128190
Fixes https://github.com/rust-lang/rust/issues/128119
Fixes https://github.com/rust-lang/rust/issues/127916

r? @petrochenkov

### CODE REVIEW

File: compiler/rustc_ast_lowering/src/delegation.rs [hunk 1]
```diff
@@ -324,7 +334,7 @@ impl<'hir> LoweringContext<'_, 'hir> {
 
         let call = if self
             .get_resolution_id(delegation.id, span)
-            .and_then(|def_id| Ok(self.has_self(def_id, span)))
+            .and_then(|def_id| Ok(self.has_self(def_id, span) && self.is_assoc_fn(def_id)))
```
Comment (petrochenkov) [inline compiler/rustc_ast_lowering/src/delegation.rs:337]: It's better to fix this inside `fn has_self` itself, by checking `def_kind`, it will work on local `DefId`s too.

Comment (Bryanskiy) [reply compiler/rustc_ast_lowering/src/delegation.rs]: Done. I have also renamed "has_self" to "is_method". Terminology for "method" came from [this](https://github.com/rust-lang/rfcs/pull/3530#discussion_r1411176926) conversation.
