### PR TITLE
Fix index out of bounds ICE in `point_at_expr_source_of_inferred_type`

### LINKED ISSUE #108042: ICE in type inference? type checking? on broken/wrong BTreeMap code, if inserting into BTreeMap
Ran into an ICE while refactoring. Only happens on nightly. Don't know what else I should write here.

### Code

```Rust
extern crate alloc;
use alloc::collections::BTreeMap;

struct Struct {
    map : BTreeMap<String, String>,
}

fn main() {
    let mut map = BTreeMap::new(); // ICE
    //let mut map = BTreeMap::<(String, String), String>::new(); // ICE
    //let mut map = BTreeMap::<String, String>::new(); // no ICE
    map.insert(("a".to_string(), "a".to_string()));
    let mut structdef = Struct { map };
}
```

### Meta

`rustc --version --verbose`:
```
$ rustc --version --verbose
rustc 1.67.1 (d5a82bbd2 2023-02-07)
binary: rustc
commit-hash: d5a82bbd26e1ad8b7401f6a718a9c57c96905483
commit-date: 2023-02-07
host: x86_64-pc-windows-gnu
release: 1.67.1
LLVM version: 15.0.6

$ rustc +nightly --version --verbose
rustc 1.69.0-nightly (065852def 2023-02-13)
binary: rustc
commit-hash: 065852def0903296da33a9eaf557f230bcf3a61a
commit-date: 2023-02-13
host: x86_64-pc-windows-msvc
release: 1.69.0-nightly
LLVM version: 15.0.7
```

### Error output

```
$ rustc +nightly test.rs
error[E0061]: this method takes 2 arguments but 1 argument was supplied
  --> test.rs:12:9
   |
12 |     map.insert(("a".to_string(), "a".to_string()));
   |         ^^^^^^------------------------------------ an argument is missing
   |
note: associated function defined here
  --> /rustc/065852def0903296da33a9eaf557f230bcf3a61a\library\alloc\src\collections\btree\map.rs:955:12
help: provide the argument
   |
12 |     map.insert(("a".to_string(), "a".to_string()), /* value */);
   |               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

thread 'rustc' panicked at 'index out of bounds: the len is 1 but the index is 1', compiler\rustc_hir_typeck\src\demand.rs:332:40
<backtrace omitted, see below>

error: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.69.0-nightly (065852def 2023-02-13) running on x86_64-pc-windows-msvc

query stack during panic:
#0 [typeck] type-checking `main`
#1 [typeck_item_bodies] type-checking all item bodies
#2 [analysis] running analysis passes on this crate
end of query stack
error: aborting due to previous error

For more information about this error, try `rustc --explain E0061`.
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
stack backtrace:
   0:     0x7ffcfd6698a2 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h78e89e9946a237ab
   1:     0x7ffcfd6a532b - core::fmt::write::hb0cb1c9de7a39696
   2:     0x7ffcfd65c88a - <std::io::IoSliceMut as core::fmt::Debug>::fmt::h2d13ae8023f6410a
   3:     0x7ffcfd6695eb - std::sys::common::alloc::realloc_fallback::h95ea3faf57f4bab2
   4:     0x7ffcfd66cf89 - std::panicking::default_hook::h031c528ccf47d428
   5:     0x7ffcfd66cc0b - std::panicking::default_hook::h031c528ccf47d428
   6:     0x7ffce4ac00ef - rustc_driver_impl[e542371b9e5deca1]::describe_lints
   7:     0x7ffcfd66d8ef - std::panicking::rust_panic_with_hook::h2bf5e2387af40df5
   8:     0x7ffcfd66d64e - <std::panicking::begin_panic_handler::StrPanicPayload as core::panic::BoxMeUp>::get::h3fc7e7bd4173a984
   9:     0x7ffcfd66a59f - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h78e89e9946a237ab
  10:     0x7ffcfd66d300 - rust_begin_unwind
  11:     0x7ffcfd6d8a05 - core::panicking::panic_fmt::h3223cb95b63b2d59
  12:     0x7ffcfd6d8b97 - core::panicking::panic_bounds_check::hfedaf1b227ea46ee
  13:     0x7ffce4c547f3 - <rustc_hir_typeck[96d41babe8f90f07]::fn_ctxt::FnCtxt>::point_at_expr_source_of_inferred_type
  14:     0x7ffce4c50e1c - <rustc_hir_typeck[96d41babe8f90f07]::fn_ctxt::FnCtxt>::emit_type_mismatch_suggestions
  15:     0x7ffce4c51afc - <rustc_hir_typeck[96d41babe8f90f07]::fn_ctxt::FnCtxt>::emit_coerce_suggestions
  16:     0x7ffce2fcb5b6 - <rustc_hir_typeck[96d41babe8f90f07]::fn_ctxt::FnCtxt>::demand_coerce_diag
  17:     0x7ffce2f7c940 - <rustc_hir_typeck[96d41babe8f90f07]::fn_ctxt::FnCtxt>::demand_coerce
  18:     0x7ffce2f5aafc - <rustc_hir_typeck[96d41babe8f90f07]::fn_ctxt::FnCtxt>::demand_coerce
  19:     0x7ffce2fafc7d - <rustc_hir_typeck[96d41babe8f90f07]::fn_ctxt::FnCtxt>::check_struct_path
  20:     0x7ffce2fb11d8 - <rustc_hir_typeck[96d41babe8f90f07]::fn_ctxt::FnCtxt>::check_struct_path
  21:     0x7ffce2f587c3 - <rustc_hir_typeck[96d41babe8f90f07]::fn_ctxt::FnCtxt>::demand_coerce
  22:     0x7ffce2f7a4ed - <rustc_hir_typeck[96d41babe8f90f07]::fn_ctxt::FnCtxt>::demand_coerce
  23:     0x7ffce30505b1 - <rustc_hir_typeck[96d41babe8f90f07]::method::probe::Pick>::maybe_emit_unstable_name_collision_hint
  24:     0x7ffce305f529 - <rustc_hir_typeck[96d41babe8f90f07]::inherited::Inherited as core[7f56be9053635011]::ops::deref::Deref>::deref
  25:     0x7ffce3748913 - <rustc_middle[9cf1323aa3ef55]::ty::Visibility as rustc_privacy[4607b2c41700df30]::VisibilityLike>::new_min
  26:     0x7ffce2fffcb6 - <rustc_hir_typeck[96d41babe8f90f07]::writeback::WritebackCx as rustc_hir[cc46961c34403ead]::intravisit::Visitor>::visit_ty
  27:     0x7ffce1dba42f - <rustc_hir_typeck[96d41babe8f90f07]::inherited::Inherited>::build
  28:     0x7ffce20c3aec - rustc_privacy[4607b2c41700df30]::provide
  29:     0x7ffce21bc172 - <rustc_query_impl[83d2b7f35e45599c]::Queries as rustc_middle[9cf1323aa3ef55]::ty::query::QueryEngine>::try_mark_green
  30:     0x7ffce1d27245 - <rustc_hir_analysis[4c58ae939ed73dca]::bounds::Bounds>::push_projection_bound
  31:     0x7ffce1d027f3 - rustc_hir_analysis[4c58ae939ed73dca]::check_crate
  32:     0x7ffce1e18160 - rustc_interface[71bf077bc0e4ea2b]::passes::analysis
  33:     0x7ffce216273d - rustc_privacy[4607b2c41700df30]::provide
  34:     0x7ffce21b963f - <rustc_query_impl[83d2b7f35e45599c]::Queries as rustc_middle[9cf1323aa3ef55]::ty::query::QueryEngine>::try_mark_green
  35:     0x7ffce1c3d27c - rustc_driver_impl[e542371b9e5deca1]::args::arg_expand_all
  36:     0x7ffce1c3b443 - rustc_driver_impl[e542371b9e5deca1]::args::arg_expand_all
  37:     0x7ffce1c3a627 - rustc_driver_impl[e542371b9e5deca1]::args::arg_expand_all
  38:     0x7ffce1c284d3 - <rustc_data_structures[72e258867a716a8c]::temp_dir::MaybeTempDir>::new
  39:     0x7ffce1c20cbd - <rustc_data_structures[72e258867a716a8c]::temp_dir::MaybeTempDir>::new
  40:     0x7ffcfd67fefc - std::sys::windows::thread::Thread::new::hcd7eb12de5a8a905
  41:     0x7ffd76fb7614 - BaseThreadInitThunk
  42:     0x7ffd791226a1 - RtlUserThreadStart
```

</p>
</details>

### PR DESCRIPTION
**Pull request by martingms**
There might be more type params than args to a method call, which leads to an index out of bounds panic.
I'm not familiar with this code at all, so unsure whether this is the right fix, but at least this patch fixes #108042 for me (I hit the same issue with similar code)

### CODE REVIEW

**Comment by compiler-errors** [comment]
This needs a UI test

r? @compiler-errors

File: compiler/rustc_hir_typeck/src/demand.rs [hunk 1]
```diff
@@ -323,13 +323,12 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
                 let mut param_found = FxHashMap::default();
                 if self.can_eq(self.param_env, ty, found).is_ok() {
                     // We only point at the first place where the found type was inferred.
-                    for (i, param_ty) in sig.inputs().skip_binder().iter().skip(1).enumerate() {
+                    for (param_ty, arg) in sig.inputs().skip_binder().iter().skip(1).zip(args) {
```
Comment (compiler-errors) [inline compiler/rustc_hir_typeck/src/demand.rs:326]: Alternatively, we can just bail here if there is a argument arity mismatch. If there isn't the right # of arguments, there's probably no good reason to point at args as the source for a bad inference.

Comment (compiler-errors) [reply compiler/rustc_hir_typeck/src/demand.rs:326]: Zipping here rather than indexing into `args` is nice regardless, we just might want to do this arity check regardless.

Comment (martingms) [reply compiler/rustc_hir_typeck/src/demand.rs:326]: Hm, in the example in the issue (#108042) the `.insert(..)` call has the wrong number of args but seems to still be the source of the inference? Or am I reading this wrong?

Current `rustc` output with the `.zip()` patch:

```
error[E0061]: this method takes 2 arguments but 1 argument was supplied
   --> p.rs:12:9
    |
12  |     map.insert(("a".to_string(), "a".to_string()));
    |         ^^^^^^------------------------------------ an argument is missing
    |
note: associated function defined here
   --> /home/mg/dev/rust/library/alloc/src/collections/btree/map.rs:955:12
    |
955 |     pub fn insert(&mut self, key: K, value: V) -> Option<V>
    |            ^^^^^^
help: provide the argument
    |
12  |     map.insert(("a".to_string(), "a".to_string()), /* value */);
    |               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

error[E0308]: mismatched types
  --> p.rs:13:34
   |
13 |     let mut structdef = Struct { map };
   |                                  ^^^ expected `BTreeMap<String, String>`, found `BTreeMap<(String, String), _>`
   |
   = note: expected struct `BTreeMap<String, String>`
              found struct `BTreeMap<(String, String), _>`

error: aborting due to 2 previous errors

Some errors have detailed explanations: E0061, E0308.
For more information about an error, try `rustc --explain E0061`.
``

**Comment by martingms** [comment]
> This needs a UI test

Cool, might as well learn how to write one of those I guess! What's the expected output in a arity mismatch case then?

File: compiler/rustc_hir_typeck/src/demand.rs (hunk 1 above)
Comment (martingms) [reply compiler/rustc_hir_typeck/src/demand.rs:326]: I added (in 0be53945) a first stab at a UI test that shows what I mean, I think.

File: tests/ui/type/type-check/point-at-inference-4.rs [hunk 2]
```diff
@@ -0,0 +1,24 @@
+struct S<A, B>(Option<(A,B)>);
+
+impl<A, B> S<A, B> {
+    fn infer(&self, a: A, b: B) {}
+    //~^ NOTE associated function defined here
+    //~| NOTE
+    //~| NOTE
```
Comment (martingms) [inline tests/ui/type/type-check/point-at-inference-4.rs:7]: I've never made one of these before so I kinda just threw stuff at it until it passed. Are these really needed?

File: tests/ui/type/type-check/point-at-inference-4.rs [hunk 3]
```diff
@@ -0,0 +1,23 @@
...
+}
+
+fn main() {
+    let s = S(None);
+    s.infer(0i32);
+    //~^ ERROR this method takes 2 arguments but 1 argument was supplied
+    //~| NOTE an argument is missing
+    //~| HELP provide the argument
+    //~| NOTE this is of type `i32`, which causes `s` to be inferred as `S<i32, _>`
```
Comment (martingms) [inline tests/ui/type/type-check/point-at-inference-4.rs:16]: This shows that this works even on arity mismatch, I think?

File: compiler/rustc_hir_typeck/src/demand.rs (hunk 1 above)
Comment (compiler-errors) [reply compiler/rustc_hir_typeck/src/demand.rs:326]: Sure, but the inference is influenced in an incorrect way -- it's not super useful to point out this as the place where the inference is occurs when we have the other error E0061.

File: tests/ui/type/type-check/point-at-inference-4.rs (hunk 2 above)
Comment (compiler-errors) [reply tests/ui/type/type-check/point-at-inference-4.rs:7]: Yeah, I think so.

File: tests/ui/type/type-check/point-at-inference-4.rs (hunk 3 above)
Comment (martingms) [reply tests/ui/type/type-check/point-at-inference-4.rs]: Right, makes sense. Arity-checking it is then.

**Comment by est31** [comment]
The ICE is reproducible on beta, it would be nice to have this PR backported so that stable users won't be hitting #108042. 

@rustbot label +beta-nominated

**Comment by apiraino** [comment]
Beta backport approved as per compiler team [on Zulip](https://rust-lang.zulipchat.com/#narrow/stream/238009-t-compiler.2Fmeetings/topic/.5Bweekly.5D.202023-02-23/near/329743291)

@rustbot label +beta-accepted

**Comment by cuviper** [comment]
We decided to revert on beta instead of backporting: #108703

@rustbot label: -beta-accepted
