### PR TITLE
Fix promotion in a `const` when projections are present

### LINKED ISSUE #65727: Incorrect promotion for projection in a `const`
Consider the following code:

[Playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=cb3b84e62b1979a8aa4bae9e0d71e826)
```rust
const _: &i32 = {
    let x = &(5, false).0;
    x
};

fn main() {
    let _: &'static i32 = &(5, false).0;
}
```

The borrow of the tuple field in `main` is promoted out along with the tuple itself in accordance with the rules for rvalue static promotion. However, in the `const`, the mechanism for promotion does not remove `Drop`/`StorageDead` for the tuple, causing `x` to dangle. On stable, this is only caught during const-evaluation and results in a `const_err` warning. If this warning is supressed, an ICE occurs.

```
error: internal compiler error: tried to intern dangling pointer
 --> src/main.rs:2:1
  |
2 | / const _: &i32 = {
3 | |     let x = &(5, false).0;
4 | |     x
5 | | };
  | |__^

thread 'rustc' panicked at 'no errors encountered even though `delay_span_bug` issued', src/librustc_errors/lib.rs:361:17
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

On nightly, the MIR borrow checker prevents this from happening, and this code is rejected instead. It should be accepted in all contexts.

### PR DESCRIPTION
**Pull request by ecstatic-morse**
Resolves #65727.

This marks the entire local as "needs promotion" when only a projection of that local appears in a promotable context. This should only affect promotion in a `const` or `static`, not in a `fn` or `const fn`, which is handled in `promote_consts.rs`.

r? @eddyb

### CODE REVIEW

File: src/librustc_mir/transform/qualify_consts.rs [hunk 1]
```diff
@@ -1038,32 +1038,28 @@ impl<'a, 'tcx> Checker<'a, 'tcx> {
 
         debug!("qualify_const: promotion_candidates={:?}", self.promotion_candidates);
         for candidate in &self.promotion_candidates {
-            match *candidate {
+            let promoted_place = match *candidate {
                 Candidate::Repeat(Location { block: bb, statement_index: stmt_idx }) => {
```
Comment (eddyb) [inline src/librustc_mir/transform/qualify_consts.rs]: It's a bug that this applies to `Repeat`. There is no way to make `Repeat` work by removing `StorageDead`.

File: src/librustc_mir/transform/qualify_consts.rs [hunk 2]
```diff
@@ -1038,32 +1038,28 @@ impl<'a, 'tcx> Checker<'a, 'tcx> {
...
+                        StatementKind::Assign(box( _, Rvalue::Ref(_, _, place))) => place,
+                        _ => continue,
                     }
                 }
-                Candidate::Argument { .. } => {}
+                Candidate::Argument { .. } => continue,
+            };
+
+            match promoted_place.base {
+                PlaceBase::Local(local) if !promoted_place.is_indirect() => {
```
Comment (eddyb) [inline src/librustc_mir/transform/qualify_consts.rs]: The "indirect" thing is irrelevant AFAIK, all you care about is the base.

File: src/librustc_mir/transform/qualify_consts.rs (hunk 1 above)
Comment (ecstatic-morse) [reply src/librustc_mir/transform/qualify_consts.rs]: So we should treat `Repeat` like `Argument` here and do nothing right?

File: src/librustc_mir/transform/qualify_consts.rs (hunk 2 above)
Comment (ecstatic-morse) [reply src/librustc_mir/transform/qualify_consts.rs]: I guess we never promote the result of a deref projection, so that guard will never take effect. I could make this a `bug` or just remove it.

Comment (ecstatic-morse) [reply src/librustc_mir/transform/qualify_consts.rs]: I've made this an `assert` for now so it will fail loudly on the test suite if my assumptions are wrong. Probably want to make this a `debug_assert` or remove it entirely before merging.

File: src/librustc_mir/transform/qualify_consts.rs (hunk 1 above)
Comment (eddyb) [reply src/librustc_mir/transform/qualify_consts.rs]: That sounds correct.

File: src/librustc_mir/transform/qualify_consts.rs (hunk 2 above)
Comment (eddyb) [reply src/librustc_mir/transform/qualify_consts.rs]: You can just remove it IMO. We *really* need to stop using "delete `StorageDead`" for faux promotion, I dislike it more by the minute.

Comment (ecstatic-morse) [reply src/librustc_mir/transform/qualify_consts.rs]: The assertion has been removed in the latest force push.

**Comment by JohnCSimon** [comment]
Ping from triage - the PR has sat idle for a week - 
@ecstatic-morse can you please address the merge conflict ? 
Also: once the that's resolved @eddyb can you please review this PR?

thanks.

**Review by eddyb — APPROVED** [review]
