### PR TITLE
fix(lints): Improve `ill_formed_attribute_input` with better help message

### LINKED ISSUE #154667: `#[ignore(lint_name)]` errors should suggest using `#[allow(lint_name)]` instead
### Code

```Rust
#![ignore(clippy::single_match)]
```

### Current output

```text
error: valid forms for the attribute are `#![ignore = "reason"]` and `#![ignore]`
 --> src/lib.rs:1:1
  |
1 | #![ignore(clippy::single_match)]
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = warning: this was previously accepted by the compiler but is being phased out; it will become a hard error in a future release!
  = note: for more information, see issue #57571 <https://github.com/rust-lang/rust/issues/57571>
  = note: `#[deny(ill_formed_attribute_input)]` (part of `#[deny(future_incompatible)]`) on by default
```

### Desired output

```text
help: if you meant to silence a warning, consider `#![allow(clippy::single_match)]` or `#![expect(clippy::single_match)]`
```

### Rationale and extra context

Recently I mixed up the name of the attribute used to silence warnings, and accidentally wrote `#[ignore(..)]` instead of `#[allow(..)]`.

The compiler was right to reject my program, but I was briefly confused by why it wasn't working, because the error message doesn't give any indication of what the `ignore` attribute is for. That made it harder for me to correct my misunderstanding.

### Other cases

```Rust

```

### Rust Version

```Shell
$ rustc --version --verbose
rustc 1.94.0 (4a4ef493e 2026-03-02)
binary: rustc
commit-hash: 4a4ef493e3a1488c6e321570238084b38948f6db
commit-date: 2026-03-02
host: aarch64-apple-darwin
release: 1.94.0
LLVM version: 21.1.8
```

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by JayanAXHF**
*[View all comments](https://triagebot.infra.rust-lang.org/gh-comments/rust-lang/rust/pull/154722)*

Add a better help message to `ill_formed_attribute_input` for the cases where it matches the usage of `#![allow]`. 

For further details see rust-lang/rust#154667

closes rust-lang/rust#154667 

cc: @Zalathar

### CODE REVIEW

**Review by jdonszelmann — APPROVED** [review]
@bors r+ rollup

*[View changes since this review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/rust/154722/e6b64a2f4c696b840f8a384ec28690eed6a5d267..94b88740d18d104a84b42a395c4f6844bbcecf69)*

File: compiler/rustc_attr_parsing/src/attributes/test_attrs.rs [hunk 1]
```diff
@@ -27,8 +27,15 @@ impl<S: Stage> SingleAttributeParser<S> for IgnoreParser {
                     };
                     Some(str_value)
                 }
-                ArgParser::List(_) => {
-                    cx.adcx().warn_ill_formed_attribute_input(ILL_FORMED_ATTRIBUTE_INPUT);
+                ArgParser::List(list) => {
+                    let help = list.single().and_then(|item| item.meta_item()).and_then(|item| {
```
Comment (jdonszelmann) [inline compiler/rustc_attr_parsing/src/attributes/test_attrs.rs:31]: @scrabsha

**Review by jdonszelmann — COMMENTED** [review]
@bors r+

*[View changes since this review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/rust/154722/f92020a676251cf985cbe5134a1fd976b5207ab6..65b88ea8ee499345aa8414f16d6cf018c6bdaed6)*
