### PR TITLE
Fix old docs

### LINKED ISSUE #41158: Trailing `+` in bounds are allowed
Current parser [allows ty/lt bounds have extra `+`](https://github.com/rust-lang/rust/blob/1.16.0/src/libsyntax/parse/parser.rs#L4025-L4072). However, the comments on the parser suggest they shouldn't be allowed. [grammar.md](https://github.com/rust-lang/rust/blob/1.16.0/src/doc/grammar.md) also suggests they shouldn't.

## Expected behavior

Both the first and second lines should lead to parse error.

```rust
fn f<'a>() where 'a: 'a + {}
fn g<'a, X>() where X: 'a + {}
fn main() {
}
```

## Current behavior

The current stable and nightly compilers allow the above code.

## Meta

Tested on Rust Playground.

stable

```
rustc 1.16.0 (30cf806ef 2017-03-10)
```

nightly

```
rustc 1.18.0-nightly (50c186419 2017-04-06)
```

### PR DESCRIPTION
**Pull request by alexeyzab**
Fixes #41158

### CODE REVIEW

File: src/libsyntax/parse/parser.rs [hunk 1]
```diff
@@ -4107,7 +4107,7 @@ impl<'a> Parser<'a> {
         self.parse_ty_param_bounds_common(true)
     }
 
-    // Parse bounds of a type parameter `BOUND + BOUND + BOUND` without trailing `+`.
+    // Parse bounds of a type parameter `BOUND + BOUND + BOUND`.
```
Comment (petrochenkov) [inline src/libsyntax/parse/parser.rs]: type parameter -> lifetime parameter

I'd also write "possibly with trailing `+`" to avoid future questions for sure.

File: src/doc/grammar.md [hunk 2]
```diff
@@ -780,6 +780,14 @@ never_type : "!" ;
...
 **FIXME:** grammar?
 
+### Type parameter bounds
+
+```antlr
+bound := ty_bound | lt_bound
+lt_bound := lifetime
+ty_bound := [?] [ for<lt_param_defs> ] simple_path
+```
+
```
Comment (petrochenkov) [inline src/doc/grammar.md]: Could you also remove the bound grammar from `### Closure types` and move the `bound-list` grammar into this paragraph (adjusting it with optional trailing `+`).

**Comment by nikomatsakis** [comment]
Seems not wrong to me.

**Comment by carols10cents** [comment]
Do I hear an r? @nikomatsakis @steveklabnik @petrochenkov ?

File: src/libsyntax/parse/parser.rs [hunk 3]
```diff
@@ -4066,7 +4066,7 @@ impl<'a> Parser<'a> {
         }).emit();
     }
 
-    // Parse bounds of a type parameter `BOUND + BOUND + BOUND` without trailing `+`.
+    // Parse bounds of a lifetime parameter `BOUND + BOUND + BOUND`, possibly with trailing `+`.
```
Comment (petrochenkov) [inline src/libsyntax/parse/parser.rs]: "lifetime parameter" -> "type parameter", otherwise r=me

Comment (petrochenkov) [inline src/libsyntax/parse/parser.rs]: I didn't notice this PR was updated, sorry.

**Comment by steveklabnik** [comment]
@bors: r+ rollup

thank you!
