### PR TITLE
Emit specific warning to clarify that `#[no_mangle]` should not be applied on foreign statics or functions

### LINKED ISSUE #78989: Incorrect no_mangle attribute warning
### Code

I tried this code:

```rust
extern "C" {
    #[no_mangle]
    static __init_array_start: i32;
}

fn main() {
    unsafe {
        println!("{:p}", &__init_array_start);
    }
}
```

I expected to see this happen: no warning.

Instead, this happened:
```
   Compiling no_mangle v0.1.0 (/home/pca/code/rust/no_mangle)
warning: attribute should be applied to a function or static
 --> src/main.rs:2:5
  |
2 |     #[no_mangle]
  |     ^^^^^^^^^^^^
3 |     static __init_array_start: i32;
  |     ------------------------------- not a function or static
  |
  = note: `#[warn(unused_attributes)]` on by default
  = warning: this was previously accepted by the compiler but is being phased out; it will become a hard error in a future release!

warning: 1 warning emitted

    Finished dev [unoptimized + debuginfo] target(s) in 0.19s
     Running `target/debug/no_mangle`
0x55626ded9540
```

~The attribute is actually applied correctly, otherwise we would get undefined symbol error.~ Also, the extern variable is clearly declared as static, so the warning does not really make sense.

Edit: it seems that the code also works without the `no_mangle` attribute. So is the `no_mangle` attribute actually not needed? Anyway, the warning about `not a function or static` is confusing.

This problem occurred in our embedded project [artiq-zynq](https://git.m-labs.hk/M-Labs/artiq-zynq/issues/115), where the static global variables are used to provide references to linker symbols.
### Version it worked on

It most recently worked on: Rust 1.47 stable. Haven't tried newer nightly.

### Version with regression
`rustc --version --verbose`:
```
rustc 1.49.0-nightly (5404efc28 2020-11-11)
binary: rustc
commit-hash: 5404efc28a0cddee103ef6396c48ea71ff9631c8
commit-date: 2020-11-11
host: x86_64-unknown-linux-gnu
release: 1.49.0-nightly
```

@rustbot modify labels: +regression-from-stable-to-nightly -regression-untriaged

### PR DESCRIPTION
**Pull request by asquared31415**
Foreign statics and foreign functions should not have `#[no_mangle]` applied, as it does nothing to the name and has some extra hidden behavior that is normally unwanted.  There was an existing warning for this, but it says the attribute is only allowed on "statics or functions", which to the user can be confusing.

This PR adds a specific version of the unused `#[no_mangle]` warning that explains that the target is a *foreign* static or function and that they do not need the attribute.

Fixes #78989

### CODE REVIEW

File: compiler/rustc_passes/src/check_attr.rs [hunk 1]
```diff
@@ -1151,6 +1151,47 @@ impl CheckAttrVisitor<'tcx> {
...
+                        .note("foreign symbol names are always preserved and the #[no_mangle] attribute may have additional undesired exporting effects.")
+                        .span_suggestion(
+                            attr.span,
+                            "remove this attribute",
+                            String::new(),
+                            Applicability::Unspecified,
+                        )
+                        .emit();
+                });
+                //bug!("AAAAAAAAAA");
```
Comment (BoxyUwU) [inline compiler/rustc_passes/src/check_attr.rs:1193]: aaaa

Comment (asquared31415) [reply compiler/rustc_passes/src/check_attr.rs]: Whoops, left that in while trying to get the test to work.  Removed.

File: compiler/rustc_passes/src/check_attr.rs [hunk 2]
```diff
@@ -1151,6 +1151,46 @@ impl CheckAttrVisitor<'tcx> {
...
+                        .note("foreign symbol names are always preserved and the #[no_mangle] attribute may have additional undesired exporting effects.")
+                        .span_suggestion(
+                            attr.span,
+                            "remove this attribute",
+                            String::new(),
+                            Applicability::Unspecified,
+                        )
+                        .emit();
+                });
+            }
```
Comment (BoxyUwU) [inline compiler/rustc_passes/src/check_attr.rs:1193]: since this code doesn't differ from the `Target::ForeignFn` arm except for the two instances of "static" instead of "function" it might be worth merging the two match arms

Comment (asquared31415) [reply compiler/rustc_passes/src/check_attr.rs]: Thank you, that looks much nicer!

**Comment by Mark-Simulacrum** [comment]
Can you say more about "may have additional undesired exporting effects"? I would naively expect that there is no additional behavior on extern statics/functions with no_mangle applied, in which case dropping that seems reasonable.

I don't think we should indicate an attribute is unused if it actually has a semantic effect (which the new diagnostic implies).

**Comment by Mark-Simulacrum** [comment]
Hm,I believe that no_mangle does not *re*export extern static/fns (which are in some sense imports, as you say), and so no_mangle has no effect whatsoever on them, right?

The warning text in this PR is:

```
warning: `#[no_mangle]` should not be applied to a foreign static
  --> $DIR/extern-no-mangle.rs:11:5
   |
LL |     #[no_mangle]
   |     ^^^^^^^^^^^^ help: remove this attribute
...
LL |     pub static FOO: u8;
   |     ------------------- foreign static
   |
   = warning: this was previously accepted by the compiler but is being phased out; it will become a hard error in a future release!
   = note: foreign symbol names are always preserved and the `#[no_mangle]` attribute may have additional undesired exporting effects.
```

I would suggest changing the main message and the note text to something like the following, presuming that it is accurate and makes sense in your eyes as well?

```
warning: `#[no_mangle]` has no effect on foreign statics
  --> $DIR/extern-no-mangle.rs:11:5
   |
LL |     #[no_mangle]
   |     ^^^^^^^^^^^^ help: remove this attribute
...
LL |     pub static FOO: u8;
   |     ------------------- foreign static
   |
   = warning: this was previously accepted by the compiler but is being phased out; it will become a hard error in a future release!
   = note: symbol names in extern blocks are not mangled by default
```

**Comment by asquared31415** [comment]
That updated text looks good.

With regards to exporting, I suppose what I was trying to do was contrast the behavior on foreign items with the behavior on everything else and explain why that is unintuitive.  However since it `#[no_mangle]` on foreign items is a no-op and doesn't make sense anyway because they don't use name mangling, it isn't really needed.

**Comment by Mark-Simulacrum** [comment]
@bors r+ rollup

Thanks! This looks good to me. I decided to skip a check in with T-lang since this seems like an obvious bug fix and we're just adding a lint here, so we can easily back this out if it shows up more often than expected or there's concerns raised at any point.
