### PR TITLE
compiletest: Remove empty 'expected' files when blessing

### LINKED ISSUE #134196: compiletest: empty stderr if check-fail -> check-pass
> > What the heck xD I blessed all ui tests in all commits...
>
> Hm, this might be a compiletest bug, where if u had a previous stderr from check-fail then u change it to check-pass it might write empty stderr but keep the file... I'll open an issue later.

_Originally posted by @jieyouxu in https://github.com/rust-lang/rust/issues/134070#issuecomment-2537790618_

### LINKED ISSUE #134793: compiletest "--bless" fails to delete stderr files
I made a mistake during compiler development so that a "--bless" run (`./x test ui --bless -- feat`) ended up generating a bunch of stderr files for compiler runs that shouldn't fail. I fixed that mistake, but unfortunately "--bless" does not remove these files. It seems I have to delete them all by hand.

That's not great; if "--bless" creates new files then it should also clean them up by itself.

### PR DESCRIPTION
**Pull request by clubby789**
Fixes #134793
Fixes #134196

This also refactors `compare_output` to return an enum; returning a usize was done for convenience but is misleading

### CODE REVIEW

**Review by jieyouxu — APPROVED** [review]
Thanks, I have some nits and a question, but otherwise LGTM.

File: src/tools/compiletest/src/runtest/coverage.rs [hunk 1]
```diff
@@ -46,9 +46,9 @@ impl<'test> TestCx<'test> {
             &expected_coverage_dump,
         );
 
-        if coverage_dump_errors > 0 {
+        if coverage_dump_errors {
             self.fatal_proc_rec(
-                &format!("{coverage_dump_errors} errors occurred comparing coverage output."),
+                &format!("an error occurred comparing coverage output."),
                 &proc_res,
             );
```
[the remark this answers is not in the document]
Comment (clubby789) [reply src/tools/compiletest/src/runtest/coverage.rs:53]: Since `let coverage_dump_errors = self.compare_output(...)` it can only ever be 0 or 1; I'll use the suggested enum

File: src/tools/compiletest/src/runtest.rs [hunk 2]
```diff
@@ -2653,10 +2657,12 @@ impl<'test> TestCx<'test> {
                 self.delete_file(&old);
             }
 
-            if let Err(err) = fs::write(&expected_path, &actual) {
-                self.fatal(&format!("failed to write {stream} to `{expected_path:?}`: {err}"));
+            if !actual.is_empty() {
+                if let Err(err) = fs::write(&expected_path, &actual) {
+                    self.fatal(&format!("failed to write {stream} to `{expected_path:?}`: {err}"));
+                }
+                println!("Blessing the {stream} of {test_name} in {expected_path:?}");
```
[the remark this answers is not in the document]
Comment (clubby789) [reply src/tools/compiletest/src/runtest.rs:2664]: Oh yes; I tested that both populated and empty stderr files will be removed when `actual` is empty

File: src/tools/compiletest/src/runtest.rs [hunk 3]
```diff
@@ -2570,21 +2582,29 @@ impl<'test> TestCx<'test> {
         }
     }
 
+    // Returns `true` if output differed and was not blessed
```
Comment (jieyouxu) [inline src/tools/compiletest/src/runtest.rs:2585]: Nit: outdated

File: src/tools/compiletest/src/runtest/coverage.rs [hunk 4]
```diff
@@ -46,9 +47,9 @@ impl<'test> TestCx<'test> {
             &expected_coverage_dump,
         );
 
-        if coverage_dump_errors > 0 {
+        if coverage_dump_errors.should_error() {
```
Comment (jieyouxu) [inline src/tools/compiletest/src/runtest/coverage.rs:50]: Nit: this local is named a bit strange, it's actually more like `coverage_dump_compare_outcome`, right?

**Review by jieyouxu — COMMENTED** [review]
Tiny nits, I'll do some local testing

**Comment by clubby789** [comment]
Updated; some stuff got borked in rebasing

File: src/tools/compiletest/src/runtest/coverage.rs [hunk 5]
```diff
@@ -6,6 +6,7 @@ use std::process::Command;
 
 use glob::glob;
 
+use super::CompareOutcome;
```
Comment (jieyouxu) [inline src/tools/compiletest/src/runtest/coverage.rs:9]: Nit: this is actually unused and will fail in CI due to `-D warnings`

**Review by jieyouxu — APPROVED** [review]
Based on local testing:

- Added a new ui test w/ error anno.
    - Initial no bless, failed as expected due to comparison w/ non-existent stderr failed.
    - Blessed, pass as expected.
    - Observed `.stderr` is present.
- Changed test to `//@ check-pass` and removed error annotation.
    - Observed empty `.stderr` is removed.

Seems like it's working as intended. Feel free to r=me after PR CI is green, thanks!
