### PR TITLE
Fix const-generics ICE related to binding

### LINKED ISSUE #83765: ICE:  Trying to collect bound vars with a bound region:
Got an ICE while trying to make a crate that implements Julia-like broadcast functionality. Not the most minimal example:
https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=64799ae35f987dc509e11973c1f20153

<details><summary>backtrace</summary>

```
thread 'rustc' panicked at 'Unknown variable: 0', compiler/rustc_ty_utils/src/instance.rs:46:17
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.55.0-nightly (955b9c0d4 2021-07-12) running on x86_64-unknown-linux-gnu

note: compiler flags: -C embed-bitcode=no -C codegen-units=1 -C debuginfo=2 --crate-type bin

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
thread 'rustc' panicked at 'substs of instance DefId(0:4 ~ playground[d8fc]::TensorDimension::DIM) not normalized for codegen: [^1]', compiler/rustc_middle/src/ty/instance.rs:286:9
stack backtrace:
   0:     0x7fef2af43f20 - std::backtrace_rs::backtrace::libunwind::trace::h706b838f5bbd876b
                               at /rustc/955b9c0d4cd9176b53f518e01cbe175545c69947/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
   1:     0x7fef2af43f20 - std::backtrace_rs::backtrace::trace_unsynchronized::hc15f29ae7822b7b8
                               at /rustc/955b9c0d4cd9176b53f518e01cbe175545c69947/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7fef2af43f20 - std::sys_common::backtrace::_print_fmt::h7c580c971f91926c
                               at /rustc/955b9c0d4cd9176b53f518e01cbe175545c69947/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x7fef2af43f20 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h2a772198c4032452
                               at /rustc/955b9c0d4cd9176b53f518e01cbe175545c69947/library/std/src/sys_common/backtrace.rs:46:22
   4:     0x7fef2afb1d0c - core::fmt::write::h9a6d9c74526a6c1b
                               at /rustc/955b9c0d4cd9176b53f518e01cbe175545c69947/library/core/src/fmt/mod.rs:1115:17
   5:     0x7fef2af35665 - std::io::Write::write_fmt::h00f38d9eb2c32e02
                               at /rustc/955b9c0d4cd9176b53f518e01cbe175545c69947/library/std/src/io/mod.rs:1663:15
   6:     0x7fef2af47c3b - std::sys_common::backtrace::_print::h5b3c171e6f864ae4
                               at /rustc/955b9c0d4cd9176b53f518e01cbe175545c69947/library/std/src/sys_common/backtrace.rs:49:5
   7:     0x7fef2af47c3b - std::sys_common::backtrace::print::h93b9e9ed2a98e611
                               at /rustc/955b9c0d4cd9176b53f518e01cbe175545c69947/library/std/src/sys_common/backtrace.rs:36:9
   8:     0x7fef2af47c3b - std::panicking::default_hook::{{closure}}::hd8da92bb68d520c5
                               at /rustc/955b9c0d4cd9176b53f518e01cbe175545c69947/library/std/src/panicking.rs:208:50
   9:     0x7fef2af47711 - std::panicking::default_hook::hdbc8b2951c5afbab
                               at /rustc/955b9c0d4cd9176b53f518e01cbe175545c69947/library/std/src/panicking.rs:225:9
  10:     0x7fef2b71df01 - rustc_driver::DEFAULT_HOOK::{{closure}}::{{closure}}::h9115897f26ef0e94
  11:     0x7fef2af48469 - std::panicking::rust_panic_with_hook::h8a4c841655926f4e
                               at /rustc/955b9c0d4cd9176b53f518e01cbe175545c69947/library/std/src/panicking.rs:626:17
  12:     0x7fef2af47f27 - std::panicking::begin_panic_handler::{{closure}}::h471b6bc74904b7b0
                               at /rustc/955b9c0d4cd9176b53f518e01cbe175545c69947/library/std/src/panicking.rs:519:13
  13:     0x7fef2af4441c - std::sys_common::backtrace::__rust_end_short_backtrace::h309f5c707f29932f
                               at /rustc/955b9c0d4cd9176b53f518e01cbe175545c69947/library/std/src/sys_common/backtrace.rs:141:18
  14:     0x7fef2af47e89 - rust_begin_unwind
                               at /rustc/955b9c0d4cd9176b53f518e01cbe175545c69947/library/std/src/panicking.rs:515:5
  15:     0x7fef2af10dbb - std::panicking::begin_panic_fmt::h124dfb9fde553188
                               at /rustc/955b9c0d4cd9176b53f518e01cbe175545c69947/library/std/src/panicking.rs:457:5
  16:     0x7fef2d16de8e - rustc_middle::ty::instance::Instance::new::h4bc0b902805b73c3
  17:     0x7fef2bca7d95 - std::thread::local::LocalKey<T>::with::h1bf9bba74543d0f2
  18:     0x7fef2bcb7da4 - std::thread::local::LocalKey<T>::with::hbb41c71ef11f8b4d
  19:     0x7fef2bd09dbe - rustc_query_impl::make_query::resolve_instance::h1b43a4ec840764d1
  20:     0x7fef2bc487a0 - rustc_query_system::query::plumbing::QueryState<D,K>::try_collect_active_jobs::h82516257c956e5dd
  21:     0x7fef2bcf2c64 - rustc_query_impl::Queries::try_collect_active_jobs::hfa1414681bc4a6f4
  22:     0x7fef2bcc02c1 - rustc_query_system::query::job::print_query_stack::h5730919cbd425e7c
  23:     0x7fef2b82be97 - rustc_interface::interface::try_print_query_stack::h440ea915a08bc272
  24:     0x7fef2b71e2ef - rustc_driver::report_ice::hc86e0f709da84157
  25:     0x7fef2af48469 - std::panicking::rust_panic_with_hook::h8a4c841655926f4e
                               at /rustc/955b9c0d4cd9176b53f518e01cbe175545c69947/library/std/src/panicking.rs:626:17
  26:     0x7fef2af47f27 - std::panicking::begin_panic_handler::{{closure}}::h471b6bc74904b7b0
                               at /rustc/955b9c0d4cd9176b53f518e01cbe175545c69947/library/std/src/panicking.rs:519:13
  27:     0x7fef2af4441c - std::sys_common::backtrace::__rust_end_short_backtrace::h309f5c707f29932f
                               at /rustc/955b9c0d4cd9176b53f518e01cbe175545c69947/library/std/src/sys_common/backtrace.rs:141:18
  28:     0x7fef2af47e89 - rust_begin_unwind
                               at /rustc/955b9c0d4cd9176b53f518e01cbe175545c69947/library/std/src/panicking.rs:515:5
  29:     0x7fef2af10dbb - std::panicking::begin_panic_fmt::h124dfb9fde553188
                               at /rustc/955b9c0d4cd9176b53f518e01cbe175545c69947/library/std/src/panicking.rs:457:5
  30:     0x7fef2ca15e09 - rustc_ty_utils::instance::inner_resolve_instance::ha62fdd9539be506f
  31:     0x7fef2ca12b16 - rustc_ty_utils::instance::resolve_instance::h6c43c832ecc9f58d
  32:     0x7fef2cb02be6 - rustc_query_system::query::plumbing::get_query_impl::h98c7a37900e75c1a
  33:     0x7fef2cb541d5 - <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::resolve_instance::h131142b59edae365
  34:     0x7fef2d16ed34 - rustc_middle::ty::instance::Instance::resolve_opt_const_arg::h85eff761c92245d7
  35:     0x7fef2d12044a - rustc_middle::mir::interpret::queries::<impl rustc_middle::ty::context::TyCtxt>::const_eval_resolve::h05f9be04dd287144
  36:     0x7fef2d043ab7 - <rustc_trait_selection::traits::query::normalize::QueryNormalizer as rustc_middle::ty::fold::TypeFolder>::fold_const::h2b8fc62883ffe49e
  37:     0x7fef2d9ea421 - <rustc_trait_selection::traits::query::normalize::QueryNormalizer as rustc_middle::ty::fold::TypeFolder>::fold_mir_const::hae5a0c34494777c7
  38:     0x7fef2d3ac027 - <rustc_infer::infer::at::At as rustc_trait_selection::traits::query::normalize::AtExt>::normalize::hd29ab4f556b4eba1
  39:     0x7fef2d39e861 - rustc_infer::infer::InferCtxtBuilder::enter::h914fd9bf94352a47
  40:     0x7fef2d3ad482 - core::ops::function::FnOnce::call_once::h07f7ef4c390d1173
  41:     0x7fef2d569156 - rustc_query_system::query::plumbing::get_query_impl::h228c7f5596c35d25
  42:     0x7fef2d635452 - <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::normalize_mir_const_after_erasing_regions::h8a95c105f8c26374
  43:     0x7fef2cda9f42 - rustc_middle::ty::normalize_erasing_regions::<impl rustc_middle::ty::context::TyCtxt>::normalize_erasing_regions::h18e25ec2a174f17d
  44:     0x7fef2cd8608f - rustc_mir::interpret::eval_context::InterpCx<M>::push_stack_frame::h57241db08af59ac2
  45:     0x7fef2cc9a6dc - rustc_mir::const_eval::eval_queries::eval_to_allocation_raw_provider::heae3d1b1c6a8baf5
  46:     0x7fef2cb10bca - rustc_query_system::query::plumbing::get_query_impl::he3c6640669a2a2c2
  47:     0x7fef2cb51d6c - <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::eval_to_allocation_raw::hdc0a37858c2b9f88
  48:     0x7fef2cc98f74 - rustc_mir::const_eval::eval_queries::eval_to_const_value_raw_provider::he812b93c2ed73711
  49:     0x7fef2cade79a - rustc_query_system::query::plumbing::get_query_impl::h1181b9a9d9860866
  50:     0x7fef2cb51e90 - <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::eval_to_const_value_raw::h22567b86e0543a37
  51:     0x7fef2d10dafa - rustc_middle::mir::interpret::queries::<impl rustc_middle::ty::context::TyCtxt>::const_eval_global_id::h53e1a0ab4f3788ab
  52:     0x7fef2d12048d - rustc_middle::mir::interpret::queries::<impl rustc_middle::ty::context::TyCtxt>::const_eval_resolve::h05f9be04dd287144
  53:     0x7fef2da1e726 - rustc_infer::infer::InferCtxt::const_eval_resolve::h1fc86c723833ff6a
  54:     0x7fef2c471060 - rustc_trait_selection::traits::select::SelectionContext::evaluate_predicate_recursively::{{closure}}::{{closure}}::h1aeb03e1892925ca
  55:     0x7fef2d0401df - rustc_data_structures::stack::ensure_sufficient_stack::ha262825375eb89a5
  56:     0x7fef2d074ddf - rustc_trait_selection::traits::select::SelectionContext::evaluate_predicate_recursively::hd50b7c067b113b6a
  57:     0x7fef2d066bdf - rustc_trait_selection::traits::select::SelectionContext::evaluate_predicates_recursively::h03c6cc0fc2fb0c94
  58:     0x7fef2d022860 - rustc_infer::infer::InferCtxt::probe::hfac507797fb7b5fb
  59:     0x7fef2d074fd1 - rustc_trait_selection::traits::select::SelectionContext::evaluate_candidate::hc0585d9092b0698c
  60:     0x7fef2d0822b6 - <core::iter::adapters::ResultShunt<I,E> as core::iter::traits::iterator::Iterator>::next::hea7024379e5fe349
  61:     0x7fef2d03c916 - <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter::hd9d203e90c144a08
  62:     0x7fef2d062c3b - rustc_trait_selection::traits::select::candidate_assembly::<impl rustc_trait_selection::traits::select::SelectionContext>::candidate_from_obligation_no_cache::h043296d3b8836763
  63:     0x7fef2d05eb3b - rustc_query_system::dep_graph::graph::DepGraph<K>::with_anon_task::h47195f4d0fb22b03
  64:     0x7fef2d06ba50 - rustc_trait_selection::traits::select::candidate_assembly::<impl rustc_trait_selection::traits::select::SelectionContext>::candidate_from_obligation::h0d6cdd36b0a570fb
  65:     0x7fef2d068207 - rustc_trait_selection::traits::select::SelectionContext::evaluate_stack::h69a1f50b2792c57d
  66:     0x7fef2d05efde - rustc_query_system::dep_graph::graph::DepGraph<K>::with_anon_task::h5fa14234b94c48c7
  67:     0x7fef2d067524 - rustc_trait_selection::traits::select::SelectionContext::evaluate_trait_predicate_recursively::h4fdebf34a57f66fd
  68:     0x7fef2d03f8a9 - rustc_data_structures::stack::ensure_sufficient_stack::ha262825375eb89a5
  69:     0x7fef2d074ddf - rustc_trait_selection::traits::select::SelectionContext::evaluate_predicate_recursively::hd50b7c067b113b6a
  70:     0x7fef2d021d2d - rustc_infer::infer::InferCtxt::probe::h49937ac5b33c5781
  71:     0x7fef2d066b10 - rustc_trait_selection::traits::select::SelectionContext::evaluate_root_obligation::h2f9d0895cdb84bd0
  72:     0x7fef2c8886d3 - rustc_infer::infer::InferCtxtBuilder::enter_with_canonical::h9cdf89db81539f0d
  73:     0x7fef2c89048b - rustc_traits::evaluate_obligation::evaluate_obligation::h4ab552bc983eaa00
  74:     0x7fef2caeeed9 - rustc_query_system::query::plumbing::get_query_impl::h4920e614a64e9368
  75:     0x7fef2cb53f23 - <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::evaluate_obligation::ha27bbdceb77d17b4
  76:     0x7fef2d02737c - <rustc_infer::infer::InferCtxt as rustc_trait_selection::traits::query::evaluate_obligation::InferCtxtExt>::evaluate_obligation::hf5cdf6c2f7bbe8fe
  77:     0x7fef2d027690 - <rustc_infer::infer::InferCtxt as rustc_trait_selection::traits::query::evaluate_obligation::InferCtxtExt>::evaluate_obligation_no_overflow::hb467e41644548c30
  78:     0x7fef2c451d3c - <rustc_infer::infer::InferCtxt as rustc_trait_selection::traits::error_reporting::InferCtxtPrivExt>::predicate_can_apply::hb7fe73a96fe82161
  79:     0x7fef2c44be09 - <rustc_infer::infer::InferCtxt as rustc_trait_selection::traits::error_reporting::InferCtxtExt>::report_selection_error::h539e53eede9face4
  80:     0x7fef2c447f67 - <rustc_infer::infer::InferCtxt as rustc_trait_selection::traits::error_reporting::InferCtxtExt>::report_fulfillment_errors::h14d0e8bab898c5c6
  81:     0x7fef2c901297 - rustc_typeck::check::fn_ctxt::checks::<impl rustc_typeck::check::fn_ctxt::FnCtxt>::check_argument_types::h77ab27cd91dd6c3a
  82:     0x7fef2c8ffbd7 - rustc_typeck::check::fn_ctxt::checks::<impl rustc_typeck::check::fn_ctxt::FnCtxt>::check_method_argument_types::h4868a094e1ee7843
  83:     0x7fef2c8ec5b2 - rustc_typeck::check::expr::<impl rustc_typeck::check::fn_ctxt::FnCtxt>::check_expr_kind::h847ee349f779d14a
  84:     0x7fef2c8eb765 - rustc_typeck::check::expr::<impl rustc_typeck::check::fn_ctxt::FnCtxt>::check_expr_with_expectation::h8c0cb080ad6933ce
  85:     0x7fef2c9031a9 - rustc_typeck::check::fn_ctxt::checks::<impl rustc_typeck::check::fn_ctxt::FnCtxt>::check_block_with_expected::h3d043f9e26a99125
  86:     0x7fef2c8eb765 - rustc_typeck::check::expr::<impl rustc_typeck::check::fn_ctxt::FnCtxt>::check_expr_with_expectation::h8c0cb080ad6933ce
  87:     0x7fef2c8f70b3 - rustc_typeck::check::expr::<impl rustc_typeck::check::fn_ctxt::FnCtxt>::check_return_expr::h9577da4ea7b48df9
  88:     0x7fef2c9c388a - rustc_typeck::check::check::check_fn::he9427b824b1bee31
  89:     0x7fef2c98a8df - rustc_infer::infer::InferCtxtBuilder::enter::h10bfca448b8abe65
  90:     0x7fef2c9dade9 - rustc_typeck::check::typeck::h9d473560c90e8eac
  91:     0x7fef2cb0a8ac - rustc_query_system::query::plumbing::get_query_impl::hb2ddc440783de3e4
  92:     0x7fef2cb51b1b - <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::typeck::h20e7e18fe4adf547
  93:     0x7fef2c9459ba - rustc_middle::ty::<impl rustc_middle::ty::context::TyCtxt>::par_body_owners::hfe38da49ef8fae21
  94:     0x7fef2d4a1a4c - rustc_typeck::check::typeck_item_bodies::h84f6dc7a319dd44a
  95:     0x7fef2d56aa0b - rustc_query_system::query::plumbing::get_query_impl::h2372b8eda1752700
  96:     0x7fef2d631790 - <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::typeck_item_bodies::h49264e150777de1e
  97:     0x7fef2d438b6f - rustc_session::utils::<impl rustc_session::session::Session>::time::hb04bad2c59296de9
  98:     0x7fef2d4cd287 - rustc_typeck::check_crate::h052f04b1c455d412
  99:     0x7fef2d2290ef - rustc_interface::passes::analysis::h57734cd964f56f31
 100:     0x7fef2d5984a9 - rustc_query_system::query::plumbing::get_query_impl::hcbbfd8ecd4ff870b
 101:     0x7fef2d62f70d - <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::analysis::hbd79061f78fee3dc
 102:     0x7fef2d1fe6a2 - rustc_interface::queries::<impl rustc_interface::interface::Compiler>::enter::h322d262b9c0938c4
 103:     0x7fef2d1ed79c - rustc_span::with_source_map::hef536b13581cfdf1
 104:     0x7fef2d1ff87a - rustc_interface::interface::create_compiler_and_run::h268d650d50fb09f1
 105:     0x7fef2d1f29c9 - scoped_tls::ScopedKey<T>::set::h01e1202900a6e691
 106:     0x7fef2d1ef8aa - std::sys_common::backtrace::__rust_begin_short_backtrace::h32f903e490a897c1
 107:     0x7fef2d1ee135 - core::ops::function::FnOnce::call_once{{vtable.shim}}::h3ecb73c3653fe1a0
 108:     0x7fef2af54a17 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::ha8b1d5a0092467fc
                               at /rustc/955b9c0d4cd9176b53f518e01cbe175545c69947/library/alloc/src/boxed.rs:1572:9
 109:     0x7fef2af54a17 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h4b9f24ec4e8a879e
                               at /rustc/955b9c0d4cd9176b53f518e01cbe175545c69947/library/alloc/src/boxed.rs:1572:9
 110:     0x7fef2af54a17 - std::sys::unix::thread::Thread::new::thread_start::h2a0e98fbc4ab4c32
                               at /rustc/955b9c0d4cd9176b53f518e01cbe175545c69947/library/std/src/sys/unix/thread.rs:74:17
 111:     0x7fef2ae8e609 - start_thread
 112:     0x7fef2ada2293 - clone
 113:                0x0 - <unknown>

```

</details>

Edit: fixed link.

### LINKED ISSUE #85848: ICE in rust nightly 2021-05-30
The code isn't correct anyways, but I did run across this. Minimized a bit, but it's still a fairly sizable example - sorry about that.
### Code
https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=49ea5447e438ddb212b8dcbee034255b

### Meta
rustc 1.54.0-nightly (c1e8f3a58 2021-05-30)

### Error output

```
   Compiling playground v0.0.1 (/playground)
error: internal compiler error: compiler/rustc_middle/src/ty/fold.rs:829:17: Trying to collect bound vars with a bound region: DebruijnIndex(0) BoundRegion { var: 0, kind: BrAnon(0) }

thread 'rustc' panicked at 'Box<Any>', compiler/rustc_errors/src/lib.rs:1005:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.54.0-nightly (c1e8f3a58 2021-05-30) running on x86_64-unknown-linux-gnu

note: compiler flags: -C embed-bitcode=no -C codegen-units=1 -C debuginfo=2 --crate-type lib

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
thread 'rustc' panicked at 'substs of instance DefId(0:10 ~ playground[4a2c]::_Contains::does_contain) not normalized for codegen: [FileCap<FileOp::Write, FileResource::StaticPath("foobar")>, &C]', compiler/rustc_middle/src/ty/instance.rs:285:9
stack backtrace:
   0:     0x7f6ea8d7bf80 - std::backtrace_rs::backtrace::libunwind::trace::h1a39bd9a98540471
                               at /rustc/c1e8f3a5857c3c8d095fd212acc6ed442f4cc58b/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
   1:     0x7f6ea8d7bf80 - std::backtrace_rs::backtrace::trace_unsynchronized::h21a1eeae7103ab3f
                               at /rustc/c1e8f3a5857c3c8d095fd212acc6ed442f4cc58b/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7f6ea8d7bf80 - std::sys_common::backtrace::_print_fmt::hc9ffbae9ed6a9871
                               at /rustc/c1e8f3a5857c3c8d095fd212acc6ed442f4cc58b/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x7f6ea8d7bf80 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h17510753a34a3f09
                               at /rustc/c1e8f3a5857c3c8d095fd212acc6ed442f4cc58b/library/std/src/sys_common/backtrace.rs:46:22
   4:     0x7f6ea8de99ac - core::fmt::write::h1e5a1f350e43b10f
                               at /rustc/c1e8f3a5857c3c8d095fd212acc6ed442f4cc58b/library/core/src/fmt/mod.rs:1110:17
   5:     0x7f6ea8d6d805 - std::io::Write::write_fmt::h06ec27c6d028baf1
                               at /rustc/c1e8f3a5857c3c8d095fd212acc6ed442f4cc58b/library/std/src/io/mod.rs:1588:15
   6:     0x7f6ea8d7fddb - std::sys_common::backtrace::_print::h1a02603349b1dc60
                               at /rustc/c1e8f3a5857c3c8d095fd212acc6ed442f4cc58b/library/std/src/sys_common/backtrace.rs:49:5
   7:     0x7f6ea8d7fddb - std::sys_common::backtrace::print::h0fc317d31c48cd9b
                               at /rustc/c1e8f3a5857c3c8d095fd212acc6ed442f4cc58b/library/std/src/sys_common/backtrace.rs:36:9
   8:     0x7f6ea8d7fddb - std::panicking::default_hook::{{closure}}::ha522601c22d7057b
                               at /rustc/c1e8f3a5857c3c8d095fd212acc6ed442f4cc58b/library/std/src/panicking.rs:208:50
   9:     0x7f6ea8d7f8b1 - std::panicking::default_hook::hd50ab173af9a3ce8
                               at /rustc/c1e8f3a5857c3c8d095fd212acc6ed442f4cc58b/library/std/src/panicking.rs:225:9
  10:     0x7f6ea95509bd - rustc_driver::report_ice::h0bbc0ae77d597594
  11:     0x7f6ea8d805e6 - std::panicking::rust_panic_with_hook::hb5a01416e02405ad
                               at /rustc/c1e8f3a5857c3c8d095fd212acc6ed442f4cc58b/library/std/src/panicking.rs:626:17
  12:     0x7f6ea8d800c7 - std::panicking::begin_panic_handler::{{closure}}::hf1dda5d5c0706ee0
                               at /rustc/c1e8f3a5857c3c8d095fd212acc6ed442f4cc58b/library/std/src/panicking.rs:519:13
  13:     0x7f6ea8d7c45c - std::sys_common::backtrace::__rust_end_short_backtrace::h56c02e9609085b17
                               at /rustc/c1e8f3a5857c3c8d095fd212acc6ed442f4cc58b/library/std/src/sys_common/backtrace.rs:141:18
  14:     0x7f6ea8d80029 - rust_begin_unwind
                               at /rustc/c1e8f3a5857c3c8d095fd212acc6ed442f4cc58b/library/std/src/panicking.rs:515:5
  15:     0x7f6ea8d48eeb - std::panicking::begin_panic_fmt::h5889dddec113b3e8
                               at /rustc/c1e8f3a5857c3c8d095fd212acc6ed442f4cc58b/library/std/src/panicking.rs:457:5
  16:     0x7f6eaafc1223 - rustc_middle::ty::instance::Instance::new::h138b137268683e1e
  17:     0x7f6ea9aff205 - std::thread::local::LocalKey<T>::with::h5d9224abdd7920e1
  18:     0x7f6ea9b058b4 - std::thread::local::LocalKey<T>::with::h98ac41cac71185c2
  19:     0x7f6ea9b35cde - rustc_query_impl::make_query::resolve_instance::h6c2db3b7c4731c32
  20:     0x7f6ea9a754dd - rustc_query_system::query::plumbing::QueryState<D,K>::try_collect_active_jobs::h8d3183294409f20d
  21:     0x7f6ea9b4e7da - rustc_query_impl::Queries::try_collect_active_jobs::h804da0378b7580b3
  22:     0x7f6ea9c7ead7 - rustc_query_system::query::job::print_query_stack::hd56f847aa29e3347
  23:     0x7f6ea95fe637 - rustc_interface::interface::try_print_query_stack::hcd178fe26145ef9d
  24:     0x7f6ea9550d6d - rustc_driver::report_ice::h0bbc0ae77d597594
  25:     0x7f6ea8d805e6 - std::panicking::rust_panic_with_hook::hb5a01416e02405ad
                               at /rustc/c1e8f3a5857c3c8d095fd212acc6ed442f4cc58b/library/std/src/panicking.rs:626:17
  26:     0x7f6eaa52893b - std::panicking::begin_panic::{{closure}}::h79be31a52b7554ed
  27:     0x7f6eaa5288f6 - std::sys_common::backtrace::__rust_end_short_backtrace::h0d6d6b53a98843e6
  28:     0x7f6eaa52a0cf - std::panicking::begin_panic::h1d412c1e7c1dec3c
  29:     0x7f6eaa541a3d - std::panic::panic_any::h427710dcb10bbe92
  30:     0x7f6eaa54493a - rustc_errors::HandlerInner::bug::h54fd3663069746c7
  31:     0x7f6eaa5443e0 - rustc_errors::Handler::bug::h6fd29773c2809aef
  32:     0x7f6eaa4938e0 - rustc_middle::ty::context::tls::with_opt::h5d93e51ac4f84952
  33:     0x7f6eaa496d40 - rustc_middle::util::bug::opt_span_bug_fmt::h73ef8867dd647d6e
  34:     0x7f6eaa496cb6 - rustc_middle::util::bug::bug_fmt::h5eaf5bea31bbe7e0
  35:     0x7f6eaafe8e70 - <rustc_middle::ty::fold::BoundVarsCollector as rustc_middle::ty::fold::TypeVisitor>::visit_ty::h6514ebe90c448cdd
  36:     0x7f6eaa852986 - rustc_middle::ty::sty::Binder<T>::bind::h50c53be3fc93c400
  37:     0x7f6eaa84ffcb - rustc_ty_utils::instance::inner_resolve_instance::h2ee186f9093bf7d7
  38:     0x7f6eaa84f227 - rustc_ty_utils::instance::resolve_instance::h452e351b7015c1e3
  39:     0x7f6eaa963513 - rustc_query_impl::<impl rustc_query_system::query::config::QueryAccessors<rustc_query_impl::plumbing::QueryCtxt> for rustc_query_impl::queries::resolve_instance>::compute::h3a414191b883d966
  40:     0x7f6eaa94e2b8 - rustc_query_system::query::plumbing::get_query_impl::hf75519e5cd807995
  41:     0x7f6eaa98de2d - <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::resolve_instance::h82667371ba59cd83
  42:     0x7f6eaafc2ffd - rustc_middle::ty::instance::Instance::resolve_opt_const_arg::ha0925e4a88f592f8
  43:     0x7f6eaaf7b31a - rustc_middle::mir::interpret::queries::<impl rustc_middle::ty::context::TyCtxt>::const_eval_resolve::h05ad8dfc76427d5b
  44:     0x7f6eaae7d570 - <rustc_trait_selection::traits::query::normalize::QueryNormalizer as rustc_middle::ty::fold::TypeFolder>::fold_const::h1a2b3db3741ddf78
  45:     0x7f6eab85c151 - <rustc_trait_selection::traits::query::normalize::QueryNormalizer as rustc_middle::ty::fold::TypeFolder>::fold_mir_const::hc529b8661d679324
  46:     0x7f6eab21c0f7 - <rustc_infer::infer::at::At as rustc_trait_selection::traits::query::normalize::AtExt>::normalize::hbb82211ffd579d79
  47:     0x7f6eab20ef21 - rustc_infer::infer::InferCtxtBuilder::enter::h2d501578ee6c38b9
  48:     0x7f6eab21bc32 - core::ops::function::FnOnce::call_once::h67853e98b8f1ca08
  49:     0x7f6eab4750a8 - rustc_query_impl::<impl rustc_query_system::query::config::QueryAccessors<rustc_query_impl::plumbing::QueryCtxt> for rustc_query_impl::queries::normalize_mir_const_after_erasing_regions>::compute::h013cf6812c6dfcde
  50:     0x7f6eab4132a4 - rustc_query_system::query::plumbing::get_query_impl::hd0fdeba8daa0e895
  51:     0x7f6eab4a7b39 - <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::normalize_mir_const_after_erasing_regions::hef60be0778070bfa
  52:     0x7f6eaabe30ed - rustc_middle::ty::normalize_erasing_regions::<impl rustc_middle::ty::context::TyCtxt>::normalize_erasing_regions::h8cd5a629f411350d
  53:     0x7f6eaabbc5d0 - rustc_mir::interpret::eval_context::InterpCx<M>::push_stack_frame::hb4d3d6e60f56f2cd
  54:     0x7f6eaabdd7ff - rustc_mir::interpret::terminator::<impl rustc_mir::interpret::eval_context::InterpCx<M>>::eval_fn_call::h18df32d0a18b92f7
  55:     0x7f6eaabcfdfb - rustc_mir::interpret::step::<impl rustc_mir::interpret::eval_context::InterpCx<M>>::run::h578d68801dae73c8
  56:     0x7f6eaaad8770 - rustc_mir::const_eval::eval_queries::eval_to_allocation_raw_provider::hc342a5cc80315017
  57:     0x7f6eaa962efd - rustc_query_impl::<impl rustc_query_system::query::config::QueryAccessors<rustc_query_impl::plumbing::QueryCtxt> for rustc_query_impl::queries::eval_to_allocation_raw>::compute::h50f34bc5c1b84fb8
  58:     0x7f6eaa933c64 - rustc_query_system::query::plumbing::get_query_impl::h82efa1836f4eb10a
  59:     0x7f6eaa98bdf7 - <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::eval_to_allocation_raw::h2b3ca26d4a0bfe39
  60:     0x7f6eaaad71aa - rustc_mir::const_eval::eval_queries::eval_to_const_value_raw_provider::h492a1f0908ef1033
  61:     0x7f6eaa962f3d - rustc_query_impl::<impl rustc_query_system::query::config::QueryAccessors<rustc_query_impl::plumbing::QueryCtxt> for rustc_query_impl::queries::eval_to_const_value_raw>::compute::hf332c6ae6cc62cca
  62:     0x7f6eaa93c6e5 - rustc_query_system::query::plumbing::get_query_impl::ha84d8dc8b8f75ed2
  63:     0x7f6eaa98bf17 - <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::eval_to_const_value_raw::h46d27616aa3d4e98
  64:     0x7f6eaaf64684 - rustc_middle::mir::interpret::queries::<impl rustc_middle::ty::context::TyCtxt>::const_eval_global_id::h5b31d85c4aaa4700
  65:     0x7f6eaaf7b35d - rustc_middle::mir::interpret::queries::<impl rustc_middle::ty::context::TyCtxt>::const_eval_resolve::h05ad8dfc76427d5b
  66:     0x7f6eab898056 - rustc_infer::infer::InferCtxt::const_eval_resolve::h8853853f26ced4a7
  67:     0x7f6eaa27d449 - rustc_trait_selection::traits::fulfill::FulfillProcessor::progress_changed_obligations::{{closure}}::h31242c7bb950182e
  68:     0x7f6eaae7c8d9 - rustc_trait_selection::traits::fulfill::FulfillProcessor::progress_changed_obligations::he0b9099f8a0ebc6e
  69:     0x7f6eaae9747f - rustc_data_structures::obligation_forest::ObligationForest<O>::process_obligations::h85e16c4356ccd540
  70:     0x7f6eaae7bc7b - <rustc_trait_selection::traits::fulfill::FulfillmentContext as rustc_infer::traits::engine::TraitEngine>::select_where_possible::h137caf5bfc9f4211
  71:     0x7f6eaa737ebc - rustc_typeck::check::fn_ctxt::checks::<impl rustc_typeck::check::fn_ctxt::FnCtxt>::check_argument_types::hd9c65b7090c33843
  72:     0x7f6eaa71b67b - rustc_typeck::check::callee::<impl rustc_typeck::check::fn_ctxt::FnCtxt>::confirm_builtin_call::h49cff8412dd49fd0
  73:     0x7f6eaa71a830 - rustc_typeck::check::callee::<impl rustc_typeck::check::fn_ctxt::FnCtxt>::check_call::h9e8271b1bb5c17fc
  74:     0x7f6eaa7236d7 - rustc_typeck::check::expr::<impl rustc_typeck::check::fn_ctxt::FnCtxt>::check_expr_kind::h9a0610c69d1db80e
  75:     0x7f6eaa722da5 - rustc_typeck::check::expr::<impl rustc_typeck::check::fn_ctxt::FnCtxt>::check_expr_with_expectation::hbec31136b572e013
  76:     0x7f6eaa73a276 - rustc_typeck::check::fn_ctxt::checks::<impl rustc_typeck::check::fn_ctxt::FnCtxt>::check_stmt::hd9c9401fae4f4007
  77:     0x7f6eaa73ab0c - rustc_typeck::check::fn_ctxt::checks::<impl rustc_typeck::check::fn_ctxt::FnCtxt>::check_block_with_expected::hec26ce1e195d7b11
  78:     0x7f6eaa722da5 - rustc_typeck::check::expr::<impl rustc_typeck::check::fn_ctxt::FnCtxt>::check_expr_with_expectation::hbec31136b572e013
  79:     0x7f6eaa72e323 - rustc_typeck::check::expr::<impl rustc_typeck::check::fn_ctxt::FnCtxt>::check_return_expr::hd1dd70742d727dbf
  80:     0x7f6eaa80da18 - rustc_typeck::check::check::check_fn::h6af6276ff63ec41c
  81:     0x7f6eaa7b343c - rustc_typeck::check::inherited::InheritedBuilder::enter::hf5a3faec0a6907b2
  82:     0x7f6eaa806088 - rustc_typeck::check::typeck::h896d419cb4279063
  83:     0x7f6eaa93ba8f - rustc_query_system::query::plumbing::get_query_impl::ha6569a99536f15ef
  84:     0x7f6eaa98bbad - <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::typeck::hc9871bea409f75ba
  85:     0x7f6eaa77f48a - rustc_middle::ty::<impl rustc_middle::ty::context::TyCtxt>::par_body_owners::h5653ee80ce8eeaf5
  86:     0x7f6eab314b0c - rustc_typeck::check::typeck_item_bodies::h84a3ebce4ed8af72
  87:     0x7f6eab400537 - rustc_query_system::query::plumbing::get_query_impl::h9d41a92686f2332d
  88:     0x7f6eab4a43c9 - <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::typeck_item_bodies::hfc11308daf2482eb
  89:     0x7f6eab2bbfdf - rustc_session::utils::<impl rustc_session::session::Session>::time::h5e0207abea9a46ba
  90:     0x7f6eab343e2c - rustc_typeck::check_crate::h033d52ddf5a3c52c
  91:     0x7f6eaa6534dc - rustc_interface::passes::analysis::h44573dd1f435360d
  92:     0x7f6eab408c14 - rustc_query_system::query::plumbing::get_query_impl::hb28d9338aaa73db6
  93:     0x7f6eab4a2619 - <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::analysis::h92a4884e0478500d
  94:     0x7f6eab081aa7 - rustc_interface::passes::QueryContext::enter::hb9b4b642821635fe
  95:     0x7f6eab05d6e3 - rustc_interface::queries::<impl rustc_interface::interface::Compiler>::enter::h16bd07ff16fa3d4a
  96:     0x7f6eab059f0c - rustc_span::with_source_map::h6ee13da35fa72295
  97:     0x7f6eab05cf28 - scoped_tls::ScopedKey<T>::set::h9c6565b722913393
  98:     0x7f6eab081e4b - std::sys_common::backtrace::__rust_begin_short_backtrace::hdcf17779193f6d57
  99:     0x7f6eab058c15 - core::ops::function::FnOnce::call_once{{vtable.shim}}::hf48084e1b458d4b2
 100:     0x7f6ea8d8cad7 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hf00ff0dfc0b9e39f
                               at /rustc/c1e8f3a5857c3c8d095fd212acc6ed442f4cc58b/library/alloc/src/boxed.rs:1575:9
 101:     0x7f6ea8d8cad7 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h236979b1b61b3517
                               at /rustc/c1e8f3a5857c3c8d095fd212acc6ed442f4cc58b/library/alloc/src/boxed.rs:1575:9
 102:     0x7f6ea8d8cad7 - std::sys::unix::thread::Thread::new::thread_start::h8f357e546e4775fa
                               at /rustc/c1e8f3a5857c3c8d095fd212acc6ed442f4cc58b/library/std/src/sys/unix/thread.rs:71:17
 103:     0x7f6ea8cc7609 - start_thread
 104:     0x7f6ea8bdb293 - clone
 105:                0x0 - <unknown>

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.54.0-nightly (c1e8f3a58 2021-05-30) running on x86_64-unknown-linux-gnu

note: compiler flags: -C embed-bitcode=no -C codegen-units=1 -C debuginfo=2 --crate-type lib

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
thread panicked while panicking. aborting.
error: could not compile `playground`

Caused by:
  process didn't exit successfully: `rustc --crate-name playground --edition=2018 src/lib.rs --error-format=json --json=diagnostic-rendered-ansi --crate-type lib --emit=dep-info,metadata,link -C embed-bitcode=no -C codegen-units=1 -C debuginfo=2 -C metadata=d5583dc9c61d0f13 -C extra-filename=-d5583dc9c61d0f13 --out-dir /playground/target/debug/deps -L dependency=/playground/target/debug/deps --extern addr2line=/playground/target/debug/deps/libaddr2line-ee0d9d4a76af11ea.rmeta --extern adler=/playground/target/debug/deps/libadler-b49c949e3504cbd1.rmeta --extern adler32=/playground/target/debug/deps/libadler32-d4247d4849a00fb6.rmeta --extern ahash=/playground/target/debug/deps/libahash-66e41c6e5122aadb.rmeta --extern aho_corasick=/playground/target/debug/deps/libaho_corasick-c6441250f4377f75.rmeta --extern ansi_term_0_11_0=/playground/target/debug/deps/libansi_term-120d85761b0feaf7.rmeta --extern ansi_term=/playground/target/debug/deps/libansi_term-ab35f8b11e59385a.rmeta --extern anyhow=/playground/target/debug/deps/libanyhow-179cdb76302d10b0.rmeta --extern approx=/playground/target/debug/deps/libapprox-190b3889ec54de9c.rmeta --extern arc_swap=/playground/target/debug/deps/libarc_swap-7b1a27cbfcae6908.rmeta --extern arrayvec=/playground/target/debug/deps/libarrayvec-ed5725d717896463.rmeta --extern async_trait=/playground/target/debug/deps/libasync_trait-9b53c0ce0d6bf428.so --extern atty=/playground/target/debug/deps/libatty-b32971181cd4632c.rmeta --extern autocfg=/playground/target/debug/deps/libautocfg-335ede5611a9b684.rmeta --extern backtrace=/playground/target/debug/deps/libbacktrace-038694a4f7fabb45.rmeta --extern base64=/playground/target/debug/deps/libbase64-c4895e085902010c.rmeta --extern bit_set=/playground/target/debug/deps/libbit_set-47a0d090fe1f7f69.rmeta --extern bit_vec=/playground/target/debug/deps/libbit_vec-d1b5bfc20fd2fdbc.rmeta --extern bitflags=/playground/target/debug/deps/libbitflags-a2155987696b8596.rmeta --extern block_buffer=/playground/target/debug/deps/libblock_buffer-cf569edb3edc0bc5.rmeta --extern bstr=/playground/target/debug/deps/libbstr-d6fef2b5ed7a6253.rmeta --extern bytemuck=/playground/target/debug/deps/libbytemuck-9cbbcec9795b0be3.rmeta --extern byteorder=/playground/target/debug/deps/libbyteorder-247b40861da05bec.rmeta --extern bytes=/playground/target/debug/deps/libbytes-fee841c20de076cb.rmeta --extern cc=/playground/target/debug/deps/libcc-14df8ee1f221c2e7.rmeta --extern cfg_if_0_1_10=/playground/target/debug/deps/libcfg_if-a42a72dabfa4a887.rmeta --extern cfg_if=/playground/target/debug/deps/libcfg_if-17db79e6160d9d60.rmeta --extern chrono=/playground/target/debug/deps/libchrono-3055731e32502d08.rmeta --extern clap=/playground/target/debug/deps/libclap-2d33e23686e77c52.rmeta --extern color_quant=/playground/target/debug/deps/libcolor_quant-18f74000246df249.rmeta --extern const_fn=/playground/target/debug/deps/libconst_fn-2fa43ad16cae7ca1.so --extern cpufeatures=/playground/target/debug/deps/libcpufeatures-83c3ca0f017c3e89.rmeta --extern crc32fast=/playground/target/debug/deps/libcrc32fast-11f74ee15174c644.rmeta --extern crossbeam=/playground/target/debug/deps/libcrossbeam-c6ea1577332ee86d.rmeta --extern crossbeam_channel=/playground/target/debug/deps/libcrossbeam_channel-cf2faca17e7aa8e0.rmeta --extern crossbeam_deque=/playground/target/debug/deps/libcrossbeam_deque-f4851f8a143ce40b.rmeta --extern crossbeam_epoch=/playground/target/debug/deps/libcrossbeam_epoch-28907527c93d5ffa.rmeta --extern crossbeam_queue=/playground/target/debug/deps/libcrossbeam_queue-508e25cb0c9b5c6e.rmeta --extern crossbeam_utils=/playground/target/debug/deps/libcrossbeam_utils-042ee9495f71bdfb.rmeta --extern crypto_mac=/playground/target/debug/deps/libcrypto_mac-c62c745d6784bc52.rmeta --extern csv=/playground/target/debug/deps/libcsv-a7bfd95643843dbe.rmeta --extern csv_core=/playground/target/debug/deps/libcsv_core-89157bb2fb151cdd.rmeta --extern data_encoding=/playground/target/debug/deps/libdata_encoding-5b6f22d0f4108c54.rmeta --extern deflate=/playground/target/debug/deps/libdeflate-e53f1b38507311f9.rmeta --extern derivative=/playground/target/debug/deps/libderivative-606320fe6b1cdefc.so --extern digest=/playground/target/debug/deps/libdigest-fb0e132aa354ba96.rmeta --extern dtoa=/playground/target/debug/deps/libdtoa-4c7fbf1ff0cbab74.rmeta --extern either=/playground/target/debug/deps/libeither-04371dfd35bf3584.rmeta --extern encoding_rs=/playground/target/debug/deps/libencoding_rs-1e774a9fa3beaffe.rmeta --extern env_logger=/playground/target/debug/deps/libenv_logger-e2cdfc5bfa4ca8d3.rmeta --extern error_chain=/playground/target/debug/deps/liberror_chain-210e48177c7db42f.rmeta --extern fallible_iterator=/playground/target/debug/deps/libfallible_iterator-ff9acd467715c624.rmeta --extern fallible_streaming_iterator=/playground/target/debug/deps/libfallible_streaming_iterator-af89121c1162058b.rmeta --extern filetime=/playground/target/debug/deps/libfiletime-3db6ab81dd6d75c0.rmeta --extern fixedbitset=/playground/target/debug/deps/libfixedbitset-7f130894b62c8660.rmeta --extern flate2=/playground/target/debug/deps/libflate2-2fdbab57365ff513.rmeta --extern fnv=/playground/target/debug/deps/libfnv-ae9dcfe01b70696a.rmeta --extern foreign_types=/playground/target/debug/deps/libforeign_types-35628d5e26d8374d.rmeta --extern foreign_types_shared=/playground/target/debug/deps/libforeign_types_shared-04972c5c102436b5.rmeta --extern form_urlencoded=/playground/target/debug/deps/libform_urlencoded-e91eb0906f17a107.rmeta --extern futf=/playground/target/debug/deps/libfutf-ab209591d3e97362.rmeta --extern futures=/playground/target/debug/deps/libfutures-3640da6c18eeac60.rmeta --extern futures_channel=/playground/target/debug/deps/libfutures_channel-697402c8a6d1b4d9.rmeta --extern futures_core=/playground/target/debug/deps/libfutures_core-91cc4549ca0472bf.rmeta --extern futures_executor=/playground/target/debug/deps/libfutures_executor-1919684d89f05f3b.rmeta --extern futures_io=/playground/target/debug/deps/libfutures_io-1c519c7af5f9be31.rmeta --extern futures_macro=/playground/target/debug/deps/libfutures_macro-98ca7b3d3a049c34.so --extern futures_sink=/playground/target/debug/deps/libfutures_sink-1ba616e92182ae88.rmeta --extern futures_task=/playground/target/debug/deps/libfutures_task-c10619735ffa0a4f.rmeta --extern futures_util=/playground/target/debug/deps/libfutures_util-8bb7d92340bb0033.rmeta --extern generic_array=/playground/target/debug/deps/libgeneric_array-ac53d730f67a9215.rmeta --extern getrandom_0_1_16=/playground/target/debug/deps/libgetrandom-dd734ec333646ec0.rmeta --extern getrandom=/playground/target/debug/deps/libgetrandom-953aad598d824cb7.rmeta --extern gif=/playground/target/debug/deps/libgif-5981fd6c37878d57.rmeta --extern gimli=/playground/target/debug/deps/libgimli-6cb0c61547c32c8f.rmeta --extern glob=/playground/target/debug/deps/libglob-8875c8c77f264e1f.rmeta --extern h2=/playground/target/debug/deps/libh2-04e37a8fa0f03808.rmeta --extern hashbrown_0_9_1=/playground/target/debug/deps/libhashbrown-b64880a240aa7322.rmeta --extern hashbrown=/playground/target/debug/deps/libhashbrown-4b9ac570b77fd59a.rmeta --extern hashlink=/playground/target/debug/deps/libhashlink-2df54f962698c5b5.rmeta --extern hmac=/playground/target/debug/deps/libhmac-6ca13de78761dcfa.rmeta --extern html5ever=/playground/target/debug/deps/libhtml5ever-fe07ebe884d52b30.rmeta --extern http=/playground/target/debug/deps/libhttp-6d4e9ea1f4436748.rmeta --extern http_body=/playground/target/debug/deps/libhttp_body-19f131530a31992a.rmeta --extern httparse=/playground/target/debug/deps/libhttparse-470041685c40f349.rmeta --extern httpdate=/playground/target/debug/deps/libhttpdate-3777d2580bf7b262.rmeta --extern humantime=/playground/target/debug/deps/libhumantime-2dac88ea32d7c5f9.rmeta --extern hyper=/playground/target/debug/deps/libhyper-269f946083df2091.rlib --extern hyper_tls=/playground/target/debug/deps/libhyper_tls-3cd96babba668b53.rmeta --extern idna=/playground/target/debug/deps/libidna-5189f56b88cf228a.rmeta --extern image=/playground/target/debug/deps/libimage-12c2fa3bf902c850.rmeta --extern indexmap=/playground/target/debug/deps/libindexmap-a16c9943b089e7da.rmeta --extern instant=/playground/target/debug/deps/libinstant-048283c91b125bac.rmeta --extern iovec=/playground/target/debug/deps/libiovec-20d7ac17ea53fe5d.rmeta --extern ipnet=/playground/target/debug/deps/libipnet-c9dd5fe28501a45f.rmeta --extern itertools=/playground/target/debug/deps/libitertools-83b02edb16ec9dc2.rmeta --extern itoa=/playground/target/debug/deps/libitoa-83e3755614d1c657.rmeta --extern jpeg_decoder=/playground/target/debug/deps/libjpeg_decoder-998a051a33d2a30b.rmeta --extern lazy_static=/playground/target/debug/deps/liblazy_static-735e050bd0c7e24f.rmeta --extern libc=/playground/target/debug/deps/liblibc-1995c28b8f2b0962.rmeta --extern libm=/playground/target/debug/deps/liblibm-cea705af515fc7b9.rmeta --extern libsqlite3_sys=/playground/target/debug/deps/liblibsqlite3_sys-aa8be5e8db948cf1.rmeta --extern linked_hash_map=/playground/target/debug/deps/liblinked_hash_map-de04d3a5c1d34737.rmeta --extern lock_api=/playground/target/debug/deps/liblock_api-ac13900cead869b4.rmeta --extern log=/playground/target/debug/deps/liblog-408df375a9649a3b.rmeta --extern log_mdc=/playground/target/debug/deps/liblog_mdc-99e505949276356c.rmeta --extern log4rs=/playground/target/debug/deps/liblog4rs-fc0ad27b59678119.rmeta --extern mac=/playground/target/debug/deps/libmac-e654eafe9d5122d7.rmeta --extern markup5ever=/playground/target/debug/deps/libmarkup5ever-5d4403d9e0000b42.rmeta --extern markup5ever_rcdom=/playground/target/debug/deps/libmarkup5ever_rcdom-83574fb059ebb9e9.rmeta --extern matches=/playground/target/debug/deps/libmatches-bd6291e3e71f7f58.rmeta --extern matrixmultiply=/playground/target/debug/deps/libmatrixmultiply-2815ae7c5268c707.rmeta --extern md5=/playground/target/debug/deps/libmd5-c688bc3f2ad8e1bf.rmeta --extern memchr=/playground/target/debug/deps/libmemchr-303ba0c6b7f69fdd.rmeta --extern memmap=/playground/target/debug/deps/libmemmap-75637b8d7b752bb8.rmeta --extern memoffset=/playground/target/debug/deps/libmemoffset-7bc0aaefb961dea4.rmeta --extern mime=/playground/target/debug/deps/libmime-b10d8882042d97b0.rmeta --extern miniz_oxide_0_3_7=/playground/target/debug/deps/libminiz_oxide-1d1d3f7f4239ae4c.rmeta --extern miniz_oxide=/playground/target/debug/deps/libminiz_oxide-e797ff84e041dd1b.rmeta --extern mio=/playground/target/debug/deps/libmio-4bc38476a11e445d.rmeta --extern nalgebra=/playground/target/debug/deps/libnalgebra-497ec3171c8a4d1d.rmeta --extern native_tls=/playground/target/debug/deps/libnative_tls-9894440be1f722c7.rmeta --extern ndarray=/playground/target/debug/deps/libndarray-9fb34296dc561b08.rmeta --extern net2=/playground/target/debug/deps/libnet2-e701ad3c61b0b028.rmeta --extern debug_unreachable=/playground/target/debug/deps/libdebug_unreachable-b62bf2bc851953e4.rmeta --extern num=/playground/target/debug/deps/libnum-310bd912008768ec.rmeta --extern num_bigint=/playground/target/debug/deps/libnum_bigint-f29aaa9fd78cd487.rmeta --extern num_complex_0_3_1=/playground/target/debug/deps/libnum_complex-980527fb46f49d6c.rmeta --extern num_complex=/playground/target/debug/deps/libnum_complex-c5a2adc8136581d0.rmeta --extern num_integer=/playground/target/debug/deps/libnum_integer-ef83eb595093d5c1.rmeta --extern num_iter=/playground/target/debug/deps/libnum_iter-26ef1d7d168b78fc.rmeta --extern num_rational_0_3_2=/playground/target/debug/deps/libnum_rational-7cc1ce30694fb776.rmeta --extern num_rational=/playground/target/debug/deps/libnum_rational-4f68421956e44075.rmeta --extern num_traits=/playground/target/debug/deps/libnum_traits-29185bbab3bdb97e.rmeta --extern num_cpus=/playground/target/debug/deps/libnum_cpus-5b99b8fc9a28fdc5.rmeta --extern object=/playground/target/debug/deps/libobject-b93a28bf81b69015.rmeta --extern once_cell=/playground/target/debug/deps/libonce_cell-17eb46c299237e16.rmeta --extern opaque_debug=/playground/target/debug/deps/libopaque_debug-0572f128331f44db.rmeta --extern openssl=/playground/target/debug/deps/libopenssl-efb98e29b5e5fba2.rmeta --extern openssl_probe=/playground/target/debug/deps/libopenssl_probe-686a8228f73d5587.rmeta --extern openssl_sys=/playground/target/debug/deps/libopenssl_sys-4045b399e7cdf3d3.rmeta --extern ordered_float=/playground/target/debug/deps/libordered_float-019dfbabae12313c.rmeta --extern parking_lot=/playground/target/debug/deps/libparking_lot-fbc04678a689e37a.rmeta --extern parking_lot_core=/playground/target/debug/deps/libparking_lot_core-4b82bbd1f7f9b70f.rmeta --extern paste=/playground/target/debug/deps/libpaste-00233cab4e8b72fc.so --extern percent_encoding=/playground/target/debug/deps/libpercent_encoding-6b4a80c4029ee4a3.rmeta --extern pest=/playground/target/debug/deps/libpest-921bca10ad4500d5.rmeta --extern petgraph=/playground/target/debug/deps/libpetgraph-062a231d714bf404.rmeta --extern phf=/playground/target/debug/deps/libphf-229c542ba338a49b.rmeta --extern phf_codegen=/playground/target/debug/deps/libphf_codegen-bdb4f021da5a033f.rmeta --extern phf_generator=/playground/target/debug/deps/libphf_generator-3536c6b907b70097.rmeta --extern phf_shared=/playground/target/debug/deps/libphf_shared-2a85a3479f3e9d7c.rmeta --extern pin_project=/playground/target/debug/deps/libpin_project-f77941bfb3338770.rmeta --extern pin_project_internal=/playground/target/debug/deps/libpin_project_internal-4dac01d9f797bd58.so --extern pin_project_lite=/playground/target/debug/deps/libpin_project_lite-4aca7f5ab6899e96.rmeta --extern pin_utils=/playground/target/debug/deps/libpin_utils-dd2961d584c22a9f.rmeta --extern pkg_config=/playground/target/debug/deps/libpkg_config-562f800da154de92.rmeta --extern png=/playground/target/debug/deps/libpng-cea4ce28892beca3.rmeta --extern postgres=/playground/target/debug/deps/libpostgres-0dbfa21c851ef125.rmeta --extern postgres_protocol=/playground/target/debug/deps/libpostgres_protocol-dc84516331d375dc.rmeta --extern postgres_types=/playground/target/debug/deps/libpostgres_types-d9c2dce66b67e3f4.rmeta --extern ppv_lite86=/playground/target/debug/deps/libppv_lite86-e926ed38ecbba29b.rmeta --extern precomputed_hash=/playground/target/debug/deps/libprecomputed_hash-c6d01971a34f5807.rmeta --extern proc_macro_hack=/playground/target/debug/deps/libproc_macro_hack-1fe68e267e98fed1.so --extern proc_macro_nested=/playground/target/debug/deps/libproc_macro_nested-c3e0e2e0e50d9cf6.rmeta --extern proc_macro2=/playground/target/debug/deps/libproc_macro2-171d29b015a25fed.rmeta --extern quick_error=/playground/target/debug/deps/libquick_error-73bf4d47b8e0946f.rmeta --extern quote=/playground/target/debug/deps/libquote-28f6da0b487d7867.rmeta --extern rand_0_7_3=/playground/target/debug/deps/librand-4bc4fa282dff2114.rmeta --extern rand=/playground/target/debug/deps/librand-57e804266b74ff6d.rmeta --extern rand_chacha_0_2_2=/playground/target/debug/deps/librand_chacha-b8619118511a1def.rmeta --extern rand_chacha=/playground/target/debug/deps/librand_chacha-fec8269fa383021e.rmeta --extern rand_core_0_5_1=/playground/target/debug/deps/librand_core-b7dc4e0d18959f21.rmeta --extern rand_core=/playground/target/debug/deps/librand_core-90c42f306c0a67c6.rmeta --extern rand_distr=/playground/target/debug/deps/librand_distr-fd8a48ab1041ab25.rmeta --extern rand_hc=/playground/target/debug/deps/librand_hc-184f8043827622bb.rmeta --extern rand_pcg=/playground/target/debug/deps/librand_pcg-c02b643b3c706d6d.rmeta --extern rawpointer=/playground/target/debug/deps/librawpointer-80c34ebe31e8881e.rmeta --extern rayon=/playground/target/debug/deps/librayon-efa02685d840aaa2.rmeta --extern rayon_core=/playground/target/debug/deps/librayon_core-47767e9c1bb1e123.rmeta --extern regex=/playground/target/debug/deps/libregex-a743d6793e59d4c0.rmeta --extern regex_automata=/playground/target/debug/deps/libregex_automata-02b61cebf24eb8c0.rmeta --extern regex_syntax=/playground/target/debug/deps/libregex_syntax-a3684af575b07253.rmeta --extern remove_dir_all=/playground/target/debug/deps/libremove_dir_all-5c0a87a169460981.rmeta --extern reqwest=/playground/target/debug/deps/libreqwest-eddd8d69dcb85115.rmeta --extern ring=/playground/target/debug/deps/libring-309f803389994ae1.rmeta --extern rusqlite=/playground/target/debug/deps/librusqlite-f61ee64936c66008.rmeta --extern rustc_demangle=/playground/target/debug/deps/librustc_demangle-9c9497fccfbeb6f4.rmeta --extern rustc_version=/playground/target/debug/deps/librustc_version-75e8a0114436076c.rmeta --extern ryu=/playground/target/debug/deps/libryu-fc722432573e8d7d.rmeta --extern same_file=/playground/target/debug/deps/libsame_file-aeaece771fe5a4c2.rmeta --extern scoped_threadpool=/playground/target/debug/deps/libscoped_threadpool-c6d356f1e1f61de2.rmeta --extern scopeguard=/playground/target/debug/deps/libscopeguard-a0d059c36fcc038c.rmeta --extern select=/playground/target/debug/deps/libselect-ff6802aec982cf06.rmeta --extern semver_0_11_0=/playground/target/debug/deps/libsemver-a62cee498f3c98c6.rmeta --extern semver=/playground/target/debug/deps/libsemver-89ee22c77159f823.rmeta --extern semver_parser=/playground/target/debug/deps/libsemver_parser-f4ec13d2daacd2c2.rmeta --extern serde=/playground/target/debug/deps/libserde-3be3aabe22700213.rmeta --extern serde_value=/playground/target/debug/deps/libserde_value-1c51d967072b1146.rmeta --extern serde_derive=/playground/target/debug/deps/libserde_derive-c418fc817a4e665f.so --extern serde_json=/playground/target/debug/deps/libserde_json-11ef87148e2682c3.rmeta --extern serde_urlencoded=/playground/target/debug/deps/libserde_urlencoded-4801cebf46d8a639.rmeta --extern serde_yaml=/playground/target/debug/deps/libserde_yaml-8e97ddd36fcbdb88.rmeta --extern sha2=/playground/target/debug/deps/libsha2-480edd035d499151.rmeta --extern simba=/playground/target/debug/deps/libsimba-5ad51f737fc567e7.rmeta --extern siphasher=/playground/target/debug/deps/libsiphasher-0b689d4e61ff3bad.rmeta --extern slab=/playground/target/debug/deps/libslab-8360eda8f600df05.rmeta --extern smallvec=/playground/target/debug/deps/libsmallvec-9e48c7819f40ec21.rmeta --extern smawk=/playground/target/debug/deps/libsmawk-8e38b6e5a5778769.rmeta --extern socket2=/playground/target/debug/deps/libsocket2-0838fcc7aeaf3135.rmeta --extern spin=/playground/target/debug/deps/libspin-459161897768fba8.rmeta --extern standback=/playground/target/debug/deps/libstandback-766c95787038fe25.rmeta --extern string_cache=/playground/target/debug/deps/libstring_cache-bbb6e0d504d96d08.rmeta --extern string_cache_codegen=/playground/target/debug/deps/libstring_cache_codegen-7d8e96147bf05d1b.rmeta --extern stringprep=/playground/target/debug/deps/libstringprep-28c2833df3cff0ef.rmeta --extern strsim_0_8_0=/playground/target/debug/deps/libstrsim-1094d6105a6b9102.rmeta --extern strsim=/playground/target/debug/deps/libstrsim-596fcd52b29ab067.rmeta --extern subtle=/playground/target/debug/deps/libsubtle-9abff15ff12775b5.rmeta --extern syn=/playground/target/debug/deps/libsyn-9d9f6aef6969da15.rmeta --extern synstructure=/playground/target/debug/deps/libsynstructure-7579161d5937eb71.rmeta --extern tar=/playground/target/debug/deps/libtar-5b795d685e9295e6.rmeta --extern tempfile=/playground/target/debug/deps/libtempfile-a887fbeb3c565c67.rmeta --extern tendril=/playground/target/debug/deps/libtendril-0de8141ddc771892.rmeta --extern termcolor=/playground/target/debug/deps/libtermcolor-46403bcbadff7ce9.rmeta --extern textwrap_0_11_0=/playground/target/debug/deps/libtextwrap-34d11634d35d2890.rmeta --extern textwrap=/playground/target/debug/deps/libtextwrap-9cac5c85790b3b1f.rmeta --extern thiserror=/playground/target/debug/deps/libthiserror-385b7d90f4c0e299.rmeta --extern thiserror_impl=/playground/target/debug/deps/libthiserror_impl-a1ce8d13d7bf50de.so --extern thread_id=/playground/target/debug/deps/libthread_id-7fe87ffdec07bebf.rmeta --extern thread_local=/playground/target/debug/deps/libthread_local-c41cf3494ad4d6ea.rmeta --extern threadpool=/playground/target/debug/deps/libthreadpool-1caecdbf14adddfa.rmeta --extern tiff=/playground/target/debug/deps/libtiff-1cd50ca84da2362a.rmeta --extern time_0_1_44=/playground/target/debug/deps/libtime-7db81ef2db6e706c.rmeta --extern time=/playground/target/debug/deps/libtime-469cbffb33911a86.rmeta --extern time_macros=/playground/target/debug/deps/libtime_macros-e01e99c658446be3.rmeta --extern time_macros_impl=/playground/target/debug/deps/libtime_macros_impl-056a36a6471c9fcb.so --extern tinyvec=/playground/target/debug/deps/libtinyvec-d5d38abfbdb27dc7.rmeta --extern tinyvec_macros=/playground/target/debug/deps/libtinyvec_macros-81d45e7b064eddd1.rmeta --extern tokio=/playground/target/debug/deps/libtokio-89dc1aacc690db7f.rmeta --extern tokio_native_tls=/playground/target/debug/deps/libtokio_native_tls-ee3ddcd438ed4095.rmeta --extern tokio_postgres=/playground/target/debug/deps/libtokio_postgres-0c92c5709bbf800a.rmeta --extern tokio_util=/playground/target/debug/deps/libtokio_util-46bc61a788a4663b.rmeta --extern toml=/playground/target/debug/deps/libtoml-f8a3e338d8b2ec8c.rmeta --extern tower_service=/playground/target/debug/deps/libtower_service-81097ae8f3ca822e.rmeta --extern tracing=/playground/target/debug/deps/libtracing-131dd695f9a3faa0.rmeta --extern tracing_core=/playground/target/debug/deps/libtracing_core-fb9824e74e5fe1d0.rmeta --extern traitobject=/playground/target/debug/deps/libtraitobject-65b44d6642786d87.rmeta --extern try_lock=/playground/target/debug/deps/libtry_lock-e4ac6437db956571.rmeta --extern typemap=/playground/target/debug/deps/libtypemap-ac1698b586ce6597.rmeta --extern typenum=/playground/target/debug/deps/libtypenum-9e7e9f850d4382a6.rmeta --extern ucd_trie=/playground/target/debug/deps/libucd_trie-45ec7daed9838d32.rmeta --extern unicase=/playground/target/debug/deps/libunicase-101756c05806db13.rmeta --extern unicode_bidi=/playground/target/debug/deps/libunicode_bidi-3139b89156d0786c.rmeta --extern unicode_normalization=/playground/target/debug/deps/libunicode_normalization-9e911e4edf677bf4.rmeta --extern unicode_segmentation=/playground/target/debug/deps/libunicode_segmentation-7eaecf846a4a004b.rmeta --extern unicode_width=/playground/target/debug/deps/libunicode_width-44d374a05dce6145.rmeta --extern unicode_xid=/playground/target/debug/deps/libunicode_xid-b18ccd133c106cd2.rmeta --extern unsafe_any=/playground/target/debug/deps/libunsafe_any-fbd575c915548e61.rmeta --extern untrusted=/playground/target/debug/deps/libuntrusted-524f673fcd7df21f.rmeta --extern url=/playground/target/debug/deps/liburl-273ff0298e451cf3.rmeta --extern utf8=/playground/target/debug/deps/libutf8-03bfb833d07e7ce7.rmeta --extern uuid=/playground/target/debug/deps/libuuid-6b01ff66b69be148.rmeta --extern vec_map=/playground/target/debug/deps/libvec_map-3e0d68bb2400498e.rmeta --extern version_check=/playground/target/debug/deps/libversion_check-8621e40e791d7e0b.rmeta --extern walkdir=/playground/target/debug/deps/libwalkdir-9288cdb139d035e8.rmeta --extern want=/playground/target/debug/deps/libwant-c21a0912f1e5429f.rmeta --extern weezl=/playground/target/debug/deps/libweezl-ef532351b91f45d8.rmeta --extern winapi=/playground/target/debug/deps/libwinapi-769de98f80380deb.rmeta --extern xattr=/playground/target/debug/deps/libxattr-31db13a661348bef.rmeta --extern xml5ever=/playground/target/debug/deps/libxml5ever-b1f2a27a4cf21995.rmeta --extern yaml_rust=/playground/target/debug/deps/libyaml_rust-bcd6d9b5400b9c0e.rmeta -L native=/playground/target/debug/build/libsqlite3-sys-a91e742d94f16749/out -L native=/playground/target/debug/build/ring-8241b1316fef72ea/out` (signal: 4, SIGILL: illegal instruction)
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
Compiling playground v0.0.1 (/playground)
error: internal compiler error: compiler/rustc_middle/src/ty/fold.rs:829:17: Trying to collect bound vars with a bound region: DebruijnIndex(0) BoundRegion { var: 0, kind: BrAnon(0) }

thread 'rustc' panicked at 'Box<Any>', compiler/rustc_errors/src/lib.rs:1005:9
stack backtrace:
   0: std::panicking::begin_panic
   1: std::panic::panic_any
   2: rustc_errors::HandlerInner::bug
   3: rustc_errors::Handler::bug
   4: rustc_middle::ty::context::tls::with_opt
   5: rustc_middle::util::bug::opt_span_bug_fmt
   6: rustc_middle::util::bug::bug_fmt
   7: <rustc_middle::ty::fold::BoundVarsCollector as rustc_middle::ty::fold::TypeVisitor>::visit_ty
   8: rustc_middle::ty::sty::Binder<T>::bind
   9: rustc_ty_utils::instance::inner_resolve_instance
  10: rustc_ty_utils::instance::resolve_instance
  11: rustc_query_impl::<impl rustc_query_system::query::config::QueryAccessors<rustc_query_impl::plumbing::QueryCtxt> for rustc_query_impl::queries::resolve_instance>::compute
  12: rustc_query_system::query::plumbing::get_query_impl
  13: <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::resolve_instance
  14: rustc_middle::ty::instance::Instance::resolve_opt_const_arg
  15: rustc_middle::mir::interpret::queries::<impl rustc_middle::ty::context::TyCtxt>::const_eval_resolve
  16: <rustc_trait_selection::traits::query::normalize::QueryNormalizer as rustc_middle::ty::fold::TypeFolder>::fold_const
  17: <rustc_trait_selection::traits::query::normalize::QueryNormalizer as rustc_middle::ty::fold::TypeFolder>::fold_mir_const
  18: <rustc_infer::infer::at::At as rustc_trait_selection::traits::query::normalize::AtExt>::normalize
  19: rustc_infer::infer::InferCtxtBuilder::enter
  20: core::ops::function::FnOnce::call_once
  21: rustc_query_impl::<impl rustc_query_system::query::config::QueryAccessors<rustc_query_impl::plumbing::QueryCtxt> for rustc_query_impl::queries::normalize_mir_const_after_erasing_regions>::compute
  22: rustc_query_system::query::plumbing::get_query_impl
  23: <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::normalize_mir_const_after_erasing_regions
  24: rustc_middle::ty::normalize_erasing_regions::<impl rustc_middle::ty::context::TyCtxt>::normalize_erasing_regions
  25: rustc_mir::interpret::eval_context::InterpCx<M>::push_stack_frame
  26: rustc_mir::interpret::terminator::<impl rustc_mir::interpret::eval_context::InterpCx<M>>::eval_fn_call
  27: rustc_mir::interpret::step::<impl rustc_mir::interpret::eval_context::InterpCx<M>>::run
  28: rustc_mir::const_eval::eval_queries::eval_to_allocation_raw_provider
  29: rustc_query_impl::<impl rustc_query_system::query::config::QueryAccessors<rustc_query_impl::plumbing::QueryCtxt> for rustc_query_impl::queries::eval_to_allocation_raw>::compute
  30: rustc_query_system::query::plumbing::get_query_impl
  31: <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::eval_to_allocation_raw
  32: rustc_mir::const_eval::eval_queries::eval_to_const_value_raw_provider
  33: rustc_query_impl::<impl rustc_query_system::query::config::QueryAccessors<rustc_query_impl::plumbing::QueryCtxt> for rustc_query_impl::queries::eval_to_const_value_raw>::compute
  34: rustc_query_system::query::plumbing::get_query_impl
  35: <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::eval_to_const_value_raw
  36: rustc_middle::mir::interpret::queries::<impl rustc_middle::ty::context::TyCtxt>::const_eval_global_id
  37: rustc_middle::mir::interpret::queries::<impl rustc_middle::ty::context::TyCtxt>::const_eval_resolve
  38: rustc_infer::infer::InferCtxt::const_eval_resolve
  39: rustc_trait_selection::traits::fulfill::FulfillProcessor::progress_changed_obligations::{{closure}}
  40: rustc_trait_selection::traits::fulfill::FulfillProcessor::progress_changed_obligations
  41: rustc_data_structures::obligation_forest::ObligationForest<O>::process_obligations
  42: <rustc_trait_selection::traits::fulfill::FulfillmentContext as rustc_infer::traits::engine::TraitEngine>::select_where_possible
  43: rustc_typeck::check::fn_ctxt::checks::<impl rustc_typeck::check::fn_ctxt::FnCtxt>::check_argument_types
  44: rustc_typeck::check::callee::<impl rustc_typeck::check::fn_ctxt::FnCtxt>::confirm_builtin_call
  45: rustc_typeck::check::callee::<impl rustc_typeck::check::fn_ctxt::FnCtxt>::check_call
  46: rustc_typeck::check::expr::<impl rustc_typeck::check::fn_ctxt::FnCtxt>::check_expr_kind
  47: rustc_typeck::check::expr::<impl rustc_typeck::check::fn_ctxt::FnCtxt>::check_expr_with_expectation
  48: rustc_typeck::check::fn_ctxt::checks::<impl rustc_typeck::check::fn_ctxt::FnCtxt>::check_stmt
  49: rustc_typeck::check::fn_ctxt::checks::<impl rustc_typeck::check::fn_ctxt::FnCtxt>::check_block_with_expected
  50: rustc_typeck::check::expr::<impl rustc_typeck::check::fn_ctxt::FnCtxt>::check_expr_with_expectation
  51: rustc_typeck::check::expr::<impl rustc_typeck::check::fn_ctxt::FnCtxt>::check_return_expr
  52: rustc_typeck::check::check::check_fn
  53: rustc_typeck::check::inherited::InheritedBuilder::enter
  54: rustc_typeck::check::typeck
  55: rustc_query_system::query::plumbing::get_query_impl
  56: <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::typeck
  57: rustc_middle::ty::<impl rustc_middle::ty::context::TyCtxt>::par_body_owners
  58: rustc_typeck::check::typeck_item_bodies
  59: rustc_query_system::query::plumbing::get_query_impl
  60: <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::typeck_item_bodies
  61: rustc_session::utils::<impl rustc_session::session::Session>::time
  62: rustc_typeck::check_crate
  63: rustc_interface::passes::analysis
  64: rustc_query_system::query::plumbing::get_query_impl
  65: <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::analysis
  66: rustc_interface::passes::QueryContext::enter
  67: rustc_interface::queries::<impl rustc_interface::interface::Compiler>::enter
  68: rustc_span::with_source_map
  69: scoped_tls::ScopedKey<T>::set
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.54.0-nightly (c1e8f3a58 2021-05-30) running on x86_64-unknown-linux-gnu

note: compiler flags: -C embed-bitcode=no -C codegen-units=1 -C debuginfo=2 --crate-type lib

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
thread 'rustc' panicked at 'substs of instance DefId(0:10 ~ playground[4a2c]::_Contains::does_contain) not normalized for codegen: [FileCap<FileOp::Write, FileResource::StaticPath("foobar")>, &C]', compiler/rustc_middle/src/ty/instance.rs:285:9
stack backtrace:
   0:     0x7f2cafb83f80 - std::backtrace_rs::backtrace::libunwind::trace::h1a39bd9a98540471
                               at /rustc/c1e8f3a5857c3c8d095fd212acc6ed442f4cc58b/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
   1:     0x7f2cafb83f80 - std::backtrace_rs::backtrace::trace_unsynchronized::h21a1eeae7103ab3f
                               at /rustc/c1e8f3a5857c3c8d095fd212acc6ed442f4cc58b/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7f2cafb83f80 - std::sys_common::backtrace::_print_fmt::hc9ffbae9ed6a9871
                               at /rustc/c1e8f3a5857c3c8d095fd212acc6ed442f4cc58b/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x7f2cafb83f80 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h17510753a34a3f09
                               at /rustc/c1e8f3a5857c3c8d095fd212acc6ed442f4cc58b/library/std/src/sys_common/backtrace.rs:46:22
   4:     0x7f2cafbf19ac - core::fmt::write::h1e5a1f350e43b10f
                               at /rustc/c1e8f3a5857c3c8d095fd212acc6ed442f4cc58b/library/core/src/fmt/mod.rs:1110:17
   5:     0x7f2cafb75805 - std::io::Write::write_fmt::h06ec27c6d028baf1
                               at /rustc/c1e8f3a5857c3c8d095fd212acc6ed442f4cc58b/library/std/src/io/mod.rs:1588:15
   6:     0x7f2cafb87ddb - std::sys_common::backtrace::_print::h1a02603349b1dc60
                               at /rustc/c1e8f3a5857c3c8d095fd212acc6ed442f4cc58b/library/std/src/sys_common/backtrace.rs:49:5
   7:     0x7f2cafb87ddb - std::sys_common::backtrace::print::h0fc317d31c48cd9b
                               at /rustc/c1e8f3a5857c3c8d095fd212acc6ed442f4cc58b/library/std/src/sys_common/backtrace.rs:36:9
   8:     0x7f2cafb87ddb - std::panicking::default_hook::{{closure}}::ha522601c22d7057b
                               at /rustc/c1e8f3a5857c3c8d095fd212acc6ed442f4cc58b/library/std/src/panicking.rs:208:50
   9:     0x7f2cafb878b1 - std::panicking::default_hook::hd50ab173af9a3ce8
                               at /rustc/c1e8f3a5857c3c8d095fd212acc6ed442f4cc58b/library/std/src/panicking.rs:225:9
  10:     0x7f2cb03589bd - rustc_driver::report_ice::h0bbc0ae77d597594
  11:     0x7f2cafb885e6 - std::panicking::rust_panic_with_hook::hb5a01416e02405ad
                               at /rustc/c1e8f3a5857c3c8d095fd212acc6ed442f4cc58b/library/std/src/panicking.rs:626:17
  12:     0x7f2cafb880c7 - std::panicking::begin_panic_handler::{{closure}}::hf1dda5d5c0706ee0
                               at /rustc/c1e8f3a5857c3c8d095fd212acc6ed442f4cc58b/library/std/src/panicking.rs:519:13
  13:     0x7f2cafb8445c - std::sys_common::backtrace::__rust_end_short_backtrace::h56c02e9609085b17
                               at /rustc/c1e8f3a5857c3c8d095fd212acc6ed442f4cc58b/library/std/src/sys_common/backtrace.rs:141:18
  14:     0x7f2cafb88029 - rust_begin_unwind
                               at /rustc/c1e8f3a5857c3c8d095fd212acc6ed442f4cc58b/library/std/src/panicking.rs:515:5
  15:     0x7f2cafb50eeb - std::panicking::begin_panic_fmt::h5889dddec113b3e8
                               at /rustc/c1e8f3a5857c3c8d095fd212acc6ed442f4cc58b/library/std/src/panicking.rs:457:5
  16:     0x7f2cb1dc9223 - rustc_middle::ty::instance::Instance::new::h138b137268683e1e
  17:     0x7f2cb0907205 - std::thread::local::LocalKey<T>::with::h5d9224abdd7920e1
  18:     0x7f2cb090d8b4 - std::thread::local::LocalKey<T>::with::h98ac41cac71185c2
  19:     0x7f2cb093dcde - rustc_query_impl::make_query::resolve_instance::h6c2db3b7c4731c32
  20:     0x7f2cb087d4dd - rustc_query_system::query::plumbing::QueryState<D,K>::try_collect_active_jobs::h8d3183294409f20d
  21:     0x7f2cb09567da - rustc_query_impl::Queries::try_collect_active_jobs::h804da0378b7580b3
  22:     0x7f2cb0a86ad7 - rustc_query_system::query::job::print_query_stack::hd56f847aa29e3347
  23:     0x7f2cb0406637 - rustc_interface::interface::try_print_query_stack::hcd178fe26145ef9d
  24:     0x7f2cb0358d6d - rustc_driver::report_ice::h0bbc0ae77d597594
  25:     0x7f2cafb885e6 - std::panicking::rust_panic_with_hook::hb5a01416e02405ad
                               at /rustc/c1e8f3a5857c3c8d095fd212acc6ed442f4cc58b/library/std/src/panicking.rs:626:17
  26:     0x7f2cb133093b - std::panicking::begin_panic::{{closure}}::h79be31a52b7554ed
  27:     0x7f2cb13308f6 - std::sys_common::backtrace::__rust_end_short_backtrace::h0d6d6b53a98843e6
  28:     0x7f2cb13320cf - std::panicking::begin_panic::h1d412c1e7c1dec3c
  29:     0x7f2cb1349a3d - std::panic::panic_any::h427710dcb10bbe92
  30:     0x7f2cb134c93a - rustc_errors::HandlerInner::bug::h54fd3663069746c7
  31:     0x7f2cb134c3e0 - rustc_errors::Handler::bug::h6fd29773c2809aef
  32:     0x7f2cb129b8e0 - rustc_middle::ty::context::tls::with_opt::h5d93e51ac4f84952
  33:     0x7f2cb129ed40 - rustc_middle::util::bug::opt_span_bug_fmt::h73ef8867dd647d6e
  34:     0x7f2cb129ecb6 - rustc_middle::util::bug::bug_fmt::h5eaf5bea31bbe7e0
  35:     0x7f2cb1df0e70 - <rustc_middle::ty::fold::BoundVarsCollector as rustc_middle::ty::fold::TypeVisitor>::visit_ty::h6514ebe90c448cdd
  36:     0x7f2cb165a986 - rustc_middle::ty::sty::Binder<T>::bind::h50c53be3fc93c400
  37:     0x7f2cb1657fcb - rustc_ty_utils::instance::inner_resolve_instance::h2ee186f9093bf7d7
  38:     0x7f2cb1657227 - rustc_ty_utils::instance::resolve_instance::h452e351b7015c1e3
  39:     0x7f2cb176b513 - rustc_query_impl::<impl rustc_query_system::query::config::QueryAccessors<rustc_query_impl::plumbing::QueryCtxt> for rustc_query_impl::queries::resolve_instance>::compute::h3a414191b883d966
  40:     0x7f2cb17562b8 - rustc_query_system::query::plumbing::get_query_impl::hf75519e5cd807995
  41:     0x7f2cb1795e2d - <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::resolve_instance::h82667371ba59cd83
  42:     0x7f2cb1dcaffd - rustc_middle::ty::instance::Instance::resolve_opt_const_arg::ha0925e4a88f592f8
  43:     0x7f2cb1d8331a - rustc_middle::mir::interpret::queries::<impl rustc_middle::ty::context::TyCtxt>::const_eval_resolve::h05ad8dfc76427d5b
  44:     0x7f2cb1c85570 - <rustc_trait_selection::traits::query::normalize::QueryNormalizer as rustc_middle::ty::fold::TypeFolder>::fold_const::h1a2b3db3741ddf78
  45:     0x7f2cb2664151 - <rustc_trait_selection::traits::query::normalize::QueryNormalizer as rustc_middle::ty::fold::TypeFolder>::fold_mir_const::hc529b8661d679324
  46:     0x7f2cb20240f7 - <rustc_infer::infer::at::At as rustc_trait_selection::traits::query::normalize::AtExt>::normalize::hbb82211ffd579d79
  47:     0x7f2cb2016f21 - rustc_infer::infer::InferCtxtBuilder::enter::h2d501578ee6c38b9
  48:     0x7f2cb2023c32 - core::ops::function::FnOnce::call_once::h67853e98b8f1ca08
  49:     0x7f2cb227d0a8 - rustc_query_impl::<impl rustc_query_system::query::config::QueryAccessors<rustc_query_impl::plumbing::QueryCtxt> for rustc_query_impl::queries::normalize_mir_const_after_erasing_regions>::compute::h013cf6812c6dfcde
  50:     0x7f2cb221b2a4 - rustc_query_system::query::plumbing::get_query_impl::hd0fdeba8daa0e895
  51:     0x7f2cb22afb39 - <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::normalize_mir_const_after_erasing_regions::hef60be0778070bfa
  52:     0x7f2cb19eb0ed - rustc_middle::ty::normalize_erasing_regions::<impl rustc_middle::ty::context::TyCtxt>::normalize_erasing_regions::h8cd5a629f411350d
  53:     0x7f2cb19c45d0 - rustc_mir::interpret::eval_context::InterpCx<M>::push_stack_frame::hb4d3d6e60f56f2cd
  54:     0x7f2cb19e57ff - rustc_mir::interpret::terminator::<impl rustc_mir::interpret::eval_context::InterpCx<M>>::eval_fn_call::h18df32d0a18b92f7
  55:     0x7f2cb19d7dfb - rustc_mir::interpret::step::<impl rustc_mir::interpret::eval_context::InterpCx<M>>::run::h578d68801dae73c8
  56:     0x7f2cb18e0770 - rustc_mir::const_eval::eval_queries::eval_to_allocation_raw_provider::hc342a5cc80315017
  57:     0x7f2cb176aefd - rustc_query_impl::<impl rustc_query_system::query::config::QueryAccessors<rustc_query_impl::plumbing::QueryCtxt> for rustc_query_impl::queries::eval_to_allocation_raw>::compute::h50f34bc5c1b84fb8
  58:     0x7f2cb173bc64 - rustc_query_system::query::plumbing::get_query_impl::h82efa1836f4eb10a
  59:     0x7f2cb1793df7 - <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::eval_to_allocation_raw::h2b3ca26d4a0bfe39
  60:     0x7f2cb18df1aa - rustc_mir::const_eval::eval_queries::eval_to_const_value_raw_provider::h492a1f0908ef1033
  61:     0x7f2cb176af3d - rustc_query_impl::<impl rustc_query_system::query::config::QueryAccessors<rustc_query_impl::plumbing::QueryCtxt> for rustc_query_impl::queries::eval_to_const_value_raw>::compute::hf332c6ae6cc62cca
  62:     0x7f2cb17446e5 - rustc_query_system::query::plumbing::get_query_impl::ha84d8dc8b8f75ed2
  63:     0x7f2cb1793f17 - <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::eval_to_const_value_raw::h46d27616aa3d4e98
  64:     0x7f2cb1d6c684 - rustc_middle::mir::interpret::queries::<impl rustc_middle::ty::context::TyCtxt>::const_eval_global_id::h5b31d85c4aaa4700
  65:     0x7f2cb1d8335d - rustc_middle::mir::interpret::queries::<impl rustc_middle::ty::context::TyCtxt>::const_eval_resolve::h05ad8dfc76427d5b
  66:     0x7f2cb26a0056 - rustc_infer::infer::InferCtxt::const_eval_resolve::h8853853f26ced4a7
  67:     0x7f2cb1085449 - rustc_trait_selection::traits::fulfill::FulfillProcessor::progress_changed_obligations::{{closure}}::h31242c7bb950182e
  68:     0x7f2cb1c848d9 - rustc_trait_selection::traits::fulfill::FulfillProcessor::progress_changed_obligations::he0b9099f8a0ebc6e
  69:     0x7f2cb1c9f47f - rustc_data_structures::obligation_forest::ObligationForest<O>::process_obligations::h85e16c4356ccd540
  70:     0x7f2cb1c83c7b - <rustc_trait_selection::traits::fulfill::FulfillmentContext as rustc_infer::traits::engine::TraitEngine>::select_where_possible::h137caf5bfc9f4211
  71:     0x7f2cb153febc - rustc_typeck::check::fn_ctxt::checks::<impl rustc_typeck::check::fn_ctxt::FnCtxt>::check_argument_types::hd9c65b7090c33843
  72:     0x7f2cb152367b - rustc_typeck::check::callee::<impl rustc_typeck::check::fn_ctxt::FnCtxt>::confirm_builtin_call::h49cff8412dd49fd0
  73:     0x7f2cb1522830 - rustc_typeck::check::callee::<impl rustc_typeck::check::fn_ctxt::FnCtxt>::check_call::h9e8271b1bb5c17fc
  74:     0x7f2cb152b6d7 - rustc_typeck::check::expr::<impl rustc_typeck::check::fn_ctxt::FnCtxt>::check_expr_kind::h9a0610c69d1db80e
  75:     0x7f2cb152ada5 - rustc_typeck::check::expr::<impl rustc_typeck::check::fn_ctxt::FnCtxt>::check_expr_with_expectation::hbec31136b572e013
  76:     0x7f2cb1542276 - rustc_typeck::check::fn_ctxt::checks::<impl rustc_typeck::check::fn_ctxt::FnCtxt>::check_stmt::hd9c9401fae4f4007
  77:     0x7f2cb1542b0c - rustc_typeck::check::fn_ctxt::checks::<impl rustc_typeck::check::fn_ctxt::FnCtxt>::check_block_with_expected::hec26ce1e195d7b11
  78:     0x7f2cb152ada5 - rustc_typeck::check::expr::<impl rustc_typeck::check::fn_ctxt::FnCtxt>::check_expr_with_expectation::hbec31136b572e013
  79:     0x7f2cb1536323 - rustc_typeck::check::expr::<impl rustc_typeck::check::fn_ctxt::FnCtxt>::check_return_expr::hd1dd70742d727dbf
  80:     0x7f2cb1615a18 - rustc_typeck::check::check::check_fn::h6af6276ff63ec41c
  81:     0x7f2cb15bb43c - rustc_typeck::check::inherited::InheritedBuilder::enter::hf5a3faec0a6907b2
  82:     0x7f2cb160e088 - rustc_typeck::check::typeck::h896d419cb4279063
  83:     0x7f2cb1743a8f - rustc_query_system::query::plumbing::get_query_impl::ha6569a99536f15ef
  84:     0x7f2cb1793bad - <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::typeck::hc9871bea409f75ba
  85:     0x7f2cb158748a - rustc_middle::ty::<impl rustc_middle::ty::context::TyCtxt>::par_body_owners::h5653ee80ce8eeaf5
  86:     0x7f2cb211cb0c - rustc_typeck::check::typeck_item_bodies::h84a3ebce4ed8af72
  87:     0x7f2cb2208537 - rustc_query_system::query::plumbing::get_query_impl::h9d41a92686f2332d
  88:     0x7f2cb22ac3c9 - <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::typeck_item_bodies::hfc11308daf2482eb
  89:     0x7f2cb20c3fdf - rustc_session::utils::<impl rustc_session::session::Session>::time::h5e0207abea9a46ba
  90:     0x7f2cb214be2c - rustc_typeck::check_crate::h033d52ddf5a3c52c
  91:     0x7f2cb145b4dc - rustc_interface::passes::analysis::h44573dd1f435360d
  92:     0x7f2cb2210c14 - rustc_query_system::query::plumbing::get_query_impl::hb28d9338aaa73db6
  93:     0x7f2cb22aa619 - <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::analysis::h92a4884e0478500d
  94:     0x7f2cb1e89aa7 - rustc_interface::passes::QueryContext::enter::hb9b4b642821635fe
  95:     0x7f2cb1e656e3 - rustc_interface::queries::<impl rustc_interface::interface::Compiler>::enter::h16bd07ff16fa3d4a
  96:     0x7f2cb1e61f0c - rustc_span::with_source_map::h6ee13da35fa72295
  97:     0x7f2cb1e64f28 - scoped_tls::ScopedKey<T>::set::h9c6565b722913393
  98:     0x7f2cb1e89e4b - std::sys_common::backtrace::__rust_begin_short_backtrace::hdcf17779193f6d57
  99:     0x7f2cb1e60c15 - core::ops::function::FnOnce::call_once{{vtable.shim}}::hf48084e1b458d4b2
 100:     0x7f2cafb94ad7 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hf00ff0dfc0b9e39f
                               at /rustc/c1e8f3a5857c3c8d095fd212acc6ed442f4cc58b/library/alloc/src/boxed.rs:1575:9
 101:     0x7f2cafb94ad7 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h236979b1b61b3517
                               at /rustc/c1e8f3a5857c3c8d095fd212acc6ed442f4cc58b/library/alloc/src/boxed.rs:1575:9
 102:     0x7f2cafb94ad7 - std::sys::unix::thread::Thread::new::thread_start::h8f357e546e4775fa
                               at /rustc/c1e8f3a5857c3c8d095fd212acc6ed442f4cc58b/library/std/src/sys/unix/thread.rs:71:17
 103:     0x7f2cafacf609 - start_thread
 104:     0x7f2caf9e3293 - clone
 105:                0x0 - <unknown>

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.54.0-nightly (c1e8f3a58 2021-05-30) running on x86_64-unknown-linux-gnu

note: compiler flags: -C embed-bitcode=no -C codegen-units=1 -C debuginfo=2 --crate-type lib

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
thread panicked while panicking. aborting.
error: could not compile `playground`

Caused by:
  process didn't exit successfully: `rustc --crate-name playground --edition=2018 src/lib.rs --error-format=json --json=diagnostic-rendered-ansi --crate-type lib --emit=dep-info,metadata,link -C embed-bitcode=no -C codegen-units=1 -C debuginfo=2 -C metadata=d5583dc9c61d0f13 -C extra-filename=-d5583dc9c61d0f13 --out-dir /playground/target/debug/deps -L dependency=/playground/target/debug/deps --extern addr2line=/playground/target/debug/deps/libaddr2line-ee0d9d4a76af11ea.rmeta --extern adler=/playground/target/debug/deps/libadler-b49c949e3504cbd1.rmeta --extern adler32=/playground/target/debug/deps/libadler32-d4247d4849a00fb6.rmeta --extern ahash=/playground/target/debug/deps/libahash-66e41c6e5122aadb.rmeta --extern aho_corasick=/playground/target/debug/deps/libaho_corasick-c6441250f4377f75.rmeta --extern ansi_term_0_11_0=/playground/target/debug/deps/libansi_term-120d85761b0feaf7.rmeta --extern ansi_term=/playground/target/debug/deps/libansi_term-ab35f8b11e59385a.rmeta --extern anyhow=/playground/target/debug/deps/libanyhow-179cdb76302d10b0.rmeta --extern approx=/playground/target/debug/deps/libapprox-190b3889ec54de9c.rmeta --extern arc_swap=/playground/target/debug/deps/libarc_swap-7b1a27cbfcae6908.rmeta --extern arrayvec=/playground/target/debug/deps/libarrayvec-ed5725d717896463.rmeta --extern async_trait=/playground/target/debug/deps/libasync_trait-9b53c0ce0d6bf428.so --extern atty=/playground/target/debug/deps/libatty-b32971181cd4632c.rmeta --extern autocfg=/playground/target/debug/deps/libautocfg-335ede5611a9b684.rmeta --extern backtrace=/playground/target/debug/deps/libbacktrace-038694a4f7fabb45.rmeta --extern base64=/playground/target/debug/deps/libbase64-c4895e085902010c.rmeta --extern bit_set=/playground/target/debug/deps/libbit_set-47a0d090fe1f7f69.rmeta --extern bit_vec=/playground/target/debug/deps/libbit_vec-d1b5bfc20fd2fdbc.rmeta --extern bitflags=/playground/target/debug/deps/libbitflags-a2155987696b8596.rmeta --extern block_buffer=/playground/target/debug/deps/libblock_buffer-cf569edb3edc0bc5.rmeta --extern bstr=/playground/target/debug/deps/libbstr-d6fef2b5ed7a6253.rmeta --extern bytemuck=/playground/target/debug/deps/libbytemuck-9cbbcec9795b0be3.rmeta --extern byteorder=/playground/target/debug/deps/libbyteorder-247b40861da05bec.rmeta --extern bytes=/playground/target/debug/deps/libbytes-fee841c20de076cb.rmeta --extern cc=/playground/target/debug/deps/libcc-14df8ee1f221c2e7.rmeta --extern cfg_if_0_1_10=/playground/target/debug/deps/libcfg_if-a42a72dabfa4a887.rmeta --extern cfg_if=/playground/target/debug/deps/libcfg_if-17db79e6160d9d60.rmeta --extern chrono=/playground/target/debug/deps/libchrono-3055731e32502d08.rmeta --extern clap=/playground/target/debug/deps/libclap-2d33e23686e77c52.rmeta --extern color_quant=/playground/target/debug/deps/libcolor_quant-18f74000246df249.rmeta --extern const_fn=/playground/target/debug/deps/libconst_fn-2fa43ad16cae7ca1.so --extern cpufeatures=/playground/target/debug/deps/libcpufeatures-83c3ca0f017c3e89.rmeta --extern crc32fast=/playground/target/debug/deps/libcrc32fast-11f74ee15174c644.rmeta --extern crossbeam=/playground/target/debug/deps/libcrossbeam-c6ea1577332ee86d.rmeta --extern crossbeam_channel=/playground/target/debug/deps/libcrossbeam_channel-cf2faca17e7aa8e0.rmeta --extern crossbeam_deque=/playground/target/debug/deps/libcrossbeam_deque-f4851f8a143ce40b.rmeta --extern crossbeam_epoch=/playground/target/debug/deps/libcrossbeam_epoch-28907527c93d5ffa.rmeta --extern crossbeam_queue=/playground/target/debug/deps/libcrossbeam_queue-508e25cb0c9b5c6e.rmeta --extern crossbeam_utils=/playground/target/debug/deps/libcrossbeam_utils-042ee9495f71bdfb.rmeta --extern crypto_mac=/playground/target/debug/deps/libcrypto_mac-c62c745d6784bc52.rmeta --extern csv=/playground/target/debug/deps/libcsv-a7bfd95643843dbe.rmeta --extern csv_core=/playground/target/debug/deps/libcsv_core-89157bb2fb151cdd.rmeta --extern data_encoding=/playground/target/debug/deps/libdata_encoding-5b6f22d0f4108c54.rmeta --extern deflate=/playground/target/debug/deps/libdeflate-e53f1b38507311f9.rmeta --extern derivative=/playground/target/debug/deps/libderivative-606320fe6b1cdefc.so --extern digest=/playground/target/debug/deps/libdigest-fb0e132aa354ba96.rmeta --extern dtoa=/playground/target/debug/deps/libdtoa-4c7fbf1ff0cbab74.rmeta --extern either=/playground/target/debug/deps/libeither-04371dfd35bf3584.rmeta --extern encoding_rs=/playground/target/debug/deps/libencoding_rs-1e774a9fa3beaffe.rmeta --extern env_logger=/playground/target/debug/deps/libenv_logger-e2cdfc5bfa4ca8d3.rmeta --extern error_chain=/playground/target/debug/deps/liberror_chain-210e48177c7db42f.rmeta --extern fallible_iterator=/playground/target/debug/deps/libfallible_iterator-ff9acd467715c624.rmeta --extern fallible_streaming_iterator=/playground/target/debug/deps/libfallible_streaming_iterator-af89121c1162058b.rmeta --extern filetime=/playground/target/debug/deps/libfiletime-3db6ab81dd6d75c0.rmeta --extern fixedbitset=/playground/target/debug/deps/libfixedbitset-7f130894b62c8660.rmeta --extern flate2=/playground/target/debug/deps/libflate2-2fdbab57365ff513.rmeta --extern fnv=/playground/target/debug/deps/libfnv-ae9dcfe01b70696a.rmeta --extern foreign_types=/playground/target/debug/deps/libforeign_types-35628d5e26d8374d.rmeta --extern foreign_types_shared=/playground/target/debug/deps/libforeign_types_shared-04972c5c102436b5.rmeta --extern form_urlencoded=/playground/target/debug/deps/libform_urlencoded-e91eb0906f17a107.rmeta --extern futf=/playground/target/debug/deps/libfutf-ab209591d3e97362.rmeta --extern futures=/playground/target/debug/deps/libfutures-3640da6c18eeac60.rmeta --extern futures_channel=/playground/target/debug/deps/libfutures_channel-697402c8a6d1b4d9.rmeta --extern futures_core=/playground/target/debug/deps/libfutures_core-91cc4549ca0472bf.rmeta --extern futures_executor=/playground/target/debug/deps/libfutures_executor-1919684d89f05f3b.rmeta --extern futures_io=/playground/target/debug/deps/libfutures_io-1c519c7af5f9be31.rmeta --extern futures_macro=/playground/target/debug/deps/libfutures_macro-98ca7b3d3a049c34.so --extern futures_sink=/playground/target/debug/deps/libfutures_sink-1ba616e92182ae88.rmeta --extern futures_task=/playground/target/debug/deps/libfutures_task-c10619735ffa0a4f.rmeta --extern futures_util=/playground/target/debug/deps/libfutures_util-8bb7d92340bb0033.rmeta --extern generic_array=/playground/target/debug/deps/libgeneric_array-ac53d730f67a9215.rmeta --extern getrandom_0_1_16=/playground/target/debug/deps/libgetrandom-dd734ec333646ec0.rmeta --extern getrandom=/playground/target/debug/deps/libgetrandom-953aad598d824cb7.rmeta --extern gif=/playground/target/debug/deps/libgif-5981fd6c37878d57.rmeta --extern gimli=/playground/target/debug/deps/libgimli-6cb0c61547c32c8f.rmeta --extern glob=/playground/target/debug/deps/libglob-8875c8c77f264e1f.rmeta --extern h2=/playground/target/debug/deps/libh2-04e37a8fa0f03808.rmeta --extern hashbrown_0_9_1=/playground/target/debug/deps/libhashbrown-b64880a240aa7322.rmeta --extern hashbrown=/playground/target/debug/deps/libhashbrown-4b9ac570b77fd59a.rmeta --extern hashlink=/playground/target/debug/deps/libhashlink-2df54f962698c5b5.rmeta --extern hmac=/playground/target/debug/deps/libhmac-6ca13de78761dcfa.rmeta --extern html5ever=/playground/target/debug/deps/libhtml5ever-fe07ebe884d52b30.rmeta --extern http=/playground/target/debug/deps/libhttp-6d4e9ea1f4436748.rmeta --extern http_body=/playground/target/debug/deps/libhttp_body-19f131530a31992a.rmeta --extern httparse=/playground/target/debug/deps/libhttparse-470041685c40f349.rmeta --extern httpdate=/playground/target/debug/deps/libhttpdate-3777d2580bf7b262.rmeta --extern humantime=/playground/target/debug/deps/libhumantime-2dac88ea32d7c5f9.rmeta --extern hyper=/playground/target/debug/deps/libhyper-269f946083df2091.rlib --extern hyper_tls=/playground/target/debug/deps/libhyper_tls-3cd96babba668b53.rmeta --extern idna=/playground/target/debug/deps/libidna-5189f56b88cf228a.rmeta --extern image=/playground/target/debug/deps/libimage-12c2fa3bf902c850.rmeta --extern indexmap=/playground/target/debug/deps/libindexmap-a16c9943b089e7da.rmeta --extern instant=/playground/target/debug/deps/libinstant-048283c91b125bac.rmeta --extern iovec=/playground/target/debug/deps/libiovec-20d7ac17ea53fe5d.rmeta --extern ipnet=/playground/target/debug/deps/libipnet-c9dd5fe28501a45f.rmeta --extern itertools=/playground/target/debug/deps/libitertools-83b02edb16ec9dc2.rmeta --extern itoa=/playground/target/debug/deps/libitoa-83e3755614d1c657.rmeta --extern jpeg_decoder=/playground/target/debug/deps/libjpeg_decoder-998a051a33d2a30b.rmeta --extern lazy_static=/playground/target/debug/deps/liblazy_static-735e050bd0c7e24f.rmeta --extern libc=/playground/target/debug/deps/liblibc-1995c28b8f2b0962.rmeta --extern libm=/playground/target/debug/deps/liblibm-cea705af515fc7b9.rmeta --extern libsqlite3_sys=/playground/target/debug/deps/liblibsqlite3_sys-aa8be5e8db948cf1.rmeta --extern linked_hash_map=/playground/target/debug/deps/liblinked_hash_map-de04d3a5c1d34737.rmeta --extern lock_api=/playground/target/debug/deps/liblock_api-ac13900cead869b4.rmeta --extern log=/playground/target/debug/deps/liblog-408df375a9649a3b.rmeta --extern log_mdc=/playground/target/debug/deps/liblog_mdc-99e505949276356c.rmeta --extern log4rs=/playground/target/debug/deps/liblog4rs-fc0ad27b59678119.rmeta --extern mac=/playground/target/debug/deps/libmac-e654eafe9d5122d7.rmeta --extern markup5ever=/playground/target/debug/deps/libmarkup5ever-5d4403d9e0000b42.rmeta --extern markup5ever_rcdom=/playground/target/debug/deps/libmarkup5ever_rcdom-83574fb059ebb9e9.rmeta --extern matches=/playground/target/debug/deps/libmatches-bd6291e3e71f7f58.rmeta --extern matrixmultiply=/playground/target/debug/deps/libmatrixmultiply-2815ae7c5268c707.rmeta --extern md5=/playground/target/debug/deps/libmd5-c688bc3f2ad8e1bf.rmeta --extern memchr=/playground/target/debug/deps/libmemchr-303ba0c6b7f69fdd.rmeta --extern memmap=/playground/target/debug/deps/libmemmap-75637b8d7b752bb8.rmeta --extern memoffset=/playground/target/debug/deps/libmemoffset-7bc0aaefb961dea4.rmeta --extern mime=/playground/target/debug/deps/libmime-b10d8882042d97b0.rmeta --extern miniz_oxide_0_3_7=/playground/target/debug/deps/libminiz_oxide-1d1d3f7f4239ae4c.rmeta --extern miniz_oxide=/playground/target/debug/deps/libminiz_oxide-e797ff84e041dd1b.rmeta --extern mio=/playground/target/debug/deps/libmio-4bc38476a11e445d.rmeta --extern nalgebra=/playground/target/debug/deps/libnalgebra-497ec3171c8a4d1d.rmeta --extern native_tls=/playground/target/debug/deps/libnative_tls-9894440be1f722c7.rmeta --extern ndarray=/playground/target/debug/deps/libndarray-9fb34296dc561b08.rmeta --extern net2=/playground/target/debug/deps/libnet2-e701ad3c61b0b028.rmeta --extern debug_unreachable=/playground/target/debug/deps/libdebug_unreachable-b62bf2bc851953e4.rmeta --extern num=/playground/target/debug/deps/libnum-310bd912008768ec.rmeta --extern num_bigint=/playground/target/debug/deps/libnum_bigint-f29aaa9fd78cd487.rmeta --extern num_complex_0_3_1=/playground/target/debug/deps/libnum_complex-980527fb46f49d6c.rmeta --extern num_complex=/playground/target/debug/deps/libnum_complex-c5a2adc8136581d0.rmeta --extern num_integer=/playground/target/debug/deps/libnum_integer-ef83eb595093d5c1.rmeta --extern num_iter=/playground/target/debug/deps/libnum_iter-26ef1d7d168b78fc.rmeta --extern num_rational_0_3_2=/playground/target/debug/deps/libnum_rational-7cc1ce30694fb776.rmeta --extern num_rational=/playground/target/debug/deps/libnum_rational-4f68421956e44075.rmeta --extern num_traits=/playground/target/debug/deps/libnum_traits-29185bbab3bdb97e.rmeta --extern num_cpus=/playground/target/debug/deps/libnum_cpus-5b99b8fc9a28fdc5.rmeta --extern object=/playground/target/debug/deps/libobject-b93a28bf81b69015.rmeta --extern once_cell=/playground/target/debug/deps/libonce_cell-17eb46c299237e16.rmeta --extern opaque_debug=/playground/target/debug/deps/libopaque_debug-0572f128331f44db.rmeta --extern openssl=/playground/target/debug/deps/libopenssl-efb98e29b5e5fba2.rmeta --extern openssl_probe=/playground/target/debug/deps/libopenssl_probe-686a8228f73d5587.rmeta --extern openssl_sys=/playground/target/debug/deps/libopenssl_sys-4045b399e7cdf3d3.rmeta --extern ordered_float=/playground/target/debug/deps/libordered_float-019dfbabae12313c.rmeta --extern parking_lot=/playground/target/debug/deps/libparking_lot-fbc04678a689e37a.rmeta --extern parking_lot_core=/playground/target/debug/deps/libparking_lot_core-4b82bbd1f7f9b70f.rmeta --extern paste=/playground/target/debug/deps/libpaste-00233cab4e8b72fc.so --extern percent_encoding=/playground/target/debug/deps/libpercent_encoding-6b4a80c4029ee4a3.rmeta --extern pest=/playground/target/debug/deps/libpest-921bca10ad4500d5.rmeta --extern petgraph=/playground/target/debug/deps/libpetgraph-062a231d714bf404.rmeta --extern phf=/playground/target/debug/deps/libphf-229c542ba338a49b.rmeta --extern phf_codegen=/playground/target/debug/deps/libphf_codegen-bdb4f021da5a033f.rmeta --extern phf_generator=/playground/target/debug/deps/libphf_generator-3536c6b907b70097.rmeta --extern phf_shared=/playground/target/debug/deps/libphf_shared-2a85a3479f3e9d7c.rmeta --extern pin_project=/playground/target/debug/deps/libpin_project-f77941bfb3338770.rmeta --extern pin_project_internal=/playground/target/debug/deps/libpin_project_internal-4dac01d9f797bd58.so --extern pin_project_lite=/playground/target/debug/deps/libpin_project_lite-4aca7f5ab6899e96.rmeta --extern pin_utils=/playground/target/debug/deps/libpin_utils-dd2961d584c22a9f.rmeta --extern pkg_config=/playground/target/debug/deps/libpkg_config-562f800da154de92.rmeta --extern png=/playground/target/debug/deps/libpng-cea4ce28892beca3.rmeta --extern postgres=/playground/target/debug/deps/libpostgres-0dbfa21c851ef125.rmeta --extern postgres_protocol=/playground/target/debug/deps/libpostgres_protocol-dc84516331d375dc.rmeta --extern postgres_types=/playground/target/debug/deps/libpostgres_types-d9c2dce66b67e3f4.rmeta --extern ppv_lite86=/playground/target/debug/deps/libppv_lite86-e926ed38ecbba29b.rmeta --extern precomputed_hash=/playground/target/debug/deps/libprecomputed_hash-c6d01971a34f5807.rmeta --extern proc_macro_hack=/playground/target/debug/deps/libproc_macro_hack-1fe68e267e98fed1.so --extern proc_macro_nested=/playground/target/debug/deps/libproc_macro_nested-c3e0e2e0e50d9cf6.rmeta --extern proc_macro2=/playground/target/debug/deps/libproc_macro2-171d29b015a25fed.rmeta --extern quick_error=/playground/target/debug/deps/libquick_error-73bf4d47b8e0946f.rmeta --extern quote=/playground/target/debug/deps/libquote-28f6da0b487d7867.rmeta --extern rand_0_7_3=/playground/target/debug/deps/librand-4bc4fa282dff2114.rmeta --extern rand=/playground/target/debug/deps/librand-57e804266b74ff6d.rmeta --extern rand_chacha_0_2_2=/playground/target/debug/deps/librand_chacha-b8619118511a1def.rmeta --extern rand_chacha=/playground/target/debug/deps/librand_chacha-fec8269fa383021e.rmeta --extern rand_core_0_5_1=/playground/target/debug/deps/librand_core-b7dc4e0d18959f21.rmeta --extern rand_core=/playground/target/debug/deps/librand_core-90c42f306c0a67c6.rmeta --extern rand_distr=/playground/target/debug/deps/librand_distr-fd8a48ab1041ab25.rmeta --extern rand_hc=/playground/target/debug/deps/librand_hc-184f8043827622bb.rmeta --extern rand_pcg=/playground/target/debug/deps/librand_pcg-c02b643b3c706d6d.rmeta --extern rawpointer=/playground/target/debug/deps/librawpointer-80c34ebe31e8881e.rmeta --extern rayon=/playground/target/debug/deps/librayon-efa02685d840aaa2.rmeta --extern rayon_core=/playground/target/debug/deps/librayon_core-47767e9c1bb1e123.rmeta --extern regex=/playground/target/debug/deps/libregex-a743d6793e59d4c0.rmeta --extern regex_automata=/playground/target/debug/deps/libregex_automata-02b61cebf24eb8c0.rmeta --extern regex_syntax=/playground/target/debug/deps/libregex_syntax-a3684af575b07253.rmeta --extern remove_dir_all=/playground/target/debug/deps/libremove_dir_all-5c0a87a169460981.rmeta --extern reqwest=/playground/target/debug/deps/libreqwest-eddd8d69dcb85115.rmeta --extern ring=/playground/target/debug/deps/libring-309f803389994ae1.rmeta --extern rusqlite=/playground/target/debug/deps/librusqlite-f61ee64936c66008.rmeta --extern rustc_demangle=/playground/target/debug/deps/librustc_demangle-9c9497fccfbeb6f4.rmeta --extern rustc_version=/playground/target/debug/deps/librustc_version-75e8a0114436076c.rmeta --extern ryu=/playground/target/debug/deps/libryu-fc722432573e8d7d.rmeta --extern same_file=/playground/target/debug/deps/libsame_file-aeaece771fe5a4c2.rmeta --extern scoped_threadpool=/playground/target/debug/deps/libscoped_threadpool-c6d356f1e1f61de2.rmeta --extern scopeguard=/playground/target/debug/deps/libscopeguard-a0d059c36fcc038c.rmeta --extern select=/playground/target/debug/deps/libselect-ff6802aec982cf06.rmeta --extern semver_0_11_0=/playground/target/debug/deps/libsemver-a62cee498f3c98c6.rmeta --extern semver=/playground/target/debug/deps/libsemver-89ee22c77159f823.rmeta --extern semver_parser=/playground/target/debug/deps/libsemver_parser-f4ec13d2daacd2c2.rmeta --extern serde=/playground/target/debug/deps/libserde-3be3aabe22700213.rmeta --extern serde_value=/playground/target/debug/deps/libserde_value-1c51d967072b1146.rmeta --extern serde_derive=/playground/target/debug/deps/libserde_derive-c418fc817a4e665f.so --extern serde_json=/playground/target/debug/deps/libserde_json-11ef87148e2682c3.rmeta --extern serde_urlencoded=/playground/target/debug/deps/libserde_urlencoded-4801cebf46d8a639.rmeta --extern serde_yaml=/playground/target/debug/deps/libserde_yaml-8e97ddd36fcbdb88.rmeta --extern sha2=/playground/target/debug/deps/libsha2-480edd035d499151.rmeta --extern simba=/playground/target/debug/deps/libsimba-5ad51f737fc567e7.rmeta --extern siphasher=/playground/target/debug/deps/libsiphasher-0b689d4e61ff3bad.rmeta --extern slab=/playground/target/debug/deps/libslab-8360eda8f600df05.rmeta --extern smallvec=/playground/target/debug/deps/libsmallvec-9e48c7819f40ec21.rmeta --extern smawk=/playground/target/debug/deps/libsmawk-8e38b6e5a5778769.rmeta --extern socket2=/playground/target/debug/deps/libsocket2-0838fcc7aeaf3135.rmeta --extern spin=/playground/target/debug/deps/libspin-459161897768fba8.rmeta --extern standback=/playground/target/debug/deps/libstandback-766c95787038fe25.rmeta --extern string_cache=/playground/target/debug/deps/libstring_cache-bbb6e0d504d96d08.rmeta --extern string_cache_codegen=/playground/target/debug/deps/libstring_cache_codegen-7d8e96147bf05d1b.rmeta --extern stringprep=/playground/target/debug/deps/libstringprep-28c2833df3cff0ef.rmeta --extern strsim_0_8_0=/playground/target/debug/deps/libstrsim-1094d6105a6b9102.rmeta --extern strsim=/playground/target/debug/deps/libstrsim-596fcd52b29ab067.rmeta --extern subtle=/playground/target/debug/deps/libsubtle-9abff15ff12775b5.rmeta --extern syn=/playground/target/debug/deps/libsyn-9d9f6aef6969da15.rmeta --extern synstructure=/playground/target/debug/deps/libsynstructure-7579161d5937eb71.rmeta --extern tar=/playground/target/debug/deps/libtar-5b795d685e9295e6.rmeta --extern tempfile=/playground/target/debug/deps/libtempfile-a887fbeb3c565c67.rmeta --extern tendril=/playground/target/debug/deps/libtendril-0de8141ddc771892.rmeta --extern termcolor=/playground/target/debug/deps/libtermcolor-46403bcbadff7ce9.rmeta --extern textwrap_0_11_0=/playground/target/debug/deps/libtextwrap-34d11634d35d2890.rmeta --extern textwrap=/playground/target/debug/deps/libtextwrap-9cac5c85790b3b1f.rmeta --extern thiserror=/playground/target/debug/deps/libthiserror-385b7d90f4c0e299.rmeta --extern thiserror_impl=/playground/target/debug/deps/libthiserror_impl-a1ce8d13d7bf50de.so --extern thread_id=/playground/target/debug/deps/libthread_id-7fe87ffdec07bebf.rmeta --extern thread_local=/playground/target/debug/deps/libthread_local-c41cf3494ad4d6ea.rmeta --extern threadpool=/playground/target/debug/deps/libthreadpool-1caecdbf14adddfa.rmeta --extern tiff=/playground/target/debug/deps/libtiff-1cd50ca84da2362a.rmeta --extern time_0_1_44=/playground/target/debug/deps/libtime-7db81ef2db6e706c.rmeta --extern time=/playground/target/debug/deps/libtime-469cbffb33911a86.rmeta --extern time_macros=/playground/target/debug/deps/libtime_macros-e01e99c658446be3.rmeta --extern time_macros_impl=/playground/target/debug/deps/libtime_macros_impl-056a36a6471c9fcb.so --extern tinyvec=/playground/target/debug/deps/libtinyvec-d5d38abfbdb27dc7.rmeta --extern tinyvec_macros=/playground/target/debug/deps/libtinyvec_macros-81d45e7b064eddd1.rmeta --extern tokio=/playground/target/debug/deps/libtokio-89dc1aacc690db7f.rmeta --extern tokio_native_tls=/playground/target/debug/deps/libtokio_native_tls-ee3ddcd438ed4095.rmeta --extern tokio_postgres=/playground/target/debug/deps/libtokio_postgres-0c92c5709bbf800a.rmeta --extern tokio_util=/playground/target/debug/deps/libtokio_util-46bc61a788a4663b.rmeta --extern toml=/playground/target/debug/deps/libtoml-f8a3e338d8b2ec8c.rmeta --extern tower_service=/playground/target/debug/deps/libtower_service-81097ae8f3ca822e.rmeta --extern tracing=/playground/target/debug/deps/libtracing-131dd695f9a3faa0.rmeta --extern tracing_core=/playground/target/debug/deps/libtracing_core-fb9824e74e5fe1d0.rmeta --extern traitobject=/playground/target/debug/deps/libtraitobject-65b44d6642786d87.rmeta --extern try_lock=/playground/target/debug/deps/libtry_lock-e4ac6437db956571.rmeta --extern typemap=/playground/target/debug/deps/libtypemap-ac1698b586ce6597.rmeta --extern typenum=/playground/target/debug/deps/libtypenum-9e7e9f850d4382a6.rmeta --extern ucd_trie=/playground/target/debug/deps/libucd_trie-45ec7daed9838d32.rmeta --extern unicase=/playground/target/debug/deps/libunicase-101756c05806db13.rmeta --extern unicode_bidi=/playground/target/debug/deps/libunicode_bidi-3139b89156d0786c.rmeta --extern unicode_normalization=/playground/target/debug/deps/libunicode_normalization-9e911e4edf677bf4.rmeta --extern unicode_segmentation=/playground/target/debug/deps/libunicode_segmentation-7eaecf846a4a004b.rmeta --extern unicode_width=/playground/target/debug/deps/libunicode_width-44d374a05dce6145.rmeta --extern unicode_xid=/playground/target/debug/deps/libunicode_xid-b18ccd133c106cd2.rmeta --extern unsafe_any=/playground/target/debug/deps/libunsafe_any-fbd575c915548e61.rmeta --extern untrusted=/playground/target/debug/deps/libuntrusted-524f673fcd7df21f.rmeta --extern url=/playground/target/debug/deps/liburl-273ff0298e451cf3.rmeta --extern utf8=/playground/target/debug/deps/libutf8-03bfb833d07e7ce7.rmeta --extern uuid=/playground/target/debug/deps/libuuid-6b01ff66b69be148.rmeta --extern vec_map=/playground/target/debug/deps/libvec_map-3e0d68bb2400498e.rmeta --extern version_check=/playground/target/debug/deps/libversion_check-8621e40e791d7e0b.rmeta --extern walkdir=/playground/target/debug/deps/libwalkdir-9288cdb139d035e8.rmeta --extern want=/playground/target/debug/deps/libwant-c21a0912f1e5429f.rmeta --extern weezl=/playground/target/debug/deps/libweezl-ef532351b91f45d8.rmeta --extern winapi=/playground/target/debug/deps/libwinapi-769de98f80380deb.rmeta --extern xattr=/playground/target/debug/deps/libxattr-31db13a661348bef.rmeta --extern xml5ever=/playground/target/debug/deps/libxml5ever-b1f2a27a4cf21995.rmeta --extern yaml_rust=/playground/target/debug/deps/libyaml_rust-bcd6d9b5400b9c0e.rmeta -L native=/playground/target/debug/build/libsqlite3-sys-a91e742d94f16749/out -L native=/playground/target/debug/build/ring-8241b1316fef72ea/out` (signal: 4, SIGILL: illegal instruction)

```

</p>
</details>

### PR DESCRIPTION
**Pull request by JohnTitor**
Fixes #83765, fixes #85848
r? @jackh726 as you're familiar with `Binding`. I'd like to get some views if the current approach is right path.

### CODE REVIEW

**Comment by jackh726** [comment]
So, unfortunately this isn't correct :/

As you can see from the failed test, this indeed is a tricky case (see https://github.com/rust-lang/rust/pull/83825/files#diff-a54c982c1e255569ddede4404cdf85ecfbd93c20edfa8a090a5f2dc2bc1dff6bR119 where we were going to just shunt that `BoundVarsCollector` into the corner for now).

I knew that `issue-64494#full` was creating bound *types* that lose their `Binder`. But I just now found out that there are tests that create bound *regions* that lose their `Binder`.

Ultimately, the "solution" is to either 1) not be creating bound vars (I'm not familiar with the originating code) or 2) Ensure that we also keep the `Binder` (in `rcvr_substs` in this example) when creating the bound vars.

@camelid thinks that these are originating from the coherence code, but hasn't been able to track down more specifically.


One alternative to "fix" things for now, is to move `BoundVarsCollector` here as I would like in #83825 then just re-add the code that collects regions. Ideally, I would like the *real* fix, but I would also be fine with merging the patch. I left a few reviews on #83825; if you want to use that PR as a base, work through the review, and re-add the region code, I'm sure @camelid wouldn't mind :)

**Comment by JohnTitor** [comment]
Thanks for checking!

> 2) Ensure that we also keep the `Binder` (in `rcvr_substs` in this example) when creating the bound vars.

Could we achieve this by following?

```diff
- let bound_vars = tcx
-             .mk_bound_variable_kinds(std::iter::once(ty::BoundVariableKind::Region(ty::BrAnon(0))));
+ let bound_vars = trait_ref.to_poly_trait_ref().bound_vars();
```

And it's odd not to reproduce the issue-64494's failure on my end, how could I reproduce it?

**Comment by JohnTitor** [comment]
Okay, moved `BoundVarsCollector` here (didn't actually move them because it'd cause a cyclic dependency error unless we move all the changes on #83825 here), added FIXME comment, and removed `bug!` macro. Can this be a "fix" for now?

File: compiler/rustc_ty_utils/src/instance.rs [hunk 1]
```diff
@@ -2,14 +2,98 @@ use rustc_errors::ErrorReported;
...
+                }
+            }
+
+            _ => (),
+        };
+
+        t.super_visit_with(self)
+    }
+
+    fn visit_region(&mut self, r: ty::Region<'tcx>) -> ControlFlow<Self::BreakTy> {
```
Comment (jackh726) [inline compiler/rustc_ty_utils/src/instance.rs:92]: This should look like https://github.com/jackh726/rust/commit/30187c81f65aa29a53ad7c24fe3b4c7bff947094#diff-79cd877dd2dfb44945f291684ef33b7d715853b694fcaa153e0d849712e9439cR779

**Review by jackh726 — CHANGES_REQUESTED** [review]
I think I would rather this completely subsume the other PR, rather than just duplicate `BoundVarsCollector` (honestly, should be pretty quick).

**Comment by jackh726** [comment]
> Could we achieve this by following?
> 
> ```diff
> - let bound_vars = tcx
> -             .mk_bound_variable_kinds(std::iter::once(ty::BoundVariableKind::Region(ty::BrAnon(0))));
> + let bound_vars = trait_ref.to_poly_trait_ref().bound_vars();
> ```

Nope! If you look at `to_poly_trait_ref`, it actually wraps it in a `Binder::dummy` (I would like at some point to remove these functions in favor of being more explicit at the call sites)

> And it's odd not to reproduce the issue-64494's failure on my local, how could I reproduce it?

Weid. When I do `./x.py test src/test/ui/const-generics` it repros fine

**Comment by JohnTitor** [comment]
Thanks for the pointer! Pulled the changes from that PR applying your review comments.

> Weid. When I do `./x.py test src/test/ui/const-generics` it repros fine

Hmm, then maybe my config.toml or something else is wrong. For now, I'm using CI here for testing.

File: compiler/rustc_ty_utils/src/instance.rs [hunk 2]
```diff
@@ -2,14 +2,123 @@ use rustc_errors::ErrorReported;
...
+    fn new() -> Self {
+        BoundVarsCollector {
+            binder_index: ty::INNERMOST,
+            vars: BTreeMap::new(),
+            visited: SsoHashSet::default(),
+        }
+    }
+
+    fn into_vars(self, tcx: TyCtxt<'tcx>) -> &'tcx ty::List<ty::BoundVariableKind> {
+        let max = self.vars.iter().map(|(k, _)| *k).max().unwrap_or_else(|| 0);
```
Comment (klensy) [inline compiler/rustc_ty_utils/src/instance.rs:42]:
```suggestion
        let max = self.vars.iter().map(|(k, _)| *k).max().unwrap_or(0);
```

File: compiler/rustc_ty_utils/src/instance.rs [hunk 3]
```diff
@@ -2,14 +2,123 @@ use rustc_errors::ErrorReported;
...
+
+        t.super_visit_with(self)
+    }
+
+    fn visit_region(&mut self, r: ty::Region<'tcx>) -> ControlFlow<Self::BreakTy> {
+        use std::collections::btree_map::Entry;
+        match r {
+            ty::ReLateBound(index, br) if *index == self.binder_index => match br.kind {
+                ty::BrNamed(_def_id, _name) => {
+                    // FIXME
```
Comment (jackh726) [inline compiler/rustc_ty_utils/src/instance.rs:97]: Oh oops. I don't remember if later versions of this added this or if I begin to track state before it was needed.

Given that the problem here is still unclear, I wonder if it's worth adding back this code or not (and for BrEnv). At the very least the FIXME should be changed to an explicit comment.

Also...it just occured to me that we now have a `var` field available to us. So we can rewrite this in a smarter way. Or, at least verify that the variable is in the same place we would expect it!

I can either look back through the history to see if there's a more up to date version, or maybe you can.

File: compiler/rustc_typeck/src/check/wfcheck.rs [hunk 4]
```diff
@@ -1087,14 +1087,10 @@ fn check_method_receiver<'fcx, 'tcx>(
     debug!("check_method_receiver: sig={:?}", sig);
 
     let self_ty = fcx.normalize_associated_types_in(span, self_ty);
-    let self_ty =
-        fcx.tcx.liberate_late_bound_regions(method.def_id, ty::Binder::bind(self_ty, fcx.tcx));
+    let self_ty = fcx.tcx.liberate_late_bound_regions(method.def_id, ty::Binder::dummy(self_ty));
```
Comment (jackh726) [inline compiler/rustc_typeck/src/check/wfcheck.rs:1091]: These two lines can be removed. Don't need to liberate anything if there aren't bound vars.

**Review by jackh726 — CHANGES_REQUESTED** [review]
Some comments. Sorry this ended up being a bit more involved than you probably expected. 🙃

File: compiler/rustc_ty_utils/src/instance.rs (hunk 3 above)
Comment (JohnTitor) [reply compiler/rustc_ty_utils/src/instance.rs:97]: > I can either look back through the history to see if there's a more up to date version, or maybe you can.

So after the above commit, https://github.com/rust-lang/rust/pull/76814/commits/6d5efa9f040d2638318f9e8b96eab718ef664e3c changed it to the current style.

> Also...it just occured to me that we now have a var field available to us. So we can rewrite this in a smarter way. Or, at least verify that the variable is in the same place we would expect it!

Hmm, I haven't understood it, could you elaborate? Something like this?

```rust
ty::BrNamed(def_id, _name) => match self.vars.get(&br.var.as_u32()) {
                    Some(_) => {}
                    None => bug!("couldn't find!"),
                }
```

Comment (jackh726) [reply compiler/rustc_ty_utils/src/instance.rs:97]: Oops, this is what I get for reviewing from mobile early. I think we can just do
```rust
match r {
  ty::ReLateBound(index, br) if *index == self.binder_index => {
    match self.vars.entry(br.var.as_u32()) {
      ... (insert of check same kind)
    }
  }
}
```

Comment (JohnTitor) [reply compiler/rustc_ty_utils/src/instance.rs]: Thanks! Actually, I overlooked how we implemented `visit_ty` above. Now I think I addressed your comment.

File: compiler/rustc_typeck/src/check/wfcheck.rs [hunk 5]
```diff
@@ -1086,15 +1086,8 @@ fn check_method_receiver<'fcx, 'tcx>(
 
     debug!("check_method_receiver: sig={:?}", sig);
 
-    let self_ty = fcx.normalize_associated_types_in(span, self_ty);
```
Comment (jackh726) [inline compiler/rustc_typeck/src/check/wfcheck.rs:1089]: I think this line got removed unintentionally.

**Review by jackh726 — CHANGES_REQUESTED** [review]
One small change (it gets removed in #85499 anyways, but would rather not make that here)

Then LGTM!

File: compiler/rustc_typeck/src/check/wfcheck.rs (hunk 5 above)
Comment (JohnTitor) [reply compiler/rustc_typeck/src/check/wfcheck.rs:1089]: Oops, yes, restored.

**Comment by jackh726** [comment]
@bors r+ rollup=never

There might be a slight perf improvement because of `Binder::dummy`, but the perf run done in #83825 suggests this is very slight, if any.

**Comment by JohnTitor** [comment]
```
2021-07-02T23:00:37.2702922Z ##[group]Run exit 1
2021-07-02T23:00:37.3307585Z shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
2021-07-02T23:00:37.3308542Z ##[endgroup]
2021-07-02T23:00:37.3778908Z ##[error]Process completed with exit code 1.
2021-07-02T23:00:37.3810471Z Cleaning up orphan processes
```

@bors retry
