### PR TITLE
rustdoc: Correctly merge import's and its target's docs in one more case

### LINKED ISSUE #108061: Compiler panic when running rustdoc
### Code

The [`skia-safe`](https://github.com/rust-skia/rust-skia) crate

### Meta

```
rustc 1.69.0-nightly (065852def 2023-02-13) running on aarch64-apple-darwin
```

### Error output

```
thread 'rustc' panicked at 'no resolution for "Path" MacroNS DefId(0:2566 ~ skia_safe[0ba6]::core::path_types)', src/librustdoc/passes/collect_intra_doc_links.rs:393:32
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
stack backtrace:
   0:        0x1039d014c - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h41165bc928a6a061
   1:        0x103a1fbf4 - core::fmt::write::hc1381c8a8889ae59
   2:        0x1039c3b7c - std::io::Write::write_fmt::h597fe54d40a99bca
   3:        0x1039cff60 - std::sys_common::backtrace::print::hffd3791d3c76c5bf
   4:        0x1039d2a40 - std::panicking::default_hook::{{closure}}::hdcf127fa35c85582
   5:        0x1039d2798 - std::panicking::default_hook::hea25b24bcf201545
   6:        0x10bda393c - rustc_driver_impl[bf58ad8ec9b96ac6]::DEFAULT_HOOK::{closure#0}::{closure#0}
   7:        0x1039d3138 - std::panicking::rust_panic_with_hook::h1f31579a116a5567
   8:        0x1039d2f30 - std::panicking::begin_panic_handler::{{closure}}::h91adc5c2252dfa41
   9:        0x1039d05ac - std::sys_common::backtrace::__rust_end_short_backtrace::h1ce4494cc6011cab
  10:        0x1039d2c8c - _rust_begin_unwind
  11:        0x103a4ac38 - core::panicking::panic_fmt::he9b8054d565a504b
  12:        0x102686e20 - <rustdoc[45017e1e30933be6]::passes::collect_intra_doc_links::LinkCollector>::resolve_path
  13:        0x102686f14 - <rustdoc[45017e1e30933be6]::passes::collect_intra_doc_links::LinkCollector>::resolve
  14:        0x10268a398 - <rustdoc[45017e1e30933be6]::passes::collect_intra_doc_links::LinkCollector as rustdoc[45017e1e30933be6]::visit::DocVisitor>::visit_item
  15:        0x1026946d8 - <rustdoc[45017e1e30933be6]::passes::collect_intra_doc_links::LinkCollector as rustdoc[45017e1e30933be6]::visit::DocVisitor>::visit_inner_recur
  16:        0x10268c134 - <rustdoc[45017e1e30933be6]::passes::collect_intra_doc_links::LinkCollector as rustdoc[45017e1e30933be6]::visit::DocVisitor>::visit_item
  17:        0x1026946d8 - <rustdoc[45017e1e30933be6]::passes::collect_intra_doc_links::LinkCollector as rustdoc[45017e1e30933be6]::visit::DocVisitor>::visit_inner_recur
  18:        0x10268c134 - <rustdoc[45017e1e30933be6]::passes::collect_intra_doc_links::LinkCollector as rustdoc[45017e1e30933be6]::visit::DocVisitor>::visit_item
  19:        0x102685cf4 - rustdoc[45017e1e30933be6]::passes::collect_intra_doc_links::collect_intra_doc_links
  20:        0x10264f104 - <rustc_session[89163586e80eb523]::session::Session>::time::<rustdoc[45017e1e30933be6]::clean::types::Crate, rustdoc[45017e1e30933be6]::core::run_global_ctxt::{closure#7}>
  21:        0x1026bc214 - rustdoc[45017e1e30933be6]::core::run_global_ctxt
  22:        0x10264f48c - <rustc_session[89163586e80eb523]::session::Session>::time::<(rustdoc[45017e1e30933be6]::clean::types::Crate, rustdoc[45017e1e30933be6]::config::RenderOptions, rustdoc[45017e1e30933be6]::formats::cache::Cache), rustdoc[45017e1e30933be6]::main_args::{closure#1}::{closure#0}::{closure#1}::{closure#0}>
  23:        0x10254fb38 - <rustc_middle[1df477d6d6e6e6bb]::ty::context::GlobalCtxt>::enter::<rustdoc[45017e1e30933be6]::main_args::{closure#1}::{closure#0}::{closure#1}, core[ffaedfe380a89c03]::result::Result<(), rustc_errors[684c395a6d8c68d2]::ErrorGuaranteed>>
  24:        0x1025812f0 - <rustc_interface[fd812d6d93653895]::interface::Compiler>::enter::<rustdoc[45017e1e30933be6]::main_args::{closure#1}::{closure#0}, core[ffaedfe380a89c03]::result::Result<(), rustc_errors[684c395a6d8c68d2]::ErrorGuaranteed>>
  25:        0x10264e644 - rustc_span[bd1a3074b802070d]::with_source_map::<core[ffaedfe380a89c03]::result::Result<(), rustc_errors[684c395a6d8c68d2]::ErrorGuaranteed>, rustc_interface[fd812d6d93653895]::interface::run_compiler<core[ffaedfe380a89c03]::result::Result<(), rustc_errors[684c395a6d8c68d2]::ErrorGuaranteed>, rustdoc[45017e1e30933be6]::main_args::{closure#1}>::{closure#0}::{closure#0}>
  26:        0x1025bf678 - <scoped_tls[b65597938795c41d]::ScopedKey<rustc_span[bd1a3074b802070d]::SessionGlobals>>::set::<rustc_interface[fd812d6d93653895]::interface::run_compiler<core[ffaedfe380a89c03]::result::Result<(), rustc_errors[684c395a6d8c68d2]::ErrorGuaranteed>, rustdoc[45017e1e30933be6]::main_args::{closure#1}>::{closure#0}, core[ffaedfe380a89c03]::result::Result<(), rustc_errors[684c395a6d8c68d2]::ErrorGuaranteed>>
  27:        0x102660f90 - std[63e5474b8dbdb59]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[fd812d6d93653895]::util::run_in_thread_pool_with_globals<rustc_interface[fd812d6d93653895]::interface::run_compiler<core[ffaedfe380a89c03]::result::Result<(), rustc_errors[684c395a6d8c68d2]::ErrorGuaranteed>, rustdoc[45017e1e30933be6]::main_args::{closure#1}>::{closure#0}, core[ffaedfe380a89c03]::result::Result<(), rustc_errors[684c395a6d8c68d2]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[ffaedfe380a89c03]::result::Result<(), rustc_errors[684c395a6d8c68d2]::ErrorGuaranteed>>
  28:        0x10271b890 - <<std[63e5474b8dbdb59]::thread::Builder>::spawn_unchecked_<rustc_interface[fd812d6d93653895]::util::run_in_thread_pool_with_globals<rustc_interface[fd812d6d93653895]::interface::run_compiler<core[ffaedfe380a89c03]::result::Result<(), rustc_errors[684c395a6d8c68d2]::ErrorGuaranteed>, rustdoc[45017e1e30933be6]::main_args::{closure#1}>::{closure#0}, core[ffaedfe380a89c03]::result::Result<(), rustc_errors[684c395a6d8c68d2]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[ffaedfe380a89c03]::result::Result<(), rustc_errors[684c395a6d8c68d2]::ErrorGuaranteed>>::{closure#1} as core[ffaedfe380a89c03]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  29:        0x1039db560 - std::sys::unix::thread::Thread::new::thread_start::h7b399846e2ac9979
  30:        0x1c49e1240 - __pthread_deallocate

error: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.69.0-nightly (065852def 2023-02-13) running on aarch64-apple-darwin

note: compiler flags: --crate-type lib

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack

```

</p>
</details>

### LINKED ISSUE #108334: ICE when documenting `clap` 3.2.23 (still)
This looks similar to #108065, but this wasn't fixed by #108129

### Code
`src/main.rs`
```rust
fn main() {
    println!("Hello world!");
}
```

`Cargo.toml`
```toml
[package]
name = "rust-issue"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3"
```

```console
$ cargo +nightly doc
```

### Meta

`rustc --version --verbose`:
```
rustc 1.69.0-nightly (246eae2fa 2023-02-21)
binary: rustc
commit-hash: 246eae2fab54a5139365c4e1a08c5724fb385fbf
commit-date: 2023-02-21
host: x86_64-unknown-linux-gnu
release: 1.69.0-nightly
LLVM version: 15.0.7
```

`rustdoc -Vv`:
```
rustdoc 1.69.0-nightly (246eae2fa 2023-02-21)
binary: rustdoc
commit-hash: unknown
commit-date: unknown
host: x86_64-unknown-linux-gnu
release: 1.69.0-nightly
LLVM version: 15.0.7
```

### Error output

```
thread 'rustc' panicked at 'no resolution for "ValueEnum" MacroNS DefId(0:52 ~ clap[670b]::derive)', src/librustdoc/passes/collect_intra_doc_links.rs:391:32
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
stack backtrace:
   0:     0x7f7df396ab3a - std::backtrace_rs::backtrace::libunwind::trace::hf28dbfd50804136b
                               at /rustc/246eae2fab54a5139365c4e1a08c5724fb385fbf/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x7f7df396ab3a - std::backtrace_rs::backtrace::trace_unsynchronized::h62d3d75d8c6c7518
                               at /rustc/246eae2fab54a5139365c4e1a08c5724fb385fbf/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7f7df396ab3a - std::sys_common::backtrace::_print_fmt::h7c65ad4db782ae35
                               at /rustc/246eae2fab54a5139365c4e1a08c5724fb385fbf/library/std/src/sys_common/backtrace.rs:65:5
   3:     0x7f7df396ab3a - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h0591d7d923081cf4
                               at /rustc/246eae2fab54a5139365c4e1a08c5724fb385fbf/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x7f7df39cab0e - core::fmt::write::hd8816c33fd513dac
                               at /rustc/246eae2fab54a5139365c4e1a08c5724fb385fbf/library/core/src/fmt/mod.rs:1232:17
   5:     0x7f7df395afe5 - std::io::Write::write_fmt::ha970bd0663a942df
                               at /rustc/246eae2fab54a5139365c4e1a08c5724fb385fbf/library/std/src/io/mod.rs:1684:15
   6:     0x7f7df396a905 - std::sys_common::backtrace::_print::hc1125f7df30aa8c7
                               at /rustc/246eae2fab54a5139365c4e1a08c5724fb385fbf/library/std/src/sys_common/backtrace.rs:47:5
   7:     0x7f7df396a905 - std::sys_common::backtrace::print::h7c336b712f9027e7
                               at /rustc/246eae2fab54a5139365c4e1a08c5724fb385fbf/library/std/src/sys_common/backtrace.rs:34:9
   8:     0x7f7df396d67f - std::panicking::default_hook::{{closure}}::h0917a311388d7814
                               at /rustc/246eae2fab54a5139365c4e1a08c5724fb385fbf/library/std/src/panicking.rs:271:22
   9:     0x7f7df396d3bb - std::panicking::default_hook::h91db7159ba663c12
                               at /rustc/246eae2fab54a5139365c4e1a08c5724fb385fbf/library/std/src/panicking.rs:290:9
  10:     0x7f7df6c32a05 - <rustc_driver_impl[4b64b4bc5ee8683e]::DEFAULT_HOOK::{closure#0}::{closure#0} as core[f58ef986ec581f4d]::ops::function::FnOnce<(&core[f58ef986ec581f4d]::panic::panic_info::PanicInfo,)>>::call_once::{shim:vtable#0}
  11:     0x7f7df396debd - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h4962fd3539ba3a02
                               at /rustc/246eae2fab54a5139365c4e1a08c5724fb385fbf/library/alloc/src/boxed.rs:2002:9
  12:     0x7f7df396debd - std::panicking::rust_panic_with_hook::h35ca8355202430f8
                               at /rustc/246eae2fab54a5139365c4e1a08c5724fb385fbf/library/std/src/panicking.rs:696:13
  13:     0x7f7df396dc39 - std::panicking::begin_panic_handler::{{closure}}::hc6b9b77304316297
                               at /rustc/246eae2fab54a5139365c4e1a08c5724fb385fbf/library/std/src/panicking.rs:583:13
  14:     0x7f7df396afa6 - std::sys_common::backtrace::__rust_end_short_backtrace::h4a71907d455ad567
                               at /rustc/246eae2fab54a5139365c4e1a08c5724fb385fbf/library/std/src/sys_common/backtrace.rs:137:18
  15:     0x7f7df396d942 - rust_begin_unwind
                               at /rustc/246eae2fab54a5139365c4e1a08c5724fb385fbf/library/std/src/panicking.rs:579:5
  16:     0x7f7df39c74b3 - core::panicking::panic_fmt::h08295fd5e9d4266f
                               at /rustc/246eae2fab54a5139365c4e1a08c5724fb385fbf/library/core/src/panicking.rs:64:14
  17:     0x55dce0441394 - <rustdoc[94b35f38d6a94f1d]::passes::collect_intra_doc_links::LinkCollector>::resolve_path
  18:     0x55dce04414be - <rustdoc[94b35f38d6a94f1d]::passes::collect_intra_doc_links::LinkCollector>::resolve
  19:     0x55dce0445042 - <rustdoc[94b35f38d6a94f1d]::passes::collect_intra_doc_links::LinkCollector as rustdoc[94b35f38d6a94f1d]::visit::DocVisitor>::visit_item
  20:     0x55dce044e53a - <rustdoc[94b35f38d6a94f1d]::passes::collect_intra_doc_links::LinkCollector as rustdoc[94b35f38d6a94f1d]::visit::DocVisitor>::visit_inner_recur
  21:     0x55dce04488ca - <rustdoc[94b35f38d6a94f1d]::passes::collect_intra_doc_links::LinkCollector as rustdoc[94b35f38d6a94f1d]::visit::DocVisitor>::visit_item
  22:     0x55dce043fe12 - rustdoc[94b35f38d6a94f1d]::passes::collect_intra_doc_links::collect_intra_doc_links
  23:     0x55dce038905e - <rustc_session[44050795d9383a68]::session::Session>::time::<rustdoc[94b35f38d6a94f1d]::clean::types::Crate, rustdoc[94b35f38d6a94f1d]::core::run_global_ctxt::{closure#7}>
  24:     0x55dce0475757 - rustdoc[94b35f38d6a94f1d]::core::run_global_ctxt
  25:     0x55dce03892e9 - <rustc_session[44050795d9383a68]::session::Session>::time::<(rustdoc[94b35f38d6a94f1d]::clean::types::Crate, rustdoc[94b35f38d6a94f1d]::config::RenderOptions, rustdoc[94b35f38d6a94f1d]::formats::cache::Cache), rustdoc[94b35f38d6a94f1d]::main_args::{closure#1}::{closure#0}::{closure#0}::{closure#0}>
  26:     0x55dce0250207 - <rustc_middle[907a58d0a040d1ca]::ty::context::GlobalCtxt>::enter::<rustdoc[94b35f38d6a94f1d]::main_args::{closure#1}::{closure#0}::{closure#0}, core[f58ef986ec581f4d]::result::Result<(), rustc_errors[4094b211812344c9]::ErrorGuaranteed>>
  27:     0x55dce02bb920 - <rustc_interface[e197867a1d20668b]::interface::Compiler>::enter::<rustdoc[94b35f38d6a94f1d]::main_args::{closure#1}::{closure#0}, core[f58ef986ec581f4d]::result::Result<(), rustc_errors[4094b211812344c9]::ErrorGuaranteed>>
  28:     0x55dce01ebf7b - rustc_span[8c8cf17da961254a]::with_source_map::<core[f58ef986ec581f4d]::result::Result<(), rustc_errors[4094b211812344c9]::ErrorGuaranteed>, rustc_interface[e197867a1d20668b]::interface::run_compiler<core[f58ef986ec581f4d]::result::Result<(), rustc_errors[4094b211812344c9]::ErrorGuaranteed>, rustdoc[94b35f38d6a94f1d]::main_args::{closure#1}>::{closure#0}::{closure#0}>
  29:     0x55dce022e112 - <scoped_tls[d6861a481158478]::ScopedKey<rustc_span[8c8cf17da961254a]::SessionGlobals>>::set::<rustc_interface[e197867a1d20668b]::interface::run_compiler<core[f58ef986ec581f4d]::result::Result<(), rustc_errors[4094b211812344c9]::ErrorGuaranteed>, rustdoc[94b35f38d6a94f1d]::main_args::{closure#1}>::{closure#0}, core[f58ef986ec581f4d]::result::Result<(), rustc_errors[4094b211812344c9]::ErrorGuaranteed>>
  30:     0x55dce039a970 - std[30e2381581ca1e47]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[e197867a1d20668b]::util::run_in_thread_pool_with_globals<rustc_interface[e197867a1d20668b]::interface::run_compiler<core[f58ef986ec581f4d]::result::Result<(), rustc_errors[4094b211812344c9]::ErrorGuaranteed>, rustdoc[94b35f38d6a94f1d]::main_args::{closure#1}>::{closure#0}, core[f58ef986ec581f4d]::result::Result<(), rustc_errors[4094b211812344c9]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[f58ef986ec581f4d]::result::Result<(), rustc_errors[4094b211812344c9]::ErrorGuaranteed>>
  31:     0x55dce04663ff - <<std[30e2381581ca1e47]::thread::Builder>::spawn_unchecked_<rustc_interface[e197867a1d20668b]::util::run_in_thread_pool_with_globals<rustc_interface[e197867a1d20668b]::interface::run_compiler<core[f58ef986ec581f4d]::result::Result<(), rustc_errors[4094b211812344c9]::ErrorGuaranteed>, rustdoc[94b35f38d6a94f1d]::main_args::{closure#1}>::{closure#0}, core[f58ef986ec581f4d]::result::Result<(), rustc_errors[4094b211812344c9]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[f58ef986ec581f4d]::result::Result<(), rustc_errors[4094b211812344c9]::ErrorGuaranteed>>::{closure#1} as core[f58ef986ec581f4d]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  32:     0x7f7df3977d93 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h740447c4991af6d5
                               at /rustc/246eae2fab54a5139365c4e1a08c5724fb385fbf/library/alloc/src/boxed.rs:1988:9
  33:     0x7f7df3977d93 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h2d2f6f4b2902f0d3
                               at /rustc/246eae2fab54a5139365c4e1a08c5724fb385fbf/library/alloc/src/boxed.rs:1988:9
  34:     0x7f7df3977d93 - std::sys::unix::thread::Thread::new::thread_start::h352f678abefa5ff1
                               at /rustc/246eae2fab54a5139365c4e1a08c5724fb385fbf/library/std/src/sys/unix/thread.rs:108:17
  35:     0x7f7df36a8fd4 - start_thread
                               at ./nptl/./nptl/pthread_create.c:442:8
  36:     0x7f7df372966c - __GI___clone3
                               at ./misc/../sysdeps/unix/sysv/linux/x86_64/clone3.S:81
  37:                0x0 - <unknown>

error: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.69.0-nightly (246eae2fa 2023-02-21) running on x86_64-unknown-linux-gnu

note: compiler flags: --crate-type lib

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
```

</p>
</details>

@rustbot modify labels +A-resolve

### LINKED ISSUE #108378: rustdoc ICE: `no resolutions for a doc link`
Found while reducing #108334, but the error is different (probably same root cause however)

### Code

```Rust
mod m {
    pub enum ValueEnum {} // Also occurs for trait, struct
}
/// [`ValueEnum`]
pub use m::ValueEnum;
```

### Meta

`rustc --version --verbose`:
```
rustc 1.69.0-nightly (4507fdaaa 2023-02-18)
binary: rustc
commit-hash: 4507fdaaa27ea2fb59a41df2ce7d1f290da53dae
commit-date: 2023-02-18
host: x86_64-unknown-linux-gnu
release: 1.69.0-nightly
LLVM version: 15.0.7
```

### Error output

<details><summary><strong>Backtrace</strong></summary>
<p>

```
 Documenting notclap v0.1.0 (/tmp/notclap)
thread 'rustc' panicked at 'no resolutions for a doc link', compiler/rustc_metadata/src/rmeta/encoder.rs:2238:18
stack backtrace:
   0:     0x7f52384b0a7a - std::backtrace_rs::backtrace::libunwind::trace::h9ab7cd28287cf18f
                               at /rustc/4507fdaaa27ea2fb59a41df2ce7d1f290da53dae/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x7f52384b0a7a - std::backtrace_rs::backtrace::trace_unsynchronized::h3e7e6ca06d1d63cf
                               at /rustc/4507fdaaa27ea2fb59a41df2ce7d1f290da53dae/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7f52384b0a7a - std::sys_common::backtrace::_print_fmt::h5b6184fd459f0c71
                               at /rustc/4507fdaaa27ea2fb59a41df2ce7d1f290da53dae/library/std/src/sys_common/backtrace.rs:65:5
   3:     0x7f52384b0a7a - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h8ed5468732b78071
                               at /rustc/4507fdaaa27ea2fb59a41df2ce7d1f290da53dae/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x7f52385109fe - core::fmt::write::h89c1e855e81d7a96
                               at /rustc/4507fdaaa27ea2fb59a41df2ce7d1f290da53dae/library/core/src/fmt/mod.rs:1232:17
   5:     0x7f52384a0f25 - std::io::Write::write_fmt::ha23ba71db044374b
                               at /rustc/4507fdaaa27ea2fb59a41df2ce7d1f290da53dae/library/std/src/io/mod.rs:1684:15
   6:     0x7f52384b0845 - std::sys_common::backtrace::_print::h194cdf55c322d5fe
                               at /rustc/4507fdaaa27ea2fb59a41df2ce7d1f290da53dae/library/std/src/sys_common/backtrace.rs:47:5
   7:     0x7f52384b0845 - std::sys_common::backtrace::print::h4549e75783bab124
                               at /rustc/4507fdaaa27ea2fb59a41df2ce7d1f290da53dae/library/std/src/sys_common/backtrace.rs:34:9
   8:     0x7f52384b35bf - std::panicking::default_hook::{{closure}}::h04a46ea9ff60bf2c
                               at /rustc/4507fdaaa27ea2fb59a41df2ce7d1f290da53dae/library/std/src/panicking.rs:267:22
   9:     0x7f52384b32fb - std::panicking::default_hook::h6f3c116d48f73fba
                               at /rustc/4507fdaaa27ea2fb59a41df2ce7d1f290da53dae/library/std/src/panicking.rs:286:9
  10:     0x7f523723c5f5 - <rustc_driver_impl[48a98004e06292cf]::DEFAULT_HOOK::{closure#0}::{closure#0} as core[69c2f5c35675f1ee]::ops::function::FnOnce<(&core[69c2f5c35675f1ee]::panic::panic_info::PanicInfo,)>>::call_once::{shim:vtable#0}
  11:     0x7f52384b3dfd - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h779d28c2deb011a8
                               at /rustc/4507fdaaa27ea2fb59a41df2ce7d1f290da53dae/library/alloc/src/boxed.rs:2002:9
  12:     0x7f52384b3dfd - std::panicking::rust_panic_with_hook::h5a936503487f19f5
                               at /rustc/4507fdaaa27ea2fb59a41df2ce7d1f290da53dae/library/std/src/panicking.rs:692:13
  13:     0x7f52384b3b79 - std::panicking::begin_panic_handler::{{closure}}::hf8db4efce7a7f23f
                               at /rustc/4507fdaaa27ea2fb59a41df2ce7d1f290da53dae/library/std/src/panicking.rs:579:13
  14:     0x7f52384b0ee6 - std::sys_common::backtrace::__rust_end_short_backtrace::h668cb6dbbf3929c2
                               at /rustc/4507fdaaa27ea2fb59a41df2ce7d1f290da53dae/library/std/src/sys_common/backtrace.rs:137:18
  15:     0x7f52384b3882 - rust_begin_unwind
                               at /rustc/4507fdaaa27ea2fb59a41df2ce7d1f290da53dae/library/std/src/panicking.rs:575:5
  16:     0x7f523850d3a3 - core::panicking::panic_fmt::h6a86232234ce2127
                               at /rustc/4507fdaaa27ea2fb59a41df2ce7d1f290da53dae/library/core/src/panicking.rs:64:14
  17:     0x7f523850d511 - core::panicking::panic_display::h37afa093fa4d76ea
                               at /rustc/4507fdaaa27ea2fb59a41df2ce7d1f290da53dae/library/core/src/panicking.rs:147:5
  18:     0x7f523850d4bb - core::panicking::panic_str::he2f729466f8303c4
                               at /rustc/4507fdaaa27ea2fb59a41df2ce7d1f290da53dae/library/core/src/panicking.rs:131:5
  19:     0x7f523850d126 - core::option::expect_failed::hc07db22650c2c2bd
                               at /rustc/4507fdaaa27ea2fb59a41df2ce7d1f290da53dae/library/core/src/option.rs:1926:5
  20:     0x7f52376e1b67 - <rustc_metadata[857d442a14fe0f98]::rmeta::encoder::provide::{closure#0} as core[69c2f5c35675f1ee]::ops::function::FnOnce<(rustc_middle[2a277d44e6a99f4f]::ty::context::TyCtxt, rustc_span[97beb3ced854c2e2]::def_id::DefId)>>::call_once
  21:     0x7f5237b0a56a - rustc_query_system[46560f6823c6ac3e]::query::plumbing::try_execute_query::<rustc_query_impl[34788ad4354c9a05]::queries::doc_link_resolutions, rustc_query_impl[34788ad4354c9a05]::plumbing::QueryCtxt>
  22:     0x7f5237b2e9d3 - rustc_query_system[46560f6823c6ac3e]::query::plumbing::get_query::<rustc_query_impl[34788ad4354c9a05]::queries::doc_link_resolutions, rustc_query_impl[34788ad4354c9a05]::plumbing::QueryCtxt, rustc_middle[2a277d44e6a99f4f]::dep_graph::dep_node::DepKind>
  23:     0x55c117eef7d8 - <rustdoc[14416492b31d7028]::passes::collect_intra_doc_links::LinkCollector>::resolve_path
  24:     0x55c117eefa8e - <rustdoc[14416492b31d7028]::passes::collect_intra_doc_links::LinkCollector>::resolve
  25:     0x55c117ef3be9 - <rustdoc[14416492b31d7028]::passes::collect_intra_doc_links::LinkCollector as rustdoc[14416492b31d7028]::visit::DocVisitor>::visit_item
  26:     0x55c117efc63a - <rustdoc[14416492b31d7028]::passes::collect_intra_doc_links::LinkCollector as rustdoc[14416492b31d7028]::visit::DocVisitor>::visit_inner_recur
  27:     0x55c117ef6a70 - <rustdoc[14416492b31d7028]::passes::collect_intra_doc_links::LinkCollector as rustdoc[14416492b31d7028]::visit::DocVisitor>::visit_item
  28:     0x55c117eee3cf - rustdoc[14416492b31d7028]::passes::collect_intra_doc_links::collect_intra_doc_links
  29:     0x55c117e5f8fe - <rustc_session[403a5d4fc02438c2]::session::Session>::time::<rustdoc[14416492b31d7028]::clean::types::Crate, rustdoc[14416492b31d7028]::core::run_global_ctxt::{closure#7}>
  30:     0x55c117faddbc - rustdoc[14416492b31d7028]::core::run_global_ctxt
  31:     0x55c117e5fb89 - <rustc_session[403a5d4fc02438c2]::session::Session>::time::<(rustdoc[14416492b31d7028]::clean::types::Crate, rustdoc[14416492b31d7028]::config::RenderOptions, rustdoc[14416492b31d7028]::formats::cache::Cache), rustdoc[14416492b31d7028]::main_args::{closure#1}::{closure#0}::{closure#0}::{closure#0}>
  32:     0x55c117dc6dc7 - <rustc_middle[2a277d44e6a99f4f]::ty::context::GlobalCtxt>::enter::<rustdoc[14416492b31d7028]::main_args::{closure#1}::{closure#0}::{closure#0}, core[69c2f5c35675f1ee]::result::Result<(), rustc_errors[abf5e0320c3520e7]::ErrorGuaranteed>>
  33:     0x55c117d6c9f0 - <rustc_interface[3e6023fe39c52850]::interface::Compiler>::enter::<rustdoc[14416492b31d7028]::main_args::{closure#1}::{closure#0}, core[69c2f5c35675f1ee]::result::Result<(), rustc_errors[abf5e0320c3520e7]::ErrorGuaranteed>>
  34:     0x55c117e5ee9b - rustc_span[97beb3ced854c2e2]::with_source_map::<core[69c2f5c35675f1ee]::result::Result<(), rustc_errors[abf5e0320c3520e7]::ErrorGuaranteed>, rustc_interface[3e6023fe39c52850]::interface::run_compiler<core[69c2f5c35675f1ee]::result::Result<(), rustc_errors[abf5e0320c3520e7]::ErrorGuaranteed>, rustdoc[14416492b31d7028]::main_args::{closure#1}>::{closure#0}::{closure#0}>
  35:     0x55c117d6fa22 - <scoped_tls[2916abd6437a3215]::ScopedKey<rustc_span[97beb3ced854c2e2]::SessionGlobals>>::set::<rustc_interface[3e6023fe39c52850]::interface::run_compiler<core[69c2f5c35675f1ee]::result::Result<(), rustc_errors[abf5e0320c3520e7]::ErrorGuaranteed>, rustdoc[14416492b31d7028]::main_args::{closure#1}>::{closure#0}, core[69c2f5c35675f1ee]::result::Result<(), rustc_errors[abf5e0320c3520e7]::ErrorGuaranteed>>
  36:     0x55c117e72490 - std[d6315e0f51da5517]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[3e6023fe39c52850]::util::run_in_thread_pool_with_globals<rustc_interface[3e6023fe39c52850]::interface::run_compiler<core[69c2f5c35675f1ee]::result::Result<(), rustc_errors[abf5e0320c3520e7]::ErrorGuaranteed>, rustdoc[14416492b31d7028]::main_args::{closure#1}>::{closure#0}, core[69c2f5c35675f1ee]::result::Result<(), rustc_errors[abf5e0320c3520e7]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[69c2f5c35675f1ee]::result::Result<(), rustc_errors[abf5e0320c3520e7]::ErrorGuaranteed>>
  37:     0x55c117f8ff5f - <<std[d6315e0f51da5517]::thread::Builder>::spawn_unchecked_<rustc_interface[3e6023fe39c52850]::util::run_in_thread_pool_with_globals<rustc_interface[3e6023fe39c52850]::interface::run_compiler<core[69c2f5c35675f1ee]::result::Result<(), rustc_errors[abf5e0320c3520e7]::ErrorGuaranteed>, rustdoc[14416492b31d7028]::main_args::{closure#1}>::{closure#0}, core[69c2f5c35675f1ee]::result::Result<(), rustc_errors[abf5e0320c3520e7]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[69c2f5c35675f1ee]::result::Result<(), rustc_errors[abf5e0320c3520e7]::ErrorGuaranteed>>::{closure#1} as core[69c2f5c35675f1ee]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  38:     0x7f52384bdc83 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::heeffe32503a99aa5
                               at /rustc/4507fdaaa27ea2fb59a41df2ce7d1f290da53dae/library/alloc/src/boxed.rs:1988:9
  39:     0x7f52384bdc83 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h5085270dbf970bb4
                               at /rustc/4507fdaaa27ea2fb59a41df2ce7d1f290da53dae/library/alloc/src/boxed.rs:1988:9
  40:     0x7f52384bdc83 - std::sys::unix::thread::Thread::new::thread_start::h76c3abd575e0d195
                               at /rustc/4507fdaaa27ea2fb59a41df2ce7d1f290da53dae/library/std/src/sys/unix/thread.rs:108:17
  41:     0x7f5233e3bbb5 - <unknown>
  42:     0x7f5233ebdd90 - <unknown>
  43:                0x0 - <unknown>

error: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.69.0-nightly (4507fdaaa 2023-02-18) running on x86_64-unknown-linux-gnu

note: compiler flags: --crate-type lib

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [doc_link_resolutions] resolutions for documentation links for a module
end of query stack
error: could not document `notclap`
```

</p>
</details>

@rustbot label +T-rustdoc

----

searched nightlies: from nightly-2023-01-01 to nightly-2023-02-23
regressed nightly: nightly-2023-02-12
searched commit range: https://github.com/rust-lang/rust/compare/2773383a314a4b8f481ce2bed12c32de794ffbe9...585f3eef26f04440bca726c29193af7b4fa90e54
regressed commit: https://github.com/rust-lang/rust/commit/5b450244876154bc1bd134694398e80c12e00b5c

<details>
<summary>bisected with <a href='https://github.com/rust-lang/cargo-bisect-rustc'>cargo-bisect-rustc</a> v0.6.5</summary>
</details>
cc #94857

### LINKED ISSUE #108658: cargo doc failed for clap version 3.2.22
### Code

```
[package]
name = "bug_clap_doc"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = "3.2.22"
```

### Meta

`rustc --version --verbose`:
```
rustc 1.69.0-nightly (f77bfb733 2023-03-01)
binary: rustc
commit-hash: f77bfb7336f21bfe6a5fb5f7358d4406e2597289
commit-date: 2023-03-01
host: x86_64-unknown-linux-gnu
release: 1.69.0-nightly
LLVM version: 15.0.7

```

### Error output

```
thread 'rustc' panicked at 'no resolution for "ValueEnum" MacroNS DefId(0:52 ~ clap[e05b]::derive)', src/librustdoc/passes/collect_intra_doc_links.rs:391:32
stack backtrace:
   0:     0x7f6f56766afa - std::backtrace_rs::backtrace::libunwind::trace::h34498aba16c27c5d
                               at /rustc/f77bfb7336f21bfe6a5fb5f7358d4406e2597289/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x7f6f56766afa - std::backtrace_rs::backtrace::trace_unsynchronized::h9289a4d08e8f8065
                               at /rustc/f77bfb7336f21bfe6a5fb5f7358d4406e2597289/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7f6f56766afa - std::sys_common::backtrace::_print_fmt::hdc48108f3bcc17d7
                               at /rustc/f77bfb7336f21bfe6a5fb5f7358d4406e2597289/library/std/src/sys_common/backtrace.rs:65:5
   3:     0x7f6f56766afa - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h0e26d08b27a6dd1d
                               at /rustc/f77bfb7336f21bfe6a5fb5f7358d4406e2597289/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x7f6f567ca27e - core::fmt::write::h72fef7731620cf25
                               at /rustc/f77bfb7336f21bfe6a5fb5f7358d4406e2597289/library/core/src/fmt/mod.rs:1232:17
   5:     0x7f6f56759a65 - std::io::Write::write_fmt::h2c6467b36a994dc1
                               at /rustc/f77bfb7336f21bfe6a5fb5f7358d4406e2597289/library/std/src/io/mod.rs:1684:15
   6:     0x7f6f567668c5 - std::sys_common::backtrace::_print::h9ed7190f3ab4032b
                               at /rustc/f77bfb7336f21bfe6a5fb5f7358d4406e2597289/library/std/src/sys_common/backtrace.rs:47:5
   7:     0x7f6f567668c5 - std::sys_common::backtrace::print::h82d15082d5d08ddd
                               at /rustc/f77bfb7336f21bfe6a5fb5f7358d4406e2597289/library/std/src/sys_common/backtrace.rs:34:9
   8:     0x7f6f5676963f - std::panicking::default_hook::{{closure}}::h8c24b2c3eee8f54e
                               at /rustc/f77bfb7336f21bfe6a5fb5f7358d4406e2597289/library/std/src/panicking.rs:271:22
   9:     0x7f6f5676937b - std::panicking::default_hook::hcd9302e49bce35d9
                               at /rustc/f77bfb7336f21bfe6a5fb5f7358d4406e2597289/library/std/src/panicking.rs:290:9
  10:     0x7f6f599d53f5 - rustc_driver_impl[4d5cb03342eaf40]::DEFAULT_HOOK::{closure#0}::{closure#0}
  11:     0x7f6f56769e7d - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h157f8bd1e3a60b9e
                               at /rustc/f77bfb7336f21bfe6a5fb5f7358d4406e2597289/library/alloc/src/boxed.rs:2001:9
  12:     0x7f6f56769e7d - std::panicking::rust_panic_with_hook::h8dc9549cbbb83c93
                               at /rustc/f77bfb7336f21bfe6a5fb5f7358d4406e2597289/library/std/src/panicking.rs:696:13
  13:     0x7f6f56769bf9 - std::panicking::begin_panic_handler::{{closure}}::h9b0840da0b1a0862
                               at /rustc/f77bfb7336f21bfe6a5fb5f7358d4406e2597289/library/std/src/panicking.rs:583:13
  14:     0x7f6f56766f66 - std::sys_common::backtrace::__rust_end_short_backtrace::h1673dd05d1a0dc8f
                               at /rustc/f77bfb7336f21bfe6a5fb5f7358d4406e2597289/library/std/src/sys_common/backtrace.rs:137:18
  15:     0x7f6f56769902 - rust_begin_unwind
                               at /rustc/f77bfb7336f21bfe6a5fb5f7358d4406e2597289/library/std/src/panicking.rs:579:5
  16:     0x7f6f567c65e3 - core::panicking::panic_fmt::hdf244b8669b920f6
                               at /rustc/f77bfb7336f21bfe6a5fb5f7358d4406e2597289/library/core/src/panicking.rs:64:14
  17:     0x55e68beeebe4 - <rustdoc[439ec2be8d52c9a7]::passes::collect_intra_doc_links::LinkCollector>::resolve_path
  18:     0x55e68beeed0e - <rustdoc[439ec2be8d52c9a7]::passes::collect_intra_doc_links::LinkCollector>::resolve
  19:     0x55e68bef2924 - <rustdoc[439ec2be8d52c9a7]::passes::collect_intra_doc_links::LinkCollector as rustdoc[439ec2be8d52c9a7]::visit::DocVisitor>::visit_item
  20:     0x55e68befbc3a - <rustdoc[439ec2be8d52c9a7]::passes::collect_intra_doc_links::LinkCollector as rustdoc[439ec2be8d52c9a7]::visit::DocVisitor>::visit_inner_recur
  21:     0x55e68bef603c - <rustdoc[439ec2be8d52c9a7]::passes::collect_intra_doc_links::LinkCollector as rustdoc[439ec2be8d52c9a7]::visit::DocVisitor>::visit_item
  22:     0x55e68beed662 - rustdoc[439ec2be8d52c9a7]::passes::collect_intra_doc_links::collect_intra_doc_links
  23:     0x55e68be35a6e - <rustc_session[947bba98393ca4fe]::session::Session>::time::<rustdoc[439ec2be8d52c9a7]::clean::types::Crate, rustdoc[439ec2be8d52c9a7]::core::run_global_ctxt::{closure#7}>
  24:     0x55e68bf61450 - rustdoc[439ec2be8d52c9a7]::core::run_global_ctxt
  25:     0x55e68be35cf9 - <rustc_session[947bba98393ca4fe]::session::Session>::time::<(rustdoc[439ec2be8d52c9a7]::clean::types::Crate, rustdoc[439ec2be8d52c9a7]::config::RenderOptions, rustdoc[439ec2be8d52c9a7]::formats::cache::Cache), rustdoc[439ec2be8d52c9a7]::main_args::{closure#1}::{closure#0}::{closure#0}::{closure#0}>
  26:     0x55e68bd34407 - <rustc_middle[9cf018341417739a]::ty::context::GlobalCtxt>::enter::<rustdoc[439ec2be8d52c9a7]::main_args::{closure#1}::{closure#0}::{closure#0}, core[87ae5becae78eb7d]::result::Result<(), rustc_span[25e4e29a33f2c9a0]::ErrorGuaranteed>>
  27:     0x55e68bd9f67e - rustc_span[25e4e29a33f2c9a0]::with_source_map::<core[87ae5becae78eb7d]::result::Result<(), rustc_span[25e4e29a33f2c9a0]::ErrorGuaranteed>, rustc_interface[7d9b2342fec184f0]::interface::run_compiler<core[87ae5becae78eb7d]::result::Result<(), rustc_span[25e4e29a33f2c9a0]::ErrorGuaranteed>, rustdoc[439ec2be8d52c9a7]::main_args::{closure#1}>::{closure#0}::{closure#0}>
  28:     0x55e68bd11c04 - <scoped_tls[734a196e81d7ad0d]::ScopedKey<rustc_span[25e4e29a33f2c9a0]::SessionGlobals>>::set::<rustc_interface[7d9b2342fec184f0]::interface::run_compiler<core[87ae5becae78eb7d]::result::Result<(), rustc_span[25e4e29a33f2c9a0]::ErrorGuaranteed>, rustdoc[439ec2be8d52c9a7]::main_args::{closure#1}>::{closure#0}, core[87ae5becae78eb7d]::result::Result<(), rustc_span[25e4e29a33f2c9a0]::ErrorGuaranteed>>
  29:     0x55e68be48590 - std[97c6a3d67a80fb6d]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[7d9b2342fec184f0]::util::run_in_thread_pool_with_globals<rustc_interface[7d9b2342fec184f0]::interface::run_compiler<core[87ae5becae78eb7d]::result::Result<(), rustc_span[25e4e29a33f2c9a0]::ErrorGuaranteed>, rustdoc[439ec2be8d52c9a7]::main_args::{closure#1}>::{closure#0}, core[87ae5becae78eb7d]::result::Result<(), rustc_span[25e4e29a33f2c9a0]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[87ae5becae78eb7d]::result::Result<(), rustc_span[25e4e29a33f2c9a0]::ErrorGuaranteed>>
  30:     0x55e68bf1807d - <<std[97c6a3d67a80fb6d]::thread::Builder>::spawn_unchecked_<rustc_interface[7d9b2342fec184f0]::util::run_in_thread_pool_with_globals<rustc_interface[7d9b2342fec184f0]::interface::run_compiler<core[87ae5becae78eb7d]::result::Result<(), rustc_span[25e4e29a33f2c9a0]::ErrorGuaranteed>, rustdoc[439ec2be8d52c9a7]::main_args::{closure#1}>::{closure#0}, core[87ae5becae78eb7d]::result::Result<(), rustc_span[25e4e29a33f2c9a0]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[87ae5becae78eb7d]::result::Result<(), rustc_span[25e4e29a33f2c9a0]::ErrorGuaranteed>>::{closure#1} as core[87ae5becae78eb7d]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  31:     0x7f6f56773cb3 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hfea88e05acd13bd2
                               at /rustc/f77bfb7336f21bfe6a5fb5f7358d4406e2597289/library/alloc/src/boxed.rs:1987:9
  32:     0x7f6f56773cb3 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h31d26542010403e8
                               at /rustc/f77bfb7336f21bfe6a5fb5f7358d4406e2597289/library/alloc/src/boxed.rs:1987:9
  33:     0x7f6f56773cb3 - std::sys::unix::thread::Thread::new::thread_start::h6a6d49bd896852f8
                               at /rustc/f77bfb7336f21bfe6a5fb5f7358d4406e2597289/library/std/src/sys/unix/thread.rs:108:17
  34:     0x7f6f56494b43 - start_thread
                               at ./nptl/./nptl/pthread_create.c:442:8
  35:     0x7f6f56526a00 - clone3
                               at ./misc/../sysdeps/unix/sysv/linux/x86_64/clone3.S:81
  36:                0x0 - <unknown>

error: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.69.0-nightly (f77bfb733 2023-03-01) running on x86_64-unknown-linux-gnu

note: compiler flags: --crate-type lib

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
error: could not document `clap`

Caused by:
  process didn't exit successfully: `rustdoc --edition=2021 --crate-type lib --crate-name clap /home/dak/.cargo/registry/src/github.com-1ecc6299db9ec823/clap-3.2.23/src/lib.rs --cap-lints allow -o /tmp/bug_clap_doc/target/doc --cfg 'feature="atty"' --cfg 'feature="color"' --cfg 'feature="default"' --cfg 'feature="std"' --cfg 'feature="strsim"' --cfg 'feature="suggestions"' --cfg 'feature="termcolor"' --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --diagnostic-width=146 -C metadata=6887d842818c485d -L dependency=/tmp/bug_clap_doc/target/debug/deps --extern atty=/tmp/bug_clap_doc/target/debug/deps/libatty-dcb18311058c963e.rmeta --extern bitflags=/tmp/bug_clap_doc/target/debug/deps/libbitflags-f75283d3dcd3daad.rmeta --extern clap_lex=/tmp/bug_clap_doc/target/debug/deps/libclap_lex-6008a919530e6b2d.rmeta --extern indexmap=/tmp/bug_clap_doc/target/debug/deps/libindexmap-97859a7641d7b1fd.rmeta --extern strsim=/tmp/bug_clap_doc/target/debug/deps/libstrsim-95324a042c633895.rmeta --extern termcolor=/tmp/bug_clap_doc/target/debug/deps/libtermcolor-09965599c40afa4c.rmeta --extern textwrap=/tmp/bug_clap_doc/target/debug/deps/libtextwrap-4d9090cd278afea4.rmeta --crate-version 3.2.23` (exit status: 101)
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
thread 'rustc' panicked at 'no resolution for "ValueEnum" MacroNS DefId(0:52 ~ clap[e05b]::derive)', src/librustdoc/passes/collect_intra_doc_links.rs:391:32
stack backtrace:
   0: rust_begin_unwind
             at /rustc/f77bfb7336f21bfe6a5fb5f7358d4406e2597289/library/std/src/panicking.rs:579:5
   1: core::panicking::panic_fmt
             at /rustc/f77bfb7336f21bfe6a5fb5f7358d4406e2597289/library/core/src/panicking.rs:64:14
   2: <rustdoc::passes::collect_intra_doc_links::LinkCollector>::resolve_path
   3: <rustdoc::passes::collect_intra_doc_links::LinkCollector>::resolve
   4: <rustdoc::passes::collect_intra_doc_links::LinkCollector as rustdoc::visit::DocVisitor>::visit_item
   5: <rustdoc::passes::collect_intra_doc_links::LinkCollector as rustdoc::visit::DocVisitor>::visit_inner_recur
   6: <rustdoc::passes::collect_intra_doc_links::LinkCollector as rustdoc::visit::DocVisitor>::visit_item
   7: rustdoc::passes::collect_intra_doc_links::collect_intra_doc_links
   8: <rustc_session::session::Session>::time::<rustdoc::clean::types::Crate, rustdoc::core::run_global_ctxt::{closure#7}>
   9: rustdoc::core::run_global_ctxt
  10: <rustc_session::session::Session>::time::<(rustdoc::clean::types::Crate, rustdoc::config::RenderOptions, rustdoc::formats::cache::Cache), rustdoc::main_args::{closure#1}::{closure#0}::{closure#0}::{closure#0}>
  11: <rustc_middle::ty::context::GlobalCtxt>::enter::<rustdoc::main_args::{closure#1}::{closure#0}::{closure#0}, core::result::Result<(), rustc_span::ErrorGuaranteed>>
  12: rustc_span::with_source_map::<core::result::Result<(), rustc_span::ErrorGuaranteed>, rustc_interface::interface::run_compiler<core::result::Result<(), rustc_span::ErrorGuaranteed>, rustdoc::main_args::{closure#1}>::{closure#0}::{closure#0}>
  13: <scoped_tls::ScopedKey<rustc_span::SessionGlobals>>::set::<rustc_interface::interface::run_compiler<core::result::Result<(), rustc_span::ErrorGuaranteed>, rustdoc::main_args::{closure#1}>::{closure#0}, core::result::Result<(), rustc_span::ErrorGuaranteed>>
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

error: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.69.0-nightly (f77bfb733 2023-03-01) running on x86_64-unknown-linux-gnu

note: compiler flags: --crate-type lib

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
error: could not document `clap`

Caused by:
  process didn't exit successfully: `rustdoc --edition=2021 --crate-type lib --crate-name clap /home/dak/.cargo/registry/src/github.com-1ecc6299db9ec823/clap-3.2.23/src/lib.rs --cap-lints allow -o /tmp/bug_clap_doc/target/doc --cfg 'feature="atty"' --cfg 'feature="color"' --cfg 'feature="default"' --cfg 'feature="std"' --cfg 'feature="strsim"' --cfg 'feature="suggestions"' --cfg 'feature="termcolor"' --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --diagnostic-width=146 -C metadata=6887d842818c485d -L dependency=/tmp/bug_clap_doc/target/debug/deps --extern atty=/tmp/bug_clap_doc/target/debug/deps/libatty-dcb18311058c963e.rmeta --extern bitflags=/tmp/bug_clap_doc/target/debug/deps/libbitflags-f75283d3dcd3daad.rmeta --extern clap_lex=/tmp/bug_clap_doc/target/debug/deps/libclap_lex-6008a919530e6b2d.rmeta --extern indexmap=/tmp/bug_clap_doc/target/debug/deps/libindexmap-97859a7641d7b1fd.rmeta --extern strsim=/tmp/bug_clap_doc/target/debug/deps/libstrsim-95324a042c633895.rmeta --extern termcolor=/tmp/bug_clap_doc/target/debug/deps/libtermcolor-09965599c40afa4c.rmeta --extern textwrap=/tmp/bug_clap_doc/target/debug/deps/libtextwrap-4d9090cd278afea4.rmeta --crate-version 3.2.23` (exit status: 101)
```

</p>
</details>

### PR DESCRIPTION
**Pull request by petrochenkov**
Fixes https://github.com/rust-lang/rust/issues/108061.
Fixes https://github.com/rust-lang/rust/issues/108334.
Fixes https://github.com/rust-lang/rust/issues/108378.
Fixes https://github.com/rust-lang/rust/issues/108658.

### CODE REVIEW

**Comment by clubby789** [comment]
Also #108658, #108501, and #108658 I believe

File: src/librustdoc/clean/mod.rs [hunk 1]
```diff
@@ -2373,21 +2374,22 @@ fn clean_maybe_renamed_item<'tcx>(
             _ => unreachable!("not yet converted"),
         };
 
-        let mut extra_attrs = Vec::new();
+        let mut import_attrs = Vec::new();
```
Comment (GuillaumeGomez) [inline src/librustdoc/clean/mod.rs:2377]: I'd nitpick to rename it into `import_attrs` but feel free to ignore it.

**Review by GuillaumeGomez — APPROVED** [review]

File: src/librustdoc/clean/mod.rs (hunk 1 above)
Comment (petrochenkov) [reply src/librustdoc/clean/mod.rs:2377]: If there are multiple imports there, then there should be multiple `import_id`s and their parents, so there's still a lot to fix here besides the naming.

Comment (GuillaumeGomez) [reply src/librustdoc/clean/mod.rs:2377]: Just to be sure we're talking about this same thing:

```rust
mod foo {
    struct A;

    pub use self::A as B;
    pub use self::B as C;
}
pub use foo::C as D;
```

Intermediate imports are `B` and `C` and they are the ones we're gathering attributes from.

Comment (petrochenkov) [reply src/librustdoc/clean/mod.rs:2377]: Yes, and their attributes should not be all merged together, but should instead be broken into groups with a separate group with a separate parent id for every `use` item in the reexport chain.

Comment (GuillaumeGomez) [reply src/librustdoc/clean/mod.rs:2377]: Do you have cases where it would be problematic by any chance?

Comment (petrochenkov) [reply src/librustdoc/clean/mod.rs:2377]: Same as the test in this PR, but with a doc link on an intermediate import.

Comment (GuillaumeGomez) [reply src/librustdoc/clean/mod.rs:2377]: Ok, I'm gonna send a fix for that too in the next days. Thanks for fixing this bug already.

Comment (petrochenkov) [reply src/librustdoc/clean/mod.rs:2377]: I'm not sure how many places in rustdoc merge attributes from different items, but all of them should ideally apply the same fix - a separate parent per item.

**Comment by compiler-errors** [comment]
Adding context to the beta nomination -- @kpreid asked for this to be nominated because they hit the problem on beta (or so it seems, and linked to these logs: https://github.com/kpreid/exhaust/actions/runs/4653637162/jobs/8234695803?pr=15).

@petrochenkov, do you know when the regression fixed by this PR was originally introduced into the compiler? That's probably useful information in helping pinpoint whether this should be backported or if there's another fix that needs to be backported to fix @kpreid's problem instead.

**Comment by petrochenkov** [comment]
@compiler-errors 
>do you know when the regression fixed by this PR was originally introduced into the compiler?

In https://github.com/rust-lang/rust/pull/94857.
It's not exactly a regression, but rather a silent incorrect behavior turning into ICE.
