### PR TITLE
Change `binary_asm_labels` to only fire on x86 and x86_64

### LINKED ISSUE #127821: `binary_asm_labels` should suggest a change
### Code

```Rust
use std::arch::asm;

#[cfg(target_arch = "x86_64")]
fn main() {
    let mut counter: u64 = 0;
    unsafe {
        asm!(
            "0:",
            "inc {counter}",
            "cmp {counter}, 10",
            "jnz 0b",
            counter = inout(reg) counter,
        );
    }
    dbg!(counter);  // prints 10
}
```

### Current output

```Shell
error: avoid using labels containing only the digits `0` and `1` in inline assembly
   --> src/aarch64_linux.rs:142:22
    |
142 |                     "0:",
    |                      ^ use a different label that doesn't start with `0` or `1`
...
271 | foreach_cas!(compare_and_swap);
    | ------------------------------ in this macro invocation
    |
    = note: an LLVM bug makes these labels ambiguous with a binary literal number
    = note: `#[deny(binary_asm_labels)]` on by default
    = note: this error originates in the macro `compare_and_swap` which comes from the expansion of the macro `foreach_cas` (in Nightly builds, run with -Z macro-backtrace for more info)
```

### Desired output

Suggest a change that fixes this.

### Rationale and extra context

I don't see any documentation about `binary_asm_labels`, so we should probably suggest what to do instead. I think the correct thing is to start numbering from 2.

The lint was added in #126922 (cc @asquared31415) to fix issue https://github.com/rust-lang/rust/issues/94426.

### Other cases

_No response_

### Rust Version

```Shell
1.81.0-nightly (24d2ac0b5 2024-07-15)
```

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by tgross35**
In <https://github.com/rust-lang/rust/pull/126922>, the `binary_asm_labels` lint was added which flags labels such as `0:` and `1:`. Before that change, LLVM was giving a confusing error on x86/x86_64 because of an incorrect interpretation.

However, targets other than x86 and x86_64 never had the error message and have not been a problem. This means that the lint was causing code that previously worked to start failing (e.g. `compiler_builtins`), rather than only providing a more clear messages where there has always been an error.

Adjust the lint to only fire on x86 and x86_64 assembly to avoid this regression.

Also update the help message.

Fixes: https://github.com/rust-lang/rust/issues/127821

### CODE REVIEW

File: compiler/rustc_lint/src/lints.rs [hunk 1]
```diff
@@ -2066,6 +2066,7 @@ pub enum InvalidAsmLabel {
         missing_precise_span: bool,
     },
     #[diag(lint_invalid_asm_label_binary)]
+    #[help]
```
Comment (tgross35) [inline compiler/rustc_lint/src/lints.rs:2069]: What do I need to do to make this propagate to https://github.com/rust-lang/rust/blob/5753b3067662e17a69b54b9418dbc37b73769a84/tests/ui/asm/binary_asm_labels.stderr#L1-L8?

File: compiler/rustc_lint/messages.ftl [hunk 2]
```diff
@@ -403,8 +403,9 @@ lint_inner_macro_attribute_unstable = inner macro attributes are unstable
 
 lint_invalid_asm_label_binary = avoid using labels containing only the digits `0` and `1` in inline assembly
     .label = use a different label that doesn't start with `0` or `1`
-    .note = an LLVM bug makes these labels ambiguous with a binary literal number
-    .note = see <https://bugs.llvm.org/show_bug.cgi?id=36144> for more information
+    .help = Start numbering with `2` instead
```
Comment (Urgau) [inline compiler/rustc_lint/messages.ftl:406]: Diagnostic messages should start with a lower case letter.
```suggestion
    .help = start numbering with `2` instead
```

File: compiler/rustc_lint/messages.ftl [hunk 3]
```diff
@@ -403,8 +403,9 @@ lint_inner_macro_attribute_unstable = inner macro attributes are unstable
...
+    .note = an LLVM bug makes these labels ambiguous with a binary literal number on x86
+    .note = see <https://github.com/llvm/llvm-project/issues/99547> for more information
```
Comment (Urgau) [inline compiler/rustc_lint/messages.ftl:408]: Pre-existing, but I don't think this works like this; this line should use a different identifier and be referenced separately in the `derive(LintDiagnostic)` (i.e. `#[note(lint_issue)]` or whatever).

File: compiler/rustc_lint/src/lints.rs (hunk 1 above)
Comment (Urgau) [reply compiler/rustc_lint/src/lints.rs:2069]: It should work. The test is gated on `only-x86_64`, so if you weren't on x86_64 it wouldn't be blessed.

File: compiler/rustc_lint/messages.ftl (hunk 3 above)
Comment (tgross35) [reply compiler/rustc_lint/messages.ftl:408]: Oh, that's probably why my `.note` wasn't showing up either. Thanks, I'll try it

File: compiler/rustc_lint/src/lints.rs (hunk 1 above)
Comment (tgross35) [reply compiler/rustc_lint/src/lints.rs:2069]: Ah, maybe I should try running it on an actual x86 machine

**Comment by tgross35** [comment]
Tested locally on both x86 and aarch64.

r? @Urgau

**Comment by estebank** [comment]
Ideally, the lint would not gate on the platform being compiled, but rather gated on whether the code *could* be run from x86. Namely, if the `asm` is behind a `cfg` flag that limits the code to anything other than x86. That being said, I believe that for now this is a reasonable compromise.

@bors r+

File: compiler/rustc_lint/messages.ftl [hunk 4]
```diff
@@ -403,8 +403,9 @@ lint_inner_macro_attribute_unstable = inner macro attributes are unstable
 
 lint_invalid_asm_label_binary = avoid using labels containing only the digits `0` and `1` in inline assembly
     .label = use a different label that doesn't start with `0` or `1`
-    .note = an LLVM bug makes these labels ambiguous with a binary literal number
-    .note = see <https://bugs.llvm.org/show_bug.cgi?id=36144> for more information
+    .help = start numbering with `2` instead
+    .note1 = an LLVM bug makes these labels ambiguous with a binary literal number on x86
+    .note2 = see <https://github.com/llvm/llvm-project/issues/99547> for more information
```
Comment (Urgau) [inline compiler/rustc_lint/messages.ftl:408]: nit: it isn't necessary for both of them to use a different identifier, only of them needs to, the other one can stay as always (`.note = ...` and `#[note]`)

Comment (tgross35) [reply compiler/rustc_lint/messages.ftl:408]: I just mirrored a few lines up in https://github.com/rust-lang/rust/pull/127935/files#diff-4a2362ab93352b636e03b023fecbe61e96c3a07f1be1393d67bbd87d87374f50L2060-L2063

Seems like we should have a way to detect unused `.note`s somehow, since the second wasn't being used until this change.

Comment (Urgau) [reply compiler/rustc_lint/messages.ftl:408]: > Seems like we should have a way to detect unused labels, since the second .note wasn't being used until this change.

We should indeed.

Anyway, no need to change anything. Just wanted you to be aware of this.

Comment (tgross35) [reply compiler/rustc_lint/messages.ftl:408]: Looks like it's at least been considered https://github.com/rust-lang/rust/issues/110754

**Comment by estebank** [comment]
> Does that kind of machinery exist? I thought if it was behind a cfg then it doesn't even know the asm is there.

We have a very basic [collection of items that got cfg'd out for the purposes of telling users that an item that wasn't found is behind a feature flag](https://github.com/rust-lang/rust/blob/8eb51852a87dd2640fbd95019ff1124b38ae8b78/compiler/rustc_resolve/src/diagnostics.rs#L2502-L2540). [We collect those during expansion](https://github.com/rust-lang/rust/blob/a23917cfd07b309f32603c6acb81b63aad8504e7/compiler/rustc_expand/src/expand.rs#L1964-L1968), which would make my request harder to accomplish, as you would need to implement the lint to be able to work with an `ast::ExprKind::InlineAsm` (as opposed to the current `hir::ExprKind::InlineAsm`) but there's precedent.

**Comment by tgross35** [comment]
For this specific lint, it seems like effort is probably better spent fixing LLVM than attempting to improve the ergonomics much more. But being able to leverage that for other inline asm sounds amazing, since it is so platform dependent and easy to make mistakes, we should be able to at least perform Rust's validation on it.

I'll update https://github.com/rust-lang/rust/issues/127938 to reflect that if it sounds accurate.

**Comment by tgross35** [comment]
I didn't update the docs so it tried to run the assembly example on all platforms. Added a commit to fix this, looking at other tests I guess the best thing we can do is `ignore` the doctest and update the output manually. `lint-docs` tests pass locally on my aarch64 machine now.

I'll let somebody double check the changes (@estebank), @rustbot review

**Comment by Urgau** [comment]
Changes looks good.

@bors r=estebank,Urgau
