### PR TITLE
bootstrap: Disable initial-exec TLS model on powerpc

### LINKED ISSUE #81334: Many tests failing with "Couldn't compile the test" on 32-bit PowerPC with 1.49 beta
Since 1.49 beta, many tests fail on 32-bit PowerPC with the error that the test could not be compiled:

```
running 1 test
test src/test/rustdoc/async-move-doctest.rs - (line 8) ... FAILED

failures:

---- src/test/rustdoc/async-move-doctest.rs - (line 8) stdout ----
Couldn't compile the test.

failures:
    src/test/rustdoc/async-move-doctest.rs - (line 8)

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out
```

I have not bisected the issue yet.

Full log in: https://buildd.debian.org/status/fetch.php?pkg=rustc&arch=powerpc&ver=1.49.0%7Ebeta.4%2Bdfsg1-1%7Eexp1&stamp=1611482142&raw=0

CC @jrtc27 @infinity0 @smaeul @mator

### PR DESCRIPTION
**Pull request by glaubitz**
Fixes #81334.

### CODE REVIEW

**Comment by glaubitz** [comment]
Please note: I have not fully tested this change yet. So please don't merge it yet although I'm sure it's correct.

File: src/bootstrap/builder.rs [hunk 1]
```diff
@@ -1237,6 +1237,7 @@ impl<'a> Builder<'a> {
         // efficient initial-exec TLS model. This doesn't work with `dlopen`,
         // so we can't use it by default in general, but we can use it for tools
         // and our own internal libraries.
+        #[cfg(not(target_arch = "powerpc"))]
```
Comment (mati865) [inline src/bootstrap/builder.rs:1240]: I think [`cfg!` macro](https://doc.rust-lang.org/rust-by-example/attribute/cfg.html) would be nicer here.

Comment (Mark-Simulacrum) [reply src/bootstrap/builder.rs:1240]: Hm, I'm surprised to see cfg here at all; I'd expect this to check target.contains("powerpc") or so...

**Comment by Aaron1011** [comment]
If this TLS mode is completely unsupported on powerpc, then I think we should emit an error whenver someone tries to specify it on the command line. Otherwise, anyone else using `-Ztls-model` will run to this issue. This could be done in a follow-up PR.

File: src/bootstrap/builder.rs (hunk 1 above)
Comment (infinity0) [reply src/bootstrap/builder.rs:1240]: I believe `cfg` would be wrong when cross-compiling - since "target" here refers to the target of `bootstrap` which would be the host (native) platform?

Comment (infinity0) [reply src/bootstrap/builder.rs:1240]: @glaubitz try `if target.triple.startswith("powerpc-") { }` instead

Comment (glaubitz) [reply src/bootstrap/builder.rs]: Done. I'm testing the change now on a real PowerPC machine to see if it actually works.

**Comment by glaubitz** [comment]
> If this TLS mode is completely unsupported on powerpc, then I think we should emit an error whenver someone tries to specify it on the command line. Otherwise, anyone else using `-Ztls-model` will run to this issue. This could be done in a follow-up PR.

Is there some sort of feature matrix that Rust is carrying internally for every architecture where this information could be stored as a flag? I would guess this bug could affect the upcoming m68k port as well.

Plus, such a feature matrix could be used to determine whether a certain test is run or not. Currently, all tests seem to be checking per architecture rather than per feature.

**Comment by petrochenkov** [comment]
>If this TLS mode is completely unsupported on powerpc, then I think we should emit an error whenver someone tries to specify it on the command line.

This mode is a hint, if a "initial-exec" hint is useless for a given target (like e.g. TLS models not generally mapping on Windows-based target), then it should be demoted to a weaker hint.
If initial-exec not being supported on powerpc is just some LLVM bug, then it can be demoted to a weaker mode as well, until the bug is fixed.

File: src/bootstrap/builder.rs (hunk 1 above)
Comment (glaubitz) [reply src/bootstrap/builder.rs]: The change as suggested by @infinity0 works fine and fixes the problem on 32-bit PowerPC.

But please feel free to use a different approach if anyone has a better idea. I don't insist on my particular approach.

**Comment by crlf0710** [comment]
@glaubitz Ping from triage, what's next steps here?

**Comment by bstrie** [comment]
@glaubitz Are you intending to add anything more to this PR, or shall I tag this for review?

**Comment by glaubitz** [comment]
@bkaestner I don't have any strong preference, the fix works for me. Feel free to merge it as-is or replace it with a better solution.

**Comment by bkaestner** [comment]
> @bkaestner I don't have any strong preference, the fix works for me. Feel free to merge it as-is or replace it with a better solution.

@bstrie I believe this message was meant for you.

**Comment by glaubitz** [comment]
Oops, sorry. Two people starting with "@b" in the thread and I just had only one coffee this morning :).

**Comment by glaubitz** [comment]
> @glaubitz Are you intending to add anything more to this PR, or shall I tag this for review?

I don't want to add anything else. Could you tag this for review? Thanks!

**Comment by Mark-Simulacrum** [comment]
Filed https://github.com/rust-lang/rust/issues/87821 to track the automatic reduction or error, but for now let's @bors r+
