### PR TITLE
Fix UB from misalignment and provenance widening in `std::sys::windows`

### LINKED ISSUE #81996: repr(C) is unsound on MSVC targets
Consider

```rust
#![allow(dead_code)]

use std::mem;

#[no_mangle]
pub fn sizeof_empty_struct_1() -> usize {
    #[repr(C)]
    struct EmptyS1 {
        f: [i64; 0],
    }

    // Expected: 4
    // Actual: 0
    mem::size_of::<EmptyS1>()
}

#[no_mangle]
pub fn sizeof_empty_struct_2() -> usize {
    #[repr(C, align(8))]
    struct X {
        i: i32,
    }

    #[repr(C)]
    struct EmptyS2 {
        x: [X; 0],
    }

    // Expected: 8
    // Actual: 0
    mem::size_of::<EmptyS2>()
}

#[no_mangle]
pub fn sizeof_enum() -> usize {
    #[repr(C)]
    enum E {
        A = 1111111111111111111
    }

    // Expected: 4
    // Actual: 8
    mem::size_of::<E>()
}

#[no_mangle]
pub fn sizeof_empty_union_1() -> usize {
    #[repr(C)]
    union EmptyU1 {
        f: [i8; 0],
    }

    // Expected: 1
    // Actual: 0
    mem::size_of::<EmptyU1>()
}

#[no_mangle]
pub fn sizeof_empty_union_2() -> usize {
    #[repr(C)]
    union EmptyU2 {
        f: [i64; 0],
    }

    // Expected: 8
    // Actual: 0
    mem::size_of::<EmptyU2>()
}
```

and the corresponding MSVC output: https://godbolt.org/z/csv4qc

The behavior of MSVC is described here as far as it is known to me: https://github.com/mahkoh/repr-c/blob/a04e931b67eed500aea672587492bd7335ea549d/repc/impl/src/builder/msvc.rs#L215-L236

### PR DESCRIPTION
**Pull request by thomcc**
This fixes two types of UB:

1. Reading past the end of a reference in types like `&c::REPARSE_DATA_BUFFER` (see https://github.com/rust-lang/unsafe-code-guidelines/issues/256). This is fixed by using `addr_of!`. I think there are probably a couple more cases where we do this for other structures, and will look into it in a bit.

2. Failing to ensure that a `[u8; N]` on the stack is sufficiently aligned to convert to a `REPARSE_DATA_BUFFER`. ~~This was done by introducing a new `AlignedAs` struct that allows aligning one type to the alignment of another type. I expect there are other places where we have this issue too, or I wouldn't introduce this type, but will get to them after this lands.~~

    ~~Worth noting, it *is* implemented in a way that can cause problems depending on how we fix #81996, but this would be caught by the test I added (and presumably if we decide to fix that in a way that would break this code, we'd also introduce a `#[repr(simple)]` or `#[repr(linear)]` as a replacement for this usage of `#[repr(C)]`).~~
    
    Edit: None of that is still in the code, I just went with a `Align8` since that's all we'll need for almost everything we want to call.

These are more or less "potential UB" since it's likely at the moment everything works fine, although the alignment not causing issues might just be down to luck (and x86 being forgiving).

~~NB: I've only ensured this check builds, but will run tests soon.~~ All tests pass, including stage2 compiler tests.

r? @ChrisDenton

### CODE REVIEW

File: library/std/src/sys/windows/fs.rs [hunk 1]
```diff
@@ -47,6 +47,9 @@ pub struct ReadDir {
     first: Option<c::WIN32_FIND_DATAW>,
 }
 
+type AlignedReparseBuf =
+    AlignedAs<c::REPARSE_DATA_BUFFER, [u8; c::MAXIMUM_REPARSE_DATA_BUFFER_SIZE]>;
```
Comment (thomcc) [inline library/std/src/sys/windows/fs.rs:51]: I'll do a followup that makes this use `MaybeUninit<u8>`. I was going to do that first, but then noticed that this code was wrong.

File: library/std/src/sys/windows/c.rs [hunk 2]
```diff
@@ -511,6 +513,8 @@ pub struct REPARSE_DATA_BUFFER {
     pub rest: (),
```
Comment (ChrisDenton) [inline library/std/src/sys/windows/c.rs:513]: Does this really need to end with a zst? Given the issues, it might be worth exploring other options. The usual way to do this in msvc is to end with `[u8; 1]` (or similar). Or it could be a union of supported reparse types. Or it could be both, which is the [canonical definition](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/ntifs/ns-ntifs-_reparse_data_buffer).

An alternative is to (ab)use the fact that the `REPARSE_DATA_BUFFER` header is 64bits on all supported platforms. Which is convenient for aligning the data (and is likely no accident).

Comment (thomcc) [reply library/std/src/sys/windows/c.rs:513]: I think it's not great for it to end in a ZST, yeah.

Comment (thomcc) [reply library/std/src/sys/windows/c.rs:513]: This wouldn't really change the situation with UB that much though -- we still couldn't return a `&REPARSE_DATA_BUFFER` without narrowing the provenance such that it'd be UB to access `PathBuffer`.

Comment (ChrisDenton) [reply library/std/src/sys/windows/c.rs:513]: Yeah, that's true. I'm not minded to block this PR on removing the zst but I do think we should be aiming to do so, and in general leaning toward not using them in Windows ffi so as to side-step #81996 completely. Especially as the Windows API doesn't really use them.

Comment (thomcc) [reply library/std/src/sys/windows/c.rs:513]: I think that one would be fine, the issue isn't with all ZSTs, so much as zero-sized arrays like `[T; 0]` (since in a struct `T foo[0];` is the same as `T *foo;` on MSVC).

File: library/std/src/sys/windows/c.rs [hunk 3]
```diff
@@ -511,6 +513,8 @@ pub struct REPARSE_DATA_BUFFER {
...
 }
 
+/// NB: Use carefully! In general using this as a reference is likely to get the
+/// provenance wrong for the `PathBuffer` field!
```
Comment (ChrisDenton) [inline library/std/src/sys/windows/c.rs:517]: This is fine but it is a shame we need to keep repeating variations of this comment. But eh, it's fine. Encapsulating the unsafely is what the higher level APIs are for.

File: library/std/src/sys/windows/mod.rs [hunk 4]
```diff
@@ -329,3 +329,26 @@ pub fn abort_internal() -> ! {
...
+
+/// Used for some win32 buffers which are stack allocated, for example:
+/// `AlignedAs<c::REPARSE_DATA_BUFFER, [u8; c::MAXIMUM_REPARSE_DATA_BUFFER_SIZE]>`
+#[repr(C)]
+#[derive(Copy, Clone)]
+pub struct AlignedAs<Aligner, Alignee: ?Sized> {
+    /// Use `[Aligner; 0]` as a sort of `PhantomAlignNextField<Aligner>`. This
+    /// is a bit of a hack, and could break (in a way that's caught by tests) if
+    /// #81996 is fixed.
+    aligner: [Aligner; 0],
```
Comment (ChrisDenton) [inline library/std/src/sys/windows/mod.rs:341]: I'm not especially enthusiastic about more hacks but it is at least more principled than what came before, and the tests help ensure it works. So... it's fine.

File: library/std/src/sys/windows/fs.rs [hunk 5]
```diff
@@ -389,7 +392,7 @@ impl File {
             attr.file_size = info.AllocationSize as u64;
             attr.number_of_links = Some(info.NumberOfLinks);
             if attr.file_type().is_reparse_point() {
-                let mut b = [0; c::MAXIMUM_REPARSE_DATA_BUFFER_SIZE];
+                let mut b = AlignedReparseBuf::new([0; c::MAXIMUM_REPARSE_DATA_BUFFER_SIZE]);
                 if let Ok((_, buf)) = self.reparse_point(&mut b) {
                     attr.reparse_tag = buf.ReparseTag;
                 }
```
Comment (ChrisDenton) [inline library/std/src/sys/windows/fs.rs:398]: Hm, you might want to update this so it matches the (non-UWP) code above?

**Review by ChrisDenton — COMMENTED** [review]
Ok, I think this is basically fine. Only one thing that I think needs to be addressed, the other comments are just me being resigned to Rust not having better support for this atm. 🤷

**Comment by ChrisDenton** [comment]
Oh, just noticed, I think you missed a spot:

https://github.com/rust-lang/rust/blob/1b8025a24c4b063d2566671f0664e5dfc263c2a4/library/std/src/sys/windows/fs.rs#L1348

Though this is in `symlink_junction` which is only used for tests..

**Comment by thomcc** [comment]
> EDIT: Wait no that's a different buffer... for some reason.

It's still wrong the way it's written, I think?

That said there are a couple places in this file that are like this that I didn't touch (for example, it's not 100% clear to me what the best fix for the DirBuff stuff would be, but I was just going to tackle it later).

File: library/std/src/sys/windows/c.rs (hunk 3 above)
Comment (thomcc) [reply library/std/src/sys/windows/c.rs:517]: Beats someone missing it -- by repeating it, it shows up in auto-complete in rust-analyzer.

**Comment by ChrisDenton** [comment]
> It's still wrong the way it's written, I think?

Yeah, but I'm ok with this PR being more focused. That said, I'm also more than happy for you to fix that too!

**Comment by thomcc** [comment]
I fixed it. It actually was wrong in another way, since it was turning a pointer derived from `data.as_ptr()` into a mutable pointer, which is wrong because it's mutating a pointer derived from `&self`, which can't give out mutable pointers.

(Tragically `as_mut_ptr()` would also be wrong -- that goes through `&mut self` which would invalidate the other pointers derived from it, so I just added a new local for `data.value.as_mut_ptr()`)

File: library/std/src/sys/windows/fs.rs (hunk 5 above)
Comment (thomcc) [reply library/std/src/sys/windows/fs.rs]: Nice catch. UWP passes a check build now, at least.

**Comment by ChrisDenton** [comment]
lgtm

@bors r+

**Comment by thomcc** [comment]
@bors r-

After a quick discussion with @ChrisDenton I'm actually going to simplify this a bit.

**Comment by thomcc** [comment]
I'll remove the `donotland` CI changes after it passes (don't have a convenient windows box right now)

File: library/std/src/sys/windows/fs.rs [hunk 6]
```diff
@@ -696,13 +705,21 @@ impl<'a> Iterator for DirBuffIter<'a> {
...
+            let header_sz = mem::size_of::<c::FILE_ID_BOTH_DIR_INFO>();
+            assert!(buffer.len() >= header_sz);
             let info = buffer.as_ptr().cast::<c::FILE_ID_BOTH_DIR_INFO>();
-            let next_entry = (*info).NextEntryOffset as usize;
+            assert!(info.is_aligned());
+            let len_bytes = (*info).FileNameLength as usize;
+            // Note: we don't need `header_sz - 2` here, since the `[WCHAR; 1]`
+            // in the header and the trailing nul char (which always present but
+            // not counted in `len_bytes`) cancel each-other out.
+            assert!(buffer.len() >= header_sz + len_bytes);
```
Comment (ChrisDenton) [inline library/std/src/sys/windows/fs.rs:716]: I think some of these asserts are a touch paranoid because we should be able to assume the OS is acting sensibly when filling the buffer. However, I don't think they do any harm either and it is possible they could catch programmer error or problems with miri's emulation.

Comment (thomcc) [reply library/std/src/sys/windows/fs.rs]: These checks are too annoying to write correctly without `offset_of!`, so I removed the ones not related to alignment.

**Comment by thomcc** [comment]
Windows passes (https://github.com/rust-lang/rust/runs/8091513764?check_suite_focus=true, https://github.com/rust-lang/rust/runs/8091513602?check_suite_focus=true), so I've undone the CI commit.
