### PR TITLE
Fix rendering of stabilization version for trait implementors

### LINKED ISSUE #80777: rustdoc renders stability attribute for trait implementations on type pages, but not trait pages
For example, `impl BitOr<NonZeroU128> for NonZeroU128` being stable since 1.45.0 is visible [on the page for `NonZeroU128`](https://doc.rust-lang.org/core/num/struct.NonZeroU128.html#impl-BitOr%3CNonZeroU128%3E):

Screenshot_2021-01-07 core num NonZeroU128 - Rust

but not [on the page for `BitOr`](https://doc.rust-lang.org/core/ops/trait.BitOr.html#impl-BitOr%3CNonZeroU128%3E):

Screenshot_2021-01-07 core ops BitOr - Rust

(also the latter doesn't have `BitOr` linkified while the former has `NonZeroU128` linkified, but self-links seem less important)

### PR DESCRIPTION
**Pull request by LeSeulArtichaut**
Rustdoc compares an item's stabilization version with its parent's to not render it if they are the same. Here, the implementor was compared with itself, resulting in the stabilization version never getting shown.

This probably needs a test.

Fixes #80777.
r? @jyn514

### CODE REVIEW

File: src/librustdoc/html/render/mod.rs [hunk 1]
```diff
@@ -2471,7 +2471,7 @@ fn item_function(w: &mut Buffer, cx: &Context<'_>, it: &clean::Item, f: &clean::
 fn render_implementor(
     cx: &Context<'_>,
     implementor: &Impl,
-    parent: &clean::Item,
+    trait_: &clean::Item,
```
Comment (jyn514) [inline src/librustdoc/html/render/mod.rs:2474]: Are you sure this is the trait? I would expect it to be the impl block, in which case this seems fishy because `unstable` and `stable` are ignored on impls blocks.

**Review by jyn514 — COMMENTED** [review]
> This probably needs a test.

Yes, please add a test in src/test/rustdoc. There are instructions at https://rustc-dev-guide.rust-lang.org/rustdoc-internals.html#dotting-is-and-crossing-ts.

File: src/librustdoc/html/render/mod.rs (hunk 1 above)
Comment (LeSeulArtichaut) [reply src/librustdoc/html/render/mod.rs:2474]: It is passed here:

https://github.com/rust-lang/rust/blob/4d0dd02ee07bddad9136f95c9f7846ebf3eb3fc5/src/librustdoc/html/render/mod.rs#L2803-L2805

where `it` comes from `item` in:

https://github.com/rust-lang/rust/blob/4d0dd02ee07bddad9136f95c9f7846ebf3eb3fc5/src/librustdoc/html/render/mod.rs#L1796

and `item` is the `Item` being matched on, so I assume it is the trait.

> I would expect it to be the impl block, in which case this seems fishy because `unstable` and `stable` are ignored on impls blocks.

Are they? They are used a lot in the standard library. Example: https://github.com/rust-lang/rust/blob/4d0dd02ee07bddad9136f95c9f7846ebf3eb3fc5/library/alloc/src/string.rs#L1821-L1826

Comment (jyn514) [reply src/librustdoc/html/render/mod.rs:2474]: Nice archeology, you convinced me :)

> Are they? They are used a lot in the standard library. Example: 

Hmm, maybe just `unstable` is ignored. But it is definitely ignored: https://github.com/rust-lang/rust/blob/4d0dd02ee07bddad9136f95c9f7846ebf3eb3fc5/compiler/rustc_lint_defs/src/builtin.rs#L2810.

Comment (LeSeulArtichaut) [reply src/librustdoc/html/render/mod.rs:2474]: Also I've tested setting the trait's `since` version to the same version as the impl, which worked (hid the version from the implementor section), so I think this is correct.

**Comment by LeSeulArtichaut** [comment]
@jyn514 Added `src/test/rustdoc/implementor-stable-version.rs`

File: src/test/rustdoc/implementor-stable-version.rs [hunk 2]
```diff
@@ -0,0 +1,18 @@
+#![crate_name = "foo"]
+
+#![feature(staged_api)]
+
+// @has foo/trait.Foo.html '//*[@id="impl-Foo-1"]//span[@class="since"]' '2.0'
+// @!has - '//*[@id="impl-Foo"]//span[@class="since"]' '1.0'
```
Comment (jyn514) [inline src/test/rustdoc/implementor-stable-version.rs:6]: I'm not super happy about depending on the order the IDs are generated. Could you do this by the name of the struct instead, maybe?

Comment (LeSeulArtichaut) [reply src/test/rustdoc/implementor-stable-version.rs:6]: How could I do that? This is my very first rustdoc test 😄

Comment (jyn514) [reply src/test/rustdoc/implementor-stable-version.rs:6]: Hmm, I'm not actually sure, since the `code` block also has other nested markup. @GuillaumeGomez do you have ideas?

Comment (LeSeulArtichaut) [reply src/test/rustdoc/implementor-stable-version.rs:6]: Oh, I could just have two traits instead

Comment (GuillaumeGomez) [reply src/test/rustdoc/implementor-stable-version.rs:6]: I'd try to go through classes if you don't want to go through IDs. In this case, it seems safer not to use IDs. Try to give a path as unique as possible based on the classes and some other attributes.

Comment (GuillaumeGomez) [reply src/test/rustdoc/implementor-stable-version.rs:6]: And yes, the simpler the rust code, the simpler the HTML checks. :p

**Comment by jyn514** [comment]
r=me with CI passing. Thanks for working on this!

@bors delegate=LeSeulArtichaut
