### PR TITLE
Flush errors before deep normalize in `dropck_outlives`

### LINKED ISSUE #140462: Non-implemented trait causes ICE
### Code

```Rust
use std::marker::PhantomData;

trait Decode<'a>: Sized {
    type Decoder: Decoder<'a, Self>;
}

trait Decoder<'a, T> {}

struct A {
    b: B,
}

impl<'a> Decode<'a> for A
{
    type Decoder = ADecoder<'a>;
}

pub struct ADecoder<'a> {
    b: <B as Decode<'a>>::Decoder,
}

impl<'a> Default for ADecoder<'a> {
    fn default() -> Self {
        Self {
            b: Default::default(),
        }
    }
}

impl<'a> Decoder<'a, A> for ADecoder<'a> {}

struct NonImplementedDecode;

struct B {
    non_implemented: NonImplementedDecode,
    c: C,
}

impl<'a> Decode<'a> for B
{
    type Decoder = BDecoder<'a>;
}
pub struct BDecoder<'a> {
    non_implemented: <NonImplementedDecode as Decode<'a>>::Decoder,
    c: <C as Decode<'a>>::Decoder,
}
impl<'a> Default for BDecoder<'a> {
    fn default() -> Self {
        Self {
            non_implemented: Default::default(),
            c: Default::default(),
        }
    }
}
impl<'a> Decoder<'a, B> for BDecoder<'a> {}

struct C;

impl<'a> Decode<'a> for C
{
    type Decoder = CDecoder<'a>;
}

pub struct CDecoder<'a> {
    __spooky: PhantomData<&'a ()>,
}

impl<'a> Default for CDecoder<'a> {
    fn default() -> Self {
        Self {
            __spooky: Default::default(),
        }
    }
}

impl<'a> Decoder<'a, C> for CDecoder<'a> {}

fn main() {}
```

### Meta

`rustc --version --verbose`:
```
rustc 1.88.0-nightly (25cdf1f67 2025-04-28)
binary: rustc
commit-hash: 25cdf1f67463c9365d8d83778c933ec7480e940b
commit-date: 2025-04-28
host: x86_64-unknown-linux-gnu
release: 1.88.0-nightly
LLVM version: 20.1.2
```

### Error output

```
thread 'rustc' panicked at compiler/rustc_trait_selection/src/traits/normalize.rs:69:17:
Box<dyn Any>
stack backtrace:
   0:     0x7efe738642e5 - std::backtrace::Backtrace::create::h5b5d29f0fcbef4c5
   1:     0x7efe71cf3855 - std::backtrace::Backtrace::force_capture::h46ea152eb057a4f7
   2:     0x7efe70d86011 - std[96024a80e4ce12a0]::panicking::update_hook::<alloc[703cfcb04acfdfda]::boxed::Box<rustc_driver_impl[a2bbb3d7e654019c]::install_ice_hook::{closure#1}>>::{closure#0}
   3:     0x7efe71d0d933 - std::panicking::rust_panic_with_hook::h7afddb00f409503c
   4:     0x7efe70dc1241 - std[96024a80e4ce12a0]::panicking::begin_panic::<rustc_errors[c4bb5e76f42fc126]::ExplicitBug>::{closure#0}
   5:     0x7efe70db5116 - std[96024a80e4ce12a0]::sys::backtrace::__rust_end_short_backtrace::<std[96024a80e4ce12a0]::panicking::begin_panic<rustc_errors[c4bb5e76f42fc126]::ExplicitBug>::{closure#0}, !>
   6:     0x7efe70db5103 - std[96024a80e4ce12a0]::panicking::begin_panic::<rustc_errors[c4bb5e76f42fc126]::ExplicitBug>
   7:     0x7efe70dcb8a1 - <rustc_errors[c4bb5e76f42fc126]::diagnostic::BugAbort as rustc_errors[c4bb5e76f42fc126]::diagnostic::EmissionGuarantee>::emit_producing_guarantee
   8:     0x7efe7136b5ac - <rustc_errors[c4bb5e76f42fc126]::DiagCtxtHandle>::span_bug::<rustc_span[bce202135c071ebd]::span_encoding::Span, alloc[703cfcb04acfdfda]::string::String>
   9:     0x7efe71402f77 - rustc_middle[41c039613f3f9b63]::util::bug::opt_span_bug_fmt::<rustc_span[bce202135c071ebd]::span_encoding::Span>::{closure#0}
  10:     0x7efe713de82a - rustc_middle[41c039613f3f9b63]::ty::context::tls::with_opt::<rustc_middle[41c039613f3f9b63]::util::bug::opt_span_bug_fmt<rustc_span[bce202135c071ebd]::span_encoding::Span>::{closure#0}, !>::{closure#0}
  11:     0x7efe713de69b - rustc_middle[41c039613f3f9b63]::ty::context::tls::with_context_opt::<rustc_middle[41c039613f3f9b63]::ty::context::tls::with_opt<rustc_middle[41c039613f3f9b63]::util::bug::opt_span_bug_fmt<rustc_span[bce202135c071ebd]::span_encoding::Span>::{closure#0}, !>::{closure#0}, !>
  12:     0x7efe6f9c70e7 - rustc_middle[41c039613f3f9b63]::util::bug::span_bug_fmt::<rustc_span[bce202135c071ebd]::span_encoding::Span>
  13:     0x7efe72c3e955 - <rustc_infer[d90e9b374f743bff]::infer::at::At as rustc_trait_selection[7f49cd931f6e56ae]::traits::normalize::NormalizeExt>::deeply_normalize::<rustc_middle[41c039613f3f9b63]::ty::Ty, rustc_infer[d90e9b374f743bff]::traits::engine::ScrubbedTraitError>
  14:     0x7efe71ba3b01 - <rustc_trait_selection[7f49cd931f6e56ae]::traits::engine::ObligationCtxt>::deeply_normalize::<rustc_middle[41c039613f3f9b63]::ty::Ty>
  15:     0x7efe7258ac68 - rustc_trait_selection[7f49cd931f6e56ae]::traits::query::dropck_outlives::compute_dropck_outlives_inner
  16:     0x7efe7294909a - rustc_traits[a378416fae6313f9]::dropck_outlives::dropck_outlives
  17:     0x7efe72948b66 - rustc_query_impl[b776171e91563e8b]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[b776171e91563e8b]::query_impl::dropck_outlives::dynamic_query::{closure#2}::{closure#0}, rustc_middle[41c039613f3f9b63]::query::erase::Erased<[u8; 8usize]>>
  18:     0x7efe72948b2b - <rustc_query_impl[b776171e91563e8b]::query_impl::dropck_outlives::dynamic_query::{closure#2} as core[6d7144d1d4266374]::ops::function::FnOnce<(rustc_middle[41c039613f3f9b63]::ty::context::TyCtxt, rustc_type_ir[56906a3c7296c975]::canonical::CanonicalQueryInput<rustc_middle[41c039613f3f9b63]::ty::context::TyCtxt, rustc_middle[41c039613f3f9b63]::ty::ParamEnvAnd<rustc_middle[41c039613f3f9b63]::traits::query::type_op::DropckOutlives>>)>>::call_once
  19:     0x7efe72948aed - <rustc_query_system[aa926e5a14f6203b]::query::plumbing::execute_job_incr<rustc_query_impl[b776171e91563e8b]::DynamicConfig<rustc_query_system[aa926e5a14f6203b]::query::caches::DefaultCache<rustc_type_ir[56906a3c7296c975]::canonical::CanonicalQueryInput<rustc_middle[41c039613f3f9b63]::ty::context::TyCtxt, rustc_middle[41c039613f3f9b63]::ty::ParamEnvAnd<rustc_middle[41c039613f3f9b63]::traits::query::type_op::Normalize<rustc_middle[41c039613f3f9b63]::ty::Ty>>>, rustc_middle[41c039613f3f9b63]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[b776171e91563e8b]::plumbing::QueryCtxt>::{closure#2}::{closure#2} as core[6d7144d1d4266374]::ops::function::FnOnce<((rustc_query_impl[b776171e91563e8b]::plumbing::QueryCtxt, rustc_query_impl[b776171e91563e8b]::DynamicConfig<rustc_query_system[aa926e5a14f6203b]::query::caches::DefaultCache<rustc_type_ir[56906a3c7296c975]::canonical::CanonicalQueryInput<rustc_middle[41c039613f3f9b63]::ty::context::TyCtxt, rustc_middle[41c039613f3f9b63]::ty::ParamEnvAnd<rustc_middle[41c039613f3f9b63]::traits::query::type_op::Normalize<rustc_middle[41c039613f3f9b63]::ty::Ty>>>, rustc_middle[41c039613f3f9b63]::query::erase::Erased<[u8; 8usize]>>, false, false, false>), rustc_type_ir[56906a3c7296c975]::canonical::CanonicalQueryInput<rustc_middle[41c039613f3f9b63]::ty::context::TyCtxt, rustc_middle[41c039613f3f9b63]::ty::ParamEnvAnd<rustc_middle[41c039613f3f9b63]::traits::query::type_op::Normalize<rustc_middle[41c039613f3f9b63]::ty::Ty>>>)>>::call_once
  20:     0x7efe7292cf0e - rustc_query_system[aa926e5a14f6203b]::query::plumbing::try_execute_query::<rustc_query_impl[b776171e91563e8b]::DynamicConfig<rustc_query_system[aa926e5a14f6203b]::query::caches::DefaultCache<rustc_type_ir[56906a3c7296c975]::canonical::CanonicalQueryInput<rustc_middle[41c039613f3f9b63]::ty::context::TyCtxt, rustc_middle[41c039613f3f9b63]::ty::ParamEnvAnd<rustc_middle[41c039613f3f9b63]::traits::query::type_op::DropckOutlives>>, rustc_middle[41c039613f3f9b63]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[b776171e91563e8b]::plumbing::QueryCtxt, true>
  21:     0x7efe7292c813 - rustc_query_impl[b776171e91563e8b]::query_impl::dropck_outlives::get_query_incr::__rust_end_short_backtrace
  22:     0x7efe72c4b0a3 - <rustc_borrowck[c484d48ab0116751]::type_check::liveness::trace::LivenessContext>::compute_drop_data
  23:     0x7efe6efc6c38 - rustc_borrowck[c484d48ab0116751]::type_check::liveness::trace::trace
  24:     0x7efe73630f6b - rustc_borrowck[c484d48ab0116751]::do_mir_borrowck
  25:     0x7efe73611b11 - rustc_borrowck[c484d48ab0116751]::mir_borrowck
  26:     0x7efe73611999 - rustc_query_impl[b776171e91563e8b]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[b776171e91563e8b]::query_impl::mir_borrowck::dynamic_query::{closure#2}::{closure#0}, rustc_middle[41c039613f3f9b63]::query::erase::Erased<[u8; 8usize]>>
  27:     0x7efe726273e9 - rustc_query_system[aa926e5a14f6203b]::query::plumbing::try_execute_query::<rustc_query_impl[b776171e91563e8b]::DynamicConfig<rustc_data_structures[9557117c3f8f3a0]::vec_cache::VecCache<rustc_span[bce202135c071ebd]::def_id::LocalDefId, rustc_middle[41c039613f3f9b63]::query::erase::Erased<[u8; 8usize]>, rustc_query_system[aa926e5a14f6203b]::dep_graph::graph::DepNodeIndex>, false, false, false>, rustc_query_impl[b776171e91563e8b]::plumbing::QueryCtxt, true>
  28:     0x7efe7266bc0b - rustc_query_impl[b776171e91563e8b]::query_impl::mir_borrowck::get_query_incr::__rust_end_short_backtrace
  29:     0x7efe72e0701c - rustc_interface[269edf8a537b00a5]::passes::run_required_analyses
  30:     0x7efe732a915e - rustc_interface[269edf8a537b00a5]::passes::analysis
  31:     0x7efe732a9133 - rustc_query_impl[b776171e91563e8b]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[b776171e91563e8b]::query_impl::analysis::dynamic_query::{closure#2}::{closure#0}, rustc_middle[41c039613f3f9b63]::query::erase::Erased<[u8; 0usize]>>
  32:     0x7efe736d727f - rustc_query_system[aa926e5a14f6203b]::query::plumbing::try_execute_query::<rustc_query_impl[b776171e91563e8b]::DynamicConfig<rustc_query_system[aa926e5a14f6203b]::query::caches::SingleCache<rustc_middle[41c039613f3f9b63]::query::erase::Erased<[u8; 0usize]>>, false, false, false>, rustc_query_impl[b776171e91563e8b]::plumbing::QueryCtxt, true>
  33:     0x7efe736d6cb5 - rustc_query_impl[b776171e91563e8b]::query_impl::analysis::get_query_incr::__rust_end_short_backtrace
  34:     0x7efe7338f3be - rustc_interface[269edf8a537b00a5]::passes::create_and_enter_global_ctxt::<core[6d7144d1d4266374]::option::Option<rustc_interface[269edf8a537b00a5]::queries::Linker>, rustc_driver_impl[a2bbb3d7e654019c]::run_compiler::{closure#0}::{closure#2}>::{closure#2}::{closure#0}
  35:     0x7efe734eceb9 - rustc_interface[269edf8a537b00a5]::interface::run_compiler::<(), rustc_driver_impl[a2bbb3d7e654019c]::run_compiler::{closure#0}>::{closure#1}
  36:     0x7efe73301728 - std[96024a80e4ce12a0]::sys::backtrace::__rust_begin_short_backtrace::<rustc_interface[269edf8a537b00a5]::util::run_in_thread_with_globals<rustc_interface[269edf8a537b00a5]::util::run_in_thread_pool_with_globals<rustc_interface[269edf8a537b00a5]::interface::run_compiler<(), rustc_driver_impl[a2bbb3d7e654019c]::run_compiler::{closure#0}>::{closure#1}, ()>::{closure#0}, ()>::{closure#0}::{closure#0}, ()>
  37:     0x7efe73301b74 - <<std[96024a80e4ce12a0]::thread::Builder>::spawn_unchecked_<rustc_interface[269edf8a537b00a5]::util::run_in_thread_with_globals<rustc_interface[269edf8a537b00a5]::util::run_in_thread_pool_with_globals<rustc_interface[269edf8a537b00a5]::interface::run_compiler<(), rustc_driver_impl[a2bbb3d7e654019c]::run_compiler::{closure#0}>::{closure#1}, ()>::{closure#0}, ()>::{closure#0}::{closure#0}, ()>::{closure#1} as core[6d7144d1d4266374]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  38:     0x7efe73302f77 - std::sys::pal::unix::thread::Thread::new::thread_start::h7eeb46109c9d7745
  39:     0x7efe6d2a8144 - <unknown>
  40:     0x7efe6d3287dc - <unknown>
  41:                0x0 - <unknown>


rustc version: 1.88.0-nightly (25cdf1f67 2025-04-28)
platform: x86_64-unknown-linux-gnu

query stack during panic:
#0 [dropck_outlives] computing dropck types for `ADecoder<'_>`
#1 [mir_borrowck] borrow-checking `<impl at src/main.rs:22:1: 22:34>::default`
#2 [analysis] running analysis passes on this crate
end of query stack
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
$ RUST_BACKTRACE=1 cargo build
   Compiling untitled v0.1.0 (/home/user/code/untitled)
error[E0277]: the trait bound `NonImplementedDecode: Decode<'a>` is not satisfied
  --> src/main.rs:44:22
   |
44 |     non_implemented: <NonImplementedDecode as Decode<'a>>::Decoder,
   |                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `Decode<'a>` is not implemented for `NonImplementedDecode`
   |
   = help: the following other types implement trait `Decode<'a>`:
             A
             B
             C

error[E0277]: the trait bound `NonImplementedDecode: Decode<'a>` is not satisfied
  --> src/main.rs:50:13
   |
50 |             non_implemented: Default::default(),
   |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `Decode<'a>` is not implemented for `NonImplementedDecode`
   |
   = help: the following other types implement trait `Decode<'a>`:
             A
             B
             C

error: internal compiler error: compiler/rustc_trait_selection/src/traits/normalize.rs:69:17: deeply_normalize should not be called with pending obligations: [
                                    Obligation(predicate=Binder { value: OutlivesPredicate('?0, '?0), bound_vars: [] }, depth=0),
                                ]


thread 'rustc' panicked at compiler/rustc_trait_selection/src/traits/normalize.rs:69:17:
Box<dyn Any>
stack backtrace:
   0: std::panicking::begin_panic::<rustc_errors::ExplicitBug>
   1: <rustc_errors::diagnostic::BugAbort as rustc_errors::diagnostic::EmissionGuarantee>::emit_producing_guarantee
   2: <rustc_errors::DiagCtxtHandle>::span_bug::<rustc_span::span_encoding::Span, alloc::string::String>
   3: rustc_middle::util::bug::opt_span_bug_fmt::<rustc_span::span_encoding::Span>::{closure#0}
   4: rustc_middle::ty::context::tls::with_opt::<rustc_middle::util::bug::opt_span_bug_fmt<rustc_span::span_encoding::Span>::{closure#0}, !>::{closure#0}
   5: rustc_middle::ty::context::tls::with_context_opt::<rustc_middle::ty::context::tls::with_opt<rustc_middle::util::bug::opt_span_bug_fmt<rustc_span::span_encoding::Span>::{closure#0}, !>::{closure#0}, !>
   6: rustc_middle::util::bug::span_bug_fmt::<rustc_span::span_encoding::Span>
   7: <rustc_infer::infer::at::At as rustc_trait_selection::traits::normalize::NormalizeExt>::deeply_normalize::<rustc_middle::ty::Ty, rustc_infer::traits::engine::ScrubbedTraitError>
   8: <rustc_trait_selection::traits::engine::ObligationCtxt>::deeply_normalize::<rustc_middle::ty::Ty>
   9: rustc_trait_selection::traits::query::dropck_outlives::compute_dropck_outlives_inner
  10: rustc_traits::dropck_outlives::dropck_outlives
      [... omitted 3 frames ...]
  11: <rustc_borrowck::type_check::liveness::trace::LivenessContext>::compute_drop_data
  12: rustc_borrowck::type_check::liveness::trace::trace
  13: rustc_borrowck::do_mir_borrowck
  14: rustc_borrowck::mir_borrowck
      [... omitted 1 frame ...]
  15: rustc_interface::passes::run_required_analyses
  16: rustc_interface::passes::analysis
      [... omitted 1 frame ...]
  17: rustc_interface::passes::create_and_enter_global_ctxt::<core::option::Option<rustc_interface::queries::Linker>, rustc_driver_impl::run_compiler::{closure#0}::{closure#2}>::{closure#2}::{closure#0}
  18: rustc_interface::interface::run_compiler::<(), rustc_driver_impl::run_compiler::{closure#0}>::{closure#1}
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: please make sure that you have updated to the latest nightly

note: please attach the file at `/home/user/code/untitled/rustc-ice-2025-04-29T14_42_17-21412.txt` to your bug report

note: compiler flags: --crate-type bin -C embed-bitcode=no -C debuginfo=2 -C incremental=[REDACTED] -C link-arg=-fuse-ld=lld

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [dropck_outlives] computing dropck types for `ADecoder<'_>`
#1 [mir_borrowck] borrow-checking `<impl at src/main.rs:22:1: 22:34>::default`
#2 [analysis] running analysis passes on this crate
end of query stack
For more information about this error, try `rustc --explain E0277`.
error: could not compile `untitled` (bin "untitled") due to 2 previous errors
```

</p>
</details>

### LINKED ISSUE #140931: ICE when building rustc_middle with some query-related trait bounds not satisfied
### Code

Apply the following patch to rustc:
```diff
diff --git a/compiler/rustc_middle/src/mir/interpret/error.rs b/compiler/rustc_middle/src/mir/interpret/error.rs
index 6ff3cac049b..7486be69daf 100644
--- a/compiler/rustc_middle/src/mir/interpret/error.rs
+++ b/compiler/rustc_middle/src/mir/interpret/error.rs
@@ -101,7 +101,7 @@ fn from(val: ReportedErrorInfo) -> Self {
 /// because the value contains something of type `ty` that is not valtree-compatible.
 /// The caller can then show an appropriate error; the query does not have the
 /// necessary context to give good user-facing errors for this case.
-pub type EvalToValTreeResult<'tcx> = Result<Result<ValTree<'tcx>, Ty<'tcx>>, ErrorHandled>;
+pub type EvalToValTreeResult<'tcx> = Result<Either<ValTree<'tcx>, Ty<'tcx>>, ErrorHandled>;
 
 #[cfg(target_pointer_width = "64")]
 rustc_data_structures::static_assert_size!(InterpErrorInfo<'_>, 8);
```

### Meta

Whatever bootstrap compiler rustc currently uses

### Error output

There are a lot of errors, and then an ICE:
```
error: internal compiler error: compiler/rustc_trait_selection/src/traits/normalize.rs:69:17: deeply_normalize should not be called with pending obligations: [
                                    Obligation(predicate=Binder { value: OutlivesPredicate('?1, '?1), bound_vars: [] }, depth=0),
                                ]


thread 'rustc' panicked at compiler/rustc_trait_selection/src/traits/normalize.rs:69:17:
Box<dyn Any>
stack backtrace:
   0:     0x7fa6ea87c613 - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::had6e551bdf697010
   1:     0x7fa6eb005d91 - core::fmt::write::h9e37a39b0361e225
   2:     0x7fa6ec1815d1 - std::io::Write::write_fmt::h1df079672db6f5be
   3:     0x7fa6ea87c472 - std::sys::backtrace::BacktraceLock::print::h84aaeea67cd911a4
   4:     0x7fa6ea87ed2a - std::panicking::default_hook::{{closure}}::he4b444e817d4c55b
   5:     0x7fa6ea87e8af - std::panicking::default_hook::h80ec831a3e3e04cd
   6:     0x7fa6e98e5310 - std[41ff0dbd664e2dc2]::panicking::update_hook::<alloc[63a6662ec60f2805]::boxed::Box<rustc_driver_impl[17ca36e85839b9c8]::install_ice_hook::{closure#1}>>::{closure#0}
   7:     0x7fa6ea87f5a3 - std::panicking::rust_panic_with_hook::hd8821efb9bfec5df
   8:     0x7fa6e9924611 - std[41ff0dbd664e2dc2]::panicking::begin_panic::<rustc_errors[bc18beab6d94fb57]::ExplicitBug>::{closure#0}
   9:     0x7fa6e99182d6 - std[41ff0dbd664e2dc2]::sys::backtrace::__rust_end_short_backtrace::<std[41ff0dbd664e2dc2]::panicking::begin_panic<rustc_errors[bc18beab6d94fb57]::ExplicitBug>::{closure#0}, !>
  10:     0x7fa6e9914c29 - std[41ff0dbd664e2dc2]::panicking::begin_panic::<rustc_errors[bc18beab6d94fb57]::ExplicitBug>
  11:     0x7fa6e992dfd1 - <rustc_errors[bc18beab6d94fb57]::diagnostic::BugAbort as rustc_errors[bc18beab6d94fb57]::diagnostic::EmissionGuarantee>::emit_producing_guarantee
  12:     0x7fa6e9ecf39c - <rustc_errors[bc18beab6d94fb57]::DiagCtxtHandle>::span_bug::<rustc_span[c3c4ef5d7f88161]::span_encoding::Span, alloc[63a6662ec60f2805]::string::String>
  13:     0x7fa6e9f69877 - rustc_middle[80461b7d4018fbd4]::util::bug::opt_span_bug_fmt::<rustc_span[c3c4ef5d7f88161]::span_encoding::Span>::{closure#0}
  14:     0x7fa6e9f452ea - rustc_middle[80461b7d4018fbd4]::ty::context::tls::with_opt::<rustc_middle[80461b7d4018fbd4]::util::bug::opt_span_bug_fmt<rustc_span[c3c4ef5d7f88161]::span_encoding::Span>::{closure#0}, !>::{closure#0}
  15:     0x7fa6e9f4515b - rustc_middle[80461b7d4018fbd4]::ty::context::tls::with_context_opt::<rustc_middle[80461b7d4018fbd4]::ty::context::tls::with_opt<rustc_middle[80461b7d4018fbd4]::util::bug::opt_span_bug_fmt<rustc_span[c3c4ef5d7f88161]::span_encoding::Span>::{closure#0}, !>::{closure#0}, !>
  16:     0x7fa6e7a2e9a7 - rustc_middle[80461b7d4018fbd4]::util::bug::span_bug_fmt::<rustc_span[c3c4ef5d7f88161]::span_encoding::Span>
  17:     0x7fa6eb84d486 - <rustc_trait_selection[5e6f5e63d48e3d03]::traits::engine::ObligationCtxt>::deeply_normalize::<rustc_middle[80461b7d4018fbd4]::ty::Ty>
  18:     0x7fa6eb1b8b5d - rustc_trait_selection[5e6f5e63d48e3d03]::traits::query::dropck_outlives::compute_dropck_outlives_inner
  19:     0x7fa6eb673364 - rustc_traits[9bed9e12332a3392]::dropck_outlives::dropck_outlives
  20:     0x7fa6eb672e26 - rustc_query_impl[db10edd006496e38]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[db10edd006496e38]::query_impl::dropck_outlives::dynamic_query::{closure#2}::{closure#0}, rustc_middle[80461b7d4018fbd4]::query::erase::Erased<[u8; 8usize]>>
  21:     0x7fa6eb672deb - <rustc_query_impl[db10edd006496e38]::query_impl::dropck_outlives::dynamic_query::{closure#2} as core[5fd6bfabdd2b4c2b]::ops::function::FnOnce<(rustc_middle[80461b7d4018fbd4]::ty::context::TyCtxt, rustc_type_ir[3091dc864f16e166]::canonical::CanonicalQueryInput<rustc_middle[80461b7d4018fbd4]::ty::context::TyCtxt, rustc_middle[80461b7d4018fbd4]::ty::ParamEnvAnd<rustc_middle[80461b7d4018fbd4]::traits::query::type_op::DropckOutlives>>)>>::call_once
  22:     0x7fa6eb672dad - <rustc_query_system[70e091e811290e7d]::query::plumbing::execute_job_incr<rustc_query_impl[db10edd006496e38]::DynamicConfig<rustc_query_system[70e091e811290e7d]::query::caches::DefaultCache<rustc_type_ir[3091dc864f16e166]::canonical::CanonicalQueryInput<rustc_middle[80461b7d4018fbd4]::ty::context::TyCtxt, rustc_middle[80461b7d4018fbd4]::ty::ParamEnvAnd<rustc_middle[80461b7d4018fbd4]::traits::query::type_op::Normalize<rustc_middle[80461b7d4018fbd4]::ty::Ty>>>, rustc_middle[80461b7d4018fbd4]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[db10edd006496e38]::plumbing::QueryCtxt>::{closure#2}::{closure#2} as core[5fd6bfabdd2b4c2b]::ops::function::FnOnce<((rustc_query_impl[db10edd006496e38]::plumbing::QueryCtxt, rustc_query_impl[db10edd006496e38]::DynamicConfig<rustc_query_system[70e091e811290e7d]::query::caches::DefaultCache<rustc_type_ir[3091dc864f16e166]::canonical::CanonicalQueryInput<rustc_middle[80461b7d4018fbd4]::ty::context::TyCtxt, rustc_middle[80461b7d4018fbd4]::ty::ParamEnvAnd<rustc_middle[80461b7d4018fbd4]::traits::query::type_op::Normalize<rustc_middle[80461b7d4018fbd4]::ty::Ty>>>, rustc_middle[80461b7d4018fbd4]::query::erase::Erased<[u8; 8usize]>>, false, false, false>), rustc_type_ir[3091dc864f16e166]::canonical::CanonicalQueryInput<rustc_middle[80461b7d4018fbd4]::ty::context::TyCtxt, rustc_middle[80461b7d4018fbd4]::ty::ParamEnvAnd<rustc_middle[80461b7d4018fbd4]::traits::query::type_op::Normalize<rustc_middle[80461b7d4018fbd4]::ty::Ty>>>)>>::call_once
  23:     0x7fa6eb92fdd8 - rustc_query_system[70e091e811290e7d]::query::plumbing::try_execute_query::<rustc_query_impl[db10edd006496e38]::DynamicConfig<rustc_query_system[70e091e811290e7d]::query::caches::DefaultCache<rustc_type_ir[3091dc864f16e166]::canonical::CanonicalQueryInput<rustc_middle[80461b7d4018fbd4]::ty::context::TyCtxt, rustc_middle[80461b7d4018fbd4]::ty::ParamEnvAnd<rustc_middle[80461b7d4018fbd4]::traits::query::type_op::DropckOutlives>>, rustc_middle[80461b7d4018fbd4]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[db10edd006496e38]::plumbing::QueryCtxt, true>
  24:     0x7fa6eb92f716 - rustc_query_impl[db10edd006496e38]::query_impl::dropck_outlives::get_query_incr::__rust_end_short_backtrace
  25:     0x7fa6eb8594fd - <rustc_borrowck[7603524d21067fa7]::type_check::liveness::trace::LivenessContext>::compute_drop_data
  26:     0x7fa6e829b947 - rustc_borrowck[7603524d21067fa7]::type_check::liveness::trace::trace
  27:     0x7fa6e82c51fd - rustc_borrowck[7603524d21067fa7]::type_check::type_check
  28:     0x7fa6e8284fa3 - rustc_borrowck[7603524d21067fa7]::nll::compute_regions
  29:     0x7fa6ec1c0343 - rustc_borrowck[7603524d21067fa7]::do_mir_borrowck
  30:     0x7fa6ec1b016c - rustc_query_impl[db10edd006496e38]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[db10edd006496e38]::query_impl::mir_borrowck::dynamic_query::{closure#2}::{closure#0}, rustc_middle[80461b7d4018fbd4]::query::erase::Erased<[u8; 8usize]>>
  31:     0x7fa6eb36ab18 - rustc_query_system[70e091e811290e7d]::query::plumbing::try_execute_query::<rustc_query_impl[db10edd006496e38]::DynamicConfig<rustc_data_structures[9915193eb5406c5c]::vec_cache::VecCache<rustc_span[c3c4ef5d7f88161]::def_id::LocalDefId, rustc_middle[80461b7d4018fbd4]::query::erase::Erased<[u8; 8usize]>, rustc_query_system[70e091e811290e7d]::dep_graph::graph::DepNodeIndex>, false, false, false>, rustc_query_impl[db10edd006496e38]::plumbing::QueryCtxt, true>
  32:     0x7fa6eb36e6b0 - rustc_query_impl[db10edd006496e38]::plumbing::force_from_dep_node::<rustc_query_impl[db10edd006496e38]::DynamicConfig<rustc_data_structures[9915193eb5406c5c]::vec_cache::VecCache<rustc_span[c3c4ef5d7f88161]::def_id::LocalDefId, rustc_middle[80461b7d4018fbd4]::query::erase::Erased<[u8; 8usize]>, rustc_query_system[70e091e811290e7d]::dep_graph::graph::DepNodeIndex>, false, false, false>>
  33:     0x7fa6ec4b2111 - <rustc_query_impl[db10edd006496e38]::plumbing::query_callback<rustc_query_impl[db10edd006496e38]::query_impl::mir_borrowck::QueryType>::{closure#0} as core[5fd6bfabdd2b4c2b]::ops::function::FnOnce<(rustc_middle[80461b7d4018fbd4]::ty::context::TyCtxt, rustc_query_system[70e091e811290e7d]::dep_graph::dep_node::DepNode, rustc_query_system[70e091e811290e7d]::dep_graph::serialized::SerializedDepNodeIndex)>>::call_once
  34:     0x7fa6eb0192c1 - <rustc_query_system[70e091e811290e7d]::dep_graph::graph::DepGraphData<rustc_middle[80461b7d4018fbd4]::dep_graph::DepsType>>::try_mark_previous_green::<rustc_query_impl[db10edd006496e38]::plumbing::QueryCtxt>
  35:     0x7fa6eb3875be - rustc_query_system[70e091e811290e7d]::query::plumbing::ensure_must_run::<rustc_query_impl[db10edd006496e38]::DynamicConfig<rustc_data_structures[9915193eb5406c5c]::vec_cache::VecCache<rustc_span[c3c4ef5d7f88161]::def_id::LocalDefId, rustc_middle[80461b7d4018fbd4]::query::erase::Erased<[u8; 1usize]>, rustc_query_system[70e091e811290e7d]::dep_graph::graph::DepNodeIndex>, false, false, false>, rustc_query_impl[db10edd006496e38]::plumbing::QueryCtxt>
  36:     0x7fa6eb387198 - rustc_query_impl[db10edd006496e38]::query_impl::mir_borrowck::get_query_incr::__rust_end_short_backtrace
  37:     0x7fa6eb923fcd - rustc_interface[9abced68ad600168]::passes::run_required_analyses
  38:     0x7fa6ec18795e - rustc_interface[9abced68ad600168]::passes::analysis
  39:     0x7fa6ec187933 - rustc_query_impl[db10edd006496e38]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[db10edd006496e38]::query_impl::analysis::dynamic_query::{closure#2}::{closure#0}, rustc_middle[80461b7d4018fbd4]::query::erase::Erased<[u8; 0usize]>>
  40:     0x7fa6ec18a27d - rustc_query_system[70e091e811290e7d]::query::plumbing::try_execute_query::<rustc_query_impl[db10edd006496e38]::DynamicConfig<rustc_query_system[70e091e811290e7d]::query::caches::SingleCache<rustc_middle[80461b7d4018fbd4]::query::erase::Erased<[u8; 0usize]>>, false, false, false>, rustc_query_impl[db10edd006496e38]::plumbing::QueryCtxt, true>
  41:     0x7fa6ec189ba9 - rustc_query_impl[db10edd006496e38]::query_impl::analysis::get_query_incr::__rust_end_short_backtrace
  42:     0x7fa6ec14000d - rustc_interface[9abced68ad600168]::passes::create_and_enter_global_ctxt::<core[5fd6bfabdd2b4c2b]::option::Option<rustc_interface[9abced68ad600168]::queries::Linker>, rustc_driver_impl[17ca36e85839b9c8]::run_compiler::{closure#0}::{closure#2}>::{closure#2}::{closure#0}
  43:     0x7fa6ec1286aa - rustc_interface[9abced68ad600168]::interface::run_compiler::<(), rustc_driver_impl[17ca36e85839b9c8]::run_compiler::{closure#0}>::{closure#1}
  44:     0x7fa6ec0f5608 - std[41ff0dbd664e2dc2]::sys::backtrace::__rust_begin_short_backtrace::<rustc_interface[9abced68ad600168]::util::run_in_thread_with_globals<rustc_interface[9abced68ad600168]::util::run_in_thread_pool_with_globals<rustc_interface[9abced68ad600168]::interface::run_compiler<(), rustc_driver_impl[17ca36e85839b9c8]::run_compiler::{closure#0}>::{closure#1}, ()>::{closure#0}, ()>::{closure#0}::{closure#0}, ()>
  45:     0x7fa6ec0f5ef4 - <<std[41ff0dbd664e2dc2]::thread::Builder>::spawn_unchecked_<rustc_interface[9abced68ad600168]::util::run_in_thread_with_globals<rustc_interface[9abced68ad600168]::util::run_in_thread_pool_with_globals<rustc_interface[9abced68ad600168]::interface::run_compiler<(), rustc_driver_impl[17ca36e85839b9c8]::run_compiler::{closure#0}>::{closure#1}, ()>::{closure#0}, ()>::{closure#0}::{closure#0}, ()>::{closure#1} as core[5fd6bfabdd2b4c2b]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  46:     0x7fa6ec0f72eb - std::sys::pal::unix::thread::Thread::new::thread_start::h82c6b7e8ccb00138
  47:     0x7fa6e5e9cb7b - start_thread
                               at ./nptl/pthread_create.c:448:8
  48:     0x7fa6e5f1a7b8 - __GI___clone3
                               at ./misc/../sysdeps/unix/sysv/linux/x86_64/clone3.S:78:0
  49:                0x0 - <unknown>

note: using internal features is not supported and expected to cause internal compiler errors when used incorrectly

note: rustc 1.87.0-beta.1 (45165c82a 2025-04-01) running on x86_64-unknown-linux-gnu

note: compiler flags: --crate-type lib -C opt-level=3 -C embed-bitcode=no -C debuginfo=1 -C debug-assertions=on -C overflow-checks=off -C incremental=[REDACTED] -C symbol-mangling-version=v0 -Z unstable-options -Z macro-backtrace -C split-debuginfo=off -C llvm-args=-import-instr-limit=10 -Z on-broken-pipe=kill -Z binary-dep-depinfo -Z tls-model=initial-exec -Z force-unstable-if-unmarked

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [dropck_outlives] computing dropck types for `ty::context::GlobalCtxt<'_>`
#1 [mir_borrowck] borrow-checking `ty::context::<impl at compiler/rustc_middle/src/ty/context.rs:1515:1: 1515:24>::create_global_ctxt::{closure#1}`
... and 1 other queries... use `env RUST_BACKTRACE=1` to see the full query stack
there was a panic while trying to force a dep node
try_mark_green dep node stack:
#0 mir_borrowck(rustc_middle[db4e]::ty::context::{impl#24}::create_global_ctxt)
end of try_mark_green dep node stack

thread 'rustc' panicked at compiler/rustc_trait_selection/src/traits/normalize.rs:69:17:
Box<dyn Any>
stack backtrace:
   0:     0x7f82b007c613 - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::had6e551bdf697010
   1:     0x7f82b0805d91 - core::fmt::write::h9e37a39b0361e225
   2:     0x7f82b19815d1 - std::io::Write::write_fmt::h1df079672db6f5be
   3:     0x7f82b007c472 - std::sys::backtrace::BacktraceLock::print::h84aaeea67cd911a4
   4:     0x7f82b007ed2a - std::panicking::default_hook::{{closure}}::he4b444e817d4c55b
   5:     0x7f82b007e8af - std::panicking::default_hook::h80ec831a3e3e04cd
   6:     0x7f82af0e5310 - std[41ff0dbd664e2dc2]::panicking::update_hook::<alloc[63a6662ec60f2805]::boxed::Box<rustc_driver_impl[17ca36e85839b9c8]::install_ice_hook::{closure#1}>>::{closure#0}
   7:     0x7f82b007f5a3 - std::panicking::rust_panic_with_hook::hd8821efb9bfec5df
   8:     0x7f82af124611 - std[41ff0dbd664e2dc2]::panicking::begin_panic::<rustc_errors[bc18beab6d94fb57]::ExplicitBug>::{closure#0}
   9:     0x7f82af1182d6 - std[41ff0dbd664e2dc2]::sys::backtrace::__rust_end_short_backtrace::<std[41ff0dbd664e2dc2]::panicking::begin_panic<rustc_errors[bc18beab6d94fb57]::ExplicitBug>::{closure#0}, !>
  10:     0x7f82af114c29 - std[41ff0dbd664e2dc2]::panicking::begin_panic::<rustc_errors[bc18beab6d94fb57]::ExplicitBug>
  11:     0x7f82af12dfd1 - <rustc_errors[bc18beab6d94fb57]::diagnostic::BugAbort as rustc_errors[bc18beab6d94fb57]::diagnostic::EmissionGuarantee>::emit_producing_guarantee
  12:     0x7f82af6cf39c - <rustc_errors[bc18beab6d94fb57]::DiagCtxtHandle>::span_bug::<rustc_span[c3c4ef5d7f88161]::span_encoding::Span, alloc[63a6662ec60f2805]::string::String>
  13:     0x7f82af769877 - rustc_middle[80461b7d4018fbd4]::util::bug::opt_span_bug_fmt::<rustc_span[c3c4ef5d7f88161]::span_encoding::Span>::{closure#0}
  14:     0x7f82af7452ea - rustc_middle[80461b7d4018fbd4]::ty::context::tls::with_opt::<rustc_middle[80461b7d4018fbd4]::util::bug::opt_span_bug_fmt<rustc_span[c3c4ef5d7f88161]::span_encoding::Span>::{closure#0}, !>::{closure#0}
  15:     0x7f82af74515b - rustc_middle[80461b7d4018fbd4]::ty::context::tls::with_context_opt::<rustc_middle[80461b7d4018fbd4]::ty::context::tls::with_opt<rustc_middle[80461b7d4018fbd4]::util::bug::opt_span_bug_fmt<rustc_span[c3c4ef5d7f88161]::span_encoding::Span>::{closure#0}, !>::{closure#0}, !>
  16:     0x7f82ad22e9a7 - rustc_middle[80461b7d4018fbd4]::util::bug::span_bug_fmt::<rustc_span[c3c4ef5d7f88161]::span_encoding::Span>
  17:     0x7f82b104d486 - <rustc_trait_selection[5e6f5e63d48e3d03]::traits::engine::ObligationCtxt>::deeply_normalize::<rustc_middle[80461b7d4018fbd4]::ty::Ty>
  18:     0x7f82b09b8b5d - rustc_trait_selection[5e6f5e63d48e3d03]::traits::query::dropck_outlives::compute_dropck_outlives_inner
  19:     0x7f82b0e73364 - rustc_traits[9bed9e12332a3392]::dropck_outlives::dropck_outlives
  20:     0x7f82b0e72e26 - rustc_query_impl[db10edd006496e38]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[db10edd006496e38]::query_impl::dropck_outlives::dynamic_query::{closure#2}::{closure#0}, rustc_middle[80461b7d4018fbd4]::query::erase::Erased<[u8; 8usize]>>
  21:     0x7f82b0e72deb - <rustc_query_impl[db10edd006496e38]::query_impl::dropck_outlives::dynamic_query::{closure#2} as core[5fd6bfabdd2b4c2b]::ops::function::FnOnce<(rustc_middle[80461b7d4018fbd4]::ty::context::TyCtxt, rustc_type_ir[3091dc864f16e166]::canonical::CanonicalQueryInput<rustc_middle[80461b7d4018fbd4]::ty::context::TyCtxt, rustc_middle[80461b7d4018fbd4]::ty::ParamEnvAnd<rustc_middle[80461b7d4018fbd4]::traits::query::type_op::DropckOutlives>>)>>::call_once
  22:     0x7f82b0e72dad - <rustc_query_system[70e091e811290e7d]::query::plumbing::execute_job_incr<rustc_query_impl[db10edd006496e38]::DynamicConfig<rustc_query_system[70e091e811290e7d]::query::caches::DefaultCache<rustc_type_ir[3091dc864f16e166]::canonical::CanonicalQueryInput<rustc_middle[80461b7d4018fbd4]::ty::context::TyCtxt, rustc_middle[80461b7d4018fbd4]::ty::ParamEnvAnd<rustc_middle[80461b7d4018fbd4]::traits::query::type_op::Normalize<rustc_middle[80461b7d4018fbd4]::ty::Ty>>>, rustc_middle[80461b7d4018fbd4]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[db10edd006496e38]::plumbing::QueryCtxt>::{closure#2}::{closure#2} as core[5fd6bfabdd2b4c2b]::ops::function::FnOnce<((rustc_query_impl[db10edd006496e38]::plumbing::QueryCtxt, rustc_query_impl[db10edd006496e38]::DynamicConfig<rustc_query_system[70e091e811290e7d]::query::caches::DefaultCache<rustc_type_ir[3091dc864f16e166]::canonical::CanonicalQueryInput<rustc_middle[80461b7d4018fbd4]::ty::context::TyCtxt, rustc_middle[80461b7d4018fbd4]::ty::ParamEnvAnd<rustc_middle[80461b7d4018fbd4]::traits::query::type_op::Normalize<rustc_middle[80461b7d4018fbd4]::ty::Ty>>>, rustc_middle[80461b7d4018fbd4]::query::erase::Erased<[u8; 8usize]>>, false, false, false>), rustc_type_ir[3091dc864f16e166]::canonical::CanonicalQueryInput<rustc_middle[80461b7d4018fbd4]::ty::context::TyCtxt, rustc_middle[80461b7d4018fbd4]::ty::ParamEnvAnd<rustc_middle[80461b7d4018fbd4]::traits::query::type_op::Normalize<rustc_middle[80461b7d4018fbd4]::ty::Ty>>>)>>::call_once
  23:     0x7f82b112fdd8 - rustc_query_system[70e091e811290e7d]::query::plumbing::try_execute_query::<rustc_query_impl[db10edd006496e38]::DynamicConfig<rustc_query_system[70e091e811290e7d]::query::caches::DefaultCache<rustc_type_ir[3091dc864f16e166]::canonical::CanonicalQueryInput<rustc_middle[80461b7d4018fbd4]::ty::context::TyCtxt, rustc_middle[80461b7d4018fbd4]::ty::ParamEnvAnd<rustc_middle[80461b7d4018fbd4]::traits::query::type_op::DropckOutlives>>, rustc_middle[80461b7d4018fbd4]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[db10edd006496e38]::plumbing::QueryCtxt, true>
  24:     0x7f82b112f716 - rustc_query_impl[db10edd006496e38]::query_impl::dropck_outlives::get_query_incr::__rust_end_short_backtrace
  25:     0x7f82b10594fd - <rustc_borrowck[7603524d21067fa7]::type_check::liveness::trace::LivenessContext>::compute_drop_data
  26:     0x7f82ada9b947 - rustc_borrowck[7603524d21067fa7]::type_check::liveness::trace::trace
  27:     0x7f82adac51fd - rustc_borrowck[7603524d21067fa7]::type_check::type_check
  28:     0x7f82ada84fa3 - rustc_borrowck[7603524d21067fa7]::nll::compute_regions
  29:     0x7f82b19c0343 - rustc_borrowck[7603524d21067fa7]::do_mir_borrowck
  30:     0x7f82b19b016c - rustc_query_impl[db10edd006496e38]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[db10edd006496e38]::query_impl::mir_borrowck::dynamic_query::{closure#2}::{closure#0}, rustc_middle[80461b7d4018fbd4]::query::erase::Erased<[u8; 8usize]>>
  31:     0x7f82b0b6ab18 - rustc_query_system[70e091e811290e7d]::query::plumbing::try_execute_query::<rustc_query_impl[db10edd006496e38]::DynamicConfig<rustc_data_structures[9915193eb5406c5c]::vec_cache::VecCache<rustc_span[c3c4ef5d7f88161]::def_id::LocalDefId, rustc_middle[80461b7d4018fbd4]::query::erase::Erased<[u8; 8usize]>, rustc_query_system[70e091e811290e7d]::dep_graph::graph::DepNodeIndex>, false, false, false>, rustc_query_impl[db10edd006496e38]::plumbing::QueryCtxt, true>
  32:     0x7f82b0b6e6b0 - rustc_query_impl[db10edd006496e38]::plumbing::force_from_dep_node::<rustc_query_impl[db10edd006496e38]::DynamicConfig<rustc_data_structures[9915193eb5406c5c]::vec_cache::VecCache<rustc_span[c3c4ef5d7f88161]::def_id::LocalDefId, rustc_middle[80461b7d4018fbd4]::query::erase::Erased<[u8; 8usize]>, rustc_query_system[70e091e811290e7d]::dep_graph::graph::DepNodeIndex>, false, false, false>>
  33:     0x7f82b1cb2111 - <rustc_query_impl[db10edd006496e38]::plumbing::query_callback<rustc_query_impl[db10edd006496e38]::query_impl::mir_borrowck::QueryType>::{closure#0} as core[5fd6bfabdd2b4c2b]::ops::function::FnOnce<(rustc_middle[80461b7d4018fbd4]::ty::context::TyCtxt, rustc_query_system[70e091e811290e7d]::dep_graph::dep_node::DepNode, rustc_query_system[70e091e811290e7d]::dep_graph::serialized::SerializedDepNodeIndex)>>::call_once
  34:     0x7f82b08192c1 - <rustc_query_system[70e091e811290e7d]::dep_graph::graph::DepGraphData<rustc_middle[80461b7d4018fbd4]::dep_graph::DepsType>>::try_mark_previous_green::<rustc_query_impl[db10edd006496e38]::plumbing::QueryCtxt>
  35:     0x7f82b0b875be - rustc_query_system[70e091e811290e7d]::query::plumbing::ensure_must_run::<rustc_query_impl[db10edd006496e38]::DynamicConfig<rustc_data_structures[9915193eb5406c5c]::vec_cache::VecCache<rustc_span[c3c4ef5d7f88161]::def_id::LocalDefId, rustc_middle[80461b7d4018fbd4]::query::erase::Erased<[u8; 1usize]>, rustc_query_system[70e091e811290e7d]::dep_graph::graph::DepNodeIndex>, false, false, false>, rustc_query_impl[db10edd006496e38]::plumbing::QueryCtxt>
  36:     0x7f82b0b87198 - rustc_query_impl[db10edd006496e38]::query_impl::mir_borrowck::get_query_incr::__rust_end_short_backtrace
  37:     0x7f82b1123fcd - rustc_interface[9abced68ad600168]::passes::run_required_analyses
  38:     0x7f82b198795e - rustc_interface[9abced68ad600168]::passes::analysis
  39:     0x7f82b1987933 - rustc_query_impl[db10edd006496e38]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[db10edd006496e38]::query_impl::analysis::dynamic_query::{closure#2}::{closure#0}, rustc_middle[80461b7d4018fbd4]::query::erase::Erased<[u8; 0usize]>>
  40:     0x7f82b198a27d - rustc_query_system[70e091e811290e7d]::query::plumbing::try_execute_query::<rustc_query_impl[db10edd006496e38]::DynamicConfig<rustc_query_system[70e091e811290e7d]::query::caches::SingleCache<rustc_middle[80461b7d4018fbd4]::query::erase::Erased<[u8; 0usize]>>, false, false, false>, rustc_query_impl[db10edd006496e38]::plumbing::QueryCtxt, true>
  41:     0x7f82b1989ba9 - rustc_query_impl[db10edd006496e38]::query_impl::analysis::get_query_incr::__rust_end_short_backtrace
  42:     0x7f82b194000d - rustc_interface[9abced68ad600168]::passes::create_and_enter_global_ctxt::<core[5fd6bfabdd2b4c2b]::option::Option<rustc_interface[9abced68ad600168]::queries::Linker>, rustc_driver_impl[17ca36e85839b9c8]::run_compiler::{closure#0}::{closure#2}>::{closure#2}::{closure#0}
  43:     0x7f82b19286aa - rustc_interface[9abced68ad600168]::interface::run_compiler::<(), rustc_driver_impl[17ca36e85839b9c8]::run_compiler::{closure#0}>::{closure#1}
  44:     0x7f82b18f5608 - std[41ff0dbd664e2dc2]::sys::backtrace::__rust_begin_short_backtrace::<rustc_interface[9abced68ad600168]::util::run_in_thread_with_globals<rustc_interface[9abced68ad600168]::util::run_in_thread_pool_with_globals<rustc_interface[9abced68ad600168]::interface::run_compiler<(), rustc_driver_impl[17ca36e85839b9c8]::run_compiler::{closure#0}>::{closure#1}, ()>::{closure#0}, ()>::{closure#0}::{closure#0}, ()>
  45:     0x7f82b18f5ef4 - <<std[41ff0dbd664e2dc2]::thread::Builder>::spawn_unchecked_<rustc_interface[9abced68ad600168]::util::run_in_thread_with_globals<rustc_interface[9abced68ad600168]::util::run_in_thread_pool_with_globals<rustc_interface[9abced68ad600168]::interface::run_compiler<(), rustc_driver_impl[17ca36e85839b9c8]::run_compiler::{closure#0}>::{closure#1}, ()>::{closure#0}, ()>::{closure#0}::{closure#0}, ()>::{closure#1} as core[5fd6bfabdd2b4c2b]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  46:     0x7f82b18f72eb - std::sys::pal::unix::thread::Thread::new::thread_start::h82c6b7e8ccb00138
For more information about this error, try `rustc --explain E0277`.
error: could not compile `rustc_middle` (lib) due to 22 previous errors
warning: build failed, waiting for other jobs to finish...
  47:     0x7f82ab69cb7b - start_thread
                               at ./nptl/pthread_create.c:448:8
  48:     0x7f82ab71a7b8 - __GI___clone3
                               at ./misc/../sysdeps/unix/sysv/linux/x86_64/clone3.S:78:0
  49:                0x0 - <unknown>

note: using internal features is not supported and expected to cause internal compiler errors when used incorrectly

note: rustc 1.87.0-beta.1 (45165c82a 2025-04-01) running on x86_64-unknown-linux-gnu

note: compiler flags: -C opt-level=3 -C embed-bitcode=no -C debuginfo=1 -C debug-assertions=on -C overflow-checks=off -C incremental=[REDACTED] -C symbol-mangling-version=v0 -Z unstable-options -Z macro-backtrace -C split-debuginfo=off -C llvm-args=-import-instr-limit=10 -Z on-broken-pipe=kill -Z binary-dep-depinfo -Z tls-model=initial-exec -Z force-unstable-if-unmarked

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [dropck_outlives] computing dropck types for `ty::context::GlobalCtxt<'_>`
#1 [mir_borrowck] borrow-checking `ty::context::<impl at compiler/rustc_middle/src/ty/context.rs:1515:1: 1515:24>::create_global_ctxt::{closure#1}`
... and 1 other queries... use `env RUST_BACKTRACE=1` to see the full query stack
there was a panic while trying to force a dep node
try_mark_green dep node stack:
#0 mir_borrowck(rustc_middle[e891]::ty::context::{impl#24}::create_global_ctxt)
end of try_mark_green dep node stack
error: could not compile `rustc_middle` (lib test) due to 22 previous errors
Build completed unsuccessfully in 0:00:04
```

</p>
</details>

Cc @rust-lang/types

### PR DESCRIPTION
**Pull request by compiler-errors**
Deep normalization doesn't allow the ocx to have pending obligations, so process them before deeply normalizing.

Fixes https://github.com/rust-lang/rust/issues/140931
Fixes https://github.com/rust-lang/rust/issues/140462

### CODE REVIEW

File: compiler/rustc_trait_selection/src/traits/query/dropck_outlives.rs [hunk 1]
```diff
@@ -196,6 +196,14 @@ where
...
+                // obligations, and we may have pending obligations from the
+                // branch above (from other types).
+                let errors = ocx.select_all_or_error();
+                if !errors.is_empty() {
+                    return Err(errors);
+                }
+
                 ocx.deeply_normalize(&cause, param_env, ty)?;
 
                 let errors = ocx.select_where_possible();
```
Comment (lcnr) [inline compiler/rustc_trait_selection/src/traits/query/dropck_outlives.rs:209]: arent these errors always empty now?

Comment (compiler-errors) [reply compiler/rustc_trait_selection/src/traits/query/dropck_outlives.rs:209]: yeah

Comment (compiler-errors) [reply compiler/rustc_trait_selection/src/traits/query/dropck_outlives.rs]: reworked this code a bit b/c it was kinda goofy, returning `Err(vec![])` in case deep normalization succeeded.

File: compiler/rustc_trait_selection/src/traits/query/dropck_outlives.rs [hunk 2]
```diff
@@ -196,11 +196,27 @@ where
...
+                // branch above (from other types).
+                let errors = ocx.select_all_or_error();
+                if !errors.is_empty() {
+                    return Err(errors);
+                }
 
-                let errors = ocx.select_where_possible();
-                debug!("normalize errors: {ty} ~> {errors:#?}");
-                return Err(errors);
+                match ocx.deeply_normalize(&cause, param_env, ty) {
```
Comment (lcnr) [inline compiler/rustc_trait_selection/src/traits/query/dropck_outlives.rs:207]: pls add comment that we do this match to get `FulfillmentError`s to report in case `query_normalize` failed to avoid ICE due to a delayed bug
