### PR TITLE
When single impl can satisfy inference error, suggest type

### LINKED ISSUE #100802: Iterator::sum requires type annotations in seemingly simple cases
Even with type annotations, Iterator::sum is not handled very nicely:
```
    let foo: usize = (1usize..10).sum() + 1usize;
```
fails to build with:
```
error[[E0283]](https://doc.rust-lang.org/stable/error-index.html#E0283): type annotations needed
 --> src/main.rs:2:35
  |
2 |     let foo: usize = (1usize..10).sum() + 1usize;
  |                                   ^^^ cannot infer type of the type parameter `S` declared on the associated function `sum`
  |
  = note: cannot satisfy `_: Sum<usize>`
note: required by a bound in `std::iter::Iterator::sum`
help: consider specifying the generic argument
  |
2 |     let foo: usize = (1usize..10).sum::<S>() + 1usize;
  |                                      +++++
help: consider specifying the type argument in the function call
  |
2 |     let foo: usize = (1usize..10).sum::<S>() + 1usize;
  |                                      +++++
```

The converse:
```
    let bar: usize = 1usize + (1usize..10).sum();
```
fails to build with:
```
error[[E0284]](https://doc.rust-lang.org/stable/error-index.html#E0284): type annotations needed: cannot satisfy `<usize as Add<_>>::Output == usize`
 --> src/main.rs:2:29
  |
2 |     let bar: usize = 1usize + (1usize..10).sum();
  |                             ^ cannot satisfy `<usize as Add<_>>::Output == usize`
```

### PR DESCRIPTION
**Pull request by estebank**
When encountering an inference error where a return type must be known, like when calling `Iterator::sum::<T>()` without specifying `T`, look for all `T` that would satisfy `Sum<S>`. If only one, suggest it.

```
error[E0283]: type annotations needed
  --> $DIR/cannot-infer-iterator-sum-return-type.rs:4:9
   |
LL |     let sum = v
   |         ^^^
...
LL |         .sum(); // `sum::<T>` needs `T` to be specified
   |          --- type must be known at this point
   |
   = note: cannot satisfy `_: Sum<i32>`
help: the trait `Sum` is implemented for `i32`
  --> $SRC_DIR/core/src/iter/traits/accum.rs:LL:COL
  ::: $SRC_DIR/core/src/iter/traits/accum.rs:LL:COL
   |
   = note: in this macro invocation
note: required by a bound in `std::iter::Iterator::sum`
  --> $SRC_DIR/core/src/iter/traits/iterator.rs:LL:COL
   = note: this error originates in the macro `integer_sum_product` (in Nightly builds, run with -Z macro-backtrace for more info)
help: consider giving `sum` an explicit type, where the type for type parameter `S` is specified
   |
LL |     let sum: i32 = v
   |            +++++
```

Fix rust-lang/rust#100802.

### CODE REVIEW

File: compiler/rustc_trait_selection/src/error_reporting/traits/fulfillment_errors.rs [hunk 1]
```diff
@@ -2256,6 +2256,16 @@ impl<'a, 'tcx> TypeErrCtxt<'a, 'tcx> {
...
+            let mut specific_candidates = candidates.clone();
+            specific_candidates.retain(|(tr, _)| {
+                tr.with_replaced_self_ty(self.tcx, trait_pred.skip_binder().self_ty())
+                    == trait_pred.skip_binder().trait_ref
+            });
+            if !specific_candidates.is_empty() {
+                // We have found a subset of impls that fully satisfy the expected trait, only
+                // mention those types.
+                candidates = specific_candidates;
+            }
```
Comment (estebank) [inline compiler/rustc_trait_selection/src/error_reporting/traits/fulfillment_errors.rs:2263]: This gives us the

```
help: the trait `Sum` is implemented for `i32`
    --> library/core/src/iter/traits/accum.rs:48:9
     |
  48 |         impl Sum for $a {
     |         ^^^^^^^^^^^^^^^
...
 204 | integer_sum_product! { i8 i16 i32 i64 i128 isize u8 u16 u32 u64 u128 usize }
     | ---------------------------------------------------------------------------- in this macro invocation
```

instead of
```
     = help: the following types implement trait `Sum<A>`:
               `Duration` implements `Sum<&'a Duration>`
               `Duration` implements `Sum`
               `Option<T>` implements `Sum<Option<U>>`
               `Result<T, E>` implements `Sum<Result<U, E>>`
               `Saturating<u128>` implements `Sum<&'a Saturating<u128>>`
               `Saturating<u128>` implements `Sum`
               `Saturating<u16>` implements `Sum<&'a Saturating<u16>>`
               `Saturating<u16>` implements `Sum`
             and 88 others
```

File: compiler/rustc_trait_selection/src/error_reporting/infer/need_type_info.rs [hunk 2]
```diff
@@ -1183,8 +1223,13 @@ impl<'a, 'tcx> Visitor<'tcx> for FindInferSourceVisitor<'a, 'tcx> {
     fn visit_local(&mut self, local: &'tcx LetStmt<'tcx>) {
         intravisit::walk_local(self, local);
 
-        if let Some(ty) = self.opt_node_type(local.hir_id) {
+        if let Some(mut ty) = self.opt_node_type(local.hir_id) {
             if self.generic_arg_contains_target(ty.into()) {
+                if let Some(t) = self.ty
+                    && ty.has_infer()
+                {
+                    ty = t;
```
Comment (JohnTitor) [inline compiler/rustc_trait_selection/src/error_reporting/infer/need_type_info.rs:1287]: IIUC the logic on ambiguity.rs doesn't check what's the local type at all, right?
I wonder sometimes (inferred) self type isn't same as the local type when it has an outer type unrelated to the trait resolution, e.g. `Box<T>`, so overwriting seems a bit risky.
What's happen on suggestions for such a case?

Comment (estebank) [reply compiler/rustc_trait_selection/src/error_reporting/infer/need_type_info.rs:1287]: Note that the overwriting is purely *local* and affecting the diagnostic: we're changing what will be included in the `LetBinding` `ty` field below *not* affecting the type associated to `local.hir_id`, for that we'd have to go through `typeck.adjustments_mut()`.

Comment (JohnTitor) [reply compiler/rustc_trait_selection/src/error_reporting/infer/need_type_info.rs:1287]: I see, thank you for clarifying!

**Review by JohnTitor — APPROVED** [review]
LGTM! @bors r+

*[View changes since this review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/rust/153727/3645249d79dfb136b5d8de3ce153d19d6698d92d..42709d421e6a677ddd1cd1e1af0e9b288ddfbe5c)*
