### PR TITLE
rustdoc search: relax rules for identifiers

### LINKED ISSUE #147763: Rustdoc frontend: cannot search a number
# Description

On any webpage generated by `rustdoc`, using a number as a search term results in an error:

```
Query parser error: "Unexpected <N> (not a valid identifier)".
```

Where `<N>` is the first digit of the number searched.

Searching for rfc3339 in chrono

Searching for 3339 in chrono

# Expected Outcome

It should search.

# Version

Rust: 1.92.0-nightly (57ef8d642 2025-10-15)
Browser: Firefox 145.0b1; Chrome 141.0.7390.107

### PR DESCRIPTION
**Pull request by lolbinarycat**
fixes https://github.com/rust-lang/rust/issues/147763

### CODE REVIEW

File: tests/rustdoc-js-std/search-by-number.js [hunk 1]
```diff
@@ -0,0 +1,12 @@
+// regression test for https://github.com/rust-lang/rust/issues/147763
```
Comment (GuillaumeGomez) [inline tests/rustdoc-js-std/search-by-number.js:1]: Maybe explain what it's actually testing too?

**Review by notriddle — APPROVED** [review]
Other than guillaume's question, this looks reasonable to me.

*[View changes since this review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/rust/147860/6380899f32599ea25615d4ccd708d0e8da652b0c..97e6ef32d981593cb9d6ec6b58b3670b89b1a475)*

**Comment by lolbinarycat** [comment]
Added a much more in depth comment on the test
