### PR TITLE
Fix volatile / atomic ops on bools and small aggregates

### LINKED ISSUE #23550: `volatile_load` + newtype = LLVM assertion
### STR

``` rust
#![crate_type = "lib"]

mod mmio {
    use std::intrinsics;

    pub struct RO<T>(T) where T: Copy;

    impl<T> RO<T> where T: Copy {
        pub fn get(&self) -> T {
            unsafe {
                intrinsics::volatile_load(&self.0)
            }
        }
    }
}

struct Gpio {
    idr: mmio::RO<Idr>,
}

#[derive(Copy)]
struct Idr(u32);

fn ice(gpio: &Gpio) -> Idr {
    gpio.idr.get()
}
```

### Output

``` rust
rustc: /home/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/llvm/lib/IR/Instructions.cpp:1083: void llvm::StoreInst::AssertOK(): Assertion `getOperand(0)->getType() == cast<PointerType>(getOperand(1)->getType())->getElementType() && "Ptr must be a pointer to Val type!"' failed.
```

I think this should work given that `Idr` is a newtype over a copyable/primitive type.

### PR DESCRIPTION
**Pull request by dotdash**
Boolean values and small aggregates have a different type in args/allocas than
in SSA values but the intrinsics for volatile and atomic ops were
missing the necessary casts to handle that.

Fixes #23550

### CODE REVIEW

File: src/test/compile-fail/issue-23550.rs [hunk 1]
```diff
@@ -0,0 +1,38 @@
...
+    intrinsics::volatile_load(p);
+    intrinsics::volatile_store(p, v);
+    intrinsics::atomic_load(p);
+    intrinsics::atomic_cxchg(p, v, v);
+    intrinsics::atomic_store(p, v);
+    intrinsics::atomic_xchg(p, v);
+}
+
+#[rustc_error]
+fn main() {} //~ ERROR compilation successful
```
Comment (eddyb) [inline src/test/compile-fail/issue-23550.rs]: Why is this a compile-fail test and not run-pass?

File: src/librustc_trans/trans/base.rs [hunk 2]
```diff
@@ -983,56 +983,72 @@ pub fn load_if_immediate<'blk, 'tcx>(cx: Block<'blk, 'tcx>,
...
+    }
+}
+
+pub fn to_arg_ty_ptr<'blk, 'tcx>(bcx: Block<'blk, 'tcx>, ptr: ValueRef, ty: Ty<'tcx>) -> ValueRef {
+    if type_is_immediate(bcx.ccx(), ty) && type_of::type_of(bcx.ccx(), ty).is_aggregate() {
         // We want to pass small aggregates as immediate values, but using an aggregate LLVM type
         // for this leads to bad optimizations, so its arg type is an appropriately sized integer
         // and we have to convert it
-        Store(cx, v, BitCast(cx, dst, type_of::arg_type_of(cx.ccx(), t).ptr_to()));
+        BitCast(bcx, ptr, type_of::arg_type_of(bcx.ccx(), ty).ptr_to())
```
Comment (eddyb) [inline src/librustc_trans/trans/base.rs]: I wonder if there's any difference between `BitCast` and other forms of pointer-casting.

Comment (dotdash) [inline src/librustc_trans/trans/base.rs]: I'm not sure what you mean by that.

**Comment by dotdash** [comment]
Moved the test to run-pass.
