### PR TITLE
Fix sidebar scroll on mobile devices

### LINKED ISSUE #77942: Rustdoc closes sidebar when window is resized
On a small viewport where the sidebar is hidden by default, if the sidebar is opened and then the window is resized the sidebar closes.

This makes rustdoc pages practically unusable on Android Firefox as scrolling down hides the top bar and resizes the window.

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Fixes #77942.

The issue was coming from the appearance/disappearance of the "wrapper" on the mobile devices web browsers, which triggers the "resize" event, calling the `hideSidebar` function is the JS code.

r? @jyn514

### CODE REVIEW

File: src/librustdoc/html/static/main.js [hunk 1]
```diff
@@ -2716,10 +2716,6 @@ function defocusSearchBar() {
         };
     }
 
-    window.onresize = function() {
-        hideSidebar();
-    };
```
Comment (jyn514) [inline src/librustdoc/html/static/main.js:2721]: This will impact desktops too, right? Is that intentional? Do you know why this was added in the first place?

Comment (GuillaumeGomez) [reply src/librustdoc/html/static/main.js:2721]: It won't have impact on desktop because it was only used for mobile devices. As for what it was used originally, I'm not sure... It was three years ago so things evolved quite a lot in the meantime in both rustdoc and mobile web browsers...

Comment (jyn514) [reply src/librustdoc/html/static/main.js:2721]: Ok, seems reasonable.

**Comment by jyn514** [comment]
@bors r+ 

not 100% sure about this change but I trust @GuillaumeGomez's word.
