### PR TITLE
merge unused-extern-crate and unnecessary-extern-crate lints

### LINKED ISSUE #50672: Lint for removing `extern crate` has false positive when crate is used
The [following code](https://play.rust-lang.org/?gist=18ff3facf246fe36e51170f368d373c4&version=nightly&mode=debug)

```rust
#![feature(rust_2018_preview)]
#![deny(unnecessary_extern_crate)]
#![allow(unused_imports)]

extern crate libc;

mod foo {
    use crate::libc;
}

fn main() {}
```

generates an error:

```
error: `extern crate` is unnecessary in the new edition
 --> src/main.rs:5:1
  |
5 | extern crate libc;
  | ^^^^^^^^^^^^^^^^^^ help: remove it
  |
note: lint level defined here
 --> src/main.rs:2:9
  |
2 | #![deny(unnecessary_extern_crate)]
  |         ^^^^^^^^^^^^^^^^^^^^^^^^

error: aborting due to previous error

error: Could not compile `playground`.
```

but if the `extern crate libc;` is removed it no longer compiles!

This situation has come up on two occasions so far:

1. In attempting to fix https://github.com/rust-lang/rust/issues/50660 the lint started firing for `use libc;` and rustfix rewrote it to `use crate::libc;`. This worked in the 2015 edition because `extern crate libc;` was declared at the top. Later this `unnecessary_extern_crate` lint ended up showing the error above.
2. Discovered in https://github.com/rust-lang/rust/pull/50665 the `use *;` statement is entirely disallowed in the 2018 edition, so we instead recommend the replacement `use crate::*;`. This, however, will also break if one of the identifiers used is an `extern crate` as the lint currently suggests removing `extern crate`

### PR DESCRIPTION
**Pull request by nikomatsakis**
Extend the `unused_extern_crates` lint to offer a suggestion to remove the extern crate and remove the `unnecessary_extern_crate` lint.

Still a few minor issues to fix:
- [x] this *does* now leave a blank line... (defer to https://github.com/rust-lang/rust/issues/51176)
  - idea: extend the span to be replaced by 1 character if the next character is a `\n`
- [x] what about macros? do we need to watch out for that? (defer to https://github.com/rust-lang/rust/issues/48704)
- [x] also it doesn't work for `extern crate foo; fn main() { foo::bar(); }`
  - this is subtle: the `foo` might be shadowing a glob import too, can't always remove
  - defer to https://github.com/rust-lang/rust/issues/51177
- [x] we also don't do the `pub use` rewrite thang (https://github.com/rust-lang/rust/issues/51013)

Spun off from https://github.com/rust-lang/rust/pull/51010

Fixes #50672 

r? @alexcrichton

### CODE REVIEW

**Comment by alexcrichton** [comment]
Seems like a fine idea to me! I haven't personally looked too closely at this lint yet for removing `extern crate` annotations, but fusing lints seems fine by me :)

**Comment by nikomatsakis** [comment]
ok I added the `pub use` logic etc back in, but I need to do more tests

**Comment by alexcrichton** [comment]
r=me when this is passing travis!

**Comment by nikomatsakis** [comment]
This is gonna break clippy cc @Manishearth and @oli-obk — but pretty trivial change.

**Comment by nikomatsakis** [comment]
@estebank btw do we have some utility that says "if the last character of a span is a `\n`, grow the span by one character?"

I'd like to remove a line like

```rust
extern crate foo;
```

by replacing its span with `""`, but this leaves a blank line.

**Comment by estebank** [comment]
> do we have some utility that says "if the last character of a span is a \n, grow the span by one character?"

No, but you could use [`take_span_while`](https://github.com/rust-lang/rust/blob/master/src/libsyntax/codemap.rs#L680-L702) or [`span_until_non_whitespace`](https://github.com/rust-lang/rust/blob/master/src/libsyntax/codemap.rs#L660-L678).

**Comment by andjo403** [comment]
@nikomatsakis shall this lint also work with unused extern crates from the --extern flag to rustc?
have been thinking that it can be the only way to find if unused crates is added to the toml file.

**Comment by nikomatsakis** [comment]
@andjo403 that would be a nice extension; it doesn't now though. Ideally, we'd have some way to point into the `Cargo.toml`...

**Comment by kennytm** [comment]
@bors retry p=29 #40474

```
[02:18:16] fatal: unable to access 'https://github.com/Aaronepower/tokei/': Failed to connect to github.com port 443: Connection timed out
```

**Comment by SimonSapin** [comment]
Does `unused_extern_crates` now warn by default?

File: src/test/ui-fulldeps/unnecessary-extern-crate.rs [hunk 1]
```diff
@@ -10,48 +10,90 @@
...
+            d::getpid();
+        }
     }
 }
 
 
-fn main() {}
+fn main() {
+    unsafe { a::getpid(); }
+    unsafe { b::getpid(); }
```
Comment (eddyb) [inline src/test/ui-fulldeps/unnecessary-extern-crate.rs]: What are these calls testing? As per https://github.com/rust-lang/rust/pull/49219#issuecomment-441618498, these don't exist on `wasm32`, is there a suitable replacement for `libc`?
Or should I just ignore the test on `wasm32` (ideally I wouldn't).

cc @petrochenkov @alexcrichton

Comment (petrochenkov) [reply src/test/ui-fulldeps/unnecessary-extern-crate.rs]: I suspect that they make `a`, `b`, etc used, so they report "`extern crate` is not idiomatic" rather than "`extern crate` is unused".

AFAIK, `libc` has universally available names like `c_int` or `c_void`, so they can be used instead.
```rust
type A = a::c_int; // Makes `a` used
```

Comment (eddyb) [reply src/test/ui-fulldeps/unnecessary-extern-crate.rs]: No, `wasm32` has an empty `libc` last I checked. Maybe we can flip `alloc` and `libc`, as I expect `alloc` to not be empty on `wasm32`?

Comment (petrochenkov) [reply src/test/ui-fulldeps/unnecessary-extern-crate.rs]: `alloc` would do too.
Or a new custom crate in the `auxiliary` dir.
