### PR TITLE
rustc: Fix (again) simd vectors by-val in ABI

### LINKED ISSUE #50154: Small SIMD test fails with --release but passes without
Full repro here:
https://github.com/danielrh/simd_playground run with `cargo test --release`
failing test is here:
```rust
#![feature(stdsimd)]
mod test {
#[test]
fn baseline() {
use std::simd::*;
   let symbol = 2i16;
   let inc = 1i16;
   let data = i16x16::new(4, 8, 12, 16, 20, 24, 28, 32, 36, 40, 44, 48, 52, 56, 60, 64);
   let one_to_16 = i16x16::new(1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16);
   let increment_v = i16x16::splat(inc);
   let mask_v = unsafe {
            ::std::arch::x86_64::_mm256_cmpgt_epi16(::std::arch::x86_64::__m256i::from_bits(one_to_16),
                                                   ::std::arch::x86_64::__m256i::from_bits(i16x16::splat(i16::from(symbol))))
    };
    let output = data + (increment_v & i16x16::from_bits(mask_v));
    let mut xfinal = [0i16; 16];
    output.store_unaligned(&mut xfinal);
    assert_eq!(xfinal, [4, 8, 13, 17, 21, 25, 29, 33, 37, 41, 45, 49, 53, 57, 61, 65]);
}
}
```
using: 
```rustc 1.27.0-nightly (ac3c2288f 2018-04-18)
binary: rustc
commit-hash: ac3c2288f9f9d977acb46406ba60033d65165a7b
commit-date: 2018-04-18
host: x86_64-apple-darwin
release: 1.27.0-nightly
LLVM version: 6.0
```
on OSX 10.12.6 (16G1314)

and also on linux
```
rustc --verbose --version
rustc 1.27.0-nightly (ac3c2288f 2018-04-18)
binary: rustc
commit-hash: ac3c2288f9f9d977acb46406ba60033d65165a7b
commit-date: 2018-04-18
host: x86_64-unknown-linux-gnu
release: 1.27.0-nightly
LLVM version: 6.0
```

I was unable to reproduce the above problem by making a simple main with the above function, so it could be something to do with the build options.

One more note: the same exact test and code have been working for months with stdsimd 0.0.3 and 0.0.4 crate. I couldn't get that crate to build with nightly 1.27.0, so I couldn't see if it still worked.

### LINKED ISSUE #52636: _mm256_loadu_si256 only loads 128 bits when compiled with default cargo build --release
The AVX2 intrinsic `_mm256_loadu_si256` fully loads all 256 bits from memory into the register when compiled without any optimization, but only loads 128 bits when compiled with the default `cargo build --release` option. This small program exhibits the issue:

```rust
use std::arch::x86_64;

fn main() {
    if is_x86_feature_detected!("avx2") {
        let load_bytes: [u8; 32] = [0x0f; 32];
        let lb_ptr = load_bytes.as_ptr();
        let reg_load = unsafe {
            x86_64::_mm256_loadu_si256(
                lb_ptr as *const x86_64::__m256i
            )
        };
        println!("{:?}", reg_load);
        let mut store_bytes: [u8; 32] = [0; 32];
        let sb_ptr = store_bytes.as_mut_ptr();
        unsafe {
            x86_64::_mm256_storeu_si256(sb_ptr as *mut x86_64::__m256i, reg_load);
        }
        assert_eq!(load_bytes, store_bytes);
    } else {
        println!("AVX2 is not supported on this machine/build.");
    }
}
```

When I run `cargo run`, this is the output:

```
   Compiling...
    Finished dev [unoptimized + debuginfo] target(s) in 0.33s
     Running `target/debug/avx2_bug_hunt`
__m256i(1085102592571150095, 1085102592571150095, 1085102592571150095, 1085102592571150095)
```

However, with `cargo run --release`, this is the output:
```
   Compiling...
    Finished release [optimized] target(s) in 0.26s
     Running `target/release/avx2_bug_hunt`
__m256i(1085102592571150095, 1085102592571150095, 0, 0)
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `[15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15]`,
 right: `[15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]`', src/main.rs:18:9
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

I am on macOS 10.13.6 with a Core i7 I7-4960HQ, and the output of `rustc --version --verbose` is

```
rustc 1.27.2
binary: rustc
commit-hash: unknown
commit-date: unknown
host: x86_64-apple-darwin
release: 1.27.2
LLVM version: 6.0
```

Curiously, when inspecting the assembly of `main`, the call to `_mm256_loadu_si256` is not inlined, but instead generates this function:

```
avx2_bug_hunt`core::coresimd::x86::avx::_mm256_loadu_si256::hd7fc98ebefdce593:
avx2_bug_hunt[0x1000018a0] <+0>:  pushq  %rbp
avx2_bug_hunt[0x1000018a1] <+1>:  movq   %rsp, %rbp
avx2_bug_hunt[0x1000018a4] <+4>:  vmovaps %ymm0, (%rdi)
avx2_bug_hunt[0x1000018a8] <+8>:  popq   %rbp
avx2_bug_hunt[0x1000018a9] <+9>:  vzeroupper 
avx2_bug_hunt[0x1000018ac] <+12>: retq   
avx2_bug_hunt[0x1000018ad] <+13>: nopl   (%rax)
```

Note the `vzeroupper` instruction, which clears out the non-XMM registers. This is incorrect behavior, `_m256i` requires the full YMM register to be loaded unmodified. A similar spurious `vzeroupper` is also present in the assembly generated for `_mm256_storeu_si256`, but after the register is stored into memory.

### LINKED ISSUE #54583: Release builds using AVX code produce incorrect output
# Code 

```
#[cfg(target_arch = "x86_64")]
use std::arch::x86_64::*;

fn main() {
    unsafe {
        let f = _mm256_set_pd(2.0, 2.0, 2.0, 2.0);
        let r = _mm256_mul_pd(f, f);

        println!("{:?}", r);
    }
}
```
# Output

The expected output is 
```
__m256d(4.0, 4.0, 4.0, 4.0)
```
The actual output is
```
__m256d(4.0, 4.0, 0.0, 0.0)
```

# Notes
- The code built in debug mode produces the expected result. This issue only occurs in a release build.
- Using `_mm` instead of `_mm256` results in correct output in both debug and release mode.
- Code using only `_mm` or `_mm256` yields the same performance (I have another piece of code for that. I can provide it if needed).

# Versions
The issue can be reproduced with 1.30.0-nightly (2018-09-24), 1.30.0-beta.7, 1.29.0.

### LINKED ISSUE #55059: Miscompilation of SIMD when crossing target_feature boundaries
This is a reduced example of a problem I've run into trying to make safe SIMD wrappers. The idea here is to have a newtype that can only be constructed when the capability is dynamically detected. However, the compiler seems to get confused about calling conventions when calling into code with `target_feature` enabled from code that doesn't.

```rust
#[cfg(target_arch = "x86_64")]
use std::arch::x86_64::*;

#[target_feature(enable = "avx")]
unsafe fn avx_mul(a: __m256, b: __m256) -> __m256 {
    _mm256_mul_ps(a, b)
}

#[target_feature(enable = "avx")]
unsafe fn avx_store(p: *mut f32, a: __m256) {
    _mm256_storeu_ps(p, a)
}

#[target_feature(enable = "avx")]
unsafe fn avx_setr(a: f32, b: f32, c: f32, d: f32, e: f32, f: f32, g: f32, h: f32) -> __m256 {
    _mm256_setr_ps(a, b, c, d, e, f, g, h)
}

#[target_feature(enable = "avx")]
unsafe fn avx_set1(a: f32) -> __m256 {
    _mm256_set1_ps(a)
}

struct Avx(__m256);

fn mul(a: Avx, b: Avx) -> Avx {
    unsafe { Avx(avx_mul(a.0, b.0)) }
}

fn set1(a: f32) -> Avx {
    unsafe { Avx(avx_set1(a)) }
}

fn setr(a: f32, b: f32, c: f32, d: f32, e: f32, f: f32, g: f32, h: f32) -> Avx {
    unsafe { Avx(avx_setr(a, b, c, d, e, f, g, h)) }
}

unsafe fn store(p: *mut f32, a: Avx) {
    avx_store(p, a.0);
}

pub fn main() {
    let mut result = [0.0f32; 8];
    let a = mul(setr(0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0), set1(0.25));
    unsafe { store(result.as_mut_ptr(), a)}
    println!("{:?}", result);
}

```

([Playground](https://play.rust-lang.org/?version=stable&mode=release&edition=2015&gist=385b6ea5622ac948e6e46842a64a7579))

Output:

```
[0.0, 5.0, 12.0, 21.0, 0.0, 0.0, 0.0, 0.0]

```

Errors:

```
   Compiling playground v0.0.1 (file:///playground)
    Finished release [optimized] target(s) in 0.59s
     Running `target/release/playground`

```

In a debug build, the answer is `[0.0, 0.25, 0.5, 0.75, 1.0, 1.25, 1.5, 1.75]` as expected. Notice that the first 3 values of the miscompiled version are [0, 1, 2, 3] * [4, 5, 6, 7], suggesting that the halves are getting scrambled (and this is confirmed by looking at the generated asm).

Also, this just crashes on Windows.

Same miscompilation happens if I move the Avx() newtype wrapper up into the top four functions.

It's possible I don't understand the rules for what's safe to do in SIMD. If that's the case, the limitations on passing values across function boundaries should be documented.

### PR DESCRIPTION
**Pull request by alexcrichton**
The issue of passing around SIMD types as values between functions has
seen [quite a lot] of [discussion], and although we thought [we fixed
it][quite a lot] it [wasn't]! This PR is a change to rustc to, again,
try to fix this issue.

The fundamental problem here remains the same, if a SIMD vector argument
is passed by-value in LLVM's function type, then if the caller and
callee disagree on target features a miscompile happens. We solve this
by never passing SIMD vectors by-value, but LLVM will still thwart us
with its argument promotion pass to promote by-ref SIMD arguments to
by-val SIMD arguments.

This commit is an attempt to thwart LLVM thwarting us. We, just before
codegen, will take yet another look at the LLVM module and demote any
by-value SIMD arguments we see. This is a very manual attempt by us to
ensure the codegen for a module keeps working, and it unfortunately is
likely producing suboptimal code, even in release mode. The saving grace
for this, in theory, is that if SIMD types are passed by-value across
a boundary in release mode it's pretty unlikely to be performance
sensitive (as it's already doing a load/store, and otherwise
perf-sensitive bits should be inlined).

The implementation here is basically a big wad of C++. It was largely
copied from LLVM's own argument promotion pass, only doing the reverse.
In local testing this...

Closes #50154
Closes #52636
Closes #54583
Closes #55059

[quite a lot]: https://github.com/rust-lang/rust/pull/47743
[discussion]: https://github.com/rust-lang/rust/issues/44367
[wasn't]: https://github.com/rust-lang/rust/issues/50154

### CODE REVIEW

**Comment by gnzlbg** [comment]
cc @rkruppe

File: src/rustllvm/DemoteSimd.cpp [hunk 1]
```diff
@@ -0,0 +1,186 @@
...
+    assert(!F->getReturnType()->isVectorTy());
+
+    // If any argument to this function is a by-value vector type, then that's
+    // bad! The compiler didn't generate any functions that looked like this,
+    // and we try to rely on LLVM to not do this! Argument promotion may,
+    // however, promote arguments from behind references. In any case, figure
+    // out if we're interested in demoting this argument.
+    bool anyVector = false;
+    for (auto &Arg : F.args())
+      anyVector = anyVector || Arg.getType()->isVectorTy();
```
Comment (gnzlbg) [inline src/rustllvm/DemoteSimd.cpp]: Shouldn't this stop at the first argument that's a vector?:

```c++
for (auto &Arg : F.args()) {
  if (Arg.getType()->isVectorTy()) {
    Ret.push_back(&F);
    break;
  }
}
```

**Comment by gnzlbg** [comment]
It might be worth it to run the `packed_simd` examples as benchmarks on this change.

**Comment by alexcrichton** [comment]
@gnzlbg sure! I'm not sure there's an easy way to compare the output, but [this is the output I got from nightly and this PR](https://gist.github.com/alexcrichton/8a444db57633b5164ecd16a21a9f5a79)

**Comment by alexcrichton** [comment]
@Mark-Simulacrum heh this pr does indeed make more sense for perf! I believe basically nothing in rustc uses explicit SIMD though, so I don't think this'll be a good source of benchmarks :(

**Comment by Mark-Simulacrum** [comment]
Hm, true, but I'm hopeful we can at least get manual or perhaps https://lolbench.rs/ results.

**Comment by gnzlbg** [comment]
@alexcrichton this does not appear to affect the performance of those benchmarks :)

File: src/librustc_codegen_llvm/back/write.rs [hunk 2]
```diff
@@ -691,6 +691,38 @@ unsafe fn codegen(cgcx: &CodegenContext,
...
+        // tough part is that we want this to actually work correctly!
+        //
+        // We go to great lengths to make sure this works, and one crucial
+        // aspect is that vector arguments (simd types) are never passed by
+        // value in the ABI of functions. It turns out, however, that LLVM will
+        // undo our "clever work" of passing vector types by reference. Its
+        // argument promotion pass will promote these by-ref arguments to
+        // by-val. That, however, introduces codegen errors!
+        //
+        // The upstream LLVM bug [1] has unfortunatey not really seen a lot of
```
Comment (nikomatsakis) [inline src/librustc_codegen_llvm/back/write.rs]: Nit "unfortunatey" => "unfortunately"

**Review by nikomatsakis — APPROVED** [review]
So, I didn't see any obvious problems with this code, but I'm not particularly familiar with LLVM. I'd rather get a review from @eddyb, @nagisa, or somebody else who pokes more closely at LLVM on a regular basis.

File: src/test/codegen/repr-transparent.rs [hunk 3]
```diff
@@ -108,7 +108,7 @@ struct f32x4(f32, f32, f32, f32);
 #[repr(transparent)]
 pub struct Vector(f32x4);
 
-// CHECK: define <4 x float> @test_Vector(<4 x float> %arg0)
+// CHECK: define <4 x float> @test_Vector(<4 x float>* %arg0)
 #[no_mangle]
 pub extern fn test_Vector(_: Vector) -> Vector { loop {} }
```
Comment (nagisa) [inline src/test/codegen/repr-transparent.rs]: Is this change *really* correct?

File: src/rustllvm/DemoteSimd.cpp (hunk 1 above)
Comment (gnzlbg) [reply src/rustllvm/DemoteSimd.cpp]: Can one use `llvm/ADT/STLExtras.h` here? This:

```c++
any_of(F.args(), [](auto &arg) { return arg.getType()->isVectorTy().; })
```

might work too.

Comment (rkruppe) [reply src/rustllvm/DemoteSimd.cpp]: Ah, sure, that works even better.

**Review by nagisa — COMMENTED** [review]
Ugh, is it nasty that it is necessary to do this at all. 

I would strongly prefer an approach that either involves some sort of an attribute on arguments which block the promotion in the first place or a patch to LLVM that would stop LLVM from "promoting" vectors in arguments when the callee and caller disagree on features.

With the current behaviour and proposed PR we lose a lot of information pertaining to the by-pointer arguments, that was initially given by the compiler to LLVM, and expose ourselves to potentially very nasty to figure out ABI mismatch issues as well.

To elaborate on ABI issues, the most obvious example would be the changed codegen test which tests for (now mis-)matching C ABI. The less obvious one would be code generated by rustc itself, between its own codegen units… while it could very well be that it is not a problem at this particular moment, if anybody was to work in the related area in the future, I’m sure they’d be in for a lot of pain and confusion.

File: src/test/codegen/repr-transparent.rs (hunk 3 above)
Comment (rkruppe) [reply src/test/codegen/repr-transparent.rs]: It seems wrong to affect the C ABI, or any non-Rust ABI. We deliberately only pass vectors in memory for the Rust ABI, so in a sense this pass is currently doing far more than undoing argument promotion.

**Comment by alexcrichton** [comment]
> I would strongly prefer an approach that either involves some sort of an attribute on arguments which block the promotion in the first place or a patch to LLVM that would stop LLVM from "promoting" vectors in arguments when the callee and caller disagree on features.

I agree! We have, however, [waited months for an LLVM fix](https://github.com/rust-lang/rust/issues/50154), responsibly [filed an upstream bug](https://bugs.llvm.org/show_bug.cgi?id=37358), did all the bisection to get to the above state, and nothing is moving. It doesn't look like this is going to be fixed in LLVM unless we do it, and I do not know how to fix it in LLVM. I'm interested in getting a fix in rustc for this *now*, but if someone else were willing to send a patch to LLVM for this I'd be more than happy to delete all this.

This PR is indeed not a great implementation but I believe it fits all our use cases on stable. We don't have a way to prevent promotion of these arguments so we're forcibly demoting them. In the code rustc generates the only promoted arguments are for internal functions which started out as demoted. FFI with SIMD is already unstable and has its own problems, so I have opted to not worry much here and if it's later decided to stabilize that it's a bug to fix then, I can certainly leave a comment to this effect though! I'd rather not be on the hook for blocking a bugfix affecting many users on stable while the implementation isn't perfect for possible future futures that aren't decided on yet.

**Comment by nikomatsakis** [comment]
@nagisa I definitely agree with the sentiment (and suspect @alexcrichton does too) — but it was not clear to me if that was a "r=me (holding my nose)" sort of comment or if you had some concrete idea for an alternative approach. (Unless you meant to land a PR/patch to LLVM to prevent promotion in the first place.)

File: src/test/codegen/repr-transparent.rs (hunk 3 above)
Comment (alexcrichton) [reply src/test/codegen/repr-transparent.rs]: I [mentioned below](https://github.com/rust-lang/rust/pull/55073#issuecomment-430267183), but passing SIMD values in FFI is unstable and not supported in rustc right now. It's correct that this demotion is blindly demoting all arguments, irrespective of ABI. That's not affecting stable users, however. I do not personally know of an easy fix for this (but would be willing to implement one!), and would prefer to not block the patch on a bug in what seems to be a rarely-used unstable feature

**Comment by nagisa** [comment]
As discussed on zulip, r=me if we skip external (or non-internal) functions for demotion.

**Comment by nikomatsakis** [comment]
[Link to zulip discussion](https://rust-lang.zulipchat.com/#narrow/stream/131828-t-compiler/subject/simd-pass-by-value/near/135904114)

**Comment by kennytm** [comment]
@bors r-

A bunch of errors when building `llvm-emscripten`, see error log at https://api.travis-ci.org/v3/job/443401944/log.txt.

**Comment by jackmott** [comment]
performance seems to be not significantly changed by this for my simd noise library: https://github.com/jackmott/rust-simd-noise  it has a big set of simd heavy benchmarks you can run if you want to compare more in detail.

**Comment by tstellar** [comment]
I proposed a fix for the LLVM bug here: https://reviews.llvm.org/D53554

For the work-around in rust, is there some reason why a new pass was written instead of just disabling llvm's ArgumentPromotion pass?

**Comment by alexcrichton** [comment]
Thanks so much @tstellar! I'll be very happy to remove this PR from our repo :)

I didn't actually know that passes could be selectively disabled, but that probably would have been a better fix!

**Comment by alexcrichton** [comment]
It looks like this patch also causes segfaults in CI for stdsimd, so I've [posted a revert](https://github.com/rust-lang/rust/pull/55281).

**Comment by tstellar** [comment]
@alexcrichton You can't really disable most passes if you are using the default pass pipeline defined by one of LLVM's pass managers, but you can if you build your own pipeline manually.  I wasn't sure if rust had its own pipeline or not.  If not, it might be something to consider.

**Comment by alexcrichton** [comment]
@tstellar ah ok, makes sense! We're using the default pass managers currently in rustc so it sounds like we may not be able to turn it off easily. In any case waiting for your patch is probably the quickest way now :)
