### PR TITLE
Suggest to bind `self.x` to `x` when field `x` may be in format string

### LINKED ISSUE #141350: Diagnostic assumes that braced unresolved identifiers are formatting argument
Uplifted from https://github.com/rust-lang/rust/pull/141213#discussion_r2099811526. Given

```rs
struct Foo { x: i32 }

impl Foo {
    fn foo(&self) { _ = {x}; }
}
```

the compiler outputs

```
error[E0425]: cannot find value `x` in this scope
 --> file.rs:4:26
  |
4 |     fn foo(&self) { _ = {x}; }
  |                          ^
  |
  = help: you might have meant to use the available field in a format string: `"{}", self.x`

warning: unnecessary braces around assigned value
 --> file.rs:4:25
  |
4 |     fn foo(&self) { _ = {x}; }
  |                         ^ ^
  |
  = note: `#[warn(unused_braces)]` on by default
help: remove these braces
  |
4 -     fn foo(&self) { _ = {x}; }
4 +     fn foo(&self) { _ = x; }
  |
```

Notice the (unstructured) suggestion ``you might have meant to use the available field in a format string: `"{}", self.x` `` which is obviously incorrect, there's no format string in sight and `fn foo(&self) { _ = "{}", self.x; }` is butchered.

### Meta

```
rustc 1.89.0-nightly (c43786c9b 2025-05-21)
binary: rustc
commit-hash: c43786c9b7b8d8dcc3f9c604e0e3074c16ed69d3
commit-date: 2025-05-21
host: x86_64-unknown-linux-gnu
release: 1.89.0-nightly
LLVM version: 20.1.5
```
```

### PR DESCRIPTION
**Pull request by xizheyin**
*[View all comments](https://triagebot.infra.rust-lang.org/gh-comments/rust-lang/rust/pull/141633)*

Fixes rust-lang/rust#141350

I added the new test in the first commit, and committed the changes in the second one.

r? @fmease  
cc @mejrs

### CODE REVIEW

File: compiler/rustc_resolve/src/late/diagnostics.rs [hunk 1]
```diff
@@ -766,14 +766,15 @@ impl<'ast, 'ra: 'ast, 'tcx> LateResolutionVisitor<'_, 'ast, 'ra, 'tcx> {
                     AssocSuggestion::Field(field_span) => {
                         if self_is_available {
                             let source_map = self.r.tcx.sess.source_map();
-                            // check if the field is used in a format string, such as `"{x}"`
-                            let field_is_format_named_arg = source_map
+                            // Check if the field is used in a format string, such as `{x}`.
+                            // Note that both `let y = {x}` and `"{x}"` can match this pattern.
+                            let maybe_field_is_format_named_arg = source_map
```
Comment (xizheyin) [inline compiler/rustc_resolve/src/late/diagnostics.rs:771]: Use `maybe` to imply that maybe `x` is in the format string, and add a comment here to clarify.

**Review by davidtwco — CHANGES_REQUESTED** [review]
I don't think this is an improvement, the help message being changed is just as correct as what you are suggesting, but feels more appropriate as it adds to the format macro that is where the error originates rather than adding another line entirely. You could attempt to improve this with a structured suggestion that the user add a `, foo = self.foo` argument to the format macro.

**Comment by xizheyin** [comment]
For structured suggestions, I tried, but I don't currently have a better way to get the HIR or ast of the format macro, in this diagnostic I can only get the span of x. There is so little information given here. Do you have a good idea?

**Comment by mejrs** [comment]
> I don't think this is an improvement, the help message being changed is just as correct as what you are suggesting, but feels more appropriate as it adds to the format macro that is where the error originates rather than adding another line entirely. You could attempt to improve this with a structured suggestion that the user add a `, foo = self.foo` argument to the format macro.

The problem is that there's not a good way to detect that we're in the format (or write, print etc) macro to begin with.

But format string parsing has a specialized error path for  `format!("{thing.field}")` that suggests what you say. So I guess if we just revert https://github.com/rust-lang/rust/pull/141213 then they'll eventually get there:

With that PR reverted, users will go from
`format!("{x}")` to `format!("{self.x}")` to `format!("{}", self.x)`.

Not that elegant, but it works.

**Comment by davidtwco** [comment]
> For structured suggestions, I tried, but I don't currently have a better way to get the HIR or ast of the format macro, in this diagnostic I can only get the span of x. There is so little information given here. Do you have a good idea?

Does `Span::from_expansion` help?

**Comment by xizheyin** [comment]
I tried this and it was false. Probably because it's not what the macro expands out to, but is simply treated as a variable.

**Comment by xizheyin** [comment]
This PR seems to be on hold for a while, maybe David doesn't have time on this PR for a while.
may r? @nnethercote

File: compiler/rustc_resolve/src/late/diagnostics.rs [hunk 2]
```diff
@@ -980,12 +980,15 @@ impl<'ast, 'ra, 'tcx> LateResolutionVisitor<'_, 'ast, 'ra, 'tcx> {
...
-                            let field_is_format_named_arg = source_map
+                            let field_is_format_named_arg = matches!(
+                                span.desugaring_kind(),
+                                Some(DesugaringKind::FormatLiteral { .. })
+                            ) && source_map
                                 .span_to_source(span, |s, start, _| {
-                                    Ok(s.get(start - 1..start) == Some("{"))
-                                });
-                            if let Ok(true) = field_is_format_named_arg {
+                                    Ok(s.get(start.saturating_sub(1)..start) == Some("{"))
```
Comment (xizheyin) [inline compiler/rustc_resolve/src/late/diagnostics.rs:988]: Here is a small fix, because the start may be 0 in some cases.

File: compiler/rustc_resolve/src/late/diagnostics.rs [hunk 3]
```diff
@@ -980,12 +980,15 @@ impl<'ast, 'ra, 'tcx> LateResolutionVisitor<'_, 'ast, 'ra, 'tcx> {
                     AssocSuggestion::Field(field_span) => {
                         if self_is_available {
                             let source_map = self.r.tcx.sess.source_map();
-                            // check if the field is used in a format string, such as `"{x}"`
-                            let field_is_format_named_arg = source_map
+                            let field_is_format_named_arg = matches!(
+                                span.desugaring_kind(),
+                                Some(DesugaringKind::FormatLiteral { .. })
```
Comment (xizheyin) [inline compiler/rustc_resolve/src/late/diagnostics.rs:985]: Here we check FormatLiteral.

**Review by xizheyin — COMMENTED** [review]
Sorry for late response. This version may resolve the issue.
waiting for green

*[View changes since this review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/rust/141633/2bd7a97871a74d4333bd3edb6564136167ac604b..c4f14ad560d6b821c1e30e8f75eefb8e90256ad9)*

**Review by nnethercote — APPROVED** [review]
