### PR TITLE
Suggest adding `{ .. }` around a const function call with arguments

### LINKED ISSUE #91020: Suggest surrounding with braces when using a const function with arguments with const generics.
Given the following code: [playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=158f6163789fda6c04165c1330c8a0eb)

```rust
fn foo<const N: i32>() -> i32 {
    N
}

const fn bar() -> i32 {
    1
}

const fn baz(n: i32) -> i32 {
    n
}

pub fn main() {
    foo::<bar()>();
    foo::<baz(1)>();
}
```

The current output is:

```
error: expected type, found `1`
  --> src/main.rs:15:15
   |
15 |     foo::<baz(1)>();
   |               ^ expected type

error[E0573]: expected type, found function `bar`
  --> src/main.rs:14:11
   |
14 |     foo::<bar()>();
   |           ^^^^^ not a type

error[E0747]: unresolved item provided when a constant was expected
  --> src/main.rs:14:11
   |
14 |     foo::<bar()>();
   |           ^^^^^
   |
help: if this generic argument was intended as a const parameter, surround it with braces
   |
14 |     foo::<{ bar() }>();
   |           +       +

Some errors have detailed explanations: E0573, E0747.
For more information about an error, try `rustc --explain E0573`.
```

Ideally the output should also suggest adding braces to `foo::<baz(1)>()`

### PR DESCRIPTION
**Pull request by TaKO8Ki**
closes #91020

### CODE REVIEW

File: compiler/rustc_parse/src/parser/path.rs [hunk 1]
```diff
@@ -624,9 +624,18 @@ impl<'a> Parser<'a> {
...
             match self.parse_ty() {
                 Ok(ty) => GenericArg::Type(ty),
                 Err(err) => {
+                    if is_const_fn {
+                        if let Ok(expr) = snapshot.parse_expr_res(Restrictions::CONST_EXPR, None) {
+                            *self = snapshot;
+                            return Ok(Some(self.dummy_const_arg_needs_braces(err, expr.span)));
+                        }
+                    }
+                    // self.parse_fn_call_expr();
```
Comment (davidtwco) [inline compiler/rustc_parse/src/parser/path.rs:638]: If it isn't necessary then the commented function call can be removed.

File: compiler/rustc_parse/src/parser/path.rs [hunk 2]
```diff
@@ -624,9 +624,18 @@ impl<'a> Parser<'a> {
             GenericArg::Const(self.parse_const_arg()?)
         } else if self.check_type() {
             // Parse type argument.
+            let is_const_fn = self.look_ahead(1, |t| t.kind == token::OpenDelim(token::Paren));
+            let mut snapshot = self.clone();
```
Comment (davidtwco) [inline compiler/rustc_parse/src/parser/path.rs:628]: I'm a little hesitant that we're cloning the parser before we know whether or not there is an error, but it looks like we do this elsewhere so I guess it's fine.

File: compiler/rustc_parse/src/parser/path.rs [hunk 3]
```diff
@@ -624,9 +624,18 @@ impl<'a> Parser<'a> {
...
             match self.parse_ty() {
                 Ok(ty) => GenericArg::Type(ty),
                 Err(err) => {
+                    if is_const_fn {
+                        if let Ok(expr) = snapshot.parse_expr_res(Restrictions::CONST_EXPR, None) {
```
Comment (davidtwco) [inline compiler/rustc_parse/src/parser/path.rs:633]: It looks like from the error that you're getting that attempting this additional parsing might be producing duplicate errors for some cases?

**Review by davidtwco — CHANGES_REQUESTED** [review]
Improvement looks good, some minor comments and the CI failure to fix.

File: compiler/rustc_parse/src/parser/path.rs (hunk 3 above)
Comment (TaKO8Ki) [reply compiler/rustc_parse/src/parser/path.rs:633]: After debugging, I found that cloning the parser causes the problem. If you try the following, the error is duplicated.

```rust
} else if self.check_type() {
    // Parse type argument.
    // let is_const_fn = self.look_ahead(1, |t| t.kind == token::OpenDelim(token::Paren));
    let _snapshot = self.clone();
    match self.parse_ty() {
        Ok(ty) => GenericArg::Type(ty),
        Err(err) => {
            // if is_const_fn {
            //     if let Ok(expr) = snapshot.parse_expr_res(Restrictions::CONST_EXPR, None) {
            //         *self = snapshot;
            //         return Ok(Some(self.dummy_const_arg_needs_braces(err, expr.span)));
            //     }
            // }

            // Try to recover from possible `const` arg without braces.
            return self.recover_const_arg(start, err).map(Some);
        }
    }
} else if self.token.is_keyword(kw::Const) {
```

Comment (TaKO8Ki) [reply compiler/rustc_parse/src/parser/path.rs:633]: After debugging, I found that cloning the parser causes the problem. If you try the following, the error is duplicated.

```rust
} else if self.check_type() {
    // Parse type argument.
    // let is_const_fn = self.look_ahead(1, |t| t.kind == token::OpenDelim(token::Paren));
    let _snapshot = self.clone();
    match self.parse_ty() {
        Ok(ty) => GenericArg::Type(ty),
        Err(err) => {
            // if is_const_fn {
            //     if let Ok(expr) = snapshot.parse_expr_res(Restrictions::CONST_EXPR, None) {
            //         *self = snapshot;
            //         return Ok(Some(self.dummy_const_arg_needs_braces(err, expr.span)));
            //     }
            // }

            // Try to recover from possible `const` arg without braces.
            return self.recover_const_arg(start, err).map(Some);
        }
    }
} else if self.token.is_keyword(kw::Const) {
```

Comment (TaKO8Ki) [reply compiler/rustc_parse/src/parser/path.rs]: Hmm. I've debugged a lot of things and can't understand why cloning the parser causes duplicated errors.

Comment (TaKO8Ki) [reply compiler/rustc_parse/src/parser/path.rs]: Cloning the parser before calling `parse_xxx` other than `parse_ty` does't cause this problem.

Comment (TaKO8Ki) [reply compiler/rustc_parse/src/parser/path.rs]: I would appreciate any solutions or other suggestions.

Comment (davidtwco) [reply compiler/rustc_parse/src/parser/path.rs]: Looks like `Parser` has a `Drop` implementation that emits errors based on the contents of the [`unclosed_delims`](https://doc.rust-lang.org/stable/nightly-rustc/rustc_parse/parser/struct.Parser.html#structfield.unclosed_delims) field and your snapshot is emitting those when dropped? That seems easy enough to confirm.

If that is the case, perhaps make a `diagnostic_snapshot` function on `Parser` which does a `clone` and then clears any state like this (probably just `unclosed_delims`) and use that anywhere that snapshots like these are being made. In fact, perhaps that isn't a great idea because if we want the snapshot parser to become the actual parser (i.e. `*self = snapshot`) then we don't want to lose anything we might want if the snapshot is to be kept - maybe you can experiment with adding a nice API for this that lets us stash away that state that could produce errors when the snapshot gets dropped without throwing away that state entirely, just in case we want to keep the snapshot.

Comment (TaKO8Ki) [reply compiler/rustc_parse/src/parser/path.rs]: Thank you. I missed the `Drop` implementation.

File: compiler/rustc_parse/src/parser/path.rs [hunk 4]
```diff
@@ -624,9 +624,17 @@ impl<'a> Parser<'a> {
...
         } else if self.check_type() {
             // Parse type argument.
+            let is_const_fn = self.look_ahead(1, |t| t.kind == token::OpenDelim(token::Paren));
+            let mut snapshot = self.diagnostic_snapshot();
             match self.parse_ty() {
                 Ok(ty) => GenericArg::Type(ty),
                 Err(err) => {
+                    if is_const_fn {
+                        if let Ok(expr) = snapshot.parse_expr_res(Restrictions::CONST_EXPR, None) {
+                            *self = snapshot;
```
Comment (davidtwco) [inline compiler/rustc_parse/src/parser/path.rs:634]: If we do this using `diagnostic_snapshot` then we might be missing `unclosed_delims` that we had before.

**Review by davidtwco — CHANGES_REQUESTED** [review]

File: compiler/rustc_parse/src/parser/path.rs [hunk 5]
```diff
@@ -624,9 +624,18 @@ impl<'a> Parser<'a> {
...
         } else if self.check_type() {
             // Parse type argument.
+            let is_const_fn = self.look_ahead(1, |t| t.kind == token::OpenDelim(token::Paren));
+            let mut snapshot = self.diagnostic_snapshot();
             match self.parse_ty() {
                 Ok(ty) => GenericArg::Type(ty),
                 Err(err) => {
+                    if is_const_fn {
+                        if let Ok(expr) = snapshot.parse_expr_res(Restrictions::CONST_EXPR, None) {
+                            snapshot.unclosed_delims.extend(self.unclosed_delims.clone());
```
Comment (davidtwco) [inline compiler/rustc_parse/src/parser/path.rs:634]: This would do it but if anyone else notices `diagnotic_snapshot` and wants to use it, they might miss that this is required which could result in a bug later. You could maybe make a `SnapshotParser` struct containing the cloned `Parser` and the saved `unclosed_delims`, and then I think a `Deref` implementation to `Parser` let us use it like we would `self`, you could implement a function on `Parser` (or on `SnapshotParser`, the specifics aren't that important, as long as it is hard to misuse) that takes the `SnapshotParser` and replaces itself with it and restores the `unclosed_delims`. Ideally we'd be able to replace all of the other uses of `self.clone()` in the parser for diagnostics with this machinery, and we can put some documentation comments on it that describe how it is to be used, etc.

File: compiler/rustc_parse/src/parser/diagnostics.rs [hunk 6]
```diff
@@ -179,6 +200,19 @@ impl<'a> Parser<'a> {
...
 
+    pub(super) fn restore(&mut self, snapshot: SnapshotParser<'a>) {
+        *self = snapshot.parser;
+        self.unclosed_delims.extend(snapshot.unclosed_delims.clone());
+    }
+
+    pub(super) fn diagnostic_snapshot(&self) -> SnapshotParser<'a> {
+        let mut snapshot = self.clone();
+        let unclosed_delims = self.unclosed_delims.clone();
+        // initialize unclosed_delims to avoid duplicate errors.
```
Comment (davidtwco) [inline compiler/rustc_parse/src/parser/diagnostics.rs:211]:
```suggestion
        // Clear `unclosed_delims` in snapshot to avoid
        // duplicate errors being emitted when the `Parser`
        // is dropped (which may or may not happen, depending
        // if the parsing the snapshot is created for is successful)
```

File: compiler/rustc_parse/src/parser/diagnostics.rs [hunk 7]
```diff
@@ -154,6 +156,25 @@ impl AttemptLocalParseRecovery {
     }
 }
 
+pub(super) struct SnapshotParser<'a> {
```
Comment (davidtwco) [inline compiler/rustc_parse/src/parser/diagnostics.rs:159]: Could you add a documentation comment on this describing what it is for?

File: compiler/rustc_parse/src/parser/diagnostics.rs [hunk 8]
```diff
@@ -179,6 +200,19 @@ impl<'a> Parser<'a> {
         &self.sess.span_diagnostic
     }
 
+    pub(super) fn restore(&mut self, snapshot: SnapshotParser<'a>) {
+        *self = snapshot.parser;
+        self.unclosed_delims.extend(snapshot.unclosed_delims.clone());
+    }
+
+    pub(super) fn diagnostic_snapshot(&self) -> SnapshotParser<'a> {
```
Comment (davidtwco) [inline compiler/rustc_parse/src/parser/diagnostics.rs:208]: Likewise, a documentation comment on this function would be great.

```suggestion
    pub(super) fn create_snapshot_for_diagnostics(&self) -> SnapshotParser<'a> {
```

File: compiler/rustc_parse/src/parser/diagnostics.rs [hunk 9]
```diff
@@ -179,6 +200,19 @@ impl<'a> Parser<'a> {
         &self.sess.span_diagnostic
     }
 
+    pub(super) fn restore(&mut self, snapshot: SnapshotParser<'a>) {
```
Comment (davidtwco) [inline compiler/rustc_parse/src/parser/diagnostics.rs:203]:
```suggestion
    pub(super) fn restore_snapshot(&mut self, snapshot: SnapshotParser<'a>) {
```

Similarly, a documentation comment would be helpful.

File: compiler/rustc_parse/src/parser/path.rs [hunk 10]
```diff
@@ -624,9 +624,18 @@ impl<'a> Parser<'a> {
             GenericArg::Const(self.parse_const_arg()?)
         } else if self.check_type() {
             // Parse type argument.
+            let is_const_fn = self.look_ahead(1, |t| t.kind == token::OpenDelim(token::Paren));
+            let mut snapshot = self.diagnostic_snapshot();
```
Comment (davidtwco) [inline compiler/rustc_parse/src/parser/path.rs:628]: Could you try using this other places in the parser where we make a snapshot manually?

**Review by davidtwco — CHANGES_REQUESTED** [review]
This looks good, thanks for making these changes, I've left a few more comments.

File: compiler/rustc_parse/src/parser/path.rs (hunk 10 above)
Comment (TaKO8Ki) [reply compiler/rustc_parse/src/parser/path.rs]: I replaced all `self.clone()` with `self.create_snapshot_for_diagnostic()`.
