### PR TITLE
Fortify handing of where bounds on trait & trait alias definitions

### LINKED ISSUE #96664: Regression in nightly-2022-05-01 relating to trait objects
### Code

When updating from nightly nightly-2022-04-30-x86_64-unknown-linux-gnu to nightly nightly-2022-05-01-x86_64-unknown-linux-gnu, some code that previously compiled stopped compiling. Here's the basic idea of it:

```rust
pub trait State = Clone + Send + Sync + PartialOrd + PartialEq + fmt::Display;
pub trait RandState<S: State> = FnMut() -> S + Send;

pub struct Evolver<E: Evaluator> {
    rand_state: Box<dyn RandState<E::State>>
}
```

I expected to see this happen: compiles

Instead, this happened:
```
error[E0225]: only auto traits can be used as additional traits in a trait object
   --> src/gen/evaluated.rs:172:26
    |
172 |         genfn: &mut (dyn RandState<S> + '_),
    |                          ^^^^^^^^^^^^
    |                          |
    |                          trait alias used in trait object type (additional use)
    |                          trait alias used in trait object type (first use)
    |
   ::: src/evolve/evolver.rs:14:24
    |
14  | pub trait RandState<S: State> = FnMut() -> S + Send;
    |                        -----    ------------ first non-auto trait
    |                        |
    |                        referenced here (additional use)
    |
   ::: src/eval.rs:8:19
    |
8   | pub trait State = Clone + Send + Sync + PartialOrd + PartialEq + fmt::Display;
    |                   ----- additional non-auto trait
    |
    = help: consider creating a new trait with all of these as supertraits and using that trait here instead: `trait NewTrait: FnMut<()> + Clone + PartialOrd + PartialEq + std::fmt::Display {}`

```

This code previously compiled, and the code already does what the advice of the error message suggests, so it seems like a regression to me.

If needed, you can get the full repro by looking at https://github.com/Edgeworth/memega

### Version it worked on

nightly-2022-04-30-x86_64-unknown-linux-gnu

### Version with regression

nightly-2022-05-01-x86_64-unknown-linux-gnu

### LINKED ISSUE #96665: cycle detected when computing the super predicates of `...`
### Code

I tried this code: 

```rust
pub trait Sequence<Item, Subsequence: Sequence<Item, Subsequence>> {}

pub trait NodeWalk<Graph: GraphBase, NodeSubwalk: NodeWalk<Graph, NodeSubwalk>>:
    Sequence<Graph::NodeIndex, NodeSubwalk>
{
}

pub trait GraphBase {
    type NodeIndex;
}

pub trait WalkableGraph: GraphBase {}
```

[playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=b12a9e880f38a2395e0a784faa943eea)

(this example was created by stripping down https://crates.io/crates/traitgraph/0.10.0)

I expected to see this happen: it should build on nightly as it does on beta and stable

Instead, this happened:

```
Compiling playground v0.0.1 (/playground)
error[E0391]: cycle detected when computing the super predicates of `NodeWalk`
 --> src/lib.rs:5:1
  |
5 | / pub trait NodeWalk<Graph: GraphBase, NodeSubwalk: NodeWalk<Graph, NodeSubwalk>>:
6 | |     Sequence<Graph::NodeIndex, NodeSubwalk>
7 | | {
8 | | }
  | |_^
  |
note: ...which requires computing the super traits of `NodeWalk`...
 --> src/lib.rs:6:14
  |
6 |     Sequence<Graph::NodeIndex, NodeSubwalk>
  |              ^^^^^^^^^^^^^^^^
note: ...which requires computing the bounds for type parameter `Graph`...
 --> src/lib.rs:5:20
  |
5 | pub trait NodeWalk<Graph: GraphBase, NodeSubwalk: NodeWalk<Graph, NodeSubwalk>>:
  |                    ^^^^^
  = note: ...which again requires computing the super predicates of `NodeWalk`, completing the cycle
note: cycle used when collecting item types in top-level module
 --> src/lib.rs:5:1
  |
5 | / pub trait NodeWalk<Graph: GraphBase, NodeSubwalk: NodeWalk<Graph, NodeSubwalk>>:
6 | |     Sequence<Graph::NodeIndex, NodeSubwalk>
7 | | {
8 | | }
  | |_^

For more information about this error, try `rustc --explain E0391`.
error: could not compile `playground` due to previous error
```

### Version it worked on

It most recently worked on: stable 1.60.0 and 1.61.0-beta.4 (69a6d12e9 2022-04-25)

### Version with regression

`rustc --version --verbose`:
```
rustc 1.62.0-nightly (bed05e996 2022-05-02)
binary: rustc
commit-hash: bed05e996e37e44b1a3980b84754af621fd3c4ce
commit-date: 2022-05-02
host: x86_64-unknown-linux-gnu
release: 1.62.0-nightly
LLVM version: 14.0.1
```

@rustbot modify labels: +regression-from-stable-to-nightly -regression-untriaged

### PR DESCRIPTION
**Pull request by cjgillot**
Closes https://github.com/rust-lang/rust/issues/96664
Closes https://github.com/rust-lang/rust/issues/96665

Since https://github.com/rust-lang/rust/pull/93803, when listing all bounds and predicates we now need to account for the possible presence of predicates on any of the generic parameters.  Both bugs were hidden by the special handling of bounds at  the generic parameter declaration position.

Trait alias expansion used to confuse predicates on `Self` and where predicates.
Exiting too late when listing all the bounds caused a cycle error.

### CODE REVIEW

**Comment by michaelwoerister** [comment]
I don't think I'm a good reviewer for this. Re-rolling the dice: r? rust-lang/compiler

File: src/test/ui/traits/issue-65673.rs [hunk 1]
```diff
@@ -7,6 +7,6 @@ trait Alias<T> = where T: Trait;
 
 impl<T> WithType for T {
     type Ctx = dyn Alias<T>;
-//~^ ERROR the size for values of type `(dyn Trait + 'static)` cannot be known at compilation time
+    //~^ ERROR at least one trait is required for an object type [E0224]
```
Comment (b-naber) [inline src/test/ui/traits/issue-65673.rs:10]: @compiler-errors Is this not a diagnostics regression?

Comment (compiler-errors) [reply src/test/ui/traits/issue-65673.rs:10]: why would this be a diagnostics regression? i thought the previous error message was nonsense, since trait alias "Alias" has no trait types...

Comment (b-naber) [reply src/test/ui/traits/issue-65673.rs:10]: I think you're right, this isn't a regression. The new error message is somewhat confusing though.
