### PR TITLE
Fix diagnostic suggests adding type `[type error]`

### LINKED ISSUE #79040: Diagnostic suggests adding type `[type error]`
I think the suggestion is trying to suggest a type, but gets a `TyKind::Error` due to the type error in the body of the `const`. Ideally we would just not suggest a type, but there are probably a lot of other places that this issue occurs.

```rust
const FOO = "hello" + 1;
```

([Playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=dca4d4e8947686a6bad3656973181094))

Errors:

```
   Compiling playground v0.0.1 (/playground)
error[E0369]: cannot add `{integer}` to `&str`
 --> src/lib.rs:1:21
  |
1 | const FOO = "hello" + 1;
  |             ------- ^ - {integer}
  |             |
  |             &str

error: missing type for `const` item
 --> src/lib.rs:1:7
  |
1 | const FOO = "hello" + 1;
  |       ^^^ help: provide a type for the item: `FOO: [type error]`

error: aborting due to 2 previous errors

For more information about this error, try `rustc --explain E0369`.
error: could not compile `playground`.

To learn more, run the command again with --verbose.

```

### PR DESCRIPTION
**Pull request by henryboisdequin**
Fixes #79040

### Unresolved questions:

<del>Why does this change output the diagnostic twice (`src/test/ui/79040.rs`)?</del> Thanks @oli-obk

### CODE REVIEW

File: src/test/ui/parser/item-free-static-no-body-semantic-fail.rs [hunk 1]
```diff
@@ -3,9 +3,9 @@
 fn main() {}
 
 static A: u8; //~ ERROR free static item without body
-static B; //~ ERROR free static item without body
+static B;
 //~^ ERROR missing type for `static` item
 
 static mut C: u8; //~ ERROR free static item without body
-static mut D; //~ ERROR free static item without body
```
Comment (oli-obk) [inline src/test/ui/parser/item-free-static-no-body-semantic-fail.rs:10]: I think you removed the wrong error label

**Comment by oli-obk** [comment]
> Why does this change output the diagnostic twice (`src/test/ui/79040.rs`)?

It always did that, we just hide duplicates by default. The test suite wants to know about all diagnostics, so it doesn't do deduplication

File: src/test/ui/parser/item-free-static-no-body-semantic-fail.rs (hunk 1 above)
Comment (henryboisdequin) [reply src/test/ui/parser/item-free-static-no-body-semantic-fail.rs:10]: Thanks, I have addressed this comment

**Comment by henryboisdequin** [comment]
@oli-obk I think this was the 1,419'th addition to `src/test/ui` hence why the tidy error 😮. What should I do to fix this?

File: src/test/ui/79040.rs [hunk 2]
```diff
@@ -0,0 +1,6 @@
+fn main() {
```
Comment (JohnTitor) [inline src/test/ui/79040.rs:1]: This file name should be `issue-79040.rs` and can be placed in `ui/typeck` or `ui/consts`, I think.

File: src/test/ui/typeck/issue-79040.stderr [hunk 3]
```diff
@@ -0,0 +1,19 @@
+error[E0369]: cannot add `{integer}` to `&str`
+  --> $DIR/79040.rs:2:25
```
Comment (JohnTitor) [inline src/test/ui/typeck/issue-79040.stderr:2]: You should bless it :)

Comment (henryboisdequin) [reply src/test/ui/typeck/issue-79040.stderr:2]: Oh yeah, thanks for the reminder

**Comment by oli-obk** [comment]
Please run `./x.py test src/test/ui --bless` and `./x.py test src/tools/tidy` before pushing. These will allow you to quickly fix the problems locally instead of having to play ping-pong with CI

File: src/test/ui/parser/item-free-const-no-body-semantic-fail.rs [hunk 4]
```diff
@@ -3,5 +3,4 @@
 fn main() {}
 
 const A: u8; //~ ERROR free constant item without body
-const B; //~ ERROR free constant item without body
```
Comment (camelid) [inline src/test/ui/parser/item-free-const-no-body-semantic-fail.rs:6]: Was this `//~ ERROR` marker intentionally removed? I still see the error in the stderr.

File: src/test/ui/parser/item-free-static-no-body-semantic-fail.rs (hunk 1 above)
Comment (camelid) [reply src/test/ui/parser/item-free-static-no-body-semantic-fail.rs:10]: It still looks to me like you've removed the "free static item without body" label.

File: src/test/ui/parser/item-free-static-no-body-semantic-fail.rs [hunk 5]
```diff
@@ -3,9 +3,7 @@
 fn main() {}
 
 static A: u8; //~ ERROR free static item without body
-static B; //~ ERROR free static item without body
-//~^ ERROR missing type for `static` item
+static B; //~ ERROR missing type for `static` item
```
Comment (camelid) [inline src/test/ui/parser/item-free-static-no-body-semantic-fail.rs:6]: Same here.

File: compiler/rustc_typeck/src/collect/type_of.rs [hunk 6]
```diff
@@ -659,7 +659,7 @@ fn infer_placeholder_type(
                 format!("{}: {}", item_ident, ty),
                 Applicability::MachineApplicable,
             )
-            .emit();
+            .emit_unless(matches!(ty.kind(), ty::Error(_)));
```
Comment (estebank) [inline compiler/rustc_typeck/src/collect/type_of.rs:662]: I think we might want to check if `ty.references_error()` here and below in the `None` case instead. That way we account for things like `Option<[type error]>` as well.

File: compiler/rustc_typeck/src/collect/type_of.rs [hunk 7]
```diff
@@ -659,18 +659,28 @@ fn infer_placeholder_type(
...
+
+            if ty.references_error() {
+                // Account for cases such as `Option<[type error]>`
+                diag.span_suggestion(
+                    span,
+                    "provide a type for the item",
+                    format!("{}: {}", item_ident, ty),
+                    Applicability::MachineApplicable,
+                );
+            } else if !matches!(ty.kind(), ty::Error(_)) {
```
Comment (estebank) [inline compiler/rustc_typeck/src/collect/type_of.rs:675]: I think this can be

```suggestion
            if !ty.references_error() {
```

File: compiler/rustc_typeck/src/collect/type_of.rs [hunk 8]
```diff
@@ -659,18 +659,28 @@ fn infer_placeholder_type(
                 format!("{}: {}", item_ident, ty),
                 Applicability::MachineApplicable,
             )
-            .emit();
+            .emit_unless(matches!(ty.kind(), ty::Error(_)) || ty.references_error());
```
Comment (estebank) [inline compiler/rustc_typeck/src/collect/type_of.rs:662]:
```suggestion
            .emit_unless(ty.references_error());
```

If `let ty::Error(_) = ty.kind()`, then `ty.references_error()` would also be true, I think.

File: src/test/ui/typeck/typeck_type_placeholder_item.stderr [hunk 9]
```diff
@@ -603,7 +612,10 @@ error[E0121]: the type placeholder `_` is not allowed within types on item signa
   --> $DIR/typeck_type_placeholder_item.rs:205:14
    |
 LL |     const C: _;
-   |              ^ not allowed in type signatures
+   |              ^
+   |              |
+   |              not allowed in type signatures
+   |              help: provide a type for the item: `C: [type error]`
```
Comment (camelid) [inline src/test/ui/typeck/typeck_type_placeholder_item.stderr:618]: Perhaps you've already noticed this, but just want to note that this is a regression.

Comment (estebank) [reply src/test/ui/typeck/typeck_type_placeholder_item.stderr:618]: Looking at the code, I am not sure how these happened 🤔

Comment (henryboisdequin) [reply src/test/ui/typeck/typeck_type_placeholder_item.stderr]: It's because I didn't bless the tests 😅
