### PR TITLE
suggest adding space in accidental doc comments

### LINKED ISSUE #67553: When finding an invalid outer doc comment, suggest turning it into a comment
```
error: expected one of `.`, `;`, `?`, `}`, or an operator, found doc comment `//!self.allow_ty_infer()`
    --> src/librustc_typeck/astconv.rs:2461:21
     |
2460 |                     false
     |                          - expected one of `.`, `;`, `?`, `}`, or an operator
2461 |                     //!self.allow_ty_infer()
     |                     ^^^^^^^^^^^^^^^^^^^^^^^^ unexpected token
```

should be

```
error: expected one of `.`, `;`, `?`, `}`, or an operator, found doc comment `//!self.allow_ty_infer()`
    --> src/librustc_typeck/astconv.rs:2461:21
     |
2460 |                     false
     |                          - expected one of `.`, `;`, `?`, `}`, or an operator
2461 |                     //!self.allow_ty_infer()
     |                     ---^^^^^^^^^^^^^^^^^^^^^ unexpected token
     |                     |
     |                     help: if you wanted a regular comment, add a space before the exclamation mark: `// !`
```

### PR DESCRIPTION
**Pull request by euclio**
Fixes #67553.

r? @estebank

### CODE REVIEW

File: src/librustc_parse/parser/stmt.rs [hunk 1]
```diff
@@ -431,6 +431,23 @@ impl<'a> Parser<'a> {
...
+                                    sp.with_hi(sp.lo() + BytePos(marker.len() as u32)),
+                                    &format!(
+                                        "add a space before `{}` to use a regular comment",
+                                        doc_comment_marker,
+                                    ),
+                                    format!("{} {}", comment_marker, doc_comment_marker),
+                                    Applicability::MaybeIncorrect,
+                                );
+                            }
+                        }
```
Comment (Centril) [inline src/librustc_parse/parser/stmt.rs]: This new logic should imo be moved, including with some of the surroundings to a new method instead of having more recovery logic in the happy path.
