### PR TITLE
Account for macros when suggesting adding lifetime

### LINKED ISSUE #70152: use of undeclared lifetime emits incorrect help message
In case there is an undeclared lifetime in an ADT deriving `Eq` a wrong help message is emited
```rust
#[derive(Eq, PartialEq)]
struct Test {
    a: &'b str,
}
```
causes the following error

```
error[E0261]: use of undeclared lifetime name `'b`
 --> src/lib.rs:3:9
  |
2 | struct Test {
  |            - help: consider introducing lifetime `'b` here: `<'b>`
3 |     a: &'b str,
  |         ^^ undeclared lifetime

error[E0261]: use of undeclared lifetime name `'b`
 --> src/lib.rs:3:9
  |
3 |     a: &'b str,
  |         ^^ undeclared lifetime
  |
help: consider introducing lifetime `'b` here
  |
1 | #[derive(<'b>, PartialEq)]
  |          ^^^^
help: consider introducing lifetime `'b` here
  |
1 | #[derive(<'b>, PartialEq)]
  |          ^^^^
```

thx, bye

### PR DESCRIPTION
**Pull request by estebank**
Fix #70152.

### CODE REVIEW

File: compiler/rustc_resolve/src/late/diagnostics.rs [hunk 1]
```diff
@@ -1664,12 +1665,20 @@ impl<'tcx> LifetimeContext<'_, 'tcx> {
...
+                            span,
+                            &format!("consider introducing lifetime `{}` here", lifetime_ref),
+                            sugg,
+                            Applicability::MaybeIncorrect,
+                        );
+                    } else if suggest_note {
+                        suggest_note = false; // Avoid displaying the same help multiple times.
+                        err.help(&format!(
+                            "consider introducing lifetime `{}` to the item's generics",
+                            lifetime_ref,
```
Comment (lcnr) [inline compiler/rustc_resolve/src/late/diagnostics.rs:1679]: can you add a note here mentioning that we're inside of an expansion?

I think otherwise these two nearly identical error messages in the added test case might be confusing

Comment (estebank) [reply compiler/rustc_resolve/src/late/diagnostics.rs:1679]: What do you think about rewriting this to "lifetime `{}` is missing in an item created through a proc macro"?

Comment (estebank) [reply compiler/rustc_resolve/src/late/diagnostics.rs]: Check out the new output
