### PR TITLE
 Be more permissive with required bounds on existential types 

### LINKED ISSUE #54184: generic existential types should (at most) warn, not error, if a type parameter is unused
Consider the following code ([play](https://play.rust-lang.org/?gist=d57057ce3bab5ec0d9e28fc1e86cd6d6&version=nightly&mode=debug&edition=2015)): 

```rust
#![feature(existential_type)]

fn main() {
    let y = choose(vec![1, 2, 3, 4].into_iter());
    for (i, elem) in y.enumerate() {
        println!("processing y[{}]: {:?}", i, elem);
    }
}

existential type MaybeWrapped<I>: Iterator<Item = usize>;

fn choose<I: Iterator<Item = usize>>(x: I) -> MaybeWrapped<I> {
    // If you switch to variant below, it works.
    // return Wrapped(x);
    return x.collect::<Vec<usize>>().into_iter();
}

/// Trivial wrapper around an iterator.
struct Wrapped<I: Iterator>(I);
impl<I: Iterator> Iterator for Wrapped<I> {
    type Item = I::Item;
    fn next(&mut self) -> Option<I::Item> { self.0.next() }
}
```

The compiler errors, with the diagnostic

```
error[E0091]: type parameter `I` is unused
  --> src/main.rs:10:31
   |
10 | existential type MaybeWrapped<I>: Iterator<Item = usize>;
   |                               ^ unused type parameter

error: aborting due to previous error
```

But it should not be illegal to leave a type parameter unused. It is useful, from the view-point of the implementor, to have the option of returning concrete types that do not use the given type.

(Also, I find the diagnostic itself a bit less helpful than it could be; when I first read it, I thought it was complaining about not seeing `I` on the trait-bound in `existential type <NAME>: <TRAIT_BOUND>`; I needed @eddyb  to point out to me that the issue is in the body of `fn choose` itself.)

### PR DESCRIPTION
**Pull request by oli-obk**
fixes  #54184

r? @pnkfelix

### CODE REVIEW

File: src/test/ui/existential_types/generic_duplicate_param_use.rs [hunk 1]
```diff
@@ -1,8 +1,10 @@
+// compile-pass
 #![feature(existential_type)]
 
 fn main() {}
 
-existential type Two<T, U>: 'static; //~ ERROR type parameter `U` is unused
+// test that unused generic parameters are ok
+existential type Two<T, U>: 'static;
 
 fn one<T: 'static>(t: T) -> Two<T, T> {
```
Comment (cramertj) [inline src/test/ui/existential_types/generic_duplicate_param_use.rs]: Under the RFC, this function doesn't qualify as a defining use because multiple mappings from `Two<T, T>` to type `T` could exist. This is especially clear in this example, where (AFAICT) there's no reason that `U` is unused, but `T` isn't unused-- it could be that `T` is unused but `U` is used instead (i.e. `type Two<T, U> = T;` vs `type Two<T, U> = U;`).

In order for something to qualify as a defining use, all type parameters must be able to vary independently, e.g. `fn one<T, U>(..) -> Two<T, U>`. The rules for this are actually probably similar-ish to the ones that @nikomatsakis had in mind for "always applicable impls" for specialization.

File: src/test/ui/existential_types/generic_duplicate_param_use2.rs [hunk 2]
```diff
@@ -0,0 +1,15 @@
...
+fn main() {}
+
+// test that unused generic parameters are ok
+existential type Two<T, U>: 'static;
+
+fn one<T: 'static>(t: T) -> Two<T, T> {
+    t
+}
+
+fn two<T: 'static, U: 'static>(t: T, _: U) -> Two<T, U> {
```
Comment (cramertj) [inline src/test/ui/existential_types/generic_duplicate_param_use2.rs]: What happens if you write this same example, but change the return type of this function to `Two<U, T>`?

File: src/test/ui/existential_types/generic_duplicate_param_use4.rs [hunk 3]
```diff
@@ -0,0 +1,15 @@
...
+fn main() {}
+
+// test that unused generic parameters are ok
+existential type Two<T, U>: 'static;
+
+fn one<T: 'static>(t: T) -> Two<T, T> {
+    t
+}
+
+fn three<T: 'static, U: 'static>(_: T, u: U) -> Two<T, U> {
```
Comment (cramertj) [inline src/test/ui/existential_types/generic_duplicate_param_use4.rs]: Oh, nvm-- it looks like the test I asked for above is basically the same as this one. I think it's a bug that this function not be allowed but the example with `one`, `two` is-- there's no reason that the order of the type parameters in the `existential type` should affect the result.

Comment (oli-obk) [reply src/test/ui/existential_types/generic_duplicate_param_use4.rs]: Yea... I think my implementation of that algorithm may be very naive (which was ok as long as unused parameters were not allowed). I'll implement this properly

File: src/test/ui/existential_types/generic_duplicate_param_use.rs (hunk 1 above)
Comment (cramertj) [reply src/test/ui/existential_types/generic_duplicate_param_use.rs]: AFAICT it's not possible for this function to be a defining use and to anonymously agree with a separate function `fn t_first<T, U>(x: T) -> Two<T, U> { x }` *or* a separate function `fn t_second<T, U>(x: T) -> Two<U, T> { x }`. Obviously both can't exist at the same time, but *one* of them could exist and be a defining use, but just looking at `fn one<T>(t: T) -> Two<T, T> { t }` we don't know which should be allowed.

Comment (oli-obk) [reply src/test/ui/existential_types/generic_duplicate_param_use.rs]: I'm iterating over all the functions anyway, so I can implement an order-independent algorithm. The question is whether that should be done. It sure feels surprising

**Comment by oli-obk** [comment]
So... I was looking at the various examples and failed to come up with a good reason not to just outright treat any generic parameter equal to any other generic parameter, as long as all the other types match up. This basically boils down to

```rust
fn foo<T>() -> Foo<T, T> { ... }
fn bar<T, U>() -> Foo<T, U> { ... }
fn mep<U, T>() -> Foo<T, U> { ... }
```

all being defining uses as long as the concrete type they return has the same structure. So the following concrete return types are ok:

|        | foo         | bar            |        | foo         | bar                                             | meh                                             |
|--------|-------------|-------------------------------------------------|-------------------------------------------------|
| Vec    | Vec<T>      | Vec<T> Vec<U>                                   | Vec<T> Vec<U>                                   |
| T      | T           | T U                                             | T U                                             |
| tuple  | (T, T)      | (T, U) (U, T) (T, T) (U, U)                     | (T, U) (U, T) (T, T) (U, U)                     |
| tuple2 | (T, u32, T) | (T, u32, U) (U, u32, T) (T, u32, T) (U, u32, U) | (T, u32, U) (U, u32, T) (T, u32, T) (U, u32, U) |
                                    | meh                                                |
|--------|-------------|----------------------------------------------------|----------------------------------------------------|
| Vec    | Vec<T>      | Vec<T>, Vec<U>                                      | Vec<T>, Vec<U>                                      |
| T      | T           | T, U                                               | T, U                                               |
| tuple  | (T, T)      | (T, U), (U, T), (T, T), (U, U)                     | (T, U), (U, T), (T, T), (U, U)                     |
| tuple2 | (T, u32, T) | (T, u32, U), (U, u32, T), (T, u32, T), (U, u32, U) | (T, u32, U), (U, u32, T), (T, u32, T), (U, u32, U) |

**Comment by cramertj** [comment]
Talked at the all hands-- I'm still of the opinion that we can't allow defining uses which don't keep both type parameters as fully universal:

```rust
existential type X<A, B>;

fn foo<A>(a: A) -> X<A, u32> {
    (a, 5u32)
}
```
This could force the concrete type to be X<A,B> = (A, B), or it could be X<A, B> = (A, u32), we don't know which one it is (it could also be something like X<A, B> = (A, <A as SomeTrait>::Output))

**Comment by oli-obk** [comment]
So... we've come full circle. We are now again requiring defining uses to use all the generic parameters of the existential type in the concrete type.

**Comment by cramertj** [comment]
I'm a bit confused by the latest error. It's fine to *not use* the generic parameter in the concrete type, but each generic parameter has to be left fully variant in the type signature of the function that includes the defining use. The example you added unambiguously (afaict) does not use type `U`, which is fine. The thing that wouldn't be fine would be if it is *unclear* whether or not it uses `U`.

**Comment by oli-obk** [comment]
Yea that was a brain-afk moment for me. I cleaned it up and it makes much more sense now (and still fixes the original issue that caused this PR)

Right now we are erroring on all potential defining uses that end up not being a defining use. As a next step (separate from this PR), we can instead collect all the potential sites and add them as notes to the "no defining use" error. If a single defining use site exists, we don't need to emit an error for the potential use sites (except if their concrete types conflict with the defining use sites)

**Comment by cramertj** [comment]
Nice, this looks good to me! Thanks for the fixes :)

@bors r+

**Comment by RalfJung** [comment]
Same macOS failure as in other PRs...

Cc @rust-lang/infra

**Comment by kennytm** [comment]
@bors retry 

3 hour timeout 🤔

File: src/librustc_typeck/collect.rs [hunk 4]
```diff
@@ -1340,23 +1347,106 @@ fn find_existential_constraints<'a, 'tcx>(
...
+                    );
+                } else if let Some((prev_span, prev_ty, ref prev_indices)) = self.found {
+                    let mut ty = concrete_type.walk().fuse();
+                    let mut p_ty = prev_ty.walk().fuse();
+                    let iter_eq = (&mut ty).zip(&mut p_ty).all(|(t, p)| match (&t.sty, &p.sty) {
+                        // type parameters are equal to any other type parameter for the purpose of
+                        // concrete type equality, as it is possible to obtain the same type just
+                        // by passing matching parameters to a function.
+                        (ty::Param(_), ty::Param(_)) => true,
+                        _ => t == p,
```
Comment (eddyb) [inline src/librustc_typeck/collect.rs]: I'm suspicious of this entire approach. Only the outermost type could be a differing `ty::Param`s, anything *containing* `ty::Param` would automatically hit `t == p` being `false`.

There are two ways to compare types deeply, and they're:
1. exact equality (which, with the right substitutions, can be reached for types coming from different contexts)
2. unification (`ty::relate` or full-on inference, which uses the former) - this is how e.g. `impl` matching works in the current trait system

"Walking" a type is a *not* a good way to achieve almost anything, the main legitimate usecase I've found is gathering leaves of some kind (e.g. `ty::Infer(_)`) or searching for a specific type.

File: src/librustc_typeck/collect.rs [hunk 5]
```diff
@@ -1340,23 +1347,106 @@ fn find_existential_constraints<'a, 'tcx>(
...
+                }
+                // compute the index within the existential type for each generic parameter used in
+                // the concrete type
+                let indices = concrete_type
+                    .subst(self.tcx, substs)
+                    .walk()
+                    .filter_map(|t| match &t.sty {
+                        ty::Param(p) => Some(*index_map.get(p).unwrap()),
+                        _ => None,
+                    }).collect();
```
Comment (eddyb) [inline src/librustc_typeck/collect.rs]: Trying to understand what this does, we have these facts:
1. `concrete_type`, in the "generics domain" of the opaque type
2. `concrete_type.subst(self.tcx, substs)`, in the "generics domain" of the definer
3. `substs` are required to be a 1:1 mapping from the opaque type to the definer
  * this implies `index_map` is the *exact inverse* of `substs`

All that means `indices` could be computed so:
```rust
                let indices = concrete_type
                    .walk()
                    .filter_map(|t| match &t.sty {
                        ty::Param(p) => Some(p.index),
                        _ => None,
                    }).collect();
```

If `indices` have to agree between definers, that means `concrete_type`s *are fully equal*.

Am I missing something? This entire PR, other than checking `substs`, looks like a noop.

I'll attempt a revert of the parts that look like a noop, and generalize to handle `const` generics (if this is even the right place to do so).

File: src/librustc/ty/context.rs [hunk 6]
```diff
@@ -315,6 +315,17 @@ impl<'a, V> LocalTableInContextMut<'a, V> {
...
 
+/// All information necessary to validate and reveal an `impl Trait` or `existential Type`
+#[derive(RustcEncodable, RustcDecodable, Debug)]
+pub struct ResolvedOpaqueTy<'tcx> {
+    /// The revealed type as seen by this function.
+    pub concrete_type: Ty<'tcx>,
+    /// Generic parameters on the opaque type as passed by this function.
+    /// For `existential type Foo<A, B>; fn foo<T, U>() -> Foo<T, U> { .. }` this is `[T, U]`, not
+    /// `[A, B]`
+    pub substs: &'tcx Substs<'tcx>,
```
Comment (eddyb) [inline src/librustc/ty/context.rs]: Hang on, isn't substs checking handled by `wfcheck`? https://github.com/rust-lang/rust/blob/5574b1df577f737373b42cbf364b6cab2dfa5960/src/librustc_typeck/check/wfcheck.rs#L818-L837

Wouldn't that make `ResolvedOpaqueTy` and most of this PR entirely redundant, if params were checked there?

Comment (eddyb) [reply src/librustc/ty/context.rs]: Hmm, I can't remove `ResolvedOpaqueTy` as it seems MIR borrowck needs the `Substs`, and I'd rather not touch that code if I can help it.

File: src/librustc_typeck/collect.rs (hunk 5 above)
Comment (eddyb) [reply src/librustc_typeck/collect.rs]: Opened #70272.
