### PR TITLE
Compute LLVM-agnostic type layouts in rustc.

### LINKED ISSUE #32377: Unexpected tail in unsized_info_ty: usize for ty=process::Core<isize, isize, isize>
Hi,
compiling the eventual crate with the latest rust nightly (2016-03-20) gives me the following ICE. The previous nightly (2016-03-17) worked fine.
```
$ RUST_BACKTRACE=1 multirust run nightly cargo build
Compiling eventual v0.1.5 (file:///private/tmp/eventual)
error: internal compiler error: unexpected panic
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
thread 'rustc' panicked at 'internal error: entered unreachable code: Unexpected tail in unsized_info_ty: usize for ty=process::Core<isize, isize, isize>', ../src/librustc_trans/trans/type_of.rs:135
stack backtrace:
   1:        0x11312af38 - sys::backtrace::tracing::imp::write::h83bc1946ac132a7d0Gu
   2:        0x113134475 - panicking::default_hook::_$u7b$$u7b$closure$u7d$$u7d$::closure.43767
   3:        0x113133fd7 - panicking::default_hook::had684d056a84b05cPgz
   4:        0x1130fb336 - sys_common::unwind::begin_unwind_inner::hfef527c9f2434064HGt
   5:        0x1130fcf4e - sys_common::unwind::begin_unwind_fmt::h02d40e945b8e457cNFt
   6:        0x10f01d7fa - trans::type_of::unsized_info_ty::h2e7677e19516a63dYwS
   7:        0x10eee2abe - trans::type_of::sizing_type_of::h7b00ca8fada013b0roS
   8:        0x10ef39726 - trans::base::trans_crate::h389b5fe1abf2545ch3k
   9:        0x10ec74e6e - driver::phase_4_translate_to_llvm::h9c2dd5a6e3ca512cK2a
  10:        0x10ec73774 - driver::compile_input::_$u7b$$u7b$closure$u7d$$u7d$::closure.31089
  11:        0x10ec70425 - driver::phase_3_run_analysis_passes::_$u7b$$u7b$closure$u7d$$u7d$::closure.30095
  12:        0x10ec6a3e9 - middle::ty::context::TyCtxt<'tcx>::create_and_enter::h11812805895441873020
  13:        0x10ec66dad - driver::phase_3_run_analysis_passes::h5261001332275006052
  14:        0x10ec39df7 - driver::compile_input::he5def18759d9424cPca
  15:        0x10ec276f6 - run_compiler::h61ff55f691b932efVMc
  16:        0x10ec24ca2 - sys_common::unwind::try::try_fn::h2984156204492186173
  17:        0x11312879b - __rust_try
  18:        0x113128723 - sys_common::unwind::inner_try::hbef67b929e699248JDt
  19:        0x10ec25539 - boxed::F.FnBox<A>::call_box::h8793623295134616532
  20:        0x1131332c8 - sys::thread::Thread::new::thread_start::h68477ad6a3ba8036fvy
  21:     0x7fff8fb6b9b0 - _pthread_body
  22:     0x7fff8fb6b92d - _pthread_start

error: Could not compile `eventual`.

To learn more, run the command again with --verbose.
```

EDIT: I had copied the rust nightly versions incorrectly

### PR DESCRIPTION
**Pull request by eddyb**
Layout for monomorphic types, and some polymorphic ones (e.g. `&T` where `T: Sized`),
can now be computed by rustc without involving LLVM in the actual process.

This gives rustc the ability to evaluate `size_of` or `align_of`, as well as obtain field offsets.
MIR-based CTFE will eventually make use of these layouts, as will MIR trans, shortly.

Layout computation also comes with a `[breaking-change]`, or two:
- `"data-layout"` is now mandatory in custom target specifications, reverting the decision from #27076.
  This string is needed because it describes endianness, pointer size and alignments for various types.
  We have the first two and we could allow tweaking alignments in target specifications.
  Or we could also extract the data layout from LLVM and feed it back into rustc.
  However, that can vary with the LLVM version, which is fragile and undermines stability.
  For built-in targets, I've added a check that the hardcoded data-layout matches LLVM defaults.
- `transmute` calls are checked in a stricter fashion, which fixes #32377

To expand on `transmute`, there are only 2 allowed patterns: between types with statically known sizes and between pointers with the same potentially-unsized "tail" (which determines the type of unsized metadata they use, if any).
If you're affected, my suggestions are:
- try to use casts (and raw pointer deref) instead of transmutes
- _really_ try to avoid `transmute` where possible
- if you have a structure, try working on individual fields and unpack/repack the structure instead of transmuting it whole, e.g. `transmute::<RefCell<Box<T>>, RefCell<*mut T>>(x)` doesn't work, but `RefCell::new(Box::into_raw(x.into_inner()))` does (and `Box::into_raw` is just a `transmute`)

### CODE REVIEW

File: src/librustc/ty/layout.rs [hunk 1]
```diff
@@ -0,0 +1,1154 @@
...
+            }
+            ty::TyStr => {
+                Array {
+                    sized: false,
+                    align: dl.i8_align,
+                    size: Size::from_bytes(0)
+                }
+            }
+
+            // Odd unit types.
```
Comment (arielb1) [inline src/librustc/ty/layout.rs]: No `Layout::Unit`? Also `Layout::Empty` might be nice.

Comment (eddyb) [inline src/librustc/ty/layout.rs]: I don't really see the need for a dedicated unit layout, but `Layout::Empty` would probably be useful in refining the set of variants, to make `sizeof(Result<T, Void>)` just `sizeof(T)`.

*However*, just like invalid value range reusal (i.e. extending non-zero optimizations), it cannot be done before moving trans to use only `ty::Layout`.

I was hoping we can test the worst-case transmute approach before the beta, but there were complications I had to address.

File: src/librustc/ty/layout.rs [hunk 2]
```diff
@@ -0,0 +1,245 @@
...
+    pub pointer_size: Size,
+    pub pointer_align: Align,
+    pub aggregate_align: Align,
+
+    /// Alignments for vector types, sorted by size.
+    pub vector_align: Vec<(Size, Align)>
+}
+
+impl Default for TargetDataLayout {
+    fn default() -> TargetDataLayout {
```
Comment (tsion) [inline src/librustc/ty/layout.rs]: @eddyb How were these defaults chosen? When do they get used?

**Comment by alexcrichton** [comment]
My main worry on these data layouts was just that no one actually understands them and they're just opaque blobs we copy around without any thought, and then once that caused a bug one day and LLVM had reasonable defaults for everything it seemed "why not just use that?"

If we validate that our data layout is the same as LLVM, however, then this seems fine to me. I'd be curious if LLVM actually changes anything here between releases (wouldn't that be a huge breaking change for C as well?), but doing this ourselves also seems fine to me.

**Comment by tsion** [comment]
This PR will be a big help for implementing [Miri](https://github.com/tsion/miri) more properly, which hopefully will lead to MIR-based CTFE as @eddyb mentioned in the description.

In general, I think it's a good idea to make rustc less dependent on LLVM where it isn't too difficult to do so.

File: src/librustc/ty/layout.rs (hunk 2 above)
Comment (eddyb) [inline src/librustc/ty/layout.rs]: They're LLVM's defaults: http://llvm.org/docs/LangRef.html#data-layout.

Comment (Aatch) [inline src/librustc/ty/layout.rs]: Looks like the defaults match LLVMs defaults for the data layout string. The data layout string isn't required to specify every value, so the defaults are used to fill in the gaps.

Comment (tsion) [inline src/librustc/ty/layout.rs]: That makes sense, thanks.

**Comment by eddyb** [comment]
@alexcrichton They're documented, though: http://llvm.org/docs/LangRef.html#data-layout.
Also, they used to be much more verbose for redundancy's sake, but they're manageably small now.
The bug you mention was precisely my point: if we get the datalayout from LLVM and there's a bug fix, we don't get notified.

**Comment by eddyb** [comment]
I've taken a look at the [preliminary list of regressions](https://gist.github.com/nikomatsakis/8c366ca2d05ec84aff135fb10c0259ec), and even though almost half of them were build failures (timeouts?), the rest displayed a clear pattern:
* in `postgres-binary-copy-0.2.1` `Option<&'a T>` is transmuted to `Option<&'b T>` - we could try to accommodate for this by comparing the two types, with regions substituted away - or handle `Option<&T>` like `*const T` (see below)
* everywhere else, the errors come from a transmute between two pointer types, some of which are wrapped in newtypes, *both* potentially-fat with the exact same "tail", which is a type parameter

That is, in the latter case, you might have `&T` -> `Rc<RefCell<T>>` with `T: ?Sized` (not that you could make use of that, but it's an extreme example), and both of those types are potentially-fat pointers with the same metadata, depending only on `T`, now and in the future.

Assuming we want to allow the pattern of casting between maybe-newtyped pointers to maybe-unsized maybe-wrapped type parameters, how should we go about doing it?

The cleanest solution I have in mind, although not the most principled one, is to have two checks:
* first, we try to obtain static sizes for the source and destination and compare them
* if that fails, we attempt to extract potentially-unsized "pointer skeletons" from both types, and compare the pointee "tail" type; this technique also allows transmutes between pointers to `?Sized` associated types

While it may be possible to integrate unknown sizes into the regular `Layout` to get a more principled(?) solution, it would complicate any code working with layouts in monomorphic code.

**Comment by Aatch** [comment]
> * in `postgres-binary-copy-0.2.1` `Option<&'a T>` is transmuted to `Option<&'b T>` - we could try to accommodate for this by comparing the two types, with regions substituted away - or handle `Option<&T>` like `*const T` (see below)

I think regions should be ignored/substituted here. Makes more general sense, since the regions shouldn't affect the layout of the type.

**Comment by nikomatsakis** [comment]
@eddyb 

> Assuming we want to allow the pattern of casting between maybe-newtyped pointers to maybe-unsized maybe-wrapped type parameters, how should we go about doing it?

I think we do.

> While it may be possible to integrate unknown sizes into the regular Layout to get a more principled(?) solution, it would complicate any code working with layouts in monomorphic code.

I don't have an informed enough opinion yet. I'll try to take a look at your code but it may not happen until Monday, since I'm kind of busy today with other (non-Rust-related) things. But it *seems* to me like we could probably use a similar trick to what we do today, where for things where `T: ?Sized` we compute the layout multiple times, under different assumptions (T is definitely sized, T is definitely unsized, etc). But maybe your suggestion turns out nicer -- it just seems like it may wind up duplicating some layout logic. But perhaps not.

**Comment by nikomatsakis** [comment]
> in postgres-binary-copy-0.2.1 Option<&'a T> is transmuted to Option<&'b T> - we could try to accommodate for this by comparing the two types, with regions substituted away - or handle Option<&T> like *const T (see below)

Oh, and clearly regions shouldn't affect the result, but I would expect this equivalency to fallout in a more general way than strict type equality?

**Comment by eddyb** [comment]
@nikomatsakis Just trying out combinations is fragile, IMO. if we ever want to add more kinds of fat pointer metadata (or if we make it fully custom).

IMO the perfect solution is to enforce static sizes because that would allow a `size_of::<T>() == size_of::<U>()` bound on `transmute` in the future, but I am open to non-static, yet strict, solutions.

That's because we could end up simplifying, e.g. `size_of::<*mut T>() == size_of::<Option<&T>>()` to `true` based on the "pointer skeleton" rule mentioned above.

**Comment by nikomatsakis** [comment]
@eddyb 

> Just trying out combinations is pretty fragile, if we ever want to add more kinds of fat pointer metadata (or if we make it fully custom).

I see. Good point.

File: src/librustc/ty/layout.rs [hunk 3]
```diff
@@ -151,9 +189,9 @@ pub enum Endian {
 }
 
 /// Size of a type in bytes.
-#[derive(Copy, Clone, PartialEq, Eq, PartialOrd, Ord)]
+#[derive(Copy, Clone, PartialEq, Eq, PartialOrd, Ord, Hash, Debug)]
 pub struct Size {
-    raw: u64
+    pub bytes: u64
```
Comment (nikomatsakis) [inline src/librustc/ty/layout.rs]: I don't really care, but I imagine the use of privacy here was to help ensure people don't do stupid things like `let mut size = ...; size.bytes *= 2;`, but rather encourage them to go through these (presumably more careful) APIs.

Comment (eddyb) [inline src/librustc/ty/layout.rs]: I actually initially wanted to use the highest bit to indicate that the rest of the size is the base size of an unsized type, instead of an exact size, but I ended up dealing with unsized types differently.
I could go back to private `raw` and add more checks for 2^61 overflow if you want to.

**Comment by eddyb** [comment]
@alexcrichton I've added that "data-layout matches default" check to make sure we don't get caught by surprise again.

@nikomatsakis I went with the "skeleton" computation approach, and it does work on the testcases we have, which include the regression scenarios. Also included a testcase for #32377.
Mind giving it another spin on crater?

**Comment by alexcrichton** [comment]
> I've added that "data-layout matches default" check to make sure we don't get caught by surprise again.

Awesome, thanks!

File: src/librustc/ty/layout.rs [hunk 4]
```diff
@@ -1199,3 +1199,138 @@ impl Layout {
...
+                        bug!("SizeSkeleton::compute({}): layout errored ({}), yet \
+                              tail `{}` is not a type parameter or a projection",
+                             ty, err, tail)
+                    }
+                }
+            }
+
+            ty::TyStruct(def, substs) | ty::TyEnum(def, substs) => {
+                // Only newtypes and enums w/ nullable pointer optimization.
+                if def.variants.is_empty() || def.variants.len() > 2 {
```
Comment (nikomatsakis) [inline src/librustc/ty/layout.rs]: why not `def.variants.len() != 1`

Comment (nikomatsakis) [inline src/librustc/ty/layout.rs]: oh, nm.

File: src/librustc/ty/layout.rs [hunk 5]
```diff
@@ -1199,3 +1199,138 @@ impl Layout {
...
+                // Newtype.
+                if def.variants.len() == 1 {
+                    if let Some(SizeSkeleton::Pointer { non_zero, tail }) = v0 {
+                        return Ok(SizeSkeleton::Pointer {
+                            non_zero: non_zero ||
+                                Some(def.did) == tcx.lang_items.non_zero(),
+                            tail: tail
+                        });
+                    } else {
+                        return Err(err);
```
Comment (nikomatsakis) [inline src/librustc/ty/layout.rs]: Can this case even happen? This error case seems to mean that all fields were known to have size 0, in which case the entire struct has a known size, right?

File: src/librustc/ty/layout.rs [hunk 6]
```diff
@@ -1199,3 +1199,138 @@ impl Layout {
...
+                }
+            }
+
+            _ => Err(err)
+        }
+    }
+
+    pub fn same_size(self, other: SizeSkeleton) -> bool {
+        match (self, other) {
+            (SizeSkeleton::Known(a), SizeSkeleton::Known(b)) => a == b,
```
Comment (nikomatsakis) [inline src/librustc/ty/layout.rs]: To be more precise, we would want to check for some kind of "is-sized-if" predicate: i.e., a and b do not have to be the same, but a must be sized iff b is sized.

Comment (nikomatsakis) [inline src/librustc/ty/layout.rs]: Right? :)

File: src/librustc/ty/layout.rs (hunk 5 above)
Comment (eddyb) [inline src/librustc/ty/layout.rs]: Correct, do you think `bug!` is better here?

File: src/librustc/ty/layout.rs (hunk 6 above)
Comment (eddyb) [inline src/librustc/ty/layout.rs]: I'm not sure I understand. This function is pretty much `==` except for ignoring the `non_zero` in `SizeSkeleton::Pointer`.

Comment (nikomatsakis) [inline src/librustc/ty/layout.rs]: @eddyb I am imagining a comparison between something like `*mut T` and `*mut Foo<T>` where `struct Foo { t: T }`. I think this code would yield false now, but in fact such a thing is reasonable?

**Comment by nikomatsakis** [comment]
Started a crater run.

File: src/librustc/ty/layout.rs (hunk 6 above)
Comment (eddyb) [inline src/librustc/ty/layout.rs]: It compares the "tails" which are both `T`.

**Comment by nikomatsakis** [comment]
@eddyb https://gist.github.com/nikomatsakis/691c11ef264f26a05f394dfdd1272c56 shows:

* 4646 crates tested: 3180 working / 1410 broken / **0 regressed** / **3 fixed** / 53 unknown.

Nice job!

File: src/librustc/diagnostics.rs [hunk 7]
```diff
@@ -1410,6 +1410,32 @@ It is not possible to use stability attributes outside of the standard library.
 Also, for now, it is not possible to write deprecation messages either.
 "##,
 
+E0512: r##"
```
Comment (GuillaumeGomez) [inline src/librustc/diagnostics.rs]: Oh nice! Thanks for adding it! \o/

Comment (eddyb) [inline src/librustc/diagnostics.rs]: I only moved it.

**Comment by eddyb** [comment]
Nominated for backporting to beta because of #32377.

File: src/librustc/ty/layout.rs [hunk 8]
```diff
@@ -0,0 +1,1336 @@
...
+            }
+            LayoutError::SizeOverflow(ty) => {
+                write!(f, "the type `{:?}` is too big for the current architecture", ty)
+            }
+        }
+    }
+}
+
+/// Helper function for normalizing associated types in an inference context.
+fn normalize_associated_type<'a, 'tcx>(infcx: &InferCtxt<'a, 'tcx>,
```
Comment (tsion) [inline src/librustc/ty/layout.rs]: @eddyb In Miri I use `rustc::infer::normalize_associated_type`. Its source code is slightly different and has a warning about only being callable from trans, but *most* of it is duplicated so it seems a bit ugly. Could they be unified somehow?

Comment (eddyb) [inline src/librustc/ty/layout.rs]: See how I call `ty.layout(&infcx)` from trans. The effect is the same in that case, it's only different elsewhere (intrinsicck).

**Comment by pnkfelix** [comment]
after a week of exercising in the nightly release, the compiler team has decided to accept this for beta, largely because it fixes a real regression (#32377), and that outweighed the relative risk of backporting such a largish change to beta.
