### PR TITLE
Fix ABI flags in RISC-V/LoongArch ELF file generated by rustc

### LINKED ISSUE #114153: Use of RiscV "+forced-atomics" target feature triggers hard-float ABI for symbols.o
When building for RiscV-32, adding the "+forced-atomics" target feature (in this case, adding it to a custom target .json file)  causes the symbols.o file to be built with the single-float ABI rather than the soft-float ABI used for the all .rcgu.o files, which causes the link to fail due to incompatible float ABIs.

It appears to be due to this code in compiler/rustc_codegen_ssa/src/back/metadata.rs:

```
        Architecture::Riscv32 | Architecture::Riscv64 => {
            // Source: https://github.com/riscv-non-isa/riscv-elf-psabi-doc/blob/079772828bd10933d34121117a222b4cc0ee2200/riscv-elf.adoc
            let mut e_flags: u32 = 0x0;
            let features = &sess.target.options.features;
            // Check if compressed is enabled
            if features.contains("+c") {
                e_flags |= elf::EF_RISCV_RVC;
            }

            // Select the appropriate floating-point ABI
            if features.contains("+d") {
                e_flags |= elf::EF_RISCV_FLOAT_ABI_DOUBLE;
            } else if features.contains("+f") {
                e_flags |= elf::EF_RISCV_FLOAT_ABI_SINGLE;
            } else {
                e_flags |= elf::EF_RISCV_FLOAT_ABI_SOFT;
            }
            e_flags
        }
```
which assumes that any feature *beginning* with "+f" is in fact *exactly* "+f", so the addition of "+forced-atomics" triggers the single-float ABI.

Should this check (and most other feature checks) actually be something like: `features.split(",").any(|f| f == "+f")` (probably useful as a TargetOptions::has_feature() helper method)?

### PR DESCRIPTION
**Pull request by nbdd0121**
Fix #114153

It turns out the current way to set these flags are completely wrong. In LLVM the target ABI is used instead of target features to determine these flags.

Not sure how to write a test though. Or maybe a test isn't necessary because this affects only those touching target json?

r? @Nilstrieb

### CODE REVIEW

File: compiler/rustc_codegen_ssa/src/back/metadata.rs [hunk 1]
```diff
@@ -271,35 +272,37 @@ pub(crate) fn create_object_file(sess: &Session) -> Option<write::Object<'static
         Architecture::Riscv32 | Architecture::Riscv64 => {
             // Source: https://github.com/riscv-non-isa/riscv-elf-psabi-doc/blob/079772828bd10933d34121117a222b4cc0ee2200/riscv-elf.adoc
             let mut e_flags: u32 = 0x0;
-            let features = &sess.target.options.features;
+
             // Check if compressed is enabled
-            if features.contains("+c") {
+            if sess.unstable_target_features.contains(&sym::c) {
```
Comment (Nilstrieb) [inline compiler/rustc_codegen_ssa/src/back/metadata.rs:277]: I'm not sure whether looking at the `unstable_target_features` is correct here.

Actually, I don't understand that field at all. Previously, the only usage of it seems to be when deciding on the feature available inside an inline asm context. But I also see other inline asm related code using `sess.target_features` normally. Unstable features also seem especially unfortunate because they're silently discarded from `sess.target_features` on stable compilers, but that's besides the point.

The changes below look good to me though.

Comment (nbdd0121) [reply compiler/rustc_codegen_ssa/src/back/metadata.rs:277]: But wouldn't `target_features` mean that "+c" is silently ignored in non-nightly compilers?  

TBH the whole `target_features` unstable computation thing is puzzling to me.

Comment (Nilstrieb) [reply compiler/rustc_codegen_ssa/src/back/metadata.rs:277]: > But wouldn't target_features mean that "+c" is silently ignored in non-nightly compilers?

well, it is unstable according to the list so that's "correct behavior" (but pretty stupid behavior)

> TBH the whole target_features unstable computation thing is puzzling to me.

same.

so given that `+c` used to work on stable already I'm fine with keeping `unstable_target_features` here. Can you at least add a comment saying that using `unstable_target_features` was chosen because it used to work on stable?

pinging @Amanieu because maybe you have an idea: What exactly is the deal with unstable target features? They're silently ignored on stable which is pretty odd and also in one place they're actually used on stable.

Comment (nbdd0121) [reply compiler/rustc_codegen_ssa/src/back/metadata.rs:277]: The "unstable features" still gets passed to LLVM (well, actually, it's the other way around, they are worked out from LLVM in the first place).

File: tests/ui/or-patterns/missing-bindings.stderr [hunk 2]
```diff
@@ -79,6 +79,14 @@ LL |     let (A(A(..) | B(a), _) | B(A(a, _) | B(a))) = Y;
    |            |
    |            pattern doesn't bind `a`
 
+error[E0408]: variable `c` is not bound in all patterns
```
Comment (Nilstrieb) [inline tests/ui/or-patterns/missing-bindings.stderr:82]: what happened here... I assume this is related to adding `c` as a known symbol???
Yeah, I renamed `c` to `builtin_syntax` and the error changed in nightly. Looks like it's sorting the symbols by their index? That's strange and bad, but luckily not your problem.

**Review by Noratrieb — APPROVED** [review]

File: tests/ui/or-patterns/missing-bindings.stderr (hunk 2 above)
Comment (Nilstrieb) [reply tests/ui/or-patterns/missing-bindings.stderr:82]: yeah I see, I'll fix it

Comment (Nilstrieb) [reply tests/ui/or-patterns/missing-bindings.stderr:82]: #114454

**Comment by nbdd0121** [comment]
Some of the RISC-V targets don't have llvm_abiname set explicitly. I now default unset llvm_abiname to be the same as ilp32/lp64, i.e. not using hardware floating point.

**Comment by Nilstrieb** [comment]
sorry for the late response, I've been away
r? compiler

**Review by compiler-errors — APPROVED** [review]
