### PR TITLE
sugg: take into count the debug formatting

### LINKED ISSUE #100648: named_arguments_used_positionally suggestion does not take into account debug displaying
The suggestion that rustc gives is incorrect and seems to not take into account what characters are in the format argument.
I tried this code:

```rust
println!("hello {:?}", world = "world");
```

I expected to see this happen: 
```
  |
2 |     println!("hello {:?}", world = "world");
  |                     ----   ^^^^^ this named argument is referred to by position in formatting string
  |                     |
  |                     this formatting argument uses named argument `world` by position
  |
  = note: `#[warn(named_arguments_used_positionally)]` on by default
help: use the named argument by name to avoid ambiguity
  |
2 |     println!("hello {world:?}", world = "world");
  |                      ~~~~~
```

Instead, this happened: 
```
  |
2 |     println!("hello {:?}", world = "world");
  |                     ----   ^^^^^ this named argument is referred to by position in formatting string
  |                     |
  |                     this formatting argument uses named argument `world` by position
  |
  = note: `#[warn(named_arguments_used_positionally)]` on by default
help: use the named argument by name to avoid ambiguity
  |
2 |     println!("hello {world}", world = "world");
  |                      ~~~~~
```
### Meta
Using beta.2/nightly

`rustc --version --verbose`:
```
rustc 1.65.0-nightly (40336865f 2022-08-15)
binary: rustc
commit-hash: 40336865fe7d4a01139a3336639c6971647e885c
commit-date: 2022-08-15
host: x86_64-unknown-linux-gnu
release: 1.65.0-nightly
LLVM version: 15.0.0
```

### PR DESCRIPTION
**Pull request by vincenzopalazzo**
Closes https://github.com/rust-lang/rust/issues/100648

This PR will fix a suggestion error by taking into consideration also the `:?` symbol and act in a different way

@rustbot r? @compiler-errors

N.B: I did not find a full way to test the change, any idea?

### CODE REVIEW

File: compiler/rustc_lint/src/context.rs [hunk 1]
```diff
@@ -865,9 +865,15 @@ pub trait LintContext: Sized {
 
                     if let Some(positional_arg_to_replace) = position_sp_to_replace {
                         let name = if is_formatting_arg { named_arg_name + "$" } else { named_arg_name };
-
+                        let span_to_replace = if let Ok(positional_arg_content) = self.sess().source_map().span_to_snippet(positional_arg_to_replace) {
+                            if positional_arg_content.contains(":?") {
```
Comment (TaKO8Ki) [inline compiler/rustc_lint/src/context.rs:869]: We also need to take into account something like `:#?`.

https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=1f095b3602a2b95d8637b47aa357fc5b

Comment (vincenzopalazzo) [reply compiler/rustc_lint/src/context.rs:869]: Ah! right! maybe we should check if a string start `:` and end `?` sounds like a regex job?

Comment (TaKO8Ki) [reply compiler/rustc_lint/src/context.rs:869]: I think just checking if `positional_arg_content` starts with `:` can solve this problem. Ideally, we should improve `PositionalNamedArg::get_positional_arg_spans` so that it returns appropriate `position_sp_to_replace` by improving `has_formatting` field of `PositionalNamedArg`, but I think there is no need to do this much.

https://github.com/rust-lang/rust/blob/a8a33cf27166d3eabaffc58ed3799e054af3b0c6/compiler/rustc_builtin_macros/src/format.rs#L68-L101

Comment (vincenzopalazzo) [reply compiler/rustc_lint/src/context.rs]: I think that we can open an issue and move this to another task? I think your solution is the better one to improve the code, and remove some if else.

Comment (vincenzopalazzo) [reply compiler/rustc_lint/src/context.rs]: Tracking here https://github.com/rust-lang/rust/issues/100891 I will give the love that it needed in a new PR

Comment (TaKO8Ki) [reply compiler/rustc_lint/src/context.rs]: Thank you!

File: compiler/rustc_lint/src/context.rs [hunk 2]
```diff
@@ -865,9 +865,15 @@ pub trait LintContext: Sized {
 
                     if let Some(positional_arg_to_replace) = position_sp_to_replace {
                         let name = if is_formatting_arg { named_arg_name + "$" } else { named_arg_name };
-
+                        let span_to_replace = if let Ok(positional_arg_content) = self.sess().source_map().span_to_snippet(positional_arg_to_replace) {
+                            if positional_arg_content.starts_with(":") {
```
Comment (TaKO8Ki) [inline compiler/rustc_lint/src/context.rs:869]: Could you use let-chains?
```suggestion
                        let span_to_replace = if let Ok(positional_arg_content) = self.sess().source_map().span_to_snippet(positional_arg_to_replace)
                        && positional_arg_content.starts_with(":") {
```

**Comment by TaKO8Ki** [comment]
I left a comment. r=me after it is addressed

**Comment by TaKO8Ki** [comment]
Thank you! @bors r+ rollup
