### PR TITLE
Revisit fix_is_ci_llvm_available logic

### LINKED ISSUE #107225: bootstrap: `download-ci-llvm = "if-available"` tries to download alt artifacts that don't exist on tier 2 platforms
Since there is no `-alt` variation of CI action for [dist-aarch64-apple](https://github.com/rust-lang/rust/blob/master/src/ci/github-actions/ci.yml#L541), prebuilt llvm is never published for arm macs.
Hence compete bootstrap like `> ./x.py build library` will always fail on arm macs with
> Copying stage0 library from stage0 (aarch64-apple-darwin -> aarch64-apple-darwin / aarch64-apple-darwin)
downloading https://ci-artifacts.rust-lang.org/rustc-builds-alt/<commit-hash\>/rust-dev-nightly-aarch64-apple-darwin.tar.xz
curl: (22) The requested URL returned error: 404
error: failed to download llvm from ci

    help: old builds get deleted after a certain time
    help: if trying to compile an old commit of rustc, disable `download-ci-llvm` in config.toml:

    [llvm]
    download-ci-llvm = false

Although it's straightforward to fix by following the hint from error message and finding correct `config.codegen.toml` (among other config.toml's), bootstrap experience could be better:
1. `Config::download_ci_llvm()` could point to correct config file, since there are really few of them;
2. `Config::llvm_from_ci` could be set to `false` for those host triplets that have no published llvm;
3. Prebuilt llvm could be published for `dist-aarch64-apple` ie creating `dist-aarch64-apple-alt` CI action;
4. Notion of fallback distros could be introduced ie `rust-dev-nightly-x86_64-apple-darwin.tar.xz` is fallback for `rust-dev-nightly-aarch64-apple-darwin.tar.xz`.

### PR DESCRIPTION
**Pull request by Rattenkrieg**
Fixes #107225 
Now `supported_platforms` has a knowledge whether llvm asserts artifacts are available for particular host triple.

@jyn514 @albertlarsan68 PTAL

### CODE REVIEW

File: src/bootstrap/native.rs [hunk 1]
```diff
@@ -180,43 +180,40 @@ pub(crate) fn is_ci_llvm_available(config: &Config, asserts: bool) -> bool {
...
-        "i686-unknown-linux-gnu",
-        "x86_64-unknown-linux-gnu",
-        "x86_64-apple-darwin",
-        "x86_64-pc-windows-gnu",
-        "x86_64-pc-windows-msvc",
+        ("aarch64-unknown-linux-gnu", false),
+        ("i686-pc-windows-gnu", false),
+        ("i686-pc-windows-msvc", false),
+        ("i686-unknown-linux-gnu", false),
+        ("x86_64-unknown-linux-gnu", true),
```
Comment (Rattenkrieg) [inline src/bootstrap/native.rs:187]: First five are `false` according to now removed 
```rust
if (triple == "aarch64-unknown-linux-gnu" || triple.contains("i686")) && asserts {
    return false
}

File: src/bootstrap/native.rs [hunk 2]
```diff
@@ -180,43 +180,40 @@ pub(crate) fn is_ci_llvm_available(config: &Config, asserts: bool) -> bool {
...
+        ("mipsel-unknown-linux-gnu", false),
+        ("powerpc-unknown-linux-gnu", false),
+        ("powerpc64-unknown-linux-gnu", false),
+        ("powerpc64le-unknown-linux-gnu", false),
+        ("riscv64gc-unknown-linux-gnu", false),
+        ("s390x-unknown-linux-gnu", false),
+        ("x86_64-unknown-freebsd", false),
+        ("x86_64-unknown-illumos", false),
+        ("x86_64-unknown-linux-musl", false),
+        ("x86_64-unknown-netbsd", false),
```
Comment (Rattenkrieg) [inline src/bootstrap/native.rs:210]: No "llvm with asserts" artifacts are published for tier 2 with host tools.

File: src/bootstrap/config/tests.rs [hunk 3]
```diff
@@ -19,6 +19,8 @@ fn download_ci_llvm() {
     assert_eq!(parse_llvm(""), if_available);
     assert_eq!(parse_llvm("rust.channel = \"dev\""), if_available);
     assert!(!parse_llvm("rust.channel = \"stable\""));
+    assert!(parse_llvm("llvm.assertions = true \r\n build.target = [\"x86_64-unknown-linux-gnu\"] \r\n llvm.download-ci-llvm = \"if-available\""));
+    assert_eq!(parse_llvm("llvm.assertions = true \r\n build.target = [\"aarch64-apple-darwin\"] \r\n llvm.download-ci-llvm = \"if-available\""), false);
```
Comment (Rattenkrieg) [inline src/bootstrap/config/tests.rs:23]: Seems specifying target in config under test is not affecting `config.build.triple`, it is still `"aarch64-apple-darwin"` as my machine.
> ./x.py test src/bootstrap/ --target x86_64-unknown-linux-gnu --test-args download_ci_llvm
is not helping either: `x.py` complains about argument.

Comment (jyn514) [reply src/bootstrap/config/tests.rs:23]: you want `build.build`, not `build.target`. https://github.com/rust-lang/rust/blob/a377893da2cd7124e5a18c7116cbb70e16dd5541/config.toml.example#L188-L194

File: src/bootstrap/config/tests.rs [hunk 4]
```diff
@@ -19,6 +19,8 @@ fn download_ci_llvm() {
     assert_eq!(parse_llvm(""), if_available);
     assert_eq!(parse_llvm("rust.channel = \"dev\""), if_available);
     assert!(!parse_llvm("rust.channel = \"stable\""));
+    assert!(parse_llvm("llvm.assertions = true \r\n build.build = \"x86_64-unknown-linux-gnu\" \r\n llvm.download-ci-llvm = \"if-available\""));
+    assert_eq!(parse_llvm("llvm.assertions = true \r\n build.build = \"aarch64-apple-darwin\" \r\n llvm.download-ci-llvm = \"if-available\""), false);
```
Comment (albertlarsan68) [inline src/bootstrap/config/tests.rs:23]:
```suggestion
    assert!(!parse_llvm("llvm.assertions = true \r\n build.build = \"aarch64-apple-darwin\" \r\n llvm.download-ci-llvm = \"if-available\""));
```
Asserting for `false` should be done in this way rather than asserting equality with `false`.

**Review by albertlarsan68 — APPROVED** [review]
Just a nit, r=me when done and CI passes

File: src/bootstrap/config/tests.rs (hunk 4 above)
Comment (Rattenkrieg) [reply src/bootstrap/config/tests.rs:23]: Got it! I'll get back to these tests later today, since there are formatting issues and adding `build.build` didn't help.

File: src/bootstrap/config.rs [hunk 5]
```diff
@@ -965,6 +965,9 @@ impl Config {
         config.changelog_seen = toml.changelog_seen;
 
         let build = toml.build.unwrap_or_default();
+        if let Some(file_build) = build.build {
+            config.build = TargetSelection::from_user(&file_build);
+        };
```
Comment (Rattenkrieg) [inline src/bootstrap/config.rs:970]: NB build triple wasn't read from result of `get_toml`. I don't know whether it was skipped deliberately or just simply forgotten. I'm leaning towards the latter, since `build.host` and `build.target` are read below from the same toml.

Comment (jyn514) [reply src/bootstrap/config.rs:970]: probably accidental; https://github.com/rust-lang/rust/blob/8adbe6e436d7ae03dbb0e82729745e1e514eb508/src/bootstrap/config.rs#L815 gets it right 99% of the time and python sets it for https://github.com/rust-lang/rust/blob/8adbe6e436d7ae03dbb0e82729745e1e514eb508/src/bootstrap/build.rs#L4-L6 the rest of the time in https://github.com/rust-lang/rust/blob/8adbe6e436d7ae03dbb0e82729745e1e514eb508/src/bootstrap/bootstrap.py#L788-L797, so likely no one ever noticed.

I *think* it shouldn't ever matter in practice; even when we stop using python (https://github.com/rust-lang/rust/issues/94829) the shell scripts should still respect `build.build` in config.toml, but changing it to make things testable seems good 👍

**Comment by Rattenkrieg** [comment]
@albertlarsan68 is there anything else left for me to address?

**Comment by jyn514** [comment]
@Rattenkrieg Albert is on vacation until next week

**Comment by Rattenkrieg** [comment]
> @Rattenkrieg Albert is on vacation until next week

Got it, sorry, no rush then.

**Comment by albertlarsan68** [comment]
I think this is good. Can you squash the commits please?

Tip: post a comment containing @rustbot ready when you want another review, it puts the PR back into the to-do list of the reviewer.

**Comment by albertlarsan68** [comment]
Thanks!
@bors r+ rollup
