### PR TITLE
Fix ICE #63226

### LINKED ISSUE #63226: ICE when constructing monomorphic vtable in a static in dependent crate.
This is ICE happens when I call `ROnce::new` from the abi_stable crate in const contexts in dependent crates/doctests,
but not when using the `ROnce::NEW` associated constant.

# Reproducing

It can be reproduced using a doctest in the playground:
https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=27b35d06267adeacb7334388600c96be

It can also be reproduced by cloning [this repository](https://github.com/rodrimati1992/const_fn_ice_0),and then build lib_1.

# Code

The code for the linked repositories is :

lib_0:

```rust

pub struct VTable{
    state:extern fn(),
}


impl VTable{
    pub const fn vtable()->&'static VTable{
        Self::VTABLE
    }

    const VTABLE: &'static VTable = 
        &VTable{state};
}

extern fn state(){  }


```

lib_1:

```rust

use lib_0::VTable;

static ICE_ICE:&'static VTable=VTable::vtable();

```

# Error

This is the error message:

```

   Compiling lib_1 v0.1.0 (/home/matias/Documents/eclipse_workspace/tmp/const_fn_ice/lib_1)
warning: static item is never used: `ICE_ICE`
 --> src/lib.rs:3:1
  |
3 | static ICE_ICE:&'static VTable=VTable::vtable();
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: `#[warn(dead_code)]` on by default

error: internal compiler error: src/librustc_mir/monomorphize/collector.rs:778: Cannot create local mono-item for DefId(15:17 ~ lib_0[ce77]::state[0])

thread 'rustc' panicked at 'Box<Any>', src/librustc_errors/lib.rs:644:9
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.34/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.34/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:47
   3: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:36
   4: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:200
   5: std::panicking::default_hook
             at src/libstd/panicking.rs:214
   6: rustc::util::common::panic_hook
   7: core::ops::function::Fn::call
   8: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:481
   9: std::panicking::begin_panic
  10: rustc_errors::Handler::bug
  11: rustc::util::bug::opt_span_bug_fmt::{{closure}}
  12: rustc::ty::context::tls::with_opt::{{closure}}
  13: rustc::ty::context::tls::with_context_opt
  14: rustc::ty::context::tls::with_opt
  15: rustc::util::bug::opt_span_bug_fmt
  16: rustc::util::bug::bug_fmt
  17: rustc_mir::monomorphize::collector::should_monomorphize_locally
  18: rustc_mir::monomorphize::collector::collect_miri
  19: rustc_mir::monomorphize::collector::collect_miri
  20: rustc_mir::monomorphize::collector::collect_const
  21: rustc_mir::monomorphize::collector::collect_items_rec
  22: rustc_mir::monomorphize::collector::collect_crate_mono_items::{{closure}}
  23: rustc::util::common::time
  24: rustc_mir::monomorphize::collector::collect_crate_mono_items
  25: rustc::util::common::time
  26: rustc_mir::monomorphize::partitioning::collect_and_partition_mono_items
  27: rustc::ty::query::__query_compute::collect_and_partition_mono_items
  28: rustc::dep_graph::graph::DepGraph::with_task_impl
  29: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt>::get_query
  30: rustc_codegen_ssa::back::symbol_export::exported_symbols_provider_local
  31: rustc::ty::query::__query_compute::exported_symbols
  32: rustc::dep_graph::graph::DepGraph::with_task_impl
  33: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt>::get_query
  34: rustc_metadata::encoder::EncodeContext::encode_crate_root
  35: rustc::dep_graph::graph::DepGraph::with_ignore
  36: rustc_metadata::encoder::encode_metadata
  37: rustc_metadata::cstore_impl::<impl rustc::middle::cstore::CrateStore for rustc_metadata::cstore::CStore>::encode_metadata
  38: rustc::ty::context::TyCtxt::encode_metadata
  39: rustc_interface::passes::encode_and_write_metadata
  40: rustc::util::common::time
  41: rustc_interface::passes::start_codegen
  42: rustc::ty::context::tls::enter_global
  43: rustc_interface::passes::BoxedGlobalCtxt::access::{{closure}}
  44: rustc_interface::passes::create_global_ctxt::{{closure}}
  45: rustc_interface::passes::BoxedGlobalCtxt::enter
  46: rustc_interface::queries::Query<T>::compute
  47: rustc_interface::queries::<impl rustc_interface::interface::Compiler>::ongoing_codegen
  48: rustc_interface::interface::run_compiler_in_existing_thread_pool
  49: std::thread::local::LocalKey<T>::with
  50: syntax::with_globals
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
query stack during panic:
#0 [collect_and_partition_mono_items] collect_and_partition_mono_items
#1 [exported_symbols] exported_symbols
end of query stack
error: aborting due to previous error


note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.38.0-nightly (435236b88 2019-08-01) running on i686-unknown-linux-gnu

note: compiler flags: -C debuginfo=2 -C incremental --crate-type lib

note: some of the compiler flags provided by cargo are hidden

error: Could not compile `lib_1`.


```

### PR DESCRIPTION
**Pull request by JohnTitor**
Fixes #63226

r? @oli-obk

### CODE REVIEW

File: src/librustc/middle/reachable.rs [hunk 1]
```diff
@@ -32,9 +32,15 @@ fn item_might_be_inlined(tcx: TyCtxt<'tcx>, item: &hir::Item, attrs: CodegenFnAt
         return true
     }
 
-    match item.node {
-        hir::ItemKind::Impl(..) |
-        hir::ItemKind::Fn(..) => {
+        match item.node {
```
Comment (Centril) [inline src/librustc/middle/reachable.rs]:
```suggestion
    match item.node {
```

File: src/librustc/middle/reachable.rs [hunk 2]
```diff
@@ -32,9 +32,15 @@ fn item_might_be_inlined(tcx: TyCtxt<'tcx>, item: &hir::Item, attrs: CodegenFnAt
...
+        hir::ItemKind::Fn(_, header, ..) => {
+            if header.constness == hir::Constness::Const {
```
Comment (Centril) [inline src/librustc/middle/reachable.rs]: Imo this should be turned into a guard condition instead (or better yet, pattern match on `constness`).

File: src/librustc/middle/reachable.rs [hunk 3]
```diff
@@ -32,9 +32,15 @@ fn item_might_be_inlined(tcx: TyCtxt<'tcx>, item: &hir::Item, attrs: CodegenFnAt
...
+                return true;
+            }
+            let generics = tcx.generics_of(tcx.hir().local_def_id(item.hir_id));
+            generics.requires_monomorphization(tcx)
+        }
+        hir::ItemKind::Impl(..) => {
             let generics = tcx.generics_of(tcx.hir().local_def_id(item.hir_id));
```
Comment (Centril) [inline src/librustc/middle/reachable.rs]: ...since it would allow us to reuse the body of this match arm.

File: src/test/ui/issues/issue-63226.rs [hunk 4]
```diff
@@ -0,0 +1,10 @@
+// aux-build:issue-63226.rs
```
Comment (Centril) [inline src/test/ui/issues/issue-63226.rs]: Also, can we move this test to where the other tests for `const fn`s are?
A comment explaining the test would also be good. :)

File: src/librustc/middle/reachable.rs (hunk 1 above)
Comment (JohnTitor) [reply src/librustc/middle/reachable.rs]: Fixed!

File: src/librustc/middle/reachable.rs (hunk 2 above)
Comment (JohnTitor) [reply src/librustc/middle/reachable.rs]: Added a match guard.

File: src/test/ui/issues/issue-63226.rs (hunk 4 above)
Comment (JohnTitor) [reply src/test/ui/issues/issue-63226.rs]: Moved into `ui/consts`

File: src/librustc/middle/reachable.rs [hunk 5]
```diff
@@ -33,6 +33,9 @@ fn item_might_be_inlined(tcx: TyCtxt<'tcx>, item: &hir::Item, attrs: CodegenFnAt
     }
 
     match item.node {
+        hir::ItemKind::Fn(_, header, ..) if header.constness == hir::Constness::Const => {
```
Comment (Centril) [inline src/librustc/middle/reachable.rs]:
```suggestion
        hir::ItemKind::Fn(_, header, ..) if header.is_const() => {
```

(There is some follow-up cleanup potential from using more of `.is_const()` from a quick search `hir::Constness::Const`.)

File: src/librustc/middle/reachable.rs [hunk 6]
```diff
@@ -52,6 +55,11 @@ fn method_might_be_inlined(
     if codegen_fn_attrs.requests_inline() || generics.requires_monomorphization(tcx) {
         return true
     }
+    if let hir::ImplItemKind::Method(method_sig, _) = &impl_item.node {
+        if method_sig.header.constness == hir::Constness::Const {
```
Comment (Centril) [inline src/librustc/middle/reachable.rs]:
```suggestion
        if method_sig.header.is_const() {
```

File: src/librustc/middle/reachable.rs (hunk 5 above)
Comment (JohnTitor) [reply src/librustc/middle/reachable.rs]: Oh, thanks! Uses it instead of `==`.

File: src/test/ui/issues/issue-8171-default-method-self-inherit-builtin-trait.stderr [hunk 7]
```diff
@@ -0,0 +1,6 @@
+error: failed to remove $TEST_BUILD_DIR/issues/issue-8171-default-method-self-inherit-builtin-trait/issue-8171-default-method-self-inherit-builtin-trait.issue_8171_default_method_self_inherit_builtin_trait.7rcbfp3g-cgu.0.rcgu.o: 指定されたパスが見つかりません。 (os error 3)
```
Comment (oli-obk) [inline src/test/ui/issues/issue-8171-default-method-self-inherit-builtin-trait.stderr]: What happened here?

Comment (JohnTitor) [reply src/test/ui/issues/issue-8171-default-method-self-inherit-builtin-trait.stderr]: Ah, my bad, should be removed.
