### PR TITLE
Fix handling of `!` in rustdoc search

### LINKED ISSUE #96399: rustdoc: search no longer accepts `!` as part of query
Steps to reproduce:

1. Visit https://doc.rust-lang.org/nightly/std/string/trait.ToString.html?search=panic!

Expected result:

All versions of panic (that are macros) appear.

Actual result:

Query parse error.

Compare vs stable: https://doc.rust-lang.org/stable/std/string/trait.ToString.html?search=panic!

I think this is just a matter of accepting `!` in the eBNF grammar and also the JS-implemented parser.

Note that the results on stable include modules, which arguably they shouldn't. So as an additional feature improvement we might want to recognize `!` specially and treat as requiring that the results be macros (or specifically function-like macros?).

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Fixes #96399.

I also updated the eBNF.

cc @jsha 
r? @notriddle

### CODE REVIEW

File: src/librustdoc/html/static/js/search.js [hunk 1]
```diff
@@ -587,7 +597,7 @@ window.initSearch = function(rawSearchIndex) {
      *
      * The supported syntax by this parser is as follow:
      *
-     * ident = *(ALPHA / DIGIT / "_")
+     * ident = *(ALPHA / DIGIT / "_") [!]
```
Comment (notriddle) [inline src/librustdoc/html/static/js/search.js:600]: This doesn't quite match the actual implemented rule.

According to this eBNF, `!::!` is valid, because there's one bang at the end of each ident. But the actual search.js rule allows only one `!` in the entire *path*.

File: src/test/rustdoc-js-std/parser-ident.js [hunk 2]
```diff
@@ -0,0 +1,77 @@
+const QUERY = [
+    "R<!>",
+    "!",
+    "a!",
+    "a!::b",
```
Comment (notriddle) [inline src/test/rustdoc-js-std/parser-ident.js:5]: Please add a test case for `-> !`?

That seems like something that would be worth putting extra work into to make sure it work right, since diverging functions are pretty common, but also special-cased enough that it's likely to be broken if we don't test it.

File: src/librustdoc/html/static/js/search.js (hunk 1 above)
Comment (GuillaumeGomez) [reply src/librustdoc/html/static/js/search.js:600]: Indeed! I need to update the eBNF.

Comment (GuillaumeGomez) [reply src/librustdoc/html/static/js/search.js:600]: Hum actually, should we allow multiple `!` in a path? Like `!::!`?

Comment (notriddle) [reply src/librustdoc/html/static/js/search.js:600]: It doesn't actually matter to me either way.

It shouldn't ever match anything, because we can work it out for the four possible ways you can get paths that look like that, and they're all impossible:

* `never::macro`: macros can currently only appear in modules, not primitives
* `never::never`: the Never primitive has no parent item
* `macro::macro`: macros have no child items
* `macro::never`: macros have no child items

However, I'm not sure we need to reject it in the parser. All that really matters to me is that the parser reject things that look like `!foo`, for future-proofing purposes. We might want to use that for exclusion syntax later (a NOT operator, basically).

Comment (GuillaumeGomez) [reply src/librustdoc/html/static/js/search.js:600]: Ok, let's support `!::!` then.

**Comment by GuillaumeGomez** [comment]
Done!
