### PR TITLE
 Give an error when running `x.py test --stage 0 src/test/ui`

### LINKED ISSUE #77711: x.py test --stage 0 src/test/ui should give an error
Consider someone working with the standard library and running a UI test for the first time. Their workflow up until now has been
```
x.py test --stage 0 library/std
```
This is correct: it builds the standard library once and the compiler zero times. Any changes they make will be reflected in the tests.
Now assume for some reason they have to run a UI test; maybe they change a `rustc_on_unimplemented` diagnostic so the .stderr files need to change. They've been using --stage 0 so far, and they _really_ don't want to build the compiler, so they try the same thing on the new test suite:
```
x.py test --stage 0 src/test/ui
```
This is incorrect: it builds neither the standard library nor the compiler and runs tests on beta instead.
Unfortunately, the errors this gives are incomprehensible: they say things like
```
-    LL | impl<T: Copy> Foo<T> {
-       |       ^^^^^^
+    LL | impl<T: std::marker::Copy> Foo<T> {
+       |       ^^^^^^^^^^^^^^^^^^^
```
which give absolutely no indication that you're running the wrong version of the compiler (maybe you'd even think it's caused by your change!)

Instead, x.py should give an error like this:
```
$ x.py test --stage 0 src/test/ui
error: `--stage 0` is not meaningful for compiletest test suites
help: use `--stage 1` instead
note: if you're sure you want to do this, please open an issue as to why. In the meantime, you can override this with `COMPILETEST_FORCE_STAGE_0=1`.
```

### PR DESCRIPTION
**Pull request by jyn514**
The error can be overridden with `COMPILETEST_FORCE_STAGE0=1`. In practice I don't know why anyone would do this.

r? @Mark-Simulacrum 

Closes https://github.com/rust-lang/rust/issues/77711

### CODE REVIEW

File: src/bootstrap/test.rs [hunk 1]
```diff
@@ -966,6 +966,15 @@ impl Step for Compiletest {
     /// compiletest `mode` and `suite` arguments. For example `mode` can be
     /// "run-pass" or `suite` can be something like `debuginfo`.
     fn run(self, builder: &Builder<'_>) {
+        if builder.top_stage == 0 && env::var("COMPILETEST_FORCE_STAGE0").is_err() {
+            eprintln!("\
+error: `--stage 0` is not meaningful for compiletest test suites
```
Comment (Mark-Simulacrum) [inline src/bootstrap/test.rs:971]: I don't think we should say "not meaningful" - it *is* meaningful, it's just almost never going to work, because beta and master have almost always already diverged sufficiently to break tests.

Comment (jyn514) [reply src/bootstrap/test.rs:971]: How does this sound?

> error: `--stage 0` runs compiletest on the beta compiler, not your local changes, and will almost always cause tests to fail
