### PR TITLE
fix(rustdoc): Fixed stability version in rustdoc

### LINKED ISSUE #137141: Nightly docs of `std::task::ready!` report wrong stabilization version
### Location

https://doc.rust-lang.org/nightly/std/task/macro.ready.html

### Summary

The nightly docs for [`std::task::ready!`](https://doc.rust-lang.org/nightly/std/task/macro.ready.html) report a stabilization version of v1.36, while [`core::task::ready!`](https://doc.rust-lang.org/nightly/core/task/macro.ready.html) correctly reports v1.64.

This doesn't appear for [current beta docs](https://doc.rust-lang.org/beta/std/task/macro.ready.html) and [current stable docs](https://doc.rust-lang.org/1.84.1/std/task/macro.ready.html)

### PR DESCRIPTION
**Pull request by tapanprakasht**
Tries to fix https://github.com/rust-lang/rust/issues/137141 
Fixed by adding checks glob exports

### CODE REVIEW

**Review by GuillaumeGomez — APPROVED** [review]

**Comment by GuillaumeGomez** [comment]
Looks good to me, thanks!

I'll just let @notriddle take a look first before approving.

**Comment by notriddle** [comment]
This does not look good to me, because it causes docs to claim that `core::ffi::CStr` was available in 1.0.0. It just trades one bug for a different bug.

Instead, if you just want to fix this one problem, modify the propagate_stability code to ignore glob exports. It's reasonable to assume that anyone who re-exports one and only one item will write the correct stability marker on that re-export.

File: tests/rustdoc/inline_local/staged-inline.rs [hunk 1]
```diff
@@ -13,6 +13,6 @@ pub mod ffi {
 
 #[stable(feature = "v1", since = "1.0.0")]
 #[doc(inline)]
-//@ has "foo/struct.CStr.html" "//span[@class='sub-heading']/span[@class='since']" "1.0.0"
-//@ !has - "//span[@class='sub-heading']/span[@class='since']" "1.99.0"
+//@ has "foo/struct.CStr.html" "//span[@class='sub-heading']/span[@class='since']" "1.99.0"
+//@ !has - "//span[@class='sub-heading']/span[@class='since']" "1.0.0"
```
Comment (notriddle) [inline tests/rustdoc/inline_local/staged-inline.rs:17]: This does not look good to me, because it causes docs to claim that std::ffi::CStr was available in 1.64.0. It just trades one bug for a different bug.

Instead, if you just want to fix this one problem, modify the propagate_stability code to ignore glob exports. It's reasonable to assume that anyone who re-exports one and only one item will write the correct stability marker on that re-export.

**Review by notriddle — CHANGES_REQUESTED** [review]

File: tests/rustdoc/inline_local/staged-inline.rs (hunk 1 above)
Comment (tapanprakasht) [reply tests/rustdoc/inline_local/staged-inline.rs]: @notriddle I have addressed the review comments. Please check

**Review by notriddle — APPROVED** [review]

**Comment by tapanprakasht** [comment]
@GuillaumeGomez or @notriddle  I see the PR is approved now. Can you merge the changes if everything okay?

**Comment by GuillaumeGomez** [comment]
We were just waiting for CI to pass. Thanks for the fix!

@bors r=notriddle rollup

File: src/librustdoc/passes/propagate_stability.rs [hunk 2]
```diff
@@ -39,6 +39,16 @@ impl DocFolder for StabilityPropagator<'_, '_> {
...
+                let is_glob_export = item.inline_stmt_id.and_then(|id| {
+                    let hir_id = self.cx.tcx.local_def_id_to_hir_id(id);
+                    Some(matches!(
+                        self.cx.tcx.hir_node(hir_id),
+                        rustc_hir::Node::Item(rustc_hir::Item {
+                            kind: rustc_hir::ItemKind::Use(_, rustc_hir::UseKind::Glob),
+                            ..
+                        })
+                    ))
+                });
```
Comment (yotamofek) [inline src/librustdoc/passes/propagate_stability.rs:51]:
```suggestion
                let is_glob_export = item.inline_stmt_id.map(|id| {
                    let hir_id = self.cx.tcx.local_def_id_to_hir_id(id);
                    matches!(
                        self.cx.tcx.hir_node(hir_id),
                        rustc_hir::Node::Item(rustc_hir::Item {
                            kind: rustc_hir::ItemKind::Use(_, rustc_hir::UseKind::Glob),
                            ..
                        })
                    )
                });
```

Hey @tapanprakasht , sorry for the drive-by, but there is no reason to use `and_then` when your closure can never return `None`. `map` is simpler. 😊

**Review by yotamofek — CHANGES_REQUESTED** [review]
