### PR TITLE
fix: wrong trait import suggestion for T:

### LINKED ISSUE #95898: Incorrect add bounds suggestion when given type parameter like `<T:>`
Given the following code:
```rust
fn foo<T:>(t: T) {
    t.clone();
}
```

The current output is:

```
error[E0599]: no method named `clone` found for type parameter `T` in the current scope
 --> src/lib.rs:2:7
  |
2 |     t.clone();
  |       ^^^^^ method not found in `T`
  |
  = help: items from traits can only be used if the type parameter is bounded by the trait
help: the following trait defines an item `clone`, perhaps you need to restrict type parameter `T` with it:
  |
1 | fn foo<T: Clone:>(t: T) {
  |        ~~~~~~~~
```

Ideally the output should look like:

```
error[E0599]: no method named `clone` found for type parameter `T` in the current scope
 --> src/lib.rs:2:7
  |
2 |     t.clone();
  |       ^^^^^ method not found in `T`
  |
  = help: items from traits can only be used if the type parameter is bounded by the trait
help: the following trait defines an item `clone`, perhaps you need to restrict type parameter `T` with it:
  |
1 | fn foo<T: Clone>(t: T) {
  |          ++++++
```

Note: The `T:` bound is treated incorrectly.

### PR DESCRIPTION
**Pull request by PoorlyDefinedBehaviour**
The suggestion to bound `T` had an extra `:`.

```rust
fn foo<T:>(t: T) {
  t.clone();
}
```

```
error[E0599]: no method named `clone` found for type parameter `T` in the current scope
 --> src/lib.rs:2:7
  |
2 |     t.clone();
  |       ^^^^^ method not found in `T`
  |
  = help: items from traits can only be used if the type parameter is bounded by the trait
help: the following trait defines an item `clone`, perhaps you need to restrict type parameter `T` with it:
  |
1 | fn foo<T: Clone:>(t: T) {
  |        ~~~~~~~~
 ```

Fixes: #95898

### CODE REVIEW

File: compiler/rustc_hir/src/hir.rs [hunk 1]
```diff
@@ -523,6 +523,40 @@ impl<'hir> GenericParam<'hir> {
...
+    /// fn b<T       :>()
+    ///
+    /// fn c<T
+    ///
+    /// :>()
+    /// ^
+    /// |
+    /// here
+    /// ```
+    pub fn colon_span_for_suggestions(&self, source_map: &SourceMap) -> Option<Span> {
```
Comment (compiler-errors) [inline compiler/rustc_hir/src/hir.rs:546]: This might possibly merge-conflict with #95970, since it's duplicated from that. Might want to wait on that landing and rebase.

File: src/test/ui/traits/issue-95898.rs [hunk 2]
```diff
@@ -0,0 +1,10 @@
+// Test for #95898: The trait suggestion had an extra `:` after the trait.
+// edition:2021
+
+#[rustfmt::skip]
```
Comment (fee1-dead) [inline src/test/ui/traits/issue-95898.rs:4]: I don't think you need rustfmt::skip here. We configured rustfmt to not run on ui tests for this exact reason.

Comment (fee1-dead) [reply src/test/ui/traits/issue-95898.rs:4]: You might need to turn off auto formatting from your IDE to remove this attribute.

Comment (PoorlyDefinedBehaviour) [reply src/test/ui/traits/issue-95898.rs]: Removed `rustfmt::skip`, thanks :+1:

File: compiler/rustc_hir/src/hir.rs (hunk 1 above)
Comment (PoorlyDefinedBehaviour) [reply compiler/rustc_hir/src/hir.rs]: Done

**Comment by PoorlyDefinedBehaviour** [comment]
> Can you please [squash](https://stackoverflow.com/questions/25356810/git-how-to-squash-all-commits-on-branch) the commits? If you want, I can do it for you by having a bot squash the commits.

Done

**Review by fee1-dead — APPROVED** [review]

**Comment by PoorlyDefinedBehaviour** [comment]
Thanks for your patience @fee1-dead @compiler-errors :+1:
