### PR TITLE
Suggest use .. to fill in the rest of the fields of Struct

### LINKED ISSUE #102806: Detect attempt to use '...' for struct update
If I try to use "functional record update syntax" (aka "struct update syntax") with three dots instead of two, the compiler could emit a clearer error message.

Given the following code ([playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=39a57212a40e794a2c10cfec60fdd323)):

```rust
struct V3 {
    x: f32,
    y: f32,
    z: f32
}

fn pz(v: V3) {
    let _ = V3 {
        z: 0.0,
        ...v
    };
}
```

The current output is:

```
error: expected identifier, found `...`
  --> src/lib.rs:10:9
   |
8  |     let _ = V3 {
   |             -- while parsing this struct
9  |         z: 0.0,
10 |         ...v
   |         ^^^ expected identifier

error[E0063]: missing fields `x` and `y` in initializer of `V3`
 --> src/lib.rs:8:13
  |
8 |     let _ = V3 {
  |             ^^ missing `x` and `y`
```

Ideally the output should be more inclusive about what token was expected:

```
error: expected identifier or `..`, found `...`
```

and include a suggestion directing the programmer to the correct syntax:

```
help: to fill in the rest of the fields from `v`, write `..v` (note only two dots)
```

**Motivation**

* Programmers who also write in JavaScript might be familiar with the similar [spread syntax in object literals](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_syntax#spread_in_object_literals), which uses `...`
* In English prose, `...` is more common than `..`

### PR DESCRIPTION
**Pull request by chenyukang**
Fixes #102806

### CODE REVIEW

File: compiler/rustc_parse/src/parser/expr.rs [hunk 1]
```diff
@@ -2820,6 +2820,15 @@ impl<'a> Parser<'a> {
...
                 self.recover_struct_comma_after_dotdot(exp_span);
                 break;
+            } else if self.token == token::DotDotDot && self.look_ahead(1, |t| t.is_ident()) {
+                // suggest `..v` instead of `...v`
+                self.sess.emit_err(MissingDotDot {
+                    token_span: self.token.span,
+                    sugg_span: self.token.span,
+                });
+                self.bump();
+                self.bump(); // bump the next ident
```
Comment (compiler-errors) [inline compiler/rustc_parse/src/parser/expr.rs:2830]: This probably doesn't handle something like `...Default::default()` correctly -- can you use a snapshot and `parse_expr` instead?

Comment (chenyukang) [reply compiler/rustc_parse/src/parser/expr.rs]: Great point, updated the code.

File: compiler/rustc_parse/src/parser/expr.rs [hunk 2]
```diff
@@ -2820,6 +2820,21 @@ impl<'a> Parser<'a> {
...
                 self.recover_struct_comma_after_dotdot(exp_span);
                 break;
+            } else if self.token == token::DotDotDot {
+                // suggest `..v` instead of `...v`
+                let snapshot = self.create_snapshot_for_diagnostic();
+                let span = self.token.span;
+                self.bump();
+                match self.parse_expr() {
+                    Ok(_p) => {
+                        self.sess.emit_err(MissingDotDot { token_span: span, sugg_span: span });
```
Comment (compiler-errors) [inline compiler/rustc_parse/src/parser/expr.rs:2830]: Looking better! 

Can you actually set the base expression like above? Something like `base = ast::StructRest::Base(e)`. Basically emulate the code above. That should suppress the "missing fields `x` and `y` in initializer of `V3`" error below.

Also, can handle the case of `... }` like above?

Comment (chenyukang) [reply compiler/rustc_parse/src/parser/expr.rs:2830]: oo, I left the "missing fields x and y in initializer of V3" intentionally, I thought it may helpful for let developer know which fields are missing.

And for the case of `...}`, we need to suggest something like `..{expr}`? So I left it as before also.

Comment (compiler-errors) [reply compiler/rustc_parse/src/parser/expr.rs:2830]: > I thought it may helpful for let developer know which fields are missing.

This is extra noise if the developer wrote `...` instead of `..`

> And for the case of `...}`, we need to suggest something like `..{expr}`?

Not in the case of a pattern, which is the same place that `.. }` is valid.

---

Basically, we should treat `...` typo as closely to `..` as possible, especially if we're ¨recovering" parsing here.

Comment (compiler-errors) [reply compiler/rustc_parse/src/parser/expr.rs:2830]: It may actually be easier to merge this check with the `..` logic above, since we're basically just duplicating that.

Comment (chenyukang) [reply compiler/rustc_parse/src/parser/expr.rs:2830]: Ok, I will make a update.

Comment (chenyukang) [reply compiler/rustc_parse/src/parser/expr.rs:2830]: For the case of `let V3 { z: val, ...} = v`, we already have a check to report:

```console
error: expected field pattern, found `...`
  --> /home/cat/code/rust/src/test/ui/parser/issue-102806.rs:23:22
   |
23 |     let V3 { z: val, ... } = v;
   |                      ^^^ help: to omit remaining fields, use one fewer `.`: `..`
```

Will keep same as before.

Comment (chenyukang) [reply compiler/rustc_parse/src/parser/expr.rs]: > It may actually be easier to merge this check with the `..` logic above, since we're basically just duplicating that.

Tried to merge the two checks, but I found split them seems more easy to read.

Comment (compiler-errors) [reply compiler/rustc_parse/src/parser/expr.rs]: That's ok, I don't think it's necessary

**Comment by Nilstrieb** [comment]
Hi, I've seen you changed some diagnostic structs in your PR. After #103345, the way we refer to fluent messages changed. They are now in a flat namespace with the same identifier as in the fluent file. For example,  `parser::cool_thing` is now `parser_cool_thing` and `parser::suggestion` just `suggestion`.
You should [rebase](https://rustc-dev-guide.rust-lang.org/git.html#rebasing-and-conflicts) to the latest master and change your fluent message references as described above. Thanks!

**Comment by chenyukang** [comment]
> You should [rebase](https://rustc-dev-guide.rust-lang.org/git.html#rebasing-and-conflicts) to the latest master and change your fluent message references as described above. Thanks!

Rebased update.
r? @compiler-errors

**Comment by Rageking8** [comment]
> > You should [rebase](https://rustc-dev-guide.rust-lang.org/git.html#rebasing-and-conflicts) to the latest master and change your fluent message references as described above. Thanks!
> 
> Rebased update.
> r? @compiler-errors 

Should be `@rustbot ready` to signify the PR is ready for another review and not `r?`.

**Comment by chenyukang** [comment]
> Should be `@rustbot ready` to signify the PR is ready for another review and not `r?`.
Thanks for tip 😁.

@rustbot ready

File: compiler/rustc_parse/src/parser/expr.rs [hunk 3]
```diff
@@ -2897,6 +2897,27 @@ impl<'a> Parser<'a> {
                 }
                 self.recover_struct_comma_after_dotdot(exp_span);
                 break;
+            } else if self.token == token::DotDotDot {
+                // suggest `..v` instead of `...v`
```
Comment (davidtwco) [inline compiler/rustc_parse/src/parser/expr.rs:2901]: Could you move this logic into a function? To keep `parse_struct_fields` free of diagnostic logic as much as we can. :)

**Review by davidtwco — APPROVED** [review]
r=me,compiler-errors after one comment

File: compiler/rustc_parse/src/parser/expr.rs (hunk 3 above)
Comment (chenyukang) [reply compiler/rustc_parse/src/parser/expr.rs]: Split out an function and make it shorter.

File: compiler/rustc_parse/src/parser/expr.rs (hunk 2 above)
Comment (chenyukang) [reply compiler/rustc_parse/src/parser/expr.rs]: Finally, merge it with the `..` logic above 😁

File: compiler/rustc_parse/src/parser/expr.rs [hunk 4]
```diff
@@ -3027,6 +3027,18 @@ impl<'a> Parser<'a> {
         self.recover_stmt();
     }
 
+    fn recover_struct_fileds_dots(&mut self, close_delim: Delimiter) -> bool {
```
Comment (compiler-errors) [inline compiler/rustc_parse/src/parser/expr.rs:3030]:
```suggestion
    fn recover_struct_field_dots(&mut self, close_delim: Delimiter) -> bool {
```

File: compiler/rustc_parse/src/parser/expr.rs [hunk 5]
```diff
@@ -2880,7 +2880,7 @@ impl<'a> Parser<'a> {
         };
 
         while self.token != token::CloseDelim(close_delim) {
-            if self.eat(&token::DotDot) {
+            if self.eat(&token::DotDot) || self.recover_struct_fileds_dots(close_delim) {
```
Comment (compiler-errors) [inline compiler/rustc_parse/src/parser/expr.rs:2883]:
```suggestion
            if self.eat(&token::DotDot) || self.recover_struct_field_dots(close_delim) {
```

**Comment by chenyukang** [comment]
> @bors r=davidtwco,compiler-errors
> 
> I hope you didn't mind me renaming the function typo, but I didn't want to delay r+'ing still since I know you have been waiting 😄

Thanks very much.
