### PR TITLE
Rustdoc: Fix macros 2.0 and built-in derives being shown at the wrong path

### LINKED ISSUE #74355: `pub macro` defined in submodule is shown at the wrong path
rustdoc is showing the `raw_mut` macro at the wrong path in libcore: https://doc.rust-lang.org/nightly/core/macro.raw_mut.html says `core::raw_mut` but really it is `core::ptr::raw_mut` (and the same goes for `core::ptr::raw_const`). Looks like `pub macro` is not handled correctly?

Cc @rust-lang/rustdoc

### PR DESCRIPTION
**Pull request by danielhenrymantilla**
Fixes #74355

  - ~~waiting on author + draft PR since my code ought to be cleaned up _w.r.t._ the way I avoid the `.unwrap()`s:~~

      - ~~dummy items may avoid the first `?`,~~

      - ~~but within the module traversal some tests did fail (hence the second `?`), meaning the crate did not possess the exact path of the containing module (`extern` / `impl` blocks maybe? I'll look into that).~~

r? @jyn514

### CODE REVIEW

File: src/librustdoc/visit_ast.rs [hunk 1]
```diff
@@ -63,23 +63,67 @@ impl<'a, 'tcx> RustdocVisitor<'a, 'tcx> {
...
+                // Only the last two need to be fixed, thus:
+                if def.ast.macro_rules {
+                    return None;
+                }
+                let macro_parent_module = self.cx.tcx.def_path({
+                    use rustc_middle::ty::DefIdTree;
+                    self.cx
+                        .tcx
+                        /* Because of #77828 we cannot do the simpler:
+                        .parent_module(def.hir_id).to_def_id()
```
Comment (danielhenrymantilla) [inline src/librustdoc/visit_ast.rs:100]: Maybe we should wait for #77828 to be fixed before merging the current PR?

File: src/librustdoc/visit_ast.rs [hunk 2]
```diff
@@ -63,23 +63,67 @@ impl<'a, 'tcx> RustdocVisitor<'a, 'tcx> {
...
+                let mut cur_mod = &mut top_level_module;
+                for path_segment in macro_parent_module.data {
+                    let path_segment = path_segment.to_string();
+                    cur_mod = cur_mod.mods.iter_mut().find(|module| {
+                        matches!(
+                            module.name, Some(symbol)
+                            if symbol.with(|mod_name| mod_name == path_segment)
+                        )
+                    })?;
+                }
```
Comment (jyn514) [inline src/librustdoc/visit_ast.rs:113]: Ugh, I _really_ wish rustdoc didn't use its own data structures (https://github.com/rust-lang/rust/issues/76382). That said, if this works I won't block on it, but it's unambiguously a hack.

```suggestion
                // HACK: rustdoc has no way to lookup `doctree::Module`s by their HirId
                // HACK: instead, lookup the module by its name, by looking at each path segment one at a time
                // WARNING: this will probably break in the presence of re-exports or shadowing.
                for path_segment in macro_parent_module.data {
                    let path_segment = path_segment.to_string();
                    cur_mod = cur_mod.mods.iter_mut().find(|module| {
                        matches!(
                            module.name, Some(symbol)
                            if symbol.with(|mod_name| mod_name == path_segment)
                        )
                    })?;
                }
```
@GuillaumeGomez before I sign off on this, do you know a better way to do this?

**Review by jyn514 — COMMENTED** [review]
This is awful, but I don't know a better way to do it.

**Comment by jyn514** [comment]
> dummy items may avoid the first ?,

Sorry, I wasn't thinking when I said this originally - dummy items are always `impl`s, not macros. A `?` wouldn't have worked for fake items, those will ICE instead before the function returns. I'm not sure when `parent` would return `None` for a macro.

> but within the module traversal some tests did fail (hence the second ?), meaning the crate did not possess the exact path of the containing module (extern / impl blocks maybe? I'll look into that).

Yeah, this will break for macros defined in an `impl` since those are unnamed. I don't _think_ those macros can be publicly re-exported but I could be wrong.

File: src/librustdoc/visit_ast.rs [hunk 3]
```diff
@@ -63,23 +63,67 @@ impl<'a, 'tcx> RustdocVisitor<'a, 'tcx> {
...
+        top_level_module.is_crate = true;
+        // Attach the crate's exported macros to the top-level module.
+        // In the case of macros 2.0 (`pub macro`), and for built-in `derive`s as well
+        // (_e.g._, `Copy`), these are wrongly bundled in there too, so we need to fix that by
+        // moving them back to their correct locations.
+        krate.exported_macros.iter().for_each(|def| {
+            macro_rules! try_some {($($body:tt)*) => ({
+                fn fn_once<R, F: FnOnce() -> R> (f: F) -> F { f }
+                fn_once(|| Some({ $($body)* }))()
+            })}
```
[the remark this answers is not in the document]
Comment (danielhenrymantilla) [reply src/librustdoc/visit_ast.rs:83]: I did hesitate between `try` blocks and this hand-rolled `try_some!` macro a lot, and the thing is, I wanted to have that `is_macro_rules` early escape branch, by early returning `None`. And `try` blocks have no mechanism to early return other than `?`, which means that with a `try` block the code becomes:

```rust
try {
    if def.ast.macro_rules {
        None?;
    }
    ...
}
```

Which can be made to "look" better by being more hacky: `return None?;`, _abusing_ the fact the `return` is actually unreachable 😱

None of these options pleased me, which is the main reason for this being at a draft stage 😞.

If I could understand why the `for` iteration can fail (`pub macro` inside an unnamed item, maybe?), then I could, change the `macro_rules!` branch to a standard one, and then the first `?` could be replaced with a `.map`, propagated through a `.into_iter().flat_map(|it| it.data)`.

___

The other option is to factor that `try` block inside its own function, which would take as parameters what the block / closure currently captures: ` def`, `tcx`, and `&mut top_level_module`. I think that's how people usually circumvent the lack of `try` stuff, since needing such a block to begin with is a sympton of there being enough logic to warrant its own function. In that case, @jyn514:

> where should I put such a helper function?

  - If this were my code /  a crate of mine, I would put it right inside that block, since I like the reduced cognitive burden of super-scoped functions, but I know that most people are not fond of functions scoped inside other function bodies 😅

File: src/librustdoc/visit_ast.rs (hunk 2 above)
Comment (danielhenrymantilla) [reply src/librustdoc/visit_ast.rs:113]: > That said, if this works I won't block on it, but it's unambiguously a hack.

Definitely! The reason I've submitted this code (despite my not having cleaned that `try` block elsewhere) was for you people to tell me if there was some obvious tool I had missed in places like here, given my lack of experience with `rustdoc` and `rustc` internals 👶

File: src/test/rustdoc/macro_pub_in_module.rs [hunk 4]
```diff
@@ -0,0 +1,9 @@
+//! See issue #74355
+#![crate_name = "krate"]
+#![feature(decl_macro)]
+
+// @has krate/some_module/macro.my_macro.html
+pub mod some_module {
+    //
+    pub macro my_macro() {}
```
[the remark this answers is not in the document]
Comment (danielhenrymantilla) [reply src/test/rustdoc/macro_pub_in_module.rs:8]: Oh, I didn't know that could be done. Neat! 👌

File: src/librustdoc/visit_ast.rs (hunk 3 above)
[the remark this answers is not in the document]
Comment (jyn514) [reply src/librustdoc/visit_ast.rs:83]: I like a function-scoped function, it's local, does the same thing as `try_some` and is easier to read.

File: src/librustdoc/visit_ast.rs [hunk 5]
```diff
@@ -63,23 +63,69 @@ impl<'a, 'tcx> RustdocVisitor<'a, 'tcx> {
...
+                /* Because of #77828 we cannot do the simpler:
+                let macro_parent_module = tcx.def_path(tcx.parent_module(def.hir_id).to_def_id());
+                // and instead have to do: */
+                let macro_parent_module = tcx.def_path({
+                    use rustc_middle::ty::DefIdTree;
+                    tcx.parent(tcx.hir().local_def_id(def.hir_id).to_def_id())?
+                });
+                // HACK: rustdoc has no way to lookup `doctree::Module`s by their HirId. Instead,
+                // lookup the module by its name, by looking at each path segment one at a time.
+                // WARNING: this will probably break in the presence of re-exports or shadowing.
```
Comment (danielhenrymantilla) [inline src/librustdoc/visit_ast.rs:104]: @jyn514 I've been thinking about this: since this whole `visit_ast` happens before `clean`, I don't really see how re-exports could break this (unless the obtained `DefPath` is not what I thought it was (which may be the case 😅)):

 1. IIUC, `rustc` only puts macros in `krate.exported_macros` if they have been defined (and exported) within that very crate. For non-`macro_rules!` macros, their _initial_ location (`DefPath`) is the one traversed through this `for` loop.

 1. The macro or one of its containing modules may be re-exported elsewhere, but that only matters later on, at the `clean` stage.

 1. `clean` will then already to The Right Thing™ in presence of re-exports.

Maybe I should enhance the test file with these weirder scenarios?

```rust
mod inner {
    // ...
    mod private {
        pub macro m() {}
    }

    // @has krate/inner/macro.m.html
    pub use private::m;
}
```

Granted, there is one scenario that does worry me, so I'll add that test case too (I don't know what a `DefPath`s expands to when within a function's scope):

```rust
fn both_fn_and_mod() {
    pub macro m() {}
}
pub mod both_fn_and_mod {
    // @!has krate/both_fn_and_mod/macro.m.html
}
```

Comment (jyn514) [reply src/librustdoc/visit_ast.rs:104]: Hmm, that makes sense to me. Can you add those test cases, and also one for cross-crate re-exports? Search for `aux-build` for examples of how to write a test.

Comment (danielhenrymantilla) [reply src/librustdoc/visit_ast.rs:104]: Will do!
@rustbot modify labels: -S-waiting-on-review +S-waiting-on-author

File: src/librustdoc/visit_ast.rs [hunk 6]
```diff
@@ -63,23 +63,65 @@ impl<'a, 'tcx> RustdocVisitor<'a, 'tcx> {
...
-        module
-            .macros
-            .extend(krate.exported_macros.iter().map(|def| self.visit_local_macro(def, None)));
-        module.is_crate = true;
+        top_level_module.is_crate = true;
+        // Attach the crate's exported macros to the top-level module.
+        // In the case of macros 2.0 (`pub macro`), and for built-in `derive`s or attributes as
+        // well (_e.g._, `Copy`), these are wrongly bundled in there too, so we need to fix that by
+        // moving them back to their correct locations.
+        krate.exported_macros.iter().for_each(|def| {
```
Comment (jyn514) [inline src/librustdoc/visit_ast.rs:79]: nit: I don't like `for_each`, I'd rather use
```suggestion
        for def in &krate.exported_macros {
```

File: src/test/rustdoc/auxiliary/macro_pub_in_module.rs [hunk 7]
```diff
@@ -0,0 +1,13 @@
...
+
+#![feature(decl_macro)]
+#![crate_name = "external_crate"]
+
+pub mod some_module {
+    /* == Make sure the logic is not affected by a re-export == */
+    mod private {
+        pub macro external_macro() {}
+    }
+    // @has external_crate/some_module/macro.external_macro.html
```
Comment (jyn514) [inline src/test/rustdoc/auxiliary/macro_pub_in_module.rs:11]: You only need to put this in the main test file, not both.
```suggestion
```

File: src/test/rustdoc/macro_pub_in_module.rs [hunk 8]
```diff
@@ -0,0 +1,49 @@
+// aux-build:macro_pub_in_module.rs
+// edition:2018
+// build-aux-docs
+// @has external_crate/some_module/macro.external_macro.html
```
Comment (jyn514) [inline src/test/rustdoc/macro_pub_in_module.rs:4]:
```suggestion
// @has external_crate/some_module/macro.external_macro.html
// @!has external_crate/macro.raw_const.html
// @!has external_crate/macro.test.html
// @!has external_crate/macro.Clone.html
// @!has external_crate/macro.m.html
```

File: src/test/rustdoc/macro_pub_in_module.rs [hunk 9]
```diff
@@ -0,0 +1,49 @@
...
+    // @has krate/inner/macro.Clone.html
+    #[rustc_builtin_macro]
+    pub macro Clone($item:item) {}
+
+    // Make sure the logic is not affected by a re-export.
+    mod private {
+        pub macro m() {}
+    }
+    // @has krate/inner/macro.renamed.html
+    pub use private::m as renamed;
```
Comment (jyn514) [inline src/test/rustdoc/macro_pub_in_module.rs:30]: What happens if you rename the module, not the macro?
```suggestion
    // Make sure the logic is not affected by a re-export.
    mod private {
        pub macro m() {}
    }
    // @has krate/inner/macro.renamed.html
    pub use private::m as renamed;
    
    mod private2 {
        pub macro m2() {}
    }
    use private2 as renamed_mod;
    // @has krate/inner/macro.m2.html
    pub use renamed_mod::m2;
```

**Comment by danielhenrymantilla** [comment]
@Dylan-DPC still have an issue with the links in the rendered documentation, so I have to fix that before the PR is mergeable. I have been quite busy the last 2 weeks, so I have been unable to make much progress in the meantime, but now I should be able to.

**Comment by Dylan-DPC** [comment]
Cool, no issues :)

**Comment by RalfJung** [comment]
@danielhenrymantilla what is the status of this? https://github.com/rust-lang/rust/issues/74355 is the last thing blocking the stabilization of https://github.com/rust-lang/rust/issues/73394, so if there's any way I can help move this forward, please let me know. :) However, I have zero experience working on rustdoc... or even *running* rustdoc, for that matter.^^

**Comment by jyn514** [comment]
@RalfJung the review comments need to be addressed, especially the tests.

In general I'm not super happy with the approach this takes, but I don't have a better one in mind, so I'm ok with merging this temporarily until https://github.com/rust-lang/rust/issues/77828 is fixed.

**Comment by Dylan-DPC** [comment]
@danielhenrymantilla any updates?

**Comment by jyn514** [comment]
@RalfJung here is the correct way to fix the issue, which doesn't require hacks: https://github.com/rust-lang/rust/pull/79396#issuecomment-733534180. Unfortunately it needs large changes to the HIR.

**Comment by danielhenrymantilla** [comment]
Yes, there are two outstanding issues:

 1. I still have one issue with the generated links (_e.g._, references to `::core::task::ready!` do not yield a valid / clickable link; it seems to be related to the `semi_transparent` attribute somehow?);

 1. my current implementation is "hacky" due to some "limitations" of the current HIR design.

If only `2.` remained, I would leave this be waiting on review and let you people decide; but I obviously need to fix `1.` first. And I have been horribly busy as of the last month, so this PR has been in a suspended state 😅  especially given that we are not convinced this "hack" may be the way to do. I'd thus like to hear some input from other people about that point, since if the PR is deemed short-term mergeable, while waiting for the future proper fix, then I can try to squeeze some free time to fix `1.` to get this PR mergeable and get `::core::ptr::raw_{const,mut}` be ready for stabilization (cc @RalfJung)

**Comment by jyn514** [comment]
@danielhenrymantilla yes, like I said in https://github.com/rust-lang/rust/pull/77862#issuecomment-731750435 I think this is ok as a short-term hack. Not sure what's going on with `semi_transparent` but petrochenkov or Aaron Hill may have ideas.

**Comment by jyn514** [comment]
> I think this is ok as a short-term hack

Or in other words, I think it's good enough for internal use (e.g. `core::ready::task`), but I would consider fixing the hack a blocking issue for stabilizing `pub macro`.

File: src/test/rustdoc/macro_pub_in_module.rs [hunk 10]
```diff
@@ -1,49 +1,73 @@
...
 
-    // Make sure the logic is not affected by a re-export.
+    // Make sure the logic is not affected by re-exports.
+    mod unrenamed {
+        // @!has krate/macro.unrenamed.html
+        #[rustc_macro_transparency = "semitransparent"]
+        pub macro unrenamed() {}
+    }
+    // @has krate/inner/macro.unrenamed.html
+    pub use unrenamed::unrenamed;
```
Comment (danielhenrymantilla) [inline src/test/rustdoc/macro_pub_in_module.rs:35]: This check fails (and in practice, matches the case of `::core::task::ready!` re-exported from a private `mode ::core::task::ready`) because of:

https://github.com/rust-lang/rust/blob/76188b6830897a875a1289809c12b5c5d69bb7ef/compiler/rustc_privacy/src/lib.rs#L834-L840

Indeed, `rustdoc` uses the public-reachability info to decide whether or not to inline the definition of the item when it is left unspecified.

https://github.com/rust-lang/rust/blob/76188b6830897a875a1289809c12b5c5d69bb7ef/src/librustdoc/visit_ast.rs#L179-L184

If `rustc` says the item is always publicly reachable, then `rustdoc` decides not to inline the definition, which is thus then missing when the private items are stripped.

I have hacked my way around this limitation with https://github.com/rust-lang/rust/pull/77862/commits/73369151b4278ca665494d449c3e4d8e1278d5ba, but I'd welcome some feedback regarding what is deemed the best course of action, here.

  - cc @jyn514 @petrochenkov

File: src/test/rustdoc/macro_pub_in_module.rs [hunk 11]
```diff
@@ -1,49 +1,73 @@
...
 // edition:2018
 // build-aux-docs
-// @has external_crate/some_module/macro.external_macro.html
 
 //! See issue #74355
 #![feature(decl_macro, no_core, rustc_attrs)]
 #![crate_name = "krate"]
 #![no_core]
 
+// @has external_crate/some_module/macro.external_macro.html
```
Comment (jyn514) [inline src/test/rustdoc/macro_pub_in_module.rs:10]:
```suggestion
 // @has external_crate/some_module/macro.external_macro.html
  // @!has external_crate/macro.external_macro.html
```

File: src/librustdoc/clean/inline.rs [hunk 12]
```diff
@@ -169,7 +169,17 @@ crate fn record_extern_fqn(cx: &DocContext<'_>, did: DefId, kind: clean::TypeKin
         if !s.is_empty() { Some(s) } else { None }
     });
     let fqn = if let clean::TypeKind::Macro = kind {
-        vec![crate_name, relative.last().expect("relative was empty")]
+        // Check to see if it is a macro 2.0 or built-in macro
+        if matches!(
+            cx.enter_resolver(|r| r.cstore().load_macro_untracked(did, cx.sess())),
+            LoadedMacro::MacroDef(def, _)
+                if matches!(&def.kind, ast::ItemKind::MacroDef(def)
+                    if !def.macro_rules)
```
Comment (jyn514) [inline src/librustdoc/clean/inline.rs:177]: Took me a second to realize what was going on here.
```suggestion
                if matches!(&def.kind, ast::ItemKind::MacroDef(ast_def)
                    if !ast_def.macro_rules)
```

File: src/librustdoc/visit_ast.rs [hunk 13]
```diff
@@ -61,20 +61,63 @@ impl<'a, 'tcx> RustdocVisitor<'a, 'tcx> {
...
+                        // then the item is not accessible, and should thus act as if it didn't
+                        // exist (unless "associated macros" (inside an `impl`) were a thing…).
+                        continue 'exported_macros;
+                    }
+                };
+                cur_mod = cur_mod
+                    .mods
+                    .iter_mut()
+                    .find(|module| module.name == Some(path_segment_ty_ns))
+                    .unwrap();
```
Comment (jyn514) [inline src/librustdoc/visit_ast.rs:113]: I can imagine this breaking on something like

```rust
pub mod a {
  pub macro m() {}
}
pub use a as b;
pub use b::m;
```
if `def_path()` returned `b::m` instead of `a::m`. I don't think it will ever do that, but could you add the test case?

**Review by jyn514 — COMMENTED** [review]
I would prefer to wait for https://github.com/rust-lang/rust/pull/80415 so we can avoid the hack in https://github.com/rust-lang/rust/pull/77862/files#diff-4b76d999d0f2e74f6df3724a36a6b96302b16968a2f7af48d2b4c08048f8f871R90-R93. Otherwise, this looks good enough to me (https://github.com/rust-lang/rust/pull/77862#issuecomment-740744018), but petrochenkov should take a look at https://github.com/rust-lang/rust/pull/77862/commits/73369151b4278ca665494d449c3e4d8e1278d5ba to make sure it's the right fix.

r? @petrochenkov

File: src/librustdoc/visit_ast.rs (hunk 13 above)
Comment (danielhenrymantilla) [reply src/librustdoc/visit_ast.rs:113]: Except for some differences in `pub`, we already have:

https://github.com/rust-lang/rust/blob/a59bcb1c910437f35c57ccdd55025d044b207440/src/test/rustdoc/macro_pub_in_module.rs#L46-L52

Could `pub` affect HIR `def_path`s?

Comment (danielhenrymantilla) [reply src/librustdoc/visit_ast.rs:113]: Okay, I think I've managed to make this hack fail:

```rust
enum Crazy {
    Weird = {
        pub macro but_why() {}
        42
    },
}
```

This manages to hit a parent in the type namespace which is not `mod`ule.

Comment (jyn514) [reply src/librustdoc/visit_ast.rs:113]: Oh nice, good catch 😆 I don't think that needs to be supported here, but it would be nice to have a test to show the current behavior.

**Comment by danielhenrymantilla** [comment]
Okay, I think this PR is as good as it can get (modulo `rustc_privacy` changes which somebody more knowledgeable ought to review, cc @petrochenkov: I tried to follow the comments you told me by PM, so I _think_ it's okay), meaning that this PR is definitely no longer waiting on me (modulo a rebase a squash I'll do once reviewers confirm this PR is good; I try to avoid rewriting history while a review is in process since it makes stuff less readable). cc @RalfJung @jyn514.

  - There is one outstanding issue, although our current `core/std` ecosystem does not hit it, which is beyond the scope of this PR: #80414. This is an issue of very low severity since it only applies to a potential documentation link failure when dealing with `#![no_core]` crates that rely on `rustc_builtin_macro`s.

___

Here are the possible approaches going forward:

  - This can be quickly merged, despite it showcasing a hack: indeed, such a hack has been thoroughly tested with crazier and crazier code (also, this PR changes to `rustc_privacy` may address #80523, although I haven't checked that).

      - I personally advocate for this 👆.

  - We can wait for #80415 to be merged, and then I can replace the `for` loop hack with the intended HIR query. At that point this PR should be both trivial and undoubtedly correct. This may delay merging this PR, however, which may, in turn, either delay the sabilization of the `raw_ref` macros, or have them moved at the crate root (imho, both of these outcomes are worse than temporarily relying on this duly tested hack).

  - Since, at some point, we should fully integrate macros within the HIR (this is the better long-term solution for which @petrochenkov advocates), we could skip these _ad-hoc_ fixes and directly tackle that one. Again, since I don't think that fully integrating macros within the HIR can be achieved quickly, this would delay any other fixes, which is not ideal.

      - That being said, I'd be willing to try tackling this big feat with some tutoring from somebody more knowledgeable (which, again, seems to be @petrochenkov 😅), precisely to get more people to know the macro internals, and reduce the current 🚌 factor 😄.

**Comment by RalfJung** [comment]
> We can wait for #80415 to be merged

That PR has been merged. :)

**Comment by danielhenrymantilla** [comment]
Hmm, it looks like that PR hasn't solved all the issues related to it: https://github.com/rust-lang/rust/issues/77828#issuecomment-755412078

File: src/librustdoc/visit_ast.rs [hunk 14]
```diff
@@ -61,20 +61,57 @@ impl<'a, 'tcx> RustdocVisitor<'a, 'tcx> {
...
+            //  - a `pub macro`.
+            // Only the last two need to be fixed, thus:
+            if def.ast.macro_rules {
+                top_level_module.macros.push((def, None));
+                continue 'exported_macros;
+            }
+            let tcx = self.cx.tcx;
+            /* Because of #77828 we cannot do the simpler:
+            let macro_parent_module = tcx.def_path(tcx.parent_module(def.hir_id).to_def_id());
+            // and instead have to do: */
```
Comment (jyn514) [inline src/librustdoc/visit_ast.rs:89]: This still can't be fixed because of https://github.com/rust-lang/rust/issues/77828#issuecomment-755412078 ?

File: src/librustdoc/visit_ast.rs [hunk 15]
```diff
@@ -61,20 +61,57 @@ impl<'a, 'tcx> RustdocVisitor<'a, 'tcx> {
...
+                    rustc_hir::definitions::DefPathData::TypeNs(symbol) => symbol,
+                    _ => continue 'exported_macros,
+                };
+                // Descend into the child module that matches this path segment (if any).
+                match cur_mod.mods.iter_mut().find(|child| child.name == Some(path_segment_ty_ns)) {
+                    Some(child_mod) => cur_mod = &mut *child_mod,
+                    None => continue 'exported_macros,
+                }
+            }
+            cur_mod.macros.push((def, None));
```
Comment (jyn514) [inline src/librustdoc/visit_ast.rs:111]: Can you add an assertion that this ended up with the right module? Note that this whole hack with the loop is only necessary because rustdoc uses a separate `doctree::Module` type, if it used `hir::Module` directly we could check [`tcx.hir().expect_item(macro_parent_module_id)`](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_middle/hir/map/struct.Map.html#method.expect_item) instead.

You'll need to move `tcx.parent(def.hir_id)` to a separate variable, since I don't think you can get the Id back from a `DefPath`.
```suggestion
            assert_eq!(cur_mod.id, macro_parent_module_id);
            cur_mod.macros.push((def, None));
```

**Review by jyn514 — COMMENTED** [review]
> This can be quickly merged, despite it showcasing a hack: indeed, such a hack has been thoroughly tested with crazier and crazier code (also, this PR changes to rustc_privacy may address #80523, although I haven't checked that).

I agree this is what we should do.

> We can wait for #80415 to be merged, and then I can replace the for loop hack with the intended HIR query. At that point this PR should be both trivial and undoubtedly correct. This may delay merging this PR, however, which may, in turn, either delay the sabilization of the raw_ref macros, or have them moved at the crate root (imho, both of these outcomes are worse than temporarily relying on this duly tested hack).

I don't think the new PR will help, other than letting you remove `tcx.parent` in favor of `tcx.parent_module`. See my comment about `doctree::Module` below.

> Since, at some point, we should fully integrate macros within the HIR (this is the better long-term solution for which petrochenkov advocates), we could skip these ad-hoc fixes and directly tackle that one. Again, since I don't think that fully integrating macros within the HIR can be achieved quickly, this would delay any other fixes, which is not ideal.

I agree this is too much work to be worth blocking `std::ptr::raw_const!` on. I still think this should be fixed before stabilizing `pub macro`, though.

I left a few review comments, but mostly this is just waiting for @petrochenkov to sign off on the rustc_privacy changes.

File: src/librustdoc/visit_ast.rs (hunk 14 above)
Comment (danielhenrymantilla) [reply src/librustdoc/visit_ast.rs:89]: Correct, it still fails for `pub macro`s defined inside a `const` def or an `fn` def.

File: src/librustdoc/visit_ast.rs [hunk 16]
```diff
@@ -61,20 +61,60 @@ impl<'a, 'tcx> RustdocVisitor<'a, 'tcx> {
...
+                    _ => continue 'exported_macros,
+                };
+                // Descend into the child module that matches this path segment (if any).
+                match cur_mod.mods.iter_mut().find(|child| child.name == Some(path_segment_ty_ns)) {
+                    Some(child_mod) => cur_mod = &mut *child_mod,
+                    None => continue 'exported_macros,
+                }
+            }
+            let cur_mod_def_id = tcx.hir().local_def_id(cur_mod.id).to_def_id();
+            assert_eq!(cur_mod_def_id, macro_parent_def_id);
```
Comment (jyn514) [inline src/librustdoc/visit_ast.rs:113]: Now that you added the comment, I think this isn't true in general and there will be times the assertion fails, because `cur_mod_def_id` is *always* a module and `macro_parent` may not be. I think looking for the nearest module is the correct behavior.

Comment (danielhenrymantilla) [reply src/librustdoc/visit_ast.rs:113]: Technically that should be caught by the loop logic: if one of the ancestors is not a module, we will be hitting one of the two `continue 'exported macros;` bail points, and thus never reach that part of the code. That being said, I am open to suggestions to make these things clearer (_e.g._, we could `.try_fold()` and `Err` rather than `for + continue` 🤷)

Comment (jyn514) [reply src/librustdoc/visit_ast.rs:113]: Ok, but wouldn't it be simpler to only look up the parent module in the first place? Then you wouldn't have to skip the segments you don't care about, because you care about all of them.

Comment (danielhenrymantilla) [reply src/librustdoc/visit_ast.rs:113]: We could add a "fail faster" branch where we'd compare the immediate parent and the parent module, and bail if they're not equal; but even then we'd still need to check that that module in and of itself is reachable / nameable, so most of the logic would still be here. I think the micro optimization is not worth the extra branch; but I keep thinking that a `try_fold()` for the inner loop may be interesting, since it avoids the need to `continue` the `'outer` loop:

<details><summary>Example (assuming postfix <code>match</code> for the ergonomics)</summary>

```rust
for def in krate.exported_macros {
    let put_macro_in = |module| module.macros.push((def, None));
    // The `def` of a macro in `exported_macros` should correspond to either:
    //  - a `#[macro_export] macro_rules!` macro,
    //  - a built-in `derive` (or attribute) macro such as the ones in `::core`,
    //  - a `pub macro`.
    // Only the last two need to be fixed, thus:
    if def.ast.macro_rules {
        put_macro_in(&mut top_level_module);
        continue;
    }
    let tcx = self.cx.tcx;
    // Note: this is not the same as `.parent_module()`. Indeed, the latter looks
    // for the closest module _ancestor_, which is not necessarily a direct parent
    // (since a direct parent isn't necessarily a module, c.f. #77828).
    let macro_parent_def_id = {
        use rustc_middle::ty::DefIdTree;
        tcx.parent(tcx.hir().local_def_id(def.hir_id).to_def_id()).unwrap()
    };
    let macro_parent_path = tcx.def_path(macro_parent_def_id);
    // HACK: rustdoc has no way to lookup `doctree::Module`s by their HirId. Instead,
    // lookup the module by its name, by looking at each path segment one at a time.
    macro_parent_path.data.try_fold(&mut top_level_module, |(cur_mod, path_segment)| {
        // Path segments may refer to a module (in which case they belong to the type
        // namespace), which is _necessary_ for the macro to be accessible outside it
        // (no "associated macros" as of yet). Else we bail.
        let path_segment_ty_ns = match path_segment.data {
            rustc_hir::definitions::DefPathData::TypeNs(symbol) => symbol,
            _ => return Err(()),
        };
        // Descend into the child module that matches this path segment, if any.
        cur_mod.mods.iter_mut().find(|child| child.name == Some(path_segment_ty_ns)).ok_or(())
    }).match {
        Ok(module) => {
            let module_def_id =
                tcx.hir().local_def_id(module.id).to_def_id()
            ;
            assert_eq!(module_def_id, macro_parent_def_id);
            put_macro_in(&mut module);
        },
        Err(()) => continue,
    }
}
```

</details>

Comment (jyn514) [reply src/librustdoc/visit_ast.rs:113]: Hmm, ok. I'm fine with either the current code or the try_fold.

**Review by jyn514 — APPROVED** [review]
r=me once Petrochenkov signs off on the resolve changes.

File: compiler/rustc_privacy/src/lib.rs [hunk 17]
```diff
@@ -832,10 +832,15 @@ impl Visitor<'tcx> for EmbargoVisitor<'tcx> {
...
+        // Non-opaque macros cannot make other items more accessible than they already are.
         if attr::find_transparency(&self.tcx.sess, &md.attrs, md.ast.macro_rules).0
             != Transparency::Opaque
         {
-            self.update(md.hir_id, Some(AccessLevel::Public));
+            // `#[macro_export]`-ed `macro_rules!` are `Public` since they
+            // ignore their containing path to always appear at the crate root.
+            if md.ast.macro_rules {
+                self.update(md.hir_id, Some(AccessLevel::Public));
+            }
```
Comment (petrochenkov) [inline compiler/rustc_privacy/src/lib.rs:843]: In theory `#[rustc_macro_transparency = "transparent"] pub macro foo { ... }` is also possible and needs `update` called, but that's not a case used by the standard library, and all of this is a hack anyway, so it should be ok for now.

**Comment by petrochenkov** [comment]
I'm ok with this.
r? @jyn514
