### PR TITLE
Document that calling Drop, even after it panics, is UB

### LINKED ISSUE #60822: Drop impl of Vec is not idempotent and this is not documented
#60611 shows that the `Drop` impl of `Vec` is not idempotent. That is, if `Drop` fails, the `Vec` is left in an "un-droppable" state, and trying to re-drop the vector invokes undefined behavior - that is, the vector must be leaked.

It might be possible to make it idempotent without adding significant overhead [0], but I don't know whether we should do this. I think we should be clearer about whether the `Drop` impl of a type is idempotent or not, since making the wrong assumption can lead to UB, so I believe we should document this somewhere.

We could document this for the `Vec` type, but maybe this can also be something that can be documented at the top of the `libcore`/`liballoc`/`libstd` crates for all types (e.g. `Drop` impls of standard types are not idempotent). 

---

[0] Maybe setting the vector `len` field to zero before dropping the slice elements and having the `Drop` impl of `RawVec` set the capacity to zero before exiting is enough to avoid trying to re-drop the elements or trying to deallocate the memory (which is always freed on the first drop attempt).

### PR DESCRIPTION
**Pull request by Mark-Simulacrum**
Fixes #60822.

r? @gnzlbg

### CODE REVIEW

**Review by gnzlbg — APPROVED** [review]
LGTM.

Related: https://github.com/rust-lang/reference/issues/348

cc @RalfJung @Centril @tmandry

File: src/libcore/ops/drop.rs [hunk 1]
```diff
@@ -99,9 +99,15 @@ pub trait Drop {
     /// Given that a [`panic!`] will call `drop` as it unwinds, any [`panic!`]
     /// in a `drop` implementation will likely abort.
     ///
+    /// Note that even if this panics, the value is considered to be dropped;
+    /// you cannot cause it to be called again. This is normally automatically
```
Comment (RalfJung) [inline src/libcore/ops/drop.rs]:
```suggestion
    /// you must not cause `drop` to be called again. This is normally automatically
```
"it" could be the value here (makes no sense semantically, but still)

**Comment by RalfJung** [comment]
LGTM with the nit fixed.

**Comment by Mark-Simulacrum** [comment]
@bors r=RalfJung

Squashed the fixup commit.
