### PR TITLE
Reimplement NormalizeArrayLen based on SsaLocals

### LINKED ISSUE #105929: `NormalizeArrayLen` MIR opt unsound due to missed writes
The opt, as written today, will miscompile something that looks like this:

```
slice_ptr = Cast(array_ptr);
r = &mut slice_ptr;
*r = something_else;
Len(slice_ptr)
```

The bug is roughly on this line: https://github.com/rust-lang/rust/blob/696563efc5c3c0d87a601dff22966d2c5eb20a5e/compiler/rustc_mir_transform/src/normalize_array_len.rs#L270

This makes an attempt to detect other writes to the `slice_ptr` local, but it misses a lot of cases. Taking a reference like in the example above is an easy one, but `SetDiscriminant` is also missed, as well as writes to any aliasing pointers.

As far as I can tell this needs `Rvalue::Cast` support in custom MIR to reproduce.

@rustbot label A-mir-opt T-compiler requires-nightly

### PR DESCRIPTION
**Pull request by cjgillot**
Based on https://github.com/rust-lang/rust/pull/106908
Fixes https://github.com/rust-lang/rust/issues/105929

Only the last commit "Reimplement NormalizeArrayLen" is relevant.

### CODE REVIEW

File: compiler/rustc_mir_transform/src/normalize_array_len.rs [hunk 1]
```diff
@@ -1,288 +1,105 @@
...
+use rustc_middle::ty::{self, TyCtxt};
+use rustc_mir_dataflow::impls::borrowed_locals;
 
 pub struct NormalizeArrayLen;
 
 impl<'tcx> MirPass<'tcx> for NormalizeArrayLen {
     fn is_enabled(&self, sess: &rustc_session::Session) -> bool {
         // See #105929
-        sess.mir_opt_level() >= 4 && sess.opts.unstable_opts.unsound_mir_opts
+        sess.mir_opt_level() >= 3
```
Comment (nagisa) [inline compiler/rustc_mir_transform/src/normalize_array_len.rs:17]: Shouldn’t the comment above be removed at this point?

File: compiler/rustc_mir_transform/src/normalize_array_len.rs [hunk 2]
```diff
@@ -1,288 +1,105 @@
...
+                CastKind::Pointer(ty::adjustment::PointerCast::Unsize),
+                operand,
+                cast_ty,
+            ) => {
+                let operand_ty = operand.ty(body, tcx);
+                debug!(?operand_ty);
+                if let Some(operand_ty) = operand_ty.builtin_deref(true)
+                    && let ty::Array(_, len) = operand_ty.ty.kind()
+                    && let Some(cast_ty) = cast_ty.builtin_deref(true)
+                    && let ty::Slice(..) = cast_ty.ty.kind()
```
Comment (nagisa) [inline compiler/rustc_mir_transform/src/normalize_array_len.rs:57]: (This is just me trying to understand code rather than suggesting any particular change to be made – you can largely ignore this.) Is this check necessary at all? I guess it is a nice defense-in-depth measure, but what other things an unsizing cast could be to? A dynamic object?

**Review by nagisa — COMMENTED** [review]
The last commit seems reasonable to me!

r=me (with the issue link removed and the prerequisite PR landed)

File: compiler/rustc_mir_transform/src/normalize_array_len.rs (hunk 2 above)
Comment (cjgillot) [reply compiler/rustc_mir_transform/src/normalize_array_len.rs:57]: Yes, `Unsize` has to be interpreted based on both input and output types. We only want `&[T; _] -> &[T]`. The other possible cases are `&T -> &dyn Trait`, `&dyn Trait1 -> &dyn Trait2`, `Struct<[T; _]> -> Struct<[T]>`.
