### PR TITLE
Skip cleanups on unsupported targets

### LINKED ISSUE #140293: Exception handling instructions emitted on wasm even when exception-handling feature is disabled
I tried this code:

```rust
pub extern "C-unwind" fn gzgetc() -> i32 {
    42
}

pub extern "C-unwind" fn gzgetc_() -> i32 {
    gzgetc()
}

fn main() {
    for gzgetc_fn in [gzgetc, gzgetc_] {
        // gzgetc on a null file handle should return -1.
        assert_eq!(gzgetc_fn(), -1);
    }
}
```

compiled for wasm32-wasip1 or wasm32-unknown-unknown without `-Ctarget-feature=exception-handling`.

I expected to see this happen: No exception handling instructions emitted

Instead, this happened: `catch_call` is emitted for `gzgetc_fn()` when opt-level < 2.

### Meta

`rustc --version --verbose`: Both 1.86 and nightly

This is causing failure to run on Wasmtime in some cases: https://github.com/trifectatechfoundation/zlib-rs/pull/352#issuecomment-2829049152

### PR DESCRIPTION
**Pull request by alexcrichton**
This commit is an update to the `AbortUnwindingCalls` MIR pass in the compiler. Specifically a new boolean is added for "can this target possibly unwind" and if that's `false` then terminators are all adjusted to be unreachable/not present. The end result is that this fixes rust-lang/rust#140293 for wasm targets.

The motivation for this PR is that currently on WebAssembly targets the usage of the `C-unwind` ABI can lead LLVM to either (a) emit exception-handling instructions or (b) hit a LLVM-ICE-style codegen error. WebAssembly as a base instruction set does not support unwinding at all, and a later proposal to WebAssembly, the exception-handling proposal, was what enabled this. This means that the current intent of WebAssembly targets is that they maintain the baseline of "don't emit exception-handling instructions unless enabled". The commit here is intended to restore this behavior by skipping these instructions even when `C-unwind` is present.

Exception-handling is a relatively tricky and also murky topic in WebAssembly, however. There are two sets of instructions LLVM can emit for WebAssembly exceptions, Rust's Emscripten target supports exceptions, WASI targets do not, the LLVM flags to enable this are not always obvious, and additionally this all touches on "changing exception-handling behavior should be a target-level concern, not a feature". Effectively WebAssembly's exception-handling integration into Rust is not finalized at this time. The best idea at this time is that a parallel set of targets will eventually be added which support exceptions, but it's not clear if/when to do this. In the meantime the goal is to keep existing targets working while still enabling experimentation with exception-handling with `-Zbuild-std` and various permutations of LLVM flags.

To that extent this commit does not blanket disable these landing pads and cleanup routines for WebAssembly but instead checks to see if panic=unwind is enabled or if `+exception-handling` is enabled. Tests are updated here as well to account for this where, by default, using a `C-unwind` ABI won't affect Rust codegen at all. If `+exception-handling` is enabled, however, then Rust codegen will look like native platforms where exceptions are caught and the program aborts. More-or-less I've done my best to keep exceptions working on wasm where it's possible to have them work, but turned them off where they're not supposed to be emitted.

Closes rust-lang/rust#140293

### CODE REVIEW

**Comment by alexcrichton** [comment]
ping @bjorn3 would you be ok taking a look at this?

File: tests/codegen-llvm/wasm_exceptions.rs [hunk 1]
```diff
@@ -51,23 +57,40 @@ pub fn test_rtry() {
...
 // Make sure the intrinsic is not inferred as nounwind. This is a regression test for #132416.
-// CHECK-LABEL: @test_intrinsic() {{.*}} @__gxx_wasm_personality_v0
+//
+// Note that this test uses the raw `wasm_throw` intrinsic because the one from
+// libstd was built with `-Cpanic=abort` and it's technically not valid to use
+// when this crate is compiled with `-Cpanic=unwind`.
+//
+// WASMEXN-LABEL: @test_intrinsic() {{.*}} @__gxx_wasm_personality_v0
 #[no_mangle]
+#[cfg(wasmexn)]
```
Comment (bjorn3) [inline tests/codegen-llvm/wasm_exceptions.rs:81]: Is lowercase correct here or does it need to be upper case like the revision name you specified?

Comment (alexcrichton) [reply tests/codegen-llvm/wasm_exceptions.rs:81]: Just confirmed yeah, it's lowercase here.
