### PR TITLE
Fix suppression of `unused_assignment` in binding of `unused_variable`

### LINKED ISSUE #151514: Unexpected warning about unused assignment in Rust 1.92 and newer
### Code

I tried this code, which is using the [docsplay](https://github.com/bugadani/docsplay/tree/main) crate:

```rust
#[derive(docsplay::Display)]
pub enum DocsplayError {
    /// Use field a: {a}, but not b.
    A { a: usize, b: usize },
    /// Generic error in a tuple
    B(usize),
}
```

I expected to see this happen: 

This code should compile, and no warning should be shown.

Instead, this happened: 

I get a warning about an unused assignment:

```
warning: value assigned to `b` is never read
 --> src/lib.rs:4:19
  |
4 |     A { a: usize, b: usize },
  |                   ^
  |
  = help: maybe it is overwritten before being read?
  = note: `#[warn(unused_assignments)]` (part of `#[warn(unused)]`) on by default
```

This is unexpected, because there is no visible assignment anywhere. The expanded code for the macro looks like this:

```rust
// Expanded version of above code

pub enum DocsplayErrorExpanded {
    /// Use field a: {a}, but not b.
    A { a: usize, b: usize },
    /// Generic error in a tuple
    B(usize),
}
impl ::core::fmt::Display for DocsplayErrorExpanded {
    fn fmt(&self, formatter: &mut ::core::fmt::Formatter) -> ::core::fmt::Result {
        #[allow(unused_imports)]
        use ::docsplay::{DisplayToDisplayDoc, PathToDisplayDoc};
        #[allow(unused_variables)]
        match self {
            Self::A { a, b } => formatter.write_fmt(format_args!(
                "Use field a: {0}, but not b.",
                (&(a)).__displaydoc_display(),
            )),
            Self::B(_0) => formatter.write_fmt(format_args!("Generic error in a tuple")),
        }
    }
}

```

There is ` #[allow(unused_variables)]`, which means that the unused field b does not trigger that warning, but it is unexpected that the `unused_assignments` warning is triggered.

### Version it worked on

It most recently worked on: 1.91

### Version with regression

`rustc --version --verbose`:
```
rustc 1.92.0 (ded5c06cf 2025-12-08)
binary: rustc
commit-hash: ded5c06cf21d2b93bffd5d884aa6e96934ee4234
commit-date: 2025-12-08
host: x86_64-unknown-linux-gnu
release: 1.92.0
LLVM version: 21.1.3
```
Also seems to happen on the latest nighly,, `rustc 1.95.0-nightly (eda76d9d1 2026-01-21)`.

### Backtrace

<details><summary>Backtrace</summary>
<p>

```
<backtrace>
```

</p>
</details>

### PR DESCRIPTION
**Pull request by eggyal**
Unused assignments to an unused variable should trigger only the `unused_variables` lint and not also the `unused_assignments` lint. This was previously implemented by checking whether the span of the assignee was within the span of the binding pattern, however that failed to capture situations was imported from elsewhere (eg from the input tokenstream of a proc-macro that generates the binding pattern).

By comparing the span of the assignee to those of the variable introductions instead, a reported stable-to-stable regression is resolved.

This fix also impacted some other preexisting tests, which had (undesirably) been triggering both the `unused_variables` and `unused_assignments` lints on the same initializing assignment; those tests have therefore now been updated to expect only the former lint.

Fixes rust-lang/rust#151514
r? cjgillot (as author of reworked liveness testing in rust-lang/rust#142390)

### CODE REVIEW

File: tests/ui/pattern/bindings-after-at/bind-by-copy.rs [hunk 1]
```diff
@@ -53,7 +53,6 @@ pub fn main() {
     }
     match (E::E { a: 10, e: C { c: 20 } }) {
         mut x @ E::E{ a, e: C { mut c } } => {
-            //~^ WARN value assigned to `a` is never read
```
Comment (eggyal) [inline tests/ui/pattern/bindings-after-at/bind-by-copy.rs:56]: This line does still trigger the `unused_variables` lint in respect of `a`, but that lint is allowed by the test and so is not shown here.  I'd be happy to enable it, but there are a bunch of other occasions in the test that would then trigger it (if enabled test-wide; of course I could just enable it for this scope).

File: compiler/rustc_mir_transform/src/liveness.rs [hunk 2]
```diff
@@ -986,7 +986,7 @@ impl<'a, 'tcx> AssignmentResult<'a, 'tcx> {
             // warn twice, for the unused local and for the unused assignment. Therefore, we remove
             // from the list of assignments the ones that happen at the definition site.
             statements.retain(|source_info, _| {
-                source_info.span.find_ancestor_inside(binding.pat_span).is_none()
+                !binding.introductions.iter().any(|intro| intro.span == source_info.span)
```
Comment (Tuntii) [inline compiler/rustc_mir_transform/src/liveness.rs:989]: This additional filter against binding.introductions makes sense, especially for proc-macro generated bindings where spans don’t line up lexically. It avoids double warnings without weakening the lint.

File: tests/ui/lint/unused/auxiliary/unused_assignment_proc_macro.rs [hunk 3]
```diff
@@ -0,0 +1,23 @@
...
+    let _struct = ts.next();
+    let name = ts.next().unwrap();
+    let TokenTree::Group(fields) = ts.next().unwrap() else { panic!() };
+    let mut fields = fields.stream().into_iter();
+    let field = fields.next().unwrap();
+
+    quote! {
+        impl Drop for $name {
+            fn drop(&mut self) {
+                let Self { $field } = self;
```
Comment (Tuntii) [inline tests/ui/lint/unused/auxiliary/unused_assignment_proc_macro.rs:19]: Without the fix, the compiler would incorrectly emit both unused_variables and unused_assignments. This test clearly asserts the intended behavior.

**Review by Tuntii — COMMENTED** [review]
The resulting diagnostics are more precise without weakening either lint.

*[View changes since this review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/rust/151556/d222ddc4d90743dfc1e53b610be8fc9d95893d2c..22b3f598821a7262e06f57542cdf146108709df2)*

**Comment by apiraino** [comment]
Beta backport accepted as per compiler team [on Zulip](https://rust-lang.zulipchat.com/#narrow/channel/238009-t-compiler.2Fmeetings/topic/.5Bweekly.5D.202026-02-12/near/573546115). A backport PR will be authored by the release team at the end of the current development cycle. Backport labels handled by them.

@rustbot label +beta-accepted
