### PR TITLE
fix #55972: Erroneous self arguments on bare functions emit subpar compilation error

### LINKED ISSUE #55972: Erroneous self arguments on bare functions emit subpar compilation error
When refactoring methods as bare functions and forgetting to remove the self argument, the compiler fails to parse the new function entirely instead of emitting a better error.

```
error: expected one of `::` or `:`, found `,`
    --> components/canvas_traits/webgl.rs:1000:10
     |
1000 |     &self,
     |          ^ expected one of `::` or `:` here
```

### PR DESCRIPTION
**Pull request by lcnr**
#55972 

r? @estebank

### CODE REVIEW

**Comment by Axary** [comment]
r? estebank

**Comment by Axary** [comment]
should work, should probably still improve the Error message

File: src/libsyntax/parse/parser.rs [hunk 1]
```diff
@@ -5385,11 +5385,16 @@ impl<'a> Parser<'a> {
 
     fn parse_fn_args(&mut self, named_args: bool, allow_variadic: bool)
                      -> PResult<'a, (Vec<Arg> , bool)> {
+        self.expect(&token::OpenDelim(token::Paren))?;
+
+        if let Ok(Some(_)) = self.parse_self_arg() {
+            return Err(self.fatal("unexpected `self` argument in bare function"))
```
Comment (estebank) [inline src/libsyntax/parse/parser.rs]: You can use the following here:

```
let mut err self.struct_span_err(self.prev_span, "unexpected `self` argument in bare function");
err.span_label(self.prev_span, "invalid argument in bare function");
return Err(err);
```

File: src/test/ui/bare-function-self.rs [hunk 2]
```diff
@@ -0,0 +1,15 @@
+// Copyright 2018 The Rust Project Developers. See the COPYRIGHT
+// file at the top-level directory of this distribution and at
+// http://rust-lang.org/COPYRIGHT.
+//
+// Licensed under the Apache License, Version 2.0 <LICENSE-APACHE or
+// http://www.apache.org/licenses/LICENSE-2.0> or the MIT license
+// <LICENSE-MIT or http://opensource.org/licenses/MIT>, at your
+// option. This file may not be copied, modified, or distributed
+// except according to those terms.
```
Comment (estebank) [inline src/test/ui/bare-function-self.rs]: The license is no longer needed.

**Review by estebank — CHANGES_REQUESTED** [review]
Could you rebase against latest master to remove the merge commit?

One nitpick, but the code changes look good.

Can you also add a test for the other case you mentioned in the ticket?

**Comment by Axary** [comment]
In my opinion it is not worth to handle invalid uses of `self` differently. To implement this I would probably change `parse_arg_general(&mut self, require_name: bool)` to `parse_arg_general(&mut self, require_name: bool, is_bare_fn: bool)`, which is somewhat ugly.

File: src/libsyntax/parse/parser.rs [hunk 3]
```diff
@@ -1824,6 +1824,14 @@ impl<'a> Parser<'a> {
     fn parse_arg_general(&mut self, require_name: bool) -> PResult<'a, Arg> {
         maybe_whole!(self, NtArg, |x| x);
 
+        if let Ok(Some(_)) = self.parse_self_arg() {
+            let mut err = self.struct_span_err(self.prev_span,
+                "unexpected `self` argument in function");
+            err.span_label(self.prev_span,
+                "`self` is only valid as the first argument of a trait function");
```
Comment (RalfJung) [inline src/libsyntax/parse/parser.rs]: This is misleading, it also works for inherent impls.

File: src/test/ui/invalid-self-argument/trait-fn.rs [hunk 4]
```diff
@@ -0,0 +1,11 @@
+struct Foo {}
+
+impl Foo {
+    fn c(foo: u32, self) {}
+    //~^ ERROR unexpected `self` argument in function
+    //~| NOTE `self` is only valid as the first argument of a trait function
```
Comment (RalfJung) [inline src/test/ui/invalid-self-argument/trait-fn.rs]: Since this is a function in an inherent impl, it would be nice if the error could emphasize here that the problem is that it must be the *first* argument.

Comment (Axary) [reply src/test/ui/invalid-self-argument/trait-fn.rs]: will fix

File: src/libsyntax/parse/parser.rs (hunk 3 above)
Comment (Axary) [reply src/libsyntax/parse/parser.rs]: will fix

Comment (Axary) [reply src/libsyntax/parse/parser.rs]: Should I rename this to

> `self` is only valid as the first argument of an associated function

File: src/test/ui/invalid-self-argument/trait-fn.rs (hunk 4 above)
Comment (RalfJung) [reply src/test/ui/invalid-self-argument/trait-fn.rs]: It's not a big deal, but still would be nice.

But I am not knowledgeable in the relevant APIs either.^^

File: src/libsyntax/parse/parser.rs (hunk 3 above)
Comment (RalfJung) [reply src/libsyntax/parse/parser.rs]: That seems accurate.
