### PR TITLE
Make "consider importing" consistent for macros

### LINKED ISSUE #112439: "Did you mean" for attributes should be the same style as functions
### Code

In the playground (which has a large number of dependencies already):

```Rust
#[instrument(skip_all)]
fn demo() {
    time::sleep();
}
```

### Current output

```none
error: cannot find attribute `instrument` in this scope
  --> src/main.rs:19:3
   |
19 | #[instrument(skip_all)]
   |   ^^^^^^^^^^
   |
   = help: consider importing one of these items:
           tracing::instrument
           tracing_attributes::instrument
```

```none
error[E0425]: cannot find function `sleep` in crate `time`
  --> src/main.rs:11:19
   |
11 |             time::sleep(Duration::from_millis(100)).await;
   |                   ^^^^^ not found in `time`
   |
help: consider importing one of these items
   |
1  + use libc::sleep;
   |
1  + use openssl_sys::sleep;
   |
1  + use std::thread::sleep;
   |
1  + use tokio::time::sleep;
```

### Desired output

The first block should match the second block:

```none
error: cannot find attribute `instrument` in this scope
  --> src/main.rs:19:3
   |
19 | #[instrument(skip_all)]
   |   ^^^^^^^^^^
   |
help: consider importing one of these items
   |
1  + use tracing::instrument;
   |
1  + use tracing_attributes::instrument;
```

(I'd also love it if the line between each `use` suggestions was gone, but that's an extra request.)

### Rationale and extra context

Consistency is nice. The playground uses a regex to make these into clickable suggestions, but the regex only matches the latter.

### Other cases

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by mu001999**
Fixes #112439

### CODE REVIEW

File: compiler/rustc_resolve/src/diagnostics.rs [hunk 1]
```diff
@@ -1364,13 +1365,20 @@ impl<'a, 'tcx> Resolver<'a, 'tcx> {
 
         let import_suggestions =
             self.lookup_import_candidates(ident, Namespace::MacroNS, parent_scope, is_expected);
+        let (span, found_use) =
+            if let Some(def_id) = parent_scope.module.nearest_parent_mod().as_local() {
+                UsePlacementFinder::check(krate, self.def_id_to_node_id[def_id])
+            } else {
+                (None, FoundUse::No)
+            };
```
Comment (petrochenkov) [inline compiler/rustc_resolve/src/diagnostics.rs:1373]: Nit: `if let` with two short alternatives typically looks better and more compact as a `match`.

**Comment by petrochenkov** [comment]
r=me with the nit addressed.
@rustbot author

**Comment by petrochenkov** [comment]
Thanks!
@bors r+
