### PR TITLE
Discard overflow obligations in `impl_may_apply`

### LINKED ISSUE #123493: requirement solver overflow involving `proptest::sugar::NamedArguments`
I have a full repro in https://github.com/SohumB/proptest_sugar_rustc_overflow, but the short version is, it seems like some cases of code that _look_ like an omitted type should be inferrable:

```rust
fn _foo<Error: Debug>() {
    todo!()
}

pub fn foo() {
    _foo();
}
```

while certain dependencies, leading to `proptest`, are in the compile pathway (I could only get it to reproduce via a weird dependency chain via a workspace and a couple of public crates), can lead `rustc` to an overflow:

```
error[E0275]: overflow evaluating the requirement `proptest::sugar::NamedArguments<(_, _, _), &(..., ..., ...)>: Debug`
  |
  = help: consider increasing the recursion limit by adding a `#![recursion_limit = "256"]` attribute to your crate (`pipeline`)
  = note: required for `proptest::sugar::NamedArguments<((_, _, _), _, _), &((_, _, _), _, _)>` to implement `Debug`
  = note: 126 redundant requirements hidden
  = note: required for `NamedArguments<((((((((((..., ..., ...), ..., ...), ..., ...), ..., ...), ..., ...), ..., ...), ..., ...), ..., ...), ..., ...), ..., ...), ...>` to implement `Debug`
  = note: the full name for the type has been written to '/home/sohum/versioned/xdi/ice_repro/target/debug/deps/pipeline-00f02624ad986c54.long-type-16626873074358915367.txt'
  = note: consider using `--verbose` to print the full type name to the console
```

If the dependency chain is altered in any way that I could divine, the expected error is output:

```
error[E0283]: type annotations needed
 --> foo/src/lib.rs:9:5
  |
9 |     _foo();
  |     ^^^^ cannot infer type of the type parameter `Error` declared on the function `_foo`
  |
  = note: cannot satisfy `_: Debug`
note: required by a bound in `_foo`
 --> foo/src/lib.rs:4:16
  |
4 | fn _foo<Error: Debug>() {
  |                ^^^^^ required by this bound in `_foo`
help: consider specifying the generic argument
  |
9 |     _foo::<Error>();
  |         +++++++++
```

### Meta

I've reproduced this bug both in `nightly-2024-04-05` and in `nightly-2024-03-12`.

`rustc --version --verbose`:
```
rustc 1.79.0-nightly (385fa9d84 2024-04-04)
binary: rustc
commit-hash: 385fa9d845dd326c6bbfd58c22244215e431948a
commit-date: 2024-04-04
host: x86_64-unknown-linux-gnu
release: 1.79.0-nightly
LLVM version: 18.1.2
```

### PR DESCRIPTION
**Pull request by compiler-errors**
Hacky fix for #123493. Throws away obligations that are overflowing in `impl_may_apply` when we recompute if an impl applies, since those will lead to fatal overflow if processed during fulfillment.

Something about #114811 (I think it's the predicate reordering) caused us to evaluate predicates differently in error reporting leading to fatal overflow, though I believe the underlying overflow is possible to hit since this code was rewritten to use fulfillment.

Fixes #123493

### CODE REVIEW

**Comment by compiler-errors** [comment]
r? types

File: compiler/rustc_trait_selection/src/traits/error_reporting/type_err_ctxt_ext.rs [hunk 1]
```diff
@@ -2398,12 +2398,12 @@ impl<'tcx> TypeErrCtxt<'_, 'tcx> {
                 if ambiguities.len() > 5 {
                     let infcx = self.infcx;
                     if !ambiguities.iter().all(|option| match option {
-                        DefId(did) => infcx.fresh_args_for_item(DUMMY_SP, *did).is_empty(),
```
Comment (compiler-errors) [inline compiler/rustc_trait_selection/src/traits/error_reporting/type_err_ctxt_ext.rs:2401]: This is a very strange way of computing `generics().count()`.

File: compiler/rustc_trait_selection/src/traits/error_reporting/type_err_ctxt_ext.rs [hunk 2]
```diff
@@ -2398,12 +2398,12 @@ impl<'tcx> TypeErrCtxt<'_, 'tcx> {
...
+                        DefId(did) => infcx.tcx.generics_of(*did).count() == 0,
                         ParamEnv(_) => true,
                     }) {
                         // If not all are blanket impls, we filter blanked impls out.
                         ambiguities.retain(|option| match option {
-                            DefId(did) => infcx.fresh_args_for_item(DUMMY_SP, *did).is_empty(),
+                            DefId(did) => infcx.tcx.generics_of(*did).count() == 0,
```
Comment (spastorino) [inline compiler/rustc_trait_selection/src/traits/error_reporting/type_err_ctxt_ext.rs:2406]: Just commenting to note that we do `.count() == 0` in some places and `.params.is_empty()` in other places, those two things are different as count considers parent_count and params is owns generics.
I was wondering should we maybe add `is_empty` and `is_own_empty` methods for the sake of making these things clear?.

File: compiler/rustc_trait_selection/src/traits/error_reporting/ambiguity.rs [hunk 3]
```diff
@@ -52,10 +53,21 @@ pub fn compute_applicable_impls_for_diagnostics<'tcx>(
...
-                Obligation::new(tcx, ObligationCause::dummy(), param_env, predicate)
-            }));
+            let obligations = tcx
+                .predicates_of(impl_def_id)
+                .instantiate(tcx, impl_args)
+                .into_iter()
+                .map(|(predicate, _)| {
+                    Obligation::new(tcx, ObligationCause::dummy(), param_env, predicate)
+                })
+                // Kinda hacky, but let's just throw away obligations that overflow.
```
Comment (spastorino) [inline compiler/rustc_trait_selection/src/traits/error_reporting/ambiguity.rs:63]: I was wondering if we should add a FIXME here or something and if you have some kind of thought about how we could potentially get rid of the "hack" at some point.

**Review by spastorino — COMMENTED** [review]
Left some comments but feel free to r=me as is or if you think we should add a FIXME just do it and r=me.

File: compiler/rustc_trait_selection/src/traits/error_reporting/ambiguity.rs (hunk 3 above)
Comment (spastorino) [reply compiler/rustc_trait_selection/src/traits/error_reporting/ambiguity.rs:63]: Yeah, at that point it will be obvious but maybe worth adding a `FIXME(next_solver)` or something like that

File: compiler/rustc_trait_selection/src/traits/error_reporting/type_err_ctxt_ext.rs (hunk 2 above)
Comment (compiler-errors) [reply compiler/rustc_trait_selection/src/traits/error_reporting/type_err_ctxt_ext.rs:2406]: I'll do this as a follow-up actually
