### PR TITLE
avoid recreating field_const vec

### LINKED ISSUE #150354: ICE `expected ConstKind::Value, got N/#1`
auto-reduced (treereduce-rust):
````rust
//@compile-flags: --edition=2024
#![feature(min_generic_const_args, adt_const_params)]

enum Option<T> {
    Some(T),
    None,
}

fn foo<const N: Option<u32>>() {}

fn bar<T, const N: u32>() {
    foo::<{ Some::<u32> { 0: N } }>;
}

````

<details><summary><strong>original code</strong></summary>
<p>

original:
````rust
#![feature(min_generic_const_args, adt_const_params)]


#[derive(Eq, PartialEq, std::marker::ConstParamTy)]
enum Option<T> {
    Some(T),
    None,
}
use Option::Some;

fn foo<const N: Option<u32>>() {}

trait Trait {
    #[type_const]
    const ASSOC: usize;
}

fn bar<T, const N: u32>() {
    // the initializer of `_0` is a `N` which is a legal const argument
    // so this is ok.
    foo::<{ Some::<u32> { 0: N } }>;

    // this is allowed as mgca supports uses of assoc consts in the
    // type system. ie `<T as Trait>::ASSOC` is a legal const argument
    foo::<{ Some::<u32> { 0: <T as Trait>::ASSOC } }>();

    // this on the other hand is not allowed as `N + 1` is not a legal
    // const argument
    foo::<{ Some::<u32> { 0: N + 1 } }>();
    //~^ ERROR: complex const arguments must be placed inside of a `const` block

    // this also is not allowed as generic parameters cannot be used
    // in anon const const args
    foo::<{ Some::<u32> { 0: const { N + 1 } } }>();
    //~^ ERROR: generic parameters may not be used in const operations
}

fn main() {}

````
</p>
</details>

Version information
````
rustc 1.94.0-nightly (efa32de15 2025-12-24)
binary: rustc
commit-hash: efa32de15b394620520f24781d8c55d4df6fa106
commit-date: 2025-12-24
host: x86_64-unknown-linux-gnu
release: 1.94.0-nightly
LLVM version: 21.1.8

````

Possibly related line of code:
https://github.com/rust-lang/rust/blob/efa32de15b394620520f24781d8c55d4df6fa106/compiler/rustc_middle/src/ty/consts.rs#L252-L264

Command:
`/home/matthias/.rustup/toolchains/master/bin/rustc --edition=2024`

<details><summary><strong>Program output</strong></summary>
<p>

```
warning: the feature `min_generic_const_args` is incomplete and may not be safe to use and/or cause compiler crashes
 --> /tmp/icemaker_global_tempdir.co1336ymRBvg/rustc_testrunner_tmpdir_reporting.HBliNFcGkwUu/mvce.rs:1:12
  |
1 | #![feature(min_generic_const_args, adt_const_params)]
  |            ^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: see issue #132980 <https://github.com/rust-lang/rust/issues/132980> for more information
  = note: `#[warn(incomplete_features)]` on by default

error[E0601]: `main` function not found in crate `mvce`
  --> /tmp/icemaker_global_tempdir.co1336ymRBvg/rustc_testrunner_tmpdir_reporting.HBliNFcGkwUu/mvce.rs:12:2
   |
12 | }
   |  ^ consider adding a `main` function to `/tmp/icemaker_global_tempdir.co1336ymRBvg/rustc_testrunner_tmpdir_reporting.HBliNFcGkwUu/mvce.rs`

error[E0741]: `Option<u32>` must implement `ConstParamTy` to be used as the type of a const generic parameter
 --> /tmp/icemaker_global_tempdir.co1336ymRBvg/rustc_testrunner_tmpdir_reporting.HBliNFcGkwUu/mvce.rs:8:17
  |
8 | fn foo<const N: Option<u32>>() {}
  |                 ^^^^^^^^^^^
  |
help: add `#[derive(ConstParamTy, PartialEq, Eq)]` to the enum
  |
3 + #[derive(ConstParamTy, PartialEq, Eq)]
4 | enum Option<T> {
  |

error: internal compiler error: /rustc-dev/efa32de15b394620520f24781d8c55d4df6fa106/compiler/rustc_middle/src/ty/consts.rs:258:18: expected ConstKind::Value, got N/#1


thread 'rustc' (3462691) panicked at /rustc-dev/efa32de15b394620520f24781d8c55d4df6fa106/compiler/rustc_middle/src/ty/consts.rs:258:18:
Box<dyn Any>
stack backtrace:
   0:     0x7fee48c5fda3 - <<std[8a52549f710fb415]::sys::backtrace::BacktraceLock>::print::DisplayBacktrace as core[9df9debe8b3ae22c]::fmt::Display>::fmt
   1:     0x7fee49410648 - core[9df9debe8b3ae22c]::fmt::write
   2:     0x7fee48c764f6 - <std[8a52549f710fb415]::sys::stdio::unix::Stderr as std[8a52549f710fb415]::io::Write>::write_fmt
   3:     0x7fee48c36548 - std[8a52549f710fb415]::panicking::default_hook::{closure#0}
   4:     0x7fee48c53c13 - std[8a52549f710fb415]::panicking::default_hook
   5:     0x7fee47c2d377 - std[8a52549f710fb415]::panicking::update_hook::<alloc[d3a84aa4019980d4]::boxed::Box<rustc_driver_impl[84ab8a953ff30580]::install_ice_hook::{closure#1}>>::{closure#0}
   6:     0x7fee48c53ef2 - std[8a52549f710fb415]::panicking::panic_with_hook
   7:     0x7fee47c6a4c1 - std[8a52549f710fb415]::panicking::begin_panic::<rustc_errors[699e0d49929a30bc]::ExplicitBug>::{closure#0}
   8:     0x7fee47c5aa06 - std[8a52549f710fb415]::sys::backtrace::__rust_end_short_backtrace::<std[8a52549f710fb415]::panicking::begin_panic<rustc_errors[699e0d49929a30bc]::ExplicitBug>::{closure#0}, !>
   9:     0x7fee47c57da9 - std[8a52549f710fb415]::panicking::begin_panic::<rustc_errors[699e0d49929a30bc]::ExplicitBug>
  10:     0x7fee47c884b1 - <rustc_errors[699e0d49929a30bc]::diagnostic::BugAbort as rustc_errors[699e0d49929a30bc]::diagnostic::EmissionGuarantee>::emit_producing_guarantee
  11:     0x7fee48237099 - rustc_middle[6c8ebc09c5dee75c]::util::bug::opt_span_bug_fmt::<rustc_span[f43d92d060b6ef6a]::span_encoding::Span>::{closure#0}
  12:     0x7fee48237222 - rustc_middle[6c8ebc09c5dee75c]::ty::context::tls::with_opt::<rustc_middle[6c8ebc09c5dee75c]::util::bug::opt_span_bug_fmt<rustc_span[f43d92d060b6ef6a]::span_encoding::Span>::{closure#0}, !>::{closure#0}
  13:     0x7fee482280fb - rustc_middle[6c8ebc09c5dee75c]::ty::context::tls::with_context_opt::<rustc_middle[6c8ebc09c5dee75c]::ty::context::tls::with_opt<rustc_middle[6c8ebc09c5dee75c]::util::bug::opt_span_bug_fmt<rustc_span[f43d92d060b6ef6a]::span_encoding::Span>::{closure#0}, !>::{closure#0}, !>
  14:     0x7fee45c3a3c4 - rustc_middle[6c8ebc09c5dee75c]::util::bug::bug_fmt
  15:     0x7fee48246a3d - <rustc_middle[6c8ebc09c5dee75c]::ty::consts::Const>::to_value
  16:     0x7fee48badca9 - rustc_ty_utils[4ecae0266dc2b209]::consts::destructure_const
  17:     0x7fee48634546 - rustc_query_impl[741bec1d205ed836]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[741bec1d205ed836]::query_impl::destructure_const::dynamic_query::{closure#2}::{closure#0}, rustc_middle[6c8ebc09c5dee75c]::query::erase::Erased<[u8; 24usize]>>
  18:     0x7fee48737e49 - <rustc_query_impl[741bec1d205ed836]::query_impl::destructure_const::dynamic_query::{closure#2} as core[9df9debe8b3ae22c]::ops::function::FnOnce<(rustc_middle[6c8ebc09c5dee75c]::ty::context::TyCtxt, rustc_middle[6c8ebc09c5dee75c]::ty::consts::Const)>>::call_once
  19:     0x7fee4865c4ca - rustc_query_system[d1e761e268b8884b]::query::plumbing::try_execute_query::<rustc_query_impl[741bec1d205ed836]::DynamicConfig<rustc_query_system[d1e761e268b8884b]::query::caches::DefaultCache<rustc_middle[6c8ebc09c5dee75c]::ty::consts::Const, rustc_middle[6c8ebc09c5dee75c]::query::erase::Erased<[u8; 24usize]>>, false, false, false>, rustc_query_impl[741bec1d205ed836]::plumbing::QueryCtxt, false>
  20:     0x7fee486d11c9 - rustc_query_impl[741bec1d205ed836]::query_impl::destructure_const::get_query_non_incr::__rust_end_short_backtrace
  21:     0x7fee482cded2 - <rustc_middle[6c8ebc09c5dee75c]::ty::print::pretty::FmtPrinter as rustc_middle[6c8ebc09c5dee75c]::ty::print::pretty::PrettyPrinter>::pretty_print_const_valtree
  22:     0x7fee48a26c7f - <rustc_trait_selection[5e395e029186e477]::error_reporting::TypeErrCtxt>::report_selection_error
  23:     0x7fee47565dfa - <rustc_trait_selection[5e395e029186e477]::error_reporting::TypeErrCtxt>::report_fulfillment_errors
  24:     0x7fee49dd7256 - rustc_hir_typeck[8cc08117c3dde91c]::typeck_with_inspect::{closure#0}
  25:     0x7fee49dcccf4 - rustc_query_impl[741bec1d205ed836]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[741bec1d205ed836]::query_impl::typeck::dynamic_query::{closure#2}::{closure#0}, rustc_middle[6c8ebc09c5dee75c]::query::erase::Erased<[u8; 8usize]>>
  26:     0x7fee497251f7 - rustc_query_system[d1e761e268b8884b]::query::plumbing::try_execute_query::<rustc_query_impl[741bec1d205ed836]::DynamicConfig<rustc_data_structures[ededeb3d82402ac5]::vec_cache::VecCache<rustc_span[f43d92d060b6ef6a]::def_id::LocalDefId, rustc_middle[6c8ebc09c5dee75c]::query::erase::Erased<[u8; 8usize]>, rustc_query_system[d1e761e268b8884b]::dep_graph::graph::DepNodeIndex>, false, false, false>, rustc_query_impl[741bec1d205ed836]::plumbing::QueryCtxt, false>
  27:     0x7fee49724ac9 - rustc_query_impl[741bec1d205ed836]::query_impl::typeck::get_query_non_incr::__rust_end_short_backtrace
  28:     0x7fee49b9b0f1 - <rustc_middle[6c8ebc09c5dee75c]::ty::context::TyCtxt>::par_hir_body_owners::<rustc_hir_analysis[6d86651e35dd2117]::check_crate::{closure#2}>::{closure#0}
  29:     0x7fee49b9ab03 - rustc_hir_analysis[6d86651e35dd2117]::check_crate
  30:     0x7fee4a2dee9b - rustc_interface[f52ab86d5a555b2e]::passes::analysis
  31:     0x7fee4a2deaf5 - rustc_query_impl[741bec1d205ed836]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[741bec1d205ed836]::query_impl::analysis::dynamic_query::{closure#2}::{closure#0}, rustc_middle[6c8ebc09c5dee75c]::query::erase::Erased<[u8; 0usize]>>
  32:     0x7fee4a60e766 - rustc_query_system[d1e761e268b8884b]::query::plumbing::try_execute_query::<rustc_query_impl[741bec1d205ed836]::DynamicConfig<rustc_query_system[d1e761e268b8884b]::query::caches::SingleCache<rustc_middle[6c8ebc09c5dee75c]::query::erase::Erased<[u8; 0usize]>>, false, false, false>, rustc_query_impl[741bec1d205ed836]::plumbing::QueryCtxt, false>
  33:     0x7fee4a60e336 - rustc_query_impl[741bec1d205ed836]::query_impl::analysis::get_query_non_incr::__rust_end_short_backtrace
  34:     0x7fee4a785011 - <rustc_interface[f52ab86d5a555b2e]::passes::create_and_enter_global_ctxt<core[9df9debe8b3ae22c]::option::Option<rustc_interface[f52ab86d5a555b2e]::queries::Linker>, rustc_driver_impl[84ab8a953ff30580]::run_compiler::{closure#0}::{closure#2}>::{closure#2} as core[9df9debe8b3ae22c]::ops::function::FnOnce<(&rustc_session[4724149daa9f2ace]::session::Session, rustc_middle[6c8ebc09c5dee75c]::ty::context::CurrentGcx, alloc[d3a84aa4019980d4]::sync::Arc<rustc_data_structures[ededeb3d82402ac5]::jobserver::Proxy>, &std[8a52549f710fb415]::sync::once_lock::OnceLock<rustc_middle[6c8ebc09c5dee75c]::ty::context::GlobalCtxt>, &rustc_data_structures[ededeb3d82402ac5]::sync::worker_local::WorkerLocal<rustc_middle[6c8ebc09c5dee75c]::arena::Arena>, &rustc_data_structures[ededeb3d82402ac5]::sync::worker_local::WorkerLocal<rustc_hir[d3cd5594ffcae9cc]::Arena>, rustc_driver_impl[84ab8a953ff30580]::run_compiler::{closure#0}::{closure#2})>>::call_once::{shim:vtable#0}
  35:     0x7fee4a5ce48a - rustc_interface[f52ab86d5a555b2e]::interface::run_compiler::<(), rustc_driver_impl[84ab8a953ff30580]::run_compiler::{closure#0}>::{closure#1}
  36:     0x7fee4a54c3ce - std[8a52549f710fb415]::sys::backtrace::__rust_begin_short_backtrace::<rustc_interface[f52ab86d5a555b2e]::util::run_in_thread_with_globals<rustc_interface[f52ab86d5a555b2e]::util::run_in_thread_pool_with_globals<rustc_interface[f52ab86d5a555b2e]::interface::run_compiler<(), rustc_driver_impl[84ab8a953ff30580]::run_compiler::{closure#0}>::{closure#1}, ()>::{closure#0}, ()>::{closure#0}::{closure#0}, ()>
  37:     0x7fee4a54c1a0 - <std[8a52549f710fb415]::thread::lifecycle::spawn_unchecked<rustc_interface[f52ab86d5a555b2e]::util::run_in_thread_with_globals<rustc_interface[f52ab86d5a555b2e]::util::run_in_thread_pool_with_globals<rustc_interface[f52ab86d5a555b2e]::interface::run_compiler<(), rustc_driver_impl[84ab8a953ff30580]::run_compiler::{closure#0}>::{closure#1}, ()>::{closure#0}, ()>::{closure#0}::{closure#0}, ()>::{closure#1} as core[9df9debe8b3ae22c]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  38:     0x7fee4a54a578 - <std[8a52549f710fb415]::sys::thread::unix::Thread>::new::thread_start
  39:     0x7fee43c9698b - <unknown>
  40:     0x7fee43d1a9cc - <unknown>
  41:                0x0 - <unknown>

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: please make sure that you have updated to the latest nightly

note: rustc 1.94.0-nightly (efa32de15 2025-12-24) running on x86_64-unknown-linux-gnu

note: compiler flags: -Z dump-mir-dir=dir

query stack during panic:
#0 [destructure_const] destructuring type level constant
#1 [typeck] type-checking `bar`
#2 [analysis] running analysis passes on crate `mvce`
end of query stack
error: aborting due to 3 previous errors; 1 warning emitted

Some errors have detailed explanations: E0601, E0741.
For more information about an error, try `rustc --explain E0601`.

```

</p>
</details>

@rustbot label +F-min_generic_const_args +F-adt_const_params

### LINKED ISSUE #150355: ICE `expected ConstKind::Value, got UnevaluatedConst `
may be dup of #150354 

auto-reduced (treereduce-rust):
````rust
//@compile-flags: --edition=2024
#![feature(generic_const_exprs)]
#![feature(min_generic_const_args, adt_const_params)]

enum Option<T> {
    Some(T),
    None,
}

fn foo<const N: Option<u32>>() {}

fn bar<T>() {
    foo::<{ Some::<u32> { 0: const {} } }>();
}

````

<details><summary><strong>original code</strong></summary>
<p>

original:
````rust
#![feature(min_generic_const_args, adt_const_params)]
#![expect(incomplete_features)]

#[derive(Eq, N1, std::marker::ConstParamTy)]
enum Option<T> {
    Some(T),
    None,
}
use Option::Some;

fn foo<const N: Option<u32>>() {}

trait Tr {
    #[type_const()]
    //~^ ERROR malformed
    //~| ERROR experimental
    const N: usize;
}

fn bar<T>() {
    // the initializer of `_0` is a `N` which is a legal const argument
    // so this is ok.
    foo::<{ Some::<u32> { 0: N } }>();

    // this is allowed as mgca supports uses of assoc consts in the
    // type system. ie `<T as Trait>::ASSOC` is a legal const argument
    foo::<{ Some::<u32> { 0: N + 1 } }>();

    // this on the other hand is not allowed as `N + 1` is not a legal
    // const argument
    foo::<{ Some::<u32> { 0: N + 1 } }>();
    //~^ ERROR: complex const arguments must be placed inside of a `const` block

    // this also is not allowed as generic parameters cannot be used
    // in anon const const args
    foo::<{ Some::<u32> { 0: const { N + 5_usize } } }>();
    //~^ ERROR: generic parameters may not be used in const operations
}

fn main() {}

````
</p>
</details>

Version information
````
rustc 1.94.0-nightly (efa32de15 2025-12-24)
binary: rustc
commit-hash: efa32de15b394620520f24781d8c55d4df6fa106
commit-date: 2025-12-24
host: x86_64-unknown-linux-gnu
release: 1.94.0-nightly
LLVM version: 21.1.8

````

Possibly related line of code:
https://github.com/rust-lang/rust/blob/efa32de15b394620520f24781d8c55d4df6fa106/compiler/rustc_middle/src/ty/consts.rs#L252-L264

Command:
`/home/matthias/.rustup/toolchains/master/bin/rustc --edition=2024 -Zcrate-attr=feature(generic_const_exprs)`

<details><summary><strong>Program output</strong></summary>
<p>

```
warning: the feature `min_generic_const_args` is incomplete and may not be safe to use and/or cause compiler crashes
 --> /tmp/icemaker_global_tempdir.co1336ymRBvg/rustc_testrunner_tmpdir_reporting.OZjcV00ko7Dn/mvce.rs:1:12
  |
1 | #![feature(min_generic_const_args, adt_const_params)]
  |            ^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: see issue #132980 <https://github.com/rust-lang/rust/issues/132980> for more information
  = note: `#[warn(incomplete_features)]` on by default

warning: the feature `generic_const_exprs` is incomplete and may not be safe to use and/or cause compiler crashes
 --> <crate attribute>:1:12
  |
1 | #![feature(generic_const_exprs)]
  |            ^^^^^^^^^^^^^^^^^^^
  |
  = note: see issue #76560 <https://github.com/rust-lang/rust/issues/76560> for more information

error[E0601]: `main` function not found in crate `mvce`
  --> /tmp/icemaker_global_tempdir.co1336ymRBvg/rustc_testrunner_tmpdir_reporting.OZjcV00ko7Dn/mvce.rs:12:2
   |
12 | }
   |  ^ consider adding a `main` function to `/tmp/icemaker_global_tempdir.co1336ymRBvg/rustc_testrunner_tmpdir_reporting.OZjcV00ko7Dn/mvce.rs`

error[E0741]: `Option<u32>` must implement `ConstParamTy` to be used as the type of a const generic parameter
 --> /tmp/icemaker_global_tempdir.co1336ymRBvg/rustc_testrunner_tmpdir_reporting.OZjcV00ko7Dn/mvce.rs:8:17
  |
8 | fn foo<const N: Option<u32>>() {}
  |                 ^^^^^^^^^^^
  |
help: add `#[derive(ConstParamTy, PartialEq, Eq)]` to the enum
  |
3 + #[derive(ConstParamTy, PartialEq, Eq)]
4 | enum Option<T> {
  |

error[E0308]: mismatched types
  --> /tmp/icemaker_global_tempdir.co1336ymRBvg/rustc_testrunner_tmpdir_reporting.OZjcV00ko7Dn/mvce.rs:11:36
   |
11 |     foo::<{ Some::<u32> { 0: const {} } }>();
   |                                    ^^ expected `u32`, found `()`

error: internal compiler error: /rustc-dev/efa32de15b394620520f24781d8c55d4df6fa106/compiler/rustc_middle/src/ty/consts.rs:258:18: expected ConstKind::Value, got UnevaluatedConst { def: DefId(0:14 ~ mvce[0f08]::bar::{constant#0}), args: [T/#0] }


thread 'rustc' (3462838) panicked at /rustc-dev/efa32de15b394620520f24781d8c55d4df6fa106/compiler/rustc_middle/src/ty/consts.rs:258:18:
Box<dyn Any>
stack backtrace:
   0:     0x7f77b285fda3 - <<std[8a52549f710fb415]::sys::backtrace::BacktraceLock>::print::DisplayBacktrace as core[9df9debe8b3ae22c]::fmt::Display>::fmt
   1:     0x7f77b3010648 - core[9df9debe8b3ae22c]::fmt::write
   2:     0x7f77b28764f6 - <std[8a52549f710fb415]::sys::stdio::unix::Stderr as std[8a52549f710fb415]::io::Write>::write_fmt
   3:     0x7f77b2836548 - std[8a52549f710fb415]::panicking::default_hook::{closure#0}
   4:     0x7f77b2853c13 - std[8a52549f710fb415]::panicking::default_hook
   5:     0x7f77b182d377 - std[8a52549f710fb415]::panicking::update_hook::<alloc[d3a84aa4019980d4]::boxed::Box<rustc_driver_impl[84ab8a953ff30580]::install_ice_hook::{closure#1}>>::{closure#0}
   6:     0x7f77b2853ef2 - std[8a52549f710fb415]::panicking::panic_with_hook
   7:     0x7f77b186a4c1 - std[8a52549f710fb415]::panicking::begin_panic::<rustc_errors[699e0d49929a30bc]::ExplicitBug>::{closure#0}
   8:     0x7f77b185aa06 - std[8a52549f710fb415]::sys::backtrace::__rust_end_short_backtrace::<std[8a52549f710fb415]::panicking::begin_panic<rustc_errors[699e0d49929a30bc]::ExplicitBug>::{closure#0}, !>
   9:     0x7f77b1857da9 - std[8a52549f710fb415]::panicking::begin_panic::<rustc_errors[699e0d49929a30bc]::ExplicitBug>
  10:     0x7f77b18884b1 - <rustc_errors[699e0d49929a30bc]::diagnostic::BugAbort as rustc_errors[699e0d49929a30bc]::diagnostic::EmissionGuarantee>::emit_producing_guarantee
  11:     0x7f77b1e37099 - rustc_middle[6c8ebc09c5dee75c]::util::bug::opt_span_bug_fmt::<rustc_span[f43d92d060b6ef6a]::span_encoding::Span>::{closure#0}
  12:     0x7f77b1e37222 - rustc_middle[6c8ebc09c5dee75c]::ty::context::tls::with_opt::<rustc_middle[6c8ebc09c5dee75c]::util::bug::opt_span_bug_fmt<rustc_span[f43d92d060b6ef6a]::span_encoding::Span>::{closure#0}, !>::{closure#0}
  13:     0x7f77b1e280fb - rustc_middle[6c8ebc09c5dee75c]::ty::context::tls::with_context_opt::<rustc_middle[6c8ebc09c5dee75c]::ty::context::tls::with_opt<rustc_middle[6c8ebc09c5dee75c]::util::bug::opt_span_bug_fmt<rustc_span[f43d92d060b6ef6a]::span_encoding::Span>::{closure#0}, !>::{closure#0}, !>
  14:     0x7f77af83a3c4 - rustc_middle[6c8ebc09c5dee75c]::util::bug::bug_fmt
  15:     0x7f77b1e46a3d - <rustc_middle[6c8ebc09c5dee75c]::ty::consts::Const>::to_value
  16:     0x7f77b27adca9 - rustc_ty_utils[4ecae0266dc2b209]::consts::destructure_const
  17:     0x7f77b2234546 - rustc_query_impl[741bec1d205ed836]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[741bec1d205ed836]::query_impl::destructure_const::dynamic_query::{closure#2}::{closure#0}, rustc_middle[6c8ebc09c5dee75c]::query::erase::Erased<[u8; 24usize]>>
  18:     0x7f77b2337e49 - <rustc_query_impl[741bec1d205ed836]::query_impl::destructure_const::dynamic_query::{closure#2} as core[9df9debe8b3ae22c]::ops::function::FnOnce<(rustc_middle[6c8ebc09c5dee75c]::ty::context::TyCtxt, rustc_middle[6c8ebc09c5dee75c]::ty::consts::Const)>>::call_once
  19:     0x7f77b225c4ca - rustc_query_system[d1e761e268b8884b]::query::plumbing::try_execute_query::<rustc_query_impl[741bec1d205ed836]::DynamicConfig<rustc_query_system[d1e761e268b8884b]::query::caches::DefaultCache<rustc_middle[6c8ebc09c5dee75c]::ty::consts::Const, rustc_middle[6c8ebc09c5dee75c]::query::erase::Erased<[u8; 24usize]>>, false, false, false>, rustc_query_impl[741bec1d205ed836]::plumbing::QueryCtxt, false>
  20:     0x7f77b22d11c9 - rustc_query_impl[741bec1d205ed836]::query_impl::destructure_const::get_query_non_incr::__rust_end_short_backtrace
  21:     0x7f77b1ecded2 - <rustc_middle[6c8ebc09c5dee75c]::ty::print::pretty::FmtPrinter as rustc_middle[6c8ebc09c5dee75c]::ty::print::pretty::PrettyPrinter>::pretty_print_const_valtree
  22:     0x7f77b2626c7f - <rustc_trait_selection[5e395e029186e477]::error_reporting::TypeErrCtxt>::report_selection_error
  23:     0x7f77b1165dfa - <rustc_trait_selection[5e395e029186e477]::error_reporting::TypeErrCtxt>::report_fulfillment_errors
  24:     0x7f77b3236362 - <rustc_hir_typeck[8cc08117c3dde91c]::fn_ctxt::FnCtxt>::check_expr_call
  25:     0x7f77b320c9f1 - <rustc_hir_typeck[8cc08117c3dde91c]::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
  26:     0x7f77b3207b3b - <rustc_hir_typeck[8cc08117c3dde91c]::fn_ctxt::FnCtxt>::check_expr_block
  27:     0x7f77b320c9cc - <rustc_hir_typeck[8cc08117c3dde91c]::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
  28:     0x7f77b31ed749 - rustc_hir_typeck[8cc08117c3dde91c]::check::check_fn
  29:     0x7f77b39ce379 - rustc_hir_typeck[8cc08117c3dde91c]::typeck_with_inspect::{closure#0}
  30:     0x7f77b39cccf4 - rustc_query_impl[741bec1d205ed836]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[741bec1d205ed836]::query_impl::typeck::dynamic_query::{closure#2}::{closure#0}, rustc_middle[6c8ebc09c5dee75c]::query::erase::Erased<[u8; 8usize]>>
  31:     0x7f77b33251f7 - rustc_query_system[d1e761e268b8884b]::query::plumbing::try_execute_query::<rustc_query_impl[741bec1d205ed836]::DynamicConfig<rustc_data_structures[ededeb3d82402ac5]::vec_cache::VecCache<rustc_span[f43d92d060b6ef6a]::def_id::LocalDefId, rustc_middle[6c8ebc09c5dee75c]::query::erase::Erased<[u8; 8usize]>, rustc_query_system[d1e761e268b8884b]::dep_graph::graph::DepNodeIndex>, false, false, false>, rustc_query_impl[741bec1d205ed836]::plumbing::QueryCtxt, false>
  32:     0x7f77b3324ac9 - rustc_query_impl[741bec1d205ed836]::query_impl::typeck::get_query_non_incr::__rust_end_short_backtrace
  33:     0x7f77b379b0f1 - <rustc_middle[6c8ebc09c5dee75c]::ty::context::TyCtxt>::par_hir_body_owners::<rustc_hir_analysis[6d86651e35dd2117]::check_crate::{closure#2}>::{closure#0}
  34:     0x7f77b379ab03 - rustc_hir_analysis[6d86651e35dd2117]::check_crate
  35:     0x7f77b3edee9b - rustc_interface[f52ab86d5a555b2e]::passes::analysis
  36:     0x7f77b3edeaf5 - rustc_query_impl[741bec1d205ed836]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[741bec1d205ed836]::query_impl::analysis::dynamic_query::{closure#2}::{closure#0}, rustc_middle[6c8ebc09c5dee75c]::query::erase::Erased<[u8; 0usize]>>
  37:     0x7f77b420e766 - rustc_query_system[d1e761e268b8884b]::query::plumbing::try_execute_query::<rustc_query_impl[741bec1d205ed836]::DynamicConfig<rustc_query_system[d1e761e268b8884b]::query::caches::SingleCache<rustc_middle[6c8ebc09c5dee75c]::query::erase::Erased<[u8; 0usize]>>, false, false, false>, rustc_query_impl[741bec1d205ed836]::plumbing::QueryCtxt, false>
  38:     0x7f77b420e336 - rustc_query_impl[741bec1d205ed836]::query_impl::analysis::get_query_non_incr::__rust_end_short_backtrace
  39:     0x7f77b4385011 - <rustc_interface[f52ab86d5a555b2e]::passes::create_and_enter_global_ctxt<core[9df9debe8b3ae22c]::option::Option<rustc_interface[f52ab86d5a555b2e]::queries::Linker>, rustc_driver_impl[84ab8a953ff30580]::run_compiler::{closure#0}::{closure#2}>::{closure#2} as core[9df9debe8b3ae22c]::ops::function::FnOnce<(&rustc_session[4724149daa9f2ace]::session::Session, rustc_middle[6c8ebc09c5dee75c]::ty::context::CurrentGcx, alloc[d3a84aa4019980d4]::sync::Arc<rustc_data_structures[ededeb3d82402ac5]::jobserver::Proxy>, &std[8a52549f710fb415]::sync::once_lock::OnceLock<rustc_middle[6c8ebc09c5dee75c]::ty::context::GlobalCtxt>, &rustc_data_structures[ededeb3d82402ac5]::sync::worker_local::WorkerLocal<rustc_middle[6c8ebc09c5dee75c]::arena::Arena>, &rustc_data_structures[ededeb3d82402ac5]::sync::worker_local::WorkerLocal<rustc_hir[d3cd5594ffcae9cc]::Arena>, rustc_driver_impl[84ab8a953ff30580]::run_compiler::{closure#0}::{closure#2})>>::call_once::{shim:vtable#0}
  40:     0x7f77b41ce48a - rustc_interface[f52ab86d5a555b2e]::interface::run_compiler::<(), rustc_driver_impl[84ab8a953ff30580]::run_compiler::{closure#0}>::{closure#1}
  41:     0x7f77b414c3ce - std[8a52549f710fb415]::sys::backtrace::__rust_begin_short_backtrace::<rustc_interface[f52ab86d5a555b2e]::util::run_in_thread_with_globals<rustc_interface[f52ab86d5a555b2e]::util::run_in_thread_pool_with_globals<rustc_interface[f52ab86d5a555b2e]::interface::run_compiler<(), rustc_driver_impl[84ab8a953ff30580]::run_compiler::{closure#0}>::{closure#1}, ()>::{closure#0}, ()>::{closure#0}::{closure#0}, ()>
  42:     0x7f77b414c1a0 - <std[8a52549f710fb415]::thread::lifecycle::spawn_unchecked<rustc_interface[f52ab86d5a555b2e]::util::run_in_thread_with_globals<rustc_interface[f52ab86d5a555b2e]::util::run_in_thread_pool_with_globals<rustc_interface[f52ab86d5a555b2e]::interface::run_compiler<(), rustc_driver_impl[84ab8a953ff30580]::run_compiler::{closure#0}>::{closure#1}, ()>::{closure#0}, ()>::{closure#0}::{closure#0}, ()>::{closure#1} as core[9df9debe8b3ae22c]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  43:     0x7f77b414a578 - <std[8a52549f710fb415]::sys::thread::unix::Thread>::new::thread_start
  44:     0x7f77ad89698b - <unknown>
  45:     0x7f77ad91a9cc - <unknown>
  46:                0x0 - <unknown>

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: please make sure that you have updated to the latest nightly

note: rustc 1.94.0-nightly (efa32de15 2025-12-24) running on x86_64-unknown-linux-gnu

note: compiler flags: -Z crate-attr=feature(generic_const_exprs) -Z dump-mir-dir=dir

query stack during panic:
#0 [destructure_const] destructuring type level constant
#1 [typeck] type-checking `bar`
#2 [analysis] running analysis passes on crate `mvce`
end of query stack
error: aborting due to 4 previous errors; 2 warnings emitted

Some errors have detailed explanations: E0308, E0601, E0741.
For more information about an error, try `rustc --explain E0308`.

```

</p>
</details>

@rustbot label +F-min_generic_const_args +F-adt_const_params +F-generic_const_exprs

### PR DESCRIPTION
**Pull request by Kivooeo**
r? BoxyUwU

fixes https://github.com/rust-lang/rust/issues/150354
fixes https://github.com/rust-lang/rust/issues/150355

### CODE REVIEW

File: compiler/rustc_middle/src/ty/print/pretty.rs [hunk 1]
```diff
@@ -1543,7 +1543,7 @@ pub trait PrettyPrinter<'tcx>: Printer<'tcx> + fmt::Write {
         match ct.kind() {
             ty::ConstKind::Unevaluated(ty::UnevaluatedConst { def, args }) => {
                 match self.tcx().def_kind(def) {
-                    DefKind::Const | DefKind::AssocConst => {
+                    DefKind::Const | DefKind::AssocConst | DefKind::Enum => {
```
Comment (Kivooeo) [inline compiler/rustc_middle/src/ty/print/pretty.rs]: so the only problem i dont know is this place, the problem that this fails in wildcard

```rust
defkind => bug!("`{:?}` has unexpected defkind {:?}", ct, defkind),
```

so i just randomly added a `DefKind::Enum` here :) well, it fixes the problem, but i don't know if this is correct or not

should i somehow separately handle it here?

File: compiler/rustc_ty_utils/src/consts.rs [hunk 2]
```diff
@@ -51,8 +51,13 @@ fn destructure_const<'tcx>(
 
             for (field, field_valtree) in iter::zip(fields, branches) {
                 let field_ty = field.ty(tcx, args);
-                let field_const =
-                    ty::Const::new_value(tcx, field_valtree.to_value().valtree, field_ty);
+                let field_const = match field_valtree.kind() {
```
Comment (BoxyUwU) [inline compiler/rustc_ty_utils/src/consts.rs]: you can get rid of this entire for loop actually as `field_consts` is just `branches` (we store a list of `ty::Const` where previously we used to store a list of `ValTree` hence this logic existing). no point in matching on a `ty::Const` just to recreate it exactly as it already is

File: compiler/rustc_middle/src/ty/print/pretty.rs (hunk 1 above)
Comment (BoxyUwU) [reply compiler/rustc_middle/src/ty/print/pretty.rs]: `DefKind::Enum` as the defid for an unevaluated const is completely nonsensical. Are you sure this is what fixed things? This change should be reverted and if we *are* winding up with a `DefKind::Enum` here then whatever lowering code is resulting in this should updated to use a different `DefId`

Comment (Kivooeo) [reply compiler/rustc_middle/src/ty/print/pretty.rs]: not sure what happened before but yeah, removed it and it fine, because i remember it pretty good (it was like hour or two ago), that i got `has unexpected defkind Enum` and after I added this `DefKind::Enum` it fixes the problem

File: compiler/rustc_ty_utils/src/consts.rs (hunk 2 above)
Comment (Kivooeo) [reply compiler/rustc_ty_utils/src/consts.rs]: something like this? (last changes)

File: compiler/rustc_ty_utils/src/consts.rs [hunk 3]
```diff
@@ -39,25 +39,16 @@ fn destructure_const<'tcx>(
...
-                let field_ty = field.ty(tcx, args);
-                let field_const =
-                    ty::Const::new_value(tcx, field_valtree.to_value().valtree, field_ty);
-                field_consts.push(field_const);
-            }
-            debug!(?field_consts);
+            debug!(?branches);
 
-            (field_consts, Some(variant_idx))
+            (branches.to_vec(), Some(variant_idx))
```
Comment (BoxyUwU) [inline compiler/rustc_ty_utils/src/consts.rs]:
```suggestion
            (field_consts.to_vec(), Some(variant_idx))
```

rename seems nicer

File: tests/ui/const-generics/mgca/not-only-value-150354-150355.rs [hunk 4]
```diff
@@ -0,0 +1,27 @@
+//! Regression test for <https://github.com/rust-lang/rust/issues/150354>
+//!                     <https://github.com/rust-lang/rust/issues/150355>
+//!
+//@ edition 2024
+
+#![allow(incomplete_features)]
+#![feature(min_generic_const_args, adt_const_params, generic_const_items, generic_const_exprs)]
```
Comment (BoxyUwU) [inline tests/ui/const-generics/mgca/not-only-value-150354-150355.rs]:
```suggestion
#![feature(min_generic_const_args, adt_const_params)]
```

dont think those feature gates should be necessary

**Review by BoxyUwU — COMMENTED** [review]
In theory we ought to make the same change to the match arms for handling arays/slices/tuples. They're currently doing the same `ty::Const::new_value(ct.to_value())` thing which they shouldn't be. I don't think it's possible to write a test case where this matters yet though (we would need mgca to have support for `hir::ConstArgKind::Array/Tuple` which it doesn't yet).

I feel like a more involved refactor could be nice. Specifically:
- Stop handling `Array`/`Slice`/`Tuple` in `destructure_const`
- Have all callers of `destructure_const` handle array/slice/tuples themselves by using the `branches` of the `ValTree`.
- Rename `destructure_const` and `ty::DestructuredConst` to `destructure_adt_const` and `ty::DestructuredAdtConst`

Would you be interested in doing that? Can either do so in this PR or a future PR if you like. I'm happy to just merge this PR without the proposed refactoring if you prefer.

*[View changes since this review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/rust/150380/1bf12c32a08384862297674921d1137ad94892dc..73aeea4dd39c09c644a22d2fd67ea47d2963860b)*

File: tests/ui/const-generics/mgca/printing_valtrees_supports_non_values.rs [hunk 5]
```diff
@@ -0,0 +1,27 @@
+//! Regression test for <https://github.com/rust-lang/rust/issues/150354>
```
Comment (BoxyUwU) [inline tests/ui/const-generics/mgca/printing_valtrees_supports_non_values.rs:1]: ah also can you rename this file. having the issue numbers doesn't feel that important to me, and `not-only-value` doesn't explain much. Maybe `printing_valtrees_supports_non_values.rs`

**Comment by Kivooeo** [comment]
> Would you be interested in doing that?

sure, I'd be happy to look into this refactor in the follow up PRs

File: tests/ui/const-generics/mgca/printing_valtrees_supports_non_values.rs (hunk 5 above)
Comment (Kivooeo) [reply tests/ui/const-generics/mgca/printing_valtrees_supports_non_values.rs:1]: yeah the test name was the thing i'd spent most time on and ended up with this, forget to say that this part is need some help, so thanks for catching this up

File: tests/ui/const-generics/mgca/printing_valtrees_supports_non_values.rs [hunk 6]
```diff
@@ -0,0 +1,26 @@
...
+
+enum Option<T> {
+    Some(T),
+    None,
+}
+
+fn foo<const N: Option<u32>>() {} //~ ERROR `Option<u32>` must implement `ConstParamTy` to be used as the type of a const generic parameter [E0741]
+
+fn bar<T>() {
+    foo::<{ Some::<u32> { 0: const {} } }>();
```
Comment (BoxyUwU) [inline tests/ui/const-generics/mgca/printing_valtrees_supports_non_values.rs]: I've just realised *this* part of the test did need GCE to ICE :thinking: 
```suggestion
    foo::<{ Some::<u32> { 0: <T as Trait>::ASSOC } }>();
```
This should ICE without GCE and give the same ICE message. You'll need to add some `trait Trait { #[type_const] const ASSOC: usize; }` though.

I think `foo::<{ Some::<u32> { 0: _ } }>();`

should be another slightly different test case, can add this too

File: tests/ui/const-generics/mgca/printing_valtrees_supports_non_values.rs [hunk 7]
```diff
@@ -0,0 +1,26 @@
...
+//!
+//@ edition 2024
+
+#![allow(incomplete_features)]
+#![feature(min_generic_const_args, adt_const_params)]
+
+enum Option<T> {
+    Some(T),
+    None,
+}
```
Comment (BoxyUwU) [inline tests/ui/const-generics/mgca/printing_valtrees_supports_non_values.rs]:
```suggestion
#[derive(Eq, PartialEq, core::marker::ConstParamTy)]
struct Foo;
```
A lot of the type mismatches are kind of confusing because its to do with `crate::Option` vs `core::Option`. I think this will make it a bit clearer

File: tests/ui/const-generics/mgca/printing_valtrees_supports_non_values.rs [hunk 8]
```diff
@@ -0,0 +1,26 @@
...
+
+fn foo<const N: Option<u32>>() {} //~ ERROR `Option<u32>` must implement `ConstParamTy` to be used as the type of a const generic parameter [E0741]
```
Comment (BoxyUwU) [inline tests/ui/const-generics/mgca/printing_valtrees_supports_non_values.rs]:
```suggestion
fn foo<const N: Foo>() {}
```

File: tests/ui/const-generics/mgca/printing_valtrees_supports_non_values.rs [hunk 9]
```diff
@@ -0,0 +1,26 @@
...
+
+fn bar<T>() {
+    foo::<{ Some::<u32> { 0: const {} } }>();
+    //~^ ERROR mismatched types [E0308]
+}
+
+fn baz<T, const N: u32>() {
+    foo::<{ Some::<u32> { 0: N } }>;
+    //~^ ERROR the constant `std::option::Option::<u32>::Some(N)` is not of type `Option<u32>`
```
Comment (BoxyUwU) [inline tests/ui/const-generics/mgca/printing_valtrees_supports_non_values.rs]:
```suggestion
    //~^ ERROR the constant `std::option::Option::<u32>::Some(N)` is not of type `Foo`
```

File: tests/ui/const-generics/mgca/printing_valtrees_supports_non_values.rs (hunk 6 above)
Comment (Kivooeo) [reply tests/ui/const-generics/mgca/printing_valtrees_supports_non_values.rs]: the case `foo::<{ Some::<u32> { 0: _ } }>();` ICEs with 

```
thread 'rustc' (3151814) panicked at /home/gh-Kivooeo/rust/compiler/rustc_type_ir/src/const_kind.rs:124:17:
const variables should not be hashed: ?0c
```

Comment (Kivooeo) [reply tests/ui/const-generics/mgca/printing_valtrees_supports_non_values.rs]: the case with `foo::<{ Some::<u32> { 0: <T as Trait>::ASSOC } }>();` works fine

Comment (BoxyUwU) [reply tests/ui/const-generics/mgca/printing_valtrees_supports_non_values.rs]: oh interesting that `0: _` still ICEs :thinking: I guess that's because `destructure_const` isn't a canonical query haha.. good to know.

When you say that code "works fine" do you mean under this PR or on nightly? I was thinking of something like:
```rust
//@compile-flags: --edition=2024
#![feature(min_generic_const_args, adt_const_params)]

trait Trait {
    #[type_const]
    const ASSOC: usize;
}

fn foo<const N: u32>() {}

fn bar<T: Trait>() {
    foo::<{ Some::<u32> { 0: <T as Trait>::ASSOC } }>();
}
```
which does ICE on nightly according to the playground and I would expect to be fixed by your PR

Comment (Kivooeo) [reply tests/ui/const-generics/mgca/printing_valtrees_supports_non_values.rs]: under this PR, yes

Comment (Kivooeo) [reply tests/ui/const-generics/mgca/printing_valtrees_supports_non_values.rs]: I added test case for this

File: tests/ui/const-generics/mgca/printing_valtrees_supports_non_values.rs [hunk 10]
```diff
@@ -0,0 +1,39 @@
+//! Regression test for <https://github.com/rust-lang/rust/issues/150354>
+//!                     <https://github.com/rust-lang/rust/issues/150355>
+//!
+//@ edition 2024
+
+#![allow(incomplete_features)]
+#![feature(min_generic_const_args, adt_const_params, generic_const_exprs)]
```
Comment (BoxyUwU) [inline tests/ui/const-generics/mgca/printing_valtrees_supports_non_values.rs]:
```suggestion
#![feature(min_generic_const_args, adt_const_params)]
```

File: tests/ui/const-generics/mgca/printing_valtrees_supports_non_values.rs [hunk 11]
```diff
@@ -0,0 +1,39 @@
...
+}
+
+fn foo<const N: Foo>() {}
+
+fn bar<T>() {
+    foo::<{ Option::Some::<u32> { 0: const {} } }>();
+    //~^ ERROR mismatched types [E0308]
+    //~| ERROR the constant `Option::<u32>::Some({})` is not of type `Foo`
+}
+
```
Comment (BoxyUwU) [inline tests/ui/const-generics/mgca/printing_valtrees_supports_non_values.rs]:
```suggestion
```
dont need to test GCE-only stuff :3

File: tests/ui/const-generics/mgca/printing_valtrees_supports_non_values.rs [hunk 12]
```diff
@@ -0,0 +1,39 @@
...
+fn baz<T, const N: u32>() {
+    foo::<{ Option::Some::<u32> { 0: N } }>;
+    //~^ ERROR the constant `Option::<u32>::Some(N)` is not of type `Foo`
+}
+
+fn qux<T>()
+where
+    [(); T::ASSOC]:,
+    T: Trait,
```
Comment (BoxyUwU) [inline tests/ui/const-generics/mgca/printing_valtrees_supports_non_values.rs]:
```suggestion
fn qux<T: Trait>()
```

**Review by BoxyUwU — COMMENTED** [review]
thx

*[View changes since this review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/rust/150380/4c383cd5cba5bf87b42e3f9b352db1c9c91198e7..f711ba7d24c9a80e270acdd6ac45189519c623f4)*

**Comment by Kivooeo** [comment]
seems like it should be very fine now

**Review by BoxyUwU — APPROVED** [review]
r=me once CI passes

*[View changes since this review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/rust/150380/4c383cd5cba5bf87b42e3f9b352db1c9c91198e7..517411f143f43689add7f5739a200fbdf8e2d03a)*
