### PR TITLE
Emscripten: Turn wasm-eh on by default

### LINKED ISSUE #112195: Support wasm exception handling for Emscripten target
Currently the Rust Emscripten target supports js exception handling. I've been trying to get it to support also wasm exception handling. The patch for this is quite small. The following suffices:

<details>
<summary>Patch</summary>

```patch
diff --git a/compiler/rustc_codegen_llvm/src/llvm_util.rs b/compiler/rustc_codegen_llvm/src/llvm_util.rs
index a0a640473eb..cd88648911a 100644
--- a/compiler/rustc_codegen_llvm/src/llvm_util.rs
+++ b/compiler/rustc_codegen_llvm/src/llvm_util.rs
@@ -110,7 +110,7 @@ fn llvm_arg_to_arg_name(full_arg: &str) -> &str {
         }
 
         if sess.target.os == "emscripten" && sess.panic_strategy() == PanicStrategy::Unwind {
-            add("-enable-emscripten-cxx-exceptions", false);
+            add("-wasm-enable-sjlj", false);
         }
 
         // HACK(eddyb) LLVM inserts `llvm.assume` calls to preserve align attributes
diff --git a/compiler/rustc_codegen_ssa/src/back/link.rs b/compiler/rustc_codegen_ssa/src/back/link.rs
index 94acdea894b..2909401836d 100644
--- a/compiler/rustc_codegen_ssa/src/back/link.rs
+++ b/compiler/rustc_codegen_ssa/src/back/link.rs
@@ -2057,12 +2057,11 @@ fn add_order_independent_options(
     }
 
     if sess.target.os == "emscripten" {
-        cmd.arg("-s");
-        cmd.arg(if sess.panic_strategy() == PanicStrategy::Abort {
-            "DISABLE_EXCEPTION_CATCHING=1"
+        if sess.panic_strategy() == PanicStrategy::Abort {
+            cmd.arg("-sDISABLE_EXCEPTION_CATCHING=1");
         } else {
-            "DISABLE_EXCEPTION_CATCHING=0"
-        });
+            cmd.arg("-fwasm-exceptions");
+        }
     }
 
     if flavor == LinkerFlavor::PtxLinker {
```

</details>

I'm not sure how to allow a choice between these two options.

@aheejin

### LINKED ISSUE #148309: Tracking issue for MCP 920: Turn emscripten-wasm-eh unwinding ABI on by default
This is a tracking issue for MCP "Turn emscripten-wasm-eh unwinding ABI on by default" (rust-lang/compiler-team#920).

> [!NOTE]
> Tracking issues are used to record the overall progress of implementation.
> They are also used as hubs connecting to other relevant issues, e.g., bugs or open design questions.
>
> A tracking issue is however *not* meant for large scale discussion, questions, or bug reports.
> Instead, open a dedicated issue for the specific matter, link to this tracking issue and ping the MCP author.
> Alternatively, post in the Zulip stream linked from the MCP.
>
> Discussion comments will get marked as off-topic or deleted.
> Repeated discussions on the tracking issue may lead to the tracking issue getting locked.

### Steps

- [ ] Implement the MCP
- [ ] Adjust documentation
  - [ ] In the [Rust Compiler Development Guide] if applicable (e.g., for refactorings)
  - [ ] In the [Rust Forge] if applicable (e.g., for policy changes)
  - [ ] In the [rustc book] if applicable (e.g., for target tier or CLI changes)

[Rust Compiler Development Guide]: https://rustc-dev-guide.rust-lang.org/
[Rust Forge]: https://forge.rust-lang.org/compiler/index.html
[rustc book]: https://doc.rust-lang.org/rustc/index.html

### Unresolved questions

*None so far.*

### Implementation history

*Empty so far.*

---

@hoodmane, consider `@rustbot claim`'ing the work.

### PR DESCRIPTION
**Pull request by hoodmane**
As specified by [MCP](https://github.com/rust-lang/compiler-team/issues/920)
Resolves https://github.com/rust-lang/rust/issues/148309
Resolves https://github.com/rust-lang/rust/issues/112195

### CODE REVIEW

**Comment by lcnr** [comment]
I think this is blocked on a team decision?

**Comment by hoodmane** [comment]
Yes, I think that's the only blocker. It should be about another week before the next Emscripten release. I will post here when it's out.

**Comment by hoodmane** [comment]
Okay Emscripten 4.0.21 was released yesterday so I think this is ready to move forward.

**Comment by bjorn3** [comment]
CI fails.

File: tests/ui/feature-gates/feature-gate-cfg-emscripten-wasm-eh.rs [hunk 1]
```diff
@@ -1,4 +1,4 @@
 //@ compile-flags: --check-cfg=cfg(emscripten_wasm_eh)
```
Comment (bjorn3) [inline tests/ui/feature-gates/feature-gate-cfg-emscripten-wasm-eh.rs:1]: Why does this even need `--check-cfg`?

Edit: Looks like rustc does also emit a warning about an unexpected cfg when unstable cfgs are not allowed.

**Comment by hoodmane** [comment]
Okay CI looks green now
