### PR TITLE
Prevent downstream `impl DerefMut for Pin<LocalType>`

### LINKED ISSUE #85099: A Pin unsoundness involving an `impl DerefMut for Pin<&dyn LocalTrait>`
Haven’t got the time to do any more explaining right now, but here’s the code:

```rust
use std::{
    cell::RefCell,
    future::Future,
    mem,
    ops::DerefMut,
    pin::Pin,
    sync::Arc,
    task::{Context, Poll, Wake},
};

struct SomeLocalStruct<'a, Fut>(&'a RefCell<Fut>);

trait SomeTrait<'a, Fut> {
    #[allow(clippy::mut_from_ref)]
    fn deref_helper(&self) -> &mut (dyn SomeTrait<'a, Fut> + 'a) {
        unimplemented!()
    }
    fn downcast(self: Pin<&mut Self>) -> Pin<&mut Fut> {
        unimplemented!()
    }
}

impl<'a, Fut: Future<Output = ()>> SomeTrait<'a, Fut> for SomeLocalStruct<'a, Fut> {
    fn deref_helper(&self) -> &mut (dyn SomeTrait<'a, Fut> + 'a) {
        let x = Box::new(self.0.borrow_mut());
        let x = Box::leak(x);
        &mut **x
    }
}
impl<'a, Fut: Future<Output = ()>> SomeTrait<'a, Fut> for Fut {
    fn downcast(self: Pin<&mut Self>) -> Pin<&mut Fut> {
        self
    }
}

impl<'b, 'a, Fut> DerefMut for Pin<&'b dyn SomeTrait<'a, Fut>> {
    fn deref_mut<'c>(
        self: &'c mut Pin<&'b dyn SomeTrait<'a, Fut>>,
    ) -> &'c mut (dyn SomeTrait<'a, Fut> + 'b) {
        self.deref_helper()
    }
}

pub fn unsound_pin<Fut: Future<Output = ()>>(
    fut: Fut,
    callback: impl FnOnce(Pin<&mut Fut>),
) -> Fut {
    let cell = RefCell::new(fut);
    let s = &SomeLocalStruct(&cell);
    let p = Pin::new(Pin::new(s));
    let mut p: Pin<Pin<&dyn SomeTrait<'_, Fut>>> = p;
    let r = p.as_mut();
    let f = r.downcast();
    callback(f);
    cell.into_inner()
}

fn yield_now() -> impl Future<Output = ()> {
    struct Yield(bool);
    impl Future for Yield {
        type Output = ();

        fn poll(mut self: Pin<&mut Self>, _cx: &mut std::task::Context<'_>) -> Poll<Self::Output> {
            if matches!(mem::replace(&mut *self, Yield(true)), Yield(true)) {
                Poll::Ready(())
            } else {
                Poll::Pending
            }
        }
    }
    Yield(false)
}

fn main() {
    let fut = async {
        let x = &&0;
        let reference = &x;
        yield_now().await;
        dbg!(reference);
    };

    struct Waker;
    impl Wake for Waker {
        fn wake(self: std::sync::Arc<Self>) {}
    }
    let waker = Arc::new(Waker).into();
    let mut cx = Context::from_waker(&waker);

    let fut = unsound_pin(fut, |fut| {
        let _ = fut.poll(&mut cx);
    });
    let _ = Box::pin(fut).as_mut().poll(&mut cx);
}
```
```
   Compiling playground v0.0.1 (/playground)
    Finished dev [unoptimized + debuginfo] target(s) in 1.10s
     Running `target/debug/playground`
[src/main.rs:79] reference = timeout: the monitored command dumped core
/playground/tools/entrypoint.sh: line 11:     8 Segmentation fault      timeout --signal=KILL ${timeout} "$@"
```
([playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=e1674d1409617cce80f1817a42ba6731))

segfaults in debug build due to an `async`-block future being moved after the first `.poll()` call

### PR DESCRIPTION
**Pull request by Darksonn**
The safety requirements for [`PinCoerceUnsized`](https://doc.rust-lang.org/stable/std/pin/trait.PinCoerceUnsized.html) are essentially that the type does not have a malicious `Deref` or `DerefMut` impl. However, the `Pin` type is fundamental, so the end-user can provide their own implementation of `DerefMut` for `Pin<&SomeLocalType>`, so it's possible for `Pin` to have a malicious `DerefMut` impl. This unsoundness is known as rust-lang/rust#85099.

Unfortunately, this means that the implementation of `PinCoerceUnsized` for `Pin` is currently unsound. To fix that, modify the impl so that it becomes impossible for downstream crates to provide their own implementation of `DerefMut` for `Pin` by abusing a hidden struct that is not fundamental.

This PR is a breaking change, but it fixes rust-lang/rust#85099. The PR supersedes rust-lang/rust#144896.

r? lcnr

### CODE REVIEW

**Comment by Darksonn** [comment]
It doesn't immediately look like error messages have regressed, but the docs have:

image

I'm going to push another commit to improve the docs to this:

image

I think it's reasonable in this case since the impls really are equivalent except for the orphan rules treatment.

**Comment by lcnr** [comment]
I want to make sure I properly understand https://github.com/rust-lang/rust/issues/85099 before merging this. I do think it's a very nice solution and gj for coming up with it!

I personally dislike "lying in the impl", even if it doesn't matter in practice. Gonna throw that question to @rust-lang/libs-api.

Let's crater

@bors try

**Comment by dtolnay** [comment]
We discussed this PR in today's standard library API meeting. Those present were on board with the approach, but it will be important to see a reasonably clean crater result and send PRs for any breakage, because not all downstream impls of DerefMut for Pin are necessarily unsound. The new implementation rules out correct as well as incorrect impls.

Once crater is finished, we would like to do a libs-api FCP to surface this to the rest of the team.

We noticed that the new pin::hidden::PinHelper type is now going to appear in diagnostics such as the pin-unsound-issue-85099-derefmut.stderr in this PR, but hopefully this mostly only happens when someone is doing funny business like writing their own DerefMut impl, and not for more typical use of Pin's methods and impls.

**Comment by Darksonn** [comment]
Ok, let's see what crater says. But I don't think there are any valid use-cases for `impl DerefMut for Pin<P>` for pointer types that aren't `DerefMut`.

**Comment by Darksonn** [comment]
Updating this with some additional tests for error messages. I'm not worried about `PinHelper` showing up in `pin-unsound-issue-85099-derefmut.stderr`, but that it also shows up in `tests/ui/deref/pin-impl-deref.stderr` is unfortunate.

**Comment by Skgland** [comment]
> @Skgland How should I interpret https://github.com/rust-lang/crater/issues/791? Were there actually regressions? 

Sorry, not that I know of, but crater currently also has a bunch of spurious failures which it wasn't pointing out, here 152k+ prepare-fail failures. These spurious failures might be hiding actual regressions, a retry using the retry regressed list might be advisable to get that number down. 

Another PR had regressions missed due to this https://github.com/rust-lang/rust/pull/122661#issuecomment-3207810553
and the retry showed a bunch more https://github.com/rust-lang/rust/issues/145770#issuecomment-3222643785

**Comment by jieyouxu** [comment]
@craterbot run mode=check-only start=master#8c32e313cccf7df531e2d49ffb8227bb92304aee end=try#c659ee110de67e82444e4b6c8407c1a9af9c2cf6 crates=crates=https://crater-reports.s3.amazonaws.com/pr-145608-1/retry-regressed-list.txt

**Comment by jieyouxu** [comment]
@craterbot run mode=check-only start=master#8c32e313cccf7df531e2d49ffb8227bb92304aee end=try#c659ee110de67e82444e4b6c8407c1a9af9c2cf6 crates=https://crater-reports.s3.amazonaws.com/pr-145608-1/retry-regressed-list.txt

**Comment by lcnr** [comment]
lgtm and I agree that this is a good fix for #85099. Great job coming up with this solution. It's a lot nicer than adding some weird type system hack and has pretty much exactly the behavior we want.

r=me after RFC

My only open question is https://github.com/rust-lang/rust/pull/145608#issuecomment-3201162564 and whether we want the docs to lie. I guess @rust-lang/libs-api vibe is "yes, hiding the helper stuff is desirable".

**Comment by Darksonn** [comment]
I still think there is the open question of whether we should use the current implementation, or the one mentioned in https://github.com/rust-lang/rust/pull/145608#issuecomment-3201692051. It seems like the other implementation produces better error messages. I believe the behavior is identical.

**Comment by lcnr** [comment]
if u go with the alternative impl we won't need to transmute anything :thinking: by changing the signature of `DerefMutHelper::deref_mut` to take `Pin<Ptr>`?

**Comment by traviscross** [comment]
This looks right to me.  I propose we accept the behavior of this PR.  As far as this pFCP goes, it would be OK to land the [alternate](https://github.com/Darksonn/rust/commit/5e4d49ad0ae05c0500b0b7a051cf05d688a01100) implementation as well or @lcnr's proposed alternative without the transmute.

@rfcbot fcp merge

cc @rust-lang/types

**Comment by tmandry** [comment]
Writing an impl like this doesn't make a lot of sense and I'm fine removing the ability, especially given the clean crater run.

Given the fact that Pin is `#[fundamental]` and the pin ergonomics work that makes Pin a lang item I think it makes sense to lang FCP this.

@rfcbot reviewed

**Comment by nikomatsakis** [comment]
@rfcbot reviewed

So, I think this is very clever and we should land it. I *also* feel like this is an interesting case study -- there is obviously *something* missing at the language level that we ought to be expressing more clearly. But I'm not really clear on what it is. I'm also struggling a bit to express the requirements around this impl in 'plain english' terms.

File: library/core/src/pin.rs [hunk 1]
```diff
@@ -1689,9 +1689,66 @@ impl<Ptr: [const] Deref> const Deref for Pin<Ptr> {
     }
 }
 
+mod helper {
+    /// Helper that prevents downstream crates from implementing `DerefMut` for `Pin`.
+    ///
+    /// This type is not `#[fundamental]`, so it's possible to relax its `DerefMut` impl bounds in
+    /// the future, so the orphan rules reject downstream impls of `DerefMut` of `Pin`.
```
Comment (BurntSushi) [inline library/core/src/pin.rs]: Can you spill a few more words here explaining how this hack works?

**Review by lcnr — APPROVED** [review]

File: library/core/src/pin.rs (hunk 1 above)
Comment (Darksonn) [reply library/core/src/pin.rs]: Sure. How does this look?

Comment (BurntSushi) [reply library/core/src/pin.rs]: Oh yes, this is much better! Thank you for explaining it. I definitely had a couple gaps in my understanding and the extra words plugged them. :-)

**Comment by lcnr** [comment]
What are the expected changes to the reference here? This does not change anything about fundamental types in the language. The most I can think of would be "note: the standard library sometimes works around this by 'sealing' traits for fundamental types via indirection, e.g. `Pin: DerefMut`...".

But I feel like given the way it is implemented as an ordinary trait implementation, I would expect us to document this in the standard library on the impl, if at all. If we think this exception to the coherence rules for fundamental types is worth documenting, imo we should add a comment to the `DerefMut` impl and potentially remove the `#[cfg(docs)]` version to always show the 'correct' trait bounds

**Comment by traviscross** [comment]
> ...which is prevented using an `impl<T> !DerefMut for &T` clause...

We [document](https://doc.rust-lang.org/std/ops/trait.DerefMut.html#impl-DerefMut-for-%26T) that.  In this case, we're suppressing any documentation which would explain the behavior.

**Comment by traviscross** [comment]
As [mentioned](https://github.com/rust-lang/rust/pull/145608#issuecomment-3335915793), I'm happy as long as we document it somewhere.

> As for where that should go, we've discussed recently that somewhat more in the way of details about lang-item types may need to live in the Reference, so I can see this here from that perspective. I could see the core library docs saying something about this too, of course. It's OK if both say something about it. The key point, though, is that we should say this clearly and normatively somewhere in our documentation.

**Comment by Darksonn** [comment]
I looked at what the reference says about fundamental types, and I don't think this fits there. I added this to the docs:

image

File: library/core/src/pin.rs [hunk 2]
```diff
@@ -1755,13 +1755,18 @@ where
     }
 }
 
+/// Restricted to `Unpin` types, as it's not safe to obtain a mutable reference to a pinned value.
```
Comment (traviscross) [inline library/core/src/pin.rs]:
```suggestion
/// The `Target` is restricted to `Unpin` types as it's not safe to obtain a mutable reference to a
/// pinned value.
```

File: library/core/src/pin.rs [hunk 3]
```diff
@@ -1755,13 +1755,18 @@ where
...
+///
+/// Note that because `Pin` is fundamental, it would normally be possible for crates to implement
+/// `DerefMut` for `Pin<T>` when `T` is a local type and not covered by this impl block. However,
+/// this impl block is written in a special way to prevent that for soundness reasons.
```
Comment (traviscross) [inline library/core/src/pin.rs]:
```suggestion
/// For soundness reasons, implementations of `DerefMut` for `Pin<T>` are rejected even when `T` is
/// a local type not covered by this impl block. (Because `Pin` is [fundamental], such
/// implementations would normally be possible.)
///
/// [fundamental]: ../../reference/items/implementations.html#r-items.impl.trait.fundamental
```

Revised to put the bottom line upfront and to state it as a rule without speaking to its implementation (we could conceivably enforce this rule in other ways).  Also ,as @RalfJung often points out, "note that" tends to imply the rule was already stated and what follows is an implication, but that's not the case here.

**Comment by traviscross** [comment]
Thanks for adding the doc comment.  Left some editorial notes.

**Comment by Darksonn** [comment]
Suggestions applied.

image

**Review by traviscross — APPROVED** [review]
Thanks; all looks great to me.

*[View changes since this review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/rust/145608/dc2c3564d273cf8ccce32dc4f47eaa27063bceb9..b50e33022c6e77f35a8741812babcaed08acca70)*

File: library/core/src/pin.rs [hunk 4]
```diff
@@ -1689,9 +1689,88 @@ impl<Ptr: [const] Deref> const Deref for Pin<Ptr> {
...
+    /// orphan rules assume that stdlib might implement `helper::DerefMut` for `helper::Pin<&_>` in
+    /// the future. Because of this, downstream crates can no longer provide an implementation of
+    /// `DerefMut` for `Pin<&_>`, as it might overlap with a trait impl that, according to the
+    /// orphan rules, the stdlib could introduce without a breaking change in a future release.
+    ///
+    /// See <https://github.com/rust-lang/rust/issues/85099> for the issue this fixes.
+    #[repr(transparent)]
+    #[unstable(feature = "pin_derefmut_internals", issue = "none")]
+    #[allow(missing_debug_implementations)]
+    pub struct Pin<Ptr> {
```
Comment (lcnr) [inline library/core/src/pin.rs]: hmm, having `struct Pin` here seems quite confusing to me. Why did you change this from `struct PinHelper`

Comment (Darksonn) [reply library/core/src/pin.rs]: I thought the error messages were slightly nicer that way.

Comment (lcnr) [reply library/core/src/pin.rs]: hmm, also why define a separate `DerefMut` trait here 🤔 that's surprising to me

Comment (lcnr) [reply library/core/src/pin.rs]: is only the error message for tests/ui/typeck/pin-unsound-issue-85099-derefmut.rs affected? I feel like talking about `PinHelper` is easier to understand, or `pin::helper::DerefMutHelper`

Comment (lcnr) [reply library/core/src/pin.rs]: ah no, also as part of the "= note: required for `pin::helper::Pin<&MyPinType>` to implement `pin::helper::DerefMut`"

Comment (lcnr) [reply library/core/src/pin.rs]: I feel like instead of trying to improve the naming of the std types here, change

https://github.com/rust-lang/rust/blob/1e1a39441bd11aba541a48ba714d939490fc7b85/compiler/rustc_trait_selection/src/error_reporting/traits/suggestions.rs#L3467

to use a diagnostic item for the `struct PinHelper` and just immediately call https://github.com/rust-lang/rust/blob/1e1a39441bd11aba541a48ba714d939490fc7b85/compiler/rustc_trait_selection/src/error_reporting/traits/suggestions.rs#L3590-L3598 for (`DerefMut`) goals using that as the self type

Comment (Darksonn) [reply library/core/src/pin.rs]: My ideal error message would be to rename it back to `PinHelper`, and to remove the mention of the helper from `tests/ui/deref/pin-impl-deref.stderr`.

Comment (Darksonn) [reply library/core/src/pin.rs]: Done!
