### PR TITLE
repr_transparent_external_private_fields: special-case some std types

### LINKED ISSUE #129470: `repr_transparent_external_private_fields` lint fires on `ManuallyDrop` containing a ZST
Consider the following code:

```rust
struct ZST;

#[repr(transparent)]
struct TransparentWithManuallyDropZST {
    value: i32,
    md: std::mem::ManuallyDrop<ZST>,  // error: repr_transparent_external_private_fields
    zst: ZST,                         // no error
}
```

the field `md` fires a lint warning:

```
warning: zero-sized fields in `repr(transparent)` cannot contain external non-exhaustive types
 --> src/lib.rs:7:5
  |
7 |     md: std::mem::ManuallyDrop<ZST>,
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = warning: this was previously accepted by the compiler but is being phased out; it will become a hard error in a future release!
  = note: for more information, see issue #78586 <https://github.com/rust-lang/rust/issues/78586>
  = note: this struct contains `ManuallyDrop<ZST>`, which contains private fields, and makes it not a breaking change to become non-zero-sized in the future.
  = note: `#[warn(repr_transparent_external_private_fields)]` on by default
```

While the spirit of the lint seems reasonable, the [docs state](https://doc.rust-lang.org/stable/std/mem/struct.ManuallyDrop.html):

> `ManuallyDrop<T>` is guaranteed to have the same layout and bit validity as `T`

So in this case, it seems like `ManuallyDrop` changing size _would_ be a breaking change, and the lint at the very least misleading here. Perhaps an exclusion is needed on this lint for `ManuallyDrop`?

----

More generally, quoting [the nomicon](https://doc.rust-lang.org/nomicon/other-reprs.html#reprtransparent):

> This repr is only considered part of the public ABI of a type if either the single field is pub, or if its layout is documented in prose. Otherwise, the layout should not be relied upon by other crates.

So, in `ManuallyDrop`'s case, the single field is not pub, but the layout is documented in prose and so should be considered part of the ABI. Is it possible there are other types out there with such a layout guarantee in prose, which might also be incorrectly flagged by this lint?

### PR DESCRIPTION
**Pull request by GrigorenkoPV**
Fixes #129470

@rustbot label +A-lint +L-repr_transparent_external_private_fields

### CODE REVIEW

File: compiler/rustc_hir_analysis/src/check/check.rs [hunk 1]
```diff
@@ -1259,6 +1259,17 @@ pub(super) fn check_transparent<'tcx>(tcx: TyCtxt<'tcx>, adt: ty::AdtDef<'tcx>)
                 ty::Tuple(list) => list.iter().try_for_each(|t| check_non_exhaustive(tcx, t)),
                 ty::Array(ty, _) => check_non_exhaustive(tcx, *ty),
                 ty::Adt(def, args) => {
+                    if matches!(
+                        tcx.as_lang_item(def.did()),
+                        Some(LangItem::UnsafeCell | LangItem::ManuallyDrop | LangItem::MaybeUninit)
+                    ) || matches!(
+                        tcx.get_diagnostic_name(def.did()),
```
Comment (compiler-errors) [inline compiler/rustc_hir_analysis/src/check/check.rs:1266]: I don't think diagnostic items should be used in a way that *affects* whether something is linted. They should only be used to change the quality of a diagnostic (i.e. its labels or its message). These should be turned into lang items.

Comment (compiler-errors) [reply compiler/rustc_hir_analysis/src/check/check.rs:1266]: Also, is there a reason why we don't apply this to any `repr(transparent)` ADT?

Comment (GrigorenkoPV) [reply compiler/rustc_hir_analysis/src/check/check.rs:1266]: > Also, is there a reason why we don't apply this to any `repr(transparent)` ADT?

As mentioned in the original issue

> More generally, quoting [the nomicon](https://doc.rust-lang.org/nomicon/other-reprs.html#reprtransparent):
> 
> > This repr is only considered part of the public ABI of a type if either the single field is pub, or if its layout is documented in prose. Otherwise, the layout should not be relied upon by other crates.
> 
> So, in `ManuallyDrop`'s case, the single field is not pub, but the layout is documented in prose and so should be considered part of the ABI. Is it possible there are other types out there with such a layout guarantee in prose, which might also be incorrectly flagged by this lint?

Comment (GrigorenkoPV) [reply compiler/rustc_hir_analysis/src/check/check.rs:1266]: > These should be turned into lang items.

Is there some sort of FCP required for this?

Comment (compiler-errors) [reply compiler/rustc_hir_analysis/src/check/check.rs:1266]: No, you just need to do something like this: f4f57bfccb98522f4aaa2942baaa5a381c7d952d

**Comment by GrigorenkoPV** [comment]
@rustbot label +A-lang-item

`Cell` & `SyncUnsafeCell` are now lang items. As per https://github.com/rust-lang/rust/pull/129487#discussion_r1729569499

File: compiler/rustc_hir_analysis/src/check/check.rs (hunk 1 above)
Comment (lukas-code) [reply compiler/rustc_hir_analysis/src/check/check.rs]: For `Pin` we also [guarantee the layout in prose](https://doc.rust-lang.org/nightly/core/pin/struct.Pin.html#layout-and-abi).

I think it would be better to introduce an internal attribute (e.g. `rustc_pub_transparent`) to mark those types rather than special case them all individually just for this lint.

Comment (compiler-errors) [reply compiler/rustc_hir_analysis/src/check/check.rs]: Yep, I think a builtin attr would be nice.

**Comment by compiler-errors** [comment]
Could you please rework this by adding a new attribute which tracks if the repr is "public" via `rustc_pub_transparent`? Then please squash the history since we don't need to track adding a diagnostic item and a lang item if it didn't make it into the final revision.

**Comment by compiler-errors** [comment]
> Then please squash the history since we don't need to track adding a diagnostic item and a lang item if it didn't make it into the final revision.

@rustbot author

File: compiler/rustc_feature/src/builtin_attrs.rs [hunk 2]
```diff
@@ -641,6 +641,11 @@ pub const BUILTIN_ATTRIBUTES: &[BuiltinAttribute] = &[
         ErrorFollowing, EncodeCrossCrate::Yes,
         "rustc_deprecated_safe_2024 is supposed to be used in libstd only",
     ),
+    rustc_attr!(
+        rustc_pub_transparent, Normal, template!(Word),
+        WarnFollowing, EncodeCrossCrate::Yes,
+        "rustc_pub_transparent is supposed to be used in libstd only",
```
Comment (compiler-errors) [inline compiler/rustc_feature/src/builtin_attrs.rs:647]: give this a better description

(rustc_deprecated_safe_2024 also has a bad description, but that's unrelated)

File: compiler/rustc_passes/src/check_attr.rs [hunk 3]
```diff
@@ -2381,6 +2382,18 @@ impl<'tcx> CheckAttrVisitor<'tcx> {
             }
         }
     }
+
+    fn check_rustc_pub_transparent(&self, attr_span: Span, span: Span, attrs: &[Attribute]) {
```
Comment (compiler-errors) [inline compiler/rustc_passes/src/check_attr.rs:2386]: Can you check that this is applied to an ADT only?

**Review by compiler-errors — CHANGES_REQUESTED** [review]

**Comment by GrigorenkoPV** [comment]
> Then please squash the history since we don't need to track adding a diagnostic item and a lang item if it didn't make it into the final revision.
 
 I have force-pushed a new version, where those commits do not even exist.

**Comment by compiler-errors** [comment]
Please squash this still. We don't need a FIVE commit PR for a simple attribute addition.

**Comment by compiler-errors** [comment]
Like, this is a pretty basic PR; it does not need to document every single tiny step that you took in implementing something. This PR touches about as many files in the compiler as the number of commits, so I feel like it's a bit excessive.

**Comment by compiler-errors** [comment]
Sorry, though; I saw 5 commits before and saw 5 commits after so I didn't realize that you actually ended up just writing 4 more commits just to add an internal attribute, lol.

**Comment by GrigorenkoPV** [comment]
No problem, I will squash them, as they have indeed got a bit too small but numerous

File: compiler/rustc_passes/src/check_attr.rs (hunk 3 above)
Comment (GrigorenkoPV) [reply compiler/rustc_passes/src/check_attr.rs:2386]: Well, I rely on `#[repr(transparent)]` being present, which, in turn, should probably guaranteed it's only applied to ADTs? Is it still worth it to check?

Comment (compiler-errors) [reply compiler/rustc_passes/src/check_attr.rs:2386]: Eh, I'd kinda rather we double check but I guess it doesn't matter 🤷

Comment (compiler-errors) [reply compiler/rustc_passes/src/check_attr.rs:2386]: I mean, it's an internal attribute so we don't need to do *any* validation; all of this is for the benefit. The less we can encode internal assumptions about how attributes are used, the better IMO. But it's kinda moot. Unless we get some `repr(transparent)` changes in the future, or something.

**Comment by GrigorenkoPV** [comment]
@rustbot ready
i think

**Review by compiler-errors — APPROVED** [review]
Thanks!

**Comment by GrigorenkoPV** [comment]
Thank you a lot for the review!
