### PR TITLE
Check `const Drop` impls considering `~const` Bounds

### LINKED ISSUE #92881: ~const bounds do not work when impling const Drop
I encountered this issue while trying to remove `box_free`.

I tried this code:

```rust
#![feature(const_trait_impl, const_fn_trait_bound, const_mut_refs)]

trait X {
    fn x();
}

struct Y<T: X>(T);

impl<T: ~const X> const Drop for Y<T> {
    fn drop(&mut self) {
        T::x();
    }
}
```

I expected the code to compile.

Instead, I got the following error:
```
error[E0367]: `Drop` impl requires `T: X` but the struct it is implemented for does not
 --> src/lib.rs:9:9
  |
9 | impl<T: ~const X> const Drop for Y<T> {
  |         ^^^^^^^^
  |
note: the implementor must specify the same requirement
 --> src/lib.rs:7:1
  |
7 | struct Y<T: X>(T);
  | ^^^^^^^^^^^^^^^^^^
  ```

### Meta

`rustc --version --verbose`:
```
rustc 1.60.0-nightly (22e491ac7 2022-01-13)
binary: rustc
commit-hash: 22e491ac7ed454d34669151a8b6464cb643c9b41
commit-date: 2022-01-13
host: x86_64-pc-windows-msvc
release: 1.60.0-nightly
LLVM version: 13.0.0
```

</p>
</details>

### PR DESCRIPTION
**Pull request by compiler-errors**
This PR adds logic to trait selection to account for `~const` bounds in custom `impl const Drop` for types, elaborates the `const Drop` check in `rustc_const_eval` to check those bounds, and steals some drop linting fixes from #92922, thanks @DrMeepster.

r? @fee1-dead @oli-obk <sup>(edit: guess I can't request review from two people, lol)</sup>
since each of you wrote and reviewed #88558, respectively.

Since the logic here is more complicated than what existed, it's possible that this is a perf regression. But it works correctly with tests, and that makes me happy.

Fixes #92881

### CODE REVIEW

**Review by fee1-dead — COMMENTED** [review]
On a first glance the changes LGTM.

Preferably we'd want to have some sort of wf check for `impl const Drop`s that requires it to already satisfy the conditions for a structurally `const Drop`, I'm not saying that it should be in this PR though.

I'll take a deeper look when I have time.

File: compiler/rustc_middle/src/ty/util.rs [hunk 1]
```diff
@@ -1041,6 +1041,42 @@ pub fn needs_drop_components<'tcx>(
...
+        | ty::FnDef(..)
+        | ty::FnPtr(_) => true,
+
+        ty::Opaque(..)
+        | ty::Dynamic(..)
+        | ty::Error(_)
+        | ty::Bound(..)
+        | ty::Param(_)
+        | ty::Placeholder(_)
+        | ty::Never
```
Comment (fee1-dead) [inline compiler/rustc_middle/src/ty/util.rs:1065]: This should be trivial to make `Result<u8, !>: ~const Drop`.

**Review by fee1-dead — COMMENTED** [review]
I think I understand what is causing this regression: For user-defined types, you want to select bounds on `impl const Drop`s of the types and check if all bounds are satisfied. Instead of nesting a lot of obligations and running the trait selection process many times, why not extract the components to check bounds for and do just that? For types that require the environment (parameter types) and types that are user-defined, collect them into a list and test them. For other trivial components don't even nest obligations for them.

**Comment by compiler-errors** [comment]
> Instead of nesting a lot of obligations and running the trait selection process many times, why not extract the components to check bounds for and do just that?

I'm hesitant to structurally recurse on the type during candidate assembly (like the code was doing previously) because of normalization, etc., and because other traits (e.g. `auto trait`s, and `Copy`/`Clone`) leave that complicated machinery until during confirmation. I could perhaps be a bit more efficient with the list of nested obligations we generate during confirmation, but I want to leave the code simpler if possible.

Actually I think the regression might've gone away with the last commit I pushed, at least with local testing on the `keccak` example...
@fee1-dead: Do you mind retrying a perf run? I'll see what I can do to make confirmation a bit more efficient if perf still says this code still needs some work.

Also I'll put up a fix to make `!: ~const Drop` later, but if you can get that perf run started I can check on it later.

**Comment by compiler-errors** [comment]
I'll look into this, I guess.

 @rustbot author

**Comment by compiler-errors** [comment]
An attempt was made at being a bit smarter during confirmation :sweat_smile: 

@rustbot ready

**Comment by oli-obk** [comment]
The keccak change looks like noise, as the detailed view (click on the percentage) actually shows an improvement

Not sure about the others. Looks like a regression in mir_const_qualif

File: compiler/rustc_middle/src/ty/util.rs [hunk 2]
```diff
@@ -1041,6 +1041,42 @@ pub fn needs_drop_components<'tcx>(
...
+        | ty::FnPtr(_)
+        | ty::Never => true,
+
+        ty::Opaque(..)
+        | ty::Dynamic(..)
+        | ty::Error(_)
+        | ty::Bound(..)
+        | ty::Param(_)
+        | ty::Placeholder(_)
+        | ty::Foreign(_)
```
Comment (fee1-dead) [inline compiler/rustc_middle/src/ty/util.rs:1066]: I don't think `ty::Foreign` should return false because there is nothing non-const-droppy about them. You cannot have custom drop impls for them i.e. the following would fail:

```rust
#![feature(extern_types)]
extern "C" {
    type Foo;
}

impl Drop for Foo {
    fn drop(&mut self) {
        // side effect
    }
}
```

As for "do we ever encounter this type when checking for const Drop?" I'd say not currently, but if we were to introduce const heap it might become possible:

```rust
#![feature(extern_types)]
extern "C" {
    type Foo;
}

fn dropbox(_x: Box<Foo>) {}
```

File: compiler/rustc_trait_selection/src/traits/select/candidate_assembly.rs [hunk 3]
```diff
@@ -918,139 +912,77 @@ impl<'cx, 'tcx> SelectionContext<'cx, 'tcx> {
...
-                }
+        let self_ty = self.infcx().shallow_resolve(obligation.self_ty());
+        match self_ty.skip_binder().kind() {
+            ty::Opaque(..)
+            | ty::Dynamic(..)
+            | ty::Error(_)
+            | ty::Bound(..)
+            | ty::Param(_)
+            | ty::Placeholder(_)
+            | ty::Foreign(_)
```
Comment (fee1-dead) [inline compiler/rustc_trait_selection/src/traits/select/candidate_assembly.rs:935]: Same comment as above

File: compiler/rustc_trait_selection/src/traits/select/confirmation.rs [hunk 4]
```diff
@@ -1087,4 +1089,127 @@ impl<'cx, 'tcx> SelectionContext<'cx, 'tcx> {
...
+                | ty::Uint(_)
+                | ty::Float(_)
+                | ty::Infer(ty::IntVar(_))
+                | ty::Infer(ty::FloatVar(_))
+                | ty::Str
+                | ty::RawPtr(_)
+                | ty::Ref(..)
+                | ty::FnDef(..)
+                | ty::FnPtr(_)
+                | ty::Never => {}
```
Comment (fee1-dead) [inline compiler/rustc_trait_selection/src/traits/select/confirmation.rs:1136]: Add ty::Foreign to this

File: compiler/rustc_typeck/src/check/dropck.rs [hunk 5]
```diff
@@ -228,9 +228,15 @@ fn ensure_drop_predicates_are_implied_by_item_defn<'tcx>(
...
             match (predicate.skip_binder(), p.skip_binder()) {
-                (ty::PredicateKind::Trait(a), ty::PredicateKind::Trait(b)) => {
-                    relator.relate(predicate.rebind(a), p.rebind(b)).is_ok()
-                }
+                (ty::PredicateKind::Trait(a), ty::PredicateKind::Trait(b)) => relator
+                    .relate(
+                        predicate.rebind(ty::TraitPredicate {
+                            constness: ty::BoundConstness::NotConst,
+                            ..a
+                        }),
```
Comment (fee1-dead) [inline compiler/rustc_typeck/src/check/dropck.rs:236]: Perhaps you should add a comment explaining why the predicate should be rebound.

**Review by fee1-dead — APPROVED** [review]
r=me with comments resolved

File: compiler/rustc_typeck/src/check/dropck.rs (hunk 5 above)
Comment (compiler-errors) [reply compiler/rustc_typeck/src/check/dropck.rs]: left a comment that explains why the predicate is modified to NotConst.

**Comment by compiler-errors** [comment]
Bors seems to have failed for exactly no reason... let's try this again? Wonder if that delegate gives me `retry` permissions..

@bors retry

**Comment by compiler-errors** [comment]
I'll try this one more time before posting on zulip or something 

@bors retry spurious failure with no reason provided
