### PR TITLE
In `BTreeMap::eq`, do not compare the elements if the sizes are different.

### LINKED ISSUE #149122: 1.92 regression: Behavior change in `PartialEq` impl of `BTreeSet`?
Test failure found in the beta crater run:

```
[INFO] [stdout] thread 'atom::tests::test_possible_states_eq' (22) panicked at src/value.rs:63:18:
[INFO] [stdout] can't compare values String("a") and Number(0)
```

https://crater-reports.s3.amazonaws.com/beta-1.92-4/beta-2025-11-10/gh/ttaubert.tlc/log.txt

Minimized reproducer:

```rust
use std::cmp::Ordering;
use std::collections::BTreeSet;

#[derive(Debug)]
pub(crate) enum Value {
    One,
    Two(i32),
}

impl Ord for Value {
    fn cmp(&self, other: &Value) -> Ordering {
        match (self, other) {
            (Value::One, Value::One) => Ordering::Equal,
            (Value::Two(x), Value::Two(y)) => x.cmp(y),
            _ => panic!("can't compare values {:?} and {:?}", self, other),
        }
    }
}

impl PartialOrd for Value {
    fn partial_cmp(&self, other: &Value) -> Option<Ordering> {
        Some(self.cmp(other))
    }
}

impl PartialEq for Value {
    fn eq(&self, other: &Value) -> bool {
        match (self, other) {
            (Value::One, Value::One) => true,
            (Value::Two(x), Value::Two(y)) => x == y,
            _ => panic!("can't compare values {:?} and {:?}", self, other),
        }
    }
}

impl Eq for Value {}

fn main() {
    let lhs = BTreeSet::from([Value::One]);
    let rhs = BTreeSet::from([Value::Two(1), Value::Two(2)]);
    let _ = lhs == rhs;
}
```

This code runs without errors on stable, but panics on beta.

It's reasonable to say that this code should have panicked in the first place, but still, it's strange that the behavior changed. So, maybe this needs some investigation on what happened?

### PR DESCRIPTION
**Pull request by zachs18**
*[View all comments](https://triagebot.infra.rust-lang.org/gh-comments/rust-lang/rust/pull/149125)*

Reverts rust-lang/rust#147101 in library/alloc/src/btree/

rust-lang/rust#147101 replaced some instances of code like `a.len() == b.len() && a.iter().eq(&b)` with just `a.iter().eq(&b)`, but the optimization that PR introduced only applies for `TrustedLen` iterators, and `BTreeMap`'s itertors are not `TrustedLen`, so this theoretically regressed perf for comparing large `BTreeMap`/`BTreeSet`s with unequal lengths but equal prefixes, (and also made it so that comparing two different-length `BTreeMap`/`BTreeSet`s with elements whose `PartialEq` impls that can panic now can panic, though this is not a "promised" behaviour either way (cc rust-lang/rust#149122))

Given that `TrustedLen` is an unsafe trait, I opted to not implement it for `BTreeMap`'s iterators, and instead just revert the change. If someone else wants to audit `BTreeMap`'s iterators to make sure they always return the right number of items (even in the face of incorrect user `Ord` impls) and then implement `TrustedLen` for them so that the optimization works for them, then this can be closed in favor of that (or if the perf regression is deemed too theoretical, this can be closed outright).

Example of theoretical perf regression: https://play.rust-lang.org/?version=beta&mode=release&edition=2024&gist=a37e3d61e6bf02669b251315c9a44fe2 (very rough estimates, using `Instant::elapsed`).
In release mode on stable the comparison takes ~23.68µs.
In release mode on beta/nightly the comparison takes ~48.351057ms.

### CODE REVIEW

**Review by workingjubilee — COMMENTED** [review]
Would it be overmuch to suggest we add a test of a "naughty" BTreeMap comparison of panicking equality impls that manages to avoid panicking because of the `len` check, and add a comment to it that says that regressing the test is fine *if* you did it on purpose?

*[View changes since this review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/rust/149125/d2f887349fe3ea079a4f89b020ce6df1993e1e06..4adcdbb58ba65d0af86c50d77ef42b344b9a5cb2)*

**Comment by zachs18** [comment]
I added a module in `library/alloctests/collections/` that tests that various collections' `PartialEq::eq` impls don't compare elements if the lengths of two compared collections are different.

**Review by workingjubilee — APPROVED** [review]
yay! evil tests!

*[View changes since this review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/rust/149125/d2f887349fe3ea079a4f89b020ce6df1993e1e06..907f5c118096eb2e2031f41a5a3337791c7a111e)*

**Comment by matthiaskrgr** [comment]
@bors2 try jobs=test-various

File: library/alloctests/tests/collections/eq_diff_len.rs [hunk 1]
```diff
@@ -0,0 +1,96 @@
...
+
+    assert_eq!(false, v1 == v2);
+}
+
+#[test]
+fn hashset_evil_eq() {
+    let s1 = HashSet::from([(0, Evil)]);
+    let s2 = HashSet::from([(0, Evil), (1, Evil)]);
+
+    assert_eq!(false, s1 == s2);
```
Comment (yotamofek) [inline library/alloctests/tests/collections/eq_diff_len.rs:63]: nit: `assert_eq!` with `true` or `false` is kinda weird, IMHO.


```suggestion
    assert_ne!(s1, s2);
```

(also pertinent to rest of the assertions in this file)

File: library/alloctests/tests/collections/eq_diff_len.rs [hunk 2]
```diff
@@ -0,0 +1,96 @@
...
+    let v1 = vec![Evil];
+    let v2 = vec![Evil; 2];
+
+    assert_eq!(false, v1 == v2);
+}
+
+#[test]
+fn hashset_evil_eq() {
+    let s1 = HashSet::from([(0, Evil)]);
+    let s2 = HashSet::from([(0, Evil), (1, Evil)]);
```
Comment (yotamofek) [inline library/alloctests/tests/collections/eq_diff_len.rs:61]:
```suggestion
    let s1 = HashSet::from([Evil]);
    let s2 = HashSet::from([Evil; 2]);
```

the various `Set` collections don't need to have `(usize, Evil)` tuples as elements.
Actually, I'm not even sure that having these tuples would catch the failures you're testing for, since the `usize` would be compared first and found unequal, so `Evil::eq` would never be called. No?

Comment (yotamofek) [reply library/alloctests/tests/collections/eq_diff_len.rs:61]: Does this test actually fail on beta?

Comment (yotamofek) [reply library/alloctests/tests/collections/eq_diff_len.rs:61]: now that I think about it, I'm not completely sure the `Map`-collection tests would catch this regression either, since their keys would always compare as unequal and short-circuit the `PartialEq` implementation?

Comment (zachs18) [reply library/alloctests/tests/collections/eq_diff_len.rs:61]: > the various `Set` collections don't need to have `(usize, Evil)` tuples as elements. Actually, I'm not even sure that having these tuples would catch the failures you're testing for, since the `usize` would be compared first and found unequal, so `Evil::eq` would never be called. No?

The suggested change makes the two sets have the same length, so would not be testing the case of comparing sets with different lengths (actually, it makes the test panic during `HashSet::from([Evil; 2])`, because `HashSet` will call `Evil::eq` to deduplicate during construction). The tuples are there specifically to avoid calling `Evil::eq` when constructing the sets/maps, since the first element/key makes the comparison short-circuit.

> now that I think about it, I'm not completely sure the `Map`-collection tests would catch this regression either, since their keys would always compare as unequal and short-circuit the `PartialEq` implementation?


As I said in https://github.com/rust-lang/rust/pull/149125#issuecomment-3556092556 , 
> (I think teeeechically a regression for `(BTree,Hash)(Map,Set)` could get past the test if they compare the `(1, Evil)` to the `(0, Evil)` first and bail early, but I think that's an unlikely change for `BTree*`, and would be nondeterministic for `Hash*` so would be caught *eventually*)

To expand on that: currently `BTreeMap`'s `eq` impl goes in order, so if it did compare the elements, it would start with the two first elements which are both `(0, Evil)`, so it would call `Evil::eq`. Similarly, `HashMap`'s `eq` impl (checks the lengths are equal, and then) iterates over `self` and checks that all of `self`'s keys exist in `other` with the equal values.

Comment (yotamofek) [reply library/alloctests/tests/collections/eq_diff_len.rs:61]: Right, missed that paragraph from the PR description. Thanks!

Comment (yotamofek) [reply library/alloctests/tests/collections/eq_diff_len.rs:61]: A holistic test would probably need a `struct Evil(usize);` where the `Hash` implementation is guaranteed to return a different hash for `Evil(0)` and `Evil(1)`, but panic in the impl for `PartialEq::eq`?
(just curious, not sure if it's worth the implementation, and even if it did, could definitely go in a follow-up PR)

**Comment by workingjubilee** [comment]
it's spurious in the sense that it's occurring because the test is poorly designed and not because a "true" regression occurred.

**Comment by mati865** [comment]
Regardless of that test, saying the error was spurious and marking PR as ready for review again sounds like the next attempt should succeed.

**Comment by workingjubilee** [comment]
True!

File: library/alloctests/tests/collections/eq_diff_len.rs (hunk 2 above)
Comment (workingjubilee) [reply library/alloctests/tests/collections/eq_diff_len.rs:61]: should it? was HashSet in the affected set?

**Comment by zachs18** [comment]
I assumed the failure was nondeterministic. In any case, I filed https://github.com/rust-lang/rust/pull/149190 to fix the actual issue.

File: library/alloctests/tests/collections/eq_diff_len.rs (hunk 2 above)
Comment (yotamofek) [reply library/alloctests/tests/collections/eq_diff_len.rs:61]: > should it? was HashSet in the affected set?

Right, it shouldn't!
Brain went AWOL for a bit there :D

**Comment by workingjubilee** [comment]
nada!
@bors r+ rollup

**Comment by workingjubilee** [comment]
hm, wait, taking stock. I missed something

@bors r-

**Comment by workingjubilee** [comment]
@yotamofek This PR was marked beta-accepted. https://github.com/rust-lang/rust/pull/149381 was not. I am going to have to ask T-release very nicely to get this pulled at all into 1.92, because this was supposed to land first and then everyone decided it had to wait for this and that and the other thing. We almost always land changes on main first and then pull them to beta. Knowing all this, if you want me to bors r-, I will.

**Comment by apiraino** [comment]
I assume it was discussed by t-libs

@rustbot label -I-libs-nominated
