### PR TITLE
fix [type error] for error E0029 and E0277

### LINKED ISSUE #105946: [type error] when wrongly destructing boxes of ints
Given the following code: 

```rust
#![feature(box_syntax)]
#![feature(half_open_range_patterns_in_slices)]
fn main() {
    let [_y..] = [box 1, box 2];
}
```

The current output is:

```
error[E0425]: cannot find value `_y` in this scope
 --> 4a310255aac576a3d3d7ede99bff59ef38f2fb87.rs:4:10
  |
4 |     let [_y..] = [box 1, box 2];
  |          ^^ not found in this scope

error[E0527]: pattern requires 1 element but array has 2
 --> 4a310255aac576a3d3d7ede99bff59ef38f2fb87.rs:4:9
  |
4 |     let [_y..] = [box 1, box 2];
  |         ^^^^^^ expected 2 elements

error[E0029]: only `char` and numeric types are allowed in range patterns
 --> 4a310255aac576a3d3d7ede99bff59ef38f2fb87.rs:4:10
  |
4 |     let [_y..] = [box 1, box 2];
  |          ^^ this is of type `[type error]` but it should be `char` or numeric

error: aborting due to 3 previous errors

Some errors have detailed explanations: E0029, E0425, E0527.
For more information about an error, try `rustc --explain E0029`.
```

We shouldn't show `[type error]` here.

### PR DESCRIPTION
**Pull request by lyming2007**
check explicitly for the type references error
if ty.references_error() is true change the error to be err.delay_as_bug() and prevent the error E0029 and E0277 from emitting out this fix #105946

### CODE REVIEW

**Comment by estebank** [comment]
You'll need to fix this:

```
tidy error: /checkout/src/test/ui/typeck/issue-105946.rs: too many trailing newlines (2)
```

Remove *one* trailing line from that file (some editors will show a single trailing line as no line at all, and some will show them, if you remove all trailing empty lines tidy will also complain).

**Comment by estebank** [comment]
You need to re`--bless` 😅

File: compiler/rustc_hir_typeck/src/pat.rs [hunk 1]
```diff
@@ -562,6 +577,9 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
                     type between two end-points, you can use a guard.",
             );
         }
+        if is_ty_references_error {
```
Comment (compiler-errors) [inline compiler/rustc_hir_typeck/src/pat.rs:580]: I wonder if we can just do `(lhs, rhs).references_error()` here? I think 3-tuples implement `TypeVisitable`... or else they should.

File: compiler/rustc_trait_selection/src/traits/error_reporting/suggestions.rs [hunk 2]
```diff
@@ -1684,19 +1684,21 @@ impl<'tcx> TypeErrCtxtExt<'tcx> for TypeErrCtxt<'_, 'tcx> {
         true
     }
 
+    // return true if hit type references_error
     fn point_at_returns_when_relevant(
         &self,
         err: &mut Diagnostic,
         obligation: &PredicateObligation<'tcx>,
-    ) {
+    ) -> bool {
```
Comment (compiler-errors) [inline compiler/rustc_trait_selection/src/traits/error_reporting/suggestions.rs:1692]: It's not obvious that this function returns a bool that is true if the type references error. 

could you change this `err: &mut DiagnosticBuilder<'tcx, ErrorGuaranteed>`, and then you can `delay_as_bug` inside the body?

File: compiler/rustc_trait_selection/src/traits/error_reporting/mod.rs [hunk 3]
```diff
@@ -1386,8 +1386,9 @@ impl<'tcx> TypeErrCtxtExt<'tcx> for TypeErrCtxt<'_, 'tcx> {
         };
 
         self.note_obligation_cause(&mut err, &obligation);
-        self.point_at_returns_when_relevant(&mut err, &obligation);
-
+        if self.point_at_returns_when_relevant(&mut err, &obligation) {
+            err.delay_as_bug();
+        }
```
Comment (estebank) [inline compiler/rustc_trait_selection/src/traits/error_reporting/mod.rs:1391]: To mirror what compiler-errors said, here you could instead check if `obligation.references_error()`, instead of changing `point_at_returns_when_relevant`.

File: compiler/rustc_hir_typeck/src/pat.rs (hunk 1 above)
Comment (estebank) [reply compiler/rustc_hir_typeck/src/pat.rs:580]: The tuple they've got is `(Option(_, ty, _), Option(_, ty, _))`, they wouldn't be able to invoke it in any case without changing the logic. I do not remember if `delay_as_bug` is idempotent. If it is, then we could pull up line 581 into every place above where `is_ty_references_error` is assigned instead.

Comment (compiler-errors) [reply compiler/rustc_hir_typeck/src/pat.rs:580]: [`downgrade_to_delayed_bug`](https://doc.rust-lang.org/nightly/nightly-rustc/src/rustc_errors/diagnostic_builder.rs.html#489-492) is idempotent

Comment (lyming2007) [reply compiler/rustc_hir_typeck/src/pat.rs]: I used [downgrade_to_delayed_bug](https://doc.rust-lang.org/nightly/nightly-rustc/src/rustc_errors/diagnostic_builder.rs.html#489-492) to replace `delay_as_bug()`.
since` (lhs, rhs).references_error()` works, we don't need to pull up `is_ty_references_error `which was removed.

File: compiler/rustc_trait_selection/src/traits/error_reporting/suggestions.rs (hunk 2 above)
Comment (lyming2007) [reply compiler/rustc_trait_selection/src/traits/error_reporting/suggestions.rs]: that's a great suggestion, and I changed to `DiagnosticBuilder `from Diagnostic for `invokcing `delay_as_bug inside `point_at_returns_when_relevant()`

File: compiler/rustc_trait_selection/src/traits/error_reporting/mod.rs (hunk 3 above)
Comment (lyming2007) [reply compiler/rustc_trait_selection/src/traits/error_reporting/mod.rs]: I tried, but it didn't work, thus `obligation.predicate.references_error()` behaves differently from` ty_references_error()`.
I've changed `point_at_returns_when_relevant()` as Michael suggested, which works well.

**Comment by lyming2007** [comment]
> You'll need to fix this:
> 
> ```
> tidy error: /checkout/src/test/ui/typeck/issue-105946.rs: too many trailing newlines (2)
> ```
> 
> Remove _one_ trailing line from that file (some editors will show a single trailing line as no line at all, and some will show them, if you remove all trailing empty lines tidy will also complain).

I think `./x.py fmt` would remove those trailing newlines...  :(

**Comment by estebank** [comment]
> I think ./x.py fmt would remove those trailing newlines... :(

I'd have to agree :)

File: compiler/rustc_trait_selection/src/traits/error_reporting/suggestions.rs [hunk 4]
```diff
@@ -1684,9 +1684,10 @@ impl<'tcx> TypeErrCtxtExt<'tcx> for TypeErrCtxt<'_, 'tcx> {
         true
     }
 
+    // return true if hit type references_error
```
Comment (estebank) [inline compiler/rustc_trait_selection/src/traits/error_reporting/suggestions.rs:1687]: This comment is now inaccurate.

**Review by estebank — APPROVED** [review]

File: compiler/rustc_trait_selection/src/traits/error_reporting/mod.rs [hunk 5]
```diff
@@ -1387,7 +1387,9 @@ impl<'tcx> TypeErrCtxtExt<'tcx> for TypeErrCtxt<'_, 'tcx> {
 
         self.note_obligation_cause(&mut err, &obligation);
         self.point_at_returns_when_relevant(&mut err, &obligation);
-
+        if obligation.predicate.references_error() {
+            err.delay_as_bug();
+        }
```
Comment (compiler-errors) [inline compiler/rustc_trait_selection/src/traits/error_reporting/mod.rs:1392]: Is this necessary for your fix?

Comment (lyming2007) [reply compiler/rustc_trait_selection/src/traits/error_reporting/mod.rs:1392]: sorry. I forgot to remove these code after testing the function Esteban suggested.
I'm going to remove them soon.

File: compiler/rustc_trait_selection/src/traits/error_reporting/suggestions.rs (hunk 4 above)
Comment (lyming2007) [reply compiler/rustc_trait_selection/src/traits/error_reporting/suggestions.rs:1687]: yes. forgot to remove the old comment and add new comment.
will do it soon

File: compiler/rustc_trait_selection/src/traits/error_reporting/mod.rs (hunk 5 above)
Comment (lyming2007) [reply compiler/rustc_trait_selection/src/traits/error_reporting/mod.rs]: removed

File: compiler/rustc_trait_selection/src/traits/error_reporting/suggestions.rs (hunk 4 above)
Comment (lyming2007) [reply compiler/rustc_trait_selection/src/traits/error_reporting/suggestions.rs]: removed
