### PR TITLE
attempt to fix unreachable code regression 

### LINKED ISSUE #149571: rustc 1.92.0-beta3 flags unreachable code where there is none
### Code

```Rust
use std::convert::Infallible;

pub fn foo(f: impl FnOnce () -> Infallible) -> Infallible {
    f()
}
```

### Current output

```Shell
error[E0601]: `main` function not found in crate `lib`
 --> lib.rs:5:2
  |
5 | }
  |  ^ consider adding a `main` function to `lib.rs`

warning: unreachable expression
 --> lib.rs:5:1
  |
4 |     f()
  |     --- any code following this expression is unreachable
5 | }
  | ^ unreachable expression
  |
note: this expression has type `Infallible`, which is uninhabited
 --> lib.rs:4:5
  |
4 |     f()
  |     ^^^
  = note: `#[warn(unreachable_code)]` (part of `#[warn(unused)]`) on by default

error: aborting due to 1 previous error; 1 warning emitted

For more information about this error, try `rustc --explain E0601`.
```

### Desired output

```Shell
None. Compilation should succeed with no warnings.
```

### Rationale and extra context

The real-world version of this where the lint tripped upon updating the compiler looks like this:

```
pub fn reset_stack_guards(continuation: impl FnOnce() -> Infallible) -> Infallible {
    sys::android_reset_stack_guards();
    continuation()
}
```

It is intended that the passed continuation never returns, and no user code exists past it. The fact that it will never return is surfaced to the caller through the type signature.

I understand that there may be MIR which is "unreachable" in this case (the return path), but there is no unreachable user code.

There's currently no way to write the function above without suppressing the modified lint that I can see, because the lint also triggers on

```
pub fn reset_stack_guards(continuation: impl FnOnce() -> Infallible) -> ! {
    sys::android_reset_stack_guards();
    match continuation() {}
}
```

If we had never type support, this lint might be reasonable as with `#![feature(never_type)]` and a signature `fn reset_stack_guards(continuation: impl FnOnce() -> !) -> !`, the lint does not complain.

Since never types are not stable, this means that a useful, default-enabled lint now reports in non-actionable situations.

### Other cases

```Rust

```

### Rust Version

```Shell
rustc 1.92.0-beta.3 (f3f12444a 2025-11-09)
binary: rustc
commit-hash: f3f12444a017add0468f683f3a10656d29438a05
commit-date: 2025-11-09
host: x86_64-unknown-linux-gnu
release: 1.92.0-beta.3
LLVM version: 21.1.3
```

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by Kivooeo**
For some reason it works, it checks function output type and suppress warning if type is uninhabited  

~~This double negations in code breaks my mind actually~~

I'd love to revisit this part in future and try to find a proper solution maybe, but for now I feel like it's enough before release to fix the issue? I really wonder what team does think, especially @cjgillot and other people who are more confident in this part of compiler than I do 

I tried a lot of things here, it's only approach that pass all tests included new regression one

fixes https://github.com/rust-lang/rust/issues/149571

r? compiler

### CODE REVIEW

File: compiler/rustc_mir_build/src/builder/mod.rs [hunk 1]
```diff
@@ -849,10 +849,28 @@ impl<'a, 'tcx> Builder<'a, 'tcx> {
...
+                            && fn_sig.is_inhabited_from(
+                                self.tcx,
+                                self.parent_module,
+                                self.infcx.typing_env(self.param_env),
+                            )
+                    }
+                    _ => !ty.is_never(),
+                };
+
+                if should_warn {
```
Comment (davidtwco) [inline compiler/rustc_mir_build/src/builder/mod.rs]: nit: I'd maybe pull `!ty.is_never()` out of both branches of the `match` and put it in this conditional, and only check if the signature is inhabited in the previous branch, and add a comment as to why we check that.

**Review by davidtwco — COMMENTED** [review]
r=me after fixing nit

*[View changes since this review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/rust/149664/b33119ffdd483969934b10a886dc06dd29a473f9..a23f6a75d9d4e3b35d00b71af6d3e8734b27d70f)*

File: compiler/rustc_mir_build/src/builder/mod.rs (hunk 1 above)
Comment (Kivooeo) [reply compiler/rustc_mir_build/src/builder/mod.rs]: I'd keep `!ty.is_never() && output_is_inhabited` as safest here

**Comment by Kobzol** [comment]
It seems like this caused a perf. regression. Do you think something could be done to reduce it?

**Comment by eggyal** [comment]
Per https://rust-lang.zulipchat.com/#narrow/channel/241545-t-release/topic/1.2E93.2E1/near/572503361

@rustbot label +stable-nominated
