### PR TITLE
change method resolution to constrain hidden types instead of rejecting method candidates

### LINKED ISSUE #121404: DefineOpaqueTypes::No in UFC `Self` resolution
in https://github.com/rust-lang/rust/blob/1d447a9946effc38c4b964a888ab408a3df3c246/compiler/rustc_hir_typeck/src/fn_ctxt/_impl.rs#L1452 we disable hidden type registration. I have been unable to craft a test case for this, as either the `self_ty` arg of `instantiate_value_path` is `None`, or there are no generic parameters on the self type, so it gets inference variables which end up working out fine. 

As an example:

```rust
#![feature(type_alias_impl_trait)]
struct Foo<T>(T);

impl Foo<u32> {
    fn method() {}
    fn method2(self) {}
}

type Bar = impl Sized;

fn bar() -> Bar {
    42_u32
}

impl Foo<Bar> {
    fn foo() -> Bar {
        Self::method();
        //~^ ERROR: no function or associated item named `method` found for struct `Foo<Bar>`
        Foo::<Bar>::method();
        //~^ ERROR: no function or associated item named `method` found for struct `Foo<Bar>`
        let x = Foo(bar());
        Foo::method2(x);
        let x = Self(bar());
        Self::method2(x);
        //~^ ERROR: no function or associated item named `method2` found for struct `Foo<Bar>`
        todo!()
    }
}

fn main() {}
```

the `Foo::method2(x);` works fine, none of the others do, and none of them have a `self_ty` set here either.

Wrapping the types in `<>` does not have an effect, even if the code seems to hint at that: https://github.com/rust-lang/rust/blob/1d447a9946effc38c4b964a888ab408a3df3c246/compiler/rustc_hir_typeck/src/fn_ctxt/_impl.rs#L1150

any ideas @compiler-errors 

cc https://github.com/rust-lang/rust/pull/121394

### PR DESCRIPTION
**Pull request by oli-obk**
Some of these are in probes and may affect inference. This is therefore a breaking change.

This allows new code to compile on stable:

```rust
trait Trait {}

impl Trait for u32 {}

struct Bar<T>(T);

impl Bar<u32> {
    fn foo(self) {}
}

fn foo(x: bool) -> Bar<impl Sized> {
    if x {
        let x = foo(false);
        x.foo();
        //^ this used to not find the `foo` method, because while we did equate `x`'s type with possible candidates, we didn't allow opaque type inference while doing so
    }
    todo!()
}
```

r? @compiler-errors

fixes  #121404

cc https://github.com/rust-lang/rust/issues/116652

### CODE REVIEW

**Comment by oli-obk** [comment]
@rustbot fcp merge

This allows new code to compile on stable. It is a necessary step towards making the old solver more similar to the new solver.

**Comment by oli-obk** [comment]
@rfcbot merge

This allows new code to compile on stable. It is a necessary step towards making the old solver more similar to the new solver (and subsequently unblocking stabilizing impl-trait-in-associated-types). See the PR's main post for an example of the new kind of code that is now accepted

**Comment by compiler-errors** [comment]
This causes (TAIT) code to break, like what caused that CI failure. Pls update the FCP to include an example of what becomes ambiguous during method probe.

File: tests/ui/impl-trait/method-resolution.rs [hunk 1]
```diff
@@ -0,0 +1,21 @@
+//@ check-pass
+
+trait Trait {}
+
+impl Trait for u32 {}
+
+struct Bar<T>(T);
+
+impl Bar<u32> {
+    fn foo(self) {}
```
Comment (lcnr) [inline tests/ui/impl-trait/method-resolution.rs:10]:
```suggestion
    fn bar(self) {}
```
:blush:

File: tests/ui/impl-trait/method-resolution2.rs [hunk 2]
```diff
@@ -0,0 +1,24 @@
+trait Trait {}
```
Comment (lcnr) [inline tests/ui/impl-trait/method-resolution2.rs:1]: can you add a short explanation for why this test fails with ambiguity?

File: tests/ui/impl-trait/method-resolution2.rs [hunk 3]
```diff
@@ -0,0 +1,24 @@
...
+    fn foo(self) {}
+}
+
+fn foo(x: bool) -> Bar<impl Trait> {
+    //~^ ERROR type annotations needed
+    if x {
+        let x = foo(false);
+        x.foo();
+    }
+    todo!()
```
Comment (lcnr) [inline tests/ui/impl-trait/method-resolution2.rs:21]: maybe instead return `Bar<i32>` here and change this to `check-pass`? I think this test is intended to show that we still reject the `Bar<u32>` impl because `u32: Trait` does not hold. So method selection succeeds and the ambiguity only happens after that

File: tests/ui/impl-trait/method-resolution3.rs [hunk 4]
```diff
@@ -0,0 +1,24 @@
+trait Trait {}
```
Comment (lcnr) [inline tests/ui/impl-trait/method-resolution3.rs:1]: short comment explaning this test:

> check that we consider `Bar<impl Sized>` to successfully unify with `Bar<u32>` and `Bar<i32>`, causing ambiguity.

**Review by lcnr — COMMENTED** [review]
please also add a revision for `-Znext-solver` to the added tests

File: tests/ui/type-alias-impl-trait/method_resolution.rs [hunk 5]
```diff
@@ -0,0 +1,29 @@
+//! check that we do not unify `Bar<Foo>` with `BAr<u32>`, even though the
+//! `bar` method call can be resolved unambiguously by doing so.
```
Comment (lcnr) [inline tests/ui/type-alias-impl-trait/method_resolution.rs:2]: wait, why this? :thinking:

File: tests/ui/type-alias-impl-trait/method_resolution2.rs [hunk 6]
```diff
@@ -0,0 +1,28 @@
+//! check that we do not unify `Bar<Foo>` with `BAr<u32>`, even though the
```
Comment (lcnr) [inline tests/ui/type-alias-impl-trait/method_resolution2.rs:1]: we do unify `Foo` with `u32` here, do we?

File: tests/ui/type-alias-impl-trait/method_resolution.rs (hunk 5 above)
Comment (oli-obk) [reply tests/ui/type-alias-impl-trait/method_resolution.rs:2]: I forgot to update the test descriptions in thr commit that affected them

**Comment by jackh726** [comment]
> But it is also a breaking change, since `&self` and `&mut self` method calls on recursive RPIT function calls now constrain the hidden type to `&_` and `&mut _` respectively. This is not what users really expect or want from this, but there's way around this.

This is concerning to me and I would prefer us to outright error of ambiguity here than constrain incorrectly.

**Comment by oli-obk** [comment]
> This is concerning to me and I would prefer us to outright error of ambiguity here than constrain incorrectly.

That's not easy to do in the old solver, and likely impossible to do without major downsides. While we could attempt to move the initial method probing into a canonical query, that would mess with inference as we would not have access to the trait bounds on infer vars anymore.

**Comment by jackh726** [comment]
> > This is concerning to me and I would prefer us to outright error of ambiguity here than constrain incorrectly.
> 
> That's not easy to do in the old solver, and likely impossible to do without major downsides. While we could attempt to move the initial method probing into a canonical query, that would mess with inference as we would not have access to the trait bounds on infer vars anymore.
> 
> Note that ne new solver handles this correctly

The test I'm focusing on here is `tests/ui/impl-trait/method-resolution4.rs`. Today, this works exactly as I would expect on stable. With both this PR and with `-Znext-solver`, it fails. So, this is not a case where I think the new solver behaves as expected. (Similar with `tests/ui/type-alias-impl-trait/method_resolution_trait_method_from_opaque.rs`).

The problem I have is, I think, if we make this change and break these cases today, we can't in the future unbreak these cases in the future in a backwards-compatible manner, even though as we've both said this is not what users expect.

I think it would be good if you can make a separate PR just adding the tests, so we can more clearly see what would be changing in the future.

**Comment by jackh726** [comment]
I actually do feel strongly about this, so I'm going to go ahead and raise a concern.

@rfcbot concern unexpected-self-constraint

**Comment by oli-obk** [comment]
@craterbot check

File: compiler/rustc_hir_typeck/src/method/probe.rs [hunk 7]
```diff
@@ -1488,7 +1488,7 @@ impl<'a, 'tcx> ProbeContext<'a, 'tcx> {
         self.probe(|_| {
             // First check that the self type can be related.
             let sub_obligations = match self.at(&ObligationCause::dummy(), self.param_env).sup(
-                DefineOpaqueTypes::No,
+                DefineOpaqueTypes::Yes,
```
Comment (lcnr) [inline compiler/rustc_hir_typeck/src/method/probe.rs:1491]: we could try to get away with only using `DefineOPaqueTypes::No` here when checking whether the self type could be unified 🤔 I think all the other changes here are a lot less of a concern

Comment (oli-obk) [reply compiler/rustc_hir_typeck/src/method/probe.rs]: I manually added a check for that instead of relying on `No`. I'm surprised it doesn't work for the new solver. I don't see where it would replace a field expression's opaque type with an inference var.

File: compiler/rustc_hir_typeck/src/method/probe.rs [hunk 8]
```diff
@@ -1483,20 +1484,31 @@ impl<'a, 'tcx> ProbeContext<'a, 'tcx> {
...
+                // Thus we need to prevent them from trying to match the `&_` autoref
+                // candidates that get created for `&self` trait methods.
+                ty::Alias(ty::Opaque, alias_ty)
+                    if self.infcx.can_define_opaque_ty(alias_ty.def_id) =>
+                {
+                    if !probe.xform_self_ty.is_ty_var() {
+                        return ProbeResult::NoMatch;
+                    }
+                    vec![]
                 }
```
Comment (oli-obk) [inline compiler/rustc_hir_typeck/src/method/probe.rs:1500]: This is only an issue for opaque types themselves, not if they are nested in anything. This is because

* references get autodereffed and we start out with the most dereffed version
* aggregates that have opaques in their associated types are either dereffable or will only get matched against infer vars or references to infer vars

**Comment by oli-obk** [comment]
@bors try

let's run crater with the breaking change fixed

**Comment by oli-obk** [comment]
@craterbot check

**Comment by jackh726** [comment]
Regressions seems real. Not sure exactly what's happening, but it seems like the compiler thinks these could impl `Iterator`...

**Comment by oli-obk** [comment]
@craterbot check p=1 crates=https://crater-reports.s3.amazonaws.com/pr-123962/retry-regressed-list.txt

File: compiler/rustc_data_structures/src/obligation_forest/mod.rs [hunk 9]
```diff
@@ -359,7 +359,10 @@ impl<O: ForestObligation> ObligationForest<O> {
             Entry::Vacant(v) => {
                 let obligation_tree_id = match parent {
                     Some(parent_index) => self.nodes[parent_index].obligation_tree_id,
-                    None => self.obligation_tree_id_generator.next().unwrap(),
+                    // FIXME(type_alias_impl_trait): with `#[defines]` attributes required to define hidden
+                    // types we can convert this back to a `next` method call, as this function shouldn't be
+                    // defining a hidden type anyway.
+                    None => Iterator::next(&mut self.obligation_tree_id_generator).unwrap(),
```
Comment (jackh726) [inline compiler/rustc_data_structures/src/obligation_forest/mod.rs:365]: Can this change be reverted now?

File: tests/ui/impl-trait/issues/issue-70877.rs [hunk 10]
```diff
@@ -27,7 +27,9 @@ fn ham() -> Foo {
 
 fn oof(_: Foo) -> impl std::fmt::Debug {
     let mut bar = ham();
-    let func = bar.next().unwrap();
+    // Need to UFC invoke `Iterator::next`,
+    // as otherwise the hidden type gets constrained to `&mut _`
+    let func = Iterator::next(&mut bar).unwrap();
```
Comment (jackh726) [inline tests/ui/impl-trait/issues/issue-70877.rs:32]: and here

**Review by jackh726 — CHANGES_REQUESTED** [review]

File: tests/ui/impl-trait/issues/issue-70877.rs [hunk 11]
```diff
@@ -27,7 +27,9 @@ fn ham() -> Foo {
 
 fn oof(_: Foo) -> impl std::fmt::Debug {
     let mut bar = ham();
-    let func = bar.next().unwrap();
+    // Need to UFC invoke `Iterator::next`,
```
Comment (nikomatsakis) [inline tests/ui/impl-trait/issues/issue-70877.rs:30]: I'm a bit surprised by this. I expect this to be equivalent to `let mut bar: Option<_> = None; bar.unwrap().next()` -- i.e., an error, yes, but not for this reason?

File: compiler/rustc_hir_typeck/src/method/probe.rs [hunk 12]
```diff
@@ -1484,20 +1486,29 @@ impl<'a, 'tcx> ProbeContext<'a, 'tcx> {
...
-                probe.xform_self_ty,
-                self_ty,
-            ) {
-                Ok(InferOk { obligations, value: () }) => obligations,
-                Err(err) => {
-                    debug!("--> cannot relate self-types {:?}", err);
+            let sub_obligations = match self_ty.kind() {
+                // HACK: opaque types will match anything for which their bounds hold.
+                // Thus we need to prevent them from trying to match the `&_` autoref
+                // candidates that get created for `&self` trait methods.
```
Comment (nikomatsakis) [inline compiler/rustc_hir_typeck/src/method/probe.rs:1494]: Not just `&self`, right? Also `&mut self`?

Also, I kind of expect that if the self-type is an opaque that can be defined we would just give an error if it hasn't been constrained yet. 

Do I have an inaccurate mental model?

**Review by nikomatsakis — CHANGES_REQUESTED** [review]

File: compiler/rustc_hir_typeck/src/method/probe.rs (hunk 12 above)
Comment (oli-obk) [reply compiler/rustc_hir_typeck/src/method/probe.rs:1494]: Even unconstrained, users are relying on this already, and since we can support it, it seems odd to reject it.

We do support `&self` and all other receivers (mutable, pin, ...), as long as the hidden type is constrained to `Self` and not a reference to it. There's tests for that.

File: compiler/rustc_hir_typeck/src/method/probe.rs [hunk 13]
```diff
@@ -1437,19 +1439,30 @@ impl<'a, 'tcx> ProbeContext<'a, 'tcx> {
...
+                        // HACK: opaque types will match anything for which their bounds hold.
+                        // Thus we need to prevent them from trying to match the `&_` autoref
+                        // candidates that get created for `&self` trait methods.
+                        ty::Alias(ty::Opaque, alias_ty)
+                            if self.infcx.can_define_opaque_ty(alias_ty.def_id)
+                                && !xform_self_ty.is_ty_var() =>
+                        {
                             return ProbeResult::NoMatch;
                         }
+                        // FIXME: Make this `ocx.sup` once we define opaques more eagerly.
```
Comment (lcnr) [inline compiler/rustc_hir_typeck/src/method/probe.rs:1452]: can now change this to `ocx.sup`

**Comment by nikomatsakis** [comment]
@rfcbot reviewed

OK, I just spent an hour with @oli-obk and @lcnr and came to the conclusion that this PR is a step in the right direction and, even though the specific change is hacky, I don't think it accepts anything we don't *want* to accept. It does reject *some* code that we accept today and accept some code we reject today. We don't know of a case that changes the behavior of code we accept today. But all these cases are extreme edge cases that are difficult to devise and which strike as quite unlikely to exist in the wild or to have an impact.

To put down my thoughts for posterity:

In general, we want in-scope opaque types to behave like inference variables. Which would imply that invoking `opaque.method()` should give you an error unless the `opaque` type has been constrained. *But* that's kind of inconsistent and annoying. If you have 

```rust
fn foo(mut x: impl Iterator) {
    x.next()
}
```

it works, so it'd be nice if this code would work too

```rust
fn foo(n: usize) -> impl Iterator<Item = u32> {
    if n > 0 {
        let mut iter = foo(n - 1);
        iter.next();
    }
    None
}
```

But here `iter` is an unbound opaque type (`impl Iterator<Item = u32>`) and so, naively, treating that like an inference variable would give us an unbound error. This broke some crates and generally seems undesirable. (@jackh726's concern)

However, if we go ahead and *allow* execution to continue, we also get into a weird place. This is because `iter` is effectively an unbound inf var `impl Iterator = ?0`. The candidate for `Iterator` is instantiated with `&mut ?1`. We try to unify `?0 = &mut ?1`. This succeeds, but then we later try to `impl Iterator = Option<u32>` on the last line, and so we get an error. So @jackh726's concern is not resolved, because the code still fails to compile.

Oli then introduced a special change that ignores candidates when, in effect, (a) the self type (perhaps after derefs) is an in-scope, unconstrained opaque variable; (b) we are not doing auto-ref or other adjustments; and (c) the method is not by-value self. This is a kind of odd rule but it has the impact that we skip over the problematic candidate above, because it fails criteria (c). We then try auto-mut-ref, and hence the self type is `&mut impl Iterator`. This gets unified with the candidate's `&mut ?1`, and so `?1 = impl Iterator`. Great. Later on we also constrain `impl Iterator = Option<u32>`. Great. No problems.

You can observe edge cases that fail to compile or begin compiling but you have to work at it. For example, to get more things to compile, you need exactly one impl, in which case we may infer a value for the opaque type. But that's ok and in line with us treating it like an inference variable. On the other hand, if you invoke not `opaque.method()` but `(&opaque).method()`, then when we consider that first candidate we decide that `&?O = &&?1` and so we get the same kind of error that we added the hack to avoid. Seems ok.

File: tests/ui/impl-trait/call_method_without_import.rs [hunk 14]
```diff
@@ -0,0 +1,35 @@
+//@ revisions: import no_import
+//@[import] check-pass
+
```
Comment (lcnr) [inline tests/ui/impl-trait/call_method_without_import.rs:3]: can you write a quick explanatio for why this happens, maybe with a `FIXME`?

File: tests/ui/type-alias-impl-trait/method_resolution.rs [hunk 15]
```diff
@@ -0,0 +1,29 @@
+//! check that we do not unify `Bar<Foo>` with `BAr<u32>`, even though the
```
[the remark this answers is not in the document]
Comment (lcnr) [reply tests/ui/type-alias-impl-trait/method_resolution.rs:1]: not resolved, also this comment feels outdated :thinking: isn't the cause here that `the `Bar<u32>` impl does not define `Foo`?

**Review by lcnr — COMMENTED** [review]
r=me after nits

File: tests/ui/type-alias-impl-trait/method_resolution.rs (hunk 15 above)
[the remark this answers is not in the document]
Comment (oli-obk) [reply tests/ui/type-alias-impl-trait/method_resolution.rs]: I added more tests to cover the case where it actually defines `Foo`
