### PR TITLE
libtest: add --show-output flag to print stdout of successful tests

### LINKED ISSUE #54669: Using `--format=json` with `--nocapture`
I'm looking for a way to get test results, including stdout/stderr, in json format.

I've tried to use `--format=json` with `--nocapture` and have got an unexpected result, imo.

Example file:
```rust
#[cfg(test)]
mod tests {
    #[test]
    fn test1() {
        println!("Hello from test #1");
        panic!();
    }
    #[test]
    fn test2() {
        println!("Hello from test #2");
    }
}
```

1. `cargo test -- -Z unstable-options --format=json` output:
```
    Finished dev [unoptimized + debuginfo] target(s) in 0.03s                                                                                                                        
     Running target/debug/deps/rust_sandbox-3aca71fd58cbc041
{ "type": "suite", "event": "started", "test_count": "0" }
{ "type": "suite", "event": "ok", "passed": 0, "failed": 0, "allowed_fail": 0, "ignored": 0, "measured": 0, "filtered_out": "0" }
     Running target/debug/deps/tests-03a860f74891dd25
{ "type": "suite", "event": "started", "test_count": "2" }
{ "type": "test", "event": "started", "name": "tests::test1" }
{ "type": "test", "event": "started", "name": "tests::test2" }
{ "type": "test", "name": "tests::test2", "event": "ok" }
{ "type": "test", "name": "tests::test1", "event": "failed", "stdout": "Hello from test #1\nthread 'tests::test1' panicked at 'explicit panic', tests/tests.rs:6:9\nnote: Run with `RUST_BACKTRACE=1` for a backtrace.\n" }
{ "type": "suite", "event": "failed", "passed": 1, "failed": 1, "allowed_fail": 0, "ignored": 0, "measured": 0, "filtered_out": "0" }
error: test failed, to rerun pass '--test tests'
```

2. `cargo test -- --nocapture -Z unstable-options --format=json` output:
```
    Finished dev [unoptimized + debuginfo] target(s) in 0.03s                                                                                                                        
     Running target/debug/deps/rust_sandbox-3aca71fd58cbc041
{ "type": "suite", "event": "started", "test_count": "0" }
{ "type": "suite", "event": "ok", "passed": 0, "failed": 0, "allowed_fail": 0, "ignored": 0, "measured": 0, "filtered_out": "0" }
     Running target/debug/deps/tests-03a860f74891dd25
{ "type": "suite", "event": "started", "test_count": "2" }
{ "type": "test", "event": "started", "name": "tests::test1" }
{ "type": "test", "event": "started", "name": "tests::test2" }
Hello from test #1
Hello from test #2
thread 'tests::test1' panicked at 'explicit panic', tests/tests.rs:6:9
note: Run with `RUST_BACKTRACE=1` for a backtrace.
{ "type": "test", "name": "tests::test2", "event": "ok" }
{ "type": "test", "name": "tests::test1", "event": "failed" }
{ "type": "suite", "event": "failed", "passed": 1, "failed": 1, "allowed_fail": 0, "ignored": 0, "measured": 0, "filtered_out": "0" }
error: test failed, to rerun pass '--test tests'
```
I expected to see this happen:
* In the 1st case, the `Hello from test #1` line doesn't appear in the `stdout` field.
* In the 2nd case, the `println!` output and errors are recorded in different fields (e.g. `stdout` and `stderr`).

Expected behavior can be useful for integrating test frameworks with IDEs and editors.

I'm using:
* rustc 1.29.1 (b801ae664 2018-09-20)

### PR DESCRIPTION
**Pull request by emmericp**
This pull request adds a new flag `--show-output` for tests to show the output of successful tests. For most formatters this was already supported just not exposed via the CLI (apparently only used by `librustdoc`). I've also added support for this option in the JSON formatter.

This kind of fixes https://github.com/rust-lang/rust/issues/54669 which wants `--format json` to work with `--nocapture`, which is... well, impossible. What this issue really calls for is `--show-output` as implemented here.

### CODE REVIEW

**Comment by Centril** [comment]
Assigning random T-compiler member...

r? @varkor

**Comment by emmericp** [comment]
updated with a new test case for the json output

**Comment by varkor** [comment]
Assigning someone more familiar with libtest JSON output as in https://github.com/rust-lang/rust/pull/46450.

r? @nrc

**Comment by ProgrammaticNajel** [comment]
Ping from triage. @nrc any updates on this? Thank you.

**Comment by JohnTitor** [comment]
Ping from triage: @nrc do you have time to review?

**Comment by Centril** [comment]
cc @gnzlbg

File: src/libtest/lib.rs [hunk 1]
```diff
@@ -272,7 +272,7 @@ impl Options {
 
 // The default console test runner. It accepts the command line
 // arguments and a vector of test_descs.
-pub fn test_main(args: &[String], tests: Vec<TestDescAndFn>, options: Options) {
+pub fn test_main(args: &[String], tests: Vec<TestDescAndFn>, options: Option<Options>) {
```
Comment (gnzlbg) [inline src/libtest/lib.rs]: I'm not really sure why this change is necessary.

**Review by gnzlbg — CHANGES_REQUESTED** [review]
The json formatting part LGTM. Otherwise I only left a question.

**Comment by Centril** [comment]
r? @gnzlbg 

cc @rust-lang/compiler @rust-lang/dev-tools for FCP.

File: src/libtest/lib.rs (hunk 1 above)
Comment (emmericp) [reply src/libtest/lib.rs]: The two places that call this function internally are:

* librustdoc, which gets the display_output options from some config somewhere else, so we don't want to override it from the commandline parameter here (at least not flag not present overring the config), so can't override display_output
* test_main_static, which wants to get display_output from the not yet parsed args list, so we need to set it here from the command line

I guess it would be possible to change librustdoc to add/remove the --show-output flag in the args array when its internal config option is present/not present, but i think having options as an Option to override this is nicer than fiddling with cli args.

So the actual problem is that there are basically two structs storing test options, it's overall messy. I didn't want to make a big change to that logic here

**Comment by emmericp** [comment]
thanks for your review!

File: src/libtest/lib.rs (hunk 1 above)
Comment (gnzlbg) [reply src/libtest/lib.rs]: Makes sense. I just took a look and unifying these isn't trivial.

**Review by gnzlbg — APPROVED** [review]

**Comment by gnzlbg** [comment]
I thought this was awaiting some sort of FCP since the option isn't an unstable one (cc @rust-lang/dev-tools ?). This option feels harmless, and we still have a nightly cycle to make it unstable if we want to, so I'm fine with merging this as is.
