### PR TITLE
Reject invalid literal suffixes in tuple indexing, tuple struct indexing, and struct field name position

### LINKED ISSUE #60210: Tracking issue for future-incompatbility warning 'invalid literal suffix on tuple index' (not a lint)
This is the **summary issue** for a bug fix related to tuple indexing. The goal of this page is describe why this change was made and how you can fix code that is affected by it. It also provides a place to ask questions or register a complaint if you feel the change should not be made. For more information on the policy around future-compatibility warnings, see our [breaking change policy guidelines][guidelines].

[guidelines]: https://forge.rust-lang.org/rustc-bug-fix-procedure.html

### What is the warning for?

As reported in https://github.com/rust-lang/rust/issues/59418, the compiler incorrectly accepts `foo.0_u32` (and other suffixes) when indexing into tuples. The expected syntax is simply `foo.0`. We are presently issuing **warnings** when this incorrect syntax is used but we expect to transition those warnings to **errors** in the future.

### How can you fix your code?

Most often this error manifests in procedural macros that employ the `syn` or `quote` crates. It can be avoided by using `syn::Index::from` or `proc_macro::Literal::*_unsuffixed`. For example, if before you were generating `foo.0` doing something like this:

```rust
let i = 0;
quote! { foo.$i }
```

you might now do instead:

```rust
let i = syn::Index::from(0);
quote! { foo.$i }
```

### When will this warning become a hard error?
                    
At the beginning of each 6-week release cycle, the Rust compiler team
will review the set of outstanding future compatibility warnings and
nominate some of them for **Final Comment Period**. Toward the end of
the cycle, we will review any comments and make a final determination
whether to convert the warning into a hard error or remove it
entirely.

### Related bugs

Here are some of the regressions found in the wild:

- https://github.com/rust-lang/rust/issues/59553
- https://github.com/rust-lang/rust/issues/60138

### PR DESCRIPTION
**Pull request by jieyouxu**
Tracking issue: rust-lang/rust#60210
Closes rust-lang/rust#60210

## Summary

Bump the ["suffixes on a tuple index are invalid" non-lint pseudo future-incompatibility warning (#60210)][issue-60210][^non-lint] to a **hard error** across all editions, rejecting the remaining carve outs from accidentally accepted invalid suffixes since Rust **1.27**.

- We accidentally accepted invalid suffixes in tuple indexing positions in Rust **1.27**. Originally reported at https://github.com/rust-lang/rust/issues/59418.
- We tried to hard reject all invalid suffixes in https://github.com/rust-lang/rust/pull/59421, but unfortunately it turns out there were proc macros accidentally relying on it: https://github.com/rust-lang/rust/issues/60138.
- We temporarily accepted `{i,u}{32,size}` in https://github.com/rust-lang/rust/pull/60186 (the "*carve outs*") to mitigate *immediate* ecosystem impact, but it came with an FCW warning indicating that we wanted to reject it after a few Rust releases.
- Now (1.89.0) is a few Rust releases later (1.35.0), thus I'm proposing to **also reject the carve outs**.
    - `std::mem::offset_of!` stabilized in Rust **1.77.0** happens to use the same "don't expect suffix" code path which has the carve outs, so it also accepted the carve out suffixes. I'm proposing to **reject this case as well**.

## What specifically breaks?

Code that still relied on invalid `{i,u}{32,size}` suffixes being temporarily accepted by rust-lang/rust#60186 as an ecosystem impact mitigation measure (cf. rust-lang/rust#60138). Specifically, the following cases (particularly the construction of these forms in proc macros like reported in rust-lang/rust#60138):

### Position 1: Invalid `{i,u}{32,size}` suffixes in tuple indexing

```rs
fn main() {
    let _x = (42,).0invalid; // Already error, already rejected by #59421
    let _x = (42,).0i8;      // Already error, not one of the #60186 carve outs.
    let _x = (42,).0usize;   // warning: suffixes on a tuple index are invalid
}
```

### Position 2: Invalid `{i,u}{32,size}` suffixes in tuple struct indexing

```rs
fn main() {
    struct X(i32);
    let _x = X(42);
	let _x = _x.0invalid; // Already error, already rejected by #59421
    let _x = _x.0i8;      // Already error, not one of the #60186 carve outs.
    let _x = _x.0usize;   // warning: suffixes on a tuple index are invalid
}
```

### Position 3: Invalid `{i,u}{32,size}` suffixes in numeric struct field names

```rs
fn main() {
    struct X(i32, i32, i32);
    let _x = X(1, 2, 3);
    let _y = X { 0usize: 42, 1: 42, 2: 42 };    // warning: suffixes on a tuple index are invalid
	match _x {
        X { 0usize: 1, 1: 2, 2: 3 } => todo!(), // warning: suffixes on a tuple index are invalid
        _ => {}
    }
}
```

### Position 4: Invalid `{i,u}{32,size}` suffixes in `std::mem::offset_of!`

While investigating the warning, unfortunately I noticed `std::mem::offset_of!` also happens to use the "expect no suffix" code path which had the carve outs. So this was accepted since Rust **1.77.0** with the same FCW:

```rs
fn main() {
    #[repr(C)]
    pub struct Struct<T>(u8, T);

    assert_eq!(std::mem::offset_of!(Struct<u32>, 0usize), 0);
    //~^ WARN suffixes on a tuple index are invalid
}
```

### The above forms in proc macros

For instance, constructions like (see tracking issue rust-lang/rust#60210):

```rs
let i = 0;
quote! { foo.$i }
```

where the user needs to actually write

```rs
let i = syn::Index::from(0);
quote! { foo.$i }
```

### Crater results

Conducted a crater run (https://github.com/rust-lang/rust/pull/145463#issuecomment-3194920383).

- https://github.com/AmlingPalantir/r4/tree/256af3c72f094b298cd442097ef7c571d8001f29: genuine regression; "invalid suffix `usize`" in derive macro. Has a ton of other build warnings, last updated 6 years ago.
    - Exactly the kind of intended breakage. Minimized down to https://github.com/AmlingPalantir/r4/blob/256af3c72f094b298cd442097ef7c571d8001f29/validates_derive/src/lib.rs#L71-L75, where when interpolation uses `quote`'s `ToTokens` on a `usize` index (i.e. on tuple struct `Tup(())`), the generated suffix becomes `.0usize` (cf. Position 2).
    - Notified crate author of breakage in https://github.com/AmlingPalantir/r4/issues/1.
- Other failures are unrelated or spurious.

## Review remarks

- Commits 1-3 expands the test coverage to better reflect the current situation before doing any functional changes.
- Commit 4 is an intentional **breaking change**. We bump the non-lint "suffixes on a tuple index are invalid" warning into a hard error. Thus, this will need a crater run and a T-lang FCP.

## Tasks

- [x] Run crater to check if anyone is still relying on this being not a hard error. Determine degree of ecosystem breakage.
- [x] If degree of breakage seems acceptable, draft nomination report for T-lang for FCP.
- [x] Determine hard error on Edition 2024+, or on all editions.

## Accompanying Reference update

- https://github.com/rust-lang/reference/pull/1966

[^non-lint]: The FCW was implemented as a *non-lint* warning (meaning it has no associated lint name, and you can't `#![deny(..)]` it) because spans coming from proc macros could not be distinguished from regular field access. This warning was also intentionally impossible to silence. See https://github.com/rust-lang/rust/pull/60186#issuecomment-485581694.

[issue-60210]: https://github.com/rust-lang/rust/issues/60210

### CODE REVIEW

File: compiler/rustc_parse/src/parser/expr.rs [hunk 1]
```diff
@@ -2226,21 +2226,7 @@ impl<'a> Parser<'a> {
     }
 
     pub(super) fn expect_no_tuple_index_suffix(&self, span: Span, suffix: Symbol) {
```
Comment (fmease) [inline compiler/rustc_parse/src/parser/expr.rs]: 3 usage sites, could inline (if you want to), should be 1 line → 1 line change.

File: tests/ui/parser/tuple-index-suffix.rs
Comment (fmease) [inline tests/ui/parser/tuple-index-suffix.rs:1]: Should link to #59418 instead of #60210 or to both at least? This file was renamed from `tests/ui/parser/issues/issue-59418.rs` and enhanced, right?

I see that you linked to #59418 from `tests/ui/parser/tuple-index-suffix-proc-macro.rs` but this here is the "primary" test and the proc-macro one is a "secondary" one.

File: tests/ui/parser/auxiliary/tuple-index-suffix-proc-macro-aux.rs [hunk 2]
```diff
@@ -0,0 +1,33 @@
...
+}
+
+// Expects {IDENT, COMMA, LITERAL}
+#[proc_macro]
+pub fn bad_tup_struct_indexing(input: TokenStream) -> TokenStream {
+    let mut input = input.into_iter();
+
+    let id_tt = input.next().unwrap();
+    let _comma = input.next().unwrap();
+    let tt = input.next().unwrap();
```
Comment (fmease) [inline tests/ui/parser/auxiliary/tuple-index-suffix-proc-macro-aux.rs]: (minor)

```suggestion
    let ident = input.next().unwrap();
    let _comma = input.next().unwrap();
    let lit = input.next().unwrap();
```

`ident` is more conventional compared to `id`. No `_tt` because all of these tokens are wrapped in a token tree (`_comma` is "`TokenTree::Punct(",")`")

**Review by fmease — APPROVED** [review]
r=me after nits and if/once T-lang approves with a fFCP-merge.

File: tests/ui/parser/tuple-index-suffix.rs
Comment (jieyouxu) [reply tests/ui/parser/tuple-index-suffix.rs:1]: Yeah, let me do that, good point

File: tests/ui/parser/auxiliary/tuple-index-suffix-proc-macro-aux.rs (hunk 2 above)
Comment (jieyouxu) [reply tests/ui/parser/auxiliary/tuple-index-suffix-proc-macro-aux.rs]: Changed

File: tests/ui/parser/tuple-index-suffix.rs
Comment (jieyouxu) [reply tests/ui/parser/tuple-index-suffix.rs:1]: Added backlinks

File: compiler/rustc_parse/src/parser/expr.rs (hunk 1 above)
Comment (jieyouxu) [reply compiler/rustc_parse/src/parser/expr.rs]: Inlined

**Comment by jieyouxu** [comment]
Accompanying Reference PR: https://github.com/rust-lang/reference/pull/1966

FWIW, it looks like the `TUPLE_INDEX` grammar production as currently written in the Reference seems wrong, the production would accept more than what the compiler currently does.

**Comment by Zalathar** [comment]
Bors, this has already been merged.

@bors r-
