### PR TITLE
Ship LLVM tools for the correct target when cross-compiling

### LINKED ISSUE #145699: error: unable to run `rust-objcopy`: Bad CPU type in executable (os error 86)
Host:  x86_64-apple-darwin
`rustc 1.91.0-nightly (040a98af7 2025-08-20)`

Compile with error:
`error: unable to run `rust-objcopy`: Bad CPU type in executable (os error 86)`

full output:
```
error: unable to run `rust-objcopy`: Bad CPU type in executable (os error 86)

error: could not compile `proc-macro2` (build script) due to 1 previous error
warning: build failed, waiting for other jobs to finish...
error: could not compile `libc` (build script) due to 1 previous error
```

### PR DESCRIPTION
**Pull request by Kobzol**
The LLVM config returned from the `Llvm` step in bootstrap was always the *host* LLVM config (as we cannot execute the cross-compiled LLVM config). But this wasn't obvious in bootstrap before (there was just a comment about it, but that's it), which caused a bug where bootstrap was copying LLVM tools from the host target to the cross-compiled rustc sysroot. This was probably happening for quite a long time, we just haven't noticed before.

Note that I consider this to be mostly a hotfix, I plan to refactor the LLVM handling in bootstrap soon-ish to make it harder to misuse and be better in general.

Fixes: https://github.com/rust-lang/rust/issues/145699

### CODE REVIEW

File: src/bootstrap/src/core/build_steps/compile.rs [hunk 1]
```diff
@@ -2001,14 +2001,52 @@ impl Step for Assemble {
...
+                    // figure out where binaries are located. We thus have to guess.
+                    let external_llvm_config = builder
+                        .config
+                        .target_config
+                        .get(&target)
+                        .and_then(|t| t.llvm_config.clone());
+                    if let Some(external_llvm_config) = external_llvm_config {
+                        // If we have an external LLVM, just hope that the bindir is the directory
+                        // where the LLVM config is located
+                        external_llvm_config.parent().unwrap().to_path_buf()
```
Comment (bjorn3) [inline src/bootstrap/src/core/build_steps/compile.rs:2029]: Is the llvm-config path canonicalized? If not this logic will probably break on Debian based systems if you use `/usr/bin/llvm-config` as llvm-config as it and the individual executables in `/usr/bin` are symlinks to executables in `/usr/lib/llvm-NN/bin` and thus this would only be copying the symlink I think.

Comment (Kobzol) [reply src/bootstrap/src/core/build_steps/compile.rs:2029]: https://github.com/rust-lang/rust/blob/53744bc255307255728256c3d07f864537cffa33/src/bootstrap/src/core/build_steps/compile.rs#L2078 this should take care of any symlinks.

**Comment by shepmaster** [comment]
Local testing shows that this does fix the problem for macOS.

**Comment by jieyouxu** [comment]
Based on [#t-infra/bootstrap/backports > #145763: beta-nominated](https://rust-lang.zulipchat.com/#narrow/channel/507486-t-infra.2Fbootstrap.2Fbackports/topic/.23145763.3A.20beta-nominated/with/535809721)

@rustbot label: +beta-accepted
