### PR TITLE
Make `std::env::{set_var, remove_var}` unsafe in edition 2024

### LINKED ISSUE #27970: set_var/remove_var are unsound in combination with C code that reads the environment
Like the documentation for our `set_var` (setenv) says, care must be taken with mutating environment variables in a multithreaded program. See [this glibc bug #13271](https://sourceware.org/bugzilla/show_bug.cgi?id=13271) that says getaddrinfo may call getenv.

It looks like we have an unsynchronized call to getaddrinfo and this may cause trouble with glibc/Linux.

Seeing glibc's attitude to setenv in multithreaded programs, `set_var` seems like a big hazard in general(?).

Discovered as an issue tangential to #27966

cc @alexcrichton

### LINKED ISSUE #90308: Consider deprecating and/or modifying behavior of std::env::set_var
Observing an environment variable concurrently with a call to `setenv` constitutes a data race. Rust currently handles this by using a mutex, but that only protects against functions in `std::env`. My interpretation of POSIX (which appears to be the same as the glibc developers') is that any libc function is allowed to call `getenv`. This has already caused problems with `getaddrinfo` in #27970.
Additionally, a large amount of C code calls `getenv` but is otherwise thread-safe. While this isn't necessarily the standard library's issue, it's impossible for third-party libraries to soundly use this code without requiring the user to certify that this isn't an issue via an `unsafe` block. Some examples of this happening in practice are in https://github.com/time-rs/time/issues/293 and https://github.com/rust-lang/flate2-rs/issues/272.
https://github.com/rustsec/advisory-db/issues/926 had several proposals on how this could be handled brought up.

## Make `std::env::set_var` unsafe
This is arguably the cleanest solution to the issue. This could be considered a soundness fix, which would make it an option, but the ecosystem impact feels like it'd be too big.

## Don't actually call `setenv`
`std` could keep track of the environment itself, and make `set_var` changes only visible to `var` and subprocesses. This is probably the way to solve the issue with the least impact on existing code, but the behavior is somewhat unexpected and not zero-cost.

## Only call `setenv` in single-threaded code
This would reduce the impact further, but seems even less expected for negligible benefit.

## Deprecate `std::env::set_var`
This would make it clear that setting an environment variable in the current process is discouraged. It could also be combined with not actually calling `setenv`, which would be my preferred solution to this issue.

### PR DESCRIPTION
**Pull request by tbu-**
Allow calling these functions without `unsafe` blocks in editions up until 2021, but don't trigger the `unused_unsafe` lint for `unsafe` blocks containing these functions.

Fixes #27970.
Fixes #90308.
CC #124866.

### CODE REVIEW

**Comment by RalfJung** [comment]
Should there be a warning on older editions, to make this not come entirely out of the blue when doing edition migration?

**Comment by tbu-** [comment]
> Should there be a warning on older editions, to make this not come entirely out of the blue when doing edition migration?

I agree that this would be quite useful. It seems hard to do right now, though, because a stage 0 compiler will detect a lot of unused `unsafe` blocks because it doesn't know about the `std::env::set_var` unsafety. Perhaps this could be postponed until after one bootstrap cycle?

**Comment by RalfJung** [comment]
> I agree that this would be quite useful. It seems hard to do right now, though, because a stage 0 compiler will detect a lot of unused unsafe blocks because it doesn't know about the std::env::set_var unsafety. Perhaps this could be postponed until after one bootstrap cycle?

I wasn't talking about unused_unsafe, but a lint that warns against using set_var/remove_var outside an unsafe block on old editions.

Also, I am not sure if it's the best idea to add new lang items for these functions. In the past the proposal was to add an attribute for "deprecating safety". Then we could e.g. also add that attribute to [before_exec](https://doc.rust-lang.org/nightly/std/os/unix/process/trait.CommandExt.html#method.before_exec).

**Comment by tbu-** [comment]
> I wasn't talking about unused_unsafe, but a lint that warns against using set_var/remove_var outside an unsafe block on old editions.

Yes. Adding that lint will make bootstrapping harder: Either you put occurrences of `set_var`/`remove_var` in `unsafe` blocks in the compiler code, then it'll trigger the `unused_unsafe` lint in the bootstrap, failing the build or needing `#[allow(unused_unsafe)]` on every occurrence of `set_var`/`remove_var`. Or you don't, and you trigger the lint you propose, needing an `#[allow(future_incompatible_set_env)]` on every occurrence of `set_var`/`remove_var` in the compiler code.

If you wait one bootstrap cycle, you can simply put every occurrence in an `unsafe` block without needing a distinction between pre- and post-bootstrap compiler.

> Also, I am not sure if it's the best idea to add new lang items for these functions. In the past the proposal was to add an attribute for "deprecating safety". Then we could e.g. also add that attribute to [before_exec](https://doc.rust-lang.org/nightly/std/os/unix/process/trait.CommandExt.html#method.before_exec).

I was basically following the advice from https://rust-lang.zulipchat.com/#narrow/stream/268952-edition/topic/.60std.3A.3Aenv.3A.3A.7Bset_var.2C.20remove_var.7D.60.20unsoundness to get this out. This issue has existed for almost 10 years now, and an edition boundary is a good place to fix it.

**Comment by tbu-** [comment]
> > Also, I am not sure if it's the best idea to add new lang items for these functions. In the past the proposal was to add an attribute for "deprecating safety". Then we could e.g. also add that attribute to [before_exec](https://doc.rust-lang.org/nightly/std/os/unix/process/trait.CommandExt.html#method.before_exec).
> 
> <s>This issue has existed for almost 10 years now, and an edition boundary is a good place to fix it.</s>

Sorry, this part doesn't make sense. You're right that an attribute might be better. I'll check whether I'll be able to implement it.

**Comment by RalfJung** [comment]
> Yes. Adding that lint will make bootstrapping harder: Either you put occurrences of set_var/remove_var in unsafe blocks in the compiler code, then it'll trigger the unused_unsafe lint in the bootstrap, failing the build or needing #[allow(unused_unsafe)] on every occurrence of set_var/remove_var. Or you don't, and you trigger the lint you propose, needing an #[allow(future_incompatible_set_env)] on every occurrence of set_var/remove_var in the compiler code.

I imagined the lint would be `allow`ed initially. We can add it in a separate PR. It doesn't have to wait a cycle though, it can be added allow-by-default with some tests setting it to `warn` -- that would help keep sufficient context around among reviewers and yourself.

**Comment by tbu-** [comment]
> I imagined the lint would be `allow`ed initially.

That makes sense. I'll see what I can do. :)

**Comment by tbu-** [comment]
A crater run would probably be useful to see that this doesn't break any crate.

> > I imagined the lint would be `allow`ed initially.
> 
> That makes sense. I'll see what I can do. :)

I'd like to do that in a follow-up PR.

**Comment by RalfJung** [comment]
This doesn't change anything on edition 2021, so how can it break anything...?

**Comment by tbu-** [comment]
The function is marked as `unsafe` in edition 2021 and edition 2024. It's only that calling this specific function is allowed in edition 2021 without using an `unsafe` block. If more complicated stuff is being done to this function in any crate, e.g. taking a function pointer and returning it somewhere else, then that might break.

**Comment by RalfJung** [comment]
Ah, right... I think earlier approaches tried to also allow the implicit coercion to a safe function pointer on an old edition, but I guess the idea is that maybe we don't need that. How hard would it be to do that?

I can start a crater run but its going to take at least a week until we get results.
@bors try

**Comment by tbu-** [comment]
> Ah, right... I think earlier approaches tried to also allow the implicit coercion to a safe function pointer on an old edition, but I guess the idea is that maybe we don't need that.

Yes, my idea is that it's unlikely that someone wants to use this as a function pointer. On the other hand, there are so many crates, so maybe someone actually did it…

> How hard would it be to do that?

I'm not sure, this is my first contribution to the compiler. I'll try to find out.

> I can start a crater run but its going to take at least a week until we get results.

Thanks!

**Comment by RalfJung** [comment]
@craterbot check

File: library/std/src/env.rs [hunk 1]
```diff
@@ -318,10 +318,52 @@ impl Error for VarError {
...
-/// be because invoking it can cause undefined behaviour. The function will be
-/// marked `unsafe` in a future version of Rust. This is tracked in
-/// [rust#27970](https://github.com/rust-lang/rust/issues/27970).
+/// This function is safe to call in a single-threaded program.
+///
+/// In multi-threaded programs, you must ensure that are no other threads
+/// concurrently writing or *reading*(!) from the environment through functions
+/// other than the ones in this module. You are responsible for figuring out
+/// how to achieve this, but we strongly suggest not using `set_var` or
+/// `remove_var` in multi-threaded programs at all.
```
Comment (CryZe) [inline library/std/src/env.rs:327]: Would it also makes sense to mention that this is always safe to call on Windows (and maybe listing other platforms that are well behaved?). My comment is inspired by https://github.com/rust-lang/rust/issues/124866#issuecomment-2102404431 but instead of adding a safe API for Windows, we could at least document it as such.

**Comment by RalfJung** [comment]
Seems to be a single true regression, in https://github.com/mattwparas/steel. I've submitted a [PR](https://github.com/mattwparas/steel/pull/207) to fix that crate.

File: compiler/rustc_driver_impl/src/lib.rs [hunk 2]
```diff
@@ -1307,7 +1307,11 @@ fn ice_path() -> &'static Option<PathBuf> {
 /// internal features.
 ///
 /// A custom rustc driver can skip calling this to set up a custom ICE hook.
-pub fn install_ice_hook(
+///
+/// # Unsafety
+///
+/// This function modifies the environment and has the same safety as [`std::env::set_var`].
+pub unsafe fn install_ice_hook(
```
Comment (RalfJung) [inline compiler/rustc_driver_impl/src/lib.rs:1314]: If this is only for setting RUST_BACKTRACE, maybe use https://doc.rust-lang.org/nightly/std/panic/fn.set_backtrace_style.html instead.

In general I think we should separate "making the compiler not trigger the new lint" from the PR that introduces the lint, or else review will easily get terribly derailed. (For instance, with such a large unsafe fn, we'd definitely want to enable `unsafe_op_in_unsafe_fn` as well.)

File: library/std/src/env.rs [hunk 3]
```diff
@@ -318,10 +318,52 @@ impl Error for VarError {
...
+///
+/// Most C libraries, including libc itself do not advertise which functions
```
Comment (RalfJung) [inline library/std/src/env.rs:329]:
```suggestion
/// Most C libraries, including libc itself, do not advertise which functions
```

File: library/std/src/env.rs [hunk 4]
```diff
@@ -350,18 +392,23 @@ impl Error for VarError {
...
 /// use std::env;
 ///
 /// let key = "KEY";
-/// env::set_var(key, "VALUE");
+/// unsafe {
+///     env::set_var(key, "VALUE");
+/// }
 /// assert_eq!(env::var(key), Ok("VALUE".to_string()));
 /// ```
+#[cfg(bootstrap)]
```
Comment (RalfJung) [inline library/std/src/env.rs:405]: The bootstrap-only version of the function never shows up in docs, so it doesn't need a doc comment (or only a dummy comment to satisfy a lint). That should avoid the duplication and make the diff easier to review.

File: library/std/src/env.rs [hunk 5]
```diff
@@ -350,18 +392,23 @@ impl Error for VarError {
 /// # Examples
 ///
 /// ```
+/// # #![allow(unused_unsafe)]
+///
```
Comment (RalfJung) [inline library/std/src/env.rs:396]:
```suggestion
```
or else the empty line would show in the docs

File: library/std/src/env.rs [hunk 6]
```diff
@@ -403,22 +445,81 @@ fn _set_var(key: &OsStr, value: &OsStr) {
...
+/// This function may panic if `key` is empty, contains an ASCII equals sign
+/// `'='` or the NUL character `'\0'`, or when the value contains the NUL
+/// character.
+///
+/// # Examples
+///
+/// ```no_run
+/// # #![allow(unused_unsafe)]
+///
```
Comment (RalfJung) [inline library/std/src/env.rs:502]:
```suggestion
```

Comment (tbu-) [reply library/std/src/env.rs]: Done.

File: library/std/src/env.rs (hunk 5 above)
Comment (tbu-) [reply library/std/src/env.rs]: Done.

File: library/std/src/env.rs (hunk 4 above)
Comment (tbu-) [reply library/std/src/env.rs:366]: Done.

File: library/std/src/env.rs (hunk 3 above)
Comment (tbu-) [reply library/std/src/env.rs]: Done.

File: library/std/src/env.rs (hunk 1 above)
Comment (tbu-) [reply library/std/src/env.rs]: Done.

File: compiler/rustc_driver_impl/src/lib.rs (hunk 2 above)
Comment (tbu-) [reply compiler/rustc_driver_impl/src/lib.rs]: > If this is only for setting RUST_BACKTRACE, maybe use https://doc.rust-lang.org/nightly/std/panic/fn.set_backtrace_style.html instead.

Done.

> In general I think we should separate "making the compiler not trigger the new lint" from the PR that introduces the lint, or else review will easily get terribly derailed. (For instance, with such a large unsafe fn, we'd definitely want to enable `unsafe_op_in_unsafe_fn` as well.)

Factored out into #125063.

**Comment by Amanieu** [comment]
FCP for making these functions `unsafe` in edition 2024. For the actual implementation, this could be reviewed by the compiler team.

@rfcbot fcp merge

**Comment by Amanieu** [comment]
Yes, it should.

@rfcbot cancel

**Comment by Amanieu** [comment]
@rfcbot merge

**Comment by jhpratt** [comment]
> Should there be a warning on older editions, to make this not come entirely out of the blue when doing edition migration?

Big :+1: here, even if not part of this PR. If it is a hard error in ≥e2024 and a warning in ≤e2021, that would be sufficient for me to remove the soundness checks I have in place specifically to avoid this edge case. It may not be possible for a different reason, but I know it's not possible as-is.

Ideally I'd prefer force-warn given the safety implications, for what it's worth.

**Comment by tbu-** [comment]
> Big 👍 here, even if not part of this PR.

I'm planning to create a follow-up PR.

File: library/std/src/sys/pal/solid/os.rs [hunk 7]
```diff
@@ -191,19 +191,19 @@ pub fn getenv(k: &OsStr) -> Option<OsString> {
     .flatten()
 }
 
-pub fn setenv(k: &OsStr, v: &OsStr) -> io::Result<()> {
+pub unsafe fn setenv(k: &OsStr, v: &OsStr) -> io::Result<()> {
     run_with_cstr(k.as_bytes(), &|k| {
         run_with_cstr(v.as_bytes(), &|v| {
             let _guard = ENV_LOCK.write();
-            cvt_env(unsafe { libc::setenv(k.as_ptr(), v.as_ptr(), 1) }).map(drop)
+            cvt_env(libc::setenv(k.as_ptr(), v.as_ptr(), 1)).map(drop)
```
Comment (riking) [inline library/std/src/sys/pal/solid/os.rs:198]: This should probably be converted to `unsafe_op_in_unsafe_function` style and keep the unsafe block here.

File: library/std/src/env.rs [hunk 8]
```diff
@@ -318,20 +318,18 @@ impl Error for VarError {
...
-/// how to achieve this, but we strongly suggest not using `set_var` or
-/// `remove_var` in multi-threaded programs at all.
+/// This function is also always safe to call on Windows, in single-threaded
+/// and multi-threaded programs.
 ///
-/// Most C libraries, including libc itself do not advertise which functions
+/// In multi-threaded programs on other operating systems, you must ensure that
+/// are no other threads concurrently writing or *reading*(!) from the
+/// environment through functions other than the ones in this module. You are
+/// responsible for figuring out how to achieve this, but we strongly suggest
```
Comment (oxalica) [inline library/std/src/env.rs:329]: So it's already the caller responsibility to avoid racing, and the functions are unsafe now. Then could we remove the lock in the implementation of `_set_var` and `_remove_var`?

Comment (RalfJung) [reply library/std/src/env.rs:329]: Let's not overdo it. There's likely tons of Rust code out there that isn't super careful about environment variable races, and that's entirely our fault as we made these functions safe. I don't think there is a reason to make this code more broken than it is today.

Maybe once a large fraction of the ecosystem is adjusted to the new world, we can consider this. But the lock doesn't cost us that much (IIRC even the fork/exec in `Command` now deals with the lock properly), so I feel like it'd be a disservice to all the code out there that relies on the lock to remove it "just because we can".

File: library/std/src/sys/pal/solid/os.rs (hunk 7 above)
Comment (tbu-) [reply library/std/src/sys/pal/solid/os.rs]: Done.

File: library/std/src/env.rs [hunk 9]
```diff
@@ -318,20 +318,18 @@ impl Error for VarError {
...
+/// not using `set_var` or `remove_var` in multi-threaded programs at all.
```
Comment (RalfJung) [inline library/std/src/env.rs:330]:
```suggestion
/// environment through functions or global variables other than the ones in this module.
///  These operating systems unfortunately provide no thread-safe way to mutate the
/// environment, so you are responsible for figuring out how to achieve this, e.g. by
/// carefully controlling all the code that runs in all concurrent threads. We strongly
///  suggest not using `set_var` or `remove_var` in multi-threaded programs at all.
```

File: library/std/src/env.rs [hunk 10]
```diff
@@ -318,20 +318,18 @@ impl Error for VarError {
...
+///
+/// Most C libraries, including libc itself, do not advertise which functions
 /// read from the environment. Even functions from the Rust standard library do
 /// that, e.g. for DNS lookups from [`std::net::ToSocketAddrs`].
```
Comment (RalfJung) [inline library/std/src/env.rs:334]: This should probably be part of the previous paragraph? It's part of "what needs to be done to ensure that no concurrent threads read or write the environment".

File: library/std/src/env.rs (hunk 9 above)
Comment (tbu-) [reply library/std/src/env.rs]: Done.

File: library/std/src/env.rs (hunk 10 above)
Comment (tbu-) [reply library/std/src/env.rs:336]: Hmm, I think the paragraph is long enough as-is. I'd say it's okay since this gives a wider view of the ecosystem.

Comment (RalfJung) [reply library/std/src/env.rs:336]: It should be one paragraph, one point. Currently this paragraph sits here on its own in a somewhat disconnected way to the rest of the document, which is confusing. "Why are you telling me this? Oh, it's part of that argument in the middle of the previous paragraph..."

Comment (tbu-) [reply library/std/src/env.rs]: Done.

File: library/std/src/env.rs [hunk 11]
```diff
@@ -318,22 +318,21 @@ impl Error for VarError {
...
+/// In multi-threaded programs on other operating systems, you must ensure that
+/// environment through functions or global variables other than the ones in
+/// this module. These operating systems unfortunately provide no thread-safe
+/// way to mutate the environment, so you are responsible for figuring out how
+/// to achieve this, carefully controlling all the code that runs in all
+/// concurrent threads. We strongly suggest not using `set_var` or `remove_var`
+/// in multi-threaded programs at all. Most C libraries, including libc itself,
+/// do not advertise which functions read from the environment. Even functions
+/// from the Rust standard library do that, e.g. for DNS lookups from
+/// [`std::net::ToSocketAddrs`].
```
Comment (RalfJung) [inline library/std/src/env.rs:335]: Something went wrong here with the suggestion it seems, this isn't even a sentence any more.
```suggestion
/// In multi-threaded programs on other operating systems, we strongly suggest
/// not using `set_var` or `remove_var` at all.
/// The exact requirement is: you must ensure that
/// there are no other threads concurrently writing or *reading*(!) from the
/// environment through functions or global variables other than the ones in
/// this module.
/// The problem is that these operating systems do not provide a thread-safe
/// way to read the environment, and most C libraries, including libc itself,
/// do not advertise which functions read from the environment. Even functions
/// from the Rust standard library may read the environment without going
/// through this module, e.g. for DNS lookups from
/// [`std::net::ToSocketAddrs`]. No stable guarantee is made about which functions
/// may read from the environment in future versions of a library.
/// All this makes it not practically possible for you to guarantee that no other thread
/// will read the environment, so the only safe option is to not use `set_var` or
/// `remove_var` in multi-threaded programs at all.
```

Comment (RalfJung) [reply library/std/src/env.rs:335]: We currently guarantee it and I don't think we should remove that. This change is already disruptive enough as it is, let's avoid making it any worse than absolutely necessary.

Comment (tbu-) [reply library/std/src/env.rs]: Do we gain something from keeping this lock in the documentation and thus likely forever in the code? I'd say that realistically, almost all Rust code calling this cannot guarantee that all environment access goes through these functions, but might think it can. As such, it might be negative to document it this way.

Changed it to your suggestion anyway.

**Comment by traviscross** [comment]
Before this PR is merged, the edition team would prefer if the planned migration lints that will wrap these calls in `unsafe { .. }` could first be added to it.  Doing so better facilitates how we test the edition with crater.

This will also likely result in a better experience for users, as if these deprecation warnings were to land in a stable release before these migration lints, users would not be able to benefit from the ability to use `cargo fix` to resolve these warnings.

cc @joboet @tbu

**Comment by jhpratt** [comment]
On the contrary, wouldn't automatically putting the calls in an `unsafe` block as part of the migration defeat the purpose in part? People would be far more likely to not think about the safety invariants if it is seemingly done for them.

**Comment by traviscross** [comment]
The way we test the edition using crater is that we run the migration lints, then we test that the migrated code works in the new edition.  Anything without an automated migration lint interferes with this.

In some cases, where we really do want people to have to check things carefully because what they were doing was almost certainly wrong, we can bend a bit.  Disallowing references to `static mut` is an example of this.  We're choosing to not add a semantics-preserving migration lint (though we could) because, in nearly all cases, the code that will be broken by this was not correct to begin with.  The number of crates broken is also manageable.

This case seems different.  Most code that will be broken by this probably isn't wrong, and most people probably will just wrap all of these calls in `unsafe`.  And I'd intuitively expect this to break a lot more crates.

RFC 3085 specifies:

> When we release a new edition, we also release tooling to automate the migration of crates. Some manual work may be required but that should be uncommon.

What will be broken here seems maybe a bit too *common*.

**Comment by tbu-** [comment]
> Most code that will be broken by this probably isn't wrong,

I doubt it, to be honest. I'd say that most code that will be broken by this is actually wrong.

> and most people probably will just wrap all of these calls in `unsafe`.

And thus I think this is a bad outcome.

> And I'd intuitively expect this to break a lot more crates. What will be broken here seems maybe a bit too _common_.

I agree with this point. Especially about testing the new edition. I'd still be wary of telling *users* that what they're doing is most likely okay and that they'll just need to sprinkle a little `unsafe` in there.

Even just auditing the standard library, I think most usages I saw weren't okay. E.g. tests setting environment variables are immediately out because they can run in parallel with other threads which almost certainly call into some C functions.

**Comment by traviscross** [comment]
Fair enough about there being a lot of incorrect uses that will need to be reviewed.  Hopefully the insertion of `unsafe { .. }` will still be enough to spook people into doing this.

In terms of correct uses, I'm thinking about all the uses in `build.rs`, in single-threaded CLI applications, and the many uses that happen right at the start of `main` before any threads are spawned.

**Comment by RalfJung** [comment]
Maybe the lint could insert something like
```rust
// FIXME: audit the code to ensure this only occurs in single-threaded code.
unsafe { ... }
```

**Comment by traviscross** [comment]
Adding such a comment as @RalfJung suggests makes sense to me.

**Comment by tbu-** [comment]
I added a lint with machine-applicable suggestions. I wanted to get the `set_var`/`remove_var` independently, but now it also contains the lint because it's useful for crater testing. I'd like to address non-critical feedback to the lint in a separate PR so that the main change can go in sooner.

**Review by traviscross — APPROVED** [review]
From the edition side, this looks good to me.

File: library/std/src/env.rs (hunk 11 above)
Comment (saethlin) [reply library/std/src/env.rs]: > Do we gain something from keeping this lock in the documentation and thus likely forever in the code?

It should probably be in the code permanently as a basic security mitigation. I think it's unreasonable to consider programs that need super-fast environment access; environment access should generally be hoisted as far as possible to the beginning of a program. So I don't really see that there is a downside here.

But for applications that do need do so some environment modification, we are either making it harder for things to go wrong, or automating adding the lock that a pure-Rust program would need.

**Review by jhpratt — APPROVED** [review]
LGTM from a libs perspective. I don't see any issues from a compiler perspective, but I'm not a reviewer for that.

This needs a compiler reviewer to sign off and we should be good to go, I believe.

**Comment by RalfJung** [comment]
r? compiler

File: tests/ui/rust-2024/unsafe-env.rs [hunk 12]
```diff
@@ -0,0 +1,30 @@
...
+
+use std::env;
+
+unsafe fn unsafe_fn() {}
+fn safe_fn() {}
+
+#[deny(unused_unsafe)]
+fn main() {
+    env::set_var("FOO", "BAR");
+    //[e2024]~^ ERROR [E0133]
```
Comment (petrochenkov) [inline tests/ui/rust-2024/unsafe-env.rs:14]:
```suggestion
    //[e2024]~^ ERROR call to unsafe function `set_var` is unsafe
```
Could you use human readable error annotations in all tests?

File: library/std/src/env.rs [hunk 13]
```diff
@@ -318,22 +318,25 @@ impl Error for VarError {
...
+/// than the ones in this module. The problem is that these operating systems
+/// do not provide a thread-safe way to read the environment, and most C
+/// libraries, including libc itself, do not advertise which functions read
+/// from the environment. Even functions from the Rust standard library may
+/// read the environment without going through this module, e.g. for DNS
+/// lookups from [`std::net::ToSocketAddrs`]. No stable guarantee is made about
+/// which functions may read from the environment in future versions of a
+/// library. All this makes it not practically possible for you to guarantee
+/// that no other thread will read the environment, so the only safe option is
+/// to not use `set_var` or `remove_var` in multi-threaded programs at all.
```
Comment (petrochenkov) [inline library/std/src/env.rs:339]: If you are in a multi-threaded *program*, but is, for example, still at its very beginning and haven't created any threads except the main one.
Maybe tweak the wording in the direction from "multi-threaded program" to "process that currently has multiple threads"? Or it's already clear from the context?

File: library/std/src/env.rs [hunk 14]
```diff
@@ -353,15 +356,26 @@ impl Error for VarError {
...
 ///
 /// let key = "KEY";
-/// env::set_var(key, "VALUE");
+/// unsafe {
+///     env::set_var(key, "VALUE");
+/// }
 /// assert_eq!(env::var(key), Ok("VALUE".to_string()));
 /// ```
+#[cfg(not(bootstrap))]
+#[rustc_deprecated_safe_2024]
```
Comment (petrochenkov) [inline library/std/src/env.rs:365]:
```suggestion
#[cfg_attr(not(bootstrap), rustc_deprecated_safe_2024)]
```
The `unsafe` block in the body can be used unconditionally.

File: tests/ui/rust-2024/unsafe-env.rs (hunk 12 above)
Comment (petrochenkov) [reply tests/ui/rust-2024/unsafe-env.rs:14]: All these annotations are for humans to double check, if something changes a human should go and manually verify and update the new error text.

Technically we could not have these annotations at all because all the errors are already in `.stderr` files, but that would just gradually turned the test suite into garbage because it's hard to match the contents of `.rs` and `.stderr` files during review (especially given that stderr files don't have line numbers now). In testing redundancy is good.

File: library/std/src/env.rs (hunk 14 above)
Comment (tbu-) [reply library/std/src/env.rs:365]: The difference between the `#[cfg(bootstrap)]` and `#[cfg(not(bootstrap))]` is mostly whether the function itself is `unsafe` – I'm not aware of a method to conditionally mark a function as unsafe.

File: tests/ui/rust-2024/unsafe-env.rs (hunk 12 above)
Comment (tbu-) [reply tests/ui/rust-2024/unsafe-env.rs]: Fixed. Thanks for the explanation!

File: library/std/src/env.rs (hunk 13 above)
Comment (tbu-) [reply library/std/src/env.rs:339]: I'd say it's already clear from the context. This is at the end of an already long explanation, I think "process that currently has multiple threads" would make it more confusing.

**Comment by RalfJung** [comment]
CI passed, though...

**Comment by ChrisDenton** [comment]
Maybe bors picked up an old commit again

**Comment by Skgland** [comment]
For me the hostory looks like this:

> tbu- force-pushed the pr_env_unsafe branch from [bbeccea ](https://github.com/rust-lang/rust/commit/bbecceade61b0cd8077ba46052707e269f9b56ba)to [44f9f8b ](https://github.com/rust-lang/rust/commit/44f9f8bc33c0b5537c52c9e18697b83f12f19604)

> @bors r+

> 📌 Commit [bbeccea](https://github.com/rust-lang/rust/commit/bbecceade61b0cd8077ba46052707e269f9b56ba) has been approved by `petrochenkov`
> 
> It is now in the [queue](https://bors.rust-lang.org/homu/queue/rust) for this repository.

looks like it picked up the commit before the force push

**Comment by RalfJung** [comment]
Yeah, looks like the commit it picked up was 1h outdated at that point. Wow that's bad.
Let's see if it got the latest one now.

@bors r=petrochenkov

**Comment by jstarks** [comment]
@jhpratt I think you probably didn't mean to change the title.

**Comment by BoxyUwU** [comment]
This had the relnotes label added but as far as I can tell this only affects 2024 edition. Is that understanding correct or is there a subtle stable affecting change here :3

File: compiler/rustc_mir_build/messages.ftl [hunk 15]
```diff
@@ -28,6 +28,12 @@ mir_build_borrow_of_moved_value = borrow of moved value
     .value_borrowed_label = value borrowed here after move
     .suggestion = borrow this binding in the pattern to avoid moving the value
 
+mir_build_call_to_deprecated_safe_fn_requires_unsafe =
+    call to deprecated safe function `{$function}` is unsafe and requires unsafe block
+    .note = consult the function's documentation for information on how to avoid undefined behavior
+    .label = call to unsafe function
+    .suggestion = you can wrap the call in an `unsafe` block if you can guarantee the code is only ever called from single-threaded code
```
Comment (joshtriplett) [inline compiler/rustc_mir_build/messages.ftl:35]: This will be incorrect if we mark any other functions with this attribute where the unsafety is for a different reason.

**Comment by joshtriplett** [comment]
@beetrees Yikes, that doesn't seem right. That sounds like a bug in the implementation of rustc_deprecated_safe_2024; If you're allowed to treat the function as safe, you should be allowed to do anything with it you could have with a safe function, including passing it as an argument.

**Comment by RalfJung** [comment]
That was a deliberate choice evaluated with crater. From my understanding, it is quite tricky to hook into the type system to achieve this, and it is what stalled the previous attempt at implementing this.

File: compiler/rustc_mir_build/messages.ftl (hunk 15 above)
Comment (tbu-) [reply compiler/rustc_mir_build/messages.ftl:35]: Yes, it'll be fixed before #125970 is merged. This PR was intentionally minimal so it could definitely make it into the Rust 2024 edition.

**Comment by cuviper** [comment]
For safe function pointers, a workaround is that you can wrap them in a safe closure.

```rust
let x: fn(OsString, OsString) = |name, value| std::env::set_var(name, value);
```

It's unfortunate, but maybe someone will figure out how to make this unnecessary later. Or it will just become moot after everyone migrates to 2024+ and they really are unsafe.

File: library/std/src/env.rs (hunk 13 above)
Comment (marcospb19) [inline library/std/src/env.rs:339]: > so the only safe option is to not use `set_var` or `remove_var` in multi-threaded programs at all

Can't we use a static Mutex to guard env reads and writes? If so, saying that "the only option is not to use this" sounds misleading.

Comment (ChrisDenton) [reply library/std/src/env.rs:339]: No we cannot. There's a lot of discussion about that on the linked issues but in short that would only make it safe for Rust std and then only if all FFI was guarded by that Mutex (because any libc function is allowed to read the environment).

File: library/std/src/env.rs [hunk 16]
```diff
@@ -403,22 +420,35 @@ fn _set_var(key: &OsStr, value: &OsStr) {
 ///
 /// # Examples
 ///
-/// ```
+/// ```no_run
```
Comment (RalfJung) [inline library/std/src/env.rs:423]: Would have been good to add a comment explaining why this is `no_run`. Are you worried about UB in the doctest?

*[View changes since the review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/rust/124636/debd22da66cfa97c74040ebf68e420672ac8560e..44f9f8bc33c0b5537c52c9e18697b83f12f19604)*

Comment (tbu-) [reply library/std/src/env.rs:423]: Yes, I'm worried about that. The doctest has no safety documentation, and I wouldn't know how I could prove that no other thread is running concurrently to it.

Comment (ChrisDenton) [reply library/std/src/env.rs:423]: It is not safe to use in a doctest. We would need to use an integration test.

A doctest could work on platforms where `set_var` is thread safe but I'm not sure there's much utility in a test only for those platforms if we can have something that works cross-platform.
