### PR TITLE
Fix error message for calling a non-tuple struct

### LINKED ISSUE #148919: “cannot initialize a tuple struct which contains private fields” with no tuple struct involved
### Code

```Rust
struct Foo {}
struct Bar {}

impl Foo {
    fn into_bar(self) -> Bar {
        Bar(self)
    }
}
```

### Current output

```Shell
error[E0423]: cannot initialize a tuple struct which contains private fields
 --> src/lib.rs:6:9
  |
6 |         Bar(self)
  |         ^^^
  |
  = note: constructor is not visible here due to private fields
```

### Desired output

```Shell
error[E0423]: expected function, tuple struct or tuple variant, found struct `Bar`
 --> src/lib.rs:6:9
  |
6 |         Bar(self)
  |         ^^^
```

### Rationale and extra context

The message is incorrect in two ways:

* `Bar` is not a tuple struct
* `Bar` has no private fields

It appears that something is making too many assumptions about why a tuple struct constructor might not be visible at a specific call site.

### Other cases

The incorrect diagnostic only occurs for `Bar(self)`, and not when a normal variable is used in place of `self`. It also seems like sometimes the correct error is printed, nondeterministically, but I have not found consistent reproduction conditions.

### Rust Version

```Shell
rustc 1.93.0-nightly (01867557c 2025-11-12)
binary: rustc
commit-hash: 01867557cd7dbe256a031a7b8e28d05daecd75ab
commit-date: 2025-11-12
host: aarch64-apple-darwin
release: 1.93.0-nightly
LLVM version: 21.1.5
```

### Anything else?

@rustbot label +regression-from-stable-to-nightly

### PR DESCRIPTION
**Pull request by Jamesbarford**
This feels a bit odd checking for `"0"` but I can't see how else to check for it being a Tuple

closes https://github.com/rust-lang/rust/issues/148919

### CODE REVIEW

File: compiler/rustc_resolve/src/late/diagnostics.rs [hunk 1]
```diff
@@ -1642,6 +1644,17 @@ impl<'ast, 'ra, 'tcx> LateResolutionVisitor<'_, 'ast, 'ra, 'tcx> {
         }
     }
 
+    fn has_tuple_fields(&mut self, def_id: DefId) -> bool {
```
Comment (fmease) [inline compiler/rustc_resolve/src/late/diagnostics.rs]: I'm relatively sure the proper way to check if a definition is a tuple struct is something like:

```rs
let adt_def = tcx.adt_def(def_id);
adt_def.is_struct() && adt_def.non_enum_variant().ctor_kind() == Some(CtorKind::Fn)
```

No guarantees.

Comment (Jamesbarford) [reply compiler/rustc_resolve/src/late/diagnostics.rs]: Thanks for the suggestion, however when doing `self.r.tcx.adt_def(def_id)` I encounter this error
```
error[E0391]: cycle detected when looking up span for `m::S`
```

However it got me thinking checking the constructor definition to see if it is a `ctor` & `fn` is a less brittle solution; 3d3394200adbb6749b58cfe5238ea9a853a5fb68

Comment (fmease) [reply compiler/rustc_resolve/src/late/diagnostics.rs]: Ah right, we're in `rustc_resolve` which is too early for that query, missed that
