### PR TITLE
Fix invalid macro tag generation for keywords which can be followed by values

### LINKED ISSUE #148617: ICE: Didn't find 'Class::Original' to close
```rust
// src/lib.rs

enum Enum {
    Variant,
}

pub fn repro() {
    if !matches!(Enum::Variant, Enum::Variant) {}
}
```

`cargo rustdoc --lib --config='build.rustdocflags=["-Zunstable-options", "--generate-macro-expansion"]'`

```console
thread 'rustc' (2263394) panicked at src/librustdoc/html/highlight.rs:449:9:
Didn't find `Class::Original` to close
stack backtrace:
   0:     0x7bc6e245f223 - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::hde21067283f7e82e
   1:     0x7bc6e2c01afc - core::fmt::write::h24186904251c31cb
   2:     0x7bc6e2413d93 - std::io::Write::write_fmt::h3ab9f1f4d8d19b72
   3:     0x7bc6e24253a2 - std::sys::backtrace::BacktraceLock::print::he038489aba5894a6
   4:     0x7bc6e242b3f9 - std::panicking::default_hook::{{closure}}::h80a26d916c49679b
   5:     0x7bc6e242af23 - std::panicking::default_hook::he2e9efee79b3dce9
   6:     0x7bc6e1420c91 - std[e95ebcffb71a5621]::panicking::update_hook::<alloc[6ba2be5df7d20276]::boxed::Box<rustc_driver_impl[8bc3447375e6b2d8]::install_ice_hook::{closure#1}>>::{closure#0}
   7:     0x7bc6e242b81f - std::panicking::panic_with_hook::hf5648b7cec6bc73e
   8:     0x7bc6e242b5a6 - std::panicking::panic_handler::{{closure}}::h1b2ed3864ba94359
   9:     0x7bc6e24254e9 - std::sys::backtrace::__rust_end_short_backtrace::hd0186b2b27f5aaa7
  10:     0x7bc6e24060dd - __rustc[f7dae8b92efe1d7a]::rust_begin_unwind
  11:     0x7bc6df472000 - core::panicking::panic_fmt::hb5d6b83773432920
  12:     0x5acfe30cf3ba - rustdoc[f6dad7f1425a8a52]::html::highlight::end_expansion::<core[a4c7c2348b0f0abe]::fmt::Formatter>
  13:     0x5acfe31828dd - rustdoc[f6dad7f1425a8a52]::html::highlight::write_code::<core[a4c7c2348b0f0abe]::fmt::Formatter>::{closure#2}
  14:     0x5acfe3279907 - <rustdoc[f6dad7f1425a8a52]::html::highlight::Classifier>::advance
  15:     0x5acfe327a53b - <rustdoc[f6dad7f1425a8a52]::html::highlight::Classifier>::highlight
  16:     0x5acfe30ce825 - rustdoc[f6dad7f1425a8a52]::html::highlight::write_code::<core[a4c7c2348b0f0abe]::fmt::Formatter>
  17:     0x5acfe338b10b - <&core[a4c7c2348b0f0abe]::fmt::builders::FromFn<rustdoc[f6dad7f1425a8a52]::html::sources::print_src<&mut core[a4c7c2348b0f0abe]::fmt::Formatter>::{closure#0}> as core[a4c7c2348b0f0abe]::fmt::Display>::fmt
  18:     0x7bc6e2c01afc - core::fmt::write::h24186904251c31cb
  19:     0x5acfe338b7cb - <&askama[1cc127e36e4e4cf3]::filters::escape::Safe<&core[a4c7c2348b0f0abe]::fmt::builders::FromFn<rustdoc[f6dad7f1425a8a52]::html::sources::print_src<&mut core[a4c7c2348b0f0abe]::fmt::Formatter>::{closure#0}>> as core[a4c7c2348b0f0abe]::fmt::Display>::fmt
  20:     0x7bc6e2c01afc - core::fmt::write::h24186904251c31cb
  21:     0x5acfe3354195 - <rustdoc[f6dad7f1425a8a52]::html::sources::SourceCollector as rustdoc[f6dad7f1425a8a52]::visit::DocVisitor>::visit_item
  22:     0x5acfe3212fe8 - <rustdoc[f6dad7f1425a8a52]::html::render::context::Context>::init
  23:     0x5acfe3188938 - rustdoc[f6dad7f1425a8a52]::main_args::{closure#2}::{closure#0}
  24:     0x5acfe317d4ce - rustc_interface[d5ff205a9ab97820]::interface::run_compiler::<(), rustdoc[f6dad7f1425a8a52]::main_args::{closure#2}>::{closure#1}
  25:     0x5acfe30c5d08 - std[e95ebcffb71a5621]::sys::backtrace::__rust_begin_short_backtrace::<rustc_interface[d5ff205a9ab97820]::util::run_in_thread_with_globals<rustc_interface[d5ff205a9ab97820]::util::run_in_thread_pool_with_globals<rustc_interface[d5ff205a9ab97820]::interface::run_compiler<(), rustdoc[f6dad7f1425a8a52]::main_args::{closure#2}>::{closure#1}, ()>::{closure#0}, ()>::{closure#0}::{closure#0}, ()>
  26:     0x5acfe31aec8d - <<std[e95ebcffb71a5621]::thread::Builder>::spawn_unchecked_<rustc_interface[d5ff205a9ab97820]::util::run_in_thread_with_globals<rustc_interface[d5ff205a9ab97820]::util::run_in_thread_pool_with_globals<rustc_interface[d5ff205a9ab97820]::interface::run_compiler<(), rustdoc[f6dad7f1425a8a52]::main_args::{closure#2}>::{closure#1}, ()>::{closure#0}, ()>::{closure#0}::{closure#0}, ()>::{closure#1} as core[a4c7c2348b0f0abe]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  27:     0x7bc6e3a95daf - std::sys::thread::unix::Thread::new::thread_start::hb3dc6483caa1b987
  28:     0x7bc6dd49caa4 - start_thread
                               at ./nptl/pthread_create.c:447:8
  29:     0x7bc6dd529c6c - clone3
                               at ./misc/../sysdeps/unix/sysv/linux/x86_64/clone3.S:78:0
  30:                0x0 - <unknown>

error: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-rustdoc&template=ice.md

note: please make sure that you have updated to the latest nightly

note: please attach the file at `/git/repro/rustc-ice-2025-11-07T03_41_46-2263393.txt` to your bug report

note: compiler flags: --crate-type lib -Z unstable-options

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
```

Bisects to https://github.com/rust-lang/rust/pull/148573. Likely https://github.com/rust-lang/rust/pull/148213 but I did not confirm for sure. @GuillaumeGomez @yotamofek

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Fixes https://github.com/rust-lang/rust/issues/148617.

The problem didn't come from the `generate-macro-expansion` feature but was actually uncovered thanks to it.

Keywords like `if` or `return`, when followed by a `!` were considered as macros, which was wrong and let to invalid class stack and to the panic.

~~While working on it, I realized that `_` was considered as a keyword, so I fixed that as well in the second commit.~~ (reverted, see https://github.com/rust-lang/rust/pull/148655#issuecomment-3508220823, https://github.com/rust-lang/rust/pull/148655#issuecomment-3508262637)

r? @yotamofek

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
CI passed \o/

File: src/librustdoc/html/highlight.rs [hunk 1]
```diff
@@ -1249,7 +1269,18 @@ impl<'src> Classifier<'src> {
                         "self" | "Self" => Class::Self_(new_span(before, text, file_span)),
                         _ => Class::Ident(new_span(before, text, file_span)),
                     },
-                    Some(c) => c,
+                    Some(c) => {
+                        // So if it's not a keyword which can be followed by a value (like `if` or
+                        // `return`) and the next non-whitespace token is a `!`, then we consider
+                        // it's a macro.
+                        if !KEYWORDS_FOLLOWABLE_BY_VALUE.contains(&text)
+                            && self.peek_non_whitespace() == Some(TokenKind::Bang)
```
Comment (yotamofek) [inline src/librustdoc/html/highlight.rs]: nit:

I think it would be more consistent (with previous match arms) to put this condition in a match guard. (and then have another `Some(c) => c` arm, like before)

File: src/librustdoc/html/highlight.rs [hunk 2]
```diff
@@ -1223,17 +1242,18 @@ impl<'src> Classifier<'src> {
...
             },
             TokenKind::GuardedStrPrefix => return no_highlight(sink),
-            TokenKind::Ident | TokenKind::RawIdent
-                if self.peek_non_whitespace() == Some(TokenKind::Bang) =>
-            {
-                self.in_macro = true;
-                let span = new_span(before, text, file_span);
-                sink(DUMMY_SP, Highlight::EnterSpan { class: Class::Macro(span) });
-                sink(span, Highlight::Token { text, class: None });
+            TokenKind::RawIdent if self.peek_non_whitespace() == Some(TokenKind::Bang) => {
```
Comment (yotamofek) [inline src/librustdoc/html/highlight.rs]: might be missing something and maybe too lazy to dig in any deeper, but why did you remove `TokenKind::Ident` from this arm?

**Comment by yotamofek** [comment]
This *looks* absolutely fine, the fixture is more correct, and it adds more tests without breaking any previous ones, so I'd approve this...
but I've already approved two related PRs that introduced/uncovered edge cases, so I think I'd be inclined to wait for another r+ this time 😅 (maybe @lolbinarycat if you the time?)

File: tests/rustdoc/source-code-pages/keyword-macros.rs [hunk 3]
```diff
@@ -0,0 +1,19 @@
+// This test ensures that keywords which can be followed by values (and therefore `!`)
+// are not considered as macros.
+// This is a regression test for <https://github.com/rust-lang/rust/issues/148617>.
+
+#![crate_name = "foo"]
+
+//@ has 'src/foo/keyword-macros.rs.html'
+
+fn a() {
```
Comment (yotamofek) [inline tests/rustdoc/source-code-pages/keyword-macros.rs:20]: Maybe add at least one test case where the `!` is not separated by whitespace from the keyword?
e.g. `if! true{}`
To make sure it works, and doesn't regress in the future.

Also, do we have tests for `!`s following punctuation? e.g. something like `const ARR: [u8; 2] = [!0,! 0];`?

File: src/librustdoc/html/highlight.rs (hunk 2 above)
Comment (GuillaumeGomez) [reply src/librustdoc/html/highlight.rs]: Because a `RawIdent` can never be a keyword, meaning `get_real_ident_class` is unneeded, allowing this check to be simpler.

File: src/librustdoc/html/highlight.rs (hunk 1 above)
Comment (GuillaumeGomez) [reply src/librustdoc/html/highlight.rs]: Sure, changing it. :)

File: tests/rustdoc/source-code-pages/keyword-macros.rs (hunk 3 above)
Comment (GuillaumeGomez) [reply tests/rustdoc/source-code-pages/keyword-macros.rs:20]: The same issue cannot happen with something other than idents but added it just in case.

**Comment by GuillaumeGomez** [comment]
Ok ok, removing this change.

File: src/librustdoc/html/highlight.rs [hunk 4]
```diff
@@ -789,6 +789,9 @@ impl<'a> Iterator for TokenIter<'a> {
     }
 }
 
+/// Used to know if a keyword followed by a `!` should never be treated as a macro.
+const KEYWORDS_FOLLOWABLE_BY_VALUE: &[&str] = &["if", "while", "match", "break", "return"];
```
Comment (fmease) [inline src/librustdoc/html/highlight.rs]: Could you include `impl` as well? To fix negative impls: https://doc.rust-lang.org/nightly/src/core/marker.rs.html#1028

Screenshot 2025-11-09 at 14-22-40 marker rs - source

Of course, then the naming `…_BY_VALUE` won't make sense anymore because the thing following the `impl !` is a trait/type.

File: src/librustdoc/html/highlight.rs [hunk 5]
```diff
@@ -1216,16 +1232,49 @@ impl<'src> Classifier<'src> {
...
+                    "false" | "true" => Class::Bool,
+                    "self" | "Self" => Class::Self_(span()),
+                    "Option" | "Result" => Class::PreludeTy(span()),
+                    "Some" | "None" | "Ok" | "Err" => Class::PreludeVal(span()),
+                    _ if self.is_weak_keyword(text) || is_keyword(Symbol::intern(text)) => {
+                        // So if it's not a keyword which can be followed by a value (like `if` or
+                        // `return`) and the next non-whitespace token is a `!`, then we consider
+                        // it's a macro.
+                        if !KEYWORDS_FOLLOWABLE_BY_VALUE.contains(&text)
+                            && matches!(self.peek_non_trivia(), Some((TokenKind::Bang, _)))
```
Comment (fmease) [inline src/librustdoc/html/highlight.rs:1259]: Actually, why don't we exclude *all* keywords except for `self`, `super`, `crate` (`.is_path_segment_keyword()`)[^1]? I.e., turning the list around since you can't invoke arbitrary keywords as macros (unless `r#`'ed ofc which we already handle).

For example, the list keeps growing, there's not only `impl !Trait for ()` from above (so `impl`) but also `#[cfg(false)] impl const !Trait for () {}` (so `const`).

[^1]: Since `#[cfg(false)] self!(…)` and so on is valid even though you can't define a macro called `self` / `r#self`.

File: src/librustdoc/html/highlight.rs [hunk 6]
```diff
@@ -1216,16 +1232,49 @@ impl<'src> Classifier<'src> {
...
             },
             TokenKind::GuardedStrPrefix => return no_highlight(sink),
-            TokenKind::Ident | TokenKind::RawIdent
-                if let Some((TokenKind::Bang, _)) = self.peek_non_trivia() =>
-            {
+            TokenKind::RawIdent if let Some((TokenKind::Bang, _)) = self.peek_non_trivia() => {
                 self.in_macro = true;
                 let span = new_span(before, text, file_span);
                 sink(DUMMY_SP, Highlight::EnterSpan { class: Class::Macro(span) });
                 sink(span, Highlight::Token { text, class: None });
```
Comment (fmease) [inline src/librustdoc/html/highlight.rs]:
```suggestion
                self.new_macro_span(text, sink, before, file_span);
```

File: src/librustdoc/html/highlight.rs (hunk 4 above)
Comment (GuillaumeGomez) [reply src/librustdoc/html/highlight.rs]: Gonna rename the const. Synthax ambiguities are a nightmare on their own. :')

File: src/librustdoc/html/highlight.rs (hunk 5 above)
Comment (GuillaumeGomez) [reply src/librustdoc/html/highlight.rs:1259]: It doesn't work because `try` is not a path segment keyword, and yet you can name your macro `try`. So we're blocked on the constant. :')

Comment (fmease) [reply src/librustdoc/html/highlight.rs:1259]: Ah yeah, true, well until we start factoring in the requested/ambient edition (see https://github.com/rust-lang/rust/issues/148221), then that will no longer pose a problem.

Still, we could invert this check by rejecting all keywords except `self`, `super`, `crate` (`.is_path_segment_keyword()`) as mentioned and edition-sensitive keywords like `async`, `try`, `gen` (HACK: `.is_reserved(Rust2015)` (since we've never unreserved a keyword so far)).

However, I guess it's fine to keep your current approach given a fix of #148221 would be the ultimate & proper fix.

Comment (GuillaumeGomez) [reply src/librustdoc/html/highlight.rs:1259]: Well, I had in the back of my mind to use the actual rustc parser for this to get an AST for quite some time (and completely forgot until @yotamofek just asked me today why we didn't do it 🤣 ).

Comment (fmease) [reply src/librustdoc/html/highlight.rs:1259]: cc @yotamofek

Well, it's an AST, not a CST (concrete syntax tree), so you can't really faithfully / losslessly reconstruct the source code unless you meticulously call `span_to_snippet` basically *everywhere* and I'm talking *everywhere* and even then it's basically impossible.

Of course, we don't necessarily need to reconstruct the source à la `rustfmt` and could just use it to splice the source string in a few selected places but that wouldn't allow us to highlight comments as they aren't represented in the AST obviously and some keywords most likely (again, we can do some `span_to_snippet` trickery but we will get this wrong similar to `rustfmt` which just swallows comments here & there (we would only fail to highlight things but still)).

I mean it's worth a try, maybe I'm missing some third approach that's miles better.

Okay, so we could follow a hybrid solution by lexing the source, going through the token stream like we do now to highlight comments only, then parse the token stream & use it to splice+highlight the source. Might be perf heavy. Still won't catch everything but alright, trade-offs are everywhere and it might be better than the current approach.

Comment (GuillaumeGomez) [reply src/librustdoc/html/highlight.rs:1259]: I was planning to use `span_to_snippet` once per file and then map the spans to this string. Although I remember the issue about comments and was looking into forcing to keep it (and don't remember where I ended up).

Anyway, I think it would allow to simplify things quite a lot, but I also think it would have a performance impact, whichever solution we use. To be tested. :)

Comment (yotamofek) [reply src/librustdoc/html/highlight.rs:1259]: I might be saying silly things due to lack of knowledge,
but can't we *just* use the [lexer](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_parse/lexer/struct.Lexer.html), without invoking the parser, to generate a stream of [`Token`](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_ast/token/struct.Token.html)s? Then we "just" have to map a [`TokenKind`](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_ast/token/enum.TokenKind.html) to a CSS class?

I do wonder why rustfmt doesn't do that, though. Is it because they need AST-level information? But isn't rustfmt context-unaware?

I'll try to read up on it, maybe we can talk about it at tomorrow's meeting. Seems like it would simplify rustdoc quite a bit and be a much more robust solution, assuming it's actually feasible. But again - no idea what I'm talking about here 😁

Comment (yotamofek) [reply src/librustdoc/html/highlight.rs:1259]: Yeah, was gonna say the lexer is probably much slower since it also allows for recovery, suggestions, and can't assume the code is actually syntactically valid (which we can, I think?)

Comment (fmease) [reply src/librustdoc/html/highlight.rs:1259]: Just for the sake of completely, I'll mention it: While I'm pretty sure all the ASTs created at the start of the rustdoc process were dropped already, the HIR should still be around. We could in theory visit it and splice the source according to all the spans we find in the HIR.

Now, the biggest drawback of that will probably be syntactic sugar like `for` loops and `async` bodies (the latter have been turned into state machines at this point) which we might not be able to highlight easily or at all but I could be wrong.

Comment (fmease) [reply src/librustdoc/html/highlight.rs:1259]: > I might be saying silly things due to lack of knowledge,
but can't we *just* use the [lexer](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_parse/lexer/struct.Lexer.html), without invoking the parser, to generate a stream of [`Token`](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_ast/token/struct.Token.html)s? Then we "just" have to map a [`TokenKind`](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_ast/token/enum.TokenKind.html) to a CSS class?

That's essentially what we're doing right now. We're currently only lexing the source using `rustc_lexer` and iterate through its `Token`s (cc https://doc.rust-lang.org/nightly/nightly-rustc/rustc_lexer/enum.TokenKind.html).

`rustc_parse`'s lexer which you've mentioned only transforms the token stream provided by `rustc_lexer` into a different representation that's "slightly easier" to parse. For all intents and purposes, however they're the same thing in a different color, rustdoc's approach wouldn't change on a macro scale by changing over to it.

Comment (yotamofek) [reply src/librustdoc/html/highlight.rs:1259]: Oh right, got it. Thanks for the explanation!
