### PR TITLE
Strip frontmatter in fewer places

### LINKED ISSUE #145945: Theoretical breaking change from a combination of frontmatter and include!
With rustc 1.87, compiling the following pair of files succeeds:

`main.rs`:
```rust
fn main() {
    let _ = include!("expression.inc");
}
```

`expression.inc`:
```rust
---1
```

With rustc 1.88 or 1.89 (or `rustc 1.91.0-nightly (160e7623e 2025-08-26)`), compilation fails.

With 1.89 the first error message is
```
error: invalid infostring for frontmatter
 --> src/expression.inc:1:4
  |
1 | ---1
  |    ^
  |
  = note: frontmatter infostrings must be a single identifier immediately following the opening
```

See #145520 for a similar issue with `TokenStream::from_str`.

### LINKED ISSUE #146132: Introduction of frontmatter was a theoretical breaking change (via `Literal::from_str`)
See also https://github.com/rust-lang/rust/issues/145520 and https://github.com/rust-lang/rust/issues/145945.
This is basically (the fixed) https://github.com/rust-lang/rust/issues/145520 but with `TokenStream` replaced with `Literal` inside `.parse()`.

### Reproducer

* `rustc a.rs --crate-type proc-macro --extern proc_macro` where `a.rs`:
  ```rs
  #[proc_macro]
  pub fn ck(x: proc_macro::TokenStream) -> proc_macro::TokenStream {
      _ = "---".parse::<proc_macro::Literal>();
      x
  }
  ```
* `rustc b.rs --crate-type lib --extern a -L.` where `b.rs`:
  ```rs
  a::ck!();
  ```

In 1.87 and earlier, this used to compile just fine. However, since 1.88 (more precisely since PR #140035) this fails with:

```
error: invalid infostring for frontmatter
 --> <proc-macro source code>:1:4
  |
1 | ---
  |    ^
  |
  = note: frontmatter infostrings must be a single identifier immediately following the opening

error: unclosed frontmatter
 --> <proc-macro source code>:1:1
  |
1 | ---
  | ^^^
  |
note: frontmatter opening here was not closed
 --> <proc-macro source code>:1:1
  |
1 | ---
  | ^^^

error[E0658]: frontmatters are experimental
 --> <proc-macro source code>:1:1
  |
1 | ---
  | ^^^
  |
  = note: see issue #136889 <https://github.com/rust-lang/rust/issues/136889> for more information
  = help: add `#![feature(frontmatter)]` to the crate attributes to enable
  = note: this compiler was built on 2025-09-02; consider upgrading it if it is out of date

error: aborting due to 3 previous errors

For more information about this error, try `rustc --explain E0658`.
```

### PR DESCRIPTION
**Pull request by fmease**
* Stop stripping frontmatter in `proc_macro::Literal::from_str` (RUST-146132)
* Stop stripping frontmatter in expr-ctxt (but not item-ctxt!) `include`s (RUST-145945)
* Stop stripping shebang (!) in `proc_macro::Literal::from_str`
  * Not a breaking change because it did compare spans already to ensure there wasn't extra whitespace or comments (`Literal::from_str("#!\n0")` already yields `Err(_)` thankfully!)
* Stop stripping frontmatter+shebang inside some rustdoc code where it doesn't make any observable difference (see self review comments)
* (Stop stripping frontmatter+shebang inside internal test code) 

Fixes https://github.com/rust-lang/rust/issues/145945.
Fixes https://github.com/rust-lang/rust/issues/146132.

r? fee1-dead

### CODE REVIEW

File: compiler/rustc_expand/src/proc_macro_server.rs [hunk 1]
```diff
@@ -485,8 +485,13 @@ impl server::FreeFunctions for Rustc<'_, '_> {
...
     fn literal_from_str(&mut self, s: &str) -> Result<Literal<Self::Span, Self::Symbol>, ()> {
         let name = FileName::proc_macro_source_code(s);
-        let mut parser =
-            unwrap_or_emit_fatal(new_parser_from_source_str(self.psess(), name, s.to_owned()));
+
+        let mut parser = unwrap_or_emit_fatal(new_parser_from_source_str(
+            self.psess(),
+            name,
+            s.to_owned(),
+            StripTokens::Nothing,
```
Comment (fmease) [inline compiler/rustc_expand/src/proc_macro_server.rs:493]: Updating this to not strip shebangs isn't breaking.

It already compares spans below to ensure no extra trivia is contained like whitespace, comments or – well – shebangs. However, it's just cleaner to pass `Nothing` here.

File: compiler/rustc_parse/src/lib.rs [hunk 2]
```diff
@@ -54,29 +54,18 @@ pub fn unwrap_or_emit_fatal<T>(expr: Result<T, Vec<Diag<'_>>>) -> T {
...
-    let source_file = psess.source_map().new_source_file(name, source);
-    new_parser_from_source_file(psess, source_file, StripTokens::ShebangAndFrontmatter)
-}
-
-/// Creates a new parser from a simple (no shebang, no frontmatter) source string.
+/// Creates a new parser from a source string.
 ///
 /// On failure, the errors must be consumed via `unwrap_or_emit_fatal`, `emit`, `cancel`,
 /// etc., otherwise a panic will occur when they are dropped.
-pub fn new_parser_from_simple_source_str(
```
Comment (fmease) [inline compiler/rustc_parse/src/lib.rs:73]: Removing this convenience wrapper (for `StripTokens::Nothing`) to force all callers to have to think what behavior they want which is a lot more robust. Otherwise, people will just overlook this function and blindly go for the "normal" variant `new_parser_from_source_str`.

File: compiler/rustc_parse/src/lib.rs [hunk 3]
```diff
@@ -172,20 +162,26 @@ fn new_parser_from_source_file(
...
 }
 
+/// Given a source string, produces a sequence of token trees.
+///
+/// NOTE: This only strips shebangs, not frontmatter!
 pub fn source_str_to_stream(
     psess: &ParseSess,
     name: FileName,
     source: String,
     override_span: Option<Span>,
```
Comment (fmease) [inline compiler/rustc_parse/src/lib.rs:172]: I might add `strip_tokens: StripTokens` as a parameter to this function in a future PR. At the time of writing, it wouldn't really matter but there are some call sites like the one for `-Zcrate-attr` where we could pass `StripTokens::Nothing` (since the input is wrapped in `#![` `]` anyway) but it wouldn't lead to any observable difference in rustc's behavior.

File: src/librustdoc/clean/render_macro_matchers.rs [hunk 4]
```diff
@@ -64,14 +65,18 @@ fn snippet_equal_to_token(tcx: TyCtxt<'_>, matcher: &TokenTree) -> Option<String
...
-            Err(errs) => {
-                errs.into_iter().for_each(|err| err.cancel());
-                return None;
-            }
-        };
+    let mut parser = match rustc_parse::new_parser_from_source_str(
+        &psess,
+        file_name,
+        snippet.clone(),
+        StripTokens::Nothing,
```
Comment (fmease) [inline src/librustdoc/clean/render_macro_matchers.rs:72]: Shouldn't make a difference since this is for (re)parsing macro matchers which will have already been validated by rustc and shebangs or frontmatters aren't part of that subgrammar.

File: compiler/rustc_parse/src/parser/tests.rs
Comment (fmease) [inline compiler/rustc_parse/src/parser/tests.rs:1]: This is just test code; use `StripTokens::Nothing` for simplicity. If anybody wants to test shebangs and/or frontmatter in here, they can just update it.

File: src/librustdoc/doctest/make.rs [hunk 5]
```diff
@@ -468,14 +469,16 @@ fn parse_source(
...
-        Ok(p) => p,
-        Err(errs) => {
-            errs.into_iter().for_each(|err| err.cancel());
-            reset_error_count(&psess);
-            return Err(());
-        }
-    };
+    // Don't strip any tokens; it wouldn't matter anyway because the source is wrapped in a function.
+    let mut parser =
+        match new_parser_from_source_str(&psess, filename, wrapped_source, StripTokens::Nothing) {
```
Comment (fmease) [inline src/librustdoc/doctest/make.rs:474]: Change is unobservable as the added comment explains.

File: tests/ui-fulldeps/auxiliary/parser.rs [hunk 6]
```diff
@@ -22,6 +22,7 @@ pub fn parse_expr(psess: &ParseSess, source_code: &str) -> Option<Box<Expr>> {
     let parser = rustc_parse::unwrap_or_emit_fatal(rustc_parse::new_parser_from_source_str(
         psess,
         FileName::anon_source_code(source_code),
+        rustc_parse::lexer::StripTokens::Nothing,
```
Comment (fmease) [inline tests/ui-fulldeps/auxiliary/parser.rs]: This is also just test code.

File: src/tools/clippy/clippy_lints/src/doc/needless_doctest_main.rs [hunk 7]
```diff
@@ -49,7 +50,7 @@ pub fn check(
                 let sm = Arc::new(SourceMap::new(FilePathMapping::empty()));
                 let psess = ParseSess::with_dcx(dcx, sm);
 
-                let mut parser = match new_parser_from_source_str(&psess, filename, code) {
+                let mut parser = match new_parser_from_source_str(&psess, filename, code,StripTokens::ShebangAndFrontmatter) {
```
Comment (Urgau) [inline src/tools/clippy/clippy_lints/src/doc/needless_doctest_main.rs]: (missing space and maybe format as well)
```suggestion
                let mut parser = match new_parser_from_source_str(&psess, filename, code, StripTokens::ShebangAndFrontmatter) {
```

**Review by Urgau — APPROVED** [review]
Looks good to me.

*[View changes since this review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/rust/146340/be8de5d6a0fc5cb2924e174a809a0aff303f281a..541e36fa82c9550b615ce8f645b9b534744ece0c)*

**Review by fee1-dead — APPROVED** [review]
Awesome, r=me when green

*[View changes since this review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/rust/146340/be8de5d6a0fc5cb2924e174a809a0aff303f281a..7a66925a8138df105f77d646f9206024baf7ea4b)*
