### PR TITLE
Typecheck patterns of all match arms first, so we get types for bindings

### LINKED ISSUE #55810: romaji fails to build on beta,
[romaji](https://crater-reports.s3.amazonaws.com/beta-1.31-1/beta-2018-10-30/reg/romaji-0.1.1/log.txt), cc @uzimith

With a few minutes of time invested I wasn't able to narrow this down to a smaller example that still succeeded on stable. 

```
! 
Nov 02 07:32:11.418 INFO kablam! error[E0282]: type annotations needed
Nov 02 07:32:11.418 INFO kablam!   --> src/romaji.rs:80:24
Nov 02 07:32:11.418 INFO kablam!    |
Nov 02 07:32:11.418 INFO kablam! 80 |                 x if x.is_youon() && buffer.is_katakana() => {
Nov 02 07:32:11.419 INFO kablam!    |                        ^^^^^^^^ cannot infer type for `T`
Nov 02 07:32:11.419 INFO kablam!    |
Nov 02 07:32:11.419 INFO kablam!    = note: type must be known at this point
```

cc @rust-lang/libs

### PR DESCRIPTION
**Pull request by pnkfelix**
Fix eventually (after backport to beta) the issue #55810

### CODE REVIEW

**Comment by estebank** [comment]
Accepting for backport.

File: src/librustc_typeck/check/_match.rs [hunk 1]
```diff
@@ -626,9 +626,9 @@ https://doc.rust-lang.org/reference/types.html#trait-objects");
         let discrim_diverges = self.diverges.get();
         self.diverges.set(Diverges::Maybe);
 
-        // Typecheck the patterns first, so that we get types for all the
-        // bindings.
-        let all_arm_pats_diverge = arms.iter().map(|arm| {
+        // rust-lang/rust#55810: Typecheck patterns first (via eager
+        // collection into `Vec`), so we get types for all bindings.
```
Comment (eddyb) [inline src/librustc_typeck/check/_match.rs]: Ahh, had I seen this PR, I would've suggested adding a note that the `map` below has side-effects in terms of type inference (unifying the types of all the arms together), and that's why it has to fully complete first.
