### PR TITLE
diagnostics: wrap fn cast suggestions in parens when needed

### LINKED ISSUE #121632: Named functions do not implement traits implemented on fn()
I tried this code:

```rust
trait Foo {}

impl Foo for fn() {}

fn main() {
    let x: &dyn Foo = &main;
}
```

[playground link](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=b7599602952b263f8d3e1009dfeb681e)

I expected this code to compile, as `main` is a fn() pointer, which implements the trait `Foo`

However, rustc seems to need additiontal casting to convert a named fn() to a unnamed one:
```
   Compiling playground v0.0.1 (/playground)
error[E0277]: the trait bound `fn() {main}: Foo` is not satisfied
 --> src/lib.rs:6:23
  |
6 |     let x: &dyn Foo = &main;
  |                       ^^^^^ the trait `Foo` is not implemented for fn item `fn() {main}`
  |
  = note: required for the cast from `&fn() {main}` to `&dyn Foo`
help: the trait `Foo` is implemented for fn pointer `fn()`, try casting using `as`
  |
6 |     let x: &dyn Foo = &main as fn();
  |                             +++++++

For more information about this error, try `rustc --explain E0277`.
error: could not compile `playground` (lib) due to 1 previous error
```

On a side note, the solution suggested by rustc is missing parentheses. The correct way would be `&(main as fn())`. When following the suggestions given by rustc, the code goes `&main` -> `&main as fn()` -> `&(&main as fn())`. The last code suggestion is an invalid cast, because you cannot cast `&fn()` to `fn()`.

### Meta

`rustc --version --verbose`:
```
rustc 1.76.0 (07dca489a 2024-02-04)
binary: rustc
commit-hash: 07dca489ac2d933c78d3c5158e3f43beefeb02ce
commit-date: 2024-02-04
host: x86_64-unknown-linux-gnu
release: 1.76.0
LLVM version: 17.0.6
```
(also happens on beta and nightly)

### PR DESCRIPTION
**Pull request by notriddle**
Fixes #121632

### CODE REVIEW

**Review by compiler-errors — APPROVED** [review]

**Comment by compiler-errors** [comment]
I'm not too happy with how span-based this approach is. I think this is generally a shortcoming of trait selection errors, given the way that we fail to track much of the necessary "source" information. But I guess it's not significantly worse than existing diagnostics code.

@bors r+ rollup

File: compiler/rustc_trait_selection/src/error_reporting/traits/fulfillment_errors.rs [hunk 1]
```diff
@@ -378,14 +379,34 @@ impl<'a, 'tcx> TypeErrCtxt<'a, 'tcx> {
                             if let (ty::FnPtr(..), ty::FnDef(..)) =
                                 (cand.self_ty().kind(), main_trait_ref.self_ty().skip_binder().kind())
                             {
-                                err.span_suggestion(
-                                    span.shrink_to_hi(),
+                                // Wrap method receivers and `&`-references in parens
+                                let suggestion = if self.tcx.sess.source_map().span_look_ahead(span, ".", Some(50)).is_some() {
+                                    vec![
```
Comment (chenyukang) [inline compiler/rustc_trait_selection/src/error_reporting/traits/fulfillment_errors.rs:384]: `span_look_ahead` is not correct sometimes, can we use the `expr` way to find out there is a method call?
