### PR TITLE
Avoid follow-up errors if the number of generic parameters already doesn't match

### LINKED ISSUE #125604: When passing too many lifetimes to a struct, there are tons of unrelated errors about needing explicit lifetime annotations
To reproduce, check out commit cdc509f7c09361466d543fc8311ce7066b10cc4f of rustc and then edit this line:

https://github.com/rust-lang/rust/blob/d50c2b0a52f31fbbf6e6bfa27c129b513fdddb0b/src/tools/miri/src/borrow_tracker/stacked_borrows/mod.rs#L278

Specifically, add another `'_, ` before the `'tcx`. Then run `./x.py check miri`. This results in some surprising errors:
```
error[E0107]: struct takes 4 lifetime arguments but 5 lifetime arguments were supplied
   --> src/tools/miri/src/borrow_tracker/stacked_borrows/mod.rs:278:19
    |
278 |         dcx: &mut DiagnosticCx<'_, '_, '_, '_,'tcx>,
    |                   ^^^^^^^^^^^^                ---- help: remove this lifetime argument
    |                   |
    |                   expected 4 lifetime arguments
    |
note: struct defined here, with 4 lifetime parameters: `'history`, `'ecx`, `'mir`, `'tcx`
   --> src/tools/miri/src/borrow_tracker/stacked_borrows/diagnostics.rs:123:12
    |
123 | pub struct DiagnosticCx<'history, 'ecx, 'mir, 'tcx> {
    |            ^^^^^^^^^^^^ --------  ----  ----  ----

error[E0621]: explicit lifetime required in the type of `dcx`
   --> src/tools/miri/src/borrow_tracker/stacked_borrows/mod.rs:285:13
    |
278 |         dcx: &mut DiagnosticCx<'_, '_, '_, '_,'tcx>,
    |              -------------------------------------- help: add explicit lifetime `'tcx` to the type of `dcx`: `&mut DiagnosticCx<'_, '_, '_, 'tcx>`
...
285 |             self.find_granting(access, tag, exposed_tags).map_err(|()| dcx.access_error(self))?;
    |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ lifetime `'tcx` required

error[E0621]: explicit lifetime required in the type of `dcx`
   --> src/tools/miri/src/borrow_tracker/stacked_borrows/mod.rs:305:17
    |
278 |         dcx: &mut DiagnosticCx<'_, '_, '_, '_,'tcx>,
    |              -------------------------------------- help: add explicit lifetime `'tcx` to the type of `dcx`: `&mut DiagnosticCx<'_, 'tcx, '_, '_>`
...
305 |                 dcx.log_invalidation(item.tag());
    |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ lifetime `'tcx` required
```

The first error is what I expected, but the other two are not useful: they are referring to an argument type that's not even a valid type, so they should not be shown. When doing refactoring, it can be quite hard to spot the actual errors in this sea of false errors.

So far I have not managed to reproduce this with a smaller example.

Cc @oli-obk is this a consequence of your recent work to keep compiling in more cases?

### PR DESCRIPTION
**Pull request by oli-obk**
fixes #125604

best reviewed commit-by-commit

### CODE REVIEW

File: compiler/rustc_hir_analysis/src/hir_ty_lowering/object_safety.rs [hunk 1]
```diff
@@ -214,7 +216,9 @@ impl<'tcx> dyn HirTyLowerer<'tcx> + '_ {
         // Erase the `dummy_self` (`trait_object_dummy_self`) used above.
         let existential_trait_refs = regular_traits.iter().map(|i| {
             i.trait_ref().map_bound(|trait_ref: ty::TraitRef<'tcx>| {
-                assert_eq!(trait_ref.self_ty(), dummy_self);
+                if !trait_ref.self_ty().references_error() {
+                    assert_eq!(trait_ref.self_ty(), dummy_self);
+                }
```
Comment (BoxyUwU) [inline compiler/rustc_hir_analysis/src/hir_ty_lowering/object_safety.rs:221]: I am a bit nervous about this change. It seems like the rest of the compiler ought to be able to assume that trait objects are represented "correctly".

**Review by BoxyUwU — COMMENTED** [review]
cool

File: compiler/rustc_hir_analysis/src/hir_ty_lowering/object_safety.rs (hunk 1 above)
Comment (oli-obk) [reply compiler/rustc_hir_analysis/src/hir_ty_lowering/object_safety.rs]: I reverted the change and instead only marked those generic params as errors that were actually erroneous

File: compiler/rustc_hir_analysis/src/hir_ty_lowering/mod.rs [hunk 2]
```diff
@@ -569,15 +554,19 @@ impl<'tcx> dyn HirTyLowerer<'tcx> + '_ {
...
-                            }) {
+                            if let Some(prev) =
+                                preceding_args.iter().find_map(|arg| match arg.unpack() {
+                                    GenericArgKind::Type(ty) => ty.error_reported().err(),
+                                    _ => None,
+                                })
+                            {
                                 // Avoid ICE #86756 when type error recovery goes awry.
-                                return Ty::new_misc_error(tcx).into();
+                                return Ty::new_error(tcx, prev).into();
```
Comment (oli-obk) [inline compiler/rustc_hir_analysis/src/hir_ty_lowering/mod.rs:551]: Fishy ICE workaround, but I rather preserved it for now instead of looking into it

File: compiler/rustc_hir_typeck/src/fn_ctxt/_impl.rs [hunk 3]
```diff
@@ -1275,6 +1275,7 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
 
             fn provided_kind(
                 &mut self,
+                _preceding_args: &[ty::GenericArg<'tcx>],
```
Comment (oli-obk) [inline compiler/rustc_hir_typeck/src/fn_ctxt/_impl.rs:1278]: Could actually allow generic const generics now here, but there's probably other work required elsewhere to support it properly

Comment (BoxyUwU) [reply compiler/rustc_hir_typeck/src/fn_ctxt/_impl.rs:1278]: Yeah basically nothing is set up for that at all lol

File: compiler/rustc_hir_analysis/src/hir_ty_lowering/generics.rs [hunk 4]
```diff
@@ -474,16 +475,9 @@ pub(crate) fn check_generic_arg_count(
             return Ok(());
         }
 
-        if provided_args > max_expected_args {
-            invalid_args.extend(
-                gen_args.args[max_expected_args..provided_args].iter().map(|arg| arg.span()),
-            );
-        };
+        invalid_args.extend(min_expected_args..provided_args);
```
Comment (BoxyUwU) [inline compiler/rustc_hir_analysis/src/hir_ty_lowering/generics.rs:478]: Will this not give a backwards range (i.e. `2..1`) if you have a `fn foo<'a: 'a, 'b: 'b>` and you call it `foo::<'static>`?

Comment (oli-obk) [reply compiler/rustc_hir_analysis/src/hir_ty_lowering/generics.rs:478]: Yes, but that's the prev behaviour. I just merged the two loops

File: tests/crashes/121134.rs [hunk 5]
```diff
@@ -1,20 +0,0 @@
...
-        FnOnce:,
-        F: for<'a> FnOnce(<F as Output<i32, _>>::Type),
-    {
-    }
-}
-
-fn main() {
-    let mut wrapper = Wrapper;
-    wrapper.do_something_wrapper::<i32, _>(|value| ());
-}
```
Comment (matthiaskrgr) [inline tests/crashes/121134.rs:20]: this issue is not closed
