### PR TITLE
Issue 50970 migration lint fq path

### LINKED ISSUE #50970: migration lint for `use crate` fails with `<Foo as Bar>::Baz` paths
Test case:

```rust
#![warn(rust_2018_compatibility)]
#![feature(rust_2018_preview)]

mod foo {
    crate trait Foo {
        type Bar;
    }

    impl Foo for u32 {
        type Bar = ();
    }
}


fn main() {
    let _: <u32 as ::foo::Foo>::Bar = ();
}
```

This currently suggests:

```
help: use `crate`: `crate::<u32 as ::foo::Foo>::Bar`
```

but should suggest:

```
help: use `crate`: `<u32 as crate::foo::Foo>::Bar`
```

### PR DESCRIPTION
**Pull request by nikomatsakis**
Similar issue, but for fully qualified paths.

Fixes #50970 

r? @alexcrichton

### CODE REVIEW

File: src/librustc_resolve/lib.rs [hunk 1]
```diff
@@ -2273,7 +2273,13 @@ impl<'a> Resolver<'a> {
 
                 if items.len() == 0 {
                     // Resolve prefix of an import with empty braces (issue #28388).
-                    self.smart_resolve_path(id, None, &path, PathSource::ImportPrefix);
+                    self.smart_resolve_path_with_crate_lint(
+                        id,
+                        None,
+                        &path,
+                        PathSource::ImportPrefix,
+                        CrateLint::SimplePath(id), // TODO seems wrong
```
Comment (nikomatsakis) [inline src/librustc_resolve/lib.rs]: whoops forgot about TODO. I'll fix tomorrow. I couldn't actually reproduce a bug here, so maybe it's fine as is, but it *seems* like this is wrong in some case or other and we should be tracking the root-id and root-path

Comment (alexcrichton) [reply src/librustc_resolve/lib.rs]: Hm so this may fall in this category?

```rust
#![crate_type = "rlib"]
#![feature(rust_2018_preview)]
#![warn(rust_2018_compatibility)]
#![allow(unused_imports, dead_code)]

mod foo {}
mod bar {}


fn main() {
    use {foo::{}, bar::{}};
}
```

Even with https://github.com/rust-lang/rust/pull/50982 I think I'm still getting two warnings here

Comment (nikomatsakis) [reply src/librustc_resolve/lib.rs]: I fixed it in any case.

Comment (nikomatsakis) [reply src/librustc_resolve/lib.rs]: I found some other ways for it to go wrong, with a bit more effort =)

**Comment by alexcrichton** [comment]
@bors: r+ p=1

(higher priority for the edition preview)

**Comment by alexcrichton** [comment]
@bors: retry

er... hanging in musl?
