### PR TITLE
fix rustdoc `render_call_locations`  panicking because of default span `DUMMY_SP` pointing at non local-source file

### LINKED ISSUE #144752: ICE: `only local crates should have sources emitted`
[rustc-ice-2025-07-31T21_03_32-3325.txt](https://github.com/user-attachments/files/21537667/rustc-ice-2025-07-31T21_03_32-3325.txt)

### Code

https://github.com/oold/daemonize/tree/ec717e7b6254d4acabecf8bb37e924b068e18d88

### Meta

`rustc --version --verbose`:
```
rustc 1.90.0-nightly (3048886e5 2025-07-30)
binary: rustc
commit-hash: 3048886e59c94470e726ecaaf2add7242510ac11
commit-date: 2025-07-30
host: x86_64-unknown-linux-gnu
release: 1.90.0-nightly
LLVM version: 20.1.8
```

### Error output

```
thread 'rustc' panicked at src/librustdoc/html/sources.rs:346:14:
only local crates should have sources emitted
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
stack backtrace:
   0: __rustc::rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::option::expect_failed
   3: <&core::fmt::builders::FromFn<rustdoc::html::sources::print_src<&mut core::fmt::Formatter>::{closure#0}> as core::fmt::Display>::fmt
   4: core::fmt::write
   5: <&askama::filters::escape::Safe<&core::fmt::builders::FromFn<rustdoc::html::sources::print_src<&mut core::fmt::Formatter>::{closure#0}>> as core::fmt::Display>::fmt
   6: core::fmt::write
   7: rustdoc::html::render::render_call_locations::<&mut core::fmt::Formatter>::{closure#2}
   8: <core::fmt::builders::FromFn<rustdoc::html::render::document_full_inner::{closure#0}> as core::fmt::Display>::fmt
   9: core::fmt::write
  10: rustdoc::html::render::render_impl::{closure#0}::doc_impl_item::<&mut alloc::string::String, &mut alloc::string::String>
  11: <core::fmt::builders::FromFn<rustdoc::html::render::render_impl::{closure#0}> as core::fmt::Display>::fmt
  12: core::fmt::write
  13: rustdoc::html::render::render_assoc_items_inner
  14: <core::fmt::builders::FromFn<rustdoc::html::render::render_assoc_items::{closure#0}> as core::fmt::Display>::fmt
  15: core::fmt::write
  16: <rustdoc::html::render::print_item::DisplayStruct>::render_into::<core::fmt::Formatter>
  17: <core::fmt::builders::FromFn<rustdoc::html::render::print_item::item_struct::{closure#0}> as core::fmt::Display>::fmt
  18: core::fmt::write
  19: <rustdoc::html::render::context::Context>::render_item
  20: <rustdoc::html::render::context::Context as rustdoc::formats::renderer::FormatRenderer>::item
  21: rustdoc::formats::renderer::run_format_inner::<rustdoc::html::render::context::Context>
  22: rustdoc::formats::renderer::run_format_inner::<rustdoc::html::render::context::Context>
  23: rustc_interface::passes::create_and_enter_global_ctxt::<(), rustdoc::main_args::{closure#2}::{closure#0}>::{closure#2}::{closure#0}
  24: rustc_interface::interface::run_compiler::<(), rustdoc::main_args::{closure#2}>::{closure#1}
```

</p>
</details>

### PR DESCRIPTION
**Pull request by janis-bhm**
fixes https://github.com/rust-lang/rust/issues/144752
related to/builds on https://github.com/rust-lang/rust/pull/145008

bevy still crashes in the same way as rust-lang/rust#144752 when building docs on nightly, and from what I can tell the cause seems to be the following (copied from zulip [#t-rustdoc > docs on nightly with example scrapes crash](https://rust-lang.zulipchat.com/#narrow/channel/266220-t-rustdoc/topic/docs.20on.20nightly.20with.20example.20scrapes.20crash)):

> render_call_locations tries to [find](https://github.com/rust-lang/rust/blob/84a17470220e7adf249b18d7c0178dfbede89462/src/librustdoc/html/render/mod.rs#L2816) the source span of a call to add as an example, but the example files are never actually in the source map from what I can tell, and so it falls back to the default span, which points at the first file in the source map.
> Now, the issue that guillaume mentions [here](https://github.com/rust-lang/rust/pull/145008) adds new files to the source map in order to get them into the dep info, and that leads to some files, namely docs-rs/trait-tags.html in the case of bevy because it's added with --html-after-content, being added before any source files, so then the default span points at them, and when href_from_span tries to find the [source file](https://github.com/rust-lang/rust/blob/84a17470220e7adf249b18d7c0178dfbede89462/src/librustdoc/html/render/context.rs#L368) corresponding to the span, the file doesn't belong to local_sources, and it short circuits.
> This can be fixed by just not using DUMMY_SP as the default span and calculating, for example, the crates root source file as the span, because I'm not entirely sure what the href from that span is actually used for; it's not what links to the example in the end.
> I think the proper way of fixing this would be to make sure the example files are part of the local_sources or at least the source map, but I don't know nearly enough about rust internals to be able to figure out how to fix that.

I've included a test that's mostly copied from rust-lang/rust#145008's test with the addition of `--html-after-content after.html` in the `RUSTDOCFLAGS`, which panics on master in conjunction with the `-Zrustdoc-scrape-examples` cargo flag.

cc @GuillaumeGomez

### CODE REVIEW

**Comment by jieyouxu** [comment]
r? rustdoc

File: src/librustdoc/html/render/mod.rs [hunk 1]
```diff
@@ -2829,7 +2829,21 @@ fn render_call_locations<W: fmt::Write>(
                 file.start_pos + BytePos(byte_max),
             ))
         })()
-        .unwrap_or(DUMMY_SP);
+        .unwrap_or_else(|| {
```
Comment (GuillaumeGomez) [inline src/librustdoc/html/render/mod.rs]: Instead of cloning parts of the above code, I think it'd might be simpler to instead tweak it a bit:

```rust
            let local = tcx.sess.local_crate_source_file()?;
            let crate_src = local.into_local_path()?;
            let abs_crate_src = crate_src.canonicalize().ok()?;
            let crate_root = abs_crate_src.parent()?.parent()?;
            let rel_path = path.strip_prefix(crate_root).ok()?;
            let files = source_map.files();
            let file = files.iter().find(|file| match &file.name {
                FileName::Real(RealFileName::LocalPath(other_path)) => rel_path == other_path,
                _ => false,
            }).or_else(|| files.iter().find(|file| matches!(&file.name, FileName::Real(file_name) if file_name == &local))?;
```

Comment (GuillaumeGomez) [reply src/librustdoc/html/render/mod.rs]: Then we can replace the `unwrap_or(DUMMY_SP)` with `expect("no local file found")`.

File: tests/rustdoc-gui/src/scrape_examples_ice/src/lib.rs [hunk 2]
```diff
@@ -0,0 +1,9 @@
+//@ run-flags:-Zrustdoc-scrape-examples
+//@ rustc-env: RUSTDOCFLAGS='--html-after-content after.html'
```
Comment (GuillaumeGomez) [inline tests/rustdoc-gui/src/scrape_examples_ice/src/lib.rs]: Please pass `--html-after-content after.html` directly in `run-flags`.

**Comment by GuillaumeGomez** [comment]
Also please [squash](https://blog.guillaume-gomez.fr/Git-tips/1/2) your commits once done.

File: tests/rustdoc-gui/search-result-display.goml [hunk 3]
```diff
@@ -52,7 +52,7 @@ compare-elements-size-near: (
 set-window-size: (900, 900)
 
 // First we check the current width, height and position.
-assert-css: ("#crate-search", {"width": "159px"})
+assert-css: ("#crate-search", {"width": "185px"})
```
Comment (GuillaumeGomez) [inline tests/rustdoc-gui/search-result-display.goml]: This change is because the longest crate name increased.

**Comment by GuillaumeGomez** [comment]
Note for myself, once merged, I'll need to add a test for the extra HTML added.

**Comment by GuillaumeGomez** [comment]
Thanks for the fix!

@bors r+ rollup

**Review by GuillaumeGomez — APPROVED** [review]
