### PR TITLE
Stabilize `const_ptr_offset_from`.

### LINKED ISSUE #92980: Tracking Issue for const offset_from (const_ptr_offset_from)
The feature gate for the issue is `#![feature(const_ptr_offset_from)]`.

This tracks `const`ness of the following function(s):
```rust
impl<T> *const T {
  const unsafe fn offset_from(self, origin: *const T) -> isize
}
```

### About tracking issues

Tracking issues are used to record the overall progress of implementation.
They are also used as hubs connecting to other relevant issues, e.g., bugs or open design questions.
A tracking issue is however *not* meant for large scale discussion, questions, or bug reports about a feature.
Instead, open a dedicated issue for the specific matter and add the relevant feature gate label.

### Steps

- [x] Implementation
- Stabilization report: https://github.com/rust-lang/rust/issues/92980#issuecomment-1065644848
- [ ] Stabilization PR ([see instructions on rustc-dev-guide][stabilization-guide])

[stabilization-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#stabilization-pr
[doc-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#documentation-prs

### Unresolved Questions

- Should we allow calling this function in case both pointers point to the same allocation (in terms of their provenance) but are not both in-bounds? Cc https://github.com/rust-lang/rust/issues/92512 <br>    → this can be resolved post-stabilization since it is backwards compatible

### Implementation history

- see https://github.com/rust-lang/rust/issues/41079
- https://github.com/rust-lang/rust/pull/94827

### PR DESCRIPTION
**Pull request by fee1-dead**
Stabilization has been completed [here](https://github.com/rust-lang/rust/issues/92980#issuecomment-1065644848) with a FCP.

Closes #92980.

### CODE REVIEW

**Comment by fee1-dead** [comment]
r? rust-lang/libs-api

@rustbot label +T-libs-api +T-lang -T-libs

**Comment by coolreader18** [comment]
Is there an update for this?

**Review by jhpratt — COMMENTED** [review]
Other than bumping the version to 1.63, LGTM.

**Comment by fee1-dead** [comment]
bumped.

**Comment by fee1-dead** [comment]
r? rust-lang/libs-api

**Comment by fee1-dead** [comment]
I will resolve the conflicts (and bump the version) pending review.

**Comment by fee1-dead** [comment]
r? rust-lang/libs

File: library/core/src/intrinsics.rs [hunk 1]
```diff
@@ -1903,11 +1903,11 @@ extern "rust-intrinsic" {
     pub fn nontemporal_store<T>(ptr: *mut T, val: T);
 
     /// See documentation of `<*const T>::offset_from` for details.
-    #[rustc_const_unstable(feature = "const_ptr_offset_from", issue = "92980")]
+    #[rustc_const_stable(feature = "const_ptr_offset_from", since = "1.63.0")]
```
Comment (klensy) [inline library/core/src/intrinsics.rs:1906]: 1.64.0 here and lower?

Comment (fee1-dead) [reply library/core/src/intrinsics.rs]: done

**Comment by coolreader18** [comment]
Sorry to bump this again, but I think this stabilization is super exciting and important, since it finally allows for const `offsetof(Foo.bar)` calculations. I think by this point it should be stable `since = "1.65.0"` since 1.63 has been released, but could someone from the libs-api team (@jhpratt?) take a look at it after? The FCP was completed 5+ months ago at this point.

**Comment by jhpratt** [comment]
I'm not on T-libs-api, but I'll take another look at it in the near future.

**Review by jhpratt — APPROVED** [review]
As with before, diff LGTM. Just needs the version bumped to 1.65, naturally.
