### PR TITLE
simplify const params diagnostic on stable

### LINKED ISSUE #95150: Diagnostic for const generic enum on stable suggests requirements for nightly-only feature (PartialEq, Eq)
Given the following code ([playground link](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=6804b0c085c6fcf4fba0c2fa9d49385e)):

```rust
enum E {
    V1,
    V2,
}

struct S<const X: E>;
```

Rust gives a diagnostic suggesting deriving `PartialEq, Eq`:

```
error: `E` is forbidden as the type of a const generic parameter
 --> src/lib.rs:6:19
  |
6 | struct S<const X: E>;
  |                   ^
  |
  = note: the only supported types are integers, `bool` and `char`

error[E0741]: `E` must be annotated with `#[derive(PartialEq, Eq)]` to be used as the type of a const parameter
 --> src/lib.rs:6:19
  |
6 | struct S<const X: E>;
  |                   ^ `E` doesn't derive both `PartialEq` and `Eq`

For more information about this error, try `rustc --explain E0741`.
```

However, adding `#[derive(PartialEq, Eq)]` leads the compiler to still give an error about not supporting this.

A non-nightly compiler should not give the second error at all; it should only give the first, saying that the only supported types are integers, `bool` and `char`.

### PR DESCRIPTION
**Pull request by OliverMD**
Resolves #95150

### CODE REVIEW

**Comment by OliverMD** [comment]
@lcnr You added the E-Mentor tag on #95150, is this sort of what you had in mind? Would you like to review this?

File: compiler/rustc_typeck/src/check/wfcheck.rs [hunk 1]
```diff
@@ -863,7 +863,9 @@ fn check_param_wf(tcx: TyCtxt<'_>, param: &hir::GenericParam<'_>) {
                 }
             };
 
-            if traits::search_for_structural_match_violation(param.span, tcx, ty).is_some() {
+            if tcx.features().adt_const_params // structural matching only allowed with adt_const_params feature
```
Comment (lcnr) [inline compiler/rustc_typeck/src/check/wfcheck.rs:866]: we already have a check for the `adt_const_params` feature a few lines above. I would prefer to only have 1 branch for that. So pretty much

```rust
if tcx.features().adt_const_params {
   // complex check¹
} else {
   // simple check, completely ignoring structural equality
}
```
¹ It might be interesting to check whether function pointers are considered a structural match violation. If they are, you can completely avoid checking the `ty` in that branch.

**Review by lcnr — COMMENTED** [review]
Thanks :+1: 

While your approach works, I think that this code already was a bit more complex than necessary and should get cleaned up a bit while we're already here.

**Comment by lcnr** [comment]
thanks

@bors r+ rollup
