### PR TITLE
Tweak macro parse errors when reaching EOF during macro call parse

### LINKED ISSUE #27569: End of macro invocation before expected produces EOF
``` rust
fn main() {
    let message = "world";
    println!("Hello, {}", message/);
}
```

This gives the following compile error:

```


<anon>:3:34: 3:35 error: unexpected token: `<eof>`
<anon>:3     println!("Hello, {}", message/);
                                          ^
```

I think this is slightly misleading: it's not an EOF at the position where the caret is.

### PR DESCRIPTION
**Pull request by estebank**
Add detail on origin of current parser when reaching EOF, stop saying "found `<eof>`" and point at the end of macro calls.

Fix #27569.

### CODE REVIEW

File: src/libsyntax/config.rs [hunk 1]
```diff
@@ -94,6 +94,17 @@ impl<'a> StripUnconfigured<'a> {
         if !attr.check_name(sym::cfg_attr) {
             return vec![attr];
         }
+        if attr.tokens.len() == 0 {
+            self.sess.span_diagnostic.struct_span_err(attr.span, "bad `cfg_attr` attribute")
+                .span_label(attr.span, "missing condition and attribute")
+                .note("`cfg_attr` must be of the form: \
+                       `#[cfg_attr(condition, attribute)]`")
```
Comment (Centril) [inline src/libsyntax/config.rs]: N.B. `cfg_attr` accepts a list of attributes these days. See https://github.com/rust-lang/rust/issues/54881.

File: src/libsyntax/ext/tt/macro_parser.rs [hunk 2]
```diff
@@ -658,7 +658,14 @@ pub fn parse(
...
 ) -> NamedParseResult {
     // Create a parser that can be used for the "black box" parts.
-    let mut parser = Parser::new(sess, tts, directory, recurse_into_modules, true);
+    let mut parser = Parser::new(
+        sess,
+        tts,
+        directory,
+        recurse_into_modules,
+        true,
+        Some("macro arguments"),
```
Comment (Centril) [inline src/libsyntax/ext/tt/macro_parser.rs]: Duplicated in `ext/base.rs`.

File: src/libsyntax/parse/mod.rs [hunk 3]
```diff
@@ -245,7 +245,7 @@ fn maybe_source_file_to_parser(
 // must preserve old name for now, because quote! from the *existing*
 // compiler expands into it
 pub fn new_parser_from_tts(sess: &ParseSess, tts: Vec<TokenTree>) -> Parser<'_> {
-    stream_to_parser(sess, tts.into_iter().collect())
+    stream_to_parser(sess, tts.into_iter().collect(), Some("macro arguments"))
```
Comment (Centril) [inline src/libsyntax/parse/mod.rs]: And here... :)

Use a `const` somewhere to centralize?

File: src/libsyntax/parse/parser.rs [hunk 4]
```diff
@@ -233,6 +233,8 @@ pub struct Parser<'a> {
     /// error.
     crate unclosed_delims: Vec<UnmatchedBrace>,
     last_unexpected_token_span: Option<Span>,
+    /// If `true`, this `Parser` is not parsing Rust code but rather a macro call.
+    is_subparser: Option<&'static str>,
```
Comment (Centril) [inline src/libsyntax/parse/parser.rs]: Not a boolean -- presumably `Some(_)`?... Naming also seems off.

File: src/libsyntax/parse/parser.rs [hunk 5]
```diff
@@ -637,16 +642,28 @@ impl<'a> Parser<'a> {
             } else {
```
Comment (Centril) [inline src/libsyntax/parse/parser.rs]: This branch seems like something to refactor out to one or more functions/methods in `diagnostics.rs`?

File: src/test/ui/parser/bad-macro-argument.rs [hunk 6]
```diff
@@ -0,0 +1,4 @@
+fn main() {
```
Comment (Centril) [inline src/test/ui/parser/bad-macro-argument.rs]: There's a folder for macros in `ui/parser` -- move into there?

File: src/libsyntax/parse/parser.rs [hunk 7]
```diff
@@ -2625,16 +2599,24 @@ impl<'a> Parser<'a> {
                         }
                         Err(mut err) => {
```
Comment (Centril) [inline src/libsyntax/parse/parser.rs]: Also a candidate for refactoring?

File: src/libsyntax/config.rs [hunk 8]
```diff
@@ -117,7 +128,7 @@ impl<'a> StripUnconfigured<'a> {
             Ok(result) => result,
             Err(mut e) => {
                 e.emit();
-                return Vec::new();
+                return vec![];
```
Comment (petrochenkov) [inline src/libsyntax/config.rs]: Ha, I always do the opposite change in code I touch.

File: src/libsyntax/ext/derive.rs [hunk 9]
```diff
@@ -17,8 +17,11 @@ pub fn collect_derives(cx: &mut ExtCtxt<'_>, attrs: &mut Vec<ast::Attribute>) ->
             return true;
         }
         if !attr.is_meta_item_list() {
-            cx.span_err(attr.span,
-                        "attribute must be of the form `#[derive(Trait1, Trait2, ...)]`");
```
Comment (petrochenkov) [inline src/libsyntax/ext/derive.rs]: The output was supposed to be identical to the generic attribute input validation infra in `feature_gate.rs`.
(Some attributes like `cfg` or `derive` are very special, and have to be checked before that generic infra works.)

Comment (petrochenkov) [reply src/libsyntax/ext/derive.rs]: I removed plenty of attribute-specific messages like "missing traits to be derived" in https://github.com/rust-lang/rust/pull/57321 because the generic messages are good enough and intuitive.

Comment (petrochenkov) [reply src/libsyntax/ext/derive.rs]: The `cfg_attr` check should probably follow the same template.
I still hope that the special attributes can be made less special and go through the generic infra one day.

Comment (estebank) [reply src/libsyntax/ext/derive.rs]: I was considering (but obviously didn't do it in this PR) moving the generic errors to this new format. Is the concern about these being inconsistent or fundamentally against the new output? If it is the former, should I just do that work here for you to see what it'd look like?

Comment (petrochenkov) [reply src/libsyntax/ext/derive.rs]: Fist, consistency, second, I don't like the new wording.
"Bad attribute" doesn't says that the issue is with the attribute input specifically, and not with name or something, the format suggestion is moved too far into a note.
The status quo looks good to me (that's not surprising, since I wrote it) and I don't understand the motivation behind the change.

If I'd change anything, I'd rather move the "must be of the form #[...]" to a suggestion, since it's indeed an approximate suggesion (IIRC, it will be rendered as a label then and will stay close enough).
For the primary message in that case I'd choose something mentioning input, e.g. "ill-formed attribute input".

Comment (estebank) [reply src/libsyntax/ext/derive.rs]: I made these changes and it ballooned the size of the PR, I hope that's ok.

File: src/test/ui/target-feature-wrong.stderr [hunk 10]
```diff
@@ -1,35 +1,38 @@
-error: attribute must be of the form `#[target_feature(enable = "name")]`
+error: malformed `target_feature` attribute input
   --> $DIR/target-feature-wrong.rs:16:1
    |
 LL | #[target_feature = "+sse2"]
-   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^
+   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: must be of the form: `#[target_feature(enable = "name")]`
```
Comment (estebank) [inline src/test/ui/target-feature-wrong.stderr]: This could suggest `#[target_feature(enable = "+sse2")]`. I'll look into it later.

File: src/test/ui/repr.stderr [hunk 11]
```diff
@@ -1,20 +1,20 @@
...
+   | ^^^^^^^^^^^^^ help: must be of the form: `#[repr(C, packed, ...)]`
 
-error: attribute must be of the form `#[repr(C, packed, ...)]`
-  --> $DIR/repr.rs:9:1
+error: malformed `repr` attribute input
+  --> $DIR/repr.rs:7:1
    |
 LL | #[repr = "C"]
-   | ^^^^^^^^^^^^^
+   | ^^^^^^^^^^^^^ help: must be of the form: `#[repr(C, packed, ...)]`
```
Comment (estebank) [inline src/test/ui/repr.stderr]: This should probably just suggest `#[repr(C)]` directly.

File: src/test/ui/on-unimplemented/bad-annotation.stderr [hunk 12]
```diff
@@ -1,8 +1,14 @@
-error: attribute must be of the form `#[rustc_on_unimplemented(/*opt*/ message = "...", /*opt*/ label = "...", /*opt*/ note = "...")]` or `#[rustc_on_unimplemented = "message"]`
+error: malformed `rustc_on_unimplemented` attribute input
   --> $DIR/bad-annotation.rs:17:1
    |
 LL | #[rustc_on_unimplemented]
    | ^^^^^^^^^^^^^^^^^^^^^^^^^
+help: the following are the possible correct uses
+   |
+LL | #[rustc_on_unimplemented(/*opt*/ message = "...", /*opt*/ label = "...", /*opt*/ note = "...")]
```
Comment (estebank) [inline src/test/ui/on-unimplemented/bad-annotation.stderr]: Right now it's not possible to have more than one suggestion per input type, but now that we suggest we could add it and have a suggestion for each combination (this is probably not best example that would benefit of this).

File: src/test/ui/no_crate_type.stderr [hunk 13]
```diff
@@ -1,8 +1,8 @@
-error: attribute must be of the form `#[crate_type = "bin|lib|..."]`
+error: malformed `crate_type` attribute input
   --> $DIR/no_crate_type.rs:2:1
    |
 LL | #![crate_type]
-   | ^^^^^^^^^^^^^^
+   | ^^^^^^^^^^^^^^ help: must be of the form: `#[crate_type = "bin|lib|..."]`
```
Comment (estebank) [inline src/test/ui/no_crate_type.stderr]: Would benefit of multiple suggestions of the same type.

File: src/test/ui/malformed/malformed-unwind-1.stderr [hunk 14]
```diff
@@ -1,14 +1,14 @@
-error: attribute must be of the form `#[unwind(allowed|aborts)]`
+error: malformed `unwind` attribute input
   --> $DIR/malformed-unwind-1.rs:3:1
    |
 LL | #[unwind]
-   | ^^^^^^^^^
+   | ^^^^^^^^^ help: must be of the form: `#[unwind(allowed|aborts)]`
```
Comment (estebank) [inline src/test/ui/malformed/malformed-unwind-1.stderr]: Would benefit of multiple suggestions

File: src/test/ui/lint/reasons-erroneous.stderr [hunk 15]
```diff
@@ -1,55 +1,47 @@
...
-   = help: reason must be a string literal
+   |                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ reason must be a string literal
 
-error[E0452]: malformed lint attribute
+error[E0452]: malformed lint attribute input
   --> $DIR/reasons-erroneous.rs:9:29
    |
 LL | #![warn(bare_trait_objects, reasons = "leaders to no sure land, guides their bearings lost")]
-   |                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
+   |                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ bad attribute argument
```
Comment (estebank) [inline src/test/ui/lint/reasons-erroneous.stderr]: Should we add levenshtein distance enabled suggestions?

File: src/test/ui/lint/reasons-erroneous.stderr [hunk 16]
```diff
@@ -1,55 +1,47 @@
-error[E0452]: malformed lint attribute
+error[E0452]: malformed lint attribute input
   --> $DIR/reasons-erroneous.rs:3:58
    |
 LL | #![warn(absolute_paths_not_starting_with_crate, reason = 0)]
-   |                                                          ^
-   |
-   = help: reason must be a string literal
+   |                                                          ^ reason must be a string literal
```
Comment (estebank) [inline src/test/ui/lint/reasons-erroneous.stderr]: Could suggest `"0"`.

File: src/test/ui/lint/reasons-erroneous.stderr [hunk 17]
```diff
@@ -1,55 +1,47 @@
...
 
-error[E0452]: malformed lint attribute
+error[E0452]: malformed lint attribute input
   --> $DIR/reasons-erroneous.rs:6:40
    |
 LL | #![warn(anonymous_parameters, reason = b"consider these, for we have condemned them")]
-   |                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
-   |
-   = help: reason must be a string literal
+   |                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ reason must be a string literal
```
Comment (estebank) [inline src/test/ui/lint/reasons-erroneous.stderr]: Could suggest removing the `b`.

**Comment by estebank** [comment]
CC @rust-lang/wg-diagnostics for more eyes

File: src/libsyntax/ext/derive.rs (hunk 9 above)
Comment (petrochenkov) [reply src/libsyntax/ext/derive.rs]: FWIW, you can move the EOF staff into a separate PR and consider it r+'d.
I'll be mostly unavailable in the next few days, so this PR may land with a delay.

Comment (estebank) [reply src/libsyntax/ext/derive.rs]: Kept the EOF stuff here and opened a new one with the rewording at https://github.com/rust-lang/rust/pull/61140

**Comment by estebank** [comment]
@bors r=petrochenkov

as per https://github.com/rust-lang/rust/pull/61026#discussion_r287502465, the extraneous changes have been moved to https://github.com/rust-lang/rust/pull/61140
