### PR TITLE
Supress swapping lhs and rhs in equality suggestion in extern macro 

### LINKED ISSUE #139050: Misleading compiler suggestion: Swapp the equality in rustlib due to mismatched types in user code
### Code

```Rust
use std::fmt::Debug;

pub fn foo<I: Iterator>(mut iter: I, value: &I::Item)
where
    Item: Eq + Debug,
{
    debug_assert_eq!(iter.next(), Some(value));
}

fn main() {}
```

### Current output

```Shell
error[E0412]: cannot find type `Item` in this scope
 --> .\test.rs:5:5
  |
5 |     Item: Eq + Debug,
  |     ^^^^ not found in this scope

error[E0308]: mismatched types
 --> .\test.rs:7:35
  |
7 |     debug_assert_eq!(iter.next(), Some(value));
  |                                   ^^^^^^^^^^^ expected `Option<<I as Iterator>::Item>`, found `Option<&<I as Iterator>::Item>`
  |
  = note: expected enum `Option<_>`
             found enum `Option<&_>`
  = note: `Option<&<I as Iterator>::Item>` implements `PartialEq<Option<<I as Iterator>::Item>>`
help: consider swapping the equality
 --> C:\Users\jjl98\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib/rustlib/src/rust\library\core\src\macros\mod.rs:46:22
  |
46|                 if !(*right_val == *left_val) {
  |                      ~~~~~~~~~~    ~~~~~~~~~

error: aborting due to 2 previous errors

Some errors have detailed explanations: E0308, E0412.
For more information about an error, try `rustc --explain E0308`.
```

### Desired output

```Shell

```

### Rationale and extra context

I'm not entirely sure what the compiler's output should be, but it is inappropriate for the compiler to suggest modifying rustlib when the issue lies in the user code. This suggestion is clearly flawed.

### Other cases

```Rust

```

### Rust Version

```Shell
rustc 1.85.1 (4eb161250 2025-03-15)
binary: rustc
commit-hash: 4eb161250e340c8f48f66e2b929ef4a5bed7c181
commit-date: 2025-03-15
host: x86_64-pc-windows-msvc
release: 1.85.1
LLVM version: 19.1.7
```

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by xizheyin**
Fixes rust-lang/rust#139050

### CODE REVIEW

**Comment by compiler-errors** [comment]
If the test can't actually demonstrate the change, then there's no reason to make this into two commits. Please squash this into one.

File: compiler/rustc_hir_typeck/src/fn_ctxt/suggestions.rs [hunk 1]
```diff
@@ -3533,6 +3533,12 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
                 .must_apply_modulo_regions()
         {
             let sm = self.tcx.sess.source_map();
+            // If the span of rhs_expr is in an external macro,
+            // we should not suggest to swap the equality. See issue #139050
+            if rhs_expr.span.in_external_macro(sm) {
```
Comment (compiler-errors) [inline compiler/rustc_hir_typeck/src/fn_ctxt/suggestions.rs]: This needs to check both `lhs_expr` and `rhs_expr`, since suggestions are invalid if either are in an external macro.

**Review by compiler-errors — CHANGES_REQUESTED** [review]

File: compiler/rustc_hir_typeck/src/fn_ctxt/suggestions.rs [hunk 2]
```diff
@@ -3533,6 +3533,12 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
                 .must_apply_modulo_regions()
         {
             let sm = self.tcx.sess.source_map();
+            // If the span of rhs_expr or lhs_expr is in an external macro,
+            // we should not suggest to swap the equality. See issue #139050
+            if rhs_expr.span.in_external_macro(sm) || lhs_expr.span.in_external_macro(sm) {
+                return;
+            }
+
```
Comment (xizheyin) [inline compiler/rustc_hir_typeck/src/fn_ctxt/suggestions.rs]: Now I checked both.

**Review by xizheyin — COMMENTED** [review]
Pretty fast review!

@rustbot ready

File: compiler/rustc_hir_typeck/src/fn_ctxt/suggestions.rs [hunk 3]
```diff
@@ -3533,6 +3533,12 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
                 .must_apply_modulo_regions()
         {
             let sm = self.tcx.sess.source_map();
+            // If the span of rhs_expr or lhs_expr is in an external macro,
```
Comment (compiler-errors) [inline compiler/rustc_hir_typeck/src/fn_ctxt/suggestions.rs:3639]: There is another copy of `suggest_swapping_lhs_and_rhs` in `rustc_trait_selection`. Could you please add this check to that, too, since I think it suffers from the same issue.

Comment (xizheyin) [reply compiler/rustc_hir_typeck/src/fn_ctxt/suggestions.rs:3639]: Yeah, I'll also look for a test case for that tomorrow.

Comment (compiler-errors) [reply compiler/rustc_hir_typeck/src/fn_ctxt/suggestions.rs:3639]: I don't really think it needs a test case, but if you want to add one it's probably something like:

upstream crate:

```
macro_rules! eq {
    ($a:expr) => { $a == () }
}
```

downstream crate:

```
struct Foo;

impl PartialEq<Foo> for () {
    fn eq(&self, _: &Foo) -> bool { todo!() }
}

fn main() {
    let _ = eq!(Foo);
}
```

Pay attention to the fact that it's a trait error and there may already be some macro suppression going on there 🤔

**Comment by xizheyin** [comment]
I submitted #144268. We can find the correct span with the newly added methods, thus not needing to suppress this suggestion.

File: compiler/rustc_hir_typeck/src/fn_ctxt/suggestions.rs [hunk 4]
```diff
@@ -3539,15 +3539,25 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
                 .must_apply_modulo_regions()
         {
             let sm = self.tcx.sess.source_map();
-            if let Ok(rhs_snippet) = sm.span_to_snippet(rhs_expr.span)
-                && let Ok(lhs_snippet) = sm.span_to_snippet(lhs_expr.span)
+            // If the span of rhs_expr or lhs_expr is in an external macro,
+            // we should find the user-written code span. See issue #139050
+            if let Some(rhs_span) = rhs_expr.span.find_ancestor_not_from_extern_macro(sm)
+                && let Some(lhs_span) = lhs_expr.span.find_ancestor_not_from_extern_macro(sm)
```
Comment (xizheyin) [inline compiler/rustc_hir_typeck/src/fn_ctxt/suggestions.rs]: If the `==` is from the extern macro, it will find the first ancestor that is not from extern macro by `find_ancestor_not_from_extern_macro`.

File: compiler/rustc_hir_typeck/src/fn_ctxt/suggestions.rs [hunk 5]
```diff
@@ -3539,15 +3539,25 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
...
+                    err.multipart_suggestion(
+                        "consider swapping the equality",
+                        vec![(lhs_span, rhs_snippet), (rhs_span, lhs_snippet)],
+                        Applicability::MaybeIncorrect,
+                    );
+                } else {
+                    // rhs_span and lhs_span are the same because it from extern macro.
+                    // we should suggest to swap two arguments of the equality
+                    err.span_help(rhs_span, "consider swapping two arguments of the equality");
+                }
```
Comment (xizheyin) [inline compiler/rustc_hir_typeck/src/fn_ctxt/suggestions.rs]: It`rhs_span` and `lhs_span` is the same, it is expand from extern macro, we use `span_help` to hint.

**Review by xizheyin — COMMENTED** [review]
Now, we could reproduce the bug.
@rustbot ready

File: tests/ui/typeck/sugg-swap-equality-in-macro-issue-139050.rs [hunk 6]
```diff
@@ -8,7 +8,7 @@ extern crate ext;
 
 use std::fmt::Debug;
 
-macro_rules! eq_local {
```
Comment (nnethercote) [inline tests/ui/typeck/sugg-swap-equality-in-macro-issue-139050.rs]: You should fix these whitespace issues in the first commit.

**Comment by nnethercote** [comment]
This seems like it's doing what's it's supposed to. But it's papering over a problem, which is that the suggestion to switch the argument is incorrect -- it doesn't fix the problem. And this suggestion seems to be a new one. I don't get it in rust 1.89.0. It would be better if the suggestion wasn't given at all...

**Comment by xizheyin** [comment]
Sorry for slow response! @Dylan-DPC @nnethercote  :)

I revised the code. My initial thinking was to provide different and more precise suggestions for user-written external libraries. However, for a minimal change, directly suppressing it is also a good approach.

In this version, I directly suppressed the lhs and rhs from external macros because we cannot obtain precise spans.

Additionally, I fixed the formatting issues in the first commit proposed by @nnethercote .
