### PR TITLE
Fix clippy::collapsible_match with let expressions

### LINKED ISSUE #7575: collapsible_match suggests an incorrect behavior change
```rust
fn next() -> Option<Enum> {
    None
}

enum Enum {
    Yes,
    No,
}

fn main() {
    while let Some(thing) = next() {
        if let Enum::Yes = thing {
            println!("yes");
        }
    }
}
```

```console
$ cargo clippy

warning: unnecessary nested `if let` or `match`
  --> src/main.rs:12:9
   |
12 | /         if let Enum::Yes = thing {
13 | |             println!("yes");
14 | |         }
   | |_________^
   |
   = note: `#[warn(clippy::collapsible_match)]` on by default
help: the outer pattern can be modified to include the inner pattern
  --> src/main.rs:11:20
   |
11 |     while let Some(thing) = next() {
   |                    ^^^^^ replace this binding
12 |         if let Enum::Yes = thing {
   |                ^^^^^^^^^ with this pattern
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#collapsible_match
```

Clippy apparently wants this loop written as:

```rust
    while let Some(Enum::Yes) = next() {
        println!("yes");
    }
```

which is just not the same meaning.

### Meta

- `cargo clippy -V`: e.g. clippy 0.1.56 (0035d9d 2021-08-16)
- `rustc -Vv`:
  ```
  rustc 1.56.0-nightly (0035d9dce 2021-08-16)
  binary: rustc
  commit-hash: 0035d9dcecee49d1f7349932bfa52c05a6f83641
  commit-date: 2021-08-16
  host: x86_64-unknown-linux-gnu
  release: 1.56.0-nightly
  LLVM version: 12.0.1
  ```

### LINKED ISSUE #7586: clippy::if_let_some_result suggests changing while to if, resulting in code with different behaviour
Lint name: `if_let_some_result `

I tried this code:

```rust
struct Wat {
    counter: i32,
}

impl Wat {
    fn next(&mut self) -> Result<i32, &str> {
        self.counter += 1;
        if self.counter < 5 {
            Ok(self.counter)
        } else {
            Err("Oh no")
        }
    }
}

fn main() {
    let mut wat = Wat { counter: 0 };
    while let Some(a) = wat.next().ok() {
        dbg!(&a);
    }
}
```

When you run the above code, you get:

```
cargo run
   Compiling whilelet v0.1.0 (/home/dllu/snippets/whilelet)
    Finished dev [unoptimized + debuginfo] target(s) in 0.38s
     Running `target/debug/whilelet`
[src/main.rs:19] &a = 1
[src/main.rs:19] &a = 2
[src/main.rs:19] &a = 3
[src/main.rs:19] &a = 4
```

I expected to see this happen: *while let Ok(a) = wat.next()*

Instead, this happened: *if let Ok(a) = wat.next()*

```
cargo +nightly clippy -Z unstable-options
    Checking whilelet v0.1.0 (/home/dllu/snippets/whilelet)
warning: matching on `Some` with `ok()` is redundant
  --> src/main.rs:18:5
   |
18 |     while let Some(a) = wat.next().ok() {
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: `#[warn(clippy::if_let_some_result)]` on by default
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#if_let_some_result
help: consider matching on `Ok(a)` and removing the call to `ok` instead
   |
18 |     if let Ok(a) = wat.next() {
   |     ~~~~~~~~~~~~~~~~~~~~~~~~~

warning: `whilelet` (bin "whilelet") generated 1 warning
    Finished dev [unoptimized + debuginfo] target(s) in 0.18s
```

This is quite dangerous because if you run `--fix`, you will get code with different behaviour!!!

```
> cargo +nightly clippy -Z unstable-options --fix
    Checking whilelet v0.1.0 (/home/dllu/snippets/whilelet)
       Fixed src/main.rs (1 fix)
    Finished dev [unoptimized + debuginfo] target(s) in 0.29s
> cargo run
   Compiling whilelet v0.1.0 (/home/dllu/snippets/whilelet)
    Finished dev [unoptimized + debuginfo] target(s) in 0.37s
     Running `target/debug/whilelet`
[src/main.rs:19] &a = 1
```

### Meta

- `cargo clippy -V`: `clippy 0.1.56 (30a0a9b 2021-08-17)`
- `rustc -Vv`:
```
rustc 1.56.0-nightly (30a0a9b69 2021-08-17)
binary: rustc
commit-hash: 30a0a9b694cde95cbab863f7ef4d554f0f46b606
commit-date: 2021-08-17
host: x86_64-unknown-linux-gnu
release: 1.56.0-nightly
LLVM version: 12.0.1
```

### LINKED ISSUE #7591: FP in `collapsible_match` on futures `select!` macro
I tried this code:

```rust
use futures::executor::block_on;
use futures::future;
use futures::select;

fn main() {
    let mut a = future::ready(Some(4));
    let mut b = future::pending::<()>();

    block_on(async {
        let mut res = 0;
        select! {
            a_res = a => if let Some(a_res) = a_res { res = a_res + 1 },
            _ = b => (),
        };
        assert_eq!(res, 5);
    })
}
```

I expected to see no clippy error

Instead, this happened: 
```
warning: unnecessary nested `if let` or `match`
  --> src/main.rs:12:26
   |
12 |             a_res = a => if let Some(a_res) = a_res { res = a_res + 1 },
   |                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: `#[warn(clippy::collapsible_match)]` on by default
help: the outer pattern can be modified to include the inner pattern
  --> src/main.rs:12:13
   |
12 |             a_res = a => if let Some(a_res) = a_res { res = a_res + 1 },
   |             ^^^^^               ^^^^^^^^^^^ with this pattern
   |             |
   |             replace this binding
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#collapsible_match

```

clippy seems to want a different code which is not valid:
```rust
 Some(a_res) = a => res = a_res + 1,
```
leading to
```
  --> src/main.rs:11:9
   |
11 | /         select! {
12 | |             Some(a_res) = a => res = a_res + 1,
13 | |             _ = b => (),
14 | |         };
   | |          ^
   | |          |
   | |          pattern `_0(None)` not covered
   | |__________`main::{closure#0}::__PrivResult<std::option::Option<i32>, ()>` defined here
   |            not covered
```

### Meta

```
➜  clippy_test cargo clippy -V
clippy 0.1.56 (0035d9dc 2021-08-16)
```

### It's a recent regression

Notably, I found that with
```
clippy 0.1.56 (2d2bc94c 2021-08-15)
```

things work fine

came up in the testsuite of https://github.com/rust-lang/futures-rs/pull/2479

### PR DESCRIPTION
**Pull request by camsteffen**
This fixes rust-lang/rust-clippy#7575 which is a regression from #80357. I am fixing the bug here instead of in the clippy repo (if that's okay) because a) the regression has not been synced yet and b) I would like to land the fix on nightly asap.

The fix is basically to re-generalize `match` and `if let` for the lint implementation (they were split because `if let` no longer desugars to `match` in the HIR).

Also fixes rust-lang/rust-clippy#7586 and fixes rust-lang/rust-clippy#7591
cc @rust-lang/clippy 
@xFrednet do you want to review this?

### CODE REVIEW

**Comment by xFrednet** [comment]
Sure, I can take a look. :+1:

File: src/tools/clippy/clippy_lints/src/collapsible_match.rs [hunk 1]
```diff
@@ -49,104 +49,87 @@ declare_lint_pass!(CollapsibleMatch => [COLLAPSIBLE_MATCH]);
...
-                    let mut help_span = MultiSpan::from_spans(vec![binding_span, non_wild_inner_arm.pat.span]);
-                    help_span.push_span_label(binding_span, "replace this binding".into());
-                    help_span.push_span_label(non_wild_inner_arm.pat.span, "with this pattern".into());
-                    diag.span_help(help_span, "the outer pattern can be modified to include the inner pattern");
-                },
+            let what = |is_match| if is_match { "match" } else { "if let" };
+            let msg = format!(
+                "this `{}` can be collapsed into the outer `{}`",
+                what(matches!(inner, IfLetOrMatch::Match(..))),
+                what(outer_else_body.is_some()),
```
Comment (xFrednet) [inline src/tools/clippy/clippy_lints/src/collapsible_match.rs:122]: An outer if-let block can also have an else block, meaning that this is not a clear indication that the outer body is a `match` statement. This can lead to wrong lint messages:

##### Input `src/tools/clippy/tests/ui/collapsible_match.rs:32:9`
```rs
    // if let else, if let else
    if let Ok(val) = res_opt {
        if let Some(n) = val {
            take(n);
        } else {
            return;
        }
    } else {
        return;
    }
```

##### Output `src/tools/clippy/tests/ui/collapsible_match.stderr`
```txt
help: the outer pattern can be modified to include the inner pattern
  --> $DIR/collapsible_match.rs:24:15
   |
LL |     if let Ok(val) = res_opt {
   |               ^^^ replace this binding
LL |         if let Some(n) = val {
   |                ^^^^^^^ with this pattern

error: this `if let` can be collapsed into the outer `match`
  --> $DIR/collapsible_match.rs:32:9
   |
LL | /         if let Some(n) = val {
LL | |             take(n);
LL | |         } else {
LL | |             return;
LL | |         }
   | |_________^
```

**Review by xFrednet — COMMENTED** [review]
Only a small NIT when it comes to the lint message. I would be okay with merging this and fixing it after the sync if you want this to land ASAP. However, I would prefer to get this fixed before the sync (Also because I'm not sure if we'll have a sync before next week).

---

I needed some time to get used to the new syntax and structure with the `let` expression, and now I like it. Great work! 

Another sidenote: The commit is not linked to your GH account (The email probably isn't set). This is not a dealbreaker, just FYI in case that is not intended :upside_down_face:

File: src/tools/clippy/clippy_lints/src/collapsible_match.rs (hunk 1 above)
Comment (camsteffen) [reply src/tools/clippy/clippy_lints/src/collapsible_match.rs]: Fixed the output issue. Also fixed rust-lang/rust-clippy#7586. I changed `higher::IfLet` to strictly require that it is not in `while` loop desugaring.

> Another sidenote: The commit is not linked to your GH account (The email probably isn't set). This is not a dealbreaker, just FYI in case that is not intended 🙃

Really appreciate you pointing that out! I have a new machine and didn't have my gitconfig set up right.

File: src/tools/clippy/tests/ui/if_let_some_result.fixed [hunk 2]
```diff
@@ -20,8 +20,8 @@ fn strange_some_no_else(x: &str) -> i32 {
     }
 }
 
-fn main() {
-    let _ = str_to_int("1");
-    let _ = str_to_int_ok("2");
-    let _ = strange_some_no_else("3");
```
Comment (xFrednet) [inline src/tools/clippy/tests/ui/if_let_some_result.fixed:26]: Rust allows `unused`-lints in normal compiler UI tests. Are they now also disabled in Clippy's UI tests? (When running them locally via `cargo test` or inside the Clippy CI)

**Review by xFrednet — COMMENTED** [review]
LGTM

Just one last question

File: src/tools/clippy/tests/ui/if_let_some_result.fixed (hunk 2 above)
Comment (xFrednet) [reply src/tools/clippy/tests/ui/if_let_some_result.fixed:26]: Well, looks like @rust-log-analyzer answered the question for us ^^. We could add something like that in the future to Clippy as well ^^

File: src/tools/clippy/clippy_lints/src/collapsible_match.rs [hunk 3]
```diff
@@ -168,14 +151,30 @@ fn strip_singleton_blocks<'hir>(mut expr: &'hir Expr<'hir>) -> &'hir Expr<'hir>
     expr
 }
 
-/// A "wild-like" pattern is wild ("_") or `None`.
-/// For this lint to apply, both the outer and inner patterns
-/// must have "wild-like" branches that can be combined.
-fn is_wild_like(cx: &LateContext<'_>, pat_kind: &PatKind<'_>, arm_guard: &Option<Guard<'_>>) -> bool {
-    if arm_guard.is_some() {
+enum IfLetOrMatch<'hir> {
```
Comment (Manishearth) [inline src/tools/clippy/clippy_lints/src/collapsible_match.rs:154]: should be in utils IMO, but we can do that refactor once this is synced back

**Review by Manishearth — APPROVED** [review]

**Comment by Manishearth** [comment]
r=me when tests pass

File: src/tools/clippy/tests/ui/if_let_some_result.fixed (hunk 2 above)
Comment (camsteffen) [reply src/tools/clippy/tests/ui/if_let_some_result.fixed:26]: > Rust allows `unused`-lints in normal compiler UI tests.

Didn't know that. Sounds good for Clippy.
