### PR TITLE
Fix trait solver overflow with `non_local_definitions` lint

### LINKED ISSUE #123573: nightly-2024-04-05 regression: error[E0275]: overflow evaluating the requirement
### Code

Sorry, I don't have simple code to reproduce the issue, because the project is large.

The repro is this:

```
$ git clone https://github.com/facebook/starlark-rust

$ git co 96a2bf3d164d99cccc6cf330433d770e7d01b15a  # Latest revision

$ cargo +nightly-2024-04-05-aarch64-apple-darwin test -p starlark --lib --no-run

This works (warnings are unrelated)

$ cargo +nightly-2024-04-06-aarch64-apple-darwin test -p starlark --lib --no-run

...

error[E0275]: overflow evaluating the requirement `&_: StarlarkTypeRepr`
    |
    = help: consider increasing the recursion limit by adding a `#![recursion_limit = "256"]` attribute to your crate (`starlark`)
note: required for `&[_]` to implement `StarlarkTypeRepr`
   --> starlark/src/values/types/list/value.rs:251:17
    |
251 | impl<'a, V: 'a> StarlarkTypeRepr for &'a [V]
    |                 ^^^^^^^^^^^^^^^^     ^^^^^^^
252 | where
253 |     &'a V: StarlarkTypeRepr,
    |            ---------------- unsatisfied trait bound introduced here
    = note: 126 redundant requirements hidden
    = note: required for `&[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[...]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]` to implement `StarlarkTypeRepr`
    = note: the full name for the type has been written to '/Users/nga/devel/starlark-rust/target/debug/deps/starlark-e78de373a7652cbb.long-type-11371795697589288004.txt'
```

Contents of the mentioned file is:

```
&[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[_]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]
```

I tried increasing `#![recursion_limit = "256"]`, did not help.

### Version it worked on

```
$ cargo +nightly-2024-04-05-aarch64-apple-darwin --version
cargo 1.79.0-nightly (0637083df 2024-04-02)
$ rustc +nightly-2024-04-05-aarch64-apple-darwin --version
rustc 1.79.0-nightly (385fa9d84 2024-04-04)
```

Also works on stable.

### Version with regression

```
$ cargo +nightly-2024-04-06-aarch64-apple-darwin --version
cargo 1.79.0-nightly (0637083df 2024-04-02)
$ rustc +nightly-2024-04-06-aarch64-apple-darwin --version
rustc 1.79.0-nightly (9d79cd5f7 2024-04-05)
```

This may be duplicate of https://github.com/rust-lang/rust/issues/123493 because timing.

### PR DESCRIPTION
**Pull request by Urgau**
This PR fixes the trait solver overflow with the `non_local_definitions` lint reported in https://github.com/rust-lang/rust/issues/123573 using the suggestion from @lcnr: https://github.com/rust-lang/rust/issues/123573#issuecomment-2041348320 to use the next trait solver.

~~I have not (yet) tried to create a minimized repro~~ `@compiler-errors` did the minimization (thanks you) but I have manually tested on the `starlark-rust` project that it fixes the issue.

Fixes #123573
r? @lcnr

### CODE REVIEW

**Comment by compiler-errors** [comment]
I think I minimized a test:

```rust
#![deny(non_local_definitions)]

pub trait StarlarkTypeRepr {}

impl<'a, V: 'a> StarlarkTypeRepr for &'a [V] where &'a V: StarlarkTypeRepr {}

fn hello() {
    struct Local {}
    impl StarlarkTypeRepr for &Local {}
}
```

File: tests/ui/lint/non_local_definitions.rs [hunk 1]
```diff
@@ -461,6 +461,17 @@ non_local_macro::non_local_impl!(CargoUpdate);
 non_local_macro::non_local_macro_rules!(my_macro);
 //~^ WARN non-local `macro_rules!` definition
 
+// https://github.com/rust-lang/rust/issues/123573#issue-2229428739
+pub trait StarlarkTypeRepr {}
+
+impl<'a, T: 'a> StarlarkTypeRepr for &[T] where &'a T: StarlarkTypeRepr {}
```
Comment (compiler-errors) [inline tests/ui/lint/non_local_definitions.rs:467]: Why is this in like one mega UI test? I feel like it should he broken up into several files.

Also like, there's no reason for us to put crate-specific names on these traits. I think a placeholder name is better than StarlarkXYZ for a UI test.

Comment (Urgau) [reply tests/ui/lint/non_local_definitions.rs:467]: > Why is this in like one mega UI test? I feel like it should he broken up into several files.

Because that's currently the only UI test file for the `non_local_definitions` lint. But you're right this file is now too big, I'll split in a follow-up PR.

> Also like, there's no reason for us to put crate-specific names on these traits. I think a placeholder name is better than StarlarkXYZ for a UI test.

My reasoning is recognition (of the crate) and ease of navigation (in this file).

Comment (lcnr) [reply tests/ui/lint/non_local_definitions.rs:467]: please split this file in this PR. I would also prefer multiple self-contained tests

**Comment by lcnr** [comment]
cc @rust-lang/types. this PR changes a lint to always use the new trait solver by default to avoid errors from fatal overflow with the old solver.

This lint always runs in an empty environment and does not use generic params. It therefore does not rely on any additional behavior not required for `-Ztrait-solver=next` which is getting stabilized separately. Given that it's a lint it is also not stability or soundness relevant.

**Comment by lcnr** [comment]
Going to start a types FCP to officially state that going forward, the @rust-lang/initiative-trait-system-refactor has the authority to enable the use of the new solver in other stable, but not soundness relevant, without FCPs as long as t-types is pinged in the PR.

@rfcbot fcp merge

File: tests/ui/lint/non_local_definitions.rs (hunk 1 above)
Comment (Urgau) [reply tests/ui/lint/non_local_definitions.rs]: It took me took a bit of time but I ended up splitting it into 11 different UI test files.
It's not perfect but it's definitively much better. (I also reverted to the cratename-less repro).
