### PR TITLE
Don't report disambiguator error if link would have been ignored

### LINKED ISSUE #83859: rustdoc is parsing email link literals in docs as intradoc links in the latest nightly
I tried this code:

```rust
/// Information about an Artichoke build.
///
/// Implementations of this trait are used to set global Ruby constants that
/// describe the current build.
pub trait ReleaseMetadata {
    /// Copyright information.
    ///
    /// This value will populate the `RUBY_COPYRIGHT` constant.
    ///
    /// # Examples
    ///
    /// > artichoke - Copyright (c) 2019-2020 Ryan Lopopolo <rjl@hyperbo.la>
    fn ruby_copyright(&self) -> &str;
}
```

I expected to see this happen: rustdoc parses the link as an email address and renders it as a mailto: link.

Instead, this happened:

- https://twitter.com/artichokeruby/status/1378788852261736450
- https://github.com/artichoke/artichoke/pull/1152

```
error: unknown disambiguator `rjl`
  --> artichoke-core/src/release_metadata.rs:18:62
   |
18 |     /// > artichoke - Copyright (c) 2019-2020 Ryan Lopopolo <rjl@hyperbo.la>
   |                                                              ^^^
   |
   = note: requested on the command line with `-D rustdoc::broken-intra-doc-links`
```

### Meta

```
/usr/share/rust/.cargo/bin/rustup show
Default host: x86_64-unknown-linux-gnu
rustup home:  /home/runner/.rustup

info: syncing channel updates for '1.51.0-x86_64-unknown-linux-gnu'
info: latest update on 2021-03-25, rust version 1.51.0 (2fd73fabe 2021-03-23)
info: downloading component 'cargo'
info: downloading component 'rust-std'
info: downloading component 'rustc'
info: installing component 'cargo'
info: using up to 500.0 MiB of RAM to unpack components
info: installing component 'rust-std'
info: installing component 'rustc'
1.51.0-x86_64-unknown-linux-gnu (overridden by '/home/runner/work/artichoke/artichoke/rust-toolchain')
rustc 1.51.0 (2fd73fabe 2021-03-23)
/usr/share/rust/.cargo/bin/rustup -V
rustup 1.23.1 (3df2264a9 2020-11-30)
info: This is the version for the rustup toolchain manager, not the rustc compiler.
info: The currently active `rustc` version is `rustc 1.51.0 (2fd73fabe 2021-03-23)`
Installed rustup 1.23.1 support profiles
/usr/share/rust/.cargo/bin/rustup set profile minimal
info: profile set to 'minimal'
/usr/share/rust/.cargo/bin/rustup toolchain install nightly
info: syncing channel updates for 'nightly-x86_64-unknown-linux-gnu'
info: latest update on 2021-04-04, rust version 1.53.0-nightly (0b417ab5c 2021-04-03)
info: downloading component 'cargo'
info: downloading component 'rust-std'
info: downloading component 'rustc'
info: installing component 'cargo'
info: using up to 500.0 MiB of RAM to unpack components
info: installing component 'rust-std'
info: installing component 'rustc'

  nightly-x86_64-unknown-linux-gnu installed - rustc 1.53.0-nightly (0b417ab5c 2021-04-03)

info: checking for self-updates
/usr/share/rust/.cargo/bin/rustup override set nightly
info: using existing install for 'nightly-x86_64-unknown-linux-gnu'
info: override toolchain for '/home/runner/work/artichoke/artichoke' set to 'nightly-x86_64-unknown-linux-gnu'

  nightly-x86_64-unknown-linux-gnu unchanged - rustc 1.53.0-nightly (0b417ab5c 2021-04-03)
```

(from a GitHub Actions run, the latest nightly won't install on my Arch box due to broken components)

### PR DESCRIPTION
**Pull request by camelid**
Fixes #83859.

This prevents us from warning on links such as `<hello@example.com>`.
Note that we still warn on links such as `<hello@localhost>` because
they have no dots in them. However, the links will still work, even
though a warning is reported.

r? @jyn514

### CODE REVIEW

File: src/test/rustdoc-ui/intra-doc/email-address-localhost.rs [hunk 1]
```diff
@@ -0,0 +1,4 @@
+#![deny(warnings)]
+
+//! Email me at <hello@localhost>.
+//~^ ERROR unknown disambiguator `hello`
```
Comment (jyn514) [inline src/test/rustdoc-ui/intra-doc/email-address-localhost.rs:4]: Can you also test that dots don't have warnings?
```suggestion
//! Email me at <hello@localhost>.
//~^ ERROR unknown disambiguator `hello`

//! This link should *not* warn: <me@example.com>
```

File: src/librustdoc/passes/collect_intra_doc_links.rs [hunk 2]
```diff
@@ -1515,6 +1519,20 @@ fn range_between_backticks(ori_link: &MarkdownLink) -> Range<usize> {
         ..(ori_link.range.start + before_second_backtick_group)
 }
 
+/// Returns true if we should ignore `path_str` due to it being unlikely
+/// that it is an intra-doc link.
+/// The difference between this and [`should_ignore_link()`] is that this
+/// check should only be used on links that still have disambiguators.
```
Comment (jyn514) [inline src/librustdoc/passes/collect_intra_doc_links.rs:1525]:
```suggestion
/// Returns true if we should ignore `path_str` due to it being unlikely
/// that it is an intra-doc link.
///
/// The difference between this and [`should_ignore_link()`] is that this
/// check should only be used on links that still have disambiguators.
```

Comment (camelid) [reply src/librustdoc/passes/collect_intra_doc_links.rs:1525]: I intentionally put it all in the same paragraph so that the difference sentence would show up in the summary. But I can split them if you like.

**Comment by petrochenkov** [comment]
@camelid @jyn514 
How is `<hello@localhost>` a documentation link?
I assumed that doc links must include square brackets, as the documentation at https://doc.rust-lang.org/rustdoc/linking-to-items-by-name.html says.
The main optimization if https://github.com/rust-lang/rust/pull/94857 relies on this.

What other syntax doc links may have?

**Comment by jyn514** [comment]
Doclinks can have basically arbitrary syntax - they can be arbitrary markdown or html. The documentation at https://doc.rust-lang.org/rustdoc/linking-to-items-by-name.html describes what paths you can use inside a markdown link context, but does not describe the syntax for a markdown link itself. There's a reference here: https://daringfireball.net/projects/markdown/syntax#link
and automatic links are described here: https://daringfireball.net/projects/markdown/syntax#autolink

**Comment by jyn514** [comment]
@petrochenkov but yes you are correct, in this case it is not a intra-doc link because `hello` is not a valid disambiguator.

**Comment by jyn514** [comment]
I think a conservative estimate is `link.contains(&['[', '<'])`. Without `<`, it can't be an automatic or HTML link, and without `[` it can't be a shortcut or reference link.

**Comment by petrochenkov** [comment]
>a conservative estimate is `link.contains(&['[', '<'])`

Ok, that's also good enough.
