### PR TITLE
Suggest solutions for `fn foo(&foo: Foo)`

### LINKED ISSUE #38371: Bad compile error with fun bar(&foo: Foo) syntax
See the following code fragment:

```
struct Foo {
}

fn foo(&foo: Foo) {  // illegal syntax
}

fn main() {
    println!("Hello, world!");
}
```

This generates the following confusing error:

```
15:29:19|~/tmp/rust_compile_error (master)$ cargo build
   Compiling rust_compile_error v0.1.0 (file:///Users/ekr/tmp/rust_compile_error)
error[E0308]: mismatched types
 --> src/main.rs:4:8
  |
4 | fn foo(&foo: Foo) {
  |        ^^^^ expected struct `Foo`, found reference
  |
  = note: expected type `Foo`
  = note:    found type `&_`

error: aborting due to previous error

error: Could not compile `rust_compile_error`.
```

### PR DESCRIPTION
**Pull request by estebank**
For a given file:

```rust
struct Foo {}

fn foo(&foo: Foo) {}
```

suggest:

```
error[E0308]: mismatched types
 --> file.rs:3:8
  |
3 | fn foo(&foo: Foo) {}
  |        ^^^^ expected struct `Foo`, found reference
  |
  = note: expected type `Foo`
  = note:    found type `&_`
  = help: did you mean `foo: &Foo`?
```

Fix #38371.

### CODE REVIEW

**Comment by nikomatsakis** [comment]
@estebank I definitely think we need suggestions here, but somehow I'm not sure this output will address the core problem, which tends to be that people don't know where to put the `&`. I wonder if we want something more targeted. I am imagining something like:

```rust
error[E0308]: inappropriate pattern for type
 --> file.rs:3:8
  |
3 | fn foo(&foo: Foo) {}
  |        ^^^^ `&` pattern cannot be used to match a value of type `Foo`
  |
  = help: use `foo: &Foo` to declare an argument `foo` of type `&Foo`
```

I realize this is a deeper change, but my goals here are:

- convey to user that in fact this is a "pattern" and use the word "match" to show that is related to `match`
- give a suggestion for what I suspect they actually wanted

I am not crazy about the precise wording of my final suggestion there. (I wonder if @wycats has any suggestions here?)

**Comment by pnkfelix** [comment]
Perhaps the most important point of @nikomatsakis 's comment:

in practice, someone who writes: `fn f(&foo: Foo)` wants 
 * neither `foo: Foo` (pass by value but clearly they wanted a reference *somewhere*),
 *  nor `&foo: &Foo` (because pattern-binding of `&foo` will attempt to copy the dereferenced value into `foo`, which is probably not what was wanted either).

So I imagine a shallower change to your PR would be to make it emit:

```
help: did you mean `foo: &Foo`?
```

**Comment by nikomatsakis** [comment]
> help: did you mean `foo: &Foo`?

Yeah, this is probably best

**Comment by estebank** [comment]
Changed to @pnkfelix's version. Next time I have some time to look at this, I will look at adding a new error code for this specific case so that `--explain` has a complete explanation of the differences for the three valid cases (`f: F`, `f: &F`, `&f: &F`), as well as the more specific wording in @nikomatsakis' suggestion.

File: src/librustc_typeck/check/_match.rs [hunk 1]
```diff
@@ -212,7 +216,19 @@ impl<'a, 'gcx, 'tcx> FnCtxt<'a, 'gcx, 'tcx> {
...
                             let region = self.next_region_var(infer::PatternRegion(pat.span));
                             let rptr_ty = tcx.mk_ref(region, mt);
-                            self.demand_eqtype(pat.span, expected, rptr_ty);
+                            let err = self.demand_eqtype_diag(pat.span, expected, rptr_ty);
+                            if let Some(mut err) = err {
+                                if is_arg {
+                                    if let Ok(snippet) = self.sess().codemap()
+                                        .span_to_snippet(pat.span)
+                                    {
+                                        err.help(&format!("did you mean `{}: &{}`?",
```
Comment (nikomatsakis) [inline src/librustc_typeck/check/_match.rs]: One concern -- what happens in more extreme cases? I think we should check that the inner pattern (represented by `inner`, here) is a binding pattern, so as not to trigger for something like `fn foo(&&bar: &u32)` or `fn foo(&[bar]: &u32)`. Suggesting `&bar: &&u32` and `[bar]: &&u32` respectively doesn't seem all that helpful (that is what we will do, right?)

File: src/test/ui/mismatched_types/issue-38371.stderr [hunk 2]
```diff
@@ -0,0 +1,12 @@
+error[E0308]: mismatched types
+  --> $DIR/issue-38371.rs:14:8
+   |
+14 | fn foo(&foo: Foo) {  // illegal syntax
+   |        ^^^^ expected struct `Foo`, found reference
+   |
+   = note: expected type `Foo`
+   = note:    found type `&_`
```
Comment (nikomatsakis) [inline src/test/ui/mismatched_types/issue-38371.stderr]: I don't think we have to fix this here necessarily, but I feel like these `note:` messages are kind of distracting from the `help`, which is more likely to be of use. But I'm not sure how to fix without doing potentially more harm than good, so let's leave as is.

**Review by nikomatsakis — CHANGES_REQUESTED** [review]
Can you add the wacky test cases too?

File: src/librustc_typeck/check/_match.rs (hunk 1 above)
Comment (estebank) [inline src/librustc_typeck/check/_match.rs]: I tried adding these cases to the test and the results where:

```
fn ugh(&[bar]: &u32) {
}

error: slice pattern syntax is experimental (see issue #23121)
  --> ../../src/test/ui/mismatched_types/issue-38371.rs:26:9
   |
26 | fn ugh(&[bar]: &u32) {
   |         ^^^^^
```
```
fn agh(&&bar: &u32) {
}

error[E0308]: mismatched types
  --> ../../src/test/ui/mismatched_types/issue-38371.rs:29:9
   |
29 | fn agh(&&bar: &u32) {
   |         ^^^^ expected u32, found reference
   |
   = note: expected type `u32`
   = note:    found type `&_`
```

without changes to the code as is.

File: src/test/ui/mismatched_types/issue-38371.stderr (hunk 2 above)
Comment (estebank) [inline src/test/ui/mismatched_types/issue-38371.stderr]: For a while I've been thinking wether it would make sense to make the `expected`/`found` notes a first class comment, so that these errors would look closer to

```
error[E0308]: mismatched types
  --> ../../src/test/ui/mismatched_types/issue-38371.rs:14:8
   |
14 | fn foo(&foo: Foo) {
   |        ^^^^ expected struct `Foo`, found reference
   |
   = expected type `Foo`
   =    found type `&_`
   = help: did you mean `foo: &Foo`?

error[E0308]: mismatched types
  --> ../../src/test/ui/mismatched_types/issue-38371.rs:26:9
   |
26 | fn agh(&&bar: &u32) {
   |         ^^^^ expected u32, found reference
   |
   = expected type `u32`
   =    found type `&_`
```

If you feel there'd be value on that, I could create an issue and start a PR for it.

Comment (nikomatsakis) [inline src/test/ui/mismatched_types/issue-38371.stderr]: I agree that looks better

File: src/librustc_typeck/check/_match.rs (hunk 1 above)
Comment (nikomatsakis) [inline src/librustc_typeck/check/_match.rs]: So, the first one is a case of needing a feature-gate, but I'm surprised by the second one. What does `&&bar: &Foo` do? I can't tell why the help doesn't trigger here...?

File: src/test/ui/mismatched_types/issue-38371.stderr (hunk 2 above)
Comment (estebank) [inline src/test/ui/mismatched_types/issue-38371.stderr]: Opened #38901 for this. Working on a PR for it.

File: src/librustc_typeck/check/_match.rs (hunk 1 above)
Comment (estebank) [inline src/librustc_typeck/check/_match.rs]: >  I can't tell why the help doesn't trigger here...?

Neither can I. I've never even thought about trying to use something like `(&&bar: &u32)`.

> the first one is a case of needing a feature-gate

I figured as much. Last time I looked at this I couldn't find the appropriate feature gate, but just googled again and found it. I added the test back.

Comment (nikomatsakis) [inline src/librustc_typeck/check/_match.rs]: Maybe I'll pull your branch and build it locally and try to figure out what is going on then. I mean the tests look pretty good but I'd rather not enable misleading output if we can help it. Might take a day or two though.

**Comment by nikomatsakis** [comment]
OK, I investigated. The reason that my examples were not producing bad suggestions was because the `is_arg` flag is only true **on the outermost pattern**. This was not obvious to me and probably merits a comment. In any case, you can produce bad output with an example like this one:

```rust
fn agh(&&&bar: u32) {
}

fn main() { }
```

which emits:

```
error[E0308]: mismatched types
 --> /home/nmatsakis/tmp/foo.rs:1:8
  |
1 | fn agh(&&bar: u32) {
  |        ^^^^^ expected u32, found reference
  |
  = note: expected type `u32`
  = note:    found type `&_`
  = help: did you mean `&bar: &u32`?

error: aborting due to previous error
```

I pushed a commit addressing this issue and adding a comment -- but without a test case yet.

**Comment by alexcrichton** [comment]
@bors: retry

* https://github.com/rust-lang/rust/issues/39003
