### PR TITLE
Friendlier error message for closure argument type mismatch

### LINKED ISSUE #42143: Wrong error message with closures on nightly
The following example

```rust
fn main() {
    let a = vec![(1, 2)];
    
    let b: Vec<_> = a.iter().map(|x: (u32, u32)| 45).collect(); 
}
```

gives the following error on nightly:

```
error[E0593]: closure takes 2 arguments but 1 argument is required
 --> src/main.rs:4:30
  |
4 |     let b: Vec<_> = a.iter().map(|x: (u32, u32)| 45).collect(); 
  |                              ^^^ ------------------ takes 2 arguments
  |                              |
  |                              expected closure that takes 1 argument
```

which is wrong (`map` is expecting a function with one argument, which is what this closure is) and the following correct message on stable/beta:

```
error[E0281]: type mismatch: the type `[closure@src/main.rs:4:34: 4:52]` implements the trait `std::ops::FnMut<((u32, u32),)>`, but the trait `std::ops::FnMut<(&({integer}, {integer}),)>` is required (expected reference, found tuple)
 --> src/main.rs:4:30
  |
4 |     let b: Vec<_> = a.iter().map(|x: (u32, u32)| 45).collect(); 
  |                              ^^^
```

### PR DESCRIPTION
**Pull request by tirr-c**
Rebased #42270.
Fixes #42143.

---

`test.rs`:

```rust
fn main() {
    foo(|_: i32, _: usize| ());
}

fn foo<F>(_: F) where F: Fn(&str, usize) {}
```

Before:

```
error[E0281]: type mismatch: `[closure@test.rs:2:9: 2:30]` implements the trait `std::ops::Fn<(i32, usize)>`, but the trait `for<'r> std::ops::Fn<(&'r str, usize)>` is required
 --> test.rs:2:5
  |
2 |     foo(|_: i32, _: usize| ());
  |     ^^^ --------------------- implements `std::ops::Fn<(i32, usize)>`
  |     |
  |     expected &str, found i32
  |     requires `for<'r> std::ops::Fn<(&'r str, usize)>`
  |
  = note: required by `foo`
```

After (early):

```
error[E0631]: type mismatch in closure arguments
 --> test.rs:2:5
  |
2 |     foo(|_: i32, _: usize| ());
  |     ^^^ --------------------- takes arguments of type `i32` and `usize`
  |     |
  |     expected arguments of type `&str` and `usize`
  |
  = note: required by `foo`
```

After (current):

```
error[E0631]: type mismatch in closure arguments
 --> test.rs:2:5
  |
2 |     foo(|_: i32, _: usize| ());
  |     ^^^ --------------------- found signature of `fn(i32, usize) -> _`
  |     |
  |     expected signature of `for<'r> fn(&'r str, usize) -> _`
  |
  = note: required by `foo`
```

~~Compiler output has been changed, and a few tests are failing. Help me writing/fixing tests!~~

r? @nikomatsakis

### CODE REVIEW

File: src/librustc/traits/error_reporting.rs [hunk 1]
```diff
@@ -837,6 +832,47 @@ impl<'a, 'gcx, 'tcx> InferCtxt<'a, 'gcx, 'tcx> {
...
+                           expected_ref: ty::PolyTraitRef<'tcx>,
+                           found: ty::PolyTraitRef<'tcx>)
+        -> DiagnosticBuilder<'tcx>
+    {
+        fn build_args_type_string(trait_ref: &ty::TraitRef) -> String {
+            match trait_ref.substs.type_at(1).sty {
+                ty::TyTuple(args, _) => {
+                    let len = args.len();
+                    if len == 0 {
+                        return String::from("no arguments");
```
Comment (tirr-c) [inline src/librustc/traits/error_reporting.rs]: Is this code unreachable? I mean, will `report_closure_arg_mismatch` be called even when one of the `Fn` traits has zero arguments?

File: src/librustc/traits/error_reporting.rs [hunk 2]
```diff
@@ -837,6 +832,47 @@ impl<'a, 'gcx, 'tcx> InferCtxt<'a, 'gcx, 'tcx> {
...
+                            type_list_string.push_str(&format!("`{}`, ", ty));
+                        }
+                        type_list_string.push_str(&format!("`{}` and ", args[len-2]));
+                    }
+                    type_list_string.push_str(&format!("`{}`", args[len-1]));
+                    format!("argument{} of type {}",
+                            if len == 1 { "" } else { "s" },
+                            type_list_string)
+                },
+                _ => panic!(),
```
Comment (tirr-c) [inline src/librustc/traits/error_reporting.rs]: Is it fine to use standard panic macro like `panic!` or `unreachable!` to signal compiler bugs? (`panic!` here is a mistake, I should have used `unreachable!` here)

File: src/librustc/traits/error_reporting.rs [hunk 3]
```diff
@@ -730,40 +730,35 @@ impl<'a, 'gcx, 'tcx> InferCtxt<'a, 'gcx, 'tcx> {
                                                    expected_found.found,
                                                    expected_trait_ty.is_closure())
                 } else if let &TypeError::Sorts(ref expected_found) = e {
-                    let expected = if let ty::TyTuple(tys, _) = expected_found.expected.sty {
```
Comment (arielb1) [inline src/librustc/traits/error_reporting.rs]: You're still matching against the expected/found, which could lead to this bogusly triggering when one of the *arguments* is a tuple - when you have something like `fn((u32, u32)): Fn<(u32,)>`.

There's no reason to do so - you have the trait-refs in `expected_trait_ref` and `actual_trait_ref`.

You can get the argument length of each argument in this way:
```Rust
// skipping the binder is ok because we only care if this is a tuple
let arg_len = match X_trait_ref.skip_binder().substs.type_at(1) {
    ty::TyTuple(ref tys) => Some(tys.len()),
    _ => None
};
```
```

**Review by tirr-c — COMMENTED** [review]
I have a few questions. I've contributed to Rust a little, but still not sure how to write compiler code...

File: src/librustc/traits/error_reporting.rs (hunk 1 above)
Comment (arielb1) [reply src/librustc/traits/error_reporting.rs]: Why aren't you calling `report_type_argument_mismatch`?

Comment (arielb1) [reply src/librustc/traits/error_reporting.rs]: ok I see

Comment (arielb1) [reply src/librustc/traits/error_reporting.rs]: I think you won't see this error message - no arguments, no place for a type error.

File: src/librustc/traits/error_reporting.rs (hunk 2 above)
Comment (arielb1) [reply src/librustc/traits/error_reporting.rs]: An `unreachable!()` is ok-ish for local things, but it is recommended to use `bug!` or `span_bug!(span, "error")` - `span_bug` also displays the span of the error, which makes for easier debugging.

File: src/librustc/traits/error_reporting.rs [hunk 4]
```diff
@@ -837,6 +833,50 @@ impl<'a, 'gcx, 'tcx> InferCtxt<'a, 'gcx, 'tcx> {
...
+            }
+        }
+
+        let mut err = struct_span_err!(self.tcx.sess, span, E0631,
+                                       "type mismatch in closure arguments");
+        let found_arg_list = found.map_bound_ref(
+            move |trait_ref| build_args_type_string(span, trait_ref)
+        );
+        err.span_label(span, format!("expected {}", found_arg_list.skip_binder()));
+        if let Some(sp) = found_span {
```
Comment (arielb1) [inline src/librustc/traits/error_reporting.rs]: You should display the "takes" even when you don't have a span - aka fn pointers:
```Rust
fn foo(f: fn((u32, u32))) {
    a.iter().map(f)
}
```

Comment (arielb1) [reply src/librustc/traits/error_reporting.rs]: I think you should add a test for each case with fn pointer - arg count mismatch, same arg count but type-error, higher-ranked error, F: Fn<u32> bad bound.

Comment (arielb1) [reply src/librustc/traits/error_reporting.rs]: Higher-ranked test for fn pointers:
```Rust
fn foo<F: Fn(*mut &u32)>(_f: F) {}
fn bar<'a>(f: fn(*mut &'a u32)) { foo(f); }
```

Higher-ranked test for closures: src/test/ui/mismatched_types/closure-mismatch.rs (already exists)

Just check that the error message is sane.

**Comment by nikomatsakis** [comment]
@tirr-c this looks awesome btw!

File: src/librustc/traits/error_reporting.rs (hunk 4 above)
Comment (tirr-c) [reply src/librustc/traits/error_reporting.rs]: Can I use `note` here?

Comment (nikomatsakis) [reply src/librustc/traits/error_reporting.rs]: With respect to the span specifically, probably just something like this would be fine:

```
let found_span = found_span.unwrap_or(span);
```

i.e., if we don't have a better span, display both messages at the same place.

**Comment by tirr-c** [comment]
Tried @arielb1's test code, and I get two errors.

```rust
#![feature(unboxed_closures)]

fn main() {}
fn foo<F: Fn(*mut &u32)>(_f: F) {}
fn bar<'a>(f: fn(*mut &'a u32)) { foo(f); }
```

```
error[E0631]: type mismatch in closure arguments
 --> test.rs:5:35
  |
5 | fn bar<'a>(f: fn(*mut &'a u32)) { foo(f); }
  |                                   ^^^
  |                                   |
  |                                   expected argument of type `*mut &u32`
  |                                   takes argument of type `*mut &'a u32`
  |
  = note: required by `foo`

error[E0271]: type mismatch resolving `for<'r> <fn(*mut &'a u32) as std::ops::FnOnce<(*mut &'r u32,)>>::Output == ()`
 --> test.rs:5:35
  |
5 | fn bar<'a>(f: fn(*mut &'a u32)) { foo(f); }
  |                                   ^^^ expected bound lifetime parameter, found concrete lifetime
  |
  = note: required by `foo`

error: aborting due to 2 previous errors
```

Is this okay?

**Comment by arielb1** [comment]
> Is this okay?

Your error message says "closure" for the function pointer. You should make it say "function".

**Comment by arielb1** [comment]
Other than that the error messages look sane. Just be sure to add a UI test so I can see them before giving the r+.

Otherwise LGTM.

**Comment by tirr-c** [comment]
I've removed the test `mismatched_types/E0281` because most of the E0281 errors are replaced by E0631 which is added in this PR, and `mismatched_types/closure-arg-type-mismatch` contains tests for both E0281 and E0631.

File: src/test/ui/mismatched_types/E0281.rs [hunk 5]
```diff
@@ -1,25 +0,0 @@
-// Copyright 2016 The Rust Project Developers. See the COPYRIGHT
```
Comment (arielb1) [inline src/test/ui/mismatched_types/E0281.rs]: If E0281 still exists, please write a test that reproduces it. That's the `Fn<usize>` test.

File: src/test/ui/mismatched_types/closure-mismatch.stderr [hunk 6]
```diff
@@ -7,14 +7,13 @@ error[E0271]: type mismatch resolving `for<'r> <[closure@$DIR/closure-mismatch.r
    = note: required because of the requirements on the impl of `Foo` for `[closure@$DIR/closure-mismatch.rs:18:9: 18:15]`
    = note: required by `baz`
 
-error[E0281]: type mismatch: `[closure@$DIR/closure-mismatch.rs:18:9: 18:15]` implements the trait `std::ops::Fn<(_,)>`, but the trait `for<'r> std::ops::Fn<(&'r (),)>` is required
+error[E0631]: type mismatch in closure arguments
```
Comment (arielb1) [inline src/test/ui/mismatched_types/closure-mismatch.stderr]: This erases the binder. I don't like this error message.

**Comment by arielb1** [comment]
Please add the test for E0281 back - all error codes are supposed to have a test for them, and you can similarly add a test for E0631 with the name `E0631.rs`. We also need to think of how to handle `closure-mismatch`.

**Comment by arielb1** [comment]
```
[01:05:30] failures:
[01:05:30] 
[01:05:30] ---- /checkout/obj/build/x86_64-unknown-linux-gnu/test/error-index.md - Rust_Compiler_Error_Index (line 4928) stdout ----
[01:05:30] 	error[E0631]: type mismatch in closure arguments
[01:05:30]  --> /checkout/obj/build/x86_64-unknown-linux-gnu/test/error-index.md:7:5
[01:05:30]   |
[01:05:30] 7 |     foo(|y: String| { });
[01:05:30]   |     ^^^ --------------- takes argument of type `std::string::String`
[01:05:30]   |     |
[01:05:30]   |     expected argument of type `usize`
[01:05:30]   |
[01:05:30]   = note: required by `foo`
[01:05:30] 
[01:05:30] thread 'rustc' panicked at 'Some expected error codes were not found: ["E0281"]', /checkout/src/librustdoc/test.rs:286:8
[01:05:30] 
[01:05:30] 
[01:05:30] failures:
[01:05:30]     /checkout/obj/build/x86_64-unknown-linux-gnu/test/error-index.md - Rust_Compiler_Error_Index (line 4928)
[01:05:30] 
[01:05:30] test result: FAILED. 659 passed; 1 failed; 19 ignored; 0 measured; 0 filtered out
[01:05:30] 
[01:05:30] 
```

there's another doctest for E0281 in https://github.com/rust-lang/rust/blob/1b55d19479eabcb5d6cbda651187c7004aa28f7f/src/librustc/diagnostics.rs#L1141, you need to fix it

**Comment by tirr-c** [comment]
Should pass the test, but the documentation needs to be rewritten now I think...

**Comment by arielb1** [comment]
now you just need to use `fn` in the error messages.

**Comment by tirr-c** [comment]
```
error[E0631]: type mismatch in closure arguments
  --> src/test/ui/mismatched_types/closure-mismatch.rs:18:5
   |
18 |     baz(|_| ());
   |     ^^^ ------ found signature of fn(_) -> _
   |     |
   |     expected signature of for<'r> fn(&'r ()) -> _
   |
   = note: required because of the requirements on the impl of `Foo` for `[closure@src/test/ui/mismatched_types/closure-mismatch.rs:18:9: 18:15]`
   = note: required by `baz`
```

**Comment by tirr-c** [comment]
Error message from the test for `Fn<usize>` became worse.

Before:

```
error[E0593]: closure takes 0 arguments but 1 argument is required
  --> src/test/ui/mismatched_types/closure-arg-type-mismatch.rs:26:5
   |
26 |     bar(|| {});
   |     ^^^ ----- takes 0 arguments
   |     |
   |     expected closure that takes 1 argument
   |
   = note: required by `bar`
```

After:

```
error[E0281]: type mismatch: `[closure@src/test/ui/mismatched_types/closure-arg-type-mismatch.rs:26:9: 26:14]` implements the trait `std::ops::Fn<()>`, but the trait `std::ops::Fn<usize>` is required
  --> src/test/ui/mismatched_types/closure-arg-type-mismatch.rs:26:5
   |
26 |     bar(|| {});
   |     ^^^ ----- implements `std::ops::Fn<()>`
   |     |
   |     expected usize, found ()
   |     requires `std::ops::Fn<usize>`
   |
   = note: required by `bar`
```

**Comment by tirr-c** [comment]
```
error[E0631]: type mismatch in closure arguments
  --> E0631.rs:17:5
   |
17 |     foo(|_: isize| {});
   |     ^^^ ------------- found signature of fn(isize) -> _
   |     |
   |     expected signature of fn(usize) -> _
   |
   = note: required by `foo`

error[E0631]: type mismatch in closure arguments
  --> E0631.rs:18:5
   |
18 |     bar(|_: isize| {});
   |     ^^^ ------------- found signature of fn(isize) -> _
   |     |
   |     expected signature of fn(usize) -> _
   |
   = note: required by `bar`
```

E0281, the original error code, is *totally* replaced by E0631. I left E0281 in the error code index, though.

File: src/test/ui/mismatched_types/issue-36053-2.stderr [hunk 7]
```diff
@@ -8,14 +8,13 @@ error[E0599]: no method named `count` found for type `std::iter::Filter<std::ite
            `std::iter::Filter<std::iter::Fuse<std::iter::Once<&str>>, [closure@$DIR/issue-36053-2.rs:17:39: 17:53]> : std::iter::Iterator`
            `&mut std::iter::Filter<std::iter::Fuse<std::iter::Once<&str>>, [closure@$DIR/issue-36053-2.rs:17:39: 17:53]> : std::iter::Iterator`
 
-error[E0281]: type mismatch: `[closure@$DIR/issue-36053-2.rs:17:39: 17:53]` implements the trait `for<'r> std::ops::FnMut<(&'r str,)>`, but the trait `for<'r> std::ops::FnMut<(&'r &str,)>` is required
+error[E0631]: type mismatch in closure arguments
   --> $DIR/issue-36053-2.rs:17:32
    |
 17 |     once::<&str>("str").fuse().filter(|a: &str| true).count();
-   |                                ^^^^^^ -------------- implements `for<'r> std::ops::FnMut<(&'r str,)>`
+   |                                ^^^^^^ -------------- found signature of for<'r> fn(&'r str) -> _
```
Comment (nikomatsakis) [inline src/test/ui/mismatched_types/issue-36053-2.stderr]: Nit: we should enclose the signature in backticks:

```
 +   |                                ^^^^^^ -------------- found signature of `for<'r> fn(&'r str) -> _`
```

File: src/test/ui/mismatched_types/closure-mismatch.stderr (hunk 6 above)
Comment (estebank) [reply src/test/ui/mismatched_types/closure-mismatch.stderr]: @arielb1 the expected and found signatures are in the labels now, I'm not sure if that was the case when you left this comment.

**Comment by arielb1** [comment]
That's cool.

@bors r+
