### PR TITLE
Fix intra-doc handling of `Self` in enum

### LINKED ISSUE #82209: rustdoc: Confusing intra-doc handling of `Self` in enum
This code works fine:

```rust
pub enum Foo {
    /// [Self::Bar::abc]
    Bar {
        abc: i32,
        xyz: i32,
    },
}
```

But this code's intra-doc link doesn't resolve:

```rust
pub enum Foo {
    Bar {
        abc: i32,
        /// [Self::Bar::abc]
        xyz: i32,
    },
}
```

```
warning: unresolved link to `Bar::Bar::abc`
 --> foo.rs:4:14
  |
4 |         /// [Self::Bar::abc]
  |              ^^^^^^^^^^^^^^ no item named `Bar` in scope
  |
  = note: `#[warn(broken_intra_doc_links)]` on by default
```

Doesn't `Self` usually only refer to types, not enum variants? (Barring the proposed RFC to make enum variant types.)

### PR DESCRIPTION
**Pull request by lucas-deangelis**
Fixes #82209

### CODE REVIEW

File: src/test/rustdoc/issue-82209.rs [hunk 1]
```diff
@@ -0,0 +1,8 @@
+#![deny(broken_intra_doc_links)]
+pub enum Foo {
+    Bar {
+        abc: i32,
+        /// [Self::Bar::abc]
```
Comment (jyn514) [inline src/test/rustdoc/issue-82209.rs:5]: Can you also test that this generates the right link? There's instructions at https://rustc-dev-guide.rust-lang.org/rustdoc-internals.html#dotting-is-and-crossing-ts and examples in the other files in this directory.

Please also move this to `rustdoc/intra-doc`, with the rest of the intra-doc link tests.

File: src/librustdoc/passes/collect_intra_doc_links.rs [hunk 2]
```diff
@@ -838,6 +838,14 @@ impl<'a, 'tcx> DocFolder for LinkCollector<'a, 'tcx> {
         debug!("looking for the `Self` type");
         let self_id = if item.is_fake() {
             None
+        // Checking if the item is a field in a variant in an enum
```
Comment (jyn514) [inline src/librustdoc/passes/collect_intra_doc_links.rs:841]: Variants can only appear in enums.
```suggestion
        // Checking if the item is a field in an enum variant
```

**Review by jyn514 — APPROVED** [review]
This looks great, thanks!

File: src/test/rustdoc/issue-82209.rs (hunk 1 above)
Comment (lucas-deangelis) [reply src/test/rustdoc/issue-82209.rs]: I've added a test for the generation of the link. I used a `#![crate_name = "foo"]`at the beginning since I couldn't get it to work with `issue-82209` as the name of the file. Is the repetition of "foo" okay?

Comment (jyn514) [reply src/test/rustdoc/issue-82209.rs]: Yes, that's fine. Fyi the way to do it with dashes is to change them to underscores in the filename,  but this works too.

**Comment by jyn514** [comment]
@bors r+ squash

This is great, thanks!

File: src/test/rustdoc/issue-82209.rs (hunk 1 above)
Comment (lucas-deangelis) [reply src/test/rustdoc/issue-82209.rs]: Thanks for the explanation.
