### PR TITLE
Fix incorrect diagnostics for expected type in E0271 with an associated type

### LINKED ISSUE #57226: “expected” and “found” interchanged in error message E0308
I’m using `rustc 1.33.0-nightly (a2b0f247b 2018-12-30)`.

```rust
trait MyTrait {
    type Item;
}

struct MyStruct<T> {
    item: T
}

impl<T> MyTrait for MyStruct<T> {
    type Item = T;
}

fn func<T: MyTrait<Item=i32>>(t: T) { }

fn main() {
    func(MyStruct { item: "str" });
}
```

`func` expects an `MyTrait<Item=i32>`, so the error message should say: “expected type `i32`, found type `&str`.” Instead, they’re interchanged and it says:

```
error[E0271]: type mismatch resolving `<MyStruct<&str> as MyTrait>::Item == i32`
  --> src/main.rs:17:5
   |
17 |     func(my_struct);
   |     ^^^^ expected &str, found i32
   |
   = note: expected type `&str`
              found type `i32`
note: required by `func`
  --> src/main.rs:13:1
   |
13 | fn func<T: MyTrait<Item=i32>>(t: T) { }
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

### LINKED ISSUE #58092: Misleading message for mismatch of `associated type`
In the compiler message for type mismatching error of associated type, "expected A, found B" should be reversed ("expected B, found A").

```rust
struct X;

trait Foo {
    type Item;
}

impl Foo for X {
    type Item = i32;
}

fn foo(_: impl Foo<Item = f64>) {}

fn main() {
    foo(X);
}
```

The above example shows the error below:

```
error[E0271]: type mismatch resolving `<X as Foo>::Item == f64`
  --> (filename):14:5
   |
14 |     foo(X);
   |     ^^^ expected i32, found f64
   |
note: required by `foo`
  --> (filename):11:1
   |
11 | fn foo(_: impl Foo<Item = f64>) {}
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: aborting due to previous error

For more information about this error, try `rustc --explain E0271`.
```

Especially, compiler says "expected i32, found f64".  However "expected f64, found i32" is more natural since the mismatching here is that the function `foo()` requires `X::Item` to be `f64` but `X::Item` is actually `i32`.

Another example is below:

```rust
fn main() {
    let _ = vec![1, 2, 3].into_iter().cloned();
}
```

It causes an error like:

```
error[E0271]: type mismatch resolving `<std::vec::IntoIter<{integer}> as std::iter::Iterator>::Item == &_`
 --> (filename):2:39
  |
2 |     let _ = vec![1, 2, 3].into_iter().cloned();
  |                                       ^^^^^^ expected integer, found reference
  |
  = note: expected type `{integer}`
             found type `&_`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0271`.
```

The error here is that `Iterator::cloned()` requires `Iterator::Item` to be a reference but the supplied iterator here (`vec![1, 2, 3].into_iter()`) is a iterator generating integers. However error message is shown as if `Iterator::cloned()` required something to be an integer but that was reference. The message should be "expected reference, found integer".

## Meta

`rustc --version --verbose`:

```
rustc 1.33.0-nightly (b43986184 2019-01-11)
binary: rustc
commit-hash: b43986184b8f4e0d633e8ae1704f0e19aec30cb2
commit-date: 2019-01-11
host: x86_64-pc-windows-msvc
release: 1.33.0-nightly
LLVM version: 8.0
```

### LINKED ISSUE #64760: Incorrect note for expected type in E0271 when using an associated type
With the following code:
```
#[derive(Debug)]
struct Data {}


fn do_stuff<'a>(iterator: impl Iterator<Item = &'a Data>) {
    for item in iterator {
        println!("{:?}", item)
    }
}


fn main() {
    let v = vec![Data {}];
    
    do_stuff(v.into_iter());
}
```

the diagnostic (in nightly & stable) wrongly complains about the expected type:
```
error[E0271]: type mismatch resolving `<std::vec::IntoIter<Data> as std::iter::Iterator>::Item == &Data`
  --> src/main.rs:15:5
   |
5  | fn do_stuff<'a>(iterator: impl Iterator<Item = &'a Data>) {
   |    --------                             --------------- required by this bound in `do_stuff`
...
15 |     do_stuff(v.into_iter());
   |     ^^^^^^^^ expected struct `Data`, found &Data
   |
   = note: expected type `Data`
              found type `&Data`
```

It should be the reversed.
This makes it difficult to understand that the `into_iter` should be changed to `iter`.

### PR DESCRIPTION
**Pull request by ohadravid**
With code like the following code:

```rust
#[derive(Debug)]
struct Data {}

fn do_stuff<'a>(iterator: impl Iterator<Item = &'a Data>) {
    for item in iterator {
        println!("{:?}", item)
    }
}

fn main() {
    let v = vec![Data {}];
    
    do_stuff(v.into_iter());
}
```

the diagnostic (in nightly & stable) wrongly complains about the expected type:

```
error[E0271]: type mismatch resolving `<std::vec::IntoIter<Data> as std::iter::Iterator>::Item == &Data`
  --> src/main.rs:15:5
   |
5  | fn do_stuff<'a>(iterator: impl Iterator<Item = &'a Data>) {
   |    --------                             --------------- required by this bound in `do_stuff`
...
15 |     do_stuff(v.into_iter());
   |     ^^^^^^^^ expected struct `Data`, found &Data
   |
   = note: expected type `Data`
              found type `&Data`
```

This PR fixes this issue by flipping the expected/actual values where appropriate, so it looks like this:

```
error[E0271]: type mismatch resolving `<std::vec::IntoIter<Data> as std::iter::Iterator>::Item == &Data`
  --> main.rs:15:5
   |
5  | fn do_stuff<'a>(iterator: impl Iterator<Item = &'a Data>) {
   |    --------                             --------------- required by this bound in `do_stuff`
...
15 |     do_stuff(v.into_iter());
   |     ^^^^^^^^ expected &Data, found struct `Data`
   |
   = note: expected type `&Data`
              found type `Data`
```

This improves the output of a lot of existing tests (check out `associated-types-binding-to-type-defined-in-supertrait`!).

The only change which I wasn't too sure about is in the test `associated-types-overridden-binding-2`, but I think it's an improvement and the underlying problem is with handling of `trait_alias`.

Fix #57226, fix #64760, fix #58092.

### CODE REVIEW

**Comment by estebank** [comment]
It looks good but I am also slightly concerned with `associated-types-overridden-binding-2`, but it _is_ a weird construct where we don't point at `trait I32Iterator = Iterator<Item = i32>;` and it is a leveraging a nightly feature for it. I think the error was already not great, so r=me once CI is green.

**Comment by ohadravid** [comment]
@estebank CI is green 😄

File: src/librustc/traits/error_reporting.rs [hunk 1]
```diff
@@ -226,13 +226,30 @@ impl<'a, 'tcx> InferCtxt<'a, 'tcx> {
...
+
+                let is_normalized_ty_expected = match &obligation.cause.code {
+                    ObligationCauseCode::ItemObligation(_) |
+                    ObligationCauseCode::BindingObligation(_, _) |
+                    ObligationCauseCode::ObjectCastObligation(_) => {
+                        false
+                    }
+                    _ => {
+                        true
+                    }
```
Comment (estebank) [inline src/librustc/traits/error_reporting.rs]: This can also be written as

```
                    ObligationCauseCode::ObjectCastObligation(_) => false,
                    _ => true,
```

**Comment by ohadravid** [comment]
@estebank update the code according to your comment, CI is green again

**Comment by gralpli** [comment]
Does this also fix #63211 ?
