### PR TITLE
Suppress the error for private fields with non_exhaustive attribute

### LINKED ISSUE #147513: The "cannot create non-exhaustive struct using struct expression" warning should silence the "cannot construct `Foo` with struct literal syntax due to private fields" warning
### Code

```Rust
// src/lib.rs
#[non_exhaustive]
pub struct Foo {
    pub my_field: u32,
    private_field: i32,
}
```
```Rust
// src/main.rs
use exhaustive_test::Foo;

fn main() {
    let foo = Foo {
        my_field: 10,
    };
}
```

### Current output

```text
error[E0639]: cannot create non-exhaustive struct using struct expression
 --> src/main.rs:4:15
  |
4 |       let foo = Foo {
  |  _______________^
5 | |         my_field: 10,
6 | |     };
  | |_____^

error: cannot construct `Foo` with struct literal syntax due to private fields
 --> src/main.rs:4:15
  |
4 |     let foo = Foo {
  |               ^^^
  |
  = note: ...and other private field `private_field` that was not provided
```

### Desired output

```text
error[E0639]: cannot create non-exhaustive struct using struct expression
 --> src/main.rs:4:15
  |
4 |       let foo = Foo {
  |  _______________^
5 | |         my_field: 10,
6 | |     };
  | |_____^
```

### Rationale and extra context

There is no reason to provide two errors for the same issue, and the `#[non_exhaustive]` issue is the one that should be highlighted since it's explicitly chosen by the struct author.

### Other cases

If there is no private field, then the correct output is created.

### Rust Version

```text
$ rustc +nightly --version --verbose
rustc 1.92.0-nightly (b6f0945e4 2025-10-08)
binary: rustc
commit-hash: b6f0945e4681bc4d2faa7c22c5f61dc36abf7dd2
commit-date: 2025-10-08
host: x86_64-unknown-linux-gnu
release: 1.92.0-nightly
LLVM version: 21.1.2
```

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by chenyukang**
Fixes rust-lang/rust#147513

### CODE REVIEW

File: tests/ui/privacy/non-exhaustive-with-private-fields-147513.rs [hunk 1]
```diff
@@ -0,0 +1,22 @@
+//@ aux-build:non_exhaustive_with_private.rs
+
+// Test that creating a non-exhaustive struct from another crate
+// with private fields produces both errors:
+// 1. E0639: cannot create non-exhaustive struct using struct expression
+// 2. Error about private fields
```
Comment (Darksonn) [inline tests/ui/privacy/non-exhaustive-with-private-fields-147513.rs]: This comment is outdated.

Comment (chenyukang) [reply tests/ui/privacy/non-exhaustive-with-private-fields-147513.rs]: removed.
