### PR TITLE
MGCA: Support struct expressions without intermediary anon consts

### LINKED ISSUE #137888: ICE：rustc panicked at compiler\rustc_hir_analysis\src\hir_ty_lowering\mod.rs:2315:13
**Possible repetition of question #127972**
### Code

```Rust
#![feature(generic_const_exprs)]
macro_rules! empty {
    () => ();
}
fn bar<const N: i32>() -> [(); {
       empty! {};
       N
   }] {
}
fn main() {}
```

### Meta

`rustc --version --verbose`:
```
rustc 1.87.0-nightly (8c392966a 2025-03-01)
binary: rustc
commit-hash: 8c392966a013fd8a09e6b78b3c8d6e442bc278e1
commit-date: 2025-03-01
host: x86_64-pc-windows-msvc
release: 1.87.0-nightly
LLVM version: 20.1.0
```

### Error output

```
warning: the feature `generic_const_exprs` is incomplete and may not be safe to use and/or cause compiler crashes
  --> .\ttt\test.rs:53:12
   |
53 | #![feature(generic_const_exprs)]
   |            ^^^^^^^^^^^^^^^^^^^
   |
   = note: see issue #76560 <https://github.com/rust-lang/rust/issues/76560> for more information
   = note: `#[warn(incomplete_features)]` on by default

error: internal compiler error: compiler\rustc_hir_analysis\src\hir_ty_lowering\mod.rs:2315:13: try_lower_anon_const_lit: received const param which shouldn't be possible
  --> .\ttt\test.rs:59:8
   |
59 |        N
   |        ^
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
thread 'rustc' panicked at compiler\rustc_hir_analysis\src\hir_ty_lowering\mod.rs:2315:13:
Box<dyn Any>
stack backtrace:
   0:     0x7ff8a45f6b8e - std::backtrace_rs::backtrace::win64::trace
                               at /rustc/8c392966a013fd8a09e6b78b3c8d6e442bc278e1/library\std\src\..\..\backtrace\src\backtrace\win64.rs:85
   1:     0x7ff8a45f6b8e - std::backtrace_rs::backtrace::trace_unsynchronized
                               at /rustc/8c392966a013fd8a09e6b78b3c8d6e442bc278e1/library\std\src\..\..\backtrace\src\backtrace\mod.rs:66
   2:     0x7ff8a45f6b8e - std::backtrace::Backtrace::create
                               at /rustc/8c392966a013fd8a09e6b78b3c8d6e442bc278e1/library\std\src\backtrace.rs:331
   3:     0x7ff8a45f6aca - std::backtrace::Backtrace::force_capture
                               at /rustc/8c392966a013fd8a09e6b78b3c8d6e442bc278e1/library\std\src\backtrace.rs:312
   4:     0x7ff8a5b8e448 - core[840dbb2f2845c865]::slice::sort::unstable::heapsort::heapsort::<((rustc_lint_defs[82a80524e948e0f0]::Level, &str), usize), <((rustc_lint_defs[82a80524e948e0f0]::Level, &str), usize) as core[840dbb2f2845c865]::cmp::PartialOrd>::lt>
   5:     0x7ff8a461424e - alloc::boxed::impl$30::call
                               at /rustc/8c392966a013fd8a09e6b78b3c8d6e442bc278e1/library\alloc\src\boxed.rs:1986
   6:     0x7ff8a461424e - std::panicking::rust_panic_with_hook
                               at /rustc/8c392966a013fd8a09e6b78b3c8d6e442bc278e1/library\std\src\panicking.rs:839
   7:     0x7ff8a7265dc3 - RINvNtNtNtNtCsbkUWnEU8R6r_4core5slice4sort6stable9quicksort9quicksortTjRNtNtCseGJQQZfSkuo_12rustc_errors7snippet10AnnotationENCINvMNtCs4ufdBmpk0L3_5alloc5sliceSB15_11sort_by_keyTINtNtBa_3cmp7ReversejEbENCNCNvMs5_NtB1c_7emitterNtB3o_12HumanEmitter18render_s
   8:     0x7ff8a72596f9 - std[47ca72d4d3ff77e3]::sys::backtrace::__rust_end_short_backtrace::<std[47ca72d4d3ff77e3]::panicking::begin_panic<rustc_errors[ab188e13c83bdd4e]::ExplicitBug>::{closure#0}, !>
   9:     0x7ff8a7254868 - std[47ca72d4d3ff77e3]::panicking::begin_panic::<rustc_errors[ab188e13c83bdd4e]::ExplicitBug>
  10:     0x7ff8a7272df5 - <rustc_errors[ab188e13c83bdd4e]::diagnostic::BugAbort as rustc_errors[ab188e13c83bdd4e]::diagnostic::EmissionGuarantee>::emit_producing_guarantee
  11:     0x7ff8a70fbe8f - <hashbrown[ff07c58cb9724894]::raw::RawTable<((rustc_middle[1aca9e23c1f5e2ca]::mir::interpret::GlobalAlloc, usize), rustc_middle[1aca9e23c1f5e2ca]::mir::interpret::AllocId)>>::reserve_rehash::<hashbrown[ff07c58cb9724894]::map::make_hasher<(rustc_middle[1aca9e23c1f5e2ca]::mir::interpret::GlobalAlloc, usize), rustc_middle[1aca9e23c1f5e2ca]::mir::interpret::AllocId, rustc_hash[a5ea869f66795bec]::FxBuildHasher>::{closure#0}>
  12:     0x7ff8a7197539 - rustc_middle[1aca9e23c1f5e2ca]::util::bug::span_bug_fmt::<rustc_span[f932d894d049cea0]::span_encoding::Span>
  13:     0x7ff8a71780dd - <rustc_middle[1aca9e23c1f5e2ca]::ty::consts::Const>::to_value
  14:     0x7ff8a7177eb6 - <rustc_middle[1aca9e23c1f5e2ca]::ty::consts::Const>::to_value
  15:     0x7ff8a7197479 - rustc_middle[1aca9e23c1f5e2ca]::util::bug::span_bug_fmt::<rustc_span[f932d894d049cea0]::span_encoding::Span>
  16:     0x7ff8a3edf7ee - <dyn rustc_hir_analysis[416f618b0e25329]::hir_ty_lowering::HirTyLowerer>::lower_const_arg
  17:     0x7ff8a49b7d56 - <dyn rustc_hir_analysis[416f618b0e25329]::hir_ty_lowering::HirTyLowerer>::lower_ty
  18:     0x7ff8a49b8ec4 - <dyn rustc_hir_analysis[416f618b0e25329]::hir_ty_lowering::HirTyLowerer>::lower_fn_ty
  19:     0x7ff8a3eafffa - <rustc_hir_analysis[416f618b0e25329]::collect::ItemCtxt as rustc_hir_analysis[416f618b0e25329]::hir_ty_lowering::HirTyLowerer>::probe_ty_param_bounds
  20:     0x7ff8a498f391 - <rustc_hir_analysis[416f618b0e25329]::collect::resolve_bound_vars::BoundVarContext as rustc_hir[f712dc1a8f2aa62e]::intravisit::Visitor>::visit_impl_item
  21:     0x7ff8a53b7628 - rustc_query_impl[ea048ce6c953afc7]::plumbing::query_key_hash_verify_all
  22:     0x7ff8a53a05fd - RINvNtNtCsg1k9pdWcLJk_18rustc_query_system5query8plumbing17try_execute_queryINtCsk5FBNSQLY8t_16rustc_query_impl13DynamicConfigINtNtCsiIwSlclO99C_21rustc_data_structures9vec_cache8VecCacheNtNtCslotEWgXnnMG_10rustc_span6def_id10LocalDefIdINtNtNtCs2iBQmlseRnO
  23:     0x7ff8a5285dab - RINvNtNtCsg1k9pdWcLJk_18rustc_query_system5query8plumbing17try_execute_queryINtCsk5FBNSQLY8t_16rustc_query_impl13DynamicConfigINtNtB4_6caches10DefIdCacheINtNtNtCs2iBQmlseRnO_12rustc_middle5query5erase6ErasedAhj18_EEKb0_KB3s_KB3s_ENtNtB1f_8plumbing9QueryCtx
  24:     0x7ff8a53bf548 - rustc_query_impl[ea048ce6c953afc7]::plumbing::query_key_hash_verify_all
  25:     0x7ff8a48cfcb7 - <hashbrown[ff07c58cb9724894]::raw::RawTable<(&usize, ())>>::reserve_rehash::<hashbrown[ff07c58cb9724894]::map::make_hasher<&usize, (), rustc_hash[a5ea869f66795bec]::FxBuildHasher>::{closure#0}>
  26:     0x7ff8a4982cc5 - rustc_hir_analysis[416f618b0e25329]::check_crate
  27:     0x7ff8a4934154 - <rustc_hir_analysis[416f618b0e25329]::collect::generics_of::has_late_bound_regions::LateBoundRegionsDetector as rustc_hir[f712dc1a8f2aa62e]::intravisit::Visitor>::visit_ty
  28:     0x7ff8a53b69b8 - rustc_query_impl[ea048ce6c953afc7]::plumbing::query_key_hash_verify_all
  29:     0x7ff8a5285d8f - RINvNtNtCsg1k9pdWcLJk_18rustc_query_system5query8plumbing17try_execute_queryINtCsk5FBNSQLY8t_16rustc_query_impl13DynamicConfigINtNtB4_6caches10DefIdCacheINtNtNtCs2iBQmlseRnO_12rustc_middle5query5erase6ErasedAhj18_EEKb0_KB3s_KB3s_ENtNtB1f_8plumbing9QueryCtx
  30:     0x7ff8a53bcbc7 - rustc_query_impl[ea048ce6c953afc7]::plumbing::query_key_hash_verify_all
  31:     0x7ff8a497d009 - rustc_hir_analysis[416f618b0e25329]::check_crate
  32:     0x7ff8a53b5a03 - rustc_query_impl[ea048ce6c953afc7]::plumbing::query_key_hash_verify_all
  33:     0x7ff8a52858ce - RINvNtNtCsg1k9pdWcLJk_18rustc_query_system5query8plumbing17try_execute_queryINtCsk5FBNSQLY8t_16rustc_query_impl13DynamicConfigINtNtB4_6caches10DefIdCacheINtNtNtCs2iBQmlseRnO_12rustc_middle5query5erase6ErasedAhj18_EEKb0_KB3s_KB3s_ENtNtB1f_8plumbing9QueryCtx
  34:     0x7ff8a53bace7 - rustc_query_impl[ea048ce6c953afc7]::plumbing::query_key_hash_verify_all
  35:     0x7ff8a4941c55 - <rustc_hir_analysis[416f618b0e25329]::collect::CollectItemTypesVisitor as rustc_hir[f712dc1a8f2aa62e]::intravisit::Visitor>::visit_item
  36:     0x7ff8a490a626 - rustc_hir_analysis[416f618b0e25329]::check::wfcheck::check_well_formed
  37:     0x7ff8a53b625b - rustc_query_impl[ea048ce6c953afc7]::plumbing::query_key_hash_verify_all
  38:     0x7ff8a52ff227 - RINvNtNtCsg1k9pdWcLJk_18rustc_query_system5query8plumbing17try_execute_queryINtCsk5FBNSQLY8t_16rustc_query_impl13DynamicConfigINtNtCsiIwSlclO99C_21rustc_data_structures9vec_cache8VecCacheNtNtCslotEWgXnnMG_10rustc_span6def_id10LocalDefIdINtNtNtCs2iBQmlseRnO
  39:     0x7ff8a53c5746 - rustc_query_impl[ea048ce6c953afc7]::plumbing::query_key_hash_verify_all
  40:     0x7ff8a491d516 - rustc_hir_analysis[416f618b0e25329]::check::wfcheck::check_mod_type_wf
  41:     0x7ff8a419009b - RINvNtNtCsg1k9pdWcLJk_18rustc_query_system5query8plumbing17try_execute_queryINtCsk5FBNSQLY8t_16rustc_query_impl13DynamicConfigINtNtCsiIwSlclO99C_21rustc_data_structures9vec_cache8VecCacheNtNtCslotEWgXnnMG_10rustc_span6def_id8CrateNumINtNtNtCs2iBQmlseRnO_12
  42:     0x7ff8a40e39b6 - RINvNtNtCsg1k9pdWcLJk_18rustc_query_system5query8plumbing17try_execute_queryINtCsk5FBNSQLY8t_16rustc_query_impl13DynamicConfigINtNtB4_6caches12DefaultCacheNtNtCslotEWgXnnMG_10rustc_span6def_id13LocalModDefIdINtNtNtCs2iBQmlseRnO_12rustc_middle5query5erase6E
  43:     0x7ff8a41a35c1 - rustc_query_impl[ea048ce6c953afc7]::query_system
  44:     0x7ff8a496158a - rustc_hir_analysis[416f618b0e25329]::check_crate
  45:     0x7ff8a468928f - rustc_interface[30f504d58a964a28]::passes::resolver_for_lowering_raw
  46:     0x7ff8a0ff74d9 - rustc_interface[30f504d58a964a28]::passes::analysis
  47:     0x7ff8a4192caa - RINvNtNtCsg1k9pdWcLJk_18rustc_query_system5query8plumbing17try_execute_queryINtCsk5FBNSQLY8t_16rustc_query_impl13DynamicConfigINtNtCsiIwSlclO99C_21rustc_data_structures9vec_cache8VecCacheNtNtCslotEWgXnnMG_10rustc_span6def_id8CrateNumINtNtNtCs2iBQmlseRnO_12
  48:     0x7ff8a40a51f4 - RINvNtNtCsg1k9pdWcLJk_18rustc_query_system5query8plumbing17try_execute_queryINtCsk5FBNSQLY8t_16rustc_query_impl13DynamicConfigINtNtB4_6caches11SingleCacheINtNtNtCs2iBQmlseRnO_12rustc_middle5query5erase6ErasedAhj0_EEKb0_KB3s_KB3s_ENtNtB1f_8plumbing9QueryCtx
  49:     0x7ff8a41987a4 - rustc_query_impl[ea048ce6c953afc7]::query_system
  50:     0x7ff8a0fbd7d2 - RINvNtNtCs6a8JjPkqOIx_3std3sys9backtrace28___rust_begin_short_backtraceNCNCNCINvMNtB6_6threadNtB1h_7Builder16spawn_unchecked_INtNtCs4ufdBmpk0L3_5alloc5boxed3BoxDINtNtNtCsbkUWnEU8R6r_4core3ops8function6FnOnceuEp6OutputuNtNtB2G_6marker4SendEL_EuEs_000uECsccF
  51:     0x7ff8a0fb5d64 - RINvNtNtCs6a8JjPkqOIx_3std3sys9backtrace28___rust_begin_short_backtraceNCNCNCINvMNtB6_6threadNtB1h_7Builder16spawn_unchecked_INtNtCs4ufdBmpk0L3_5alloc5boxed3BoxDINtNtNtCsbkUWnEU8R6r_4core3ops8function6FnOnceuEp6OutputuNtNtB2G_6marker4SendEL_EuEs_000uECsccF
  52:     0x7ff8a0fae383 - RINvNtNtCs6a8JjPkqOIx_3std3sys9backtrace28___rust_begin_short_backtraceNCNCINvNtCs4cB2S276j5A_15rustc_interface4util26run_in_thread_with_globalsNCINvB1e_31run_in_thread_pool_with_globalsNCINvNtB1g_9interface12run_compileruNCNvCsccFkNLNd5xy_17rustc_driver_i
  53:     0x7ff8a0fc29d0 - RINvNtNtCs6a8JjPkqOIx_3std3sys9backtrace28___rust_begin_short_backtraceNCNCNCINvMNtB6_6threadNtB1h_7Builder16spawn_unchecked_INtNtCs4ufdBmpk0L3_5alloc5boxed3BoxDINtNtNtCsbkUWnEU8R6r_4core3ops8function6FnOnceuEp6OutputuNtNtB2G_6marker4SendEL_EuEs_000uECsccF
  54:     0x7ff8a46249ed - alloc::boxed::impl$28::call_once
                               at /rustc/8c392966a013fd8a09e6b78b3c8d6e442bc278e1/library\alloc\src\boxed.rs:1972
  55:     0x7ff8a46249ed - alloc::boxed::impl$28::call_once
                               at /rustc/8c392966a013fd8a09e6b78b3c8d6e442bc278e1/library\alloc\src\boxed.rs:1972
  56:     0x7ff8a46249ed - std::sys::pal::windows::thread::impl$0::new::thread_start
                               at /rustc/8c392966a013fd8a09e6b78b3c8d6e442bc278e1/library\std\src\sys\pal\windows\thread.rs:56
  57:     0x7ff9697d7374 - BaseThreadInitThunk
  58:     0x7ff969b3cc91 - RtlUserThreadStart


rustc version: 1.87.0-nightly (8c392966a 2025-03-01)
platform: x86_64-pc-windows-msvc

query stack during panic:
#0 [fn_sig] computing function signature of `bar`
#1 [explicit_predicates_of] computing explicit predicates of `bar`
#2 [predicates_of] computing predicates of `bar`
#3 [check_well_formed] checking that `bar` is well-formed
#4 [check_mod_type_wf] checking that types are well-formed in top-level module
#5 [analysis] running analysis passes on this crate
end of query stack

```

</p>
</details>

### LINKED ISSUE #140275: ICE: `try_lower_anon_const_lit: received const param which shouldn't be possible` with `generic_const_exprs`
Following issue may related:
- The [#137888 ](https://github.com/rust-lang/rust/issues/137888)
- And also [#127972](https://github.com/rust-lang/rust/issues/127972)
*Above issue happens in func sig instead of trait, but also want's to get the size of the array?*

### Code

```Rust
#![feature(generic_const_exprs)]
trait T{}
trait V{}
impl<const N: i32> T for [i32; N::<&mut V>] {} 

```

*A fuzzer is used, with manual minimize*

### Meta

`rustc --version --verbose`:
```
rustc 1.88.0-nightly (df35ff6c3 2025-04-23)
binary: rustc
commit-hash: df35ff6c354f1f1fbf430b84e7dea37dfe997f34
commit-date: 2025-04-23
host: x86_64-unknown-linux-gnu
release: 1.88.0-nightly
LLVM version: 20.1.2
```

### Error output

```
error: internal compiler error: compiler/rustc_hir_analysis/src/hir_ty_lowering/mod.rs:2536:13: try_lower_anon_const_lit: received const param which shouldn't be possible
 --> results/2.rs:4:32
  |
4 | impl<const N: i32> T for [i32; N::<&mut V>] {} 
  |                                ^^^^^^^^^^^


thread 'rustc' panicked at compiler/rustc_hir_analysis/src/hir_ty_lowering/mod.rs:2536:13:
Box<dyn Any>
...
query stack during panic:
#0 [type_of] computing type of `<impl at results/2.rs:4:1: 4:44>`
#1 [trait_impls_of] finding trait impls of `T`
#2 [check_well_formed] checking that `T` is well-formed
#3 [check_mod_type_wf] checking that types are well-formed in top-level module
#4 [analysis] running analysis passes on this crate
end of query stack
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
warning: the feature `generic_const_exprs` is incomplete and may not be safe to use and/or cause compiler crashes
 --> results/2.rs:1:12
  |
1 | #![feature(generic_const_exprs)]
  |            ^^^^^^^^^^^^^^^^^^^
  |
  = note: see issue #76560 <https://github.com/rust-lang/rust/issues/76560> for more information
  = note: `#[warn(incomplete_features)]` on by default

error: internal compiler error: compiler/rustc_hir_analysis/src/hir_ty_lowering/mod.rs:2536:13: try_lower_anon_const_lit: received const param which shouldn't be possible
 --> results/2.rs:4:32
  |
4 | impl<const N: i32> T for [i32; N::<&mut V>] {} 
  |                                ^^^^^^^^^^^


thread 'rustc' panicked at compiler/rustc_hir_analysis/src/hir_ty_lowering/mod.rs:2536:13:
Box<dyn Any>
stack backtrace:
   0:     0x7c354e0d3aa3 - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::h69244135d6875fb2
   1:     0x7c354e805ac7 - core::fmt::write::h8f228de95b735da4
   2:     0x7c354fc38391 - std::io::Write::write_fmt::hb10b33e03dac9dbe
   3:     0x7c354e0d3902 - std::sys::backtrace::BacktraceLock::print::hc0088d579301e87b
   4:     0x7c354e0d727a - std::panicking::default_hook::{{closure}}::hf9e3ab0f550f7255
   5:     0x7c354e0d6dff - std::panicking::default_hook::hde8dcea18bdfa1fc
   6:     0x7c354d156f23 - std[de55bbf40c15c1d9]::panicking::update_hook::<alloc[63d4616c10cc4540]::boxed::Box<rustc_driver_impl[60c1a2efe706eb75]::install_ice_hook::{closure#1}>>::{closure#0}
   7:     0x7c354e0d7af3 - std::panicking::rust_panic_with_hook::hf0478db2c66e7f22
   8:     0x7c354d192921 - std[de55bbf40c15c1d9]::panicking::begin_panic::<rustc_errors[31cbf59e29f13936]::ExplicitBug>::{closure#0}
   9:     0x7c354d186956 - std[de55bbf40c15c1d9]::sys::backtrace::__rust_end_short_backtrace::<std[de55bbf40c15c1d9]::panicking::begin_panic<rustc_errors[31cbf59e29f13936]::ExplicitBug>::{closure#0}, !>
  10:     0x7c354d1867db - std[de55bbf40c15c1d9]::panicking::begin_panic::<rustc_errors[31cbf59e29f13936]::ExplicitBug>
  11:     0x7c354d19ccf1 - <rustc_errors[31cbf59e29f13936]::diagnostic::BugAbort as rustc_errors[31cbf59e29f13936]::diagnostic::EmissionGuarantee>::emit_producing_guarantee
  12:     0x7c354d7482ec - <rustc_errors[31cbf59e29f13936]::DiagCtxtHandle>::span_bug::<rustc_span[98bd2c4b67b16de7]::span_encoding::Span, alloc[63d4616c10cc4540]::string::String>
  13:     0x7c354d7df1d7 - rustc_middle[71ebc2cfed4e8fd4]::util::bug::opt_span_bug_fmt::<rustc_span[98bd2c4b67b16de7]::span_encoding::Span>::{closure#0}
  14:     0x7c354d7ba21a - rustc_middle[71ebc2cfed4e8fd4]::ty::context::tls::with_opt::<rustc_middle[71ebc2cfed4e8fd4]::util::bug::opt_span_bug_fmt<rustc_span[98bd2c4b67b16de7]::span_encoding::Span>::{closure#0}, !>::{closure#0}
  15:     0x7c354d7ba08b - rustc_middle[71ebc2cfed4e8fd4]::ty::context::tls::with_context_opt::<rustc_middle[71ebc2cfed4e8fd4]::ty::context::tls::with_opt<rustc_middle[71ebc2cfed4e8fd4]::util::bug::opt_span_bug_fmt<rustc_span[98bd2c4b67b16de7]::span_encoding::Span>::{closure#0}, !>::{closure#0}, !>
  16:     0x7c354b8ed237 - rustc_middle[71ebc2cfed4e8fd4]::util::bug::span_bug_fmt::<rustc_span[98bd2c4b67b16de7]::span_encoding::Span>
  17:     0x7c354eb62ed6 - <dyn rustc_hir_analysis[ded1f67b4756a5c]::hir_ty_lowering::HirTyLowerer>::lower_const_arg
  18:     0x7c354eb53bf8 - <dyn rustc_hir_analysis[ded1f67b4756a5c]::hir_ty_lowering::HirTyLowerer>::lower_ty
  19:     0x7c354eb3c04b - rustc_hir_analysis[ded1f67b4756a5c]::collect::type_of::type_of
  20:     0x7c354eb3b678 - rustc_query_impl[10518d27c996caef]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[10518d27c996caef]::query_impl::type_of::dynamic_query::{closure#2}::{closure#0}, rustc_middle[71ebc2cfed4e8fd4]::query::erase::Erased<[u8; 8usize]>>
  21:     0x7c354eb359ef - rustc_query_system[5b8097dc30659efa]::query::plumbing::try_execute_query::<rustc_query_impl[10518d27c996caef]::DynamicConfig<rustc_query_system[5b8097dc30659efa]::query::caches::DefIdCache<rustc_middle[71ebc2cfed4e8fd4]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[10518d27c996caef]::plumbing::QueryCtxt, false>
  22:     0x7c354eb3559f - rustc_query_impl[10518d27c996caef]::query_impl::type_of::get_query_non_incr::__rust_end_short_backtrace
  23:     0x7c354e9d1591 - rustc_middle[71ebc2cfed4e8fd4]::ty::trait_def::trait_impls_of_provider
  24:     0x7c354e9d2ba3 - rustc_query_impl[10518d27c996caef]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[10518d27c996caef]::query_impl::trait_impls_of::dynamic_query::{closure#2}::{closure#0}, rustc_middle[71ebc2cfed4e8fd4]::query::erase::Erased<[u8; 8usize]>>
  25:     0x7c354eb359ef - rustc_query_system[5b8097dc30659efa]::query::plumbing::try_execute_query::<rustc_query_impl[10518d27c996caef]::DynamicConfig<rustc_query_system[5b8097dc30659efa]::query::caches::DefIdCache<rustc_middle[71ebc2cfed4e8fd4]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[10518d27c996caef]::plumbing::QueryCtxt, false>
  26:     0x7c354eb2c43b - rustc_query_impl[10518d27c996caef]::query_impl::trait_impls_of::get_query_non_incr::__rust_end_short_backtrace
  27:     0x7c354f4bd0ec - <rustc_trait_selection[585b92a45c9def05]::traits::select::SelectionContext>::candidate_from_obligation::{closure#0}::{closure#0}
  28:     0x7c354f0cc75b - <rustc_trait_selection[585b92a45c9def05]::traits::select::SelectionContext>::poly_select::{closure#0}
  29:     0x7c354f22cfd8 - <rustc_trait_selection[585b92a45c9def05]::traits::fulfill::FulfillProcessor as rustc_data_structures[796c5d692efe04c0]::obligation_forest::ObligationProcessor>::process_obligation
  30:     0x7c354e807648 - <rustc_data_structures[796c5d692efe04c0]::obligation_forest::ObligationForest<rustc_trait_selection[585b92a45c9def05]::traits::fulfill::PendingPredicateObligation>>::process_obligations::<rustc_trait_selection[585b92a45c9def05]::traits::fulfill::FulfillProcessor>
  31:     0x7c354ef92467 - <rustc_trait_selection[585b92a45c9def05]::traits::fulfill::FulfillmentContext<rustc_trait_selection[585b92a45c9def05]::traits::FulfillmentError> as rustc_infer[297106f8a53538f8]::traits::engine::TraitEngine<rustc_trait_selection[585b92a45c9def05]::traits::FulfillmentError>>::select_all_or_error
  32:     0x7c354f1159a6 - rustc_hir_analysis[ded1f67b4756a5c]::check::wfcheck::check_trait
  33:     0x7c354f103738 - rustc_hir_analysis[ded1f67b4756a5c]::check::wfcheck::check_well_formed
  34:     0x7c354f10186b - rustc_query_impl[10518d27c996caef]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[10518d27c996caef]::query_impl::check_well_formed::dynamic_query::{closure#2}::{closure#0}, rustc_middle[71ebc2cfed4e8fd4]::query::erase::Erased<[u8; 1usize]>>
  35:     0x7c354f101114 - rustc_query_system[5b8097dc30659efa]::query::plumbing::try_execute_query::<rustc_query_impl[10518d27c996caef]::DynamicConfig<rustc_data_structures[796c5d692efe04c0]::vec_cache::VecCache<rustc_span[98bd2c4b67b16de7]::def_id::LocalDefId, rustc_middle[71ebc2cfed4e8fd4]::query::erase::Erased<[u8; 1usize]>, rustc_query_system[5b8097dc30659efa]::dep_graph::graph::DepNodeIndex>, false, false, false>, rustc_query_impl[10518d27c996caef]::plumbing::QueryCtxt, false>
  36:     0x7c354f100c03 - rustc_query_impl[10518d27c996caef]::query_impl::check_well_formed::get_query_non_incr::__rust_end_short_backtrace
  37:     0x7c354f0fd065 - rustc_hir_analysis[ded1f67b4756a5c]::check::wfcheck::check_mod_type_wf
  38:     0x7c354f0fce5d - rustc_query_impl[10518d27c996caef]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[10518d27c996caef]::query_impl::check_mod_type_wf::dynamic_query::{closure#2}::{closure#0}, rustc_middle[71ebc2cfed4e8fd4]::query::erase::Erased<[u8; 1usize]>>
  39:     0x7c354f853c59 - rustc_query_system[5b8097dc30659efa]::query::plumbing::try_execute_query::<rustc_query_impl[10518d27c996caef]::DynamicConfig<rustc_query_system[5b8097dc30659efa]::query::caches::DefaultCache<rustc_span[98bd2c4b67b16de7]::def_id::LocalModDefId, rustc_middle[71ebc2cfed4e8fd4]::query::erase::Erased<[u8; 1usize]>>, false, false, false>, rustc_query_impl[10518d27c996caef]::plumbing::QueryCtxt, false>
  40:     0x7c354f8539ca - rustc_query_impl[10518d27c996caef]::query_impl::check_mod_type_wf::get_query_non_incr::__rust_end_short_backtrace
  41:     0x7c354ea42e72 - rustc_hir_analysis[ded1f67b4756a5c]::check_crate
  42:     0x7c354f1fed34 - rustc_interface[dc0dcaed68c46eda]::passes::run_required_analyses
  43:     0x7c354f6e2bde - rustc_interface[dc0dcaed68c46eda]::passes::analysis
  44:     0x7c354f6e2bad - rustc_query_impl[10518d27c996caef]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[10518d27c996caef]::query_impl::analysis::dynamic_query::{closure#2}::{closure#0}, rustc_middle[71ebc2cfed4e8fd4]::query::erase::Erased<[u8; 0usize]>>
  45:     0x7c354f6e867d - rustc_query_system[5b8097dc30659efa]::query::plumbing::try_execute_query::<rustc_query_impl[10518d27c996caef]::DynamicConfig<rustc_query_system[5b8097dc30659efa]::query::caches::SingleCache<rustc_middle[71ebc2cfed4e8fd4]::query::erase::Erased<[u8; 0usize]>>, false, false, false>, rustc_query_impl[10518d27c996caef]::plumbing::QueryCtxt, false>
  46:     0x7c354f6e8378 - rustc_query_impl[10518d27c996caef]::query_impl::analysis::get_query_non_incr::__rust_end_short_backtrace
  47:     0x7c354fa3bc00 - rustc_interface[dc0dcaed68c46eda]::passes::create_and_enter_global_ctxt::<core[2e306e03d5fcddd8]::option::Option<rustc_interface[dc0dcaed68c46eda]::queries::Linker>, rustc_driver_impl[60c1a2efe706eb75]::run_compiler::{closure#0}::{closure#2}>::{closure#2}::{closure#0}
  48:     0x7c354f8d1a84 - rustc_interface[dc0dcaed68c46eda]::interface::run_compiler::<(), rustc_driver_impl[60c1a2efe706eb75]::run_compiler::{closure#0}>::{closure#1}
  49:     0x7c354f70f528 - std[de55bbf40c15c1d9]::sys::backtrace::__rust_begin_short_backtrace::<rustc_interface[dc0dcaed68c46eda]::util::run_in_thread_with_globals<rustc_interface[dc0dcaed68c46eda]::util::run_in_thread_pool_with_globals<rustc_interface[dc0dcaed68c46eda]::interface::run_compiler<(), rustc_driver_impl[60c1a2efe706eb75]::run_compiler::{closure#0}>::{closure#1}, ()>::{closure#0}, ()>::{closure#0}::{closure#0}, ()>
  50:     0x7c354f70f974 - <<std[de55bbf40c15c1d9]::thread::Builder>::spawn_unchecked_<rustc_interface[dc0dcaed68c46eda]::util::run_in_thread_with_globals<rustc_interface[dc0dcaed68c46eda]::util::run_in_thread_pool_with_globals<rustc_interface[dc0dcaed68c46eda]::interface::run_compiler<(), rustc_driver_impl[60c1a2efe706eb75]::run_compiler::{closure#0}>::{closure#1}, ()>::{closure#0}, ()>::{closure#0}::{closure#0}, ()>::{closure#1} as core[2e306e03d5fcddd8]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  51:     0x7c354f710d77 - std::sys::pal::unix::thread::Thread::new::thread_start::ha9b262a03fd58cd3
  52:     0x7c35496a3708 - <unknown>
  53:     0x7c3549727aac - <unknown>
  54:                0x0 - <unknown>

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: please make sure that you have updated to the latest nightly

note: please attach the file at `/home/lw/Work/rust/nfuzz2/rustc-ice-2025-04-25T00_39_29-1692280.txt` to your bug report

note: compiler flags: -C opt-level=3 -Z no-codegen -Z mir-opt-level=4 -Z validate-mir --crate-type lib

query stack during panic:
#0 [type_of] computing type of `<impl at results/2.rs:4:1: 4:44>`
#1 [trait_impls_of] finding trait impls of `T`
#2 [check_well_formed] checking that `T` is well-formed
#3 [check_mod_type_wf] checking that types are well-formed in top-level module
#4 [analysis] running analysis passes on this crate
end of query stack
error: aborting due to 1 previous error; 1 warning emitted


```

</p>
</details>

*Please do teach me if I've done anything wrong :)*

### PR DESCRIPTION
**Pull request by BoxyUwU**
r? oli-obk

tracking issue: rust-lang/rust#132980

Fixes rust-lang/rust#127972
Fixes rust-lang/rust#137888
Fixes rust-lang/rust#140275

due to delaying a bug instead of ICEing in HIR ty lowering.

### High level goal

Under `feature(min_generic_const_args)` this PR adds another kind of const argument. A struct/variant construction const arg kind. We represent the values of the fields as themselves being const arguments which allows for uses of generic parameters subject to the existing restrictions present in `min_generic_const_args`:
```rust
fn foo<const N: Option<u32>>() {}

trait Trait {
    #[type_const]
    const ASSOC: usize;
}

fn bar<T: Trait, const N: u32>() {
    // the initializer of `_0` is a `N` which is a legal const argument
    // so this is ok.
    foo::<{ Some::<u32> { 0: N } }>();

    // this is allowed as mgca supports uses of assoc consts in the
    // type system. ie `<T as Trait>::ASSOC` is a legal const argument
    foo::<{ Some::<u32> { 0: <T as Trait>::ASSOC } }>();

    // this on the other hand is not allowed as `N + 1` is not a legal
    // const argument
    foo::<{ Some::<u32> { 0: N + 1 } }>();
}
```

This PR does not support uses of const ctors, e.g. `None`. And also does not support tuple constructors, e.g. `Some(N)`. I believe that it would not be difficult to add support for such functionality after this PR lands so have left it out deliberately.

We currently require that all generic parameters on the type being constructed be explicitly specified. I haven't really looked into why that is but it doesn't seem desirable to me as it should be legal to write `Some { ... }` in a const argument inside of a body and have that desugar to `Some::<_> { ... }`. Regardless this can definitely be a follow-up PR and I assume this is some underlying consistency with the way that elided args are handled with type paths elsewhere.

This PRs implementation of supporting struct expressions is somewhat incomplete. We don't handle `Foo { ..expr }` at all and aren't handling privacy/stability. The printing of `ConstArgKind::Struct` HIR nodes doesn't really exist either :')

I've tried to keep the implementation here somewhat deliberately incomplete as I think a number of these issues are actually quite small and self contained after this PR lands and I'm hoping it could be a good set of issues to mentor newer contributors on :thinking: I just wanted the "bare minimum" required to actually demonstrate that the previous changes are "necessary".

### `ValTree` now recurse through `ty::Const`

In order to actually represent struct/variant construction in `ty::Const` without going through an anon const we would need to introduce some new `ConstKind` variant. Let's say some hypothetical `ConstKind::ADT(Ty<'tcx>, List<Const<'tcx>>)`.

This variant would represent things the same way that `ValTree` does with the first element representing the `VariantIdx` of the enum (if its an enum), and then followed by a list of field values in definition order.

This *could* work but there are a few reasons why it's suboptimal.

First it would mean we have a second kind of `Const` that can be normalized. Right now we only have `ConstKind::Unevaluated` which possibly needs normalization. Similarly with `TyKind` we *only* have `TyKind::Alias`. If we introduced `ConstKind::ADT` it would need to be normalized to a `ConstKind::Value` eventually. This feels to me like it has the potential to cause bugs in the long run where only `ConstKind::Unevaluated` is handled by some code paths.

Secondly it would make type equality/inference be kind of... weird... It's desirable for `Some { 0: ?x } eq Some { 0: 1_u32 }` to result in `?x=1_u32`.  I can't see a way for this to work with this `ConstKind::ADT` design under the current architecture for how we represent types/consts and generally do equality operations.

We would need to wholly special case these two variants in type equality and have a custom recursive walker separate from the existing architecture for doing type equality. It would also be somewhat unique in that it's a non-rigid `ty::Const` (it can be normalized more later on in type inference) while also having somewhat "structural" equality behaviour.

Lastly, it's worth noting that its not *actually* `ConstKind::ADT` that we want. It's desirable to extend this setup to also support tuples and arrays, or even references if we wind up supporting those in const generics. Therefore this isn't really `ConstKind::ADT` but a more general `ConstKind::ShallowValue` or something to that effect. It represents at least one "layer" of a types value :')

Instead of doing this implementation choice we instead change `ValTree::Branch`:
```rust
enum ValTree<'tcx> {
    Leaf(ScalarInt),
    // Before this PR:
    Branch(Box<[ValTree<'tcx>]>),
    // After this PR
    Branch(Box<[Const<'tcx>]>),
}
```

The representation for so called "shallow values" is now the same as the representation for the *entire* full value. The desired inference/type equality behaviour just falls right out of this. We also don't wind up with these shallow values actually being non-rigid. And `ValTree` *already* supports references/tuples/arrays so we can handle those just fine.

I think in the future it might be worth considering inlining `ValTree` into `ty::ConstKind`. E.g:
```rust
enum ConstKind {
    Scalar(Ty<'tcx>, ScalarInt),
    ShallowValue(Ty<'tcx>, List<Const<'tcx>>),
    Unevaluated(UnevaluatedConst<'tcx>),
    ...
}
```

This would imply that the usage of `ValTree`s in patterns would now be using `ty::Const` but they already kind of are anyway and I think that's probably okay in the long run. It also would mean that the set of things we *could* represent in const patterns is greater which may be desirable in the long run for supporting things such as const patterns of const generic parameters.

Regardless, this PR doesn't actually inline `ValTree` into `ty::ConstKind`, it only changes `Branch` to recurse through `Const`. This change could be split out of this PR if desired. 

I'm not sure if there'll be a perf impact from this change. It's somewhat plausible as now all const pattern values that have nesting will be interning a lot more `Ty`s. We shall see :>

### Forbidding generic parameters under mgca

Under mgca we now allow all const arguments to resolve paths to generic parameters. We then *later* actually validate that the const arg should be allowed to access generic parameters if it did wind up resolving to any.

This winds up just being a lot simpler to implement than trying to make name resolution "keep track" of whether we're inside of a non-anon-const const arg and then encounter a `const { ... }` indicating we should now stop allowing resolving to generic parameters.

It's also somewhat in line with what we'll need for a `feature(generic_const_args)` where we'll want to decide whether an anon const should have any generic parameters based off syntactically whether any generic parameters were used. Though that design is entirely hypothetical at this point :)

### Followup Work

- Make HIR ty lowering check whether lowering generic parameters is supported and if not lower to an error type/const. Should make the code cleaner, fix some other bugs, and maybe(?) recover perf since we'll be accessing less queries which I think is part of the perf regression of this PR
- Make the ValTree setup less scuffed. We should find a new name for `ConstKind::Value` and the `Val` part of `ValTree` and `ty::Value` as they no longer correspond to a fully normalized structure. It may also be worth looking into inlining `ValTreeKind` into `ConstKind` or atleast into `ty::Value` or sth :thinking:
- Support tuple constructors and const constructors not just struct expressions.
- Reduce code duplication between HIR ty lowering's handling of struct expressions, and HIR typeck's handling of struct expressions
- Try fix perf https://github.com/rust-lang/rust/pull/149114#issuecomment-3668038853. Maybe this will clear up once we clean up `ValTree` a bit and stop doing double interning and whatnot

### CODE REVIEW

File: compiler/rustc_middle/src/arena.rs [hunk 1]
```diff
@@ -92,7 +92,7 @@ macro_rules! arena_types {
             [] name_set: rustc_data_structures::unord::UnordSet<rustc_span::Symbol>,
             [] autodiff_item: rustc_ast::expand::autodiff_attrs::AutoDiffItem,
             [] ordered_name_set: rustc_data_structures::fx::FxIndexSet<rustc_span::Symbol>,
-            [] valtree: rustc_middle::ty::ValTreeKind<'tcx>,
+            [] valtree: rustc_middle::ty::ValTreeKind<rustc_middle::ty::TyCtxt<'tcx>>,
```
Comment (BoxyUwU) [inline compiler/rustc_middle/src/arena.rs:95]: this is in the wrong commit :<

File: compiler/rustc_ast/src/ast.rs [hunk 2]
```diff
@@ -1372,6 +1367,15 @@ pub enum UnsafeSource {
     UserProvided,
 }
 
+/// Track whether under `feature(min_generic_const_args)` this anon const
+/// was explicitly disambiguated as an anon const or not through the use of
+/// `const { ... }` syntax.
+#[derive(Clone, PartialEq, Encodable, Decodable, Debug, Copy, Walkable)]
+pub enum MgcaDisambiguation {
+    AnonConst,
+    Direct,
```
Comment (BoxyUwU) [inline compiler/rustc_ast/src/ast.rs:1389]: probably comment on what `Direct` means

File: compiler/rustc_ast/src/ast.rs [hunk 3]
```diff
@@ -1372,6 +1367,15 @@ pub enum UnsafeSource {
     UserProvided,
 }
 
+/// Track whether under `feature(min_generic_const_args)` this anon const
+/// was explicitly disambiguated as an anon const or not through the use of
+/// `const { ... }` syntax.
+#[derive(Clone, PartialEq, Encodable, Decodable, Debug, Copy, Walkable)]
+pub enum MgcaDisambiguation {
```
Comment (BoxyUwU) [inline compiler/rustc_ast/src/ast.rs:1387]: gotta be a better name here :') it is entirely mgca specific though

File: compiler/rustc_ty_utils/src/consts.rs [hunk 4]
```diff
@@ -43,7 +43,7 @@ fn destructure_const<'tcx>(
         ty::Adt(def, args) => {
             let (variant_idx, branches) = if def.is_enum() {
                 let (head, rest) = branches.split_first().unwrap();
-                (VariantIdx::from_u32(head.unwrap_leaf().to_u32()), rest)
+                (VariantIdx::from_u32(head.to_value().valtree.unwrap_leaf().to_u32()), rest)
```
Comment (BoxyUwU) [inline compiler/rustc_ty_utils/src/consts.rs]: the addition of all the `.to_value().valtree` everywhere is kind of unfortunate

File: compiler/rustc_mir_build/src/thir/constant.rs [hunk 5]
```diff
@@ -63,7 +63,7 @@ pub(crate) fn lit_to_const<'tcx>(
             // A CStr is a newtype around a byte slice, so we create the inner slice here.
             // We need a branch for each "level" of the data structure.
             let bytes = ty::ValTree::from_raw_bytes(tcx, byte_sym.as_byte_str());
-            ty::ValTree::from_branches(tcx, [bytes])
+            ty::ValTree::from_branches(tcx, [ty::Const::new_value(tcx, bytes, *inner_ty)])
```
Comment (BoxyUwU) [inline compiler/rustc_mir_build/src/thir/constant.rs:66]: same with all the extra calls to `ty::Const::new_x`

File: compiler/rustc_hir_analysis/src/hir_ty_lowering/mod.rs [hunk 6]
```diff
@@ -2263,8 +2263,79 @@ impl<'tcx> dyn HirTyLowerer<'tcx> + '_ {
...
+                let opt_discr_const = if adt_def.is_enum() {
+                    let valtree = ty::ValTree::from_scalar_int(tcx, variant_idx.into());
+                    Some(ty::Const::new_value(tcx, valtree, tcx.types.u32))
+                } else {
+                    None
+                };
+
+                let valtree =
+                    ty::ValTree::from_branches(tcx, opt_discr_const.into_iter().chain(fields));
+                ty::Const::new_value(tcx, valtree, ty)
```
Comment (BoxyUwU) [inline compiler/rustc_hir_analysis/src/hir_ty_lowering/mod.rs]: need to add some tests into this commit, pretty much any of the example code ive written for showing the PR to people :laughing:

**Comment by BoxyUwU** [comment]
>   62 | #![deny(clippy::manual_let_else)]

Oh dear.. why is this a thing

File: tests/ui/const-generics/mgca/adt_expr_fields_type_check.rs [hunk 7]
```diff
@@ -0,0 +1,17 @@
+//@ check-pass
+// This should error
```
Comment (BoxyUwU) [inline tests/ui/const-generics/mgca/adt_expr_fields_type_check.rs]: should be a simple fix in theory. just updating wf obligations to return `ConstArgHasType` stuff for `ty::Const` inside of valtrees. seems fairly self contained and could be a nice issue for someone to work on for dipping toes into type system stuff

File: compiler/rustc_resolve/src/def_collector.rs [hunk 8]
```diff
@@ -360,29 +366,71 @@ impl<'a, 'ra, 'tcx> visit::Visitor<'a> for DefCollector<'a, 'ra, 'tcx> {
...
+                self.visit_path(path);
+
+                match rest {
+                    StructRest::Base(expr) => self.visit_expr(expr),
+                    _ => (),
+                }
+
                 return;
             }
+            ExprKind::Field(ref init_expr, _) if self.invocation_parent.in_direct_const_arg => {
```
Comment (BoxyUwU) [inline compiler/rustc_resolve/src/def_collector.rs]: tests for this case

File: compiler/rustc_resolve/src/def_collector.rs [hunk 9]
```diff
@@ -360,29 +366,71 @@ impl<'a, 'ra, 'tcx> visit::Visitor<'a> for DefCollector<'a, 'ra, 'tcx> {
...
-                for attr in &expr.attrs {
-                    visit::walk_attribute(self, attr);
+                handle_const_block(self, constant, DefKind::InlineConst);
+                return;
+            }
+            ExprKind::Struct(ref se) if self.invocation_parent.in_direct_const_arg => {
+                let StructExpr { qself, path, fields, rest } = &**se;
+
+                for init_expr in fields {
+                    if let ExprKind::ConstBlock(ref constant) = init_expr.expr.kind {
```
Comment (BoxyUwU) [inline compiler/rustc_resolve/src/def_collector.rs]: need to special case literals so that `field: 1` can work without an explicit anon const

Comment (BoxyUwU) [reply compiler/rustc_resolve/src/def_collector.rs]: actually that seems kind of annoying. there's not really a nodeid to associate the defid with so just gonna write a test showing the special case doesn't apply here :>

File: compiler/rustc_hir_typeck/src/lib.rs [hunk 10]
```diff
@@ -116,6 +116,13 @@ fn typeck_with_inspect<'tcx>(
         return tcx.typeck(typeck_root_def_id);
     }
 
+    if let DefKind::AnonConst = tcx.def_kind(def_id)
+        && let ty::AnonConstKind::MCG = tcx.anon_const_kind(def_id)
+        && let Err(e) = tcx.hir_const_arg_anon_check_invalid_param_uses(def_id)
```
Comment (lcnr) [inline compiler/rustc_hir_typeck/src/lib.rs]: `check_const_arg_invalid_param_uses`?

File: compiler/rustc_hir_analysis/src/hir_ty_lowering/mod.rs [hunk 11]
```diff
@@ -2378,6 +2378,14 @@ impl<'tcx> dyn HirTyLowerer<'tcx> + '_ {
         let expr = &tcx.hir_body(anon.body).value;
         debug!(?expr);
 
+        // If the rhs is an anon const naming generics it shouldn't have
+        // access to then we lower to `ConstKind::Error`.
+        if let ty::AnonConstKind::MCG = tcx.anon_const_kind(anon.def_id)
+            && let Err(e) = tcx.hir_const_arg_anon_check_invalid_param_uses(anon.def_id)
+        {
+            return ty::Const::new_error(tcx, e);
+        }
```
Comment (lcnr) [inline compiler/rustc_hir_analysis/src/hir_ty_lowering/mod.rs]: is this necessary?

File: compiler/rustc_hir_typeck/src/lib.rs [hunk 12]
```diff
@@ -116,6 +116,13 @@ fn typeck_with_inspect<'tcx>(
...
+    {
+        e.raise_fatal();
```
Comment (lcnr) [inline compiler/rustc_hir_typeck/src/lib.rs:127]: kinda meh:

three options

wrap with `Result<TypeckResults, ErrorGuaranteed>`
- meh, not used by other code

make a dummy `TypeckResults`
- fragile, we don't have good test coverage for how e.g. lints access the typeck results, likely to cause a bunch of rare ICE

change `HirTyLowering` to disable lowering anything to `ty::Param`/`ConstKind`
- similar to "forbid lower to infer"
- seems best, add fixme for this pls :3

File: compiler/rustc_middle/src/hir/map.rs [hunk 13]
```diff
@@ -1086,6 +1088,47 @@ impl<'tcx> TyCtxt<'tcx> {
 
         None
     }
+
+    pub fn hir_const_arg_anon_check_invalid_param_uses(
```
Comment (lcnr) [inline compiler/rustc_middle/src/hir/map.rs]: pretty iffy, idk, add fixme that we should remove it medium-term

File: compiler/rustc_ast_lowering/src/lib.rs [hunk 14]
```diff
@@ -2394,6 +2394,37 @@ impl<'a, 'hir> LoweringContext<'a, 'hir> {
 
                 ConstArg { hir_id: self.next_id(), kind: hir::ConstArgKind::Path(qpath) }
             }
+            ExprKind::Struct(se) => {
+                let path = self.lower_qpath(
+                    expr.id,
+                    &se.qself,
+                    &se.path,
+                    ParamMode::Explicit,
```
Comment (lcnr) [inline compiler/rustc_ast_lowering/src/lib.rs:2421]: add FIXME that we should use `Optional` here and make sure the `ItemCtxt` still errors if u do it in a signature

File: compiler/rustc_ast_lowering/src/lib.rs [hunk 15]
```diff
@@ -2394,6 +2394,37 @@ impl<'a, 'hir> LoweringContext<'a, 'hir> {
...
+                    AllowReturnTypeNotation::No,
+                    ImplTraitContext::Disallowed(ImplTraitPosition::Path),
+                    None,
+                );
+
+                let fields = self.arena.alloc_from_iter(se.fields.iter().map(|f| {
+                    let hir_id = self.lower_node_id(f.id);
+                    self.lower_attrs(hir_id, &f.attrs, f.span, Target::ExprField);
```
Comment (lcnr) [inline compiler/rustc_ast_lowering/src/lib.rs:2432]: add fixme to look into this, I expect this to be broken as it causes us to silently allow attrs

File: compiler/rustc_ast_lowering/src/lib.rs [hunk 16]
```diff
@@ -2394,6 +2394,37 @@ impl<'a, 'hir> LoweringContext<'a, 'hir> {
...
+
+                    let expr = if let ExprKind::ConstBlock(anon_const) = &f.expr.kind {
+                        self.lower_anon_const_to_const_arg_direct(anon_const)
+                    } else {
+                        self.lower_expr_to_const_arg_direct(&f.expr)
```
Comment (lcnr) [inline compiler/rustc_ast_lowering/src/lib.rs:2441]: this naming sucks :3 we should rename the `lower_ty` and `lower_ty_direct` to `lower_ty_and_intern` and `lower_ty`.

Same with const stuff.

File: compiler/rustc_hir/src/intravisit.rs [hunk 17]
```diff
@@ -1067,7 +1081,17 @@ pub fn walk_const_arg<'v, V: Visitor<'v>>(
 ) -> V::Result {
     let ConstArg { hir_id, kind } = const_arg;
     try_visit!(visitor.visit_id(*hir_id));
+
```
Comment (lcnr) [inline compiler/rustc_hir/src/intravisit.rs]: why whitespace

File: compiler/rustc_middle/src/hir/mod.rs [hunk 18]
```diff
@@ -315,6 +315,7 @@ impl<'tcx> TyCtxt<'tcx> {
             Node::Block(_)
             | Node::Arm(_)
             | Node::ExprField(_)
+            | Node::ConstArgExprField(_)
```
Comment (lcnr) [inline compiler/rustc_middle/src/hir/mod.rs]: try to move into an unreachable branch and then we get a test if it ICEs after merge

File: compiler/rustc_resolve/src/def_collector.rs [hunk 19]
```diff
@@ -363,27 +369,61 @@ impl<'a, 'ra, 'tcx> visit::Visitor<'a> for DefCollector<'a, 'ra, 'tcx> {
         if let MgcaDisambiguation::Direct = constant.mgca_disambiguation
```
Comment (lcnr) [inline compiler/rustc_resolve/src/def_collector.rs]: make this a match now that mgca impacts both branches

File: compiler/rustc_resolve/src/def_collector.rs [hunk 20]
```diff
@@ -363,27 +369,61 @@ impl<'a, 'ra, 'tcx> visit::Visitor<'a> for DefCollector<'a, 'ra, 'tcx> {
...
         let parent_def = match expr.kind {
             ExprKind::MacCall(..) => return self.visit_macro_invoc(expr.id),
             ExprKind::Closure(..) | ExprKind::Gen(..) => {
                 self.create_def(expr.id, None, DefKind::Closure, expr.span)
             }
             ExprKind::ConstBlock(ref constant) => {
-                for attr in &expr.attrs {
-                    visit::walk_attribute(self, attr);
+                handle_const_block(self, constant, DefKind::InlineConst);
+                return;
```
Comment (lcnr) [inline compiler/rustc_resolve/src/def_collector.rs]:
```                
return handle_const_block(self, constant, DefKind::InlineConst);
```

File: compiler/rustc_resolve/src/def_collector.rs [hunk 21]
```diff
@@ -363,27 +369,61 @@ impl<'a, 'ra, 'tcx> visit::Visitor<'a> for DefCollector<'a, 'ra, 'tcx> {
...
+                }
+
+                if let Some(qself) = qself {
+                    self.visit_qself(qself);
+                }
+                self.visit_path(path);
+
+                match rest {
+                    StructRest::Base(expr) => self.visit_expr(expr),
+                    _ => (),
```
Comment (lcnr) [inline compiler/rustc_resolve/src/def_collector.rs]: ??? why no exhaustive

File: compiler/rustc_resolve/src/def_collector.rs
Comment (lcnr) [inline compiler/rustc_resolve/src/def_collector.rs]: can you rewrite this to only use `with_parent` if we actually create a new def_id and just `walk_expr` in the other branches?

File: compiler/rustc_resolve/src/def_collector.rs [hunk 22]
```diff
@@ -363,27 +369,61 @@ impl<'a, 'ra, 'tcx> visit::Visitor<'a> for DefCollector<'a, 'ra, 'tcx> {
...
-                    visit::walk_attribute(self, attr);
+                handle_const_block(self, constant, DefKind::InlineConst);
+                return;
+            }
+            ExprKind::Struct(ref se) if self.invocation_parent.in_direct_const_arg => {
+                let StructExpr { qself, path, fields, rest } = &**se;
+
+                for init_expr in fields {
+                    if let ExprKind::ConstBlock(ref constant) = init_expr.expr.kind {
+                        handle_const_block(self, constant, DefKind::AnonConst);
```
Comment (lcnr) [inline compiler/rustc_resolve/src/def_collector.rs]: please add a comment that we only do this to give const blocks a different `DefKind`, the rest is just a `walk`

File: compiler/rustc_type_ir/src/const_kind.rs [hunk 23]
```diff
@@ -124,3 +124,39 @@ impl<CTX> HashStable<CTX> for InferConst {
...
+    //SliceOrStr(ValSlice<'tcx>),
+    // don't use SliceOrStr for now
+    /// The fields of any kind of aggregate. Structs, tuples and arrays are represented by
+    /// listing their fields' values in order.
+    ///
+    /// Enums are represented by storing their variant index as a u32 field, followed by all
+    /// the fields of the variant.
+    ///
+    /// ZST types are represented as an empty slice.
+    Branch(Box<[I::Const]>),
```
Comment (lcnr) [inline compiler/rustc_type_ir/src/const_kind.rs:163]: pls add FIXME to use a `List`

Comment (lcnr) [reply compiler/rustc_type_ir/src/const_kind.rs:163]: also add FIXME to struct that we shouldn't intern valtree anymore, we already intern `Const` and valtree is now always directly inside of `Const`

File: compiler/rustc_type_ir/src/inherent.rs [hunk 24]
```diff
@@ -292,6 +292,11 @@ pub trait ValueConst<I: Interner<ValueConst = Self>>: Copy + Debug + Hash + Eq {
     fn valtree(self) -> I::ValTree;
 }
 
+pub trait ValTree<I: Interner<ValTree = Self>>: Copy + Debug + Hash + Eq {
+    // This isnt' `IntoKind` because then we can't return a reference
```
Comment (lcnr) [inline compiler/rustc_type_ir/src/inherent.rs:297]: add a FIXME that we don't need this once we properly intern instead of using `Box<[_]>`

File: compiler/rustc_middle/src/ty/structural_impls.rs [hunk 25]
```diff
@@ -697,6 +697,29 @@ impl<'tcx> TypeSuperVisitable<TyCtxt<'tcx>> for ty::Const<'tcx> {
...
+        folder: &mut F,
+    ) -> Result<Self, F::Error> {
+        let inner: &ty::ValTreeKind<TyCtxt<'tcx>> = &*self;
+        let valtree = folder.cx().intern_valtree(inner.clone().try_fold_with(folder)?);
+        Ok(valtree)
+    }
+
+    fn fold_with<F: TypeFolder<TyCtxt<'tcx>>>(self, folder: &mut F) -> Self {
+        let inner: &ty::ValTreeKind<TyCtxt<'tcx>> = &*self;
+        folder.cx().intern_valtree(inner.clone().fold_with(folder))
```
Comment (lcnr) [inline compiler/rustc_middle/src/ty/structural_impls.rs]: before reintern, check for eq

File: compiler/rustc_middle/src/ty/structural_impls.rs [hunk 26]
```diff
@@ -697,6 +697,29 @@ impl<'tcx> TypeSuperVisitable<TyCtxt<'tcx>> for ty::Const<'tcx> {
...
+    }
+}
+
+impl<'tcx> TypeFoldable<TyCtxt<'tcx>> for ty::ValTree<'tcx> {
+    fn try_fold_with<F: FallibleTypeFolder<TyCtxt<'tcx>>>(
+        self,
+        folder: &mut F,
+    ) -> Result<Self, F::Error> {
+        let inner: &ty::ValTreeKind<TyCtxt<'tcx>> = &*self;
+        let valtree = folder.cx().intern_valtree(inner.clone().try_fold_with(folder)?);
```
Comment (lcnr) [inline compiler/rustc_middle/src/ty/structural_impls.rs]: also check for eq here

File: compiler/rustc_middle/src/ty/consts/valtree.rs [hunk 27]
```diff
@@ -192,9 +174,14 @@ impl<'tcx> Value<'tcx> {
...
 
-        Some(tcx.arena.alloc_from_iter(
-            self.valtree.unwrap_branch().into_iter().map(|v| v.unwrap_leaf().to_u8()),
-        ))
+        Some(
+            tcx.arena.alloc_from_iter(
+                self.valtree
+                    .unwrap_branch()
+                    .into_iter()
+                    .map(|ct| ct.to_value().valtree.unwrap_leaf().to_u8()),
```
Comment (lcnr) [inline compiler/rustc_middle/src/ty/consts/valtree.rs]: pls add a method to `ty::Const` to get the leaf and use that

File: compiler/rustc_middle/src/ty/consts/valtree.rs [hunk 28]
```diff
@@ -3,74 +3,45 @@ use std::ops::Deref;
...
-    /// ZST types are represented as an empty slice.
-    Branch(Box<[ValTree<'tcx>]>),
-}
-
-impl<'tcx> ValTreeKind<'tcx> {
+#[extension(pub trait ValTreeKindExt<'tcx>)]
+impl<'tcx> ty::ValTreeKind<TyCtxt<'tcx>> {
     #[inline]
-    pub fn unwrap_leaf(&self) -> ScalarInt {
+    fn unwrap_leaf(&self) -> ScalarInt {
```
Comment (lcnr) [inline compiler/rustc_middle/src/ty/consts/valtree.rs]: pls move as many as possible to `rustc_type_ir` instead of adding an extension trait

File: compiler/rustc_hir_analysis/src/hir_ty_lowering/mod.rs [hunk 29]
```diff
@@ -2263,15 +2263,117 @@ impl<'tcx> dyn HirTyLowerer<'tcx> + '_ {
...
+            hir::ConstArgKind::Struct(qpath, inits) => {
+                self.lower_struct_expr_const_arg(hir_id, qpath, inits, const_arg.span())
             }
             hir::ConstArgKind::Anon(anon) => self.lower_anon_const(anon),
             hir::ConstArgKind::Infer(span, ()) => self.ct_infer(None, span),
             hir::ConstArgKind::Error(_, e) => ty::Const::new_error(tcx, e),
         }
     }
 
+    fn lower_struct_expr_const_arg(
```
Comment (lcnr) [inline compiler/rustc_hir_analysis/src/hir_ty_lowering/mod.rs]: `fn lower_const_arg_struct` or `lower_const_arg_expr_struct` idk, sth that's consistent and not ass :>

File: compiler/rustc_hir_analysis/src/hir_ty_lowering/mod.rs [hunk 30]
```diff
@@ -2263,15 +2263,117 @@ impl<'tcx> dyn HirTyLowerer<'tcx> + '_ {
...
+        &self,
+        hir_id: HirId,
+        qpath: hir::QPath<'tcx>,
+        inits: &'tcx [&'tcx hir::ConstArgExprField<'tcx>],
+        span: Span,
+    ) -> Const<'tcx> {
+        let tcx = self.tcx();
+
+        let non_adt_or_variant_res = || {
```
Comment (lcnr) [inline compiler/rustc_hir_analysis/src/hir_ty_lowering/mod.rs:2286]: add `FIXME` that most of this function should be reused with normal struct expr hir lowering

File: compiler/rustc_hir_analysis/src/hir_ty_lowering/mod.rs [hunk 31]
```diff
@@ -2263,15 +2263,117 @@ impl<'tcx> dyn HirTyLowerer<'tcx> + '_ {
...
+        let ty::Adt(adt_def, adt_args) = ty.kind() else { unreachable!() };
+
+        let variant_def = adt_def.variant_with_id(variant_did);
+        let variant_idx = adt_def.variant_index_with_id(variant_did).as_u32();
+
+        let fields = variant_def
+            .fields
+            .iter()
+            .map(|field_def| {
+                // FIXME(mgca): we aren't really handling privacy or stability at all but we should
```
Comment (lcnr) [inline compiler/rustc_hir_analysis/src/hir_ty_lowering/mod.rs]: and macro visibility

File: tests/ui/const-generics/mgca/adt_expr_erroneuous_inits.rs [hunk 32]
```diff
@@ -0,0 +1,23 @@
+#![feature(min_generic_const_args, adt_const_params)]
+#![expect(incomplete_features)]
+#![crate_type = "lib"]
+
+#[derive(Eq, PartialEq, std::marker::ConstParamTy)]
```
Comment (lcnr) [inline tests/ui/const-generics/mgca/adt_expr_erroneuous_inits.rs:8]: comment

File: tests/ui/const-generics/mgca/adt_expr_fields_type_check.rs (hunk 7 above)
Comment (lcnr) [inline tests/ui/const-generics/mgca/adt_expr_fields_type_check.rs]: change to FIXME

File: compiler/rustc_ast_lowering/src/lib.rs (hunk 16 above)
Comment (BoxyUwU) [reply compiler/rustc_ast_lowering/src/lib.rs:2441]: this has been split out to an issue #150062

**Comment by BoxyUwU** [comment]
@bors try @rust-timer queue

perf run with fast path in valtree interning

File: compiler/rustc_hir_analysis/src/hir_ty_lowering/mod.rs (hunk 11 above)
Comment (BoxyUwU) [reply compiler/rustc_hir_analysis/src/hir_ty_lowering/mod.rs]: turns out yes, though just because of One assertion later in the function, though tbh that assertion has been quite useful in the past so I'm inclined to keep it

File: compiler/rustc_resolve/src/def_collector.rs [hunk 33]
```diff
@@ -99,7 +100,10 @@ impl<'a, 'ra, 'tcx> DefCollector<'a, 'ra, 'tcx> {
         }
     }
 
+    #[instrument(level = "debug", skip(self))]
     fn visit_macro_invoc(&mut self, id: NodeId) {
+        debug!(?self.invocation_parent);
+
```
Comment (lcnr) [inline compiler/rustc_resolve/src/def_collector.rs:106]: use `instrument(... fields(invocation_parent = ?sekf.invocation_parent)` or whatever the syntax for that is again?

File: compiler/rustc_hir_analysis/src/hir_ty_lowering/mod.rs (hunk 11 above)
Comment (lcnr) [reply compiler/rustc_hir_analysis/src/hir_ty_lowering/mod.rs]: what is that assert and why do we hit it?

File: compiler/rustc_middle/src/mir/consts.rs [hunk 34]
```diff
@@ -377,14 +366,10 @@ impl<'tcx> Const<'tcx> {
...
-            && cv.ty.is_primitive()
-        {
-            // Avoid the `valtree_to_const_val` query. Can only be done on primitive types that
-            // are valtree leaves, and *not* on references. (References should return the
-            // pointer here, which valtrees don't represent.)
-            Some(cv.valtree.unwrap_leaf().into())
+        if let Const::Ty(_, c) = self {
+            // We don't evaluate anything for type system constants as normalizing
+            // the MIR will handle this for us
+            c.try_to_scalar()
```
Comment (lcnr) [inline compiler/rustc_middle/src/mir/consts.rs:372]: hmm, kinda dislike the change as it adds an implicit invariant that the MIR is already normalized when calling this function, even if that invariant currently holds

File: compiler/rustc_middle/src/ty/structural_impls.rs [hunk 35]
```diff
@@ -697,6 +697,41 @@ impl<'tcx> TypeSuperVisitable<TyCtxt<'tcx>> for ty::Const<'tcx> {
...
+    ) -> Result<Self, F::Error> {
+        let inner: &ty::ValTreeKind<TyCtxt<'tcx>> = &*self;
+        let new_inner = inner.clone().try_fold_with(folder)?;
+
+        if inner == &new_inner {
+            return Ok(self);
+        }
+
+        let valtree = folder.cx().intern_valtree(new_inner);
+        Ok(valtree)
```
Comment (lcnr) [inline compiler/rustc_middle/src/ty/structural_impls.rs]:
```suggestion
        if *inner == new_inner {
            Ok(self);
        } else {
            Ok(folder.cx().intern_valtree(new_inner))
        }
```

File: compiler/rustc_middle/src/ty/structural_impls.rs [hunk 36]
```diff
@@ -697,6 +697,41 @@ impl<'tcx> TypeSuperVisitable<TyCtxt<'tcx>> for ty::Const<'tcx> {
...
+
+    fn fold_with<F: TypeFolder<TyCtxt<'tcx>>>(self, folder: &mut F) -> Self {
+        let inner: &ty::ValTreeKind<TyCtxt<'tcx>> = &*self;
+        let new_inner = inner.clone().fold_with(folder);
+
+        if inner == &new_inner {
+            return self;
+        }
+
+        folder.cx().intern_valtree(new_inner)
```
Comment (lcnr) [inline compiler/rustc_middle/src/ty/structural_impls.rs]: same here

File: compiler/rustc_resolve/src/def_collector.rs [hunk 37]
```diff
@@ -357,39 +367,84 @@ impl<'a, 'ra, 'tcx> visit::Visitor<'a> for DefCollector<'a, 'ra, 'tcx> {
...
-        self.with_parent(parent, |this| visit::walk_anon_const(this, constant));
+        match constant.mgca_disambiguation {
+            // `MgcaDisambiguation::Direct` is set even when MGCA is disabled, so
+            // to avoid affecting stable we have to feature gate the not creating
+            // anon consts
+            _ if !self.resolver.tcx.features().min_generic_const_args() => {
+                let parent =
+                    self.create_def(constant.id, None, DefKind::AnonConst, constant.value.span);
+                self.with_parent(parent, |this| visit::walk_anon_const(this, constant));
+            }
```
Comment (lcnr) [inline compiler/rustc_resolve/src/def_collector.rs]: why in the match instead of just an early return above it?

File: compiler/rustc_resolve/src/def_collector.rs [hunk 38]
```diff
@@ -357,39 +367,84 @@ impl<'a, 'ra, 'tcx> visit::Visitor<'a> for DefCollector<'a, 'ra, 'tcx> {
...
+                    visit::walk_expr(this, expr)
+                });
             }
-            _ => self.invocation_parent.parent_def,
         };
 
-        self.with_parent(parent_def, |this| visit::walk_expr(this, expr))
+        self.with_const_arg(ConstArgContext::NonDirect, |this| {
+            this.with_parent(parent_def, |this| visit::walk_expr(this, expr))
+        })
```
Comment (lcnr) [inline compiler/rustc_resolve/src/def_collector.rs:443]: move and duplicate this into the branches which return and evoid explicit returns in all others? there's literally one branch which doesn't return rn?

File: src/librustdoc/clean/mod.rs [hunk 39]
```diff
@@ -319,6 +319,9 @@ pub(crate) fn clean_const<'tcx>(constant: &hir::ConstArg<'tcx>) -> ConstantKind
         hir::ConstArgKind::Path(qpath) => {
             ConstantKind::Path { path: qpath_to_string(qpath).into() }
         }
+        hir::ConstArgKind::Struct(..) => {
+            ConstantKind::Path { path: "/* STRUCT EXPR */".to_string().into() }
```
Comment (lcnr) [inline src/librustdoc/clean/mod.rs:324]: FIXME?

**Review by lcnr — COMMENTED** [review]
some more nits

*[View changes since this review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/rust/149114/f794a08738958bbef01c3dcab34ec21d3da1e51a..092187d12c1e2e6d1bd5aa1dc3c90fdd514d679a)*

File: compiler/rustc_middle/src/mir/consts.rs (hunk 34 above)
Comment (BoxyUwU) [reply compiler/rustc_middle/src/mir/consts.rs:372]: I think we already rely on this in other places, e.g. `mir::Const::eval` doesn't actually normalize `Const::Ty`. It seems fine/expected to me to rely on the MIR being normalized :thinking:

Comment (BoxyUwU) [reply compiler/rustc_middle/src/mir/consts.rs:372]: this also just isn't meaningfully different from the previous logic. the code did not normalize before this change either (i.e. ive not added a new invariant here). it's just more concise now

Comment (BoxyUwU) [reply compiler/rustc_middle/src/mir/consts.rs:372]: ah I guess we'd ICE now :thinking:

Comment (BoxyUwU) [reply compiler/rustc_middle/src/mir/consts.rs:372]: yh this change is just wrong xd will update this

Comment (BoxyUwU) [reply compiler/rustc_middle/src/mir/consts.rs:372]: ah or, not wrong becuse its `try_to_scalar` :thinking: i see what u mean. i do kinda prefer this how it is. we already rely on the MIR being normalized though so I don't think it makes sense to try avoid relying on it

Comment (BoxyUwU) [reply compiler/rustc_middle/src/mir/consts.rs:372]: ah nvm. yeah this is fucntionally the same and doesnt introduce a new invariant. `eval` does not normalize `Ty` consts

File: compiler/rustc_hir_analysis/src/hir_ty_lowering/mod.rs (hunk 11 above)
Comment (BoxyUwU) [reply compiler/rustc_hir_analysis/src/hir_ty_lowering/mod.rs]: we assert that anon consts aren't a wrapper around a usage of a const parameter because it was tricky to get right when we stopped using anon consts for that case

File: src/librustdoc/clean/mod.rs (hunk 39 above)
Comment (BoxyUwU) [reply src/librustdoc/clean/mod.rs:324]: ah true

File: compiler/rustc_resolve/src/def_collector.rs (hunk 33 above)
Comment (BoxyUwU) [reply compiler/rustc_resolve/src/def_collector.rs:106]: that feels more complex than doing the `debug!` here :thinking:  I think also makes the debug logs harder to read because the `instrument` output just winds up as one huge line whereas this is on its own line

File: compiler/rustc_resolve/src/def_collector.rs (hunk 38 above)
Comment (BoxyUwU) [reply compiler/rustc_resolve/src/def_collector.rs:443]: that is indeed nicer but now there's a bunch of duplication across all the branches that could be solved by just returning a `DefId` and sharing the logic :> which is how the code was previously xd

Comment (BoxyUwU) [reply compiler/rustc_resolve/src/def_collector.rs:443]: ive pushed changes to just put this back to how it was originally structured, if u care a lot about how this function should be structured pls submit ur own PR :> i dont wanna spend anymore time doing miscellaneous cleanup of the existing logic here

File: compiler/rustc_hir_typeck/src/lib.rs [hunk 40]
```diff
@@ -115,6 +115,14 @@ fn typeck_with_inspect<'tcx>(
         return tcx.typeck(typeck_root_def_id);
     }
 
+    if tcx.features().min_generic_const_args()
```
Comment (lcnr) [inline compiler/rustc_hir_typeck/src/lib.rs:122]:
```suggestion
    // We can't handle bodies containing generic parameters even though
    // these generic parameters aren't part of its `generics_of` right now.
    //
    // See the FIXME on `check_anon_const_invalid_param_uses`.
    if tcx.features().min_generic_const_args()
```
or sth

File: tests/ui/const-generics/mgca/explicit_anon_consts_literals_hack.rs [hunk 41]
```diff
@@ -1,9 +1,11 @@
-//@ check-pass
-
 // We allow for literals to implicitly be anon consts still regardless
 // of whether a const block is placed around them or not
+//
+// However, we don't allow so for const arguments in field init positions.
+// This is just harder to implement so we did not do so.
+
```
Comment (lcnr) [inline tests/ui/const-generics/mgca/explicit_anon_consts_literals_hack.rs:6]:
```suggestion
```

**Review by lcnr — COMMENTED** [review]
final nits, then r=me

*[View changes since this review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/rust/149114/24139cf844095e574708faf406034dc78cb39143..bf5db6a3042c1665f1278ae08a9581b06c920447)*
