### PR TITLE
Fix autodiff incorrectly applying fat-lto to proc-macro crates 

### LINKED ISSUE #147487: autodiff incorrectly applies fat-lto to proc-macro crate.
std::autodiff requires fat-lto to work (although we intend to support embed-bc in the future).
Since it's an experimental feature, we require users to set -Zautodiff=Enable to be able to use it as well.

A while ago I opened an issue to automatically enable fat-lto if the user sets the autodiff=Enable flag, so users can't forget about it. The [implementation PR](https://github.com/rust-lang/rust/pull/146229) was a nice improvement for most cases. Unfortunately, though, I just noticed that it looks like the implementation had a slightly different effect than desired:

I tried this code:

```bash
cargo init <name>
cd <name>
cargo add faer
 RUSTFLAGS="-Z autodiff=Enable" cargo +enzyme build -r
```

I expected to see this happen: *compiles*

Instead, this happened:
```sh
   Compiling libm v0.2.15
   Compiling proc-macro2 v1.0.101
   Compiling autocfg v1.5.0
   Compiling unicode-ident v1.0.19
   Compiling quote v1.0.41
   Compiling crossbeam-utils v0.8.21
   Compiling bytemuck v1.24.0
   Compiling rand_core v0.6.4
   Compiling cfg-if v1.0.3
   Compiling nano-gemm-codegen v0.1.0
   Compiling rayon-core v1.13.0
   Compiling version_check v0.9.5
   Compiling libc v0.2.176
   Compiling reborrow v0.5.5
   Compiling either v1.15.0
   Compiling dyn-stack-macros v0.1.0
   Compiling paste v1.0.15
   Compiling bitflags v2.9.4
   Compiling zerocopy v0.8.27
error: lto cannot be used for `proc-macro` crate type without `-Zdylib-lto`

error: could not compile `dyn-stack-macros` (lib) due to 1 previous error
```

The same example used to compile though, if we revert the PR and manually set "lto=fat" in our Cargo.toml.
So apparently the PR enforces fat-lto for slightly more than the equivalent Cargo.toml setting? It would be good if we could match it and not try to fat-lto proc-macro crates.

cc @Hayden602 and @helldawg in case you want to look into this follow-up issue.

</p>
</details>

### PR DESCRIPTION
**Pull request by osamakader**
Fixes rust-lang/rust#147487

### CODE REVIEW

**Comment by petrochenkov** [comment]
r=me after fixing up the commit message https://github.com/rust-lang/rust/pull/147792#issuecomment-3412952008.
@bors rollup
@rustbot author

File: compiler/rustc_session/src/session.rs [hunk 1]
```diff
@@ -604,7 +604,10 @@ impl Session {
         // fat-lto is the easiest solution to this requirement, but quite expensive.
         // FIXME(autodiff): Make autodiff also work with embed-bc instead of fat-lto.
         if self.opts.autodiff_enabled() {
-            return config::Lto::Fat;
+            // Don't apply fat-lto to proc-macro crates as they cannot use fat-lto without -Zdylib-lto
+            if !self.opts.crate_types.contains(&CrateType::ProcMacro) {
```
Comment (petrochenkov) [inline compiler/rustc_session/src/session.rs]: Also, the two `if`s can be collapsed together.

**Comment by ZuseZ4** [comment]
This unfortunately didn't fix the case I posted in the tracking issue, so I reopened it.
But I also ran into this new error when I tried to fix it myself, and I think it's a step in the right direction.
```
 RUSTFLAGS="-Z autodiff=Enable,LooseTypes" cargo +enzyme build       
 Compiling proc-macro2 v1.0.101
   Compiling libm v0.2.15
   Compiling autocfg v1.5.0
   Compiling unicode-ident v1.0.19
   Compiling quote v1.0.41
   Compiling crossbeam-utils v0.8.21
   Compiling rand_core v0.6.4
   Compiling bytemuck v1.24.0
   Compiling cfg-if v1.0.3
   Compiling nano-gemm-codegen v0.1.0
   Compiling rayon-core v1.13.0
   Compiling version_check v0.9.5
   Compiling libc v0.2.176
   Compiling either v1.15.0
   Compiling reborrow v0.5.5
   Compiling dyn-stack-macros v0.1.0
   Compiling bitflags v2.9.4
   Compiling paste v1.0.15
   Compiling memchr v2.7.6
   Compiling rand v0.8.5
   Compiling raw-cpuid v11.6.0
   Compiling dyn-stack v0.13.2
   Compiling getrandom v0.3.3
   Compiling pulp v0.21.5
   Compiling once_cell v1.21.3
   Compiling num-traits v0.2.19
error: failed to get bitcode from object file for LTO (Can't find section .llvmbc)

error: could not compile `pulp` (build script) due to 1 previous error
warning: build failed, waiting for other jobs to finish...
error: could not compile `num-traits` (build script) due to 1 previous error
```
