### PR TITLE
Fix Ord, Eq and Hash implementation of panic::Location

### LINKED ISSUE #144486: `panic::Location` ordering is defined by pointer ordering, not string ordering
Based upon the definition here:

```rust
pub struct Location<'a> {
    // A raw pointer is used rather than a reference because the pointer is valid for one more byte
    // than the length stored in this pointer; the additional byte is the NUL-terminator used by
    // `Location::file_with_nul`.
    filename: NonNull<str>,
    line: u32,
    col: u32,
    _filename: PhantomData<&'a str>,
}
```

This has a derived `Ord` (and subtraits) impl, which means it uses the `Ord` (and subtraits) impl for `NonNull<str>` instead of `str`, which uses pointer-based ordering. This feels incorrect, and I noticed it when trying to make its ordering impls const. The utility of making the ordering const is questionable, but regardless, this feels like an incorrect impl.

I'm filing this as an issue since this feels like it deserves a proper libs decision on whether this ordering should be preserved, or updated to be correct. Plus, maybe a crater run to ensure nobody cares about the fact that it uses pointer-ordering instead of string-ordering.

For the `PartialEq` impl, this doesn't matter because the location string is the same for each file, but for `Ord`, it definitely does matter.

### PR DESCRIPTION
**Pull request by orlp**
Fixes https://github.com/rust-lang/rust/issues/144486.

Now properly compares/hashes the filename rather than the pointer to the string.

### CODE REVIEW

File: library/core/src/panic/location.rs [hunk 1]
```diff
@@ -44,6 +46,42 @@ pub struct Location<'a> {
     _filename: PhantomData<&'a str>,
 }
 
+#[stable(feature = "panic_hooks", since = "1.10.0")]
+impl PartialEq for Location<'_> {
+    fn eq(&self, other: &Self) -> bool {
+        self.file() == other.file() && self.line == other.line && self.col == other.col
```
Comment (Mark-Simulacrum) [inline library/core/src/panic/location.rs]: Is it worth flipping the order here? Comparing the filename is expensive, but in 99% of cases the line + column will mismatch on different locations I'd guess.

File: library/core/src/panic/location.rs [hunk 2]
```diff
@@ -44,6 +46,42 @@ pub struct Location<'a> {
...
+
+#[stable(feature = "panic_hooks", since = "1.10.0")]
+impl Hash for Location<'_> {
+    fn hash<H: Hasher>(&self, state: &mut H) {
+        self.file().hash(state);
+        self.line.hash(state);
+        self.col.hash(state);
+    }
+}
+
```
Comment (Mark-Simulacrum) [inline library/core/src/panic/location.rs:86]: Can you add some test coverage for these? That would help prevent future accidental regressions.

File: library/core/src/panic/location.rs (hunk 1 above)
Comment (orlp) [reply library/core/src/panic/location.rs]: I think that's fair enough for equality. What about the ordering? You could apply the same efficiency argument there although I think people would expect the ordering to be the filename > line > col.

EDIT: after double-checking the documentation, it very clearly states filename > line > col for both ordering and equality. However since that order isn't observable for equality I'll change this for efficiency.

File: library/core/src/panic/location.rs (hunk 2 above)
Comment (orlp) [reply library/core/src/panic/location.rs:86]: I'm actually not 100% sure if I can? In what little tests I've written for the standard library it's been single-file-per-test.

Comment (clarfonthey) [reply library/core/src/panic/location.rs:86]: You should be able to easily add some tests into `library/coretests` somewhere, I believe. Although you will need to have some sort of perma-unstable method to construct these that's marked `#[doc(hidden)]`, since these are private fields.

Comment (tgross35) [reply library/core/src/panic/location.rs:86]: `Location::internal_constructor` does just that :) and there is an existing test file at `library/coretests/tests/panic/location.rs`

Comment (clarfonthey) [reply library/core/src/panic/location.rs:86]: It appears that the function you're referencing no longer exists and was removed when the file was converted to a non-null pointer instead of a real string. Specifically here: b541f93

Comment (tgross35) [reply library/core/src/panic/location.rs:86]: Interesting; I guess it could be brought back as a function taking a `&CStr`.

**Comment by Mark-Simulacrum** [comment]
https://github.com/rust-lang/rust/pull/142708 landed in 1.90 and I think that's what introduced the bug, so presuming this doesn't land by ~Friday we should backport it to future beta. Not nominating yet since it'll cause confusion until we actually branch.

File: library/core/src/panic/location.rs (hunk 2 above)
Comment (orlp) [reply library/core/src/panic/location.rs:86]: I've added tests now using some extra helper modules in separate files, so the tests can remain integration rather than needing specific test-only hidden constructors.

**Comment by ibraheemdev** [comment]
Thanks for the fix. @bors r+ rollup

**Comment by tgross35** [comment]
squash?

**Comment by orlp** [comment]
@ibraheemdev Done.
