### PR TITLE
Silence knock-down errors on `[type error]` bindings

### LINKED ISSUE #56036: Confusing interaction between deref coercion and unknown type
I wrote something like the following code:

```
// fn function_that_doesnt_exist() -> String {
//    String::new()
// }

fn test(s: &str) {
    println!("{}", s);
}

fn test2(s: String) {
    println!("{}", s);
}

fn main() {
    let s = function_that_doesnt_exist();
    test(&s);
    test2(s);
}
```

https://play.rust-lang.org/?version=stable&mode=debug&edition=2015&gist=4be367b5c1d5a1d3d6eb20001c171825

Notice that the actual error is the missing `function_that_doesnt_exist`, but the compiler confusingly reports errors about `str` not having a size known at compile time, presumably because it infers the type of `s` as `str`. When I was writing this code, I missed the message about the missing function, so I was left scratching my head for a bit. It might be nice to silence such errors when the type of the variable is unknowable.

### LINKED ISSUE #76589: Compiler guesses incorrect type after error occurs
The following code:

```rust
fn main() {
    let a = String::missing_method();
    let b: &str = &a;
    let c: String = a;
}
```

prints the following error messages:

```
error[E0599]: no function or associated item named `missing_method` found for struct `std::string::String` in the current scope
 --> src/main.rs:2:21
  |
2 |     let a = String::missing_method();
  |                     ^^^^^^^^^^^^^^ function or associated item not found in `std::string::String`

error[E0308]: mismatched types
 --> src/main.rs:4:21
  |
4 |     let c: String = a;
  |            ------   ^
  |            |        |
  |            |        expected struct `std::string::String`, found `str`
  |            |        help: try using a conversion method: `a.to_string()`
  |            expected due to this

error: aborting due to 2 previous errors
```

The compiler appears to have inferred the type of `a` to be `str`, based on the statement `let b: &str = &a`. However, this is almost certainly the wrong thing to do. The fact that an error occurred while type-checking the initial declaration means that we cannot be sure of what type the user intended to use. In this case, unifying `&str` with `&a` produces an incorrect type of `a`, since a deref coercion will likely be involved in the corrected code (e.g. if the user writes `let a = String::new()`).

We should be more cautious about inferring the types of locals when an error has occurred. If we are certain that no coercions can be occurring (e.g. passing `a` to a function that takes a `String` parameter), then continuing on to infer the variable's type should be fine.

### PR DESCRIPTION
**Pull request by estebank**
Fix #56036, fix #76589.

### CODE REVIEW

File: src/test/ui/suggestions/issue-104287.rs [hunk 1]
```diff
@@ -1,9 +1,13 @@
 // The purpose of this test is not to validate the output of the compiler.
 // Instead, it ensures the suggestion is generated without performing an arithmetic overflow.
 
+struct S;
```
Comment (compiler-errors) [inline src/test/ui/suggestions/issue-104287.rs:4]: Why did you change this UI test? I think the UI test was added specifically to check for an ICE that resulted specifically from this combination of resolver errors.

Comment (estebank) [reply src/test/ui/suggestions/issue-104287.rs:4]: Because the error that produced the ICE would no longer emit with the correct propagation of `[type error]`. The relevant part seemed to be the error that I kept.

Comment (compiler-errors) [reply src/test/ui/suggestions/issue-104287.rs:4]: Hm, I'm not sure if this modified UI test is "faithful" to the ICE anymore, either, though. I'm tempted to leave it as-is even if the error output turns into basically nothing. Either that, or we should just yeet this test completely.. 

I guess I don't care strongly any way.

**Comment by compiler-errors** [comment]
r=me
