### PR TITLE
const validation: properly ignore zero-sized UnsafeCell

### LINKED ISSUE #142948: `{UnsafeCell,Cell}::from_mut` on `&mut [T; 0]` then unsize-coerced in consteval reports UB in safe code
This code makes the compiler report undefined behavior in safe code during consteval.

```rust
use std::cell::UnsafeCell;
const X: &mut UnsafeCell<[i32]> = UnsafeCell::from_mut(&mut []);
```

```
error[E0080]: constructing invalid value at .<deref>: encountered `UnsafeCell` in read-only memory
 --> src/lib.rs:2:1
  |
2 | const X: &mut UnsafeCell<[i32]> = UnsafeCell::from_mut(&mut []);
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ it is undefined behavior to use this value
  |
  = note: The rules on what exactly is undefined behavior aren't clear, so this check might be overzealous. Please open an issue on the rustc repository if you believe it should not be considered undefined behavior.
  = note: the raw bytes of the constant (size: 16, align: 8) {
              ╾───────alloc3────────╼ 00 00 00 00 00 00 00 00 │ ╾──────╼........
          }

For more information about this error, try `rustc --explain E0080`.
error: could not compile `playground` (lib) due to 1 previous error
```

`UnsafeCell::from_mut` has been stable in const since 1.84.0. The similar `Cell::from_mut` is about to be stabilized in const in 1.88.0, which is in a couple days. Using `Cell` instead of `UnsafeCell` results in a similar error.

<details>
<summary>Code using Cell</summary>

```rust
use std::cell::Cell;
const X: &Cell<[i32]> = Cell::from_mut(&mut []);
```

```
error[E0080]: constructing invalid value at .<deref>.value: encountered `UnsafeCell` in read-only memory
 --> src/lib.rs:2:1
  |
2 | const X: &Cell<[i32]> = Cell::from_mut(&mut []);
  | ^^^^^^^^^^^^^^^^^^^^^ it is undefined behavior to use this value
  |
  = note: The rules on what exactly is undefined behavior aren't clear, so this check might be overzealous. Please open an issue on the rustc repository if you believe it should not be considered undefined behavior.
  = note: the raw bytes of the constant (size: 16, align: 8) {
              ╾───────alloc3────────╼ 00 00 00 00 00 00 00 00 │ ╾──────╼........
          }

For more information about this error, try `rustc --explain E0080`.
error: could not compile `playground` (lib) due to 1 previous error
```

</details>

Note that this issue only happens if there's an unsize coercion from `[T; 0]` to `[T]`. That is, the following code compiles fine:

```rust
use std::cell::UnsafeCell;
const X: &mut UnsafeCell<[i32; 0]> = UnsafeCell::from_mut(&mut []);
```

Note that storing a `&mut` in a const in safe code is only possible on empty arrays. See #140126.

### Meta

Reproducible on the playground with `1.90.0-nightly (2025-06-23 706f244db581212cabf2)`

@rustbot labels +A-const-eval +I-unsound

### PR DESCRIPTION
**Pull request by RalfJung**
Fixes https://github.com/rust-lang/rust/issues/142948
r? @oli-obk

### CODE REVIEW

File: compiler/rustc_const_eval/src/interpret/validity.rs [hunk 1]
```diff
@@ -1086,8 +1086,13 @@ impl<'rt, 'tcx, M: Machine<'tcx>> ValueVisitor<'tcx, M> for ValidityVisitor<'rt,
...
         // Special check for CTFE validation, preventing `UnsafeCell` inside unions in immutable memory.
         if self.ctfe_mode.is_some_and(|c| !c.allow_immutable_unsafe_cell()) {
-            if !val.layout.is_zst() && !val.layout.ty.is_freeze(*self.ecx.tcx, self.ecx.typing_env)
-            {
+            // Unsized unions are currently not a thing, but let's keep this code consistent with
+            // the check in `visit_value`.
+            let zst = self
+                .ecx
+                .size_and_align_of(&val.meta(), &val.layout)?
+                .is_some_and(|(s, _a)| s.bytes() == 0);
```
Comment (lcnr) [inline compiler/rustc_const_eval/src/interpret/validity.rs]: ~~this seems very footgunny, why do `is_zst` and `size_and_align_of(&val.meta(), &val.layout).is_some_and(|(s, _a)| s.bytes() == 0)` differ. When is using `is_zst` actually correct?~~

Okay, this is because we're not checking whether the type itself is a ZST, but that the value is a zero-sized. So we don't use `is_zst` to also handle slices and trait objects. Can you add this as a comment to the code in `visit_value`?

after that r=me

Comment (RalfJung) [reply compiler/rustc_const_eval/src/interpret/validity.rs]: > When is using is_zst actually correct?

Basically this is `must_be_zst`, but it can miss types that are only dynamically zero-sized.

**Comment by RalfJung** [comment]
I also added a 2nd commit making the size_and_align_of APIs in the interpreter a bit nicer.
