### PR TITLE
Avoid another gha group nesting

### LINKED ISSUE #113798: x test error_index_generator triggers 'nested groups are not supported by GHA' check
### Command

```
x test error_index_generator
```

### Output

```
Testing stage1 error-index (x86_64-unknown-linux-gnu)
Building tool rustdoc (stage0 -> stage1, x86_64-unknown-linux-gnu)
thread 'main' panicked at 'nested groups are not supported by GHA!', tool.rs:486:30
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

This is a regression from https://github.com/rust-lang/rust/pull/113514.

### PR DESCRIPTION
**Pull request by oli-obk**
fixes https://github.com/rust-lang/rust/issues/113798 (`x test error_index_generator` did not work locally anymore)

r? @jyn514

### CODE REVIEW

File: src/bootstrap/test.rs [hunk 1]
```diff
@@ -2087,13 +2087,15 @@ impl Step for ErrorIndex {
...
-        // available.
-        builder.ensure(compile::Std::new(compiler, compiler.host));
+        {
+            let _guard =
+                builder.msg(Kind::Test, compiler.stage, "error-index", compiler.host, compiler.host);
+            let _time = util::timeit(&builder);
+            builder.run_quiet(&mut tool);
+            // The tests themselves need to link to std, so make sure it is
+            // available.
+            builder.ensure(compile::Std::new(compiler, compiler.host));
```
Comment (jyn514) [inline src/bootstrap/test.rs:2097]: this needs to be moved out of the block to avoid nesting it

(probably it didn't panic because this is only relevant when cross-compiling? i'd expect x t error--index-generator --target i686 to break though.)

**Review by jyn514 — APPROVED** [review]
this seems good other than my one comment 👍 I've been using explicit drop() for the guards and it would be nice to settle on one style but I don't feel strongly on which it should be

**Comment by jyn514** [comment]
i won't have time to look at this for a while. r=me unless you want to make more changes.

r? bootstrap
