### PR TITLE
Change E0451 to output proper indices for tuple-struct fields.

### LINKED ISSUE #31706: Nitpicking: visibility errors on a tuple struct count fields from 1 when the language counts them from 0
```rust
mod m {
    pub struct S(i32);
    pub const K: S = S(0);
}

fn main() {
    0 == m::K.0;
}
```

```
<anon>:7:10: 7:16 error: field #1 of struct `m::S` is private [E0451]
<anon>:7     0 == m::K.0;
                  ^~~~~~
<anon>:7:10: 7:16 help: see the detailed explanation for E0451
```

- https://play.rust-lang.org/?gist=d090346cd5446b09a7d4&version=nightly

### PR DESCRIPTION
**Pull request by rphmeier**
Fixes #31706

Also fixes a phrasing error in the diagnostic.

### CODE REVIEW

**Comment by Manishearth** [comment]
Huh, this is interesting; pretty ambivalent about this. On one hand I see the dissonance between this and the tuple access syntax, on the other hand English. Hm.

**Comment by Manishearth** [comment]
@bors r+ rollup

thought a bit more about this. As long as it isn't saying "zeroeth" and "first" it should be fine.

thanks!

File: src/librustc_privacy/lib.rs [hunk 1]
```diff
@@ -710,7 +710,7 @@ impl<'a, 'tcx> PrivacyVisitor<'a, 'tcx> {
             NamedField(name) => format!("field `{}` of {} is private",
                                         name, struct_desc),
             UnnamedField(idx) => format!("field #{} of {} is private",
```
Comment (nrc) [inline src/librustc_privacy/lib.rs]: This use of `#` always irks me - is it an american thing? I thought using '#' for 'number' went out of fashion in about 1900. The error message would be just as good without the '#', IMO.

Comment (nrc) [inline src/librustc_privacy/lib.rs]: More so when describing the fields as 0-indexed

Comment (rphmeier) [inline src/librustc_privacy/lib.rs]: I'm inclined to agree about the error message itself -- it would probably look nicer just as "field `X` of Y is private". I figure that such a change would be better in another PR, but I could add it to this one.

Comment (nrc) [inline src/librustc_privacy/lib.rs]: Another PR is fine
