### PR TITLE
remove the usize field from CandidateSource::AliasBound

### LINKED ISSUE #107380: remove the `usize` field from `CandidateSource::AliasBound`
The field is currently unused and can be incorrect due to the way the new solver deals with projections

https://github.com/rust-lang/rust/blob/7919ef0ec5776c72dace7fec1c68551a617505ad/compiler/rustc_trait_selection/src/solve/assembly.rs#L79

https://github.com/rust-lang/rust/blob/7919ef0ec5776c72dace7fec1c68551a617505ad/compiler/rustc_trait_selection/src/solve/assembly.rs#L220-L221

### PR DESCRIPTION
**Pull request by lenko-d**
Fixes [#107380](https://github.com/rust-lang/rust/issues/107380)

### CODE REVIEW

File: compiler/rustc_trait_selection/src/solve/assembly.rs [hunk 1]
```diff
@@ -76,7 +76,7 @@ pub(super) enum CandidateSource {
     ///     let _y = x.clone();
     /// }
     /// ```
-    AliasBound(usize),
+    AliasBound(),
```
Comment (eggyal) [inline compiler/rustc_trait_selection/src/solve/assembly.rs:79]: Rather than a tuple variant with no fields, it'd be more idiomatic for this to be a plain field-less variant (ie omit the brackets).

**Review by eggyal — CHANGES_REQUESTED** [review]

File: compiler/rustc_trait_selection/src/solve/assembly.rs [hunk 2]
```diff
@@ -342,15 +340,15 @@ impl<'tcx> EvalCtxt<'_, 'tcx> {
             ty::Alias(_, alias_ty) => alias_ty,
         };
 
-        for (i, (assumption, _)) in self
+        for (_, (assumption, _)) in self
             .tcx()
             .bound_explicit_item_bounds(alias_ty.def_id)
             .subst_iter_copied(self.tcx(), alias_ty.substs)
             .enumerate()
```
Comment (eggyal) [inline compiler/rustc_trait_selection/src/solve/assembly.rs:347]: Here you can drop the `.enumerate()` in order to iterate over `(assumption, _)` without pairing the (no longer used) index to the iterator.

**Review by eggyal — CHANGES_REQUESTED** [review]

**Review by eggyal — APPROVED** [review]

File: compiler/rustc_trait_selection/src/solve/assembly.rs [hunk 3]
```diff
@@ -76,7 +76,7 @@ pub(super) enum CandidateSource {
     ///     let _y = x.clone();
     /// }
     /// ```
-    AliasBound(usize),
+    AliasBound,
```
Comment (lcnr) [inline compiler/rustc_trait_selection/src/solve/assembly.rs:79]: still referring to "the `n-th` bound in the `item_bounds`" in the doc comment
