### PR TITLE
Make crashes dump mir to build dir

### LINKED ISSUE #125029: tests/crashes/124436.rs is creating a `mir_dump` directory in the repo root, not the build directory
https://github.com/rust-lang/rust/pull/124775 added some tests, and one of them is creating a `mir_dump` directory in the repo root, where it really shouldn't. Surely we have ways of dumping MIR to other directories for the mir-opt tests, right?

@matthiaskrgr

### PR DESCRIPTION
**Pull request by compiler-errors**
Set `-Zdump-mir-dir` for `crashes`-style tests.

Alternatively, we just remove `tests/crashes/124436.rs`, since if the only way to get it to repro is via `-Zdump-mir`, then maybe it's not worth it to fix.

Fixes #125029

### CODE REVIEW

File: src/tools/compiletest/src/runtest.rs [hunk 1]
```diff
@@ -2560,8 +2560,15 @@ impl<'test> TestCx<'test> {
             Assembly | Codegen => {
                 rustc.arg("-Cdebug-assertions=no");
             }
+            Crashes => {
+                let mir_dump_dir = self.get_mir_dump_dir();
+                remove_and_create_dir_all(&mir_dump_dir);
+                let mut dir_opt = "-Zdump-mir-dir=".to_string();
+                dir_opt.push_str(mir_dump_dir.to_str().unwrap());
+                rustc.arg(dir_opt);
```
Comment (saethlin) [inline src/tools/compiletest/src/runtest.rs:2568]: I wouldn't mind some abstraction. Could we even just stuff this in a closure and call it on both arms that need this?
