### PR TITLE
Fix `emit_unused_delims_expr` ICE

### LINKED ISSUE #104392: ice: "Span must not be empty and have no suggestion"
### Code
Needs debug assertions
```Rust
fn main() {
    { unsafe 92 }
}
```

### Meta

`rustc --version --verbose`:
```
commit 3be81dd0cedef3c83fba7047857418633708890f (origin/master, origin/HEAD)
Merge: 229e875878a ba46b683736
Author: bors <bors@rust-lang.org>
Date:   Sun Nov 13 06:23:18 2022 +0000

    Auto merge of #104282 - cjgillot:intern-span, r=compiler-errors

    Hash spans when interning types

    Ignoring hash for spans creates an inconsistency between the `Hash` impl for `WithStableHash`, which takes them into account, and the `HashStable` impl which does not.

    cc `@compiler-errors`

    Fixes https://github.com/rust-lang/rust/issues/104271
    Fixes https://github.com/rust-lang/rust/issues/104255
    Fixes https://github.com/rust-lang/rust/issues/104238
```

### Error output

```
<output>
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
error: expected `{`, found `92`
 --> ./rust-analyzer/crates/parser/test_data/parser/err/0042_weird_blocks.rs:2:14
  |
2 |     { unsafe 92 }
  |       ------ ^^ expected `{`
  |       |
  |       while parsing this `unsafe` expression
  |
help: try placing this code inside a block
  |
2 |     { unsafe { 92 } }
  |              +    +

thread 'rustc' panicked at 'Span must not be empty and have no suggestion', /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_errors/src/diagnostic.rs:624:9
stack backtrace:
   0:     0x7f53888ebe6e - std::backtrace_rs::backtrace::libunwind::trace::h2eba450607c8505f
                               at /home/matthias/vcs/github/rust_debug_assertions/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   1:     0x7f53888ebe6e - std::backtrace_rs::backtrace::trace_unsynchronized::h807100070af02067
                               at /home/matthias/vcs/github/rust_debug_assertions/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7f53888ebe6e - std::sys_common::backtrace::_print_fmt::hb7560753851ac705
                               at /home/matthias/vcs/github/rust_debug_assertions/library/std/src/sys_common/backtrace.rs:65:5
   3:     0x7f53888ebe6e - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hbd9919f0d0dab500
                               at /home/matthias/vcs/github/rust_debug_assertions/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x7f538896a128 - core::fmt::write::h6dd0aa79d810b449
                               at /home/matthias/vcs/github/rust_debug_assertions/library/core/src/fmt/mod.rs:1209:17
   5:     0x7f53888bac4f - std::io::Write::write_fmt::hfd60031a8e080dfa
                               at /home/matthias/vcs/github/rust_debug_assertions/library/std/src/io/mod.rs:1682:15
   6:     0x7f53888ebc65 - std::sys_common::backtrace::_print::hd608f7bedb66f36d
                               at /home/matthias/vcs/github/rust_debug_assertions/library/std/src/sys_common/backtrace.rs:47:5
   7:     0x7f53888ebc65 - std::sys_common::backtrace::print::h860e7f8950ec5f10
                               at /home/matthias/vcs/github/rust_debug_assertions/library/std/src/sys_common/backtrace.rs:34:9
   8:     0x7f53888c1d94 - std::panicking::default_hook::{{closure}}::hcbdc2c60ca06f4de
   9:     0x7f53888c19fe - std::panicking::default_hook::h6a3c0b6519439000
                               at /home/matthias/vcs/github/rust_debug_assertions/library/std/src/panicking.rs:286:9
  10:     0x7f538970d1d2 - <alloc[55cbc4dc069182d1]::boxed::Box<dyn for<'a, 'b> core[6b044a951f062b59]::ops::function::Fn<(&'a core[6b044a951f062b59]::panic::panic_info::PanicInfo<'b>,), Output = ()> + core[6b044a951f062b59]::marker::Send + core[6b044a951f062b59]::marker::Sync> as core[6b044a951f062b59]::ops::function::Fn<(&core[6b044a951f062b59]::panic::panic_info::PanicInfo,)>>::call
                               at /home/matthias/vcs/github/rust_debug_assertions/library/alloc/src/boxed.rs:2024:9
  11:     0x7f538970d1d2 - rustc_driver[804584070814ac7f]::DEFAULT_HOOK::{closure#0}::{closure#0}
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_driver/src/lib.rs:1207:13
  12:     0x7f53888c2477 - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h2f1f731eb522bca3
                               at /home/matthias/vcs/github/rust_debug_assertions/library/alloc/src/boxed.rs:2024:9
  13:     0x7f53888c2477 - std::panicking::rust_panic_with_hook::h89bceab315f7fcd4
                               at /home/matthias/vcs/github/rust_debug_assertions/library/std/src/panicking.rs:692:13
  14:     0x7f53888ec1b1 - std::panicking::begin_panic_handler::{{closure}}::h0d7cacab89b29cb2
                               at /home/matthias/vcs/github/rust_debug_assertions/library/std/src/panicking.rs:577:13
  15:     0x7f53888ebfbe - std::sys_common::backtrace::__rust_end_short_backtrace::h9db04dfc5a3661d7
                               at /home/matthias/vcs/github/rust_debug_assertions/library/std/src/sys_common/backtrace.rs:137:18
  16:     0x7f53888c1f92 - rust_begin_unwind
                               at /home/matthias/vcs/github/rust_debug_assertions/library/std/src/panicking.rs:575:5
  17:     0x7f538887a173 - core::panicking::panic_fmt::h00fdaf7d8f535993
                               at /home/matthias/vcs/github/rust_debug_assertions/library/core/src/panicking.rs:65:14
  18:     0x7f538e6be949 - <rustc_errors[a8b59b4023676711]::diagnostic::Diagnostic>::multipart_suggestion_with_style::<rustc_error_messages[acd37de281c042dc]::SubdiagnosticMessage>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_errors/src/diagnostic.rs:624:9
  19:     0x7f538e63abd8 - <rustc_errors[a8b59b4023676711]::diagnostic::Diagnostic>::multipart_suggestion::<rustc_error_messages[acd37de281c042dc]::SubdiagnosticMessage>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_errors/src/diagnostic.rs:592:9
  20:     0x7f538e63abd8 - <rustc_errors[a8b59b4023676711]::diagnostic_builder::DiagnosticBuilder<()>>::multipart_suggestion::<rustc_error_messages[acd37de281c042dc]::SubdiagnosticMessage>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_errors/src/diagnostic_builder.rs:376:13
  21:     0x7f538e63abd8 - <rustc_lint[798cc8cfe34c1960]::unused::UnusedBraces as rustc_lint[798cc8cfe34c1960]::unused::UnusedDelimLint>::emit_unused_delims::{closure#0}
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_lint/src/unused.rs:602:17
  22:     0x7f538e63abd8 - <<rustc_lint[798cc8cfe34c1960]::unused::UnusedBraces as rustc_lint[798cc8cfe34c1960]::unused::UnusedDelimLint>::emit_unused_delims::{closure#0} as core[6b044a951f062b59]::ops::function::FnOnce<(&mut rustc_errors[a8b59b4023676711]::diagnostic_builder::DiagnosticBuilder<()>,)>>::call_once::{shim:vtable#0}
                               at /home/matthias/vcs/github/rust_debug_assertions/library/core/src/ops/function.rs:424:5
  23:     0x7f538e627bea - <alloc[55cbc4dc069182d1]::boxed::Box<dyn for<'a, 'b> core[6b044a951f062b59]::ops::function::FnOnce<(&'a mut rustc_errors[a8b59b4023676711]::diagnostic_builder::DiagnosticBuilder<'b, ()>,), Output = &'a mut rustc_errors[a8b59b4023676711]::diagnostic_builder::DiagnosticBuilder<'b, ()>>> as core[6b044a951f062b59]::ops::function::FnOnce<(&mut rustc_errors[a8b59b4023676711]::diagnostic_builder::DiagnosticBuilder<()>,)>>::call_once
                               at /home/matthias/vcs/github/rust_debug_assertions/library/alloc/src/boxed.rs:1990:9
  24:     0x7f538e627bea - rustc_middle[b2dac501715e078e]::lint::struct_lint_level::struct_lint_level_impl::<rustc_error_messages[acd37de281c042dc]::DiagnosticMessage>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_middle/src/lint.rs:466:9
  25:     0x7f538e624ba2 - rustc_middle[b2dac501715e078e]::lint::struct_lint_level::<rustc_error_messages[acd37de281c042dc]::DiagnosticMessage, <rustc_lint[798cc8cfe34c1960]::unused::UnusedBraces as rustc_lint[798cc8cfe34c1960]::unused::UnusedDelimLint>::emit_unused_delims::{closure#0}>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_middle/src/lint.rs:470:5
  26:     0x7f538e68e2d9 - <rustc_lint[798cc8cfe34c1960]::levels::LintLevelsBuilder<rustc_lint[798cc8cfe34c1960]::levels::TopDown>>::struct_lint::<rustc_error_messages[acd37de281c042dc]::DiagnosticMessage, <rustc_lint[798cc8cfe34c1960]::unused::UnusedBraces as rustc_lint[798cc8cfe34c1960]::unused::UnusedDelimLint>::emit_unused_delims::{closure#0}>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_lint/src/levels.rs:1087:9
  27:     0x7f538e61596f - <rustc_lint[798cc8cfe34c1960]::context::EarlyContext as rustc_lint[798cc8cfe34c1960]::context::LintContext>::lookup::<rustc_error_messages[acd37de281c042dc]::MultiSpan, rustc_error_messages[acd37de281c042dc]::DiagnosticMessage, <rustc_lint[798cc8cfe34c1960]::unused::UnusedBraces as rustc_lint[798cc8cfe34c1960]::unused::UnusedDelimLint>::emit_unused_delims::{closure#0}>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_lint/src/context.rs:1050:9
  28:     0x7f538e61596f - <rustc_lint[798cc8cfe34c1960]::context::EarlyContext as rustc_lint[798cc8cfe34c1960]::context::LintContext>::struct_span_lint::<rustc_error_messages[acd37de281c042dc]::MultiSpan, rustc_error_messages[acd37de281c042dc]::DiagnosticMessage, <rustc_lint[798cc8cfe34c1960]::unused::UnusedBraces as rustc_lint[798cc8cfe34c1960]::unused::UnusedDelimLint>::emit_unused_delims::{closure#0}>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_lint/src/context.rs:923:9
  29:     0x7f538e61596f - <rustc_lint[798cc8cfe34c1960]::unused::UnusedBraces as rustc_lint[798cc8cfe34c1960]::unused::UnusedDelimLint>::emit_unused_delims
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_lint/src/unused.rs:580:9
  30:     0x7f538e61596f - <rustc_lint[798cc8cfe34c1960]::unused::UnusedBraces as rustc_lint[798cc8cfe34c1960]::unused::UnusedDelimLint>::emit_unused_delims_expr
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_lint/src/unused.rs:564:9
  31:     0x7f538e617a8b - <rustc_lint[798cc8cfe34c1960]::unused::UnusedBraces as rustc_lint[798cc8cfe34c1960]::unused::UnusedDelimLint>::check_unused_delims_expr
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_lint/src/unused.rs:1021:29
  32:     0x7f538e66265e - <rustc_lint[798cc8cfe34c1960]::unused::UnusedBraces as rustc_lint[798cc8cfe34c1960]::unused::UnusedDelimLint>::check_stmt
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_lint/src/unused.rs:690:17
  33:     0x7f538e66265e - <rustc_lint[798cc8cfe34c1960]::unused::UnusedBraces as rustc_lint[798cc8cfe34c1960]::passes::EarlyLintPass>::check_stmt
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_lint/src/unused.rs:1043:9
  34:     0x7f538e66265e - <rustc_lint[798cc8cfe34c1960]::BuiltinCombinedEarlyLintPass as rustc_lint[798cc8cfe34c1960]::passes::EarlyLintPass>::check_stmt
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_lint/src/passes.rs:205:13
  35:     0x7f538997ebf5 - <rustc_lint[798cc8cfe34c1960]::early::EarlyContextAndPass<rustc_lint[798cc8cfe34c1960]::BuiltinCombinedEarlyLintPass> as rustc_ast[10a597527468fdcd]::visit::Visitor>::visit_stmt::{closure#0}
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_lint/src/early.rs:137:13
  36:     0x7f538997ebf5 - <rustc_lint[798cc8cfe34c1960]::early::EarlyContextAndPass<rustc_lint[798cc8cfe34c1960]::BuiltinCombinedEarlyLintPass>>::with_lint_attrs::<<rustc_lint[798cc8cfe34c1960]::early::EarlyContextAndPass<rustc_lint[798cc8cfe34c1960]::BuiltinCombinedEarlyLintPass> as rustc_ast[10a597527468fdcd]::visit::Visitor>::visit_stmt::{closure#0}>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_lint/src/early.rs:67:9
  37:     0x7f538997ebf5 - <rustc_lint[798cc8cfe34c1960]::early::EarlyContextAndPass<rustc_lint[798cc8cfe34c1960]::BuiltinCombinedEarlyLintPass> as rustc_ast[10a597527468fdcd]::visit::Visitor>::visit_stmt
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_lint/src/early.rs:136:9
  38:     0x7f538992804c - rustc_ast[10a597527468fdcd]::visit::walk_block::<rustc_lint[798cc8cfe34c1960]::early::EarlyContextAndPass<rustc_lint[798cc8cfe34c1960]::BuiltinCombinedEarlyLintPass>>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_ast/src/visit.rs:716:5
  39:     0x7f538992804c - <rustc_lint[798cc8cfe34c1960]::early::EarlyContextAndPass<rustc_lint[798cc8cfe34c1960]::BuiltinCombinedEarlyLintPass> as rustc_ast[10a597527468fdcd]::visit::Visitor>::visit_block
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_lint/src/early.rs:201:9
  40:     0x7f538992804c - rustc_ast[10a597527468fdcd]::visit::walk_fn::<rustc_lint[798cc8cfe34c1960]::early::EarlyContextAndPass<rustc_lint[798cc8cfe34c1960]::BuiltinCombinedEarlyLintPass>>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_ast/src/visit.rs:667:13
  41:     0x7f538992c4ca - <rustc_lint[798cc8cfe34c1960]::early::EarlyContextAndPass<rustc_lint[798cc8cfe34c1960]::BuiltinCombinedEarlyLintPass> as rustc_ast[10a597527468fdcd]::visit::Visitor>::visit_fn
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_lint/src/early.rs:150:9
  42:     0x7f538992c4ca - rustc_ast[10a597527468fdcd]::visit::walk_item::<rustc_lint[798cc8cfe34c1960]::early::EarlyContextAndPass<rustc_lint[798cc8cfe34c1960]::BuiltinCombinedEarlyLintPass>>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_ast/src/visit.rs:312:13
  43:     0x7f538997e4c9 - <rustc_lint[798cc8cfe34c1960]::early::EarlyContextAndPass<rustc_lint[798cc8cfe34c1960]::BuiltinCombinedEarlyLintPass> as rustc_ast[10a597527468fdcd]::visit::Visitor>::visit_item::{closure#0}
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_lint/src/early.rs:85:13
  44:     0x7f538997e4c9 - <rustc_lint[798cc8cfe34c1960]::early::EarlyContextAndPass<rustc_lint[798cc8cfe34c1960]::BuiltinCombinedEarlyLintPass>>::with_lint_attrs::<<rustc_lint[798cc8cfe34c1960]::early::EarlyContextAndPass<rustc_lint[798cc8cfe34c1960]::BuiltinCombinedEarlyLintPass> as rustc_ast[10a597527468fdcd]::visit::Visitor>::visit_item::{closure#0}>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_lint/src/early.rs:67:9
  45:     0x7f538997e4c9 - <rustc_lint[798cc8cfe34c1960]::early::EarlyContextAndPass<rustc_lint[798cc8cfe34c1960]::BuiltinCombinedEarlyLintPass> as rustc_ast[10a597527468fdcd]::visit::Visitor>::visit_item
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_lint/src/early.rs:83:9
  46:     0x7f538992273c - rustc_ast[10a597527468fdcd]::visit::walk_crate::<rustc_lint[798cc8cfe34c1960]::early::EarlyContextAndPass<rustc_lint[798cc8cfe34c1960]::BuiltinCombinedEarlyLintPass>>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_ast/src/visit.rs:263:5
  47:     0x7f5389973d29 - <&rustc_ast[10a597527468fdcd]::ast::Crate as rustc_lint[798cc8cfe34c1960]::early::EarlyCheckNode>::check::<rustc_lint[798cc8cfe34c1960]::BuiltinCombinedEarlyLintPass>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_lint/src/early.rs:347:9
  48:     0x7f5389973d29 - rustc_lint[798cc8cfe34c1960]::early::early_lint_node::<rustc_lint[798cc8cfe34c1960]::BuiltinCombinedEarlyLintPass, &rustc_ast[10a597527468fdcd]::ast::Crate>::{closure#0}
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_lint/src/early.rs:391:66
  49:     0x7f5389973d29 - <rustc_lint[798cc8cfe34c1960]::early::EarlyContextAndPass<rustc_lint[798cc8cfe34c1960]::BuiltinCombinedEarlyLintPass>>::with_lint_attrs::<rustc_lint[798cc8cfe34c1960]::early::early_lint_node<rustc_lint[798cc8cfe34c1960]::BuiltinCombinedEarlyLintPass, &rustc_ast[10a597527468fdcd]::ast::Crate>::{closure#0}>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_lint/src/early.rs:67:9
  50:     0x7f5389973d29 - rustc_lint[798cc8cfe34c1960]::early::early_lint_node::<rustc_lint[798cc8cfe34c1960]::BuiltinCombinedEarlyLintPass, &rustc_ast[10a597527468fdcd]::ast::Crate>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_lint/src/early.rs:391:5
  51:     0x7f5389973d29 - rustc_lint[798cc8cfe34c1960]::early::check_ast_node::<rustc_lint[798cc8cfe34c1960]::BuiltinCombinedEarlyLintPass, &rustc_ast[10a597527468fdcd]::ast::Crate>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_lint/src/early.rs:425:20
  52:     0x7f538988e014 - rustc_interface[31f5dff205b05af]::passes::configure_and_expand::{closure#8}
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_interface/src/passes.rs:448:9
  53:     0x7f538988e014 - <rustc_data_structures[bb7700ba3124b76b]::profiling::VerboseTimingGuard>::run::<(), rustc_interface[31f5dff205b05af]::passes::configure_and_expand::{closure#8}>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_session/src/utils.rs:10:9
  54:     0x7f538988e014 - <rustc_session[7d66d4184c51f11]::session::Session>::time::<(), rustc_interface[31f5dff205b05af]::passes::configure_and_expand::{closure#8}>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_session/src/utils.rs:10:9
  55:     0x7f53898d5f43 - rustc_interface[31f5dff205b05af]::passes::configure_and_expand
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_interface/src/passes.rs:446:5
  56:     0x7f5389952283 - <rustc_interface[31f5dff205b05af]::queries::Queries>::expansion::{closure#0}::{closure#0}
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_interface/src/queries.rs:182:17
  57:     0x7f5389952283 - <rustc_interface[31f5dff205b05af]::passes::boxed_resolver::BoxedResolver>::access::<<rustc_interface[31f5dff205b05af]::queries::Queries>::expansion::{closure#0}::{closure#0}, core[6b044a951f062b59]::result::Result<rustc_ast[10a597527468fdcd]::ast::Crate, rustc_errors[a8b59b4023676711]::ErrorGuaranteed>>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_interface/src/passes.rs:134:13
  58:     0x7f53898a417e - <rustc_interface[31f5dff205b05af]::queries::Queries>::expansion::{closure#0}
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_interface/src/queries.rs:181:25
  59:     0x7f53898a417e - <rustc_interface[31f5dff205b05af]::queries::Query<(alloc[55cbc4dc069182d1]::rc::Rc<rustc_ast[10a597527468fdcd]::ast::Crate>, alloc[55cbc4dc069182d1]::rc::Rc<core[6b044a951f062b59]::cell::RefCell<rustc_interface[31f5dff205b05af]::passes::boxed_resolver::BoxedResolver>>, alloc[55cbc4dc069182d1]::rc::Rc<rustc_lint[798cc8cfe34c1960]::context::LintStore>)>>::compute::<<rustc_interface[31f5dff205b05af]::queries::Queries>::expansion::{closure#0}>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_interface/src/queries.rs:38:28
  60:     0x7f53898a417e - <rustc_interface[31f5dff205b05af]::queries::Queries>::expansion
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_interface/src/queries.rs:170:9
  61:     0x7f53897a7da0 - rustc_driver[804584070814ac7f]::run_compiler::{closure#1}::{closure#2}
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_driver/src/lib.rs:357:13
  62:     0x7f53897a7da0 - <rustc_interface[31f5dff205b05af]::interface::Compiler>::enter::<rustc_driver[804584070814ac7f]::run_compiler::{closure#1}::{closure#2}, core[6b044a951f062b59]::result::Result<core[6b044a951f062b59]::option::Option<rustc_interface[31f5dff205b05af]::queries::Linker>, rustc_errors[a8b59b4023676711]::ErrorGuaranteed>>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_interface/src/queries.rs:381:19
  63:     0x7f538970ed35 - rustc_driver[804584070814ac7f]::run_compiler::{closure#1}
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_driver/src/lib.rs:308:22
  64:     0x7f538970ed35 - rustc_interface[31f5dff205b05af]::interface::run_compiler::<core[6b044a951f062b59]::result::Result<(), rustc_errors[a8b59b4023676711]::ErrorGuaranteed>, rustc_driver[804584070814ac7f]::run_compiler::{closure#1}>::{closure#0}::{closure#1}
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_interface/src/interface.rs:327:21
  65:     0x7f538970ed35 - rustc_span[8a6424ea12543a70]::with_source_map::<core[6b044a951f062b59]::result::Result<(), rustc_errors[a8b59b4023676711]::ErrorGuaranteed>, rustc_interface[31f5dff205b05af]::interface::run_compiler<core[6b044a951f062b59]::result::Result<(), rustc_errors[a8b59b4023676711]::ErrorGuaranteed>, rustc_driver[804584070814ac7f]::run_compiler::{closure#1}>::{closure#0}::{closure#1}>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_span/src/lib.rs:1009:5
  66:     0x7f5389795b8c - rustc_interface[31f5dff205b05af]::interface::run_compiler::<core[6b044a951f062b59]::result::Result<(), rustc_errors[a8b59b4023676711]::ErrorGuaranteed>, rustc_driver[804584070814ac7f]::run_compiler::{closure#1}>::{closure#0}
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_interface/src/interface.rs:321:13
  67:     0x7f5389795b8c - <scoped_tls[4b2a4c8958d0f0a7]::ScopedKey<rustc_span[8a6424ea12543a70]::SessionGlobals>>::set::<rustc_interface[31f5dff205b05af]::interface::run_compiler<core[6b044a951f062b59]::result::Result<(), rustc_errors[a8b59b4023676711]::ErrorGuaranteed>, rustc_driver[804584070814ac7f]::run_compiler::{closure#1}>::{closure#0}, core[6b044a951f062b59]::result::Result<(), rustc_errors[a8b59b4023676711]::ErrorGuaranteed>>
                               at /home/matthias/.cargo/registry/src/github.com-1ecc6299db9ec823/scoped-tls-1.0.0/src/lib.rs:137:9
  68:     0x7f5389791140 - rustc_span[8a6424ea12543a70]::create_session_globals_then::<core[6b044a951f062b59]::result::Result<(), rustc_errors[a8b59b4023676711]::ErrorGuaranteed>, rustc_interface[31f5dff205b05af]::interface::run_compiler<core[6b044a951f062b59]::result::Result<(), rustc_errors[a8b59b4023676711]::ErrorGuaranteed>, rustc_driver[804584070814ac7f]::run_compiler::{closure#1}>::{closure#0}>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_span/src/lib.rs:111:5
  69:     0x7f5389791140 - rustc_interface[31f5dff205b05af]::util::run_in_thread_pool_with_globals::<rustc_interface[31f5dff205b05af]::interface::run_compiler<core[6b044a951f062b59]::result::Result<(), rustc_errors[a8b59b4023676711]::ErrorGuaranteed>, rustc_driver[804584070814ac7f]::run_compiler::{closure#1}>::{closure#0}, core[6b044a951f062b59]::result::Result<(), rustc_errors[a8b59b4023676711]::ErrorGuaranteed>>::{closure#0}::{closure#0}
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_interface/src/util.rs:148:38
  70:     0x7f5389791140 - std[828477b612daf80a]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[31f5dff205b05af]::util::run_in_thread_pool_with_globals<rustc_interface[31f5dff205b05af]::interface::run_compiler<core[6b044a951f062b59]::result::Result<(), rustc_errors[a8b59b4023676711]::ErrorGuaranteed>, rustc_driver[804584070814ac7f]::run_compiler::{closure#1}>::{closure#0}, core[6b044a951f062b59]::result::Result<(), rustc_errors[a8b59b4023676711]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[6b044a951f062b59]::result::Result<(), rustc_errors[a8b59b4023676711]::ErrorGuaranteed>>
                               at /home/matthias/vcs/github/rust_debug_assertions/library/std/src/sys_common/backtrace.rs:121:18
  71:     0x7f5389726739 - <std[828477b612daf80a]::thread::Builder>::spawn_unchecked_::<rustc_interface[31f5dff205b05af]::util::run_in_thread_pool_with_globals<rustc_interface[31f5dff205b05af]::interface::run_compiler<core[6b044a951f062b59]::result::Result<(), rustc_errors[a8b59b4023676711]::ErrorGuaranteed>, rustc_driver[804584070814ac7f]::run_compiler::{closure#1}>::{closure#0}, core[6b044a951f062b59]::result::Result<(), rustc_errors[a8b59b4023676711]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[6b044a951f062b59]::result::Result<(), rustc_errors[a8b59b4023676711]::ErrorGuaranteed>>::{closure#1}::{closure#0}
                               at /home/matthias/vcs/github/rust_debug_assertions/library/std/src/thread/mod.rs:551:17
  72:     0x7f5389726739 - <core[6b044a951f062b59]::panic::unwind_safe::AssertUnwindSafe<<std[828477b612daf80a]::thread::Builder>::spawn_unchecked_<rustc_interface[31f5dff205b05af]::util::run_in_thread_pool_with_globals<rustc_interface[31f5dff205b05af]::interface::run_compiler<core[6b044a951f062b59]::result::Result<(), rustc_errors[a8b59b4023676711]::ErrorGuaranteed>, rustc_driver[804584070814ac7f]::run_compiler::{closure#1}>::{closure#0}, core[6b044a951f062b59]::result::Result<(), rustc_errors[a8b59b4023676711]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[6b044a951f062b59]::result::Result<(), rustc_errors[a8b59b4023676711]::ErrorGuaranteed>>::{closure#1}::{closure#0}> as core[6b044a951f062b59]::ops::function::FnOnce<()>>::call_once
                               at /home/matthias/vcs/github/rust_debug_assertions/library/core/src/panic/unwind_safe.rs:271:9
  73:     0x7f5389726739 - std[828477b612daf80a]::panicking::try::do_call::<core[6b044a951f062b59]::panic::unwind_safe::AssertUnwindSafe<<std[828477b612daf80a]::thread::Builder>::spawn_unchecked_<rustc_interface[31f5dff205b05af]::util::run_in_thread_pool_with_globals<rustc_interface[31f5dff205b05af]::interface::run_compiler<core[6b044a951f062b59]::result::Result<(), rustc_errors[a8b59b4023676711]::ErrorGuaranteed>, rustc_driver[804584070814ac7f]::run_compiler::{closure#1}>::{closure#0}, core[6b044a951f062b59]::result::Result<(), rustc_errors[a8b59b4023676711]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[6b044a951f062b59]::result::Result<(), rustc_errors[a8b59b4023676711]::ErrorGuaranteed>>::{closure#1}::{closure#0}>, core[6b044a951f062b59]::result::Result<(), rustc_errors[a8b59b4023676711]::ErrorGuaranteed>>
                               at /home/matthias/vcs/github/rust_debug_assertions/library/std/src/panicking.rs:483:40
  74:     0x7f5389726739 - std[828477b612daf80a]::panicking::try::<core[6b044a951f062b59]::result::Result<(), rustc_errors[a8b59b4023676711]::ErrorGuaranteed>, core[6b044a951f062b59]::panic::unwind_safe::AssertUnwindSafe<<std[828477b612daf80a]::thread::Builder>::spawn_unchecked_<rustc_interface[31f5dff205b05af]::util::run_in_thread_pool_with_globals<rustc_interface[31f5dff205b05af]::interface::run_compiler<core[6b044a951f062b59]::result::Result<(), rustc_errors[a8b59b4023676711]::ErrorGuaranteed>, rustc_driver[804584070814ac7f]::run_compiler::{closure#1}>::{closure#0}, core[6b044a951f062b59]::result::Result<(), rustc_errors[a8b59b4023676711]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[6b044a951f062b59]::result::Result<(), rustc_errors[a8b59b4023676711]::ErrorGuaranteed>>::{closure#1}::{closure#0}>>
                               at /home/matthias/vcs/github/rust_debug_assertions/library/std/src/panicking.rs:447:19
  75:     0x7f5389726739 - std[828477b612daf80a]::panic::catch_unwind::<core[6b044a951f062b59]::panic::unwind_safe::AssertUnwindSafe<<std[828477b612daf80a]::thread::Builder>::spawn_unchecked_<rustc_interface[31f5dff205b05af]::util::run_in_thread_pool_with_globals<rustc_interface[31f5dff205b05af]::interface::run_compiler<core[6b044a951f062b59]::result::Result<(), rustc_errors[a8b59b4023676711]::ErrorGuaranteed>, rustc_driver[804584070814ac7f]::run_compiler::{closure#1}>::{closure#0}, core[6b044a951f062b59]::result::Result<(), rustc_errors[a8b59b4023676711]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[6b044a951f062b59]::result::Result<(), rustc_errors[a8b59b4023676711]::ErrorGuaranteed>>::{closure#1}::{closure#0}>, core[6b044a951f062b59]::result::Result<(), rustc_errors[a8b59b4023676711]::ErrorGuaranteed>>
                               at /home/matthias/vcs/github/rust_debug_assertions/library/std/src/panic.rs:137:14
  76:     0x7f5389726739 - <std[828477b612daf80a]::thread::Builder>::spawn_unchecked_::<rustc_interface[31f5dff205b05af]::util::run_in_thread_pool_with_globals<rustc_interface[31f5dff205b05af]::interface::run_compiler<core[6b044a951f062b59]::result::Result<(), rustc_errors[a8b59b4023676711]::ErrorGuaranteed>, rustc_driver[804584070814ac7f]::run_compiler::{closure#1}>::{closure#0}, core[6b044a951f062b59]::result::Result<(), rustc_errors[a8b59b4023676711]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[6b044a951f062b59]::result::Result<(), rustc_errors[a8b59b4023676711]::ErrorGuaranteed>>::{closure#1}
                               at /home/matthias/vcs/github/rust_debug_assertions/library/std/src/thread/mod.rs:550:30
  77:     0x7f5389726739 - <<std[828477b612daf80a]::thread::Builder>::spawn_unchecked_<rustc_interface[31f5dff205b05af]::util::run_in_thread_pool_with_globals<rustc_interface[31f5dff205b05af]::interface::run_compiler<core[6b044a951f062b59]::result::Result<(), rustc_errors[a8b59b4023676711]::ErrorGuaranteed>, rustc_driver[804584070814ac7f]::run_compiler::{closure#1}>::{closure#0}, core[6b044a951f062b59]::result::Result<(), rustc_errors[a8b59b4023676711]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[6b044a951f062b59]::result::Result<(), rustc_errors[a8b59b4023676711]::ErrorGuaranteed>>::{closure#1} as core[6b044a951f062b59]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
                               at /home/matthias/vcs/github/rust_debug_assertions/library/core/src/ops/function.rs:424:5
  78:     0x7f53888a4458 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h1083929d9621d625
                               at /home/matthias/vcs/github/rust_debug_assertions/library/alloc/src/boxed.rs:1990:9
  79:     0x7f53888a4458 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hfd204b891b513d5c
                               at /home/matthias/vcs/github/rust_debug_assertions/library/alloc/src/boxed.rs:1990:9
  80:     0x7f538888d115 - std::sys::unix::thread::Thread::new::thread_start::haf18d2abc166ac7c
                               at /home/matthias/vcs/github/rust_debug_assertions/library/std/src/sys/unix/thread.rs:108:17
  81:     0x7f5388a9f8fd - <unknown>
  82:     0x7f5388b21a60 - <unknown>
  83:                0x0 - <unknown>

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.67.0-dev running on x86_64-unknown-linux-gnu

query stack during panic:
end of query stack
thread 'rustc' panicked at 'Found a `push` without a `pop`.', compiler/rustc_lint/src/levels.rs:504:9
stack backtrace:
   0:     0x7f53888ebe6e - std::backtrace_rs::backtrace::libunwind::trace::h2eba450607c8505f
                               at /home/matthias/vcs/github/rust_debug_assertions/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   1:     0x7f53888ebe6e - std::backtrace_rs::backtrace::trace_unsynchronized::h807100070af02067
                               at /home/matthias/vcs/github/rust_debug_assertions/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7f53888ebe6e - std::sys_common::backtrace::_print_fmt::hb7560753851ac705
                               at /home/matthias/vcs/github/rust_debug_assertions/library/std/src/sys_common/backtrace.rs:65:5
   3:     0x7f53888ebe6e - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hbd9919f0d0dab500
                               at /home/matthias/vcs/github/rust_debug_assertions/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x7f538896a128 - core::fmt::write::h6dd0aa79d810b449
                               at /home/matthias/vcs/github/rust_debug_assertions/library/core/src/fmt/mod.rs:1209:17
   5:     0x7f53888bac4f - std::io::Write::write_fmt::hfd60031a8e080dfa
                               at /home/matthias/vcs/github/rust_debug_assertions/library/std/src/io/mod.rs:1682:15
   6:     0x7f53888ebc65 - std::sys_common::backtrace::_print::hd608f7bedb66f36d
                               at /home/matthias/vcs/github/rust_debug_assertions/library/std/src/sys_common/backtrace.rs:47:5
   7:     0x7f53888ebc65 - std::sys_common::backtrace::print::h860e7f8950ec5f10
                               at /home/matthias/vcs/github/rust_debug_assertions/library/std/src/sys_common/backtrace.rs:34:9
   8:     0x7f53888c1d94 - std::panicking::default_hook::{{closure}}::hcbdc2c60ca06f4de
   9:     0x7f53888c19fe - std::panicking::default_hook::h6a3c0b6519439000
                               at /home/matthias/vcs/github/rust_debug_assertions/library/std/src/panicking.rs:286:9
  10:     0x7f538970d1d2 - <alloc[55cbc4dc069182d1]::boxed::Box<dyn for<'a, 'b> core[6b044a951f062b59]::ops::function::Fn<(&'a core[6b044a951f062b59]::panic::panic_info::PanicInfo<'b>,), Output = ()> + core[6b044a951f062b59]::marker::Send + core[6b044a951f062b59]::marker::Sync> as core[6b044a951f062b59]::ops::function::Fn<(&core[6b044a951f062b59]::panic::panic_info::PanicInfo,)>>::call
                               at /home/matthias/vcs/github/rust_debug_assertions/library/alloc/src/boxed.rs:2024:9
  11:     0x7f538970d1d2 - rustc_driver[804584070814ac7f]::DEFAULT_HOOK::{closure#0}::{closure#0}
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_driver/src/lib.rs:1207:13
  12:     0x7f53888c2477 - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h2f1f731eb522bca3
                               at /home/matthias/vcs/github/rust_debug_assertions/library/alloc/src/boxed.rs:2024:9
  13:     0x7f53888c2477 - std::panicking::rust_panic_with_hook::h89bceab315f7fcd4
                               at /home/matthias/vcs/github/rust_debug_assertions/library/std/src/panicking.rs:692:13
  14:     0x7f53888ec1b1 - std::panicking::begin_panic_handler::{{closure}}::h0d7cacab89b29cb2
                               at /home/matthias/vcs/github/rust_debug_assertions/library/std/src/panicking.rs:577:13
  15:     0x7f53888ebfbe - std::sys_common::backtrace::__rust_end_short_backtrace::h9db04dfc5a3661d7
                               at /home/matthias/vcs/github/rust_debug_assertions/library/std/src/sys_common/backtrace.rs:137:18
  16:     0x7f53888c1f92 - rust_begin_unwind
                               at /home/matthias/vcs/github/rust_debug_assertions/library/std/src/panicking.rs:575:5
  17:     0x7f538887a173 - core::panicking::panic_fmt::h00fdaf7d8f535993
                               at /home/matthias/vcs/github/rust_debug_assertions/library/core/src/panicking.rs:65:14
  18:     0x7f538e689309 - <rustc_lint[798cc8cfe34c1960]::levels::BuilderPush as core[6b044a951f062b59]::ops::drop::Drop>::drop
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_lint/src/levels.rs:504:9
  19:     0x7f538997eef0 - <rustc_lint[798cc8cfe34c1960]::early::EarlyContextAndPass<rustc_lint[798cc8cfe34c1960]::BuiltinCombinedEarlyLintPass>>::with_lint_attrs::<<rustc_lint[798cc8cfe34c1960]::early::EarlyContextAndPass<rustc_lint[798cc8cfe34c1960]::BuiltinCombinedEarlyLintPass> as rustc_ast[10a597527468fdcd]::visit::Visitor>::visit_stmt::{closure#0}>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_lint/src/early.rs:71:5
  20:     0x7f538997eef0 - <rustc_lint[798cc8cfe34c1960]::early::EarlyContextAndPass<rustc_lint[798cc8cfe34c1960]::BuiltinCombinedEarlyLintPass> as rustc_ast[10a597527468fdcd]::visit::Visitor>::visit_stmt
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_lint/src/early.rs:136:9
  21:     0x7f538992804c - rustc_ast[10a597527468fdcd]::visit::walk_block::<rustc_lint[798cc8cfe34c1960]::early::EarlyContextAndPass<rustc_lint[798cc8cfe34c1960]::BuiltinCombinedEarlyLintPass>>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_ast/src/visit.rs:716:5
  22:     0x7f538992804c - <rustc_lint[798cc8cfe34c1960]::early::EarlyContextAndPass<rustc_lint[798cc8cfe34c1960]::BuiltinCombinedEarlyLintPass> as rustc_ast[10a597527468fdcd]::visit::Visitor>::visit_block
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_lint/src/early.rs:201:9
  23:     0x7f538992804c - rustc_ast[10a597527468fdcd]::visit::walk_fn::<rustc_lint[798cc8cfe34c1960]::early::EarlyContextAndPass<rustc_lint[798cc8cfe34c1960]::BuiltinCombinedEarlyLintPass>>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_ast/src/visit.rs:667:13
  24:     0x7f538992c4ca - <rustc_lint[798cc8cfe34c1960]::early::EarlyContextAndPass<rustc_lint[798cc8cfe34c1960]::BuiltinCombinedEarlyLintPass> as rustc_ast[10a597527468fdcd]::visit::Visitor>::visit_fn
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_lint/src/early.rs:150:9
  25:     0x7f538992c4ca - rustc_ast[10a597527468fdcd]::visit::walk_item::<rustc_lint[798cc8cfe34c1960]::early::EarlyContextAndPass<rustc_lint[798cc8cfe34c1960]::BuiltinCombinedEarlyLintPass>>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_ast/src/visit.rs:312:13
  26:     0x7f538997e4c9 - <rustc_lint[798cc8cfe34c1960]::early::EarlyContextAndPass<rustc_lint[798cc8cfe34c1960]::BuiltinCombinedEarlyLintPass> as rustc_ast[10a597527468fdcd]::visit::Visitor>::visit_item::{closure#0}
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_lint/src/early.rs:85:13
  27:     0x7f538997e4c9 - <rustc_lint[798cc8cfe34c1960]::early::EarlyContextAndPass<rustc_lint[798cc8cfe34c1960]::BuiltinCombinedEarlyLintPass>>::with_lint_attrs::<<rustc_lint[798cc8cfe34c1960]::early::EarlyContextAndPass<rustc_lint[798cc8cfe34c1960]::BuiltinCombinedEarlyLintPass> as rustc_ast[10a597527468fdcd]::visit::Visitor>::visit_item::{closure#0}>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_lint/src/early.rs:67:9
  28:     0x7f538997e4c9 - <rustc_lint[798cc8cfe34c1960]::early::EarlyContextAndPass<rustc_lint[798cc8cfe34c1960]::BuiltinCombinedEarlyLintPass> as rustc_ast[10a597527468fdcd]::visit::Visitor>::visit_item
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_lint/src/early.rs:83:9
  29:     0x7f538992273c - rustc_ast[10a597527468fdcd]::visit::walk_crate::<rustc_lint[798cc8cfe34c1960]::early::EarlyContextAndPass<rustc_lint[798cc8cfe34c1960]::BuiltinCombinedEarlyLintPass>>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_ast/src/visit.rs:263:5
  30:     0x7f5389973d29 - <&rustc_ast[10a597527468fdcd]::ast::Crate as rustc_lint[798cc8cfe34c1960]::early::EarlyCheckNode>::check::<rustc_lint[798cc8cfe34c1960]::BuiltinCombinedEarlyLintPass>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_lint/src/early.rs:347:9
  31:     0x7f5389973d29 - rustc_lint[798cc8cfe34c1960]::early::early_lint_node::<rustc_lint[798cc8cfe34c1960]::BuiltinCombinedEarlyLintPass, &rustc_ast[10a597527468fdcd]::ast::Crate>::{closure#0}
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_lint/src/early.rs:391:66
  32:     0x7f5389973d29 - <rustc_lint[798cc8cfe34c1960]::early::EarlyContextAndPass<rustc_lint[798cc8cfe34c1960]::BuiltinCombinedEarlyLintPass>>::with_lint_attrs::<rustc_lint[798cc8cfe34c1960]::early::early_lint_node<rustc_lint[798cc8cfe34c1960]::BuiltinCombinedEarlyLintPass, &rustc_ast[10a597527468fdcd]::ast::Crate>::{closure#0}>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_lint/src/early.rs:67:9
  33:     0x7f5389973d29 - rustc_lint[798cc8cfe34c1960]::early::early_lint_node::<rustc_lint[798cc8cfe34c1960]::BuiltinCombinedEarlyLintPass, &rustc_ast[10a597527468fdcd]::ast::Crate>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_lint/src/early.rs:391:5
  34:     0x7f5389973d29 - rustc_lint[798cc8cfe34c1960]::early::check_ast_node::<rustc_lint[798cc8cfe34c1960]::BuiltinCombinedEarlyLintPass, &rustc_ast[10a597527468fdcd]::ast::Crate>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_lint/src/early.rs:425:20
  35:     0x7f538988e014 - rustc_interface[31f5dff205b05af]::passes::configure_and_expand::{closure#8}
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_interface/src/passes.rs:448:9
  36:     0x7f538988e014 - <rustc_data_structures[bb7700ba3124b76b]::profiling::VerboseTimingGuard>::run::<(), rustc_interface[31f5dff205b05af]::passes::configure_and_expand::{closure#8}>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_session/src/utils.rs:10:9
  37:     0x7f538988e014 - <rustc_session[7d66d4184c51f11]::session::Session>::time::<(), rustc_interface[31f5dff205b05af]::passes::configure_and_expand::{closure#8}>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_session/src/utils.rs:10:9
  38:     0x7f53898d5f43 - rustc_interface[31f5dff205b05af]::passes::configure_and_expand
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_interface/src/passes.rs:446:5
  39:     0x7f5389952283 - <rustc_interface[31f5dff205b05af]::queries::Queries>::expansion::{closure#0}::{closure#0}
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_interface/src/queries.rs:182:17
  40:     0x7f5389952283 - <rustc_interface[31f5dff205b05af]::passes::boxed_resolver::BoxedResolver>::access::<<rustc_interface[31f5dff205b05af]::queries::Queries>::expansion::{closure#0}::{closure#0}, core[6b044a951f062b59]::result::Result<rustc_ast[10a597527468fdcd]::ast::Crate, rustc_errors[a8b59b4023676711]::ErrorGuaranteed>>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_interface/src/passes.rs:134:13
  41:     0x7f53898a417e - <rustc_interface[31f5dff205b05af]::queries::Queries>::expansion::{closure#0}
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_interface/src/queries.rs:181:25
  42:     0x7f53898a417e - <rustc_interface[31f5dff205b05af]::queries::Query<(alloc[55cbc4dc069182d1]::rc::Rc<rustc_ast[10a597527468fdcd]::ast::Crate>, alloc[55cbc4dc069182d1]::rc::Rc<core[6b044a951f062b59]::cell::RefCell<rustc_interface[31f5dff205b05af]::passes::boxed_resolver::BoxedResolver>>, alloc[55cbc4dc069182d1]::rc::Rc<rustc_lint[798cc8cfe34c1960]::context::LintStore>)>>::compute::<<rustc_interface[31f5dff205b05af]::queries::Queries>::expansion::{closure#0}>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_interface/src/queries.rs:38:28
  43:     0x7f53898a417e - <rustc_interface[31f5dff205b05af]::queries::Queries>::expansion
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_interface/src/queries.rs:170:9
  44:     0x7f53897a7da0 - rustc_driver[804584070814ac7f]::run_compiler::{closure#1}::{closure#2}
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_driver/src/lib.rs:357:13
  45:     0x7f53897a7da0 - <rustc_interface[31f5dff205b05af]::interface::Compiler>::enter::<rustc_driver[804584070814ac7f]::run_compiler::{closure#1}::{closure#2}, core[6b044a951f062b59]::result::Result<core[6b044a951f062b59]::option::Option<rustc_interface[31f5dff205b05af]::queries::Linker>, rustc_errors[a8b59b4023676711]::ErrorGuaranteed>>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_interface/src/queries.rs:381:19
  46:     0x7f538970ed35 - rustc_driver[804584070814ac7f]::run_compiler::{closure#1}
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_driver/src/lib.rs:308:22
  47:     0x7f538970ed35 - rustc_interface[31f5dff205b05af]::interface::run_compiler::<core[6b044a951f062b59]::result::Result<(), rustc_errors[a8b59b4023676711]::ErrorGuaranteed>, rustc_driver[804584070814ac7f]::run_compiler::{closure#1}>::{closure#0}::{closure#1}
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_interface/src/interface.rs:327:21
  48:     0x7f538970ed35 - rustc_span[8a6424ea12543a70]::with_source_map::<core[6b044a951f062b59]::result::Result<(), rustc_errors[a8b59b4023676711]::ErrorGuaranteed>, rustc_interface[31f5dff205b05af]::interface::run_compiler<core[6b044a951f062b59]::result::Result<(), rustc_errors[a8b59b4023676711]::ErrorGuaranteed>, rustc_driver[804584070814ac7f]::run_compiler::{closure#1}>::{closure#0}::{closure#1}>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_span/src/lib.rs:1009:5
  49:     0x7f5389795b8c - rustc_interface[31f5dff205b05af]::interface::run_compiler::<core[6b044a951f062b59]::result::Result<(), rustc_errors[a8b59b4023676711]::ErrorGuaranteed>, rustc_driver[804584070814ac7f]::run_compiler::{closure#1}>::{closure#0}
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_interface/src/interface.rs:321:13
  50:     0x7f5389795b8c - <scoped_tls[4b2a4c8958d0f0a7]::ScopedKey<rustc_span[8a6424ea12543a70]::SessionGlobals>>::set::<rustc_interface[31f5dff205b05af]::interface::run_compiler<core[6b044a951f062b59]::result::Result<(), rustc_errors[a8b59b4023676711]::ErrorGuaranteed>, rustc_driver[804584070814ac7f]::run_compiler::{closure#1}>::{closure#0}, core[6b044a951f062b59]::result::Result<(), rustc_errors[a8b59b4023676711]::ErrorGuaranteed>>
                               at /home/matthias/.cargo/registry/src/github.com-1ecc6299db9ec823/scoped-tls-1.0.0/src/lib.rs:137:9
  51:     0x7f5389791140 - rustc_span[8a6424ea12543a70]::create_session_globals_then::<core[6b044a951f062b59]::result::Result<(), rustc_errors[a8b59b4023676711]::ErrorGuaranteed>, rustc_interface[31f5dff205b05af]::interface::run_compiler<core[6b044a951f062b59]::result::Result<(), rustc_errors[a8b59b4023676711]::ErrorGuaranteed>, rustc_driver[804584070814ac7f]::run_compiler::{closure#1}>::{closure#0}>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_span/src/lib.rs:111:5
  52:     0x7f5389791140 - rustc_interface[31f5dff205b05af]::util::run_in_thread_pool_with_globals::<rustc_interface[31f5dff205b05af]::interface::run_compiler<core[6b044a951f062b59]::result::Result<(), rustc_errors[a8b59b4023676711]::ErrorGuaranteed>, rustc_driver[804584070814ac7f]::run_compiler::{closure#1}>::{closure#0}, core[6b044a951f062b59]::result::Result<(), rustc_errors[a8b59b4023676711]::ErrorGuaranteed>>::{closure#0}::{closure#0}
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_interface/src/util.rs:148:38
  53:     0x7f5389791140 - std[828477b612daf80a]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[31f5dff205b05af]::util::run_in_thread_pool_with_globals<rustc_interface[31f5dff205b05af]::interface::run_compiler<core[6b044a951f062b59]::result::Result<(), rustc_errors[a8b59b4023676711]::ErrorGuaranteed>, rustc_driver[804584070814ac7f]::run_compiler::{closure#1}>::{closure#0}, core[6b044a951f062b59]::result::Result<(), rustc_errors[a8b59b4023676711]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[6b044a951f062b59]::result::Result<(), rustc_errors[a8b59b4023676711]::ErrorGuaranteed>>
                               at /home/matthias/vcs/github/rust_debug_assertions/library/std/src/sys_common/backtrace.rs:121:18
  54:     0x7f5389726739 - <std[828477b612daf80a]::thread::Builder>::spawn_unchecked_::<rustc_interface[31f5dff205b05af]::util::run_in_thread_pool_with_globals<rustc_interface[31f5dff205b05af]::interface::run_compiler<core[6b044a951f062b59]::result::Result<(), rustc_errors[a8b59b4023676711]::ErrorGuaranteed>, rustc_driver[804584070814ac7f]::run_compiler::{closure#1}>::{closure#0}, core[6b044a951f062b59]::result::Result<(), rustc_errors[a8b59b4023676711]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[6b044a951f062b59]::result::Result<(), rustc_errors[a8b59b4023676711]::ErrorGuaranteed>>::{closure#1}::{closure#0}
                               at /home/matthias/vcs/github/rust_debug_assertions/library/std/src/thread/mod.rs:551:17
  55:     0x7f5389726739 - <core[6b044a951f062b59]::panic::unwind_safe::AssertUnwindSafe<<std[828477b612daf80a]::thread::Builder>::spawn_unchecked_<rustc_interface[31f5dff205b05af]::util::run_in_thread_pool_with_globals<rustc_interface[31f5dff205b05af]::interface::run_compiler<core[6b044a951f062b59]::result::Result<(), rustc_errors[a8b59b4023676711]::ErrorGuaranteed>, rustc_driver[804584070814ac7f]::run_compiler::{closure#1}>::{closure#0}, core[6b044a951f062b59]::result::Result<(), rustc_errors[a8b59b4023676711]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[6b044a951f062b59]::result::Result<(), rustc_errors[a8b59b4023676711]::ErrorGuaranteed>>::{closure#1}::{closure#0}> as core[6b044a951f062b59]::ops::function::FnOnce<()>>::call_once
                               at /home/matthias/vcs/github/rust_debug_assertions/library/core/src/panic/unwind_safe.rs:271:9
  56:     0x7f5389726739 - std[828477b612daf80a]::panicking::try::do_call::<core[6b044a951f062b59]::panic::unwind_safe::AssertUnwindSafe<<std[828477b612daf80a]::thread::Builder>::spawn_unchecked_<rustc_interface[31f5dff205b05af]::util::run_in_thread_pool_with_globals<rustc_interface[31f5dff205b05af]::interface::run_compiler<core[6b044a951f062b59]::result::Result<(), rustc_errors[a8b59b4023676711]::ErrorGuaranteed>, rustc_driver[804584070814ac7f]::run_compiler::{closure#1}>::{closure#0}, core[6b044a951f062b59]::result::Result<(), rustc_errors[a8b59b4023676711]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[6b044a951f062b59]::result::Result<(), rustc_errors[a8b59b4023676711]::ErrorGuaranteed>>::{closure#1}::{closure#0}>, core[6b044a951f062b59]::result::Result<(), rustc_errors[a8b59b4023676711]::ErrorGuaranteed>>
                               at /home/matthias/vcs/github/rust_debug_assertions/library/std/src/panicking.rs:483:40
  57:     0x7f5389726739 - std[828477b612daf80a]::panicking::try::<core[6b044a951f062b59]::result::Result<(), rustc_errors[a8b59b4023676711]::ErrorGuaranteed>, core[6b044a951f062b59]::panic::unwind_safe::AssertUnwindSafe<<std[828477b612daf80a]::thread::Builder>::spawn_unchecked_<rustc_interface[31f5dff205b05af]::util::run_in_thread_pool_with_globals<rustc_interface[31f5dff205b05af]::interface::run_compiler<core[6b044a951f062b59]::result::Result<(), rustc_errors[a8b59b4023676711]::ErrorGuaranteed>, rustc_driver[804584070814ac7f]::run_compiler::{closure#1}>::{closure#0}, core[6b044a951f062b59]::result::Result<(), rustc_errors[a8b59b4023676711]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[6b044a951f062b59]::result::Result<(), rustc_errors[a8b59b4023676711]::ErrorGuaranteed>>::{closure#1}::{closure#0}>>
                               at /home/matthias/vcs/github/rust_debug_assertions/library/std/src/panicking.rs:447:19
  58:     0x7f5389726739 - std[828477b612daf80a]::panic::catch_unwind::<core[6b044a951f062b59]::panic::unwind_safe::AssertUnwindSafe<<std[828477b612daf80a]::thread::Builder>::spawn_unchecked_<rustc_interface[31f5dff205b05af]::util::run_in_thread_pool_with_globals<rustc_interface[31f5dff205b05af]::interface::run_compiler<core[6b044a951f062b59]::result::Result<(), rustc_errors[a8b59b4023676711]::ErrorGuaranteed>, rustc_driver[804584070814ac7f]::run_compiler::{closure#1}>::{closure#0}, core[6b044a951f062b59]::result::Result<(), rustc_errors[a8b59b4023676711]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[6b044a951f062b59]::result::Result<(), rustc_errors[a8b59b4023676711]::ErrorGuaranteed>>::{closure#1}::{closure#0}>, core[6b044a951f062b59]::result::Result<(), rustc_errors[a8b59b4023676711]::ErrorGuaranteed>>
                               at /home/matthias/vcs/github/rust_debug_assertions/library/std/src/panic.rs:137:14
  59:     0x7f5389726739 - <std[828477b612daf80a]::thread::Builder>::spawn_unchecked_::<rustc_interface[31f5dff205b05af]::util::run_in_thread_pool_with_globals<rustc_interface[31f5dff205b05af]::interface::run_compiler<core[6b044a951f062b59]::result::Result<(), rustc_errors[a8b59b4023676711]::ErrorGuaranteed>, rustc_driver[804584070814ac7f]::run_compiler::{closure#1}>::{closure#0}, core[6b044a951f062b59]::result::Result<(), rustc_errors[a8b59b4023676711]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[6b044a951f062b59]::result::Result<(), rustc_errors[a8b59b4023676711]::ErrorGuaranteed>>::{closure#1}
                               at /home/matthias/vcs/github/rust_debug_assertions/library/std/src/thread/mod.rs:550:30
  60:     0x7f5389726739 - <<std[828477b612daf80a]::thread::Builder>::spawn_unchecked_<rustc_interface[31f5dff205b05af]::util::run_in_thread_pool_with_globals<rustc_interface[31f5dff205b05af]::interface::run_compiler<core[6b044a951f062b59]::result::Result<(), rustc_errors[a8b59b4023676711]::ErrorGuaranteed>, rustc_driver[804584070814ac7f]::run_compiler::{closure#1}>::{closure#0}, core[6b044a951f062b59]::result::Result<(), rustc_errors[a8b59b4023676711]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[6b044a951f062b59]::result::Result<(), rustc_errors[a8b59b4023676711]::ErrorGuaranteed>>::{closure#1} as core[6b044a951f062b59]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
                               at /home/matthias/vcs/github/rust_debug_assertions/library/core/src/ops/function.rs:424:5
  61:     0x7f53888a4458 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h1083929d9621d625
                               at /home/matthias/vcs/github/rust_debug_assertions/library/alloc/src/boxed.rs:1990:9
  62:     0x7f53888a4458 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hfd204b891b513d5c
                               at /home/matthias/vcs/github/rust_debug_assertions/library/alloc/src/boxed.rs:1990:9
  63:     0x7f538888d115 - std::sys::unix::thread::Thread::new::thread_start::haf18d2abc166ac7c
                               at /home/matthias/vcs/github/rust_debug_assertions/library/std/src/sys/unix/thread.rs:108:17
  64:     0x7f5388a9f8fd - <unknown>
  65:     0x7f5388b21a60 - <unknown>
  66:                0x0 - <unknown>

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.67.0-dev running on x86_64-unknown-linux-gnu

query stack during panic:
end of query stack
thread panicked while panicking. aborting.
[2]    3199823 IOT instruction (core dumped)   ./rust-analyzer/crates/parser/test_data/parser/err/0042_weird_blocks.rs
```

</p>
</details>

### PR DESCRIPTION
**Pull request by TaKO8Ki**
Fixes #104392

### CODE REVIEW

File: compiler/rustc_lint/src/unused.rs [hunk 1]
```diff
@@ -517,16 +517,14 @@ trait UnusedDelimLint {
         right_pos: Option<BytePos>,
     ) {
         let spans = match value.kind {
-            ast::ExprKind::Block(ref block, None) if block.stmts.len() > 0 => {
-                let start = block.stmts[0].span;
-                let end = block.stmts[block.stmts.len() - 1].span;
-                if let Some(start) = start.find_ancestor_inside(value.span)
-                    && let Some(end) = end.find_ancestor_inside(value.span)
+            ast::ExprKind::Block(ref block, None) if block.stmts.len() == 1 => {
```
Comment (TaKO8Ki) [inline compiler/rustc_lint/src/unused.rs:520]: According to the following comment, the block always has one statement.

https://github.com/rust-lang/rust/blob/101e1822c3e54e63996c8aaa014d55716f3937eb/compiler/rustc_lint/src/unused.rs#L992-L998
