### PR TITLE
Fix connect timeout for VxWorks, read readiness of socket connection, Read readiness to detect errors. `Fixes #127018`

### LINKED ISSUE #127018: std::net::TcpStream::connect_timeout on vxworks
I'm tracking a issue with connect_timeout function on rust for vxworks. The function is also accepting connections on a non responsive server port. I get errors on unreachable host, but with host that are reachable any connection to a non existent server port is not resulting in an error.

example program:

```rust
use std::{
    net::{SocketAddr, TcpStream},
    time::Duration,
};

fn main() {
    let sock_addr: SocketAddr = std::env::args()
        .into_iter()
        .nth(1)
        .unwrap()
        .parse()
        .unwrap();
    dbg!(sock_addr);
    let timeout = Duration::from_secs(5);
    let maybe_stream = TcpStream::connect_timeout(&sock_addr, timeout);
    match maybe_stream {
        Ok(_stream) => println!("Successfully connected to server"),
        Err(err) => eprintln!("Failed to connect to server: {:?}", err),
    };
}
```

Results:
#./exe 127.0.0.1:90 /// No server at this port
Successfully connected to server
#./exe 192.0.0.1:20 //// Host is unreachable so correct behaviour.
Failed to connect to server
#./exe 172.16.2.223:8002 //Host is reachable, but there's no server at this port
Successfully connected to server

This is not observed with the connect function.
I don't see a specified folder in library/std/src/sys/pal for vxworks. I found only one file for vxworks library/std/src/sys/pal/unix/process/process_vxworks.rs files. Does vxworks fall back on unix implementations for these functionalities? Any leads on how to proceed would be really helpful.

### PR DESCRIPTION
**Pull request by biabbas**
Fixes #127018 
Connect_timeout would call `poll` and check `pollfd.revents` for POLLHUP error, rather that checking readiness. This behavior was meant for Linux as it returns POLLHUP | POLLOUT | POLLERR in case of errors. But on targets that do not return POLLHUP in `pollfd.revents`, this would indicate a false success and result in this issue. To resolve this we will check readiness of socket using  `getsockopt():`  and return success from connect_timeout when there are no errors.
Changes were tested on Linux and an rtos.
Screenshot 2024-07-04 105820
Thank you.

### CODE REVIEW

**Comment by jhpratt** [comment]
Not sure why I was explicitly requested as a reviewer. I don't have the necessary context/knowledge in any situation.

r? libs

**Comment by jhpratt** [comment]
r? libs

**Comment by Nilstrieb** [comment]
I don't know enough about this area either. maybe you do?
r? the8472

File: library/std/src/sys/pal/unix/net.rs [hunk 1]
```diff
@@ -213,15 +213,9 @@ impl Socket {
...
-                            io::const_io_error!(
-                                io::ErrorKind::Uncategorized,
-                                "no error set after POLLHUP",
-                            )
-                        });
+                    // Check if the connnection actually succeeded and return ok only when
+                    // the socket is ready and no errors were found
+                    if let Some(e) = self.take_error()? {
                         return Err(e);
                     }
```
Comment (tgross35) [inline library/std/src/sys/pal/unix/net.rs:220]: I don't think it makes sense to change this for all platforms, since https://github.com/rust-lang/rust/pull/127272 (precursor) and https://github.com/rust-lang/rust/issues/127018 seem to indicate this is only on vxworks (or are there others you know of?)

```suggestion
                    if cfg!(target_os = "vxworks") {
                        // [comment about vxworks not using POLLHUP]
                        if let Some(e) = self.take_error()? {
                            return Err(e);
                        }
                    } else {
                        /* original impl */
                    }
```

Also just for reference, if you put `Fixes #127018` in a line of your PR description then it will close the issue when this merges.

**Review by tgross35 — CHANGES_REQUESTED** [review]

File: library/std/src/sys/pal/unix/net.rs (hunk 1 above)
Comment (biabbas) [reply library/std/src/sys/pal/unix/net.rs:220]: @tgross35 I don't think that changes I made will impact other platforms. For code simplicity, I did not make these changes specific for Vxworks.

**Comment by biabbas** [comment]
Not sure if @tgross35 can approve this pr as I don't know if he is a member of rust lang. 
r?

File: library/std/src/sys/pal/unix/net.rs (hunk 1 above)
Comment (tgross35) [reply library/std/src/sys/pal/unix/net.rs:220]: I also do not understand the details here but to me it seems like the difference between returning `Err` on all errors vs. only on hangups must be intentional. So I am hesitant to change this without having a better picture of what is going on.

@sfackler it looks like you authored this bit of code in https://github.com/rust-lang/rust/pull/43062 and updated it in https://github.com/rust-lang/rust/pull/45269. What is the reasoning to check for `POLLOUT`/`POLLHUP` rather than just always returning an error?

Comment (tgross35) [reply library/std/src/sys/pal/unix/net.rs:220]: @the8472 might have a better idea here too

Comment (sfackler) [reply library/std/src/sys/pal/unix/net.rs:220]: I wrote that code 7 years ago - I do not remember the specific context around it.

Comment (tgross35) [reply library/std/src/sys/pal/unix/net.rs:220]: Worth a shot, thanks for taking a look.

Comment (biabbas) [reply library/std/src/sys/pal/unix/net.rs:220]: Thanks @sfackler

Comment (tgross35) [reply library/std/src/sys/pal/unix/net.rs:220]: A few relevant things from https://man7.org/linux/man-pages/man2/poll.2.html:

```text
The field events is an input parameter ...
This field may be specified as zero, in which case the only
events that can be returned in revents are POLLHUP, POLLERR, and
POLLNVAL (see below).
```

We probably don't need to set `POLLOUT` anymore as we aren't checking on it since https://github.com/rust-lang/rust/pull/45269.

```text
       POLLERR
              Error condition (only returned in revents; ignored in
              events).  This bit is also set for a file descriptor
              referring to the write end of a pipe when the read end has
              been closed.

       POLLHUP
              Hang up (only returned in revents; ignored in events).
              Note that when reading from a channel such as a pipe or a
              stream socket, this event merely indicates that the peer
              closed its end of the channel.  Subsequent reads from the
              channel will return 0 (end of file) only after all
              outstanding data in the channel has been consumed.

       POLLNVAL
              Invalid request: fd not open (only returned in revents;
              ignored in events).
```

From https://github.com/rust-lang/rust/issues/45265#issuecomment-336536875, it sounds like in reality it sets all three.

The manpage doesn't say anything about setting an error to `SO_ERROR`. I would assume this is always true, but it does seem safer to me to have the fallback. It seems a bit weird to me that we are checking only against POLLHUP and not a `POLLHUP | POLLNVAL | POLLERR` mask since these are all documented error conditions, even though this does seem to work (perhaps the other cases come up more for files).

---

So: I wouldn't really want to change the existing Linux handling to the proposal (except for maybe checking `POLLNVAL` and `POLLERR` too)  because it means going from documented behavior to empirical behavior, even if that seems correct. In which case I would prefer the `cfg` suggestion above to the current proposal.

However, I think this code could be cleaned up a bit with the following, that should work on your system too:

1. Change the `libc::pollfd` struct to have events as 0 rather than `POLLOUT` as we are no longer checking `POLLOUT` (since https://github.com/rust-lang/rust/pull/45269)
2. Since we are no longer have a possible `POLLOUT` `revent`, the possible results of `libc::poll` are:
    - -1: error via errno
    - 0: success
    - 3 (Linux), something else (vxworks): emitted three revents, `POLLHUP | POLLNVAL | POLLERR`
3. Since we no longer have the case of one successful revent (`POLLOUT`), the last match arm can be changed to always emit an error without maybe checking `revents`. So just remove the `if` from the existing code so it always emits `self.take_error()?.unwrap_or_else(|| { ... })`.

   That is, it will always try to read the `SO_ERROR` (works on both Linux and vxworks). If that fails, meaning revents were set but there is no `SO_ERROR` for some unexpected reason, it will emit an `Uncategorized` error (can never happen on vxworks per https://github.com/rust-lang/rust/issues/127018, but maybe possible on linux?).
4. If you feel like it, `debug_assert!` that the revents are what we expect.

If that tests well, then I think it might be a more robust option on all systems. If you make the changes please comment it well, somebody else is going to have to reverse engineer this one day...

---

Doesn't matter if the above works, but does Vxworks set `POLLNVAL` or `POLLERR` rather than a mask including `POLLHUP`?

Comment (biabbas) [reply library/std/src/sys/pal/unix/net.rs:220]: If we set `poll->events` to zero, poll will wait until the specified time until its gets an file descriptor with error event. This behavior is not convenient for successful connections as you would end up waiting till the specified timeout.
I think going with the cfg option for vxworks is better for now.

Comment (biabbas) [reply library/std/src/sys/pal/unix/net.rs]: I'm a bit surprised that no other targets reported an error on connect_timeout only checking POLLHUP in revents.

File: library/std/src/sys/pal/unix/net.rs [hunk 2]
```diff
@@ -213,16 +213,25 @@ impl Socket {
...
-                            io::const_io_error!(
-                                io::ErrorKind::Uncategorized,
-                                "no error set after POLLHUP",
-                            )
-                        });
-                        return Err(e);
+                    if cfg!(target_os = "vxworks") {
+                        // Check if the connnection actually succeeded and return ok only when
+                        // the socket is ready and no errors were found
+                        // https://github.com/rust-lang/rust/issues/127018
```
Comment (tgross35) [inline library/std/src/sys/pal/unix/net.rs:219]: Could you just add a note specifically saying vxworks does not set POLLHUP, POLLERR, or POLLOUT? Ok to delete the issue link with this if you want.

r=me after this

File: library/std/src/sys/pal/unix/net.rs (hunk 1 above)
Comment (tgross35) [reply library/std/src/sys/pal/unix/net.rs]: Ah right, duh. Thanks for the change and for all the followup here, I left one suggested change to a comment then looks good.

File: library/std/src/sys/pal/unix/net.rs [hunk 3]
```diff
@@ -213,16 +213,25 @@ impl Socket {
...
+                        if let Some(e) = self.take_error()? {
+                            return Err(e);
+                        }
+                    } else {
+                        // linux returns POLLOUT|POLLERR|POLLHUP for refused connections (!), so look
+                        // for POLLHUP rather than read readiness
+                        if pollfd.revents & libc::POLLHUP != 0 {
```
Comment (tgross35) [inline library/std/src/sys/pal/unix/net.rs:226]: > I'm a bit surprised that no other targets reported an error on connect_timeout only checking POLLHUP in revents.

If you're up for it I think you can change this to check POLLERR too:

```suggestion
                        // linux returns POLLOUT|POLLERR|POLLHUP for refused connections (!), so check
                        // the error conditions.
                        if pollfd.revents & (libc::POLLHUP | libc::POLLERR) != 0 {
```

But definitely not required

Comment (biabbas) [reply library/std/src/sys/pal/unix/net.rs:226]: Sure. I'll set it to look for POLLHUP or POLLERR for linux.

File: library/std/src/sys/pal/unix/net.rs (hunk 2 above)
Comment (biabbas) [reply library/std/src/sys/pal/unix/net.rs]: r=me

**Comment by biabbas** [comment]
@r? =me

File: library/std/src/sys/pal/unix/net.rs (hunk 2 above)
Comment (biabbas) [reply library/std/src/sys/pal/unix/net.rs]: @tgross35 `r=me` doesn't work.

Comment (tgross35) [reply library/std/src/sys/pal/unix/net.rs]: Not literally `r=me`, It just means that someone can tell bors `r=tgross35` (or whoever said it) to approve it. But you still need to be in reviewers.

File: library/std/src/sys/pal/unix/net.rs (hunk 3 above)
Comment (tgross35) [reply library/std/src/sys/pal/unix/net.rs]: Thanks!

**Review by tgross35 — APPROVED** [review]

File: library/std/src/sys/pal/unix/net.rs (hunk 2 above)
Comment (biabbas) [reply library/std/src/sys/pal/unix/net.rs]: Can I also be a Contributor/reviewer? What are the requirements? @tgross35

Comment (tgross35) [reply library/std/src/sys/pal/unix/net.rs]: Github adds the "contributor" label to anybody who has a merged PR, which you will soon, if that is what you meant. So welcome :). You can also always add your review to any PRs, help with issues, and join discussion on Zulip. You'll come across other ways to get more involved (WGs, teams) if you stay around for a while.

If you are interested in contributing more, something that would be immediately helpful is to list yourself as a maintainer for vxworks, since we could use somebody to refer to but don't have anyone listed yet. You just need to add a file to https://github.com/rust-lang/rust/tree/9c3bc805dd9cb84019c124b9a50fdff1e62a7ec9/src/doc/rustc/src/platform-support by duplicating `TEMPLATE.md` and updating it.
