### PR TITLE
Move E0379 check from typeck to ast validation

### LINKED ISSUE #35404: Prettify E0379
Original issue #35338, PR #35364.

From: src/test/compile-fail/const-fn-mismatch.rs

Bonus: shrink the span to focus on the const part:
```
error[E0379]: trait fns cannot be declared const
  --> src/test/compile-fail/const-fn-mismatch.rs:23:5
   |
23 |     const fn f() -> u32 { 22 } //~ ERROR E0379
   |     ^^^^^ trait tns cannot be const
```

### PR DESCRIPTION
**Pull request by KiChjang**
Part of #35233.
Extension of #35338, #35364.
Fixes #35404.

r? @jonathandturner

### CODE REVIEW

File: src/libsyntax/ext/tt/macro_rules.rs [hunk 1]
```diff
@@ -94,7 +94,7 @@ impl<'a> MacResult for ParserAnyMacro<'a> {
             let mut parser = self.parser.borrow_mut();
             match parser.token {
                 token::Eof => break,
-                _ => ret.push(panictry!(parser.parse_impl_item()))
+                _ => ret.push(panictry!(parser.parse_impl_item(false)))
```
Comment (KiChjang) [inline src/libsyntax/ext/tt/macro_rules.rs]: Someone should double-check this - `make_items` should cover the case fo macro trait impl fns and trait fns, so when `make_impl_items` is called, we can be certain that this is going to be a plain impl without traits, hence this here is false.

**Comment by petrochenkov** [comment]
@KiChjang 
Checks performed in the parser can be overridden by syntax extensions (and occasionally macros), so we have a special pass instead that runs after expansion: https://github.com/rust-lang/rust/blob/master/src/librustc_passes/ast_validation.rs
This check is a perfect candidate for moving there.

**Comment by KiChjang** [comment]
Moved the error from the parser to the ast validator.

File: src/librustc_typeck/check/mod.rs [hunk 2]
```diff
@@ -819,14 +819,10 @@ pub fn check_item_body<'a,'tcx>(ccx: &CrateCtxt<'a,'tcx>, it: &'tcx hir::Item) {
                     check_const(ccx, trait_item.span, &expr, trait_item.id)
                 }
                 hir::MethodTraitItem(ref sig, Some(ref body)) => {
```
Comment (nikomatsakis) [inline src/librustc_typeck/check/mod.rs]: can you add an assertion here that the fn is not const? (and maybe a comment pointing out that this is checked in the AST validator?)

File: src/librustc_typeck/check/mod.rs [hunk 3]
```diff
@@ -819,14 +819,10 @@ pub fn check_item_body<'a,'tcx>(ccx: &CrateCtxt<'a,'tcx>, it: &'tcx hir::Item) {
...
-                    check_trait_fn_not_const(ccx, trait_item.span, sig.constness);
-
                     check_method_body(ccx, &trait_def.generics, sig, body,
                                       trait_item.id, trait_item.span);
                 }
-                hir::MethodTraitItem(ref sig, None) => {
-                    check_trait_fn_not_const(ccx, trait_item.span, sig.constness);
-                }
+                hir::MethodTraitItem(_, None) |
```
Comment (nikomatsakis) [inline src/librustc_typeck/check/mod.rs]: assertion here too

File: src/librustc_typeck/check/mod.rs [hunk 4]
```diff
@@ -1030,9 +1010,7 @@ fn check_impl_items_against_trait<'a, 'tcx>(ccx: &CrateCtxt<'a, 'tcx>,
                          err.emit()
                     }
                 }
-                hir::ImplItemKind::Method(ref sig, ref body) => {
-                    check_trait_fn_not_const(ccx, impl_item.span, sig.constness);
-
+                hir::ImplItemKind::Method(_, ref body) => {
```
Comment (nikomatsakis) [inline src/librustc_typeck/check/mod.rs]: assertion here too

File: src/librustc_passes/ast_validation.rs [hunk 5]
```diff
@@ -68,6 +68,26 @@ impl<'a> AstValidator<'a> {
...
+    fn check_trait_fn_not_const(&self, span: Span, constness: Constness) {
+        match constness {
+            Constness::Const => {
+                // FIXME: This is just a wild guess, since the only accepted const fn
+                //        syntax is `const unsafe fn`, thus we attempt to span only the
+                //        first 5 characters on the function declaration's span.
+                //        Note that using `unsafe const fn` would throw a syntax error.
+                let span = Span {
+                    lo: span.lo,
+                    hi: BytePos(span.lo.0 + 5),
```
Comment (nikomatsakis) [inline src/librustc_passes/ast_validation.rs]: Hmm, I am not very comfortable with this kind of span manipulation. :( It seems like it could easily cause problems when method declarations are created by macros and the like. If we want to track the span of the `Constness`, then I think we should add that into the AST (and/or HIR, as needed).

Comment (nikomatsakis) [inline src/librustc_passes/ast_validation.rs]: (Alternatively, we could leave this as a FIXME (with the unadjusted span))

Comment (KiChjang) [inline src/librustc_passes/ast_validation.rs]: Could you show me where a span is created for an AST/HIR node?

File: src/librustc_typeck/check/mod.rs (hunk 2 above)
Comment (petrochenkov) [inline src/librustc_typeck/check/mod.rs]: But that will cause ICEs in erroneous code - the error in the validation pass is not fatal and compilation continues until type checking is done.

Comment (KiChjang) [inline src/librustc_typeck/check/mod.rs]: Yes, this would cause an ICE with `const unsafe fn`.

**Comment by nikomatsakis** [comment]
@KiChjang 

> Could you show me where a span is created for an AST/HIR node? (probably not doing in this PR, but is good to know nonetheless)

Yes, that is generally in the parser (and, in that context, it's ok to do subtraction of this kind, though always a **bit** sketchy -- but in any case there we know that macro expansion hasn't happened yet, so the spans of different files and so forth are not mixed up). If you look in the parser, you'll see that it tracks `lo` (start points) and so forth and constructs spans and sticks them into various AST/HIR nodes.

If we wanted to track the span of just this keyword, then, I would probably change the AST to have `Spanned<Constness>` instead of `Constness` -- the type-checker will then guide you to the place that you have to add the span in the parser. (You'll also have to make misc changes elsewhere as a result, typically changing `constness` to `constness.node` (to skip past the span).)

**Comment by nikomatsakis** [comment]
OK, sorry, forget the assertions, you're right :)

**Comment by nikomatsakis** [comment]
In that case, can you just add some comments?

**Comment by nikomatsakis** [comment]
Meh, I guess that's not necessary.

**Comment by nikomatsakis** [comment]
(To be clear, I'd still like to see the "span munging" changed.)

**Comment by KiChjang** [comment]
Just a heads up, I've changed my mind. I'll be incorporating the changes to make `Spanned<Constness>` possible.

**Comment by KiChjang** [comment]
Okay, I've made it so that all `Constness` fields in the ast/hir are all `Spanned<Constness>` instead.

**Comment by nikomatsakis** [comment]
@KiChjang this all looks good; one thought is that if you convert the test into a `ui` test, we would be able to see (in the test) that the span is correct (right now the test harness is only checking line-numbers). There is some advice for writing `ui` tests (and generated the reference files) in [`src/test/ui/README.md`](https://github.com/rust-lang/rust/blob/master/src/test/ui/README.md).

What do you think?

**Comment by petrochenkov** [comment]
Adding a span to constness seems pretty random. Why does it have a span while `unsafe`ty doesn't, for example. Many more important AST fragments, like match arms, don't have spans. What is the general policy here?
Spans are heavy enough (`3 * u32`), @KiChjang have you checked if sizes of `Item`/`ImplItem`/`TraitItem` changed? Is an improvement to one error message important enough to pay the price if they did?
(Of course, It would be ideal to have spans for all tokens, but that would blow up the AST/HIR size unless some smart scheme is used, which is not the case now.) 
Also, this is a plugin-breaking change now.

**Comment by jonathandturner** [comment]
@petrochenkov - there can be multiple PRs that address different issues, so a later PR could add a span to `unsafe`, for example.

cc @nikomatsakis - since we were just chatting about AST nodes getting spans.

There may be a cost, which hopefully we can detect and address it if any exists, but the ergonomics of being able to have the spans and give better error messages is helpful.

**Comment by KiChjang** [comment]
@nikomatsakis I'm fine with adding them to this PR, but I think we'll need to make it so that everyone working on #35233 should also write UI tests, if they have tightened the spans for some errors.

**Comment by nikomatsakis** [comment]
@petrochenkov we are already somewhat inconsistent about where we include spans -- e.g., we sometimes put spans on identifiers, sometimes not. It seems... ok to me.

**Comment by nikomatsakis** [comment]
> but I think we'll need to make it so that everyone working on #35233 should also write UI tests, if they have tightened the spans for some errors.

I agree that if we are trying to get some particular span, we should have a `ui` test (I actually think we should at some point migrate all our tests to `ui` tests.)

**Comment by KiChjang** [comment]
UI test added. r? @nikomatsakis

File: src/librustc_passes/ast_validation.rs [hunk 6]
```diff
@@ -68,6 +69,19 @@ impl<'a> AstValidator<'a> {
             }
         }
     }
+
+    fn check_trait_fn_not_const(&self, constness: Spanned<Constness>) {
+        match constness.node {
+            Constness::Const => {
+                // FIXME: Tighten the span so that it is under the const keyword
```
Comment (KiChjang) [inline src/librustc_passes/ast_validation.rs]: Ugh, this comment is still here...

**Comment by jseyfried** [comment]
cc @Manishearth -- I believe this is a plugin-[breaking-change].

**Comment by Manishearth** [comment]
@bors r-

Will be merged in next breaking batch. Which will be soon.

@KiChjang can you go through any diagnostics changes you've planned and let me know if they touch libsyntax's public API -- and, if so, make those changes early?

**Comment by nikomatsakis** [comment]
Ah, shoot, sorry @Manishearth. I am also reminded by some IRC chatter that I had wanted to check on whether the span was needed in both the AST *and* the HIR.

**Comment by nikomatsakis** [comment]
And, indeed, the `ast_validation` pass only operates on the AST, so I guess it is not. In that case, @KiChjang, it's probably better to remove it from HIR -- sorry I didn't comment on it earlier.

**Comment by KiChjang** [comment]
@nikomatsakis No worries, I've already removed them from the HIR in my latest force-push after discussion with @eddyb on IRC.

**Comment by KiChjang** [comment]
Rebased.

File: src/libsyntax/parse/parser.rs [hunk 7]
```diff
@@ -4752,18 +4752,21 @@ impl<'a> Parser<'a> {
...
-            (Constness::Const, unsafety, Abi::Rust)
+            (respan(const_span, Constness::Const), unsafety, Abi::Rust)
         } else {
             let abi = if self.eat_keyword(keywords::Extern) {
                 self.parse_opt_abi()?.unwrap_or(Abi::C)
             } else {
                 Abi::Rust
             };
-            (Constness::NotConst, unsafety, abi)
+            (dummy_spanned(Constness::NotConst), unsafety, abi)
```
Comment (nikomatsakis) [inline src/libsyntax/parse/parser.rs]: Just noticed this -- it seems like it would be better to use some other span here besides the dummy span. For example, the span of the `fn` keyword seems not terrible. I think we try to avoid having dummy spans in the AST itself.

File: src/libsyntax/parse/parser.rs [hunk 8]
```diff
@@ -5665,7 +5668,9 @@ impl<'a> Parser<'a> {
                 // EXTERN FUNCTION ITEM
                 let abi = opt_abi.unwrap_or(Abi::C);
                 let (ident, item_, extra_attrs) =
-                    self.parse_item_fn(Unsafety::Normal, Constness::NotConst, abi)?;
+                    self.parse_item_fn(Unsafety::Normal,
+                                       dummy_spanned(Constness::NotConst),
```
Comment (nikomatsakis) [inline src/libsyntax/parse/parser.rs]: Also here.

File: src/libsyntax/parse/parser.rs [hunk 9]
```diff
@@ -5775,7 +5783,9 @@ impl<'a> Parser<'a> {
             // FUNCTION ITEM
             self.bump();
             let (ident, item_, extra_attrs) =
-                self.parse_item_fn(Unsafety::Normal, Constness::NotConst, Abi::Rust)?;
+                self.parse_item_fn(Unsafety::Normal,
+                                   dummy_spanned(Constness::NotConst),
```
Comment (nikomatsakis) [inline src/libsyntax/parse/parser.rs]: Also here.

File: src/libsyntax/parse/parser.rs [hunk 10]
```diff
@@ -5796,7 +5806,9 @@ impl<'a> Parser<'a> {
             };
             self.expect_keyword(keywords::Fn)?;
             let (ident, item_, extra_attrs) =
-                self.parse_item_fn(Unsafety::Unsafe, Constness::NotConst, abi)?;
+                self.parse_item_fn(Unsafety::Unsafe,
+                                   dummy_spanned(Constness::NotConst),
```
Comment (nikomatsakis) [inline src/libsyntax/parse/parser.rs]: Also here.

**Comment by KiChjang** [comment]
Dummy spans removed from `parser.rs`.

**Comment by KiChjang** [comment]
Rebased.

**Comment by jonathandturner** [comment]
Huh, looks like a test in the `src/libsyntax/parse/mod.rs` needs updating?

```
test parse::tests::parse_fundecl ... FAILED
```

**Comment by KiChjang** [comment]
Fixed the unit test in the latest force-push.

**Comment by jseyfried** [comment]
@bors r-
This is a syntax-[breaking-change] and will land in the next batch (c.f. https://github.com/rust-lang/rust/issues/31645#issuecomment-239228452).
