### PR TITLE
Fix integer overflow in rotate_left

### LINKED ISSUE #61406: integer overflow in CTFE implementation of rotate_left
The following code ICEs when compiled with a rustc with debug-assertions enabled:
```rust
const X: i16 = 0i16.rotate_left(124);
```

The problem is in the implementation of `rotate_left`, specifically in this line: https://github.com/rust-lang/rust/blob/75f464481ed8c924086fc0b9a2d31841bbdbcabd/src/librustc_mir/interpret/intrinsics.rs#L197
The subtraction overflows here.

Cc @oli-obk

### PR DESCRIPTION
**Pull request by tesuji**
Closes #61406
r? @RalfJung

### CODE REVIEW

File: src/test/ui/consts/const-int-rotate.rs [hunk 1]
```diff
@@ -3,4 +3,5 @@ fn main() {
     //~^ ERROR temporary value dropped while borrowed
     let y: &'static i32 = &(5_i32.rotate_right(3));
     //~^ ERROR temporary value dropped while borrowed
+    assert_eq!(0i16.rotate_left(124), 0);
```
Comment (RalfJung) [inline src/test/ui/consts/const-int-rotate.rs]: Uh, this is weird. @oli-obk what kind of test is this? I thought it would test functionality for rotate in CTFE but that does not seem to be the case. Do we have any test that does that?

@lzutao 	in any case, we want to test functionality here, so please move the actual call to within a `const` item. Something like
```rust
const X: i16 = 0i16.rotate_left(124);
```

Comment (oli-obk) [reply src/test/ui/consts/const-int-rotate.rs]: The above code just checks that we don't promote calls to the `rotate_*` methods. The actual tests are in https://github.com/rust-lang/rust/blob/9ebf47851a357faa4cd97f4b1dc7835f6376e639/src/test/run-pass/const-int-rotate.rs

Comment (RalfJung) [reply src/test/ui/consts/const-int-rotate.rs]: Ah, thanks!

Both this test here and that one suffer for a severe lack of comments (e.g. for stuff like the `ident` function).

**Comment by RalfJung** [comment]
@lzutao 	so please move the new test to `src/test/run-pass/const-int-rotate.rs`. Please also add a test for `rotate_right`.  See [this](https://github.com/rust-lang/rust/blob/d461555e443a07bc75564b8322dc461efe7cea7c/src/libcore/tests/num/int_macros.rs#L92) for some inspiration for test cases.

**Comment by lzutao** [comment]
@RalfJung I think this PR is ready for review again.

**Comment by RalfJung** [comment]
This looks great, thanks a lot!

@bors r+

**Comment by RalfJung** [comment]
Actually could you squash the commits and remove the "WIP" from the commit message?

@bors r-

**Comment by lzutao** [comment]
Ping again, I squashed those two commits.

**Comment by RalfJung** [comment]
Awesome!

@bors r+
