### PR TITLE
Check if format argument is identifier to avoid error err-emit

### LINKED ISSUE #139104: Invalid format string with certain fill characters yields incorrect suggestion
The following line that's missing an alignment specifier between the (intended) fill character `_` and width+precision `1.4`:

```Rust
println!("{foo:_1.4}", foo = 3.14);
```

makes the compiler think we're trying to access a tuple field and helpfully but incorrectly suggests replacing it with 

```Rust
println!("{0}", foo:_1.4, foo = 3.14);
```

which is, of course, invalid syntax. The same holds for any alphabetic character as well as `.`.

### Current output

```text
error: invalid format string: tuple index access isn't supported
 --> src/main.rs:4:16
  |
4 |     println!("{foo:_1.4}", foo = 3.14);
  |                ^^^^^^^^ not supported in format string
  |
help: consider using a positional formatting argument instead
  |
4 |     println!("{0}", foo:_1.4, foo = 3.14);
  |                ~  ++++++++++
```

### Desired output

```text
error: invalid format string: invalid alignment specifier
 --> src/main.rs:4:16
  |
4 |     println!("{foo:_1.4}", foo = 3.14);
  |                    ^ not supported in format string
  |
help: if you're trying to use a fill character, it must be followed by one of `<` `>` `^`
  |
4 |     println!("{foo:_>1.4}", foo = 3.14);
  |                     +
```

### Other cases

Using a non-alphanumeric fill character that's not `[._+-]` yields a different error message that is not incorrect but is perhaps not very helpful:

```text
error: invalid format string: expected `}`, found `*`
 --> src/main.rs:4:20
  |
4 |     println!("{foo:*10.4}", foo = 3.14);
  |               -    ^ expected `}` in format string
  |               |
  |               because of this opening brace
  |
  = note: if you intended to print `{`, you can escape it using `{{`
```

### Rust Version

```Shell
rustc 1.85.1 (4eb161250 2025-03-15)
binary: rustc
commit-hash: 4eb161250e340c8f48f66e2b929ef4a5bed7c181
commit-date: 2025-03-15
host: x86_64-apple-darwin
release: 1.85.1
LLVM version: 19.1.7
```

### PR DESCRIPTION
**Pull request by xizheyin**
Fixes #139104

When `argument` is not an identifier, it should not be considered a field access. I checked this and if not emit an invalid format string error. I think we could do with a little finer error handling, I'll open an issue to track this down later.

The first commit submits the ui test, the second commits the code and the changes to the test output.

r? compiler

### CODE REVIEW

File: compiler/rustc_parse_format/src/lib.rs [hunk 1]
```diff
@@ -894,52 +918,73 @@ impl<'a> Parser<'a> {
...
+                                    secondary_label: None,
+                                    suggestion: Suggestion::UsePositional,
+                                },
+                            );
+                        }
+                        _ => {}
+                    };
+                }
             }
+        } else if matches!(arg.position, ArgumentNamed(_) | ArgumentIs(_)) {
```
[the remark this answers is not in the document]
Comment (lcnr) [reply compiler/rustc_parse_format/src/lib.rs:970]: please move this out of this function. Te function is called `suggest_positional_arg_instead_of_captured_arg` and here you're certainly not suggesting a positional arg.

[the remark this answers is not in the document]
Comment (xizheyin) [reply compiler/rustc_parse_format/src/lib.rs]: Ok, I revised it.

File: tests/ui/parser/issues/invalid-parse-format-issue-139104.rs [hunk 2]
```diff
@@ -0,0 +1,8 @@
+fn main() {
+    println!("{foo:_1.4}", foo = 3.14); //~ ERROR invalid format string: invalid format string for argument `foo`
+    println!("{foo:1.4_1.4}", foo = 3.14); //~ ERROR invalid format string: invalid format string for argument `foo`
+    println!("xxx{0:_1.4}", 1.11); //~ ERROR invalid format string: invalid format string for argument at index `0`
+    println!("{foo:_1.4", foo = 3.14); //~ ERROR invalid format string: invalid format string for argument `foo`
+    println!("xxx{0:_1.4", 1.11); //~ ERROR invalid format string: invalid format string for argument at index `0`
+    println!("xxx{  0", 1.11); //~ ERROR invalid format string: expected `}`, found `0`
```
Comment (lcnr) [inline tests/ui/parser/issues/invalid-parse-format-issue-139104.rs:7]: also test `{:_1.4}` or whatever? i.e. an implicit positional argument

File: compiler/rustc_parse_format/src/lib.rs [hunk 3]
```diff
@@ -893,54 +921,82 @@ impl<'a> Parser<'a> {
...
+                        }
+                        _ => {}
+                    };
+                }
             }
         }
+        false
+    }
+
+    fn report_invalid_format_string(&mut self, arg: Argument<'a>) {
```
Comment (lcnr) [inline compiler/rustc_parse_format/src/lib.rs:980]: so this changes the error from "expected `}`" to "invalid format string"?

I feel like we should change `errors` to just be an `Option` or a `Result<(), ParseError>` to make this clear. I feel like the current setup is deeply confusing. We've got some places which `push` to the `Vec` which is just a noop if there's already a previous error, but that's far from clear when reading the code



I have to say, the way `rustc_parse_format` handles errors is quite weird xx

we only ever use the first error in diagnostics, so inserting a new error at index 0 simply drops the previously emitted error.

Comment (xizheyin) [reply compiler/rustc_parse_format/src/lib.rs:980]: Yes, maybe we can open an issue to clean up that part of the error handling.

Comment (lcnr) [reply compiler/rustc_parse_format/src/lib.rs:980]: separately, I feel like this is not necessarily an improvement over the "expected `}`" error we would otherwise emit. That error is useful in telling you which part of the format specifier is unexpected. Now with `{foo:_1.4}` I have no indication for why it is invalid.

Comment (lcnr) [reply compiler/rustc_parse_format/src/lib.rs:980]: I would r+ this change with `report_invalid_format_string` removed.

While the new error is not necessarily worse, it adds a bit of complexity and I feel like there's probably a better structure for how to deal with errors here and having a more involved starting point makes getting there harder.

Comment (xizheyin) [reply compiler/rustc_parse_format/src/lib.rs:980]: OK, thanks for your insight.

File: compiler/rustc_parse_format/src/lib.rs [hunk 4]
```diff
@@ -894,6 +918,11 @@ impl<'a> Parser<'a> {
     }
 
     fn suggest_positional_arg_instead_of_captured_arg(&mut self, arg: Argument<'a>) {
+        // If the argument is not an identifier, it is not a field access.
+        if !arg.is_identifier() {
+            return;
+        }
+
```
Comment (xizheyin) [inline compiler/rustc_parse_format/src/lib.rs:925]: Now, the only change I made based on original code was a check at the beginning of the `support_positional_arg_instead_of_captured_arg`.

File: tests/ui/parser/issues/invalid-parse-format-issue-139104.rs [hunk 5]
```diff
@@ -0,0 +1,13 @@
+fn main() {
+    println!("{foo:_1.4}", foo = 3.14); //~ ERROR invalid format string: expected `}`, found `.`
+    println!("{0:_1.4}", 1.11); //~ ERROR invalid format string: expected `}`, found `.`
+    println!("{:_1.4}", 3.14); //~ ERROR invalid format string: expected `}`, found `.`
```
Comment (xizheyin) [inline tests/ui/parser/issues/invalid-parse-format-issue-139104.rs:4]: And I added some new tests to check implicit arguments. These includes `index args`, `named args`, `implicit args`.

**Comment by lcnr** [comment]
Thanks :+1: 

@bors r+ rollup
