### PR TITLE
Don't lint 'unused_parens` on `if (break _) { .. }`

### LINKED ISSUE #54704: Incorrect suggestion to remove parentheses around if-condition containing break
```rust
#![allow(unreachable_code)]

fn f() -> bool {
    loop {
        if (break { return true }) {
        }
    }
    false
}

fn g() -> bool {
    loop {
        if break { return true } {
        }
    }
    false
}

fn main() {
    println!("f={} g={}", f(), g());
}
```

```console
f=true g=false
```

Rustc 1.30.0-nightly (bb0896af1 2018-09-29) suggests turning `f` into `g`, which changes the meaning of the program.

```console

```warning: unnecessary parentheses around `if` condition
 --> src/main.rs:5:12
  |
5 |         if (break { return true }) {
  |            ^^^^^^^^^^^^^^^^^^^^^^^ help: remove these parentheses
  |
  = note: #[warn(unused_parens)] on by default

### PR DESCRIPTION
**Pull request by llogiq**
This fixes #54704

### CODE REVIEW

**Comment by nikomatsakis** [comment]
Travis is still pretty grumpy.

**Comment by llogiq** [comment]
Sorry about that, I failed to commit the changed .stderr – will do that once I get to a PC with a stable connection.

**Comment by llogiq** [comment]
Travis is now happy.

**Comment by kleimkuhler** [comment]
This will likely introduce a merge conflict with https://github.com/rust-lang/rust/pull/54820 just a heads up! I don't mind on the order these go in; I think both will be pretty easy to rebase from.

File: src/librustc_lint/unused.rs [hunk 1]
```diff
@@ -270,47 +270,52 @@ impl UnusedParens {
...
-                err.span_suggestion_short_with_applicability(
-                    value.span,
-                    "remove these parentheses",
-                    parens_removed,
-                    Applicability::MachineApplicable
-                );
-                err.emit();
+            if struct_lit_needs_parens &&
+                    (parser::contains_exterior_struct_lit(&inner) ||
+                        if let ast::ExprKind::Break(..) = inner.node {
```
Comment (kleimkuhler) [inline src/librustc_lint/unused.rs]: @llogiq You can probably simplify this whole block down to `... || inner.node == ast::ExprKind::Break`

Comment (kleimkuhler) [inline src/librustc_lint/unused.rs]: You can probably simplify this addition down to `... || inner.node == ast::ExprKind::Break`

Comment (llogiq) [reply src/librustc_lint/unused.rs]: That would be surprising to say the least, because `ExprKind::Break` is defined as a tuple struct of two values (note the two dots). I didn't know you could compare with incomplete value definitions.

Comment (kleimkuhler) [reply src/librustc_lint/unused.rs]: Sorry yes you may still need the two dots! What I was trying to point out is that you can just check if `inner.node` is a `ExprKind::Break` as the _whole_ condition and get ride of the `... { true } else { false }`.

Comment (llogiq) [reply src/librustc_lint/unused.rs]: How would that work? The `if let` needs some values in the then/else branches.

Comment (kleimkuhler) [reply src/librustc_lint/unused.rs]: Ah yes I see what you mean. I was under the impression we could get a `bool` from `inner.node == ast::ExprKind::Break(..)`. What I was mainly hoping to simplify in all this was getting rid of the additional `... { true } else { false }` as it just looks a little odd to read.

A way I see doing that is keeping things how they were (with `necessary`) and going for something like adding those additional four lines to check for a `Break`.
```
let necessary = struct_lit_needs_parens && parser::contains_exterior_struct_lit(&inner);
if !necessary {
+    // We don't want to lint when there is a `break` in `inner`
+    if let ast::ExprKind::Break(..) = inner.node {
+        return
+    }
    ...
}
```
Either way - just an initial reaction I had to seeing the new additions! I'm fine keeping it how it is.

**Comment by llogiq** [comment]
@nikomatsakis r?

File: src/librustc_lint/unused.rs (hunk 1 above)
Comment (nikomatsakis) [inline src/librustc_lint/unused.rs]: Nit: I'd prefer to see this `if let` captured into a temporary value, or perhaps with a helper function. This is a pretty complex conditional! Maybe even break it into a `if`

File: src/librustc_lint/unused.rs [hunk 2]
```diff
@@ -270,47 +270,52 @@ impl UnusedParens {
                                 msg: &str,
                                 struct_lit_needs_parens: bool) {
```
Comment (nikomatsakis) [inline src/librustc_lint/unused.rs]: Nit: this name no longer seems very accurate; let's call it something like `is_restricted_expr: bool` perhaps? And I think a comment on `check_unused_parens_core` would be good. Something like:

---

Invoked on expressions that appear in places where people traditionally put parentheses out of habit, but where they are not needed in Rust. For example, `if (a == b) { .. }`. Issues a lint if `value` is a parenthesized node, unless those parentheses are deemed "necessary".

Parentheses are considered necessary if (a) `is_restricted_expr` is true, which indicates that this is a context (such as an `if`) where only a subset of expressions are permitted and (b) the parenthesized expression falls outside of that subset. So e.g. `if (Foo { a: 22 }) { .. }` would not get a warning; similarly `while (break) { .. }` would not.

**Review by nikomatsakis — CHANGES_REQUESTED** [review]
r=me with nits below fixed

File: src/librustc_lint/unused.rs (hunk 1 above)
Comment (llogiq) [reply src/librustc_lint/unused.rs]: That'd be a pity; I just found a way to use a `return` instead of a boolean that would shorten the code considerably. But I can (and should) add a comment why we don't lint on `break` here.

Comment (nikomatsakis) [reply src/librustc_lint/unused.rs]: I don't follow what would be a pity...? I was just suggesting reformatting things

Comment (llogiq) [reply src/librustc_lint/unused.rs]: Sorry, I've been busy lately. I'll revisit and rebase this later this week.

**Comment by llogiq** [comment]
Rebased on current master, this time I could piggy-back on the recent changes to the lint.

**Review by nikomatsakis — APPROVED** [review]
