### PR TITLE
Don't emit "is not a logical operator" error outside of associative expressions

### LINKED ISSUE #75599: Regression involving "is not a logical operator" in match
The following used to work from rust 1.0.0 through 1.41.0, but has been failing to compile since 1.42.0. I believe the ```"`and` is not a logical operator"``` diagnostic is being overzealous and should not be triggering on this program.

```rust
mod or {
    pub const ID: usize = 0;
}

mod and {
    pub const ID: usize = 1;
}

fn main() {
    match 0 {
        or::ID => {}
        and::ID => {}
        _ => {}
    }
}
```

```console
error: `and` is not a logical operator
  --> src/main.rs:12:9
   |
12 |         and::ID => {}
   |         ^^^ help: use `&&` to perform logical conjunction
   |
   = note: unlike in e.g., python and PHP, `&&` and `||` are used for logical operators
```

### PR DESCRIPTION
**Pull request by tgnottingham**
Avoid showing this error where it doesn't make sense by not assuming
"and" and "or" were intended to mean "&&" and "||" until after we decide
to continue parsing input as an associative expression.

Note that the decision of whether or not to continue parsing input as an
associative expression doesn't actually depend on this assumption.

Fixes #75599

---

First time contributor! Let me know if there are any conventions or policies I should be following that I missed here. Thanks :)

### CODE REVIEW

**Comment by tgnottingham** [comment]
r? @estebank 

Hi @estebank, thought you might be the best person to review, since you've touched this part of the code recently.

---

Also, want to point out that, with this change, code like this...

```
fn foo(a: Option<u32>, b: Option<u32>) -> bool {
    if let Some(x) = a { true } else { false }
    and
    if let Some(y) = a { true } else { false }
}
```

...will no longer generate the suggestion to replace "and" with "&&". But it still suggests using parens to turn the construct into an expression, and after you do that, you will get the "and" ->  "&&" suggestion.

File: src/test/ui/issues/issue-75599.rs [hunk 1]
```diff
@@ -0,0 +1,24 @@
+// run-pass
```
Comment (jyn514) [inline src/test/ui/issues/issue-75599.rs:1]:
```suggestion
// check-pass
```
No need to run it, it's only there for the diagnostics.

Comment (tgnottingham) [reply src/test/ui/issues/issue-75599.rs]: Thanks!

**Comment by estebank** [comment]
This looks good to me. Can you squash the two commits? r=me after that.

**Comment by estebank** [comment]
> But it does show the exact same errors as before, sans the "and" -> "&&" suggestion. Not sure if this is a deal-breaker.

That is unfortunate, but at the same time the code is far away from correct enough for us to accept the lack of helpful suggestions.

**Comment by tgnottingham** [comment]
Squashed the commits. Thanks @estebank.
