### PR TITLE
instantiate_value_path: on `SelfCtor`, avoid unconstrained tyvars

### LINKED ISSUE #69306: Inconsistent Self behavior with generic structs
Summary from @pnkfelix : `Self` used as a tuple-struct constructor function should use the fully type-substituted form from the `impl` block, but does not.

Thus, today this code is accepted, but it should not be.

```rust
struct _Bar<T>(T);

impl<T> _Bar<T> {
    fn _map1<U>(x: U) -> _Bar<U> {
        Self(x)
    }
}
```

(Fixing this would be a breaking-change, so we should take care in how we deploy it.)

Original bug report follows:

----

I tried this code:

```rust
struct _Foo<T> {
    x: T
}

impl<T> _Foo<T> {
    fn _map<U>(x: U) -> _Foo<U> {
        Self { x }
    }
}

struct _Bar<T>(T);

impl<T> _Bar<T> {
    fn _map<U>(x: U) -> _Bar<U> {
        Self(x)
    }
}
```

In nightly rustc, `_Bar` compiles while `_Foo` yields a type mismatch error:

```
error[E0308]: mismatched types
  --> src/main.rs:10:16
   |
8  | impl<T> _Foo<T> {
   |      - expected type parameter
9  |     fn _map<U>(x: U) -> _Foo<U> {
   |             - found type parameter
10 |         Self { x }
   |                ^ expected type parameter `T`, found type parameter `U`
   |
```

### PR DESCRIPTION
**Pull request by Centril**
Fixes https://github.com/rust-lang/rust/issues/69306.

On `Self(...)` (that is, a `Res::SelfCtor`), do not use `self.impl_self_ty(...)`. The problem with that method is that it creates unconstrained inference variables for type parameters in the `impl` (e.g. `impl<T> S0<T>`). These variables then eventually get substituted for something else when they come in contact with the expected type (e.g. `S0<u8>`) or merely the arguments passed to the tuple constructor (e.g. the `0` in `Self(0)`).

Instead of using `self.impl_self_ty(...)`, we instead merely use `let ty = self.normalize_ty(span, tcx.at(span).type_of(impl_def_id));` to get the rewritten `res`.

r? @eddyb

### CODE REVIEW

**Comment by eddyb** [comment]
> ... do not use `self.impl_self_ty` ...
> The problem with that method is that it creates unconstrained inference variables for type parameters in the `impl`

Wait what? That's not what the name would suggest... If it creates inference variables it should have `instantiate` in the name IMO.

File: src/librustc_typeck/check/mod.rs [hunk 1]
```diff
@@ -5465,9 +5465,7 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
             .unwrap_or(false);
 
         let (res, self_ctor_substs) = if let Res::SelfCtor(impl_def_id) = res {
-            let ty = self.impl_self_ty(span, impl_def_id).ty;
```
Comment (eddyb) [inline src/librustc_typeck/check/mod.rs]: Okay, I see, the `.ty` should've been a big warning flag (the other field is... `substs`).

Can you also change the call sites in `check::method::suggest` to just use `tcx.type_of(impl_def_id)`?
And then maybe inline `impl_self_ty` into the only remaining use site (which is in `check::method::confirm`?).

If `impl_self_ty` was used more widely in `check::method` I'd suggest renaming it to `instantiate_impl_self_ty` *and* make it private to `check::method`. But it's not, so might as well get rid of it before this happens again.

**Comment by Centril** [comment]
Note to self: Investigate whether this should be `self.normalize_ty(tcx.type_of(...))` so that if the `Self` type is a projection or some such, we normalize it before seeing whether the normalized type is an ADT. (Also add a test case.)

**Comment by Centril** [comment]
@craterbot check

**Comment by Centril** [comment]
Crater triage:
- There are 6 root regressions.
   - 1 was in my own crate and has already been fixed (with a point release).
   - All the others have PRs open fixing the problem.

File: src/librustc_typeck/check/mod.rs (hunk 1 above)
Comment (Centril) [reply src/librustc_typeck/check/mod.rs]: I would prefer not dealing with it in this PR. I've filed https://github.com/rust-lang/rust/issues/69489 for the follow-up.

**Comment by Centril** [comment]
I added a call to `normalize_ty` as well to handle projections, as this was previously allowed, and is allowed when using `Self { ... }`.

I believe this should be ready to go as there's a single remaining regression which has an open PR.
r? @petrochenkov

**Comment by pnkfelix** [comment]
discussed at T-compiler meeting. Delaying question of whether to beta backport to next week's meeting.

**Comment by nikomatsakis** [comment]
@bors r+

My two cents:

The change would be difficult, from a technical perspective, to do a future-compatibility warning for.

The impact is non-trivial but manageable, and @Centril did a great job of opening PRs (which have been merged). However, this doesn't mean we're "all set", as those changes still have to make their way into new releases (ideally, point releases), and that usually takes some time.

I'm inclined to approve this, but I think we want to be on the lookout for bug reports from folks that are affected "in the wild". 

I'm somewhat inclined *not* to backport, so as to give people a bit more time to adapt before it reaches a stable release, but it depends on how many regression reports we receive after landing.

**Comment by pnkfelix** [comment]
discussed in T-compiler meeting. declined for beta-backport.
