### PR TITLE
Don't put Cargo into the rustc workspace

### LINKED ISSUE #40284: error: failed to read src/tools/cargo/Cargo.toml
```
$ make -j4 && make install
error: failed to read `/home/cesarb/opt/rust-git/src/rust/src/tools/cargo/Cargo.toml`

Caused by:
  No such file or directory (os error 2)
Build completed unsuccessfully in 0:00:00
Makefile:24: recipe for target 'all' failed
make: *** [all] Error 101
$ git rev-parse --short HEAD
65e2a14
$ ls src/tools/cargo
$ 
```

The `src/tools/cargo` directory is empty. Cleaning the checkout (with `git clean -f -x -d`) and running `configure` again didn't fix it.

Configure command line: `./configure --prefix=/home/cesarb/opt/rust-git --android-cross-path=/home/cesarb/android-sdks/temp/arm-linux-androideabi --target=x86_64-unknown-linux-gnu,i686-unknown-linux-gnu,x86_64-pc-windows-gnu,arm-linux-androideabi,armv7-linux-androideabi`

### PR DESCRIPTION
**Pull request by alexcrichton**
This causes problems when first cloning and bootstrapping the repository
unfortunately, so let's ensure that Cargo sticks around in its own workspace.
Because Cargo is a submodule it's not available by default on the inital clone
of the rust-lang/rust repository. Normally it's the responsibility of the
rustbuild to take care of this, but unfortunately to build rustbuild itself we
need to resolve the workspace conflicts.

To deal with this we'll just have to ensure that all submodules are in their own
workspace, which sort of makes sense anyway as updates to dependencies as
bugfixes to Cargo should go to rust-lang/cargo instead of rust-lang/rust. In any
case this commit removes Cargo from the global workspace which should resolve
the issues that we've been seeing.

To actually perform this the `cargo` submodule has been moved to a new `vendor`
directory to ensure it's outside the scope of `src/Cargo.toml` as a workspace.

Closes https://github.com/rust-lang/rust/issues/40284

### CODE REVIEW

**Comment by brson** [comment]
This likes like it's putting a submodule into src/vendor, which does not seem like a suitable place for submodules. Why src/vendor?

**Comment by alexcrichton** [comment]
Ah yeah unfortunately `src/vendor` won't work b/c it's hierarchically below `src/Cargo.toml`, which means it still tries to be part of the workspace. 

I could send a commit to Cargo with `[workspace]` which I believe will disable this though, if you'd prefer. I thought though at some point we were gonna try and wrangle all our third-party deps in `vendor/*`, although I may be misremembering.

**Comment by brson** [comment]
If the options are putting this in src/vendor or giving cargo its own workspace I prefer the latter. We wouldn't put all the other submodules into src/vendor, or the other tools, I think - istm src/vendor is purely for incidental dependencies, not for the actual tools that are part of Rust.

**Comment by alexcrichton** [comment]
Unfortunately I can't [give Cargo it's own workspace](https://github.com/rust-lang/cargo/pull/3801) due to [CI errors](https://travis-ci.org/rust-lang/cargo/jobs/208377916) caused by [existing bugs in Cargo](https://github.com/rust-lang/cargo/issues/3192).

That to me means the only solution is to put Cargo in some external directory for now. I hope to fix https://github.com/rust-lang/cargo/issues/3192 soon though which I believe should allow us to get the "ideal" hierarchy in the future.

@brson how do you feel about `vendor` (not `src/vendor`, just `vendor`) in the meantime?

File: src/bootstrap/step.rs [hunk 1]
```diff
@@ -559,7 +559,7 @@ pub fn build_rules<'a>(build: &'a Build) -> Rules {
     rules.build("tool-qemu-test-client", "src/tools/qemu-test-client")
          .dep(|s| s.name("libstd"))
          .run(move |s| compile::tool(build, s.stage, s.target, "qemu-test-client"));
-    rules.build("tool-cargo", "src/tools/cargo")
+    rules.build("tool-cargo", "vendor/cargo")
```
Comment (brson) [inline src/bootstrap/step.rs]: Do you really mean "vendor/" here?

**Comment by brson** [comment]
r=me with comment addressed

**Comment by alexcrichton** [comment]
For posterity, we decided to put cargo into a top-level dir for now. That's not scalable but we'll fix the bug in Cargo soon which prevents Cargo from going into a "proper" location.

**Comment by alexcrichton** [comment]
@bors: p=1

We're not getting nightlies because of this
