### PR TITLE
suggest `;` on expr `mac!()` which is good as stmt `mac!()`

### LINKED ISSUE #34421: error message for macro in wrong context is missing context
This is a regression from stable to beta and nightly.

This code is wrong (missing semicolons):

``` rust
macro_rules! make_item {
    ($a:ident) => { struct $a; }
}

fn a() { make_item!(A) }
fn b() { make_item!(B) }
```

Stable prints:

```
<anon>:2:21: 2:27 error: expected identifier, found keyword `struct`
<anon>:2     ($a:ident) => { struct $a; }
                             ^~~~~~
<anon>:5:21: 5:22 error: macro expansion ignores token `A` and any following
<anon>:5 fn a() { make_item!(A) }
                             ^
<anon>:5:10: 5:23 note: caused by the macro expansion here; the usage of `make_item!` is likely invalid in expression context
<anon>:5 fn a() { make_item!(A) }
                  ^~~~~~~~~~~~~
<anon>:2:21: 2:27 error: expected identifier, found keyword `struct`
<anon>:2     ($a:ident) => { struct $a; }
                             ^~~~~~
<anon>:6:21: 6:22 error: macro expansion ignores token `B` and any following
<anon>:6 fn b() { make_item!(B) }
                             ^
<anon>:6:10: 6:23 note: caused by the macro expansion here; the usage of `make_item!` is likely invalid in expression context
<anon>:6 fn b() { make_item!(B) }
                  ^~~~~~~~~~~~~
error: aborting due to 4 previous errors
```

Beta and nightly both print:

```
error: expected expression, found keyword `struct`
 --> <anon>:2:21
  |>
2 |>     ($a:ident) => { struct $a; }
  |>                     ^^^^^^
```

Notice that not only is all the useful information gone, but the compiler aborts after the first error instead of finding the rest. It does not matter whether `RUST_NEW_ERROR_FORMAT` is on or off.

cc @nikomatsakis @jonathandturner

### PR DESCRIPTION
**Pull request by Centril**
Fixes https://github.com/rust-lang/rust/issues/34421 by implementing @jseyfried's suggestion in https://github.com/rust-lang/rust/issues/34421#issuecomment-301578683.

r? @petrochenkov

### CODE REVIEW

File: src/librustc_expand/mbe/macro_rules.rs [hunk 1]
```diff
@@ -126,10 +143,11 @@ fn emit_frag_parse_err(
 impl<'a> ParserAnyMacro<'a> {
     crate fn make(mut self: Box<ParserAnyMacro<'a>>, kind: AstFragmentKind) -> AstFragment {
         let ParserAnyMacro { site_span, macro_ident, ref mut parser, arm_span } = *self;
+        let snapshot = &mut parser.clone();
```
Comment (Centril) [inline src/librustc_expand/mbe/macro_rules.rs]: This is the main trade-off in this logic, but it doesn't seem all too costly.

Comment (estebank) [reply src/librustc_expand/mbe/macro_rules.rs]: Can we perf it? I'm intrigued to see the effects of this change in the `syn` case.

File: src/test/ui/macros/macro-in-expression-context-2.stderr [hunk 2]
```diff
@@ -5,7 +5,15 @@ LL | macro_rules! empty { () => () }
    |                            -- in this macro arm
 ...
 LL |         _ => { empty!() }
-   |                ^^^^^^^^ expected expression
+   |                ^^^^^^^^
+   |                |
+   |                expected expression
+   |                this macro call doesn't expand to an expression, but it does to a statement
```
Comment (estebank) [inline src/test/ui/macros/macro-in-expression-context-2.stderr]: "but it does to a statement" sounds like it could be confusing to people (mainly ESL). Maybe we can add a bit of redundancy to the copy or make it a `note` so that we don't worry about its length? Maybe:

```
  = note: the macro call doesn't expand to an expression, but it can expand to a statement
```

File: src/librustc_expand/mbe/macro_rules.rs [hunk 3]
```diff
@@ -118,6 +119,22 @@ fn emit_frag_parse_err(
...
+                    "this macro call doesn't expand to an expression, but it does to a statement",
+                );
+                e.span_suggestion_verbose(
+                    site_span.shrink_to_hi(),
+                    "add `;` to interpret the expansion as a statement",
+                    ";".to_string(),
+                    Applicability::MaybeIncorrect,
+                );
+            }
+        },
```
Comment (estebank) [inline src/librustc_expand/mbe/macro_rules.rs]: Should we attempt recovery in the success case?

**Comment by petrochenkov** [comment]
I'm ok with this if perf is unaffected, but I don't care to much about fixing this because the example should compile successfully in the token-based expansion model.

r? @estebank

**Comment by Centril** [comment]
Perfbot suggests this was a perf win but I suspect that's bogus. At least it's not a regression, so I'll make the other requested changes. :)

File: src/librustc_expand/mbe/macro_rules.rs (hunk 3 above)
Comment (Centril) [reply src/librustc_expand/mbe/macro_rules.rs]: We already do as the caller of this function does `return kind.dummy(...);`.

File: src/librustc_expand/mbe/macro_rules.rs (hunk 1 above)
Comment (Centril) [reply src/librustc_expand/mbe/macro_rules.rs]: Perfbot says it was a win; I'm inclined not to trust that, but I don't think it's a regression either based on that data.

File: src/test/ui/macros/macro-in-expression-context-2.stderr (hunk 2 above)
Comment (Centril) [reply src/test/ui/macros/macro-in-expression-context-2.stderr]: I'll make it a note. :)

**Comment by Centril** [comment]
@estebank I've addressed your comments. :)
