### PR TITLE
Fix wrong span for hightlight for duplicated diff lines

### LINKED ISSUE #147070: Red highlighting in the wrong spot in the "help: remove the extra argument" message
The one time where a screenshot is needed rather than copy-pasting the output! 🤣 

### Code

When I attempt to compile:

```Rust
struct Thingie;

impl Thingie {
    pub(crate) fn new(
        _a: String,
        _b: String,
        _c: String,
        _d: String,
        _e: String,
        _f: String,
    ) -> Self {
        unimplemented!()
    }
}

fn main() {
    let foo = Thingie::new(
        String::from(""),
        String::from(""),
        String::from(""),
        String::from(""),
        String::from(""),
        String::from(""),
        String::from(""),
    );
}
```

### Current output

I'm seeing this, note the "n" in "argument" that's highlighted:

Image

### Desired output

I think the intention is for the whole `23 -         String::from(""),` line to be red?

When I change the code to:

```
fn main() {
    let foo = Thingie::new(
        String::from("a"),
        String::from("b"),
        String::from("c"),
        String::from("d"),
        String::from("e"),
        String::from("f"),
        String::from("g"),
    );
}
```

then I see this:

Image

Which is also weird? Why is the comma on the previous line red instead of the line that needs to be removed?

### Other cases

I have some proprietary code that whenever I try to reduce or obfuscate it, the behavior goes away, but instead of just an "n" I'm seeing "he extra argument" in red:

Image

### Rust Version

I'm seeing this behavior with stable, beta, and nightly as follows:

```Shell
❯ rustc +stable --version --verbose
rustc 1.90.0 (1159e78c4 2025-09-14)
binary: rustc
commit-hash: 1159e78c4747b02ef996e55082b704c09b970588
commit-date: 2025-09-14
host: aarch64-apple-darwin
release: 1.90.0
LLVM version: 20.1.8
```

```Shell
❯ rustc +beta --version --verbose
rustc 1.91.0-beta.3 (bb624dcb4 2025-09-20)
binary: rustc
commit-hash: bb624dcb4c8ab987e10c0808d92d76f3b84dd117
commit-date: 2025-09-20
host: aarch64-apple-darwin
release: 1.91.0-beta.3
LLVM version: 21.1.1
```

```Shell
❯ rustc +nightly --version --verbose
rustc 1.92.0-nightly (7ac0330c6 2025-09-25)
binary: rustc
commit-hash: 7ac0330c6d684d86d6f86fabe601a3defdc3b234
commit-date: 2025-09-25
host: aarch64-apple-darwin
release: 1.92.0-nightly
LLVM version: 21.1.2
```

### Other info

I'm on macos Sequoia 15.7 using iTerm2 3.6.2 and zsh. Happy to provide more env info or try eliminating various causes!

Also note that this isn't reproducible in the playground because the playground has its own highlighting system and doesn't use the terminal's highlighting at all 😭

### PR DESCRIPTION
**Pull request by chenyukang**
Fixes rust-lang/rust#147070

From comments: https://github.com/rust-lang/rust/issues/147070#issuecomment-3368593144
The lightlight row for diff must at least 2.

r? @estebank

### CODE REVIEW

**Comment by chenyukang** [comment]
current output: 
image

**Comment by chenyukang** [comment]
The output for `tests/ui/mismatched_types/newlines-in-diagnostic-fix-suggestions-92741.rs` is also fixed.

Before:
image

Now:
image

File: tests/ui/argument-suggestions/wrong-highlight-span-extra-arguments-147070.rs [hunk 1]
```diff
@@ -0,0 +1,26 @@
+struct Thingie;
```
Comment (xizheyin) [inline tests/ui/argument-suggestions/wrong-highlight-span-extra-arguments-147070.rs:5]: It would be great to add a comment before this test. This change doesn't involve any textual modifications of test outputs, making it difficult to trace.

```
// The hightlight span should be correct. See #147070
```

**Review by xizheyin — APPROVED** [review]

File: tests/ui/argument-suggestions/wrong-highlight-span-extra-arguments-147070.rs (hunk 1 above)
Comment (estebank) [reply tests/ui/argument-suggestions/wrong-highlight-span-extra-arguments-147070.rs:5]: Can you also mark this test as `//@ compile-flags: --color=always` so that we generate an svg of the output?

You'll also need `//@ ignore-windows` iirc.

**Review by estebank — APPROVED** [review]

**Comment by estebank** [comment]
r=me after addressing comments
