### PR TITLE
borrowck: do not suggest to change "&mut self" to "&mut mut self"

### LINKED ISSUE #31424: Error message suggests illegal syntax for method receiver
```rust
// Playpen Link: http://is.gd/2baYh8
struct Struct;

impl Struct {
    fn foo(&mut self) {
        (&mut self).bar();
    }
    
    fn bar(&mut self) {}
}

fn main () {}
```

Output:

```
<anon>:5:15: 5:19 error: cannot borrow immutable argument `self` as mutable
<anon>:5         (&mut self).bar();
                       ^~~~
<anon>:4:17: 4:21 help: to make the argument mutable, use `mut` as shown:
<anon>:      fn foo(&mut mut self) {
error: aborting due to previous error
playpen: application terminated with error code 101
```

### PR DESCRIPTION
**Pull request by birkenfeld**
Matching the snippet string might not be the cleanest, but matching
the AST node instead seems to end in a lot of nested `if let`s, so I
don't know what's better.

Of course it's entirely possible that there is another API altogether
that I just don't know of?

Fixes #31424.

### CODE REVIEW

**Comment by jseyfried** [comment]
This would prevent the following correct suggestion:
```
struct Struct;

impl Struct {
    fn foo(self: &mut Self) {
        (&mut self).bar();
        //~^ ERROR cannot borrow immutable argument `self` as mutable
        //~| HELP to make the argument mutable, use `mut` as shown:
        //~|    fn foo(mut self: &mut Self) {
    }
    
    fn bar(&mut self) {}
}
```

It might be a good idea to match the AST node so that we can continue providing the suggestion in the above case. It would be even better if we could provide the above `HELP` message even when `self` is declared as `&mut self` instead of `self: &mut Self`.

That being said, I think it's more important to not provide a bad suggestion in the common case of `&mut self`, so r=me unless you would like to work one of the above improvements.

**Comment by birkenfeld** [comment]
I've looked a bit at what would be involved, and it's tricky: the "pat" node I can get only ever spans the "self" (it's the special pseudo node added by `Arg::new_self`). The next parent is the whole Item, and the individual Args have no spans. So it'd be a lot of work for this edge case (which is probably quite obscure, since a `&mut &mut T` is not often necessary).

But I've rebased and added a test, will push that now.

File: src/test/compile-fail/issue-31424.rs [hunk 1]
```diff
@@ -0,0 +1,30 @@
...
+// file at the top-level directory of this distribution and at
+// http://rust-lang.org/COPYRIGHT.
+//
+// Licensed under the Apache License, Version 2.0 <LICENSE-APACHE or
+// http://www.apache.org/licenses/LICENSE-2.0> or the MIT license
+// <LICENSE-MIT or http://opensource.org/licenses/MIT>, at your
+// option. This file may not be copied, modified, or distributed
+// except according to those terms.
+
+// forbid-output: &mut mut self
```
Comment (jseyfried) [inline src/test/compile-fail/issue-31424.rs]: Nice -- I didn't know about `forbid-output`
