### PR TITLE
Include bounds from promoted constants in NLL

### LINKED ISSUE #57170: Borrow checker incorrectly accepts code when calling function with complex lifetime bounds through a fn pointer
The following code compiles and prints a bogus value: 
```rust
fn shorten_lifetime<'a, 'b, 'min>(a: &'a i32, b: &'b i32) -> &'min i32
where 'a: 'min, 'b: 'min
{
    if *a < *b {
        &a
    } else {
        &b
    }
}


fn main()
{
    let fnptr = &shorten_lifetime;
    
    let a = &5;
    let ptr = {
        let b = 3;
        let b = &b;
        //let c = shorten_lifetime(a, b);
        let c = fnptr(a, b);
        c
    };
    
    println!("ptr = {:?}", ptr);
    
}
```

Output (release mode):
```
ptr = -1876488848
```
 
(playground: https://play.rust-lang.org/?version=stable&mode=release&edition=2018&gist=048d856b4689599b1e35f0a44ebe629f)

Expected result: a borrow checker error, the same as the one obtained when calling `shorten_lifetime` directly.

I accidentally ran into this issue when trying to spell the fn pointer type of `fnptr` (I'm not sure how to add constraints to the lifetimes of a higher-ranked fn type like `for<'a, 'b> fn(...) -> T`)

### PR DESCRIPTION
**Pull request by matthewjasper**
Previously a promoted function wouldn't have its bound propagated out to
the main function body.

When we visit a promoted, we now type check the MIR of the promoted
and transfer any lifetime constraints to back to the main function's MIR.

Fixes #57170 

r? @nikomatsakis

### CODE REVIEW

**Comment by matthewjasper** [comment]
I have an alternative approach that does the location adjustment in the `BorrowCheckContext` which can be seen here: https://github.com/matthewjasper/rust/tree/nll-typeck-promoteds-alternative. This feels a bit more principled, and ends up being a smaller diff.

**Comment by nikomatsakis** [comment]
@matthewjasper would you like me to compare the two branches, then?

**Comment by matthewjasper** [comment]
Yes, or suggest a third approach if you feel neither is satisfactory.

**Comment by matthewjasper** [comment]
I've pushed (yet) another version that avoids changing other parts of typeck.

**Comment by pnkfelix** [comment]
NLL triage. Assigning to self for review.

File: src/librustc_mir/borrow_check/nll/type_check/mod.rs [hunk 1]
```diff
@@ -528,6 +540,66 @@ impl<'a, 'b, 'gcx, 'tcx> TypeVerifier<'a, 'b, 'gcx, 'tcx> {
         place_ty
     }
 
+    fn sanitize_promoted(&mut self, promoted_mir: &'b Mir<'tcx>, location: Location) {
+        // Determine the constraints from the promoted MIR by running the type
+        // checker on the promoted MIR, then transfer the constraints back to
+        // the main MIR, changing the locations to the provided location.
+
+        let main_mir = mem::replace(&mut self.mir, promoted_mir);
+        self.cx.mir = promoted_mir;
```
Comment (pnkfelix) [inline src/librustc_mir/borrow_check/nll/type_check/mod.rs]: hmm. It makes me a little sad that we've got this redundancy in the representation, in that I worry that other code might similarly swap in different MIR but omit one of the partnering references to that MIR (either because out of ignorance or because it doesn't have access to the outer `TypeVerifier`).

But I don't have a better answer for what to do here (well, apart from getting rid of the `self.mir` field in `TypeVerifier` and instead make those accesses go through `self.cx.mir`, potentially via a `mir()` method or via a `Deref` to the `self.cx`...)

Comment (pnkfelix) [reply src/librustc_mir/borrow_check/nll/type_check/mod.rs]: (Oh and of course I don't want to block *this* PR on such a change. Anything we can do to make this soundness fix more likely to be backported, I'm a fan of....)

File: src/librustc_mir/borrow_check/nll/type_check/mod.rs [hunk 2]
```diff
@@ -528,6 +540,66 @@ impl<'a, 'b, 'gcx, 'tcx> TypeVerifier<'a, 'b, 'gcx, 'tcx> {
...
+
+        let all_facts = &mut None;
+        let mut constraints = Default::default();
+        let mut closure_bounds = Default::default();
+        if let Some(ref mut bcx) = self.cx.borrowck_context {
+            // Don't try to add borrow_region facts for the promted MIR
```
Comment (pnkfelix) [inline src/librustc_mir/borrow_check/nll/type_check/mod.rs]: typo: promted

File: src/test/ui/nll/issue-48697.rs [hunk 3]
```diff
@@ -1,14 +1,12 @@
...
-// compile-pass
-
 #![feature(nll)]
 
 fn foo(x: &i32) -> &i32 {
     let z = 4;
     let f = &|y| y;
     let k = f(&z);
-    f(x)
+    f(x) //~ cannot return value referencing local variable
```
Comment (pnkfelix) [inline src/test/ui/nll/issue-48697.rs]: uh.... uh oh?

Is this because we aren't inferring a sufficiently general type for the closure?

Comment (pnkfelix) [reply src/test/ui/nll/issue-48697.rs]: but I guess the "good" news is that AST-borrowck also rejects this code, so the impact of this "regression" will be limited... maybe...?

**Comment by pnkfelix** [comment]
I'm r+'ing this but I'm also nominating it for discussion at the NLL meeting. In particular, I want us to make sure we're all okay with the change from accepting the test from #48697 to rejecting it. (My current hypothesis is that its being rejected because of known issues with inferring higher-ranked lifetime for closures; see also discussion on #58052.)

**Comment by pnkfelix** [comment]
oh and I'm also beta nominating, since this is fixing a soundness issue and is relatively straight-forward.

File: src/librustc_mir/borrow_check/nll/type_check/mod.rs (hunk 1 above)
Comment (matthewjasper) [reply src/librustc_mir/borrow_check/nll/type_check/mod.rs]: Well, this ended up happening anyway with the fix for the ICE.

**Comment by matthewjasper** [comment]
@pnkfelix the last commit fixes the ICE, do you want to review it?

**Comment by pnkfelix** [comment]
@matthewjasper if you get a chance it might be nice to make a unit test for whatever problem was uncovered by the ICE?

**Comment by pnkfelix** [comment]
discussed at T-compiler meeting. We'll revisit the question of whether or not to backport this to beta next week. (@nikomatsakis wants to review the approach.)

**Comment by pnkfelix** [comment]
discussed at T-compiler meeting. beta-accepting.
