### PR TITLE
Use the new solver in the `impossible_predicates`

### LINKED ISSUE #140212: incompletely relating alias args is unsound during vtable creation
cc https://github.com/rust-lang/rust/issues/140211 the following snippet segfaults :3

```rust
trait Id {
    type This<'a>;
}
impl<T> Id for T {
    type This<'a> = T;
}

trait Trait<T> {}
impl<T: Id> Trait<for<'a> fn(T::This<'a>)> for T {}

trait Method<T: Id> {
    fn call_me(&self)
    where
        T: Trait<for<'a> fn(T::This<'a>)>;
}

impl<T, U> Method<U> for T {
    fn call_me(&self) {}
}

fn generic<T: Id>(x: &dyn Method<T>) {
    // Proving `T: Trait<for<'a> fn(T::This<'a>)>` holds.
    x.call_me();
}

fn main() {
    // Proving `u32: Trait<fn(u32)>` fails due to incompleteness.
    // We don't add the method to the vtable of `dyn Method`, so
    // calling it causes UB.
    generic::<u32>(&());
}
```

### PR DESCRIPTION
**Pull request by compiler-errors**
The old solver is unsound for many reasons. One of which was weaponized by @lcnr in #140212, where the old solver was incompletely considering a dyn vtable method to be impossible and replacing its vtable entry with a null value. This null function could be called post-mono. 

The new solver is expected to be less incomplete due to its correct handling of higher-ranked aliases in relate. This PR switches the `impossible_predicates` query to use the new solver, which patches this UB.

r? lcnr

### CODE REVIEW

**Comment by compiler-errors** [comment]
Ok let me fix AFIDT first.

@rustbot author

**Comment by compiler-errors** [comment]
@bors try @rust-timer queue

(and crater)

**Comment by compiler-errors** [comment]
@craterbot check

**Comment by wesleywiser** [comment]
Checking in from compiler team triage, it looks like crater did find [an ICE](https://crater-reports.s3.amazonaws.com/pr-136988/try%234c525d43052e921548191f82f6ed9e2f9e98dcb1/reg/spark-orderbook-sdk-0.2.1/log.txt) perhaps. I think this is probably waiting on the author to comment on the crater results.

@rustbot author

**Comment by compiler-errors** [comment]
This was the last decision we made about utilizing the new solver in the compiler: https://github.com/rust-lang/rust/pull/123594#issuecomment-2042756398

> Going to start a types FCP to officially state that going forward, the @rust-lang/initiative-trait-system-refactor has the authority to enable the use of the new solver on stable without FCPs as long as t-types is pinged in the PR and the affected area is neither relevant for soundness nor backwards compatibility.

Given that this is a soundness fix, I think it warrants a re-FCP for this specific case.

**Comment by lcnr** [comment]
We're checking fully concrete goals in an empty environment. I believe that the new solver is able to handle this case well and certainly expect it to be *more* complete than the old solver. There should be far fewer, if any, cases, where we incorrectly return `NoSolution` even if the goal should actually hold.

This only avoids monomorphizing impossible functions, so it should not be user-visible.

File: tests/ui/traits/vtable/impossible-method.rs [hunk 1]
```diff
@@ -0,0 +1,38 @@
...
+fn generic<T: Id>(x: &dyn Method<T>) {
+    // Proving `T: Trait<for<'a> fn(T::This<'a>)>` holds.
+    x.call_me();
+}
+
+fn main() {
+    // Proving `u32: Trait<fn(u32)>` fails due to incompleteness.
+    // We don't add the method to the vtable of `dyn Method`, so
+    // calling it causes UB.
+    generic::<u32>(&());
```
Comment (BoxyUwU) [inline tests/ui/traits/vtable/impossible-method.rs:37]: - goal: `u32: Trait<fn(u32)>`
- impl candidate: `?t: Trait<for<'a> fn(<?t as Id>::This<'a>)>`
- doesn't apply in old solver as `u32 eq <?t as Id>::This<'a>` doesn't hold because we treat all aliases as rigid, and, its an ambig alias that cant be normalized to infer because escaping bound vars?
- applies in new solver because we emit a `<?t as Id>::This<'!a_u1> alias-relate u32` goal which can succeed once we infer `?t=u32`?

Is that the right understanding of what's going on here? And then its just generally unsound for checking impossible preds to consider preds to be impossible if they actually aren't.

Comment (compiler-errors) [reply tests/ui/traits/vtable/impossible-method.rs:37]: Correct. 

In other words, the impossible preds query needs to be *complete* b/c we use "this goal is impossible to satisfy" responses to skip monomorphizing items with bad where clauses in codegen. Here in vtable, but also as monomorphization roots, etc.

File: compiler/rustc_trait_selection/src/traits/mod.rs [hunk 2]
```diff
@@ -690,8 +690,11 @@ fn replace_param_and_infer_args_with_placeholder<'tcx>(
 /// used during analysis.
 pub fn impossible_predicates<'tcx>(tcx: TyCtxt<'tcx>, predicates: Vec<ty::Clause<'tcx>>) -> bool {
     debug!("impossible_predicates(predicates={:?})", predicates);
-    let (infcx, param_env) =
-        tcx.infer_ctxt().build_with_typing_env(ty::TypingEnv::fully_monomorphized());
+    let (infcx, param_env) = tcx
+        .infer_ctxt()
+        .with_next_trait_solver(true)
+        .build_with_typing_env(ty::TypingEnv::fully_monomorphized());
```
Comment (BoxyUwU) [inline compiler/rustc_trait_selection/src/traits/mod.rs:696]: It feels kind of weird to be using the new trait solver "because its more complete" while *also* using a typing mode that is allowed to be incomplete (unlike coherence mode). I guess it is also true that the not-required-to-be-complete solver modes in the new solver should less incomplete than the not-required-to-be-complete-solver-modes in the old solver. So still a good change and it being weird is kind of pre-existing.

Do we expect the trait solver to always be complete even outside of coherence in some specific circumstances? What are those circumstances?

Comment (lcnr) [reply compiler/rustc_trait_selection/src/traits/mod.rs:696]: > Do we expect the trait solver to always be complete even outside of coherence in some specific circumstances? What are those circumstances?

I think the following incompletenesses should be forbidden:
- goal holds without infer vars in a generic context -> goal holds in an empty env after instantiating this context (otherwise we'd have to recheck all goals during monomorphization)
- goal holds with infer vars, constraining the infer vars to some concrete type also means the goal holds (otherwise we'd need to keep goals around until they have no infer vars, even if they hold. This would result in a MIR typeck ICE if it goes wrong)
 
So we'd have "`for<T: Clone> Foo<T>: Clone` implies `Foo<u32>: Clone`" and "`Foo<?x>: Clone` implies `Foo<Vec<u32>>: Clone`".

I am not totally sure whether `Foo<?x>: Clone` implies `Foo<Vec<?x>>: Clone` and think that not doing so wouldn't be unsound, just questionable.

**Comment by Kobzol** [comment]
The regressions are mostly in `helloworld` and tiny benchmarks, and they are relatively small, so I think it's fine. We generally expect the perf. of the new solver to improve over time.

@rustbot label: +perf-regression-triaged
