### PR TITLE
Break up compiletest `runtest.rs` into smaller helper modules

### LINKED ISSUE #89475: Splitting up `compiletest::runtest`
Subtask to #60302.

- [ ] RunPassValgrind is practically useless (valgrind is not installed on CI, and the tests are just run in run-pass mode). The right approach here is likely to refactor it as a modifier atop the regular run-pass tests -- it looks like the code generally just mirrors the RunPass mode, other than setting the runtool to valgrind. That mode can be enabled in the configuration of the test with `// use-valgrind` or something like that.
- [x] Move diff computation out into a separate module (DiffLine, Mismatch, make_diff, ...)
- [x] Move read2_abbreviated to the read2.rs module
- [x] Move DebuggerCommands and their parsing out to a separate file, alongside check_debugger_output (which is similarly parsing code).

I suspect this set of changes is likely harder, and might not get to <3000 lines; there's likely more cleanup work possible, though. This module has grown pretty organically over the last ~10 years -- there's a lot of small bits that can be adjusted to make things better. There's probably also subtle inconsistencies between various functions that would likely be nice to clean up and unify, and filing PRs for those would be helpful -- likely some care is needed, perhaps even some small test updates, but overall a good goal.

You might also be interested in https://github.com/rust-lang/rust/issues/40713, as a somewhat larger project.

_Originally posted by @Mark-Simulacrum in https://github.com/rust-lang/rust/issues/89240#issuecomment-932658341_

### LINKED ISSUE #130565: Tracking Issue for assorted compiletest cleanups
This is a tracking issue for a series of `compiletest` cleanups. This tracking issue is on-going and will be edited as suitable to reflect the next steps. Tasks should be broken up into small actionable items.

### Motivation

Currently `compiletest` is a bit of a mess causing it to be really hard to maintain. Let's try to do some housekeeping in `compiletest` to make it easier to maintain.

### Phase 1: `compiletest/src/runtest.rs` cleanups

- Step 1: Break up `compiletest/src/runtest.rs` into smaller helper modules.
    - Originally https://github.com/rust-lang/rust/issues/89475
- Step 2: Investigate and rework how `valgrind` test suites are handled, namely what happens if `valgrind` is not available.
- Step 3: Relocate functions on `TestCx` that does not need to be on `TestCx` (especially ones that don't depend on `TestCx` itself) to suitable locations.
- Step 4: Reorganize methods on `TestCx`:
    - Step 4.1: Privatize methods only used by a specific test suite/mode to their specific helper modules.
    - Step 4.2: Reorder/regroup methods on the core `TestCx` in `runtest.rs` to make it easier to navigate.
- Step 5: Improve documentation around `runtest.rs`:
    - Step 5.1: Document util and helper methods on `TestCx`.
    - Step 5.2: Document individual test suites/modes.
    - Step 5.3: Document top-level `TestCx` and types/concepts in `runtest.rs`.
    - Step 5.4: Update `rustc-dev-guide` docs about the individual test modes/suites and about test running.
- TODO

### Phase 2: Rework directive handling

- Step 1: Redesign how directives are parsed and handled.
    - @tgross35 has some experimentation in https://github.com/rust-lang/rust/pull/128070, this should get an MCP to receive more feedback from other compiler team members (TODO(@jieyouxu): write-up an MCP)
- Step 2: Survey existing directive handling related bugs.
- Step 3: Implement more robust directive handling.
    - Step 3.1: Implement the more robust design but not merge yet, as we need to...
    - Step 3.2: ... find out which tests contain invalid directives w.r.t. new directive handling and fix them.
    - Step 3.3: Investigate and improve testing for directive handling.
    - Step 3.4: Try to land the improved directive handling.
- Step 4: Improve directive documentation in source and in rustc-dev-guide:
    - Step 4.1: Unify terminology: stick with "directive", not also "header" or "comment" etc.
    - Step 4.2: Document individual directives: syntax, applicable to which test suites, behavior
- TODO

### Phase 3: Rework compiletest error handling and error reporting

- Step 1: Investigate how `compiletest` currently handles errors and reports them.
- Step 2: Come up with a design to make `compiletest` error reporting more cohesive and more helpful for users.
- TODO

There are more phases intended, but they are to be planned.

### PR DESCRIPTION
**Pull request by jieyouxu**
Previously compiletest's `runtest.rs` was a massive 4700 lines file that made reading and navigation very awkward. This PR breaks the `runtest.rs` file up into smaller helper modules, one for each test suite/mode.

> [!NOTE]
> This PR should not contain functional changes, it is intended to be mostly code motion to breakup `runtest.rs` into smaller helper modules to make it easier to digest.
>
> This PR intentionally does not neatly reorganize where all the methods on `TestCx` goes, that is intended for a follow-up PR. Some methods on `TestCx` do not need to be on `TestCx`. It also does not address a weirdness in valgrind, that is intended for a follow-up PR as well.

Part of a series of compiletest cleanups #130565.

Fixes #89475.

r? @ghost (I need to do a self-review pass first)

### CODE REVIEW

File: src/tools/compiletest/src/runtest/coverage.rs [hunk 1]
```diff
@@ -18,7 +18,7 @@ impl<'test> TestCx<'test> {
             .unwrap_or_else(|| self.fatal("missing --coverage-dump"))
     }
 
-    pub(crate) fn run_coverage_map_test(&self) {
+    pub(super) fn run_coverage_map_test(&self) {
```
Comment (jieyouxu) [inline src/tools/compiletest/src/runtest/coverage.rs:21]: Remark: changed visibility from `pub(crate)` -> `pub(super)` for consistency as it does not need to be visible outside of `runtest.rs`.

File: src/tools/compiletest/src/runtest/incremental.rs [hunk 2]
```diff
@@ -0,0 +1,128 @@
+use super::{TestCx, WillExecute};
+use crate::errors;
+
+// FIXME(jieyouxu): `run_rpass_test` got hoisted out of this because apparently valgrind falls back
+// to `run_rpass_test` if valgrind isn't available, which is questionable, but keeping it for
+// refactoring changes to preserve current behavior.
```
Comment (jieyouxu) [inline src/tools/compiletest/src/runtest/incremental.rs:6]: Remark: FIXME because valgrind just runs rpass if valgrind isn't available, which is highly questionable.

File: src/tools/compiletest/src/runtest/valgrind.rs [hunk 3]
```diff
@@ -0,0 +1,34 @@
...
+impl TestCx<'_> {
+    pub(super) fn run_valgrind_test(&self) {
+        assert!(self.revision.is_none(), "revisions not relevant here");
+
+        // FIXME(jieyouxu): does this really make any sense? If a valgrind test isn't testing
+        // valgrind, what is it even testing?
+        if self.config.valgrind_path.is_none() {
+            assert!(!self.config.force_valgrind);
+            return self.run_rpass_test();
+        }
```
Comment (jieyouxu) [inline src/tools/compiletest/src/runtest/valgrind.rs:12]: Remark: this is sus

File: src/tools/compiletest/src/runtest.rs
Comment (jieyouxu) [inline src/tools/compiletest/src/runtest.rs:1]: Remark: I know this file is still really messy, further changes planned in future PRs.

File: src/tools/compiletest/src/runtest.rs [hunk 4]
```diff
@@ -31,12 +28,27 @@ use crate::compute_diff::{write_diff, write_filtered_diff};
...
+use crate::{json, ColorConfig};
 
+// tidy-alphabet-start
+mod assembly;
+mod codegen;
+mod codegen_units;
 mod coverage;
+mod crash;
 mod debugger;
-use debugger::DebuggerCommands;
```
Comment (jieyouxu) [inline src/tools/compiletest/src/runtest.rs:39]: I should move `debugger` out of this listing because it's a helper module not a test suite/mode. I should also add a comment to say the intended purpose of the organization of helper submodules as each implementing a test suite/mode.

**Review by jieyouxu — COMMENTED** [review]
This PR might want to get its git rev ignored as it does a lot of moving.

File: src/tools/compiletest/src/runtest.rs (hunk 4 above)
Comment (jieyouxu) [reply src/tools/compiletest/src/runtest.rs:39]: Fixed.

**Comment by jieyouxu** [comment]
This should now be ready for review.
r? compiler
@rustbot ready

**Comment by jieyouxu** [comment]
Would appreciate feedback if this organization makes sense, or if there's a better way to organize it.
