### PR TITLE
Fix mutex's docs inconsistency

### LINKED ISSUE #40176: Inconsistency in the document of std::sync::Mutex
In the document of std::sync::Mutex, *lock* and *mutex* are used interchangeably.
For example, the document of `lock()` is as follows:

```rust
/// This function will block the local thread until it is available to acquire
/// the mutex. Upon returning, the thread is the only thread with the mutex
/// held. An RAII guard is returned to allow scoped unlock of the lock. When
/// the guard goes out of scope, the mutex will be unlocked.
```

Here, *the lock* and *the mutex* are used to refer to the same `Mutex` object. As a non-native English speaker, this kind of inconsistency is  somewhat confusing. This is especially the case for this document because *lock* also refers to the operation on the mutex object.

I do understand these two words are interchangable unless you are writing a thesis or the like. However, I feel that using them consistently throughout the document makes it more readable.

Therefore, I would like to suggest to use *mutex* to refer to the `Mutex` object, and *lock* or *unlock* to refer to the operations on the `Mutex` object.

e.g. An RAII guard is returned to allow scoped unlock of the mutex.

Sorry in advance if this inconsistency is intentional.

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Fixes #40176.

r? @steveklabnik 
cc @rust-lang/docs

### CODE REVIEW

File: src/libstd/sync/mutex.rs [hunk 1]
```diff
@@ -183,18 +183,18 @@ impl<T: ?Sized> Mutex<T> {
     /// Acquires a mutex, blocking the current thread until it is able to do so.
     ///
     /// This function will block the local thread until it is available to acquire
-    /// the mutex. Upon returning, the thread is the only thread with the mutex
+    /// the lock. Upon returning, the thread is the only thread with the lock
     /// held. An RAII guard is returned to allow scoped unlock of the lock. When
-    /// the guard goes out of scope, the mutex will be unlocked.
+    /// the guard goes out of scope, the mutex's lock will be unlocked.
```
Comment (ScottAbbey) [inline src/libstd/sync/mutex.rs]: >  the mutex's lock will be unlocked.

I'm not sure this change is an improvement over the original.

File: src/libstd/sync/mutex.rs [hunk 2]
```diff
@@ -183,18 +183,18 @@ impl<T: ?Sized> Mutex<T> {
     /// Acquires a mutex, blocking the current thread until it is able to do so.
```
Comment (ScottAbbey) [inline src/libstd/sync/mutex.rs]: > Acquires a mutex, blocking

Two lines after this, the comment speaks of acquiring "the lock," should this instance be modified as well?

Comment (whoisj) [inline src/libstd/sync/mutex.rs]: Concern here: "lock" is generic, while "mutex" is shorthand for "mutually exclusive lock" and therefore seems most specific and correct to me.

Comment (ScottAbbey) [inline src/libstd/sync/mutex.rs]: This is the same paragraph directly quoted in #40176, would you say it would have been better to change the one instance of "the lock" to "the mutex" instead of the other way around?

Comment (whoisj) [inline src/libstd/sync/mutex.rs]: Yes "lock" or "acquire" as the verb, and "mutex" as the noun. Therefore "the mutex" makes more sense than "the lock". 😃

Comment (GuillaumeGomez) [inline src/libstd/sync/mutex.rs]: I agree with @ScottAbbey on this one. For non-english speaker, acquiring a lock better than acquiring a mutex which doesn't mean much.

Comment (whoisj) [inline src/libstd/sync/mutex.rs]: @GuillaumeGomez while I agree, this isn't just pros. We're discussing technical documentation and as such should be as specific as possible, without being exclusionary. 

If we're going with the general term, then we need to the MSDN thing of explaining that the lock is exclusive and will block any threads that attempt to acquire the lock while the lock is held.

IMO this gets verbose, but does have the advantage of being very approachable and lends itself well to education as well as to translation.

**Comment by frewsxcv** [comment]
cc @rust-lang/libs for terminology here

**Comment by alexcrichton** [comment]
I personally consider "mutex" and "lock" as interchangeable, but canonicalizing on one seems fine (e.g. they're interchangeable, so doesn't matter what we call it!)

File: src/libstd/sync/mutex.rs (hunk 1 above)
Comment (sfackler) [inline src/libstd/sync/mutex.rs]: I agree - a mutex doesn't contain a lock, it *is* a lock, IMO.

**Comment by ScottAbbey** [comment]
I agree with @whoisj, almost every reference to "lock" should instead be "mutex."

The language that seems to make the most sense is:

The *mutex* may be *locked* or *unlocked*.

The original complaint in #40176 was that *the lock* and *the mutex* were both used to refer to the `Mutex` object.  By changing all references of "mutex" to "lock", the problem only got worse, now we are talking about *locking* and *unlocking* the *lock*.

Searching for some other published writing about a similar topic, I found the following in Chapter 30 (page 634) of The Linux Programming Interface, by Michael Kerrisk:

> When a thread locks a mutex, it becomes the owner of that mutex. Only the mutex owner can unlock the mutex.

I find this short quote easy to read and understand.  Rewriting that sentence to fit the state of this mutex documentation as it currently stands, we would have something like:

> When a thread acquires a lock, it becomes the holder of that lock. Only the lock owner can unlock the mutex.

This is still in the same confusing state we started with.  Shouldn't the thread acquire (or lock) "the mutex", be the holder (or owner) of "the mutex", and "the mutex holder (or owner)" be able to unlock it?

There are still some consistency issues.  In the comment for `is_poisoned`:

> /// Determines whether **the lock** is poisoned
...
> ///    panic!(); // **the mutex** gets poisoned

The first one and several other "lock is poisoned" references should instead say "the mutex".

This phrase appears many times:

> /// If another user of this mutex panicked while holding the lock, then this call will return an error instead.

I think all of those should be changed back to "while holding the mutex".

Under `struct Mutex<T>`:

> to ensure that the native mutex is used correctly we box the inner lock...

Should be "the inner mutex".

I don't trust myself to try writing any of this as I really don't know what I'm talking about anyway.

**Comment by steveklabnik** [comment]
agree wholeheartedly with @ScottAbbey

**Comment by steveklabnik** [comment]
@GuillaumeGomez ping! any updates on this?

**Comment by GuillaumeGomez** [comment]
I need to update it. Will do it in the day.

**Comment by GuillaumeGomez** [comment]
Ok so I made a first update. Did I miss anything?

File: src/libstd/sync/mutex.rs [hunk 3]
```diff
@@ -92,7 +92,7 @@ use sys_common::poison::{self, TryLockError, TryLockResult, LockResult};
 /// let lock2 = lock.clone();
 ///
 /// let _ = thread::spawn(move || -> () {
-///     // This thread will acquire the mutex first, unwrapping the result of
+///     // This thread will acquire the lock first, unwrapping the result of
```
Comment (steveklabnik) [inline src/libstd/sync/mutex.rs]: this is the inverse

File: src/libstd/sync/mutex.rs [hunk 4]
```diff
@@ -180,10 +180,10 @@ impl<T> Mutex<T> {
 }
 
 impl<T: ?Sized> Mutex<T> {
-    /// Acquires a mutex, blocking the current thread until it is able to do so.
+    /// Acquires a lock, blocking the current thread until it is able to do so.
```
Comment (steveklabnik) [inline src/libstd/sync/mutex.rs]: same

File: src/libstd/sync/mutex.rs [hunk 5]
```diff
@@ -180,10 +180,10 @@ impl<T> Mutex<T> {
...
     ///
     /// This function will block the local thread until it is available to acquire
-    /// the mutex. Upon returning, the thread is the only thread with the mutex
+    /// the lock. Upon returning, the thread is the only thread with the lock
```
Comment (steveklabnik) [inline src/libstd/sync/mutex.rs]: same

File: src/libstd/sync/mutex.rs [hunk 6]
```diff
@@ -193,8 +193,8 @@ impl<T: ?Sized> Mutex<T> {
     ///
     /// # Errors
     ///
-    /// If another user of this mutex panicked while holding the mutex, then
-    /// this call will return an error once the mutex is acquired.
+    /// If another user of this mutex panicked while holding the lock, then
+    /// this call will return an error once the lock is acquired.
```
Comment (steveklabnik) [inline src/libstd/sync/mutex.rs]: same on both lines

File: src/libstd/sync/mutex.rs [hunk 7]
```diff
@@ -233,8 +233,8 @@ impl<T: ?Sized> Mutex<T> {
     ///
     /// # Errors
     ///
-    /// If another user of this mutex panicked while holding the mutex, then
-    /// this call will return failure if the mutex would otherwise be
+    /// If another user of this mutex panicked while holding the lock, then
+    /// this call will return failure if the lock would otherwise be
```
Comment (steveklabnik) [inline src/libstd/sync/mutex.rs]: same

**Review by steveklabnik — CHANGES_REQUESTED** [review]
a couple more spots, then r=me

**Comment by GuillaumeGomez** [comment]
I updated to @steveklabnik's comments.

**Review by steveklabnik — APPROVED** [review]
