### PR TITLE
Fix confusing error message for comma typo in multiline statement

### LINKED ISSUE #72253: odd suggestion for comma typo
In an obscure situation with a typo (where there is a comma instead of a period), rustc will suggest replacing the comma with a semicolon, which will fail to compile.

```rust
let a = std::process::Command::new("echo")
    .arg("1")
    ,arg("2")
    .output();
```

Produces the following error and suggestion:

```
error: expected `;`, found ``,``
 --> src/main.rs:4:5
  |
4 |     ,arg("2")
  |     ^ help: change this to `;`: `;`

error[E0425]: cannot find function `arg` in this scope
 --> src/main.rs:4:6
  |
4 |     ,arg("2")
  |      ^^^ not found in this scope

error: aborting due to 2 previous errors

For more information about this error, try `rustc --explain E0425`.
```

Some observations:

* This must be a let binding.
* The method calls must be on separate lines (all on one line gives a different error).

I would expect this to provide the same error if it is all on one line ("expected one of `.`, `;`, `?`, or an operator"), possibly with a "maybe incorrect" suggestion to replace it with a period (maybe only if the following character is not whitespace?).

Note: Feel free to close this.  This is really obscure, and I suspect it is not trivial to change, and it is fairly obvious what is wrong.  I just thought it was strange, and I was doubly puzzled that the indentation mattered.

### Meta
rustc 1.45.0-nightly (9912925c2 2020-05-10)

### PR DESCRIPTION
**Pull request by chrissimpkins**
Fixes #72253.  Expands on the issue with a colon typo check.

r? @estebank 

cc @ehuss

### CODE REVIEW

File: src/librustc_parse/parser/diagnostics.rs [hunk 1]
```diff
@@ -934,6 +934,25 @@ impl<'a> Parser<'a> {
             return self.expect(&token::Semi).map(drop);
         } else if !sm.is_multiline(self.prev_token.span.until(self.token.span)) {
```
Comment (estebank) [inline src/librustc_parse/parser/diagnostics.rs:935]: What happens if we instead change this to the following and remove the new code?
```suggestion
        } else if !sm.is_multiline(self.prev_token.span.between(self.token.span)) {
```

File: src/librustc_parse/parser/diagnostics.rs [hunk 2]
```diff
@@ -934,6 +934,25 @@ impl<'a> Parser<'a> {
...
+            //         .arg("1")
+            //         ,arg("2")
+            //         ^
+            // https://github.com/rust-lang/rust/issues/72253
+
+            let sp = self.token.span;
+            self.struct_span_err(sp, &msg)
+                .span_label(self.token.span, "unexpected token")
+                .span_help(sp, "change this to `.`, `;`, `?`, or an operator")
+                .emit();
```
Comment (estebank) [inline src/librustc_parse/parser/diagnostics.rs:954]: `self.expect(_)` already holds a list of acceptable following tokens, so it isn't necessary to create a new list manually that accounts for all possible valid expressions.

File: src/librustc_parse/parser/diagnostics.rs [hunk 3]
```diff
@@ -934,6 +934,25 @@ impl<'a> Parser<'a> {
             return self.expect(&token::Semi).map(drop);
         } else if !sm.is_multiline(self.prev_token.span.until(self.token.span)) {
             // The current token is in the same line as the prior token, not recoverable.
+        } else if sm.is_multiline(self.prev_token.span.until(self.token.span))
```
Comment (estebank) [inline src/librustc_parse/parser/diagnostics.rs:937]: The `is_multiline` is already implied by the previous if branch.

File: src/librustc_parse/parser/diagnostics.rs [hunk 4]
```diff
@@ -934,6 +934,25 @@ impl<'a> Parser<'a> {
...
+            && [token::Comma, token::Colon].contains(&self.token.kind)
+            && &self.prev_token.kind == &token::CloseDelim(token::Paren)
```
Comment (estebank) [inline src/librustc_parse/parser/diagnostics.rs:939]: This seems a bit too constraining to a specific case. Let's see if the proposed change to the PR actually helps out for the case we are trying to address (without this code).

File: src/librustc_parse/parser/diagnostics.rs [hunk 5]
```diff
@@ -934,6 +934,25 @@ impl<'a> Parser<'a> {
...
+            // let a = std::process::Command::new("echo")
+            //         .arg("1")
+            //         ,arg("2")
+            //         ^
+            // https://github.com/rust-lang/rust/issues/72253
+
+            let sp = self.token.span;
+            self.struct_span_err(sp, &msg)
+                .span_label(self.token.span, "unexpected token")
+                .span_help(sp, "change this to `.`, `;`, `?`, or an operator")
```
Comment (estebank) [inline src/librustc_parse/parser/diagnostics.rs:953]: For future reference, we have "structured suggestions" for these kind of things (called through `.span_suggestion` , `.multipart_suggestion` and `.span_suggestions`, among other available methods) which lets other tools show tooltips for the code changes.

File: src/librustc_parse/parser/diagnostics.rs [hunk 6]
```diff
@@ -934,6 +934,25 @@ impl<'a> Parser<'a> {
...
+            && [token::Comma, token::Colon].contains(&self.token.kind)
+            && &self.prev_token.kind == &token::CloseDelim(token::Paren)
+        {
+            // Likely typo: The current token is on a new line and is expected to be
+            // `.`, `;`, `?`, or an operator after a close delimiter token.
+            //
+            // let a = std::process::Command::new("echo")
+            //         .arg("1")
+            //         ,arg("2")
+            //         ^
```
Comment (estebank) [inline src/librustc_parse/parser/diagnostics.rs:947]: I think we could _potentially_ add a case for this specific scenario to detect typos (like `;`, `:` and `,`), but I would like to see what the error looks like if `self.expect(&Semi)` where called instead to see how misleading it would be.

**Review by estebank — CHANGES_REQUESTED** [review]
Thank you very much for taking the time to look into this!

I have a couple of comments I would like you to address before this is merged.

File: src/librustc_parse/parser/diagnostics.rs (hunk 2 above)
Comment (chrissimpkins) [reply src/librustc_parse/parser/diagnostics.rs:954]: Is this a suggestion to format the return value from self.expect in the string?  I am not following completely here.

File: src/librustc_parse/parser/diagnostics.rs (hunk 5 above)
Comment (chrissimpkins) [reply src/librustc_parse/parser/diagnostics.rs:953]: Ty!  Will track them down and read up.

**Comment by chrissimpkins** [comment]
Thank you very much for your review Esteban.  I'll have a look at these issues.

Do you happen to know what is going on with the new UI test fail?  I ran it locally with `--bless` and confirmed that the formatting issues with paths and line numbers are resolved for the string comparisons.  I don't understand the error that is being raised, nor how to address it.  I think that the current compiler stderr stream string and stderr file string match at this stage.  I'd like to understand how to appropriately add a new UI test irrespective of whether we end up using the one that is proposed at the moment. Do I need to add a stdout file too? It looks like the fail may be on the stdout?

**Comment by estebank** [comment]
You did the right thing. By running `--bless` you update the `.stderr` files, but the `.rs` test file _also_ has comments that start with `//~ ERROR` followed by the error message that check the current line for an error being emitted on it (or `//~^ ERROR` to point at the line above). You just need to change the comment from `// error: ` to `//~ ERROR `. Sorry I didn't catch that before :)

We care about both because the comments highlight intent, while we look at the `stderr` files as a sanity check that we don't regress the way humans actually see the error.

File: src/librustc_parse/parser/diagnostics.rs (hunk 1 above)
Comment (chrissimpkins) [reply src/librustc_parse/parser/diagnostics.rs:935]: No change from OP with this change:

```
error: expected `;`, found `,`
 --> src/main.rs:4:5
  |
4 |     ,arg("2")
  |     ^ help: change this to `;`: `;`

error[E0425]: cannot find function `arg` in this scope
 --> src/main.rs:4:6
  |
4 |     ,arg("2")
  |      ^^^ not found in this scope

error: aborting due to 2 previous errors

For more information about this error, try `rustc --explain E0425`.
error: could not compile `tester`.

To learn more, run the command again with --verbose.
```

File: src/librustc_parse/parser/diagnostics.rs (hunk 6 above)
Comment (chrissimpkins) [reply src/librustc_parse/parser/diagnostics.rs:947]: with this change to my original block:

```rust
else if [token::Comma, token::Colon].contains(&self.token.kind)
        && &self.prev_token.kind == &token::CloseDelim(token::Paren)
        
    self.expect(&token::Semi)?;
}
```

I get this error message:

```
error: expected one of `.`, `;`, `?`, or an operator, found `,`
 --> src/main.rs:4:5
  |
3 |     .arg("1")
  |              - expected one of `.`, `;`, `?`, or an operator
4 |     ,arg("2")
  |     ^ unexpected token

error: aborting due to previous error

error: could not compile `tester`.
```

That seems pretty close.  It would be nice to drop the "expected one of..." line down to the line 4 level below the unexpected token message IMO.

File: src/librustc_parse/parser/diagnostics.rs (hunk 2 above)
Comment (chrissimpkins) [reply src/librustc_parse/parser/diagnostics.rs:954]: addressed in https://github.com/rust-lang/rust/pull/72348#discussion_r427719055

File: src/librustc_parse/parser/diagnostics.rs (hunk 3 above)
Comment (chrissimpkins) [reply src/librustc_parse/parser/diagnostics.rs:937]: Changed this locally. Will wait to hear your thoughts about the current set of changes and where we are with the report before I push anything. See https://github.com/rust-lang/rust/pull/72348#discussion_r427719055 for something that is very close to what we want.

File: src/librustc_parse/parser/diagnostics.rs (hunk 4 above)
Comment (chrissimpkins) [reply src/librustc_parse/parser/diagnostics.rs:939]: Waiting to hear additional thoughts about this. This is still in place as of the comments in https://github.com/rust-lang/rust/pull/72348#discussion_r427719055

**Comment by chrissimpkins** [comment]
> You just need to change the comment from `// error: ` to `//~ ERROR `. 

I can confirm that this fixes the test.  Ty!

File: src/test/ui/issues/issue-72253.stderr [hunk 7]
```diff
@@ -0,0 +1,10 @@
+error: expected one of `.`, `;`, `?`, or an operator, found `,`
+  --> $DIR/issue-72253.rs:4:9
+   |
+LL |         .arg("1")
+   |                  - expected one of `.`, `;`, `?`, or an operator
```
Comment (chrissimpkins) [inline src/test/ui/issues/issue-72253.stderr:5]: I'd like to see this line below the "^ unexpected token" line

Comment (chrissimpkins) [reply src/test/ui/issues/issue-72253.stderr:5]: or as a separate help recommendation

Comment (estebank) [reply src/test/ui/issues/issue-72253.stderr:5]: Why do you feel this is bad? This actually give you context as to why it was expecting a `;` or `?`, but it might be that I am just used to this way of displaying things.

Comment (chrissimpkins) [reply src/test/ui/issues/issue-72253.stderr:5]: I wouldn't go so far as to say that it is bad.  I'm good with it if it is not simple to drop the message down so that they both point to the comma token.  This is definitely an improvement over the initial report.

**Comment by chrissimpkins** [comment]
CI is failing but it looks like this is an issue with tidy checks on source unrelated to this PR

https://github.com/rust-lang/rust/pull/72348/checks?check_run_id=700945715#step:24:1208

**Comment by chrissimpkins** [comment]
@estebank I think that we are gtg here

File: src/librustc_parse/parser/diagnostics.rs (hunk 5 above)
Comment (chrissimpkins) [reply src/librustc_parse/parser/diagnostics.rs]: I am collecting this information and plan to add it to the rustc-dev-guide diagnostics documentation.

**Comment by estebank** [comment]
LGTM. Can we squash all commits into a single commit for log cleanliness sake? Other than that, r=me

**Comment by chrissimpkins** [comment]
Squashed to https://github.com/rust-lang/rust/commit/f384cdcbecf46db38e46177700d29e881dcb53b7

**Comment by chrissimpkins** [comment]
> @chrissimpkins: 🔑 Insufficient privileges: Not in reviewers

@estebank ^^
