### PR TITLE
Neither require nor imply lifetime bounds on opaque type for well formedness

### LINKED ISSUE #84305: Opaque `impl Trait` return types unsoundly ignoring lifetime constraints
```rust
trait StaticDefaultRef: 'static {
    fn default_ref() -> &'static Self;
}

impl StaticDefaultRef for str {
    fn default_ref() -> &'static str {
        ""
    }
}

fn into_impl(x: &str) -> &(impl ?Sized + AsRef<str> + StaticDefaultRef + '_) {
    x
}

fn extend_lifetime<'a>(x: &'a str) -> &'static str {
    let t = into_impl(x);
    helper(|_| t)
}

fn helper<T: ?Sized + AsRef<str> + StaticDefaultRef>(f: impl FnOnce(&T) -> &T) -> &'static str {
    f(T::default_ref()).as_ref()
}

fn main() {
    let r;
    {
        let x = String::from("Hello World?");
        r = extend_lifetime(&x);
    }
    println!("{}", r);
}
```
([playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=15e60236475397e321b393dc4f72954f))
```
�j�0V
```

So IMO the biggest problem in the code above is that the opaque type returned by `into_impl` implements `StaticDefaultRef` even though its lifetime is `'_`, i.e. _not_ `'static`.

This particular code only compiles since `1.45`, so this might be a regression.

@rustbot modify labels: T-compiler, A-impl-trait, A-lifetimes, A-typesystem
and someone please add “I-unsound 💥”.

### LINKED ISSUE #86218: Min TAIT + GAT lifetime issue
I tried this code:
https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=71e56b49edea6de440eed3a417322308

Code that is an equivalent to the one above, but that compiles: https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=f071b171eda8921c1d4902999417594d

I'm not sure about the exact reason for this to happen, but I can suspect the presence of an additional lifetime in impl block that is causing this bug.

I expected to see this happen: It compiles

Instead, this happened: Lifetime error

### Meta
`rustc --version --verbose`: Latest playground version

### PR DESCRIPTION
**Pull request by oli-obk**
The actual hidden type can live arbitrarily longer than any individual lifetime and arbitrarily shorter than all but one of the lifetimes.

fixes #86218
fixes #84305

This is a **breaking change** but it is a necessary soundness fix

### CODE REVIEW

**Comment by oli-obk** [comment]
When the compiler encounters a `&'b OpaqueType<'a>` it assumes that `'a: 'b`. This is not correct though, as the hidden type of the opaque type may be `()`, so one can produce an `&'b OpaqueType<'a>` simply by providing any `&'b ()`. Most of the time this is not an issue as creating a `&'b OpaqueType<'a>` constrains everything else with the same lifetimes, so one can indeed rely on `'a: 'b`. An example where the check work is

```rust
    type OpaqueType<'a> = impl Send;
    fn convert<'a, 'b, T: ?Sized>(x: &'a T, _proof: &'b OpaqueType<'a>) -> &'b T {
        x
    }
    let r;
    {
        let x = String::from("Hello World?");
        r = convert(&x, &()); // error `x` must live for `'static`
    }
    println!("{}", r);
```

The more complex example in https://github.com/rust-lang/rust/issues/84305#issuecomment-828805784 demonstrates that with sufficient associated type indirection this error can be avoided.

**Comment by oli-obk** [comment]
@bors try

preparing for crater check run, as this is a breaking change

File: src/test/ui/generic-associated-types/bugs/issue-86218.rs [hunk 1]
```diff
@@ -1,7 +1,4 @@
-// check-fail
-// known-bug
-
-// This should pass, but seems to run into a TAIT issue.
+// check-pass
```
Comment (jackh726) [inline src/test/ui/generic-associated-types/bugs/issue-86218.rs:1]: Can you also move this into the parent directory? The intention was for this to be "known-bugs", but I guess I could have named better.

**Comment by jackh726** [comment]
> When the compiler encounters ...

This comment is helpful, thanks! Will think a bit about this when I get some time.

**Comment by b-naber** [comment]
Does this also fix https://github.com/rust-lang/rust/issues/42940?

**Comment by oli-obk** [comment]
@craterbot check

**Comment by oli-obk** [comment]
This is a breaking change, fixing a soundness bug. Crater found no regressions.

TLDR: `&'b OpaqueType<'a>` currently implies `'a: 'b`, even though that isn't necessarily true if the opaque type's hidden type does not have any lifetimes, thus causing unsoundness. After this PR, we don't imply that this outlives bound holds anymore.

A moderately longer explanation of what is going on can be found in [this earlier comment on this PR](https://github.com/rust-lang/rust/pull/95474#issuecomment-1084669797). An example of code that will now fail to compile is the newly added test. Note that it will also break cases that accidentally use this soundly.

**Comment by jackh726** [comment]
Let's wait for lang team decision until I review.

**Comment by oli-obk** [comment]
ping @scottmcm 

Afaict https://github.com/rust-lang/triagebot/blob/330a7ccb6aa4fe6a81657d8c51fefe78f05bf9f9/src/agenda.rs#L515 should be picking up this PR, but it hasn't been on the agenda at all afaict. I'll run triagebot locally tomorrow to debug this, but I wanted to bring this up for the lang team directly now thus the ping

**Comment by nikomatsakis** [comment]
@rfcbot fcp merge

We discussed this in the @rust-lang/lang meeting today and agreed this was a clear bug fix.

**Comment by nikomatsakis** [comment]
@rfcbot concern good-relnotes-writeup

I agreed to write a good relnotes writeup

**Comment by nikomatsakis** [comment]
@rfcbot cancel

wrong team label dang it

**Comment by nikomatsakis** [comment]
@rfcbot fcp merge

We discussed this in the @rust-lang/lang meeting today and agreed this was a clear bug fix.

**Comment by nikomatsakis** [comment]
@rfcbot concern good-relnotes-writeup

I agreed to write a good relnotes writeup

**Comment by aliemjay** [comment]
I think this is wrong. Given the rules from RFC 1214 and how we currently check impls for well-formedness, I believe we must always be able to conclude `'a: 'b` from `Ty<'a>: 'b`, for any generic type `Ty`.

The argument is this: Given a generic opaque type `Ty<'a>`
```rust
type Ty<'a> = impl Future;
```
If we know `Ty<'a>: 'static`, then RFC 1214 allows us to safely assume `<Ty<'a> as Future>::Output: 'static` but that's obviously wrong!

I came across the same problem in #84366.

**Comment by nikomatsakis** [comment]
@aliemjay The rules are actually a bit more subtle. We actually have a concept of a *constrained* lifetime -- for a lifetime to appear in the value of an associated type, it must be constrained. Lifetimes that appear in a projection, for example, are not constrained, which is why this code will not build ([playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=434ad5d8e347dcf682d4e8a0de8a2875)):

```rust
trait Mirror<'a> {
    type Item;
}

impl<'a, T> Mirror<'a> for T {
    type Item = T;
}

trait AnotherTrait { 
    type Blah;
}

impl<'a> AnotherTrait for <u32 as Mirror<'a>>::Item {
    type Blah = &'a u32;
}
```

Still, you raise a good point, @oli-obk, we should be sure to add tests that ensure we are handling this case correctly for opaque types! I.e., we want to be sure that lifetimes which appear in an opaque type are not considered constrained.

**Comment by nikomatsakis** [comment]
For the release notes:

The compiler was incorrectly applying implied bounds for `impl Trait` and opaque types that could lead to unsound code being accepted (e.g. because `&'a impl Trait<'b>` was assumed to mean that `'b: 'a` must hold). It is difficult to construct a small example illustrating the problem; complex examples can be found in #84305. Crater tests found no regressions.

**Comment by nikomatsakis** [comment]
I was trying to make a nice example illustrating the problem and failed. [Here is one attempt](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=ae5fa2561cbf1f4bc1c7fb5ca92bddfd) -- I have to read the original issue, I may have a slightly broken mental model of what is going on here.

**Comment by aliemjay** [comment]
I believe no unconstraining lifetime is needed. This is what I mean:

```rust
trait Tr { type Assoc; }
impl<'a> Tr for &'a str { type Assoc = &'a str; }

type OpaqueTy<'a> = impl Tr;
fn defining(s: &str) -> OpaqueTy<'_> { s }

// now we must be able to conclude `'a: 'static` from `Opaque<'a>: 'static`
```

**Comment by aliemjay** [comment]
Another weird thing is that type parameters are now treated differently: `Ty<A>: 'static` still implies `A: 'static`.
```rust
// FAIL
mod test_lifetime_param {
    type Ty<'a> = impl Sized;
    fn defining(a: &str) -> Ty<'_> { a }
    fn assert_static<'a: 'static>() {}
    fn test<'a>() where Ty<'a>: 'static { assert_static::<'a>() }
}

// PASS
mod test_type_param {
    type Ty<A> = impl Sized;
    fn defining<A>(s: A) -> Ty<A> { s }
    fn assert_static<A: 'static>() {}
    fn test<A>() where Ty<A>: 'static { assert_static::<A>() }
}
```

**Comment by aliemjay** [comment]
Giving it more thought, I see nothing obviously wrong about this fix. Sorry for the disturbing you!

But here is why it looked suspicious to me (you can consider it as a user experience report for the subtleties introduced in this change):


- It breaks my mental model that `GenericTy<'a, A>: 'lt` always implies/requires `'a: 't` and `A: 'lt`, which I thought was true because of RFC 1214 and because I expect all lifetime/type parameters to be constraining.

- The only exception to above rule, as far as I know, is `FnDef` types with early-bound lifetimes and it leads to the unsoundness in #84366. Exactly because `my_fn::<'a>: 'static` doesn't require `'a: 'static`!

- The special treament of type vs lifetime parameters as noted in the comment above, was also surprising.

**Comment by nikomatsakis** [comment]
> Another weird thing is that type parameters are now treated differently: Ty<A>: 'static still implies A: 'static.

So, I was reading the PR and wondering about this. I might be a bit confused about what's going on here, but I would expect that opaque types should behave more like projection types.

**Comment by oli-obk** [comment]
> Another weird thing is that type parameters are now treated differently: `Ty<A>: 'static` still implies `A: 'static`.

oof yea, this will allow the same unsoundness ([To be sure, I tried it out locally and on playground and yes, that will just work around the issue](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=e5f77dca6b260f0cbd72ccb6a43c002a)

**Comment by jackh726** [comment]
FCP is still using wrong team. Need to readd compiler team, cancel, remove compiler team, and then restart.

**Comment by oli-obk** [comment]
@rfcbot cancel

**Comment by nikomatsakis** [comment]
@rfcbot fcp merge

We discussed this in the https://github.com/orgs/rust-lang/teams/lang meeting today and agreed this was a clear bug fix.

File: compiler/rustc_infer/src/infer/outlives/components.rs [hunk 2]
```diff
@@ -71,6 +71,26 @@ fn compute_components<'tcx>(
...
+                            }
+                            _ => (),
+                        }
+                    }
+                    GenericArgKind::Lifetime(_) => {}
+                    GenericArgKind::Const(_) => {
+                        compute_components_recursive(tcx, ty, out, visited);
+                    }
+                }
+            },
```
Comment (nikomatsakis) [inline compiler/rustc_infer/src/infer/outlives/components.rs:93]: I suggest we approach this the same way we do for projections:

Push a "opaque-component" and then skip over the contents in some cases, expand in others. I can supply more links if desired. :)

**Review by nikomatsakis — CHANGES_REQUESTED** [review]

File: src/test/ui/generic-associated-types/issue-86218.rs [hunk 3]
```diff
@@ -21,7 +18,8 @@ trait Yay<AdditionalValue> {
 
 impl<'a> Yay<&'a ()> for () {
     type InnerStream<'s> = impl Stream<Item = i32> + 's;
-    fn foo<'s>() -> Self::InnerStream<'s> { todo!() }
+    //^ ERROR does not fulfill the required lifetime
+    fn foo<'s>() -> Self::InnerStream<'s> { () }
```
Comment (aliemjay) [inline src/test/ui/generic-associated-types/issue-86218.rs:22]: I think this indeed should pass, but it fails because the opaque type erroneously captures `'a`. See #96996. So #86218 probably shouldn't be closed.

**Review by aliemjay — COMMENTED** [review]
Found a regression while testing:
```rust
type Ty<'a, A> = impl Sized + 'a;
fn defining<'a, A>() -> Ty<'a, A> {}
fn assert_static<T: 'static>() {}
fn test<'a, A>() where Ty<'a, A>: 'static, { assert_static::<Ty<'a, A>>() }
```

Surprisingly, this now fails! `Ty<T>: 'static` no longer implies `Ty<T>: 'static` :confused:

**Comment by oli-obk** [comment]
yes, this is very much WIP. I am currently implementing the proposal from https://github.com/rust-lang/rust/pull/95474#discussion_r871569010 but it is rather involved and I also want to make sure not to just copy past the projection logic but share code where applicable

File: src/test/ui/generic-associated-types/issue-86218.rs (hunk 3 above)
Comment (aliemjay) [reply src/test/ui/generic-associated-types/issue-86218.rs:22]: Thinking more about it, now I believe it should pass with this PR even if the opaque type captures `'a` (which is another bug but entirely orthogonal). With this PR we should be able to infer `Opaque<'s, 'a>: 's` even if `'a: 's` doesn't hold, right?

Here's an test using type parameters instead to make it clear. I expect it to pass with this PR but it doesn't:
```rust
#![feature(generic_associated_types)]
#![feature(type_alias_impl_trait)]

pub trait Stream {
    type Item;
}

impl Stream for () {
    type Item = i32;
}

trait Yay<AdditionalValue> {
    type InnerStream<'s>: Stream<Item = i32> + 's;
    fn foo<'s>() -> Self::InnerStream<'s>;
}

impl<I> Yay<I> for () {
    type InnerStream<'s> = impl Stream<Item = i32> + 's;
    fn foo<'s>() -> Self::InnerStream<'s> { () }
}

fn main() {}
```

**Comment by oli-obk** [comment]
Got a bit further, but still needs more work

File: compiler/rustc_infer/src/infer/outlives/obligations.rs [hunk 4]
```diff
@@ -392,23 +429,11 @@ where
         // the problem is to add `T: 'r`, which isn't true. So, if there are no
         // inference variables, we use a verify constraint instead of adding
         // edges, which winds up enforcing the same condition.
-        let needs_infer = projection_ty.needs_infer();
+        let needs_infer = substs.needs_infer();
         if approx_env_bounds.is_empty() && trait_bounds.is_empty() && needs_infer {
```
Comment (aliemjay) [inline compiler/rustc_infer/src/infer/outlives/obligations.rs:433]: The rationale for `&& need_infer` in the previous comment doesn't seem to apply to RPITs, because the type cannot be named anyway, so the user will  eventually need to specify the bounds on the components rater than on the opaque type.

This indeed causes diagnostics regression in this case:
```rust
fn id<T>(_: T) -> impl Sized {}
fn test<T>(t: T) -> impl Sized + 'static {
    id(t)
    //^ ERROR the opaque type `id<T>::{opaque#0}` may not live long enough
}
```

But removing `needs_infer` condition for RPITs may not be a good solution either since it would prevent us from adding useful suggestions like adding explicit lifetime bounds to the opaque type (I guess!). Maybe we can improve diagnostics by some other way, at least by removing the cryptic `id<T>::{opaque#0}`.

This is  problem for TAIT as well because it shows the same cryptic error message, but I think here we want to suggest the bound `OpaqueTy<T>: 'static` rather than `T: 'static`.

**Review by aliemjay — COMMENTED** [review]
This should now fix #42940 :tada:. Thanks!

File: compiler/rustc_infer/src/infer/outlives/verify.rs [hunk 5]
```diff
@@ -119,66 +133,49 @@ impl<'cx, 'tcx> VerifyBoundCx<'cx, 'tcx> {
...
-    pub fn projection_declared_bounds_from_trait(
-        &self,
-        projection_ty: ty::ProjectionTy<'tcx>,
-    ) -> impl Iterator<Item = ty::Region<'tcx>> + 'cx + Captures<'tcx> {
-        self.declared_projection_bounds_from_trait(projection_ty)
-    }
-
-    pub fn projection_bound(
+    #[instrument(level = "debug", skip(self, visited))]
+    fn env_bounds(
```
Comment (aliemjay) [inline compiler/rustc_infer/src/infer/outlives/verify.rs:151]: `env_bounds` sounds misleading to me, because it applies verify bounds from TraitRef and for individual substs as well. `projection_opaque_bounds` might be more suitable.

File: compiler/rustc_infer/src/infer/outlives/verify.rs [hunk 6]
```diff
@@ -282,15 +279,15 @@ impl<'cx, 'tcx> VerifyBoundCx<'cx, 'tcx> {
     ///
     /// then this function would return `'x`. This is subject to the
     /// limitations around higher-ranked bounds described in
-    /// `region_bounds_declared_on_associated_item`.
-    fn declared_projection_bounds_from_trait(
+    /// `declared_region_bounds`.
+    #[instrument(level = "debug", skip(self))]
+    pub fn bounds(
```
Comment (aliemjay) [inline compiler/rustc_infer/src/infer/outlives/verify.rs:284]: I find the previous name more descriptive. Maybe we can generalize it to `declared_bounds_from_(trait|definition)`.

Perhaps it's good to inline `declared_region_bounds` too?

**Review by aliemjay — COMMENTED** [review]
Some nitpicking follows :sweat_smile: .

I'm happy to apply them myself in a followup PR if you like.

File: compiler/rustc_infer/src/infer/outlives/obligations.rs [hunk 7]
```diff
@@ -324,17 +327,57 @@ where
...
+    #[instrument(level = "debug", skip(self, filter))]
+    fn generic_must_outlive(
+        &mut self,
+        origin: infer::SubregionOrigin<'tcx>,
+        region: ty::Region<'tcx>,
+        generic: GenericKind<'tcx>,
+        def_id: DefId,
+        substs: SubstsRef<'tcx>,
+        filter: impl Fn(Ty<'tcx>) -> (DefId, SubstsRef<'tcx>),
+    ) {
```
[the remark this answers is not in the document]
Comment (oli-obk) [reply compiler/rustc_infer/src/infer/outlives/obligations.rs:374]: Yea, I was worried about performance here, which is why I wanted to get a baseline perf run with the current version, the problem is that I broke a stable crate :(

```rust
use std::pin::Pin;
use std::future::Future;

pub struct ReusableBoxFuture<'a, T> {
    boxed: Pin<Box<dyn Future<Output = T> + 'a>>,
}

impl<'a, T> ReusableBoxFuture<'a, T> {
    pub fn new<F>(future: F) -> Self
    where
        F: Future<Output = T> + 'a,
    {
        unimplemented!()
    }
}

fn new<T>() -> ReusableBoxFuture<'static, T> {
    ReusableBoxFuture::new(async { unreachable!() })
}

fn main() {
}
```

errors with

```
error[E0310]: the opaque type `from_generator<[static generator@/home/ubuntu/rust4/src/test/ui/type-alias-impl-trait/implied_bounds3.rs:22:34: 22:52]>::{opaque#0}` may not live long enough
  --> /home/ubuntu/rust4/src/test/ui/type-alias-impl-trait/implied_bounds3.rs:22:5
   |
LL |     ReusableBoxFuture::new(async { unreachable!() })
   |     ^^^^^^^^^^^^^^^^^^^^^^
   |
   = help: consider adding an explicit lifetime bound `from_generator<[static generator@/home/ubuntu/rust4/src/test/ui/type-alias-impl-trait/implied_bounds3.rs:22:34: 22:52]>::{opaque#0}: 'static`...
   = note: ...so that the type `impl Future<Output = T>` will meet its required lifetime bounds...
note: ...that is required by this bound
  --> /home/ubuntu/rust4/src/test/ui/type-alias-impl-trait/implied_bounds3.rs:15:33
   |
LL |         F: Future<Output = T> + 'a,
   |    
```

**Review by estebank — COMMENTED** [review]
(Just some drive by nitpicks/stray thoughts on the output.)

File: compiler/rustc_infer/src/infer/outlives/obligations.rs (hunk 7 above)
[the remark this answers is not in the document]
Comment (oli-obk) [reply compiler/rustc_infer/src/infer/outlives/obligations.rs:374]: Minimized to

```rust
fn foo<F>(_: F)
where
    F: 'static,
{
}

fn from<F: Send>(f: F) -> impl Send {
    f
}

fn bar<T>() {
    foo(from(|| ()))
}
```

giving the following error

```
error[E0310]: the opaque type `from<[closure@/home/ubuntu/rust4/src/test/ui/type-alias-impl-trait/implied_bounds3.rs:16:14: 16:19]>::{opaque#0}` may not live long enough
  --> /home/ubuntu/rust4/src/test/ui/type-alias-impl-trait/implied_bounds3.rs:16:5
   |
LL |     foo(from(|| ()))
   |     ^^^^^^^^^^^^^^^^
   |
   = help: consider adding an explicit lifetime bound `from<[closure@/home/ubuntu/rust4/src/test/ui/type-alias-impl-trait/implied_bounds3.rs:16:14: 16:19]>::{opaque#0}: 'static`...
   = note: ...so that the type `impl Send` will meet its required lifetime bounds
```

This is because with this PR we don't consider the fact that calling `from` with `F` being the type of the `|| ()` closure, we should be able to know that the return type of `from` must outlive `'static` because `F` outlives `'static`. But we explicitly avoid inferring this kind of information, as it is unsound to do.

Now... the above snippet works on stable, so we shouldn't break it, especially since it *is* sound for return position impl trait. It's just that the very same thing would be unsound for return position impl trait.

Changing the example to

```rust
fn from<'a, F: Send + 'a>(f: F) -> impl Send + 'a {
    f
}
```

makes it compile again right now, since now we can sanely infer that the return type outlives `'static` just by knowing `F: 'static`.

Now... I'm going to add some logic to allow return position impl trait to look at its generic parameters to imply lifetime bounds that hold, just so we have back compat. But we need to look into it more to figure out whether this divergence between RPIT and TAIT is desirable.

[the remark this answers is not in the document]
Comment (aliemjay) [reply compiler/rustc_infer/src/infer/outlives/obligations.rs:374]: I believe #97406 is sufficient to fix this regression. Am I missing something?

Can you experiment with merging #97406 here, just to get perf run and perhaps another crater run?

File: compiler/rustc_typeck/src/outlives/utils.rs [hunk 8]
```diff
@@ -96,6 +96,39 @@ pub fn insert_outlives_predicate<'tcx>(
                             .or_insert(span);
                     }
 
+                    Component::Opaque(def_id, substs) => {
+                        for predicate in tcx.item_bounds(def_id) {
+                            let predicate = EarlyBinder(predicate).subst(tcx, substs);
+                            // FIXME(oli-obk): fishy skip-binder
+                            match predicate.kind().skip_binder() {
+                                ty::PredicateKind::Trait(tp) => {
```
Comment (aliemjay) [inline compiler/rustc_typeck/src/outlives/utils.rs:104]: This doesn't look right to me. Can we just treat them just like projections? - bubble them up and force the user to specify the bound explicitly.  At least this is what I expect at this point.

Here's a test to that now crashes with  a stack overflow because the opaque type is found in `trait_ref.substs`:
```rust
#![feature(type_alias_impl_trait)]
type Opaque<T> = impl Sized;
fn defining<T>() -> Opaque<T> {}
struct Ss<'a, T>(&'a Opaque<T>);
```
I expect it to require `where Opaque<T>: 'a` in struct definition.

Another problem that emerges is the case of opaque type with no generic params. - They're clearly 'static but they would still require an explicit bound `Opaque: 'a`. Maybe we can exclude them.

File: src/test/ui/type-alias-impl-trait/implied_bounds_closure.stderr [hunk 9]
```diff
@@ -0,0 +1,11 @@
+error: lifetime may not live long enough
+  --> $DIR/implied_bounds_closure.rs:17:16
+   |
+LL | fn extend_lifetime<'a>(x: &'a str) -> &'static str {
+   |                    -- lifetime `'a` defined here
+LL |     let t = into_impl(x);
+LL |     helper(|_| t)
+   |                ^ returning this value requires that `'a` must outlive `'static`
```
Comment (estebank) [inline src/test/ui/type-alias-impl-trait/implied_bounds_closure.stderr:8]: *(Non blocking)* It seems that we are either not properly tracking or not displaying the Obligations involved here, where we should likely be pointing at `helper`'s `'static` obligation introduction.

File: compiler/rustc_infer/src/infer/outlives/obligations.rs (hunk 7 above)
[the remark this answers is not in the document]
Comment (oli-obk) [reply compiler/rustc_infer/src/infer/outlives/obligations.rs:374]: yes that did the trick! thanks!

File: src/test/ui/type-alias-impl-trait/implied_bounds_closure.stderr (hunk 9 above)
Comment (compiler-errors) [reply src/test/ui/type-alias-impl-trait/implied_bounds_closure.stderr:8]: i think this is a consequence of NLL stabilization

**Comment by oli-obk** [comment]
This is ready now, but blocked on https://github.com/rust-lang/rust/pull/97406

File: src/test/ui/generic-associated-types/issue-86218.rs [hunk 10]
```diff
@@ -21,7 +18,8 @@ trait Yay<AdditionalValue> {
 
 impl<'a> Yay<&'a ()> for () {
     type InnerStream<'s> = impl Stream<Item = i32> + 's;
-    fn foo<'s>() -> Self::InnerStream<'s> { todo!() }
+    //^ ERROR does not fulfill the required lifetime
```
Comment (ivan770) [inline src/test/ui/generic-associated-types/issue-86218.rs:21]: Is this an intended behaviour? In the original issue it's noted, that with a separate type alias code compiles.

File: src/test/ui/type-alias-impl-trait/implied_bounds_closure.stderr (hunk 9 above)
Comment (estebank) [reply src/test/ui/type-alias-impl-trait/implied_bounds_closure.stderr:8]: Interestingly, we don't have *too* much obligation information at all:

```
DEBUG rustc_borrowck::diagnostics::region_errors report_region_error(fr='_#1r, outlived_fr='_#0r)
DEBUG rustc_borrowck::diagnostics::region_errors report_region_error: category=Return(Normal) ObligationCause { span: f43.rs:17:16: 17:17 (#0), body_id: HirId { owner: DefId(0:0 ~ f43[1164]), local_id: 0 }, code: InternedObligationCauseCode { code: None } } None
DEBUG rustc_borrowck::diagnostics::region_errors report_region_error: fr_is_local=true outlived_fr_is_local=false category=Return(Normal)
┐rustc_borrowck::diagnostics::region_errors::report_general_error errci=ErrorConstraintInfo { fr: '_#1r, fr_is_local: true, outlived_fr: '_#0r, outlived_fr_is_local: false, category: Return(Normal), span: f43.rs:17:16: 17:17 (#0) }
┘
```

Comment (estebank) [reply src/test/ui/type-alias-impl-trait/implied_bounds_closure.stderr:8]: Oh, that's why

https://github.com/rust-lang/rust/blob/3c9765cff18a3c4ba2962ea59d4c3f6966f9700c/compiler/rustc_borrowck/src/region_infer/mod.rs#L2077-L2096

File: src/test/ui/generic-associated-types/issue-86218.rs (hunk 10 above)
Comment (oli-obk) [reply src/test/ui/generic-associated-types/issue-86218.rs:21]: nope, but it is consistent until we address https://github.com/rust-lang/rust/issues/96996

**Comment by jackh726** [comment]
@oli-obk is this just waiting on final review and r+?

**Comment by oli-obk** [comment]
Yes

**Comment by aliemjay** [comment]
I think we need to re-run crater. This PR introduced more breakages since the last time we ran crater.

One breakage I immediately see is when the opaque type has multiple declared lifetime bounds `+ 'a + 'b`:
```rust
fn opaque<'a, 'b>() -> impl Sized + 'a + 'b {}

fn want_static<T: 'static>(_: T) {}

fn main() {
    want_static(opaque());
    //~^ ERROR the opaque type `opaque<'_, '_>::{opaque#0}<'_, '_>` may not live long enough.

}
```

Side note: I think we may want to mention this breakage in the release notes with the reasoning that lifetime inference for `'a` and `'b` is ambiguous, and thus is rejected.
```rust
fn opaque<'a, 'b>() -> impl Sized + 'a + 'b {}

fn want_static<T: 'static>(_: T) {}

fn main() {
    // This fails because lifetime inference is ambiguous
    want_static(opaque::<'_, '_>());

    // lifetime annotation is required to choose one of the possible solutions
    want_static(opaque::<'static, '_>());
    want_static(opaque::<'_, 'static>());
    want_static(opaque::<'static, 'static>());
}
```

**Comment by jackh726** [comment]
Do we want to rerun crater @oli-obk?

**Comment by oli-obk** [comment]
@craterbot check

**Comment by estebank** [comment]
I've been seeing a lot of libc build failures in crater runs... I wonder what that's about.

```
[INFO] [stdout] error[E0309]: the opaque type `validate_post_dispute_for_existing_tx<impl Disputable, T>::{opaque#0}` may not live long enough
[INFO] [stdout]    --> src/validate.rs:245:13
[INFO] [stdout]     |
[INFO] [stdout] 245 |             validate_post_dispute_for_existing_tx(post, disputed_tx, accounts, disputes)
[INFO] [stdout]     |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[INFO] [stdout]     |
[INFO] [stdout]     = help: consider adding an explicit lifetime bound `validate_post_dispute_for_existing_tx<impl Disputable, T>::{opaque#0}: 't`...
[INFO] [stdout]     = note: ...so that the type `impl Disputable` will meet its required lifetime bounds
```
```
[INFO] [stdout] error[E0310]: the parameter type `T` may not live long enough
[INFO] [stdout]    --> src/nn/mod.rs:635:20
[INFO] [stdout]     |
[INFO] [stdout] 635 |         I::Output: Into<VarDiff<T, U>>,
[INFO] [stdout]     |                    ^^^^^^^^^^^^^^^^^^^ ...so that the type `T` will meet its required lifetime bounds...
[INFO] [stdout]     |
[INFO] [stdout] note: ...that is required by this bound
[INFO] [stdout]    --> src/variable/vardiff.rs:49:15
[INFO] [stdout]     |
[INFO] [stdout] 49  |     T: Data + 'static,
[INFO] [stdout]     |               ^^^^^^^
[INFO] [stdout] help: consider adding an explicit lifetime bound...
[INFO] [stdout]     |
[INFO] [stdout] 636 |         T: Data<Dim = Ix2> + 'static,
[INFO] [stdout]     |                            +++++++++
[INFO] [stdout] 
[INFO] [stdout] 
[INFO] [stdout] error[E0310]: the parameter type `U` may not live long enough
[INFO] [stdout]    --> src/nn/mod.rs:635:20
[INFO] [stdout]     |
[INFO] [stdout] 635 |         I::Output: Into<VarDiff<T, U>>,
[INFO] [stdout]     |                    ^^^^^^^^^^^^^^^^^^^ ...so that the type `U` will meet its required lifetime bounds...
[INFO] [stdout]     |
[INFO] [stdout] note: ...that is required by this bound
[INFO] [stdout]    --> src/variable/vardiff.rs:50:31
[INFO] [stdout]     |
[INFO] [stdout] 50  |     U: Gradient + Overwrite + 'static,
[INFO] [stdout]     |                               ^^^^^^^
[INFO] [stdout] help: consider adding an explicit lifetime bound...
[INFO] [stdout]     |
[INFO] [stdout] 637 |         U: Gradient<Dim = Ix2> + Overwrite + 'static,
[INFO] [stdout]     |                                            +++++++++
```

**Comment by aliemjay** [comment]
From a quick scan I can recognize two types of regressions:
1. `sycamore`, `neuronika` and  `payments-engine-example` all boils down to this example passing on stable because of implied bounds and the fact that RPIT captures all type parameters:
```rust
fn assert_static<T: 'static>() {}

fn test<T>() -> &'static impl Sized {
    assert_static::<T>(); // True because `T: 'static` was an elaboration of `WF(&'static Rpit<T>)`
    &()
}
```
I haven't tested it though.

Another thing to note is the shameful error message from `payments-enging-example`:
```
error[E0309]: the opaque type `validate_post_dispute_for_existing_tx<impl Disputable, T>::{opaque#0}` may not live long enough
   --> src/validate.rs:245:13
    |
245 |             validate_post_dispute_for_existing_tx(post, disputed_tx, accounts, disputes)
    |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = help: consider adding an explicit lifetime bound `validate_post_dispute_for_existing_tx<impl Disputable, T>::{opaque#0}: 't`...
    = note: ...so that the type `impl Disputable` will meet its required lifetime bounds
```



2.  `syn` failures. I haven't looked into these.

All others looks spurious build script failures.

**Comment by oli-obk** [comment]
The payments-enging-example failure looks to me like `&'t impl Foo` can't be used for another `&'t impl Foo` because we don't realize the first one must outlive `'t` as it's behind a reference of said lifetime. So something like

```rust
trait Foo {}
fn foo<'a>(x: &'a impl Foo) -> &'a impl Foo { x }
fn bar<'a>(x: &'a impl Foo) -> &'a impl Foo { foo(x) }
```

Where the return value of the call to `foo` is a reference to an opaque type. Then that value is used as the hidden type of a reference to another opaque type, but now we can't prove that the `foo`'s return type outlives 'a, because we stopped considering the lifetimes on `foo`. We can still figure out that `foo`'s opaque type outlives `'a` though, as it's behind a `&'a`, I just don't know if this knowledge is exploitable that way to make the given example compile again

**Comment by aliemjay** [comment]
> So something like

This example _does_ compile under this branch as expected!

I believe the example I put  is more correctly representing these regressions; `OpaqueTy<T>: 'a` (from fn sig)  no longer implies `T: 'a` and that's the intended behavior and is necessary for the soundness fix.

**Comment by oli-obk** [comment]
I created PRs to all three actual regressions so they can adjust their impl ahead of time (and in case of `sycamore` maybe even yank the only published non-beta version with the problem)

**Comment by oli-obk** [comment]
@rfcbot merge

This PR fixes a soundness bug by making `&'b WithLifetime<'a>` not imply `'a` outlives `'b` anymore.
This is a breaking change for completely fine code, too, as people have been relying on `&'x impl Trait` implying that all generic type parameters (which are captured implicitly) of the function outlive `'x`. Now they must explicitly mention `&'x impl Trait + 'x` for that to be true.

The breakage on crater was minimal (3 failures, one of which is already not relevant anymore as the crate owner has changed the code enough already for this to be a non issue, and one already got the fix merged and published to crates.io). All failures have trivial fixes (which are also suggested by rustc) and I have created PRs against the crates to fix the issue.

**Comment by oli-obk** [comment]
@rfcbot fcp merge

This PR fixes a soundness bug by making &'b WithLifetime<'a> not imply 'a outlives 'b anymore.
This is a breaking change for completely fine code, too, as people have been relying on &'x impl Trait implying that all generic type parameters (which are captured implicitly) of the function outlive 'x. Now they must explicitly mention &'x impl Trait + 'x for that to be true.

The breakage on crater was minimal (3 failures, one of which is already not relevant anymore as the crate owner has changed the code enough already for this to be a non issue, and one already got the fix merged and published to crates.io). All failures have trivial fixes (which are also suggested by rustc) and I have created PRs against the crates to fix the issue.

**Comment by oli-obk** [comment]
This PR fixes a soundness bug by making &'b WithLifetime<'a> not imply 'a outlives 'b anymore.
This is a breaking change for completely fine code, too, as people have been relying on &'x impl Trait implying that all generic type parameters (which are captured implicitly) of the function outlive 'x. Now they must explicitly mention &'x impl Trait + 'x for that to be true.

The breakage on crater was minimal (3 failures, one of which is already not relevant anymore as the crate owner has changed the code enough already for this to be a non issue, and one already got the fix merged and published to crates.io). All failures have trivial fixes (which are also suggested by rustc) and I have created PRs against the crates to fix the issue.

@rfcbot merge

**Comment by oli-obk** [comment]
@rfcbot merge

**Comment by oli-obk** [comment]
This PR fixes a soundness bug by making &'b WithLifetime<'a> not imply 'a outlives 'b anymore.
This is a breaking change for completely fine code, too, as people have been relying on &'x impl Trait implying that all generic type parameters (which are captured implicitly) of the function outlive 'x. Now they must explicitly mention &'x impl Trait + 'x for that to be true.

The breakage on crater was minimal (3 failures, one of which is already not relevant anymore as the crate owner has changed the code enough already for this to be a non issue, and one already got the fix merged and published to crates.io). All failures have trivial fixes (which are also suggested by rustc) and I have created PRs against the crates to fix the issue.

@rfcbot pr merge

**Comment by oli-obk** [comment]
@rfcbot cancel

**Comment by oli-obk** [comment]
@rfcbot merge

File: compiler/rustc_infer/src/infer/error_reporting/mod.rs [hunk 11]
```diff
@@ -2349,6 +2349,14 @@ impl<'a, 'tcx> InferCtxt<'a, 'tcx> {
                     None
                 }
             }
+            GenericKind::Opaque(def_id, _substs) => {
+                // Avoid emitting a `... so that the type` message at the error site.
+                // It would be out of order for return position impl trait
+                origin = None;
+                // Make sure the lifetime suggestion is on the RPIT instead of proposing
+                // to add a bound for opaque types (which isn't possible)
+                Some((self.tcx.def_span(def_id).shrink_to_hi(), true))
```
Comment (aliemjay) [inline compiler/rustc_infer/src/infer/error_reporting/mod.rs:2358]: This would suggest making changes at the opaque type's definition site and the suggested lifetime probably cannot be named in that scope.

I still think removing the `need_infer` hack for opaque types in https://github.com/rust-lang/rust/pull/95474/files#r880479741 is the way to go. After all it's just a diagnostics hack for projection types only.

for example:
```rust
// Now we suggest adding `+ 'static` to the RPIT here.
fn opaque<T>(_: T) -> impl Sized {}

// ... but I think we should suggest `T: 'static` here similar to the current stable.
fn test<T>(t: T) -> impl Sized + 'static {
    opaque(t)
}
```

**Review by aliemjay — CHANGES_REQUESTED** [review]

File: src/test/ui/type-alias-impl-trait/implied_lifetime_wf_check3.rs [hunk 12]
```diff
@@ -0,0 +1,42 @@
...
+
+mod test_type_param {
+    type Ty<A> = impl Sized;
+    fn defining<A>(s: A) -> Ty<A> { s }
+    fn assert_static<A: 'static>() {}
+    fn test<A>() where Ty<A>: 'static { assert_static::<A>() }
+}
+
+mod test_type_param_static {
+    type Ty<A> = impl Sized + 'static;
```
Comment (aliemjay) [inline src/test/ui/type-alias-impl-trait/implied_lifetime_wf_check3.rs:35]: either remove this test or move it into separate file so that all other tests here fail as expected.

File: src/test/ui/type-alias-impl-trait/implied_lifetime_wf_check3.rs [hunk 13]
```diff
@@ -0,0 +1,42 @@
...
+    //~^ ERROR: the parameter type `A` may not live long enough
+    fn defining<A: 'static>(s: A) -> Ty<A> { s }
+    fn assert_static<A: 'static>() {}
+    fn test<A>() where Ty<A>: 'static { assert_static::<A>() }
+}
+
+fn main() {}
```
Comment (aliemjay) [inline src/test/ui/type-alias-impl-trait/implied_lifetime_wf_check3.rs:42]:
```suggestion
}

mod test_implied_from_fn_sig {
    type Opaque<T: 'static> = impl Sized;
    fn defining<T: 'static>() -> Opaque<T> {}
    fn assert_static<T: 'static>() {}
    fn test<T>(_: Opaque<T>) { assert_static::<T>(); }
}

fn main() {}
```

a check-pass test for implied bounds from fn signature.

File: src/test/ui/impl-trait/unactionable_diagnostic.rs [hunk 14]
```diff
@@ -0,0 +1,23 @@
+trait Trait {}
+
+struct Foo;
+
+impl Trait for Foo {}
+
+fn foo<'t, P>(
+    post: P,
+    x: &'t Foo,
+) -> &'t impl Trait {
```
Comment (aliemjay) [inline src/test/ui/impl-trait/unactionable_diagnostic.rs:10]:
```suggestion
fn foo<'x, P>(
    post: P,
    x: &'x Foo,
) -> &'x impl Trait {
```
If the lifetime here has a different name the error incorrectly suggest adding `+ 't` bound. This should be fixed by removing the `needs_infer` hack as I suggested earlier.

**Review by aliemjay — CHANGES_REQUESTED** [review]
A round on tests.

File: compiler/rustc_infer/src/infer/outlives/obligations.rs (hunk 4 above)
Comment (oli-obk) [reply compiler/rustc_infer/src/infer/outlives/obligations.rs:440]: Note that TAITs will be nameable, so, we do need to keep this path

Comment (aliemjay) [reply compiler/rustc_infer/src/infer/outlives/obligations.rs]: I'd leave it as it is for TAIT as well. I prefer suggesting `T: 'static` than `OpaqueTy<T>: 'static`. It's true that the later is more general but they're not really different unless `T` appears unconstrained in the hidden type, which should be a rare use case.

IMO, it's a cursed hack even for projection types. This is a diagnostic issue and should not be dealt with here. The diagnostics machinery should be smarter to suggest the two solutions.

**Review by aliemjay — APPROVED** [review]
:+1:

**Review by jackh726 — APPROVED** [review]
