### PR TITLE
Prevent foreign Rust exceptions from being caught

### LINKED ISSUE #102715: Unsoundness when a panic Rust code is caught by separetely compiled Rust code through FFI-unwind
Rust code might be able to catch foreign Rust code through FFI unwind.

a.rs:
```rust
#![crate_type = "cdylib"]
#![feature(c_unwind)]

#[no_mangle]
extern "C-unwind" fn panic() {
    panic!();
}
```

b.rs:
```rust
#![feature(c_unwind)]

#[link(name = "a")]
extern "C-unwind" {
    fn panic();
}

fn main() {
    let err = std::panic::catch_unwind(|| {
        unsafe { panic() };
    });
    match err {
        Err(v) => {
            // Able to access `Box<dyn Any>` generated by another
            // compiler; we can't guarantee that typeid does not conflict
            // across Rust versions, nor that the vtable format is
            // stable.
			// EDIT: Also this will result a `Box` allocated in one allocator
			// from being deallocated in another, which is more obviously unsound.
        }
        _ => (),
    }
}
```

These two crates *could* be compiled with different Rust versions, or same version with different flags (e.g. struct layout randomisation), and this will create unsoundness because we couldn't guarantee the ABI for separate compilations.

Currently we just use the exception class in the unwind runtime ("MOZ\0RUST") to tell apart Rust exceptions from foreign exceptions, but for soundness we need to treat Rust exception from another compilation as foreign exception as well.

### PR DESCRIPTION
**Pull request by nbdd0121**
Fix #102715

Use the address of a static variable (which is guaranteed to be unique per copy of std) to tell apart if a Rust exception comes from local or foreign Rust code, and abort for the latter.

### CODE REVIEW

File: library/panic_unwind/src/gcc.rs [hunk 1]
```diff
@@ -38,12 +38,23 @@
...
 
+// In case where multiple copies of std is compiled into a single binary,
+// we use address of this static variable to distinguish an exception raised by
+// this copy and some other copy (which needs to be treated as foreign exception).
+static CANARY: u8 = 0;
+
+// NOTE(nbdd0121)
+// Once `c_unwind` feature is stabilized, there will be ABI stability requirement
+// on this struct. The field two field must be `_Unwind_Exception` and `canary`,
+// as it may be accessed by a different version of the std with a different compiler.
```
Comment (MinerSebas) [inline library/panic_unwind/src/gcc.rs:53]: Was something accidentally deleted in this sentence?

File: library/panic_unwind/src/emcc.rs [hunk 2]
```diff
@@ -47,7 +47,12 @@ static EXCEPTION_TYPE_INFO: TypeInfo = TypeInfo {
     name: b"rust_panic\0".as_ptr(),
```
Comment (bjorn3) [inline library/panic_unwind/src/emcc.rs:47]: Maybe change it to avoid unsoundness in combination with older rust versions? Same for the exception type for the other unwinding mechanisms.

File: library/panic_unwind/src/gcc.rs [hunk 3]
```diff
@@ -38,12 +38,23 @@
...
 #[repr(C)]
 struct Exception {
     _uwe: uw::_Unwind_Exception,
+    canary: *const u8,
```
Comment (bjorn3) [inline library/panic_unwind/src/gcc.rs:57]: Maybe put the canary first such that it becomes easier to guarantee a stable order across rust versions?

Comment (bjorn3) [inline library/panic_unwind/src/gcc.rs:57]: Maybe put the canary first?

**Review by bjorn3 — CHANGES_REQUESTED** [review]

File: library/panic_unwind/src/gcc.rs (hunk 3 above)
Comment (bjorn3) [reply library/panic_unwind/src/gcc.rs:57]: Right

File: library/panic_unwind/src/emcc.rs (hunk 2 above)
Comment (nbdd0121) [reply library/panic_unwind/src/emcc.rs:47]: I think it's worth mentioning that it should be noted that catching a foreign unwind in Rust is UB. We are providing guards against this but it's not part of guarantee.

Currently there are no ways to hit this on stable, and if you hit this using nightly you are already in UB territory. So we *can* change this string (and the exception class), but we *don't have to*.

**Review by Amanieu — APPROVED** [review]

File: library/panic_unwind/src/emcc.rs [hunk 4]
```diff
@@ -90,7 +100,14 @@ pub unsafe fn panic(data: Box<dyn Any + Send>) -> u32 {
     if exception.is_null() {
         return uw::_URC_FATAL_PHASE1_ERROR as u32;
     }
-    ptr::write(exception, Exception { caught: AtomicBool::new(false), data: Some(data) });
+    ptr::write(
```
Comment (joboet) [inline library/panic_unwind/src/emcc.rs:103]: The structure allocated above is too small, so this causes UB. This probably used to work because the allocator added some padding, but 4 bytes are now definitely to little for a structure of 12 bytes. `sz` should be `mem::size_of::<Exception>()`.

**Comment by joboet** [comment]
I hope I am correct in doing this, but this should probably not be merged with the unsoundness above (I think that also caused the rollup to fail).

@bors r-

File: library/panic_unwind/src/emcc.rs (hunk 4 above)
Comment (nbdd0121) [reply library/panic_unwind/src/emcc.rs:102]: Fixed

**Comment by nbdd0121** [comment]
Hmm, I tested the test case on nightly i686-pc-windows-gnu and it doesn't work either. I am not familiar enough with windows-gnu targets to troubleshoot it, unfortunately.

However, given that the problem is not related to the main PR itself, I'll just mark the test as `ignore-windows-gnu`. Is that okay? @Amanieu

**Comment by Amanieu** [comment]
i686-mingw requires unwind tables to be registered with the unwinder when the module is loaded. We do this, but the problem in this case is that the cdylib has its own copy of libgcc statically linked into it. This is somewhat by design so that mingw executables don't have a runtime dependency on libgcc_s.dll, but it breaks cross-DLL unwinding since the respective unwinders are not aware of the unwind tables in other modules.

I think ignoring the test is fine in this case, but only on i686. Other architectures do not have this limitation.

**Comment by nbdd0121** [comment]
> I think ignoring the test is fine in this case, but only on i686. Other architectures do not have this limitation.

Yeah, I tested this on x86_64 MinGW and it works fine. However we only have `ignore-x86` and `ignore-windows-gnu`, but not `ignore-(x86 and windows-gnu)`. Which directive should I use?

**Comment by Amanieu** [comment]
You can pass a full target triple: `// ignore-i686-pc-windows-gnu`
