### PR TITLE
Warn if linking to a private item

### LINKED ISSUE #72769: rustdoc fails to link to private items without warning
I tried this code:

```rust
/// See also [`g()`][crate::g]
pub fn f() {}

fn g() {}
```

I expected to see this happen:
```
warning: `[crate::g]` cannot be resolved, ignoring it.
``` 
or preferably
```
warning: `[crate::g]` is private and therefore cannot be linked, ignoring it.
```

Instead, this happened: The crate documents without warnings, but does not generate links: `See also [g()][crate::g] `

### Meta

```
$ rustdoc +nightly --version
rustdoc 1.45.0-nightly (4bd32c980 2020-05-29)
```

@rustbot modify labels: T-rustdoc A-intra-doc-links

### PR DESCRIPTION
**Pull request by jyn514**
Closes https://github.com/rust-lang/rust/issues/72769

r? @GuillaumeGomez

### CODE REVIEW

**Comment by jyn514** [comment]
Changes that should be made before merging:
- Right now this warns twice for each link? I'm not sure why.

Changes that I think can be made in follow-up PRs:
- Instead of warning, this should properly resolve the link when passed `--document-private-items` (https://github.com/rust-lang/rust/issues/65697)

**Comment by jyn514** [comment]
Output for the example in #72769:
```
warning: `[crate::g]` public documentation for `f` links to a private item
 --> priv-in-pub.rs:1:22
  |
1 | /// See also [`g()`][crate::g] and [`h()`]
  |                      ^^^^^^^^ itemtype is private
  |
  = note: `#[warn(intra_doc_link_resolution_failure)]` on by default

warning: `[crate::g]` public documentation for `f` links to a private item
 --> priv-in-pub.rs:1:22
  |
1 | /// See also [`g()`][crate::g] and [`h()`]
  |                      ^^^^^^^^ itemtype is private

warning: 2 warnings emitted
```

File: src/librustdoc/passes/collect_intra_doc_links.rs [hunk 1]
```diff
@@ -697,6 +703,24 @@ impl<'a, 'tcx> DocFolder for LinkCollector<'a, 'tcx> {
...
+                            cx,
+                            &item,
+                            path_str,
+                            &dox,
+                            link_range,
+                            &format!("public documentation for `{}` links to a private item", item_name),
+                            "this item is private",
+                            None,
+                        );
+                    }
```
Comment (GuillaumeGomez) [inline src/librustdoc/passes/collect_intra_doc_links.rs:722]: I think you forgot to add a `continue` after your call to `build_diagnostic`.

File: src/librustdoc/passes/collect_intra_doc_links.rs [hunk 2]
```diff
@@ -697,6 +703,24 @@ impl<'a, 'tcx> DocFolder for LinkCollector<'a, 'tcx> {
             if let Res::PrimTy(_) = res {
                 item.attrs.links.push((ori_link, None, fragment));
             } else {
+                // ~~WRONG: TODO: I think this happens too late and we need to instead put this in `self.resolve`~~
+                debug!("item {:?} resolved to {:?}", item, res);
+                if let Some(def_id) = res.opt_def_id() {
+                    let (link_vis, _span, _desc) = ::rustc_privacy::def_id_visibility(self.cx.tcx, def_id);
+                    if !matches!(link_vis, rustc_middle::ty::Visibility::Public) {
```
Comment (GuillaumeGomez) [inline src/librustdoc/passes/collect_intra_doc_links.rs:710]: Can't you just use `!=`?

File: src/librustdoc/passes/collect_intra_doc_links.rs (hunk 1 above)
Comment (jyn514) [reply src/librustdoc/passes/collect_intra_doc_links.rs:735]: Added a continue

File: src/librustdoc/passes/collect_intra_doc_links.rs (hunk 2 above)
Comment (jyn514) [reply src/librustdoc/passes/collect_intra_doc_links.rs]: I ended up using a different approach that didn't involve messing around with `rustc_privacy` internals.

**Comment by jyn514** [comment]
My workaround to avoid the bugs from the markdown parser means that we no longer give a warning for each time the same broken link is seen, only the first time. Not sure how to fix this.
```
/// [Foo::bar], [Foo::bar]
pub fn f() {}
```
```
warning: `[Foo::bar]` cannot be resolved, ignoring it.
 --> duplicate-err.rs:1:6
  |
1 | /// [Foo::bar], [Foo::bar]
  |      ^^^^^^^^ cannot be resolved, ignoring
  |
  = note: `#[warn(intra_doc_link_resolution_failure)]` on by default
  = help: to escape `[` and `]` characters, just add '\' before them like `\[` or `\]`

warning: 1 warning emitted
```

**Comment by jyn514** [comment]
After https://github.com/rust-lang/rust/pull/72771/commits/368d0f8cb5dc3585e0dcbac47cc2a8dfa0b254ca this also closes https://github.com/rust-lang/rust/issues/65697.

**Comment by jyn514** [comment]
The way this works is by
- Moving `document_private`/hidden from `Options` to `RenderOptions`
- Adding `RenderOptions` to `DocContext` so it can be used while running passes
- Adding `document_private` to the cache so it can used in free functions (like `href`)
- Checking in `fn href()` if `--document-private-items` was passed, and not silently deleting the link if so
- Checking in `fold_item` if `document-private-items` was passed; if not, it gives an error when linking to private items
- Removing duplicate warnings as mentioned in https://github.com/rust-lang/rust/pull/72771#issuecomment-636360376

**Comment by jyn514** [comment]
Status: this is waiting on https://github.com/raphlinus/pulldown-cmark/pull/445. However, I think that bug was pre-existing (I just happened to notice while working on this PR). @GuillaumeGomez if I fix the test failures does this look good? I can add an ignored test case for the bug I spotted and fix it in a follow-up PR at some point.

**Comment by jyn514** [comment]
I opened https://github.com/rust-lang/rust/issues/73264 for the secondary issue, it's not actually related to this PR.

**Review by Manishearth — APPROVED** [review]
r=me for this, but please clean up the commit history

might also be worth being a little bit more verbose in `debug!()`

Do you intend to wait for the pulldown-cmark PR to land?

File: src/test/rustdoc-ui/intra-links-private.rs [hunk 3]
```diff
@@ -0,0 +1,10 @@
+// check-pass
+// revisions: public private
+// [private]compile-flags: --document-private-items
+#![cfg_attr(private, deny(intra_doc_resolution_failure))]
+
+/// docs [DontDocMe]
```
Comment (GuillaumeGomez) [inline src/test/rustdoc-ui/intra-links-private.rs:6]: It sounds weird to me to have this warning when the flag `--document-private-items` is passed. In my opinion, it shouldn't complain in this case.

**Review by GuillaumeGomez — CHANGES_REQUESTED** [review]

File: src/test/rustdoc-ui/intra-links-private.rs (hunk 3 above)
Comment (Manishearth) [reply src/test/rustdoc-ui/intra-links-private.rs:6]: It isn't warning when the flag is passed, look closer

**Comment by jyn514** [comment]
> please clean up the commit history

Done, good call.

> might also be worth being a little bit more verbose in debug!()

I was worried I was _too_ verbose, what did you want changed? I changed some debugging around in the latest commit.

> Do you intend to wait for the pulldown-cmark PR to land?

No, it's been two weeks and I don't expect it to land any time soon. It was a pre-existing bug anyway.

**Comment by Manishearth** [comment]
> I was worried I was _too_ verbose, what did you want changed? I changed some debugging around in the latest commit.

That's pretty much what i was looking for, basically it should vaguely mention intra doc links, ideally

@bors r+

File: src/test/rustdoc-ui/intra-links-private.rs (hunk 3 above)
Comment (GuillaumeGomez) [reply src/test/rustdoc-ui/intra-links-private.rs:6]: Oh you're right! My bad.

**Comment by dennis-hamester** [comment]
With this MR, the following produces a warning:

```rust
struct Private;

pub struct Public {
    /// A private field with a [`Private`] type.
    private: Private,
}
```

Was this intentional? The field itself is not public, so it should be fine to link to a private type, right?

**Comment by GuillaumeGomez** [comment]
I think warn in this case is valid as well. You link to a private item, so wether or not you're using it on a private item shouldn't matter in my opinion. You can see it as a case of "this item was public but is not private (but mistake or not), and rustdoc is warning about items linked by it and to it".

**Comment by jyn514** [comment]
@GuillaumeGomez I disagree. One of the use cases I was thinking about here was `--document-private-items`. With the current behavior, adding docs that only show up when `--document-private-items` is passed will give a warning _even if_ the docs are never generated or shown to the user. So there's no way to have links among private items without seeing this warning each time.

@dennis-hamester can you open an issue for this behavior?

**Comment by Manishearth** [comment]
One potential fix is to only emit this warning for docs that are going to be emitted in the current run. Linking private types is useful in document-private-items: when that's enabled we shoudl disable this lint, and when that's disabled we should only emit the lint for docs that are going to be rendered

**Comment by dennis-hamester** [comment]
I use this "pattern" a lot in my crates, to provide documentation for private items when building with `--document-private-items`. When building without that flag no link to any of the private types ever gets actually generated, which is why the warning seems wrong to me.

Actually, I also tend to deny `intra_doc_link_resolution_failure` to catch bad links and but now of course I get lot's of errors.

Does that mean linking to a private type is generally discouraged? Is there a better way? I'd like to provide documentation for internals as well, not just for the public api.

**Comment by Manishearth** [comment]
I agree with @jyn514, people use document-private-items and we shouldn't warn then.

**Comment by GuillaumeGomez** [comment]
In case the `--document-private-items` option is used, it makes sense not to warn at this point. But otherwise, it seems normal to warn.

**Comment by GuillaumeGomez** [comment]
Hum, on second thought, it might make no sense to complain if it's a link *from* a private item. But I still that linking *to* a private item should emit a warning (unless the `--document-private-items` option is provided of course).

**Comment by dennis-hamester** [comment]
I opened #74134 and discussion should probably continue there.

**Comment by Manishearth** [comment]
@GuillaumeGomez Yes, we should complain if you link _to_ a private item _from_ a public item, in non-private-document mode. The private-to-private links only make sense with document-private-items anyway, and it's weird to warn about them when that's disabled where they don't matter.

**Comment by GuillaumeGomez** [comment]
@Manishearth Absolutely, took me a few minutes to see it.
