### PR TITLE
Expand suggestions for type ascription parse errors

### LINKED ISSUE #51222: "expecting a type here because of type ascription" when forgetting a :
In the following code, I forgot a semicolon:

```
fn main() {
    Box:new("foo".to_string())
}
```

This generates the following error:

```
  |
2 |     Box:new("foo".to_string())
  |             ^^^^^ expecting a type here because of type ascription
```

This may get confusing when nesting multiple calls in the argument of `Box::new`.

ping @GuillaumeGomez

### PR DESCRIPTION
**Pull request by estebank**
Fix #51222. CC #48016, #47666, #54516, #34255.

### CODE REVIEW

File: src/libsyntax/parse/parser.rs [hunk 1]
```diff
@@ -3548,21 +3548,55 @@ impl<'a> Parser<'a> {
...
                             );
+                        } else {
+                            if maybe_path {
+                                err.span_suggestion(
+                                    cur_op_span,
+                                    "maybe you meant to write a path separator here",
+                                    "::".to_string(),
+                                    Applicability::MaybeIncorrect,
+                                );
+                            } else {
```
Comment (Centril) [inline src/libsyntax/parse/parser.rs]: Break out to function?

**Comment by TimNN** [comment]
Ping from triage @vakor: This PR requires your review.

File: src/test/ui/error-codes/E0423.stderr [hunk 2]
```diff
@@ -3,6 +3,19 @@ error: expected type, found `1`
    |
 LL |     if let S { x: _x, y: 2 } = S { x: 1, y: 2 } { println!("Ok"); }
    |                                       ^ expecting a type here because of type ascription
+   |
+   = note: type ascription is a nightly only feature that lets you annotate expressions with a type: `<expr>: <type>`
+note: this expression is annotated with type ascription...
+  --> $DIR/E0423.rs:12:36
+   |
+LL |     if let S { x: _x, y: 2 } = S { x: 1, y: 2 } { println!("Ok"); }
```
Comment (varkor) [inline src/test/ui/error-codes/E0423.stderr]: The message at the moment is quite long. I wonder if we could collapse it into a single snippet. Also, I think the colon could come first, as it is that which triggers the ascription.
```
note: this expression expects an ascribed type
  --> $DIR/E0423.rs:12:36
   |
LL |     if let S { x: _x, y: 2 } = S { x: 1, y: 2 } { println!("Ok"); }
   |                                     - the colon here...
   |                                    ^ ...implies that this expression is ascribed a type
   = help: this might be indicative of a syntax error elsewhere
```

**Review by varkor — COMMENTED** [review]
I still need to look over these changes in detail (I will do soon, sorry for taking so long). I've left a suggestion about making the diagnostic more concise in the meantime.

File: src/test/ui/error-codes/E0423.stderr (hunk 2 above)
Comment (estebank) [reply src/test/ui/error-codes/E0423.stderr]: @varkor the problem is that we can't add them as span_labels in the main error without it getting too crowded, and secondary diagnostic windows do not let you (at the moment) specify span labels. I thought that although it is unnecessarily verbose, it is better than the alternative. Once we have more flexibility to actually accomplish the output you suggest, I would be happy to implement it.

Comment (estebank) [reply src/test/ui/error-codes/E0423.stderr]: An option would be

```
note: this expression expects an ascribed type after the colon
  --> $DIR/E0423.rs:12:36
   |
LL |     if let S { x: _x, y: 2 } = S { x: 1, y: 2 } { println!("Ok"); }
   |                                    ^
   = help: this might be indicative of a syntax error elsewhere
```

Comment (varkor) [reply src/test/ui/error-codes/E0423.stderr]: @estebank: ahh, I see.

I prefer the suggested option in the interim: I think it captures all the necessary information, without being too verbose.

File: src/libsyntax/parse/parser.rs [hunk 3]
```diff
@@ -3668,6 +3665,62 @@ impl<'a> Parser<'a> {
         Ok(lhs)
     }
 
+    fn could_ascription_be_path(&self, node: &ast::ExprKind) -> bool {
+        self.token.is_ident() &&
+            if let ast::ExprKind::Path(..) = node { true } else { false } &&
+            !self.token.is_reserved_ident() &&           // v `foo:bar(baz)`
```
Comment (varkor) [inline src/libsyntax/parse/parser.rs]: Is this `v` intentional?

Comment (estebank) [reply src/libsyntax/parse/parser.rs]: It's meant to be an arrow pointing down 😬

Comment (varkor) [reply src/libsyntax/parse/parser.rs]: Oh, I see 😄I would be tempted just to put it on its own line, but this is fine too.

File: src/test/ui/error-codes/E0423.stderr (hunk 2 above)
Comment (estebank) [reply src/test/ui/error-codes/E0423.stderr]: Changed.

**Comment by estebank** [comment]
Ping
