### PR TITLE
suggestion for unit enum variant when matched with a patern

### LINKED ISSUE #84700: Diagnostics: Suggest Unit Variant Enum in match
https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=5a6b1a3497842e4ddc883b2345febd8f

```rust
#[derive(PartialEq, Debug)]
enum FarmAnimal {
    Worm,
    Cow,
    Bull,
    Chicken { num_eggs: usize },
    Dog { name: String },
}

fn what_does_the_animal_say(animal: &FarmAnimal) {

    /* TODO: fill in the match statement below to make this code compile */
    
    let noise = match animal {
        FarmAnimal::Cow(_) => "moo".to_string(),
        // /* Chicken      */ => "cluck, cluck!".to_string(),
        // /* Dog          */  => format!("woof, woof! I am {}!", name),
        // /* Worm– or all silent animals?*/ => "-- (silence)".to_string(),
        _ => todo!()
    };
    
    /* Bonus task: Give Dogs named Lassie a different output */
    
    println!("{:?} says: {:?}", animal, noise);
}

fn main() {
    what_does_the_animal_say(
        &FarmAnimal::Dog {
            name: "Lassie".to_string()
    });
    what_does_the_animal_say(&FarmAnimal::Cow);
    what_does_the_animal_say(&FarmAnimal::Bull);
    what_does_the_animal_say(&FarmAnimal::Chicken{num_eggs: 3});
    what_does_the_animal_say(&FarmAnimal::Worm);

    /*
    Output should be:
    
    Dog { name: "Lassie" } says: "woof, woof! I am Lassie!"
    Cow says: "moo"
    Bull says: "moo"
    Chicken { num_eggs: 3 } says: "cluck, cluck!"
    Worm says: "-- (silence)"
    
    */
}
```

The current output is:

```
error[E0532]: expected tuple struct or tuple variant, found unit variant `FarmAnimal::Cow`
  --> src/main.rs:15:9
   |
15 |         FarmAnimal::Cow(_) => "moo".to_string(),
   |         ^^^^^^^^^^^^^^^ not a tuple struct or tuple variant

error: aborting due to previous error

For more information about this error, try `rustc --explain E0532`.
error: could not compile `playground`

To learn more, run the command again with --verbose.
```

Ideally the output should look like:

I'd like it to say "try to use a ~~tuple~~ unit variant like "FarmAnimal::Cow" instead".

For example, here's what happens if you use Tuple syntax instead of Struct syntax:

```
error[E0532]: expected tuple struct or tuple variant, found struct variant `FarmAnimal::Chicken`
  --> src/main.rs:16:9
   |
6  |     Chicken { num_eggs: usize },
   |     --------------------------- `FarmAnimal::Chicken` defined here
...
16 |         FarmAnimal::Chicken(x)  => "cluck, cluck!".to_string(),
   |         ^^^^^^^^^^^^^^^^^^^^^^ help: use struct pattern syntax instead: `FarmAnimal::Chicken { num_eggs }`

error: aborting due to 2 previous errors
```

So I'd like the new diagnostic to look something like:

```
error[Exxxx]: expected tuple struct or tuple variant, found unit variant `FarmAnimal::Cow`
  --> src/main.rs:16:9
   |
6  |     Cow,
   |     --- `FarmAnimal::Cow` defined here
...
16 |         FarmAnimal::Cow(_)  => "moo".to_string(),
   |         ^^^^^^^^^^^^^^^^^^ help: use unit pattern syntax instead: `FarmAnimal::Cow`
```

### PR DESCRIPTION
**Pull request by ABouttefeux**
resolve #84700

add suggestion for code like
```rust
enum FarmAnimal {
    Worm,
    Cow,
    Bull,
    Chicken { num_eggs: usize },
    Dog (String),
}

fn what_does_the_animal_say(animal: &FarmAnimal) {

    let noise = match animal {
        FarmAnimal::Cow(_) => "moo".to_string(),
        _ => todo!()
    };

    println!("{:?} says: {:?}", animal, noise);
}
```

```
error[E0532]: expected tuple struct or tuple variant, found unit variant `FarmAnimal::Cow`
  --> $DIR/issue-84700.rs:15:9
   |
LL |     Cow,
   |     --- `FarmAnimal::Cow` defined here
...
LL |         FarmAnimal::Cow(_) => "moo".to_string(),
   |         ^^^^^^^^^^^^^^^^^^ help: use this syntax instead: `FarmAnimal::Cow`
   ```

### CODE REVIEW

**Comment by jackh726** [comment]
LGTM. Thanks!

@bors r+ rollup

File: compiler/rustc_resolve/src/late/diagnostics.rs [hunk 1]
```diff
@@ -1047,6 +1049,23 @@ impl<'a: 'ast, 'ast> LateResolutionVisitor<'a, '_, 'ast> {
...
+                    PathSource::Expr(_) | PathSource::TupleStruct(..) | PathSource::Pat => {
+                        let span = find_span(&source, err);
+                        if let Some(span) = self.def_span(def_id) {
+                            err.span_label(span, &format!("`{}` defined here", path_str));
+                        }
+                        err.span_suggestion(
+                            span,
+                            &format!("use this syntax instead"),
+                            format!("{path_str}"),
+                            Applicability::MaybeIncorrect,
```
Comment (pickfire) [inline compiler/rustc_resolve/src/late/diagnostics.rs:1063]: Shouldn't this be machine applicable? In what cases it will be incorrect?

Comment (jackh726) [reply compiler/rustc_resolve/src/late/diagnostics.rs:1063]: I mean, there are two different suggestions that get emitted, so there *could* be some ambiguity. (I guess the "help: a tuple struct with a similar name exists" suggestion *might* just never be what the user wants, but that decision would have to be made in another PR)
