### PR TITLE
const_eval: allow function pointer signatures containing &mut T in const contexts

### LINKED ISSUE #114994: Function pointer signature containing `&mut T` should work in const context
Proposing to extract this from #57349.

The following examples shouldn't error:
```rust
const fn get_some_fn() -> fn(&mut String) {
  String::clear
}

const fn use_const_fn(_f: fn(&mut String)) {
  ()
}

const fn some_const_fn() {
  let _f: fn(&mut String) = String::clear;
}

// mutable references are not allowed in constant functions      x3
```

While this has been considered part of #57349 for a while, it's also been acknowledged as a bug and suggested by @RalfJung to address separately ahead of stabilizing `const_mut_refs`. Indeed it's surprising for users that this would count as handling a mutable reference in const contexts.

See:
https://github.com/rust-lang/rust/issues/57349#issuecomment-1266769993
https://github.com/rust-lang/rust/issues/57349#issuecomment-1684898459

### PR DESCRIPTION
**Pull request by EvanMerlock**
potentially fixes #114994

We utilize a `TypeVisitor` here in order to more easily handle control flow.
- In the event the typekind the Visitor sees is a function pointer, we skip over it
- However, otherwise we do one of two things:
   - If we find a mutable reference, check it, then continue visiting types
   - If we find any other type, continue visiting types

This means we will check if the function pointer _itself_ is mutable, but not if any of the types _within_ are.

### CODE REVIEW

**Comment by cjgillot** [comment]
cc @oli-obk as it touches const-fn checks.

File: compiler/rustc_const_eval/src/transform/check_consts/check.rs [hunk 1]
```diff
@@ -356,6 +356,7 @@ impl<'mir, 'tcx> Checker<'mir, 'tcx> {
             };
 
             match *ty.kind() {
+                ty::FnPtr(_) => break,
```
Comment (oli-obk) [inline compiler/rustc_const_eval/src/transform/check_consts/check.rs:359]: This will cause `(fn(), &mut u32)` types to not error (please add a test for it). You will need to rewrite the entire `for` loop and use a `TypeVisitor` instead. If you'd like more instructions than this hint, let me know, I'll write something up

Comment (EvanMerlock) [reply compiler/rustc_const_eval/src/transform/check_consts/check.rs]: Thanks, I completely missed that. 

Added test and updated to use `TypeVisitor`. My implementation follows how other implementations I found in `rustc` work.
Please let me know if anything else needs to change.

Comment (oli-obk) [reply compiler/rustc_const_eval/src/transform/check_consts/check.rs]: Looks great to me now!

**Comment by oli-obk** [comment]
Nominating for T-lang FCP as this enables more code to compile. Specifically this allows mutable references in `const fn`, as long as they are part of a function pointer. We already support function pointers on stable (but not calling them), and we forbid all mutable references. This check was overzealous and also forbade function pointers that had mutable references as arguments, even though there is no risk associated with that at all, as function pointers can't be used at compile-time anyway (except to pass them around).

**Comment by nikomatsakis** [comment]
@oli-obk I'm fine with this PR, but it'd be nice to have examples of other places where `&mut` *is* disallowed (and why) so that we can see that those cases don't apply here.

**Comment by nikomatsakis** [comment]
@rfcbot reviewed

**Comment by compiler-errors** [comment]
@nikomatsakis: See https://github.com/rust-lang/rust/issues/57349 for the remaining blockers for `&mut` in const, there seems to be some outstanding issue with statics (de)duplication.

**Comment by RalfJung** [comment]
Cc @rust-lang/wg-const-eval
