### PR TITLE
Fix AnonConst ICE

### LINKED ISSUE #91267: ICE: compiler/rustc_typeck/src/collect/type_of.rs:186:25: no arg matching AnonConst in path
I'm seeing an internal compiler error on the following input, found by [fuzz-rustc](https://github.com/dwrensha/fuzz-rustc):

### Code

```Rust
fn main() {
    0: u8<e<5>=e>
}
```

### Error output

```
error[E0412]: cannot find type `e` in this scope
 --> src/main.rs:2:16
  |
2 |     0: u8<e<5>=e>
  |                ^
  |                |
  |                not found in this scope
  |                help: maybe you meant to write an assignment here: `let e`

error: internal compiler error: compiler/rustc_typeck/src/collect/type_of.rs:186:25: no arg matching AnonConst in path

thread 'rustc' panicked at 'Box<dyn Any>', compiler/rustc_errors/src/lib.rs:1169:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

The ICE happens after correctly reporting another error, so low priority. Affected versions: I tried nightly 2021-11-25 and stable 1.56.1 and they both show the same ICE.

<details><summary><strong>Backtrace</strong></summary>
<p>

```
   Compiling playground v0.0.1 (/playground)
error[E0412]: cannot find type `e` in this scope
 --> src/main.rs:2:16
  |
2 |     0: u8<e<5>=e>
  |                ^
  |                |
  |                not found in this scope
  |                help: maybe you meant to write an assignment here: `let e`

error: internal compiler error: compiler/rustc_typeck/src/collect/type_of.rs:186:25: no arg matching AnonConst in path

thread 'rustc' panicked at 'Box<dyn Any>', compiler/rustc_errors/src/lib.rs:1169:9
stack backtrace:
   0: std::panicking::begin_panic::<rustc_errors::ExplicitBug>
   1: std::panic::panic_any::<rustc_errors::ExplicitBug>
   2: <rustc_errors::HandlerInner>::bug
   3: <rustc_errors::Handler>::bug
   4: rustc_middle::ty::context::tls::with_opt::<rustc_middle::util::bug::opt_span_bug_fmt<rustc_span::span_encoding::Span>::{closure#0}, ()>
   5: rustc_middle::util::bug::opt_span_bug_fmt::<rustc_span::span_encoding::Span>
   6: rustc_middle::util::bug::bug_fmt
   7: rustc_typeck::collect::type_of::opt_const_param_of
   8: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::plumbing::QueryCtxt, rustc_query_system::query::caches::DefaultCache<rustc_span::def_id::LocalDefId, core::option::Option<rustc_span::def_id::DefId>>>
   9: <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::opt_const_param_of
  10: rustc_typeck::check::typeck
  11: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::plumbing::QueryCtxt, rustc_query_system::query::caches::DefaultCache<rustc_span::def_id::LocalDefId, &rustc_middle::ty::context::TypeckResults>>
  12: <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::typeck
  13: <rustc_middle::hir::map::Map>::par_body_owners::<rustc_typeck::check::typeck_item_bodies::{closure#0}>
  14: rustc_typeck::check::typeck_item_bodies
  15: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::plumbing::QueryCtxt, rustc_query_system::query::caches::DefaultCache<(), ()>>
  16: rustc_query_system::query::plumbing::get_query::<rustc_query_impl::queries::typeck_item_bodies, rustc_query_impl::plumbing::QueryCtxt>
  17: <rustc_session::session::Session>::time::<(), rustc_typeck::check_crate::{closure#7}>
  18: rustc_typeck::check_crate
  19: rustc_interface::passes::analysis
  20: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::plumbing::QueryCtxt, rustc_query_system::query::caches::DefaultCache<(), core::result::Result<(), rustc_errors::ErrorReported>>>
  21: rustc_query_system::query::plumbing::get_query::<rustc_query_impl::queries::analysis, rustc_query_impl::plumbing::QueryCtxt>
  22: <rustc_interface::passes::QueryContext>::enter::<rustc_driver::run_compiler::{closure#1}::{closure#2}::{closure#3}, core::result::Result<(), rustc_errors::ErrorReported>>
  23: <rustc_interface::interface::Compiler>::enter::<rustc_driver::run_compiler::{closure#1}::{closure#2}, core::result::Result<core::option::Option<rustc_interface::queries::Linker>, rustc_errors::ErrorReported>>
  24: rustc_span::with_source_map::<core::result::Result<(), rustc_errors::ErrorReported>, rustc_interface::interface::create_compiler_and_run<core::result::Result<(), rustc_errors::ErrorReported>, rustc_driver::run_compiler::{closure#1}>::{closure#1}>
  25: rustc_interface::interface::create_compiler_and_run::<core::result::Result<(), rustc_errors::ErrorReported>, rustc_driver::run_compiler::{closure#1}>
  26: <scoped_tls::ScopedKey<rustc_span::SessionGlobals>>::set::<rustc_interface::util::setup_callbacks_and_run_in_thread_pool_with_globals<rustc_interface::interface::run_compiler<core::result::Result<(), rustc_errors::ErrorReported>, rustc_driver::run_compiler::{closure#1}>::{closure#0}, core::result::Result<(), rustc_errors::ErrorReported>>::{closure#0}::{closure#0}, core::result::Result<(), rustc_errors::ErrorReported>>
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.58.0-nightly (dd549dcab 2021-11-25) running on x86_64-unknown-linux-gnu

note: compiler flags: -C embed-bitcode=no -C codegen-units=1 -C debuginfo=2 --crate-type bin

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [opt_const_param_of] computing the optional const parameter of `main::{constant#0}`
#1 [typeck] type-checking `main::{constant#0}`
#2 [typeck_item_bodies] type-checking all item bodies
#3 [analysis] running analysis passes on this crate
end of query stack
For more information about this error, try `rustc --explain E0412`.
error: could not compile `playground` due to previous error
```

</p>
</details>

### PR DESCRIPTION
**Pull request by terrarier2111**
I am not sure if this is even the correct place to fix this issue, but i went down the path where the generic args came from and i wasn't able to find a clear cause for this down there. But if anybody has a suggestion what i should do, just tell me.
This fixes: https://github.com/rust-lang/rust/issues/91267

### CODE REVIEW

File: compiler/rustc_typeck/src/collect/type_of.rs [hunk 1]
```diff
@@ -134,7 +134,15 @@ pub(super) fn opt_const_param_of(tcx: TyCtxt<'_>, def_id: LocalDefId) -> Option<
             | Node::Pat(_) => {
                 let path = match parent_node {
                     Node::Ty(&Ty { kind: TyKind::Path(QPath::Resolved(_, path)), .. })
-                    | Node::TraitRef(&TraitRef { path, .. }) => &*path,
+                    | Node::TraitRef(&TraitRef { path, .. }) => {
+                        // Check for empty generic args, because if there are no generic args, this would otherwise ICE
+                        if path.segments.len() == 1
```
Comment (terrarier2111) [inline compiler/rustc_typeck/src/collect/type_of.rs:139]: Not sure if ```== 1``` is correct here or if checking for ```< 2``` would be better.

File: compiler/rustc_typeck/src/collect/type_of.rs [hunk 2]
```diff
@@ -134,7 +134,15 @@ pub(super) fn opt_const_param_of(tcx: TyCtxt<'_>, def_id: LocalDefId) -> Option<
...
+                            && path.segments[0].args.map_or(-1, |x| x.args.len() as isize) == 0
```
Comment (terrarier2111) [inline compiler/rustc_typeck/src/collect/type_of.rs:140]: Not sure if ```None``` should be handled the same as ```len == 0```.

**Comment by terrarier2111** [comment]
Also I am not sure if this is the correct way or if I should replace the ```bug!``` in line 194 with ```return None;```

File: compiler/rustc_typeck/src/collect/type_of.rs (hunk 1 above)
Comment (b-naber) [reply compiler/rustc_typeck/src/collect/type_of.rs:139]: Checking for the length of the segment does prevent the `unwrap` triggered ICE in this test case, but this doesn't seem like the best way to prevent similar ICEs. I think something like `0: u8<e::f<5>=e::f>` should also trigger an ICE after your fixes. 

Obviously this fuzzer generated example is really contrived, but to prevent this type of ICE, the most reasonable change to me seems to be to shift the code [here](https://github.com/rust-lang/rust/blob/27d5935df18d7035c9bd8dc5c1dfbbad6ac59793/compiler/rustc_typeck/src/collect/type_of.rs#L175-L187), which tries to find the `arg_index` and `segment` from the path, to this pattern arm and not call `unwrap` on the result, but just return None if this fails to find any `arg_index`. Maybe try to minimize code duplication here. 

I'm not sure about the other pattern arms, maybe calling `unwrap` on the resulting path for those branches could also ICE and maybe we should never call `unwrap` in the first place.

Comment (terrarier2111) [reply compiler/rustc_typeck/src/collect/type_of.rs:139]: First of all thanks for the feedback, i'll look into applying the changes you suggested.
(btw ```0: u8<e::f<5>=e::f>``` doesn't panic at all neither on stable nor with my changed)

Comment (b-naber) [reply compiler/rustc_typeck/src/collect/type_of.rs:139]: What about `0: u8<e<5>=e::f>`?

Comment (terrarier2111) [reply compiler/rustc_typeck/src/collect/type_of.rs:139]: Stable panics, with my changes it doesn't.

Comment (terrarier2111) [reply compiler/rustc_typeck/src/collect/type_of.rs:139]: > 



> 

You mentioned "this pattern arm" do you mean the pattern arm at line 137 with that?

Comment (b-naber) [reply compiler/rustc_typeck/src/collect/type_of.rs:139]: Yes. 

Maybe I'm misunderstanding something here. What is `parent_node` when you run this with `0: u8<e::f<5>=e::f>`?

Comment (terrarier2111) [reply compiler/rustc_typeck/src/collect/type_of.rs:139]: This is parent_node: ```parent: Ty(Ty { hir_id: HirId { owner: DefId(0:3 ~ anon_const[dfde]::main), local_id: 2 }, kind: Path(Resolved(None, Path { span: anon_const.rs:2:8: 2:21 (#0), res: PrimTy(Uint(U8)), segments: [PathSegment { ident: u8#0, hir_id: Some(HirId { owner: DefId(0:3 ~ anon_const[dfde]::main), local_id: 9 }), res: Some(Err), args: Some(GenericArgs { args: [], bindings: [TypeBinding { hir_id: HirId { owner: DefId(0:3 ~ anon_const[dfde]::main), local_id: 8 }, ident: e#0, gen_args: GenericArgs { args: [Const(ConstArg { value: AnonConst { hir_id: HirId { owner: DefId(0:3 ~ anon_const[dfde]::main), local_id: 3 }, body: BodyId { hir_id: HirId { owner: DefId(0:3 ~ anon_const[dfde]::main), local_id: 4 } } }, span: anon_const.rs:2:13: 2:14 (#0) })], bindings: [], parenthesized: false, span_ext: anon_const.rs:2:12: 2:15 (#0) }, kind: Equality { ty: Ty { hir_id: HirId { owner: DefId(0:3 ~ anon_const[dfde]::main), local_id: 5 }, kind: Path(Resolved(None, Path { span: anon_const.rs:2:16: 2:20 (#0), res: Err, segments: [PathSegment { ident: e#0, hir_id: Some(HirId { owner: DefId(0:3 ~ anon_const[dfde]::main), local_id: 6 }), res: Some(Err), args: None, infer_args: false }, PathSegment { ident: f#0, hir_id: Some(HirId { owner: DefId(0:3 ~ anon_const[dfde]::main), local_id: 7 }), res: Some(Err), args: None, infer_args: false }] })), span: anon_const.rs:2:16: 2:20 (#0) } }, span: anon_const.rs:2:11: 2:20 (#0) }], parenthesized: false, span_ext: anon_const.rs:2:10: 2:21 (#0) }), infer_args: false }] })), span: anon_const.rs:2:8: 2:21 (#0) })```

Comment (terrarier2111) [reply compiler/rustc_typeck/src/collect/type_of.rs:139]: > 

But wouldn't moving that code block to said pattern lead to code duplication and to computing the result of that code block twice? Is there a reason why I can't just let the code block be where it is and replace the ```bug!``` with a ```return None``` and if necessary add a boolean which indicates from which pattern arm the ```path``` came from?

Comment (b-naber) [reply compiler/rustc_typeck/src/collect/type_of.rs:139]: > Is there a reason why I can't just let the code block be where it is and replace the bug! with a return None

I would assume that there is a reason for that. Returning None instead of unwrap would certainly be the cleanest solution, but I'm not sure in what contexts `opt_const_param_of` is called and how this call is handled in case we cannot find the generic parameter corresponding to this path and return None. It might be that we don't handle some error correctly if we just return None whenever we cannot find a generic param. Can you look into that?

Comment (terrarier2111) [reply compiler/rustc_typeck/src/collect/type_of.rs:139]: "I would assume that there is a reason for that" I don't really understand what you mean by that, but sure, i'll look into the context thingy.

Comment (b-naber) [reply compiler/rustc_typeck/src/collect/type_of.rs:139]: I just mean that without knowing more about this code that it makes more sense to assume that the person who inserted that `unwrap` probably had a good reason for including it.

Comment (terrarier2111) [reply compiler/rustc_typeck/src/collect/type_of.rs:139]: So, i looked into it and i didn't find any case in which it could cause problems
Disclaimer: I am relatively new to rustc development, so maybe i missed something.

Comment (terrarier2111) [reply compiler/rustc_typeck/src/collect/type_of.rs:139]: @jackh726 what are your thoughts on this?

Comment (jackh726) [reply compiler/rustc_typeck/src/collect/type_of.rs:139]: Right, so I guess in this case `u8<e<5>=e>` is treated as type ascription for the `0`?

I think the right thing here is to change the `unwrap_or_else(|| bug!())` [here](https://github.com/rust-lang/rust/blob/27d5935df18d7035c9bd8dc5c1dfbbad6ac59793/compiler/rustc_typeck/src/collect/type_of.rs#L186) to a `delay_span_bug` ("no arg matching AnonConst in path") and a `return None`.

**Review by jackh726 — CHANGES_REQUESTED** [review]

File: compiler/rustc_typeck/src/collect/type_of.rs (hunk 1 above)
Comment (terrarier2111) [reply compiler/rustc_typeck/src/collect/type_of.rs]: > 

Right, so i applied your suggestions, I had to add another variable cuz i can't return the ```None``` value in the ```unwrap_or_else```, also the test output didn't change

File: compiler/rustc_typeck/src/collect/type_of.rs [hunk 3]
```diff
@@ -189,10 +181,13 @@ pub(super) fn opt_const_param_of(tcx: TyCtxt<'_>, def_id: LocalDefId) -> Option<
...
-                    })
-                    .unwrap_or_else(|| {
-                        bug!("no arg matching AnonConst in path");
                     });
+                if filtered.is_none() {
+                    tcx.sess
+                        .delay_span_bug(tcx.def_span(def_id), "no arg matching AnonConst in path");
+                    return None;
+                }
+                let (arg_index, segment) = filtered.unwrap();
```
Comment (jackh726) [inline compiler/rustc_typeck/src/collect/type_of.rs:190]: Can you use a match with the above condition too?

**Review by jackh726 — CHANGES_REQUESTED** [review]

**Comment by jackh726** [comment]
When you fix formatting, can you also squash commits?

**Comment by terrarier2111** [comment]
> When you fix formatting, can you also squash commits?

Done
