### PR TITLE
test: Add test for async-move in 2015 Rust proc macro

### LINKED ISSUE #89699: Compiling a Rocket application on the 2015 edition doesn't emit errors
When trying to compile any Rocket application in the 2015 edition the compiler says an error occured without showing any actual error:

```
$ RUST_BACKTRACE=1 cargo build
   Compiling repro v0.1.0
error: could not compile `repro`
$
```

Switching to the 2018 edition fixes the problem, by either showing errors or properly compiling the application. Minimal reproduction:

```rust
// src/main.rs

#[rocket::launch]
fn foo() -> _ {
    rocket::build()
}
```

```toml
# Cargo.toml

[package]
name = "repro"
version = "0.1.0"
edition = "2015"

[dependencies]
rocket = "0.5.0-rc.1"
```

### Meta

`rustc --version --verbose`:
```
rustc 1.55.0 (c8dfcfe04 2021-09-06)
binary: rustc
commit-hash: c8dfcfe046a7680554bf4eb612bad840e7631c4b
commit-date: 2021-09-06
host: x86_64-unknown-linux-gnu
release: 1.55.0
LLVM version: 12.0.1
```

### PR DESCRIPTION
**Pull request by CohenArthur**
Fixes #89699

Ran cargo bisect-rustc to find when this was fixed exactly, which is in 474709a9a2a74a8bcf0055fadb335d0ca0d2d939

### CODE REVIEW

File: tests/ui/proc-macro/auxiliary/async-move.rs [hunk 1]
```diff
@@ -0,0 +1,36 @@
...
+    ]);
+
+    let mut ret = TokenStream::new();
+    ret.extend([
+        TokenTree::Ident(Ident::new("fn", sp)),
+        TokenTree::Ident(Ident::new("main", sp)),
+        TokenTree::Group(Group::new(Delimiter::Parenthesis, TokenStream::new())),
+        TokenTree::Group(Group::new(Delimiter::Brace, body)),
+    ]);
+    eprintln!("{:?}", ret);
```
Comment (lqd) [inline tests/ui/proc-macro/auxiliary/async-move.rs:34]: Is this output needed for the test?

Comment (CohenArthur) [reply tests/ui/proc-macro/auxiliary/async-move.rs:34]: no, it was in the original repro so I kept it - I don't mind removing it if you think it is better

**Comment by lqd** [comment]
Actually I'll take this from you @wesleywiser, the bot is also assigning you a million PRs to review.

r? lqd

File: tests/ui/proc-macro/issue-89699.rs [hunk 2]
```diff
@@ -0,0 +1,6 @@
+// aux-build:async-move.rs
```
Comment (lqd) [inline tests/ui/proc-macro/issue-89699.rs:1]: And here as well, let's add a comment like "Non-regression test for issue 89699 where a proc-macro emitting edition 2018 syntax is used on edition 2015"

Even if it's the default, it's kind of the point of the test so maybe we could also make the `// edition: 2015` explicit (though I'm not sure if the annotation works with the default value). I'll let you ponder this question, I'm fine either way.

**Review by lqd — COMMENTED** [review]
Are a couple things of note:
- Naming: according to https://github.com/rust-lang/compiler-team/issues/658 the test name should be more representative. Something like "edition gated syntax issue 89699" will work fine, and let's make sure both the test and proc-macro share most of that same name.
- Let's add a couple comments to both the test and the proc macro aux.
- And remove the println of course

**Comment by CohenArthur** [comment]
Fixed review comments in [c639090](https://github.com/rust-lang/rust/pull/117973/commits/c6390906f592deb857816b8b8b7fa1e074b037dd)

**Comment by CohenArthur** [comment]
rebased and tidied up

**Comment by lqd** [comment]
@CohenArthur please rebless and squash the 2 commits and we're good to go.

**Comment by CohenArthur** [comment]
thanks @lqd :heart:

**Comment by lqd** [comment]
on va y arriver :3

**Comment by lqd** [comment]
Thanks!

@bors r+ rollup
