### PR TITLE
Check that main/start is not async

### LINKED ISSUE #68523: Bad error message with async main
If someone tries to do the following `async fn main() -> Result<(), Box<dyn std::error::Error>` the error message is not helpful (though it is technically correct).

```rust
error[E0277]: `main` has invalid return type `impl futures::Future`
  --> rs/agent-updater/src/main.rs:46:20
   |
46 | async fn main() -> Result<(), Box<dyn std::error::Error>> {
   |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ `main` can only return types that implement `std::process::Termination`
   |
   = help: consider using `()`, or a `Result`
```

I think that it should point to the `async` keyword and say that standard rust does not support `async` main.

This issue has been assigned to @Nokel81 via [this comment](https://github.com/rust-lang/rust/issues/68523#issuecomment-580037030).

### PR DESCRIPTION
**Pull request by Nokel81**
* Add new error code E0752
* Add span to hir::IsAsync::Yes
* Emit an error if main or the start function is marked as async
* Add two regression tests

This PR fixes #68523.

### CODE REVIEW

File: src/test/compile-fail/issue-68523.rs [hunk 1]
```diff
@@ -0,0 +1,6 @@
+// compile-flags: --edition 2018
+// error-pattern: `main` function is not allowed to be `async`
+
+async fn main() -> Result<i32, ()> {
+    Ok(1)
+}
```
Comment (petrochenkov) [inline src/test/compile-fail/issue-68523.rs:6]: Could you move the tests to `src\test\ui\async-await` and use `//~ ERROR ...` annotations instead of `// error-pattern: ...`?

File: src/librustc_metadata/rmeta/decoder.rs [hunk 2]
```diff
@@ -1366,25 +1368,25 @@ impl<'a, 'tcx> CrateMetadataRef<'a> {
...
-            EntryKind::ForeignFn(data) => data.decode(self).constness,
+            EntryKind::ForeignFn(data) => data.decode((self, sess)).constness,
             EntryKind::Variant(..) | EntryKind::Struct(..) => hir::Constness::Const,
             _ => hir::Constness::NotConst,
         };
         constness == hir::Constness::Const
     }
 
-    fn asyncness(&self, id: DefIndex) -> hir::IsAsync {
+    fn asyncness(&self, id: DefIndex, sess: &Session) -> hir::IsAsync {
```
Comment (petrochenkov) [inline src/librustc_metadata/rmeta/decoder.rs:1385]: This is a cost that affects all functions, but benefits only a specific diagnostic in an erroneous case.

Comment (petrochenkov) [reply src/librustc_metadata/rmeta/decoder.rs:1385]: The errors could use `guess_head_span` from the `fn main`'s item span instead.

File: src/test/compile-fail/issue-68523.rs (hunk 1 above)
Comment (Nokel81) [reply src/test/compile-fail/issue-68523.rs:6]: Sure sounds good

File: src/librustc_metadata/rmeta/decoder.rs (hunk 2 above)
Comment (Nokel81) [reply src/librustc_metadata/rmeta/decoder.rs:1385]: So I think you are suggesting not adding `span` to `hir::IsAsync` but instead using `guess_head_span` in the check in `lib_typchk/lib.rs`?

Comment (Nokel81) [reply src/librustc_metadata/rmeta/decoder.rs:1385]: That has the effect that this error will point to the whole line, not just the word `async`. Do we really want this?

Comment (petrochenkov) [reply src/librustc_metadata/rmeta/decoder.rs:1390]: Yes, pointing to `async fn main` is almost as good as pointing to `async` and doesn't have the metadata encoding/decoding cost in the common case.

**Comment by Nokel81** [comment]
Done @petrochenkov

**Comment by petrochenkov** [comment]
r=me after squashing the commits.

**Comment by Nokel81** [comment]
r=petrochenkov
