### PR TITLE
Fix exceeding bitshifts not emitting for assoc. consts (properly this time, I swear!)

### LINKED ISSUE #69021: "exceeding_bitshifts" lint does not work in associated consts
The `exceeding_bitshifts` lint should fire on the following code, but it does not:
```rust
pub trait Foo {
    const N: i32;
}

impl<T: Foo> Foo for Vec<T> {
    const N: i32 = T::N << 42; // no warning here
}
```
[Playground](https://play.rust-lang.org/?version=nightly&mode=release&edition=2018&gist=11c45c0bd4b22ff997e69901b3bb0709)
(This testcase now exists in-tree as a FIXME in `ui/lint/lint-exceeding-bitshifts.rs`.)

Cc @oli-obk @wesleywiser 

This issue has been assigned to @jumbatm via [this comment](https://github.com/rust-lang/rust/issues/69021#issuecomment-584603723).

### LINKED ISSUE #71353: Type validation mistreats layout errors
The original problem got fixed by avoiding the broken code paths; this issue now tracks [fixing those code paths](https://github.com/rust-lang/rust/issues/71353#issuecomment-617901923).

### Original issue

In [the `ffi_helpers` crate](https://github.com/Michael-F-Bryan/ffi_helpers) we have a [`Nullable`](https://docs.rs/ffi_helpers/0.2.0/ffi_helpers/trait.Nullable.html) trait which gives you a generic way to do null pointer checks.

```rust
pub trait Nullable {
    const NULL: Self;

    fn is_null(&self) -> bool;
}
```

A user recently reported that the crate no longer compiles on `nightly` (https://github.com/Michael-F-Bryan/ffi_helpers/issues/2) because type validation detects that `std::ptr::null()` and `std::ptr::null_mut()` create uninitialized raw pointers.

```
  Compiling playground v0.0.1 (/playground)
error[E0080]: it is undefined behavior to use this value
  --> src/lib.rs:17:5
   |
17 |     const NULL: Self = std::ptr::null_mut();
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ type validation failed: encountered uninitialized raw pointer
   |
   = note: The rules on what exactly is undefined behavior aren't clear, so this check might be overzealous. Please open an issue on the rustc repository if you believe it should not be considered undefined behavior.

error: aborting due to previous error

For more information about this error, try `rustc --explain E0080`.
error: could not compile `playground`.
```

I can reproduce this [on the playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=6d119e3b2cdbaa82880a469401d73800) with the latest nightly, `1.44.0-nightly (2020-04-19 dbf8b6bf116c7bece298)`.

Is the use shown in that playground example (`*self == Self::NULL` on a `*mut T`) actually UB?

Also, I noticed that calling the `is_null()` method defined on a raw pointer with `<*const T>::is_null(*self)` *doesn't* trigger this error, implying that the problem isn't with declaring a constant that contains a null pointer (`const NULL: Self = std::ptr::null_mut()`), but the fact that we're using it for a comparison. Was this intended, or is it just an oversight in the error detection code?

<details>
<summary>Full example with output</summary>

```rust
pub trait Nullable {
    const NULL: Self;

    fn is_null(&self) -> bool;
}

impl<T> Nullable for *const T {
    const NULL: Self = std::ptr::null();

    #[inline]
    fn is_null(&self) -> bool {
        <*const T>::is_null(*self)
    }
}

impl<T> Nullable for *mut T {
    const NULL: Self = std::ptr::null_mut();

    #[inline]
    fn is_null(&self) -> bool {
        *self == Self::NULL
    }
}
```

```
Compiling playground v0.0.1 (/playground)
error[E0080]: it is undefined behavior to use this value
  --> src/lib.rs:17:5
   |
17 |     const NULL: Self = std::ptr::null_mut();
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ type validation failed: encountered uninitialized raw pointer
   |
   = note: The rules on what exactly is undefined behavior aren't clear, so this check might be overzealous. Please open an issue on the rustc repository if you believe it should not be considered undefined behavior.

error: aborting due to previous error

For more information about this error, try `rustc --explain E0080`.
error: could not compile `playground`.

To learn more, run the command again with --verbose.
```
</details>

CC: @RalfJung because it looks like they were the last person to touch that error message (9ee4d1aadc7f4151193a7f53d1fcbb4fddf40ece).

This issue has been assigned to @jumbatm via [this comment](https://github.com/rust-lang/rust/issues/71353#issuecomment-617128281).

### PR DESCRIPTION
**Pull request by jumbatm**
Fixes #69021 and fixes #71353.

As described in https://github.com/rust-lang/rust/issues/71353#issuecomment-617901923, this PR:

- adds a variant of `try_validation!` called `try_validation_pat!` that allows specific failures to be turned into validation failures (but returns the rest, unchanged), and
- allows `InvalidProgram` to be returned out of validation

r? @RalfJung

### CODE REVIEW

**Comment by RalfJung** [comment]
Cc @rust-lang/wg-const-eval

File: src/librustc_mir/interpret/validity.rs [hunk 1]
```diff
@@ -46,6 +47,24 @@ macro_rules! try_validation {
...
+/// ```rust
+/// let v = try_validation_pat(some_fn(), Foo | Bar | Baz, "some failure", "some place");
+/// // Failures that match $p are thrown up as validation errors, but other errors are passed back
+/// // unchanged.
+/// ```
+macro_rules! try_validation_pat {
+    ($e:expr, $( $p:pat )|*, $what:expr, $where:expr $(, $details:expr )?) => {{
+        match $e {
+            Ok(x) => x,
+            $( Err($p) )|* if true => throw_validation_failure!($what, $where $(, $details)?),
```
Comment (oli-obk) [inline src/librustc_mir/interpret/validity.rs:61]: Instead of `if true`, can you silence the lint via `#[allow` instead?

**Review by oli-obk — COMMENTED** [review]
I love it, this is very precisely targetting the issue, I wonder if we should extend the use of `try_validation_pat` to other situations (out of scope for this PR obviously).

Do we have a test for the ICE that was caused by the earlier fix? Just to make sure we don't regress that case again :)

File: src/librustc_mir/interpret/validity.rs [hunk 2]
```diff
@@ -24,43 +25,41 @@ use super::{
...
-    }};
-    ($what:expr, $where:expr) => {{
+    ($what:expr, $where:expr $(, $details:expr )?) => {{
         let mut msg = format!("encountered {}", $what);
         let where_ = &$where;
         if !where_.is_empty() {
             msg.push_str(" at ");
             write_path(&mut msg, where_);
         }
+        $( write!(&mut msg, ", but expected {}", $details).unwrap(); )?
```
Comment (RalfJung) [inline src/librustc_mir/interpret/validity.rs:35]: Oooh this is clever. :)
I clearly don't know macros well enough.^^

File: src/librustc_mir/interpret/validity.rs [hunk 3]
```diff
@@ -24,43 +25,41 @@ use super::{
...
         throw_ub!(ValidationFailure(msg))
     }};
 }
 
+/// Returns a validation failure for any Err value of $e.
 macro_rules! try_validation {
```
Comment (RalfJung) [inline src/librustc_mir/interpret/validity.rs:41]: Please add a FIXME to migrate everything to `try_validation_pat`.

File: src/librustc_mir/interpret/validity.rs [hunk 4]
```diff
@@ -24,43 +25,41 @@ use super::{
...
+/// matched. Other errors are passed back to the caller, unchanged. This lets you use the patterns
+/// as a kind of validation blacklist:
+///
+/// ```rust
+/// let v = try_validation_pat(some_fn(), Foo | Bar | Baz, "some failure", "some place");
+/// // Failures that match $p are thrown up as validation errors, but other errors are passed back
+/// // unchanged.
+/// ```
+macro_rules! try_validation_pat {
+    ($e:expr, $( $p:pat )|*, $what:expr, $where:expr $(, $details:expr )?) => {{
```
Comment (RalfJung) [inline src/librustc_mir/interpret/validity.rs:56]: I wonder if we can come up with a better syntax that this function-like one? Maybe
```rust
try_validation_pat!(some_fn() {
  Foo | Bar | Baz => "some failure" @ self.path
})
```
That's more readable -- maybe?

File: src/librustc_mir/interpret/validity.rs [hunk 5]
```diff
@@ -24,43 +25,41 @@ use super::{
...
     }};
-
-    ($e:expr, $what:expr, $where:expr) => {{
+}
+/// Like try_validation, but will throw a validation error if any of the patterns in $p are
+/// matched. Other errors are passed back to the caller, unchanged. This lets you use the patterns
+/// as a kind of validation blacklist:
+///
+/// ```rust
+/// let v = try_validation_pat(some_fn(), Foo | Bar | Baz, "some failure", "some place");
```
Comment (RalfJung) [inline src/librustc_mir/interpret/validity.rs:51]:
```suggestion
/// let v = try_validation_pat(some_fn(), Foo | Bar | Baz, "some failure", path);
```

File: src/librustc_mir/interpret/validity.rs [hunk 6]
```diff
@@ -484,8 +483,9 @@ impl<'rt, 'mir, 'tcx: 'mir, M: Machine<'mir, 'tcx>> ValidityVisitor<'rt, 'mir, '
                 // We are conservative with undef for integers, but try to
                 // actually enforce the strict rules for raw pointers (mostly because
                 // that lets us re-use `ref_to_mplace`).
-                let place = try_validation!(
+                let place = try_validation_pat!(
                     self.ecx.ref_to_mplace(self.ecx.read_immediate(value)?),
+                    InterpErrorInfo { kind: err_ub!(InvalidUndefBytes(..)), ..},
```
Comment (RalfJung) [inline src/librustc_mir/interpret/validity.rs:488]: Please adjust `try_validation_pat` so we match on the `InterpError`, no need to repeat this unwrapping of `InterpErrorInfo` everywhere.

File: src/librustc_mir/interpret/validity.rs [hunk 7]
```diff
@@ -835,9 +835,12 @@ impl<'mir, 'tcx: 'mir, M: Machine<'mir, 'tcx>> InterpCx<'mir, 'tcx, M> {
         // Run it.
         match visitor.visit_value(op) {
             Ok(()) => Ok(()),
-            // We should only get validation errors here. Avoid other errors as
-            // those do not show *where* in the value the issue lies.
+            // Allow validation failures to be returned.
             Err(err) if matches!(err.kind, err_ub!(ValidationFailure { .. })) => Err(err),
+            // Also allow InvalidProgram to be returned, because it's likely that different callers
+            // will want to do different things in this situation.
```
Comment (RalfJung) [inline src/librustc_mir/interpret/validity.rs:841]:
```suggestion
            // Also pass through InvalidProgram, those just indicate that we could not
            // validate and each caller will know best what to do with them.
```

File: src/librustc_mir/interpret/validity.rs [hunk 8]
```diff
@@ -835,9 +835,12 @@ impl<'mir, 'tcx: 'mir, M: Machine<'mir, 'tcx>> InterpCx<'mir, 'tcx, M> {
         // Run it.
         match visitor.visit_value(op) {
             Ok(()) => Ok(()),
-            // We should only get validation errors here. Avoid other errors as
-            // those do not show *where* in the value the issue lies.
+            // Allow validation failures to be returned.
```
Comment (RalfJung) [inline src/librustc_mir/interpret/validity.rs:838]:
```suggestion
            // Pass through validation failures.
```

File: src/librustc_mir/interpret/validity.rs [hunk 9]
```diff
@@ -835,9 +835,12 @@ impl<'mir, 'tcx: 'mir, M: Machine<'mir, 'tcx>> InterpCx<'mir, 'tcx, M> {
         // Run it.
```
Comment (RalfJung) [inline src/librustc_mir/interpret/validity.rs:835]: While we are adjusting the forwarding here, could you also adjust the comment `// Other errors shouldn't be possible` above (line 795) to match what we do elsewhere when propagating?
```rust
// Propagate other errors upwards (that will also check for unexpected errors).
```

File: src/librustc_mir/interpret/validity.rs [hunk 10]
```diff
@@ -46,6 +47,24 @@ macro_rules! try_validation {
...
+/// let v = try_validation_pat(some_fn(), Foo | Bar | Baz, "some failure", "some place");
+/// // Failures that match $p are thrown up as validation errors, but other errors are passed back
+/// // unchanged.
+/// ```
+macro_rules! try_validation_pat {
+    ($e:expr, $( $p:pat )|*, $what:expr, $where:expr $(, $details:expr )?) => {{
+        match $e {
+            Ok(x) => x,
+            $( Err($p) )|* if true => throw_validation_failure!($what, $where $(, $details)?),
+            Err(e) =>  Err::<!, _>(e)?,
```
[the remark this answers is not in the document]
Comment (RalfJung) [reply src/librustc_mir/interpret/validity.rs:62]: So this propagates non-matching failures upwards, right?
Please add a comment for this like elsewhere:
```rust
// Propagate other errors upwards (that will also check for unexpected errors).
```

File: src/test/ui/consts/const-eval/ice-generic-assoc-const.rs [hunk 11]
```diff
@@ -14,3 +13,6 @@ impl<T> Nullable for *const T {
         *self == Self::NULL
     }
 }
+
+fn main() {
+}
```
Comment (RalfJung) [inline src/test/ui/consts/const-eval/ice-generic-assoc-const.rs:18]: No please do *not* change this test! Your PR is reverting the test back to the broken state where it doesn't actually trigger the ICE.

**Comment by RalfJung** [comment]
> Do we have a test for the ICE that was caused by the earlier fix? Just to make sure we don't regress that case again :)

Yes we do: `src/test/ui/consts/const-eval/ice-generic-assoc-const.rs`. Except that this PR breaks that test again, which obviously it should not do.

File: src/librustc_mir/interpret/validity.rs (hunk 4 above)
Comment (jumbatm) [reply src/librustc_mir/interpret/validity.rs:56]: I'd 100% be down for something like this, but the issue is that `expr`s can only be followed by `,`, `=>` or `;`, so it'd have to be something like

```rust
try_validation_pat!(some_fn(); {
    Foo | Bar | Baz => "some failure", details, @ self.path,
    Quux | Quuux => "some other failure", @ self.path,
});
```
ie, you'd need to delimit `some_fn()`, and you'd also need to delimit the what, where and details. The sigil `@` on the "where" parameter would also be necessary, so that the end of each case can be distinguished. An alternative would be to have each arm delimited by a `;`, but then it wouldn't look similar to a match expression anymore.

Hmm, looking at it now, that's still a fair readability improvement over the function-like syntax . It's definitely easier to tell which parameters are what. Downside is that it's as natural to write as the syntax you suggested. Would you mind this syntax?

Comment (RalfJung) [reply src/librustc_mir/interpret/validity.rs:56]: Can't we use custom tokens (like `@path`) to delimit expressions?

Comment (RalfJung) [reply src/librustc_mir/interpret/validity.rs:56]: Hm, looks like we cannot, bummer. So let's improvise. Based on what you proposed... but also, `self.path` will be the same for all branches... so what about this?
```rust
try_validation_pat!(some_fn(), self.path, {
    Foo | Bar | Baz => "bad bytes", @expected "a pointer",
    Quux | Quuux => "some other failure",
});
```
Ideally we could even have built-in support for format strings, instead of repeating `format_args!` everywhere. Maybe `what` and `details` (should be renamed to `expected`?) should just be `tt` and we add some extra parentheses?

File: src/librustc_mir/interpret/validity.rs [hunk 12]
```diff
@@ -24,43 +25,71 @@ use super::{
...
+        try_validation_pat!($e, $where, {
+            _ => { "{}", $what } $( expected { "{}", $expected } )?,
+        })
     }};
-
-    ($e:expr, $what:expr, $where:expr) => {{
+}
+/// Like try_validation, but will throw a validation error if any of the patterns in $p are
+/// matched. Other errors are passed back to the caller, unchanged. This lets you use the patterns
+/// as a kind of validation blacklist:
```
Comment (RalfJung) [inline src/librustc_mir/interpret/validity.rs:51]: Isn't it more of a whitelist? Unexpected errors will bubble up to the root and cause ICEs.

File: src/librustc_mir/interpret/validity.rs [hunk 13]
```diff
@@ -24,43 +25,71 @@ use super::{
...
+    ($e:expr, $where:expr, { $( $p:pat )|+ =>
+        { $( $what_fmt:expr ),+ } $( expected { $( $expected_fmt:expr ),+ } )? $( , )?}) => {{
         match $e {
             Ok(x) => x,
-            // We re-throw the error, so we are okay with allocation:
-            // this can only slow down builds that fail anyway.
-            Err(_) => throw_validation_failure!($what, $where),
+            // We catch the error and turn it into a validation failure. We are okay with
+            // allocation here as this can only slow down builds that fail anyway.
+            $( Err(InterpErrorInfo { kind: $p, .. }) )|+ =>
```
Comment (RalfJung) [inline src/librustc_mir/interpret/validity.rs:85]: Wow this is advanced macro magic, cool stuff.

File: src/librustc_mir/interpret/validity.rs [hunk 14]
```diff
@@ -24,43 +25,71 @@ use super::{
...
+///     Foo | Bar | Baz => { "some failure" } expected { "something that wasn't a failure" },
+/// });
+/// ```
+///
+/// An additional nicety is that both parameters actually take format args, so you can just write
+/// the format string in directly:
+///
+/// ```
+/// let v = try_validation_pat!(some_fn(), some_path, {
+///     Foo | Bar | Baz => { "{:?}", some_failure } expected { "{}", expected_value },
```
Comment (RalfJung) [inline src/librustc_mir/interpret/validity.rs:74]: This is great. :D

I think my one complaint is that using curly braces to delemit parameters is a bit odd. We don't write `format_args!{ "{:?}", some_failure }` either. But I don't have a better proposal off the top of my head either... @oli-obk any ideas?

Comment (oli-obk) [reply src/librustc_mir/interpret/validity.rs:74]: I can't come up with a nicer syntax off the top of my head. Parens would definitely look worse:

```
Foo | Bar | Baz => ("{:?}", some_failure) expected("{}", expected_value),
```

I think it's fine as it is.

Comment (RalfJung) [reply src/librustc_mir/interpret/validity.rs:74]: Okay, let's go with curly braces then.

Should we replace `expected` by `@expected` or so to more clearly mark it as a keyword? Not sure what the usual macro conventions are, this is certainly something I have seen before.

Comment (oli-obk) [reply src/librustc_mir/interpret/validity.rs:74]: I think it's standing out enough by the definitely not-legal-rust syntax. But I wouldn't mind an additional `@` if you think that makes it clearer.

Comment (RalfJung) [reply src/librustc_mir/interpret/validity.rs:74]: Okay, let's go with this for now, we can always change it later.

**Comment by RalfJung** [comment]
Thanks @jumbatm!
@bors r+
