### PR TITLE
Normalize capture place `ty`s to prevent ICE

### LINKED ISSUE #120811: error: internal compiler error: no errors encountered even though `span_delayed_bug` issued
### Code

Unfortunately it's nearly impossible for me to figure out where the problem actually happens, so finding a minimal example is tough.

Branch here: https://github.com/antiguru/timely-dataflow/tree/container_gat_ice

Command:
```
RUST_BACKTRACE=1 cargo check --features bincode --example wordcount_flatcontainer
```

### Meta

`rustc --version --verbose`:
```
➜  timely-dataflow git:(container_gat_ice) rustc --version --verbose
rustc 1.76.0 (07dca489a 2024-02-04)
binary: rustc
commit-hash: 07dca489ac2d933c78d3c5158e3f43beefeb02ce
commit-date: 2024-02-04
host: x86_64-unknown-linux-gnu
release: 1.76.0
LLVM version: 17.0.6
➜
```

The same error happens on nightly.

### Error output

```
warning: unnecessary `unsafe` block
  --> communication/src/allocator/zero_copy/push_pull.rs:93:26
   |
93 |             .map(|bytes| unsafe { Message::from_bytes(bytes) });
   |                          ^^^^^^ unnecessary `unsafe` block
   |
   = note: `#[warn(unused_unsafe)]` on by default

warning: unnecessary `unsafe` block
   --> communication/src/allocator/zero_copy/push_pull.rs:137:30
    |
137 |                 .map(|bytes| unsafe { Message::from_bytes(bytes) });
    |                              ^^^^^^ unnecessary `unsafe` block

warning: variant `Binary` is never constructed
  --> communication/src/message.rs:72:5
   |
70 | enum MessageContents<T> {
   |      --------------- variant in this enum
71 |     /// Binary representation. Only available as a reference.
72 |     Binary(abomonation::abomonated::Abomonated<T, Bytes>),
   |     ^^^^^^
   |
   = note: `#[warn(dead_code)]` on by default

warning: `timely_communication` (lib) generated 3 warnings
    Checking timely v0.12.0 (/home/moritz/dev/repos/timely-dataflow/timely)
warning: variable does not need to be mutable
  --> timely/examples/wordcount_flatcontainer.rs:44:37
   |
44 | ...                   for mut batch in val.drain(..) {
   |                           ----^^^^^
   |                           |
   |                           help: remove this `mut`
   |
   = note: `#[warn(unused_mut)]` on by default

error: internal compiler error: no errors encountered even though `span_delayed_bug` issued

error: internal compiler error: broken MIR in DefId(0:18 ~ wordcount_flatcontainer[7bab]::main::{closure#0}) ({closure@timely/examples/wordcount_flatcontainer.rs:22:38: 22:45} { input: move _10, exchange: move _5, probe: move _11 }): timely::dataflow::channels::pact::ExchangeCore<timely_container::flatcontainer::FlatStack<timely_container::flatcontainer::impls::tuple::TupleABRegion<timely_container::flatcontainer::StringRegion, timely_container::flatcontainer::MirrorRegion<i64>>>, Closure(DefId(0:19 ~ wordcount_flatcontainer[7bab]::main::{closure#0}::{closure#0}), [i16, Binder(extern "RustCall" fn((&ReBound(DebruijnIndex(0), BoundRegion { var: 0, kind: BrAnon }) (&ReBound(DebruijnIndex(0), BoundRegion { var: 1, kind: BrAnon }) str, i64),)) -> u64, [Region(BrAnon), Region(BrAnon)]), ()])> is not a subtype of timely::dataflow::channels::pact::ExchangeCore<timely_container::flatcontainer::FlatStack<timely_container::flatcontainer::impls::tuple::TupleABRegion<timely_container::flatcontainer::StringRegion, timely_container::flatcontainer::MirrorRegion<i64>>>, Closure(DefId(0:19 ~ wordcount_flatcontainer[7bab]::main::{closure#0}::{closure#0}), [i16, Binder(extern "RustCall" fn((&ReBound(DebruijnIndex(0), BoundRegion { var: 0, kind: BrAnon }) Alias(Projection, AliasTy { args: [timely_container::flatcontainer::FlatStack<timely_container::flatcontainer::impls::tuple::TupleABRegion<timely_container::flatcontainer::StringRegion, timely_container::flatcontainer::MirrorRegion<i64>>>, ReBound(DebruijnIndex(0), BoundRegion { var: 1, kind: BrAnon })], def_id: DefId(34:167 ~ timely_container[8ff9]::Container::Item) }),)) -> u64, [Region(BrAnon), Region(BrAnon)]), ()])>: NoSolution
  --> timely/examples/wordcount_flatcontainer.rs:22:38
   |
22 |           worker.dataflow::<usize,_,_>(|scope| {
   |  ______________________________________^
23 | |             input.to_stream(scope)
24 | |                  .flat_map::<FlatStack<<(String, i64) as Containerized>::Region>, _, _>(|(text, diff): (String, i64)|
25 | |                     text.split_whitespace()
...  |
57 | |                  .probe_with(&mut probe);
58 | |         });
   | |_________^
   |
note: delayed at compiler/rustc_borrowck/src/type_check/mod.rs:2440:17
         0: <rustc_errors::DiagCtxtInner>::emit_diagnostic_without_consuming
         1: <rustc_errors::DiagCtxtInner>::emit_diagnostic
         2: <rustc_errors::DiagCtxt>::span_delayed_bug::<rustc_span::span_encoding::Span, alloc::string::String>
         3: <rustc_borrowck::type_check::TypeChecker>::typeck_mir
         4: rustc_borrowck::type_check::type_check
         5: rustc_borrowck::nll::compute_regions
         6: rustc_borrowck::do_mir_borrowck
         7: rustc_borrowck::mir_borrowck
         8: rustc_query_impl::plumbing::__rust_begin_short_backtrace::<rustc_query_impl::query_impl::mir_borrowck::dynamic_query::{closure#2}::{closure#0}, rustc_middle::query::erase::Erased<[u8; 8]>>
         9: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::DynamicConfig<rustc_query_system::query::caches::VecCache<rustc_span::def_id::LocalDefId, rustc_middle::query::erase::Erased<[u8; 8]>>, false, false, false>, rustc_query_impl::plumbing::QueryCtxt, true>
        10: rustc_query_impl::query_impl::mir_borrowck::get_query_incr::__rust_end_short_backtrace
        11: <rustc_borrowck::type_check::TypeChecker>::prove_closure_bounds
        12: <rustc_borrowck::type_check::TypeChecker>::typeck_mir
        13: rustc_borrowck::type_check::type_check
        14: rustc_borrowck::nll::compute_regions
        15: rustc_borrowck::do_mir_borrowck
        16: rustc_borrowck::mir_borrowck
        17: rustc_query_impl::plumbing::__rust_begin_short_backtrace::<rustc_query_impl::query_impl::mir_borrowck::dynamic_query::{closure#2}::{closure#0}, rustc_middle::query::erase::Erased<[u8; 8]>>
        18: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::DynamicConfig<rustc_query_system::query::caches::VecCache<rustc_span::def_id::LocalDefId, rustc_middle::query::erase::Erased<[u8; 8]>>, false, false, false>, rustc_query_impl::plumbing::QueryCtxt, true>
        19: rustc_query_impl::query_impl::mir_borrowck::get_query_incr::__rust_end_short_backtrace
        20: rustc_interface::passes::analysis
        21: rustc_query_impl::plumbing::__rust_begin_short_backtrace::<rustc_query_impl::query_impl::analysis::dynamic_query::{closure#2}::{closure#0}, rustc_middle::query::erase::Erased<[u8; 1]>>
        22: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::DynamicConfig<rustc_query_system::query::caches::SingleCache<rustc_middle::query::erase::Erased<[u8; 1]>>, false, false, false>, rustc_query_impl::plumbing::QueryCtxt, true>
        23: rustc_query_impl::query_impl::analysis::get_query_incr::__rust_end_short_backtrace
        24: rustc_interface::interface::run_compiler::<core::result::Result<(), rustc_span::ErrorGuaranteed>, rustc_driver_impl::run_compiler::{closure#0}>::{closure#0}
        25: std::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface::util::run_in_thread_with_globals<rustc_interface::interface::run_compiler<core::result::Result<(), rustc_span::ErrorGuaranteed>, rustc_driver_impl::run_compiler::{closure#0}>::{closure#0}, core::result::Result<(), rustc_span::ErrorGuaranteed>>::{closure#0}::{closure#0}, core::result::Result<(), rustc_span::ErrorGuaranteed>>
        26: <<std::thread::Builder>::spawn_unchecked_<rustc_interface::util::run_in_thread_with_globals<rustc_interface::interface::run_compiler<core::result::Result<(), rustc_span::ErrorGuaranteed>, rustc_driver_impl::run_compiler::{closure#0}>::{closure#0}, core::result::Result<(), rustc_span::ErrorGuaranteed>>::{closure#0}::{closure#0}, core::result::Result<(), rustc_span::ErrorGuaranteed>>::{closure#1} as core::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
        27: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
                   at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/alloc/src/boxed.rs:2015:9
        28: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
                   at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/alloc/src/boxed.rs:2015:9
        29: std::sys::unix::thread::Thread::new::thread_start
                   at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/sys/unix/thread.rs:108:17
        30: start_thread
                   at ./nptl/pthread_create.c:444:8
        31: __GI___clone3
                   at ./misc/../sysdeps/unix/sysv/linux/x86_64/clone3.S:81
  --> timely/examples/wordcount_flatcontainer.rs:22:38
   |
22 |           worker.dataflow::<usize,_,_>(|scope| {
   |  ______________________________________^
23 | |             input.to_stream(scope)
24 | |                  .flat_map::<FlatStack<<(String, i64) as Containerized>::Region>, _, _>(|(text, diff): (String, i64)|
25 | |                     text.split_whitespace()
...  |
57 | |                  .probe_with(&mut probe);
58 | |         });
   | |_________^

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.76.0 (07dca489a 2024-02-04) running on x86_64-unknown-linux-gnu

note: compiler flags: --crate-type bin -C embed-bitcode=no -C debuginfo=2 -C incremental=[REDACTED]

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
warning: `timely` (example "wordcount_flatcontainer") generated 1 warning (run `cargo fix --example "wordcount_flatcontainer"` to apply 1 suggestion)
error: could not compile `timely` (example "wordcount_flatcontainer"); 1 warning emitted
```

### PR DESCRIPTION
**Pull request by JohnTitor**
Fixes rust-lang/rust#151579
Fixes https://github.com/rust-lang/rust/issues/120811
r? @lcnr

### CODE REVIEW

File: compiler/rustc_middle/src/ty/closure.rs [hunk 1]
```diff
@@ -304,41 +309,64 @@ pub fn place_to_string_for_capture<'tcx>(tcx: TyCtxt<'tcx>, place: &HirPlace<'tc
...
 
     curr_string
 }
 
+fn typing_env_for_place<'tcx>(tcx: TyCtxt<'tcx>, place: &HirPlace<'tcx>) -> ty::TypingEnv<'tcx> {
+    match place.base {
+        HirPlaceBase::Upvar(upvar_id) => {
+            ty::TypingEnv::post_analysis(tcx, upvar_id.closure_expr_id)
+        }
+        _ => ty::TypingEnv::fully_monomorphized(),
```
Comment (lcnr) [inline compiler/rustc_middle/src/ty/closure.rs]: This is hacky and subtly wrong in two ways.
- even if the type is not from an upvar, we still need the right param_env to normalize
- we use this during MIR build, so it should probably use `TypingMode::Borrowck` or whatever

see https://rustc-dev-guide.rust-lang.org/typing-parameter-envs.html

**Review by lcnr — COMMENTED** [review]
ah, I didn't see we always get these types from the `typeck_results`. We should deeply normalize them in writeback and then assume that they are normalized afterwards

*[View changes since this review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/rust/152165/286fbe5d84569c718f189122db9e68a16b50eeef..a544343ee3a6f57f7252500ad12f912c6d0b4972)*

File: compiler/rustc_middle/src/ty/closure.rs (hunk 1 above)
Comment (JohnTitor) [reply compiler/rustc_middle/src/ty/closure.rs]: Ah I see, I've switched to use `try_structurally_resolve_ty` as mentioned in the issue: [`176bf7d` (this PR)](https://github.com/rust-lang/rust/pull/152165/commits/176bf7d1f083c95ff5feff39d87d9435a1e84041)
This way, we can avoid deep normalization here, right?

File: compiler/rustc_hir_typeck/src/upvar.rs [hunk 2]
```diff
@@ -1127,6 +1128,19 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
         }
     }
 
+    fn try_structurally_resolve_place_ty(&self, span: Span, place: &mut Place<'tcx>) {
+        place.base_ty = self.try_structurally_resolve_type(span, place.base_ty);
```
Comment (lcnr) [inline compiler/rustc_hir_typeck/src/upvar.rs]: use `deeply_normalize` here. We deeply normalize types in the writeback results, so I think we should do the same here

Comment (JohnTitor) [reply compiler/rustc_hir_typeck/src/upvar.rs]: Just replacing didn't work so I had to do something like this instead: https://github.com/rust-lang/rust/pull/152165/changes/750cd5365fd0d79e6318ce5147b48d7a20e871cf

Is this what you meant for?

Comment (lcnr) [reply compiler/rustc_hir_typeck/src/upvar.rs]: can you use `at.deeply_normalize` with both solvers?

Comment (JohnTitor) [reply compiler/rustc_hir_typeck/src/upvar.rs]: I've tried but had to construct `TraitEngine` there which seems an unusual way (I haven't seen such a way in other places).
Instead, I guess using `ObligationCtxt` might be better here, other places do this way and it shoudl call `at.deeply_normalize` internally: https://github.com/rust-lang/rust/pull/152165/changes/a7ea420b8318ed671b58802f0515b403be41db76
How about this?

File: compiler/rustc_hir_typeck/src/upvar.rs [hunk 3]
```diff
@@ -1229,7 +1254,7 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
                 problematic_captures.insert(
                     UpvarMigrationInfo::CapturingPrecise {
                         source_expr: capture.info.path_expr_id,
-                        var_name: capture.to_string(self.tcx),
+                        var_name: self.place_to_string_for_migration(capture),
```
Comment (lcnr) [inline compiler/rustc_hir_typeck/src/upvar.rs]: can we move this normalization even further up so that `catpure.place` is already deeply normalized and we don't have to do so here?

Comment (JohnTitor) [reply compiler/rustc_hir_typeck/src/upvar.rs]: Moved: https://github.com/rust-lang/rust/pull/152165/changes/c22ffdbc30b6e353e8d5bf6b07a772104ecfdc88
I wonder if we should reduce scope by  `if next_solver` as we now normalize stuff more generally, i.e. other than emitting lint `rust_2021_incompatible_closure_captures` and it would bring unnecessary cost for most cases :thinking:

File: compiler/rustc_hir_typeck/src/upvar.rs [hunk 4]
```diff
@@ -1127,6 +1133,26 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
         }
     }
 
+    fn try_structurally_resolve_place_ty(&self, span: Span, place: &mut Place<'tcx>) {
```
Comment (lcnr) [inline compiler/rustc_hir_typeck/src/upvar.rs]: `deeply_normalize` should normalize arbitrary `TypeFoldable` things. Is `Place` type foldable?

Also, change this function name :>

Comment (JohnTitor) [reply compiler/rustc_hir_typeck/src/upvar.rs]: Ah, you're right, it's `TypeFoldable`. Addressed: https://github.com/rust-lang/rust/pull/152165/changes/7def3bc8ed76c953ccad3108fd17d8959a144e7d
And I noticed we have another win, it would fix https://github.com/rust-lang/rust/issues/120811 (N.B. crashes/120911 is a dup of 120811, so I removed it).

**Comment by lcnr** [comment]
I messed up by reviewing your commit directly yesterday, see https://github.com/rust-lang/rust/commit/c22ffdbc30b6e353e8d5bf6b07a772104ecfdc88#r177216090

File: compiler/rustc_hir_typeck/src/upvar.rs [hunk 5]
```diff
@@ -197,17 +199,18 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
         let closure_def_id = closure_def_id.expect_local();
 
         assert_eq!(self.tcx.hir_body_owner_def_id(body.id()), closure_def_id);
+
+        // Used by `ExprUseVisitor` when collecting closure capture information.
```
Comment (lcnr) [inline compiler/rustc_hir_typeck/src/upvar.rs]: This comment feels is odd. It states information which is clearly visible 3 lines down. You could state sth like "We need to create a separate `FnCtxt` for nested bodies"

Creating `FnCtxt`s for nested bodies is also something we normally do, so I don't know if that is that useful either. I think it's fine to just not have a comment here at all

Comment (JohnTitor) [reply compiler/rustc_hir_typeck/src/upvar.rs]: Ok, removed in https://github.com/rust-lang/rust/pull/152165/changes/ebefb53c2a16a39ba6b6f0f47efd1da29fca994a.

File: compiler/rustc_hir_typeck/src/upvar.rs [hunk 6]
```diff
@@ -1126,6 +1128,44 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
             );
         }
     }
+    fn normalize_capture_place(&self, span: Span, place: &mut Place<'tcx>) {
+        *place = self.resolve_vars_if_possible(place.clone());
+
```
Comment (lcnr) [inline compiler/rustc_hir_typeck/src/upvar.rs:1133]: why `&mut Place` instead of taking by value and returning it again?

File: compiler/rustc_hir_typeck/src/upvar.rs [hunk 7]
```diff
@@ -2047,8 +2093,11 @@ impl<'tcx> euv::Delegate<'tcx> for InferBorrowKind<'tcx> {
         // such as deref of a raw pointer.
         let dummy_capture_kind = ty::UpvarCapture::ByRef(ty::BorrowKind::Immutable);
 
-        let (place, _) =
-            restrict_capture_precision(place_with_id.place.clone(), dummy_capture_kind);
+        let span = self.fcx.tcx.hir_span(diag_expr_id);
+        let mut place = place_with_id.place.clone();
+        self.fcx.normalize_capture_place(span, &mut place);
```
Comment (lcnr) [inline compiler/rustc_hir_typeck/src/upvar.rs]: could also eagerly normalize `closure_fake_reads` 🤔

Comment (lcnr) [reply compiler/rustc_hir_typeck/src/upvar.rs]: though, I guess this is fine for now as making sure the `ExprUseVisitor` always handles things correctly seems like a bigger change

File: compiler/rustc_hir_typeck/src/upvar.rs (hunk 6 above)
Comment (JohnTitor) [reply compiler/rustc_hir_typeck/src/upvar.rs:1133]: Fair enough, addressed in https://github.com/rust-lang/rust/pull/152165/changes/dddbf96f9176ba38e27ef96509d802ee45c67d2b

File: compiler/rustc_hir_typeck/src/upvar.rs (hunk 7 above)
Comment (JohnTitor) [reply compiler/rustc_hir_typeck/src/upvar.rs]: Alright, should I add FIXME or something else?

File: compiler/rustc_hir_typeck/src/upvar.rs [hunk 8]
```diff
@@ -1126,6 +1128,45 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
...
+        let mut place = self.resolve_vars_if_possible(place);
+
+        // In the new solver, types in HIR `Place`s can contain unnormalized aliases,
+        // which can ICE later (e.g. when projecting fields for diagnostics).
+        if self.next_trait_solver() {
+            let cause = self.misc(span);
+            let at = self.at(&cause, self.param_env);
+            match solve::deeply_normalize_with_skipped_universes_and_ambiguous_coroutine_goals(
+                at,
+                place.clone(),
```
Comment (lcnr) [inline compiler/rustc_hir_typeck/src/upvar.rs:1141]: why clone?

Comment (lcnr) [reply compiler/rustc_hir_typeck/src/upvar.rs:1141]: i guess to return some place in the error case?

File: compiler/rustc_hir_typeck/src/upvar.rs (hunk 7 above)
Comment (lcnr) [reply compiler/rustc_hir_typeck/src/upvar.rs]: Hmm, I think `ExprUseVisitor` is generally fairly weird and we should clean this up. Don't have a good sense of how it should work.

Adding "clean up `ExprUseVisitor`" as a genreal work item to my type system roadmap/planning thingy
