### PR TITLE
recursively evaluate the constants in everything that is 'mentioned'

### LINKED ISSUE #107503: Const-eval errors in dead functions are optimization-dependent
I tried this code: [[playground]](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=1ffcf365aa942927bfb5f465c4dc4e99)

```rust
#![feature(inline_const)]

pub fn cause_late_error<T>() {
    const {
        panic!()
    };
}

fn main() {
    let a = 1;
    let b = 2;
    if a + b == 5 {
        cause_late_error::<()>();
    }
}
```

I expected to see this happen:

```text
error[E0080]: evaluation of `cause_late_error::<()>::{constant#0}` failed
 --> src/main.rs:7:9
  |
7 |         panic!()
  |         ^^^^^^^^ the evaluated program panicked at 'explicit panic', src/main.rs:7:9
  |
  = note: this error originates in the macro `$crate::panic::panic_2021` which comes from the expansion of the macro `panic` (in Nightly builds, run with -Z macro-backtrace for more info)

note: the above error was encountered while instantiating `fn cause_late_error::<()>`
  --> src/main.rs:13:9
   |
13 |         cause_late_error::<()>();
   |         ^^^^^^^^^^^^^^^^^^^^^^^^
```

Instead, this happened: it compiled without any warnings.

### Meta

Playground nightly, 1.69.0-nightly (2023-01-30 001a77fac33f6560ff36)

### Related

- https://github.com/rust-lang/rust/issues/85836
- https://github.com/rust-lang/rust/pull/104087
- https://github.com/rust-lang/rust/issues/106617

Potential fix:

- #122568

### PR DESCRIPTION
**Pull request by RalfJung**
This is another attempt at fixing https://github.com/rust-lang/rust/issues/107503. The previous attempt at https://github.com/rust-lang/rust/pull/112879 seems stuck in figuring out where the [perf regression](https://perf.rust-lang.org/compare.html?start=c55d1ee8d4e3162187214692229a63c2cc5e0f31&end=ec8de1ebe0d698b109beeaaac83e60f4ef8bb7d1&stat=instructions:u) comes from. In  https://github.com/rust-lang/rust/pull/122258 I learned some things, which informed the approach this PR is taking.

Quoting from the new collector docs, which explain the high-level idea:
```rust
//! One important role of collection is to evaluate all constants that are used by all the items
//! which are being collected. Codegen can then rely on only encountering constants that evaluate
//! successfully, and if a constant fails to evaluate, the collector has much better context to be
//! able to show where this constant comes up.
//!
//! However, the exact set of "used" items (collected as described above), and therefore the exact
//! set of used constants, can depend on optimizations. Optimizing away dead code may optimize away
//! a function call that uses a failing constant, so an unoptimized build may fail where an
//! optimized build succeeds. This is undesirable.
//!
//! To fix this, the collector has the concept of "mentioned" items. Some time during the MIR
//! pipeline, before any optimization-level-dependent optimizations, we compute a list of all items
//! that syntactically appear in the code. These are considered "mentioned", and even if they are in
//! dead code and get optimized away (which makes them no longer "used"), they are still
//! "mentioned". For every used item, the collector ensures that all mentioned items, recursively,
//! do not use a failing constant. This is reflected via the [`CollectionMode`], which determines
//! whether we are visiting a used item or merely a mentioned item.
//!
//! The collector and "mentioned items" gathering (which lives in `rustc_mir_transform::mentioned_items`)
//! need to stay in sync in the following sense:
//!
//! - For every item that the collector gather that could eventually lead to build failure (most
//!   likely due to containing a constant that fails to evaluate), a corresponding mentioned item
//!   must be added. This should use the exact same strategy as the ecollector to make sure they are
//!   in sync. However, while the collector works on monomorphized types, mentioned items are
//!   collected on generic MIR -- so any time the collector checks for a particular type (such as
//!   `ty::FnDef`), we have to just onconditionally add this as a mentioned item.
//! - In `visit_mentioned_item`, we then do with that mentioned item exactly what the collector
//!   would have done during regular MIR visiting. Basically you can think of the collector having
//!   two stages, a pre-monomorphization stage and a post-monomorphization stage (usually quite
//!   literally separated by a call to `self.monomorphize`); the pre-monomorphizationn stage is
//!   duplicated in mentioned items gathering and the post-monomorphization stage is duplicated in
//!   `visit_mentioned_item`.
//! - Finally, as a performance optimization, the collector should fill `used_mentioned_item` during
//!   its MIR traversal with exactly what mentioned item gathering would have added in the same
//!   situation. This detects mentioned items that have *not* been optimized away and hence don't
//!   need a dedicated traversal.

enum CollectionMode {
    /// Collect items that are used, i.e., actually needed for codegen.
    ///
    /// Which items are used can depend on optimization levels, as MIR optimizations can remove
    /// uses.
    UsedItems,
    /// Collect items that are mentioned. The goal of this mode is that it is independent of
    /// optimizations: the set of "mentioned" items is computed before optimizations are run.
    ///
    /// The exact contents of this set are *not* a stable guarantee. (For instance, it is currently
    /// computed after drop-elaboration. If we ever do some optimizations even in debug builds, we
    /// might decide to run them before computing mentioned items.) The key property of this set is
    /// that it is optimization-independent.
    MentionedItems,
}
```
And the `mentioned_items` MIR body field docs:
```rust
    /// Further items that were mentioned in this function and hence *may* become monomorphized,
    /// depending on optimizations. We use this to avoid optimization-dependent compile errors: the
    /// collector recursively traverses all "mentioned" items and evaluates all their
    /// `required_consts`.
    ///
    /// This is *not* soundness-critical and the contents of this list are *not* a stable guarantee.
    /// All that's relevant is that this set is optimization-level-independent, and that it includes
    /// everything that the collector would consider "used". (For example, we currently compute this
    /// set after drop elaboration, so some drop calls that can never be reached are not considered
    /// "mentioned".) See the documentation of `CollectionMode` in
    /// `compiler/rustc_monomorphize/src/collector.rs` for more context.
    pub mentioned_items: Vec<Spanned<MentionedItem<'tcx>>>,
```

Fixes #107503

### CODE REVIEW

**Comment by RalfJung** [comment]
Okay so this should hopefully codegen nothing more than what was already codegen'd before this PR... only the collector and MIR passes are doing more work.

@bors try @rust-timer queue

File: compiler/rustc_middle/src/mir/mod.rs [hunk 1]
```diff
@@ -375,8 +386,18 @@ pub struct Body<'tcx> {
 
     /// Constants that are required to evaluate successfully for this MIR to be well-formed.
     /// We hold in this field all the constants we are not able to evaluate yet.
+    ///
+    /// This is soundness-critical, we make a guarantee that all consts syntactically mentioned in a
+    /// function have successfully evaluated if the function ever gets xecuted at runtime.
```
Comment (Dante-Broggi) [inline compiler/rustc_middle/src/mir/mod.rs:391]:
```suggestion
    /// function have successfully evaluated if the function ever gets executed at runtime.
```

**Comment by RalfJung** [comment]
Well that looks a lot better. :) And almost all regressions are for "incr". That makes sense, as collection is re-done when anything changes (right?) so making collection a bit slower would be a much bigger absolute change when the build is fast due to being mostly cached.

**Comment by RalfJung** [comment]
I've added an optimization that should help with the common case of "most 'mentioned items' are also still used". Let's see if that makes a difference.

@bors try @rust-timer queue

**Comment by RalfJung** [comment]
I think this is basically ready.
r? @oli-obk 

If we compare the latest perf run with [this one](https://perf.rust-lang.org/compare.html?start=25ee3c6a2f429a97ff4ad239e3f42409cd71fe0a&end=f39ef07cd6826cdd5ceaecb265b71d0898f50b8f&stat=instructions:u) where all we did was populate the "mentions items" list (but entirely ignore it in the collector), we can see that most of the regression is from having that list in the first place. My guess is that most of the cost is from serializing and deserializing the list to/from disk. There's not a ton we can do here:
- We could remove the `Span` to make the data smaller... but that earlier benchmark measuring only the overhead of having the "mentions items" list did not have spans, so we'll not get less than 2% for the worst-affected benchmarks.
- We could try to be clever and put fewer things in the list. Note that even in debug builds, we run with mir-opt-level 1, so if we wanted to skip  the list for debug builds we'd have to be sure that no optimization will ever remove an unused item in mir-opt-level 1. I would not be surprised if one day we wanted to optimize `is false` even in debug builds, so this does not seem like a good strategy. (Also we'd then make the mentioned item phase in the collector more expensive as we'd have to walk the fully body rather than just the mentioned-items-list to keep recursing. Currently the collector implicitly assumes that mentioned-items is always populated.)

  @oli-obk tried having `should_codegen_locally` logic around during mentioned-items list building. However we can't use the logic from the collector as mentioned-items list building happens pre-monomorphization. I'll do one last perf experiment to see if that would help here.

File: compiler/rustc_monomorphize/src/collector.rs [hunk 2]
```diff
@@ -199,7 +219,7 @@ use crate::errors::{
 };
 
 #[derive(PartialEq)]
-pub enum MonoItemCollectionMode {
+pub enum MonoItemCollectionStrategy {
```
Comment (RalfJung) [inline compiler/rustc_monomorphize/src/collector.rs:222]: I renamed this to "strategy" since we now also have the `CollectionMode` (used vs mentioned) and I could not come up with a better name for the new enum.

**Comment by RalfJung** [comment]
That looks basically the same, and the code is more complex, so my inclination would be to remove the `may_codegen_locally` check again. @oli-obk please let me know what you think.

**Comment by RalfJung** [comment]
Yeah so that's obviously a lot worse.^^

**Comment by RalfJung** [comment]
Regarding https://github.com/rust-lang/rust/pull/122568/commits/e27a7be5391b43d0a7ffe27baefcfd13bece745c, so the difference in the mean of the perf regression with and without that commit is 0.04%, with the commit overall making it slightly faster but also increasing the variance in the results. I'm going to take the commit out again for now.

**Comment by RalfJung** [comment]
> If it is not changing the performance, it may be worthwhile to just visit all types.

All right, let's try that.
@bors try @rust-timer queue

File: compiler/rustc_mir_transform/src/mentioned_items.rs [hunk 3]
```diff
@@ -0,0 +1,97 @@
...
+        body.mentioned_items = mentioned_items;
+    }
+}
+
+impl<'tcx> Visitor<'tcx> for MentionedItemsVisitor<'_, 'tcx> {
+    fn visit_constant(&mut self, constant: &ConstOperand<'tcx>, _: Location) {
+        let const_ = constant.const_;
+        // This is how function items get referenced: via constants of `FnDef` type. This handles
+        // both functions that are called and those that are just turned to function pointers.
+        if let ty::FnDef(def_id, args) = const_.ty().kind() {
```
[the remark this answers is not in the document]
Comment (RalfJung) [reply compiler/rustc_mir_transform/src/mentioned_items.rs]: > Wrt opaque types, I just realized that we may in fact need to normalize all types and then walk them to find all function types inside:

I added a testcase for that, it seems to already be handled correctly without doing further normalization in `mentioned_items`. (But it does not get handled correctly without this PR.)

File: tests/ui/consts/required-consts/collect-in-dead-fn.rs [hunk 4]
```diff
@@ -1,15 +1,11 @@
 //@revisions: noopt opt
-//@[noopt] build-fail
+//@ build-fail
 //@[opt] compile-flags: -O
```
Comment (the8472) [inline tests/ui/consts/required-consts/collect-in-dead-fn.rs:3]: The way that compiletest calculates the opt level for tests depends on several factors (`optimize-tests` setting, whether it's a build/fail/run test).
I think it's better to be explicitly and set `-Copt-level=0` for noopt tests to override heuristics.

Comment (RalfJung) [reply tests/ui/consts/required-consts/collect-in-dead-fn.rs:3]: Uff, okay I thought the opt level defaults to 0. I don't think the test suite will pass with other settings -- they are clearly not covered by CI so they will ~never work.

So I think we should remove such settings and heuristics, they are fragile and cause undue maintenance costs.

**Comment by RalfJung** [comment]
Okay that's still basically the same as before... primary tests got a tiny bit slower (+0.37% -> +0.39%), secondary tests a tiny bit faster, so probably all noise.

I could imagine though that if we do normalization that will make things a lot slower. So I hope we don't have to do that. And given that the new test case already passes maybe we don't? Maybe something normalizes the entire MIR body before it reaches this pass? There is a `RevealAll` pass in `run_runtime_lowering_passes`, which is before this one.

**Comment by oli-obk** [comment]
> There is a `RevealAll` pass in `run_runtime_lowering_passes`, which is before this one.

Yea that'll do it.

I think this covers everything, as any way to hide the opaque further just means it's in a struct field or sth and never gets called, turned into a fn ptr, or gets unsized. If a zst fn handle never gets called, we don't care about nested consts, right?

**Comment by RalfJung** [comment]
> I think this covers everything, as any way to hide the opaque further just means it's in a struct field or sth and never gets called, turned into a fn ptr, or gets unsized. If a zst fn handle never gets called, we don't care about nested consts, right?

The only constraint here is for behavior to be the same with and without optimizations. So the question is, will the collector consider them? As far as I can tell the collector only considers calls and casts, it doesn't have a `visit_ty`.

However I did try to add an assertion to `mentioned_items` to ensure that we never see an `AliasKind::Opaque`, and that triggers an ICE while building the standard library. So it's a bit hard for me to say whether we can be sure that all `FnDef` have become visible at this point.

But I wasn't able to write a testcase where a `FnDef` would be completely hidden pre-monomorphization and only show up during monomorphization. After all it has to come from somewhere... but then `visit_ty` does not traverse into the structure of the type, so as you say something with hiding the `FnDef` in a field and then projecting it out in a generic function that doesn't see the `FnDef` but preserves the `impl FnOnce()`...

I feel like it must be possible to bypass this somehow, but so far I have not managed. Even this test passes:
```rust
#![feature(impl_trait_in_assoc_type)]
//@revisions: noopt opt
//@ build-fail
//@[opt] compile-flags: -O
//! This fails without optimizations, so it should also fail with optimizations.

struct Fail<T>(T);
impl<T> Fail<T> {
    const C: () = panic!(); //~ERROR evaluation of `Fail::<i32>::C` failed
}

fn not_called<T>() {
    if false {
        let _ = Fail::<T>::C;
    }
}

fn callit_not(f: impl FnOnce()) {
    if false {
        f();
    }
}

trait Hideaway {
    type T: FnOnce();
    const C: Self::T;
}
impl Hideaway for () {
    type T = impl FnOnce();
    const C: Self::T = not_called::<i32>;
}

fn reveal<T: Hideaway>() {
    if false {
        callit_not(T::C);
    }
}

fn main() {
    if false {
        reveal::<()>()
    }
}
```
But even that works. I don't even know why. I would have thought `callit_not` gets an empty `mentioned_items` and then the chain stops there...

But I feel like it may be necessary to preserve all types used in function calls and these coercions, because that's what the collector actually cares about. Having mentioned_items use different parts of the MIR than the collector risks them getting out-of-sync. `MentionedItem::Fn` should actually just be a `Ty` so that it can be generic, and then *after* monomorphization we can extract the `FnDef` and traverse it. I just wish I had a testcase to confirm this...

**Comment by RalfJung** [comment]
Ah, I think I got one. Strangely `impl FnOnce` gives rise to some `FnPtrShim` that is enough to make it work, but this test case still shows no error with optimizations (and one error without):
```rust
#![feature(impl_trait_in_assoc_type)]
//@revisions: noopt opt
//@ build-fail
//@[opt] compile-flags: -O
//! This fails without optimizations, so it should also fail with optimizations.

struct Fail<T>(T);
impl<T> Fail<T> {
    const C: () = panic!(); //~ERROR evaluation of `Fail::<i32>::C` failed
}

fn not_called<T>() {
    if false {
        let _ = Fail::<T>::C;
    }
}

fn callit_not(f: impl Fn()) {
    if false {
        f();
    }
}

trait Hideaway {
    type T: Fn();
    const C: Self::T;
}
impl Hideaway for () {
    type T = impl Fn();
    const C: Self::T = not_called::<i32>;
}

fn reveal<T: Hideaway>() {
    if false {
        callit_not(T::C);
    }
}

fn main() {
    if false {
        reveal::<()>()
    }
}
```

**Comment by RalfJung** [comment]
> Having mentioned_items use different parts of the MIR than the collector risks them getting out-of-sync.

I fixed that now, they use the same MIR syntax locations to find functions. We also no longer rely on seeing `FnDef` there: we always record the type, monomorphize, and *then* check for `FnDef`. That fixes the latest testcase.

The visitors in `collector` and `mentioned_items` are becoming extremely similar now... there's probable some way to make this super abstract and share the code. Though the collector has this "big move" lint mixed up with the traversal logic which is quite annoying... IMO adding that into `collector.rs` should never have been accepted. :/

@bors try @rust-timer queue

File: tests/ui/consts/required-consts/collect-in-dead-fn.rs (hunk 4 above)
Comment (the8472) [reply tests/ui/consts/required-consts/collect-in-dead-fn.rs:3]: In merge-CI the testsuite is run with `optimize-tests` true and false at least but for UI tests that only affects run tests, not build tests I think.

Anyway, if the test is trying to cover specific optimization levels it should be part of the test configuration. Things accidentally depending on defaults of options has caused problems in the past when the defaults changed. E.g. tests testing CGU-dependent things failing with 1CGU.

The majority of UI tests aren't trying to test things that depend on specific compiler options.

**Comment by RalfJung** [comment]
Okay that's actually faster, probably due to [this commit](https://github.com/rust-lang/rust/commit/de0feb36e8c6721184eacca864e7eef32afb472f) which fixes an oopsie in the `used_mentioned_items` optimization.

I haven't systematically added that optimization for *all* `MentionedItem` sources, only for the most common ones (function calls and drops). I guess I should add it for all of them.

**Comment by RalfJung** [comment]
Turns out new optimization-dependent behavior has been [added recently with the cross-crate inlining heuristic](https://github.com/rust-lang/rust/issues/107503#issuecomment-2008088416). This PR doesn't fix that. But the change to fix that will likely have to build on this PR so I think we can still land this first.

**Comment by traviscross** [comment]
@rustbot labels +T-lang +I-lang-nominated

We had a proposed FCP on #112879 that never actually completed due to the concern filed over the performance regression.  Let's nominate this in its place to see how we want to handle that decision.

**Comment by RalfJung** [comment]
Hm, given that this is implementing an explicit T-lang feature request that came up during the inline const stabilization FCP more than a year ago, I didn't expect it'd need to be FCP'd again... but sure.

File: compiler/rustc_mir_transform/src/mentioned_items.rs [hunk 5]
```diff
@@ -0,0 +1,110 @@
...
+// visiting the exact same places but then instead of monomorphizing and creating `MonoItems`, we
+// have to remain generic and just recording the relevant information in `mentioned_items`, where it
+// will then be monomorphized later during "mentioned items" collection.
+impl<'tcx> Visitor<'tcx> for MentionedItemsVisitor<'_, 'tcx> {
+    fn visit_terminator(&mut self, terminator: &mir::Terminator<'tcx>, location: Location) {
+        self.super_terminator(terminator, location);
+        let span = || self.body.source_info(location).span;
+        match &terminator.kind {
+            mir::TerminatorKind::Call { func, .. } => {
+                let callee_ty = func.ty(self.body, self.tcx);
```
[the remark this answers is not in the document]
Comment (RalfJung) [reply compiler/rustc_mir_transform/src/mentioned_items.rs:42]: Yeah, I know. But is it worth it? Function pointer calls are very rare, it's not going to show up in perf.

File: compiler/rustc_mir_transform/src/mentioned_items.rs [hunk 6]
```diff
@@ -0,0 +1,110 @@
...
+        match *rvalue {
+            // We need to detect unsizing casts that required vtables.
+            mir::Rvalue::Cast(
+                mir::CastKind::PointerCoercion(PointerCoercion::Unsize),
+                ref operand,
+                target_ty,
+            )
+            | mir::Rvalue::Cast(mir::CastKind::DynStar, ref operand, target_ty) => {
+                // This isn't monomorphized yet so we can't tell what the actual types are -- just
+                // add everything.
```
[the remark this answers is not in the document]
Comment (RalfJung) [reply compiler/rustc_mir_transform/src/mentioned_items.rs:79]: That would basically only be array-to-`str`/slice unsizing, right? The moment ADTs are involved, the ADT tail may be a dyn trait. We could compute the tail to figure that out but IMO it's not worth it, such casts aren't common enough to make a dent in the profiles.

**Review by oli-obk — APPROVED** [review]

File: compiler/rustc_monomorphize/src/collector.rs [hunk 7]
```diff
@@ -753,8 +924,11 @@ impl<'a, 'tcx> MirVisitor<'tcx> for MirUsedCollector<'a, 'tcx> {
                 target_ty,
             )
             | mir::Rvalue::Cast(mir::CastKind::DynStar, ref operand, target_ty) => {
-                let target_ty = self.monomorphize(target_ty);
                 let source_ty = operand.ty(self.body, self.tcx);
+                // *Before* monomorphizing, record that we already handled this mention.
+                self.used_mentioned_items
+                    .insert(MentionedItem::UnsizeCast { source_ty, target_ty });
```
Comment (RalfJung) [inline compiler/rustc_monomorphize/src/collector.rs:930]: I haven't added the str/slice filter here. It's annoying to duplicate that code, and while mentioned_items get serialized into metadata, here it's entirely local to the already pretty expensive collection pass so it doesn't seem worth it. The `used_mentioned_items` optimization is effective as long as at least all the mentioned items are added to the set; it's okay if there are a few more.

Comment (oli-obk) [reply compiler/rustc_monomorphize/src/collector.rs:930]: yea I think it's fine

File: compiler/rustc_monomorphize/src/collector.rs [hunk 8]
```diff
@@ -1612,31 +1635,54 @@ impl<'v> RootCollector<'_, 'v> {
...
+                        .flags
+                        .contains(CodegenFnAttrFlags::RUSTC_STD_INTERNAL_SYMBOL)
             }
+        };
+        if is_used_root {
+            return Some(CollectionMode::UsedItems);
+        }
+        // We have to skip `must_be_overridden` bodies; asking for their "mentioned" items
+        // leads to ICEs.
+        if self.tcx.intrinsic(def_id).is_some_and(|i| i.must_be_overridden) {
```
Comment (RalfJung) [inline compiler/rustc_monomorphize/src/collector.rs:1666]: I think it should be safe to move this check further up this function, but just in case that query has a measurable cost I wanted to keep the codepath for regular roots the same as before. That said I think there may be latent ICEs hiding here; if a must_be_overridden-intrinsic ever makes it into the root set we'll be in trouble. Or maybe that is prevented elsewhere already? What if I mark it as the entry fn or a "RUSTC_STD_INTERNAL_SYMBOL"? :joy:

File: tests/ui/consts/required-consts/collect-roots-dead-fn.rs
Comment (RalfJung) [inline tests/ui/consts/required-consts/collect-roots-dead-fn.rs:1]: I currently have no theory for why previously this file built successfully without optimizations (and failed with optimizations), even with all the other "mentioned items" stuff in place. I hope @tmiasko will be able to explain. :)

**Comment by RalfJung** [comment]
Uff, incremental tests are unhappy with asking more items for their MIR it seems. No idea how these tests even work.^^

**Comment by RalfJung** [comment]
I can fix those incremental tests by making the functions generic, just adding a dummy `T` parameter. But I doubt that's the intention here.^^ I'll likely take that commit out of the PR once we have timing data. I hope an incremental expert can then eventually help land that.

**Comment by oli-obk** [comment]
The way to adjust incremental tests is to add `optimized_mir` to the `except` list in the `rustc_clean` attribute. It's ok to change incremental tests if the change can be explained

**Comment by RalfJung** [comment]
Looks like we do have a bunch of dead code in the benchmark crates... but the biggest impact is still on incr benchmarks. For full builds, there's [only a few regressions](https://perf.rust-lang.org/compare.html?start=0f706af330022b46efb5bcc8da7ad7276dfdeb69&end=80f337fff62c71cbd8f5030e0218ac7086a057af&stat=instructions%3Au&incrFull=false&incrUnchanged=false&incrPatched=false). Further optimization may be possible as indicated above.

But maybe it's better to split this up in a separate PR? There's always a chance of regressions and usually smaller changes are better. Also I wouldn't mind to get this landed and maybe have someone else take over, other things are keeping me quite busy. :shrug: 

@oli-obk how do you want to proceed? Land without the last commit, or try to get the last commit to work and maybe do further optimizations?

**Comment by traviscross** [comment]
@rustbot labels -I-lang-nominated

As **scottmcm** mentioned, this is good to go forward as far as lang is concerned, so let's unnominate.

File: tests/ui/consts/required-consts/collect-roots-dead-fn.rs
Comment (RalfJung) [reply tests/ui/consts/required-consts/collect-roots-dead-fn.rs:1]: Ah I think I have an explanation...

In both optimized and unoptimized builds, the call to `g` gets optimized away pretty early, before we build "mentioned_items". (Specifically it's the first `SimplifyCfg` that does this.)

In unoptimized builds, only `f` is reachable,  and `f` does not use nor mention anything else, so we're done.

In optimized builds, `f` gets marked as ready for inlining, so `g` enters the reachability set and the collector roots, and so we do end up considering `h` to be used and its constants get evaluated.

Only non-generic functions can be collector roots, so by considering all non-generic functions to be collector roots we do properly fix this -- at some cost for incremental builds. I think incremental builds show up in this PR because you need a lot of items to make these new iterations matter, and for full builds the cost drowns in the time it takes to process all those items -- but incremental builds are fast even for many items, so increasing the per-item cost by a small constant becomes much more noticeable.

Comment (RalfJung) [reply tests/ui/consts/required-consts/collect-roots-dead-fn.rs:1]: That also points at a different way of fixing this: building `mentioned_items` earlier so that it includes `g`. However, that will also cost a lot of performance since it means we are treating more code as "mentioned"...

Maybe we can make SimplifyCfg (at least the early passes up until we build the "mentioned" list) not remove unreachable blocks? That would also fix this issue. Or... maybe not, I haven't fully thought through the consequences for `Drop` calls.

**Comment by oli-obk** [comment]
> Land without the last commit, or try to get the last commit to work and maybe do further optimizations?

unless I'm reading the perf runs wrong, the latest commits actually cause more regressions?

I'm fine landing simpler code, and then trying to optimize in new PRs instead

File: compiler/rustc_monomorphize/src/collector.rs
Comment (oli-obk) [inline compiler/rustc_monomorphize/src/collector.rs:1]: when doing such large code moves, we may as well create new modules to separate some parts entirely

Comment (RalfJung) [reply compiler/rustc_monomorphize/src/collector.rs:1]: The root part does call some of the collector functions though...

**Comment by RalfJung** [comment]
> unless I'm reading the perf runs wrong, the latest commits actually cause more regressions?

Yes. They fix optimization-dependent behavior caused by different root sets, but ofc that means doing more work and so things get slower. T-lang is not sure yet whether they want to consider that a blocker of inline consts or not.

I will remove that commit. (For future reference, that's a303df006a5be15f799fdb9f987ac083f8de191d.)

**Comment by RalfJung** [comment]
I added some missing `inline(never)` to the new tests, just to make sure they test what they are supposed to test.

@bors r=oli-obk

**Comment by RalfJung** [comment]
These are expected, we are doing more work -- because were were previously skipping work that shouldn't have been skipped. Regressions affect almost exclusively incr benchmarks, where collector changes show up disproportionally -- there are still tons of items but all the queries are already cached, so there's little work per item outside the collector. A large fraction of the regression is from just reading and writing the list of "mentioned items" for each MIR body.

@rustbot label: +perf-regression-triaged

**Comment by therealprof** [comment]
> These are expected, we are doing more work -- because we were previously skipping work that shouldn't have been skipped. Regressions affect almost exclusively incr benchmarks, where collector changes show up disproportionally -- there are still tons of items but all the queries are already cached, so there's little work per item outside the collector. A large fraction of the regression is from just reading and writing the list of "mentioned items" for each MIR body.

Okay, the compiler is doing more work, fine. But why the massive regression in binary size?

**Comment by RalfJung** [comment]
Eh, no idea. rlib files would get a bit bigger since they are now storing the "mentioned items" list. What kind of artifact is measured here, does it include Rust metadata?

We should be sending the exact same stuff to codegen as before. (And we'd see a perf regression if we did more codegen.)

**Comment by Kobzol** [comment]
This is all metadata (see https://perf.rust-lang.org/compare.html?start=47dd709bedda8127e8daec33327e0a9d0cdae845&end=df8ac8f1d74cffb96a93ae702d16e224f5b9ee8c&stat=size%3Acrate_metadata). If you uncheck libraries in the binary size metric, there are no changes ("binary size" for libraries is the size of the .rlib, including metadata).

That being said, even regressions in metadata size are unfortunate, especially of such magnitude (not sure if they can be avoided here though).

**Comment by RalfJung** [comment]
Yeah I think it's the "mentioned items". [This here](https://perf.rust-lang.org/compare.html?start=25ee3c6a2f429a97ff4ad239e3f42409cd71fe0a&end=f39ef07cd6826cdd5ceaecb265b71d0898f50b8f&stat=size:linked_artifact) is a benchmark from early development of this patch when all I did was add the "mentioned items" list, but not do anything with it. That's actually a bigger regression, I later did some changes that made the list shorter.

> That being said, even regressions in metadata size are unfortunate, especially of such magnitude (not sure if they can be avoided here though).

We could strip the `Span`, which would save some space I guess? Or we could 'intern' function items in MIR so that we don't have to repeat them (once in the actual code and once in "mentioned items"), and instead referencing some index into a function item table or so -- but that would be a pretty drastic change.

**Comment by RalfJung** [comment]
How does something like `Ty<'tcx>` even get represented on-disk? Does it repeat the entire type? I guess that makes this much less efficient than in-memory where they get deduplicated.

The rlib format could store all types in a table and then just index that table. But again, that's a big change.

**Comment by the8472** [comment]
Note that #122785 already recovered some of the lib sizes - I was wondering why sizes were down. [perf link](https://perf.rust-lang.org/compare.html?start=a0569fa8f91b5271e92d2f73fd252de7d3d05b9c&end=0ad927c0c07b65fc0dae37105e09c877c87c296a&stat=size%3Alinked_artifact&tab=compile)

If those mentioned items weren't previously included in the rlibs does that mean they're also dead code? Maybe we can find a few more places where that trick can be applied.

**Comment by RalfJung** [comment]
Even for live code we're now duplicating information. If a MIR body calls 100 functions, then it has 100 basic blocks for these calls, and 100 "mentioned items" with the types of the callees.

**Comment by RalfJung** [comment]
I have opened an issue for this: https://github.com/rust-lang/rust/issues/122936.

If we can make the on-disk representation of "mentioned items" smaller, that would also fix a significant part of the perf regression here. I just don't know if it can be done.
