### PR TITLE
Rustdoc: resolve associated traits for non-generic primitive types

### LINKED ISSUE #90703: rustdoc: cannot resolve links to associated trait items for primitives
I tried this code:

```rust
use std::{num::ParseFloatError, str::FromStr};

/// Uses the rules from [`f64::from_str()`].
pub struct Number {
    pub value: f64,
}

impl FromStr for Number {
    type Err = ParseFloatError;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        let value = s.parse::<f64>()?;
        Ok(Self{value})
    }
}
```

I expected to see this happen: the `[f64::from_str()]` in the docstring links to https://doc.rust-lang.org/1.56.0/std/primitive.f64.html#method.from_str

Instead, this happened:

```
cargo doc
 Documenting cayenne v0.1.0 (/home/abi/projects/classabbyamp/rspice)
warning: unresolved link to `f64::from_str`
 --> src/v.rs:3:27
  |
3 | /// Uses the rules from [`f64::from_str()`].
  |                           ^^^^^^^^^^^^^^^ the builtin type `f64` has no function named `from_str`
  |
  = note: `#[warn(rustdoc::broken_intra_doc_links)]` on by default

warning: `cayenne` (lib doc) generated 1 warning
    Finished dev [unoptimized + debuginfo] target(s) in 0.34s
```

This does not happen for `[f64::floor()]` nor for linking to a non-primitive `FromStr` implmentation, like `[Number::from_str()]` (in the example above).

@jyn514 suggested that [`resolve_primitive_associated_item()`](https://github.com/rust-lang/rust/blob/495322d776fd6f679cd8cd4ca02b8fa834da654b/src/librustdoc/passes/collect_intra_doc_links.rs#L366) may be only looking at inherent impls and not trait impls, and that it may need a call to [`resolve_associated_trait_item()`](https://github.com/rust-lang/rust/blob/495322d776fd6f679cd8cd4ca02b8fa834da654b/src/librustdoc/passes/collect_intra_doc_links.rs#L729).

### Meta

`rustc --version --verbose`:
```
rustc 1.56.0 (09c42c458 2021-10-18)
binary: rustc
commit-hash: 09c42c45858d5f3aedfa670698275303a3d19afa
commit-date: 2021-10-18
host: x86_64-unknown-linux-gnu
release: 1.56.0
LLVM version: 13.0.0
```
Reproduced on beta:
```
rustc 1.57.0-beta.3 (708d57e28 2021-11-01)
binary: rustc
commit-hash: 708d57e288d051a6238ed56039ffeac158e10e84
commit-date: 2021-11-01
host: x86_64-unknown-linux-gnu
release: 1.57.0-beta.3
LLVM version: 13.0.0
```
and nightly:
```
rustc 1.58.0-nightly (46b8e7488 2021-11-07)
binary: rustc
commit-hash: 46b8e7488eae116722196e8390c1bd2ea2e396cf
commit-date: 2021-11-07
host: x86_64-unknown-linux-gnu
release: 1.58.0-nightly
LLVM version: 13.0.0
```

<details><summary>Backtrace</summary>
<p>

`RUSTC_BOOTSTRAP=1 RUSTDOC_LOG=rustdoc::passes::collect_intra_doc_links=debug cargo rustdoc -- -Dwarnings -Ztreat-err-as-bug`:

```
 Documenting cayenne v0.1.0 (/home/classabbyamp/projects/cayenne)
warning: some trace filter directives would enable traces that are disabled statically
 | `rustdoc::passes::collect_intra_doc_links=debug` would enable the DEBUG level for the `rustdoc::passes::collect_intra_doc_links` target
 = note: the static max level is `info`
 = help: to enable DEBUG logging, remove the `max_level_info` feature
DEBUG rustdoc::passes::collect_intra_doc_links::early doc=" Uses the rules from [`f64::from_str()`]."
DEBUG rustdoc::passes::collect_intra_doc_links::early link.link="`f64::from_str()`"
DEBUG rustdoc::passes::collect_intra_doc_links looking for the `Self` type
DEBUG rustdoc::passes::collect_intra_doc_links using item_name(): Some("cayenne")
DEBUG rustdoc::passes::collect_intra_doc_links looking for the `Self` type
DEBUG rustdoc::passes::collect_intra_doc_links using item_name(): Some("v")
DEBUG rustdoc::passes::collect_intra_doc_links looking for the `Self` type
DEBUG rustdoc::passes::collect_intra_doc_links using item_name(): Some("Number")
DEBUG rustdoc::passes::collect_intra_doc_links combined_docs=Uses the rules from [`f64::from_str()`].
DEBUG rustdoc::passes::collect_intra_doc_links f64::from_str resolved to Err(()) in namespace ValueNS
DEBUG rustdoc::passes::collect_intra_doc_links resolved primitives F64
DEBUG rustdoc::passes::collect_intra_doc_links looking for enum variant f64::from_str
DEBUG rustdoc::passes::collect_intra_doc_links f64::from_str resolved to Err(()) in namespace TypeNS
DEBUG rustdoc::passes::collect_intra_doc_links resolved primitives F64
DEBUG rustdoc::passes::collect_intra_doc_links resolving f64::from_str as a macro in the module DefId(0:3 ~ cayenne[f5be]::v)
DEBUG rustdoc::passes::collect_intra_doc_links f64 resolved to Ok(Primitive(F64)) in namespace TypeNS
DEBUG rustdoc::passes::collect_intra_doc_links found partial_res=Primitive(F64)
error: unresolved link to `f64::from_str`
 --> src/v.rs:3:27
  |
3 | /// Uses the rules from [`f64::from_str()`].
  |                           ^^^^^^^^^^^^^^^ the builtin type `f64` has no function named `from_str`
  |
  = note: `-D rustdoc::broken-intra-doc-links` implied by `-D warnings`

thread 'rustc' panicked at 'aborting due to `-Z treat-err-as-bug=1`', compiler/rustc_errors/src/lib.rs:1182:27
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

error: Unrecognized option: 'crate-version'

error: could not document `cayenne`

Caused by:
  process didn't exit successfully: `rustdoc --edition=2021 --crate-type lib --crate-name cayenne src/lib.rs -o /home/classabbyamp/projects/cayenne/target/doc --error-format=json --json=diagnostic-rendered-ansi -Dwarnings -Ztreat-err-as-bug -L dependency=/home/classabbyamp/projects/cayenne/target/debug/deps --crate-version 0.1.0` (exit status: 1)
```

</p>
</details>

### PR DESCRIPTION
**Pull request by mdibaiee**
Fixes #90703

This seems to work:
image

I'm just afraid I might have missed some cases / broken previous functionality.

I also have not written tests yet, I will have to take a look to see where tests are and how they are structured, but any help there is also appreciated.

### CODE REVIEW

File: src/librustdoc/passes/collect_intra_doc_links.rs [hunk 1]
```diff
@@ -618,6 +618,44 @@ impl<'a, 'tcx> LinkCollector<'a, 'tcx> {
...
+            U128 => ty::Uint(ty::UintTy::U128),
+            Usize => ty::Uint(ty::UintTy::Usize),
+            //ty::Tuple(tys) if tys.is_empty() => Res::Primitive(Unit),
+            //ty::Tuple(_) => Res::Primitive(Tuple),
+            //ty::Array(..) => Res::Primitive(Array),
+            //ty::Slice(_) => Res::Primitive(Slice),
+            //ty::RawPtr(_) => Res::Primitive(RawPointer),
+            //ty::Ref(..) => Res::Primitive(Reference),
+            //ty::FnDef(..) => panic!("type alias to a function definition"),
+            //ty::FnPtr(_) => Res::Primitive(Fn),
```
Comment (mdibaiee) [inline src/librustdoc/passes/collect_intra_doc_links.rs:654]: So these commented out lines can't be converted, if I understand correctly. The `PrimitiveType` enum does not have any parameters for these types, whereas the `ty` counterpart requires more information.

Let me know if I'm mistaken here and if so, any guidance on how to convert them would be appreciated. Otherwise, I'll just delete these comments.

```suggestion
```

File: src/librustdoc/passes/collect_intra_doc_links.rs [hunk 2]
```diff
@@ -666,8 +722,13 @@ impl<'a, 'tcx> LinkCollector<'a, 'tcx> {
                     // To handle that properly resolve() would have to support
                     // something like [`ambi_fn`](<SomeStruct as SomeTrait>::ambi_fn)
                     .or_else(|| {
-                        let item =
-                            resolve_associated_trait_item(did, module_id, item_name, ns, self.cx);
+                        let item = resolve_associated_trait_item(
+                            tcx.type_of(did),
```
Comment (mdibaiee) [inline src/librustdoc/passes/collect_intra_doc_links.rs:726]: Is this a reliable call? (e.g. can we be sure that it doesn't panic for the possible input values here)

File: src/librustdoc/passes/collect_intra_doc_links.rs [hunk 3]
```diff
@@ -826,19 +890,10 @@ fn traits_implemented_by(cx: &mut DocContext<'_>, type_: DefId, module: DefId) -
...
-                || match impl_type.kind() {
-                    // Check if these are the same def_id
-                    ty::Adt(def, _) => {
-                        debug!("adt def_id: {:?}", def.did);
-                        def.did == type_
-                    }
-                    ty::Foreign(def_id) => *def_id == type_,
-                    _ => false,
-                };
+            let saw_impl = impl_type == ty;
```
Comment (mdibaiee) [inline src/librustdoc/passes/collect_intra_doc_links.rs:896]: My understanding is that the `match` that was here before is not necessary, since `ty::Adt`'s `eq` implementation does basically compare the `did`:

https://doc.rust-lang.org/nightly/nightly-rustc/src/rustc_middle/ty/adt.rs.html#120-122

Similarly for `Foreign`, it will just compare the `def_id` inside.

File: src/librustdoc/passes/collect_intra_doc_links.rs [hunk 4]
```diff
@@ -2383,3 +2438,18 @@ fn strip_generics_from_path_segment(
...
+}
+
+impl FromStr for Number {
+    type Err = ParseFloatError;
+
+    fn from_str(s: &str) -> Result<Self, Self::Err> {
+        let value = s.parse::<f64>()?;
+        Ok(Self { value })
+    }
+}
```
Comment (mdibaiee) [inline src/librustdoc/passes/collect_intra_doc_links.rs:2455]: I just left here so the example from the issue can be tested by building the docs for this module:

```
./x.py doc --open src/librustdoc
```

Will remove once we are finished with the feedback/review.
```suggestion
```

**Comment by mdibaiee** [comment]
> The job **`x86_64-gnu-llvm-12`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/runs/4668505475?check_suite_focus=true) [(plain)](https://github.com/rust-lang/rust/commit/61bc75471c4607ae5ea7fd1bad1f6b6cec717b68/checks/4668505475/logs)
> Click to see the possible cause of the failure (guessed by this bot)

If I understand this correctly, we have tests that confirm that associated items on primitive types don't work, and because now they work as part of this PR, this test is failing. I suppose I can delete these tests and instead write tests for them working?

File: src/librustdoc/passes/collect_intra_doc_links.rs (hunk 1 above)
Comment (camelid) [reply src/librustdoc/passes/collect_intra_doc_links.rs:654]: You could maybe instantiate the types with fresh generic parameters? Not sure how though.

File: src/librustdoc/passes/collect_intra_doc_links.rs (hunk 3 above)
Comment (camelid) [reply src/librustdoc/passes/collect_intra_doc_links.rs:896]: Can you move this change into its own PR?

File: src/librustdoc/passes/collect_intra_doc_links.rs (hunk 4 above)
Comment (camelid) [reply src/librustdoc/passes/collect_intra_doc_links.rs:2455]: Please remove it now and make it a test in `src/test/rustdoc/intra-doc`.

You can see how it looks with `./x.py build rustdoc` and then [`rustdoc +stage2 path/to/test.rs`](https://rustc-dev-guide.rust-lang.org/rustdoc.html#cheat-sheet).

File: src/librustdoc/passes/collect_intra_doc_links.rs (hunk 3 above)
Comment (mdibaiee) [reply src/librustdoc/passes/collect_intra_doc_links.rs:896]: @camelid this is necessary to make this function work with a `ty` input, the `match` is only useful if the function accepts DefId. I don't understand how it can be its own PR.

Comment (camelid) [reply src/librustdoc/passes/collect_intra_doc_links.rs:896]: I'm not sure why it's necessary; the `match` doesn't seem to use the function's DefId parameter.

But either way, I meant can you open another that makes just this change, which this PR can then be rebased upon once the new one is merged? It seems like a cleanup that should be made independently of this feature PR.

File: src/test/rustdoc/intra-doc/prim-associated-traits.rs [hunk 5]
```diff
@@ -0,0 +1,6 @@
+use std::{num::ParseFloatError, str::FromStr};
+
+/// Uses the rules from [`f64::from_str()`].
```
Comment (camelid) [inline src/test/rustdoc/intra-doc/prim-associated-traits.rs:3]: This test doesn't do much without a check like this:

```suggestion
// @has 'doc/prim_associated_traits/struct.Number.html' '//a[@href="https://doc.rust-lang.org/nightly/std/primitive.f64.html#method.from_str"]' 'f64::from_str()'
/// Uses the rules from [`f64::from_str()`].
```

File: src/librustdoc/passes/collect_intra_doc_links.rs (hunk 3 above)
Comment (mdibaiee) [reply src/librustdoc/passes/collect_intra_doc_links.rs:896]: The match is there because we are trying to see if the `ty` that we have found is equal to the `DefId` that we have, hence we have a match that is like this:

```
match impl_type.kind() {
                    // Check if these are the same def_id
                    ty::Adt(def, _) => {
                        debug!("adt def_id: {:?}", def.did);
                        def.did == type_
                    }
                    ty::Foreign(def_id) => *def_id == type_,
                    _ => false,
                };
```

The `type_` here is the `DefId` we receive in the arguments of the function, however since I have removed that `DefId` and turned it into a `ty`, and `ty` handles these cases of `Foreign` and `Adt` properly, a simple `==` is enough here.

Comment (mdibaiee) [reply src/librustdoc/passes/collect_intra_doc_links.rs:896]: Now, I'm not sure if the `tcx.type_of` previously used to get a `ty` instance out of the `type_ : DefId` (`let ty = tcx.type_of(type_);`) would achieve the same thing: is that `ty` also fully informative so that the equal sign is enough? Perhaps... in that case we can have a separate PR, but I'm not sure if that's the case.

File: src/librustdoc/passes/collect_intra_doc_links.rs (hunk 1 above)
Comment (mdibaiee) [reply src/librustdoc/passes/collect_intra_doc_links.rs:654]: I think I would need actual information, e.g. for [`ty::Array`](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_middle/ty/enum.TyKind.html#variant.Array) we have:

```
Array(Ty<'tcx>, &'tcx Const<'tcx>)
Tuple Fields
0: Ty<'tcx>
1: &'tcx Const<'tcx>

An array with the given length. Written as [T; n].
```

Which means I need to know the type and size of the array.

Comment (Manishearth) [reply src/librustdoc/passes/collect_intra_doc_links.rs:654]: I _suspect_ you can generate a type with generic parameters but I'm not sure how best to do that here. Fine to file a followup

File: src/librustdoc/passes/collect_intra_doc_links.rs (hunk 2 above)
Comment (Manishearth) [reply src/librustdoc/passes/collect_intra_doc_links.rs:726]: should be fine

File: src/librustdoc/passes/collect_intra_doc_links.rs (hunk 3 above)
Comment (Manishearth) [reply src/librustdoc/passes/collect_intra_doc_links.rs:896]: this seems okay to me

**Review by Manishearth — APPROVED** [review]

File: src/librustdoc/passes/collect_intra_doc_links.rs (hunk 1 above)
Comment (mdibaiee) [reply src/librustdoc/passes/collect_intra_doc_links.rs:654]: Okay I will create a follow-up issue for this, perhaps it can be addressed somehow

Comment (mdibaiee) [reply src/librustdoc/passes/collect_intra_doc_links.rs]: Added a comment to the original issue, I think that issue covers these cases, so by this PR it will be "partially" fixed. Or would you rather I create a new separate issue?

https://github.com/rust-lang/rust/issues/90703#issuecomment-1004263455

Comment (camelid) [reply src/librustdoc/passes/collect_intra_doc_links.rs]: Can you open a separate issue? That issue will be closed by this PR and having a separate issue will make it easier to track.

Comment (mdibaiee) [reply src/librustdoc/passes/collect_intra_doc_links.rs]: https://github.com/rust-lang/rust/issues/92536

**Review by Manishearth — APPROVED** [review]

**Comment by matthiaskrgr** [comment]
@bors r- 
Looks like some tests failed: https://github.com/rust-lang/rust/pull/92564#issuecomment-1005341236

**Comment by camelid** [comment]
Weird... I think those should have been run on CI.

**Comment by mdibaiee** [comment]
Weird indeed, I ran these tests locally and they passed. I’ll take a look now

**Comment by mdibaiee** [comment]
Okay I think I found the issue: I was using these XPATHs:

```
// @has 'prim_associated_traits/struct.Number.html' '//a[@href="https://doc.rust-lang.org/nightly/std/primitive.f64.html#method.from_str"]' 'f64::from_str()'
```

I just noticed all other tests in the same directory use `{{ channel }}` instead of `https://doc.rust-lang.org/nightly`, so I changed it to:

```
// @has 'prim_associated_traits/struct.Number.html' '//a[@href="{{channel}}/std/primitive.f64.html#method.from_str"]' 'f64::from_str()'
```

The test that failed is `stable` and `nightly`, and it's the stable that's failing because I'm expecting nightly links. My bad.

**Comment by jyn514** [comment]
@pietroalbini your checks are paying off :_)
