### PR TITLE
CFI: Monomorphize transparent ADTs before typeid

### LINKED ISSUE #106230: ICE: CFI dies on `#[repr(transparent)]` on a parameterized ADT (e.g. `ManuallyDrop`).
I've got a fix for this that I'll be uploading in a minute or two, I'm filing the issue to claim an issue number for the test.

### Code

```Rust
#[repr(transparent)]
pub struct Thin<T> (T);
pub fn foo() -> Thin<u8> {
  Thin(0)
}
```

### Meta
`rustc --version --verbose`:
```
rustc 1.68.0-dev
binary: rustc
commit-hash: unknown
commit-date: unknown
host: x86_64-unknown-linux-gnu
release: 1.68.0-dev
LLVM version: 15.0.6
```

### Error output
`rustc -Zsanitizer=cfi -C lto --crate-type=rlib input.rs`
```
error: internal compiler error: compiler/rustc_symbol_mangling/src/typeid/typeid_itanium_cxx_abi.rs:798:13: transform_ty: unexpected `Param(T/#0)`

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.68.0-dev running on x86_64-unknown-linux-gnu

note: compiler flags: -Z sanitizer=cfi -C lto --crate-type rlib

query stack during panic:
end of query stack
error: aborting due to previous error
```
</p>
</details>

### PR DESCRIPTION
**Pull request by maurer**
Monomorphise `#[repr(transparent)]` parameterized ADTs before turning them into an Itanium mangled String.

`#[repr(transparent)]` ADTs currently use the single field to represent them in their CFI type ID to ensure that they are compatible. However, if that type involves a type parameter instantiated at the ADT level, as in `ManuallyDrop`, this will currently ICE as the `Parameter` type cannot be mangled. Since this happens at lowering time, it should always be concrete after substitution.

Fixes #106230

### CODE REVIEW

**Comment by maurer** [comment]
cc @rcvalle

File: compiler/rustc_symbol_mangling/src/typeid/typeid_itanium_cxx_abi.rs [hunk 1]
```diff
@@ -698,7 +700,7 @@ fn transform_ty<'tcx>(tcx: TyCtxt<'tcx>, ty: Ty<'tcx>, options: TransformTyOptio
                     !is_zst
                 });
                 if let Some(field) = field {
-                    let ty0 = tcx.type_of(field.did);
+                    let ty0 = EarlyBinder(tcx.type_of(field.did)).subst(tcx, substs);
```
Comment (compiler-errors) [inline compiler/rustc_symbol_mangling/src/typeid/typeid_itanium_cxx_abi.rs:703]: you can use `tcx.bound_type_of` here

**Comment by compiler-errors** [comment]
One change and this can be r+'d.

File: compiler/rustc_symbol_mangling/src/typeid/typeid_itanium_cxx_abi.rs (hunk 1 above)
Comment (maurer) [reply compiler/rustc_symbol_mangling/src/typeid/typeid_itanium_cxx_abi.rs]: Done, thanks.

File: src/test/codegen/sanitizer-cfi-emit-type-metadata-id-itanium-cxx-abi.rs [hunk 2]
```diff
@@ -425,6 +429,8 @@ pub fn foo145(_: Type13, _: Type13) { }
 // CHECK: define{{.*}}foo145{{.*}}!type ![[TYPE145:[0-9]+]]
 pub fn foo146(_: Type13, _: Type13, _: Type13) { }
 // CHECK: define{{.*}}foo146{{.*}}!type ![[TYPE146:[0-9]+]]
+pub fn foo147(_: Type14<u8>) { }
```
Comment (rcvalle) [inline src/test/codegen/sanitizer-cfi-emit-type-metadata-id-itanium-cxx-abi.rs:432]: Would you mind adding functions with two and three parameters (i.e., foo148 and foo149) similarly to other types to test compression/substitution works for this type?

File: src/test/codegen/sanitizer-cfi-emit-type-metadata-id-itanium-cxx-abi.rs [hunk 3]
```diff
@@ -425,6 +429,8 @@ pub fn foo145(_: Type13, _: Type13) { }
...
+// CHECK: define{{.*}}foo147{{.*}}!type ![[TYPE30]]
```
Comment (rcvalle) [inline src/test/codegen/sanitizer-cfi-emit-type-metadata-id-itanium-cxx-abi.rs:433]: Would you also mind also using an user-defined concrete type for this similarly to Type12 so you have independent type ids for these functions?

**Comment by rcvalle** [comment]
Thanks for reporting and also working on a fix/solution for it, @maurer! Much appreciated.

**Comment by rcvalle** [comment]
(I also just wanted to let you know that I’m currently on vacation so my responses may be delayed.)

File: src/test/codegen/sanitizer-cfi-emit-type-metadata-id-itanium-cxx-abi.rs (hunk 2 above)
Comment (maurer) [reply src/test/codegen/sanitizer-cfi-emit-type-metadata-id-itanium-cxx-abi.rs]: Done.

File: src/test/codegen/sanitizer-cfi-emit-type-metadata-id-itanium-cxx-abi.rs (hunk 3 above)
Comment (maurer) [reply src/test/codegen/sanitizer-cfi-emit-type-metadata-id-itanium-cxx-abi.rs]: Done.

**Comment by compiler-errors** [comment]
Lol, bors closed this because of the "fixes" comment.
