### PR TITLE
Fixed ByteStr not padding within its Display trait when no specific alignment is mentioned

### LINKED ISSUE #152804: std::path::Display regressed in 1.95.0 Nightly
### Code

I tried this code:

```rust
#[test]
fn format_path() {
    use std::path::Path;
    assert_eq!(format!("{:10}", Path::new("/bin/ls").display()), "/bin/ls   ");
}
```

I expected this test to pass; formatting should produce a string 10 characters wide.

Instead, the test fails with:

```
---- tests::format_other stdout ----

thread 'tests::format_other' (208327) panicked at src/lib.rs:14:9:
assertion `left == right` failed
  left: "/bin/ls"
 right: "/bin/ls   "
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

### Version it worked on

It most recently worked on: 1.94.0-beta.3

### Version with regression

`rustc --version --verbose`:
```
rustc 1.95.0-nightly (838709580 2026-02-17)
binary: rustc
commit-hash: 8387095803f21a256a9a772ac1f9b41ed4d5aa0a
commit-date: 2026-02-17
host: x86_64-unknown-linux-gnu
release: 1.95.0-nightly
LLVM version: 22.1.0
```

### Backtrace
<details><summary>Backtrace</summary>
<p>

```
❯ RUST_BACKTRACE=1 cargo +nightly test
   Compiling wtf v0.1.0 (/home/jorendorff/wtf/wtf)
    Finished `test` profile [unoptimized + debuginfo] target(s) in 0.36s
     Running unittests src/lib.rs (target/debug/deps/wtf-9a0d8a9c3d31431d)

running 2 tests
test tests::it_works ... ok
test tests::format_path ... FAILED

failures:

---- tests::format_path stdout ----

thread 'tests::format_path' (210283) panicked at src/lib.rs:12:9:
assertion `left == right` failed
  left: "/bin/ls"
 right: "/bin/ls   "
stack backtrace:
   0: __rustc::rust_begin_unwind
             at /rustc/8387095803f21a256a9a772ac1f9b41ed4d5aa0a/library/std/src/panicking.rs:689:5
   1: core::panicking::panic_fmt
             at /rustc/8387095803f21a256a9a772ac1f9b41ed4d5aa0a/library/core/src/panicking.rs:80:14
   2: core::panicking::assert_failed_inner
             at /rustc/8387095803f21a256a9a772ac1f9b41ed4d5aa0a/library/core/src/panicking.rs:439:17
   3: core::panicking::assert_failed::<alloc::string::String, &str>
             at /home/jorendorff/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/panicking.rs:394:5
   4: wtf::tests::format_path
             at ./src/lib.rs:12:9
   5: wtf::tests::format_path::{closure#0}
             at ./src/lib.rs:10:21
   6: <wtf::tests::format_path::{closure#0} as core::ops::function::FnOnce<()>>::call_once
             at /home/jorendorff/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:250:5
   7: <fn() -> core::result::Result<(), alloc::string::String> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/8387095803f21a256a9a772ac1f9b41ed4d5aa0a/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.


failures:
    tests::format_path

test result: FAILED. 1 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.27s

error: test failed, to rerun pass `--lib`
```

</p>
</details>

@rustbot modify labels: +regression-from-stable-to-nightly -regression-untriaged

### PR DESCRIPTION
**Pull request by asder8215**
Fixes rust-lang/rust#152804. `Path`'s `Display` uses `ByteStr`'s `Display`, which is where the problem was occurring.

The issue was coming from `ByteStr` implementation of `fmt()` in this particular area:
```rust
        let Some(align) = f.align() else {
            return fmt_nopad(self, f);
        };
        let nchars: usize = self
            .utf8_chunks()
            .map(|chunk| {
                chunk.valid().chars().count() + if chunk.invalid().is_empty() { 0 } else { 1 }
            })
            .sum();
        let padding = f.width().unwrap_or(0).saturating_sub(nchars);
        let fill = f.fill();
        let (lpad, rpad) = match align {
            fmt::Alignment::Left => (0, padding),
            fmt::Alignment::Right => (padding, 0),
            fmt::Alignment::Center => {
                let half = padding / 2;
                (half, half + padding % 2)
            }
        };
```

The docs for the align implies that `Alignment::Left`, `Alignment::Right`, `Alignment::Center` comes from `:<`, `:>`, and `:^` respectively with `align()` returning `None` if neither of those symbols are used in the formatted string. However, while padding is taken care of in the aligned cases, we could still have padding for things that don't use alignment like:
```rust
assert_eq!(format!("{:10}", Path::new("/foo/bar").display()), "/foo/bar  ");
```
We shouldn't write to `f` and return from there when there's no alignment; we should also include any potential padding/filling bytes here.

r? @joboet

### CODE REVIEW

File: library/core/src/bstr/mod.rs [hunk 1]
```diff
@@ -184,17 +184,24 @@ impl fmt::Display for ByteStr {
...
+
+        let Some(align) = f.align() else {
+            fmt_nopad(self, f)?;
+            for _ in 0..padding {
+                write!(f, "{fill}")?;
+            }
+            return Ok(());
+        };
+
         let (lpad, rpad) = match align {
```
Comment (joboet) [inline library/core/src/bstr/mod.rs]: I'd match on `f.align()` directly and merge the `else` path with the `Alignment::Left` branch. Then you can also inline `fmt_nopad` since it'll only be used below.

**Review by joboet — CHANGES_REQUESTED** [review]

File: library/core/src/bstr/mod.rs (hunk 1 above)
Comment (asder8215) [reply library/core/src/bstr/mod.rs]: Done.

**Comment by asder8215** [comment]
I'm assuming LLVM optimizes away dead for loops for l_pad in `(0, padding)` or r_pad in `(padding, 0)`. But I can see in most cases that `Alignment:None` has no padding (`r_pad` would be 0 in most cases), which I'm not sure if that right padding for loop would be optimized away.

I'm wondering if this is something that we can optimize in the code?

**Comment by JonathanBrouwer** [comment]
Note that the regressions are all in doc builds, not sure why
