### PR TITLE
resolve #130122: reword 'sort-by' edge-conditions documentation

### LINKED ISSUE #130122: Documentation for `sort_by` (and related methods) is potentially self-contradictory
### Location

[slice::sort_by](https://doc.rust-lang.org/stable/std/primitive.slice.html#method.sort_by)

### Summary

Now that `sort_by` can panic when the ordering is not total, it seems confusing and misleading to me, if not technically wrong, to specifically provide a guarantee about the state of the slice after the operation:

> ...the resulting order of elements in the slice is unspecified. All original elements will remain in the slice and any possible modifications via interior mutability are observed in the input.

In general, I would assume that a guarantee like this only applies if the function returns normally rather than diverging, and thus that it implies the function will not diverge. I'm a bit confused about what the purpose of the guarantee even is; is the point just that, for the purpose of cleanup with `drop` and/or `catch_unwind`, the slice still contains all the same data? I can see how this would be important in the case of a `Vec` or other container with smart-pointer elements, but it also seems that in that case, the more straightforward guarantee is just that, if `Vec::sort_by` panics (for any reason), and this causes the `Vec` itself to be dropped, its `drop` method will still be able to properly `drop` all the elements it contains. Mentioning the "order of elements", though, seems to imply that a user might be able to continue using the slice (or vector) after the panic occurs, and I'm having a hard time thinking of a scenario where that would be useful.

And, of course, with `panic=abort`, control should never return to the caller at all when `sort_by` panics, so this guarantee is meaningless.

The other interpretation I can think of is that this is explaining what happens if the ordering is not total but the new logic _doesn't_ catch it, so `sort_by` returns normally. If that's the case, this should be made explicit.

### PR DESCRIPTION
**Pull request by BatmanAoD**
See #130122 for rationale & preliminary discussion.

### CODE REVIEW

File: library/alloc/src/slice.rs [hunk 1]
```diff
@@ -178,10 +178,15 @@ impl<T> [T] {
     /// This sort is stable (i.e., does not reorder equal elements) and *O*(*n* \* log(*n*))
     /// worst-case.
     ///
-    /// If the implementation of [`Ord`] for `T` does not implement a [total order] the resulting
-    /// order of elements in the slice is unspecified. All original elements will remain in the
-    /// slice and any possible modifications via interior mutability are observed in the input. Same
-    /// is true if the implementation of [`Ord`] for `T` panics.
+    /// If the comparison function compare does not implement a [total order], the function may
```
Comment (Mark-Simulacrum) [inline library/alloc/src/slice.rs:181]: This is on .sort(), so I'm not sure why we're saying "comparison function compare" -- the `Ord` impl wording seems better?

File: library/alloc/src/slice.rs [hunk 2]
```diff
@@ -178,10 +178,15 @@ impl<T> [T] {
...
+    /// panic; even if the function exits normally, the resulting order of elements in the slice is
+    /// unspecified.
+    ///
+    /// Even if `sort_by` or `compare` panics, all original elements will remain in the slice and
+    /// any possible modifications via interior mutability are observed in the input. This ensures
+    /// that recovery code (for instance inside of a `Drop` or following a `catch_unwind`) will
+    /// still have access to all the original elements. For instance, if the slice belongs to a
+    /// `Vec`, the `Vec::drop` method will be able to dispose of all contained elements.
```
Comment (Mark-Simulacrum) [inline library/alloc/src/slice.rs:189]: Part of me wonders if this could use a "which is always true for safe slice methods"? I don't think std is ever in a position to shrink a slice...?

File: library/alloc/src/slice.rs (hunk 1 above)
Comment (BatmanAoD) [reply library/alloc/src/slice.rs:183]: 🤦🏻 I edited the wrong doc-comment. Apologies! But I suppose both `sort` and `sort_by` should have analogous changes.

File: library/alloc/src/slice.rs (hunk 2 above)
Comment (BatmanAoD) [reply library/alloc/src/slice.rs]: I think that makes sense. I've prefixed this paragraph with "all safe functions on slices preserve the invariant that even if the function panics...", moved it to the "Panics" section, and copied into into the "panics" section of each "sort" function.
