### PR TITLE
def_collector, visit_fn: account for no body

### LINKED ISSUE #70736: internal compiler error: local_def_id: no entry for HirId { owner ...
I'm seeing an internal compiler error on the following input (found by [fuzz-rustc](https://github.com/dwrensha/fuzz-rustc)):

```rust
async fn foo();
fn main() {}
```

```
$ rustc --edition=2018 main.rs
error: free function without a body
 --> main.rs:1:1
  |
1 | async fn foo();
  | ^^^^^^^^^^^^^^-
  |               |
  |               help: provide a definition for the function: `{ <body> }`

error: internal compiler error: src/librustc_middle/hir/map/mod.rs:177: local_def_id: no entry for `HirId { owner: DefId(0:3 ~ main[317d]::foo[0]), local_id: 8 }`, which has a map of `Some(Entry { parent: HirId { owner: DefId(0:3 ~ main[317d]::foo[0]), local_id: 14 }, node: Expr(Expr { hir_id: HirId { owner: DefId(0:3 ~ main[317d]::foo[0]), local_id: 8 }, kind: Closure(Value, FnDecl { inputs: [Ty { hir_id: HirId { owner: DefId(0:3 ~ main[317d]::foo[0]), local_id: 1 }, kind: Infer, span: main.rs:1:1: 1:16 }], output: DefaultReturn(main.rs:1:1: 1:16), c_variadic: false, implicit_self: None }, BodyId { hir_id: HirId { owner: DefId(0:3 ~ main[317d]::foo[0]), local_id: 7 } }, main.rs:1:1: 1:16, Some(Static)), attrs: ThinVec(None), span: main.rs:1:1: 1:16 }) })`

thread 'rustc' panicked at 'Box<Any>', src/librustc_errors/lib.rs:880:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.44.0-nightly (76b11980a 2020-04-01) running on x86_64-unknown-linux-gnu

error: aborting due to 2 previous errors
```

### PR DESCRIPTION
**Pull request by Centril**
Fixes #70736 

r? @petrochenkov

### CODE REVIEW

File: src/librustc_resolve/def_collector.rs [hunk 1]
```diff
@@ -117,10 +118,8 @@ impl<'a> visit::Visitor<'a> for DefCollector<'a> {
                 // we must mirror everything that `visit::walk_fn` below does.
                 self.visit_fn_header(&sig.header);
                 visit::walk_fn_decl(self, &sig.decl);
-                if let Some(body) = body {
-                    let closure_def = self.create_def(closure_id, DefPathData::ClosureExpr, span);
-                    self.with_parent(closure_def, |this| this.visit_block(body));
-                }
+                let closure_def = self.create_def(closure_id, DefPathData::ClosureExpr, span);
+                self.with_parent(closure_def, |this| walk_list!(this, visit_block, body));
```
Comment (petrochenkov) [inline src/librustc_resolve/def_collector.rs:122]: I think it's a problem in item lowering rather than here?
If there's no body then there's no closure, but `async fn` lowering still wraps the `ExprKind::Err` recovered from the "no block" into a closure instead of just returning an `ExprKind::Err`.

Comment (Centril) [reply src/librustc_resolve/def_collector.rs:122]: I looked a bit now. Changing lowering to avoid creating the closure on `body = None` would also work I think, but it seems to me it would duplicate more logic and break the `fn lower_block_expr_opt` abstraction used in a bunch of places. Treating `qualifiers fn foo();` as `qualifiers fn foo() { err }` seems fairly consistent and it also simplifies the logic in `def_collector` as well.

Comment (petrochenkov) [reply src/librustc_resolve/def_collector.rs:122]: Ok.
