### PR TITLE
resolve: private fields in tuple struct ctor diag

### LINKED ISSUE #75906: [diagnostics] Attempting to initialize a private field in a public tuple struct yields confusing error message
_This is a constructor counterpart to https://github.com/rust-lang/rust/issues/75907_

## Overview

Errors for private fields in public non-tuple structs are pretty good. Given the following code:

```rust
mod foo {
    pub struct Bar { field: u8 }
}

use foo::Bar;

fn main() {
    let x = Bar { field: 12 };
}
```

The following error is returned:
```txt
error[E0451]: field `field` of struct `foo::Bar` is private
 --> src/main.rs:9:19
  |
9 |     let x = Bar { field: 12 };
  |                   ^^^^^^^^^ private field
```

A hint could be useful here, but overall this is good enough to understand. However when we convert this to a tuple struct the errors get more confusing:

```rust
mod foo {
    pub struct Bar(u8);
}

use foo::Bar;

fn main() {
    let x = Bar(12);
}
```

This yields the following error:

```txt
error[E0423]: expected function, tuple struct or tuple variant, found struct `Bar`
 --> src/main.rs:8:13
  |
8 |     let x = Bar(12);
  |             ^^^ constructor is not visible here due to private fields
```

The message of `expected function, tuple struct or tuple variant, found struct Bar` is not helpful here. It's a bit confusing what the fix is: how do we make the constructor visible? I had to look up how to declare visibility for inner fields in tuple structs.

## Proposed solution

The error message could probably use some work. Something closer to the text of non-tuple structs would be clearer:
```txt
field `0` of struct `foo::Bar` is private
```
Or perhaps an even better direction would be:

```txt
cannot initialize a tuple struct which contains private fields
```

The main code block seems useful. But we could go even further and provide a hint on how to fix this if the struct is defined inside the same project:

```txt
error[E0423]: cannot initialize a tuple struct which contains private fields
 --> src/main.rs:8:13
  |
8 |     let x = Bar(12);
  |             ^^^ constructor is not visible here due to private fields
  |             |
  |             help: declare the struct's fields as public: `struct Bar(pub(crate) u8);`
```

## Conclusion

I found a location where our errors aren't as good as they could be, and figured there may be a way we can use that to not just improve the error message -- but actually teach people about visibility modifiers in tuple structs.

I hope this is helpful. Thanks!

### PR DESCRIPTION
**Pull request by davidtwco**
Fixes #75906.

This PR improves the diagnostic emitted when a tuple struct is being constructed which has private fields so that private fields are labelled and the message is improved.

r? @estebank

### CODE REVIEW

File: compiler/rustc_resolve/src/late/diagnostics.rs [hunk 1]
```diff
@@ -917,54 +917,71 @@ impl<'a: 'ast, 'ast> LateResolutionVisitor<'a, '_, 'ast> {
...
-                            err.span_label(
-                                span,
-                                "constructor is not visible here due to private fields".to_string(),
-                            );
-                        }
+                    if non_visible_spans.len() > 0 {
+                        let mut m: rustc_span::MultiSpan = non_visible_spans.clone().into();
+                        non_visible_spans
+                            .into_iter()
+                            .for_each(|s| m.push_span_label(s, "private field".to_string()));
```
Comment (estebank) [inline compiler/rustc_resolve/src/late/diagnostics.rs:974]: oh! I hadn't thought about doing this this way! neat.

File: compiler/rustc_resolve/src/late/diagnostics.rs [hunk 2]
```diff
@@ -917,54 +917,71 @@ impl<'a: 'ast, 'ast> LateResolutionVisitor<'a, '_, 'ast> {
...
+
+                let is_accessible = self.r.is_accessible_from(ctor_vis, self.parent_scope.module);
+                if !is_expected(ctor_def) || is_accessible {
+                    return true;
+                }
+
+                let field_spans = match source {
+                    // e.g. `if let Enum::TupleVariant(field1, field2) = _`
+                    PathSource::TupleStruct(_, pattern_spans) => {
+                        err.set_primary_message(
```
Comment (guswynn) [inline compiler/rustc_resolve/src/late/diagnostics.rs:936]: nice use of `set_primary_span`

File: compiler/rustc_resolve/src/late/diagnostics.rs [hunk 3]
```diff
@@ -917,54 +917,71 @@ impl<'a: 'ast, 'ast> LateResolutionVisitor<'a, '_, 'ast> {
...
+                            "cannot match against a tuple struct which contains private fields",
+                        );
+
+                        // Use spans of the tuple struct pattern.
+                        Some(Vec::from(pattern_spans))
+                    }
+                    // e.g. `let _ = Enum::TupleVariant(field1, field2);`
+                    _ if source.is_call() => {
```
Comment (guswynn) [inline compiler/rustc_resolve/src/late/diagnostics.rs:944]: when I did the other issue I had no idea i could do this, i though it would require attaching more info into the struct_constructors, nice!

**Review by guswynn — COMMENTED** [review]
I believe for both constructor and pattern cases we need to still extend this to work across crate boundaries (see src/test/ui/issues/issue-75907_b.rs not having the private_field spans)

should we create a follow up issue?

**Comment by davidtwco** [comment]
> I believe for both constructor and pattern cases we need to still extend this to work across crate boundaries (see src/test/ui/issues/issue-75907_b.rs not having the private_field spans)
> 
> should we create a follow up issue?

I think that would make sense.
