### PR TITLE
Always emit unclosed delimiter diagnostics

### LINKED ISSUE #58886: Rust incorrectly accepts unbalanced parentheses
Rust incorrectly accepts the following code (which is missing a `)`):
```rust
pub struct Value {
}

pub fn new() -> Result<Value, ()> {
    Ok(Value {
    } // Look ma, no `)`!
}
```

So far this seems to only happen if the code is inside a submodule. Shell script to reproduce:
```sh
#!/bin/bash

cargo new --lib this_should_not_build
mkdir this_should_not_build/src/foo

cat >> this_should_not_build/src/lib.rs <<-'EOF'
    pub mod foo;
EOF

cat > this_should_not_build/src/foo/mod.rs <<-'EOF'
    pub struct Value {
    }

    pub fn new() -> Result<Value, ()> {
        Ok(Value {
        }
    }
EOF

cd this_should_not_build
cargo build
```

My compiler version: `rustc 1.34.0-nightly (0ea22717a 2019-03-02)`

### PR DESCRIPTION
**Pull request by estebank**
Fix #58886.

### CODE REVIEW

**Comment by Centril** [comment]
@estebank Does this regression exist on the current beta compiler? If so we should beta backport.

**Comment by estebank** [comment]
@Centril I thought beta was spared, but alas, it wasn't.

**Comment by Centril** [comment]
@estebank Aw; crap... 😭; At least we caught it before it went to stable 🎉!

File: src/libsyntax/parse/parser.rs [hunk 1]
```diff
@@ -258,6 +258,14 @@ pub struct Parser<'a> {
     crate unclosed_delims: Vec<UnmatchedBrace>,
 }
 
+impl<'a> Drop for Parser<'a> {
+    fn drop(&mut self) {
+        if !self.unclosed_delims.is_empty() {
+            let diag = self.diagnostic();
+            emit_unclosed_delims(&mut self.unclosed_delims, diag);
```
Comment (petrochenkov) [inline src/libsyntax/parse/parser.rs]: With logic like this, seems like all the remaining calls to `emit_unclosed_delims` can be removed.

File: src/libsyntax/parse/parser.rs [hunk 2]
```diff
@@ -258,6 +258,14 @@ pub struct Parser<'a> {
     crate unclosed_delims: Vec<UnmatchedBrace>,
 }
 
+impl<'a> Drop for Parser<'a> {
+    fn drop(&mut self) {
+        if !self.unclosed_delims.is_empty() {
```
Comment (petrochenkov) [inline src/libsyntax/parse/parser.rs]: Unnecessary condition.

File: src/libsyntax/parse/parser.rs (hunk 1 above)
Comment (estebank) [reply src/libsyntax/parse/parser.rs]: Sadly the ones that get called after `parse_stream_from_source_str` can't be removed (they are using a `ParseSess` instead of a `Parser`), but given that every call of it does it it can be added into its body to have it called in one place for those.

**Comment by estebank** [comment]
@petrochenkcov subsuming #58863 into this PR to avoid merge conflict.

File: src/test/ui/issues/issue-58856-2.stderr [hunk 3]
```diff
@@ -0,0 +1,30 @@
...
+   |                   |     help: `)` may belong here
+   |                   unclosed delimiter
+
+error: expected one of `async`, `const`, `crate`, `default`, `existential`, `extern`, `fn`, `pub`, `type`, `unsafe`, or `}`, found `)`
+  --> $DIR/issue-58856-2.rs:11:1
+   |
+LL |     }
+   |      - expected one of 11 possible tokens here
+LL | }
+   | ^ unexpected token
```
Comment (estebank) [inline src/test/ui/issues/issue-58856-2.stderr]: Finally identified what is causing these: when reaching the end of the current `TokenTree`, `self.bump()` will advance to a close token corresponding to the opening delimiter. There are two options: 1) attempt to rewrite the `TokenTree` representation that the `Parser` has once we suggest a close delim (high potential for bad lurking bugs), or 2) catch this specific case in `expect_one_of`, but that might be too magical.

**Comment by pnkfelix** [comment]
discussed at T-compiler meeting. beta-accepted.
