### PR TITLE
Fix unit struct/enum variant in destructuring assignment

### LINKED ISSUE #94319: Unit struct and enum variants are not accepted as the pattern for destructuring assignment
```rust
fn main() {
    let mut a;
    struct S;
    (S, a) = (S, ()); // Error
    (S {}, a) = (S, ()); // Works
    enum E { A }
    (E::A, a) = (E::A, ()); // Error
    (E::A {}, a) = (E::A, ()); // Works
}
```
```
error[E0070]: invalid left-hand side of assignment
 --> src/main.rs:4:12
  |
4 |     (S, a) = (S, ()); // Error
  |      -     ^
  |      |
  |      cannot assign to this expression

error[E0070]: invalid left-hand side of assignment
 --> src/main.rs:7:15
  |
7 |     (E::A, a) = (E::A, ()); // Error
  |      ----     ^
  |      |
  |      cannot assign to this expression
```
https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=bf807e599b504f489454388eb27acbbb

The RFC states explicitly we should support them:

https://github.com/rust-lang/rfcs/blob/master/text/2909-destructuring-assignment.md#reference-level-explanation

> The class of assignee expressions is defined inductively:
>
>  - Place: `place`.
>  - Underscore: `_`.
>  - Tuples: `(assignee, assignee, assignee)`, `(assignee, .., assignee)`, `(.., assignee, assignee)`, `(assignee, assignee, ..)`.
>  - Slices: `[assignee, assignee, assignee]`, `[assignee, .., assignee]`, `[.., assignee, assignee]`, `[assignee, assignee, ..]`.
>  - Tuple structs: `path(assignee, assignee, assignee)`, `path(assignee, .., assignee)`, `path(.., assignee, assignee)`, `path(assignee, assignee, ..)`.
>  - Structs: `path { field: assignee, field: assignee }`, `path { field: assignee, field: assignee, .. }`.
>  - **Unit structs: `path`**.

@rustbot label: +F-destructuring_assignment

### PR DESCRIPTION
**Pull request by compiler-errors**
See https://github.com/rust-lang/rfcs/blob/master/text/2909-destructuring-assignment.md#guide-level-explanation, "including **unit** and tuple structs"

Fixes #94319

### CODE REVIEW

**Comment by lcnr** [comment]
looks good to me, @rust-lang/lang this PR adds unit structs and enum variants to destructuring assignment as insta stable. 

This will be quite infrequently used and imo is a small enough papercut that most people will not add a feature for this. It is also a consistency fix and was part of the original RFC.

Still want some kind of signoff here.

**Comment by petrochenkov** [comment]
I'll check the implementation because there was some tricky details with destructuring assignments to tuple structs.

As for usefulness, this certainly doesn't look useful.
The only possible motivation here is consistency in the sense "if the expression looks like a pattern, then the assignment desugaring is possible".

**Comment by lcnr** [comment]
> As for usefulness, this certainly doesn't look useful.

I guess one might use it for
```rust
struct ZstToken;
fn returns_value_and_token() -> (u32, ZstToken) { ... }

let mut x = 0;
// With this PR:
(x, ZstToken) = returns_value_and_token();
// Without it:
x = returns_value_and_token().0;
// ^ won't detect if the return type of that function changes in the future
```

**Comment by petrochenkov** [comment]
>there was some tricky details with destructuring assignments to tuple structs

Ok, as expected, the implementation is subtly incorrect in presence of associated items and `Self`.

@compiler-errors 
Could you repeat the setup used for the `ExprKind::Call` case exactly?
I.e. introduce analogues for `fn extract_tuple_struct_path` and `fn expected_in_tuple_struct_pat`, but for path patterns.

(I'd also recommend to avoid additional refactorings like moving `self.lower_expr(lhs)`.)

File: compiler/rustc_hir/src/def.rs [hunk 1]
```diff
@@ -657,4 +657,13 @@ impl<Id> Res<Id> {
     pub fn expected_in_tuple_struct_pat(&self) -> bool {
         matches!(self, Res::Def(DefKind::Ctor(_, CtorKind::Fn), _) | Res::SelfCtor(..))
     }
+
+    /// Returns whether such a resolved path can occur in a unit struct/variant pattern
+    pub fn expected_in_unit_struct_pat(&self) -> bool {
```
Comment (petrochenkov) [inline compiler/rustc_hir/src/def.rs:662]: Could you use this function in `fn is_expected` in rustc_resolve?
```rust
PathSource::Pat => res.expected_in_unit_struct_pat() || matches!(res, DefKind::Const | DefKind::AssocConst)
```

File: src/test/ui/destructuring-assignment/struct-or-enum-variant-path.rs [hunk 2]
```diff
@@ -0,0 +1,11 @@
...
+
+fn main() {
+    let mut a;
+
+    struct S;
+    (S, a) = (S, ());
+
+    enum E { A }
+    (E::A, a) = (E::A, ());
+}
```
Comment (petrochenkov) [inline src/test/ui/destructuring-assignment/struct-or-enum-variant-path.rs:11]: Could you add test cases for qualified paths, type-relative paths and `Self` constructor?
```rust
struct S;

impl S {
    fn check() { (Self, a) = (S, ()); }
}

enum E { V }
type A = E;

fn check() {
    (<E>::V, a) = (E::V, ());
    (A::V, a) = (E::V, ());
}
```

**Comment by compiler-errors** [comment]
Rebased and addressed comments

**Comment by petrochenkov** [comment]
Thanks!
r=me on the implementation.

I'm going to reroute this to the lang team for some kind of approval.

**Comment by nikomatsakis** [comment]
@bors r+

We discussed this in the @rust-lang/lang meeting. Given that this is a bug-fix that is making the behavior match the RFC as specified, and that the old code did not compile (rather than compiling with different behavior, for example), we don't feel an FCP is necessary.

Thanks @petrochenkov for raising it to our attention!
