### PR TITLE
Fix incorrect mutable suggestion information for binding in ref pattern like:  `let &b = a;` 

### LINKED ISSUE #114896: `consider changing this to be mutable` suggested for a binding in a ref pattern
### Code

```Rust
fn x(a: &char) {
    let &b = a;
    b.make_ascii_uppercase();
}
```

### Current output

```Shell
error[E0596]: cannot borrow `b` as mutable, as it is not declared as mutable
 --> src/lib.rs:3:5
  |
3 |     b.make_ascii_uppercase();
  |     ^ cannot borrow as mutable
  |
help: consider changing this to be mutable
  |
2 |     let &mut b = a;
  |          +++
```

### Desired output

_No response_

### Rationale and extra context

Applying the suggestion gives

```
error[[E0308]](https://doc.rust-lang.org/nightly/error_codes/E0308.html): mismatched types
 --> src/lib.rs:2:9
  |
2 |     let &mut b = a;
  |         ^^^^^^   - this expression has type `&char`
  |         |
  |         types differ in mutability
  |         help: to declare a mutable variable use: `mut b`
  |
  = note:      expected reference `&char`
          found mutable reference `&mut _`
```

### Other cases

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by surechen**
fixes #114896

I find we have to get pat_span but not local_decl.source_info.span for suggestion. In `let &b = a;`  pat_span is &b. I think check `let &b = a` in hir to make sure it is hir::Node::Local(hir::Local {pat: hir::Pat{kind: hir::PatKind::Ref(.......   can distinguish it from other situation, but I'm not sure.

If my processing method is not accurate, please guide me to modify it, thank you.

r? @davidtwco

### CODE REVIEW

File: compiler/rustc_borrowck/src/diagnostics/mutability_errors.rs [hunk 1]
```diff
@@ -710,6 +705,63 @@ impl<'a, 'tcx> MirBorrowckCtxt<'a, 'tcx> {
...
+                        self.hir_id = Some(local.hir_id);
+                    }
+                }
+                hir::intravisit::walk_stmt(self, s);
+            }
+        }
+
+        let hir_map = self.infcx.tcx.hir();
+        let def_id = self.body.source.def_id();
+        let hir_id = if let Some(local_def_id) = def_id.as_local() && let Some(body_id) = hir_map.maybe_body_owned_by(local_def_id) {
```
Comment (davidtwco) [inline compiler/rustc_borrowck/src/diagnostics/mutability_errors.rs:739]: nit: this line is a little bit long (rustfmt should get this automatically but can't with let-chains yet)

File: compiler/rustc_borrowck/src/diagnostics/mutability_errors.rs [hunk 2]
```diff
@@ -710,6 +705,63 @@ impl<'a, 'tcx> MirBorrowckCtxt<'a, 'tcx> {
...
+                v.hir_id
+            } else {
+                None
+            };
+
+        // suggestion for issue: #114896
+        // let &b = a;
+        // b.make_ascii_uppercase();
+        if let Some(hir_id) = hir_id && let Some(hir::Node::Local(hir::Local {pat: hir::Pat{kind: hir::PatKind::Ref(_, _), ..}, ..})) = hir_map.find(hir_id) {
+                err.span_suggestion(pat_span, "consider changing this to be mutable", format!("&(mut {})", self.infcx.tcx.sess.source_map().span_to_snippet(local_decl.source_info.span).unwrap()), Applicability::MachineApplicable,);
```
Comment (davidtwco) [inline compiler/rustc_borrowck/src/diagnostics/mutability_errors.rs:755]: nit: likewise with the inside of this condition

Comment (davidtwco) [inline compiler/rustc_borrowck/src/diagnostics/mutability_errors.rs:755]: I'd move the `span_to_snippet` into an `if let` in the surrounding chain.

File: compiler/rustc_borrowck/src/diagnostics/mutability_errors.rs [hunk 3]
```diff
@@ -710,6 +705,63 @@ impl<'a, 'tcx> MirBorrowckCtxt<'a, 'tcx> {
...
+                };
+                v.visit_body(body);
+                v.hir_id
+            } else {
+                None
+            };
+
+        // suggestion for issue: #114896
+        // let &b = a;
+        // b.make_ascii_uppercase();
```
Comment (davidtwco) [inline compiler/rustc_borrowck/src/diagnostics/mutability_errors.rs:753]:
```suggestion
        // With ref-binding patterns, the mutability suggestion has to apply to
        // the binding, not the reference (which would be a type error):
        //
        // `let &b = a;` -> `let &(mut b) = a;`
```

**Review by davidtwco — CHANGES_REQUESTED** [review]

File: compiler/rustc_borrowck/src/diagnostics/mutability_errors.rs [hunk 4]
```diff
@@ -710,6 +705,63 @@ impl<'a, 'tcx> MirBorrowckCtxt<'a, 'tcx> {
         )
     }
 
+    fn construct_suggestion(&self, err: &mut DiagnosticBuilder<'_, ErrorGuaranteed>, local: Local) {
+        let local_decl = &self.body.local_decls[local];
+        debug!("local_decl: {:?}", local_decl);
+        let pat_span = match *local_decl.local_info() {
+            LocalInfo::User(BindingForm::Var(mir::VarBindingForm {
+                binding_mode: ty::BindingMode::BindByValue(Mutability::Not),
```
Comment (matthewjasper) [inline compiler/rustc_borrowck/src/diagnostics/mutability_errors.rs:713]: Probably not in scope for this PR, but we really should put a `HirId` in here.

Comment (surechen) [reply compiler/rustc_borrowck/src/diagnostics/mutability_errors.rs:713]: > Probably not in scope for this PR, but we really should put a `HirId` in here.

Thanks a lot, since this will cause multiple changes when using `LocalDecl`, I thought I could submit another pr to support this.

File: compiler/rustc_borrowck/src/diagnostics/mutability_errors.rs [hunk 5]
```diff
@@ -710,6 +705,63 @@ impl<'a, 'tcx> MirBorrowckCtxt<'a, 'tcx> {
         )
     }
 
+    fn construct_suggestion(&self, err: &mut DiagnosticBuilder<'_, ErrorGuaranteed>, local: Local) {
```
[the remark this answers is not in the document]
Comment (surechen) [reply compiler/rustc_borrowck/src/diagnostics/mutability_errors.rs]: > It might be worth giving this a more descriptive name - I'm sure that there are lots of suggestions being constructed during borrowck, so we mention the specific suggestion being constructed.

done

File: compiler/rustc_borrowck/src/diagnostics/mutability_errors.rs [hunk 6]
```diff
@@ -710,6 +705,63 @@ impl<'a, 'tcx> MirBorrowckCtxt<'a, 'tcx> {
...
+                v.visit_body(body);
+                v.hir_id
+            } else {
+                None
+            };
+
+        // suggestion for issue: #114896
+        // let &b = a;
+        // b.make_ascii_uppercase();
+        if let Some(hir_id) = hir_id && let Some(hir::Node::Local(hir::Local {pat: hir::Pat{kind: hir::PatKind::Ref(_, _), ..}, ..})) = hir_map.find(hir_id) {
```
[the remark this answers is not in the document]
Comment (surechen) [reply compiler/rustc_borrowck/src/diagnostics/mutability_errors.rs]: > nit: formatting again, this line is a bit long and the missing spaces around `{}` look out of place (rustfmt should get this automatically but can't with let-chains yet)

done

File: compiler/rustc_borrowck/src/diagnostics/mutability_errors.rs (hunk 2 above)
Comment (surechen) [reply compiler/rustc_borrowck/src/diagnostics/mutability_errors.rs]: > nit: likewise with the inside of this condition

done

**Review by davidtwco — APPROVED** [review]
