### PR TITLE
Directly use raw pointers in `AtomicPtr` store/load

### LINKED ISSUE #1574: Memory leak checker misses AtomicPtr
```rust
use std::{
    cell::UnsafeCell,
    ptr,
    sync::atomic::{AtomicPtr, Ordering},
};

fn leak() {
    static LEAK: AtomicPtr<usize> = AtomicPtr::new(ptr::null_mut());
    LEAK.store(Box::into_raw(Box::new(0usize)), Ordering::SeqCst);
}

fn no_leak() {
    struct Local(UnsafeCell<*mut usize>);

    unsafe impl Send for Local {}
    unsafe impl Sync for Local {}

    static LEAK: Local = Local(UnsafeCell::new(ptr::null_mut()));
    *unsafe { &mut *LEAK.0.get() } = Box::into_raw(Box::new(0usize));
}

fn main() {
    no_leak();
    // leak();
}
```

Miri considers memory leaks reachable through a static global as non-leaking. I'd expect the Atomic* case be non-leaking as well, however miri reports it as leaked memory.

```
The following memory was leaked: alloc1834 (Rust heap, size: 8, align: 8) {
    00 00 00 00 00 00 00 00                         │ ........
}

error: the evaluated program leaked memory

error: aborting due to previous error; 1 warning emitted
```

(This is a special case of https://github.com/rust-lang/miri/issues/1618.)

### PR DESCRIPTION
**Pull request by oli-obk**
I was unable to find any reason for this limitation in the latest source of LLVM or in the documentation [here](http://llvm.org/docs/Atomics.html#libcalls-atomic).

fixes https://github.com/rust-lang/miri/issues/1574

### CODE REVIEW

**Comment by RalfJung** [comment]
With this you can probably remove the use of `miri_static_root` in `library/std/src/sys/windows/thread_local_key.rs`.

**Comment by oli-obk** [comment]
Removed that and miri still tests successfully

**Comment by RalfJung** [comment]
AFAIK @cuviper is also knowledgeable for matters of LLVM

**Comment by nagisa** [comment]
There's an entire workgroup of us! (rust-lang/wg-llvm)

This seems just fine to me, @bors r+ rollup=iffy

**Comment by oli-obk** [comment]
:laughing: nevermind, we found a platform where this doesn't work

```
Intrinsic has incorrect argument type!
void ({}*)* @llvm.ppc.cfence.p0sl_s
in function rust_oom
LLVM ERROR: Broken function found, compilation aborted!
[RUSTC-TIMING] std test:false 20.161
error: could not compile `std`
```

I'll adjust the llvm backend to do the appropriate transformation instead of having that in libcore

**Comment by RalfJung** [comment]
Oh, this looks great, I feared it would be much more complicated. :)

If I understood correctly, since this happens in the general SSA backend, the Cranelift backend will not need to do anything itself? Cc @bjorn3

**Comment by bjorn3** [comment]
I don't use cg_ssa yet. Cranelift doesn't have a separate pointer type, so no changes to the actual codegen are necessary. There is a validation for the used type though. The fix for cg_clif should be a matter of adding `ty::RawPtr` to the match arm at https://github.com/rust-lang/rust/blob/2e5723137b2b88368d018b262a0a823a1423131b/compiler/rustc_codegen_cranelift/src/intrinsics/mod.rs#L149

File: library/core/src/sync/atomic.rs [hunk 1]
```diff
@@ -1179,6 +1200,14 @@ impl<T> AtomicPtr<T> {
                 Err(x) => Err(x as *mut T),
             }
         }
+        #[cfg(not(bootstrap))]
+        // SAFETY: This intrinsic is unsafe because it operates on a raw pointer
+        // but we know for sure that the pointer is valid (we just got it from
+        // an `UnsafeCell` that we have by reference) and the atomic operation
+        // itself allows us to safely mutate the `UnsafeCell` contents.
```
Comment (bjorn3) [inline library/core/src/sync/atomic.rs:1207]: This doesn't match the safety comment for the `#[cfg(bootstrap)]` case.

**Review by bjorn3 — APPROVED** [review]
The cg_clif change LGTM

File: library/core/src/sync/atomic.rs (hunk 1 above)
Comment (oli-obk) [reply library/core/src/sync/atomic.rs:1207]: I know, but I felt like it wasn't worth updating that, too, since it'll go away with the next beta anyway

**Comment by bjorn3** [comment]
It says "This check failed" without any logs. I guess it is spurious

@bors retry
