### PR TITLE
Don't assume traits used as type are trait objs in 2021 edition

### LINKED ISSUE #120241: ICE: E0391
¯\ _(ツ)_/¯

auto-reduced (treereduce-rust):
````rust
#![feature(object_safe_for_dispatch)]

trait B {
    fn f(a: A) -> A;
}

trait A {
    fn g(b: B) -> B;
}

fn main() {}


````

original:
````rust
#![feature(object_safe_for_dispatch)]

trait B { fn f(a: A) -> A; }
//~^ ERROR associated item referring to unboxed trait object for its own trait
//~| WARN trait objects without an explicit `dyn` are deprecated
//~| WARN trait objects without an explicit `dyn` are deprecated
//~| WARN this is accepted in the current edition
//~| WARN this is accepted in the current edition
//~| WARN this is accepted in the current edition
//~| ERROR the trait `A` cannot be made into an object
trait A { fn g(b: B) -> B; }
//~^ WARN trait objects without an explicit `dyn` are deprecated
//~| WARN trait objects without an explicit `dyn` are deprecated
//~| WARN trait objects without an explicit `dyn` are deprecated
// can't actually invoke it from an object (yet...?).
//~| WARN this is accepted in the current edition
//~| WARN this is accepted in the current edition
//~| ERROR the trait `B` cannot be made into an object
fn main() {}

````

Version information
````
rustc 1.77.0-nightly (a58ec8ff0 2024-01-22)
binary: rustc
commit-hash: a58ec8ff03b3269b20104eb7eae407be48ab95a7
commit-date: 2024-01-22
host: x86_64-unknown-linux-gnu
release: 1.77.0-nightly
LLVM version: 17.0.6

````

Command:
`/home/matthias/.rustup/toolchains/master/bin/rustc `

<details><summary><strong>Program output</strong></summary>
<p>

```
warning: trait objects without an explicit `dyn` are deprecated
 --> /tmp/icemaker_global_tempdir.yPYGjh9iJjgj/rustc_testrunner_tmpdir_reporting.YjRXwTSsOKW4/mvce.rs:8:13
  |
8 |     fn g(b: B) -> B;
  |             ^
  |
  = warning: this is accepted in the current edition (Rust 2015) but is a hard error in Rust 2021!
  = note: for more information, see <https://doc.rust-lang.org/nightly/edition-guide/rust-2021/warnings-promoted-to-error.html>
  = note: `B` it is not object safe, so it can't be `dyn`
  = note: `#[warn(bare_trait_objects)]` on by default
help: use a new generic type parameter, constrained by `B`
  |
8 |     fn g<T: B>(b: T) -> B;
  |         ++++++    ~
help: you can also use an opaque type, but users won't be able to specify the type parameter when calling the `fn`, having to rely exclusively on type inference
  |
8 |     fn g(b: impl B) -> B;
  |             ++++

warning: trait objects without an explicit `dyn` are deprecated
 --> /tmp/icemaker_global_tempdir.yPYGjh9iJjgj/rustc_testrunner_tmpdir_reporting.YjRXwTSsOKW4/mvce.rs:8:19
  |
8 |     fn g(b: B) -> B;
  |                   ^
  |
  = warning: this is accepted in the current edition (Rust 2015) but is a hard error in Rust 2021!
  = note: for more information, see <https://doc.rust-lang.org/nightly/edition-guide/rust-2021/warnings-promoted-to-error.html>
help: `B` is not object safe, use `impl B` to return an opaque type, as long as you return a single underlying type
  |
8 |     fn g(b: B) -> impl B;
  |                   ++++

warning: trait objects without an explicit `dyn` are deprecated
 --> /tmp/icemaker_global_tempdir.yPYGjh9iJjgj/rustc_testrunner_tmpdir_reporting.YjRXwTSsOKW4/mvce.rs:4:13
  |
4 |     fn f(a: A) -> A;
  |             ^
  |
  = warning: this is accepted in the current edition (Rust 2015) but is a hard error in Rust 2021!
  = note: for more information, see <https://doc.rust-lang.org/nightly/edition-guide/rust-2021/warnings-promoted-to-error.html>
  = note: `A` it is not object safe, so it can't be `dyn`
help: use a new generic type parameter, constrained by `A`
  |
4 |     fn f<T: A>(a: T) -> A;
  |         ++++++    ~
help: you can also use an opaque type, but users won't be able to specify the type parameter when calling the `fn`, having to rely exclusively on type inference
  |
4 |     fn f(a: impl A) -> A;
  |             ++++

warning: trait objects without an explicit `dyn` are deprecated
 --> /tmp/icemaker_global_tempdir.yPYGjh9iJjgj/rustc_testrunner_tmpdir_reporting.YjRXwTSsOKW4/mvce.rs:4:19
  |
4 |     fn f(a: A) -> A;
  |                   ^
  |
  = warning: this is accepted in the current edition (Rust 2015) but is a hard error in Rust 2021!
  = note: for more information, see <https://doc.rust-lang.org/nightly/edition-guide/rust-2021/warnings-promoted-to-error.html>
help: `A` is not object safe, use `impl A` to return an opaque type, as long as you return a single underlying type
  |
4 |     fn f(a: A) -> impl A;
  |                   ++++

note: no errors encountered even though `span_delayed_bug` issued

note: those delayed bugs will now be shown as internal compiler errors

error: internal compiler error[E0391]: cycle detected when computing function signature of `B::f`
  --> /tmp/icemaker_global_tempdir.yPYGjh9iJjgj/rustc_testrunner_tmpdir_reporting.YjRXwTSsOKW4/mvce.rs:4:5
   |
4  |     fn f(a: A) -> A;
   |     ^^^^^^^^^^^^^^^^
   |
note: ...which requires checking if trait `A` is object safe...
  --> /tmp/icemaker_global_tempdir.yPYGjh9iJjgj/rustc_testrunner_tmpdir_reporting.YjRXwTSsOKW4/mvce.rs:7:1
   |
7  | trait A {
   | ^^^^^^^
note: ...which requires determining object safety of trait `A`...
  --> /tmp/icemaker_global_tempdir.yPYGjh9iJjgj/rustc_testrunner_tmpdir_reporting.YjRXwTSsOKW4/mvce.rs:7:1
   |
7  | trait A {
   | ^^^^^^^
note: ...which requires computing function signature of `A::g`...
  --> /tmp/icemaker_global_tempdir.yPYGjh9iJjgj/rustc_testrunner_tmpdir_reporting.YjRXwTSsOKW4/mvce.rs:8:5
   |
8  |     fn g(b: B) -> B;
   |     ^^^^^^^^^^^^^^^^
note: ...which requires checking if trait `B` is object safe...
  --> /tmp/icemaker_global_tempdir.yPYGjh9iJjgj/rustc_testrunner_tmpdir_reporting.YjRXwTSsOKW4/mvce.rs:3:1
   |
3  | trait B {
   | ^^^^^^^
note: ...which requires determining object safety of trait `B`...
  --> /tmp/icemaker_global_tempdir.yPYGjh9iJjgj/rustc_testrunner_tmpdir_reporting.YjRXwTSsOKW4/mvce.rs:3:1
   |
3  | trait B {
   | ^^^^^^^
   = note: ...which again requires computing function signature of `B::f`, completing the cycle
note: cycle used when collecting item types in top-level module
  --> /tmp/icemaker_global_tempdir.yPYGjh9iJjgj/rustc_testrunner_tmpdir_reporting.YjRXwTSsOKW4/mvce.rs:1:1
   |
1  | / #![feature(object_safe_for_dispatch)]
2  | |
3  | | trait B {
4  | |     fn f(a: A) -> A;
...  |
10 | |
11 | | fn main() {}
   | |____________^
   = note: see https://rustc-dev-guide.rust-lang.org/overview.html#queries and https://rustc-dev-guide.rust-lang.org/query.html for more information
note: delayed at compiler/rustc_query_system/src/query/job.rs:605:16
         0: <rustc_errors::DiagCtxtInner>::emit_diagnostic
         1: <rustc_errors::DiagCtxt>::emit_diagnostic
         2: <rustc_span::ErrorGuaranteed as rustc_errors::diagnostic_builder::EmissionGuarantee>::emit_producing_guarantee
         3: rustc_query_system::query::plumbing::mk_cycle::<rustc_query_impl::DynamicConfig<rustc_query_system::query::caches::DefIdCache<rustc_middle::query::erase::Erased<[u8; 24]>>, false, false, false>, rustc_query_impl::plumbing::QueryCtxt>
         4: rustc_query_system::query::plumbing::cycle_error::<rustc_query_impl::DynamicConfig<rustc_query_system::query::caches::DefIdCache<rustc_middle::query::erase::Erased<[u8; 24]>>, false, false, false>, rustc_query_impl::plumbing::QueryCtxt>
         5: rustc_query_impl::query_impl::fn_sig::get_query_non_incr::__rust_end_short_backtrace
         6: rustc_middle::query::plumbing::query_get_at::<rustc_query_system::query::caches::DefIdCache<rustc_middle::query::erase::Erased<[u8; 24]>>>
         7: rustc_trait_selection::traits::object_safety::virtual_call_violations_for_method
         8: rustc_trait_selection::traits::object_safety::object_safety_violations_for_assoc_item
         9: <core::iter::adapters::flatten::FlatMap<core::iter::adapters::map::Map<core::iter::adapters::map::Map<core::slice::iter::Iter<(rustc_span::symbol::Symbol, rustc_middle::ty::assoc::AssocItem)>, <rustc_data_structures::sorted_map::index_map::SortedIndexMultiMap<u32, rustc_span::symbol::Symbol, rustc_middle::ty::assoc::AssocItem>>::iter::{closure#0}>, <rustc_middle::ty::assoc::AssocItems>::in_definition_order::{closure#0}>, alloc::vec::Vec<rustc_middle::traits::ObjectSafetyViolation>, rustc_trait_selection::traits::object_safety::object_safety_violations_for_trait::{closure#0}> as core::iter::traits::iterator::Iterator>::next
        10: <core::iter::adapters::flatten::FlatMap<rustc_trait_selection::traits::util::SupertraitDefIds, alloc::vec::Vec<rustc_middle::traits::ObjectSafetyViolation>, rustc_trait_selection::traits::object_safety::object_safety_violations::{closure#0}> as core::iter::traits::iterator::Iterator>::next
        11: rustc_trait_selection::traits::object_safety::object_safety_violations
        12: rustc_query_impl::plumbing::__rust_begin_short_backtrace::<rustc_query_impl::query_impl::object_safety_violations::dynamic_query::{closure#2}::{closure#0}, rustc_middle::query::erase::Erased<[u8; 16]>>
        13: <rustc_query_impl::query_impl::object_safety_violations::dynamic_query::{closure#2} as core::ops::function::FnOnce<(rustc_middle::ty::context::TyCtxt, rustc_span::def_id::DefId)>>::call_once
        14: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::DynamicConfig<rustc_query_system::query::caches::DefIdCache<rustc_middle::query::erase::Erased<[u8; 16]>>, false, false, false>, rustc_query_impl::plumbing::QueryCtxt, false>
        15: rustc_query_impl::query_impl::object_safety_violations::get_query_non_incr::__rust_end_short_backtrace
        16: rustc_middle::query::plumbing::query_get_at::<rustc_query_system::query::caches::DefIdCache<rustc_middle::query::erase::Erased<[u8; 16]>>>
        17: rustc_trait_selection::traits::object_safety::check_is_object_safe
        18: rustc_query_impl::plumbing::__rust_begin_short_backtrace::<rustc_query_impl::query_impl::check_is_object_safe::dynamic_query::{closure#2}::{closure#0}, rustc_middle::query::erase::Erased<[u8; 1]>>
        19: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::DynamicConfig<rustc_query_system::query::caches::DefIdCache<rustc_middle::query::erase::Erased<[u8; 1]>>, false, false, false>, rustc_query_impl::plumbing::QueryCtxt, false>
        20: rustc_query_impl::query_impl::check_is_object_safe::get_query_non_incr::__rust_end_short_backtrace
        21: rustc_middle::query::plumbing::query_get_at::<rustc_query_system::query::caches::DefIdCache<rustc_middle::query::erase::Erased<[u8; 1]>>>
        22: <dyn rustc_hir_analysis::astconv::AstConv>::maybe_lint_impl_trait
        23: <<dyn rustc_hir_analysis::astconv::AstConv>::maybe_lint_bare_trait::{closure#1} as core::ops::function::FnOnce<(&mut rustc_errors::diagnostic_builder::DiagnosticBuilder<()>,)>>::call_once::{shim:vtable#0}
        24: <alloc::boxed::Box<dyn for<'a, 'b> core::ops::function::FnOnce<(&'a mut rustc_errors::diagnostic_builder::DiagnosticBuilder<'b, ()>,), Output = ()>> as core::ops::function::FnOnce<(&mut rustc_errors::diagnostic_builder::DiagnosticBuilder<()>,)>>::call_once
        25: rustc_middle::lint::struct_lint_level::struct_lint_level_impl::<&str>
        26: <dyn rustc_hir_analysis::astconv::AstConv>::maybe_lint_bare_trait
        27: <dyn rustc_hir_analysis::astconv::AstConv>::ast_ty_to_ty_inner
        28: <dyn rustc_hir_analysis::astconv::AstConv>::ty_of_fn
        29: rustc_hir_analysis::collect::fn_sig
        30: rustc_query_impl::plumbing::__rust_begin_short_backtrace::<rustc_query_impl::query_impl::fn_sig::dynamic_query::{closure#2}::{closure#0}, rustc_middle::query::erase::Erased<[u8; 24]>>
        31: <rustc_query_impl::query_impl::fn_sig::dynamic_query::{closure#2} as core::ops::function::FnOnce<(rustc_middle::ty::context::TyCtxt, rustc_span::def_id::DefId)>>::call_once
        32: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::DynamicConfig<rustc_query_system::query::caches::DefIdCache<rustc_middle::query::erase::Erased<[u8; 24]>>, false, false, false>, rustc_query_impl::plumbing::QueryCtxt, false>
        33: rustc_query_impl::query_impl::fn_sig::get_query_non_incr::__rust_end_short_backtrace
        34: rustc_middle::query::plumbing::query_get_at::<rustc_query_system::query::caches::DefIdCache<rustc_middle::query::erase::Erased<[u8; 24]>>>
        35: rustc_trait_selection::traits::object_safety::virtual_call_violations_for_method
        36: rustc_trait_selection::traits::object_safety::object_safety_violations_for_assoc_item
        37: <core::iter::adapters::flatten::FlatMap<core::iter::adapters::map::Map<core::iter::adapters::map::Map<core::slice::iter::Iter<(rustc_span::symbol::Symbol, rustc_middle::ty::assoc::AssocItem)>, <rustc_data_structures::sorted_map::index_map::SortedIndexMultiMap<u32, rustc_span::symbol::Symbol, rustc_middle::ty::assoc::AssocItem>>::iter::{closure#0}>, <rustc_middle::ty::assoc::AssocItems>::in_definition_order::{closure#0}>, alloc::vec::Vec<rustc_middle::traits::ObjectSafetyViolation>, rustc_trait_selection::traits::object_safety::object_safety_violations_for_trait::{closure#0}> as core::iter::traits::iterator::Iterator>::next
        38: <core::iter::adapters::flatten::FlatMap<rustc_trait_selection::traits::util::SupertraitDefIds, alloc::vec::Vec<rustc_middle::traits::ObjectSafetyViolation>, rustc_trait_selection::traits::object_safety::object_safety_violations::{closure#0}> as core::iter::traits::iterator::Iterator>::next
        39: rustc_trait_selection::traits::object_safety::object_safety_violations
        40: rustc_query_impl::plumbing::__rust_begin_short_backtrace::<rustc_query_impl::query_impl::object_safety_violations::dynamic_query::{closure#2}::{closure#0}, rustc_middle::query::erase::Erased<[u8; 16]>>
        41: <rustc_query_impl::query_impl::object_safety_violations::dynamic_query::{closure#2} as core::ops::function::FnOnce<(rustc_middle::ty::context::TyCtxt, rustc_span::def_id::DefId)>>::call_once
        42: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::DynamicConfig<rustc_query_system::query::caches::DefIdCache<rustc_middle::query::erase::Erased<[u8; 16]>>, false, false, false>, rustc_query_impl::plumbing::QueryCtxt, false>
        43: rustc_query_impl::query_impl::object_safety_violations::get_query_non_incr::__rust_end_short_backtrace
        44: rustc_middle::query::plumbing::query_get_at::<rustc_query_system::query::caches::DefIdCache<rustc_middle::query::erase::Erased<[u8; 16]>>>
        45: rustc_trait_selection::traits::object_safety::check_is_object_safe
        46: rustc_query_impl::plumbing::__rust_begin_short_backtrace::<rustc_query_impl::query_impl::check_is_object_safe::dynamic_query::{closure#2}::{closure#0}, rustc_middle::query::erase::Erased<[u8; 1]>>
        47: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::DynamicConfig<rustc_query_system::query::caches::DefIdCache<rustc_middle::query::erase::Erased<[u8; 1]>>, false, false, false>, rustc_query_impl::plumbing::QueryCtxt, false>
        48: rustc_query_impl::query_impl::check_is_object_safe::get_query_non_incr::__rust_end_short_backtrace
        49: rustc_middle::query::plumbing::query_get_at::<rustc_query_system::query::caches::DefIdCache<rustc_middle::query::erase::Erased<[u8; 1]>>>
        50: <dyn rustc_hir_analysis::astconv::AstConv>::maybe_lint_impl_trait
        51: <<dyn rustc_hir_analysis::astconv::AstConv>::maybe_lint_bare_trait::{closure#1} as core::ops::function::FnOnce<(&mut rustc_errors::diagnostic_builder::DiagnosticBuilder<()>,)>>::call_once::{shim:vtable#0}
        52: <alloc::boxed::Box<dyn for<'a, 'b> core::ops::function::FnOnce<(&'a mut rustc_errors::diagnostic_builder::DiagnosticBuilder<'b, ()>,), Output = ()>> as core::ops::function::FnOnce<(&mut rustc_errors::diagnostic_builder::DiagnosticBuilder<()>,)>>::call_once
        53: rustc_middle::lint::struct_lint_level::struct_lint_level_impl::<&str>
        54: <dyn rustc_hir_analysis::astconv::AstConv>::maybe_lint_bare_trait
        55: <dyn rustc_hir_analysis::astconv::AstConv>::ast_ty_to_ty_inner
        56: <dyn rustc_hir_analysis::astconv::AstConv>::ty_of_fn
        57: rustc_hir_analysis::collect::fn_sig
        58: rustc_query_impl::plumbing::__rust_begin_short_backtrace::<rustc_query_impl::query_impl::fn_sig::dynamic_query::{closure#2}::{closure#0}, rustc_middle::query::erase::Erased<[u8; 24]>>
        59: <rustc_query_impl::query_impl::fn_sig::dynamic_query::{closure#2} as core::ops::function::FnOnce<(rustc_middle::ty::context::TyCtxt, rustc_span::def_id::DefId)>>::call_once
        60: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::DynamicConfig<rustc_query_system::query::caches::DefIdCache<rustc_middle::query::erase::Erased<[u8; 24]>>, false, false, false>, rustc_query_impl::plumbing::QueryCtxt, false>
        61: rustc_query_impl::query_impl::fn_sig::get_query_non_incr::__rust_end_short_backtrace
        62: <rustc_hir_analysis::collect::CollectItemTypesVisitor as rustc_hir::intravisit::Visitor>::visit_trait_item
        63: rustc_hir_analysis::collect::collect_mod_item_types
        64: rustc_query_impl::plumbing::__rust_begin_short_backtrace::<rustc_query_impl::query_impl::collect_mod_item_types::dynamic_query::{closure#2}::{closure#0}, rustc_middle::query::erase::Erased<[u8; 0]>>
        65: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::DynamicConfig<rustc_query_system::query::caches::DefaultCache<rustc_span::def_id::LocalModDefId, rustc_middle::query::erase::Erased<[u8; 0]>>, false, false, false>, rustc_query_impl::plumbing::QueryCtxt, false>
        66: rustc_query_impl::query_impl::collect_mod_item_types::get_query_non_incr::__rust_end_short_backtrace
        67: rustc_hir_analysis::check_crate
        68: rustc_interface::passes::analysis
        69: rustc_query_impl::plumbing::__rust_begin_short_backtrace::<rustc_query_impl::query_impl::analysis::dynamic_query::{closure#2}::{closure#0}, rustc_middle::query::erase::Erased<[u8; 1]>>
        70: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::DynamicConfig<rustc_query_system::query::caches::SingleCache<rustc_middle::query::erase::Erased<[u8; 1]>>, false, false, false>, rustc_query_impl::plumbing::QueryCtxt, false>
        71: rustc_query_impl::query_impl::analysis::get_query_non_incr::__rust_end_short_backtrace
        72: rustc_interface::interface::run_compiler::<core::result::Result<(), rustc_span::ErrorGuaranteed>, rustc_driver_impl::run_compiler::{closure#0}>::{closure#0}
        73: std::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface::util::run_in_thread_with_globals<rustc_interface::util::run_in_thread_pool_with_globals<rustc_interface::interface::run_compiler<core::result::Result<(), rustc_span::ErrorGuaranteed>, rustc_driver_impl::run_compiler::{closure#0}>::{closure#0}, core::result::Result<(), rustc_span::ErrorGuaranteed>>::{closure#0}, core::result::Result<(), rustc_span::ErrorGuaranteed>>::{closure#0}::{closure#0}, core::result::Result<(), rustc_span::ErrorGuaranteed>>
        74: <<std::thread::Builder>::spawn_unchecked_<rustc_interface::util::run_in_thread_with_globals<rustc_interface::util::run_in_thread_pool_with_globals<rustc_interface::interface::run_compiler<core::result::Result<(), rustc_span::ErrorGuaranteed>, rustc_driver_impl::run_compiler::{closure#0}>::{closure#0}, core::result::Result<(), rustc_span::ErrorGuaranteed>>::{closure#0}, core::result::Result<(), rustc_span::ErrorGuaranteed>>::{closure#0}::{closure#0}, core::result::Result<(), rustc_span::ErrorGuaranteed>>::{closure#1} as core::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
        75: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
                   at /rustc/a58ec8ff03b3269b20104eb7eae407be48ab95a7/library/alloc/src/boxed.rs:2016:9
        76: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
                   at /rustc/a58ec8ff03b3269b20104eb7eae407be48ab95a7/library/alloc/src/boxed.rs:2016:9
        77: std::sys::pal::unix::thread::Thread::new::thread_start
                   at /rustc/a58ec8ff03b3269b20104eb7eae407be48ab95a7/library/std/src/sys/pal/unix/thread.rs:108:17
        78: <unknown>
        79: <unknown>
  --> /tmp/icemaker_global_tempdir.yPYGjh9iJjgj/rustc_testrunner_tmpdir_reporting.YjRXwTSsOKW4/mvce.rs:4:5
   |
4  |     fn f(a: A) -> A;
   |     ^^^^^^^^^^^^^^^^

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.77.0-nightly (a58ec8ff0 2024-01-22) running on x86_64-unknown-linux-gnu

query stack during panic:
end of query stack
error: aborting due to 1 previous error; 4 warnings emitted

For more information about this error, try `rustc --explain E0391`.

```

</p>
</details>

### LINKED ISSUE #120482: ICE: error[E0782]: trait objects must include the `dyn` keyword
auto-reduced (treereduce-rust):
````rust
#![feature(object_safe_for_dispatch)]

trait B {
    fn bar(&self, x: &Self);
}

trait A {
    fn g(new: B) -> B;
}

fn main() {}
````

original:
````rust
// revisions: old new
//[old] edition:2015
//[new] edition:2021
trait B { fn bar(&self, x: &Self); }
//~^ ERROR the trait `A` cannot be made into an object
// revisions: old new
//[old]~| WARN trait objects without an explicit `dyn` are deprecated
//[old]~| WARN trait objects without an explicit `dyn` are deprecated
//[old]~| WARN this is accepted in the current edition
// other object safety *hard errors* to be suppressed, because we currently
//[old]~| WARN this is accepted in the current edition
trait A { fn g(new: B) -> B; }
//~^ ERROR the trait `B` cannot be made into an object
//[old]~| WARN trait objects without an explicit `dyn` are deprecated
//[old]~| WARN trait objects without an explicit `dyn` are deprecated
//[old]~| WARN trait objects without an explicit `dyn` are deprecated
//[old]~| WARN this is accepted in the current edition
//[old]~| WARN this is accepted in the current edition
//[old]~| WARN this is accepted in the current edition
fn main() {}

````

Version information
````
rustc 1.77.0-nightly (af08c64e3 2024-01-29)
binary: rustc
commit-hash: af08c64e3800fd15f0afdb8651de8fa7dacc0026
commit-date: 2024-01-29
host: x86_64-unknown-linux-gnu
release: 1.77.0-nightly
LLVM version: 17.0.6

````

Command:
`/home/matthias/.rustup/toolchains/master/bin/rustc -Zcrate-attr=feature(object_safe_for_dispatch) --edition=2021`

<details><summary><strong>Program output</strong></summary>
<p>

```
note: no errors encountered even though `span_delayed_bug` issued

note: those delayed bugs will now be shown as internal compiler errors

error: internal compiler error[E0782]: trait objects must include the `dyn` keyword
 --> /tmp/icemaker_global_tempdir.FSnI1dXGl0xd/rustc_testrunner_tmpdir_reporting.ycftxsMipEYM/mvce.rs:6:15
  |
6 |     fn g(new: B) -> B;
  |               ^
  |
  = note: `B` it is not object safe, so it can't be `dyn`
note: delayed at compiler/rustc_hir_analysis/src/astconv/lint.rs:228:21
         0: <rustc_errors::DiagCtxtInner>::emit_diagnostic
         1: <rustc_errors::DiagCtxtInner>::emit_stashed_diagnostics
         2: <rustc_errors::DiagCtxt>::print_error_count
         3: <rustc_session::session::Session>::finish_diagnostics
         4: rustc_interface::interface::run_compiler::<core::result::Result<(), rustc_span::ErrorGuaranteed>, rustc_driver_impl::run_compiler::{closure#0}>::{closure#0}
         5: std::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface::util::run_in_thread_with_globals<rustc_interface::util::run_in_thread_pool_with_globals<rustc_interface::interface::run_compiler<core::result::Result<(), rustc_span::ErrorGuaranteed>, rustc_driver_impl::run_compiler::{closure#0}>::{closure#0}, core::result::Result<(), rustc_span::ErrorGuaranteed>>::{closure#0}, core::result::Result<(), rustc_span::ErrorGuaranteed>>::{closure#0}::{closure#0}, core::result::Result<(), rustc_span::ErrorGuaranteed>>
         6: <<std::thread::Builder>::spawn_unchecked_<rustc_interface::util::run_in_thread_with_globals<rustc_interface::util::run_in_thread_pool_with_globals<rustc_interface::interface::run_compiler<core::result::Result<(), rustc_span::ErrorGuaranteed>, rustc_driver_impl::run_compiler::{closure#0}>::{closure#0}, core::result::Result<(), rustc_span::ErrorGuaranteed>>::{closure#0}, core::result::Result<(), rustc_span::ErrorGuaranteed>>::{closure#0}::{closure#0}, core::result::Result<(), rustc_span::ErrorGuaranteed>>::{closure#1} as core::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
         7: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
                   at /rustc/af08c64e3800fd15f0afdb8651de8fa7dacc0026/library/alloc/src/boxed.rs:2015:9
         8: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
                   at /rustc/af08c64e3800fd15f0afdb8651de8fa7dacc0026/library/alloc/src/boxed.rs:2015:9
         9: std::sys::pal::unix::thread::Thread::new::thread_start
                   at /rustc/af08c64e3800fd15f0afdb8651de8fa7dacc0026/library/std/src/sys/pal/unix/thread.rs:108:17
        10: <unknown>
        11: <unknown>
 --> /tmp/icemaker_global_tempdir.FSnI1dXGl0xd/rustc_testrunner_tmpdir_reporting.ycftxsMipEYM/mvce.rs:6:15
  |
6 |     fn g(new: B) -> B;
  |               ^
help: use a new generic type parameter, constrained by `B`
  |
6 |     fn g<T: B>(new: T) -> B;
  |         ++++++      ~
help: you can also use an opaque type, but users won't be able to specify the type parameter when calling the `fn`, having to rely exclusively on type inference
  |
6 |     fn g(new: impl B) -> B;
  |               ++++

error: internal compiler error[E0782]: trait objects must include the `dyn` keyword
 --> /tmp/icemaker_global_tempdir.FSnI1dXGl0xd/rustc_testrunner_tmpdir_reporting.ycftxsMipEYM/mvce.rs:6:21
  |
6 |     fn g(new: B) -> B;
  |                     ^
  |
note: delayed at compiler/rustc_hir_analysis/src/astconv/lint.rs:228:21
         0: <rustc_errors::DiagCtxtInner>::emit_diagnostic
         1: <rustc_errors::DiagCtxtInner>::emit_stashed_diagnostics
         2: <rustc_errors::DiagCtxt>::print_error_count
         3: <rustc_session::session::Session>::finish_diagnostics
         4: rustc_interface::interface::run_compiler::<core::result::Result<(), rustc_span::ErrorGuaranteed>, rustc_driver_impl::run_compiler::{closure#0}>::{closure#0}
         5: std::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface::util::run_in_thread_with_globals<rustc_interface::util::run_in_thread_pool_with_globals<rustc_interface::interface::run_compiler<core::result::Result<(), rustc_span::ErrorGuaranteed>, rustc_driver_impl::run_compiler::{closure#0}>::{closure#0}, core::result::Result<(), rustc_span::ErrorGuaranteed>>::{closure#0}, core::result::Result<(), rustc_span::ErrorGuaranteed>>::{closure#0}::{closure#0}, core::result::Result<(), rustc_span::ErrorGuaranteed>>
         6: <<std::thread::Builder>::spawn_unchecked_<rustc_interface::util::run_in_thread_with_globals<rustc_interface::util::run_in_thread_pool_with_globals<rustc_interface::interface::run_compiler<core::result::Result<(), rustc_span::ErrorGuaranteed>, rustc_driver_impl::run_compiler::{closure#0}>::{closure#0}, core::result::Result<(), rustc_span::ErrorGuaranteed>>::{closure#0}, core::result::Result<(), rustc_span::ErrorGuaranteed>>::{closure#0}::{closure#0}, core::result::Result<(), rustc_span::ErrorGuaranteed>>::{closure#1} as core::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
         7: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
                   at /rustc/af08c64e3800fd15f0afdb8651de8fa7dacc0026/library/alloc/src/boxed.rs:2015:9
         8: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
                   at /rustc/af08c64e3800fd15f0afdb8651de8fa7dacc0026/library/alloc/src/boxed.rs:2015:9
         9: std::sys::pal::unix::thread::Thread::new::thread_start
                   at /rustc/af08c64e3800fd15f0afdb8651de8fa7dacc0026/library/std/src/sys/pal/unix/thread.rs:108:17
        10: <unknown>
        11: <unknown>
 --> /tmp/icemaker_global_tempdir.FSnI1dXGl0xd/rustc_testrunner_tmpdir_reporting.ycftxsMipEYM/mvce.rs:6:21
  |
6 |     fn g(new: B) -> B;
  |                     ^
help: `B` is not object safe, use `impl B` to return an opaque type, as long as you return a single underlying type
  |
6 |     fn g(new: B) -> impl B;
  |                     ++++

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.77.0-nightly (af08c64e3 2024-01-29) running on x86_64-unknown-linux-gnu

note: compiler flags: -Z crate-attr=feature(object_safe_for_dispatch) -Z dump-mir-dir=dir

query stack during panic:
end of query stack

```

</p>
</details>

### LINKED ISSUE #125512: ICE: `cycle detected when computing function signature of`
auto-reduced (treereduce-rust):
````rust
#![feature(object_safe_for_dispatch)]
trait B {
    fn f(a: A) -> A;
}
trait A {
    fn concrete(b: B) -> B;
}
fn main() {}


````

original:
````rust
#![feature(object_safe_for_dispatch)]
trait B { fn f(a: A) -> A; }
trait A { fn concrete(b: B) -> B; }
fn main() {}

````

Version information
````
rustc 1.80.0-nightly (9e297bf54 2024-05-24)
binary: rustc
commit-hash: 9e297bf54d31eb3b30067208ff9af4416945a2ed
commit-date: 2024-05-24
host: x86_64-unknown-linux-gnu
release: 1.80.0-nightly
LLVM version: 18.1.6

````

Command:
`/home/matthias/.rustup/toolchains/master/bin/rustc -Zunstable-options --edition=2024`

<details><summary><strong>Program output</strong></summary>
<p>

```
warning: trait `B` is never used
 --> /tmp/icemaker_global_tempdir.Y2ZB7VqiZYxB/rustc_testrunner_tmpdir_reporting.n6c2niMcV32C/mvce.rs:2:7
  |
2 | trait B {
  |       ^
  |
  = note: `#[warn(dead_code)]` on by default

warning: trait `A` is never used
 --> /tmp/icemaker_global_tempdir.Y2ZB7VqiZYxB/rustc_testrunner_tmpdir_reporting.n6c2niMcV32C/mvce.rs:5:7
  |
5 | trait A {
  |       ^

warning: 2 warnings emitted

note: no errors encountered even though delayed bugs were created

note: those delayed bugs will now be shown as internal compiler errors

error: internal compiler error[E0391]: cycle detected when computing function signature of `B::f`
 --> /tmp/icemaker_global_tempdir.Y2ZB7VqiZYxB/rustc_testrunner_tmpdir_reporting.n6c2niMcV32C/mvce.rs:3:5
  |
3 |     fn f(a: A) -> A;
  |     ^^^^^^^^^^^^^^^^
  |
note: ...which requires checking if trait `A` is object safe...
 --> /tmp/icemaker_global_tempdir.Y2ZB7VqiZYxB/rustc_testrunner_tmpdir_reporting.n6c2niMcV32C/mvce.rs:5:1
  |
5 | trait A {
  | ^^^^^^^
note: ...which requires determining object safety of trait `A`...
 --> /tmp/icemaker_global_tempdir.Y2ZB7VqiZYxB/rustc_testrunner_tmpdir_reporting.n6c2niMcV32C/mvce.rs:5:1
  |
5 | trait A {
  | ^^^^^^^
note: ...which requires computing function signature of `A::concrete`...
 --> /tmp/icemaker_global_tempdir.Y2ZB7VqiZYxB/rustc_testrunner_tmpdir_reporting.n6c2niMcV32C/mvce.rs:6:5
  |
6 |     fn concrete(b: B) -> B;
  |     ^^^^^^^^^^^^^^^^^^^^^^^
note: ...which requires checking if trait `B` is object safe...
 --> /tmp/icemaker_global_tempdir.Y2ZB7VqiZYxB/rustc_testrunner_tmpdir_reporting.n6c2niMcV32C/mvce.rs:2:1
  |
2 | trait B {
  | ^^^^^^^
note: ...which requires determining object safety of trait `B`...
 --> /tmp/icemaker_global_tempdir.Y2ZB7VqiZYxB/rustc_testrunner_tmpdir_reporting.n6c2niMcV32C/mvce.rs:2:1
  |
2 | trait B {
  | ^^^^^^^
  = note: ...which again requires computing function signature of `B::f`, completing the cycle
note: cycle used when checking that `B` is well-formed
 --> /tmp/icemaker_global_tempdir.Y2ZB7VqiZYxB/rustc_testrunner_tmpdir_reporting.n6c2niMcV32C/mvce.rs:2:1
  |
2 | trait B {
  | ^^^^^^^
  = note: see https://rustc-dev-guide.rust-lang.org/overview.html#queries and https://rustc-dev-guide.rust-lang.org/query.html for more information
note: delayed at compiler/rustc_query_system/src/query/job.rs:597:16 - disabled backtrace
 --> /tmp/icemaker_global_tempdir.Y2ZB7VqiZYxB/rustc_testrunner_tmpdir_reporting.n6c2niMcV32C/mvce.rs:3:5
  |
3 |     fn f(a: A) -> A;
  |     ^^^^^^^^^^^^^^^^

error: internal compiler error[E0782]: trait objects must include the `dyn` keyword
 --> /tmp/icemaker_global_tempdir.Y2ZB7VqiZYxB/rustc_testrunner_tmpdir_reporting.n6c2niMcV32C/mvce.rs:6:20
  |
6 |     fn concrete(b: B) -> B;
  |                    ^
  |
  = note: `B` it is not object safe, so it can't be `dyn`
note: delayed at compiler/rustc_hir_analysis/src/hir_ty_lowering/lint.rs:63:17 - disabled backtrace
 --> /tmp/icemaker_global_tempdir.Y2ZB7VqiZYxB/rustc_testrunner_tmpdir_reporting.n6c2niMcV32C/mvce.rs:6:20
  |
6 |     fn concrete(b: B) -> B;
  |                    ^
help: use a new generic type parameter, constrained by `B`
  |
6 |     fn concrete<T: B>(b: T) -> B;
  |                ++++++    ~
help: you can also use an opaque type, but users won't be able to specify the type parameter when calling the `fn`, having to rely exclusively on type inference
  |
6 |     fn concrete(b: impl B) -> B;
  |                    ++++

error: internal compiler error[E0782]: trait objects must include the `dyn` keyword
 --> /tmp/icemaker_global_tempdir.Y2ZB7VqiZYxB/rustc_testrunner_tmpdir_reporting.n6c2niMcV32C/mvce.rs:6:26
  |
6 |     fn concrete(b: B) -> B;
  |                          ^
  |
note: delayed at compiler/rustc_hir_analysis/src/hir_ty_lowering/lint.rs:63:17 - disabled backtrace
 --> /tmp/icemaker_global_tempdir.Y2ZB7VqiZYxB/rustc_testrunner_tmpdir_reporting.n6c2niMcV32C/mvce.rs:6:26
  |
6 |     fn concrete(b: B) -> B;
  |                          ^
help: `B` is not object safe, use `impl B` to return an opaque type, as long as you return a single underlying type
  |
6 |     fn concrete(b: B) -> impl B;
  |                          ++++

error: internal compiler error[E0782]: trait objects must include the `dyn` keyword
 --> /tmp/icemaker_global_tempdir.Y2ZB7VqiZYxB/rustc_testrunner_tmpdir_reporting.n6c2niMcV32C/mvce.rs:3:13
  |
3 |     fn f(a: A) -> A;
  |             ^
  |
  = note: `A` it is not object safe, so it can't be `dyn`
note: delayed at compiler/rustc_hir_analysis/src/hir_ty_lowering/lint.rs:63:17 - disabled backtrace
 --> /tmp/icemaker_global_tempdir.Y2ZB7VqiZYxB/rustc_testrunner_tmpdir_reporting.n6c2niMcV32C/mvce.rs:3:13
  |
3 |     fn f(a: A) -> A;
  |             ^
help: use a new generic type parameter, constrained by `A`
  |
3 |     fn f<T: A>(a: T) -> A;
  |         ++++++    ~
help: you can also use an opaque type, but users won't be able to specify the type parameter when calling the `fn`, having to rely exclusively on type inference
  |
3 |     fn f(a: impl A) -> A;
  |             ++++

error: internal compiler error[E0782]: trait objects must include the `dyn` keyword
 --> /tmp/icemaker_global_tempdir.Y2ZB7VqiZYxB/rustc_testrunner_tmpdir_reporting.n6c2niMcV32C/mvce.rs:3:19
  |
3 |     fn f(a: A) -> A;
  |                   ^
  |
note: delayed at compiler/rustc_hir_analysis/src/hir_ty_lowering/lint.rs:63:17 - disabled backtrace
 --> /tmp/icemaker_global_tempdir.Y2ZB7VqiZYxB/rustc_testrunner_tmpdir_reporting.n6c2niMcV32C/mvce.rs:3:19
  |
3 |     fn f(a: A) -> A;
  |                   ^
help: `A` is not object safe, use `impl A` to return an opaque type, as long as you return a single underlying type
  |
3 |     fn f(a: A) -> impl A;
  |                   ++++

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: please make sure that you have updated to the latest nightly

note: rustc 1.80.0-nightly (9e297bf54 2024-05-24) running on x86_64-unknown-linux-gnu

note: compiler flags: -Z unstable-options -Z dump-mir-dir=dir

query stack during panic:
end of query stack

```

</p>
</details>

@rustbot label +F-object_safe_for_dispatch

### LINKED ISSUE #127548: Traits in type position should be a fatal error in ≥2018 editions
### Code

```Rust
struct Foo {
    a: Fn(),
    b: Fn(),
}
```

### Current output

```Shell
error[E0277]: the size for values of type `(dyn Fn() + 'static)` cannot be known at compilation time
 --> src/lib.rs:2:8
  |
2 |     a: Fn(),
  |        ^^^^ doesn't have a size known at compile-time
  |
  = help: the trait `Sized` is not implemented for `(dyn Fn() + 'static)`
  = note: only the last field of a struct may have a dynamically sized type
  = help: change the field's type to have a statically known size
help: borrowed types always have a statically known size
  |
2 |     a: &Fn(),
  |        +
help: the `Box` type always has a statically known size and allocates its contents in the heap
  |
2 |     a: Box<Fn()>,
  |        ++++    +

error[E0782]: trait objects must include the `dyn` keyword
 --> src/lib.rs:2:8
  |
2 |     a: Fn(),
  |        ^^^^
  |
help: add `dyn` keyword before this trait
  |
2 |     a: dyn Fn(),
  |        +++

error[E0782]: trait objects must include the `dyn` keyword
 --> src/lib.rs:3:8
  |
3 |     b: Fn(),
  |        ^^^^
  |
help: add `dyn` keyword before this trait
  |
3 |     b: dyn Fn(),
  |        +++
```

### Desired output

There are two fixes that I think would be wise here.

1. Most importantly, the E0277 should not occur; the compiler should not 
attempt to continue interpreting the program as if it were in edition 2015. Or, at a minimum, the E0782 should appear *first*.

2. E0782 could be better expressed, in the modern perspective, as “expected type, found trait”. Don't bring up trait objects at all until the author writes `dyn`.

### Rationale and extra context

Today, when a newcomer writes a trait in a type position, it most often means they're confused about what the difference is, not that they wanted a trait object and need to be taught the new syntax. The whole point of adding `dyn` to Rust's syntax was to remove that easy confusion. Therefore, the compiler should stop making the assumption whatsoever that the author of the code meant a trait object.

This will have the further advantage that newcomers will not be confronted with errors about `Sized` when they probably didn't even mean to use any DST.

### Rust Version

```Shell
rustc 1.81.0-nightly (ba1d7f4a0 2024-06-29)
binary: rustc
commit-hash: ba1d7f4a083e6402679105115ded645512a7aea8
commit-date: 2024-06-29
host: x86_64-apple-darwin
release: 1.81.0-nightly
LLVM version: 18.1.7
```

### PR DESCRIPTION
**Pull request by VulnBandit**
Fixes #127548

When you use a trait as a type, the compiler automatically assumes you meant to use a trait object, which is not always the case.
This PR fixes the bug where you don't need a trait object, so the error message was changed to:
```
error[E0782]: expected a type, found a trait
```
Also fixes some ICEs:
Fixes https://github.com/rust-lang/rust/issues/120241
Fixes https://github.com/rust-lang/rust/issues/120482
Fixes https://github.com/rust-lang/rust/issues/125512

### CODE REVIEW

**Comment by jieyouxu** [comment]
> This PR fixes the vunlnerability where you don't need a trait object

FYI the word "vunlnerability" has a specific meaning (i.e. a weakness that makes something easy to be attacked/exploited), but this PR is just trying to improve diagnostics not trying to address an exploit.

**Comment by jieyouxu** [comment]
We usually call those those "bugs" or "diagnostic issues", "vulnerability" usually indicates an exploitable weakness that has to do with security that wg-security-response would need to look at.

**Comment by lcnr** [comment]
r=me after CI

File: compiler/rustc_hir_analysis/src/hir_ty_lowering/lint.rs [hunk 1]
```diff
@@ -83,7 +86,15 @@ impl<'tcx> dyn HirTyLowerer<'tcx> + '_ {
             // Check if the impl trait that we are considering is an impl of a local trait.
             self.maybe_suggest_blanket_trait_impl(self_ty, &mut diag);
             self.maybe_suggest_assoc_ty_bound(self_ty, &mut diag);
-            diag.stash(self_ty.span, StashKey::TraitMissingMethod);
+            if let Some(mut sugg) =
```
Comment (lcnr) [inline compiler/rustc_hir_analysis/src/hir_ty_lowering/lint.rs:89]: please leave a comment here explaining why we need to do this. afaik it's for the case where there's something that could be both an associated type or a trait object

Comment (VulnBandit) [reply compiler/rustc_hir_analysis/src/hir_ty_lowering/lint.rs:91]: Done. Workflow needs approval again
