### PR TITLE
resolve: Fix unused import false positive with `item_like_imports`

### LINKED ISSUE #36249: unused_imports false positive in reexport (using `pub_restricted, item_like_imports`)
```Rust
#![feature(pub_restricted, item_like_imports)]

mod rw {
	trait SectionWrite {}
	
    // private prelude for submodules
	mod prelude {
		pub(super) use super::SectionWrite;
	}
	
	mod foo {
		use Foo;
		use rw::prelude::*;

		impl SectionWrite for Foo {}
	}
}

#[derive(Debug)]
struct Foo;

fn main() {
	println!("{:?}", Foo);
}

```

```
warning: unused import, #[warn(unused_imports)] on by default
 --> test_case.rs:7:18
  |
7 | 		pub(super) use super::SectionWrite;
  | 		               ^^^^^^^^^^^^^^^^^^^
```

Using `rustc 1.13.0-nightly (ef9786ce0 2016-09-02)`, which has the `item_like_imports` feature.

### PR DESCRIPTION
**Pull request by jseyfried**
Fixes #36249.
r? @nrc

### CODE REVIEW

File: src/librustc_resolve/lib.rs [hunk 1]
```diff
@@ -1063,7 +1056,7 @@ pub struct Resolver<'a> {
     pub maybe_unused_trait_imports: NodeSet,
 
     privacy_errors: Vec<PrivacyError<'a>>,
-    ambiguity_errors: Vec<(Span, Name, &'a NameBinding<'a>)>,
+    ambiguity_errors: Vec<(Span, Name, &'a NameBinding<'a>, &'a NameBinding<'a>)>,
```
Comment (nrc) [inline src/librustc_resolve/lib.rs]: This is getting complex enough that it should be factored out into a struct

**Comment by nrc** [comment]
r=me with a struct
