### PR TITLE
Properly check for builtin derived code

### LINKED ISSUE #108122: ICE in unaligned references MIR check
https://miri.saethlin.dev/logs/hdf5-derive/0.8.1.html

### Meta

```
rustc 1.69.0-nightly (e7acd078f 2023-02-09) running on x86_64-unknown-linux-gnu
```

### Error output

```
thread 'rustc' panicked at 'internal error: entered unreachable code', compiler/rustc_mir_transform/src/check_packed_ref.rs:50:21
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
thread 'rustc' panicked at 'internal error: entered unreachable code', compiler/rustc_mir_transform/src/check_packed_ref.rs:50:21
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.69.0-nightly (e7acd078f 2023-02-09) running on x86_64-unknown-linux-gnu

note: compiler flags: -C embed-bitcode=no -C debuginfo=2 -C linker=clang -Z randomize-layout -C opt-level=0 -C debuginfo=0 -Z miri-disable-isolation -Z miri-ignore-leaks -Z miri-panic-on-unsupported

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [mir_const] preparing `_IMPL_H5TYPE_FOR_P1::<impl at tests/test.rs:36:10: 36:16>::type_descriptor` for borrow checking
#1 [mir_promoted] processing MIR for `_IMPL_H5TYPE_FOR_P1::<impl at tests/test.rs:36:10: 36:16>::type_descriptor`
end of query stack
thread 'rustc' panicked at 'internal error: entered unreachable code', compiler/rustc_mir_transform/src/check_packed_ref.rs:50:21

error: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.69.0-nightly (e7acd078f 2023-02-09) running on x86_64-unknown-linux-gnu

note: compiler flags: -C embed-bitcode=no -C debuginfo=2 -C linker=clang -Z randomize-layout -C opt-level=0 -C debuginfo=0 -Z miri-disable-isolation -Z miri-ignore-leaks -Z miri-panic-on-unsupported

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [mir_const] preparing `_IMPL_H5TYPE_FOR_P2::<impl at tests/test.rs:43:10: 43:16>::type_descriptor` for borrow checking
#1 [mir_promoted] processing MIR for `_IMPL_H5TYPE_FOR_P2::<impl at tests/test.rs:43:10: 43:16>::type_descriptor`
end of query stack
```

</p>
</details>

### PR DESCRIPTION
**Pull request by clubby789**
Fixes #108122

### CODE REVIEW

**Comment by compiler-errors** [comment]
Should this be a rustc_* attr rather than have its own feature gate?

**Comment by clubby789** [comment]
I didn't make it `rustc_` since the macros are technically (at least at the place where the `allow_internal_unstable` is) part of std rather than rustc but I'll move it if you think that makes more sense

File: library/core/src/clone.rs [hunk 1]
```diff
@@ -140,7 +140,7 @@ pub trait Clone: Sized {
 /// Derive macro generating an impl of the trait `Clone`.
 #[rustc_builtin_macro]
```
Comment (compiler-errors) [inline library/core/src/clone.rs:141]: also, what's the difference between this attr and the one you're adding?

Comment (compiler-errors) [reply library/core/src/clone.rs:141]: all of the macros you've tagged with this new attribute are already tagged with this one -- is there a distinction that this new macro is making?

Comment (clubby789) [reply library/core/src/clone.rs:141]: This is specifically for derive macros - if we just checked `rustc_builtin_macro`, I believe illegal references could be made in `println!()` etc.
I didn't see this before though - maybe checking for *both* `automatically_derived` and `rustc_builtin_macro` would be a quicker solution to this instead of a new attr.

**Comment by clubby789** [comment]
Updated to check for an `automatically_derived` trait impl that comes from an expansion of a derive macro annotated `rustc_builtin_macro`
