### PR TITLE
Fix for "ambiguous associated type" issue with ATBs

### LINKED ISSUE #61752: `associated_type_bounds`: errors with ambiguous associated type
I think I found a bug with associated type bounds! #52662

https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=28d566e7244a0b3ad21b73e31418894d
```rust
#![feature(associated_type_bounds)]

trait Foo {
    type Bar;
}

fn works<F: Foo>() where F::Bar: Copy {}

// This should be fine, but I get `error[E0221]` instead
fn breaks<F: Foo<Bar: Foo>>() where F::Bar: Copy {}
```
This is the exact same error you get when you do this
```rust
trait Foo<T> {
    type Bar;
}

fn breaks<F: Foo<String> + Foo<u32>>() where F::Bar: Copy {}
```
Because Rust can't tell which `Foo::<_>::Bar` you mean, but in the case of `associated_type_bounds`, there is no ambiguity, which makes this error confusing.

### PR DESCRIPTION
**Pull request by alexreg**
Fixes #61752.

r? @nikomatsakis

CC @Centril

### CODE REVIEW

**Comment by alexreg** [comment]
I'm not sure of the underlying motivation for the actual fix (2nd commit)... having diagnosed the problem, I addressed it very much "head on". If this is the right solution, then great. Either way, I should probably add a little explainer comment to the `predicates_from_bound` function. Let me know your thoughts, @nikomatsakis.

File: src/librustc_typeck/collect.rs [hunk 1]
```diff
@@ -2211,7 +2212,12 @@ fn predicates_from_bound<'tcx>(
     match *bound {
         hir::GenericBound::Trait(ref tr, hir::TraitBoundModifier::None) => {
             let mut bounds = Bounds::default();
-            let (pred, _) = astconv.instantiate_poly_trait_ref(tr, param_ty, &mut bounds);
+            let (pred, _) = astconv.instantiate_poly_trait_ref(
+                tr,
+                param_ty,
+                &mut bounds,
+                false,
```
Comment (Centril) [inline src/librustc_typeck/collect.rs]: Would be good to leave a comment for this one since it's the only case where `include_atb == false`.

File: src/librustc_privacy/lib.rs [hunk 2]
```diff
@@ -1053,14 +1053,18 @@ impl<'a, 'tcx> Visitor<'tcx> for TypePrivacyVisitor<'a, 'tcx> {
...
+                if self.visit_trait(*trait_predicate.skip_binder()) {
+                    return;
+                }
             }
+
             for (poly_predicate, _) in bounds.projection_bounds {
                 let tcx = self.tcx;
                 if self.visit(poly_predicate.skip_binder().ty) ||
-                   self.visit_trait(poly_predicate.skip_binder().projection_ty.trait_ref(tcx)) {
+                self.visit_trait(poly_predicate.skip_binder().projection_ty.trait_ref(tcx)) {
```
Comment (Centril) [inline src/librustc_privacy/lib.rs]: Indentation seems weird here.

File: src/librustc_typeck/astconv.rs [hunk 3]
```diff
@@ -1241,24 +1245,20 @@ impl<'o, 'tcx> dyn AstConv<'tcx> + 'o {
         let dummy_self = self.tcx().types.trait_object_dummy_self;
         // FIXME: we want to avoid collecting into a `Vec` here, but simply cloning the iterator is
```
Comment (Centril) [inline src/librustc_typeck/astconv.rs]: FIXME here is resolved now?

File: src/librustc_privacy/lib.rs (hunk 2 above)
Comment (alexreg) [reply src/librustc_privacy/lib.rs]: Double tab indent instead? Not sure.

File: src/librustc_typeck/astconv.rs (hunk 3 above)
Comment (alexreg) [reply src/librustc_typeck/astconv.rs]: Yeah, heh. Purely by accident.

File: src/librustc_privacy/lib.rs (hunk 2 above)
Comment (Centril) [reply src/librustc_privacy/lib.rs]: This is how rustfmt does it:
```rust
fn foo() {
    if my_very_long_function_oh_my_gosh_it_is_so_long()
        && and_this_one_will_overflow_the_maximum_amount()
    {}
}
```

Comment (alexreg) [reply src/librustc_privacy/lib.rs]: Thanks.

File: src/librustc_typeck/collect.rs (hunk 1 above)
Comment (alexreg) [reply src/librustc_typeck/collect.rs]: Yep. Will do so once I consult with Niko, per the above comment. :-)

Comment (nikomatsakis) [reply src/librustc_typeck/collect.rs]: OK, so, it was not very obvious to me why passing `false` here makes sense -- but I believe it is true, given where this function is called from. Perhaps we can adust the name. Essentially, it only makes sense in those cases where we are assembling the bounds only for the purpose of resolving `T::Bar` to a specific trait. 

We definitely need to adjust the names and apply some comments -- but not just here, also to the callers. The key point is that we are in a context where we are trying to resolve `T::Bar`, and we only want *just as many* predicates as we need to do that (to avoid artificial cycles).

I'm not sure if adding this `false` parameter is the best approach or not, but I don't immediately see a better one.

Comment (nikomatsakis) [reply src/librustc_typeck/collect.rs]: (I just spent a while tracing back through the code, checking on things)

File: src/librustc_typeck/astconv.rs [hunk 4]
```diff
@@ -778,11 +778,12 @@ impl<'o, 'tcx> dyn AstConv<'tcx> + 'o {
     /// The given trait-ref must actually be a trait.
     pub(super) fn instantiate_poly_trait_ref_inner(&self,
         trait_ref: &hir::TraitRef,
+        span: Span,
         self_ty: Ty<'tcx>,
         bounds: &mut Bounds<'tcx>,
         speculative: bool,
         include_atb: bool,
-    ) -> (ty::PolyTraitRef<'tcx>, Option<Vec<Span>>)
+    ) -> Option<Vec<Span>>
```
Comment (nikomatsakis) [inline src/librustc_typeck/astconv.rs]: this refactoring looks good!

**Review by nikomatsakis — CHANGES_REQUESTED** [review]
So I spent some more time looking into this PR this morning. I actually think this is the wrong approach. The problem seems to be this:

The functon `type_param_predicates` in collect.rs is meant to return *only the predicates that apply to the type parameter with the given def-id*. i.e., if you have the defid for `T`, it should return predicates like `T: Foo` and `T: Bar`. But today, if you have `T: Foo<Bar: Baz>`, it is also returning `<T as Foo>::Bar: Baz`. This then confuses the code in `find_bound_for_assoc_item` in `astconv.rs` down the line, which assumes that the self-type is always just `T`. Threading this boolean flag *works* to suppress that confusion, but it's not my preferred approach.

I think what I would rather do is just add a filtering step right [after this line](https://github.com/rust-lang/rust/blob/1b1b538843503568994c7ef37ea8206f0ee3c2e4/src/librustc_typeck/collect.rs#L330), similar to what you find in [the `FnCtxt` code](https://github.com/rust-lang/rust/blob/1b1b538843503568994c7ef37ea8206f0ee3c2e4/src/librustc_typeck/check/mod.rs#L2018).

Also, I think we should add a comment to `type_param_predicates` and `get_type_parameter_bounds` clarifying that they take a type parameter and return only the predicates that apply to that. I might push a comment or two to that effect to your branch.

**Comment by nikomatsakis** [comment]
An alternative might be to add filtering around [this line](https://github.com/rust-lang/rust/blob/1b1b538843503568994c7ef37ea8206f0ee3c2e4/src/librustc_typeck/astconv.rs#L1500) -- i.e., at the place where `get_type_parameter_bounds` is called. In that case, the contract would not be to return *just bounds* like `X: Foo`, but rather *some superset including those bounds*.

**Comment by nikomatsakis** [comment]
and hence you would want to adjust the comments accordingly

**Comment by Alexendoo** [comment]
Ping from triage, any updates? @alexreg

**Comment by alexreg** [comment]
@Alexendoo Yeah sorry, I meant to get around to this, but I will finally in the next day or two.

**Comment by JohnCSimon** [comment]
Ping from triage. 
@alexreg Hi! Any more progress on this?

**Comment by alexreg** [comment]
@JohnCSimon Ah sorry. Later today, I'm pretty confident!

**Comment by alexreg** [comment]
@nikomatsakis Tried your first approach, since that made perfect sense to me, while I didn't quite get your alternative one. Hope that's alright.

@varkor Pending a rebase and adding a test for #61738, would you mind kindly reviewing this in Niko's absence? I think you know this part of the compiler reasonably well.

File: src/test/ui/associated-type-bounds/ambiguous-associated-type.rs [hunk 5]
```diff
@@ -0,0 +1,12 @@
+// build-pass (FIXME(62277): could be check-pass?)
```
Comment (Centril) [inline src/test/ui/associated-type-bounds/ambiguous-associated-type.rs]:
```suggestion
// check-pass
```

This is just about type checking :)

File: src/test/ui/associated-type-bounds/issue-61752.rs [hunk 6]
```diff
@@ -0,0 +1,24 @@
+// run-pass
```
Comment (Centril) [inline src/test/ui/associated-type-bounds/issue-61752.rs]:
```suggestion
// check-pass
```
Same; you never test the dynamic semantics. :)

**Review by nikomatsakis — APPROVED** [review]

**Comment by alexreg** [comment]
Thanks @nikomatsakis!
