### PR TITLE
ThreadId generation fallback path: avoid spurious yields

### LINKED ISSUE #4737: Unexpected non-determinism with thread::scope (but only on some targets)
The following test should always pass with `-Zmiri-fixed-schedule`:
```rust
use std::thread;

fn main() {
    thread::scope(|s| {
        s.spawn(|| {
            thread::yield_now();
            std::process::abort();
        });
        s.spawn(|| {
            std::process::exit(0);
        });
    });
}
```
We will always run the first thread, yield, go to the second thread, and exit, therefore never reaching the `abort` (which would fail the test). On x86_64-unknown-linux-gnu, i686-unknown-linux-gnu, and armv7-unknown-linux-gnueabihf, this indeed behaves as expected.

However, on mips-unknown-linux-gnu, the test sometimes (for around 33% of the seeds) does hit the `abort` and fail. I have no idea how that is possible. This behavior also only very recently started with a rustup covering this upstream diff: https://github.com/rust-lang/rust/compare/1eb0657f78777f0b4d6bcc49c126d5d35212cae5...3ff30e7eafc1da7104c3960187d17939172428ed. That includes https://github.com/rust-lang/rust/pull/148765 which is described as merely moving code around but maybe something changed somewhere...? It also includes https://github.com/rust-lang/rust/pull/144465 which is more likely to be the culprit as that mips target does not have 64bit atomics. Cc @joboet @orlp

### PR DESCRIPTION
**Pull request by RalfJung**
Fixes https://github.com/rust-lang/miri/issues/4737
Alternative to https://github.com/rust-lang/rust/pull/149476
Cc @orlp @joboet

### CODE REVIEW

File: library/std/src/thread/id.rs [hunk 1]
```diff
@@ -70,7 +70,9 @@ impl ThreadId {
 
                 // Acquire lock.
                 let mut spin = 0;
-                while COUNTER_LOCKED.compare_exchange_weak(false, true, Ordering::Acquire, Ordering::Relaxed).is_err() {
+                // Miri doesn't like it when we yield here as it interferes with deterministically
+                // scheduling threads, so use `compare_exchange` to avoid spurious yields.
+                while COUNTER_LOCKED.compare_exchange(false, true, Ordering::Acquire, Ordering::Relaxed).is_err() {
```
Comment (joboet) [inline library/std/src/thread/id.rs]: In this case, I'd use `swap(true)` here, as it can generate better assembly on platforms that don't have a CAS instruction, but do have swap (like RISC-V, even though it always has 64-bit atomics if I understand correctly).

**Review by joboet — APPROVED** [review]
Looks fine, r=me with or without the nit.

*[View changes since this review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/rust/149481/91ab3083bb2d163dfa408033ac01c73970630cf9..bc595576a76bfebd5cc79de576b54fa3badb6914)*

**Comment by joboet** [comment]
Yes, exactly!
@bors r+

**Comment by orlp** [comment]
@RalfJung I had already spotted another bug, but yes that is also an issue, let me fix that.
