### PR TITLE
Normalize types when deducing closure signature from supertraits

### LINKED ISSUE #104025: False E0644 closure/generator type that references itself; new in nightly-2022-11-05
I tried this code with `cargo +nightly-2022-11-05 check`:

```rust
pub trait Fn0: Fn() -> Self::Out {
    type Out;
}

impl<F: Fn() -> ()> Fn0 for F {
    type Out = ();
}

pub fn closure_typer(_: impl Fn0) {}

fn main() {
    closure_typer(move || {});
}
```

I expected to see this happen: successful compilation

Instead, this happened:

```rust
error[E0644]: closure/generator type that references itself
  --> src/bin/cyclic-repro.rs:13:19
   |
13 |     closure_typer(move || {});
   |                   ^^^^^^^^^^ cyclic type of infinite size
   |
   = note: closures cannot capture themselves or take themselves as argument;
           this error may be the result of a recent compiler bug-fix,
           see issue #46062 <https://github.com/rust-lang/rust/issues/46062>
           for more information
```

It compiles successfully with the preceding nightly, `cargo +nightly-2022-11-04 check`, and stable 1.65.0.

### Meta

`rustc --version --verbose`:
```
rustc 1.67.0-nightly (09508489e 2022-11-04)
binary: rustc
commit-hash: 09508489efc223287731fe8abbd2a81bbf7adf8e
commit-date: 2022-11-04
host: x86_64-apple-darwin
release: 1.67.0-nightly
LLVM version: 15.0.4
```

To be clear, this is the nightly I installed with `rustup install nightly-2022-11-05`. I assume it's normal for the commit date to be a day earlier, but I haven't specifically noticed that before.

### Related

This sounds extremely similar to #97680, but that bug was reported months earlier whereas this one appeared today. My original discovery involved [async fn traits](https://docs.rs/async_fn_traits/0.1.1/async_fn_traits/trait.AsyncFn0.html) too, but I reduced it to an example which contains only a closure.

@rustbot label regression-from-stable-to-nightly A-closures

### PR DESCRIPTION
**Pull request by compiler-errors**
Elaborated supertraits should be normalized, since there's no guarantee they don't contain projections :sweat_smile: 

Fixes #104025
r? types

### CODE REVIEW

File: compiler/rustc_hir_typeck/src/closure.rs [hunk 1]
```diff
@@ -241,9 +242,12 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
             if expected_sig.is_none()
                 && let ty::PredicateKind::Projection(proj_predicate) = bound_predicate.skip_binder()
             {
-                expected_sig = self.deduce_sig_from_projection(
+                expected_sig = self.normalize_associated_types_in(
```
Comment (compiler-errors) [inline compiler/rustc_hir_typeck/src/closure.rs:245]: Fold after `deduce_sig_from_projection` so we only need to normalize the types that end up in the closure sig.
