### PR TITLE
Include nonexported macro_rules! macros in the doctest target

### LINKED ISSUE #88038: Doctests don't run on nonexported `macro_rules!` macros
At present, doctests aren't run on `macro_rules!` macros that are not annotated with `#[macro_export]`. After #88019, it will become possible to fix this problem. However, doing so will cause tests to run that were skipped previously to run, which will likely cause test failures and may mess up people's CI. It might be helpful to provide some form of warning period first.

The relevant code is here:
https://github.com/rust-lang/rust/blob/5eacec9ec7e112a0de1011519a57c45586d58414/src/librustdoc/doctest.rs#L1175-L1184

Fixing this issue technically just requires removing that special case. However, things are complicated by the fact that this will cause people's tests to suddenly fail. I'm not really sure how we should handle that. @jyn514, do you have any ideas?

### PR DESCRIPTION
**Pull request by m-ysk**
Fixes #88038 

This PR aims to include nonexported `macro_rules!` macros in the doctest target. For more details, please see the above issue.

### CODE REVIEW

**Comment by jyn514** [comment]
I'm no longer part of the rustdoc team, please don't assign me. You can use `r? rust-lang/rustdoc` to reroll high-five.

**Comment by m-ysk** [comment]
r? rust-lang/rustdoc

File: library/core/src/internal_macros.rs [hunk 1]
```diff
@@ -190,7 +190,7 @@ macro_rules! impl_fn_for_zst {
 ///
 /// # Example
 ///
-/// ```
+/// ```ignore(cannot-test-this-because-non-exported-macro)
```
Comment (m-ysk) [inline library/core/src/internal_macros.rs:193]: I think that we have no way to run this doctest because `cfg_if!` is not exported and the doctest cannot import `cfg_if!`. Is that right?

**Review by notriddle — APPROVED** [review]

**Comment by steffahn** [comment]
This PR has a `relnotes` tag, but somehow, I can’t find anything about it in the 1.62 release notes. Is this the right place to ask about that? See also #98735, where this change is perceived as a regression (bug) due to it being undocumented.

**Comment by Mark-Simulacrum** [comment]
Probably not - could you file an issue on the release team repo for us to investigate?

**Comment by steffahn** [comment]
[This repo](https://github.com/rust-lang/release-team)? (I’m asking because there’s not too many issues over there.)
