### PR TITLE
Suggest calling method when first argument is `self`

### LINKED ISSUE #66782: Unfelpful error when trying to call member function as free function
I just spent far too long trying to figure out the problem with the following (reduced) code

```
struct X { i: isize }

impl X {
    fn a(&self, i: usize)
    { }

    fn b(&self)
    { a(self, 2) }
}
```

Which produces the error:

```
    Checking playground v0.0.1 (/playground)
error[E0425]: cannot find function `a` in this scope
 --> src/lib.rs:8:7
  |
8 |     { a(self, 2) }
  |       ^ not found in this scope

error: aborting due to previous error

For more information about this error, try `rustc --explain E0425`.
error: could not compile `playground`.

To learn more, run the command again with --verbose.
```

While I don't expect the code to compile, perhaps mention when trying to call `a(self,...)` that I should be calling `self.a(...)`?

### PR DESCRIPTION
**Pull request by VirrageS**
Closes: #66782 

I've explored different approaches for this MR but I think the most straightforward is the best one.

I've tried to find out if the methods for given type exist (to maybe have a better suggestion), but we don't collect them anywhere and collecting them is quite problematic. Moreover, collecting all the methods would require rewriting big part of the code and also could potentially include performance degradation, which I don't think is necessary for this simple case.

### CODE REVIEW

**Comment by JohnCSimon** [comment]
Ping from triage: 
@varkor can you please review this PR? Thanks.

File: src/librustc_resolve/late/diagnostics.rs [hunk 1]
```diff
@@ -253,6 +253,37 @@ impl<'a> LateResolutionVisitor<'a, '_> {
                 }
                 return (err, candidates);
             }
+
+            // Check if the first argument is `self` and suggest calling a method.
+            let mut has_self_arg = false;
+            if let PathSource::Expr(parent) = source {
+                match &parent.map(|p| &p.kind) {
+                    Some(ExprKind::Call(_, args)) if args.len() > 0 => {
+                        let mut expr_kind = &args.first().unwrap().kind;
```
Comment (varkor) [inline src/librustc_resolve/late/diagnostics.rs]: Does `&args[0].kind` not work here?

File: src/librustc_resolve/late/diagnostics.rs [hunk 2]
```diff
@@ -253,6 +253,37 @@ impl<'a> LateResolutionVisitor<'a, '_> {
...
+                        loop {
+                            match expr_kind {
+                                ExprKind::Path(_, arg_name) if arg_name.segments.len() == 1 => {
+                                    has_self_arg = arg_name.segments[0].ident.name == kw::SelfLower;
+                                    break;
+                                },
+                                ExprKind::AddrOf(_, _, expr) => { expr_kind = &expr.kind; }
```
Comment (varkor) [inline src/librustc_resolve/late/diagnostics.rs]:
```suggestion
                                ExprKind::AddrOf(_, _, expr) => expr_kind = &expr.kind,
```

File: src/librustc_resolve/late/diagnostics.rs [hunk 3]
```diff
@@ -253,6 +253,37 @@ impl<'a> LateResolutionVisitor<'a, '_> {
...
+                        }
+                    }
+                    _ => (),
+                }
+            };
+
+            if has_self_arg {
+                err.span_suggestion(
+                    span,
+                    &"try calling method instead of passing `self` as parameter",
```
Comment (varkor) [inline src/librustc_resolve/late/diagnostics.rs]: Can we change this to: "try calling {method name} as a method"?

File: src/test/ui/self/suggest-self-2.stderr [hunk 4]
```diff
@@ -0,0 +1,28 @@
...
+  --> $DIR/suggest-self-2.rs:5:9
+   |
+LL |         bar(self);
+   |         ^^^ help: try calling method instead of passing `self` as parameter: `self.bar`
+
+error[E0425]: cannot find function `bar` in this scope
+  --> $DIR/suggest-self-2.rs:10:9
+   |
+LL |         bar(&self);
+   |         ^^^ help: try calling method instead of passing `self` as parameter: `self.bar`
```
Comment (varkor) [inline src/test/ui/self/suggest-self-2.stderr]: It would be nice if the suggestion rewrote the entire call:
```
try calling `bar` as a method: `self.bar();`
```

File: src/librustc_resolve/late/diagnostics.rs [hunk 5]
```diff
@@ -253,6 +253,37 @@ impl<'a> LateResolutionVisitor<'a, '_> {
...
+                    format!("self.{}", path_str),
```
Comment (varkor) [inline src/librustc_resolve/late/diagnostics.rs]: This doesn't get rid of the existing `self`/`&self`, etc. at the moment.

**Review by varkor — CHANGES_REQUESTED** [review]

File: src/test/ui/self/suggest-self-2.stderr (hunk 4 above)
Comment (VirrageS) [reply src/test/ui/self/suggest-self-2.stderr]: Yeah, I was thinking about it but I'm not sure how I can do that. I was thinking that we can do something like: `Span(args[1].span.lo, args.last().span.hi)` but then I don't know how to get the actual code for that span.

File: src/librustc_resolve/late/diagnostics.rs (hunk 5 above)
Comment (VirrageS) [reply src/librustc_resolve/late/diagnostics.rs]: Could you elaborate? I'm not sure if I understand this.

Comment (varkor) [reply src/librustc_resolve/late/diagnostics.rs]: This was really the same comment as https://github.com/rust-lang/rust/pull/66913#discussion_r355130743.

File: src/test/ui/self/suggest-self-2.stderr (hunk 4 above)
Comment (varkor) [reply src/test/ui/self/suggest-self-2.stderr]: Yes, I think you'll want to do something similar to that. I haven't got time to work it out exactly now, but I'll try to get back to you if you can't figure it out.

Comment (VirrageS) [reply src/test/ui/self/suggest-self-2.stderr]: Sorry for the delay. I've managed to include arguments into suggestion.

File: src/test/ui/self/suggest-self-2.stderr [hunk 6]
```diff
@@ -0,0 +1,34 @@
+error[E0425]: cannot find function `bar` in this scope
+  --> $DIR/suggest-self-2.rs:5:9
+   |
+LL |         bar(self);
+   |         ^^^ help: try calling `bar` as a method: `self.bar()`
```
Comment (varkor) [inline src/test/ui/self/suggest-self-2.stderr]: The span should be the entire call: `bar(self)`. Other than that, this looks good!

**Comment by varkor** [comment]
Sorry @VirrageS, I didn't spot that you had updated the PR. One small tweak, and I think this is good to go :)

File: src/test/ui/self/suggest-self-2.stderr (hunk 6 above)
Comment (VirrageS) [reply src/test/ui/self/suggest-self-2.stderr]: Done :) Also changed the implementation a bit - hope for the better.

File: src/test/ui/self/suggest-self-2.stderr [hunk 7]
```diff
@@ -2,19 +2,25 @@ error[E0425]: cannot find function `bar` in this scope
   --> $DIR/suggest-self-2.rs:5:9
    |
 LL |         bar(self);
-   |         ^^^ help: try calling `bar` as a method: `self.bar()`
+   |         ^^^------
+   |         |
+   |         help: try calling `bar` as a method: `self.bar()`
```
Comment (varkor) [inline src/test/ui/self/suggest-self-2.stderr]: I think both the error span and the suggestion span need to be the whole call, otherwise a tool may try auto-fixing to `self.bar()(self)`.

Comment (VirrageS) [reply src/test/ui/self/suggest-self-2.stderr]: Done

File: src/librustc_resolve/late/diagnostics.rs [hunk 8]
```diff
@@ -295,6 +295,7 @@ impl<'a> LateResolutionVisitor<'a, '_> {
                     }
                 }
 
+                err.set_span(call_span);
```
Comment (varkor) [inline src/librustc_resolve/late/diagnostics.rs]: Sorry, I realised I misread the output before and flipped the hint/error spans in my head. They were right beforehand: I'm sorry for wasting your time! Let's revert the last commit, and then I'll approve.

Comment (VirrageS) [reply src/librustc_resolve/late/diagnostics.rs]: No worries :) Reverted last commit

**Comment by varkor** [comment]
@VirrageS: this looks great, thank you! (And thanks for dealing with my slowness.)

@bors r+ rollup

**Comment by Centril** [comment]
Seems tidy checks failed in https://github.com/rust-lang/rust/pull/67555#issuecomment-568437030, @bors r-

File: src/librustc_resolve/late/diagnostics.rs [hunk 9]
```diff
@@ -253,6 +253,56 @@ impl<'a> LateResolutionVisitor<'a, '_> {
...
+                        args_snippet = snippet;
+                    }
+                }
+
+                err.span_suggestion(
+                    call_span,
+                    &format!("try calling `{}` as a method", ident),
+                    format!("self.{}({})", path_str, args_snippet),
+                    Applicability::MachineApplicable,
+                );
```
Comment (Centril) [inline src/librustc_resolve/late/diagnostics.rs]: Could we please extract this to its own method?

Comment (VirrageS) [reply src/librustc_resolve/late/diagnostics.rs]: Done, but not sure if the method has the meaningful name.. Will appreciate suggestions

File: src/librustc_resolve/late/diagnostics.rs [hunk 10]
```diff
@@ -298,6 +316,43 @@ impl<'a> LateResolutionVisitor<'a, '_> {
         (err, candidates)
     }
 
+    /// Check if the source is call expression and the first argument is `self`. If true,
+    /// return the span of whole call and the span for all arguments expect the first one (`self`).
+    fn call_has_self_arg(&self, source: PathSource<'_>) -> Option<(Span, Option<Span>)> {
+        let mut has_self_arg = None;
+        if let PathSource::Expr(parent) = source {
+            match &parent.map(|p| &p.kind) {
```
Comment (Centril) [inline src/librustc_resolve/late/diagnostics.rs]: `parent?.kind` should work now

(function name feels appropriate)

**Comment by VirrageS** [comment]
@Centril could you look into MR, I've fixed all previous comments
