### PR TITLE
Do not spill operand debuginfo to stack for AArch64 SVE predicates `<vscale x N x i1>` where `N != 16`

### LINKED ISSUE #150419: LLVM instruction selection error when spilling operand debuginfo to stack for AArch64 SVE predicates `<vscale x N x i1>` where `N != 16`
I tried this code (https://godbolt.org/z/edj7vz3e9):

```rust
#![allow(internal_features)]
#![feature(rustc_attrs, link_llvm_intrinsics)]

#[rustc_scalable_vector(16)]
#[allow(non_camel_case_types)]
#[repr(transparent)]
pub struct svbool_t(bool);

#[rustc_scalable_vector(4)]
#[allow(non_camel_case_types)]
#[repr(transparent)]
pub struct svbool4_t(bool);

impl std::convert::Into<svbool_t> for svbool4_t {
    #[inline(always)]
    fn into(self) -> svbool_t {
        unsafe extern "C" {
            #[link_name = "llvm.aarch64.sve.convert.to.svbool.nxv4i1"]
            fn convert_to_svbool(b: svbool4_t) -> svbool_t;
        }
        unsafe { convert_to_svbool(self) }
    }
}

pub fn svwhilelt_b32_u64(op1: u64, op2: u64) -> svbool_t {
    unsafe extern "C" {
        #[link_name = "llvm.aarch64.sve.whilelo.nxv4i1.u64"]
        fn _svwhilelt_b32_u64(op1: u64, op2: u64) -> svbool4_t;
    }
    unsafe { _svwhilelt_b32_u64(op1, op2) }.into()
}
```

I expected to see this happen: *compiles successfully*.

Instead, this happened: *failed to compile with error*.
```
rustc-LLVM ERROR: Cannot select: 0x7fb7ed3a05b0: ch = store<(store (<vscale x 1 x s8>) into %ir.3, align 4)> 0x7fb7ed3a03f0, 0x7fb7ed3a0230, FrameIndex:i64<0>, undef:i64
  0x7fb7ed3a0230: nxv4i1 = get_active_lane_mask 0x7fb7ed3a0070, 0x7fb7ed3a0150, example.rs:30:14
    0x7fb7ed3a0070: i64,ch = CopyFromReg 0x7fb7ed21bd20, Register:i64 %0
    0x7fb7ed3a0150: i64,ch = CopyFromReg 0x7fb7ed21bd20, Register:i64 %1
In function: _RNvCs5pe9rO2ESBx_7example17svwhilelt_b32_u64
Compiler returned: 101
```

Compile with `-C debuginfo=0` or `-C debuginfo=1` works well.

### Analysis
The debuginfo for SVE predicates `<vscale x N x i1>` where `N != 16` should be ignored by this [commit](https://github.com/rust-lang/rust/pull/143924/changes/89eea57594e3e1d8e618dd530ea1c8e7c9b4c7a4).

https://github.com/rust-lang/rust/blob/89eea57594e3e1d8e618dd530ea1c8e7c9b4c7a4/compiler/rustc_codegen_ssa/src/mir/debuginfo.rs#L438-L452

The problem comes from line 446. The `marker_type.kind()` is `ty::Bool` instead of `ty::Slice`, so the code doesn't work as intended.

### Meta

`rustc --version --verbose`:
```
rustc 1.94.0-nightly (e7d44143a 2025-12-24)
binary: rustc
commit-hash: e7d44143a12a526488e4f0c0d7ea8e62a4fe9354
commit-date: 2025-12-24
host: x86_64-unknown-linux-gnu
release: 1.94.0-nightly
LLVM version: 21.1.8
Internal compiler ID: nightly
```

No backtrace.

<details><summary>tracing log with "RUSTC_LOG=rustc_codegen_ssa=debug,rustc_codegen_llvm=debug"</summary>
<p>

```
DEBUG rustc_codegen_ssa::back::metadata getting rlib metadata for /home/h3f/projects/rust/build/x86_64-unknown-linux-gnu/stage1/lib/rustlib/aarch64-unknown-linux-gnu/lib/libstd-b722ecfd18460264.rlib
 DEBUG rustc_codegen_ssa::back::metadata getting rlib metadata for /home/h3f/projects/rust/build/x86_64-unknown-linux-gnu/stage1/lib/rustlib/aarch64-unknown-linux-gnu/lib/libstd_detect-b3fdc47f3d355bad.rlib
 DEBUG rustc_codegen_ssa::back::metadata getting rlib metadata for /home/h3f/projects/rust/build/x86_64-unknown-linux-gnu/stage1/lib/rustlib/aarch64-unknown-linux-gnu/lib/libcore-624b00c374a358a8.rlib
 DEBUG rustc_codegen_ssa::back::metadata getting rlib metadata for /home/h3f/projects/rust/build/x86_64-unknown-linux-gnu/stage1/lib/rustlib/aarch64-unknown-linux-gnu/lib/liballoc-f2772df9365cc4da.rlib
 DEBUG rustc_codegen_ssa::back::metadata getting rlib metadata for /home/h3f/projects/rust/build/x86_64-unknown-linux-gnu/stage1/lib/rustlib/aarch64-unknown-linux-gnu/lib/libcompiler_builtins-53bd3af74bc58210.rlib
 DEBUG rustc_codegen_ssa::back::metadata getting rlib metadata for /home/h3f/projects/rust/build/x86_64-unknown-linux-gnu/stage1/lib/rustlib/aarch64-unknown-linux-gnu/lib/liblibc-8d8a49490d6b18a5.rlib
 DEBUG rustc_codegen_ssa::back::metadata getting rlib metadata for /home/h3f/projects/rust/build/x86_64-unknown-linux-gnu/stage1/lib/rustlib/aarch64-unknown-linux-gnu/lib/librustc_std_workspace_core-6beee1409bec0d5d.rlib
 DEBUG rustc_codegen_ssa::back::metadata getting rlib metadata for /home/h3f/projects/rust/build/x86_64-unknown-linux-gnu/stage1/lib/rustlib/aarch64-unknown-linux-gnu/lib/libunwind-d84c6b56dc0a48be.rlib
 DEBUG rustc_codegen_ssa::back::metadata getting rlib metadata for /home/h3f/projects/rust/build/x86_64-unknown-linux-gnu/stage1/lib/rustlib/aarch64-unknown-linux-gnu/lib/libminiz_oxide-ef8c35a4029e1a12.rlib
 DEBUG rustc_codegen_ssa::back::metadata getting rlib metadata for /home/h3f/projects/rust/build/x86_64-unknown-linux-gnu/stage1/lib/rustlib/aarch64-unknown-linux-gnu/lib/libadler2-0d225b3d0412fa92.rlib
 DEBUG rustc_codegen_ssa::back::metadata getting rlib metadata for /home/h3f/projects/rust/build/x86_64-unknown-linux-gnu/stage1/lib/rustlib/aarch64-unknown-linux-gnu/lib/libhashbrown-652447b1e838a6d1.rlib
 DEBUG rustc_codegen_ssa::back::metadata getting rlib metadata for /home/h3f/projects/rust/build/x86_64-unknown-linux-gnu/stage1/lib/rustlib/aarch64-unknown-linux-gnu/lib/librustc_std_workspace_alloc-84820e8648f0cf13.rlib
 DEBUG rustc_codegen_ssa::back::metadata getting rlib metadata for /home/h3f/projects/rust/build/x86_64-unknown-linux-gnu/stage1/lib/rustlib/aarch64-unknown-linux-gnu/lib/libstd_detect-b3fdc47f3d355bad.rlib
 DEBUG rustc_codegen_ssa::back::metadata getting rlib metadata for /home/h3f/projects/rust/build/x86_64-unknown-linux-gnu/stage1/lib/rustlib/aarch64-unknown-linux-gnu/lib/librustc_demangle-5ef949d6f622f056.rlib
 DEBUG rustc_codegen_ssa::back::metadata getting rlib metadata for /home/h3f/projects/rust/build/x86_64-unknown-linux-gnu/stage1/lib/rustlib/aarch64-unknown-linux-gnu/lib/libcfg_if-94c4a8f9b958cb90.rlib
 DEBUG rustc_codegen_ssa::back::metadata getting rlib metadata for /home/h3f/projects/rust/build/x86_64-unknown-linux-gnu/stage1/lib/rustlib/aarch64-unknown-linux-gnu/lib/libaddr2line-a245022b019119c8.rlib
 DEBUG rustc_codegen_ssa::back::metadata getting rlib metadata for /home/h3f/projects/rust/build/x86_64-unknown-linux-gnu/stage1/lib/rustlib/aarch64-unknown-linux-gnu/lib/libgimli-c62209d43f4ec605.rlib
 DEBUG rustc_codegen_ssa::back::metadata getting rlib metadata for /home/h3f/projects/rust/build/x86_64-unknown-linux-gnu/stage1/lib/rustlib/aarch64-unknown-linux-gnu/lib/libobject-a2fa2dac4168f971.rlib
 DEBUG rustc_codegen_ssa::back::metadata getting rlib metadata for /home/h3f/projects/rust/build/x86_64-unknown-linux-gnu/stage1/lib/rustlib/aarch64-unknown-linux-gnu/lib/libmemchr-7d75c34d451546bb.rlib
 DEBUG rustc_codegen_ssa::back::metadata getting rlib metadata for /home/h3f/projects/rust/build/x86_64-unknown-linux-gnu/stage1/lib/rustlib/aarch64-unknown-linux-gnu/lib/libpanic_unwind-af6a46d2374d192d.rlib
 DEBUG rustc_codegen_ssa::back::symbol_export EXPORTED SYMBOL (local): _RNvCsdHHX9MsTYBi_9debuginfo17svwhilelt_b32_u64 (Rust)
 DEBUG rustc_codegen_llvm::debuginfo CodegenUnitDebugContext::new
 DEBUG rustc_codegen_llvm::debuginfo::metadata build_compile_unit_di_node: "src/debuginfo.rs/@/debuginfo.9fa162b06e2e3ac2-cgu.0"
 DEBUG rustc_codegen_ssa::mono_item BEGIN PREDEFINING 'fn svwhilelt_b32_u64 (Fn(Item(DefId(0:13 ~ debuginfo[9fa1]::svwhilelt_b32_u64)), 139834379250504))' in cgu debuginfo.9fa162b06e2e3ac2-cgu.0
 DEBUG rustc_codegen_ssa::mono_item symbol _RNvCsdHHX9MsTYBi_9debuginfo17svwhilelt_b32_u64
 DEBUG rustc_codegen_llvm::declare declare_rust_fn(name="_RNvCsdHHX9MsTYBi_9debuginfo17svwhilelt_b32_u64", fn_abi=FnAbi { args: [ArgAbi { layout: TyAndLayout { ty: i64, layout: Layout { size: Size(8 bytes), align: AbiAlign { abi: Align(8 bytes) }, backend_repr: Scalar(Initialized { value: Int(I64, true), valid_range: 0..=18446744073709551615 }), fields: Primitive, largest_niche: None, uninhabited: false, variants: Single { index: 0 }, max_repr_align: None, unadjusted_abi_align: Align(8 bytes), randomization_seed: 4294967303 } }, mode: Direct(ArgAttributes { regular: NoUndef, arg_ext: None, pointee_size: Size(0 bytes), pointee_align: None }) }, ArgAbi { layout: TyAndLayout { ty: i64, layout: Layout { size: Size(8 bytes), align: AbiAlign { abi: Align(8 bytes) }, backend_repr: Scalar(Initialized { value: Int(I64, true), valid_range: 0..=18446744073709551615 }), fields: Primitive, largest_niche: None, uninhabited: false, variants: Single { index: 0 }, max_repr_align: None, unadjusted_abi_align: Align(8 bytes), randomization_seed: 4294967303 } }, mode: Direct(ArgAttributes { regular: NoUndef, arg_ext: None, pointee_size: Size(0 bytes), pointee_align: None }) }], ret: ArgAbi { layout: TyAndLayout { ty: svbool_t, layout: Layout { size: Size(16 bytes), align: AbiAlign { abi: Align(16 bytes) }, backend_repr: ScalableVector { element: Initialized { value: Int(I8, false), valid_range: 0..=1 }, count: 16 }, fields: Arbitrary { offsets: [Size(0 bytes)], in_memory_order: [0] }, largest_niche: Some(Niche { offset: Size(0 bytes), value: Int(I8, false), valid_range: 0..=1 }), uninhabited: false, variants: Single { index: 0 }, max_repr_align: None, unadjusted_abi_align: Align(1 bytes), randomization_seed: 281483566645265 } }, mode: Direct(ArgAttributes { regular: , arg_ext: None, pointee_size: Size(0 bytes), pointee_align: None }) }, c_variadic: false, fixed_count: 2, conv: Rust, can_unwind: true })
 DEBUG rustc_codegen_llvm::type_of llvm_type(TyAndLayout {
     ty: svbool_t,
     layout: Layout {
         size: Size(16 bytes),
         align: AbiAlign {
             abi: Align(16 bytes),
         },
         backend_repr: ScalableVector {
             element: Initialized {
                 value: Int(
                     I8,
                     false,
                 ),
                 valid_range: 0..=1,
             },
             count: 16,
         },
         fields: Arbitrary {
             offsets: [
                 Size(0 bytes),
             ],
             in_memory_order: [
                 0,
             ],
         },
         largest_niche: Some(
             Niche {
                 offset: Size(0 bytes),
                 value: Int(
                     I8,
                     false,
                 ),
                 valid_range: 0..=1,
             },
         ),
         uninhabited: false,
         variants: Single {
             index: 0,
         },
         max_repr_align: None,
         unadjusted_abi_align: Align(1 bytes),
         randomization_seed: 281483566645265,
     },
 })
 DEBUG rustc_codegen_llvm::type_of --> mapped TyAndLayout {
     ty: svbool_t,
     layout: Layout {
         size: Size(16 bytes),
         align: AbiAlign {
             abi: Align(16 bytes),
         },
         backend_repr: ScalableVector {
             element: Initialized {
                 value: Int(
                     I8,
                     false,
                 ),
                 valid_range: 0..=1,
             },
             count: 16,
         },
         fields: Arbitrary {
             offsets: [
                 Size(0 bytes),
             ],
             in_memory_order: [
                 0,
             ],
         },
         largest_niche: Some(
             Niche {
                 offset: Size(0 bytes),
                 value: Int(
                     I8,
                     false,
                 ),
                 valid_range: 0..=1,
             },
         ),
         uninhabited: false,
         variants: Single {
             index: 0,
         },
         max_repr_align: None,
         unadjusted_abi_align: Align(1 bytes),
         randomization_seed: 281483566645265,
     },
 } to llty=<vscale x 16 x i1>
 DEBUG rustc_codegen_llvm::declare declare_raw_fn(name="_RNvCsdHHX9MsTYBi_9debuginfo17svwhilelt_b32_u64", ty=<vscale x 16 x i1> (i64, i64))
 DEBUG rustc_codegen_llvm::declare declare_simple_fn(name="_RNvCsdHHX9MsTYBi_9debuginfo17svwhilelt_b32_u64", ty=<vscale x 16 x i1> (i64, i64))
 DEBUG rustc_codegen_llvm::mono_item predefine_fn: instance = Instance { def: Item(DefId(0:13 ~ debuginfo[9fa1]::svwhilelt_b32_u64)), args: [] }
 DEBUG rustc_codegen_ssa::mono_item END PREDEFINING 'fn svwhilelt_b32_u64 (Fn(Item(DefId(0:13 ~ debuginfo[9fa1]::svwhilelt_b32_u64)), 139834379250504))' in cgu debuginfo.9fa162b06e2e3ac2-cgu.0
 DEBUG rustc_codegen_ssa::mono_item BEGIN PREDEFINING 'fn <svbool4_t as Into<svbool_t>>::into (Fn(Item(DefId(0:10 ~ debuginfo[9fa1]::{impl#0}::into)), 139834379250504))' in cgu debuginfo.9fa162b06e2e3ac2-cgu.0
 DEBUG rustc_codegen_ssa::mono_item symbol _RNvXCsdHHX9MsTYBi_9debuginfoNtB2_9svbool4_tINtNtCs7D9OQsQgQbp_4core7convert4IntoNtB2_8svbool_tE4into
 DEBUG rustc_codegen_llvm::declare declare_rust_fn(name="_RNvXCsdHHX9MsTYBi_9debuginfoNtB2_9svbool4_tINtNtCs7D9OQsQgQbp_4core7convert4IntoNtB2_8svbool_tE4into", fn_abi=FnAbi { args: [ArgAbi { layout: TyAndLayout { ty: svbool4_t, layout: Layout { size: Size(4 bytes), align: AbiAlign { abi: Align(4 bytes) }, backend_repr: ScalableVector { element: Initialized { value: Int(I8, false), valid_range: 0..=1 }, count: 4 }, fields: Arbitrary { offsets: [Size(0 bytes)], in_memory_order: [0] }, largest_niche: Some(Niche { offset: Size(0 bytes), value: Int(I8, false), valid_range: 0..=1 }), uninhabited: false, variants: Single { index: 0 }, max_repr_align: None, unadjusted_abi_align: Align(1 bytes), randomization_seed: 281483566645253 } }, mode: Direct(ArgAttributes { regular: , arg_ext: None, pointee_size: Size(0 bytes), pointee_align: None }) }], ret: ArgAbi { layout: TyAndLayout { ty: svbool_t, layout: Layout { size: Size(16 bytes), align: AbiAlign { abi: Align(16 bytes) }, backend_repr: ScalableVector { element: Initialized { value: Int(I8, false), valid_range: 0..=1 }, count: 16 }, fields: Arbitrary { offsets: [Size(0 bytes)], in_memory_order: [0] }, largest_niche: Some(Niche { offset: Size(0 bytes), value: Int(I8, false), valid_range: 0..=1 }), uninhabited: false, variants: Single { index: 0 }, max_repr_align: None, unadjusted_abi_align: Align(1 bytes), randomization_seed: 281483566645265 } }, mode: Direct(ArgAttributes { regular: , arg_ext: None, pointee_size: Size(0 bytes), pointee_align: None }) }, c_variadic: false, fixed_count: 1, conv: Rust, can_unwind: true })
 DEBUG rustc_codegen_llvm::type_of llvm_type(TyAndLayout {
     ty: svbool4_t,
     layout: Layout {
         size: Size(4 bytes),
         align: AbiAlign {
             abi: Align(4 bytes),
         },
         backend_repr: ScalableVector {
             element: Initialized {
                 value: Int(
                     I8,
                     false,
                 ),
                 valid_range: 0..=1,
             },
             count: 4,
         },
         fields: Arbitrary {
             offsets: [
                 Size(0 bytes),
             ],
             in_memory_order: [
                 0,
             ],
         },
         largest_niche: Some(
             Niche {
                 offset: Size(0 bytes),
                 value: Int(
                     I8,
                     false,
                 ),
                 valid_range: 0..=1,
             },
         ),
         uninhabited: false,
         variants: Single {
             index: 0,
         },
         max_repr_align: None,
         unadjusted_abi_align: Align(1 bytes),
         randomization_seed: 281483566645253,
     },
 })
 DEBUG rustc_codegen_llvm::type_of --> mapped TyAndLayout {
     ty: svbool4_t,
     layout: Layout {
         size: Size(4 bytes),
         align: AbiAlign {
             abi: Align(4 bytes),
         },
         backend_repr: ScalableVector {
             element: Initialized {
                 value: Int(
                     I8,
                     false,
                 ),
                 valid_range: 0..=1,
             },
             count: 4,
         },
         fields: Arbitrary {
             offsets: [
                 Size(0 bytes),
             ],
             in_memory_order: [
                 0,
             ],
         },
         largest_niche: Some(
             Niche {
                 offset: Size(0 bytes),
                 value: Int(
                     I8,
                     false,
                 ),
                 valid_range: 0..=1,
             },
         ),
         uninhabited: false,
         variants: Single {
             index: 0,
         },
         max_repr_align: None,
         unadjusted_abi_align: Align(1 bytes),
         randomization_seed: 281483566645253,
     },
 } to llty=<vscale x 4 x i1>
 DEBUG rustc_codegen_llvm::declare declare_raw_fn(name="_RNvXCsdHHX9MsTYBi_9debuginfoNtB2_9svbool4_tINtNtCs7D9OQsQgQbp_4core7convert4IntoNtB2_8svbool_tE4into", ty=<vscale x 16 x i1> (<vscale x 4 x i1>))
 DEBUG rustc_codegen_llvm::declare declare_simple_fn(name="_RNvXCsdHHX9MsTYBi_9debuginfoNtB2_9svbool4_tINtNtCs7D9OQsQgQbp_4core7convert4IntoNtB2_8svbool_tE4into", ty=<vscale x 16 x i1> (<vscale x 4 x i1>))
 DEBUG rustc_codegen_llvm::mono_item predefine_fn: instance = Instance { def: Item(DefId(0:10 ~ debuginfo[9fa1]::{impl#0}::into)), args: [] }
 DEBUG rustc_codegen_ssa::mono_item END PREDEFINING 'fn <svbool4_t as Into<svbool_t>>::into (Fn(Item(DefId(0:10 ~ debuginfo[9fa1]::{impl#0}::into)), 139834379250504))' in cgu debuginfo.9fa162b06e2e3ac2-cgu.0
 DEBUG rustc_codegen_ssa::mono_item BEGIN IMPLEMENTING 'fn svwhilelt_b32_u64 (Fn(Item(DefId(0:13 ~ debuginfo[9fa1]::svwhilelt_b32_u64)), 139834379250504))' in cgu debuginfo.9fa162b06e2e3ac2-cgu.0
  INFO rustc_codegen_ssa::base codegen_instance(svwhilelt_b32_u64)
 rustc_codegen_ssa::mir::codegen_mir instance=Instance { def: Item(DefId(0:13 ~ debuginfo[9fa1]::svwhilelt_b32_u64)), args: [] }
   0ms DEBUG rustc_codegen_llvm::callee get_fn(instance=Instance { def: Item(DefId(0:13 ~ debuginfo[9fa1]::svwhilelt_b32_u64)), args: [] })
   0ms DEBUG rustc_codegen_ssa::mir fn_abi: FnAbi { args: [ArgAbi { layout: TyAndLayout { ty: i64, layout: Layout { size: Size(8 bytes), align: AbiAlign { abi: Align(8 bytes) }, backend_repr: Scalar(Initialized { value: Int(I64, true), valid_range: 0..=18446744073709551615 }), fields: Primitive, largest_niche: None, uninhabited: false, variants: Single { index: 0 }, max_repr_align: None, unadjusted_abi_align: Align(8 bytes), randomization_seed: 4294967303 } }, mode: Direct(ArgAttributes { regular: NoUndef, arg_ext: None, pointee_size: Size(0 bytes), pointee_align: None }) }, ArgAbi { layout: TyAndLayout { ty: i64, layout: Layout { size: Size(8 bytes), align: AbiAlign { abi: Align(8 bytes) }, backend_repr: Scalar(Initialized { value: Int(I64, true), valid_range: 0..=18446744073709551615 }), fields: Primitive, largest_niche: None, uninhabited: false, variants: Single { index: 0 }, max_repr_align: None, unadjusted_abi_align: Align(8 bytes), randomization_seed: 4294967303 } }, mode: Direct(ArgAttributes { regular: NoUndef, arg_ext: None, pointee_size: Size(0 bytes), pointee_align: None }) }], ret: ArgAbi { layout: TyAndLayout { ty: svbool_t, layout: Layout { size: Size(16 bytes), align: AbiAlign { abi: Align(16 bytes) }, backend_repr: ScalableVector { element: Initialized { value: Int(I8, false), valid_range: 0..=1 }, count: 16 }, fields: Arbitrary { offsets: [Size(0 bytes)], in_memory_order: [0] }, largest_niche: Some(Niche { offset: Size(0 bytes), value: Int(I8, false), valid_range: 0..=1 }), uninhabited: false, variants: Single { index: 0 }, max_repr_align: None, unadjusted_abi_align: Align(1 bytes), randomization_seed: 281483566645265 } }, mode: Direct(ArgAttributes { regular: , arg_ext: None, pointee_size: Size(0 bytes), pointee_align: None }) }, c_variadic: false, fixed_count: 2, conv: Rust, can_unwind: true }
   rustc_codegen_llvm::debuginfo::metadata::alloc_new_file_metadata 
     0ms DEBUG rustc_codegen_llvm::debuginfo::metadata source_file.name=Real(RealFileName { local: Some(InnerRealFileName { name: "src/debuginfo.rs", working_directory: "/home/h3f/projects/sve", embeddable_name: "/home/h3f/projects/sve/src/debuginfo.rs" }), maybe_remapped: InnerRealFileName { name: "src/debuginfo.rs", working_directory: "/home/h3f/projects/sve", embeddable_name: "/home/h3f/projects/sve/src/debuginfo.rs" }, scopes: RemapPathScopeComponents(0x0) })
     0ms DEBUG rustc_codegen_llvm::debuginfo::metadata working_directory="/home/h3f/projects/sve", embeddable_name="/home/h3f/projects/sve/src/debuginfo.rs"
   0ms DEBUG rustc_codegen_llvm::debuginfo::metadata type_di_node: svbool_t kind: svbool_t
   0ms DEBUG rustc_codegen_llvm::debuginfo::metadata type_di_node: bool kind: bool
   0ms DEBUG rustc_codegen_llvm::debuginfo::metadata build_basic_type_di_node: bool
   0ms DEBUG rustc_codegen_llvm::debuginfo::metadata type_di_node: i64 kind: i64
   0ms DEBUG rustc_codegen_llvm::debuginfo::metadata build_basic_type_di_node: i64
   0ms DEBUG rustc_codegen_ssa::mir monomorphize: self.instance=Instance { def: Item(DefId(0:13 ~ debuginfo[9fa1]::svwhilelt_b32_u64)), args: [] }
   0ms DEBUG rustc_codegen_ssa::mir monomorphize: self.instance=Instance { def: Item(DefId(0:13 ~ debuginfo[9fa1]::svwhilelt_b32_u64)), args: [] }
   0ms DEBUG rustc_codegen_ssa::mir monomorphize: self.instance=Instance { def: Item(DefId(0:13 ~ debuginfo[9fa1]::svwhilelt_b32_u64)), args: [] }
   0ms DEBUG rustc_codegen_ssa::mir monomorphize: self.instance=Instance { def: Item(DefId(0:13 ~ debuginfo[9fa1]::svwhilelt_b32_u64)), args: [] }
   0ms DEBUG rustc_codegen_ssa::mir monomorphize: self.instance=Instance { def: Item(DefId(0:13 ~ debuginfo[9fa1]::svwhilelt_b32_u64)), args: [] }
   0ms DEBUG rustc_codegen_ssa::mir monomorphize: self.instance=Instance { def: Item(DefId(0:13 ~ debuginfo[9fa1]::svwhilelt_b32_u64)), args: [] }
   0ms DEBUG rustc_codegen_ssa::mir monomorphize: self.instance=Instance { def: Item(DefId(0:13 ~ debuginfo[9fa1]::svwhilelt_b32_u64)), args: [] }
   0ms DEBUG rustc_codegen_ssa::mir monomorphize: self.instance=Instance { def: Item(DefId(0:13 ~ debuginfo[9fa1]::svwhilelt_b32_u64)), args: [] }
   0ms DEBUG rustc_codegen_ssa::mir::analyze visit_place(place=_1, context=NonMutatingUse(Copy))
   0ms DEBUG rustc_codegen_ssa::mir::analyze visit_place(place=_2, context=NonMutatingUse(Copy))
   0ms DEBUG rustc_codegen_ssa::mir::analyze visit_place(place=_3, context=MutatingUse(Call))
   0ms DEBUG rustc_codegen_ssa::mir monomorphize: self.instance=Instance { def: Item(DefId(0:13 ~ debuginfo[9fa1]::svwhilelt_b32_u64)), args: [] }
   0ms DEBUG rustc_codegen_ssa::mir::analyze visit_place(place=_3, context=NonMutatingUse(Move))
   0ms DEBUG rustc_codegen_ssa::mir::analyze visit_place(place=_0, context=MutatingUse(Call))
   0ms DEBUG rustc_codegen_ssa::mir monomorphize: self.instance=Instance { def: Item(DefId(0:13 ~ debuginfo[9fa1]::svwhilelt_b32_u64)), args: [] }
   0ms DEBUG rustc_codegen_ssa::mir monomorphize: self.instance=Instance { def: Item(DefId(0:13 ~ debuginfo[9fa1]::svwhilelt_b32_u64)), args: [] }
   0ms DEBUG rustc_codegen_ssa::mir monomorphize: self.instance=Instance { def: Item(DefId(0:13 ~ debuginfo[9fa1]::svwhilelt_b32_u64)), args: [] }
   0ms DEBUG rustc_codegen_ssa::mir monomorphize: self.instance=Instance { def: Item(DefId(0:13 ~ debuginfo[9fa1]::svwhilelt_b32_u64)), args: [] }
   0ms DEBUG rustc_codegen_ssa::mir alloc: _0 -> operand
   0ms DEBUG rustc_codegen_ssa::mir monomorphize: self.instance=Instance { def: Item(DefId(0:13 ~ debuginfo[9fa1]::svwhilelt_b32_u64)), args: [] }
   0ms DEBUG rustc_codegen_ssa::mir alloc: _3 -> operand
   0ms DEBUG rustc_codegen_ssa::mir monomorphize: self.instance=Instance { def: Item(DefId(0:13 ~ debuginfo[9fa1]::svwhilelt_b32_u64)), args: [] }
   0ms DEBUG rustc_codegen_ssa::mir monomorphize: self.instance=Instance { def: Item(DefId(0:13 ~ debuginfo[9fa1]::svwhilelt_b32_u64)), args: [] }
   0ms DEBUG rustc_codegen_ssa::mir::operand OperandRef::store: operand=Immediate((i64:i64 %0)), dest=PlaceRef { val: PlaceValue { llval: (ptr:  %3 = alloca [8 x i8], align 8), llextra: None, align: Align(8 bytes) }, layout: TyAndLayout { ty: i64, layout: Layout { size: Size(8 bytes), align: AbiAlign { abi: Align(8 bytes) }, backend_repr: Scalar(Initialized { value: Int(I64, true), valid_range: 0..=18446744073709551615 }), fields: Primitive, largest_niche: None, uninhabited: false, variants: Single { index: 0 }, max_repr_align: None, unadjusted_abi_align: Align(8 bytes), randomization_seed: 4294967303 } } }
   0ms DEBUG rustc_codegen_llvm::builder Store (i64:i64 %0) -> (ptr:  %3 = alloca [8 x i8], align 8) (MemFlags(0x0))
   0ms DEBUG rustc_codegen_ssa::mir::operand OperandRef::store: operand=Immediate((i64:i64 %1)), dest=PlaceRef { val: PlaceValue { llval: (ptr:  %3 = alloca [8 x i8], align 8), llextra: None, align: Align(8 bytes) }, layout: TyAndLayout { ty: i64, layout: Layout { size: Size(8 bytes), align: AbiAlign { abi: Align(8 bytes) }, backend_repr: Scalar(Initialized { value: Int(I64, true), valid_range: 0..=18446744073709551615 }), fields: Primitive, largest_niche: None, uninhabited: false, variants: Single { index: 0 }, max_repr_align: None, unadjusted_abi_align: Align(8 bytes), randomization_seed: 4294967303 } } }
   0ms DEBUG rustc_codegen_llvm::builder Store (i64:i64 %1) -> (ptr:  %3 = alloca [8 x i8], align 8) (MemFlags(0x0))
   0ms DEBUG rustc_codegen_ssa::mir::block codegen_block(bb0=BasicBlockData { statements: [], after_last_stmt_debuginfos: StmtDebugInfos([]), terminator: Some(Terminator { source_info: SourceInfo { span: src/debuginfo.rs:30:14: 30:42 (#0), scope: scope[0] }, kind: _3 = svwhilelt_b32_u64::_svwhilelt_b32_u64(copy _1, copy _2) -> [return: bb1, unwind unreachable] }), is_cleanup: false })
   0ms DEBUG rustc_codegen_ssa::mir::block codegen_terminator: Terminator { source_info: SourceInfo { span: src/debuginfo.rs:30:14: 30:42 (#0), scope: scope[0] }, kind: _3 = svwhilelt_b32_u64::_svwhilelt_b32_u64(copy _1, copy _2) -> [return: bb1, unwind unreachable] }
   0ms DEBUG rustc_codegen_ssa::mir::operand codegen_operand(operand=svwhilelt_b32_u64::_svwhilelt_b32_u64)
   0ms DEBUG rustc_codegen_ssa::mir monomorphize: self.instance=Instance { def: Item(DefId(0:13 ~ debuginfo[9fa1]::svwhilelt_b32_u64)), args: [] }
   0ms DEBUG rustc_codegen_ssa::mir monomorphize: self.instance=Instance { def: Item(DefId(0:13 ~ debuginfo[9fa1]::svwhilelt_b32_u64)), args: [] }
   0ms DEBUG rustc_codegen_ssa::mir monomorphize: self.instance=Instance { def: Item(DefId(0:13 ~ debuginfo[9fa1]::svwhilelt_b32_u64)), args: [] }
   0ms DEBUG rustc_codegen_ssa::mir::operand codegen_operand(operand=copy _1)
   0ms DEBUG rustc_codegen_ssa::mir::operand codegen_consume(place_ref=_1)
   0ms DEBUG rustc_codegen_ssa::mir monomorphize: self.instance=Instance { def: Item(DefId(0:13 ~ debuginfo[9fa1]::svwhilelt_b32_u64)), args: [] }
   0ms DEBUG rustc_codegen_ssa::mir::operand maybe_codegen_consume_direct(place_ref=_1)
   0ms DEBUG rustc_codegen_ssa::mir::operand codegen_operand(operand=copy _2)
   0ms DEBUG rustc_codegen_ssa::mir::operand codegen_consume(place_ref=_2)
   0ms DEBUG rustc_codegen_ssa::mir monomorphize: self.instance=Instance { def: Item(DefId(0:13 ~ debuginfo[9fa1]::svwhilelt_b32_u64)), args: [] }
   0ms DEBUG rustc_codegen_ssa::mir::operand maybe_codegen_consume_direct(place_ref=_2)
   0ms DEBUG rustc_codegen_llvm::callee get_fn(instance=Instance { def: Item(DefId(0:15 ~ debuginfo[9fa1]::svwhilelt_b32_u64::{extern#0}::_svwhilelt_b32_u64)), args: [] })
   0ms DEBUG rustc_codegen_llvm::callee get_fn(Instance { def: Item(DefId(0:15 ~ debuginfo[9fa1]::svwhilelt_b32_u64::{extern#0}::_svwhilelt_b32_u64)), args: [] }: FnDef(DefId(0:15 ~ debuginfo[9fa1]::svwhilelt_b32_u64::{extern#0}::_svwhilelt_b32_u64), [])) => llvm.aarch64.sve.whilelo.nxv4i1.i64
   0ms DEBUG rustc_codegen_llvm::declare get_declared_value(name="llvm.aarch64.sve.whilelo.nxv4i1.i64")
   0ms DEBUG rustc_codegen_llvm::declare declare_rust_fn(name="llvm.aarch64.sve.whilelo.nxv4i1.i64", fn_abi=FnAbi { args: [ArgAbi { layout: TyAndLayout { ty: i64, layout: Layout { size: Size(8 bytes), align: AbiAlign { abi: Align(8 bytes) }, backend_repr: Scalar(Initialized { value: Int(I64, true), valid_range: 0..=18446744073709551615 }), fields: Primitive, largest_niche: None, uninhabited: false, variants: Single { index: 0 }, max_repr_align: None, unadjusted_abi_align: Align(8 bytes), randomization_seed: 4294967303 } }, mode: Direct(ArgAttributes { regular: NoUndef, arg_ext: None, pointee_size: Size(0 bytes), pointee_align: None }) }, ArgAbi { layout: TyAndLayout { ty: i64, layout: Layout { size: Size(8 bytes), align: AbiAlign { abi: Align(8 bytes) }, backend_repr: Scalar(Initialized { value: Int(I64, true), valid_range: 0..=18446744073709551615 }), fields: Primitive, largest_niche: None, uninhabited: false, variants: Single { index: 0 }, max_repr_align: None, unadjusted_abi_align: Align(8 bytes), randomization_seed: 4294967303 } }, mode: Direct(ArgAttributes { regular: NoUndef, arg_ext: None, pointee_size: Size(0 bytes), pointee_align: None }) }], ret: ArgAbi { layout: TyAndLayout { ty: svbool4_t, layout: Layout { size: Size(4 bytes), align: AbiAlign { abi: Align(4 bytes) }, backend_repr: ScalableVector { element: Initialized { value: Int(I8, false), valid_range: 0..=1 }, count: 4 }, fields: Arbitrary { offsets: [Size(0 bytes)], in_memory_order: [0] }, largest_niche: Some(Niche { offset: Size(0 bytes), value: Int(I8, false), valid_range: 0..=1 }), uninhabited: false, variants: Single { index: 0 }, max_repr_align: None, unadjusted_abi_align: Align(1 bytes), randomization_seed: 281483566645253 } }, mode: Direct(ArgAttributes { regular: , arg_ext: None, pointee_size: Size(0 bytes), pointee_align: None }) }, c_variadic: false, fixed_count: 2, conv: C, can_unwind: false })
   0ms DEBUG rustc_codegen_llvm::declare declare_raw_fn(name="llvm.aarch64.sve.whilelo.nxv4i1.i64", ty=<vscale x 4 x i1> (i64, i64))
   0ms DEBUG rustc_codegen_llvm::declare declare_simple_fn(name="llvm.aarch64.sve.whilelo.nxv4i1.i64", ty=<vscale x 4 x i1> (i64, i64))
   0ms DEBUG rustc_codegen_llvm::callee get_fn: not casting pointer!
   0ms DEBUG rustc_codegen_llvm::builder call (ptr:; Function Attrs: nocallback nofree nosync nounwind willreturn memory(none) uwtable
 declare <vscale x 4 x i1> @llvm.aarch64.sve.whilelo.nxv4i1.i64(i64, i64) unnamed_addr #2
 ) with args ([(i64:i64 %0), (i64:i64 %1)])
   0ms DEBUG rustc_codegen_ssa::mir monomorphize: self.instance=Instance { def: Item(DefId(0:13 ~ debuginfo[9fa1]::svwhilelt_b32_u64)), args: [] }
   0ms DEBUG rustc_codegen_ssa::mir::block codegen_block(bb1=BasicBlockData { statements: [], after_last_stmt_debuginfos: StmtDebugInfos([]), terminator: Some(Terminator { source_info: SourceInfo { span: src/debuginfo.rs:30:5: 30:51 (#0), scope: scope[0] }, kind: _0 = <svbool4_t as Into<svbool_t>>::into(move _3) -> [return: bb2, unwind continue] }), is_cleanup: false })
   0ms DEBUG rustc_codegen_ssa::mir::block codegen_terminator: Terminator { source_info: SourceInfo { span: src/debuginfo.rs:30:5: 30:51 (#0), scope: scope[0] }, kind: _0 = <svbool4_t as Into<svbool_t>>::into(move _3) -> [return: bb2, unwind continue] }
   0ms DEBUG rustc_codegen_ssa::mir::operand codegen_operand(operand=<svbool4_t as Into<svbool_t>>::into)
   0ms DEBUG rustc_codegen_ssa::mir monomorphize: self.instance=Instance { def: Item(DefId(0:13 ~ debuginfo[9fa1]::svwhilelt_b32_u64)), args: [] }
   0ms DEBUG rustc_codegen_ssa::mir monomorphize: self.instance=Instance { def: Item(DefId(0:13 ~ debuginfo[9fa1]::svwhilelt_b32_u64)), args: [] }
   0ms DEBUG rustc_codegen_ssa::mir monomorphize: self.instance=Instance { def: Item(DefId(0:13 ~ debuginfo[9fa1]::svwhilelt_b32_u64)), args: [] }
   0ms DEBUG rustc_codegen_ssa::mir::operand codegen_operand(operand=move _3)
   0ms DEBUG rustc_codegen_ssa::mir::operand codegen_consume(place_ref=_3)
   0ms DEBUG rustc_codegen_ssa::mir monomorphize: self.instance=Instance { def: Item(DefId(0:13 ~ debuginfo[9fa1]::svwhilelt_b32_u64)), args: [] }
   0ms DEBUG rustc_codegen_ssa::mir::operand maybe_codegen_consume_direct(place_ref=_3)
   0ms DEBUG rustc_codegen_llvm::callee get_fn(instance=Instance { def: Item(DefId(0:10 ~ debuginfo[9fa1]::{impl#0}::into)), args: [] })
   0ms DEBUG rustc_codegen_llvm::builder call (ptr:; Function Attrs: alwaysinline uwtable
 declare internal <vscale x 16 x i1> @_RNvXCsdHHX9MsTYBi_9debuginfoNtB2_9svbool4_tINtNtCs7D9OQsQgQbp_4core7convert4IntoNtB2_8svbool_tE4into(<vscale x 4 x i1>) unnamed_addr #1
 ) with args ([(<vscale x 4 x i1>:  %5 = call <vscale x 4 x i1> @llvm.aarch64.sve.whilelo.nxv4i1.i64(i64 %0, i64 %1) #3, !dbg !20)])
   0ms DEBUG rustc_codegen_ssa::mir monomorphize: self.instance=Instance { def: Item(DefId(0:13 ~ debuginfo[9fa1]::svwhilelt_b32_u64)), args: [] }
   0ms DEBUG rustc_codegen_ssa::mir::block codegen_block(bb2=BasicBlockData { statements: [], after_last_stmt_debuginfos: StmtDebugInfos([]), terminator: Some(Terminator { source_info: SourceInfo { span: src/debuginfo.rs:31:2: 31:2 (#0), scope: scope[0] }, kind: return }), is_cleanup: false })
   0ms DEBUG rustc_codegen_ssa::mir::block codegen_terminator: Terminator { source_info: SourceInfo { span: src/debuginfo.rs:31:2: 31:2 (#0), scope: scope[0] }, kind: return }
   0ms DEBUG rustc_codegen_ssa::mir::operand codegen_consume(place_ref=_0)
   0ms DEBUG rustc_codegen_ssa::mir monomorphize: self.instance=Instance { def: Item(DefId(0:13 ~ debuginfo[9fa1]::svwhilelt_b32_u64)), args: [] }
   0ms DEBUG rustc_codegen_ssa::mir::operand maybe_codegen_consume_direct(place_ref=_0)
 DEBUG rustc_codegen_ssa::mono_item END IMPLEMENTING 'fn svwhilelt_b32_u64 (Fn(Item(DefId(0:13 ~ debuginfo[9fa1]::svwhilelt_b32_u64)), 139834379250504))' in cgu debuginfo.9fa162b06e2e3ac2-cgu.0
 DEBUG rustc_codegen_ssa::mono_item BEGIN IMPLEMENTING 'fn <svbool4_t as Into<svbool_t>>::into (Fn(Item(DefId(0:10 ~ debuginfo[9fa1]::{impl#0}::into)), 139834379250504))' in cgu debuginfo.9fa162b06e2e3ac2-cgu.0
  INFO rustc_codegen_ssa::base codegen_instance(<svbool4_t as Into<svbool_t>>::into)
 rustc_codegen_ssa::mir::codegen_mir instance=Instance { def: Item(DefId(0:10 ~ debuginfo[9fa1]::{impl#0}::into)), args: [] }
   0ms DEBUG rustc_codegen_llvm::callee get_fn(instance=Instance { def: Item(DefId(0:10 ~ debuginfo[9fa1]::{impl#0}::into)), args: [] })
   0ms DEBUG rustc_codegen_ssa::mir fn_abi: FnAbi { args: [ArgAbi { layout: TyAndLayout { ty: svbool4_t, layout: Layout { size: Size(4 bytes), align: AbiAlign { abi: Align(4 bytes) }, backend_repr: ScalableVector { element: Initialized { value: Int(I8, false), valid_range: 0..=1 }, count: 4 }, fields: Arbitrary { offsets: [Size(0 bytes)], in_memory_order: [0] }, largest_niche: Some(Niche { offset: Size(0 bytes), value: Int(I8, false), valid_range: 0..=1 }), uninhabited: false, variants: Single { index: 0 }, max_repr_align: None, unadjusted_abi_align: Align(1 bytes), randomization_seed: 281483566645253 } }, mode: Direct(ArgAttributes { regular: , arg_ext: None, pointee_size: Size(0 bytes), pointee_align: None }) }], ret: ArgAbi { layout: TyAndLayout { ty: svbool_t, layout: Layout { size: Size(16 bytes), align: AbiAlign { abi: Align(16 bytes) }, backend_repr: ScalableVector { element: Initialized { value: Int(I8, false), valid_range: 0..=1 }, count: 16 }, fields: Arbitrary { offsets: [Size(0 bytes)], in_memory_order: [0] }, largest_niche: Some(Niche { offset: Size(0 bytes), value: Int(I8, false), valid_range: 0..=1 }), uninhabited: false, variants: Single { index: 0 }, max_repr_align: None, unadjusted_abi_align: Align(1 bytes), randomization_seed: 281483566645265 } }, mode: Direct(ArgAttributes { regular: , arg_ext: None, pointee_size: Size(0 bytes), pointee_align: None }) }, c_variadic: false, fixed_count: 1, conv: Rust, can_unwind: true }
   0ms DEBUG rustc_codegen_llvm::debuginfo::metadata type_di_node: svbool4_t kind: svbool4_t
   0ms DEBUG rustc_codegen_ssa::mir monomorphize: self.instance=Instance { def: Item(DefId(0:10 ~ debuginfo[9fa1]::{impl#0}::into)), args: [] }
   0ms DEBUG rustc_codegen_ssa::mir monomorphize: self.instance=Instance { def: Item(DefId(0:10 ~ debuginfo[9fa1]::{impl#0}::into)), args: [] }
   0ms DEBUG rustc_codegen_ssa::mir monomorphize: self.instance=Instance { def: Item(DefId(0:10 ~ debuginfo[9fa1]::{impl#0}::into)), args: [] }
   0ms DEBUG rustc_codegen_ssa::mir monomorphize: self.instance=Instance { def: Item(DefId(0:10 ~ debuginfo[9fa1]::{impl#0}::into)), args: [] }
   0ms DEBUG rustc_codegen_ssa::mir::analyze visit_place(place=_1, context=NonMutatingUse(Copy))
   0ms DEBUG rustc_codegen_ssa::mir::analyze visit_place(place=_0, context=MutatingUse(Call))
   0ms DEBUG rustc_codegen_ssa::mir monomorphize: self.instance=Instance { def: Item(DefId(0:10 ~ debuginfo[9fa1]::{impl#0}::into)), args: [] }
   0ms DEBUG rustc_codegen_ssa::mir monomorphize: self.instance=Instance { def: Item(DefId(0:10 ~ debuginfo[9fa1]::{impl#0}::into)), args: [] }
   0ms DEBUG rustc_codegen_ssa::mir monomorphize: self.instance=Instance { def: Item(DefId(0:10 ~ debuginfo[9fa1]::{impl#0}::into)), args: [] }
   0ms DEBUG rustc_codegen_ssa::mir alloc: _0 -> operand
   0ms DEBUG rustc_codegen_ssa::mir monomorphize: self.instance=Instance { def: Item(DefId(0:10 ~ debuginfo[9fa1]::{impl#0}::into)), args: [] }
   0ms DEBUG rustc_codegen_ssa::mir::operand OperandRef::store: operand=Immediate((<vscale x 4 x i1>:<vscale x 4 x i1> %0)), dest=PlaceRef { val: PlaceValue { llval: (ptr:  %2 = alloca <vscale x 4 x i1>, align 4), llextra: None, align: Align(4 bytes) }, layout: TyAndLayout { ty: svbool4_t, layout: Layout { size: Size(4 bytes), align: AbiAlign { abi: Align(4 bytes) }, backend_repr: ScalableVector { element: Initialized { value: Int(I8, false), valid_range: 0..=1 }, count: 4 }, fields: Arbitrary { offsets: [Size(0 bytes)], in_memory_order: [0] }, largest_niche: Some(Niche { offset: Size(0 bytes), value: Int(I8, false), valid_range: 0..=1 }), uninhabited: false, variants: Single { index: 0 }, max_repr_align: None, unadjusted_abi_align: Align(1 bytes), randomization_seed: 281483566645253 } } }
   0ms DEBUG rustc_codegen_llvm::builder Store (<vscale x 4 x i1>:<vscale x 4 x i1> %0) -> (ptr:  %2 = alloca <vscale x 4 x i1>, align 4) (MemFlags(0x0))
   0ms DEBUG rustc_codegen_ssa::mir::block codegen_block(bb0=BasicBlockData { statements: [], after_last_stmt_debuginfos: StmtDebugInfos([]), terminator: Some(Terminator { source_info: SourceInfo { span: src/debuginfo.rs:21:18: 21:41 (#0), scope: scope[0] }, kind: _0 = <svbool4_t as Into<svbool_t>>::into::convert_to_svbool(copy _1) -> [return: bb1, unwind unreachable] }), is_cleanup: false })
   0ms DEBUG rustc_codegen_ssa::mir::block codegen_terminator: Terminator { source_info: SourceInfo { span: src/debuginfo.rs:21:18: 21:41 (#0), scope: scope[0] }, kind: _0 = <svbool4_t as Into<svbool_t>>::into::convert_to_svbool(copy _1) -> [return: bb1, unwind unreachable] }
   0ms DEBUG rustc_codegen_ssa::mir::operand codegen_operand(operand=<svbool4_t as Into<svbool_t>>::into::convert_to_svbool)
   0ms DEBUG rustc_codegen_ssa::mir monomorphize: self.instance=Instance { def: Item(DefId(0:10 ~ debuginfo[9fa1]::{impl#0}::into)), args: [] }
   0ms DEBUG rustc_codegen_ssa::mir monomorphize: self.instance=Instance { def: Item(DefId(0:10 ~ debuginfo[9fa1]::{impl#0}::into)), args: [] }
   0ms DEBUG rustc_codegen_ssa::mir monomorphize: self.instance=Instance { def: Item(DefId(0:10 ~ debuginfo[9fa1]::{impl#0}::into)), args: [] }
   0ms DEBUG rustc_codegen_ssa::mir::operand codegen_operand(operand=copy _1)
   0ms DEBUG rustc_codegen_ssa::mir::operand codegen_consume(place_ref=_1)
   0ms DEBUG rustc_codegen_ssa::mir monomorphize: self.instance=Instance { def: Item(DefId(0:10 ~ debuginfo[9fa1]::{impl#0}::into)), args: [] }
   0ms DEBUG rustc_codegen_ssa::mir::operand maybe_codegen_consume_direct(place_ref=_1)
   0ms DEBUG rustc_codegen_llvm::callee get_fn(instance=Instance { def: Item(DefId(0:12 ~ debuginfo[9fa1]::{impl#0}::into::{extern#0}::convert_to_svbool)), args: [] })
   0ms DEBUG rustc_codegen_llvm::callee get_fn(Instance { def: Item(DefId(0:12 ~ debuginfo[9fa1]::{impl#0}::into::{extern#0}::convert_to_svbool)), args: [] }: FnDef(DefId(0:12 ~ debuginfo[9fa1]::{impl#0}::into::{extern#0}::convert_to_svbool), [])) => llvm.aarch64.sve.convert.to.svbool.nxv4i1
   0ms DEBUG rustc_codegen_llvm::declare get_declared_value(name="llvm.aarch64.sve.convert.to.svbool.nxv4i1")
   0ms DEBUG rustc_codegen_llvm::declare declare_rust_fn(name="llvm.aarch64.sve.convert.to.svbool.nxv4i1", fn_abi=FnAbi { args: [ArgAbi { layout: TyAndLayout { ty: svbool4_t, layout: Layout { size: Size(4 bytes), align: AbiAlign { abi: Align(4 bytes) }, backend_repr: ScalableVector { element: Initialized { value: Int(I8, false), valid_range: 0..=1 }, count: 4 }, fields: Arbitrary { offsets: [Size(0 bytes)], in_memory_order: [0] }, largest_niche: Some(Niche { offset: Size(0 bytes), value: Int(I8, false), valid_range: 0..=1 }), uninhabited: false, variants: Single { index: 0 }, max_repr_align: None, unadjusted_abi_align: Align(1 bytes), randomization_seed: 281483566645253 } }, mode: Direct(ArgAttributes { regular: , arg_ext: None, pointee_size: Size(0 bytes), pointee_align: None }) }], ret: ArgAbi { layout: TyAndLayout { ty: svbool_t, layout: Layout { size: Size(16 bytes), align: AbiAlign { abi: Align(16 bytes) }, backend_repr: ScalableVector { element: Initialized { value: Int(I8, false), valid_range: 0..=1 }, count: 16 }, fields: Arbitrary { offsets: [Size(0 bytes)], in_memory_order: [0] }, largest_niche: Some(Niche { offset: Size(0 bytes), value: Int(I8, false), valid_range: 0..=1 }), uninhabited: false, variants: Single { index: 0 }, max_repr_align: None, unadjusted_abi_align: Align(1 bytes), randomization_seed: 281483566645265 } }, mode: Direct(ArgAttributes { regular: , arg_ext: None, pointee_size: Size(0 bytes), pointee_align: None }) }, c_variadic: false, fixed_count: 1, conv: C, can_unwind: false })
   0ms DEBUG rustc_codegen_llvm::declare declare_raw_fn(name="llvm.aarch64.sve.convert.to.svbool.nxv4i1", ty=<vscale x 16 x i1> (<vscale x 4 x i1>))
   0ms DEBUG rustc_codegen_llvm::declare declare_simple_fn(name="llvm.aarch64.sve.convert.to.svbool.nxv4i1", ty=<vscale x 16 x i1> (<vscale x 4 x i1>))
   0ms DEBUG rustc_codegen_llvm::callee get_fn: not casting pointer!
   0ms DEBUG rustc_codegen_llvm::builder call (ptr:; Function Attrs: nocallback nofree nosync nounwind willreturn memory(none) uwtable
 declare <vscale x 16 x i1> @llvm.aarch64.sve.convert.to.svbool.nxv4i1(<vscale x 4 x i1>) unnamed_addr #2
 ) with args ([(<vscale x 4 x i1>:<vscale x 4 x i1> %0)])
   0ms DEBUG rustc_codegen_ssa::mir monomorphize: self.instance=Instance { def: Item(DefId(0:10 ~ debuginfo[9fa1]::{impl#0}::into)), args: [] }
   0ms DEBUG rustc_codegen_ssa::mir::block codegen_block(bb1=BasicBlockData { statements: [], after_last_stmt_debuginfos: StmtDebugInfos([]), terminator: Some(Terminator { source_info: SourceInfo { span: src/debuginfo.rs:22:6: 22:6 (#0), scope: scope[0] }, kind: return }), is_cleanup: false })
   0ms DEBUG rustc_codegen_ssa::mir::block codegen_terminator: Terminator { source_info: SourceInfo { span: src/debuginfo.rs:22:6: 22:6 (#0), scope: scope[0] }, kind: return }
   0ms DEBUG rustc_codegen_ssa::mir::operand codegen_consume(place_ref=_0)
   0ms DEBUG rustc_codegen_ssa::mir monomorphize: self.instance=Instance { def: Item(DefId(0:10 ~ debuginfo[9fa1]::{impl#0}::into)), args: [] }
   0ms DEBUG rustc_codegen_ssa::mir::operand maybe_codegen_consume_direct(place_ref=_0)
 DEBUG rustc_codegen_ssa::mono_item END IMPLEMENTING 'fn <svbool4_t as Into<svbool_t>>::into (Fn(Item(DefId(0:10 ~ debuginfo[9fa1]::{impl#0}::into)), 139834379250504))' in cgu debuginfo.9fa162b06e2e3ac2-cgu.0
 DEBUG rustc_codegen_llvm::debuginfo finalize
 DEBUG rustc_codegen_llvm::back::write write_output_file output="debuginfo.debuginfo.9fa162b06e2e3ac2-cgu.0.rcgu.o" dwo_output=None
rustc-LLVM ERROR: Cannot select: 0x7f2d8c11dce0: ch = store<(store (<vscale x 1 x s8>) into %ir.3, align 4)> 0x7f2d8c11db20, 0x7f2d8c11d960, FrameIndex:i64<0>, undef:i64
  0x7f2d8c11d960: nxv4i1 = get_active_lane_mask 0x7f2d8c11d7a0, 0x7f2d8c11d880, src/debuginfo.rs:30:14
    0x7f2d8c11d7a0: i64,ch = CopyFromReg 0x7f2d8c0bfc20, Register:i64 %0
    0x7f2d8c11d880: i64,ch = CopyFromReg 0x7f2d8c0bfc20, Register:i64 %1
In function: _RNvCsdHHX9MsTYBi_9debuginfo17svwhilelt_b32_u64
```

</p>
</details>

### PR DESCRIPTION
**Pull request by h3fang**
This pull request tries to fix rust-lang/rust#150419.

The debuginfo for AArch64 SVE predicates `<vscale x N x i1>` where `N != 16` should be ignored by this [commit](https://github.com/rust-lang/rust/pull/143924/changes/89eea57594e3e1d8e618dd530ea1c8e7c9b4c7a4).

https://github.com/rust-lang/rust/blob/89eea57594e3e1d8e618dd530ea1c8e7c9b4c7a4/compiler/rustc_codegen_ssa/src/mir/debuginfo.rs#L438-L452

But in line 446, the `marker_type.kind()` is `ty::Bool` instead of `ty::Slice`, so the code doesn't work as intended.

This pull request uses the [`Ty::scalable_vector_element_count_and_type`](https://github.com/rust-lang/rust/blob/main/compiler/rustc_middle/src/ty/sty.rs#L1272) method to fix the condition checks for  `<vscale x N x i1>` where `N != 16` and add a compiletest for this case.

### CODE REVIEW

File: compiler/rustc_codegen_ssa/src/mir/debuginfo.rs [hunk 1]
```diff
@@ -431,7 +431,7 @@ impl<'a, 'tcx, Bx: BuilderMethods<'a, 'tcx>> FunctionCx<'a, 'tcx, Bx> {
                 // Internally, with an intrinsic operating on a `svint32_t`/`<vscale x 4 x i32>`
                 // (for example), the intrinsic takes the `svbool_t`/`<vscale x 16 x i1>` predicate
                 // and casts it to a `svbool4_t`/`<vscale x 4 x i1>`. Therefore, it's important that
-                // the `<vscale x 4 x i32>` never spills because that'll cause errors during
+                // the `<vscale x 4 x i1>` never spills because that'll cause errors during
                 // instruction selection. Spilling to the stack to create debuginfo for these
                 // intermediate values must be avoided and won't degrade the debugging experience
                 // anyway.
```
Comment (workingjubilee) [inline compiler/rustc_codegen_ssa/src/mir/debuginfo.rs]: I felt slightly uncertain about the form of this on my first pass.

This probably should also be
```suggestion
                // intermediate values must be avoided and doing so won't affect the
                // debugging experience anyway.
```

File: compiler/rustc_codegen_ssa/src/mir/debuginfo.rs [hunk 2]
```diff
@@ -431,22 +431,17 @@ impl<'a, 'tcx, Bx: BuilderMethods<'a, 'tcx>> FunctionCx<'a, 'tcx, Bx> {
...
                 {
-                    let marker_type = marker_type_field.ty(bx.tcx(), args);
+                    let (count, element_ty) =
+                        operand.layout.ty.scalable_vector_element_count_and_type(bx.tcx());
                     // i.e. `<vscale x N x i1>` when `N != 16`
-                    if let ty::Slice(element_ty) = marker_type.kind()
-                        && element_ty.is_bool()
-                        && adt.repr().scalable != Some(ScalableElt::ElementCount(16))
-                    {
+                    if element_ty.is_bool() && count != 16 {
```
Comment (workingjubilee) [inline compiler/rustc_codegen_ssa/src/mir/debuginfo.rs:444]: Ah, the original PR had used slices to represent the "marker type", whereas david's final-er version used single elements because that had less overhead. Apologies, I should have caught that or asked for a test.

File: tests/codegen-llvm/scalable-vectors/debuginfo.rs [hunk 3]
```diff
@@ -0,0 +1,39 @@
+// Compiletest for #150419: Do not spill operand debuginfo to stack for
+// AArch64 SVE predicates `<vscale x N x i1>` where `N != 16`
```
Comment (workingjubilee) [inline tests/codegen-llvm/scalable-vectors/debuginfo.rs]: The word ordering seems funny here. I think this should be more like...
```suggestion
// Compiletest for rust-lang/rust#150419: Do not spill operands to the stack when creating debuginfo for
// AArch64 SVE predicates `<vscale x N x i1>` where `N != 16`
```

File: tests/ui/scalable-vectors/debuginfo-does-not-spill.rs
Comment (workingjubilee) [inline tests/ui/scalable-vectors/debuginfo-does-not-spill.rs:1]: Yay test. Should this be "debuginfo-does-not-spill.rs"? Just "debuginfo" seems off since we're testing a particular aspect here. "debuginfo-aarch64-sve.rs" would also be fine.

File: tests/ui/scalable-vectors/debuginfo-does-not-spill.rs [hunk 4]
```diff
@@ -0,0 +1,39 @@
...
+    }
+}
+
+pub fn svwhilelt_b32_u64(op1: u64, op2: u64) -> svbool_t {
+    unsafe extern "C" {
+        #[link_name = "llvm.aarch64.sve.whilelo.nxv4i1.u64"]
+        fn _svwhilelt_b32_u64(op1: u64, op2: u64) -> svbool4_t;
+    }
+    unsafe { _svwhilelt_b32_u64(op1, op2) }.into()
+}
```
Comment (workingjubilee) [inline tests/ui/scalable-vectors/debuginfo-does-not-spill.rs:39]: Yay test... but why doesn't it have any FileCheck comments to verify the LLVMIR for this looks a particular way? Is it because we are just hoping for LLVM to scream because it will fail isel if the debuginfo generation turns wrong? I feel like it should at least contain a basic "existence check" for *something*, here, as I don't feel super-confident that this test would always have failed before this PR, because in-principle LLVM doesn't have to reach actual machine instruction generation in order to emit LLVMIR, and this test suite only evaluates LLVMIR generation.

The problem as I understand it is about LLVM's failure during machine instruction selection. Even if it happens to *also* always perform it for this test suite, it doesn't actually relate, and it should be in "tests/assembly-llvm" if we aren't actually testing the shape of LLVMIR but want to assert something about the shape of the assembly.

If it shouldn't actually have any FileCheck comments at all, though, it should be in "tests/ui" and keep the existing `//@ build-pass` annotation, because that's where we put "the build works at all" tests.

File: tests/ui/scalable-vectors/debuginfo-does-not-spill.rs [hunk 5]
```diff
@@ -0,0 +1,39 @@
+// Compiletest for #150419: Do not spill operand debuginfo to stack for
+// AArch64 SVE predicates `<vscale x N x i1>` where `N != 16`
+//@ edition: 2021
+//@ only-aarch64
+//@ build-pass
```
Comment (workingjubilee) [inline tests/ui/scalable-vectors/debuginfo-does-not-spill.rs:5]: I believe this is the line that enforces that LLVM's ISel happens. Note that its sister test, simple.rs, does not have this line. Almost nothing in the codegen-llvm test suite has the `//@ build-pass` annotation, and we shouldn't increase the exception count beyond 1 without reason.

**Review by workingjubilee — CHANGES_REQUESTED** [review]
I have a few comments about comments and a minor quibble about where to put the test.

*[View changes since this review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/rust/150420/38ed7700e7ba3adb7af96e3dcb2ba6dfa3a0c951..0479d980e80b47460b6f05b77e21b1d416d8416a)*

File: tests/ui/scalable-vectors/debuginfo-does-not-spill.rs (hunk 4 above)
Comment (workingjubilee) [reply tests/ui/scalable-vectors/debuginfo-does-not-spill.rs:39]: tl;dr this comment can be addressed with `git mv tests/codegen-llvm/scalable-vectors/debuginfo.rs tests/ui/scalable-vectors/aarch64-sve-debuginfo.rs`

File: compiler/rustc_codegen_ssa/src/mir/debuginfo.rs (hunk 1 above)
Comment (h3fang) [reply compiler/rustc_codegen_ssa/src/mir/debuginfo.rs]: Fixed

File: compiler/rustc_codegen_ssa/src/mir/debuginfo.rs (hunk 2 above)
Comment (h3fang) [reply compiler/rustc_codegen_ssa/src/mir/debuginfo.rs:444]: I was wondering why `ty::Slice` was there, that makes sense now. Thanks!

File: tests/codegen-llvm/scalable-vectors/debuginfo.rs (hunk 3 above)
Comment (h3fang) [reply tests/codegen-llvm/scalable-vectors/debuginfo.rs]: Initially, I used "Don't spill `<vscale x N x i1>` for `N != 16`" from David's [comment](https://github.com/rust-lang/rust/pull/143924/changes/89eea57594e3e1d8e618dd530ea1c8e7c9b4c7a4#diff-e988b87653090cb5afac30ee289e6e276036c6ec08d6210af77c0994e6e9a9a8R411). Then I realized that was too vague for a [test comment](https://rustc-dev-guide.rust-lang.org/tests/adding.html#comment-explaining-what-the-test-is-about). I added a few more words there, but didn't try to make it better. :man_facepalming: 

Fixed.

File: tests/ui/scalable-vectors/debuginfo-does-not-spill.rs
Comment (h3fang) [reply tests/ui/scalable-vectors/debuginfo-does-not-spill.rs:1]: I think "debuginfo-does-not-spill.rs" is better, since we are not testing for other sve types like `svbool_t` or `svfloat32_t`.

Fixed.

File: tests/ui/scalable-vectors/debuginfo-does-not-spill.rs (hunk 4 above)
Comment (h3fang) [reply tests/ui/scalable-vectors/debuginfo-does-not-spill.rs:39]: Yes, I was hoping for "LLVM to scream because it will fail isel if the debuginfo generation turns wrong? ". 🤦‍♂️

I was considering add a test similar to [`tests/debuginfo/simd.rs`](https://github.com/rust-lang/rust/blob/main/tests/debuginfo/simd.rs) with content like creating a  `tests/debuginfo/scalable-vectors-predicates.rs` with
```rust
//@ only-aarch64

//@ compile-flags:-g -C target-feature=+sve
//@ disable-gdb-pretty-printers
//@ ignore-backends: gcc
//@ gdb-command:run

//@ gdb-command:print b16
//@ gdb-check:$1 = scalable_vectors_predicates::svbool_t (255)
//@ gdb-command:print b8
//@ gdb-check:$2 = <optimized out>
//@ gdb-command:print b4
//@ gdb-check:$3 = <optimized out>
//@ gdb-command:print b2
//@ gdb-check:$4 = <optimized out>

//@ gdb-command:continue

#![allow(internal_features)]
#![feature(rustc_attrs, link_llvm_intrinsics)]

macro_rules! impl_sve_type {
    ($(($name:ident, $elem_type:ty, $elt:literal))*) => ($(
        #[derive(Copy, Clone)]
        #[rustc_scalable_vector($elt)]
        #[allow(non_camel_case_types)]
        #[repr(transparent)]
        struct $name($elem_type);
    )*)
}

impl_sve_type! {
    (svbool_t, bool, 16)
    (svbool8_t, bool, 8)
    (svbool4_t, bool, 4)
    (svbool2_t, bool, 2)
}

#[repr(i32)]
#[allow(non_camel_case_types)]
#[derive(Clone, Copy, PartialEq, Eq)]
#[non_exhaustive]
pub enum svpattern {
    SV_ALL = 31,
}

unsafe extern "C" {
    #[cfg_attr(target_arch = "aarch64", link_name = "llvm.aarch64.sve.ptrue.nxv16i1")]
    fn svptrue_pat_b8(pattern: svpattern) -> svbool_t;
    #[cfg_attr(target_arch = "aarch64", link_name = "llvm.aarch64.sve.ptrue.nxv8i1")]
    fn svptrue_pat_b16(pattern: svpattern) -> svbool8_t;
    #[cfg_attr(target_arch = "aarch64", link_name = "llvm.aarch64.sve.ptrue.nxv4i1")]
    fn svptrue_pat_b32(pattern: svpattern) -> svbool4_t;
    #[cfg_attr(target_arch = "aarch64", link_name = "llvm.aarch64.sve.ptrue.nxv2i1")]
    fn svptrue_pat_b64(pattern: svpattern) -> svbool2_t;
}

fn main() {
    let b16 = unsafe { svptrue_pat_b8(svpattern::SV_ALL) };
    let b8 = unsafe { svptrue_pat_b16(svpattern::SV_ALL) };
    let b4 = unsafe { svptrue_pat_b32(svpattern::SV_ALL) };
    let b2 = unsafe { svptrue_pat_b64(svpattern::SV_ALL) };

    zzz(); //break
}

#[inline(never)]
fn zzz() {
    ()
}
```
I figured out that the [`tests/debuginfo/simd.rs`](https://github.com/rust-lang/rust/blob/main/tests/debuginfo/simd.rs) test has to be compiled and ran with the debugger. I was not sure whether rust's CI machines have SVE support or not. So, I did not add that test.

Do you think we should use this approach or just `git mv tests/codegen-llvm/scalable-vectors/debuginfo.rs tests/ui/scalable-vectors/aarch64-sve-debuginfo.rs` ?

Comment (workingjubilee) [reply tests/ui/scalable-vectors/debuginfo-does-not-spill.rs:39]: Our CI machines probably do not have such support so they cannot meaningfully execute such a program, no.

File: tests/ui/scalable-vectors/debuginfo-does-not-spill.rs (hunk 5 above)
Comment (h3fang) [reply tests/ui/scalable-vectors/debuginfo-does-not-spill.rs:5]: Agree. Fixed.

File: tests/ui/scalable-vectors/debuginfo-does-not-spill.rs (hunk 4 above)
Comment (h3fang) [reply tests/ui/scalable-vectors/debuginfo-does-not-spill.rs:39]: OK, fixed.

**Comment by workingjubilee** [comment]
Excellent, excellent, happy to have it.

@bors r+ rollup
