### PR TITLE
Detect JS-style `===` and `!==` and recover

### LINKED ISSUE #75312: Provide auto-fix suggestion for triple equals
Been working in JavaScript a lot lately and find myself accidentally typing this a lot. It would be nice to automatically detect this and offer a proper fix. Lots of languages use this syntax in addition to JavaScript so it seems like a reasonable error to make.

Playground example below.

```rust
#![feature(test)]
use std::hint::black_box;
fn main() {
    if 1 === black_box(1) {
        println!("yup!");
    } else if 2 !== black_box(2) {
        println!("nope!");
    }
}
```

([Playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=1dd65e329efa94cdb700c6b648f8ebfb))

Errors:

```
   Compiling playground v0.0.1 (/playground)
error: expected expression, found `=`
 --> src/main.rs:4:12
  |
4 |     if 1 === black_box(1) {
  |            ^ expected expression

warning: unused import: `std::hint::black_box`
 --> src/main.rs:2:5
  |
2 | use std::hint::black_box;
  |     ^^^^^^^^^^^^^^^^^^^^
  |
  = note: `#[warn(unused_imports)]` on by default

error: aborting due to previous error; 1 warning emitted

error: could not compile `playground`.

To learn more, run the command again with --verbose.

```

### PR DESCRIPTION
**Pull request by estebank**
Fix #75312.

### CODE REVIEW

File: src/librustc_parse/parser/expr.rs [hunk 1]
```diff
@@ -195,6 +195,28 @@ impl<'a> Parser<'a> {
                     return Ok(expr);
                 }
             }
+
+            if (op.node == AssocOp::Equal || op.node == AssocOp::NotEqual)
+                && self.token.kind == token::Eq
```
Comment (lcnr) [inline src/librustc_parse/parser/expr.rs:200]: how does this deal with `a == = B`?

**Review by davidtwco — APPROVED** [review]
LGTM, r=me after resolving existing comments

File: src/librustc_parse/parser/expr.rs (hunk 1 above)
Comment (estebank) [reply src/librustc_parse/parser/expr.rs:200]: It will suggest it's removal. It doesn't differentiate between `===` and `== =`. Didn't add any logic to do so because the later would never be valid logic. Similarly, this won't trigger on `= ==`, which I thought acceptable.

Comment (lcnr) [reply src/librustc_parse/parser/expr.rs:200]: My main concern is that the error message will mention `===` which isn't what's actually written, but that really isn't important enough to spend a lot of time on :laughing: so feel free to go ahead and merge this even if you don't want to fix this

Comment (estebank) [reply src/librustc_parse/parser/expr.rs:200]: Done :)

**Comment by estebank** [comment]
@bors retry

```
2020-08-11T06:15:26.6759676Z Preparing to unpack .../python3-setuptools_39.0.1-2_all.deb ...
2020-08-11T06:15:26.6805197Z Unpacking python3-setuptools (39.0.1-2) ...
2020-08-11T06:15:26.7645131Z Setting up python3-setuptools (39.0.1-2) ...
2020-08-11T06:15:28.3118620Z   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
2020-08-11T06:15:28.3118927Z                                  Dload  Upload   Total   Spent    Left  Speed
2020-08-11T06:15:28.3119032Z 
2020-08-11T06:15:28.4342240Z   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
2020-08-11T06:15:28.4342780Z  41 9230k   41 3838k    0     0  30.7M      0 --:--:-- --:--:-- --:--:-- 30.7M
2020-08-11T06:15:28.4342986Z curl: (56) OpenSSL SSL_read: SSL_ERROR_SYSCALL, errno 104
2020-08-11T06:15:28.4362538Z tar: Unexpected EOF in archive
2020-08-11T06:15:28.4362826Z tar: Unexpected EOF in archive
2020-08-11T06:15:28.4363255Z tar: Error is not recoverable: exiting now
2020-08-11T06:15:28.4375872Z ##[error]Process completed with exit code 2.
2020-08-11T06:15:28.4445285Z Cleaning up orphan processes
2020-08-11T06:15:28.4843168Z Terminate orphan process: pid (3162) (node)
2020-08-11T06:15:28.4855239Z Terminate orphan process: pid (3190) (python)
```
