### PR TITLE
Detect incorrect chaining of if and if let conditions and recover

### LINKED ISSUE #103381: Detect incorrect chaining of `if` and `if let` conditions and recover gracefully
Given

```rust
fn foo(b: bool, x: Option<u32>) {
    if b && if let Some(x) = x {}
}
fn main() {
    if true && if true { true }
}
```

[the current output is](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=28db46bf3ce2d2c7d3dae7305740e8ee)

```
error: expected `{`, found `}`
 --> src/main.rs:3:1
  |
3 | }
  | ^ expected `{`
  |
note: the `if` expression is missing a block after this condition
 --> src/main.rs:2:8
  |
2 |     if b && if let Some(x) = x {}
  |        ^^^^^^^^^^^^^^^^^^^^^^^^^^

error: expected `{`, found `}`
 --> src/main.rs:6:1
  |
6 | }
  | ^ expected `{`
  |
note: the `if` expression is missing a block after this condition
 --> src/main.rs:5:8
  |
5 |     if true && if true { true }
  |        ^^^^^^^^^^^^^^^^^^^^^^^^
```

We should detect that what was intended was

```rust
fn foo(b: bool, x: Option<u32>) {
    if b && let Some(x) = x {}
}
fn main() {
    if true && true { true }
}
```

_https://github.com/rust-lang/rust/issues/53667#issuecomment-1228604924_

### PR DESCRIPTION
**Pull request by chenyukang**
Fixes #103381

### CODE REVIEW

**Review by compiler-errors — CHANGES_REQUESTED** [review]
This breaks existing code -- `if` expressions are allowed to be their own conditions within other `if` statements.

```rust
fn main() {
    if true && if let 1 = 1 { true } else { true } {}
}
```

Before this PR: compiles

After this PR:
```rust
error: unexpected `if` in the condition expression
 --> /home/gh-compiler-errors/test.rs:2:16
  |
2 |     if true && if let 1 = 1 { true } else { true } {}
  |                ^^^
  |
help: remove the `if`
  |
2 -     if true && if let 1 = 1 { true } else { true } {}
2 +     if true && let 1 = 1 { true } else { true } {}
  |

error[E0658]: `let` expressions in this position are unstable
 --> /home/gh-compiler-errors/test.rs:2:19
  |
2 |     if true && if let 1 = 1 { true } else { true } {}
  |                   ^^^^^^^^^
  |
  = note: see issue #53667 <https://github.com/rust-lang/rust/issues/53667> for more information
  = help: add `#![feature(let_chains)]` to the crate attributes to enable

error[E0308]: mismatched types
 --> /home/gh-compiler-errors/test.rs:2:31
  |
2 |     if true && if let 1 = 1 { true } else { true } {}
  |     --------------------------^^^^----------------
  |     |                         |
  |     |                         expected `()`, found `bool`
  |     expected this to be `()`

error[E0308]: mismatched types
 --> /home/gh-compiler-errors/test.rs:2:45
  |
2 |     if true && if let 1 = 1 { true } else { true } {}
  |     ----------------------------------------^^^^--
  |     |                                       |
  |     |                                       expected `()`, found `bool`
  |     expected this to be `()`

error: aborting due to 4 previous errors

Some errors have detailed explanations: E0308, E0658.
For more information about an error, try `rustc --explain E0308`.
```

**Comment by chenyukang** [comment]
> This breaks existing code -- `if` expressions are allowed to be their own conditions within other `if` statements.

This code will also compile in current compiler:

```rust

fn should_ok() {
    if true && if let 1 = 1 { true } else { true } {}
}
```

With this warning:

```console
warning: irrefutable `if let` pattern
  --> /home/cat/code/rust/src/test/ui/parser/issue-103381.rs:13:19
   |
13 |     if true && if let x = 1 { true } else { true } {}
   |                   ^^^^^^^^^
   |
   = note: `#[warn(irrefutable_let_patterns)]` on by default
   = note: this pattern will always match, so the `if let` is useless
   = help: consider replacing the `if let` with a `let`

warning: 1 warning emitted
```

**Comment by compiler-errors** [comment]
Just noting that "irrefutable `if let` pattern" warning is unrelated to this issue, and is just because `let x = 1` is a "irrefutable" binding, i.e. not actually conditional.

**Comment by chenyukang** [comment]
> The job **`x86_64-gnu-llvm-13`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/actions/runs/3303928537/jobs/5452437996) [(plain)](https://github.com/rust-lang/rust/commit/81d18e37d98c0cdfdf5d5a71263180753b52555e/checks/9047738495/logs)
> 
> Click to see the possible cause of the failure (guessed by this bot)

From the UI testing result, we have this syntax：

```rust
fn shoule_match_ok() {
    #[cfg(feature = "full")]
    {
        let a = 1;
        let b = 2;
        if match a {
            1 if b == 1 => true,
            _ => false,
        } && if a > 1 { true } else { false }
        {
            true
        }
    }
}
```

I think it's not a readable code, but it compiled and runnable 😂
Anyway, I plan to restrict this suggestion to limited scenarios:

```rust
  // recovery from `if b && if let Some(x)`
            if op == AssocOp::LAnd
                && self.token.is_keyword(kw::If)
                && self.look_ahead(1, |t| t.is_bool_lit())
                || (self.look_ahead(1, |t| t.is_keyword(kw::Let))
                    && self.look_ahead(2, |t| {
                        t.is_ident_named(sym::Some) || t.is_ident_named(sym::None)
                    }))
            {
                // eat the `if`
                self.bump();
                self.sess.emit_err(UnexpectedIfWithIf(
                    self.prev_token.span.to(self.token.span.shrink_to_lo()),
                ));
            }
```

Not sure whether there is a better way.

**Comment by compiler-errors** [comment]
@chenyukang, this approach still has issues:

```rust
fn main() {
    if true && if true { true } else { false } {}
}
```

This fails to compile with your new changes:

```
error: unexpected `if` in the condition expression
 --> /home/gh-compiler-errors/test.rs:2:16
  |
2 |     if true && if true { true } else { false } {}
  |                ^^^
  |
help: remove the `if`
  |
2 -     if true && if true { true } else { false } {}
2 +     if true && true { true } else { false } {}
  |

error[E0308]: mismatched types
 --> /home/gh-compiler-errors/test.rs:2:26
  |
2 |     if true && if true { true } else { false } {}
  |     ---------------------^^^^-----------------
  |     |                    |
  |     |                    expected `()`, found `bool`
  |     expected this to be `()`

error[E0308]: mismatched types
 --> /home/gh-compiler-errors/test.rs:2:40
  |
2 |     if true && if true { true } else { false } {}
  |     -----------------------------------^^^^^--
  |     |                                  |
  |     |                                  expected `()`, found `bool`
  |     expected this to be `()`

error: aborting due to 3 previous errors
```

----

I'm pretty sure it's impossible to detect #103381 inside of `parse_assoc_expr_with` -- you need to add a suggestion to remove `if` only _after_ the parser has already detected an error, probably by passing the correct state down to `parse_if_after_cond` or some similar function that is involved in parsing `if` statements.

**Comment by chenyukang** [comment]
Ok, I will have look later

Michael Goulet ***@***.***> 于 2022年10月23日周日 14:06写道：

**Comment by Nilstrieb** [comment]
Hi, I've seen you changed some diagnostic structs in your PR. After #103345, the way we refer to fluent messages changed. They are now in a flat namespace with the same identifier as in the fluent file. For example,  `parser::cool_thing` is now `parser_cool_thing` and `parser::suggestion` just `suggestion`.
You should [rebase](https://rustc-dev-guide.rust-lang.org/git.html#rebasing-and-conflicts) to the latest master and change your fluent message references as described above. Thanks!

**Comment by chenyukang** [comment]
> This may be hard to do, or not worth the changes to the parser to allow this state to be tracked.

Take some time investigating it.
Yes, seems it is not easy since we need to rollback too much.
I think we'd better don't try to suggest and fix this case right now:

```rust
 let _ = if true && if true { true } else { false };
 let _ = if true && if false { true } else { false };
```

Only add check for `&& if let Options`...

File: compiler/rustc_parse/src/parser/expr.rs [hunk 1]
```diff
@@ -313,6 +313,20 @@ impl<'a> Parser<'a> {
                 break;
             }
 
+            // recovery from `if b && if let Some(x)`
+            if op == AssocOp::LAnd
+                && self.token.is_keyword(kw::If)
+                && self.look_ahead(1, |t| t.is_keyword(kw::Let))
+                && self
+                    .look_ahead(2, |t| t.is_ident_named(sym::Some) || t.is_ident_named(sym::None))
```
Comment (camsteffen) [inline compiler/rustc_parse/src/parser/expr.rs:321]: The following code is perfectly valid:
```rust
if true
    && if let Some(1) = Some(1) { true } else { true }
{
    todo!()
}
```
In general, it is always possible to write valid code containing `if <some condition> && if let <some pattern>`.

I don't think it's possible to detect the scenario you're looking for until _after_ you parse the inner `if let ..` expression.

**Comment by compiler-errors** [comment]
@chenyukang, camsteffen is correct, and as I noted in [my previous comment](https://github.com/rust-lang/rust/pull/103405#issuecomment-1288015937), I'm pretty sure it's impossible to detect #103381 inside of `parse_assoc_expr_with`. 

This check needs to live in another function using a different strategy, after parsing has detected a failure.

**Comment by chenyukang** [comment]
> @chenyukang, camsteffen is correct, and as I noted in [my previous comment](https://github.com/rust-lang/rust/pull/103405#issuecomment-1288015937), I'm pretty sure it's impossible to detect #103381 inside of `parse_assoc_expr_with`. Marking as `S-waiting-on-author` until this PR is reformulated.
> 
> This check needs to live in another function using a different strategy, after parsing has detected a failure. Be very careful about adding parser recoveries before we've detected an error, since it's [very1](https://github.com/rust-lang/rust/pull/103986) [easy2](https://github.com/rust-lang/rust/pull/97474#issuecomment-1141922957) to accidentally introduce changes in parser behavior while improving error messages during parsing...

Got it, thanks!
I didn't understand the trivial differences between those code pattern.

**Comment by chenyukang** [comment]
I think we'd better don't recover from these scenarios, but give proper diagnostics 😁
Code updated.

File: src/test/ui/parser/issue-103381.stderr [hunk 2]
```diff
@@ -0,0 +1,50 @@
...
+error: unexpected `if` in the condition expression
+  --> $DIR/issue-103381.rs:19:15
+   |
+LL |     if true && if true { true } else { false };
+   |               ^^^^
+   |
+help: remove the `if`
+   |
+LL -     if true && if true { true } else { false };
+LL +     if true && true { true } else { false };
```
Comment (estebank) [inline src/test/ui/parser/issue-103381.stderr:34]: What happens for `if true && if true { true } else { false } { true } else { false };`?

Comment (compiler-errors) [reply src/test/ui/parser/issue-103381.stderr:34]: > Given where you call the recovery it should succeed, right? 

yeah, this is my thinking. I'll give this a better review later, but I much prefer this approach since it's already deep in the "bad path".

Comment (chenyukang) [reply src/test/ui/parser/issue-103381.stderr:34]: Yes, this code will compile successfully, I have added it as a UI.

**Comment by compiler-errors** [comment]
@rustbot ready

I will get around to reviewing this soon.

**Comment by chenyukang** [comment]
@rustbot ready

conflict resolved.
