### PR TITLE
Fix issue for module name when surround the struct literal with parentheses

### LINKED ISSUE #112278: Suggestion to "surround the struct literal in parentheses" sometimes places the opening parenthesis after the module name
### Code

```Rust
mod module {
    #[derive(Eq, PartialEq)]
    pub struct Type {
        pub x: u8,
        pub y: u8,
    }

    pub const C: u8 = 32u8;
}

fn test(x: module::Type) -> i32 {
    if x == module::Type { x: module::C, y: 1 } {
        1
    } else {
        0
    }
}
```

### Current output

```Shell
error: invalid struct literal
  --> <source>:12:21
   |
12 |     if x == module::Type { x: module::C, y: 1 } {
   |                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
help: you might need to surround the struct literal in parentheses
   |
12 |     if x == module::(Type { x: module::C, y: 1 }) {
   |                     +                           +
```

### Desired output

```Shell
error: invalid struct literal
  --> <source>:12:21
   |
12 |     if x == module::Type { x: module::C, y: 1 } {
   |                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
help: you might need to surround the struct literal in parentheses
   |
12 |     if x == (module::Type { x: module::C, y: 1 }) {
   |             +                                   +
```

### Rationale and extra context

_No response_

### Other cases

_No response_

### Anything else?

This defect is reproducible with (at least) 1.68, 1.69, beta, and nightly.

Furthermore, I think it would be good to reword the message to suggest surrounding _with_ parentheses.

### PR DESCRIPTION
**Pull request by chenyukang**
Fixes #112278

### CODE REVIEW

File: compiler/rustc_parse/src/parser/diagnostics.rs [hunk 1]
```diff
@@ -751,10 +751,18 @@ impl<'a> Parser<'a> {
                     tail.could_be_bare_literal = true;
                     if maybe_struct_name.is_ident() && can_be_struct_literal {
                         // Account for `if Example { a: one(), }.is_pos() {}`.
+                        // expand `before` so that we take care of module path such as:
+                        // `foo::Bar { ... } `
+                        // we expect to suggest `(foo::Bar { ... })` instead of `foo::(Bar { ... })`
+                        let sm = self.sess.source_map();
+                        let before = maybe_struct_name.span.shrink_to_lo();
```
Comment (chenyukang) [inline compiler/rustc_parse/src/parser/diagnostics.rs:758]: It's not a great way, but in the parsing phase, we don't have more context here?
any better solution?

Comment (compiler-errors) [reply compiler/rustc_parse/src/parser/diagnostics.rs:758]: > we don't have more context here?

Probably not.... We'd need to pass in more span information here, which it seems like we don't have.

File: compiler/rustc_parse/src/parser/diagnostics.rs [hunk 2]
```diff
@@ -751,10 +751,18 @@ impl<'a> Parser<'a> {
...
+                        let extend_before = sm.span_extend_prev_while(before, |t| {
+                            t.is_alphanumeric() || t == ':' || t == '_'
+                        });
                         Err(self.sess.create_err(StructLiteralNeedingParens {
                             span: maybe_struct_name.span.to(expr.span),
                             sugg: StructLiteralNeedingParensSugg {
-                                before: maybe_struct_name.span.shrink_to_lo(),
+                                before: extend_before.unwrap().shrink_to_lo(),
```
Comment (compiler-errors) [inline compiler/rustc_parse/src/parser/diagnostics.rs:765]: Unwrap is probably not a good idea, will cause an ICE probably 😰 -- we shouldn't be giving a suggestion if `span_extend_prev_while` fails.

Maybe just return `None`?

File: compiler/rustc_parse/src/parser/diagnostics.rs (hunk 1 above)
Comment (chenyukang) [reply compiler/rustc_parse/src/parser/diagnostics.rs:758]: It seems we need to get the spans of several previous tokens here, since the module path may contain multiple tokens, while `parser` keep `prev_token` and `token`.

Comment (compiler-errors) [reply compiler/rustc_parse/src/parser/diagnostics.rs:758]: I think this approach is ok

File: compiler/rustc_parse/src/parser/diagnostics.rs (hunk 2 above)
Comment (chenyukang) [reply compiler/rustc_parse/src/parser/diagnostics.rs]: fixed :)
