### PR TITLE
Check the number of generic lifetime and const parameters of intrinsics

### LINKED ISSUE #85855: ICE: compiler/rustc_middle/src/ty/generics.rs:188:18: expected type parameter, but found another generic parameter
### Code

```Rust
extern "platform-intrinsic" {
    fn simd_saturating_add<'a, T: 'a>(x: T, y: T);
}
```

### Meta

`rustc --version --verbose`:
```
rustc 1.54.0-nightly (c1e8f3a58 2021-05-30)
binary: rustc
commit-hash: c1e8f3a5857c3c8d095fd212acc6ed442f4cc58b
commit-date: 2021-05-30
host: x86_64-unknown-linux-gnu
release: 1.54.0-nightly
LLVM version: 12.0.1
```

### Error output

```
error[E0658]: platform intrinsics are experimental and possibly buggy
 --> mutant.rs:1:8
  |
1 | extern "platform-intrinsic" {
  |        ^^^^^^^^^^^^^^^^^^^^
  |
  = note: see issue #27731 <https://github.com/rust-lang/rust/issues/27731> for more information
  = help: add `#![feature(platform_intrinsics)]` to the crate attributes to enable

error[E0601]: `main` function not found in crate `mutant`
 --> mutant.rs:1:1
  |
1 | / extern "platform-intrinsic" {
2 | |     fn simd_saturating_add<'a, T: 'a>(x: T, y: T);
3 | | }
  | |_^ consider adding a `main` function to `mutant.rs`

error: internal compiler error: compiler/rustc_middle/src/ty/generics.rs:188:18: expected type parameter, but found another generic parameter

thread 'rustc' panicked at 'Box<Any>', compiler/rustc_errors/src/lib.rs:1005:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.54.0-nightly (c1e8f3a58 2021-05-30) running on x86_64-unknown-linux-gnu

query stack during panic:
#0 [check_mod_item_types] checking item types in top-level module
#1 [analysis] running analysis passes on this crate
end of query stack
error: aborting due to 3 previous errors

Some errors have detailed explanations: E0601, E0658.
For more information about an error, try `rustc --explain E0601`.
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
error[E0658]: platform intrinsics are experimental and possibly buggy
 --> mutant.rs:1:8
  |
1 | extern "platform-intrinsic" {
  |        ^^^^^^^^^^^^^^^^^^^^
  |
  = note: see issue #27731 <https://github.com/rust-lang/rust/issues/27731> for more information
  = help: add `#![feature(platform_intrinsics)]` to the crate attributes to enable

error[E0601]: `main` function not found in crate `mutant`
 --> mutant.rs:1:1
  |
1 | / extern "platform-intrinsic" {
2 | |     fn simd_saturating_add<'a, T: 'a>(x: T, y: T);
3 | | }
  | |_^ consider adding a `main` function to `mutant.rs`

error: internal compiler error: compiler/rustc_middle/src/ty/generics.rs:188:18: expected type parameter, but found another generic parameter

thread 'rustc' panicked at 'Box<Any>', compiler/rustc_errors/src/lib.rs:1005:9
stack backtrace:
   0: std::panicking::begin_panic
   1: std::panic::panic_any
   2: rustc_errors::HandlerInner::bug
   3: rustc_errors::Handler::bug
   4: rustc_middle::ty::context::tls::with_opt
   5: rustc_middle::util::bug::opt_span_bug_fmt
   6: rustc_middle::util::bug::bug_fmt
   7: rustc_middle::ty::generics::Generics::type_param
   8: rustc_middle::ty::error::<impl rustc_middle::ty::context::TyCtxt>::note_and_explain_type_err
   9: rustc_infer::infer::error_reporting::<impl rustc_infer::infer::InferCtxt>::note_type_err
  10: rustc_infer::infer::error_reporting::<impl rustc_infer::infer::InferCtxt>::report_and_explain_type_error
  11: rustc_infer::infer::InferCtxt::report_mismatched_types
  12: rustc_infer::infer::InferCtxtBuilder::enter
  13: rustc_typeck::check::intrinsic::equate_intrinsic_type
  14: rustc_typeck::check::intrinsic::check_platform_intrinsic_type
  15: rustc_typeck::check::check::check_item_type
  16: rustc_middle::hir::map::Map::visit_item_likes_in_module
  17: rustc_typeck::check::check::check_mod_item_types
  18: rustc_query_system::query::plumbing::get_query_impl
  19: <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::check_mod_item_types
  20: rustc_session::utils::<impl rustc_session::session::Session>::time
  21: rustc_typeck::check_crate
  22: rustc_interface::passes::analysis
  23: rustc_query_system::query::plumbing::get_query_impl
  24: <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::analysis
  25: rustc_interface::passes::QueryContext::enter
  26: rustc_interface::queries::<impl rustc_interface::interface::Compiler>::enter
  27: rustc_span::with_source_map
  28: scoped_tls::ScopedKey<T>::set
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.54.0-nightly (c1e8f3a58 2021-05-30) running on x86_64-unknown-linux-gnu

query stack during panic:
#0 [check_mod_item_types] checking item types in top-level module
#1 [analysis] running analysis passes on this crate
end of query stack
error: aborting due to 3 previous errors

Some errors have detailed explanations: E0601, E0658.
For more information about an error, try `rustc --explain E0601`.
```

</p>
</details>

### PR DESCRIPTION
**Pull request by FabianWolff**
This pull request fixes #85855. The current code for type checking intrinsics only checks the number of generic _type_ parameters, but does not check for an incorrect number of lifetime or const parameters, which can cause problems later on, such as the ICE in #85855, where the code thought that it was looking at a type parameter but found a lifetime parameter:
```
error: internal compiler error: compiler/rustc_middle/src/ty/generics.rs:188:18:
    expected type parameter, but found another generic parameter
```

The changes in this PR add checks for the number of lifetime and const parameters, expand the scope of `E0094` to also apply to these cases, and improve the error message by properly pluralizing the number of expected generic parameters.

### CODE REVIEW

File: compiler/rustc_typeck/src/check/intrinsic.rs [hunk 1]
```diff
@@ -21,36 +21,68 @@ fn equate_intrinsic_type<'tcx>(
...
+    n_lts: usize,
     sig: ty::PolyFnSig<'tcx>,
 ) {
-    match it.kind {
-        hir::ForeignItemKind::Fn(..) => {}
+    let (gen_lts, gen_tys, gen_cns, span) = match &it.kind {
+        hir::ForeignItemKind::Fn(.., generics) => {
+            let mut gen_lts = 0;
+            let mut gen_tys = 0;
+            let mut gen_cns = 0;
```
Comment (varkor) [inline compiler/rustc_typeck/src/check/intrinsic.rs:31]: You could use `GenericParamCount` for this. See the function `own_counts`.

File: compiler/rustc_typeck/src/check/intrinsic.rs [hunk 2]
```diff
@@ -21,36 +21,68 @@ fn equate_intrinsic_type<'tcx>(
...
-    let i_n_tps = tcx.generics_of(it.def_id).own_counts().types;
-    if i_n_tps != n_tps {
-        let span = match it.kind {
-            hir::ForeignItemKind::Fn(_, _, ref generics) => generics.span,
-            _ => bug!(),
-        };
+    };
 
-        tcx.sess.emit_err(WrongNumberOfTypeArgumentsToInstrinsic {
+    if gen_lts != n_lts {
```
Comment (varkor) [inline compiler/rustc_typeck/src/check/intrinsic.rs:57]: It would be nice to abstract the following three conditions into a loop or something, because they all essentially have the same effect.

**Review by varkor — COMMENTED** [review]
Code mostly looks good. I just had a couple of comments. Apologies for taking so long.

File: compiler/rustc_typeck/src/check/intrinsic.rs (hunk 1 above)
Comment (FabianWolff) [reply compiler/rustc_typeck/src/check/intrinsic.rs]: The HIR and `tcx.generics_of(...).own_counts()` seem to disagree on the number of lifetime parameters sometimes, but this seems unrelated to my changes. Fixed.

File: compiler/rustc_typeck/src/check/intrinsic.rs (hunk 2 above)
Comment (FabianWolff) [reply compiler/rustc_typeck/src/check/intrinsic.rs]: I moved the check into a closure and used nested `if` statements to make sure only one error gets emitted at a time.

File: compiler/rustc_typeck/src/check/intrinsic.rs [hunk 3]
```diff
@@ -21,36 +21,47 @@ fn equate_intrinsic_type<'tcx>(
...
     it: &hir::ForeignItem<'_>,
     n_tps: usize,
+    n_lts: usize,
     sig: ty::PolyFnSig<'tcx>,
 ) {
-    match it.kind {
-        hir::ForeignItemKind::Fn(..) => {}
+    let (gen_lts, gen_tys, gen_cns, span) = match &it.kind {
+        hir::ForeignItemKind::Fn(.., generics) => {
+            let gc = tcx.generics_of(it.def_id.to_def_id()).own_counts();
```
Comment (varkor) [inline compiler/rustc_typeck/src/check/intrinsic.rs:29]:
```suggestion
            let own_counts = tcx.generics_of(it.def_id.to_def_id()).own_counts();
```

File: compiler/rustc_typeck/src/check/intrinsic.rs [hunk 4]
```diff
@@ -21,36 +21,47 @@ fn equate_intrinsic_type<'tcx>(
...
+            (gc.lifetimes, gc.types, gc.consts, generics.span)
```
Comment (varkor) [inline compiler/rustc_typeck/src/check/intrinsic.rs:30]:
```suggestion
            (own_counts, generics.span)
```

File: compiler/rustc_typeck/src/check/intrinsic.rs [hunk 5]
```diff
@@ -21,36 +21,47 @@ fn equate_intrinsic_type<'tcx>(
...
+        }
+    };
 
-        tcx.sess.emit_err(WrongNumberOfTypeArgumentsToInstrinsic {
-            span,
-            found: i_n_tps,
-            expected: n_tps,
-        });
-        return;
+    if gen_count_ok(gen_lts, n_lts, "lifetime") {
```
Comment (varkor) [inline compiler/rustc_typeck/src/check/intrinsic.rs:55]: You could use `&&` here instead of nested `if`s.

Comment (FabianWolff) [reply compiler/rustc_typeck/src/check/intrinsic.rs]: Fixed.

**Comment by varkor** [comment]
Thanks, this all looks good to me now!

@bors r+
