### PR TITLE
Fix `non_exhaustive_omitted_patterns` on arguments and locals

### LINKED ISSUE #99815: False positive on `non_exhaustive_omitted_patterns_lint` with closures
I tried this code ([playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=5eda6149e4d8df5ec233e5133d06b0f1)):

```rust
#![warn(non_exhaustive_omitted_patterns)]

// in other library:
// #[non_exhaustive] pub enum Foo { A, B }
use lib::Foo;

fn foo(_: impl Fn(Foo)) {}

fn main() {
    foo(|_: Foo| { todo!() });
}
```

I expected to see this happen: no warnings.

Instead, this happened:
```
warning: some variants are not matched explicitly
  --> src/main.rs:10:14
   |
10 |         foo(|_: Foo| { todo!() });
   |              ^ patterns `A` and `B` not covered
   |
```

### Meta
```
1.64.0-nightly (2022-07-26 4d6d601c8a83284d6b23)
```

cc #89554

### PR DESCRIPTION
**Pull request by clubby789**
Fixes #99815

r? @Nilstrieb

### CODE REVIEW

**Review by Noratrieb — APPROVED** [review]

**Comment by Nilstrieb** [comment]
r=me after CI is happy
@bors delegate+

File: compiler/rustc_mir_build/src/thir/pattern/usefulness.rs [hunk 1]
```diff
@@ -867,6 +868,8 @@ fn is_useful<'p, 'tcx>(
                     &ctor,
                     Constructor::Missing { nonexhaustive_enum_missing_real_variants: true }
                 )
+                // We don't want to lint patterns which are function arguments
```
Comment (Nilstrieb) [inline compiler/rustc_mir_build/src/thir/pattern/usefulness.rs:871]: r=me after updating the comment
