### PR TITLE
Suggest removing the tuple struct field for the unwrapped value

### LINKED ISSUE #99416: Suggest to directly use a value instead of wrapping the unwrapped value
Given the following code: [this](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=7a72bcda8a7c6bc6a7263a5b5a1f7655)

```rust
pub struct MyWrapper(u32);

fn main() {
    let value = MyWrapper(123);
    some_fn(value.0);
}

fn some_fn(wrapped: MyWrapper) {
    drop(wrapped);
}
```

The current output is:

```
Compiling playground v0.0.1 (/playground)
error[[E0308]](https://doc.rust-lang.org/stable/error-index.html#E0308): mismatched types
 --> src/main.rs:6:13
  |
6 |     some_fn(value.0);
  |             ^^^^^^^ expected struct `MyWrapper`, found `u32`
  |
help: try wrapping the expression in `MyWrapper`
  |
6 |     some_fn(MyWrapper(value.0));
  |             ++++++++++       +

For more information about this error, try `rustc --explain E0308`.
error: could not compile `playground` due to previous error
```

Ideally the output should look like:

```
Compiling playground v0.0.1 (/playground)
error[[E0308]](https://doc.rust-lang.org/stable/error-index.html#E0308): mismatched types
 --> src/main.rs:6:13
  |
6 |     some_fn(value.0);
  |             ^^^^^^^ expected struct `MyWrapper`, found `u32`
  |
help: try using `value` directly
  |
6 |     some_fn(value);
  |             +++++

For more information about this error, try `rustc --explain E0308`.
error: could not compile `playground` due to previous error
```

Just encountered this as I was refactoring code to properly use my tuple struct instead of an raw integer identifier.

### PR DESCRIPTION
**Pull request by TaKO8Ki**
fixes #99416

### CODE REVIEW

File: compiler/rustc_typeck/src/check/demand.rs [hunk 1]
```diff
@@ -287,6 +287,21 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
         expr_ty: Ty<'tcx>,
     ) {
         if let ty::Adt(expected_adt, substs) = expected.kind() {
+            if let hir::ExprKind::Field(base, ident) = expr.kind
+                && let Some(typeck_results) = self.in_progress_typeck_results
+            {
+                let base_ty = typeck_results.borrow().expr_ty(base);
```
Comment (compiler-errors) [inline compiler/rustc_typeck/src/check/demand.rs:293]: FnCtxt has `self.typeck_results` which are not `Option<T>`

```suggestion
        if let ty::Adt(expected_adt, substs) = expected.kind() {
            if let hir::ExprKind::Field(base, ident) = expr.kind
            {
                let base_ty = self.typeck_results.borrow().expr_ty(base);
```

File: compiler/rustc_typeck/src/check/demand.rs [hunk 2]
```diff
@@ -287,6 +287,21 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
...
+                if base_ty == expected {
```
Comment (compiler-errors) [inline compiler/rustc_typeck/src/check/demand.rs:294]: Can we use something like `can_eq` instead?

```suggestion
                if self.can_eq(self.param_env, base_ty, expected).is_ok() {
```

File: compiler/rustc_typeck/src/check/demand.rs [hunk 3]
```diff
@@ -287,6 +287,21 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
...
+                    err.span_suggestion_verbose(
+                        expr.span.with_lo(base.span.hi()),
```
Comment (compiler-errors) [inline compiler/rustc_typeck/src/check/demand.rs:296]: What does this do if `base` comes from a macro expansion? For example:

```rust
// run-rustfix

pub struct MyWrapper(u32);

macro_rules! my_wrapper {
  ($expr:expr) => { MyWrapper($expr) }
}

fn main() {
    some_fn(my_wrapper!(123).0); //~ ERROR mismatched types
}

fn some_fn(wrapped: MyWrapper) {
    drop(wrapped);
}
```

I think `base.span` should probably be adjusted to account for macros. Try matching `if let Some(base_span) 
 = base.span.find_ancestor_inside(expr.span)` first to make sure that expr span and base span overlap.

File: compiler/rustc_typeck/src/check/demand.rs (hunk 2 above)
Comment (compiler-errors) [reply compiler/rustc_typeck/src/check/demand.rs:294]: alternatively we could use `same_type_modulo_regions`, but since we have access to `can_eq`, it's a bit more accurate.

**Comment by compiler-errors** [comment]
Wonderful. Thanks for addressing comments.

@bors r+
