### PR TITLE
`EscapeAscii` is not an `ExactSizeIterator`

### LINKED ISSUE #99878: Panic in escape_ascii().len()
I tried this code:

```rust
fn main() {
    "omgwtfbbq".as_bytes().escape_ascii().len();
}
```

I expected the length of the`escape_ascii` iterator.  Instead, panic:

```
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `None`,
 right: `Some(0)`', /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/iter/traits/exact_size.rs:108:9

```

### Meta

```
rustc 1.62.1 (e092d0b6b 2022-07-16)
binary: rustc
commit-hash: e092d0b6b43f2de967af0887873151bb1c0b18d3
commit-date: 2022-07-16
host: x86_64-unknown-linux-gnu
release: 1.62.1
LLVM version: 14.0.5
```

<details>
<summary>
My first suspicion would be the size_hint() on the iterator.  It also happens in no_std.
</summary>
<p>

Stacktrace:
```
stack backtrace:
   0: rust_begin_unwind
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/panicking.rs:142:14
   2: core::panicking::assert_failed_inner
   3: core::panicking::assert_failed
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/panicking.rs:181:5
   4: core::iter::traits::exact_size::ExactSizeIterator::len
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/iter/traits/exact_size.rs:108:9
   5: omgwtfbbq::main
             at ./src/main.rs:2:5
   6: core::ops::function::FnOnce::call_once
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/ops/function.rs:248:5
```

</p>
</details>

### PR DESCRIPTION
**Pull request by compiler-errors**
Fixes #99878

Do we want/need `EscapeAscii` to be an `ExactSizeIterator`? I guess we could precompute the length of the output if so?

### CODE REVIEW

**Comment by softdevca** [comment]
> Fixes #99878
> 
> Do we want/need `EscapeAscii` to be an `ExactSizeIterator`? I guess we could precompute the length of the output if so?

Submitter of #99878 here:

I welcome dropping `ExactSizeIterator` from `EscapeAscii` as long it doesn't cause backwards compatibility issues. 

I can create a PR of an implementation of `ExactSizeIterator` if needed.  My initial implementation precomputes the length using the same `EscapeDefault` mechanism used by `escape_ascii`.

If I was to add an `ExactSizeIterator` where should the tests be located?  I would prefer not to add to  `library/core/tests/slices.rs` as it's already rather large.  Would creating `tests/slice/ascii.rs` be appropriate so it matches the implementation path?  Thank you.

**Comment by compiler-errors** [comment]
@softdevca yeah, if t-lang prefers that we keep the `ExactSizeIterator` implementation, you can totally go ahead and implement it in favor of this PR which I can close.

**Comment by thomcc** [comment]
Oof, looks like this was missed in review. This is a breaking change to remove. It's likely nobody's using it yet, since it just panics, but it could cause type errors (which would be perhaps detectable via a crater run).

Making this correctly implement ExactSizeIterator is the "correct" fix, but doing so has a very unfortunate cost...

**Comment by thomcc** [comment]
I think we should do a crater run to evaluate the impact of this, to see if it's on the table. (Step 1 is a try build, according to https://std-dev-guide.rust-lang.org/tools-and-bots/crater.html)

@bors try

**Comment by compiler-errors** [comment]
Just for the record, the crater queue is quite long lol. It's probably going to be like a few weeks until it gets results back at this rate.

If t-libs deems this critical then we should probably bump the priority on the crater job though.

**Comment by thomcc** [comment]
That's unfortunate. I'll leave it to the reviewer to decide how critical it is. I think this would be a nice approach to do if we can get away with it, since this type shouldn't have implemented ExactSizeIterator in the first place.

File: library/std/src/sys/unsupported/process.rs [hunk 1]
```diff
@@ -200,6 +200,9 @@ impl<'a> Iterator for CommandArgs<'a> {
     fn next(&mut self) -> Option<&'a OsStr> {
         None
     }
+    fn size_hint(&self) -> (usize, Option<usize>) {
```
Comment (thomcc) [inline library/std/src/sys/unsupported/process.rs:203]: This change seems unrelated?

**Comment by compiler-errors** [comment]
@craterbot check

**Comment by softdevca** [comment]
> @softdevca yeah, if t-lang prefers that we keep the `ExactSizeIterator` implementation, you can totally go ahead and implement it in favor of this PR which I can close.

I am implementing `ExactSizeIterator` and will submit a new PR.

**Comment by softdevca** [comment]
PR  #99913 has been submitted to correct the implementation of `ExactSizeIterator` for `EscapeAscii`

**Comment by thomcc** [comment]
Still wanna know (and t-infra said to go ahead)

@craterbot name=pr-99880 p=1

**Comment by thomcc** [comment]
The two root errors seem to be unrelated, so we can probably can go ahead with removing the impl.

**Comment by softdevca** [comment]
The crater run seems to indicate that nothing depends on `EscapeAscii` implementing `ExactSizeIterator`.  This would be expected because `.len()` would panic for any non-empty iterator.  

Pull request #99913 has been updated to remove the implementation of `ExactSizeIterator` for `EscapeAscii`.

**Comment by compiler-errors** [comment]
> Pull request https://github.com/rust-lang/rust/pull/99913 has been updated to remove the implementation of ExactSizeIterator for EscapeAscii.

This PR already implements that change...? :thinking:

**Comment by softdevca** [comment]
> This PR already implements that change...? 

Yes, can walk it back if needed.

File: library/std/src/sys/unsupported/process.rs (hunk 1 above)
Comment (compiler-errors) [reply library/std/src/sys/unsupported/process.rs:203]: I'll do that.

**Comment by compiler-errors** [comment]
Anyone want to r+ this?

> https://github.com/rust-lang/rust/issues/99878#issuecomment-1216660341

**Comment by softdevca** [comment]
Can we get this in 1.64?  The longer `ExactSizeIterator` is implemented for `EscapeAscii` the more likely it is that someone will use it and not realize a panic is lurking.

**Comment by thomcc** [comment]
> Anyone want to r+ this?

Does it need FCP? I can r+ if it does not.

**Comment by compiler-errors** [comment]
Yeah, I didn't know whether it needed an FCP or not based on this:

> Reverting it seems okay, even though it's technically a breaking change.

Anyone from @rust-lang/libs-api can weigh in?

**Comment by softdevca** [comment]
Can we get this released?   I feel like it would be better to make the breaking change sooner rather than later.  Thank you.

**Comment by thomcc** [comment]
I've marked this as nominated because it's sat here for so long and needs to be merged (or to be FCPed).

**Comment by m-ou-se** [comment]
@rfcbot merge

**Comment by compiler-errors** [comment]
I'm gonna beta nominate this too.

**Comment by pietroalbini** [comment]
Will likely not make it into 1.64, even though that seemed to be the intention.

**Comment by thomcc** [comment]
Looks like we're good!

@bors r+
