### PR TITLE
Workarounds for copy_file_range issues

### LINKED ISSUE #75387: std::fs::copy fails on NFS volumes on CentOS 7
I tried this code:

```rust
// On a CentOS 7 VM, where the current directory is an NFS mount containing a file called "a" with any content
use std::fs;

fn main() {
  println!("Hello, world!");
  fs::copy("a", "b").unwrap();
}
```

I expected to see this happen: The file is successfully copied

Instead, this happened:
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 95, kind: Other, message: "Operation not Supported" }', src/main.rs:4:4
```

### Meta

`rustc --version --verbose`:

Screen Shot 2020-08-11 at 12 08 34 AM

<details><summary>Backtrace</summary>
<p>

Screen Shot 2020-08-11 at 12 10 16 AM
Screen Shot 2020-08-11 at 12 10 56 AM
Screen Shot 2020-08-11 at 12 11 59 AM

</p>
</details>

Apologies for screenshots, I'm running in a VM I can't easily copy/paste out of.

See also https://github.com/rust-lang/rustup/issues/2452, which has a likely explanation of the cause of this.

### LINKED ISSUE #75446: fs::copy hangs on docker (Linux)
Running Fedora 32 with selinux set to non-enforcing, building a project with OpenCV.

I am building a rather weird docker setup, but what I ran into was hanging during build stage of opencv-rust, [around here](https://github.com/twistedfall/opencv-rust/blob/34c94516668f91e28257b85a0a5ce2b212559c84/build.rs#L1019).

I expected to see this happen: build succeed rather quickly

Instead, this happened: execution froze on [fs::copy call](https://github.com/twistedfall/opencv-rust/blob/34c94516668f91e28257b85a0a5ce2b212559c84/build.rs#L835), and cpu got stuck running almost full speed.

My project was mounted using `-v $PWD/project:/project:Z` (name changed), opencv was manually cloned (for debugging) into the root of the docker image, at `/opencv-rust`.

Copies from `/opencv-rust` to `/project` don't work (example: `/opencv-rust/bindings/cpp/opencv_4/aruco.cpp` => `/project/target/release/build/opencv-50ff47d79816a5ea/out/aruco.cpp`)

File copies from `/project` to `/opencv-rust` work just fine (example: `/project/target/release/build/opencv-50ff47d79816a5ea/out/xobjdetect_types.hpp` => `/opencv-rust/bindings/cpp/opencv_4/xobjdetect_types.hpp`)

It appears to be an issue in the implementation of [Linux's fs::copy](https://github.com/rust-lang/rust/blob/2c31b45ae878b821975c4ebd94cc1e49f6073fd0/library/std/src/sys/unix/fs.rs#L1123), as implementing [the more generic version above](https://github.com/rust-lang/rust/blob/2c31b45ae878b821975c4ebd94cc1e49f6073fd0/library/std/src/sys/unix/fs.rs#L1115) does not freeze the operation.

### Meta

`rustc --version --verbose`:
```
rustc 1.45.2 (d3fb005a3 2020-07-31)
binary: rustc
commit-hash: d3fb005a39e62501b8b0b356166e515ae24e2e54
commit-date: 2020-07-31
host: x86_64-unknown-linux-gnu
release: 1.45.2
LLVM version: 10.0
```

</p>
</details>

### PR DESCRIPTION
**Pull request by the8472**
fixes #75387
fixes #75446

### CODE REVIEW

File: library/std/src/sys/unix/fs.rs [hunk 1]
```diff
@@ -1180,11 +1180,13 @@ pub fn copy(from: &Path, to: &Path) -> io::Result<u64> {
...
                             || os_err == libc::EXDEV
                             || os_err == libc::EINVAL
-                            || os_err == libc::EPERM =>
+                            || os_err == libc::EPERM
+                            || os_err == libc::EOPNOTSUPP =>
                     {
                         // Try fallback io::copy if either:
                         // - Kernel version is < 4.5 (ENOSYS)
                         // - Files are mounted on different fs (EXDEV)
+                        // - copy_file_range is broken in various ways on RHEL/CentOS 7 (EOPNOTSUPP)
```
Comment (Tavi-Kohn) [inline library/std/src/sys/unix/fs.rs:1189]: I'm not sure if the bug is exclusive to RHEL/CentOS, it may apply to other Linux kernels. It may be more accurate to make a more general statement.

File: library/std/src/sys/unix/fs.rs [hunk 2]
```diff
@@ -1180,11 +1180,13 @@ pub fn copy(from: &Path, to: &Path) -> io::Result<u64> {
                         if os_err == libc::ENOSYS
                             || os_err == libc::EXDEV
                             || os_err == libc::EINVAL
-                            || os_err == libc::EPERM =>
+                            || os_err == libc::EPERM
```
Comment (lzutao) [inline library/std/src/sys/unix/fs.rs:1183]: I would use
```diff
-Some(os_err)
+Some(libc::ENOSYS | libc::EXDEV | libc::EINVAL | libc:EPERM | libc::EOPNOTSUPP) => 
```

File: library/std/src/sys/unix/fs.rs [hunk 3]
```diff
@@ -1162,7 +1162,7 @@ pub fn copy(from: &Path, to: &Path) -> io::Result<u64> {
             };
             if let Err(ref copy_err) = copy_result {
                 match copy_err.raw_os_error() {
-                    Some(libc::ENOSYS) | Some(libc::EPERM) => {
+                    Some(libc::ENOSYS) | Some(libc::EPERM) | Some(libc::EOPNOTSUPP) => {
```
Comment (lzutao) [inline library/std/src/sys/unix/fs.rs:1165]:
```suggestion
                    Some(libc::ENOSYS | libc::EPERM | libc::EOPNOTSUPP) => {
```

File: library/std/src/sys/unix/fs.rs (hunk 1 above)
Comment (Tavi-Kohn) [inline library/std/src/sys/unix/fs.rs:1189]: This comment could be more specific, but the exact platforms this occurs on and what's happening in the kernel is still somewhat mysterious (to me), so I think it's acceptable.

Comment (the8472) [reply library/std/src/sys/unix/fs.rs:1185]: There's some additional information in the commit message.

**Comment by the8472** [comment]
The bors error is not helpful, spurious failure?

File: library/std/src/sys/unix/fs.rs [hunk 4]
```diff
@@ -1162,7 +1162,7 @@ pub fn copy(from: &Path, to: &Path) -> io::Result<u64> {
             };
             if let Err(ref copy_err) = copy_result {
                 match copy_err.raw_os_error() {
-                    Some(libc::ENOSYS) | Some(libc::EPERM) => {
+                    Some(libc::ENOSYS | libc::EPERM | libc::EOPNOTSUPP) => {
```
Comment (nagisa) [inline library/std/src/sys/unix/fs.rs:1165]: side note `EOPNOTSUPP` and `EPERM` setting `HAS_COPY_FILE_RANGE` sound like a pessimisation to me.

I can see either of those errors occurring transiently (e.g. when copying to/from NFS or copying to a file system with no write permissions) on a system that otherwise supports this syscall just fine...

Comment (cuviper) [reply library/std/src/sys/unix/fs.rs:1165]: I think `EPERM` was here because of seccomp failures noted below, where you might as well act like the syscall doesn't exist. I suppose a seccomp filter could be more nuanced than completely disabling this syscall though. However, if the filesystem had no write permission, wouldn't we have failed earlier trying to open that file handle at all?

`EOPNOTSUPP` could go either way, but I think that's mostly a quirk of RHEL7's bug. AIUI, in newer kernels VFS will fallback to splice automatically, so the user wouldn't even see it.

Comment (the8472) [reply library/std/src/sys/unix/fs.rs:1165]: [EOPNOTSUPP shouldn't be visible to userspace](https://github.com/torvalds/linux/commit/64bf5ff58dff757253cf2142542672de4b21cd1a#diff-63018726069897e4a3a3b5b03ff71613R1673), the kernel will (should) fallback to a generic splice in that case.
EPERM may indeed be a pessimization in some cases, afaict it exists to detect seccomp containers where the syscall is blocked and thus will never succeed and thus be a waste of syscalls.

If we want to change that that should be done in a separate PR imo.

Comment (nagisa) [reply library/std/src/sys/unix/fs.rs:1165]: > EOPNOTSUPP shouldn't be visible to userspace

We’re already taking time to handle this case that shouldn’t ever happen, though. I was and still am a proponent of not spending any time, bytes or effort on broken setups and kernels, but the opinion held by others appears to be different. So we might as well do it right.

> However, if the filesystem had no write permission, wouldn't we have failed earlier trying to open that file handle at all?

I can still imagine cases where this could be overly pessimistic. Especially with network filesystems where having a writable file descriptor does not necessarily mean you’ll have permission to write to it (anymore).

> If we want to change that that should be done in a separate PR imo.

Fair.

**Comment by the8472** [comment]
Updated to address an additional copy_file_range issue.

File: library/std/src/sys/unix/fs.rs (hunk 4 above)
Comment (the8472) [reply library/std/src/sys/unix/fs.rs:1165]: Use of `copy_file_range`  is an optimization. if you have a buggy kernel which violates the stated contract in the manpage I think it is fair game to just not apply this optimization and we don't have to jump through extra hoops to detect what kind of specific unexpected error we're getting.

**Comment by the8472** [comment]
ping @joshtriplett

File: library/std/src/sys/unix/fs.rs [hunk 5]
```diff
@@ -1140,14 +1140,14 @@ pub fn copy(from: &Path, to: &Path) -> io::Result<u64> {
...
+    let max_len = u64::MAX;
     let (mut writer, _) = open_to_and_set_permissions(to, reader_metadata)?;
 
     let has_copy_file_range = HAS_COPY_FILE_RANGE.load(Ordering::Relaxed);
     let mut written = 0u64;
-    while written < len {
+    while written < max_len {
         let copy_result = if has_copy_file_range {
-            let bytes_to_copy = cmp::min(len - written, usize::MAX as u64) as usize;
+            let bytes_to_copy = cmp::min(max_len - written, usize::MAX as u64) as usize;
```
Comment (tavianator) [inline library/std/src/sys/unix/fs.rs:1150]: Is it really necessary to keep track of `max_len - written` accurately at this point?  It's probably okay just to pass a large constant size on every call.

Comment (the8472) [reply library/std/src/sys/unix/fs.rs:1150]: It avoids overflowing an u64. Plus I want to reuse the code in #75272 which will require exact max sizes

**Comment by the8472** [comment]
I don't see how linux-only code changes can make a mingw build fail. Doubly so when it's doc tests.
