### PR TITLE
rustc: Allow changing the default allocator

### LINKED ISSUE #27389: Tracking issue for changing the global, default allocator (RFC 1974)
Tracking issue for ~~https://github.com/rust-lang/rfcs/pull/1183~~ https://github.com/rust-lang/rfcs/pull/1974

Known bugs:

* [ ] The `#[global_allocator]` attribute doesn't work in modules #44113

Current status:

* [x] Implemented in https://github.com/rust-lang/rust/pull/42727
* [ ] [Stabilization checklist](https://forge.rust-lang.org/stabilization-guide.html)
  * [ ] Remove docs from the unstable book
  * [ ] Add docs to the real book
* [x] Add jemalloc as a crates on crates.io ([jemallocator](https://crates.io/crates/jemallocator))
* [ ] Once stable, link binaries to the system allocator by default #36963
  * known issues https://github.com/rust-lang/rust/issues/36963#issuecomment-252029017
  * valgrind doesn't work on jemalloc https://github.com/rust-lang/rust/issues/28224
  * crates are gone https://github.com/rust-lang/rust/issues/33082

A quick summary of the current state of this feature is that you can change the default global allocator via:

```rust
// Change this program's global allocator. At most one `#[global_allocator]` 
// allowed in any crate graph.
#[global_allocator]
static ALLOCATOR: MyAlloc = MyAlloc;


// When defining a global allocator, the `Alloc` trait must be defined
// for `&'a T` instead of `T`
use std::heap::Alloc;

struct MyAlloc;

impl<'a> Alloc for &'a MyAlloc {
    // ...
}
```

### PR DESCRIPTION
**Pull request by alexcrichton**
This commit is an implementation of [RFC 1183](https://github.com/rust-lang/rfcs/pull/1183) which allows swapping out
the default allocator on nightly Rust. No new stable surface area should be
added as a part of this commit.

Two new attributes have been added to the compiler:
- `#![needs_allocator]` - this is used by liballoc (and likely only liballoc) to
  indicate that it requires an allocator crate to be in scope.
- `#![allocator]` - this is a indicator that the crate is an allocator which can
  satisfy the `needs_allocator` attribute above.

The ABI of the allocator crate is defined to be a set of symbols that implement
the standard Rust allocation/deallocation functions. The symbols are not
currently checked for exhaustiveness or typechecked. There are also a number of
restrictions on these crates:
- An allocator crate cannot transitively depend on a crate that is flagged as
  needing an allocator (e.g. allocator crates can't depend on liballoc).
- There can only be one explicitly linked allocator in a final image.
- If no allocator is explicitly requested one will be injected on behalf of the
  compiler. Binaries and Rust dylibs will use jemalloc by default where
  available and staticlibs/other dylibs will use the system allocator by
  default.

Two allocators are provided by the distribution by default, `alloc_system` and
`alloc_jemalloc` which operate as advertised.

Closes #27389

### CODE REVIEW

**Comment by alexcrichton** [comment]
r? @brson 

cc @nnethercote

File: src/librustc/metadata/creader.rs [hunk 1]
```diff
@@ -49,15 +49,16 @@ impl<'a, 'v> visit::Visitor<'v> for CrateReader<'a> {
 }
 
 fn dump_crates(cstore: &CStore) {
-    debug!("resolved crates:");
```
Comment (pnkfelix) [inline src/librustc/metadata/creader.rs]: Was the switch from `debug!` to `info!` (and likewise from `log::DEBUG` to `log::INFO`) deliberate, or an accident?

I would have thought we could (and should) leave it as it was, under `debug!`

Comment (alexcrichton) [inline src/librustc/metadata/creader.rs]: Yeah this was currently intentional but I wouldn't mind changing it back. Whenever someone's having weird behavior with loading crates I typically ask them to set `RUST_LOG=rustc::metadata::creader,rustc::metadata::loader` to get info like this, but `debug!` means it's all compiled out by default.

Along those lines I'd somewhat prefer to have it be `info!` but I don't have much of a preference either way

**Comment by nnethercote** [comment]
@alexcrichton: can I ask what the code would look like for a program (such as Servo) to implement allocation wrappers? I know we talked about this at Whistler but I don't remember the details and now that you have an implementation to reference it might be easier to describe. Thank you.

**Comment by alexcrichton** [comment]
Certainly! You'd basically just create a copy of [`src/liballoc_jemalloc/lib.rs`](https://github.com/alexcrichton/rust/blob/less-jemalloc/src/liballoc_jemalloc/lib.rs), filling in different implementations for the [various allocation functions](https://github.com/alexcrichton/rust/blob/less-jemalloc/src/liballoc_jemalloc/lib.rs#L68-L98). You'd then just say `extern crate foo` to link in your allocator and you'd be good to go!

File: src/liballoc_system/lib.rs [hunk 2]
```diff
@@ -0,0 +1,205 @@
...
+    pub fn usable_size(size: usize, _align: usize) -> usize {
+        size
+    }
+}
+
+#[cfg(windows)]
+mod imp {
+    use core::mem::size_of;
+    use libc::{BOOL, DWORD, HANDLE, LPVOID, SIZE_T, INVALID_HANDLE_VALUE};
+    use libc::{WriteFile};
```
Comment (retep998) [inline src/liballoc_system/lib.rs]: `WriteFile` and `INVALID_HANDLE_VALUE` aren't needed.

File: src/liballoc_system/lib.rs [hunk 3]
```diff
@@ -0,0 +1,205 @@
...
+        fn HeapReAlloc(hHeap: HANDLE, dwFlags: DWORD, lpMem: LPVOID,
+                       dwBytes: SIZE_T) -> LPVOID;
+        fn HeapFree(hHeap: HANDLE, dwFlags: DWORD, lpMem: LPVOID) -> BOOL;
+    }
+
+    #[repr(C)]
+    struct Header(*mut u8);
+
+    const HEAP_REALLOC_IN_PLACE_ONLY: DWORD = 0x00000010;
+    const STD_OUTPUT_HANDLE: DWORD = -11i32 as u32;
```
Comment (retep998) [inline src/liballoc_system/lib.rs]: Also `STD_OUTPUT_HANDLE` isn't needed anymore.

File: src/liballoc_system/lib.rs [hunk 4]
```diff
@@ -0,0 +1,205 @@
...
+#[cfg(windows)]
+mod imp {
+    use core::mem::size_of;
+    use libc::{BOOL, DWORD, HANDLE, LPVOID, SIZE_T, INVALID_HANDLE_VALUE};
+    use libc::{WriteFile};
+    use MIN_ALIGN;
+
+    extern "system" {
+        fn GetProcessHeap() -> HANDLE;
+        fn GetStdHandle(nStdHandle: DWORD) -> HANDLE;
```
Comment (retep998) [inline src/liballoc_system/lib.rs]: `GetStdHandle` isn't needed.

File: src/liballoc_system/lib.rs [hunk 5]
```diff
@@ -0,0 +1,202 @@
...
+    }
+
+    pub fn usable_size(size: usize, _align: usize) -> usize {
+        size
+    }
+}
+
+#[cfg(windows)]
+mod imp {
+    use core::mem::size_of;
```
Comment (retep998) [inline src/liballoc_system/lib.rs]: `size_of` is also unused it seems.

**Comment by brson** [comment]
This feels very complex, makes me want to remove jemalloc.

**Comment by retep998** [comment]
Considering how jemalloc is responsible for https://github.com/rust-lang/rust/issues/26647 and is also really brittle when used under conemu https://github.com/rust-lang/rust/issues/14600#issuecomment-113042180.

You know, this reminds me of the time we had green threaded IO, then split it using virtual dispatch between a green and a native portion, then later dropped the green part entirely.

**Comment by steveklabnik** [comment]
jemalloc tends to have _way_ better performance than libc's malloc or the
system malloc, though. At least, in my understanding...

**Comment by alexcrichton** [comment]
@brson 

> This feels very complex, makes me want to remove jemalloc.

Could you elaborate a bit on this? I can certainly more aggressively document various aspects and I certainly wouldn't mind rewriting various code paths. I don't think that we want to just look at this and jettison jemalloc, though, as there are very real other use cases for swapping out for custom allocators (such as Servo's memory tracking, embedded systems with different allocators, etc). 

If we followed reasoning like this I would also say that supporting both dylibs/rlibs at the same time is pretty complex, but I don't feel the need to remove that distinction. There's concrete use cases for both so we just need to support both in as robust a manner as possible.

---

@retep998 

> You know, this reminds me of the time we had green threaded IO, then split it using virtual dispatch between a green and a native portion, then later dropped the green part entirely.

I don't think that this is the same situation as here most notably because there's no virtual dispatch here. This is a static decision which is made that has no costs associated with it (unlike the virtual dispatch).

Like I said above, complexity is not a reason to jettison something, it's a reason to rethink why it's so complex and consider other options, but in this case I don't consider removing jemalloc an option.

If there are bugs on Windows caused by our usage of jemalloc (I was unaware of these), then we should track them down and fix them, but removing it from all platforms is a pretty heavy hammer.

**Comment by alexcrichton** [comment]
I'm currently running a crater build for this PR

**Comment by alexcrichton** [comment]
Crater reports [one regression](https://gist.github.com/anonymous/4eb1413f1274f3b5515b) but I have confirmed locally that it was spurious.

**Comment by nnethercote** [comment]
A few comments...
- The ability to provide custom allocators is very important and useful.
- In the context of Rust, I've heard it said many times that jemalloc is faster, but I haven't seen any measurements showing this. (Hmm, now that I think of it, somebody may have mentioned that using jemalloc sped up rustc significantly? Not sure.)
- Servo uses a mixture of jemalloc (for Rust code) and the system heap (for C/C++ code, e.g. SpiderMonkey). Servo's memory reporting code thus has machinery for dealing with both: it reports the total size of both heaps, and it uses `je_malloc_usable_size` to measure jemalloc heap blocks and `malloc_usable_size` (on Linux) or `malloc_size` (on Mac) to measure system heap blocks.

**Comment by alexcrichton** [comment]
Rebased

**Comment by alexcrichton** [comment]
> In the context of Rust, I've heard it said many times that jemalloc is faster, but I haven't seen any measurements showing this.

Interestingly enough, I just modified the `shootout-binarytrees.rs` benchmark (an allocation-heavy shootout benchmark) to use `Box` everywhere instead of arenas, and the system allocator (on Linux for me) was faster:

```
$ time ./binary-jemalloc 18
stretch tree of depth 19         check: -1
524288   trees of depth 4        check: -524288
131072   trees of depth 6        check: -131072
32768    trees of depth 8        check: -32768
8192     trees of depth 10       check: -8192
2048     trees of depth 12       check: -2048
512      trees of depth 14       check: -512
128      trees of depth 16       check: -128
32       trees of depth 18       check: -32
long lived tree of depth 18      check: -1
./binary-jemalloc 18  5.88s user 0.57s system 375% cpu 1.715 total
$ time ./binary-system 18   
stretch tree of depth 19         check: -1
524288   trees of depth 4        check: -524288
131072   trees of depth 6        check: -131072
32768    trees of depth 8        check: -32768
8192     trees of depth 10       check: -8192
2048     trees of depth 12       check: -2048
512      trees of depth 14       check: -512
128      trees of depth 16       check: -128
32       trees of depth 18       check: -32
long lived tree of depth 18      check: -1
./binary-system 18  5.14s user 0.02s system 370% cpu 1.395 total
```

I'm a little surprised by this as I've never seen a benchmark showing that jemalloc was slower than the system allocator...

**Comment by pnkfelix** [comment]
> there are very real other use cases for swapping out for custom allocators (such as Servo's memory tracking, embedded systems with different allocators, etc). 

strong +1 to this.  Even if we dropped jemalloc I'd *still* want the ability to swap in a different allocator at the lowest level.

(I have more than once taking the tack when debugging some hairy issue of manually instrumenting our allocator. This strategy is very useful, but hard to deploy in our current infrastructure; this PR will make it nearly trivial, and could, in principle, enable the introduction of a marketplace of debuggable liballoc API's.)

**Comment by pnkfelix** [comment]
@alexcrichton n.b. this PR does not build for me on Mac OS X.

Here is the tail of the log (plus the configure args): https://gist.github.com/pnkfelix/b1293dd1bf5d2c3e887e

**Comment by briansmith** [comment]
> If no allocator is explicitly requested one will be injected on behalf of the compiler. Binaries and Rust dylibs will use jemalloc by default where available and staticlibs/other dylibs will use the system allocator by default.

I think it is fine to have a default allocator. However, I am working on microcontroller stuff using `#![feature(no_std)]` where I try to avoid all dynamic allocation. In that case, I would like to have the option of opting out of having any allocator whatsoever. This would be particularly useful for libraries that guarantee they do not use the heap.

**Comment by Gankro** [comment]
@briansmith if you don't `extern crate alloc` no allocator will be linked in.

**Comment by alexcrichton** [comment]
Oops thanks for the pointers @pnkfelix, I've tweaked the dependencies in stage0 and OSX should now botstrap

File: src/liballoc/heap.rs [hunk 6]
```diff
@@ -16,6 +16,18 @@
 
 use core::{isize, usize};
 
+#[allow(improper_ctypes)]
+extern {
+    #[allocator]
```
Comment (brson) [inline src/liballoc/heap.rs]: It looks like there's nothing gating the use of this attribute (I don't see `feature` added to this crate). Is there anything preventing this from being written on stable?

File: src/test/auxiliary/needs_allocator.rs [hunk 7]
```diff
@@ -0,0 +1,18 @@
...
+// http://www.apache.org/licenses/LICENSE-2.0> or the MIT license
+// <LICENSE-MIT or http://opensource.org/licenses/MIT>, at your
+// option. This file may not be copied, modified, or distributed
+// except according to those terms.
+
+// no-prefer-dynamic
+
+#![feature(no_std, core, custom_attribute)]
+#![no_std]
+#![needs_allocator]
```
Comment (brson) [inline src/test/auxiliary/needs_allocator.rs]: I also don't see anything gating this attribute.

File: src/liballoc/heap.rs (hunk 6 above)
Comment (brson) [inline src/liballoc/heap.rs]: What is the difference in meaning when `#[allocator]` is applied to an extern block vs a crate?

File: src/librustc/metadata/cstore.rs [hunk 8]
```diff
@@ -59,11 +60,17 @@ pub struct crate_metadata {
...
     pub codemap_import_info: RefCell<Vec<ImportedFileMap>>,
     pub span: codemap::Span,
-    pub staged_api: bool
+    pub staged_api: bool,
+
+    /// Flag if this crate is required by an rlib version of this crate, or in
+    /// other words whether it was explicitly linked to. An example of a crate
+    /// where this is false is when an allocator crate is injected into the
+    /// dependency list, and therefore isn't actually needed to link an rlib.
+    pub required_by_rlib: Cell<bool>,
```
Comment (brson) [inline src/librustc/metadata/cstore.rs]: I find the name of this variable and the comments hard to understand, even as somebody who knows what this current patch does. I think this flag just means 'not an allocator crate', but I'm not sure.

**Comment by brson** [comment]
> This feels very complex, makes me want to remove jemalloc.
> 
> Could you elaborate a bit on this?

Not really.

File: src/liballoc/heap.rs (hunk 6 above)
Comment (alexcrichton) [inline src/liballoc/heap.rs]: This crate has `#![feature(allocator)]` at the top, is that what you're looking for?

This attribute existed before this PR and is a way to [add an attribute](https://github.com/rust-lang/rust/blob/master/src/librustc_trans/trans/attributes.rs#L119-L121) to the function for optimization purposes.

File: src/test/auxiliary/needs_allocator.rs (hunk 7 above)
Comment (alexcrichton) [inline src/test/auxiliary/needs_allocator.rs]: This is gated by the `custom_attribute` lint (and there's a test to ensure that `#![needs_allocator]` is gated), but I'll just switch it over to a full-fledged feature and call it a day

File: src/librustc/metadata/cstore.rs (hunk 8 above)
Comment (alexcrichton) [inline src/librustc/metadata/cstore.rs]: I think this can be extended in the future to more concepts of "lazy crates", for example a panicking implementation. In that sense I wouldn't want to solely call it "not an allocator" but rather consider it as "needed to correctly link an rlib".

Perhaps something like `explicitly_linked`?

**Comment by alexcrichton** [comment]
@brson pushed with a `needs_allocator` feature

File: src/librustc/metadata/cstore.rs (hunk 8 above)
Comment (brson) [inline src/librustc/metadata/cstore.rs]: `explicitly_linked` *seems* clearer to me.

File: src/liballoc/heap.rs (hunk 6 above)
Comment (brson) [inline src/liballoc/heap.rs]: Huh, well I'm maybe more confused now. Does `#[allocator]` mean two different things depending on context? It seems like it does, and they are both gated by the `allocator` feature? Might we rename one of these so they aren't overloaded. I guess it doesn't matter right now as long as they are gated....

Comment (alexcrichton) [inline src/liballoc/heap.rs]: Currently, yeah, I think that's how it'll work out. We can probably rename the `#[allocator]` attribute on this function to something like `#[noalias]` as that's the name of the actual LLVM attribute anyway.

File: src/librustc/metadata/cstore.rs (hunk 8 above)
Comment (alexcrichton) [inline src/librustc/metadata/cstore.rs]: Sounds good to me! Updated with this renaming.

**Comment by brson** [comment]
For what it's worth I still feel uneasy about the new complexity here in metadata loading and linking, but I don't feel able to consider alternatives right now.

**Comment by steveklabnik** [comment]
:sob:

**Comment by steveklabnik** [comment]
not 100% sure this is spurious, but everyone is out to lunch, so, let's just try

**Comment by retep998** [comment]
I'm convinced that this build error is __not__ spurious and so needs an actual fix.

**Comment by steveklabnik** [comment]
:+1: just failed again, so i'm with you

**Comment by alexcrichton** [comment]
Holy cow that's an awful error message
