### PR TITLE
Avoid expanding to unstable internal method

### LINKED ISSUE #123156: Can't ignore soft destabilization of `rustc-serialize` with `#![allow(soft_unstable)]`
In chrono we have support for `rustc-serialize` behind a feature flag.

As a workaround for #116016 I added the line:
```rust
#![cfg_attr(feature = "rustc-serialize", allow(deprecated), allow(soft_unstable))]
```
It now gives a new error:
```
error[E0658]: use of unstable library feature 'libstd_sys_internals': used by the panic! macro
  --> src/weekday.rs:33:64
   |
33 | #[cfg_attr(feature = "rustc-serialize", derive(RustcEncodable, RustcDecodable))]
   |                                                                ^^^^^^^^^^^^^^
   |
   = help: add `#![feature(libstd_sys_internals)]` to the crate attributes to enable
   = note: this compiler was built on 2024-03-27; consider upgrading it if it is out of date
   = note: this error originates in the derive macro `RustcDecodable` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0658]: use of unstable library feature 'libstd_sys_internals': used by the panic! macro
  --> src/month.rs:32:64
   |
32 | #[cfg_attr(feature = "rustc-serialize", derive(RustcEncodable, RustcDecodable))]
   |                                                                ^^^^^^^^^^^^^^
   |
   = help: add `#![feature(libstd_sys_internals)]` to the crate attributes to enable
   = note: this compiler was built on 2024-03-27; consider upgrading it if it is out of date
   = note: this error originates in the derive macro `RustcDecodable` (in Nightly builds, run with -Z macro-backtrace for more info)

For more information about this error, try `rustc --explain E0658`.
error: could not compile `chrono` (lib) due to 2 previous errors; 4 warnings emitted
```

cc @jhpratt

### PR DESCRIPTION
**Pull request by jhpratt**
Fixes #123156

Rather than expanding to `std::rt::begin_panic`, the expansion is now to `unreachable!()`. The resulting behavior is identical. A test that previously triggered the same error as #123156 has been added to ensure it does not regress.

r? compiler

### CODE REVIEW

File: compiler/rustc_builtin_macros/src/deriving/decodable.rs [hunk 1]
```diff
@@ -149,7 +149,20 @@ fn decodable_substructure(
                 arms.push(cx.arm(v_span, cx.pat_lit(v_span, cx.expr_usize(v_span, i)), decoded));
             }
 
-            arms.push(cx.arm_unreachable(trait_span));
+            let expr_unreachable = cx.expr_macro_call(
```
Comment (davidtwco) [inline compiler/rustc_builtin_macros/src/deriving/decodable.rs:152]: nit: it probably makes sense to keep `arm_unreachable` as a function and just put this in it to keep the code simpler?

**Review by davidtwco — COMMENTED** [review]
r=me unless you want to fix the nit

**Review by davidtwco — APPROVED** [review]
r=me unless you want to fix the nit

File: compiler/rustc_builtin_macros/src/deriving/decodable.rs (hunk 1 above)
Comment (jhpratt) [reply compiler/rustc_builtin_macros/src/deriving/decodable.rs]: I re-added some of the methods that were initially removed.
