### PR TITLE
Make inline const work in range patterns

### LINKED ISSUE #78108: A problem with inline_const feature in ranges
As soon as I've seen the new inline_const feature, I've tried to find some use cases for it in my code, and I did find only very few of them, unfortunately, and one of the two uses cases could be reduced to this:

```rust
#![allow(incomplete_features)]
#![feature(inline_const)]
fn main() {
    const N: u32 = 10;
    let x: u32 = 3;

    match x {
        1 .. const { N - 1 } => {},
        _ => {},
    }
}
```
That gives errors:
```rust
error: expected one of `=>`, `if`, or `|`, found keyword `const`
 --> ...\temp.rs:9:14
  |
9 |         1 .. const { N - 1 } => {},
  |              ^^^^^ expected one of `=>`, `if`, or `|`

error[E0658]: half-open range patterns are unstable
 --> ...\temp.rs:9:9
  |
9 |         1 .. const { N - 1 } => {},
  |         ^^^^
  |
  = note: see issue #67264 <https://github.com/rust-lang/rust/issues/67264> for more information
  = help: add `#![feature(half_open_range_patterns)]` to the crate attributes to enable
```

So I am not sure if this is a bug report or an enhancement request.

### PR DESCRIPTION
**Pull request by spastorino**
Fixes #78108 which is a follow up of https://github.com/rust-lang/rust/pull/77124

r? @petrochenkov

### CODE REVIEW

File: src/test/ui/inline-const/const-match-pat-range.rs [hunk 1]
```diff
@@ -0,0 +1,23 @@
...
+
+    match x {
+        const { N - 1 } ..= const { N + 1 } => {},
+        _ => {},
+    }
+
+    match x {
+        1 ..= const { N - 1 } => {},
+        _ => {},
+    }
```
Comment (petrochenkov) [inline src/test/ui/inline-const/const-match-pat-range.rs:22]: Could you add test cases for half-open ranges as well - `const { N } ..` and `.. const { N }`?

**Comment by petrochenkov** [comment]
r=me with additional test cases.

**Comment by spastorino** [comment]
@petrochenkov check it out again because the half open ranges solutions seems a bit hacky to me.

File: compiler/rustc_ast/src/token.rs [hunk 2]
```diff
@@ -553,6 +553,10 @@ impl Token {
         self == &Lt || self == &BinOp(Shl)
     }
 
+    pub fn is_inline_const_start(&self) -> bool {
+        self.is_keyword(kw::Const)
+    }
```
Comment (petrochenkov) [inline compiler/rustc_ast/src/token.rs:558]: Could you always use `check_inline_const` instead of introducing new functions?
You could add a `dist: usize` to it for the lookahead case (see `fn is_keyword_ahead` as an example.)

File: compiler/rustc_parse/src/parser/pat.rs [hunk 3]
```diff
@@ -716,17 +727,20 @@ impl<'a> Parser<'a> {
     }
 
     /// Is the token `dist` away from the current suitable as the start of a range patterns end?
-    fn is_pat_range_end_start(&self, dist: usize) -> bool {
+    fn is_pat_range_end_start(&mut self, dist: usize) -> bool {
```
Comment (petrochenkov) [inline compiler/rustc_parse/src/parser/pat.rs:730]:
```suggestion
    fn is_pat_range_end_start(&self, dist: usize) -> bool {
```

File: compiler/rustc_parse/src/parser/pat.rs [hunk 4]
```diff
@@ -716,17 +727,20 @@ impl<'a> Parser<'a> {
...
+            || t.kind == token::Dot // e.g. `.5` for recovery;
+            || t.can_begin_literal_maybe_minus() // e.g. `42`.
                 || t.is_whole_expr()
         })
     }
 
     fn parse_pat_range_end(&mut self) -> PResult<'a, P<Expr>> {
-        if self.check_path() {
+        if self.check_inline_const() {
+            self.parse_const_expr(self.token.span)
```
Comment (petrochenkov) [inline compiler/rustc_parse/src/parser/pat.rs:742]: Semi-related: could you rename `parse_const_expr` into `parse_const_block`, this is a missing part of my old comment - https://github.com/rust-lang/rust/pull/77124#discussion_r494532128.

File: src/test/ui/inline-const/const-match-pat-range.rs (hunk 1 above)
Comment (petrochenkov) [reply src/test/ui/inline-const/const-match-pat-range.rs:32]: Could you add `..= const { .. }` to test cases as well, so all range code paths are covered?

File: compiler/rustc_parse/src/parser/pat.rs [hunk 5]
```diff
@@ -315,7 +315,18 @@ impl<'a> Parser<'a> {
             PatKind::Box(pat)
         } else if self.check_inline_const() {
             // Parse `const pat`
-            PatKind::Lit(self.parse_const_expr(lo.to(self.token.span))?)
+            let const_expr = self.parse_const_expr(lo.to(self.token.span))?;
+
+            if let Some(re) = self.parse_range_end() {
+                if !self.check(&token::FatArrow) {
```
Comment (petrochenkov) [inline compiler/rustc_parse/src/parser/pat.rs:321]: I think `parse_pat_range_begin_with` is supposed to be used here.
See how range end is treated in other cases (`CONST .. <END>` and `10 .. <END>`).

File: src/test/ui/inline-const/const-match-pat-range.rs (hunk 1 above)
Comment (spastorino) [reply src/test/ui/inline-const/const-match-pat-range.rs:32]: Let me know if the added tests are the ones you wanted to include

File: src/test/ui/inline-const/const-match-pat-range.rs [hunk 6]
```diff
@@ -0,0 +1,44 @@
...
+    match x {
+        ..= const { N + 1 } => {},
+        _ => {}
+    }
+
+    match x {
+        const { N + 1 } ..= => {},
+        _ => {},
+    }
+
```
Comment (camelid) [inline src/test/ui/inline-const/const-match-pat-range.rs:43]: nit: extra blank line

**Review by camelid — COMMENTED** [review]
It might be a good idea to add some UI check-fail tests for cases like:

```rust
match x {
    1 .. const 2 => {}
}
```

**Comment by spastorino** [comment]
> ```rust
> match x {
>     1 .. const 2 => {}
> }
> ```

It's interesting how this case fails ...

```
error[E0586]: inclusive range with no end
 --> src/test/ui/inline-const/const-match-pat-fail.rs:5:11
  |
5 |         1 ..= const 2 => {}
  |           ^^^ help: use `..` instead
  |
  = note: inclusive ranges must be bounded at the end (`..=b` or `a..=b`)

error: expected one of `=>`, `if`, or `|`, found keyword `const`
 --> src/test/ui/inline-const/const-match-pat-fail.rs:5:15
  |
5 |         1 ..= const 2 => {}
  |               ^^^^^ expected one of `=>`, `if`, or `|`

error[E0658]: half-open range patterns are unstable
 --> src/test/ui/inline-const/const-match-pat-fail.rs:5:9
  |
5 |         1 ..= const 2 => {}
  |         ^^^^^
  |
  = note: see issue #67264 <https://github.com/rust-lang/rust/issues/67264> for more information
  = help: add `#![feature(half_open_range_patterns)]` to the crate attributes to enable
```

In the parser we are looking for `const {` not just const so it asummes that it's a half-open range with no end. Unsure what would be ok to do with this case but the error doesn't sound great.
Anyway it's the same that happens if instead of const you use something else like let.

```
error[E0586]: inclusive range with no end
 --> src/test/ui/inline-const/const-match-pat-fail.rs:5:11
  |
5 |         1 ..= let 2 => {}
  |           ^^^ help: use `..` instead
  |
  = note: inclusive ranges must be bounded at the end (`..=b` or `a..=b`)

error: expected one of `=>`, `if`, or `|`, found keyword `let`
 --> src/test/ui/inline-const/const-match-pat-fail.rs:5:15
  |
5 |         1 ..= let 2 => {}
  |               ^^^ expected one of `=>`, `if`, or `|`

error[E0658]: half-open range patterns are unstable
 --> src/test/ui/inline-const/const-match-pat-fail.rs:5:9
  |
5 |         1 ..= let 2 => {}
  |         ^^^^^
  |
  = note: see issue #67264 <https://github.com/rust-lang/rust/issues/67264> for more information
  = help: add `#![feature(half_open_range_patterns)]` to the crate attributes to enable
```

**Comment by camelid** [comment]
> In the parser we are looking for `const {` not just const so it asummes that it's a half-open range with no end. Unsure what would be ok to do with this case but the error doesn't sound great.

I'm trying to work on this in #78168.

**Comment by petrochenkov** [comment]
r=me after squashing commits.
