### PR TITLE
Disallow subtyping between T and U in T: Unsize<U>.

### LINKED ISSUE #40288: Mutable slices as function parameters allow aliasing mutable references
This currently affects all 3 release channels.

If you have a mutable slice of references as an input to a function, it allows borrows to escape and cause aliasing. The following example compiles and prints "3", but it shouldn't compile at all ([Playground](https://is.gd/sOSun1)):

```rust
fn save_ref<'a>(refr: &'a i32, to: &mut [&'a i32]) {
    for val in &mut *to {
        *val = refr;
    }
}

fn main() {
    let ref init = 0i32;
    let ref mut refr = 1i32;

    let mut out = [init];
    
    save_ref(&*refr, &mut out);
    
    // This shouldn't be allowed as `refr` is borrowed
    *refr = 3;
    
    // Prints 3?!
    println!("{:?}", out[0]);
}
```

This appears to be tied to slices as the non-slice equivalent fails to compile as expected ([Playground](https://is.gd/wKt36u)):

```rust
fn save_ref<'a>(refr: &'a i32, to: &mut &'a i32) {
    *to = refr;
}

fn main() {
    let ref mut refr = 1i32;
    let mut out = &0i32;
    
    save_ref(&*refr, &mut out);
    
    // ERROR: cannot assign to `*refr` because it is borrowed
    *refr = 3;

    println!("{:?}", out);
}
``` 

cc seanmonstar/httparse#34

### PR DESCRIPTION
**Pull request by eddyb**
Because `&mut T` can be coerced to `&mut U`, `T` and `U` must be unified invariantly. Fixes #40288.
E.g. coercing `&mut [&'a X; N]` to `&mut [&'b X]` must require `'a` be equal to `'b`, otherwise you can convert between `&'a X` and `&'b X` (in either direction), potentially unsoundly lengthening lifetimes.

Subtyping here was introduced with `Unsize` in #24619 (landed in 1.1, original PR is #23785).

### CODE REVIEW

**Comment by eddyb** [comment]
(starting crater run now)

**Comment by nikomatsakis** [comment]
The code looks good to me, curious to hear the results of the crater run. I'll try to do a quick skim through the code to convince myself that these are all the relevant cases though.

File: src/librustc_typeck/check/coercion.rs [hunk 1]
```diff
@@ -424,20 +425,29 @@ impl<'f, 'gcx, 'tcx> Coerce<'f, 'gcx, 'tcx> {
...
 
         // Handle reborrows before selecting `Source: CoerceUnsized<Target>`.
         let (source, reborrow) = match (&source.sty, &target.sty) {
             (&ty::TyRef(_, mt_a), &ty::TyRef(_, mt_b)) => {
                 coerce_mutbls(mt_a.mutbl, mt_b.mutbl)?;
 
-                let coercion = Coercion(self.cause.span);
-                let r_borrow = self.next_region_var(coercion);
-                (mt_a.ty, Some(AutoBorrow::Ref(r_borrow, mt_b.mutbl)))
+                // For `&T`, we don't reborrow, (which is only needed
```
Comment (arielb1) [inline src/librustc_typeck/check/coercion.rs]: Don't you need this also on the raw ptr path? better to subtype `source` as one unit.

Comment (eddyb) [inline src/librustc_typeck/check/coercion.rs]: Subtype first, then resolve the variable, then reborrow from `&mut` and/or to raw pointers?

Comment (eddyb) [inline src/librustc_typeck/check/coercion.rs]: Aaaaah, that would also keep `Rc` working! I'll try to do it that way and add more testcases.

**Comment by eddyb** [comment]
[Crater report](https://gist.github.com/eddyb/7109897c4201cf4eed08bf60d21fed00) shows 6 root regressions:
* [ ] [`valico`](https://crates.io/crates/valico) ([failure](https://taskcluster.github.io/unified-logviewer/?url=https%3A%2F%2Fqueue.taskcluster.net%2Fv1%2Ftask%2FwXs7hXyqS6qY2q9CG_414w%2Fruns%2F0%2Fartifacts%2Fpublic%2Flogs%2Flive.log&highlightStart=147&highlightEnd=147&lineNumber=&wrapLines=false&showLineNumbers=true&jumpToHighlight=true&followLog=false&lineHeight=19&asText=false))
* [ ] [`mime_multipart`](https://crates.io/crates/mime_multipart) ([failure](https://taskcluster.github.io/unified-logviewer/?url=https%3A%2F%2Fqueue.taskcluster.net%2Fv1%2Ftask%2Fh9cTOHh_QFGcpuvk2d6JHQ%2Fruns%2F0%2Fartifacts%2Fpublic%2Flogs%2Flive.log&highlightStart=147&highlightEnd=147&lineNumber=&wrapLines=false&showLineNumbers=true&jumpToHighlight=true&followLog=false&lineHeight=19&asText=false))
* [ ] [`intervallum`](https://crates.io/crates/intervallum) ([failure](https://taskcluster.github.io/unified-logviewer/?url=https%3A%2F%2Fqueue.taskcluster.net%2Fv1%2Ftask%2FaENhLvnBSdeq_dDoqL0G_Q%2Fruns%2F0%2Fartifacts%2Fpublic%2Flogs%2Flive.log&highlightStart=110&highlightEnd=110&lineNumber=&wrapLines=false&showLineNumbers=true&jumpToHighlight=true&followLog=false&lineHeight=19&asText=false))
* [ ] [`crayon`](https://crates.io/crates/crayon) ([failure](https://taskcluster.github.io/unified-logviewer/?url=https%3A%2F%2Fqueue.taskcluster.net%2Fv1%2Ftask%2FKsanb73ITuG0uLb2TKk16g%2Fruns%2F0%2Fartifacts%2Fpublic%2Flogs%2Flive.log&highlightStart=309&highlightEnd=309&lineNumber=&wrapLines=false&showLineNumbers=true&jumpToHighlight=true&followLog=false&lineHeight=19&asText=false))
* [ ] [`multipart`](https://crates.io/crates/multipart) ([failure](https://taskcluster.github.io/unified-logviewer/?url=https%3A%2F%2Fqueue.taskcluster.net%2Fv1%2Ftask%2FExJiw3fPRrqgJWy_fGLABQ%2Fruns%2F0%2Fartifacts%2Fpublic%2Flogs%2Flive.log&highlightStart=275&highlightEnd=275&lineNumber=&wrapLines=false&showLineNumbers=true&jumpToHighlight=true&followLog=false&lineHeight=19&asText=false)) (similar/same crate as `mime_multipart`?)
* [ ] [`yamlette`](https://crates.io/crates/yamlette) ([failure](https://taskcluster.github.io/unified-logviewer/?url=https%3A%2F%2Fqueue.taskcluster.net%2Fv1%2Ftask%2FB9jKp6rXRgOu7gN9hGWh5Q%2Fruns%2F0%2Fartifacts%2Fpublic%2Flogs%2Flive.log&highlightStart=108&highlightEnd=108&lineNumber=&wrapLines=false&showLineNumbers=true&jumpToHighlight=true&followLog=false&lineHeight=19&asText=false))

**Comment by Stebalien** [comment]
> similar/same crate as mime_multipart?

Different crates but the issue in both stems from the `httparse`  bug (the original bug linked in the first post). Those are both legitimate UB (I can't tell with the other bugs).

**Comment by eddyb** [comment]
@Stebalien I hadn't even realized that was the original report! Alright, I'm more confident now.
I've only looked in depth at `crayon` (AFAICT there's some lifetime parameter order confusion).

Assuming only `{mime_},multipart` and `valico` have any dependents, we should be able to release fixed patch versions of them (if it's possible at all without changing the API), and that will be that.

**Comment by eddyb** [comment]
So the crates that other crates depend on are:
* [ ] @s-panferov's `valico` (needs fix and `1.0.2` released)
* [ ] @mikedilger's `mime_multipart` (needs fix and `0.3.6` and `0.4.1` released)
* [ ] @abonander's `multipart` (needs fix and `0.9.1` released)

Everything else we can break without having a cascade of regressions.
I may attempt making PRs to some of the crates, but they're pretty tough to understand.

**Comment by abonander** [comment]
I've already got this fixed in `multipart 0.10.1` so it's trivial to backport.

**Comment by eddyb** [comment]
@abonander (and everyone else) Ping me when you have the fix on a branch somewhere, or a patch in a gist, etc. if you want a confirmation that it indeed compiles with this branch.

**Comment by abonander** [comment]
@eddyb branch `0.9` has the fix backported. I'll publish once you confirm.

**Comment by eddyb** [comment]
@abonander It compiles 👍

**Comment by abonander** [comment]
@eddyb Published.

**Comment by mikedilger** [comment]
@eddyb Not sure I understand the bug very well, but I hope a simple sub-scope makes the borrow issue go away.  Let me know if thats right or if I need some other fix.  https://github.com/mikedilger/mime-multipart/tree/rust40288

**Comment by eddyb** [comment]
@mikedilger Almost there! I was getting confused by not knowing what is actually keeping the borrow alive.
Turns out your change is in the right direction, you just have to *also* move `header_memory` in that block.
That should work on both `0.4.0` (master) and `0.3.5` (b118d606feb62c15d0dbd4e3280597a02e004190).

**Comment by mikedilger** [comment]
@eddyb Ok, I (evilly) force-pushed  https://github.com/mikedilger/mime-multipart/tree/rust40288 and also created  https://github.com/mikedilger/mime-multipart/tree/rust40288_03 for the 0.3 branch.  Once they are confirmed to work I'll pull them in and publish new versions.

**Comment by eddyb** [comment]
@mikedilger Those do indeed work, thank you!

**Comment by mikedilger** [comment]
@eddyb Published.

File: src/librustc_typeck/check/coercion.rs [hunk 2]
```diff
@@ -424,20 +425,32 @@ impl<'f, 'gcx, 'tcx> Coerce<'f, 'gcx, 'tcx> {
...
-        // Note, we want to avoid unnecessary unsizing. We don't want to coerce to
-        // a DST unless we have to. This currently comes out in the wash since
-        // we can't unify [T] with U. But to properly support DST, we need to allow
-        // that, at which point we will need extra checks on the target here.
+        // Subtype the whole source type first, allowing, e.g.
+        // coercing `&'static [&'static T; N]` to `&'b [&'a T]`,
+        // or `Rc<[&'static T; N]>` to `Rc<[&'a T]>`, etc.
+        let coercion = TypeVariableOrigin::MiscVariable(self.cause.span);
+        let super_source = self.next_ty_var(coercion);
+        match self.sub_types(false, &self.cause, source, super_source)? {
```
Comment (eddyb) [inline src/librustc_typeck/check/coercion.rs]: Not needing `use_lub` felt wrong, and it is!
Reordering [these two](https://github.com/rustless/valico/blob/ba11d71b6f5210d0ea1740828f2a54881f2eff74/src/json_dsl/param.rs#L136-L140) `match` arms "fixes" the false positive, but they should both work identically.
I'm preparing an improved version that should not have this problem.

**Comment by eddyb** [comment]
[Second crater report](https://gist.github.com/eddyb/28147c1af27bdf630aecb2e3b7d5b5a6) leaves only two regressions, `assembunny_plus` and `yamlette`.

File: src/test/run-pass/coerce-subtype.rs [hunk 3]
```diff
@@ -0,0 +1,39 @@
...
+// http://www.apache.org/licenses/LICENSE-2.0> or the MIT license
+// <LICENSE-MIT or http://opensource.org/licenses/MIT>, at your
+// option. This file may not be copied, modified, or distributed
+// except according to those terms.
+
+// pretty-expanded FIXME #23616
+
+use std::rc::Rc;
+
+fn lub_short<'a, T>(_: &[&'a T], _: &[&'a T]) {}
```
Comment (nikomatsakis) [inline src/test/run-pass/coerce-subtype.rs]: can you add a comment explaining precisely what this test is shooting for?

**Review by nikomatsakis — APPROVED** [review]
r=me with a comment in the test

File: src/test/run-pass/coerce-subtype.rs (hunk 3 above)
Comment (eddyb) [inline src/test/run-pass/coerce-subtype.rs]: This function or the whole file? The function is just a helper.
