### PR TITLE
use `LocalDefId` instead of `HirId` in trait resolution to simplify the obligation clause resolution

### LINKED ISSUE #104827: internal compiler error: local_def_id: no entry for HirId
### Code

It appears this occurs when the ` impl FromResidual` is located inside the function. Moving it out yields regular compiler errors. 

```Rust
#![feature(try_trait_v2)]

use core::ops::FromResidual;

struct MySnafu;

fn test_function() {
    impl FromResidual for MySnafu {
        fn from_residual(s: Self) -> Self {
            todo!()
        }
    }
}
```

### Meta

`rustc --version --verbose`:
```
rustc 1.67.0-nightly (70f8737b2 2022-11-23)
binary: rustc
commit-hash: 70f8737b2f5d3bf7d6b784fad00b663b7ff9feda
commit-date: 2022-11-23
host: aarch64-apple-darwin
release: 1.67.0-nightly
LLVM version: 15.0.4
```

Also `rustc 1.67.0-nightly (a28f3c88e 2022-11-20)`

### Error output

```
error: internal compiler error: /rustc/70f8737b2f5d3bf7d6b784fad00b663b7ff9feda/compiler/rustc_middle/src/hir/map/mod.rs:175:13: local_def_id: no entry for `HirId { owner: OwnerId { def_id: DefId(0:8 ~ try_trait[742b]::test_function) }, local_id: 1 }`, which has a map of `Some(Stmt(Stmt { hir_id: HirId { owner: OwnerId { def_id: DefId(0:8 ~ try_trait[742b]::test_function) }, local_id: 1 }, kind: Item(ItemId { owner_id: OwnerId { def_id: DefId(0:9 ~ try_trait[742b]::test_function::{impl#0}) } }), span: src/lib.rs:8:5: 12:6 (#0) }))`

thread 'rustc' panicked at 'Box<dyn Any>', /rustc/70f8737b2f5d3bf7d6b784fad00b663b7ff9feda/compiler/rustc_errors/src/lib.rs:1560:9
stack backtrace:
   0:        0x104de3c44 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h5ceaa9f104581d16
   1:        0x104e34ff0 - core::fmt::write::h70c33f48cfd4e8aa
   2:        0x104dd71f4 - std::io::Write::write_fmt::h24e387c05c0fa515
   3:        0x104de3a58 - std::sys_common::backtrace::print::ha3dd569c0e03b1e6
   4:        0x104de64ec - std::panicking::default_hook::{{closure}}::h85ce766fb3b3c496
   5:        0x104de6244 - std::panicking::default_hook::h7c44756c2f138c7c
   6:        0x10cede784 - rustc_driver[34fe2e47ceb1eef]::DEFAULT_HOOK::{closure#0}::{closure#0}
   7:        0x104de6be4 - std::panicking::rust_panic_with_hook::h243fdb33bd154152
   8:        0x110b7b9e0 - std[f91ad3a11560037b]::panicking::begin_panic::<rustc_errors[159eca52afa358bf]::ExplicitBug>::{closure#0}
   9:        0x110b75aec - std[f91ad3a11560037b]::sys_common::backtrace::__rust_end_short_backtrace::<std[f91ad3a11560037b]::panicking::begin_panic<rustc_errors[159eca52afa358bf]::ExplicitBug>::{closure#0}, !>
  10:        0x111166b8c - std[f91ad3a11560037b]::panicking::begin_panic::<rustc_errors[159eca52afa358bf]::ExplicitBug>
  11:        0x110b75ae0 - std[f91ad3a11560037b]::panic::panic_any::<rustc_errors[159eca52afa358bf]::ExplicitBug>
  12:        0x110b6ec54 - <rustc_errors[159eca52afa358bf]::HandlerInner>::bug::<&alloc[81ea9162d64fa727]::string::String>
  13:        0x110b6e7a4 - <rustc_errors[159eca52afa358bf]::Handler>::bug::<&alloc[81ea9162d64fa727]::string::String>
  14:        0x110c84fdc - rustc_middle[c84cff28799a9d3c]::ty::context::tls::with_context_opt::<rustc_middle[c84cff28799a9d3c]::ty::context::tls::with_opt<rustc_middle[c84cff28799a9d3c]::util::bug::opt_span_bug_fmt<rustc_span[668ea99b1ecd1622]::span_encoding::Span>::{closure#0}, ()>::{closure#0}, ()>
  15:        0x110c861c4 - rustc_middle[c84cff28799a9d3c]::util::bug::opt_span_bug_fmt::<rustc_span[668ea99b1ecd1622]::span_encoding::Span>
  16:        0x111168288 - rustc_middle[c84cff28799a9d3c]::util::bug::bug_fmt
  17:        0x110a161b0 - <rustc_infer[3bc63bf749147a71]::infer::error_reporting::TypeErrCtxt as rustc_trait_selection[b44494f3cb938fdc]::traits::error_reporting::suggestions::TypeErrCtxtExt>::suggest_await_before_try
  18:        0x110a0ece4 - <rustc_infer[3bc63bf749147a71]::infer::error_reporting::TypeErrCtxt as rustc_trait_selection[b44494f3cb938fdc]::traits::error_reporting::TypeErrCtxtExt>::report_selection_error
  19:        0x110a163f0 - <rustc_infer[3bc63bf749147a71]::infer::error_reporting::TypeErrCtxt as rustc_trait_selection[b44494f3cb938fdc]::traits::error_reporting::InferCtxtPrivExt>::report_fulfillment_error
  20:        0x110a0b4a8 - <rustc_infer[3bc63bf749147a71]::infer::error_reporting::TypeErrCtxt as rustc_trait_selection[b44494f3cb938fdc]::traits::error_reporting::TypeErrCtxtExt>::report_fulfillment_errors
  21:        0x10f3ff7c0 - rustc_hir_analysis[aa2bb5447508424a]::check::wfcheck::check_well_formed
  22:        0x110151e00 - <rustc_query_system[12fba011c4346c8d]::dep_graph::graph::DepGraph<rustc_middle[c84cff28799a9d3c]::dep_graph::dep_node::DepKind>>::with_task::<rustc_middle[c84cff28799a9d3c]::ty::context::TyCtxt, rustc_hir[91bdc5c262343971]::hir_id::OwnerId, ()>
  23:        0x10ff0e680 - rustc_query_system[12fba011c4346c8d]::query::plumbing::try_execute_query::<rustc_query_impl[fb17ba4877a40690]::plumbing::QueryCtxt, rustc_query_system[12fba011c4346c8d]::query::caches::DefaultCache<rustc_hir[91bdc5c262343971]::hir_id::OwnerId, ()>>
  24:        0x10ff8174c - rustc_query_system[12fba011c4346c8d]::query::plumbing::get_query::<rustc_query_impl[fb17ba4877a40690]::queries::check_well_formed, rustc_query_impl[fb17ba4877a40690]::plumbing::QueryCtxt>
  25:        0x10f3447cc - rustc_data_structures[aec675fb838b577e]::sync::par_for_each_in::<&[rustc_hir[91bdc5c262343971]::hir::ItemId], <rustc_middle[c84cff28799a9d3c]::hir::ModuleItems>::par_items<rustc_hir_analysis[aa2bb5447508424a]::check::wfcheck::check_mod_type_wf::{closure#0}>::{closure#0}>
  26:        0x10f4088c8 - rustc_hir_analysis[aa2bb5447508424a]::check::wfcheck::check_mod_type_wf
  27:        0x110133648 - <rustc_query_system[12fba011c4346c8d]::dep_graph::graph::DepGraph<rustc_middle[c84cff28799a9d3c]::dep_graph::dep_node::DepKind>>::with_task::<rustc_middle[c84cff28799a9d3c]::ty::context::TyCtxt, rustc_span[668ea99b1ecd1622]::def_id::LocalDefId, ()>
  28:        0x10fec79ec - rustc_query_system[12fba011c4346c8d]::query::plumbing::try_execute_query::<rustc_query_impl[fb17ba4877a40690]::plumbing::QueryCtxt, rustc_query_system[12fba011c4346c8d]::query::caches::DefaultCache<rustc_span[668ea99b1ecd1622]::def_id::LocalDefId, ()>>
  29:        0x10ff81614 - rustc_query_system[12fba011c4346c8d]::query::plumbing::get_query::<rustc_query_impl[fb17ba4877a40690]::queries::check_mod_type_wf, rustc_query_impl[fb17ba4877a40690]::plumbing::QueryCtxt>
  30:        0x10f3448b0 - rustc_data_structures[aec675fb838b577e]::sync::par_for_each_in::<&[rustc_hir[91bdc5c262343971]::hir_id::OwnerId], <rustc_middle[c84cff28799a9d3c]::hir::map::Map>::par_for_each_module<rustc_hir_analysis[aa2bb5447508424a]::check_crate::{closure#5}::{closure#0}::{closure#0}>::{closure#0}>
  31:        0x10f389814 - <rustc_session[ee64fa510201ce22]::session::Session>::track_errors::<rustc_hir_analysis[aa2bb5447508424a]::check_crate::{closure#5}, ()>
  32:        0x10f45b6f4 - rustc_hir_analysis[aa2bb5447508424a]::check_crate
  33:        0x10cf7c164 - rustc_interface[d6308f9366e490e8]::passes::analysis
  34:        0x11015be2c - <rustc_query_system[12fba011c4346c8d]::dep_graph::graph::DepGraph<rustc_middle[c84cff28799a9d3c]::dep_graph::dep_node::DepKind>>::with_task::<rustc_middle[c84cff28799a9d3c]::ty::context::TyCtxt, (), core[b4b423dc40156325]::result::Result<(), rustc_errors[159eca52afa358bf]::ErrorGuaranteed>>
  35:        0x10ff26544 - rustc_query_system[12fba011c4346c8d]::query::plumbing::try_execute_query::<rustc_query_impl[fb17ba4877a40690]::plumbing::QueryCtxt, rustc_query_system[12fba011c4346c8d]::query::caches::DefaultCache<(), core[b4b423dc40156325]::result::Result<(), rustc_errors[159eca52afa358bf]::ErrorGuaranteed>>>
  36:        0x10ff9a86c - rustc_query_system[12fba011c4346c8d]::query::plumbing::get_query::<rustc_query_impl[fb17ba4877a40690]::queries::analysis, rustc_query_impl[fb17ba4877a40690]::plumbing::QueryCtxt>
  37:        0x10ceaad78 - <rustc_interface[d6308f9366e490e8]::passes::QueryContext>::enter::<rustc_driver[34fe2e47ceb1eef]::run_compiler::{closure#1}::{closure#2}::{closure#3}, core[b4b423dc40156325]::result::Result<(), rustc_errors[159eca52afa358bf]::ErrorGuaranteed>>
  38:        0x10cebab40 - rustc_span[668ea99b1ecd1622]::with_source_map::<core[b4b423dc40156325]::result::Result<(), rustc_errors[159eca52afa358bf]::ErrorGuaranteed>, rustc_interface[d6308f9366e490e8]::interface::run_compiler<core[b4b423dc40156325]::result::Result<(), rustc_errors[159eca52afa358bf]::ErrorGuaranteed>, rustc_driver[34fe2e47ceb1eef]::run_compiler::{closure#1}>::{closure#0}::{closure#1}>
  39:        0x10ceb1f8c - <scoped_tls[44143ff9a1fdbbff]::ScopedKey<rustc_span[668ea99b1ecd1622]::SessionGlobals>>::set::<rustc_interface[d6308f9366e490e8]::interface::run_compiler<core[b4b423dc40156325]::result::Result<(), rustc_errors[159eca52afa358bf]::ErrorGuaranteed>, rustc_driver[34fe2e47ceb1eef]::run_compiler::{closure#1}>::{closure#0}, core[b4b423dc40156325]::result::Result<(), rustc_errors[159eca52afa358bf]::ErrorGuaranteed>>
  40:        0x10ce80f74 - std[f91ad3a11560037b]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[d6308f9366e490e8]::util::run_in_thread_pool_with_globals<rustc_interface[d6308f9366e490e8]::interface::run_compiler<core[b4b423dc40156325]::result::Result<(), rustc_errors[159eca52afa358bf]::ErrorGuaranteed>, rustc_driver[34fe2e47ceb1eef]::run_compiler::{closure#1}>::{closure#0}, core[b4b423dc40156325]::result::Result<(), rustc_errors[159eca52afa358bf]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[b4b423dc40156325]::result::Result<(), rustc_errors[159eca52afa358bf]::ErrorGuaranteed>>
  41:        0x10ce66d40 - <<std[f91ad3a11560037b]::thread::Builder>::spawn_unchecked_<rustc_interface[d6308f9366e490e8]::util::run_in_thread_pool_with_globals<rustc_interface[d6308f9366e490e8]::interface::run_compiler<core[b4b423dc40156325]::result::Result<(), rustc_errors[159eca52afa358bf]::ErrorGuaranteed>, rustc_driver[34fe2e47ceb1eef]::run_compiler::{closure#1}>::{closure#0}, core[b4b423dc40156325]::result::Result<(), rustc_errors[159eca52afa358bf]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[b4b423dc40156325]::result::Result<(), rustc_errors[159eca52afa358bf]::ErrorGuaranteed>>::{closure#1} as core[b4b423dc40156325]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  42:        0x104deee60 - std::sys::unix::thread::Thread::new::thread_start::h94b0d6958f791f7f
  43:        0x1a46f206c - __pthread_deallocate

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.67.0-nightly (70f8737b2 2022-11-23) running on aarch64-apple-darwin

note: compiler flags: --crate-type lib -C embed-bitcode=no -C split-debuginfo=unpacked -C debuginfo=2 -C incremental=[REDACTED]

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [check_well_formed] checking that `test_function::<impl at src/lib.rs:8:5: 8:34>` is well-formed
#1 [check_mod_type_wf] checking that types are well-formed in top-level module
#2 [analysis] running analysis passes on this crate
end of query stack
```

### PR DESCRIPTION
**Pull request by vincenzopalazzo**
This commit introduces a refactoring suggested by @lcnr to simplify the obligation clause resolution.

This is just the first PR that introduces a type of refactoring, but others PRs will follow this to introduce name changing to change from the variable name from `body_id` to something else.

Fixes https://github.com/rust-lang/rust/issues/104827

Signed-off-by: Vincenzo Palazzo <vincenzopalazzodev@gmail.com>

@rustbot r? @lcnr

### CODE REVIEW

File: compiler/rustc_hir_analysis/src/check/compare_method.rs [hunk 1]
```diff
@@ -153,13 +153,10 @@ fn compare_predicate_entailment<'tcx>(
     // This node-id should be used for the `body_id` field on each
     // `ObligationCause` (and the `FnCtxt`).
     //
-    // FIXME(@lcnr): remove that after removing `cause.body_id` from
-    // obligations.
-    let impl_m_hir_id = tcx.hir().local_def_id_to_hir_id(impl_m.def_id.expect_local());
     // We sometimes modify the span further down.
```
Comment (lcnr) [inline compiler/rustc_hir_analysis/src/check/compare_method.rs:156]: can you instead use `let impl_m_def_id = impl_m.def_id.expect_local()` instead of using `expect_local()` multiple times in this method?

File: compiler/rustc_hir_analysis/src/check/compare_method.rs [hunk 2]
```diff
@@ -628,15 +626,15 @@ struct ImplTraitInTraitCollector<'a, 'tcx> {
     types: FxHashMap<DefId, (Ty<'tcx>, ty::SubstsRef<'tcx>)>,
     span: Span,
     param_env: ty::ParamEnv<'tcx>,
-    body_id: hir::HirId,
+    body_id: hir::def_id::LocalDefId,
```
Comment (lcnr) [inline compiler/rustc_hir_analysis/src/check/compare_method.rs:629]: nit: add `use rustc_span::def_id::LocalDefId;` to the top of this function instead.

File: compiler/rustc_hir_analysis/src/check/compare_method.rs [hunk 3]
```diff
@@ -1511,7 +1504,8 @@ fn compare_type_predicate_entailment<'tcx>(
 
     debug!("compare_type_predicate_entailment: bounds={:?}", hybrid_preds);
 
-    let normalize_cause = traits::ObligationCause::misc(impl_ty_span, impl_ty_hir_id);
+    let normalize_cause =
+        traits::ObligationCause::misc(impl_ty_span, impl_ty.def_id.expect_local());
```
Comment (lcnr) [inline compiler/rustc_hir_analysis/src/check/compare_method.rs:1508]: same here, `let impl_ty_def_id = impl_ty.def_id.expect_local();`

File: compiler/rustc_hir_typeck/src/fn_ctxt/mod.rs [hunk 4]
```diff
@@ -157,7 +157,8 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
     }
 
     pub fn cause(&self, span: Span, code: ObligationCauseCode<'tcx>) -> ObligationCause<'tcx> {
-        ObligationCause::new(span, self.body_id, code)
+        let body_def_id = self.tcx.hir().local_def_id(self.body_id);
```
Comment (lcnr) [inline compiler/rustc_hir_typeck/src/fn_ctxt/mod.rs:160]: change `body_id` of `FnCtxt` to be a `LocalDefId` as well

**Review by lcnr — COMMENTED** [review]
didn't yet look through everything, will do the rest of this PR later

File: compiler/rustc_hir_analysis/src/check/intrinsic.rs [hunk 5]
```diff
@@ -56,7 +56,8 @@ fn equate_intrinsic_type<'tcx>(
         && gen_count_ok(own_counts.consts, 0, "const")
     {
         let fty = tcx.mk_fn_ptr(sig);
-        let cause = ObligationCause::new(it.span, it.hir_id(), ObligationCauseCode::IntrinsicType);
+        let it_def_id = tcx.hir().local_def_id(it.hir_id());
```
Comment (cjgillot) [inline compiler/rustc_hir_analysis/src/check/intrinsic.rs:59]:
```suggestion
        let it_def_id = it.owner_id.def_id;
```

File: compiler/rustc_hir_analysis/src/hir_wf_check.rs [hunk 6]
```diff
@@ -66,9 +66,10 @@ fn diagnostic_hir_wf_check<'tcx>(
         fn visit_ty(&mut self, ty: &'tcx hir::Ty<'tcx>) {
             let infcx = self.tcx.infer_ctxt().build();
             let tcx_ty = self.icx.to_ty(ty).fold_with(&mut EraseAllBoundRegions { tcx: self.tcx });
+            let def_id = self.tcx.hir().local_def_id(self.hir_id);
```
Comment (cjgillot) [inline compiler/rustc_hir_analysis/src/hir_wf_check.rs:69]: Should `HirWfCheck` directly contain a `LocalDefId`?

File: compiler/rustc_hir_typeck/src/check.rs [hunk 7]
```diff
@@ -44,10 +44,11 @@ pub(super) fn check_fn<'a, 'tcx>(
 
     let declared_ret_ty = fn_sig.output();
 
+    let body_def_id = tcx.hir().local_def_id(body.value.hir_id);
```
Comment (cjgillot) [inline compiler/rustc_hir_typeck/src/check.rs:47]: This will ICE: bodies' HirId do not have a `LocalDefId`.  Their `body_owner` does, accessible using `tcx.hir().body_owner_def_id(body_id)`.

File: compiler/rustc_trait_selection/src/traits/outlives_bounds.rs [hunk 8]
```diff
@@ -14,14 +14,14 @@ pub trait InferCtxtExt<'a, 'tcx> {
     fn implied_outlives_bounds(
         &self,
         param_env: ty::ParamEnv<'tcx>,
-        body_id: hir::HirId,
+        body_id: def_id::LocalDefId,
```
Comment (cjgillot) [inline compiler/rustc_trait_selection/src/traits/outlives_bounds.rs:17]: Please import `LocalDefId` directly, in all files that use it.

File: compiler/rustc_traits/src/implied_outlives_bounds.rs [hunk 9]
```diff
@@ -70,8 +70,9 @@ fn compute_implied_outlives_bounds<'tcx>(
         // FIXME(@lcnr): It's not really "always fine", having fewer implied
         // bounds can be backward incompatible, e.g. #101951 was caused by
         // us not dealing with inference vars in `TypeOutlives` predicates.
-        let obligations = wf::obligations(infcx, param_env, hir::CRATE_HIR_ID, 0, arg, DUMMY_SP)
-            .unwrap_or_default();
+        let obligations =
+            wf::obligations(infcx, param_env, hir::def_id::CRATE_DEF_ID, 0, arg, DUMMY_SP)
```
Comment (cjgillot) [inline compiler/rustc_traits/src/implied_outlives_bounds.rs:74]: Could you import `CRATE_DEF_ID` directly too everywhere useful?

File: compiler/rustc_hir_analysis/src/hir_wf_check.rs (hunk 6 above)
Comment (lcnr) [reply compiler/rustc_hir_analysis/src/hir_wf_check.rs:69]: yes

Comment (vincenzopalazzo) [reply compiler/rustc_hir_analysis/src/hir_wf_check.rs:69]: Yeah, maybe yes. I skipped this refactoring sometimes to have a PR with minimal change, but if make sense I can change it

File: compiler/rustc_traits/src/implied_outlives_bounds.rs (hunk 9 above)
Comment (lcnr) [reply compiler/rustc_traits/src/implied_outlives_bounds.rs:74]: yeah, I also prefer using an import, even in that case

File: compiler/rustc_hir_analysis/src/hir_wf_check.rs (hunk 6 above)
Comment (vincenzopalazzo) [reply compiler/rustc_hir_analysis/src/hir_wf_check.rs:69]: Ok this was easy 😄

File: compiler/rustc_hir_typeck/src/method/probe.rs [hunk 10]
```diff
@@ -579,10 +579,9 @@ impl<'a, 'tcx> ProbeContext<'a, 'tcx> {
     fn push_candidate(&mut self, candidate: Candidate<'tcx>, is_inherent: bool) {
         let is_accessible = if let Some(name) = self.method_name {
             let item = candidate.item;
-            let def_scope = self
-                .tcx
-                .adjust_ident_and_get_scope(name, item.container_id(self.tcx), self.body_id)
-                .1;
+            let hir_id = self.tcx.hir().local_def_id_to_hir_id(self.body_id);
+            let def_scope =
+                self.tcx.adjust_ident_and_get_scope(name, item.container_id(self.tcx), hir_id).1;
```
Comment (cjgillot) [inline compiler/rustc_hir_typeck/src/method/probe.rs:584]: Follow-up idea: make `adjust_ident_and_get_scope` take a `LocalDefId`.

File: compiler/rustc_hir_typeck/src/method/suggest.rs [hunk 11]
```diff
@@ -500,14 +501,9 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
...
                                         // suggest restricting its type params.
-                                        let did = self.tcx.hir().body_owner_def_id(hir::BodyId {
-                                            hir_id: self.body_id,
-                                        });
-                                        Some(
-                                            self.tcx
-                                                .hir()
-                                                .get(self.tcx.hir().local_def_id_to_hir_id(did)),
-                                        )
+                                        Some(self.tcx.hir().get(
```
Comment (cjgillot) [inline compiler/rustc_hir_typeck/src/method/suggest.rs:504]:
```suggestion
                                        Some(self.tcx.hir().get_by_def_id(self.body_id))
```

File: compiler/rustc_hir_typeck/src/method/suggest.rs [hunk 12]
```diff
@@ -1167,7 +1163,8 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
             _ => None,
         });
         if let Some((field, field_ty)) = field_receiver {
-            let scope = tcx.parent_module(self.body_id);
+            let hir_id = self.tcx.hir().local_def_id_to_hir_id(self.body_id);
+            let scope = tcx.parent_module(hir_id);
```
Comment (cjgillot) [inline compiler/rustc_hir_typeck/src/method/suggest.rs:1167]:
```suggestion
            let scope = tcx.parent_module_from_def_id(self.body_id);
```

File: compiler/rustc_hir_typeck/src/method/suggest.rs [hunk 13]
```diff
@@ -1939,7 +1936,8 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
             true
         });
 
-        let module_did = self.tcx.parent_module(self.body_id);
+        let body_id = self.tcx.hir().local_def_id_to_hir_id(self.body_id);
+        let module_did = self.tcx.parent_module(body_id);
```
Comment (cjgillot) [inline compiler/rustc_hir_typeck/src/method/suggest.rs:1940]:
```suggestion
        let module_did = self.tcx.parent_module_from_def_id(self.body_id);
```

File: compiler/rustc_hir_typeck/src/op.rs [hunk 14]
```diff
@@ -511,7 +511,6 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
                                         }
                                         _ => None,
                                     };
-
```
Comment (cjgillot) [inline compiler/rustc_hir_typeck/src/op.rs:514]: Spurious change?

File: compiler/rustc_infer/src/traits/mod.rs [hunk 15]
```diff
@@ -8,6 +8,7 @@ mod project;
 mod structural_impls;
 pub mod util;
 
+use hir::def_id;
```
Comment (cjgillot) [inline compiler/rustc_infer/src/traits/mod.rs:11]:
```suggestion
use hir::def_id::LocalDefId;
```

File: compiler/rustc_infer/src/traits/mod.rs [hunk 16]
```diff
@@ -142,7 +143,7 @@ impl<'tcx, O> Obligation<'tcx, O> {
 
     pub fn misc(
         span: Span,
-        body_id: hir::HirId,
+        body_id: def_id::LocalDefId,
```
Comment (cjgillot) [inline compiler/rustc_infer/src/traits/mod.rs:146]:
```suggestion
        body_id: LocalDefId,
```

File: compiler/rustc_lint/src/builtin.rs [hunk 17]
```diff
@@ -755,11 +755,12 @@ impl<'tcx> LateLintPass<'tcx> for MissingCopyImplementations {
         if ty.is_copy_modulo_regions(cx.tcx, param_env) {
             return;
         }
+        let item_hir = cx.tcx.hir().local_def_id(item.hir_id());
```
Comment (cjgillot) [inline compiler/rustc_lint/src/builtin.rs:758]:
```suggestion
        let item_hir = item.owner_id.def_id;
```

File: compiler/rustc_middle/src/traits/mod.rs [hunk 18]
```diff
@@ -15,6 +15,7 @@ use crate::ty::abstract_const::NotConstEvaluatable;
 use crate::ty::subst::SubstsRef;
 use crate::ty::{self, AdtKind, Ty, TyCtxt};
 
+use hir::def_id;
```
Comment (cjgillot) [inline compiler/rustc_middle/src/traits/mod.rs:18]:
```suggestion
use rustc_span::def_id::{CRATE_DEF_ID, LocalDefId};
```

File: compiler/rustc_middle/src/traits/mod.rs [hunk 19]
```diff
@@ -99,7 +100,7 @@ pub struct ObligationCause<'tcx> {
     /// (in particular, closures can add new assumptions). See the
     /// field `region_obligations` of the `FulfillmentContext` for more
     /// information.
-    pub body_id: hir::HirId,
+    pub body_id: def_id::LocalDefId,
```
Comment (cjgillot) [inline compiler/rustc_middle/src/traits/mod.rs:103]:
```suggestion
    pub body_id: LocalDefId,
```

File: compiler/rustc_middle/src/traits/mod.rs [hunk 20]
```diff
@@ -120,13 +121,13 @@ impl<'tcx> ObligationCause<'tcx> {
     #[inline]
     pub fn new(
         span: Span,
-        body_id: hir::HirId,
+        body_id: def_id::LocalDefId,
```
Comment (cjgillot) [inline compiler/rustc_middle/src/traits/mod.rs:124]:
```suggestion
        body_id: LocalDefId,
```

File: compiler/rustc_middle/src/traits/mod.rs [hunk 21]
```diff
@@ -120,13 +121,13 @@ impl<'tcx> ObligationCause<'tcx> {
...
         code: ObligationCauseCode<'tcx>,
     ) -> ObligationCause<'tcx> {
         ObligationCause { span, body_id, code: code.into() }
     }
 
-    pub fn misc(span: Span, body_id: hir::HirId) -> ObligationCause<'tcx> {
+    pub fn misc(span: Span, body_id: def_id::LocalDefId) -> ObligationCause<'tcx> {
```
Comment (cjgillot) [inline compiler/rustc_middle/src/traits/mod.rs:130]:
```suggestion
    pub fn misc(span: Span, body_id: LocalDefId) -> ObligationCause<'tcx> {
```

File: compiler/rustc_middle/src/traits/mod.rs [hunk 22]
```diff
@@ -137,7 +138,7 @@ impl<'tcx> ObligationCause<'tcx> {
 
     #[inline(always)]
     pub fn dummy_with_span(span: Span) -> ObligationCause<'tcx> {
-        ObligationCause { span, body_id: hir::CRATE_HIR_ID, code: Default::default() }
+        ObligationCause { span, body_id: def_id::CRATE_DEF_ID, code: Default::default() }
```
Comment (cjgillot) [inline compiler/rustc_middle/src/traits/mod.rs:141]:
```suggestion
        ObligationCause { span, body_id: CRATE_DEF_ID, code: Default::default() }
```

File: compiler/rustc_trait_selection/src/autoderef.rs [hunk 23]
```diff
@@ -1,6 +1,7 @@
 use crate::errors::AutoDerefReachedRecursionLimit;
 use crate::traits::query::evaluate_obligation::InferCtxtExt;
 use crate::traits::{self, TraitEngine};
+use hir::def_id;
```
Comment (cjgillot) [inline compiler/rustc_trait_selection/src/autoderef.rs:4]:
```suggestion
use rustc_span::def_id::LocalDefId;
```

File: compiler/rustc_trait_selection/src/autoderef.rs [hunk 24]
```diff
@@ -28,7 +29,7 @@ pub struct Autoderef<'a, 'tcx> {
     infcx: &'a InferCtxt<'tcx>,
     span: Span,
     overloaded_span: Span,
-    body_id: hir::HirId,
+    body_id: def_id::LocalDefId,
```
Comment (cjgillot) [inline compiler/rustc_trait_selection/src/autoderef.rs:32]:
```suggestion
    body_id: LocalDefId,
```

File: compiler/rustc_trait_selection/src/autoderef.rs [hunk 25]
```diff
@@ -96,7 +97,7 @@ impl<'a, 'tcx> Autoderef<'a, 'tcx> {
     pub fn new(
         infcx: &'a InferCtxt<'tcx>,
         param_env: ty::ParamEnv<'tcx>,
-        body_id: hir::HirId,
+        body_id: def_id::LocalDefId,
```
Comment (cjgillot) [inline compiler/rustc_trait_selection/src/autoderef.rs:100]:
```suggestion
        body_id: LocalDefId,
```

File: compiler/rustc_trait_selection/src/traits/error_reporting/mod.rs [hunk 26]
```diff
@@ -867,6 +860,8 @@ impl<'tcx> TypeErrCtxtExt<'tcx> for TypeErrCtxt<'_, 'tcx> {
                             );
                         }
 
+                        let body_hir =
```
Comment (cjgillot) [inline compiler/rustc_trait_selection/src/traits/error_reporting/mod.rs:863]:
```suggestion
                        let body_hir_id =
```
?

File: compiler/rustc_trait_selection/src/traits/error_reporting/on_unimplemented.rs [hunk 27]
```diff
@@ -126,10 +126,9 @@ impl<'tcx> TypeErrCtxtExt<'tcx> for TypeErrCtxt<'_, 'tcx> {
             .unwrap_or_else(|| (trait_ref.def_id(), trait_ref.skip_binder().substs));
         let trait_ref = trait_ref.skip_binder();
 
-        let mut flags = vec![(
-            sym::ItemContext,
-            self.describe_enclosure(obligation.cause.body_id).map(|s| s.to_owned()),
-        )];
+        let body_hir = self.tcx.hir().local_def_id_to_hir_id(obligation.cause.body_id);
+        let mut flags =
+            vec![(sym::ItemContext, self.describe_enclosure(body_hir).map(|s| s.to_owned()))];
```
Comment (cjgillot) [inline compiler/rustc_trait_selection/src/traits/error_reporting/on_unimplemented.rs:131]: Follow-up: can `describe_enclosure` take a `LocalDefId`?

File: compiler/rustc_trait_selection/src/traits/error_reporting/mod.rs [hunk 28]
```diff
@@ -947,7 +942,7 @@ impl<'tcx> TypeErrCtxtExt<'tcx> for TypeErrCtxt<'_, 'tcx> {
                             if !self.report_similar_impl_candidates(
```
Comment (cjgillot) [inline compiler/rustc_trait_selection/src/traits/error_reporting/mod.rs:942]: Follow-up: can `report_similar_impl_candidates` take a `LocalDefId`?

File: compiler/rustc_trait_selection/src/traits/error_reporting/suggestions.rs [hunk 29]
```diff
@@ -8,7 +8,7 @@ use crate::infer::InferCtxt;
 use crate::traits::normalize_to;
 
 use hir::def::CtorOf;
-use hir::HirId;
+use hir::{def_id, HirId};
```
Comment (cjgillot) [inline compiler/rustc_trait_selection/src/traits/error_reporting/suggestions.rs:11]:
```suggestion
use rustc_span::def_id::LocalDefId;
use hir::HirId;
```

File: compiler/rustc_trait_selection/src/traits/error_reporting/suggestions.rs [hunk 30]
```diff
@@ -175,7 +175,7 @@ pub trait TypeErrCtxtExt<'tcx> {
         err: &mut Diagnostic,
         trait_pred: ty::PolyTraitPredicate<'tcx>,
         associated_item: Option<(&'static str, Ty<'tcx>)>,
-        body_id: hir::HirId,
+        body_id: def_id::LocalDefId,
```
Comment (cjgillot) [inline compiler/rustc_trait_selection/src/traits/error_reporting/suggestions.rs:178]:
```suggestion
        body_id: LocalDefId,
```

File: compiler/rustc_trait_selection/src/traits/error_reporting/suggestions.rs [hunk 31]
```diff
@@ -473,7 +473,7 @@ impl<'tcx> TypeErrCtxtExt<'tcx> for TypeErrCtxt<'_, 'tcx> {
         mut err: &mut Diagnostic,
         trait_pred: ty::PolyTraitPredicate<'tcx>,
         associated_ty: Option<(&'static str, Ty<'tcx>)>,
-        body_id: hir::HirId,
+        body_id: def_id::LocalDefId,
```
Comment (cjgillot) [inline compiler/rustc_trait_selection/src/traits/error_reporting/suggestions.rs:476]:
```suggestion
        body_id: LocalDefId,
```

File: compiler/rustc_trait_selection/src/traits/error_reporting/suggestions.rs [hunk 32]
```diff
@@ -486,7 +486,7 @@ impl<'tcx> TypeErrCtxtExt<'tcx> for TypeErrCtxt<'_, 'tcx> {
 
         // FIXME: Add check for trait bound that is already present, particularly `?Sized` so we
         //        don't suggest `T: Sized + ?Sized`.
-        let mut hir_id = body_id;
+        let mut hir_id = self.tcx.hir().local_def_id_to_hir_id(body_id);
         while let Some(node) = self.tcx.hir().find(hir_id) {
```
Comment (cjgillot) [inline compiler/rustc_trait_selection/src/traits/error_reporting/suggestions.rs:490]:
```suggestion
        while let Some(node) = self.tcx.hir().find_by_def_id(body_id) {
```

File: compiler/rustc_trait_selection/src/traits/mod.rs [hunk 33]
```diff
@@ -157,7 +157,7 @@ pub fn type_known_to_meet_bound_modulo_regions<'tcx>(
         ty::Binder::dummy(ty::TraitRef { def_id, substs: infcx.tcx.mk_substs_trait(ty, &[]) });
     let obligation = Obligation {
         param_env,
-        cause: ObligationCause::misc(span, hir::CRATE_HIR_ID),
+        cause: ObligationCause::misc(span, hir::def_id::CRATE_DEF_ID),
```
Comment (cjgillot) [inline compiler/rustc_trait_selection/src/traits/mod.rs:160]: Could you import `CRATE_DEF_ID`?

File: compiler/rustc_trait_selection/src/traits/wf.rs [hunk 34]
```diff
@@ -1,5 +1,6 @@
 use crate::infer::InferCtxt;
 use crate::traits;
+use hir::def_id;
```
Comment (cjgillot) [inline compiler/rustc_trait_selection/src/traits/wf.rs:3]:
```suggestion
use rustc_span::def_id::LocalDefId;
```

File: compiler/rustc_trait_selection/src/traits/wf.rs [hunk 35]
```diff
@@ -17,7 +18,7 @@ use std::iter;
 pub fn obligations<'tcx>(
     infcx: &InferCtxt<'tcx>,
     param_env: ty::ParamEnv<'tcx>,
-    body_id: hir::HirId,
+    body_id: def_id::LocalDefId,
```
Comment (cjgillot) [inline compiler/rustc_trait_selection/src/traits/wf.rs:21]:
```suggestion
    body_id: LocalDefId,
```

File: compiler/rustc_trait_selection/src/traits/wf.rs [hunk 36]
```diff
@@ -82,7 +83,7 @@ pub fn obligations<'tcx>(
 pub fn trait_obligations<'tcx>(
     infcx: &InferCtxt<'tcx>,
     param_env: ty::ParamEnv<'tcx>,
-    body_id: hir::HirId,
+    body_id: def_id::LocalDefId,
```
Comment (cjgillot) [inline compiler/rustc_trait_selection/src/traits/wf.rs:86]:
```suggestion
    body_id: LocalDefId,
```
qualified `DefId`/`LocalDefId`/`CRATE_DEF_ID` may deserve an internal lint...

File: compiler/rustc_trait_selection/src/traits/wf.rs [hunk 37]
```diff
@@ -105,7 +106,7 @@ pub fn trait_obligations<'tcx>(
 pub fn predicate_obligations<'tcx>(
     infcx: &InferCtxt<'tcx>,
     param_env: ty::ParamEnv<'tcx>,
-    body_id: hir::HirId,
+    body_id: def_id::LocalDefId,
```
Comment (cjgillot) [inline compiler/rustc_trait_selection/src/traits/wf.rs:109]:
```suggestion
    body_id: LocalDefId,
```

File: compiler/rustc_trait_selection/src/traits/wf.rs [hunk 38]
```diff
@@ -166,7 +167,7 @@ pub fn predicate_obligations<'tcx>(
 struct WfPredicates<'tcx> {
     tcx: TyCtxt<'tcx>,
     param_env: ty::ParamEnv<'tcx>,
-    body_id: hir::HirId,
+    body_id: def_id::LocalDefId,
```
Comment (cjgillot) [inline compiler/rustc_trait_selection/src/traits/wf.rs:170]:
```suggestion
    body_id: LocalDefId,
```

File: compiler/rustc_traits/src/type_op.rs [hunk 39]
```diff
@@ -73,7 +73,10 @@ impl<'me, 'tcx> AscribeUserTypeCx<'me, 'tcx> {
     where
         T: TypeFoldable<'tcx>,
     {
-        self.normalize_with_cause(value, ObligationCause::misc(self.span, hir::CRATE_HIR_ID))
+        self.normalize_with_cause(
+            value,
+            ObligationCause::misc(self.span, hir::def_id::CRATE_DEF_ID),
```
Comment (cjgillot) [inline compiler/rustc_traits/src/type_op.rs:78]: Could you import `CRATE_DEF_ID`?

File: compiler/rustc_traits/src/type_op.rs [hunk 40]
```diff
@@ -130,7 +133,7 @@ impl<'me, 'tcx> AscribeUserTypeCx<'me, 'tcx> {
             let span = if self.span == DUMMY_SP { predicate_span } else { self.span };
             let cause = ObligationCause::new(
                 span,
-                hir::CRATE_HIR_ID,
+                hir::def_id::CRATE_DEF_ID,
```
Comment (cjgillot) [inline compiler/rustc_traits/src/type_op.rs:136]: Likewise.

File: compiler/rustc_ty_utils/src/ty.rs [hunk 41]
```diff
@@ -218,9 +218,12 @@ fn param_env(tcx: TyCtxt<'_>, def_id: DefId) -> ty::ParamEnv<'_> {
...
-        Some(id) => id,
-        None if hir_id.is_some() => hir_id.unwrap(),
-        _ => hir::CRATE_HIR_ID,
+        Some(id) => tcx.hir().local_def_id(id),
+        None if hir_id.is_some() => {
+            let id = hir_id.unwrap();
+            tcx.hir().local_def_id(id)
+        }
+        _ => hir::def_id::CRATE_DEF_ID,
     };
```
Comment (cjgillot) [inline compiler/rustc_ty_utils/src/ty.rs:227]: This match changes behaviour.
`local_def_id` will ICE when called on a body id. `local_def_id(body_owned_by(id).hir_id)` is not identity, it's an ICE.
`let body_id = local_id.unwrap_or(CRATE_DEF_ID)` should be enough.

File: compiler/rustc_trait_selection/src/traits/error_reporting/suggestions.rs [hunk 42]
```diff
@@ -1381,7 +1381,8 @@ impl<'tcx> TypeErrCtxtExt<'tcx> for TypeErrCtxt<'_, 'tcx> {
         trait_pred: ty::PolyTraitPredicate<'tcx>,
     ) -> bool {
         let hir = self.tcx.hir();
-        let parent_node = hir.get_parent_node(obligation.cause.body_id);
+        let body_hir = hir.local_def_id_to_hir_id(obligation.cause.body_id);
+        let parent_node = hir.get_parent_node(body_hir);
         let node = hir.find(parent_node);
```
Comment (cjgillot) [inline compiler/rustc_trait_selection/src/traits/error_reporting/suggestions.rs:1386]: The new `body_id: LocalDefId` is typically the parent of the old `body_id: BodyId`, as its `body_owner_def_id`.
Therefore, you should not look at `get_parent_node`, and directly inspect the node at `body_id`.
```suggestion
        let node = hir.find_by_def_id(obligation.cause.body_id);
```

File: compiler/rustc_trait_selection/src/traits/error_reporting/suggestions.rs [hunk 43]
```diff
@@ -1418,7 +1419,8 @@ impl<'tcx> TypeErrCtxtExt<'tcx> for TypeErrCtxt<'_, 'tcx> {
 
     fn return_type_span(&self, obligation: &PredicateObligation<'tcx>) -> Option<Span> {
         let hir = self.tcx.hir();
-        let parent_node = hir.get_parent_node(obligation.cause.body_id);
+        let body_hir = hir.local_def_id_to_hir_id(obligation.cause.body_id);
+        let parent_node = hir.get_parent_node(body_hir);
         let Some(hir::Node::Item(hir::Item { kind: hir::ItemKind::Fn(sig, ..), .. })) = hir.find(parent_node) else {
```
Comment (cjgillot) [inline compiler/rustc_trait_selection/src/traits/error_reporting/suggestions.rs:1424]: Likewise.

File: compiler/rustc_trait_selection/src/traits/error_reporting/suggestions.rs [hunk 44]
```diff
@@ -1443,7 +1445,8 @@ impl<'tcx> TypeErrCtxtExt<'tcx> for TypeErrCtxt<'_, 'tcx> {
         }
 
         let hir = self.tcx.hir();
-        let fn_hir_id = hir.get_parent_node(obligation.cause.body_id);
+        let body_hir = hir.local_def_id_to_hir_id(obligation.cause.body_id);
+        let fn_hir_id = hir.get_parent_node(body_hir);
         let node = hir.find(fn_hir_id);
```
Comment (cjgillot) [inline compiler/rustc_trait_selection/src/traits/error_reporting/suggestions.rs:1450]: Likewise.

File: compiler/rustc_trait_selection/src/traits/error_reporting/suggestions.rs [hunk 45]
```diff
@@ -1655,7 +1659,8 @@ impl<'tcx> TypeErrCtxtExt<'tcx> for TypeErrCtxt<'_, 'tcx> {
         }
 
         let hir = self.tcx.hir();
-        let parent_node = hir.get_parent_node(obligation.cause.body_id);
+        let body_hir = hir.local_def_id_to_hir_id(obligation.cause.body_id);
+        let parent_node = hir.get_parent_node(body_hir);
         let node = hir.find(parent_node);
```
Comment (cjgillot) [inline compiler/rustc_trait_selection/src/traits/error_reporting/suggestions.rs:1664]: Likewise.

File: compiler/rustc_trait_selection/src/traits/error_reporting/suggestions.rs [hunk 46]
```diff
@@ -2955,7 +2960,7 @@ impl<'tcx> TypeErrCtxtExt<'tcx> for TypeErrCtxt<'_, 'tcx> {
         trait_pred: ty::PolyTraitPredicate<'tcx>,
         span: Span,
     ) {
-        let body_hir_id = obligation.cause.body_id;
+        let body_hir_id = self.tcx.hir().local_def_id_to_hir_id(obligation.cause.body_id);
         let item_id = self.tcx.hir().get_parent_node(body_hir_id);
 
         if let Some(body_id) =
```
Comment (cjgillot) [inline compiler/rustc_trait_selection/src/traits/error_reporting/suggestions.rs:2966]: Likewise.

File: compiler/rustc_hir_analysis/src/check/compare_method.rs [hunk 47]
```diff
@@ -1528,15 +1524,15 @@ fn compare_type_predicate_entailment<'tcx>(
...
     {
-        let cause = ObligationCause::misc(span, impl_ty_hir_id);
+        let cause = ObligationCause::misc(span, impl_ty_def_id);
         let traits::Normalized { value: predicate, obligations } =
             traits::normalize(&mut selcx, param_env, cause, predicate);
 
         let cause = ObligationCause::new(
             span,
-            impl_ty_hir_id,
+            impl_ty.def_id.expect_local(),
```
[the remark this answers is not in the document]
Comment (vincenzopalazzo) [reply compiler/rustc_hir_analysis/src/check/compare_method.rs:1533]:
```
    Checking rustc_hir_analysis v0.0.0 (/home/vincent/Github/rust/compiler/rustc_hir_analysis)
error[E0308]: mismatched types
    --> compiler/rustc_hir_analysis/src/check/compare_method.rs:1532:13
     |
1530 |         let cause = ObligationCause::new(
     |                     -------------------- arguments to this function are incorrect
1531 |             span,
1532 |             impl_ty.def_id,
     |             ^^^^^^^^^^^^^^ expected struct `LocalDefId`, found struct `rustc_span::def_id::DefId`
     |
note: associated function defined here
    --> /home/vincent/Github/rust/compiler/rustc_middle/src/traits/mod.rs:122:12
     |
122  |     pub fn new(
     |            ^^^

For more information about this error, try `rustc --explain E0308`.

```

File: compiler/rustc_hir_analysis/src/check/wfcheck.rs [hunk 48]
```diff
@@ -90,13 +90,12 @@ pub(super) fn enter_wf_checking_ctxt<'tcx, F>(
...
 {
     let param_env = tcx.param_env(body_def_id);
-    let body_id = tcx.hir().local_def_id_to_hir_id(body_def_id);
     let infcx = &tcx.infer_ctxt().build();
     let ocx = ObligationCtxt::new(infcx);
 
     let assumed_wf_types = ocx.assumed_wf_types(param_env, span, body_def_id);
 
-    let mut wfcx = WfCheckingCtxt { ocx, span, body_id, param_env };
+    let mut wfcx = WfCheckingCtxt { ocx, span, body_id: body_def_id, param_env };
```
[the remark this answers is not in the document]
Comment (vincenzopalazzo) [reply compiler/rustc_hir_analysis/src/check/wfcheck.rs:99]: I can introduce the renaming in another PR introduced in the body messages of the PR?

File: compiler/rustc_trait_selection/src/traits/error_reporting/mod.rs (hunk 26 above)
Comment (vincenzopalazzo) [reply compiler/rustc_trait_selection/src/traits/error_reporting/mod.rs:872]: make sense!

File: compiler/rustc_trait_selection/src/traits/wf.rs (hunk 36 above)
Comment (vincenzopalazzo) [reply compiler/rustc_trait_selection/src/traits/wf.rs:86]: I did not get your suggestion sorry, can you clarify?

File: compiler/rustc_ty_utils/src/ty.rs (hunk 41 above)
Comment (vincenzopalazzo) [reply compiler/rustc_ty_utils/src/ty.rs:227]: Yeah this was the part of the code where I was not sure

File: compiler/rustc_trait_selection/src/traits/wf.rs (hunk 36 above)
Comment (cjgillot) [reply compiler/rustc_trait_selection/src/traits/wf.rs:86]: I mean: there is an internal lint when someone write 'ty::TyCtxt' instead of just TyCtxt. We could use a similar one around DefId and co. 
(it's just a passing thought, not for this PR)

File: compiler/rustc_ty_utils/src/ty.rs (hunk 41 above)
Comment (vincenzopalazzo) [reply compiler/rustc_ty_utils/src/ty.rs:227]: >let body_id = local_id.unwrap_or(CRATE_DEF_ID) should be enough.

What is `local_id` in this case?

File: compiler/rustc_trait_selection/src/traits/error_reporting/suggestions.rs (hunk 42 above)
Comment (vincenzopalazzo) [reply compiler/rustc_trait_selection/src/traits/error_reporting/suggestions.rs:1386]: Oh, thanks

File: compiler/rustc_trait_selection/src/traits/error_reporting/suggestions.rs (hunk 46 above)
Comment (vincenzopalazzo) [reply compiler/rustc_trait_selection/src/traits/error_reporting/suggestions.rs:2967]: I fixed it with the following diff

```diff
@@ -2961,11 +2958,8 @@ fn suggest_await_before_try(
         trait_pred: ty::PolyTraitPredicate<'tcx>,
         span: Span,
     ) {
-        let body_hir_id = self.tcx.hir().local_def_id_to_hir_id(obligation.cause.body_id);
-        let item_id = self.tcx.hir().get_parent_node(body_hir_id);
-
         if let Some(body_id) =
-            self.tcx.hir().maybe_body_owned_by(self.tcx.hir().local_def_id(item_id))
+            self.tcx.hir().maybe_body_owned_by(obligation.cause.body_id)
         {
             let body = self.tcx.hir().body(body_id);
             if let Some(hir::GeneratorKind::Async(_)) = body.generator_kind {

```

File: compiler/rustc_ty_utils/src/ty.rs (hunk 41 above)
Comment (cjgillot) [reply compiler/rustc_ty_utils/src/ty.rs:226]: The ICE comes from here. I meant `local_did`.

Comment (vincenzopalazzo) [reply compiler/rustc_ty_utils/src/ty.rs]: Sorry, my bad, I push the fix and it works fine thanks or the catch.

Now I found new ICE and try to fix it in the following comment https://github.com/rust-lang/rust/pull/103902/commits/d6c50c0ea26be8dc2f0c90ea58d0a9adb05a77b6 but I think to exit a better solution for this issues?

File: compiler/rustc_hir_typeck/src/fn_ctxt/mod.rs [hunk 49]
```diff
@@ -121,7 +122,7 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
         param_env: ty::ParamEnv<'tcx>,
         body_id: hir::HirId,
     ) -> FnCtxt<'a, 'tcx> {
-        let body_def_id = inh.tcx.hir().local_def_id(body_id);
+        let body_def_id = inh.tcx.hir().opt_local_def_id(body_id).unwrap_or(CRATE_DEF_ID);
```
Comment (lcnr) [inline compiler/rustc_hir_typeck/src/fn_ctxt/mod.rs:125]: the `FnCtxt` should always use a correct `LocalDefId`. Please change `body_id` to already be a `LocalDefId`.

File: compiler/rustc_hir_typeck/src/inherited.rs [hunk 50]
```diff
@@ -190,7 +191,7 @@ impl<'tcx> Inherited<'tcx> {
     where
         T: TypeFoldable<'tcx>,
     {
-        let body_def_id = self.tcx.hir().local_def_id(body_id);
+        let body_def_id = self.tcx.hir().opt_local_def_id(body_id).unwrap_or(CRATE_DEF_ID);
```
Comment (lcnr) [inline compiler/rustc_hir_typeck/src/inherited.rs:194]: Same here, please change `body_id` to already be a `LocalDefId`.

File: compiler/rustc_hir_analysis/src/check/compare_method.rs [hunk 51]
```diff
@@ -414,7 +412,7 @@ fn compare_predicate_entailment<'tcx>(
     let outlives_environment = OutlivesEnvironment::with_bounds(
         param_env,
         Some(infcx),
-        infcx.implied_bounds_tys(param_env, impl_m_hir_id, wf_tys),
+        infcx.implied_bounds_tys(param_env, impl_m.def_id.expect_local(), wf_tys),
```
Comment (lcnr) [inline compiler/rustc_hir_analysis/src/check/compare_method.rs:415]: should also update to always use a local variable `impl_m_def_id` here

File: compiler/rustc_hir_analysis/src/check/compare_method.rs [hunk 52]
```diff
@@ -1730,7 +1722,7 @@ pub fn check_type_bounds<'tcx>(
     let mut selcx = traits::SelectionContext::new(&infcx);
     let normalize_cause = ObligationCause::new(
         impl_ty_span,
-        impl_ty_hir_id,
+        impl_ty.def_id.expect_local(),
```
[the remark this answers is not in the document]
Comment (lcnr) [reply compiler/rustc_hir_analysis/src/check/compare_method.rs:1722]: still relevant

File: compiler/rustc_hir_analysis/src/check/wfcheck.rs (hunk 48 above)
[the remark this answers is not in the document]
Comment (lcnr) [reply compiler/rustc_hir_analysis/src/check/wfcheck.rs:99]: please already do it in this PR

File: compiler/rustc_hir_analysis/src/hir_wf_check.rs [hunk 53]
```diff
@@ -57,7 +58,7 @@ fn diagnostic_hir_wf_check<'tcx>(
         cause: Option<ObligationCause<'tcx>>,
         cause_depth: usize,
         icx: ItemCtxt<'tcx>,
-        hir_id: HirId,
+        hir_id: LocalDefId,
```
Comment (lcnr) [inline compiler/rustc_hir_analysis/src/hir_wf_check.rs:61]: please update the name to `def_id`

File: compiler/rustc_hir_typeck/src/_match.rs [hunk 54]
```diff
@@ -186,10 +186,10 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
         prior_arm: Option<(Option<hir::HirId>, Ty<'tcx>, Span)>,
     ) {
         let hir = self.tcx.hir();
-
+        let body_hir = hir.local_def_id_to_hir_id(self.body_id);
         // First, check that we're actually in the tail of a function.
         let hir::Node::Expr(hir::Expr { kind: hir::ExprKind::Block(block, _), .. }) =
-            hir.get(self.body_id) else { return; };
+            hir.get(body_hir) else { return; };
```
Comment (lcnr) [inline compiler/rustc_hir_typeck/src/_match.rs:192]:
```suggestion
            hir.get_by_def_id(self.body_id) else { return; };
```

File: compiler/rustc_hir_typeck/src/closure.rs [hunk 55]
```diff
@@ -734,10 +734,11 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
 
         // async fn that have opaque types in their return type need to redo the conversion to inference variables
         // as they fetch the still opaque version from the signature.
+        let body_def_id = self.tcx.hir().local_def_id(body_id);
```
Comment (lcnr) [inline compiler/rustc_hir_typeck/src/closure.rs:737]: please propagate the change outwards, changing the argument `body_id` to `LocalDefId`

File: compiler/rustc_hir_typeck/src/expr.rs [hunk 56]
```diff
@@ -856,7 +856,8 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
         return_expr_ty: Ty<'tcx>,
     ) {
         // Don't point at the whole block if it's empty
-        if span == self.tcx.hir().span(self.body_id) {
+        let body_hir_id = self.tcx.hir().local_def_id_to_hir_id(self.body_id);
+        if span == self.tcx.hir().span(body_hir_id) {
```
Comment (lcnr) [inline compiler/rustc_hir_typeck/src/expr.rs:860]:
```suggestion
        if span == self.tcx.def_span(self.body_id) {
```

File: compiler/rustc_hir_typeck/src/expr.rs [hunk 57]
```diff
@@ -2497,7 +2500,8 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
     }
 
     fn point_at_param_definition(&self, err: &mut Diagnostic, param: ty::ParamTy) {
-        let generics = self.tcx.generics_of(self.body_id.owner.to_def_id());
+        let body_hir_id = self.tcx.hir().local_def_id_to_hir_id(self.body_id);
+        let generics = self.tcx.generics_of(body_hir_id.owner.to_def_id());
```
Comment (lcnr) [inline compiler/rustc_hir_typeck/src/expr.rs:2504]:
```suggestion
        let generics = self.tcx.generics_of(self.body_id);
```
this previous code looks wrong. We shouldn't use the `HirId` owner to get the generics.

File: compiler/rustc_hir_typeck/src/fn_ctxt/_impl.rs [hunk 58]
```diff
@@ -373,7 +373,8 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
     where
         T: TypeFoldable<'tcx>,
     {
-        self.inh.normalize_associated_types_in(span, self.body_id, self.param_env, value)
+        let hir_id = self.tcx.hir().local_def_id_to_hir_id(self.body_id);
+        self.inh.normalize_associated_types_in(span, hir_id, self.param_env, value)
```
Comment (lcnr) [inline compiler/rustc_hir_typeck/src/fn_ctxt/_impl.rs:377]: `normalize_associated_types_in` should use a `LocalDefId` instead of a `HirId`

File: compiler/rustc_hir_typeck/src/fn_ctxt/checks.rs [hunk 59]
```diff
@@ -2090,10 +2090,11 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
             && let Some(callee_ty) = callee_ty
         {
             let callee_ty = callee_ty.peel_refs();
+            let hir_id = self.tcx.hir().local_def_id_to_hir_id(self.body_id);
             match *callee_ty.kind() {
                 ty::Param(param) => {
                     let param =
-                        self.tcx.generics_of(self.body_id.owner).type_param(&param, self.tcx);
+                        self.tcx.generics_of(hir_id.owner).type_param(&param, self.tcx);
```
Comment (lcnr) [inline compiler/rustc_hir_typeck/src/fn_ctxt/checks.rs:2097]: `generics_of(hir_id.owner)` isn't right as the owner of a `HirId` is not the innermost context of the `hir_id`. Directly use `self.tcx.generics_of(self.body_id)` here

File: compiler/rustc_hir_typeck/src/fn_ctxt/checks.rs [hunk 60]
```diff
@@ -2102,7 +2103,7 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
                         // and point at that.
                         let instantiated = self
                             .tcx
-                            .explicit_predicates_of(self.body_id.owner)
+                            .explicit_predicates_of(hir_id.owner)
```
Comment (lcnr) [inline compiler/rustc_hir_typeck/src/fn_ctxt/checks.rs:2106]:
```suggestion
                            .explicit_predicates_of(self.body_id)
```

File: compiler/rustc_hir_typeck/src/fn_ctxt/mod.rs [hunk 61]
```diff
@@ -60,7 +61,7 @@ pub struct FnCtxt<'a, 'tcx> {
     /// expressions. If `None`, this is in a context where return is
     /// inappropriate, such as a const expression.
     ///
-    /// This is a `RefCell<DynamicCoerceMany>`, which means that we
+    /// This is a `RefCell<DynamicCoerceM,any>`, which means that we
```
Comment (lcnr) [inline compiler/rustc_hir_typeck/src/fn_ctxt/mod.rs:64]:
```suggestion
    /// This is a `RefCell<DynamicCoerceMany>`, which means that we
```

File: compiler/rustc_hir_typeck/src/fn_ctxt/mod.rs [hunk 62]
```diff
@@ -182,7 +184,7 @@ impl<'a, 'tcx> AstConv<'tcx> for FnCtxt<'a, 'tcx> {
     }
 
     fn item_def_id(&self) -> DefId {
-        self.body_id.owner.to_def_id()
+        self.tcx.hir().local_def_id_to_hir_id(self.body_id).owner.to_def_id()
```
Comment (lcnr) [inline compiler/rustc_hir_typeck/src/fn_ctxt/mod.rs:187]:
```suggestion
        self.body_id.to_def_id()
```

File: compiler/rustc_hir_typeck/src/fn_ctxt/suggestions.rs [hunk 63]
```diff
@@ -206,8 +207,9 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
                     })
                 }
                 ty::Param(param) => {
-                    let def_id = self.tcx.generics_of(self.body_id.owner).type_param(&param, self.tcx).def_id;
-                    self.tcx.predicates_of(self.body_id.owner).predicates.iter().find_map(|(pred, _)| {
+                    let body_id = self.tcx.hir().local_def_id_to_hir_id(self.body_id);
+                    let def_id = self.tcx.generics_of(body_id.owner).type_param(&param, self.tcx).def_id;
+                    self.tcx.predicates_of(body_id.owner).predicates.iter().find_map(|(pred, _)| {
```
Comment (lcnr) [inline compiler/rustc_hir_typeck/src/fn_ctxt/suggestions.rs:212]: again, you can directly use `self.body_id` here instead of using the `HirId` owner

File: compiler/rustc_hir_typeck/src/method/mod.rs [hunk 64]
```diff
@@ -332,8 +332,8 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
 
         // Construct an obligation
         let poly_trait_ref = ty::Binder::dummy(trait_ref);
-        let output_ty = expected.only_has_type(self).and_then(|ty| (!ty.needs_infer()).then(|| ty));
 
+        let output_ty = expected.only_has_type(self).and_then(|ty| (!ty.needs_infer()).then(|| ty));
```
Comment (lcnr) [inline compiler/rustc_hir_typeck/src/method/mod.rs:336]: unrelated change?

File: compiler/rustc_hir_typeck/src/method/suggest.rs [hunk 65]
```diff
@@ -347,11 +347,11 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
...
                 }
-
+                let body_hir = self.tcx.hir().local_def_id_to_hir_id(self.body_id);
                 let ty_span = match actual.kind() {
-                    ty::Param(param_type) => Some(
-                        param_type.span_from_generics(self.tcx, self.body_id.owner.to_def_id()),
-                    ),
+                    ty::Param(param_type) => {
+                        Some(param_type.span_from_generics(self.tcx, body_hir.owner.to_def_id()))
+                    }
```
Comment (lcnr) [inline compiler/rustc_hir_typeck/src/method/suggest.rs:354]: same here, use `self.body_id` directly instead of going through the `HirId` owner

File: compiler/rustc_hir_typeck/src/method/suggest.rs [hunk 66]
```diff
@@ -2191,7 +2189,8 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
             };
             // Obtain the span for `param` and use it for a structured suggestion.
             if let Some(param) = param_type {
-                let generics = self.tcx.generics_of(self.body_id.owner.to_def_id());
+                let hir_id = self.tcx.hir().local_def_id_to_hir_id(self.body_id);
+                let generics = self.tcx.generics_of(hir_id.owner.to_def_id());
```
Comment (lcnr) [inline compiler/rustc_hir_typeck/src/method/suggest.rs:2193]: same here `generics_of(self.body_id)`

File: compiler/rustc_infer/src/infer/error_reporting/mod.rs [hunk 67]
```diff
@@ -1918,14 +1918,7 @@ impl<'tcx> TypeErrCtxt<'_, 'tcx> {
...
 
-        // In some (most?) cases cause.body_id points to actual body, but in some cases
-        // it's an actual definition. According to the comments (e.g. in
-        // rustc_hir_analysis/check/compare_method.rs:compare_predicate_entailment) the latter
-        // is relied upon by some other code. This might (or might not) need cleanup.
-        let body_owner_def_id =
-            self.tcx.hir().opt_local_def_id(cause.body_id).unwrap_or_else(|| {
-                self.tcx.hir().body_owner_def_id(hir::BodyId { hir_id: cause.body_id })
-            });
+        let body_owner_def_id = cause.body_id;
```
Comment (lcnr) [inline compiler/rustc_infer/src/infer/error_reporting/mod.rs:1921]: can you instead replace all uses of this variable with `cause.body_id`?

File: compiler/rustc_lint/src/builtin.rs [hunk 68]
```diff
@@ -755,11 +755,12 @@ impl<'tcx> LateLintPass<'tcx> for MissingCopyImplementations {
         if ty.is_copy_modulo_regions(cx.tcx, param_env) {
             return;
         }
+        let item_hir = item.owner_id.def_id;
```
Comment (lcnr) [inline compiler/rustc_lint/src/builtin.rs:758]: weird variable name, maybe `item_def_id` or just inline `item.owner_id.def_id`

File: compiler/rustc_hir_typeck/src/fn_ctxt/mod.rs (hunk 49 above)
Comment (vincenzopalazzo) [reply compiler/rustc_hir_typeck/src/fn_ctxt/mod.rs:125]: Yes I was just discussing with @cjgillot regarding a ICE, and I found my code a little bit messy

File: compiler/rustc_hir_typeck/src/method/mod.rs (hunk 64 above)
Comment (vincenzopalazzo) [reply compiler/rustc_hir_typeck/src/method/mod.rs:336]: github diff shout is wrong? it is the same code

File: compiler/rustc_hir_typeck/src/check.rs [hunk 69]
```diff
@@ -32,18 +33,20 @@ pub(super) fn check_fn<'a, 'tcx>(
 ) -> (FnCtxt<'a, 'tcx>, Option<GeneratorTypes<'tcx>>) {
     // Create the function context. This is either derived from scratch or,
     // in the case of closures, based on the outer context.
-    let mut fcx = FnCtxt::new(inherited, param_env, body.value.hir_id);
+    let def_id = inherited.tcx.hir().opt_local_def_id(body.value.hir_id).unwrap_or(CRATE_DEF_ID);
```
Comment (cjgillot) [inline compiler/rustc_hir_typeck/src/check.rs:36]: This is wrong. A body's `HirId` never has a `LocalDefId`, so this line always returns `CRATE_DEF_ID`, which is not whar we want. (Uses of `opt_local_def_id` are almost always wrong.)

```suggestion
    let def_id = inherited.tcx.hir().body_owner_def_id(body.id());
```

File: compiler/rustc_hir_typeck/src/fn_ctxt/suggestions.rs [hunk 70]
```diff
@@ -23,10 +23,11 @@ use rustc_trait_selection::traits::query::evaluate_obligation::InferCtxtExt as _
 
 impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
     pub(crate) fn body_fn_sig(&self) -> Option<ty::FnSig<'tcx>> {
+        let body_hir = self.tcx.hir().local_def_id_to_hir_id(self.body_id);
         self.typeck_results
             .borrow()
             .liberated_fn_sigs()
-            .get(self.tcx.hir().get_parent_node(self.body_id))
+            .get(self.tcx.hir().get_parent_node(body_hir))
```
Comment (cjgillot) [inline compiler/rustc_hir_typeck/src/fn_ctxt/suggestions.rs:30]:
```suggestion
            .get(body_hir)
```
New `self.body_id` is already one level higher than the former one.

File: compiler/rustc_hir_typeck/src/closure.rs [hunk 71]
```diff
@@ -632,8 +633,10 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
                 // function.
                 Some(hir::GeneratorKind::Async(hir::AsyncGeneratorKind::Fn)) => {
                     debug!("closure is async fn body");
-                    self.deduce_future_output_from_obligations(expr_def_id, body.id().hir_id)
-                        .unwrap_or_else(|| {
+                    let def_id =
+                        self.tcx.hir().opt_local_def_id(body.id().hir_id).unwrap_or(CRATE_DEF_ID);
```
Comment (cjgillot) [inline compiler/rustc_hir_typeck/src/closure.rs:637]:
```suggestion
                        self.tcx.hir().body_owner_def_id(body.id());
```
I think that value is actually the same as `expr_def_id` (which is always local btw).

File: compiler/rustc_hir_typeck/src/closure.rs [hunk 72]
```diff
@@ -832,9 +836,10 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
         bound_sig: ty::PolyFnSig<'tcx>,
     ) -> ClosureSignatures<'tcx> {
         let liberated_sig = self.tcx().liberate_late_bound_regions(expr_def_id, bound_sig);
+        let def_id = self.tcx.hir().opt_local_def_id(body.value.hir_id).unwrap_or(CRATE_DEF_ID);
```
Comment (cjgillot) [inline compiler/rustc_hir_typeck/src/closure.rs:839]:
```suggestion
        let def_id = self.tcx.hir().body_owner_def_id(body.id());
```
Likewise, this value should be equal to `expr_def_id.expect_owner()`.

File: compiler/rustc_hir_typeck/src/expr.rs [hunk 73]
```diff
@@ -1365,7 +1366,8 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
         let body = self.tcx.hir().body(anon_const.body);
 
         // Create a new function context.
-        let fcx = FnCtxt::new(self, self.param_env.with_const(), body.value.hir_id);
+        let def_id = self.tcx.hir().opt_local_def_id(body.value.hir_id).unwrap_or(CRATE_DEF_ID);
```
Comment (cjgillot) [inline compiler/rustc_hir_typeck/src/expr.rs:1369]:
```suggestion
        let def_id = self.tcx.hir().body_owner_def_id(body.id());
```
OR
```suggestion
        let def_id = self.tcx.hir().local_def_id(anon_const.hir_id);
```

File: compiler/rustc_hir_typeck/src/lib.rs [hunk 74]
```diff
@@ -235,25 +236,25 @@ fn typeck_with_fallback<'tcx>(
         let param_env = tcx.param_env(def_id);
         let mut fcx = if let Some(hir::FnSig { header, decl, .. }) = fn_sig {
             let fn_sig = if rustc_hir_analysis::collect::get_infer_ret_ty(&decl.output).is_some() {
-                let fcx = FnCtxt::new(&inh, param_env, body.value.hir_id);
+                let def_id =
+                    inh.tcx.hir().opt_local_def_id(body.value.hir_id).unwrap_or(CRATE_DEF_ID);
```
Comment (cjgillot) [inline compiler/rustc_hir_typeck/src/lib.rs:240]: The `def_id` from the outer scope is the better value here: `body` is already the body owned by `def_id`.

File: compiler/rustc_hir_typeck/src/lib.rs [hunk 75]
```diff
@@ -235,25 +236,25 @@ fn typeck_with_fallback<'tcx>(
...
+                let fcx = FnCtxt::new(&inh, param_env, def_id);
                 <dyn AstConv<'_>>::ty_of_fn(&fcx, id, header.unsafety, header.abi, decl, None, None)
             } else {
                 tcx.fn_sig(def_id)
             };
 
             check_abi(tcx, id, span, fn_sig.abi());
 
+            let def_id = inh.tcx.hir().opt_local_def_id(body.value.hir_id).unwrap_or(CRATE_DEF_ID);
```
Comment (cjgillot) [inline compiler/rustc_hir_typeck/src/lib.rs:249]: Likewise.

File: compiler/rustc_hir_typeck/src/lib.rs [hunk 76]
```diff
@@ -235,25 +236,25 @@ fn typeck_with_fallback<'tcx>(
...
-                body_id.hir_id,
-                param_env,
-                fn_sig,
-            );
+            let fn_sig =
+                inh.normalize_associated_types_in(body.value.span, def_id, param_env, fn_sig);
             check_fn(&inh, param_env, fn_sig, decl, id, body, None).0
         } else {
-            let fcx = FnCtxt::new(&inh, param_env, body.value.hir_id);
+            let def_id = inh.tcx.hir().opt_local_def_id(body.value.hir_id).unwrap_or(CRATE_DEF_ID);
```
Comment (cjgillot) [inline compiler/rustc_hir_typeck/src/lib.rs:256]: Likewise.

File: compiler/rustc_hir_analysis/src/check/compare_method.rs [hunk 77]
```diff
@@ -439,7 +437,7 @@ pub fn collect_trait_impl_trait_tys<'tcx>(
     let return_span = tcx.hir().fn_decl_by_hir_id(impl_m_hir_id).unwrap().output.span();
     let cause = ObligationCause::new(
         return_span,
-        impl_m_hir_id,
+        impl_m.def_id.expect_local(),
```
Comment (cjgillot) [inline compiler/rustc_hir_analysis/src/check/compare_method.rs:440]: Nit: this deserves to be a local variable.

File: compiler/rustc_hir_analysis/src/lib.rs [hunk 78]
```diff
@@ -183,16 +184,15 @@ fn check_main_fn_ty(tcx: TyCtxt<'_>, main_def_id: DefId) {
     let main_fnsig = tcx.fn_sig(main_def_id);
     let main_span = tcx.def_span(main_def_id);
 
-    fn main_fn_diagnostics_hir_id(tcx: TyCtxt<'_>, def_id: DefId, sp: Span) -> hir::HirId {
+    fn main_fn_diagnostics_def_id(tcx: TyCtxt<'_>, def_id: DefId, sp: Span) -> def_id::LocalDefId {
```
Comment (cjgillot) [inline compiler/rustc_hir_analysis/src/lib.rs:187]:
```suggestion
    fn main_fn_diagnostics_def_id(tcx: TyCtxt<'_>, def_id: DefId, sp: Span) -> LocalDefId {
```

File: compiler/rustc_hir_analysis/src/lib.rs [hunk 79]
```diff
@@ -97,10 +97,11 @@ mod outlives;
 pub mod structured_errors;
 mod variance;
 
+use hir::def_id;
 use rustc_errors::{struct_span_err, ErrorGuaranteed};
 use rustc_hir as hir;
-use rustc_hir::def_id::DefId;
-use rustc_hir::{Node, CRATE_HIR_ID};
+use rustc_hir::def_id::{DefId, CRATE_DEF_ID};
```
Comment (cjgillot) [inline compiler/rustc_hir_analysis/src/lib.rs:103]:
```suggestion
use rustc_hir::def_id::{DefId, LocalDefId, CRATE_DEF_ID};
```

File: compiler/rustc_hir_typeck/src/_match.rs [hunk 80]
```diff
@@ -198,7 +197,7 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
 
         // Next, make sure that we have no type expectation.
         let Some(ret) = hir
-            .find_by_def_id(self.body_id.owner.def_id)
+            .find_by_def_id(self.body_id)
```
Comment (cjgillot) [inline compiler/rustc_hir_typeck/src/_match.rs:200]: There is something fishy here: we cannot have both `get_by_def_id(self.body_id)` a `Node::Expr(ExprKind::Block)` and `find_by_def_id(self.body_id) = Some(get_by_def_id(self.body_id))` have a `fn_decl`.

File: compiler/rustc_hir_typeck/src/expr.rs [hunk 81]
```diff
@@ -2111,13 +2113,14 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
         variant: &'tcx ty::VariantDef,
         access_span: Span,
     ) -> Vec<Symbol> {
+        let body_def_id = self.tcx.hir().local_def_id_to_hir_id(self.body_id);
```
Comment (cjgillot) [inline compiler/rustc_hir_typeck/src/expr.rs:2116]: The naming is a bit off here. `body_owner_hir_id`?

File: compiler/rustc_hir_typeck/src/lib.rs [hunk 82]
```diff
@@ -47,6 +47,7 @@ mod writeback;
 pub use diverges::Diverges;
 pub use expectation::Expectation;
 pub use fn_ctxt::*;
+use hir::def_id::CRATE_DEF_ID;
```
Comment (cjgillot) [inline compiler/rustc_hir_typeck/src/lib.rs:50]: This belongs with imports from other crates.
```suggestion
use rustc_hir::def_id::CRATE_DEF_ID;
```

File: compiler/rustc_trait_selection/src/traits/mod.rs [hunk 83]
```diff
@@ -165,7 +165,7 @@ pub fn type_known_to_meet_bound_modulo_regions<'tcx>(
         // We can use a dummy node-id here because we won't pay any mind
         // to region obligations that arise (there shouldn't really be any
         // anyhow).
-        let cause = ObligationCause::misc(span, hir::CRATE_HIR_ID);
+        let cause = ObligationCause::misc(span, hir::def_id::CRATE_DEF_ID);
```
Comment (cjgillot) [inline compiler/rustc_trait_selection/src/traits/mod.rs:168]:
```suggestion
        let cause = ObligationCause::misc(span, CRATE_DEF_ID);
```

File: compiler/rustc_traits/src/type_op.rs [hunk 84]
```diff
@@ -130,7 +130,7 @@ impl<'me, 'tcx> AscribeUserTypeCx<'me, 'tcx> {
...
```
Comment (cjgillot) [inline compiler/rustc_traits/src/type_op.rs:133]:
```suggestion
                CRATE_DEF_ID,
```

File: compiler/rustc_hir_typeck/src/check.rs (hunk 69 above)
Comment (vincenzopalazzo) [reply compiler/rustc_hir_typeck/src/check.rs:36]: Mh, I was thinking that this was too simple, I ca know why the body does not have the `LocalDefId`?

Comment (cjgillot) [reply compiler/rustc_hir_typeck/src/check.rs:36]: For instance, the `LocalDefId` identifies the function item, which is a `hir::Item`. That item *contains* a `BodyId`.
The `BodyId` points to a `Body` which wraps a `Expr` (the indirection is there to help incremental compilation, when looking at HIR of the function signature only).
By convention, the `HirId` inside the `BodyId` is the `HirId` of the `Expr` (`Body::value` is an `Expr`, and you may have seen `body.value.hir_id` plenty of times).

Likewise for closures: the closure *itself* has both a `HirId` and a `LocalDefId`, but the returned expression is the one with the `BodyId`.

This also explains the naming for `body_owner_def_id`: we go one level higher (hence the "owner") when going from the `BodyId` to the `LocalDefId`.

I've been wanting to make `BodyId` store the `LocalDefId` of the function instead, but putting off that work. Your PR will make that significantly easier.

File: compiler/rustc_hir_typeck/src/expr.rs (hunk 81 above)
Comment (vincenzopalazzo) [reply compiler/rustc_hir_typeck/src/expr.rs:2116]: yep

File: compiler/rustc_hir_typeck/src/_match.rs (hunk 80 above)
Comment (vincenzopalazzo) [reply compiler/rustc_hir_typeck/src/_match.rs:200]: Mh, I can not catch what is the possible solution here?

File: compiler/rustc_mir_build/src/thir/pattern/const_to_pat.rs [hunk 85]
```diff
@@ -226,10 +226,11 @@ impl<'tcx> ConstToPat<'tcx> {
         // using `PartialEq::eq` in this scenario in the past.)
         let partial_eq_trait_id =
             self.tcx().require_lang_item(hir::LangItem::PartialEq, Some(self.span));
+        let def_id = self.tcx().hir().local_def_id(self.id);
```
Comment (vincenzopalazzo) [inline compiler/rustc_mir_build/src/thir/pattern/const_to_pat.rs:229]: This is causing to me some problems, and I do not think I should use the body id here? the const should have a LocalDefId most of the time right?

```diff
+++ b/compiler/rustc_mir_build/src/thir/pattern/const_to_pat.rs
@@ -1,3 +1,4 @@
+use hir::def_id::CRATE_DEF_ID;
 use rustc_errors::DelayDm;
 use rustc_hir as hir;
 use rustc_index::vec::Idx;
@@ -226,7 +227,7 @@ fn type_may_have_partial_eq_impl(&self, ty: Ty<'tcx>) -> bool {
         // using `PartialEq::eq` in this scenario in the past.)
         let partial_eq_trait_id =
             self.tcx().require_lang_item(hir::LangItem::PartialEq, Some(self.span));
-        let def_id = self.tcx().hir().local_def_id(self.id);
+        let def_id = self.tcx().hir().opt_local_def_id(self.id).unwrap_or(CRATE_DEF_ID);
         let obligation: PredicateObligation<'_> = predicate_for_trait_def(
             self.tcx(),
             self.param_env,

```

**Comment by cjgillot** [comment]
This should fix https://github.com/rust-lang/rust/issues/104827. Could you add a test when you come back to this PR?

**Comment by vincenzopalazzo** [comment]
>This should fix https://github.com/rust-lang/rust/issues/104827. Could you add a test when you come back to this PR?

Yes, I try to do it by the end of the next week!

File: compiler/rustc_trait_selection/src/traits/error_reporting/suggestions.rs [hunk 86]
```diff
@@ -486,8 +487,8 @@ impl<'tcx> TypeErrCtxtExt<'tcx> for TypeErrCtxt<'_, 'tcx> {
 
         // FIXME: Add check for trait bound that is already present, particularly `?Sized` so we
         //        don't suggest `T: Sized + ?Sized`.
-        let mut hir_id = body_id;
-        while let Some(node) = self.tcx.hir().find(hir_id) {
+        let mut hir_id = self.tcx.hir().local_def_id_to_hir_id(body_id);
+        while let Some(node) = self.tcx.hir().find_by_def_id(body_id) {
```
Comment (compiler-errors) [inline compiler/rustc_trait_selection/src/traits/error_reporting/suggestions.rs:491]: this will loop forever

**Review by compiler-errors — CHANGES_REQUESTED** [review]

File: compiler/rustc_trait_selection/src/traits/error_reporting/suggestions.rs (hunk 86 above)
Comment (compiler-errors) [reply compiler/rustc_trait_selection/src/traits/error_reporting/suggestions.rs:491]: you need to remove `mut hir_id`, and then at the bottom of the loop reassign `body_id = tcx.local_parent(body_id);` instead so you're actually going up the def id tree.

Comment (vincenzopalazzo) [reply compiler/rustc_trait_selection/src/traits/error_reporting/suggestions.rs:491]: I think you mean the following refactoring?

```rust
while let Some(node) = self.tcx.local_parent(body_id) {
```

Comment (compiler-errors) [reply compiler/rustc_trait_selection/src/traits/error_reporting/suggestions.rs:491]: No, you still need `while let Some(node) = self.tcx.hir().find_by_def_id(body_id) { .. }`.

Line 669 will become:

`body_id = self.tcx.local_parent(body_id);`

And you will delete 490, and make `body_id` on 477 mutable.

Comment (vincenzopalazzo) [reply compiler/rustc_trait_selection/src/traits/error_reporting/suggestions.rs:491]: Ah, ok I think I get it, this while looks stau stuck because the `body_id` never change! thanks to catch it.

However, I did not understand this

>  instead so you're actually going up the def id tree.

Comment (vincenzopalazzo) [reply compiler/rustc_trait_selection/src/traits/error_reporting/suggestions.rs:491]: I think this diff make sense

```diff
diff --git a/compiler/rustc_trait_selection/src/traits/error_reporting/suggestions.rs b/compiler/rustc_trait_selection/src/traits/error_reporting/suggestions.rs
index 4c77537a0a5..0ada543b731 100644
--- a/compiler/rustc_trait_selection/src/traits/error_reporting/suggestions.rs
+++ b/compiler/rustc_trait_selection/src/traits/error_reporting/suggestions.rs
@@ -487,8 +487,9 @@ fn suggest_restricting_param_bound(
 
         // FIXME: Add check for trait bound that is already present, particularly `?Sized` so we
         //        don't suggest `T: Sized + ?Sized`.
-        let mut hir_id = self.tcx.hir().local_def_id_to_hir_id(body_id);
+        let mut body_id = body_id;
         while let Some(node) = self.tcx.hir().find_by_def_id(body_id) {
+            let hir_id = self.tcx.hir().local_def_id_to_hir_id(body_id);
             match node {
                 hir::Node::Item(hir::Item {
                     ident,
@@ -665,8 +666,7 @@ fn suggest_restricting_param_bound(
 
                 _ => {}
             }
-
-            hir_id = self.tcx.hir().get_parent_item(hir_id).into();
+           body_id = self.tcx.local_parent(body_id);
         }
     }

```

**Comment by cjgillot** [comment]
@vincenzopalazzo could you rebase that PR, so we can get it merged?
Thanks for all this work!

**Comment by cjgillot** [comment]
Looks like you accidentally deleted Cargo.lock.

**Comment by vincenzopalazzo** [comment]
>Looks like you accidentally deleted Cargo.lock.

Yeah the rebase was painful, I'm on it, but before the PR need some hammer with the new version of the master

File: compiler/rustc_trait_selection/src/traits/error_reporting/suggestions.rs [hunk 87]
```diff
@@ -1059,7 +1060,7 @@ impl<'tcx> TypeErrCtxtExt<'tcx> for TypeErrCtxt<'_, 'tcx> {
     ) -> bool {
         let self_ty = self.resolve_vars_if_possible(trait_pred.self_ty());
         let ty = self.tcx.erase_late_bound_regions(self_ty);
-        let owner = self.tcx.hir().get_parent_item(obligation.cause.body_id);
+        let owner = self.tcx.hir().get_parent_item_by_def_id(obligation.cause.body_id);
```
Comment (cjgillot) [inline compiler/rustc_trait_selection/src/traits/error_reporting/suggestions.rs:1063]:
```suggestion
        let owner = self.tcx.hir().get_by_def_id(obligation.cause.body_id);
```

File: compiler/rustc_trait_selection/src/traits/error_reporting/suggestions.rs [hunk 88]
```diff
@@ -1731,8 +1731,8 @@ impl<'tcx> TypeErrCtxtExt<'tcx> for TypeErrCtxt<'_, 'tcx> {
         }
 
         let hir = self.tcx.hir();
-        let fn_hir_id = hir.parent_id(obligation.cause.body_id);
-        let node = hir.find(fn_hir_id);
+        let fn_hir_id = hir.parent_id_by_def_id(obligation.cause.body_id);
```
Comment (cjgillot) [inline compiler/rustc_trait_selection/src/traits/error_reporting/suggestions.rs:1734]:
```suggestion
        let fn_hir_id = hir.local_def_id_to_hir_id(obligation.cause.body_id);
```

File: compiler/rustc_trait_selection/src/traits/mod.rs [hunk 89]
```diff
@@ -163,12 +162,6 @@ fn pred_known_to_hold_modulo_regions<'tcx>(
     debug!(?result);
 
     if result && has_non_region_infer {
-        // Because of inference "guessing", selection can sometimes claim
-        // to succeed while the success requires a guess. To ensure
-        // this function's result remains infallible, we must confirm
-        // that guess. While imperfect, I believe this is sound.
-
-        // FIXME(@lcnr): this function doesn't seem right.
```
Comment (cjgillot) [inline compiler/rustc_trait_selection/src/traits/mod.rs:171]: This comment should stay.

Comment (vincenzopalazzo) [reply compiler/rustc_trait_selection/src/traits/mod.rs:171]: Sorry rebasing mistake!

File: compiler/rustc_trait_selection/src/traits/error_reporting/suggestions.rs (hunk 87 above)
Comment (vincenzopalazzo) [reply compiler/rustc_trait_selection/src/traits/error_reporting/suggestions.rs:1063]: I think this could be simplified as 

```diff
@@ -1060,8 +1061,7 @@ fn suggest_add_clone_to_arg(
     ) -> bool {
         let self_ty = self.resolve_vars_if_possible(trait_pred.self_ty());
         let ty = self.tcx.erase_late_bound_regions(self_ty);
-        let owner = self.tcx.hir().get_parent_item_by_def_id(obligation.cause.body_id);
-        let Some(generics) = self.tcx.hir().get_generics(owner.def_id) else { return false };
+        let Some(generics) = self.tcx.hir().get_generics(obligation.cause.body_id) else { return false };
         let ty::Ref(_, inner_ty, hir::Mutability::Not) = ty.kind() else { return false };
         let ty::Param(param) = inner_ty.kind() else { return false };
         let ObligationCauseCode::FunctionArgumentObligation { arg_hir_id, .. } = obligation.cause.code() else { return false };
@@ -1731,7 +1731,7 @@ fn suggest_impl_trait(
         }

```

**Comment by vincenzopalazzo** [comment]
Ok I only have one question regarding the following change that I made

```diff
@@ -1706,8 +1706,7 @@ fn suggest_semicolon_removal(
 
     fn return_type_span(&self, obligation: &PredicateObligation<'tcx>) -> Option<Span> {
         let hir = self.tcx.hir();
-        let parent_node = hir.parent_id_by_def_id(obligation.cause.body_id);
-        let Some(hir::Node::Item(hir::Item { kind: hir::ItemKind::Fn(sig, ..), .. })) = hir.find(parent_node) else {
+        let Some(hir::Node::Item(hir::Item { kind: hir::ItemKind::Fn(sig, ..), .. })) = hir.find_by_def_id(obligation.cause.body_id) else {
             return None;
         };

```

File: compiler/rustc_hir_analysis/src/collect.rs [hunk 90]
```diff
@@ -1247,11 +1247,12 @@ fn infer_return_ty_for_fn_sig<'tcx>(
     }
 }
 
+// FIXME(vincenzopalazzo): remove the hir item when the refactoring is stable
 fn suggest_impl_trait<'tcx>(
     tcx: TyCtxt<'tcx>,
     ret_ty: Ty<'tcx>,
     span: Span,
-    hir_id: hir::HirId,
+    _hir_id: hir::HirId,
```
[the remark this answers is not in the document]
Comment (vincenzopalazzo) [reply compiler/rustc_hir_analysis/src/collect.rs:1255]: Yeah but I think this deserve a separate commit

File: compiler/rustc_hir_analysis/src/check/wfcheck.rs [hunk 91]
```diff
@@ -701,10 +700,11 @@ fn resolve_regions_with_wf_tys<'tcx>(
     // region constraints get added and solved there and we need to test each
     // call individually.
     let infcx = tcx.infer_ctxt().build();
+    let id_def_id = tcx.hir().local_def_id(id);
```
[the remark this answers is not in the document]
Comment (vincenzopalazzo) [reply compiler/rustc_hir_analysis/src/check/wfcheck.rs]: Done! sorry I missed it

File: compiler/rustc_hir_typeck/src/closure.rs [hunk 92]
```diff
@@ -80,7 +80,8 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
 
         debug!(?bound_sig, ?liberated_sig);
 
-        let mut fcx = FnCtxt::new(self, self.param_env.without_const(), body.value.hir_id);
+        let body_def_id = self.tcx.hir().local_def_id(body.value.hir_id);
+        let mut fcx = FnCtxt::new(self, self.param_env.without_const(), body_def_id);
```
Comment (vincenzopalazzo) [inline compiler/rustc_hir_typeck/src/closure.rs:84]: looks like that this will ICE

File: compiler/rustc_hir_typeck/src/_match.rs (hunk 80 above)
Comment (oli-obk) [reply compiler/rustc_hir_typeck/src/_match.rs:200]: You'll probably want to do 
```suggestion
            .find_by_def_id(self.tcx.parent(self.body_id))
```

As I think the `DefId` parent should be the same item we were looking for before?

File: compiler/rustc_hir_typeck/src/check.rs [hunk 93]
```diff
@@ -34,16 +34,16 @@ pub(super) fn check_fn<'a, 'tcx>(
     can_be_generator: Option<hir::Movability>,
 ) -> Option<GeneratorTypes<'tcx>> {
     let fn_id = fcx.tcx.hir().local_def_id_to_hir_id(fn_def_id);
-
     let tcx = fcx.tcx;
     let hir = tcx.hir();
 
     let declared_ret_ty = fn_sig.output();
 
+    let body_def_id = tcx.hir().body_owner_def_id(body.id());
```
Comment (oli-obk) [inline compiler/rustc_hir_typeck/src/check.rs:42]: isn't that just the `fn_def_id`?

File: compiler/rustc_hir_typeck/src/closure.rs (hunk 92 above)
Comment (oli-obk) [reply compiler/rustc_hir_typeck/src/closure.rs:84]: I think you'll want to use `closure.def_id` here?

File: compiler/rustc_hir_analysis/src/check/wfcheck.rs [hunk 94]
```diff
@@ -460,20 +462,28 @@ fn check_gat_where_clauses(tcx: TyCtxt<'_>, associated_items: &[hir::TraitItemRe
         debug!(?required_bounds);
         let param_env = tcx.param_env(gat_def_id);
         let gat_hir = gat_item_hir.hir_id();
+        let gat_defid = tcx.hir().local_def_id(gat_hir);
```
Comment (oli-obk) [inline compiler/rustc_hir_analysis/src/check/wfcheck.rs:465]: There's already a `gat_def_id.def_id` available

File: compiler/rustc_hir_analysis/src/check/wfcheck.rs [hunk 95]
```diff
@@ -583,9 +593,10 @@ fn gather_gat_bounds<'tcx, T: TypeFoldable<'tcx>>(
         // relationship to the type arguments (e.g., `Self`). If there is an
         // outlives relationship (`Self: 'a`), then we want to ensure that is
         // reflected in a where clause on the GAT itself.
+        let item_def_id = tcx.hir().local_def_id(item_hir);
```
Comment (oli-obk) [inline compiler/rustc_hir_analysis/src/check/wfcheck.rs:596]: Change the `item_hir` argument to a `DefId`, it is only used here.

File: compiler/rustc_hir_typeck/src/expr.rs [hunk 96]
```diff
@@ -1374,7 +1374,8 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
         let body = self.tcx.hir().body(anon_const.body);
 
         // Create a new function context.
-        let fcx = FnCtxt::new(self, self.param_env.with_const(), body.value.hir_id);
+        let def_id = self.tcx.hir().body_owner_def_id(body.id());
```
Comment (oli-obk) [inline compiler/rustc_hir_typeck/src/expr.rs:1377]: `AnonConst` has a `def_id` field, use that instead

File: compiler/rustc_hir_typeck/src/expr.rs (hunk 81 above)
Comment (oli-obk) [reply compiler/rustc_hir_typeck/src/expr.rs:2155]: This hasn't been addressed

File: compiler/rustc_hir_typeck/src/expr.rs [hunk 97]
```diff
@@ -2199,8 +2201,9 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
             match deref_base_ty.kind() {
                 ty::Adt(base_def, substs) if !base_def.is_enum() => {
                     debug!("struct named {:?}", deref_base_ty);
+                    let body_hir_id = self.tcx.hir().local_def_id_to_hir_id(self.body_id);
                     let (ident, def_scope) =
-                        self.tcx.adjust_ident_and_get_scope(field, base_def.did(), self.body_id);
+                        self.tcx.adjust_ident_and_get_scope(field, base_def.did(), body_hir_id);
```
Comment (oli-obk) [inline compiler/rustc_hir_typeck/src/expr.rs:2206]: Pass in a `DefId` and use `parent_module_from_def_id` instead of `parent_module` inside

File: compiler/rustc_hir_typeck/src/fn_ctxt/suggestions.rs [hunk 98]
```diff
@@ -164,7 +164,8 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
         &self,
         ty: Ty<'tcx>,
     ) -> Option<(DefIdOrName, Ty<'tcx>, Vec<Ty<'tcx>>)> {
-        self.err_ctxt().extract_callable_info(self.body_id, self.param_env, ty)
+        let body_hir_id = self.tcx.hir().local_def_id_to_hir_id(self.body_id);
+        self.err_ctxt().extract_callable_info(body_hir_id, self.param_env, ty)
```
Comment (oli-obk) [inline compiler/rustc_hir_typeck/src/fn_ctxt/suggestions.rs:168]: Pass in the `DefId` directly, the `HirId` is only used to get a `DefId`

File: compiler/rustc_hir_typeck/src/method/suggest.rs [hunk 99]
```diff
@@ -352,7 +352,8 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
 
         let ty_span = match rcvr_ty.kind() {
             ty::Param(param_type) => {
-                Some(param_type.span_from_generics(self.tcx, self.body_id.owner.to_def_id()))
+                let body_hir_id = self.tcx.hir().local_def_id_to_hir_id(self.body_id);
+                Some(param_type.span_from_generics(self.tcx, body_hir_id.owner.to_def_id()))
```
Comment (oli-obk) [inline compiler/rustc_hir_typeck/src/method/suggest.rs:356]:
```suggestion
                Some(param_type.span_from_generics(self.tcx, self.body_id))
```

File: compiler/rustc_hir_typeck/src/closure.rs (hunk 92 above)
Comment (vincenzopalazzo) [reply compiler/rustc_hir_typeck/src/closure.rs:84]: Oh nice, yeah this should work!

File: compiler/rustc_middle/src/hir/map/mod.rs [hunk 100]
```diff
@@ -757,6 +757,11 @@ impl<'hir> Map<'hir> {
         }
     }
 
+    pub fn get_parent_item_by_def_id(self, def_id: LocalDefId) -> OwnerId {
+        let hir = self.tcx.hir().local_def_id_to_hir_id(def_id);
+        self.get_parent_item(hir)
+    }
```
Comment (oli-obk) [inline compiler/rustc_middle/src/hir/map/mod.rs:763]: Does this differ from `self.tcx.parent(def_id)`?

File: compiler/rustc_trait_selection/src/traits/error_reporting/ambiguity.rs [hunk 101]
```diff
@@ -80,8 +80,8 @@ pub fn recompute_applicable_impls<'tcx>(
         },
     );
 
-    let predicates =
-        tcx.predicates_of(obligation.cause.body_id.owner.to_def_id()).instantiate_identity(tcx);
+    let body_hir = tcx.hir().local_def_id_to_hir_id(obligation.cause.body_id);
+    let predicates = tcx.predicates_of(body_hir.owner.to_def_id()).instantiate_identity(tcx);
```
Comment (oli-obk) [inline compiler/rustc_trait_selection/src/traits/error_reporting/ambiguity.rs:84]:
```suggestion
    let predicates = tcx.predicates_of(obligation.cause.body_id.to_def_id()).instantiate_identity(tcx);
```

File: compiler/rustc_trait_selection/src/traits/error_reporting/suggestions.rs [hunk 102]
```diff
@@ -1805,7 +1804,8 @@ impl<'tcx> TypeErrCtxtExt<'tcx> for TypeErrCtxt<'_, 'tcx> {
 
         match liberated_sig.output().kind() {
             ty::Dynamic(predicates, _, ty::Dyn) => {
-                let cause = ObligationCause::misc(ret_ty.span, fn_hir_id);
+                let fn_def_id = self.tcx.hir().local_def_id(fn_hir_id);
+                let cause = ObligationCause::misc(ret_ty.span, fn_def_id);
```
Comment (oli-obk) [inline compiler/rustc_trait_selection/src/traits/error_reporting/suggestions.rs:1808]:
```suggestion
                let cause = ObligationCause::misc(ret_ty.span, obligation.cause.body_id);
```

**Review by oli-obk — CHANGES_REQUESTED** [review]
I guess some of these changes can come in a follow up PR...

**Comment by oli-obk** [comment]
You need to clear your changes to `Cargo.lock`, I don't think this PR needs any of them

File: compiler/rustc_middle/src/hir/map/mod.rs (hunk 100 above)
Comment (vincenzopalazzo) [reply compiler/rustc_middle/src/hir/map/mod.rs:763]: I do not think so, I removed the method in a folloup commit

File: compiler/rustc_hir_typeck/src/method/suggest.rs (hunk 99 above)
Comment (vincenzopalazzo) [reply compiler/rustc_hir_typeck/src/method/suggest.rs:356]:
```
   Compiling rustc_hir_typeck v0.1.0 (/home/vincent/Github/rust/compiler/rustc_hir_typeck)
error[E0308]: mismatched types
    --> compiler/rustc_hir_typeck/src/method/suggest.rs:355:62
     |
355  |                 Some(param_type.span_from_generics(self.tcx, self.body_id))
     |                                 ------------------           ^^^^^^^^^^^^ expected struct `rustc_span::def_id::DefId`, found struct `LocalDefId`
     |                                 |
     |                                 arguments to this function are incorrect
     |
note: associated function defined here
    --> /home/vincent/Github/rust/compiler/rustc_middle/src/ty/sty.rs:1316:12
     |
1316 |     pub fn span_from_generics(&self, tcx: TyCtxt<'tcx>, item_with_generics: DefId) -> Span {
     |            ^^^^^^^^^^^^^^^^^^
help: call `Into::into` on this expression to convert `LocalDefId` into `rustc_span::def_id::DefId`
     |
355  |                 Some(param_type.span_from_generics(self.tcx, self.body_id.into()))

```

I was not able to get what is the say way to pass from LocalDefId to a DefId

**Comment by vincenzopalazzo** [comment]
>I guess some of these changes can come in a follow-up PR...

Yeah what I want to do in a follow-up PR or commit is introduce the change in the method signature, I had a couple of simplifications that can be done, but I do not want to mix the kind of change inside the same commit

>You need to clear your changes to Cargo.lock, I don't think this PR needs any of them

Mh! it looks like Cargo generate two kind of lock file, wondering why we need it at all inside the compiler?

**Comment by vincenzopalazzo** [comment]
Ok separate the in separate commit that need a squash when the PR is stable, and I was thinking to open a v2 of the patch!

**Comment by oli-obk** [comment]
Please squash so we can land it before it bitrots again

@bors p=5

File: compiler/rustc_hir_typeck/src/method/suggest.rs (hunk 99 above)
Comment (oli-obk) [reply compiler/rustc_hir_typeck/src/method/suggest.rs:356]: There's a `to_def_id` method on `LocalDefId`

**Comment by vincenzopalazzo** [comment]
Done @oli-obk !

File: compiler/rustc_middle/src/hir/map/mod.rs (hunk 100 above)
Comment (oli-obk) [reply compiler/rustc_middle/src/hir/map/mod.rs:763]: it's still here

**Comment by oli-obk** [comment]
https://github.com/rust-lang/rust/blob/d12412c90fbd974b1cf886e42a95c850d9ee45a1/src/tools/compiletest/src/runtest.rs#L1933-L1938 and https://github.com/rust-lang/rust/pull/103902?notification_referrer_id=NT_kwDOAAURBLE0NzQzNzA2ODkxOjMzMjAzNg#discussion_r1071093014 left, then we can land it

**Comment by oli-obk** [comment]
There seem to be a few ICEs in ui tests

File: compiler/rustc_hir_analysis/src/check/compare_impl_item.rs [hunk 103]
```diff
@@ -167,10 +167,10 @@ fn compare_method_predicate_entailment<'tcx>(
     //
     // FIXME(@lcnr): remove that after removing `cause.body_id` from
     // obligations.
-    let impl_m_hir_id = tcx.hir().local_def_id_to_hir_id(impl_m.def_id.expect_local());
+    let impl_m_def_id = impl_m.def_id.expect_local();
     let cause = ObligationCause::new(
         impl_m_span,
-        impl_m_hir_id,
+        impl_m.def_id.expect_local(),
```
Comment (deltragon) [inline compiler/rustc_hir_analysis/src/check/compare_impl_item.rs:173]:
```suggestion
        impl_m_def_id,
```

File: compiler/rustc_hir_analysis/src/check/compare_impl_item.rs [hunk 104]
```diff
@@ -167,10 +167,10 @@ fn compare_method_predicate_entailment<'tcx>(
...
         ObligationCauseCode::CompareImplItemObligation {
             impl_item_def_id: impl_m.def_id.expect_local(),
```
Comment (deltragon) [inline compiler/rustc_hir_analysis/src/check/compare_impl_item.rs:175]:
```suggestion
            impl_item_def_id: impl_m_def_id,
```

Comment (deltragon) [reply compiler/rustc_hir_analysis/src/check/compare_impl_item.rs:175]: There's some more occurrences further down as well.

File: compiler/rustc_hir_typeck/src/_match.rs (hunk 80 above)
Comment (vincenzopalazzo) [reply compiler/rustc_hir_typeck/src/_match.rs:200]: ok, so after deep thinking on this PR and after talking with some people, I think this is what we need!

```diff
+++ b/compiler/rustc_hir_typeck/src/_match.rs
@@ -197,7 +197,7 @@ fn suggest_removing_semicolon_for_coerce(
 
         // Next, make sure that we have no type expectation.
         let Some(ret) = hir
-            .find_by_def_id(self.body_id)
+            .find_by_def_id(self.tcx.hir().body_owned_by(self.body_id).def_id)
             .and_then(|owner| owner.fn_decl())
             .map(|decl| decl.output.span()) else { return; };
         let Expectation::IsLast(stmt) = expectation else {
```

File: compiler/rustc_trait_selection/src/traits/error_reporting/mod.rs (hunk 28 above)
Comment (vincenzopalazzo) [reply compiler/rustc_trait_selection/src/traits/error_reporting/mod.rs:1009]: yep, added a fixme to include it in a folloup PR

File: compiler/rustc_hir_typeck/src/method/suggest.rs [hunk 105]
```diff
@@ -1593,7 +1593,8 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
                 else { return };
 
         let map = self.infcx.tcx.hir();
-        let body = map.body(rustc_hir::BodyId { hir_id: self.body_id });
+        let body_hir = self.tcx.hir().local_def_id_to_hir_id(self.body_id);
+        let body = map.body(rustc_hir::BodyId { hir_id: body_hir });
```
[the remark this answers is not in the document]
Comment (cjgillot) [reply compiler/rustc_hir_typeck/src/method/suggest.rs:1595]: `tcx.hir().body_owner_by` should do it.

File: compiler/rustc_trait_selection/src/traits/error_reporting/suggestions.rs [hunk 106]
```diff
@@ -3727,9 +3721,14 @@ impl<'tcx> TypeErrCtxtExt<'tcx> for TypeErrCtxt<'_, 'tcx> {
                     term: ty_var.into(),
                 },
             )));
+            let body_def_id = self.tcx.hir().local_def_id(body_id);
```
Comment (cjgillot) [inline compiler/rustc_trait_selection/src/traits/error_reporting/suggestions.rs:3724]:
```suggestion
            let body_def_id = self.tcx.hir().enclosing_body_owner(body_id);
```
?

File: compiler/rustc_trait_selection/src/traits/error_reporting/suggestions.rs [hunk 107]
```diff
@@ -1429,7 +1431,7 @@ impl<'tcx> TypeErrCtxtExt<'tcx> for TypeErrCtxt<'_, 'tcx> {
             span.remove_mark();
         }
         let mut expr_finder = super::FindExprBySpan::new(span);
-        let Some(hir::Node::Expr(body)) = self.tcx.hir().find(obligation.cause.body_id) else {
+        let Some(hir::Node::Expr(body)) = self.tcx.hir().find_by_def_id(obligation.cause.body_id) else {
             return false;
         };
         expr_finder.visit_expr(&body);
```
Comment (cjgillot) [inline compiler/rustc_trait_selection/src/traits/error_reporting/suggestions.rs:1437]:
```suggestion
        let Some(body_id) = self.tcx.hir().maybe_body_owned_by(obligation.cause.body_id) else {
            return false;
        };
        let body = self.tcx.hir().body(body_id);
        expr_finder.visit_expr(body.value);
```

File: compiler/rustc_trait_selection/src/traits/error_reporting/suggestions.rs [hunk 108]
```diff
@@ -1004,7 +1006,7 @@ impl<'tcx> TypeErrCtxtExt<'tcx> for TypeErrCtxt<'_, 'tcx> {
             span.remove_mark();
         }
         let mut expr_finder = FindExprBySpan::new(span);
-        let Some(hir::Node::Expr(body)) = self.tcx.hir().find(obligation.cause.body_id) else { return; };
+        let Some(hir::Node::Expr(body)) = self.tcx.hir().find_by_def_id(obligation.cause.body_id) else { return; };
         expr_finder.visit_expr(&body);
```
Comment (cjgillot) [inline compiler/rustc_trait_selection/src/traits/error_reporting/suggestions.rs:1010]:
```suggestion
        let Some(body_id) = self.tcx.hir().maybe_body_owned_by(obligation.cause.body_id) else { return; };
        let body = self.tcx.hir().body(body_id);
        expr_finder.visit_expr(body.value);
```

File: compiler/rustc_hir_typeck/src/method/suggest.rs [hunk 109]
```diff
@@ -496,8 +495,7 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
                             ty::Param(_) => {
                                 // Account for `fn` items like in `issue-35677.rs` to
                                 // suggest restricting its type params.
-                                let parent_body =
-                                    hir.body_owner(hir::BodyId { hir_id: self.body_id });
+                                let parent_body = hir.body_owned_by(self.body_id).hir_id;
                                 Some(hir.get(parent_body))
```
Comment (cjgillot) [inline compiler/rustc_hir_typeck/src/method/suggest.rs:499]:
```suggestion
                                Some(hir.get_by_def_id(self.body_id))
```

File: compiler/rustc_hir_typeck/src/expr.rs [hunk 110]
```diff
@@ -864,7 +864,7 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
         return_expr_ty: Ty<'tcx>,
     ) {
         // Don't point at the whole block if it's empty
-        if span == self.tcx.hir().span(self.body_id) {
+        if span == self.tcx.def_span(self.body_id) {
```
Comment (cjgillot) [inline compiler/rustc_hir_typeck/src/expr.rs:867]: The RHS should be `return_expr.span` from `check_return_expr`.

File: compiler/rustc_trait_selection/src/traits/error_reporting/suggestions.rs (hunk 106 above)
Comment (vincenzopalazzo) [reply compiler/rustc_trait_selection/src/traits/error_reporting/suggestions.rs:3727]: That sounds good thanks! I think this is the method that I need to call in each of the `local_def_id` usage to have the same  behavior or always

File: compiler/rustc_trait_selection/src/traits/error_reporting/suggestions.rs (hunk 107 above)
Comment (vincenzopalazzo) [reply compiler/rustc_trait_selection/src/traits/error_reporting/suggestions.rs]: yeah, I think we need also to keep the check of `Some(hir::Node::Expr(body))` but I had this change in my local history, thanks!

File: compiler/rustc_hir_typeck/src/method/suggest.rs (hunk 109 above)
Comment (vincenzopalazzo) [reply compiler/rustc_hir_typeck/src/method/suggest.rs:499]: mh maybe I'm, missing something here but we do not need to access the parent before? and then find the node?

**Comment by oli-obk** [comment]
You still got ICEs in tests. Please check the backtrace to see if the call stack is near something you changed

File: compiler/rustc_trait_selection/src/traits/error_reporting/suggestions.rs (hunk 107 above)
Comment (vincenzopalazzo) [reply compiler/rustc_trait_selection/src/traits/error_reporting/suggestions.rs]: No i'm wrong, sorry I did not full think about your refactoring, you are right! thanks!

**Comment by vincenzopalazzo** [comment]
Ok rebased and open a new clean PR https://github.com/rust-lang/rust/pull/107218 for easy review, thanks for the support that you give me in understand the HIR

File: compiler/rustc_hir_analysis/src/check/compare_impl_item.rs (hunk 104 above)
Comment (oli-obk) [reply compiler/rustc_hir_analysis/src/check/compare_impl_item.rs:155]: this is still unaddressed

Comment (oli-obk) [reply compiler/rustc_hir_analysis/src/check/compare_impl_item.rs:155]: this is still unaddressed

File: compiler/rustc_hir_typeck/src/_match.rs (hunk 80 above)
Comment (oli-obk) [reply compiler/rustc_hir_typeck/src/_match.rs:201]: this is still unaddressed

File: compiler/rustc_hir_typeck/src/method/suggest.rs [hunk 111]
```diff
@@ -496,9 +495,10 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
                             ty::Param(_) => {
                                 // Account for `fn` items like in `issue-35677.rs` to
                                 // suggest restricting its type params.
-                                let parent_body =
-                                    hir.body_owner(hir::BodyId { hir_id: self.body_id });
-                                Some(hir.get(parent_body))
+                                // FIXME(vincenzopalazzo): this sounds right?
+                                // or we need to get before the body owned by the
+                                // def id?
```
Comment (oli-obk) [inline compiler/rustc_hir_typeck/src/method/suggest.rs:500]: no this looks right to me, can remove the fixme

File: compiler/rustc_lint/src/for_loops_over_fallibles.rs [hunk 112]
```diff
@@ -139,9 +139,10 @@ fn suggest_question_mark<'tcx>(
 
     let ty = substs.type_at(0);
     let infcx = cx.tcx.infer_ctxt().build();
+    let body_def_id = cx.tcx.hir().body_owner_def_id(body_id);
```
Comment (oli-obk) [inline compiler/rustc_lint/src/for_loops_over_fallibles.rs:142]: seems okayish, but we may want to look into changing `enclosing_body` in the future

**Review by oli-obk — CHANGES_REQUESTED** [review]

File: compiler/rustc_hir_typeck/src/_match.rs (hunk 80 above)
Comment (vincenzopalazzo) [reply compiler/rustc_hir_typeck/src/_match.rs:201]: Sorry forget to apply!

File: compiler/rustc_lint/src/for_loops_over_fallibles.rs (hunk 112 above)
Comment (vincenzopalazzo) [reply compiler/rustc_lint/src/for_loops_over_fallibles.rs:142]: yes, I had this on my todo list for the followup PR this week!

File: compiler/rustc_hir_typeck/src/_match.rs (hunk 80 above)
Comment (vincenzopalazzo) [reply compiler/rustc_hir_typeck/src/_match.rs:201]: Ah no, I did not forget, but I reverted it.

This is the cause of the following UI failure `tests/ui/suggestions/match-with-different-arm-types-as-stmt-instead-of-expr.rs`

```

------------------------------------------
diff of stderr:

22	   |
23	   = note: expected struct `Box<Baz>`
24	              found struct `Box<Bar>`
-	note: you might have meant to return the `match` expression
-	  --> $DIR/match-with-different-arm-types-as-stmt-instead-of-expr.rs:27:6
-	   |
-	LL |   fn wrong(c: &str) -> Box<dyn Foo> {
-	   |                        ------------ the `match` arms can conform to this return type
-	LL | /     match c {
-	LL | |         "baz" => Box::new(Baz),
-	LL | |         _ => Box::new(Bar),
-	LL | |     };
-	   | |     -^ the `match` is a statement because of this semicolon, consider removing it
-	   | |_____|
-	   |       this could be implicitly returned but it is a statement, not a tail expression
37	
38	error[E0308]: mismatched types
39	  --> $DIR/match-with-different-arm-types-as-stmt-instead-of-expr.rs:23:22

```

Comment (vincenzopalazzo) [reply compiler/rustc_hir_typeck/src/_match.rs:201]: maybe there is another place where to fix this error?

Comment (oli-obk) [reply compiler/rustc_hir_typeck/src/_match.rs:201]: ah nevermind, you changed the logic above this piece and I just didn't check the comment properly. This is resolved now. This specific `find_by_def_id` was correct, but at the time when this comment was written the `hir.maybe_body_owned_by(self.body_id)` was something else still

**Comment by oli-obk** [comment]
lgtm now. Please squash the commits as they do not seem to be independent.

**Comment by vincenzopalazzo** [comment]
>lgtm now. Please squash the commits as they do not seem to be independent.

ah, I squashed the wrong branch!
