### PR TITLE
derive(SmartPointer): register helper attributes

### LINKED ISSUE #128888: regression: `pointee` is ambiguous
- https://crater-reports.s3.amazonaws.com/beta-1.81-2/beta-2024-07-26/reg/ptr_meta-0.3.0-alpha.2/log.txt
- https://crater-reports.s3.amazonaws.com/beta-1.81-2/beta-2024-07-26/reg/rancor-0.1.0-alpha.9/log.txt

```
[INFO] [stdout] error[E0659]: `pointee` is ambiguous
[INFO] [stdout]    --> src/lib.rs:546:11
[INFO] [stdout]     |
[INFO] [stdout] 546 |         #[pointee]
[INFO] [stdout]     |           ^^^^^^^ ambiguous name
[INFO] [stdout]     |
[INFO] [stdout]     = note: ambiguous because of a name conflict with a builtin attribute
[INFO] [stdout]     = note: `pointee` could refer to a built-in attribute
```

#125575 cc @davidtwco @dingxiangfei2009

### PR DESCRIPTION
**Pull request by dingxiangfei2009**
Fix #128888 

This PR enables built-in macros to register helper attributes, if any, to support correct name resolution in the correct lexical scope under the macros.

Also, `#[pointee]` is moved into the scope under `derive(SmartPointer)`.

cc @Darksonn @davidtwco

### CODE REVIEW

File: compiler/rustc_builtin_macros/src/lib.rs [hunk 1]
```diff
@@ -66,8 +67,16 @@ pub fn register_builtin_macros(resolver: &mut dyn ResolverExpand) {
...
         $(register(sym::$name, SyntaxExtensionKind::LegacyAttr(Box::new($f)));)*
     }
-    macro register_derive($($name:ident: $f:expr,)*) {
-        $(register(sym::$name, SyntaxExtensionKind::LegacyDerive(Box::new(BuiltinDerive($f))));)*
+    macro_rules! register_derive {
+        ($name:ident: $f:expr, $($rest:tt)*) => {
+            register(sym::$name, SyntaxExtensionKind::LegacyDerive(Box::new(BuiltinDerive($f)), smallvec![]));
+            register_derive!($($rest)*);
+        };
+        ($name:ident[$($attr:ident),+]: $f:expr, $($rest:tt)*) => {
```
Comment (compiler-errors) [inline compiler/rustc_builtin_macros/src/lib.rs:75]: Can we make this syntax a bit more explicit?

```suggestion
        ($name:ident(attrs = [$($attr:ident),+]): $f:expr, $($rest:tt)*) => {
```

so then you write 

```
register! {
  SmartPointer(attrs = [pointee]): ..
}
```

**Review by compiler-errors — CHANGES_REQUESTED** [review]
This needs a test

**Comment by dingxiangfei2009** [comment]
Yeah working on a test now

**Comment by Darksonn** [comment]
This may also implicitly fix https://github.com/rust-lang/rust/issues/128485

File: compiler/rustc_builtin_macros/src/lib.rs (hunk 1 above)
Comment (dingxiangfei2009) [reply compiler/rustc_builtin_macros/src/lib.rs]: Surely. Applied.

**Review by compiler-errors — COMMENTED** [review]
Can you add a test showing what happens when you have `#[pointee]` without `#[derive(SmartPointer)]`?

**Comment by dingxiangfei2009** [comment]
> How does the `derive(Default)` register the `#[default]` attribute?

Ah it registered that with `#[rustc_builtin_macro(..)]` attribute. Now it is much cleaner.

**Review by compiler-errors — APPROVED** [review]

**Comment by dingxiangfei2009** [comment]
Another test was added but I think it is optional. I just found that the test was convered by the Default macro test suite.

**Comment by apiraino** [comment]
Beta backport accepted as per compiler team [on Zulip](https://rust-lang.zulipchat.com/#narrow/stream/238009-t-compiler.2Fmeetings/topic/.5Bweekly.5D.202024-08-15/near/462563380). A backport PR will be authored by the release team at the end of the current development cycle.

@rustbot label +beta-accepted
