### PR TITLE
Fixes #58586: Make E0505 erronous example fail for the 2018 edition

### LINKED ISSUE #58586: compiler error E0505 example compiles with 2018 edition
Taken from [https://doc.rust-lang.org](https://doc.rust-lang.org/error-index.html#E0505)
[Erroneous code compiles fine for E0505](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=5bf27b44da06b2b181d41c0c7eec98fc)

A possible way to [trigger E0505 in the 2018 edition](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=93372135deaafc1f1e74982b664d5d3d)

Rust version 1.32 on playground

### PR DESCRIPTION
**Pull request by gurgalex**
The original example worked for 2015, but not the 2018 edition of Rust.

Borrowing the moved value after ownership is transferred seems required for 2018.

[this](https://github.com/rust-lang/rust/compare/rust-lang:f66e469...gurgalex:b2a02c8#diff-4ca866aea4a6efecd732f1975faaad88R1564) line though is correct for 2018, but not for the 2015 edition.

Fix #58586

### CODE REVIEW

File: src/librustc_mir/diagnostics.rs [hunk 1]
```diff
@@ -1545,20 +1545,24 @@ Erroneous code example:
...
+
 fn eat(val: Value) {}
 
 fn main() {
     let x = Value{};
     {
         let _ref_to_val: &Value = &x;
         eat(x);
+        borrow(_ref_to_val);
     }
```
Comment (matthewjasper) [inline src/librustc_mir/diagnostics.rs]: Can you remove this set of braces from all of the examples?

File: src/librustc_mir/diagnostics.rs [hunk 2]
```diff
@@ -1585,12 +1592,15 @@ Or:
...
+fn borrow(val: &Value) {}
+
 fn eat(val: Value) {}
 
 fn main() {
     let x = Value{};
     {
         let _ref_to_val: &Value = &x;
+        borrow(_ref_to_val);
     }
```
Comment (gurgalex) [inline src/librustc_mir/diagnostics.rs]: Should I keep this set of braces in?
It is one way to resolve the error.

Comment (matthewjasper) [reply src/librustc_mir/diagnostics.rs]: Sorry, I forgot that we still have AST borrow check on the 2015 edition. Keep them for now.

Comment (gurgalex) [reply src/librustc_mir/diagnostics.rs]: I can remove the braces from all the examples except this one, and they give the expected results for both 2015 and 2018.

erroneous: Fails
Take by ref: Passes
Implement Copy: Passes

Comment (matthewjasper) [reply src/librustc_mir/diagnostics.rs]: Ok, it's fine like this for now.

File: src/librustc_mir/diagnostics.rs [hunk 3]
```diff
@@ -1545,20 +1545,22 @@ Erroneous code example:
 ```compile_fail,E0505
 struct Value {}
```
Comment (hellow554) [inline src/librustc_mir/diagnostics.rs]: Is there an opinion for `struct Value {}` over `struct Value;`?

Comment (gurgalex) [reply src/librustc_mir/diagnostics.rs]: Didn't know that an empty struct could be made like that.

I'd want to keep the `{}` so that the reader doesn't have to guess that the struct has no fields.
