### PR TITLE
Simple modification of `non_lifetime_binders`'s diagnostic information to adapt to type binders

### LINKED ISSUE #119067: `non_lifetime_binders` falsely recognizes (and rejects) trait as lifetime
minimal repro:
```rust
#![allow(incomplete_features)]
#![feature(non_lifetime_binders)]

trait MyTrait1 {}

trait MyTrait2
    where for <T: MyTrait1> ():
{
    
}
```

output:
```
error: lifetime bounds cannot be used in this context
 --> src/lib.rs:7:19
  |
7 |     where for <T: MyTrait1> ():
  |                   ^^^^^^^^
```

use case:
> [[playground]](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=cf6cb68a291cd0982dd00d021df0c0f3) 
> weird example, i know. its difficult to construct a proper example that isn't overly complex

workaround:
> add the bound to all call sites that require it (e.g. add `where Human: Consume<Food>` to `foo()` in the above example)

rustc:
> 1.76.0-nightly (2023-12-17 6a62871320e262661bb1)

### PR DESCRIPTION
**Pull request by surechen**
fixes #119067

Replace diagnostic information "lifetime bounds cannot be used in this context" to "bounds cannot be used in this context".

```rust
#![allow(incomplete_features)]
#![feature(non_lifetime_binders)]

trait Trait {}

trait Trait2
    where for <T: Trait> ():{}
//~^ ERROR bounds cannot be used in this context
```

### CODE REVIEW

File: tests/ui/traits/non_lifetime_binders/non-lifetime-binders-issue-119067.rs [hunk 1]
```diff
@@ -0,0 +1,18 @@
...
+#![feature(closure_lifetime_binder)]
+
+trait Trait {}
+
+trait Trait2
+    where for <T: Trait> ():{}
+//~^ ERROR bounds cannot be used in this context
+
+fn main() {
+    let _ = for<T: Trait> || {};
```
Comment (fmease) [inline tests/ui/traits/non_lifetime_binders/non-lifetime-binders-issue-119067.rs:14]:
```suggestion
    let _ = for<T: Trait> -> () || {};
```

This way, you can suppress *implicit types are not allowed …* error.

File: compiler/rustc_ast_passes/src/feature_gate.rs [hunk 2]
```diff
@@ -152,8 +152,7 @@ impl<'a> PostExpansionVisitor<'a> {
     }
 
     fn check_late_bound_lifetime_defs(&self, params: &[ast::GenericParam]) {
-        // Check only lifetime parameters are present and that the lifetime
-        // parameters that are present have no bounds.
+        // Check parameters that are present have no bounds.
```
Comment (fmease) [inline compiler/rustc_ast_passes/src/feature_gate.rs:155]:
```suggestion
        // Check parameters that are present have no bounds.
```

```suggestion
        // Check only lifetime parameters are present and that the generic parameters have no bounds.
```

We should keep the first comment since we're still making sure that only lifetime parameters are present.

**Review by fmease — CHANGES_REQUESTED** [review]
Thanks! I have one nit and one suggestion. After that, it's good to go. Lastly, could you update the PR title to something more descriptive? It's pretty general right now.
r? fmease

File: tests/ui/traits/non_lifetime_binders/non-lifetime-binders-issue-119067.rs [hunk 3]
```diff
@@ -0,0 +1,18 @@
+// check-fail
+
+#![allow(incomplete_features)]
+#![feature(non_lifetime_binders)]
+#![feature(closure_lifetime_binder)]
+
+trait Trait {}
+
+trait Trait2
+    where for <T: Trait> ():{}
```
Comment (fmease) [inline tests/ui/traits/non_lifetime_binders/non-lifetime-binders-issue-119067.rs:10]:
```suggestion
trait Trait2
where
    for<T: Trait> ():,
{
}
```

(formatting)

File: tests/ui/traits/non_lifetime_binders/non-lifetime-binders-issue-119067.rs
Comment (fmease) [inline tests/ui/traits/non_lifetime_binders/non-lifetime-binders-issue-119067.rs:1]: I think it would be better to split this test file or move it somewhere else since it not only contains `non_lifetime_binders` but also `closure_lifetime_binder` (tests for the latter are usually placed in `tests/ui/closures/binder`).

Also the name of this test isn't super descriptive, maybe call it `trait-bounds-on-type-binders.rs`?

**Comment by surechen** [comment]
> Thanks! I have one nit and one suggestion. After that, it's good to go. Lastly, could you update the PR title to something more descriptive? It's pretty general right now. r? fmease

Thank you very much. Modified according to the comments, please help review again.

File: tests/ui/traits/non_lifetime_binders/non-lifetime-binders-issue-119067.rs (hunk 1 above)
Comment (surechen) [reply tests/ui/traits/non_lifetime_binders/non-lifetime-binders-issue-119067.rs]: Done. Thank you.

File: compiler/rustc_ast_passes/src/feature_gate.rs (hunk 2 above)
Comment (surechen) [reply compiler/rustc_ast_passes/src/feature_gate.rs]: Done. Thank you.

File: tests/ui/traits/non_lifetime_binders/non-lifetime-binders-issue-119067.rs (hunk 3 above)
Comment (surechen) [reply tests/ui/traits/non_lifetime_binders/non-lifetime-binders-issue-119067.rs]: Done. Thank you.

File: tests/ui/traits/non_lifetime_binders/non-lifetime-binders-issue-119067.rs
Comment (surechen) [reply tests/ui/traits/non_lifetime_binders/non-lifetime-binders-issue-119067.rs:1]: Thank you.
According to the suggestion, split it into two files.

**Review by fmease — APPROVED** [review]

**Comment by fmease** [comment]
Thanks a lot!
@bors r+ rollup
