### PR TITLE
Do not suggest adding semicolon/changing delimiters for macros in item position that originates in macros

### LINKED ISSUE #91800: Rustc suggestsion with invalid syntax
```rust
// lib.rs  in proc-macro crate
#[proc_macro_derive(MyTrait)]
pub fn mytrait(item: TokenStream) -> TokenStream {
    "compile_error!()".parse().unwrap()
}

// lib.rs in other crate
#[derive(MyTrait)]
struct MyStruct;
```

```
error: macros that expand to items must be delimited with braces or followed by a semicolon
  --> examples\mytrait.rs:10:10
   |
10 | #[derive(MyTrait)]
   |          ^^^^^^^
   |
   = note: this error originates in the derive macro `MyTrait` (in Nightly builds, run with -Z macro-backtrace for more info)
help: change the delimiters to curly braces
   |
10 | #[derive({})]
   |          ~
help: add a semicolon
   |
10 | #[derive(MyTrait;)]
   |                 +
```

Both suggestions have invalid syntax.
Ideally rustc should suggest to add `;` into token stream returned from derive-proc-macro.

### PR DESCRIPTION
**Pull request by ChayimFriedman2**
Fixes #91800.

### CODE REVIEW

**Comment by michaelwoerister** [comment]
Thanks for the PR, @ChayimFriedman2! That FIXME suggests that there's a diagnostics design decision to be made here. 
r? rust-lang/diagnostics

File: compiler/rustc_parse/src/parser/item.rs [hunk 1]
```diff
@@ -1762,30 +1762,34 @@ impl<'a> Parser<'a> {
...
-            };
-            err.multipart_suggestion(
-                "change the delimiters to curly braces",
-                vec![(open, "{".to_string()), (close, '}'.to_string())],
-                Applicability::MaybeIncorrect,
-            );
-        } else {
+        // FIXME: This will make us not emit the help even for declarative
+        // macros within the same crate (that we can fix), which is sad.
+        if !span.from_expansion() {
```
Comment (estebank) [inline compiler/rustc_parse/src/parser/item.rs:1767]: What happens if you instead use the following? Is the FIXME still applicable then? I suspect it might not be.

```suggestion
        if !span.can_be_used_for_suggestions() {
```

File: src/test/ui/proc-macro/issue-91800.stderr [hunk 2]
```diff
@@ -0,0 +1,56 @@
...
+   |
+   = note: this error originates in the derive macro `MyTrait` (in Nightly builds, run with -Z macro-backtrace for more info)
+
+error: proc-macro derive produced unparseable tokens
+  --> $DIR/issue-91800.rs:6:10
+   |
+LL | #[derive(MyTrait)]
+   |          ^^^^^^^
+
+error:
```
Comment (estebank) [inline src/test/ui/proc-macro/issue-91800.stderr:15]: What is going on here! 😮

**Review by estebank — APPROVED** [review]

File: compiler/rustc_parse/src/parser/item.rs (hunk 1 above)
Comment (ChayimFriedman2) [reply compiler/rustc_parse/src/parser/item.rs:1767]: That doesn't work. `can_be_used_for_suggestions()` only checks for derive macros where the span they emit is different from the span of themselves. This will both provide incorrect suggestions for those macros and still fail as with the FIXME.

https://github.com/rust-lang/rust/blob/49c82f31a85f04a709810de4ccfb8ba765c1377b/compiler/rustc_span/src/lib.rs#L575-L583

File: src/test/ui/proc-macro/issue-91800.stderr (hunk 2 above)
Comment (ChayimFriedman2) [reply src/test/ui/proc-macro/issue-91800.stderr:15]: I can use a custom error message if necessary, it will be more clear.

File: compiler/rustc_parse/src/parser/item.rs (hunk 1 above)
Comment (estebank) [reply compiler/rustc_parse/src/parser/item.rs:1767]: What about using `in_derive_expansion` and only gate on those, then?

Comment (ChayimFriedman2) [reply compiler/rustc_parse/src/parser/item.rs:1767]: I've thought about that, but attribute macros should not suggest help either; and probably neither should declarative macros from separate crates.

Comment (estebank) [reply compiler/rustc_parse/src/parser/item.rs:1767]: Could you then checks for `!matches!(kind, ExprKind::Macro(MacroKind::Derive | MacroKind::Attr, _))` and using `tcx.sess().source_map().lookup_char_pos(span.lo()).file` on both the suggestion span and the callsite span to see if they belong to the same file?

Also, an additional test for those cases so that we see when the suggestion should appear in the same file might be useful. That might be easy to do for a macro by example. You might need to expand the test to also have an "external crate" example to check for that case too.

Would you have time to get these things done in this PR?

Comment (ChayimFriedman2) [reply compiler/rustc_parse/src/parser/item.rs:1767]: Soon. But should it be the same file or same crate?

Comment (ChayimFriedman2) [reply compiler/rustc_parse/src/parser/item.rs:1767]: And what about function-like proc macros? How can I differentiate those?

Comment (estebank) [reply compiler/rustc_parse/src/parser/item.rs:1767]: Ah, you're right. @petrochenkov what would the best way of checking that a span doesn't correspond to a proc-macro of any type nor a macro by example from a foreign crate, while parsing an item?

Comment (estebank) [reply compiler/rustc_parse/src/parser/item.rs:1767]: @petrochenkov friendly ping, if you have advice re: ^

I'm ok with landing with `if !span.from_expansion() {`, at least for now. Would you mind rebasing @ChayimFriedman2?

Comment (ChayimFriedman2) [reply compiler/rustc_parse/src/parser/item.rs:1780]: @estebank ^^^ Done.
