### PR TITLE
Apple: Always pass SDK root when linking with `cc`, and pass it via `SDKROOT` env var

### LINKED ISSUE #80817: Linker errors when cross-compiling from Xcode on Big Sur
Hi all, invoking `cargo build` from Xcode on Big Sur currently fails when a crate needs to link against a system library from a build script, unless `SDKROOT` has been [explicitly set to the path of the macOS SDK](https://github.com/irh/rust-big-sur-test/blob/e4fdc1fa73c32ad9b54cce077367fe4f45e3f207/xcode/rust-build-script.sh#L2). Test project [here](https://github.com/irh/rust-big-sur-test/tree/5b23ad719c477c31c6121ef7d6f3e8093569b513).

When invoking `cargo build` from an Xcode build script, `SDKROOT` is set for the platform that's being built. #64254 made it so that `SDKROOT` gets un-set if the target platform doesn't match the host platform. This seems reasonable to me, but then I don't understand why there's now a difference in behaviour between Xcode and non-Xcode builds. 

I logged a similiar [issue](https://github.com/TimNN/cargo-lipo/issues/41) for `cargo-lipo`, which has a different workaround of instead setting `LIBRARY_PATH`.

### LINKED ISSUE #96943: Spurious "error: could not find native static library `objc`, perhaps an -L flag is missing?" on macOS Big Sur
Hi 👋 

There's been a change in macOS Big Sur 11 with regards to how shared libraries are handled [1]:

> New in macOS Big Sur 11 beta, the system ships with a built-in dynamic linker cache of all system-provided libraries. As part of this change, copies of dynamic libraries are no longer present on the filesystem. Code that attempts to check for dynamic library presence by looking for a file at a path or enumerating a directory will fail. Instead, check for library presence by attempting to dlopen() the path, which will correctly check for the library in the cache. (62986286)

I'm experiencing this issue on macOS Big Sur when [libusb1-sys crate's `build.rs`](https://github.com/a1ien/rusb/blob/master/libusb1-sys/build.rs) invokes `pkg-config` and gets this:

```
$ pkg-config --static --libs /usr/local/Cellar/libusb/1.0.26/lib/pkgconfig/libusb-1.0.pc
-L/usr/local/Cellar/libusb/1.0.26/lib -lusb-1.0 -lobjc -Wl,-framework,IOKit -Wl,-framework,CoreFoundation -Wl,-framework,Security
```

rustc seems then proceed to try to link `libobjc`:

```
$ [...] cargo build
   Compiling libusb1-sys v0.6.2 (/Users/adaszko/repos/rusb/libusb1-sys)
   Compiling rusb v0.9.1
error: could not find native static library `objc`, perhaps an -L flag is missing?
```

Contrary to [1] recommendations, rustc [checks for library file existence rather than doing dlopen](https://github.com/rust-lang/rust/blob/78450d2d602b06d9b94349aaf8cece1a4acaf3a8/compiler/rustc_codegen_ssa/src/back/archive.rs#L32) so there's the rub.

Just to confirm, I've written a minimal program that uses dlopen instead of file existence test and it *doesn't* produce any error:

```
$ cat src/main.rs
fn main() {
    unsafe {
        libloading::Library::new("/usr/lib/libobjc.dylib").unwrap();
    }
}
```

[1]: https://web.archive.org/web/20220317152936/https://developer.apple.com/documentation/macos-release-notes/macos-big-sur-11-beta-release-notes

### PR DESCRIPTION
**Pull request by madsmtm**
Fixes https://github.com/rust-lang/rust/issues/80817, fixes https://github.com/rust-lang/rust/issues/96943, and generally simplifies our linker invocation on Apple platforms.

Part of https://github.com/rust-lang/rust/issues/129432.

### Necessary background on trampoline binaries

The developer binaries such as `/usr/bin/cc` and `/usr/bin/clang` are actually trampolines (similar in spirit to the Rust binaries in `~/.cargo/bin`) which effectively invokes `xcrun` to get the current Xcode developer directory, which allows it to find the actual binary under `/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/*`.

This binary is then launched with the following environment variables set (but none of them are set if `SDKROOT` is set explicitly):
- `SDKROOT=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk`
- `LIBRARY_PATH=/usr/local/lib` (appended)
- `CPATH=/usr/local/include` (appended)
- `MANPATH=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man:/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/usr/share/man:/Applications/Xcode.app/Contents/Developer/usr/share/man:/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/share/man:` (prepended)

This allows the user to type e.g. `clang foo.c` in their terminal on macOS, and have it automatically pick up a suitable Clang binary and SDK from either an installed Xcode.app or the Xcode Command Line Tools.
(It acts roughly as-if you typed `xcrun -sdk macosx clang foo.c`).

### Finding a suitable SDK

All compilation on macOS is cross-compilation using SDKs, there are no system headers any more (`/usr/include` is gone), and the system libraries are elsewhere in the file system (`/usr/lib` is basically empty). Instead, the logic for finding the SDK is handled by the `/usr/bin/cc` trampoline (see above).

But relying on the `cc` trampoline doesn't work when:
- Cross-compiling, since a different SDK is needed there.
- Invoking the linker directly, since the linker doesn't understand `SDKROOT`.
- Linking build scripts inside Xcode (see https://github.com/rust-lang/rust/issues/80817), since Xcode prepends `/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin` to `PATH`, which means `cc` refers to the _actual_ Clang binary, and we end up with the wrong SDK root specified.

Basically, we cannot rely on the trampoline at all, so the last commit removes the special-casing that was done when linking with `cc` for macOS (i.e. the most common path), so that **we now always invoke `xcrun` (if `SDKROOT` is not explicitly specified) to find the SDK root**.

Making sure this is non-breaking has a few difficulties though, namely that the user might not have Xcode installed, and that the compiler driver may not understand the `-isysroot` flag. These difficulties are explored below.

#### No Xcode

There are several compiler drivers which work without Xcode by bundling their own SDK, including `zig cc`, Nixpkgs' `clang` and Homebrew's `llvm` package. Additionally, `xcrun` is rarely available when cross-compiling from non-macOS and instead the user might provide a downloaded SDK manually with `-Clink-args=...`.

We do still want to _try_ to invoke `xcrun` if possible, since it is usually the SDK that the user wants (and if not, the environment should override `xcrun`, such as is done by Nixpkgs). But we do not want failure to invoke `xcrun` to stop the linking process. This is changed in the second-to-last commit.

#### `SDKROOT` vs. `-isysroot`

The exact reasoning why we do not always pass the SDK root when linking on macOS eludes me (the git history dead ends in rust-lang/rust#100286), but I suspect it's because we want to support compiler drivers which do not support the `-isysroot` option.

To make sure that such use-cases continue to work, we now pass the SDK root via the `SDKROOT` environment variable. This way, compiler drivers that support setting the SDK root (such as Clang and GCC) can use it, while compiler drivers that don't (presumably because they figure out the SDK in some other way) can just ignore it.

One small danger here would be if there's some compiler driver out there which works with the `-isysroot` flag, but not with the `SDKROOT` environment variable. I am not aware of any?

In a sense, this also shifts the blame; if a compiler driver does not understand `SDKROOT`, it won't work with e.g. `xcrun -sdk macosx15.0 $tool` either, so it can more clearly be argued that this is incorrect behaviour on the part of the tool.

Note also that this overrides the behaviour discussed above (`/usr/bin/cc` sets some extra environment variables), I will argue that is fine since `MANPATH` and `CPATH` is useless when linking, and `/usr/local/lib` is empty on a default system at least since macOS 10.14 (it might be filled by extra libraries installed by the user, but I'll argue that if we want it to be part of the default library search path, we should set it explicitly so that it's also set when linking with `-Clinker=ld`).

### Considered alternatives

- Invoke `/usr/bin/cc` instead of `cc`.
  - This breaks many other use-cases though where overriding `cc` in the PATH is desired.
- Look up `which cc`, and do special logic if in Xcode toolchain.
  - Seems brittle, and besides, it's not the `cc` in the Xcode toolchain that's wrong, it's the `/usr/bin/cc` behaviour that is a bit too magical.
- Invoke `xcrun --sdk macosx cc`.
  - This completely ignores `SDKROOT`, so we'd still have to parse that first to figure out if it's suitable or not, but would probably be workable.
- Maybe somehow configure the linker with extra flags such that it'll be able to link regardless of linking for macOS or e.g. iOS? Though I doubt this is possible.
- Bundle the SDK, similar to `zig-cc`.
  - Comes with it's own host of problems.

### Testing

Tested that this works with the following `-Clinker=...`:
- [x] Default (`cc`)
- [x] `/usr/bin/ld`
- [x] Actual Clang from Xcode (`/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang`)
- [x] `/usr/bin/clang` (invoked via `clang` instead of `cc`)
- [x] Homebrew's `llvm` package (ignores `SDKROOT`, uses their own SDK)
- [x] Homebrew's `gcc` package (`SDKROOT` is preferred over their own SDK)
- [x] ~Macports `clang`~ Couldn't get it to build
- [x] Macports `gcc` (`SDKROOT` is preferred over their own SDK)
- [x] Zig CC installed via. homebrew (ignores both `-isysroot` and `SDKROOT`, uses their own SDK)
- [x] Nixpkgs `clang` (ignores `SDKROOT`, uses their own SDK)
- [x] Nixpkgs `gcc` (ignores `SDKROOT`, uses their own SDK)
- [x] ~[`cosmocc`](https://github.com/jart/cosmopolitan)?~ Doesn't accept common flags (like `-arch`)

CC @BlackHoleFox @thomcc

### CODE REVIEW

**Comment by nnethercote** [comment]
This looks reasonable, but I don't really have the first idea about any of this stuff and that means I'm not a great reviewer for it. @thomcc, are you able to take a look? I can rubber-stamp it if  you are happy.

One question: there are no tests in this PR or in #131433. Should there be?

**Comment by madsmtm** [comment]
> One question: there are no tests in this PR or in #131433. Should there be?

There are a few unit tests under `compiler/rustc_codegen_ssa/src/apple/tests.rs`, but your point stands, there are no integration tests for this.

The main reason for that is that this is really hard to write a robust test for, since this is so heavily environment specific - but I guess a test that adds the Xcode paths to `PATH` as a regression test for https://github.com/rust-lang/rust/issues/80817 would be doable, I've done that and rebased, thanks for the nudge to do it ;).

File: compiler/rustc_target/src/spec/base/apple/mod.rs [hunk 1]
```diff
@@ -309,29 +309,10 @@ fn link_env_remove(os: &'static str) -> StaticCow<[StaticCow<str>]> {
     // that's only applicable to cross-OS compilation. Always leave anything for the
     // host OS alone though.
     if os == "macos" {
-        let mut env_remove = Vec::with_capacity(2);
-        // Remove the `SDKROOT` environment variable if it's clearly set for the wrong platform, which
```
Comment (BlackHoleFox) [inline compiler/rustc_target/src/spec/base/apple/mod.rs:296]: Is `rustc` now relying on `cc` or `clang` to sort this out since `SDKROOT` is unconditionally passed now?

Comment (madsmtm) [reply compiler/rustc_target/src/spec/base/apple/mod.rs:296]: Before, this code was only really useful when linking with `cc` on macOS (because in other cases, we passed the `-isysroot` parameter on the commandline, which overwrote it).

Now, we explicitly set the `SDKROOT` environment variable when linking with `cc`, so it'll get overwritten.

Comment (madsmtm) [reply compiler/rustc_target/src/spec/base/apple/mod.rs:296]: Oh, you meant the logic itself.

That was somewhat duplicated between this function and `get_apple_sdk_root`, I've made sure to merge it properly now.

**Review by thomcc — APPROVED** [review]
I approve of the macOS specific parts of this. I'm not a compiler reviewer so I haven't done any review for style/etc. That said that part does look fine to me. It's a great PR overall. Great PR description too, clarified some things I had always wondered about.

**Comment by nnethercote** [comment]
Thanks, @thomcc. Once #131433 is merged I'm happy for this to merge.

@bors delegate=madsmtm

File: compiler/rustc_target/src/spec/base/apple/mod.rs (hunk 1 above)
Comment (BlackHoleFox) [reply compiler/rustc_target/src/spec/base/apple/mod.rs:296]: Aaaa, nice :)

**Review by BlackHoleFox — APPROVED** [review]

**Comment by madsmtm** [comment]
I have become aware via https://github.com/rust-lang/cc-rs/issues/1278 that Homebrew creates Clang configuration files that passes `--sysroot`, will have to investigate whether using the `SDKROOT` env var is still desirable there?
