### PR TITLE
Fix a couple ICEs in the new `CastKind::Transmute` code

### LINKED ISSUE #109992: ICE: `Couldn't translate Aggregate { sized: true } as backend immediate`
### Code

```Rust
fn test_fn_transmute_zst(x: ()) -> [(); 1] {
    id(unsafe { std::mem::transmute(x) })
}

fn id<T>(x: T) -> T {
    x
}

fn main() {
    let r = 3;

    assert_eq!(test_fn_transmute_zst(()), [()]);
}
```

### Meta

`rustc --version --verbose`:
```
b2b676d886ded452125712a304c524c08360f916
```

### Error output
requires debug assertions!
`rustc treereduce.out  -Zmir-opt-level=0`
```
<output>
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
warning: unused variable: `r`
  --> treereduce.out:10:9
   |
10 |     let r = 3;
   |         ^ help: if this is intentional, prefix it with an underscore: `_r`
   |
   = note: `#[warn(unused_variables)]` on by default

error: internal compiler error: /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_codegen_ssa/src/mir/rvalue.rs:892:22: Couldn't translate Aggregate { sized: true } as backend immediate

thread 'rustc' panicked at 'Box<dyn Any>', /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_errors/src/lib.rs:1644:9
stack backtrace:
   0:     0x7f50b0b08b74 - std::backtrace_rs::backtrace::libunwind::trace::hb665cc1e15997bac
                               at /home/matthias/vcs/github/rust_debug_assertions/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x7f50b0b08b74 - std::backtrace_rs::backtrace::trace_unsynchronized::h055f8ddc726b8f7c
                               at /home/matthias/vcs/github/rust_debug_assertions/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7f50b0b08b74 - std::sys_common::backtrace::_print_fmt::h999bfbccdb2f08c6
                               at /home/matthias/vcs/github/rust_debug_assertions/library/std/src/sys_common/backtrace.rs:65:5
   3:     0x7f50b0b08b74 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h69192bf0ed9c5c99
                               at /home/matthias/vcs/github/rust_debug_assertions/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x7f50b0bb962b - core::fmt::write::h2dac34aae88eac3a
                               at /home/matthias/vcs/github/rust_debug_assertions/library/core/src/fmt/mod.rs:1254:17
   5:     0x7f50b0b4cc4f - std::io::Write::write_fmt::ha9250e813467be99
                               at /home/matthias/vcs/github/rust_debug_assertions/library/std/src/io/mod.rs:1698:15
   6:     0x7f50b0b08975 - std::sys_common::backtrace::_print::h7f5c2f1ca54d0413
                               at /home/matthias/vcs/github/rust_debug_assertions/library/std/src/sys_common/backtrace.rs:47:5
   7:     0x7f50b0b08975 - std::sys_common::backtrace::print::h6c093bf114bc8569
                               at /home/matthias/vcs/github/rust_debug_assertions/library/std/src/sys_common/backtrace.rs:34:9
   8:     0x7f50b0b33ef4 - std::panicking::default_hook::{{closure}}::hbab87a1d77c907c2
   9:     0x7f50b0b33b2d - std::panicking::default_hook::h888aa058ad9d0fac
                               at /home/matthias/vcs/github/rust_debug_assertions/library/std/src/panicking.rs:288:9
  10:     0x7f50b3666b75 - <alloc[8685091c532fe695]::boxed::Box<dyn for<'a, 'b> core[56d2be079082b2f7]::ops::function::Fn<(&'a core[56d2be079082b2f7]::panic::panic_info::PanicInfo<'b>,), Output = ()> + core[56d2be079082b2f7]::marker::Send + core[56d2be079082b2f7]::marker::Sync> as core[56d2be079082b2f7]::ops::function::Fn<(&core[56d2be079082b2f7]::panic::panic_info::PanicInfo,)>>::call
                               at /home/matthias/vcs/github/rust_debug_assertions/library/alloc/src/boxed.rs:1990:9
  11:     0x7f50b3666b75 - rustc_driver_impl[53cfb4cfe592b1cc]::DEFAULT_HOOK::{closure#0}::{closure#0}
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_driver_impl/src/lib.rs:1199:17
  12:     0x7f50b0b346e1 - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h40961c4fa974a79e
                               at /home/matthias/vcs/github/rust_debug_assertions/library/alloc/src/boxed.rs:1990:9
  13:     0x7f50b0b346e1 - std::panicking::rust_panic_with_hook::hf2bdefcf339fd31a
                               at /home/matthias/vcs/github/rust_debug_assertions/library/std/src/panicking.rs:694:13
  14:     0x7f50b46a64b3 - std[86ab35e6a6527d40]::panicking::begin_panic::<rustc_errors[bf7ae9ae6b851a13]::ExplicitBug>::{closure#0}
                               at /home/matthias/vcs/github/rust_debug_assertions/library/std/src/panicking.rs:610:9
  15:     0x7f50b46a0486 - std[86ab35e6a6527d40]::sys_common::backtrace::__rust_end_short_backtrace::<std[86ab35e6a6527d40]::panicking::begin_panic<rustc_errors[bf7ae9ae6b851a13]::ExplicitBug>::{closure#0}, !>
                               at /home/matthias/vcs/github/rust_debug_assertions/library/std/src/sys_common/backtrace.rs:150:18
  16:     0x7f50b47b9216 - std[86ab35e6a6527d40]::panicking::begin_panic::<rustc_errors[bf7ae9ae6b851a13]::ExplicitBug>
                               at /home/matthias/vcs/github/rust_debug_assertions/library/std/src/panicking.rs:609:12
  17:     0x7f50b4729ffa - std[86ab35e6a6527d40]::panic::panic_any::<rustc_errors[bf7ae9ae6b851a13]::ExplicitBug>
                               at /home/matthias/vcs/github/rust_debug_assertions/library/std/src/panic.rs:61:5
  18:     0x7f50b4729ffa - <rustc_errors[bf7ae9ae6b851a13]::HandlerInner>::bug::<&alloc[8685091c532fe695]::string::String>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_errors/src/lib.rs:1644:9
  19:     0x7f50b4729ba0 - <rustc_errors[bf7ae9ae6b851a13]::Handler>::bug::<&alloc[8685091c532fe695]::string::String>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_errors/src/lib.rs:1064:9
  20:     0x7f50b47a9d9e - rustc_middle[1621e1d9efb092ce]::util::bug::opt_span_bug_fmt::<rustc_span[5e1e12958345f30f]::span_encoding::Span>::{closure#0}
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_middle/src/util/bug.rs:35:34
  21:     0x7f50b47a93d4 - rustc_middle[1621e1d9efb092ce]::ty::context::tls::with_opt::<rustc_middle[1621e1d9efb092ce]::util::bug::opt_span_bug_fmt<rustc_span[5e1e12958345f30f]::span_encoding::Span>::{closure#0}, !>::{closure#0}
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_middle/src/ty/context/tls.rs:154:36
  22:     0x7f50b47a936e - rustc_middle[1621e1d9efb092ce]::ty::context::tls::with_context_opt::<rustc_middle[1621e1d9efb092ce]::ty::context::tls::with_opt<rustc_middle[1621e1d9efb092ce]::util::bug::opt_span_bug_fmt<rustc_span[5e1e12958345f30f]::span_encoding::Span>::{closure#0}, !>::{closure#0}, !>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_middle/src/ty/context/tls.rs:100:18
  23:     0x7f50b47a9cd7 - rustc_middle[1621e1d9efb092ce]::ty::context::tls::with_opt::<rustc_middle[1621e1d9efb092ce]::util::bug::opt_span_bug_fmt<rustc_span[5e1e12958345f30f]::span_encoding::Span>::{closure#0}, !>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_middle/src/ty/context/tls.rs:154:5
  24:     0x7f50b47a9cd7 - rustc_middle[1621e1d9efb092ce]::util::bug::opt_span_bug_fmt::<rustc_span[5e1e12958345f30f]::span_encoding::Span>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_middle/src/util/bug.rs:31:5
  25:     0x7f50b47a9c53 - rustc_middle[1621e1d9efb092ce]::util::bug::bug_fmt
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_middle/src/util/bug.rs:15:5
  26:     0x7f50b32e0241 - <rustc_codegen_ssa[cb990c0ddf67acf7]::mir::FunctionCx<rustc_codegen_llvm[c562a0c5f00a438f]::builder::Builder>>::value_kind
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_codegen_ssa/src/mir/rvalue.rs:892:22
  27:     0x7f50b32e0396 - <rustc_codegen_ssa[cb990c0ddf67acf7]::mir::FunctionCx<rustc_codegen_llvm[c562a0c5f00a438f]::builder::Builder>>::rvalue_creates_operand
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_codegen_ssa/src/mir/rvalue.rs:843:24
  28:     0x7f50b31f7b62 - <rustc_codegen_ssa[cb990c0ddf67acf7]::mir::analyze::LocalAnalyzer<rustc_codegen_llvm[c562a0c5f00a438f]::builder::Builder> as rustc_middle[1621e1d9efb092ce]::mir::visit::Visitor>::visit_assign
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_codegen_ssa/src/mir/analyze.rs:183:21
  29:     0x7f50b31f7b62 - <rustc_codegen_ssa[cb990c0ddf67acf7]::mir::analyze::LocalAnalyzer<rustc_codegen_llvm[c562a0c5f00a438f]::builder::Builder> as rustc_middle[1621e1d9efb092ce]::mir::visit::Visitor>::super_statement
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_middle/src/mir/visit.rs:370:25
  30:     0x7f50b31f7b62 - <rustc_codegen_ssa[cb990c0ddf67acf7]::mir::analyze::LocalAnalyzer<rustc_codegen_llvm[c562a0c5f00a438f]::builder::Builder> as rustc_middle[1621e1d9efb092ce]::mir::visit::Visitor>::visit_statement
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_middle/src/mir/visit.rs:105:17
  31:     0x7f50b31f7b62 - <rustc_codegen_ssa[cb990c0ddf67acf7]::mir::analyze::LocalAnalyzer<rustc_codegen_llvm[c562a0c5f00a438f]::builder::Builder> as rustc_middle[1621e1d9efb092ce]::mir::visit::Visitor>::super_basic_block_data
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_middle/src/mir/visit.rs:299:21
  32:     0x7f50b31f7b62 - <rustc_codegen_ssa[cb990c0ddf67acf7]::mir::analyze::LocalAnalyzer<rustc_codegen_llvm[c562a0c5f00a438f]::builder::Builder> as rustc_middle[1621e1d9efb092ce]::mir::visit::Visitor>::visit_basic_block_data
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_middle/src/mir/visit.rs:90:17
  33:     0x7f50b31f7b62 - rustc_codegen_ssa[cb990c0ddf67acf7]::mir::analyze::non_ssa_locals::<rustc_codegen_llvm[c562a0c5f00a438f]::builder::Builder>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_codegen_ssa/src/mir/analyze.rs:46:9
  34:     0x7f50b32c72bc - rustc_codegen_ssa[cb990c0ddf67acf7]::mir::codegen_mir::<rustc_codegen_llvm[c562a0c5f00a438f]::builder::Builder>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_codegen_ssa/src/mir/mod.rs:224:25
  35:     0x7f50b3248d64 - rustc_codegen_ssa[cb990c0ddf67acf7]::base::codegen_instance::<rustc_codegen_llvm[c562a0c5f00a438f]::builder::Builder>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_codegen_ssa/src/base.rs:398:5
  36:     0x7f50b328ba75 - <rustc_middle[1621e1d9efb092ce]::mir::mono::MonoItem as rustc_codegen_ssa[cb990c0ddf67acf7]::mono_item::MonoItemExt>::define::<rustc_codegen_llvm[c562a0c5f00a438f]::builder::Builder>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_codegen_ssa/src/mono_item.rs:91:17
  37:     0x7f50b315415e - rustc_codegen_llvm[c562a0c5f00a438f]::base::compile_codegen_unit::module_codegen
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_codegen_llvm/src/base.rs:95:17
  38:     0x7f50b3158a14 - <rustc_query_system[eeda195d38f2e6a0]::dep_graph::graph::DepGraph<rustc_middle[1621e1d9efb092ce]::dep_graph::dep_node::DepKind>>::with_task::<rustc_middle[1621e1d9efb092ce]::ty::context::TyCtxt, rustc_span[5e1e12958345f30f]::symbol::Symbol, rustc_codegen_ssa[cb990c0ddf67acf7]::ModuleCodegen<rustc_codegen_llvm[c562a0c5f00a438f]::ModuleLlvm>>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_query_system/src/dep_graph/graph.rs:275:22
  39:     0x7f50b3158a14 - rustc_codegen_llvm[c562a0c5f00a438f]::base::compile_codegen_unit
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_codegen_llvm/src/base.rs:64:37
  40:     0x7f50b3158a14 - <rustc_codegen_llvm[c562a0c5f00a438f]::LlvmCodegenBackend as rustc_codegen_ssa[cb990c0ddf67acf7]::traits::backend::ExtraBackendMethods>::compile_codegen_unit
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_codegen_llvm/src/lib.rs:131:9
  41:     0x7f50b3248110 - rustc_codegen_ssa[cb990c0ddf67acf7]::base::codegen_crate::<rustc_codegen_llvm[c562a0c5f00a438f]::LlvmCodegenBackend>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_codegen_ssa/src/base.rs:733:34
  42:     0x7f50b315e407 - <rustc_codegen_llvm[c562a0c5f00a438f]::LlvmCodegenBackend as rustc_codegen_ssa[cb990c0ddf67acf7]::traits::backend::CodegenBackend>::codegen_crate
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_codegen_llvm/src/lib.rs:343:18
  43:     0x7f50b41b6462 - rustc_interface[a109d3959576535b]::passes::start_codegen::{closure#0}
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_interface/src/passes.rs:874:9
  44:     0x7f50b41b6462 - <rustc_data_structures[8a557029cfac743e]::profiling::VerboseTimingGuard>::run::<alloc[8685091c532fe695]::boxed::Box<dyn core[56d2be079082b2f7]::any::Any>, rustc_interface[a109d3959576535b]::passes::start_codegen::{closure#0}>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_data_structures/src/profiling.rs:752:9
  45:     0x7f50b41b6462 - <rustc_session[5da8902571af233a]::session::Session>::time::<alloc[8685091c532fe695]::boxed::Box<dyn core[56d2be079082b2f7]::any::Any>, rustc_interface[a109d3959576535b]::passes::start_codegen::{closure#0}>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_session/src/utils.rs:11:50
  46:     0x7f50b41b6462 - rustc_interface[a109d3959576535b]::passes::start_codegen
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_interface/src/passes.rs:873:19
  47:     0x7f50b4273a85 - <rustc_interface[a109d3959576535b]::queries::Queries>::ongoing_codegen::{closure#0}::{closure#0}
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_interface/src/queries.rs:264:20
  48:     0x7f50b4273a85 - <rustc_middle[1621e1d9efb092ce]::ty::context::GlobalCtxt>::enter::<<rustc_interface[a109d3959576535b]::queries::Queries>::ongoing_codegen::{closure#0}::{closure#0}, core[56d2be079082b2f7]::result::Result<alloc[8685091c532fe695]::boxed::Box<dyn core[56d2be079082b2f7]::any::Any>, rustc_span[5e1e12958345f30f]::ErrorGuaranteed>>::{closure#0}
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_middle/src/ty/context.rs:559:37
  49:     0x7f50b4273a85 - rustc_middle[1621e1d9efb092ce]::ty::context::tls::enter_context::<<rustc_middle[1621e1d9efb092ce]::ty::context::GlobalCtxt>::enter<<rustc_interface[a109d3959576535b]::queries::Queries>::ongoing_codegen::{closure#0}::{closure#0}, core[56d2be079082b2f7]::result::Result<alloc[8685091c532fe695]::boxed::Box<dyn core[56d2be079082b2f7]::any::Any>, rustc_span[5e1e12958345f30f]::ErrorGuaranteed>>::{closure#0}, core[56d2be079082b2f7]::result::Result<alloc[8685091c532fe695]::boxed::Box<dyn core[56d2be079082b2f7]::any::Any>, rustc_span[5e1e12958345f30f]::ErrorGuaranteed>>::{closure#0}
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_middle/src/ty/context/tls.rs:82:9
  50:     0x7f50b4273a85 - <std[86ab35e6a6527d40]::thread::local::LocalKey<core[56d2be079082b2f7]::cell::Cell<*const ()>>>::try_with::<rustc_middle[1621e1d9efb092ce]::ty::context::tls::enter_context<<rustc_middle[1621e1d9efb092ce]::ty::context::GlobalCtxt>::enter<<rustc_interface[a109d3959576535b]::queries::Queries>::ongoing_codegen::{closure#0}::{closure#0}, core[56d2be079082b2f7]::result::Result<alloc[8685091c532fe695]::boxed::Box<dyn core[56d2be079082b2f7]::any::Any>, rustc_span[5e1e12958345f30f]::ErrorGuaranteed>>::{closure#0}, core[56d2be079082b2f7]::result::Result<alloc[8685091c532fe695]::boxed::Box<dyn core[56d2be079082b2f7]::any::Any>, rustc_span[5e1e12958345f30f]::ErrorGuaranteed>>::{closure#0}, core[56d2be079082b2f7]::result::Result<alloc[8685091c532fe695]::boxed::Box<dyn core[56d2be079082b2f7]::any::Any>, rustc_span[5e1e12958345f30f]::ErrorGuaranteed>>
                               at /home/matthias/vcs/github/rust_debug_assertions/library/std/src/thread/local.rs:252:16
  51:     0x7f50b4273a85 - <std[86ab35e6a6527d40]::thread::local::LocalKey<core[56d2be079082b2f7]::cell::Cell<*const ()>>>::with::<rustc_middle[1621e1d9efb092ce]::ty::context::tls::enter_context<<rustc_middle[1621e1d9efb092ce]::ty::context::GlobalCtxt>::enter<<rustc_interface[a109d3959576535b]::queries::Queries>::ongoing_codegen::{closure#0}::{closure#0}, core[56d2be079082b2f7]::result::Result<alloc[8685091c532fe695]::boxed::Box<dyn core[56d2be079082b2f7]::any::Any>, rustc_span[5e1e12958345f30f]::ErrorGuaranteed>>::{closure#0}, core[56d2be079082b2f7]::result::Result<alloc[8685091c532fe695]::boxed::Box<dyn core[56d2be079082b2f7]::any::Any>, rustc_span[5e1e12958345f30f]::ErrorGuaranteed>>::{closure#0}, core[56d2be079082b2f7]::result::Result<alloc[8685091c532fe695]::boxed::Box<dyn core[56d2be079082b2f7]::any::Any>, rustc_span[5e1e12958345f30f]::ErrorGuaranteed>>
                               at /home/matthias/vcs/github/rust_debug_assertions/library/std/src/thread/local.rs:228:9
  52:     0x7f50b42b33ab - rustc_middle[1621e1d9efb092ce]::ty::context::tls::enter_context::<<rustc_middle[1621e1d9efb092ce]::ty::context::GlobalCtxt>::enter<<rustc_interface[a109d3959576535b]::queries::Queries>::ongoing_codegen::{closure#0}::{closure#0}, core[56d2be079082b2f7]::result::Result<alloc[8685091c532fe695]::boxed::Box<dyn core[56d2be079082b2f7]::any::Any>, rustc_span[5e1e12958345f30f]::ErrorGuaranteed>>::{closure#0}, core[56d2be079082b2f7]::result::Result<alloc[8685091c532fe695]::boxed::Box<dyn core[56d2be079082b2f7]::any::Any>, rustc_span[5e1e12958345f30f]::ErrorGuaranteed>>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_middle/src/ty/context/tls.rs:79:5
  53:     0x7f50b42b33ab - <rustc_middle[1621e1d9efb092ce]::ty::context::GlobalCtxt>::enter::<<rustc_interface[a109d3959576535b]::queries::Queries>::ongoing_codegen::{closure#0}::{closure#0}, core[56d2be079082b2f7]::result::Result<alloc[8685091c532fe695]::boxed::Box<dyn core[56d2be079082b2f7]::any::Any>, rustc_span[5e1e12958345f30f]::ErrorGuaranteed>>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_middle/src/ty/context.rs:559:9
  54:     0x7f50b42b33ab - <rustc_interface[a109d3959576535b]::queries::QueryResult<&rustc_middle[1621e1d9efb092ce]::ty::context::GlobalCtxt>>::enter::<core[56d2be079082b2f7]::result::Result<alloc[8685091c532fe695]::boxed::Box<dyn core[56d2be079082b2f7]::any::Any>, rustc_span[5e1e12958345f30f]::ErrorGuaranteed>, <rustc_interface[a109d3959576535b]::queries::Queries>::ongoing_codegen::{closure#0}::{closure#0}>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_interface/src/queries.rs:71:9
  55:     0x7f50b42b33ab - <rustc_interface[a109d3959576535b]::queries::Queries>::ongoing_codegen::{closure#0}
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_interface/src/queries.rs:251:13
  56:     0x7f50b42b33ab - <rustc_interface[a109d3959576535b]::queries::Query<alloc[8685091c532fe695]::boxed::Box<dyn core[56d2be079082b2f7]::any::Any>>>::compute::<<rustc_interface[a109d3959576535b]::queries::Queries>::ongoing_codegen::{closure#0}>::{closure#0}::{closure#0}
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_interface/src/queries.rs:45:41
  57:     0x7f50b42b33ab - <core[56d2be079082b2f7]::option::Option<core[56d2be079082b2f7]::result::Result<rustc_data_structures[8a557029cfac743e]::steal::Steal<alloc[8685091c532fe695]::boxed::Box<dyn core[56d2be079082b2f7]::any::Any>>, rustc_span[5e1e12958345f30f]::ErrorGuaranteed>>>::get_or_insert_with::<<rustc_interface[a109d3959576535b]::queries::Query<alloc[8685091c532fe695]::boxed::Box<dyn core[56d2be079082b2f7]::any::Any>>>::compute<<rustc_interface[a109d3959576535b]::queries::Queries>::ongoing_codegen::{closure#0}>::{closure#0}::{closure#0}>
                               at /home/matthias/vcs/github/rust_debug_assertions/library/core/src/option.rs:1724:49
  58:     0x7f50b42b33ab - <rustc_interface[a109d3959576535b]::queries::Query<alloc[8685091c532fe695]::boxed::Box<dyn core[56d2be079082b2f7]::any::Any>>>::compute::<<rustc_interface[a109d3959576535b]::queries::Queries>::ongoing_codegen::{closure#0}>::{closure#0}
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_interface/src/queries.rs:45:17
  59:     0x7f50b42b33ab - <core[56d2be079082b2f7]::cell::RefMut<core[56d2be079082b2f7]::option::Option<core[56d2be079082b2f7]::result::Result<rustc_data_structures[8a557029cfac743e]::steal::Steal<alloc[8685091c532fe695]::boxed::Box<dyn core[56d2be079082b2f7]::any::Any>>, rustc_span[5e1e12958345f30f]::ErrorGuaranteed>>>>::filter_map::<rustc_data_structures[8a557029cfac743e]::steal::Steal<alloc[8685091c532fe695]::boxed::Box<dyn core[56d2be079082b2f7]::any::Any>>, <rustc_interface[a109d3959576535b]::queries::Query<alloc[8685091c532fe695]::boxed::Box<dyn core[56d2be079082b2f7]::any::Any>>>::compute<<rustc_interface[a109d3959576535b]::queries::Queries>::ongoing_codegen::{closure#0}>::{closure#0}>
                               at /home/matthias/vcs/github/rust_debug_assertions/library/core/src/cell.rs:1637:15
  60:     0x7f50b42b33ab - <rustc_interface[a109d3959576535b]::queries::Query<alloc[8685091c532fe695]::boxed::Box<dyn core[56d2be079082b2f7]::any::Any>>>::compute::<<rustc_interface[a109d3959576535b]::queries::Queries>::ongoing_codegen::{closure#0}>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_interface/src/queries.rs:42:9
  61:     0x7f50b42b33ab - <rustc_interface[a109d3959576535b]::queries::Queries>::ongoing_codegen
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_interface/src/queries.rs:250:9
  62:     0x7f50b36cd873 - rustc_driver_impl[53cfb4cfe592b1cc]::run_compiler::{closure#1}::{closure#2}
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_driver_impl/src/lib.rs:397:13
  63:     0x7f50b36cd873 - <rustc_interface[a109d3959576535b]::interface::Compiler>::enter::<rustc_driver_impl[53cfb4cfe592b1cc]::run_compiler::{closure#1}::{closure#2}, core[56d2be079082b2f7]::result::Result<core[56d2be079082b2f7]::option::Option<rustc_interface[a109d3959576535b]::queries::Linker>, rustc_span[5e1e12958345f30f]::ErrorGuaranteed>>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_interface/src/queries.rs:394:19
  64:     0x7f50b3667eab - rustc_driver_impl[53cfb4cfe592b1cc]::run_compiler::{closure#1}
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_driver_impl/src/lib.rs:332:22
  65:     0x7f50b3667eab - rustc_interface[a109d3959576535b]::interface::run_compiler::<core[56d2be079082b2f7]::result::Result<(), rustc_span[5e1e12958345f30f]::ErrorGuaranteed>, rustc_driver_impl[53cfb4cfe592b1cc]::run_compiler::{closure#1}>::{closure#0}::{closure#0}
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_interface/src/interface.rs:301:21
  66:     0x7f50b3667eab - rustc_span[5e1e12958345f30f]::set_source_map::<core[56d2be079082b2f7]::result::Result<(), rustc_span[5e1e12958345f30f]::ErrorGuaranteed>, rustc_interface[a109d3959576535b]::interface::run_compiler<core[56d2be079082b2f7]::result::Result<(), rustc_span[5e1e12958345f30f]::ErrorGuaranteed>, rustc_driver_impl[53cfb4cfe592b1cc]::run_compiler::{closure#1}>::{closure#0}::{closure#0}>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_span/src/lib.rs:1040:5
  67:     0x7f50b3677832 - rustc_interface[a109d3959576535b]::interface::run_compiler::<core[56d2be079082b2f7]::result::Result<(), rustc_span[5e1e12958345f30f]::ErrorGuaranteed>, rustc_driver_impl[53cfb4cfe592b1cc]::run_compiler::{closure#1}>::{closure#0}
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_interface/src/interface.rs:295:13
  68:     0x7f50b3677832 - <scoped_tls[4c47fe243b885cb1]::ScopedKey<rustc_span[5e1e12958345f30f]::SessionGlobals>>::set::<rustc_interface[a109d3959576535b]::interface::run_compiler<core[56d2be079082b2f7]::result::Result<(), rustc_span[5e1e12958345f30f]::ErrorGuaranteed>, rustc_driver_impl[53cfb4cfe592b1cc]::run_compiler::{closure#1}>::{closure#0}, core[56d2be079082b2f7]::result::Result<(), rustc_span[5e1e12958345f30f]::ErrorGuaranteed>>
                               at /home/matthias/.cargo/registry/src/github.com-1ecc6299db9ec823/scoped-tls-1.0.0/src/lib.rs:137:9
  69:     0x7f50b3677832 - rustc_span[5e1e12958345f30f]::create_session_globals_then::<core[56d2be079082b2f7]::result::Result<(), rustc_span[5e1e12958345f30f]::ErrorGuaranteed>, rustc_interface[a109d3959576535b]::interface::run_compiler<core[56d2be079082b2f7]::result::Result<(), rustc_span[5e1e12958345f30f]::ErrorGuaranteed>, rustc_driver_impl[53cfb4cfe592b1cc]::run_compiler::{closure#1}>::{closure#0}>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_span/src/lib.rs:120:5
  70:     0x7f50b3677832 - rustc_interface[a109d3959576535b]::util::run_in_thread_pool_with_globals::<rustc_interface[a109d3959576535b]::interface::run_compiler<core[56d2be079082b2f7]::result::Result<(), rustc_span[5e1e12958345f30f]::ErrorGuaranteed>, rustc_driver_impl[53cfb4cfe592b1cc]::run_compiler::{closure#1}>::{closure#0}, core[56d2be079082b2f7]::result::Result<(), rustc_span[5e1e12958345f30f]::ErrorGuaranteed>>::{closure#0}::{closure#0}
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_interface/src/util.rs:152:38
  71:     0x7f50b3677832 - std[86ab35e6a6527d40]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[a109d3959576535b]::util::run_in_thread_pool_with_globals<rustc_interface[a109d3959576535b]::interface::run_compiler<core[56d2be079082b2f7]::result::Result<(), rustc_span[5e1e12958345f30f]::ErrorGuaranteed>, rustc_driver_impl[53cfb4cfe592b1cc]::run_compiler::{closure#1}>::{closure#0}, core[56d2be079082b2f7]::result::Result<(), rustc_span[5e1e12958345f30f]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[56d2be079082b2f7]::result::Result<(), rustc_span[5e1e12958345f30f]::ErrorGuaranteed>>
                               at /home/matthias/vcs/github/rust_debug_assertions/library/std/src/sys_common/backtrace.rs:134:18
  72:     0x7f50b367b6b1 - <std[86ab35e6a6527d40]::thread::Builder>::spawn_unchecked_::<rustc_interface[a109d3959576535b]::util::run_in_thread_pool_with_globals<rustc_interface[a109d3959576535b]::interface::run_compiler<core[56d2be079082b2f7]::result::Result<(), rustc_span[5e1e12958345f30f]::ErrorGuaranteed>, rustc_driver_impl[53cfb4cfe592b1cc]::run_compiler::{closure#1}>::{closure#0}, core[56d2be079082b2f7]::result::Result<(), rustc_span[5e1e12958345f30f]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[56d2be079082b2f7]::result::Result<(), rustc_span[5e1e12958345f30f]::ErrorGuaranteed>>::{closure#1}::{closure#0}
                               at /home/matthias/vcs/github/rust_debug_assertions/library/std/src/thread/mod.rs:525:17
  73:     0x7f50b367b6b1 - <core[56d2be079082b2f7]::panic::unwind_safe::AssertUnwindSafe<<std[86ab35e6a6527d40]::thread::Builder>::spawn_unchecked_<rustc_interface[a109d3959576535b]::util::run_in_thread_pool_with_globals<rustc_interface[a109d3959576535b]::interface::run_compiler<core[56d2be079082b2f7]::result::Result<(), rustc_span[5e1e12958345f30f]::ErrorGuaranteed>, rustc_driver_impl[53cfb4cfe592b1cc]::run_compiler::{closure#1}>::{closure#0}, core[56d2be079082b2f7]::result::Result<(), rustc_span[5e1e12958345f30f]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[56d2be079082b2f7]::result::Result<(), rustc_span[5e1e12958345f30f]::ErrorGuaranteed>>::{closure#1}::{closure#0}> as core[56d2be079082b2f7]::ops::function::FnOnce<()>>::call_once
                               at /home/matthias/vcs/github/rust_debug_assertions/library/core/src/panic/unwind_safe.rs:271:9
  74:     0x7f50b367b6b1 - std[86ab35e6a6527d40]::panicking::try::do_call::<core[56d2be079082b2f7]::panic::unwind_safe::AssertUnwindSafe<<std[86ab35e6a6527d40]::thread::Builder>::spawn_unchecked_<rustc_interface[a109d3959576535b]::util::run_in_thread_pool_with_globals<rustc_interface[a109d3959576535b]::interface::run_compiler<core[56d2be079082b2f7]::result::Result<(), rustc_span[5e1e12958345f30f]::ErrorGuaranteed>, rustc_driver_impl[53cfb4cfe592b1cc]::run_compiler::{closure#1}>::{closure#0}, core[56d2be079082b2f7]::result::Result<(), rustc_span[5e1e12958345f30f]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[56d2be079082b2f7]::result::Result<(), rustc_span[5e1e12958345f30f]::ErrorGuaranteed>>::{closure#1}::{closure#0}>, core[56d2be079082b2f7]::result::Result<(), rustc_span[5e1e12958345f30f]::ErrorGuaranteed>>
                               at /home/matthias/vcs/github/rust_debug_assertions/library/std/src/panicking.rs:485:40
  75:     0x7f50b367b6b1 - std[86ab35e6a6527d40]::panicking::try::<core[56d2be079082b2f7]::result::Result<(), rustc_span[5e1e12958345f30f]::ErrorGuaranteed>, core[56d2be079082b2f7]::panic::unwind_safe::AssertUnwindSafe<<std[86ab35e6a6527d40]::thread::Builder>::spawn_unchecked_<rustc_interface[a109d3959576535b]::util::run_in_thread_pool_with_globals<rustc_interface[a109d3959576535b]::interface::run_compiler<core[56d2be079082b2f7]::result::Result<(), rustc_span[5e1e12958345f30f]::ErrorGuaranteed>, rustc_driver_impl[53cfb4cfe592b1cc]::run_compiler::{closure#1}>::{closure#0}, core[56d2be079082b2f7]::result::Result<(), rustc_span[5e1e12958345f30f]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[56d2be079082b2f7]::result::Result<(), rustc_span[5e1e12958345f30f]::ErrorGuaranteed>>::{closure#1}::{closure#0}>>
                               at /home/matthias/vcs/github/rust_debug_assertions/library/std/src/panicking.rs:449:19
  76:     0x7f50b367b6b1 - std[86ab35e6a6527d40]::panic::catch_unwind::<core[56d2be079082b2f7]::panic::unwind_safe::AssertUnwindSafe<<std[86ab35e6a6527d40]::thread::Builder>::spawn_unchecked_<rustc_interface[a109d3959576535b]::util::run_in_thread_pool_with_globals<rustc_interface[a109d3959576535b]::interface::run_compiler<core[56d2be079082b2f7]::result::Result<(), rustc_span[5e1e12958345f30f]::ErrorGuaranteed>, rustc_driver_impl[53cfb4cfe592b1cc]::run_compiler::{closure#1}>::{closure#0}, core[56d2be079082b2f7]::result::Result<(), rustc_span[5e1e12958345f30f]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[56d2be079082b2f7]::result::Result<(), rustc_span[5e1e12958345f30f]::ErrorGuaranteed>>::{closure#1}::{closure#0}>, core[56d2be079082b2f7]::result::Result<(), rustc_span[5e1e12958345f30f]::ErrorGuaranteed>>
                               at /home/matthias/vcs/github/rust_debug_assertions/library/std/src/panic.rs:140:14
  77:     0x7f50b367b6b1 - <std[86ab35e6a6527d40]::thread::Builder>::spawn_unchecked_::<rustc_interface[a109d3959576535b]::util::run_in_thread_pool_with_globals<rustc_interface[a109d3959576535b]::interface::run_compiler<core[56d2be079082b2f7]::result::Result<(), rustc_span[5e1e12958345f30f]::ErrorGuaranteed>, rustc_driver_impl[53cfb4cfe592b1cc]::run_compiler::{closure#1}>::{closure#0}, core[56d2be079082b2f7]::result::Result<(), rustc_span[5e1e12958345f30f]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[56d2be079082b2f7]::result::Result<(), rustc_span[5e1e12958345f30f]::ErrorGuaranteed>>::{closure#1}
                               at /home/matthias/vcs/github/rust_debug_assertions/library/std/src/thread/mod.rs:524:30
  78:     0x7f50b367b6b1 - <<std[86ab35e6a6527d40]::thread::Builder>::spawn_unchecked_<rustc_interface[a109d3959576535b]::util::run_in_thread_pool_with_globals<rustc_interface[a109d3959576535b]::interface::run_compiler<core[56d2be079082b2f7]::result::Result<(), rustc_span[5e1e12958345f30f]::ErrorGuaranteed>, rustc_driver_impl[53cfb4cfe592b1cc]::run_compiler::{closure#1}>::{closure#0}, core[56d2be079082b2f7]::result::Result<(), rustc_span[5e1e12958345f30f]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[56d2be079082b2f7]::result::Result<(), rustc_span[5e1e12958345f30f]::ErrorGuaranteed>>::{closure#1} as core[56d2be079082b2f7]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
                               at /home/matthias/vcs/github/rust_debug_assertions/library/core/src/ops/function.rs:250:5
  79:     0x7f50b0b381da - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h354d14dc16c7e009
                               at /home/matthias/vcs/github/rust_debug_assertions/library/alloc/src/boxed.rs:1976:9
  80:     0x7f50b0b381da - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h6252c296bff6789e
                               at /home/matthias/vcs/github/rust_debug_assertions/library/alloc/src/boxed.rs:1976:9
  81:     0x7f50b0b0b035 - std::sys::unix::thread::Thread::new::thread_start::hc92da0325fb0a23e
                               at /home/matthias/vcs/github/rust_debug_assertions/library/std/src/sys/unix/thread.rs:108:17
  82:     0x7f50b0c9ebb5 - <unknown>
  83:     0x7f50b0d20d90 - <unknown>
  84:                0x0 - <unknown>

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.70.0-dev running on x86_64-unknown-linux-gnu

note: compiler flags: -Z mir-opt-level=0

query stack during panic:
end of query stack
error: aborting due to previous error; 1 warning emitted
```

</p>
</details>

### LINKED ISSUE #110005: LLVM_ERROR: invalid bitcast: transmute
### Code

```Rust
fn main() {
    let x: Option<Box<[u8]>> = unsafe {
        let z = (0usize, true);
        std::mem::transmute::<(usize, bool), Option<Box<[u8]>>>(z)
    };
}
```

### Meta

`rustc --version --verbose`:
```
rustc 1.70.0-nightly (2eaeb1eee 2023-04-05)
binary: rustc
commit-hash: 2eaeb1eee1b21772de8b935236d16ff8e03fdcf5
commit-date: 2023-04-05
host: x86_64-unknown-linux-gnu
release: 1.70.0-nightly
LLVM version: 16.0.0
```

### Error output

```
<output>
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
warning: unused variable: `x`
 --> treereduce.out:2:9
  |
2 |     let x: Option<Box<[u8]>> = unsafe {
  |         ^ help: if this is intentional, prefix it with an underscore: `_x`
  |
  = note: `#[warn(unused_variables)]` on by default

Invalid bitcast
  %7 = bitcast i8 %6 to i64
in function _ZN10treereduce4main17haa15f44c7ccefff9E
LLVM ERROR: Broken function found, compilation aborted!
```

</p>
</details>

### LINKED ISSUE #110032: [ICE] Couldn't translate Aggregate { sized: true } as backend immediate
### Code

Code is too big, and the error too unspecific to upload to an issue, if necesary it could be uploaded to Github.

### Meta

`rustc --version --verbose`:
```
rustc 1.70.0-nightly (2036fdd24 2023-03-27)
binary: rustc
commit-hash: 2036fdd24f77d607dcfaa24c48fbe85d3f785823
commit-date: 2023-03-27
host: x86_64-unknown-linux-gnu
release: 1.70.0-nightly
LLVM version: 16.0.0
```

### Error output

```
[<output>](error: internal compiler error: /rustc/2eaeb1eee1b21772de8b935236d16ff8e03fdcf5/compiler/rustc_codegen_ssa/src/mir/rvalue.rs:892:22: Couldn't translate Aggregate { sized: true } as backend immediate)
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
thread 'rustc' panicked at 'Box<dyn Any>', /rustc/2eaeb1eee1b21772de8b935236d16ff8e03fdcf5/compiler/rustc_errors/src/lib.rs:1644:9
stack backtrace:
   0:     0x7f1cea42bf8a - std::backtrace_rs::backtrace::libunwind::trace::h543e5a71eb1b5eeb
                               at /rustc/2eaeb1eee1b21772de8b935236d16ff8e03fdcf5/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x7f1cea42bf8a - std::backtrace_rs::backtrace::trace_unsynchronized::h8798c87c5fd54c42
                               at /rustc/2eaeb1eee1b21772de8b935236d16ff8e03fdcf5/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7f1cea42bf8a - std::sys_common::backtrace::_print_fmt::h982e629a02833f3b
                               at /rustc/2eaeb1eee1b21772de8b935236d16ff8e03fdcf5/library/std/src/sys_common/backtrace.rs:65:5
   3:     0x7f1cea42bf8a - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hd16097abfc45a49a
                               at /rustc/2eaeb1eee1b21772de8b935236d16ff8e03fdcf5/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x7f1cea49004f - core::fmt::write::haccd80b41eab472e
                               at /rustc/2eaeb1eee1b21772de8b935236d16ff8e03fdcf5/library/core/src/fmt/mod.rs:1254:17
   5:     0x7f1cea41ebc5 - std::io::Write::write_fmt::h578b3def4330fd2b
                               at /rustc/2eaeb1eee1b21772de8b935236d16ff8e03fdcf5/library/std/src/io/mod.rs:1698:15
   6:     0x7f1cea42bd55 - std::sys_common::backtrace::_print::he237786f41276d1a
                               at /rustc/2eaeb1eee1b21772de8b935236d16ff8e03fdcf5/library/std/src/sys_common/backtrace.rs:47:5
   7:     0x7f1cea42bd55 - std::sys_common::backtrace::print::h504fa2bef175cc1e
                               at /rustc/2eaeb1eee1b21772de8b935236d16ff8e03fdcf5/library/std/src/sys_common/backtrace.rs:34:9
   8:     0x7f1cea42e9fe - std::panicking::default_hook::{{closure}}::hac9a65d5f66db25e
                               at /rustc/2eaeb1eee1b21772de8b935236d16ff8e03fdcf5/library/std/src/panicking.rs:269:22
   9:     0x7f1cea42e7a5 - std::panicking::default_hook::h4e334937c58bdca9
                               at /rustc/2eaeb1eee1b21772de8b935236d16ff8e03fdcf5/library/std/src/panicking.rs:288:9
  10:     0x7f1ced739635 - rustc_driver_impl[bd452c501c51eef0]::DEFAULT_HOOK::{closure#0}::{closure#0}
  11:     0x7f1cea42f1f4 - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h2c058cd2c0afd653
                               at /rustc/2eaeb1eee1b21772de8b935236d16ff8e03fdcf5/library/alloc/src/boxed.rs:1990:9
  12:     0x7f1cea42f1f4 - std::panicking::rust_panic_with_hook::h1fcbef96fdc6ec0c
                               at /rustc/2eaeb1eee1b21772de8b935236d16ff8e03fdcf5/library/std/src/panicking.rs:694:13
  13:     0x7f1cedc8bef1 - std[1137eeb067dcff5d]::panicking::begin_panic::<rustc_errors[b273ccddd230f82e]::ExplicitBug>::{closure#0}
  14:     0x7f1cedc87e06 - std[1137eeb067dcff5d]::sys_common::backtrace::__rust_end_short_backtrace::<std[1137eeb067dcff5d]::panicking::begin_panic<rustc_errors[b273ccddd230f82e]::ExplicitBug>::{closure#0}, !>
  15:     0x7f1cedc87d96 - std[1137eeb067dcff5d]::panicking::begin_panic::<rustc_errors[b273ccddd230f82e]::ExplicitBug>
  16:     0x7f1cedcdc876 - <rustc_errors[b273ccddd230f82e]::HandlerInner>::bug::<&alloc[facd9c3565c23052]::string::String>
  17:     0x7f1cedcdc540 - <rustc_errors[b273ccddd230f82e]::Handler>::bug::<&alloc[facd9c3565c23052]::string::String>
  18:     0x7f1cedcd5eab - rustc_middle[b98cfd31c7bf31fd]::util::bug::opt_span_bug_fmt::<rustc_span[b847b06bcddf9aef]::span_encoding::Span>::{closure#0}
  19:     0x7f1cedcd5a3a - rustc_middle[b98cfd31c7bf31fd]::ty::context::tls::with_opt::<rustc_middle[b98cfd31c7bf31fd]::util::bug::opt_span_bug_fmt<rustc_span[b847b06bcddf9aef]::span_encoding::Span>::{closure#0}, !>::{closure#0}
  20:     0x7f1cedcd5a06 - rustc_middle[b98cfd31c7bf31fd]::ty::context::tls::with_context_opt::<rustc_middle[b98cfd31c7bf31fd]::ty::context::tls::with_opt<rustc_middle[b98cfd31c7bf31fd]::util::bug::opt_span_bug_fmt<rustc_span[b847b06bcddf9aef]::span_encoding::Span>::{closure#0}, !>::{closure#0}, !>
  21:     0x7f1cedcd5df6 - rustc_middle[b98cfd31c7bf31fd]::util::bug::opt_span_bug_fmt::<rustc_span[b847b06bcddf9aef]::span_encoding::Span>
  22:     0x7f1ceb971033 - rustc_middle[b98cfd31c7bf31fd]::util::bug::bug_fmt
  23:     0x7f1cebf4debd - rustc_codegen_ssa[908d924d1a0e06ad]::mir::analyze::non_ssa_locals::<rustc_codegen_llvm[b01ba7ae6a55fff3]::builder::Builder>
  24:     0x7f1cebf1e967 - rustc_codegen_ssa[908d924d1a0e06ad]::mir::codegen_mir::<rustc_codegen_llvm[b01ba7ae6a55fff3]::builder::Builder>
  25:     0x7f1cecc858ee - rustc_codegen_llvm[b01ba7ae6a55fff3]::base::compile_codegen_unit::module_codegen
  26:     0x7f1cecc84ba6 - rustc_codegen_llvm[b01ba7ae6a55fff3]::base::compile_codegen_unit
  27:     0x7f1cecce2954 - rustc_codegen_ssa[908d924d1a0e06ad]::base::codegen_crate::<rustc_codegen_llvm[b01ba7ae6a55fff3]::LlvmCodegenBackend>
  28:     0x7f1cecce226a - <rustc_codegen_llvm[b01ba7ae6a55fff3]::LlvmCodegenBackend as rustc_codegen_ssa[908d924d1a0e06ad]::traits::backend::CodegenBackend>::codegen_crate
  29:     0x7f1cec98d202 - <rustc_session[8a142d07c6ec552f]::session::Session>::time::<alloc[facd9c3565c23052]::boxed::Box<dyn core[d2a11d220902df1]::any::Any>, rustc_interface[c7956fe9641ea70c]::passes::start_codegen::{closure#0}>
  30:     0x7f1cec98cccd - rustc_interface[c7956fe9641ea70c]::passes::start_codegen
  31:     0x7f1cec987c54 - <rustc_middle[b98cfd31c7bf31fd]::ty::context::GlobalCtxt>::enter::<<rustc_interface[c7956fe9641ea70c]::queries::Queries>::ongoing_codegen::{closure#0}::{closure#0}, core[d2a11d220902df1]::result::Result<alloc[facd9c3565c23052]::boxed::Box<dyn core[d2a11d220902df1]::any::Any>, rustc_span[b847b06bcddf9aef]::ErrorGuaranteed>>
  32:     0x7f1cec986028 - <rustc_interface[c7956fe9641ea70c]::queries::Queries>::ongoing_codegen
  33:     0x7f1cec985834 - <rustc_interface[c7956fe9641ea70c]::interface::Compiler>::enter::<rustc_driver_impl[bd452c501c51eef0]::run_compiler::{closure#1}::{closure#2}, core[d2a11d220902df1]::result::Result<core[d2a11d220902df1]::option::Option<rustc_interface[c7956fe9641ea70c]::queries::Linker>, rustc_span[b847b06bcddf9aef]::ErrorGuaranteed>>
  34:     0x7f1cec980ae1 - rustc_span[b847b06bcddf9aef]::set_source_map::<core[d2a11d220902df1]::result::Result<(), rustc_span[b847b06bcddf9aef]::ErrorGuaranteed>, rustc_interface[c7956fe9641ea70c]::interface::run_compiler<core[d2a11d220902df1]::result::Result<(), rustc_span[b847b06bcddf9aef]::ErrorGuaranteed>, rustc_driver_impl[bd452c501c51eef0]::run_compiler::{closure#1}>::{closure#0}::{closure#0}>
  35:     0x7f1cec98008f - std[1137eeb067dcff5d]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[c7956fe9641ea70c]::util::run_in_thread_pool_with_globals<rustc_interface[c7956fe9641ea70c]::interface::run_compiler<core[d2a11d220902df1]::result::Result<(), rustc_span[b847b06bcddf9aef]::ErrorGuaranteed>, rustc_driver_impl[bd452c501c51eef0]::run_compiler::{closure#1}>::{closure#0}, core[d2a11d220902df1]::result::Result<(), rustc_span[b847b06bcddf9aef]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[d2a11d220902df1]::result::Result<(), rustc_span[b847b06bcddf9aef]::ErrorGuaranteed>>
  36:     0x7f1cecfed8b1 - <<std[1137eeb067dcff5d]::thread::Builder>::spawn_unchecked_<rustc_interface[c7956fe9641ea70c]::util::run_in_thread_pool_with_globals<rustc_interface[c7956fe9641ea70c]::interface::run_compiler<core[d2a11d220902df1]::result::Result<(), rustc_span[b847b06bcddf9aef]::ErrorGuaranteed>, rustc_driver_impl[bd452c501c51eef0]::run_compiler::{closure#1}>::{closure#0}, core[d2a11d220902df1]::result::Result<(), rustc_span[b847b06bcddf9aef]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[d2a11d220902df1]::result::Result<(), rustc_span[b847b06bcddf9aef]::ErrorGuaranteed>>::{closure#1} as core[d2a11d220902df1]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  37:     0x7f1cea4392d5 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hcb3c543eabd3883a
                               at /rustc/2eaeb1eee1b21772de8b935236d16ff8e03fdcf5/library/alloc/src/boxed.rs:1976:9
  38:     0x7f1cea4392d5 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h4c6155c5f5f14f7d
                               at /rustc/2eaeb1eee1b21772de8b935236d16ff8e03fdcf5/library/alloc/src/boxed.rs:1976:9
  39:     0x7f1cea4392d5 - std::sys::unix::thread::Thread::new::thread_start::he5347f8288d9936e
                               at /rustc/2eaeb1eee1b21772de8b935236d16ff8e03fdcf5/library/std/src/sys/unix/thread.rs:108:17
  40:     0x7f1cea2f5609 - start_thread
                               at /build/glibc-SzIz7B/glibc-2.31/nptl/pthread_create.c:477:8
  41:     0x7f1cea218133 - clone
                               at /build/glibc-SzIz7B/glibc-2.31/misc/../sysdeps/unix/sysv/linux/x86_64/clone.S:95
  42:                0x0 - <unknown>

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.70.0-nightly (2eaeb1eee 2023-04-05) running on x86_64-unknown-linux-gnu

note: compiler flags: --crate-type bin -C opt-level=3 -C embed-bitcode=no -C debuginfo=2 -C link-arg=--nmagic -C link-arg=-Tlink.x -C link-arg=-Tlink-rp.x -C link-arg=-Tdefmt.x

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
```

</p>
</details>

### PR DESCRIPTION
**Pull request by scottmcm**
Check the sizes of the immediates, rather than the overall types, when deciding whether we can convert types without going through memory.

Fixes #110005
Fixes #109992
Fixes #110032
cc @matthiaskrgr

### CODE REVIEW

**Comment by scottmcm** [comment]
Oh, convenient, this accidentally made a repro of #109992 too 🙃

File: compiler/rustc_codegen_ssa/src/mir/rvalue.rs [hunk 1]
```diff
@@ -905,6 +923,21 @@ impl<'a, 'tcx, Bx: BuilderMethods<'a, 'tcx>> FunctionCx<'a, 'tcx, Bx> {
 #[derive(Debug, Copy, Clone)]
 enum OperandValueKind {
     Ref,
-    Immediate(abi::Scalar),
+    Immediate(ScalarOrZst),
```
Comment (compiler-errors) [inline compiler/rustc_codegen_ssa/src/mir/rvalue.rs:926]: I wonder if this is best represented as a separate as a different variant `OperandValueKind::Zst`?

File: compiler/rustc_codegen_ssa/src/mir/rvalue.rs [hunk 2]
```diff
@@ -202,8 +191,21 @@ impl<'a, 'tcx, Bx: BuilderMethods<'a, 'tcx>> FunctionCx<'a, 'tcx, Bx> {
...
+        // Check for transmutes that are always UB.
+        if operand.layout.size != cast.size
+            || operand.layout.abi.is_uninhabited()
+            || cast.abi.is_uninhabited()
+        {
+            if !operand.layout.abi.is_uninhabited() {
+                // Since this is known statically and the input could have existed
+                // without already having hit UB, might as well trap for it.
+                bx.abort();
+            }
```
[the remark this answers is not in the document]
Comment (scottmcm) [reply compiler/rustc_codegen_ssa/src/mir/rvalue.rs:203]: No, for the `abort` block I really do mean the input could have existed.

Basically, if we're transmuting `!` → `_` then there's no need to trap, since to get here they already did something UB.  Whereas for `()` → `!` this is also UB, but it's (in a sense) the "first" UB, so I figured it'd be worth trapping for, since it must always be dead code and thus if it's actually in the final binary detecting it seems plausibly helpful.

But then for all three UB cases -- size mismatch, impossible input, and impossible output -- I just return poison instead of bothering with figuring out bitcasts or whatever.

[the remark this answers is not in the document]
Comment (compiler-errors) [reply compiler/rustc_codegen_ssa/src/mir/rvalue.rs:203]: Oh actually, that clarification made me realize that I was reading this block totally wrong and that suggested refactor makes no sense, lol.

File: compiler/rustc_codegen_ssa/src/mir/rvalue.rs (hunk 1 above)
Comment (scottmcm) [reply compiler/rustc_codegen_ssa/src/mir/rvalue.rs:926]: I thought about that, but that loses the "same variants as `OperandValue`" property that I originally added this type for, as mentioned in the `value_kind` comments.

I think it's also a bit of a net loss in the places that lose it, since I need to look at it in pairs.  This form is nicer in `rvalue_creates_operand`, I'd say, rather than adding new arms for `ImmediateScalar`-and-`ImmediateZst` mismatches.

(Though I do wonder if maybe having a dedicated `OperandValue::Zst` could make sense, rather than [needing to pass around a useless `Bx::Value` for those cases](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_codegen_ssa/mir/operand/struct.OperandRef.html#method.new_zst) at all.)

Comment (compiler-errors) [reply compiler/rustc_codegen_ssa/src/mir/rvalue.rs:926]: are zst poisons a thing? that would be a reason to carry around a `Bx::Value` I guess?

File: compiler/rustc_codegen_ssa/src/mir/rvalue.rs [hunk 3]
```diff
@@ -222,10 +224,20 @@ impl<'a, 'tcx, Bx: BuilderMethods<'a, 'tcx>> FunctionCx<'a, 'tcx, Bx> {
                     bug!("Found {operand_kind:?} for operand {operand:?}");
                 };
                 if let OperandValueKind::Immediate(out_scalar) = cast_kind {
-                    let cast_bty = bx.backend_type(cast);
-                    Some(OperandValue::Immediate(Self::transmute_immediate(
-                        bx, imm, in_scalar, out_scalar, cast_bty,
-                    )))
+                    match (in_scalar, out_scalar) {
```
[the remark this answers is not in the document]
Comment (scottmcm) [reply compiler/rustc_codegen_ssa/src/mir/rvalue.rs:227]: I could certainly push the `OperandValueKind::Immediate` down to the two arms.

I'm not sure if I like it better, though, since it would makes the "these match" the arms are doing a bit less obvious.  How strongly do you feel about it?  Anything I missed that'd be a better layout?

File: compiler/rustc_codegen_ssa/src/mir/rvalue.rs (hunk 1 above)
Comment (scottmcm) [reply compiler/rustc_codegen_ssa/src/mir/rvalue.rs:926]: We certainly do pass around the `Bx::Value`s for them, but they also don't seem to end up [in even the `-C no-prepopulate-passes -Z mir-opt-level=0` IR](https://rust.godbolt.org/z/qWT6YvKjh), so 🤷

Comment (scottmcm) [reply compiler/rustc_codegen_ssa/src/mir/rvalue.rs:926]: Looks like they're a thing, because opt and llc at least don't complain about LLVM IR like `ret {} poison`: <https://llvm.godbolt.org/z/ccYYMKjYb> -- not that that's how we return ZSTs in Rust.

File: compiler/rustc_codegen_ssa/src/mir/rvalue.rs [hunk 4]
```diff
@@ -222,10 +224,20 @@ impl<'a, 'tcx, Bx: BuilderMethods<'a, 'tcx>> FunctionCx<'a, 'tcx, Bx> {
...
+                        (ScalarOrZst::Zst, ScalarOrZst::Zst) => {
+                            Some(OperandRef::new_zst(bx, cast).val)
+                        }
+                        (ScalarOrZst::Scalar(in_scalar), ScalarOrZst::Scalar(out_scalar))
+                            if in_scalar.size(self.cx) == out_scalar.size(self.cx) =>
```
Comment (WaffleLapkin) [inline compiler/rustc_codegen_ssa/src/mir/rvalue.rs:232]: Why is this check necessary?

For pairs you need to check the inner size because matching size of the whole pair doesn't necessarily imply matching sizes of elements... But surely the `operand.layout.size != cast.size` check is sufficient for scalars? 🤔

File: tests/codegen/intrinsics/transmute.rs [hunk 5]
```diff
@@ -301,3 +327,65 @@ pub unsafe fn check_pair_to_array(x: (i64, u64)) -> [u8; 16] {
     // CHECK: store i64 %x.1, ptr %{{.+}}, align 1
     transmute(x)
 }
+
+// CHECK-LABEL: @check_heterogeneous_integer_pair(
+#[no_mangle]
+pub unsafe fn check_heterogeneous_integer_pair(x: (i32, bool)) -> (bool, u32) {
```
Comment (WaffleLapkin) [inline tests/codegen/intrinsics/transmute.rs:333]: What are the `store`s at the start of `check_heterogeneous_integer_pair`, `check_heterogeneous_float_pair` and `check_issue_110005`? From reading [LLVM LangRef](https://llvm.org/docs/LangRef.html#store-instruction) it looks like `store` is supposed to take a value and a pointer, but these only take values?...

I can't quite understand what is written here...

Comment (scottmcm) [reply tests/codegen/intrinsics/transmute.rs:333]: The actual IR looks like this:
```llvm
define { float, double } @check_heterogeneous_float_pair(double noundef %x.0, float noundef %x.1) unnamed_addr #0 {
start:
  %0 = alloca { float, double }, align 8
  %1 = getelementptr inbounds { double, float }, ptr %0, i32 0, i32 0
  store double %x.0, ptr %1, align 8
  %2 = getelementptr inbounds { double, float }, ptr %0, i32 0, i32 1
  store float %x.1, ptr %2, align 8
  %3 = getelementptr inbounds { float, double }, ptr %0, i32 0, i32 0
  %4 = load float, ptr %3, align 8, !noundef !1
  %5 = getelementptr inbounds { float, double }, ptr %0, i32 0, i32 1
  %6 = load double, ptr %5, align 8, !noundef !1
  %7 = insertvalue { float, double } poison, float %4, 0
  %8 = insertvalue { float, double } %7, double %6, 1
  ret { float, double } %8
}
```
But the `CHECK` lines don't need to match the whole thing.

I wrote the test as a "what I really want to see is that it's loading/storing them", and didn't bother putting all the GEPing in the `CHECK`s since that would just clutter things up more.

File: compiler/rustc_codegen_ssa/src/mir/rvalue.rs (hunk 4 above)
Comment (scottmcm) [reply compiler/rustc_codegen_ssa/src/mir/rvalue.rs:232]: Oh, good call.  Let me give that a shot -- might allow deleting more code too...

Comment (scottmcm) [reply compiler/rustc_codegen_ssa/src/mir/rvalue.rs]: Removed this check, but `ScalarOrZst::size` is still needed elsewhere, so I couldn't remove more than that.

Comment (scottmcm) [reply compiler/rustc_codegen_ssa/src/mir/rvalue.rs:232]: Oh, no, vectors.  Without this check `<4 x i64>` to `<8 x f32>` trips the later debug-assert.

I suppose I could hypothetically `bitcast` that anyway, but I'm not doing that this PR.

Added some codegen tests for vectors so that when future me breaks this while running `--keep-stage-std` again, I'll notice without CI 😬

**Review by compiler-errors — APPROVED** [review]

**Comment by compiler-errors** [comment]
r=me

**Comment by scottmcm** [comment]
I'd forgotten I made that test file only-64bit instead of my usual only-x86_64 🤦 

@bors r=compiler-errors
