### PR TITLE
Issue error when -C link-self-contained option is used on unsupported platforms

### LINKED ISSUE #103576: -C self-contained=yes creates programs that crash on startup (on linux-gnu targets)
Compiling and running a "hello world" with the `-C self-contained=yes` option on `x64_64-unknown-linux-gnu` results in:
```
$ cat hello.rs 
fn main() {
    println!("Hello World!");
}
$ rustc hello.rs -C link-self-contained=yes
$ ./hello 
Segmentation fault (core dumped)
```
This happens with any rust version I tried, in particular `rustc 1.64.0 (a55dd71d5 2022-09-19)`.

Looking into more details reveals:
```
$ RUSTC_LOG=rustc_codegen_ssa::back::link=info rustc hello.rs -C link-self-contained=yes
[...]
 INFO rustc_codegen_ssa::back::link linker stderr:
/usr/bin/ld: warning: cannot find entry symbol _start; defaulting to 0000000000000320
```

So what appears to happen is that there are no startup objects available in self-contained mode for the target, therefore no startup objects participate in the link command, and therefore the entry point symbol in the final ELF executable is set to some random address, causing the crash on startup.

Now, the RELEASES.md file states that `link-self-contained` is not supported on linux-gnu (glibc) targets.  I assume this is still true (the "normal" documentation apparently doesn't say)?

Even so, I guess it would still be much preferable to issue an error (or even just ignore the option), rather than silently creating broken binaries.

### PR DESCRIPTION
**Pull request by StackDoubleFlow**
The documentation was also updated to reflect this.

I'm assuming the supported platforms are the same as initially written in [RELEASES.md](https://github.com/rust-lang/rust/blob/master/RELEASES.md#compiler-17).

Fixes #103576

### CODE REVIEW

File: compiler/rustc_codegen_ssa/src/back/link.rs [hunk 1]
```diff
@@ -1582,6 +1582,17 @@ fn detect_self_contained_mingw(sess: &Session) -> bool {
...
 fn self_contained(sess: &Session, crate_type: CrateType) -> bool {
     if let Some(self_contained) = sess.opts.cg.link_self_contained {
+        if self_contained {
+            let supported = match (&*sess.target.os, &*sess.target.env) {
+                ("windows", "gnu") => true,
+                ("linux", "musl") => true,
+                ("wasi", _) => true,
+                _ => false,
+            };
+            if !supported {
```
Comment (petrochenkov) [inline compiler/rustc_codegen_ssa/src/back/link.rs:1592]:
```suggestion
            if sess.target.link_self_contained == LinkSelfContainedDefault::False {
```
I think you can currently just use this condition instead of specifying the targets explicitly.

Also it makes sense to prohibit `-Clink-self-contained=false` too for unsupported targets.

File: compiler/rustc_error_messages/locales/en-US/codegen_ssa.ftl [hunk 2]
```diff
@@ -182,3 +182,5 @@ codegen_ssa_extract_bundled_libs_write_file = failed to write file '{$rlib}': {$
 codegen_ssa_unsupported_arch = unsupported arch `{$arch}` for os `{$os}`
 
 codegen_ssa_apple_sdk_error_sdk_path = failed to get {$sdk_name} SDK path: {error}
+
+codegen_ssa_unsupported_link_self_contained = option `-C link-self-contained` is not supported on this platform
```
Comment (petrochenkov) [inline compiler/rustc_error_messages/locales/en-US/codegen_ssa.ftl:186]:
```suggestion
codegen_ssa_unsupported_link_self_contained = option `-C link-self-contained` is not supported on this target
```

File: compiler/rustc_codegen_ssa/src/back/link.rs (hunk 1 above)
Comment (StackDoubleFlow) [reply compiler/rustc_codegen_ssa/src/back/link.rs:1592]: Checking for `LinkSelfContainedDefault::False` would currently exclude all `wasm32` targets, not just the `wasi` environment. Though, if we are already using self-contained link on all wasm targets by default, I guess that would mean it's supported on all wasm targets? If so, I should update the docs to show that.

In which scenario would we want to prohibit `-Clink-self-contained=false`?

Comment (petrochenkov) [reply compiler/rustc_codegen_ssa/src/back/link.rs:1592]: >In which scenario would we want to prohibit `-Clink-self-contained=false`?

`-Clink-self-contained` may become more fine-grained in the future (https://github.com/rust-lang/rust/pull/96884) and be supported for targets for which it's not nominally supported right now but for which we still ship some components (like libunwind for some targets).
So it's better to restrict it now if that's possible.

Comment (petrochenkov) [reply compiler/rustc_codegen_ssa/src/back/link.rs:1592]: >Checking for `LinkSelfContainedDefault::False` would currently exclude all `wasm32` targets, not just the `wasi` environment.

Could you move `link_self_contained: LinkSelfContainedDefault::True` from `compiler\rustc_target\src\spec\wasm_base.rs` to `compiler\rustc_target\src\spec\wasm32_wasi.rs` then?
(Next to the other self contained config options.)

That would be closer to the truth.

**Comment by petrochenkov** [comment]
Thanks!
r=me after squashing commits.
@rustbot author

File: compiler/rustc_target/src/spec/wasm_base.rs [hunk 3]
```diff
@@ -95,9 +94,6 @@ pub fn options() -> TargetOptions {
 
         pre_link_args,
 
-        // FIXME: Figure out cases in which WASM needs to link with a native toolchain.
-        link_self_contained: LinkSelfContainedDefault::True,
```
Comment (bjorn3) [inline compiler/rustc_target/src/spec/wasm_base.rs:99]: wasm32-unknown-unknown is always fully self contained. Both for linker and libraries. Why did you change it to no longer allow `-Clink-self-contained`?

Comment (StackDoubleFlow) [reply compiler/rustc_target/src/spec/wasm_base.rs:99]: It was previously said that a self contained build was only supported for the `wasi` environment [RELEASES.md](https://github.com/rust-lang/rust/blob/master/RELEASES.md#compiler-17), https://github.com/rust-lang/rust/pull/104137#discussion_r1020200709

Do we also support `-Clink-self-contained` for wasm32-unknown-emscripten?

Comment (bjorn3) [reply compiler/rustc_target/src/spec/wasm_base.rs:99]: `echo "fn main() {}" | rustc -Clink-self-contained=yes --target wasm32-unknown-unknown -` works just fine. I don't think `-Clink-self-contained=yes` has any effect though.

Comment (StackDoubleFlow) [reply compiler/rustc_target/src/spec/wasm_base.rs:99]: Shall I set `LinkSelfContainedDefault::True` in `wasm32_unknown_unknown.rs` then?

Comment (bjorn3) [reply compiler/rustc_target/src/spec/wasm_base.rs:99]: I think so. Probably same for wasm64-unknown-unknown.

**Comment by StackDoubleFlow** [comment]
This is no longer in queue

@rustbot ready

File: compiler/rustc_target/src/spec/wasm_base.rs (hunk 3 above)
Comment (petrochenkov) [reply compiler/rustc_target/src/spec/wasm_base.rs:99]: So my point in https://github.com/rust-lang/rust/pull/104137#discussion_r1020200709 was to allow `-Clink-self-contained` only when it's 1) supported 2) has any effect.

The second case is not true for wasm32/64 targets and for many other bare metal targets too, I guess.
It's unlikely that this option is currently used in practice with targets where it has no effect.

In theory, when https://github.com/rust-lang/rust/pull/96884 is implemented, `-Clink-self-contained` should start having an effect for these targets by enabling/disabling the shipped LLD.
So I wanted to prohibit `-Clink-self-contained` for as many targets as possible sooner, as a future-proofing measure.

Comment (bjorn3) [reply compiler/rustc_target/src/spec/wasm_base.rs:99]: Makes sense.

Comment (pnkfelix) [reply compiler/rustc_target/src/spec/wasm_base.rs:99]: Just as a heads up, it seems like `-Clink-self-contained` (especially its default value of "True" here) did have a meaningful (side-)effect for wasm32 (and presumably also wasm64): It caused the subsequent link step to include `-nostartfiles`, which we need on wasm32-unknown-unknown so that it will not attempt to link in `crt1.o` with other linkers like `clang`. See #108910 for more details.

Comment (pnkfelix) [reply compiler/rustc_target/src/spec/wasm_base.rs:99]: (also, @cuviper has [suggested on zulip](https://rust-lang.zulipchat.com/#narrow/stream/131828-t-compiler/topic/wasm.20custom.20linker.20breakage.20.23108910/near/340444726) that perhaps this example motivates a separate per-target flag for controlling whether we have crt objects.)

Comment (pnkfelix) [reply compiler/rustc_target/src/spec/wasm_base.rs:99]: (marking as unresolved to make this conversation easier to see while #108910 is open and others are skimming this to find connection with that issue.)
