### PR TITLE
fix weak memory bug in TLS on Windows

### LINKED ISSUE #123583: Miri sometimes reports memory leak in thread-local storage on *-pc-windows-gnu
I've only seen this [once](https://github.com/rust-lang/rust/actions/runs/8583356399/job/23522466884), even though the test should be covered by miri-test-libstd every day:
```
  error: memory leaked: alloc26870878 (Rust heap, size: 8, align: 4), allocated here:
  Error:     --> /checkout/library/alloc/src/alloc.rs:100:9
       |
  100  |         __rust_alloc(layout.size(), layout.align())
       |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
       |
       = note: BACKTRACE:
       = note: inside `realstd::alloc::alloc` at /checkout/library/alloc/src/alloc.rs:100:9: 100:52
       = note: inside `realstd::alloc::Global::alloc_impl` at /checkout/library/alloc/src/alloc.rs:183:73: 183:86
       = note: inside `<realstd::alloc::Global as core::alloc::Allocator>::allocate` at /checkout/library/alloc/src/alloc.rs:243:9: 243:39
       = note: inside `alloc_crate::alloc::exchange_malloc` at /checkout/library/alloc/src/alloc.rs:332:11: 332:34
       = note: inside `realstd::boxed::Box::<realstd::sys::thread_local::os_local::Value<u8>>::new` at /checkout/library/alloc/src/boxed.rs:218:9: 218:20
       = note: inside `realstd::thread::local_impl::Key::<u8>::try_initialize::<{closure@/checkout/library/std/src/sys/thread_local/os_local.rs:28:27: 28:34}>` at /checkout/library/std/src/sys/thread_local/os_local.rs:145:37: 145:94
       = note: inside `realstd::thread::local_impl::Key::<u8>::get::<{closure@/checkout/library/std/src/sys/thread_local/os_local.rs:28:27: 28:34}>` at /checkout/library/std/src/sys/thread_local/os_local.rs:127:18: 127:43
  note: inside `sync::reentrant_lock::current_thread_unique_ptr::X::__getit`
      --> /checkout/library/std/src/sys/thread_local/os_local.rs:28:17
       |
  11   |   pub macro thread_local_inner {
       |   ----------------------------
       |   |
       |   in this expansion of `$crate::thread::local_impl::thread_local_inner!` (#2)
       |   in this expansion of `$crate::thread::local_impl::thread_local_inner!` (#3)
  ...
  28   | /                 __KEY.get(move || {
  29   | |                     if let $crate::option::Option::Some(init) = _init {
  30   | |                         if let $crate::option::Option::Some(value) = init.take() {
  31   | |                             return value;
  ...    |
  36   | |                     __init()
  37   | |                 })
       | |__________________^
  ...
  82   |               $crate::thread::local_impl::thread_local_inner!(@key $t, $($init)*);
       |               ------------------------------------------------------------------- in this macro invocation (#3)
       |
      ::: library/std/src/sync/reentrant_lock.rs:318:5
       |
  318  |       thread_local! { static X: u8 = const { 0 } }
       |       -------------------------------------------- in this macro invocation (#1)
       |
      ::: library/std/src/thread/local.rs:183:1
       |
  183  | / macro_rules! thread_local {
  184  | |     // empty (base case for the recursion)
  185  | |     () => {};
  ...    |
  193  | |         $crate::thread::local_impl::thread_local_inner!($(#[$attr])* $vis $name, $t, const $init);
       | |         ----------------------------------------------------------------------------------------- in this macro invocation (#2)
  ...    |
  205  | |     );
  206  | | }
       | |_- in this expansion of `thread_local!` (#1)
       = note: inside `realstd::thread::LocalKey::<u8>::try_with::<{closure@library/std/src/sync/reentrant_lock.rs:319:12: 319:15}, usize>` at /checkout/library/std/src/thread/local.rs:283:32: 283:50
       = note: inside `realstd::thread::LocalKey::<u8>::with::<{closure@library/std/src/sync/reentrant_lock.rs:319:12: 319:15}, usize>` at /checkout/library/std/src/thread/local.rs:260:9: 260:25
  note: inside `sync::reentrant_lock::current_thread_unique_ptr`
      --> library/std/src/sync/reentrant_lock.rs:319:5
       |
  319  |     X.with(|x| <*const _>::addr(x))
       |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  note: inside `sync::reentrant_lock::ReentrantLock::<()>::lock`
      --> library/std/src/sync/reentrant_lock.rs:184:27
       |
  184  |         let this_thread = current_thread_unique_ptr();
       |                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  note: inside `sync::reentrant_lock::tests::smoke`
      --> library/std/src/sync/reentrant_lock/tests.rs:10:17
       |
  10   |         let a = l.lock();
       |                 ^^^^^^^^
  note: inside closure
      --> library/std/src/sync/reentrant_lock/tests.rs:7:11
       |
  6    | #[test]
       | ------- in this procedural macro expansion
  7    | fn smoke() {
       |           ^
       |
      ::: /checkout/library/core/src/macros/mod.rs:1636:5
       |
  1636 |     pub macro test($item:item) {
       |     -------------- in this expansion of `#[test]`
```

Cc @joboet @m-ou-se @Amanieu

### PR DESCRIPTION
**Pull request by RalfJung**
We need to store the `key` *after* we register the dtor.

Now I hope there isn't also some other reason why we have to actually register the dtor last... @joboet is there a reason you picked this particular order in https://github.com/rust-lang/rust/pull/102655?

Fixes https://github.com/rust-lang/rust/issues/123583

### CODE REVIEW

**Comment by joboet** [comment]
Ah yes, this is clearly a bug.

> Now I hope there isn't also some other reason why we have to actually register the dtor last... @joboet is there a reason you picked this particular order in #102655?

There was: the destructor may be called as soon as it is registered so I wanted to make sure that the key was set at that point so that the `TlsGetValue` reads from a correct key.

You can fix this by skipping the TLS variable in `run_dtors` if the stored key is zero.

**Comment by RalfJung** [comment]
Ah, makes sense. And in the Miri testcase, we don't have a thread-exit racing with a key-init so we wouldn't hit this.

I have updated the code.

File: library/std/src/sys/pal/windows/thread_local_key.rs [hunk 1]
```diff
@@ -313,17 +319,25 @@ unsafe fn run_dtors() {
         // Use acquire ordering to observe key initialization.
         let mut cur = DTORS.load(Acquire);
         while !cur.is_null() {
-            let key = (*cur).key.load(Relaxed) - 1;
+            let pre_key = (*cur).key.load(Relaxed);
```
Comment (RalfJung) [inline library/std/src/sys/pal/windows/thread_local_key.rs:322]: Is it really worth making this `Relaxed`? If we make it `Acquire` then we're guaranteed to fully sync with the key's `init()` in case initialization completed, which seems much safer.

**Comment by RalfJung** [comment]
I extended the Miri test to also cover this, that triggered the bug immediately:
```rust
//! Regression test for <https://github.com/rust-lang/rust/issues/123583>.
use std::thread;

fn with_thread_local1() {
    thread_local! { static X: Box<u8> = Box::new(0); }
    X.with(|_x| {})
}


fn with_thread_local2() {
    thread_local! { static Y: Box<u8> = Box::new(0); }
    Y.with(|_y| {})
}

fn main() {
    // Here we have two threads racing on initializing the thread-local
    // and (on Windows without target_thread_local) adding it to the global dtor list.
    let t = thread::spawn(with_thread_local1);
    with_thread_local1();
    t.join().unwrap();

    // Here we have one thread running the destructors racing with another thread initializing a thread-local.
    // The second thread adds a destructor that could be picked up by the first thread.
    let t = thread::spawn(|| { /* immediately just run destructors */});
    with_thread_local2(); // initialize thread-local
    t.join().unwrap();
}
```

File: library/std/src/sys/pal/windows/thread_local_key.rs (hunk 1 above)
Comment (joboet) [reply library/std/src/sys/pal/windows/thread_local_key.rs:322]: With the new change, it has to be `Acquire` because we might observe key initialization through this load. Previously, `Relaxed` was fine since all registered `StaticKey`s in the list already had their key initialized.

Comment (RalfJung) [reply library/std/src/sys/pal/windows/thread_local_key.rs:322]: > we might observe key initialization through this load

Are you sure? There's still a release-acquire pair via registering the dtor and the picking up the dtor here, so `TlsAlloc` happens-before `TlsGetValue`.

Comment (joboet) [reply library/std/src/sys/pal/windows/thread_local_key.rs]: Yeah, right. Anyway, the `Acquire` here is fine.

**Comment by joboet** [comment]
Thank you very much, especially for the detailed comments!
@bors r+

**Comment by RalfJung** [comment]
The regression tests are being added on the Miri side in https://github.com/rust-lang/miri/pull/3501.
