### PR TITLE
Fix capture analysis for by-move closure bodies

### LINKED ISSUE #123251: `Unexpected initial operand type` with async closures and `FnOnce`
Something is still wrong w/ async call shims. I think I'm not doing the `FnOnce` transform correctly or something.

Putting this up so I don't forget about it, but I'll fix it.

```rust
#![feature(async_closure)]

#[inline(never)]
async fn call_once(x: impl async FnOnce()) {
    x().await
}

#[tokio::main]
async fn main() {
    let v = &1;
    call_once(async || {
        println!("{v}");
    }).await;
}
```

```
Unexpected initial operand type: expected *mut Coroutine(DefId(0:8 ~ playground[5acf]::main::{closure#0}::{closure#0}::{closure#0}), [i32, std::future::ResumeTy, (), (), CoroutineWitness(DefId(0:8 ~ playground[5acf]::main::{closure#0}::{closure#0}::{closure#0}), []), (&'{erased} i32,)]), found *mut Coroutine(DefId(0:8 ~ playground[5acf]::main::{closure#0}::{closure#0}::{closure#0}), [i32, std::future::ResumeTy, (), (), CoroutineWitness(DefId(0:8 ~ playground[5acf]::main::{closure#0}::{closure#0}::{closure#0}), []), (&'{erased} &'{erased} i32,)]).
```

### PR DESCRIPTION
**Pull request by compiler-errors**
The check we were doing to figure out if a coroutine was borrowing from its parent coroutine-closure was flat-out wrong -- a misunderstanding of mine of the way that `tcx.closure_captures` represents its captures.

Fixes #123251 (the miri/ui test I added should more than cover that issue)

r? @oli-obk -- I recognize that this PR may be underdocumented, so please ask me what I should explain further.

### CODE REVIEW

File: compiler/rustc_mir_transform/src/coroutine/by_move_body.rs [hunk 1]
```diff
@@ -26,36 +28,68 @@ impl<'tcx> MirPass<'tcx> for ByMoveBody {
...
+        let mut by_ref_fields = FxIndexSet::default();
+        for (idx, (coroutine_capture, parent_capture)) in tcx
+            .closure_captures(coroutine_def_id)
+            .iter()
+            // By construction we capture all the args first.
+            .skip(num_args)
+            .zip_eq(tcx.closure_captures(parent_def_id))
+            .enumerate()
+        {
+            // This argument is captured by-move from the parent closure, but by-ref
```
[the remark this answers is not in the document]
Comment (compiler-errors) [reply compiler/rustc_mir_transform/src/coroutine/by_move_body.rs:62]: Typo, "the upvar" is captured by-move

File: compiler/rustc_mir_transform/src/coroutine/by_move_body.rs [hunk 2]
```diff
@@ -59,41 +122,30 @@ impl<'tcx> MirPass<'tcx> for ByMoveBody {
...
             assert_eq!(coroutine_capture.place.ty(), parent_capture.place.ty());
         }
 
-        let by_move_coroutine_ty = Ty::new_coroutine(
-            tcx,
-            coroutine_def_id.to_def_id(),
-            ty::CoroutineArgs::new(
+        let by_move_coroutine_ty = tcx
+            .instantiate_bound_regions_with_erased(parent_closure_args.coroutine_closure_sig())
+            .to_coroutine_given_kind_and_upvars(
```
Comment (compiler-errors) [inline compiler/rustc_mir_transform/src/coroutine/by_move_body.rs:140]: Since we're already getting the parent `CoroutineClosure`, there's no need to manually construct a `Coroutine` from its parts. Just use the helper function that we already have for computing the `FnOnce`/by-move coroutine.

File: compiler/rustc_mir_transform/src/coroutine/by_move_body.rs [hunk 3]
```diff
@@ -1,7 +1,63 @@
-//! A MIR pass which duplicates a coroutine's body and removes any derefs which
-//! would be present for upvars that are taken by-ref. The result of which will
-//! be a coroutine body that takes all of its upvars by-move, and which we stash
-//! into the `CoroutineInfo` for all coroutines returned by coroutine-closures.
+//! This pass constructs a second closure body sufficient for `FnOnce`/`AsyncFnOnce`
```
Comment (compiler-errors) [inline compiler/rustc_mir_transform/src/coroutine/by_move_body.rs:1]: This is high-level motivation for this pass -- it's probably not as detailed as it could be, but it's a start.

**Comment by oli-obk** [comment]
r=me with CI happy on the documentation
