### PR TITLE
Fix jemalloc usage on OSX

### LINKED ISSUE #82423: jemalloc does not seem to be working for rustc on macos
jemalloc is supposed to be enabled on macos for rustc, but with all the testing I've done, it does not appear to work.  

Noted by Thom Chiovoloni on Zulip [here](https://zulip-archive.rust-lang.org/247081tcompilerperformance/01486UsinganonsystemallocatorforrustconmacOS.html), the jemalloc-sys crate prevents using unprefixed symbols [here](https://github.com/gnzlbg/jemallocator/blob/c27a859e98e3cb790dc269773d9da71a1e918458/jemalloc-sys/build.rs#L83-L89), which IIUC, means that it is building with symbols like `__rjem_malloc`, which AFAIK are never actually used.

If it indeed does not work, then I think it would be good to consider either looking into fixing it (which I suspect may not be easy), or stop building it on CI.

Tested with most recent nightly (`rustc 1.52.0-nightly (3e826bb11 2021-02-21)`) and master (a15f484b918a4533ad633ea903ccce82910af342).

### PR DESCRIPTION
**Pull request by sfackler**
Closes #82423

### CODE REVIEW

**Comment by sfackler** [comment]
cc @ehuss

**Comment by JohnTitor** [comment]
Failed in rollup: https://github.com/rust-lang/rust/pull/82790#issuecomment-791290632

@bors r- rollup=iffy

File: compiler/rustc/src/main.rs [hunk 1]
```diff
@@ -24,6 +24,20 @@ fn main() {
...
+        // the linker doesn't seem to consider ctors as "used" when statically
+        // linking, so we need to explicitly depend on the function.
+        #[cfg(target_os = "macos")]
+        {
+            extern "C" {
+                fn _rjem_je_zone_register();
+            }
+
+            #[used]
+            static _F7: unsafe extern "C" fn() = _rjem_je_zone_register();
```
Comment (sfackler) [inline compiler/rustc/src/main.rs:39]:
```suggestion
            static _F7: unsafe extern "C" fn() = _rjem_je_zone_register;
```

**Comment by sfackler** [comment]
Whoops

@bors r=pnkfelix

**Comment by ehuss** [comment]
I did some basic benchmarks, and it looks like this had a fairly significant improvement!  Thanks @sfackler!

cargo:
```
Benchmark #1: PATH=/Users/eric/.rustup/toolchains/nightly-x86_64-apple-darwin/bin:$PATH cargo build
  Time (mean ± σ):     66.658 s ±  0.394 s    [User: 299.565 s, System: 27.624 s]
  Range (min … max):   66.380 s … 66.937 s    2 runs

Benchmark #2: PATH=/Users/eric/.rustup/toolchains/nightly-2021-03-08-x86_64-apple-darwin/bin:$PATH cargo build
  Time (mean ± σ):     75.251 s ±  0.283 s    [User: 337.470 s, System: 28.521 s]
  Range (min … max):   75.051 s … 75.451 s    2 runs

Summary
  'PATH=/Users/eric/.rustup/toolchains/nightly-x86_64-apple-darwin/bin:$PATH cargo build' ran
    1.13 ± 0.01 times faster than 'PATH=/Users/eric/.rustup/toolchains/nightly-2021-03-08-x86_64-apple-darwin/bin:$PATH cargo build'
```

toml-rs:
```
Benchmark #1: PATH=/Users/eric/.rustup/toolchains/nightly-x86_64-apple-darwin/bin:$PATH cargo build
  Time (mean ± σ):      5.968 s ±  0.010 s    [User: 7.561 s, System: 0.493 s]
  Range (min … max):    5.961 s …  5.975 s    2 runs

Benchmark #2: PATH=/Users/eric/.rustup/toolchains/nightly-2021-03-08-x86_64-apple-darwin/bin:$PATH cargo build
  Time (mean ± σ):      6.777 s ±  0.049 s    [User: 8.598 s, System: 0.509 s]
  Range (min … max):    6.743 s …  6.812 s    2 runs

Summary
  'PATH=/Users/eric/.rustup/toolchains/nightly-x86_64-apple-darwin/bin:$PATH cargo build' ran
    1.14 ± 0.01 times faster than 'PATH=/Users/eric/.rustup/toolchains/nightly-2021-03-08-x86_64-apple-darwin/bin:$PATH cargo build'
```

ripgrep:
```
Benchmark #1: PATH=/Users/eric/.rustup/toolchains/nightly-x86_64-apple-darwin/bin:$PATH cargo build
  Time (mean ± σ):     19.493 s ±  0.057 s    [User: 126.485 s, System: 8.628 s]
  Range (min … max):   19.452 s … 19.533 s    2 runs

Benchmark #2: PATH=/Users/eric/.rustup/toolchains/nightly-2021-03-08-x86_64-apple-darwin/bin:$PATH cargo build
  Time (mean ± σ):     22.563 s ±  0.665 s    [User: 147.224 s, System: 9.124 s]
  Range (min … max):   22.093 s … 23.033 s    2 runs

Summary
  'PATH=/Users/eric/.rustup/toolchains/nightly-x86_64-apple-darwin/bin:$PATH cargo build' ran
    1.16 ± 0.03 times faster than 'PATH=/Users/eric/.rustup/toolchains/nightly-2021-03-08-x86_64-apple-darwin/bin:$PATH cargo build'
```
