### PR TITLE
const-eval: fix and re-enable pointer fragment support

### LINKED ISSUE #72: Full support for pointer fragments
These days, values of types like `MaybeUninit` are only ever represented in-memory in the interpreter; they cannot be stored in a `Scalar`. Only integers (that never have provenance) and pointers (that always have a single well-defined provenance) can exist as `Scalar`.

This does give us a chance to represent "partial pointers", so that we could support people writing *their own `memcpy` in const* that works by copying `MaybeUninit<u8>` in a loop. I don't know if there's any real usecase for this, but it seems neat. :D

The main challenge is that we have to ensure that when the bytes of a pointer get put back together, that they all appear in the right order. This is not a constraint that our current per-byte provenance system supports, and I doubt that we want to put such a constraint onto regular runtime semantics. We'd also have to report an error if such a pointer fragment byte makes it into the final value of a constant, since AFAIK we can't represent them in LLVM.

### LINKED ISSUE #147959: Consteval pointer fragment support was not properly disabled.
In https://github.com/rust-lang/rust/pull/144081/, pointer fragment support was enabled in consteval. Then, a bug was found in https://github.com/rust-lang/rust/issues/146291, so this support was supposedly then disabled in https://github.com/rust-lang/rust/pull/146324. However, it seems like this disabling was not done properly.

The below code is adapted from the previously-deleted test in https://github.com/rust-lang/rust/pull/144081/files#diff-7882729ad52694021ddccdd40fefa200d6d24ead1d586852eb4816bce32f2c6b

```rust
const PARTIAL_OVERWRITE: () = {
    let mut p = &42;
    unsafe {
        let ptr: *mut _ = &mut p;
        *(ptr as *mut u8) = 123;
    }
};
```

This code compiles in beta, but gives the following error in stable:
```
error[E0080]: unable to overwrite parts of a pointer in memory at alloc4
 --> src/lib.rs:5:9
  |
5 |         *(ptr as *mut u8) = 123;
  |         ^^^^^^^^^^^^^^^^^^^^^^^ evaluation of `PARTIAL_OVERWRITE` failed here
  |
  = help: this code performed an operation that depends on the underlying bytes representing a pointer
  = help: the absolute address of a pointer is not known at compile-time, so such operations are not supported

For more information about this error, try `rustc --explain E0080`.
```

I am unable to reproduce the bug in https://github.com/rust-lang/rust/issues/146291, but I still find it worrisome that new code was newly allowed seemingly unintentionally.

Is this operation intended to be supported in consteval?

cc @RalfJung 

### Meta

Tested on the playground with versions `1.91.0-beta.9 (2025-10-17 1f251978870710eb72e9)` and `1.90.0`

### PR DESCRIPTION
**Pull request by RalfJung**
The pointer fragment support from https://github.com/rust-lang/rust/pull/144081 got disabled due to https://github.com/rust-lang/rust/issues/146291. This brings it back. To fix the issue, the per-byte provenance fragment tracking tracks *both* the provenance and raw address of the full pointer, so we can ensure that only fragments that are truly part of the same pointer are being merged.

r? @oli-obk 
Cc @theemathas 
Fixes https://github.com/rust-lang/const-eval/issues/72 again.
Also fixes https://github.com/rust-lang/rust/issues/147959.

@traviscross I assume this won't need another t-lang FCP since it already got FCP'd in rust-lang/rust#144081?

### CODE REVIEW

**Comment by traviscross** [comment]
This seems right to me.  I propose we restabilize this.

@rfcbot fcp merge

File: compiler/rustc_middle/src/mir/interpret/allocation/provenance_map.rs [hunk 1]
```diff
@@ -107,18 +119,12 @@ impl<Prov: Provenance> ProvenanceMap<Prov> {
...
-            debug_assert!(self.bytes.as_ref().is_none_or(|b| !b.contains_key(&offset)));
-            Some((entry.1, (offset - entry.0).bytes() as u8))
-        } else {
-            // Look up per-byte provenance.
-            self.bytes.as_ref().and_then(|b| b.get(&offset).copied())
-        }
+    /// Get the provenance of a single byte. Must only be called if there is no
+    /// pointer-sized provenance here.
+    pub fn get_byte(&self, offset: Size, cx: &impl HasDataLayout) -> Option<&PointerFrag<Prov>> {
+        debug_assert!(self.range_ptrs_get(alloc_range(offset, Size::from_bytes(1)), cx).is_empty());
```
Comment (RalfJung) [inline compiler/rustc_middle/src/mir/interpret/allocation/provenance_map.rs]: Actually this isn't right, we can hit this assertion...

File: compiler/rustc_middle/src/mir/interpret/pointer.rs [hunk 2]
```diff
@@ -77,9 +77,6 @@ pub trait Provenance: Copy + PartialEq + fmt::Debug + 'static {
     /// Otherwise this function is best-effort (but must agree with `Machine::ptr_get_alloc`).
     /// (Identifying the offset in that allocation, however, is harder -- use `Memory::ptr_get_alloc` for that.)
     fn get_alloc_id(self) -> Option<AllocId>;
-
-    /// Defines the 'join' of provenance: what happens when doing a pointer load and different bytes have different provenance.
-    fn join(left: Self, right: Self) -> Option<Self>;
```
Comment (RalfJung) [inline compiler/rustc_middle/src/mir/interpret/pointer.rs:82]: I'm getting rid of the join function because the code that used it anyway had to special-case wildcards, and then it became easier to just have the entire wildcard logic there rather than having some of it inside `join`.

File: compiler/rustc_const_eval/src/interpret/memory.rs [hunk 3]
```diff
@@ -1502,10 +1502,7 @@ impl<'tcx, M: Machine<'tcx>> InterpCx<'tcx, M> {
         // `get_bytes_mut` will clear the provenance, which is correct,
         // since we don't want to keep any provenance at the target.
         // This will also error if copying partial provenance is not supported.
```
Comment (theemathas) [inline compiler/rustc_const_eval/src/interpret/memory.rs]: Is this comment outdated?

**Comment by theemathas** [comment]
Do we need tests for https://github.com/rust-lang/rust/issues/147959?

**Comment by RalfJung** [comment]
> Do we need tests for #147959?

Good point, I added that.

File: compiler/rustc_middle/src/mir/interpret/allocation/provenance_map.rs [hunk 4]
```diff
@@ -11,7 +11,22 @@ use rustc_serialize::{Decodable, Decoder, Encodable, Encoder};
...
+
+/// A pointer fragment represents one byte of a pointer.
+/// If the bytes are re-assembled in their original order, the pointer can be used again.
+/// Wildcard provenance is allowed to have index 0 everywhere.
+#[derive(Clone, PartialEq, Eq, Hash, Debug)]
+#[derive(HashStable)]
+pub struct PointerFrag<Prov> {
+    /// The position of this fragment inside the pointer (in `0..8`).
+    pub idx: u8,
+    /// The pointer this is a fragment of: provenance and the "real" raw bytes.
```
Comment (oli-obk) [inline compiler/rustc_middle/src/mir/interpret/allocation/provenance_map.rs]: the real raw bytes are in the next field, not in the prov field.

Comment (RalfJung) [reply compiler/rustc_middle/src/mir/interpret/allocation/provenance_map.rs]: True. I wasn't sure how to best write a comment that spans both fields. I'm open to suggestions.

**Comment by RalfJung** [comment]
I don't understand what you think the issue is, that all sounds as expected. If the padding ends up containing a partial pointer, we error. Your different variants correspond to having a partial pointer in padding that then gets removed if we clear padding, and having a pointer in the type that is made partial when clearing pattern -- that's why `-Zextra-const-ub-checks` can both add and remove errors.

It is unfortunate that partial pointers in padding stop compilation, but since our memory is untyped, by the time we check for partial pointers, it is not always possible to know whether this is padding or not.

**Comment by RalfJung** [comment]
It's admittedly confusing. We could have a more elaborate pointer fragment merging algorithm that takes into account uninitialized memory. I'm not convinced that is worth blocking this PR over. It's a nightly-only flag after all.

File: compiler/rustc_middle/src/mir/interpret/allocation/provenance_map.rs (hunk 4 above)
Comment (oli-obk) [reply compiler/rustc_middle/src/mir/interpret/allocation/provenance_map.rs]: I would just document each field individually.
```suggestion
    /// The provenance of the pointer this is a fragment of
```

File: compiler/rustc_middle/src/mir/interpret/allocation/provenance_map.rs [hunk 5]
```diff
@@ -107,68 +122,128 @@ impl<Prov: Provenance> ProvenanceMap<Prov> {
...
+                    None => {
+                        expected = Some((frag.prov, frag.bytes));
+                    }
+                }
+            }
+            // The final provenance is the expected one we found along the way, or wildcard if
+            // we didn't find any.
+            break 'prov Some(
+                expected.map(|(prov, _addr)| prov).or_else(|| Prov::WILDCARD).unwrap(),
+            );
```
Comment (oli-obk) [inline compiler/rustc_middle/src/mir/interpret/allocation/provenance_map.rs]:
```suggestion
            Some(
                expected.map(|(prov, _addr)| prov).or_else(|| Prov::WILDCARD).unwrap(),
            )
```

**Review by oli-obk — APPROVED** [review]
r=me with FCP finished

*[View changes since this review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/rust/148259/53efb3d4f3b67d189a0c72eb475a52017d79d609..07d183523dcea4d2abadc290ff044dadbb03f10d)*

**Comment by RalfJung** [comment]
@oli-obk I have added a commit to reduce the impact of https://github.com/rust-lang/rust/issues/148470, so this needs another review I am afraid.

**Comment by RalfJung** [comment]
@bors try
@rust-timer queue

File: compiler/rustc_const_eval/src/interpret/place.rs [hunk 6]
```diff
@@ -714,23 +715,31 @@ where
...
+                let BackendRepr::ScalarPair(_a, b) = layout.backend_repr else {
                     span_bug!(
                         self.cur_span(),
                         "write_immediate_to_mplace: invalid ScalarPair layout: {:#?}",
                         layout
                     )
                 };
-                let b_offset = a.size(&tcx).align_to(b.align(&tcx).abi);
+                let a_size = a_val.size();
+                let b_offset = a_size.align_to(b.align(&tcx).abi);
```
Comment (oli-obk) [inline compiler/rustc_const_eval/src/interpret/place.rs:726]: Can the alignment also be loaded from b_val?

Comment (RalfJung) [reply compiler/rustc_const_eval/src/interpret/place.rs:726]: No. Scalar values know their size, but they don't have an alignment since they don't exist in memory.

**Review by oli-obk — APPROVED** [review]
