### PR TITLE
Make `x test tests` work

### LINKED ISSUE #97314: `x.py test tests/` doesn't work
If you try to do `./x.py test src/test`, it doesn't work:

```
./x.py test --stage 1 src/test/ --bless
Updating only changed submodules
  Submodules updated in 0.01 seconds
Building rustbuild
    Finished dev [unoptimized] target(s) in 0.14s
error: no `test` rules matched 'src/test/'
help: run `x.py test --help --verbose` to show a list of available paths
note: if you are adding a new Step to bootstrap itself, make sure you register it with `describe!`
Build completed unsuccessfully in 0:00:00
``` 

Same goes for `x.py test compiler` and `x.py test library`.

@rustbot label A-rustbuild

### PR DESCRIPTION
**Pull request by clubby789**
Fixes #97314

This makes `x test tests` work, and be roughly equivalent to `x test tests/*`. The `--dry-run` output is identical, except for errors on the non-test items in `tests` and a couple of things being in a different order (where path != struct name).

This probably needs a test, but I'm not sure of the best way to do it.

### CODE REVIEW

**Comment by clubby789** [comment]
Whoops, left over commit from something else

**Review by onur-ozkan — COMMENTED** [review]
I think we can make this work without adding a fake build step by improving the path remapping in builder.rs:

https://github.com/rust-lang/rust/blob/0987e41d1ccbae7a8a55fdcde4af0ea76ebfe2d3/src/bootstrap/src/core/builder.rs#L291-L301

File: src/bootstrap/src/core/builder.rs [hunk 1]
```diff
@@ -288,16 +288,61 @@ impl PathSet {
...
+    for (i, path) in paths
+        .iter()
+        .enumerate()
+        .filter_map(|(i, path)| if let Some(s) = path.to_str() { Some((i, s)) } else { None })
+    {
         for &(search, replace) in PATH_REMAP {
-            if path.to_str() == Some(search) {
-                *path = Path::new(replace)
+            // Remove leading and trailing slashes so `tests/` and `tests` are equivalent
+            if path.trim_matches(std::path::is_separator) == search {
```
Comment (clubby789) [inline src/bootstrap/src/core/builder.rs:333]: Different shells can tab-complete a folder name with or without a trailing slash so hopefully this can handle both

**Review by onur-ozkan — APPROVED** [review]
Thanks!

File: src/bootstrap/src/core/builder.rs [hunk 2]
```diff
@@ -288,16 +288,61 @@ impl PathSet {
...
+const PATH_REMAP: &[(&str, &[&str])] = &[
+    // config.toml uses `rust-analyzer-proc-macro-srv`, but the
+    // actual path is `proc-macro-srv-cli`
+    ("rust-analyzer-proc-macro-srv", &["proc-macro-srv-cli"]),
+    // Make `x test tests` function the same as `x t tests/*`
+    (
+        "tests",
+        &[
+            "tests/assembly",
+            "tests/codegen",
```
Comment (klensy) [inline src/bootstrap/src/core/builder.rs:300]: Nothing can go wrong with hardcoded paths.

Comment (klensy) [reply src/bootstrap/src/core/builder.rs:300]: Maybe collects folders in /tests at runtime and assert that lists equal (excluding `auxiliary`)?

Comment (onur-ozkan) [reply src/bootstrap/src/core/builder.rs:300]: We have a test for checking the existance paths. Seems like we need to test for missing paths too.

Comment (onur-ozkan) [reply src/bootstrap/src/core/builder.rs:300]: > We have a test for checking the existance paths. Seems like we need a test for missing paths too.

Here it is: https://github.com/rust-lang/rust/pull/124969
