### PR TITLE
Recover from where clauses placed before tuple struct bodies

### LINKED ISSUE #100790: Bad generic error for incorrectly placed `where` clause for tuple struct
Given the following code: [[playground]](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=4dc80bbbe0a909a632ad92055ffba8df)

```rust
struct Example
where
    (): Sized,
(usize);
```

The current output is:

```
error: expected one of `:`, `==`, or `=`, found `;`
 --> src/lib.rs:4:8
  |
4 | (usize);
  |        ^ expected one of `:`, `==`, or `=`
```

What appears to be happening is that we're trying to parse this as a unit struct (which *can* have a `where` clause), and thus trying to parse the struct tuple as a type to bound.

With a tuple visibility:

```rust
struct Example
where
    (): Sized,
(pub usize, usize);
```

```
error: expected type, found keyword `pub`
 --> src/lib.rs:4:2
  |
4 | (pub usize, usize);
  |  ^^^ expected type
```

Ideally,

- In the former case (easier?) we can notice that we parsed a tuple type and then got `;` instead of `:` (or a currently-just-for-diagnostics `=`) and then reinterpret the tuple type as a tuple struct tuple, printing a more useful error;
- In the latter case (harder?) we would likely need to backtrack when seeing a `pub` visibility marker and retry to parse as a tuple struct definition tuple in order to provide the nicer error.

### PR DESCRIPTION
**Pull request by fmease**
Open to any suggestions regarding the phrasing of the diagnostic.

Fixes #100790.
@rustbot label A-diagnostics
r? diagnostics

### CODE REVIEW

File: compiler/rustc_parse/src/parser/generics.rs [hunk 1]
```diff
@@ -286,7 +304,77 @@ impl<'a> Parser<'a> {
                     },
                 ));
             } else if self.check_type() {
-                where_clause.predicates.push(self.parse_ty_where_predicate()?);
+                // Save the state of the parser before trying to parse a predicate, in case we fail
+                // and encounter something that looks like a misplaced tuple struct body allowing us
+                // to recover from it and fail with a more helpful diagnostic.
+                let parser_snapshot_before_type = self.clone();
```
Comment (fmease) [inline compiler/rustc_parse/src/parser/generics.rs:310]: Sadly, I have to clone the parser here even in the happy path incurring a performance cost.
Unsure how to avoid this. As far as I understand, we also do this when parsing `as` casts.
See:
https://github.com/rust-lang/rust/blob/7bbbaabbb6ec93800409478e2af7bc063701604b/compiler/rustc_parse/src/parser/expr.rs#L707

File: src/test/ui/parser/recover-where-clause-before-tuple-struct-body.stderr [hunk 2]
```diff
@@ -0,0 +1,51 @@
...
+LL | |     (): Sized,
+LL | |     String: Clone,
+   | |__________________^
+LL |   (pub usize, usize);
+   |   ------------------ the tuple struct body
+   |
+help: consider moving the where clause after the body
+   |
+LL - where
+LL + (pub usize, usize) where (): Sized, String: Clone;
```
Comment (fmease) [inline src/test/ui/parser/recover-where-clause-before-tuple-struct-body.stderr:29]: Personally, I am not a fan how this diff is rendered. In my eyes, it looks as if it's only the `where` keyword that needs to be replaced and as if the trait bounds are allowed to stay.
I would have expected it to like this (nested diff incoming):

```diff
- - where
- + (pub usize, usize) where (): Sized, String: Clone;
+ - where
+ -     (): Sized,
+ -     String: Clone,
+ + (pub usize, usize) where (): Sized, String: Clone;
```

I've double-checked that the span is correct by running `rustfix`, so it's only the rendering that's off.

File: compiler/rustc_parse/src/parser/generics.rs (hunk 1 above)
Comment (compiler-errors) [reply compiler/rustc_parse/src/parser/generics.rs:310]: I'm not sure the better diagnostics warrrants this complexity, but I guess we'll see what rust perf bot says.

Comment (estebank) [reply compiler/rustc_parse/src/parser/generics.rs:310]: You can make the snapshot creation conditional on checking `may_recover` and on `look_ahead(1, |t| t==OpenDelim(Paren))` so that we only pay the cost in those cases. There's also a method in the parser to create the snapshots, I think it's called `create_snapshot_for_diagnostic` (or something along that line) and another to replace `self`, please use those.

File: src/test/ui/parser/recover-where-clause-before-tuple-struct-body.stderr (hunk 2 above)
Comment (estebank) [reply src/test/ui/parser/recover-where-clause-before-tuple-struct-body.stderr:29]: File a ticket for it. It is definitely in the `Emitter`.

File: src/test/ui/parser/recover-where-clause-before-tuple-struct-body.stderr [hunk 3]
```diff
@@ -0,0 +1,51 @@
...
+LL | |     (): Sized,
+   | |______________^
+LL |   (usize);
+   |   ------- the tuple struct body
+   |
+help: consider moving the where clause after the body
+   |
+LL - where
+LL + (usize) where (): Sized;
+   |
```
Comment (estebank) [inline src/test/ui/parser/recover-where-clause-before-tuple-struct-body.stderr:14]: Wouldn't it look better to suggest moving the `(Type)` right next to the struct ident?

Comment (estebank) [reply src/test/ui/parser/recover-where-clause-before-tuple-struct-body.stderr:14]: We should also have a secondary span pointing at the ident in the main diagnostic to provide enough context in the diagnostic to understand at a glance which type this is talking about.

Comment (fmease) [reply src/test/ui/parser/recover-where-clause-before-tuple-struct-body.stderr:14]: Good idea! I'm going to try that! :)

**Comment by fmease** [comment]
I hope my force-push (of a tiny superfluous change) does not disrupt the try-build & the timing procedure. I will try to implement Esteban's suggestion locally re the parser cloning.

**Comment by compiler-errors** [comment]
restarting try-build, @bors try

File: compiler/rustc_parse/src/parser/generics.rs [hunk 4]
```diff
@@ -286,7 +304,74 @@ impl<'a> Parser<'a> {
                     },
                 ));
             } else if self.check_type() {
-                where_clause.predicates.push(self.parse_ty_where_predicate()?);
+                // Save the state of the parser before trying to parse a predicate, in case we fail
```
Comment (estebank) [inline compiler/rustc_parse/src/parser/generics.rs:307]: Can we also move all in this block to its own function? Maybe `parse_ty_where_predicate_with_invalid_tuple_struct_recovery` or something :)

**Comment by fmease** [comment]
Sorry for the delay, I couldn't find time earlier.
@rustbot review

File: compiler/rustc_parse/src/parser/generics.rs [hunk 5]
```diff
@@ -310,8 +339,75 @@ impl<'a> Parser<'a> {
...
+                                WhereClauseBeforeTupleStructBodySugg {
+                                    left: body_insertion_point.shrink_to_hi(),
+                                    snippet: body,
+                                    right: map.end_point(where_sp).to(body_sp),
+                                }
+                            }),
+                        });
+
+                        self.restore_snapshot(snapshot);
+                        *tuple_struct_body = Some(body);
```
Comment (fmease) [inline compiler/rustc_parse/src/parser/generics.rs:399]: Instead of this out-parameter logic, I could use `either::Either` (after adding `either` as a dependency to `rustc_parse`).

File: src/test/ui/parser/recover-where-clause-before-tuple-struct-body.stderr [hunk 6]
```diff
@@ -0,0 +1,61 @@
...
+   | |______________^ unexpected where clause
+LL |   (usize);
+   |   ------- the struct body
+   |
+help: consider moving the body before the where clause
+   |
+LL ~ struct Example(usize)
+LL | where
+LL ~     (): Sized;
+   |
```
Comment (estebank) [inline src/test/ui/parser/recover-where-clause-before-tuple-struct-body.stderr:17]: Looks great!

File: compiler/rustc_error_messages/locales/en-US/parse.ftl [hunk 7]
```diff
@@ -368,3 +368,9 @@ parse_maybe_fn_typo_with_impl = you might have meant to write `impl` instead of
 
 parse_expected_fn_path_found_fn_keyword = expected identifier, found keyword `fn`
     .suggestion = use `Fn` to refer to the trait
+
+parse_where_clause_before_tuple_struct_body = where clauses are not allowed before tuple struct bodies
+    .label = unexpected where clause
+    .name_label = while parsing this tuple struct
+    .body_label = the struct body
+    .suggestion = consider moving the body before the where clause
```
Comment (estebank) [inline compiler/rustc_error_messages/locales/en-US/parse.ftl:376]: Let's be more forceful with the wording, there's nothing else the user might have meant, this is their only path forward.

```suggestion
    .suggestion = move the body before the where clause
```

File: src/test/ui/parser/recover-where-clause-before-tuple-struct-body.rs [hunk 8]
```diff
@@ -0,0 +1,18 @@
+// Regression test for issues #100790 and #106439.
```
Comment (estebank) [inline src/test/ui/parser/recover-where-clause-before-tuple-struct-body.rs:1]: Could this test be marked `// run-rustfix`? I'm not sure the missing `;` has a tool only suggestion, but otherwise this test seems like it could be checked for the suggestions keeping to apply cleanly.

File: compiler/rustc_parse/src/parser/generics.rs (hunk 5 above)
Comment (estebank) [reply compiler/rustc_parse/src/parser/generics.rs:399]: You can also create a new private `enum`.

File: compiler/rustc_parse/src/parser/generics.rs [hunk 9]
```diff
@@ -310,8 +339,75 @@ impl<'a> Parser<'a> {
...
+                        Ok(None)
+                    }
+                    result => {
+                        if let Err(body_err) = result {
+                            body_err.cancel();
+                        }
```
Comment (estebank) [inline compiler/rustc_parse/src/parser/generics.rs:405]: Isn't this the same?

```suggestion
                    Err(body_err) => {
                        body_err.cancel();
```

**Review by estebank — APPROVED** [review]
We very sparingly use out parameters in this codebase, but there are a couple of places we do. If you don't have the time to slightly rewrite things to use a new private enum and return the parsed body, then please add a comment in the definition of `typle_struct_body` and in `parse_ty_where_predicate_or_recover_tuple_struct_body`.

Left a few other nitpicks, but r=me after addressing them.

File: compiler/rustc_parse/src/parser/generics.rs (hunk 9 above)
Comment (fmease) [reply compiler/rustc_parse/src/parser/generics.rs:405]: It's not because of the guard `Ok(body) if /* heuristic */`. I admit it looks a bit awkward.

File: src/test/ui/parser/recover-where-clause-before-tuple-struct-body.rs (hunk 8 above)
Comment (fmease) [reply src/test/ui/parser/recover-where-clause-before-tuple-struct-body.rs:1]: Should I make the diagnostic *machine-applicable*, too? It currently is *maybe-incorrect*.

Comment (estebank) [reply src/test/ui/parser/recover-where-clause-before-tuple-struct-body.rs:1]: Yeah, do so too.

File: compiler/rustc_parse/src/parser/generics.rs [hunk 10]
```diff
@@ -310,8 +339,75 @@ impl<'a> Parser<'a> {
...
+                        Err(type_err)
+                    }
```
Comment (estebank) [inline compiler/rustc_parse/src/parser/generics.rs:407]: Given your comment above, and because it is a single expression, I would write this this way:

```suggestion
                    Err(body_err) => {
                        body_err.cancel();
                        Err(type_err)
                    }
                    Ok(_) => Err(type_err),
```

I think this will be less surprising when skimming the code :)

**Comment by fmease** [comment]
Test failure is unrelated to my PR. It looks like a flaky rustdoc GUI test (CC @GuillaumeGomez).

Could someone please reapprove my PR? Thanks! :)

**Comment by GuillaumeGomez** [comment]
O.o

What the hell happened...

@bors r=estebank

**Comment by GuillaumeGomez** [comment]
Ah it should have been a retry instead, my bad. Also, are you fully rebased on `master`? If not that would explain why this error occurred...

**Comment by fmease** [comment]
> Ah it should have been a retry instead, my bad. Also, are you fully rebased on master? If not that would explain why this error occurred...

I am not. I didn't know that could lead to such problems. I'm gonna rebase onto latest master, then you can `retry` again. Thanks a lot! Sorry for the noise.

**Comment by GuillaumeGomez** [comment]
It's really just a wild guess because the error doesn't look flaky at all this time.

**Comment by fmease** [comment]
#105670 is probably going to get merged first making my PR unmergeable soon. So please hold off from r+'ing at the moment.

**Comment by fmease** [comment]
It looks like it's gonna take a short while for #105670 to be ready again for merging (after failing tests & the `src/test` migration etc.). Could someone please bors-reapprove this PR? CI is green. Thanks a lot in advance! :heart:
