### PR TITLE
Do two passes of `handle_opaque_type_uses_next`

### LINKED ISSUE #240: `handle_opaque_type_uses` happens after fallback
causing this test to fail with the new solver
```rust
#[derive(Clone, Copy)]
struct FileSystem;
impl FileSystem {
    fn build<T>(self, commands: T) -> Option<impl Sized> {
        match false {
            true => Some(commands),
            false => {
                drop(match self.build::<_>(commands) {
                    Some(x) => x,
                    None => return None,
                });
                panic!()
            },
        }
    }
}
```

i don't understand how fallback works :3

### PR DESCRIPTION
**Pull request by jackh726**
Fixes https://github.com/rust-lang/trait-system-refactor-initiative/issues/240

Also did a little bit of cleanup, can squash the commits if decided.

r? lcnr

### CODE REVIEW

File: tests/ui/traits/next-solver/opaques/hidden-types-equate-before-fallback.rs [hunk 1]
```diff
@@ -0,0 +1,27 @@
+//@ revisions: current next
+//@ ignore-compare-mode-next-solver (explicit revisions)
+//@[next] compile-flags: -Znext-solver
+//@ check-pass
+
+// Regression test for trait-system-refactor-initiative#240. Hidden types should
+// equate *before* inference var fallback, otherwise we can get mismatched types.
+
```
Comment (lcnr) [inline tests/ui/traits/next-solver/opaques/hidden-types-equate-before-fallback.rs:8]:
```suggestion
```

File: compiler/rustc_hir_typeck/src/opaque_types.rs [hunk 2]
```diff
@@ -137,17 +193,17 @@ impl<'tcx> FnCtxt<'_, 'tcx> {
...
-                .hidden_types
+                .concrete_opaque_types
                 .insert(def_id, OpaqueHiddenType::new_error(tcx, guar));
             self.set_tainted_by_errors(guar);
         }
     }
 
+    #[tracing::instrument(skip(self), ret)]
     fn consider_opaque_type_use(
         &mut self,
```
Comment (lcnr) [inline compiler/rustc_hir_typeck/src/opaque_types.rs]: doens't need `&mut self` anymore, does it? I like your change of making this function pure 👍

File: compiler/rustc_hir_typeck/src/opaque_types.rs [hunk 3]
```diff
@@ -22,6 +22,29 @@ impl<'tcx> FnCtxt<'_, 'tcx> {
     /// inference variables.
     ///
     /// It then uses these defining uses to guide inference for all other uses.
+    ///
+    /// Unlike `handle_opaque_type_uses_next`, this does not report errors.
+    #[instrument(level = "debug", skip(self))]
+    pub(super) fn try_handle_opaque_type_uses_next(&mut self) {
+        // We clone the opaques instead of stealing them here as they are still used for
+        // normalization in the next generation trait solver.
```
Comment (lcnr) [inline compiler/rustc_hir_typeck/src/opaque_types.rs]: this comment is wrong. we clone because we're not done yet :3

File: compiler/rustc_hir_typeck/src/opaque_types.rs [hunk 4]
```diff
@@ -74,6 +97,7 @@ impl<'tcx> FnCtxt<'_, 'tcx> {
     fn compute_definition_site_hidden_types(
         &mut self,
         opaque_types: &[(OpaqueTypeKey<'tcx>, OpaqueHiddenType<'tcx>)],
+        first_pass: bool,
```
Comment (lcnr) [inline compiler/rustc_hir_typeck/src/opaque_types.rs]: `first_pass` is a confusing/unhelpful argument name, maybe something like

```rust
enum ComputeDefinitionSiteHiddenMode {
    TryCompute,
    OrError,
}
```

I would like to ideally mirror `select_where_possible`/now
- `try_evaluate_obligations` and
- `evaluate_obligations_error_on_ambiguity` here

Would also be fine with `error_on_missing_defining_use: bool`.

I think a big issue with `first_pass` is that I could imagine us adding additional calls to `try`. We actually care about "is this the last pass where we error on ambiguity"

File: compiler/rustc_hir_typeck/src/opaque_types.rs [hunk 5]
```diff
@@ -88,19 +112,50 @@ impl<'tcx> FnCtxt<'_, 'tcx> {
...
+
+                let prev = self.typeck_results.borrow_mut().hidden_types.insert(def_id, ty);
+
+                // We do want to insert opaque types the first pass, because
+                // we want to equate them. So, the second pass (where we
+                // report errors) may have a hidden type inserted.
+                if first_pass {
+                    assert!(prev.is_none());
+                }
+            }
```
Comment (lcnr) [inline compiler/rustc_hir_typeck/src/opaque_types.rs:143]: I feel conflicted about this change and slightly dislike it.

I like having `apply_definition_site_hidden_types` in a separate function. It more closely matches the setup in MIR borrowck, so it feels more consistent.

I guess you don't want to equate things again if you've already had a defining use in a previous iteration. We actually kind of need to do so in case we end up with new non-defining uses since a previous call to `try_handle_opaque_type_uses_next`. 

I wouldn't worry about the perf of equating a few opaque types too frequently.

Idk if you've got strong opinions here yourself, but I would prefer to keep it as two functions 🤔

Comment (jackh726) [reply compiler/rustc_hir_typeck/src/opaque_types.rs:143]: I want to push back on this comment a bit. I definitely understand wanting to mirror MIR borrowck a bit, but the work done here is *much* simpler than the work done there - so it's not entirely a 1:1 comparison.

Second, there is no change here in when we equate opaque type. It's just a change in the flow of thought:

before:
- for each opaque ty, search through possible defining uses, find the first valid one
- store it
- if none, error
- separately, for each opaque ty use site, lookup the defining use, and equate the current hidden ty with that

here:
- for each opaque ty, search through possible defining uses, find the first valid one
- equate all other hidden tys with that defining use
- store it
- if none, error

Basically, rather than going through this "store the hidden ty then later look it up for every use", we equate immediately after identifying it - for me this is much more understandable (which is why I did this refactor)

There *is* a slight perf benefit, in that we don't do n hashmap looks (for each opaque type use site), but like you said, that isn't something too much to worry about and was not the motivation for this change.

Actually, MIR borrowck could be written in the same way (actually, briefly skimming the code there, it seems like it could be cleaner too, since there we're even emitting a `NonDefiningUseInDefiningScope` error in `apply_definition_site_hidden_types`, even though I would *expect* an invariant of `compute_definition_site_hidden_types` to be a hidden type (or error). I'm happy to make that change *separately*, but I am not convinced that we need to match that structure here.

Comment (jackh726) [reply compiler/rustc_hir_typeck/src/opaque_types.rs:143]: > Actually, MIR borrowck could be written in the same way (actually, briefly skimming the code there, it seems like it could be cleaner too, since there we're even emitting a `NonDefiningUseInDefiningScope` error in `apply_definition_site_hidden_types`, even though I would _expect_ an invariant of `compute_definition_site_hidden_types` to be a hidden type (or error). I'm happy to make that change _separately_, but I am not convinced that we need to match that structure here.

Taking a deeper look at this now, I didn't quite grok the MIR borrowck code on first glance. I'm not fully convinced that there *isn't* a cleanup that could be done there (but it's certainly not as simple as I thought), but I'm even more convinced that mirroring simple function names is not all that helpful. MIR borrowck handling of opaque types is much more complex than HIR typeck, and trying to mirror them just makes HIR typeck harder to understand.

File: compiler/rustc_hir_typeck/src/opaque_types.rs [hunk 6]
```diff
@@ -22,6 +22,29 @@ impl<'tcx> FnCtxt<'_, 'tcx> {
...
+    /// Unlike `handle_opaque_type_uses_next`, this does not report errors.
+    #[instrument(level = "debug", skip(self))]
+    pub(super) fn try_handle_opaque_type_uses_next(&mut self) {
+        // We clone the opaques instead of stealing them here as we still need
+        // to use them after fallback.
+        let mut opaque_types: Vec<_> = self.infcx.clone_opaque_types();
+        for entry in &mut opaque_types {
+            *entry = self.resolve_vars_if_possible(*entry);
+        }
+        debug!(?opaque_types);
```
Comment (lcnr) [inline compiler/rustc_hir_typeck/src/opaque_types.rs]: given that we only ever use the opaques in `compute_definition_site_hidden_types`, just move this into that function as well, or even have a single `handle_opaque_type_uses_next(HandleOpaqueTypeUses::ErrorOnMissingDefiningUse9`

File: compiler/rustc_hir_typeck/src/opaque_types.rs [hunk 7]
```diff
@@ -88,19 +112,47 @@ impl<'tcx> FnCtxt<'_, 'tcx> {
                 _ => unreachable!("not opaque or generator: {def_id:?}"),
             }
 
+            // We do actually need to check this the second pass (we can't just
+            // store this), because we can go from `UnconstrainedHiddenType` to
+            // `HasDefiningUse` (because of fallback)
```
Comment (lcnr) [inline compiler/rustc_hir_typeck/src/opaque_types.rs:114]: we can also just go from no uses to a defining use due to fallback, e.g. if you have soem `?will_fallback: Trait<opaque>` goal

**Review by lcnr — COMMENTED** [review]
please also/instead add the more minimized tests from https://github.com/rust-lang/trait-system-refactor-initiative/issues/240

*[View changes since this review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/rust/147249/595b9a498bc55fcd30111e430d8e4290ed833b4c..283ad6699cb806f6b5d38efc13a40dbd9a3321ca)*

File: compiler/rustc_hir_typeck/src/opaque_types.rs (hunk 7 above)
Comment (jackh726) [reply compiler/rustc_hir_typeck/src/opaque_types.rs:114]: That is `UnconstrainedHiddleType`?

File: compiler/rustc_hir_typeck/src/opaque_types.rs (hunk 6 above)
Comment (jackh726) [reply compiler/rustc_hir_typeck/src/opaque_types.rs]: I moved this into `compute_definition_site_hidden_types` and passed by value.

File: compiler/rustc_hir_typeck/src/opaque_types.rs (hunk 7 above)
Comment (lcnr) [reply compiler/rustc_hir_typeck/src/opaque_types.rs:114]: it could also be `None`. Maybe not with this specific example, but certainly with `?will_fallback: RequiresSend<fn_ptr_to_opaque>`

File: compiler/rustc_hir_typeck/src/opaque_types.rs [hunk 8]
```diff
@@ -88,19 +109,47 @@ impl<'tcx> FnCtxt<'_, 'tcx> {
...
+
+                // Being explicit here: it may be possible that we in a
+                // previous call to this function we did an insert, but this
+                // should be just fine, since they all get equated anyways and
+                // we shouldn't ever go from `HasDefiningUse` to anyway else.
+                let _ = self.typeck_results.borrow_mut().hidden_types.insert(def_id, ty);
+            }
+
+            // If this the first pass (`try_handle_opaque_type_uses_next`),
+            // then do not report any errors.
```
Comment (lcnr) [inline compiler/rustc_hir_typeck/src/opaque_types.rs]:
```suggestion
            // If we're in `fn try_handle_opaque_type_uses_next`,
            // then do not report any errors.
```

File: tests/ui/traits/next-solver/opaques/hidden-types-equate-before-fallback.rs [hunk 9]
```diff
@@ -0,0 +1,50 @@
...
+                });
+                panic!()
+            },
+        }
+    }
+}
+
+struct FileSystem2;
+impl FileSystem2 {
+    fn build<T, U>() -> impl Sized {
```
Comment (lcnr) [inline tests/ui/traits/next-solver/opaques/hidden-types-equate-before-fallback.rs]: i don't think we need to an inherent impl here. do we? we can just have `build2` and `build3`

**Review by lcnr — COMMENTED** [review]
nits, then r=me

*[View changes since this review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/rust/147249/595b9a498bc55fcd30111e430d8e4290ed833b4c..2fc6f8024fc0e430ef77bbb96beae2d362e0e108)*

**Comment by Zalathar** [comment]
Bors hasn't noticed that this was merged.

@bors r-
