### PR TITLE
rustdoc: Remove 'need_backline' field from `DocFragment`

### LINKED ISSUE #92084: Investigate removing `need_backline` from `rustdoc::clean::DocFragment`
I expected this change to work:
```diff
diff --git a/src/librustdoc/clean/types.rs b/src/librustdoc/clean/types.rs
index 2bd90f67cf4..a7ef658e811 100644
--- a/src/librustdoc/clean/types.rs
+++ b/src/librustdoc/clean/types.rs
@@ -936,8 +936,8 @@ fn get_word_attr(mut self, word: Symbol) -> Option<ast::NestedMetaItem> {
 //
 // * Applying the computed indent to each lines in each doc fragment (a `DocFragment` can contain
 //   multiple lines in case of `#[doc = ""]`).
-// * Adding backlines between `DocFragment`s and adding an extra one if required (stored in the
-//   `need_backline` field).
+//
+// NOTE: this can contain trailing newlines. Make sure you remove the final newline.
 fn add_doc_fragment(out: &mut String, frag: &DocFragment) {
     let s = frag.doc.as_str();
     let mut iter = s.lines().peekable();
@@ -952,9 +952,7 @@ fn add_doc_fragment(out: &mut String, frag: &DocFragment) {
             out.push('\n');
         }
     }
-    if frag.need_backline {
-        out.push('\n');
-    }
+    out.push('\n');
 }
 
 /// Collapse a collection of [`DocFragment`]s into one string,
@@ -964,6 +962,9 @@ fn add_doc_fragment(out: &mut String, frag: &DocFragment) {
     for frag in doc_strings {
         add_doc_fragment(&mut acc, frag);
     }
+    if acc.ends_with('\n') {
+        acc.pop();
+    }
     acc
 }
 
@@ -1091,6 +1092,9 @@ fn update_need_backline(doc_strings: &mut Vec<DocFragment>) {
             }
             add_doc_fragment(&mut out, new_frag);
         }
+        if out.ends_with('\n') {
+            out.pop();
+        }
         if out.is_empty() { None } else { Some(out) }
     }
 
@@ -1103,6 +1107,9 @@ fn update_need_backline(doc_strings: &mut Vec<DocFragment>) {
         for new_frag in self.doc_strings.iter() {
             let out = ret.entry(new_frag.parent_module).or_default();
             add_doc_fragment(out, new_frag);
+            if out.ends_with('\n') {
+                out.pop();
+            }
         }
         ret
     }
```
But it causes `source_span_for_markdown_range` to panic:
```
---- [rustdoc] rustdoc/intra-doc/trait-impl.rs stdout ----

error: rustdoc failed!
------------------------------------------
stderr:
------------------------------------------
thread 'rustc' panicked at 'could not find markdown in source', src/librustdoc/passes/mod.rs:199:48
```

<details><summary>Backtrace</summary>

```
thread 'rustc' panicked at 'could not find markdown in source', src/librustdoc/passes/mod.rs:199:48
stack backtrace:
   0: rust_begin_unwind
             at /rustc/d3f300477b89e70dd42379ba53c0e8ff74e9c694/library/std/src/panicking.rs:498:5
   1: core::panicking::panic_fmt
             at /rustc/d3f300477b89e70dd42379ba53c0e8ff74e9c694/library/core/src/panicking.rs:107:14
   2: core::panicking::panic_display
             at /rustc/d3f300477b89e70dd42379ba53c0e8ff74e9c694/library/core/src/panicking.rs:63:5
   3: core::option::expect_failed
             at /rustc/d3f300477b89e70dd42379ba53c0e8ff74e9c694/library/core/src/option.rs:1819:5
   4: rustdoc::passes::source_span_for_markdown_range
   5: <rustdoc::passes::collect_intra_doc_links::report_diagnostic<rustdoc::passes::collect_intra_doc_links::resolution_failure::{closure#0}>::{closure#0} as core::ops::function::FnOnce<(rustc_middle::lint::LintDiagnosticBuilder,)>>::call_once::{shim:vtable#0}
   6: rustc_middle::lint::struct_lint_level::struct_lint_level_impl
   7: rustc_middle::lint::struct_lint_level::<rustdoc::passes::collect_intra_doc_links::report_diagnostic<rustdoc::passes::collect_intra_doc_links::resolution_failure::{closure#0}>::{closure#0}>
   8: <rustc_middle::ty::context::TyCtxt>::struct_span_lint_hir::<rustc_span::span_encoding::Span, rustdoc::passes::collect_intra_doc_links::report_diagnostic<rustdoc::passes::collect_intra_doc_links::resolution_failure::{closure#0}>::{closure#0}>
   9: rustdoc::passes::collect_intra_doc_links::report_diagnostic::<rustdoc::passes::collect_intra_doc_links::resolution_failure::{closure#0}>
  10: rustdoc::passes::collect_intra_doc_links::resolution_failure
  11: <rustdoc::passes::collect_intra_doc_links::LinkCollector as rustdoc::visit::DocVisitor>::visit_item
  12: <rustdoc::passes::collect_intra_doc_links::LinkCollector as rustdoc::visit::DocVisitor>::visit_item_recur
  13: <rustdoc::passes::collect_intra_doc_links::LinkCollector as rustdoc::visit::DocVisitor>::visit_item
  14: <rustdoc::passes::collect_intra_doc_links::LinkCollector as rustdoc::visit::DocVisitor>::visit_item_recur
  15: <rustdoc::passes::collect_intra_doc_links::LinkCollector as rustdoc::visit::DocVisitor>::visit_item
  16: <rustdoc::passes::collect_intra_doc_links::LinkCollector as rustdoc::visit::DocVisitor>::visit_crate
  17: rustdoc::passes::collect_intra_doc_links::collect_intra_doc_links
  18: <rustc_session::session::Session>::time::<rustdoc::clean::types::Crate, rustdoc::core::run_global_ctxt::{closure#11}>
  19: rustdoc::core::run_global_ctxt
  20: <rustc_session::session::Session>::time::<(rustdoc::clean::types::Crate, rustdoc::config::RenderOptions, rustdoc::formats::cache::Cache), rustdoc::main_options::{closure#0}::{closure#0}::{closure#0}::{closure#0}>
  21: <rustc_interface::passes::QueryContext>::enter::<rustdoc::main_options::{closure#0}::{closure#0}::{closure#0}, core::result::Result<(), rustc_errors::ErrorReported>>
  22: <rustc_interface::interface::Compiler>::enter::<rustdoc::main_options::{closure#0}::{closure#0}, core::result::Result<(), rustc_errors::ErrorReported>>
  23: rustc_span::with_source_map::<core::result::Result<(), rustc_errors::ErrorReported>, rustc_interface::interface::create_compiler_and_run<core::result::Result<(), rustc_errors::ErrorReported>, rustdoc::main_options::{closure#0}>::{closure#1}>
  24: rustc_interface::interface::create_compiler_and_run::<core::result::Result<(), rustc_errors::ErrorReported>, rustdoc::main_options::{closure#0}>
  25: rustdoc::main_options
  26: <scoped_tls::ScopedKey<rustc_span::SessionGlobals>>::set::<rustc_interface::util::setup_callbacks_and_run_in_thread_pool_with_globals<rustdoc::main_args::{closure#0}, core::result::Result<(), rustc_errors::ErrorReported>>::{closure#0}::{closure#0}, core::result::Result<(), rustc_errors::ErrorReported>>
```

</details>

I don't have time to look into it right now, but I wouldn't expect it to be *too* hard to fix and it would reduce the memory usage of rustdoc by quite a lot. I'd suggest starting by adding a bunch of assertions that the old and new behavior of `collapsed_doc_value` is the same and investigating the assertion failures.

### PR DESCRIPTION
**Pull request by vacuus**
Fixes [#92084](https://github.com/rust-lang/rust/issues/92084)

### CODE REVIEW

**Comment by vacuus** [comment]
Just having noticed https://github.com/rust-lang/rust/issues/92084, this PR may become obsolete.

**Comment by jyn514** [comment]
@vacuus here's a guide on fixing conflicts: https://rustc-dev-guide.rust-lang.org/git.html#rebasing-and-conflicts

I'm not sure what you mean by obsolete - this is exactly the sort of change I was hoping to see when I opened the issue :)

File: src/librustdoc/clean/types.rs [hunk 1]
```diff
@@ -932,42 +932,37 @@ crate enum DocFragmentKind {
...
-// transforming into the final markdown. So the transformations in here are:
+// The goal of this function is to apply the `DocFragment` transformation that is required when
+// transforming into the final Markdown, which is applying the computed indent to each line in
+// each doc fragment (a `DocFragment` can contain multiple lines in case of `#[doc = ""]`).
 //
-// * Applying the computed indent to each lines in each doc fragment (a `DocFragment` can contain
-//   multiple lines in case of `#[doc = ""]`).
-// * Adding backlines between `DocFragment`s and adding an extra one if required (stored in the
-//   `need_backline` field).
+// Note: remove the trailing newline where appropriate
```
Comment (jyn514) [inline src/librustdoc/clean/types.rs:939]: While you're rewriting these comments, can you make them doc-comments so they show up on doc.rust-lang.org/rustdoc?

File: src/librustdoc/clean/types.rs [hunk 2]
```diff
@@ -1094,6 +1089,7 @@ impl Attributes {
             }
             add_doc_fragment(&mut out, new_frag);
         }
+        out.pop();
```
Comment (jyn514) [inline src/librustdoc/clean/types.rs:1092]: Doesn't `collapsed_doc_value` also need to be updated?

**Review by jyn514 — COMMENTED** [review]
This looks great! Could you now remove the `need_backline` field everywhere in `types.rs`? That should give a big memory improvement :)

**Comment by vacuus** [comment]
I confess that I'm stumped on the rebase. Right after cloning my fork, I did `git remote add upstream https://github.com/rust-lang/rust.git` and then `git pull upstream master`. However, `git rebase master` just says "current branch master is up to date". Doing `git config pull.rebase true` instead of `git config pull.rebase false` changes nothing. Would it be better to close this PR and open a new one?

File: src/librustdoc/clean/types.rs (hunk 2 above)
Comment (vacuus) [reply src/librustdoc/clean/types.rs:1092]: I assume you mean [#92078](https://github.com/rust-lang/rust/pull/92078)? They don't conceptually overlap.

**Comment by jyn514** [comment]
@vacuus try `git fetch upstream` and then `git rebase upstream/master`

**Comment by vacuus** [comment]
Sorry to bother you more, but do I just allow the changes I made? For example, this is one of the conflicts: since the goal is to remove 'need_backline`, the if let would be deleted. There shouldn't be any problem with me deleting the whole snippet and considering that conflict resolved, right?
```
<<<<<<< master
=======
                if let Some(prev) = doc_strings.last_mut() {
                    prev.need_backline = true;
                }

>>>>>>> master
```

**Comment by jyn514** [comment]
Yup! That whole block shouldn't be needed any more

**Comment by camelid** [comment]
All you need to do is delete the conflict marker arrows and made sure the code that is left behind is what you want. So if you want to delete the section that has conflicts, just delete it.

**Comment by camelid** [comment]
Should this be marked as closing #92084? (Just add the phrases "Fixes #92084" to the PR description body.)

**Comment by vacuus** [comment]
The size assertion at [line 923](https://github.com/rust-lang/rust/blob/master/src/librustdoc/clean/types.rs) (`rustc_data_structures::static_assert_size!(DocFragment, 32);`) should be updated to 31 bytes, right?

**Comment by vacuus** [comment]
There seem to be quite a few compilation errors due to a `String` being returned from one or two of the functions instead of an `Option`. I'll try to fix those. The macro-related ones are probably beyond my expertise.

**Comment by jyn514** [comment]
> There seem to be quite a few compilation errors due to a `String` being returned from one or two of the functions instead of an `Option`. I'll try to fix those. The macro-related ones are probably beyond my expertise.

Wait, why did you change that in this PR? I thought this was only changing need_backline.

**Comment by vacuus** [comment]
I guess I thought that [#92078](https://github.com/rust-lang/rust/pull/92078) was already merged and I should update this accordingly. My bad. I'll revert those changes.

**Comment by vacuus** [comment]
I suppose that, for alignment reasons, the size of `DocFragment` is still 32 bytes and not 31.

**Comment by vacuus** [comment]
That seems to be a formatting issue, yet running rustfmt on [the file](https://github.com/vacuus/rust/blob/master/src/librustdoc/clean/types.rs) doesn't raise any complaints.

**Comment by camelid** [comment]
@vacuus when you get a chance, could you please [squash your commits](https://rustc-dev-guide.rust-lang.org/git.html#advanced-rebasing)? In this case, run the following command:

```console
$ git rebase -i $(git merge-base upstream/master HEAD)
```

then replace all the `pick`s with `squash`s, except for the first and second lines (since those commits should be independent).

**Comment by vacuus** [comment]
I've squashed my commits on my local repo but I'm not sure how to update my remote repo accordingly. How do I proceed?
```
Your branch and 'origin/master' have diverged,
and have 2 and 13 different commits each, respectively.
  (use "git pull" to merge the remote branch into yours)

hint: You have divergent branches and need to specify how to reconcile them.
hint: You can do so by running one of the following commands sometime before
hint: your next pull:
hint: 
hint:   git config pull.rebase false  # merge (the default strategy)
hint:   git config pull.rebase true   # rebase
hint:   git config pull.ff only       # fast-forward only
```

**Comment by camelid** [comment]
Run `git push --force-with-lease`.

**Comment by vacuus** [comment]
Silly me, I should've picked that up from the rebasing guide you graciously provided. Thanks, y'all, for your guidance!

**Comment by camelid** [comment]
You're welcome! Also, keep in mind that much of the time when something goes wrong with Git, you can recover the old state of your repository by [running `git reflog`](https://github.blog/2015-06-08-how-to-undo-almost-anything-with-git/#redo-after-undo-local).

**Comment by jyn514** [comment]
> That seems to be a formatting issue, yet running rustfmt on [the file](https://github.com/vacuus/rust/blob/master/src/librustdoc/clean/types.rs) doesn't raise any complaints.

Are you running `rustfmt` directly? Try `x.py fmt` instead.

File: src/librustdoc/clean/types.rs [hunk 3]
```diff
@@ -1094,10 +1081,17 @@ impl Attributes {
...
         let mut ret = FxHashMap::default();
+        let last_string = match self.doc_strings.last() {
+            Some(string) => string,
+            None => return ret,
+        };
 
         for new_frag in self.doc_strings.iter() {
             let out = ret.entry(new_frag.parent_module).or_default();
             add_doc_fragment(out, new_frag);
+            if new_frag == last_string {
```
Comment (jyn514) [inline src/librustdoc/clean/types.rs:1092]: This compares the whole string, not the index, which seems wrong: you could have two lines with the same docs. Can you use enumerate() and compare the indexes instead?

Comment (vacuus) [reply src/librustdoc/clean/types.rs]: Done. Alternatively, the conditional could be removed, and `pop` called on the entry for the last element after the loop. Would that be preferred? (That would make two instances of removing a conditional from a loop in the same PR!) It would probably only be better if 'self.doc_strings' has a lot of elements such that the cost of another hashing/retrieval operation is less expensive than numerous integer equality checks.

Comment (vacuus) [reply src/librustdoc/clean/types.rs]: Should there be a test to make sure this doesn't regress to what you described?

Comment (jyn514) [reply src/librustdoc/clean/types.rs]: If you can put a test together, that would be great! I don't think it's strictly necessary though.

**Comment by vacuus** [comment]
Unfortunately, I don't believe there were any gains in memory efficiency, but I daresay that this was productive. I've gained some experience with making a pull request and rebasing. Again, thanks for your guidance! I hope to contribute further to the language.
(hopefully, there's no last minute gotcha with this PR)

**Review by jyn514 — APPROVED** [review]
This is still way easier to understand than before :) thanks for working on it!

**Comment by jyn514** [comment]
Apple job failed without logs.

@bors retry

**Comment by vacuus** [comment]
Well, that's a doozy.
