### PR TITLE
Highlight edition-specific keywords correctly in code blocks, accounting for code block edition modifiers

### LINKED ISSUE #80004: `async` and other Rust 2018+ keywords not recognized as so in Rustdoc highlighting
I tried this code:

```rust
/// ```rust ignore
/// fn foo(bar: &dyn Baz);
/// async fn quux() {
///     qaz.frobnify().await;
/// }
/// fn bar() {
///     let mut a = 0;
///     abstract blah; /// is a reserved keyword
/// }
/// ```
fn foo() {}
```

I expected to see this happen: `async` and other Rust 2018+ keywords are highlighted as my project is set to `edition = "2018"` in its `Cargo.toml`

Instead, this happened: They were not highlighted, but regular keywords (including reserved ones) were.
image

I believe that the reason why this is happening is this snippet in librustdoc: https://github.com/rust-lang/rust/blob/eb4fc71dc9024f15a0c9cc44bcc10c861e9d585e/src/librustdoc/html/highlight.rs#L292-L305

In this case, `Ident::from_str` will only create a dummy span (which isn't set to 2018 edition), so `is_reserved` does not include 2018+ keywords.

I would be willing to try to work on a PR to fix this issue if it is deemed worthy.

### Meta
Tested 

`rustc --version --verbose`:
stable:
```
rustc 1.48.0 (7eac88abb 2020-11-16)
binary: rustc
commit-hash: 7eac88abb2e57e752f3302f02be5f3ce3d7adfb4
commit-date: 2020-11-16
host: x86_64-unknown-linux-gnu
release: 1.48.0
LLVM version: 11.0
```
nightly:
```
rustc 1.50.0-nightly (7efc097c4 2020-12-12)
binary: rustc
commit-hash: 7efc097c4fe6e97f54a44cee91c56189e9ddb41c
commit-date: 2020-12-12
host: x86_64-unknown-linux-gnu
release: 1.50.0-nightly
```

Backtrace is not applicable.

### PR DESCRIPTION
**Pull request by ThePuzzlemaker**
Previously, edition-specific keywords (such as `async` and `await`) were not highlighted in code blocks, regardless of what edition was set. With this PR, this issue is fixed.

Now, the following behavior happens:
- When a code block is explicitly set to edition X, keywords from edition X are highlighted
- When a code block is explicitly set to a version that does not contain those keywords from edition X (e.g. edition Y), keywords from edition X are **not** highlighted
- When a code block has no explicit edition, keywords from the edition passed via `--edition` to rustdoc are highlighted

For example, a project set with `edition = "2015"` in its `Cargo.toml` would not highlight `async`/`await` unless the code block was set to `edition2018`. Additionally, a project set with `edition = "2018"` in its `Cargo.toml` *would* highlight `async`/`await` unless the code block was set to a version that did not contain those keywords (e.g. `edition2015`).

This PR fixes #80004.

r? @jyn514

### CODE REVIEW

**Comment by jyn514** [comment]
Hmm, I see - the issue is that the edition is not necessarily related to the span, so even if you pass in `item.source`, someone could have an `edition2018` lang string on the code block.

The rustdoc side of things seems reasonable to me but I think this should have a reviewer from T-compiler.

r? @petrochenkov

**Comment by jyn514** [comment]
Also you need to fix the unit tests:

```
error[E0061]: this function takes 3 arguments but 2 arguments were supplied
  --> src/librustdoc/html/highlight/tests.rs:21:9
   |
21 |         write_code(&mut out, src);
   |         ^^^^^^^^^^ --------  --- supplied 2 arguments
   |         |
   |         expected 3 arguments
```

**Comment by ThePuzzlemaker** [comment]
> Hmm, I see - the issue is that the edition is not necessarily related to the span, so even if you pass in `item.source`, someone could have an `edition2018` lang string on the code block.

I'm not sure what you're talking about. The only time I think I can see something like `item.source` is in this code: https://github.com/rust-lang/rust/blob/ffa98d6fb1144ca42ee92d0465b7bc1b669d64c1/src/librustdoc/html/render/mod.rs#L4717-L4728
I'm pretty sure that this code is only for highlighting macro definitions (e.g. at the top of [`dbg!`](https://doc.rust-lang.org/nightly/std/macro.dbg.html)).

**Comment by ThePuzzlemaker** [comment]
As for code blocks, they use either the explicit edition attribute or the edition given by `--edition`.

File: compiler/rustc_span/src/symbol.rs [hunk 1]
```diff
@@ -1661,7 +1673,15 @@ impl Ident {
 
     /// Returns `true` if the token is either a special identifier or a keyword.
     pub fn is_reserved(self) -> bool {
-        self.is_special() || self.is_used_keyword() || self.is_unused_keyword()
+        // Note: `span.edition()` is relatively expensive, don't call it unless necessary.
+        self.is_reserved_in_edition(self.span.edition())
```
Comment (petrochenkov) [inline compiler/rustc_span/src/symbol.rs:1677]: There are three issues here:
- You copy the comment about `span.edition()` being expensive, and then evaluate it eagerly even if it's not necessary.
- Methods taking `Edition` are put on `Ident` and not on `Symbol` despite not using the span.
- The newly added methods duplicate logic from old methods.

I'll try to come up with something better today.

**Comment by petrochenkov** [comment]
One more question - I assumed that rustdoc "compiles" separate code blocks as independent programs, creating independent compilation sessions, so each session can have its own default edition (which will be used by `Ident::from_str(text).is_reserved()`).
Why doesn't it happen here?

File: compiler/rustc_span/src/symbol.rs (hunk 1 above)
Comment (ThePuzzlemaker) [reply compiler/rustc_span/src/symbol.rs:1677]: Sorry about that. I’m not very good at tinkering with the compiler :/

**Comment by ThePuzzlemaker** [comment]
> One more question - I assumed that rustdoc "compiles" separate code blocks as independent programs, creating independent compilation sessions, so each session can have its own default edition possibly depending on the block's annotations (which will be used by `Ident::from_str(text).is_reserved()`).
> Why doesn't it happen here?

@petrochenkov I’m pretty sure this is just simple lexing for highlighting and rendering—individual sessions for each code block/doctest would probably be part of the doctest logic rather than rendering as that’d seem expensive for simple lexing.

File: compiler/rustc_span/src/symbol.rs (hunk 1 above)
Comment (petrochenkov) [reply compiler/rustc_span/src/symbol.rs:1677]: >I'll try to come up with something better today.

Implemented in https://github.com/rust-lang/rust/pull/80226.

**Comment by ThePuzzlemaker** [comment]
#80272 merged; no longer blocked. Will update and re-test.
@rustbot modify labels: S-blocked

**Comment by ThePuzzlemaker** [comment]
Updated, rebased, and squashed. Working again :smile:

**Comment by ThePuzzlemaker** [comment]
I used `Symbol::intern(...).is_reserved` rather than `Ident::from_str(...).name.is_reserved` to prevent unnecessary uses of a bunch of dummy spans

**Comment by Dylan-DPC** [comment]
has conflicts

@bors r-

**Comment by ThePuzzlemaker** [comment]
Rebased and fixed merge conflicts.

**Comment by ThePuzzlemaker** [comment]
Fixed.
