### PR TITLE
Suggest remove last method call when type coerce with expected  type

### LINKED ISSUE #105494: Compiler suggestion "try using a conversion method: .to_string"
I tried this code ([playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=f5a8a63d39604cdedc368ffb5c41707f)):

```rust
fn main() {
    let mut path: String = "/usr".to_string();
    let folder: String = "lib".to_string();
    
    path = format!("{}/{}", path, folder).as_str();
    
    println!("{}", &path);
}
```

I expected to see this happen: 

```
error[[E0308]](https://doc.rust-lang.org/stable/error-index.html#E0308): mismatched types
 --> src/main.rs:6:12
  |
2 |     let mut path: String = "/usr".to_string();
  |                   ------ expected due to this type
...
5 |     path = format!("{}/{}", path, folder).as_str();
  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^- help: try removing the call to method: `.as_str()`
  |            |
  |            expected struct `String`, found `&str`
```

Instead, this happened:

```
error[[E0308]](https://doc.rust-lang.org/stable/error-index.html#E0308): mismatched types
 --> src/main.rs:6:12
  |
2 |     let mut path: String = "/usr".to_string();
  |                   ------ expected due to this type
...
5 |     path = format!("{}/{}", path, folder).as_str();
  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^- help: try using a conversion method: `.to_string()`
  |            |
  |            expected struct `String`, found `&str`
```

This is just a very specific instance where the suggestion to add some code, while "technically correct", is less useful than the better suggestion to remove some code.

### Meta

`rustc --version --verbose`:
```
rustc 1.65.0 (897e37553 2022-11-02)
binary: rustc
commit-hash: 897e37553bba8b42751c67658967889d11ecd120
commit-date: 2022-11-02
host: aarch64-apple-darwin
release: 1.65.0
LLVM version: 15.0.0
```

<details><summary>Backtrace</summary>
<p>

```
<backtrace>
```

</p>
</details>

### PR DESCRIPTION
**Pull request by chenyukang**
Fixes #105494

### CODE REVIEW

File: compiler/rustc_hir_typeck/src/fn_ctxt/suggestions.rs [hunk 1]
```diff
@@ -331,6 +331,26 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
...
+        &self,
+        err: &mut Diagnostic,
+        expr: &hir::Expr<'tcx>,
+        expected: Ty<'tcx>,
+    ) -> bool {
+        if let hir::ExprKind::MethodCall(hir::PathSegment { ident: method, .. }, recv_expr, &[], _) = expr.kind &&
+            let Some(recv_ty) = self.typeck_results.borrow().expr_ty_opt(recv_expr) &&
+            self.can_coerce(recv_ty, expected) {
+                err.span_suggestion_verbose(
+                    expr.span.with_lo(method.span.lo() - rustc_span::BytePos(1)),
```
Comment (compiler-errors) [inline compiler/rustc_hir_typeck/src/fn_ctxt/suggestions.rs:344]: Can you use `rcvr_expr.span.hi()` instead of subtracting 1 from `lo`? 

We can have spaces I think like `a . b()`

Comment (chenyukang) [reply compiler/rustc_hir_typeck/src/fn_ctxt/suggestions.rs:344]: Yes, I tried to use `rcvr_expr.span.hi()`,
but seems it's not right in the scenario of macro, for example:

```rust
let s: &str = format!("hello world").to_string()
```
the `rcvr_expr.span.hi()` is span after macro expansion.

Comment (compiler-errors) [reply compiler/rustc_hir_typeck/src/fn_ctxt/suggestions.rs:344]: can you use Span::find_ancestor_inside?

Comment (chenyukang) [reply compiler/rustc_hir_typeck/src/fn_ctxt/suggestions.rs]: code updated, thanks!

**Review by eholk — APPROVED** [review]

**Comment by eholk** [comment]
r=me after resolving the conflicts.
