### PR TITLE
Enforce supertrait outlives obligations hold when confirming impl

### LINKED ISSUE #98117: Unsoundness due to where clauses not checked for well-formedness
This code does pass:  ([playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=4225e75d1514837fb4df4d35ee880f55))
```rust
trait Outlives<'a>: 'a {} // without `: 'a`, it fails as expected.

fn t_is_static<T>()
where
    &'static T: Outlives<'static>,
{
}
```
But according to [RFC 1214](https://github.com/rust-lang/rfcs/blob/master/text/1214-projections-lifetimes-and-wf.md) functions are responsible for checking the well-formedness of their own where clauses. So this should fail and require an explicit bound `T: 'static`.

Here is an exploit of this unsoundness: ([playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=4839e77e4f4058b1790a1e5ecf3f653e))
```rust
trait Outlives<'a>: 'a {}
impl<'a, T> Outlives<'a> for &'a T {}

fn step2<T>(t: T) -> &'static str
where
    &'static T: Outlives<'static>,
    T: AsRef<str>,
{
    AsRef::as_ref(Box::leak(Box::new(t) as Box<dyn AsRef<str> + 'static>))
}

fn step1<T>(t: T) -> &'static str
where
    for<'a> &'a T: Outlives<'a>,
    T: AsRef<str>,
{
    step2(t)
}

fn main() {
    let s: &'static str = step1(&String::from("blah blah blah"));
    println!("{s}");
}
```

@rustbot label C-bug T-compiler T-types A-lifetimes I-unsound

### PR DESCRIPTION
**Pull request by compiler-errors**
**TL;DR:** We elaborate super-predicates and apply any outlives obligations when proving an impl holds to fix a mismatch between implied bounds.

Bugs in implied bounds (and implied well-formedness) occur whenever there is a mismatch between the assumptions that some code can assume to hold, and the obligations that a caller/user of that code must prove. If the former is stronger than the latter, then unsoundness occurs.

Take a look at the example unsoundness:

```rust
use std::fmt::Display;

trait Static: 'static {}
impl<T> Static for &'static T {}
fn foo<S: Display>(x: S) -> Box<dyn Display>
where
    &'static S: Static,
{
    Box::new(x)
}

fn main() {
    let s = foo(&String::from("blah blah blah"));
    println!("{}", s);
}
```

This specific example occurs because we elaborate obligations in `fn foo`:

* `&'static S: Static`
    * `&'static S: 'static` <- super predicate
        * `S: 'static` <- elaborating outlives bounds

However, when calling `foo`, we only need to prove the direct set of where clauses. So at the call site for some substitution `S = &'not_static str`, that means only proving `&'static &'not_static str: Static`. To prove this, we apply the impl, which itself holds trivially since it has no where clauses.

This is the mismatch -- `foo` is allowed to assume that `S: 'static` via elaborating supertraits, but callers of `foo` never need to prove that `S: 'static`.

There are several approaches to fixing this, all of which have problems due to current limitations in our type system:
1. proving the elaborated set of predicates always - This leads to issues since we don't have coinductive trait semantics, so we easily hit new cycles.
    * This would fix our issue, since callers of `foo` would have to both prove `&'static &'not_static str: Static` and its elaborated bounds, which would surface the problematic `'not_static: 'static` outlives obligation.
    * However, proving supertraits when proving impls leads to inductive cycles which can't be fixed until we get coinductive trait semantics.
2. Proving that an impl header is WF when applying that impl:
    * This would fix our issue, since when we try to prove `&'static &'not_static str: Static`, we'd need to prove `WF(&'static &'not_static str)`, which would surface the problematic `'not_static: 'static` outlives obligation.
    * However, this leads to issues since we don't have higher-ranked implied bounds. This breaks things when trying to apply impls to higher-ranked trait goals.

To get around these limitations, we apply a subset of (1.), which is to elaborate the supertrait obligations of the impl but filter only the (region/type) outlives out of that set, since those can never participate in an inductive cycle. This is likely not sufficient to fix a pathological example of this issue, but it does clearly fill in a major gap that we're currently overlooking.

This can also result in 'unintended' errors due to missing implied-bounds on binders. We did not encounter this in the crater run and don't expect people to rely on this code in practice:
```rust
trait Outlives<'b>: 'b {}
impl<'b, T> Outlives<'b> for &'b T {}
fn foo<'b>()
where
    // This bound will break due to this PR as we end up proving
    // `&'b &'!a (): 'b` without the implied `'!a: 'b`
    // bound.
    for<'a> &'b &'a (): Outlives<'b>, 
{}
```

Fixes #98117

---

Crater: https://github.com/rust-lang/rust/pull/124336#issuecomment-2209165320
Triaged: https://github.com/rust-lang/rust/pull/124336#issuecomment-2236321325

All of the fallout is due to generic const exprs, and can be ignored.

### CODE REVIEW

**Comment by compiler-errors** [comment]
TODO: also do this in the new solver

**Comment by compiler-errors** [comment]
@craterbot check

**Comment by compiler-errors** [comment]
@craterbot run mode=check-only start=master#5557f8c9d08d7f3f680943dcf97b6d4a7eb13aea end=try#311f8b6ca41358db8ae08490a9ca0916f11e9de3

**Comment by apiraino** [comment]
seems the crater run wasnt too happy

@rustbot author

**Comment by compiler-errors** [comment]
@craterbot run mode=check-only start=master#5557f8c9d08d7f3f680943dcf97b6d4a7eb13aea end=try#311f8b6ca41358db8ae08490a9ca0916f11e9de3 crates=https://crater-reports.s3.amazonaws.com/pr-124336/retry-regressed-list.txt

**Comment by apiraino** [comment]
better, but still some regression (if I read the report correctly)

@rustbot author

**Comment by lcnr** [comment]
- https://github.com/ITesserakt/optimization https://github.com/rust-lang/project-const-generics/issues/33 gce issue, can ignore
 - https://github.com/xfoxfu/rust-aes/blob/5b7026389f7d4e7e1d2d56b7ad047c6cf439fce7/src/aes/encrypt.rs#L104 also gce `M::ASSOC_CONST` currently forces a type to be static if `M` is
 - dfdx-0.13.0 also GCE
 - gregg_anni_interpreter depends on dfdx
 - rust_domino same
 - dfdx-perf-test same
 - snake-ai-v2 same
 - https://github.com/favilo/tardyai same
 - https://github.com/iacore/debug-dfdx-stddev same
 - https://github.com/strasdat/sophus-rs same

no breakage not caused by generic const expressions. Feels acceptable to go ahead

**Comment by compiler-errors** [comment]
The second commit is somewhat of a hack, though I'm not too sad about it -- it ensures we don't have a mismatch between the outlives obligations from the `impl<T: ?Sized + 'static> Any for T {}` and `dyn Any: Any` built-in impl. Elaborating the `dyn` supertrait obligations explicitly ensures that we end up elaborating `dyn Any + '?0: 'static` into `'?0: 'static`.

**Comment by compiler-errors** [comment]
OK this is ready

@rustbot ready

File: compiler/rustc_next_trait_solver/src/solve/assembly/structural_traits.rs [hunk 1]
```diff
@@ -668,11 +668,12 @@ where
 {
     let cx = ecx.cx();
     let mut requirements = vec![];
-    requirements.extend(
+    requirements.extend(elaborate::elaborate(
```
Comment (lcnr) [inline compiler/rustc_next_trait_solver/src/solve/assembly/structural_traits.rs:671]: please add a comment why we elaborate here:
- it's not soundness critical
- however, we currently elaborate the super predicates for user-defined impls which destructures outlives requirements. So for the builtin and user-defined impl of `dyn Any: Any` to have the same region constraints (to enable us to merge them), we also elaborate to get all outlives constraints here

Comment (compiler-errors) [reply compiler/rustc_next_trait_solver/src/solve/assembly/structural_traits.rs:671]: Can do

**Comment by lcnr** [comment]
@rfcbot fcp merge (see the PR description)

**Comment by BoxyUwU** [comment]
(GCE = `feature(generic_const_exprs)` which is largely pretty broken and is, of course, unstable. so should not be taken into account for "potential breakage" of this PR)

**Comment by nikomatsakis** [comment]
@rfcbot reviewed

File: compiler/rustc_next_trait_solver/src/solve/assembly/structural_traits.rs (hunk 1 above)
Comment (lcnr) [reply compiler/rustc_next_trait_solver/src/solve/assembly/structural_traits.rs:671]: still relevant

File: compiler/rustc_trait_selection/src/traits/select/mod.rs [hunk 2]
```diff
@@ -2787,6 +2789,34 @@ impl<'tcx> SelectionContext<'_, 'tcx> {
             });
         }
 
+        if matches!(self.tcx().def_kind(def_id), DefKind::Impl { of_trait: true })
```
Comment (lcnr) [inline compiler/rustc_trait_selection/src/traits/select/mod.rs:2792]:
```suggestion
        // Register any outlives obligations from the trait here, cc #124336.
        if matches!(self.tcx().def_kind(def_id), DefKind::Impl { of_trait: true })
```

File: compiler/rustc_next_trait_solver/src/solve/trait_goals.rs [hunk 3]
```diff
@@ -87,6 +87,19 @@ where
                 .map(|pred| goal.with(cx, pred));
             ecx.add_goals(GoalSource::ImplWhereBound, where_clause_bounds);
 
+            // We currently elaborate all supertrait obligations from impls. This
+            // can be removed when we actually do coinduction correctly and just
+            // register that the impl header must be WF.
```
Comment (lcnr) [inline compiler/rustc_next_trait_solver/src/solve/trait_goals.rs:92]: this comment doesn't feel right?

**Review by lcnr — COMMENTED** [review]
r=me after comments

File: compiler/rustc_next_trait_solver/src/solve/trait_goals.rs (hunk 3 above)
Comment (compiler-errors) [reply compiler/rustc_next_trait_solver/src/solve/trait_goals.rs:92]: I guess it should be "actually do coinduction correctly and just register supertrait obligations always". The impl header WF check is a totally different approach, yeah.

Comment (lcnr) [reply compiler/rustc_next_trait_solver/src/solve/trait_goals.rs:92]: We also don't elaborate all supertrait obligations :sweat_smile: we only elaborate region obligations as elaborating all of them causes inductive solver cycles

Comment (compiler-errors) [reply compiler/rustc_next_trait_solver/src/solve/trait_goals.rs:92]: Well I think the point here is that we do deep elaboration `elaborate(...)` rather than shallow elaboration `tcx.explicit_supertraits(...)`.  I'll reword the comment.

**Comment by compiler-errors** [comment]
Ruh roh!

**Comment by compiler-errors** [comment]
Let me see if I can queryify the transitive supertrait outlives here...

**Comment by Kobzol** [comment]
Regression resolved in https://github.com/rust-lang/rust/pull/128746.

@rustbot label: +perf-regression-triaged

**Comment by apiraino** [comment]
IIUC when this will reach stable (in a week from now) it will cause regressions in some crates we accept (for example #130577).

Tagging accordingly for release notes.

@rustbot label +relnotes
