### PR TITLE
Drop array patterns using subslices

### LINKED ISSUE #109004: Compiling `drop(Box<large array>)` causes runaway compiler memory usage
Attempting to compile this code causes extremely large memory usage by rustc.
By experimentation, the important features of the code are: large `LIMIT`, the element type needs to have drop glue, and the drop can't be skipped with `forget` or some other mechanism. It also must be a program, not a library function.

`src/main.rs`
```rust
fn main() {
    const LIMIT: usize = 64_000_000;
    // NB. if it compiled successfully, this would just panic, it wouldn't even allocate...
    let _arr: Box<[String; LIMIT]> = Vec::new().into_boxed_slice().try_into().ok().unwrap();
}
```
`Cargo.toml`
```
[package]
name = "repro"
version = "0.1.0"
edition = "2021"
```

The problematic compiler invocation: `cargo build`. 

I expected to see this happen: The compiler memory usage shouldn't run away due to large `LIMIT`; in fact the compiler memory usage should be almost entirely independent of `LIMIT` for this program.

Instead, this happened: When `LIMIT` is large, `rustc` uses a lot of memory and takes a long time. I have not successfully compiled the above program with the given `LIMIT` of 64M.

### Meta
I repro'd this on `1.65.0`, `1.68.0`, and finally:
```
rustc 1.70.0-nightly (39f2657d1 2023-03-09)
binary: rustc
commit-hash: 39f2657d1101b50f9b71ae460b762d330cc8426b
commit-date: 2023-03-09
host: x86_64-unknown-linux-gnu
release: 1.70.0-nightly
LLVM version: 15.0.7
```

(I did not capture a compiler backtrace.)

### Thoughts
I surmise that there's a correlation between `LIMIT` and compiler behavior but I haven't explored it beyond verifying a small `LIMIT` doesn't repro the bad behavior.

I thought perhaps this program tries to use the stack for the slice->array cast, and somehow the compiler is getting stuck on such a large stack frame. Thankfully, this is ruled out by checking that `src/alloc/boxed.rs:boxed_slice_as_array_unchecked` does indeed do the slice->array cast entirely using pointers. So the compiler shouldn't "see" how big the array is; it's behind a pointer.

Appending `std::mem::forget(_arr);` to `main` bypasses the issue, so it appears to be drop glue for the box which causes the problem. I don't see a particular reason why the drop glue for this type should be problematic; it should be no different than dropping the initialized part of a large `Vec<String>`.
</p>
</details>

### PR DESCRIPTION
**Pull request by clubby789**
Fixes #109004
Drops contiguous subslices of an array when moving elements out with a pattern, which improves perf for large arrays
r? @compiler-errors

### CODE REVIEW

File: compiler/rustc_mir_dataflow/src/elaborate_drops.rs [hunk 1]
```diff
@@ -889,12 +866,7 @@ where
                 }
             }
             ty::Dynamic(..) => self.complete_drop(self.succ, self.unwind),
-            ty::Array(ety, size) => {
-                let size = size.try_eval_target_usize(self.tcx(), self.elaborator.param_env());
-                self.open_drop_for_array(*ety, size)
-            }
-            ty::Slice(ety) => self.open_drop_for_array(*ety, None),
-
+            ty::Array(ety, _) | ty::Slice(ety) => self.open_drop_for_array(*ety, None),
```
Comment (compiler-errors) [inline compiler/rustc_mir_dataflow/src/elaborate_drops.rs:869]: nit, don't apply yet since bors is `try`ing: we can probably just remove this `None` argument, unless there are other callers to `open_drop_for_array`?

**Comment by compiler-errors** [comment]
Also this will eventually need a UI test :)

File: compiler/rustc_mir_dataflow/src/elaborate_drops.rs [hunk 2]
```diff
@@ -747,29 +747,6 @@ where
...
-                        ),
-                        self.elaborator.array_subpath(self.path, i, size),
-                    )
-                })
-                .collect();
-
-            if fields.iter().any(|(_, path)| path.is_some()) {
-                let (succ, unwind) = self.drop_ladder_bottom();
-                return self.drop_ladder(fields, succ, unwind).0;
-            }
```
Comment (tmiasko) [inline compiler/rustc_mir_dataflow/src/elaborate_drops.rs:770]: This code path is used when only some of the elements of the array need to be dropped.

**Comment by clubby789** [comment]
This now fixes the case from the example, but still blows up memory when the huge array is partially moved from.

**Comment by compiler-errors** [comment]
I'm happy to r+ this with a detailed comment, both explaining what the double iteration is doing and where it falls short, and a UI test.

**Comment by clubby789** [comment]
Added a test and explanation, but I'll try and investigate a better solution for this

**Comment by clubby789** [comment]
Found a new approach that seems to work, passing relevant drop tests locally.
1. Iterate over `array_subpath` for each index, recording contiguous ranges where `array_subpath` is `None`
2. For any indexes which are `Some`, push the current range, then path and then start a new range
3. Iterate backward over the ranges - for a `Drop`, make a place for the subslice and for a `Keep` make a place for the index
4. Pass these places and paths to the drop ladder as before

**Comment by compiler-errors** [comment]
Hmm... not sure if I'm fully qualified to review this new drop strategy.

r? compiler

**Review by davidtwco — APPROVED** [review]
LGTM - perf is mixed but I _think_ that's reasonable given that the memory usage for some cases was so high that it effectively prevented compilation.
