### PR TITLE
avoid suggesting traits from private dependencies

### LINKED ISSUE #138191: Imports from private std dependency `object` shouldn't be suggested
### Code

```Rust
struct VecReader(Vec<u8>);
impl std::io::Read for VecReader {
    fn read(&mut self, buf: &mut [u8]) -> std::io::Result<usize> {
        self.0.read(buf)
    }
}
```

### Current output

```Shell
error[E0599]: no method named `read` found for struct `Vec<u8>` in the current scope
 --> src/lib.rs:4:16
  |
4 |         self.0.read(buf)
  |                ^^^^
  |
  = help: items from traits can only be used if the trait is in scope
help: trait `ReadRef` which provides `read` is implemented but not in scope; perhaps you want to import it
  |
1 + use object::read::read_ref::ReadRef;
  |
help: there is a method `read_at` with a similar name
  |
4 |         self.0.read_at(buf)
  |                    +++
```

### Desired output

```Shell
error[E0599]: no method named `read` found for struct `Vec<u8>` in the current scope
 --> src/lib.rs:4:16
  |
4 |         self.0.read(buf)
  |                ^^^^
  |
```

### Rationale and extra context

`object` is not a dependency of my crate, so the suggestion cannot work (additionally, `object::read::read_ref::ReadRef` appears to be private too (?))

### Other cases

```Rust

```

### Rust Version

```Shell
rustc 1.87.0-nightly (b74da9613 2025-03-06)
binary: rustc
commit-hash: b74da9613a8cb5ba67a985f71325be0b7b16c0dd
commit-date: 2025-03-06
host: x86_64-unknown-linux-gnu
release: 1.87.0-nightly
LLVM version: 20.1.0
```

### Anything else?

_No response_

@rustbot label D-incorrect

### LINKED ISSUE #142676: rustc suggest adding an import of `compiler_builtins`
### Code

```Rust
fn f() {
    u8::cast_from_lossy(9);
}
```

### Current output

```Shell
Compiling playground v0.0.1 (/playground)
error[E0599]: no function or associated item named `cast_from_lossy` found for type `u8` in the current scope
 --> src/lib.rs:2:9
  |
2 |     u8::cast_from_lossy(9);
  |         ^^^^^^^^^^^^^^^ function or associated item not found in `u8`
  |
  = help: items from traits can only be used if the trait is in scope
help: trait `CastFrom` which provides `cast_from_lossy` is implemented but not in scope; perhaps you want to import it
  |
1 + use compiler_builtins::math::libm::support::int_traits::CastFrom;
  |

For more information about this error, try `rustc --explain E0599`.
error: could not compile `playground` (lib) due to 1 previous error
```

### Desired output

```Shell
Compiling playground v0.0.1 (/playground)
error[E0599]: no function or associated item named `cast_from_lossy` found for type `u8` in the current scope
 --> src/lib.rs:2:9
  |
2 |     u8::cast_from_lossy(9);
  |         ^^^^^^^^^^^^^^^ function or associated item not found in `u8`
  |

For more information about this error, try `rustc --explain E0599`.
error: could not compile `playground` (lib) due to 1 previous error
```

### Rationale and extra context

The suggested import does not work. Additionally, the import will be suggested even if it's already there.

### Other cases

```Rust
A previously reported issue #71090 was supposed to be fixed, but maybe it regressed?
```

### Rust Version

```Shell
rustc 1.87.0 (17067e9ac 2025-05-09)
binary: rustc
commit-hash: 17067e9ac6d7ecb70e50f92c1944e545188d2359
commit-date: 2025-05-09
host: x86_64-unknown-linux-gnu
release: 1.87.0
LLVM version: 20.1.1
```

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by Qelxiros**
fixes rust-lang/rust#142676
fixes rust-lang/rust#138191

r? @tgross35

### CODE REVIEW

**Comment by tgross35** [comment]
Oh that's a wonderfully small fix.

Were you able to reproduce this with something other than `object` and `compiler_builtins`? The test here is good to have, but it would also be good to extend it with an aux build that puts some known trait into scope (in case object/builtins ever wind up with a different API or not being deps). As an example of that, check out the tests at https://github.com/rust-lang/rust/tree/bc4376fa73b636eb6f2c7d48b1f731d70f022c4b/tests/ui/privacy/pub-priv-dep.

Just make sure it actually fails without the fix since I know this is a bit touchy.

File: compiler/rustc_hir_typeck/src/method/suggest.rs [hunk 1]
```diff
@@ -3477,9 +3477,10 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
         &self,
         err: &mut Diag<'_>,
         item_name: Ident,
-        valid_out_of_scope_traits: Vec<DefId>,
+        mut valid_out_of_scope_traits: Vec<DefId>,
         explain: bool,
     ) -> bool {
+        valid_out_of_scope_traits.retain(|id| !self.tcx.is_private_dep(id.krate));
```
Comment (tgross35) [inline compiler/rustc_hir_typeck/src/method/suggest.rs]: I think it might be better to rename `all_traits` to `all_visible_traits` (and update its usage) here https://github.com/rust-lang/rust/blob/2f3d599989883d0be932df3dceed65a6ec3274f8/compiler/rustc_hir_typeck/src/method/suggest.rs#L4387C15-L4389, then have that function call `visible_traits` https://github.com/rust-lang/rust/blob/bc4376fa73b636eb6f2c7d48b1f731d70f022c4b/compiler/rustc_middle/src/ty/context.rs#L2320-L2335. That seems likely to catch future problems that don't go through `suggest_valid_traits`.

@estebank any opinions here?

File: tests/ui/typeck/dont-suggest-private-dependencies.rs [hunk 2]
```diff
@@ -0,0 +1,15 @@
+// Don't suggest importing a function from a private dependency.
+
```
Comment (tgross35) [inline tests/ui/typeck/dont-suggest-private-dependencies.rs]: For future reference

```suggestion
// Don't suggest importing a function from a private dependency.
// Issue: https://github.com/rust-lang/rust/issues/138191
// Issue: https://github.com/rust-lang/rust/issues/142676
```

I think this test would actually pass even without the fix, have you checked that? Suggestions aren't asserted by default. The blessed stderr wouldn't match up of course, but we should check this with directives as well (less easy for someone to accidentally update)

```rust
// Check some known issues suggesting `.read` and `cast_from_lossy` from std-private deps
//@ forbid-output: compiler_builtins
//@ forbid-output: object
```

File: compiler/rustc_hir_typeck/src/method/suggest.rs (hunk 1 above)
Comment (estebank) [reply compiler/rustc_hir_typeck/src/method/suggest.rs]: Maybe renaming `all_traits` to `all_traits_inclusing_private` or something else verbose? `visible_traits` is what most people want/need so it should have the shorter, more findable name.

**Review by estebank — APPROVED** [review]

File: compiler/rustc_hir_typeck/src/method/suggest.rs (hunk 1 above)
Comment (tgross35) [reply compiler/rustc_hir_typeck/src/method/suggest.rs]: The actual tcx methods you mean? That seems reasonable to me to avoid the footgun. [It's only named in ~10 places](https://github.com/search?q=repo%3Arust-lang%2Frust+%2F%5Cball_traits%5Cb%2F+path%3Acompiler&type=code) so @Qelxiros feel free to either do that in a second commit in this PR, or as a separate PR.

Comment (Qelxiros) [reply compiler/rustc_hir_typeck/src/method/suggest.rs]: I'm happy to add it here. As a side note, `visible_traits` above uses `TyCtxt::is_user_visible_dep`, which allows imports from *direct* private dependencies. Using that instead of `is_private_dep` still removes the erroneous suggestions, is more in line with my mental model of what I'm trying to do here, and aligns with the documentation of `is_user_visible_dep`: https://github.com/rust-lang/rust/blob/bc4376fa73b636eb6f2c7d48b1f731d70f022c4b/compiler/rustc_middle/src/ty/util.rs#L838-L839 I also think that this will preserve the compiler's ability to make suggestions like these for library developers. Am I missing anything here?

**Comment by Qelxiros** [comment]
I'm assuming that ping is due to the function rename, see https://github.com/rust-lang/rust/pull/143038#discussion_r2169378772 for context

**Review by estebank — APPROVED** [review]

**Comment by Qelxiros** [comment]
@estebank @tgross35 anything preventing merging this?

**Review by tgross35 — APPROVED** [review]
LGTM as well, thank you for the changes!

One request if possible, are you able to adjust the history a bit? Split commits like:

1. Add the tests and run+bless it so we have the current failures in history (this is purely nice to have, feel free to disregard this if it's tricky)
2. Make `compiler-builtins` a private dep
3. Add the fix and update the test (everything else)

This is so we will be able to backport only the library changes (second commit) to beta, which should fix https://github.com/rust-lang/rust/issues/143215.

**Comment by tgross35** [comment]
> help: trait `CastFrom` which provides `cast_from_lossy` is implemented but not in scope; perhaps you want to import it

Awesome to see the failure reproduced in the first commit since I was having trouble getting it to work locally. Thank you for all the work here!

@bors r+

**Comment by tgross35** [comment]
@rust-lang/libs nominating commit ~~208ab5839866cc7d071c0eaedb045acb663b5d36~~ 1e6e4bb95ab7879283e4274bd80c3e04b1ea3f7c for backport, which should fix https://github.com/rust-lang/rust/issues/143215. The remaining commits aren't needed in beta since they are diagnostic changes.

@rustbot label +I-libs-nominated +beta-nominated

(updated team labels for the backport)

File: library/rustc-std-workspace-core/Cargo.toml [hunk 3]
```diff
@@ -1,3 +1,5 @@
+cargo-features = ["public-dependency"]
+
```
Comment (tgross35) [inline library/rustc-std-workspace-core/Cargo.toml:2]: Sorry, just noticed something. Could you update the second commit to mark `core` public (lower in this file than it lets me comment)? `core = { path = "../core", public = true }`

It should be public via other paths anyway but since `public-dependency` flips the defaults, this will make things consistent.

**Review by tgross35 — APPROVED** [review]

**Comment by matthiaskrgr** [comment]
@bors r-
https://github.com/rust-lang/rust/pull/143317#issuecomment-3027547971

**Comment by tgross35** [comment]
Since `read_at` is only available on Unix via `FileExt`, I guess that makes the rest of the diagnostic not cross-platform (which is preexisting). I think you could make this cross-platform by adding something like

```rust
// By default, the `read` diagnostic suggests `std::os::unix::fs::FileExt::read_at`. Add 
// something more likely to be recommended to make the diagnostic cross-platform. 
trait DecoyRead {
    fn read1(&self) {}
}
impl<T> DecoyRead for Vec<T> {}
```

**Comment by tgross35** [comment]
@bors2 try jobs=test-various

**Comment by tgross35** [comment]
Removing the nomination since https://github.com/rust-lang/rust/pull/143660 fixes it instead
