### PR TITLE
Remove duplicate error about raw underscore lifetime

### LINKED ISSUE #143152: `'r#_` gives two confusingly similar errors
### Code

```Rust
fn f<'r#_>(){}
```

### Current output

```Shell
error: `_` cannot be a raw lifetime
 --> src/lib.rs:1:6
  |
1 | fn f<'r#_>(){}
  |      ^^^^

error[E0637]: `'_` cannot be used here
 --> src/lib.rs:1:6
  |
1 | fn f<'r#_>(){}
  |      ^^^^ `'_` is a reserved lifetime name
```

### Desired output

```Shell
error: `_` cannot be a raw lifetime
 --> src/lib.rs:1:6
  |
1 | fn f<'r#_>(){}
  |      ^^^^
```

### Rationale and extra context

I believe the first diagnostic is from the lexer, and the second diagnostic occurs in parsing.

These diagnostics technically don't communicate the same information:
- the first diagnostic states that there is something wrong with the token's shape
- the second diagnostic states that if `'r#_` was a valid token (in which case it would be a synonym of `'_`, similar to `'r#static`), it would not be allowed in this position.

But both boil down to "this isn't allowed" without any suggestion for how to change it. And the second diagnostic is really about a *hypothetical* synonym to `'r#_`, but because that token is invalid, it has no synonyms.

So, i think the best alternative would be to only display the error saying that ``"`_` cannot be a raw lifetime"``

### Other cases

```Rust

```

### Rust Version

```Shell
rustc 1.90.0-nightly (bdaba05a9 2025-06-27)
binary: rustc
commit-hash: bdaba05a953eb5abeba0011cdda2560d157aed2e
commit-date: 2025-06-27
host: x86_64-unknown-linux-gnu
release: 1.90.0-nightly
LLVM version: 20.1.7
```

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by xizheyin**
Fixes rust-lang/rust#143152 

r? @fee1-dead

### CODE REVIEW

**Review by compiler-errors — CHANGES_REQUESTED** [review]
Can you instead use `tcx.sess.psess.raw_identifier_spans` to look for the raw lifetime span? I think we populate `raw_identifier_spans` with raw lifetimes too.

If not, then I don't think this hack should land. Using `span_to_snippet` here seems fragile.

**Comment by compiler-errors** [comment]
r? compiler-errors

**Comment by xizheyin** [comment]
> Can you instead use tcx.sess.psess.raw_identifier_spans to look for the raw lifetime span? I think we populate raw_identifier_spans with raw lifetimes too.

I have a try on it, and it works.

File: compiler/rustc_resolve/src/late.rs [hunk 1]
```diff
@@ -2902,7 +2902,16 @@ impl<'a, 'ast, 'ra, 'tcx> LateResolutionVisitor<'a, 'ast, 'ra, 'tcx> {
...
+                // To avoid emitting two duplicate errors, we need to check if the span is a raw underscore lifetime, see issue #143152
+                let is_raw_underscore = self
+                    .r
+                    .tcx
+                    .sess
+                    .psess
+                    .raw_identifier_spans
+                    .iter()
+                    .any(|span| span == param.span());
+                if param.ident.name == kw::UnderscoreLifetime && !is_raw_underscore {
```
Comment (xizheyin) [inline compiler/rustc_resolve/src/late.rs]: I'm wondering if I should split it into 2 parts, as this doesn't seem very aesthetically pleasing taking up so many lines. However it seems to give the wrong impression that the variable in the middle will be used multiple times.

File: compiler/rustc_resolve/src/late.rs [hunk 2]
```diff
@@ -2902,7 +2902,16 @@ impl<'a, 'ast, 'ra, 'tcx> LateResolutionVisitor<'a, 'ast, 'ra, 'tcx> {
...
                     self.r
                         .dcx()
                         .emit_err(errors::UnderscoreLifetimeIsReserved { span: param.ident.span });
```
Comment (compiler-errors) [inline compiler/rustc_resolve/src/late.rs]: Use `emit_unless`, and also we don't need to factor this into a variable.

```suggestion
                self.r
                  .dcx()
                  .create_err(errors::UnderscoreLifetimeIsReserved {
                      span: param.ident.span,
                  })
                  // To avoid emitting two duplicate errors, we need to check if the span is a raw underscore lifetime, see issue #143152
                  .emit_unless(
                      kw::UnderscoreLifetime
                          && self
                              .r
                              .tcx
                              .sess
                              .psess
                              .raw_identifier_spans
                              .iter()
                              .any(|span| span == param.span()),
                  );
```

Comment (compiler-errors) [reply compiler/rustc_resolve/src/late.rs]: Also I think the comment could be tweaked; instead of "two duplicate errors", b/c the error is not duplicate, we should say something different.

File: compiler/rustc_resolve/src/late.rs [hunk 3]
```diff
@@ -2902,7 +2902,16 @@ impl<'a, 'ast, 'ra, 'tcx> LateResolutionVisitor<'a, 'ast, 'ra, 'tcx> {
                     }
                 }
 
-                if param.ident.name == kw::UnderscoreLifetime {
+                // To avoid emitting two similar errors, we need to check if the span is a raw underscore lifetime, see issue #143152
```
Comment (xizheyin) [inline compiler/rustc_resolve/src/late.rs]: I use `similar` instead of `duplicate`.

**Review by xizheyin — COMMENTED** [review]
We may not be able to use `emit_unless`, because there are other logic in the if block.
```
                if param.ident.name == kw::UnderscoreLifetime && !is_raw_underscore {
                    self.r
                        .dcx()
                        .emit_err(errors::UnderscoreLifetimeIsReserved { span: param.ident.span });
                    // Record lifetime res, so lowering knows there is something fishy.
                    self.record_lifetime_param(param.id, LifetimeRes::Error);
                    continue;
                }
```

File: compiler/rustc_resolve/src/late.rs [hunk 4]
```diff
@@ -2902,7 +2902,16 @@ impl<'a, 'ast, 'ra, 'tcx> LateResolutionVisitor<'a, 'ast, 'ra, 'tcx> {
...
+                let is_raw_underscore = self
+                    .r
+                    .tcx
+                    .sess
+                    .psess
+                    .raw_identifier_spans
+                    .iter()
+                    .any(|span| span == param.span());
+                if param.ident.name == kw::UnderscoreLifetime && !is_raw_underscore {
```
Comment (compiler-errors) [inline compiler/rustc_resolve/src/late.rs]: You should still be able to `emit_unless(is_raw_underscore)`. I don't think calling `self.record_lifetime_param(param.id, LifetimeRes::Error);` matters if it's a raw underscore or not.

**Review by compiler-errors — CHANGES_REQUESTED** [review]
> We may not be able to use emit_unless, because there are other logic in the if block.

Did you *try* it? 

Just try calling `self.record_lifetime_param(param.id, LifetimeRes::Error);` unconditionally, it should be fine. We should definitely be delaying a bug.

File: compiler/rustc_resolve/src/late.rs (hunk 4 above)
Comment (compiler-errors) [reply compiler/rustc_resolve/src/late.rs]: i.e.

```
if param.ident.name == kw::UnderscoreLifetime {
  let is_raw_underscore = self
    .r
    .tcx
    .sess
    .psess
    .raw_identifier_spans
    .iter()
    .any(|span| span == param.span());
    self.r
      .dcx()
      .create_err(errors::UnderscoreLifetimeIsReserved { span: param.ident.span })
      .emit_unless(is_raw_lifetime);
  // Record lifetime res, so lowering knows there is something fishy.
  self.record_lifetime_param(param.id, LifetimeRes::Error);
  continue;
}
```

File: compiler/rustc_resolve/src/late.rs [hunk 5]
```diff
@@ -2899,9 +2899,21 @@ impl<'a, 'ast, 'ra, 'tcx> LateResolutionVisitor<'a, 'ast, 'ra, 'tcx> {
...
+                        .psess
+                        .raw_identifier_spans
+                        .iter()
+                        .any(|span| span == param.span());
+
                     self.r
                         .dcx()
-                        .emit_err(errors::UnderscoreLifetimeIsReserved { span: param.ident.span });
+                        .create_err(errors::UnderscoreLifetimeIsReserved { span: param.ident.span })
+                        .emit_unless(is_raw_underscore_lifetime);
```
Comment (xizheyin) [inline compiler/rustc_resolve/src/late.rs:2916]: Oh my bad, the code now doesn't affect the original logic.

**Review by xizheyin — COMMENTED** [review]
By the way, `emit_unless` doesn't seem intuitive and is very misleading, is it possible to give it a new name, e.g. `emit_or_delay_as_bug`

@rustbot ready
