### PR TITLE
Fix wrong "move keyword" suggestion for async gen block

### LINKED ISSUE #139839: wrong help message
I tried this code:

```rust
Box::pin(
                async gen {
                    loop {
                        yield tunnel_manager.next_broadcast().await;
                    }
                }
                .into_stream(),
)
```

I expected to see this happen:

when rustc tell me

```
async gen block may outlive the current function, but it borrows `tunnel_manager`, which is owned by the current function
```

and give me a right help message, to add the `move` keyword after the `gen`

Instead, this happened:

it give me

```
help: to force the async gen block to take ownership of `tunnel_manager` (and any other referenced variables), use the `move` keyword
    |
197 |                 async move gen {
    |                       ++++

For more information about this error, try `rustc --explain E0373`.
```

follow this help message, now rustc report

```
197 |                 async move gen {
    |                            ^^^ expected one of `async`, `|`, or `||`
```

so I have to tried `async gen move`, and it works for me

### Meta

`rustc --version --verbose`:
```
rustc 1.88.0-nightly (092a284ba 2025-04-13)
binary: rustc
commit-hash: 092a284ba0421695f2032c947765429fd7095796
commit-date: 2025-04-13
host: x86_64-unknown-linux-gnu
release: 1.88.0-nightly
LLVM version: 20.1.2
```
<details><summary>Backtrace</summary>
<p>

```
<backtrace>
```

</p>
</details>

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Fixes #139839.

It was just missing a string comparison with `async gen`.

### CODE REVIEW

**Comment by compiler-errors** [comment]
Tests are typically put into a subdirectory of `ui/` rather than the top. Could you move it? There's the `async-await/` dir, which probably has a subdirectory inside of *that* for async gen stuff.

@rustbot author

**Comment by compiler-errors** [comment]
Also squash this into one commit please

File: compiler/rustc_borrowck/src/diagnostics/conflict_errors.rs [hunk 1]
```diff
@@ -3376,9 +3376,12 @@ impl<'infcx, 'tcx> MirBorrowckCtxt<'_, 'infcx, 'tcx> {
 
         let (sugg_span, suggestion) = match tcx.sess.source_map().span_to_snippet(args_span) {
             Ok(string) => {
-                let coro_prefix = if string.starts_with("async") {
-                    // `async` is 5 chars long. Not using `.len()` to avoid the cast from `usize`
-                    // to `u32`.
+                let coro_prefix = if string.starts_with("async gen") {
```
Comment (compiler-errors) [inline compiler/rustc_borrowck/src/diagnostics/conflict_errors.rs:3379]: Also this is still broken b/c it doesn't take into account the fact that the rendered source may have spaces `async     gen {}`

**Comment by GuillaumeGomez** [comment]
Ah right, tab characters are triggering `tidy`. Well, backline and whitespace should hopefully be enough.

**Review by compiler-errors — APPROVED** [review]
