### PR TITLE
Show trait method signature when impl differs

### LINKED ISSUE #28011: Friendlier compiler message for incorrect trait method signatures
When implementing a trait, it would be useful to see the expected method signature in compiler error messages. Example

```
impl std::fmt::Display for MyType {
   // Not sure what to put here so I stub it and hope to get help from error
   fn fmt() -> () { } 
}   
```

The current error message for E0186 only lets me partially resolve the issue:

```
error: method `fmt` has a `&self` declaration in the trait, but not in the impl [E0186]
```

It would be more friendly to the user if the message showed both the actual and expected method signatures. 

```
Incorrect method signature for trait `Display` method `fmt`
Actual signature    fn fmt() -> ()
Expected signature  fn fmt(&self, &mut Formatter) -> Result<(), Error>
```

### PR DESCRIPTION
**Pull request by estebank**
When the trait's span is available, it is already being used, add a
`note` for the cases where the span isn't available:

<pre>
error[E0053]: <b>method `fmt` has an incompatible type for trait</b>
  --> $DIR/trait_type.rs:17:4
   |
17 |    fn fmt(&self, x: &str) -> () { }
   |    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ types differ in mutability
   |
   = note: expected type `<b>fn(&MyType, &mut std::fmt::Formatter<'_>) -> std::result::Result<(), std::fmt::Error></b>`
              found type `<b>fn(&MyType, &str)</b>`

error[E0050]: <b>method `fmt` has 1 parameter but the declaration in trait `std::fmt::Display::fmt` has 2</b>
  --> $DIR/trait_type.rs:21:11
   |
21 |    fn fmt(&self) -> () { }
   |           ^^^^^ expected 2 parameters, found 1
   |
   = note: `fmt` from trait: `<b>fn(&Self, &mut std::fmt::Formatter<'_>) -> std::result::Result<(), std::fmt::Error></b>`

error[E0186]: <b>method `fmt` has a `&self` declaration in the trait, but not in the impl</b>
  --> $DIR/trait_type.rs:25:4
   |
25 |    fn fmt() -> () { }
   |    ^^^^^^^^^^^^^^^^^^ expected `&self` in impl
   |
   = note: `fmt` from trait: `<b>fn(&Self, &mut std::fmt::Formatter<'_>) -> std::result::Result<(), std::fmt::Error></b>`

error[E0046]: <b>not all trait items implemented, missing: `fmt`</b>
  --> $DIR/trait_type.rs:28:1
   |
28 | impl std::fmt::Display for MyType4 {}
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ missing `fmt` in implementation
   |
   = note: `fmt` from trait: `<b>fn(&Self, &mut std::fmt::Formatter<'_>) -> std::result::Result<(), std::fmt::Error></b>`
</code></pre>

Fix #28011.

### CODE REVIEW

**Comment by shepmaster** [comment]
Thanks @estebank ! We'll get a wonderful reviewer like @arielb1 or someone equally awesome on the case.

File: src/librustc/ty/mod.rs [hunk 1]
```diff
@@ -221,6 +221,18 @@ impl AssociatedItem {
             AssociatedKind::Method => !self.method_has_self_argument,
         }
     }
+
+    pub fn signature<'a, 'tcx>(&self, tcx: &TyCtxt<'a, 'tcx, 'tcx>) -> String {
+        match self.kind {
+            ty::AssociatedKind::Method => {
+                format!("{}", tcx.type_of(self.def_id).fn_sig().0)
```
Comment (arielb1) [inline src/librustc/ty/mod.rs]: why the `.0`?

**Comment by arielb1** [comment]
Nice! r+ with `skip_binder` and comment instead of `.0` (yes I know the `.0` is in the original).

**Comment by arielb1** [comment]
@bors r-

> with `skip_binder` and comment instead of `.0`

There should be comments for all `skip_binder` calls. For example, here we would want
```Rust
    pub fn signature<'a, 'tcx>(&self, tcx: &TyCtxt<'a, 'tcx, 'tcx>) -> String {
        match self.kind {
            ty::AssociatedKind::Method => {
                format!("{}",
                    // We skip the binder here because the binder would deanonymize all
                    // late-bound regions, and we don't want signatures to show up asshow up as
                    // `for<'r> fn(&'r MyType)`. Pretty-printing handles late-bound regions just
                    // fine, showing `fn(&MyType)`.
                    tcx.type_of(self.def_id).fn_sig().skip_binder())
            }
            ty::AssociatedKind::Type => format!("type {};", self.name.to_string()),
            ty::AssociatedKind::Const => {
                format!("const {}: {:?};", self.name.to_string(), tcx.type_of(self.def_id))
            }
        }
+    }
```

**Comment by estebank** [comment]
@arielb1 forgot about the comment. Added the one proposed.

@bors r=arielb1
