### PR TITLE
rustdoc: set the default edition when pre-parsing a doctest

### LINKED ISSUE #59313: `async move` breaks doc tests
Steps to reproduce:

1. Create a library project with the following contents in `lib.rs`:

```rust
//! ```
//! #![feature(async_await)]
//!
//! fn foo() {
//!     drop(async move {});
//! }
//! ```
```

2. Run tests:

```console
repro master $ cargo --version
cargo 1.35.0-nightly (0e35bd8af 2019-03-13)
repro master $ rustc --version
rustc 1.35.0-nightly (3eb4890df 2019-03-19)
repro master $ cargo test
    Finished dev [unoptimized + debuginfo] target(s) in 0.00s
     Running target/debug/deps/repro-0e401502cf52c662

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

   Doc-tests repro

running 1 test
test src/lib.rs -  (line 1) ... FAILED

failures:

failures:
    src/lib.rs -  (line 1)

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out

error: test failed, to rerun pass '--doc'
```

3. Now delete the `move` inside `async move {}`:

```rust
//! ```
//! #![feature(async_await)]
//!
//! fn foo() {
//!     drop(async {});
//! }
//! ```
```

4. Run tests again:

```console
repro master $ cargo test
   Compiling repro v0.1.0 (/home/stjepan/work/repro)
    Finished dev [unoptimized + debuginfo] target(s) in 0.25s
     Running target/debug/deps/repro-0e401502cf52c662

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

   Doc-tests repro

running 1 test
test src/lib.rs -  (line 1) ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out
```

### PR DESCRIPTION
**Pull request by QuietMisdreavus**
Fixes https://github.com/rust-lang/rust/issues/59313 (possibly more? i think we've had issues with parsing edition-specific syntax in doctests at some point)

When handling a doctest, rustdoc needs to parse it beforehand, so that it can see whether it declares a `fn main` or `extern crate my_crate` explicitly. However, while doing this, rustdoc doesn't set the "default edition" used by the parser like the regular compilation runs do. This caused a problem when parsing a doctest with an `async move` block in it, since it was expecting the `move` keyword to start a closure, not a block.

This PR changes the `rustdoc::test::make_test` function to set the parser's default edition while looking for a main function and `extern crate` statement. However, to do this, `make_test` needs to know what edition to set. Since this is also used during the HTML rendering process (to make playground URLs), now the HTML renderer needs to know about the default edition. Upshot: rendering standalone markdown files can now accept a "default edition" for their doctests with the `--edition` flag! (I'm pretty sure i waffled around how to set that a long time ago when we first added the `--edition` flag... `>_>`)

I'm posting this before i stop for the night so that i can write this description while it's still in my head, but before this merges i want to make sure that (1) the `rustdoc-ui/failed-doctest-output` test still works (i expect it doesn't), and (2) i add a test with the sample from the linked issue.

### CODE REVIEW

**Comment by QuietMisdreavus** [comment]
Turns out, i guessed the wrong failing test. The `failed-doctest-output` test is fine, but the playground URL tests failed because i made it start emitting the edition flag all the time. I've also pushed up the test from the linked issue, so this should be ready to go now.

r? @rust-lang/rustdoc

File: src/librustdoc/config.rs [hunk 1]
```diff
@@ -383,27 +383,28 @@ impl Options {
             }
         }
 
+        let edition = matches.opt_str("edition").unwrap_or("2015".to_string());
```
Comment (GuillaumeGomez) [inline src/librustdoc/config.rs]: We tend to prefer `.unwrap_or_else`. ;)

**Comment by GuillaumeGomez** [comment]
Just a small nit but everything else looks good. r=me once nit fixed and CI passed.

File: src/librustdoc/config.rs (hunk 1 above)
Comment (QuietMisdreavus) [reply src/librustdoc/config.rs]: This was existing code that i moved for this PR, but i can fix it.

**Comment by ollie27** [comment]
I don't think that this completely fixes #59313 because rustdoc will still fail while looking for `fn main` if the edition is set to 2015. rustdoc should never fail at that stage and it means you don't get a useful error message:

```
running 1 test
test issue-59313.rs -  (line 1) ... FAILED

failures:

failures:
    issue-59313.rs -  (line 1)

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out
```

It should output:

```
running 1 test
test issue-59313.rs -  (line 1) ... FAILED

failures:

---- issue-59313.rs -  (line 1) stdout ----
error: expected one of `!`, `)`, `,`, `.`, `::`, `?`, `{`, or an operator, found `move`
 --> issue-59313.rs:5:16
  |
6 |     drop(async move {});
  |                ^^^^ expected one of 8 possible tokens here

error: aborting due to previous error

thread 'issue-59313.rs -  (line 1)' panicked at 'couldn't compile the test', src\librustdoc\test.rs:310:13
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.


failures:
    issue-59313.rs -  (line 1)

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out
```

**Comment by QuietMisdreavus** [comment]
@ollie27 That's a valid point. To solve that, i think we'd have to change this line in `Parser::expect_one_of`:

https://github.com/rust-lang/rust/blob/22fa4bb0ebdfe9fcd7962f1fa6e758c036c878e6/src/libsyntax/parse/parser.rs#L791-L792

That `FatalError.raise` is what's causing the parsing thread to abort without an error message. I'm not super sure what i should replace it with, though, so i need to call in @rust-lang/compiler to see if someone who knows their way around the parser can give some guidance.

**Comment by ollie27** [comment]
How about wrapping the code looking for `fn main` in a `panic::catch_unwind`?

**Comment by Zoxc** [comment]
This PR seems to have quite a lot of overlap with https://github.com/rust-lang/rust/pull/59742, which may fix the same issue as a side effect.

**Comment by QuietMisdreavus** [comment]
@Zoxc Oh yeah, you do seem to make a lot of the same changes! I gave your branch a try, and it does make the doctest pass under 2018, but it doesn't solve the issue that @ollie27 mentioned - there is still no output for the failure under 2015. I'd like to fold my work into your PR somehow and have someone check out the `FatalError` thing separately, if possible.

(On a side note, it strikes me as odd that we have a `DEFAULT_EDITION` constant but not an implementation of the `Default` trait... :thinking:)

**Comment by QuietMisdreavus** [comment]
Looks like the issue @ollie27 mentioned will get fixed by https://github.com/rust-lang/rust/pull/60220, and @Zoxc's PR does almost the same thing this one does. (This one goes farther in spreading the edition-passing through rustdoc's code itself, so it's not the *same*, but fixes the same issue in the end.)

@Zoxc Should we land this PR so you can use the other rustdoc changes in your PR?

**Comment by Zoxc** [comment]
@QuietMisdreavus Don't block on my PR

**Comment by estebank** [comment]
@QuietMisdreavus that hard failure is there because we want to avoid spamming the user with errors caused by error recovery, in other words, spurious errors. It should be possible to make this configurable on the `Parser` and have rustdoc configure it to be less dogmatic and continue returning an `Err` and maybe generating a few extra errors while keeping the output clean-ish for rustc users.

**Comment by QuietMisdreavus** [comment]
I've rebased the PR to include https://github.com/rust-lang/rust/pull/60220. IMO we should get this in so that it can be used in https://github.com/rust-lang/rust/pull/59742.

**Comment by GuillaumeGomez** [comment]
Looks good to me. Just waiting for @ollie27 confirmation.

**Comment by Zoxc** [comment]
What is this PR waiting on now?

**Comment by ollie27** [comment]
My bad, lets get this in.

@bors r+
