### PR TITLE
Suggest importing the right kind of macro.

### LINKED ISSUE #88228: Missing derive macro suggests importing regular macro
Found while working on https://github.com/rust-lang/rust/issues/88206

```
error: cannot find derive macro `println` in this scope
  --> src/main.rs:16:10
   |
16 | #[derive(println)]
   |          ^^^^^^^
   |
   = note: consider importing this macro:
           std::println
```

### PR DESCRIPTION
**Pull request by m-ou-se**
Fixes #88228.

r? @estebank

### CODE REVIEW

File: compiler/rustc_resolve/src/diagnostics.rs [hunk 1]
```diff
@@ -950,9 +950,7 @@ impl<'a> Resolver<'a> {
         self.add_typo_suggestion(err, suggestion, ident.span);
 
         let import_suggestions =
-            self.lookup_import_candidates(ident, Namespace::MacroNS, parent_scope, |res| {
-                matches!(res, Res::Def(DefKind::Macro(MacroKind::Bang), _))
-            });
+            self.lookup_import_candidates(ident, Namespace::MacroNS, parent_scope, is_expected);
```
Comment (estebank) [inline compiler/rustc_resolve/src/diagnostics.rs:953]: This is gonna have a merge conflict with the other PR, right?

**Review by estebank — APPROVED** [review]

File: compiler/rustc_resolve/src/diagnostics.rs (hunk 1 above)
Comment (m-ou-se) [reply compiler/rustc_resolve/src/diagnostics.rs:953]: That other PR includes this one as the first commit (with identical hash even), so should be fine. ^^
