### PR TITLE
make abi_unsupported_vector_types a hard error

### LINKED ISSUE #116558: The `extern "C"` ABI of SIMD vector types depends on target features (tracking issue for `abi_unsupported_vector_types` future-incompatibility lint)
The following program has UB, for very surprising reasons:
```rust
use std::mem::transmute;
#[cfg(target_arch = "x86")]
use std::arch::x86::*;
#[cfg(target_arch = "x86_64")]
use std::arch::x86_64::*;

extern "C" fn no_target_feature(_dummy: f32, x: __m256) {
    let val = unsafe { transmute::<_, [u32; 8]>(x) };
    dbg!(val);
}

#[target_feature(enable = "avx")]
unsafe fn with_target_feature(x: __m256) {
  // Here we're seemingly just calling a safe function... but actually this call is UB!
  // Caller and callee do not agree on the ABI; specifically they disagree on how the
  // `__m256` argument gets passed.
  no_target_feature(0.0, x);
}

fn main() {
    assert!(is_x86_feature_detected!("avx"));
    // SAFETY: we checked that the `avx` feature is present.
    unsafe {
        with_target_feature(transmute([1; 8]));
    }
}
```
The reason is that the ABI of the `__m256` type depends on the set of target features, so the caller (`with_target_feature`) and callee (`no_target_feature`) do not agree on how the argument should be passed. The result is a [vector half-filled with junk](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=ee15f570ee5df1ecbec6321c44066008). (The same issue also arises in the other direction, where the caller has fewer features than the callee: [example here](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=78a91a7266b7e39fe539c1e8d8c9892d).)

Currently, we have no good way to do correct code generation here. See https://github.com/rust-lang/rust/issues/132865 for a discussion of how we could support such code in the future; it will require some non-trivial work. So instead, the current plan is to reject such code entirely.

This is the tracking issue for the lint that moves us in that direction. The hope is that passing SIMD vectors across a C ABI is sufficiently rare, and most of the cases being rejected have anyway already been broken, that we can reject this without much of an ecosystem impact. Crater showed no regressions. 

This is linted against since Rust 1.84, and shown in future breakage reports starting with Rust 1.85. The plan is to move to a hard error with Rust 1.87. 

**When this becomes a hard error:**

- We can probably remove the error tracked at https://github.com/rust-lang/rust/issues/63068?
- And also the warning triggered [in this example](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=10c712ef153066a8c1829f6c7f41a3f4)?

----

**Original issue text:**

I'm not sure if this is currently even properly documented? We are mentioning it in https://github.com/rust-lang/rust/pull/115476 but the program above doesn't involve any function pointers so we really cannot expect people to be aware of that part of the docs. We show a general warning about the type not being FFI-compatible, but that warning shows up a lot and anyway in this case both caller and callee are Rust functions!

I think we need to do better here, but backwards compatibility might make that hard. @chorman0773 suggested we should just reject functions like `no_target_feature` that take an AVX type by-val without having declared the AVX feature. That seems reasonable; a crater run would be needed to assess whether it breaks too much code. An alternative might be to have a deny-by-default lint that very clearly explains what is happening.

There are also details to work out wrt what exactly the lint should check. Newtypes around `__m256` will have the same problem. What about other larger types that contain `__m256`? Behind a ptr indirection it's obviously fine, but what about `(__m256, __m256)`? If we apply the `ScalarPair` optimization this will be passed in registers even on x86.

A possible place to put the check could be [somewhere around here](https://github.com/rust-lang/rust/blob/8fa7bdf191d8658e5ab670766ac0b2d40c7d83c2/compiler/rustc_codegen_ssa/src/codegen_attrs.rs#L279-L309).

In terms of process, I am not sure if an RFC is required; a t-compiler MCP might be sufficient. Currently we accept code that clearly doesn't do what it looks like it should do.

And finally -- are there any other targets (besides x86 and x86-64) that have target-features that affect the ABI? They should get the same treatment.

Note that this is different from https://github.com/rust-lang/rust/issues/116344 in two ways:
- This issue only affects non-"Rust" ABIs; the other issue affects even the "Rust" ABI. (The Rust ABI passes `__m256` by-pointer exactly to work-around this issue.)
- This issue comes about when the user enables extra features (which is possible also locally via `#[target_feature]`), the other issue comes about when the user *disables* features (which is only possible on a per-crate level via `-C`, and if you're mixing crates with different `-C` flags then you're already already on very shaky grounds -- we do that with std but nobody else really gets to do that, I think).

Cc @workingjubilee more ABI fun ;)

### PR DESCRIPTION
**Pull request by RalfJung**
Fixes https://github.com/rust-lang/rust/issues/116558 by completing the transition; see that issue for context. The lint was introduced with Rust 1.84 and this has been shown in cargo's future breakage reports since Rust 1.85, released 6 weeks ago, and so far we got 0 complaints by users. There's not even a backlink on the tracking issue. We did a [crater run](https://github.com/rust-lang/rust/pull/127731#issuecomment-2286736295) when the lint was originally added and found no breakage. So I don't think we need another crater run now, but I can do one if the team prefers that.

https://github.com/rust-lang/rust/issues/131800 is done, so for most current targets (in particular, all tier 1 and tier 2 targets) we have the information to implement this check (modulo the targets where we don't properly support SIMD vectors yet, see the sub-issues of https://github.com/rust-lang/rust/issues/116558). If a new target gets added in the future, it will default to reject all SIMD vector types until proper information is added, which is the default we want.

This will need approval by for @rust-lang/lang. Cc @workingjubilee @veluca93 

try-job: test-various
try-job: armhf-gnu
try-job: dist-i586-gnu-i586-i686-musl

### CODE REVIEW

File: tests/codegen/regparm-inreg.rs [hunk 1]
```diff
@@ -3,7 +3,7 @@
 // x86 only.
 
 //@ add-core-stubs
-//@ compile-flags: --target i686-unknown-linux-gnu -Cno-prepopulate-passes -Copt-level=3
+//@ compile-flags: --target i686-unknown-linux-gnu -Cno-prepopulate-passes -Copt-level=3 -Ctarget-feature=+avx
```
Comment (RalfJung) [inline tests/codegen/regparm-inreg.rs:6]: @azhogin this test was using SIMD vector types without the appropriate target feature... I hope adding the target feature preserves the meaning of the test.

File: compiler/rustc_codegen_cranelift/example/std_example.rs [hunk 2]
```diff
@@ -8,9 +8,6 @@
     unboxed_closures
 )]
 #![allow(internal_features)]
-// FIXME once abi_unsupported_vector_types is a hard error disable the foo test when the respective
-// target feature is not enabled.
```
Comment (RalfJung) [inline compiler/rustc_codegen_cranelift/example/std_example.rs:12]: @bjorn3 apparently I have to "disable the foo test when the respective target feature is not enabled". What does that mean?^^

Comment (bjorn3) [reply compiler/rustc_codegen_cranelift/example/std_example.rs:12]: There is a function called `foo` which accepts a `I64X2` type. It can only be used when the sse target feature is enabled. Given that cg_clif always enables the sse target feature for non -none targets, I don't think it is necessary to disable it after all. So nothing needs to be changed in this PR.

File: tests/run-make/simd-ffi/rmake.rs [hunk 3]
```diff
@@ -56,7 +56,7 @@ fn main() {
             .target(&target)
             .emit("llvm-ir,asm")
             .input("simd.rs")
-            .arg("-Ctarget-feature=-soft-float,+neon,+sse")
+            .arg("-Ctarget-feature=-soft-float,+neon,+sse2,+msa")
             .arg(&format!("-Cextra-filename=-{target}"))
             .run();
```
Comment (RalfJung) [inline tests/run-make/simd-ffi/rmake.rs:61]: This test will become a complete nightmare to maintain when we start to properly enforce some basic consistency of target features.

**Comment by ehuss** [comment]
@RalfJung Do you think we can get this documented in the reference? Like maybe somewhere in the [target_feature](https://doc.rust-lang.org/nightly/reference/attributes/codegen.html#the-target_feature-attribute) documentation or probably it makes more sense to be a part of the [abi chapter](https://doc.rust-lang.org/nightly/reference/abi.html) with the [abi chapter rework](https://github.com/rust-lang/reference/pull/1545)? Although I'm a little confused since Connor [removed the SIMD section](https://github.com/rust-lang/reference/pull/1545/commits/79a248d608c9f499e2a3452112c71ae957e0dcbf) and I'm not sure why.

My uncertainty is emphasized because we currently don't really document SIMD, and I don't know how we plan to do that.

File: tests/codegen/regparm-inreg.rs (hunk 1 above)
Comment (workingjubilee) [reply tests/codegen/regparm-inreg.rs:6]: It does.

**Comment by RalfJung** [comment]
> @RalfJung Do you think we can get this documented in the reference? Like maybe somewhere in the [target_feature](https://doc.rust-lang.org/nightly/reference/attributes/codegen.html#the-target_feature-attribute) documentation or probably it makes more sense to be a part of the [abi chapter](https://doc.rust-lang.org/nightly/reference/abi.html) with the [abi chapter rework](https://github.com/rust-lang/reference/pull/1545)? Although I'm a little confused since Connor [removed the SIMD section](https://github.com/rust-lang/reference/pull/1545/commits/79a248d608c9f499e2a3452112c71ae957e0dcbf) and I'm not sure why.
> 
> My uncertainty is emphasized because we currently don't really document SIMD, and I don't know how we plan to do that.

Seems like this should be part of https://github.com/rust-lang/reference/pull/1545 so I'd rather not add a separate PR now, that would just be a huge conflict.

**Review by fee1-dead — APPROVED** [review]
Compiler changes LGTM

**Comment by traviscross** [comment]
Sounds right to me.

@rfcbot reviewed

**Review by traviscross — APPROVED** [review]
Looks right to me.  I see that @fee1-dead already approved also, so `r=fee1-dead,traviscross` after resolving the conflicts.

**Comment by traviscross** [comment]
Actually, I see now that @fee1-dead already had a [look](https://github.com/rust-lang/rust/pull/139309#pullrequestreview-2752619564), so let's...

@bors r=fee1-dead,traviscross rollup

**Comment by ChrisDenton** [comment]
I think this failed in rollup: https://github.com/rust-lang/rust/pull/140078#issuecomment-2817180956

@bors r-

**Comment by ChrisDenton** [comment]
Failed in rollup: https://github.com/rust-lang/rust/pull/140161#issuecomment-2821670255

@bors r-
