### PR TITLE
When declaring a declarative macro in an item it's only accessible inside it

### LINKED ISSUE #63164: internal error: entered unreachable code
Seems to be something to do with Rocket. Having a `get` on the internal function is causing the compiler to blow up.

```rust
fn moo() {
    #[get("/moo")]
    fn get() -> String {
        "moo".to_string()
    }
}
```

Version:

```
rustc 1.38.0-nightly (dddb7fca0 2019-07-30)
binary: rustc
commit-hash: dddb7fca09dc817ba275602b950bb81a9032fb6d
commit-date: 2019-07-30
host: x86_64-unknown-linux-gnu
release: 1.38.0-nightly
LLVM version: 9.0
```

Stack trace:

```
thread 'rustc' panicked at 'internal error: entered unreachable code', src/librustc_privacy/lib.rs:767:17
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.29/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.29/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:47
   3: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:36
   4: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:200
   5: std::panicking::default_hook
             at src/libstd/panicking.rs:214
   6: rustc::util::common::panic_hook
   7: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:481
   8: std::panicking::begin_panic
   9: <rustc_privacy::EmbargoVisitor as rustc::hir::intravisit::Visitor>::visit_macro_def
  10: rustc_privacy::privacy_access_levels
  11: rustc::ty::query::__query_compute::privacy_access_levels
  12: rustc::dep_graph::graph::DepGraph::with_task_impl
  13: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt>::get_query
  14: rustc::util::common::time
  15: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
  16: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:80
  17: rustc_interface::passes::analysis::{{closure}}
  18: rustc::util::common::time
  19: rustc_interface::passes::analysis
  20: rustc::ty::query::__query_compute::analysis
  21: rustc::dep_graph::graph::DepGraph::with_task_impl
  22: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt>::get_query
  23: rustc_interface::passes::BoxedGlobalCtxt::access::{{closure}}
  24: rustc_interface::passes::create_global_ctxt::{{closure}}
  25: rustc_interface::interface::run_compiler_in_existing_thread_pool
  26: std::thread::local::LocalKey<T>::with
  27: syntax::with_globals
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
query stack during panic:
#0 [privacy_access_levels] privacy access levels
#1 [analysis] running analysis passes on this crate
end of query stack
```

### PR DESCRIPTION
**Pull request by estebank**
Fix #63164.
r? @petrochenkov

### CODE REVIEW

File: src/test/ui/macros/macro-in-fn.rs [hunk 1]
```diff
@@ -0,0 +1,9 @@
+#![feature(decl_macro)]
+
+pub fn moo() {
+    pub macro ABC() {{}}
+}
+
+fn main() {
+    ABC!(); //~ ERROR cannot find macro `ABC!` in this scope
```
Comment (hellow554) [inline src/test/ui/macros/macro-in-fn.rs]: Shouldn't this be `moo::ABC!`? (In similarity if `moo` would be a `mod`)

Comment (petrochenkov) [inline src/test/ui/macros/macro-in-fn.rs]: This line actually prevents the ICE.
With this error compilation stops after type checking and never reaches the privacy-reachability pass that ICEs.

Comment (petrochenkov) [reply src/test/ui/macros/macro-in-fn.rs]: (So it's better to remove it and turn the test into `check-pass`.)

File: src/librustc/hir/map/mod.rs [hunk 2]
```diff
@@ -514,18 +514,21 @@ impl<'hir> Map<'hir> {
         &self.forest.krate.attrs
     }
 
-    pub fn get_module(&self, module: DefId) -> (&'hir Mod, Span, HirId)
-    {
+    pub fn get_module(&self, module: DefId) -> (&'hir Mod, Span, HirId) {
+        self.get_if_module(module).expect("not a module")
+    }
+
+    pub fn get_if_module(&self, module: DefId) -> Option<(&'hir Mod, Span, HirId)> {
```
Comment (petrochenkov) [inline src/librustc/hir/map/mod.rs]:
```suggestion
    pub fn opt_get_module(&self, module: DefId) -> Option<(&'hir Mod, Span, HirId)> {
```

Comment (petrochenkov) [reply src/librustc/hir/map/mod.rs]: Actually, from looking at what `update_macro_reachable_mod` does, it may be better to keep this function alone and directly match on the result of `find_entry`/`get_if_local` there.

File: src/librustc_privacy/lib.rs [hunk 3]
```diff
@@ -508,39 +508,45 @@ impl EmbargoVisitor<'tcx> {
...
                         }
                     }
                 }
             }
+        } else if let Some(hir::Node::Item(hir::Item {
+            hir_id,
+            ..
+        })) = self.tcx.hir().get_if_local(module_def_id) { // #63164
+            // `macro` defined inside of an item is only visible inside of that item's scope.
+            set_vis(self, *hir_id);
```
Comment (petrochenkov) [inline src/librustc_privacy/lib.rs]: I'm not sure this line is doing something meaningful.
I'm also not sure how a macro in a nameless block ended up reachable at all.
Need to think a bit and re-read the code around.

Comment (matthewjasper) [reply src/librustc_privacy/lib.rs]: I think the issue is here:
https://github.com/rust-lang/rust/blob/9dd5c191993aab6c2f1538eb8ab69afdc4b6e67a/src/librustc_privacy/lib.rs#L890-L894

This should return early when `module_id` doesn't refer to a module.

Comment (petrochenkov) [reply src/librustc_privacy/lib.rs]: Yeah, this should be the right fix, we can bail out from `fn visit_macro_def` early if the macro's parent is not a module.

(Unless it's `#[rustc_macro_transparency = "opaque"] #[macro_export] macro_rules! { ... }` inside an unnamed block, but anything involving `rustc_*` attributes is entirely internal and not publicly supported.)

Comment (estebank) [reply src/librustc_privacy/lib.rs]: @petrochenkov do you want to implement that change in a separate PR?

Comment (petrochenkov) [reply src/librustc_privacy/lib.rs]: It's probably better to update this PR.
