### PR TITLE
Fix query cycle when encounter unevaluated const

### LINKED ISSUE #249: unevaluated consts in param_env query cycle
```rust
const CONST: &str = "hi";

trait ToUnit {
    type Assoc;
}
impl<T> ToUnit for T {
    type Assoc = ();
}

fn foo()
where
    <[u8; CONST.len()] as ToUnit>::Assoc: Sized,
{}
```
results in 
```
error[E0391]: cycle detected when evaluating type-level constant
  --> src/main.rs:12:11
   |
12 |     <[u8; CONST.len()] as ToUnit>::Assoc: Sized,
   |           ^^^^^^^^^^^
   |
note: ...which requires const-evaluating + checking `foo::{constant#0}`...
  --> src/main.rs:12:11
   |
12 |     <[u8; CONST.len()] as ToUnit>::Assoc: Sized,
   |           ^^^^^
note: ...which requires simplifying constant for the type system `CONST`...
  --> src/main.rs:1:1
   |
 1 | const CONST: &str = "hi";
   | ^^^^^^^^^^^^^^^^^
note: ...which requires const-evaluating + checking `CONST`...
  --> src/main.rs:1:1
   |
 1 | const CONST: &str = "hi";
   | ^^^^^^^^^^^^^^^^^
   = note: ...which requires computing layout of `&str`...
note: ...which requires computing whether `str` is `Sized`...
  --> src/main.rs:12:11
   |
12 |     <[u8; CONST.len()] as ToUnit>::Assoc: Sized,
   |           ^^^^^^^^^^^
   = note: ...which again requires evaluating type-level constant, completing the cycle
note: cycle used when checking that `foo` is well-formed
  --> src/main.rs:12:11
   |
12 |     <[u8; CONST.len()] as ToUnit>::Assoc: Sized,
   |           ^^^^^^^^^^^
   = note: see https://rustc-dev-guide.rust-lang.org/overview.html#queries and https://rustc-dev-guide.rust-lang.org/query.html for more information
```
with the new solver as we evaluate `CONST.len()` in the param_env of the impl, we then try to use the where-bound containing that const when checking whether `str: Sized` holds while computing the layout of the return type of `CONST`.

The reason this doesn't have a cycle error in the old solver is that we don't try to normalize where-bounds while trait solving.

### PR DESCRIPTION
**Pull request by tiif**
Fixes https://github.com/rust-lang/trait-system-refactor-initiative/issues/249

In this PR, the environment is dropped when evaluating const that does not have any generic parameter to fix the query cycle.

### CODE REVIEW

**Comment by tiif** [comment]
I didn't do this for the ``GCE`` and ``RepeatExprCount`` path above for now :thinking:  If that should be done, feel free to let me know, and it'd be nice to have test for those paths too.

File: compiler/rustc_trait_selection/src/traits/mod.rs [hunk 1]
```diff
@@ -635,9 +635,18 @@ pub fn try_evaluate_const<'tcx>(
...
-                    let typing_env = infcx
+                    let mut typing_env;
+
+                    typing_env = infcx
                         .typing_env(tcx.erase_and_anonymize_regions(param_env))
                         .with_post_analysis_normalized(tcx);
+
+                    // Since there is no generic parameter, we can just drop the environment
+                    // to prevent query cycle.
+                    if !uv.args.has_non_region_param() {
```
Comment (BoxyUwU) [inline compiler/rustc_trait_selection/src/traits/mod.rs]: I think you should be able to do this unconditionally because we early exit above if there are any generic parameters. can can you try always using the empty env. should also be able to get rid of the previous assignment to `typing_env` this way too

Comment (tiif) [reply compiler/rustc_trait_selection/src/traits/mod.rs]: If there is any region param / region infer in args, unconditionally doing this will empty everything in param_env though, is it ok?

Comment (tiif) [reply compiler/rustc_trait_selection/src/traits/mod.rs]: As discussed privately, it is ok because region will be erased later.

File: compiler/rustc_trait_selection/src/traits/mod.rs [hunk 2]
```diff
@@ -635,9 +635,10 @@ pub fn try_evaluate_const<'tcx>(
                         return Err(EvaluateConstErr::HasGenericsOrInfers);
                     }
 
-                    let typing_env = infcx
-                        .typing_env(tcx.erase_and_anonymize_regions(param_env))
-                        .with_post_analysis_normalized(tcx);
+                    // Since there is no generic parameter, we can just drop the environment
+                    // to prevent query cycle.
+                    let typing_env = infcx.typing_env(ty::ParamEnv::empty());
```
Comment (lcnr) [inline compiler/rustc_trait_selection/src/traits/mod.rs:640]: that typing env is wrong 🤔 surprised this doesn't blow up. We should use `ty::TypingEnv::post_analysis` here

I expect us to currently not normalize opaques or default assoc items because of that

Comment (BoxyUwU) [reply compiler/rustc_trait_selection/src/traits/mod.rs:640]: yh it seemed kinda funny to me too, I was surprised we don't have a test for this

Comment (tiif) [reply compiler/rustc_trait_selection/src/traits/mod.rs:640]: oops will fix this soon. do y'all have any test in mind that could surface this issue in future?

Comment (lcnr) [reply compiler/rustc_trait_selection/src/traits/mod.rs:640]: some use of a TAIT while evaluating the constant. I don't quite know what would cause it to fail :thinking:  I guess maybe calling a method on the opaque?

Comment (tiif) [reply compiler/rustc_trait_selection/src/traits/mod.rs:640]: Fixed in https://github.com/rust-lang/rust/pull/149183, didn't manage to craft a test that can make it fail :(
