### PR TITLE
rustdoc: Don't mark `#[target_feature]` functions as ⚠

### LINKED ISSUE #142952: rustdoc: safe functions with `#[target_feature]` are marked as unsafe (⚠) on index page
# Code

```rust
#[target_feature(enable = "popcnt")]
pub fn add_simd(x: i32, y: i32) -> i32 {
    x + y
}
```

# Reproduction Steps

`rustdoc +nightly ./mcve.rs`

# Expected Outcome

Function isn't marked as unsafe in index page:

Image

# Actual Output

Function is marked as ⚠ to indicate it's unsafe.

Image

But on the function's own page, it's correct.

Image

# Version

rustdoc 1.90.0-nightly (706f244db 2025-06-23)

# Additional Details

Probably the same root cause as  https://github.com/rust-lang/rust/issues/142655#issuecomment-2982338480

### PR DESCRIPTION
**Pull request by aDotInTheVoid**
Closes https://github.com/rust-lang/rust/issues/142952

### CODE REVIEW

File: tests/rustdoc/target-feature.rs [hunk 1]
```diff
@@ -0,0 +1,38 @@
...
+//@ has   - '//dl[@class="item-table"]/dt[1]//code' 'popcnt'
+//@ count - '//dl[@class="item-table"]/dt[1]//sup' 0
+//@ has   - '//dl[@class="item-table"]/dt[2]//a' 'f2_not_safe'
+//@ has   - '//dl[@class="item-table"]/dt[2]//code' 'avx2'
+//@ count - '//dl[@class="item-table"]/dt[2]//sup' 1
+//@ has   - '//dl[@class="item-table"]/dt[2]//sup' '⚠'
+
+#[target_feature(enable = "popcnt")]
+//@ has 'foo/fn.f1_safe.html'
+//@ matches - '//pre[@class="rust item-decl"]' '^pub fn f1_safe'
```
Comment (aDotInTheVoid) [inline tests/rustdoc/target-feature.rs:15]: This test needs to use `matches` instead of `has` to catch check if there was a attribute printed before the function, e.g. to test for https://github.com/rust-lang/rust/pull/142876#discussion_r2164686184

**Review by JonathanBrouwer — APPROVED** [review]

File: tests/rustdoc/target-feature.rs [hunk 2]
```diff
@@ -0,0 +1,38 @@
+#![crate_name = "foo"]
```
Comment (JonathanBrouwer) [inline tests/rustdoc/target-feature.rs:1]: Nit: I think this file could be test/rustdoc/attrs/target-feature.rs

**Review by GuillaumeGomez — APPROVED** [review]

**Comment by GuillaumeGomez** [comment]
Thanks!

@bors r+ rollup
