### PR TITLE
Fix ICE and report a human readable error

### LINKED ISSUE #55063: ICE when returning Vec from const fn
<short summary of the bug>
Returning `Vec` from a const fn causes internal compiler error, with the message 'bad input type for cast'.

I tried this code:

Minimal example
```rust
const fn foo() -> Vec<i32> {
    vec![1, 2, 3]
}
```

Original example
```rust
const fn foo(a: i32) -> Vec<i32> {
    vec![1, 2, 3]
}

const CT: Vec<i32> = foo(3);

fn main() {
    println!("Hello {}", CT[1])
}
```

I expected to see this happen: program compiles and prints 'Hello 1' or I get a compiler error.

Instead, this happened: ICE

## Meta

```
Compiling playground v0.0.1 (/playground)
thread 'main' panicked at 'bad input type for cast', libcore/option.rs:1008:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:211
   3: std::panicking::default_hook
             at libstd/panicking.rs:227
   4: rustc::util::common::panic_hook
   5: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:480
   6: std::panicking::continue_panic_fmt
             at libstd/panicking.rs:390
   7: rust_begin_unwind
             at libstd/panicking.rs:325
   8: core::panicking::panic_fmt
             at libcore/panicking.rs:77
   9: core::option::expect_failed
             at libcore/option.rs:1008
  10: rustc_mir::transform::qualify_min_const_fn::is_min_const_fn
  11: <rustc_mir::transform::qualify_consts::QualifyAndPromoteConstants as rustc_mir::transform::MirPass>::run_pass
  12: rustc_mir::transform::mir_validated::{{closure}}
  13: rustc_mir::transform::mir_validated
  14: rustc::ty::query::__query_compute::mir_validated
  15: rustc::ty::query::<impl rustc::ty::query::config::QueryAccessors<'tcx> for rustc::ty::query::queries::mir_validated<'tcx>>::compute
  16: rustc::dep_graph::graph::DepGraph::with_task_impl
  17: rustc::ty::context::tls::with_related_context
  18: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt<'a, 'gcx, 'tcx>>::force_query_with_job
  19: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt<'a, 'gcx, 'tcx>>::get_query
  20: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt<'a, 'gcx, 'tcx>>::ensure_query
  21: rustc_borrowck::borrowck::borrowck
  22: rustc::ty::query::<impl rustc::ty::query::config::QueryAccessors<'tcx> for rustc::ty::query::queries::borrowck<'tcx>>::compute
  23: rustc::dep_graph::graph::DepGraph::with_task_impl
  24: rustc::ty::context::tls::with_related_context
  25: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt<'a, 'gcx, 'tcx>>::force_query_with_job
  26: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt<'a, 'gcx, 'tcx>>::get_query
  27: rustc::ty::<impl rustc::ty::context::TyCtxt<'a, 'gcx, 'tcx>>::par_body_owners
  28: rustc_borrowck::borrowck::check_crate
  29: rustc::util::common::time
  30: rustc::ty::context::tls::enter_context
  31: <std::thread::local::LocalKey<T>>::with
  32: rustc::ty::context::TyCtxt::create_and_enter
  33: rustc_driver::driver::compile_input
  34: rustc_driver::run_compiler_with_pool
  35: rustc_driver::driver::spawn_thread_pool
  36: rustc_driver::run_compiler
  37: <scoped_tls::ScopedKey<T>>::set
  38: syntax::with_globals
  39: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:102
  40: rustc_driver::run
  41: rustc_driver::main
  42: std::rt::lang_start::{{closure}}
  43: std::panicking::try::do_call
             at libstd/rt.rs:59
             at libstd/panicking.rs:310
  44: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:102
  45: std::rt::lang_start_internal
             at libstd/panicking.rs:289
             at libstd/panic.rs:392
             at libstd/rt.rs:58
  46: main
  47: __libc_start_main
  48: <unknown>
query stack during panic:
#0 [mir_validated] processing `foo`
#1 [borrowck] processing `foo`
end of query stack

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.31.0-nightly (4699283c5 2018-10-13) running on x86_64-unknown-linux-gnu

note: compiler flags: -C codegen-units=1 -C debuginfo=2 --crate-type lib

note: some of the compiler flags provided by cargo are hidden

error: Could not compile `playground`.
```

### PR DESCRIPTION
**Pull request by oli-obk**
fixes #55063

r? @RalfJung

### CODE REVIEW

File: src/librustc_mir/transform/qualify_min_const_fn.rs [hunk 1]
```diff
@@ -163,6 +163,10 @@ fn check_rvalue(
                 _ => check_operand(tcx, mir, operand, span),
             }
         }
+        Rvalue::Cast(_, _, _) => Err((
+            span,
+            "only int casts are allowed in const fn".into(),
```
Comment (RalfJung) [inline src/librustc_mir/transform/qualify_min_const_fn.rs]: "int casts" doesn't seem like the right description here, not all `Misc` casts involved integers -- do they?

There are not so many kinds of casts, so depending on that you could make it say "unsizing casts" or "function pointer casts".

Comment (estebank) [reply src/librustc_mir/transform/qualify_min_const_fn.rs]: Also, can you add a test case for this code branch?

Comment (oli-obk) [reply src/librustc_mir/transform/qualify_min_const_fn.rs]: I'm not sure if I can, but I'll try

Comment (estebank) [reply src/librustc_mir/transform/qualify_min_const_fn.rs]: Don't let it be a blocker, but it'd be nice to have error cases so that later we can give them all their own error code and a good extended description.

Comment (oli-obk) [reply src/librustc_mir/transform/qualify_min_const_fn.rs]: I managed to get to the unsizing errors. Everything else errors out early due to fn pointers not being allowed

**Comment by estebank** [comment]
lgtm++

File: src/librustc_mir/transform/qualify_min_const_fn.rs [hunk 2]
```diff
@@ -163,6 +163,19 @@ fn check_rvalue(
...
             }
         }
+        Rvalue::Cast(CastKind::UnsafeFnPointer, _, _) |
+        Rvalue::Cast(CastKind::ReifyFnPointer, _, _) => Err((
+            span,
+            "function pointer casts are not allowed in const fn".into(),
+        )),
+        Rvalue::Cast(CastKind::ClosureFnPointer, _, _) => Err((
+            span,
+            "closures are not allowed in const fn".into(),
```
Comment (RalfJung) [inline src/librustc_mir/transform/qualify_min_const_fn.rs]: This is not just having a closure, but then casting it to `fn()` (I think). The message should contain the word "cast" one way or another.

I would have just grouped it with the other two fn ptr casts.

**Comment by RalfJung** [comment]
r=me with that nit fixed.
