### PR TITLE
Don't use projection cache or candidate cache in intercrate mode

### LINKED ISSUE #88969: regression: Copy no longer implemented
Found by 1.56 crater - https://crater-reports.s3.amazonaws.com/beta-1.56-2/beta-2021-09-12/reg/gmorph-0.1.0/log.txt

```
[INFO] [stdout] error[E0204]: the trait `Copy` may not be implemented for this type
[INFO] [stdout]   --> src/enc.rs:16:17
[INFO] [stdout]    |
[INFO] [stdout] 16 | #[derive(Debug, Copy, Clone, PartialEq, Serialize, Deserialize)]
[INFO] [stdout]    |                 ^^^^
[INFO] [stdout] 17 | pub struct Enc {
[INFO] [stdout] 18 |     inner: Matrix3<Q231>,
[INFO] [stdout]    |     -------------------- this field does not implement `Copy`
[INFO] [stdout]    |
[INFO] [stdout]    = note: this error originates in the derive macro `Copy` (in Nightly builds, run with -Z macro-backtrace for more info)
[INFO] [stdout] 
```

Bisections seems to point at https://github.com/rust-lang/rust/commit/371f3cd3fe523d0b398ed1db1620667c53ba7d02, cc @Aaron1011

### PR DESCRIPTION
**Pull request by Aaron1011**
Fixes #88969

It appears that *just* disabling the evaluation cache (in #88994)
leads to other issues involving intercrate mode caching. I suspect
that since we now always end up performing the full evaluation
in intercrate mode, we end up 'polluting' the candidate and projection
caches with results that depend on being in intercrate mode in some way.
Previously, we might have hit a cached evaluation (stored during
non-intercrate mode), and skipped doing this extra work in
intercrate mode.

The whole situation with intercrate mode caching is turning into
a mess. Ideally, we would remove intercrate mode entirely - however,
this might require waiting on Chalk.

### CODE REVIEW

**Comment by Aaron1011** [comment]
cc @rust-lang/wg-traits

**Comment by jackh726** [comment]
If this is only disabling caches, the r=me with appropriate comments added

**Comment by Aaron1011** [comment]
This is a correctness fix, so we'll need to take the performance hit (at least until we can come up with a better solution).

@bors r=jackh726

File: compiler/rustc_trait_selection/src/traits/project.rs [hunk 1]
```diff
@@ -844,6 +844,10 @@ fn opt_normalize_projection_type<'a, 'b, 'tcx>(
     obligations: &mut Vec<PredicateObligation<'tcx>>,
 ) -> Result<Option<Ty<'tcx>>, InProgress> {
     let infcx = selcx.infcx();
+    // Don't use the projection cache in intercrate mode -
+    // the `infcx` may be re-used between intercrate in non-intercrate
+    // mode, which could lead to using incorrect cache results.
+    let use_cache = !selcx.is_intercrate();
```
Comment (nikomatsakis) [inline compiler/rustc_trait_selection/src/traits/project.rs:850]: Probably the *right* answer is that the cache key incorporates the environment, and intercrate mode is part of the environment (this is how chalk approaches it).

**Review by nikomatsakis — COMMENTED** [review]
(Also, do we have a test case?)

**Comment by apiraino** [comment]
@Aaron1011 should this be nominated for beta-backport?

**Comment by apiraino** [comment]
Beta backport accepted as per compiler team [on Zulip](https://rust-lang.zulipchat.com/#narrow/stream/238009-t-compiler.2Fmeetings/topic/.5Bweekly.5D.202021-09-30.20.2354818/near/255580891)

@rustbot label +beta-accepted
