### PR TITLE
resolve: Avoid a regression from splitting prelude into two scopes

### LINKED ISSUE #145575: Glob import causes ambiguity on nightly
On nightly, using `std` is now rejected due to ambiguity when there is a glob import from a module that exports `std` 

This affects the following crates:
https://github.com/CasualX/pelite/issues/287

~~May be related to #145524~~

### Code

I tried this code:

```rust
extern crate no_std_compat as std;

mod inner {
    use crate::*;
    use std::str;
}

fn main() {
    println!("Hello, world!");
}
```

I expected to see this happen: Code is accepted on stable and nightly.

Instead, this happened: Code was accepted on stable, but rejected on nightly (starting from `nightly-2025-08-15`).

```
error[E0659]: `std` is ambiguous
 --> src\main.rs:5:9
  |
5 |     use std::str;
  |         ^^^ ambiguous name
  |
  = note: ambiguous because of a conflict between a name from a glob import and an outer scope during import or macro resolution
  = note: `std` could refer to a built-in crate
  = help: use `::std` to refer to this crate unambiguously
note: `std` could also refer to the crate imported here
 --> src\main.rs:4:9
  |
4 |     use crate::*;
  |         ^^^^^^^^
  = help: consider adding an explicit import of `std` to disambiguate
  = help: or use `self::std` to refer to this crate unambiguously
```

### Version it worked on

It most recently worked on: `nightly-2025-08-14`

### Version with regression

`rustc --version --verbose`:
```
$ rustc +nightly-2025-08-15 -vV    
rustc 1.91.0-nightly (898aff704 2025-08-14)
binary: rustc
commit-hash: 898aff704d6f0d00343f21d31b8b9bfac8e43007
commit-date: 2025-08-14
host: x86_64-pc-windows-msvc
release: 1.91.0-nightly
LLVM version: 21.1.0
```

@rustbot modify labels: +regression-from-stable-to-nightly

</p>
</details>

### PR DESCRIPTION
**Pull request by petrochenkov**
Fixes https://github.com/rust-lang/rust/issues/145575.

### CODE REVIEW

File: compiler/rustc_resolve/src/ident.rs [hunk 1]
```diff
@@ -422,6 +422,8 @@ impl<'ra, 'tcx> Resolver<'ra, 'tcx> {
         // to detect potential ambiguities.
         let mut innermost_result: Option<(NameBinding<'_>, Flags)> = None;
         let mut determinacy = Determinacy::Determined;
+        let mut extprel_item_binding = None;
+        let mut extprel_flag_binding = None;
```
Comment (nnethercote) [inline compiler/rustc_resolve/src/ident.rs]: What does "extprel_" mean? It's not obvious.

**Comment by nnethercote** [comment]
r=me with a better name for the `extprel_` variables, or a comment explaining what they mean.

File: compiler/rustc_resolve/src/ident.rs (hunk 1 above)
Comment (jieyouxu) [reply compiler/rustc_resolve/src/ident.rs]: "extern prelude"? but yeah, maybe `ext_prelude` or just in full

**Comment by petrochenkov** [comment]
Updated with the variables renamed to avoid the abbreviations.
@bors r=nnethercote

**Comment by jieyouxu** [comment]
I'm not convinced the failure is due to this PR 🤔 

<details>
<summary>PPC64</summary>

```
   Compiling rustc_driver v0.0.0 (/checkout/compiler/
error: linking with `powerpc64-unknown-linux-gnu-gcc` 
  |
  = note:  "powerpc64-unknown-linux-gnu-gcc" "-Wl,--version-script=/tmp/rustcQGEg2L/list" "-Wl,--no-undefined-version" "-m64" "/tmp/rustcQGEg2L/symbols.o" "<1 object files omitted>" "/tmp/rustcQGEg2L/rmeta.o" "<1 object files omitted>" "-Wl,--as-needed" "-Wl,-Bstatic" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2-rustc/powerpc64-unknown-linux-gnu/release/deps/{librustc_driver_impl-83f593c2b695f964,libctrlc-840b7fda5d37de23,libnix-eaf0476a0e2c6b67,librustc_log-1bc1a4f917de2b74,libtracing_tree-ed1ff03afe3f7677,libtracing_log-5497030f4092971b,libnu_ansi_term-41315a42e5b4d1aa,libtracing_subscriber-656d1b8ef015d203,libnu_ansi_term-35a084056411a511,liboverload-963de30b416ec1f3,libsharded_slab-0c87193002118d16,liblazy_static-c2840cc93c6473a2,libmatchers-8c346fcc54b7a0bb,libregex_automata-9a947b793563982a,libregex_syntax-7a9e24463f2a8f9f,libthread_local-3d514404cd0e148c,libjiff-439f36af638d0669,librustc_public-7559d52dd63b25bf,librustc_public_bridge-d37dd04dcbb0493e,librustc_interface-c72b7512dce13cf8,librustc_codegen_llvm-ae53cf56e0d2fa48,librustc_llvm-c50729062a1162b3,librustc_sanitizers-a092c2b11fd23c1c,librustc_hir_typeck-1d48f4a7684709e6,librustc_hir_analysis-abe917882e4b181a,librustc_monomorphize-9b8018977e38d9eb,librustc_mir_transform-d4393310184d296a,librustc_mir_build-4798dbcfeb850af1,librustc_pattern_analysis-3c370b28df0aa063,librustc_borrowck-609f7413588fe1c7,librustc_traits-c03e3d9ea7d245e9,librustc_const_eval-f3d2e00ad892d521,librustc_mir_dataflow-897de9d57c1411f8,librustc_builtin_macros-015e356a51831979,librustc_resolve-789eed3a9e561ace,libpulldown_cmark-189610a92b441a9d,libunicase-9a3f6a7a2f64411f,libpulldown_cmark_escape-d2062d23f1042fd4,librustc_passes-7848fc5a112f1ee6,librustc_ast_lowering-46b1efdde1f8589f,librustc_privacy-e6ffb3fc48d906d8,librustc_ty_utils-0339b5ca1d0d4a6c,librustc_lint-89c987b9f4cb57f2,libunicode_security-b6d61efa992f67bd,libunicode_script-f0233b806e5b6c15,librustc_query_impl-b08689310a80cd89,librustc_codegen_ssa-5c677a1969a517e5,libwasm_encoder-260ddd30b8c6915b,libleb128-5f64861c6419b075,libthorin-6bef83f614144eee,libgimli-9ee5031661f77876,libfallible_iterator-93714debe61d3ba2,libbstr-c1398fc68d4d99f7,librustc_trait_selection-7c66a61d8815ea09,librustc_next_trait_solver-27ecd92806d5ef6c,librustc_parse_format-11b625c939ebcd7b,librustc_transmute-43bc8ec28654f2c4,librustc_infer-f900d06a68ed7e36,librustc_symbol_mangling-3dda5c5e00d9b7ab,librustc_demangle-ba49eb7e2d07a91d,libpunycode-ab527ca8af2bac0b,libpathdiff-028598837e9837a8,libregex-d3b46172e709cba1,libcc-9d5ddb935488259b,libshlex-92ae92e59aad5af9,libar_archive_writer-c7f9bf00393ad945,libobject-4555ca5ca77c7104,libruzstd-3df00a9cc1a600be,libtwox_hash-cc1e2edc4e8aa46b,librand-57c8b4bf5b67ddc8,librand_chacha-220b00626e302fc6,librand_core-8050972ee7cc6154,libgetrandom-4f960aca6437881c,libstatic_assertions-38363cb65946c6c7,libflate2-76ae9988431925e0,libminiz_oxide-e700761d08984c0b,libadler2-1100d8e2e461048f,librustc_metadata-041ab808b7c6473d,liblibloading-cd5ba07cb23ca271,librustc_incremental-3584743333d75599,librustc_expand-8fd97a4142dad6d4,librustc_ast_passes-b3cddb506653aba4,librustc_proc_macro-ea51952f2df2f74e,librustc_attr_parsing-e7addd75c27938f9,librustc_parse-6aa1fd6de1543f2c,libunicode_normalization-a00c3e19aa1e7fd3,libtinyvec-864492acbaae54f7,libtinyvec_macros-6af1c8acdf21c9af,librustc_middle-295aee3cc0385661,librustc_apfloat-361addea7ebb1d42,libgsgdt-abda59a4e92052ed,libpolonius_engine-df475828c860f45b,libdatafrog-39aa0ea3e418e874,librustc_query_system-e8a56ff45ca7f4ed,librustc_type_ir-14a6a025c986610a,librustc_session-7f0e3f5ada505508,libgetopts-fea9856e38e88554,librustc_feature-c3ca31965f990d74,librustc_hir_pretty-15d5f9ce48886aa0,librustc_errors-da160d5971a3e6dc,libtermize-91a25f1f487a682c,librustc_error_codes-fddfc3d4358eaa92,libannotate_snippets-013cd92c94d30f6f,libanstyle-581a36e5a21262cf,libtermcolor-cae7679e3136ac14,librustc_lint_defs-46dee9712db04bd2,librustc_hir-da942830f6bb2138,libodht-4cd2388b0305caf1,librustc_hir_id-c47c3d450d69e55f,librustc_target-f31aca37dd4fe2bd,libserde_path_to_error-cbeec585049a62c7,libobject-8cbc191bc8da8956,libcrc32fast-41965501bc4e8079,libwasmparser-d9eee9272d12c054,librustc_fs_util-16735922c06ab7c9,libserde_json-a3771a38b9a71035,libryu-ab3dce72dbb77067,libserde-295151132734d0b0,librustc_abi-9a19ab82097f2c15,librand_xoshiro-6c0a94ebcf8f47ca,librustc_error_messages-64c5d52cf96c2160,librustc_baked_icu_data-fb1dffa21fa6b247,libicu_list-3732170e8716eab3,libregex_automata-c06c27f7a7014c4e,libaho_corasick-c1b33b63a7982865,libregex_syntax-a27e083ed6d95b87,libicu_locale-497433ec58b5cfed,libicu_locale_data-9017d519197fc90a,libicu_collections-5c001009c91dfe3d,libpotential_utf-df865401a0a135be,libicu_provider-c6d383fb6ba93293,libzerotrie-6e20419557200c5b,libicu_locale_core-cf1b144bafafe032,libwriteable-3a813812134e8bc8,liblitemap-717e04e0dd1f9030,librustc_ast_pretty-5b87825d24621ccd,librustc_lexer-39a877cf54a2fb53,libunicode_xid-8ca726f63a8c6380,libunicode_properties-36ac71a39b54c2db,libitertools-e90420a979fc1685,libfluent_bundle-f08681e03f7461c4,libfluent_langneg-26bace3603c5aa38,libintl_pluralrules-61daea538a36ab40,libself_cell-9f59ac94dfcb3334,libintl_memoizer-7220fb2cea47ec60,libtype_map-7eb3360c6199b484,libunic_langid-cab0e114ffebe5ea,libunic_langid_macros-934b203e9e80cba0,libunic_langid_impl-7e7c6c6640948686,libtinystr-efc4fb4b63a2c82d,libzerovec-4370abf910781544,libyoke-d7e1d68a0d13caf2,libzerofrom-5d774ee0ca51164b,libfluent_syntax-081ad2b3ce799e1f,libthiserror-ab5baf949e421bbe,librand-4f9ced6d62978524,librand_chacha-9df0ebd4efd6cce7,libppv_lite86-f9b273fc4b827c45,libzerocopy-8975f25aac87e97c,librand_core-7499049b07e68ef5,librustc_ast-715b00d9baabd9c3,libmemchr-662d60455531103e,librustc_ast_ir-45a8825f93b1fe92,librustc_literal_escaper-eee7d18be8c6340f,librustc_span-fa9a980ca4cc0e00,libunicode_width-a8760a591627b8cc,libblake3-9838f0927b33ca31,libconstant_time_eq-8b07c77bf77e7525,libarrayref-bf3b474ce3a9739a,libitoa-d0eb80bbe7bb59bf,libscoped_tls-fa782ac99578523e,libsha2-28e943d6082fa171,libsha1-6bfef0a78f831542,libmd5-957876a5036c6155,libdigest-53fe04aa42e7c674,libblock_buffer-d6d11562aa1c76fc,libcrypto_common-44d980d57ff8c575,libgeneric_array-c9b2f1335a37b5f8,libtypenum-49f559468f97f244,librustc_data_structures-8c27291e6871b48f,libelsa-b1fb2b64bd91b35b,libstable_deref_trait-57ede062c16f3d93,librustc_thread_pool-6efb2a21aa590de2,libcrossbeam_deque-964ae026216013b3,libcrossbeam_epoch-53be87125eb9c5a9,libcrossbeam_utils-0dc69cf704ca183f,libstacker-7a1b21bd1c943a83,libpsm-d632fc5c75203c7d,libmemmap2-6e70d229ec0818b9,librustc_arena-51e49574e19014ce,libtempfile-7a012216ad7f35b8,libgetrandom-1f42b3a9dc9ee60f,libfastrand-f2ece741eee3dfde,librustix-a3c7817ed5580fb9,liblinux_raw_sys-e9e5cb5081cc38a7,libbitflags-7cbf63bc902ada55,liberrno-01e2c489a233edc8,libarrayvec-50869652dd30c9ba,libeither-64ffc78542e17885,libmeasureme-6eaf9d59d314a3c8,librustc_hash-c1ec50f3fbfb5ce9,librustc_graphviz-1eeb74e8d9518df6,libparking_lot-26c5680804eec4d8,libparking_lot_core-98db99ce730a78f9,liblock_api-f5970ca062c610be,libscopeguard-f7466ebb9b3d3126,libjobserver-49541e47d3cec2c7,liblibc-5e84419902dcf6af,libtracing-9256c4a56d63b7b6,libcfg_if-98cb65f135f2f9d9,libpin_project_lite-12262d2ccf77f5d9,libtracing_core-e0b0d74a035e3f93,libonce_cell-71d953a2757af972,librustc_hash-edd61cd76541e0cc,librustc_index-d296ca3e6bc78650,librustc_serialize-12766c75d95a4c78,libindexmap-ca5ba6e8cbea3a0b,libhashbrown-d5dc1ba774f667dc,libfoldhash-ace7cf48b9303bf5,libequivalent-f53e7b7949df86bd,libthin_vec-201d6c78ba262059,librustc_hashes-2cf018e28574ae70,librustc_stable_hash-ce971fe4145eea78,libsmallvec-32d6c730ad9c00b4,libena-add11e8870a3e829,liblog-a5e55efc7e305a58}.rlib" "<sysroot>/lib/rustlib/powerpc64-unknown-linux-gnu/lib/{libstd-*,libpanic_unwind-*,libobject-*,libmemchr-*,libaddr2line-*,libgimli-*,libcfg_if-*,librustc_demangle-*,libstd_detect-*,libhashbrown-*,librustc_std_workspace_alloc-*,libminiz_oxide-*,libadler2-*,libunwind-*,liblibc-*,librustc_std_workspace_core-*,liballoc-*,libcore-*,libcompiler_builtins-*}.rlib" "-Wl,-Bdynamic" "-ldl" "-lgcc_s" "-lutil" "-lrt" "-lpthread" "-lm" "-ldl" "-lc" "-L" "/tmp/rustcQGEg2L/raw-dylibs" "-Wl,--eh-frame-hdr" "-Wl,-z,noexecstack" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2-rustc/powerpc64-unknown-linux-gnu/release/build/psm-5a0f2d86c5f5125a/out" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2-rustc/powerpc64-unknown-linux-gnu/release/build/rustc_llvm-4fc85c55338268f3/out" "-L" "/checkout/obj/build/powerpc64-unknown-linux-gnu/llvm/lib" "-L" "/x-tools/powerpc64-unknown-linux-gnu/lib/gcc/powerpc64-unknown-linux-gnu/8.5.0/../../../../powerpc64-unknown-linux-gnu/lib/../lib64" "-L" "<sysroot>/lib/rustlib/powerpc64-unknown-linux-gnu/lib" "-o" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2-rustc/powerpc64-unknown-linux-gnu/release/deps/librustc_driver-8db663b40032437e.so" "-shared" "-Wl,-soname=librustc_driver-8db663b40032437e.so" "-Wl,-z,relro,-z,now" "-Wl,-O1" "-nodefaultlibs" "-Wl,-z,origin" "-Wl,-rpath,$ORIGIN/../lib"
2025-08-29T20:51:14.4661970Z   = note: some arguments are omitted. use `--verbose` to show all linker arguments
2025-08-29T20:51:14.4663386Z   = note: /x-tools/powerpc64-unknown-linux-gnu/lib/gcc/powerpc64-unknown-linux-gnu/8.5.0/../../../../powerpc64-unknown-linux-gnu/bin/ld: BFD (crosstool-NG UNKNOWN) 2.32 assertion fail /tmp/build/.build/powerpc64-unknown-linux-gnu/src/binutils/bfd/elf64-ppc.c:10251
2025-08-29T20:51:14.4665271Z           /x-tools/powerpc64-unknown-linux-gnu/lib/gcc/powerpc64-unknown-linux-gnu/8.5.0/../../../../powerpc64-unknown-linux-gnu/bin/ld: BFD (crosstool-NG UNKNOWN) 2.32 assertion fail /tmp/build/.build/powerpc64-unknown-linux-gnu/src/binutils/bfd/elf64-ppc.c:10251
2025-08-29T20:51:14.4667056Z           /x-tools/powerpc64-unknown-linux-gnu/lib/gcc/powerpc64-unknown-linux-gnu/8.5.0/../../../../powerpc64-unknown-linux-gnu/bin/ld: BFD (crosstool-NG UNKNOWN) 2.32 assertion fail /tmp/build/.build/powerpc64-unknown-linux-gnu/src/binutils/bfd/elf64-ppc.c:10251
          collect2: error: ld returned 1 exit status
          

[RUSTC-TIMING] rustc_driver test:false 20.430
```
</details>

@bors try jobs=dist-powerpc64-linux
