### PR TITLE
resolve: improve diagnostics and lay groundwork for resolving before ast->hir

### LINKED ISSUE #33186: resolve: nonsensical diagnostics for an expression that resolves to a module
This code:
```rust
mod foo {}

fn main() {
    let v = Vec::new();
    v.push(foo);
}
```
produces these diagnostics:
```
<anon>:5:12: 5:15 error: unresolved name `foo` [E0425]
<anon>:5     v.push(foo);
                    ^~~
<anon>:5:12: 5:15 help: see the detailed explanation for E0425
<anon>:5:12: 5:15 help: To call a function from the `foo` module, use `foo::push(..)`
```
The suggestion doesn't make sense -- we should instead emit something like "modules are not valid expressions".

### PR DESCRIPTION
**Pull request by jseyfried**
This PR improves diagnostics in `resolve` and lays some groundwork for resolving before ast->hir.

More specifically,
- It removes an API in `resolve` intended for external refactoring tools (see #27493) that appears not to be in active use. The API is incompatible with resolving before ast->hir, but could be rewritten in a more compatible and less intrusive way.
- It improves the diagnostics for pattern bindings that conflict with `const`s.
- It improves the diagnostics for modules used as expressions (fixes #33186).
- It refactors away some uses of the hir map, which is unavavailable before ast->hir lowering.

r? @eddyb

### CODE REVIEW

File: src/test/compile-fail/const-pattern-irrefutable.rs [hunk 1]
```diff
@@ -9,8 +9,8 @@
 // except according to those terms.
 
 mod foo {
-    pub const b: u8 = 2; //~ NOTE constant defined here
-    pub const d: u8 = 2; //~ NOTE constant defined here
```
Comment (jseyfried) [inline src/test/compile-fail/const-pattern-irrefutable.rs]: We used to emit two notes for an conflicting imported constant -- one where the conflict was imported and another where the conflict was defined. For all other conflict errors, we only emit where the conflicting imported item was imported.

Comment (jseyfried) [inline src/test/compile-fail/const-pattern-irrefutable.rs]: I can re-implement the original behavior if desired, but I think it's better to be consistent and only emit one note.

**Comment by jseyfried** [comment]
@GSam If you're still interested in continuing to develop the refactoring tool, feel free to ping me and we can design a different API.

**Comment by jseyfried** [comment]
cc @nrc

**Comment by nrc** [comment]
cc @aochagavia  who's working on refactoring things now.

**Comment by aochagavia** [comment]
I am not using the resolve functionality at the moment and am not sure if it will be necessary in the future, so I am ok with this.

**Comment by alexcrichton** [comment]
@bors: retry

* https://github.com/rust-lang/rust/pull/33332
