### PR TITLE
fix panic-safety in specialized Zip::next_back

### LINKED ISSUE #86443: Panic safety issue in `Zip::next_back()` TrustedRandomAccess specialization
https://github.com/rust-lang/rust/blob/312b894cc12240a3fcc645474c3daa14f7d568ea/library/core/src/iter/adapters/zip.rs#L296-L301

https://github.com/rust-lang/rust/blob/312b894cc12240a3fcc645474c3daa14f7d568ea/library/core/src/iter/adapters/zip.rs#L235-L244

Yet another soundness bug in Zip's TRA specialization. Line 300 is not called when line 298 panics. This leaves `self.a_len` outdated, which results in calling `__iterator_get_unchecked()` with an invalid index in line 242.

Here is a [playground link](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=52b3da1b55be68e043676780a00df1e4) that demonstrates creating two mutable references to the same memory location without unsafe code.

### PR DESCRIPTION
**Pull request by the8472**
This was unsound since a panic in a.next_back() would result in the
length not being updated which would then lead to the same element
being revisited in the side-effect preserving code.

fixes #86443

### CODE REVIEW

**Comment by m-ou-se** [comment]
Thank you!

@bors r+

**Comment by the8472** [comment]
I can reproduce the wasm error locally, but the test passes on stage 1, x86_64-unknown-linux-gnu, `debug-assertions-std = true`.
Could this be a miscompilation?

**Comment by the8472** [comment]
I have been informed that this is due to wasm not supporting unwinding. Added `cfg(panic = "unwind")` to the test to exclude all such platforms.

File: library/core/src/iter/adapters/zip.rs [hunk 1]
```diff
@@ -295,9 +295,10 @@ where
                 let sz_a = self.a.size();
                 if A::MAY_HAVE_SIDE_EFFECT && sz_a > self.len {
                     for _ in 0..sz_a - self.len {
+                        self.a_len -= 1;
```
Comment (RalfJung) [inline library/core/src/iter/adapters/zip.rs:298]: Might be a good idea to have a comment explaining why we do this in steps of 1.

Comment (the8472) [reply library/core/src/iter/adapters/zip.rs:298]: This kind of pattern occurs in many places, e.g. the family of methods that fill/append to vecs from iterators and updates lengths. It's a common pitfall to just update the length after iteration is done, it seems more efficient after all when you don't think about the panics and that you're running user-supplied code.

So I'm not sure if adding a comment to this one place among many will really improve anything. But if you still think it's valuable I can do it anyway.

Comment (RalfJung) [reply library/core/src/iter/adapters/zip.rs:298]: How many is many?

> It's a common pitfall to just update the length after iteration is done

Exactly. That's why I think a comment is in order. Don't assume the next person reading this code knows as much as you do, or has read all the other files in this folder.

Comment (the8472) [reply library/core/src/iter/adapters/zip.rs:298]: There's about 4 of those in vec, in various flavors. Some use drop guards and bump pointers instead of setting length directly. Of the reading type there's 1-4 cases in `Zip`, depending on whether one wants to count only loops or single step ones. One of the single-step ones has been wrong before (#81740). Another one in `core::array`, but that one already has plenty of comments. Possibly with more to come in the future as more const-generic methods are added to fill arrays. Haven't checked other types.

Comment (RalfJung) [reply library/core/src/iter/adapters/zip.rs:298]: Still seems like an amount where adding (brief) comments individually doesn't seem overwhelming.

Comment (the8472) [reply library/core/src/iter/adapters/zip.rs:298]: Ok, will do.

Comment (RalfJung) [reply library/core/src/iter/adapters/zip.rs:298]: Thanks. :)
