### PR TITLE
Better diagnostics for `env!` where variable contains escape

### LINKED ISSUE #110559: diagnostics look weird when rustc is trying to quote whitespace characters
### Code

```Rust
env!{"\t"}
```

### Current output

```Shell
error: environment variable `    ` not defined at compile time
 --> env.rs:1:1
  |
1 | env!{"\t"}
  | ^^^^^^^^^^
  |
  = help: use `std::env::var("	")` to read the variable at run time
  = note: this error originates in the macro `env` (in Nightly builds, run with -Z macro-backtrace for more info)
```

### Desired output

```Shell
This error: environment variable `    ` not defined at compile time

looks very weird imo because it looks like its something misssing there. I think actually rustc is quoting the `\t` here but while it is escaped in the code, it is not escaped in the error message.
Might be nice to print something like
..`    `(`\t`) not defined.. ?
```

### Rationale and extra context

_No response_

### Other cases

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by clubby789**
Fixes #110559

### CODE REVIEW

File: compiler/rustc_builtin_macros/src/env.rs [hunk 1]
```diff
@@ -63,10 +63,19 @@ pub fn expand_env<'cx>(
...
     };
 
+    let ast::ExprKind::Lit(ast::token::Lit { kind: ast::token::LitKind::Str, symbol: original_var, ..}) = &var_expr.kind else {
+        unreachable!("`expr_to_string` ensures this is a string lit")
+    };
+    if original_var.as_str().contains('\\') {
+        // If the variable name contains escape sequences, we should report it to the user
+        // as written in the code to avoid confusing diagnostics
+        var = *original_var;
+    }
```
Comment (cjgillot) [inline compiler/rustc_builtin_macros/src/env.rs:78]: Why don't we always prefer reporting using original_var?

Comment (clubby789) [reply compiler/rustc_builtin_macros/src/env.rs:78]: Hmm, that sounds more sensible
