### PR TITLE
fix building libstd without backtrace feature

### LINKED ISSUE #64410: libstd build without backtrace feature broken
Likely because of https://github.com/rust-lang/rust/pull/64154.

```
error[E0432]: unresolved import `crate::sys_common::backtrace`
  --> sysroot_src/src/libstd/backtrace.rs:98:24
   |
98 | use crate::sys_common::backtrace::{output_filename, lock};
   |                        ^^^^^^^^^ could not find `backtrace` in `sys_common`

error[E0432]: unresolved import `backtrace`
   --> sysroot_src/src/libstd/backtrace.rs:100:5
    |
100 | use backtrace::BytesOrWideString;
    |     ^^^^^^^^^ help: a similar path exists: `crate::backtrace`
    |
    = note: `use` statements changed in Rust 2018; read more at <https://doc.rust-lang.org/edition-guide/rust-2018/module-system/path-clarity.html>

error[E0433]: failed to resolve: use of undeclared type or module `backtrace`
   --> sysroot_src/src/libstd/backtrace.rs:146:12
    |
146 |     frame: backtrace::Frame,
    |            ^^^^^^^^^ use of undeclared type or module `backtrace`

error[E0433]: failed to resolve: use of undeclared type or module `backtrace`
   --> sysroot_src/src/libstd/backtrace.rs:231:13
    |
231 |             backtrace::trace_unsynchronized(|frame| {
    |             ^^^^^^^^^ use of undeclared type or module `backtrace`

error[E0433]: failed to resolve: use of undeclared type or module `backtrace`
   --> sysroot_src/src/libstd/backtrace.rs:285:35
    |
285 |             (&capture.frames[..], backtrace::PrintFmt::Full)
    |                                   ^^^^^^^^^ use of undeclared type or module `backtrace`

error[E0433]: failed to resolve: use of undeclared type or module `backtrace`
   --> sysroot_src/src/libstd/backtrace.rs:287:55
    |
287 |             (&capture.frames[capture.actual_start..], backtrace::PrintFmt::Short)
    |                                                       ^^^^^^^^^ use of undeclared type or module `backtrace`

error[E0433]: failed to resolve: use of undeclared type or module `backtrace`
   --> sysroot_src/src/libstd/backtrace.rs:299:21
    |
299 |         let mut f = backtrace::BacktraceFmt::new(fmt, style, &mut print_path);
    |                     ^^^^^^^^^ use of undeclared type or module `backtrace`

error[E0433]: failed to resolve: use of undeclared type or module `backtrace`
   --> sysroot_src/src/libstd/backtrace.rs:309:54
    |
309 |                         symbol.name.as_ref().map(|b| backtrace::SymbolName::new(b)),
    |                                                      ^^^^^^^^^ use of undeclared type or module `backtrace`

error[E0433]: failed to resolve: use of undeclared type or module `backtrace`
   --> sysroot_src/src/libstd/backtrace.rs:339:17
    |
339 |                 backtrace::resolve_frame_unsynchronized(&frame.frame, |symbol| {
    |                 ^^^^^^^^^ use of undeclared type or module `backtrace`
```

### PR DESCRIPTION
**Pull request by RalfJung**
Fixes https://github.com/rust-lang/rust/issues/64410

r? @alexcrichton

### CODE REVIEW

**Comment by alexcrichton** [comment]
Thanks! I think this ended up having a bit more `#[cfg]` than I was hoping for though. Could this perhaps go for an alternative strategy where libstd always depends on the `backtrace` crate, but only if the standard library's `backtrace` feature is enabled does it actually enable features of `backtrace`? If you remove all features from `backtrace`-the-crate it should basically compile anywhere since it's just a bunch of empty stubs, and that should remove any need for `#[cfg]` here.

**Comment by RalfJung** [comment]
@alexcrichton is `backtrace` without any features Rust-only, or does it still need a C toolchain?
Right now, libstd without features can be built without a C toolchain, which would be nice to preserve I think (once we no longer build a dylib, that makes cross-compilation *so* much simpler).

**Comment by RalfJung** [comment]
@alexcrichton I implemented your suggestion. However, for reasons I do not understand, it still builds "backtrace-sys" even when the backtrace feature is not set:
```
    Updating crates.io index
   Compiling core v0.0.0 (/home/r/src/rust/rustc.2/src/libcore)
   Compiling compiler_builtins v0.1.19
   Compiling libc v0.2.62
   Compiling cc v1.0.45
   Compiling build_helper v0.1.0 (/home/r/src/rust/rustc.2/src/build_helper)
   Compiling cmake v0.1.42
   Compiling unwind v0.0.0 (/home/r/src/rust/rustc.2/src/libunwind)
   Compiling backtrace-sys v0.1.31
   Compiling rustc_tsan v0.0.0 (/home/r/src/rust/rustc.2/src/librustc_tsan)
   Compiling rustc_asan v0.0.0 (/home/r/src/rust/rustc.2/src/librustc_asan)
   Compiling rustc_msan v0.0.0 (/home/r/src/rust/rustc.2/src/librustc_msan)
   Compiling rustc_lsan v0.0.0 (/home/r/src/rust/rustc.2/src/librustc_lsan)
   Compiling std v0.0.0 (/home/r/src/rust/rustc.2/src/libstd)
   Compiling rustc-std-workspace-core v1.99.0 (/home/r/src/rust/rustc.2/src/tools/rustc-std-workspace-core)
   Compiling cfg-if v0.1.8
   Compiling alloc v0.0.0 (/home/r/src/rust/rustc.2/src/liballoc)
   Compiling rustc-demangle v0.1.16
   Compiling panic_abort v0.0.0 (/home/r/src/rust/rustc.2/src/libpanic_abort)
   Compiling backtrace v0.3.37
   Compiling rustc-std-workspace-alloc v1.99.0 (/home/r/src/rust/rustc.2/src/tools/rustc-std-workspace-alloc)
   Compiling panic_unwind v0.0.0 (/home/r/src/rust/rustc.2/src/libpanic_unwind)
   Compiling hashbrown v0.5.0
    Finished release [optimized] target(s) in 26.09s
   Compiling rustc-std-workspace-std v1.99.0 (/home/r/src/rust/rustc.2/src/tools/rustc-std-workspace-std)
   Compiling proc_macro v0.0.0 (/home/r/src/rust/rustc.2/src/libproc_macro)
   Compiling term v0.0.0 (/home/r/src/rust/rustc.2/src/libterm)
   Compiling unicode-width v0.1.6
   Compiling getopts v0.2.21
   Compiling test v0.0.0 (/home/r/src/rust/rustc.2/src/libtest)
    Finished release [optimized] target(s) in 10.36s
```

**Comment by RalfJung** [comment]
Ah, I suppose the reason is this in backtrace's `Cargo.toml`:
```
rustc-dep-of-std = ["backtrace-sys/rustc-dep-of-std", "cfg-if/rustc-dep-of-std", "core", "compiler_builtins", "libc/rustc-dep-of-std", "rustc-demangle/rustc-dep-of-std"]
```

File: src/libstd/sys_common/backtrace.rs [hunk 1]
```diff
@@ -34,6 +33,7 @@ pub fn lock() -> impl Drop {
 }
 
 /// Prints the current backtrace.
+#[cfg(feature = "backtrace")]
```
Comment (alexcrichton) [inline src/libstd/sys_common/backtrace.rs]: Instead of `#[cfg]` here, could this also update [this section of code](https://github.com/rust-lang/rust/blob/b6269f27d99d7da9e95f0b3fdc53193dc8c42fbe/src/libstd/panicking.rs#L160-L206) to use `if cfg!(feature = "backtrace")` instead of `#[cfg]`?

**Comment by alexcrichton** [comment]
Looks great! Just one minor nit and otherwise r=me

**Comment by RalfJung** [comment]
@alexcrichton done (I made `log_backtrace` default to `None` instead of trying to reorganize the code).

@bors r=alexcrichton

However, do you have any idea how we could avoid building backtrace-sys when the backtrace feature is not set? Seems like currently, setting the `rustc-dep-of-std` feature flag of the backtrace crate also enables `backtrace-sys`.

**Comment by alexcrichton** [comment]
It may be sort of roundaboutedly possible but it's probably best to just have a feature for the crate itself which, if disabled, causes the build script to return immediately. That way when the `backtrace` crate *really* depends on `backtrace-sys`, it enables something like `backtrace-sys/actually-build` or something like that.

**Comment by RalfJung** [comment]
So, implicitly enabling "foo" when "foo/feature" is enabled is deliberate? That's quite unfortunate as it is a serious reduction in expressivity; *not* doing that would be easily worked around by enabling *both* "foo" and "foo/feature" when needed. Is there a tracking issue for such improvements/changes to the feature mechanism (I guess this one would have to be opt-in or tied to an "edition" or so)?

**Comment by est31** [comment]
>  implicitly enabling "foo" when "foo/feature" is enabled is deliberate? That's quite unfortunate

@RalfJung there is an issue about this: https://github.com/rust-lang/cargo/issues/3494

See also my comment in one of its dupes for a possible syntax that doesn't require a new edition: https://github.com/rust-lang/cargo/issues/7259#issuecomment-522391699
