### PR TITLE
Change the desugaring of `assert!` for better error output

### LINKED ISSUE #122159: inconsistent and confusing error message about first argument of `assert!`
### Code

```Rust
fn f(x: Result<i8, Box<dyn std::error::Error>>) {
    assert!(x.unwrap(), "expected Ok");      // expected `bool`, found `i8`
    assert!(x.unwrap_err(), "expected Err"); // cannot apply unary operator `!`
}
```

### Current output

```Shell
error[E0308]: mismatched types
 --> src/lib.rs:2:5
  |
2 |     assert!(x.unwrap(), "expected Ok");      // expected `bool`, found `i8`
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected `bool`, found `i8`

error[E0600]: cannot apply unary operator `!` to type `Box<dyn std::error::Error>`
 --> src/lib.rs:3:5
  |
3 |     assert!(x.unwrap_err(), "expected Err"); // cannot apply unary operator `!` to type `Box<dyn std::error::Error>`
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ cannot apply unary operator `!`
  |
  = note: this error originates in the macro `assert` (in Nightly builds, run with -Z macro-backtrace for more info)

Some errors have detailed explanations: E0308, E0600.
For more information about an error, try `rustc --explain E0308`.
```

### Desired output

_No response_

### Rationale and extra context

The macro `assert!` is documented as taking a bool as its first parameter. Therefore I suggest the error message be `expected ``bool``, found ``i8`` ` in both cases.

The very different error messages are very confusing, because `Result::unwrap` and `Result::unwrap_err` are basically the same. While I understand both error messages, I do not understand why they are different.

### Other cases

_No response_

### Rust Version

```Shell
rustc 1.76.0 (07dca489a 2024-02-04)
binary: rustc
commit-hash: 07dca489ac2d933c78d3c5158e3f43beefeb02ce
commit-date: 2024-02-04
host: x86_64-unknown-linux-gnu
release: 1.76.0
LLVM version: 17.0.6
```

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by estebank**
In the desugaring of `assert!`, we now expand to a `match` expression instead of `if !cond {..}`.

The span of incorrect conditions will point only at the expression, and not the whole `assert!` invocation.

```
error[E0308]: mismatched types
  --> $DIR/issue-14091.rs:2:13
   |
LL |     assert!(1,1);
   |             ^ expected `bool`, found integer
```

We no longer mention the expression needing to implement the `Not` trait.

```
error[E0308]: mismatched types
  --> $DIR/issue-14091-2.rs:15:13
   |
LL |     assert!(x, x);
   |             ^ expected `bool`, found `BytePos`
```

Now `assert!(val)` desugars to:

```rust
match val {
    true => {},
    _ => $crate::panic::panic_2021!(),
}
```

Fix #122159.

### CODE REVIEW

File: src/tools/miri/tests/pass/binops.rs [hunk 1]
```diff
@@ -2,23 +2,23 @@
 
 fn test_nil() {
     assert_eq!((), ());
-    assert!((!(() != ())));
-    assert!((!(() < ())));
-    assert!((() <= ()));
-    assert!((!(() > ())));
-    assert!((() >= ()));
+    assert!(!(() != ()));
```
Comment (estebank) [inline src/tools/miri/tests/pass/binops.rs:5]: All of these are because now the unnecessary parentheses lint (correctly) triggers on `assert!((expr))`.

File: tests/ui/issues/issue-14091-2.stderr [hunk 2]
```diff
@@ -1,18 +1,9 @@
...
-   |     ^^^^^^^^^^^^^ cannot apply unary operator `!`
-   |
-note: an implementation of `Not` might be missing for `BytePos`
-  --> $DIR/issue-14091-2.rs:6:1
-   |
-LL | pub struct BytePos(pub u32);
-   | ^^^^^^^^^^^^^^^^^^ must implement `Not`
-note: the trait `Not` must be implemented
-  --> $SRC_DIR/core/src/ops/bit.rs:LL:COL
-   = note: this error originates in the macro `assert` (in Nightly builds, run with -Z macro-backtrace for more info)
```
Comment (estebank) [inline tests/ui/issues/issue-14091-2.stderr:14]: This is the best example of how this is an improvement.

**Comment by estebank** [comment]
Sigh, clippy shows at least one test where a suggestion causes there to be a condition that isn't a `bool` but rather a type where `Not` returns a `bool`. We can easily continue supporting that by making the desugaring `!!cond`, but would rather not do that. This happens when it suggest changing `assert_eq!(non_bool, true)`, ending up as `assert!(non_bool)`, which doesn't work with this change .

**Comment by pnkfelix** [comment]
Isn't this technically a breaking change for e.g. ([playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021)):

```rust
struct Booly(i32);

impl std::ops::Not for Booly {
    type Output = bool;
    fn not(self) -> Self::Output {
        self.0 == 0
    }
}

fn main() {
    assert!(Booly(1), "booly booly!")
}
```

**Comment by pnkfelix** [comment]
At the very least, we might need to tie such a change to an edition.

I am not certain whether this decision would be a T-lang matter or a T-libs-api one. I'll nominate for T-lang for now.

(Namely: The question is whether we can start enforcing a rule that the first expression to `assert!` must be of bool type, which is how the [macro is documented](https://doc.rust-lang.org/std/macro.assert.html), but its current behavior is a little bit more general, as demonstrated in my [prior comment](https://github.com/rust-lang/rust/pull/122661#issuecomment-2004197554))

@rustbot label +I-lang-nominated

File: src/tools/rust-analyzer/crates/parser/test_data/parser/ok/0035_weird_exprs.rs [hunk 3]
```diff
@@ -64,8 +64,8 @@ fn notsure() {
 
 fn canttouchthis() -> usize {
     fn p() -> bool { true }
-    let _a = (assert!((true)) == (assert!(p())));
-    let _c = (assert!((p())) == ());
+    let _a = (assert!(true) == (assert!(p())));
+    let _c = (assert!(p()) == ());
```
Comment (Veykril) [inline src/tools/rust-analyzer/crates/parser/test_data/parser/ok/0035_weird_exprs.rs:68]: This will fail r-a's tests as the syntax tree is dumped in a neighboring file, probably best to not touch this

**Comment by estebank** [comment]
@pnkfelix we can keep the current (undocumented) behavior by making the desugaring be

```rust
{
    let x: bool = !!condition;
    x
}
```

instead of what this PR does:

```rust
{
    let x: bool = condition;
    x
}
```

I believe that would still cause errors to complain about `Not` not being implemented, instead of the more straightforward type error, albeit with a better span. I don't particularly like the idea of keeping the current emergent behavior if there aren't people exploiting it in crates.io.

File: src/tools/rust-analyzer/crates/parser/test_data/parser/ok/0035_weird_exprs.rs (hunk 3 above)
Comment (lnicola) [reply src/tools/rust-analyzer/crates/parser/test_data/parser/ok/0035_weird_exprs.rs:68]: Says it right there in the function name :stuck_out_tongue_winking_eye:.

(but seriously, it's fine to file this against RA if there's a decision to move forward with the change)

**Comment by pnkfelix** [comment]
> what about making the expansion edition-dependent? Is there precedent for that?

(to answer my own question, `panic!` is one obvious precedent here. So it seems like making it edition-dependent would be one acceptable path; no opinion yet as to which is best...)

File: src/tools/rust-analyzer/crates/parser/test_data/parser/ok/0035_weird_exprs.rs (hunk 3 above)
Comment (estebank) [reply src/tools/rust-analyzer/crates/parser/test_data/parser/ok/0035_weird_exprs.rs]: reverted

**Comment by estebank** [comment]
I tried the marker trait approach for <=2021, and it *kind* of worked, but the diagnostics were actually worse than just doing `{ let x: bool = !!$expr; x }`, which accounts for pretty much everything we currently support, but with better spans *and* better errors (if `typeof($expr)` implements `<Not<Output = NotBool>`, we now produce an appropriate E0308 type error).

**Comment by compiler-errors** [comment]
Since I don't think it's been acknowledged above, for the record, this breaks the following code:

```
fn hello(x: &bool) {
  assert!(x);
}
```

Because `&bool: Not<Output = bool>`.

**Comment by estebank** [comment]
@compiler-errors that is indeed the case for 2024 onwards, not [for previous editions](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=8829d46029927ae94a4e6da146492969).

**Comment by pnkfelix** [comment]
> @compiler-errors that is indeed the case for 2024 onwards, not [for previous editions](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=8829d46029927ae94a4e6da146492969).

I think the critical point is whether an edition-dependent expansion is worth breaking that case (of `assert!(x)` where `x: &bool`), or if we should do a non-breaking non-edition-dependent expansion using the `let x: bool = !!$expr` trick across the board...

**Comment by pnkfelix** [comment]
(this is waiting for a decision from T-lang and/or T-libs regarding what interface we want to commit to for `assert!`)

@rustbot +S-waiting-on-team -S-waiting-on-review

File: compiler/rustc_builtin_macros/src/assert.rs [hunk 4]
```diff
@@ -154,10 +161,66 @@ fn parse_assert<'a>(cx: &mut ExtCtxt<'a>, sp: Span, stream: TokenStream) -> PRes
...
+        // `{ let assert_macro: bool = !!$expr; assert_macro }`
+        let not = |expr| parser.mk_expr(span, ast::ExprKind::Unary(ast::UnOp::Not, expr));
+        not(not(cond_expr))
+    };
+    let block = thin_vec![
+        cx.stmt_let_ty(
+            DUMMY_SP,
+            false,
+            ident,
+            Some(cx.ty_ident(span, Ident::new(sym::bool, DUMMY_SP))),
```
Comment (m-ou-se) [inline compiler/rustc_builtin_macros/src/assert.rs:194]: The hygiene is not sufficient here. This example now breaks:

```rust
fn main() {
    type bool = i32;
    assert!(true);
}
```

```
error[E0308]: mismatched types
 --> src/main.rs:3:13
  |
3 |     assert!(true);
  |             ^^^^ expected `i32`, found `bool`
  |
```

Comment (m-ou-se) [reply compiler/rustc_builtin_macros/src/assert.rs:194]: It's probably better and easier to just use `if <expr> {} else { panic!(..) }`, without making any block expressions or local bindings, and without making any changes to the expansion in previous editions.

File: compiler/rustc_builtin_macros/src/assert.rs [hunk 5]
```diff
@@ -154,10 +161,66 @@ fn parse_assert<'a>(cx: &mut ExtCtxt<'a>, sp: Span, stream: TokenStream) -> PRes
...
+        // `{ let assert_macro: bool = $expr; assert_macro }`
+        cond_expr
+    } else {
+        // In <=2021, we allow anything that can be negated to `bool`, not just `bool`s. We use the
+        // "double not" trick to coerce the expression to `bool`. We still assign it to a new `bool`
+        // binding so that in the case of a type that implements `Not` but doesn't return `bool`,
+        // like `i32`, we still point at the condition and not at the whole macro.
+        // `{ let assert_macro: bool = !!$expr; assert_macro }`
+        let not = |expr| parser.mk_expr(span, ast::ExprKind::Unary(ast::UnOp::Not, expr));
+        not(not(cond_expr))
```
Comment (m-ou-se) [inline compiler/rustc_builtin_macros/src/assert.rs:187]: The `!!` solution adds more issues: this is now accepted:

```rust
use std::ops::Not;

struct A;
struct B;

impl Not for A {
    type Output = B;
    fn not(self) -> B { B }
}

impl Not for B {
    type Output = bool;
    fn not(self) -> bool { true }
}

fn main() {
    assert!(A);
}
```

**Comment by m-ou-se** [comment]
We briefly discussed this in the lib-api meeting.

This seems fine, but we thought it is important to consider if this could just be a non-edition change, considering how rare using `Not<Output=bool>` in assert!() probably is.

However, in the meeting we failed to realize that that includes `&bool`; I assume that would have changed the outcome. ^^'

**Comment by m-ou-se** [comment]
We discussed this again in the libs-api meeting. We think it's fine if `assert!()` no longer supports `&bool` (and other `Not<Output=bool>` types) in the next edition. It might be worth checking (with crater) if it's possible to get away with that (breaking) change in all editions, but that seems unlikely.

**Comment by estebank** [comment]
It just dawned on me that changing the macro from expanding to `if !cond { then }` to `if cond {} else { then }`, we get the consistent behavior we want *in every edition* without any "tricks".

**Comment by joshtriplett** [comment]
We discussed this in today's @rust-lang/lang meeting and confirmed that we feel this is entirely the scope of @rust-lang/libs-api to determine, not lang.

@pnkfelix wasn't present, and since he nominated it: if you have any objections to that, @pnkfelix, please raise them.

**Comment by joshtriplett** [comment]
What's the current state of this one? I think it has all the necessary approvals.

**Comment by estebank** [comment]
Ok, @joshtriplett, I've found *one* thing that might have gave me pause on calling this done: right now the output when the condition is not boolean (modulo references) is *not* ideal:

```
error[E0308]: mismatched types
 --> bat.rs:3:13
  |
3 |     assert!(x);
  |             ^ expected integer, found `bool`
  |
  = note: this error originates in the macro `assert` (in Nightly builds, run with -Z macro-backtrace for more info)
```

The expectation is reversed (because the diagnostic logic thinks that the matched value is the source of truth and not the pattern). Gonna take a look.

**Comment by estebank** [comment]
Ok, I am satisfied with the current implementation of this change.

The should be no backcompat issues with the current approach, and there are no diagnostic regressions outstanding. This is now waiting on review from @rust-lang/libs-api. The commits will need to be squashed, but I'm leaving them available for now purely in case the reviewer wants to see the different approaches tried.

**Comment by estebank** [comment]
r? t-libs-api

**Comment by estebank** [comment]
I don't understand why the test failure above is happening. I haven't been able to repro in my own linux setup.

**Comment by estebank** [comment]
Confirmed that the test failure is a miri issue. They are on top of it.

**Comment by dtolnay** [comment]
We discussed this PR in last week's standard library API meeting. Our understanding is that this will break cases of custom Not impls (in all editions), such as the following contrived one:

```rust
struct True;

impl core::ops::Not for True {
    type Output = bool;
    fn not(self) -> bool {
        false
    }
}

fn example() {
    assert!(True);
}
```

but that it will _not_ break `&bool` as earlier iterations of the PR used to, such as:

```rust
struct Struct {
    valid: bool,
}

fn example(s: &Struct) {
    let Struct { valid } = s;
    assert!(valid);
}
```

In return, error messages get better.

Those present were on board with the change, if we can get a team FCP. If someone would like to see a crater run, that can happen in parallel with the FCP.

@rfcbot fcp merge

File: compiler/rustc_builtin_macros/src/assert.rs [hunk 6]
```diff
@@ -89,26 +89,30 @@ pub(crate) fn expand_assert<'cx>(
...
-    span: Span,
-    cond: P<Expr>,
-    then: P<Expr>,
-    els: Option<P<Expr>>,
-) -> P<Expr> {
-    cx.expr_if(span, cx.expr(span, ExprKind::Unary(UnOp::Not, cond)), then, els)
+/// `match <cond> { true => {} _ => <then> }`
+fn assert_cond_check(cx: &ExtCtxt<'_>, span: Span, cond: P<Expr>, then: P<Expr>) -> P<Expr> {
+    // Instead of expanding to `if !<cond> { <then> }`, we expand to
+    // `match <cond> { true => {} _ <then> }`.
```
Comment (teor2345) [inline compiler/rustc_builtin_macros/src/assert.rs:107]: Is there a typo here?
```suggestion
    // `match <cond> { true => {} _ => <then> }`.
```

File: src/tools/clippy/tests/ui/incompatible_msrv.stderr [hunk 7]
```diff
@@ -36,17 +36,26 @@ LL |     my_panic!("foo");
...
    = note: this error originates in the macro `my_panic` (in Nightly builds, run with -Z macro-backtrace for more info)
 
+error: sub-expression diverges
+  --> tests/ui/incompatible_msrv.rs:59:13
+   |
+LL |     assert!(core::panicking::panic("out of luck"));
+   |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
+   |
+   = note: `-D clippy::diverging-sub-expression` implied by `-D warnings`
+   = help: to override `-D warnings` add `#[allow(clippy::diverging_sub_expression)]`
```
Comment (estebank) [inline src/tools/clippy/tests/ui/incompatible_msrv.stderr:46]: @rust-lang/clippy would this be considered a regression? The lint triggers here now because of the change to the expansion of `assert!`.

Comment (samueltardieu) [reply src/tools/clippy/tests/ui/incompatible_msrv.stderr:46]: It looks like a lint ordering issue (lint order is not defined). I would add `#[allow(clippy::diverging_sub_expression)]` (as this is not the lint this test wants to trigger) and check that the original diagnostic still stands.

Comment (flip1995) [reply src/tools/clippy/tests/ui/incompatible_msrv.stderr:46]: I'd rather allow unrelated lints.

I agree that cross-checking lints would be nice. But doing that in some tests won't give us any guarantees, but just increases the number of files that need to be updated for changes.

Comment (estebank) [reply src/tools/clippy/tests/ui/incompatible_msrv.stderr:46]: From my experience on rustc, the number of errors being affected by changes isn't that big of a deal and has helped caught issues during development, but changed this test to avoid it, leaving it to the team to decide whether to add cross-lint tests at your leisure.

**Comment by estebank** [comment]
As per https://github.com/rust-lang/rust/pull/122661#issuecomment-2886972197 and https://github.com/rust-lang/rust/pull/122661#issuecomment-2714915388, I believe this can be merged. The [error I couldn't reproduce](https://github.com/rust-lang/rust/pull/122661#issuecomment-2900431922) no longer seems to be triggering.

Running crater just in case.

@craterbot run mode=check-only

**Comment by estebank** [comment]
@craterbot check

**Comment by traviscross** [comment]
It's interesting how this ends up interacting, on older editions, with things we improved in Rust 2024.  Most (but not all) of the regressions match this pattern:

```rust
use core::cell::RefCell;

fn f1() {
    let x = RefCell::new([0u8]);
    if !x.borrow().is_empty() { //~ OK
        panic!()
    }
}

fn f2() {
    let x = RefCell::new([0u8]);
    match x.borrow().is_empty() {
        //[2021]~^ ERROR does not live long enough
        //[2024]~^ OK
        false => panic!(),
        _ => (),
    }
}
```

Both versions work in Rust 2024, but the latter fails in earlier editions due to the [rule](https://doc.rust-lang.org/nightly/edition-guide/rust-2024/temporary-tail-expr-scope.html) about temporaries in tail expressions.  The `f1` version works because `if` drops the temporaries in its condition before entering either branch, but `match` doesn't do this for its scrutinee, so the scopes of these temporaries extend beyond the `match` itself and therefore interact with the old-edition tail expression rule.

**Comment by estebank** [comment]
There are at least two potential sources of regressions:

Lifetimes:

```
[INFO] [stdout] error[E0597]: `data` does not live long enough
[INFO] [stdout]    --> src/controllers/servitor/authorization.rs:134:11
[INFO] [stdout]     |
[INFO] [stdout] 124 |         let data = mock_data(None);
[INFO] [stdout]     |             ---- binding `data` declared here
[INFO] [stdout] ...
[INFO] [stdout] 134 |         assert!(data.read().await.servitor.is_empty())
[INFO] [stdout]     |                 ^^^^-------------
[INFO] [stdout]     |                 |
[INFO] [stdout]     |                 borrowed value does not live long enough
[INFO] [stdout]     |                 a temporary with access to the borrow is created here ...
[INFO] [stdout] 135 |     }
[INFO] [stdout]     |     -
[INFO] [stdout]     |     |
[INFO] [stdout]     |     `data` dropped here while still borrowed
[INFO] [stdout]     |     ... and the borrow might be used here, when that temporary is dropped and runs the `Drop` code for type `tokio::sync::RwLockReadGuard`
[INFO] [stdout]     |
[INFO] [stdout] help: consider adding semicolon after the expression so its temporaries are dropped sooner, before the local variables declared by the block are dropped
[INFO] [stdout]     |
[INFO] [stdout] 134 |         assert!(data.read().await.servitor.is_empty());
[INFO] [stdout]     |                                                       +
```

I think I just need to change the desugaring to be for a statement of a match instead of a match expression.

Inference:

```
[INFO] [stdout] error[E0282]: type annotations needed
[INFO] [stdout]   --> java_runtime/tests/classes/java/util/jar/test_jar_file.rs:63:18
[INFO] [stdout]    |
[INFO] [stdout] 63 |     assert!(!jvm.invoke_virtual(&entries, "hasMoreElements", "()Z", ()).await?);
[INFO] [stdout]    |                  ^^^^^^^^^^^^^^ cannot infer type of the type parameter `U` declared on the method `invoke_virtual`
[INFO] [stdout]    |
[INFO] [stdout] help: consider specifying the generic arguments
[INFO] [stdout]    |
[INFO] [stdout] 63 |     assert!(!jvm.invoke_virtual::<(), U>(&entries, "hasMoreElements", "()Z", ()).await?);
[INFO] [stdout]    |                                +++++++++
```

I don't think there's anything we can do to avoid the inference regression, but thankfully only two crates have real code that triggers it.

**Comment by teor2345** [comment]
Most fixes are spurious, they seem to be in build tools.

There are a few (expected?) type ambiguity errors, and many more drop order errors.

### Type ambiguity (2 crates)

cradle 0.2.2

```
[INFO] [stdout] error[E0282]: type annotations needed
[INFO] [stdout]    --> src/lib.rs:972:21
[INFO] [stdout]     |
[INFO] [stdout] 972 |             assert!(!run_output!("false"));
[INFO] [stdout]     |                     ^^^^^^^^^^^^^^^^^^^^^ cannot infer type
```

dlunch/jvm -> rust_java v0.0.1 (?)

```
[INFO] [stderr]     Checking rust_java v0.0.1 (/opt/rustwide/workdir)
[INFO] [stdout] error[E0282]: type annotations needed
[INFO] [stdout]   --> java_runtime/tests/classes/java/util/jar/test_jar_file.rs:63:18
[INFO] [stdout]    |
[INFO] [stdout] 63 |     assert!(!jvm.invoke_virtual(&entries, "hasMoreElements", "()Z", ()).await?);
[INFO] [stdout]    |                  ^^^^^^^^^^^^^^ cannot infer type of the type parameter `U` declared on the method `invoke_virtual`
[INFO] [stdout]    |
[INFO] [stdout] help: consider specifying the generic arguments
[INFO] [stdout]    |
[INFO] [stdout] 63 |     assert!(!jvm.invoke_virtual::<(), U>(&entries, "hasMoreElements", "()Z", ()).await?);
[INFO] [stdout]    |                                +++++++++
```



### Drop order (22 crates)

Most failures seem to be around drop order when the assert is not followed by a semicolon. Hyrum's law in action.

#### mutex lock drop order

syndicus 0.3.1

```
[INFO] [stderr]     Checking syndicus v0.3.1 (/opt/rustwide/workdir)
[INFO] [stdout] error[E0597]: `counter` does not live long enough
[INFO] [stdout]   --> src/scope.rs:79:18
[INFO] [stdout]    |
[INFO] [stdout] 65 |         let counter = scope::<_, ()>(|tasker| {
[INFO] [stdout]    |             ------- binding `counter` declared here
[INFO] [stdout] ...
[INFO] [stdout] 79 |         assert!(*counter.lock().await == task_load)
[INFO] [stdout]    |                  ^^^^^^^-------------
[INFO] [stdout]    |                  |
[INFO] [stdout]    |                  borrowed value does not live long enough
[INFO] [stdout]    |                  a temporary with access to the borrow is created here ...
[INFO] [stdout] 80 |     }
[INFO] [stdout]    |     -
[INFO] [stdout]    |     |
[INFO] [stdout]    |     `counter` dropped here while still borrowed
[INFO] [stdout]    |     ... and the borrow might be used here, when that temporary is dropped and runs the `Drop` code for type `tokio::sync::MutexGuard`
[INFO] [stdout]    |
[INFO] [stdout] help: consider adding semicolon after the expression so its temporaries are dropped sooner, before the local variables declared by the block are dropped
[INFO] [stdout]    |
[INFO] [stdout] 79 |         assert!(*counter.lock().await == task_load);
```

statsig-rust 0.6.2-beta.2507190239 in tests

Similar to the lock above:

```
[INFO] [stderr]     Checking statsig-rust v0.6.2-beta.2507190239 (/opt/rustwide/workdir)
…
[INFO] [stdout] error[E0597]: `obs_client` does not live long enough
[INFO] [stdout]    --> tests/event_logger_flush_tests.rs:346:13
…
[INFO] [stdout] 346 |     assert!(obs_client.error_calls.lock().unwrap().is_empty())
```

saptest 0.5.0 in tests

Similar to the lock above:

```
[INFO] [stderr]     Checking saptest v0.5.0 (/opt/rustwide/workdir)
[INFO] [stdout]    --> src/lib/tests/test_hard_mode_toy_t1.rs:164:13
…
[INFO] [stdout] error[E0597]: `pets` does not live long enough
[INFO] [stdout] 164 |     assert!(pets[2].read().unwrap().item.is_none())
…
[INFO] [stdout] error[E0597]: `pets` does not live long enough
[INFO] [stdout]    --> src/lib/tests/test_hard_mode_toy_t1.rs:192:13
[INFO] [stdout]     |
…
[INFO] [stdout] 192 |     assert!(pets[2].read().unwrap().item.is_none())
```

Also:
* reqwest-conditional-middleware 0.4.0 in tests:
  * src/lib.rs:161
  * src/lib.rs:180
* happylock 0.5.0 in tests (?)
  * src/collection/boxed.rs, many errors
* rainshowerLabs/blutgang
* Angelin01/gjallarbot

#### Other drop order

scylla-cql 1.3.0 -> criterion v0.6.0 (?)

Iterator drop order

```
[INFO] [stderr]     Checking criterion v0.6.0
[INFO] [stdout] error[E0597]: `values` does not live long enough
[INFO] [stdout]    --> src/serialize/row_tests.rs:564:13
[INFO] [stdout]     |
[INFO] [stdout] 551 |       let mut values = SerializedValues::new();
[INFO] [stdout]     |           ---------- binding `values` declared here
[INFO] [stdout] ...
[INFO] [stdout] 564 |       assert!(values
[INFO] [stdout]     |               -^^^^^
[INFO] [stdout]     |               |
[INFO] [stdout]     |  _____________borrowed value does not live long enough
[INFO] [stdout]     | |
[INFO] [stdout] 565 | |         .iter()
[INFO] [stdout]     | |_______________- a temporary with access to the borrow is created here ...
[INFO] [stdout] 566 |           .all(|v| v == RawValue::Value(&[0, 0, 0, 0, 0x07, 0x5b, 0xcd, 0x15])))
[INFO] [stdout] 567 |   }
[INFO] [stdout]     |   -
[INFO] [stdout]     |   |
[INFO] [stdout]     |   `values` dropped here while still borrowed
[INFO] [stdout]     |   ... and the borrow might be used here, when that temporary is dropped and runs the destructor for type `impl Iterator<Item = RawValue<'_>>`
[INFO] [stdout]     |
[INFO] [stdout] help: consider adding semicolon after the expression so its temporaries are dropped sooner, before the local variables declared by the block are dropped
[INFO] [stdout]     |
[INFO] [stdout] 566 |         .all(|v| v == RawValue::Value(&[0, 0, 0, 0, 0x07, 0x5b, 0xcd, 0x15])));
[INFO] [stdout]     |  
```

Also:
* orc 0.0.1 in tests: heap allocator (?) drop order
  * src/lib.rs:268
* laurel 0.7.2 -> toml v0.8.20: RefCell
  * src/coalesce.rs:1863
* anyflux 0.1.0: Rc
  * src/context.rs:152
* analyse-json 0.6.1, cbrown1234/analyse-json in tests (?): Rc
  * src/json/ndjson.rs, many errors
* mukuact/simCAN: RefCell
* l0s/rlox: Rc
* kimond/rust_cmustify: RefCell
* hi-rustin/rq: Iterator
* gpabois/jarnac: RefPage
* dlunch/Renderer: Iterator
* babarai45/crux_fram: Iterator
* astahhu/calendar-join: impl Deref
* JohnMitchell04/toy-langauge: Ref, `Result<Module<'_>, _>`
* Barandis/rust-c64: Ref

**Comment by traviscross** [comment]
If someone has a minimization of those type inference regressions, probably we'll be interested to look at that.

**Comment by estebank** [comment]
@craterbot check

**Comment by estebank** [comment]
@traviscross I've been trying to replicate a case where inference fails under the new desugaring but the old doesn't, and I'm having trouble doing so.

**Comment by estebank** [comment]
There's an option to avoid the inference regression, by looking at the condition and if there's a single `!`, then remove it and change the `cx.expr_bool()` to be `false` instead of `true`, which keeps everything working and makes `cradle` work as well, but that would get in the way of the change to the clippy error telling people to leverage the double negation `!!` trick for things that have `Not<Output=bool>` but aren't `bool`. I haven't been able to cause `RustJava` to fail locally in any way.

**Comment by traviscross** [comment]
For me, in this case, it's probably more important to understand them than necessarily to avoid them.

**Comment by estebank** [comment]
@traviscross for `cradle`, it is a case of having something akin to `fn foo<T: Output>() -> T` which can coerce to `bool`, but having `!foo()` causes inference to get lost (the `assert!` makes the `!foo()` to be `bool`, but that doesn't get propagated to `foo()` because anything can potentially `impl Not<Output = bool>`). I'm not entirely sure why it works under the current code (given that it desugars to `if !cond { panic(); }`. From the context of the `RustJava` one (`assert!(!jvm.invoke_virtual(...).await?)`), I'm assuming it's a similar situation.

**Comment by teor2345** [comment]
In one crate there's a lot of:
> [INFO] [stdout] error: unnecessary parentheses around `match` scrutinee expression
> [INFO] [stdout]    --> src/tests/mod.rs:53:21
> [INFO] [stdout]     |
> [INFO] [stdout] 53  |             assert!((m.opt_present("test")));

https://crater-reports.s3.amazonaws.com/pr-122661-1/try%23b047d5f4496a7526d91d0dddea494c05853f2a7b/reg/getopts-0.2.23/log.txt

Everything else looks like spurious cmake, docker, or download errors.

**Comment by estebank** [comment]
Yes, the only "real" regression is the inference one, which only affects `dlunch/RustJava`.

**Comment by estebank** [comment]
@dtolnay under whose responsibility does it fall to `r+` the PR itself, after [`t-libs-api` approval](https://github.com/rust-lang/rust/pull/122661#issuecomment-2714915388)?

**Comment by Noratrieb** [comment]
since the changes are in the compiler,
r? compiler

File: compiler/rustc_parse/src/parser/expr.rs [hunk 8]
```diff
@@ -3991,7 +3991,7 @@ impl<'a> Parser<'a> {
         P(Expr { kind, span, attrs, id: DUMMY_NODE_ID, tokens: None })
     }
 
-    pub(crate) fn mk_expr(&self, span: Span, kind: ExprKind) -> P<Expr> {
+    pub fn mk_expr(&self, span: Span, kind: ExprKind) -> P<Expr> {
```
Comment (petrochenkov) [inline compiler/rustc_parse/src/parser/expr.rs]: Unnecessary change.

File: compiler/rustc_parse/src/parser/stmt.rs [hunk 9]
```diff
@@ -1045,16 +1045,11 @@ impl<'a> Parser<'a> {
...
-        stmts: ThinVec<Stmt>,
-        rules: BlockCheckMode,
-        span: Span,
-    ) -> P<Block> {
+    pub fn mk_block(&self, stmts: ThinVec<Stmt>, rules: BlockCheckMode, span: Span) -> P<Block> {
         P(Block { stmts, id: DUMMY_NODE_ID, rules, span, tokens: None })
     }
 
-    pub(super) fn mk_stmt(&self, span: Span, kind: StmtKind) -> Stmt {
+    pub fn mk_stmt(&self, span: Span, kind: StmtKind) -> Stmt {
```
Comment (petrochenkov) [inline compiler/rustc_parse/src/parser/stmt.rs]: Unnecessary changes in this file too.

File: compiler/rustc_trait_selection/src/error_reporting/infer/mod.rs [hunk 10]
```diff
@@ -1618,8 +1618,16 @@ impl<'a, 'tcx> TypeErrCtxt<'a, 'tcx> {
...
-            let found = with_forced_trimmed_paths!(f.sort_string(self.tcx));
+            let mut expected = with_forced_trimmed_paths!(e.sort_string(self.tcx));
+            let mut found = with_forced_trimmed_paths!(f.sort_string(self.tcx));
+            if let Some(def_id) = cause.span.ctxt().outer_expn_data().macro_def_id
+                && self.tcx.is_diagnostic_item(sym::assert_macro, def_id)
+            {
+                // When the type error comes from `assert!()`, the cause and effect are reversed
+                // because that macro expands to `match val { false => {panic!()}, _ => {} }`, which
+                // would say something like "expected `Type`, found `bool`", confusing the user.
+                (found, expected) = (expected, found);
```
Comment (petrochenkov) [inline compiler/rustc_trait_selection/src/error_reporting/infer/mod.rs:1633]: If this makes sense for assert, then it makes sense for all similarly structured matches.

File: compiler/rustc_trait_selection/src/error_reporting/infer/mod.rs [hunk 11]
```diff
@@ -2180,15 +2188,27 @@ impl<'a, 'tcx> TypeErrCtxt<'a, 'tcx> {
...
         }
+        let (mut expected, mut found) = (exp_found.expected, exp_found.found);
+        if let Some(def_id) = cause.span.ctxt().outer_expn_data().macro_def_id
+            && self.tcx.is_diagnostic_item(sym::assert_macro, def_id)
+        {
+            // When the type error comes from `assert!()`, the cause and effect are reversed
+            // because that macro expands to `match val { false => {panic!()}, _ => {} }`, which
+            // would say something like
+            // = note: expected `Type`
+            //            found `bool`"
```
Comment (petrochenkov) [inline compiler/rustc_trait_selection/src/error_reporting/infer/mod.rs:2221]: If this makes sense for assert, then it makes sense for all similarly structured matches.

**Comment by petrochenkov** [comment]
I'd prefer to land the miscellaneous diagnostic, clippy and test changes separately from the desugaring change itself.

File: compiler/rustc_trait_selection/src/error_reporting/infer/mod.rs (hunk 11 above)
Comment (estebank) [reply compiler/rustc_trait_selection/src/error_reporting/infer/mod.rs:2221]: This is a consequence of `assert!(condition, msg)` expanding to

```rust
match condition {
    true => {}
    _ => panic!(msg),
};
```

On that expanded code, the output is

```
error[E0308]: mismatched types
 --> src/main.rs:4:5
  |
3 | match condition {
  |       --------- this expression has type `&str`
4 |     true => {}
  |     ^^^^ expected `str`, found `bool`
```

but without this reversal the output for `assert!("foo")` the output is:

```
error[E0308]: mismatched types
  --> $DIR/issue-28308.rs:2:13
   |
LL |     assert!("foo");
   |             ^^^^^ expected `str`, found `bool`
```

which as far as the user is concerned, is always backwards.

Do note that I went over several iterations to try and make this kind of change unnecessary, like making the desugaring be `let condition: bool = "foo";`, but we *must* rely on match ergonomics to continue supporting the prior behavior (where `&bool` and `bool` are accepted).

We could instead modify this to take macros in general into account to apply these changes, when the pattern is a literal coming from a macro.

**Comment by estebank** [comment]
I'll split off the clippy changes shortly.

File: compiler/rustc_trait_selection/src/error_reporting/infer/mod.rs (hunk 10 above)
Comment (estebank) [reply compiler/rustc_trait_selection/src/error_reporting/infer/mod.rs:1633]: Changed it to be more general: if the pattern found comes from user code, while the obligation comes from a macro, only then we revert the expectation order.

File: src/tools/clippy/clippy_lints/src/missing_asserts_for_indexing.rs
Comment (estebank) [inline src/tools/clippy/clippy_lints/src/missing_asserts_for_indexing.rs:1]: These changes need to land with this PR, as they need to be kept in sync with the macro desugaring to function properly.

**Comment by estebank** [comment]
Blocked on https://github.com/rust-lang/rust/pull/145227, https://github.com/rust-lang/rust-clippy/pull/15453 and (less so, as the reason those need to change is because the new desugaring causes the existing lint to correctly trigger) https://github.com/rust-lang/rust/pull/145228.

File: compiler/rustc_trait_selection/src/error_reporting/infer/mod.rs (hunk 10 above)
Comment (petrochenkov) [reply compiler/rustc_trait_selection/src/error_reporting/infer/mod.rs:1633]: That's almost exactly what I wanted to suggest, except I thought about replacing "from a macro" with "from an external macro", but I'm not sure what would be better in practice.

**Comment by petrochenkov** [comment]
r=me after (probably) waiting for https://github.com/rust-lang/rust-clippy/pull/15453, and squashing commits.
@rustbot author

**Comment by Zalathar** [comment]
Investigating mysterious rollup failure: https://github.com/rust-lang/rust/pull/145373#issuecomment-3187661017

@bors try jobs=i686-gnu-nopt-1

**Comment by Zalathar** [comment]
Bingo!

@bors r-

**Comment by estebank** [comment]
Thank you to everyone who spent time reviewing this PR!

**Comment by estebank** [comment]
@durin42 could you point us to where that change in behavior affected you? We tried our best at doing our due diligence to avoid that behavior affecting the ecosystem, but if there was a failure in our methodology it is best to know about it so that we can revise our process in for future changes.

**Comment by estebank** [comment]
I'm shocked this wasn't picked up by our crater runs :-/

We had an earlier proposed approach to restrict the new desugaring to the latest edition, which would have helped/masked this one case. I am concerned that there might have been more cases out there.

**Comment by saethlin** [comment]
> I'm shocked this wasn't picked up by our crater runs :-/

`bitvec` is prepare-fail in at least the second crater run above, along with 135,940 other crates.

https://rust-lang.zulipchat.com/#narrow/channel/242791-t-infra/topic/crater.3A.20.3E100k.20.22prepare-fail.22.20crates.3F

**Comment by Skgland** [comment]
> > I'm shocked this wasn't picked up by our crater runs :-/
> 
> `bitvec` is prepare-fail in at least the second crater run above, along with 135,940 other crates.
> 
> https://rust-lang.zulipchat.com/#narrow/channel/242791-t-infra/topic/crater.3A.20.3E100k.20.22prepare-fail.22.20crates.3F

This scenario was basically what my addition of the prepare-fail category was trying to prevent.
By moving spurious failures during crate preparation into their own category and including that category in the retry-regeressed-list.txt they were supposed to be included when a retry is done to prevent the spurious failure from masking an actual regression. Though that obviously only works if the crater run is actually retried with the retry-regressed-list.txt .

**Comment by Amanieu** [comment]
@estebank Beta is branching later this week, if you are submitting a PR to revert it will need a beta backport.
