### PR TITLE
Fix ICE when passing DefId-creating args to legacy_const_generics.

### LINKED ISSUE #123077: ICE: thir: `LocalTableInContext: key not found`
auto-reduced (treereduce-rust):
````rust
use std::arch::x86_64::{__m128, _mm_blend_ps};

pub fn sse41_blend_noinline( ) -> __m128 {
    let f = { |x, y| unsafe {
        _mm_blend_ps(x, y, { |x, y| unsafe })
    }};
    f(x, y)
}




````

original:
````rust
use std::arch::x86_64::{__m128, _mm_blend_ps};

pub fn sse41_blend_noinline( ) -> __m128 {
    let f = { |x, y| unsafe {
        _mm_blend_ps(x, y, { |x, y| unsafe })
    }};
    f(x, y)
}

pub fn main() {}

````

Version information
````
rustc 1.79.0-nightly (35936c483 2024-03-25)
binary: rustc
commit-hash: 35936c4839dd272646394779d151e060d0f6b3ac
commit-date: 2024-03-25
host: x86_64-unknown-linux-gnu
release: 1.79.0-nightly
LLVM version: 18.1.2

````

Command:
`/home/matthias/.rustup/toolchains/master/bin/rustc `

<details><summary><strong>Program output</strong></summary>
<p>

```
error: expected `{`, found `}`
 --> /tmp/icemaker_global_tempdir.jaXmoMCLgeqT/rustc_testrunner_tmpdir_reporting.sSd9oSx6BE2l/mvce.rs:5:44
  |
5 |         _mm_blend_ps(x, y, { |x, y| unsafe })
  |                              ------ ------ ^ expected `{`
  |                              |      |
  |                              |      while parsing this `unsafe` expression
  |                              while parsing the body of this closure
  |
help: you might have meant to open the body of the closure, instead of enclosing the closure in a block
  |
5 -         _mm_blend_ps(x, y, { |x, y| unsafe })
5 +         _mm_blend_ps(x, y,  |x, y| { unsafe })
  |

error[E0425]: cannot find value `x` in this scope
 --> /tmp/icemaker_global_tempdir.jaXmoMCLgeqT/rustc_testrunner_tmpdir_reporting.sSd9oSx6BE2l/mvce.rs:7:7
  |
7 |     f(x, y)
  |       ^ help: a local variable with a similar name exists: `f`

error[E0425]: cannot find value `y` in this scope
 --> /tmp/icemaker_global_tempdir.jaXmoMCLgeqT/rustc_testrunner_tmpdir_reporting.sSd9oSx6BE2l/mvce.rs:7:10
  |
7 |     f(x, y)
  |          ^ help: a local variable with a similar name exists: `f`

error[E0601]: `main` function not found in crate `mvce`
 --> /tmp/icemaker_global_tempdir.jaXmoMCLgeqT/rustc_testrunner_tmpdir_reporting.sSd9oSx6BE2l/mvce.rs:8:2
  |
8 | }
  |  ^ consider adding a `main` function to `/tmp/icemaker_global_tempdir.jaXmoMCLgeqT/rustc_testrunner_tmpdir_reporting.sSd9oSx6BE2l/mvce.rs`

thread 'rustc' panicked at compiler/rustc_mir_build/src/thir/cx/mod.rs:80:58:
LocalTableInContext: key not found
stack backtrace:
   0:     0x73247a222fd5 - std::backtrace_rs::backtrace::libunwind::trace::h358d27b0beb91d52
                               at /rustc/35936c4839dd272646394779d151e060d0f6b3ac/library/std/src/../../backtrace/src/backtrace/libunwind.rs:105:5
   1:     0x73247a222fd5 - std::backtrace_rs::backtrace::trace_unsynchronized::hb23626f2832be2ef
                               at /rustc/35936c4839dd272646394779d151e060d0f6b3ac/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x73247a222fd5 - std::sys_common::backtrace::_print_fmt::h12a2241e36ed88c8
                               at /rustc/35936c4839dd272646394779d151e060d0f6b3ac/library/std/src/sys_common/backtrace.rs:68:5
   3:     0x73247a222fd5 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h00f4d0202e49b73c
                               at /rustc/35936c4839dd272646394779d151e060d0f6b3ac/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x73247a27413b - core::fmt::rt::Argument::fmt::h50b99c7ac9b6f780
                               at /rustc/35936c4839dd272646394779d151e060d0f6b3ac/library/core/src/fmt/rt.rs:142:9
   5:     0x73247a27413b - core::fmt::write::h052bbc034f024029
                               at /rustc/35936c4839dd272646394779d151e060d0f6b3ac/library/core/src/fmt/mod.rs:1153:17
   6:     0x73247a217d6f - std::io::Write::write_fmt::h8a7055241a914793
                               at /rustc/35936c4839dd272646394779d151e060d0f6b3ac/library/std/src/io/mod.rs:1843:15
   7:     0x73247a222dae - std::sys_common::backtrace::_print::hc7429e59d20aef3d
                               at /rustc/35936c4839dd272646394779d151e060d0f6b3ac/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x73247a222dae - std::sys_common::backtrace::print::h098f1297ce95d7fd
                               at /rustc/35936c4839dd272646394779d151e060d0f6b3ac/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x73247a225a29 - std::panicking::default_hook::{{closure}}::hfacad2d95a15b54f
  10:     0x73247a225793 - std::panicking::default_hook::h335f6dbc0bdf0870
                               at /rustc/35936c4839dd272646394779d151e060d0f6b3ac/library/std/src/panicking.rs:292:9
  11:     0x732476bd127f - std[8986ecfb476bfa7d]::panicking::update_hook::<alloc[d5b01f14e800d591]::boxed::Box<rustc_driver_impl[4b2f8406c0f6a8ac]::install_ice_hook::{closure#0}>>::{closure#0}
  12:     0x73247a22612c - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h981ebc744fbdca0e
                               at /rustc/35936c4839dd272646394779d151e060d0f6b3ac/library/alloc/src/boxed.rs:2029:9
  13:     0x73247a22612c - std::panicking::rust_panic_with_hook::h1985d360b67b5f37
                               at /rustc/35936c4839dd272646394779d151e060d0f6b3ac/library/std/src/panicking.rs:793:13
  14:     0x73247a225ed6 - std::panicking::begin_panic_handler::{{closure}}::hf64883af21dee792
                               at /rustc/35936c4839dd272646394779d151e060d0f6b3ac/library/std/src/panicking.rs:658:13
  15:     0x73247a223499 - std::sys_common::backtrace::__rust_end_short_backtrace::h48fdcafa2a5427ef
                               at /rustc/35936c4839dd272646394779d151e060d0f6b3ac/library/std/src/sys_common/backtrace.rs:171:18
  16:     0x73247a225c07 - rust_begin_unwind
                               at /rustc/35936c4839dd272646394779d151e060d0f6b3ac/library/std/src/panicking.rs:646:5
  17:     0x73247a2705d6 - core::panicking::panic_fmt::h01c5db37aea323f1
                               at /rustc/35936c4839dd272646394779d151e060d0f6b3ac/library/core/src/panicking.rs:72:14
  18:     0x73247a27078c - core::panicking::panic_display::h10389bf786f46e48
                               at /rustc/35936c4839dd272646394779d151e060d0f6b3ac/library/core/src/panicking.rs:193:5
  19:     0x73247a27037c - core::panicking::panic_str::h841866e0247822cd
                               at /rustc/35936c4839dd272646394779d151e060d0f6b3ac/library/core/src/panicking.rs:168:5
  20:     0x73247a27037c - core::option::expect_failed::h56dab3756fc11b37
                               at /rustc/35936c4839dd272646394779d151e060d0f6b3ac/library/core/src/option.rs:1994:5
  21:     0x73247841ad99 - rustc_mir_build[dc0b4206fe456e8d]::thir::cx::thir_body
  22:     0x732478419712 - rustc_query_impl[a0c31ac015223081]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[a0c31ac015223081]::query_impl::thir_body::dynamic_query::{closure#2}::{closure#0}, rustc_middle[b97de266c643709b]::query::erase::Erased<[u8; 16usize]>>
  23:     0x7324782990ed - rustc_query_system[97bff28321f2bac]::query::plumbing::try_execute_query::<rustc_query_impl[a0c31ac015223081]::DynamicConfig<rustc_query_system[97bff28321f2bac]::query::caches::VecCache<rustc_span[ebc71fb0dc5af8f5]::def_id::LocalDefId, rustc_middle[b97de266c643709b]::query::erase::Erased<[u8; 16usize]>>, false, false, false>, rustc_query_impl[a0c31ac015223081]::plumbing::QueryCtxt, false>
  24:     0x732478298c69 - rustc_query_impl[a0c31ac015223081]::query_impl::thir_body::get_query_non_incr::__rust_end_short_backtrace
  25:     0x7324784204d9 - rustc_mir_build[dc0b4206fe456e8d]::thir::pattern::check_match::check_match
  26:     0x73247841f6bb - rustc_query_impl[a0c31ac015223081]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[a0c31ac015223081]::query_impl::check_match::dynamic_query::{closure#2}::{closure#0}, rustc_middle[b97de266c643709b]::query::erase::Erased<[u8; 1usize]>>
  27:     0x7324787ca5bc - rustc_query_system[97bff28321f2bac]::query::plumbing::try_execute_query::<rustc_query_impl[a0c31ac015223081]::DynamicConfig<rustc_query_system[97bff28321f2bac]::query::caches::VecCache<rustc_span[ebc71fb0dc5af8f5]::def_id::LocalDefId, rustc_middle[b97de266c643709b]::query::erase::Erased<[u8; 1usize]>>, false, false, false>, rustc_query_impl[a0c31ac015223081]::plumbing::QueryCtxt, false>
  28:     0x7324787ca23f - rustc_query_impl[a0c31ac015223081]::query_impl::check_match::get_query_non_incr::__rust_end_short_backtrace
  29:     0x73247840f2f3 - rustc_mir_build[dc0b4206fe456e8d]::build::mir_build
  30:     0x73247840e7a8 - rustc_query_impl[a0c31ac015223081]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[a0c31ac015223081]::query_impl::mir_built::dynamic_query::{closure#2}::{closure#0}, rustc_middle[b97de266c643709b]::query::erase::Erased<[u8; 8usize]>>
  31:     0x7324781d08b1 - rustc_query_system[97bff28321f2bac]::query::plumbing::try_execute_query::<rustc_query_impl[a0c31ac015223081]::DynamicConfig<rustc_query_system[97bff28321f2bac]::query::caches::VecCache<rustc_span[ebc71fb0dc5af8f5]::def_id::LocalDefId, rustc_middle[b97de266c643709b]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[a0c31ac015223081]::plumbing::QueryCtxt, false>
  32:     0x7324781d048c - rustc_query_impl[a0c31ac015223081]::query_impl::mir_built::get_query_non_incr::__rust_end_short_backtrace
  33:     0x7324787cb348 - rustc_mir_transform[38567eaebfa221d1]::ffi_unwind_calls::has_ffi_unwind_calls
  34:     0x7324787cae57 - rustc_query_impl[a0c31ac015223081]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[a0c31ac015223081]::query_impl::has_ffi_unwind_calls::dynamic_query::{closure#2}::{closure#0}, rustc_middle[b97de266c643709b]::query::erase::Erased<[u8; 1usize]>>
  35:     0x7324787ca4f9 - rustc_query_system[97bff28321f2bac]::query::plumbing::try_execute_query::<rustc_query_impl[a0c31ac015223081]::DynamicConfig<rustc_query_system[97bff28321f2bac]::query::caches::VecCache<rustc_span[ebc71fb0dc5af8f5]::def_id::LocalDefId, rustc_middle[b97de266c643709b]::query::erase::Erased<[u8; 1usize]>>, false, false, false>, rustc_query_impl[a0c31ac015223081]::plumbing::QueryCtxt, false>
  36:     0x7324787ca195 - rustc_query_impl[a0c31ac015223081]::query_impl::has_ffi_unwind_calls::get_query_non_incr::__rust_end_short_backtrace
  37:     0x732475623973 - rustc_mir_transform[38567eaebfa221d1]::mir_promoted
  38:     0x732478298e1a - rustc_query_impl[a0c31ac015223081]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[a0c31ac015223081]::query_impl::mir_promoted::dynamic_query::{closure#2}::{closure#0}, rustc_middle[b97de266c643709b]::query::erase::Erased<[u8; 16usize]>>
  39:     0x7324782990db - rustc_query_system[97bff28321f2bac]::query::plumbing::try_execute_query::<rustc_query_impl[a0c31ac015223081]::DynamicConfig<rustc_query_system[97bff28321f2bac]::query::caches::VecCache<rustc_span[ebc71fb0dc5af8f5]::def_id::LocalDefId, rustc_middle[b97de266c643709b]::query::erase::Erased<[u8; 16usize]>>, false, false, false>, rustc_query_impl[a0c31ac015223081]::plumbing::QueryCtxt, false>
  40:     0x732478298d23 - rustc_query_impl[a0c31ac015223081]::query_impl::mir_promoted::get_query_non_incr::__rust_end_short_backtrace
  41:     0x7324781cea10 - rustc_borrowck[bf6c423544e45c9]::mir_borrowck
  42:     0x7324781ce957 - rustc_query_impl[a0c31ac015223081]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[a0c31ac015223081]::query_impl::mir_borrowck::dynamic_query::{closure#2}::{closure#0}, rustc_middle[b97de266c643709b]::query::erase::Erased<[u8; 8usize]>>
  43:     0x7324781d08b1 - rustc_query_system[97bff28321f2bac]::query::plumbing::try_execute_query::<rustc_query_impl[a0c31ac015223081]::DynamicConfig<rustc_query_system[97bff28321f2bac]::query::caches::VecCache<rustc_span[ebc71fb0dc5af8f5]::def_id::LocalDefId, rustc_middle[b97de266c643709b]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[a0c31ac015223081]::plumbing::QueryCtxt, false>
  44:     0x7324781d03cc - rustc_query_impl[a0c31ac015223081]::query_impl::mir_borrowck::get_query_non_incr::__rust_end_short_backtrace
  45:     0x7324784a6f1d - rustc_interface[c38f70925b3e6389]::passes::analysis
  46:     0x7324784a60c7 - rustc_query_impl[a0c31ac015223081]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[a0c31ac015223081]::query_impl::analysis::dynamic_query::{closure#2}::{closure#0}, rustc_middle[b97de266c643709b]::query::erase::Erased<[u8; 1usize]>>
  47:     0x732478da8f03 - rustc_query_system[97bff28321f2bac]::query::plumbing::try_execute_query::<rustc_query_impl[a0c31ac015223081]::DynamicConfig<rustc_query_system[97bff28321f2bac]::query::caches::SingleCache<rustc_middle[b97de266c643709b]::query::erase::Erased<[u8; 1usize]>>, false, false, false>, rustc_query_impl[a0c31ac015223081]::plumbing::QueryCtxt, false>
  48:     0x732478da8c7f - rustc_query_impl[a0c31ac015223081]::query_impl::analysis::get_query_non_incr::__rust_end_short_backtrace
  49:     0x732478c8c299 - rustc_interface[c38f70925b3e6389]::interface::run_compiler::<core[8cbc9b2d85f665a9]::result::Result<(), rustc_span[ebc71fb0dc5af8f5]::ErrorGuaranteed>, rustc_driver_impl[4b2f8406c0f6a8ac]::run_compiler::{closure#0}>::{closure#0}
  50:     0x732478d62bd9 - std[8986ecfb476bfa7d]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[c38f70925b3e6389]::util::run_in_thread_with_globals<rustc_interface[c38f70925b3e6389]::util::run_in_thread_pool_with_globals<rustc_interface[c38f70925b3e6389]::interface::run_compiler<core[8cbc9b2d85f665a9]::result::Result<(), rustc_span[ebc71fb0dc5af8f5]::ErrorGuaranteed>, rustc_driver_impl[4b2f8406c0f6a8ac]::run_compiler::{closure#0}>::{closure#0}, core[8cbc9b2d85f665a9]::result::Result<(), rustc_span[ebc71fb0dc5af8f5]::ErrorGuaranteed>>::{closure#0}, core[8cbc9b2d85f665a9]::result::Result<(), rustc_span[ebc71fb0dc5af8f5]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[8cbc9b2d85f665a9]::result::Result<(), rustc_span[ebc71fb0dc5af8f5]::ErrorGuaranteed>>
  51:     0x732478d62a06 - <<std[8986ecfb476bfa7d]::thread::Builder>::spawn_unchecked_<rustc_interface[c38f70925b3e6389]::util::run_in_thread_with_globals<rustc_interface[c38f70925b3e6389]::util::run_in_thread_pool_with_globals<rustc_interface[c38f70925b3e6389]::interface::run_compiler<core[8cbc9b2d85f665a9]::result::Result<(), rustc_span[ebc71fb0dc5af8f5]::ErrorGuaranteed>, rustc_driver_impl[4b2f8406c0f6a8ac]::run_compiler::{closure#0}>::{closure#0}, core[8cbc9b2d85f665a9]::result::Result<(), rustc_span[ebc71fb0dc5af8f5]::ErrorGuaranteed>>::{closure#0}, core[8cbc9b2d85f665a9]::result::Result<(), rustc_span[ebc71fb0dc5af8f5]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[8cbc9b2d85f665a9]::result::Result<(), rustc_span[ebc71fb0dc5af8f5]::ErrorGuaranteed>>::{closure#1} as core[8cbc9b2d85f665a9]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  52:     0x73247a22fa49 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h6dc9de06dfc501ab
                               at /rustc/35936c4839dd272646394779d151e060d0f6b3ac/library/alloc/src/boxed.rs:2015:9
  53:     0x73247a22fa49 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hc5bbd99ced815c6f
                               at /rustc/35936c4839dd272646394779d151e060d0f6b3ac/library/alloc/src/boxed.rs:2015:9
  54:     0x73247a22fa49 - std::sys::pal::unix::thread::Thread::new::thread_start::h0243db2ae6ac2b16
                               at /rustc/35936c4839dd272646394779d151e060d0f6b3ac/library/std/src/sys/pal/unix/thread.rs:108:17
  55:     0x732473aa955a - <unknown>
  56:     0x732473b26a3c - <unknown>
  57:                0x0 - <unknown>

error: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.79.0-nightly (35936c483 2024-03-25) running on x86_64-unknown-linux-gnu

query stack during panic:
#0 [thir_body] building THIR for `sse41_blend_noinline::{closure#0}::{closure#0}`
#1 [check_match] match-checking `sse41_blend_noinline::{closure#0}::{closure#0}`
#2 [mir_built] building MIR for `sse41_blend_noinline::{closure#0}::{closure#0}`
#3 [has_ffi_unwind_calls] checking if `sse41_blend_noinline::{closure#0}::{closure#0}` contains FFI-unwind calls
#4 [mir_promoted] promoting constants in MIR for `sse41_blend_noinline::{closure#0}::{closure#0}`
#5 [mir_borrowck] borrow-checking `sse41_blend_noinline::{closure#0}::{closure#0}`
#6 [analysis] running analysis passes on this crate
end of query stack
error: aborting due to 4 previous errors

Some errors have detailed explanations: E0425, E0601.
For more information about an error, try `rustc --explain E0425`.

```

</p>
</details>

### LINKED ISSUE #129150: ICE: `node_type: no type for node HirId(`
auto-reduced (treereduce-rust):
````rust
use std::arch::x86_64::{__m128, _mm_blend_ps};

pub fn arch() -> __m128 {
    let f = { |x, y| unsafe { _mm_blend_ps(x, y, { &const {} }) } };
    f(x, y)
}


````

original:
````rust
use std::arch::x86_64::{__m128, _mm_blend_ps};

pub fn arch( ) -> __m128 {
    let f = { |x, y| unsafe {
        _mm_blend_ps(x, y, { &const { InvariantRef::<'a>::NEW } })
    }};
    f(x, y)
}

````

Version information
````
rustc 1.82.0-nightly (d626fbdc6 2024-08-16)
binary: rustc
commit-hash: d626fbdc66d667dd5beefb9e43bd2798485f7a44
commit-date: 2024-08-16
host: x86_64-unknown-linux-gnu
release: 1.82.0-nightly
LLVM version: 19.1.0

````

Command:
`/home/matthias/.rustup/toolchains/master/bin/rustc -Zincremental-verify-ich=yes -Cincremental=<dir> -Cdebuginfo=2`

<details><summary><strong>Program output</strong></summary>
<p>

```
error[E0425]: cannot find value `x` in this scope
 --> /tmp/icemaker_global_tempdir.JBgDV4vgI7p6/rustc_testrunner_tmpdir_reporting.FndBZ8q46rCS/mvce.rs:5:7
  |
5 |     f(x, y)
  |       ^ help: a local variable with a similar name exists: `f`

error[E0425]: cannot find value `y` in this scope
 --> /tmp/icemaker_global_tempdir.JBgDV4vgI7p6/rustc_testrunner_tmpdir_reporting.FndBZ8q46rCS/mvce.rs:5:10
  |
5 |     f(x, y)
  |          ^ help: a local variable with a similar name exists: `f`

warning: unnecessary braces around function argument
 --> /tmp/icemaker_global_tempdir.JBgDV4vgI7p6/rustc_testrunner_tmpdir_reporting.FndBZ8q46rCS/mvce.rs:4:50
  |
4 |     let f = { |x, y| unsafe { _mm_blend_ps(x, y, { &const {} }) } };
  |                                                  ^^         ^^
  |
  = note: `#[warn(unused_braces)]` on by default
help: remove these braces
  |
4 -     let f = { |x, y| unsafe { _mm_blend_ps(x, y, { &const {} }) } };
4 +     let f = { |x, y| unsafe { _mm_blend_ps(x, y, &const {}) } };
  |

error[E0601]: `main` function not found in crate `mvce`
 --> /tmp/icemaker_global_tempdir.JBgDV4vgI7p6/rustc_testrunner_tmpdir_reporting.FndBZ8q46rCS/mvce.rs:6:2
  |
6 | }
  |  ^ consider adding a `main` function to `/tmp/icemaker_global_tempdir.JBgDV4vgI7p6/rustc_testrunner_tmpdir_reporting.FndBZ8q46rCS/mvce.rs`

error[E0308]: mismatched types
 --> /tmp/icemaker_global_tempdir.JBgDV4vgI7p6/rustc_testrunner_tmpdir_reporting.FndBZ8q46rCS/mvce.rs:4:52
  |
4 |     let f = { |x, y| unsafe { _mm_blend_ps(x, y, { &const {} }) } };
  |                                                    ^^^^^^^^^ expected `i32`, found `&()`

error: internal compiler error: compiler/rustc_middle/src/ty/typeck_results.rs:334:13: node_type: no type for node HirId(DefId(0:6 ~ mvce[3c83]::arch).15) (const `{}`)

thread 'rustc' panicked at compiler/rustc_middle/src/ty/typeck_results.rs:334:13:
Box<dyn Any>
stack backtrace:
   0:     0x7ac7ecfb54dd - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::hbcb9f5cf12b14f47
   1:     0x7ac7ed805297 - core::fmt::write::h10bda66e6bf714b2
   2:     0x7ac7ee7cfa91 - std::io::Write::write_fmt::haaf2df02fc383af3
   3:     0x7ac7ecfb7bbb - std::panicking::default_hook::{{closure}}::h103ad5f921545bf2
   4:     0x7ac7ecfb782e - std::panicking::default_hook::h699e6afa04bbf2d2
   5:     0x7ac7ec14c049 - std[8b2db094fc706015]::panicking::update_hook::<alloc[bb0f9e622dcbf0d]::boxed::Box<rustc_driver_impl[fd132fbcc7c8abf5]::install_ice_hook::{closure#0}>>::{closure#0}
   6:     0x7ac7ecfb84d7 - std::panicking::rust_panic_with_hook::h4b7c19967d3e4727
   7:     0x7ac7ec186211 - std[8b2db094fc706015]::panicking::begin_panic::<rustc_errors[b18244f215bb32e0]::ExplicitBug>::{closure#0}
   8:     0x7ac7ec1793f6 - std[8b2db094fc706015]::sys::backtrace::__rust_end_short_backtrace::<std[8b2db094fc706015]::panicking::begin_panic<rustc_errors[b18244f215bb32e0]::ExplicitBug>::{closure#0}, !>
   9:     0x7ac7ec1793a6 - std[8b2db094fc706015]::panicking::begin_panic::<rustc_errors[b18244f215bb32e0]::ExplicitBug>
  10:     0x7ac7ec18f391 - <rustc_errors[b18244f215bb32e0]::diagnostic::BugAbort as rustc_errors[b18244f215bb32e0]::diagnostic::EmissionGuarantee>::emit_producing_guarantee
  11:     0x7ac7ec751b84 - rustc_middle[83734a3cfd7912b4]::util::bug::opt_span_bug_fmt::<rustc_span[f1a14652fe04e1f9]::span_encoding::Span>::{closure#0}
  12:     0x7ac7ec737e6a - rustc_middle[83734a3cfd7912b4]::ty::context::tls::with_opt::<rustc_middle[83734a3cfd7912b4]::util::bug::opt_span_bug_fmt<rustc_span[f1a14652fe04e1f9]::span_encoding::Span>::{closure#0}, !>::{closure#0}
  13:     0x7ac7ec737d1b - rustc_middle[83734a3cfd7912b4]::ty::context::tls::with_context_opt::<rustc_middle[83734a3cfd7912b4]::ty::context::tls::with_opt<rustc_middle[83734a3cfd7912b4]::util::bug::opt_span_bug_fmt<rustc_span[f1a14652fe04e1f9]::span_encoding::Span>::{closure#0}, !>::{closure#0}, !>
  14:     0x7ac7ea21a100 - rustc_middle[83734a3cfd7912b4]::util::bug::bug_fmt
  15:     0x7ac7ee0052cb - rustc_mir_build[a568d047590b32ed]::thir::cx::thir_body
  16:     0x7ac7ee003592 - rustc_query_impl[ecaf2260d0180310]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[ecaf2260d0180310]::query_impl::thir_body::dynamic_query::{closure#2}::{closure#0}, rustc_middle[83734a3cfd7912b4]::query::erase::Erased<[u8; 16usize]>>
  17:     0x7ac7edc3111a - rustc_query_system[fa82f4068ff2e0d1]::query::plumbing::try_execute_query::<rustc_query_impl[ecaf2260d0180310]::DynamicConfig<rustc_query_system[fa82f4068ff2e0d1]::query::caches::VecCache<rustc_span[f1a14652fe04e1f9]::def_id::LocalDefId, rustc_middle[83734a3cfd7912b4]::query::erase::Erased<[u8; 16usize]>>, false, false, false>, rustc_query_impl[ecaf2260d0180310]::plumbing::QueryCtxt, true>
  18:     0x7ac7edc308d4 - rustc_query_impl[ecaf2260d0180310]::query_impl::thir_body::get_query_incr::__rust_end_short_backtrace
  19:     0x7ac7edff43a2 - rustc_mir_build[a568d047590b32ed]::thir::pattern::check_match::check_match
  20:     0x7ac7edff3b1b - rustc_query_impl[ecaf2260d0180310]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[ecaf2260d0180310]::query_impl::check_match::dynamic_query::{closure#2}::{closure#0}, rustc_middle[83734a3cfd7912b4]::query::erase::Erased<[u8; 1usize]>>
  21:     0x7ac7edbbbe53 - rustc_query_system[fa82f4068ff2e0d1]::query::plumbing::try_execute_query::<rustc_query_impl[ecaf2260d0180310]::DynamicConfig<rustc_query_system[fa82f4068ff2e0d1]::query::caches::VecCache<rustc_span[f1a14652fe04e1f9]::def_id::LocalDefId, rustc_middle[83734a3cfd7912b4]::query::erase::Erased<[u8; 1usize]>>, false, false, false>, rustc_query_impl[ecaf2260d0180310]::plumbing::QueryCtxt, true>
  22:     0x7ac7ed986701 - rustc_query_impl[ecaf2260d0180310]::query_impl::check_match::get_query_incr::__rust_end_short_backtrace
  23:     0x7ac7ee00a092 - rustc_mir_build[a568d047590b32ed]::build::mir_build
  24:     0x7ac7ee00974e - rustc_query_impl[ecaf2260d0180310]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[ecaf2260d0180310]::query_impl::mir_built::dynamic_query::{closure#2}::{closure#0}, rustc_middle[83734a3cfd7912b4]::query::erase::Erased<[u8; 8usize]>>
  25:     0x7ac7edabd20a - rustc_query_system[fa82f4068ff2e0d1]::query::plumbing::try_execute_query::<rustc_query_impl[ecaf2260d0180310]::DynamicConfig<rustc_query_system[fa82f4068ff2e0d1]::query::caches::VecCache<rustc_span[f1a14652fe04e1f9]::def_id::LocalDefId, rustc_middle[83734a3cfd7912b4]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[ecaf2260d0180310]::plumbing::QueryCtxt, true>
  26:     0x7ac7edbc7bdc - rustc_query_impl[ecaf2260d0180310]::query_impl::mir_built::get_query_incr::__rust_end_short_backtrace
  27:     0x7ac7ee0a61ed - rustc_mir_transform[d1eb952f32b25668]::mir_const_qualif
  28:     0x7ac7ee0a60f7 - rustc_query_impl[ecaf2260d0180310]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[ecaf2260d0180310]::query_impl::mir_const_qualif::dynamic_query::{closure#2}::{closure#0}, rustc_middle[83734a3cfd7912b4]::query::erase::Erased<[u8; 4usize]>>
  29:     0x7ac7ee0a4059 - rustc_query_system[fa82f4068ff2e0d1]::query::plumbing::try_execute_query::<rustc_query_impl[ecaf2260d0180310]::DynamicConfig<rustc_query_system[fa82f4068ff2e0d1]::query::caches::DefIdCache<rustc_middle[83734a3cfd7912b4]::query::erase::Erased<[u8; 4usize]>>, false, false, false>, rustc_query_impl[ecaf2260d0180310]::plumbing::QueryCtxt, true>
  30:     0x7ac7ee0a3a0a - rustc_query_impl[ecaf2260d0180310]::query_impl::mir_const_qualif::get_query_incr::__rust_end_short_backtrace
  31:     0x7ac7edff02da - rustc_mir_transform[d1eb952f32b25668]::mir_promoted
  32:     0x7ac7edfefc52 - rustc_query_impl[ecaf2260d0180310]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[ecaf2260d0180310]::query_impl::mir_promoted::dynamic_query::{closure#2}::{closure#0}, rustc_middle[83734a3cfd7912b4]::query::erase::Erased<[u8; 16usize]>>
  33:     0x7ac7edc3117b - rustc_query_system[fa82f4068ff2e0d1]::query::plumbing::try_execute_query::<rustc_query_impl[ecaf2260d0180310]::DynamicConfig<rustc_query_system[fa82f4068ff2e0d1]::query::caches::VecCache<rustc_span[f1a14652fe04e1f9]::def_id::LocalDefId, rustc_middle[83734a3cfd7912b4]::query::erase::Erased<[u8; 16usize]>>, false, false, false>, rustc_query_impl[ecaf2260d0180310]::plumbing::QueryCtxt, true>
  34:     0x7ac7edc307d4 - rustc_query_impl[ecaf2260d0180310]::query_impl::mir_promoted::get_query_incr::__rust_end_short_backtrace
  35:     0x7ac7ee928b93 - rustc_query_impl[ecaf2260d0180310]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[ecaf2260d0180310]::query_impl::mir_borrowck::dynamic_query::{closure#2}::{closure#0}, rustc_middle[83734a3cfd7912b4]::query::erase::Erased<[u8; 8usize]>>
  36:     0x7ac7edabd20a - rustc_query_system[fa82f4068ff2e0d1]::query::plumbing::try_execute_query::<rustc_query_impl[ecaf2260d0180310]::DynamicConfig<rustc_query_system[fa82f4068ff2e0d1]::query::caches::VecCache<rustc_span[f1a14652fe04e1f9]::def_id::LocalDefId, rustc_middle[83734a3cfd7912b4]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[ecaf2260d0180310]::plumbing::QueryCtxt, true>
  37:     0x7ac7edbc7f74 - rustc_query_impl[ecaf2260d0180310]::query_impl::mir_borrowck::get_query_incr::__rust_end_short_backtrace
  38:     0x7ac7ee274344 - rustc_interface[3c61e9c6fae1d8f5]::passes::run_required_analyses
  39:     0x7ac7ee34041e - rustc_interface[3c61e9c6fae1d8f5]::passes::analysis
  40:     0x7ac7ee3403f1 - rustc_query_impl[ecaf2260d0180310]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[ecaf2260d0180310]::query_impl::analysis::dynamic_query::{closure#2}::{closure#0}, rustc_middle[83734a3cfd7912b4]::query::erase::Erased<[u8; 1usize]>>
  41:     0x7ac7ee81724d - rustc_query_system[fa82f4068ff2e0d1]::query::plumbing::try_execute_query::<rustc_query_impl[ecaf2260d0180310]::DynamicConfig<rustc_query_system[fa82f4068ff2e0d1]::query::caches::SingleCache<rustc_middle[83734a3cfd7912b4]::query::erase::Erased<[u8; 1usize]>>, false, false, false>, rustc_query_impl[ecaf2260d0180310]::plumbing::QueryCtxt, true>
  42:     0x7ac7ee816efa - rustc_query_impl[ecaf2260d0180310]::query_impl::analysis::get_query_incr::__rust_end_short_backtrace
  43:     0x7ac7ee60062a - rustc_interface[3c61e9c6fae1d8f5]::interface::run_compiler::<core[5472d93c6cba957b]::result::Result<(), rustc_span[f1a14652fe04e1f9]::ErrorGuaranteed>, rustc_driver_impl[fd132fbcc7c8abf5]::run_compiler::{closure#0}>::{closure#1}
  44:     0x7ac7ee5d5d10 - std[8b2db094fc706015]::sys::backtrace::__rust_begin_short_backtrace::<rustc_interface[3c61e9c6fae1d8f5]::util::run_in_thread_with_globals<rustc_interface[3c61e9c6fae1d8f5]::util::run_in_thread_pool_with_globals<rustc_interface[3c61e9c6fae1d8f5]::interface::run_compiler<core[5472d93c6cba957b]::result::Result<(), rustc_span[f1a14652fe04e1f9]::ErrorGuaranteed>, rustc_driver_impl[fd132fbcc7c8abf5]::run_compiler::{closure#0}>::{closure#1}, core[5472d93c6cba957b]::result::Result<(), rustc_span[f1a14652fe04e1f9]::ErrorGuaranteed>>::{closure#0}, core[5472d93c6cba957b]::result::Result<(), rustc_span[f1a14652fe04e1f9]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[5472d93c6cba957b]::result::Result<(), rustc_span[f1a14652fe04e1f9]::ErrorGuaranteed>>
  45:     0x7ac7ee5d637a - <<std[8b2db094fc706015]::thread::Builder>::spawn_unchecked_<rustc_interface[3c61e9c6fae1d8f5]::util::run_in_thread_with_globals<rustc_interface[3c61e9c6fae1d8f5]::util::run_in_thread_pool_with_globals<rustc_interface[3c61e9c6fae1d8f5]::interface::run_compiler<core[5472d93c6cba957b]::result::Result<(), rustc_span[f1a14652fe04e1f9]::ErrorGuaranteed>, rustc_driver_impl[fd132fbcc7c8abf5]::run_compiler::{closure#0}>::{closure#1}, core[5472d93c6cba957b]::result::Result<(), rustc_span[f1a14652fe04e1f9]::ErrorGuaranteed>>::{closure#0}, core[5472d93c6cba957b]::result::Result<(), rustc_span[f1a14652fe04e1f9]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[5472d93c6cba957b]::result::Result<(), rustc_span[f1a14652fe04e1f9]::ErrorGuaranteed>>::{closure#1} as core[5472d93c6cba957b]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  46:     0x7ac7ee5d66eb - std::sys::pal::unix::thread::Thread::new::thread_start::h7504247ad105ec0b
  47:     0x7ac7efdc739d - <unknown>
  48:     0x7ac7efe4c49c - <unknown>
  49:                0x0 - <unknown>

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: please make sure that you have updated to the latest nightly

note: rustc 1.82.0-nightly (d626fbdc6 2024-08-16) running on x86_64-unknown-linux-gnu

note: compiler flags: -Z incremental-verify-ich=yes -C incremental=[REDACTED] -C debuginfo=2

query stack during panic:
#0 [thir_body] building THIR for `arch::{closure#0}::{constant#0}`
#1 [check_match] match-checking `arch::{closure#0}::{constant#0}`
end of query stack
error: aborting due to 5 previous errors; 1 warning emitted

Some errors have detailed explanations: E0308, E0425, E0601.
For more information about an error, try `rustc --explain E0308`.

```

</p>
</details>

### PR DESCRIPTION
**Pull request by veluca93**
r? BoxyUwU

Fixes #123077 
Fixes #129150

### CODE REVIEW

File: compiler/rustc_ast_lowering/src/expr.rs [hunk 1]
```diff
@@ -22,9 +24,28 @@ use super::errors::{
...
+impl<'v> rustc_ast::visit::Visitor<'v> for WillCreateDefIdsVisitor {
+    type Result = ControlFlow<()>;
+
+    fn visit_item(&mut self, _: &'v Item) -> Self::Result {
+        ControlFlow::Break(())
+    }
+
+    fn visit_expr(&mut self, ex: &'v Expr) -> Self::Result {
+        match ex.kind {
+            ExprKind::Gen(..) | ExprKind::ConstBlock(..) | ExprKind::Closure(..) => {
```
Comment (compiler-errors) [inline compiler/rustc_ast_lowering/src/expr.rs:41]: maybe break with the value of `ControlFlow<Span>` so you can point at the span of the closure/gen block/etc specifically, rather than the whole expr?

File: compiler/rustc_ast_lowering/src/expr.rs [hunk 2]
```diff
@@ -22,9 +24,28 @@ use super::errors::{
...
 };
-use crate::errors::YieldInClosure;
+use crate::errors::{InvalidLegacyConstGenericArg, YieldInClosure};
 use crate::{fluent_generated, FnDeclKind, ImplTraitPosition};
 
+struct WillCreateDefIdsVisitor {}
+
+impl<'v> rustc_ast::visit::Visitor<'v> for WillCreateDefIdsVisitor {
+    type Result = ControlFlow<()>;
+
```
Comment (BoxyUwU) [inline compiler/rustc_ast_lowering/src/expr.rs:34]: This wont find any const arguments such as `foo::<{ 1 + 2 }>()` which will also be parented wrong. You can use `visit_anon_const` to find those then we can try running crater and see how widespread defining defs in legacy const generic args is

Comment (veluca93) [reply compiler/rustc_ast_lowering/src/expr.rs:34]: Is this supposed to fail?
`std::arch::x86_64::_mm_blend_ps(loop {}, loop {}, foo::<3>());`

Comment (BoxyUwU) [reply compiler/rustc_ast_lowering/src/expr.rs:34]: Yeah, we desugar *every* const argument to an anon const right now

Comment (veluca93) [reply compiler/rustc_ast_lowering/src/expr.rs:34]: (FWIW neither `3` nor `1 + 2` appears to ICE)

Comment (BoxyUwU) [reply compiler/rustc_ast_lowering/src/expr.rs:34]: Yeah anon consts don't seem to ICE but they will still have incorrect def parenting, I think defining *items* also doesn't ICE but will have incorrect def parenting. It's possible we'll wind up wanting to future compat warn on the stuff that doesnt ICE and error on the stuff that *does*. Though I think at some point we'll want to be having hir checks that def parenting lines up with how the hir is structured in which case all of these would be ICEing ^^

**Comment by BoxyUwU** [comment]
@bors try
(pushing commits cancels the try run xd)

File: compiler/rustc_ast_lowering/messages.ftl [hunk 3]
```diff
@@ -103,6 +103,8 @@ ast_lowering_invalid_asm_template_modifier_reg_class =
 ast_lowering_invalid_asm_template_modifier_sym =
     asm template modifiers are not allowed for `sym` arguments
 
+ast_lowering_invalid_legacy_const_generic_arg =
+  invalid argument to a legacy const generic: cannot have const blocks, closures, async blocks or items
```
Comment (klensy) [inline compiler/rustc_ast_lowering/messages.ftl:107]: Should be 4 space indent?

**Comment by compiler-errors** [comment]
@craterbot check

**Comment by veluca93** [comment]
@rust-lang/lang this PR fixes some ICEs by making it a compilation error to pass too complex expressions as an argument of a legacy_const_generic function. In particular, it forbids all expressions that create a definition.

Context:
- legacy_const_generics is currently used in the stdlib for a few niche functions (mostly in `arch`, AFAIU).
- code that uses these const generics in simple ways is not affected; in particular, for the code to be affected one needs to have a type definition, closure or const generic argument inside the legacy_const_generic argument. The first two cases ICE today. The third case does *not*, and would be a potential source of new errors. Example: `std::arch::x86_64::_mm_blend_ps(loop {}, loop {}, foo::<3>());` works today but would fail to compile with this PR.
- all those functions can be called with the "regular" const generic syntax, and this PR has no effect on calls done that way. All code that uses the legacy syntax can be rewritten using the modern const generic syntax.
- people that know the compiler better than me say that supporting this kind of usage in the compiler would be very hard and would likely lead to more ICEs in the future.
- calling non-legacy_const_generics functions is not affected, and neither is passing const arguments with the regular `Foo<{ ... }>` or `bar::<{ ... }>()` syntax.

A crater run only shows spurious failures due to this change. The main question we have is whether to make this a hard error immediately, or to start by making it a future-compat warning.

**Comment by BoxyUwU** [comment]
> people that know the compiler better than me say that supporting this kind of usage in the compiler would be very hard and would likely lead to more ICEs in the future.

Specifically: it is not possible to support definitions in legacy const generic arguments having their parent definition be specified correctly in the compiler. This causes ICEs for nested bodies but affects *all* definitions inside of legacy const generic arguments and even though the other cases do not ICE right now I would expect future changes to the compiler to cause them to *start* ICEing and it would not be possible to fix.

**Comment by nikomatsakis** [comment]
Hi folks. We discussed this in the lang-team meeting today. To start, we are all assuming we will make this change, but we have a few questions we'd like answered first.

In particular, we were pretty unclear on what *exactly* is changing here. What would be ideal is some kind of write-up or characterization for the kinds of expressions *can* be used as the value for one of these arguments. Possible answers might be

* most conservative: literals and paths (named constants, associated constants)
* most accepting: anything that could appear as the tail expression of a `const { }` block

Can you characterize what is legal? I *suspect* virtually *any* of those characterizations would be fine, since I believe that the usages of this in the wild are expected to be very simple (tell me if you know otherwise), but I think either way we really want to know what we expect to be working (and to error cleanly on everything else).

Just so we don't forget, I'm tagging this as relnotes:

@rustbot label +relnotes

**Comment by BoxyUwU** [comment]
The `legacy_const_generics` feature allows defining functions with const generic parameters that are callable via normal function call syntax instead of the turbofish, for example:
```rust
#[rustc_legacy_const_generics(0)]
fn foo<const N: usize>() {}
```
can be called as `foo(10)` and is desugared to `foo::<10>()`. this function `foo` will be used in future examples in this comment.

*Before* this PR the rules for what is a valid argument for a legacy const generics parameter were the same as for regular const generics, specifically the argument must be either:
- A bare usage of a const parameter, e.g. `foo(N)` is legal but not `foo(N + 1)`
- Any arbitrary expression valid in a const context that does not make use of any generic parameters. e.g. `foo(1 + bar())` is legal but not `foo(1 + bar() + N)`

*After* this PR an additional restriction is introduced: The argument to a `rustc_legacy_const_generics` parameter must not contain an item definition, a nested body (such as a const block or closure), or any kind of argument to a const generic parameter.

This restriction *only* applies when using `foo(/* my expr */)` syntax *not* when using the explicit turbofish syntax `foo::<{ /* my expr */ }>`. Some concrete examples of what compiles before/after this PR:

| Code | Pre-PR  | Post-PR | Reason |
| ------------- | ------------- | ------------- | --------- |
| `foo(const { 10 })` | :white_check_mark:  |  :x:  | Defines a nested body (const block) |
| `foo::<{ const { 10 } }>()` | :white_check_mark: | :white_check_mark:  |  |
| `foo((\|\| 10)())` | :white_check_mark:  |  :x:  | Defines a nested body (closure) |
| `foo::<{ (\|\| 10)() }>()` | :white_check_mark: | :white_check_mark:  |
| `foo({ const N: usize = 10; N })`  | :white_check_mark: | :x: | Defines an item (const item) |
| `foo::<{ const N: usize = 10; N }>()`  | :white_check_mark: | :white_check_mark: |
| `foo(bar::<{ 10 }>())`  | :white_check_mark: | :x: | Contains an argument to a const generic parameter |
| `foo::<{ bar::<{ 10 }>() }>()`  | :white_check_mark: | :white_check_mark: | |

**Comment by traviscross** [comment]
@rfcbot fcp merge

**Comment by tmandry** [comment]
@rfcbot reviewed

**Comment by nikomatsakis** [comment]
@rfcbot reviewed

File: tests/ui/invalid/invalid-rustc_legacy_const_generics-issue-123077.rs [hunk 4]
```diff
@@ -0,0 +1,28 @@
...
+
+    std::arch::x86_64::_mm_blend_ps(loop {}, loop {}, &const {});
+    //~^ invalid argument to a legacy const generic
+
+    std::arch::x86_64::_mm_blend_ps(loop {}, loop {}, {
+        struct F();
+        //~^ invalid argument to a legacy const generic
+        1
+    });
+}
```
Comment (BoxyUwU) [inline tests/ui/invalid/invalid-rustc_legacy_const_generics-issue-123077.rs:28]: Can you add an example like:
```rust
// crate A

#![feature(rustc_attrs)]

#[rustc_legacy_const_generics(0, 1)]
fn foo<const N: usize, const M: usize>() {}

// crate B

fn main() {
    foo(12, (|| 10)());
}
```

to test the case where there are multiple `legacy_const_generic_parameter` arguments. In the example above ideally we would suggest removing *all* legacy const generic arguments and replacing them all with explicit const generic arguments

Comment (veluca93) [reply tests/ui/invalid/invalid-rustc_legacy_const_generics-issue-123077.rs:32]: Pushed a testcase using `std::arch::x86_64::_mm_inserti_si64`.

File: compiler/rustc_ast_lowering/messages.ftl [hunk 5]
```diff
@@ -103,6 +103,12 @@ ast_lowering_invalid_asm_template_modifier_reg_class =
 ast_lowering_invalid_asm_template_modifier_sym =
     asm template modifiers are not allowed for `sym` arguments
 
+ast_lowering_invalid_legacy_const_generic_arg =
+    invalid argument to a legacy const generic: cannot have const blocks, closures, async blocks or items
+
+ast_lowering_invalid_legacy_const_generic_arg_suggestion =
+    try using a const generic parameter instead
```
Comment (BoxyUwU) [inline compiler/rustc_ast_lowering/messages.ftl:110]:
```suggestion
    try using a const generic argument instead
```

File: compiler/rustc_ast_lowering/src/expr.rs [hunk 6]
```diff
@@ -410,7 +436,39 @@ impl<'hir> LoweringContext<'_, 'hir> {
                     self.create_def(parent_def_id, node_id, kw::Empty, DefKind::AnonConst, f.span);
                 }
 
-                let anon_const = AnonConst { id: node_id, value: arg };
+                let mut visitor = WillCreateDefIdsVisitor {};
+                let const_value = if let ControlFlow::Break(span) = visitor.visit_expr(&arg) {
+                    let mut const_args = vec![];
+                    let mut other_args = vec![];
+                    for (idx, arg) in args.iter().enumerate() {
```
Comment (BoxyUwU) [inline compiler/rustc_ast_lowering/src/expr.rs:443]: Can you move all this logic outside of the outer for loop. i.e. having two top level `for (idx, arg) in args.iter()` loops in this function. One that just finds all the spans needed to emit an error and then the existing loop (pre this PR) that is responsible for actually lowering the function call.

**Comment by veluca93** [comment]
> These commits modify the `Cargo.lock` file. Unintentional changes to `Cargo.lock` can be introduced when switching branches and rebasing PRs.
> 
> If this was unintentional then you should revert the changes before this PR is merged. Otherwise, you can ignore this comment.

That's from re-adding the pretty printer as a dep in rustc_ast_lowering.

File: compiler/rustc_ast_lowering/Cargo.toml [hunk 7]
```diff
@@ -9,6 +9,7 @@ doctest = false
 [dependencies]
 # tidy-alphabetical-start
 rustc_ast = { path = "../rustc_ast" }
+rustc_ast_pretty = { path = "../rustc_ast_pretty" }
```
Comment (RalfJung) [inline compiler/rustc_ast_lowering/Cargo.toml:12]: Was this already a transitive dep, or did this change reduce build parallelism?

Comment (veluca93) [reply compiler/rustc_ast_lowering/Cargo.toml:12]: It was a dep through rustc_errors (and it also was a direct dep ~10 days ago: https://github.com/rust-lang/rust/commit/b480f0f224b6e92a514a477516dd65d06b68f3cc)
