### PR TITLE
suggest lifetime for closure parameter type when mismatch

### LINKED ISSUE #105675: Confusing diagnostic complains about lifetimes in a closure, when parameter type is missing
1. Create a new project with `cargo new closure_lifetimes`
2. `cargo add pathfinding` (in my case, it used pathfinding version 4.0.0 or 4.0.1)
3. Replace main.rs with:

```rust
use std::collections::HashMap;
use pathfinding::prelude::bfs;

fn main() {
    // Just enough to satisfy the compiler
    let input = Input { ending_point: (3,4), heights: HashMap::new() };

    let success = |node| input.heights[node] == 0;
    let successors = |node| {
        let node_height = input.heights[node];
        input.neighbors(node).into_iter()
            .filter(|other| input.heights[&other] >= node_height - 1)
            .collect::<Vec<Coord>>()
    };
    let answer = bfs(&input.ending_point, successors, success).unwrap().len();
    println!("answer = {answer}");
}

type Coord = (i32, i32);

struct Input {
    ending_point: Coord,
    heights: HashMap<Coord, u32>
}

impl Input {
    // Just do something to satisfy the compiler
    fn neighbors(&self, node: &Coord) -> Vec<Coord> {
        vec![(node.0, node.1 + 1), (node.0 + 1, node.1)]
    }
}
```

`cargo check` produces the following output:

```
    Checking closure_lifetimes v0.1.0 (/Users/mark/sources/closure_lifetimes)
error[E0308]: mismatched types
  --> src/main.rs:15:18
   |
15 |     let answer = bfs(&input.ending_point, successors, success).unwrap().len();
   |                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ one type is more general than the other
   |
   = note: expected trait `for<'r> FnMut<(&'r (i32, i32),)>`
              found trait `FnMut<(&(i32, i32),)>`
note: this closure does not fulfill the lifetime requirements
  --> src/main.rs:9:22
   |
9  |     let successors = |node| {
   |                      ^^^^^^
note: the lifetime requirement is introduced here
  --> /Users/mark/.cargo/registry/src/github.com-1ecc6299db9ec823/pathfinding-4.0.1/src/directed/bfs.rs:69:9
   |
69 |     FN: FnMut(&N) -> IN,
   |         ^^^^^^^^^^^^^^^

error: implementation of `FnOnce` is not general enough
  --> src/main.rs:15:18
   |
15 |     let answer = bfs(&input.ending_point, successors, success).unwrap().len();
   |                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ implementation of `FnOnce` is not general enough
   |
   = note: closure with signature `fn(&'2 (i32, i32)) -> Vec<(i32, i32)>` must implement `FnOnce<(&'1 (i32, i32),)>`, for any lifetime `'1`...
   = note: ...but it actually implements `FnOnce<(&'2 (i32, i32),)>`, for some specific lifetime `'2`

error[E0308]: mismatched types
  --> src/main.rs:15:18
   |
15 |     let answer = bfs(&input.ending_point, successors, success).unwrap().len();
   |                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ one type is more general than the other
   |
   = note: expected trait `for<'r> FnMut<(&'r (i32, i32),)>`
              found trait `FnMut<(&(i32, i32),)>`
note: this closure does not fulfill the lifetime requirements
  --> src/main.rs:8:19
   |
8  |     let success = |node| input.heights[node] == 0;
   |                   ^^^^^^
note: the lifetime requirement is introduced here
  --> /Users/mark/.cargo/registry/src/github.com-1ecc6299db9ec823/pathfinding-4.0.1/src/directed/bfs.rs:71:9
   |
71 |     FS: FnMut(&N) -> bool,
   |         ^^^^^^^^^^^^^^^^^

error: implementation of `FnOnce` is not general enough
  --> src/main.rs:15:18
   |
15 |     let answer = bfs(&input.ending_point, successors, success).unwrap().len();
   |                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ implementation of `FnOnce` is not general enough
   |
   = note: closure with signature `fn(&'2 (i32, i32)) -> bool` must implement `FnOnce<(&'1 (i32, i32),)>`, for any lifetime `'1`...
   = note: ...but it actually implements `FnOnce<(&'2 (i32, i32),)>`, for some specific lifetime `'2`

For more information about this error, try `rustc --explain E0308`.
error: could not compile `closure_lifetimes` due to 4 previous errors
```

For the two closures (`success` and `successors`), if I add a type for the parameter by changing `|node|` to `|node: &Coord|`, it builds without any errors.  If it had told me that it needed type annotations, I would have understood the problem and been able to fix it right away.  (I assumed that there was enough type information for it to infer the correct types.)

The first confusing bit is that both errors highlight the entire call to `bfs()`, including all parameters.  This makes it harder to figure out which one it is complaining about (though the second note contains the line number).  Does the first argument have something to do with the lifetimes it is complaining about?

I found this part of the message hard to understand:

```
   = note: closure with signature `fn(&'2 (i32, i32)) -> Vec<(i32, i32)>` must implement `FnOnce<(&'1 (i32, i32),)>`, for any lifetime `'1`...
   = note: ...but it actually implements `FnOnce<(&'2 (i32, i32),)>`, for some specific lifetime `'2`
```

The type parameters look almost identical, and the `for some specific lifetime` didn't make sense to me.  Could it somehow indicate the bounds of that lifetime (2), or better explain why that lifetime doesn't last long enough?

FYI: found as part of solving Advent of Code 2022, Day 12.

### PR DESCRIPTION
**Pull request by skyzh**
<del>This is a draft PR, will add test cases later and be ready for review.</del>

This PR fixes https://github.com/rust-lang/rust/issues/105675 by adding a diagnostics suggestion. Also a partial fix to https://github.com/rust-lang/rust/issues/105528.

The following code will have a compile error now:

```
fn const_if_unit(input: bool) -> impl for<'a> FnOnce(&'a ()) -> usize {
    let x = |_| 1;
    x
}
```

Before this PR:

```
error[E0308]: mismatched types
 --> src/lib.rs:3:5
  |
3 |     x
  |     ^ one type is more general than the other
  |
  = note: expected trait `for<'a> FnOnce<(&'a (),)>`
             found trait `FnOnce<(&(),)>`
note: this closure does not fulfill the lifetime requirements
 --> src/lib.rs:2:13
  |
2 |     let x = |_| 1;
  |             ^^^

error: implementation of `FnOnce` is not general enough
 --> src/lib.rs:3:5
  |
3 |     x
  |     ^ implementation of `FnOnce` is not general enough
  |
  = note: closure with signature `fn(&'2 ()) -> usize` must implement `FnOnce<(&'1 (),)>`, for any lifetime `'1`...
  = note: ...but it actually implements `FnOnce<(&'2 (),)>`, for some specific lifetime `'2`

For more information about this error, try `rustc --explain E0308`.
error: could not compile `rust-test` due to 2 previous errors
```

After this PR:

```
error[E0308]: mismatched types
 --> src/lib.rs:3:5
  |
3 |     x
  |     ^ one type is more general than the other
  |
  = note: expected trait `for<'a> FnOnce<(&'a (),)>`
             found trait `FnOnce<(&(),)>`
note: this closure does not fulfill the lifetime requirements
 --> src/lib.rs:2:13
  |
2 |     let x = |_| 1;
  |             ^^^
help: consider changing the type of the closure parameters
  |
2 |     let x = |_: &_| 1;
  |             ~~~~~~~

error: implementation of `FnOnce` is not general enough
 --> src/lib.rs:3:5
  |
3 |     x
  |     ^ implementation of `FnOnce` is not general enough
  |
  = note: closure with signature `fn(&'2 ()) -> usize` must implement `FnOnce<(&'1 (),)>`, for any lifetime `'1`...
  = note: ...but it actually implements `FnOnce<(&'2 (),)>`, for some specific lifetime `'2`

For more information about this error, try `rustc --explain E0308`.
error: could not compile `rust-test` due to 2 previous errors
```

After applying the suggestion, it compiles. The suggestion might not always be correct as the generation procedure of that suggestion is quite simple...

### CODE REVIEW

**Comment by skyzh** [comment]
Originally I think we should fix this bug and make the original code compiles. But it seems that we will need to decide whether `_` is `for <'a>` or some specific lifetime in advance before going into the borrow checker. Therefore making a diagnostics suggestion might be a better fix... I guess?

**Comment by skyzh** [comment]
Test case updated. This suggestion may also fix some previous issues. e.g, for `src/test/ui/lifetimes/issue-79187-2.stderr`, the suggested fix actually works.

File: compiler/rustc_infer/src/infer/error_reporting/suggest.rs [hunk 1]
```diff
@@ -461,6 +461,64 @@ impl<'tcx> TypeErrCtxt<'_, 'tcx> {
...
+    /// of the parameters to accept all lifetimes.
+    pub(super) fn suggest_for_all_lifetime_closure(
+        &self,
+        span: Span,
+        exp_found: &ty::error::ExpectedFound<ty::PolyTraitRef<'tcx>>,
+        diag: &mut Diagnostic,
+    ) {
+        // 1. Get the substs of the closure.
+        // 2. Assume exp_found is FnOnce / FnMut / Fn, we can extract function parameters from [1].
+        let expected = exp_found.expected.try_map_bound(|x| x.substs.get(1).cloned().ok_or(()));
```
Comment (compiler-errors) [inline compiler/rustc_infer/src/infer/error_reporting/suggest.rs:475]: Can you use `map_bound` and [`transpose`](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_middle/ty/sty/struct.Binder.html#method.transpose) instead of `try_map_bound` and `ok_or`?

```suggestion
        let expected = exp_found.expected.map_bound(|x| x.substs.get(1)).transpose();
```

File: compiler/rustc_infer/src/infer/error_reporting/suggest.rs [hunk 2]
```diff
@@ -461,6 +461,64 @@ impl<'tcx> TypeErrCtxt<'_, 'tcx> {
...
+        let found = exp_found.found.try_map_bound(|x| x.substs.get(1).cloned().ok_or(()));
+
+        // 3. Extract the tuple type from Fn trait and suggest the change.
+        if let (Ok(expected), Ok(found)) = (expected, found) {
+            let expected = expected.skip_binder().unpack();
+            let found = found.skip_binder().unpack();
+            if let (GenericArgKind::Type(expected), GenericArgKind::Type(found)) = (expected, found)
+            {
+                if let (ty::Tuple(expected), ty::Tuple(found)) = (expected.kind(), found.kind())
```
Comment (compiler-errors) [inline compiler/rustc_infer/src/infer/error_reporting/suggest.rs:484]: Can you collapse these two nested `if` into one?

File: compiler/rustc_infer/src/infer/error_reporting/suggest.rs (hunk 1 above)
Comment (skyzh) [reply compiler/rustc_infer/src/infer/error_reporting/suggest.rs]: Fixed, thanks for the suggestion!

**Comment by apiraino** [comment]
I assume the last round of review is finished and the review flag can be switched. @skyzh  Feel free to request a review with `@rustbot ready`, thanks!

@rustbot author

File: compiler/rustc_infer/src/infer/error_reporting/suggest.rs [hunk 3]
```diff
@@ -461,6 +461,62 @@ impl<'tcx> TypeErrCtxt<'_, 'tcx> {
...
+    ) {
+        // 1. Get the substs of the closure.
+        // 2. Assume exp_found is FnOnce / FnMut / Fn, we can extract function parameters from [1].
+        let expected = exp_found.expected.map_bound(|x| x.substs.get(1).cloned()).transpose();
+        let found = exp_found.found.map_bound(|x| x.substs.get(1).cloned()).transpose();
+
+        // 3. Extract the tuple type from Fn trait and suggest the change.
+        if let (Some(expected), Some(found)) = (expected, found) {
+            let expected = expected.skip_binder().unpack();
+            let found = found.skip_binder().unpack();
```
Comment (compiler-errors) [inline compiler/rustc_infer/src/infer/error_reporting/suggest.rs:481]:
```suggestion
        let Some(expected) = exp_found.expected.skip_binder().substs.get(1) else { return; };
        let Some(found) = exp_found.found.skip_binder().substs.get(1) else { return; };

        // 3. Extract the tuple type from Fn trait and suggest the change.
```

(get rid of the `if` braces and indentation)

File: compiler/rustc_infer/src/infer/error_reporting/suggest.rs [hunk 4]
```diff
@@ -461,6 +461,62 @@ impl<'tcx> TypeErrCtxt<'_, 'tcx> {
...
+            if let (GenericArgKind::Type(expected), GenericArgKind::Type(found)) = (expected, found)
```
Comment (compiler-errors) [inline compiler/rustc_infer/src/infer/error_reporting/suggest.rs:482]: If you're gonna use let-chains here, can you split this `let (a, b) = (c, d)` into `let a = c && let b = d`? It's confusing to mix these.

File: compiler/rustc_infer/src/infer/error_reporting/suggest.rs [hunk 5]
```diff
@@ -461,6 +461,62 @@ impl<'tcx> TypeErrCtxt<'_, 'tcx> {
...
+                            // Otherwise, keep it as-is.
+                            suggestion += "_";
+                        }
+                    }
+                    suggestion += "|";
+
+                    if has_suggestion {
+                        diag.span_suggestion_verbose(
+                            span,
+                            "consider changing the type of the closure parameters",
```
Comment (compiler-errors) [inline compiler/rustc_infer/src/infer/error_reporting/suggest.rs:512]:
```suggestion
                            "consider specifying the type of the closure parameters",
```

File: compiler/rustc_infer/src/infer/error_reporting/suggest.rs [hunk 6]
```diff
@@ -461,6 +461,62 @@ impl<'tcx> TypeErrCtxt<'_, 'tcx> {
...
+                            is_first = true;
+                        } else {
+                            suggestion += ", ";
+                        }
+
+                        if let (ty::Ref(expected_region, _, _), ty::Ref(found_region, _, _)) = (expected.kind(), found.kind())
+                            && expected_region.is_late_bound() && !found_region.is_late_bound() {
+                            // If the expected region is late bound, and the found region is not, we can suggest adding `: &_`.
+                            // FIXME: use the actual type + variable name provided by user instead of `_`.
+                            suggestion += "_: &_";
```
Comment (compiler-errors) [inline compiler/rustc_infer/src/infer/error_reporting/suggest.rs:500]: Doesn't this totally overwrite the closure's argument names?

File: compiler/rustc_infer/src/infer/error_reporting/suggest.rs [hunk 7]
```diff
@@ -461,6 +461,62 @@ impl<'tcx> TypeErrCtxt<'_, 'tcx> {
             }
         }
     }
+
+    /// For "one type is more general than the other" errors on closures, suggest changing the lifetime
+    /// of the parameters to accept all lifetimes.
+    pub(super) fn suggest_for_all_lifetime_closure(
+        &self,
+        span: Span,
```
Comment (compiler-errors) [inline compiler/rustc_infer/src/infer/error_reporting/suggest.rs:469]: We probably need to pass the closure's HIR representation in as an argument instead of just using `def_span`, in order to make sure we have the right span (just the stuff in the args `|...|`) and to make sure we don't overwrite the arguments during suggestion.

File: compiler/rustc_infer/src/infer/error_reporting/suggest.rs (hunk 5 above)
Comment (compiler-errors) [reply compiler/rustc_infer/src/infer/error_reporting/suggest.rs:512]: We should only make the suggestion if the argument type is missing or `_`, I think.

**Review by compiler-errors — CHANGES_REQUESTED** [review]

**Comment by compiler-errors** [comment]
This needs a rebase. Marking this as waiting-on-author. Please use `@rustbot ready` to mark this as ready.

@rustbot author

**Comment by JohnCSimon** [comment]
@skyzh 

ping from triage - can you post your status on this PR? There hasn't been an update in a few months. Thanks!

FYI: when a PR is ready for review, send a message containing 
`@rustbot ready` to switch to `S-waiting-on-review` so the PR is in the reviewer's backlog.

File: tests/ui/lifetimes/issue-79187-2.stderr [hunk 8]
```diff
@@ -43,6 +43,10 @@ note: the lifetime requirement is introduced here
    |
 LL | fn take_foo(_: impl Foo) {}
    |                     ^^^
+help: consider specifying the type of the closure parameters
+   |
+LL |     take_foo(|a: &_| a);
```
Comment (skyzh) [inline tests/ui/lifetimes/issue-79187-2.stderr:48]: Is the `ty_span` assigned wrongly here? I believe it should be assigned to `impl Foo` instead of `a`. I can open another PR to fix this if this looks like a bug.

Comment (skyzh) [reply tests/ui/lifetimes/issue-79187-2.stderr:48]: ... so that we can produce diagnostics message like `a: &impl Foo`

**Comment by skyzh** [comment]
r? @compiler-errors

Thanks!

File: tests/ui/lifetimes/issue-79187-2.stderr (hunk 8 above)
Comment (compiler-errors) [reply tests/ui/lifetimes/issue-79187-2.stderr:48]: The span may be messed up because of the desugaring into a parameter :shrug:

**Review by compiler-errors — APPROVED** [review]
This may be messed up for polymorphic functions but good enough IMO :+1:

**Comment by Dylan-DPC** [comment]
@bors r-

failed in [rollup](https://github.com/rust-lang/rust/pull/110308#issuecomment-1507958748)

**Comment by skyzh** [comment]
@rustbot ready

Looks like a merge conflict 🙈 Fixed
