### PR TITLE
Clarify the doc for MaybeUninit::zeroed on incorrect use

### LINKED ISSUE #74343: Doc clarification for `MaybeUninit::zeroed()`
:wave: Hi! While reading the documentation for `MaybeUninit::zeroed()` I found it unclear whether using this method for a struct where `0` is an invalid bit pattern is correct usage or not.

The method description makes it clear that it is acceptable to use this method, only a user cannot assume that it is already valid.

> It depends on T whether that already makes for proper initialization.

https://doc.rust-lang.org/std/mem/union.MaybeUninit.html#method.zeroed

However, the example introduces some ambiguity.

> _Incorrect_ usage of this function: initializing a struct with zero, where some fields cannot hold 0 as a valid value.

This phrasing seems to suggest that you should *not* use `MaybeUninit::zeroed()` when 0 is not a valid bit pattern. However, I believe the intent is to merely to convey that calling `assume_init()` without otherwise initializing the value is invalid.

There are some valid use cases to zero the memory to prevent an accidental security issue from mis-initialization, even if the bit pattern is invalid.

Suggested alternate phrasing:
> _Incorrect_ usage of this function: assuming zero filled memory is initialized, where some fields cannot hold 0 as a valid value, without overwriting with a valid bit-pattern.

### PR DESCRIPTION
**Pull request by poliorcetics**
Fixes #74343.

@rustbot modify labels: C-enhancement, T-doc

### CODE REVIEW

File: library/core/src/mem/maybe_uninit.rs [hunk 1]
```diff
@@ -336,8 +336,9 @@ impl<T> MaybeUninit<T> {
     /// assert_eq!(x, (0, false));
     /// ```
     ///
-    /// *Incorrect* usage of this function: initializing a struct with zero, where some fields
-    /// cannot hold 0 as a valid value.
+    /// *Incorrect* usage of this function: assuming zero filled memory is initialized,
+    /// where some fields cannot hold 0 as a valid value, without overwriting with a
+    /// valid bit-pattern.
```
Comment (jyn514) [inline library/core/src/mem/maybe_uninit.rs:341]: This seems like a round about way to say 'calling `x.zeroed().assume_init()` when 0 is not a valid bit-pattern for the type'.

Comment (poliorcetics) [reply library/core/src/mem/maybe_uninit.rs]: Good catch, thanks !
