### PR TITLE
Make sure we handle `backwards_incompatible_lint` drops appropriately in drop elaboration

### LINKED ISSUE #134482: Double Drop with #![deny(rust_2024_compatibility)]
I had a custom Rc that was doubly freeing memory because Drop was being called more times than it should.
After a little bit of testing I think this is a small enough Minimal-Reproducible-Example:
[playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=4943de32dc0785a67a3f78b5ce9a478b)
```rust
// ---------------------------------------- //
// If commented, it only calls Drop 2 times //
// If not commented,  it calls Drop 3 times //
// ---------------------------------------- //
#![deny(rust_2024_compatibility)]

use std::backtrace::Backtrace;

struct Guard();
impl Clone for Guard {
    fn clone(&self) -> Self {
        Self()
    }
}
impl Drop for Guard {
    fn drop(&mut self) {
        println!("Drop!");
        eprintln!("Drop at {}!", Backtrace::force_capture());
    }
}

fn main() {
    let _ = method_1(Guard());
}

fn method_1(g: Guard) -> Result<String, ()> {
    // ----------------------- //
    // This calls Drop 2 times //
    // ----------------------- //

    // let argument = &g.clone();
    // match method_2(argument) {
    //     Ok(str) => Ok(str),
    //     Err(err) => Err(err),
    // }

    // --- //

    // ----------------------- //
    // This calls Drop 3 times //
    // ----------------------- //

    match method_2(&g.clone()) {
        Ok(str) => Ok(str),
        Err(err) => Err(err),
    }
}

fn method_2(_: &Guard) -> Result<String, ()> {
    panic!("Method 2 panics!");
}
```

I expected to see this happen: Drop is called twice.

Instead, this happened: Drop is called 3 times.

### Notes

* The return type doesn't need to be a `Result<String, ()>`
It seems that it happens as long as it is an enum in which one arm has a non-`Copy` type.
So it also happens if the return type is
```rust
enum CustomEnum {
    MyArm(Vec<u32>),
}
```
* The problems seems to happen regardless of the presence of the `--release` flag
* As seen in the backtrace below, the first drop is called at the end of the enum match, and the other two are called at the end of method_1

### Meta

`rustc --version --verbose`:
```
rustc 1.85.0-nightly (a4cb3c831 2024-12-17)
binary: rustc
commit-hash: a4cb3c831823d9baa56c3d90514b75b2660116fa
commit-date: 2024-12-17
host: x86_64-pc-windows-msvc
release: 1.85.0-nightly
LLVM version: 19.1.5
```

<details><summary>Backtrace</summary>
<p>
Reduced stderr from the playground:

```
     Running `target/debug/playground`
thread 'main' panicked at src/main.rs:51:5:
Method 2 panics!
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Drop at    0: <playground::Guard as core::ops::drop::Drop>::drop
             at ./src/main.rs:18:33
   1: core::ptr::drop_in_place<playground::Guard>
             at ./.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ptr/mod.rs:522:1
   2: playground::method_1
             at ./src/main.rs:46:5
   3: [...]

Drop at    0: <playground::Guard as core::ops::drop::Drop>::drop
             at ./src/main.rs:18:33
   1: core::ptr::drop_in_place<playground::Guard>
             at ./.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ptr/mod.rs:522:1
   2: playground::method_1
             at ./src/main.rs:47:1
   3: [...]

Drop at    0: <playground::Guard as core::ops::drop::Drop>::drop
             at ./src/main.rs:18:33
   1: core::ptr::drop_in_place<playground::Guard>
             at ./.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ptr/mod.rs:522:1
   2: playground::method_1
             at ./src/main.rs:47:1
   3: [...]
```

</p>
</details>

### PR DESCRIPTION
**Pull request by compiler-errors**
In #131326, a new kind of scheduled drop (`drop_kind: DropKind::Value` + `backwards_incompatible_lint: true`) was added so that we could insert a new kind of no-op MIR statement (`backward incompatible drop`) for linting purposes. 

These drops were intended to have *no side-effects*, but drop elaboration code forgot to handle these drops specially and they were handled otherwise as normal drops in most of the code. This ends up being **unsound** since we insert more than one drop call for some values, which means that `Drop::drop` could be called more than once.

This PR fixes this by splitting out the `DropKind::ForLint` and adjusting the code. I'm not totally certain if all of the places I've adjusted are either reachable or correct, but I'm pretty certain that it's *more* correct than it was previously.

cc @dingxiangfei2009 
r? nikomatsakis

Fixes #134482

### CODE REVIEW

File: compiler/rustc_mir_build/src/builder/scope.rs [hunk 1]
```diff
@@ -411,6 +405,27 @@ impl DropTree {
                     };
                     cfg.terminate(block, drop_node.data.source_info, terminator);
                 }
+                DropKind::ForLint => {
```
Comment (compiler-errors) [inline compiler/rustc_mir_build/src/builder/scope.rs:408]: I ended up adjusting this to act like `DropKind::Storage`, but inserting a `BackwardIncompatibleDropHint` instead of a `StorageDead`. Previously we'd insert a drop terminator here.

File: compiler/rustc_mir_build/src/builder/scope.rs [hunk 2]
```diff
@@ -822,6 +832,15 @@ impl<'a, 'tcx> Builder<'a, 'tcx> {
                         });
                         block = next;
                     }
+                    DropKind::ForLint => {
```
Comment (compiler-errors) [inline compiler/rustc_mir_build/src/builder/scope.rs:835]: Previously we were inserting a drop terminator for tail calls. Not certain if this is ever reachable, but it's more correct.

File: compiler/rustc_mir_build/src/builder/scope.rs [hunk 3]
```diff
@@ -1430,25 +1447,38 @@ fn build_scope_drops<'tcx>(
...
+            DropKind::ForLint => {
+                // If the operand has been moved, and we are not on an unwind
+                // path, then don't generate the drop. (We only take this into
+                // account for non-unwind paths so as not to disturb the
+                // caching mechanism.)
+                if scope.moved_locals.iter().any(|&o| o == local) {
+                    continue;
+                }
+
+                if storage_dead_on_unwind {
```
Comment (compiler-errors) [inline compiler/rustc_mir_build/src/builder/scope.rs:1469]: I'm not certain if we need to handle this unwind block here.

File: tests/mir-opt/tail_expr_drop_order_unwind.method_1.ElaborateDrops.after.panic-unwind.mir [hunk 4]
```diff
@@ -78,106 +75,85 @@ fn method_1(_1: Guard) -> () {
...
         goto -> bb12;
     }
 
-    bb28 (cleanup): {
-        _14 = discriminant(_2);
-        switchInt(move _14) -> [0: bb26, otherwise: bb27];
-    }
-
-    bb29 (cleanup): {
-        drop(_5) -> [return: bb16, unwind terminate(cleanup)];
```
Comment (compiler-errors) [inline tests/mir-opt/tail_expr_drop_order_unwind.method_1.ElaborateDrops.after.panic-unwind.mir]: notably, this is the drop terminator that is bad. previously we were unwinding to  bb14, which would drop `_5`, then which branched to bb15 -> bb30 which tested a drop flag for `_5` (which was never set to false), which branched to bb29 where we would drop `_5` yet again.

**Comment by ehuss** [comment]
@nikomatsakis I just want to make sure that you are aware of my comment in https://github.com/rust-lang/rust/issues/132861#issuecomment-2539960199. This approach of using MIR to implement the lint means that it does not work with `cargo fix --edition`, because `cargo check` does not run far enough to reach this. The only way for a user to see this is if they manually enable the lint and run a full build. I'm concerned that almost nobody will do that, making this ineffective.

I also want to make sure you are aware that there are significant false negatives with this lint (such as the basic example in https://github.com/rust-lang/rust/issues/132861#issuecomment-2492591937), even when doing a full build. That pattern unfortunately happens quite often due to the introduction of `unsafe_op_in_unsafe_fn` which adds a lot of inline `unsafe {…}` expressions.

**Comment by nikomatsakis** [comment]
Hmm! I'll check into that tomorrow morning. Also, doh, the dropck code was indeed an oversight on my part. I'm amazed that didn't trigger test failures! But I guess the drops are rarely inserted.

**Comment by lqd** [comment]
(https://github.com/rust-lang/rust/pull/131326 is on beta, nominating for backport)

File: compiler/rustc_mir_build/src/builder/scope.rs (hunk 1 above)
Comment (nikomatsakis) [reply compiler/rustc_mir_build/src/builder/scope.rs:408]: Makes sense.

**Review by nikomatsakis — APPROVED** [review]
r+

**Comment by wesleywiser** [comment]
@bors p=1

Fixes P-critical unsoundness in beta

**Comment by jieyouxu** [comment]
(btw @nikomatsakis, bors doesn't pick up r+ from review comments, only in regular comments)

**Comment by nikomatsakis** [comment]
@jieyouxu thanks! (I know that about bors, I was intentionally waiting to see that CI was good first...)

**Comment by apiraino** [comment]
beta backport approved on [Zulip](https://rust-lang.zulipchat.com/#narrow/channel/238009-t-compiler.2Fmeetings/topic/.5Bweekly.5D.202024-12-19/near/489984336)

@rustbot label +beta-accepted

**Comment by matthiaskrgr** [comment]
>Fixes P-critical unsoundness in beta
:thinking:  this pr is against the master branch

**Comment by compiler-errors** [comment]
@matthiaskrgr: It will get backported.

File: tests/mir-opt/tail_expr_drop_order_unwind.rs [hunk 5]
```diff
@@ -0,0 +1,36 @@
+// skip-filecheck
+// EMIT_MIR_FOR_EACH_PANIC_STRATEGY
+// EMIT_MIR tail_expr_drop_order_unwind.method_1.ElaborateDrops.after.mir
+
+#![deny(tail_expr_drop_order)]
+
+use std::backtrace::Backtrace;
```
Comment (Clipi-12) [inline tests/mir-opt/tail_expr_drop_order_unwind.rs:7]: This was probably unintentionally copy-pasted from [my mcve](https://github.com/rust-lang/rust/issues/134482)

Comment (compiler-errors) [reply tests/mir-opt/tail_expr_drop_order_unwind.rs:7]: lol ya, doesn't really matter bc i'm not gonna fix it now, and doesn't affect the test

**Comment by jieyouxu** [comment]
I'm not 100% certain, but the changes to the drop handling might be able to trigger an ICE related too

```
error: internal compiler error: compiler/rustc_mir_build/src/builder/scope.rs:1724:17: cannot unwind from goto -> bb198
```

cf. #134541.

**Comment by Clipi-12** [comment]
I'm not at home atm but earlier I tried to use nightly-2024-12-20 in the rust-toolchain file of the project from which I created the MCVE and it indeed ICEd
