### PR TITLE
Detect when move of !Copy value occurs within loop and should likely not be cloned

### LINKED ISSUE #92531: Confusing error message with moving a value within a nested for loop
I had code similar to the below (which is a minimal reproduction version of the original code), and its error was very confusing to me, enough so that I had to ask about what was wrong with it on the Rust discord, and even then it took a little while before anyone could get through to me what was even wrong.

Given the following code: <https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=c437992df178c2e794b09b37cc3b2ea3>

```rust
let foos = vec![String::from("hello"), String::from("world")];
let bars = vec!["world"];

let mut baz = vec![];
let mut qux = vec![];

for foo in foos {
    for bar in &bars {
        if foo == *bar {
            baz.push(foo);
            continue;
        }
    }
    
    qux.push(foo);
}
```

The current output is:

```
error[E0382]: borrow of moved value: `foo`
  --> src/main.rs:10:16
   |
8  |     for foo in foos {
   |         ---
   |         |
   |         this reinitialization might get skipped
   |         move occurs because `foo` has type `String`, which does not implement the `Copy` trait
9  |         for bar in &bars {
10 |             if foo == *bar {
   |                ^^^ value borrowed here after move
11 |                 baz.push(foo);
   |                          --- value moved here, in previous iteration of loop
```

The problem was that I meant to `continue` the outer loop, but I had forgotten that I was inside an inner loop. What made it all the more confusing is that it points to `foo` in the outer loop and says "this reinitialization might get skipped," which baffled me, because I couldn't ever imagine a loop variable *not* being reinitialized when the next iteration comes around.

So the combination of "value moved here, in previous iteration of loop" combined with "this reinitialization might get skipped" made no sense to me.

I'm not really sure how this could be improved, but the fact that there are two loops involved makes this diagnostic confusing in my opinion. It might make sense to detect that such a situation is going on and be more careful about the wording, by saying something like "in previous iteration of inner loop."

### LINKED ISSUE #121466: Rustc identifies use of moved value correctly in while let loop match correctly, but the suggested fix results in infinite loop.
### Code

```Rust
use futures::StreamExt;

#[tokio::main]
async fn main() {
        let vec = vec!["one", "two", "three"];
        while let Some(item) = futures::stream::iter(vec).next().await {
            println!("{:?}", item);
        }
}
```

### Current output

```Shell
Compiling playground v0.0.1 (/playground)
error[E0382]: use of moved value: `vec`
 --> src/lib.rs:6:54
  |
5 |         let vec = vec!["one", "two", "three"];
  |             --- move occurs because `vec` has type `Vec<&str>`, which does not implement the `Copy` trait
6 |         while let Some(item) = futures::stream::iter(vec).next().await {
  |         ---------------------------------------------^^^--------------
  |         |                                            |
  |         |                                            value moved here, in previous iteration of loop
  |         inside of this loop
  |
help: consider cloning the value if the performance cost is acceptable
  |
6 |         while let Some(item) = futures::stream::iter(vec.clone()).next().await {
  |                                                         ++++++++

For more information about this error, try `rustc --explain E0382`.
error: could not compile `playground` (lib) due to 1 previous error
```

### Desired output

```Shell
A slightly different example:


use futures::StreamExt;

#[tokio::main]
async fn main() {
        let vec = vec!["one", "two", "three"];
        while let item = futures::stream::iter(vec).next().await {
            println!("{:?}", item);
        }
}
```

produces an "irrefutable loop" warning at least

```
Standard Error
   Compiling playground v0.0.1 (/playground)
warning: irrefutable `while let` pattern
 --> src/lib.rs:6:15
  |
6 |         while let item = futures::stream::iter(vec).next().await {
  |               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: this pattern will always match, so the loop will never exit
  = help: consider instead using a `loop { ... }` with a `let` inside it
  = note: `#[warn(irrefutable_let_patterns)]` on by default

error[E0382]: use of moved value: `vec`
 --> src/lib.rs:6:48
  |
5 |         let vec = vec!["one", "two", "three"];
  |             --- move occurs because `vec` has type `Vec<&str>`, which does not implement the `Copy` trait
6 |         while let item = futures::stream::iter(vec).next().await {
  |         ---------------------------------------^^^--------------
  |         |                                      |
  |         |                                      value moved here, in previous iteration of loop
  |         inside of this loop
  |
help: consider cloning the value if the performance cost is acceptable
  |
6 |         while let item = futures::stream::iter(vec.clone()).next().await {
  |                                                   ++++++++

For more information about this error, try `rustc --explain E0382`.
warning: `playground` (lib) generated 1 warning
error: could not compile `playground` (lib) due to 1 previous error; 1 warning emitted
Standard Output
```

### Rationale and extra context

I'm a rust beginner: When I mistakenly wrote code matching `irrefutable_let_patterns` the warning was helpful to me that I had made a mistake. 

But I still had a flaw in that I should have made the stream outside the while let match stanza - The code is re-initializain the loop variable on each iteration. The rustc suggestion to add a `clone()` on `vec` as `vec` was moved in the previous loop iteration is "technically correct" but the suggestion creates another irrefutable loop which doesn't produce such a warning. I know this pattern is harder to recognize as it involves the r-value instead of the match side (`while let x =`). 

`while let Some(item) = futures::stream::iter(vec.clone()).next().await`

Since I'm a beginner I didn't realize that when rustc said `value moved here, in previous iteration of loop` that I had put use of `vec` in the wrong place. It should have been.

```
let mut s = futures::stream::iter(vec);
while let Some(item) = s.next().await {
...
```

While I ran into this when using an async stream, I think it a general situation whenever the right hand side creates a new and same object on the right side. Here's an example with an iterator along.

```
fn main() {
        let vec = vec!["one", "two", "three"];
        while let Some(item) = vec.iter().next() {
            println!("{:?}", item);
        }
}
```

It's a problem in the class of loop variable issues. I come from golang which says a similar issue that everone hits once or twice (and hopefully recognizes when!). Goland is introducing a way to systematically addres this class of error: https://go.dev/blog/loopvar-preview

I was encourage to report this by @carols10cents. 

### Other cases

_No response_

### Rust Version

```Shell
1.76.0 - I used the playground to reproduce it.
```

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by estebank**
When encountering a move error on a value within a loop of any kind,
identify if the moved value belongs to a call expression that should not
be cloned and avoid the semantically incorrect suggestion. Also try to
suggest moving the call expression outside of the loop instead.

```
error[E0382]: use of moved value: `vec`
  --> $DIR/recreating-value-in-loop-condition.rs:6:33
   |
LL |     let vec = vec!["one", "two", "three"];
   |         --- move occurs because `vec` has type `Vec<&str>`, which does not implement the `Copy` trait
LL |     while let Some(item) = iter(vec).next() {
   |     ----------------------------^^^--------
   |     |                           |
   |     |                           value moved here, in previous iteration of loop
   |     inside of this loop
   |
note: consider changing this parameter type in function `iter` to borrow instead if owning the value isn't necessary
  --> $DIR/recreating-value-in-loop-condition.rs:1:17
   |
LL | fn iter<T>(vec: Vec<T>) -> impl Iterator<Item = T> {
   |    ----         ^^^^^^ this parameter takes ownership of the value
   |    |
   |    in this function
help: consider moving the expression out of the loop so it is only moved once
   |
LL ~     let mut value = iter(vec);
LL ~     while let Some(item) = value.next() {
   |
```

We use the presence of a `break` in the loop that would be affected by
the moved value as a heuristic for "shouldn't be cloned".

Fix https://github.com/rust-lang/rust/issues/121466.

---

*Point at continue and break that might be in the wrong place*

Sometimes move errors are because of a misplaced `continue`, but we didn't
surface that anywhere. Now when there are more than one set of nested loops
we show them out and point at the `continue` and `break` expressions within
that might need to go elsewhere.

```
error[E0382]: use of moved value: `foo`
  --> $DIR/nested-loop-moved-value-wrong-continue.rs:46:18
   |
LL |     for foo in foos {
   |         ---
   |         |
   |         this reinitialization might get skipped
   |         move occurs because `foo` has type `String`, which does not implement the `Copy` trait
...
LL |         for bar in &bars {
   |         ---------------- inside of this loop
...
LL |                 baz.push(foo);
   |                          --- value moved here, in previous iteration of loop
...
LL |         qux.push(foo);
   |                  ^^^ value used here after move
   |
note: verify that your loop breaking logic is correct
  --> $DIR/nested-loop-moved-value-wrong-continue.rs:41:17
   |
LL |     for foo in foos {
   |     ---------------
...
LL |         for bar in &bars {
   |         ----------------
...
LL |                 continue;
   |                 ^^^^^^^^ this `continue` advances the loop at line 33
help: consider moving the expression out of the loop so it is only moved once
   |
LL ~         let mut value = baz.push(foo);
LL ~         for bar in &bars {
LL |
 ...
LL |             if foo == *bar {
LL ~                 value;
   |
help: consider cloning the value if the performance cost is acceptable
   |
LL |                 baz.push(foo.clone());
   |                             ++++++++
```

Fix https://github.com/rust-lang/rust/issues/92531.

### CODE REVIEW

**Comment by cjgillot** [comment]
I don't currently have the bandwidth to review this.
r? compiler

File: compiler/rustc_borrowck/src/diagnostics/conflict_errors.rs [hunk 1]
```diff
@@ -743,8 +743,166 @@ impl<'cx, 'tcx> MirBorrowckCtxt<'cx, 'tcx> {
...
+        }
+        can_suggest_clone
+    }
+
     fn suggest_cloning(&self, err: &mut Diag<'_>, ty: Ty<'tcx>, expr: &hir::Expr<'_>, span: Span) {
         let tcx = self.infcx.tcx;
+        if !self.suggest_hoisting_call_outside_loop(err, expr) {
+            // The place where the the type moves would be misleading to suggest clone. (#121466)
+            return;
+        }
```
Comment (Nadrieril) [inline compiler/rustc_borrowck/src/diagnostics/conflict_errors.rs:1001]: This is doing something different than what "suggest_cloning" suggests. Could you move the call to `suggest_hoisting_call_outside_loop` near the call site of `suggest_cloning`, or rename `suggest_cloning` to something like `suggest_cloning_or_hoisting`

File: compiler/rustc_borrowck/src/diagnostics/conflict_errors.rs [hunk 2]
```diff
@@ -743,8 +743,166 @@ impl<'cx, 'tcx> MirBorrowckCtxt<'cx, 'tcx> {
...
+        // The immediate HIR parent of the moved expression. We'll look for it to be a call.
+        let mut parent = None;
+        // The top-most loop where the moved expression could be moved to a new binding.
+        let mut outer_most_loop: Option<&hir::Expr<'_>> = None;
+        for (_, node) in tcx.hir().parent_iter(expr.hir_id) {
+            let e = match node {
+                hir::Node::Expr(e) => e,
+                hir::Node::Local(hir::Local { els: Some(els), .. }) => {
+                    let mut finder = BreakFinder { found_break: false };
```
Comment (Nadrieril) [inline compiler/rustc_borrowck/src/diagnostics/conflict_errors.rs]: You use `BreakFinder` here but declare it below, that confused me for a second; could you move its declaration next to the other `Finder`?

File: compiler/rustc_borrowck/src/diagnostics/conflict_errors.rs [hunk 3]
```diff
@@ -743,8 +743,166 @@ impl<'cx, 'tcx> MirBorrowckCtxt<'cx, 'tcx> {
...
+        {
+            // FIXME: We could check that the call's *parent* takes `&mut val` to make the
+            // suggestion more targeted to the `mk_iter(val).next()` case. Maybe do that only to
+            // check for wheter to suggest `let value` or `let mut value`.
+
+            let span = in_loop.span;
+            let mut finder = BreakFinder { found_break: false };
+            finder.visit_expr(in_loop);
+            let sm = tcx.sess.source_map();
+            if (finder.found_break || true)
```
Comment (Nadrieril) [inline compiler/rustc_borrowck/src/diagnostics/conflict_errors.rs]: I presume the `|| true` was for testing?
```suggestion
            if finder.found_break
```

File: compiler/rustc_borrowck/src/diagnostics/conflict_errors.rs [hunk 4]
```diff
@@ -743,8 +743,166 @@ impl<'cx, 'tcx> MirBorrowckCtxt<'cx, 'tcx> {
...
+                            kind: hir::ExprKind::If(cond, ..), ..
+                        }) => {
+                            let mut finder = Finder { hir_id: expr.hir_id, found: false };
+                            finder.visit_expr(cond);
+                            if finder.found {
+                                // The expression where the move error happened is in a `while let`
+                                // condition Don't suggest clone as it will likely end in an
+                                // infinite loop.
+                                // while let Some(_) = foo(non_copy.clone()) { }
+                                // ---------                       ^^^^^^^^
```
Comment (Nadrieril) [inline compiler/rustc_borrowck/src/diagnostics/conflict_errors.rs:836]: Let me check that I follow here: we found a parent of `expr` that's an `if let`, and we know `expr` is in the condition of the `if` (as opposed as being in one of the arms). How do we deduce that this `if` is the condition of a `while` loop?

File: tests/ui/moves/recreating-value-in-loop-condition.rs [hunk 5]
```diff
@@ -0,0 +1,57 @@
+fn iter<T>(vec: Vec<T>) -> impl Iterator<Item = T> {
+    vec.into_iter()
+}
+fn foo() {
+    let vec = vec!["one", "two", "three"];
+    while let Some(item) = iter(vec).next() { //~ ERROR use of moved value
+        println!("{:?}", item);
+    }
+}
```
Comment (Nadrieril) [inline tests/ui/moves/recreating-value-in-loop-condition.rs:9]: Could you add the appropriate `//~ HELP` lines as well? You can probably inline `iter()` to avoid the "consider changing this parameter to borrow" suggestion

File: compiler/rustc_borrowck/src/diagnostics/conflict_errors.rs [hunk 6]
```diff
@@ -846,51 +846,148 @@ impl<'cx, 'tcx> MirBorrowckCtxt<'cx, 'tcx> {
...
+                    }
+                    _ => None,
+                })
+                .collect();
+            // It is possible that a user written `break` or `continue` is in the wrong place. We
+            // point them out at the user for them to make a determination. (#92531)
+            if !spans.is_empty() && loop_count > 1 {
+                // Getting fancy: if the spans of the loops *do not* overlap, we only use the line
+                // number when referring to them. If there *are* overlaps (multiple loops on the
+                // same line) then we use the more verbose span output (`file.rs:col:ll`).
```
Comment (Nadrieril) [inline compiler/rustc_borrowck/src/diagnostics/conflict_errors.rs:913]: :exploding_head: nice

File: compiler/rustc_borrowck/src/diagnostics/conflict_errors.rs (hunk 3 above)
Comment (Nadrieril) [reply compiler/rustc_borrowck/src/diagnostics/conflict_errors.rs]: I see you removed it in the next commit

**Comment by Nadrieril** [comment]
Cool stuff! I don't completely follow the "look for breaks" heuristic but I'll trust you on that. A few comments but looks good overall.

File: tests/ui/moves/recreating-value-in-loop-condition.rs (hunk 5 above)
Comment (estebank) [reply tests/ui/moves/recreating-value-in-loop-condition.rs:9]: > You can probably inline iter() to avoid the "consider changing this parameter to borrow" suggestion

If I do that the error *doesn't* happen, with a logic error because then the iterator gets recreated on every loop iteration, turning it into an infinite loop.

File: compiler/rustc_borrowck/src/diagnostics/conflict_errors.rs (hunk 4 above)
Comment (estebank) [reply compiler/rustc_borrowck/src/diagnostics/conflict_errors.rs:836]: We don't care that it is a `while` loop specifically, because we also want the following case to trigger:

```rust
fn qux() {
    let vec = vec!["one", "two", "three"];
    loop {
        if let Some(item) = iter(vec).next() { //~ ERROR use of moved value
            println!("{:?}", item);
            break;
        }
    }
}
```

We could check that the `if let` comes from a desugaring to only trigger on `while let`, if we had concerns about the general case.

File: tests/ui/moves/recreating-value-in-loop-condition.rs (hunk 5 above)
Comment (Nadrieril) [reply tests/ui/moves/recreating-value-in-loop-condition.rs]: The error does happen on `while let Some(item) = vec.into_iter().next()`, is that not what we're testing?

Comment (Nadrieril) [reply tests/ui/moves/recreating-value-in-loop-condition.rs]: Ah, I was worried you'd have to add a bunch of `NOTE`s because of `iter()` but apparently not so all's good

**Comment by Nadrieril** [comment]
Nice work, ty

@bors r+
