### PR TITLE
LLVM 4.0 Upgrade

### LINKED ISSUE #37609: Upgrade to LLVM 4.0
The AVR-Rust post continues to track AVR-LLVM, which is tracking upstream LLVM. That means we are running into changes from the future LLVM 4.0. I figured we could open up this issue now to track the changes required to stay compatible. 

This is the current list of upgrade hazards. Note that some of the text may be nonsensical as I don't truly grok all the internals of LLVM so some changes are wild stabs in the dark. It's also possible that some failed fix for earlier problems actually caused later problems:

- [x] DIDescriptorFlags became a real C++ enum and not a bitset (#37857)
- [x] An EH personality is required for every function that can unwind (#37862)
- [x] `AlwaysInliner` pass changed header and constructor name (#37861)
- [x] `createBasicType` changed API (#38317)
- [x] Bitcode/ReaderWriter.h has been renamed / API changed (#38156)
- [x] [`powidf2` / `powisf2` calling convention changed](https://github.com/rust-lang/rust/issues/37609#issuecomment-261109814) ([LLVM 31685](https://llvm.org/bugs/show_bug.cgi?id=31685))
- [x] `llvm::AttrBuilder` changed API (#37831)
- [x] `DIBuilder::createNameSpace` changed API (#38000)
- [x] `LLVMRustPrintPasses` prefers `StringRef` over `char *` (#38027)
- [x] `OptimizationDiagnostic` string type changes (#37982)
- [x] `llvm::StringRef` is not guaranteed to be null terminated (#38048)
- [x] `getPassName` changed return types (#38195)
- [x] Archive support changed error handling types (#38196)
- [x] Teach Rust about an LLVM 4.0 API change for creating debug info
for global variables (#38295)
- [x] Check all errors in LLVMRustArchiveIterator API (#38676)
- [x] Upgrade emscripten (kripken/emscripten-fastcomp#165, kripken/emscripten-fastcomp-clang#13)
- [x] Alignment now represented with 32 bits instead of 64 (#39529)
- [x] `DIBuilder::createGlobalVariable` API changed again (#39528)
- [x] `llvm::DIBuilder::createCompileUnit` now takes an `llvm::DIFile*` instead of a `Filename` and `Directory` (#39747)
- [ ] Symbol lookup error when linking dylibs (#39782)
- [x] Undefined behavior in `repr(packed)` tests (#40373)
- [ ] Unoptimised builds of compiler_builtins on ARM have references to `core::panicking::panic` (#40508)

----

A WIP PR that performs the upgrade!  #40123

-----

Some issues whose resolution is believed to be blocked on LLVM 4.0:

- [ ] https://github.com/rust-lang/rust/issues/39015

### PR DESCRIPTION
**Pull request by TimNN**
Since nobody has done this yet, I decided to get things started:

**Todo:**

* [x] push the relevant commits to `rust-lang/llvm` and `rust-lang/compiler-rt`
* [x] cleanup `.gitmodules`
* [x] Verify if there are any other commits from `rust-lang/llvm` which need backporting
* [x] Investigate / fix debuginfo ("`<optimized out>`") failures
* [x] Use correct emscripten version in docker image

---

Closes #37609.

---

**Test results:**

Everything is green 🎉

### CODE REVIEW

**Comment by alexcrichton** [comment]
@TimNN you can probably work faster than going through @bors by selectively adding `ALLOW_PR=1` to various entries in `.travis.yml`, that'll run the tests on the PR itself before we hit @bors.

I'd recommend doing that for a couple of the cross targets at least and then probably some of the other builders as well (such as emscripten)

My guess is that AppVeyor will be one of the most difficult pieces to update as part of this upgrade. Unfortunately we don't have any extra capacity there for running tests so it may be difficult to do so on the PR before bors :(

**Comment by TimNN** [comment]
The debuginfo failures all occur because `static mut`s are optimized out. (I verified that no optimisation flags were passed to rustc.

I'm unsure what the best fix would be here (something like the `#[used]` attribute from #39987 would probably work).

**Comment by rkruppe** [comment]
`static mut`s getting optimized out sounds like an issue with the IR/debug info we generate. Perhaps one of the debug info-related changes was incomplete and we don't emit everything we need to emit for globals? To clarify, does this:

> `static mut`s are optimized out

mean that gdb outputs `<optimized out>`, or did you check the object files and the symbols for the globals were missing?

In any case, requiring `#[used]` on `static mut`s to enable debugging would be a serious regression, not to mention that `#[used]` doesn't exist yet and I'm not even sure it would fix this (see above).

**Comment by petrochenkov** [comment]
I vaguely remember about statics being optimized away the last summer already, when I wrote debuginfo tests for unions (one of the failing tests in this PR).
So I had to add at least an [assignment](https://github.com/rust-lang/rust/blob/master/src/test/debuginfo/union-smoke.rs#L48) for the static to be kept.
Maybe the LLVM optimizer become better and now sees that the optimization is still possible?

**Comment by TimNN** [comment]
> To clarify, does this:
>
> > static muts are optimized out
> 
> mean that gdb outputs `<optimized out>`, or did you check the object files and the symbols for the globals were missing?

It means that gdb prints `<optimized out>`

Apparently I made some assumptions that weren't quite correct.

The symbols exist (output of `nm` from the `simple-struct` test:

```
0000000000201008 d _ZN13simple_struct13NO_PADDING_1617h8f8e1027ea816fe7E
000000000020100c d _ZN13simple_struct13NO_PADDING_3217h9e367c36ef03eabcE
0000000000201018 d _ZN13simple_struct13NO_PADDING_6417h3c4e19994ee55915E
0000000000201050 d _ZN13simple_struct14PADDING_AT_END17h210f8219dd75f271E
0000000000201040 d _ZN13simple_struct16INTERNAL_PADDING17he308dba4866e981bE
0000000000201030 d _ZN13simple_struct17NO_PADDING_16326417h136d93d95c4cf5b5E
```

Since this is apparently indeed debuginfo related I guess cc @michaelwoerister, @dylanmckay

**Comment by TimNN** [comment]
The generated IR, in case that helps anyone: https://gist.github.com/TimNN/92152a2f8062909805657d1bb4131998

**Comment by TimNN** [comment]
The failed build of the `IMAGE=cross` seems to be qemu related, one of the failed tests:

```
---- [run-pass] run-pass/alignment-gep-tup-like-1.rs stdout ----
	
error: test run failed!
status: exit code: 101
command: /checkout/obj/build/x86_64-unknown-linux-gnu/stage0-tools/x86_64-unknown-linux-gnu/release/qemu-test-client run /checkout/obj/build/x86_64-unknown-linux-gnu/test/run-pass/alignment-gep-tup-like-1.stage2-arm-unknown-linux-gnueabihf
stdout:
------------------------------------------
uploaded "/checkout/obj/build/x86_64-unknown-linux-gnu/test/run-pass/alignment-gep-tup-like-1.stage2-arm-unknown-linux-gnueabihf", waiting for result
a=22 b=44

------------------------------------------
stderr:
------------------------------------------
thread 'main' panicked at 'client.read_exact(&mut header) failed with failed to fill whole buffer', /checkout/src/tools/qemu-test-client/src/main.rs:174
note: Run with `RUST_BACKTRACE=1` for a backtrace.

------------------------------------------

thread '[run-pass] run-pass/alignment-gep-tup-like-1.rs' panicked at 'explicit panic', /checkout/src/tools/compiletest/src/runtest.rs:2637
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

I saw the following panics:

```
     61 thread 'main' panicked at 'client.read_exact(&mut header) failed with Connection reset by peer (os error 104)', /checkout/src/tools/qemu-test-client/src/main.rs:174
      3 thread 'main' panicked at 'client.read_exact(&mut header) failed with failed to fill whole buffer', /checkout/src/tools/qemu-test-client/src/main.rs:174
      1 thread 'main' panicked at 'io::copy(&mut file, dst) failed I/O failure during tests: Error { repr: Os { code: 11, message: "Resource temporarily unavailable" } }
     96 thread 'main' panicked at 'io::copy(&mut file, dst) failed with Broken pipe (os error 32)', /checkout/src/tools/qemu-test-client/src/main.rs:220
      1 thread 'main' panicked at 'io::copy(&mut file, dst) failed with Connection reset by peer (os error 104)', /checkout/src/tools/qemu-test-client/src/main.rs:220
```

Do they ring a bell for anyone?

**Comment by TimNN** [comment]
The `emscripten` failure are mainly of the kind `Invalid record (Producer: 'LLVM4.0.0' Reader: 'LLVM 3.9.0')`, although there are some assertion failures as well. (I would fix the llvm version mismatch first, maybe that fixes the assertion failures as well).

**Comment by TimNN** [comment]
The android image fails with an LLVM assertion:

```
rustc: /checkout/src/llvm/lib/Target/ARM/ARMConstantIslandPass.cpp:492: void {anonymous}::ARMConstantIslands::doInitialConstPlacement(std::vector<llvm::MachineInstr*>&): Assertion `Size >= 4 && "Too small constant pool entry"' failed.
Build failed, waiting for other jobs to finish...
rustc: /checkout/src/llvm/lib/Target/ARM/ARMConstantIslandPass.cpp:492: void {anonymous}::ARMConstantIslands::doInitialConstPlacement(std::vector<llvm::MachineInstr*>&): Assertion `Size >= 4 && "Too small constant pool entry"' failed.
error: Could not compile `core`.
```

There are also some warnings (see below for an example), of which I am unsure how relevant / important they are.

```
warning: ../compiler-rt/lib/builtins/mulsc3.c:21:1: warning: conflicting types for built-in function '__mulsc3'
warning:  __mulsc3(float __a, float __b, float __c, float __d)
warning:  ^
```

**Comment by alexcrichton** [comment]
@TimNN the former may be a bug in LLVM? (or just something we've never exposed ourselves before). The latter is normal, I believe it's happening on builds today.

**Comment by alexcrichton** [comment]
Oh we've also got ~10 extra capacity on Travis so feel free to test more than one row at a time if you'd like :)

**Comment by TimNN** [comment]
@alexcrichton: Have you ever seen something like the qemu failures in https://github.com/rust-lang/rust/pull/40123#issuecomment-282828575 before?

> Oh we've also got ~10 extra capacity on Travis so feel free to test more than one row at a time if you'd like :)

Ah, ok. I've been doing 3 at a time (when not debugging emscripten), but I guess I can run a few more :)

**Comment by TimNN** [comment]
The `dist-s390x-linux-netbsd` build fails while cross compiling llvm due to missing `std::thread` support:

```
In file included from /checkout/src/llvm/include/llvm/Support/ThreadPool.h:17:0,
                 from /checkout/src/llvm/lib/Support/ThreadPool.cpp:14:
/checkout/src/llvm/include/llvm/Support/thread.h:41:14: error: 'thread' in namespace 'std' does not name a type
 typedef std::thread thread;
```

I guess the fix here is to backport https://github.com/rust-lang/llvm/commit/58731be9e1da9dd14100ea8e99119ec9fc7d770d as well.

**Comment by TimNN** [comment]
I've been investigating the emscripten failures:

**`run-pass/packed-struct-vec.rs`** [IR](https://gist.github.com/49b1f374071614a98aa4936794f33265):

The `#[repr(packed)]` seems to be just broken, printing instead of asserting for equality gives the following results:

```
Foo { bar: 2, baz: 2 }, Foo { bar: 1, baz: 33649522 }
Foo { bar: 0, baz: 2 }, Foo { bar: 1, baz: 33649522 }
Foo { bar: 0, baz: 2 }, Foo { bar: 1, baz: 33649522 }
Foo { bar: 1, baz: 2 }, Foo { bar: 1, baz: 33649522 }
Foo { bar: 2, baz: 2 }, Foo { bar: 1, baz: 33649522 }
Foo { bar: 0, baz: 2 }, Foo { bar: 1, baz: 33649522 }
Foo { bar: 0, baz: 2 }, Foo { bar: 1, baz: 33649522 }
Foo { bar: 1, baz: 2 }, Foo { bar: 1, baz: 33649522 }
Foo { bar: 2, baz: 2 }, Foo { bar: 1, baz: 33649522 }
Foo { bar: 0, baz: 2 }, Foo { bar: 1, baz: 33649522 }
Foo { bar: 0, baz: 144115188075855872 }, Foo { bar: 1, baz: 33649522 }
Foo { bar: 0, baz: 562949953421312 }, Foo { bar: 1, baz: 33649522 }
Foo { bar: 0, baz: 0 }, Foo { bar: 1, baz: 33649522 }
Foo { bar: 2, baz: 2 }, Foo { bar: 1, baz: 33649522 }
Foo { bar: 0, baz: 144115188075855872 }, Foo { bar: 1, baz: 33649522 }
Foo { bar: 0, baz: 562949953421312 }, Foo { bar: 1, baz: 33649522 }
Foo { bar: 0, baz: 0 }, Foo { bar: 1, baz: 33649522 }
Foo { bar: 2, baz: 2 }, Foo { bar: 1, baz: 33649522 }
Foo { bar: 0, baz: 144115188075855872 }, Foo { bar: 1, baz: 33649522 }
Foo { bar: 0, baz: 0 }, Foo { bar: 1, baz: 33649522 }
```

(with this code:)

```rust
use std::mem;

#[repr(packed)]
#[derive(Copy, Clone, PartialEq, Debug)]
struct Foo {
    bar: u8,
    baz: u64
}

pub fn main() {
    let foos = [Foo { bar: 1, baz: 2 }; 10];

    assert_eq!(mem::size_of::<[Foo; 10]>(), 90);

    for i in 0..10 {
        println!("{:?}, {:?}", foos[i], Foo { bar: 1, baz: 2});
    }

    for &foo in &foos {
        println!("{:?}, {:?}", foo, Foo { bar: 1, baz: 2 });
    }

    assert!(false);
}
```

**Comment by alexcrichton** [comment]
@TimNN 

The QEMU failures don't look familiar but are perhaps indicative of the program segfaulting or otherwise exiting un-cleanly. Do you have the full logs I could help take a look at?

The missing `std::thread` business may be related to how we compile compilers. It may be that one of our compilers is too old or something like that. I know that MinGW C++ compilers, at least, do not have `std::thread` (at least if I'm remembering correctly). Historically we've "dealt" with this by just deleting code that uses `std::thread`, but it's clearly getting harder over time! This also isn't scalable into the future really. Unfortunately I don't know of a great solution here.

**Comment by alexcrichton** [comment]
Fascinating! Unfortunately I may not be of much help. Also thanks for the links, I should have looked around for them! Of the failures so far:

* armhf - this is really suspicious. In theory if qemu-test-server panics in any way we'd see it in the logs (as it doesn't daemonize that much or anything), but I'm not seeing anything. The errors mean that the server is prematurely closing the connection, but I'm not sure how that's possible without otherwise printing error information! It *may* be a bug in LLVM or related to the assertion failures, but it may also require more debugging the qemu instance itself :(

* emscripten - looks like you're on top of these (maybe fastcomp regressions? maybe llvm regression? unsure myself...)

* android - yeah looks like an LLVM bug? Although I wouldn't rule out invalid codegen on our side just yet.

* s390x-netbsd - Ok so this specifically failed to compiled LLVM for NetBSD. [This is our script to compile NetBSD gcc](https://github.com/rust-lang/rust/blob/master/src/ci/docker/dist-s390x-linux-netbsd/build-netbsd-toolchain.sh) and I don't see anything immediately wrong that should compile the wrong C++. I wonder if the gcc options accidentally disable `std::thread`? Or maybe it's disabled somewhere else on NetBSD by default? Not sure why that happened :(

Some other tips I'd have is:

* You can run docker images locally via `./src/ci/docker/run.sh $image_name` which can help with debugging (e.g. avoiding going through Travis). That should in theory use the precise same environment as Travis modulo kernel and hardware.

* For suspected LLVM bugs the best way (although certainly not the fastest way) that I know to work with them is to (a) get it to reproduce with a manual rustc invocation then (b) get it to reproduce with an `opt` invocation by using rustc to generate LLVM IR then switching to LLVM's tools and then (c) minimizing that IR as much as possible. If it's small enough then reporting a bug on LLVM's issue tracker is usually good for getting the issue fixed in a timely fashion.

**Comment by TimNN** [comment]
> * You can run docker images locally via ./src/ci/docker/run.sh $image_name which can help with debugging (e.g. avoiding going through Travis). That should in theory use the precise same environment as Travis modulo kernel and hardware.

Yeah, I'm doing that right now :)

> s390x-netbsd

Alright, so the problem is, I think, that the following `./configure` check fails when compiling: `checking for gthreads library... no`

**Comment by alexcrichton** [comment]
@TimNN heh yeah that'd do it! I wonder if some more headers need to be copied from the NetBSD base system or something like that? Unfortunately I forget now at this point where I got those instructions from to build a NetBSD cross-compiler...

**Comment by mattico** [comment]
Those warnings aren't new. I forget the cause.

**Comment by TimNN** [comment]
Some notes on the `armhf-gnu` image:

* I (once) got the same LLVM assertion as on android, this went away when retrying the build. I'll try to get this to reliably reproduce.
* The qemu connection errors happen non deterministically, as far as I can tell, example: `run-pass` ran successfully, `incremental` failed afterwards, after a retry all of`run-pass` failed.

**Comment by alexcrichton** [comment]
Odd! I wouldn't entirely rule out a bug in qemu-test-{client,server} FWIW

**Comment by TimNN** [comment]
First of all a small progress update: Of the 25 Docker based builds, 16 build without problems, 2 required (small) fixes, 2 timed out on travis but succeeded locally and 5 are currently broken. I'll investigate the broken images over the next days when I have the time.

---

Some notes on the android failure:

The `arm-android` image causes an llvm assertion:

```
rustc: /checkout/src/llvm/lib/Target/ARM/ARMConstantIslandPass.cpp:492: void {anonymous}::ARMConstantIslands::doInitialConstPlacement(std::vector<llvm::MachineInstr*>&): Assertion `Size >= 4 && "Too small constant pool entry"' failed.
```

This happens while compiling the `coretest` crate:

```
"/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc" "--crate-name" "coretest" "/checkout/src/libcore/../libcoretest/lib.rs" "-C" "opt-level=2" "--test" "-C" "metadata=84b5aaef553ce96c" "-C" "extra-filename=-84b5aaef553ce96c" "--out-dir" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2-std/arm-linux-androideabi/release/deps" "--emit=dep-info,link" "--target" "arm-linux-androideabi" "-L" "dependency=/checkout/obj/build/x86_64-unknown-linux-gnu/stage2-std/arm-linux-androideabi/release/deps" "-L" "dependency=/checkout/obj/build/x86_64-unknown-linux-gnu/stage2-std/release/deps" "--extern" "core=/checkout/obj/build/x86_64-unknown-linux-gnu/stage2-std/arm-linux-androideabi/release/deps/libcore-cd0ca85e71f914ca.rlib" "--cfg" "stage2" "--sysroot" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2" "-Cprefer-dynamic" "-C" "debug-assertions=n"
```

While running llvm passes, full backtrace:

```
#0  0x00007ffff736d7ef in raise () from /lib/x86_64-linux-gnu/libc.so.6
#1  0x00007ffff736f3ea in abort () from /lib/x86_64-linux-gnu/libc.so.6
#2  0x00007ffff7365bb7 in ?? () from /lib/x86_64-linux-gnu/libc.so.6
#3  0x00007ffff7365c62 in __assert_fail () from /lib/x86_64-linux-gnu/libc.so.6
#4  0x00007ffff15c300e in (anonymous namespace)::ARMConstantIslands::doInitialConstPlacement(std::vector<llvm::MachineInstr*, std::allocator<llvm::MachineInstr*> >&) [clone .constprop.328] () from /home/logic/build-tmp/rust-src/obj/arm-android/build/x86_64-unknown-linux-gnu/stage2/bin/../lib/../lib/librustc_llvm-7c760c0d87163cbb.so
#5  0x00007ffff15c8908 in (anonymous namespace)::ARMConstantIslands::runOnMachineFunction(llvm::MachineFunction&) ()
   from /home/logic/build-tmp/rust-src/obj/arm-android/build/x86_64-unknown-linux-gnu/stage2/bin/../lib/../lib/librustc_llvm-7c760c0d87163cbb.so
#6  0x00007ffff1bb8ac5 in llvm::MachineFunctionPass::runOnFunction(llvm::Function&) ()
   from /home/logic/build-tmp/rust-src/obj/arm-android/build/x86_64-unknown-linux-gnu/stage2/bin/../lib/../lib/librustc_llvm-7c760c0d87163cbb.so
#7  0x00007ffff2458c13 in llvm::FPPassManager::runOnFunction(llvm::Function&) ()
   from /home/logic/build-tmp/rust-src/obj/arm-android/build/x86_64-unknown-linux-gnu/stage2/bin/../lib/../lib/librustc_llvm-7c760c0d87163cbb.so
#8  0x00007ffff2458cdc in llvm::FPPassManager::runOnModule(llvm::Module&) ()
   from /home/logic/build-tmp/rust-src/obj/arm-android/build/x86_64-unknown-linux-gnu/stage2/bin/../lib/../lib/librustc_llvm-7c760c0d87163cbb.so
#9  0x00007ffff245877d in llvm::legacy::PassManagerImpl::run(llvm::Module&) ()
   from /home/logic/build-tmp/rust-src/obj/arm-android/build/x86_64-unknown-linux-gnu/stage2/bin/../lib/../lib/librustc_llvm-7c760c0d87163cbb.so
#10 0x00007ffff0d69903 in LLVMRustWriteOutputFile ()
   from /home/logic/build-tmp/rust-src/obj/arm-android/build/x86_64-unknown-linux-gnu/stage2/bin/../lib/../lib/librustc_llvm-7c760c0d87163cbb.so
#11 0x00007ffff606d834 in rustc_trans::back::write::write_output_file::h713482cdaa178321 ()
   from /home/logic/build-tmp/rust-src/obj/arm-android/build/x86_64-unknown-linux-gnu/stage2/bin/../lib/../lib/librustc_trans-efa094249cef739c.so
#12 0x00007ffff606fd3f in rustc_trans::back::write::optimize_and_codegen::_$u7b$$u7b$closure$u7d$$u7d$::h1b757de20fba8b9a ()
   from /home/logic/build-tmp/rust-src/obj/arm-android/build/x86_64-unknown-linux-gnu/stage2/bin/../lib/../lib/librustc_trans-efa094249cef739c.so
#13 0x00007ffff6074c26 in rustc_trans::back::write::execute_work_item::hbc7cd39d8cd88c44 ()
   from /home/logic/build-tmp/rust-src/obj/arm-android/build/x86_64-unknown-linux-gnu/stage2/bin/../lib/../lib/librustc_trans-efa094249cef739c.so
#14 0x00007ffff607167a in rustc_trans::back::write::run_passes::h7cf08f2c47729966 ()
   from /home/logic/build-tmp/rust-src/obj/arm-android/build/x86_64-unknown-linux-gnu/stage2/bin/../lib/../lib/librustc_trans-efa094249cef739c.so
#15 0x00007ffff7b52353 in rustc_driver::driver::phase_5_run_llvm_passes::h7c9bbedc8969c4b3 ()
   from /home/logic/build-tmp/rust-src/obj/arm-android/build/x86_64-unknown-linux-gnu/stage2/bin/../lib/librustc_driver-b65378ba5ffb99d4.so
#16 0x00007ffff7b18aa4 in rustc_driver::driver::compile_input::hf3e3aa4173908b86 ()
   from /home/logic/build-tmp/rust-src/obj/arm-android/build/x86_64-unknown-linux-gnu/stage2/bin/../lib/librustc_driver-b65378ba5ffb99d4.so
#17 0x00007ffff7b646d6 in rustc_driver::run_compiler::h8f8d47f1d258a8a6 ()
   from /home/logic/build-tmp/rust-src/obj/arm-android/build/x86_64-unknown-linux-gnu/stage2/bin/../lib/librustc_driver-b65378ba5ffb99d4.so
#18 0x00007ffff7a84115 in std::panicking::try::do_call::h206b9daee04f4ea2 ()
   from /home/logic/build-tmp/rust-src/obj/arm-android/build/x86_64-unknown-linux-gnu/stage2/bin/../lib/librustc_driver-b65378ba5ffb99d4.so
#19 0x00007ffff77a8077 in __rust_maybe_catch_panic ()
   from /home/logic/build-tmp/rust-src/obj/arm-android/build/x86_64-unknown-linux-gnu/stage2/bin/../lib/libstd-9a66b6a343d52844.so
#20 0x00007ffff7aa0e62 in _$LT$F$u20$as$u20$alloc..boxed..FnBox$LT$A$GT$$GT$::call_box::h5d196fbb3229f499 ()
   from /home/logic/build-tmp/rust-src/obj/arm-android/build/x86_64-unknown-linux-gnu/stage2/bin/../lib/librustc_driver-b65378ba5ffb99d4.so
#21 0x00007ffff779d248 in std::sys::imp::thread::Thread::new::thread_start::h2c901daa88f3cb32 ()
   from /home/logic/build-tmp/rust-src/obj/arm-android/build/x86_64-unknown-linux-gnu/stage2/bin/../lib/libstd-9a66b6a343d52844.so
#22 0x00007fffeefda6ca in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#23 0x00007ffff74400af in clone () from /lib/x86_64-linux-gnu/libc.so.6
```

I will attempt to build llvm / rustc with debug info tomorrow to get some more information on what is going on.

**Comment by alexcrichton** [comment]
@TimNN FWIW timing out on travis may be fixed by re-running. If travis has a cold cache for both the docker image *and* LLVM it's likely to fail, but with sccache you'll likely cache LLVM the first time so the second build will have it cached (just a guess). If it passes locally though I'd be pretty confident that it'll pass on Travis.

Also thank you so much again for taking this on!

**Comment by TimNN** [comment]
I have (somewhat) minified the android assertion, compiling the generated llvm IR with `llc` triggers the same assertion. The assertion only triggers when compiling with optimizations. IR and the minified example: https://gist.github.com/52fcea6426c872869269114c47f96e1f

**Comment by TimNN** [comment]
Bugpoint minified IR: https://gist.github.com/fa2cdcabaa481d619277d1c2ea9d04b4

**Comment by alexcrichton** [comment]
Nice! Want to submit that upstream?

**Comment by TimNN** [comment]
Yeah, I'll just try to reproduce with an official llvm 4.0 build first.

**Comment by TimNN** [comment]
Upstream bug: https://bugs.llvm.org/show_bug.cgi?id=32130

**Comment by TimNN** [comment]
I've been investigating the volatile emscripten failure a bit: It appears that the `write_volatile` (or the reading during verification) is miss optimized, see https://gist.github.com/TimNN/a43fc1376888e1d39ea5e9b93c099478 for the rust source, compilation options as well as optimized and unoptimized IR.

cc @kripken -- maybe you could take a look? The IR is sadly not freestanding (and depends on some rust libraries) but maybe you can see something anyway? I'm not sure how to debug this further -- if you have something I should try / do feel free to ping me here or on irc.

**Comment by kripken** [comment]
@TimNN: looks like the [ExpandStructRegs](https://github.com/kripken/emscripten-fastcomp/blob/next-merge/lib/Target/JSBackend/NaCl/ExpandStructRegs.cpp) pass is doing something wrong. It translates a bunch of `insertvalue`s + a `store volatile` of their result into a bunch of `store volatile`s of `undef`. So it's losing the actual data, and only 0s will be stored.

That pass is originally from NaCl, and I'm not that familiar with its internals. So first thing that could help is to know if this is a new pattern of IR being generated? Is this a new test in 4.0, or is Rust in 4.0 generating something it didn't use to?

In particular, the relevant type here is `%E = type { [32 x i64] }`, that's what that pass is trying to legalize. Perhaps the pass can't handle arrays inside structs.

**Comment by kripken** [comment]
Here's a [before and after](https://gist.github.com/kripken/838b51dd22a23417ce8b04823da6fc70) of the important part. The `store volatile i64 undef`s are what is wrong in the after.

**Comment by TimNN** [comment]
> So first thing that could help is to know if this is a new pattern of IR being generated? Is this a new test in 4.0, or is Rust in 4.0 generating something it didn't use to?

The test is not new and the generated IR is exactly the same before and after the llvm upgrade. So it is my believe that something in LLVM / emscripten changed for 4.0 causing this failure (although I don't currently have a way to test that).

**Comment by TimNN** [comment]
Another note: Things work fine if the array is not wrapped in a struct, see https://gist.github.com/TimNN/419a598a0c5795dc2a83657ae684539f for source code and IR.

**Comment by kripken** [comment]
Ok, if it's the same IR as before, then either LLVM is optimizing it differently, or emscripten is compiling it differently. Running `opt -O3` on the unoptimized ll from your gist results in the same output in both LLVM versions (well, minus a new `nonnull` attr). And running emscripten on that gives me the same results as well. However, when I `opt -O3` your unoptimized code, I don't get the same optimized code - so perhaps the optimization flags matter. How are you generating the optimized code?

**Comment by TimNN** [comment]
>  Running `opt -O3` on the **unoptimized** ll from your gist results in the same output in both LLVM versions

> However, when I `opt -O3` your **unoptimized** code, I don't get the same optimized code

I guess one of those should be **optimized**? (Which one?)

> How are you generating the optimized code?

The optimized code is generated using `opt -S -O1 vol.ll -o vol-opt.ll`

**Comment by TimNN** [comment]
By the way -- I don't need to run `opt` again, just compiling the `-opt.ll` files with `emcc` (`-O0`) is enough to trigger the bad code. See https://gist.github.com/TimNN/76ca254f3ad4105dd83d39721a02e118 for the complete emcc command.

**Comment by kripken** [comment]
No typo, both of those were meant to be "unoptimized". What I see is that starting from your unoptimized IR, I end up with bad results in old llvm+emscripten as well as new.

Ok, looking at `-O1` now, I also see both old and new llvm+emscripten emit the same bad code (with tiny unrelated differences like the new `nonnull` stuff). So the issue seems to be that if this test worked in the past, it had different unoptimized input IR to begin with.

**Comment by kripken** [comment]
And yes, wrapping an array in a struct seems to be the issue - so if older rust didn't do that wrapping, it could explain this. (But not assign blame, of course, the problem is in that legalization pass, not rust.)

**Comment by TimNN** [comment]
> No typo, both of those were meant to be "unoptimized". 

Ah, I originally misunderstood what you were saying.

Interesting. I'll be building a full rustc + LLVM 3.9 now and run that test manually, to see what happens.

**Comment by TimNN** [comment]
Alright, **manually** running the test on rust with llvm 3.9 **does** fais as well... Now to find out why this is not picked up during normal testing... / occurs in my update builds.

**Comment by TimNN** [comment]
So the mystery why the test passes with rustc + llvm 4.0 is solved, consider the following table and that rust compiles tests with `-O2`:

Results of the test case with different LLVM version / optimization levels (the `-O` flag was given directly to `rustc`):

|       | LLVM 3.9 | LLVM 4.0 |
|-------|----------|----------|
| `-O0` | ok       | ok       |
| `-O1` | fail     | fail     |
| `-O2` | **ok**   | **fail** |
| `-O3` | ok       | fail     |

I'm unsure how this relates to your observation that the generated IR is the same for LLVM 3.9 / 4.0 however this at least explains why the test passes on rust pre 4.0.

I have uploaded some more IR at https://gist.github.com/86c800a71b4654912626ad6e13105d90:

* the `llvm-X.X` prefix specifies the llvm used to generate the IR.
* the `-rust-OX` files where generated directly using `rustc -Copt-level=X --emit=llvm-ir -o *.ll`
* the `-opt-OX` files where generated from the `-O0` rust IR: `opt -S -OX *-rust-O0.ll -o *.ll`

**Comment by kripken** [comment]
Ok, likely what's going on is that emscripten updated llvm since last rust did, and I am using that newer llvm in between the old one and the new one for this PR, since on current emscripten, `-O2` fails on 3.9 as well from those IRs, while it doesn't for you with that older llvm. Which indicates that something in the llvm optimizer changed in that first range - likely more aggressive used of insertelement etc.

In any case, the result is almost certainly that that legalization pass needs to be fixed. Does that block this PR? Might be worth just disabling that test for now if it's the last thing.

**Comment by TimNN** [comment]
> Does that block this PR? 

Not (yet), there are still some other things which need to be fixed. Among them is one other emscripten failure (related to packed structs, I think), however I have not yet had the time to investigate that.

Thanks a lot for the help so far!

By the way, rust uses the 1.37.1 tag of emscripten IIRC, however I don't know which exact llvm version is used by rust itself.

**Comment by pftbest** [comment]
Rust is using llvm revision 282753. It is somewhere between 3.9 and 3.9.1 release.

**Comment by TimNN** [comment]
So the second emscripten failure is actually due to #27060 I believe: `rustc` emits loads to unaligned pointers (to contents of a `#[repr(packed)]` struct) without marking them as unaligned. The test passed previously when compiled with `-O2` (which is what the test runner uses) put not with `-O0`.

Here is a small sample program which demonstrates the problem (with `-O0`):

```rust
#[repr(packed)]
struct Foo {
    _bar: u8,
    baz: u64
}

pub fn main() {
    let foo = Foo { _bar: 1, baz: 2 };

    if *&foo.baz != 2 {
        ::std::process::exit(1);
    }

    ::std::process::exit(0);
}
```

IR:

```ll
; ModuleID = 'p.cgu-0.rs'
source_filename = "p.cgu-0.rs"
target datalayout = "e-p:32:32-i64:64-v128:32:128-n32-S128"
target triple = "asmjs-unknown-emscripten"

%Foo = type <{ i8, i64 }>

define internal void @_ZN1p4main17h5a74305885b4a113E() unnamed_addr {
entry-block:
  %_2 = alloca {}
  %foo = alloca %Foo
  br label %start

start:                                            ; preds = %entry-block
  %0 = getelementptr inbounds %Foo, %Foo* %foo, i32 0, i32 0
  store i8 1, i8* %0, align 1
  %1 = getelementptr inbounds %Foo, %Foo* %foo, i32 0, i32 1
  store i64 2, i64* %1, align 1
  %2 = getelementptr inbounds %Foo, %Foo* %foo, i32 0, i32 1
  %3 = load i64, i64* %2 ; <<< as far as I can tell this is the problem
  %4 = icmp ne i64 %3, 2
  br i1 %4, label %bb1, label %bb2

bb1:                                              ; preds = %start
  call void @_ZN3std7process4exit17hffedc4a49948f761E(i32 1)
  unreachable

bb2:                                              ; preds = %start
  call void @_ZN3std7process4exit17hffedc4a49948f761E(i32 0)
  unreachable
}

; Function Attrs: noreturn
declare void @_ZN3std7process4exit17hffedc4a49948f761E(i32) unnamed_addr #0

define i32 @main(i32, i8**) unnamed_addr {
top:
  %2 = call i32 @_ZN3std2rt10lang_start17hb7fc7ec87b663023E(i8* bitcast (void ()* @_ZN1p4main17h5a74305885b4a113E to i8*), i32 %0, i8** %1)
  ret i32 %2
}

declare i32 @_ZN3std2rt10lang_start17hb7fc7ec87b663023E(i8*, i32, i8**) unnamed_addr

attributes #0 = { noreturn }

!llvm.module.flags = !{!0}

!0 = !{i32 1, !"PIE Level", i32 2}
```

**Comment by arielb1** [comment]
@TimNN 

Can you instead fix the test to not UB?

**Comment by TimNN** [comment]
@arielb1: Probably, I'll take a look.

**Comment by pftbest** [comment]
@arielb1 Are you sure there is UB in this test?

**Comment by arielb1** [comment]
@pftbest 

Sure. It exploits a known soundness bug to create and dereference references to unaligned values.

**Comment by pftbest** [comment]
@arielb1 Can you please give me the issue number?

**Comment by arielb1** [comment]
#27060

**Comment by pftbest** [comment]
@arielb1 Sorry, I didn't notice it in TimNN's message. Thank you very much.

**Comment by TimNN** [comment]
I've been investigating some of the failures some more:

* I currently can't reproduce the powerpc failure (locally). I'll try travis again at some point.
* The `qemu-test-server` segfaults, which causes the `armhf-gnu` failure. I don't know yet why or where.

**Comment by TimNN** [comment]
After lots of printf debugging (anyone know how to easily use gdb with qemu?) I've identified and (somewhat) minified the segfault. 

As far as I can tell three things are required for the segfault to occur:

* A function returning a `u32`
* Which is immediately cast to a `u64` and assigned to a variable
* That variable is printed (which probably means a reference is taken and then dereferenced)

To reproduce use [this code](https://gist.github.com/7f19e9c8b7e110c61853002c2275a69a) as the `qemu-test-client` and send any four bytes. Sending any four bytes to the server should show `@@EXIT@@: 11` in the output.

I'll try to reduce this a bit further and submit an upstream bug report.

**Comment by TimNN** [comment]
Further minified:

```rs
fn main() {
    let amt = read_u32() as u64;
    amt.to_string();
}

fn read_u32() -> u32 {
    0xFFFFFFFF
}
```

This crashes on `-O0` as well. 

The IR looks good to me, see [this gist](https://gist.github.com/def210e8e4b163c8194e9f907fa3c289).

**Comment by TimNN** [comment]
I apparently made some wrong assumptions in the previous two posts, the actual issue seems to be with the Display implementation of `u64`, at least that's where the segfault occurs in the following reduced test case: `0xFFFFFFFFu64.to_string();`.

Which raises another question: The original `qemu-test-server` never calls that method (at least not directly), so where does it segfault?

Anyway, I got the following backtrace from a core dump (qemu has so far resisted all my attempts to directly debug it):

```
#0  core::fmt::num::{{impl}}::fmt (self=<optimized out>, f=<optimized out>) at /checkout/src/libcore/fmt/num.rs:225
#1  0xf6fa6bc4 in _$LT$$RF$$u27$a$u20$T$u20$as$u20$core..fmt..Display$GT$::fmt::h1aba0184188044d1 ()
#2  0xf6fe143c in core::fmt::write (output=..., args=...) at /checkout/src/libcore/fmt/mod.rs:911
#3  0xf6fa5d94 in core::fmt::Write::write_fmt::ha6ffb1fa01467a58 ()
#4  0xf6fa67dc in _$LT$T$u20$as$u20$collections..string..ToString$GT$::to_string::hdbd793466b747911 ()
#5  0xf6fa75c4 in crash::main::h2ab5f3fb53babb4d ()
#6  0xf6fb3510 in std::panicking::try::do_call<fn(),()> (data=<optimized out>) at /checkout/src/libstd/panicking.rs:454
#7  0xf6fbbe08 in panic_unwind::__rust_maybe_catch_panic (f=0xfd8f270f, data=0xfff <error: Cannot access memory at address 0xfff>, data_ptr=0xf6f9e484, vtable_ptr=0xf6f9e488)
    at /checkout/src/libpanic_unwind/lib.rs:98
#8  0xf6fb3ffc in std::panicking::try<(),fn()> (f=<optimized out>) at /checkout/src/libstd/panicking.rs:433
#9  std::panic::catch_unwind<fn(),()> (f=<optimized out>) at /checkout/src/libstd/panic.rs:361
#10 std::rt::lang_start (main=<optimized out>, argc=1, argv=0xf6f9e624) at /checkout/src/libstd/rt.rs:57
#11 0xf6fa7628 in main ()
```

**Comment by TimNN** [comment]
The segfault only occurs if `std` is compiled with optimizations. `configure`ing with `--disable-optimize` makes that segfault from the reduced test cases go away and the ~`qemu-test-server` seems to be stable so far~. Lets see how the the actual tests go...

... so I just got a rather interesting failure of the `qemu-test-server`:

```
@@ Watcher is running.
@@ Child is running.
starting test server
listening!
thread '<unnamed>' panicked at 'raw_cap overflow', /checkout/src/libstd/collections/hash/map.rs:52
note: Run with `RUST_BACKTRACE=1` for a backtrace.
@@EXIT@@: 11
```

Running with `RUST_BACKTRACE=1` produces this:

```
stack backtrace:
   0: std::collections::hash::map::DefaultResizePolicy::raw_capacity
             at ./checkout/src/libstd/collections/hash/map.rs:-738
   1: <std::collections::hash::map::HashMap<K, V, S>>::reserve
             at ./checkout/src/libstd/collections/hash/map.rs:777
   2: <std::collections::hash::map::HashMap<K, V, S>>::entry
             at ./checkout/src/libstd/collections/hash/map.rs:711
   3: std::sys::imp::process::process_common::Command::env
             at ./checkout/src/libstd/sys/unix/process/process_common.rs:390
   4: std::process::Command::env
             at ./checkout/src/libstd/process.rs:-42
   5: qemu_test_server::handle_run
             at ./checkout/src/tools/qemu-test-server/src/main.rs:-740
   6: qemu_test_server::main::{{closure}}
             at ./checkout/src/tools/qemu-test-server/src/main.rs:50
   7: <std::panic::AssertUnwindSafe<F> as core::ops::FnOnce<()>>::call_once
             at ./checkout/src/libstd/panic.rs:28
   8: std::panicking::try::do_call
             at ./checkout/src/libstd/panicking.rs:782
   9: __rust_try
  10: __rust_maybe_catch_panic
             at ./checkout/src/libpanic_unwind/lib.rs:70
  11: std::panicking::try
             at ./checkout/src/libstd/panicking.rs:727
  12: std::panic::catch_unwind
             at ./checkout/src/libstd/panic.rs:28
  13: std::thread::Builder::spawn::{{closure}}
             at ./checkout/src/libstd/thread/mod.rs:705
  14: <F as alloc::boxed::FnBox<A>>::call_box
             at ./checkout/src/liballoc/boxed.rs:28
  15: <alloc::boxed::Box<alloc::boxed::FnBox<A, Output$u3d$R$GT$$u20$$u2b$$u20$$u27$a$GT$$u20$as$u20$core..ops..FnOnce$LT$A$GT$$GT$::call_once
             at ./checkout/src/liballoc/boxed.rs:-70
  16: std::sys_common::thread::start_thread
             at ./checkout/src/libstd/sys_common/thread.rs:-98
  17: std::sys::imp::thread::Thread::new::thread_start
             at ./checkout/src/libstd/sys/unix/thread.rs:342
```

Don't ask me where the negative line numbers come from, some of the others seem to be incorrect as well.

Running with `RUST_BACKTRACE=full` causes the following output (and then hangs):

```
thread '<unnamed>' panicked at 'raw_cap overflow', /checkout/src/libstd/collections/hash/map.rs:52
stack backtrace:
   0: thread '<unnamed>' panicked at 'number not in the range 0..15: 91', /checkout/src/libcore/fmt/num.rs:340
thread '<unnamed>' panicked at 'raw_cap overflow', /checkout/src/libstd/collections/hash/map.rs:52
```

---

I'm not sure if I messed something up along the road but something seems to be seriously broken here.

**Comment by alexcrichton** [comment]
Oh dear sounds like something is definitely going seriously wrong :( 

My guess would be a miscompile or a misoptimization, although historically LLVM upgrades have uncovered existing bugs in the compiler which were only exploited by the newer LLVM version, so this may very well also be a bug in our own codegen.

**Comment by pftbest** [comment]
I see `debuginfo-lldb/union-smoke.rs` test failing on `x86_64-apple-darwin`
Is it ok? [full log](https://gist.github.com/pftbest/49ec5407ef7cdfc79ee9e7a42f2d6b04)

**Comment by TimNN** [comment]
@pftbest: It's not ok, however a known issue -- there's a problem with debuginfo for globals (I have ignored the affected tests on gdb for now, until I get around to fixing the issue). I would actually have expected more lldb test failures.

**Comment by TimNN** [comment]
Well, I'm not sure I'm happy about finding this, but it seems that we are (once again) having problems with `compiler-rt`, consider:

```rust
fn main() {
    let a = 176usize;
    let b = 10usize;
    let c = a / b;
    ::std::process::abort(); // yes, I'm debugging by forcibly generating coredumps  >.<
}
```

An `info locals` from the coredump reveals:

```
a = 176
b = 10
c = 15 // <-- This doesn't seem quite correct....
```

**Comment by TimNN** [comment]
So the problem is apparently with `__udivsi3` (which comes from `libgcc_s.so.1`!!): The arguments are passed in `r0` and `r1`, but then the returned value is `15` in `r0`.

I now checked with the current nightly: Here, `__udivsi3` originates from the compiled binary -- so apparently our compiler-rt is used.

Which now brings up the question what changes to make us fall back on `gcc_s` with LLVM 4.0? The only thing I can think of is the compiler-rt submodule update, I'll investigate what changed there.

On another note, I noticed that binaries compiled with LLVM 4.0 take *significantly* longer to start than those generate with a current rust nightly -- I don't know yet why or if this is even relevant.

**Comment by alexcrichton** [comment]
@TimNN holy cow you are crazy deep in "debug everything" land, but nice find! It's odd that compiler-rt is often the last suspect and more commonly than not the actual suspect...

cc @japaric, you may have thoughts here as well.

**Comment by TimNN** [comment]
One thing I noticed while poking around at things is in the output of `readelf` on the generated binaries (grepped for `udivsi3`):

```
# Dev / LLVM 4.0
 25400: 00000000     0 FILE    LOCAL  DEFAULT  ABS udivsi3.o
 25457: 00080ee8   728 FUNC    LOCAL  DEFAULT   13 __udivsi3

# Nightly / LLVM 3.9
 11607: 00000000     0 FILE    LOCAL  DEFAULT  ABS udivsi3.o
 11920: 000397b8   456 FUNC    GLOBAL HIDDEN    13 __udivsi3
```

I know that there have been discussions of marking functions as hidden, so maybe the above tells someone something?

**Comment by alexcrichton** [comment]
Hm that seems unusual. We try to compile that symbol as a hidden symbol, but that's just a flag we pass to the compiler when compiling compiler-rt. I'm not sure how that would change here... Unless the symbol was dropped/moved in the compiler-rt upgrade?

**Comment by TimNN** [comment]
And things are getting interesting again: The interesting symbol is `__aeabi_uidiv` (which is, of course, an alias for `__udivsi3`...): Now checking the `libcomiler_builtins.rlib` files for *that* symbol gives the following results:

```
# Dev / LLVM 4.0
     6: 00000000   728 FUNC    GLOBAL HIDDEN     1 __aeabi_uidiv

# Nightly / LLVM 3.9
     6: 00000000   456 FUNC    GLOBAL DEFAULT    1 __aeabi_uidiv
```

**Comment by alexcrichton** [comment]
Looks like a bunch of thumb related changes happened to [what I believe is the relevant file](https://github.com/llvm-mirror/compiler-rt/blob/1fdc27db84c9d0d9ae4ae60185629e8c43b4a11c/lib/builtins/arm/udivsi3.S) during the last upgrade.

https://github.com/llvm-mirror/compiler-rt/commit/b11de00dd802c0fbb263c9f263724067d7f6f6e0 also looks suspicious maybe? (just guessing here)

**Comment by TimNN** [comment]
> llvm-mirror/compiler-rt@b11de00 also looks suspicious maybe? (just guessing here)

Indeed, I'll see what happens if I revert that.

**Comment by TimNN** [comment]
>> llvm-mirror/compiler-rt@b11de00 also looks suspicious maybe? (just guessing here)
>
> Indeed, I'll see what happens if I revert that.

Well, that didn't work. On the other hand, I discovered that GDB was being annoying and the whole visibility thing was entirely the wrong direction:

* In the disassembly of my test program, gdb showed `bl	0xf6fddee8 <__udivsi3>`
* Checking `info symbol __udivsi3` says the symbol came from `libgcc_s.so.1`
* Checking `info symbol 0xf6fddee8` says the symbol comes from my binary
* :tired_face:
* So we are apparently miscompiling `comiler-rt` -- which *does* seem more reasonable than `libgcc_s` being broken.

**Comment by TimNN** [comment]
So, reverting llvm-mirror/compiler-rt@2fb759fa512d51f791a5bc94a31d4b952f25d04a seems to fix my small `__udivsi3` test case, however I'm still getting the `raw_cap overflow` panic, let's try to revert another of the thumb commits.

**Comment by alexcrichton** [comment]
It may be worth running a compilation by hand using cmake (compiler-rt's build system) and comparing the flags passed, they may be passing a crucial flag that we're missing :(

**Comment by TimNN** [comment]
Progress! With a second commit reverted and a clean rebuild of the arm stuff (not sure if the second revert was necessary) some tests seem to be running now!

However *some* tests (not all) are failing because we get a `undefined reference to core::panicking::panic::h6e43017a4193bfc4` while linking (with `-Cprefer-dynamic`). Lets investigate...

So, if I understand the output of `nm libstd.so` correctly, then the `core::panicking::panic::h6e43017a4193bfc4` symbol is "local", which could be a problem?

```
0041f818 t _ZN4core9panicking5panic17h6e43017a4193bfc4E
```

**Comment by alexcrichton** [comment]
I wonder if `__ARM_ARCH_ISA_THUMB` introduced in that commit is defined by compiler-rt's cmake build? Nothing jumped out to me but I'm not sure... We may just not be compiling with the right flags as well (or be targetting something completely different). I've never gotten a good handle on what appears to be a myriad of ARM targets...

That symbol in theory should be public yeah, although I've also never been able to decipher the output of `nm` so I'm not sure if that's the right visibility or not (have I mentioned that I've also never been able to keep the myriad of visibility/linkage settings straight in my head either?).

@TimNN does it print out where that undefined reference is coming from? It may be related to https://github.com/rust-lang/rust/pull/40254 if you haven't picked that up yet maybe. Or it may also be somewhere else in libcompiler_builtins which is accidentally wanting to unwind when it shouldn't want to be.

**Comment by TimNN** [comment]
@alexcrichton: I have #40254 in my branch, the undefined references are in the main code, examples:

```
  = note: /checkout/obj/build/x86_64-unknown-linux-gnu/test/run-fail/panic-task-name-owned.0.o: In function `panic_task_name_owned::main::h9a3cee2c481acc9d':
          panic_task_name_owned.cgu-0.rs:(.text._ZN21panic_task_name_owned4main17h9a3cee2c481acc9dE+0x338): undefined reference to `core::panicking::panic::h6e43017a4193bfc4'
          panic_task_name_owned.cgu-0.rs:(.text._ZN21panic_task_name_owned4main17h9a3cee2c481acc9dE+0x344): undefined reference to `core::panicking::panic::h6e43017a4193bfc4'
          collect2: error: ld returned 1 exit status

  = note: /checkout/obj/build/x86_64-unknown-linux-gnu/test/run-fail/overflowing-sub.0.o: In function `overflowing_sub::main::hbae6f30f43d4e64b':
          overflowing_sub.cgu-0.rs:(.text._ZN15overflowing_sub4main17hbae6f30f43d4e64bE+0xc): undefined reference to `core::panicking::panic::h6e43017a4193bfc4'

  = note: /checkout/obj/build/x86_64-unknown-linux-gnu/stage2/lib/rustlib/arm-unknown-linux-gnueabihf/lib/libtest-3acfb8602222df7d.so: undefined reference to `core::panicking::panic::h6e43017a4193bfc4'
```

By the way, these are the failing tests:

```
   [run-fail] run-fail/divide-by-zero.rs
    [run-fail] run-fail/hashmap-capacity-overflow.rs
    [run-fail] run-fail/mod-zero.rs
    [run-fail] run-fail/overflowing-add.rs
    [run-fail] run-fail/overflowing-lsh-1.rs
    [run-fail] run-fail/overflowing-lsh-2.rs
    [run-fail] run-fail/overflowing-lsh-3.rs
    [run-fail] run-fail/overflowing-lsh-4.rs
    [run-fail] run-fail/overflowing-mul.rs
    [run-fail] run-fail/overflowing-neg.rs
    [run-fail] run-fail/overflowing-pow-signed.rs
    [run-fail] run-fail/overflowing-pow-unsigned.rs
    [run-fail] run-fail/overflowing-rsh-1.rs
    [run-fail] run-fail/overflowing-rsh-2.rs
    [run-fail] run-fail/overflowing-rsh-3.rs
    [run-fail] run-fail/overflowing-rsh-4.rs
    [run-fail] run-fail/overflowing-rsh-5.rs
    [run-fail] run-fail/overflowing-rsh-6.rs
    [run-fail] run-fail/overflowing-sub.rs
    [run-fail] run-fail/panic-task-name-none.rs
    [run-fail] run-fail/panic-task-name-owned.rs
    [run-fail] run-fail/run-unexported-tests.rs
    [run-fail] run-fail/task-spawn-barefn.rs
    [run-fail] run-fail/test-panic.rs
    [run-fail] run-fail/test-should-fail-bad-message.rs
    [run-fail] run-fail/test-should-panic-bad-message.rs
    [run-fail] run-fail/test-should-panic-no-message.rs
    [run-fail] run-fail/test-tasks-invalid-value.rs
```

I can also reproduce with a program that simply `panic!()`s in `main`:

```
  = note: tp.0.o: In function `alloc::heap::allocate::h4af6872d500b6a6b':
          tp.cgu-0.rs:(.text._ZN5alloc4heap8allocate17h4af6872d500b6a6bE+0x4c): undefined reference to `core::panicking::panic::h6e43017a4193bfc4'
```

**Comment by alexcrichton** [comment]
Ok yeah that seems entirely unrelated to compiler-rt.

Can you check the IR generated for libcore? It may be helpful to take a look at the function definition for this symbol to see what we're telling LLVM. (hint: it shouldn't be `internal`)

**Comment by TimNN** [comment]
Re: `__ARM_ARCH_ISA_THUMB`: I think we *don't* want that flag to be defined (to keep the old implementation), however compiling the following small test program with my cross compiler, reveals that `__ARM_ARCH_ISA_THUMB` is automatically defined...

```c
#ifdef __ARM_ARCH_ISA_THUMB
#error BAD
#else
#error GOOD
#endif
```

**Comment by TimNN** [comment]
> Can you check the IR generated for libcore?

I can do so momentarily, however at least the libcore rlib seems to have the symbol publicly defined:

```
00000000 T _ZN4core9panicking5panic17h6e43017a4193bfc4E
```

How are the shared libraries generated?

---

By the way, forget the ~__ARM_ARCH_ISA_THUMB: I think we don't want that flag to be defined (to keep the old implementation)~ from the previous comment, I don't think that is correct.

**Comment by TimNN** [comment]
For the record my cross compiler uses:

```
__ARM_ARCH: 7
__ARM_ARCH_ISA_THUMB: 2
__ARM_ARCH_PROFILE: A
```

**Comment by alexcrichton** [comment]
We should just run basically:

```
gcc -shared -o libfoo.so -Wl,--whole-archive libfoo.rlib
```

(e.g. nothing fancy or LLVM dependent there)

**Comment by TimNN** [comment]
I get the following function definition:

```ll
; Function Attrs: cold noinline noreturn uwtable
define void @_ZN4core9panicking5panic17h6e43017a4193bfc4E({ %str_slice, %str_slice, i32 }* noalias readonly dereferenceable(20)) unnamed_addr #3 {

; For comparison:

; Function Attrs: cold noinline noreturn uwtable
define void @_ZN4core9panicking9panic_fmt17he3b8c85c760dcdccE(%"fmt::Arguments"* noalias nocapture dereferenceable(24), { %str_slice, i32 }* noalias readonly dereferenceable(12)) unnamed_addr #3 {
```

**Comment by TimNN** [comment]
Alright, so I think I know some of what is going on, however how that is different from LLVM 3.9, I don't know (yet):

As it turns out, `libcompiler_builtins` has references to `core::panicking::panic`! And if it is linked into the `.so` *after* `libcore`, the symbol gets hidden (I've only checked the `nm`, not yet a test compilation).

For the record, the following functions call `core::panicking::panic` (if I'm reading the output of `readelf` correctly):

```
_ZN4core3num21_$LT$impl$u20$i64$GT$15overflowing_shr17hbb25084440bea1ffE
_ZN4core3num21_$LT$impl$u20$u32$GT$15overflowing_shl17hebf019cda7aaad4eE
_ZN4core3num21_$LT$impl$u20$u32$GT$15overflowing_shr17h28c64480ffb5b769E
_ZN4core3num21_$LT$impl$u20$u64$GT$15overflowing_shl17h057b937dda71a8daE
_ZN4core3num21_$LT$impl$u20$u64$GT$15overflowing_shr17h77d38bf1169ec68aE
_ZN4core3num22_$LT$impl$u20$i128$GT$15overflowing_shl17h264aab4280fbd05fE
_ZN4core3num22_$LT$impl$u20$i128$GT$15overflowing_shr17ha7a3617a02c8f37bE
_ZN4core3num22_$LT$impl$u20$u128$GT$15overflowing_shl17h7cbe64bca4ffa03cE
_ZN4core3num22_$LT$impl$u20$u128$GT$15overflowing_shr17h363dc51c526c1d4fE
__ashlti3
__ashrti3
__lshrti3
__multi3
__fixunsdfti
__fixunssfti
__fixdfti
__fixsfti
```

cc @nagisa You fixed this (or something similar) in #40254, could you maybe take a look?

**Comment by TimNN** [comment]
So, apparently, the problem with the `panic` references is that `compiler_builtins` was compiled without optimizations. Whether this is ARM specific or caused by LLVM 4.0, I don't know yet, we'll see.

**Comment by alexcrichton** [comment]
Oh dear, that sounds bad! Note that with or without optimizations, the compiler builtins crate shouldn't reference any panic symbols...

**Comment by nagisa** [comment]
The panicking is introduced by `overflowing_sh*` which has implementation that looks like this:

```
(self >> (rhs & ($BITS - 1)), (rhs > ($BITS - 1)))
```

That shift over there is a checked shift and does not get optimised in no-opt mode. `wrapping_sh*` are implemented in terms of this `overflowing_sh*`. These could be fixed with some intrinsics, maybe?

**Comment by alexcrichton** [comment]
@TimNN want to try out conversion to the wrapping versions and see what happens?

**Comment by TimNN** [comment]
@alexcrichton: I don't think that would work, we would have infinite recursion then, according to @nagisa.

**Comment by nagisa** [comment]
Wrapping shifts are implemented in terms of the overflowing_sh*. At the
very least an intrinsic will be necessary.

**Comment by TimNN** [comment]
I opened #40508 for the ARM / panic failure.

**Comment by TimNN** [comment]
So some (mostly good, I guess) news: A (once again) optimized ARM build with the two commits mentioned previously reverted leads to almost all `run-pass` tests passing, with three (`issue-28950.rs`, `run-pass/panic-runtime/abort.rs` and `run-pass/panic-runtime/abort-link-to-unwinding-crates.rs`) hanging... somewhere. I'll investigate those as well as a "proper" fix for the reverted commits.

**Comment by TimNN** [comment]
Investigation results (on a Raspberry Pi 2):

* `issue-28950.rs`: segfault in`jemalloc::arena_run_split_remove` -> `std::sys::imp::stack_overflow::imp::signal_handler` -> thread local cleanup / atexit -> jemalloc -> deadlock
* `abort.rs`: Runs fine without `RUST_BACKTRACE`, with `=1` it hangs somewhere during unwinding (although I don't think we set `RUST_BACKTRACE` by default when running tests?), potentially a dead lock as well
* `abort-link-to-unwinding-crates.rs`: Same as `abort.rs`

**Comment by alexcrichton** [comment]
@TimNN we're still running into jemalloc dealocks?! 

:( :( :( :( :(

**Comment by TimNN** [comment]
@alexcrichton: Apparently :( Although it only happened after a segfault, so it's probably not *that* bad? Here is the backtrace, in case you are interested: https://gist.github.com/0b02e3fae217490cd004ea8a58b22f83

**Comment by TimNN** [comment]
Regarding the `issue-28950.rs` segfault / deadlock:

I can only assume that *somehow* jemalloc is miscompiled: The failures happens in the newly started thread, before any user code is run.

Now consider these three lines from the gdb stacktrace:

```
#23 <signal handler called>
#24 0x76dbac28 in arena_run_alloc_large_helper (arena=0x0, size=0, zero=false) at /checkout/src/liballoc_jemalloc/../jemalloc/src/arena.c:1093
#25 0x76dbb154 in arena_run_alloc_large (arena=0x766011c0, size=20480, zero=true) at /checkout/src/liballoc_jemalloc/../jemalloc/src/arena.c:1112
```

[The relevant jemalloc code](https://github.com/rust-lang/jemalloc/blob/11bfb0dcf85f7aa92abd30524bb1e42e18d108c6/src/arena.c#L1091-L1112).

Notice how `arena` is `0x766011c0` in `arena_run_alloc_large`, but when it is passed to `arena_run_alloc_large_helper`, it is `NULL` (and then later dereferenced in a probably inlined function?).

I'm not sure if these symptoms are indicative of a stackoverflow or not, however the test seems to deliberately test something in that regard.

**Comment by alexcrichton** [comment]
Note that I would at least personally have no problem jettisoning jemalloc further, especially if there's problems. If disabling jemalloc solves the issue, I say do that.

**Comment by TimNN** [comment]
@alexcrichton: Yeah, I was planning to try a `--disable-jeamlloc` build next.

**Comment by brson** [comment]
Here's some updates on the emscripten LLVM upgrade: https://internals.rust-lang.org/t/need-help-with-emscripten-port/3154/142

**Comment by TimNN** [comment]
I have tracked down the issue with the llvm IR that causes globals to show as `<optimzed out>` in GDB, the details can be found in #40580.

**Comment by TimNN** [comment]
I have opened #40612 which updates the NetBSD compiler to one which can compiler LLVM 4.0. That will hopefully lead to a successful `dist-s390x-linux-netbsd` build.

---

On another note, I was happily surprised that a build of `dist-fuchsia` was successful out of the box.

**Comment by alexcrichton** [comment]
Awesome work @TimNN (I really can't tell you that enough)

Out of curiosity have you tested this yet on Windows/OSX? Unfortunately those are harder to get testing on this PR (there's some bug for OSX on Travis and we don't have capacity to do so on AppVeyor), but I can start running builds and reporting back locally if that'd help.

**Comment by TimNN** [comment]
@alexcrichton: Not yet, however I think someone commented that they had at least gotten until the debuginfo tests on macOS. I can also test macOS locally however I don't have easy access to a windows machine. So if you (or someone else) wants to test those (especially windows), that would be helpful.

**Comment by alexcrichton** [comment]
Unfortunately MSVC failed pretty quickly in stage1 :(

```
   Compiling syntax v0.0.0 (file:///C:/msys64/home/alex/code/rust2/src/libsyntax)
LLVM ERROR: No open Win64 EH frame function!
error: Could not compile `syntax`.
```

**Comment by alexcrichton** [comment]
These run-pass tests all fail with the same error, and are likely smaller than all of libsyntax

```
failures:
    [run-pass] run-pass\debuginfo-lto.rs
    [run-pass] run-pass\issue-2631-b.rs
    [run-pass] run-pass\issue-29746.rs
    [run-pass] run-pass\issue-5666.rs
    [run-pass] run-pass\panic-runtime\lto-abort.rs
    [run-pass] run-pass\panic-runtime\lto-unwind.rs
    [run-pass] run-pass\sepcomp-lib-lto.rs
    [run-pass] run-pass\type-id-higher-rank-2.rs
```

**Comment by TimNN** [comment]
I have submitted a fix for the android assertion to LLVM: https://reviews.llvm.org/D31116

**Comment by TimNN** [comment]
@alexcrichton: FYI, `x86_64-pc-windows-msvc` and `x86_64-pc-windows-gnu` were successful for me. Were your failures for one of those targets?

(Note that I ran my `llvm40-tmp` branch, which however should only be a cleaned up version of this branch (and rebased on rust master)).

**Comment by alexcrichton** [comment]
Odd! I tested a523fba0942c36701e865cc112f4e692859801b1 with x86_64-pc-windows-msvc, but maybe I botched something? If it works for you locally I'd trust that.

I thought windows-gnu was in general an awful hurdle to overcome, but if x86_64 already works I didn't *think* it was i686 specific, but it may be worth double checking if you've got the cycles.

**Comment by TimNN** [comment]
@alexcrichton: Yeah, I'll try `i686` tomorrow. (I saw an ad for the microsoft azure free trial yesterday, and decided, why use that for something useful ;)

**Comment by TimNN** [comment]
More windows updates:

* `i686-pc-windows-msvc` fails `run-pass\backtrace.rs` it seems to work with may work if `RUST_BACKTRACE=full` is used for the failing test case.
* `i686-pc-windows-gnu`: I use the msys2 mingw, which apparently uses pthreads instead of win32 threads, I'll see if I can't get another build environment set up.

**Comment by alexcrichton** [comment]
Ah OK so on the backtrace business I have a [backport](https://github.com/rust-lang/rust/pull/40684) to reenable full and there's [ongoing discussion](https://github.com/rust-lang/rust/pull/40264) of how to work with it. In any case working around locally or setting `full` should be fine for now.

For the latter I'd recommend downloading the literal toolchain used on the bots (downloaded in `appveyor.yml`) to ensure it's the same, although we can certainly update that whenever we need to as well (we just haven't ever had impetus to do so).

**Comment by TimNN** [comment]
Regarding the backtrace test: cherry-picking @alexcrichton's backport did not fix the test. However adding an explicit `RUST_BACKTRACE=1` (no full required) [here](https://github.com/rust-lang/rust/blob/master/src/test/run-pass/backtrace.rs#L84) fixed the test. I'm not entirely sure what that part of the test is testing and if the missing `RUST_BACKTRACE=1` is an actual bug which just magically doesn't manifest on other platforms.

I'll try `i686-pc-windows-gnu` again tomorrow.

**Comment by TimNN** [comment]
I've been experimenting with `i686-pc-windows-gnu` and the toolchains specified in `appveyor.yml`: If I understand the situation correctly, we want mingw builds which use `win32` threads. This causes problems when compiling llvm, since those toolchains don't have support for `std::thread`. (I also tried newer versions of those toolchains, same result). (This also means that my success with `x86_64-pc-windows-gnu` is probably invalid).

As far as I can see we have three options:

* Remove all mention of `std::thread` and related things from llvm -- I believe this was done last time and tried / started to do this when testing freebsd in the beginning. From my impression / memories, I believe that this is not as easily done as last time.
* Switch to pthread based mingw -- I'm not sure what the advantages / disadvantages are here. There are apparently reasons for not wanting to do this. Also, I previously tried a build with a pthread based mingw and got some link failures which would need to be debugged.
* We could experiment with [some hacky? headers](https://github.com/meganz/mingw-std-threads) which apparently provide the necessary `std::threads` implementation however lack other things (futures / async / packaged_task or something).

**Comment by nagisa** [comment]
I’d be inclined to just drop i686-pc-windows-gnu rustc builds altogether if its that troublesome. Except its a Tier 1 platform :/

**Comment by petrochenkov** [comment]
`meganz/mingw-std-threads` seems to be a commonly advised solution and the way to go in the short term (if it works).
It's not as crucial change as switching to pthread model, not so blatantly non-future proof as removing uses of `std::thread` from LLVM code, and it unblocks the progress towards 4.0.

**Comment by vadimcn** [comment]
@TimNN: There were basically two reasons we've avoided pthread-based mingw-w64 toolchain:
1. It added a dependency on pthreads dll to all Rust programs compiled with this toolchain (mainly because Rust heavily relied on libc, which, in turn, used pthreads' sync primitives).
2. Back then it was found to be [very slow](https://github.com/rust-lang/rust/issues/8996#issuecomment-24292739), though it seems this may have been [fixed](https://sourceforge.net/p/mingw-w64/bugs/344/) since.

I wouldn't mind switching to pthread-based toolchain for building *rustc itself*, as long as 1. were still true. 
 I don't remember all the details at the moment, but it should be possible - these days libstd directly calls into native Windows API most of the time.

I'll try to find time to look into this in the next few days.

**Comment by alexcrichton** [comment]
Yeah unfortunately this may end up being one of the more difficult parts of the LLVM upgrade (not that the parts leading up to this have been easy ...). @vadimcn is right in that we intentionally have not used the pthread toolchain yet for various reasons. The landscape is very different today though from way-back-when, notably MSVC is a thing that is also tier 1.

My thoughts on this are in order of preference (but not in order of feasibility):

* Ideally we stop shipping i686-pc-windows-gnu targets. MinGW just flat out is not supported by LLVM afaik, and yet we keep trying to get it to work. This is unfortunately a pretty invasive change though. While possible I think this is a last resort style option due to the work involved to implement this.
* Otherwise ideally I like @vadimcn's idea of compiling the compiler with a pthread toolchain. The hard constraint here is that a user-compiled program should not depend on the pthread dll and should be compatible with the win32 toolchain. Note that I think the dependency on the pthread dll arises from the unwinder, not Rust code nowadays. AFAIK libstd uses nothing fro the mingw runtime other than the unwinder (which is a pretty big piece ...)
* I hadn't heard of the compiler @petrochenkov mentioned, but sounds plausible! I'm slightly wary of switching to a semi-random compiler to compile all our builds, but we may not have many other options.
* Finally, we can look again to ripping out threading support from LLVM. We don't want LLVM to spawn threads anyway, and I believe most synchronization primitives at least are implemented in the i686-pc-windows-gnu win32 toolchain. This is obviously the most distasteful approach though.

Mostly I'm up for anything here. My only real hard constraint is that we can't impact users of the i686-pc-windows-gnu toolchain (e.g. the binaries they generate), but other than that I think we can pick whatever works first.

**Comment by TimNN** [comment]
The `meganz/mingw-std-threads` @petrochenkov Is the same thing I linked above -- basically just three headers, which provide `thread`, `mutex` and `condition_variable`. However LLVM uses other stuff as well, such as futures, async and packaged_task which are provided neither by mingw nor by these additional headers.

**Comment by TimNN** [comment]
I did a quick check on the `x86_64-pc-windows-gnu` which was compiled by msys2/mingw, which is the `pthread/seh` version as far as I can tell: According to dependency walker, `rustc` has a transitive dependency on winpthread through `librustc_llvm` -> `libstc++6` -> `winpthreads`. `libstd` and a program compiled by that toolchain seem to be `winpthread` free.

**Comment by alexcrichton** [comment]
Ah so the x86_64-pc-windows-gnu unwinder is very different than the i686-pc-windows-gnu unwinder, so it may be worth double checking i686. If libstd binaries picked up a dependency on winpthreads my guess is it'd be through that (the unwinder)

**Comment by TimNN** [comment]
Yeah, I don't think we can get around the pthread dependency on i686 easily, if at all. However I'm still happy that  we can probably get away with `pthread/seh` on `x86_64-pc-windows-gnu`.

Out of curiosity, do you have download / usage stats for the different windows versions of rust?

**Comment by alexcrichton** [comment]
Ah yeah so FWIW I think moving to compiling the compiler with a pthread/seh toolchain on x86_64 should work just fine. We'll have to update some script somewhere to distribute the new dll but that's no different than distributing the libstdc++ dll we do today. I'm pretty confident this toolchain switch will not affect programs compiled by the compiler (the unwinder is implemented in Rust and kernel32.dll, not in the mingw libraries)

Unfortunately we don't have many usage stats :(

**Comment by vadimcn** [comment]
-pc-windows-msvc depend on MSVC linker, so you need to have at least the MSVC Build Tools installed along with it.   I don't think we can kill  -pc-windows-gnu targets until we migrate to the lld linker or something.

**Comment by jonathandturner** [comment]
@vadimcn - for sake of argument, since the VS tools are free, it seems they are roughly on par with the gnu tools in terms of being able to get and use them.  Since the access is the same, are there other advantages of the gnu tools?

**Comment by vadimcn** [comment]
@jonathandturner: For one thing, you can install a complete -pc-windows-gnu toolchain with rustup, not so for -msvc.
-gnu may also be needed when linking with c++ libraries that do not build with MSVC.

**Comment by vadimcn** [comment]
So I tried building Rust with msys2's i686 mingw toolchain and it fails to link because of references to pthread functions from libgcc_eh.a.

**Comment by JordiPolo** [comment]
Maybe open a question in some very visible blog or reddit or somewhere like that about if anyone is in fact using `i686-pc-windows-gnu`?

**Comment by vadimcn** [comment]
I've managed to build the compiler with msys2's i686 mingw toolchain, but this required several manual steps.
1.  First of all, since gcc's unwinder depends on pthreads, we'll need to add ` println!("cargo:rustc-link-lib=pthread");` after [this line](https://github.com/rust-lang/rust/blob/8c4f2c64c6759a82f143e23964a46a65c67509c9/src/libunwind/build.rs#L38).
2. stage0 failed to build stage1 because it does not have the line above.  Setting `RUSTC_FLAGS=-Clink-arg=-lpthread` didn't seem to have any effect, so I fixed this by copying libgcc_eh.a and import libs from a nightly into `stage0/lib/rustlib/i686-pc-windows-gnu/lib`. 
3. Using the newly built stage1 toolchain I compiled a test program, and found out that it depends on winpthread1.dll :(  
Turns out gcc has both static and dynamic version of libpthread, and by default it prefers the dynamic one.   Fixed this by deleting `libpthread.dll.a` from `msys/mingw32/i686-w64-mingw32/lib`.  

After all that my test program compiled and did not depend on winpthread dll.  
Not sure how to fix 2. and 3. in rustbuild though...

**Comment by TimNN** [comment]
@vadimcn: Awesome! I thought that something along the lines of 1) and 2) should be possible, thanks for figuring that out!

@alexcrichton: Does linking `libpthread` statically sound like an acceptable solution to you?

I can look into the necessary rustbuild changes and would open a separate PR for that.

Regarding the slowness you mentioned, @vadimcn: I'll assume we would need a fairly recent mingw toolchain to get that fix? Live Edit: Ah you mentioned in https://github.com/rust-lang/rust/issues/28445#issuecomment-242923887 that this was fixed in 6.2.0, so I assume we'd just go and use 6.3.0?

@alexcrichton: Do we have any compatibility constraints, which mingw version we use?

**Comment by vadimcn** [comment]
@TimNN: yes, the slowness seems to have been fixed. 

To make sure that ld selects the static version of libpthread we could use `-Wl,-Bstatic` hint, except that I don't think you can inject it from a build script.  We'd have to switch to `#[link_args=...]`.

**Comment by cuviper** [comment]
Build scripts can specifiy the "kind", with the same meaning as `#[link]` kind.  So you'd output:
`cargo:rustc-link-lib=static=pthread`

**Comment by alexcrichton** [comment]
Yeah upgrading to 6.3.0 should be totally fine and linking libpthread statically seems ok.

I, too, do not know how to deal with `-Wl,-Bstatic`. I unfortunately don't think we can use `static=pthread` like @cuviper mentioned as I think such a construction would cause the libstd to be incompatible with other non-6.3.0 toolchains. I wonder if maybe the `static-nobundle` type can be used in this case? I think technically gcc_eh should also be `static-nobundle`...

**Comment by vadimcn** [comment]
>  I wonder if maybe the static-nobundle type can be used in this case? I think technically gcc_eh should also be static-nobundle...

Yeah, sounds like another use case for `static-nobundle`!   I don't think we currently do static hinting for them though.

**Comment by vadimcn** [comment]
Okay, I have a branch [here](https://github.com/vadimcn/rust/tree/msys-mingw) that builds and passes tests (well, up until debug info tests) on msys's version of mingw.

Depends on #40524 for kind=static-nobundle

**Comment by alexcrichton** [comment]
@vadimcn so just to clarify, I think that patch will break compatibility with win32 toolchains, right?

**Comment by vadimcn** [comment]
>  I think that patch will break compatibility with win32 toolchains, right?

I don't think so: win32 toolchains still include libpthread, they just don't use in std.

**Comment by alexcrichton** [comment]
Excellent! A+ from me

**Comment by vadimcn** [comment]
@TimNN, do you want incorporate this into your PR, or should I submit it separately?

**Comment by TimNN** [comment]
@vadimcn: I think it would be best to land this separately. This PR will still take a bit of time -- There're still some test failures on ARM and I haven't yet really tested on macOS.

Also I think both PR have a high potential to causes trouble on the bots, so landing things in small chunks would be preferable, I think.

**Comment by arielb1** [comment]
@TimNN

If you are rebasing, remember to apply the fix in #40779 to your LLVM (or you'll get a test failure on ARM).

**Comment by TimNN** [comment]
@arielb1: Thanks for the heads up, this was already on my mental todo list :)

**Comment by TimNN** [comment]
I reported the PowerPC failure as https://bugs.llvm.org//show_bug.cgi?id=32485.

**Comment by TimNN** [comment]
I have a tentative (but probably a bit too heavy-handed for inclusion in upstream LLVM) fix for the PowerPC failure at https://github.com/TimNN/llvm/commit/aa34b2c4570ac876c4b28917bceed0cbbd322972, which simply disables the bad optimisation in more situations.

With that patch PowerPC completes successfully.

**Comment by TimNN** [comment]
So, I also went back to the ARM failures:

To recap: `compiler-rt` got a [few](https://github.com/llvm-mirror/compiler-rt/commit/af83c6630d02151a694e51bd4e73c1d112d71bfa?diff=split) [patches](https://github.com/llvm-mirror/compiler-rt/commit/2fb759fa512d51f791a5bc94a31d4b952f25d04a?diff=split) which added code specific for Thumb1. With those patches applied our builds were failing in strange ways.

I originally stated that our cross compiler had `__ARM_ARCH_ISA_THUMB=2` defined, so those patches should not apply to us. Revisiting the issue I noticed that, due to us passing `-march=armv6` to the compiler, it's actually using `__ARM_ARCH_ISA_THUMB=1`. 

Thus my new fix is to [patch `gcc-rs`](https://github.com/TimNN/gcc-rs/commit/2f0fcfecb469d8221eaff14f48b9d78563dd8fdb) to use `-march=armv6t2`.

This seems to fix the main problem on ARM and incidentally the jemalloc deadlock as well.

Still remaining are `panic-runtime/abort.rs` and `run-pass/panic-runtime/abort-link-to-unwinding-crates.rs` not terminating.

**TODO:**

* [ ] Should we adjust the configs in `dist-arm-linux` to also set `CT_ARCH_ARCH=armv6t2`?

Now the real questions:

* Is that the "correct" fix?
* Is it acceptable to upstream that patch to `gcc-rs`?
* Or should we maybe try and compile just `compiler-rt` (and jemalloc?) with `-march=armv6t2`?

**Comment by ticki** [comment]
@MeinFuehrer 

what is your point even?

**Comment by alexcrichton** [comment]
@TimNN I personally have no idea what the difference between armv6 and armv6t2 are, so I probably can't comment much to wheteher that's right or not. But hey if it makes things work it makes things work!

Adjusting dist-arm-linux is ok, although optional. It basically just affects how we compile jemalloc which isn't too too important if it's a little slower than it would be otherwise.

The powerpc patch also seems ok to me, but it'd be great if an LLVM dev could say "yeah seems fine" before we throw it in (it's good that we have an issue to track upstream as well)

**Comment by TimNN** [comment]
I'm currently debugging the `panic-runtime/abort.rs` hang: As previously stated it only occurs when `RUST_BACKTRACE=1`, it gets until `_Unwind_Backtrace`, where it apparently ends up in some complex endless loop.

As best as I can tell, our `trace_fn` is called repeated, with the exact same values in the registers and on the stack around `$sp`.

I have no idea what could be going on. There is a [supposedly fixed gcc bug](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=56846) from 2014 which describes somewhat the same symptoms.

If someone wants to take a look, here is a link to the compiled abort test: https://transfer.sh/YJdCY/abort

Run with `RUST_BACKTRACE=1` and `foo` as an argument and you should have an endlessly running program.

Hint: If gdb shows a broken backtrace (eg. only to entries in `gcc_s.so`) do `stepi` until you're out of `gcc_s.so`.

**Comment by MeinFuehrer** [comment]
Where's my fucking comment you fucking SJW monkeys? These two idiots don't even know what the fuck they're doing, no use covering it all up.

**Previous comment:**
@timnn Unless you actually have no idea what you're talking about, that's a great idea to fuck the fruity logo SJW crowd!

jawohl, Käpt'n!

**Comment by alexcrichton** [comment]
@TimNN I wonder if that's related to the super ancient toolchain we're using? 

(or is that the other image...)

**Comment by MeinFuehrer** [comment]
Where's my fucking comment you fucking SJW monkeys? These two idiots don't even know what the fuck they're doing, no use covering it all up.

**Previous comment:**
@timnn Unless you actually have no idea what you're talking about, that's a great idea to fuck the fruity logo SJW crowd!

jawohl, Käpt'n!

**Comment by TimNN** [comment]
@alexcrichton: No, we're actually using a fairly recent toolchain in that image:

```
$ arm-linux-gnueabihf-gcc --version
arm-linux-gnueabihf-gcc (Ubuntu/Linaro 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609
```

On my test raspberry I have gcc 5.2.1.

**Comment by alexcrichton** [comment]
Bah that's a bummer.. If worse comes to worse I think we should disable that test. It's a non-tier 1 platform and it's holding up the LLVM upgrade, which probably isn't worth it.

**Comment by alexcrichton** [comment]
(disable that test for arm, that is)

**Comment by MeinFuehrer** [comment]
Saved for posterity: https://archive.is/ACutm

Where's my fucking comment you fucking SJW monkeys? These two idiots don't even know what the fuck they're doing, no use covering it all up.

Previous comment:
@timnn Unless you actually have no idea what you're talking about, that's a great idea to fuck the fruity logo SJW crowd!
jawohl, Käpt'n!

https://archive.is/ACutm

**Comment by nagisa** [comment]
So, the Thumb2 thing is interesting, because sources seem to indicate it is a required extension in ARMv6, but then there’s no point in not having it enabled by default?

**Comment by TimNN** [comment]
I just patched both of those tests to set `RUST_BACKTRACE=0` for the sub command executed, and all other tests passed. So I would just set `RUST_BACKTRACE=0` conditionally on the arm target.

**Comment by alexcrichton** [comment]
@TimNN that seems like a reasonable workaround to me at least, yeah.

Note that if we take that route we should file an issue to track fixing it, but that's ok.

**Comment by alexcrichton** [comment]
guh didn't mean to close

**Comment by TimNN** [comment]
So, it appears that the `thumb 1` implementation of (at least) `__udivsi3` is simply incorrect, it doesn't even pass `compiler-rt`'s unittests when compiled with `-march=arm`.

**Comment by TimNN** [comment]
With the `-D__ARM_ARCH_ISA_THUMB=0` proposed by @nagisa in alexcrichton/gcc-rs#149 the compiler-rt unit tests pass as well, so I'll see what happens if I pass that to the `compiler-rt` build.

**Comment by TimNN** [comment]
I reported the bad Thumb1 builtin as https://bugs.llvm.org/show_bug.cgi?id=32492

**Comment by TimNN** [comment]
I've switched to a different fix for the ARM builtin failures: manually defining `__ARM_ARCH_ISA_THUMB=0` in the `compiler-rt` build script, as suggested in alexcrichton/gcc-rs#149.

Note that this does not fix the `panic-runtime/abort*` failures, so extra path for them is still required.

**Comment by MeinFuehrer** [comment]
https://archive.is/o2yuQ

https://archive.is/ACutm#selection-22847.0-22865.15

**Comment by TimNN** [comment]
Since the linux builds seem to be done now (except for emscripten, I'll try to report that bug upstream this week) I've been looking into macOS today:

Except for one debuginfo test, everything passes!

The failing test is `cross-crates-span.rs`: The same generic function (from another crate) is called with different type parameters. The test sets a breakpoint in that function. The breakpoint in *one* of the instantiations of the generic function is not hit (I've experimented with different combinations).

I'll continue looking into that, though if anyone has any insights, please let me know.

**Comment by TimNN** [comment]
So, well, I checked, and `cross-crates-span.rs` fails for me with LLVM 3.9 as well, so I guess that's good news and I'll just assume it will pass on the bots.

The iOS build was successful as well, which means we should be getting pretty close to getting this merged.

This means I will be looking into Windows again next.

**Comment by alexcrichton** [comment]
Thanks for the updates @TimNN! If you're feeling like this is getting close we can try throwing this at @bors.

**Comment by TimNN** [comment]
I reported the emscripten failure upstream with a minimised testcase: kripken/emscripten-fastcomp#176

**Comment by pnkfelix** [comment]
(FYI it is thought that landing this PR will fix #39015 . I mention this mostly so that this PR's status will show up on that ticket. ;)

**Comment by TimNN** [comment]
So just FYI, the test thats failing with emscripten & LLVM 4.0 actually fails as well on master when emscripten is compiled with debug assertions...

On the other hand, I think I've found the problem and a fix!

**Comment by TimNN** [comment]
I've also submitted my initial patch for the PowerPC assertion to upstream llvm ([D31790](https://reviews.llvm.org/D31790)) and got some feedback on a better, more targeted fix. I'll switch to that once the review is done.

**Comment by cuviper** [comment]
It seems like you're getting really close!

Do you think this will be ready before 1.18 branches?

**Comment by TimNN** [comment]
So unless something has regressed, the only thing that requires more work is `windows-gnu` and I'll be working on that over the weekend so this PR will hopefully be ready by the end of next week at the latest. Which means it should be in time for 1.18.

The only thing that I can imagine delaying this PR to 1.19 is a deliberate decision to merge this after 1.18 has branched to have the full six weeks of nightlies to find any regressions.

**Comment by TimNN** [comment]
Lets make use of the empty queue:

@bors try

**Comment by TimNN** [comment]
Well... `windows-gnu` is proving to be terribly uncooperative. 

As expected MinGW with Win32 threads doesn't work since it doesn't provide `std::thread (c++)`. MinGW with Posix threads required some additional, manual linking of `libpthread` and `libgcc_s` (despite #40805) and now causes `undefined reference to LLVMRustSetLLVMOptions, rustc_llvm::initialize_available_targets::hdba7e30f03a6524a` with MinGW64. On MinGW32 `llvm-tblgen.exe` crashes...

This led me to ask the question: Why do we even compile `rustc` with `MinGW`? Wouldn't `std` be enough? Thus I opened #41165 to discuss just that.

---

On another note, while the emscripten assertion has been fixed, the test still fails... I'll investigate a bit, but if nothing jumps out I'm inclined to just ignore the test for emscripten (at least for now).

**Comment by alexcrichton** [comment]
@TimNN feel free to throw this at @bors if we've got an empty queue, we can at least test out and see how far it gets.

I'll comment on the reference issue about MinGW. tl;dr; we should try really hard to get it working as-is.

**Comment by TimNN** [comment]
@alexcrichton: Does "working as-is" mean staying with Win32 Threads or does that include switching to pthread?

---

@vadimcn: I'm having trouble building my `llvm40` branch (which has your patch applied) with MinGW with  Posix threads:

* Linking `rustllvm` complains about missing `pthread` / `tls` symbols, though this can be fixed by adding `cargo:rustc-link-lib={gcc_s,pthread}` (also tried with `static` and `static-nobundle`)
* Linking `rustc` complains about missing symbols (if the above is fixed):

```
  = note: C:\r4\64-msys\build\x86_64-pc-windows-gnu\stage0-rustc\x86_64-pc-windows-gnu\release\deps\rustc-b4f37a4481245cd2.0.o:(.text+0x21dde): undefined reference to `LLVMStartMultithreaded'
          C:\r4\64-msys\build\x86_64-pc-windows-gnu\stage0-rustc\x86_64-pc-windows-gnu\release\deps\rustc-b4f37a4481245cd2.0.o:(.text+0x21ebf): undefined reference to `LLVMInitializePasses'
          C:\r4\64-msys\build\x86_64-pc-windows-gnu\stage0-rustc\x86_64-pc-windows-gnu\release\deps\rustc-b4f37a4481245cd2.0.o:(.text+0x21ec4): undefined reference to `rustc_llvm::initialize_available_targets'
          C:\r4\64-msys\build\x86_64-pc-windows-gnu\stage0-rustc\x86_64-pc-windows-gnu\release\deps\rustc-b4f37a4481245cd2.0.o:(.text+0x21ed2): undefined reference to `LLVMRustSetLLVMOptions'
          collect2.exe: error: ld returned 1 exit status
```

Do you have any ideas?

For the record, I have configured rustc with: `configure --enable-extended --enable-ninja --disable-manage-submodules --enable-locked-deps --enable-cargo-openssl-static --enable-llvm-static-stdcpp --enable-debug-assertions --enable-llvm-assertions --build=x86_64-pc-windows-gnu`

---

(@alexcrichton: I don't think throwing at bors is useful yet, since the `windows-gnu` build fail fairly quickly, so all the other builds would be canceled)

Although I guess trying wouldn't hurt.

@bors r+

**Comment by cuviper** [comment]
Perhaps bors is deterred by WIP in the title?

**Comment by petrochenkov** [comment]
>Perhaps bors is deterred by WIP in the title?

[Exactly.](https://github.com/servo/homu/blob/8d565101c84aeed60a0df9e57f90cf6c1713b072/homu/main.py#L431)

**Comment by TimNN** [comment]
Ugh. I thought this was somehow related to the 'try', which previously bors thought had timed out.

Thanks for the heads up!

**Comment by vadimcn** [comment]
@TimNN: I've managed to build at least stage1, though with current LLVM snapshot not with your branch.
Also, I used cargobuild (i.e. configured it via config.toml), not `configure`.

Did you use the toolchain packaged by msys2, or a standalone one (e.g. from mingw-builds)?
Did you rebuild LLVM?

**Comment by TimNN** [comment]
@vadimcn: I'm using the mingw shipped with msys2.

I can build the current master just fine, the errors only occur on my branch.

> Did you rebuild LLVM?

I started in a clean build directory, so I'd say that counts as a yes.

**Comment by TimNN** [comment]
@vadimcn: BTW, the only potentially important thing in that configure line is probably `--enable-llvm-static-stdcpp`, although again, that works just fine on rust master.

**Comment by vadimcn** [comment]
@TimNN: are you saying that the only combination that doesn't work is pthreads mingw + your branch?

**Comment by TimNN** [comment]
@vadimcn:

* `master` + `MingGW Win32 Threads`: Presumably works
* `master` + `Msys2 MinGW (Posix Threads)`: Works
* `llvm40` + `MinGW Win32 Threads`: Doesn't work (missing `std::thread (c++)` support
* `llvm40` + `Msys2 MinGW (Posix Threads)`: Doesn't work (see errors above)

**Comment by vadimcn** [comment]
I've repro'd the linker error. This is very strange - these 4 symbols *are* exported from rustc_llvm-XXXXXXX.dll

**Comment by vadimcn** [comment]
> these 4 symbols are exported from rustc_llvm-XXXXXXX.dll

Actually, it seems that I was wrong abut that.  After rebuilding everything from scratch, I found that `rustc_llvm-XXXXXXX.dll` exported only a handful of symbols, all of them from emscripten's "Relooper" library (e.g. `rl_new_relooper`).

Why had this happened?  [This page](https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/4/html/Using_ld_the_GNU_Linker/win32.html) gives the answer:

> By default ld exports symbols with the auto-export functionality, 
> [...]
> If, however, -export-all-symbols is not given explicitly on the command line, then the default auto-export behavior will be disabled if either of the following are true:
> * A DEF file is used.
> * Any symbol in any object file was marked with the __declspec(dllexport) attribute.

As it happens, Relooper's public API is marked with `__declspec(dllexport)` and so all other symbols become private.
I found it a bit hard to believe that this is the first time we are coming across this case, but setting `RUSTFLAGS=-CLink-arg=-Wl,--export-all-symbols` did fix the build.

**Comment by TimNN** [comment]
@vadimcn: Awesome, thanks for the investigation!

**Comment by TimNN** [comment]
So how do we best fix this?

With my admittedly limited understanding of the situation, we have multiple choices

* Fix this for rustbuild only:
    * Use `RUSTFLAGS`
    * Update cargo to support adding `-Clink-arg=...` from the build script of `rustc_llvm`
    * Hack something together with `#[link_args=...]` and features set in the build script of `rustc_llvm`
* Fix this in `rustc`:
    * on mingw, always pass `--export-all-symbols`

cc @alexcrichton, @retep998

**Comment by retep998** [comment]
@TimNN What we *should* be doing is using an explicit DEF file or linker script for dylibs, the way we currently do for cdylibs on all platforms, and dylibs for msvc.

**Comment by alexcrichton** [comment]
Spoke briefly with @TimNN on IRC about this. First off awesome find @vadimcn, that sounds notoriously hard to track down!

Looks like the dllexport may be coming from the LLVM source itself, so @TimNN is going to run a test where we just comment that out in our forked version of LLVM and see if it work.

**Comment by vadimcn** [comment]
Removing dllexports from relooper symbols would be the quickest fix in this case.

To fix it robustly, we should either start passing `--export-all-symbols` when linking Rust dylibs, or provide an explicit list of exports as @retep998 syggests.
In either case well need a separate fix for stage0.  `#[link_args("-Wl,--export-all-symbols")]` in rustc_llvm would probably work.

**Comment by alexcrichton** [comment]
I would prefer to avoid changing linker invocations in this PR itself, those have a high likelihood for causing breakage. Let's defer that to later if the removing dllexport fixes the issue.

**Comment by TimNN** [comment]
@bors r+

Lets see what the bots say, (this includes an `exit 1`) to deliberately fail the build.

**Comment by TimNN** [comment]
Appveyor fails with this:

```
FAILED: lib/Target/ARM/ARMGenSubtargetInfo.inc.tmp 
cmd.exe /C "cd /D C:\projects\rust\build\i686-pc-windows-gnu\llvm\build\lib\Target\ARM && C:\projects\rust\build\i686-pc-windows-gnu\llvm\build\bin\llvm-tblgen.exe -gen-subtarget -I C:/projects/rust/src/llvm/lib/Target/ARM -I C:/projects/rust/src/llvm/include -I C:/projects/rust/src/llvm/lib/Target C:/projects/rust/src/llvm/lib/Target/ARM/ARM.td -o C:/projects/rust/build/i686-pc-windows-gnu/llvm/build/lib/Target/ARM/ARMGenSubtargetInfo.inc.tmp"
Wrote crash dump file "C:\Users\appveyor\AppData\Local\Temp\1\llvm-tblgen.exe-079dbc.dmp"
0x004683DA (0x0167FA38 0x00000003 0x004D5241 0x00000020)
0x03358D58 (0x0029D8A8 0x00000000 0x005DEF40 0x0015C1A6) <unknown module>
0x7675E3FB (0x00000000 0x02E4FD68 0x018134B0 0x0337A230), _mbsnbicoll_l() + 0x5B bytes(s)
0x75B8D4E3 (0x0181BBD8 0x004671F0 0x00602AE4 0x00000000), SetConsoleCtrlHandler() + 0xD3 bytes(s)
0x005DA851 (0x0000000B 0x0181BBA0 0x01813778 0x00000000)
0x004013E2 (0x7FFDE000 0x76B87BE0 0xB71583D1 0x0167FFDC)
0x76B87C04 (0x7FFDE000 0xB6DBCBBA 0x00000000 0x00000000), BaseThreadInitThunk() + 0x24 bytes(s)
0x76FEAB8F (0xFFFFFFFF 0x76FCFFFD 0x00000000 0x00000000), RtlInitializeExceptionChain() + 0x8F bytes(s)
0x76FEAB5A (0x004014E0 0x7FFDE000 0x00000000 0x00000000), RtlInitializeExceptionChain() + 0x5A bytes(s)
[964/1773] Building ARMGenMCCodeEmitter.inc...
```

If I remember correctly, I've encountered this previously when using a 32bit MinGW from sourceforge. I'll see if I can reproduce this again.

**Comment by TimNN** [comment]
I couldn't reproduce the `tablegen` failure locally, however appveyor seems to fail consistently (I tried different mingw versions as well):

https://ci.appveyor.com/project/TimNN/rust/history

I had the `.dmp` file uploaded to https://transfer.sh/x9pLn/foo.dmp, 

I uploaded that dump file to http://www.osronline.com/page.cfm?name=analyze, however the only useful thing I could gleam from the output was that it was apparently caused by a null pointer.

At this point I'm kinda out of ideas, anyone any thoughts?

**Comment by ranma42** [comment]
That looks similar to http://lists.llvm.org/pipermail/cfe-dev/2016-December/051980.html (i.e. it might be caused by a miscompilation).

**Comment by TimNN** [comment]
@ranma42: Nice find! I'll try the suggested workaround (compile with `-fno-omit-frame-pointer`) soon.

**Comment by TimNN** [comment]
Lets give this anothet try, since my test build has passed the critical point.

@bors r+

**Comment by TimNN** [comment]
Ugh. I think I lost a small patch during a rebase, I'll fix that once I'm back at a computer.

**Comment by nagbot-rs** [comment]
test

-Manish

**Comment by arielb1** [comment]
```
ar: creating archive ../libcrypto.a
...
[01:01:38] Undefined symbols for architecture i386:

[01:01:38]   "_ERR_load_OBJ_strings", referenced from:

[01:01:38]       _ERR_load_crypto_strings in libcrypto.a(err_all.o)
```

 - #40417 (not sure)

let's see: @bors retry

**Comment by TimNN** [comment]
@alexcrichton: I went through all the merged PRs newer than rust-lang/llvm#34 and cherry-picked those not in my branch except rust-lang/llvm#68 (that hasn't landed on `rust-lang/master` yet) and rust-lang/llvm#37 (that had merge conflicts and I wasn't sure how applicable it still was).

If those don't cause any problems with bors I think this is good to go, but I'll leave the final r+ to you.

**Comment by TimNN** [comment]
(Grrr. I wasn't done yet GitHub)

One open question remains: Given that the next beta is cut in 11 days, should we postpone merging this until after the beta (to give more time to find and fix any regressions)?

NB: this PR currently still includes a deliberate failure to allow running tests without actually merging it.

**Comment by arielb1** [comment]
```
ERROR:sccache::server: [Error(ProcessError(Output { status: ExitStatus(ExitStatus(256)), stdout: "", stderr: "/checkout/src/llvm/lib/CodeGen/SelectionDAG/FastISel.cpp: In member function \'bool llvm::FastISel::selectIntrinsicCall(const llvm::IntrinsicInst*)\':\n/checkout/src/llvm/lib/CodeGen/SelectionDAG/FastISel.cpp:1099:3: error: duplicate case value\n   case Intrinsic::assume:\n   ^\n/checkout/src/llvm/lib/CodeGen/SelectionDAG/FastISel.cpp:1095:3: error: previously used here\n   case Intrinsic::assume:\n   ^\n" }), State { next_error: None })] 	FastISel.cpp.o
```

**Comment by TimNN** [comment]
Things are looking good, I'd say: The first appveyor bot (64bit MinGW deploy) ran succesfully (and hit the `exit 1` I put a the and, which cancelled the other bots).

Should we try again with `finish-fast` set to `false` in `appveyor.yml`?

**Comment by arielb1** [comment]
@TimNN

You can add a `echo YAY; sleep 10000` to get results on all the bots

**Comment by TimNN** [comment]
@arielb1: Good idea, I hadn't though of that (although we probably want to do that in a loop so the builds aren't canceled from a lack of output)

**Comment by TimNN** [comment]
@bors r+

Lets test this again, this time with an infinite sleep loop at the end so that tests aren't prematurely canceled.

**Comment by alexcrichton** [comment]
Looking great as usual @TimNN, thanks so much for sticking with this!

A few requests for the LLVM submodule:

* Could you expand the commit message for https://github.com/rust-lang/llvm/commit/4275d89fe46b5d025361f27c7988528d11cd6e94?
* Could you mention the breakage seen in https://github.com/rust-lang/llvm/commit/20acd7068bf7a56d2086c64255bbe4f503d727d8? (notably @vadimcn's comment, or a link to that would be great)
* Could you remove the PR merge commits? (should be ok to just cherry-pick the actual commits)

Dropping the jemalloc bits should be fine, I'm dubious that optimization ever kicked in anyway.

I'd also idly muse that there's no real reason to use the literal `release_40` branch. We could reduce the stack of patches by a lot I think by just using LLVM tip (as of like right now). I think that'd cause problems with emscripten though, right? (different merge bases) It seems like we should also stick with the current merge base as you've already done all the testing. You should mostly disregard this paragraph.

The compiler-rt submodule looks a little suspicious though, so I just wanted to confirm. I think the following PRs are missing from the `rust-2017-04-13`, was that intentional? (I don't recall upstreaming many of these...)

* https://github.com/rust-lang/compiler-rt/pull/24 - UB with INT_MIN in an intrinsic
* https://github.com/rust-lang/compiler-rt/pull/26 - was this fixed upstream in LLVM, right?
* https://github.com/rust-lang/compiler-rt/pull/27 - infinite recursion on FreeBSD in an intrinsic
* https://github.com/rust-lang/compiler-rt/pull/28 - fixing https://github.com/rust-lang/compiler-rt/pull/27 I think?
* https://github.com/rust-lang/compiler-rt/pull/31 - more mystery on sparc?


> One open question remains: Given that the next beta is cut in 11 days, should we postpone merging this until after the beta (to give more time to find and fix any regressions)?

Yeah if you're ok with it I'd prefer to stay conservative here and wait until after beta is branched (should happen late next week) before merging this. This looks like it's got a lot of potential for accidental regressions! 

Although it may be good to at some point categorize the number of bugs this (the upgrade to LLVM 4.0) fixes. If it fixes enough bugs we may wish to land it for beta and deal with the backports.

**Comment by TimNN** [comment]
> * Could you expand the commit message for rust-lang/llvm@4275d89?

Sure (this has also been upstreamed to emscripten).

> * Could you mention the breakage seen in rust-lang/llvm@20acd70? (notably @vadimcn's comment, or a link to that would be great)

Of course. I'll add a link to @vadimcn's comment to the comment added in that commit.

> * Could you remove the PR merge commits? (should be ok to just cherry-pick the actual commits)

That's what I had originally when @arielb1 requested on IRC I use the merge commits so that the original PR number was linked from the cherry picks. Although I can easily go back to the non merge commit version.

> The compiler-rt submodule looks a little suspicious though.

Ugh. Yeah, thanks for the reminder, I honestly didn't even look at compiler-rt submodule.

>> One open question remains: Given that the next beta is cut in 11 days, should we postpone merging this until after the beta (to give more time to find and fix any regressions)?
>
> Yeah if you're ok with it I'd prefer to stay conservative here and wait until after beta is branched (should happen late next week) before merging this. This looks like it's got a lot of potential for accidental regressions!

Yeah I'm totally fine with postponing (the bitrot potential for this PR is luckily pretty low).

**Comment by alexcrichton** [comment]
> I use the merge commits so that the original PR number was linked from the cherry picks

That actually sounds very reasonable, let's leave as is.

**Comment by frewsxcv** [comment]
> @bors r+
> 
> Lets test this again, this time with an infinite sleep loop at the end so that tests aren't prematurely canceled.

Instead of holding up the queue, you could also just conditionally turn on whichever builders you want for this pull request by temporarily adding `ALLOW_PR=1` here https://github.com/rust-lang/rust/blob/master/.travis.yml#L15-L49

**Comment by TimNN** [comment]
@frewsxcv: Yeah, I know, but right now the most important bit is appveyor (and seeing if the latest llvm backports broke any of the other bots), so r+ is the best way to go here as far as I know.

**Comment by arielb1** [comment]
- #40546

@bors retry

**Comment by retep998** [comment]
That looks like a resounding success to me. Build died at exactly 3 hours when the timeout was hit.

**Comment by TimNN** [comment]
> That looks like a resounding success to me. Build died at exactly 3 hours when the timeout was hit.

Yay! I checked all the logs and they indeed show that all builds were successful :tada:

**Comment by Kixunil** [comment]
@TimNN did someone hire you to do this or did you do it in your free time? If someone hired you, could you disclose your employer?

**Comment by TimNN** [comment]
@Kixunil: Nope, not being payed for this. Just started it and stubbornly stuck with it.

**Comment by Kixunil** [comment]
Awesome! Thank you very much! I look forward to being able to target AVR... :)

**Comment by copumpkin** [comment]
This is great, thanks! As someone not familiar with LLVM release process, is there an ETA on when this will end up in a release?

**Comment by TimNN** [comment]
> I look forward to being able to target AVR.

Yeah, wanting to experiment with rust on ARM (without having to build a custom compiler) was one the motivating factors in me starting this.

@copumpkin:

The current plans are as follows, as far as I am aware:

This will be available on **nightly** once the next beta has branched (in about a week) and then make its ways to **beta** in about 7 weeks and to **stable** in about three months.

**Comment by alexcrichton** [comment]
@TimNN congratulations! That's awesome news that we've got green lights across the board (and warm sccache caches now).

Did you wanna take care of the last few compiler-rt patches? I don't mind taking care of them either if you've run out of time for this :)

**Comment by TimNN** [comment]
@alexcrichton: I can take care of the compiler-rt patches, although probably not until this weekend, which I guess is fine given that we want to wait until after the beta has branched before we merge this.

If you want them done earlier I won't mind if you do them.

**Comment by alexcrichton** [comment]
Nah sounds good to me!

**Comment by mrhota** [comment]
@alexcrichton @TimNN what's this about compiler-rt patches? It seems like most work on this issue is happening in other repos, and perhaps on non-master branches, but there's nothing written down anywhere that I can see. Could y'all provide links or relevant information so we can see what work went into this issue?

**Comment by alexcrichton** [comment]
@mrhota oh you can find the list of patches here: https://github.com/rust-lang/compiler-rt/commits/rust-llvm-2016-07-18

(note that's the branch corresponding to the commit of the compiler-rt submodule in the rust-lang/rust repo)

**Comment by TimNN** [comment]
@alexcrichton: I think I incorporated all your feedback:

* The `to_string` commit / backport is no longer necessary, since it's part of the new emscripten merge (see below)
* I updated the comment regarding the `dllexport`
* I pushed the five PR's mentioned to the `compiler-rt` branch (I also had a quick look over the others `compiler-rt` PR's and didn't find any others that seemed relevant and weren't upstreamed).

Since I had to rebase the LLVM submodule anyway to edit the commit message, I:

* cleaned up the older LLVM submodule commits as well, so that every rust modification now has a merge commit with pull request number (with two old exceptions).
* updated the llvm base to 4.0.1
* update the fastcomp base to 1.37.10

---

The fast fail is still active, so lets test this PR again:

@bors r+

File: src/librustc_llvm/build.rs [hunk 1]
```diff
@@ -265,4 +265,8 @@ fn main() {
     if target.contains("windows") {
         println!("cargo:rustc-link-lib=ole32");
     }
+    if target.contains("windows-gnu") {
+        println!("cargo:rustc-link-lib=static-nobundle=gcc_s");
+        println!("cargo:rustc-link-lib=static-nobundle=pthread");
```
Comment (retep998) [inline src/librustc_llvm/build.rs]: Yay, it's useful!

**Comment by TimNN** [comment]
@bors retry

* ar.exe failure

**Comment by TimNN** [comment]
Yay, looks like all the builds timed out again, so things seem to be good to go. (I didn't verify all the logs this time).

**Comment by alexcrichton** [comment]
@TimNN looks great to me!

I hope to branch beta later today, so want to pull out the fast-fail? I'll r+ this after the beta is branched.

I'd also like to reiterate that you're at least my own personal "Rust Hero of the last N Months" where N is two and counting. If we delay this for 3 more days then it'll be a 2+ month PR!

**Comment by TimNN** [comment]
@alexcrichton: I removed the always fail commit.

---

> I'd also like to reiterate that you're at least my own personal "Rust Hero of the last N Months" where N is two and counting. If we delay this for 3 more days then it'll be a 2+ month PR!

Thanks a lot! All the positive encouragement and feedback has helped a lot in keeping me motivated to work on the upgrade :).

**Comment by Kixunil** [comment]
> I'd also like to reiterate that you're at least my own personal "Rust Hero of the last N Months"

Mine too! :)

**Comment by alexcrichton** [comment]
@bors: r+

Beta's branched, let's do this!

**Comment by brson** [comment]
Thanks for slogging through this @TimNN.

**Comment by BatmanAoD** [comment]
Congratulations @TimNN!

**Comment by DemiMarie** [comment]
Thank you @TimNN!

**Comment by michaelwoerister** [comment]
:tada:

**Comment by pkphilip** [comment]
Wow! Thanks a lot @TimNN! That is some effort!

**Comment by Kixunil** [comment]
I've just noticed that README mentions clang 3.x. Shouldn't this be updated?

**Comment by rkruppe** [comment]
@Kixunil That part of the readme is about the C and C++ compiler used for compiling C and C++ dependencies during the build, not about the LLVM version.

**Comment by Kixunil** [comment]
@rkruppe I guess I'm too hungry and tired. Thank you for pointing that out! :)
