### PR TITLE
Modify MIR building to drop repeat expressions with length zero

### LINKED ISSUE #74836: Initializing a zero-length array leaks the initializer
This bug was [reported on StackOverflow today](https://stackoverflow.com/questions/63104426/creating-an-array-of-size-0-consumes-value-forgetting-it). Filipe Rodrigues noticed that the initializer of a zero-length array is leaked:

```rust
#[derive(PartialEq, Debug)]
struct A;

impl Drop for A {
    fn drop(&mut self) {
        println!("Dropping A");
    }
}

fn main() {
    let vec: Vec<A> = vec![];
    let a = A;
    assert_eq!(vec, [a; 0]);
}
```
The code above does not run `drop()` for `a`, while I'd expect that it should. According to a comment by @mcarton, this regression occurred between Rust 1.11.0 and 1.12.0, i.e. when MIR code generation was enabled by default.

### PR DESCRIPTION
**Pull request by JakobDegen**
Closes #74836 .

Previously, when a user wrote `[foo; 0]` we used to simply leak `foo`. The goal is to fix that. This PR changes MIR building to make `[foo; 0]` equivalent to `{ drop(foo); [] }` in all cases. Of course, this is a breaking change (see below). A crater run did not indicate any regressions though, and given that the previous behavior was almost definitely not what any user wanted, it seems unlikely that anyone was relying on this.

Note that const generics are in general unaffected by this. Inserting the extra `drop` is only meaningful/necessary when `foo` is of a non-`Copy` type, and array repeat expressions with const generic repetition count must always be `Copy`.

Besides the obvious change to behavior associated with the additional drop, there are three categories of examples where this also changes observable behavior. In all of these cases, the new behavior is consistent with what you would get by replacing `[foo; 0]` with `{ drop(foo); [] }`. As such, none of these give the user new powers to express more things.

**No longer allowed in const (breaking)**:

```rust
const _: [String; 0] = [String::new(); 0];
```

This compiles on stable today. Because we now introduce the drop of `String`, this no longer compiles as `String` may not be dropped in a const context.

**Reduced dataflow (non-breaking)**:

```rust
let mut x: i32 = 0;
let r = &x;
let a = [r; 0];
x = 5;
let _b = a;
```

Borrowck rejects this code on stable because it believes there is dataflow between `a` and `r`, and so the lifetime of `r` has to extend to the last statement. This change removes the dataflow and the above code is allowed to compile.

**More const promotion (non-breaking)**:

```rust
let _v: &'static [String; 0] = &[String::new(); 0];
```

This does not compile today because `String` having drop glue keeps it from being const promoted (despite that drop glue never being executed). After this change, this is allowed to compile.

### Alternatives

A previous attempt at this tried to reduce breakage by various tricks. This is still a possibility, but given that crater showed no regressions it seems unclear why we would want to introduce this complexity.

Disallowing `[foo; 0]` completely is also an option, but obviously this is more of a breaking change. I do not know how often this is actually used though.

r? @oli-obk

### CODE REVIEW

**Comment by oli-obk** [comment]
cc @RalfJung we're preventing to promote `[String::new(); 0]` while fixing it that the element is actually dropped instead of leaked. We avoid this by not changing the mir (in a meaningful way) until after promotion and before borrowck.

**Comment by oli-obk** [comment]
Please reference the bug in the main post and re-explain what the problem is and what code is now changed, as we'll want to nominate this for the lang team. Technically this is a breaking change after all.

Running it through crater, too

@bors try

**Comment by RalfJung** [comment]
> cc @RalfJung we're preventing to promote `[String::new(); 0]` while fixing it that the element is actually dropped instead of leaked. We avoid this by not changing the mir (in a meaningful way) until after promotion and before borrowck.

I think we should break code like in "snippet A".

What is the problem with allowing code like "snippet B"?

> and then immediately after borrowck changing it to this if we are in a non-const context:

Honestly, this sounds like a terrible hack that will come to bite us later.

**Comment by JakobDegen** [comment]
I don't have strong opinions on breaking snippet A, mostly because I don't have enough experience with how these decisions are made.

> What is the problem with allowing code like "snippet B"?

Quoting [the reference](https://doc.rust-lang.org/stable/reference/destructors.html#constant-promotion):

> Promotion of a value expression to a 'static slot occurs when the expression could be written in a constant and borrowed, and that borrow could be dereferenced where the expression was originally written, without changing the runtime behavior.

I'm interpreting this to mean that `&expr` should const promote if `&*const { &expr }` would work. In the case of `&[String::new(); 0]`, `const { &[String::new(); 0] }` would not be allowed, and so it should not const promote.

> Honestly, this sounds like a terrible hack that will come to bite us later.

Agreed. That being said, I'm going to claim that given how horrible the requirements that have emerged are, our options are either to change the requirements or have a terribly hacky implementation. I'm honestly somewhat surprised that the requirements under which I was operating could be implemented with this little code

**Comment by RalfJung** [comment]
> I don't have strong opinions on breaking snippet A, mostly because I don't have enough experience with how these decisions are made.

If crater doesn't find a case of this happening in the wild, the teams are usually on-board with doing the breaking change. We had a bunch of those around promotion last year.

> I'm interpreting this to mean that &expr should const promote if &*const { &expr } would work. In the case of &[String::new(); 0], const { &[String::new(); 0] } would not be allowed, and so it should not const promote.

I'd be shocked if that was the only such example.

Promotion is a lot more subtle than that, e.g. when you write `&(A+B)`, the addition gets promoted but the assertion in case of overflow remains unpromoted. With `&something[idx]` we sometimes promote the `&something` but leave the indexing to runtime (because the index is dynamic). This list probably goes on.

Also see [this document](https://github.com/rust-lang/const-eval/blob/master/promotion.md), but I don't think it is complete either, unfortunately.

At this point, as far as I am concerned, promotion is mostly something we keep around to keep old code working. Anything more complicated than `&42` works "by accident". My biggest concern is keeping the promotion *implementation* as simple as possible, since it has been a huge source of pain (and bugs, even some soundness bugs) in the past.

If there is a nice way to prevent `&[String::new(); 0]` from being promoted, sure. But first constructing "wrong" MIR and then ad-hoc patching it later?!? That's not worth it.

> Agreed. That being said, I'm going to claim that given how horrible the requirements that have emerged are, our options are either to change the requirements or have a terribly hacky implementation. I'm honestly somewhat surprised that the requirements under which I was operating could be implemented with this little code

So let's change those requirements then. :)

**Comment by JakobDegen** [comment]
Yeah, this makes sense to me. Possibly we should cancel the crater run, pending a T-Lang response?

**Comment by oli-obk** [comment]
@craterbot cancel

**Comment by oli-obk** [comment]
@craterbot abort

**Comment by oli-obk** [comment]
We can just crater the version that breaks A and allows B (so basically your original one 😆 ) and then present the result to the lang team. It's easier to talk about if we have data

**Comment by JakobDegen** [comment]
The new version breaks A and allows B. I took some extra time to learn about how drops work in MIR building, and I believe this should do the right thing. The diagnostic on snippet A leaves a little to be desired, but that probably shouldn't block the crater run.

One interesting thing to note is that this change teaches MIR that there is no dataflow dependency between `foo` and `bar` in `let foo = [bar; 0];` That seems like what we want, since it is after all true, but this is at least a little orthogonal to the drop stuff

**Comment by RalfJung** [comment]
> One interesting thing to note is that this change teaches MIR that there is no dataflow dependency between foo and bar in let foo = [bar; 0]; That seems like what we want, since it is after all true, but this is at least a little orthogonal to the drop stuff

FWIW, if there is a nice way to pretend to dataflow that such a dependency exists, I wouldn't be opposed to that -- as long as it can be added during MIR building, not as a post-doc semantics-changing MIR-patching transformations.

**Comment by oli-obk** [comment]
> FWIW, if there is a nice way to pretend to dataflow that such a dependency exists, I wouldn't be opposed to that -- as long as it can be added during MIR building, not as a post-doc semantics-changing MIR-patching transformation.

I think that would be the effect if we didn't do the patch-up but generated the final MIR directly on mir building.

**Comment by JakobDegen** [comment]
> I think that would be the effect if we didn't do the patch-up but generated the final MIR directly on mir building.

Hmm, how so? What would the MIR look like?

**Comment by oli-obk** [comment]
Hmm... good point, the place where the drop happens is very relevant here. Yea, I guess we go with the current impl and just accept the slight oddity in promotion (but the user could have written the same code anyway).

**Comment by oli-obk** [comment]
@craterbot check

**Comment by oli-obk** [comment]
Possible regressions:
* https://github.com/JakeDawkins/graphql-client-302-repro
* https://github.com/zeroisme/rusic-relm
* rttrust 0.1.3

Please run master and your PR against these crates to check if the regressions are spurious

**Comment by JakobDegen** [comment]
I tested all three. The failures on `rttrust` and `rusic-relm` did not reproduce locally. The other one did - I took a look with GDB and it's a case of a known bug in that library: graphql-rust/graphql-client#370 . I have no idea why this change causes it to trigger though. I'll investigate a little more

**Comment by oli-obk** [comment]
I don't think your PR is related. I'm guessing the stack overflow just accidentally didn't happen on master? That repro should be failing on master afaict, as it uses graphql 0.9 which definitely has this bug.

A stack overflow is UB after all, so it could be that it just happened to abort "gracefully"

**Comment by JakobDegen** [comment]
I've updated the PR description to reflect this version of things. Should this be re-nominated for T-Lang now?

**Comment by oli-obk** [comment]
Nominating for T-lang consideration. The description is in the main comment of this PR. The TLDR: `[x; 0]` was not dropping the `x`, it now is. This is a breaking change, with no regressions found.

If you (T-lang) got a few extra minutes in your meeting (I know, who am I kidding), this kind of PR is what I'd expect the types team to handle in the future without checking back with you unless it is deemed purely a language change. The relevant section of the RFC is https://github.com/jackh726/rfcs/blob/types-team/text/0000-types-team.md#bug-in-the-type-checker

Does that sound right to you?

**Comment by RalfJung** [comment]
> A stack overflow is UB after all, so it could be that it just happened to abort "gracefully"

It's not, we have the guard page for that. (It'd be quite bad if you could trigger UB from safe code via a stack overflow.)

**Comment by nikomatsakis** [comment]
@rfcbot fcp merge

We discussed in the @rust-lang/lang meeting today. Everybody felt this was a clear bug fix, so moving to merge.

**Comment by scottmcm** [comment]
Agreed this is a bug that should just be fixed :+1:

@rfcbot reviewed

**Comment by scottmcm** [comment]
Actually, one request: if there isn't already one, can you add a test like the following, just to be sure?
```rust
fn foo() -> [u8; 0] {
    let x: u8;
    [x; 0] // ERROR: use of possibly-uninitialized variable: `x`
}
```

(I'm pretty sure it'll pass, as from what I can tell this PR keeps that error, but I could imagine different choices in this area which would let that through.)

**Comment by JakobDegen** [comment]
Thanks for the suggestion @scottmcm , added that test. Also rebased

**Comment by JakobDegen** [comment]
Hmm, this is sort of messy. The problem here is this: In the case where it's a zero repeat, we cannot introduce a temporary because then we won't know if the original operand was a const anymore. At the same time, in the case of a non-zero repeat we must introduce the temporary, as otherwise the test Scott suggested above fails.

I could implement this by using `NeedsTemporary::No` at first, then checking if its a const, and introducing the temporary if not. But it seems bad to depend on `NeedsTemporary::No` actually not generating a temporary, since the intent seems to be for this to only be an "optimization hint" or such. @oli-obk , any advice on how to proceed?

File: src/test/ui/drop/repeat-drop.rs [hunk 1]
```diff
@@ -0,0 +1,69 @@
...
+
+struct DropPanic;
+
+impl Drop for DropPanic {
+    fn drop(&mut self) {
+        panic!()
+    }
+}
+
+fn a() {
```
Comment (oli-obk) [inline src/test/ui/drop/repeat-drop.rs:26]: Please duplicate `a` and `b` with versions that use `[DropChecker(1); N]` and that use `[DROP_CHECKER; N]` where `const DROP_CHECKER: DropChecker = DropChecker(1);`

**Comment by oli-obk** [comment]
> any advice on how to proceed?

Note sure, we need to figure out the intended behaviour first

> The problem here is this: In the case where it's a zero repeat, we cannot introduce a temporary because then we won't know if the original operand was a const anymore. At the same time, in the case of a non-zero repeat we must introduce the temporary, as otherwise the test Scott suggested above fails.

So the main problem with unconditionally inserting is that we'd not figure out that `[SOME_CONST; 5]` is legal, while inlining the initializer of `SOME_CONST` would not be legal here? We could mark the inserted local via its `LocalDecl` as "is const" so that using the local can be treated just like using `Operand::Const`

**Comment by JakobDegen** [comment]
It's not about it being legal, it's about `[SOME_CONST; 0]` not dropping `SOME_CONST`. In other words, these two examples do not have the same behavior:

```rust
let _x = [SOME_CONST; 0];
// vs
let temp = SOME_CONST;
let _x = [temp; 0];
```

Because the second drops an instance of `SOME_CONST` while the first does not.

Tracking this information via local decls is indeed an option, but honestly seems like a hack too. I'll try it tomorrow and see how it goes

**Comment by scottmcm** [comment]
@rfcbot concern uncertain-intended-behaviour

Based on https://github.com/rust-lang/rust/pull/95953#issuecomment-1127295884, I'm worried that the current discussion is less of an implementation question than I initially thought.  Is there an uncertain spec question here?

**Comment by JakobDegen** [comment]
Yeah, that's a fair point actually. At the very least this is a complication that wasn't mentioned before the FCP. Specifically, what should this code do?

```rust
const HAS_DROP: HasDrop = HasDrop::new();

[HAS_DROP; 0]
```

We currently have a test that checks that this does not drop `HAS_DROP`. Is that the desired behavior? If so, for what expressions should this apply?

Imo, the only reasonable answers are 1) yes, this is the desired behavior since that `0` can actually be a const generic, and 2) it should be the behavior in all contexts where that `0` would be allowed to be `2`, even if `HasDrop` is not `Copy`

**Comment by oli-obk** [comment]
> If so, for what expressions should this apply?

This was discussed when it was allowed that non-copy types can be used as repeat expressions iff that repeat element expression is just naming a constant. The lang team made an explicit decision on that in https://github.com/rust-lang/rust/pull/79270#issuecomment-740877885

**Comment by oli-obk** [comment]
> I'm worried that the current discussion is less of an implementation question than I initially thought. Is there an uncertain spec question here?

This is just an impl question I believe. We already specced `[CONST; 0]` to be equivalent to `[]`: https://github.com/rust-lang/rust/pull/79270#issuecomment-740877885

So we just need to figure out how to make this PR not break that by adjusting the impl

**Comment by RalfJung** [comment]
But `[CONST; N]` where `N == 0` should probably also be equivalent to `[CONST; 0]`, right?

**Comment by oli-obk** [comment]
yea... the current fix only addresses the nongeneric case. This is avoided for non-const repeat expressions, as they will rightfully error about the repeat element not being `Copy` (`N` could larger than 1 after all).

The only alternative that I see to to using runtime checks (that are guaranteed to get optimized out before or during LLVM) on the generic length to figure out whether to drop, is to always generate a temporary, even for zero length repeat expressions, making `[FOO; 0]` equivalent to `[Foo; 0]`

As mentioned, doing this naively will break `[FOO; 2]` from working at all, as now there's a temporary instead of an `Operand::Constant` for the repeat element.

That said, the amount of headache that `Operand::Constant` is giving us around `Drop` types makes me wonder if we should scrap it entirely in favour of an `Rvalue::Constant` and just always create temporaries. These temporaries could get markers, just like we add markers to the temporary for getting a reference to a static item. Doesn't seem more hacky than the status quo to me.

**Comment by scottmcm** [comment]
> The lang team made an explicit decision on that in [#79270 (comment)](https://github.com/rust-lang/rust/pull/79270#issuecomment-740877885)

Thanks, oli; that's a good point.  We discussed this in the lang meeting today, and agreed we can consider fixing it an implementation concern, where we trust you'll find a good answer, and thus I'll

@rfcbot resolve uncertain-intended-behaviour

**Comment by JakobDegen** [comment]
> yea... the current fix only addresses the nongeneric case. This is avoided for non-const repeat expressions, as they will rightfully error about the repeat element not being Copy (N could larger than 1 after all).
> 
> The only alternative that I see to to using runtime checks (that are guaranteed to get optimized out before or during LLVM) on the generic length to figure out whether to drop, is to always generate a temporary, even for zero length repeat expressions, making [FOO; 0] equivalent to [Foo; 0]

I don't even think that runtime checks would help. `[FOO; 0]` and `[Foo; 0]` (const and non-const version) straight up have different behavior, and we have to be able to distinguish them at MIR building time. How difficult would it be to add a contract to `.as_operand()` that promises that if the HIR expression is a const block or named constant (and we have `NeedsTemporary::No`), then no temporary will be added and `Operand::Const` will be returned?

**Comment by RalfJung** [comment]
> [FOO; 0] and [Foo; 0] (const and non-const version) straight up have different behavior

I thought the main discussion was about `[FOO; 0]` vs `[FOO; N]` though? We cannot do anything during MIR building where we special-case a certain length, because the length might be generic.

**Comment by JakobDegen** [comment]
Ehh, not sure if there's a "main discussion," we seem to be having two at the same time :laughing: . Let me summarize briefly. `N` is a const generic, `FOO` is a named constant (or const block), and `bar` is an expression of a non-copy type:

 1. `[FOO; 1]` should obviously not emit any drops.
 2. `[FOO; 0]` should not emit any drops as decided by T-Lang previously.
 2. `[FOO; N]` should also not emit any drops, which is consistent with the behavior of `[FOO; N]` for any particular value of `N`.
 3. `[bar; 1]` should obviously not emit any drops.
 4. `[bar; N]` is a compiler error
 5. `[bar; 0]` should emit a drop.

The problem that I am running into is not that there is some `X` for which `[X; N]` for `N == 0` is inconsistent with `[X; 0]`. Instead, the problem that I am running into is that `[FOO; 0]` has different semantics from `[bar; 0]` (one emits a drop and one does not). This is absolutely something we can detect at MIR building time in principle, the question is only how to do it.

I proposed above that we add a guarantee to `.as_operand(NeedsTemporary::No)` which promises that it will hand back an `Operand::Const` if the operand is a named const/const block. Not sure if this is the right way forward though.

**Comment by oli-obk** [comment]
If we rename the `NeedsTemporary` enum to something like `InsertTemporary` and add some docs as you suggested, then that seems ok. The only other alternative I see is adding a special `as_repeat_operand` that replicates some of `as_operand` to be more explicit. Maybe that could make sense to keep all the logic contained in operand.rs and not have to reason about it in other files

**Comment by JakobDegen** [comment]
Ended up reading more code and taking a different approach that uses `Category::of` directly. That seemed like the cleanest thing to do, let me know if you'd like to see something else though Oli.

@scottmcm if you want to take another look, there's now a sequence of six tests in `repeat-drop.rs` (`value_zero` through `const_generic_one`) that should verify that everything has the desired behavior.

**Comment by oli-obk** [comment]
Yea, this is much better than the alternatives we had discussed before.

@bors r+

**Comment by JohnTitor** [comment]
Failed in rollup: https://github.com/rust-lang/rust/pull/97347#issuecomment-1135718551
Needs to ignore some targets on the tests

@bors retry r-

**Comment by JakobDegen** [comment]
Added a bunch of ignore directives, stolen from `src/test/ui/runtime/rt-explody-panic-payloads.rs`
