### PR TITLE
Promoteds can contain raw pointers, but these must still only point to immutable allocations

### LINKED ISSUE #67601: Regression in Servo: "internal compiler error: mutable allocation in constant"
https://community-tc.services.mozilla.com/tasks/bdytAYuMTdWK1kbybZ6FWA/runs/0/logs/https%3A%2F%2Fcommunity-tc.services.mozilla.com%2Fapi%2Fqueue%2Fv1%2Ftask%2FbdytAYuMTdWK1kbybZ6FWA%2Fruns%2F0%2Fartifacts%2Fpublic%2Flogs%2Flive.log#L1943

```rust
   --> /repo/target/debug/build/script-a3d7e9e184a37789/out/Bindings/ANGLEInstancedArraysBinding.rs:852:61
    |
852 |   const sMethods_specs: &'static [&'static[JSFunctionSpec]] = &[
    |  _____________________________________________________________^
853 | | &[
854 | |     JSFunctionSpec {
855 | |         name: b"drawArraysInstancedANGLE\0" as *const u8 as *const libc::c_char,
...   |
882 | |
883 | | ];
    | |_^
```

(Many other occurrences)

```rust
error: internal compiler error: mutable allocation in constant
    --> /repo/target/debug/build/script-a3d7e9e184a37789/out/Bindings/XRWebGLLayerBinding.rs:1088:64
     |
1088 |   const sAttributes_specs: &'static [&'static[JSPropertySpec]] = &[
     |  ________________________________________________________________^
1089 | | &[
1090 | |     JSPropertySpec {
1091 | |         name: b"context\0" as *const u8 as *const libc::c_char,
...    |
1203 | |
1204 | | ];
     | |_^
thread 'rustc' panicked at 'no errors encountered even though `delay_span_bug` issued', src/librustc_errors/lib.rs:349:17
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:77
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1057
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1426
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:195
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:215
  10: rustc_driver::report_ice
  11: <alloc::boxed::Box<F> as core::ops::function::Fn<A>>::call
             at /rustc/a9c1c04e986dbf610be8cbe6a8107f90b4db61ce/src/liballoc/boxed.rs:1029
  12: proc_macro::bridge::client::<impl proc_macro::bridge::Bridge>::enter::{{closure}}::{{closure}}
             at /rustc/a9c1c04e986dbf610be8cbe6a8107f90b4db61ce/src/libproc_macro/bridge/client.rs:305
  13: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:476
  14: std::panicking::begin_panic
  15: <rustc_errors::HandlerInner as core::ops::drop::Drop>::drop
  16: core::ptr::real_drop_in_place
  17: core::ptr::real_drop_in_place
  18: core::ptr::real_drop_in_place
  19: rustc_interface::interface::run_compiler_in_existing_thread_pool
  20: std::thread::local::LocalKey<T>::with
  21: scoped_tls::ScopedKey<T>::set
  22: syntax::with_globals
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
error: internal compiler error: unexpected panic
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
note: rustc 1.42.0-nightly (a9c1c04e9 2019-12-24) running on x86_64-unknown-linux-gnu
note: compiler flags: -C debuginfo=2 -C link-args=-fuse-ld=gold --crate-type rlib
note: some of the compiler flags provided by cargo are hidden
query stack during panic:
end of query stack
error: could not compile `script`.
```

The crate uses `#![feature(const_fn)]`.

Example of one of the affected `const` items:

```rust
const sMethods_specs: &'static [&'static[JSFunctionSpec]] = &[
&[
    JSFunctionSpec {
        name: b"getViewport\0" as *const u8 as *const libc::c_char,
        call: JSNativeWrapper { 
            // `generic_method` is a free function
            op: Some(generic_method),
            // getViewport_methodinfo is a const item
            info: &getViewport_methodinfo as *const _ as *const JSJitInfo
        },
        nargs: 1,
        flags: (JSPROP_ENUMERATE) as u16,
        selfHostedName: 0 as *const libc::c_char
    },
    JSFunctionSpec {
        name: 0 as *const libc::c_char,
        call: JSNativeWrapper { 
            op: None, 
            info: 0 as *const JSJitInfo
        },
        nargs: 0,
        flags: 0,
        selfHostedName: 0 as *const libc::c_char
    }
]
];
```

Definitions of types involved:

```rust
pub struct JSFunctionSpec {
    pub name: *const i8,
    pub call: JSNativeWrapper,
    pub nargs: u16,
    pub flags: u16,
    pub selfHostedName: *const i8,
}
pub struct JSNativeWrapper {
    pub op: Option<unsafe extern "C" fn(*mut JSContext, u32, *mut Value) -> bool>,
    pub info: *const JSJitInfo,
}
pub struct JSJitInfo {
    pub call: *const c_void,
    pub protoID: u16,
    pub depth: u16,
    pub _bitfield_1: u32,
}
```

Regression range:

git log --merges --oneline 9ae6cedb8...a9c1c04e9 
a9c1c04e986 Auto merge of #67241 - mark-i-m:simplify-borrow_check-3, r=matthewjasper
f6dca76be55 Auto merge of #66221 - ohadravid:doc-constants, r=Dylan-DPC
84d8f9ddd38 Auto merge of #67579 - RalfJung:miri, r=RalfJung
625375400cd Auto merge of #67575 - Centril:rollup-feikoir, r=Centril
a76d67f22f0 Rollup merge of #67572 - aidanhs:aphs-choco-direct-cdn, r=Mark-Simulacrum
20d5df91f46 Rollup merge of #67569 - Mark-Simulacrum:opt-char-encode, r=oli-obk
75b27ef59cd Rollup merge of #67561 - euclio:remove-description, r=jonas-schievink
a75968a7829 Rollup merge of #67551 - ldm0:E0627, r=Dylan-DPC
d130e8d5509 Rollup merge of #67547 - GuillaumeGomez:cleanup-err-codes, r=Dylan-DPC
07effe18b01 Rollup merge of #67543 - JohnTitor:regression-tests, r=Centril
1ac8fc76d4b Rollup merge of #67337 - oli-obk:no_mut_static_ref_from_const, r=RalfJung
a4cd03dee2b Auto merge of #66296 - Centril:bindings_after_at-init, r=pnkfelix

The error message appears to be from https://github.com/rust-lang/rust/pull/67337, cc @oli-obk 

If this (modulo ICE vs proper diagnostic) is not a rustc bug, I don’t understand what change we’re supposed to make to this code. I don’t see any heap allocation or mutability happening.

### PR DESCRIPTION
**Pull request by oli-obk**
fixes #67601

r? @RalfJung 

cc @wesleywiser in order to not change behaviour in this PR, const prop uses the constant rules for interning, but at least there's an explicit mode for it now that we can think about this in the future

### CODE REVIEW

File: src/librustc_mir/interpret/intern.rs [hunk 1]
```diff
@@ -319,10 +327,23 @@ pub fn intern_const_alloc_recursive<M: CompileTimeMachine<'mir, 'tcx>>(
...
-                InternMode::Static => {}
-                InternMode::Const | InternMode::ConstBase => {
-                    // If it's not a static, it *must* be immutable.
+            match intern_kind {
+                // Mutable statics may contain mutable allocations even behind relocations
+                InternKind::Static(hir::Mutability::Mut) => {}
+                // Once we get heap allocations we need to revisit whether immutable statics can
+                // refer to mutable (e.g. via interior mutability) allocations.
+                InternKind::Static(hir::Mutability::Not) => {
+                    alloc.mutability = Mutability::Not;
```
Comment (RalfJung) [inline src/librustc_mir/interpret/intern.rs]: Why is this correct, given things like `static FOO: AtomicUsize`, which is mutable? The old code didn't do anything like this, did it?

File: src/librustc_mir/interpret/intern.rs [hunk 2]
```diff
@@ -319,10 +327,23 @@ pub fn intern_const_alloc_recursive<M: CompileTimeMachine<'mir, 'tcx>>(
...
+                }
+                // Raw pointers in promoteds may only point to immutable things so we mark
+                // everything as immutable. Creating a promoted with interior mutability is UB, but
```
Comment (RalfJung) [inline src/librustc_mir/interpret/intern.rs]: *rustc* decides to create a promoted, so this can never be UB. UB is what the *user* has to prove to us. What is their proof obligation here?

File: src/librustc_mir/interpret/intern.rs [hunk 3]
```diff
@@ -344,7 +365,10 @@ pub fn intern_const_alloc_recursive<M: CompileTimeMachine<'mir, 'tcx>>(
         } else if ecx.memory.dead_alloc_map.contains_key(&alloc_id) {
             // dangling pointer
             throw_unsup!(ValidationFailure("encountered dangling pointer in final constant".into()))
-        } else if ecx.tcx.alloc_map.lock().get(alloc_id).is_none() {
+        } else if let Some(_) = ecx.tcx.alloc_map.lock().get(alloc_id) {
+            // FIXME: check if the allocation is ok as per the interning rules as if we interned
+            // it right here.
```
Comment (RalfJung) [inline src/librustc_mir/interpret/intern.rs]: I don't understand this comment.

File: src/librustc_mir/interpret/intern.rs (hunk 2 above)
Comment (oli-obk) [reply src/librustc_mir/interpret/intern.rs]: Well... it would be UB if the user used that raw pointer to write to the memory allocation.

File: src/librustc_mir/interpret/intern.rs (hunk 3 above)
Comment (oli-obk) [reply src/librustc_mir/interpret/intern.rs]: If we encounter an `AllocId` that points to a mutable Allocation, (directly or via relocations in its `Allocation`), we should panic, the static rules should prevent this. We may hit an `AllocId` that belongs to an already interned static, and are thus not interning any further. But since we are also checking things during interning, we should probably continue doing those checks no matter what we encounter.

E.g. this should be unreachable for `InternKind::Promoted` except for allocations created for string and byte string literals.

File: src/librustc_mir/interpret/intern.rs (hunk 1 above)
Comment (oli-obk) [reply src/librustc_mir/interpret/intern.rs]: hmm... I didn't think about that, reverting to the previous logic

File: src/librustc_mir/interpret/intern.rs (hunk 2 above)
Comment (RalfJung) [reply src/librustc_mir/interpret/intern.rs]: So why is it correct to do prpmotion then? The same code must also be UB without the promotion, or else promotion is unsound.

Comment (oli-obk) [reply src/librustc_mir/interpret/intern.rs]: It is UB without and with promotion. All we do here is acknowledge this by making the allocation immutable so llvm puts it into immutable static memory. If the user modifies it at runtime, that's UB

File: src/librustc_mir/interpret/intern.rs (hunk 3 above)
Comment (Centril) [reply src/librustc_mir/interpret/intern.rs]: (This description ^--- should probably be added to the source...)

File: src/librustc_mir/interpret/intern.rs (hunk 1 above)
Comment (oli-obk) [reply src/librustc_mir/interpret/intern.rs]: I adjusted the comment, That situation can never occur, the alloc ids we look at here are never the base allocation's alloc id

File: src/librustc_mir/interpret/intern.rs (hunk 2 above)
Comment (RalfJung) [reply src/librustc_mir/interpret/intern.rs]: That doesn't answer my question. *Why* is it UB without promotion? Where is the UB coming from?

File: src/librustc_mir/interpret/intern.rs (hunk 1 above)
Comment (RalfJung) [reply src/librustc_mir/interpret/intern.rs]: I don't see why these all have to be immutable. For constants that makes sense, but why for statics?

File: src/librustc_mir/interpret/intern.rs [hunk 4]
```diff
@@ -366,6 +369,17 @@ pub fn intern_const_alloc_recursive<M: CompileTimeMachine<'mir, 'tcx>>(
             // dangling pointer
             throw_unsup!(ValidationFailure("encountered dangling pointer in final constant".into()))
         } else if let Some(_) = ecx.tcx.alloc_map.lock().get(alloc_id) {
+            // If we encounter an `AllocId` that points to a mutable `Allocation`,
+            // (directly or via relocations in its `Allocation`), we should panic,
+            // the static rules should prevent this.
```
Comment (RalfJung) [inline src/librustc_mir/interpret/intern.rs]: Why is this? *Pointing to* something mutable seems entirely fine even for a constant, as long as the mutable thing isn't *read*. And we already check that anyway.

The point of the FIXME here seems to be to check more than we currently do, but I don't have the slightest clue what it is that would want to check here.

File: src/librustc_mir/interpret/intern.rs (hunk 2 above)
Comment (RalfJung) [reply src/librustc_mir/interpret/intern.rs]: Also this sounds like we are back to square 1 then: this is exactly what we used to do with `const`, right? We just marked them as immutable unconditionally.

Except now we do it for promoteds, which is much worse. The checks for promoteds should *never* be weaker than the checks for consts. When they are, that means one could write promoteds that desugar to consts that one couldn't write! That's basically unsoundness, as far as I am concerned.

Comment (oli-obk) [reply src/librustc_mir/interpret/intern.rs]: > Why is it UB without promotion? Where is the UB coming from?

mutating through a raw pointer obtained via an immutable reference

File: src/librustc_mir/interpret/intern.rs (hunk 1 above)
Comment (oli-obk) [reply src/librustc_mir/interpret/intern.rs]: the only way you can get a relocation in statics is by using promotion, and promotion only works for immutable references to frozen types. So no matter what you do with that pointer you get, you will never be able to write to the memory without UB

File: src/librustc_mir/interpret/intern.rs (hunk 2 above)
Comment (oli-obk) [reply src/librustc_mir/interpret/intern.rs]: > When they are, that means one could write promoteds that desugar to consts that one couldn't write!

Well... only if you were using the promoted in an unsound way. There's no user visible difference except for the fact that the user likely gets a segfault if they do UB vs they just write to semantically immutable (but not phyiscally immutable) memory.

Comment (oli-obk) [reply src/librustc_mir/interpret/intern.rs]: The only reason this is an issue at all here is that promoteds containing other promoteds don't create explicit promoteds in the `mir::Body`, but again use the "no StorageDead" trick

Comment (oli-obk) [reply src/librustc_mir/interpret/intern.rs]: Otherwise each promoted could at maximum contain one allocation without any nesting, and this one would be immutable by definition. But since we have the nested thing, the allocations need to be mutable so its value can be written.

Essentially

```
pub const FOO: &'static *const i32 = &(&0 as _);
```

is

```rust
pub const FOO: &'static *const i32 = {
    let x = 0;
    let y = &x;
    let z = y as _;
    &z
};
```

where all of `x`, `y`, `z` are temporaries. In order for the miri-engine being able to write to `x`, its allocation needs to be mutable.
Same for `z`, but since `z` is actually the base promoted, we just mark it as immutable without any checks. But then we have to recurse into its relocations to get to `x` and mark that.

I could try to figure out how to promote even inside promoteds. I think that's easy to do, but/since we explicitly do the opposite on purpose to reduce the number of promoteds.

File: src/librustc_mir/interpret/intern.rs (hunk 4 above)
Comment (oli-obk) [reply src/librustc_mir/interpret/intern.rs]: > Why is this? Pointing to something mutable seems entirely fine even for a constant, as long as the mutable thing isn't read. And we already check that anyway.

The static rules say we don't have constants pointing to mutable things, so the dynamic checks should mirror that, right?

File: src/librustc_mir/interpret/intern.rs (hunk 2 above)
Comment (RalfJung) [reply src/librustc_mir/interpret/intern.rs]: > The only reason this is an issue at all here is that promoteds containing other promoteds don't create explicit promoteds in the mir::Body, but again use the "no StorageDead" trick

Ah, that probably explains why when I tried to add an ICE in case there are mutable allocations in a `const` initializer, that failed -- back then promotion inside consts still did the "no `StorageDead`" thing.

> Otherwise each promoted could at maximum contain one allocation without any nesting, and this one would be immutable by definition.

So... can `const` even contain nested allocations currently?

File: src/librustc_mir/interpret/intern.rs (hunk 1 above)
Comment (RalfJung) [reply src/librustc_mir/interpret/intern.rs]: So does promotion still do "no `StorageDead`"?

File: src/librustc_mir/interpret/intern.rs (hunk 2 above)
Comment (RalfJung) [reply src/librustc_mir/interpret/intern.rs]: > mutating through a raw pointer obtained via an immutable reference

Please add a comment with this justification to the code.

File: src/librustc_mir/interpret/intern.rs (hunk 4 above)
Comment (RalfJung) [reply src/librustc_mir/interpret/intern.rs]: The static checks are whatever they happen to be and I don't know why. Ultimately the *dynamic* checks should be the "source of truth" and the static check justified by approxmating the dynamic checks, not the other way around.

So, "the static checks do that" does nothing to answer my question here: why do we want this restriction? (I also still don't really get what it is that you actually want to check here. What does pointing to mutable things have to do with "string and byte string literals"?)

**Comment by SimonSapin** [comment]
Friendly ping: what’s next for this PR? Can I help?

**Comment by oli-obk** [comment]
I just haven't gotten to it. Probably Tuesday or some other day next week

File: src/librustc_mir/interpret/intern.rs (hunk 4 above)
Comment (oli-obk) [reply src/librustc_mir/interpret/intern.rs]: > Ultimately the dynamic checks should be the "source of truth" and the static check justified by approxmating the dynamic checks, not the other way around.

Ok, that makes sense... I'll adjust the comment.

> What does pointing to mutable things have to do with "string and byte string literals"?)

Nothing, this comment is in a code path where immutable allocations also get to, we'd need to check for mutability first, too.

File: src/librustc_mir/interpret/intern.rs (hunk 2 above)
Comment (oli-obk) [reply src/librustc_mir/interpret/intern.rs]: > So... can const even contain nested allocations currently?

Nope

File: src/librustc_mir/interpret/intern.rs (hunk 1 above)
Comment (oli-obk) [reply src/librustc_mir/interpret/intern.rs]: well... `StorageDead` instructions just aren't moved to the promoted MIR, so... 

> does promotion still do "no StorageDead"?

yes, they have always done this

File: src/librustc_mir/interpret/intern.rs (hunk 2 above)
Comment (oli-obk) [reply src/librustc_mir/interpret/intern.rs]: > Please add a comment with this justification to the code.

done

**Comment by oli-obk** [comment]
I addressed all review comments and marked the issue as a stable to nightly regression

File: src/librustc_mir/interpret/intern.rs (hunk 2 above)
Comment (RalfJung) [reply src/librustc_mir/interpret/intern.rs]: > Nope

So... this is unreachable code, then? Might be better to just `bug!`, instead of discussing what we'd do hypothetically if could ever happen?

Comment (oli-obk) [reply src/librustc_mir/interpret/intern.rs]: This comment is talking about promoteds, which can contain nested allocations.

File: src/librustc_mir/interpret/intern.rs [hunk 5]
```diff
@@ -328,10 +336,29 @@ pub fn intern_const_alloc_recursive<M: CompileTimeMachine<'mir, 'tcx>>(
...
+                // everything as immutable. Creating a promoted with interior mutability is UB, but
+                // there's no way we can check whether the user is using raw pointers correctly.
+                // So all we can do is mark this as immutable here.
+                // It is UB to mutate through a raw pointer obtained via an immutable reference.
+                // Since all references and pointers inside a promoted must by their very definition
+                // be created from an immutable reference, mutating though them would be UB.
+                InternKind::Promoted => {
+                    alloc.mutability = Mutability::Not;
+                }
+                InternKind::Constant | InternKind::ConstProp => {
```
Comment (RalfJung) [inline src/librustc_mir/interpret/intern.rs]: Right, I was thinking about this branch here when asking about nested allocations in constants. Isn't this unreachable then?

File: src/librustc_mir/interpret/intern.rs [hunk 6]
```diff
@@ -328,10 +336,29 @@ pub fn intern_const_alloc_recursive<M: CompileTimeMachine<'mir, 'tcx>>(
...
+                }
+                // Raw pointers in promoteds may only point to immutable things so we mark
+                // everything as immutable. Creating a promoted with interior mutability is UB, but
+                // there's no way we can check whether the user is using raw pointers correctly.
+                // So all we can do is mark this as immutable here.
+                // It is UB to mutate through a raw pointer obtained via an immutable reference.
+                // Since all references and pointers inside a promoted must by their very definition
+                // be created from an immutable reference, mutating though them would be UB.
+                InternKind::Promoted => {
+                    alloc.mutability = Mutability::Not;
```
Comment (RalfJung) [inline src/librustc_mir/interpret/intern.rs]: Okay, so this is basically reverting what you did when you added the `delay_span_bug`: turns out that code is basically unreachable, and in the reachable variant we have here, everything is unchanged. Does that make sense?

File: src/librustc_mir/interpret/intern.rs [hunk 7]
```diff
@@ -328,10 +336,29 @@ pub fn intern_const_alloc_recursive<M: CompileTimeMachine<'mir, 'tcx>>(
...
+                // reference type, as that is checked by the type based main interner.
+                InternKind::Static(hir::Mutability::Not) => {
+                    alloc.mutability = Mutability::Not;
+                }
+                // Raw pointers in promoteds may only point to immutable things so we mark
+                // everything as immutable. Creating a promoted with interior mutability is UB, but
+                // there's no way we can check whether the user is using raw pointers correctly.
+                // So all we can do is mark this as immutable here.
+                // It is UB to mutate through a raw pointer obtained via an immutable reference.
+                // Since all references and pointers inside a promoted must by their very definition
```
Comment (RalfJung) [inline src/librustc_mir/interpret/intern.rs]: This needs to consider interior mutability. There is a confusing sentence before that says "creating promoteds with interior mutablity is UB", which (a) I think probably belongs into this second paragraph here, and (b) is the wrong way around -- we have to *prove* that there are no promoteds with interior mutability, whereas UB is what the user has proved to us.

File: src/librustc_mir/interpret/intern.rs (hunk 1 above)
Comment (RalfJung) [reply src/librustc_mir/interpret/intern.rs]: Well you told me recently promotion no longer does this, and works by actually extracting separate MIR the way it does from run-time code. Now you are saying the opposite. I am very confused.

File: src/librustc_mir/interpret/intern.rs [hunk 8]
```diff
@@ -353,7 +380,29 @@ pub fn intern_const_alloc_recursive<M: CompileTimeMachine<'mir, 'tcx>>(
         } else if ecx.memory.dead_alloc_map.contains_key(&alloc_id) {
             // dangling pointer
             throw_unsup!(ValidationFailure("encountered dangling pointer in final constant".into()))
-        } else if ecx.tcx.alloc_map.lock().get(alloc_id).is_none() {
+        } else if let Some(_) = ecx.tcx.alloc_map.lock().get(alloc_id) {
+            // We have hit an `AllocId` that belongs to an already interned static,
+            // and are thus not interning any further.
+
+            // E.g. this should be unreachable for `InternKind::Promoted` except for allocations
```
Comment (RalfJung) [inline src/librustc_mir/interpret/intern.rs]: Why the "E.g." prefix? What is this an example for?

File: src/librustc_mir/interpret/intern.rs [hunk 9]
```diff
@@ -353,7 +380,29 @@ pub fn intern_const_alloc_recursive<M: CompileTimeMachine<'mir, 'tcx>>(
...
+            // created for string and byte string literals, since these are interned immediately
+            // at creation time.
+
+            // FIXME(oli-obk): Since we are also checking things during interning,
+            // we should probably continue doing those checks no matter what we encounter.
```
Comment (RalfJung) [inline src/librustc_mir/interpret/intern.rs]:
```suggestion
            // we could possibly continue doing those checks no matter what we encounter.
```
I am very far from convinced that that would be a reasonable thing to do. We should check the new thing we add, but I don't see why we'd re-check the old things that were already created. For example, we have to ensure that interning a `const` doesn't add anything mutable, but there is nothing fundamentally wrong with having a `const` refer to something mutable that *already existed*.

So, I think "probably" and "we basically have to" are way too strong words here. My intuition is, doing that extra check is wrong.

File: src/librustc_mir/interpret/intern.rs (hunk 6 above)
Comment (oli-obk) [reply src/librustc_mir/interpret/intern.rs]: yes

File: src/librustc_mir/interpret/intern.rs (hunk 9 above)
Comment (oli-obk) [reply src/librustc_mir/interpret/intern.rs]: > re-check the old things that were already created. 

Because the types at which we are checking may have changed. If you transmuted a pointer to an already interned allocation, you may have changed the way the data should get validated

File: src/librustc_mir/interpret/intern.rs (hunk 1 above)
Comment (oli-obk) [reply src/librustc_mir/interpret/intern.rs]: promotion in constants and statics used to just drop the `StorageDead` markers. Now it actually extracts a real promoted, but that promoted may contain interior promoteds that again use the `StorageDead` trick.

So in `const X: &'static i32 = &5;` you get

```rust
const PROMOTED: &'static i32 = {
    let tmp = 5;
    &tmp // no storage dead for tmp
};
const X: &'static i32 = PROMOTED;
```

and in `const Y: &'static &'static i32 = &&5;` you get

```rust
const PROMOTED: &'static i32 = {
    let a = 5;
    let b = &a;
    &b // no storage dead for a and b
};
const X: &'static &'static i32 = PROMOTED;
```

File: src/librustc_mir/interpret/intern.rs (hunk 5 above)
Comment (oli-obk) [reply src/librustc_mir/interpret/intern.rs]: It is reachable, but I'm entirely unclean on why it is reachable

```rust
const RAW_TRAIT_OBJ_CONTENT_INVALID: *const dyn Trait = &unsafe { BoolTransmute { val: 3 }.bl } as *const _;
```
hits the `InternKind::Constant` arm.

See the MIR on https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=3bc6c8b165b614bbe6cf5566d30752de there's no `StorageDead` for the allocation containing the `bool` with bit pattern `3`.

I'm not really sure what's going on there. Technically, since we're inside a constant, shouldn't this trigger promotion and promote the transmuted value?

Comment (oli-obk) [reply src/librustc_mir/interpret/intern.rs]: Under unleash it's also reached in

```rust
const MUTABLE_BEHIND_RAW: *mut i32 = &UnsafeCell::new(42) as *const _ as *mut _;
```

but that triggers the delay_span_bug as expected.

Also under unleash, but without an ICE (just triggering the dynamic checks in interp):

```rust
const MUTABLE_BEHIND_RAW: *mut i32 = &UnsafeCell::new(42) as *const _ as *mut _;
//~^ WARN: skipping const checks

const MUTATING_BEHIND_RAW: () = {
    // Test that `MUTABLE_BEHIND_RAW` is actually immutable, by doing this at const time.
    unsafe {
        *MUTABLE_BEHIND_RAW = 99 //~ ERROR any use of this value will cause an error
    }
};
```

File: src/librustc_mir/interpret/intern.rs (hunk 9 above)
Comment (RalfJung) [reply src/librustc_mir/interpret/intern.rs]: That's a validation thing. But the things that are checked here, like mutability, are of a different nature -- as in the example I gave.

Validation *already* follows references into other statics/promoteds if they are in the same crate.

File: src/librustc_mir/interpret/intern.rs (hunk 1 above)
Comment (RalfJung) [reply src/librustc_mir/interpret/intern.rs]: > Now it actually extracts a real promoted, but that promoted may contain interior promoteds that again use the StorageDead trick.

Right, so promoteds *inside promoteds* still just kill `StorageDead`. But the branch this discussion about is `InternKind::Static`, not a promoted, so that part is rrelevant.

This is a static, and thus shouldn't be able to have any inner relocations, those would all have been promoted already. What am I missing?

File: src/librustc_mir/interpret/intern.rs (hunk 5 above)
Comment (RalfJung) [reply src/librustc_mir/interpret/intern.rs]: > I'm not really sure what's going on there. Technically, since we're inside a constant, shouldn't this trigger promotion and promote the transmuted value?

Ah, this must be the "not-promotion" also described [in this document](https://github.com/rust-lang/const-eval/blob/master/promotion.md) (Ctrl-F "looks like"). That makes sense.

File: src/librustc_mir/interpret/intern.rs (hunk 1 above)
Comment (RalfJung) [reply src/librustc_mir/interpret/intern.rs]: The new arm for `Static` here isn't critical for the bugfix, right? Only the `Promoted` thing is. So in the interest of getting the regression fixed ASAP, I suggest removing this part from this PR and having that discussion in a new PR.

File: src/librustc_mir/interpret/intern.rs [hunk 10]
```diff
@@ -329,10 +337,29 @@ pub fn intern_const_alloc_recursive<M: CompileTimeMachine<'mir, 'tcx>>(
...
+                // pointers encountered inside the base allocation, and then only for ones not at
+                // reference type, as that is checked by the type based main interner.
+                InternKind::Static(hir::Mutability::Not) => {
+                    alloc.mutability = Mutability::Not;
+                }
+                // Raw pointers in promoteds may only point to immutable things so we mark
+                // everything as immutable.
+                // It is UB to mutate through a raw pointer obtained via an immutable reference.
+                // Since all references and pointers inside a promoted must by their very definition
+                // be created from an immutable reference, mutating though them would be UB.
```
Comment (RalfJung) [inline src/librustc_mir/interpret/intern.rs]:
```suggestion
                // be created from an immutable reference (and promotion also excludes interior
                // mutability), mutating though them would be UB.
```

File: src/librustc_mir/interpret/intern.rs (hunk 6 above)
Comment (RalfJung) [reply src/librustc_mir/interpret/intern.rs]: All right, this new branch is fine for me then (modulo the comment). That's the critical part, I think.

File: src/librustc_mir/interpret/intern.rs (hunk 5 above)
Comment (RalfJung) [reply src/librustc_mir/interpret/intern.rs]: What I don't understand though is why `RAW_TRAIT_OBJ_CONTENT_INVALID` doesn't trigger the ICE. Why is the allocation already immutable?

File: src/librustc_mir/interpret/intern.rs (hunk 9 above)
Comment (RalfJung) [reply src/librustc_mir/interpret/intern.rs]: This is also non-critical for the regression fix so can be factored into a separate PR, right?

File: src/librustc_mir/interpret/intern.rs (hunk 5 above)
Comment (oli-obk) [reply src/librustc_mir/interpret/intern.rs]: The `&unsafe { BoolTransmute { val: 3 }.bl }` part is actually promoted

```rust
const  RAW_TRAIT_OBJ_CONTENT_INVALID: *const dyn Trait = {
    let mut _0: *const dyn Trait;        // return place in scope 0 at src/lib.rs:1:38: 1:54
    let mut _1: *const dyn Trait;        // in scope 0 at src/lib.rs:1:57: 1:108
    let mut _2: *const bool;             // in scope 0 at src/lib.rs:1:57: 1:96
    let _3: &bool;                       // in scope 0 at src/lib.rs:1:57: 1:96
    scope 1 {
    }

    bb0: {
        StorageLive(_1);                 // bb0[0]: scope 0 at src/lib.rs:1:57: 1:108
        StorageLive(_2);                 // bb0[1]: scope 0 at src/lib.rs:1:57: 1:96
        StorageLive(_3);                 // bb0[2]: scope 0 at src/lib.rs:1:57: 1:96
        _3 = &(promoted[0]: bool);       // bb0[3]: scope 0 at src/lib.rs:1:57: 1:96
        _2 = &raw const (*_3);           // bb0[4]: scope 0 at src/lib.rs:1:57: 1:96
        _1 = move _2 as *const dyn Trait (Pointer(Unsize)); // bb0[5]: scope 0 at src/lib.rs:1:57: 1:96
        _0 = _1;                         // bb0[6]: scope 0 at src/lib.rs:1:57: 1:108
        StorageDead(_3);                 // bb0[7]: scope 0 at src/lib.rs:1:107: 1:108
        StorageDead(_1);                 // bb0[8]: scope 0 at src/lib.rs:1:107: 1:108
        return;                          // bb0[9]: scope 0 at src/lib.rs:1:1: 1:109
    }
}

promoted[0] in  RAW_TRAIT_OBJ_CONTENT_INVALID: bool = {
    let mut _0: bool;                    // return place in scope 0 at src/lib.rs:1:57: 1:96
    let mut _1: bool;                    // in scope 0 at src/lib.rs:1:58: 1:96
    let mut _2: BoolTransmute;           // in scope 0 at src/lib.rs:1:67: 1:91
    scope 1 {
    }

    bb0: {
        (_2.0: u8) = const 3u8;          // bb0[0]: scope 0 at src/lib.rs:1:67: 1:91
                                         // ty::Const
                                         // + ty: u8
                                         // + val: Value(Scalar(0x03))
                                         // mir::Constant
                                         // + span: src/lib.rs:1:88: 1:89
                                         // + literal: Const { ty: u8, val: Value(Scalar(0x03)) }
        _1 = (_2.1: bool);               // bb0[1]: scope 0 at src/lib.rs:1:67: 1:94
        _0 = move _1;                    // bb0[2]: scope 0 at src/lib.rs:1:57: 1:96
        return;                          // bb0[3]: scope 0 at src/lib.rs:1:57: 1:96
    }
}
```

File: src/librustc_mir/interpret/intern.rs (hunk 9 above)
Comment (oli-obk) [reply src/librustc_mir/interpret/intern.rs]: definitely, that's why it's a FIXME

> That's a validation thing. But the things that are checked here, like mutability, are of a different nature -- as in the example I gave.

What I mean is if you have a relocation to a static with interior mutability behind a raw pointer, then validation won't catch this, but interning can realize that there's a mutable allocation reachable from a constant.

File: src/librustc_mir/interpret/intern.rs (hunk 1 above)
Comment (oli-obk) [reply src/librustc_mir/interpret/intern.rs]: Ah, this entire match is only for relocations outside of references. So your example `static FOO: AtomicUsize` wouldn't even hit this branch, you'd need `static FOO: *const AtomicUsize = &AtomicUsize::new(42);`, which... is not problematic at all, so the code is indeed wrong.

> The new arm for Static here isn't critical for the bugfix, right? Only the Promoted thing is. So in the interest of getting the regression fixed ASAP, I suggest removing this part from this PR and having that discussion in a new PR.

Yes, I'll remove it

File: src/librustc_mir/interpret/intern.rs (hunk 5 above)
Comment (RalfJung) [reply src/librustc_mir/interpret/intern.rs]: > The &unsafe { BoolTransmute { val: 3 }.bl } part is actually promoted

But then why is this arm (`InternKind::Constant | InternKind::ConstProp`) reached? Your answers just keep opening new questions.^^ If you have a holistic view of what happens, it would really help to write that down. I am trying to prove that with my questions, but each answer just exposes the next layer in what seems to be a maze...

File: src/librustc_mir/interpret/intern.rs (hunk 9 above)
Comment (RalfJung) [reply src/librustc_mir/interpret/intern.rs]: FIXME still means "here's something that needs fixing", and I have strong reservations that this is the case, hence my reluctance to land this.

> What I mean is if you have a relocation to a static with interior mutability behind a raw pointer, then validation won't catch this, but interning can realize that there's a mutable allocation reachable from a constant.

I understand. And I keep saying that this doesn't matter. Interning doesn't check for mutable allocations reachable for constants elsewhere (through references) either, only validation does (and more by accident).

There is no reason, that I can see, that we'd ever want to run-time dynamically check that a constant doesn't point to a mutable static. We don't have such a check right now. What we have is a check making sure that a constant doesn't *read from* a mutable static, and through validation that happens to also exclude some constants pointing to mutable statics, but that is an accident, not by design. At least, that is my understanding of the situation.

**Comment by RalfJung** [comment]
r=me with the `if let Some(_) = ecx.tcx.alloc_map.lock().get(alloc_id)` branch removed.

File: src/librustc_mir/interpret/intern.rs [hunk 11]
```diff
@@ -329,10 +337,24 @@ pub fn intern_const_alloc_recursive<M: CompileTimeMachine<'mir, 'tcx>>(
...
+                // Statics may contain mutable allocations even behind relocations.
+                // Even for immutable statics it would be ok to have mutable allocations behind
+                // raw pointers, e.g. for `static FOO: *const AtomicUsize = &AtomicUsize::new(42)`.
+                InternKind::Static(_) => {}
+                // Raw pointers in promoteds may only point to immutable things so we mark
+                // everything as immutable.
+                // It is UB to mutate through a raw pointer obtained via an immutable reference.
+                // Since all references and pointers inside a promoted must by their very definition
+                // be created from an immutable reference (and promotion also excludes interior
+                // mutability), mutating though them would be UB.
```
Comment (RalfJung) [inline src/librustc_mir/interpret/intern.rs]:
```suggestion
                // mutability), mutating through them would be UB.
```

File: src/librustc_mir/interpret/intern.rs (hunk 5 above)
Comment (RalfJung) [reply src/librustc_mir/interpret/intern.rs]: (The PR doesn't change anything here so this doesn't block landing, but I'd really like to understand this and then see it documented.)

Comment (wesleywiser) [reply src/librustc_mir/interpret/intern.rs]: I would find documentation here immensely helpful.

Comment (oli-obk) [reply src/librustc_mir/interpret/intern.rs]: > If you have a holistic view of what happens, it would really help to write that down.

I don't, which is why my answers are so confusing. They are just a brain dump of me discovering what is going on, not me understanding it entirely

Comment (oli-obk) [reply src/librustc_mir/interpret/intern.rs]: These issues are preexisting, so after this PR is merged I'll open a new one to write docs and actually figure out what is going on

Comment (RalfJung) [reply src/librustc_mir/interpret/intern.rs]: > I don't, which is why my answers are so confusing. They are just a brain dump of me discovering what is going on, not me understanding it entirely

Fair enough. :)

**Comment by SimonSapin** [comment]
Confirmed that this fixes https://github.com/rust-lang/rust/issues/67601 for Servo. Thanks!
