### PR TITLE
Stabilize `feature(generic_arg_infer)`

### LINKED ISSUE #85077: Tracking Issue for  `_` as a const argument: `feature(generic_arg_infer)`
This is a tracking issue for the RFC GenericArg::Infer
The feature gate for the issue is `#![feature(generic_arg_infer)]`.

## What is `GenericArg::Infer`?

Currently, rustc supports type inference. That is, given a function `fn(T)`, it can infer the type of T based on its usage. Const-generics also has limited support for inference, such as for arrays, we can infer `N: usize` in some usages `[T; N]`. In order to expand inference for consts, it's necessary to lift the current specialized type `Ty::Infer` into `GenericArg::Infer`, as `GenericArg` covers both consts and types, whereas `Ty::Infer` can only be used in the place of types. This will eventually allow for consts to be inferred in all the same locations as types.

### About tracking issues

Tracking issues are used to record the overall progress of implementation.
They are also used as hubs connecting to other relevant issues, e.g., bugs or open design questions.
A tracking issue is however *not* meant for large scale discussion, questions, or bug reports about a feature.
Instead, open a dedicated issue for the specific matter and add the relevant feature gate label.

### Steps

- [x] Implement the RFC (https://github.com/rust-lang/rust/pull/83484)
- [x] Solve #112110
- [ ] Adjust documentation ([see instructions on rustc-dev-guide][doc-guide])
- [ ] Stabilization PR ([see instructions on rustc-dev-guide][stabilization-guide])

[stabilization-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#stabilization-pr
[doc-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#documentation-prs

### Unresolved Questions

- Should `hir::Ty::Infer` be removed? No just make it unreachable for hir visitors and in `GenericArg::Ty` position

### PR DESCRIPTION
**Pull request by BoxyUwU**
Fixes rust-lang/rust#85077

r? lcnr

cc @rust-lang/project-const-generics

### CODE REVIEW

**Comment by traviscross** [comment]
@rustbot labels -I-lang-easy-decision +P-lang-drag-1

Thanks for putting up this stabilization and the obvious amount of work that went in ahead of it.  Will have a careful look.

(Regarding the label, I like your optimism, but probably this isn't going to be what we mean by an easy decision.  Even to start an FCP, one of us has to be ready to commit to it unless we concurrently file a concern.)

**Comment by traviscross** [comment]
cc @ehuss

(Heads-up this one is actually likely to move along quickly.)

**Comment by traviscross** [comment]
(Just for our notes as I work through this; not a concern...)

This stabilization puts weight on the following bit of inference breakage that will ship with Rust 1.89:

```rust
struct W<T>(Option<T>);

impl Clone for W<u8> {
    fn clone(&self) -> Self {
        W(None)
    }
}
impl Copy for W<u8> {}

fn extract<T: Copy>(x: [W<T>; 2]) -> T {
    x[0].0.unwrap()
}

fn main() {
    let x = [W(None); 2];
    //[1.89]~^ ERROR type annotations needed
    //[1.88]~^ OK
    _ = extract(x).max(2);
}
```

(The 1-impl rule strikes again.  I'm not sure whether or not there's a path to this breakage without it.)

**Comment by traviscross** [comment]
We're also putting some weight on this inference choice:

```rust
#![feature(generic_arg_infer)]

struct W<T>(Option<T>);

impl Clone for W<u32> {
    fn clone(&self) -> Self {
        W(None)
    }
}
impl Copy for W<u32> {}

trait Trait {}
impl Trait for i32 {}
impl Trait for u32 {}

fn make_goal<T: Trait>(_: &T) {}
fn tie<T>(_: &T, _: &[W<T>; 2]) {}

fn main() {
    let a = 1;
    make_goal(&a);
    let b: [W<_>; 2] = [W(None); _];
    //        ~
    //~^ Do we fall back to `i32` here (and give an error since
    // `W<i32>` is not `Copy`), or do we infer `u32` given `W<T>:
    // Copy`?  We pick `u32`.
    tie(&a, &b);
}
```

**Comment by traviscross** [comment]
@rustbot labels +S-waiting-on-documentation

Having read through https://github.com/rust-lang/rust/pull/139635, the tests, the stabilization report, and the Reference PR (though I have not yet reviewed it an editorial sense) this all seems in order to me.  So I propose we accept this stabilization.

@rfcbot fcp merge

File: tests/ui/feature-gates/feature-gate-generic_arg_infer.rs [hunk 1]
```diff
@@ -1,21 +1,15 @@
-//@ [feature] run-pass
-//@ revisions: normal feature
-
-#![cfg_attr(feature, feature(generic_arg_infer))]
+//@ run-pass
```
Comment (lcnr) [inline tests/ui/feature-gates/feature-gate-generic_arg_infer.rs]: remove this test?

**Review by lcnr — COMMENTED** [review]
r=me after nit :tada:

File: tests/ui/feature-gates/feature-gate-generic_arg_infer.rs (hunk 1 above)
Comment (BoxyUwU) [reply tests/ui/feature-gates/feature-gate-generic_arg_infer.rs]: o true :3

**Comment by BoxyUwU** [comment]
ffs

**Comment by ehuss** [comment]
@bors r-

This is still waiting on https://github.com/rust-lang/reference/pull/1835.

**Comment by BoxyUwU** [comment]
When will you have time to look at that PR? It sat for two weeks with no response, are we going to be waiting another two weeks to stabilize this feature? This is such a minor feature I really don't think this should be blocked on a reference PR being *accepted* when bandwidth is so limited and there's a long-term contributor around who you have reasonable confidence isn't just going to disappear on you

**Comment by traviscross** [comment]
We know (and very much appreciate) that you're not going to disappear on us.  And we understand the frustration this can cause (in fact, you can probably find some old threads where I argued against blocking on this sort of thing).

The trouble is just that it can take a lot of work to get a Reference PR up to the point we're willing to accept it.  This is more than just about its technical correctness, and gets into issues of ensuring the Reference is monotonically improving along other axes, e.g. its editorial character, the organization of items, the presentation of the grammar, etc.  (Without being in spec and lang-docs meetings, it'd be hard for anyone to know exactly what we're looking for here, so it's nothing for anyone to feel bad about if one's Reference PR needs this kind of work; it's expected.)

If we both want 1) those things and also 2) the Reference that ships with a particular Rust version to match the language at that version, then it becomes a problem for us to accept language changes without the Reference PR being entirely ready, as then there becomes a hard deadline for that work to happen, and there just isn't always the time without starting to make too big an ask of people.

That's the context.

**Review by traviscross — APPROVED** [review]

**Comment by traviscross** [comment]
@rustbot labels -S-waiting-on-documentation

@ehuss and I worked through the Reference PR today on a call and made the necessary changes to the branch.  It's now ready to go, so we can remove this label, and since this PR is otherwise good to go, we can...

@bors r=lcnr,traviscross rollup
