### PR TITLE
Fixes #64919. Suggest fix based on operator precendence.

### LINKED ISSUE #64919: Suggested fix does not account for operator precedence
This fails (as expected):

```
fn foo() -> String {
    1 + 2
}
```

However, the help message is wrong:

```
error[E0308]: mismatched types
 --> src/lib.rs:2:5
  |
1 | fn foo() -> String {
  |             ------ expected `std::string::String` because of return type
2 |     1 + 2
  |     ^^^^^
  |     |
  |     expected struct `std::string::String`, found integer
  |     help: try using a conversion method: `1 + 2.to_string()`
  |
  = note: expected type `std::string::String`
             found type `{integer}`
```

It should suggest `(1 + 2).to_string()` instead.

Rust version: 1.38.0 (stable)

### PR DESCRIPTION
**Pull request by sam09**
Fixes https://github.com/rust-lang/rust/issues/64919

### CODE REVIEW

File: src/test/ui/mismatched_types/abridged.rs [hunk 1]
```diff
@@ -50,4 +50,8 @@ fn e() -> X<X<String, String>, String> {
     x //~ ERROR mismatched types
 }
 
+fn f() -> String {
+    1+2 //~ ERROR mismatched types
```
Comment (jonas-schievink) [inline src/test/ui/mismatched_types/abridged.rs]: The same issue exists with unary operators, eg. `-2` will suggest `-2.to_string()`, which doesn't compile. Might make sense to add another case for `ExprKind::Unary` above.

Comment (sam09) [reply src/test/ui/mismatched_types/abridged.rs]: Sure

File: src/librustc_typeck/check/mod.rs [hunk 2]
```diff
@@ -4344,7 +4344,11 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
                                 let max_len = receiver.rfind(".").unwrap();
                                 format!("{}{}", &receiver[..max_len], method_call)
                             } else {
-                                format!("{}{}", receiver, method_call)
+                                match &expr.kind {
+                                    ExprKind::Binary(_,_,_) => format!("({}){}", receiver, method_call),
+                                    ExprKind::Unary(_,_) => format!("({}){}", receiver, method_call),
+                                    _ => format!("{}{}", receiver, method_call),
+                                }
```
Comment (estebank) [inline src/librustc_typeck/check/mod.rs]: Use `expr.precedence().order() < ExprPrecedence::MethodCall.order()` instead of matching on the `kind`, that way this will never be incorrect for any expression type, even if we add new ones.

Comment (sam09) [reply src/librustc_typeck/check/mod.rs]: @estebank I made the change. But it seems to break/change test cases for other scenarios too.

Comment (estebank) [reply src/librustc_typeck/check/mod.rs]: That is fine, it means those suggestions were incorrect in the first place.

Comment (sam09) [reply src/librustc_typeck/check/mod.rs]: Cool
