### PR TITLE
compile-test: allow overriding nodejs binary location

### LINKED ISSUE #34188: asmjs test runner should detect Node binary name
The test runner for asm.js targets [currently always runs them via `nodejs`](https://github.com/rust-lang/rust/blob/5229e0efb34f924346febcfe158973486dabdf83/src/tools/compiletest/src/runtest.rs#L1406), but that name is not universal across distributions- in fact the official name for the Node binary is `node`. Debian (and presumably Debian derivatives) uses the former name due to a [name conflict with another tool](https://lists.debian.org/debian-devel-announce/2012/07/msg00002.html).

It would be good to support both via detection at runtime, probably preferring `nodejs` and trying `node` if that is not available. In the interest of performance, this should probably be tested only once per run, with a lazy static or similar. Reporting an error if neither is found would also be useful, rather than the current behavior of failing tests due to being unable to invoke the javascript engine.

### PR DESCRIPTION
**Pull request by Mark-Simulacrum**
Add a command-line argument to manually specify which nodejs binary should be used,
which disables the default search.

Original work done by @tari.

Fixes #34188.

### CODE REVIEW

**Comment by TimNN** [comment]
There already seems to be a `nodejs` option: https://github.com/rust-lang/rust/blob/master/src/tools/compiletest/src/common.rs#L192, which is used when provided.

**Comment by Mark-Simulacrum** [comment]
@TimNN That's true, I didn't notice. Though I believe that the existing `nodejs` doesn't try to detect other variants (`node`, `node.exe`, `nodejs.exe`). If this isn't considered worth it, feel free to close this, but then we should close the linked issue (#34188).

**Comment by TimNN** [comment]
Mh, there is some detection in [`bootstrap`](https://github.com/rust-lang/rust/blob/master/src/bootstrap/sanity.rs#L84-L89), so at least when using rustbuild, thinks should be detected correctly.

**Comment by alexcrichton** [comment]
Thanks for the PR! I agree with @TimNN that the best place for this is probably in rustbuild itself, we already need the node executable to run other unit test suites like the standard library. Perhaps this logic could be moved there and continue to be communicated to compiletest via this flag?

**Comment by alexcrichton** [comment]
@Mark-Simulacrum thoughts about updating to place this logic in rustbuild's detection and passing it down to compiletest that way?

**Comment by TimNN** [comment]
@alexcrichton: I'm pretty sure that logic is already present in rustbuild, isn't it?

See https://github.com/rust-lang/rust/blob/master/src/bootstrap/sanity.rs#L84-L89:

```rust 
    // Look for the nodejs command, needed for emscripten testing
    if let Some(node) = have_cmd("node".as_ref()) {
        build.config.nodejs = Some(node);
    } else if let Some(node) = have_cmd("nodejs".as_ref()) {
        build.config.nodejs = Some(node);
    }
```

**Comment by Mark-Simulacrum** [comment]
I *think* I updated this as @alexcrichton suggested (with rustbuild), but I don't have a good way to test, since I don't use rustbuild locally. If someone can give me a set of commands to run then I can run those.

File: src/bootstrap/sanity.rs [hunk 1]
```diff
@@ -86,6 +86,10 @@ pub fn check(build: &mut Build) {
         build.config.nodejs = Some(node);
     } else if let Some(node) = have_cmd("nodejs".as_ref()) {
         build.config.nodejs = Some(node);
+    } else if let Some(node) = have_cmd("node.exe".as_ref()) {
```
Comment (TimNN) [inline src/bootstrap/sanity.rs]: No need for those extra checks, `have_cmd` will automatically consider `.exe` as well for each command.

**Comment by TimNN** [comment]
I don't think the current implementation needs much adjusting -- the only problem I can see with it is that it does not allow specifying the path to node in `config.toml` or via `./configure` but will instead always search the path.

**Comment by Mark-Simulacrum** [comment]
Hmm, yeah, I see that now. Can someone point me to where I can make those changes (if we want to)? Otherwise we can just close this.

File: src/bootstrap/check.rs [hunk 2]
```diff
@@ -110,6 +110,9 @@ pub fn compiletest(build: &Build,
 
     if let Some(nodejs) = build.config.nodejs.as_ref() {
         cmd.arg("--nodejs").arg(nodejs);
+    } else {
+        // FIXME: Print a message about being unable to detect a nodejs binary;
+        // and suggest a fix (passing --nodejs to configure?).
```
Comment (alexcrichton) [inline src/bootstrap/check.rs]: I think it's fine to leave this kind of error reporting to compiletest rather than in rustbuild itself

File: src/bootstrap/sanity.rs (hunk 1 above)
Comment (alexcrichton) [inline src/bootstrap/sanity.rs]: (agreed yeah)

File: src/tools/compiletest/src/common.rs [hunk 3]
```diff
@@ -173,6 +173,9 @@ pub struct Config {
     // status whether android device available or not
     pub adb_device_status: bool,
 
+    // Name with which to invoke Node for asmjs targets
+    pub node_path: Option<String>,
```
Comment (alexcrichton) [inline src/tools/compiletest/src/common.rs]: This should be set at some point, right? (from the command-line flag)

Comment (TimNN) [inline src/tools/compiletest/src/common.rs]: There already is a nodejs option for compiletest (a few lines down).

**Comment by alexcrichton** [comment]
@Mark-Simulacrum you can take a look at `src/bootstrap/config.rs` to support manual configuration of node (which seems great to have!). You can mirror the logic for a custom rustc/cargo by just adding appropriate fields to the structs there, parsing them out, and also parsing the line from `./configure` (if it exists) to go into the right field.

**Comment by TimNN** [comment]
Also you'll probably want to update the logic [here] to only try to auto detect node if it has not been specified by the user (somewhat like it's done for gdb just below).

[here]: https://github.com/rust-lang/rust/blob/master/src/bootstrap/sanity.rs#L84-L93

**Comment by Mark-Simulacrum** [comment]
Alright, rebased and [hopefully] made this work with the comments suggested above.

**Comment by alexcrichton** [comment]
@bors: r+

Thanks!
