### PR TITLE
Account for `maybe_whole_expr` in range patterns

### LINKED ISSUE #63115: "`X...` range patterns are not supported" occurring in today's nightly
The CI for `libssh2-sys` started to fail today with this error:

```
error: `X...` range patterns are not supported
   --> C:\Users\wez\.cargo\registry\src\github.com-1ecc6299db9ec823\extprim-1.7.0\src\traits.rs:94:21
    |
94  |                     1 ... $e => u128::new(mantissa) << exp,
    |                     ^^^^^ help: try using the maximum value for the type: `1...MAX`
...
117 | impl_to_extra_primitive_for_float!(f32, 23, 104, 103);
    | ------------------------------------------------------ in this macro invocation
```

It appears as though the compiler doesn't see `1 ... $e` and only sees `1...` as the range expression and then generates this error.

The expression is inside a `macro_rules!` expansion.

You can reproduce this by cloning the `extprim` repo and building it:

```
$ git clone git@github.com:kennytm/extprim.git
$ cd extprim
$ cargo +nightly build
```

The build succeeds on the stable channel and much older releases, so this appears to be a regression in the nightly.

Here's the version on my windows system, but note that this also fails on linux and macos too:

```
rustc 1.38.0-nightly (4560cb830 2019-07-28)
binary: rustc
commit-hash: 4560cb830fce63fcffdc4558f4281aaac6a3a1ba
commit-date: 2019-07-28
host: x86_64-pc-windows-msvc
release: 1.38.0-nightly
LLVM version: 9.0
```

### PR DESCRIPTION
**Pull request by Centril**
Fixes https://github.com/rust-lang/rust/issues/63115 (fallout from https://github.com/rust-lang/rust/pull/62550).

r? @petrochenkov

### CODE REVIEW

File: src/libsyntax/parse/token.rs [hunk 1]
```diff
@@ -476,6 +476,19 @@ impl Token {
         false
     }
 
+    /// Would `maybe_whole_expr` in `parser.rs` return `Ok(..)`?
+    /// That is, is this a pre-parsed expression dropped into the token stream
+    /// (which happens while parsing the result ofmacro expansion)?
+    crate fn is_whole_expr(&self) -> bool {
+        if let Interpolated(ref nt) = self.kind {
+            if let NtExpr(_) | NtLiteral(_) | NtPath(_) | NtBlock(_) = **nt {
```
Comment (Centril) [inline src/libsyntax/parse/token.rs]: Should this include `NtIdent` and should `parse_prefix_expr` use `is_whole_expr` in the case of `token::Ident(..) if self.token.is_ident_named(sym::not) => {`?

(Might want to look over the usage of `Interpolated` in `token.rs` and `parser.rs` overall.)

Comment (petrochenkov) [reply src/libsyntax/parse/token.rs]: >Should this include `NtIdent`

`NtIdent` is normalized to `Ident` in `Parser::bump`, so only "parser infrastructure" code need to care about it, but not "parser user" code, so `macro_rules! maybe_whole_expr` don't need it.

However, since you added this method to `Token` (which is not necessarily tied to the `Parser` in theory), adding `NtIdent` here won't hurt.

`parse_prefix_expr` can reuse `is_whole_expr`, yes.

**Comment by petrochenkov** [comment]
r=me after looking at https://github.com/rust-lang/rust/pull/63122#discussion_r309135474

**Comment by gnzlbg** [comment]
This should be p=infinity.
