### PR TITLE
Provide context for missing comma in match arm and if statement without block

### LINKED ISSUE #29586: Error reporting for missing `match` comma could be improved
UPDATE: [Mentoring instructions below.](https://github.com/rust-lang/rust/issues/29586#issuecomment-331298925)

---

[Given this code](https://play.rust-lang.org/?gist=40825ac7e9516d1140f85d60a43d3fd1&version=nightly):

``` rust
enum Foo { A, B, }

fn main() {
    match &Foo::A {
        &Foo::A => "art"
        &Foo::B => "bart"
    };
}
```

`rustc` reports this error:

```
error: expected one of `!`, `,`, `.`, `::`, `?`, `{`, `}`, or an operator, found `=>`
 --> src/main.rs:6:17
  |
6 |         &Foo::B => "bart"
  |                 ^^ expected one of 8 possible tokens here
```

As @mbrubeck pointed out in IRC, the cause is that a bitwise-and operation, namely `"art" & Foo::B` is being parsed.

### LINKED ISSUE #30035: Better error message when forgetting the right operand in an if condition
Hello.
The following code gives an error message that could be improved:

``` rust
fn main() {
    let n = 1;
    if 5 == {
        println!("five");
    }
}
```

It gives the following error:

```
src/main.rs:6:1: 6:2 error: expected `{`, found `}`
src/main.rs:6 }
              ^
src/main.rs:6:1: 6:2 help: place this code inside a block
```

This is because the compiler sees the right operand as a block expression, and is looking for the condition body, something like:

``` rust
fn main() {
    let n = 1;
    if 5 == {
        println!("five");
        5
    } {
        println!("Five");
    }
}
```

while we most probably mean to write something like:

``` rust
fn main() {
    let n = 1;
    if 5 == n {
        println!("five");
    }
}
```

So, it would be nice to improve this error message.

### PR DESCRIPTION
**Pull request by estebank**
When finding:

```rust
match &Some(3) {
    &None => 1
    &Some(2) => { 3 }
    _ => 2
}
```

provide the following diagnostic:

```
error: expected one of `,`, `.`, `?`, `}`, or an operator, found `=>`
 --> $DIR/missing-comma-in-match.rs:15:18
  |
X |         &None => 1
  |               --  - help: missing comma
  |               |
  |               while parsing the match arm starting here
X |         &Some(2) => { 3 }
  |                  ^^ expected one of `,`, `.`, `?`, `}`, or an operator here
```

When unnecessarily using a fat arrow after an if condition, suggest the
removal of it.

```
error: expected `{`, found `=>`
  --> $DIR/missing-block-hint.rs:13:18
   |
13 |         if (foo) => {} //~ ERROR expected `{`, found `=>`
   |                  ^^ help: only necessary in match arms, not before if blocks
```

When finding an if statement with no block, point at the `if` keyword to
provide more context:

```

error: expected `{`, found `}`
  --> file.rs:6:1
   |
13 |     if 5 == {
   |     -- this `if` statement has a condition, but no block
...
17 | }
   | ^
```

Fix #29586, fix #30035.

### CODE REVIEW

File: src/libsyntax/parse/parser.rs [hunk 1]
```diff
@@ -3210,7 +3228,23 @@ impl<'a> Parser<'a> {
...
+        let fat_arrow_sp = if self.token == token::FatArrow {
+            Some(self.span)
+        } else {
+            None
+        };
+        let thn = self.parse_block().map_err(|mut err| {
+            if let Some(sp) = fat_arrow_sp {
+                // if cond => expr
+                err.span_suggestion(sp,
+                                    "only necessary in match arms, not before if blocks",
```
Comment (nikomatsakis) [inline src/libsyntax/parse/parser.rs]: Nit: I found this confusingly phrased. Maybe this?

```
"only necessary with `match`, not `if`"
```

I'm also aiming to avoid jargon like "arms" and "blocks", which users may not be familiar with.

File: src/libsyntax/parse/parser.rs [hunk 2]
```diff
@@ -3402,14 +3436,48 @@ impl<'a> Parser<'a> {
...
             None
         };
+        let arrow_span = self.span;
         self.expect(&token::FatArrow)?;
-        let expr = self.parse_expr_res(Restrictions::STMT_EXPR, None)?;
+        let arm_start_span = self.span;
+
+        let expr = self.parse_expr_res(Restrictions::STMT_EXPR, None)
+            .map_err(|mut err| {
+                err.span_label(arrow_span, "while parsing the match arm starting here");
```
Comment (nikomatsakis) [inline src/libsyntax/parse/parser.rs]: I would say:

```
 "while parsing the `match` arm starting here"
```

File: src/test/ui/suggestions/missing-comma-in-match.stderr [hunk 3]
```diff
@@ -0,0 +1,12 @@
+error: expected one of `,`, `.`, `?`, `}`, or an operator, found `=>`
+  --> $DIR/missing-comma-in-match.rs:14:18
+   |
+13 |         &None => 1
+   |               --  - help: missing a comma here to end this match arm
+   |               |
+   |               while parsing the match arm starting here
```
Comment (nikomatsakis) [inline src/test/ui/suggestions/missing-comma-in-match.stderr]: I feel like this is "heavy", but I'm not sure how to suggest an improvement yet. I wonder if just the suggestion would be enough? 

```
error: expected one of `,`, `.`, `?`, `}`, or an operator, found `=>`
  --> $DIR/missing-comma-in-match.rs:14:18
   |
13 |         &None => 1
   |                   - help: maybe missing a comma here: `1,`
14 |         &Some(2) => { 3 }
   |                  ^^ expected one of `,`, `.`, `?`, `}`, or an operator here

error: aborting due to previous error
```

Would that be hard to add?

Comment (estebank) [reply src/test/ui/suggestions/missing-comma-in-match.stderr]: It shouldn't.

File: src/libsyntax/parse/parser.rs [hunk 4]
```diff
@@ -3210,7 +3228,23 @@ impl<'a> Parser<'a> {
...
-        let thn = self.parse_block()?;
+        let not_block = self.token != token::OpenDelim(token::Brace);
+        let fat_arrow_sp = if self.token == token::FatArrow {
+            Some(self.span)
+        } else {
+            None
+        };
+        let thn = self.parse_block().map_err(|mut err| {
+            if let Some(sp) = fat_arrow_sp {
+                // if cond => expr
```
Comment (petrochenkov) [inline src/libsyntax/parse/parser.rs]: Is there an issue about this or any other confirmation that this mistake is realistic?

**Comment by petrochenkov** [comment]
LGTM except for maybe removing special diagnostics for https://github.com/rust-lang/rust/pull/48338/files#r169751541

File: src/libsyntax/parse/parser.rs (hunk 4 above)
Comment (estebank) [reply src/libsyntax/parse/parser.rs]: There was an [existing test case](https://github.com/estebank/rust/commit/72d629caa50fa482dd4165cb43b9fb02ac24c8d8#diff-6ca7ee6ac85a875788a20c56dda8a64d), but it is indeed a big corner case. I can remove the special diagnostic.

Comment (petrochenkov) [reply src/libsyntax/parse/parser.rs]: Yes, I think just removing this would be for the better.

**Comment by kennytm** [comment]
@bors r-

CI failed, please update these UI tests for #48449.

```
[01:09:57] failures:
[01:09:57]     [ui] ui/if-without-block.rs
[01:09:57]     [ui] ui/suggestions/missing-comma-in-match.rs
```

**Comment by nikomatsakis** [comment]
@estebank you'll probably have to rebase =)

**Comment by kennytm** [comment]
@bors retry #46903 

34 minutes spent on building stage1-rustc.

**Comment by Manishearth** [comment]
@bors retry

(rollup priority)

**Comment by petrochenkov** [comment]
Looks like this hasn't landed as a part of rollup.
