### PR TITLE
Clarify `Error::last_os_error` can be weird

### LINKED ISSUE #106937: Unclear example in io::Error
### Location

The unclear example is located [here](https://doc.rust-lang.org/std/io/struct.Error.html#method.kind).

### Summary

I originally interpreted this example to mean that constructing an error from a raw error code always resulted in `ErrorKind::Uncategorized`. I think it might help to be explicit that no error has occurred yet and that is the reason that this shows up as uncategorized.

### PR DESCRIPTION
**Pull request by workingjubilee**
Fundamentally, querying the OS for error codes is a process that is deeply subject to the whims of chance and fortune. We can account for OS, but not for every combination of platform APIs. A compiled binary may not recognize new errors introduced years later. We should clarify a few especially odd situations, and what they mean: We can effectively promise nothing... if you ask for Rust to decode errors where none have occurred.

This allows removing mention of ErrorKind::Uncategorized.
That error variant is hidden deliberately, so we should not explicitly mention it.

This fixes #106937.

Since you had an opinion also: Does this solution seem acceptable?
r? @ChrisDenton

### CODE REVIEW

**Comment by ChrisDenton** [comment]
Hm, this does seem to adequately address the issue but I do think it'd be useful for the `kind()` docs to have some mention of what happens with OS errors (i.e. with `last_os_error` and `from_raw_os_error` their kind is automatically determined based on the OS error code). The [`from_raw_os_error`](https://doc.rust-lang.org/nightly/std/io/struct.Error.html#method.from_raw_os_error) has a relevant example so maybe it's enough to link to that method's docs.

**Comment by workingjubilee** [comment]
I tried an alternative tack of explaining that if you ask Rust to decode an error where none has actually occurred, it may not make sense. It may have even been set to random values by a truly spiteful OS. We're just a standard library, and are not necessarily capable of suggesting you ask a different question instead.

File: library/std/src/io/error.rs [hunk 1]
```diff
@@ -565,6 +565,12 @@ impl Error {
     /// other standard library functions may call platform functions that may
     /// (or may not) reset the error value even if they succeed.
     ///
+    /// If this is used in a case where no error has yet occurred in a program,
+    /// e.g. right after the beginning of `fn main`,
+    /// then in principle any possible Error may be returned.
+    /// The error code may have been set by a previous program (e.g. `execve`)
+    /// or the OS may have initialized it to an arbitrary, even random, value.
```
Comment (kadiwa4) [inline library/std/src/io/error.rs:572]: Thats not how `main` works; its not actually your program's entry point. That is actually located [here](https://github.com/rust-lang/rust/blob/master/library/std/src/rt.rs#L159) in the standard library and it already does some syscalls (on unix for example [this `init` function](https://github.com/rust-lang/rust/blob/master/library/std/src/sys/unix/mod.rs#L53) gets run)

Comment (ChrisDenton) [reply library/std/src/io/error.rs:572]: Hm, this is kind of not guaranteed (a platform may have an empty `init` function) but the most important point is that even if the std calls OS functions pre user main, there's no guarantee that these functions set the last OS error code.

That said, I'm unsure if this paragraph adds anything that isn't already stated in the previous one: 

> This should be called immediately after a call to a platform function, otherwise the state of the error value is indeterminate

Surely this covers this case adequately without getting into the weeds of what any particular platform may or may not do?

**Comment by ChrisDenton** [comment]
To be honest, I think the initial PR was more in the right direction than this alternative tack. There's no need for `kind()` to get into the nuances of `last_os_error()`. The important points are, I think, that `kind()` will either return the `io::Kind` that was set in a custom `io::Error` or else return an `io::Kind` that's inferred from an OS error code.

**Comment by workingjubilee** [comment]
More like this, then?

**Comment by ChrisDenton** [comment]
Yeah. I'll admit to still being slightly uncomfortable with the example but I think this is a definite improvement. So...

@bors r+
