### PR TITLE
Make struct_tail normalize when possible

### LINKED ISSUE #60431: ICE with unsized associated type
```
use std::mem;

pub trait Arena {
    type Dyn : ?Sized;
}

pub struct DynRef {
    _dummy: [()],
}

pub struct Ref<T, A: Arena> {
    _value: T,
    _dyn_arena: A::Dyn,
}

pub struct Obstack;

impl Arena for Obstack {
    type Dyn = DynRef;
}

fn main() {
    mem::size_of::<&Ref<u8, Obstack>>();
}
```

produces:

```
$ rustc ice-dyn.rs 
error: internal compiler error: src/librustc_codegen_llvm/context.rs:867: failed to get layout for `&Ref<u8, Obstack>`: the type `<Obstack as Arena>::Dyn` has an unknown layout

thread 'rustc' panicked at 'Box<Any>', src/librustc_errors/lib.rs:620:9
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
error: aborting due to previous error


note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.34.1 (fc50f328b 2019-04-24) running on x86_64-unknown-linux-gnu
```

Some context as to what that's actually for: the idea was to use the len metadata of the slice within the `DynRef` to smuggle a pointer to the arena in question. At first glance you'd think you could also do:

```
pub struct Ref<T, A: Arena> {
    marker: PhantomData<A>,
    value: T,
    arena: [()],
}
```

But the problem is that is mutable borrows: if `Ref` implements `DerefMut` there's no way to both access the value and the arena at the same time. You need them separate, and deliberately public:

```
pub struct Ref<T, A: Arena> {
    pub this: T,
    pub arena: A::Dyn,
}
```

allowing implementations like:

```
impl<A: Arena> Foo {
    fn frob(self: &mut Ref<Foo, A>) {
        self.arena.get(self.this.bar);
    }
}
```

...and as for why the object can't just own a reference to the arena it's in, tl;dr: memmap;

### PR DESCRIPTION
**Pull request by pnkfelix**
As noted in commit message: this replaces the existing methods to extract the struct tail(s) with new entry points that make the handling of normalization explicit.

Most of the places that call `struct_tail` are during codegen, post type-checking, and therefore they can get away with using `tcx.normalize_erasing_regions` (this is the entry point `struct_tail_erasing_lifetimes`)

For other cases that may arise, one can use the core method, which is parameterized over the normalization `Ty -> Ty` closure (`struct_tail_with_normalize`).

Or one can use the trivial entry point that does not normalization (`struct_tail_without_normalization`)

----

I spent a little while trying to make a test that exposed the bug via `impl Trait` rather than a projection, but I failed to find something that tripped up the current nightly `rustc`.
 * I have *not* spent any time trying to make tests that trip up the other places where `struct_tail` was previously being called. While I do think the task of making such tests could be worthwhile, I am simply running out of time. (Its also possible that the layout code is always the first point called, and thus it may be pointless to try to come up with such tests.)

I also spent a little time discussing with @eddyb where this code should live. They suggested moving `struct_tail` and its sibling `struct_lockstep_tails` to the `LayoutCx`.  But in the interest of time, I have left that refactoring (which may be questionable at this point) to a follow-up task.

----

Fix #60431

### CODE REVIEW

File: src/librustc/ty/util.rs [hunk 1]
```diff
@@ -295,10 +336,34 @@ impl<'tcx> TyCtxt<'tcx> {
     /// structure definitions.
     /// For `(Foo<Foo<T>>, Foo<dyn Trait>)`, the result will be `(Foo<T>, Trait)`,
     /// whereas struct_tail produces `T`, and `Trait`, respectively.
-    pub fn struct_lockstep_tails(self,
-                                 source: Ty<'tcx>,
-                                 target: Ty<'tcx>)
-                                 -> (Ty<'tcx>, Ty<'tcx>) {
+    ///
+    /// Must only be called after type-checking is complete; otherwise
+    /// normalization attempt may cause compiler bugs.
```
Comment (eddyb) [inline src/librustc/ty/util.rs]: Pretty sure you'd just get a cycle error? Or, rather, it's a bad idea to use this from anywhere that cares about lifetimes.

File: src/librustc/ty/util.rs [hunk 2]
```diff
@@ -319,7 +384,23 @@ impl<'tcx> TyCtxt<'tcx> {
                     } else {
                         break;
                     }
-                },
+                        },
```
Comment (eddyb) [inline src/librustc/ty/util.rs]: Stray change?

**Review by eddyb — APPROVED** [review]
r=me with nits fixed (if at all)

File: src/librustc/ty/util.rs (hunk 1 above)
Comment (pnkfelix) [reply src/librustc/ty/util.rs]: Well I figured the fact that I witnessed an ICE when i called the wrong thing from rvalue_hint means that I can’t go wrong making the warning here super strong, right?

Comment (eddyb) [reply src/librustc/ty/util.rs]: What kind of ICE? Maybe it should just say "don't pass types with inference variables in, and don't use this if you want to keep your lifetimes".

Comment (eddyb) [reply src/librustc/ty/util.rs]: The distinction is important because e.g. the NLL borrowck uses inference despite being after typeck, and *cares about lifetimes even more*.

So the old "after typeck" should be rephrased across the compiler - it was a poor shorthand even back then, and now it's not even true anymore.

Comment (pnkfelix) [reply src/librustc/ty/util.rs]: In this [gist][] is some RUSTC_LOG and backtrace for the ICE that I was referring to up above

[gist]: https://gist.github.com/85b11805d1fca46dad0b03d0dd9a3abc

But sure, I am happy to revise the wording more.

Comment (eddyb) [reply src/librustc/ty/util.rs]: Yeah that's inference variables. Okay, minimal changes:
* "during type checking" -> "during type inference"
* "after type checking" -> "outside of type inference"

File: src/librustc/ty/util.rs (hunk 2 above)
Comment (pnkfelix) [reply src/librustc/ty/util.rs]: so this bit is goofy, I think its an artifact, at least in emacs, of the match guard starting on its own line ...

Comment (pnkfelix) [reply src/librustc/ty/util.rs]: ah but I didn't even touch the match guard. Okay reverted this.
