### PR TITLE
Fix debug infinite loop

### LINKED ISSUE #41338: Trying to debug print the difference of two BTreeSets goes into endless print loop.
I tried printing difference of two BTreeSets using the debug print, but instead of printing anything useful it went into some weird recursive loop printing Difference(Difference(Difference endlessly.

I tried this code:

```Rust
let mut a = BTreeSet::new();
a.insert(1);
a.insert(2);

let mut b = BTreeSet::new();
b.insert(2);
b.insert(3);

println!("{:?}", a.difference(&b));
```

I obviously expected it to print something like Difference(*contents*) just like when debug printing some vec.iter().

Instead, it started printing this:

>Difference(Difference(Difference(Difference(Difference(Difference(Difference(Difference(Difference(Difference(Difference(Difference(Difference(Difference(Difference(Difference(Difference(Difference(Difference(Difference(Difference(Difference(Difference(Difference(Difference(Difference(Difference(Difference(Difference

It wouldn't stop until I killed the process.

I read the source file set.rs and I couldn't find any Debug implementation or derivation for Difference struct so I think it might be related somehow. I don't really know how it compiles without Debug being implemented / derived on this struct but I don't understand how language intrinsics work just yet.

## Meta

`rustc --version --verbose
rustc 1.18.0-nightly (28a742997 2017-04-13)
binary: rustc
commit-hash: 28a74299778cdad4ea999e4ee8f8c1ef793338bd
commit-date: 2017-04-13
host: x86_64-apple-darwin
release: 1.18.0-nightly
LLVM version: 3.9'

It doesn't panic so there's no backtrace to put here.

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Fixes #41338.

### CODE REVIEW

**Comment by sfackler** [comment]
How is this going to fix things? Isn't it just going to recurse the same way?

**Comment by GuillaumeGomez** [comment]
You give me a doubt on the fact that I tested correctly.

**Comment by GuillaumeGomez** [comment]
Fixed for good this time.

File: src/libcollections/btree/set.rs [hunk 1]
```diff
@@ -137,9 +137,7 @@ pub struct Difference<'a, T: 'a> {
 #[stable(feature = "collection_debug", since = "1.17.0")]
 impl<'a, T: 'a + fmt::Debug> fmt::Debug for Difference<'a, T> {
     fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
-        f.debug_tuple("Difference")
-         .field(&self.clone())
-         .finish()
+        write!(f, "Difference({:?}, {:?})", self.a, self.b)
```
Comment (ollie27) [inline src/libcollections/btree/set.rs]: It would be better to use `f.debug_tuple("Difference").field(&self.a).field(&self.b).finish()` but in this case as it's including every field, `#[derive(Debug)]` would suffice.

However, like other iterators in `std` this could use `f.debug_list().entries(self.clone()).finish()` to display a list of the items the iterator will return.

**Review by ollie27 — CHANGES_REQUESTED** [review]
Looking at #39002, the same mistake was made for the following types as well which need to be fixed:

```
enum_set::Iter
linked_list::Iter
linked_list::IterMut
linked_list::IntoIter
linked_list::FrontPlace
linked_list::BackPlace
vec_deque::Iter
vec_deque::IterMut
vec_deque::IntoIter
vec_deque::Drain
```

File: src/libcollections/btree/set.rs (hunk 1 above)
Comment (GuillaumeGomez) [inline src/libcollections/btree/set.rs]: This seems like a better idea. Updating and testing.

**Comment by GuillaumeGomez** [comment]
Updated.

**Comment by alexcrichton** [comment]
@bors: retry

* std.dll issue https://github.com/rust-lang/rust/issues/41006
