### PR TITLE
Fix leak in Vec::extend_from_within

### LINKED ISSUE #82533: `extend_from_within` leaks elements on panic
https://github.com/rust-lang/rust/blob/98f8cce6db6c6c6660eeffee2b3903104e547ecf/library/alloc/src/vec/mod.rs#L2163-L2182

Looking here, the internal length of the vector is only adjusted at the end of the loop

This has the caveat that if cloning panics, the Vec will start to unwind and only drop the first `len` elements which doesn't include the most recently appended ones.

Something more in line with how the stdlib does things might look like this:
https://github.com/LeonineKing1199/minivec/blob/424354dfababae7101aacf70fa9332a87e9cdb15/src/lib.rs#L1612-L1700

### PR DESCRIPTION
**Pull request by WaffleLapkin**
Fixes #82533

### CODE REVIEW

File: library/alloc/src/vec/mod.rs [hunk 1]
```diff
@@ -1942,6 +1942,18 @@ impl<T, A: Allocator> Vec<T, A> {
...
     pub fn split_at_spare_mut(&mut self) -> (&mut [T], &mut [MaybeUninit<T>]) {
+        // SAFETY:
+        // - len is ignored and so never changed
+        let (init, spare, _) = unsafe { self.split_at_spare_mut_with_len() };
+        (init, spare)
+    }
+
+    /// Safety: changing returned .2 (&mut usize) is considered the same as calling `.set_len(_)`.
+    ///
+    /// This method is used to have unique access to all vec parts at once in `extend_from_within`.
```
Comment (pickfire) [inline library/alloc/src/vec/mod.rs:1953]: s/is used to have/provides/ would be clearer

File: library/alloc/src/vec/mod.rs [hunk 2]
```diff
@@ -2165,22 +2177,23 @@ trait ExtendFromWithinSpec {
...
+        // - caller guaratees that src is a valid index
+        let to_clone = unsafe { this.get_unchecked(src) };
+
+        to_clone
+            .iter()
+            .cloned()
+            .zip(spare.iter_mut())
+            .map(|(src, dst)| dst.write(src))
+            // Note:
+            // - Element was just initialized with `MaybeUninit::write`, so it's ok to increace len
```
Comment (pickfire) [inline library/alloc/src/vec/mod.rs:2194]: s/increace/increase/

File: library/alloc/src/vec/mod.rs [hunk 3]
```diff
@@ -2165,22 +2177,23 @@ trait ExtendFromWithinSpec {
...
+            // - len is increased after each element to prevent leaks (see issue #82533)
+            .for_each(|_| *len += 1);
```
Comment (pickfire) [inline library/alloc/src/vec/mod.rs:2196]: Should't this be done with Drop in case the thread panic or something happens?

File: library/alloc/src/vec/mod.rs [hunk 4]
```diff
@@ -2165,22 +2177,23 @@ trait ExtendFromWithinSpec {
...
-            let new_len = self.len() + initialized;
-            self.set_len(new_len);
-        }
+        // - caller guaratees that src is a valid index
+        let to_clone = unsafe { this.get_unchecked(src) };
+
+        to_clone
+            .iter()
+            .cloned()
+            .zip(spare.iter_mut())
```
Comment (pickfire) [inline library/alloc/src/vec/mod.rs:2191]: Why do we need to write byte by byte?

File: library/alloc/src/vec/mod.rs (hunk 3 above)
Comment (WaffleLapkin) [reply library/alloc/src/vec/mod.rs:2196]: `Vec` already implements `Drop` so that's enough.

File: library/alloc/src/vec/mod.rs (hunk 4 above)
Comment (WaffleLapkin) [reply library/alloc/src/vec/mod.rs:2191]: It isn't bytes, it's `T`s. There simply isn't a way to clone multiple elements at the same time.
