### PR TITLE
Check code blocks tags

### LINKED ISSUE #71347: Emit a warning when a codeblock is using "compile-fail" instead of "compile_fail"
I just found out that a lot of error code explanations were using "compile-fail" instead of "compile_fail". I'm fixing this issue as part of something a bit bigger, however I assume this error is pretty common in rust and that rustdoc should warn people about it.

The big issue here is that since it's not a known tag, rustdoc doesn't recognize the codeblock as a rust one and therefore doesn't test it, which is pretty bad.

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Fixes #71347.

Explanations here: I realized recently that it was a common issue to confuse/misspell tags on code blocks. This is actually quite a big issue since it generally ends up in a code blocks being ignored since it's not being considered as a rust one. With this new warning, users will at least be notified about it.

PS: some improvements can be done on the error rendering but considering how big the PR already is, I think it's better to do it afterwards.

r? @ollie27 

cc @rust-lang/rustdoc

### CODE REVIEW

File: src/librustdoc/html/markdown.rs [hunk 1]
```diff
@@ -715,6 +778,53 @@ impl LangString {
                         seen_other_tags = true;
                     }
                 }
+                x if extra.is_some() => {
+                    let s = x.to_lowercase();
```
Comment (kinnison) [inline src/librustdoc/html/markdown.rs:782]: Without this line, the comparisons of `s == "compile_fail"` etc are pointless, but none of the test cases cover `COMPILE_FAIL` and friends.

File: src/librustdoc/html/markdown.rs [hunk 2]
```diff
@@ -715,6 +778,53 @@ impl LangString {
...
+                            "the code block will either not be tested if not marked as a rust one \
+                             or the code will be wrapped inside a main function",
+                        ))
+                    } else {
+                        None
+                    } {
+                        Some((flag, help)) => {
+                            if let Some(ref extra) = extra {
+                                extra.error_invalid_codeblock_tag(
+                                    &format!("flag `{}` looks like `{}` but isn't", x, flag),
```
Comment (kinnison) [inline src/librustdoc/html/markdown.rs:819]: Here you refer to them as flags rather than tags.  Which is more correct?

Also it might be a nicer error message if it were:
```suggestion
                                    &format!("unknown flag `{}`. Did you mean `{}`?", x, flag),
```

File: src/librustdoc/html/markdown.rs [hunk 3]
```diff
@@ -715,6 +778,53 @@ impl LangString {
                         seen_other_tags = true;
                     }
                 }
+                x if extra.is_some() => {
+                    let s = x.to_lowercase();
+                    match if s == "compile-fail" || s == "compile_fail" || s == "compilefail" {
+                        Some((
+                            "compile_fail",
+                            "the code block will either not be tested if not marked as a rust one \
```
Comment (kinnison) [inline src/librustdoc/html/markdown.rs:786]: Rather than this either/or can we please check if the block would be considered rust and be a little more specific?  If that's a pain then fair enough we can skip it for now.

File: src/librustc_session/lint/builtin.rs [hunk 4]
```diff
@@ -386,6 +386,12 @@ declare_lint! {
     "failures in resolving intra-doc link targets"
 }
 
+declare_lint! {
+    pub INVALID_CODEBLOCK_TAG,
+    Warn,
+    "codeblock tag looks a lot like a known one"
```
Comment (kinnison) [inline src/librustc_session/lint/builtin.rs:392]: Here you call them tags rather than flags.  Which is it?

**Review by kinnison — CHANGES_REQUESTED** [review]
At minimum we need to test that `COMPILE_FAIL` and friends are correctly handled.

File: src/librustc_session/lint/builtin.rs (hunk 4 above)
Comment (GuillaumeGomez) [reply src/librustc_session/lint/builtin.rs:392]: I don't know actually. Any suggestion is very welcome. :)

Comment (kinnison) [reply src/librustc_session/lint/builtin.rs:392]: The rustdoc book calls these 'attributes'

https://doc.rust-lang.org/rustdoc/documentation-tests.html#attributes

File: src/librustdoc/html/markdown.rs (hunk 1 above)
Comment (GuillaumeGomez) [reply src/librustdoc/html/markdown.rs:782]: Arf indeed! Good catch!

File: src/librustdoc/html/markdown.rs (hunk 3 above)
Comment (GuillaumeGomez) [reply src/librustdoc/html/markdown.rs:786]: No, I thought about it but wasn't sure. Let's go for it then!

File: src/librustdoc/html/markdown.rs (hunk 2 above)
Comment (GuillaumeGomez) [reply src/librustdoc/html/markdown.rs:819]: After a discussion, @kinnison discovered that it was called "attributes" in pandoc and in rustdoc book so I'll update this PR accordingly.

File: src/librustdoc/html/markdown.rs (hunk 3 above)
Comment (GuillaumeGomez) [reply src/librustdoc/html/markdown.rs:786]: This is actually far more complicated than I imagined... I think it'll have to be a PR on its own...

**Comment by GuillaumeGomez** [comment]
Updated!

File: src/librustdoc/html/markdown.rs (hunk 3 above)
Comment (kinnison) [reply src/librustdoc/html/markdown.rs:786]: OK

**Review by kinnison — COMMENTED** [review]
The test files still call them tags, otherwise looks good.

**Comment by GuillaumeGomez** [comment]
Renamed the tests files. :3

**Review by kinnison — APPROVED** [review]

**Comment by flip1995** [comment]
This PR introduced a weird regression in Clippy, see https://github.com/rust-lang/rust-clippy/runs/613510829#step:14:47

I guess this lint is now enabled for code blocks but wasn't before?

**Comment by GuillaumeGomez** [comment]
It wasn't indeed. And it's not a regression, it just means that you you incorrect attributes (which is a good news I guess).
