### PR TITLE
Detect `for _ in in bar {}` typo

### LINKED ISSUE #36611: error: expected one of `{` or an operator, found `}`
I did a stupid typo in a program, where I typed `in` twice in a `for` statement:

``` rust
fn main() {
    for i in in 1..2 {
        println!("{}", i);
    }
}
```

The compiler pointed the error on the closing brace, which, in the real code, with much more things happening in the loop (plus nested loops) was completely unhelpful.

```
error: expected one of `{` or an operator, found `}`
 --> <anon>:5:1
  |
5 | }
  | ^

error: aborting due to previous error
```

### PR DESCRIPTION
**Pull request by estebank**
Fix #36611, #52964, without modifying the parsing of emplacement `in` to avoid further problems like #50832.

### CODE REVIEW

File: src/libsyntax/parse/parser.rs [hunk 1]
```diff
@@ -3422,6 +3422,24 @@ impl<'a> Parser<'a> {
...
+                self.prev_span,
+                "expected iterable, found keyword `in`",
+            );
+            err.span_suggestion_short_with_applicability(
+                in_span.until(self.prev_span),
+                "remove the duplicated `in`",
+                String::new(),
+                Applicability::MachineApplicable,
+            );
+            err.note("if you meant to use emplacement syntax, it is obsolete (for now, anyways)");
```
Comment (theotherphil) [inline src/libsyntax/parse/parser.rs]: Nit: “anyways” should be “anyway”
