### PR TITLE
Keep track of patterns that could have introduced a binding, but didn't

### LINKED ISSUE #74863: Error on struct pattern with enum
The following code doesn't compiles:

```rust
struct Website {
    url: String,
    title: Option<String>,
}

fn main() {
    let website = Website {
        url: "http://www.example.com".into(),
        title: Some("Example Domain".into()),
    };

    if let Website { url, Some(title) } = website {
        println!("[{}]({})", title, url);
    }
}
```

The compile error:

```console
error: expected `,`
  --> src/main.rs:14:27
   |
14 |     if let Website { url, Some(title) } = website {
   |                           ^^^^

error[E0425]: cannot find value `title` in this scope
  --> src/main.rs:15:30
   |
15 |         println!("[{}]({})", title, url);
   |                              ^^^^^ not found in this scope

error[E0423]: expected value, found crate `url`
  --> src/main.rs:15:37
   |
15 |         println!("[{}]({})", title, url);
   |                                     ^^^ not a value

error: aborting due to 3 previous errors
```

If I use an tuple instead, the code compiles:

```rust
struct Website(String, Option<String>);

fn main() {
    let website = Website(
        "http://www.example.com".into(),
        Some("Example Domain".into()),
    );

    if let Website(url, Some(title)) = website {
        println!("[{}]({})", title, url);
    }
}
```

### Meta

`rustc --version --verbose`:
```
rustc 1.45.0 (5c1f21c3b 2020-07-13)
binary: rustc
commit-hash: 5c1f21c3b82297671ad3ae1e8c942d2ca92e84f2
commit-date: 2020-07-13
host: x86_64-unknown-linux-gnu
release: 1.45.0
LLVM version: 10.0
```

### PR DESCRIPTION
**Pull request by estebank**
When we recover from a pattern parse error, or a pattern uses `..`, we keep track of that and affect resolution error for missing bindings that could have been provided by that pattern. We differentiate between `..` and parse recovery. We silence resolution errors likely caused by the pattern parse error.

```
error[E0425]: cannot find value `title` in this scope
  --> $DIR/struct-pattern-with-missing-fields-resolve-error.rs:18:30
   |
LL |     if let Website { url, .. } = website {
   |            ------------------- this pattern doesn't include `title`, which is available in `Website`
LL |         println!("[{}]({})", title, url);
   |                              ^^^^^ not found in this scope
```

Fix #74863.

### CODE REVIEW

File: compiler/rustc_resolve/src/late.rs [hunk 1]
```diff
@@ -264,12 +264,17 @@ impl RibKind<'_> {
 #[derive(Debug)]
 pub(crate) struct Rib<'ra, R = Res> {
     pub bindings: IdentMap<R>,
+    pub patterns_with_skipped_bindings: FxHashMap<DefId, Vec<(Span, bool /* recovered error */)>>,
```
Comment (compiler-errors) [inline compiler/rustc_resolve/src/late.rs:267]: why use a bool for recovered error when we have `Result<(), ErrorGuaranteed>`?
