### PR TITLE
Discuss pitfalls of stateful closures with Map

### LINKED ISSUE #30632: Clarify behavior of map/filter
Apparently `iter::Map` and `iter::Filter` implement `DoubleEndedIterator`. This could lead to unexpected behavior:

```
let counter = iter::repeat(()).map({
    let mut ctr = 0;
    move |_| {
        ctr += 1;
        ctr
    }
});

let counter2 = counter.reverse(); // Doesn't reverse anything.
```

These adapters are only really reversible when passed closure is side-effect free. Unfortunately, we can't simply say that `map` calls the passed closure on each element yielded because `counter.last() != counter.reverse().next()`.

### PR DESCRIPTION
**Pull request by steveklabnik**
Fixes #30632

I'm not sure if this explanation is good enough. If it is, I will add it to filter as well.

### CODE REVIEW

File: src/libcore/iter.rs [hunk 1]
```diff
@@ -3270,6 +3270,37 @@ impl<A, B> DoubleEndedIterator for Zip<A, B> where
...
+/// ```rust
+/// let counter = vec![1, 2, 3].into_iter().map({
+///     let mut ctr = 0;
+///     move |_| {
+///        ctr += 1;
+///         ctr
+///     }
+/// });
+///
+/// let counter2 = counter.reverse();
```
Comment (bluss) [inline src/libcore/iter.rs]: .rev()

**Comment by bluss** [comment]
Maybe it can instead underline that the map's closure is called on elements in the order they are "extracted" from the iterator (i.e. if you mix next/next_back or call just next_back etc). Saying that the iteration is not backwards is too confusable with how `map()` takes elements from the underlying iterator.

File: src/libcore/iter.rs (hunk 1 above)
Comment (steveklabnik) [inline src/libcore/iter.rs]: ugh, i fixed it in my test but not when I put it over here. was too worried about the words

Comment (nikomatsakis) [inline src/libcore/iter.rs]: I think I would find the example clearer if you included the items being iterated over, and they were not the numbers 1, 2, and 3. For example:

```
vec!['a', 'b', 'c'].into_iter().map(...).rev();
```

will produce `('c', 1), ('b', 2), ('a', 3)`, right?

Comment (steveklabnik) [inline src/libcore/iter.rs]: Ah, this is a good point. Yes, something like this would be much better.

**Comment by steveklabnik** [comment]
Okay, so i pushed a new commit which actually fails. The weird thing about doing what @nikomatsakis says is that it does illustrate what's happening better, which, uh, makes it feel not weird. And so now this documentation feels strange, because it feels like it's saying "hey this is so counterintuitive"... but it's not.

So, I'm kinda almost leaning towards not writing something about this. Yes, writing weird code might be a bit confusing, but you're also writing odd code? I dunno.

File: src/libcore/iter.rs [hunk 2]
```diff
@@ -3270,6 +3270,50 @@ impl<A, B> DoubleEndedIterator for Zip<A, B> where
...
+/// However, if you call `.rev()` to iterate in the other direction, it
+/// will only be 'backwards' if your closure has no state. In other words,
+/// something like this might act in a way that you wouldn't expect:
+///
+/// ```rust
+/// // This iterator uses a closure that has side effects to count the number
+/// // of iterations.
+/// let counter = vec!['a', 'b', 'c'].into_iter().map({
+///     let mut count = 0;
+///     move |a| {
```
Comment (frewsxcv) [inline src/libcore/iter.rs]: Minor nit: using the variable name `a` when `'a'` is being iterated over is slightly confusing

Comment (steveklabnik) [inline src/libcore/iter.rs]: agreed

File: src/libcore/iter.rs [hunk 3]
```diff
@@ -3270,6 +3270,50 @@ impl<A, B> DoubleEndedIterator for Zip<A, B> where
...
+/// let v: Vec<i32> = vec![1, 2, 3].into_iter().rev().map(|x| x + 1).collect();
+///
+/// assert_eq!(v, [4, 3, 2]);
+/// ```
+///
+/// [`DoubleEndedIterator`]: trait.DoubleEndedIterator.html
+///
+/// However, if you call `.rev()` to iterate in the other direction, it
+/// will only be 'backwards' if your closure has no state. In other words,
+/// something like this might act in a way that you wouldn't expect:
```
Comment (nikomatsakis) [inline src/libcore/iter.rs]: I still feel like this text leaves too much to the reader. Some context: I think it's great to add a note here, because this can be really confusing. It definitely confounded me for a bit the first time I ran into it. In your example below, you never walk through what's happening, just say that it's the same, so the reader is left to step through the code on their own.

I would prefer an [example like this](http://is.gd/R3u5Xy). I included some comments that also give the explanatory notes I wanted:

```rust
fn main() {
    // Prints ('a', 1), ('b', 2), ('c', 3), as expected.
    let mut c = 0;
    for pair in vec!['a', 'b', 'c'].into_iter()
                                   .map(|letter| { c += 1; (letter, c) }) {
        println!("{:?}", pair);
    }

    // Now we add a call to `rev`. Prints ('c', 1), ('b', 2), ('a', 3).
    // Note that the letters are reversed, but the values of the counter
    // still go in order. This is because `map` is still being called lazilly
    // on each item, it's just that we are popping items off the back of
    // the vector now, instead of shifting them from the front.
    c = 0;
    for pair in vec!['a', 'b', 'c'].into_iter()
                                   .map(|letter| { c += 1; (letter, c) })
                                   .rev() {
        println!("{:?}", pair);
    }
}
```

(Also, isn't your code wrong? They don't, in fact, produce the same thing?)

Comment (nikomatsakis) [inline src/libcore/iter.rs]: Oh, a few other things. I intentionally used a counter declared in the surrounding function, since then we don't have to use a `move` closure, and we don't have to play tricky games with state.

Comment (steveklabnik) [inline src/libcore/iter.rs]: > (Also, isn't your code wrong? They don't, in fact, produce the same thing?)

Sorry, that's what I was trying to say in the issue itself; once you get this example, where they're now different, it doesn't seem like strange behavior anymore.

Comment (steveklabnik) [inline src/libcore/iter.rs]: (that said, maybe that version of the example is way more clear, yeah. Okay. :+1: )

**Comment by nikomatsakis** [comment]
@steveklabnik planning to update?

**Comment by steveklabnik** [comment]
Yes, later today.

**Comment by steveklabnik** [comment]
@nikomatsakis I have updated it to your example, with one or two minor wording/format tweaks.

I was trying to think of a way to get away from 'printing' examples, as I don't like them as much as assertions, since printing won't be automatically tested, but assertions end up just looking awkward in examples like this, so I don't think I can do much better.

**Comment by nikomatsakis** [comment]
@steveklabnik 

> I was trying to think of a way to get away from 'printing' examples, as I don't like them as much as assertions, since printing won't be automatically tested, but assertions end up just looking awkward in examples like this, so I don't think I can do much better.

I see. Makes sense. But I agree that here printing is natural -- also, this feels like an example that is unlikely to bitrot.

**Comment by nikomatsakis** [comment]
Note travis failure:

> /home/travis/build/rust-lang/rust/src/libcore/iter.rs:3299: trailing whitespace

Seems legit?

The only other nit is that maybe it'd be better to separate the two examples a bit. e.g., 

```
+/// However, if you call `.rev()` to iterate in the other direction, it
+/// will only be 'backwards' if your closure has no state. As an example,
+/// consider this loop, which iterates *forward* and uses `map` to
+/// track a mutable counter. This will print out `"('a', 1), ('b', 2), ('c', 3)"`.
+///
+/// ```rust
+/// let mut c = 0;
+///
+/// for pair in vec!['a', 'b', 'c'].into_iter()
+///                                .map(|letter| { c += 1; (letter, c) }) {
+///     println!("{:?}", pair);
+/// }
+/// ```
+///
+/// Now consider this twist on the previous example, where we add
+/// a call to `rev`. This version will print `('c', 1), ('b', 2), ('a', 3)`.
+/// Note that the letters are reversed, but the values of the counter
+/// still go in order. This is because `map` is still being called lazilly
+/// on each item, but we are popping items off the back of the vector now,
+/// instead of shifting them from the front.
+///
+/// ```
+/// let mut c = 0;
+///
+/// for pair in vec!['a', 'b', 'c'].into_iter()
+///                                .map(|letter| { c += 1; (letter, c) })
+///                                .rev() {
+///     println!("{:?}", pair);
+/// }
+/// ```
```

**Comment by nikomatsakis** [comment]
r=me either to the current commit or a version like what I suggested, once travis failure is resolved.

**Comment by steveklabnik** [comment]
I was thinking of the same thing. Tidy passes, and I changed to that.

@bors: r=nikomatsakis rollup

**Comment by steveklabnik** [comment]
Okay. This time I checked that both the tests _and_ `make tidy` passed, and re-worded some stuff a bit.

**Comment by nikomatsakis** [comment]
This is a work of art.

@bors r+ rollup

**Comment by steveklabnik** [comment]
:heart:
