### PR TITLE
Fix bootstrap locking

### LINKED ISSUE #109967: bootstrap: build locking doesn't work any more
I tried this code:

```rust
x t tidy & x t tidy
```

I expected to see this happen: Bootstrap is built, and one process runs tidy while the other says "waiting for build lock"

Instead, this happened:
```
; x t tidy & x t tidy 
[1] 34539
Building bootstrap
Building bootstrap
    Blocking waiting for file lock on build directory
    Finished dev [unoptimized] target(s) in 0.20s
    Finished dev [unoptimized] target(s) in 0.24s
Building tool tidy (stage0)
warning: creating symbolic link `/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-sysroot/lib/rustlib/src/rust` to `/Users/jyn/src/rust` failed with File exists (os error 17)
warning: creating symbolic link `/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-sysroot/lib/rustlib/rustc-src/rust` to `/Users/jyn/src/rust` failed with File exists (os error 17)
Building tool tidy (stage0)
    Finished release [optimized] target(s) in 0.98s
fmt check
    Finished release [optimized] target(s) in 1.14s
fmt check
```

### Meta

HEAD is branched from 90a9f69c80812c8694959c1f2d5c336e3300d1e2. 
```
; uname -a
Darwin jyns-MacBook-Pro 22.4.0 Darwin Kernel Version 22.4.0: Mon Mar  6 20:59:28 PST 2023; root:xnu-8796.101.5~3/RELEASE_ARM64_T6000 arm64
```

### PR DESCRIPTION
**Pull request by albertlarsan68**
Fix the regression introduced in #108607

Fixes #109967

### CODE REVIEW

File: src/bootstrap/bin/main.rs [hunk 1]
```diff
@@ -15,10 +15,12 @@ fn main() {
     let args = env::args().skip(1).collect::<Vec<_>>();
     let config = Config::parse(&args);
 
+    #[cfg(all(any(unix, windows), not(target_os = "solaris")))]
```
Comment (ozkanonur) [inline src/bootstrap/bin/main.rs:18]: Shouldn't this check only if not solaris?

Comment (albertlarsan68) [reply src/bootstrap/bin/main.rs:18]: We currently lock only on unix and windows, but not solaris. There may be other platforms that are used as host bootstrap that aren't unix-like or windows, and we don't support locking for them either.
