### PR TITLE
Fix range literals borrowing suggestions

### LINKED ISSUE #54505: Incorrect borrowing suggestion for range literals
```rust
use std::ops::RangeInclusive;

fn take_range(r: &RangeInclusive<i8>) {}

fn main() {
    take_range(0..=1);
}
```

```
error[E0308]: mismatched types
 --> src/main.rs:6:16
  |
6 |     take_range(0..=1);
  |                ^^^^^
  |                |
  |                expected reference, found struct `std::ops::RangeInclusive`
  |                help: consider borrowing here: `&0..=1`
  |
  = note: expected type `&std::ops::RangeInclusive<i8>`
             found type `std::ops::RangeInclusive<{integer}>`
```

`&0..=1` is an incorrect suggestion because `&` has higher precedence than `..=`. It should suggest `&(0..=1)`.

### PR DESCRIPTION
**Pull request by pawroman**
Fixes #54505. The compiler issued incorrect range borrowing suggestions (missing `()` around borrows of range literals). This was not correct syntax (see the issue for an example).

With changes in this PR, this is fixed for all types of `Range` literals.

Thanks again to @varkor and @estebank for their invaluable help and guidance.

r? @varkor

### CODE REVIEW

File: src/librustc_typeck/check/demand.rs [hunk 1]
```diff
@@ -309,11 +309,16 @@ impl<'a, 'gcx, 'tcx> FnCtxt<'a, 'gcx, 'tcx> {
...
+                            // parenthesize if needed (Issue #46756)
                             hir::ExprKind::Cast(_, _) |
-                            hir::ExprKind::Binary(_, _, _) => format!("({})", src),
-                            _ => src,
+                            hir::ExprKind::Binary(_, _, _) => true,
+                            // parenthesize borrows of range literals (Issue #54505)
+                            _ if self.is_range_literal(expr) => true,
+                            _ => false,
                         };
+                        let sugg_expr = if needs_parens { format!("({})", src) } else { src };
```
Comment (varkor) [inline src/librustc_typeck/check/demand.rs]: Generally prefer to split `if`-`else` across separate lines.

File: src/librustc_typeck/check/demand.rs [hunk 2]
```diff
@@ -374,6 +379,77 @@ impl<'a, 'gcx, 'tcx> FnCtxt<'a, 'gcx, 'tcx> {
...
+            // Ranges constructed with non-literals.
+            let source_map = self.tcx.sess.source_map();
+            let end_point = source_map.end_point(*span);
+
+            if let Ok(end_string) = source_map.span_to_snippet(end_point) {
+                end_string.ends_with("}") || end_string.ends_with(")")
+            } else {
+                false
+            }
+
```
Comment (varkor) [inline src/librustc_typeck/check/demand.rs]: Nit: delete blank line here.

File: src/librustc_typeck/check/demand.rs [hunk 3]
```diff
@@ -374,6 +379,77 @@ impl<'a, 'gcx, 'tcx> FnCtxt<'a, 'gcx, 'tcx> {
...
+                            match_seg.split("|")
+                                .into_iter()
+                                .any(|ref spl_seg| seg == spl_seg)
+                        })
+            } else {
+                false
+            }
+        };
+
+        let is_range_struct_snippet = |span: &Span| {
```
Comment (varkor) [inline src/librustc_typeck/check/demand.rs]: I'd negate this function: call it something like `is_range_literal` and invert the return value. You currently just use it as `!is_range_struct_snippet`, so it makes sense to flip it here.

File: src/librustc_typeck/check/demand.rs [hunk 4]
```diff
@@ -374,6 +379,77 @@ impl<'a, 'gcx, 'tcx> FnCtxt<'a, 'gcx, 'tcx> {
...
+            if let Ok(end_string) = source_map.span_to_snippet(end_point) {
+                end_string.ends_with("}") || end_string.ends_with(")")
+            } else {
+                false
+            }
+
+        };
+
+        match expr.node {
+            // all built-in range literals but `..=` and `..`
```
Comment (varkor) [inline src/librustc_typeck/check/demand.rs]: Nit: `All`.

File: src/librustc_typeck/check/demand.rs [hunk 5]
```diff
@@ -374,6 +379,77 @@ impl<'a, 'gcx, 'tcx> FnCtxt<'a, 'gcx, 'tcx> {
...
+            // desugar to Structs, `..` desugars to its struct path
+            ExprKind::Struct(QPath::Resolved(None, ref path), _, _) |
+            ExprKind::Path(QPath::Resolved(None, ref path)) => {
```
Comment (varkor) [inline src/librustc_typeck/check/demand.rs]: Move the comment about `..` to above this line for clarity.

File: src/librustc_typeck/check/demand.rs [hunk 6]
```diff
@@ -374,6 +379,77 @@ impl<'a, 'gcx, 'tcx> FnCtxt<'a, 'gcx, 'tcx> {
...
+                return is_range_path(&path) && !is_range_struct_snippet(&expr.span);
+            }
+
+            // `..=` desugars into RangeInclusive::new(...)
+            ExprKind::Call(ref func, _) => {
+                if let ExprKind::Path(QPath::TypeRelative(ref ty, ref segment)) = func.node {
+                    if let TyKind::Path(QPath::Resolved(None, ref path)) = ty.node {
+                        let calls_new = segment.ident.as_str() == "new";
```
Comment (varkor) [inline src/librustc_typeck/check/demand.rs]: Maybe `call_to_new` would be slightly clearer?

File: src/librustc_typeck/check/demand.rs [hunk 7]
```diff
@@ -374,6 +379,77 @@ impl<'a, 'gcx, 'tcx> FnCtxt<'a, 'gcx, 'tcx> {
...
+                        return is_range_path(&path) && calls_new &&
+                            !is_range_struct_snippet(&expr.span);
+                    }
+                }
+            }
+
+            _ => {}
+        }
+
+        false
```
Comment (varkor) [inline src/librustc_typeck/check/demand.rs]: Instead of explicitly returning `false` here, you could just move it inside the `match` (and get rid of the `return`s elsewhere).

File: src/test/ui/range/issue-54505-no-literals.fixed [hunk 8]
```diff
@@ -0,0 +1,85 @@
+// Copyright 2018 The Rust Project Developers. See the COPYRIGHT
```
Comment (varkor) [inline src/test/ui/range/issue-54505-no-literals.fixed]: Copyright notices are no longer needed — you can just get rid of this (and elsewhere).

File: src/librustc_typeck/check/demand.rs [hunk 9]
```diff
@@ -374,6 +379,77 @@ impl<'a, 'gcx, 'tcx> FnCtxt<'a, 'gcx, 'tcx> {
         None
     }
 
+    // This function checks if the specified expression is a built-in range literal
```
Comment (varkor) [inline src/librustc_typeck/check/demand.rs]: Use `///` for documentation comments for functions. (Nit: And full stops for the ends of sentences 😄)

File: src/librustc_typeck/check/demand.rs [hunk 10]
```diff
@@ -374,6 +379,77 @@ impl<'a, 'gcx, 'tcx> FnCtxt<'a, 'gcx, 'tcx> {
...
+    // (See: librustc/hir/lowering.rs::LoweringContext::lower_expr() )
```
Comment (varkor) [inline src/librustc_typeck/check/demand.rs]: Nit: I'd surround the path with backticks, like any piece of code.

File: src/librustc_typeck/check/demand.rs [hunk 11]
```diff
@@ -374,6 +379,77 @@ impl<'a, 'gcx, 'tcx> FnCtxt<'a, 'gcx, 'tcx> {
...
+    fn is_range_literal(&self, expr: &hir::Expr) -> bool {
+        use hir::{Path, QPath, ExprKind, TyKind};
+
+        // we support `::std::ops::Range` and `::std::core::Range` prefixes
+        // (via split on "|")
+        let ops_path = ["{{root}}", "std|core", "ops"];
+
+        let is_range_path = |path: &Path| {
```
Comment (varkor) [inline src/librustc_typeck/check/demand.rs]: I might be alone in this (cc @estebank), but I think for a short path like this, a more explicit approach (like below) is more readable. (I specifically don't like splitting on "|" because it feels a little too ad hoc.)
```rust
let is_range_path = |path: &Path| {
    let segs = path.segments.iter().map(|seg| seg.ident.as_str());
	if let (Some("{{root}}"), std_core, "ops", range, None) = (segs.next(), segs.next(), segs.next(), segs.next(), segs.next()) {
		(std_core == "std" || std_core == "ops") && range.starts_with("Range")
	} else {
		false
	}
};
```

**Review by varkor — CHANGES_REQUESTED** [review]
This is looking really good, thanks! I've left a few comments, but they're mostly minor things. Nice work!

File: src/librustc_typeck/check/demand.rs (hunk 9 above)
Comment (pawroman) [reply src/librustc_typeck/check/demand.rs]: Right. Does nightly rustdoc support code references yet?

File: src/librustc_typeck/check/demand.rs (hunk 11 above)
Comment (pawroman) [reply src/librustc_typeck/check/demand.rs]: That's a great suggestion! I was looking for something concise like this syntax-wise, it didn't occur to me that I could use `.next()` and rely on it returning `None` when there's no more elements.

File: src/librustc_typeck/check/demand.rs (hunk 7 above)
Comment (pawroman) [reply src/librustc_typeck/check/demand.rs]: That would proliferate `else { false }` in `ExprKind::Call` match arm due to doubly-nested `if let`. Early `return` keeps it a bit shorter.

File: src/librustc_typeck/check/demand.rs (hunk 3 above)
Comment (pawroman) [reply src/librustc_typeck/check/demand.rs]: I shall rename, but one question: `is_range_literal` would shadow the encompassing `fn` (same name). Isn't that frowned upon in Rust code?

File: src/librustc_typeck/check/demand.rs [hunk 12]
```diff
@@ -379,67 +383,56 @@ impl<'a, 'gcx, 'tcx> FnCtxt<'a, 'gcx, 'tcx> {
...
-                        .all(|(seg, match_seg)| {
-                            match_seg.split("|")
-                                .into_iter()
-                                .any(|ref spl_seg| seg == spl_seg)
-                        })
+            let mut segs = path.segments.iter()
+                .map(|seg| seg.ident.as_str());
+
+            if let (Some(root), Some(std_core), Some(ops), Some(range), None) =
+                (segs.next(), segs.next(), segs.next(), segs.next(), segs.next())
```
Comment (pawroman) [inline src/librustc_typeck/check/demand.rs]: [`Ident.as_str()`](https://doc.rust-lang.org/nightly/nightly-rustc/syntax_pos/symbol/struct.Ident.html#method.as_str) returns a `LocalInternedString` which can be compared with `&str`, but I found it too verbose to use in `Some()`.

File: src/librustc_typeck/check/demand.rs (hunk 3 above)
Comment (varkor) [reply src/librustc_typeck/check/demand.rs]: Oh, I didn't spot that: `is_range_path` is clearer, you're right 👍

File: src/librustc_typeck/check/demand.rs (hunk 7 above)
Comment (varkor) [reply src/librustc_typeck/check/demand.rs]: Ah, that's true!

File: src/librustc_typeck/check/demand.rs (hunk 9 above)
Comment (varkor) [reply src/librustc_typeck/check/demand.rs]: As in references to source files? Not that I'm aware of.

File: src/librustc_typeck/check/demand.rs [hunk 13]
```diff
@@ -374,6 +383,66 @@ impl<'a, 'gcx, 'tcx> FnCtxt<'a, 'gcx, 'tcx> {
         None
     }
 
+    /// This function checks if the specified expression is a built-in range literal.
+    /// (See: ``librustc::hir::lowering::LoweringContext::lower_expr()``).
```
Comment (varkor) [inline src/librustc_typeck/check/demand.rs]: Sorry, I meant single rather than double backticks; I should have clarified. On second thoughts, though, it might be more convenient to include the path:
```rust
/// (See `LoweringContext::lower_expr()` in `src/librustc/hir/lowering.rs`.)
```
as then someone can jump straight to the path. (Like in the following.)
https://github.com/rust-lang/rust/blob/f89622a7548f69c76e5c9857e34be568ba322d02/src/librustc_privacy/lib.rs#L1388

File: src/librustc_typeck/check/demand.rs [hunk 14]
```diff
@@ -374,6 +383,66 @@ impl<'a, 'gcx, 'tcx> FnCtxt<'a, 'gcx, 'tcx> {
...
+            {
+                // "{{root}}" is the equivalent of `::` prefix in Path
+                root == "{{root}}" && (std_core == "std" || std_core == "core")
+                    && ops == "ops" && range.starts_with("Range")
+            } else {
+                false
+            }
+        };
+
+        let is_range_literal = |span: &Span| {
```
Comment (varkor) [inline src/librustc_typeck/check/demand.rs]: As [you pointed out](https://github.com/rust-lang/rust/pull/54734#discussion_r222110792), it would be clearer to give this a different name than the function it's in. Maybe `span_is_range_literal` or something like that?

File: src/librustc_typeck/check/demand.rs [hunk 15]
```diff
@@ -374,6 +383,66 @@ impl<'a, 'gcx, 'tcx> FnCtxt<'a, 'gcx, 'tcx> {
...
+            // Tell if expression span snippet doesn't look like an explicit
+            // Range struct or `new()` call.  This is to allow inferring
```
Comment (varkor) [inline src/librustc_typeck/check/demand.rs]: "Inferring" has a very specific meaning, so I'd tend to avoid it in favour of something like:
```rust
// Check whether a span corresponding to a range is a range literal,
// rather than an explicit struct or `new()` call.
```

**Comment by varkor** [comment]
Some very minor comments to follow up, just to make things a little more readable. After this, it all looks good to me!

**Comment by pawroman** [comment]
Addressed them now -- thanks for review and please let me know if anything else.

**Comment by varkor** [comment]
Great, thanks for fixing this @pawroman!

@bors r+

**Comment by pawroman** [comment]
Uh oh! Will look into this as soon as I have some spare time.

**Comment by pawroman** [comment]
I have attempted a fix -- unfortunately having trouble getting the toolchain to work with wasm target, so can't test that at the moment. Any help with this would be appreciated. Alternatively, we can lean on the automated CI process to test with wasm target.

**Comment by pawroman** [comment]
Hmm, the failure appears unrelated at first glance. I'm seeing `Permission denied` in `stderr`. Any clues?

**Comment by varkor** [comment]
The error is confusing. It's referencing `issue-19100\a.exe`, but it doesn't appear to be a test that should be generated ancillary outputs. My inclination would be to rebase on top of master and see if that fixes it (you might as well squash the related "fix test" commits at the same time).

**Comment by pietroalbini** [comment]
Let's just retry.

@bors retry
