### PR TITLE
Interpolate AST nodes in quasiquote.

### LINKED ISSUE #15962: quote_* macros lose hygiene, gensym and span information
The `quote_*` macros stringify everything, which loses vital information.

```rust
// gensym.rs
#![feature(plugin_registrar, managed_boxes, quote)]
#![crate_type = "dylib"]

extern crate syntax;
extern crate rustc;

use syntax::ast;
use syntax::codemap::{Span};
use syntax::ext::base;
use syntax::ext::base::{ExtCtxt, MacExpr};
use syntax::ext::build::AstBuilder;
use syntax::parse::token;
use rustc::plugin::Registry;

#[plugin_registrar]
pub fn plugin_registrar(reg: &mut Registry) {
    reg.register_macro("test_quote", expand_syntax_ext);
}

pub fn expand_syntax_ext(cx: &mut ExtCtxt, sp: Span, _: &[ast::TokenTree]) -> Box<base::MacResult> {
    // expand to `{ let foo = true; foo }`, with a gensym'd foo.
    let ident = token::gensym_ident("foo");
    let decl = quote_stmt!(&mut *cx, let $ident = true;);
    let result = cx.expr_block(cx.block(sp, vec![decl], Some(cx.expr_ident(sp, ident))));

    println!("{}", result);

    MacExpr::new(result)
}
```

```rust
// test_gensym.rs
#![feature(phase)]

#[phase(plugin)] extern crate gensym;

fn main() {
    let a = test_quote!();
}
```

```
[...]
test_gensym.rs:6:13: 6:27 error: unresolved name `foo`.
test_gensym.rs:6     let a = test_quote!();
                             ^~~~~~~~~~~~~~
test_gensym.rs:1:1: 7:1 note: in expansion of test_quote!
test_gensym.rs:6:13: 6:27 note: expansion site
error: aborting due to previous error
```

Beautified/trimmed version of the output of the `println!`

```
Expr {
    node: ExprBlock(Block {
        view_items: [],
        stmts: [Spanned {
            node: StmtDecl(Spanned {
                node: DeclLocal(Local {
                    ty: Ty {
                        node: TyInfer,
                        span: Span {
                            lo: BytePos(7677),
                            hi: BytePos(7677),
                            expn_info: None
                        }
                    },
                    pat: Pat {
                        node: PatIdent(BindByValue(MutImmutable), Spanned {
                            node: "foo" (269),
                            span: Span {
                                lo: BytePos(7677),
                                hi: BytePos(7680),
                                expn_info: None
                            }
                        }, None),
                        span: Span {
                            lo: BytePos(7677),
                            hi: BytePos(7680),
                            expn_info: None
                        }
                    },
                    init: Some(Expr {
                        node: ExprLit(Spanned {
                            node: LitBool(true),
                            span: Span {
                                lo: BytePos(83),
                                hi: BytePos(97),
                                expn_info: None
                            }
                        }),
                        span: Span {
                            lo: BytePos(83),
                            hi: BytePos(97),
                            expn_info: None
                        }
                    }),
                    span: Span {
                        lo: BytePos(7677),
                        hi: BytePos(97),
                        expn_info: None
                    },
                    source: LocalLet
                }),
            }, 4294967295),
        }],
        expr: Some(Expr {
            node: ExprPath(Path {
                global: false,
                segments: [PathSegment {
                    identifier: "foo" (268)# 0,
                    lifetimes: [],
                    types: OwnedSlice {
                        {}
                    }
                }]
            }),
        }),
        rules: DefaultBlock,
    }),
}
```

Of particular attention is the difference in `Name` between `node: "foo" (269)`
 `identifier: "foo" (268)# 0,`, and also the `7677` etc. numbers in the spans inside the`DeclLocal`.

### LINKED ISSUE #16472: quote_expr! and friends should emit token-trees directly
The lines of code here: [quote.rs#L226](https://github.com/rust-lang/rust/blob/0dc215741b34236c310e409c437600ba0165c97c/src/libsyntax/ext/quote.rs#L226) are sub-optimal and also require hacks like the one described on [#15962](https://github.com/rust-lang/rust/issues/15962#issuecomment-50542760) to actually work correctly.

Effectively, the current code is implementing `to_tokens` by going through the transformation sequence:
```
AST -> string -> token-trees
```

The methods should instead be emitting token-trees directly from the AST, avoiding the serialization to and de-serialization from the intermediate string.

### LINKED ISSUE #16617: Syntactic context discarded when quoting a macro invocation
#15750 is fixed now, but a variant of the same issue occurs when quoting a macro invocation.

Using `plugin.rs` from #15750 and this `test.rs`:

```rust
#![feature(phase)]

#[phase(plugin)]
extern crate plugin;

fn main() {
    let x = true;
    println!("{}", mymacro!(assert!(x)));
}
```

I get this result:

```
$ rustc -v
rustc 0.12.0-pre (3f5d0b5b6 2014-08-19 16:35:51 +0000)

$ rustc plugin.rs

$ rustc -L. test.rs
<quote expansion>:1:20: 1:21 error: unresolved name `x`.
<quote expansion>:1 name_64,ctxt_11!(x)
                                       ^
<std macros>:1:1: 12:2 note: in expansion of assert!
<quote expansion>:1:1: 1:22 note: expansion site
test.rs:1:1: 9:1 note: in expansion of mymacro!
test.rs:8:20: 8:40 note: expansion site
note: in expansion of format_args!
<std macros>:2:23: 2:77 note: expansion site
<std macros>:1:1: 3:2 note: in expansion of println!
test.rs:8:5: 8:42 note: expansion site
error: aborting due to previous error
```

Also the NULL characters used to delimit the magic identifier string appear in the error output, which causes the error caret to appear in the wrong place.

See also #15962.

CC @pnkfelix. This is still a huge improvement from before and I think I can work around the remaining issues in `html5ever`. Thank you for fixing #15750 :)

### LINKED ISSUE #16987: Hygiene issues when reparsing token trees
I get errors when I call `to_tokens` on a parsed block and parse that again using procedural macros. It seems to be related to hygiene being lost when you do that, but I might be wrong, here's a gist that shows the problem: https://gist.github.com/uorbe001/1118f22c378d2e382d29

If I try to compile that gist, I get the following error on  the assert! line:
```
<quote expansion>:4:50: 4:53 error: unresolved name `one`.
<quote expansion>:4                          name_66,ctxt_2!(1i == one);
```

I thought this was related to #8063, but apparently this is a separate issue.

### LINKED ISSUE #17397: Error messages for quasiquoted code are extremely cryptic
This is an unfortunate consequence of the fix for #15750.

`plugin.rs`:

```rust
#![crate_type="dylib"]
#![feature(plugin_registrar, quote)]

extern crate syntax;
extern crate rustc;

use rustc::plugin::Registry;

use syntax::codemap::Span;
use syntax::ext::base::{ExtCtxt, MacResult, MacExpr};
use syntax::parse;
use syntax::ast;

fn expand(cx: &mut ExtCtxt, _span: Span, tts: &[ast::TokenTree])
        -> Box<MacResult+'static> {
    // Parse an expression and emit it unchanged.
    let mut parser = parse::new_parser_from_tts(cx.parse_sess(),
        cx.cfg(), Vec::from_slice(tts));
    let expr = parser.parse_expr();
    MacExpr::new(quote_expr!(&mut *cx, $expr))
}

#[plugin_registrar]
pub fn plugin_registrar(reg: &mut Registry) {
    reg.register_macro("mymacro", expand);
}
```

`test.rs`:

```rust
#![feature(phase)]

#[phase(plugin)]
extern crate plugin;

fn main() {
    let x: int = 3;
    let y: uint = 4;
    println!("{}", mymacro!(x + y));
}
```

Result:

```
$ rustc -L . test.rs 
<quote expansion>:1:21: 1:38 error: mismatched types: expected `int`, found `uint` (expected int, found uint)
<quote expansion>:1 name_60,ctxt_12 + name_63,ctxt_12
                                        ^~~~~~~~~~~~~~~~~
test.rs:1:1: 10:1 note: in expansion of mymacro!
test.rs:9:20: 9:35 note: expansion site
note: in expansion of format_args!
<std macros>:2:23: 2:77 note: expansion site
<std macros>:1:1: 3:2 note: in expansion of println!
test.rs:9:5: 9:37 note: expansion site
error: aborting due to previous error
```

The error output actually contains NULL characters, which is why the caret is misaligned.

See #16617, #15962.

### PR DESCRIPTION
**Pull request by goffrie**
This changes the `ToTokens` implementations for expressions, statements, etc. with almost-trivial ones that produce `Interpolated(*Nt(...))` pseudo-tokens. In this way, quasiquote now works the same way as macros do: already-parsed AST fragments are used as-is, not reparsed.

The `ToSource` trait is removed. Quasiquote no longer involves pretty-printing at all, which removes the need for the `encode_with_hygiene` hack. All associated machinery is removed.

New `Nonterminal`s are added: NtArm, NtImplItem, and NtTraitItem. These are just for quasiquote, not macros.

`ToTokens` is no longer implemented for `Arg` (although this could be added again) and `Generics` (which I don't think makes sense).

This breaks any compiler extensions that relied on the ability of `ToTokens` to turn AST fragments back into inspectable token trees. For this reason, this closes #16987.

As such, this is a [breaking-change].

Fixes #16472.
Fixes #15962.
Fixes #17397.
Fixes #16617.

### CODE REVIEW

**Comment by kmcallister** [comment]
cc me, @eddyb, @sfackler, @pnkfelix

**Comment by eddyb** [comment]
I have done this a long time ago in a branch I want to revive soon (the whole stage0 syntax extensions thing) - so I am pretty confident this is the way forward (I was too afraid of bootstrapping churn to split this specific change out).

Any chance you can remove the whole "pretty printing with hygiene (info on idents)" hack?

**Comment by goffrie** [comment]
You're talking about the encode-idents-with-null-characters thing? AFAIK, I've ripped all that out - unless you happen to know of something I've missed?

**Comment by eddyb** [comment]
@goffrie ahhh you managed to see my comment before I realized I've missed that part in tbe description.

**Comment by lfairy** [comment]
Is anyone looking at this? I'm pretty excited about this PR.

**Comment by kmcallister** [comment]
Me too! It needs a rebase though.

**Comment by goffrie** [comment]
Sorry, I've been so busy :sob: I'll try to get this PR updated this week.

**Comment by goffrie** [comment]
Rebased. Can someone review this?

**Comment by huonw** [comment]
Finally got time to review! This is very cool.

Just resolving the staging point one way or another, and I think this is good to go.

**Comment by goffrie** [comment]
@huonw I suspect that we would in fact encounter the problem you mentioned, so I removed the associated commit :( Also rebased. Should be good now?

**Comment by huonw** [comment]
That's a little sad: the quasiquoted version is definitely nicer.

@bors r+

**Comment by goffrie** [comment]
Gah, added `ignore-android` to `qquote.rs`.

**Comment by goffrie** [comment]
Is that a spurious failure..?

**Comment by alexcrichton** [comment]
To confirm, did the tests all pass locally for you?

**Comment by goffrie** [comment]
Yeah, though I haven't rebased on a really recent master.

**Comment by goffrie** [comment]
Rebased. All tests pass locally.

**Comment by lfairy** [comment]
The failure seems unrelated:

    test [debuginfo-lldb] debuginfo/associated-types.rs ... 
    command timed out: 1200 seconds without output, attempting to kill
    process killed by signal 15
    program finished with exit code -1
    elapsedTime=2966.482249

This PR only touches libsyntax; it shouldn't have anything to do with debuginfo, right?

**Comment by goffrie** [comment]
Yeah, I don't think it's related.

File: src/test/run-pass-fulldeps/qquote.rs [hunk 1]
```diff
@@ -9,59 +9,56 @@
...
 extern crate syntax;
 
-use syntax::ast;
-use syntax::codemap;
-use syntax::parse;
-use syntax::print::pprust;
+use syntax::codemap::DUMMY_SP;
+use syntax::print::pprust::*;
 
-trait FakeExtCtxt {
```
Comment (tamird) [inline src/test/run-pass-fulldeps/qquote.rs]: why change all this?

Comment (goffrie) [inline src/test/run-pass-fulldeps/qquote.rs]: I rewrote this test independently from your branch (from when it was ignore-test-ed and nonfunctional) and when rebasing I figured that my test already covered everything yours does, so I just took mine. (Also, it seems kind of fragile to me IMO to fake the `ExtCtxt` methods that quasiquote happens to need, instead of creating an actual `ExtCtxt`.)

Comment (tamird) [inline src/test/run-pass-fulldeps/qquote.rs]: Right, so I agree with that part, but if you're going to change that, there are 2 other places where a `FakeExtCtxt` is made, and it would be good to fix them as well. As for this file's `main` function, there's really no need to change it; it's just noise :(

Comment (goffrie) [inline src/test/run-pass-fulldeps/qquote.rs]: Um, I changed the main function for a reason - I'm testing unquotes now (which is what this branch is all about). I'll change the other files that use a FakeExtCtxt, though.

Comment (tamird) [inline src/test/run-pass-fulldeps/qquote.rs]: I'm not sure what you mean, but it looks to me like the main function is effectively unchanged, just rearranged.

Comment (goffrie) [inline src/test/run-pass-fulldeps/qquote.rs]: I'm testing that not only (e.g.) `quote_expr!(cx, 23)` works and produces 23, but also that `quote_expr!(cx, $expr)` (where `expr` is the result of the earlier quote) still produces 23.

**Comment by kmcallister** [comment]
:tada:
