### PR TITLE
Document why `Range*<&T> as RangeBounds<T>` impls are not `T: ?Sized`, and give an alternative.

### LINKED ISSUE #107196: RangeXxx<&T> should implement RangeBounds<T> even if T is unsized
I tried this code:

```rust
use std::collections::BTreeMap;
pub fn foo(map: &BTreeMap<String, i32>) -> impl Iterator<Item = (&String, &i32)> {
    map.range::<str, _>("".."")
}
```

I expected to see this happen: This should compile since `BTreeMap::range` is supposed to accept a `RangeBounds` with an unsized type parameter

Instead, this happened: It does not compile with the error:
```error[[E0277]](https://doc.rust-lang.org/stable/error-index.html#E0277): the size for values of type `str` cannot be known at compilation time
 --> src/lib.rs:3:25
  |
3 |     map.range::<str, _>("".."")
  |         -----           ^^^^^^ doesn't have a size known at compile-time
  |         |
  |         required by a bound introduced by this call
  |
  = help: the trait `Sized` is not implemented for `str`
  = help: the following other types implement trait `RangeBounds<T>`:
            std::ops::Range<&T>
            std::ops::Range<T>
  = note: required for `std::ops::Range<&str>` to implement `RangeBounds<str>`
note: required by a bound in `BTreeMap::<K, V, A>::range`
```

This is because `Range<&str>` does not implement `RangeBounds<str>`, because the current `impl RangeBounds<str> for Range<&str>` is as follows:

```rs
#[stable(feature = "collections_range", since = "1.28.0")]
impl<T> RangeBounds<T> for Range<&T> {
    fn start_bound(&self) -> Bound<&T> {
        Included(self.start)
    }
    fn end_bound(&self) -> Bound<&T> {
        Excluded(self.end)
    }
}
```

Similarly, for other range structs except `(Bound, Bound)` and `RangeFull` (the latter of which does not have a type anyway), the type parameter is unnecessarily constrained to be sized:

image

The implicit `Sized` bound on `T` for the `RangeXxx<&T>` cases appears to be unintentional judging from the fact that there are no comments explaining this decision.

### Meta

`rustc --version --verbose`:
```
rustc 1.66.1 (90743e729 2023-01-10)
binary: rustc
commit-hash: 90743e7298aca107ddaa0c202a4d3604e29bfeb6
commit-date: 2023-01-10
host: x86_64-unknown-linux-gnu
release: 1.66.1
LLVM version: 15.0.2
```

<details><summary>Backtrace</summary>
<p>

```
<backtrace>
```

</p>
</details>

### PR DESCRIPTION
**Pull request by zachs18**
`Range*<&T> as RangeBounds<T>` impls have been tried to be relaxed to `T: ?Sized` at least twice:

* https://github.com/rust-lang/rust/pull/61584
* https://github.com/rust-lang/rust/pull/64327

I also was just about to make another PR to do it again until I `./x.py test library/alloc` and rediscovered the type inference regression, then searched around and found the previous PRs. Hence this PR instead so hopefully that doesn't keep happening :stuck_out_tongue:.

These impls cannot be relaxed for two reasons: 

1. Type inference regressions: See @SimonSapin's explanation from a previous PR: https://github.com/rust-lang/rust/pull/61584#issuecomment-499601046
2. It's a breaking change: `impl RangeBounds<MyUnsizedType> for std::ops::Range<&MyUnsizedType>` is allowed after the coherence rebalance ([playground link](https://play.rust-lang.org/?version=stable&mode=debug&edition=2024&gist=f704a6fe53bfc33e55b2fc246d895ec2)), and relaxing these impls would conflict with that downstream impl.

This PR adds doc-comments explaining that not having `T: ?Sized` is intentional[^1], and gives an explicit alternative: `(Bound<&T>, Bound<&T>)`.

Technically, the impls for the unstable new `std::range` types could be relaxed, as they are still unstable so the change would not be breaking, but having them be different in this regard seems worse (and the non-iterable `RangeTo/RangeToInclusive` range types are shared between the "new" and "old" so cannot be changed anyway), and then the type inference regression would pop up in whatever edition the new range types stabilize in.

The "see \<link\> for discussion of those issues" is intentionally left as a non-doc comment just for whoever may try to relax these impls again in the future, but if it is preferred to have the link in the docs I can add that.

Closes https://github.com/rust-lang/rust/issues/107196 (as wontfix)
CC https://github.com/rust-lang/rust/issues/64027

[^1]: "intentional" is maybe a bit of strong wording, should it instead say something like "was stabilized without it and it would be breaking to change it now"?

### CODE REVIEW

File: library/core/src/ops/range.rs [hunk 1]
```diff
@@ -1141,6 +1141,12 @@ impl<'a, T: ?Sized + 'a> RangeBounds<T> for (Bound<&'a T>, Bound<&'a T>) {
     }
 }
 
+/// This impl intentionally does not have `T: ?Sized` due to type inference issues.
+// see https://github.com/rust-lang/rust/pull/61584 for discussion of those issues
+///
+/// If you need to use this impl where `T` is unsized,
+/// consider using the `RangeBounds` impl for a 2-tuple of [`Bound<&T>`][Bound],
+/// e.g. replace `start..` with `(Bound::Included(start), Bound::Unbounded)`.
```
Comment (tgross35) [inline library/core/src/ops/range.rs]: Few small nits/thoughts:

* I don't think the "due to type inference issues" part needs to be in public docs. That reasoning is a bit of an internal detail, I think it's fine to just make the whole first sentence a non-doc comment.
* Maybe "impl" -> "implementation" for prose
* `e.g.` -> `i.e.` probably works because it's showing a pattern rather than a specific example
* Looks like the paragraph needs a rewrap (100 chars)

Comment (zachs18) [reply library/core/src/ops/range.rs]: * Okay, I've made that part a non-doc comment, and made it not mention the reasoning, just link to it.
* :+1:
* :+1:
* The longest of the added lines in the source is ~86 characters; do you mean the length in the rendered docs?

Comment (tgross35) [reply library/core/src/ops/range.rs]: Ah sorry, yeah the length is fine but it just looks like it got some random/copy+paste wrapping (e.g. there's plenty of room for "consider using the `RangeBounds`" the next line up). Not going to block on that though, the rest lgtm.

Thanks for the updates!

**Review by tgross35 — APPROVED** [review]
