### PR TITLE
Exclude unnecessary info from CodegenResults

### LINKED ISSUE #77857: -Zno-link is broken
I tried this command:

```
$ echo "fn main() {}" | rustc -Zno-link -
```

I expected to see this happen: An `.rlink` file is generated.

Instead, this happened:
```
thread 'rustc' panicked at 'cannot encode `DefIndex` with `rustc_serialize::json::Encoder`', /rustc/381b445ff5751f9f39ec672b623372dff09c276e/compiler/rustc_span/src/def_id.rs:135:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/381b445ff5751f9f39ec672b623372dff09c276e/library/std/src/panicking.rs:483
   1: std::panicking::begin_panic_fmt
             at /rustc/381b445ff5751f9f39ec672b623372dff09c276e/library/std/src/panicking.rs:437
   2: <rustc_span::def_id::DefIndex as rustc_serialize::serialize::Encodable<E>>::encode
   3: <rustc_serialize::json::Encoder as rustc_serialize::serialize::Encoder>::emit_struct
   4: <rustc_serialize::json::Encoder as rustc_serialize::serialize::Encoder>::emit_struct
   5: <rustc_serialize::json::Encoder as rustc_serialize::serialize::Encoder>::emit_seq
   6: <rustc_serialize::json::Encoder as rustc_serialize::serialize::Encoder>::emit_map
   7: <rustc_serialize::json::Encoder as rustc_serialize::serialize::Encoder>::emit_struct
   8: <rustc_serialize::json::Encoder as rustc_serialize::serialize::Encoder>::emit_struct
   9: <rustc_codegen_llvm::LlvmCodegenBackend as rustc_codegen_ssa::traits::backend::CodegenBackend>::link
  10: rustc_interface::queries::Linker::link
  11: rustc_span::with_source_map
  12: rustc_interface::interface::create_compiler_and_run
  13: scoped_tls::ScopedKey<T>::set
```

### Meta

`rustc --version --verbose`:
```
rustc 1.48.0-nightly (381b445ff 2020-09-29)
binary: rustc
commit-hash: 381b445ff5751f9f39ec672b623372dff09c276e
commit-date: 2020-09-29
host: x86_64-unknown-linux-gnu
release: 1.48.0-nightly
LLVM version: 11.0
```

_Originally posted by @bjorn3 in https://github.com/rust-lang/rust/pull/77795#discussion_r503330079_

cc @0dvictor (original implementer of `-Zno-link`

### PR DESCRIPTION
**Pull request by 0dvictor**
`foreign_module` and `wasm_import_module` are not needed for linking, and hence can be removed from CodegenResults.

Fixes #77857

### CODE REVIEW

**Comment by 0dvictor** [comment]
@bjorn3 Could you take a look?

**Comment by bjorn3** [comment]
Can you please add a test for `-Zno-link`?

**Comment by 0dvictor** [comment]
Good idea, let me look into it.

File: compiler/rustc_codegen_ssa/src/lib.rs [hunk 1]
```diff
@@ -105,6 +107,19 @@ bitflags::bitflags! {
...
+#[derive(Clone, Debug, Encodable, Decodable, HashStable)]
+pub struct NativeLib {
+    pub kind: NativeLibKind,
+    pub name: Option<Symbol>,
+    pub cfg: Option<ast::MetaItem>,
+}
+
+impl From<&cstore::NativeLib> for NativeLib {
+    fn from(lib: &cstore::NativeLib) -> Self {
+        NativeLib { kind: lib.kind.clone(), name: lib.name.clone(), cfg: lib.cfg.clone() }
```
Comment (pickfire) [inline compiler/rustc_codegen_ssa/src/lib.rs:119]: Must we do a clone here?

Comment (bjorn3) [reply compiler/rustc_codegen_ssa/src/lib.rs:119]: The `cstore::NativeLib` originates from an `Lrc`, so we can't move any of these fields.

**Comment by 0dvictor** [comment]
Added a sanity test covering `-Z no-link` and `-Z link-only`.

**Comment by bjorn3** [comment]
Thanks!

@bors r+
