### PR TITLE
JumpThreading: fix bitwise not on non-booleans

### LINKED ISSUE #131195: `-Zmir-opt-level` miscompiles code with panic
I tried this code:

```rust
pub fn myfunc() -> i32 {
    let mut c :i32 = 1;
    c = 1 ;
    if !c != 0 {
        return 1;
    }
    panic!("Reached end of non-void function");
}

pub fn main() {
    let e = myfunc();
    println!("e={}", e);
}
```

I expected to see this happen: **always panic**

Instead, this happened: **only -Zmir-opt-level=2 panic**

For mir-opt-level 0, 1 and 3, they all normally return
```shell
% rustc -Awarnings -Zmir-opt-level=2 test.rs && ./test
thread 'main' panicked at test.rs:7:5:
Reached end of non-void function
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
%
% rustc -Awarnings -Zmir-opt-level=0 test.rs && ./test
e=1
```

### Meta

`rustc --version --verbose`:
```
rustc 1.83.0-nightly (18b1161ec 2024-10-02)
binary: rustc
commit-hash: 18b1161ec9eeab8927f91405bca0ddf59a4a26c9
commit-date: 2024-10-02
host: x86_64-unknown-linux-gnu
release: 1.83.0-nightly
LLVM version: 19.1.0
```

### PR DESCRIPTION
**Pull request by clubby789**
Fixes #131195

Alternative to #131201

### CODE REVIEW

File: compiler/rustc_middle/src/ty/consts/int.rs [hunk 1]
```diff
@@ -400,6 +400,14 @@ impl ScalarInt {
     }
 }
 
+impl std::ops::Not for ScalarInt {
```
Comment (compiler-errors) [inline compiler/rustc_middle/src/ty/consts/int.rs:403]: this type implements no other operators, so it implementing `Not` seems a bit weird. You can probably just inline this into the caller, or make this an inherent method like `bitwise_not` on the scalarint type.

Comment (clubby789) [reply compiler/rustc_middle/src/ty/consts/int.rs:403]: My thinking was it makes sense for unary ops and particularly not (since we don't have to worry about size mismatches and signedness). In the absence of other operators a method probably makes more sense

File: tests/mir-opt/jump_threading.rs [hunk 2]
```diff
@@ -531,6 +531,22 @@ fn floats() -> u32 {
     if x == 0.0 { 0 } else { 1 }
 }
 
+fn not_int() -> i32 {
```
Comment (compiler-errors) [inline tests/mir-opt/jump_threading.rs:534]: Please rebase this into a commit *before* you made the changes, so we can see the diff; usually I don't care about separate tests for "before the fix" and "after the fix" but for misfiring optimizations, I want to see that it was actually miscompiling before.

**Comment by compiler-errors** [comment]
Thanks!

@bors r+

**Comment by compiler-errors** [comment]
Ok, well, this definitely causes a crash when building lock_api@0.4.12

@bors r-

Let's actually land #131201, which is a more conservative fix. Then we can work on improving the jumpthreading optimization :)

Since cjgillot authored the jump threading optimization (I think?) I can pass this off to them.

r? @cjgillot

**Comment by clubby789** [comment]
Looks like some miscompile in std 🤔 In my local testing I get println hanging on `futex` forever

**Comment by compiler-errors** [comment]
I am very curious to learn what is wrong with this PR :D

File: compiler/rustc_middle/src/ty/consts/int.rs [hunk 3]
```diff
@@ -398,6 +398,11 @@ impl ScalarInt {
     pub fn to_f128(self) -> Quad {
         self.to_float()
     }
+
+    #[inline]
+    pub fn bitwise_not(self) -> Self {
+        Self { data: self.size().truncate(!self.data), size: self.size }
```
[the remark this answers is not in the document]
Comment (clubby789) [reply compiler/rustc_middle/src/ty/consts/int.rs:404]: Oh, are bools represented as an i8 scalar int rather than an i1?

[the remark this answers is not in the document]
Comment (DianQK) [reply compiler/rustc_middle/src/ty/consts/int.rs:404]: I think so, for reference: https://github.com/rust-lang/rust/blob/3002af6cb643138839537f6fd0265162610fdbbe/compiler/rustc_middle/src/ty/consts/int.rs#L170-L171 and https://github.com/rust-lang/rust/blob/3002af6cb643138839537f6fd0265162610fdbbe/compiler/rustc_middle/src/ty/consts/int.rs#L325-L331.

[the remark this answers is not in the document]
Comment (DianQK) [reply compiler/rustc_middle/src/ty/consts/int.rs:404]: Can you add some comments telling us not use it when the type is bool? Or add a type parameter?

File: compiler/rustc_mir_transform/src/jump_threading.rs [hunk 4]
```diff
@@ -150,10 +150,8 @@ impl Condition {
     }
 
     fn inv(mut self) -> Self {
-        self.polarity = match self.polarity {
-            Polarity::Eq => Polarity::Ne,
-            Polarity::Ne => Polarity::Eq,
-        };
+        self.value = self.value.bitwise_not();
+
```
Comment (DianQK) [inline compiler/rustc_mir_transform/src/jump_threading.rs:154]: nit ;)

File: compiler/rustc_middle/src/ty/consts/int.rs (hunk 3 above)
[the remark this answers is not in the document]
Comment (DianQK) [reply compiler/rustc_middle/src/ty/consts/int.rs:404]: > > IIUC, we need additional handling for bool. For the bitwise-not of a bool, `0x00` should be `0x01` instead of `0xff`.
> 
> Is this related to the i1 representation we use for bool immediates?

I'm not sure, but I think the i1 representation is only at the codegen phase.

File: tests/mir-opt/jump_threading.rs [hunk 5]
```diff
@@ -535,11 +535,17 @@ pub fn bitwise_not() -> i32 {
     // CHECK-LABEL: fn bitwise_not(
 
     // Test for #131195, which was optimizing `!a == b` into `a != b`.
-    let mut a: i32 = 0;
```
Comment (clubby789) [inline tests/mir-opt/jump_threading.rs:539]: Just removed the mutation to simplify the test since it wasn't necessary in the original demo

File: compiler/rustc_mir_transform/src/jump_threading.rs [hunk 6]
```diff
@@ -494,17 +491,12 @@ impl<'a, 'tcx> TOFinder<'a, 'tcx> {
...
-                if !place.ty(self.body, self.tcx).ty.is_bool() {
-                    // Constructing the conditions by inverting the polarity
-                    // of equality is only correct for bools. That is to say,
-                    // `!a == b` is not `a != b` for integers greater than 1 bit.
-                    return;
-                }
+                let is_bool = place.ty(self.body, self.tcx).ty.is_bool();
                 let Some(conditions) = state.try_get_idx(lhs, &self.map) else { return };
                 let Some(place) = self.map.find(place.as_ref()) else { return };
                 // FIXME: I think This could be generalized to not bool if we
```
Comment (DianQK) [inline compiler/rustc_mir_transform/src/jump_threading.rs:497]: We can remove this FIXME now. :3

File: compiler/rustc_mir_transform/src/jump_threading.rs [hunk 7]
```diff
@@ -494,17 +491,12 @@ impl<'a, 'tcx> TOFinder<'a, 'tcx> {
             }
             // Transfer the conditions on the copy rhs, after inversing polarity.
```
Comment (DianQK) [inline compiler/rustc_mir_transform/src/jump_threading.rs:492]: Should we also update this comment?

**Comment by cjgillot** [comment]
One naming nit.
r=me either way

File: compiler/rustc_middle/src/ty/consts/int.rs [hunk 8]
```diff
@@ -398,6 +398,18 @@ impl ScalarInt {
     pub fn to_f128(self) -> Quad {
         self.to_float()
     }
+
+    /// Performs a bitwise NOT. If this is a boolean, perform a logical NOT instead
+    /// Panics if `is_bool` is true and `value` is not a valid boolean
```
Comment (RalfJung) [inline compiler/rustc_middle/src/ty/consts/int.rs:403]:
```suggestion
    /// Performs a bitwise NOT. If this is a boolean, perform a logical NOT instead.
    /// Panics if `is_bool` is true and `value` is not a valid boolean.
```

File: compiler/rustc_mir_transform/src/jump_threading.rs [hunk 9]
```diff
@@ -149,11 +149,8 @@ impl Condition {
         (self.value == value) == (self.polarity == Polarity::Eq)
     }
 
-    fn inv(mut self) -> Self {
-        self.polarity = match self.polarity {
-            Polarity::Eq => Polarity::Ne,
-            Polarity::Ne => Polarity::Eq,
-        };
+    fn not(mut self, is_bool: bool) -> Self {
+        self.value = self.value.not(is_bool);
```
Comment (RalfJung) [inline compiler/rustc_mir_transform/src/jump_threading.rs:153]: I am not sure we want this as an operation on `ScalarInt`. We don't do this for any other operation. Instead, this should call `ecx.unary_op`.

File: compiler/rustc_mir_transform/src/jump_threading.rs [hunk 10]
```diff
@@ -492,19 +484,20 @@ impl<'a, 'tcx> TOFinder<'a, 'tcx> {
...
-                // FIXME: I think This could be generalized to not bool if we
-                // actually perform a logical not on the condition's value.
-                let conds = conditions.map(self.arena, Condition::inv);
+                let conds = conditions.map(self.arena, |mut cond| {
+                    cond.value = self
+                        .ecx
+                        .unary_op(UnOp::Not, &ImmTy::from_scalar_int(cond.value, layout))
+                        .unwrap()
+                        .to_scalar_int()
+                        .unwrap();
```
Comment (RalfJung) [inline compiler/rustc_mir_transform/src/jump_threading.rs:498]: `unwrap` is dangerous in optimizations, you probably want ti ignore errors rather than turn them into panics. So it'd be something like
```rust
if let Some(result) = self
                        .ecx
                        .unary_op(UnOp::Not, &ImmTy::from_scalar_int(cond.value, layout)).discard_err()
    && let Some(result) = result.to_scalar_int().discard_err() {
```
or maybe an `and_then` chain, seeing as this is currently in a `map`.

Comment (clubby789) [reply compiler/rustc_mir_transform/src/jump_threading.rs:498]: If I understand the flow of the code right, failing to modify the condition value would result in miscompiles similar to the original issue. I _think_ the only way to handle a failure here would be to bail out of optimizing this body? I could be wrong there

Comment (RalfJung) [reply compiler/rustc_mir_transform/src/jump_threading.rs:498]: Yes, generally that's what happens in optimizations.

They are often written as functions returning `Option` so that one can easily do `discard_err()?`.

**Comment by clubby789** [comment]
Threaded `-> Option<()>` through places where interp errors can happen. There's a few suspicious `let Some(x) = .. else { return Some(()); }` but I wanted to keep the behaviour for these as close to as the current

**Comment by cjgillot** [comment]
@clubby789 I'm not convinced by the second commit. If we get an interpreter error, we should only abort the current backwards walk, not the whole pass.

**Comment by cjgillot** [comment]
> Threaded `-> Option<()>` through places where interp errors can happen. There's a few suspicious `let Some(x) = .. else { return Some(()); }` but I wanted to keep the behaviour for these as close to as the current

Do they actually cause a bug? Do you have a reproducer?

**Comment by clubby789** [comment]
iirc all instances that I looked at seemed to be fine, and changing them to return None instead caused issues

**Comment by cjgillot** [comment]
For the correctness in case of interpreter failure.
The correctness of the backtracking is ensured by `mutated_statement` clearing all relevant conditions. So if `process_statement` fails to insert a new condition, the obsolete ones are still removed from the state.
I'd rather have `mutated_statement` fixed if there is a bug, instead of an early exit contaminating everything.

**Comment by clubby789** [comment]
Sorry, I'm not quite sure what you mean here. Do you want additional changes?
I _believe_ that all the instances where a `None` isn't propogated are intended functionality, not bugs

**Comment by DianQK** [comment]
IIUC, you can add `Polarity::Unknown` to avoid exit everything.
BTW, I think it's would be good to know when constant evaluation can fail here.

**Comment by clubby789** [comment]
>  BTW, I think it's would be good to know when constant evaluation can fail here.

It's been quite a while, but I'm not certain if there were any; I made the opt fallible due to [this comment](https://github.com/rust-lang/rust/pull/131203#discussion_r1790538533). I don't remember the specifics of the failures mentioned [here](https://github.com/rust-lang/rust/pull/131203#issuecomment-2440793496), but I _think_ this was due to mistakenly treating basic blocks where there was no optimization to be applied as an error

> IIUC, you can add `Polarity::Unknown` to avoid exit everything.
I'll investigate this approach

**Comment by apiraino** [comment]
reassignment review

r? compiler

**Review by compiler-errors — APPROVED** [review]

**Comment by clubby789** [comment]
Rebased and updated a test.

@bors r=compiler-errors rollup=never
