### PR TITLE
fix(libtest): Deprecate '--logfile'

### LINKED ISSUE #9: Export machine-readable test results to a file
As a follow up to the testing-devex's feedback for https://github.com/rust-lang/rust/pull/123365 ([draft](https://rust-lang.zulipchat.com/#narrow/stream/404371-t-testing-devex/topic/meeting.202024-05-21/near/440151339)), let me describe on a high level our use case for capturing JUnit output when running Rust test via Bazel.

In our setup, Bazel (build system) runs Rust test binaries. We use a slightly patched version of https://github.com/bazelbuild/rules_rust. Bazel is a mediator between the terminal UI, IDEs, code review websites, or remote build/test services, and the executed test. Bazel runs the test binary directly, i.e. doesn't use `cargo test`. Bazel uses JUnit XML files for communicating machine-parsable language-agnostic test results (already supported by GoogleTest, JUnit, and other languages). Right now, there is no mechanism to communicate Rust test results through Bazel to users (again, terminal, IDE plugins...). See also [Bazel Rust rules FR](https://github.com/bazelbuild/rules_rust/issues/1303).

----

One straightforward candidate solution consists of these 2 steps:
1. Have CLI flag(s) defined in Rust libtest to control export of machine-readable test results (e.g. JUnit or JSON) from the Rust test processes. For context, these PRs were attempts to add/fix such CLI flag(s):
    -  https://github.com/rust-lang/rust/pull/123365 (+ https://github.com/aspotashev/rust/pull/1 )
    - https://github.com/rust-lang/rust/pull/122145 
1. Modify Bazel Rust rules to pass the relevant CLI flags.

We also considered using a wrapper binary (Bazel runs wrapper, wrapper runs Rust test binary and captures stdout), however it has downsides which are hard-to-impossible to resolve:
- Capturing an output stream (e.g. stdout, stderr) isn't reliable because a Rust test may also write directly to stdout and that will garble XML/JSON test results output from libtest.
- Without a significant rework of Bazel, the systems that sit on top of it (e.g. IDEs) will treat the wrapper as a main application, therefore an naive attempt to debug a Rust test would start a debugger for the wrapper instead.

----

I'm looking forward to hearing your suggestions for problem resolutions that may be acceptable from the perspective of T-testing-devex. If we find a solution that doesn't require a significant rework of libtest / Rust testing framework, that would be great, and I would then be interested in contributing the relevant code.

### PR DESCRIPTION
**Pull request by epage**
rust-lang/testing-devex-team#9 proposed changing the behavior of `--logfile`. The given reasons were:

(1) Bazel can't programmatically process stdout.  This seems like a limitation in Bazel and we recommend focusing on that.  If we look at the wider Rust ecosystem, Rustc and Cargo don't support any such mechanism and the Cargo team rejected having one.  Expecting this in libtest when its not supported elsewhere seems too specialized.

(2) Tests that leak out non-programmatic output that intermixes with programmatic output.  We acknowledge this is a problem to be evaluated but we need to make sure we are stepping back and gathering requirements, rather than assuming `--logfile` will fit the needs.

Independent of the motive, regarding using or changing  `--logfile`

(1) Most ways to do it would be a breaking change, like if we respect any stable `--format`.  As suggested above, we could specialize this to new `--format` values but that would be confusing for some values to apply but not others.

(2) Other ways of solving this add new features to lib`test` when we are instead wanting to limit the feature set it has to minimize the compatibility surface that has to be maintained and the burden it would put on third party harnesses which are a focus area.  Examples include `--format compact` or a `--log-format` flag

(3) The existence of `--logfile` dates back quite a ways (https://github.com/rust-lang/rust/commit/5cc050b265509c19717e11e12dd785d8c73f5b11, rust-lang/rust#2127) and the history gives the
impression this more of slipped through rather than being an intended feature (see also
https://github.com/rust-lang/rust/pull/82350#discussion_r579732071). Deprecation would better match to how it has been treated. By deprecating this, we do not expect custom test harnesses (rust-lang/testing-devex-team#2) to implement this.

T-testing-devex held an FCP for deprecating in rust-lang/testing-devex-team#9 though according to
[RFC #3455](https://rust-lang.github.io/rfcs/3455-t-test.html), this is still subject to final approval from T-libs-api.

Closes rust-lang/testing-devex-team#9

### CODE REVIEW

File: library/test/src/options.rs [hunk 1]
```diff
@@ -38,6 +38,15 @@ pub enum OutputFormat {
     Junit,
 }
 
+impl OutputFormat {
+    pub(crate) fn is_programmatic(&self) -> bool {
+        match self {
+            Self::Pretty | Self::Terse => true,
+            Self::Json | Self::Junit => false,
```
Comment (m-ou-se) [inline library/test/src/options.rs:45]: Are `true` and `false` flipped here? Or am I misunderstanding something?

Comment (epage) [reply library/test/src/options.rs]: ... sorry

**Comment by traviscross** [comment]
This was discussed in the libs-api call today.  People on the call were a bit unclear about the context, the motivation, and the broader plan, so it would help if those things might be clarified.  In particular:

- The context: What is it that `--log-file` does now (setting aside the proposed change in behavior in https://github.com/rust-lang/testing-devex-team/issues/9), when was it added, why was it added in the first place, why do people use it, how widely is it used, etc.?
- The motivation: Why specifically are we unhappy with the current behavior or existence of `--log-file`, what do we gain by working toward removing it, and what is the cost of not doing so?
- The plan: Would this deprecation be working toward a full removal?  If so, what's the proposal for how and when that would be done, how the impact of breaking stability here could be mitigated, etc.?  Also, is this part of e.g. some larger plan to e.g. simply the arguments in general and deprecate and remove other things?

Thanks for making the proposal here and for filling in the other details that might help the team to build the context needed to make a decision on this.

File: library/test/src/cli.rs [hunk 2]
```diff
@@ -281,6 +281,10 @@ fn parse_opts_impl(matches: getopts::Matches) -> OptRes {
 
     let options = Options::new().display_output(matches.opt_present("show-output"));
 
+    if logfile.is_some() && !format.is_programmatic() {
+        let _ = write!(io::stdout(), "warning: `--logfile` is deprecated");
```
Comment (Amanieu) [inline library/test/src/cli.rs:285]: Why is this warning printed to stdout instead of stderr?

Comment (epage) [reply library/test/src/cli.rs]: Fixed

File: library/test/src/cli.rs [hunk 3]
```diff
@@ -281,6 +281,10 @@ fn parse_opts_impl(matches: getopts::Matches) -> OptRes {
 
     let options = Options::new().display_output(matches.opt_present("show-output"));
 
+    if logfile.is_some() && !format.is_programmatic() {
```
Comment (Amanieu) [inline library/test/src/cli.rs:284]: Can you explain why `format.is_programmatic()` is needed? Since we are now printing to stderr the warning shouldn't mess up the contents of stdout if it is redirected. Or is it intentional that --logfile is not deprecated with these output formats?

Comment (epage) [reply library/test/src/cli.rs]: Yes, if we've moved to stderr, then its not really needed.
