### PR TITLE
[MIR] Add Storage{Live,Dead} statements to emit llvm.lifetime.{start,end}.

### LINKED ISSUE #26764: .note.rustc dylib section flagged SHF_ALLOC on Linux (can cause crashes)
Having the metadata note section flagged "alloc" can cause two types of crashes in certain environments.

## 1. Dynamic loader crash
Glibc's dynamic loader will try to allocate and copy the entire section onto the stack which will crash if the stack size is limited. This section is particularly large (~2MB for libstd) - not something that can generally be expected to fit on the stack.

The loader is searching for .note.ABI-tag, but does so by reading in any PT_NOTE headers. Because the metadata section is flagged alloc, it gets an entry in the program header, causing it to get loaded by this code.
http://osxr.org/glibc/source/elf/dl-load.c?!v=glibc-2.19#1869 (Note the alloca() at 1879)

I think this may be the cause of #22528, or other crashes with open_verify() in the call stack.

A workaround of using objcopy -R to remove the section fixes this problem, but leaves the object in a brittle state, described below.

## 2. Crashes in stripped and prelinked shared objects
Working around 1. by stripping out .note.rustc causes a problem with section numbering. Pulling the section out from before another ALLOC section (.bss in the example below) causes that section to be renumbered. Neither GNU strip nor objcopy fix the rest of the references in the executable that point to the section by its index. In particular, entries in the .dynamic section now point to the next section (.comment, here) which breaks when prelinking.

Prelink decides not to fix up the symbols in the dynamic section because it thinks they point to .comment, a section that didn't get relocated during prelinking. So BSS gets relocated, but the dynamic symbols point to the non-prelinked address, causing the program to segfault when it tries to access exported symbols in BSS.

readelf -S libstd-4e7c5e5c.so (current behavior)
```
  [25] .data             PROGBITS        001938a0 18b8a0 0001a0 00  WA  0   0 16
  [26] .note.rustc       NOTE            00193a40 18ba40 2088d2 00  WA  0   0 16
  [27] .bss              NOBITS          0039c320 394312 000dc8 00  WA  0   0 16
  [28] .comment          PROGBITS        00000000 394312 000011 01  MS  0   0  1
  [29] .ARM.attributes   ARM_ATTRIBUTES  00000000 394323 00003d 00      0   0  1
  [30] .debug_aranges    PROGBITS        00000000 394360 0011a0 00      0   0  8
```

To fix this, I'm currently using this patch as a workaround.
https://github.com/tylerwhall/rust/commit/fc910593a98d5b8641a6974ce65959116285e00f
It runs objcopy on the intermediate metadata object to remove the alloc and write flags. This causes the final link to place the metadata section at the end of the executable and not generate a program header entry.

The fixed version has the metadata with no flags set, no load address, and located near the end of the file along with the debug sections where it can be safely stripped.

readelf -S libstd-4e7c5e5c.so (desired behavior)
```
  [25] .data             PROGBITS        001938a0 18b8a0 0001a0 00  WA  0   0 16
  [26] .bss              NOBITS          00193a40 18ba40 000dc8 00  WA  0   0 16
  [27] .comment          PROGBITS        00000000 18ba40 000011 01  MS  0   0  1
  [28] .ARM.attributes   ARM_ATTRIBUTES  00000000 18ba51 00003d 00      0   0  1
  [29] .note.rustc       PROGBITS        00000000 18ba90 2088a7 00      0   0 16
  [30] .debug_aranges    PROGBITS        00000000 394338 0011a0 00      0   0  8
```
Obviously running objcopy like this is not portable. Calling llvm::LLVMSetGlobalConstant() on the metadata variable is enough to remove the SHF_WRITE flag, but I couldn't find a way with LLVM's API to output a section that didn't request to be loaded at run time. Hopefully someone who knows more about LLVM can come up with a more elegant solution to remove SHF_ALLOC from the intermediate metadata object.

### LINKED ISSUE #27372: readelf complains that .note.rustc is malformed
After building rustc 1.1.0, if I run `readelf --section-headers --note` over the shared libraries produced, I see output like the following:
```
$ readelf --section-headers --note x86_64-unknown-linux-gnu/stage2/lib/libarena-e9599659.so
There are 30 section headers, starting at offset 0xef98:

Section Headers:
  [Nr] Name              Type             Address           Offset
       Size              EntSize          Flags  Link  Info  Align
  [ 0]                   NULL             0000000000000000  00000000
       0000000000000000  0000000000000000           0     0     0
  [ 1] .note.gnu.build-i NOTE             0000000000000200  00000200
       0000000000000024  0000000000000000   A       0     0     4
  [ 2] .gnu.hash         GNU_HASH         0000000000000228  00000228
       0000000000000118  0000000000000000   A       3     0     8
  [ 3] .dynsym           DYNSYM           0000000000000340  00000340
       00000000000003d8  0000000000000018   A       4     2     8
  [ 4] .dynstr           STRTAB           0000000000000718  00000718
       0000000000000687  0000000000000000   A       0     0     1
  [ 5] .gnu.version      VERSYM           0000000000000da0  00000da0
       0000000000000052  0000000000000002   A       3     0     2
  [ 6] .gnu.version_r    VERNEED          0000000000000df8  00000df8
       0000000000000040  0000000000000000   A       4     2     8
  [ 7] .rela.dyn         RELA             0000000000000e38  00000e38
       0000000000000150  0000000000000018   A       3     0     8
  [ 8] .rela.plt         RELA             0000000000000f88  00000f88
       0000000000000150  0000000000000018  AI       3    10     8
  [ 9] .init             PROGBITS         00000000000010d8  000010d8
       000000000000001a  0000000000000000  AX       0     0     4
  [10] .plt              PROGBITS         0000000000001100  00001100
       00000000000000f0  0000000000000010  AX       0     0     16
  [11] .text             PROGBITS         00000000000011f0  000011f0
       00000000000010ac  0000000000000000  AX       0     0     16
  [12] .fini             PROGBITS         000000000000229c  0000229c
       0000000000000009  0000000000000000  AX       0     0     4
  [13] .eh_frame_hdr     PROGBITS         00000000000022a8  000022a8
       00000000000000b4  0000000000000000   A       0     0     4
  [14] .eh_frame         PROGBITS         0000000000002360  00002360
       000000000000033c  0000000000000000   A       0     0     8
  [15] .gcc_except_table PROGBITS         000000000000269c  0000269c
       000000000000028c  0000000000000000   A       0     0     4
  [16] .init_array       INIT_ARRAY       0000000000202db0  00002db0
       0000000000000008  0000000000000000  WA       0     0     8
  [17] .fini_array       FINI_ARRAY       0000000000202db8  00002db8
       0000000000000008  0000000000000000  WA       0     0     8
  [18] .jcr              PROGBITS         0000000000202dc0  00002dc0
       0000000000000008  0000000000000000  WA       0     0     8
  [19] .data.rel.ro      PROGBITS         0000000000202dc8  00002dc8
       0000000000000008  0000000000000000  WA       0     0     8
  [20] .dynamic          DYNAMIC          0000000000202dd0  00002dd0
       00000000000001e0  0000000000000010  WA       4     0     8
  [21] .got              PROGBITS         0000000000202fb0  00002fb0
       0000000000000050  0000000000000008  WA       0     0     8
  [22] .got.plt          PROGBITS         0000000000203000  00003000
       0000000000000088  0000000000000008  WA       0     0     8
  [23] .data             PROGBITS         0000000000203088  00003088
       0000000000000008  0000000000000000  WA       0     0     8
  [24] .note.rustc       NOTE             0000000000203090  00003090
       000000000000ab12  0000000000000000  WA       0     0     16
  [25] .bss              NOBITS           000000000020dba4  0000dba2
       0000000000000004  0000000000000000  WA       0     0     4
  [26] .comment          PROGBITS         0000000000000000  0000dba2
       000000000000002c  0000000000000001  MS       0     0     1
  [27] .shstrtab         STRTAB           0000000000000000  0000dbce
       0000000000000115  0000000000000000           0     0     1
  [28] .symtab           SYMTAB           0000000000000000  0000dce8
       0000000000000978  0000000000000018          29    62     8
  [29] .strtab           STRTAB           0000000000000000  0000e660
       0000000000000938  0000000000000000           0     0     1
Key to Flags:
  W (write), A (alloc), X (execute), M (merge), S (strings), l (large)
  I (info), L (link order), G (group), T (TLS), E (exclude), x (unknown)
  O (extra OS processing required) o (OS specific), p (processor specific)

Displaying notes found at file offset 0x00000200 with length 0x00000024:
  Owner                 Data size	Description
  GNU                  0x00000014	NT_GNU_BUILD_ID (unique build ID bitstring)
    Build ID: 16a45cac5814e1be056835720bcbd14710fab8eb

Displaying notes found at file offset 0x00003090 with length 0x0000ab12:
  Owner                 Data size	Description
readelf: Warning: note with invalid namesz and/or descsz found at offset 0x0
readelf: Warning:  type: 0x6007bded, namesize: 0x74737572, descsize: 0x02000000
```
Based on the section list, it appears that the malformed section is .note.rustc

Built using the x86_64 bootstrap rustc:
```
$ ./x86_64-unknown-linux-gnu/stage0/bin/rustc --version --verbose
rustc 1.1.0-dev (857ef6e27 2015-04-27) (built 2015-04-27)
binary: rustc
commit-hash: 857ef6e272e5634cb9f3e6ee50eb6bc2a2e71651
commit-date: 2015-04-27
build-date: 2015-04-27
host: x86_64-unknown-linux-gnu
release: 1.1.0-dev
```

### PR DESCRIPTION
**Pull request by eddyb**
Storage live ranges are tracked for all MIR variables and temporaries with a drop scope.
`StorageLive` is lowered to `llvm.lifetime.start` and `StorageDead` to `llvm.lifetime.end`.

There are some improvements possible here, such as:
- pack multiple storage liveness statements by using the index of first local + `u64` bitset
- enforce that locals are not directly accessed outside their storage live range
- shrink storage live ranges for never-borrowed locals to initialization -> last use
- emit storage liveness statements for _all_ temporaries
  - however, the remaining ones are _always_ SSA immediates, so they'd be noop in MIR trans
  - could have a flag on the temporary that its storage is irrelevant (a la C's old `register`)
    - would also deny borrows if necessary
    - this seems like an overcompliation and with packing & optimizations it may be pointless

Even in the current state, it helps stage2 `rustc` compile `boiler` without overflowing (see #35408).

A later addition fixes #26764 and closes #27372 by emitting `.section` directives for dylib metadata to avoid them being allocated into memory or read as `.note`. For this PR, those bugs were tripping valgrind.

### CODE REVIEW

File: src/librustc_mir/build/expr/as_temp.rs [hunk 1]
```diff
@@ -37,6 +37,14 @@ impl<'a, 'gcx, 'tcx> Builder<'a, 'gcx, 'tcx> {
         let temp = this.temp(expr_ty.clone());
         let temp_lifetime = expr.temp_lifetime;
         let expr_span = expr.span;
+        let source_info = this.source_info(expr_span);
+
+        if temp_lifetime.is_some() {
+            this.cfg.push(block, Statement {
+                source_info: source_info,
+                kind: StatementKind::StorageLive(temp.clone())
```
Comment (nagisa) [inline src/librustc_mir/build/expr/as_temp.rs]: Make a helper function in cfg, since you’re constructing this multiple times manually.

This should become `this.cfg.push_storage_live(source_info, temp);`

File: src/librustc_mir/transform/promote_consts.rs [hunk 2]
```diff
@@ -266,8 +277,10 @@ impl<'a, 'tcx> Promoter<'a, 'tcx> {
         });
 
         // Inject the Rvalue or Call into the promoted MIR.
+        let dest = Lvalue::Temp(new_temp);
+        self.push(StatementKind::StorageLive(dest.clone()), source_info.span);
```
Comment (arielb1) [inline src/librustc_mir/transform/promote_consts.rs]: That's a `StorageLive` with no matching `StorageDead`, right?

Comment (eddyb) [inline src/librustc_mir/transform/promote_consts.rs]: It's an interesting problem. Constants can borrow things that outlive the evaluation of the constant, so in a sense, this would be valid. I had planned to emit `StorageDead` at the end of the promoted `Mir`, after the assignment to `return`, but then I remembered the borrow thing.
We could not have any `Storage{Live,Dead}` in constants, that would be fine with me, for now.

**Comment by arielb1** [comment]
Test please

File: src/librustc_mir/transform/promote_consts.rs (hunk 2 above)
Comment (Aatch) [inline src/librustc_mir/transform/promote_consts.rs]: Note that LLVM doesn't require matching intrinsic calls, so there's no strong reason to require matching `Storage{Live,Dead}` statements in MIR. It just considers the location dead before the `lifetime.start` call and after the `lifetime.end` call.

File: src/librustc/mir/repr.rs [hunk 3]
```diff
@@ -688,14 +688,23 @@ pub struct Statement<'tcx> {
 
 #[derive(Clone, Debug, RustcEncodable, RustcDecodable)]
 pub enum StatementKind<'tcx> {
+    /// Write the RHS Rvalue to the LHS Lvalue.
     Assign(Lvalue<'tcx>, Rvalue<'tcx>),
+
+    /// Start a live range for the storage of the local.
+    StorageLive(Lvalue<'tcx>),
```
Comment (nikomatsakis) [inline src/librustc/mir/repr.rs]: Hmm, should this be restricted to base lvalues or something like that? Meh, I guess it's ok to use `Lvalue<'tcx>` here.

File: src/librustc/mir/repr.rs [hunk 4]
```diff
@@ -688,14 +688,23 @@ pub struct Statement<'tcx> {
...
+    StorageDead(Lvalue<'tcx>),
 }
 
 impl<'tcx> Debug for Statement<'tcx> {
     fn fmt(&self, fmt: &mut Formatter) -> fmt::Result {
         use self::StatementKind::*;
         match self.kind {
-            Assign(ref lv, ref rv) => write!(fmt, "{:?} = {:?}", lv, rv)
+            Assign(ref lv, ref rv) => write!(fmt, "{:?} = {:?}", lv, rv),
+            StorageLive(ref lv) => write!(fmt, "storage live for {:?}", lv),
```
Comment (nikomatsakis) [inline src/librustc/mir/repr.rs]: Nit: Why not `StorageLive({:?})`? I've just found that having Debug impls generate "sentences" can often be a bit confusing when you are reading debug output.

File: src/librustc_mir/build/mod.rs [hunk 5]
```diff
@@ -238,7 +238,8 @@ pub fn construct_const<'a, 'gcx, 'tcx>(hir: Cx<'a, 'gcx, 'tcx>,
     let span = tcx.map.span(item_id);
     let mut builder = Builder::new(hir, span);
 
-    let extent = ROOT_CODE_EXTENT;
+    let extent = tcx.region_maps.temporary_scope(ast_expr.id)
```
Comment (nikomatsakis) [inline src/librustc_mir/build/mod.rs]: This seems like a bug -- but was your discovery of it prompted by some test case?

File: src/librustc_mir/build/scope.rs [hunk 6]
```diff
@@ -107,6 +107,9 @@ pub struct Scope<'tcx> {
     /// `ScopeAuxiliary`, but kept here for convenience
     extent: CodeExtent,
 
+    /// Whether there's anything for the cleanup path.
```
Comment (nikomatsakis) [inline src/librustc_mir/build/scope.rs]: I don't really know what this comment means; it doesn't seem to add much to the name. I *think* that you are distinguishing "storage-dead" from "destructor"? Or maybe something to do with panics? Anyway, I'll probably figure it out as I read, but I think you should expand it a bit. =)

File: src/librustc_mir/build/scope.rs [hunk 7]
```diff
@@ -510,7 +545,7 @@ impl<'a, 'gcx, 'tcx> Builder<'a, 'gcx, 'tcx> {
             resumeblk
         };
 
-        for scope in scopes.iter_mut().filter(|s| !s.drops.is_empty() || s.free.is_some()) {
+        for scope in scopes.iter_mut().filter(|s| s.needs_cleanup) {
```
Comment (nikomatsakis) [inline src/librustc_mir/build/scope.rs]: This feels a bit surprising to me. For example, if we have something like:

```rust
{
    let a: Box<i32>; // scope A
    let b: i32; // scope B
    let c: Box<i32>; // scope C
}
```

we will skip over scope B and hence never release the storage for `b`?
    
```

File: src/librustc_mir/build/scope.rs [hunk 8]
```diff
@@ -591,21 +626,44 @@ fn build_scope_drops<'tcx>(cfg: &mut CFG<'tcx>,
...
+            cfg.terminate(block, source_info, TerminatorKind::Drop {
+                location: drop_data.location.clone(),
+                target: next,
+                unwind: on_diverge
+            });
+            block = next;
+        }
+        match drop_data.kind {
+            DropKind::Value { .. } |
+            DropKind::Storage => {
```
Comment (nikomatsakis) [inline src/librustc_mir/build/scope.rs]: Why this `match` when this code should always execute? Just being defensive in case some variant is added in the future?

File: src/librustc_mir/build/scope.rs [hunk 9]
```diff
@@ -653,7 +711,13 @@ fn build_diverge_scope<'a, 'gcx, 'tcx>(tcx: TyCtxt<'a, 'gcx, 'tcx>,
     // *forward* order, so that we generate drops[0] first (right to
     // left in diagram above).
     for drop_data in &mut scope.drops {
-        target = if let Some(cached_block) = drop_data.cached_block {
+        // Only full value drops are emitted in the diverging path,
+        // not StorageDead.
```
Comment (nikomatsakis) [inline src/librustc_mir/build/scope.rs]: Why not emit StorageDead in both paths/

Comment (nikomatsakis) [inline src/librustc_mir/build/scope.rs]: Why not emit StorageDead in both paths?

File: src/librustc_mir/transform/promote_consts.rs (hunk 2 above)
Comment (nikomatsakis) [inline src/librustc_mir/transform/promote_consts.rs]: @eddyb 

> Constants can borrow things that outlive the evaluation of the constant, so in a sense, this would be valid...We could not have any Storage{Live,Dead} in constants, that would be fine with me, for now.

Can you clarify to me what you mean by this? Are you talking about borrowing other constants? Maybe an example?

File: src/librustc_trans/mir/analyze.rs [hunk 10]
```diff
@@ -160,8 +160,9 @@ impl<'mir, 'bcx, 'tcx> Visitor<'tcx> for LocalAnalyzer<'mir, 'bcx, 'tcx> {
                 LvalueContext::Call => {
                     self.mark_assigned(index);
                 }
-                LvalueContext::Consume => {
-                }
+                LvalueContext::StorageLive |
+                LvalueContext::StorageDead |
+                LvalueContext::Consume => {}
```
Comment (nikomatsakis) [inline src/librustc_trans/mir/analyze.rs]: Nit: In this context, I strongly prefer the `}` to go on the next line, to break this group of arms up from other groups when scanning visually.

**Comment by nikomatsakis** [comment]
> Test please

Seems like a good use for @scottcarr's MIR testing framework.

File: src/librustc_mir/build/mod.rs (hunk 5 above)
Comment (eddyb) [inline src/librustc_mir/build/mod.rs]: Existing constant expression testcases started failing. The `1+2` temporary in `[T; 1+2+3]` has a scope that's the function's. You think I should dig deeper into `middle::region` and make it the same as if it was outside of a function?

File: src/librustc_mir/build/scope.rs (hunk 6 above)
Comment (eddyb) [inline src/librustc_mir/build/scope.rs]: We should probably *always* refer to that as unwind, not cleanup, the latter is confusing, but I took it from the context. This field is true iff there's *anything* to be done for this scope when unwinding.

File: src/librustc_mir/build/scope.rs (hunk 8 above)
Comment (eddyb) [inline src/librustc_mir/build/scope.rs]: Yeah, I've come to like that style when it's not adding too much noise.

File: src/librustc_mir/build/scope.rs (hunk 7 above)
Comment (eddyb) [inline src/librustc_mir/build/scope.rs]: Maybe I should put this in the comment, but `StorageDead` doesn't go in the *unwind* path (which is what is being dealt with here, and everywhere else using `needs_cleanup`).

Having it in the unwind path would pollute functions with landing pads, and I've checked `clang` and it doesn't emit `llvm.lifetime` in landing pads.
Also, `llvm.lifetime` in a landing pad might even cause problems, as it's not being tested AFAICT and could interfere with the unwinding process, but I haven't tried it.

File: src/librustc_mir/build/scope.rs (hunk 9 above)
Comment (eddyb) [inline src/librustc_mir/build/scope.rs]: Ah, I've replied to that above, I guess this is a comment I could expand.

File: src/librustc_mir/transform/promote_consts.rs (hunk 2 above)
Comment (eddyb) [inline src/librustc_mir/transform/promote_consts.rs]: Sure, `&&&5` in a constant will create 3 temporaries in a sort of "borrow chain".

File: src/librustc/mir/repr.rs (hunk 3 above)
Comment (eddyb) [inline src/librustc/mir/repr.rs]: `Local` would be great, but *even then*, it would not be applicable to `ReturnPointer` or args.

File: src/librustc_trans/mir/statement.rs [hunk 11]
```diff
@@ -57,6 +58,22 @@ impl<'bcx, 'tcx> MirContext<'bcx, 'tcx> {
...
+                bcx
+            }
+            mir::StatementKind::StorageDead(ref lvalue) => {
+                if let Some(index) = self.mir.local_index(lvalue) {
+                    if let LocalRef::Lvalue(tr_lval) = self.locals[index] {
+                        base::Lifetime::End.call(&bcx, tr_lval.llval);
+                    }
+                }
+                bcx
+            }
```
Comment (scottcarr) [inline src/librustc_trans/mir/statement.rs]: These look like good candidates for helper methods.

I also don't fully understand why we cannot just called trans_lvalue?  I think it has a no-op case for locals?

Comment (eddyb) [inline src/librustc_trans/mir/statement.rs]: We need to do nothing if the local is not an `Lvalue`.
Using a method taking `lvalue` and the `base::Lifetime` would work, yeah.

File: src/librustc_mir/build/scope.rs (hunk 6 above)
Comment (nikomatsakis) [inline src/librustc_mir/build/scope.rs]: > This field is true iff there's anything to be done for this scope when unwinding.

Can you make the comment say that, and also mention that we don't emit StorageDead when unwinding because clang doesn't do it?

File: src/librustc_mir/build/mod.rs (hunk 5 above)
Comment (nikomatsakis) [inline src/librustc_mir/build/mod.rs]: > Existing constant expression testcases started failing. The 1+2 temporary in [T; 1+2+3] has a scope that's the function's. You think I should dig deeper into middle::region and make it the same as if it was outside of a functions?

No, just trying to understand where this change came from; it seemed kind of out of the blue. I'm a bit confused still though. What is `[T; 1+2+3]`? Some expression in a functon?

**Comment by nikomatsakis** [comment]
OK so @eddyb convinced me that most of my concerns were moot. r=me modulo the following:

- [ ] [needs a test](https://github.com/rust-lang/rust/pull/35409#issuecomment-238237234)
- [ ] [need a few more comments](https://github.com/rust-lang/rust/pull/35409#discussion_r73980965)
- [ ] make things DRY, [as @scottcarr suggested](https://github.com/rust-lang/rust/pull/35409#discussion_r73960794)
- [ ] maybe [remove storage from "constant MIR"](https://github.com/rust-lang/rust/pull/35409#discussion_r73787338)?
- [ ] super minor nits ([1](https://github.com/rust-lang/rust/pull/35409#discussion_r73873139), [2](https://github.com/rust-lang/rust/pull/35409#discussion_r73874913)) to address if you agree

File: src/librustc_mir/build/scope.rs (hunk 6 above)
Comment (Aatch) [inline src/librustc_mir/build/scope.rs]: We may also not do it because LLVM does weird things with memory dependency along the unwind path. We had to remove some lifetime annotations in a similar situation from old trans, @dotdash should know the details.

**Comment by nikomatsakis** [comment]
Failures are valgrind failures:

```
---- [run-pass-valgrind] run-pass-valgrind/coerce-match-calls.rs stdout ----
	
error: test run failed!
status: exit code: 100
command: /usr/bin/valgrind --error-exitcode=100 --fair-sched=try --quiet --soname-synonyms=somalloc=NONE --suppressions=/buildslave/rust-buildbot/slave/auto-linux-64-opt/build/src/etc/x86.supp --tool=memcheck --leak-check=full x86_64-unknown-linux-gnu/test/run-pass-valgrind/coerce-match-calls.stage2-x86_64-unknown-linux-gnu
stdout:
------------------------------------------

------------------------------------------
stderr:
------------------------------------------
==20600== Syscall param read(buf) points to unaddressable byte(s)
==20600==    at 0x401B177: read (syscall-template.S:84)
==20600==    by 0x40059FF: open_verify.constprop.7 (dl-load.c:1949)
==20600==    by 0x4005CD9: open_path (dl-load.c:2066)
==20600==    by 0x4008BE0: _dl_map_object (dl-load.c:2307)
==20600==    by 0x400D9D1: openaux (dl-deps.c:63)
==20600==    by 0x4010393: _dl_catch_error (dl-error.c:187)
==20600==    by 0x400E011: _dl_map_object_deps (dl-deps.c:254)
==20600==    by 0x40034F9: dl_main (rtld.c:1610)
==20600==    by 0x4019461: _dl_sysdep_start (dl-sysdep.c:249)
==20600==    by 0x4004E79: _dl_start_final (rtld.c:307)
==20600==    by 0x4004E79: _dl_start (rtld.c:413)
==20600==    by 0x4000CC7: ??? (in /lib/x86_64-linux-gnu/ld-2.23.so)
==20600==  Address 0xffee10a00 is on thread 1's stack
==20600==  in frame #1, created by open_verify.constprop.7 (dl-load.c:1695)
==20600== 

------------------------------------------
```

Could be real!

**Comment by eddyb** [comment]
@nikomatsakis I pinged @alexcrichton but I don't think he had time to look over them yet.
AFAICT, those are in rtld, which could only be a problem at the end of execution, if we've ruined any rtld state - but the stack trace makes me believe it's actually at the start of execution.

**Comment by eddyb** [comment]
I can't reproduce locally at all :confused:.

**Comment by eddyb** [comment]
Argh #26764 strikes again, this time libstd's `.note.rustc` section being too large for just one rtld function to `alloca` at once, according to valgrind.

**Comment by cuviper** [comment]
I don't know about the rest, but thanks for the incidental `.note` cleanup! :smile:
