### PR TITLE
std::os::errno returns platform specific value. fixes #21898

### LINKED ISSUE #21898: `std::os::errno` incorrectly has the return type `usize`

### PR DESCRIPTION
**Pull request by Jormundir**
Changes std::os::errno to return i32, the return type used by the function being delegated to.

This is my first contribution, so feel free to give me advice. I'll be happy to correct things.

### CODE REVIEW

File: src/libstd/old_io/mod.rs [hunk 1]
```diff
@@ -353,7 +353,7 @@ impl IoError {
     /// operating system) between the call(s) for which errors are
     /// being checked and the call of this function.
     pub fn last_error() -> IoError {
-        IoError::from_errno(os::errno() as uint, true)
+        IoError::from_errno(os::errno() as i32, true)
```
Comment (alexcrichton) [inline src/libstd/old_io/mod.rs]: I think you may be able to remove this cast now.

File: src/libstd/os.rs [hunk 2]
```diff
@@ -524,15 +524,15 @@ pub fn errno() -> uint {
 /// use std::os;
 ///
 /// // Same as println!("{}", last_os_error());
-/// println!("{}", os::error_string(os::errno() as uint));
+/// println!("{}", os::error_string(os::errno() as i32));
 /// ```
-pub fn error_string(errnum: uint) -> String {
+pub fn error_string(errnum: i32) -> String {
     return sys::os::error_string(errnum as i32);
```
Comment (alexcrichton) [inline src/libstd/os.rs]: I think this cast can be removed to (and the one below)

**Comment by alexcrichton** [comment]
This may not be precisely where we want to end up, (see [my comment](https://github.com/rust-lang/rust/issues/21898#issuecomment-72899027)), but I think this is "more correct" for now so it's fine by me to merge.

**Comment by CharlesSocial** [comment]
@alexcrichton thank you for reviewing. I'll take out those casts tonight to finish this off.

**Comment by Jormundir** [comment]
@alexcrichton thank you for the review. I'll take those casts out tonight to finish this off.

**Comment by Jormundir** [comment]
What's the procedure for these types of platform specific failures? Should I fix the failures in the output and lean on the test suite, or should I go whole hog and set up a windows vm to test before making a patch commit?

**Comment by alexcrichton** [comment]
Either way is fine, all platforms will need to pass tests for this to land, however. There probably aren't too many problems, though, so setting up a VM may not be necessary.

**Comment by steveklabnik** [comment]
@alexcrichton it seems @Jormundir has updated, r?

**Comment by Jormundir** [comment]
The test failure was due to file permissions?
