### PR TITLE
Fix `--remap-path-prefix` not correctly remapping `rust-src` component paths and unify handling of path mapping with virtualized paths

### LINKED ISSUE #73167: Binaries end up containing path to the rust-src component despite `--remap-path-prefix`
When the following code is built with rustc with `rust-src` component available to it, the binary will end up containing the reference to the libstd source in the rustc installation path. This reference is then possibly printed out if this program panics if an error ever occurs.

```rust
fn main() {
    std::thread::spawn(|| {
        println!("hello");
    });
}
```

Compile this program as such:

```
$ rustc src/main.rs
```

and inspect the executable with `strings`:

```
$ strings ./main | grep lib/rustlib
failed to spawn thread/nix/store/blyf5kcrmi9kciffk18qm9r6xr9k4c6v-rust-1.45.0-nightly-2020-06-04-47c3158c3/lib/rustlib/src/rust/src/libstd/thread/mod.rs
there is no such thing as a relaxed fence/nix/store/blyf5kcrmi9kciffk18qm9r6xr9k4c6v-rust-1.45.0-nightly-2020-06-04-47c3158c3/lib/rustlib/src/rust/src/libcore/macros/mod.rs
```

Then try to get rid of the source paths with the flag dedicated for exactly this purpose:

```
$ rustc src/main.rs --remap-path-prefix=/nix/store/blyf5kcrmi9kciffk18qm9r6xr9k4c6v-rust-1.45.0-nightly-2020-06-04-47c3158c3/lib/rustlib/src/=/rustc-src/
```

and notice that the binary contains the path to the original directory _anyway_:

```
$ strings ./main | grep lib/rustlib
failed to spawn thread/nix/store/blyf5kcrmi9kciffk18qm9r6xr9k4c6v-rust-1.45.0-nightly-2020-06-04-47c3158c3/lib/rustlib/src/rust/src/libstd/thread/mod.rs
there is no such thing as a relaxed fence/nix/store/blyf5kcrmi9kciffk18qm9r6xr9k4c6v-rust-1.45.0-nightly-2020-06-04-47c3158c3/lib/rustlib/src/rust/src/libcore/macros/mod.rs
```

The relevant logic appears to be here:

https://github.com/rust-lang/rust/blob/master/src/librustc_metadata/rmeta/decoder.rs#L1450

However it is not clear to me that this is the right place to introduce more logic to handle `--remap-path-prefix`.

### Version

nightly 2020-06-05

cc @eddyb who appears to have added this logic in https://github.com/rust-lang/rust/pull/70642

### PR DESCRIPTION
**Pull request by cbeuw**
This PR fixes #73167 ("Binaries end up containing path to the rust-src component despite `--remap-path-prefix`") by preventing real local filesystem paths from reaching compilation output if the path is supposed to be remapped.

`RealFileName::Named` introduced in #72767 is now renamed as `LocalPath`, because this variant wraps a (most likely) valid local filesystem path.

`RealFileName::Devirtualized` is renamed as `Remapped` to be used for remapped path from a real path via `--remap-path-prefix` argument, as well as real path inferred from a virtualized (during compiler bootstrapping) `/rustc/...` path. The `local_path` field is now an `Option<PathBuf>`, as it will be set to `None` before serialisation, so it never reaches any build output. Attempting to serialise a non-`None` `local_path` will cause an assertion faliure.

When a path is remapped, a `RealFileName::Remapped` variant is created. The original path is preserved in `local_path` field and the remapped path is saved in `virtual_name` field. Previously, the `local_path` is directly modified which goes against its purpose of "suitable for reading from the file system on the local host".

`rustc_span::SourceFile`'s fields `unmapped_path` (introduced by #44940) and `name_was_remapped` (introduced by #41508 when `--remap-path-prefix` feature originally added) are removed, as these two pieces of information can be inferred from the `name` field: if it's anything other than a `FileName::Real(_)`, or if it is a `FileName::Real(RealFileName::LocalPath(_))`, then clearly `name_was_remapped` would've been false and `unmapped_path` would've been `None`. If it is a `FileName::Real(RealFileName::Remapped{local_path, virtual_name})`, then `name_was_remapped` would've been true and `unmapped_path` would've been `Some(local_path)`. 

cc @eddyb who implemented `/rustc/...` path devirtualisation

### CODE REVIEW

File: src/test/codegen/remap_path_prefix/issue-73167-remap-std.rs [hunk 1]
```diff
@@ -0,0 +1,16 @@
...
+extern crate pseudo_std;
+// Here we check that imported code from std has their path remapped.
+// If we were to use an actual std function to test, we'd have to remap {{cwd}}/library/...,
+// but that will break if rustc was built with remap-debuginfo = true in config.toml.
+// Hence we simulate the path rust-src would take in a real linux installation
+// by remapping the prefix inside pseudo_std.rs
+// CHECK: !DIFile(filename: "REDACTED/TOOLCHAIN/lib/rustlib/src/rust/library/std/src/pseudo_std.rs", directory: ""
+fn main() {
+    pseudo_std::some_std_function();
+}
```
Comment (cbeuw) [inline src/test/codegen/remap_path_prefix/issue-73167-remap-std.rs:16]: Ideally this could be a single test file with the exact code snippet from #73167: https://github.com/rust-lang/rust/pull/83813/commits/d760af1c308400c967843ce04384d73f3c8c4b10. Instead of this workaround it might be more proper to add a header command to ignore it when `remap-debuginfo = true`, though I'm not sure.

**Comment by eddyb** [comment]
cc @pnkfelix @michaelwoerister

File: src/test/codegen/remap_path_prefix/issue-73167-remap-std.rs (hunk 1 above)
Comment (nagisa) [reply src/test/codegen/remap_path_prefix/issue-73167-remap-std.rs:16]: While this test does fail with today's rustc and is therefore useful, I'm not entirely sure this hits the code paths that are taken when the `rust-src` issue comes up. In particular the codepaths related to the `CFG_VIRTUAL_RUST_SOURCE_BASE_DIR` environment variable are not invoked.

As `CFG_VIRTUAL_RUST_SOURCE_BASE_DIR` is set by bootstrap to a value computed by this snippet… https://github.com/rust-lang/rust/blob/97717a561844eccbb6d6cc114adb94a8fa4e0172/src/bootstrap/lib.rs#L821-L824

…so I think we could write a makefile test that builds a `pseudo_std` a lot more like `std` or other sysroot crates with respect to path remapping behaviour.

---

Did the test you added in the first commit not work right? Why?

File: src/test/codegen/remap_path_prefix/issue-73167-remap-std.rs [hunk 2]
```diff
@@ -0,0 +1,16 @@
...
+// compile-flags: -g  -C no-prepopulate-passes --remap-path-prefix=/home/USERNAME=REDACTED
+// aux-build:pseudo_std.rs
+
+extern crate pseudo_std;
+// Here we check that imported code from std has their path remapped.
+// If we were to use an actual std function to test, we'd have to remap {{cwd}}/library/...,
+// but that will break if rustc was built with remap-debuginfo = true in config.toml.
+// Hence we simulate the path rust-src would take in a real linux installation
+// by remapping the prefix inside pseudo_std.rs
+// CHECK: !DIFile(filename: "REDACTED/TOOLCHAIN/lib/rustlib/src/rust/library/std/src/pseudo_std.rs", directory: ""
```
Comment (nagisa) [inline src/test/codegen/remap_path_prefix/issue-73167-remap-std.rs:13]: A `CHECK-NOT:` of the undesired prefixes across the entire file would be slightly more versatile than a check for a specific debuginfo metadata.

**Review by nagisa — COMMENTED** [review]
Could the history be simplified, please?

e.g. 1 commit for adding a test case, rather than 2, combine the `Devirtualized` changes into one, etc. As the history is right now, its not very straightforward to follow and makes reviewing difficult as the same area of code is changed multiple times.

Furthermore, am I correct that the last 2 commits are not required to fix the issue itself? Could those be split out into a separate PR?

File: src/test/codegen/remap_path_prefix/issue-73167-remap-std.rs (hunk 1 above)
Comment (cbeuw) [reply src/test/codegen/remap_path_prefix/issue-73167-remap-std.rs:16]: The test in the first commit works when `remap-debuginfo = false` in `config.toml`, but it breaks when it's set to true because `/rustc/$version/library...` will be imported rather than `{{cwd}}/library`, so remapping from `{{cwd}}` to something else won't do anything.

I think it's better to revert to the original single-file test, and use a `CHECK-NOT:` on `{{cwd}}` instead. This way the behaviour of having `rust-src` would be correctly simulated and tested when `remap-debuginfo = false`, but the test would still pass with `remap-debuginfo = true`.

Comment (nagisa) [reply src/test/codegen/remap_path_prefix/issue-73167-remap-std.rs:16]: The plan seems fine, though I still think we should keep both tests as they still exercise slightly different code paths.

**Comment by cbeuw** [comment]
@nagisa yeah I probably should've squashed some of them before the PR. I'll reorganise every change so far and force push. So further changes can still be kept as individual commits.

It's true that the bug can be solved without the last two commit and I did contemplate putting up two PRs. But the second PR would have to incorporate all the changes in the first one, so it seems I need to wait until the first PR merges into master first? Another reason was that the state before the last two commits has bits I'm unsure about (for instance, `unmaped_path` is supposed to be `None` for imported files, but we are remapping imported file paths, should it be set or left as `None` - it's better to just remove the field entirely), so I decided to put all changes in one PR to be reviewed together

File: src/test/codegen/remap_path_prefix/issue-73167-remap-std.rs (hunk 1 above)
Comment (cbeuw) [reply src/test/codegen/remap_path_prefix/issue-73167-remap-std.rs:18]: I renamed the new test and added back in the test in the first commit. It turns out that I can't use `{{cwd}}` inside a `CHECK-NOT:` directive (it'll be preserved literally and not expanded) and FileCheck itself doesn't provide similar environment variables, so I used regex wildcard on what would've been `{{cwd}}` and made it work on the path after that instead (`{{cwd}}/library/std` getting remapped to something else without the `library/std` bit)

**Comment by michaelwoerister** [comment]
Nice! Thanks for the PR, @cbeuw!

@nagisa, @varkor, let me know if you'd like me to take a closer look at the fix.

**Comment by nagisa** [comment]
Please do! My primary concern is basically that this implements repeated remapping, whereas in the linked issue @eddyb said:

> I don't think `--remap-path-prefix` should remap paths that were already remapped

I think implementation wise this is fine. Perhaps what we need is a `fcp merge`?

**Comment by cbeuw** [comment]
@nagisa Regarding repeated remapping, I think there are two senarios:
1. Remapping a `/rustc/$hash/...` path which has been remapped during compiler bootstraping. Although it doesn't seem very useful, I don't see why we shouldn't allow this. It might be used (in a very contrived manner) to manually remap it back to a real path on the system for a sysroot crate without installing `rust-src`.
2. Remapping paths embedded in the compilation output of another crate, which may have already been remapped. This is what src/test/codegen/remap_path_prefix/double-remap-imported.rs is testing. This shouldn't happen if rustc is invoked by cargo, as it passes the same `RUSTFLAGS` to all invocation to `rustc` - that is unless the user specifies multiple `--remap-path-prefix`es with the `to` path of one matching `from` path of another, e.g. `--remap-path-prefix=a=b --remap-path-prefix=b=c`. It shouldn't break anything and I don't think we should place artificial restrictions on this.

**Comment by varkor** [comment]
> @nagisa, @varkor, let me know if you'd like me to take a closer look at the fix.

I'm very busy at the moment, so if you'd be happy to complete the review, that would be great :)

r? @michaelwoerister

**Comment by michaelwoerister** [comment]
OK, I'll take over the review 👍

**Comment by michaelwoerister** [comment]
@eddyb Do you think that the functionality in https://github.com/rust-lang/rust/pull/70642 could also be implemented by making Rustup's `rustc` wrapper binary inject an appropriate `--remap-path-prefix` option?

**Comment by eddyb** [comment]
> @eddyb Do you think that the functionality in #70642 could also be implemented by making Rustup's `rustc` wrapper binary inject an appropriate `--remap-path-prefix` option?

No, I think that's way too invasive. I'm not sure if this was clear to everyone but part of the reason for making it sysroot-relative is that distro packages *can also* supply it, as long as they follow the same path hierarchy that `rust-src` has (AFAIK `make install` / `x.py install` should be enough?).

Maybe the hash and/or version should be part of the src paths in `rust-src` itself? Then the whole `/rustc/<hash>` hack could be replaced with just something like `$sysroot` - ofc this would break a bunch of tools, but it would also make it more clear what is going on.

Anyway I'm not super sure why the whole virtualized path thing is even relevant.
Its purpose is to allow *diagnostics* to point to an actual file to improve UX (we could even hide the path and only use it to *show* the code, really, but then the user wouldn't have access to wider context). The "devirtualized local path" should never end up in `file!()`/`#[track_caller]`/debuginfo, and if it does that's a bug IMO.

**Comment by michaelwoerister** [comment]
I'm still in the process of finding out what the status quo is and how this PR modifies it. My findings so far are:

- #70642 (Translate the virtual /rustc/$hash prefix back to a real directory) in conjunction with #72767 (Track devirtualized filenames) seem to do the right thing in that they preserve the stable version of imported file names, so in theory it's still available for emitting to panic messages, debuginfo, etc. 
- #72767, however, does not seem to adapt [debuginfo generation code](https://github.com/rust-lang/rust/blob/1c158b6a8b440f826d952c3a8f42bdc3f77a5ac1/compiler/rustc_codegen_llvm/src/debuginfo/metadata.rs#L765) for file names. If I read this correctly, `Filename::to_string()` will fall back on the `Display` implementation which gives the `local_path`. I would expect that this causes #73167 for debuginfo. I don't know yet if there are other such cases, such as the `file!()` macro.
- The current reliance on `Display` for `Filename` makes it easy to accidentally end up using the wrong version.
- `SourceFile::unmapped_path` and `FileName::Devirtualized::local_path` seem to overlap in functionality.
- The term "virtual" seems to be used with two different meanings in this context, once for remapped/stable paths and once for compiler-generated source files.

Currently it does not look to me like we *need* remapping of imported paths (i.e. "double remapping") to fix #73167. The compiler has the stable name of upstream file names available. I would opt for trying to fix the existing bugs without introducing new functionality (which would probably need a [major change proposal](https://forge.rust-lang.org/compiler/mcp.html)).

That being said, from the description of the PR it sounds like it contains some nice cleanup refactorings. I'll take a closer look soon.

**Comment by michaelwoerister** [comment]
> No, I think that's way too invasive. I'm not sure if this was clear to everyone but part of the reason for making it sysroot-relative is that distro packages can also supply it ...

Yes, that makes sense to me.

File: compiler/rustc_metadata/src/rmeta/encoder.rs [hunk 3]
```diff
@@ -485,18 +488,22 @@ impl<'a, 'tcx> EncodeContext<'a, 'tcx> {
...
+                        // wrong directory.
                         let mut adapted = (**source_file).clone();
-                        adapted.name = Path::new(&working_dir).join(name).into();
+                        adapted.name = match name {
+                            RealFileName::Named(local_path) => {
+                                Path::new(&working_dir).join(local_path).into()
+                            }
+                            RealFileName::Virtualized { local_path, virtual_name } => {
+                                FileName::Real(RealFileName::Virtualized {
+                                    local_path: Path::new(&working_dir).join(local_path),
```
Comment (michaelwoerister) [inline compiler/rustc_metadata/src/rmeta/encoder.rs:502]: The local path of a file must not end up in metadata. That's one of the requirements for path remapping (because of reproducible builds and privacy issues). 

If you look carefully, the existing implementation "flattens" the filename from `RealFileName::Devirtualized` into `RealFileName::Named` in line 499. Similarly, in the new version we need to map any `RealFileName::Virtualized` to a `RealFileName::Named` leaving only the `virtual_name` in there.

**Comment by cbeuw** [comment]
Currently there isn't a `impl ToString for FileName`, hence it falls back to `impl Display for FileName` which returns the `local_name` for (de)virtualised variant:
https://github.com/rust-lang/rust/blob/1c158b6a8b440f826d952c3a8f42bdc3f77a5ac1/compiler/rustc_span/src/lib.rs#L196-L201

There's one place where `FileName::to_string()` is used for debuginfo:
https://github.com/rust-lang/rust/blob/1c158b6a8b440f826d952c3a8f42bdc3f77a5ac1/compiler/rustc_codegen_llvm/src/debuginfo/metadata.rs#L761-L774

And used for panic location:
https://github.com/rust-lang/rust/blob/1c158b6a8b440f826d952c3a8f42bdc3f77a5ac1/compiler/rustc_codegen_ssa/src/mir/block.rs#L1150-L1154

It's probably appropirate to manualy do `impl ToString for FileName` and leave `impl Display for FileName` exclusively responsible for diagnostics.

File: compiler/rustc_metadata/src/rmeta/encoder.rs [hunk 4]
```diff
@@ -485,18 +488,22 @@ impl<'a, 'tcx> EncodeContext<'a, 'tcx> {
             })
             .map(|(_, source_file)| {
                 let mut adapted = match source_file.name {
-                    // This path of this SourceFile has been modified by
-                    // path-remapping, so we use it verbatim (and avoid
-                    // cloning the whole map in the process).
-                    _ if source_file.name_was_remapped => source_file.clone(),
```
Comment (michaelwoerister) [inline compiler/rustc_metadata/src/rmeta/encoder.rs:491]: This probably also constitutes a bug in the existing codebase since #72767 because the `source_file`'s `RealFileName` might be `Devirtualized` and thus contains the `local_path`.

**Comment by michaelwoerister** [comment]
Great find about the panic locations, @cbeuw! These are exactly the things we need to look for. I wonder if we can remove the `Display` implementation for `FileName` and require users to explicitly choose if they want the local or the stable version. It's really easy to get this wrong at the moment.

File: compiler/rustc_metadata/src/rmeta/encoder.rs (hunk 3 above)
Comment (cbeuw) [reply compiler/rustc_metadata/src/rmeta/encoder.rs:502]: The comment here is a bit misleading because it's not really "expand all paths to absolute paths". I just realised that working_dir could've also been remapped hence not absolute. I'll change it. 

If we were to remap all `RealFileName::Virtualized` to a `RealFileName::Named`, I suppose we would only need to deal with `Named` variant in `rustc_metadata/src/rmeta/decoder.rs:imported_source_files()`? Although this would make preventing double remapping difficult (probably impossible) without retaining the `name_was_remapped` field in `rustc_span::SourceFile`

File: compiler/rustc_span/src/source_map.rs [hunk 5]
```diff
@@ -380,10 +343,10 @@ impl SourceMap {
             nc.pos = nc.pos + start_pos;
         }
 
+        let (filename, _) = self.path_mapping.map_filename_prefix(&filename);
```
Comment (cbeuw) [inline compiler/rustc_span/src/source_map.rs:346]: What I said above https://github.com/rust-lang/rust/pull/83813#discussion_r608585013 was wrong. To stop double remapping metadata embedded in other crates we just need to remove this line.

File: compiler/rustc_metadata/src/rmeta/encoder.rs (hunk 3 above)
Comment (michaelwoerister) [reply compiler/rustc_metadata/src/rmeta/encoder.rs:502]: I'm not quite happy with the current `RealFileName` variants. The name of the `Named` variant does not tell you what it is for and is potentially confusing (if there is a `Named` variant then why isn't there an `Unnamed` variant, etc...). The `Named` variant can also be either (1) the local path or (2) the stable name, depending on whether remapping was involved or not. And we actually don't always have a name that is really "stable" in the sense of being system independent -- even remapping does not guarantee that the result is stable in that sense. 

So what a `RealFileName` actually can be is:

- The local path to a file
- A remapped path containing the local path and the result of remapping
- A path from upstream crate metadata which can either be 
   - an absolute local path or 
   - a remapped path without the local part

And depending on the situation we want to use the "most stable" path (for emitting to output artefacts) or the path that actually allows you to load something from disk (parsing & error messages).

I think I would suggest the following:

- Rename `RealFileName::Named` to `RealFileName::LocalPath` -- because that's what it is, right?
- Rename ` RealFileName::Virtualized` to `RealFileName::Remapped` so that the naming does not clash with "virtual files" generated by macro expansion.
- Make `local_path` in `RealFileName::Remapped` an `Option<_>` so that we can explicitly "erase" the local portion of the remapped path during export.
- Manually implement `Encodable` for `RealFileName` and panic if we encounter a `local_path` that wasn't erased (i.e. `assert!(local_path.is_none())`).
- Maybe rename the `stable_name` method to something like `most_stable_name` and documentation that it will fall back on the local path if that's the only thing available.
- Use `RealFileName` for the `working_dir` field in `Session` to make things explicit there too.

Comment (michaelwoerister) [reply compiler/rustc_metadata/src/rmeta/encoder.rs:502]: How does that sound to you?

Comment (cbeuw) [reply compiler/rustc_metadata/src/rmeta/encoder.rs:502]: Yup that sounds a lot cleaner

Comment (cbeuw) [reply compiler/rustc_metadata/src/rmeta/encoder.rs]: Another approach to making `local_path` in `RealFileName::Remapped` an `Option<_>` is to introduce another variant `FileName::External`, which takes two values: the path and a boolean indicating if it has been remapped already. The boolean is needed so that already remapped paths from the metadata of another crate won't be remapped again (although those haven't been remapped will be, otherwise we can't do anything about `$HOME/.cargo/registry/...` paths everywhere). A `FileName::Real` is turned into `FileName::External` in `rustc_metadata::rmeta::encoder`.

This makes an explicit distinction between self-generated and imported metadata and prevents needing all those changes to librustdoc in https://github.com/rust-lang/rust/pull/83813/commits/fdcae961afc0369dc51438bfe2ec2b516a83673d

**Comment by michaelwoerister** [comment]
@cbeuw This seems to have reached a steady state. Shall I do another review?

**Comment by cbeuw** [comment]
@michaelwoerister Yes please!

File: compiler/rustc_metadata/src/rmeta/decoder.rs [hunk 6]
```diff
@@ -1633,7 +1633,7 @@ impl<'a, 'tcx> CrateMetadataRef<'a> {
             if let Some(virtual_dir) = virtual_rust_source_base_dir {
                 if let Some(real_dir) = &sess.real_rust_source_base_dir {
                     if let rustc_span::FileName::Real(old_name) = name {
-                        if let rustc_span::RealFileName::Named(one_path) = old_name {
+                        if let rustc_span::RealFileName::LocalPath(one_path) = old_name {
```
Comment (michaelwoerister) [inline compiler/rustc_metadata/src/rmeta/decoder.rs:1636]: The Rust sources should now show up as `rustc_span::RealFileName::Remapped` with their `local_path` being `None`. Unless they were not remapped in the first place, in which case we would not get a match below anyway.

File: compiler/rustc_save_analysis/src/span_utils.rs [hunk 7]
```diff
@@ -16,8 +16,7 @@ impl<'a> SpanUtils<'a> {
 
     pub fn make_filename_string(&self, file: &SourceFile) -> String {
         match &file.name {
-            FileName::Real(name) if !file.name_was_remapped => {
-                let path = name.local_path();
+            FileName::Real(RealFileName::LocalPath(path)) => {
```
Comment (michaelwoerister) [inline compiler/rustc_save_analysis/src/span_utils.rs:19]: I'm not quite sure what the original intention of this code is ...

File: compiler/rustc_span/src/lib.rs [hunk 8]
```diff
@@ -114,52 +114,83 @@ pub fn with_default_session_globals<R>(f: impl FnOnce() -> R) -> R {
...
+                encoder.emit_enum_variant("LocalPath", 0, 1, |encoder| {
+                    Ok({
+                        encoder.emit_enum_variant_arg(0, |encoder| local_path.encode(encoder))?;
+                    })
+                })
+            }
+
+            RealFileName::Remapped { ref local_path, ref virtual_name } => encoder
+                .emit_enum_variant("Remapped", 1, 2, |encoder| {
+                    // For privacy, we must not embed host-dependant path in artifacts
```
Comment (michaelwoerister) [inline compiler/rustc_span/src/lib.rs:151]: Also mention reproducible builds, please.

File: compiler/rustc_span/src/lib.rs [hunk 9]
```diff
@@ -192,13 +223,7 @@ impl std::fmt::Display for FileName {
...
         use FileName::*;
         match *self {
-            Real(RealFileName::Named(ref path)) => write!(fmt, "{}", path.display()),
-            // FIXME: might be nice to display both components of Devirtualized.
-            // But for now (to backport fix for issue #70924), best to not
-            // perturb diagnostics so its obvious test suite still works.
-            Real(RealFileName::Devirtualized { ref local_path, virtual_name: _ }) => {
-                write!(fmt, "{}", local_path.display())
-            }
+            Real(ref name) => write!(fmt, "{}", name.most_stable_name().display()),
```
Comment (michaelwoerister) [inline compiler/rustc_span/src/lib.rs:226]: I don't think we should change the semantics of this implementation. Do you have an idea how much impact it would have to remove the `Display` impl for `Filename` altogether? I'd like to try forcing `Filename` users to explicitly make a decision which version of the path they want. For example by adding the `most_stable_name` method to `FileName` too and a `local_name_if_available()` method. The values returned by each of these would then implement `Display`.

File: compiler/rustc_span/src/source_map.rs [hunk 10]
```diff
@@ -127,30 +127,16 @@ pub struct StableSourceFileId(u128);
...
-            real_name.stable_name().hash(&mut hasher)
-        } else {
-            name.hash(&mut hasher);
-        }
-        name_was_remapped.hash(&mut hasher);
-        unmapped_path.hash(&mut hasher);
+        // If name was remapped, we need to take both the local path
+        // and stablised path into account, in case two different paths were
+        // mapped to the same
+        name.hash(&mut hasher);
```
Comment (michaelwoerister) [inline compiler/rustc_span/src/source_map.rs:139]: I'll need to look into this some more. We don't want to revive https://github.com/rust-lang/rust/issues/70924 again.

**Review by michaelwoerister — COMMENTED** [review]
Nice, great progress!

I'll do another pass tomorrow and look into some of the open questions I noted below.

File: compiler/rustc_span/src/lib.rs (hunk 9 above)
Comment (cbeuw) [reply compiler/rustc_span/src/lib.rs]: So I chased down every usage of `FileName::fmt` and `to_string`. The commits after https://github.com/rust-lang/rust/pull/83813/commits/3047fc7ae7b8985aad85bbdb9d04a8a39d3fc287 are the work.

`FileName::to_string_virtual` is used when it isn't a `FileName::Real(_)` and we don't have to worry about paths. This is helpful sometimes when the callsite had already matched on `Real(_)` and we just need an irrefutable "`otherwise`" arm. Panics if called on `Real(_)`. Might be able to lift it to compile time checks once https://github.com/rust-lang/rfcs/pull/2593 is implemented & stabalised but that's a long way off.

`FileName::to_string_local` is "local name if available". Only to be used when it won't end up in build output.

`FileName::to_string_embeddable` is used when the path will be embedded. This is basically a wrapper around `most_stable_name`.

I swapped `impl Display` methods for the above three functions in steps. `to_string_virtual` is the easiest, immediately obvious from the callsite: https://github.com/rust-lang/rust/pull/83813/commits/8c9214403d5d979eb450e93bdb6753ea77e01e2d (some changes are in the wrong commit due to me trying to rewrite history)

And then some places definitely needs `to_string_embeddable`: https://github.com/rust-lang/rust/pull/83813/commits/0d53c343826a52d3874f0e30fe7fcfaffe4212ef. Mostly codegen backends.

Some places are fine with `to_string_local`: https://github.com/rust-lang/rust/pull/83813/commits/2507bce5b8d7cec31491c05aa2948d2a061ce771, mostly error outputs and rustdoc (which should never get a `Remapped` variant I think)

The rest I'm not sure about. In this case `to_string_embeddable` is always the safer option. Wrong application might make some diagnostics slightly confusing but that's better than leaking information.

`impl Display` is now removed for `FileName` so every place makes an explicit choice.

Comment (michaelwoerister) [reply compiler/rustc_span/src/lib.rs]: Yes, the amount of change required for removing the `Display` impl seems quite acceptable. It it will certainly make it easier to catch errors now and in the future. I'm very pleased with that.

I think we can improve the setup to be a bit more ergonomic and efficient. I see three specific issues:
- We now have a number of terms now ("local", "embeddable", "remapped", and "most_stable") that somewhat overlap. We should reduce the redundancy here in order to avoid confusion. 
- In the current state of the PR we unconditionally allocate memory for a `String` but in most cases we can actually avoid that. 
- From a user's perspective it does not matter very much if a `FileName` is virtual or not (at least not when printing/embedding them). So I think it's better to remove the `to_string_virtual()` method.

I propose that we create a thin wrapper type for `FileName` for printing and embedding purposes. This type can then implement `Display` (for use in `format!()` etc) and provide a `to_string_lossy(&self) -> Cow<str>` method (for use with `Symbol::intern()`). Something like:

```rust
struct FileNameDisplay {
    inner: &FileName,
    prefer_local: bool,
}

impl Display for FileNameDisplay {
     // ...
}

impl FileNameDisplay {
    fn to_string_lossy(&self) -> Cow<'_, str> {
        match self.inner {
            FileName::Real(ref inner) => inner.to_string_lossy(self.prefer_local),
            other => Cow::from(format!("{}", self)),
        }
    }
}

impl FileName {
     fn prefer_remapped() -> FileNameDisplay { ... }
     fn prefer_local() -> FileNameDisplay { ... }
}
``` 

`RealFileName` would then probably also get a `to_string_lossy()` method with a `prefer_local: bool` parameter (as used above). In turn the `most_stable_name()` method (and the "most stable" terminology in general) could be removed. Then we could call `Symbol::intern()` without allocating memory for most real file names, e.g.:

```rust
Symbol::intern(&loc.file.name.prefer_remapped().to_string_lossy())
```

The `to_string_virtual` method would go away. One would just use `prefer_local()` or `prefer_remapped()` as appropriate (and get the same result in both cases). Alternatively, the method could be renamed to something like `to_string_assert_is_virtual()`.

File: compiler/rustc_span/src/source_map.rs (hunk 10 above)
Comment (michaelwoerister) [reply compiler/rustc_span/src/source_map.rs:139]: OK, it looks to me like the previous version of this code only fixed #70924 because `try_to_translate_virtual_to_real()` in `CrateMetadataRef::imported_source_files()` does not correctly update `unmapped_path` and `name_was_remapped`. In order to preserve the fix we must hash only the remapped path. Maybe we could (manually) implement `Hash` for the proposed `FileNameDisplay` type for this purpose.

File: compiler/rustc_span/src/lib.rs (hunk 9 above)
Comment (cbeuw) [reply compiler/rustc_span/src/lib.rs]: I renamed `most_stable_name()` to `remapped_name_if_available()` because there are places needing an embeddable `Path`. If we were to remove it we'd have to convert to `String` and back again.

File: compiler/rustc_span/src/source_map.rs (hunk 10 above)
Comment (cbeuw) [reply compiler/rustc_span/src/source_map.rs:136]: Good catch, this probably would've reintroduced #70924. I manually implemented `Hash` for `RealFileName` so it hashes only the remapped path if available.

Still concerned about the edge case of two files mapping to the same thing. E.g. we have a `src/lib.rs` relative to the current working directory, then there's a `/dependency/src/lib.rs` and we do `--remap-path-prefix=/dependency/=`, causing the latter to be remapped to the former. 

I still don't understand why change in presence of `rust-src` would trigger a panic. If `rust-src` was present before and the compilation cached, then we remove the component, surely it would lead to a different `StableSourceFileId` if we just hash the whole `RealFileName` with `local_path` (now is `None`), causing the cache to be rebuilt?

File: compiler/rustc_metadata/src/rmeta/encoder.rs [hunk 11]
```diff
@@ -490,22 +490,23 @@ impl<'a, 'tcx> EncodeContext<'a, 'tcx> {
                     FileName::Real(ref realname) => {
                         let mut adapted = (**source_file).clone();
                         adapted.name = FileName::Real(match realname {
-                            RealFileName::LocalPath(local_path) => {
-                                // Prepend path of working directory onto local path.
-                                // because relative paths are potentially relative to a
-                                // wrong directory.
+                            RealFileName::LocalPath(relative) => {
```
Comment (michaelwoerister) [inline compiler/rustc_metadata/src/rmeta/encoder.rs:493]: We actually don't know if this is a relative path or an absolute one. It's just that `Path::join` is a no-op if the argument is an absolute path, so we don't care.

File: compiler/rustc_span/src/lib.rs (hunk 9 above)
Comment (michaelwoerister) [reply compiler/rustc_span/src/lib.rs]: Those changes look good to me. Now we just need to figure out a clean handling for `StableSourceFileId` ...

File: compiler/rustc_metadata/src/rmeta/decoder.rs [hunk 12]
```diff
@@ -1671,9 +1673,13 @@ impl<'a, 'tcx> CrateMetadataRef<'a> {
...
-                                let new_name = rustc_span::RealFileName::Devirtualized {
-                                    local_path: new_path,
-                                    virtual_name,
+                                let new_name = rustc_span::RealFileName::Remapped {
+                                    local_path: Some(new_path),
+                                    virtual_name: sess
+                                        .source_map()
+                                        .path_mapping()
+                                        .map_prefix(virtual_name)
+                                        .0,
```
[the remark this answers is not in the document]
Comment (michaelwoerister) [reply compiler/rustc_metadata/src/rmeta/decoder.rs:1682]: I don't quite understand. This looks like we are applying the re-mapping to already remapped paths again. That's not what we want, is it? (i.e. the imported paths should stay just as they are if they are being re-emitted)

[the remark this answers is not in the document]
Comment (cbeuw) [reply compiler/rustc_metadata/src/rmeta/decoder.rs:1682]: This is in `try_to_translate_virtual_to_real` so it only affects sysroot crates. But yes we should preserve the original semantics and not remap it again

**Comment by michaelwoerister** [comment]
OK, I did some more digging and found a few interesting things:

- The `name_hash` field `SourceFile` must only be a hash of what is now `file_name.prefer_remapped().to_string_lossy()` because it becomes part of the "crate hash" (aka SVH). The crate hash is embedded into output artifacts too.
- We probably want to get rid of `StableSourceFileId` altogether and instead store the entire contents of `FileName` in the on-disk cache. This way we can more reliably correlate source files between compilation sessions in the case where the `rust-src` component gets added and prefix mappings are added or changed. 
- I think we should make it an error if two paths get mapped to the same result. It's easy enough to detect during insertion in `SourceMapFiles::stable_id_to_source_file` and I'm almost certain that parts of the compiler will rely on all source file names being distinct. I'm just not sure we should do it as part of this PR because there's a small chance that it will break someone somewhere.

I'm sorry that this PR turns more and more into a rabbit hole 😃 But this is stuff is quite a bit more complicated and fragile than one would expect.

**Comment by cbeuw** [comment]
@michaelwoerister No worries! It's important to get it right.

I don't think we should disallow remapping two sources to the same name. For the compiler, part of the point of tracking both tlocal and virtual paths is so that we can pick as appropirate; and for the user it's may cause build failures if they write a build script on one system and run it on another, where the other system's directory layouts cause two remappings end up being the same.

For the "local crate" where we have `local_path` available, it's fine to have `name_hash` taking into account of that. For emitted metadata from another crate, with `local_path` being `None`, there's no way we can idenitfy, uniquely, a source file from the information in `FileName` alone. For this we could emit a `name_hash` taking into account of the `local_path` before sanitisation, and we never recalculate it when we get a `SourceFile` from external metadata. Alternatively we could simply collisions between `name_hash` and the incremental compilation will check other parts of `SourceFile` to determine its identity - I'm fairly sure this has always been the case? Otherwise it won't be able to even handle change of source content without changing file names. 

If the point of `StableSourceFileId` is to uniquely identify a source file, changing it to `FileName` won't help due to the sanitisation step. Why can't we take the `src_hash` and `cnum` into account as well?

Regarding incremental compilation, currently if we change `--remap-path-prefix`, `rustc` invalidates the cache for everything and build from scratch. I think this is fine because people generally don't fiddle around with that option during development. It's nice to not having to invalidate the cache, but if that proves to be too tricky it's an OK trade off to make for this PR.

This hash issue almost definitely _collides_ with the scope of #83591 quite a bit. I'll need to think over the implications of that

**Comment by cbeuw** [comment]
I had a bit more dig around regarding the use of `StableSourceFileId`, here's what I think:

Ultimately, the filesystem only provides us with two pieces of information about the file: its path and its content, and our aim, as I understood, is to use these two pieces of information alone to find a `SourceFile` from the on-disk cache. This requires the on-disk cache to contain something that allows later sessions to uniquely idenitfy a `SourceFile`. Content can't be used because they can easily be the same across two files, so we are left with the path. Before any remapping, this can uniquely identify a `SourceFile`.

So we are left with two options: either let the artifacts to contain the local path or its hash, or prevent two paths from ever being remapped to the same thing.

I think the former option is fine, so long as the local path doesn't get embedded in the codegen output. I don't see much value in preventing filesystem layout-sentitive information from reaching metadata used for incremental compilations as they are never meant to be distributed anyway. This also sidesteps the concern on parts of the compiler will rely on all source file names being distinct. We could still replace `StableSourceFileId` with `FileName` now that we don't have separate `unmapped_path` etc. in other places

**Comment by michaelwoerister** [comment]
> Regarding incremental compilation, currently if we change --remap-path-prefix, rustc invalidates the cache for everything and build from scratch.

Unfortunately, I don't think this is true. We excluded `--remap-path-prefix` from the commandline's "dep-tracking-hash" because otherwise one could not have reproducible builds from different source directories (see https://github.com/rust-lang/rust/pull/48162). However, I think we should *make* it true -- we'll save us a number of headaches if we don't have to deal with incremental compilation.

It will require some special handling but it might be straightforward to implement this without breaking reproducible builds. Incr. comp. already [uses the commandline's "dep-tracking-hash" for invalidating the cache](https://github.com/rust-lang/rust/blob/25c15cdbe070f49d708f34750df2632e38bd4846/compiler/rustc_incremental/src/persist/load.rs#L168-L183). We can just store another hash just for `--remap-path-prefix` alongside. Since this hash is not going to be fed into the crate-hash we won't run into problems with reproducible builds.

I wonder if this could help with #83591 too if we also feed `CFG_VIRTUAL_RUST_SOURCE_BASE_DIR` into this additional hash -- but I have not yet had time to really understand the problem that #83591 tries to solve.

**Comment by Aaron1011** [comment]
@michaelwoerister: My PR isn't directly related to `CFG_VIRTUAL_RUST_SOURCE_BASE_DIR` or `--remap-path-prefix` (given the current behavior of those options). The issue is that the `Span`s decoded from a foreign crate depend on whether or not `rust-src` exists in the *current* compilation session. Adding or removing `rust-src` between compilations will cause external queries to produce different results given the same (tracked) input and foreign crate hash.

**Comment by michaelwoerister** [comment]
> The issue is that the Spans decoded from a foreign crate depend on whether or not rust-src exists in the current compilation session.

@Aaron1011 Do you know what exactly causes the spans to have a different stable hash?

**Comment by michaelwoerister** [comment]
It sounds like clearing the incr. comp. cache of the current crate when ever the value of `CFG_VIRTUAL_RUST_SOURCE_BASE_DIR` has changed can fix the problem because then there is no previous fingerprint to compare to, right? (however, I'm not a 100% positive that I have the right mental model of the problem yet...)

**Comment by Aaron1011** [comment]
@michaelwoerister: Currently, it's the fact that we hash the entire `RealFileName`, which will be different if a 'devirtualized' filename is used.

If we want to make the stable hash independent of the presence of `rust-src`, then we need to ensure that queries cannot directly use the devirtualized name (they can only use the raw decided name,.which may be a virtual path). In particular, the diagnostic code will need to delay computation of the filename until the diagnostic is actually printed to the screen, so that we can properly save diagnostics in the incremental cache.

**Comment by michaelwoerister** [comment]
That sounds complicated `:)`

However, I think we can solve the problem in a robust way by clearing the cache if `Session::real_rust_source_base_dir` changes in between sessions (via the same mechanism I [proposed for --remap-path-prefix](https://github.com/rust-lang/rust/pull/83813#issuecomment-824915891)). That way you are effectively tracking `rust-src` and `--remap-path-prefix` as inputs, like we do for commandline parameters. The only difference is that those two pieces of information don't make it into the crate-hash -- which is OK because we are taking care of them in a different way. 

> Currently, it's the fact that we hash the entire RealFileName, which will be different if a 'devirtualized' filename is used.

I think that is actually just a bug that will be solved by this PR.

**Comment by cbeuw** [comment]
Going by the `dep_tracking_hash` idea, it seems this where the command line argument hash is saved
https://github.com/rust-lang/rust/blob/7f4afdf0255600306bf67432da722c7b5d2cbf82/compiler/rustc_incremental/src/persist/save.rs#L221-L229

I guess we could keep `remap_path_prefix` untracked, but just additionally merge its hash, plus the hash of `Session::real_rust_source_base_dir` after this? The comment kind of implies that it's expected there will be extra info added in the future, even though not currently.

**Comment by michaelwoerister** [comment]
@cbeuw Yes, that's the correct spot. I think we should implement this by adding a third variant to commandline option tracking. Right now we have `[TRACKED]` and `[UNTRACKED]`. We can add `[TRACKED_NO_CRATE_HASH]` to that list for things that must not be included in the crate-hash (e.g. stuff containing local paths) but should nonetheless invalidate the incr. comp. cache. I think there are a few options that are `[UNTRACKED]` at the moment but that should actually invalidate the cache (`Options::search_paths` looks like a good candidate for that).

If we then also move `real_rust_source_base_dir` from `Session` to `Options` then we don't need to have special handling for it.

The commandline options hashing code is here: https://github.com/rust-lang/rust/blob/236580bc5bed062ad3fc34f445af8e8a54713258/compiler/rustc_session/src/options.rs#L23-L63

If you pull the body of the `[TRACKED]` branch in `hash_option!()` out into a function, it should be straightforward to add a `[TRACKED_NO_CRATE_HASH]` branch. You could then add a `include_no_crate_hash_options` parameter to `dep_tracking_hash()`. That way we won't have to change how things work in the dep-graph -- just pass `true` there and false in `hir::map::index_hir()`. 

I think it would be fine to just cover `real_rust_source_base_dir` and `remap_path_prefix` in this PR and look into other possible candidates later.

Let me know if you need help with the macro code `:)`

File: src/librustdoc/doctest.rs [hunk 13]
```diff
@@ -883,16 +885,22 @@ impl Tester for Collector {
...
-        // FIXME(#44940): if doctests ever support path remapping, then this filename
-        // needs to be the result of `SourceMap::span_to_unmapped_path`.
         let path = match &filename {
-            FileName::Real(path) => path.local_path().to_path_buf(),
+            FileName::Real(path) => {
+                if let Some(local_path) = path.local_path() {
+                    local_path.to_path_buf()
+                } else {
+                    // Somehow we got the filename from the metadata of another crate, should never happen
+                    PathBuf::from(r"doctest.rs")
```
Comment (jyn514) [inline src/librustdoc/doctest.rs:894]: Hmm, could you change this to an assert instead? This seems like a bug, I'd rather we notice it quickly than paper over it.
```suggestion
                    // Somehow we got the filename from the metadata of another crate, should never happen
                    unreachable!("doctest from a different crate");
```

File: src/librustdoc/formats/cache.rs [hunk 14]
```diff
@@ -156,10 +156,16 @@ impl Cache {
...
-                },
+                FileName::Real(ref p) => {
+                    if let Some(local_path) = p.local_path() {
+                        match local_path.parent() {
+                            Some(p) => p.to_path_buf(),
+                            None => PathBuf::new(),
+                        }
+                    } else {
+                        PathBuf::new()
+                    }
```
Comment (jyn514) [inline src/librustdoc/formats/cache.rs:167]: This will always be `None`, because extern crates are always non-local. That makes me a very nervous - I think that will break `src_href` for any remapped path from another crate. Is there no other way to get the filename? It's ok if it's only a relative path, `clean_path` will strip `src_root` anyway.

File: src/librustdoc/html/render/context.rs [hunk 15]
```diff
@@ -289,7 +289,7 @@ impl<'tcx> Context<'tcx> {
 
         // We can safely ignore synthetic `SourceFile`s.
         let file = match item.span.filename(self.sess()) {
-            FileName::Real(ref path) => path.local_path().to_path_buf(),
+            FileName::Real(ref path) => path.local_path()?.to_path_buf(),
```
Comment (jyn514) [inline src/librustdoc/html/render/context.rs:292]: Ditto, this looks wrong. Rustdoc still needs to generate links to non-local files.

File: src/librustdoc/html/render/context.rs [hunk 16]
```diff
@@ -372,10 +372,17 @@ impl<'tcx> FormatRenderer<'tcx> for Context<'tcx> {
...
-            },
+            FileName::Real(ref p) => {
+                if let Some(local_path) = p.local_path() {
+                    match local_path.parent() {
+                        Some(p) => p.to_path_buf(),
+                        None => PathBuf::new(),
+                    }
+                } else {
+                    // Somehow we got the filename from the metadata of another crate, should never happen
+                    PathBuf::new()
```
Comment (jyn514) [inline src/librustdoc/html/render/context.rs:383]: This comment is definitely wrong. Rustdoc links to non-local crates all the time, whenever an item is re-exported across crates.

File: src/librustdoc/html/sources.rs [hunk 17]
```diff
@@ -76,7 +80,13 @@ impl SourceCollector<'_, 'tcx> {
     /// Renders the given filename into its corresponding HTML source file.
     fn emit_source(&mut self, filename: &FileName) -> Result<(), Error> {
         let p = match *filename {
-            FileName::Real(ref file) => file.local_path().to_path_buf(),
+            FileName::Real(ref file) => {
+                if let Some(local_path) = file.local_path() {
+                    local_path.to_path_buf()
+                } else {
+                    return Ok(());
+                }
```
Comment (jyn514) [inline src/librustdoc/html/sources.rs:88]: This I think should be ok since rustdoc only emits sources for the current crate. Can you change the return to an assert?
```suggestion
                if let Some(local_path) = file.local_path() {
                    local_path.to_path_buf()
                } else {
                    unreachable!("only the current crate should have sources emitted");
                }
```

File: src/librustdoc/html/sources.rs [hunk 18]
```diff
@@ -113,7 +123,7 @@ impl SourceCollector<'_, 'tcx> {
         href.push_str(&fname.to_string_lossy());
 
         let title = format!("{} - source", src_fname.to_string_lossy());
-        let desc = format!("Source of the Rust file `{}`.", filename);
+        let desc = format!("Source of the Rust file `{}`.", filename.prefer_local());
```
Comment (jyn514) [inline src/librustdoc/html/sources.rs:126]: Are you sure prefer_local is correct? I would expect the documentation to get remapped, it's a public artifact the same way binaries are.

**Review by jyn514 — COMMENTED** [review]
Could you please ping me or @GuillaumeGomez when making major changes to rustdoc like this? Several of these changes would have caused regressions if I hadn't caught them.

**Comment by cbeuw** [comment]
@michaelwoerister The `TRACKED_NO_CRATE_HASH` implementation is a bit more complicated than I thought due to the existance of substructs like `CodegenOptions` and `DebuggingOptions`. They also contain a bunch of `TRACKED` and `UNTRACKED` options so we almost definitely wants to extend `TRACKED_NO_CRATE_HASH` to them.

Currently these substructs implements `DepTrackingHash` themselves, but there's no way of passing in `for_crate_hash` (I think this is clearer than `include_no_crate_hash_options`). Adding this argument to the trait's method doesn't make sense because it'll also affect all individual types implementing it.

So I ended up adding another option alled `SUBSTRUCT`, removed `DepTrackingHash` implementation for the substructs and replaced it with a similar `dep_tracking_hash` that takes in `for_crate_hash` as well as the `error_format`. 

The code quality probably isn't great but I just want to push what I have now

**Comment by cbeuw** [comment]
@jyn514 It seems like we made some wrong assumptions. 

Under the current state, the original local paths to source files will no longer be emitted to metadata if that path is affected by path remapping. Originally this path was retrievable before under `SourceFile::unmapped_path` but the bits affected in `librustdoc` didn't touch it. The original calls of `local_path()` would've got
- the local path if it was never remapped,
- the remapped path if it was, or
- the real path to source files to `sysroot` library if `rust-src` is installed

The behaviour is now changed to:
- the local path if it was never remapped,
- if it was remapped, `Some(local path)` if it was from the current crate or `None` if it came from another crate's metadata, or
- the real path to source files to `sysroot` library if `rust-src` is installed

To address the issues discovered I think we just need to use something similar to `FileName::prefer_local` we introduced. This gives the local path if we have it, the remapped one if we don't, which should match the original behaviour.

**Comment by cbeuw** [comment]
I feel like this PR is getting too big and making too much changes than necessary. We can, for now, add `real_rust_source_base_dir` and `remap-path-prefix` to the command line hash without the changes in the last commit on `dep_tracking_hash` and the directives. Those changes can be done in a follow-up PR. Otherwise if something bisects to this PR it'll be a bit difficult to unwind what's going on

**Comment by Aaron1011** [comment]
> However, I think we can solve the problem in a robust way by clearing the cache if Session::real_rust_source_base_dir changes in between sessions

My one concern is that people seem to be running into this issue far more often than I would have expected (see all the issues linked in https://github.com/rust-lang/rust/issues/84341). I'm still not sure how so many people are ending up with the `rust-src` component changed - but assuming that that's the cause of all those issues, we may end up frequently invalidating the entire incremental cache.

**Comment by cbeuw** [comment]
@Aaron1011 For now I won't touch `Session::real_rust_source_base_dir` in this PR, I hope that at least unblocks #84341.

Also could you please approve the GitHub Actions CI? I never contributed to this repo before so it needs collaborator approval due to the recent change: https://github.blog/2021-04-22-github-actions-update-helping-maintainers-combat-bad-actors/. Thanks!

File: src/librustdoc/html/render/context.rs (hunk 16 above)
Comment (cbeuw) [reply src/librustdoc/html/render/context.rs:382]: This comment is misleading. local_path() will still be `Some()` if that path from an external crate hasn't been remapped. Same for other places

**Comment by cbeuw** [comment]
@jyn514 I cherry-picked your changes to the tracking test from #84233

Regarding changes to rustdoc, the last commit makes the behaviour the same as before. Though do note that, like before, if the path to a source in an external crate has been remapped, the path won't be a valid one. It might be more desirable to call `local_path` and check if it's available, and bail otherwise, especially for the places where `.parent()` is called (we may end up at a wrong folder if the external crate's source file has been remapped)

**Comment by michaelwoerister** [comment]
@cbeuw I agree that this PR is getting rather big. We could split out the `[TRACKED_NO_CRATE_HASH]` portion of the changes and merge them first. If @jyn514 agrees we could even make those changes in https://github.com/rust-lang/rust/pull/84233 which was already opened to address that issue. 

@jyn514 We certainly don't want to break rustdoc `:)` A side goal of this PR is to make it more explicit which version of a file name (remapped or not remapped) is used. Both versions should still be as available as before -- so we just have to make sure we update the code correctly. The rustdoc changes (as well as the RLS changes) were on my list of things to double-check with experts before merging. It would be great if you could take a look -- although it might be a good idea to wait until the implementation here has reached a steady state.

**Comment by jyn514** [comment]
> We could split out the [TRACKED_NO_CRATE_HASH] portion of the changes and merge them first. If @jyn514 agrees we could even make those changes in #84233 which was already opened to address that issue.

Sure, I'm happy to do that.

> The rustdoc changes (as well as the RLS changes) were on my list of things to double-check with experts before merging. It would be great if you could take a look -- although it might be a good idea to wait until the implementation here has reached a steady state.

Thank you! Let me know when this is ready for review and I can take a look :)

**Comment by michaelwoerister** [comment]
@jyn514 The relevant information about the proposed strategy to fix tracking of `--remap-path-prefix` starts here: https://github.com/rust-lang/rust/pull/83813#issuecomment-824915891

Feel free to ask questions if anything needs clarification.

**Comment by michaelwoerister** [comment]
FYI, I'm in the middle of doing reviewing pass that should lead to another (hopefully final) set of requests for changes, mostly around semantic changes in RLS, MIRI, etc. Meanwhile https://github.com/rust-lang/rust/pull/84233 has been approved which should help with keeping the scope of this PR as it is.

**Comment by cbeuw** [comment]
@jyn514 Thanks a lot for doing #84233!

File: compiler/rustc_mir/src/interpret/eval_context.rs [hunk 19]
```diff
@@ -263,7 +263,13 @@ impl<'tcx> fmt::Display for FrameInfo<'tcx> {
...
             if !self.span.is_dummy() {
                 let lo = tcx.sess.source_map().lookup_char_pos(self.span.lo());
-                write!(f, " at {}:{}:{}", lo.file.name, lo.line, lo.col.to_usize() + 1)?;
+                write!(
+                    f,
+                    " at {}:{}:{}",
+                    lo.file.name.prefer_remapped(),
+                    lo.line,
+                    lo.col.to_usize() + 1
+                )?;
```
Comment (michaelwoerister) [inline compiler/rustc_mir/src/interpret/eval_context.rs:272]: @rust-lang/miri, what would you like the behavior of this method to be in case `--remap-path-prefix` affects a filename here? Should the method use the remapped path (`lo.file.name.prefer_remapped()`) or should it still use the local file system path (`lo.file.name.prefer_local()`)? 

If the result of this method ever ends up in a library or binary or something else that gets shipped then this must use `prefer_remapped()` in order to enable preserving privacy and reproducible builds.

File: compiler/rustc_mir/src/transform/coverage/mod.rs [hunk 20]
```diff
@@ -284,7 +284,7 @@ impl<'a, 'tcx> Instrumentor<'a, 'tcx> {
         let tcx = self.tcx;
         let source_map = tcx.sess.source_map();
         let body_span = self.body_span;
-        let file_name = Symbol::intern(&self.source_file.name.to_string());
+        let file_name = Symbol::intern(&self.source_file.name.prefer_remapped().to_string_lossy());
```
Comment (michaelwoerister) [inline compiler/rustc_mir/src/transform/coverage/mod.rs:287]: Heads up, code coverage (@richkadel and @tmandry?), this PR will make source locations emitted here respect the [--remap-path-prefix](https://doc.rust-lang.org/rustc/command-line-arguments.html#--remap-path-prefix-remap-source-names-in-output) compiler option. Please let us know if there is a reason not to do this.

(Note: if the compiler is invoked without `--remap-path-prefix` then the behavior does not change)

File: compiler/rustc_save_analysis/src/dump_visitor.rs [hunk 21]
```diff
@@ -1112,7 +1112,7 @@ impl<'tcx> DumpVisitor<'tcx> {
                 name: String::new(),
                 qualname,
                 span,
-                value: filename.to_string(),
+                value: filename.prefer_remapped().to_string(),
```
Comment (michaelwoerister) [inline compiler/rustc_save_analysis/src/dump_visitor.rs:1115]: @rust-lang/compiler-contributors & @rust-lang/compiler, who would be the best person to review changes to save-analysis? This PR forces code to explicitly choose if a given use of a source filename should respect the [--remap-path-prefix](https://doc.rust-lang.org/rustc/command-line-arguments.html#--remap-path-prefix-remap-source-names-in-output) commandline option or not. It is unclear to me what save-analysis should do in this case.

File: src/librustdoc/doctest.rs [hunk 22]
```diff
@@ -840,7 +840,7 @@ impl Collector {
         if !item_path.is_empty() {
             item_path.push(' ');
         }
-        format!("{} - {}(line {})", filename, item_path, line)
+        format!("{} - {}(line {})", filename.prefer_local(), item_path, line)
```
Comment (michaelwoerister) [inline src/librustdoc/doctest.rs:843]: @jyn514, would you be so kind and have another look if all the rustdoc changes seem OK to you?

**Review by michaelwoerister — COMMENTED** [review]
I noticed that `SourceMap::span_to_string` does not allow one to choose whether the remapped or the local version of a path should be used -- but since it defaults to the safe option (i.e. remapped) I think it is fine to leave it that way for now. 

I've posted the remaining questions below on how to handle specific cases.

File: compiler/rustc_span/src/source_map.rs [hunk 23]
```diff
@@ -380,10 +340,10 @@ impl SourceMap {
             nc.pos = nc.pos + start_pos;
         }
 
+        let (filename, _) = self.path_mapping.map_filename_prefix(&filename);
```
[the remark this answers is not in the document]
Comment (cbeuw) [reply compiler/rustc_span/src/source_map.rs]: I think this line is still necessary because the imported file might not have been remapped (a `LocalPath`), in that case we do need to remap it

File: compiler/rustc_span/src/source_map.rs [hunk 24]
```diff
@@ -1046,9 +999,20 @@ impl FilePathMapping {
...
+                        RealFileName::Remapped {
+                            local_path: Some(local_path.clone()),
+                            virtual_name: mapped_path,
+                        }
+                    } else {
+                        realfile.clone()
+                    };
+                    (FileName::Real(realfile), mapped)
+                } else {
+                    (file.clone(), false)
```
[the remark this answers is not in the document]
Comment (cbeuw) [reply compiler/rustc_span/src/source_map.rs]: This is where double remapping is prevented, otherwise we need to check the variant before calling it

File: compiler/rustc_save_analysis/src/dump_visitor.rs (hunk 21 above)
Comment (jyn514) [reply compiler/rustc_save_analysis/src/dump_visitor.rs:1115]: @Xanewok is a good reviewer I tihnk.

**Comment by michaelwoerister** [comment]
@cbeuw The `issue-73167-remap-std.rs` test case is actually outdated now that we don't allow double remapping.

**Comment by cbeuw** [comment]
@michaelwoerister On CI it acutally isn't doing double remapping because the CI's config.toml has `remap-debuginfo = false`, hence all sysroot crates persists as `LocalPath` and we remap it in `new_imported_source_file()`. 

I'm not sure if there's a good way of testing the behaviour of a distribution compiler importing a sysroot crate because we can't recompile everything just with `remap-debuginfo = true`

**Review by jyn514 — COMMENTED** [review]
I don't understand when this would ever have an effect on rustdoc. Rustdoc doesn't accept remap-path-prefix:

```
$ rustdoc --test src/lib.rs --remap-path-prefix=/home/joshua/src/rust/test-rustdoc=src
error: Unrecognized option: 'remap-path-prefix'
```

File: src/librustdoc/doctest.rs (hunk 22 above)
Comment (cbeuw) [reply src/librustdoc/doctest.rs:843]: Below in `add_test()`, it tries to figure out a `path: PathBuf` using the return value of `get_filename()`. It becomes `doctest.rs` for anything other than a `Real` filename. If `get_filename()` were to return a PathBuf directly, should I make it `doctest.rs` too if it isn't a real file? That might change the behaviour here because it could be a `Custom("input")` (formatted as `<input>`)

**Comment by michaelwoerister** [comment]
> I don't understand when this would ever have an effect on rustdoc. Rustdoc doesn't accept remap-path-prefix.

@jyn514 Are there potential privacy concerns around rustdoc? E.g. leaking absolute file paths (which could reveal usernames) into generated artifacts? Then the path-remapping infrastructure is probably a good basis for dealing with them. But I don't know enough about rustdoc to know if this is a problem or not (a good starting point would be doing a full text search for your username in any rustdoc output that would be made publicly available).

Does rustdoc ever emit file paths imported from the standard library? In that case it can encounter file names with both versions (local and remapped) available and will have to make a decision on which one to use. This might be different for each individual usage site.

**Comment by michaelwoerister** [comment]
@cbeuw We can introduce a `-Z` commandline option for simulating changes to the availability of `rust-src` for testing purposes (I think  @Aaron1011 already had this implemented somewhere).

**Comment by jyn514** [comment]
@michaelwoerister it depends if you count docs as final artifacts or not - I agree it probably makes sense to hide full paths there. But that's not my point, my point is that I don't understand *when* this could ever happen, since rustdoc doesn't accept `--remap-path-prefix` currently. Does it inherit it from metadata or something?

cc @rust-lang/rustdoc

File: compiler/rustc_mir/src/interpret/eval_context.rs (hunk 19 above)
Comment (RalfJung) [reply compiler/rustc_mir/src/interpret/eval_context.rs:272]: I think this method is only used to format stack traces for error messages. What do we do for other rustc diagnostics?

Comment (cbeuw) [reply compiler/rustc_mir/src/interpret/eval_context.rs:272]: Other places are likely using `SourceMap::span_to_string()`. https://github.com/rust-lang/rust/blob/23f769ec7776521a5cc393219d1558bb3d83f686/compiler/rustc_span/src/source_map.rs#L409-L424

Comment (RalfJung) [reply compiler/rustc_mir/src/interpret/eval_context.rs:272]: It is possible we didn't use that since we only wanted the `lo` to be printed...
but anyway if that uses `prefer_remapped`, this should do the same. Maybe add a comment that this should be kept consistent with `SourceMap::span_to_string`=

Comment (cbeuw) [reply compiler/rustc_mir/src/interpret/eval_context.rs:272]: If it's only for diagnostics and will not end up in binary it probably should use `prefer_local()`

@michaelwoerister Do you think we should add a `prefer_local` argument to `span_to_string` as well?

File: compiler/rustc_save_analysis/src/dump_visitor.rs (hunk 21 above)
Comment (Xanewok) [reply compiler/rustc_save_analysis/src/dump_visitor.rs:1115]: This looks correct, we want to have the remapped version here. Thanks for the ping.

File: compiler/rustc_mir/src/interpret/eval_context.rs (hunk 19 above)
Comment (cbeuw) [reply compiler/rustc_mir/src/interpret/eval_context.rs:272]: I changed this to `prefer_local()` because we want that in diagnostics. It broke a lot of tests with `remap-debuginfo = true` otherwise

File: compiler/rustc_span/src/source_map.rs [hunk 25]
```diff
@@ -453,7 +406,9 @@ impl SourceMap {
         }
     }
 
-    pub fn span_to_string(&self, sp: Span) -> String {
+    /// Format the span location to be printed in diagnostics. Must not be included
+    /// in build artifacts as it may leak local file paths.
+    pub fn span_to_diagnostic_string(&self, sp: Span) -> String {
```
Comment (cbeuw) [inline compiler/rustc_span/src/source_map.rs:411]: I checked everywhere this is used and I'm fairly confident that it's only ever used for debug/diagnositc prints. So I renamed it and used `prefer_local()`

File: compiler/rustc_mir/src/transform/coverage/mod.rs (hunk 20 above)
Comment (michaelwoerister) [reply compiler/rustc_mir/src/transform/coverage/mod.rs:293]: Thank you, @richkadel!

File: compiler/rustc_save_analysis/src/dump_visitor.rs (hunk 21 above)
Comment (michaelwoerister) [reply compiler/rustc_save_analysis/src/dump_visitor.rs:1115]: Thanks, @Xanewok!

**Comment by michaelwoerister** [comment]
@jyn514 Yes, it looks like `rustdoc` will currently always have an empty `rustc_session::options::Options::remap_path_prefix` map, so all file names from the local crate with be local file-system paths. As far as I can tell this has the following implications:
- It won't matter if you use `prefer_local()` or `prefer_remapped()` -- the outcome is the same. For now I personally would recommend using the local path since that should match the assumptions the original code was written under. 
- Emitting absolute file paths into generated docs isn't a good idea from a privacy point of view. I don't know if rustdoc actually does that at the moment. If it is only emitting relative paths, it should be fine. However, if this is something that needs to be addressed in future then the path-remapping infrastructure might help you accomplish that. Feel free to reach out to me in that case.

In any case, we'll be at the beginning of a new cycle by the time this PR gets merged, so there should be enough time to fix any potential regressions it introduces.

File: compiler/rustc_mir/src/interpret/eval_context.rs (hunk 19 above)
Comment (michaelwoerister) [reply compiler/rustc_mir/src/interpret/eval_context.rs:272]: If this is used only for error messages then `prefer_local()` is the way to go. Thanks, @RalfJung!

File: compiler/rustc_span/src/source_map.rs (hunk 25 above)
Comment (michaelwoerister) [reply compiler/rustc_span/src/source_map.rs:411]: OK, looks good to me!

**Comment by cbeuw** [comment]
So the `$SRC_DIR_EMBEDDED` idea doesn't work because if the src dir hasn't been remapped during bootstrapping, it'll just be normalised to `$SRC_DIR` and fails to check. There's a much simpler solution to just normalise remapped sysroot also to `$SRC_DIR`

File: src/test/codegen/remap_path_prefix/issue-73167-remap-std.rs [hunk 26]
```diff
@@ -0,0 +1,15 @@
+// ignore-windows
+
+// compile-flags: -g  -C no-prepopulate-passes -Z remap-rust-src-base=/rustc
```
Comment (michaelwoerister) [inline src/test/codegen/remap_path_prefix/issue-73167-remap-std.rs:3]: Do you need to add a pseudo-SHA value here in order for it to conform to the same regex as regular remapped paths? E.g. `-Z remap-rust-src-base=/rustc/xyz`.

Comment (cbeuw) [reply src/test/codegen/remap_path_prefix/issue-73167-remap-std.rs]: Added that. I don't have time to run the tests locally atm so let's see if the CI works

File: compiler/rustc_session/src/options.rs [hunk 27]
```diff
@@ -1161,6 +1161,9 @@ options! {DebuggingOptions, DebuggingSetter, basic_debugging_options,
         "whether ELF relocations can be relaxed"),
     relro_level: Option<RelroLevel> = (None, parse_relro_level, [TRACKED],
         "choose which RELRO level to use"),
+    remap_rust_src_base: Option<PathBuf> = (None, parse_opt_pathbuf, [TRACKED_NO_CRATE_HASH],
```
Comment (michaelwoerister) [inline compiler/rustc_session/src/options.rs:1164]: Can you rename this to `simulate_remapped_rust_src_base` and mention in the description that this option is meant to be used only for testing purposes. Also, I would make it `[TRACKED]` to be on the safe side.

**Comment by michaelwoerister** [comment]
OK, this looks pretty good now. Let's see if there are any performance changes.

@bors try @rust-timer queue

**Comment by jyn514** [comment]
Perf looks like noise.

**Comment by michaelwoerister** [comment]
Indeed it does. No unpleasant surprises there.

**Comment by michaelwoerister** [comment]
@cbeuw Would you mind squashing the commit history to clean things up a bit?

**Comment by cbeuw** [comment]
@michaelwoerister of course, will do!

**Comment by jyn514** [comment]
> Emitting absolute file paths into generated docs isn't a good idea from a privacy point of view. I don't know if rustdoc actually does that at the moment. If it is only emitting relative paths, it should be fine. However, if this is something that needs to be addressed in future then the path-remapping infrastructure might help you accomplish that. Feel free to reach out to me in that case.

It is at least for generated docs: https://github.com/rust-lang/rust/issues/18370

**Comment by cbeuw** [comment]
@michaelwoerister let me know if you want the commits to be squashed further

**Comment by michaelwoerister** [comment]
Looks good to me, @cbeuw! Alright, let's try to get this merged.

@bors r+

File: compiler/rustc_span/src/source_map.rs (hunk 25 above)
Comment (cbeuw) [inline compiler/rustc_span/src/source_map.rs:411]: >I checked everywhere this is used and I'm fairly confident that it's only ever used for debug/diagnositc prints. 

...and that's wrong. It seems like, at least in `rustc_mir::util::pretty` they all seem to use it for comments emitted for `InstrumentCoverage`

**Review by cbeuw — COMMENTED** [review]
I went over everywhere using `span_to_string` again and checked if we should use the local path or remapped path.

In `rustc_mir`, they are all used to produce strings that will end up in emitted MIR (other than immediately within `debug!`). The remapped path should be used in this case.

In `rustc_middle::ty::print`, the produced string may end up in both MIRs and compiler diagnostics (for types whose "name" may include the source file name like closures). Although we would prefer to show the local path to users, it seems more necessary to protect the reproducibility of emitted MIRs, hence the remapped path should be used.

Everywhere else, `span_to_string` are used for compiler debug/panic messages. Keeping them as local path is fine,

File: compiler/rustc_middle/src/ty/print/pretty.rs [hunk 28]
```diff
@@ -667,7 +667,10 @@ pub trait PrettyPrinter<'tcx>:
                     if let Some(did) = did.as_local() {
                         let hir_id = self.tcx().hir().local_def_id_to_hir_id(did);
                         let span = self.tcx().hir().span(hir_id);
-                        p!(write("@{}", self.tcx().sess.source_map().span_to_string(span)));
+                        p!(write(
+                            "@{}",
+                            self.tcx().sess.source_map().span_to_diagnostic_string(span)
+                        ));
```
[the remark this answers is not in the document]
Comment (michaelwoerister) [reply compiler/rustc_middle/src/ty/print/pretty.rs:675]: I agree that the remapped version is the safe option. Let's use that for now. If someone really needs local paths here then the pretty printer can be parameterized.

File: compiler/rustc_mir/src/borrow_check/region_infer/dump_mir.rs [hunk 29]
```diff
@@ -76,7 +76,9 @@ impl<'tcx> RegionInferenceContext<'tcx> {
         for constraint in &constraints {
             let OutlivesConstraint { sup, sub, locations, category } = constraint;
             let (name, arg) = match locations {
-                Locations::All(span) => ("All", tcx.sess.source_map().span_to_string(*span)),
+                Locations::All(span) => {
+                    ("All", tcx.sess.source_map().span_to_diagnostic_string(*span))
+                }
```
[the remark this answers is not in the document]
Comment (michaelwoerister) [reply compiler/rustc_mir/src/borrow_check/region_infer/dump_mir.rs:81]: Seems fine.

**Comment by michaelwoerister** [comment]
OK, let's give it another try: @bors r+

Also, let me try to spell out the implications of this PR in that state we have arrived at now:
- The PR fixes #73167, that is, one can now again prevent local file system paths from leaking into the compiler's output artifacts by using the `--remap-path-prefix` option.
- Diagnostic output will still prefer using the local file system path if it is available, preserving improved diagnostic quality for things inlined from libstd (as introduced by #70642). 
- However, there are some cases (around pretty-printing) the result of which is used in both a diagnostic context and an "embedded" context. This PR opts to emit the remapped paths in these cases because that is the safe option regarding reproducible builds and privacy. The downside of this approach is that some diagnostic messages might display a mix of actual and remapped paths if path remapping is enabled. Should this turn out to be a problem, it can be fixed by parameterizing the pretty-printing code with an option that allows to choose the right variant depending on the context.
- A side-effect of this fix is that debuginfo will contain remapped paths for libstd code, even when the `rust-src` component is available. As a consequence one will not be able to step through libstd code in the debugger (unless one uses a locally built compiler). I suspect that part of a fix for #40552 will restore this libstd stepping for debug builds while defaulting to the privacy preserving option for release builds. 

cc @rust-lang/compiler-contributors

**Comment by bjorn3** [comment]
> As a consequence one will not be able to step through libstd code in the debugger (unless one uses a locally built compiler).

Gdb supports `set pathname-substitutions` and lldb supports `settings set target.source-map`. Rust-analyzer can automatically set it using `"rust-analyzer.debug.sourceFileMap": "auto"` when running the debugger from vscode.

**Comment by michaelwoerister** [comment]
Thank you for all the hard work you have been putting into this, @cbeuw!
