### PR TITLE
Don't declare test_variadic_fnptr with two conflicting signatures

### LINKED ISSUE #66690: Test variadic fnptr uses incompatible definition and declaration
https://github.com/rust-lang/rust/blob/e41ced3f8d8e2f3f377ef931458e612d5f3d1f3f/src/libcore/tests/ptr.rs#L253-L269

This causes a crash when trying to test libcore with cg_clif, as Cranelift doesn't allow incompatible definitions of the same function. While this currently works for cg_llvm, according to https://github.com/rust-lang/unsafe-code-guidelines/issues/198 it is likely to become forbidden with cg_llvm too.

### PR DESCRIPTION
**Pull request by bjorn3**
It is UB for LLVM and results in a compile error for Cranelift.

cc https://github.com/bjorn3/rustc_codegen_cranelift/issues/806
Fixes https://github.com/rust-lang/rust/issues/66690

### CODE REVIEW

File: library/core/tests/ptr.rs [hunk 1]
```diff
@@ -289,16 +289,17 @@ fn test_const_nonnull_new() {
...
+#[cfg(any(unix, windows))] // printf may not be available on other platforms
+#[allow(deprecated)] // For SipHasher
 pub fn test_variadic_fnptr() {
     use core::hash::{Hash, SipHasher};
     extern "C" {
-        fn test_variadic_fnptr(_: u64, ...) -> f64;
+        // This needs to use the correct function signature even though it isn't called as some
+        // codegen backends make it UB to declare a function with multiple conflicting signatures
+        // (like LLVM) while others straight up return an error (like Cranelift).
+        fn printf(_: *const i8, ...) -> i32;
```
Comment (dtolnay) [inline library/core/tests/ptr.rs:300]:
```suggestion
        fn printf(_: *const c_char, ...) -> c_int;
```

There are some `cfg(unix)` targets for which `char` is not signed. For example powerpc, riscv64 according to https://github.com/rust-lang/rust/blob/1bfe40d11c3630254504fb73eeccfca28d50df52/library/core/src/ffi/mod.rs.

**Review by dtolnay — CHANGES_REQUESTED** [review]

File: library/core/tests/ptr.rs (hunk 1 above)
Comment (bjorn3) [reply library/core/tests/ptr.rs]: Didn't know the `ffi` module is available in libcore. Fixed.

**Review by dtolnay — APPROVED** [review]
Thanks!

**Comment by matthiaskrgr** [comment]
Looks like this causes linking failures on windows:
https://github.com/rust-lang/rust/pull/95123#issuecomment-1073192727
@bors r- rollup=iffy

**Comment by bjorn3** [comment]
I hoped that printf would be available on msvc. I think I will need to look for another symbol that is.

**Comment by bjorn3** [comment]
According to https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/printf-printf-l-wprintf-wprintf-l?view=msvc-170 printf should be available. @dtolnay do you have any clue what the issue could be? And if not would it be fine to disable the test on windows?

**Comment by bjorn3** [comment]
(rebased, but haven't fixed it yet)

**Review by dtolnay — CHANGES_REQUESTED** [review]
Don't know. I'd just exclude this test on Windows too.

**Comment by bjorn3** [comment]
Done

**Review by dtolnay — APPROVED** [review]
