### PR TITLE
Fix windows-gnu host cross-compilation

### LINKED ISSUE #64218: LLVM doesn't build  on the first try when cross compilling to windows-gnu host
Running `./x.py build --host x86_64-pc-windows-gnu --target x86_64-pc-windows-gnu` from Linux will fail on building LLVM for Windows (so it's 2nd LLVM build) because somehow LLVM_ON_UNIX is defined:
```
/home/mateusz/Projects/rust/rust/src/llvm-project/llvm/include/llvm/Support/FileSystem.h:164:3: error: ‘uid_t’ does not name a type; did you mean ‘pid_t’?
  164 |   uid_t fs_st_uid = 0;
      |   ^~~~~
      |   pid_t
```

Magic happens when running the same command second time without cleaning build dir or changing anything. It will finish LLVM build and install the files.

Rust build will fail on `librustc_codegen_llvm` because of missing `shell32` but this could be unrelated (although [CMake should link it](https://github.com/llvm/llvm-project/blob/6d6babf7457c8128072cb23f079123fa76cafc5b/llvm/lib/Support/CMakeLists.txt#L8)).

### PR DESCRIPTION
**Pull request by mati865**
Fixes https://github.com/rust-lang/rust/issues/64218

Also turns out it's faster to run Linux virtual machine on Windows and cross-compile `./x.py dist` than doing it on Windows directly...

### CODE REVIEW

**Comment by lcnr** [comment]
Not something I know much about.

r? @Mark-Simulacrum maybe

File: src/bootstrap/dist.rs [hunk 1]
```diff
@@ -226,7 +226,9 @@ fn make_win_dist(
         let idx = line.find(':').unwrap();
         let key = &line[..idx];
         let trim_chars: &[_] = &[' ', '='];
-        let value = line[(idx + 1)..].trim_start_matches(trim_chars).split(';').map(PathBuf::from);
+        let separator = if cfg!(windows) { ";" } else { ":" };
+        let value =
+            line[(idx + 1)..].trim_start_matches(trim_chars).split(separator).map(PathBuf::from);
```
Comment (Mark-Simulacrum) [inline src/bootstrap/dist.rs:231]: We should use [`std::env::split_paths`](https://doc.rust-lang.org/nightly/std/env/fn.split_paths.html) here instead, I think?

Comment (mati865) [reply src/bootstrap/dist.rs:231]: I knew there is such function but searched at the wrong place...

Comment (mati865) [reply src/bootstrap/dist.rs]: Thanks, tested on native Windows and cross compiled from Linux.

File: src/bootstrap/dist.rs [hunk 2]
```diff
@@ -226,7 +226,8 @@ fn make_win_dist(
         let idx = line.find(':').unwrap();
         let key = &line[..idx];
         let trim_chars: &[_] = &[' ', '='];
-        let value = line[(idx + 1)..].trim_start_matches(trim_chars).split(';').map(PathBuf::from);
+        let value =
+            env::split_paths(line[(idx + 1)..].trim_start_matches(trim_chars)).map(PathBuf::from);
```
Comment (Mark-Simulacrum) [inline src/bootstrap/dist.rs:230]: split_paths already returns `impl Iterator<Item = PathBuf>` so the map isn't necessary.

**Review by Mark-Simulacrum — COMMENTED** [review]
r=me with nit fixed

File: src/bootstrap/dist.rs (hunk 2 above)
Comment (mati865) [reply src/bootstrap/dist.rs]: Fixed.
