### PR TITLE
Don't try to evaluate const blocks during constant promotion

### LINKED ISSUE #150464: regression: "cycle detected when borrow-checking" in `offset_of!`
```
[INFO] [stdout] error[E0391]: cycle detected when borrow-checking `firmware::operation::implement::stm::gain::tests::test_phase_half`
[INFO] [stdout]    --> src/firmware/operation/implement/stm/gain.rs:649:5
[INFO] [stdout]     |
[INFO] [stdout] 649 |     fn test_phase_half() {
[INFO] [stdout]     |     ^^^^^^^^^^^^^^^^^^^^
[INFO] [stdout]     |
[INFO] [stdout] note: ...which requires promoting constants in MIR for `firmware::operation::implement::stm::gain::tests::test_phase_half`...
[INFO] [stdout]    --> src/firmware/operation/implement/stm/gain.rs:649:5
[INFO] [stdout]     |
[INFO] [stdout] 649 |     fn test_phase_half() {
[INFO] [stdout]     |     ^^^^^^^^^^^^^^^^^^^^
[INFO] [stdout] note: ...which requires simplifying constant for the type system `firmware::operation::implement::stm::gain::tests::test_phase_half::{constant#0}`...
[INFO] [stdout]    --> src/firmware/operation/implement/stm/gain.rs:704:20
[INFO] [stdout]     |
[INFO] [stdout] 704 |                 tx[offset_of!(GainSTMHead, flag)] & 0x3F
[INFO] [stdout]     |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[INFO] [stdout] note: ...which requires const-evaluating + checking `firmware::operation::implement::stm::gain::tests::test_phase_half::{constant#0}`...
[INFO] [stdout]    --> src/firmware/operation/implement/stm/gain.rs:704:20
[INFO] [stdout]     |
[INFO] [stdout] 704 |                 tx[offset_of!(GainSTMHead, flag)] & 0x3F
[INFO] [stdout]     |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[INFO] [stdout] note: ...which requires caching mir of `firmware::operation::implement::stm::gain::tests::test_phase_half::{constant#0}` for CTFE...
[INFO] [stdout]    --> src/firmware/operation/implement/stm/gain.rs:704:20
[INFO] [stdout]     |
[INFO] [stdout] 704 |                 tx[offset_of!(GainSTMHead, flag)] & 0x3F
[INFO] [stdout]     |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[INFO] [stdout] note: ...which requires elaborating drops for `firmware::operation::implement::stm::gain::tests::test_phase_half::{constant#0}`...
[INFO] [stdout]    --> src/firmware/operation/implement/stm/gain.rs:704:20
[INFO] [stdout]     |
[INFO] [stdout] 704 |                 tx[offset_of!(GainSTMHead, flag)] & 0x3F
[INFO] [stdout]     |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[INFO] [stdout]     = note: ...which again requires borrow-checking `firmware::operation::implement::stm::gain::tests::test_phase_half`, completing the cycle
[INFO] [stdout]     = note: cycle used when running analysis passes on crate `autd3_driver`
[INFO] [stdout]     = note: see https://rustc-dev-guide.rust-lang.org/overview.html#queries and https://rustc-dev-guide.rust-lang.org/query.html for more information
[INFO] [stdout]     = note: this error originates in the macro `offset_of` (in Nightly builds, run with -Z macro-backtrace for more info)
```

https://crater-reports.s3.amazonaws.com/beta-1.93-3/beta-2025-12-09/reg/autd3-driver-38.0.1/log.txt

@rustbot modify labels: +regression-from-stable-to-beta -regression-untriaged

### PR DESCRIPTION
**Pull request by dianne**
As of https://github.com/rust-lang/rust/pull/138499, trying to evaluate a const block in anything depended on by borrow-checking will result in a query cycle. Since that could happen in constant promotion, this PR adds a check for const blocks there to stop them from being evaluated.

Admittedly, this is a hack. See https://github.com/rust-lang/rust/issues/124328 for discussion of a more principled fix: removing cases like this from constant promotion altogether. To simplify the conditions under which promotion can occur, we probably shouldn't be implicitly promoting division or array indexing at all if possible. That would likely require a FCW and migration period, so I figure we may as well patch up the cycle now and simplify later.

Fixes rust-lang/rust#150464

I'll also lang-nominate this for visibility. I'm not sure there's much to discuss about this PR specifically, but it does represent a change in semantics. In Rust 1.87, the code below compiled. In Rust 1.88, it became a query cycle error. After this PR, it fails to borrow-check because the temporaries can no longer be promoted.

```rust
let (x, y, z);
// We only promote array indexing if the index is known to be in-bounds.
x = &([0][const { 0 }] & 0);
// We only promote integer division if the divisor is known not to be zero.
y = &(1 / const { 1 });
// Furthermore, if the divisor is `-1`, we only promote if the dividend is
// known not to be `int::MIN`.
z = &(const { 1 } / -1);
// The borrowed temporaries can't be promoted, so they were dropped at the ends
// of their respective statements.
(x, y, z);
```

### CODE REVIEW

File: compiler/rustc_mir_transform/src/promote_consts.rs [hunk 1]
```diff
@@ -683,6 +686,15 @@ impl<'tcx> Validator<'_, 'tcx> {
         // This passed all checks, so let's accept.
         Ok(())
     }
+
+    /// Can we try to evaluate a given constant at this point in compilation? Attempting to evaluate
+    /// a const block before borrow-checking will result in a query cycle (#150464).
+    fn is_evaluable(&self, constant: Const<'tcx>) -> bool {
+        match constant {
+            Const::Ty(..) | Const::Val(..) => true,
+            Const::Unevaluated(uc, _) => self.tcx.def_kind(uc.def) != DefKind::InlineConst,
```
Comment (BoxyUwU) [inline compiler/rustc_mir_transform/src/promote_consts.rs]:
```suggestion
            // `Const::Ty` is always a `ConstKind::Param` right now and that can never be turned
            // into a mir value for promotion
            // FIXME(mgca): do we want uses of type_const to be normalized during promotion?
            Const::Ty(..) => false,
            Const::Val(..) => true,
            // Other kinds of unevaluated's should be able to cause query cycles too, but
            // inline consts *always* cause query cycles
            Const::Unevaluated(uc, _) => self.tcx.def_kind(uc.def) != DefKind::InlineConst,
```
On stable a `Const::Ty` is always a `ConstKind::Param` which you can't do anything meaningful with.

Am I correct in assuming non inline consts can also cause a query cycle here? The following example seems to demonstrate this:
```rust
const fn foo() -> &'static u32 {
    &(10 / <()>::ASSOC)
}

trait Trait {
    const ASSOC: u32;
}

impl Trait for () {
    const ASSOC: u32 = *foo();
}
```
I think this is the kind of cycle we're talking about here?

File: tests/ui/inline-const/dont-eval-const-block-during-promotion.rs [hunk 2]
```diff
@@ -0,0 +1,34 @@
...
+    //~^ ERROR: temporary value dropped while borrowed
+    y = &(1 / const { 1 });
+    //~^ ERROR: temporary value dropped while borrowed
+    z = &(const { 1 } / -1);
+    //~^ ERROR: temporary value dropped while borrowed
+    (x, y, z);
+
+    // At the time #150464 was reported, the index as evaluated before checking whether the indexed
+    // expression and index expression could themselves be promoted. This can't be promoted since
+    // it references a local, but it still resulted in a query cycle.
```
Comment (BoxyUwU) [inline tests/ui/inline-const/dont-eval-const-block-during-promotion.rs]: Does that mean this PR makes that code go from query cycle -> pass? I feel like it'd be nice to be more clear/explicit about which specific code is fixed by this PR. Afaict any code which doesn't actually need promotion to take place but had a const block there will now pass whereas was previously broken by #138499?

File: compiler/rustc_mir_transform/src/promote_consts.rs (hunk 1 above)
Comment (dianne) [reply compiler/rustc_mir_transform/src/promote_consts.rs]: The cycle there has the same shape, but I find it conceptually a bit different, since it arises from a cyclic dependency in user code: by definition, CTFE of `<()>::ASSOC` requires CTFE of `foo`, which requires CTFE of `<()>::ASSOC`. Even if we weren't trying to evaluate `<()>::ASSOC` during constant promotion, it and `foo` are both unusable. Since the cycle is unavoidable, I don't think we need to catch it in constant promotion.

The cycle for inline consts is due to how they're borrow-checked along with their typeck root. If borrow-checking the containing body requires evaluating the constant, this gives rise to a cycle, since evaluating the constant requires borrow-checking it, which again means borrow-checking the containing body. However, using the inline const is perfectly fine as long as we don't evaluate it until after borrow-checking.

I'll tack a note onto to the "other kinds of unevaluated's" comment to clarify why the inline const cycle in particular needs to be avoided.

**Comment by jackh726** [comment]
> I'll also lang-nominate this for visibility. I'm not sure there's much to discuss about this PR specifically, but it does represent a change in semantics. In Rust 1.87, the code below compiled. In Rust 1.88, it became a query cycle error. After this PR, it fails to borrow-check because the temporaries can no longer be promoted.
> 
> ```rust
> let (x, y, z);
> // We only promote array indexing if the index is known to be in-bounds.
> x = &([0][const { 0 }] & 0);
> // We only promote integer division if the divisor is known not to be zero.
> y = &(1 / const { 1 });
> // Furthermore, if the divisor is `-1`, we only promote if the dividend is
> // known not to be `int::MIN`.
> z = &(const { 1 } / -1);
> // The borrowed temporaries can't be promoted, so they were dropped at the ends
> // of their respective statements.
> (x, y, z);
> ```

This feels not-correct. I would *expect* that a const block would be "transparent" to static promotion - I would expect that all of these would continue to compile. Changing this to *not* compiling just to fix an implementation-detail (query cycle) seems wrong.

**Comment by dianne** [comment]
A more targeted alternative to this PR could be to reorder the logic for checking if array indexing can be used in promoted constants, so that it recursively checks the array and index before evaluating the index to see if it's in-bounds. That'd fix the regression reported in #150464 (since it'd bail when finding that the array can't be used in a promoted constant) but would leave in the query cycles for cases where whether we promote something depends on CTFE of an inline constant (like `&([0][const { 0 }] & 0)`)

File: compiler/rustc_mir_transform/src/promote_consts.rs (hunk 1 above)
Comment (dianne) [reply compiler/rustc_mir_transform/src/promote_consts.rs]: Added the suggested change with further elaboration in the comment: [(diff)](https://github.com/rust-lang/rust/compare/304c5af824f5f1b4c212d1efc33a516a5ef52c3e..d758793cc43a73abf56a5ca394562f92188a4e01#diff-b1977131774f8038e30af6742b2eff299cc93e24275e676c4e70257e49aa8c8f)

File: tests/ui/inline-const/dont-eval-const-block-during-promotion.rs (hunk 2 above)
Comment (dianne) [reply tests/ui/inline-const/dont-eval-const-block-during-promotion.rs]: I think that's right, yeah. I've made the wording more explicit and added some additional examples to hopefully make the tests flow better conceptually (and catch if changes to constant promotion would make it become out-of-date): [(diff)](https://github.com/rust-lang/rust/compare/304c5af824f5f1b4c212d1efc33a516a5ef52c3e..d758793cc43a73abf56a5ca394562f92188a4e01#diff-ecf7b8759a3e184d36f65dc87d33663e3aaaed47e86c28ef419e8891d0f0dc64)

**Comment by scottmcm** [comment]
> Also to be clear, there is a clear migration path for affected code: explicit promotion, expressed as `const { &(1 / 1) }`.

Clarifying question: would `&const { 1 / 1 }` also continue to work here?  Or does the `&` *have* to be inside?

**Comment by traviscross** [comment]
We talked about this in the lang call.  Thanks @dianne for joining us to talk about it.  This sounds right.

@rfcbot fcp merge lang

**Comment by traviscross** [comment]
The idea, as I've given to understand, is that query cycles were holding space for what we'd otherwise be breaking here.  So we're expecting this to only allow new things to compile.  E.g., this will work now:

```rust
fn main() {
    let y = &(1 / const { 1 });
}
```

As @dianne says:

> As long as the referent of `y` isn't required to live past the current block, this works. Instead of being promoted, this results in a lifetime-extended temporary.

To err on the safe side, let's check this hypothesis that query cycles were holding space for us in all cases with a crater run.

@bors try

**Comment by tmandry** [comment]
@rfcbot reviewed

**Comment by Mark-Simulacrum** [comment]
Copying re:backports from T-compiler meeting:

> We're not gonna beta backport something that hasn't landed on nightly just before release so yeah. I think we can ignore this for now. We may want to beta backport in the next release cycle (so we should leave it nominated I suppose)

[#t-compiler/meetings > &#91;weekly&#93; 2026-01-15 @ 💬](https://rust-lang.zulipchat.com/#narrow/channel/238009-t-compiler.2Fmeetings/topic/.5Bweekly.5D.202026-01-15/near/568238822)

File: compiler/rustc_mir_transform/src/promote_consts.rs [hunk 3]
```diff
@@ -329,6 +330,7 @@ impl<'tcx> Validator<'_, 'tcx> {
                 if let TempState::Defined { location: loc, .. } = self.temps[local]
                     && let Left(statement) =  self.body.stmt_at(loc)
                     && let Some((_, Rvalue::Use(Operand::Constant(c)))) = statement.kind.as_assign()
+                    && self.is_evaluable(c.const_)
```
Comment (lcnr) [inline compiler/rustc_mir_transform/src/promote_consts.rs]:
```suggestion
                    && self.should_evaluate_for_promotion_checks(c.const_)
```
maybe. I feel like `is_evaluatable` is somewhat confusing of a name

**Review by lcnr — COMMENTED** [review]
one nit, otherwise r=me

*[View changes since this review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/rust/150557/50d59402bfb82a7fcdf542ed418affe425ff867e..d758793cc43a73abf56a5ca394562f92188a4e01)*

File: compiler/rustc_mir_transform/src/promote_consts.rs (hunk 3 above)
Comment (dianne) [reply compiler/rustc_mir_transform/src/promote_consts.rs]: `should_evaluate_for_promotion_checks` does feel clearer, yeah; I've made that change. It is a bit unfortunate for ease of scanning to go from
```rust
Operand::Constant(c) if self.is_evaluable(c.const_) => {
```
to
```rust
Operand::Constant(c)
    if self.should_evaluate_for_promotion_checks(
        c.const_,
    ) =>
{
```
but the nested/sequential matches that's a part of could maybe benefit from some restructuring anyway, which could remove some of the indentation. I'll save that potential cleanup for another PR

File: tests/ui/inline-const/dont-eval-const-block-during-promotion.rs [hunk 4]
```diff
@@ -0,0 +1,60 @@
+//! Test for #150464: as of #138499, trying to evaluate const blocks during constant promotion will
+//! result in a query cycle, so we shouldn't do it. Evaluation can happen when trying to promote
+//! integer division and array indexing, where it's necessary for the operation to succeed to be
+//! able to use it in a promoted constant.
+
+use std::mem::offset_of;
+
+struct Thing(i32);
+
+fn main() {
```
Comment (lcnr) [inline tests/ui/inline-const/dont-eval-const-block-during-promotion.rs:12]: one more thought, this test currently has some statements which should compile and others which should error, can you split them into 2 revisions or tests?

**Review by lcnr — COMMENTED** [review]
@bors delegate+

*[View changes since this review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/rust/150557/b3cda168c8afd5c4240a9477f6a7f54e70e2589a..ae9b9cb22519f82092174c703395b4b70d27cead)*

File: tests/ui/inline-const/dont-eval-const-block-during-promotion.rs (hunk 4 above)
Comment (dianne) [reply tests/ui/inline-const/dont-eval-const-block-during-promotion.rs:12]: opted for 2 revisions to keep the context for the tests all in one place

**Comment by apiraino** [comment]
Beta backport declined as per compiler team [on Zulip](https://rust-lang.zulipchat.com/#narrow/channel/238009-t-compiler.2Fmeetings/topic/.5Bweekly.5D.202026-01-29/near/570823285): 
> Crater triage suggests this is a pretty isolated case. I think I'd prefer to let this ride the release train in 1.95 

@rustbot label -beta-nominated
