### PR TITLE
Display better snippet for invalid char literal

### LINKED ISSUE #30033: Invalid char literal error message has an unhelpful snippet
`foo.rs`:
```rust
fn main() {
    let _ = 'ab';
}
```

```
foo.rs:2:16: 2:18 error: character literal may only contain one codepoint: ';
foo.rs:2     let _ = 'ab';
                        ^~
```

The snippet at the end of the error message is not helpful, and should probably encompass everything between the two `'`s.

### PR DESCRIPTION
**Pull request by gchp**
This is achieved by adding the scan_back method. This method looks back
through the source_text of the StringReader until it finds the target
char, returning it's offset in the source. We use this method to find
the offset of the opening single quote, and use that offset as the start
of the error.

Given this code:

``` rust
fn main() {
    let _ = 'abcd';
}
```

The compiler would give a message like:

```
error: character literal may only contain one codepoint: ';
let _ = 'abcd';
             ^~
```

With this change, the message now displays:

```
error: character literal may only contain one codepoint: 'abcd';
let _ = 'abcd';
        ^~~~~~~
```

Fixes #30033

### CODE REVIEW

**Comment by apasel422** [comment]
Ideally, the span would not include the `;` there. Also, can you add a compile-fail test for this?

**Comment by gchp** [comment]
@apasel422 ok - sure thing.

**Comment by nagisa** [comment]
To me it seems we should investigate why `start` does not contain the correct position, and if it is not possible to fix `start`, add a comment explaining why.

**Comment by gchp** [comment]
Investigating the failing test now.

@nagisa if I understand it correctly, `start` does not contain the correct position because we have already parsed past the opening single quote trying to look for a closing single quite (which in this case is not found). So I think it makes sense that `start` doesn't point to the opening single quote position?

**Comment by alexcrichton** [comment]
I agree with @nagisa that the `start` variable should indeed be the start of the character constant, and in theory we shouldn't need to scan backwards looking for the end (e.g. we just parsed it and should have the position as well).

Would it be possible to fix the span without the scan backwards function?

**Comment by gchp** [comment]
@alexcrichton sure thing. I'll dig into it and update the PR!

**Comment by nagisa** [comment]
> So I think it makes sense that start doesn't point to the opening single quote position?

You could introduce another variable earlier in the function (or rename the start which gets set to the closing apostrophe) to deal with it, I think.

**Comment by gchp** [comment]
@nagisa I did try that before I ended up with the current iteration. Even at the very beginning of the function the start variable was not in the right place. 

I might have just overlooked something though. I'll go back and try it again and see what I find. Will update here when I have something to report. 

Thanks for the feedback!

**Comment by gchp** [comment]
@nagisa & @alexcrichton - I've fixed the problem and updated the PR. See the latest commit message for details on the fix. Basically we were exiting the function too early, without checking for a closing single quote.

The latest commit makes the others which preceeded it unecessary. Should I squash them all together? Or is it ok to leave as is?

File: src/liblibc [hunk 1]
```diff
@@ -1 +1 @@
-Subproject commit 95d6a00134f284e6b889d98f4c2cb4b285950327
+Subproject commit e0c0bf439add63a6a25a25ba47e4aec9547bf9af
```
Comment (gchp) [inline src/liblibc]: This showed up when I rebased. Not sure how to make it not show up as part of this pull request...

File: src/libsyntax/parse/lexer/mod.rs [hunk 2]
```diff
@@ -1233,26 +1233,27 @@ impl<'a> StringReader<'a> {
...
                     }
+                    // lifetimes shouldn't end with a single quote
+                    // if we find one, then this is an invalid character literal
+                    if self.curr_is('\'') {
+                        panic!(self.fatal_span_verbose(
+                               // Byte offsetting here is okay because the
+                               // character before position `start` is an
+                               // ascii single quote.
+                               start - BytePos(1), self.pos,
+                               String::from("character literal may only contain one codepoint")));
```
Comment (nagisa) [inline src/libsyntax/parse/lexer/mod.rs]: Probably the better approach would be to add something along the lines of `let start_with_quote = self.last_pos;` before the `self.bump` above instead of doing manual byte arithmetic here.

Also it probably would be a good idea to move check to right after the `while ident_continue` loop, so we didn’t do all the unecessary work related to lifetimes?

File: src/test/parse-fail/lex-bad-char-literals.rs [hunk 3]
```diff
@@ -25,8 +25,7 @@ static s: &'static str =
     "\●" //~ ERROR: unknown character escape
 ;
 
-// THIS MUST BE LAST, since it kills the lexer
-
-static c: char =
-    '●  //~ ERROR: character literal may only contain one codepoint
+static invalid_c: char =
+    'nope' //~ ERROR: character literal may only contain one codepoint: 'nope'
```
Comment (nagisa) [inline src/test/parse-fail/lex-bad-char-literals.rs]: I’d like more test cases (and would prefer you didn’t remove the current one). It is fine to create more files to contain them:

* `'č`
* `'nope'`
* `'\x00\x00'`
* `'●●'`
* etc

File: src/liblibc (hunk 1 above)
Comment (nagisa) [inline src/liblibc]:
```
cd src/liblibc
git checkout 95d6a00134f284e6b889d98f4c2cb4b285950327
cd ../../
git add/commit --amend
```

is the crudest way which should work, I think.

File: src/libsyntax/parse/lexer/mod.rs (hunk 2 above)
Comment (gchp) [inline src/libsyntax/parse/lexer/mod.rs]: Yep, makes sense!

File: src/test/parse-fail/lex-bad-char-literals.rs (hunk 3 above)
Comment (gchp) [inline src/test/parse-fail/lex-bad-char-literals.rs]: Sure, will update with more tests.

File: src/libsyntax/parse/lexer/mod.rs [hunk 4]
```diff
@@ -1233,26 +1233,27 @@ impl<'a> StringReader<'a> {
...
                     return token::Lifetime(ident);
                 }
 
-                // Otherwise it is a character constant:
                 let valid = self.scan_char_or_byte(start,
                                                    c2,
                                                    // ascii_only =
                                                    false,
                                                    '\'');
-                if !self.curr_is('\'') {
```
Comment (alexcrichton) [inline src/libsyntax/parse/lexer/mod.rs]: It seems like this branch would still be necessary as the section above just deals with lifetimes (not character literals), right?

Comment (gchp) [inline src/libsyntax/parse/lexer/mod.rs]: Yeah, I think so. Looking at that now.

**Comment by gchp** [comment]
Ok, updated from comments. Let me know what other tests you'd like, if any.
Also let me know if I should squash all these commits.

Thanks!

**Comment by nagisa** [comment]
Yeah, a squash is necessary. Perhaps also a test for `'\x00\x00'`. r=me once those are done.

**Comment by gchp** [comment]
@nagisa having some issues getting the error right for `'\x00\x00`. As it stands, it comes out like: `...one codepoint: '\x00\x`. Missing the end of the second sequence. I'm not sure how to reliably fix that.

I could try parse forwards until the end of the escape sequence? I'd need to do that any number of times, though depending on the number of sequences found. Take this example:

```
'\x00\x00\x00\x00'
```

Should I just recursively parse escape sequences?

**Comment by nagisa** [comment]
My suggestion would be to *not* parse until the end – you already know what’s the error and where it is happening, you just need to ensure previous error keeps firing. i.e. current nightly outputs something like:

```
<anon>:2:5: 2:10 error: unterminated character constant: '\x00
<anon>:2     '\x00\x00'
             ^~~~~
```

It might be best to fall-back on error of this sort if you can’t immediately tell whether the literal is not terminated (i.e. missing `'`) or it is too long (i.e. too many characters before the closing `'`).

**Comment by gchp** [comment]
@nagisa ok, sounds good. Will update the PR shortly. Thanks!

**Comment by nagisa** [comment]
Thanks, the PR turned out nicely!

**Comment by gchp** [comment]
Thank you! Appreciate you going through it with me :)

**Comment by nagisa** [comment]
@bors retry

Seems like its one of the spurious errors we've been having lately.
