### PR TITLE
fix: Reject async assoc fns of const traits/impls in ast_passes

### LINKED ISSUE #117629: ice: `const_trait_impl`: `async` functions cannot be `const fn`
### Code
`rustc --edition=2021`
```Rust
#![feature(const_trait_impl)]

#[const_trait]
trait Tr {
    async fn ft1() {}
}

fn main() {}

```

### Meta

`rustc --version --verbose`:
```
rustc 1.75.0-nightly (c1ccc29cd 2023-11-05)
binary: rustc
commit-hash: c1ccc29cd6eeb79f24511d75e9db553385a5d73f
commit-date: 2023-11-05
host: x86_64-unknown-linux-gnu
release: 1.75.0-nightly
LLVM version: 17.0.4
```

### Error output

```
<output>
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
error: internal compiler error: no errors encountered even though `delay_span_bug` issued

error: internal compiler error: `async` functions cannot be `const fn`
 --> crash.rs:5:5
  |
5 |     async fn ft1() {}
  |     ^^^^^^^^^^^^^^^^^
  |
note: delayed at compiler/rustc_const_eval/src/transform/check_consts/check.rs:251:22
         0: <rustc_errors::HandlerInner>::emit_diagnostic
         1: <rustc_session::session::Session>::delay_span_bug::<rustc_span::span_encoding::Span, &str>
         2: rustc_mir_transform::mir_const_qualif
         3: rustc_query_impl::plumbing::__rust_begin_short_backtrace::<rustc_query_impl::query_impl::mir_const_qualif::dynamic_query::{closure#2}::{closure#0}, rustc_middle::query::erase::Erased<[u8; 5]>>
         4: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::DynamicConfig<rustc_query_system::query::caches::DefaultCache<rustc_span::def_id::DefId, rustc_middle::query::erase::Erased<[u8; 5]>>, false, false, false>, rustc_query_impl::plumbing::QueryCtxt, false>
         5: rustc_query_impl::query_impl::mir_const_qualif::get_query_non_incr::__rust_end_short_backtrace
         6: rustc_mir_transform::mir_promoted
         7: rustc_query_impl::plumbing::__rust_begin_short_backtrace::<rustc_query_impl::query_impl::mir_promoted::dynamic_query::{closure#2}::{closure#0}, rustc_middle::query::erase::Erased<[u8; 16]>>
         8: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::DynamicConfig<rustc_query_system::query::caches::VecCache<rustc_span::def_id::LocalDefId, rustc_middle::query::erase::Erased<[u8; 16]>>, false, false, false>, rustc_query_impl::plumbing::QueryCtxt, false>
         9: rustc_query_impl::query_impl::mir_promoted::get_query_non_incr::__rust_end_short_backtrace
        10: rustc_borrowck::mir_borrowck
        11: rustc_query_impl::plumbing::__rust_begin_short_backtrace::<rustc_query_impl::query_impl::mir_borrowck::dynamic_query::{closure#2}::{closure#0}, rustc_middle::query::erase::Erased<[u8; 8]>>
        12: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::DynamicConfig<rustc_query_system::query::caches::VecCache<rustc_span::def_id::LocalDefId, rustc_middle::query::erase::Erased<[u8; 8]>>, false, false, false>, rustc_query_impl::plumbing::QueryCtxt, false>
        13: rustc_query_impl::query_impl::mir_borrowck::get_query_non_incr::__rust_end_short_backtrace
        14: rustc_hir_analysis::collect::type_of::type_of_opaque
        15: rustc_query_impl::plumbing::__rust_begin_short_backtrace::<rustc_query_impl::query_impl::type_of_opaque::dynamic_query::{closure#2}::{closure#0}, rustc_middle::query::erase::Erased<[u8; 8]>>
        16: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::DynamicConfig<rustc_query_system::query::caches::DefaultCache<rustc_span::def_id::DefId, rustc_middle::query::erase::Erased<[u8; 8]>>, false, false, false>, rustc_query_impl::plumbing::QueryCtxt, false>
        17: rustc_query_impl::query_impl::type_of_opaque::get_query_non_incr::__rust_end_short_backtrace
        18: rustc_middle::query::plumbing::query_get_at::<rustc_query_system::query::caches::DefaultCache<rustc_span::def_id::DefId, rustc_middle::query::erase::Erased<[u8; 8]>>>
        19: rustc_hir_analysis::collect::type_of::type_of
        20: rustc_query_impl::plumbing::__rust_begin_short_backtrace::<rustc_query_impl::query_impl::type_of::dynamic_query::{closure#2}::{closure#0}, rustc_middle::query::erase::Erased<[u8; 8]>>
        21: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::DynamicConfig<rustc_query_system::query::caches::DefaultCache<rustc_span::def_id::DefId, rustc_middle::query::erase::Erased<[u8; 8]>>, false, false, false>, rustc_query_impl::plumbing::QueryCtxt, false>
        22: rustc_query_impl::query_impl::type_of::get_query_non_incr::__rust_end_short_backtrace
        23: rustc_middle::query::plumbing::query_get_at::<rustc_query_system::query::caches::DefaultCache<rustc_span::def_id::DefId, rustc_middle::query::erase::Erased<[u8; 8]>>>
        24: rustc_hir_analysis::check::check::check_mod_item_types
        25: rustc_query_impl::plumbing::__rust_begin_short_backtrace::<rustc_query_impl::query_impl::check_mod_item_types::dynamic_query::{closure#2}::{closure#0}, rustc_middle::query::erase::Erased<[u8; 0]>>
        26: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::DynamicConfig<rustc_query_system::query::caches::DefaultCache<rustc_span::def_id::LocalModDefId, rustc_middle::query::erase::Erased<[u8; 0]>>, false, false, false>, rustc_query_impl::plumbing::QueryCtxt, false>
        27: rustc_query_impl::query_impl::check_mod_item_types::get_query_non_incr::__rust_end_short_backtrace
        28: rustc_hir_analysis::check_crate
        29: rustc_interface::passes::analysis
        30: rustc_query_impl::plumbing::__rust_begin_short_backtrace::<rustc_query_impl::query_impl::analysis::dynamic_query::{closure#2}::{closure#0}, rustc_middle::query::erase::Erased<[u8; 1]>>
        31: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::DynamicConfig<rustc_query_system::query::caches::SingleCache<rustc_middle::query::erase::Erased<[u8; 1]>>, false, false, false>, rustc_query_impl::plumbing::QueryCtxt, false>
        32: rustc_query_impl::query_impl::analysis::get_query_non_incr::__rust_end_short_backtrace
        33: rustc_interface::interface::run_compiler::<core::result::Result<(), rustc_span::ErrorGuaranteed>, rustc_driver_impl::run_compiler::{closure#1}>::{closure#0}
        34: std::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface::util::run_in_thread_with_globals<rustc_interface::interface::run_compiler<core::result::Result<(), rustc_span::ErrorGuaranteed>, rustc_driver_impl::run_compiler::{closure#1}>::{closure#0}, core::result::Result<(), rustc_span::ErrorGuaranteed>>::{closure#0}::{closure#0}, core::result::Result<(), rustc_span::ErrorGuaranteed>>
        35: <<std::thread::Builder>::spawn_unchecked_<rustc_interface::util::run_in_thread_with_globals<rustc_interface::interface::run_compiler<core::result::Result<(), rustc_span::ErrorGuaranteed>, rustc_driver_impl::run_compiler::{closure#1}>::{closure#0}, core::result::Result<(), rustc_span::ErrorGuaranteed>>::{closure#0}::{closure#0}, core::result::Result<(), rustc_span::ErrorGuaranteed>>::{closure#1} as core::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
        36: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
                   at /rustc/c1ccc29cd6eeb79f24511d75e9db553385a5d73f/library/alloc/src/boxed.rs:2007:9
        37: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
                   at /rustc/c1ccc29cd6eeb79f24511d75e9db553385a5d73f/library/alloc/src/boxed.rs:2007:9
        38: std::sys::unix::thread::Thread::new::thread_start
                   at /rustc/c1ccc29cd6eeb79f24511d75e9db553385a5d73f/library/std/src/sys/unix/thread.rs:108:17
        39: <unknown>
        40: <unknown>
 --> crash.rs:5:5
  |
5 |     async fn ft1() {}
  |     ^^^^^^^^^^^^^^^^^

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: please attach the file at `/tmp/icemaker/rustc-ice-2023-11-06T10_23_53-2751136.txt` to your bug report

query stack during panic:
end of query stack
error: aborting due to 2 previous errors
```

</p>
</details>

### PR DESCRIPTION
**Pull request by ShoyuVanilla**
Fixes rust-lang/rust#117629

### CODE REVIEW

File: tests/ui/traits/const-traits/const-trait-async-assoc-fn.rs [hunk 1]
```diff
@@ -0,0 +1,10 @@
+//@ edition: 2021
+#![feature(const_trait_impl)]
+
+#[const_trait]
+trait Tr {
```
Comment (fmease) [inline tests/ui/traits/const-traits/const-trait-async-assoc-fn.rs]: Could you use the new const trait syntax (#143879). The attr-based one is legacy and is only kept because we use a beta (or nightly?) rustfmt for the stdlib instead of a locally built one, so it doesn't "yet" understand the new syntax.

```suggestion
const trait Tr {
```

File: compiler/rustc_ast_passes/messages.ftl [hunk 2]
```diff
@@ -32,6 +32,10 @@ ast_passes_assoc_type_without_body =
     associated type in `impl` without body
     .suggestion = provide a definition for the type
 
+ast_passes_async_fn_in_const_trait =
+    async functions are not allowed in `#[const_trait]`
```
Comment (fmease) [inline compiler/rustc_ast_passes/messages.ftl]: similarly

```suggestion
    async functions are not allowed in `const` traits
```

File: compiler/rustc_ast_passes/messages.ftl [hunk 3]
```diff
@@ -32,6 +32,10 @@ ast_passes_assoc_type_without_body =
...
+    .label = associated functions of `#[const_trait]` cannot be declared async
```
Comment (fmease) [inline compiler/rustc_ast_passes/messages.ftl]:
```suggestion
    .label = associated functions of `const` traits cannot be declared `async`
```

**Review by fmease — APPROVED** [review]
Two minor nits

**Comment by fmease** [comment]
Oh sry, didn't see errs assigned themself. I will wait for them.

**Comment by ShoyuVanilla** [comment]
> Oh sry, didn't see errs assigned themself. I will wait for them.

Thanks for the review anyway. I'll fix the nits!

File: compiler/rustc_ast_passes/src/ast_validation.rs [hunk 4]
```diff
@@ -294,6 +294,20 @@ impl<'a> AstValidator<'a> {
         });
     }
 
+    fn check_async_fn_in_const_trait(&self, sig: &FnSig, parent: &TraitOrTraitImpl) {
+        let TraitOrTraitImpl::Trait { constness: Const::Yes(const_trait), .. } = parent else {
+            return;
+        };
```
Comment (fmease) [inline compiler/rustc_ast_passes/src/ast_validation.rs]: We also gonna want to reject `async` fns inside `const` trait impls. The following code exhibits the same ICE atm:

```rs
#![feature(const_trait_impl)]
const trait Trait { fn f() -> impl Future<Output = ()>; }
impl const Trait for () { async fn f() {} }  
```

**Review by fmease — CHANGES_REQUESTED** [review]

File: compiler/rustc_ast_passes/src/ast_validation.rs (hunk 4 above)
Comment (ShoyuVanilla) [reply compiler/rustc_ast_passes/src/ast_validation.rs]: Oh, good catch. I couldn't think of such cases 😅  Thanks!

File: compiler/rustc_ast_passes/src/ast_validation.rs [hunk 5]
```diff
@@ -293,6 +293,25 @@ impl<'a> AstValidator<'a> {
         });
     }
 
+    fn check_async_fn_in_const_trait(&self, sig: &FnSig, parent: &TraitOrTraitImpl) {
+        let (TraitOrTraitImpl::Trait { constness: Const::Yes(const_keyword), .. }
+        | TraitOrTraitImpl::TraitImpl { constness: Const::Yes(const_keyword), .. }) = parent
+        else {
+            return;
+        };
```
Comment (fmease) [inline compiler/rustc_ast_passes/src/ast_validation.rs]:
```suggestion
        let Some(const_keyword) = parent.constness() else { return };
```

File: compiler/rustc_ast_passes/src/ast_validation.rs [hunk 6]
```diff
@@ -293,6 +293,25 @@ impl<'a> AstValidator<'a> {
         });
     }
 
+    fn check_async_fn_in_const_trait(&self, sig: &FnSig, parent: &TraitOrTraitImpl) {
```
Comment (fmease) [inline compiler/rustc_ast_passes/src/ast_validation.rs]:
```suggestion
    fn check_async_fn_in_const_trait_or_impl(&self, sig: &FnSig, parent: &TraitOrTraitImpl) {
```

or

```suggestion
    fn check_async_assoc_fn_not_const(&self, sig: &FnSig, parent: &TraitOrTraitImpl) {
```

**Review by fmease — APPROVED** [review]
Thanks! Two final nits
