### PR TITLE
stabilize `-Znext-solver=coherence`

### LINKED ISSUE #102048: relating projection substs is unsound during coherence
```rust
// This must fail coherence.
//
// Getting this to pass was fairly difficult, so here's an explanation
// of what's happening:
//
// Normalizing projections currently tries to replace them with inference variables
// while emitting a nested `Projection` obligation. This cannot be done if the projection
// has bound variables which is the case here.
//
// So the projections stay until after normalization. When unifying two projections we
// currently treat them as if they are injective, so we **incorrectly** unify their
// substs. This means that coherence for the two impls ends up unifying `?T` and `?U`
// as it tries to unify `<?T as WithAssoc1<'a>>::Assoc` with `<?U as WithAssoc1<'a>>::Assoc`.
//
// `impl1` therefore has the projection `<?T as WithAssoc2<'a>>::Assoc` and we have the
// assumption `?T: for<'a> WithAssoc2<'a, Assoc = i32>` in the `param_env`, so we normalize
// that to `i32`. We then try to unify `i32` from `impl1` with `u32` from `impl2` which fails,
// causing coherence to consider these two impls distinct.
pub trait Trait<T> {}

pub trait WithAssoc1<'a> {
    type Assoc;
}
pub trait WithAssoc2<'a> {
    type Assoc;
}

// impl 1
impl<T, U> Trait<for<'a> fn(<T as WithAssoc1<'a>>::Assoc, <U as WithAssoc2<'a>>::Assoc)> for (T, U)
where
    T: for<'a> WithAssoc1<'a> + for<'a> WithAssoc2<'a, Assoc = i32>,
    U: for<'a> WithAssoc2<'a>,
{
}

// impl 2
impl<T, U> Trait<for<'a> fn(<U as WithAssoc1<'a>>::Assoc, u32)> for (T, U) where
    U: for<'a> WithAssoc1<'a>
{
}
```
this currently compiles even though the following crate would mean that both impls overlap:
```rust
extern crate test1;
use test1::*;

struct Ty1;
struct Ty2;

impl WithAssoc1<'_> for Ty1 {
    type Assoc = ();
}
impl WithAssoc2<'_> for Ty1 {
    type Assoc = i32;
}
impl WithAssoc1<'_> for Ty2 {
    type Assoc = ();
}
impl WithAssoc2<'_> for Ty2 {
    type Assoc = u32;
}

fn foo<T, U>()
where
    (T, U): Trait<for<'a> fn((), u32)>,
{
}

fn main() {
    foo::<Ty1, Ty2>();
}
```
however, it seems like rustc generally has issues with both of these impls, so it actually believes that none of these impls apply :grin: see also #102047 where the first impl results in an ICE.

### LINKED ISSUE #105782: specialization: default items completely drop candidates instead of ambiguity
which is unsound during coherence, as coherence requires completeness
```rust
#![feature(specialization)]

trait Default {
   type Id;
}

impl<T> Default for T {
   default type Id = T;
}

trait Overlap {
   type Assoc;
}

impl Overlap for u32 {
   type Assoc = usize;
}

impl Overlap for <u32 as Default>::Id {
   type Assoc = Box<usize>;
}
```

https://github.com/rust-lang/rust/blob/03770f0e2b60c02db8fcf52fed5fb36aac70cedc/compiler/rustc_trait_selection/src/traits/project.rs#L1526

### LINKED ISSUE #107887: `project` for trait object bound candidates is incomplete
https://github.com/rust-lang/rust/blob/9b8dbd558c1c4b25c55d987e22baba312ae980ad/compiler/rustc_trait_selection/src/traits/project.rs#L1255-L1262

This ignores impl candidates even if the builtin object candidate guides inference, which is incomplete. Incompleteness during coherence is unsound, outside of coherence it can merely result in bad and confusing errors.

```rust
trait Trait<T> {
    type Assoc: ?Sized;
}

impl Trait<u32> for u32 {
    type Assoc = u32;
}

// This would trigger the check for overlap between automatic and custom impl.
// They actually don't overlap so an impl like this should remain possible
// forever.
//
// impl Trait<u64> for dyn Trait<u32, Assoc = u32> {
//     type Assoc =  dyn Trait<u32, Assoc = u32>;
// }
trait Indirect<T: ?Sized> {}
impl Indirect<dyn Trait<u32, Assoc = u32>> for () {}
impl<T: ?Sized> Trait<u64> for T
where
    (): Indirect<T>,
{
    type Assoc = u32;
}

trait Overlap<U> {}

impl<U> Overlap<U> for <dyn Trait<u32, Assoc = u32> as Trait<U>>::Assoc where
    dyn Trait<u32, Assoc = u32>: Trait<U>
{
}

impl Overlap<u64> for u32 {}

fn main() {}
```
currently results in 
```rust
error[E0277]: the trait bound `<(dyn Trait<u32, Assoc = u32> + 'static) as Trait<U>>::Assoc: Overlap<U>` is not satisfied
  --> src/main.rs:26:24
   |
26 | impl<U> Overlap<U> for <dyn Trait<u32, Assoc = u32> as Trait<U>>::Assoc
   |                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `Overlap<U>` is not implemented for `<(dyn Trait<u32, Assoc = u32> + 'static) as Trait<U>>::Assoc`
   |
help: consider further restricting the associated type
   |
28 | dyn Trait<u32, Assoc = u32>: Trait<U>, <(dyn Trait<u32, Assoc = u32> + 'static) as Trait<U>>::Assoc: Overlap<U>
   |                                      ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
```
which is also buggy :grin: adding that bound to the impl makes it compile but now they actually don't overlap because using the first impl would result in an inductive cycle. In the future all traits will be coinductive at which point this would be unsound. But as that will only happen in the new solver, we're safe.

It does however guide inference in incorrect ways, causing an additional - hopefully merely theoretical - breaking change with the new solver:
```rust
trait Trait<T> {
    type Assoc: ?Sized;
}

impl Trait<u32> for u32 {
    type Assoc = u16;
}

// This would trigger the check for overlap between automatic and custom impl
// They actually don't overlap so an impl like this should remain possible
// forever.
//
// impl Trait<u64> for dyn Trait<u32, Assoc = u32> {
//     type Assoc =  dyn Trait<u32, Assoc = u32>;
// }
trait Indirect<T: ?Sized> {}
impl Indirect<dyn Trait<u32, Assoc = u32>> for () {}
impl<T: ?Sized> Trait<u64> for T
where
    (): Indirect<T>,
{
    type Assoc = dyn Trait<u32, Assoc = u32>;
}

fn yay<T: Trait<U> + ?Sized, U>(x: &'static T) -> &'static <T as Trait<U>>::Assoc {
    todo!();
}

fn unconstrained<T>() -> T {
    todo!()
}

fn should_be_ambig() {
    let y: &'static dyn Trait<u32, Assoc = u32> = unconstrained();
    let _ = yay::<dyn Trait<u32, Assoc = u32>, _>(y);
    // The current solver incorrectly constrains `_` to `u32` here.
}

fn main() {
    let y: &'static dyn Trait<u32, Assoc = u32> = unconstrained();
    // let mut x = yay::<_, u64>(y); // compiles
    let mut x = yay::<_, _>(y); // errors
    x = y;
}
```
incorrect inference results in the following error in `main`:
```rust
error[E0308]: mismatched types
  --> src/main.rs:43:9
   |
42 |     let mut x = yay::<_, _>(y); // errors
   |                 -------------- expected due to this value
43 |     x = y;
   |         ^ expected `&u32`, found `&dyn Trait<u32, Assoc = u32>`
   |
   = note: expected reference `&u32`
              found reference `&'static (dyn Trait<u32, Assoc = u32> + 'static)`
```

### LINKED ISSUE #114862: Tracking issue for `-Znext-solver=coherence` (next solver enablement in coherence)
This is a tracking issue for `-Znext-solver=coherence`, and enabling the new solver in coherence mode. The `-Znext-solver=coherence` flag can be used to only enable the new solver for coherence, or `-Znext-solver` can be used to enable the new solver everywhere (see #107374 instead). This work is lead by the @rust-lang/initiative-trait-system-refactor.

### About tracking issues
Tracking issues are used to record the overall progress of implementation. They are also used as hubs connecting to other relevant issues, e.g., bugs or open design questions. A tracking issue is however not meant for large scale discussion, questions, or bug reports about a feature. Instead, open a dedicated issue for the specific matter and add the relevant feature gate label.

### Implementation history

* https://github.com/rust-lang/rust/pull/109447
* https://github.com/rust-lang/rust/pull/114023
* https://github.com/rust-lang/rust/pull/112122
* https://github.com/rust-lang/rust/pull/121848
* https://github.com/rust-lang/rust/pull/130249

##### Crater runs
* https://github.com/rust-lang/rust/pull/113895
* https://github.com/rust-lang/rust/pull/113991
* https://github.com/rust-lang/rust/pull/116357

### Issues

- [x] incorrect occurs check in projections https://github.com/rust-lang/trait-system-refactor-initiative/issues/8 (fixed by #117088)
- [x] intercrate ambiguity causes/proof tree work
- [x] overflow handling
  - [x] test breakage https://github.com/rust-lang/trait-system-refactor-initiative/issues/70
  - [x] typenum perrrf https://github.com/rust-lang/trait-system-refactor-initiative/issues/73
- [x] normalize for diagnostics, add new folder to `TypeErrCtxt` or sth
- [x] experiment normalizing both sides in `AliasRElate` before equating (perf)
- [x] Blog post asking for testing and experimentation https://blog.rust-lang.org/inside-rust/2023/12/22/trait-system-refactor-initiative.html
* [x] Investigate all the issues of the crater runs
* [x] https://github.com/rust-lang/trait-system-refactor-initiative/issues/65
* [x] https://github.com/rust-lang/trait-system-refactor-initiative/issues/20
    * [x] https://github.com/rust-lang/rust/pull/114023
    * [x] #118649
* [x] https://github.com/rust-lang/trait-system-refactor-initiative/issues/52 accepted breakage, caused by a bug of the old solver https://github.com/rust-lang/rust/issues/114061
* [x] https://github.com/rust-lang/trait-system-refactor-initiative/issues/51
    * [x] https://github.com/rust-lang/rust/pull/114457
* [x] work towards stabilization, writing an FCP proposal and documenting the solver https://rust-lang.zulipchat.com/#narrow/stream/364551-t-types.2Ftrait-system-refactor/topic/coherence.20stabilization
* [x] stabilization PR in #121848
* [x] reverted in #130249 due to #130056
* [ ] restabilize coherence

### LINKED ISSUE #118987: ICE: `When translating generic parameters from `..` to `..`, the expected specialization failed to hold`
auto-reduced (treereduce-rust):
````rust
#![feature(specialization)] //~ WARN the feature `specialization` is incomplete

trait Assoc {
    type Output;
}

default impl<T: Clone> Assoc for T {
    type Output = bool;
}

impl Assoc for u8 {}

trait Foo {}

impl Foo for <u8 as Assoc>::Output {}
impl Foo for <u16 as Assoc>::Output {}


````

original:
````rust
// run-pass

// Test that impls on projected self types can resolve overlap, even when the
// projections involve specialization, so long as the associated type is
// provided by the most specialized impl.

#![feature(specialization)] //~ WARN the feature `specialization` is incomplete

trait Assoc {
    type Output;
}

default impl<T:Clone> Assoc for T {
    type Output = bool;
}

impl Assoc for u8 { type Assoc = u8; }
impl Assoc for u16 { type Output = u16; }

trait Foo {}
impl Assoc for u32 {}
impl Foo for <u8 as Assoc>::Output {}
impl Foo for <u16 as Assoc>::Output {}

fn main() {}

````

Version information
````
rustc 1.76.0-nightly (d253bf61a 2023-12-15)
binary: rustc
commit-hash: d253bf61ad38a59cc579aee688f81a06c31283d3
commit-date: 2023-12-15
host: x86_64-unknown-linux-gnu
release: 1.76.0-nightly
LLVM version: 17.0.6

````

Command:
`/home/matthias/.rustup/toolchains/master/bin/rustc `

<details><summary><strong>Program output</strong></summary>
<p>

```
warning: the feature `specialization` is incomplete and may not be safe to use and/or cause compiler crashes
 --> /tmp/icemaker_global_tempdir.YmODNJIFWMvh/rustc_testrunner_tmpdir_reporting.mIkKiuxcepa6/mvce.rs:1:12
  |
1 | #![feature(specialization)] //~ WARN the feature `specialization` is incomplete
  |            ^^^^^^^^^^^^^^
  |
  = note: see issue #31844 <https://github.com/rust-lang/rust/issues/31844> for more information
  = help: consider using `min_specialization` instead, which is more stable and complete
  = note: `#[warn(incomplete_features)]` on by default

error[E0601]: `main` function not found in crate `mvce`
  --> /tmp/icemaker_global_tempdir.YmODNJIFWMvh/rustc_testrunner_tmpdir_reporting.mIkKiuxcepa6/mvce.rs:16:39
   |
16 | impl Foo for <u16 as Assoc>::Output {}
   |                                       ^ consider adding a `main` function to `/tmp/icemaker_global_tempdir.YmODNJIFWMvh/rustc_testrunner_tmpdir_reporting.mIkKiuxcepa6/mvce.rs`

error: internal compiler error: compiler/rustc_trait_selection/src/traits/specialize/mod.rs:123:21: When translating substitutions from DefId(0:8 ~ mvce[0e9d]::{impl#1}) to DefId(0:5 ~ mvce[0e9d]::{impl#0}), the expected specialization failed to hold

thread 'rustc' panicked at /rustc/d253bf61ad38a59cc579aee688f81a06c31283d3/compiler/rustc_errors/src/lib.rs:1119:75:
Box<dyn Any>
stack backtrace:
   0:     0x7f146c02d45c - std::backtrace_rs::backtrace::libunwind::trace::hd6103882acf895e3
                               at /rustc/d253bf61ad38a59cc579aee688f81a06c31283d3/library/std/src/../../backtrace/src/backtrace/libunwind.rs:104:5
   1:     0x7f146c02d45c - std::backtrace_rs::backtrace::trace_unsynchronized::h8bf8e05e9006d12a
                               at /rustc/d253bf61ad38a59cc579aee688f81a06c31283d3/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7f146c02d45c - std::sys_common::backtrace::_print_fmt::h40fa413ec9439832
                               at /rustc/d253bf61ad38a59cc579aee688f81a06c31283d3/library/std/src/sys_common/backtrace.rs:68:5
   3:     0x7f146c02d45c - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h5055b8322c3eecd3
                               at /rustc/d253bf61ad38a59cc579aee688f81a06c31283d3/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x7f146c080510 - core::fmt::rt::Argument::fmt::h142c2cad35d6896a
                               at /rustc/d253bf61ad38a59cc579aee688f81a06c31283d3/library/core/src/fmt/rt.rs:142:9
   5:     0x7f146c080510 - core::fmt::write::hd72f8a00b68449f5
                               at /rustc/d253bf61ad38a59cc579aee688f81a06c31283d3/library/core/src/fmt/mod.rs:1120:17
   6:     0x7f146c0212bf - std::io::Write::write_fmt::h1bcd670a0cd9a7ff
                               at /rustc/d253bf61ad38a59cc579aee688f81a06c31283d3/library/std/src/io/mod.rs:1810:15
   7:     0x7f146c02d244 - std::sys_common::backtrace::_print::h579af4e2f431a26b
                               at /rustc/d253bf61ad38a59cc579aee688f81a06c31283d3/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x7f146c02d244 - std::sys_common::backtrace::print::hdb76c2f48b3f9ac2
                               at /rustc/d253bf61ad38a59cc579aee688f81a06c31283d3/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x7f146c02ff47 - std::panicking::default_hook::{{closure}}::hb2313c1cb20e0e8d
  10:     0x7f146c02fcaf - std::panicking::default_hook::h0c0e9cb7313537d7
                               at /rustc/d253bf61ad38a59cc579aee688f81a06c31283d3/library/std/src/panicking.rs:292:9
  11:     0x7f1468d3f330 - std[90fcdab509e9b154]::panicking::update_hook::<alloc[197ac5e7db877155]::boxed::Box<rustc_driver_impl[c59161498cce3c44]::install_ice_hook::{closure#0}>>::{closure#0}
  12:     0x7f146c030688 - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h0f5771c93d1f75ce
                               at /rustc/d253bf61ad38a59cc579aee688f81a06c31283d3/library/alloc/src/boxed.rs:2029:9
  13:     0x7f146c030688 - std::panicking::rust_panic_with_hook::h4edda63d730d17fc
                               at /rustc/d253bf61ad38a59cc579aee688f81a06c31283d3/library/std/src/panicking.rs:783:13
  14:     0x7f1468d773b4 - std[90fcdab509e9b154]::panicking::begin_panic::<rustc_errors[b8d39b1188f581a8]::ExplicitBug>::{closure#0}
  15:     0x7f1468d73846 - std[90fcdab509e9b154]::sys_common::backtrace::__rust_end_short_backtrace::<std[90fcdab509e9b154]::panicking::begin_panic<rustc_errors[b8d39b1188f581a8]::ExplicitBug>::{closure#0}, !>
  16:     0x7f1468d6eea6 - std[90fcdab509e9b154]::panicking::begin_panic::<rustc_errors[b8d39b1188f581a8]::ExplicitBug>
  17:     0x7f1468d82558 - <rustc_errors[b8d39b1188f581a8]::diagnostic_builder::Bug as rustc_errors[b8d39b1188f581a8]::diagnostic_builder::EmissionGuarantee>::diagnostic_builder_emit_producing_guarantee
  18:     0x7f1469163a15 - <rustc_errors[b8d39b1188f581a8]::Handler>::bug::<alloc[197ac5e7db877155]::string::String>
  19:     0x7f14691fe5fd - rustc_middle[17eaf787359ec706]::util::bug::opt_span_bug_fmt::<rustc_span[9c405c0df40bde1a]::span_encoding::Span>::{closure#0}
  20:     0x7f14691e7f0a - rustc_middle[17eaf787359ec706]::ty::context::tls::with_opt::<rustc_middle[17eaf787359ec706]::util::bug::opt_span_bug_fmt<rustc_span[9c405c0df40bde1a]::span_encoding::Span>::{closure#0}, !>::{closure#0}
  21:     0x7f14691e7d88 - rustc_middle[17eaf787359ec706]::ty::context::tls::with_context_opt::<rustc_middle[17eaf787359ec706]::ty::context::tls::with_opt<rustc_middle[17eaf787359ec706]::util::bug::opt_span_bug_fmt<rustc_span[9c405c0df40bde1a]::span_encoding::Span>::{closure#0}, !>::{closure#0}, !>
  22:     0x7f146715b670 - rustc_middle[17eaf787359ec706]::util::bug::bug_fmt
  23:     0x7f146a3b9f90 - rustc_trait_selection[2323e8e34cf002d2]::traits::specialize::translate_args_with_cause::<rustc_trait_selection[2323e8e34cf002d2]::traits::specialize::translate_args::{closure#0}>
  24:     0x7f146a2a9347 - rustc_trait_selection[2323e8e34cf002d2]::traits::project::opt_normalize_projection_type
  25:     0x7f146a2a5f9e - <rustc_trait_selection[2323e8e34cf002d2]::traits::project::AssocTypeNormalizer as rustc_type_ir[f2235eff04baa55d]::fold::TypeFolder<rustc_middle[17eaf787359ec706]::ty::context::TyCtxt>>::fold_ty
  26:     0x7f146a95b95c - rustc_trait_selection[2323e8e34cf002d2]::traits::project::normalize_with_depth_to::<rustc_middle[17eaf787359ec706]::ty::ImplHeader>::{closure#0}
  27:     0x7f146a95ae43 - rustc_trait_selection[2323e8e34cf002d2]::traits::coherence::fresh_impl_header_normalized
  28:     0x7f146a959108 - rustc_trait_selection[2323e8e34cf002d2]::traits::coherence::overlap
  29:     0x7f146a76e9f3 - <rustc_middle[17eaf787359ec706]::traits::specialization_graph::Children as rustc_trait_selection[2323e8e34cf002d2]::traits::specialize::specialization_graph::ChildrenExt>::insert
  30:     0x7f146a76e07b - <rustc_middle[17eaf787359ec706]::traits::specialization_graph::Graph as rustc_trait_selection[2323e8e34cf002d2]::traits::specialize::specialization_graph::GraphExt>::insert
  31:     0x7f146aaa6d8a - rustc_trait_selection[2323e8e34cf002d2]::traits::specialize::specialization_graph_provider
  32:     0x7f146aaa67b2 - rustc_query_impl[43baca739a647e2b]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[43baca739a647e2b]::query_impl::specialization_graph_of::dynamic_query::{closure#2}::{closure#0}, rustc_middle[17eaf787359ec706]::query::erase::Erased<[u8; 8usize]>>
  33:     0x7f146a0811d4 - rustc_query_system[f7d04bba5a359203]::query::plumbing::try_execute_query::<rustc_query_impl[43baca739a647e2b]::DynamicConfig<rustc_query_system[f7d04bba5a359203]::query::caches::DefaultCache<rustc_span[9c405c0df40bde1a]::def_id::DefId, rustc_middle[17eaf787359ec706]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[43baca739a647e2b]::plumbing::QueryCtxt, false>
  34:     0x7f146a4220de - rustc_query_impl[43baca739a647e2b]::query_impl::specialization_graph_of::get_query_non_incr::__rust_end_short_backtrace
  35:     0x7f146a1ec291 - rustc_hir_analysis[521878d46db95bb1]::coherence::coherent_trait
  36:     0x7f146a1ec16f - rustc_query_impl[43baca739a647e2b]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[43baca739a647e2b]::query_impl::coherent_trait::dynamic_query::{closure#2}::{closure#0}, rustc_middle[17eaf787359ec706]::query::erase::Erased<[u8; 0usize]>>
  37:     0x7f146a9832fd - rustc_query_system[f7d04bba5a359203]::query::plumbing::try_execute_query::<rustc_query_impl[43baca739a647e2b]::DynamicConfig<rustc_query_system[f7d04bba5a359203]::query::caches::DefaultCache<rustc_span[9c405c0df40bde1a]::def_id::DefId, rustc_middle[17eaf787359ec706]::query::erase::Erased<[u8; 0usize]>>, false, false, false>, rustc_query_impl[43baca739a647e2b]::plumbing::QueryCtxt, false>
  38:     0x7f146a98308d - rustc_query_impl[43baca739a647e2b]::query_impl::coherent_trait::get_query_non_incr::__rust_end_short_backtrace
  39:     0x7f146a96e7aa - rustc_hir_analysis[521878d46db95bb1]::check_crate
  40:     0x7f146aab0117 - rustc_interface[1819133c53e350af]::passes::analysis
  41:     0x7f146aaafd5d - rustc_query_impl[43baca739a647e2b]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[43baca739a647e2b]::query_impl::analysis::dynamic_query::{closure#2}::{closure#0}, rustc_middle[17eaf787359ec706]::query::erase::Erased<[u8; 1usize]>>
  42:     0x7f146afa9ff2 - rustc_query_system[f7d04bba5a359203]::query::plumbing::try_execute_query::<rustc_query_impl[43baca739a647e2b]::DynamicConfig<rustc_query_system[f7d04bba5a359203]::query::caches::SingleCache<rustc_middle[17eaf787359ec706]::query::erase::Erased<[u8; 1usize]>>, false, false, false>, rustc_query_impl[43baca739a647e2b]::plumbing::QueryCtxt, false>
  43:     0x7f146afa9df9 - rustc_query_impl[43baca739a647e2b]::query_impl::analysis::get_query_non_incr::__rust_end_short_backtrace
  44:     0x7f146b045e97 - rustc_interface[1819133c53e350af]::interface::run_compiler::<core[ea5c17b9bf3f7e3c]::result::Result<(), rustc_span[9c405c0df40bde1a]::ErrorGuaranteed>, rustc_driver_impl[c59161498cce3c44]::run_compiler::{closure#0}>::{closure#0}
  45:     0x7f146afbceda - std[90fcdab509e9b154]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[1819133c53e350af]::util::run_in_thread_with_globals<rustc_interface[1819133c53e350af]::util::run_in_thread_pool_with_globals<rustc_interface[1819133c53e350af]::interface::run_compiler<core[ea5c17b9bf3f7e3c]::result::Result<(), rustc_span[9c405c0df40bde1a]::ErrorGuaranteed>, rustc_driver_impl[c59161498cce3c44]::run_compiler::{closure#0}>::{closure#0}, core[ea5c17b9bf3f7e3c]::result::Result<(), rustc_span[9c405c0df40bde1a]::ErrorGuaranteed>>::{closure#0}, core[ea5c17b9bf3f7e3c]::result::Result<(), rustc_span[9c405c0df40bde1a]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[ea5c17b9bf3f7e3c]::result::Result<(), rustc_span[9c405c0df40bde1a]::ErrorGuaranteed>>
  46:     0x7f146afbcd03 - <<std[90fcdab509e9b154]::thread::Builder>::spawn_unchecked_<rustc_interface[1819133c53e350af]::util::run_in_thread_with_globals<rustc_interface[1819133c53e350af]::util::run_in_thread_pool_with_globals<rustc_interface[1819133c53e350af]::interface::run_compiler<core[ea5c17b9bf3f7e3c]::result::Result<(), rustc_span[9c405c0df40bde1a]::ErrorGuaranteed>, rustc_driver_impl[c59161498cce3c44]::run_compiler::{closure#0}>::{closure#0}, core[ea5c17b9bf3f7e3c]::result::Result<(), rustc_span[9c405c0df40bde1a]::ErrorGuaranteed>>::{closure#0}, core[ea5c17b9bf3f7e3c]::result::Result<(), rustc_span[9c405c0df40bde1a]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[ea5c17b9bf3f7e3c]::result::Result<(), rustc_span[9c405c0df40bde1a]::ErrorGuaranteed>>::{closure#1} as core[ea5c17b9bf3f7e3c]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  47:     0x7f146c03a515 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h9895702b6be34956
                               at /rustc/d253bf61ad38a59cc579aee688f81a06c31283d3/library/alloc/src/boxed.rs:2015:9
  48:     0x7f146c03a515 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hbd2c76ba009df5db
                               at /rustc/d253bf61ad38a59cc579aee688f81a06c31283d3/library/alloc/src/boxed.rs:2015:9
  49:     0x7f146c03a515 - std::sys::unix::thread::Thread::new::thread_start::h8bdfca0a04fd1f70
                               at /rustc/d253bf61ad38a59cc579aee688f81a06c31283d3/library/std/src/sys/unix/thread.rs:108:17
  50:     0x7f1465eaa9eb - <unknown>
  51:     0x7f1465f2e7cc - <unknown>
  52:                0x0 - <unknown>

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.76.0-nightly (d253bf61a 2023-12-15) running on x86_64-unknown-linux-gnu

query stack during panic:
#0 [specialization_graph_of] building specialization graph of trait `Foo`
#1 [coherent_trait] coherence checking all impls of trait `Foo`
#2 [analysis] running analysis passes on this crate
end of query stack
error: aborting due to 2 previous errors; 1 warning emitted

For more information about this error, try `rustc --explain E0601`.

```

</p>
</details>

### LINKED ISSUE #119272: ICE: `unexpected ambiguity: Canonical..`
auto-reduced (treereduce-rust):
````rust
#![feature(type_alias_impl_trait)]
mod defining_scope {
    use super::*;
    pub type Alias<T> = impl Sized;

    pub fn cast<T>(x: Container<Alias<T>, T>) -> Container<T, T> {
        x
    }
}

struct Container<T: Trait<U>, U> {
    x: <T as Trait<U>>::Assoc,
}

trait Trait<T> {
    type Assoc;
}

impl<T> Trait<T> for T {
    type Assoc = Box<u32>;
}
impl<T> Trait<T> for defining_scope::Alias<T> {
    type Assoc = usize;
}

fn main() {}


````

original:
````rust
//revisions: old next
//[next] compile-flags: -Znext-solver

// A regression test for #105787

//[old] known-bug: #105787
//[old] check-pass
#![feature(type_alias_impl_trait)]
mod defining_scope {
    use super::*;
    pub type Alias<T> = impl Sized;

    pub fn cast<T>(x: Container<Alias<T>, T>) -> Container<T, T> {
        x
    }
}

struct Container<T: Trait<U>, U> {
    x: <T as Trait<U>>::Assoc,
}

trait Trait<T> {
    type Assoc;
}

impl<T> Trait<T> for T {
    type Assoc = Box<u32>;
}
impl<T> Trait<T> for defining_scope::Alias<T> {
    //[next]~^ ERROR conflicting implementations of trait
    type Assoc = usize;
}

fn main() {
        Default::default()
    }

````

Version information
````
rustc 1.77.0-nightly (2d7be7393 2023-12-23)
binary: rustc
commit-hash: 2d7be73931e0978c8758a672cc7258b417a7e999
commit-date: 2023-12-23
host: x86_64-unknown-linux-gnu
release: 1.77.0-nightly
LLVM version: 17.0.6

````

Command:
`/home/matthias/.rustup/toolchains/master/bin/rustc `

<details><summary><strong>Program output</strong></summary>
<p>

```
warning: struct `Container` is never constructed
  --> /tmp/icemaker_global_tempdir.fzzOAlARA6tK/rustc_testrunner_tmpdir_reporting.utiWfmv9NFbE/mvce.rs:11:8
   |
11 | struct Container<T: Trait<U>, U> {
   |        ^^^^^^^^^
   |
   = note: `#[warn(dead_code)]` on by default

warning: function `cast` is never used
 --> /tmp/icemaker_global_tempdir.fzzOAlARA6tK/rustc_testrunner_tmpdir_reporting.utiWfmv9NFbE/mvce.rs:6:12
  |
6 |     pub fn cast<T>(x: Container<Alias<T>, T>) -> Container<T, T> {
  |            ^^^^

error: internal compiler error: no errors encountered even though `span_delayed_bug` issued

error: internal compiler error: unexpected ambiguity: Canonical { value: ParamEnvAnd { param_env: ParamEnv { caller_bounds: [Binder { value: TraitPredicate(<T as std::marker::Sized>, polarity:Positive), bound_vars: [] }], reveal: All }, value: AliasTy { args: [T/#0, T/#0], def_id: DefId(0:15 ~ mvce[8437]::Trait::Assoc) } }, max_universe: U0, variables: [] } Canonical { value: QueryResponse { var_values: CanonicalVarValues { var_values: [] }, region_constraints: QueryRegionConstraints { outlives: [], member_constraints: [] }, certainty: Ambiguous, opaque_types: [], value: NormalizationResult { normalized_ty: ^0 } }, max_universe: U0, variables: [CanonicalVarInfo { kind: Ty(General(U0)) }] }
  |
  = note: delayed at compiler/rustc_trait_selection/src/traits/query/normalize.rs:295:34
             0: <rustc_errors::DiagCtxtInner>::emit_diagnostic_without_consuming
             1: <rustc_errors::DiagCtxt>::emit_diagnostic_without_consuming
             2: <rustc_errors::DiagCtxt>::emit_diagnostic
             3: <rustc_session::session::Session>::span_delayed_bug::<rustc_span::span_encoding::Span, alloc::string::String>
             4: <rustc_trait_selection::traits::query::normalize::QueryNormalizer as rustc_type_ir::fold::FallibleTypeFolder<rustc_middle::ty::context::TyCtxt>>::try_fold_ty
             5: <rustc_traits::normalize_erasing_regions::provide::{closure#0} as core::ops::function::FnOnce<(rustc_middle::ty::context::TyCtxt, rustc_middle::ty::ParamEnvAnd<rustc_middle::ty::generic_args::GenericArg>)>>::call_once
             6: rustc_query_impl::plumbing::__rust_begin_short_backtrace::<rustc_query_impl::query_impl::try_normalize_generic_arg_after_erasing_regions::dynamic_query::{closure#2}::{closure#0}, rustc_middle::query::erase::Erased<[u8; 8]>>
             7: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::DynamicConfig<rustc_query_system::query::caches::DefaultCache<rustc_middle::ty::ParamEnvAnd<rustc_middle::ty::generic_args::GenericArg>, rustc_middle::query::erase::Erased<[u8; 8]>>, false, false, false>, rustc_query_impl::plumbing::QueryCtxt, false>
             8: rustc_query_impl::query_impl::try_normalize_generic_arg_after_erasing_regions::get_query_non_incr::__rust_end_short_backtrace
             9: <rustc_middle::ty::normalize_erasing_regions::TryNormalizeAfterErasingRegionsFolder as rustc_type_ir::fold::FallibleTypeFolder<rustc_middle::ty::context::TyCtxt>>::try_fold_ty
            10: rustc_ty_utils::needs_drop::needs_drop_raw
            11: rustc_query_impl::plumbing::__rust_begin_short_backtrace::<rustc_query_impl::query_impl::needs_drop_raw::dynamic_query::{closure#2}::{closure#0}, rustc_middle::query::erase::Erased<[u8; 1]>>
            12: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::DynamicConfig<rustc_query_system::query::caches::DefaultCache<rustc_middle::ty::ParamEnvAnd<rustc_middle::ty::Ty>, rustc_middle::query::erase::Erased<[u8; 1]>>, false, false, false>, rustc_query_impl::plumbing::QueryCtxt, false>
            13: rustc_query_impl::query_impl::needs_drop_raw::get_query_non_incr::__rust_end_short_backtrace
            14: <rustc_mir_transform::elaborate_drops::ElaborateDrops as rustc_middle::mir::MirPass>::run_pass
            15: rustc_mir_transform::run_analysis_to_runtime_passes
            16: rustc_mir_transform::mir_drops_elaborated_and_const_checked
            17: rustc_query_impl::plumbing::__rust_begin_short_backtrace::<rustc_query_impl::query_impl::mir_drops_elaborated_and_const_checked::dynamic_query::{closure#2}::{closure#0}, rustc_middle::query::erase::Erased<[u8; 8]>>
            18: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::DynamicConfig<rustc_query_system::query::caches::VecCache<rustc_span::def_id::LocalDefId, rustc_middle::query::erase::Erased<[u8; 8]>>, false, false, false>, rustc_query_impl::plumbing::QueryCtxt, false>
            19: rustc_query_impl::query_impl::mir_drops_elaborated_and_const_checked::get_query_non_incr::__rust_end_short_backtrace
            20: rustc_interface::passes::analysis
            21: rustc_query_impl::plumbing::__rust_begin_short_backtrace::<rustc_query_impl::query_impl::analysis::dynamic_query::{closure#2}::{closure#0}, rustc_middle::query::erase::Erased<[u8; 1]>>
            22: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::DynamicConfig<rustc_query_system::query::caches::SingleCache<rustc_middle::query::erase::Erased<[u8; 1]>>, false, false, false>, rustc_query_impl::plumbing::QueryCtxt, false>
            23: rustc_query_impl::query_impl::analysis::get_query_non_incr::__rust_end_short_backtrace
            24: rustc_interface::interface::run_compiler::<core::result::Result<(), rustc_span::ErrorGuaranteed>, rustc_driver_impl::run_compiler::{closure#0}>::{closure#0}
            25: std::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface::util::run_in_thread_with_globals<rustc_interface::util::run_in_thread_pool_with_globals<rustc_interface::interface::run_compiler<core::result::Result<(), rustc_span::ErrorGuaranteed>, rustc_driver_impl::run_compiler::{closure#0}>::{closure#0}, core::result::Result<(), rustc_span::ErrorGuaranteed>>::{closure#0}, core::result::Result<(), rustc_span::ErrorGuaranteed>>::{closure#0}::{closure#0}, core::result::Result<(), rustc_span::ErrorGuaranteed>>
            26: <<std::thread::Builder>::spawn_unchecked_<rustc_interface::util::run_in_thread_with_globals<rustc_interface::util::run_in_thread_pool_with_globals<rustc_interface::interface::run_compiler<core::result::Result<(), rustc_span::ErrorGuaranteed>, rustc_driver_impl::run_compiler::{closure#0}>::{closure#0}, core::result::Result<(), rustc_span::ErrorGuaranteed>>::{closure#0}, core::result::Result<(), rustc_span::ErrorGuaranteed>>::{closure#0}::{closure#0}, core::result::Result<(), rustc_span::ErrorGuaranteed>>::{closure#1} as core::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
            27: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
                       at /rustc/2d7be73931e0978c8758a672cc7258b417a7e999/library/alloc/src/boxed.rs:2015:9
            28: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
                       at /rustc/2d7be73931e0978c8758a672cc7258b417a7e999/library/alloc/src/boxed.rs:2015:9
            29: std::sys::unix::thread::Thread::new::thread_start
                       at /rustc/2d7be73931e0978c8758a672cc7258b417a7e999/library/std/src/sys/unix/thread.rs:108:17
            30: <unknown>
            31: <unknown>
          

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.77.0-nightly (2d7be7393 2023-12-23) running on x86_64-unknown-linux-gnu

query stack during panic:
end of query stack
error: aborting due to 2 previous errors; 2 warnings emitted


```

</p>
</details>

### LINKED ISSUE #124207: ICE: `Layout::compute: unexpected type '_'`
### Code

```Rust
#![feature(transmutability)]
#![feature(type_alias_impl_trait)]
trait OpaqueTrait {}
type OpaqueType = impl OpaqueTrait;
trait AnotherTrait {}
impl<T: std::mem::BikeshedIntrinsicFrom<(), ()>> AnotherTrait for T {}
impl AnotherTrait for OpaqueType {}
pub fn main() {}

```

### Meta

`rustc --version --verbose`:
```
rustc 1.79.0-nightly (f9b161492 2024-04-19)
binary: rustc
commit-hash: f9b16149208c8a8a349c32813312716f6603eb6f
commit-date: 2024-04-19
host: x86_64-unknown-linux-gnu
release: 1.79.0-nightly
LLVM version: 18.1.4
```

### Error output

```
error: unconstrained opaque type
 --> a.rs:4:19
  |
4 | type OpaqueType = impl OpaqueTrait;
  |                   ^^^^^^^^^^^^^^^^
  |
  = note: `OpaqueType` must be used in combination with a concrete type within the same module

error[E0747]: type provided when a constant was expected
 --> a.rs:6:45
  |
6 | impl<T: std::mem::BikeshedIntrinsicFrom<(), ()>> AnotherTrait for T {}
  |                                             ^^
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
error: internal compiler error: compiler/rustc_ty_utils/src/layout.rs:676:13: Layout::compute: unexpected type `_`

thread 'rustc' panicked at compiler/rustc_ty_utils/src/layout.rs:676:13:
Box<dyn Any>
stack backtrace:
   0:     0x770d87853a75 - std::backtrace_rs::backtrace::libunwind::trace::ha83ac36f3d576216
                               at /rustc/f9b16149208c8a8a349c32813312716f6603eb6f/library/std/src/../../backtrace/src/backtrace/libunwind.rs:105:5
   1:     0x770d87853a75 - std::backtrace_rs::backtrace::trace_unsynchronized::hb98e29c033b56d71
                               at /rustc/f9b16149208c8a8a349c32813312716f6603eb6f/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x770d87853a75 - std::sys_common::backtrace::_print_fmt::h9cac98576a93da05
                               at /rustc/f9b16149208c8a8a349c32813312716f6603eb6f/library/std/src/sys_common/backtrace.rs:68:5
   3:     0x770d87853a75 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hc08cb2c96bc6af47
                               at /rustc/f9b16149208c8a8a349c32813312716f6603eb6f/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x770d878a2ceb - core::fmt::rt::Argument::fmt::h7e0e829b93f0d534
                               at /rustc/f9b16149208c8a8a349c32813312716f6603eb6f/library/core/src/fmt/rt.rs:165:63
   5:     0x770d878a2ceb - core::fmt::write::hc94efcaace3d21b0
                               at /rustc/f9b16149208c8a8a349c32813312716f6603eb6f/library/core/src/fmt/mod.rs:1157:21
   6:     0x770d878485ff - std::io::Write::write_fmt::h04b543bbaa6f2dd7
                               at /rustc/f9b16149208c8a8a349c32813312716f6603eb6f/library/std/src/io/mod.rs:1832:15
   7:     0x770d8785384e - std::sys_common::backtrace::_print::hee1e9db3a2945572
                               at /rustc/f9b16149208c8a8a349c32813312716f6603eb6f/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x770d8785384e - std::sys_common::backtrace::print::h6c7cba00911f4786
                               at /rustc/f9b16149208c8a8a349c32813312716f6603eb6f/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x770d878561b9 - std::panicking::default_hook::{{closure}}::ha7d58c0a2e775af5
  10:     0x770d87855efd - std::panicking::default_hook::h87a09229bb1730d2
                               at /rustc/f9b16149208c8a8a349c32813312716f6603eb6f/library/std/src/panicking.rs:298:9
  11:     0x770d8421a4bc - std[b1a6245f99d026e2]::panicking::update_hook::<alloc[ffa384fe5a6ae168]::boxed::Box<rustc_driver_impl[5ebafc17f6baf5ac]::install_ice_hook::{closure#0}>>::{closure#0}
  12:     0x770d878568b6 - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h5e2a6d4eae799185
                               at /rustc/f9b16149208c8a8a349c32813312716f6603eb6f/library/alloc/src/boxed.rs:2036:9
  13:     0x770d878568b6 - std::panicking::rust_panic_with_hook::hd810693d9a8c8478
                               at /rustc/f9b16149208c8a8a349c32813312716f6603eb6f/library/std/src/panicking.rs:799:13
  14:     0x770d84249f84 - std[b1a6245f99d026e2]::panicking::begin_panic::<rustc_errors[ba5989c8493379f8]::ExplicitBug>::{closure#0}
  15:     0x770d84246936 - std[b1a6245f99d026e2]::sys_common::backtrace::__rust_end_short_backtrace::<std[b1a6245f99d026e2]::panicking::begin_panic<rustc_errors[ba5989c8493379f8]::ExplicitBug>::{closure#0}, !>
  16:     0x770d84241f06 - std[b1a6245f99d026e2]::panicking::begin_panic::<rustc_errors[ba5989c8493379f8]::ExplicitBug>
  17:     0x770d84252ea1 - <rustc_errors[ba5989c8493379f8]::diagnostic::BugAbort as rustc_errors[ba5989c8493379f8]::diagnostic::EmissionGuarantee>::emit_producing_guarantee
  18:     0x770d846fcf9c - rustc_middle[e99f9e5b138cd7e6]::util::bug::opt_span_bug_fmt::<rustc_span[add96f0181708003]::span_encoding::Span>::{closure#0}
  19:     0x770d846e47fa - rustc_middle[e99f9e5b138cd7e6]::ty::context::tls::with_opt::<rustc_middle[e99f9e5b138cd7e6]::util::bug::opt_span_bug_fmt<rustc_span[add96f0181708003]::span_encoding::Span>::{closure#0}, !>::{closure#0}
  20:     0x770d846e467b - rustc_middle[e99f9e5b138cd7e6]::ty::context::tls::with_context_opt::<rustc_middle[e99f9e5b138cd7e6]::ty::context::tls::with_opt<rustc_middle[e99f9e5b138cd7e6]::util::bug::opt_span_bug_fmt<rustc_span[add96f0181708003]::span_encoding::Span>::{closure#0}, !>::{closure#0}, !>
  21:     0x770d82ab2580 - rustc_middle[e99f9e5b138cd7e6]::util::bug::bug_fmt
  22:     0x770d85c63c6d - rustc_ty_utils[48d247cc516c592c]::layout::layout_of_uncached
  23:     0x770d85c55348 - rustc_ty_utils[48d247cc516c592c]::layout::layout_of
  24:     0x770d85c552d1 - rustc_query_impl[c33ec4ad6556889c]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[c33ec4ad6556889c]::query_impl::layout_of::dynamic_query::{closure#2}::{closure#0}, rustc_middle[e99f9e5b138cd7e6]::query::erase::Erased<[u8; 16usize]>>
  25:     0x770d85c545b9 - rustc_query_system[4ce495e28c9907d2]::query::plumbing::try_execute_query::<rustc_query_impl[c33ec4ad6556889c]::DynamicConfig<rustc_query_system[4ce495e28c9907d2]::query::caches::DefaultCache<rustc_middle[e99f9e5b138cd7e6]::ty::ParamEnvAnd<rustc_middle[e99f9e5b138cd7e6]::ty::Ty>, rustc_middle[e99f9e5b138cd7e6]::query::erase::Erased<[u8; 16usize]>>, false, true, false>, rustc_query_impl[c33ec4ad6556889c]::plumbing::QueryCtxt, false>
  26:     0x770d85c54238 - rustc_query_impl[c33ec4ad6556889c]::query_impl::layout_of::get_query_non_incr::__rust_end_short_backtrace
  27:     0x770d84dc16fe - rustc_middle[e99f9e5b138cd7e6]::query::plumbing::query_get_at::<rustc_query_system[4ce495e28c9907d2]::query::caches::DefaultCache<rustc_middle[e99f9e5b138cd7e6]::ty::ParamEnvAnd<rustc_middle[e99f9e5b138cd7e6]::ty::Ty>, rustc_middle[e99f9e5b138cd7e6]::query::erase::Erased<[u8; 16usize]>>>
  28:     0x770d84ddd419 - <rustc_transmute[fa409bc515f85ab3]::maybe_transmutable::MaybeTransmutableQuery<rustc_middle[e99f9e5b138cd7e6]::ty::Ty, rustc_middle[e99f9e5b138cd7e6]::ty::context::TyCtxt>>::answer::{closure#0}
  29:     0x770d84ddab53 - <rustc_transmute[fa409bc515f85ab3]::rustc::TransmuteTypeEnv>::is_transmutable
  30:     0x770d85eb7ad3 - <rustc_trait_selection[c82f91c0eb405fdf]::traits::select::SelectionContext>::confirm_candidate
  31:     0x770d85a915cb - <rustc_trait_selection[c82f91c0eb405fdf]::traits::select::SelectionContext>::evaluate_candidate::{closure#0}::{closure#0}
  32:     0x770d82378af3 - <rustc_trait_selection[c82f91c0eb405fdf]::traits::select::SelectionContext>::candidate_from_obligation_no_cache
  33:     0x770d823b8b59 - <rustc_trait_selection[c82f91c0eb405fdf]::traits::select::SelectionContext>::candidate_from_obligation
  34:     0x770d85a94da0 - <rustc_trait_selection[c82f91c0eb405fdf]::traits::select::SelectionContext>::evaluate_trait_predicate_recursively
  35:     0x770d85a8522e - <rustc_infer[c524740c99df999d]::infer::InferCtxt>::probe::<core[4c074f95c636289]::result::Result<rustc_middle[e99f9e5b138cd7e6]::traits::select::EvaluationResult, rustc_middle[e99f9e5b138cd7e6]::traits::select::OverflowError>, <rustc_trait_selection[c82f91c0eb405fdf]::traits::select::SelectionContext>::evaluation_probe<<rustc_trait_selection[c82f91c0eb405fdf]::traits::select::SelectionContext>::evaluate_root_obligation::{closure#0}>::{closure#0}>
  36:     0x770d85a84201 - rustc_trait_selection[c82f91c0eb405fdf]::traits::coherence::overlap
  37:     0x770d823a0914 - <rustc_middle[e99f9e5b138cd7e6]::traits::specialization_graph::Children as rustc_trait_selection[c82f91c0eb405fdf]::traits::specialize::specialization_graph::ChildrenExt>::insert
  38:     0x770d832180e7 - <rustc_middle[e99f9e5b138cd7e6]::traits::specialization_graph::Graph as rustc_trait_selection[c82f91c0eb405fdf]::traits::specialize::specialization_graph::GraphExt>::insert
  39:     0x770d856b40bc - rustc_trait_selection[c82f91c0eb405fdf]::traits::specialize::specialization_graph_provider
  40:     0x770d856b3c1d - rustc_query_impl[c33ec4ad6556889c]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[c33ec4ad6556889c]::query_impl::specialization_graph_of::dynamic_query::{closure#2}::{closure#0}, rustc_middle[e99f9e5b138cd7e6]::query::erase::Erased<[u8; 8usize]>>
  41:     0x770d856b65e1 - rustc_query_system[4ce495e28c9907d2]::query::plumbing::try_execute_query::<rustc_query_impl[c33ec4ad6556889c]::DynamicConfig<rustc_query_system[4ce495e28c9907d2]::query::caches::DefIdCache<rustc_middle[e99f9e5b138cd7e6]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[c33ec4ad6556889c]::plumbing::QueryCtxt, false>
  42:     0x770d85d8a65e - rustc_query_impl[c33ec4ad6556889c]::query_impl::specialization_graph_of::get_query_non_incr::__rust_end_short_backtrace
  43:     0x770d85ce3af1 - rustc_hir_analysis[465c838ed0c91715]::coherence::coherent_trait
  44:     0x770d85ce37f1 - rustc_query_impl[c33ec4ad6556889c]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[c33ec4ad6556889c]::query_impl::coherent_trait::dynamic_query::{closure#2}::{closure#0}, rustc_middle[e99f9e5b138cd7e6]::query::erase::Erased<[u8; 1usize]>>
  45:     0x770d858371d0 - rustc_query_system[4ce495e28c9907d2]::query::plumbing::try_execute_query::<rustc_query_impl[c33ec4ad6556889c]::DynamicConfig<rustc_query_system[4ce495e28c9907d2]::query::caches::DefIdCache<rustc_middle[e99f9e5b138cd7e6]::query::erase::Erased<[u8; 1usize]>>, false, false, false>, rustc_query_impl[c33ec4ad6556889c]::plumbing::QueryCtxt, false>
  46:     0x770d85835d49 - rustc_query_impl[c33ec4ad6556889c]::query_impl::coherent_trait::get_query_non_incr::__rust_end_short_backtrace
  47:     0x770d85e4c61e - rustc_hir_analysis[465c838ed0c91715]::check::wfcheck::check_well_formed
  48:     0x770d85e4a3c7 - rustc_query_impl[c33ec4ad6556889c]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[c33ec4ad6556889c]::query_impl::check_well_formed::dynamic_query::{closure#2}::{closure#0}, rustc_middle[e99f9e5b138cd7e6]::query::erase::Erased<[u8; 1usize]>>
  49:     0x770d85e49b6a - rustc_query_system[4ce495e28c9907d2]::query::plumbing::try_execute_query::<rustc_query_impl[c33ec4ad6556889c]::DynamicConfig<rustc_query_system[4ce495e28c9907d2]::query::caches::VecCache<rustc_hir[5039c425fb71505b]::hir_id::OwnerId, rustc_middle[e99f9e5b138cd7e6]::query::erase::Erased<[u8; 1usize]>>, false, false, false>, rustc_query_impl[c33ec4ad6556889c]::plumbing::QueryCtxt, false>
  50:     0x770d85e498d3 - rustc_query_impl[c33ec4ad6556889c]::query_impl::check_well_formed::get_query_non_incr::__rust_end_short_backtrace
  51:     0x770d85e47841 - rustc_hir_analysis[465c838ed0c91715]::check::wfcheck::check_mod_type_wf
  52:     0x770d85e47689 - rustc_query_impl[c33ec4ad6556889c]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[c33ec4ad6556889c]::query_impl::check_mod_type_wf::dynamic_query::{closure#2}::{closure#0}, rustc_middle[e99f9e5b138cd7e6]::query::erase::Erased<[u8; 1usize]>>
  53:     0x770d860c4d46 - rustc_query_system[4ce495e28c9907d2]::query::plumbing::try_execute_query::<rustc_query_impl[c33ec4ad6556889c]::DynamicConfig<rustc_query_system[4ce495e28c9907d2]::query::caches::DefaultCache<rustc_span[add96f0181708003]::def_id::LocalModDefId, rustc_middle[e99f9e5b138cd7e6]::query::erase::Erased<[u8; 1usize]>>, false, false, false>, rustc_query_impl[c33ec4ad6556889c]::plumbing::QueryCtxt, false>
  54:     0x770d860c4aff - rustc_query_impl[c33ec4ad6556889c]::query_impl::check_mod_type_wf::get_query_non_incr::__rust_end_short_backtrace
  55:     0x770d857f1247 - rustc_hir_analysis[465c838ed0c91715]::check_crate
  56:     0x770d85be39fa - rustc_interface[4d16e32404bcb20f]::passes::analysis
  57:     0x770d85be3555 - rustc_query_impl[c33ec4ad6556889c]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[c33ec4ad6556889c]::query_impl::analysis::dynamic_query::{closure#2}::{closure#0}, rustc_middle[e99f9e5b138cd7e6]::query::erase::Erased<[u8; 1usize]>>
  58:     0x770d863b50e5 - rustc_query_system[4ce495e28c9907d2]::query::plumbing::try_execute_query::<rustc_query_impl[c33ec4ad6556889c]::DynamicConfig<rustc_query_system[4ce495e28c9907d2]::query::caches::SingleCache<rustc_middle[e99f9e5b138cd7e6]::query::erase::Erased<[u8; 1usize]>>, false, false, false>, rustc_query_impl[c33ec4ad6556889c]::plumbing::QueryCtxt, false>
  59:     0x770d863b4e49 - rustc_query_impl[c33ec4ad6556889c]::query_impl::analysis::get_query_non_incr::__rust_end_short_backtrace
  60:     0x770d862374d9 - rustc_interface[4d16e32404bcb20f]::interface::run_compiler::<core[4c074f95c636289]::result::Result<(), rustc_span[add96f0181708003]::ErrorGuaranteed>, rustc_driver_impl[5ebafc17f6baf5ac]::run_compiler::{closure#0}>::{closure#1}
  61:     0x770d86222367 - std[b1a6245f99d026e2]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[4d16e32404bcb20f]::util::run_in_thread_with_globals<rustc_interface[4d16e32404bcb20f]::util::run_in_thread_pool_with_globals<rustc_interface[4d16e32404bcb20f]::interface::run_compiler<core[4c074f95c636289]::result::Result<(), rustc_span[add96f0181708003]::ErrorGuaranteed>, rustc_driver_impl[5ebafc17f6baf5ac]::run_compiler::{closure#0}>::{closure#1}, core[4c074f95c636289]::result::Result<(), rustc_span[add96f0181708003]::ErrorGuaranteed>>::{closure#0}, core[4c074f95c636289]::result::Result<(), rustc_span[add96f0181708003]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[4c074f95c636289]::result::Result<(), rustc_span[add96f0181708003]::ErrorGuaranteed>>
  62:     0x770d8622212a - <<std[b1a6245f99d026e2]::thread::Builder>::spawn_unchecked_<rustc_interface[4d16e32404bcb20f]::util::run_in_thread_with_globals<rustc_interface[4d16e32404bcb20f]::util::run_in_thread_pool_with_globals<rustc_interface[4d16e32404bcb20f]::interface::run_compiler<core[4c074f95c636289]::result::Result<(), rustc_span[add96f0181708003]::ErrorGuaranteed>, rustc_driver_impl[5ebafc17f6baf5ac]::run_compiler::{closure#0}>::{closure#1}, core[4c074f95c636289]::result::Result<(), rustc_span[add96f0181708003]::ErrorGuaranteed>>::{closure#0}, core[4c074f95c636289]::result::Result<(), rustc_span[add96f0181708003]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[4c074f95c636289]::result::Result<(), rustc_span[add96f0181708003]::ErrorGuaranteed>>::{closure#2} as core[4c074f95c636289]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  63:     0x770d8786078b - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h51d53d77b032da76
                               at /rustc/f9b16149208c8a8a349c32813312716f6603eb6f/library/alloc/src/boxed.rs:2022:9
  64:     0x770d8786078b - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hd03902f6d1c8cd92
                               at /rustc/f9b16149208c8a8a349c32813312716f6603eb6f/library/alloc/src/boxed.rs:2022:9
  65:     0x770d8786078b - std::sys::pal::unix::thread::Thread::new::thread_start::ha033681dd3a5d038
                               at /rustc/f9b16149208c8a8a349c32813312716f6603eb6f/library/std/src/sys/pal/unix/thread.rs:108:17
  66:     0x770d810a955a - <unknown>
  67:     0x770d81126a3c - <unknown>
  68:                0x0 - <unknown>

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: please make sure that you have updated to the latest nightly

note: please attach the file at `/tmp/im/rustc-ice-2024-04-20T20_22_42-649638.txt` to your bug report

query stack during panic:
panicked at /rustc/f9b16149208c8a8a349c32813312716f6603eb6f/compiler/rustc_type_ir/src/ty_kind.rs:709:17:
thread panicked while processing panic. aborting.
[2]    649638 IOT instruction  rustc a.rs
```

</p>
</details>

### PR DESCRIPTION
**Pull request by lcnr**
r? @compiler-errors 

---

This PR stabilizes the use of the next generation trait solver in coherence checking by enabling `-Znext-solver=coherence` by default. More specifically its use in the *implicit negative overlap check*. The tracking issue for this is https://github.com/rust-lang/rust/issues/114862. Closes #114862.

### The next generation trait solver

The new solver lives in [`rustc_trait_selection::solve`](https://github.com/rust-lang/rust/blob/master/compiler/rustc_trait_selection/src/solve/mod.rs) and is intended to replace the existing *evaluate*, *fulfill*, and *project* implementation. It also has a wider impact on the rest of the type system, for example by changing our approach to handling associated types. 

For a more detailed explanation of the new trait solver, see the [rustc-dev-guide](https://rustc-dev-guide.rust-lang.org/solve/trait-solving.html). This does not stabilize the current behavior of the new trait solver, only the behavior impacting the implicit negative overlap check. There are many areas in the new solver which are not yet finalized. We are confident that their final design will not conflict with the user-facing behavior observable via coherence. More on that further down.

Please check out [the chapter](https://rustc-dev-guide.rust-lang.org/solve/significant-changes.html) summarizing the most significant changes between the existing and new implementations.

### Coherence and the implicit negative overlap check

Coherence checking detects any overlapping impls. Overlapping trait impls always error while overlapping inherent impls result in an error if they have methods with the same name. Coherence also results in an error if any other impls could exist, even if they are currently unknown. This affects impls which may get added to upstream crates in a backwards compatible way and impls from downstream crates.

Coherence failing to detect overlap is generally considered to be unsound, even if it is difficult to actually get runtime UB this way. It is quite easy to get ICEs due to bugs in coherence.

It currently consists of two checks:

The [orphan check] validates that impls do not overlap with other impls we do not know about: either because they may be defined in a sibling crate, or because an upstream crate is allowed to add it without being considered a breaking change.

The [overlap check] validates that impls do not overlap with other impls we know about. This is done as follows:
- Instantiate the generic parameters of both impls with inference variables
- Equate the `TraitRef`s of both impls. If it fails there is no overlap.
- [implicit negative]: Check whether any of the instantiated `where`-bounds of one of the impls definitely do not hold when using the constraints from the previous step. If a `where`-bound does not hold, there is no overlap.
- *explicit negative (still unstable, ignored going forward)*: Check whether the any negated `where`-bounds can be proven, e.g. a `&mut u32: Clone` bound definitely does not hold as an explicit `impl<T> !Clone for &mut T` exists.

The overlap check has to *prove that unifying the impls does not succeed*. This means that **incorrectly getting a type error during coherence is unsound** as it would allow impls to overlap: coherence has to be *complete*.

Completeness means that we never incorrectly error. This means that during coherence we must only add inference constraints if they are definitely necessary. During ordinary type checking [this does not hold](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=01d93b592bd9036ac96071cbf1d624a9), so the trait solver has to behave differently, depending on whether we're in coherence or not.

The implicit negative check only considers goals to "definitely not hold" if they could not be implemented downstream, by a sibling, or upstream in a backwards compatible way. If the goal is is "unknowable" as it may get added in another crate, we add an ambiguous candidate: [source](https://github.com/rust-lang/rust/blob/bea5bebf3defc56e5e3446b4a95c685dbb885fd3/compiler/rustc_trait_selection/src/solve/assembly/mod.rs#L858-L883).

[orphan check]: https://github.com/rust-lang/rust/blob/fd80c02c168c2dfbb82c29d2617f524d2723205b/compiler/rustc_trait_selection/src/traits/coherence.rs#L566-L579
[overlap check]: https://github.com/rust-lang/rust/blob/fd80c02c168c2dfbb82c29d2617f524d2723205b/compiler/rustc_trait_selection/src/traits/coherence.rs#L92-L98
[implicit negative]: https://github.com/rust-lang/rust/blob/fd80c02c168c2dfbb82c29d2617f524d2723205b/compiler/rustc_trait_selection/src/traits/coherence.rs#L223-L281

## Motivation

Replacing the existing solver in coherence fixes soundness bugs by removing sources of incompleteness in the type system. The new solver separately strengthens coherence, resulting in more impls being disjoint and passing the coherence check. The concrete changes will be elaborated further down. We believe the stabilization to reduce the likelihood of future bugs in coherence as the new implementation is easier to understand and reason about.

It allows us to remove the support for coherence and implicit-negative reasoning in the old solver, allowing us to remove some code and simplifying the old trait solver. We will only remove the old solver support once this stabilization has reached stable to make sure we're able to quickly revert in case any unexpected issues are detected before then.

Stabilizing the use of the next-generation trait solver expresses our confidence that its current behavior is intended and our work towards enabling its use everywhere will not require any breaking changes to the areas used by coherence checking. We are also confident that we will be able to replace the existing solver everywhere, as maintaining two separate systems adds a significant maintainance burden.

### Breakage due to improved handling of associated types

The new solver fixes multiple issues related to associated types. As these issues caused coherence to consider more types distinct, fixing them results in more overlap errors. This is therefore a breaking change.

#### Structurally relating aliases containing bound vars

Fixes https://github.com/rust-lang/rust/issues/102048. In the existing solver relating ambiguous projections containing bound variables is structural. This is *incomplete* and allows overlapping impls. These was mostly not exploitable as the same issue also caused impls to not apply when trying to use them. The new solver defers alias-relating to a nested goal, fixing this issue:
```rust
// revisions: current next
//[next] compile-flags: -Znext-solver=coherence
trait Trait {}

trait Project {
    type Assoc<'a>;
}

impl Project for u32 {
    type Assoc<'a> = &'a u32;
}

// Eagerly normalizing `<?infer as Project>::Assoc<'a>` is ambiguous,
// so the old solver ended up structurally relating
//
//     (?infer, for<'a> fn(<?infer as Project>::Assoc<'a>))
//
// with 
//
//     ((u32, fn(&'a u32)))
//
// Equating `&'a u32` with `<u32 as Project>::Assoc<'a>` failed, even
// though these types are equal modulo normalization.
impl<T: Project> Trait for (T, for<'a> fn(<T as Project>::Assoc<'a>)) {}

impl<'a> Trait for (u32, fn(&'a u32)) {}
//[next]~^ ERROR conflicting implementations of trait `Trait` for type `(u32, for<'a> fn(&'a u32))`
```

A crater run did not discover any breakage due to this change.

#### Unknowable candidates for higher ranked trait goals

This avoids an unsoundness by attempting to normalize in `trait_ref_is_knowable`, fixing https://github.com/rust-lang/rust/issues/114061. This is a side-effect of supporting lazy normalization, as that forces us to attempt to normalize when checking whether a `TraitRef` is knowable: [source](https://github.com/rust-lang/rust/blob/47dd709bedda8127e8daec33327e0a9d0cdae845/compiler/rustc_trait_selection/src/solve/assembly/mod.rs#L754-L764).

```rust
// revisions: current next
//[next] compile-flags: -Znext-solver=coherence
trait IsUnit {}
impl IsUnit for () {}


pub trait WithAssoc<'a> {
    type Assoc;
}

// We considered `for<'a> <T as WithAssoc<'a>>::Assoc: IsUnit`
// to be knowable, even though the projection is ambiguous.
pub trait Trait {}
impl<T> Trait for T
where
    T: 'static,
    for<'a> T: WithAssoc<'a>,
    for<'a> <T as WithAssoc<'a>>::Assoc: IsUnit,
{
}
impl<T> Trait for Box<T> {}
//[next]~^ ERROR conflicting implementations of trait `Trait`
```
The two impls of `Trait` overlap given the following downstream crate:
```rust
use dep::*;
struct Local;
impl WithAssoc<'_> for Box<Local> {
    type Assoc = ();
}
```

There a similar coherence unsoundness caused by our handling of aliases which is fixed separately in https://github.com/rust-lang/rust/pull/117164.

This change breaks the [`derive-visitor`](https://crates.io/crates/derive-visitor) crate. I have opened an issue in that repo: nikis05/derive-visitor#16.

### Evaluating goals to a fixpoint and applying inference constraints

In the old implementation of the implicit-negative check, each obligation is [checked separately without applying its inference constraints](https://github.com/rust-lang/rust/blob/bea5bebf3defc56e5e3446b4a95c685dbb885fd3/compiler/rustc_trait_selection/src/traits/coherence.rs#L323-L338). The new solver instead [uses a `FulfillmentCtxt`](https://github.com/rust-lang/rust/blob/bea5bebf3defc56e5e3446b4a95c685dbb885fd3/compiler/rustc_trait_selection/src/traits/coherence.rs#L315-L321) for this, which evaluates all obligations in a loop until there's no further inference progress.

This is necessary for backwards compatibility as we do not eagerly normalize with the new solver, resulting in constraints from normalization to only get applied by evaluating a separate obligation. This also allows more code to compile:
```rust
// revisions: current next
//[next] compile-flags: -Znext-solver=coherence
trait Mirror {
    type Assoc;
}
impl<T> Mirror for T {
    type Assoc = T;
}

trait Foo {}
trait Bar {}

// The self type starts out as `?0` but is constrained to `()`
// due to the where-clause below. Because `(): Bar` is known to
// not hold, we can prove the impls disjoint.
impl<T> Foo for T where (): Mirror<Assoc = T> {}
//[current]~^ ERROR conflicting implementations of trait `Foo` for type `()`
impl<T> Foo for T where T: Bar {}

fn main() {}
```
The old solver does not run nested goals to a fixpoint in evaluation. The new solver does do so, strengthening inference and improving the overlap check:
```rust
// revisions: current next
//[next] compile-flags: -Znext-solver=coherence
trait Foo {}
impl<T> Foo for (u8, T, T) {}
trait NotU8 {}
trait Bar {}
impl<T, U: NotU8> Bar for (T, T, U) {}

trait NeedsFixpoint {}
impl<T: Foo + Bar> NeedsFixpoint for T {}
impl NeedsFixpoint for (u8, u8, u8) {}

trait Overlap {}
impl<T: NeedsFixpoint> Overlap for T {}
impl<T, U: NotU8, V> Overlap for (T, U, V) {}
//[current]~^ ERROR conflicting implementations of trait `Foo`
```

### Breakage due to removal of incomplete candidate preference

Fixes #107887. In the old solver we incompletely prefer the builtin trait object impl over user defined impls. This can break inference guidance, inferring `?x` in `dyn Trait<u32>: Trait<?x>` to `u32`, even if an explicit impl of `Trait<u64>` also exists.

This caused coherence to incorrectly allow overlapping impls, resulting in ICEs and a theoretical unsoundness. See https://github.com/rust-lang/rust/issues/107887#issuecomment-1997261676. This compiles on stable but results in an overlap error with `-Znext-solver=coherence`:

```rust
// revisions: current next
//[next] compile-flags: -Znext-solver=coherence
struct W<T: ?Sized>(*const T);

trait Trait<T: ?Sized> {
    type Assoc;
}

// This would trigger the check for overlap between automatic and custom impl.
// They actually don't overlap so an impl like this should remain possible
// forever.
//
// impl Trait<u64> for dyn Trait<u32> {}
trait Indirect {}
impl Indirect for dyn Trait<u32, Assoc = ()> {}
impl<T: Indirect + ?Sized> Trait<u64> for T {
    type Assoc = ();
}

// Incomplete impl where `dyn Trait<u32>: Trait<_>` does not hold, but
// `dyn Trait<u32>: Trait<u64>` does.
trait EvaluateHack<U: ?Sized> {}
impl<T: ?Sized, U: ?Sized> EvaluateHack<W<U>> for T
where
    T: Trait<U, Assoc = ()>, // incompletely constrains `_` to `u32`
    U: IsU64,
    T: Trait<U, Assoc = ()>, // incompletely constrains `_` to `u32`
{
}

trait IsU64 {}
impl IsU64 for u64 {}

trait Overlap<U: ?Sized> {
    type Assoc: Default;
}
impl<T: ?Sized + EvaluateHack<W<U>>, U: ?Sized> Overlap<U> for T {
    type Assoc = Box<u32>;
}
impl<U: ?Sized> Overlap<U> for dyn Trait<u32, Assoc = ()> {
//[next]~^ ERROR conflicting implementations of trait `Overlap<_>`
    type Assoc = usize;
}
```

### Considering region outlives bounds in the `leak_check`

For details on the `leak_check`, see the FCP proposal in #119820.[^leak_check]

[^leak_check]: which should get moved to the dev-guide once that PR lands :3

In both coherence and during candidate selection, the `leak_check` relies on the region constraints added in `evaluate`. It therefore currently does not register outlives obligations: [source](https://github.com/rust-lang/rust/blob/ccb1415eac3289b5ebf64691c0190dc52e0e3d0e/compiler/rustc_trait_selection/src/traits/select/mod.rs#L792-L810). This was likely done as a performance optimization without considering its impact on the `leak_check`. This is the case as in the old solver, *evaluatation* and *fulfillment* are split, with evaluation being responsible for candidate selection and fulfillment actually registering all the constraints.

This split does not exist with the new solver. The `leak_check` can therefore eagerly detect errors caused by region outlives obligations. This improves both coherence itself and candidate selection:

```rust
// revisions: current next
//[next] compile-flags: -Znext-solver=coherence
trait LeakErr<'a, 'b> {}
// Using this impl adds an `'b: 'a` bound which results
// in a higher-ranked region error. This bound has been
// previously ignored but is now considered.
impl<'a, 'b: 'a> LeakErr<'a, 'b> for () {}

trait NoOverlapDir<'a> {}
impl<'a, T: for<'b> LeakErr<'a, 'b>> NoOverlapDir<'a> for T {}
impl<'a> NoOverlapDir<'a> for () {}
//[current]~^ ERROR conflicting implementations of trait `NoOverlapDir<'_>`

// --------------------------------------

// necessary to avoid coherence unknowable candidates
struct W<T>(T); 

trait GuidesSelection<'a, U> {}
impl<'a, T: for<'b> LeakErr<'a, 'b>> GuidesSelection<'a, W<u32>> for T {}
impl<'a, T> GuidesSelection<'a, W<u8>> for T {}

trait NotImplementedByU8 {}
trait NoOverlapInd<'a, U> {}
impl<'a, T: GuidesSelection<'a, W<U>>, U> NoOverlapInd<'a, U> for T {}
impl<'a, U: NotImplementedByU8> NoOverlapInd<'a, U> for () {}
//[current]~^ conflicting implementations of trait `NoOverlapInd<'_, _>`
```

### Removal of `fn match_fresh_trait_refs`

The old solver tries to [eagerly detect unbounded recursion](https://github.com/rust-lang/rust/blob/b14fd2359f47fb9a14bbfe55359db4bb3af11861/compiler/rustc_trait_selection/src/traits/select/mod.rs#L1196-L1211), forcing the affected goals to be ambiguous. This check is only an approximation and has not been added to the new solver.

The check is not necessary in the new solver and it would be problematic for caching. As it depends on all goals currently on the stack, using a global cache entry would have to always make sure that doing so does not circumvent this check.

This changes some goals to error - or succeed - instead of failing with ambiguity. This allows more code to compile:

```rust
// revisions: current next
//[next] compile-flags: -Znext-solver=coherence

// Need to use this local wrapper for the impls to be fully
// knowable as unknowable candidate result in ambiguity.
struct Local<T>(T);

trait Trait<U> {}
// This impl does not hold, but is ambiguous in the old
// solver due to its overflow approximation.
impl<U> Trait<U> for Local<u32> where Local<u16>: Trait<U> {}
// This impl holds.
impl Trait<Local<()>> for Local<u8> {}

// In the old solver, `Local<?t>: Trait<Local<?u>>` is ambiguous,
// resulting in `Local<?u>: NoImpl`, also being ambiguous.
//
// In the new solver the first impl does not apply, constraining
// `?u` to `Local<()>`, causing `Local<()>: NoImpl` to error.
trait Indirect<T> {}
impl<T, U> Indirect<U> for T
where
    T: Trait<U>,
    U: NoImpl
{}

// Not implemented for `Local<()>`
trait NoImpl {}
impl NoImpl for Local<u8> {}
impl NoImpl for Local<u16> {}

// `Local<?t>: Indirect<Local<?u>>` cannot hold, so
// these impls do not overlap.
trait NoOverlap<U> {}
impl<T: Indirect<U>, U> NoOverlap<U> for T {}
impl<T, U> NoOverlap<Local<U>> for Local<T> {}
//~^ ERROR conflicting implementations of trait `NoOverlap<Local<_>>`
```

### Non-fatal overflow

The old solver immediately emits a fatal error when hitting the recursion limit. The new solver instead returns overflow. This both allows more code to compile and is results in performance and potential future compatability issues.

Non-fatal overflow is generally desirable. With fatal overflow, changing the order in which we evaluate nested goals easily causes breakage if we have goal which errors and one which overflows. It is also required to prevent breakage due to the removal of `fn match_fresh_trait_refs`, e.g. [in `typenum`](https://github.com/rust-lang/trait-system-refactor-initiative/issues/73).

#### Enabling more code to compile

In the below example, the old solver first tried to prove an overflowing goal, resulting in a fatal error. The new solver instead returns ambiguity due to overflow for that goal, causing the implicit negative overlap check to succeed as `Box<u32>: NotImplemented` does not hold.
```rust
// revisions: current next
//[next] compile-flags: -Znext-solver=coherence
//[current] ERROR overflow evaluating the requirement

trait Indirect<T> {}
impl<T: Overflow<()>> Indirect<T> for () {}

trait Overflow<U> {}
impl<T, U> Overflow<U> for Box<T>
where
    U: Indirect<Box<Box<T>>>,
{}

trait NotImplemented {}

trait Trait<U> {}
impl<T, U> Trait<U> for T
where
    // T: NotImplemented, // causes old solver to succeed
    U: Indirect<T>,
    T: NotImplemented,
{}

impl Trait<()> for Box<u32> {}
```

#### Avoiding hangs with non-fatal overflow

Simply returning ambiguity when reaching the recursion limit can very easily result in hangs, e.g.
```rust
trait Recur {}
impl<T, U> Recur for ((T, U), (U, T))
where
    (T, U): Recur,
    (U, T): Recur,
{}

trait NotImplemented {}
impl<T: NotImplemented> Recur for T {}
```
This can happen quite frequently as it's easy to have exponential blowup due to multiple nested goals at each step. As the trait solver is depth-first, this immediately caused a fatal overflow error in the old solver. In the new solver we have to handle the whole proof tree instead, which can very easily hang.

To avoid this we restrict the recursion depth after hitting the recursion limit for the first time. We also **ignore all inference constraints from goals resulting in overflow**. This is mostly backwards compatible as any overflow in the old solver resulted in a fatal error.

### sidenote about normalization

We return ambiguous nested goals of `NormalizesTo` goals to the caller and ignore their impact when computing the `Certainty` of the current goal. See the [normalization chapter](https://rustc-dev-guide.rust-lang.org/solve/normalization.html) for more details.This means we apply constraints resulting from other nested goals and from equating the impl header when normalizing, even if a nested goal results in overflow. This is necessary to avoid breaking the following example:
```rust
trait Trait {
    type Assoc;
}

struct W<T: ?Sized>(*mut T);
impl<T: ?Sized> Trait for W<W<T>>
where
    W<T>: Trait,
{
    type Assoc = ();
}

// `W<?t>: Trait<Assoc = u32>` does not hold as
// `Assoc` gets normalized to `()`. However, proving
// the where-bounds of the impl results in overflow.
//
// For this to continue to compile we must not discard
// constraints from normalizing associated types.
trait NoOverlap {}
impl<T: Trait<Assoc = u32>> NoOverlap for T {}
impl<T: ?Sized> NoOverlap for W<T> {}
```

#### Future compatability concerns

Non-fatal overflow results in some unfortunate future compatability concerns. Changing the approach to avoid more hangs by more strongly penalizing overflow can cause breakage as we either drop constraints or ignore candidates necessary to successfully compile. Weakening the overflow penalities instead allows more code to compile and strengthens inference while potentially causing more code to hang.

While the current approach is not perfect, we believe it to be good enough. We believe it to apply the necessary inference constraints to avoid breakage and expect there to not be any desirable patterns broken by our current penalities. Similarly we believe the current constraints to avoid most accidental hangs. Ignoring constraints of overflowing goals is especially useful, as it may allow major future optimizations to our overflow handling. See [this summary](https://hackmd.io/ATf4hN0NRY-w2LIVgeFsVg) and the linked documents in case you want to know more.

### changes to performance

In general, trait solving during coherence checking is not significant for performance. Enabling the next-generation trait solver in coherence does not impact our compile time benchmarks. We are still unable to compile the benchmark suite when fully enabling the new trait solver.

There are rare cases where the new solver has significantly worse performance due to non-fatal overflow, its reliance on fixpoint algorithms and the removal of the `fn match_fresh_trait_refs` approximation. We encountered such issues in [`typenum`](https://crates.io/crates/typenum) and believe it should be [pretty much as bad as it can get](https://github.com/rust-lang/trait-system-refactor-initiative/issues/73).

Due to an improved structure and far better caching, we believe that there is a lot of room for improvement and that the new solver will outperform the existing implementation in nearly all cases, sometimes significantly. We have not yet spent any time micro-optimizing the implementation and have many unimplemented major improvements, such as fast-paths for trivial goals.

TODO: get some rough results here and put them in a table

#### Unsupported unstable features

The new solver currently does not support all unstable features, most notably `#![feature(generic_const_exprs)]`, `#![feature(associated_const_equality)]` and `#![feature(adt_const_params)]` are not yet fully supported in the new solver. We are confident that supporting them is possible, but did not consider this to be a priority. This stabilization introduces new ICE when using these features in impl headers.

#### fixes to `#![feature(specialization)]`

- fixes #105782 
- fixes #118987

#### fixes to `#![feature(type_alias_impl_trait)]`

- fixes #119272
- https://github.com/rust-lang/rust/issues/105787#issuecomment-1750112388
- fixes #124207

## This does not stabilize the whole solver

While this stabilizes the use of the new solver in coherence checking, there are many parts of the solver which will remain fully unstable. We may still adapt these areas while working towards stabilizing the new solver everywhere. We are confident that we are able to do so without negatively impacting coherence.

### goals with a non-empty `ParamEnv`

Coherence always uses an empty environment. We therefore do not depend on the behavior of `AliasBound` and `ParamEnv` candidates. We only stabilizes the behavior of user-defined and builtin implementations of traits. There are still many open questions there.

### opaque types in the defining scope

The handling of opaque types - `impl Trait` - in both the new and old solver is still not fully figured out. Luckily this can be ignored for now. While opaque types are reachable during coherence checking by using `impl_trait_in_associated_types`, the behavior during coherence is separate and self-contained. The old and new solver fully agree here.

### normalization is hard

This stabilizes that we equate associated types involving bound variables using deferred-alias-equality. We also stop eagerly normalizing in coherence, which should not have any user-facing impact.

We do not stabilize the normalization behavior outside of coherence, e.g. we currently deeply normalize all types during writeback with the new solver. This may change going forward 

### how to replace `select` from the old solver

We sometimes depend on getting a single `impl` for a given trait bound, e.g. when resolving a concrete method for codegen/CTFE. We do not depend on this during coherence, so the exact approach here can still be freely changed going forward.

## Acknowledgements

This work would not have been possible without @compiler-errors. He implemented large chunks of the solver himself but also and did a lot of testing and experimentation, eagerly discovering multiple issues which had a significant impact on our approach. @BoxyUwU has also done some amazing work on the solver. Thank you for the endless hours of discussion resulting in the current approach. Especially the way aliases are handled has gone through multiple revisions to get to its current state.

There were also many contributions from - and discussions with - other members of the community and the rest of @rust-lang/types. This solver builds upon previous improvements to the compiler, as well as lessons learned from `chalk` and `a-mir-formality`. Getting to this point  would not have been possible without that and I am incredibly thankful to everyone involved. See the [list of relevant PRs](https://github.com/rust-lang/rust/pulls?q=is%3Apr+is%3Amerged+label%3AWG-trait-system-refactor+-label%3Arollup+closed%3A%3C2024-03-22+).

### CODE REVIEW

**Comment by lcnr** [comment]
rebased on top of #121853 :sweat_smile: 

@bors try @rust-timer queue

**Comment by matthiaskrgr** [comment]
I'm somewhat worried because we still have a bunch of ICEs related to next-solver=coherence

https://github.com/rust-lang/rust/issues?q=is%3Aissue+is%3Aopen+label%3AI-ICE+%22%3Dcoherence%22++%22solver%22+

**Comment by compiler-errors** [comment]
@matthiaskrgr: Almost all of those are related to consts, and I'm not particularly concerned with users hitting these in production. None of them, as far as I am aware, are of the "pass -> ICE", so @lcnr and I will fix them in due time.

**Comment by lcnr** [comment]
@craterbot check

**Comment by lcnr** [comment]
one ICE as `associated_const_equality` is not yet supported in the new solver

one failure due to https://github.com/rust-lang/rust/issues/114061 and one due to `paperclip-core-0.6.2`, have to  look into that

**Comment by lcnr** [comment]
I am unable to reproduce the `paperclip-core` regression :/

@bors try

**Comment by lcnr** [comment]
rebased over #122687 which fixes the regression in `paperclip-core`.

@bors try

**Comment by matthiaskrgr** [comment]
latest regressions:
https://github.com/rust-lang/rust/issues/122861
https://github.com/rust-lang/rust/issues/121006

**Comment by lcnr** [comment]
While I don't expect this to be the case, https://github.com/rust-lang/rust/pull/122687 may also result in some unexpected breakage, so lets make sure it doesn't by rerunning crater completely instead of only for the affected crates.

@craterbot check

Regardless, I don't expect any new regressions here. I looked at the new issues provided by @matthiaskrgr (thank you for finding them!) and believe both to not require any major changes to the new solver. With this:

cc @rust-lang/lang @rust-lang/compiler @rust-lang/compiler-contributors. The FCP is limited to `T-types` but I very much appreciate any feedback, questions, or issues here.

@rfcbot fcp merge

**Comment by lcnr** [comment]
given the impact of this change I think it's important to have the whole team on-board here.

@rfcbot concern full-team signoff

**Review by compiler-errors — APPROVED** [review]
Anywho r=me when FCP is over

**Comment by jackh726** [comment]
This is incredibly impressive and I'm so proud to see this stabilization move forward (and its indication on the progress of the new trait solver). Big kudos to all those that have put work into this, but particularly @lcnr and @compiler-errors.

@rfcbot reviewed

**Comment by nikomatsakis** [comment]
@rfcbot reviewed

I am very excited to see this moving forward!

**Comment by BoxyUwU** [comment]
@rfcbot concern I would like us to change `normalizes-to` to be 0 to inf steps of normalization rather than one step norm as it is rn before we stabilize this. i.e. solve rust-lang/trait-system-refactor-initiative#103 by making `NormalizesTo` normalize the alias until it is rigid instead of just inferring the term to be what is written syntactically in the resolved impl. mostly just to be completely certain that it wont break anything to do, and it should be relatively simple to make this change so hopefully wont block this for long

**Comment by BoxyUwU** [comment]
I'm really happy to see this happen. The written material for this FCP (PR description) is outstanding thank you for putting so much effort into it <3

**Comment by lcnr** [comment]
@BoxyUwU and I discussed that at RustNation and we're in agreement that this change is desirable. It will not have any meaningful observable impact but feels a bit cleaner and also avoids the as of yet purely theoretical issue from https://github.com/rust-lang/trait-system-refactor-initiative/issues/103.

Will likely implement this this week.

**Comment by lcnr** [comment]
gdi :sweat_smile: crater actually used the wrong try build :thinking: 

@craterbot check build=fc22045

**Comment by lcnr** [comment]
@craterbot run start=master#47dd709bedda8127e8daec33327e0a9d0cdae845 end=try#5685c45 mode=check

**Comment by lcnr** [comment]
@craterbot run start=master#47dd709bedda8127e8daec33327e0a9d0cdae845 end=try#5685c45 mode=check-only

**Comment by lcnr** [comment]
@craterbot cancel

**Comment by lcnr** [comment]
@craterbot run start=master#47dd709 end=try#5685c45 mode=check-only

**Comment by lcnr** [comment]
@craterbot cancel

actually, going to first handle the concern from @BoxyUwU and then do a new crater run xx

**Comment by lcnr** [comment]
gdi, sorry :cry: 

@bors try @rust-timer queue

`typenum` is now part of perf, so lets use this to get some accurate data on just how horrible it is

**Comment by lcnr** [comment]
@rfcbot resolve full-team signoff

**Comment by lcnr** [comment]
(the change to normalizes-to has been implemented in #123363)

**Comment by lcnr** [comment]
as mentioned in the tracking issue, typenum hits a worse case performance issue of the new solver, bitmaps looks spurious as this should not impact anything apart from coherence

**Review by compiler-errors — APPROVED** [review]
This represents a really important step in improving Rust's soundness story. I'm glad we could get here in under a couple of years.

Thanks a lot of @lcnr and @BoxyUwU in particular and all of types and those who work with the team in general :3

**Comment by compiler-errors** [comment]
bors has been a bit slow today so let's see 

@bors r+ rollup=never

**Comment by lqd** [comment]
Should the breakages be mentioned in the relnotes?

**Comment by compiler-errors** [comment]
needs bless, r=me after

@bors r-

File: tests/crashes/119272.rs [hunk 1]
```diff
@@ -1,27 +0,0 @@
...
-}
-
-impl<T> Trait<T> for T {
-    type Assoc = Box<u32>;
-}
-impl<T> Trait<T> for defining_scope::Alias<T> {
-    type Assoc = usize;
-}
-
-fn main() {}
```
Comment (matthiaskrgr) [inline tests/crashes/119272.rs:27]: Could you please put something like  Fixes #abcde   into the commit message so that the corresponding tickets are closed automatically? Thx!

**Review by matthiaskrgr — CHANGES_REQUESTED** [review]

File: tests/crashes/119272.rs (hunk 1 above)
Comment (WaffleLapkin) [reply tests/crashes/119272.rs:27]: IIRC putting them into the PR is generally better, because that way GH spams less with cross references

Comment (matthiaskrgr) [reply tests/crashes/119272.rs:27]: :+1: or that, sure :)

Comment (lcnr) [reply tests/crashes/119272.rs:27]: I put them into the PR description 😁

**Comment by lcnr** [comment]
(going to wait until the beta branch on the 26th before merging)

**Comment by lcnr** [comment]
@craterbot check

**Comment by compiler-errors** [comment]
@craterbot run mode=check-only start=master#c2f2db79ca3024f68d22b45aa22b570775c2c4ad end=try#62bea82643539453fcd8c87a239097a4d47472ff

**Comment by jackh726** [comment]
Seems like `derive-visitor` is real (but correct?):
```
[INFO] [stdout] error[E0119]: conflicting implementations of trait `Drive` for type `Box<_>`
[INFO] [stdout]    --> src/lib.rs:562:1
[INFO] [stdout]     |
[INFO] [stdout] 534 | / impl<T> Drive for T
[INFO] [stdout] 535 | |     where
[INFO] [stdout] 536 | |         T: 'static,
[INFO] [stdout] 537 | |     // HRTB, because this needs to be true for late-bound lifetimes,
[INFO] [stdout] 538 | |     // as both &self and &visitor have anonymous lifetimes.
[INFO] [stdout] 539 | |         for<'a> &'a T: IntoIterator,
[INFO] [stdout] 540 | |         for<'a> <&'a T as IntoIterator>::Item: DerefAndDrive,
[INFO] [stdout]     | |_____________________________________________________________- first implementation here
[INFO] [stdout] ...
[INFO] [stdout] 562 |   impl<T> Drive for Box<T> where T: Drive {
[INFO] [stdout]     |   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ conflicting implementation for `Box<_>`
[INFO] [stdout]     |
[INFO] [stdout]     = note: downstream crates may implement trait `std::iter::Iterator` for type `&'a std::boxed::Box<_>`
```

`ink-feather-org.bounded_math` is error to ICE. Probably an easy enough fix but not blocking.

`pyella-0.1.5` also seems real but correct?

**Comment by lcnr** [comment]
`ink-feather-org.bounded_math` is also due to

> error: internal compiler error: compiler/rustc_trait_selection/src/solve/normalizes_to/mod.rs:277:25: associated const projection is not supported yet

which is currently not support

**Comment by lcnr** [comment]
`pyella-0.1.5` compiles with the old solver by accident, going to write a more general fix in #124532. I would personally like to land this PR without waiting on that separate FCP however to give us the maximum amount of time on nightly

**Comment by jackh726** [comment]
@lcnr can you make sure tests for the crater regressions make it as tests in this PR? (Or a separate PR to land before this)

**Comment by lcnr** [comment]
added tests from https://github.com/rust-lang/rust/pull/124532.

@bors r=compiler-errors rollup=never

**Comment by matthiaskrgr** [comment]
@bors r-
https://github.com/rust-lang-ci/rust/actions/runs/8918744232/job/24493839585#step:26:3741

**Comment by lcnr** [comment]
quick update: the new solver currently hangs in fuchsia. This hang is caused by some exponential blowup when encountering large trait solver cycles while checking `Send` bounds. These hangs exists due to us rerunning these cycles until their results reaches a fixpoint.

I've been playing with some approaches to improve caching inside of trait solver cycles and was able to get it to compile, even if it's still slower than with the old solver. I have a better approach in mind I wasn't yet able to implement. I am fairly confident that this will get us closer to the performance of the old solver and will allow us to finally merge this.

We separately continued to work on enabling the new solver everywhere. As part of this work we landed #125413 which slightly weakens the leak check. Will elaborate on its impact and do another crater run before merging this PR. I am quite certain that this change will not cause breakage.

**Comment by lcnr** [comment]
The optimizations added in #128828 should fix the hang in Fuchsia. I intend to merge this PR after another crater and perf run right after the next beta cutoff, so at the start of September.

**Comment by lcnr** [comment]
let's start with testing Fuchsia again, already did this in #129025 but I really want to make sure it's actually working now :sweat_smile: :sparkles: 

@bors try

**Comment by lcnr** [comment]
*gamer*

now for perf + crater

@bors try @rust-timer queue

**Comment by lcnr** [comment]
Interesting that it now also impacts bitmaps, regex, and diesel while it didn't before :thinking: 

@craterbot check

**Comment by lcnr** [comment]
last commit is only for perf for now

@bors try @rust-timer queue

**Comment by lcnr** [comment]
- https://github.com/rust-lang/rust/pull/128828 fixed the hang in Fuchsia, while the optimization in the WIP commit 82ecfc3c3ac41d4b9296747c44267bc30f5ba2e5 removes the significant performance regression in `typenum`.
- #127574 fixes the regression in `pyella`.

With this there are no remaining known performance issues or unintended breakage. As it has been a while since the original FCP I want to make sure @rust-lang/types is still on-board with landing this in version 1.83. I intend to merge this right after the [next beta-cutoff](https://forge.rust-lang.org/#current-release-versions) to get the most exposure possible. Nominating for visibility 😊

**Comment by lqd** [comment]
Incredible job @lcnr and @compiler-errors and everyone who helped.

**Comment by lqd** [comment]
`deep-vector` looks like a rollercoaster rn so let's ignore it.

image

I don't believe we need to bother looking into the others:
- they are pretty small in scale, and only in a handful of benchmarks
- this PR fixes multiple unsoundness issues in coherence
- the new solver has not been fully optimized yet (though lcnr's has done heroics on the search graph)

@rustbot label: +perf-regression-triaged
