### PR TITLE
Deny associated type bindings within associated type bindings

### LINKED ISSUE #102335: Compiler accepts const equality bound involving nonsensical nested equality constraint on associated const
I expect the following code to be rejected by the compiler but it is actually accepted and compiles successfully:

```rust
#![feature(associated_const_equality)]
#![crate_type = "lib"]

trait T {
    type A: S<C<i32 = u64> = 34>;
    //         ^^^^^^^^^^^ this should not be permitted but it is
}

trait S {
    const C: i32;
}
```

The associated constant `S::C` does not have any generic parameters / associated items (constants cannot have those anyways in the current version of Rust) and thus the argument list `<i32 = u64>` should be flagged as erroneous. Interestingly, if you remove the ` = u64`, the compiler correctly identifies this as an error: `this associated constant takes 0 generic arguments but 1 generic argument was supplied`.

I *think* `i32 = u64` is to be interpreted as a nested equality constraint (and not as a “defaulted” parameter, i.e. a parameter with a default value).

### Meta

`rustc -Vv`:
```
rustc 1.66.0-nightly (9062b780b 2022-09-21)
binary: rustc
commit-hash: 9062b780b32d2eab060b4432863e085d9504ca5c
commit-date: 2022-09-21
host: x86_64-unknown-linux-gnu
release: 1.66.0-nightly
LLVM version: 15.0.0
```

@rustbot label T-compiler requires-nightly
~~I would label this with <kbd>F-associated_const_equality</kbd> but sadly that label does not exist.~~ (it now does)
Hence, I am just going to mention its tracking issue: #92827.

CC @JulianKnodt

### PR DESCRIPTION
**Pull request by compiler-errors**
Fixes #102335

This was made worse by #100865, which unified the way we generate substs for GATs and non-generic associated types. However, the issue was not _caused_ by #100865, evidenced by the test I added for GATs:

```rust
trait T {
    type A: S<C<(), i32 = ()> = ()>;
    //~^ ERROR associated type bindings are not allowed here
}

trait Q {}

trait S {
    type C<T>: Q;
}

fn main() {}
```

^ which passes on beta (where GATs are stable) and presumably ever since GATs support was added to `create_substs_for_associated_item` in astconv.

### CODE REVIEW

**Comment by fmease** [comment]
> which passes on beta (where GATs are stable)

Does this mean we should backport this PR to beta?

**Comment by compiler-errors** [comment]
Probably.

File: compiler/rustc_hir_analysis/src/astconv/mod.rs [hunk 1]
```diff
@@ -595,16 +595,22 @@ impl<'o, 'tcx> dyn AstConv<'tcx> + 'o {
...
             item_segment,
             item_segment.args(),
             item_segment.infer_args,
             None,
-        )
-        .0
+        );
+
+        let assoc_bindings = self.create_assoc_bindings_for_generic_args(item_segment.args());
+        if let Some(b) = assoc_bindings.first() {
```
Comment (cjgillot) [inline compiler/rustc_hir_analysis/src/astconv/mod.rs:609]: I seems wasteful to convert all bindings, just to err on the first one later.  This could as well be implemented as
`if let Some(b) = item_segment.args().bindings.first()`
Probably better as a follow-up, as there are several instances of this pattern in the file.

**Comment by matthiaskrgr** [comment]
The test crashes in rustdoc apparently :sweat_smile:  https://github.com/rust-lang/rust/issues/102467

**Comment by apiraino** [comment]
Beta backport accepted as per compiler team [on Zulip](https://rust-lang.zulipchat.com/#narrow/stream/238009-t-compiler.2Fmeetings/topic/.5Bweekly.5D.202022-09-29/near/301452451)

@rustbot label +beta-accepted
