### PR TITLE
Suggest `if let x = y` when encountering `if x = y`

### LINKED ISSUE #44990: Suggest `if let` when a failed `if` block could be parsed as one
When writing `if Some(x) = foo {}`, attempt to parse as `if let Some(x) = foo {}` for better diagnostic output and if successful provide a suggestion to add the `let`.

### PR DESCRIPTION
**Pull request by estebank**
Detect potential cases where `if let` was meant but `let` was left out.

Fix #44990.

### CODE REVIEW

File: src/librustc_resolve/late.rs [hunk 1]
```diff
@@ -378,6 +378,16 @@ struct DiagnosticMetadata<'ast> {
 
     /// Only used for better errors on `let <pat>: <expr, not type>;`.
     current_let_binding: Option<(Span, Option<Span>, Option<Span>)>,
+
+    /// State used to know whether to ignore resolution errors for function bodies.
+    ///
+    /// In particular, rustdoc uses this to avoid giving errors for `cfg()` items.
+    /// In most cases this will be `None`, in which case errors will always be reported.
+    /// If it is `Some(_)`, then it will be updated when entering a nested function or trait body.
```
Comment (lcnr) [inline src/librustc_resolve/late.rs:386]: `Some(_)` for type `bool`

**Review by lcnr — APPROVED** [review]

File: src/librustc_resolve/late.rs (hunk 1 above)
Comment (estebank) [reply src/librustc_resolve/late.rs:386]: This is moved code, but good catch.

File: src/librustc_resolve/late.rs [hunk 2]
```diff
@@ -378,6 +378,16 @@ struct DiagnosticMetadata<'ast> {
 
     /// Only used for better errors on `let <pat>: <expr, not type>;`.
     current_let_binding: Option<(Span, Option<Span>, Option<Span>)>,
+
+    /// State used to know whether to ignore resolution errors for function bodies.
+    ///
+    /// In particular, rustdoc uses this to avoid giving errors for `cfg()` items.
+    /// In most cases this will be `None`, in which case errors will always be reported.
+    /// If it is `true`, then it will be updated when entering a nested function or trait body.
+    in_func_body: bool,
```
Comment (jyn514) [inline src/librustc_resolve/late.rs:387]: Any reason this was moved out of `LateResolutionVisitor`?

Comment (estebank) [reply src/librustc_resolve/late.rs:387]: This Boolean seems to only affect diagnostics, right? Reading it again it might affect _success_ of compilation. In that case I shouldn't have moved it.

I try to segregate metadata only used for diagnostics out of the main structs to make it easier at a glance to differentiate them.

Comment (jyn514) [reply src/librustc_resolve/late.rs:387]: Yeah this affects behavior, not just diagnostics. I'd prefer it be left where it was, the PR adding it was a little fragile: https://github.com/rust-lang/rust/pull/73566

Comment (estebank) [reply src/librustc_resolve/late.rs]: done

File: compiler/rustc_resolve/src/late.rs [hunk 3]
```diff
@@ -2199,7 +2202,10 @@ impl<'a, 'b, 'ast> LateResolutionVisitor<'a, 'b, 'ast> {
 
             ExprKind::If(ref cond, ref then, ref opt_else) => {
                 self.with_rib(ValueNS, NormalRibKind, |this| {
+                    let old = this.diagnostic_metadata.in_if_condition;
+                    this.diagnostic_metadata.in_if_condition = Some(cond);
```
Comment (petrochenkov) [inline compiler/rustc_resolve/src/late.rs:2206]:
```suggestion
                    let old = this.diagnostic_metadata.in_if_condition.replace(cond);
```

File: compiler/rustc_session/src/session.rs [hunk 4]
```diff
@@ -213,6 +213,9 @@ pub struct Session {
 
     known_attrs: Lock<MarkedAttrs>,
     used_attrs: Lock<MarkedAttrs>,
+
+    /// `Span`s for `if` conditions that we have suggested turning into `if let`.
+    pub if_let_suggestions: Lock<FxHashSet<Span>>,
```
Comment (petrochenkov) [inline compiler/rustc_session/src/session.rs:218]: @matklad, see?
https://github.com/rust-lang/rust/pull/75516#issuecomment-674277023

File: compiler/rustc_session/src/session.rs [hunk 5]
```diff
@@ -1354,6 +1357,7 @@ pub fn build_session(
         target_features: FxHashSet::default(),
         known_attrs: Lock::new(MarkedAttrs::new()),
         used_attrs: Lock::new(MarkedAttrs::new()),
+        if_let_suggestions: Lock::new(Default::default()),
```
Comment (petrochenkov) [inline compiler/rustc_session/src/session.rs:1360]:
```suggestion
        if_let_suggestions: Default::default(),
```

Comment (estebank) [reply compiler/rustc_session/src/session.rs:1360]: Should I do this change for all the other cases above?

Comment (estebank) [reply compiler/rustc_session/src/session.rs]: Done (only for this one line).
