### PR TITLE
Test case for borrowk ICE #25579

### LINKED ISSUE #25579: Random ICE when playing with match
On Rust 1.0

```Rust
#[derive(Debug)]
enum Sexpression {
  Id(String),
  Num(f64),
  Cons(Box<(Sexpression, Sexpression)>)
}

fn mutate_each_float<F>(l: &mut Sexpression, f: &mut F)
    where F: FnMut(&mut f64)
{
    let mut l = l;
    loop { match l {
        &mut Sexpression::Id(..) => {},
        &mut Sexpression::Num(ref mut n) => f(n),
        &mut Sexpression::Cons(ref mut expr) => {
            let &mut (ref mut car, ref mut cdr) = &mut **expr;
            mutate_each_float(cdr, f);
            l = car;
        }
    }}
}

fn main() {
}
```

```
error: internal compiler error: unexpected panic
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
note: run with `RUST_BACKTRACE=1` for a backtrace
thread 'rustc' panicked at 'assertion failed: `(left == right)` (left: `TyS { sty: ty_float(f64), flags: 0, region_depth: 0 }`, right: `TyS { sty: ty_uniq(TyS { sty: ty_tup([TyS { sty: ty_enum(DefId { krate: 0, node: 4 }, Substs { types: VecPerParamSpace {TypeSpace: [], SelfSpace: [], FnSpace: [], }, regions: NonerasedRegions(VecPerParamSpace {TypeSpace: [], SelfSpace: [], FnSpace: [], }) }), flags: 0, region_depth: 0 }, TyS { sty: ty_enum(DefId { krate: 0, node: 4 }, Substs { types: VecPerParamSpace {TypeSpace: [], SelfSpace: [], FnSpace: [], }, regions: NonerasedRegions(VecPerParamSpace {TypeSpace: [], SelfSpace: [], FnSpace: [], }) }), flags: 0, region_depth: 0 }]), flags: 0, region_depth: 0 }), flags: 0, region_depth: 0 }`)', /home/rustbuild/src/rust-buildbot/slave/stable-dist-rustc-linux/build/src/librustc_borrowck/borrowck/mod.rs:438
```

### PR DESCRIPTION
**Pull request by imjacobclark**
r? @nikomatsakis

Fixes #25579

### CODE REVIEW

File: src/test/run-pass/issue-25579.rs [hunk 1]
```diff
@@ -0,0 +1,27 @@
...
+// option. This file may not be copied, modified, or distributed
+// except according to those terms.
+
+enum Sexpression {
+  Num(()),
+  Cons(&'static mut Sexpression)
+}
+
+fn causes_ice(mut l: &mut Sexpression)
+{
```
Comment (oli-obk) [inline src/test/run-pass/issue-25579.rs]: style guide says the `{` needs to be on the previous line

File: src/test/run-pass/issue-25579.rs [hunk 2]
```diff
@@ -0,0 +1,27 @@
...
+//
+// Licensed under the Apache License, Version 2.0 <LICENSE-APACHE or
+// http://www.apache.org/licenses/LICENSE-2.0> or the MIT license
+// <LICENSE-MIT or http://opensource.org/licenses/MIT>, at your
+// option. This file may not be copied, modified, or distributed
+// except according to those terms.
+
+enum Sexpression {
+  Num(()),
+  Cons(&'static mut Sexpression)
```
Comment (oli-obk) [inline src/test/run-pass/issue-25579.rs]: should be an indentation of 4 spaces

File: src/test/run-pass/issue-25579.rs (hunk 1 above)
Comment (nikomatsakis) [inline src/test/run-pass/issue-25579.rs]: Hmm. I don't agree with this in particular -- we follow various conventions in the compiler :) -- but also this is a test case, where the conventions are looser still, particularly since this is a regression test.

That said, I don't see any harm in reformatting either.

Comment (imjacobclark) [inline src/test/run-pass/issue-25579.rs]: I have reformatted the code above, I think it makes sense to have it indented 4 spaces and the brace on the same line as the if statment, consistent with the rest of the file anyway. 

I need to resolve the failed build then hopefully this should be good to go.
