### PR TITLE
Tweak incorrect assoc item note

### LINKED ISSUE #142797: Inaccurate diagnostic when using associated type as a value
### Code

```Rust
struct SomeStruct {
    some_field: u64,
}

trait SomeTrait {
    type SomeType;
    fn foo();
}

impl SomeTrait for bool {
    type SomeType = SomeStruct;

    fn foo() {
        let ss = Self::SomeType;
    }
}

fn main() { }
```

### Current output

```Shell
error[E0599]: no associated item named `SomeType` found for type `bool` in the current scope
  --> test_assoc.rs:14:24
   |
14 |         let ss = Self::SomeType;
   |                        ^^^^^^^^ associated item not found in `bool`

error: aborting due to 1 previous error

For more information about this error, try `rustc --explain E0599`.
```

### Desired output

```Shell

```

### Rationale and extra context

The error says there is no associated item named `SomeType`, but this is not true, since (as I understand it) the technical definition of "associated item" includes associated types. I'm not sure what the ideal error message would be, maybe `expected value, found associated type` (i.e., E0423)?

### Other cases

```Rust

```

### Rust Version

```Shell
rustc 1.89.0-nightly (255aa2208 2025-06-19)
binary: rustc
commit-hash: 255aa220821c05c3eac7605fce4ea1c9ab2cbdb4
commit-date: 2025-06-19
host: aarch64-apple-darwin
release: 1.89.0-nightly
LLVM version: 20.1.7
```

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by JohnTitor**
Fix rust-lang/rust#142797
r? @fmease

### CODE REVIEW

File: compiler/rustc_hir_typeck/src/method/suggest.rs [hunk 1]
```diff
@@ -1176,10 +1176,24 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
         let mut ty_file = None;
         let mode = no_match_data.mode;
         let is_method = mode == Mode::MethodCall;
+        let has_self_assoc_type = if let SelfSource::QPath(ty) = source
+            && let hir::TyKind::Path(hir::QPath::Resolved(_, path)) = ty.kind
+            && let Res::SelfTyAlias { alias_to: impl_def_id, .. } = path.res
+            && let DefKind::Impl { .. } = self.tcx.def_kind(impl_def_id)
```
Comment (fmease) [inline compiler/rustc_hir_typeck/src/method/suggest.rs]: While this does nicely detect the scenario in issue #142797, it's not very general. E.g., it obviously doesn't account for:

```rs
struct Struct;

trait Trait { type AssocStruct; }
impl Trait for i32 { type AssocStruct = Struct; }

fn main() { let _ = i32::AssocStruct; } //~ ERROR no associated item … found …
```

File: tests/ui/associated-types/associated-type-as-value-in-impl-issue-142797.rs [hunk 2]
```diff
@@ -0,0 +1,23 @@
+// issue: <https://github.com/rust-lang/rust/issues/142797>
+
+#![allow(dead_code, unused_variables)]
+
```
Comment (fmease) [inline tests/ui/associated-types/associated-type-as-value-in-impl-issue-142797.rs]:
```suggestion
```

Compiletest already automatically adds `-Aunused` to UI tests (unless they're `run-{pass,crash}`) which implies `dead_code` and `unused_variables`.

File: compiler/rustc_hir_typeck/src/method/suggest.rs
Comment (fmease) [inline compiler/rustc_hir_typeck/src/method/suggest.rs]: I'm wondering if we should just unconditionally talk about *associated function or constant* instead of *associated item* because that's actually the truth, `rustc_hir_typeck::method` looks for assoc fns, assoc consts & enum variants, not assoc items in general.

Then we wouldn't need to check for the presence of assoc tys which is rather ad hoc.

* `variant or associated item` → `variant, associated function or constant`
* `function or associated item`, `associated item` → `associated function or constant`

I know it's slightly lengthier but *associated item* is strictly speaking incorrect. @estebank, I'd also like to hear what you think about this proposal :)

**Review by fmease — COMMENTED** [review]
Sorry about the delay.

*[View changes since this review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/rust/152880/ef70767064ab87b0a41400f69e1dc0b55c8d5284..2fe5590ff0089bfecd171b253f8cd77c8faf7bf6)*

File: compiler/rustc_hir_typeck/src/method/suggest.rs (hunk 1 above)
Comment (JohnTitor) [reply compiler/rustc_hir_typeck/src/method/suggest.rs]: Makes sense, fixed along with the below comment: https://github.com/rust-lang/rust/pull/152880/changes/5a0eccfca499182ff33a303dcf89daac3f19b339

File: tests/ui/associated-types/associated-type-as-value-in-impl-issue-142797.rs (hunk 2 above)
Comment (JohnTitor) [reply tests/ui/associated-types/associated-type-as-value-in-impl-issue-142797.rs]: I always forgot to remove them on copy-pasting from the playground... Fixed in https://github.com/rust-lang/rust/pull/152880/changes/5a0eccfca499182ff33a303dcf89daac3f19b339.

File: compiler/rustc_hir_typeck/src/method/suggest.rs
Comment (JohnTitor) [reply compiler/rustc_hir_typeck/src/method/suggest.rs]: Fair enough, aligned to your proposal in https://github.com/rust-lang/rust/pull/152880/changes/5a0eccfca499182ff33a303dcf89daac3f19b339. Would like to know Esteban's view as well.

**Review by fmease — APPROVED** [review]
Let's try this. r=me
@bors rollup

*[View changes since this review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/rust/152880/052b9c23daccef254010e43d6c4d0a5459caec5b..5a0eccfca499182ff33a303dcf89daac3f19b339)*
