### PR TITLE
Fix misoptimizations when matching against strings/slices

### LINKED ISSUE #22008: Bug in optimiser(maybe)
Hi,

The rust optimiser or some other component is not behaving correctly resulting in wrong results.
I have produced a small example here : https://github.com/eklavya/rust-bug

This was reproduced on 
Mac yosemite:
cargo 0.0.1-pre-nightly (2b9a3d6 2015-01-30 02:47:30 +0000)
rustc 1.0.0-nightly (3b2ed1490 2015-02-03 14:56:32 +0000)
and 
centos7 x64, rustc 1.0.0-nightly (706be5ba1 2015-02-05 23:14:28 +0000)

Please let me know if you need any more details.

### PR DESCRIPTION
**Pull request by dotdash**
When matching against strings/slices, we call the comparison function
for strings, which takes two string slices by value. The slices are
passed in memory, and currently we just pass in a pointer to the
original slice. That can cause misoptimizations because we emit a call
to llvm.lifetime.end for all by-value arguments at the end of a
function, which in this case marks the original slice as dead.

So we need to properly create copies of the slices to pass them to the
comparison function.

Fixes #22008

### CODE REVIEW

File: src/test/run-pass/issue22008.rs [hunk 1]
```diff
@@ -0,0 +1,18 @@
+// Copyright 2015 The Rust Project Developers. See the COPYRIGHT
+// file at the top-level directory of this distribution and at
+// http://rust-lang.org/COPYRIGHT.
+//
+// Licensed under the Apache License, Version 2.0 <LICENSE-APACHE or
+// http://www.apache.org/licenses/LICENSE-2.0> or the MIT license
+// <LICENSE-MIT or http://opensource.org/licenses/MIT>, at your
+// option. This file may not be copied, modified, or distributed
+// except according to those terms.
+
```
Comment (sfackler) [inline src/test/run-pass/issue22008.rs]: This should probably have a `// compile-flags: -O` to force optimizations.

File: src/librustc_trans/trans/_match.rs [hunk 2]
```diff
@@ -828,7 +828,16 @@ fn compare_values<'blk, 'tcx>(cx: Block<'blk, 'tcx>,
                            &format!("comparison of `{}`",
                                    cx.ty_to_string(rhs_t))[],
                            StrEqFnLangItem);
-        callee::trans_lang_call(cx, did, &[lhs, rhs], None, debug_loc)
+        let t = ty::mk_str_slice(cx.tcx(), cx.tcx().mk_region(ty::ReStatic), ast::MutImmutable);
```
Comment (huonw) [inline src/librustc_trans/trans/_match.rs]: Could you add a comment about why this is doing seemingly pointless copies?

**Comment by dotdash** [comment]
Addressed both comments. Thanks!

File: src/test/run-pass/issue22008.rs (hunk 1 above)
Comment (dotdash) [inline src/test/run-pass/issue22008.rs]: Unfortunately this break when the tests are compiled with optimizations, because -O is given twice then. So I'll remove that again.

**Comment by brson** [comment]
Nice find for a subtle bug.

**Comment by nikomatsakis** [comment]
Hmm not sure why I put rollup there. I guess because the patch was so small.
