### PR TITLE
Abort on stack overflow instead of re-raising SIGSEGV

### LINKED ISSUE #31273: Stack overflow should abort the process normally, not segfault and dump core
Today, when you overflow the stack, Rust traps the SIGSEGV and prints an error message, then the program exits with a segfault, exit code 135 on linux, and dumps core.

When we used segstacks for stack overflow the runtime just `abort!`ed, exiting with an illegal instruction.

That stack overflow protection is implemented by handling a segfault is an implementation detail. Rust should not be exposing it. Instead, when it detects a segfault because of stack overflow it should abort like any other fatal error.

cc https://users.rust-lang.org/t/rust-guarantees-no-segfaults-with-only-safe-code-but-it-segfaults-stack-overflow/4305/20

### PR DESCRIPTION
**Pull request by lambda**
Abort on stack overflow instead of re-raising SIGSEGV

We use guard pages that cause the process to abort to protect against
undefined behavior in the event of stack overflow.  We have a handler
that catches segfaults, prints out an error message if the segfault was
due to a stack overflow, then unregisters itself and returns to allow
the signal to be re-raised and kill the process.

This caused some confusion, as it was unexpected that safe code would be
able to cause a segfault, while it's easy to overflow the stack in safe
code.  To avoid this confusion, when we detect a segfault in the guard
page, abort instead of the previous behavior of re-raising SIGSEGV.

To test this, we need to adapt the tests for segfault to actually check
the exit status.  Doing so revealed that the existing test for segfault
behavior was actually invalid; LLVM optimizes the explicit null pointer
reference down to an illegal instruction, so the program aborts with
SIGILL instead of SIGSEGV and the test didn't actually trigger the
signal handler at all.  Use a C helper function to get a null pointer
that LLVM can't optimize away, so we get our segfault instead.

This is a [breaking-change] if anyone is relying on the exact signal
raised to kill a process on stack overflow.

Closes #31273

### CODE REVIEW

**Comment by lambda** [comment]
I've only tested this on Mac OS X, but I'm pretty sure that everything it does is kosher according to POSIX, and everything that's Unix-specific has been protected with `#[cfg(unix)])`, so I don't think this should break any platforms. The one thing that isn't in POSIX is `MAP_ANON` in the `mmap` that's used to map an unmap a page in the tests to test out that our processes are killed with the appropriate signals; however, every platform I checked in a quick search (Linux, FreeBSD, NetBSD, OpenBSD, Solaris, Mac OS X) supports that.

File: src/test/run-pass/segfault-no-out-of-stack.rs [hunk 1]
```diff
@@ -15,10 +15,59 @@ extern crate libc;
...
+    // Map and unmap a page of memory to guarantee that we have a pointer that
+    // will produce a segfault.
+    let pagesize = libc::sysconf(libc::_SC_PAGE_SIZE);
+    if pagesize == -1 {
+        panic!("Couldn't get pagesize");
+    }
+
+    let mut buf = libc::mmap(0 as *mut libc::c_void,
+                             pagesize as libc::size_t,
+                             libc::PROT_WRITE | libc::PROT_READ,
```
Comment (nagisa) [inline src/test/run-pass/segfault-no-out-of-stack.rs]: Perhaps just do not pass in `PROT_WRITE` here to avoid the potent race condition where pointer could become valid between the unmap and dereference?

Not that it matters much.

File: src/libstd/sys/unix/stack_overflow.rs [hunk 2]
```diff
@@ -102,17 +105,19 @@ mod imp {
         let addr = siginfo_si_addr(info);
 
         // If the faulting address is within the guard page, then we print a
-        // message saying so.
+        // message saying so and abort.
         if guard != 0 && guard - PAGE_SIZE <= addr && addr < guard {
             report_overflow();
+            libc::raise(libc::SIGABRT);
```
Comment (nagisa) [inline src/libstd/sys/unix/stack_overflow.rs]: Aha, we have a separate signal handler stack here, so I guess that’s a viable way of getting SIGABRT happen. You still need to unregister `SIGABRT` handlers in this process before raising the signal, though.

File: src/libstd/sys/unix/stack_overflow.rs [hunk 3]
```diff
@@ -83,16 +83,19 @@ mod imp {
     // were originally supposed to do.
     //
     // This handler currently exists purely to print an informative message
-    // whenever a thread overflows its stack. When run the handler always
-    // un-registers itself after running and then returns (to allow the original
-    // signal to be delivered again). By returning we're ensuring that segfaults
-    // do indeed look like segfaults.
+    // whenever a thread overflows its stack. We then abort to exit with an
+    // error (and dump core if necessary), but to avoid a misleading SIGSEGV
```
Comment (nagisa) [inline src/libstd/sys/unix/stack_overflow.rs]: NIT: The 2nd part of this sentence has no weight behind it whatsoever, because SIGSEGV is accompanied with a overflow message, thus resolving any potential confusion that might arise.

File: src/test/run-pass/segfault-no-out-of-stack.rs (hunk 1 above)
Comment (lambda) [inline src/test/run-pass/segfault-no-out-of-stack.rs]: Yeah, I tried that, but then I was getting `SIGBUS` instead of `SIGSEGV` like with `mprotect`. I figured that just unmapping would be a better way to get a guaranteed `SIGSEGV`. I don't know of any circumstances in which the kernel would re-map that memory for us without anything going on on our process to cause it to do so, so I don't think we need to worry about such a race here; also, [POSIX requires](http://pubs.opengroup.org/onlinepubs/009695399/functions/munmap.html) that after calling `munmap`, further references to those pages will produce `SIGSEGV`.

File: src/libstd/sys/unix/stack_overflow.rs (hunk 3 above)
Comment (lambda) [inline src/libstd/sys/unix/stack_overflow.rs]: It's possible that a user would see the segfault but not the overflow message, for instance if something captures the exit code but not stderr; the message below is printed by the shell, so unaffected by the redirection:

```
$ ./so >/dev/null 2>&1
Segmentation fault: 11
```

Since we have actually seen real confusion based on a [segfault cause by a stack overflow](https://users.rust-lang.org/t/rust-guarantees-no-segfaults-with-only-safe-code-but-it-segfaults-stack-overflow/4305) (though in that case it didn't have the message because of lack of stack probes #16012 not because of output redirection), I think it's reasonable to state that this SIGSEGV can be misleading.

File: src/libstd/sys/unix/stack_overflow.rs (hunk 2 above)
Comment (lambda) [inline src/libstd/sys/unix/stack_overflow.rs]: Good point, will do that.

File: src/libstd/sys/unix/stack_overflow.rs (hunk 3 above)
Comment (nagisa) [inline src/libstd/sys/unix/stack_overflow.rs]: > though in that case it didn't have the message because of lack of stack probes #16012 not because of output redirection

The lack of stack probes would result in no SIGABRT too, so my point still stands.

> for instance if something captures the exit code but not stderr

That’s not something we should be worried about in technical documentation, right?

> and dump core if necessary

NIT: its not us dumping the core, nor do we do anything beyond raising a SIGABRT to make the coredump happen. IMO this is confusing and should be removed too.

Comment (lambda) [inline src/libstd/sys/unix/stack_overflow.rs]: > That’s not something we should be worried about in technical documentation, right?

This is an explanation for why we are doing something other than re-raising the `SIGSEGV`. The reason for that is that it can be confusing to see a `SIGSEGV` that has been triggered by purely safe code. If that behavior were not confusing, there would be no need to apply this patch at all; but I think that the existence of people who have been confused by such segfaults is good evidence that this behavior is confusing.

Now, yes, as I have already pointed out, the existing confusion came about because of another separate issue that caused the stack overflow message to not get printed. It's possible that with that message reliably printed, the confusion could have been avoided. However, there are other ways, such as running daemons under other supervisory processes, in which exit codes may get logged, but stderr may not be. Those cases are all cases in which this `SIGSEGV` could be misleading.

Since the front page of Rust's website says "no segfaults" and the docs say "If a Rust program segfaults, you can be sure the cause is related to something marked unsafe", the existence of segfaults outside of unsafe code could be quite confusing. One way to fix that is to change the wording on the website and docs (suggested in #30963). Another way is this fix, to just exit with a different error.

I think that if we apply this fix, the comment should mention that this confusion is why we have this special behavior.

> NIT: its not us dumping the core, nor do we do anything beyond raising a SIGABRT to make the coredump happen. IMO this is confusing and should be removed too.

Sure; does "we then raise SIGABRT to exit and indicate a crash" sound better?

**Comment by lambda** [comment]
cc @geofft @Zoxc @brson

File: src/libstd/sys/unix/stack_overflow.rs [hunk 4]
```diff
@@ -102,17 +105,25 @@ mod imp {
...
-        let mut action: sigaction = mem::zeroed();
-        action.sa_sigaction = SIG_DFL;
-        sigaction(signum, &action, ptr::null_mut());
+            // Unregister any existing abort handler to get the default behavior.
+            let mut action: sigaction = mem::zeroed();
+            action.sa_sigaction = SIG_DFL;
+            sigaction(libc::SIGABRT, &action, ptr::null_mut());
 
-        // See comment above for why this function returns.
+            libc::raise(libc::SIGABRT);
```
Comment (alexcrichton) [inline src/libstd/sys/unix/stack_overflow.rs]: To behave more like `rtabort!` this may wish to use `intrinsics::abort()` as it mimics other runtime-abort behavior and means we don't need to mess around with signals or anything.

File: src/test/run-pass/segfault-no-out-of-stack.rs [hunk 5]
```diff
@@ -15,10 +15,59 @@ extern crate libc;
...
+    *(buf as *mut libc::c_char) = 1;  // trigger the actual segfault
+}
+
+#[cfg(not(unix))]
+unsafe fn segfault() {
+    // This isn't actually guaranteed to produce a segfault; it appears that LLVM
+    // sometimes just compiles this down to an illegal instruction.  Will need to
+    // provide an implementation of something like the above in order for this test
+    // to be valid on non-Unix platforms.
+    *(0 as *mut isize) = 1;
```
Comment (alexcrichton) [inline src/test/run-pass/segfault-no-out-of-stack.rs]: An easier way to write this is probably also to do something like add a helper function to `rust_test_helpers.c` which just returns the null pointer and then dereference that. LLVM can't prove the pointer coming from C is the null pointer so it won't be able to do this optimization.

**Comment by alexcrichton** [comment]
r? @brson 

You seem more opinionated than I, but both the current strategy an the proposed strategy are fine by me!

File: src/libstd/sys/unix/stack_overflow.rs (hunk 4 above)
Comment (lambda) [inline src/libstd/sys/unix/stack_overflow.rs]: Yeah, but `intrinsics::abort()` does so via an illegal instruction, giving us `SIGILL`, which doesn't seem ideal if we're trying to clear up confusion caused by the particular signal received.

File: src/test/run-pass/segfault-no-out-of-stack.rs (hunk 5 above)
Comment (lambda) [inline src/test/run-pass/segfault-no-out-of-stack.rs]: Thanks for the suggestion, that makes this test case much simpler.

File: src/libstd/sys/unix/stack_overflow.rs (hunk 4 above)
Comment (alexcrichton) [inline src/libstd/sys/unix/stack_overflow.rs]: Ah yeah I was just going off @brson's [desire](https://github.com/rust-lang/rust/issues/31273) that stack overflow "should abort like any other fatal error". Our other fatal errors today use `rtabort!` which ends up translating to `intrinsics::abort`.

It would indeed do so via an illegal instruction, resulting in `SIGILL`, and likely resulting in a core dump as well.

Comment (lambda) [inline src/libstd/sys/unix/stack_overflow.rs]: Would it make more sense to change `rtabort!` to call `libc::abort` instead of `intrinsics::abort`, now that we have `libc::abort`? `libc::abort` is supposed to handle all of the edge cases like this, either unregistering the signal handler or killing itself another way if the signal handler returns or just infinitely looping if all else fails.

Comment (alexcrichton) [inline src/libstd/sys/unix/stack_overflow.rs]: I'd be down with that

Comment (alexcrichton) [inline src/libstd/sys/unix/stack_overflow.rs]: Er, to be clear, on Unix that seems fine but on Windows we're trying to avoid the CRT wherever possible, so in that sense it may be a platform-specific abort process. I guess it makes less sense in that case :(

**Comment by brson** [comment]
> Yeah, but intrinsics::abort() does so via an illegal instruction, giving us SIGILL, which doesn't seem ideal if we're trying to clear up confusion caused by the particular signal received.

My preference is for all aborts to be the same, and would prefer this to be an `rtabort!`. If it would be more proper to terminate with `SIGABORT` than `SIGILL` let's do that for all aborts, not just this one (but in a separate PR). Please do turn this into an rtabort.

**Comment by brson** [comment]
This is a breaking change, but *probably* one nobody is relying on.

**Comment by lambda** [comment]
Switched to `rtabort!` instead of manually raising `SIGABRT`, updated the commit message to indicate possible breakage.

File: src/test/run-pass/out-of-stack.rs [hunk 6]
```diff
@@ -35,6 +39,23 @@ fn loud_recurse() {
...
 }
 
+#[cfg(unix)]
+fn check_status(status: std::process::ExitStatus)
+{
+    use libc;
+    use std::os::unix::process::ExitStatusExt;
+
+    assert!(!status.success());
+    assert!(status.signal() != Some(libc::SIGSEGV));
```
Comment (brson) [inline src/test/run-pass/out-of-stack.rs]: Presumably this is also true on Windows?

**Comment by lambda** [comment]
Whoops, some architectures throw `SIGBUS` on a null pointer dereference rather than `SIGSEGV`. Pushed a fix that will check for either of those in the tests.

**Comment by lambda** [comment]
Failure looks spurious.

**Comment by brson** [comment]
cc @rust-lang/lang In some ways this is a pretty significant change to how processes terminate on stack overflow. It makes stack overflow terminate the process with `rtabort!` (which produces SIGILL), instead of the SIGSEGV / SEGBUS signal delivered by the OS. The rationale is that the segfault is an implementation detail of how std catches the stack overflow, we may want to change stack over behavior.
