### PR TITLE
Win: Use POSIX rename semantics for `std::fs::rename` if available

### LINKED ISSUE #123985: `std::fs::rename` sometimes fails on Windows due to missing `FILE_RENAME_POSIX_SEMANTICS`
When opening a file on Windows, the default flags indicate sharing for read, write and delete. If you attempt to atomically rename a file over another file while it is being read, however, this results in an access-denied error despite the expectation that those access flags would allow for this to occur. 

This makes all attempts at writing atomic-file-replace operations extremely racy and difficult to get right on Windows, while working as expected on other platforms.

By default, Rust's stdlib rename should make use of the new `FILE_RENAME_POSIX_SEMANTICS` when available. This will allow a file to stay open while the underlying file is atomically replaced with new contents.

This surfaced recently in Deno as a failure in the `DiskCache` implementation on Windows (https://github.com/denoland/deno/blob/main/cli/cache/disk_cache.rs#L123). If a file is being read at the same time an atomic write happens on another thread, the write operation fails with an "access denied" error, but only on Windows.

*Justification*

There is precedent for using POSIX semantics on Windows by default: for example, recursive directory deletes use this where available, and junction points (implemented in https://github.com/rust-lang/rust/issues/121709) are created with POSIX semantics.

In addition, users can opt out of POSIX rename semantics by opening files without the `DELETE` sharing mode.

*API Background*

As of Windows 10 1709 and later, a new `FILE_RENAME_POSIX_SEMANTICS` flag is available for the `FileRenameInformationEx`

https://learn.microsoft.com/en-us/windows-hardware/drivers/ddi/ntifs/nf-ntifs-ntsetinformationfile

*Related bugs in other frameworks*

https://bugs.python.org/msg344575

### PR DESCRIPTION
**Pull request by Fulgen301**
Windows 10 1601 introduced `FileRenameInfoEx` as well as `FILE_RENAME_FLAG_POSIX_SEMANTICS`, allowing for atomic renaming and renaming if the target file is has already been opened with `FILE_SHARE_DELETE`, in which case the file gets renamed on disk while the open file handle still refers to the old file, just like in POSIX. This resolves #123985, where atomic renaming proved difficult to impossible due to race conditions.

If `FileRenameInfoEx` isn't available due to missing support from the underlying filesystem or missing OS support, the renaming is retried with `FileRenameInfo`, which matches the behavior of `MoveFileEx`.

This PR also manually replicates parts of `MoveFileEx`'s internal logic, as reverse-engineered from the disassembly: If the source file is a reparse point and said reparse point is a mount point, the mount point itself gets renamed; otherwise the reparse point is resolved and the result renamed.

Notes:
- Currently, the `win7` target doesn't bother with `FileRenameInfoEx` at all; it's probably desirable to remove that special casing and try `FileRenameInfoEx` anyway if it doesn't exist, in case the binary is run on newer OS versions.

Fixes #123985

### CODE REVIEW

**Comment by ChrisDenton** [comment]
This looks good to me.

> Currently, the `win7` target doesn't bother with `FileRenameInfoEx` at all; it's probably desirable to remove that special casing and try `FileRenameInfoEx` anyway if it doesn't exist, in case the binary is run on newer OS versions.

Yes, I'd prefer if we just did that. Doing so doesn't appear to require anything special and the less the `win7` target diverges the better.

File: library/std/src/sys/pal/windows/fs.rs [hunk 1]
```diff
@@ -1095,7 +1096,136 @@ pub fn unlink(p: &Path) -> io::Result<()> {
 pub fn rename(old: &Path, new: &Path) -> io::Result<()> {
     let old = maybe_verbatim(old)?;
     let new = maybe_verbatim(new)?;
-    cvt(unsafe { c::MoveFileExW(old.as_ptr(), new.as_ptr(), c::MOVEFILE_REPLACE_EXISTING) })?;
+
+    let new_len_without_nul_in_bytes = (new.len() - 1).try_into().unwrap();
+
+    let struct_size = mem::size_of::<c::FILE_RENAME_INFO>() - mem::size_of::<u16>()
+        + new.len() * mem::size_of::<u16>();
```
Comment (ChrisDenton) [inline library/std/src/sys/pal/windows/fs.rs:1103]: You should be able to use `offset_of!` here to get the last field instead of manually calculating it.

File: library/std/src/sys/pal/windows/fs.rs [hunk 2]
```diff
@@ -1095,7 +1096,136 @@ pub fn unlink(p: &Path) -> io::Result<()> {
...
+            }
+        }
+        // The underlying driver may not support `FILE_FLAG_OPEN_REPARSE_POINT`: Retry without it.
+        Err(err) if err.raw_os_error() == Some(c::ERROR_INVALID_PARAMETER as _) => None,
+        Err(err) => Some(Err(err)),
+    }
+    .unwrap_or_else(|| create_file(0, 0))?;
+
+    // The last field of FILE_RENAME_INFO, the file name, is unsized.
+    // Therefore we need to subtract the size of one wide char.
```
Comment (ChrisDenton) [inline library/std/src/sys/pal/windows/fs.rs:1172]: This comment and assigning `struct_size` seem rather too distant from one another.

**Review by ChrisDenton — COMMENTED** [review]
I think this is looking good. Just a couple of nits.

**Comment by ChrisDenton** [comment]
Thanks!

@bors r+
