### PR TITLE
Correctly escape hashtags when running `invalid_rust_codeblocks` lint

### LINKED ISSUE #136899: rustdoc: Failed to parse rust code block with ## in 2024
In 2024, rustdoc seems to fail to parse a rust code line that starts with `##`.

```rust
//! Test
//!
//! ```
//! ##[allow(dead_code)]
//! println!("hello world");
//! ```
```

In 2021, this renders in a weird way where it strips the first `#`, but doesn't actually hide the line. I would expect the line to be hidden. I don't know if that is intentional.

Image

In 2024, `cargo doc` generates a warning:

```
arning: could not parse code block as Rust code
 --> src/lib.rs:3:5
  |
3 |   //! ```
  |  _____^
4 | | //! ##[allow(dead_code)]
5 | | //! println!("hello world");
6 | | //! ```
  | |_______^
  |
  = note: error from rustc: reserved multi-hash token is forbidden
  = note: `#[warn(rustdoc::invalid_rust_codeblocks)]` on by default
help: mark blocks that do not contain Rust code as text
  |
3 | //! ```text
  |        ++++
```

I'm not sure what I expect here. I assume it is conflicting with the [reserved syntax](https://doc.rust-lang.org/nightly/edition-guide/rust-2024/reserved-syntax.html) of 2024.

Is the `##` form really intended to be supported as a way to hide a line?  cc @GuillaumeGomez 

### Meta

`rustc --version --verbose`:
```
rustc 1.86.0-nightly (92bedea1c 2025-02-11)
binary: rustc
commit-hash: 92bedea1c51e3a969d60972be854506ffd8c5cb6
commit-date: 2025-02-11
host: aarch64-apple-darwin
release: 1.86.0-nightly
LLVM version: 19.1.7
```

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Fixes #136899.

We forgot to use `map_line` when we wrote this lint.

r? @notriddle

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
I'll actually make a ui test to check this, not sure why I thought about a `run-make` one...

**Comment by GuillaumeGomez** [comment]
And done! :)

File: tests/rustdoc-ui/2024-hashtag-doctest.rs [hunk 1]
```diff
@@ -0,0 +1,14 @@
+// This test ensures that `##` are not emitting a warning when generating
+// docs with the 2024 edition.
+// Regression test for <https://github.com/rust-lang/rust/issues/136899>.
+
+//@ check-pass
```
Comment (fmease) [inline tests/rustdoc-ui/2024-hashtag-doctest.rs:5]:
```suggestion
//@ check-pass
//@ edition: 2024
```

UI tests default to Rust 2015

File: tests/rustdoc-ui/2024-hashtag-doctest.rs [hunk 2]
```diff
@@ -0,0 +1,14 @@
...
+
+#![deny(warnings)]
+
+//! Test
+//!
+//! ```
```
Comment (fmease) [inline tests/rustdoc-ui/2024-hashtag-doctest.rs:11]: Alternatively


```suggestion
//! ```edition2024
```

File: src/librustdoc/passes/lint/check_code_block_syntax.rs [hunk 3]
```diff
@@ -43,7 +43,10 @@ fn check_rust_syntax(
 
     let sm = Arc::new(SourceMap::new(FilePathMapping::empty()));
     let dcx = DiagCtxt::new(Box::new(emitter)).disable_warnings();
-    let source = dox[code_block.code].to_owned();
+    let source = dox[code_block.code]
+        .lines()
+        .map(|line| crate::html::markdown::map_line(line).for_code())
+        .collect::<String>();
```
Comment (notriddle) [inline src/librustdoc/passes/lint/check_code_block_syntax.rs:49]:
```suggestion
        .join("\n");
```

File: tests/rustdoc-ui/2024-hashtag-doctest.rs (hunk 1 above)
Comment (notriddle) [reply tests/rustdoc-ui/2024-hashtag-doctest.rs:5]: I'd rather test both editions at once. Neither of them should warn, after all, and the combination of features and editions should be long-term easier to manage if we make a habit of parameterizing these tests whenever there's a chance of the edition affecting it.

Comment (fmease) [reply tests/rustdoc-ui/2024-hashtag-doctest.rs:5]: Hmm, I don't fully agree (after all, `##` is Rust 2024 specific) but it doesn't hurt.

File: tests/rustdoc-ui/2024-hashtag-doctest.rs (hunk 2 above)
Comment (GuillaumeGomez) [reply tests/rustdoc-ui/2024-hashtag-doctest.rs:11]: Since we want to test both editions, I'll just use revisions instead. :)
