### PR TITLE
Merge Apple `std::os` extensions modules into `std::os::darwin`

### LINKED ISSUE #121640: Failed to build aarch64-apple-tvos target
I tried to build `aarch64-apple-tvos`, `x86_64-apple-tvos`, `aarch64-apple-tvos-sim` targets.
Unfortunately, I got

<details><summary>the following errors:</summary>
<p>

```
  error: methods `as_raw_stat`, `st_birthtime`, `st_birthtime_nsec`, `st_flags`, `st_gen`, and `st_lspare` are never used
    --> library/std/src/os/ios/fs.rs:29:8
     |
  15 | pub trait MetadataExt {
     |           ----------- methods in this trait
  ...
  29 |     fn as_raw_stat(&self) -> &raw::stat;
     |        ^^^^^^^^^^^
  ...
  60 |     fn st_birthtime(&self) -> i64;
     |        ^^^^^^^^^^^^
  61 |     #[stable(feature = "metadata_ext2", since = "1.8.0")]
  62 |     fn st_birthtime_nsec(&self) -> i64;
     |        ^^^^^^^^^^^^^^^^^
  ...
  68 |     fn st_flags(&self) -> u32;
     |        ^^^^^^^^
  69 |     #[stable(feature = "metadata_ext2", since = "1.8.0")]
  70 |     fn st_gen(&self) -> u32;
     |        ^^^^^^
  71 |     #[stable(feature = "metadata_ext2", since = "1.8.0")]
  72 |     fn st_lspare(&self) -> u32;
     |        ^^^^^^^^^
     |
     = note: `-D dead-code` implied by `-D warnings`
     = help: to override `-D warnings` add `#[allow(dead_code)]`
  
  error: method `set_created` is never used
     --> library/std/src/os/ios/fs.rs:151:8
      |
  148 | pub trait FileTimesExt: Sealed {
      |           ------------ method in this trait
  ...
  151 |     fn set_created(self, t: SystemTime) -> Self;
      |        ^^^^^^^^^^^
  
  
  Did not run successfully: exit status: 1
```

</p>
</details>

### How to reproduce

```
./configure \
		--enable-option-checking \
		--tools=cargo,clippy,rustdoc,rustfmt,rust-analyzer,analysis,src \
		--target=aarch64-apple-tvos,x86_64-apple-tvos,aarch64-apple-tvos-sim \
		--set llvm.download-ci-llvm=true \
		--set build.verbose=1 \
		--set rust.channel=dev \
		--dist-compression-formats=xz \
		--prefix=install
```

According to the [docs](https://doc.rust-lang.org/rustc/platform-support/apple-tvos.html), the target maintainer is [@thomcc](https://github.com/thomcc)

### PR DESCRIPTION
**Pull request by madsmtm**
The functionality available on Apple platforms are very similar, and were (basically) duplicated for each platform.

This PR rectifies that by merging the code into one module.

Ultimately, I've done this to fix `./x build library --target=aarch64-apple-tvos,aarch64-apple-watchos,aarch64-apple-visionos`, as that currently fails because of dead code warnings.

Publically exposing these to tvOS/watchOS/visionOS targets is considered in https://github.com/rust-lang/rust/pull/123723, but that seems to be dragging out, and in any case I think it makes sense to do the refactor separately from stabilization.

r? libs

Fixes https://github.com/rust-lang/rust/issues/121640 and https://github.com/rust-lang/rust/issues/124825.

### CODE REVIEW

**Comment by workingjubilee** [comment]
Thanks for doing this!

@madsmtm do you have an opinion on the "apple vs. darwin" thing I noted.

**Comment by workingjubilee** [comment]
note for the audience: to confuse matters for everyone, Darwin is absolutely the core of the macOS system... but also iOS, and watchOS, etc.

**Comment by madsmtm** [comment]
> @madsmtm do you have an opinion on the "apple vs. darwin" thing I noted.

Will respond on the other PR

**Comment by madsmtm** [comment]
r? workingjubilee

**Comment by madsmtm** [comment]
Ping @workingjubilee?

**Comment by workingjubilee** [comment]
oh, sorry!

I had spaced out on this.

File: library/std/src/os/darwin/mod.rs [hunk 1]
```diff
@@ -0,0 +1,17 @@
...
+//! - visionOS
+//!
+//! Note: This module is called "Darwin" as that's the name of the underlying
+//! core OS of the above operating systems, but it should not be confused with
+//! the `-darwin` suffix in the `x86_64-apple-darwin` and
+//! `aarch64-apple-darwin` target names, which are mostly named that way for
+//! legacy reasons.
+
+pub(crate) mod fs;
+pub(crate) mod raw;
```
Comment (workingjubilee) [inline library/std/src/os/darwin/mod.rs:17]: Can these be `pub(super)` instead? And I'd like a comment on `raw` since it's only for reexport on some systems, even if we make this module public, like...
```suggestion
pub(super) mod fs;
/// deprecated, only for public reexport on macOS/iOS because their platform support precedes the decision to remove these.
pub(super) mod raw;
```

Comment (workingjubilee) [reply library/std/src/os/darwin/mod.rs:17]: I think possibly only `raw` can be `pub(super)` due to certain tests? idk.

**Comment by workingjubilee** [comment]
looks good with that nit, sorry about that!

File: library/std/src/os/darwin/mod.rs (hunk 1 above)
Comment (madsmtm) [reply library/std/src/os/darwin/mod.rs]: I've written it as a slightly different comment that also talks about the usage in `std::os::unix::raw`
