### PR TITLE
save LTO import info and check it when trying to reuse build products

### LINKED ISSUE #59535: Incremental compilation results in linker error when method use is removed
See: https://github.com/jonas-schievink/rubble/compare/incr-linker-error

Build the first commit (jonas-schievink/rubble@04cf1d1), then the second (jonas-schievink/rubble@cedf7be) using `cargo build`, and you should get a linker error like this:

```
  = note: rust-lld: error: undefined symbol: _$LT$rubble..ble..time..Duration$u20$as$u20$core..fmt..Display$GT$::fmt::h343296729f83afc4
          >>> referenced by time.rs:129 (src/ble/time.rs:129)
          >>>               /home/jonas/dev/rubble/target/thumbv7em-none-eabi/debug/deps/rubble-a38354bf4561073f.3qtzuenakrd0qcaf.rcgu.o:(_$LT$$RF$T$u20$as$u20$core..fmt..Debug$GT$::fmt::h26ac05bd6f4f461e)
```

Note that this needs the `thumbv7em-none-eabi` target, so you might need to run `rustup target add thumbv7em-none-eabi` beforehand.

This is on `rustc 1.33.0 (2aa4c46cf 2019-02-28)`.
Also reproduces on `rustc 1.35.0-nightly (237bf3244 2019-03-28)`.

### PR DESCRIPTION
**Pull request by pnkfelix**
Fix #59535 

Previous runs of LTO optimization on the previous incremental build can import larger portions of the dependence graph into a codegen unit than the current compilation run is choosing to import. We need to take that into account when we choose to reuse PostLTO-optimization object files from previous compiler invocations.

This PR accomplishes that by serializing the LTO import information on each incremental build. We load up the previous LTO import data as well as the current LTO import data. Then as we decide whether to reuse previous PostLTO objects or redo LTO optimization, we check whether the LTO import data matches. After we finish with this decision process for every object, we write the LTO import data back to disk.
 
----

What is the scenario where comparing against past LTO import information is necessary?

I've tried to capture it in the comments in the regression test, but here's yet another attempt from me to summarize the situation:

 1. Consider a call-graph like `[A] -> [B -> D] <- [C]` (where the letters are functions and the modules are enclosed in `[]`)
 2. In our specific instance, the earlier compilations were inlining the call to`B` into `A`; thus `A` ended up with a external reference to the symbol `D` in its object code, to be resolved at subsequent link time. The LTO import information provided by LLVM for those runs reflected that information: it explicitly says during those runs, `B` definition and `D` declaration were imported into `[A]`.
 3. The change between incremental builds was that the call `D <- C` was removed.
 4. That change, coupled with other decisions within `rustc`, made the compiler decide to make `D` an internal symbol (since it was no longer accessed from other codegen units, this makes sense locally). And then the definition of `D` was inlined into `B` and `D` itself was eliminated entirely.
  5. The current LTO import information reported that `B` alone is imported into `[A]` for the *current compilation*. So when the Rust compiler surveyed the dependence graph, it determined that nothing `[A]` imports changed since the last build (and `[A]` itself has not changed either), so it chooses to reuse the object code generated during the previous compilation.
  6. But that previous object code has an unresolved reference to `D`, and that causes a link time failure!

----

The interesting thing is that its quite hard to actually observe the above scenario arising, which is probably why no one has noticed this bug in the year or so since incremental LTO support landed (PR #53673).

I've literally spent days trying to observe the bug on my local machine, but haven't managed to find the magic combination of factors to get LLVM and `rustc` to do just the right set of the inlining and `internal`-reclassification choices that cause this particular problem to arise.

----

Also, I have tried to be careful about injecting new bugs with this PR. Specifically, I was/am worried that we could get into a scenario where overwriting the current LTO import data with past LTO import data would cause us to "forget" a current import. ~~To guard against this, the PR as currently written always asserts, at overwrite time, that the past LTO import-set is a *superset* of the current LTO import-set. This way, the overwriting process should always be safe to run.~~
 * The previous note was written based on the first version of this PR. It has since been revised to use a simpler strategy, where we never attempt to merge the past LTO import information into the current one. We just *compare* them, and act accordingly.
 * Also, as you can see from the comments on the PR itself, I was quite right to be worried about forgetting past imports; that scenario was observable via a trivial transformation of the regression test I had devised.

### CODE REVIEW

File: src/test/run-make/removing-code-and-incremental-lto/Makefile [hunk 1]
```diff
@@ -0,0 +1,69 @@
+-include ../../run-make-fulldeps/tools.mk
+
+# How to run this
+# $ ./x.py clean
+# $ ./x.py test --target thumbv7m-none-eabi src/test/run-make
+
+# The original target of interest was thumbv7em-none-eabi
```
Comment (pnkfelix) [inline src/test/run-make/removing-code-and-incremental-lto/Makefile]: Oh, right, this probably needs an `# only-thumbv7em-none-eabi`.

(I was trying to figure out how/if to generalize beyond that target, and in the process I got distracted by filing #67018 )

**Comment by pnkfelix** [comment]
>I was/am worried that we could get into a scenario where overwriting the current LTO import data with past LTO import data would cause us to "forget" a current import. To guard against this, the PR as currently written always asserts, at overwrite time, that the past LTO import-set is a _superset_ of the current LTO import-set. This way, the overwriting process should always be safe to run.

I've been thinking more about this assertion this morning. I think I should just remove it.

Here is my thinking: assuming the LTO import set computation is always based on the current state of the code, and we observe when going from revision1 to revision2 that the import set for (green) module A has gone from set1 to set2 where set2 ⊆ set1, then logically one should be able to reverse the direction of the change (going from revision2 to revision1), and LLVM may (or even *should*) compute a corresponding change in the import set for that same (still green) module A where it now goes from set2 to set1 (where we still have set1 ⊇ set2). That would cause the assertion to fail.

Instead, I should just trust the underlying logic: the serialized imports for codegen unit A correspond to whatever information the LTO used for *that* compilation. If we reuse previously compiled A, then we keep the serialized LTO imports. If we recompile (or re-run LTO optimization) for A, then we use its newly computed LTO imports.

**Comment by pnkfelix** [comment]
>  logically one should be able to reverse the direction of the change (going from _revision₂_ to _revision₁_)

eek! Yes: One can *trivially* construct a test showing this with slight modification of the test that I **already** have on this PR.

Fixing that up now.

**Comment by michaelwoerister** [comment]
I'm wondering, do we even need to "overwrite" anything? Or could we make the decision once, before ThinLTO, based on the previous import map? Then save the current map to disk as is, without any merging. It should be correct and deterministic as it is always generated from the entire set of modules, including the cached ones.

**Comment by michaelwoerister** [comment]
That is an excellent description of the error scenario btw :heart: :heart: :heart:

**Comment by michaelwoerister** [comment]
Here is a version that makes re-use decisions based solely on the previous import map:
https://github.com/rust-lang/rust/pull/52309/files#diff-7495f8d1204a6939d7aa2d406839e509R949-R1008

It's from https://github.com/rust-lang/rust/pull/52309, which was never merged.

**Comment by pnkfelix** [comment]
> I'm wondering, do we even need to "overwrite" anything? Or could we make the decision once, before ThinLTO, based on the previous import map? Then save the current map to disk as is, without any merging. It should be correct and deterministic as it is always generated from the entire set of modules, including the cached ones.

My understanding of how the current import map is generated leads me to think that we cannot get by using the previous imports and storing the current ones. Otherwise, you'll still end up in the same scenario, just one incremental compile-cycle later.

I can try to spell this out in more detail, if need be.

**Comment by michaelwoerister** [comment]
I think the problem arises from making decision based on the _previous_ state of the object files in combination with the _current_ import map. If the two things match up, i.e. making decisions about the previous object files based on the previous import map (which always accurately describes them), then the problem would not arise.

I'm generally very uneasy about keeping around data from sessions `N-x` where `x > 1`. That could add a kind of indeterminism unless you re-create the entire version history of compiling a crate (which would make for a really nasty debugging experience).

**Comment by michaelwoerister** [comment]
If you want, I can try to sketch an alternative PR tomorrow morning, so we'd see if the bug gets fixed.

**Comment by pnkfelix** [comment]
> I think the problem arises from making decision based on the _previous_ state of the object files in combination with the _current_ import map. If the two things match up, i.e. making decisions about the previous object files based on the previous import map (which always accurately describes them), then the problem would not arise.
> 
> I'm generally very uneasy about keeping around data from sessions `N-x` where `x > 1`. That could add a kind of indeterminism unless you re-create the entire version history of compiling a crate (which would make for a really nasty debugging experience).

But that is indeed the problem: the so-called "previous object files" can come from arbitrarily distant compilation sessions. So I do not see how we can avoid accumulating information from an arbitrary number of sessions.

**Comment by michaelwoerister** [comment]
> But that is indeed the problem: the so-called "previous object files" can come from arbitrarily distant compilation sessions.

Yes, but the import map is always re-computed from scratch from the entire set of modules, including the older ones. That will make it up-to-date.

**Comment by michaelwoerister** [comment]
In other words: The import map should always be the same, regardless of what your cache looks like and even if there is no cache. That makes it a function of the current state of the source code. (<= that describes more accurately what I mean).

**Comment by pnkfelix** [comment]
Okay. I think I see what you are saying. It seems like it the import map *can* change in non-local ways though, right? I mean, the `[A] -> [B -> C] <- [D]` example seems to illustrate that a change to `D` can cause the import map for `[A]` to change.

This non-locality property doesn't contradict what you said. I just want to have a clear mental model.

File: src/librustc_codegen_llvm/back/lto.rs [hunk 2]
```diff
@@ -470,13 +479,26 @@ fn thin_lto(cgcx: &CodegenContext<LlvmCodegenBackend>,
...
-            ThinLTOImports::from_thin_lto_data(data)
+        let (import_map_path, prev_import_map, curr_import_map) =
+            if let Some(ref incr_comp_session_dir) = cgcx.incr_comp_session_dir
+        {
+            let path = incr_comp_session_dir.join(THIN_LTO_IMPORTS_INCR_COMP_FILE_NAME);
+            let prev = if path.exists() {
+                // FIXME: can/should we recover from IO error occuring here
+                // (e.g. by clearing green_modules), rather than panicking from
+                // unwrap call?
+                Some(ThinLTOImports::load_from_file(&path).unwrap())
```
Comment (michaelwoerister) [inline src/librustc_codegen_llvm/back/lto.rs]: We can recover by treating everything as changed somehow. Returning `None` here and making the code below handled that would be an option.

File: src/librustc_codegen_llvm/back/lto.rs [hunk 3]
```diff
@@ -525,10 +566,34 @@ fn thin_lto(cgcx: &CodegenContext<LlvmCodegenBackend>,
             }));
         }
 
+        // Save the accumulated ThinLTO import information
```
Comment (michaelwoerister) [inline src/librustc_codegen_llvm/back/lto.rs]: `// Save the current ThinLTO import information for the next compilation session`

File: src/librustc_codegen_llvm/back/lto.rs [hunk 4]
```diff
@@ -525,10 +566,34 @@ fn thin_lto(cgcx: &CodegenContext<LlvmCodegenBackend>,
...
 }
 
+/// Given two slices, each with no repeat elements. returns true if and only if
+/// the two slices have the same contents when considered as sets (i.e. when
+/// element order is disregarded).
+fn equivalent_as_sets(a: &[String], b: &[String]) -> bool {
+    // cheap path: unequal lengths means cannot possibly be set equivalent.
+    if a.len() != b.len() { return false; }
+    // fast path: before sorting, check if inputs are equivalent as is.
+    if a == b { return true; }
```
Comment (michaelwoerister) [inline src/librustc_codegen_llvm/back/lto.rs]: You could also create two `FxHashSet`s and compare those.

**Comment by michaelwoerister** [comment]
Hurray! I was able to construct a pretty small test case for this:
```rust
// ./src/test/incremental/thinlto/import_removed.rs

// revisions: cfail1 cfail2
// compile-flags: -O -Zhuman-readable-cgu-names -Cllvm-args=-import-instr-limit=10
// build-pass

// TODO: Add proper description.

fn main() {
    foo::foo();
    bar::baz();
}

mod foo {

    // In cfail1, foo() gets inlined into main.
    // In cfail2, ThinLTO decides that foo() does not get inlined into main, and
    // instead bar() gets inlined into foo(). But faulty logic in our incr.
    // ThinLTO implementation thought that `main()` is unchanged and thus reused
    // the object file still containing a call to the now non-existant bar().
    pub fn foo(){
        bar()
    }

    // This function needs to be big so that it does not get inlined by ThinLTO
    // but *does* get inlined into foo() once it is declared `internal` in
    // cfail2.
    pub fn bar(){
        println!("quux1");
        println!("quux2");
        println!("quux3");
        println!("quux4");
        println!("quux5");
        println!("quux6");
        println!("quux7");
        println!("quux8");
        println!("quux9");
    }
}

mod bar {

    #[inline(never)]
    pub fn baz() {
        #[cfg(cfail1)]
        {
            crate::foo::bar();
        }
    }
}
```

This test case fails with the expected error on a recent nightly. I have not tested whether the fix in this PR makes it pass, but it should.

File: src/librustc_codegen_llvm/back/lto.rs (hunk 4 above)
Comment (pnkfelix) [reply src/librustc_codegen_llvm/back/lto.rs]: i debated about that. I guess it would make sense in terms of expected asymptotic behavior, right? (And its just a question of how the constant factors associated with hash-set construction compare to sorting a vector of str)

File: src/librustc_codegen_llvm/back/lto.rs (hunk 2 above)
Comment (pnkfelix) [reply src/librustc_codegen_llvm/back/lto.rs]: You're right. That would probably be best.

File: src/librustc_codegen_llvm/back/lto.rs (hunk 4 above)
Comment (pnkfelix) [reply src/librustc_codegen_llvm/back/lto.rs]: I'll go ahead and put FxHashSet in. I'm not in the game of trying to microoptimize this beyond what I've already done.

File: src/librustc_codegen_llvm/back/lto.rs (hunk 3 above)
Comment (pnkfelix) [reply src/librustc_codegen_llvm/back/lto.rs]: will do

**Comment by pnkfelix** [comment]
(okay this is ready for re-review; I incororated all feedback and adapted the test case, thanks @michaelwoerister !)

**Comment by JohnCSimon** [comment]
Ping from triage: 
@michaelwoerister - can you please review this pr?

File: src/librustc_codegen_llvm/back/lto.rs [hunk 5]
```diff
@@ -500,18 +522,36 @@ fn thin_lto(cgcx: &CodegenContext<LlvmCodegenBackend>,
...
+            //
+            // This strategy means we can always save the computed imports as
+            // canon: when we reuse the post-ThinLTO version, condition (3.)
+            // ensures that the curent import set is the same as the previous
+            // one. (And of course, when we don't reuse the post-ThinLTO
+            // version, the current import set *is* the correct one, since we
+            // are doing the ThinLTO in this current compilation cycle.)
+            //
+            // See rust-lang/rust#59535.
+            if let (Some(prev_import_map), true) =
```
Comment (michaelwoerister) [inline src/librustc_codegen_llvm/back/lto.rs]: Interesting pattern `:)`

**Comment by michaelwoerister** [comment]
Thanks for updating the PR, @pnkfelix!
I see you left the big test case in. I can imagine that it is a bit brittle, with linker scripts and such. I'm going to r+ but if the test case breaks on any platform, I think we should just remove it.

@bors r+

**Comment by Centril** [comment]
Failed in https://github.com/rust-lang/rust/pull/67412#issuecomment-567331161, @bors r- rollup=never p=1

**Comment by michaelwoerister** [comment]
@pnkfelix, how do you feel about removing the `run-make` test case?

**Comment by pnkfelix** [comment]
yeah okay lets kill the `run-make` test case, sure

**Comment by pnkfelix** [comment]
(I went ahead and squashed since I was rebasing anyway to remove the `run-make` based test.)
