### PR TITLE
Translate the virtual `/rustc/$hash` prefix back to a real directory.

### LINKED ISSUE #53081: sysroot spans are not printed on some targets (affected: Debian, rust-lang's own i586; unaffected: Fedora)
**EDIT**(@eddyb): For a detailed update/explanation, see https://github.com/rust-lang/rust/issues/53081#issuecomment-558804239.

<hr/>

I'm trying to track down why we have this diff on all arches, which causes that test to fail:

[Test](https://github.com/rust-lang/rust/blob/1.28.0/src/test/ui/impl-trait/impl-generic-mismatch.rs), [test output](https://github.com/rust-lang/rust/blob/1.28.0/src/test/ui/impl-trait/impl-generic-mismatch.stderr)

~~~~
29	   |
30	LL |     fn hash(&self, hasher: &mut impl Hasher) {}
31	   |                                 ^^^^^^^^^^^ expected generic parameter, found `impl Trait`
-	   | 
-	  ::: $SRC_DIR/libcore/hash/mod.rs:185:13
-	   |
-	LL |     fn hash<H: Hasher>(&self, state: &mut H);
-	   |             - declaration in trait here
37	
38	error: aborting due to 3 previous errors
39	
~~~~

The test passes [on Fedora](https://kojipkgs.fedoraproject.org//packages/rust/1.28.0/1.fc29/data/logs/ppc64le/build.log).

Two main things we're doing differently in Debian is that we're currently using cargo 0.27 to build (rather than cargo 0.28) and we also [omit some components](https://salsa.debian.org/rust-team/rust/blob/debian/experimental/debian/patches/d-ignore-removed-submodules.patch). However I don't see why either of these should affect the above test output. I also can't see why [our other patches](https://salsa.debian.org/rust-team/rust/tree/debian/experimental/debian/patches) should affect it.

### LINKED ISSUE #53486: rustup component rust-src should be used to load cross-crate sources.
If I take this arbitrary example (that supports cross-crate spans, via `tcx.def_span(...)`):
```rust
struct Foo;
impl Extend<()> for Foo {
    fn extend(&mut self, _: impl IntoIterator<Item = ()>) {}
}
fn main() {}
```

and compiling it with a local rustc build, I get this error (note the `libcore` snippet):
(**NB**: if that snippet disappears, find other `tcx.def_span(...)`-using diagnostics and replace the test)
```rust
error[E0643]: method `extend` has incompatible signature for trait
   --> xcrate-span.rs:3:29
    |
3   |     fn extend(&mut self, _: impl IntoIterator<Item = ()>) {}
    |                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected generic parameter, found `impl Trait`
    |
   ::: /home/eddy/Projects/rust-2/src/libcore/iter/traits.rs:355:15
    |
355 |     fn extend<T: IntoIterator<Item=A>>(&mut self, iter: T);
    |               - declaration in trait here
```
but if try with `rustup`-provided `rustc`, I only get this shorter error:
```rust
error[E0643]: method `extend` has incompatible signature for trait
   --> xcrate-spans.rs:3:29
    |
3   |     fn extend(&mut self, _: impl IntoIterator<Item = ()>) {}
    |                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected generic parameter, found `impl Trait`
```

But `$(rustc --print=sysroot)/lib/rustlib/src/rust/src/libcore/iter/traits.rs` *does exist*, because I have the `rust-src` component enabled (it's enabled by default, which makes it likely to exist for most users), so it should be possible *in theory*, to teach rustc to look up certain paths relative to `lib/rustlib/src/rust` inside the sysroot, if it exists.

Running this:
```sh
strings $(rustc --print=sysroot)/lib/rustlib/*/lib/libcore-*.rlib | rg 'iter/traits\.rs'
```
shows that `/checkout/src/libcore/iter/traits.rs` and `libcore/iter/traits.rs` both exist in the `rlib`, and I assume the former is the one that it tries to load - we can even test this:
```sh
# Let's live a little...
sudo ln -s $(rustc --print=sysroot)/lib/rustlib/src/rust /checkout
```
Trying the test again, we now get:
```rust
error[E0643]: method `extend` has incompatible signature for trait
   --> xcrate-spans.rs:3:29
    |
3   |     fn extend(&mut self, _: impl IntoIterator<Item = ()>) {}
    |                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected generic parameter, found `impl Trait`
    |
   ::: /checkout/src/libcore/iter/traits.rs:355:15
    |
355 |     fn extend<T: IntoIterator<Item=A>>(&mut self, iter: T);
    |               - declaration in trait here
```

So it's definitely compatible, the hash check passes and whatnot, we just need to rename `/checkout` to something artificial like `$rust`, I'm guessing.

```sh
# ... but also clean up afterwards.
sudo rm /checkout
```

cc @alexcrichton @rust-lang/dev-tools @rust-lang/compiler

### PR DESCRIPTION
**Pull request by eddyb**
Closes #53486 and fixes #53081, by undoing the remapping to `/rustc/$hash` on the fly, when appropriate (e.g. our testsuites, or user crates that depend on `libstd`), but not during the Rust build itself (as that could leak the absolute build directory into the artifacts, breaking deterministic builds).

Tested locally by setting `remap-debuginfo = true` in `config.toml`, which without these changes, was causing 56 tests to fail (see https://github.com/rust-lang/rust/issues/53081#issuecomment-606703215 for more details).

cc @Mark-Simulacrum @alexcrichton @ehuss

### CODE REVIEW

File: src/bootstrap/lib.rs [hunk 1]
```diff
@@ -740,19 +740,18 @@ impl Build {
...
             GitRepo::Rustc => {
                 let sha = self.rust_sha().unwrap_or(channel::CFG_RELEASE_NUM);
-                format!("/rustc/{}", sha)
+                Some(format!("/rustc/{}", sha))
             }
-            GitRepo::Llvm => String::from("/rustc/llvm"),
-        };
-        Some(format!("{}={}", self.src.display(), path))
+            GitRepo::Llvm => Some(String::from("/rustc/llvm")),
+        }
```
Comment (estebank) [inline src/bootstrap/lib.rs:754]:
```suggest
        Some(match which {
            GitRepo::Rustc => {
                let sha = self.rust_sha().unwrap_or(channel::CFG_RELEASE_NUM);
                format!("/rustc/{}", sha)
            }
            GitRepo::Llvm => String::from("/rustc/llvm"),
        })
```

File: src/etc/generate-deriving-span-tests.py [hunk 2]
```diff
@@ -15,9 +15,6 @@
     os.path.join(os.path.dirname(__file__), '../test/ui/derives/'))
 
 TEMPLATE = """\
-// FIXME: missing sysroot spans (#53081)
-// ignore-i586-unknown-linux-gnu
-// ignore-i586-unknown-linux-musl
```
Comment (estebank) [inline src/etc/generate-deriving-span-tests.py:20]: 🎉

**Comment by RalfJung** [comment]
This is great. :)
Is there a good way to grep for tests that might also have had this problem, but failed to mention 53081 in the FIXME? (I assume you grepped for 53081.) Some time ago I tried to make them all carry this FIXME, but more not properly annotated tests could have crept in.

"ignore on 32bit targets" was a common work-around for this before we figured out which exact targets are affected, whatever the `// ignore` clause for that is. Also all of these have `$SRC_DIR` in their `stderr` file, I suppose.

File: src/bootstrap/lib.rs (hunk 1 above)
Comment (eddyb) [reply src/bootstrap/lib.rs:754]: I tend to do that for my own code, wasn't sure if it would be proper inside the Rust codebase.

**Comment by eddyb** [comment]
@RalfJung 57 files mention `$SRC_DIR`, out of which 56 are the tests that were failing before this PR and the last one is the implementation in `src/tools/compiletest/src/runtest.rs`.

File: src/bootstrap/lib.rs (hunk 1 above)
Comment (RalfJung) [reply src/bootstrap/lib.rs:754]: I would say it is. ;)

File: src/librustc_session/session.rs [hunk 3]
```diff
@@ -1056,6 +1067,37 @@ fn build_session_(
...
+            return Some(sysroot_candidate);
+        }
+
+        // As a fallback, check if the `sysroot` is inside a Rust build dir,
+        //  i.e. it ends in `build/$CFG_COMPILER_HOST_TRIPLE/stage{0-sysroot,1,2,3}`.
+        let mut sysroot_components = sysroot.components();
+        let last = sysroot_components.next_back()?.as_os_str();
+        if last == "stage0-sysroot" || last == "stage1" || last == "stage2" || last == "stage3" {
+            if sysroot_components.next_back()?.as_os_str() == host_triple {
+                if sysroot_components.next_back()?.as_os_str() == "build" {
```
Comment (Mark-Simulacrum) [inline src/librustc_session/session.rs:1088]: Note that on CI, at least, this will fail -- there we sometimes have the build directory in `obj/build`. Maybe we should have rustbuild tell the compiler what the prefix to strip is instead?

Comment (eddyb) [reply src/librustc_session/session.rs:1088]: We might want to do the symlink approach instead then, where `src/bootstrap` symlinks the checkout to `build/$triple/stage{0-sysroot,1,2,3}/lib/rustlib/src/rust`.

I just don't know what we'll have to do on platforms where that's not directly an option.

Comment (eddyb) [reply src/librustc_session/session.rs:1088]: Bonus: it would make `cargo`'s `-Z build-std` and presumably RLS, able to find the Rust sources, for locally built `rustup` toolchains.

Comment (Mark-Simulacrum) [reply src/librustc_session/session.rs:1088]: Hm, why would we want the symlink approach over an environment variable read or something (at runtime, I guess, set during our tests?)

Something like `RUST_SRC_PATH` which I think other tooling (RLS, perhaps?) uses

Comment (Mark-Simulacrum) [reply src/librustc_session/session.rs:1088]: But to be clear I think symlinking is fine (or hardlinking I guess, too, though could be more finicky).

I don't know whether platform support would be a problem -- if we can get it past bors though seems like we should land it, and we can make it optional I think, in the sense that you need it for tests to pass but if you don't have it things won't fail to build entirely.

Comment (eddyb) [reply src/librustc_session/session.rs:1088]: > Hm, why would we want the symlink approach over an environment variable read or something (at runtime, I guess, set during our tests?)

Because `rustup` places `rust-src` in a certain directory, and presumably distros can too, so we'd want to use that, and using a symlink would transparently let that work for local build sysroots, without adding an insta-stable env var.

> and we can make it optional I think, in the sense that you need it for tests to pass but if you don't have it things won't fail to build entirely.

Ah, good point, do we have a way for `src/bootstrap` to emit a warning if it tried something and that failed?
I'm thinking I would try to create the symlink, then do the same check `rustc` does (look for `src/libstd/lib.rs` inside there), and if either fails, warn instead of failing the build.

Comment (Mark-Simulacrum) [reply src/librustc_session/session.rs:1088]: Just eprintln should work fine.

I was suggesting that we use the environment variable as the fall back to normal detection, not as the only option. But I agree I think that if we can get the symlinks to work well we should.

Comment (RalfJung) [reply src/librustc_session/session.rs:1088]: @eddyb would that symlink also supersede the [special treatment Miri currently needs](https://github.com/rust-lang/miri/blob/master/src/bin/cargo-miri.rs#L309-L329) to find the sources when built against a local toolchain?

Comment (eddyb) [reply src/librustc_session/session.rs:1088]: @RalfJung Oh wow I wasn't aware of that hack, I wonder if other tools also do this.
Yes, although I'm not sure what will happen on Windows.
*However*, [`std::os::windows::fs::symlink_dir`](https://doc.rust-lang.org/std/os/windows/fs/fn.symlink_dir.html) does exist, presumably it creates a NTFS "junction"?

So we might be set on all platforms we care about, barring any odd filesystems where `symlink`s aren't supported or banned by system policy.

Comment (mati865) [reply src/librustc_session/session.rs:1088]: @eddyb it won't work for every Windows user though: https://github.com/rust-lang/rust/blob/30ddb5a8c1e85916da0acdc665d6a16535a12dd6/src/libstd/sys/windows/fs.rs#L760-L763

Comment (ollie27) [reply src/librustc_session/session.rs:1088]: @eddyb rustbuild already has a `symlink_dir` function which should do the right thing: https://github.com/rust-lang/rust/blob/99009bf31992fb9257b84550dbf7cb509f987952/src/bootstrap/util.rs#L131-L133

Comment (eddyb) [reply src/librustc_session/session.rs:1088]: Yeah I'll be using the rustbuild function. Also, this will only affect CI and a tiny subset of people building Rust (either using `remap-debuginfo = true` like CI, or testing `miri`, if `miri` removes it hack). And won't break the build if symlinking fails.

Comment (RalfJung) [reply src/librustc_session/session.rs:1088]: Miri tested via `./x.py test src/tools/miri` [does not even rely on this hack](https://github.com/rust-lang/rust/blob/235938d1acdd93d6641a741c81f64e415b786751/src/bootstrap/test.rs#L388).

**Comment by ehuss** [comment]
There were some concerns noted [here](https://github.com/rust-lang/rust/issues/53486#issuecomment-414428219) about how suggestions are exposed for cross-crate sources. Is that still a concern?  Does `rustc` know not to show suggestions for things in the standard library?  I've been trying to think of some way to concoct an example, but haven't succeeded.

**Comment by eddyb** [comment]
@ehuss It only points to the standard library to note some things, like trait/type definitions, IME, most diagnostic logic check `is_imported`, especially suggestions and lints.

You can search the test suite for `$SRC_DIR`, or just look at the diff of this PR, those are all the tests where libstd shows up.
You'll get far more though, if you enable `-Z macro-backtrace` (which most tests don't).

<hr/>

Ideally we'd have a way to check inside the compiler if the sources are user-editable, and only emit suggestions then, does `rustup` make `rust-src` and Cargo its `~/.cargo/cache`, read-only?
That'd be a nice way to hint to `rustc` to never emit suggestions for those files (i.e. we could gate this inside the diagnostic code itself, instead of in every place where they're emitted).

Kind of hard to test though, unless we made some test files read-only through `git`?

Bonus: if a suggestion arises while *building Rust itself*, then it would be fine for to point to the standard library, in some situations (we'd also get this if Cargo hinted workespaces to `rustc` directly).

File: src/bootstrap/compile.rs [hunk 4]
```diff
@@ -633,6 +633,30 @@ impl Step for Sysroot {
...
+                builder.src.display(),
+                e,
+            );
+            if builder.config.rust_remap_debuginfo {
+                eprintln!(
+                    "warning: some `src/test/ui` tests will fail when lacking `{}`",
+                    sysroot_lib_rustlib_src_rust.display(),
+                );
+            }
+        }
```
Comment (Mark-Simulacrum) [inline src/bootstrap/compile.rs:658]: FWIW, I'm not 100% sure this won't make us package up the source files into the normal components, I'll run a try build to check.

**Comment by Mark-Simulacrum** [comment]
@bors try

I think this looks good to land. The concern over linking to std from the sysroot seems largely fine to leave for a future discussion -- I believe it's true that this PR might make things worse (showing stuff from std as well) but it doesn't really change our decision making at all, so orthogonal to some extent.

I want to check that dist artifacts aren't suddenly full of sources though (and that dist doesn't break). I don't think it will, as we only copy dylibs and rlibs and such so I think we should be fine. But good to check.

Ideally we'd probably check that rustup can install rust-src tarball as well, but that's harder as we don't ship it from the try builder I think? I'll look into that separately.

**Comment by estebank** [comment]
> Ideally we'd have a way to check inside the compiler if the sources are user-editable, and only emit suggestions then

Suggestions generally lean towards the assumption that the user can only change the usage of an existing API, as we assume that for example a `trait`'s item signatures are correct while the `impl` might be wrong. This is not universal, but common enough that there should be few real issues with us suggesting users to change code in the stdlib.

**Comment by eddyb** [comment]
Looks like the base toolchain is clean of `lib/rustlib/src`:
```
$ rustup-toolchain-install-master 40f2b445cd1c6c4e72d663d23c6d1bef2c674ad4
$ ls ~/.rustup/toolchains/40f2b445cd1c6c4e72d663d23c6d1bef2c674ad4/lib/rustlib/
etc/  x86_64-unknown-linux-gnu/
```

I'm rebasing now, after that I think we're good to go?

**Comment by mati865** [comment]
@eddyb you have to tell `rustup-toolchain-install-master` to install the component.
Like this:
```
$ rustup-toolchain-install-master 40f2b445cd1c6c4e72d663d23c6d1bef2c674ad4 -c rust-src
$ ls ~/.rustup/toolchains/40f2b445cd1c6c4e72d663d23c6d1bef2c674ad4/lib/rustlib/src/rust/src
build_helper  libpanic_abort   libprofiler_builtins  libtest    tools
liballoc      libpanic_unwind  libstd                libunwind
libcore       libproc_macro    libterm               stdarch
```

**Comment by eddyb** [comment]
@mati865 Yes, that works and I've used it for https://github.com/rust-lang/rust/issues/70025#issuecomment-607697742 (see the last code block at the end).

But I was referring to the thing @Mark-Simulacrum wanted to check, which is that we *don't* include the entire `rust-lang/rust` repository in `lib/rustlib/src` *without* the `rust-src` component.

The reason for that concern is the the symlink, e.g. for a local build I now have, with this PR:
```
$ ls -l ~/.rustup/toolchains/rust-1-stage1/lib/rustlib/src/
total 1
lrwxrwxrwx 1 eddy users 26 Apr  2 09:01 rust -> /home/eddy/Projects/rust-1/
```

**Review by Mark-Simulacrum — APPROVED** [review]

**Comment by Mark-Simulacrum** [comment]
@bors r+ rollup=never

I agree! Marking to not roll this up as it's touching some relatively finicky stuff that I'd like to be able to bisect precisely if needed (in particular dist-related code), though given the try build it might not be truly necessary.

**Comment by jonas-schievink** [comment]
@bors p=2

Seems like this could fix https://github.com/rust-lang/rust/issues/70025, so let's try to land it quickly

**Comment by pnkfelix** [comment]
We may need to revert this PR if I cannot find a way to fix #70924 soonish...
