### PR TITLE
Suggest using a qualified path in patterns with inconsistent bindings

### LINKED ISSUE #50831: Better error message when missing prefix in multiple patterns
Given the example code:

```rust
enum E { A, B, C }
fn f() -> E { unimplemented!(); }

fn main() {
    match f() {
        A => print!("It was A!"),
        _ => print!("Something else"),
    }
}
```

I get a really nice warning message about what I did wrong:

```
warning[E0170]: pattern binding `A` is named the same as one of the variants of the type `E`
 --> src/main.rs:6:9
  |
6 |         A => print!("It was A!"),
  |         ^
  |
  = help: if you meant to match on a variant, consider making the path in the pattern qualified: `E::A`
```

However, if I change the main function to match multiple patterns:

```rust
fn main() {
    match f() {
        A => print!("It was A!"),
        B | C => print!("It was B or C!"),
    }
}
```

The error message is really confusing with no hint how to fix it:

```
error[E0408]: variable `B` is not bound in all patterns
 --> src/main.rs:8:13
  |
8 |         B | C => print!("It was B or C!"),
  |         -   ^ pattern doesn't bind `B`
  |         |
  |         variable not in all patterns
```

Please expand the error message for the second case to look a bit more like the first case.

### PR DESCRIPTION
**Pull request by jakubadamw**
A program like the following one:

```rust
enum E { A, B, C }
fn f(x: E) -> bool {
    match x {
        A | B => false,
        C => true
    }
}
```

is rejected by the compiler due to `E` variant paths not being in scope.
In this case `A`, `B` are resolved as pattern bindings and consequently
the pattern is considered invalid as the inner or-patterns do not bind
to the same set of identifiers.

This is expected but the compiler errors that follow could be surprising
or confusing to some users. This commit adds a help note explaining that
if the user desired to match against variants or consts, they should use
a qualified path. The help note is restricted to cases where the identifier
starts with an upper-case sequence so as to reduce the false negatives.

Since this happens during resolution, there's no clean way to check what
it is the patterns match against. The syntactic criterium, however, is in line
with the convention that's assumed by the `non-camel-case-types` lint.

Fixes #50831.

### CODE REVIEW

**Comment by jakubadamw** [comment]
r? @estebank 

I did a bit of a logical clean-up in the binding consistency check and seeing this is likely a moderately hot path, could we please have a perf run for this? I'm not sure how to trigger it. I guess special privileges are needed. :)

File: src/librustc_resolve/lib.rs [hunk 1]
```diff
@@ -331,21 +332,30 @@ fn resolve_struct_error<'sess, 'a>(resolver: &'sess Resolver<'_>,
             err
         }
         ResolutionError::VariableNotBoundInPattern(binding_error) => {
-            let target_sp = binding_error.target.iter().cloned().collect::<Vec<_>>();
+            let BindingError { name, target, origin, could_be_variant } = binding_error;
+
+            let target_sp = target.iter().cloned().collect::<Vec<_>>();
```
Comment (Centril) [inline src/librustc_resolve/lib.rs]:
```suggestion
            let target_sp = target.iter().copied().collect::<Vec<_>>();
```

File: src/librustc_resolve/lib.rs [hunk 2]
```diff
@@ -331,21 +332,30 @@ fn resolve_struct_error<'sess, 'a>(resolver: &'sess Resolver<'_>,
...
+            let origin_sp = origin.iter().cloned().collect::<Vec<_>>();
```
Comment (Centril) [inline src/librustc_resolve/lib.rs]:
```suggestion
            let origin_sp = origin.iter().copied().collect::<Vec<_>>();
```

File: src/librustc_resolve/lib.rs [hunk 3]
```diff
@@ -331,21 +332,30 @@ fn resolve_struct_error<'sess, 'a>(resolver: &'sess Resolver<'_>,
...
-                err.span_label(sp, format!("pattern doesn't bind `{}`", binding_error.name));
+                err.span_label(sp, format!("pattern doesn't bind `{}`", name));
             }
-            let origin_sp = binding_error.origin.iter().cloned();
             for sp in origin_sp {
                 err.span_label(sp, "variable not in all patterns");
             }
+            if *could_be_variant {
+                let help_msg = format!(
+                    "if you meant to match on a variant or a const, consider \
```
Comment (Centril) [inline src/librustc_resolve/lib.rs]:
```suggestion
                    "if you meant to match on a variant or a `const` item, consider \
```

File: src/librustc_resolve/lib.rs [hunk 4]
```diff
@@ -331,21 +332,30 @@ fn resolve_struct_error<'sess, 'a>(resolver: &'sess Resolver<'_>,
...
+                     making the path in the pattern qualified: `?::{}`", name);
```
Comment (Centril) [inline src/librustc_resolve/lib.rs]:
```suggestion
                     making the path in the pattern qualified: `?::{}`",
                     name,
                 );
```

File: src/librustc_resolve/lib.rs [hunk 5]
```diff
@@ -3181,61 +3191,53 @@ impl<'a> Resolver<'a> {
...
         let mut inconsistent_vars = FxHashMap::default();
-        for (i, p) in pats.iter().enumerate() {
+        for p in pats.iter() {
             let map_i = self.binding_mode_map(&p);
-
-            for (j, q) in pats.iter().enumerate() {
-                if i == j {
+            for q in pats.iter() {
+                if p.id == q.id {
                     continue;
```
Comment (Centril) [inline src/librustc_resolve/lib.rs]: Drive by improvement opportunity: Convert this to `pats.iter().filter(...)` ?

File: src/librustc_resolve/lib.rs [hunk 6]
```diff
@@ -3181,61 +3191,53 @@ impl<'a> Resolver<'a> {
...
     fn check_consistent_bindings(&mut self, pats: &[P<Pat>]) {
-        if pats.is_empty() {
+        if pats.len() <= 1 {
             return;
         }
 
         let mut missing_vars = FxHashMap::default();
         let mut inconsistent_vars = FxHashMap::default();
-        for (i, p) in pats.iter().enumerate() {
+        for p in pats.iter() {
```
Comment (Centril) [inline src/librustc_resolve/lib.rs]: Drive by improvement opportunity: `p` -> `pat_outer` and `q` -> `pat_inner`?

File: src/librustc_resolve/lib.rs [hunk 7]
```diff
@@ -3181,61 +3191,53 @@ impl<'a> Resolver<'a> {
     // Checks that all of the arms in an or-pattern have exactly the
     // same set of bindings, with the same binding modes for each.
     fn check_consistent_bindings(&mut self, pats: &[P<Pat>]) {
-        if pats.is_empty() {
+        if pats.len() <= 1 {
             return;
```
Comment (Centril) [inline src/librustc_resolve/lib.rs]: Shouldn't this be `bug!("An or-pattern cannot have < 2 patterns by construction");`?

Comment (jakubadamw) [reply src/librustc_resolve/lib.rs]: @Centril, not really, all arms of a `match` go through this check, including those with a single pattern. 🙂

File: src/librustc_resolve/lib.rs [hunk 8]
```diff
@@ -331,21 +332,30 @@ fn resolve_struct_error<'sess, 'a>(resolver: &'sess Resolver<'_>,
...
             );
             for sp in target_sp {
-                err.span_label(sp, format!("pattern doesn't bind `{}`", binding_error.name));
+                err.span_label(sp, format!("pattern doesn't bind `{}`", name));
             }
-            let origin_sp = binding_error.origin.iter().cloned();
             for sp in origin_sp {
                 err.span_label(sp, "variable not in all patterns");
             }
+            if *could_be_variant {
```
Comment (jakubadamw) [inline src/librustc_resolve/lib.rs]:
```suggestion
            if *could_be_path {
```

File: src/librustc_resolve/lib.rs (hunk 7 above)
Comment (Centril) [reply src/librustc_resolve/lib.rs]: Heh... can we float that check to those locations instead? As-is that doc comment is pretty misleading so at least if the code stays the same the comment should be changed.

**Comment by jakubadamw** [comment]
@rust-timer build 8261083

**Comment by Mark-Simulacrum** [comment]
@rust-timer build 8261083

**Comment by jakubadamw** [comment]
@Centril, thank you for the review. I addressed all your comments.

**Comment by petrochenkov** [comment]
Blocked on https://github.com/rust-lang/rust/pull/63400.

**Comment by petrochenkov** [comment]
Thanks!
@bors r+
