### PR TITLE
Stop calling unwrap when format foreign has trailing dollar

### LINKED ISSUE #137580: ICE: `called Result::unwrap() on an Err value: ParseIntError { kind: PosOverflow }` in `rustc_builtin_macros/src/format_foreign.rs`
### Code

Be aware of quotation mark locations.

```Rust
fn main() {
    println!("%100000$, 1);
    println!(s%     65536", 1337f64);
}
```

<details><summary><strong>Original Code (Mutant from Fuzzing)</strong></summary>
<p>

```Rust
fn main() {
    println!("%100000$, 1);
    //~^ ERROR argument never used
    println!(s%     65536", 1337f64);
    //~^ ERROR argument never used
}


// /home/jb/workspace/seeds_250219/tests/ui/macros/println-percent-prefix-num-issue-125002.rs
```

</p>
</details>

### Meta

`rustc --version --verbose`:
```
rustc 1.87.0-nightly (617aad8c2 2025-02-24)
binary: rustc
commit-hash: 617aad8c2e8783f6df8e5d1f8bb1e4bcdc70aa7b
commit-date: 2025-02-24
host: x86_64-apple-darwin
release: 1.87.0-nightly
LLVM version: 20.1.0
```

### Error output

```
thread 'rustc' panicked at compiler/rustc_builtin_macros/src/format_foreign.rs:417:85:
called `Result::unwrap()` on an `Err` value: ParseIntError { kind: PosOverflow }
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
thread 'rustc' panicked at compiler/rustc_builtin_macros/src/format_foreign.rs:417:85:
called `Result::unwrap()` on an `Err` value: ParseIntError { kind: PosOverflow }
stack backtrace:
   0: _rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::result::unwrap_failed
   3: <rustc_builtin_macros::format_foreign::printf::Substitutions as core::iter::traits::iterator::Iterator>::next
   4: rustc_builtin_macros::format::make_format_args
   5: rustc_builtin_macros::format::expand_format_args_impl
   6: <rustc_expand::expand::MacroExpander>::expand_invoc
   7: <rustc_expand::expand::MacroExpander>::fully_expand_fragment
   8: <rustc_expand::expand::MacroExpander>::expand_crate
   9: rustc_interface::passes::resolver_for_lowering_raw
      [... omitted 2 frames ...]
  10: rustc_interface::passes::create_and_enter_global_ctxt::<core::option::Option<rustc_interface::queries::Linker>, rustc_driver_impl::run_compiler::{closure#0}::{closure#2}>
  11: rustc_interface::interface::run_compiler::<(), rustc_driver_impl::run_compiler::{closure#0}>::{closure#1}
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

error: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: please make sure that you have updated to the latest nightly

note: please attach the file at `/Volumes/T7/workspace/250225 scratch/codes/rustc-ice-2025-02-25T03_39_56-16081.txt` to your bug report

query stack during panic:
#0 [resolver_for_lowering_raw] getting the resolver for lowering
end of query stack
```

</p>
</details>

### Note
- ICE location: `compiler/rustc_builtin_macros/src/format_foreign.rs Line-417`
https://github.com/rust-lang/rust/blob/617aad8c2e8783f6df8e5d1f8bb1e4bcdc70aa7b/compiler/rustc_builtin_macros/src/format_foreign.rs#L409-L419

### PR DESCRIPTION
**Pull request by TaKO8Ki**
Fixes rust-lang/rust#137580

### CODE REVIEW

File: tests/ui/macros/format-foreign-dollar-without-spec.rs [hunk 1]
```diff
@@ -0,0 +1,4 @@
+fn main() {
```
Comment (nnethercote) [inline tests/ui/macros/format-foreign-dollar-without-spec.rs:2]: Add a comment here saying that this was issue #137580, then remove the old crashtest, and then r=me.
