### PR TITLE
Avoid using env::temp when linking a binary

### LINKED ISSUE #139963: rustc_codegen_ssa should write temporary files to the output directory
In most places in the compiler temporary files are written to the output directory (using `tempdir_in`). E.g.:

https://github.com/rust-lang/rust/blob/15c4ccef03116e6a509199e845ad266306a0e9ee/compiler/rustc_metadata/src/fs.rs#L48-L50

https://github.com/rust-lang/rust/blob/15c4ccef03116e6a509199e845ad266306a0e9ee/compiler/rustc_codegen_ssa/src/back/archive.rs#L504-L506

The one exception is `compiler/rustc_codegen_ssa/src/back/link.rs` which writes to the OS temp directory (note the use of `tempdir` instead of `tempdir_in`):

https://github.com/rust-lang/rust/blob/15c4ccef03116e6a509199e845ad266306a0e9ee/compiler/rustc_codegen_ssa/src/back/link.rs#L103-L105

I don't think there is a good reason to maintain this inconsistency?

Note that this affects [`-C save-temps`](https://doc.rust-lang.org/rustc/codegen-options/index.html) where you have to go hunting for the relevant temp file (or redirect the platform-specific temp directory environment variable).

### PR DESCRIPTION
**Pull request by ChrisDenton**
*[View all comments](https://triagebot.infra.rust-lang.org/gh-comments/rust-lang/rust/pull/150311)*

This keeps all build artefacts (even temporary ones) within the build directory.

Fixes rust-lang/rust#139963

### CODE REVIEW

File: compiler/rustc_codegen_ssa/src/back/link.rs [hunk 1]
```diff
@@ -103,17 +103,18 @@ pub fn link_binary(
...
-            let path = MaybeTempDir::new(tmpdir, sess.opts.cg.save_temps);
             let output = out_filename(
                 sess,
                 crate_type,
                 outputs,
                 codegen_results.crate_info.local_crate_name,
             );
+            let tmpdir = TempDirBuilder::new()
+                .prefix("rustc")
+                .tempdir_in(output.parent().unwrap_or_else(|| Path::new(".")))
```
Comment (ChrisDenton) [inline compiler/rustc_codegen_ssa/src/back/link.rs:114]: This is a similar scheme as used for rustc_metadata https://github.com/rust-lang/rust/blob/0bd13c38df9a9a922bd8ec98ba7a8bc7e111860e/compiler/rustc_metadata/src/fs.rs#L45

**Review by Kivooeo — APPROVED** [review]
Looks like a reasonable change to me

*[View changes since this review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/rust/150311/0bd13c38df9a9a922bd8ec98ba7a8bc7e111860e..0bd709dbc59c838c490ee094e8c8d9de09045e91)*

**Comment by ChrisDenton** [comment]
Fixed the `invalid-tmpdir-env-var` test to check it doesn't ICE rather than looking for a particular message. Because rustc might no longer use the tempdir. If preserving the error message is important then I could find somewhere in the compiler to insert a check though I'm not sure that it's worth it.

**Comment by Kivooeo** [comment]
I don't think it's worth adding this check

r? me

File: tests/run-make/invalid-tmpdir-no-ice/rmake.rs
Comment (Kivooeo) [inline tests/run-make/invalid-tmpdir-no-ice/rmake.rs:1]: Should we rename this test? something like `invalid-tmpdir-no-ice`

**Review by Kivooeo — COMMENTED** [review]
One nit

*[View changes since this review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/rust/150311/0bd13c38df9a9a922bd8ec98ba7a8bc7e111860e..306bd5e3040580df4b20067c157f39e0ed5e4028)*

**Comment by Kivooeo** [comment]
r=me once CI is green

File: tests/run-make/invalid-tmpdir-no-ice/rmake.rs
Comment (ChrisDenton) [reply tests/run-make/invalid-tmpdir-no-ice/rmake.rs:1]: Sounds good to me. I did it as a separate commit to ensure diff tools see it as a rename.

**Comment by epage** [comment]
I should add that I'm looking at this from a cache design perspective.  What is the cacheable unit within Cargo both locally, in CI, and as we add cross-workspace and remote caching.

**Comment by ChrisDenton** [comment]
I think that sounds like a new feature. As far as I'm aware rustc doesn't really make that distinction atm wrt catchability. It does try to cleanup files it no longer needs for the build but that's about the extent of it (again, this is just my understanding).

Using the temp directory is annoying for artefacts you actually want to inspect or otherwise use since it uses a randomly generated name that can be hard to find in a sea of similarly named directories.

**Comment by ChrisDenton** [comment]
I could see it using a different directory but with `-Csave-temps` the user is explicitly asking for the tempories to be considered artefacts they will use. This is unlike, say, incremental which is essentially an implementation detail of a rustc feature (incremental compilation) and not really something that's intended to be used directly.
