### PR TITLE
fix `build --stage 2 compiler/rustc` panic

### LINKED ISSUE #90244: `x.py` panics when trying to build "stage3" compiler
I don't think there even is a stage3, so I think this is a bug in bootstrap. I haven't encountered this before. Rerunning the command produces the same panic. Despite the panic, `rustc +r2stage2 --help` works, presumably because the build has finished and `x.py` is trying to do extra steps by building a non-existent stage.

In case it helps, my branch's merge-base is 00d5e42e776da900049fe19087bc9b0057ec70cd. My branch only modifies the Miri engine, so I'm pretty sure it's unrelated to this bug.

```console
$ x build --stage 2 compiler/rustc
[...]
Copying stage1 rustc from stage1 (x86_64-apple-darwin -> x86_64-apple-darwin / x86_64-apple-darwin)
Assembling stage2 compiler (x86_64-apple-darwin)
Uplifting stage1 std (x86_64-apple-darwin -> x86_64-apple-darwin)
Copying stage2 std from stage1 (x86_64-apple-darwin -> x86_64-apple-darwin / x86_64-apple-darwin)
Uplifting stage1 rustc (x86_64-apple-darwin -> x86_64-apple-darwin)
Copying stage2 rustc from stage1 (x86_64-apple-darwin -> x86_64-apple-darwin / x86_64-apple-darwin)
Assembling stage3 compiler (x86_64-apple-darwin)
thread 'main' panicked at 'fs::read(stamp) failed with No such file or directory (os error 2) ("/Users/user/rust2/build/x86_64-apple-darwin/stage2-rustc/x86_64-apple-darwin/release/.librustc.stamp")', src/bootstrap/lib.rs:1296:24
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Build completed unsuccessfully in 0:29:07
```

<details><summary>Backtrace</summary>

```
thread 'main' panicked at 'fs::read(stamp) failed with No such file or directory (os error 2) ("/Users/user/rust2/build/x86_64-apple-darwin/stage2-rustc/x86_64-apple-darwin/release/.librustc.stamp")', src/bootstrap/lib.rs:1296:24
stack backtrace:
   0: rust_begin_unwind
             at /rustc/e784c962ea252f0874a4305168077e7048cb39e9/library/std/src/panicking.rs:517:5
   1: core::panicking::panic_fmt
             at /rustc/e784c962ea252f0874a4305168077e7048cb39e9/library/core/src/panicking.rs:101:14
   2: bootstrap::Build::read_stamp_file
             at ./src/bootstrap/lib.rs:1296:24
   3: <bootstrap::compile::Assemble as bootstrap::builder::Step>::run
             at ./src/bootstrap/compile.rs:1107:27
   4: bootstrap::builder::Builder::ensure
             at ./src/bootstrap/builder.rs:1592:23
   5: bootstrap::builder::Builder::compiler
             at ./src/bootstrap/builder.rs:627:9
   6: <bootstrap::compile::Assemble as bootstrap::builder::Step>::make_run
             at ./src/bootstrap/compile.rs:1034:30
   7: bootstrap::builder::StepDescription::maybe_run
             at ./src/bootstrap/builder.rs:175:13
   8: bootstrap::builder::StepDescription::run
             at ./src/bootstrap/builder.rs:231:21
   9: bootstrap::builder::Builder::run_step_descriptions
             at ./src/bootstrap/builder.rs:619:9
  10: bootstrap::builder::Builder::execute_cli
             at ./src/bootstrap/builder.rs:599:9
  11: bootstrap::Build::build
             at ./src/bootstrap/lib.rs:624:13
  12: bootstrap::main
             at ./src/bootstrap/bin/main.rs:33:5
  13: core::ops::function::FnOnce::call_once
             at /rustc/e784c962ea252f0874a4305168077e7048cb39e9/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Build completed unsuccessfully in 0:00:05
```

</details>

### PR DESCRIPTION
**Pull request by onur-ozkan**
Skip assembling(which causes panic due to not found `.librustc.stamp` file) process
for stage3(since it has problems with sysroot) if full-bootstrap isn't used.

Resolves #90244

### CODE REVIEW

**Comment by ozkanonur** [comment]
I have checked the sha256 checksum of stage2 lib and bin files on master and on this branch, they all provide the same result. But the bootstrap tests failed.

```diff
diff --git a/src/bootstrap/builder/tests.rs b/src/bootstrap/builder/tests.rs
index 3574f11189e..c9daa0a3b9a 100644
--- a/src/bootstrap/builder/tests.rs
+++ b/src/bootstrap/builder/tests.rs
@@ -501,15 +501,13 @@ fn build_all() {
                 std!(A => C, stage = 2),
             ]
         );
-        assert_eq!(builder.cache.all::<compile::Assemble>().len(), 5);
+        assert_eq!(builder.cache.all::<compile::Assemble>().len(), 4);
         assert_eq!(
             first(builder.cache.all::<compile::Rustc>()),
             &[
                 rustc!(A => A, stage = 0),
                 rustc!(A => A, stage = 1),
-                rustc!(A => A, stage = 2),
                 rustc!(A => B, stage = 1),
-                rustc!(A => B, stage = 2),
             ]
         );
     }
```
Does this patch look right?

File: src/bootstrap/compile.rs [hunk 1]
```diff
@@ -1246,7 +1246,7 @@ impl Step for Assemble {
 
     fn make_run(run: RunConfig<'_>) {
         run.builder.ensure(Assemble {
-            target_compiler: run.builder.compiler(run.builder.top_stage + 1, run.target),
+            target_compiler: run.builder.compiler(run.builder.top_stage, run.target),
```
Comment (Mark-Simulacrum) [inline src/bootstrap/compile.rs:1249]: Presumably with something like --stage 0, this now is a no-op rather than doing something?

**Comment by Mark-Simulacrum** [comment]
I suspect this is not the right fix -- it feels wrong to say that the code there is just overly aggressive in incrementing. But I'm not sure.

File: src/bootstrap/compile.rs (hunk 1 above)
Comment (ozkanonur) [reply src/bootstrap/compile.rs:1249]: As I mentioned earlier, `bootstrap::compile::Assemble::make_run` only gets called when a target dir is specified something like `x build compiler/rustc`.

When I execute `x build compiler/rustc --stage 0`, I get the exactly same `stage0` output compare to master branch, but missing `stage1`(which includes a bunch of empty directories), `ci-rustc`, `ci-rustc-sysroot` directories.

**Comment by ozkanonur** [comment]
> it feels wrong to say that the code there is just overly aggressive in incrementing. But I'm not sure.

You can try `x build compiler/rustc --stage 3` and see stage4 directory with bunch of empty directoires in it.

**Comment by ozkanonur** [comment]
This PR is a blocker for one of our(I am responsible for working on that) task(including tools to sysroot after build). cc @rust-lang/bootstrap

Just wanted to ping our team for reminding the PR so it's not forgotten and not to be left behind.

File: src/bootstrap/compile.rs [hunk 2]
```diff
@@ -1295,6 +1295,14 @@ impl Step for Assemble {
         // when not performing a full bootstrap).
         builder.ensure(Rustc::new(build_compiler, target_compiler.host));
 
+        // Do early return instead of assembling for stage3(since it has problems
+        // with sysroot) if full-bootstrap isn't used.
+        //
+        // See: https://github.com/rust-lang/rust/issues/90244
+        if target_compiler.stage >= 3 && !builder.config.full_bootstrap {
```
Comment (Mark-Simulacrum) [inline src/bootstrap/compile.rs:1302]: I'm not convinced this isn't just hiding the problem, it looks like we would presumably still run into the same problem with full-bootstrap and stage 3? Or, if not, then the fix is probably in some other conditional on stage 3 / full bootstrap elsewhere, which should treat stage 2 similarly.

I'm OK merging this since full-bootstrap use is rarer and it sounds like the issue is worth at least patching over, but I would prefer that this comment indicate that this is a hack. Something like:

> FIXME: For now patch over problems noted in #90244 by early returning here, even though we've not properly assembled the target sysroot. A full fix is pending further investigation, for now full bootstrap usage is rare enough that this is OK.

Comment (ozkanonur) [reply src/bootstrap/compile.rs:1302]: > I'm not convinced this isn't just hiding the problem, it looks like we would presumably still run into the same problem with full-bootstrap and stage 3?

Yes, this fixes the problem where we only want to build stage 2 compiler and get stage 3 error. Doesn't fix the main problem with stage3.

Comment (Mark-Simulacrum) [reply src/bootstrap/compile.rs:1301]: Hm. So I re-ran with full-bootstrap and stage=3 and stage=4 and that seems to work... I still suspect this isn't quite right (feels like the wrong place for this to live) but for now let's just accept as-is.

**Comment by Mark-Simulacrum** [comment]
@bors r+

I'll accept with the FIXME, but maybe worth poking some more.

File: src/bootstrap/compile.rs (hunk 2 above)
Comment (ozkanonur) [reply src/bootstrap/compile.rs:1301]: I haven't done detailed debug on the stage3 problem. I was focused on the hotfixing stage3 error on stage2 compilation. I could check that one too if you want.
