### PR TITLE
Stabilize raw ref macros

### LINKED ISSUE #73394: Tracking Issue for raw_ref_macros
This is a tracking issue for the macro version of `raw_ref_op` (https://github.com/rust-lang/rust/issues/64490).
The feature gate for the issue is `#![feature(raw_ref_macros)]`.

### About tracking issues

Tracking issues are used to record the overall progress of implementation.
They are also uses as hubs connecting to other relevant issues, e.g., bugs or open design questions.
A tracking issue is however *not* meant for large scale discussion, questions, or bug reports about a feature.
Instead, open a dedicated issue for the specific matter and add the relevant feature gate label.

### Steps

- [x] Implement
- [ ] Adjust documentation ([see instructions on rustc-dev-guide][doc-guide])
- [ ] Stabilization PR ([see instructions on rustc-dev-guide][stabilization-guide])

[stabilization-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#stabilization-pr
[doc-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#documentation-prs

### Unresolved Questions

* Are we happy with the macro names? Currently: `core::ptr::raw_const!(path)`/`core::ptr::raw_mut!(path)`
* ~~Potentially blocked on docs issue: #74355~~ [fixed in #77862]

### Implementation history

* https://github.com/rust-lang/rust/pull/72279

### PR DESCRIPTION
**Pull request by RalfJung**
This stabilizes `raw_ref_macros` (https://github.com/rust-lang/rust/issues/73394), which is possible now that https://github.com/rust-lang/rust/issues/74355 is fixed.

However, as I already said in https://github.com/rust-lang/rust/issues/73394#issuecomment-751342185, I am not particularly happy with the current names of the macros. So I propose we also change them, which means I am proposing to stabilize the following in `core::ptr`:
```rust
pub macro const_addr_of($e:expr) {
    &raw const $e
}

pub macro mut_addr_of($e:expr) {
    &raw mut $e
}
```

The macro name change means we need another round of FCP. Cc @rust-lang/libs
Fixes #73394

### CODE REVIEW

**Comment by mark-i-m** [comment]
`const_raw_ref` and `mut_raw_ref`?

`raw_ref` and `mut_raw_ref`?

**Comment by RalfJung** [comment]
@mark-i-m  I don't think "raw references" are a term I've ever seen.

**Comment by danielhenrymantilla** [comment]
I like the new names in this PR better; although using _addr_ is slightly suboptimal (pointers are not (just) addresses yadda yadda), but besides that pedantic nit I think "addr of" conveys the meaning of C's `&` / Rust's `&raw` operator better than speaking of (raw) _ref_-erences.

Also, tiny nit: could `$e` be renamed to `$place`? Since giving a non-place expression [yields an error](https://rust.godbolt.org/z/ba8azd) (which is great btw! Having potentially immediately dangling pointers would have been a bit of a footgun, so props on the compilation error).

**Comment by lzutao** [comment]
> I don't think "raw references" are a term I've ever seen.

Maybe a misunderstand from the feature name: `raw_ref_macros` ?

**Comment by RalfJung** [comment]
> Also, tiny nit: could $e be renamed to $place? Since giving a non-place expression yields an error

Sure, done.

**Comment by danielhenrymantilla** [comment]
> giving a non-place expression yields an error 

Should there be a UI test for this?

**Comment by RalfJung** [comment]
The error comes from the underlying `&raw`, I don't think it makes sense to duplicate the test for the macro.
`src/test/ui/raw-ref-op/raw-ref-temp.rs` tests the underlying `&raw`.

**Comment by mark-i-m** [comment]
> 
> 
> @mark-i-m I don't think "raw references" are a term I've ever seen.

@RalfJung Sorry, I'm forgetting what `*const T` and `*mut T` are called. Raw pointers? Would `const_raw_ptr` and `mut_raw_ptr` be better?

**Comment by RalfJung** [comment]
Yeah I think "raw pointers" is the usual term, sometimes just "pointers".

The macros are in the `ptr` namespace, so `ptr::const_raw_ptr` seems a bit redundant? `const_raw` on the other hand is hard to decipher, not much better than the current `raw_const!`. Also, `const_raw_ptr!((*x).some_field)` is IMO less clear than "address of".

But `const_raw_ptr!` is definitely better than the current `raw_const!`. So it would be an okay fallback for me if `const_addr_of!` doesn't find consensus.

**Comment by danielhenrymantilla** [comment]
```rust
unsafe // Safety: keep it cool :)
fn bikeshed (x: *mut SomeStruct)
{
    use ::core::ptr;

    ptr::raw_const!((*x).some_field);
    ptr::raw_mut!((*x).some_field);

    ptr::const_addr_of!((*x).some_field);
    ptr::mut_addr_of!((*x).some_field);

    // Personal modification of the `{const,mut}_raw_ptr!` suggestion
    ptr::const_ptr_to!((*x).some_field);
    ptr::mut_ptr_to!((*x).some_field);

    // Another personal suggestion
    ptr::raw_ptr!(&raw const (*x).some_field);
    ptr::raw_ptr!(&raw mut (*x).some_field);

    use ::core::ptr::*;

    raw_const!((*x).some_field);
    raw_mut!((*x).some_field);

    const_addr_of!((*x).some_field);
    mut_addr_of!((*x).some_field);

    const_ptr_to!((*x).some_field);
    mut_ptr_to!((*x).some_field);

    raw_ptr!(&raw const (*x).some_field);
    raw_ptr!(&raw mut (*x).some_field);
}
```

<details><summary>My personal stance (fwiw)</summary>

I don't have a strong preference here, except for `raw_{const,mut}` being the pair that reads the worst. When looking at this, `const_addr` has the drawback of not necessarily leading to the same muscle memory as `const_ptr` does, so I think I prefer `ptr_to` to `addr_of` for this reason. Finally, the idea of having not two but one macro could be worth exploring 🤷 

</details>

**Comment by RalfJung** [comment]
`const_ptr_to`/`mut_ptr_to` looks like a reasonable alternative to `addr_of`.

I don't think we want `raw_ptr!(&raw const (*x).some_field)`; the entire point of this is to *not* stabilize the `&raw` syntax.

**Comment by mark-i-m** [comment]
@RalfJung We could have it be "generic" though: `ptr_to(const (*x).some_field)` and `ptr_to(mut (*x).some_field)`...

**Comment by m-ou-se** [comment]
Since this is tagged as `I-nominated` we'll discuss this in the libs meeting next week. But here's some first thoughts:

The names `const_addr_of` and `mut_addr_of` make it sound like `const` and `mut` apply to the address.

The name `const_addr_of` makes me think more of `const X: T = ..;`, `const fn` and compile time evaluation rather than of the opposite of `mut`, especially since most const+mut pairs in Rust are called `thing`+`thing_mut` instead of `thing_const`+`thing_mut`. (I do realise this is specifically not the case for `*const T`+`*mut T`, but still.)

Do you have any alternatives for the names in mind? What would you think of something like `addr_of` and `addr_of_mut`?

**Comment by RalfJung** [comment]
> The name const_addr_of makes me think more of const X: T = ..;, const fn and compile time evaluation rather than of the opposite of mut

Yeah, I know. This is even worse with `ptr::raw_const!`, which is the current name. The new name at least indicates more clearly that `const` is an adjective. That's why I think the new names make this confusion less likely, but they certainly do not alleviate it.

> especially since most const+mut pairs in Rust are called thing+thing_mut instead of thing_const+thing_mut. (I do realise this is specifically not the case for *const T+*mut T, but still.)

Indeed, we have `&` and `&mut` -- but not for raw pointers.

> Do you have any alternatives for the names in mind? What would you think of something like addr_of and addr_of_mut?

I feel it would be strange to deviate from the `*const`/`*mut` names of the types that are being constructed here. `addr_of_mut` sounds like it is taking the address of something mutable, which is IMO the wrong picture -- the right picture is that this takes the address and stores it in a `*mut`. Mutability in raw pointers is mostly meaningless / "just a lint", but when people want to do mutation I'd still advise against using `const_addr_of`, so making the const version have the shorter (-> more ergonomic) name (`addr_of`) is not a good call, either, in my opinion.

I feel like all choices are bad here, and I had hoped that the libs team would have some good ideas since they certainly have more experience naming Rust APIs than I do. :)

**Comment by m-ou-se** [comment]
> I feel it would be strange to deviate from the `*const`/`*mut` names of the types that are being constructed here.

We already do that for `ptr::null`+`ptr::null_mut` and `ptr::slice_from_raw_parts`+`ptr::slice_from_raw_parts_mut` though.

> `addr_of_mut` sounds like it is taking the address of something mutable, which is IMO the wrong picture 

Even though const/mut in pointers is mostly meaningless, isn't `*mut T` is still supposed to point to a mutable T?

> the right picture is that this takes the address and stores it in a `*mut`.

How would you pronounce `*mut T`? "mut pointer"? "pointer to mut"? Or something else?

**Comment by RalfJung** [comment]
> Even though const/mut in pointers is mostly meaningless, isn't *mut T is still supposed to point to a mutable T?

I guess it is, but personally on the few occasions that I have been writing raw pointer code, that's not how I thought about this. But maybe I am thinking about this in weird ways.

> How would you pronounce *mut T? "mut pointer"? "pointer to mut"? Or something else?

I'd say "mutable raw pointer", and "const(ant) raw pointer" for `*const T`.

**Comment by RalfJung** [comment]
So how do we make progress here? @m-ou-se did the libs team have a chance to talk about this at their meeting?

To summarize, the most promising proposals so far have been
* `ptr::const_addr_of`/`ptr::mut_addr_of`
* `ptr::const_raw_ptr`/`ptr::mut_raw_ptr`
* `ptr::const_ptr_to`/`ptr::mut_ptr_to`
* `ptr::addr_of`/`ptr::addr_of_mut`

**Comment by m-ou-se** [comment]
@RalfJung We didn't manage to handle all the nominated issues (incl. this one) last meeting, unfortunately. We planned an extra triage meeting in four days to discuss them.

**Comment by m-ou-se** [comment]
@rust-lang/libs Opinions are needed here on the name of these macros. ^

**Comment by KodrAus** [comment]
We discussed this at our recent Libs meeting and had a preference for `ptr::addr_of`/`ptr::addr_of_mut` so would be happy to proceed with the stabilization using those names.

File: library/alloc/src/rc.rs [hunk 1]
```diff
@@ -1917,7 +1917,7 @@ impl<T: ?Sized> Weak<T> {
             // SAFETY: if is_dangling returns false, then the pointer is dereferencable.
             // The payload may be dropped at this point, and we have to maintain provenance,
             // so use raw pointer manipulation.
-            unsafe { &raw const (*ptr).value }
+            unsafe { ptr::addr_of_mut!((*ptr).value) }
```
Comment (RalfJung) [inline library/alloc/src/rc.rs:1920]: I made this `mut` for consistency with `Arc`.

**Comment by RalfJung** [comment]
All right, I renamed the macros accordingly. I left the version at 1.51, hoping this will land until the next beta branches on Monday. :D

**Comment by m-ou-se** [comment]
FCP with the old names (`raw_const`, `raw_mut`) happened here: https://github.com/rust-lang/rust/issues/73394#issuecomment-664554197.

The new names are the result of a meeting which was attended by five libs team members.

So, no need for a new FCP.

@bors r+
