### PR TITLE
Fix ICE, generalize 'move generics to trait' suggestion for >0 non-rcvr arguments

### LINKED ISSUE #101421: thread 'rustc' panicked at 'assertion failed: `(left == right)` when calling a trait method with more generic arguments than expected (nightly)
### Code
```Rust
pub trait Ice {
    fn f(&self);
}

impl Ice for () {
    fn f(&self) {}
}

fn main() {
    ().f::<()>(());
}
```
Repros on the [playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=e7e689a8eec4e4a817ae9b33818e4279)/current nightly. But works (gives an error about mismatched number of generic arguments) on stable and beta. s/o to @memoryruins for the minimal example.

### Meta
`rustc --version --verbose`:
```
rustc 1.65.0-nightly (84f0c3f79 2022-09-03)
binary: rustc
commit-hash: 84f0c3f79a85329dd79a54694ff8a7f427c842e9
commit-date: 2022-09-03
host: x86_64-unknown-linux-gnu
release: 1.65.0-nightly
LLVM version: 15.0.0
```

### Error output

<details><summary><strong>Backtrace</strong></summary>
<p>

```
thread 'rustc' panicked at 'assertion failed: `(left == right)`
  left: `2`,
 right: `1`', compiler/rustc_typeck/src/structured_errors/wrong_number_of_generic_args.rs:762:13
stack backtrace:
   0:     0x7f7afc0cc340 - std::backtrace_rs::backtrace::libunwind::trace::he4e99f7a9421fd21
                               at /rustc/84f0c3f79a85329dd79a54694ff8a7f427c842e9/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   1:     0x7f7afc0cc340 - std::backtrace_rs::backtrace::trace_unsynchronized::h74200e38a72f671f
                               at /rustc/84f0c3f79a85329dd79a54694ff8a7f427c842e9/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7f7afc0cc340 - std::sys_common::backtrace::_print_fmt::hfbb8fdb3546734fb
                               at /rustc/84f0c3f79a85329dd79a54694ff8a7f427c842e9/library/std/src/sys_common/backtrace.rs:66:5
   3:     0x7f7afc0cc340 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hb06e7a466c2aea64
                               at /rustc/84f0c3f79a85329dd79a54694ff8a7f427c842e9/library/std/src/sys_common/backtrace.rs:45:22
   4:     0x7f7afc1270fe - core::fmt::write::h8ba61610af1e729d
                               at /rustc/84f0c3f79a85329dd79a54694ff8a7f427c842e9/library/core/src/fmt/mod.rs:1202:17
   5:     0x7f7afc0bcd15 - std::io::Write::write_fmt::h93eba0e07d57e4b5
                               at /rustc/84f0c3f79a85329dd79a54694ff8a7f427c842e9/library/std/src/io/mod.rs:1679:15
   6:     0x7f7afc0cefd3 - std::sys_common::backtrace::_print::h2cdedfde5efdb664
                               at /rustc/84f0c3f79a85329dd79a54694ff8a7f427c842e9/library/std/src/sys_common/backtrace.rs:48:5
   7:     0x7f7afc0cefd3 - std::sys_common::backtrace::print::h68414ee92e65fad5
                               at /rustc/84f0c3f79a85329dd79a54694ff8a7f427c842e9/library/std/src/sys_common/backtrace.rs:35:9
   8:     0x7f7afc0cefd3 - std::panicking::default_hook::{{closure}}::h98d876334738bafa
                               at /rustc/84f0c3f79a85329dd79a54694ff8a7f427c842e9/library/std/src/panicking.rs:295:22
   9:     0x7f7afc0cecbf - std::panicking::default_hook::h098a5781bef610c8
                               at /rustc/84f0c3f79a85329dd79a54694ff8a7f427c842e9/library/std/src/panicking.rs:314:9
  10:     0x7f7afe96ed51 - <rustc_driver[50799d7c8405f566]::DEFAULT_HOOK::{closure#0}::{closure#0} as core[9e79f03012061614]::ops::function::FnOnce<(&core[9e79f03012061614]::panic::panic_info::PanicInfo,)>>::call_once::{shim:vtable#0}
  11:     0x7f7afc0cf80d - std::panicking::rust_panic_with_hook::h723649ddcf73c6f3
                               at /rustc/84f0c3f79a85329dd79a54694ff8a7f427c842e9/library/std/src/panicking.rs:702:17
  12:     0x7f7afc0cf667 - std::panicking::begin_panic_handler::{{closure}}::h9baae5c36d713817
                               at /rustc/84f0c3f79a85329dd79a54694ff8a7f427c842e9/library/std/src/panicking.rs:588:13
  13:     0x7f7afc0cc85c - std::sys_common::backtrace::__rust_end_short_backtrace::hf771b300380f68b6
                               at /rustc/84f0c3f79a85329dd79a54694ff8a7f427c842e9/library/std/src/sys_common/backtrace.rs:138:18
  14:     0x7f7afc0cf382 - rust_begin_unwind
                               at /rustc/84f0c3f79a85329dd79a54694ff8a7f427c842e9/library/std/src/panicking.rs:584:5
  15:     0x7f7afc123ce3 - core::panicking::panic_fmt::hfc3d0a8a832c19b6
                               at /rustc/84f0c3f79a85329dd79a54694ff8a7f427c842e9/library/core/src/panicking.rs:142:14
  16:     0x7f7afc123eeb - core::panicking::assert_failed_inner::h794504581fd2d25e
  17:     0x7f7afed1df7c - core[9e79f03012061614]::panicking::assert_failed::<usize, usize>
  18:     0x7f7afed179a7 - <rustc_typeck[2e4e46c673df809b]::structured_errors::wrong_number_of_generic_args::WrongNumberOfGenericArgs>::suggest_moving_args_from_assoc_fn_to_trait_for_method_call
  19:     0x7f7afed19c4e - <rustc_typeck[2e4e46c673df809b]::structured_errors::wrong_number_of_generic_args::WrongNumberOfGenericArgs as rustc_typeck[2e4e46c673df809b]::structured_errors::StructuredDiagnostic>::diagnostic_common
  20:     0x7f7afed19e64 - <rustc_typeck[2e4e46c673df809b]::structured_errors::wrong_number_of_generic_args::WrongNumberOfGenericArgs as rustc_typeck[2e4e46c673df809b]::structured_errors::StructuredDiagnostic>::diagnostic
  21:     0x7f7afd4cd321 - <rustc_typeck[2e4e46c673df809b]::check::method::confirm::ConfirmContext>::confirm
  22:     0x7f7afd492885 - <rustc_typeck[2e4e46c673df809b]::check::fn_ctxt::FnCtxt>::lookup_method
  23:     0x7f7afd479212 - <rustc_typeck[2e4e46c673df809b]::check::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
  24:     0x7f7afd4abca6 - <rustc_typeck[2e4e46c673df809b]::check::fn_ctxt::FnCtxt>::check_block_with_expected
  25:     0x7f7afd479161 - <rustc_typeck[2e4e46c673df809b]::check::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
  26:     0x7f7afd683cad - <rustc_typeck[2e4e46c673df809b]::check::fn_ctxt::FnCtxt>::check_return_expr
  27:     0x7f7afd67a148 - rustc_typeck[2e4e46c673df809b]::check::check::check_fn
  28:     0x7f7afd66b6a5 - <rustc_infer[9621d61c06e2fd28]::infer::InferCtxtBuilder>::enter::<&rustc_middle[2f4b9e29546a322f]::ty::context::TypeckResults, <rustc_typeck[2e4e46c673df809b]::check::inherited::InheritedBuilder>::enter<rustc_typeck[2e4e46c673df809b]::check::typeck_with_fallback<rustc_typeck[2e4e46c673df809b]::check::typeck::{closure#0}>::{closure#1}, &rustc_middle[2f4b9e29546a322f]::ty::context::TypeckResults>::{closure#0}>
  29:     0x7f7afd669970 - rustc_typeck[2e4e46c673df809b]::check::typeck
  30:     0x7f7afe149398 - rustc_query_system[43d3d2d99526f734]::query::plumbing::try_execute_query::<rustc_query_impl[c86171d079f7a759]::plumbing::QueryCtxt, rustc_query_system[43d3d2d99526f734]::query::caches::DefaultCache<rustc_span[e67d62ce6d130a16]::def_id::LocalDefId, &rustc_middle[2f4b9e29546a322f]::ty::context::TypeckResults>>
  31:     0x7f7afe86929a - <rustc_query_impl[c86171d079f7a759]::Queries as rustc_middle[2f4b9e29546a322f]::ty::query::QueryEngine>::typeck
  32:     0x7f7afe699cfb - rustc_data_structures[bf35110829b83311]::sync::par_for_each_in::<&[rustc_span[e67d62ce6d130a16]::def_id::LocalDefId], <rustc_middle[2f4b9e29546a322f]::hir::map::Map>::par_body_owners<rustc_typeck[2e4e46c673df809b]::check::typeck_item_bodies::{closure#0}>::{closure#0}>
  33:     0x7f7afe699ac3 - rustc_typeck[2e4e46c673df809b]::check::typeck_item_bodies
  34:     0x7f7afe59facf - rustc_query_system[43d3d2d99526f734]::query::plumbing::try_execute_query::<rustc_query_impl[c86171d079f7a759]::plumbing::QueryCtxt, rustc_query_system[43d3d2d99526f734]::query::caches::DefaultCache<(), ()>>
  35:     0x7f7afe59f7e3 - rustc_query_system[43d3d2d99526f734]::query::plumbing::get_query::<rustc_query_impl[c86171d079f7a759]::queries::typeck_item_bodies, rustc_query_impl[c86171d079f7a759]::plumbing::QueryCtxt>
  36:     0x7f7afdcb9a7f - <rustc_session[ffa4a92384fc7df0]::session::Session>::time::<(), rustc_typeck[2e4e46c673df809b]::check_crate::{closure#7}>
  37:     0x7f7afdcb963f - rustc_typeck[2e4e46c673df809b]::check_crate
  38:     0x7f7afdcb8c07 - rustc_interface[113e5a7d9d4618b]::passes::analysis
  39:     0x7f7afe6ef58f - rustc_query_system[43d3d2d99526f734]::query::plumbing::try_execute_query::<rustc_query_impl[c86171d079f7a759]::plumbing::QueryCtxt, rustc_query_system[43d3d2d99526f734]::query::caches::DefaultCache<(), core[9e79f03012061614]::result::Result<(), rustc_errors[f22a624e573ad349]::ErrorGuaranteed>>>
  40:     0x7f7afe6ef2a0 - rustc_query_system[43d3d2d99526f734]::query::plumbing::get_query::<rustc_query_impl[c86171d079f7a759]::queries::analysis, rustc_query_impl[c86171d079f7a759]::plumbing::QueryCtxt>
  41:     0x7f7afd76c5e4 - <rustc_interface[113e5a7d9d4618b]::passes::QueryContext>::enter::<rustc_driver[50799d7c8405f566]::run_compiler::{closure#1}::{closure#2}::{closure#3}, core[9e79f03012061614]::result::Result<(), rustc_errors[f22a624e573ad349]::ErrorGuaranteed>>
  42:     0x7f7afd768b9e - <rustc_interface[113e5a7d9d4618b]::interface::Compiler>::enter::<rustc_driver[50799d7c8405f566]::run_compiler::{closure#1}::{closure#2}, core[9e79f03012061614]::result::Result<core[9e79f03012061614]::option::Option<rustc_interface[113e5a7d9d4618b]::queries::Linker>, rustc_errors[f22a624e573ad349]::ErrorGuaranteed>>
  43:     0x7f7afd763d0c - rustc_span[e67d62ce6d130a16]::with_source_map::<core[9e79f03012061614]::result::Result<(), rustc_errors[f22a624e573ad349]::ErrorGuaranteed>, rustc_interface[113e5a7d9d4618b]::interface::create_compiler_and_run<core[9e79f03012061614]::result::Result<(), rustc_errors[f22a624e573ad349]::ErrorGuaranteed>, rustc_driver[50799d7c8405f566]::run_compiler::{closure#1}>::{closure#1}>
  44:     0x7f7afd763702 - rustc_interface[113e5a7d9d4618b]::interface::create_compiler_and_run::<core[9e79f03012061614]::result::Result<(), rustc_errors[f22a624e573ad349]::ErrorGuaranteed>, rustc_driver[50799d7c8405f566]::run_compiler::{closure#1}>
  45:     0x7f7afd762351 - <scoped_tls[95e243f8d973a695]::ScopedKey<rustc_span[e67d62ce6d130a16]::SessionGlobals>>::set::<rustc_interface[113e5a7d9d4618b]::interface::run_compiler<core[9e79f03012061614]::result::Result<(), rustc_errors[f22a624e573ad349]::ErrorGuaranteed>, rustc_driver[50799d7c8405f566]::run_compiler::{closure#1}>::{closure#0}, core[9e79f03012061614]::result::Result<(), rustc_errors[f22a624e573ad349]::ErrorGuaranteed>>
  46:     0x7f7afd76203f - std[1194366af38420ad]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[113e5a7d9d4618b]::util::run_in_thread_pool_with_globals<rustc_interface[113e5a7d9d4618b]::interface::run_compiler<core[9e79f03012061614]::result::Result<(), rustc_errors[f22a624e573ad349]::ErrorGuaranteed>, rustc_driver[50799d7c8405f566]::run_compiler::{closure#1}>::{closure#0}, core[9e79f03012061614]::result::Result<(), rustc_errors[f22a624e573ad349]::ErrorGuaranteed>>::{closure#0}, core[9e79f03012061614]::result::Result<(), rustc_errors[f22a624e573ad349]::ErrorGuaranteed>>
  47:     0x7f7afe785099 - <<std[1194366af38420ad]::thread::Builder>::spawn_unchecked_<rustc_interface[113e5a7d9d4618b]::util::run_in_thread_pool_with_globals<rustc_interface[113e5a7d9d4618b]::interface::run_compiler<core[9e79f03012061614]::result::Result<(), rustc_errors[f22a624e573ad349]::ErrorGuaranteed>, rustc_driver[50799d7c8405f566]::run_compiler::{closure#1}>::{closure#0}, core[9e79f03012061614]::result::Result<(), rustc_errors[f22a624e573ad349]::ErrorGuaranteed>>::{closure#0}, core[9e79f03012061614]::result::Result<(), rustc_errors[f22a624e573ad349]::ErrorGuaranteed>>::{closure#1} as core[9e79f03012061614]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  48:     0x7f7afc0d9663 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::he022220abf60d2af
                               at /rustc/84f0c3f79a85329dd79a54694ff8a7f427c842e9/library/alloc/src/boxed.rs:1940:9
  49:     0x7f7afc0d9663 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h26bdfd3e52f03485
                               at /rustc/84f0c3f79a85329dd79a54694ff8a7f427c842e9/library/alloc/src/boxed.rs:1940:9
  50:     0x7f7afc0d9663 - std::sys::unix::thread::Thread::new::thread_start::hc76b3d0624b7ab68
                               at /rustc/84f0c3f79a85329dd79a54694ff8a7f427c842e9/library/std/src/sys/unix/thread.rs:108:17
  51:     0x7f7afbfad609 - start_thread
  52:     0x7f7afbed0133 - clone
  53:                0x0 - <unknown>

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.65.0-nightly (84f0c3f79 2022-09-03) running on x86_64-unknown-linux-gnu

note: compiler flags: --crate-type bin -C embed-bitcode=no -C codegen-units=1 -C debuginfo=2

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [typeck] type-checking `main`
#1 [typeck_item_bodies] type-checking all item bodies
#2 [analysis] running analysis passes on this crate
end of query stack
error: internal compiler error: no warnings or errors encountered even though `delayed_good_path_bugs` issued

error: internal compiler error: trimmed_def_paths constructed
  |
  = note: delayed at    0: <rustc_errors::Handler>::delay_good_path_bug::<&str>
             1: rustc_middle::ty::print::pretty::trimmed_def_paths
             2: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::plumbing::QueryCtxt, rustc_query_system::query::caches::ArenaCache<(), std::collections::hash::map::HashMap<rustc_span::def_id::DefId, rustc_span::symbol::Symbol, core::hash::BuildHasherDefault<rustc_hash::FxHasher>>>>
             3: rustc_query_system::query::plumbing::get_query::<rustc_query_impl::queries::trimmed_def_paths, rustc_query_impl::plumbing::QueryCtxt>
             4: <rustc_middle::ty::print::pretty::FmtPrinter as rustc_middle::ty::print::Printer>::print_def_path
             5: <rustc_middle::ty::context::TyCtxt>::def_path_str_with_substs
             6: <rustc_middle::ty::context::TyCtxt>::def_path_str
             7: <rustc_typeck::structured_errors::wrong_number_of_generic_args::WrongNumberOfGenericArgs as rustc_typeck::structured_errors::StructuredDiagnostic>::diagnostic_common
             8: <rustc_typeck::structured_errors::wrong_number_of_generic_args::WrongNumberOfGenericArgs as rustc_typeck::structured_errors::StructuredDiagnostic>::diagnostic
             9: <rustc_typeck::check::method::confirm::ConfirmContext>::confirm
            10: <rustc_typeck::check::fn_ctxt::FnCtxt>::lookup_method
            11: <rustc_typeck::check::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
            12: <rustc_typeck::check::fn_ctxt::FnCtxt>::check_block_with_expected
            13: <rustc_typeck::check::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
            14: <rustc_typeck::check::fn_ctxt::FnCtxt>::check_return_expr
            15: rustc_typeck::check::check::check_fn
            16: <rustc_infer::infer::InferCtxtBuilder>::enter::<&rustc_middle::ty::context::TypeckResults, <rustc_typeck::check::inherited::InheritedBuilder>::enter<rustc_typeck::check::typeck_with_fallback<rustc_typeck::check::typeck::{closure#0}>::{closure#1}, &rustc_middle::ty::context::TypeckResults>::{closure#0}>
            17: rustc_typeck::check::typeck
            18: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::plumbing::QueryCtxt, rustc_query_system::query::caches::DefaultCache<rustc_span::def_id::LocalDefId, &rustc_middle::ty::context::TypeckResults>>
            19: <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::typeck
            20: rustc_data_structures::sync::par_for_each_in::<&[rustc_span::def_id::LocalDefId], <rustc_middle::hir::map::Map>::par_body_owners<rustc_typeck::check::typeck_item_bodies::{closure#0}>::{closure#0}>
            21: rustc_typeck::check::typeck_item_bodies
            22: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::plumbing::QueryCtxt, rustc_query_system::query::caches::DefaultCache<(), ()>>
            23: rustc_query_system::query::plumbing::get_query::<rustc_query_impl::queries::typeck_item_bodies, rustc_query_impl::plumbing::QueryCtxt>
            24: <rustc_session::session::Session>::time::<(), rustc_typeck::check_crate::{closure#7}>
            25: rustc_typeck::check_crate
            26: rustc_interface::passes::analysis
            27: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::plumbing::QueryCtxt, rustc_query_system::query::caches::DefaultCache<(), core::result::Result<(), rustc_errors::ErrorGuaranteed>>>
            28: rustc_query_system::query::plumbing::get_query::<rustc_query_impl::queries::analysis, rustc_query_impl::plumbing::QueryCtxt>
            29: <rustc_interface::passes::QueryContext>::enter::<rustc_driver::run_compiler::{closure#1}::{closure#2}::{closure#3}, core::result::Result<(), rustc_errors::ErrorGuaranteed>>
            30: <rustc_interface::interface::Compiler>::enter::<rustc_driver::run_compiler::{closure#1}::{closure#2}, core::result::Result<core::option::Option<rustc_interface::queries::Linker>, rustc_errors::ErrorGuaranteed>>
            31: rustc_span::with_source_map::<core::result::Result<(), rustc_errors::ErrorGuaranteed>, rustc_interface::interface::create_compiler_and_run<core::result::Result<(), rustc_errors::ErrorGuaranteed>, rustc_driver::run_compiler::{closure#1}>::{closure#1}>
            32: rustc_interface::interface::create_compiler_and_run::<core::result::Result<(), rustc_errors::ErrorGuaranteed>, rustc_driver::run_compiler::{closure#1}>
            33: <scoped_tls::ScopedKey<rustc_span::SessionGlobals>>::set::<rustc_interface::interface::run_compiler<core::result::Result<(), rustc_errors::ErrorGuaranteed>, rustc_driver::run_compiler::{closure#1}>::{closure#0}, core::result::Result<(), rustc_errors::ErrorGuaranteed>>
            34: std::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface::util::run_in_thread_pool_with_globals<rustc_interface::interface::run_compiler<core::result::Result<(), rustc_errors::ErrorGuaranteed>, rustc_driver::run_compiler::{closure#1}>::{closure#0}, core::result::Result<(), rustc_errors::ErrorGuaranteed>>::{closure#0}, core::result::Result<(), rustc_errors::ErrorGuaranteed>>
            35: <<std::thread::Builder>::spawn_unchecked_<rustc_interface::util::run_in_thread_pool_with_globals<rustc_interface::interface::run_compiler<core::result::Result<(), rustc_errors::ErrorGuaranteed>, rustc_driver::run_compiler::{closure#1}>::{closure#0}, core::result::Result<(), rustc_errors::ErrorGuaranteed>>::{closure#0}, core::result::Result<(), rustc_errors::ErrorGuaranteed>>::{closure#1} as core::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
            36: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
                       at /rustc/84f0c3f79a85329dd79a54694ff8a7f427c842e9/library/alloc/src/boxed.rs:1940:9
            37: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
                       at /rustc/84f0c3f79a85329dd79a54694ff8a7f427c842e9/library/alloc/src/boxed.rs:1940:9
            38: std::sys::unix::thread::Thread::new::thread_start
                       at /rustc/84f0c3f79a85329dd79a54694ff8a7f427c842e9/library/std/src/sys/unix/thread.rs:108:17
            39: start_thread
            40: clone
          

thread 'rustc' panicked at 'Box<dyn Any>', compiler/rustc_errors/src/lib.rs:1499:13
stack backtrace:
   0:     0x7f7afc0cc340 - std::backtrace_rs::backtrace::libunwind::trace::he4e99f7a9421fd21
                               at /rustc/84f0c3f79a85329dd79a54694ff8a7f427c842e9/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   1:     0x7f7afc0cc340 - std::backtrace_rs::backtrace::trace_unsynchronized::h74200e38a72f671f
                               at /rustc/84f0c3f79a85329dd79a54694ff8a7f427c842e9/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7f7afc0cc340 - std::sys_common::backtrace::_print_fmt::hfbb8fdb3546734fb
                               at /rustc/84f0c3f79a85329dd79a54694ff8a7f427c842e9/library/std/src/sys_common/backtrace.rs:66:5
   3:     0x7f7afc0cc340 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hb06e7a466c2aea64
                               at /rustc/84f0c3f79a85329dd79a54694ff8a7f427c842e9/library/std/src/sys_common/backtrace.rs:45:22
   4:     0x7f7afc1270fe - core::fmt::write::h8ba61610af1e729d
                               at /rustc/84f0c3f79a85329dd79a54694ff8a7f427c842e9/library/core/src/fmt/mod.rs:1202:17
   5:     0x7f7afc0bcd15 - std::io::Write::write_fmt::h93eba0e07d57e4b5
                               at /rustc/84f0c3f79a85329dd79a54694ff8a7f427c842e9/library/std/src/io/mod.rs:1679:15
   6:     0x7f7afc0cefd3 - std::sys_common::backtrace::_print::h2cdedfde5efdb664
                               at /rustc/84f0c3f79a85329dd79a54694ff8a7f427c842e9/library/std/src/sys_common/backtrace.rs:48:5
   7:     0x7f7afc0cefd3 - std::sys_common::backtrace::print::h68414ee92e65fad5
                               at /rustc/84f0c3f79a85329dd79a54694ff8a7f427c842e9/library/std/src/sys_common/backtrace.rs:35:9
   8:     0x7f7afc0cefd3 - std::panicking::default_hook::{{closure}}::h98d876334738bafa
                               at /rustc/84f0c3f79a85329dd79a54694ff8a7f427c842e9/library/std/src/panicking.rs:295:22
   9:     0x7f7afc0cecbf - std::panicking::default_hook::h098a5781bef610c8
                               at /rustc/84f0c3f79a85329dd79a54694ff8a7f427c842e9/library/std/src/panicking.rs:314:9
  10:     0x7f7afe96ed51 - <rustc_driver[50799d7c8405f566]::DEFAULT_HOOK::{closure#0}::{closure#0} as core[9e79f03012061614]::ops::function::FnOnce<(&core[9e79f03012061614]::panic::panic_info::PanicInfo,)>>::call_once::{shim:vtable#0}
  11:     0x7f7afc0cf80d - std::panicking::rust_panic_with_hook::h723649ddcf73c6f3
                               at /rustc/84f0c3f79a85329dd79a54694ff8a7f427c842e9/library/std/src/panicking.rs:702:17
  12:     0x7f7affa60111 - std[1194366af38420ad]::panicking::begin_panic::<rustc_errors[f22a624e573ad349]::ExplicitBug>::{closure#0}
  13:     0x7f7affa5ed16 - std[1194366af38420ad]::sys_common::backtrace::__rust_end_short_backtrace::<std[1194366af38420ad]::panicking::begin_panic<rustc_errors[f22a624e573ad349]::ExplicitBug>::{closure#0}, !>
  14:     0x7f7affa595b6 - std[1194366af38420ad]::panicking::begin_panic::<rustc_errors[f22a624e573ad349]::ExplicitBug>
  15:     0x7f7affa5bd86 - std[1194366af38420ad]::panic::panic_any::<rustc_errors[f22a624e573ad349]::ExplicitBug>
  16:     0x7f7afe42ce88 - <rustc_errors[f22a624e573ad349]::HandlerInner as core[9e79f03012061614]::ops::drop::Drop>::drop
  17:     0x7f7afd7ab298 - core[9e79f03012061614]::ptr::drop_in_place::<rustc_session[ffa4a92384fc7df0]::parse::ParseSess>
  18:     0x7f7afd765398 - <alloc[f02e76f600b2762f]::rc::Rc<rustc_session[ffa4a92384fc7df0]::session::Session> as core[9e79f03012061614]::ops::drop::Drop>::drop
  19:     0x7f7afd76474d - core[9e79f03012061614]::ptr::drop_in_place::<rustc_interface[113e5a7d9d4618b]::interface::Compiler>
  20:     0x7f7afd7640e5 - rustc_span[e67d62ce6d130a16]::with_source_map::<core[9e79f03012061614]::result::Result<(), rustc_errors[f22a624e573ad349]::ErrorGuaranteed>, rustc_interface[113e5a7d9d4618b]::interface::create_compiler_and_run<core[9e79f03012061614]::result::Result<(), rustc_errors[f22a624e573ad349]::ErrorGuaranteed>, rustc_driver[50799d7c8405f566]::run_compiler::{closure#1}>::{closure#1}>
  21:     0x7f7afd763702 - rustc_interface[113e5a7d9d4618b]::interface::create_compiler_and_run::<core[9e79f03012061614]::result::Result<(), rustc_errors[f22a624e573ad349]::ErrorGuaranteed>, rustc_driver[50799d7c8405f566]::run_compiler::{closure#1}>
  22:     0x7f7afd762351 - <scoped_tls[95e243f8d973a695]::ScopedKey<rustc_span[e67d62ce6d130a16]::SessionGlobals>>::set::<rustc_interface[113e5a7d9d4618b]::interface::run_compiler<core[9e79f03012061614]::result::Result<(), rustc_errors[f22a624e573ad349]::ErrorGuaranteed>, rustc_driver[50799d7c8405f566]::run_compiler::{closure#1}>::{closure#0}, core[9e79f03012061614]::result::Result<(), rustc_errors[f22a624e573ad349]::ErrorGuaranteed>>
  23:     0x7f7afd76203f - std[1194366af38420ad]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[113e5a7d9d4618b]::util::run_in_thread_pool_with_globals<rustc_interface[113e5a7d9d4618b]::interface::run_compiler<core[9e79f03012061614]::result::Result<(), rustc_errors[f22a624e573ad349]::ErrorGuaranteed>, rustc_driver[50799d7c8405f566]::run_compiler::{closure#1}>::{closure#0}, core[9e79f03012061614]::result::Result<(), rustc_errors[f22a624e573ad349]::ErrorGuaranteed>>::{closure#0}, core[9e79f03012061614]::result::Result<(), rustc_errors[f22a624e573ad349]::ErrorGuaranteed>>
  24:     0x7f7afe785099 - <<std[1194366af38420ad]::thread::Builder>::spawn_unchecked_<rustc_interface[113e5a7d9d4618b]::util::run_in_thread_pool_with_globals<rustc_interface[113e5a7d9d4618b]::interface::run_compiler<core[9e79f03012061614]::result::Result<(), rustc_errors[f22a624e573ad349]::ErrorGuaranteed>, rustc_driver[50799d7c8405f566]::run_compiler::{closure#1}>::{closure#0}, core[9e79f03012061614]::result::Result<(), rustc_errors[f22a624e573ad349]::ErrorGuaranteed>>::{closure#0}, core[9e79f03012061614]::result::Result<(), rustc_errors[f22a624e573ad349]::ErrorGuaranteed>>::{closure#1} as core[9e79f03012061614]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  25:     0x7f7afc0d9663 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::he022220abf60d2af
                               at /rustc/84f0c3f79a85329dd79a54694ff8a7f427c842e9/library/alloc/src/boxed.rs:1940:9
  26:     0x7f7afc0d9663 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h26bdfd3e52f03485
                               at /rustc/84f0c3f79a85329dd79a54694ff8a7f427c842e9/library/alloc/src/boxed.rs:1940:9
  27:     0x7f7afc0d9663 - std::sys::unix::thread::Thread::new::thread_start::hc76b3d0624b7ab68
                               at /rustc/84f0c3f79a85329dd79a54694ff8a7f427c842e9/library/std/src/sys/unix/thread.rs:108:17
  28:     0x7f7afbfad609 - start_thread
  29:     0x7f7afbed0133 - clone
  30:                0x0 - <unknown>

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.65.0-nightly (84f0c3f79 2022-09-03) running on x86_64-unknown-linux-gnu

note: compiler flags: --crate-type bin -C embed-bitcode=no -C codegen-units=1 -C debuginfo=2

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
thread panicked while panicking. aborting.
error: could not compile `playground`
```

</p>
</details>

### PR DESCRIPTION
**Pull request by compiler-errors**
Fixes #101421
cc #100838

### CODE REVIEW

File: compiler/rustc_typeck/src/structured_errors/wrong_number_of_generic_args.rs [hunk 1]
```diff
@@ -752,23 +752,50 @@ impl<'a, 'tcx> WrongNumberOfGenericArgs<'a, 'tcx> {
...
         err: &mut Diagnostic,
-        trait_: DefId,
+        trait_def_id: DefId,
         expr: &'tcx hir::Expr<'tcx>,
         msg: String,
         num_assoc_fn_excess_args: usize,
         num_trait_generics_except_self: usize,
     ) {
-        if let hir::ExprKind::MethodCall(_, args, _) = expr.kind {
-            assert_eq!(args.len(), 1);
```
Comment (compiler-errors) [inline compiler/rustc_typeck/src/structured_errors/wrong_number_of_generic_args.rs:762]: Nothing enforces this assertion as a precondition, and also it's artificially quite limiting. There's no reason we can't make this suggestion for when there are >1 arguments, and so I generalized it -- that's where most of this logic comes from.

File: src/test/ui/suggestions/move-generic-to-trait-in-method-with-params.stderr [hunk 2]
```diff
@@ -0,0 +1,24 @@
...
+   |       ^^^ expected 0 generic arguments
+   |
+note: associated function defined here, with 0 generic parameters
+  --> $DIR/move-generic-to-trait-in-method-with-params.rs:4:8
+   |
+LL |     fn bar(&self, _: T);
+   |        ^^^
+help: consider moving this generic argument to the `Foo` trait, which takes up to 1 argument
+   |
+LL |     Foo::<i32>::bar(1, 0);
```
Comment (compiler-errors) [inline src/test/ui/suggestions/move-generic-to-trait-in-method-with-params.stderr:14]: This suggestion is actually wrong -- but we are not far enough along in type-check to know if the receiver is being autoref'd here. But anyways, this suggestion is MaybeIncorrect, so no big deal.

File: compiler/rustc_typeck/src/structured_errors/wrong_number_of_generic_args.rs [hunk 3]
```diff
@@ -752,23 +752,45 @@ impl<'a, 'tcx> WrongNumberOfGenericArgs<'a, 'tcx> {
...
-                    err.span_suggestion(expr.span, msg, sugg, Applicability::MaybeIncorrect);
-                }
-            }
+        let sm = self.tcx.sess.source_map();
+        let hir::ExprKind::MethodCall(_, [rcvr, args @ ..], _) = expr.kind else { return; };
+        if num_assoc_fn_excess_args != num_trait_generics_except_self {
+            return;
         }
+        let Some(gen_args) = self.gen_args.span_ext() else { return; };
+        let Ok(generics) = self.tcx.sess.source_map().span_to_snippet(gen_args) else { return; };
```
Comment (cjgillot) [inline compiler/rustc_typeck/src/structured_errors/wrong_number_of_generic_args.rs:767]:
```suggestion
        let Ok(generics) = sm.span_to_snippet(gen_args) else { return; };
```

File: compiler/rustc_typeck/src/structured_errors/wrong_number_of_generic_args.rs [hunk 4]
```diff
@@ -752,23 +752,45 @@ impl<'a, 'tcx> WrongNumberOfGenericArgs<'a, 'tcx> {
...
+        let Ok(rcvr) = self.tcx.sess.source_map().span_to_snippet(
```
Comment (cjgillot) [inline compiler/rustc_typeck/src/structured_errors/wrong_number_of_generic_args.rs:768]:
```suggestion
        let Ok(rcvr) = sm.span_to_snippet(
```

File: compiler/rustc_typeck/src/structured_errors/wrong_number_of_generic_args.rs [hunk 5]
```diff
@@ -752,23 +752,45 @@ impl<'a, 'tcx> WrongNumberOfGenericArgs<'a, 'tcx> {
...
+            rcvr.span.find_ancestor_inside(expr.span).unwrap_or(rcvr.span)
+        ) else { return; };
+        let Ok(rest) =
+            (match args {
+                [] => Ok(String::new()),
+                [arg] => self.tcx.sess.source_map().span_to_snippet(
```
Comment (cjgillot) [inline compiler/rustc_typeck/src/structured_errors/wrong_number_of_generic_args.rs:774]:
```suggestion
                [arg] => sm.span_to_snippet(
```

**Review by cjgillot — COMMENTED** [review]
I'm usually not a fan of `span_to_snippet`, but I don't see how else this would work here.
r=me with a few nits
