### PR TITLE
Fix incorrect clashing_extern_declarations warnings.

### LINKED ISSUE #73735: Incorrect clashing_extern_decl warning in nightly
PR #70946 introduces new clashing_extern_decl lint which causes incorrect warning even when two extern functions are ABI compatible:
```rust
#![allow(dead_code)]

#[repr(transparent)]
struct T(usize);

mod a {
    use super::T;
    extern "C" {
        fn test() -> T;
    }
}

mod b {
    extern "C" {
        fn test() -> usize;
    }
}
```

Some other example pairs that are ABI compatible that are incorrectly warned
* `fn test() -> usize` and `fn test()`
* `fn test() -> usize` and `fn test() -> NonZeroUsize`
* `fn test() -> usize` and `fn test() -> Option<NonZeroUsize>`

This issue has been assigned to @jumbatm via [this comment](https://github.com/rust-lang/rust/issues/73735#issuecomment-649837650).

### LINKED ISSUE #73872: clashing_extern_declarations misses clashes of same-sized members of structs
The `clashing_extern_declarations` lint currently incorrectly misses clashing extern fn declarations if they clash on a struct with same-sized members.

In this example here:

```rust
#![crate_type = "lib"]
#![allow(unused)]

mod a {
    #[repr(C)]
    struct Point3 {
        x: f32,
        y: f32,
        z: f32,
    }
    extern "C" { fn origin() -> Point3; }
}
mod b {
    #[repr(C)]
    struct Point3 {
        x: i32,
        y: i32,
        z: i32, // NOTE: Incorrectly redeclared as i32
    }
    extern "C" { fn origin() -> Point3; }
}
```

([Playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=566d09f91b6ff2d64d4187ee33ac9191))

The declaration of `origin` should clash, because `a::Point3` and `b::Point3` have members of different type. However, the lint currently misses that the return type of `origin` is inconsistently declared, even though an`i32` and `f32` clash is warned on its own:

```rust
mod a {
    extern "C" { fn clash(x: i32); }
}
mod b {
    extern "C" { fn clash(x: f32); } //~ WARN `clash` redeclared with a different signature
}
```
Note that this false negative only occurs for same-sized members -- the lint correctly fires for members of different sizes:
```rust
mod a {
    #[repr(C)]
    struct Point3 {
        x: f32,
        y: f32,
        z: f32,
    }
    extern "C" { fn origin() -> Point3; }
}
mod b {
    #[repr(C)]
    struct Point3 {
        x: i64,
        y: i64,
        z: i64,
    }
    extern "C" { fn origin() -> Point3; }
    //~^ WARN `origin` redeclared with a different signature
}
```

This issue has been assigned to @jumbatm via [this comment](https://github.com/rust-lang/rust/issues/73872#issuecomment-651372299).

### PR DESCRIPTION
**Pull request by jumbatm**
Fixes #73735, fixes #73872.

Fix clashing_extern_declarations warning for `#[repr(transparent)]` structs and safely-FFI-convertible enums, and not warning for clashes of struct members of different types, but the same size.

r? @nagisa

### CODE REVIEW

File: src/librustc_lint/builtin.rs [hunk 1]
```diff
@@ -2196,7 +2198,56 @@ impl ClashingExternDeclarations {
                 | (Opaque(..), Opaque(..)) => false,
                 // These definitely should have been caught above.
                 (Bool, Bool) | (Char, Char) | (Never, Never) | (Str, Str) => unreachable!(),
-                _ => false,
+
+                // Disjoint kinds.
+                (_, _) => {
+                    // First, check if the conversion is FFI-safe. This can be so if the type is an
```
Comment (teymour-aldridge) [inline src/librustc_lint/builtin.rs:2204]:
```suggestion
                    // First, check if the conversion is FFI-safe. This can happen if the type is an
```

File: src/librustc_lint/builtin.rs [hunk 2]
```diff
@@ -2196,7 +2198,56 @@ impl ClashingExternDeclarations {
...
+                                            // This check works for both signed and unsigned types due to wraparound.
+                                            && *safe_range.start() == 1
+                                            && *primitive_range.start() == 0;
+                                    }
+                                    _ => {}
+                                }
+                            }
+                        }
+                    }
+                    // Otherwise, just compare the layouts. This may be underapproximate, but at
```
Comment (teymour-aldridge) [inline src/librustc_lint/builtin.rs:2247]:
```suggestion
                    // Otherwise, just compare the layouts. This may be inaccurate, but at
```

File: src/librustc_lint/types.rs [hunk 3]
```diff
@@ -559,15 +559,16 @@ impl<'a, 'tcx> ImproperCTypesVisitor<'a, 'tcx> {
 
     /// Check if this enum can be safely exported based on the "nullable pointer optimization".
     /// Currently restricted to function pointers, references, `core::num::NonZero*`,
-    /// `core::ptr::NonNull`, and `#[repr(transparent)]` newtypes.
-    fn is_repr_nullable_ptr(
+    /// `core::ptr::NonNull`, and `#[repr(transparent)]` newtypes. If it is, return the known
```
Comment (teymour-aldridge) [inline src/librustc_lint/types.rs:562]:
```suggestion
    /// `core::ptr::NonNull`, and `#[repr(transparent)]` newtypes. If it can, return the known
```

File: src/librustc_lint/types.rs [hunk 4]
```diff
@@ -559,15 +559,16 @@ impl<'a, 'tcx> ImproperCTypesVisitor<'a, 'tcx> {
...
+    /// non-null field type, else None.
```
Comment (teymour-aldridge) [inline src/librustc_lint/types.rs:563]:
```suggestion
    /// non-null field type, otherwise return `None`.
```

File: src/test/ui/lint/clashing-extern-fn.rs [hunk 5]
```diff
@@ -180,7 +168,93 @@ mod sameish_members {
...
+mod missing_return_type {
+    mod a {
+        extern "C" {
+            fn missing_return_type() -> usize;
+        }
+    }
+
+    mod b {
+        extern "C" {
+            // This should warn, because we can't assume that the first declaration is the correct
```
Comment (teymour-aldridge) [inline src/test/ui/lint/clashing-extern-fn.rs:205]: I think it's stylistically better without the comma.
```suggestion
            // This should output a warning because we can't assume that the first declaration is the correct
```

File: src/test/ui/lint/clashing-extern-fn.rs [hunk 6]
```diff
@@ -180,7 +168,93 @@ mod sameish_members {
...
+mod non_zero_and_non_null {
+    mod a {
+        extern "C" {
+            fn non_zero_usize() -> core::num::NonZeroUsize;
+            fn non_null_ptr() -> core::ptr::NonNull<usize>;
+        }
+    }
+    mod b {
+        extern "C" {
+            // For both of these cases, if there's a clash, you're either gaining an incorrect
```
Comment (teymour-aldridge) [inline src/test/ui/lint/clashing-extern-fn.rs:223]:
```suggestion
            // If there's a clash in either of these cases you're either gaining an incorrect
```

File: src/librustc_lint/builtin.rs (hunk 2 above)
Comment (nagisa) [reply src/librustc_lint/builtin.rs:2247]: "have false negatives", or better yet, "might fail to lint for some incompatible types"...

File: src/librustc_lint/builtin.rs [hunk 7]
```diff
@@ -2196,7 +2198,56 @@ impl ClashingExternDeclarations {
...
+                        && !(is_primitive_or_pointer(a) && is_primitive_or_pointer(b))
+                        && (matches!(a_kind, Adt(..)) || matches!(b_kind, Adt(..)))
+                    /* ie, 1 adt and 1 primitive */
+                    {
+                        let (primitive_ty, adt_ty) =
+                            if is_primitive_or_pointer(a) { (a, b) } else { (b, a) };
+                        // First, check that the Adt is FFI-safe to use.
+                        use crate::types::{ImproperCTypesMode, ImproperCTypesVisitor};
+                        let vis =
+                            ImproperCTypesVisitor { cx, mode: ImproperCTypesMode::Declarations };
```
Comment (nagisa) [inline src/librustc_lint/builtin.rs:2218]: Rather than constructing this visitor here (looks super out of place), consider finding how to make the function(s) you’re calling plain top-level functions. They became a method very recently, in #73758, but from what I can tell there is no reason they _need_ to be a method on the `ImproperCTypesVisitor`. 

cc @davidtwco Is there any reason why it would be unreasonable to make those functions free-standing again?

File: src/librustc_lint/builtin.rs [hunk 8]
```diff
@@ -2196,7 +2198,56 @@ impl ClashingExternDeclarations {
...
+                            if let Some(safe_ty) = repr_nullable {
+                                let safe_ty_layout = &cx.layout_of(safe_ty).unwrap();
+                                let primitive_ty_layout = &cx.layout_of(primitive_ty).unwrap();
+
+                                use rustc_target::abi::Abi::*;
+                                match (&safe_ty_layout.abi, &primitive_ty_layout.abi) {
+                                    (Scalar(safe), Scalar(primitive)) => {
+                                        // The two types are safe to convert between if `safe` is
+                                        // the non-zero version of `primitive`.
+                                        use std::ops::RangeInclusive;
```
Comment (nagisa) [inline src/librustc_lint/builtin.rs:2231]: Move the `use` to the top of the file.

File: src/librustc_lint/builtin.rs [hunk 9]
```diff
@@ -2196,7 +2198,56 @@ impl ClashingExternDeclarations {
...
+                        let vis =
+                            ImproperCTypesVisitor { cx, mode: ImproperCTypesMode::Declarations };
+
+                        if let Adt(def, substs) = adt_ty.kind {
+                            let repr_nullable = vis.is_repr_nullable_ptr(adt_ty, def, substs);
+                            if let Some(safe_ty) = repr_nullable {
+                                let safe_ty_layout = &cx.layout_of(safe_ty).unwrap();
+                                let primitive_ty_layout = &cx.layout_of(primitive_ty).unwrap();
+
+                                use rustc_target::abi::Abi::*;
```
Comment (nagisa) [inline src/librustc_lint/builtin.rs:2226]: `use` `Abi` at the top of the file and refer to variants via `Abi::Scalar` – there are just two references anyway, so the glob import doesn’t feel super justified.

File: src/librustc_lint/builtin.rs [hunk 10]
```diff
@@ -2196,7 +2198,56 @@ impl ClashingExternDeclarations {
...
+
+                // Disjoint kinds.
+                (_, _) => {
+                    // First, check if the conversion is FFI-safe. This can be so if the type is an
+                    // enum with a non-null field (see improper_ctypes).
+                    let is_primitive_or_pointer =
+                        |ty: Ty<'tcx>| ty.is_primitive() || matches!(ty.kind, RawPtr(..));
+                    if (is_primitive_or_pointer(a) || is_primitive_or_pointer(b))
+                        && !(is_primitive_or_pointer(a) && is_primitive_or_pointer(b))
+                        && (matches!(a_kind, Adt(..)) || matches!(b_kind, Adt(..)))
```
Comment (nagisa) [inline src/librustc_lint/builtin.rs:2210]: Consider moving this condition to the surrounding match with a guard. That is this whole complicated `if` condition can be replaced with a somewhat more readable:

```rust
(adt_ty@Adt(..), primitive_ty) | (primitive_ty, adt_ty@Adt(..)) 
  if is_primitive_or_pointer(primitive_ty) => { ... }
_ => { /* the else branch */ }
```

It would also avoid you to have to construct `primitive_ty` and `adt_ty` just below.

File: src/librustc_lint/builtin.rs [hunk 11]
```diff
@@ -2196,7 +2198,56 @@ impl ClashingExternDeclarations {
...
+                    /* ie, 1 adt and 1 primitive */
+                    {
+                        let (primitive_ty, adt_ty) =
+                            if is_primitive_or_pointer(a) { (a, b) } else { (b, a) };
+                        // First, check that the Adt is FFI-safe to use.
+                        use crate::types::{ImproperCTypesMode, ImproperCTypesVisitor};
```
Comment (nagisa) [inline src/librustc_lint/builtin.rs:2216]: `use` at the top of file instead.

File: src/librustc_lint/builtin.rs [hunk 12]
```diff
@@ -2196,7 +2198,56 @@ impl ClashingExternDeclarations {
...
+                                        use std::ops::RangeInclusive;
+
+                                        let safe_range: &RangeInclusive<_> = &safe.valid_range;
+                                        let primitive_range: &RangeInclusive<_> =
+                                            &primitive.valid_range;
+
+                                        return primitive_range.end() == safe_range.end()
+                                            // This check works for both signed and unsigned types due to wraparound.
+                                            && *safe_range.start() == 1
+                                            && *primitive_range.start() == 0;
```
Comment (nagisa) [inline src/librustc_lint/builtin.rs:2240]: These two conditions look somewhat sketchy. In the future exactly the same equivalence optimization could apply for `usize == Option<NonAllBitsSetUsize>` where `Option::None` would be represented by `!0`. And this little piece of code would most likely end up being missed during implementation of such functionality. I wonder if there isn’t a better way to check for this…

If not, maybe just compare the size of the two types?

File: src/librustc_lint/builtin.rs (hunk 7 above)
Comment (davidtwco) [reply src/librustc_lint/builtin.rs:2218]: They could probably be made freestanding again, I think I only made them methods so they could access the `ParamEnv` which could just as well be an argument.

File: src/librustc_lint/builtin.rs (hunk 10 above)
Comment (jumbatm) [reply src/librustc_lint/builtin.rs]: I'm not able to replace constructing `primitive_ty` and `adt_ty` because I'm matching on `TyKind`s, not `Ty`s (unless I match directly on `a` and `b`, which would mean every arm would need `Ty { kind: ... }`).  Still, I've simplified the match a bit based on your suggestion -- it's much more readable now. Thanks!

File: src/librustc_lint/builtin.rs (hunk 12 above)
Comment (jumbatm) [reply src/librustc_lint/builtin.rs]: > I wonder if there isn’t a better way to check for this…

I've opted for a more general check of seeing if one range excludes a single value of the other, which should also cover the case you've described.

File: src/librustc_lint/types.rs [hunk 13]
```diff
@@ -509,14 +509,14 @@ declare_lint! {
 
 declare_lint_pass!(ImproperCTypesDefinitions => [IMPROPER_CTYPES_DEFINITIONS]);
 
-enum ImproperCTypesMode {
+crate enum ImproperCTypesMode {
```
Comment (nagisa) [inline src/librustc_lint/types.rs:512]: These don’t need to be public anymore, do they?

**Comment by jumbatm** [comment]
This is good for re-review.

File: src/librustc_lint/types.rs [hunk 14]
```diff
@@ -525,82 +525,77 @@ enum FfiResult<'tcx> {
...
-                        return true;
-                    }
+fn ty_is_known_nonnull<'tcx>(tcx: TyCtxt<'tcx>, ty: Ty<'tcx>) -> bool {
+    match ty.kind {
+        ty::FnPtr(_) => true,
+        ty::Ref(..) => true,
+        ty::Adt(field_def, substs) if field_def.repr.transparent() && !field_def.is_union() => {
+            for field in field_def.all_fields() {
+                let field_ty =
+                    tcx.normalize_erasing_regions(ParamEnv::reveal_all(), field.ty(tcx, substs));
```
Comment (nagisa) [inline src/librustc_lint/types.rs:535]: AFAIU from #73758 `reveal_all` is to be avoided here? Maybe accept is an argument? Or instead of taking `TyCtxt` take a `LateContext<'tcx>` which contains the param_env?

cc @davidtwco

Comment (davidtwco) [reply src/librustc_lint/types.rs:535]: Yeah, `LateContext`’s `param_env` should be used in lints.

File: src/librustc_lint/types.rs [hunk 15]
```diff
@@ -525,82 +525,77 @@ enum FfiResult<'tcx> {
...
+    let field_ty = fields[0].ty(tcx, substs);
+    if !ty_is_known_nonnull(tcx, field_ty) {
+        return None;
+    }
 
-        true
+    // At this point, the field's type is known to be nonnull and the parent enum is Option-like.
+    // If the computed size for the field and the enum are different, the nonnull optimization isn't
+    // being applied (and we've got a problem somewhere).
+    let compute_size_skeleton = |t| SizeSkeleton::compute(t, tcx, ParamEnv::reveal_all()).unwrap();
```
Comment (davidtwco) [inline src/librustc_lint/types.rs:590]: This change should also still use `LateContext`s `param_env`.

File: src/librustc_lint/builtin.rs (hunk 12 above)
Comment (nagisa) [reply src/librustc_lint/builtin.rs]: Hm… I think I did a bad job at conveying the point I was trying to make here.

What I really wanted to say is that this introduces another source of truth on how the optimisation behaves and where it applies. There is already some code that codifies this kind of information in the layout calculation code (although not easily reusable here, I think) and  `is_repr_nullable_ptr` is yet another place where this happens. _If_, somebody was adjusting how this optimisation works to e.g. admit more cases or fix a bug… there is no provision to ensure that they do not miss updating all of those portions of code, including here. So its better to have fewer such sources of truth than more.

In particular to me it looks like `is_repr_nullable_ptr` already goes to some length to make sure that the contained field is a type that participates in nullable type optimisation, so I suspect this check could be dropped entirely. Is there perhaps a specific reason you want to check ranges that I’m missing? Maybe it would then make sense to move that check to more shared code like `is_repr_nullable_ptr` in the first place, then?

File: src/librustc_lint/types.rs (hunk 14 above)
Comment (jumbatm) [reply src/librustc_lint/types.rs:535]: Oops, yeah, good catch -- got a little too happy reverting.

File: src/librustc_lint/builtin.rs (hunk 12 above)
Comment (jumbatm) [reply src/librustc_lint/builtin.rs]: >its better to have fewer such sources of truth than more

Ohh, I see what you mean. Yeah, I agree -- that makes sense.

> Is there perhaps a specific reason you want to check ranges that I’m missing?

`is_repr_nullable_ptr` only checks if something like Option<NonZeroUsize> is okay, but doesn't check the type that it's casted to/from. I check the ranges to ensure, for example, that `Option<NonZeroUsize>` is being correctly converted to `usize`, and not to `isize` or another same-sized-but-incorrect type.

> move that check to more shared code like is_repr_nullable_ptr

I've currently got `is_repr_nullable_ptr` just returning the type inside the Option-like enum, which I've come to realise isn't actually that useful. Yeah, I'll go with this -- it'd probably be better to have `is_repr_nullable_ptr` return the type that the `Option<T>` is FFI-convertible to (if it exists), and ClashingExternDeclarations can just compare `primitive_ty` to that type.

**Comment by jumbatm** [comment]
I'm still working on getting `is_repr_nullable_ptr` returning the type that's FFI-safe to use, but in the meantime, I've got a working (but quite awkward) solution where the caller optionally passes a type to check against.

**Comment by jumbatm** [comment]
Alright, this good for re-review -- I have `repr_nullable_ptr` returning the corresponding FFI-safe type as I mentioned earlier.

File: src/librustc_lint/types.rs [hunk 16]
```diff
@@ -525,49 +526,41 @@ enum FfiResult<'tcx> {
...
-                        return true;
-                    }
+fn ty_is_known_nonnull<'tcx>(tcx: TyCtxt<'tcx>, ty: Ty<'tcx>) -> bool {
+    match ty.kind {
+        ty::FnPtr(_) => true,
+        ty::Ref(..) => true,
+        ty::Adt(field_def, substs) if field_def.repr.transparent() && !field_def.is_union() => {
+            for field in field_def.all_fields() {
+                let field_ty =
+                    tcx.normalize_erasing_regions(ParamEnv::reveal_all(), field.ty(tcx, substs));
```
Comment (nagisa) [inline src/librustc_lint/types.rs:536]: Still need to pass in a `LateContext`rather than `TyCtxt` into the function and use the `ParamEnv` available in the context.

File: src/librustc_lint/types.rs [hunk 17]
```diff
@@ -577,30 +570,86 @@ impl<'a, 'tcx> ImproperCTypesVisitor<'a, 'tcx> {
...
         }
 
-        true
+        // Return the nullable type this Option-like enum can be safely represented with.
+        let field_ty_abi = &cx.layout_of(field_ty).unwrap().abi;
+        if let Abi::Scalar(field_ty_scalar) = field_ty_abi {
+            match (field_ty_scalar.valid_range.start(), field_ty_scalar.valid_range.end()) {
+                (0, _) => bug!("Non-null optimisation extended to a non-zero value."),
+                (1, _) => {
+                    fn get_nullable_kind<'tcx>(tcx: TyCtxt<'tcx>, ty: Ty<'tcx>) -> Ty<'tcx> {
```
Comment (nagisa) [inline src/librustc_lint/types.rs:599]: Style nit: I would probably just extract this function out into the module level, even if just to reduce the nesting.

**Comment by nagisa** [comment]
Broadly lgtm, left 2 minor comments, r=me once resolved.

**Comment by jumbatm** [comment]
The changes have been applied. This is good to go.

**Comment by jumbatm** [comment]
Note that I've also added a few additional commits; they fix an assertion failure and false negative I noticed while working on this.

**Comment by jumbatm** [comment]
I've just done another rebase -- @nagisa, are you available to review and approve? I'd like to get this merged soon so that these fixes can be backported to beta, and so I can try a crater check run with this lint as deny-by-default.

**Comment by pnkfelix** [comment]
[discussed](https://zulip-archive.rust-lang.org/238009tcompilermeetings/48776weeklymeeting2020073054818.html#205483772) at T-compiler meeting.

We decided the complexity of this PR, weighed against the bug it fixes, does not warrant a backport.

However, we agreed that a PR that just changed the lint on beta to be allow-by-default would be a reasonable thing to put on the beta branch.

File: src/librustc_lint/types.rs [hunk 18]
```diff
@@ -525,54 +527,94 @@ enum FfiResult<'tcx> {
...
+            return None;
+        }
+    })
+}
+
+/// Check if this enum can be safely exported based on the "nullable pointer optimization". If it
+/// can, return the the type that `ty` can be safely converted to, otherwise return `None`.
+/// Currently restricted to function pointers, boxes, references, `core::num::NonZero*`,
+/// `core::ptr::NonNull`, and `#[repr(transparent)]` newtypes.
+/// FIXME: This duplicates code in codegen.
```
Comment (RalfJung) [inline src/librustc_lint/types.rs:608]: Does anyone involved still remember *which* code in codegen this duplicates? The comment as-is is unfortunately not very helpful since it is unclear where that duplication is.

Comment (RalfJung) [reply src/librustc_lint/types.rs:608]: Ah never mind, this comment predates this PR, it just got moved here.
