### PR TITLE
rustdoc: Censor certain complex unevaluated const exprs

### LINKED ISSUE #97933: Rustdoc displays private internals of associated constants (regression)
```rust
pub struct Struct {
    private: (),
}

impl Struct {
    pub const CONST: Self = Struct { private: () };
}
```

<br>

### Correct:

<br>

### Incorrect:

<br>

I used the following script to bisect:

```bash
#!/bin/bash
cargo doc && ! rg private: $CARGO_TARGET_DIR/doc/repro/struct.Struct.html >/dev/null
```

```console
cargo-bisect-rustc --script ./bisect.sh
```

It bisects to nightly-2022-04-14 and specifically https://github.com/rust-lang/rust/pull/95990, of which https://github.com/rust-lang/rust/pull/95316 seems the most relevant because it involves associated constants in rustdoc. @fmease @notriddle @GuillaumeGomez

### PR DESCRIPTION
**Pull request by fmease**
Fixes #97933.

This is more of a hotfix for the aforementioned issue. By that, I mean that my proposed patch is
not the best solution but one that does not change as much existing code.
It treats symptoms rather than the root cause.

This PR “censors” certain complex unevaluated constant expressions like `match`es, blocks, function calls, struct literals etc. by pretty-printing them as `_` / `{ _ }` (number and string literals, paths and `()` are still printed as one would expect).
Resorting to this placeholder is preferable to printing the full expression verbatim since
they can be quite large and verbose resulting in an unreadable mess in the generated documentation.
Further, mindlessly printing the const would leak private and `doc(hidden)` struct fields (#97933), at least in the current
stable & nightly implementations which rely on `span_to_snippet` (!) and `rustc_hir_pretty::id_to_string`.

The censoring of _verbose_ expressions is probably going to stay longer term.
However, in regards to private and `doc(hidden)` struct fields, I have a more proper fix in mind
which I have already partially implemented locally and for which I am going to open a separate PR sometime soon.
For that, I was already in contact with @GuillaumeGomez.
The proper fix involves rustdoc not falling back on pretty-printing unevaluated consts so easily (what this PR is concerned about)
and instead preferring to print evaluated consts which contain more information allowing it to selectively hide private and `doc(hidden)` fields, create hyperlinks etc. generally making the output more granular and precise (compared to the brutal `_` placeholder).

Unfortunately, I was a bit too late and the issue just hit stable (1.62).
Should this be backported to beta or even a potential 1.62.1?

r? @GuillaumeGomez

### CODE REVIEW

File: src/librustdoc/clean/utils.rs [hunk 1]
```diff
@@ -343,17 +343,92 @@ pub(crate) fn is_literal_expr(tcx: TyCtxt<'_>, hir_id: hir::HirId) -> bool {
...
+            }
+            // Paths with a self-type or arguments are too “complex” following our measure since
+            // they may leak private fields of structs (with feature `adt_const_params`).
+            // Consider: `<Self as Trait<{ Struct { private: () } }>>::CONSTANT`.
+            // Paths without arguments are fine though.
+            hir::ExprKind::Path(hir::QPath::Resolved(_, hir::Path { segments, .. })) => {
+                if segments.iter().all(|segment| segment.args.is_none()) { Simple } else { Complex }
+            }
+            // FIXME: Claiming those kinds of QPaths are simple is probably not true if the Ty
+            //        contains const arguments. Is there a *concise* way to check for this?
```
Comment (GuillaumeGomez) [inline src/librustdoc/clean/utils.rs:399]: Little typo:

```suggestion
            //        contains const arguments. Is there is a *concise* way to check for this?
```

File: src/librustdoc/clean/utils.rs [hunk 2]
```diff
@@ -343,17 +343,92 @@ pub(crate) fn is_literal_expr(tcx: TyCtxt<'_>, hir_id: hir::HirId) -> bool {
...
+        snippet
+    } else if classification == Simple {
+        // Otherwise we prefer pretty-printing to get rid of extraneous whitespace, comments and
+        // other formatting artifacts.
+        rustc_hir_pretty::id_to_string(&hir, body.hir_id)
+    } else if tcx.def_kind(hir.body_owner_def_id(body).to_def_id()) == DefKind::AnonConst {
+        // FIXME: Omit the curly braces if the enclosing expression is an array literal
+        //        with a repeated element (an `ExprKind::Repeat`) as in such case it
+        //        would not actually need any disambiguation.
+        "{_}".to_owned()
```
Comment (GuillaumeGomez) [inline src/librustdoc/clean/utils.rs:428]: Maybe `{ _ }`? (with whitespaces)

File: src/librustdoc/html/render/mod.rs [hunk 3]
```diff
@@ -707,12 +707,17 @@ fn assoc_const(
...
+        write!(w, " = ");
+
         // FIXME: `.value()` uses `clean::utils::format_integer_with_underscore_sep` under the
         //        hood which adds noisy underscores and a type suffix to number literals.
         //        This hurts readability in this context especially when more complex expressions
         //        are involved and it doesn't add much of value.
         //        Find a way to print constants here without all that jazz.
-        write!(w, " = {}", default.value(cx.tcx()).unwrap_or_else(|| default.expr(cx.tcx())));
+        match default.value(cx.tcx()) {
+            Some(value) => write!(w, "{}", value),
```
Comment (GuillaumeGomez) [inline src/librustdoc/html/render/mod.rs:718]: Why only the `None` is being `Escape`d?

**Comment by GuillaumeGomez** [comment]
Looks like a nice improvement, thanks for working on this! What does a type with only public fields looks like btw? Could you add a test for this case please?

Also cc @notriddle

**Comment by fmease** [comment]
I've addressed all of your comments (except for the “typo“ one).

**Review by notriddle — APPROVED** [review]

File: src/librustdoc/clean/utils.rs (hunk 1 above)
Comment (GuillaumeGomez) [reply src/librustdoc/clean/utils.rs:404]: Woups, indeed. My bad.

**Review by GuillaumeGomez — APPROVED** [review]

**Comment by GuillaumeGomez** [comment]
I think it's good enough for a first step. Please open issues (if not done already) for the next steps.

@bors r+ rollup

**Comment by fmease** [comment]
Great! I am going to open issues for things that need to be done.
@ GuillaumeGomez, since you agreed to my idea to backport this patch to beta, would you mind adding the `beta-nominated` label to this PR? I don't think I have the permission for that, do you?

**Comment by GuillaumeGomez** [comment]
For the beta nomination, I need other rustdoc people to accept too.

Are you ok with backporting this fix bet @rust-lang/rustdoc ?
