### PR TITLE
Fix the invalidation of the MIR early exit cache

### LINKED ISSUE #35737: drop not always behaving since nightly-2016-08-03-x86_64-unknown-linux-gnu
This was discovered in database connection pooling where connections were not returned to the pool properly, and reported under https://github.com/sfackler/r2d2/issues/25

Unfortunately I do not have example code small enough to share at this point.

I narrowed down the rust-nightly version that introduced the bug to nightly-2016-08-03-x86_64-unknown-linux-gnu

@sfackler

### PR DESCRIPTION
**Pull request by nagisa**
~~The #34307 introduced a cache for early exits in order to help with O(n*m) explosion of cleanup blocks but the cache is invalidated incorrectly and I can’t seem to figure out why (caching is hard!)~~

~~Remove the cache for now to fix the immediate correctness issue and worry about the performance later.~~

Cache invalidation got fixed.

Fixes #35737

r? @nikomatsakis

### CODE REVIEW

**Comment by eddyb** [comment]
I'm not seeing any invalidation *at all* for `cached_exits`, seems that it's just missing?

**Comment by nagisa** [comment]
@eddyb it was [here](https://github.com/rust-lang/rust/pull/35751/files#diff-efe92a4bb85e2e14ca66c492d897de28L202)

**Comment by eddyb** [comment]
@nagisa Oops, I see. I would've expected `.clear()` instead of throwing it away.

**Comment by arielb1** [comment]
I would prefer to keep the cache through.

**Comment by nagisa** [comment]
Cache invalidation fixed.

File: src/librustc_mir/build/scope.rs [hunk 1]
```diff
@@ -455,25 +458,24 @@ impl<'a, 'gcx, 'tcx> Builder<'a, 'gcx, 'tcx> {
...
         for scope in self.scopes.iter_mut().rev() {
-            if scope.extent == extent {
+            // We must invalidate all the caches leading up to the scope we’re looking for, because
+            // the cached blocks will branch into build of scope not containing the new drop. If we
+            // add stuff to the currently inspected scope, then in some cases the non-unwind caches
+            // may become invalid, therefore we should invalidate these as well. The unwind caches
+            // will stay correct, because the already generated unwind blocks cannot be influenced
+            // by just added drop.
+            let this_scope = scope.extent == extent;
+            scope.invalidate_cache(!this_scope);
```
Comment (eddyb) [inline src/librustc_mir/build/scope.rs]: This will invalidate the unwind cache in cases other than `DropKind::Value`, which is undesirable (as `StorageDead` doesn't end up on the unwind path at all).

File: src/librustc_mir/build/scope.rs [hunk 2]
```diff
@@ -455,25 +458,29 @@ impl<'a, 'gcx, 'tcx> Builder<'a, 'gcx, 'tcx> {
...
+            // the cached blocks will branch into build of scope not containing the new drop. If we
+            // add stuff to the currently inspected scope, then in some cases the non-unwind caches
+            // may become invalid, therefore we should invalidate these as well. The unwind caches
+            // will stay correct, because the already generated unwind blocks cannot be influenced
+            // by just added drop.
+            //
+            // If we’re scheduling cleanup for non-droppable type (i.e. DropKind::Storage), then we
+            // do not need to invalidate unwind branch, because DropKind::Storage does not end up
+            // built in the unwind branch currently.
+            let invalidate_unwind = needs_drop || !this_scope;
```
Comment (eddyb) [inline src/librustc_mir/build/scope.rs]: This needs to be `&&`, not `||`.

File: src/librustc_mir/build/scope.rs [hunk 3]
```diff
@@ -455,25 +458,29 @@ impl<'a, 'gcx, 'tcx> Builder<'a, 'gcx, 'tcx> {
         };
 
         for scope in self.scopes.iter_mut().rev() {
-            if scope.extent == extent {
+            let this_scope = scope.extent == extent;
+            // We must invalidate all the caches leading up to the scope we’re looking for, because
+            // the cached blocks will branch into build of scope not containing the new drop. If we
```
Comment (nikomatsakis) [inline src/librustc_mir/build/scope.rs]: I have a hard time following this comment, I'm afraid. Ideal would be a diagram, but maybe we can just tweak the wording...I don't quite know how since I don't understand it yet :)

Comment (nagisa) [inline src/librustc_mir/build/scope.rs]: I’ll try to draw something up.

**Comment by nikomatsakis** [comment]
Accepting for beta: this was a serious correctness regression.
