### PR TITLE
Fix requires_lto targets needing lto set in cargo

### LINKED ISSUE #148514: amdgcn-amd-amdhsa target broken? Fails to build core
I tried this code:

```rust
#![no_std]
fn foo() {}
```
with
`RUSTFLAGS="-Ctarget-cpu=gfx1103 --emit=llvm-bc,llvm-ir" cargo +offload build -Zunstable-options -r -v --target amdgcn-amd-amdhsa -Zbuild-std=core`
(As a tier 3 target, build-std is mandatory).

I expected to see this happen: compiles

Instead, this happened:
It fails to compile core: 
```
rustc: /home/manuel/prog/rust_gpu/src/llvm-project/llvm/lib/CodeGen/SelectionDAG/SelectionDAG.cpp:9502: SDValue llvm::SelectionDAG::getLoad(ISD::MemIndexedMode, ISD::LoadExtType, EVT, const SDLoc &, SDValue, SDValue, SDValue, EVT, MachineMemOperand *): Assertion `(!MMO->getRanges() || (mdconst::extract<ConstantInt>(MMO->getRanges()->getOperand(0)) ->getBitWidth() == MemVT.getScalarSizeInBits() && MemVT.isInteger())) && "Range metadata and load type must match!"' failed.
```

This is *not* reproducible on nightly, which doesn't seem surprising given: https://rustc-dev-guide.rust-lang.org/backend/debugging.html?highlight=llvm-assertions#enable-llvm-internal-checks

### Meta

`rustc --version --verbose`:
```
latest master, build from source
```
cc @Flakebi 

<details><summary>Backtrace</summary>
<p>

```
<backtrace>
```

</p>
</details>

### PR DESCRIPTION
**Pull request by Flakebi**
*[View all comments](https://triagebot.infra.rust-lang.org/gh-comments/rust-lang/rust/pull/149624)*

Targets that set `requires_lto = true` were not actually using lto when compiling with cargo by default. They needed an extra `lto = true` in `Cargo.toml` to work.

Fix this by letting lto take precedence over the `embed_bitcode` flag when lto is required by a target.

If both these flags would be supplied by the user, an error is generated. However, this did not happen when lto was requested by the target instead of the user.

Fixes rust-lang/rust#148514
Tracking issue: rust-lang/rust#135024

### CODE REVIEW

**Review by khanbilal732 — APPROVED** [review]

**Comment by jieyouxu** [comment]
> The CI/tidy complain seems like a false-positive, the test uses `--target`, just not through `//@ compile-flags:`. Maybe that lint shouldn’t run on `run-make-cargo` tests? (I’m happy to make the change, just want to get confirmation that it’s ok to do that.)

Yes, I probably forgot to extend the tidy exception to `run-make-cargo` when I split the previous run-make test suite.

**Review by khanbilal732 — APPROVED** [review]

File: compiler/rustc_codegen_ssa/src/back/write.rs [hunk 1]
```diff
@@ -410,7 +410,7 @@ struct CompiledModules {
 
 fn need_bitcode_in_object(tcx: TyCtxt<'_>) -> bool {
     let sess = tcx.sess;
-    sess.opts.cg.embed_bitcode
+    (sess.lto() != config::Lto::No || sess.opts.cg.embed_bitcode)
```
Comment (Mark-Simulacrum) [inline compiler/rustc_codegen_ssa/src/back/write.rs]: Is No the right option here? If we're doing only thin-local LTO, I wouldn't expect bitcode to be needed in produced object files... I think? Not super familiar with this area.

Comment (bjorn3) [reply compiler/rustc_codegen_ssa/src/back/write.rs]: Indeed. thin-local LTO shouldn't emit bitcode.

Comment (Mark-Simulacrum) [reply compiler/rustc_codegen_ssa/src/back/write.rs]: Yeah, perf results seem to confirm this being not what we want :)

**Comment by bjorn3** [comment]
Would adding a `requires_lto` check at https://github.com/rust-lang/rust/blob/2caa8fe4163e04b2df1c80f8024c346597fdc9e7/compiler/rustc_codegen_ssa/src/back/write.rs#L142 instead work? Your current code would cause object files containing both machine code and bitcode to be generated rather than standalone bitcode files, even when only the latter is necessary.

**Comment by bjorn3** [comment]
Yeah, I think so. Probably should update the docs for it though. It still says that it is mostly useful for Emscripten when Emscripten hasn't needed that ever since we got wasm.

**Comment by Flakebi** [comment]
I was too early claiming that it works, I tested some more (compiling amdgpu-rs examples) and it broke some of them (somehow it ignored CARGO_BUILD_RUSTFLAGS for obj_is_bitcode and EmitObj::Bitcode completely or in parts).
With `EmitObj::ObjectCode(BitcodeSection::Full)` everything seems to work.
So, this is pretty much the change from before now, but checking `requires_lto` instead of `lto != No`.

**Review by bjorn3 — APPROVED** [review]

**Comment by Flakebi** [comment]
@bjorn3, is this fix something you could get merged?

Would it be worth to have another rust-timer run before? (I see this is currently labelled with perf-regression but that comes from an earlier version of this PR.)

**Comment by bjorn3** [comment]
I figured @Mark-Simulacrum would approve given that they are assigned. I strongly doubt the current state will cause a perf regression.

@bors r+

**Comment by Mark-Simulacrum** [comment]
For the future, I don't look at waiting-on-author PRs at all today, so I wouldn't have seen this. I'd recommend updating labels (e.g., `@rustbot ready`).

**Comment by Flakebi** [comment]
Ups, I didn’t see the label was pointing to me, sorry. Thanks for approving!
