### PR TITLE
Fix some aliasing issues in Vec

### LINKED ISSUE #70301: String::push_str invalidates interior references even when it does not reallocate
To my knowledge, the following code is intended to be legal:

```rust
fn main() {
    let mut buf = String::with_capacity(11);
    buf.push_str("hello");
    let hello: &str = unsafe { &*(buf.as_str() as *const _) }; // laundering the lifetime -- we take care that `buf` does not reallocate, so that's okay.
    buf.push_str(" world");
    println!("{}", hello);
}
```

However, Miri currently flags this as UB.

I believe this is #60847, but for `String`. Discovered while writing [this post](https://matklad.github.io/2020/03/22/fast-simple-rust-interner.html).

cc @RalfJung

### PR DESCRIPTION
**Pull request by RalfJung**
`Vec::extend` and `Vec::truncate` invalidated references into the vector even without reallocation, because they (implicitly) created a mutable reference covering the *entire* initialized part of the vector.

Fixes https://github.com/rust-lang/rust/issues/70301
I verified the fix by adding some new tests here that I ran in Miri.

### CODE REVIEW

File: src/liballoc/vec.rs [hunk 1]
```diff
@@ -2122,8 +2125,9 @@ where
         self.reserve(slice.len());
         unsafe {
             let len = self.len();
+            let dst_slice = slice::from_raw_parts_mut(self.as_mut_ptr().add(len), slice.len());
+            dst_slice.copy_from_slice(slice);
             self.set_len(len + slice.len());
-            self.get_unchecked_mut(len..).copy_from_slice(slice);
```
Comment (RalfJung) [inline src/liballoc/vec.rs]: Unfortunately there is no good way to grep for all places where the implicit `DerefMut` coercion is used, like here. I grepped for `get_unchecked_mut` and audited all of them, at least.

**Comment by RalfJung** [comment]
Let's re-try that with the latest changes. I think now I have all `&mut self` methods that are not expected to change the capacity covered in the test (and found and fixed issues in `remove` and `swap_remove`).

@bors try @rust-timer queue

**Comment by llogiq** [comment]
Would a lint for implicit `deref`(`_mut`) help?

**Comment by RalfJung** [comment]
Perf looks green, except for "syn" where some runs get faster by 3% and some slower by 2% -- but they have a `?` so I suppose those are pretty noisy anyway.

@llogiq hm, good idea. I am not sure, there might be tons of harmless implicit derefs in that file. The problematic ones are the ones for `Vec` itself.

But it might be worth a shot.

File: src/liballoc/vec.rs [hunk 2]
```diff
@@ -962,13 +963,15 @@ impl<T> Vec<T> {
     #[inline]
     #[stable(feature = "rust1", since = "1.0.0")]
     pub fn swap_remove(&mut self, index: usize) -> T {
+        let len = self.len();
+        assert!(index < len, "index out of bounds: the len is {} but the index is {}", len, index);
```
Comment (RalfJung) [inline src/liballoc/vec.rs:967]: Using formatting in the error [seems to cause performance issues](https://github.com/rust-lang/rust/pull/70573#issuecomment-607364101); let me know if you'd prefer an unformatted message.

File: src/liballoc/vec.rs (hunk 1 above)
Comment (elichai) [reply src/liballoc/vec.rs:2126]: Could you maybe print the backtrace in the `DerefMut` implementation and then run the tests and it will print what functions call `DerefMut`?

Comment (RalfJung) [reply src/liballoc/vec.rs:2126]: Since `DerefMut` is called for every mutable indexing operation (`&mut v[i]`), I expect that to show tons of stacktraces and not be very useful.

**Comment by Amanieu** [comment]
The changes look fine, and there doesn't seem to be any perf impact.

@bors r+

**Comment by RalfJung** [comment]
```
##[error]An error occurred while provisioning resources (Error Type: Disconnect).
```
@bors retry

**Comment by RalfJung** [comment]
> The changes look fine, and there doesn't seem to be any perf impact.

That perf measurement was from *before* I added the panic message.
I'll make this an assertion now and once https://github.com/rust-lang/rust/pull/70573 lands, make `swap_remove` match `remove`.
