### PR TITLE
Change `std::fs::copy` to use `copyfile` on MacOS and iOS

### LINKED ISSUE #58895: Use `copyfile` for `std::fs::copy` on MacOS
`copyfile` on MacOS is similar to `CopyFileEx` on Windows. It supports copying resource forks/alternate data streams, extended attributes, and file ACLs, none of which are copied by the current generic unix implementation.

<details>
<summary>copyfile man page</summary>
    p { margin-top: 0; margin-bottom: 0; } pre { margin-top: 0; margin-bottom: 0; } table { margin-top: 0; margin-bottom: 0; }  

COPYFILE(3) BSD Library Functions Manual COPYFILE(3)

**NAME**

**copyfile**, **fcopyfile**, **copyfile\_state\_alloc**, **copyfile\_state\_free**, **copyfile\_state\_get**, **copyfile\_state\_set** — copy a file

**LIBRARY**

Standard C Library (libc, −lc)

**SYNOPSIS**

**#include <copyfile.h>**

_int_

**copyfile**(_const char \*from_, _const char \*to_, _copyfile\_state\_t state_, _copyfile\_flags\_t flags_);

_int_

**fcopyfile**(_int from_, _int to_, _copyfile\_state\_t state_, _copyfile\_flags\_t flags_);

_copyfile\_state\_t_

**copyfile\_state\_alloc**(_void_);

_int_

**copyfile\_state\_free**(_copyfile\_state\_t state_);

_int_

**copyfile\_state\_get**(_copyfile\_state\_t state_, _uint32\_t flag_, _void \* dst_);

_int_

**copyfile\_state\_set**(_copyfile\_state\_t state_, _uint32\_t flag_, _const void \* src_);

_typedef int_

**(\*copyfile\_callback\_t)**(_int what_, _int stage_, _copyfile\_state\_t state_, _const char \* src_, _const char \* dst_, _void \* ctx_);

**DESCRIPTION**

These functions are used to copy a file’s data and/or metadata. (Metadata consists of permissions, extended attributes, access control lists, and so forth.)

The **copyfile\_state\_alloc**() function initializes a _copyfile\_state\_t_ object (which is an opaque data type). This object can be passed to **copyfile**() and **fcopyfile**(); **copyfile\_state\_get**() and **copyfile\_state\_set**() can be used to manipulate the state (see below). The **copyfile\_state\_free**() function is used to deallocate the object and its contents.

The **copyfile**() function can copy the named _from_ file to the named _to_ file; the **fcopyfile**() function does the same, but using the file descriptors of already-opened files. If the _state_ parameter is the return value from **copyfile\_state\_alloc**(), then **copyfile**() and **fcopyfile**() will use the information from the state object; if it is NULL, then both functions will work normally, but less control will be available to the caller. The _flags_ parameter controls which contents are copied:

COPYFILE\_ACL

Copy the source file’s access control lists.

COPYFILE\_STAT

Copy the source file’s POSIX information (mode, modification time, etc.).

COPYFILE\_XATTR

Copy the source file’s extended attributes.

COPYFILE\_DATA

Copy the source file’s data.

These values may be or’d together; several convenience macros are provided:

COPYFILE\_SECURITY

Copy the source file’s POSIX and ACL information; equivalent to (COPYFILE\_STAT|COPYFILE\_ACL).

COPYFILE\_METADATA

Copy the metadata; equivalent to (COPYFILE\_SECURITY|COPYFILE\_XATTR).

COPYFILE\_ALL

Copy the entire file; equivalent to (COPYFILE\_METADATA|COPYFILE\_DATA).

The **copyfile**() and **fcopyfile**() functions can also have their behavior modified by the following flags:

COPYFILE\_RECURSIVE

Causes **copyfile**() to recursively copy a hierarchy. This flag is not used by **fcopyfile**(); see below for more information.

COPYFILE\_CHECK

Return a bitmask (corresponding to the _flags_ argument) indicating which contents would be copied; no data are actually copied. (E.g., if _flags_ was set to COPYFILE\_CHECK|COPYFILE\_METADATA, and the _from_ file had extended attributes but no ACLs, the return value would be COPYFILE\_XATTR .)

COPYFILE\_PACK

Serialize the _from_ file. The _to_ file is an AppleDouble-format file.

COPYFILE\_UNPACK

Unserialize the _from_ file. The _from_ file is an AppleDouble-format file; the _to_ file will have the extended attributes, ACLs, resource fork, and FinderInfo data from the _to_ file, regardless of the _flags_ argument passed in.

COPYFILE\_EXCL

Fail if the _to_ file already exists. (This is only applicable for the **copyfile**() function.)

COPYFILE\_NOFOLLOW\_SRC

Do not follow the _from_ file, if it is a symbolic link. (This is only applicable for the **copyfile**() function.)

COPYFILE\_NOFOLLOW\_DST

Do not follow the _to_ file, if it is a symbolic link. (This is only applicable for the **copyfile**() function.)

COPYFILE\_MOVE

Unlink (using remove(3)) the _from_ file. (This is only applicable for the **copyfile**() function.) No error is returned if remove(3) fails. Note that remove(3) removes a symbolic link itself, not the target of the link.

COPYFILE\_UNLINK

Unlink the _to_ file before starting. (This is only applicable for the **copyfile**() function.)

COPYFILE\_CLONE\_FORCE

Clone the file instead. This is a force flag i.e. if cloning fails, an error is returned. This flag is equivalent to (COPYFILE\_EXCL | COPYFILE\_ACL | COPYFILE\_STAT | COPYFILE\_XATTR | COPYFILE\_DATA | COPYFILE\_NOFOLLOW\_SRC). Note that if cloning is successful, progress callbacks will not be invoked. Note also that there is no support for cloning directories: if a directory is provided as the source, an error will be returned. (This is only applicable for the **copyfile**() function.)

COPYFILE\_CLONE

Try to clone the file instead. This is a best try flag i.e. if cloning fails, fallback to copying the file. This flag is equivalent to (COPYFILE\_EXCL | COPYFILE\_ACL | COPYFILE\_STAT | COPYFILE\_XATTR | COPYFILE\_DATA | COPYFILE\_NOFOLLOW\_SRC). Note that if cloning is successful, progress callbacks will not be invoked. Note also that there is no support for cloning directories: if a directory is provided as the source and COPYFILE\_CLONE\_FORCE is not passed, this will instead copy the directory. Recursive copying however is supported, see below for more information. (This is only applicable for the **copyfile**() function.)

COPYFILE\_DATA\_SPARSE

Copy a file sparsely. This requires that the source and destination file systems support sparse files with hole sizes at least as large as their block sizes. This also requires that the source file is sparse, and for **fcopyfile**() the source file descriptor’s offset be a multiple of the minimum hole size. If COPYFILE\_DATA is also specified, this will fall back to a full copy if sparse copying cannot be performed for any reason; otherwise, an error is returned.

COPYFILE\_NOFOLLOW

This is a convenience macro, equivalent to (COPYFILE\_NOFOLLOW\_DST | COPYFILE\_NOFOLLOW\_SRC).

COPYFILE\_RUN\_IN\_PLACE

If the src file has quarantine information, add the QTN\_FLAG\_DO\_NOT\_TRANSLOCATE flag to the quarantine information of the dst file. This allows a bundle to run in place instead of being translocated.

The **copyfile\_state\_get**() and **copyfile\_state\_set**() functions can be used to manipulate the _copyfile\_state\_t_ object returned by **copyfile\_state\_alloc**(). In both functions, the _dst_ parameter’s type depends on the _flag_ parameter that is passed in.

COPYFILE\_STATE\_SRC\_FD  
COPYFILE\_STATE\_DST\_FD

Get or set the file descriptor associated with the source (or destination) file. If this has not been initialized yet, the value will be -2. The _dst_ (for **copyfile\_state\_get**()) and _src_ (for **copyfile\_state\_set**()) parameters are pointers to _int_.

COPYFILE\_STATE\_SRC\_FILENAME  
COPYFILE\_STATE\_DST\_FILENAME

Get or set the filename associated with the source (or destination) file. If it has not been initialized yet, the value will be NULL. For **copyfile\_state\_set**(), the _src_ parameter is a pointer to a C string (i.e., _char\* );_ **copyfile\_state\_set**() makes a private copy of this string. For **copyfile\_state\_get**() function, the _dst_ parameter is a pointer to a pointer to a C string (i.e., _char\*\* );_ the returned value is a pointer to the _state ’s_ copy, and must not be modified or released.

COPYFILE\_STATE\_STATUS\_CB

Get or set the callback status function (currently only used for recursive copies; see below for details). The _src_ parameter is a pointer to a function of type _copyfile\_callback\_t_ (see above).

COPYFILE\_STATE\_STATUS\_CTX

Get or set the context parameter for the status call-back function (see below for details). The _src_ parameter is a _void \*_.

COPYFILE\_STATE\_QUARANTINE

Get or set the quarantine information with the source file. The _src_ parameter is a pointer to an opaque object (type _void \*_ ).

COPYFILE\_STATE\_COPIED

Get the number of data bytes copied so far. (Only valid for **copyfile\_state\_get**(); see below for more details about callbacks.) If a COPYFILE\_CLONE or COPYFILE\_CLONE\_FORCE operation successfully cloned the requested objects, then this value will be 0. The _dst_ parameter is a pointer to _off\_t_ (type _off\_t \* )._

COPYFILE\_STATE\_XATTRNAME

Get the name of the extended attribute during a callback for COPYFILE\_COPY\_XATTR (see below for details). This field cannot be set, and may be NULL.

COPYFILE\_STATE\_WAS\_CLONED

True if a COPYFILE\_CLONE or COPYFILE\_CLONE\_FORCE operation successfully cloned the requested objects. The _dst_ parameter is a pointer to _bool_ (type _bool \* )._

**Recursive Copies**

When given the COPYFILE\_RECURSIVE flag, **copyfile**() (but not **fcopyfile**()) will use the fts(3) functions to recursively descend into the source file-system object. It then calls **copyfile**() on each of the entries it finds that way. If a call-back function is given (using **copyfile\_state\_set**() and COPYFILE\_STATE\_STATUS\_CB ), the call-back function will be called four times for each directory object, and twice for all other objects. (Each directory will be examined twice, once on entry -- before copying each of the objects contained in the directory -- and once on exit -- after copying each object contained in the directory, in order to perform some final cleanup.)

The call-back function will have one of the following values as the first argument, indicating what is being copied:

COPYFILE\_RECURSE\_FILE

The object being copied is a file (or, rather, something other than a directory).

COPYFILE\_RECURSE\_DIR

The object being copied is a directory, and is being entered. (That is, none of the filesystem objects contained within the directory have been copied yet.)

COPYFILE\_RECURSE\_DIR\_CLEANUP

The object being copied is a directory, and all of the objects contained have been copied. At this stage, the destination directory being copied will have any extra permissions that were added to allow the copying will be removed.

COPYFILE\_RECURSE\_ERROR

There was an error in processing an element of the source hierarchy; this happens when fts(3) returns an error or unknown file type. (Currently, the second argument to the call-back function will always be COPYFILE\_ERR in this case.)

The second argument to the call-back function will indicate the stage of the copy, and will be one of the following values:

COPYFILE\_START

Before copying has begun. The third parameter will be a newly-created _copyfile\_state\_t_ object with the call-back function and context pre-loaded.

COPYFILE\_FINISH

After copying has successfully finished.

COPYFILE\_ERR

Indicates an error has happened at some stage. If the first argument to the call-back function is COPYFILE\_RECURSE\_ERROR, then an error occurred while processing the source hierarchy; otherwise, it will indicate what type of object was being copied, and errno will be set to indicate the error.

The fourth and fifth parameters are the source and destination paths that are to be copied (or have been copied, or failed to copy, depending on the second argument).

The last argument to the call-back function will be the value set by COPYFILE\_STATE\_STATUS\_CTX, if any.

The call-back function is required to return one of the following values:

COPYFILE\_CONTINUE

The copy will continue as expected.

COPYFILE\_SKIP

This object will be skipped, and the next object will be processed. (Note that, when entering a directory. returning COPYFILE\_SKIP from the call-back function will prevent the contents of the directory from being copied.)

COPYFILE\_QUIT

The entire copy is aborted at this stage. Any filesystem objects created up to this point will remain. **copyfile**() will return -1, but errno will be unmodified.

The call-back function must always return one of the values listed above; if not, the results are undefined.

The call-back function will be called twice for each object (and an additional two times for directory cleanup); the first call will have a _stage_ parameter of COPYFILE\_START; the second time, that value will be either COPYFILE\_FINISH or COPYFILE\_ERR to indicate a successful completion, or an error during processing. In the event of an error, the errno value will be set appropriately.

Note that recursive cloning is also supported with the COPYFILE\_CLONE flag (but not the COPYFILE\_CLONE\_FORCE flag). A recursive clone operation invokes **copyfile**() with COPYFILE\_CLONE on every entry found in the source file-system object. Because **copyfile**() does not allow the cloning of directories, a recursive clone will instead copy any directory it finds (while cloning its contents). As symbolic links may point to directories, they are not followed during recursive clones even if the source is a symbolic link. Additionally, because the COPYFILE\_CLONE flag implies the COPYFILE\_EXCL flag, recursive clones require a nonexistent destination.

The COPYFILE\_PACK, COPYFILE\_UNPACK, COPYFILE\_MOVE, and COPYFILE\_UNLINK flags are not used during a recursive copy, and will result in an error being returned.

**Progress Callback**

In addition to the recursive callbacks described above, **copyfile**() and **fcopyfile**() will also use a callback to report data (e.g., COPYFILE\_DATA) progress. If given, the callback will be invoked on each write(2) call. The first argument to the callback function will be COPYFILE\_COPY\_DATA. The second argument will either be COPYFILE\_PROGRESS (indicating that the write was successful), or COPYFILE\_ERR (indicating that there was an error of some sort).

The amount of data bytes copied so far can be retrieved using **copyfile\_state\_get**(), with the COPYFILE\_STATE\_COPIED requestor (the argument type is a pointer to _off\_t )._

When copying extended attributes, the first argument to the callback function will be COPYFILE\_COPY\_XATTR. The other arguments will be as described for COPYFILE\_COPY\_DATA; the name of the extended attribute being copied may be retrieved using **copyfile\_state\_get**() and the parameter COPYFILE\_STATE\_XATTRNAME. When using COPYFILE\_PACK, the callback may be called with COPYFILE\_START for each of the extended attributes first, followed by COPYFILE\_PROGRESS before getting and packing the data for each individual attribute, and then COPYFILE\_FINISH when finished with each individual attribute. (That is, COPYFILE\_START may be called for all of the extended attributes, before the first callback with COPYFILE\_PROGRESS is invoked.) Any attribute skipped by returning COPYFILE\_SKIP from the COPYFILE\_START callback will not be placed into the packed output file.

The return value for the data callback must be one of

COPYFILE\_CONTINUE

The copy will continue as expected. (In the case of error, it will attempt to write the data again.)

COPYFILE\_SKIP

The data copy will be aborted, but without error.

COPYFILE\_QUIT

The data copy will be aborted; in the case of COPYFILE\_PROGRESS, errno will be set to ECANCELED.

While the _src_ and _dst_ parameters will be passed in, they may be NULL in the case of **fcopyfile**().

Note that progress callbacks are not invoked when a clone is requested (e.g. COPYFILE\_CLONE) unless the clone cannot be performed and a copy is performed instead.

**RETURN VALUES**

Except when given the COPYFILE\_CHECK flag, **copyfile**() and **fcopyfile**() return less than 0 on error, and 0 on success. All of the other functions return 0 on success, and less than 0 on error.

**WARNING**

Both **copyfile**() and **fcopyfile**() can copy symbolic links; there is a gap between when the source link is examined and the actual copy is started, and this can be a potential security risk, especially if the process has elevated privileges.

When performing a recursive copy, if the source hierarchy changes while the copy is occurring, the results are undefined.

**fcopyfile**() does not reset the seek position for either source or destination. This can result in the destination file being a different size than the source file.

**ERRORS**

**copyfile**() and **fcopyfile**() will fail if:

\[EINVAL\]

An invalid flag was passed in with COPYFILE\_RECURSIVE.

\[EINVAL\]

The _from_ or _to_ parameter to **copyfile**() was a NULL pointer.

\[EINVAL\]

The _from_ or _to_ parameter to **fcopyfile**() was a negative number.

\[ENOMEM\]

A memory allocation failed.

\[ENOTSUP\]

The source file was not a directory, symbolic link, or regular file.

\[ENOTSUP\]

COPYFILE\_CLONE\_FORCE was specified and file cloning is not supported.

\[ENOTSUP\]

COPYFILE\_DATA\_SPARSE was specified, sparse copying is not supported, and COPYFILE\_DATA was not specified.

\[ECANCELED\]

The copy was cancelled by callback.

\[EEXIST\]

The _to_ parameter to **copyfile**() already existed and was passed in with COPYFILE\_EXCL.

\[ENOENT\]

The _from_ parameter to **copyfile**() did not exist.

\[EACCES\]

Search permission is denied for a component of the path prefix for the _from_ or _to_ parameters.

\[EACCES\]

Write permission is denied for a component of the path prefix for the _to_ parameter.

In addition, both functions may set errno via an underlying library or system call.

**EXAMPLES**

/\* Initialize a state variable \*/  
copyfile\_state\_t s;  
s = copyfile\_state\_alloc();  
/\* Copy the data and extended attributes of one file to another \*/  
copyfile("/tmp/f1", "/tmp/f2", s, COPYFILE\_DATA | COPYFILE\_XATTR);  
/\* Convert a file to an AppleDouble file for serialization \*/  
copyfile("/tmp/f2", "/tmp/tmpfile", NULL, COPYFILE\_ALL | COPYFILE\_PACK);  
/\* Release the state variable \*/  
copyfile\_state\_free(s);  
/\* A more complex way to call copyfile() \*/  
s = copyfile\_state\_alloc();  
copyfile\_state\_set(s, COPYFILE\_STATE\_SRC\_FILENAME, "/tmp/foo");  
/\* One of src or dst must be set... rest can come from the state \*/  
copyfile(NULL, "/tmp/bar", s, COPYFILE\_ALL);  
/\* Now copy the same source file to another destination file \*/  
copyfile(NULL, "/tmp/car", s, COPYFILE\_ALL);  
copyfile\_state\_free(s);  
/\* Remove extended attributes from a file \*/  
copyfile("/dev/null", "/tmp/bar", NULL, COPYFILE\_XATTR);

**SEE ALSO**

listxattr(2), getxattr(2), setxattr(2), acl(3)

**BUGS**

Both **copyfile**() functions lack a way to set the input or output block size.

Recursive copies do not honor hard links.

**HISTORY**

The **copyfile**() API was introduced in Mac OS X 10.5.

BSD August 30, 2017 BSD

* * *
</details>

### PR DESCRIPTION
**Pull request by ebarnard**
`copyfile` on MacOS is similar to `CopyFileEx` on Windows. It supports copying resource forks, extended attributes, and file ACLs, none of which are copied by the current generic unix implementation.

The API is available from MacOS 10.7 and iOS 4.3 (and possibly earlier but I haven't checked).

Closes #58895.

### CODE REVIEW

File: src/libstd/sys/unix/fs.rs [hunk 1]
```diff
@@ -937,3 +940,63 @@ pub fn copy(from: &Path, to: &Path) -> io::Result<u64> {
...
+        fn copyfile_state_alloc() -> copyfile_state_t;
+        fn copyfile_state_free(state: copyfile_state_t) -> libc::c_int;
+        fn copyfile_state_get(
+            state: copyfile_state_t,
+            flag: u32,
+            dst: *mut libc::c_void,
+        ) -> libc::c_int;
+    }
+
+    unsafe {
```
Comment (Centril) [inline src/libstd/sys/unix/fs.rs]: A comment justifying the soundness of `unsafe { .. }` would be nice.

File: src/libstd/sys/unix/fs.rs [hunk 2]
```diff
@@ -937,3 +940,63 @@ pub fn copy(from: &Path, to: &Path) -> io::Result<u64> {
...
+        let mut bytes_copied: libc::off_t = 0;
+        cvt(copyfile_state_get(
+            state,
+            COPYFILE_STATE_COPIED,
+            &mut bytes_copied as *mut libc::off_t as *mut libc::c_void,
+        ))?;
+
+        // `copyfile_state_free` returns -1 if the `to` or `from` files cannot
+        // be closed but we do not consider this an error
+        copyfile_state_free(state);
```
Comment (alex) [inline src/libstd/sys/unix/fs.rs]: It looks like `state` will be leaked if either `copyfile` or `copyfile_state_get` error.

Comment (ebarnard) [reply src/libstd/sys/unix/fs.rs]: Oh yeah. The [source](https://opensource.apple.com/source/copyfile/copyfile-146.200.3/copyfile.c.auto.html) (line 1248) makes it look deceptively as though state is freed on error.

File: src/libstd/sys/unix/fs.rs (hunk 1 above)
Comment (ebarnard) [reply src/libstd/sys/unix/fs.rs]: I've split up the unsafe block and added comments where there are invariants to uphold.

**Comment by sfackler** [comment]
I can't remember if we support 10.6 or not - @alexcrichton do you know? If so, we'll need to look up the symbols dynamically.

**Comment by alexcrichton** [comment]
Officially, no, we only support 10.7+.

Anecdotally though we support 10.6 with some build tweaks to libstd which have historically been used a bit. I think though that users of the 10.6 support have all moved beyond 10.6 themselves, so landing this should be fine in that regard.

**Comment by ebarnard** [comment]
It looks like the copyfile.h header is included in the MacOS 10.5 SDK - so this PR shouldn't break anything.
