### PR TITLE
When moving out of a for loop head, suggest borrowing it

### LINKED ISSUE #25534: Use of moved value error in the `for` iterator could give a hint about borrowing
``` rust
fn main() {
    let a = vec![1, 2, 3];
    for i in a {
        for j in a {
            println!("{} * {} = {}", i, j, i * j);
        }
    }
}
```

currently gives:

```
<anon>:4:18: 4:19 error: use of moved value: `a`
<anon>:4         for j in a {
                          ^
note: in expansion of for loop expansion
<anon>:4:9: 6:10 note: expansion site
note: in expansion of for loop expansion
<anon>:3:5: 7:6 note: expansion site
<anon>:3:14: 3:15 note: `a` moved here because it has type `collections::vec::Vec<i32>`, which is non-copyable
<anon>:3     for i in a {
                      ^
note: in expansion of for loop expansion
<anon>:3:5: 7:6 note: expansion site
error: aborting due to previous error
```

Of course, we all know that `for i in &a` etc. is correct here, but this is not very obvious to beginners. We may want to give a contextual hint for "use of moved value" errors among others---probably as a second note following the original move.

(Feel free to make this a metabug if there are other such examples.)

### PR DESCRIPTION
**Pull request by estebank**
When encountering code like the following, suggest borrowing the for loop
head to avoid moving it into the for loop pattern:

```
fn main() {
    let a = vec![1, 2, 3];
    for i in &a {
        for j in a {
            println!("{} * {} = {}", i, j, i * j);
        }
    }
}
```

Fix #25534.

### CODE REVIEW

File: src/librustc_borrowck/borrowck/mod.rs [hunk 1]
```diff
@@ -746,6 +747,19 @@ impl<'a, 'tcx> BorrowckCtxt<'a, 'tcx> {
                 },
                 moved_lp.ty));
         }
+        if let (Some(CompilerDesugaringKind::ForLoop), Ok(snippet)) = (
```
Comment (estebank) [inline src/librustc_borrowck/borrowck/mod.rs]: We might want to use a separate `CompilerDesugaringKind` variant to differentiate in errors, something along the lines of `ForLoopHead`, or something, or modify `ForLoop` to carry information on wether the source is completely synthetic or just moving around code that the user has written.

File: src/librustc_borrowck/borrowck/mod.rs [hunk 2]
```diff
@@ -746,6 +747,19 @@ impl<'a, 'tcx> BorrowckCtxt<'a, 'tcx> {
...
+            move_span.compiler_desugaring_kind(),
+            self.tcx.sess.source_map().span_to_snippet(move_span),
```
Comment (petrochenkov) [inline src/librustc_borrowck/borrowck/mod.rs]: Nit: not sure whether `span_to_snippet` is expensive or not, but if it is, them it may make sense to nest `if let`s to avoid pessimizing.

**Comment by estebank** [comment]
@bors r=petrochenkov

I'll deal with replicating this output in nll mode later.
