### PR TITLE
Continue folding in query normalizer on weak aliases

### LINKED ISSUE #112731: ICE: `debuginfo: unexpected type in type_di_node()`
### Code

`rustc  -Cdebuginfo=2 --crate-type lib`

```Rust
#![feature(type_alias_impl_trait)]

use std::fmt::Debug;

type Foo = impl Debug;

static FOO1: Foo = 22_u32;
```

### Meta

`rustc --version --verbose`:
```
rustc 1.72.0-nightly (1d7d82472 2023-06-17)
binary: rustc
commit-hash: 1d7d82472617a4a0fea59c7e239c8a48c8ac5c34
commit-date: 2023-06-17
host: x86_64-unknown-linux-gnu
release: 1.72.0-nightly
LLVM version: 16.0.5
```

### Error output

```
<output>
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
error: internal compiler error: compiler/rustc_codegen_llvm/src/debuginfo/metadata.rs:462:14: debuginfo: unexpected type in type_di_node(): Foo

thread 'rustc' panicked at 'Box<dyn Any>', /rustc/1d7d82472617a4a0fea59c7e239c8a48c8ac5c34/compiler/rustc_errors/src/lib.rs:1650:9
stack backtrace:
   0:     0x7f162fd68821 - std::backtrace_rs::backtrace::libunwind::trace::h6e3584f9aa263648
                               at /rustc/1d7d82472617a4a0fea59c7e239c8a48c8ac5c34/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x7f162fd68821 - std::backtrace_rs::backtrace::trace_unsynchronized::h7cba45a2d56b3723
                               at /rustc/1d7d82472617a4a0fea59c7e239c8a48c8ac5c34/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7f162fd68821 - std::sys_common::backtrace::_print_fmt::hb3e5f2b800058c47
                               at /rustc/1d7d82472617a4a0fea59c7e239c8a48c8ac5c34/library/std/src/sys_common/backtrace.rs:65:5
   3:     0x7f162fd68821 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hc6fcd56f05592786
                               at /rustc/1d7d82472617a4a0fea59c7e239c8a48c8ac5c34/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x7f162fdc9b2f - core::fmt::rt::Argument::fmt::hb8b6762d96a2930c
                               at /rustc/1d7d82472617a4a0fea59c7e239c8a48c8ac5c34/library/core/src/fmt/rt.rs:138:9
   5:     0x7f162fdc9b2f - core::fmt::write::ha824b1be2c398991
                               at /rustc/1d7d82472617a4a0fea59c7e239c8a48c8ac5c34/library/core/src/fmt/mod.rs:1094:21
   6:     0x7f162fd5ba31 - std::io::Write::write_fmt::h4bbc557c498e18be
                               at /rustc/1d7d82472617a4a0fea59c7e239c8a48c8ac5c34/library/std/src/io/mod.rs:1713:15
   7:     0x7f162fd68635 - std::sys_common::backtrace::_print::hb6a2afc924d1ac9a
                               at /rustc/1d7d82472617a4a0fea59c7e239c8a48c8ac5c34/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x7f162fd68635 - std::sys_common::backtrace::print::h39a60e9b1dd2b988
                               at /rustc/1d7d82472617a4a0fea59c7e239c8a48c8ac5c34/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x7f162fd6b317 - std::panicking::default_hook::{{closure}}::hf1636ea70b88baf6
  10:     0x7f162fd6b104 - std::panicking::default_hook::h25db0e741a15cb6c
                               at /rustc/1d7d82472617a4a0fea59c7e239c8a48c8ac5c34/library/std/src/panicking.rs:288:9
  11:     0x7f1632fc105b - <rustc_driver_impl[9fb98086b5dc1b8]::install_ice_hook::{closure#0} as core[5a025f5ac19a3684]::ops::function::FnOnce<(&core[5a025f5ac19a3684]::panic::panic_info::PanicInfo,)>>::call_once::{shim:vtable#0}
  12:     0x7f162fd6ba5d - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::hb67fc0de76dc4685
                               at /rustc/1d7d82472617a4a0fea59c7e239c8a48c8ac5c34/library/alloc/src/boxed.rs:1999:9
  13:     0x7f162fd6ba5d - std::panicking::rust_panic_with_hook::h6c10fd1f40066f99
                               at /rustc/1d7d82472617a4a0fea59c7e239c8a48c8ac5c34/library/std/src/panicking.rs:709:13
  14:     0x7f16334c21b1 - std[5e6a7ab4ec51e2fa]::panicking::begin_panic::<rustc_errors[db6e693a4d78f721]::ExplicitBug>::{closure#0}
  15:     0x7f16334c0e06 - std[5e6a7ab4ec51e2fa]::sys_common::backtrace::__rust_end_short_backtrace::<std[5e6a7ab4ec51e2fa]::panicking::begin_panic<rustc_errors[db6e693a4d78f721]::ExplicitBug>::{closure#0}, !>
  16:     0x7f16335572a6 - std[5e6a7ab4ec51e2fa]::panicking::begin_panic::<rustc_errors[db6e693a4d78f721]::ExplicitBug>
  17:     0x7f16334bdbd4 - <rustc_errors[db6e693a4d78f721]::HandlerInner>::bug::<alloc[31842ca5441cdb56]::string::String>
  18:     0x7f16334bda56 - <rustc_errors[db6e693a4d78f721]::Handler>::bug::<alloc[31842ca5441cdb56]::string::String>
  19:     0x7f163351142c - rustc_middle[c2d4873b804b2cf0]::util::bug::opt_span_bug_fmt::<rustc_span[7bbc48c8a570ee79]::span_encoding::Span>::{closure#0}
  20:     0x7f163350e2ca - rustc_middle[c2d4873b804b2cf0]::ty::context::tls::with_opt::<rustc_middle[c2d4873b804b2cf0]::util::bug::opt_span_bug_fmt<rustc_span[7bbc48c8a570ee79]::span_encoding::Span>::{closure#0}, !>::{closure#0}
  21:     0x7f163350e29a - rustc_middle[c2d4873b804b2cf0]::ty::context::tls::with_context_opt::<rustc_middle[c2d4873b804b2cf0]::ty::context::tls::with_opt<rustc_middle[c2d4873b804b2cf0]::util::bug::opt_span_bug_fmt<rustc_span[7bbc48c8a570ee79]::span_encoding::Span>::{closure#0}, !>::{closure#0}, !>
  22:     0x7f163124f89d - rustc_middle[c2d4873b804b2cf0]::util::bug::bug_fmt
  23:     0x7f16314d0a24 - rustc_codegen_llvm[69782307a30a28b1]::debuginfo::metadata::type_di_node
  24:     0x7f1631c240ba - rustc_codegen_llvm[69782307a30a28b1]::debuginfo::metadata::build_global_var_di_node
  25:     0x7f1631c236e7 - <rustc_codegen_llvm[69782307a30a28b1]::context::CodegenCx as rustc_codegen_ssa[7cf51ec1c1d8e70f]::traits::statics::StaticMethods>::codegen_static
  26:     0x7f1631c0c8bc - rustc_codegen_llvm[69782307a30a28b1]::base::compile_codegen_unit::module_codegen
  27:     0x7f1631c0a109 - rustc_codegen_llvm[69782307a30a28b1]::base::compile_codegen_unit
  28:     0x7f1631c07901 - rustc_codegen_ssa[7cf51ec1c1d8e70f]::base::codegen_crate::<rustc_codegen_llvm[69782307a30a28b1]::LlvmCodegenBackend>
  29:     0x7f1631c0720f - <rustc_codegen_llvm[69782307a30a28b1]::LlvmCodegenBackend as rustc_codegen_ssa[7cf51ec1c1d8e70f]::traits::backend::CodegenBackend>::codegen_crate
  30:     0x7f16324fc0a2 - <rustc_session[5d8f1134011332b9]::session::Session>::time::<alloc[31842ca5441cdb56]::boxed::Box<dyn core[5a025f5ac19a3684]::any::Any>, rustc_interface[75da62af7afad68]::passes::start_codegen::{closure#0}>
  31:     0x7f16324fbc1b - rustc_interface[75da62af7afad68]::passes::start_codegen
  32:     0x7f16324f696d - <rustc_middle[c2d4873b804b2cf0]::ty::context::GlobalCtxt>::enter::<<rustc_interface[75da62af7afad68]::queries::Queries>::ongoing_codegen::{closure#0}::{closure#0}, core[5a025f5ac19a3684]::result::Result<alloc[31842ca5441cdb56]::boxed::Box<dyn core[5a025f5ac19a3684]::any::Any>, rustc_span[7bbc48c8a570ee79]::ErrorGuaranteed>>
  33:     0x7f16324f50dd - <rustc_interface[75da62af7afad68]::queries::Queries>::ongoing_codegen
  34:     0x7f16324f3c3a - rustc_span[7bbc48c8a570ee79]::set_source_map::<core[5a025f5ac19a3684]::result::Result<(), rustc_span[7bbc48c8a570ee79]::ErrorGuaranteed>, rustc_interface[75da62af7afad68]::interface::run_compiler<core[5a025f5ac19a3684]::result::Result<(), rustc_span[7bbc48c8a570ee79]::ErrorGuaranteed>, rustc_driver_impl[9fb98086b5dc1b8]::run_compiler::{closure#1}>::{closure#0}::{closure#0}>
  35:     0x7f16324ec3f9 - <scoped_tls[5be461245172b0fd]::ScopedKey<rustc_span[7bbc48c8a570ee79]::SessionGlobals>>::set::<rustc_interface[75da62af7afad68]::interface::run_compiler<core[5a025f5ac19a3684]::result::Result<(), rustc_span[7bbc48c8a570ee79]::ErrorGuaranteed>, rustc_driver_impl[9fb98086b5dc1b8]::run_compiler::{closure#1}>::{closure#0}, core[5a025f5ac19a3684]::result::Result<(), rustc_span[7bbc48c8a570ee79]::ErrorGuaranteed>>
  36:     0x7f16324eb9f6 - std[5e6a7ab4ec51e2fa]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[75da62af7afad68]::util::run_in_thread_pool_with_globals<rustc_interface[75da62af7afad68]::interface::run_compiler<core[5a025f5ac19a3684]::result::Result<(), rustc_span[7bbc48c8a570ee79]::ErrorGuaranteed>, rustc_driver_impl[9fb98086b5dc1b8]::run_compiler::{closure#1}>::{closure#0}, core[5a025f5ac19a3684]::result::Result<(), rustc_span[7bbc48c8a570ee79]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[5a025f5ac19a3684]::result::Result<(), rustc_span[7bbc48c8a570ee79]::ErrorGuaranteed>>
  37:     0x7f16324eb7a5 - <<std[5e6a7ab4ec51e2fa]::thread::Builder>::spawn_unchecked_<rustc_interface[75da62af7afad68]::util::run_in_thread_pool_with_globals<rustc_interface[75da62af7afad68]::interface::run_compiler<core[5a025f5ac19a3684]::result::Result<(), rustc_span[7bbc48c8a570ee79]::ErrorGuaranteed>, rustc_driver_impl[9fb98086b5dc1b8]::run_compiler::{closure#1}>::{closure#0}, core[5a025f5ac19a3684]::result::Result<(), rustc_span[7bbc48c8a570ee79]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[5a025f5ac19a3684]::result::Result<(), rustc_span[7bbc48c8a570ee79]::ErrorGuaranteed>>::{closure#1} as core[5a025f5ac19a3684]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  38:     0x7f162fd75f55 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h3b57fe0fe8253eda
                               at /rustc/1d7d82472617a4a0fea59c7e239c8a48c8ac5c34/library/alloc/src/boxed.rs:1985:9
  39:     0x7f162fd75f55 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h6eac2c7c988070fa
                               at /rustc/1d7d82472617a4a0fea59c7e239c8a48c8ac5c34/library/alloc/src/boxed.rs:1985:9
  40:     0x7f162fd75f55 - std::sys::unix::thread::Thread::new::thread_start::h8d73f1104f34aa7b
                               at /rustc/1d7d82472617a4a0fea59c7e239c8a48c8ac5c34/library/std/src/sys/unix/thread.rs:108:17
  41:     0x7f162fb0f44b - <unknown>
  42:     0x7f162fb92e40 - <unknown>
  43:                0x0 - <unknown>

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.72.0-nightly (1d7d82472 2023-06-17) running on x86_64-unknown-linux-gnu

note: compiler flags: --crate-type lib -C debuginfo=2

query stack during panic:
end of query stack
error: aborting due to previous error
```

</p>
</details>

### LINKED ISSUE #112752: ICE: `debuginfo: Trying to create type name for unexpected type: T`
### Code
`rustc --crate-type lib -Cdebuginfo=2`
```Rust
#![feature(type_alias_impl_trait)]

type Debuggable = impl core::fmt::Debug;

static mut TEST: Option<Debuggable> = None;

fn foo() -> Debuggable {
    0u32
}
```

### Meta

`rustc --version --verbose`:
```
rustc 1.72.0-nightly (e1c29d137 2023-06-17)
binary: rustc
commit-hash: e1c29d137dd779dcfce447d8d149ee6b8e9bdf78
commit-date: 2023-06-17
host: x86_64-unknown-linux-gnu
release: 1.72.0-nightly
LLVM version: 16.0.5
```

### Error output

```

```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
error: internal compiler error: compiler/rustc_codegen_ssa/src/debuginfo/type_names.rs:426:13: debuginfo: Trying to create type name for unexpected type: Debuggable

thread 'rustc' panicked at 'Box<dyn Any>', /rustc/e1c29d137dd779dcfce447d8d149ee6b8e9bdf78/compiler/rustc_errors/src/lib.rs:1650:9
stack backtrace:
   0:     0x7fae87d76821 - std::backtrace_rs::backtrace::libunwind::trace::h9f7459fe33aa0e5d
                               at /rustc/e1c29d137dd779dcfce447d8d149ee6b8e9bdf78/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x7fae87d76821 - std::backtrace_rs::backtrace::trace_unsynchronized::hd1b84c098fa4a123
                               at /rustc/e1c29d137dd779dcfce447d8d149ee6b8e9bdf78/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7fae87d76821 - std::sys_common::backtrace::_print_fmt::hcbe1c0d5b9ccfafc
                               at /rustc/e1c29d137dd779dcfce447d8d149ee6b8e9bdf78/library/std/src/sys_common/backtrace.rs:65:5
   3:     0x7fae87d76821 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h2397bfed2776bcc3
                               at /rustc/e1c29d137dd779dcfce447d8d149ee6b8e9bdf78/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x7fae87dd7b2f - core::fmt::rt::Argument::fmt::h9d127d2c0c6d41be
                               at /rustc/e1c29d137dd779dcfce447d8d149ee6b8e9bdf78/library/core/src/fmt/rt.rs:138:9
   5:     0x7fae87dd7b2f - core::fmt::write::h7eb0e863d034bdac
                               at /rustc/e1c29d137dd779dcfce447d8d149ee6b8e9bdf78/library/core/src/fmt/mod.rs:1094:21
   6:     0x7fae87d69a31 - std::io::Write::write_fmt::h0074615eecf66aee
                               at /rustc/e1c29d137dd779dcfce447d8d149ee6b8e9bdf78/library/std/src/io/mod.rs:1713:15
   7:     0x7fae87d76635 - std::sys_common::backtrace::_print::h6be5909ad9481635
                               at /rustc/e1c29d137dd779dcfce447d8d149ee6b8e9bdf78/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x7fae87d76635 - std::sys_common::backtrace::print::h797301c61028791e
                               at /rustc/e1c29d137dd779dcfce447d8d149ee6b8e9bdf78/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x7fae87d79317 - std::panicking::default_hook::{{closure}}::hca65d86a9a46dc15
  10:     0x7fae87d79104 - std::panicking::default_hook::he1fa9c1b7e1bd558
                               at /rustc/e1c29d137dd779dcfce447d8d149ee6b8e9bdf78/library/std/src/panicking.rs:288:9
  11:     0x7fae86baab0b - <rustc_driver_impl[279ee92520ace0a6]::install_ice_hook::{closure#0} as core[b4980bc44de3a097]::ops::function::FnOnce<(&core[b4980bc44de3a097]::panic::panic_info::PanicInfo,)>>::call_once::{shim:vtable#0}
  12:     0x7fae87d79a5d - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h34cd7947431e4c22
                               at /rustc/e1c29d137dd779dcfce447d8d149ee6b8e9bdf78/library/alloc/src/boxed.rs:1999:9
  13:     0x7fae87d79a5d - std::panicking::rust_panic_with_hook::h65e494058e274a39
                               at /rustc/e1c29d137dd779dcfce447d8d149ee6b8e9bdf78/library/std/src/panicking.rs:709:13
  14:     0x7fae870ac051 - std[6ed0834f1ef78f33]::panicking::begin_panic::<rustc_errors[4119f672f666809f]::ExplicitBug>::{closure#0}
  15:     0x7fae870aaca6 - std[6ed0834f1ef78f33]::sys_common::backtrace::__rust_end_short_backtrace::<std[6ed0834f1ef78f33]::panicking::begin_panic<rustc_errors[4119f672f666809f]::ExplicitBug>::{closure#0}, !>
  16:     0x7fae8713fa56 - std[6ed0834f1ef78f33]::panicking::begin_panic::<rustc_errors[4119f672f666809f]::ExplicitBug>
  17:     0x7fae870a7a74 - <rustc_errors[4119f672f666809f]::HandlerInner>::bug::<alloc[92368cc95fb81602]::string::String>
  18:     0x7fae870a78f6 - <rustc_errors[4119f672f666809f]::Handler>::bug::<alloc[92368cc95fb81602]::string::String>
  19:     0x7fae870fae8c - rustc_middle[f4daec6bf88206fd]::util::bug::opt_span_bug_fmt::<rustc_span[d32f61a769cb4fd2]::span_encoding::Span>::{closure#0}
  20:     0x7fae870f7d2a - rustc_middle[f4daec6bf88206fd]::ty::context::tls::with_opt::<rustc_middle[f4daec6bf88206fd]::util::bug::opt_span_bug_fmt<rustc_span[d32f61a769cb4fd2]::span_encoding::Span>::{closure#0}, !>::{closure#0}
  21:     0x7fae870f7cfa - rustc_middle[f4daec6bf88206fd]::ty::context::tls::with_context_opt::<rustc_middle[f4daec6bf88206fd]::ty::context::tls::with_opt<rustc_middle[f4daec6bf88206fd]::util::bug::opt_span_bug_fmt<rustc_span[d32f61a769cb4fd2]::span_encoding::Span>::{closure#0}, !>::{closure#0}, !>
  22:     0x7fae84ec768d - rustc_middle[f4daec6bf88206fd]::util::bug::bug_fmt
  23:     0x7fae84d7a9e7 - rustc_codegen_ssa[6aedebcb74c6a4d0]::debuginfo::type_names::push_debuginfo_type_name
  24:     0x7fae84d7e1ca - rustc_codegen_ssa[6aedebcb74c6a4d0]::debuginfo::type_names::push_generic_params_internal
  25:     0x7fae851262d5 - rustc_codegen_ssa[6aedebcb74c6a4d0]::debuginfo::type_names::compute_debuginfo_type_name
  26:     0x7fae8512606e - rustc_codegen_llvm[5855ca1d4f8b4fd6]::debuginfo::metadata::enums::native::build_enum_type_di_node
  27:     0x7fae8512586c - rustc_codegen_llvm[5855ca1d4f8b4fd6]::debuginfo::metadata::enums::build_enum_type_di_node
  28:     0x7fae8511b39b - rustc_codegen_llvm[5855ca1d4f8b4fd6]::debuginfo::metadata::type_di_node
  29:     0x7fae857a8dea - rustc_codegen_llvm[5855ca1d4f8b4fd6]::debuginfo::metadata::build_global_var_di_node
  30:     0x7fae857a8417 - <rustc_codegen_llvm[5855ca1d4f8b4fd6]::context::CodegenCx as rustc_codegen_ssa[6aedebcb74c6a4d0]::traits::statics::StaticMethods>::codegen_static
  31:     0x7fae8579157c - rustc_codegen_llvm[5855ca1d4f8b4fd6]::base::compile_codegen_unit::module_codegen
  32:     0x7fae8578edc9 - rustc_codegen_llvm[5855ca1d4f8b4fd6]::base::compile_codegen_unit
  33:     0x7fae8578c5c1 - rustc_codegen_ssa[6aedebcb74c6a4d0]::base::codegen_crate::<rustc_codegen_llvm[5855ca1d4f8b4fd6]::LlvmCodegenBackend>
  34:     0x7fae8578becf - <rustc_codegen_llvm[5855ca1d4f8b4fd6]::LlvmCodegenBackend as rustc_codegen_ssa[6aedebcb74c6a4d0]::traits::backend::CodegenBackend>::codegen_crate
  35:     0x7fae860da552 - <rustc_session[b39823bffb756516]::session::Session>::time::<alloc[92368cc95fb81602]::boxed::Box<dyn core[b4980bc44de3a097]::any::Any>, rustc_interface[f42202c9eb53a071]::passes::start_codegen::{closure#0}>
  36:     0x7fae860da0cb - rustc_interface[f42202c9eb53a071]::passes::start_codegen
  37:     0x7fae860d4e1d - <rustc_middle[f4daec6bf88206fd]::ty::context::GlobalCtxt>::enter::<<rustc_interface[f42202c9eb53a071]::queries::Queries>::ongoing_codegen::{closure#0}::{closure#0}, core[b4980bc44de3a097]::result::Result<alloc[92368cc95fb81602]::boxed::Box<dyn core[b4980bc44de3a097]::any::Any>, rustc_span[d32f61a769cb4fd2]::ErrorGuaranteed>>
  38:     0x7fae860d404d - <rustc_interface[f42202c9eb53a071]::queries::Queries>::ongoing_codegen
  39:     0x7fae860d3170 - <rustc_interface[f42202c9eb53a071]::interface::Compiler>::enter::<rustc_driver_impl[279ee92520ace0a6]::run_compiler::{closure#1}::{closure#2}, core[b4980bc44de3a097]::result::Result<core[b4980bc44de3a097]::option::Option<rustc_interface[f42202c9eb53a071]::queries::Linker>, rustc_span[d32f61a769cb4fd2]::ErrorGuaranteed>>
  40:     0x7fae860d0736 - std[6ed0834f1ef78f33]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[f42202c9eb53a071]::util::run_in_thread_pool_with_globals<rustc_interface[f42202c9eb53a071]::interface::run_compiler<core[b4980bc44de3a097]::result::Result<(), rustc_span[d32f61a769cb4fd2]::ErrorGuaranteed>, rustc_driver_impl[279ee92520ace0a6]::run_compiler::{closure#1}>::{closure#0}, core[b4980bc44de3a097]::result::Result<(), rustc_span[d32f61a769cb4fd2]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[b4980bc44de3a097]::result::Result<(), rustc_span[d32f61a769cb4fd2]::ErrorGuaranteed>>
  41:     0x7fae860cfef5 - <<std[6ed0834f1ef78f33]::thread::Builder>::spawn_unchecked_<rustc_interface[f42202c9eb53a071]::util::run_in_thread_pool_with_globals<rustc_interface[f42202c9eb53a071]::interface::run_compiler<core[b4980bc44de3a097]::result::Result<(), rustc_span[d32f61a769cb4fd2]::ErrorGuaranteed>, rustc_driver_impl[279ee92520ace0a6]::run_compiler::{closure#1}>::{closure#0}, core[b4980bc44de3a097]::result::Result<(), rustc_span[d32f61a769cb4fd2]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[b4980bc44de3a097]::result::Result<(), rustc_span[d32f61a769cb4fd2]::ErrorGuaranteed>>::{closure#1} as core[b4980bc44de3a097]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  42:     0x7fae87d83f55 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::heee60d66f5fcaf5d
                               at /rustc/e1c29d137dd779dcfce447d8d149ee6b8e9bdf78/library/alloc/src/boxed.rs:1985:9
  43:     0x7fae87d83f55 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hd90650fb45aa2fdd
                               at /rustc/e1c29d137dd779dcfce447d8d149ee6b8e9bdf78/library/alloc/src/boxed.rs:1985:9
  44:     0x7fae87d83f55 - std::sys::unix::thread::Thread::new::thread_start::h328d7dcc74e3b33a
                               at /rustc/e1c29d137dd779dcfce447d8d149ee6b8e9bdf78/library/std/src/sys/unix/thread.rs:108:17
  45:     0x7fae8389d44b - <unknown>
  46:     0x7fae83920e40 - <unknown>
  47:                0x0 - <unknown>

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.72.0-nightly (e1c29d137 2023-06-17) running on x86_64-unknown-linux-gnu

note: compiler flags: --crate-type lib -C debuginfo=2

query stack during panic:
end of query stack
error: aborting due to previous error; 3 warnings emitted
```

</p>
</details>

### LINKED ISSUE #112776: ICE: debuginfo: Trying to create type name for unexpected type
### Code

```Rust
[project.tar.gz](https://github.com/rust-lang/rust/files/11782528/project.tar.gz)
```

### Meta

`rustc +nightly --version --verbose`:
```
rustc 1.72.0-nightly (3b2073f07 2023-06-17)
binary: rustc
commit-hash: 3b2073f0762cff4d3d625bb10017e0ce4e7abe50
commit-date: 2023-06-17
host: x86_64-unknown-linux-gnu
release: 1.72.0-nightly
LLVM version: 16.0.5
```

### Error output

```
error: internal compiler error: compiler/rustc_codegen_ssa/src/debuginfo/type_names.rs:426:13: debuginfo: Trying to create type name for unexpected type: app::__rtic_internal_ledtask_F

thread 'rustc' panicked at 'Box<dyn Any>', /rustc/3b2073f0762cff4d3d625bb10017e0ce4e7abe50/compiler/rustc_errors/src/lib.rs:1650:9
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
stack backtrace:
   0:     0x7ff879d67e11 - std::backtrace_rs::backtrace::libunwind::trace::hd102c46c16771587
                               at /rustc/3b2073f0762cff4d3d625bb10017e0ce4e7abe50/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x7ff879d67e11 - std::backtrace_rs::backtrace::trace_unsynchronized::h6545cf7d6ed27551
                               at /rustc/3b2073f0762cff4d3d625bb10017e0ce4e7abe50/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7ff879d67e11 - std::sys_common::backtrace::_print_fmt::h258fac35947dded0
                               at /rustc/3b2073f0762cff4d3d625bb10017e0ce4e7abe50/library/std/src/sys_common/backtrace.rs:65:5
   3:     0x7ff879d67e11 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hf070a48cb28a24d1
                               at /rustc/3b2073f0762cff4d3d625bb10017e0ce4e7abe50/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x7ff879dc94bf - core::fmt::rt::Argument::fmt::h0a093c27aabe85c6
                               at /rustc/3b2073f0762cff4d3d625bb10017e0ce4e7abe50/library/core/src/fmt/rt.rs:138:9
   5:     0x7ff879dc94bf - core::fmt::write::h809e1a6b668324f6
                               at /rustc/3b2073f0762cff4d3d625bb10017e0ce4e7abe50/library/core/src/fmt/mod.rs:1094:21
   6:     0x7ff879d5a877 - std::io::Write::write_fmt::h2ed31d529426c73c
                               at /rustc/3b2073f0762cff4d3d625bb10017e0ce4e7abe50/library/std/src/io/mod.rs:1713:15
   7:     0x7ff879d67c25 - std::sys_common::backtrace::_print::h72058f630d074235
                               at /rustc/3b2073f0762cff4d3d625bb10017e0ce4e7abe50/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x7ff879d67c25 - std::sys_common::backtrace::print::h71140e0244457266
                               at /rustc/3b2073f0762cff4d3d625bb10017e0ce4e7abe50/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x7ff879d6a9d3 - std::panicking::default_hook::{{closure}}::h4cc812472591f5d0
                               at /rustc/3b2073f0762cff4d3d625bb10017e0ce4e7abe50/library/std/src/panicking.rs:269:22
  10:     0x7ff879d6a764 - std::panicking::default_hook::h63cd13622fb98d85
                               at /rustc/3b2073f0762cff4d3d625bb10017e0ce4e7abe50/library/std/src/panicking.rs:288:9
  11:     0x7ff87cfad52b - <rustc_driver_impl[2635ae639440f84d]::install_ice_hook::{closure#0} as core[179bd5bdb7674514]::ops::function::FnOnce<(&core[179bd5bdb7674514]::panic::panic_info::PanicInfo,)>>::call_once::{shim:vtable#0}
  12:     0x7ff879d6b1fe - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h2ecbaa31401232a8
                               at /rustc/3b2073f0762cff4d3d625bb10017e0ce4e7abe50/library/alloc/src/boxed.rs:2007:9
  13:     0x7ff879d6b1fe - std::panicking::rust_panic_with_hook::h521173c88e8eb80d
                               at /rustc/3b2073f0762cff4d3d625bb10017e0ce4e7abe50/library/std/src/panicking.rs:709:13
  14:     0x7ff87d4b22e1 - std[a820ec68793a1c54]::panicking::begin_panic::<rustc_errors[b597254c8f098bdb]::ExplicitBug>::{closure#0}
  15:     0x7ff87d4b0f36 - std[a820ec68793a1c54]::sys_common::backtrace::__rust_end_short_backtrace::<std[a820ec68793a1c54]::panicking::begin_panic<rustc_errors[b597254c8f098bdb]::ExplicitBug>::{closure#0}, !>
  16:     0x7ff87d5476f6 - std[a820ec68793a1c54]::panicking::begin_panic::<rustc_errors[b597254c8f098bdb]::ExplicitBug>
  17:     0x7ff87d4ade74 - <rustc_errors[b597254c8f098bdb]::HandlerInner>::bug::<alloc[94daa9e91581ecb7]::string::String>
  18:     0x7ff87d4adcf6 - <rustc_errors[b597254c8f098bdb]::Handler>::bug::<alloc[94daa9e91581ecb7]::string::String>
  19:     0x7ff87d50146c - rustc_middle[2d6135a6a55a92f4]::util::bug::opt_span_bug_fmt::<rustc_span[9ec16770641762ee]::span_encoding::Span>::{closure#0}
  20:     0x7ff87d4fe30a - rustc_middle[2d6135a6a55a92f4]::ty::context::tls::with_opt::<rustc_middle[2d6135a6a55a92f4]::util::bug::opt_span_bug_fmt<rustc_span[9ec16770641762ee]::span_encoding::Span>::{closure#0}, !>::{closure#0}
  21:     0x7ff87d4fe2da - rustc_middle[2d6135a6a55a92f4]::ty::context::tls::with_context_opt::<rustc_middle[2d6135a6a55a92f4]::ty::context::tls::with_opt<rustc_middle[2d6135a6a55a92f4]::util::bug::opt_span_bug_fmt<rustc_span[9ec16770641762ee]::span_encoding::Span>::{closure#0}, !>::{closure#0}, !>
  22:     0x7ff87b2e4aed - rustc_middle[2d6135a6a55a92f4]::util::bug::bug_fmt
  23:     0x7ff87b1afe11 - rustc_codegen_ssa[48a71250af989085]::debuginfo::type_names::push_debuginfo_type_name
  24:     0x7ff87b1b35ca - rustc_codegen_ssa[48a71250af989085]::debuginfo::type_names::push_generic_params_internal
  25:     0x7ff87b535b6e - rustc_codegen_llvm[9635be2417e1ae72]::debuginfo::metadata::type_di_node
  26:     0x7ff87bc2a73a - rustc_codegen_llvm[9635be2417e1ae72]::debuginfo::metadata::build_global_var_di_node
  27:     0x7ff87bc29d6b - <rustc_codegen_llvm[9635be2417e1ae72]::context::CodegenCx as rustc_codegen_ssa[48a71250af989085]::traits::statics::StaticMethods>::codegen_static
  28:     0x7ff87bc12eac - rustc_codegen_llvm[9635be2417e1ae72]::base::compile_codegen_unit::module_codegen
  29:     0x7ff87bc111d5 - <rustc_middle[2d6135a6a55a92f4]::dep_graph::dep_node::DepKind as rustc_query_system[820ba01abcedc11e]::dep_graph::DepKind>::with_deps::<<rustc_query_system[820ba01abcedc11e]::dep_graph::graph::DepGraphData<rustc_middle[2d6135a6a55a92f4]::dep_graph::dep_node::DepKind>>::with_task<rustc_middle[2d6135a6a55a92f4]::ty::context::TyCtxt, rustc_span[9ec16770641762ee]::symbol::Symbol, rustc_codegen_ssa[48a71250af989085]::ModuleCodegen<rustc_codegen_llvm[9635be2417e1ae72]::ModuleLlvm>>::{closure#0}::{closure#0}, rustc_codegen_ssa[48a71250af989085]::ModuleCodegen<rustc_codegen_llvm[9635be2417e1ae72]::ModuleLlvm>>
  30:     0x7ff87bc109cf - rustc_codegen_llvm[9635be2417e1ae72]::base::compile_codegen_unit
  31:     0x7ff87bc0def1 - rustc_codegen_ssa[48a71250af989085]::base::codegen_crate::<rustc_codegen_llvm[9635be2417e1ae72]::LlvmCodegenBackend>
  32:     0x7ff87bc0d7ff - <rustc_codegen_llvm[9635be2417e1ae72]::LlvmCodegenBackend as rustc_codegen_ssa[48a71250af989085]::traits::backend::CodegenBackend>::codegen_crate
  33:     0x7ff87c4d7652 - <rustc_session[dc274bc86de11b2]::session::Session>::time::<alloc[94daa9e91581ecb7]::boxed::Box<dyn core[179bd5bdb7674514]::any::Any>, rustc_interface[b727bedca2f0eb3b]::passes::start_codegen::{closure#0}>
  34:     0x7ff87c4d71cb - rustc_interface[b727bedca2f0eb3b]::passes::start_codegen
  35:     0x7ff87c4d1f2d - <rustc_middle[2d6135a6a55a92f4]::ty::context::GlobalCtxt>::enter::<<rustc_interface[b727bedca2f0eb3b]::queries::Queries>::ongoing_codegen::{closure#0}::{closure#0}, core[179bd5bdb7674514]::result::Result<alloc[94daa9e91581ecb7]::boxed::Box<dyn core[179bd5bdb7674514]::any::Any>, rustc_span[9ec16770641762ee]::ErrorGuaranteed>>
  36:     0x7ff87c4d115d - <rustc_interface[b727bedca2f0eb3b]::queries::Queries>::ongoing_codegen
  37:     0x7ff87c4d0280 - <rustc_interface[b727bedca2f0eb3b]::interface::Compiler>::enter::<rustc_driver_impl[2635ae639440f84d]::run_compiler::{closure#1}::{closure#2}, core[179bd5bdb7674514]::result::Result<core[179bd5bdb7674514]::option::Option<rustc_interface[b727bedca2f0eb3b]::queries::Linker>, rustc_span[9ec16770641762ee]::ErrorGuaranteed>>
  38:     0x7ff87c4cd8b1 - std[a820ec68793a1c54]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[b727bedca2f0eb3b]::util::run_in_thread_pool_with_globals<rustc_interface[b727bedca2f0eb3b]::interface::run_compiler<core[179bd5bdb7674514]::result::Result<(), rustc_span[9ec16770641762ee]::ErrorGuaranteed>, rustc_driver_impl[2635ae639440f84d]::run_compiler::{closure#1}>::{closure#0}, core[179bd5bdb7674514]::result::Result<(), rustc_span[9ec16770641762ee]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[179bd5bdb7674514]::result::Result<(), rustc_span[9ec16770641762ee]::ErrorGuaranteed>>
  39:     0x7ff87c4cd035 - <<std[a820ec68793a1c54]::thread::Builder>::spawn_unchecked_<rustc_interface[b727bedca2f0eb3b]::util::run_in_thread_pool_with_globals<rustc_interface[b727bedca2f0eb3b]::interface::run_compiler<core[179bd5bdb7674514]::result::Result<(), rustc_span[9ec16770641762ee]::ErrorGuaranteed>, rustc_driver_impl[2635ae639440f84d]::run_compiler::{closure#1}>::{closure#0}, core[179bd5bdb7674514]::result::Result<(), rustc_span[9ec16770641762ee]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[179bd5bdb7674514]::result::Result<(), rustc_span[9ec16770641762ee]::ErrorGuaranteed>>::{closure#1} as core[179bd5bdb7674514]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  40:     0x7ff879d75685 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h7557df74034f0cd4
                               at /rustc/3b2073f0762cff4d3d625bb10017e0ce4e7abe50/library/alloc/src/boxed.rs:1993:9
  41:     0x7ff879d75685 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::ha799d8f85cbbc72f
                               at /rustc/3b2073f0762cff4d3d625bb10017e0ce4e7abe50/library/alloc/src/boxed.rs:1993:9
  42:     0x7ff879d75685 - std::sys::unix::thread::Thread::new::thread_start::h88ab86e849d99fd7
                               at /rustc/3b2073f0762cff4d3d625bb10017e0ce4e7abe50/library/std/src/sys/unix/thread.rs:108:17
  43:     0x7ff879a8f18a - start_thread
                               at ./nptl/pthread_create.c:444:8
  44:     0x7ff879b1dbd0 - __GI___clone3
                               at ./misc/../sysdeps/unix/sysv/linux/x86_64/clone3.S:81
  45:                0x0 - <unknown>
```

</p>
</details>

### PR DESCRIPTION
**Pull request by compiler-errors**
Fixes #112752
Fixes #112731 (same root cause, so didn't make a test for it)
fixes #112776

r? @oli-obk

### CODE REVIEW

File: compiler/rustc_trait_selection/src/traits/query/normalize.rs [hunk 1]
```diff
@@ -322,8 +322,12 @@ impl<'cx, 'tcx> FallibleTypeFolder<TyCtxt<'tcx>> for QueryNormalizer<'cx, 'tcx>
...
                 // `tcx.normalize_projection_ty` may normalize to a type that still has
                 // unevaluated consts, so keep normalizing here if that's the case.
-                if res != ty && res.has_type_flags(ty::TypeFlags::HAS_CT_PROJECTION) {
-                    res.try_super_fold_with(self)?
+                // Similarly, `tcx.normalize_weak_ty` will only unwrap one layer of type
+                // and we need to continue folding it to reveal the TAIT behind it.
+                if res != ty
+                    && (res.has_type_flags(ty::TypeFlags::HAS_CT_PROJECTION) || kind == ty::Weak)
+                {
+                    res.try_fold_with(self)?
```
Comment (compiler-errors) [inline compiler/rustc_trait_selection/src/traits/query/normalize.rs:330]: Whereas for the CT_PROJECTION case we didn't care about folding on the type or just calling super-fold, for the weak case, we need to call super-fold.

File: compiler/rustc_trait_selection/src/traits/query/normalize.rs [hunk 2]
```diff
@@ -322,8 +322,12 @@ impl<'cx, 'tcx> FallibleTypeFolder<TyCtxt<'tcx>> for QueryNormalizer<'cx, 'tcx>
                 };
                 // `tcx.normalize_projection_ty` may normalize to a type that still has
                 // unevaluated consts, so keep normalizing here if that's the case.
-                if res != ty && res.has_type_flags(ty::TypeFlags::HAS_CT_PROJECTION) {
-                    res.try_super_fold_with(self)?
+                // Similarly, `tcx.normalize_weak_ty` will only unwrap one layer of type
+                // and we need to continue folding it to reveal the TAIT behind it.
+                if res != ty
+                    && (res.has_type_flags(ty::TypeFlags::HAS_CT_PROJECTION) || kind == ty::Weak)
```
Comment (compiler-errors) [inline compiler/rustc_trait_selection/src/traits/query/normalize.rs:328]: Alternatively, we *could* instead modify the `normalize_weak_ty` query and do the deep normalization there, instead of here.

**Comment by jieyouxu** [comment]
I *think* #112777 is another issue that this PR might fix.

File: compiler/rustc_trait_selection/src/traits/query/normalize.rs (hunk 2 above)
Comment (oli-obk) [reply compiler/rustc_trait_selection/src/traits/query/normalize.rs:328]: that's not what we do for the other normalize queries. Maybe we should rename them to `shallow_normalize_...`
