### PR TITLE
Disallow frontmatter in `--cfg` and `--check-cfg` arguments

### LINKED ISSUE #146130: Frontmatter inside `--cfg` and `--check-cfg` is not feature-gated
The following invocation compiles since 1.88 (or PR #140035):

```sh
rustc /dev/null --crate-type lib --cfg '---
---
key'
```

while it shouldn't because unstable feature `frontmatter` isn't enabled anywhere.

For context, in 1.87, it yielded the following error:

```
error: invalid `--cfg` argument: `---
       ---
       key` (expected `key` or `key="value"`)
```

The same applies to `--check-cfg`.

### PR DESCRIPTION
**Pull request by Urgau**
This PR disallows the frontmatter syntax in `--cfg` and `--check-cfg` arguments.

Fixes https://github.com/rust-lang/rust/issues/146130
r? fmease

### CODE REVIEW

File: tests/run-make/multiline-args-value/rmake.rs
Comment (fmease) [inline tests/run-make/multiline-args-value/rmake.rs:1]: Maybe mention "frontmatter" somewhere in the dirname and maybe also link back to the issue?

**Review by fmease — APPROVED** [review]

**Comment by fmease** [comment]
Thanks! r=me with nit addressed in some way or another
@bors rollup

File: tests/run-make/multiline-args-value/rmake.rs
Comment (Urgau) [reply tests/run-make/multiline-args-value/rmake.rs:1]: I want to use the test for the shebang issue, so I will add a backlink in the test.

Comment (Urgau) [reply tests/run-make/multiline-args-value/rmake.rs:1]: Added.

File: tests/run-make/multiline-args-value/rmake.rs [hunk 1]
```diff
@@ -0,0 +1,37 @@
...
+        .actual_text("output", output.stdout_utf8())
+        .run();
+    diff()
+        .expected_file(format!("{flag}.stderr"))
+        .actual_text("output", output.stderr_utf8())
+        .run();
+}
+
+fn main() {
+    // Verify that frontmatter aren't allowed in `--cfg` arguments.
```
Comment (fmease) [inline tests/run-make/multiline-args-value/rmake.rs]:
```suggestion
    // Verify that frontmatter isn't allowed in `--cfg` arguments.
```

(and below), but doesn't matter; r=me regardless :)

Comment (Urgau) [reply tests/run-make/multiline-args-value/rmake.rs]: For whatever reason I thought one could specify multiple frontmatter. Seems like it's a thing. Fixed.
