### PR TITLE
errors: share `SilentEmitter` between rustc and rustfmt

### LINKED ISSUE #6082: thread 'main' panicked at src/tools/rustfmt/src/parse/session.rs:42:9: silent emitter attempted to translate a diagnostic
[rustc-ice-2024-02-19T01_32_59-84679.txt](https://github.com/rust-lang/rustfmt/files/14325344/rustc-ice-2024-02-19T01_32_59-84679.txt)

Sorry, not a very helpful bug report, but it said to open an issue

### PR DESCRIPTION
**Pull request by davidtwco**
Fixes rust-lang/rustfmt#6082.

Shares the `SilentEmitter` between rustc and rustfmt, and gives it a fallback bundle (since it can emit diagnostics in some contexts).

### CODE REVIEW

File: src/tools/rustfmt/src/parse/session.rs [hunk 1]
```diff
@@ -231,7 +199,21 @@ impl ParseSess {
...
+            rustc_driver::DEFAULT_LOCALE_RESOURCES.to_vec(),
+            false,
+        );
+        // SAFETY: `fatal_dcx` will not be dropped while it is referenced by `self.parse_sess.dcx`,
+        // and `self.parse_sess.dcx` is written to by `ptr::write` so won't drop `fatal_dcx`.
+        unsafe {
+            let fatal_dcx = std::ptr::read(&self.parse_sess.dcx);
+            std::ptr::write(
+                &mut self.parse_sess.dcx,
+                DiagCtxt::with_emitter(Box::new(SilentEmitter { fallback_bundle, fatal_dcx, fatal_note: None }))
```
Comment (compiler-errors) [inline src/tools/rustfmt/src/parse/session.rs:214]: You probably should wrap that `fatal_dcx` in a `ManuallyDrop`. In case `with_emitter` or the allocation panics, I believe this will result in the `dcx` being dropped twice.

Comment (davidtwco) [reply src/tools/rustfmt/src/parse/session.rs:214]: I might be misunderstanding, but wouldn't I just be immediately removing `fatal_dcx` from the `ManuallyDrop` to put it in the `SilentEmitter`, before the `with_emitter` call?

File: src/tools/rustfmt/src/parse/session.rs [hunk 2]
```diff
@@ -231,7 +199,21 @@ impl ParseSess {
...
     pub(crate) fn set_silent_emitter(&mut self) {
-        self.parse_sess.dcx = DiagCtxt::with_emitter(silent_emitter());
+        // Ideally this invocation wouldn't be necessary and the fallback bundle in
+        // `self.parse_sess.dcx` could be used.
+        let fallback_bundle = rustc_errors::fallback_fluent_bundle(
+            rustc_driver::DEFAULT_LOCALE_RESOURCES.to_vec(),
+            false,
+        );
+        // SAFETY: `fatal_dcx` will not be dropped while it is referenced by `self.parse_sess.dcx`,
+        // and `self.parse_sess.dcx` is written to by `ptr::write` so won't drop `fatal_dcx`.
```
[the remark this answers is not in the document]
Comment (ytmimi) [reply src/tools/rustfmt/src/parse/session.rs:214]: I'm not too keen on adding unsafe code to rustfmt. To the best of my knowledge we don't have any unsafe code in rustfmt.

File: src/tools/rustfmt/tests/source/issue-6082.rs
Comment (ytmimi) [inline src/tools/rustfmt/tests/source/issue-6082.rs:1]: I don't think the formatting is expected to change on this input snippet so it would be enough to just have the `target` test.

File: src/tools/rustfmt/tests/target/issue-6082.rs
Comment (ytmimi) [inline src/tools/rustfmt/tests/target/issue-6082.rs:1]: We have a test case in `src/tools/rustfmt/tests/rustfmt/main.rs` called `dont_emit_ICE`. Could you also add a reference to this file there.

File: src/tools/rustfmt/src/parse/session.rs [hunk 3]
```diff
@@ -231,7 +199,21 @@ impl ParseSess {
     }
 
     pub(crate) fn set_silent_emitter(&mut self) {
-        self.parse_sess.dcx = DiagCtxt::with_emitter(silent_emitter());
+        // Ideally this invocation wouldn't be necessary and the fallback bundle in
+        // `self.parse_sess.dcx` could be used.
```
[the remark this answers is not in the document]
Comment (ytmimi) [reply src/tools/rustfmt/src/parse/session.rs:208]: Just to make sure I understand things correctly, is the reason this can't be used because of the lock that you mentioned in [compiler/rustc_errors/src/emitter.rs](https://github.com/rust-lang/rust/pull/121301/files#diff-a35029c589a6b5b002ecf598efb24d174232e719ecbc6f741a58eee8509cd6a5)? If so, could you also capture that context here.

File: src/tools/rustfmt/src/parse/session.rs (hunk 1 above)
Comment (pnkfelix) [reply src/tools/rustfmt/src/parse/session.rs]: I think that you are both correct. I.e., it looks to me like a `ManuallyDrop` around just the `fatal_dcx` local won't resolve things, but nonetheless the risk of a double-drop here is real...

File: src/tools/rustfmt/src/parse/session.rs (hunk 2 above)
[the remark this answers is not in the document]
Comment (calebcartwright) [reply src/tools/rustfmt/src/parse/session.rs:214]: yeah this would be the very first `unsafe` block that I'm aware of and if there's any way we could avoid it then we'd have a strong preference to do so, even if it results in increased code verbosity

File: src/tools/rustfmt/src/parse/session.rs (hunk 1 above)
Comment (pnkfelix) [reply src/tools/rustfmt/src/parse/session.rs]: @davidtwco would you be willing to explore options here that don't require unsafe code? E.g. storing the `fatal_dcx` in an option and doing the none-swapping pattern, or something?

File: src/tools/rustfmt/src/parse/session.rs (hunk 3 above)
[the remark this answers is not in the document]
Comment (davidtwco) [reply src/tools/rustfmt/src/parse/session.rs:208]: Added a note to this effect.

File: src/tools/rustfmt/src/parse/session.rs (hunk 2 above)
[the remark this answers is not in the document]
Comment (davidtwco) [reply src/tools/rustfmt/src/parse/session.rs]: Removed the unsafe code now.

File: src/tools/rustfmt/src/parse/session.rs (hunk 1 above)
Comment (davidtwco) [reply src/tools/rustfmt/src/parse/session.rs]: Removed the unsafe now.

File: src/tools/rustfmt/tests/target/issue-6082.rs
Comment (davidtwco) [reply src/tools/rustfmt/tests/target/issue-6082.rs:1]: Added

File: src/tools/rustfmt/tests/source/issue-6082.rs
Comment (davidtwco) [reply src/tools/rustfmt/tests/source/issue-6082.rs:1]: Removed

**Review by ytmimi — APPROVED** [review]
rustfmt changes look good to me 👍🏼

**Comment by ytmimi** [comment]
@davidtwco thanks again for working on this fix. I've got confirmation that https://github.com/rust-lang/rustfmt/issues/6082 is resolved!
