### PR TITLE
lint/ctypes: ext. abi fn-ptr in internal abi fn

### LINKED ISSUE #94223: internal compiler error: unexpected panic: thread 'rustc' panicked at 'called `Option::unwrap()` on a `None` value', compiler/rustc_target/src/abi/call/x86_64.rs:158:47
### Code

```Rust
use std::os::raw::*;
use std::ffi::CStr;

pub trait Driver {
	fn resolution(&self) -> u32;
}

#[repr(C)]
pub struct CDriver {
	open: unsafe extern "C" fn(path: CStr, rd_obj: *mut c_void, wr_obj: *mut c_void) -> c_int,
	get_meta: unsafe extern "C" fn(name: *mut *const c_char, version: *mut *const c_char),
	get_resolution: unsafe extern "C" fn() -> u32,
}

#[repr(transparent)]
struct CDriverWrap {
	inner: CDriver,
}

impl Driver for CDriverWrap {
	fn resolution(&self) -> u32 {
		todo!();
	}
}
```

Notes:

* Removing `inner: CDriver` removes the ICE
* Removing any of the other fields from CDriver removes the ICE
* Removing the trait + impl removes the ICE

### Meta

NB: reproduces with [beta + nightly via play.rust-lang.org](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=788f1de2c6ec05c23dee3d65ff2a33f5)

`rustc --version --verbose`:
```
rustc 1.57.0 (f1edd0429 2021-11-29)
binary: rustc
commit-hash: f1edd0429582dd29cccacaf50fd134b05593bd9c
commit-date: 2021-11-29
host: x86_64-unknown-linux-gnu
release: 1.57.0
LLVM version: 13.0.0
```

### Error output

```
thread 'rustc' panicked at 'called `Option::unwrap()` on a `None` value', compiler/rustc_target/src/abi/call/x86_64.rs:158:47
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

<details><summary><strong>Full output + Backtrace</strong></summary>
<p>

```
warning: field is never read: `inner`
  --> main.rs:17:2
   |
17 |     inner: CDriver,
   |     ^^^^^^^^^^^^^^
   |
   = note: `#[warn(dead_code)]` on by default

thread 'rustc' panicked at 'called `Option::unwrap()` on a `None` value', compiler/rustc_target/src/abi/call/x86_64.rs:158:47
stack backtrace:
   0: rust_begin_unwind
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panicking.rs:517:5
   1: core::panicking::panic_fmt
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/panicking.rs:100:14
   2: core::panicking::panic
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/panicking.rs:50:5
   3: rustc_target::abi::call::x86_64::cast_target
   4: rustc_target::abi::call::x86_64::compute_abi_info::{{closure}}
   5: rustc_target::abi::call::x86_64::compute_abi_info
   6: rustc_target::abi::call::FnAbi<Ty>::adjust_for_foreign_abi
   7: rustc_middle::ty::layout::LayoutCx<rustc_middle::ty::context::TyCtxt>::fn_abi_new_uncached
   8: rustc_middle::ty::layout::fn_abi_of_fn_ptr
   9: rustc_query_system::query::plumbing::get_query
  10: <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::fn_abi_of_fn_ptr
  11: <rustc_target::abi::TyAndLayout<&rustc_middle::ty::TyS> as rustc_codegen_llvm::type_of::LayoutLlvmExt>::llvm_type
  12: rustc_codegen_llvm::type_of::struct_llfields
  13: <rustc_target::abi::TyAndLayout<&rustc_middle::ty::TyS> as rustc_codegen_llvm::type_of::LayoutLlvmExt>::llvm_type
  14: rustc_codegen_llvm::type_of::struct_llfields
  15: <rustc_target::abi::TyAndLayout<&rustc_middle::ty::TyS> as rustc_codegen_llvm::type_of::LayoutLlvmExt>::llvm_type
  16: <rustc_target::abi::TyAndLayout<&rustc_middle::ty::TyS> as rustc_codegen_llvm::type_of::LayoutLlvmExt>::llvm_type
  17: <rustc_target::abi::call::FnAbi<&rustc_middle::ty::TyS> as rustc_codegen_llvm::abi::FnAbiLlvmExt>::llvm_type
  18: rustc_codegen_llvm::mono_item::<impl rustc_codegen_ssa::traits::declare::PreDefineMethods for rustc_codegen_llvm::context::CodegenCx>::predefine_fn
  19: rustc_codegen_llvm::base::compile_codegen_unit::module_codegen
  20: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task
  21: rustc_codegen_llvm::base::compile_codegen_unit
  22: rustc_codegen_ssa::base::codegen_crate
  23: <rustc_codegen_llvm::LlvmCodegenBackend as rustc_codegen_ssa::traits::backend::CodegenBackend>::codegen_crate
  24: rustc_interface::queries::Queries::ongoing_codegen
  25: rustc_interface::queries::<impl rustc_interface::interface::Compiler>::enter
  26: rustc_span::with_source_map
  27: scoped_tls::ScopedKey<T>::set
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.57.0 (f1edd0429 2021-11-29) running on x86_64-unknown-linux-gnu

note: compiler flags: --crate-type lib

query stack during panic:
#0 [fn_abi_of_fn_ptr] computing call ABI of `unsafe extern "C" fn(std::ffi::c_str::CStr, *mut core::ffi::c_void, *mut core::ffi::c_void) -> i32` function pointers
end of query stack
warning: 1 warning emitted
```

</p>
</details>

### PR DESCRIPTION
**Pull request by davidtwco**
Fixes #94223.

- In the improper ctypes lint, instead of skipping functions with internal ABIs, check that the signature doesn't contain any fn-ptr types with external ABIs that aren't FFI-safe.
- When computing the ABI for fn-ptr types, remove an `unwrap` that assumed FFI-safe types in foreign fn-ptr types.
  - I'm not certain that this is the correct approach.

### CODE REVIEW

File: compiler/rustc_lint/src/types.rs [hunk 1]
```diff
@@ -1255,23 +1278,45 @@ impl<'a, 'tcx> ImproperCTypesVisitor<'a, 'tcx> {
             SpecAbi::Rust | SpecAbi::RustCall | SpecAbi::RustIntrinsic | SpecAbi::PlatformIntrinsic
         )
     }
+
+    /// Find any fn-ptr types with external ABIs in `ty`.
+    ///
+    /// For example, `Option<extern "C" fn()>` returns `extern "C" fn()`
+    fn find_fn_ptr_ty_with_external_abi(&self, ty: Ty<'tcx>) -> Option<Ty<'tcx>> {
```
Comment (WaffleLapkin) [inline compiler/rustc_lint/src/types.rs:1285]: Why does this return a single type? Wouldn't something like `Result<extern "C" fn(), extern "C" fn(FfiUnsafe)>` still cause problems?

File: compiler/rustc_lint/src/types.rs [hunk 2]
```diff
@@ -1255,23 +1278,45 @@ impl<'a, 'tcx> ImproperCTypesVisitor<'a, 'tcx> {
...
-                }
-                hir::ForeignItemKind::Static(ref ty, _) => {
-                    vis.check_foreign_static(it.owner_id, ty.span);
-                }
-                hir::ForeignItemKind::Type => (),
+        match it.kind {
+            hir::ForeignItemKind::Fn(ref decl, _, _) => {
+                vis.check_maybe_foreign_fn(abi, it.owner_id.def_id, decl);
+            }
+            hir::ForeignItemKind::Static(ref ty, _) if !vis.is_internal_abi(abi) => {
```
Comment (WaffleLapkin) [inline compiler/rustc_lint/src/types.rs:1316]: Wouldn't a static of type `extern "C" fn(FfiUnsafe)` cause problems, similarly to functions?

**Comment by Nilstrieb** [comment]
This seems to be the wording that is already used, but I really don't like the `internal` vs `external| wording here, it makes no sense. An `extern "Rust" fn` is not internal, it just has a Rust ABI. Maybe `c_like` vs `rust_like` would be a better name.

File: compiler/rustc_lint/src/types.rs (hunk 2 above)
Comment (davidtwco) [reply compiler/rustc_lint/src/types.rs:1347]: It would, checking this too now.

File: compiler/rustc_lint/src/types.rs (hunk 1 above)
Comment (davidtwco) [reply compiler/rustc_lint/src/types.rs]: Fixed!

**Comment by davidtwco** [comment]
> This seems to be the wording that is already used, but I really don't like the `internal` vs `external| wording here, it makes no sense. An `extern "Rust" fn`is not internal, it just has a Rust ABI. Maybe`c_like`vs`rust_like` would be a better name.

I agree, but I'll leave this for a follow-up.

**Review by WaffleLapkin — COMMENTED** [review]
I'm a bit confused now.

Surely this should fail compilation:
```rust
#![deny(improper_ctypes_definitions, improper_ctypes)]
struct __(extern "C" fn([u8]));
```
And yet, it currently passes it ([[play]](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=4109817167d14b7135a2c9d657297803)). And, if I understood correctly, under this PR it would pass too...

Maybe instead of trying to deeply check types in `extern` items, we should actually just check _all_ types, find `extern ... fn(...)` types and check their arguments?

**Comment by WaffleLapkin** [comment]
> I've extended support to all types that could contain the extern fn-ptr types

I don't think that's necessarily enough.

For example this doesn't get linted, still:
```rust
#![deny(improper_ctypes_definitions, improper_ctypes)]
fn main() {
    let _: extern "C" fn([u8]) = todo!();
}
```

I would prefer using something like [`LateLintPass::check_ty`](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_lint/trait.LateLintPass.html#method.check_ty), so that we are sure we lint every type that is written in the source... but `check_ty` gets only a `hir::Ty` so I'm not sure if it could work (I don't see an easy way to get `rustc_middle::ty::Ty` from it)

**Comment by davidtwco** [comment]
> I would prefer using something like [LateLintPass::check_ty](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_lint/trait.LateLintPass.html#method.check_ty), so that we are sure we lint every type that is written in the source... but check_ty gets only a hir::Ty so I'm not sure if it could work (I don't see an easy way to get rustc_middle::ty::Ty from it)

That's exactly why I haven't used `check_ty`, also because I didn't want to check anything in foreign items, as the `ImproperCTypesDeclarations` lint visitor handles those.

I think all that I can do is implement `check_expr`?

File: compiler/rustc_lint/src/types.rs [hunk 3]
```diff
@@ -1230,17 +1230,45 @@ impl<'a, 'tcx> ImproperCTypesVisitor<'a, 'tcx> {
...
+        &mut self,
+        abi: SpecAbi,
+        def_id: LocalDefId,
+        decl: &'tcx hir::FnDecl<'_>,
+    ) {
         let sig = self.cx.tcx.fn_sig(def_id).subst_identity();
         let sig = self.cx.tcx.erase_late_bound_regions(sig);
 
+        let is_internal_abi = self.is_internal_abi(abi);
+        let check_ty = |this: &mut ImproperCTypesVisitor<'a, 'tcx>,
```
Comment (jackh726) [inline compiler/rustc_lint/src/types.rs:1248]: So, this all seems like it should just be a part of a visitor with a flag for foreign abi or not.

**Review by jackh726 — APPROVED** [review]
Just one thought, but r=me if you don't want to try to change things.

**Comment by davidtwco** [comment]
@bors r=jackh726 

I think that suggestion is best left for a follow-up.

**Comment by Dylan-DPC** [comment]
@bors rollup=iffy 

(potential failure for #111093, running it individually to see if it fails with the same error)

**Comment by Dylan-DPC** [comment]
@bors r-

this wasn't supposed to be running
