### PR TITLE
Fix: ices on virtual-function-elimination about principal trait

### LINKED ISSUE #123955: ICE: virtual-function-elimination
### Code

This happens when compiling the crate https://crates.io/crates/webbrowser `x86_64-pc-windows-gnu` with [virtual-function-elimination](https://doc.rust-lang.org/stable/unstable-book/compiler-flags/virtual-function-elimination.html#virtual-function-elimination).

```
# Cargo.toml
[dependencies]
webbrowser = "0.8"

[profile.release]
opt-level = 3
strip = true
codegen-units = 1
lto = true
panic = "abort"
incremental = false
```
```
# .cargo/config.toml
[build]
rustflags = [
    "-Clto",
    "-Zvirtual-function-elimination",
    "-Zlocation-detail=none"
]
```

### Meta

`rustc --version --verbose`:
```
rustc 1.79.0-nightly (0d8b3346a 2024-04-14)
binary: rustc
commit-hash: 0d8b3346a3992ab11ea35ff0fb95a6864b91f797
commit-date: 2024-04-14
host: x86_64-unknown-linux-gnu
release: 1.79.0-nightly
LLVM version: 18.1.3
```

### Error output

The backtrace and output here are obtained during cross-compilation (host `x86_64-unknown-linux-gnu`, target `x86_64-pc-windows-gnu`, build-std), but the panic also happens when the host is Windows and without build-std.
<details><summary><strong>Backtrace</strong></summary>
<p>

```
thread 'rustc' panicked at compiler/rustc_codegen_ssa/src/meth.rs:77:37:
expected principal trait object
stack backtrace:
   0:     0x7f23afd74b55 - std::backtrace_rs::backtrace::libunwind::trace::h0041d53520962ed0
                               at /rustc/0d8b3346a3992ab11ea35ff0fb95a6864b91f797/library/std/src/../../backtrace/src/backtrace/libunwind.rs:105:5
   1:     0x7f23afd74b55 - std::backtrace_rs::backtrace::trace_unsynchronized::hf766828f611d7b85
                               at /rustc/0d8b3346a3992ab11ea35ff0fb95a6864b91f797/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7f23afd74b55 - std::backtrace::Backtrace::create::hd233542d9b78f687
                               at /rustc/0d8b3346a3992ab11ea35ff0fb95a6864b91f797/library/std/src/backtrace.rs:331:13
   3:     0x7f23afd74aa5 - std::backtrace::Backtrace::force_capture::h664151d7068618d8
                               at /rustc/0d8b3346a3992ab11ea35ff0fb95a6864b91f797/library/std/src/backtrace.rs:312:9
   4:     0x7f23b2e7a353 - std[28e079ecff9295a0]::panicking::update_hook::<alloc[f6e078dfec71fdaa]::boxed::Box<rustc_driver_impl[e4c67f8d11c8e5e4]::install_ice_hook::{closure#0}>>::{closure#0}
   5:     0x7f23afd8fb2c - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h6b1d9df3b9d447c5
                               at /rustc/0d8b3346a3992ab11ea35ff0fb95a6864b91f797/library/alloc/src/boxed.rs:2032:9
   6:     0x7f23afd8fb2c - std::panicking::rust_panic_with_hook::h32d6515ed3e50ef3
                               at /rustc/0d8b3346a3992ab11ea35ff0fb95a6864b91f797/library/std/src/panicking.rs:792:13
   7:     0x7f23afd8f8d6 - std::panicking::begin_panic_handler::{{closure}}::h747e30852c586aa5
                               at /rustc/0d8b3346a3992ab11ea35ff0fb95a6864b91f797/library/std/src/panicking.rs:657:13
   8:     0x7f23afd8d199 - std::sys_common::backtrace::__rust_end_short_backtrace::h29f2ae5b8f4a37f0
                               at /rustc/0d8b3346a3992ab11ea35ff0fb95a6864b91f797/library/std/src/sys_common/backtrace.rs:171:18
   9:     0x7f23afd8f607 - rust_begin_unwind
                               at /rustc/0d8b3346a3992ab11ea35ff0fb95a6864b91f797/library/std/src/panicking.rs:645:5
  10:     0x7f23afdd8466 - core::panicking::panic_fmt::h0db242b390fa423a
                               at /rustc/0d8b3346a3992ab11ea35ff0fb95a6864b91f797/library/core/src/panicking.rs:72:14
  11:     0x7f23afdd861c - core::panicking::panic_display::h191733efabdeadb5
                               at /rustc/0d8b3346a3992ab11ea35ff0fb95a6864b91f797/library/core/src/panicking.rs:256:5
  12:     0x7f23afdd820c - core::panicking::panic_str::hf4314323308839b3
                               at /rustc/0d8b3346a3992ab11ea35ff0fb95a6864b91f797/library/core/src/panicking.rs:231:5
  13:     0x7f23afdd820c - core::option::expect_failed::h8cb1e01b3c84794d
                               at /rustc/0d8b3346a3992ab11ea35ff0fb95a6864b91f797/library/core/src/option.rs:1994:5
  14:     0x7f23b2db3789 - rustc_codegen_ssa[e08ec6553c5b268c]::meth::expect_dyn_trait_in_self
  15:     0x7f23b5a08d6b - <rustc_codegen_ssa[e08ec6553c5b268c]::meth::VirtualIndex>::get_fn::<rustc_codegen_llvm[dea4b532a132fe1]::builder::Builder>.cold
  16:     0x7f23b10bc887 - <rustc_codegen_ssa[e08ec6553c5b268c]::mir::FunctionCx<rustc_codegen_llvm[dea4b532a132fe1]::builder::Builder>>::codegen_terminator
  17:     0x7f23b4f6b276 - rustc_codegen_ssa[e08ec6553c5b268c]::mir::codegen_mir::<rustc_codegen_llvm[dea4b532a132fe1]::builder::Builder>
  18:     0x7f23b4f5768e - rustc_codegen_llvm[dea4b532a132fe1]::base::compile_codegen_unit::module_codegen
  19:     0x7f23b4f538d6 - <rustc_codegen_llvm[dea4b532a132fe1]::LlvmCodegenBackend as rustc_codegen_ssa[e08ec6553c5b268c]::traits::backend::ExtraBackendMethods>::compile_codegen_unit
  20:     0x7f23b5175d67 - rustc_codegen_ssa[e08ec6553c5b268c]::base::codegen_crate::<rustc_codegen_llvm[dea4b532a132fe1]::LlvmCodegenBackend>
  21:     0x7f23b50d1474 - <rustc_codegen_llvm[dea4b532a132fe1]::LlvmCodegenBackend as rustc_codegen_ssa[e08ec6553c5b268c]::traits::backend::CodegenBackend>::codegen_crate
  22:     0x7f23b50d0ddd - rustc_interface[6ffa910166101c62]::passes::start_codegen
  23:     0x7f23b50d0458 - <rustc_interface[6ffa910166101c62]::queries::Queries>::codegen_and_build_linker
  24:     0x7f23b4ecd2c4 - rustc_interface[6ffa910166101c62]::interface::run_compiler::<core[b4e8c3011bb447ec]::result::Result<(), rustc_span[9e93fcdd45ee9b78]::ErrorGuaranteed>, rustc_driver_impl[e4c67f8d11c8e5e4]::run_compiler::{closure#0}>::{closure#0}
  25:     0x7f23b4fad95d - std[28e079ecff9295a0]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[6ffa910166101c62]::util::run_in_thread_with_globals<rustc_interface[6ffa910166101c62]::util::run_in_thread_pool_with_globals<rustc_interface[6ffa910166101c62]::interface::run_compiler<core[b4e8c3011bb447ec]::result::Result<(), rustc_span[9e93fcdd45ee9b78]::ErrorGuaranteed>, rustc_driver_impl[e4c67f8d11c8e5e4]::run_compiler::{closure#0}>::{closure#0}, core[b4e8c3011bb447ec]::result::Result<(), rustc_span[9e93fcdd45ee9b78]::ErrorGuaranteed>>::{closure#0}, core[b4e8c3011bb447ec]::result::Result<(), rustc_span[9e93fcdd45ee9b78]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[b4e8c3011bb447ec]::result::Result<(), rustc_span[9e93fcdd45ee9b78]::ErrorGuaranteed>>
  26:     0x7f23b4fad76a - <<std[28e079ecff9295a0]::thread::Builder>::spawn_unchecked_<rustc_interface[6ffa910166101c62]::util::run_in_thread_with_globals<rustc_interface[6ffa910166101c62]::util::run_in_thread_pool_with_globals<rustc_interface[6ffa910166101c62]::interface::run_compiler<core[b4e8c3011bb447ec]::result::Result<(), rustc_span[9e93fcdd45ee9b78]::ErrorGuaranteed>, rustc_driver_impl[e4c67f8d11c8e5e4]::run_compiler::{closure#0}>::{closure#0}, core[b4e8c3011bb447ec]::result::Result<(), rustc_span[9e93fcdd45ee9b78]::ErrorGuaranteed>>::{closure#0}, core[b4e8c3011bb447ec]::result::Result<(), rustc_span[9e93fcdd45ee9b78]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[b4e8c3011bb447ec]::result::Result<(), rustc_span[9e93fcdd45ee9b78]::ErrorGuaranteed>>::{closure#2} as core[b4e8c3011bb447ec]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  27:     0x7f23afd99a1b - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h2b96691ad6dafbe5
                               at /rustc/0d8b3346a3992ab11ea35ff0fb95a6864b91f797/library/alloc/src/boxed.rs:2018:9
  28:     0x7f23afd99a1b - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h39ccdff465ac8cd2
                               at /rustc/0d8b3346a3992ab11ea35ff0fb95a6864b91f797/library/alloc/src/boxed.rs:2018:9
  29:     0x7f23afd99a1b - std::sys::pal::unix::thread::Thread::new::thread_start::h53dc0fc9f9e756a0
                               at /rustc/0d8b3346a3992ab11ea35ff0fb95a6864b91f797/library/std/src/sys/pal/unix/thread.rs:108:17
  30:     0x7f23afb7e55a - <unknown>
  31:     0x7f23afbfba3c - <unknown>
  32:                0x0 - <unknown>


rustc version: 1.79.0-nightly (0d8b3346a 2024-04-14)
platform: x86_64-unknown-linux-gnu

query stack during panic:
end of query stack
```

</p>
</details>

### LINKED ISSUE #124092: ICE: `expected principal trait object`
auto-reduced (treereduce-rust):
````rust
const X: for<'b> fn(&'b ()) = |&()| ();
fn main() {
    let dyn_debug = Box::new(X) as Box<fn(&'static ())> as Box<dyn Send>;
}


````

original:
````rust
//@ run-pass
//@ revisions: mir codegen
//@[mir] compile-flags: -Zmir-opt-level=3
//@[codegen] compile-flags: -Zmir-opt-level=0

// A regression test for #107205

const X: for<'b> fn(&'b ()) = |&()| ();
fn main() {
    let dyn_debug = Box::new(X) as Box<fn(&'static ())> as Box<dyn Send>;
    drop(dyn_debug)
}

````

Version information
````
rustc 1.79.0-nightly (00ed4edb4 2024-04-17)
binary: rustc
commit-hash: 00ed4edb44ccc76d8cc992ef9f9f4634ea6d0e82
commit-date: 2024-04-17
host: x86_64-unknown-linux-gnu
release: 1.79.0-nightly
LLVM version: 18.1.3

````

Command:
`/home/matthias/.rustup/toolchains/master/bin/rustc -Zvirtual-function-elimination=true -Clto=true`

<details><summary><strong>Program output</strong></summary>
<p>

```
warning: unused variable: `dyn_debug`
 --> /tmp/icemaker_global_tempdir.8xGPA271RB07/rustc_testrunner_tmpdir_reporting.xnMiIiI7kJOB/mvce.rs:3:9
  |
3 |     let dyn_debug = Box::new(X) as Box<fn(&'static ())> as Box<dyn Send>;
  |         ^^^^^^^^^ help: if this is intentional, prefix it with an underscore: `_dyn_debug`
  |
  = note: `#[warn(unused_variables)]` on by default

thread 'rustc' panicked at compiler/rustc_codegen_ssa/src/meth.rs:77:37:
expected principal trait object
stack backtrace:
   0:     0x77abee75ccd5 - std::backtrace_rs::backtrace::libunwind::trace::h0703e74daad28c72
                               at /rustc/00ed4edb44ccc76d8cc992ef9f9f4634ea6d0e82/library/std/src/../../backtrace/src/backtrace/libunwind.rs:105:5
   1:     0x77abee75ccd5 - std::backtrace_rs::backtrace::trace_unsynchronized::h25ed5cd2627369cf
                               at /rustc/00ed4edb44ccc76d8cc992ef9f9f4634ea6d0e82/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x77abee75ccd5 - std::sys_common::backtrace::_print_fmt::h469d42c17b595d59
                               at /rustc/00ed4edb44ccc76d8cc992ef9f9f4634ea6d0e82/library/std/src/sys_common/backtrace.rs:68:5
   3:     0x77abee75ccd5 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h4b38e3480371ee05
                               at /rustc/00ed4edb44ccc76d8cc992ef9f9f4634ea6d0e82/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x77abee7abf9b - core::fmt::rt::Argument::fmt::haf74bdf42f86a86e
                               at /rustc/00ed4edb44ccc76d8cc992ef9f9f4634ea6d0e82/library/core/src/fmt/rt.rs:165:63
   5:     0x77abee7abf9b - core::fmt::write::h3ae636f8b2626ce6
                               at /rustc/00ed4edb44ccc76d8cc992ef9f9f4634ea6d0e82/library/core/src/fmt/mod.rs:1157:21
   6:     0x77abee7518df - std::io::Write::write_fmt::hf9a4f1c9d6e09581
                               at /rustc/00ed4edb44ccc76d8cc992ef9f9f4634ea6d0e82/library/std/src/io/mod.rs:1832:15
   7:     0x77abee75caae - std::sys_common::backtrace::_print::h66bab3906cd40f88
                               at /rustc/00ed4edb44ccc76d8cc992ef9f9f4634ea6d0e82/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x77abee75caae - std::sys_common::backtrace::print::hd18c1231cf228a1b
                               at /rustc/00ed4edb44ccc76d8cc992ef9f9f4634ea6d0e82/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x77abee75f429 - std::panicking::default_hook::{{closure}}::h130a7699868564f4
  10:     0x77abee75f16d - std::panicking::default_hook::h770af655f3cddf72
                               at /rustc/00ed4edb44ccc76d8cc992ef9f9f4634ea6d0e82/library/std/src/panicking.rs:291:9
  11:     0x77abeb072b8c - std[537910c0bd201ce8]::panicking::update_hook::<alloc[92eb594650394d8e]::boxed::Box<rustc_driver_impl[ce7c3c359a362676]::install_ice_hook::{closure#0}>>::{closure#0}
  12:     0x77abee75fb2c - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h5f454ec0e52ed414
                               at /rustc/00ed4edb44ccc76d8cc992ef9f9f4634ea6d0e82/library/alloc/src/boxed.rs:2036:9
  13:     0x77abee75fb2c - std::panicking::rust_panic_with_hook::h77fbacc29d9a7d93
                               at /rustc/00ed4edb44ccc76d8cc992ef9f9f4634ea6d0e82/library/std/src/panicking.rs:792:13
  14:     0x77abee75f8d6 - std::panicking::begin_panic_handler::{{closure}}::hfff1f5b59b8da58a
                               at /rustc/00ed4edb44ccc76d8cc992ef9f9f4634ea6d0e82/library/std/src/panicking.rs:657:13
  15:     0x77abee75d199 - std::sys_common::backtrace::__rust_end_short_backtrace::h00ea868235fbef86
                               at /rustc/00ed4edb44ccc76d8cc992ef9f9f4634ea6d0e82/library/std/src/sys_common/backtrace.rs:171:18
  16:     0x77abee75f607 - rust_begin_unwind
                               at /rustc/00ed4edb44ccc76d8cc992ef9f9f4634ea6d0e82/library/std/src/panicking.rs:645:5
  17:     0x77abee7a8446 - core::panicking::panic_fmt::h83468d22ea7ff0a1
                               at /rustc/00ed4edb44ccc76d8cc992ef9f9f4634ea6d0e82/library/core/src/panicking.rs:72:14
  18:     0x77abee7a85fc - core::panicking::panic_display::h8b6cc0415c5b118c
                               at /rustc/00ed4edb44ccc76d8cc992ef9f9f4634ea6d0e82/library/core/src/panicking.rs:256:5
  19:     0x77abee7a81ec - core::panicking::panic_str::hff617a584c04d29d
                               at /rustc/00ed4edb44ccc76d8cc992ef9f9f4634ea6d0e82/library/core/src/panicking.rs:231:5
  20:     0x77abee7a81ec - core::option::expect_failed::h843fcdeda94ac1db
                               at /rustc/00ed4edb44ccc76d8cc992ef9f9f4634ea6d0e82/library/core/src/option.rs:1994:5
  21:     0x77abeafac119 - rustc_codegen_ssa[ae02e9f47c76e5c0]::meth::expect_dyn_trait_in_self
  22:     0x77abedbff481 - <rustc_codegen_ssa[ae02e9f47c76e5c0]::meth::VirtualIndex>::get_fn::<rustc_codegen_llvm[9750cc59031b9897]::builder::Builder>.cold
  23:     0x77abe926e197 - <rustc_codegen_ssa[ae02e9f47c76e5c0]::mir::FunctionCx<rustc_codegen_llvm[9750cc59031b9897]::builder::Builder>>::codegen_terminator
  24:     0x77abed151f12 - rustc_codegen_ssa[ae02e9f47c76e5c0]::mir::codegen_mir::<rustc_codegen_llvm[9750cc59031b9897]::builder::Builder>
  25:     0x77abed13e3ce - rustc_codegen_llvm[9750cc59031b9897]::base::compile_codegen_unit::module_codegen
  26:     0x77abed13a616 - <rustc_codegen_llvm[9750cc59031b9897]::LlvmCodegenBackend as rustc_codegen_ssa[ae02e9f47c76e5c0]::traits::backend::ExtraBackendMethods>::compile_codegen_unit
  27:     0x77abed409e67 - rustc_codegen_ssa[ae02e9f47c76e5c0]::base::codegen_crate::<rustc_codegen_llvm[9750cc59031b9897]::LlvmCodegenBackend>
  28:     0x77abed2eaf34 - <rustc_codegen_llvm[9750cc59031b9897]::LlvmCodegenBackend as rustc_codegen_ssa[ae02e9f47c76e5c0]::traits::backend::CodegenBackend>::codegen_crate
  29:     0x77abed2ea89d - rustc_interface[6da10dd202fdb9b4]::passes::start_codegen
  30:     0x77abed2e9f18 - <rustc_interface[6da10dd202fdb9b4]::queries::Queries>::codegen_and_build_linker
  31:     0x77abed0c10fc - rustc_interface[6da10dd202fdb9b4]::interface::run_compiler::<core[e932fa5924b4d1b7]::result::Result<(), rustc_span[a340915128aea4cf]::ErrorGuaranteed>, rustc_driver_impl[ce7c3c359a362676]::run_compiler::{closure#0}>::{closure#1}
  32:     0x77abed072ea7 - std[537910c0bd201ce8]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[6da10dd202fdb9b4]::util::run_in_thread_with_globals<rustc_interface[6da10dd202fdb9b4]::util::run_in_thread_pool_with_globals<rustc_interface[6da10dd202fdb9b4]::interface::run_compiler<core[e932fa5924b4d1b7]::result::Result<(), rustc_span[a340915128aea4cf]::ErrorGuaranteed>, rustc_driver_impl[ce7c3c359a362676]::run_compiler::{closure#0}>::{closure#1}, core[e932fa5924b4d1b7]::result::Result<(), rustc_span[a340915128aea4cf]::ErrorGuaranteed>>::{closure#0}, core[e932fa5924b4d1b7]::result::Result<(), rustc_span[a340915128aea4cf]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[e932fa5924b4d1b7]::result::Result<(), rustc_span[a340915128aea4cf]::ErrorGuaranteed>>
  33:     0x77abed072c6a - <<std[537910c0bd201ce8]::thread::Builder>::spawn_unchecked_<rustc_interface[6da10dd202fdb9b4]::util::run_in_thread_with_globals<rustc_interface[6da10dd202fdb9b4]::util::run_in_thread_pool_with_globals<rustc_interface[6da10dd202fdb9b4]::interface::run_compiler<core[e932fa5924b4d1b7]::result::Result<(), rustc_span[a340915128aea4cf]::ErrorGuaranteed>, rustc_driver_impl[ce7c3c359a362676]::run_compiler::{closure#0}>::{closure#1}, core[e932fa5924b4d1b7]::result::Result<(), rustc_span[a340915128aea4cf]::ErrorGuaranteed>>::{closure#0}, core[e932fa5924b4d1b7]::result::Result<(), rustc_span[a340915128aea4cf]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[e932fa5924b4d1b7]::result::Result<(), rustc_span[a340915128aea4cf]::ErrorGuaranteed>>::{closure#2} as core[e932fa5924b4d1b7]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  34:     0x77abee769a1b - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::he6b356c71c632967
                               at /rustc/00ed4edb44ccc76d8cc992ef9f9f4634ea6d0e82/library/alloc/src/boxed.rs:2022:9
  35:     0x77abee769a1b - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h6c29e09c486110af
                               at /rustc/00ed4edb44ccc76d8cc992ef9f9f4634ea6d0e82/library/alloc/src/boxed.rs:2022:9
  36:     0x77abee769a1b - std::sys::pal::unix::thread::Thread::new::thread_start::h8f690723e033c81d
                               at /rustc/00ed4edb44ccc76d8cc992ef9f9f4634ea6d0e82/library/std/src/sys/pal/unix/thread.rs:108:17
  37:     0x77abe7ea955a - <unknown>
  38:     0x77abe7f26a3c - <unknown>
  39:                0x0 - <unknown>

error: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: please make sure that you have updated to the latest nightly

note: rustc 1.79.0-nightly (00ed4edb4 2024-04-17) running on x86_64-unknown-linux-gnu

note: compiler flags: -Z virtual-function-elimination=true -C lto=true -Z dump-mir-dir=dir

query stack during panic:
end of query stack
warning: 1 warning emitted


```

</p>
</details>

### PR DESCRIPTION
**Pull request by Luv-Ray**
Extract `load_vtable` function to ensure the `virtual_function_elimination` option is always checked.
It's okay not to use `llvm.type.checked.load` to load the vtable if there is no principal trait.

Fixes #123955 
Fixes #124092

### CODE REVIEW

File: tests/ui/codegen/virtual-function-elimination.rs [hunk 1]
```diff
@@ -0,0 +1,17 @@
+//@ build-pass
+//@ compile-flags: -Zvirtual-function-elimination=true -Clto=true
+//@ only-x86_64
+//@ no-prefer-dynamic
```
Comment (lcnr) [inline tests/ui/codegen/virtual-function-elimination.rs:4]: why is this argument needed?

**Review by lcnr — COMMENTED** [review]
r=me after review comment

File: tests/ui/codegen/virtual-function-elimination.rs (hunk 1 above)
Comment (Luv-Ray) [reply tests/ui/codegen/virtual-function-elimination.rs:4]: `./x test` needs this argument to perform LTO.
Below is the error message without `no-prefer-dynamic`:
```
running 1 tests

[ui] tests/ui/codegen/virtual-function-elimination.rs ... F


failures:

---- [ui] tests/ui/codegen/virtual-function-elimination.rs stdout ----

error: test compilation failed although it shouldn't!
status: exit status: 1
command: env -u RUSTC_LOG_COLOR RUSTC_ICE="0" RUST_BACKTRACE="short" "/home/ray/Desktop/rust/build/x86_64-unknown-linux-gnu/stage1/bin/rustc" "/home/ray/Desktop/rust/tests/ui/codegen/virtual-function-elimination.rs" "-Zthreads=1" "-Zsimulate-remapped-rust-src-base=/rustc/FAKE_PREFIX" "-Ztranslate-remapped-path-to-local-path=no" "-Z" "ignore-directory-in-diagnostics-source-blocks=/home/ray/.cargo" "-Z" "ignore-directory-in-diagnostics-source-blocks=/home/ray/Desktop/rust/vendor" "--sysroot" "/home/ray/Desktop/rust/build/x86_64-unknown-linux-gnu/stage1" "--target=x86_64-unknown-linux-gnu" "--check-cfg" "cfg(FALSE)" "--error-format" "json" "--json" "future-incompat" "-Ccodegen-units=1" "-Zui-testing" "-Zdeduplicate-diagnostics=no" "-Zwrite-long-types-to-disk=no" "-Cstrip=debuginfo" "-C" "prefer-dynamic" "--out-dir" "/home/ray/Desktop/rust/build/x86_64-unknown-linux-gnu/test/ui/codegen/virtual-function-elimination" "-A" "unused" "-A" "internal_features" "-Crpath" "-Cdebuginfo=0" "-Lnative=/home/ray/Desktop/rust/build/x86_64-unknown-linux-gnu/native/rust-test-helpers" "-L" "/home/ray/Desktop/rust/build/x86_64-unknown-linux-gnu/test/ui/codegen/virtual-function-elimination/auxiliary" "-Zvirtual-function-elimination=true" "-Clto=true"
stdout: none
--- stderr -------------------------------
error: cannot prefer dynamic linking when performing LTO
   |
   = note: only 'staticlib', 'bin', and 'cdylib' outputs are supported with LTO

error: aborting due to 1 previous error
------------------------------------------
```
