### PR TITLE
Warn about unknown or renamed lints in rustdoc

### LINKED ISSUE #75884: Rustdoc does not warn about unknown, renamed, or removed lints
Found in https://github.com/tokio-rs/tracing/issues/940#issuecomment-679249098.

```
$ cat broken.rs 
#![deny(x)]
$ rustdoc broken.rs  # no output
$ rustc broken.rs 
warning: unknown lint: `x`
 --> broken.rs:1:9
  |
1 | #![deny(x)]
  |         ^
  |
  = note: `#[warn(unknown_lints)]` on by default
$ rustdoc --version
rustdoc 1.45.2 (d3fb005a3 2020-07-31)
```

### PR DESCRIPTION
**Pull request by jyn514**
Fixes https://github.com/rust-lang/rust/issues/75884.
This is best reviewed one commit at a time.
r? @GuillaumeGomez

Originally I tried to do a much broader refactoring that got rid of `init_lints` altogether. My reasoning is that now the lints aren't being run anymore (after https://github.com/rust-lang/rust/pull/73566), there's no need to ignore them explicitly. But it seems there are still some lints that aren't affected by setting `lint_mod` to a no-op:

```
deny(pub_use_of_private_extern_crate)
deny(const_err)
warn(unused_imports)
```

(there are possibly more, these are just the ones that failed in the rustdoc test suite).

Some of these seem like we really should be warning about, but that's a much larger change and I don't propose to make it here. So for the time being, this just adds the `unknown_lints` and `renamed_or_removed_lints` passes to the list of lints rustdoc warns about.

### CODE REVIEW

**Comment by jyn514** [comment]
Originally I tried to do a much broader refactoring that got rid of `init_lints` altogether. My reasoning is that now the lints aren't being run anymore (after https://github.com/rust-lang/rust/pull/73566), there's no need to ignore them explicitly. But it seems there are still some lints that aren't affected by setting `lint_mod` to a no-op:

```
deny(pub_use_of_private_extern_crate)
deny(const_err)
warn(unused_imports)
```

(there are possibly more, these are just the ones that failed in the rustdoc test suite).

Some of these seem like we really should be warning about, but that's a much larger change and I don't propose to make it here. So for the time being, this just adds the `unknown_lints` and `renamed_or_removed_lints` passes to the list of lints rustdoc warns about.

File: src/librustdoc/core.rs [hunk 1]
```diff
@@ -257,7 +257,7 @@ where
         .filter_map(|lint| {
             // Permit feature-gated lints to avoid feature errors when trying to
             // allow all lints.
-            if lint.name == warnings_lint_name || lint.feature_gate.is_some() {
+            if lint.name == warnings_lint_name || lint.feature_gate.is_some() || allowed_lints.iter().any(|l| lint.name == l) {
```
Comment (GuillaumeGomez) [inline src/librustdoc/core.rs:260]: I'm surprised: normally you don't need this check here... Maybe it's because it's part of `HardwiredLints`?

Comment (jyn514) [reply src/librustdoc/core.rs:260]: Yeah, this is the thing I was confused about on discord. I'm not sure exactly why it works, just that it does.

File: src/librustdoc/core.rs [hunk 2]
```diff
@@ -257,7 +257,10 @@ where
         .filter_map(|lint| {
             // Permit feature-gated lints to avoid feature errors when trying to
             // allow all lints.
-            if lint.name == warnings_lint_name || lint.feature_gate.is_some() {
+            if lint.name == warnings_lint_name
+                || lint.feature_gate.is_some()
+                || allowed_lints.iter().any(|l| lint.name == l)
```
Comment (GuillaumeGomez) [inline src/librustdoc/core.rs:262]: Now that you're doing this check, I wonder if we still need to mark the "warnings" lint as "allowed" (meaning, not caped to "allowed" haha). Can you give it a try please?

Comment (jyn514) [reply src/librustdoc/core.rs]: Good idea, changed and all the rustdoc-ui tests pass locally :)

Comment (GuillaumeGomez) [reply src/librustdoc/core.rs]: Yeay! \o/

**Review by GuillaumeGomez — APPROVED** [review]

**Comment by GuillaumeGomez** [comment]
Thanks!

@bors: r+
