### PR TITLE
Stabilize BTree{Map,Set}::extract_if

### LINKED ISSUE #70530: Tracking Issue for {BTreeMap,BTreeSet}::drain_filter
This is a tracking issue for the Implementation of a `drain_filter` method on `BTreeMap` and `BTreeSet`, similar to the one in LinkedList and in Vec (#43244).
The feature gate for the issue is `#![feature(btree_drain_filter)]`.

### About tracking issues

Tracking issues are used to record the overall progress of implementation.
They are also uses as hubs connecting to other relevant issues, e.g., bugs or open design questions.
A tracking issue is however *not* meant for large scale discussion, questions, or bug reports about a feature.
Instead, open a dedicated issue for the specific matter and add the relevant feature gate label.

### Steps

- [ ] Implement suboptimally, relying on an `Ord` bound: efficient for simple and common cases, but falling back on a coarse restart after complicated removals.
- [ ] Possibly adjust the underlying tree representation (using `Cell`s) to cater .
- [ ] Implement all cases without relying on an `Ord` bound, tracking
- [ ] Adjust documentation ([see instructions on rustc-dev-guide][doc-guide])
- [ ] Stabilization PR ([see instructions on rustc-dev-guide][stabilization-guide])

[stabilization-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#stabilization-pr
[doc-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#documentation-prs

### Unresolved Questions
- Do we need to implement some post-panic guarantees beyond memory leaks, like the ones `Vec` and `LinkedList` provide but do not document, as I tried to discuss in #67290?

### Implementation history
- Initial suboptimal implementation #68770
- Related attempt to implement `drain` and `retain` #66747

### PR DESCRIPTION
**Pull request by rs-sac**
Tracking issue: rust-lang/rust#70530
FCP completed: https://github.com/rust-lang/rust/issues/70530#issuecomment-3191454465
Closes: rust-lang/rust#70530

### CODE REVIEW

File: src/tools/miri/tests/pass/btreemap.rs [hunk 1]
```diff
@@ -50,7 +49,7 @@ pub fn main() {
     test_all_refs(&mut 13, b.values_mut());
 
     // Test forgetting the extractor.
-    let mut d = b.extract_if(.., |_, i| *i < 30);
+    let mut d = b.extract_if::<_, std::ops::RangeFull, String>(.., |_, i| *i < 30);
```
Comment (the8472) [inline src/tools/miri/tests/pass/btreemap.rs]: Ah, interesting. I think this might be too much friction if users have to annotate the type when they're using `..` since that's a fairly common case.

Ideally we'd somehow tell type-inference here that K=Q if nothing is specified but I don't know of any way to do that. So I think that's too big a change for a stabilization PR.

Comment (rs-sac) [reply src/tools/miri/tests/pass/btreemap.rs]: Understandable.  Reverted.

**Comment by rs-sac** [comment]
@the8472 I went back to stabilization only and rebased.  Was there anything else necessary?

**Comment by rs-sac** [comment]
@the8472 It appears that the i686-msvc-1 job inexplicably got stuck for over one hour.
