### PR TITLE
Permit mutable references in all const contexts

### LINKED ISSUE #71212: Static checks for `&mut` in final value of constant with `#![feature(const_mut_refs)]`
On stable, we prevent users from creating an `&mut` that points to memory inside a `const` by forbidding the creation of mutable references during const-eval. This limitation is only temporary, see #57349. We have a feature flag, `const_mut_refs`, that allows users to create mutable references, but no attempt is made to prevent `&mut` from escaping into the final value of a `const` [like so](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=56115ed810cdfe4fb46f6db90802a6ab):

```rust
#![feature(const_mut_refs)]
const FOO: &mut i32 = &mut 4;

fn main() {
    *FOO = 2;
}
```

This errors on the current nightly, and if there were a feature gate that allowed it, we would get an ICE:

```
error: internal compiler error: src/librustc_mir/interpret/intern.rs:238: const qualif failed to prevent mutable references
```

I think we've not yet settled on the semantics we want. We're allowing them in `const fn` and relying on the borrow checker to prevent references from escaping.

### PR DESCRIPTION
**Pull request by oli-obk**
fixes #71212

cc @rust-lang/wg-const-eval @christianpoveda

### CODE REVIEW

**Comment by RalfJung** [comment]
> This also allows (with feature(const_mut_ref)) mutable references in the final value of
immutable statics, which is not a problem, because
accessing a mutable static FOO works via *&FOO, so
the intermediate immutable reference blocks any mis-use.

But what about interior mutability? Also, what is even the problem against which this is defending? Assuming the lifetimes work out, I see no reason that an `&mut` in a `static` would cause any issue. The only concern is we need to make sure that we put it into mutable memory whenever it can actually be mutated -- we should have some tests to ensure that this is the case, but I am not sure what the best way is to test for this.

> Constants prevent mutable references in their final value
via two separate means:

So, we are giving up on doing static checks here, and rely on (post-monomorphitation) "dynamic" checks?

File: src/test/ui/consts/const-mut-refs/mut_ref_in_final.rs [hunk 1]
```diff
@@ -0,0 +1,22 @@
+#![feature(const_mut_refs)]
+#![feature(const_fn)]
+#![feature(raw_ref_op)]
+const NULL: *mut i32 = std::ptr::null_mut();
+const A: *const i32 = &4;
+
+// Must not compile.
+const B: *mut i32 = &mut 4; //~ ERROR untyped pointers are not allowed in constant
```
Comment (RalfJung) [inline src/test/ui/consts/const-mut-refs/mut_ref_in_final.rs:8]: IIRC we considered dropping that "untyped pointers" check... but that would make this code compile. Doing anything bad requires `unsafe`, so that is still okay -- it is just the same as doing `&mut 4 as *mut _` at runtime and copying that raw pointer around too much. So why do you say this *must* not compile?

The thing that really must not compile is `const B: &mut i32`; I assume we already have a test for that?

**Comment by oli-obk** [comment]
> But what about interior mutability?

We already permit that on stable and it's only possible through wrapper types with `unsafe impl Sync`, so the user said it's alright.

> Also, what is even the problem against which this is defending?

Since we allow `static FOO: &mut i32 = &mut 42;` now, that could mean users can at any arbitrary point write

```rust
let x: &'static mut i32 = FOO;
let y: &'static mut i32 = FOO;
```

and then they have two mutable references to the same memory. *BUT* since we actually generate the above as


```rust
let x: &'static mut i32 = *&FOO;
let y: &'static mut i32 = *&FOO;
```

The user will get an error because you can't access a mutable reference behind an immutable referenc as mutable.

> Assuming the lifetimes work out, I see no reason that an &mut in a static would cause any issue.

Not in the current way that MIR implements static accesses, and not in the way I think we want to ever use statics, but it still something we need to protect against.

> The only concern is we need to make sure that we put it into mutable global memory whenever it can actually be mutated. Interning should already get this right, but we should have some tests to ensure that this is the case, but I am not sure what the best way is to test for this.

Why into mutable memory? You cannot safely access it mutably, and any access will go through an immutable reference, so unsafely accessing it mutably would be UB, right?

> So, we are giving up on doing static checks here, and rely on (post-monomorphitation) "dynamic" checks?

hmm... indeed. I'll read through @eddyb 's suggestion in zulip again.

File: src/test/ui/consts/const-mut-refs/mut_ref_in_final.rs (hunk 1 above)
Comment (oli-obk) [reply src/test/ui/consts/const-mut-refs/mut_ref_in_final.rs:8]: >  So why do you say this must not compile?

I think it is a good extra protection layer that prevents users from accidentally assuming that they can access this mutably via unsafe code. But we could just make that a (clippy?) lint I guess. It feels like a footgun to allow `const B: *mut i32 = &mut 4;` without complaint

**Comment by RalfJung** [comment]
> We already permit that on stable and it's only possible through wrapper types with unsafe impl Sync, so the user said it's alright.

What I meant is, `RefCell<&mut T>` should be okay... right? Your OP does not talk about this case at all.

> Since we allow static FOO: &mut i32 = &mut 42; now, that could mean users can at any arbitrary point write

Ah, right. So even if we move away again from "statics as const pointers", we have to make sure they are still treated as an *immutable* place by the borrow checker.

> Why into mutable memory? You cannot safely access it mutably, and any access will go through an immutable reference, so unsafely accessing it mutably would be UB, right?

I said "we need to make sure that we put it into mutable global memory *whenever it can actually be mutated*" (emphasis is new). Like for example in case of `RefCell<&mut T>`. I think our code does this right, but it is a case worth carefully documenting and thinking through, that's why I brought it up.

File: src/test/ui/consts/const-mut-refs/mut_ref_in_final.rs (hunk 1 above)
Comment (RalfJung) [reply src/test/ui/consts/const-mut-refs/mut_ref_in_final.rs:8]: > I think it is a good extra protection layer that prevents users from accidentally assuming that they can access this mutably via unsafe code. 

Right, I agree with that. But by saying "must", the comment makes it sound like this is a soundness concern, which I think is not. If you code tone down the comment to what you said here, I am happy. :)

**Comment by oli-obk** [comment]
> What I meant is, `RefCell<&mut T>` should be okay... right? Your OP does not talk about this case at all.

Well, not `RefCell` per se, but a custom `Sync` type could work from a type-system perspective. It will still not work though.

```rust
use core::cell::UnsafeCell;
struct NotAMutex<T>(UnsafeCell<T>);

unsafe impl<T> Sync for NotAMutex<T> {}

const FOO: NotAMutex<&i32> = NotAMutex(UnsafeCell::new(&42));
```

The above only works, because `&42` is promoted. I think if you could move to `&mut` (like in this PR), you'd get borrow errors. You can emulate the effect on nightly with immutable references by using a block:

```rust
const FOO: NotAMutex<&i32> = NotAMutex(UnsafeCell::new(&{
    let x = 42;
    x
}));
```

I'll write appropriate tests and post my findings here.

**Comment by oli-obk** [comment]
I added a new test for your example, and as I expected, it is not possible to do that, so we do not need to check whether interning can handle this.

**Comment by RalfJung** [comment]
What about using `&mut STATIC_MUT`?

**Comment by oli-obk** [comment]
For constants that is not possible anyway (yes, this time it is really a static check ;) ).

For static items, it's not a problem, as the allocation behind the reference is not part of the static currently being interned. For all other concerns, accessing a mutable static requires `unsafe`, so the user is the one who has to prove correctness.

File: src/test/ui/consts/const-mut-refs/mut_ref_in_final_ok.rs [hunk 2]
```diff
@@ -0,0 +1,22 @@
...
+#![feature(const_fn)]
+#![feature(raw_ref_op)]
+
+use std::cell::UnsafeCell;
+struct NotAMutex<T>(UnsafeCell<T>);
+
+unsafe impl<T> Sync for NotAMutex<T> {}
+
+const FOO: NotAMutex<&mut i32> = NotAMutex(UnsafeCell::new(&mut 42));
+//~^ ERROR temporary value dropped while borrowed
```
Comment (RalfJung) [inline src/test/ui/consts/const-mut-refs/mut_ref_in_final_ok.rs:11]: Could you add the same test also for a `static` and a `static mut`?

**Comment by RalfJung** [comment]
Hm, I am running out of ideas.^^ Would unleashing Miri let us disable some of these restrictions?

I feel like there probably are or will be other ways to get `&mut`, such as transmuting `&UnsafeCell<T>` to `&mut T` or `Box::leak` or so... I think our code should handle this all correctly, so I would much rather rely on the interner being correct than relying on it being impossible to write such code. You invoked several otherwise independent invariants to crush my counterexamples, which makes this all seem rather fragile.

In particular you invoked the const-may-not-point-to-static restriction, which only exists for the benefit of const-in-pattern and which rejects way more code that it would have to. If, hypothetically, we'd instead dynamically check this only when a const is actually used in a pattern, your scheme here does not work any more. I have a plan for how to make that restriction not load-beaing any more (when constructing a valtree, ensure we only read from immutable allocations; make patterns go through valtrees). I think we should be careful not to add anything else that would make this restriction load-bearing in different ways.

File: src/test/ui/consts/const-mut-refs/mut_ref_in_final_ok.rs (hunk 2 above)
Comment (RalfJung) [reply src/test/ui/consts/const-mut-refs/mut_ref_in_final_ok.rs:11]: Also why is this a separate test from `mut_ref_in_final.rs`? The "ok" in the filename does not even make much sense, there is an ERROR here after all.

File: src/test/ui/consts/const-mut-refs/mut_ref_in_final_ok.rs [hunk 3]
```diff
@@ -0,0 +1,22 @@
...
+
+// `BAR` works, because `&42` promotes immediately instead of relying on
+// "final value lifetime extension".
```
Comment (RalfJung) [inline src/test/ui/consts/const-mut-refs/mut_ref_in_final_ok.rs:14]: I think we call it the "enclosing scope rule" in our docs.

File: src/test/ui/consts/const-mut-refs/mut_ref_in_final.rs [hunk 4]
```diff
@@ -0,0 +1,24 @@
+#![feature(const_mut_refs)]
+#![feature(const_fn)]
+#![feature(raw_ref_op)]
+const NULL: *mut i32 = std::ptr::null_mut();
+const A: *const i32 = &4;
+
+// It could be made sound to allow it to compile,
+// but we do not want to allow this to compile,
+// as that would be an enormous footgun in oli-obk's opinion.
+const B: *mut i32 = &mut 4; //~ ERROR untyped pointers are not allowed in constant
```
Comment (RalfJung) [inline src/test/ui/consts/const-mut-refs/mut_ref_in_final.rs:10]: I think this is exactly my main concern here... there are legitimate contsants that are disallowed by the same check, such as
```rust
const CONST_RAW: *const Vec<i32> = &Vec::new() as *const _;
```
So your proposed PR here makes it very very hard to ever allow `CONST_RAW`. It is basically closing a door.

**Comment by RalfJung** [comment]
> when there is an UnsafeCell or "hidden pointers", we correctly intern allocations referenced inside there as mutable

Btw, there is a funny corner case here where the same allocation is referenced multiple times, so it might end up immutable from the first reference we encounter to it and then later another reference wants it to be mutable... something like
```rust
static EVIL: (&i32, *mut i32) = {
  let x: &mut i32 = Box::leak(Box::new(0)); // let's just imagine some way to get an &'static mut
  (x, x)
};
```
One could argue that if `x.0` is never used, writing to `x.1` is actually fine...

File: src/test/ui/consts/const-mut-refs/mut_ref_in_final.rs [hunk 5]
```diff
@@ -0,0 +1,24 @@
...
+
+// Could be ok, but the same analysis that prevents the mutable one above will also bail out here
+// Using a block with some complex content, because just `&45` would get promoted,
+// which is not what we want to test here.
+const C: *const i32 = &{ //~ ERROR untyped pointers are not allowed in constant
+    let mut x = 42;
+    x += 3;
+    x
+};
+
```
Comment (RalfJung) [inline src/test/ui/consts/const-mut-refs/mut_ref_in_final.rs:20]: Could you add tests for what you said in the PR description, "Some(&mut 42) is not ok, while None::<&mut i32> is"?

**Comment by RalfJung** [comment]
Sorry for all the rambling, but I feel *very* uneasy about this change.^^ I don't think the required soundness conditions and the checks that uphold them have been documented clearly enough. We shouldn't start with examples, we should start with "here is a list of conditions that, if they are all met, we agree are sufficient to make this all sound", and then we should go on with "here are some checks that ensure that all conditions are met", and *then* we can come up with testcases to try to beak them.

**Comment by oli-obk** [comment]
> We shouldn't start with examples, we should start with "here is a list of (dynamic) conditions that, if they are all met, we agree are sufficient to make this all sound", and then we should go on with "here are some (static and/or dynamic) checks that ensure that all conditions are met", and then we can come up with testcases to try to beak them.

I think part of this is because, as you correctly noted, we are mixing a lot of different concerns. E.g. I consider it ok for the dynamic checks to permit `const FOO: *mut i32 = &mut 42;` since, that is not a soundness issue, just a footgun. Obviously the static checks must at least cover all dynamic checks, but we don't just need to cover "too hard to statically check" in addition, we can also add static checks to prevent footguns.

> One could argue that if EVIL.0 is never used, writing to EVIL.1 is actually fine...

I thought we had to consider all references to be used, no matter if they actually are. I don't see how having a shared reference to some memory that is mutated through other means is fine, but a reference to dangling memory is not.

The only way that example seems doable to me is to use `*const i32` instead of `&i32`, and then we can't intern immutably anyway.

File: src/test/ui/consts/const-mut-refs/mut_ref_in_final_ok.rs (hunk 3 above)
Comment (oli-obk) [reply src/test/ui/consts/const-mut-refs/mut_ref_in_final_ok.rs:14]: This comment was meant to explain why the situation is different from the other situations in the same file. Thus I brought it up again.

File: src/test/ui/consts/const-mut-refs/mut_ref_in_final.rs (hunk 4 above)
Comment (oli-obk) [reply src/test/ui/consts/const-mut-refs/mut_ref_in_final.rs:10]: I'm currently looking into creating static checks similar to the interior mutability checks. This spawned off https://github.com/rust-lang/rust/pull/78679.

**Comment by RalfJung** [comment]
> I thought we had to consider all references to be used, no matter if they actually are. I don't see how having a shared reference to some memory that is mutated through other means is fine, but a reference to dangling memory is not.

Well, the following is allowed under Stacked Borrows in runtime code:
```rust
    let x: *mut i32 = unsafe { &mut FOO };
    let (_, x) = (unsafe { &*x }, SyncRawPtr(x));
    unsafe { *x = 1; }
```
Basically, the lifetime of the shared reference ends immediately, that's why this is okay. (It would also be permitted to dangle.) The guarantee of a shared ref is that *between any two of its uses*, nothing has been mutated, but if the shared ref is unused... well, this guarantee doesn't do anything.

I think to obtain the behavior you seem to expect, we'd need to somehow reflect the idea that "the 'static lifetime goes on forever" into Stacked Borrows, making sure the tag of the shared reference never gets popped... but we don't actually have any tags in compile-time computed pointers so this cannot really work.^^ Indeed having provenance somehow connect compile-time and run-time computations seems tricky (and strange), but if we make compile-time-computed pointers have *no* provenance, that automatically means there is no way to distinguish different compile-time computed pointers to the same data.

**Comment by oli-obk** [comment]
So... "must be unused" is actually not true here? We could alternately use the reference to read and the `SyncRawPtr` to write, as long as we don't keep a reference around while using `SyncRawPtr`? At least from a stacked borrows perspective.

**Comment by oli-obk** [comment]
Sorry, all of this is getting a bit off topic, but I really want to understand the details even if irrelevant to this PR. Should we take it to some other place?

I fully agree that we should not intern an allocation as immutable if some later place wants to intern it as mutable.

Though, in the case you showed, we won't intern anything anyway, as that is a pointer to a mutable static, which by itself is already a mutable allocation. But for hyptothetical heap allocations, this could definitely occur.

**Comment by RalfJung** [comment]
Right, sorry, I was somewhat distracted this morning and did not have enough time to reply properly. I still don't really have enough time...

So in terms of soundness, if all "inner" static allocations are interned mutable and hidden pointers are not allowed in `const`, I think I can agree that this is all sound. I just did not agree with the *reasons* you gave for soundness above, namely that how `&mut` can appear in `static` is restricted... that was never a soundness goal so far, so I do not think it should become one now. But I think it is not necessary, if interning does the right thing.

So my main soundness concerns are around
* Interning inner static allocations as immutable: we need to be really sure that this is indeed correct. I wonder if validity checking can help here... probably not because of raw pointers.
* Can we do this in a way that leaves the door open for "hidden pointers" in a const without being a huge footgun? A lint is likely to have many false positives, which is not great.

**Comment by RalfJung** [comment]
After thinking about this some more, I wonder if there isn't another approach -- given my inability to come up with an example that has mutable memory in an inner static allocation. We could say that all inner allocations of `static` (and `static mut`) are interned immutably. We'd have to add some tests to make sure that this holds up when with Miri-unleashed (and validation might be able to help by detecting `UnsafeCell`), but if it does it would let us remove all the type-based interning and instead just intern all inner allocations of everything immutably, which would be a great simplification.

@oli-obk almost convinced me that this could be sound for current CTFE, though I'd need to think about this some more. It would clearly not be sound with heap allocations during CTFE, but those are easily recognized and we could just always intern them mutably.

**Comment by oli-obk** [comment]
I can unconvince you in a single line that works on stable:

```rust
static mut FOO: &mut [u32] = &mut [5, 3, 4];
```

your mention of `static mut` reminded me that we have this special case for slices in mutable statics. Maybe I should finally create the future incompat lint [removing `static mut` from the language](https://github.com/rust-lang/rust/issues/53639)?

**Comment by RalfJung** [comment]
> I can unconvince you in a single line that works on stable:

Isn't that just because https://github.com/rust-lang/rust/pull/75585 did not arrive on stable yet?

**Comment by RalfJung** [comment]
Ah no, it works even on nightly, because this is the "enclosing scope rule" for mutable references. Shame.

Well we could just intern all allocations in a `static mut` as mutable and all allocations in everything else as immutable...

**Comment by oli-obk** [comment]
Agreed, let's just be conservative in `static mut`, then we can get rid of the type based check (mostly, the outer one still needs to check for freeze, but that's it, no walking any fields or anything)

**Comment by RalfJung** [comment]
> the outer one still needs to check for freeze

Ah, good point.

I am onboard for that plan, but then we should also augment validation to... reject `UnsafeCell` in inner allocations of all `statics`, or is that not right? Or maybe instead of checking the inner/outer thing, really what we should do is ensure that `UnsafeCell` only ever exist in *mutable allocations*... except for the topmost allocation of a `const`, which is special because we know it ill only ever be copied, not accessed by reference.

**Comment by oli-obk** [comment]
I rewrote the PR to make it work exactly like #78578 works for immutable references to interior mutability. This change resolves all of the weird situations around mutable references in statics and the promotion issues discussed for `static mut`

**Comment by RalfJung** [comment]
@oli-obk that was a self-reference, did you mean to link to https://github.com/rust-lang/rust/pull/80418?

**Comment by oli-obk** [comment]
oops yes. This PR does the same thing, so we can discuss the scheme fully in the other PR and thus not create duplicate discussions.

**Comment by oli-obk** [comment]
@RalfJung do you have the nerve for another one of these? This PR is pretty much the same as  #80418, but for mutable references. Since the messages above I adjusted it to make that statement more true

File: compiler/rustc_mir/src/transform/check_consts/ops.rs [hunk 6]
```diff
@@ -268,43 +268,41 @@ impl NonConstOp for CellBorrow {
...
 impl NonConstOp for MutBorrow {
     fn status_in_item(&self, ccx: &ConstCx<'_, '_>) -> Status {
-        // Forbid everywhere except in const fn with a feature gate
-        if ccx.const_kind() == hir::ConstContext::ConstFn {
-            Status::Unstable(sym::const_mut_refs)
-        } else {
-            Status::Forbidden
+        match ccx.const_kind() {
+            // Mutable statics can handle mutable references in their final value
+            hir::ConstContext::Static(hir::Mutability::Mut) => Status::Allowed,
```
Comment (RalfJung) [inline compiler/rustc_mir/src/transform/check_consts/ops.rs:280]: Shouldn't this *at least* have a feature gate? Also I could not find a testcase for this.
Mutability is tricky, so it's not immediately obvious to me that this is right.^^

File: src/test/ui/check-static-immutable-mut-slices.stderr [hunk 7]
```diff
@@ -1,8 +1,8 @@
-error[E0764]: mutable references are not allowed in statics
+error[E0764]: mutable references are not allowed in final value of statics
```
Comment (RalfJung) [inline src/test/ui/check-static-immutable-mut-slices.stderr:1]: "in the final value" would be more grammatical, I think.

File: src/test/ui/consts/const-mut-refs/mut_ref_in_final.rs [hunk 8]
```diff
@@ -0,0 +1,24 @@
...
+#![feature(raw_ref_op)]
+const NULL: *mut i32 = std::ptr::null_mut();
+const A: *const i32 = &4;
+
+// It could be made sound to allow it to compile,
+// but we do not want to allow this to compile,
+// as that would be an enormous footgun in oli-obk's opinion.
+const B: *mut i32 = &mut 4; //~ ERROR mutable references are not allowed
+
+// Could be ok, but the same analysis that prevents the mutable one above will also bail out here
```
Comment (RalfJung) [inline src/test/ui/consts/const-mut-refs/mut_ref_in_final.rs:12]: The comment seems to contradict reality, as that same analysis does not bail below.^^

File: src/test/ui/consts/const-mut-refs/mut_ref_in_final.rs (hunk 5 above)
Comment (RalfJung) [reply src/test/ui/consts/const-mut-refs/mut_ref_in_final.rs:20]: This comment seems to still be open?

File: src/test/ui/consts/const-mut-refs/mut_ref_in_final_ok.rs (hunk 2 above)
Comment (RalfJung) [reply src/test/ui/consts/const-mut-refs/mut_ref_in_final_ok.rs:11]: Same, this comment seems to still be open.

File: src/test/ui/consts/const-mut-refs/mut_ref_in_final_ok.rs (hunk 3 above)
Comment (RalfJung) [reply src/test/ui/consts/const-mut-refs/mut_ref_in_final_ok.rs:14]: Okay, I see. But please use consistent terminology.

File: src/test/ui/consts/projection_qualif.rs [hunk 9]
```diff
@@ -7,7 +7,7 @@ use std::cell::Cell;
 const FOO: &u32 = {
```
Comment (RalfJung) [inline src/test/ui/consts/projection_qualif.rs:7]: FWIW, I do not understand the filename of this test... but that is pre-existing.

File: src/test/ui/consts/read_from_static_mut_ref.rs [hunk 10]
```diff
@@ -1,9 +1,8 @@
-// We are keeping this test in case we decide to allow mutable references in statics again
 #![feature(const_mut_refs)]
 #![allow(const_err)]
 
-static OH_NO: &mut i32 = &mut 42;
-//~^ ERROR mutable references are not allowed in statics
+static OH_NO: &mut i32 = &mut 42; //~ ERROR mutable references are not allowed
 fn main() {
     assert_eq!(*OH_NO, 42);
+    *OH_NO = 43; //~ ERROR cannot assign to `*OH_NO`, as `OH_NO` is an immutable static
```
Comment (RalfJung) [inline src/test/ui/consts/read_from_static_mut_ref.rs:7]: Shouldn't the filename be "write to static mut ref"?

File: compiler/rustc_mir/src/transform/check_consts/ops.rs (hunk 6 above)
Comment (oli-obk) [reply compiler/rustc_mir/src/transform/check_consts/ops.rs]: I undid this, it's not necessary, it was only relevant in the old dataflow scheme, not in this new scheme.

**Comment by RalfJung** [comment]
r? @RalfJung
@rustbot modify labels: -S-waiting-on-review +S-waiting-on-author
(There are some unresolved comments at the top of the discussion; as far as I can see they still apply.)

File: src/test/ui/consts/const-mut-refs/mut_ref_in_final.rs [hunk 11]
```diff
@@ -0,0 +1,68 @@
...
+    // This code never gets executed, because the static checks fail before that.
+    Some(&mut *(42 as *mut i32))
+} }
+// Check that we do not look into function bodies.
+// We treat all functions as not returning a mutable reference, because there is no way to
+// do that without causing the borrow checker to complain (see the B5/helper2 test below).
+const B4: Option<&mut i32> = helper();
+
+const fn helper2(x: &mut i32) -> Option<&mut i32> { Some(x) }
+const B5: Option<&mut i32> = helper2(&mut 42); //~ ERROR temporary value dropped while borrowed
```
Comment (oli-obk) [inline src/test/ui/consts/const-mut-refs/mut_ref_in_final.rs:32]: I'm not too happy with `B4`... but also not sure what else to do here. We could start running checks on the return type of functions, but I'm not sure how to do that properly, especially once generics are involved.

Comment (RalfJung) [reply src/test/ui/consts/const-mut-refs/mut_ref_in_final.rs:32]: > because the static checks fail before that

Why is there no `//~ ERROR` here then?
What if you do `Some(&mut *(&mut 42 as *mut i32))` instead?

Comment (oli-obk) [reply src/test/ui/consts/const-mut-refs/mut_ref_in_final.rs:32]: the static checks on other constants fail. This code will work and then error in validation if we were getting this far, but since everything else erros first, and B4 is not used, it isn't evaluated.

Comment (oli-obk) [reply src/test/ui/consts/const-mut-refs/mut_ref_in_final.rs:32]: > What if you do Some(&mut *(&mut 42 as *mut i32)) instead?

that would just give us a dangling pointer, but still not get to validation. I could put this test in a separate file, then we would get to validation.

Comment (RalfJung) [reply src/test/ui/consts/const-mut-refs/mut_ref_in_final.rs:32]: Oh, the static checks *in other consts* fail.

Looks like this test needs its own file then.

> that would just give us a dangling pointer, but still not get to validation. I could put this test in a separate file, then we would get to validation.

Sure, I meant to test that in addition to B4, not instead of.

Comment (oli-obk) [reply src/test/ui/consts/const-mut-refs/mut_ref_in_final.rs:32]: done
