### PR TITLE
Provide a better error and a suggestion for `Fn` traits with lifetime params

### LINKED ISSUE #103490: Recover from malformed trait bounds of the form `Fn<'a>()`
The following code:

```rust
fn f(_: impl FnOnce<'a>(&'a str) -> bool) {}
```

currently produces a heap of semi-helpful diagnostics:

<details>
<summary><b>stderr (7 errors)</b></summary>

```
error: unexpected lifetime `'a` in pattern
 --> src/lib.rs:1:26
  |
1 | fn f(_: impl FnOnce<'a>(&'a str) -> bool) {}
  |                          ^^ help: remove the lifetime

error: expected one of `:` or `|`, found `->`
 --> src/lib.rs:1:34
  |
1 | fn f(_: impl FnOnce<'a>(&'a str) -> bool) {}
  |                                  ^^ expected one of `:` or `|`

error: expected one of `)`, `+`, `,`, or `::`, found `(`
 --> src/lib.rs:1:24
  |
1 | fn f(_: impl FnOnce<'a>(&'a str) -> bool) {}
  |                        ^
  |                        |
  |                        expected one of `)`, `+`, `,`, or `::`
  |                        help: missing `,`

error[E0261]: use of undeclared lifetime name `'a`
 --> src/lib.rs:1:21
  |
1 | fn f(_: impl FnOnce<'a>(&'a str) -> bool) {}
  |                     ^^ undeclared lifetime
  |
  = note: for more information on higher-ranked polymorphism, visit https://doc.rust-lang.org/nomicon/hrtb.html
help: consider making the bound lifetime-generic with a new `'a` lifetime
  |
1 | fn f(_: impl for<'a> FnOnce<'a>(&'a str) -> bool) {}
  |              +++++++
help: consider introducing lifetime `'a` here
  |
1 | fn f<'a>(_: impl FnOnce<'a>(&'a str) -> bool) {}
  |     ++++

error[E0658]: the precise format of `Fn`-family traits' type parameters is subject to change
 --> src/lib.rs:1:14
  |
1 | fn f(_: impl FnOnce<'a>(&'a str) -> bool) {}
  |              ^^^^^^^^^^ help: use parenthetical notation instead: `FnOnce() -> ()`
  |
  = note: see issue #29625 <https://github.com/rust-lang/rust/issues/29625> for more information

error[E0107]: this trait takes 0 lifetime arguments but 1 lifetime argument was supplied
 --> src/lib.rs:1:14
  |
1 | fn f(_: impl FnOnce<'a>(&'a str) -> bool) {}
  |              ^^^^^^---- help: remove these generics
  |              |
  |              expected 0 lifetime arguments

error[E0107]: this trait takes 1 generic argument but 0 generic arguments were supplied
 --> src/lib.rs:1:14
  |
1 | fn f(_: impl FnOnce<'a>(&'a str) -> bool) {}
  |              ^^^^^^ expected 1 generic argument
  |
help: add missing generic argument
  |
1 | fn f(_: impl FnOnce<'a, Args>(&'a str) -> bool) {}
  |                       ++++++
```

</details>

when instead we could special-case this and emit a single (or at least fewer) diagnostic that suggests the following:

```patch
- impl FnOnce<'a>(&'a str) -> bool
+ impl for<'a> FnOnce(&'a str) -> bool
```

---

If the bound in not inside `impl Trait`, like in:

```rust
fn f<F>(_: F) where F: FnOnce<'a>(&'a str) -> bool {}
```

we currently emit the following:

```
error: expected one of `+`, `,`, `::`, or `{`, found `(`
 --> src/lib.rs:1:34
  |
1 | fn f<F>(_: F) where F: FnOnce<'a>(&'a str) -> bool {}
  |                                  ^ expected one of `+`, `,`, `::`, or `{`

```

which is less verbose for sure but still, we should provide the same suggestion I propose above.

Related issue: #103487.

@rustbot label A-parser A-suggestion-diagnostics D-newcomer-roadblock

### PR DESCRIPTION
**Pull request by ohno418**
Given `Fn`-family traits with lifetime params in trait bounds like `fn f(_: impl Fn<'a>(&'a str) -> bool)`, we currently produce many unhelpful errors.

This PR allows these situations to suggest simply using Higher-Rank Trait Bounds like `for<'a> Fn(&'a str) -> bool`.

Fixes https://github.com/rust-lang/rust/issues/103490.

### CODE REVIEW

**Comment by fmease** [comment]
Probably best reviewed by a member of the diagnostics working group.
r? diagnostics

File: compiler/rustc_parse/src/parser/ty.rs [hunk 1]
```diff
@@ -911,8 +911,13 @@ impl<'a> Parser<'a> {
         has_parens: bool,
         modifiers: BoundModifiers,
     ) -> PResult<'a, GenericBound> {
-        let lifetime_defs = self.parse_late_bound_lifetime_defs()?;
-        let path = self.parse_path(PathStyle::Type)?;
+        let mut lifetime_defs = self.parse_late_bound_lifetime_defs()?;
+        let mut path = self.parse_path(PathStyle::Type)?;
+
+        if self.token == TokenKind::OpenDelim(Delimiter::Parenthesis) {
```
Comment (fmease) [inline compiler/rustc_parse/src/parser/ty.rs:917]:
```suggestion
        if self.may_recover() && self.token == TokenKind::OpenDelim(Delimiter::Parenthesis) {
```

To avoid stepping into #103534 territory.

File: compiler/rustc_parse/src/parser/ty.rs [hunk 2]
```diff
@@ -955,6 +960,94 @@ impl<'a> Parser<'a> {
...
 
+    /// Recover from `Fn`-family traits (Fn, FnMut, FnOnce) with lifetime arguments
+    /// (e.g. `FnOnce<'a>(&'a str) -> bool`). Up to generic arguments have already
+    /// been eaten.
+    fn recover_fn_trait_with_lifetime_params(
+        &mut self,
+        fn_path: &mut ast::Path,
+        lifetime_defs: &mut Vec<GenericParam>,
+    ) -> PResult<'a, ()> {
+        let Some(fn_path_segment) = fn_path.segments.last_mut() else {
```
Comment (fmease) [inline compiler/rustc_parse/src/parser/ty.rs:971]: You could just use `.unwrap()` here instead of `let`/`else`.

File: compiler/rustc_parse/src/parser/ty.rs [hunk 3]
```diff
@@ -955,6 +960,94 @@ impl<'a> Parser<'a> {
...
+                    .collect()
+            } else {
+                Vec::new()
+            };
+        // Only try to recover if the trait has lifetime params.
+        if lifetimes.is_empty() {
+            return Ok(());
+        }
+
+        // Parse `(T, U) -> R`.
```
Comment (fmease) [inline compiler/rustc_parse/src/parser/ty.rs:1004]: Couldn't you replace all of the following with `self.parse_fn_decl(…)` or am I missing something?

File: compiler/rustc_parse/src/parser/ty.rs [hunk 4]
```diff
@@ -955,6 +960,94 @@ impl<'a> Parser<'a> {
...
+        let generic_args_span = generic_args.span();
+        let mut err =
+            self.struct_span_err(generic_args_span, "Fn traits cannot take lifetime parameters");
+        let snippet = format!(
+            "for<{}> ",
+            lifetimes.iter().map(|lt| lt.ident.as_str()).intersperse(", ").collect::<String>(),
+        );
+        let before_fn_path = fn_path.span.shrink_to_lo();
+        err.multipart_suggestion(
+            "consider using a Hier-Rank Trait Bound instead",
```
Comment (fmease) [inline compiler/rustc_parse/src/parser/ty.rs:1043]:
```suggestion
            "consider using a higher-ranked trait bound instead",
```

**Review by fmease — CHANGES_REQUESTED** [review]
Thanks for working on this! I have some suggestions.

File: compiler/rustc_parse/src/parser/ty.rs [hunk 5]
```diff
@@ -955,6 +960,94 @@ impl<'a> Parser<'a> {
...
+                is_placeholder: false,
+                kind: ast::GenericParamKind::Lifetime,
+                colon_span: None,
+            })
+            .collect::<Vec<GenericParam>>();
+        lifetime_defs.append(&mut generic_params);
+
+        let generic_args_span = generic_args.span();
+        let mut err =
+            self.struct_span_err(generic_args_span, "Fn traits cannot take lifetime parameters");
```
Comment (estebank) [inline compiler/rustc_parse/src/parser/ty.rs:1036]:
```suggestion
            self.struct_span_err(generic_args_span, "`Fn` traits cannot take lifetime parameters");
```

File: compiler/rustc_parse/src/parser/ty.rs (hunk 1 above)
Comment (ohno418) [reply compiler/rustc_parse/src/parser/ty.rs:917]: Great. Thanks!

File: compiler/rustc_parse/src/parser/ty.rs (hunk 2 above)
Comment (ohno418) [reply compiler/rustc_parse/src/parser/ty.rs:971]: Thanks, I've tried. But I think it'll be more difficult to get `inputs_span` when using `parse_fn_decl`:

```rust
// Here, inputs refers their own spans, but not include "(" and ")".
let ast::FnDecl { inputs, output } = self.parse_fn_decl(...)?.into_inner();
```

Any better way here?

File: compiler/rustc_parse/src/parser/ty.rs (hunk 3 above)
Comment (ohno418) [reply compiler/rustc_parse/src/parser/ty.rs:1004]: Thanks, I've tried. But I think it'll be more difficult to get `inputs_span` when using `parse_fn_decl`:

```rust
// Here, `inputs` refer to their own spans, but do not include "(" and ")".
let ast::FnDecl { inputs, output } = self.parse_fn_decl(...)?.into_inner();
```

Any better way here?

**Comment by ohno418** [comment]
@fmease @estebank 
Thank you for the reviews! Updated.

File: compiler/rustc_parse/src/parser/ty.rs (hunk 3 above)
Comment (estebank) [reply compiler/rustc_parse/src/parser/ty.rs:1001]: What you can do instead then is to take `self.token.span` or `self.prev_token.span` and create a new one (`lo.to(hi)`) that does cover the parens, and rely on the existing parsing logic. Alternatively, you might want to change `inputs` to include the parens (and check the test suite to see if that causes any regressions).

Comment (ohno418) [reply compiler/rustc_parse/src/parser/ty.rs:1001]: @estebank 
Sorry, I'm getting a little confused.

> What you can do instead then is to take self.token.span or self.prev_token.span and create a new one (lo.to(hi)) that does cover the parens,

Given `Fn<'a>(&'a str) -> bool`, for example, we're trying to get the span referring to `(&'a str)` to use as the `inputs_span` in the `ast::ParenthesizedArgs`. But `parse_fn_decl()` eats `(&'a str) -> bool`, so `self.prev_token.span` refers to `bool` after that.

> Alternatively, you might want to change inputs to include the parens

I'm not sure I understand this. The type of the `inputs` field in the `FnDecl` struct, which is returned from `parse_fn_decl()`, is a `Vec` of input params. So I think it's difficult to change `inputs` to include the parens.

Comment (ohno418) [reply compiler/rustc_parse/src/parser/ty.rs:1001]: I'm wondering if we change the visibility of `parse_fn_params` to `pub(super)` and use it to parse the input params here. It'll be more simple and readable than `self.parse_paren_comma_seq(|p| p.parse_ty())`, and may work well because easy to get `inputs_span`. I think this visibility change is consistent because `parse_ret_ty` has `pub(super)` visibility too.

Comment (estebank) [reply compiler/rustc_parse/src/parser/ty.rs:1001]: Yes, changing visibility in that way is reasonable

Comment (ohno418) [reply compiler/rustc_parse/src/parser/ty.rs:1001]: Thanks! Changed.

**Comment by ohno418** [comment]
@estebank
Hi, could you please take another look at this?

File: compiler/rustc_parse/src/parser/ty.rs [hunk 6]
```diff
@@ -955,6 +960,92 @@ impl<'a> Parser<'a> {
...
+    /// been eaten.
+    fn recover_fn_trait_with_lifetime_params(
+        &mut self,
+        fn_path: &mut ast::Path,
+        lifetime_defs: &mut Vec<GenericParam>,
+    ) -> PResult<'a, ()> {
+        let fn_path_segment = fn_path.segments.last_mut().unwrap();
+        let generic_args = if let Some(p_args) = &fn_path_segment.args {
+            p_args.clone().into_inner()
+        } else {
```
Comment (estebank) [inline compiler/rustc_parse/src/parser/ty.rs:974]: This can now be

```suggestion
        let Some(p_args) = &fn_path_segment.args {
            p_args.clone().into_inner()
        } else {
```

**Review by estebank — APPROVED** [review]
r=me after rebase

File: compiler/rustc_parse/src/parser/ty.rs (hunk 6 above)
Comment (ohno418) [reply compiler/rustc_parse/src/parser/ty.rs:1035]: Is this valid syntax? I got the following error:
```
error: expected one of `(`, `.`, `::`, `;`, `?`, `else`, or an operator, found `{`
    --> compiler/rustc_parse/src/parser/ty.rs:1033:50
     |
1033 |         let Some(p_args) = &fn_path_segment.args {
     |                                                  ^ expected one of 7 possible tokens

error: could not compile `rustc_parse` due to previous error
warning: build failed, waiting for other jobs to finish...
error: could not compile `rustc_parse` due to previous error
```

Comment (fmease) [reply compiler/rustc_parse/src/parser/ty.rs:1035]: With `let`/`else` syntax, it's

```rust
let Some(p_args) = &fn_path_segment.args else {
    // ... ... ...
    return Ok(());
};
let p_args = p_args.clone().into_inner();
```

or

```rust
let Some(p_args) = fn_path_segment.args.cloned().map(|arg| arg) else {
    // ... ... ...
    return Ok(());
};
```

or

```rust
let Some(p_args) = fn_path.segments
    .last_mut()
    .unwrap()
    .args
    .cloned()
    .map(|arg| arg)
else {
    // ... ... ...
    return Ok(());
};
```

at your choosing.

Comment (estebank) [reply compiler/rustc_parse/src/parser/ty.rs:1035]: Ah, yeah, I mistyped what I meant. Thanks @fmease for clarifying it
