### PR TITLE
Fix atan2 inaccuracy in documentation

### LINKED ISSUE #136275: `f64::atan2` documentation error
### Location

`library/std/src/f64.rs:793`

### Summary

The `f64::atan2` function documentation specifies that the output could be in the range `(-PI, PI]`. However its not true. It could return `-PI` as well.
Following is from the function documentation:
> ```
> /// * `x = 0`, `y = 0`: `0`
> /// * `x >= 0`: `arctan(y/x)` -> `[-pi/2, pi/2]`
> /// * `y >= 0`: `arctan(y/x) + pi` -> `(pi/2, pi]`
> /// * `y < 0`: `arctan(y/x) - pi` -> `(-pi, -pi/2)`
> ```

Example case:
`f64::atan2(-0.0, -1.0)` returns `-f64::PI`

### PR DESCRIPTION
**Pull request by DimitriiTrater**
Fixes rust-lang/rust#136275

### CODE REVIEW

**Review by GrigorenkoPV — COMMENTED** [review]
Maybe it would make more sense to rephrase the existing part in terms of `>= +0.0` and `<= -0.0` instead of adding a new section?

*[View changes since this review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/rust/146451/76c5ed2847cdb26ef2822a3a165d710f6b772217..a6f181d0f80561de414a8a0e6770b82494a73c52)*

**Comment by GrigorenkoPV** [comment]
Yes, this is what I had in mind, more or less. Though, probably with the sign included in the output too.

Also, not sure if the `pi` should be changed to `π` here.

File: library/std/src/num/f128.rs [hunk 1]
```diff
@@ -557,10 +557,10 @@ impl f128 {
...
     /// Computes the four quadrant arctangent of `self` (`y`) and `other` (`x`) in radians.
     ///
-    /// * `x = 0`, `y = 0`: `0`
-    /// * `x >= 0`: `arctan(y/x)` -> `[-pi/2, pi/2]`
-    /// * `y >= 0`: `arctan(y/x) + pi` -> `(pi/2, pi]`
-    /// * `y < 0`: `arctan(y/x) - pi` -> `(-pi, -pi/2)`
+    /// * `x >= +0`, `y >= +0`: `[+0, +pi/2]`
+    /// * `x >= +0`, `y <= -0`: `[-pi/2, -0]`
+    /// * `x <= -0`, `y >= +0`: `[+pi/2, +pi]`
+    /// * `x <= -0`, `y <= -0`: `[-pi, -pi/2]`
```
Comment (tgross35) [inline library/std/src/num/f128.rs]: I think the mathematical representation is helpful to keep for the intuition. Maybe a table format would work nicely?

```rust
/// | `x`     | `y`     | Equivalent    | Range        |
/// |---------|---------|---------------|--------------|
/// | `>= +0` | `>= +0` | `arctan(y/x)` | `[+0, +π/2]` |
/// ...
```

Basically a combination of the piecewise bit from https://en.wikipedia.org/wiki/Atan2#Definition_and_computation with the format of https://en.wikipedia.org/wiki/Inverse_trigonometric_functions#Domains.

Comment (tgross35) [reply library/std/src/num/f128.rs]: While you're here, would you mind also adding a note about how `self` and `other` map to `x` and `y`? The `(y, x)` argument order can be a bit surprising.

Comment (DimitriiTrater) [reply library/std/src/num/f128.rs]: I didn't understand. It's already has note about self (y), other(x).

Comment (DimitriiTrater) [reply library/std/src/num/f128.rs]: With your approach, I can suggest this:

``` 
    ///  | `x`     | `y`     | Equivalent        | Range         |
    ///  |---------|---------|-------------------|---------------|
    ///  | `>= +0` | `>= +0` | `arctan(y/x)`     | `[+0, +π/2]`  |
    ///  | `>= +0` | `<= -0` | `arctan(y/x)`     | `[-pi/2, -0]` |
    ///  | `<= -0` | `>= +0` | `arctan(y/x) + pi`| `[+pi/2, +pi]`|
    ///  | `<= -0` | `<= -0` | `arctan(y/x) - pi`| `[-pi, -pi/2]`|
```
But from a mathematical point of view, the signed zero here has no meaning, so it looks a bit confusing. And equivalent here is not a true for x, y in this inequalities.
I can change "Equivalent" to "Expression used" or "Definition" so this will more reliable.

What do you think?

Comment (tgross35) [reply library/std/src/num/f128.rs]: > I didn't understand. It's already has note about self (y), other(x).

Ah yeah, totally overlooked that.

> But from a mathematical point of view, the signed zero here has no meaning, so it looks a bit confusing.

What specifically? The current PR already makes use of +/-0, this seems reasonable to me.

> I can change "Equivalent" to "Expression used" or "Definition" so this will more reliable.

"Definition" seems reasonable to me. Or maybe "Piecewise Definition".

Comment (DimitriiTrater) [reply library/std/src/num/f128.rs]: I have updated PR, "Piecewise Definition" - really good.

**Review by tgross35 — APPROVED** [review]
