### PR TITLE
Toggle assert_unsafe_precondition in codegen instead of expansion

### LINKED ISSUE #120243: Hazard in the specification of std::slice::from_raw_parts, since other languages can represent empty slices with a null pointer
The documentation is clear that [`std::slice::from_raw_parts`](https://doc.rust-lang.org/std/slice/fn.from_raw_parts.html)`(std::ptr::null, 0)` is UB.

This creates a significant hazard for FFI code interfacing with C++ ([and very likely other languages](https://stackoverflow.com/a/44305910/393146)). Although C++ doesn't have a built-in or standard-library type for a slice, the most common way of representing slices is as a `start` pointer and a length, or as `start` and `end` pointers. As explained in [this post](https://davidben.net/2024/01/15/empty-slices.html), `start` is conventionally allowed to be null (i.e. the representation of an empty slice can be `(nullptr, 0)` or `(nullptr, nullptr)`), and this is consistent with the behaviour of C++ standard library APIs such as [std::span](https://en.cppreference.com/w/cpp/container/span/span).

The stated rationale for this call being UB is:

> `data` must be non-null and aligned even for zero-length slices. One reason for this is that enum layout optimizations may rely on references (including slices of any length) being aligned and non-null to distinguish them from other data. You can obtain a pointer that is usable as data for zero-length slices using [ptr::NonNull::dangling()](https://doc.rust-lang.org/std/ptr/struct.NonNull.html#method.dangling).

This rationale is unconvincing to me. It's unnecessary for the detail of the Rust ABI's internal representation of slices to result in exposing this hazard. The full signature is
```rust
pub const unsafe fn from_raw_parts<'a, T>(data: *const T, len: usize) -> &'a [T]
```
Null slices are a niche-value optimization, they're not part of the domain of `&'a [T]`. When Rust programmers write a use of this function, they are most likely to be writing FFI code. We don't know where `data` and `len` are taken from; they could be using either the Rust or the C++ convention for an empty slice. But there is no ambiguity: neither of these representations can mean anything else than an empty slice. So, I argue that the implementation of `slice::from_raw_parts` should accept either, converting a null pointer into an aligned "dangling" pointer as necessary.

The fact that this involves a representation change because of differences between C++ and Rust slice conventions shouldn't matter: returning a valid Rust representation of an empty slice is the only thing that could be correct. Note that it is fine for `std::slice::from_raw_parts(ptr::null, len)` still to be UB when `len > 0`.

To correctly convert a `data` and `len` that could be using the C++ convention, with the current definition of `slice::from_raw_parts` you would need to do something like:
```rust
if data.is_null() {
    slice::from_raw_parts(ptr::NonNull::dangling(), 0)
} else {
    slice::from_raw_parts(data, len)
}
```
which is verbose and easy to miss the need for.

What about the cost of the null pointer check? Well, in many cases the compiler will be able to statically determine that `data` is non-null. In those cases, when it inlines `slice::from_raw_parts` it will optimize out the null check, and the cost will be zero. This includes both invocations in the code above. It even includes complicated cases such as [this](https://docs.rs/bitvec/1.0.1/src/bitvec/vec.rs.html#325-331) in `bitvec`:

```rust
/// Views the bit-vector as a slice of its underlying memory elements.
#[inline]
pub fn as_raw_slice(&self) -> &[T] {
    let (data, len) = (self.bitspan.address().to_const(), self.bitspan.elements());
    unsafe { slice::from_raw_parts(data, len) }
}
```
Here `self.bitspan.address().to_const()` returns the result of `as_ptr()` on a `NonNull` value (via [this code](https://docs.rs/bitvec/1.0.1/src/bitvec/vec.rs.html#325-331) in `wyz` which is `#[inline(always)]`), which allows the null check to be optimized out. Many of the other examples I looked at are like this.

The only cases where *correct* code can incur an additional cost for the null check is when the programmer knows &mdash;and is correct&mdash; that `data` cannot be null, but the compiler does not. And we only care about that in cases where it causes a performance regression. I would suggest that this is probably very rare, and that it is likely to be much more common that programmers take a `(start, len)` or `(start, end)` slice according to the C++ convention and just don't think of the corner case where `start` is null.

What about the possibility of code written for the new specification being run on an older Rust version that requires `data` to be non-null? That's okay as long as we document when the requirement was changed. Then:
* If a programmer checked the previous documentation and wrote previously correct code, their code will still be correct.
* If they check the new documentation, they will see that a null pointer wasn't previously allowed. Either their MSRV is already after the version where it changed; or they bump their MSRV; or they check for a null pointer.
* If they wrote previously incorrect code, the code may work correctly under a later version of Rust. This is fine and what we intend. Eventually they will update the MSRV and the code will be correct.

Aside: [String::from_raw_parts](https://doc.rust-lang.org/std/string/struct.String.html#method.from_raw_parts) and [Vec::from_raw_parts_in](https://doc.rust-lang.org/nightly/std/vec/struct.Vec.html#from_raw_parts_in) are similar, but the case for changing those is much weaker, since they impose strong constraints on the allocated region that would be unlikely to be met by a random slice coming from C++ or another language.

### LINKED ISSUE #120539: debug_asserts within libstd are not hit unless using -Zbuild-std
STR:
```
$ cargo new testcase ; cd testcase
$ cat <<EOF > src/main.rs
fn main() {
    let a = [0; 2];
    let b = unsafe { a.get_unchecked(3) };
    println!("{}", b);
}
$ cargo +nightly run -q
32764
$ cargo +nightly run -q -Zbuild-std --target=x86_64-unknown-linux-gnu
thread 'main' panicked at /home/glandium/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/slice/index.rs:228:9:
slice::get_unchecked requires that the index is within the slice
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread caused non-unwinding panic. aborting.
EOF
```

It would seem the intent is for the latter to always happen, but it doesn't.

```
$ rustc +nightly --version
rustc 1.77.0-nightly (cb4d9a190 2024-01-30)
```

### PR DESCRIPTION
**Pull request by saethlin**
The goal of this PR is to make some of the unsafe precondition checks in the standard library available in debug builds. Some UI tests are included to verify that it does that.

The diff is large, but most of it is blessing mir-opt tests and I've also split up this PR so it can be reviewed commit-by-commit.

This PR:
1. Adds a new intrinsic, `debug_assertions` which is lowered to a new MIR NullOp, and only to a constant after monomorphization
2. Rewrites `assume_unsafe_precondition` to check the new intrinsic, and be monomorphic.
3. Skips codegen of the `assume` intrinsic in unoptimized builds, because that was silly before but with these checks it's *very* silly
4. The checks with the most overhead are `ptr::read`/`ptr::write` and `NonNull::new_unchecked`. I've simply added `#[cfg(debug_assertions)]` to the checks for `ptr::read`/`ptr::write` because I was unable to come up with any (good) ideas for decreasing their impact. But for `NonNull::new_unchecked` I found that the majority of callers can use a different function, often a safe one.

Yes, this PR slows down the compile time of some programs. But in our benchmark suite it's never more than 1% icount, and the average icount change in debug-full programs is 0.22%. I think that is acceptable for such an improvement in developer experience.

https://github.com/rust-lang/rust/issues/120539#issuecomment-1922687101

### CODE REVIEW

**Comment by saethlin** [comment]
The few improvements are probably because the precondition checks are always kept in MIR, so we do less MIR inlining generally, and in some cases that happens to help.

Now I'm going to try to find the precondition checks that I think are least profitable and make those get toggled early.

File: compiler/rustc_mir_transform/src/instsimplify.rs [hunk 1]
```diff
@@ -252,6 +255,28 @@ impl<'tcx> InstSimplifyContext<'tcx, '_> {
         terminator.kind = TerminatorKind::Goto { target: destination_block };
     }
 
+    fn simplify_nounwind_call(&self, terminator: &mut Terminator<'tcx>) {
```
Comment (Nilstrieb) [inline compiler/rustc_mir_transform/src/instsimplify.rs:258]: Where is this coming from?

Comment (saethlin) [reply compiler/rustc_mir_transform/src/instsimplify.rs:258]: The `precondition_check` function is a nounwind function, but without this optimization we sometimes generate landing pads out of it.

**Comment by workingjubilee** [comment]
@saethlin leaving me out of the fun, huh.

File: src/tools/clippy/clippy_utils/src/qualify_min_const_fn.rs
Comment (oli-obk) [inline src/tools/clippy/clippy_utils/src/qualify_min_const_fn.rs:1]: squash commit into previous

File: library/core/src/intrinsics.rs [hunk 2]
```diff
@@ -2777,10 +2809,16 @@ pub const unsafe fn copy_nonoverlapping<T>(src: *const T, dst: *mut T, count: us
         assert_unsafe_precondition!(
             "ptr::copy_nonoverlapping requires that both pointer arguments are aligned and non-null \
             and the specified memory ranges do not overlap",
-            [T](src: *const T, dst: *mut T, count: usize) =>
-            is_aligned_and_not_null(src)
-                && is_aligned_and_not_null(dst)
-                && is_nonoverlapping(src, dst, count)
+            (
+                src as *const () => src: *const (),
```
Comment (oli-obk) [inline library/core/src/intrinsics.rs:2813]: it could be easier for rustaceans to read as `src: *const() = src as *const()`, as that looks like a variable definition.

File: library/core/src/ptr/non_null.rs [hunk 3]
```diff
@@ -1828,9 +1828,8 @@ impl<T: ?Sized> hash::Hash for NonNull<T> {
 impl<T: ?Sized> From<Unique<T>> for NonNull<T> {
     #[inline]
     fn from(unique: Unique<T>) -> Self {
-        // SAFETY: A Unique pointer cannot be null, so the conditions for
-        // new_unchecked() are respected.
-        unsafe { NonNull::new_unchecked(unique.as_ptr()) }
+        // SAFETY: A Unique pointer cannot be null.
+        unsafe { NonNull { pointer: unique.as_ptr() } }
```
Comment (oli-obk) [inline library/core/src/ptr/non_null.rs:1832]: Since `Unique` is unstable, maybe just change `as_ptr` to return the inner `NonNull`

**Review by oli-obk — CHANGES_REQUESTED** [review]

File: library/core/src/ptr/non_null.rs (hunk 3 above)
Comment (saethlin) [reply library/core/src/ptr/non_null.rs:1832]: Hm, that would be unlike our other `as_ptr` methods that all return raw pointers, and this is used in a handful of place that do need a `*mut T`, so they'd have to be `.as_ptr().as_ptr()`. `NonNull` already has an `as_non_null_ptr` so I suppose there's some precedent at least?

**Review by oli-obk — APPROVED** [review]
r=me (needs rebase)

**Comment by saethlin** [comment]
These linker errors seem spurious? https://rust-lang.zulipchat.com/#narrow/stream/242791-t-infra/topic/Weird.20CI.20failure.20on.20x86_64-apple-1.3A.20invalid.20r_symbolnum.3D14/near/419968478
@bors retry

**Comment by saethlin** [comment]
Perf changes are about net-neutral, and in any case a ~1% slowdown in some builds is a fine price to pay for these checks. @rustbot label: +perf-regression-triaged

File: compiler/rustc_const_eval/src/interpret/step.rs [hunk 4]
```diff
@@ -246,13 +246,25 @@ impl<'mir, 'tcx: 'mir, M: Machine<'mir, 'tcx>> InterpCx<'mir, 'tcx, M> {
...
+                    }
                     mir::NullOp::OffsetOf(fields) => {
-                        layout.offset_of_subfield(self, fields.iter()).bytes()
+                        let val = layout.offset_of_subfield(self, fields.iter()).bytes();
+                        Scalar::from_target_usize(val, self)
+                    }
+                    mir::NullOp::DebugAssertions => {
+                        // The checks hidden behind this are always better done by the interpreter
+                        // itself, because it knows the runtime state better.
+                        Scalar::from_bool(false)
```
Comment (RalfJung) [inline compiler/rustc_const_eval/src/interpret/step.rs:264]: This calls for careful documentation in `intrinsics.rs` (which is currently missing). If the intrinsic is ever used in cases where there is *not* immediate UB after a failed assertion, this will lead to a surprising lack of debug checks in Miri (and potentially const-eval).

File: library/core/src/intrinsics.rs [hunk 5]
```diff
@@ -2766,10 +2809,16 @@ pub const unsafe fn copy_nonoverlapping<T>(src: *const T, dst: *mut T, count: us
...
+            (
+                src: *const () = src as *const (),
+                dst: *mut () = dst as *mut (),
+                size: usize = size_of::<T>(),
+                align: usize = align_of::<T>(),
+                count: usize = count,
+            ) =>
+            is_aligned_and_not_null(src, align)
+                && is_aligned_and_not_null(dst, align)
+                && is_nonoverlapping_mono(src, dst, size, count)
```
Comment (RalfJung) [inline library/core/src/intrinsics.rs:2821]: A comment for why this calls the "mono" variant would be useful.

File: library/core/src/intrinsics.rs [hunk 6]
```diff
@@ -2632,30 +2658,47 @@ pub(crate) use assert_unsafe_precondition;
...
+    let diff = src_usize.abs_diff(dst_usize);
+    // If the absolute distance between the ptrs is at least as big as the size of the buffer,
+    // they do not overlap.
+    diff >= size
+}
+
 /// Checks whether the regions of memory starting at `src` and `dst` of size
 /// `count * size_of::<T>()` do *not* overlap.
 #[inline]
 pub(crate) fn is_nonoverlapping<T>(src: *const T, dst: *const T, count: usize) -> bool {
```
Comment (RalfJung) [inline library/core/src/intrinsics.rs:2693]: We could avoid some code duplication by making this call the `mono` variant.

Why do we even have both variants?

File: library/core/src/intrinsics.rs [hunk 7]
```diff
@@ -2587,10 +2598,27 @@ pub const unsafe fn is_val_statically_known<T: Copy>(_arg: T) -> bool {
...
+/// a caller of the standard library has debug assertions enabled and monomorphizes an expansion of
+/// this macro, that monomorphization will contain the check.
+///
+/// Since these checks cannot be optimized out in MIR, some care must be taken in both call and
+/// implementation to mitigate their compile-time overhead. The runtime function that we
+/// [`const_eval_select`] to is monomorphic, `#[inline(never)]`, and `#[rustc_nounwind]`. That
+/// combination of properties ensures that the code for the checks is only compiled once, and has a
+/// minimal impact on the caller's code size.
+///
+/// Caller should also introducing any other `let` bindings or any code outside this macro in order
```
Comment (RalfJung) [inline library/core/src/intrinsics.rs:2618]: Is there an "avoid" missing here? And the first word of the sentence should probably be "Callers".

File: library/core/src/intrinsics.rs (hunk 6 above)
Comment (saethlin) [reply library/core/src/intrinsics.rs:2693]: The mono variant has an argument for the pointee size, but it's less ergonomic to call as a result. Eh, maybe it doesn't matter. I'll PR some form of cleanup here.

File: compiler/rustc_const_eval/src/interpret/step.rs (hunk 4 above)
Comment (saethlin) [reply compiler/rustc_const_eval/src/interpret/step.rs:264]: Where should this be documented? In a module doc comment? On the enclosing function?

Comment (RalfJung) [reply compiler/rustc_const_eval/src/interpret/step.rs:264]: I was thinking the doc comment for the `debug_assertions` intrinsic.

File: compiler/rustc_mir_transform/src/instsimplify.rs (hunk 1 above)
Comment (RalfJung) [reply compiler/rustc_mir_transform/src/instsimplify.rs:258]: "sometimes"? Strange. Is this a MIR building bug?

File: tests/mir-opt/inline/unwrap_unchecked.unwrap_unchecked.Inline.panic-abort.diff [hunk 8]
```diff
@@ -7,41 +7,44 @@
...
-+         _5 = Eq(_4, const 1_isize);
-+         assume(move _5);
++         _3 = discriminant(_2);
++         switchInt(move _3) -> [0: bb1, 1: bb3, otherwise: bb2];
+      }
+  
+      bb1: {
++         StorageLive(_4);
++         _4 = cfg!(debug_assertions);
++         assume(_4);
```
Comment (DianQK) [inline tests/mir-opt/inline/unwrap_unchecked.unwrap_unchecked.Inline.panic-abort.diff:37]: So it's expected that it doesn't directly convert to `unreachable` here, right?

Comment (saethlin) [reply tests/mir-opt/inline/unwrap_unchecked.unwrap_unchecked.Inline.panic-abort.diff:37]: Yes

File: compiler/rustc_mir_transform/src/instsimplify.rs (hunk 1 above)
Comment (saethlin) [reply compiler/rustc_mir_transform/src/instsimplify.rs:258]: I don't know. I tried to fix this in MIR building and it seemed really awkward.

I also wonder if inlining will cause the optimization to sometimes see a monomorphic call that was initially built polymorphic. And thus we'd need the opt anyway.

File: tests/mir-opt/inline/unwrap_unchecked.unwrap_unchecked.Inline.panic-abort.diff (hunk 8 above)
Comment (DianQK) [reply tests/mir-opt/inline/unwrap_unchecked.unwrap_unchecked.Inline.panic-abort.diff:37]: I didn't notice the associated comments. This is for the standard library. :)

File: compiler/rustc_mir_transform/src/instsimplify.rs (hunk 1 above)
Comment (RalfJung) [reply compiler/rustc_mir_transform/src/instsimplify.rs:258]: Ah, inlining is a good point. Might be worth a dedicated test.
