### PR TITLE
Avoid ICE when checking `Destination` of `break` inside a closure

### LINKED ISSUE #62480: Internal compiler error with labeled break inside closure
**Toolchain version**: rustc 1.38.0-nightly (dfd52ba6a 2019-07-06)

The following code produces internal compiler error
```rust
#![feature(label_break_value)]

fn main() {
    let a = 'a: {
        let a = |x: i32| break 'a;
        1
    };
}
```

<details><summary>backtrace</summary>
<p>

```
thread 'rustc' panicked at 'Box<Any>', src/librustc_errors/lib.rs:649:9
stack backtrace:
error: internal compiler error: src/librustc_typeck/check/mod.rs:509: could not find enclosing breakable with id HirId { owner: DefIndex(12), local_id: 9 }

thread 'rustc' panicked at 'Box<Any>', src/librustc_errors/lib.rs:649:9
stack backtrace:
   0: std::panicking::default_hook::{{closure}}
   0: std::panicking::default_hook::{{closure}}
   1: std::panicking::default_hook
   1: std::panicking::default_hook
   2: rustc::util::common::panic_hook
   2: rustc::util::common::panic_hook
   3: std::panicking::rust_panic_with_hook
   3: std::panicking::rust_panic_with_hook
   4: std::panicking::begin_panic
   4: std::panicking::begin_panic
   5: rustc_errors::Handler::bug
   5: rustc_errors::Handler::bug
   6: rustc::util::bug::opt_span_bug_fmt::{{closure}}
   6: rustc::util::bug::opt_span_bug_fmt::{{closure}}
   7: rustc::ty::context::tls::with_opt::{{closure}}
   7: rustc::ty::context::tls::with_opt::{{closure}}
   8: rustc::ty::context::tls::with_context_opt
   8: rustc::ty::context::tls::with_context_opt
   9: rustc::ty::context::tls::with_opt
   9: rustc::ty::context::tls::with_opt
  10: rustc::util::bug::opt_span_bug_fmt
  10: rustc::util::bug::opt_span_bug_fmt
  11: rustc::util::bug::bug_fmt
  11: rustc::util::bug::bug_fmt
  12: rustc_typeck::check::EnclosingBreakables::find_breakable::{{closure}}
  12: rustc_typeck::check::EnclosingBreakables::find_breakable::{{closure}}
  13: rustc_typeck::check::EnclosingBreakables::find_breakable
  13: rustc_typeck::check::EnclosingBreakables::find_breakable
  14: rustc_typeck::check::expr::<impl rustc_typeck::check::FnCtxt>::check_expr_with_expectation_and_needs
  14: rustc_typeck::check::expr::<impl rustc_typeck::check::FnCtxt>::check_expr_with_expectation_and_needs
  15: rustc_typeck::check::expr::<impl rustc_typeck::check::FnCtxt>::check_return_expr
  16: rustc_typeck::check::check_fn
  15: rustc_typeck::check::expr::<impl rustc_typeck::check::FnCtxt>::check_return_expr
  16: rustc_typeck::check::check_fn
  17: rustc_typeck::check::closure::<impl rustc_typeck::check::FnCtxt>::check_expr_closure
  17: rustc_typeck::check::closure::<impl rustc_typeck::check::FnCtxt>::check_expr_closure
  18: rustc_typeck::check::expr::<impl rustc_typeck::check::FnCtxt>::check_expr_with_expectation_and_needs
  18: rustc_typeck::check::expr::<impl rustc_typeck::check::FnCtxt>::check_expr_with_expectation_and_needs
  19: rustc_typeck::check::FnCtxt::check_decl_initializer
  19: rustc_typeck::check::FnCtxt::check_decl_initializer
  20: rustc_typeck::check::FnCtxt::check_decl_local
  21: rustc_typeck::check::FnCtxt::check_stmt
  20: rustc_typeck::check::FnCtxt::check_decl_local
  22: rustc_typeck::check::FnCtxt::check_block_with_expected
  21: rustc_typeck::check::FnCtxt::check_stmt
  22: rustc_typeck::check::FnCtxt::check_block_with_expected
  23: rustc_typeck::check::expr::<impl rustc_typeck::check::FnCtxt>::check_expr_with_expectation_and_needs
  23: rustc_typeck::check::expr::<impl rustc_typeck::check::FnCtxt>::check_expr_with_expectation_and_needs
  24: rustc_typeck::check::FnCtxt::check_decl_initializer
  24: rustc_typeck::check::FnCtxt::check_decl_initializer
  25: rustc_typeck::check::FnCtxt::check_decl_local
  25: rustc_typeck::check::FnCtxt::check_decl_local
  26: rustc_typeck::check::FnCtxt::check_stmt
  26: rustc_typeck::check::FnCtxt::check_stmt
  27: rustc_typeck::check::FnCtxt::check_block_with_expected
  27: rustc_typeck::check::FnCtxt::check_block_with_expected
  28: rustc_typeck::check::expr::<impl rustc_typeck::check::FnCtxt>::check_expr_with_expectation_and_needs
  28: rustc_typeck::check::expr::<impl rustc_typeck::check::FnCtxt>::check_expr_with_expectation_and_needs
  29: rustc_typeck::check::expr::<impl rustc_typeck::check::FnCtxt>::check_return_expr
  29: rustc_typeck::check::expr::<impl rustc_typeck::check::FnCtxt>::check_return_expr
  30: rustc_typeck::check::check_fn
  30: rustc_typeck::check::check_fn
  31: rustc::ty::context::GlobalCtxt::enter_local
  31: rustc::ty::context::GlobalCtxt::enter_local
  32: rustc_typeck::check::typeck_tables_of
  32: rustc_typeck::check::typeck_tables_of
  33: rustc::ty::query::__query_compute::typeck_tables_of
  33: rustc::ty::query::__query_compute::typeck_tables_of
  34: rustc::ty::query::<impl rustc::ty::query::config::QueryAccessors for rustc::ty::query::queries::typeck_tables_of>::compute
  34: rustc::ty::query::<impl rustc::ty::query::config::QueryAccessors for rustc::ty::query::queries::typeck_tables_of>::compute
  35: rustc::dep_graph::graph::DepGraph::with_task_impl
  35: rustc::dep_graph::graph::DepGraph::with_task_impl
  36: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt>::get_query
  36: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt>::get_query
  37: rustc::ty::<impl rustc::ty::context::TyCtxt>::par_body_owners
  37: rustc::ty::<impl rustc::ty::context::TyCtxt>::par_body_owners
  38: rustc_typeck::check::typeck_item_bodies
  38: rustc_typeck::check::typeck_item_bodies
  39: rustc::ty::query::__query_compute::typeck_item_bodies
  39: rustc::ty::query::__query_compute::typeck_item_bodies
  40: rustc::dep_graph::graph::DepGraph::with_task_impl
  40: rustc::dep_graph::graph::DepGraph::with_task_impl
  41: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt>::get_query
  41: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt>::get_query
  42: rustc::util::common::time
  42: rustc::util::common::time
  43: rustc_typeck::check_crate
  43: rustc_typeck::check_crate
  44: rustc_interface::passes::analysis
  44: rustc_interface::passes::analysis
  45: rustc::ty::query::__query_compute::analysis
  45: rustc::ty::query::__query_compute::analysis
  46: rustc::dep_graph::graph::DepGraph::with_task_impl
  46: rustc::dep_graph::graph::DepGraph::with_task_impl
  47: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt>::get_query
  47: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt>::get_query
  48: rustc_interface::passes::BoxedGlobalCtxt::access::{{closure}}
  48: rustc_interface::passes::BoxedGlobalCtxt::access::{{closure}}
  49: rustc_interface::passes::create_global_ctxt::{{closure}}
  49: rustc_interface::passes::create_global_ctxt::{{closure}}
  50: rustc_interface::interface::run_compiler_in_existing_thread_pool
  50: rustc_interface::interface::run_compiler_in_existing_thread_pool
  51: std::thread::local::LocalKey<T>::with
  51: std::thread::local::LocalKey<T>::with
  52: scoped_tls::ScopedKey<T>::set
  53: syntax::with_globals
  52: scoped_tls::ScopedKey<T>::set
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
  53: syntax::with_globals
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
query stack during panic:
query stack during panic:
#0 [typeck_tables_of] processing `main`
#0 [typeck_tables_of] processing `main`
#1 [typeck_item_bodies] type-checking all item bodies
#2 [analysis] running analysis passes on this crate
end of query stack
#1 [typeck_item_bodies] type-checking all item bodies
#2 [analysis] running analysis passes on this crate
end of query stack
```

</p>
</details>

### LINKED ISSUE #65383: Could not find enclosing breakable with id HirId
I tried to compile some massive project and the rust compiler unexpectedly panicked. Luckily, I have managed to replicate the error in a small, reproducible example (still panics on rust playground online, 11 lines of code): 
```rust
fn main() {
    let c = |p| {
        'main: for h in p..(p + 10) {
            let j = |k| {
                break 'main;
            };
            j(p);
        }
    };
    c(1);
}
```

I expected a regular error without a panic, but the compiler simply halted.

Output of RUST_BACKTRACE=1 rustc ~/Desktop/rust_bug.rs -o bug.out -C debuginfo=2:
```
error[E0267]: `break` inside of a closure
 --> /home/liam/Desktop/rust_bug.rs:5:17
  |
5 |                 break 'main;
  |                 ^^^^^^^^^^^ cannot break inside of a closure

error: internal compiler error: src/librustc_typeck/check/mod.rs:509: could not find enclosing breakable with id HirId { owner: DefIndex(12), local_id: 34 }

thread 'rustc' panicked at 'Box<Any>', src/librustc_errors/lib.rs:644:9
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.29/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.29/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:47
   3: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:36
   4: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:200
   5: std::panicking::default_hook
             at src/libstd/panicking.rs:214
   6: rustc::util::common::panic_hook
   7: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:481
   8: std::panicking::begin_panic
   9: rustc_errors::Handler::bug
  10: rustc::util::bug::opt_span_bug_fmt::{{closure}}
  11: rustc::ty::context::tls::with_opt::{{closure}}
  12: rustc::ty::context::tls::with_context_opt
  13: rustc::ty::context::tls::with_opt
  14: rustc::util::bug::opt_span_bug_fmt
  15: rustc::util::bug::bug_fmt
  16: rustc_typeck::check::EnclosingBreakables::find_breakable::{{closure}}
  17: rustc_typeck::check::EnclosingBreakables::find_breakable
  18: rustc_typeck::check::expr::<impl rustc_typeck::check::FnCtxt>::check_expr_with_expectation_and_needs
  19: rustc_typeck::check::FnCtxt::check_stmt
  20: rustc_typeck::check::FnCtxt::check_block_with_expected
  21: rustc_typeck::check::expr::<impl rustc_typeck::check::FnCtxt>::check_expr_with_expectation_and_needs
  22: rustc_typeck::check::expr::<impl rustc_typeck::check::FnCtxt>::check_return_expr
  23: rustc_typeck::check::check_fn
  24: rustc_typeck::check::closure::<impl rustc_typeck::check::FnCtxt>::check_expr_closure
  25: rustc_typeck::check::expr::<impl rustc_typeck::check::FnCtxt>::check_expr_with_expectation_and_needs
  26: rustc_typeck::check::FnCtxt::check_decl_initializer
  27: rustc_typeck::check::FnCtxt::check_decl_local
  28: rustc_typeck::check::FnCtxt::check_stmt
  29: rustc_typeck::check::FnCtxt::check_block_with_expected
  30: rustc_typeck::check::expr::<impl rustc_typeck::check::FnCtxt>::check_expr_with_expectation_and_needs
  31: rustc_typeck::check::expr::<impl rustc_typeck::check::FnCtxt>::check_expr_meets_expectation_or_error
  32: rustc_typeck::check::FnCtxt::check_stmt
  33: rustc_typeck::check::FnCtxt::check_block_with_expected
  34: rustc_typeck::check::expr::<impl rustc_typeck::check::FnCtxt>::check_expr_with_expectation_and_needs
  35: rustc_typeck::check::_match::<impl rustc_typeck::check::FnCtxt>::check_match
  36: rustc_typeck::check::expr::<impl rustc_typeck::check::FnCtxt>::check_expr_with_expectation_and_needs
  37: rustc_typeck::check::expr::<impl rustc_typeck::check::FnCtxt>::check_expr_with_expectation_and_needs
  38: rustc_typeck::check::FnCtxt::check_block_with_expected
  39: rustc_typeck::check::expr::<impl rustc_typeck::check::FnCtxt>::check_expr_with_expectation_and_needs
  40: rustc_typeck::check::expr::<impl rustc_typeck::check::FnCtxt>::check_return_expr
  41: rustc_typeck::check::check_fn
  42: rustc_typeck::check::closure::<impl rustc_typeck::check::FnCtxt>::check_expr_closure
  43: rustc_typeck::check::expr::<impl rustc_typeck::check::FnCtxt>::check_expr_with_expectation_and_needs
  44: rustc_typeck::check::FnCtxt::check_decl_initializer
  45: rustc_typeck::check::FnCtxt::check_decl_local
  46: rustc_typeck::check::FnCtxt::check_stmt
  47: rustc_typeck::check::FnCtxt::check_block_with_expected
  48: rustc_typeck::check::expr::<impl rustc_typeck::check::FnCtxt>::check_expr_with_expectation_and_needs
  49: rustc_typeck::check::expr::<impl rustc_typeck::check::FnCtxt>::check_return_expr
  50: rustc_typeck::check::check_fn
  51: rustc::ty::context::GlobalCtxt::enter_local
  52: rustc_typeck::check::typeck_tables_of
  53: rustc::ty::query::__query_compute::typeck_tables_of
  54: rustc::ty::query::<impl rustc::ty::query::config::QueryAccessors for rustc::ty::query::queries::typeck_tables_of>::compute
  55: rustc::dep_graph::graph::DepGraph::with_task_impl
  56: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt>::get_query
  57: rustc::ty::<impl rustc::ty::context::TyCtxt>::par_body_owners
  58: rustc_typeck::check::typeck_item_bodies
  59: rustc::ty::query::__query_compute::typeck_item_bodies
  60: rustc::dep_graph::graph::DepGraph::with_task_impl
  61: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt>::get_query
  62: rustc::util::common::time
  63: rustc_typeck::check_crate
  64: rustc_interface::passes::analysis
  65: rustc::ty::query::__query_compute::analysis
  66: rustc::dep_graph::graph::DepGraph::with_task_impl
  67: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt>::get_query
  68: rustc_interface::passes::BoxedGlobalCtxt::access::{{closure}}
  69: rustc_interface::passes::create_global_ctxt::{{closure}}
  70: rustc_interface::interface::run_compiler_in_existing_thread_pool
  71: std::thread::local::LocalKey<T>::with
  72: syntax::with_globals
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
query stack during panic:
#0 [typeck_tables_of] processing `main`
#1 [typeck_item_bodies] type-checking all item bodies
#2 [analysis] running analysis passes on this crate
end of query stack
error: aborting due to 2 previous errors

For more information about this error, try `rustc --explain E0267`.

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.38.0-nightly (04b88a9eb 2019-07-29) running on x86_64-unknown-linux-gnu

note: compiler flags: -C debuginfo=2
```

Output of `rustc --version --verbose`:
```
rustc 1.38.0-nightly (04b88a9eb 2019-07-29)
binary: rustc
commit-hash: 04b88a9eba8abbac87eddcb2998beea09589c2c9
commit-date: 2019-07-29
host: x86_64-unknown-linux-gnu
release: 1.38.0-nightly
LLVM version: 9.0
```

### PR DESCRIPTION
**Pull request by estebank**
Fix #65383, fix #62480. This is a `[regression-from-stable-to-stable]` and a fairly small change to avoid the ICE by properly handling this case.

### CODE REVIEW

File: src/librustc_typeck/check/expr.rs [hunk 1]
```diff
@@ -566,43 +566,48 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
...
-                if let Some(ref e) = expr_opt {
-                    coerce.coerce(self, &cause, e, e_ty);
+            if let Some(ref mut ctxt) = enclosing_breakables.opt_find_breakable(target_id) {
+                if let Some(ref mut coerce) = ctxt.coerce {
+                    if let Some(ref e) = expr_opt {
+                        coerce.coerce(self, &cause, e, e_ty);
+                    } else {
+                        assert!(e_ty.is_unit());
+                        let ty = coerce.expected_ty();
+                        coerce.coerce_forced_unit(self, &cause, &mut |err| {
```
Comment (Centril) [inline src/librustc_typeck/check/expr.rs]: Could we refactor this closure into a method or some other parts? It's getting hard to reason about the typesystem logic here cause it's not all in scope at once. :)

File: src/librustc_typeck/check/expr.rs [hunk 2]
```diff
@@ -566,43 +566,48 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
             // the `enclosing_loops` field and let's coerce the
             // type of `expr_opt` into what is expected.
             let mut enclosing_breakables = self.enclosing_breakables.borrow_mut();
-            let ctxt = enclosing_breakables.find_breakable(target_id);
-            if let Some(ref mut coerce) = ctxt.coerce {
-                if let Some(ref e) = expr_opt {
-                    coerce.coerce(self, &cause, e, e_ty);
+            if let Some(ref mut ctxt) = enclosing_breakables.opt_find_breakable(target_id) {
```
Comment (Centril) [inline src/librustc_typeck/check/expr.rs]: I think this could use a comment wrt. why it was `None` in the first place.
Also -- should this delay_span_bug in the `else` case that isn't included?

File: src/librustc_typeck/check/mod.rs [hunk 3]
```diff
@@ -536,10 +536,16 @@ pub struct EnclosingBreakables<'tcx> {
...
-        let ix = *self.by_id.get(&target_id).unwrap_or_else(|| {
+        self.opt_find_breakable(target_id).unwrap_or_else(|| {
             bug!("could not find enclosing breakable with id {}", target_id);
-        });
-        &mut self.stack[ix]
+        })
+    }
+
+    fn opt_find_breakable(&mut self, target_id: hir::HirId) -> Option<&mut BreakableCtxt<'tcx>> {
+        match self.by_id.get(&target_id) {
```
Comment (Centril) [inline src/librustc_typeck/check/mod.rs]: Use `.map(...)`?

File: src/test/ui/issues/issue-65383.rs [hunk 4]
```diff
@@ -0,0 +1,7 @@
+fn main() {
```
Comment (Centril) [inline src/test/ui/issues/issue-65383.rs]: Could use a comment saying this used to ICE and why it did.
Also relate it to the code by mentioning e.g. `check_expr_break`.
Also can we place the test with the other break-related tests?

**Comment by Centril** [comment]
(It would also be good to make a note of, in the PR description, why it is beta & stable nominated)

File: src/librustc_typeck/check/expr.rs (hunk 1 above)
Comment (estebank) [reply src/librustc_typeck/check/expr.rs]: I would prefer to make that change in a follow up PR to minimize backporting woes.

File: src/librustc_typeck/check/mod.rs (hunk 3 above)
Comment (estebank) [reply src/librustc_typeck/check/mod.rs]: borrow checker woes because `self` is used in both places.

Comment (Centril) [reply src/librustc_typeck/check/mod.rs]: Argh... borrowck is being stupid :( The captures disjoint stuff needs to happen sooner!

File: src/librustc_typeck/check/expr.rs (hunk 1 above)
Comment (Centril) [reply src/librustc_typeck/check/expr.rs]: Gonna hold you to that... ;)

**Comment by est31** [comment]
Does this also fix #62480 ?

**Comment by estebank** [comment]
@est31 yes. Just verified.

**Review by eddyb — APPROVED** [review]
r=me with or without a test

**Comment by estebank** [comment]
@bors r=eddyb

There were tests added already.

**Comment by nikomatsakis** [comment]
Discussed in the @rust-lang/compiler meeting, [accepted](https://rust-lang.zulipchat.com/#narrow/stream/131828-t-compiler/topic/weekly.20meeting.202019-10-24.20.2354818/near/178956213) for beta backport.

**Comment by nikomatsakis** [comment]
We are also giving a "technical 👍" for stable backport, I believe final decision there is made by @rust-lang/release though.

**Comment by pietroalbini** [comment]
@nikomatsakis you should add the `stable-accepted` for the "technical :+1:" btw, the release team then decides what to do based on the amount of `stable-accepted` stuff.

**Comment by Mark-Simulacrum** [comment]
Release team discussed and decided to deny stable backport given that next release is 2 weeks out and this is not a fix in the sense that it is just moving ICEs to errors, not error -> building code or so.

(Procedural note: we don't really have a good process for doing this denial, so I'll just drop both labels.)
