### PR TITLE
Don't check match scrutinee of postfix match for unused parens

### LINKED ISSUE #123064: Postfix match: Unexpected `unused_parens` warning when LHS contained parenthesis
cc #121618.

I tried this code:

```rust
#![feature(postfix_match)]
fn main() {
    (&1).match { a => a };
    (1 + 2).match { b => b };
}
```

I expected to see this happen: *no warnings*

Instead, this happened: 

```
warning: unnecessary parentheses around `match` scrutinee expression
 --> src/main.rs:3:5
  |
3 |     (&1).match { a => a };
  |     ^  ^
  |
  = note: `#[warn(unused_parens)]` on by default
help: remove these parentheses
  |
3 -     (&1).match { a => a };
3 +     &1.match { a => a };
  |

warning: unnecessary parentheses around `match` scrutinee expression
 --> src/main.rs:4:5
  |
4 |     (1 + 2).match { b => b };
  |     ^     ^
  |
help: remove these parentheses
  |
4 -     (1 + 2).match { b => b };
4 +     1 + 2.match { b => b };
  |

warning: `playground` (bin "playground") generated 2 warnings (run `cargo fix --bin "playground"` to apply 2 suggestions)
```

### Meta

`rustc --version --verbose`:
```
1.79.0-nightly (2024-03-24 0824b300eb0dae5d9ed5)
```

### PR DESCRIPTION
**Pull request by compiler-errors**
We only check the scrutinees of block-like constructs and a few others (return/index/assign/method calls). Just don't do it for postfix match at all.

Fixes #123064

r? fmease

### CODE REVIEW

File: compiler/rustc_lint/src/unused.rs [hunk 1]
```diff
@@ -865,7 +865,9 @@ trait UnusedDelimLint {
                 (iter, UnusedDelimsCtx::ForIterExpr, true, None, Some(body.span.lo()), true)
             }
 
-            Match(ref head, ..) if Self::LINT_EXPR_IN_PATTERN_MATCHING_CTX => {
+            Match(ref head, _, ast::MatchKind::Prefix)
```
Comment (fmease) [inline compiler/rustc_lint/src/unused.rs:868]: I was about to say that is too coarse-grained since it leads to us no longer flagging `(0).match {}` or `(f()).match {}` but after a quick check I realized that we currently don't flag `(f()).await`, `(0).f()` and `(f()).g()` either.

I'm gonna add an item to my TODO list to open an issue for all of these cases unless there already exists one.

Comment (compiler-errors) [reply compiler/rustc_lint/src/unused.rs:868]: Yeah, I'd prefer if those were implemented in a principled way. This PR doesn't add more inconsistency.
