### PR TITLE
Restore `#![no_builtins]` crates participation in LTO.

### LINKED ISSUE #347: -Zbuild-std + lto="fat" = undefined reference to `core::panicking::panic`
```shell
$ cargo new --bin a
     Created binary (application) `a` package
$ cd a/
$ echo -e '[profile.dev]\nlto="fat"' >> Cargo.toml 
$ cargo run -Zbuild-std --target x86_64-unknown-linux-gnu
...
error: linking with `cc` failed: exit code: 1
  |
  = note: "cc" "-Wl,--as-needed" "-Wl,-z,noexecstack" "-m64" "-L" "/../.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "/tmp/a/target/x86_64-unknown-linux-gnu/debug/deps/a-f6afee8bd619dd6c.10btgdcccpdgwv38.rcgu.o" "-o" "/tmp/a/target/x86_64-unknown-linux-gnu/debug/deps/a-f6afee8bd619dd6c" "-Wl,--gc-sections" "-pie" "-Wl,-zrelro" "-Wl,-znow" "-nodefaultlibs" "-L" "/tmp/a/target/x86_64-unknown-linux-gnu/debug/deps" "-L" "/tmp/a/target/debug/deps" "-L" "/tmp/a/target/x86_64-unknown-linux-gnu/debug/build/backtrace-sys-23683e5572d20c8c/out" "-L" "/../.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-Wl,--start-group" "-Wl,-Bstatic" "/tmp/rustcgyDZiW/libbacktrace_sys-ba159dd14189807b.rlib" "-Wl,--end-group" "/tmp/a/target/x86_64-unknown-linux-gnu/debug/deps/libcompiler_builtins-495badfa0e51e0a1.rlib" "-Wl,-Bdynamic" "-ldl" "-lrt" "-lpthread" "-lgcc_s" "-lc" "-lm" "-lrt" "-lpthread" "-lutil" "-lutil"
  = note: /usr/bin/ld: /tmp/a/target/x86_64-unknown-linux-gnu/debug/deps/libcompiler_builtins-495badfa0e51e0a1.rlib(compiler_builtins-495badfa0e51e0a1.compiler_builtins.ecun6ipv-cgu.15.rcgu.o): in function `<i128 as core::ops::arith::Sub>::sub':
          /../.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libcore/ops/arith.rs:194: undefined reference to `core::panicking::panic'
          /usr/bin/ld: /tmp/a/target/x86_64-unknown-linux-gnu/debug/deps/libcompiler_builtins-495badfa0e51e0a1.rlib(compiler_builtins-495badfa0e51e0a1.compiler_builtins.ecun6ipv-cgu.11.rcgu.o): in function `compiler_builtins::int::sdiv::Div::div':
          /../.cargo/registry/src/github.com-1ecc6299db9ec823/compiler_builtins-0.1.25/src/int/sdiv.rs:6: undefined reference to `core::panicking::panic'
          /usr/bin/ld: /../.cargo/registry/src/github.com-1ecc6299db9ec823/compiler_builtins-0.1.25/src/int/sdiv.rs:7: undefined reference to `core::panicking::panic'
          /usr/bin/ld: /tmp/a/target/x86_64-unknown-linux-gnu/debug/deps/libcompiler_builtins-495badfa0e51e0a1.rlib(compiler_builtins-495badfa0e51e0a1.compiler_builtins.ecun6ipv-cgu.11.rcgu.o): in function `compiler_builtins::int::sdiv::Mod::mod_':
          /../.cargo/registry/src/github.com-1ecc6299db9ec823/compiler_builtins-0.1.25/src/int/sdiv.rs:28: undefined reference to `core::panicking::panic'
          /usr/bin/ld: /../.cargo/registry/src/github.com-1ecc6299db9ec823/compiler_builtins-0.1.25/src/int/sdiv.rs:31: undefined reference to `core::panicking::panic'
          /usr/bin/ld: /tmp/a/target/x86_64-unknown-linux-gnu/debug/deps/libcompiler_builtins-495badfa0e51e0a1.rlib(compiler_builtins-495badfa0e51e0a1.compiler_builtins.ecun6ipv-cgu.13.rcgu.o):/../.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libcore/ops/bit.rs:515: more undefined references to `core::panicking::panic' follow
          collect2: error: ld returned 1 exit status
          

error: aborting due to previous error
```

Looks like this is either an issue with compiler-builtins which should avoid
using any checked operations which could generate references to core crate, or
an issue with cargo `-Zbuild-std` which should always built this crate with
`-Coverflow-checks=no`.

### LINKED ISSUE #10118: build-std: wasm32-unknown-unknown failing with `overflow-checks=true` and LTO
### Problem

It seems that recompiling libstd/libcore with overflow checks isn't something you want to to. At least it leads to some annoying bugs: 
https://github.com/rust-lang/rust/issues/78744
https://github.com/rust-lang/rust/issues/91158

I wonder if recompiling the standard library with overflow checks is even useful. It seems that we are perfectly fine with enabling `overflow-checks=true` in some workspace and then link against the precompiled version of libstd (which isn't compiled without these checks). Please correct me if I am wrong here.

### Proposed Solution

The `-Z build-std` feature should always disable `overflow-checks` when building the standard library no matter what is defined in the `Cargo.toml` of the workspace in question.

### Notes

Is there some workaround where I can make the std build use a different profile than the workspace?

### LINKED ISSUE #72140: LTO and no_builtins: undefined references to standard Rust symbols errors at link time
It seems that depending on a Rust library that has the attribute `#![no_builtins]` prevents the linker to provide the needed symbols to the library.

I made a repository to demonstrate this issue with a minimal reproduction case: [Deluvi/bug-no-builtins-lto-rust](https://github.com/Deluvi/bug-no-builtins-lto-rust). The instructions to run the example are in the README.

Here is an example error line (you can find the whole `cargo` output in the "Error output" drop down below):

```
/usr/bin/ld: no_builtins_lib.2derfq4u-cgu.2:(.text._ZN5alloc7raw_vec19RawVec$LT$T$C$A$GT$7reserve17h791963cb9aa36cdbE+0x7f): undefined reference to `__rust_alloc'
```

If you want the compilation to work, you can remove the [`#!\[no_builtins\] line](https://github.com/Deluvi/bug-no-builtins-lto-rust/blob/38a36ceaa2bed1dfa6a1963c855d92adc4896cbe/no-builtins-lib/src/lib.rs#L1) and the compilation will work just fine.

### Meta

`rustc --version --verbose`:
```
rustc 1.43.1 (8d69840ab 2020-05-04)
binary: rustc
commit-hash: 8d69840ab92ea7f4d323420088dd8c9775f180cd
commit-date: 2020-05-04
host: x86_64-unknown-linux-gnu
release: 1.43.1
LLVM version: 9.0
```

<details><summary>Error output</summary>
<p>

```
cargo run --release -p no-builtins-bin
   Compiling no-builtins-lib v0.1.0 (/home/deluvi/tests/test-lto/no-builtins-lib)
   Compiling no-builtins-bin v0.1.0 (/home/deluvi/tests/test-lto/no-builtins-bin)
error: linking with `cc` failed: exit code: 1
  |
  = note: "cc" "-Wl,--as-needed" "-Wl,-z,noexecstack" "-m64" "-L" "/home/deluvi/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "/home/deluvi/tests/test-lto/target/release/deps/no_builtins_bin-d28e15586db11f8b.no_builtins_bin.ds5ffvdz-cgu.7.rcgu.o" "-o" "/home/deluvi/tests/test-lto/target/release/deps/no_builtins_bin-d28e15586db11f8b" "-Wl,--gc-sections" "-pie" "-Wl,-zrelro" "-Wl,-znow" "-Wl,-O1" "-nodefaultlibs" "-L" "/home/deluvi/tests/test-lto/target/release/deps" "-L" "/home/deluvi/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-Wl,-Bstatic" "/home/deluvi/tests/test-lto/target/release/deps/libno_builtins_lib-cef2adf5c7c12373.rlib" "-Wl,--start-group" "/tmp/rustcvFiUgJ/libbacktrace_sys-dc606003556dfe9c.rlib" "-Wl,--end-group" "/home/deluvi/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcompiler_builtins-2541f1e09df1c67d.rlib" "-Wl,-Bdynamic" "-ldl" "-lrt" "-lpthread" "-lgcc_s" "-lc" "-lm" "-lrt" "-lpthread" "-lutil" "-lutil"
  = note: /usr/bin/ld: /home/deluvi/tests/test-lto/target/release/deps/libno_builtins_lib-cef2adf5c7c12373.rlib(no_builtins_lib-cef2adf5c7c12373.no_builtins_lib.2derfq4u-cgu.0.rcgu.o): in function `core::ptr::drop_in_place':
          no_builtins_lib.2derfq4u-cgu.0:(.text._ZN4core3ptr13drop_in_place17h107dbe4e36e3489dE+0x13): undefined reference to `__rust_dealloc'
          /usr/bin/ld: /home/deluvi/tests/test-lto/target/release/deps/libno_builtins_lib-cef2adf5c7c12373.rlib(no_builtins_lib-cef2adf5c7c12373.no_builtins_lib.2derfq4u-cgu.2.rcgu.o): in function `alloc::raw_vec::RawVec<T,A>::reserve':
          no_builtins_lib.2derfq4u-cgu.2:(.text._ZN5alloc7raw_vec19RawVec$LT$T$C$A$GT$7reserve17h791963cb9aa36cdbE+0x58): undefined reference to `__rust_realloc'
          /usr/bin/ld: no_builtins_lib.2derfq4u-cgu.2:(.text._ZN5alloc7raw_vec19RawVec$LT$T$C$A$GT$7reserve17h791963cb9aa36cdbE+0x7f): undefined reference to `__rust_alloc'
          /usr/bin/ld: no_builtins_lib.2derfq4u-cgu.2:(.text._ZN5alloc7raw_vec19RawVec$LT$T$C$A$GT$7reserve17h791963cb9aa36cdbE+0x8f): undefined reference to `__rust_dealloc'
          /usr/bin/ld: no_builtins_lib.2derfq4u-cgu.2:(.text._ZN5alloc7raw_vec19RawVec$LT$T$C$A$GT$7reserve17h791963cb9aa36cdbE+0x98): undefined reference to `core::alloc::Layout::dangling'
          /usr/bin/ld: no_builtins_lib.2derfq4u-cgu.2:(.text._ZN5alloc7raw_vec19RawVec$LT$T$C$A$GT$7reserve17h791963cb9aa36cdbE+0xa8): undefined reference to `core::alloc::Layout::dangling'
          /usr/bin/ld: no_builtins_lib.2derfq4u-cgu.2:(.text._ZN5alloc7raw_vec19RawVec$LT$T$C$A$GT$7reserve17h791963cb9aa36cdbE+0xc4): undefined reference to `alloc::raw_vec::capacity_overflow'
          /usr/bin/ld: no_builtins_lib.2derfq4u-cgu.2:(.text._ZN5alloc7raw_vec19RawVec$LT$T$C$A$GT$7reserve17h791963cb9aa36cdbE+0xd4): undefined reference to `alloc::alloc::handle_alloc_error'
          collect2: error: ld returned 1 exit status
          

error: aborting due to previous error

error: could not compile `no-builtins-bin`.
```

</p>
</details>

### LINKED ISSUE #78744: Non existing function imported when compiling for wasm
Whenever I try to compile  some specific code for `wasm32-unknown-unknown` with enabled `overflow-checks` and `lto` the compiler inserts a function import into the resulting wasm module that looks like this:

```wat
(import "env" "_ZN4core9panicking5panic17h80a3410ec4f43255E" (func $_ZN4core9panicking5panic17h80a3410ec4f43255E (type 0))
```

These are the complete contents of the `lib.rs`:

```rust
#![no_std]

#[panic_handler]
fn my_panic(_info: &core::panic::PanicInfo) -> ! {
    loop {}
}

#[no_mangle]
pub fn multer(a: i128, b: i128) -> i128 {
    // trigger usage of the __multi3 compiler intrinsic which seems to be necessary
    // in order to reproduce the bug
    a * b
}
```

What seems to trigger the bug are the following conditions:
* The `--target` must be `wasm32-unknown-unknown`
* `overflow-checks = true`
* `lto = true`
* Recompile core libs with cargo xbuild or the std aware cargo
* The call of the panic function originates in some compiler extrinsic

The [minimal reproducer repo](https://github.com/athei/mult-panic) contains the exact command line that reproduces the bug.

I expected to see this happen: 
The resulting wasm module does **not** import any function from the environment.

Instead, this happened:
The resulting wasm module imports the previously mentioned panic function from the environment.

### Meta
`rustc +nightly --version --verbose`:
```
rustc 1.49.0-nightly (ffa2e7ae8 2020-10-24)
binary: rustc
commit-hash: ffa2e7ae8fbf9badc035740db949b9dae271c29f
commit-date: 2020-10-24
host: x86_64-apple-darwin
release: 1.49.0-nightly
LLVM version: 11.0
```

### LINKED ISSUE #91158: Compiler builtin calls imported function when compiling with `-Z build-std` for wasm
[This is a minimal reproducer](https://github.com/athei/mult-panic) for a bug where the compiler inserts a call to a non-existent
panic function. The following things need to be true to reproduce the bug:

* target must be wasm32-unknown-unknown
* overflow checks must be enabled
* link time optimization must be enabled
* core must be recompiled using `-Z build-std`
* The compiler needs to insert a call to `memcpy`

The non existent imported function will be then called by the overflow checks in the
`memcpy` compiler intrinsic.

[I reported this error before](https://github.com/rust-lang/rust/issues/78744) and also added a regression test but this error is slightly different and hence the regression test didn't catch it.

## Steps to reproduce

Clone the reproducer repo and run the following:

```shell
cargo +nightly build --release --target wasm32-unknown-unknown -Z build-std
wasm2wat target/wasm32-unknown-unknown/release/mult_panic.wasm | less
```

I tested these steps with `rustc 1.58.0-nightly (936f2600b 2021-11-22)`. Version `2021-11-17` and
less seem to be unaffected. Therefore the first version to have this bug is `2021-11-18`.

If you inspect the resulting wasm file you see that it imports some none existing panic function:

```wat
(import "env" "_ZN4core9panicking5panic17h80a3410ec4f43255E" (func $_ZN4core9panicking5panic17h80a3410ec4f43255E (type 0)))
```

This function is called from the compiler intrinsic on integer overflow. If either lto or
integer overflow is disabled, the error goes away.

It seems that recompiling libcore with `overflow-checks = true` is at the root of this problem. I wonder if that is even a good idea but I see no way to have this option to only apply to my own crate and not to `-Z build-std`.

### LINKED ISSUE #96486: Nightly: LTO with share-generics causes undefined symbols when using build-std
### Meta

`rustc --version --verbose`:
```
rustc 1.62.0-nightly (082e4ca49 2022-04-26)
binary: rustc
commit-hash: 082e4ca49770ebc9cb0ee616f3726a67471be8cb
commit-date: 2022-04-26
host: x86_64-apple-darwin
release: 1.62.0-nightly
LLVM version: 14.0.1
```

Enabling thin LTO causes a few undefined symbols:
<details><summary>Compiler Output (click)</summary>
<p>

```
error: linking with `rust-lld` failed: exit status: 1
  |
  = note: "rust-lld" "-flavor" "link" "/NOLOGO" "/entry:efi_main" "/subsystem:efi_application" "/var/folders/fp/w6d3psl51lgf5w8pk08d2frw0000gn/T/rustcO0BlRS/symbols.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.105u7pgm0xpbllzb.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.149d2wxu0jx3f3zo.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.14syk41ghaff7dhi.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.16ac3be4npx816a5.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.16tv3si5ezyo8pfv.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.18gyd5i7p8su7oaj.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.198v6kjkir1l9vto.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.1aw97atxqy7apc3g.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.1g62om2ivuwrps34.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.1ga0t5ufq4chpx4t.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.1ge8pxwfhtjex5hc.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.1mh52ly06rs9x5m4.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.1o9s35x28qzscgm4.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.1pt7l3ldpoy33k0a.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.1vc4jyih444vxwfc.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.22d5qe6x7h1ym6ye.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.24qp24wbjh4i9r8e.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.25cqehu6bk2tzvbm.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.275sls7nkx787tdd.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.29tjr8clw5y1rgjm.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.2c7l41c3owlzlutk.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.2f74xc4jb76o1893.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.2fsfccexqoonx5e.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.2jdsm1ghbsu2ivtb.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.2qb3kstih8htfgln.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.2tidepwrj14gjust.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.2v5paz8dyvarevg3.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.2xa7ud4juy275r8r.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.2zas6n44aluhfodc.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.32480oy07g65u0vn.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.32ahr4879xby5bwt.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.34157l53lng5yahj.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.3aaqvyhg76g7yd6w.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.3ad1b4rpmr1pwgle.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.3dmuomymen3bq7dd.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.3gre37e61jqhhkuq.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.3mg3hbkj4vixmd06.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.3n2rd2m24qvschna.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.3orier2zwrylogg.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.3tihlap3wz7uipik.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.3vq8v4t07r96y8a6.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.3x8n8z4014en3y2l.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.3xdg7ck1lo2x2slc.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.3xqiyqnr7rds1nfn.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.41grnk8ssoepdx6c.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.42pun2rxd44pfhn9.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.439kybdindab1sci.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.442hgz36p0fqfvu5.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.459o5jwhz2msbs4m.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.48ahqdqa585kbmee.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.48ssm3t53yc915uv.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.4c17k42ftvd11at1.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.4cve068ii8bwmxl1.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.4g9xcfj61t92fa2x.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.4hixeya2cqe2kuaz.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.4l43oeq94n8s2oz5.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.4v6een7ry8r9otyd.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.4w64374m7s0yebnr.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.50f6vtkc273fzvee.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.52cfsrwnkyr20wl5.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.5642e4r31g3kt4fn.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.5agzcxhcu6kh6ljp.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.5bizsw0m5ojexu3u.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.5d2484xq7wsmgs1a.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.5dt30xbh91lznarw.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.5fk2ptgksv6f0bp7.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.5fs3kxsbcxwbv2i8.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.7v7krim0ivg7tlo.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.7xqge75jrnboye9.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.acpi-0477cbc053069779.11ut7s04cl7pdocr.rcgu.o.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.acpi-0477cbc053069779.184qxycuqlczhlog.rcgu.o.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.acpi-0477cbc053069779.1eg49g7283kjnpaz.rcgu.o.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.acpi-0477cbc053069779.1lzsie18c6z27gpz.rcgu.o.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.acpi-0477cbc053069779.1p46cug066ufpk1w.rcgu.o.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.acpi-0477cbc053069779.1ry0lrvim0yngf51.rcgu.o.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.acpi-0477cbc053069779.24xulz6177ci8mpo.rcgu.o.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.acpi-0477cbc053069779.2a7o8q89wc4r2uzj.rcgu.o.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.acpi-0477cbc053069779.2g41jeq00zuwc8wt.rcgu.o.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.acpi-0477cbc053069779.2qdt85urzkdqqxfw.rcgu.o.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.acpi-0477cbc053069779.2szfsx5dc0rq03wr.rcgu.o.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.acpi-0477cbc053069779.2wbzl9817j2ryspf.rcgu.o.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.acpi-0477cbc053069779.32juxp8jdv1ip3e7.rcgu.o.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.acpi-0477cbc053069779.3hpufurfansxz0qt.rcgu.o.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.acpi-0477cbc053069779.3i25i2vjr9u3r576.rcgu.o.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.acpi-0477cbc053069779.3i74ojrrr9cf9uxi.rcgu.o.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.acpi-0477cbc053069779.3mxetzl60vv2afao.rcgu.o.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.acpi-0477cbc053069779.3tkk9pmuf5eoba8s.rcgu.o.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.acpi-0477cbc053069779.3ylkihaq54nehbhu.rcgu.o.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.acpi-0477cbc053069779.3zc2rosd1zmut98j.rcgu.o.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.acpi-0477cbc053069779.47lwvlo70wffy69m.rcgu.o.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.acpi-0477cbc053069779.48797s5wwxgunjlm.rcgu.o.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.acpi-0477cbc053069779.4cuh5m6iisy12vzp.rcgu.o.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.acpi-0477cbc053069779.4eqmnt9qe4z8fabm.rcgu.o.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.acpi-0477cbc053069779.4jr4qqy0c16v795r.rcgu.o.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.acpi-0477cbc053069779.4l0rp7j41doexyek.rcgu.o.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.acpi-0477cbc053069779.4m7xbwwbqik5xb84.rcgu.o.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.acpi-0477cbc053069779.4mcz50bu9hnpd9fx.rcgu.o.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.acpi-0477cbc053069779.4tvlwub85hbsr9i4.rcgu.o.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.acpi-0477cbc053069779.4w32kj3jehice591.rcgu.o.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.acpi-0477cbc053069779.55q3ksvnyv1vqu7b.rcgu.o.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.acpi-0477cbc053069779.56lzlq3q5qk3n7eh.rcgu.o.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.acpi-0477cbc053069779.56uyftl9wjxhtpf5.rcgu.o.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.acpi-0477cbc053069779.59jjkb5g786w73mz.rcgu.o.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.acpi-0477cbc053069779.5a1ogi2idax0xoil.rcgu.o.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.acpi-0477cbc053069779.5am3otixxdwcbfwr.rcgu.o.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.acpi-0477cbc053069779.5eix55qgfrhq9pxv.rcgu.o.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.acpi-0477cbc053069779.75dfp8nguj42vpr.rcgu.o.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.acpi-0477cbc053069779.dwxl0uhqzyy31xg.rcgu.o.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.acpi-0477cbc053069779.gm7b1s3vx83mqgl.rcgu.o.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.acpi-0477cbc053069779.i5l69rrug423sy0.rcgu.o.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.acpi-0477cbc053069779.jiciqiey0r8wq8i.rcgu.o.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.acpi-0477cbc053069779.nv14kf575q959o3.rcgu.o.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.acpi-0477cbc053069779.oawzqs8rnmicioa.rcgu.o.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.acpi-0477cbc053069779.p1qrbukhpoqbeii.rcgu.o.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.acpi-0477cbc053069779.pl8cctgw2wxwmx0.rcgu.o.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.acpi-0477cbc053069779.pwg3ylylp2nhk4j.rcgu.o.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.acpi-0477cbc053069779.s3nv2wtjh9fc8p1.rcgu.o.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.acpi-0477cbc053069779.s7h1op63eidsirs.rcgu.o.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.acpi-0477cbc053069779.ufo3xbx91z7a0zl.rcgu.o.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.acpi-0477cbc053069779.uwnv6cdhygx155d.rcgu.o.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.acpi-0477cbc053069779.w22ejo7wymvrjjh.rcgu.o.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.acpi-0477cbc053069779.xr4ok5scnxvp1ho.rcgu.o.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.alloc-7be5de7db84d9b97.alloc.264d9e4c-cgu.0.rcgu.o.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.alloc-7be5de7db84d9b97.alloc.264d9e4c-cgu.1.rcgu.o.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.alloc-7be5de7db84d9b97.alloc.264d9e4c-cgu.10.rcgu.o.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.alloc-7be5de7db84d9b97.alloc.264d9e4c-cgu.11.rcgu.o.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.alloc-7be5de7db84d9b97.alloc.264d9e4c-cgu.12.rcgu.o.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.alloc-7be5de7db84d9b97.alloc.264d9e4c-cgu.13.rcgu.o.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.alloc-7be5de7db84d9b97.alloc.264d9e4c-cgu.14.rcgu.o.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.alloc-7be5de7db84d9b97.alloc.264d9e4c-cgu.15.rcgu.o.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.alloc-7be5de7db84d9b97.alloc.264d9e4c-cgu.2.rcgu.o.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.alloc-7be5de7db84d9b97.alloc.264d9e4c-cgu.3.rcgu.o.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.alloc-7be5de7db84d9b97.alloc.264d9e4c-cgu.4.rcgu.o.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.alloc-7be5de7db84d9b97.alloc.264d9e4c-cgu.5.rcgu.o.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.alloc-7be5de7db84d9b97.alloc.264d9e4c-cgu.6.rcgu.o.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.alloc-7be5de7db84d9b97.alloc.264d9e4c-cgu.7.rcgu.o.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.alloc-7be5de7db84d9b97.alloc.264d9e4c-cgu.8.rcgu.o.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.alloc-7be5de7db84d9b97.alloc.264d9e4c-cgu.9.rcgu.o.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.amd64-fbef3751fd417b49.13swdsgov8g0955k.rcgu.o.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.amd64-fbef3751fd417b49.16s2wshj2ikmz65l.rcgu.o.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.amd64-fbef3751fd417b49.1aum826mf10axaoq.rcgu.o.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.amd64-fbef3751fd417b49.1cj97vbom0xg7fds.rcgu.o.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.amd64-fbef3751fd417b49.1hlfq5xgrh6kmsyl.rcgu.o.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.amd64-fbef3751fd417b49.1juigdwyhxvm8mzr.rcgu.o.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.amd64-fbef3751fd417b49.1lbdloo3aku25ppb.rcgu.o.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.amd64-fbef3751fd417b49.1ytuvgw6701fa3kr.rcgu.o.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.amd64-fbef3751fd417b49.2dg822odjj76efgy.rcgu.o.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.amd64-fbef3751fd417b49.2en9f3axax84eoxf.rcgu.o.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.amd64-fbef3751fd417b49.2kp8u4cdvy6kwujz.rcgu.o.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.amd64-fbef3751fd417b49.2ph1ue33d6v7ktwl.rcgu.o.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.amd64-fbef3751fd417b49.2pl0t2pt9y6wlesf.rcgu.o.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.amd64-fbef3751fd417b49.2q0g09ktf3tfvghh.rcgu.o.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.amd64-fbef3751fd417b49.2wseon759vket36x.rcgu.o.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.amd64-fbef3751fd417b49.38hwth94d35eati8.rcgu.o.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.amd64-fbef3751fd417b49.39846dd1xhhct7c9.rcgu.o.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.amd64-fbef3751fd417b49.3aw9vl3nkrniykcz.rcgu.o.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.amd64-fbef3751fd417b49.3b1hoyl6otqnu2h7.rcgu.o.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.amd64-fbef3751fd417b49.3eqeak31kw5xh4zw.rcgu.o.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.amd64-fbef3751fd417b49.3j0mmqwqytnspvg6.rcgu.o.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.amd64-fbef3751fd417b49.3xad8lsl1xnshrqj.rcgu.o.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.amd64-fbef3751fd417b49.4182hrcsoahe5d3x.rcgu.o.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.amd64-fbef3751fd417b49.4491o8xt4kj4fthg.rcgu.o.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.amd64-fbef3751fd417b49.46qn6b0omruer0wz.rcgu.o.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.amd64-fbef3751fd417b49.48nowtha82xkdffj.rcgu.o.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.amd64-fbef3751fd417b49.4bjuolucyxbpw9jc.rcgu.o.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.amd64-fbef3751fd417b49.4dpnqvohf3dsjjoi.rcgu.o.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.amd64-fbef3751fd417b49.4guxfysi63ss9jxk.rcgu.o.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.amd64-fbef3751fd417b49.4i7w41sqd7y2enig.rcgu.o.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.amd64-fbef3751fd417b49.4z6kzwwt8t2qf13l.rcgu.o.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.amd64-fbef3751fd417b49.58sobc0ugae7wm30.rcgu.o.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.amd64-fbef3751fd417b49.59dp0sg2d7yloqyi.rcgu.o.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.amd64-fbef3751fd417b49.8o9byfpqynqgpt1.rcgu.o.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.amd64-fbef3751fd417b49.gk7u1wz2dpp15ew.rcgu.o.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.amd64-fbef3751fd417b49.hs3m9b8kczziipg.rcgu.o.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.amd64-fbef3751fd417b49.kzeujz9eokx0lm.rcgu.o.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.amd64-fbef3751fd417b49.sycmhekifrqk6d3.rcgu.o.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.amd64-fbef3751fd417b49.yrlxj1nw7ybhq95.rcgu.o.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.ato497uqszce622.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.bit_field-593473af38cbca31.bit_field.719f43d7-cgu.0.rcgu.o.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.bitflags-7a792385de610a62.bitflags.1a40b536-cgu.0.rcgu.o.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.cfg_if-dbf890f07f19aa0d.cfg_if.c9e9c65a-cgu.0.rcgu.o.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.core-f393faa56f6a6cd8.core.69082225-cgu.0.rcgu.o.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.core-f393faa56f6a6cd8.core.69082225-cgu.1.rcgu.o.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.core-f393faa56f6a6cd8.core.69082225-cgu.10.rcgu.o.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.core-f393faa56f6a6cd8.core.69082225-cgu.11.rcgu.o.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.core-f393faa56f6a6cd8.core.69082225-cgu.12.rcgu.o.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.core-f393faa56f6a6cd8.core.69082225-cgu.13.rcgu.o.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.core-f393faa56f6a6cd8.core.69082225-cgu.14.rcgu.o.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.core-f393faa56f6a6cd8.core.69082225-cgu.15.rcgu.o.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.core-f393faa56f6a6cd8.core.69082225-cgu.2.rcgu.o.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.core-f393faa56f6a6cd8.core.69082225-cgu.3.rcgu.o.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.core-f393faa56f6a6cd8.core.69082225-cgu.4.rcgu.o.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.core-f393faa56f6a6cd8.core.69082225-cgu.5.rcgu.o.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.core-f393faa56f6a6cd8.core.69082225-cgu.6.rcgu.o.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.core-f393faa56f6a6cd8.core.69082225-cgu.7.rcgu.o.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.core-f393faa56f6a6cd8.core.69082225-cgu.8.rcgu.o.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.core-f393faa56f6a6cd8.core.69082225-cgu.9.rcgu.o.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.f7mgtyqjvlkqnr.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.g6ewn9j0ywo5xvo.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.goblin-bfa1039b2dccf78e.goblin.113e4044-cgu.0.rcgu.o.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.goblin-bfa1039b2dccf78e.goblin.113e4044-cgu.1.rcgu.o.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.goblin-bfa1039b2dccf78e.goblin.113e4044-cgu.10.rcgu.o.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.goblin-bfa1039b2dccf78e.goblin.113e4044-cgu.11.rcgu.o.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.goblin-bfa1039b2dccf78e.goblin.113e4044-cgu.12.rcgu.o.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.goblin-bfa1039b2dccf78e.goblin.113e4044-cgu.13.rcgu.o.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.goblin-bfa1039b2dccf78e.goblin.113e4044-cgu.14.rcgu.o.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.goblin-bfa1039b2dccf78e.goblin.113e4044-cgu.15.rcgu.o.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.goblin-bfa1039b2dccf78e.goblin.113e4044-cgu.2.rcgu.o.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.goblin-bfa1039b2dccf78e.goblin.113e4044-cgu.3.rcgu.o.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.goblin-bfa1039b2dccf78e.goblin.113e4044-cgu.4.rcgu.o.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.goblin-bfa1039b2dccf78e.goblin.113e4044-cgu.5.rcgu.o.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.goblin-bfa1039b2dccf78e.goblin.113e4044-cgu.6.rcgu.o.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.goblin-bfa1039b2dccf78e.goblin.113e4044-cgu.7.rcgu.o.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.goblin-bfa1039b2dccf78e.goblin.113e4044-cgu.8.rcgu.o.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.goblin-bfa1039b2dccf78e.goblin.113e4044-cgu.9.rcgu.o.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.kaboom-78b03706628a2e8d.112brepwhqnwgdut.rcgu.o.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.kaboom-78b03706628a2e8d.1hup4i8hs99eevrw.rcgu.o.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.kaboom-78b03706628a2e8d.26v23whhdd3699aa.rcgu.o.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.kaboom-78b03706628a2e8d.299w1tejfsg8cgru.rcgu.o.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.kaboom-78b03706628a2e8d.2ejuiqvxjovszsma.rcgu.o.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.kaboom-78b03706628a2e8d.335zk8yl1cfclday.rcgu.o.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.kaboom-78b03706628a2e8d.37xn99t001y1pybx.rcgu.o.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.kaboom-78b03706628a2e8d.3bcxum57fb3tgedj.rcgu.o.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.kaboom-78b03706628a2e8d.3f10wbldtbxqivxy.rcgu.o.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.kaboom-78b03706628a2e8d.3gatbrxm2r1crby8.rcgu.o.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.kaboom-78b03706628a2e8d.48rn18f2xd0t0udw.rcgu.o.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.kaboom-78b03706628a2e8d.4jeni5h85t0ntigr.rcgu.o.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.kaboom-78b03706628a2e8d.4oehnu0jlgvb9a3k.rcgu.o.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.kaboom-78b03706628a2e8d.52ltncdkgbcd6wc5.rcgu.o.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.kaboom-78b03706628a2e8d.j259mliqi2o0kkp.rcgu.o.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.log-7f4f5eb304fc734c.log.eedf02e3-cgu.0.rcgu.o.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.log-7f4f5eb304fc734c.log.eedf02e3-cgu.1.rcgu.o.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.log-7f4f5eb304fc734c.log.eedf02e3-cgu.10.rcgu.o.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.log-7f4f5eb304fc734c.log.eedf02e3-cgu.11.rcgu.o.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.log-7f4f5eb304fc734c.log.eedf02e3-cgu.12.rcgu.o.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.log-7f4f5eb304fc734c.log.eedf02e3-cgu.13.rcgu.o.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.log-7f4f5eb304fc734c.log.eedf02e3-cgu.14.rcgu.o.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.log-7f4f5eb304fc734c.log.eedf02e3-cgu.15.rcgu.o.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.log-7f4f5eb304fc734c.log.eedf02e3-cgu.2.rcgu.o.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.log-7f4f5eb304fc734c.log.eedf02e3-cgu.3.rcgu.o.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.log-7f4f5eb304fc734c.log.eedf02e3-cgu.4.rcgu.o.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.log-7f4f5eb304fc734c.log.eedf02e3-cgu.5.rcgu.o.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.log-7f4f5eb304fc734c.log.eedf02e3-cgu.6.rcgu.o.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.log-7f4f5eb304fc734c.log.eedf02e3-cgu.7.rcgu.o.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.log-7f4f5eb304fc734c.log.eedf02e3-cgu.8.rcgu.o.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.log-7f4f5eb304fc734c.log.eedf02e3-cgu.9.rcgu.o.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.lr3ne3u15k10otk.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.modular_bitfield-6689f4aec36cf35c.modular_bitfield.28f4b8ea-cgu.0.rcgu.o.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.modular_bitfield-6689f4aec36cf35c.modular_bitfield.28f4b8ea-cgu.1.rcgu.o.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.modular_bitfield-6689f4aec36cf35c.modular_bitfield.28f4b8ea-cgu.2.rcgu.o.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.modular_bitfield-6689f4aec36cf35c.modular_bitfield.28f4b8ea-cgu.3.rcgu.o.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.plain-1ceb16850932eebd.plain.c581b585-cgu.0.rcgu.o.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.qlharlnzvobqi52.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.rustc_std_workspace_core-914b8d2849fe932d.rustc_std_workspace_core.59db470c-cgu.0.rcgu.o.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.s90cspb88isuv2g.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.scroll-24d96cafe0f4ba41.scroll.1ac65fde-cgu.0.rcgu.o.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.scroll-24d96cafe0f4ba41.scroll.1ac65fde-cgu.1.rcgu.o.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.scroll-24d96cafe0f4ba41.scroll.1ac65fde-cgu.2.rcgu.o.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.scroll-24d96cafe0f4ba41.scroll.1ac65fde-cgu.3.rcgu.o.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.scroll-24d96cafe0f4ba41.scroll.1ac65fde-cgu.4.rcgu.o.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.scroll-24d96cafe0f4ba41.scroll.1ac65fde-cgu.5.rcgu.o.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.static_assertions-22687176e86cc0d1.static_assertions.9eb0569f-cgu.0.rcgu.o.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.ucs2-d793d88343680a62.ucs2.04af408a-cgu.0.rcgu.o.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.ucs2-d793d88343680a62.ucs2.04af408a-cgu.1.rcgu.o.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.ucs2-d793d88343680a62.ucs2.04af408a-cgu.10.rcgu.o.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.ucs2-d793d88343680a62.ucs2.04af408a-cgu.11.rcgu.o.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.ucs2-d793d88343680a62.ucs2.04af408a-cgu.12.rcgu.o.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.ucs2-d793d88343680a62.ucs2.04af408a-cgu.13.rcgu.o.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.ucs2-d793d88343680a62.ucs2.04af408a-cgu.2.rcgu.o.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.ucs2-d793d88343680a62.ucs2.04af408a-cgu.3.rcgu.o.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.ucs2-d793d88343680a62.ucs2.04af408a-cgu.4.rcgu.o.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.ucs2-d793d88343680a62.ucs2.04af408a-cgu.5.rcgu.o.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.ucs2-d793d88343680a62.ucs2.04af408a-cgu.6.rcgu.o.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.ucs2-d793d88343680a62.ucs2.04af408a-cgu.7.rcgu.o.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.ucs2-d793d88343680a62.ucs2.04af408a-cgu.8.rcgu.o.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.ucs2-d793d88343680a62.ucs2.04af408a-cgu.9.rcgu.o.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.uefi-da922a5253fe8cd7.uefi.86782151-cgu.0.rcgu.o.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.uefi-da922a5253fe8cd7.uefi.86782151-cgu.1.rcgu.o.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.uefi-da922a5253fe8cd7.uefi.86782151-cgu.10.rcgu.o.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.uefi-da922a5253fe8cd7.uefi.86782151-cgu.11.rcgu.o.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.uefi-da922a5253fe8cd7.uefi.86782151-cgu.12.rcgu.o.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.uefi-da922a5253fe8cd7.uefi.86782151-cgu.13.rcgu.o.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.uefi-da922a5253fe8cd7.uefi.86782151-cgu.14.rcgu.o.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.uefi-da922a5253fe8cd7.uefi.86782151-cgu.15.rcgu.o.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.uefi-da922a5253fe8cd7.uefi.86782151-cgu.2.rcgu.o.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.uefi-da922a5253fe8cd7.uefi.86782151-cgu.3.rcgu.o.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.uefi-da922a5253fe8cd7.uefi.86782151-cgu.4.rcgu.o.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.uefi-da922a5253fe8cd7.uefi.86782151-cgu.5.rcgu.o.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.uefi-da922a5253fe8cd7.uefi.86782151-cgu.6.rcgu.o.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.uefi-da922a5253fe8cd7.uefi.86782151-cgu.7.rcgu.o.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.uefi-da922a5253fe8cd7.uefi.86782151-cgu.8.rcgu.o.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.uefi-da922a5253fe8cd7.uefi.86782151-cgu.9.rcgu.o.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.uefi_services-3166955552e101cc.uefi_services.08e9a66a-cgu.0.rcgu.o.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.uefi_services-3166955552e101cc.uefi_services.08e9a66a-cgu.1.rcgu.o.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.uefi_services-3166955552e101cc.uefi_services.08e9a66a-cgu.10.rcgu.o.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.uefi_services-3166955552e101cc.uefi_services.08e9a66a-cgu.11.rcgu.o.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.uefi_services-3166955552e101cc.uefi_services.08e9a66a-cgu.12.rcgu.o.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.uefi_services-3166955552e101cc.uefi_services.08e9a66a-cgu.13.rcgu.o.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.uefi_services-3166955552e101cc.uefi_services.08e9a66a-cgu.14.rcgu.o.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.uefi_services-3166955552e101cc.uefi_services.08e9a66a-cgu.15.rcgu.o.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.uefi_services-3166955552e101cc.uefi_services.08e9a66a-cgu.2.rcgu.o.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.uefi_services-3166955552e101cc.uefi_services.08e9a66a-cgu.3.rcgu.o.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.uefi_services-3166955552e101cc.uefi_services.08e9a66a-cgu.4.rcgu.o.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.uefi_services-3166955552e101cc.uefi_services.08e9a66a-cgu.5.rcgu.o.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.uefi_services-3166955552e101cc.uefi_services.08e9a66a-cgu.6.rcgu.o.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.uefi_services-3166955552e101cc.uefi_services.08e9a66a-cgu.7.rcgu.o.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.uefi_services-3166955552e101cc.uefi_services.08e9a66a-cgu.8.rcgu.o.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.uefi_services-3166955552e101cc.uefi_services.08e9a66a-cgu.9.rcgu.o.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.wdszhxj8j80rtqz.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.ws7z87msg2yw562.rcgu.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.ycckb53aw9ntsfd.rcgu.o" "/LIBPATH:/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps" "/LIBPATH:/Users/visualdevel/Developer/FWLauncher/target/debug/deps" "/LIBPATH:/Users/visualdevel/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/x86_64-unknown-uefi/lib" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/libcompiler_builtins-38c2cee9d3a6e440.rlib" "/NXCOMPAT" "/LIBPATH:/Users/visualdevel/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/x86_64-unknown-uefi/lib" "/OUT:/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-ed91ffee5f0f7993.efi" "/OPT:REF,NOICF" "/DEBUG" "/NODEFAULTLIB"
  = note: rust-lld: error: undefined symbol: core::intrinsics::const_eval_select::he0701d019b187a68
          >>> referenced by /Users/visualdevel/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/num/f32.rs:942
          >>>               libcompiler_builtins-38c2cee9d3a6e440.rlib(compiler_builtins-38c2cee9d3a6e440.compiler_builtins.0de39e8f-cgu.12.rcgu.o):(core::f32::_$LT$impl$u20$f32$GT$::to_bits::h1acae0bbda7c0dc2)

          rust-lld: error: undefined symbol: core::intrinsics::const_eval_select::hee4dc3e45db98cb7
          >>> referenced by /Users/visualdevel/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/num/f32.rs:1030
          >>>               libcompiler_builtins-38c2cee9d3a6e440.rlib(compiler_builtins-38c2cee9d3a6e440.compiler_builtins.0de39e8f-cgu.12.rcgu.o):(core::f32::_$LT$impl$u20$f32$GT$::from_bits::hb34bd8fbe5269edf)

          rust-lld: error: undefined symbol: core::intrinsics::const_eval_select::h40736e1cc1f6c06d
          >>> referenced by /Users/visualdevel/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/num/f64.rs:935
          >>>               libcompiler_builtins-38c2cee9d3a6e440.rlib(compiler_builtins-38c2cee9d3a6e440.compiler_builtins.0de39e8f-cgu.12.rcgu.o):(core::f64::_$LT$impl$u20$f64$GT$::to_bits::hcee6547be61594e6)

          rust-lld: error: undefined symbol: core::intrinsics::const_eval_select::h16ca3881705cadde
          >>> referenced by /Users/visualdevel/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/num/f64.rs:1028
          >>>               libcompiler_builtins-38c2cee9d3a6e440.rlib(compiler_builtins-38c2cee9d3a6e440.compiler_builtins.0de39e8f-cgu.12.rcgu.o):(core::f64::_$LT$impl$u20$f64$GT$::from_bits::h36bdcfbfe460db46)


error: could not compile `fwlauncher` due to previous error
```

</p>
</details>

While on full LTO it's even worse:
<details><summary>Compiler Output (click)</summary>
<p>

```
error: linking with `rust-lld` failed: exit status: 1
  |
  = note: "rust-lld" "-flavor" "link" "/NOLOGO" "/entry:efi_main" "/subsystem:efi_application" "/var/folders/fp/w6d3psl51lgf5w8pk08d2frw0000gn/T/rustcvlpDLU/symbols.o" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-5f52ae816ef87061.goblin-5192977218db1b81.goblin.c9b8d717-cgu.0.rcgu.o.rcgu.o" "/LIBPATH:/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps" "/LIBPATH:/Users/visualdevel/Developer/FWLauncher/target/debug/deps" "/LIBPATH:/Users/visualdevel/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/x86_64-unknown-uefi/lib" "/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/libcompiler_builtins-a8fbb790a59498a0.rlib" "/NXCOMPAT" "/LIBPATH:/Users/visualdevel/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/x86_64-unknown-uefi/lib" "/OUT:/Users/visualdevel/Developer/FWLauncher/target/x86_64-unknown-uefi/debug/deps/bootx64-5f52ae816ef87061.efi" "/OPT:REF,NOICF" "/DEBUG" "/NODEFAULTLIB"
  = note: rust-lld: error: undefined symbol: core::panicking::panic::h69766d17d6745c28
          >>> referenced by /Users/visualdevel/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/ops/bit.rs:476
          >>>               libcompiler_builtins-a8fbb790a59498a0.rlib(compiler_builtins-a8fbb790a59498a0.compiler_builtins.9189e95f-cgu.15.rcgu.o):(_$LT$u32$u20$as$u20$core..ops..bit..Shl$GT$::shl::hff8117e6e71404d6)
          >>> referenced by /Users/visualdevel/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/ops/bit.rs:595
          >>>               libcompiler_builtins-a8fbb790a59498a0.rlib(compiler_builtins-a8fbb790a59498a0.compiler_builtins.9189e95f-cgu.15.rcgu.o):(_$LT$u32$u20$as$u20$core..ops..bit..Shr$GT$::shr::h312682acc897e2fb)
          >>> referenced by /Users/visualdevel/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/ops/bit.rs:1018
          >>>               libcompiler_builtins-a8fbb790a59498a0.rlib(compiler_builtins-a8fbb790a59498a0.compiler_builtins.9189e95f-cgu.15.rcgu.o):(_$LT$u32$u20$as$u20$core..ops..bit..ShrAssign$GT$::shr_assign::h09d7c87390a4e574)
          >>> referenced 574 more times

          rust-lld: error: undefined symbol: core::ptr::const_ptr::_$LT$impl$u20$$BP$const$u20$T$GT$::guaranteed_eq::h14f63b9afcaf9c37
          >>> referenced by /Users/visualdevel/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/ptr/const_ptr.rs:39
          >>>               libcompiler_builtins-a8fbb790a59498a0.rlib(compiler_builtins-a8fbb790a59498a0.compiler_builtins.9189e95f-cgu.4.rcgu.o):(core::ptr::const_ptr::_$LT$impl$u20$$BP$const$u20$T$GT$::is_null::h87992f33b09fd3ce)
          >>> referenced by /Users/visualdevel/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/ptr/const_ptr.rs:39
          >>>               libcompiler_builtins-a8fbb790a59498a0.rlib(compiler_builtins-a8fbb790a59498a0.compiler_builtins.9189e95f-cgu.4.rcgu.o):(core::ptr::const_ptr::_$LT$impl$u20$$BP$const$u20$T$GT$::is_null::he9b65571c82325aa)

          rust-lld: error: undefined symbol: core::ptr::const_ptr::_$LT$impl$u20$$BP$const$u20$$u5b$T$u5d$$GT$::as_ptr::h4bcffb3704529ba4
          >>> referenced by /Users/visualdevel/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/slice/index.rs:226
          >>>               libcompiler_builtins-a8fbb790a59498a0.rlib(compiler_builtins-a8fbb790a59498a0.compiler_builtins.9189e95f-cgu.8.rcgu.o):(_$LT$usize$u20$as$u20$core..slice..index..SliceIndex$LT$$u5b$T$u5d$$GT$$GT$::get_unchecked::haa6b517c0823ed03)

          rust-lld: error: undefined symbol: core::ptr::const_ptr::_$LT$impl$u20$$BP$const$u20$$u5b$T$u5d$$GT$::len::h63cbd6dacb6094a7
          >>> referenced by /Users/visualdevel/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/slice/index.rs:225
          >>>               libcompiler_builtins-a8fbb790a59498a0.rlib(compiler_builtins-a8fbb790a59498a0.compiler_builtins.9189e95f-cgu.8.rcgu.o):(_$LT$usize$u20$as$u20$core..slice..index..SliceIndex$LT$$u5b$T$u5d$$GT$$GT$::get_unchecked::_$u7b$$u7b$closure$u7d$$u7d$::hc5da8d1ea42a314a)

          rust-lld: error: undefined symbol: core::intrinsics::const_eval_select::hcfb916065d08dcaf
          >>> referenced by /Users/visualdevel/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/num/f32.rs:942
          >>>               libcompiler_builtins-a8fbb790a59498a0.rlib(compiler_builtins-a8fbb790a59498a0.compiler_builtins.9189e95f-cgu.12.rcgu.o):(core::f32::_$LT$impl$u20$f32$GT$::to_bits::hb2f86b51f18bf9ab)

          rust-lld: error: undefined symbol: core::intrinsics::const_eval_select::h0d3e5971beca728d
          >>> referenced by /Users/visualdevel/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/num/f32.rs:1030
          >>>               libcompiler_builtins-a8fbb790a59498a0.rlib(compiler_builtins-a8fbb790a59498a0.compiler_builtins.9189e95f-cgu.12.rcgu.o):(core::f32::_$LT$impl$u20$f32$GT$::from_bits::hf88c1b50f241c2a6)

          rust-lld: error: undefined symbol: core::intrinsics::const_eval_select::h4039f20961280450
          >>> referenced by /Users/visualdevel/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/num/f64.rs:935
          >>>               libcompiler_builtins-a8fbb790a59498a0.rlib(compiler_builtins-a8fbb790a59498a0.compiler_builtins.9189e95f-cgu.12.rcgu.o):(core::f64::_$LT$impl$u20$f64$GT$::to_bits::h6ce36224f97e6285)

          rust-lld: error: undefined symbol: core::intrinsics::const_eval_select::h1e2fe5fe20d93177
          >>> referenced by /Users/visualdevel/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/num/f64.rs:1028
          >>>               libcompiler_builtins-a8fbb790a59498a0.rlib(compiler_builtins-a8fbb790a59498a0.compiler_builtins.9189e95f-cgu.12.rcgu.o):(core::f64::_$LT$impl$u20$f64$GT$::from_bits::he05503d14049bce8)

          rust-lld: error: undefined symbol: _$LT$I$u20$as$u20$core..iter..traits..collect..IntoIterator$GT$::into_iter::he1b706f828c0cef2
          >>> referenced by /Users/visualdevel/.cargo/registry/src/github.com-1ecc6299db9ec823/compiler_builtins-0.1.71/src/../libm/src/math/rem_pio2.rs:174
          >>>               libcompiler_builtins-a8fbb790a59498a0.rlib(compiler_builtins-a8fbb790a59498a0.compiler_builtins.9189e95f-cgu.12.rcgu.o):(compiler_builtins::math::libm::rem_pio2::rem_pio2::hd4f7a0810b4a4d4c)
          >>> referenced by /Users/visualdevel/.cargo/registry/src/github.com-1ecc6299db9ec823/compiler_builtins-0.1.71/src/../libm/src/math/rem_pio2_large.rs:313
          >>>               libcompiler_builtins-a8fbb790a59498a0.rlib(compiler_builtins-a8fbb790a59498a0.compiler_builtins.9189e95f-cgu.9.rcgu.o):(compiler_builtins::math::libm::rem_pio2_large::rem_pio2_large::h14effa88a0fcdc20)

          rust-lld: error: undefined symbol: core::iter::range::_$LT$impl$u20$core..iter..traits..iterator..Iterator$u20$for$u20$core..ops..range..Range$LT$A$GT$$GT$::next::h01548e81c4addb49
          >>> referenced by /Users/visualdevel/.cargo/registry/src/github.com-1ecc6299db9ec823/compiler_builtins-0.1.71/src/../libm/src/math/rem_pio2.rs:174
          >>>               libcompiler_builtins-a8fbb790a59498a0.rlib(compiler_builtins-a8fbb790a59498a0.compiler_builtins.9189e95f-cgu.12.rcgu.o):(compiler_builtins::math::libm::rem_pio2::rem_pio2::hd4f7a0810b4a4d4c)
          >>> referenced by /Users/visualdevel/.cargo/registry/src/github.com-1ecc6299db9ec823/compiler_builtins-0.1.71/src/../libm/src/math/rem_pio2_large.rs:313
          >>>               libcompiler_builtins-a8fbb790a59498a0.rlib(compiler_builtins-a8fbb790a59498a0.compiler_builtins.9189e95f-cgu.9.rcgu.o):(compiler_builtins::math::libm::rem_pio2_large::rem_pio2_large::h14effa88a0fcdc20)

          rust-lld: error: undefined symbol: core::slice::index::slice_index_order_fail::h53c3aab39937a232
          >>> referenced by /Users/visualdevel/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/slice/index.rs:302
          >>>               libcompiler_builtins-a8fbb790a59498a0.rlib(compiler_builtins-a8fbb790a59498a0.compiler_builtins.9189e95f-cgu.6.rcgu.o):(_$LT$core..ops..range..Range$LT$usize$GT$$u20$as$u20$core..slice..index..SliceIndex$LT$$u5b$T$u5d$$GT$$GT$::index::h1b9e5e0619e51d00)

          rust-lld: error: undefined symbol: core::slice::index::slice_end_index_len_fail::hf16c69ae4b53679a
          >>> referenced by /Users/visualdevel/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/slice/index.rs:304
          >>>               libcompiler_builtins-a8fbb790a59498a0.rlib(compiler_builtins-a8fbb790a59498a0.compiler_builtins.9189e95f-cgu.6.rcgu.o):(_$LT$core..ops..range..Range$LT$usize$GT$$u20$as$u20$core..slice..index..SliceIndex$LT$$u5b$T$u5d$$GT$$GT$::index::h1b9e5e0619e51d00)

          rust-lld: error: undefined symbol: core::mem::replace::hbf2b8b6763ea1493
          >>> referenced by /Users/visualdevel/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/iter/range.rs:1058
          >>>               libcompiler_builtins-a8fbb790a59498a0.rlib(compiler_builtins-a8fbb790a59498a0.compiler_builtins.9189e95f-cgu.6.rcgu.o):(_$LT$core..ops..range..RangeInclusive$LT$T$GT$$u20$as$u20$core..iter..range..RangeInclusiveIteratorImpl$GT$::spec_next_back::ha3a2144d26032682)
          >>> referenced by /Users/visualdevel/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/iter/range.rs:1013
          >>>               libcompiler_builtins-a8fbb790a59498a0.rlib(compiler_builtins-a8fbb790a59498a0.compiler_builtins.9189e95f-cgu.6.rcgu.o):(_$LT$core..ops..range..RangeInclusive$LT$T$GT$$u20$as$u20$core..iter..range..RangeInclusiveIteratorImpl$GT$::spec_next::h4846798ae8dd91eb)

          rust-lld: error: undefined symbol: core::ops::range::RangeInclusive$LT$Idx$GT$::end::h33ee871cef07fa7b
          >>> referenced by /Users/visualdevel/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/slice/index.rs:471
          >>>               libcompiler_builtins-a8fbb790a59498a0.rlib(compiler_builtins-a8fbb790a59498a0.compiler_builtins.9189e95f-cgu.6.rcgu.o):(_$LT$core..ops..range..RangeInclusive$LT$usize$GT$$u20$as$u20$core..slice..index..SliceIndex$LT$$u5b$T$u5d$$GT$$GT$::index::hb2055ad8c6fe48cc)

          rust-lld: error: undefined symbol: core::slice::index::slice_end_index_overflow_fail::h582261f4d590c4c4
          >>> referenced by /Users/visualdevel/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/slice/index.rs:472
          >>>               libcompiler_builtins-a8fbb790a59498a0.rlib(compiler_builtins-a8fbb790a59498a0.compiler_builtins.9189e95f-cgu.6.rcgu.o):(_$LT$core..ops..range..RangeInclusive$LT$usize$GT$$u20$as$u20$core..slice..index..SliceIndex$LT$$u5b$T$u5d$$GT$$GT$::index::hb2055ad8c6fe48cc)

          rust-lld: error: undefined symbol: core::ops::range::RangeInclusive$LT$Idx$GT$::new::h5e54cbb0bf539c8f
          >>> referenced by /Users/visualdevel/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/slice/index.rs:515
          >>>               libcompiler_builtins-a8fbb790a59498a0.rlib(compiler_builtins-a8fbb790a59498a0.compiler_builtins.9189e95f-cgu.6.rcgu.o):(_$LT$core..ops..range..RangeToInclusive$LT$usize$GT$$u20$as$u20$core..slice..index..SliceIndex$LT$$u5b$T$u5d$$GT$$GT$::index::h179072b603e71aee)
          >>> referenced by /Users/visualdevel/.cargo/registry/src/github.com-1ecc6299db9ec823/compiler_builtins-0.1.71/src/../libm/src/math/rem_pio2_large.rs:260
          >>>               libcompiler_builtins-a8fbb790a59498a0.rlib(compiler_builtins-a8fbb790a59498a0.compiler_builtins.9189e95f-cgu.9.rcgu.o):(compiler_builtins::math::libm::rem_pio2_large::rem_pio2_large::h14effa88a0fcdc20)
          >>> referenced by /Users/visualdevel/.cargo/registry/src/github.com-1ecc6299db9ec823/compiler_builtins-0.1.71/src/../libm/src/math/rem_pio2_large.rs:270
          >>>               libcompiler_builtins-a8fbb790a59498a0.rlib(compiler_builtins-a8fbb790a59498a0.compiler_builtins.9189e95f-cgu.9.rcgu.o):(compiler_builtins::math::libm::rem_pio2_large::rem_pio2_large::h14effa88a0fcdc20)
          >>> referenced 13 more times


error: could not compile `fwlauncher` due to previous error
```

</p>
</details>

This wasn't happening a few versions back, but currently not sure since which version this broke.
As a temporary workaround, I've disabled LTO on profile.dev

### LINKED ISSUE #105734: rust-lld: lto="fat" prunes symbols that are used
When compiling on `riscv32imac-unknown-xous-elf`, occasionally there is a linker error where the linker removes `core::panicking::panic_str_nounwind::h9b449c0fe03c8dac` and then complains that the symbol does not exist. It is trying to call this function from `compiler_builtins::math::libm::rem_pio2_large::rem_pio2_large::h3db6431f23a281c1`.

Building with `lto="thin"` does not prune this symbol. Additionally, other crates do not have trouble, even if they call `f32::sin()` or `f32::cos()` which seem to use these functions.

Test code:

```rust
fn main() {
    for i in 0..2 {
        let x = i as f32;
        println!("cosf(x): {}", x.cos());
    }
}
```

Cargo.toml:

```toml
[package]
name = "libm_test"
version = "0.1.0"
edition = "2021"

[profile.dev]
lto = "fat"
```

### Meta

`rustc --version --verbose`:
```
rustc 1.66.0 (69f9c33d7 2022-12-12)
binary: rustc
commit-hash: 69f9c33d71c871fc16ac445211281c6e7a340943
commit-date: 2022-12-12
host: x86_64-pc-windows-msvc
release: 1.66.0
LLVM version: 15.0.2
```

<details><summary>Build Output</summary>
<p>

```
[1:43:32 pm] E:/Code/Xous/libm_test> cargo build --target riscv32imac-unknown-xous-elf
   Compiling libm_test v0.1.0 (E:\Code\Xous\libm_test)
error: linking with `rust-lld` failed: exit code: 1
  |
  = note: "rust-lld" "-flavor" "gnu" "C:\\Users\\Sean\\AppData\\Local\\Temp\\rustcc9RUUw\\symbols.o" "E:\\Code\\Xous\\libm_test\\target\\riscv32imac-unknown-xous-elf\\debug\\deps\\libm_test-76ee56b79358e7a1.std-ebb179c122f95043.std.3da42809-cgu.0.rcgu.o.rcgu.o" "--as-needed" "-L" "E:\\Code\\Xous\\libm_test\\target\\riscv32imac-unknown-xous-elf\\debug\\deps" "-L" "E:\\Code\\Xous\\libm_test\\target\\debug\\deps" "-L" "C:\\Users\\Sean\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\riscv32imac-unknown-xous-elf\\lib" "-Bstatic" "C:\\Users\\Sean\\AppData\\Local\\Temp\\rustcc9RUUw\\libxous-22b3b9f34be0acc4.rlib" "C:\\Users\\Sean\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\riscv32imac-unknown-xous-elf\\lib\\libcompiler_builtins-b913bacb8fda1c55.rlib" "-Bdynamic" "--eh-frame-hdr" "-znoexecstack" "-L" "C:\\Users\\Sean\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\riscv32imac-unknown-xous-elf\\lib" "-o" "E:\\Code\\Xous\\libm_test\\target\\riscv32imac-unknown-xous-elf\\debug\\deps\\libm_test-76ee56b79358e7a1" "--gc-sections"
  = note: rust-lld: error: undefined symbol: core::panicking::panic_str_nounwind::h9b449c0fe03c8dac
          >>> referenced by compiler_builtins.22a3dcb1-cgu.13
          >>>               compiler_builtins-b913bacb8fda1c55.compiler_builtins.22a3dcb1-cgu.13.rcgu.o:(compiler_builtins::math::libm::rem_pio2_large::rem_pio2_large::h3db6431f23a281c1) in archive C:\Users\Sean\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\riscv32imac-unknown-xous-elf\lib\libcompiler_builtins-b913bacb8fda1c55.rlib
          >>> referenced by compiler_builtins.22a3dcb1-cgu.13
          >>>               compiler_builtins-b913bacb8fda1c55.compiler_builtins.22a3dcb1-cgu.13.rcgu.o:(compiler_builtins::math::libm::rem_pio2_large::rem_pio2_large::h3db6431f23a281c1) in archive C:\Users\Sean\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\riscv32imac-unknown-xous-elf\lib\libcompiler_builtins-b913bacb8fda1c55.rlib


error: could not compile `libm_test` due to previous error
[1:43:40 pm] E:/Code/Xous/libm_test>
```

</p>
</details>

### LINKED ISSUE #108853: Latest nightly are failing to build non-toy projects at linking stage when using LTO optimization
After updating to the latest version of Rust, I found that many of my projects are failing to compile at linking stage when doing size-optimized builds (cf. https://github.com/johnthagen/min-sized-rust). I found the possible nightly-to-nightly regression to be from `nightly-2023-02-27` to `nightly-2023-02-28`. This seems to be a real issue since min-sized builds are widely used. Also I failed to reproduce this in a toy project.

To trigger that "bug" I used these compiler flags:
```bash
OPTI_FLAGS="-C link-dead-code=n -C lto=fat -C opt-level=z -C embed-bitcode=yes -C panic=abort"
OPTI_ARGS="-Z build-std=std,panic_abort -Z build-std-features=panic_immediate_abort"

# for linux you might want to use -C panic=abort to overpass another bug

RUSTFLAGS=$OPTI_FLAGS cargo +nightly build --target x86_64-unknown-linux-gnu --release $OPTI_ARGS
RUSTFLAGS=$OPTI_FLAGS XWIN_ARCH="x86_64" XWIN_CACHE_DIR="/tmp/xwin_64" cargo +nightly xwin build --target x86_64-pc-windows-msvc --release $OPTI_ARGS
```

Possible linked issues:
- https://github.com/rust-lang/rust/issues/107016
- https://github.com/rust-lang/rust/issues/108030
- https://github.com/rust-lang/compiler-builtins/issues/347

I tried to build those projects with the latest working nightly (`nightly-2023-02-27`) and the first non-working nightly (`nightly-2023-02-28`):
- RustHound (https://github.com/OPENCYBER-FR/RustHound - 534 stars)
- RustScan (https://github.com/RustScan/RustScan - 9.4k stars)
- Helix (https://github.com/helix-editor/helix - 19.6k stars)

I expected to see this happen: build succeed in both cases.

Instead, this happened: linker errors on the first non-working nightly (`nightly-2023-02-28`) and compile success with the latest working nightly (`nightly-2023-02-27`). This show a possible regression.

For RustHound (using `nightly-2023-02-28`):
<details><summary>Compile error</summary>
<p>

```
   Compiling rusthound v1.1.62 (/$USER/Projets/XXX/RustHound)
error: linking with `lld-link` failed: exit status: 1
  |
  = note: LC_ALL="C" PATH="/$USER/.rustup/toolchains/nightly-2023-02-28-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/bin:/$USER/.vscode-server/bin/441438abd1ac652551dbe4d408dfcec8a499b8bf/bin/remote-cli:/$USER/.local/bin:/$USER/.cargo/bin:/$USER/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/tmp" VSLANG="1033" "lld-link" "-flavor" "link" "/NOLOGO" "/tmp/rustcAWOQqQ/symbols.o" "/$USER/Projets/XXX/RustHound/target/x86_64-pc-windows-msvc/release/deps/rusthound.rusthound.4bfd0cff-cgu.3.rcgu.o" "/LIBPATH:/$USER/Projets/XXX/RustHound/target/x86_64-pc-windows-msvc/release/deps" "/LIBPATH:/$USER/Projets/XXX/RustHound/target/release/deps" "/LIBPATH:/tmp/xwin_64/crt/lib/x86_64" "/LIBPATH:/tmp/xwin_64/sdk/lib/um/x86_64" "/LIBPATH:/tmp/xwin_64/sdk/lib/ucrt/x86_64" "/LIBPATH:/$USER/.cargo/registry/src/github.com-1ecc6299db9ec823/windows_x86_64_msvc-0.42.1/lib" "/LIBPATH:/$USER/.cargo/registry/src/github.com-1ecc6299db9ec823/windows_x86_64_msvc-0.34.0/lib" "/LIBPATH:/$USER/Projets/XXX/RustHound/target/x86_64-pc-windows-msvc/release/build/ring-175a80523169bc78/out" "/LIBPATH:/$USER/.rustup/toolchains/nightly-2023-02-28-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-pc-windows-msvc/lib" "/tmp/rustcAWOQqQ/libring-98a43d4a731d3bc1.rlib" "/$USER/Projets/XXX/RustHound/target/x86_64-pc-windows-msvc/release/deps/libcompiler_builtins-a57aa224b6747535.rlib" "windows.lib" "windows.lib" "iphlpapi.lib" "bcrypt.lib" "ntdll.lib" "windows.lib" "advapi32.lib" "cfgmgr32.lib" "credui.lib" "fwpuclnt.lib" "gdi32.lib" "kernel32.lib" "msimg32.lib" "ntdll.lib" "ole32.lib" "opengl32.lib" "runtimeobject.lib" "secur32.lib" "user32.lib" "winspool.lib" "ws2_32.lib" "kernel32.lib" "advapi32.lib" "userenv.lib" "kernel32.lib" "ws2_32.lib" "bcrypt.lib" "msvcrt.lib" "legacy_stdio_definitions.lib" "/NXCOMPAT" "/LIBPATH:/$USER/.rustup/toolchains/nightly-2023-02-28-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-pc-windows-msvc/lib" "/OUT:/$USER/Projets/XXX/RustHound/target/x86_64-pc-windows-msvc/release/deps/rusthound.exe" "/OPT:REF,ICF" "/DEBUG"
  = note: lld-link: error: undefined symbol: _$LT$T$u20$as$u20$core..convert..TryInto$LT$U$GT$$GT$::try_into::ha70d088502189c5c
          >>> referenced by libcompiler_builtins-a57aa224b6747535.rlib(compiler_builtins-a57aa224b6747535.compiler_builtins.08706f9d-cgu.3.rcgu.o):(_$LT$u8$u20$as$u20$compiler_builtins..int..Int$GT$::wrapping_shl::h75be24e30ae66717)
          >>> referenced by libcompiler_builtins-a57aa224b6747535.rlib(compiler_builtins-a57aa224b6747535.compiler_builtins.08706f9d-cgu.3.rcgu.o):(_$LT$u8$u20$as$u20$compiler_builtins..int..Int$GT$::logical_shr::h2923ea1dd2188a7b)
          
          lld-link: error: undefined symbol: _$LT$T$u20$as$u20$core..convert..TryInto$LT$U$GT$$GT$::try_into::h3facc516142b808f
          >>> referenced by libcompiler_builtins-a57aa224b6747535.rlib(compiler_builtins-a57aa224b6747535.compiler_builtins.08706f9d-cgu.3.rcgu.o):(_$LT$u16$u20$as$u20$compiler_builtins..int..Int$GT$::wrapping_shl::hc9f2c5447bea3c19)
          >>> referenced by libcompiler_builtins-a57aa224b6747535.rlib(compiler_builtins-a57aa224b6747535.compiler_builtins.08706f9d-cgu.3.rcgu.o):(_$LT$u16$u20$as$u20$compiler_builtins..int..Int$GT$::logical_shr::ha0c8059f27d2ee43)
          
          lld-link: error: undefined symbol: _$LT$T$u20$as$u20$core..convert..TryInto$LT$U$GT$$GT$::try_into::hc3c814c714409716
          >>> referenced by libcompiler_builtins-a57aa224b6747535.rlib(compiler_builtins-a57aa224b6747535.compiler_builtins.08706f9d-cgu.3.rcgu.o):(_$LT$u32$u20$as$u20$compiler_builtins..int..Int$GT$::wrapping_shl::h5da56a5404567510)
          >>> referenced by libcompiler_builtins-a57aa224b6747535.rlib(compiler_builtins-a57aa224b6747535.compiler_builtins.08706f9d-cgu.3.rcgu.o):(_$LT$u32$u20$as$u20$compiler_builtins..int..Int$GT$::logical_shr::he654838393c6dac6)
          >>> referenced by libcompiler_builtins-a57aa224b6747535.rlib(compiler_builtins-a57aa224b6747535.compiler_builtins.08706f9d-cgu.7.rcgu.o):(compiler_builtins::int::specialized_div_rem::u32_div_rem::hb22b2448b8f01ed2)
          

error: could not compile `rusthound` due to previous error
```

</p>
</details>

For RustScan (using `nightly-2023-02-28`):
<details><summary>Compile error</summary>
<p>

```
   Compiling rustscan v2.1.1 (/$USER/Projets/XXX/RustScan)
error: linking with `lld-link` failed: exit status: 1
  |
  = note: LC_ALL="C" PATH="/$USER/.rustup/toolchains/nightly-2023-02-28-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/bin:/$USER/.vscode-server/bin/441438abd1ac652551dbe4d408dfcec8a499b8bf/bin/remote-cli:/$USER/.local/bin:/$USER/.cargo/bin:/$USER/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/tmp" VSLANG="1033" "lld-link" "-flavor" "link" "/NOLOGO" "/tmp/rustcMAAVJR/symbols.o" "/$USER/Projets/XXX/RustScan/target/x86_64-pc-windows-msvc/release/deps/rustscan.rustscan.2fa56812-cgu.0.rcgu.o" "/LIBPATH:/$USER/Projets/XXX/RustScan/target/x86_64-pc-windows-msvc/release/deps" "/LIBPATH:/$USER/Projets/XXX/RustScan/target/release/deps" "/LIBPATH:/tmp/xwin_64/crt/lib/x86_64" "/LIBPATH:/tmp/xwin_64/sdk/lib/um/x86_64" "/LIBPATH:/tmp/xwin_64/sdk/lib/ucrt/x86_64" "/LIBPATH:/$USER/Projets/XXX/RustScan/target/x86_64-pc-windows-msvc/release/build/wepoll-ffi-719df429f6c384f7/out" "/LIBPATH:/$USER/.cargo/registry/src/github.com-1ecc6299db9ec823/windows_x86_64_msvc-0.42.0/lib" "/LIBPATH:/$USER/Projets/XXX/RustScan/target/x86_64-pc-windows-msvc/release/build/ring-a690ee922a6572a9/out" "/LIBPATH:/$USER/.rustup/toolchains/nightly-2023-02-28-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-pc-windows-msvc/lib" "/tmp/rustcMAAVJR/libring-188f86f2fd8f068a.rlib" "/tmp/rustcMAAVJR/libwepoll_ffi-48d31142813b117f.rlib" "/$USER/Projets/XXX/RustScan/target/x86_64-pc-windows-msvc/release/deps/libcompiler_builtins-18ed03317118022b.rlib" "iphlpapi.lib" "bcrypt.lib" "ntdll.lib" "windows.lib" "advapi32.lib" "advapi32.lib" "cfgmgr32.lib" "credui.lib" "fwpuclnt.lib" "gdi32.lib" "kernel32.lib" "msimg32.lib" "ntdll.lib" "ole32.lib" "opengl32.lib" "secur32.lib" "shell32.lib" "synchronization.lib" "user32.lib" "winspool.lib" "ws2_32.lib" "kernel32.lib" "advapi32.lib" "userenv.lib" "kernel32.lib" "ws2_32.lib" "bcrypt.lib" "msvcrt.lib" "legacy_stdio_definitions.lib" "/NXCOMPAT" "/LIBPATH:/$USER/.rustup/toolchains/nightly-2023-02-28-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-pc-windows-msvc/lib" "/OUT:/$USER/Projets/XXX/RustScan/target/x86_64-pc-windows-msvc/release/deps/rustscan.exe" "/OPT:REF,ICF" "/DEBUG"
  = note: lld-link: error: undefined symbol: _$LT$T$u20$as$u20$core..convert..TryInto$LT$U$GT$$GT$::try_into::hf83a56f591ad91c2
          >>> referenced by libcompiler_builtins-18ed03317118022b.rlib(compiler_builtins-18ed03317118022b.compiler_builtins.c902bbf6-cgu.3.rcgu.o):(_$LT$u8$u20$as$u20$compiler_builtins..int..Int$GT$::wrapping_shl::he7ed35977b0d0fac)
          >>> referenced by libcompiler_builtins-18ed03317118022b.rlib(compiler_builtins-18ed03317118022b.compiler_builtins.c902bbf6-cgu.3.rcgu.o):(_$LT$u8$u20$as$u20$compiler_builtins..int..Int$GT$::logical_shr::h00538ae7c426f37f)
          
          lld-link: error: undefined symbol: _$LT$T$u20$as$u20$core..convert..TryInto$LT$U$GT$$GT$::try_into::hae711d779ec4e591
          >>> referenced by libcompiler_builtins-18ed03317118022b.rlib(compiler_builtins-18ed03317118022b.compiler_builtins.c902bbf6-cgu.3.rcgu.o):(_$LT$u16$u20$as$u20$compiler_builtins..int..Int$GT$::wrapping_shl::h659e210b754e206f)
          >>> referenced by libcompiler_builtins-18ed03317118022b.rlib(compiler_builtins-18ed03317118022b.compiler_builtins.c902bbf6-cgu.3.rcgu.o):(_$LT$u16$u20$as$u20$compiler_builtins..int..Int$GT$::logical_shr::h970afb9c096c3a26)
          
          lld-link: error: undefined symbol: _$LT$T$u20$as$u20$core..convert..TryInto$LT$U$GT$$GT$::try_into::h183171ab1b2751dc
          >>> referenced by libcompiler_builtins-18ed03317118022b.rlib(compiler_builtins-18ed03317118022b.compiler_builtins.c902bbf6-cgu.3.rcgu.o):(_$LT$u32$u20$as$u20$compiler_builtins..int..Int$GT$::wrapping_shl::h6c6b22f19a38a7e4)
          >>> referenced by libcompiler_builtins-18ed03317118022b.rlib(compiler_builtins-18ed03317118022b.compiler_builtins.c902bbf6-cgu.3.rcgu.o):(_$LT$u32$u20$as$u20$compiler_builtins..int..Int$GT$::logical_shr::hb512d2478bac3150)
          >>> referenced by libcompiler_builtins-18ed03317118022b.rlib(compiler_builtins-18ed03317118022b.compiler_builtins.c902bbf6-cgu.7.rcgu.o):(compiler_builtins::int::specialized_div_rem::u32_div_rem::h4103159706e15559)
          

error: could not compile `rustscan` due to previous error
```

</p>
</details>

For Helix (using `nightly-2023-02-28`):
<details><summary>Compile error</summary>
<p>

```
   Compiling helix-tui v0.6.0 (/$USER/Projets/XXX/Helix/helix-tui)
error: linking with `lld-link` failed: exit status: 1
  |
  = note: LC_ALL="C" PATH="/$USER/.rustup/toolchains/nightly-2023-02-28-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/bin:/$USER/.vscode-server/bin/441438abd1ac652551dbe4d408dfcec8a499b8bf/bin/remote-cli:/$USER/.local/bin:/$USER/.cargo/bin:/$USER/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/tmp" VSLANG="1033" "lld-link" "-flavor" "link" "/NOLOGO" "/tmp/rustcIC5pT0/symbols.o" "/$USER/Projets/XXX/Helix/target/x86_64-pc-windows-msvc/release/deps/hx.hx.97f34d47-cgu.12.rcgu.o" "/LIBPATH:/$USER/Projets/XXX/Helix/target/x86_64-pc-windows-msvc/release/deps" "/LIBPATH:/$USER/Projets/XXX/Helix/target/release/deps" "/LIBPATH:/tmp/xwin_64/crt/lib/x86_64" "/LIBPATH:/tmp/xwin_64/sdk/lib/um/x86_64" "/LIBPATH:/tmp/xwin_64/sdk/lib/ucrt/x86_64" "/LIBPATH:/$USER/.cargo/registry/src/github.com-1ecc6299db9ec823/windows_x86_64_msvc-0.42.1/lib" "/LIBPATH:/$USER/Projets/XXX/Helix/target/x86_64-pc-windows-msvc/release/build/tree-sitter-2a9907837c51abd5/out" "/LIBPATH:/$USER/.rustup/toolchains/nightly-2023-02-28-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-pc-windows-msvc/lib" "/tmp/rustcIC5pT0/libtree_sitter-846e7dfbf9fccdfd.rlib" "/$USER/Projets/XXX/Helix/target/x86_64-pc-windows-msvc/release/deps/libcompiler_builtins-15b4049fca2c0d34.rlib" "windows.lib" "ntdll.lib" "legacy_stdio_definitions.lib" "windows.lib" "kernel32.lib" "advapi32.lib" "ole32.lib" "oleaut32.lib" "bcrypt.lib" "windows.lib" "advapi32.lib" "cfgmgr32.lib" "fwpuclnt.lib" "gdi32.lib" "kernel32.lib" "msimg32.lib" "ntdll.lib" "ole32.lib" "opengl32.lib" "runtimeobject.lib" "shell32.lib" "shlwapi.lib" "synchronization.lib" "user32.lib" "winspool.lib" "ws2_32.lib" "kernel32.lib" "advapi32.lib" "userenv.lib" "kernel32.lib" "ws2_32.lib" "bcrypt.lib" "msvcrt.lib" "legacy_stdio_definitions.lib" "/NXCOMPAT" "/LIBPATH:/$USER/.rustup/toolchains/nightly-2023-02-28-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-pc-windows-msvc/lib" "/OUT:/$USER/Projets/XXX/Helix/target/x86_64-pc-windows-msvc/release/deps/hx.exe" "/OPT:REF,ICF" "/DEBUG"
  = note: lld-link: error: undefined symbol: _$LT$T$u20$as$u20$core..convert..TryInto$LT$U$GT$$GT$::try_into::hc27fcf92225fa76d
          >>> referenced by libcompiler_builtins-15b4049fca2c0d34.rlib(compiler_builtins-15b4049fca2c0d34.compiler_builtins.b4f7fc22-cgu.3.rcgu.o):(_$LT$u8$u20$as$u20$compiler_builtins..int..Int$GT$::wrapping_shl::hde1da1a440758e53)
          >>> referenced by libcompiler_builtins-15b4049fca2c0d34.rlib(compiler_builtins-15b4049fca2c0d34.compiler_builtins.b4f7fc22-cgu.3.rcgu.o):(_$LT$u8$u20$as$u20$compiler_builtins..int..Int$GT$::logical_shr::h69f3e9a4cec906c3)
          
          lld-link: error: undefined symbol: _$LT$T$u20$as$u20$core..convert..TryInto$LT$U$GT$$GT$::try_into::hc09440a623908dd2
          >>> referenced by libcompiler_builtins-15b4049fca2c0d34.rlib(compiler_builtins-15b4049fca2c0d34.compiler_builtins.b4f7fc22-cgu.3.rcgu.o):(_$LT$u16$u20$as$u20$compiler_builtins..int..Int$GT$::wrapping_shl::h8fa431404ce61bc8)
          >>> referenced by libcompiler_builtins-15b4049fca2c0d34.rlib(compiler_builtins-15b4049fca2c0d34.compiler_builtins.b4f7fc22-cgu.3.rcgu.o):(_$LT$u16$u20$as$u20$compiler_builtins..int..Int$GT$::logical_shr::h66ae3ce6d28d7dc9)
          
          lld-link: error: undefined symbol: _$LT$T$u20$as$u20$core..convert..TryInto$LT$U$GT$$GT$::try_into::hcee917ca27ced0ac
          >>> referenced by libcompiler_builtins-15b4049fca2c0d34.rlib(compiler_builtins-15b4049fca2c0d34.compiler_builtins.b4f7fc22-cgu.3.rcgu.o):(_$LT$u32$u20$as$u20$compiler_builtins..int..Int$GT$::wrapping_shl::h51b6ed721278058c)
          >>> referenced by libcompiler_builtins-15b4049fca2c0d34.rlib(compiler_builtins-15b4049fca2c0d34.compiler_builtins.b4f7fc22-cgu.3.rcgu.o):(_$LT$u32$u20$as$u20$compiler_builtins..int..Int$GT$::logical_shr::h337b670af4036651)
          >>> referenced by libcompiler_builtins-15b4049fca2c0d34.rlib(compiler_builtins-15b4049fca2c0d34.compiler_builtins.b4f7fc22-cgu.7.rcgu.o):(compiler_builtins::int::specialized_div_rem::u32_div_rem::hc40953c0c14b372c)
          

error: could not compile `helix-term` due to previous error
```

</p>
</details>

Please note that I used windows cross compilation builds as an example, ~~but same thing can happen with other targets (even when not cross-compiling)~~. _Also note that the linking errors can be different regarding the selected target._

After some more tests with Linux (and checking [this](https://github.com/rust-lang/rust/issues/107016) issue), I found that we need to add `-C panic=abort` to overpass another linking issue (cf. https://github.com/rust-lang/rust/issues/107016#issuecomment-1401116129). This doesn't resolve the issue for Windows cross-compilation however.

### LINKED ISSUE #108893: Undefined reference in unchecked_shl function when compiling in release mode for thumbv4t-none-eabi
Since the nightly version released on the 28th February, we've been getting a build failure for agb (https://github.com/agbrs/agb) relating to undefined reference to `<T as core::convert::TryInto<U>>::try_into` in `core::num::<impl u32>::unchecked_shl`

### Code

If you build the `text_render` example in the `agb` directory as follows:

```
$ cargo build --example=text_render
```

it works correctly, but if you do so in release mode, you get

```
$ cargo build --example=text_render --release
<lots of output>
  = note: arm-none-eabi-ld: /home/gwilym/Projects/agb/agb/target/thumbv4t-none-eabi/release/deps/libcompiler_builtins-59056e9a57a3f920.rlib(compiler_builtins-59056e9a57a3f920.compiler_builtins.12b6ae5a-cgu.3.rcgu.o): in function `core::num::<impl u32>::unchecked_shl':
          /home/gwilym/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/num/uint_macros.rs:942: undefined reference to `<T as core::convert::TryInto<U>>::try_into'
```

Note that you'll need `arm-none-eabi-binutils` installed since we use the `arm-none-eabi-ld` linker and the assembler.

I tried some smaller examples, but couldn't work out how to trigger this smaller since it seems to be optimisation related? Let me know if I can do further research for this.

### Version it worked on

The nightly version before the 28th February (we know this is the exact build it failed on because we run the build daily (https://github.com/agbrs/agb/actions/workflows/build-and-test.yml)

Installing an older nightly version fixes the issue:

```
rustc --version --verbose
rustc 1.69.0-nightly (d962ea578 2023-02-26)
binary: rustc
commit-hash: d962ea57899d64dc8a57040142c6b498a57c8064
commit-date: 2023-02-26
host: x86_64-unknown-linux-gnu
release: 1.69.0-nightly
LLVM version: 15.0.7
```

### Version with regression

It fails on the most recent nightly, but the first version it doesn't work on is provided below:

`rustc --version --verbose`:
```
rustc 1.69.0-nightly (7281249a1 2023-02-27)
binary: rustc
commit-hash: 7281249a19a9755e9d889ee251ec323629caadab
commit-date: 2023-02-27
host: x86_64-unknown-linux-gnu
release: 1.69.0-nightly
LLVM version: 15.0.7
```

### LINKED ISSUE #110606: undefined reference to 'bar::add' with LTO and no_builtins
I tried this code:

```shell
git clone https://github.com/DianQK/rust-109821-reproducible.git
cd rust-109821-reproducible/stable
cargo build --release
```

I expected to see this happen: *Build Success.*

Instead, this happened: *undefined reference to 'bar::add'.*

### Meta
`rustc --version --verbose`:
```
rustc 1.68.2 (9eb3afe9e 2023-03-27)
binary: rustc
commit-hash: 9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0
commit-date: 2023-03-27
host: x86_64-unknown-linux-gnu
release: 1.68.2
LLVM version: 15.0.6
```

### Error output 

```
  = note: /usr/bin/ld: /home/dianqk/Projects/rust-109821-reproducible/stable/target/release/deps/libfoo-43f9aa8deb6de355.rlib(foo-43f9aa8deb6de355.foo.dc68fc3e-cgu.0.rcgu.o): in function `foo::add':
          foo.dc68fc3e-cgu.0:(.text._ZN3foo3add17h49dc1e6624cb3836E+0x3): undefined reference to `bar::add'
          collect2: error: ld returned 1 exit status
```

<details><summary>Backtrace</summary>
<p>

```
     Running `rustc --crate-name tool --edition=2021 src/main.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --diagnostic-width=212 --crate-type bin --emit=dep-info,link -C opt-level=1 -C lto=fat -C codegen-units=1 -C metadata=eb743437eba5f3e9 -C extra-filename=-eb743437eba5f3e9 --out-dir /home/dianqk/Projects/rust-109821-reproducible/stable/target/release/deps -L dependency=/home/dianqk/Projects/rust-109821-reproducible/stable/target/release/deps --extern foo=/home/dianqk/Projects/rust-109821-reproducible/stable/target/release/deps/libfoo-43f9aa8deb6de355.rlib`
error: linking with `cc` failed: exit status: 1
  |
  = note: LC_ALL="C" PATH="/home/dianqk/.rustup/toolchains/1.68.2-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/bin:/home/dianqk/.cargo/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/opt/android-sdk/platform-tools:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl" VSLANG="1033" "cc" "-m64" "/tmp/rustckARHcS/symbols.o" "/home/dianqk/Projects/rust-109821-reproducible/stable/target/release/deps/tool-eb743437eba5f3e9.tool.5d7473d5-cgu.0.rcgu.o" "-Wl,--as-needed" "-L" "/home/dianqk/Projects/rust-109821-reproducible/stable/target/release/deps" "-L" "/home/dianqk/.rustup/toolchains/1.68.2-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-Wl,-Bstatic" "/home/dianqk/Projects/rust-109821-reproducible/stable/target/release/deps/libfoo-43f9aa8deb6de355.rlib" "/home/dianqk/.rustup/toolchains/1.68.2-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcompiler_builtins-10f041ff25bad5f3.rlib" "-Wl,-Bdynamic" "-lgcc_s" "-lutil" "-lrt" "-lpthread" "-lm" "-ldl" "-lc" "-Wl,--eh-frame-hdr" "-Wl,-znoexecstack" "-L" "/home/dianqk/.rustup/toolchains/1.68.2-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-o" "/home/dianqk/Projects/rust-109821-reproducible/stable/target/release/deps/tool-eb743437eba5f3e9" "-Wl,--gc-sections" "-pie" "-Wl,-zrelro,-znow" "-nodefaultlibs"
  = note: /usr/bin/ld: /home/dianqk/Projects/rust-109821-reproducible/stable/target/release/deps/libfoo-43f9aa8deb6de355.rlib(foo-43f9aa8deb6de355.foo.dc68fc3e-cgu.0.rcgu.o): in function `foo::add':
          foo.dc68fc3e-cgu.0:(.text._ZN3foo3add17h49dc1e6624cb3836E+0x3): undefined reference to `bar::add'
          collect2: error: ld returned 1 exit status
          
  = note: some `extern` functions couldn't be found; some native libraries may need to be installed or have their path specified
  = note: use the `-l` flag to specify native libraries to link
  = note: use the `cargo:rustc-link-lib` directive to specify the native libraries to link with Cargo (see https://doc.rust-lang.org/cargo/reference/build-scripts.html#cargorustc-link-libkindname)

error: could not compile `tool` due to previous error

Caused by:
  process didn't exit successfully: `rustc --crate-name tool --edition=2021 src/main.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --diagnostic-width=212 --crate-type bin --emit=dep-info,link -C opt-level=1 -C lto=fat -C codegen-units=1 -C metadata=eb743437eba5f3e9 -C extra-filename=-eb743437eba5f3e9 --out-dir /home/dianqk/Projects/rust-109821-reproducible/stable/target/release/deps -L dependency=/home/dianqk/Projects/rust-109821-reproducible/stable/target/release/deps --extern foo=/home/dianqk/Projects/rust-109821-reproducible/stable/target/release/deps/libfoo-43f9aa8deb6de355.rlib` (exit status: 1)
```

</p>
</details>

I filed this because it is different from #108853. And can be reproduced in a stable version.

### LINKED ISSUE #112245: Nightly: Enabling LTO causes undefined symbols when using build-std
This bug occurs when I tried to build the example [uefi app](https://rust-osdev.github.io/uefi-rs/HEAD/tutorial/app.html) in a workspace of mine that enables LTO. I was able to replicate it using a standalone project:

Cargo.toml:
```toml
[package]
name = "bootloader-uefi"
version = "0.1.0"
edition = "2021"

[profile.dev]
lto = true

[dependencies]
log = "0.4"
uefi = "0.22"
uefi-services = "0.19"
```

main.rs:
```rust
#![no_std]
#![no_main]

use log::info;
use uefi::prelude::*;

#[entry]
fn main(_image_handle: Handle, mut system_table: SystemTable<Boot>) -> Status {
    uefi_services::init(&mut system_table).unwrap();
    info!("Hello, firmware!");
    system_table.boot_services().stall(10_000_000);
    Status::SUCCESS
}
```

I expected the crate to compile successfully, as it does when LTO is turned off.

Instead, the crate fails to link correctly, with many undefined symbols not only from compiler_builtins but also some from core.

I am forced to use build-std, so it could definitely be related to [this issue](https://github.com/rust-lang/rust/issues/96486), but it is slightly different in that even disabling share-generics doesn't help.

The full command that I am running to attempt the build is:

```
RUST_BACKTRACE=1 RUSTFLAGS="-Zshare-generics=n" cargo build -Zbuild-std=core,compiler_builtins -Zbuild-std-features=compiler-builtins-mem --target x86_64-unknown-uefi
```

### Meta

`rustc --version --verbose`:
```
rustc 1.72.0-nightly (dd5d7c729 2023-06-02)
binary: rustc
commit-hash: dd5d7c729d4e8a59708df64002e09dbcbc4005ba
commit-date: 2023-06-02
host: x86_64-unknown-linux-gnu
release: 1.72.0-nightly
LLVM version: 16.0.4
```

<details><summary>Compiler output</summary>
<p>

```
   Compiling bootloader-uefi v0.1.0 (/home/luke/Documents/bootloader-uefi)
error: linking with rust-lld failed: exit status: 1
  = note: rust-lld: error: undefined symbol: core::panicking::panic::hb163aad4ddc55c9f
          >>> referenced by /home/luke/.cargo/registry/src/index.crates.io-6f17d22bba15001f/compiler_builtins-0.1.92/src/../libm/src/math/exp.rs:129
          >>>               libcompiler_builtins-0152c520d1c8b186.rlib(compiler_builtins-0152c520d1c8b186.compiler_builtins.75569f00fa09706c-cgu.10.rcgu.o):(compiler_builtins::math::libm::exp::exp::h02a4bfd20070f07c)
          >>> referenced by /home/luke/.cargo/registry/src/index.crates.io-6f17d22bba15001f/compiler_builtins-0.1.92/src/../libm/src/math/exp.rs:129
          >>>               libcompiler_builtins-0152c520d1c8b186.rlib(compiler_builtins-0152c520d1c8b186.compiler_builtins.75569f00fa09706c-cgu.10.rcgu.o):(compiler_builtins::math::libm::exp::exp::h02a4bfd20070f07c)
          >>> referenced by /home/luke/.cargo/registry/src/index.crates.io-6f17d22bba15001f/compiler_builtins-0.1.92/src/../libm/src/math/fmaf.rs:102
          >>>               libcompiler_builtins-0152c520d1c8b186.rlib(compiler_builtins-0152c520d1c8b186.compiler_builtins.75569f00fa09706c-cgu.10.rcgu.o):(compiler_builtins::math::libm::fmaf::fmaf::h64c4fdc39a6a9200)
          >>> referenced 581 more times

          rust-lld: error: undefined symbol: core::panicking::panic_fmt::hda82d1e6e39651a7
          >>> referenced by /home/luke/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/fmt/mod.rs:299
          >>>               libcompiler_builtins-0152c520d1c8b186.rlib(compiler_builtins-0152c520d1c8b186.compiler_builtins.75569f00fa09706c-cgu.2.rcgu.o):(core::fmt::Arguments::new_const::hb12de13e127e57a4)
          >>> referenced by /home/luke/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ptr/const_ptr.rs:1567
          >>>               libcompiler_builtins-0152c520d1c8b186.rlib(compiler_builtins-0152c520d1c8b186.compiler_builtins.75569f00fa09706c-cgu.0.rcgu.o):(core::ptr::const_ptr::_$LT$impl$u20$$BP$const$u20$T$GT$::is_aligned_to::h14d9509bf7aaf5c9)
          >>> referenced by /home/luke/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ptr/const_ptr.rs:1567
          >>>               libcompiler_builtins-0152c520d1c8b186.rlib(compiler_builtins-0152c520d1c8b186.compiler_builtins.75569f00fa09706c-cgu.0.rcgu.o):(core::ptr::const_ptr::_$LT$impl$u20$$BP$const$u20$T$GT$::is_aligned_to::h22908f059c723326)
          >>> referenced 2 more times

          rust-lld: error: undefined symbol: core::panicking::panic_nounwind::h0f909d7fd0d3bd3e
          >>> referenced by /home/luke/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ptr/mod.rs:1539
          >>>               libcompiler_builtins-0152c520d1c8b186.rlib(compiler_builtins-0152c520d1c8b186.compiler_builtins.75569f00fa09706c-cgu.7.rcgu.o):(core::ptr::read_volatile::h2a19696369700077)
          >>> referenced by /home/luke/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ptr/mod.rs:1539
          >>>               libcompiler_builtins-0152c520d1c8b186.rlib(compiler_builtins-0152c520d1c8b186.compiler_builtins.75569f00fa09706c-cgu.7.rcgu.o):(core::ptr::read_volatile::hd1a8b1667212015d)
          >>> referenced by /home/luke/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ptr/mod.rs:1175
          >>>               libcompiler_builtins-0152c520d1c8b186.rlib(compiler_builtins-0152c520d1c8b186.compiler_builtins.75569f00fa09706c-cgu.7.rcgu.o):(core::ptr::read::h70c3ace9010db4c7)
          >>> referenced 12 more times

          rust-lld: error: undefined symbol: core::option::expect_failed::hc5188971195ae32b
          >>> referenced by /home/luke/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/option.rs:898
          >>>               libcompiler_builtins-0152c520d1c8b186.rlib(compiler_builtins-0152c520d1c8b186.compiler_builtins.75569f00fa09706c-cgu.12.rcgu.o):(core::option::Option$LT$T$GT$::expect::h63b03588bfa56574)

          rust-lld: error: undefined symbol: core::slice::index::slice_index_order_fail::h89839b514f12b875
          >>> referenced by /home/luke/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/slice/index.rs:406
          >>>               libcompiler_builtins-0152c520d1c8b186.rlib(compiler_builtins-0152c520d1c8b186.compiler_builtins.75569f00fa09706c-cgu.8.rcgu.o):(_$LT$core..ops..range..Range$LT$usize$GT$$u20$as$u20$core..slice..index..SliceIndex$LT$$u5b$T$u5d$$GT$$GT$::index::h088287bcb6971bb6)

          rust-lld: error: undefined symbol: core::slice::index::slice_end_index_len_fail::hc3c969f2bc3a976b
          >>> referenced by /home/luke/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/slice/index.rs:408
          >>>               libcompiler_builtins-0152c520d1c8b186.rlib(compiler_builtins-0152c520d1c8b186.compiler_builtins.75569f00fa09706c-cgu.8.rcgu.o):(_$LT$core..ops..range..Range$LT$usize$GT$$u20$as$u20$core..slice..index..SliceIndex$LT$$u5b$T$u5d$$GT$$GT$::index::h088287bcb6971bb6)

          rust-lld: error: undefined symbol: core::slice::index::slice_end_index_overflow_fail::h7c1f489fb05731b4
          >>> referenced by /home/luke/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/slice/index.rs:576
          >>>               libcompiler_builtins-0152c520d1c8b186.rlib(compiler_builtins-0152c520d1c8b186.compiler_builtins.75569f00fa09706c-cgu.8.rcgu.o):(_$LT$core..ops..range..RangeInclusive$LT$usize$GT$$u20$as$u20$core..slice..index..SliceIndex$LT$$u5b$T$u5d$$GT$$GT$::index::h981b17dba1d622a5)

error: could not compile `bootloader-uefi` (bin "bootloader-uefi") due to previous error
```

</p>
</details>

### PR DESCRIPTION
**Pull request by dianqk**
After #113716, we can make `#![no_builtins]` crates participate in LTO again.

`#![no_builtins]` with LTO does not result in undefined references to the error. I believe this type of issue won't happen again. 

Fixes #72140.  Fixes #112245. Fixes #110606.  Fixes #105734. Fixes #96486. Fixes #108853. Fixes #108893. Fixes #78744. Fixes #91158. Fixes https://github.com/rust-lang/cargo/issues/10118. Fixes https://github.com/rust-lang/compiler-builtins/issues/347.

 The `nightly-2023-07-20` version does not always reproduce problems due to changes in compiler-builtins, core, and user code. That's why this issue recurs and disappears.
Some issues were not tested due to the difficulty of reproducing them.

r? pnkfelix

cc @bjorn3 @japaric @alexcrichton @Amanieu

### CODE REVIEW

File: compiler/rustc_codegen_ssa/src/base.rs [hunk 1]
```diff
@@ -898,55 +894,6 @@ impl CrateInfo {
...
         }
 
-        // Handle circular dependencies in the standard library.
-        // See comment before `add_linked_symbol_object` function for the details.
-        // If global LTO is enabled then almost everything (*) is glued into a single object file,
-        // so this logic is not necessary and can cause issues on some targets (due to weak lang
-        // item symbols being "privatized" to that object file), so we disable it.
-        // (*) Native libs, and `#[compiler_builtins]` and `#[no_builtins]` crates are not glued,
-        // and we assume that they cannot define weak lang items. This is not currently enforced
-        // by the compiler, but that's ok because all this stuff is unstable anyway.
```
Comment (petrochenkov) [inline compiler/rustc_codegen_ssa/src/base.rs:908]: This logic is mostly unrelated to `no_builtins`, it should not be removed.
The only thing that should need an update here is this comment.

"Native libs are not glued, and we assume that they cannot define weak lang items."

Comment (DianQK) [reply compiler/rustc_codegen_ssa/src/base.rs:908]: Thanks, I've updated it.

**Comment by DianQK** [comment]
Removed opaque pointers for LLVM 14.

File: compiler/rustc_codegen_ssa/src/base.rs [hunk 2]
```diff
@@ -903,9 +903,8 @@ impl CrateInfo {
         // If global LTO is enabled then almost everything (*) is glued into a single object file,
         // so this logic is not necessary and can cause issues on some targets (due to weak lang
         // item symbols being "privatized" to that object file), so we disable it.
-        // (*) Native libs, and `#[compiler_builtins]` and `#[no_builtins]` crates are not glued,
-        // and we assume that they cannot define weak lang items. This is not currently enforced
-        // by the compiler, but that's ok because all this stuff is unstable anyway.
+        // (*) Native libs are not glued, and we assume that they cannot define weak lang items.
+        // This is not currently enforced by the compiler, but that's ok because all this stuff is unstable anyway.
```
Comment (petrochenkov) [inline compiler/rustc_codegen_ssa/src/base.rs:907]: (This sentence was also about compiler_builtins/no_builtins and can be removed.)

**Comment by DianQK** [comment]
ping? @pnkfelix

**Comment by DianQK** [comment]
Rebase and remove the DisableSimplifyLibCalls parameter.

**Comment by DianQK** [comment]
Based on the error message, I believe #78744, #91158 amd https://github.com/rust-lang/cargo/issues/10118 are also not participating in the LTO issue.
But let me fix the no_builtins issue with wasm first.

It show
```
  (import "env" "__muloti4" (func $__muloti4 (type 0)))
```

**Comment by DianQK** [comment]
TL;DR
Using built-in functions like `__multi3` does not generate calls during IR optimization.
This call is not generated until the LLVM code generation phase. 
https://llvm.godbolt.org/z/aoMK4KTWT is an example.

I renamed `wasm-spurious-import` to `wasm-builtins-import`. Because we have found the essence of the problem, and it is the same issue that this PR is trying to solve. (That's why it magically disappeared.)
Now we use this test to check that the built-in functions are not missing.

---

An interesting attempt: I can get correct results using LLVM's LTO in lld.
I just need to change the `main.main.7fc14dcaa7e3fa65-cgu.0.rcgu.o` to `main.main.7fc14dcaa7e3fa65-cgu.0.rcgu.lto.input.bc`.

```sh
"lld" "-flavor" "wasm" "--rsp-quoting=posix" \
"--export" "multer" "--export=__heap_base" "--export=__data_end" \
"-z" "stack-size=1048576" "--stack-first" "--allow-undefined" "--fatal-warnings" "--no-demangle" "--no-entry" \
"main.main.7fc14dcaa7e3fa65-cgu.0.rcgu.lto.input.bc" \
"-o" "main.wasm" "--gc-sections" "--no-entry" "-O3"
```

I investigated along with this result why lld's LTO could be successful.
Then I found https://github.com/llvm/llvm-project/commit/e06bac4796bffed2b80649497afaadfb67d767cf.

---

Two issues in LLVM (or maybe not).
The first is `InternalizePass` should consider built-in functions.
The second is the `no-builtins` should work with `__multi3`. https://llvm.godbolt.org/z/9vcj8dqaY
I will ping the LLVM working group after further digging.

File: compiler/rustc_codegen_llvm/src/back/lto.rs [hunk 3]
```diff
@@ -39,6 +39,24 @@ pub fn crate_type_allows_lto(crate_type: CrateType) -> bool {
     }
 }
 
+fn get_llvm_reserved_symbols() -> Vec<String> {
```
Comment (pnkfelix) [inline compiler/rustc_codegen_llvm/src/back/lto.rs:42]: This should be named `get_llvm_preserved_symbols`, not `get_llvm_reserved_symbols`, right?

File: compiler/rustc_codegen_llvm/src/back/lto.rs [hunk 4]
```diff
@@ -53,8 +71,13 @@ fn prepare_lto(
         Lto::No => panic!("didn't request LTO but we're doing LTO"),
     };
 
+    let llvm_reserved_symbols = get_llvm_reserved_symbols();
```
Comment (pnkfelix) [inline compiler/rustc_codegen_llvm/src/back/lto.rs:74]: again, I think this variable should be named `llvm_preserved_symbols`, not `llvm_reserved_symbols`, if I understand this correctly...

File: compiler/rustc_llvm/llvm-wrapper/PassWrapper.cpp [hunk 5]
```diff
@@ -1043,6 +1043,20 @@ extern "C" void LLVMRustPrintPasses() {
   PB.printPassNames(outs());
 }
 
+// from https://github.com/llvm/llvm-project/blob/7021182d6b43de9488ab70de626192ce70b3a4a6/llvm/lib/Object/IRSymtab.cpp#L48-L57
+static const char *PreservedSymbols[] = {
```
Comment (pnkfelix) [inline compiler/rustc_llvm/llvm-wrapper/PassWrapper.cpp:1047]: Duplicating this piece of state from IRSymtab.cpp makes me nervous. How is anyone going to know that they need to watch that file and update this array if changes are made over there?

Is there no better way to architect this to avoid that duplication?

Its possible that we have no other option here; I skimmed IRSymtab.cpp and didn't see any immediate way to access that hidden state. We could contribute a patch upstream to allow such observation, or even rearchitect their work to move the two strings to a separate .def file analogous to RuntimeLibcalls.def...

but I figured I wanted to ask the question first.

Comment (DianQK) [reply compiler/rustc_llvm/llvm-wrapper/PassWrapper.cpp:1047]: First, there will be no more updates in LLVM 17 and lower.

If `InternalizePass` should consider built-in functions, we can remove this code in LLVM 18.
If rustc still needs to pass it, I'll add `PreservedSymbols` to the header file for rustc to use.

File: compiler/rustc_codegen_llvm/src/back/lto.rs (hunk 3 above)
Comment (DianQK) [reply compiler/rustc_codegen_llvm/src/back/lto.rs]: It was my mistake, thanks.

File: tests/run-make/wasm-builtins-import/main.rs [hunk 6]
```diff
@@ -9,6 +9,6 @@ fn my_panic(_info: &core::panic::PanicInfo) -> ! {
 #[no_mangle]
 pub fn multer(a: i128, b: i128) -> i128 {
     // Trigger usage of the __multi3 compiler intrinsic which then leads to an imported
-    // panic function in case of a bug. We verify that no imports exist in our verifier.
+    // __multi3 function in case of a bug. We verify that no imports exist in our verifier.
```
Comment (pnkfelix) [inline tests/run-make/wasm-builtins-import/main.rs:12]: nit: This comment, at the time it was written, *was* talking about an imported panic function. (See https://github.com/rust-lang/rust/issues/78744 .)

**Comment by DianQK** [comment]
Change `&[*const i8]` to `&[*const _]`.

**Comment by pnkfelix** [comment]
(I just realized that the PR author was attempting a try first. Lets do that first too.)

**Comment by DianQK** [comment]
> (I just realized that the PR author was attempting a try first. Lets do that first too.)

I just misunderstood that `try` performs tests for all platforms. So I asked for a try at https://rust-lang.zulipchat.com/#narrow/stream/182449-t-compiler.2Fhelp/topic/.E2.9C.94.20Requesting.20execution.20.60.40bors.20try.60.

I hope to reduce your r+ on this pr. So I aim to run a test to see if there are still errors under the new platform. 
If there are no errors, I believe ready r+.

**Comment by DianQK** [comment]
Resolve conflicts.

@rustbot ready

**Comment by DianQK** [comment]
Pinging. @pnkfelix 
Looks like we're blocking other PRs. :)

**Comment by pnkfelix** [comment]
Sorry for the delay @DianQK

**Comment by DianQK** [comment]
A very strange failure?

@bors retry

**Comment by DianQK** [comment]
> Sorry for the delay @DianQK

It's okay. :p
But this failure looks like a bors problem?
Is it possible to call `delegate+` and when merge is done you come back to the PR? If there are any problems, we can always revert it.

**Comment by pnkfelix** [comment]
@DianQK 

The failures look legit to me; its just that bors and/or github's CI is not presenting them well.

I had to go to the link for [auto - dist-i586-gnu-i586-i686-musl](https://github.com/rust-lang-ci/rust/actions/runs/6497359920/job/17646303104#logs) and then go from there to  the raw log to actually see output that I could make sense of the failures:

See [here](https://pipelinesghubeus1.actions.githubusercontent.com/DhU3eyB11Ei4viT99vzh0CpKzg7REqx1Nup2tB9LzmxBcoHdbh/_apis/pipelines/1/runs/36917/signedlogcontent/28?urlExpires=2023-10-13T14%3A28%3A52.6470074Z&urlSigningMethod=HMACV1&urlSignature=PkXz%2BihVW1nDUOnEfGhLlDp%2BlecNzJ4BH47uJyuGUkQ%3D):

there are a bunch of failures:

```
2023-10-12T15:22:52.0882907Z failures:
2023-10-12T15:22:52.0883196Z     [ui] tests/ui/async-await/deep-futures-are-freeze.rs
2023-10-12T15:22:52.0883579Z     [ui] tests/ui/extern/issue-64655-extern-rust-must-allow-unwind.rs#thin0
2023-10-12T15:22:52.0883984Z     [ui] tests/ui/extern/issue-64655-extern-rust-must-allow-unwind.rs#fat1
2023-10-12T15:22:52.0884387Z     [ui] tests/ui/extern/issue-64655-extern-rust-must-allow-unwind.rs#fat0
2023-10-12T15:22:52.0884766Z     [ui] tests/ui/extern/issue-64655-extern-rust-must-allow-unwind.rs#fat2
2023-10-12T15:22:52.0885197Z     [ui] tests/ui/extern/issue-64655-allow-unwind-when-calling-panic-directly.rs#thin
2023-10-12T15:22:52.0885709Z     [ui] tests/ui/extern/issue-64655-allow-unwind-when-calling-panic-directly.rs#fat
2023-10-12T15:22:52.0886139Z     [ui] tests/ui/extern/issue-64655-extern-rust-must-allow-unwind.rs#thin1
2023-10-12T15:22:52.0886542Z     [ui] tests/ui/extern/issue-64655-extern-rust-must-allow-unwind.rs#fat3
2023-10-12T15:22:52.0886921Z     [ui] tests/ui/extern/issue-64655-extern-rust-must-allow-unwind.rs#thin2
2023-10-12T15:22:52.0887315Z     [ui] tests/ui/extern/issue-64655-extern-rust-must-allow-unwind.rs#thin3
2023-10-12T15:22:52.0887633Z     [ui] tests/ui/lto/debuginfo-lto.rs
2023-10-12T15:22:52.0887902Z     [ui] tests/ui/lto/all-crates.rs
2023-10-12T15:22:52.0888209Z     [ui] tests/ui/lto/lto-rustc-loads-linker-plugin.rs
2023-10-12T15:22:52.0888499Z     [ui] tests/ui/lto/fat-lto.rs
2023-10-12T15:22:52.0888782Z     [ui] tests/ui/lto/lto-many-codegen-units.rs
2023-10-12T15:22:52.0889125Z     [ui] tests/ui/lto/lto-thin-rustc-loads-linker-plugin.rs
2023-10-12T15:22:52.0889483Z     [ui] tests/ui/lto/lto-still-runs-thread-dtors.rs#thir
2023-10-12T15:22:52.0889825Z     [ui] tests/ui/lto/lto-still-runs-thread-dtors.rs#mir
2023-10-12T15:22:52.0890135Z     [ui] tests/ui/lto/thin-lto-inlines2.rs
2023-10-12T15:22:52.0890433Z     [ui] tests/ui/panic-runtime/lto-abort.rs
2023-10-12T15:22:52.0890731Z     [ui] tests/ui/panic-runtime/lto-unwind.rs
2023-10-12T15:22:52.0891027Z     [ui] tests/ui/sepcomp/sepcomp-lib-lto.rs
```

and here's a sample of one of them:

```
2023-10-12T15:22:51.9964533Z ---- [ui] tests/ui/async-await/deep-futures-are-freeze.rs stdout ----
2023-10-12T15:22:51.9965011Z 
2023-10-12T15:22:51.9985070Z error: test compilation failed although it shouldn't!
2023-10-12T15:22:51.9985592Z status: exit status: 1
2023-10-12T15:22:51.9987843Z command: RUSTC_ICE="0" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc" "/checkout/tests/ui/async-await/deep-futures-are-freeze.rs" "-Zthreads=1" "-Zsimulate-remapped-rust-src-base=/rustc/FAKE_PREFIX" "-Ztranslate-remapped-path-to-local-path=no" "-Z" "ignore-directory-in-diagnostics-source-blocks=/cargo" "--sysroot" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2" "--target=i686-unknown-linux-musl" "--error-format" "json" "--json" "future-incompat" "-Ccodegen-units=1" "-Zui-testing" "-Zdeduplicate-diagnostics=no" "-Zwrite-long-types-to-disk=no" "-Cstrip=debuginfo" "--out-dir" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/async-await/deep-futures-are-freeze" "-A" "unused" "-A" "internal_features" "-Crpath" "-Cdebuginfo=0" "-Lnative=/checkout/obj/build/i686-unknown-linux-musl/native/rust-test-helpers" "-Clinker=/musl-i686/bin/musl-gcc" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/async-await/deep-futures-are-freeze/auxiliary" "-Copt-level=s" "-Clto=fat" "--edition=2021"
2023-10-12T15:22:51.9989221Z stdout: none
2023-10-12T15:22:51.9989577Z --- stderr -------------------------------
2023-10-12T15:22:51.9989967Z error: linking with `/musl-i686/bin/musl-gcc` failed: exit status: 1
2023-10-12T15:22:51.9990211Z    |
2023-10-12T15:22:51.9993521Z    = note: LC_ALL="C" PATH="/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/lib/rustlib/x86_64-unknown-linux-gnu/bin:/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/lib/rustlib/x86_64-unknown-linux-gnu/bin/self-contained:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/x-tools/i586-unknown-linux-gnu/bin" VSLANG="1033" "/musl-i686/bin/musl-gcc" "-m32" "-Wl,-melf_i386" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/lib/rustlib/i686-unknown-linux-musl/lib/self-contained/crt1.o" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/lib/rustlib/i686-unknown-linux-musl/lib/self-contained/crti.o" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/lib/rustlib/i686-unknown-linux-musl/lib/self-contained/crtbegin.o" "/tmp/rustcOI1eyb/symbols.o" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/async-await/deep-futures-are-freeze/deep-futures-are-freeze.deep_futures_are_freeze.e53591368acd06c7-cgu.0.rcgu.o" "-Wl,--as-needed" "-L" "/checkout/obj/build/i686-unknown-linux-musl/native/rust-test-helpers" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/async-await/deep-futures-are-freeze/auxiliary" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/lib/rustlib/i686-unknown-linux-musl/lib" "-Wl,-Bstatic" "-lunwind" "-lc" "/tmp/rustcOI1eyb/libcompiler_builtins-de4f3a80d6a657a8.rlib" "-Wl,-Bdynamic" "-Wl,--eh-frame-hdr" "-Wl,-z,noexecstack" "-nostartfiles" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/lib/rustlib/i686-unknown-linux-musl/lib" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/lib/rustlib/i686-unknown-linux-musl/lib/self-contained" "-o" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/async-await/deep-futures-are-freeze/deep-futures-are-freeze" "-Wl,--gc-sections" "-static" "-no-pie" "-Wl,-z,relro,-z,now" "-Wl,--strip-debug" "-nodefaultlibs" "-Wl,--enable-new-dtags" "-Wl,-z,origin" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/lib/rustlib/i686-unknown-linux-musl/lib/self-contained/crtend.o" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/lib/rustlib/i686-unknown-linux-musl/lib/self-contained/crtn.o"
2023-10-12T15:22:51.9995976Z    = note: /usr/bin/ld: /checkout/obj/build/x86_64-unknown-linux-gnu/stage2/lib/rustlib/i686-unknown-linux-musl/lib/self-contained/libc.a(vfprintf.lo): in function `fmt_u':
2023-10-12T15:22:51.9996468Z            /build/musl-1.2.3/src/stdio/vfprintf.c:168: undefined reference to `__udivmoddi4'
2023-10-12T15:22:51.9997046Z            /usr/bin/ld: /checkout/obj/build/x86_64-unknown-linux-gnu/stage2/lib/rustlib/i686-unknown-linux-musl/lib/self-contained/libc.a(vfprintf.lo): in function `fmt_fp':
2023-10-12T15:22:51.9997529Z            /build/musl-1.2.3/src/stdio/vfprintf.c:282: undefined reference to `__udivmoddi4'
2023-10-12T15:22:51.9997834Z            collect2: error: ld returned 1 exit status
2023-10-12T15:22:51.9998069Z            
2023-10-12T15:22:51.9998487Z    = note: some `extern` functions couldn't be found; some native libraries may need to be installed or have their path specified
2023-10-12T15:22:51.9998966Z    = note: use the `-l` flag to specify native libraries to link
2023-10-12T15:22:51.9999572Z    = note: use the `cargo:rustc-link-lib` directive to specify the native libraries to link with Cargo (see https://doc.rust-lang.org/cargo/reference/build-scripts.html#cargorustc-link-libkindname)
```

**Comment by DianQK** [comment]
> The failures look legit to me; its just that bors and/or github's CI is not presenting them well.

Thank you very much. The failures make sense.
I noticed that RuntimeLibcalls.def does not have these symbols. I need some time to add the missing builtins function.
I'd start by trying something that auto-fills these symbols.

**Comment by DianQK** [comment]
It doesn't look like there is currently a tool that can automate this. But I can do it by updating the upstream LLVM.
Candidate PR: https://github.com/llvm/llvm-project/pull/69216.

I added the missing symbols. This list can always be updated if we find new missing built-in symbols.

@rustbot ready

File: tests/run-make/wasm-builtins-import/main.rs [hunk 7]
```diff
@@ -8,7 +8,7 @@ fn my_panic(_info: &core::panic::PanicInfo) -> ! {
 
 #[no_mangle]
 pub fn multer(a: i128, b: i128) -> i128 {
-    // Trigger usage of the __multi3 compiler intrinsic which then leads to an imported
-    // panic function in case of a bug. We verify that no imports exist in our verifier.
+    // Trigger usage of the __multi3 compiler intrinsic which then leads to an imported function
+    // such as panic or __multi3 in case of a bug. We verify that no imports exist in our verifier.
```
Comment (pnkfelix) [inline tests/run-make/wasm-builtins-import/main.rs:12]:
```suggestion
    // such as panic or __multi3 (externally defined) in case of a bug. We verify that no imports exist in our verifier.
```

File: tests/run-make/wasm-builtins-import/main.rs [hunk 8]
```diff
@@ -8,7 +8,7 @@ fn my_panic(_info: &core::panic::PanicInfo) -> ! {
 
 #[no_mangle]
 pub fn multer(a: i128, b: i128) -> i128 {
-    // Trigger usage of the __multi3 compiler intrinsic which then leads to an imported
-    // panic function in case of a bug. We verify that no imports exist in our verifier.
+    // Trigger usage of the __multi3 compiler intrinsic which then leads to an imported function
+    // such as panic or __multi3 (externally defined) in case of a bug. We verify that no imports exist in our verifier.
```
Comment (pnkfelix) [inline tests/run-make/wasm-builtins-import/main.rs:12]:
```suggestion
    // such as panic or __multi3 (externally defined) in case of a bug. We verify that
    // no imports exist in our verifier.
```

**Comment by DianQK** [comment]
The following test I verified locally passed:

- dist-i586-gnu-i586-i686-musl
- dist-i686-linux
- arm-android

File: compiler/rustc_codegen_ssa/src/back/link.rs [hunk 9]
```diff
@@ -2778,8 +2753,6 @@ fn add_static_crate<'a>(
         let canonical_name = name.replace('-', "_");
         let upstream_rust_objects_already_included =
             are_upstream_rust_objects_already_included(sess);
-        let is_builtins =
-            sess.target.no_builtins || !codegen_results.crate_info.is_no_builtins.contains(&cnum);
```
Comment (bjorn3) [inline compiler/rustc_codegen_ssa/src/back/link.rs:2782]: Can the `is_no_builtins` field be removed from `CrateInfo` now?

File: compiler/rustc_codegen_ssa/src/back/symbol_export.rs [hunk 10]
```diff
@@ -107,7 +107,11 @@ fn reachable_non_generics_provider(tcx: TyCtxt<'_>, _: LocalCrate) -> DefIdMap<S
         .map(|def_id| {
             // We won't link right if this symbol is stripped during LTO.
             let name = tcx.symbol_name(Instance::mono(tcx, def_id.to_def_id())).name;
-            let used = name == "rust_eh_personality";
+            // We have to preserve the symbols of the built-in functions during LTO.
+            let is_builtin_fn = is_compiler_builtins
+                && symbol_export_level(tcx, def_id.to_def_id())
+                    .is_below_threshold(SymbolExportLevel::Rust);
```
Comment (bjorn3) [inline compiler/rustc_codegen_ssa/src/back/symbol_export.rs:113]: I think you mean `SymbolExportLevel::C`. The current code will make all functions in compiler-builtins `#[used]` rather than just the `#[no_mangle]` functions.

Comment (DianQK) [reply compiler/rustc_codegen_ssa/src/back/symbol_export.rs]: Thanks! Yes!

File: compiler/rustc_codegen_ssa/src/back/link.rs (hunk 9 above)
Comment (DianQK) [reply compiler/rustc_codegen_ssa/src/back/link.rs:2782]: `compiler_builtins` seems to be used at https://github.com/rust-lang/rust/blob/b2d2184edea578109a48ec3d8decbee5948e8f35/compiler/rustc_codegen_ssa/src/back/link.rs#L2614.

Comment (bjorn3) [reply compiler/rustc_codegen_ssa/src/back/link.rs:2782]: I see. Fine to leave `compiler_builtins` in that case.

File: compiler/rustc_llvm/llvm-wrapper/PassWrapper.cpp (hunk 5 above)
Comment (pnkfelix) [reply compiler/rustc_llvm/llvm-wrapper/PassWrapper.cpp]: (For future reference: #114209 *might* end up being of interest for accomplishing the desired outcome here, of keeping two otherwise disconnected lists in sync with each other in our code base.)

**Comment by pnkfelix** [comment]
New solution looks plausible to me.

@bors r+ rollup=never p=3

(assigning higher than normal priority because this is blocking stabilization of c_unwind (https://github.com/rust-lang/rust/pull/116088))

**Comment by DianQK** [comment]
> A job failed! Check out the build log: [(web)](https://github.com/rust-lang-ci/rust/actions/runs/6659263954/job/18097976667) [(plain)](https://github.com/rust-lang-ci/rust/commit/ea74e09745befb3bce917a78e114e49892fe0d2d/checks/18097976667/logs)

😢

**Comment by DianQK** [comment]
> A job failed! Check out the build log: [(web)](https://github.com/rust-lang-ci/rust/actions/runs/6662029500/job/18105755332) [(plain)](https://github.com/rust-lang-ci/rust/commit/c6441c1fd290a522fe84c5d5017a8b48baedf6b4/checks/18105755332/logs)

Same error. Is this another coincidence? @saethlin

**Comment by DianQK** [comment]
I don't have M1, but I can reproduce it using x86_64 cross compilation with thinlto.

@rustbot author

**Comment by DianQK** [comment]
The parameters of the failed linker are roughly:

```sh
cc librustc_driver.foo.o \
  /tmp/libcompiler_builtins.rlib -o librustc_driver.dylib
```

This causes the built-in functions we implemented using rust to be dropped.

I expect it to be:

```sh
cc librustc_driver.compiler_builtins.o librustc_driver.foo.o \
  /tmp/libcompiler_builtins.rlib -o librustc_driver.dylib
```

@rustbot ready

**Comment by DianQK** [comment]
Ping. Hopefully I can pass all the tests this time.

**Comment by lnicola** [comment]
@DianQK  I'm not supposed to r+ PRs, but I can at least do this:

@bors try

**Comment by saethlin** [comment]
I was debating re-adding the approval for this PR, but I think the new commit is just barely delta-reviewable (I don't understand the whole PR, but the most recent commit is hard to argue with) and some of T-compiler seems to agree.

@bors r=pnkfelix

**Comment by saethlin** [comment]
Same HTTP error as before
@bors retry

**Comment by DianQK** [comment]
😦😖😣
I only know how to use Windows. But let me first configure the development environment to see exactly what is causing the error.

**Comment by DianQK** [comment]
> The job **`x86_64-msvc`** failed! Check out the build log: [(web)](https://github.com/rust-lang-ci/rust/actions/runs/6887582429/job/18735013737) [(plain)](https://github.com/rust-lang-ci/rust/commit/fffba520cab5d0ecf8d4776a105b9e1dcc37aa1d/checks/18735013737/logs)
> Click to see the possible cause of the failure (guessed by this bot)

We need to add test support for thinlto. I created a PR #118036.

File: tests/run-make/no-builtins-lto/main.rs [hunk 11]
```diff
@@ -1,3 +1,28 @@
+#![feature(no_core, start, lang_items)]
+#![no_std]
+// We use `no_core` to reduce the LTO products is small enough.
+#![no_core]
+
 extern crate no_builtins;
+extern crate foo;
+
+#[link(name = "c")]
+extern "C" {}
```
[the remark this answers is not in the document]
Comment (DianQK) [reply tests/run-make/no-builtins-lto/main.rs]: You saved me time. Even though I don't have a test environment ready, this seems to make sense. Maybe we can try again.

**Comment by DianQK** [comment]
> The job **`x86_64-msvc`** failed! Check out the build log: [(web)](https://github.com/rust-lang-ci/rust/actions/runs/7063477730/job/19229571130) [(plain)](https://github.com/rust-lang-ci/rust/commit/974b31aae370139d4107788463f5ca53937ed52a/checks/19229571130/logs)
> Click to see the possible cause of the failure (guessed by this bot)

It works. But llvm-dis doesn't work on windows?

File: tests/run-make/no-builtins-lto/Makefile [hunk 12]
```diff
@@ -1,9 +1,15 @@
...
-	# Compile a `#![no_builtins]` rlib crate
-	$(RUSTC) no_builtins.rs
-	# Build an executable that depends on that crate using LTO. The no_builtins crate doesn't
-	# participate in LTO, so its rlib must be explicitly linked into the final binary. Verify this by
-	# grepping the linker arguments.
-	$(RUSTC) main.rs -C lto --print link-args | $(CGREP) 'libno_builtins.rlib'
+	$(RUSTC) -C linker-plugin-lto -C opt-level=2 -C debuginfo=0 foo.rs
+	$(RUSTC) -C linker-plugin-lto -C opt-level=2 -C debuginfo=0 no_builtins.rs
+	$(RUSTC) main.rs -C lto -C opt-level=2 -C debuginfo=0 -C save-temps -C metadata=1 -C codegen-units=1
+	$(LLVM_BIN_DIR)/llvm-dis $(TMPDIR)/main.main.*-cgu.0.rcgu.lto.input.bc -o $(TMPDIR)/lto.ll
```
Comment (bjorn3) [inline tests/run-make/no-builtins-lto/Makefile:14]: Looks like this got mangled to `C:arustrustbuildx86_64-pc-windows-msvcllvmbuildbin/llvm-dis`. Note the missing backslashes everywhere. You have to put `$(LLVM_BIN_DIR)` in quotes to prevent this issue.

Comment (DianQK) [reply tests/run-make/no-builtins-lto/Makefile]: I've just removed `llvm-dis`, and I can use `--emit=llvm-ir`

Comment (DianQK) [reply tests/run-make/no-builtins-lto/Makefile:14]: > ~I've just removed `llvm-dis`, and I can use `--emit=llvm-ir`.~

I also need to check the linker successfully.

**Comment by bjorn3** [comment]
It seems that linking has become 10-20ms slower and binaries ~260kb bigger. Maybe we no longer gc unused compiler builtins functions?

**Comment by nnethercote** [comment]
Right, those compile-time regressions are really bad :(  Lots of ~5% binary size increases, too. What can be done?

**Comment by bjorn3** [comment]
I believe I saw something around symbols being marked as "used". If this is currently linker used, maybe we can downgrade it to compiler used?

**Comment by DianQK** [comment]
> Right, those compile-time regressions are really bad :( Lots of ~5% binary size increases, too. What can be done?

I can verify that this indeed preserves builtin functions.

**Comment by DianQK** [comment]
> It seems that linking has become 10-20ms slower and binaries ~260kb bigger. Maybe we no longer gc unused compiler builtins functions?

This should be the right way to go.

> I believe I saw something around symbols being marked as "used". If this is currently linker used, maybe we can downgrade it to compiler used?

I will start debugging with your analysis this weekend. :)

**Comment by rylev** [comment]
https://github.com/rust-lang/rust/pull/118568 seems to reverse these perf regressions.

@rustbot label: +perf-regression-triaged
