### PR TITLE
Do not complain about unmentioned fields in recovered patterns

### LINKED ISSUE #59145: Syntax error in patterns should elide missing field errors
[The following code](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=cf4b33bcebbe1179dcb77c25e1d5ea09)
```
struct S {
    a: usize,
    b: usize,
}

fn main() {
    let s = S { a: 4, b: 2 };
    let S {a , ref b: _ } = s;
}
```

produces the following error:

```
error: expected `,`
 --> src/main.rs:8:20
  |
8 |     let S {a , ref b: _ } = s;
  |                    ^

error[E0027]: pattern does not mention fields `a`, `b`
 --> src/main.rs:8:9
  |
8 |     let S {a , ref b: _ } = s;
  |         ^^^^^^^^^^^^^^^^^ missing fields `a`, `b`
```

It shouldn't complain about the missing fields.

### PR DESCRIPTION
**Pull request by estebank**
When the parser has to recover from malformed code in a pattern, do not
complain about missing fields.

Fix #59145.

### CODE REVIEW

File: src/libsyntax/parse/parser.rs [hunk 1]
```diff
@@ -4698,7 +4698,7 @@ impl<'a> Parser<'a> {
                         let (fields, etc) = self.parse_pat_fields().unwrap_or_else(|mut e| {
                             e.emit();
                             self.recover_stmt();
-                            (vec![], false)
+                            (vec![], true)
```
Comment (zackmdavis) [inline src/libsyntax/parse/parser.rs]: Testing my understanding: this is getting assigned to the name `etc`; so, the mechanism here is that we're pretending that struct patterns that failed to parse have a `..` so that we shouldn't emit additional errors about missing fields?

Comment (estebank) [reply src/libsyntax/parse/parser.rs]: Correct.

**Comment by zackmdavis** [comment]
Looks like I need to keep better track of my review queue. :cold_sweat: 

r? @zackmdavis 

@bors r+
