### PR TITLE
Mark `std::os::wasi::io::AsFd` etc. as stable.

### LINKED ISSUE #103306: std::os::wasi::io::AsFd regression on Rust 1.64
I tried this code:

```rust
#![allow(unused_imports)]

use std::os::wasi::io::AsFd;
```

I expected to see this happen: it compiles

Instead, this happened:

With Rust 1.63, it compiles. With Rust 1.64 and Rust nightly, it gets this error:
```
error[E0658]: use of unstable library feature 'wasi_ext'
 --> src/lib.rs:3:5
  |
3 | use std::os::wasi::io::AsFd;
  |     ^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: see issue #71213 <https://github.com/rust-lang/rust/issues/71213> for more information
```

### PR DESCRIPTION
**Pull request by sunfishcode**
io_safety was stabilized in Rust 1.63, so mark the io_safety exports in `std::os::wasi::io` as stable.

Fixes #103306.

### CODE REVIEW

**Comment by compiler-errors** [comment]
This probably should also be beta (and stable?) nominated, so doing that now.

File: library/std/src/os/wasi/io/mod.rs [hunk 1]
```diff
@@ -2,5 +2,5 @@
 
 #![unstable(feature = "wasi_ext", issue = "71213")]
```
Comment (joshtriplett) [inline library/std/src/os/wasi/io/mod.rs:3]: Don't you also need the module itself to be stable?

Comment (sunfishcode) [reply library/std/src/os/wasi/io/mod.rs]: Ah, you're right. Fixed now.

**Comment by m-ou-se** [comment]
This briefly came up in the libs meeting today: https://rust-lang.zulipchat.com/#narrow/stream/259402-t-libs.2Fmeetings/topic/Meeting.202022-10-26/near/306260701

We're fine with backporting it to 1.65.0 (which is released in eight days from now), but it'd be good if this says `version = "1.65.0"` instead of `version = "1.63.0"` to avoid confusion for users on 1.64.0.
