### PR TITLE
Stabilize std::num

### LINKED ISSUE #21069: Numeric traits inconsistent with integer type system
From all the integer traits present in `std::num`, only `SignedInt` includes `Neg`. The `Neg` trait is not implemented by `Int` and `UnsignedInt` types because, presumably, it does not make sense to negate unsigned integers. I will not argue whether this is a good policy or not.

However, this makes writing generic code for unsigned types harder than it needs to be. For example, suppose we have the function 

    fn f(x: u32) -> u32 { -(x >> 31) }

This function works perfectly (albeit with a warning, but it *is* valid Rust as far as I can tell) when implemented with a concrete unsigned integer type. However, when making the function generic it stops working:

    fn f<T: UnsignedInt>(x: T) -> T { -(x >> (size_of::<T>()*8 - 1)) }
    // error: cannot apply unary operator `-` to type `T`

Changing this to `0 - <expression>` is a simple solution, but one that also does not work very well without pulling other (`NumCast`, `FromPrimitive`) traits. Another solution is to pull in the `Neg` trait directly, but this increases verbosity due to `Neg`'s associated type machinery. All in all, the lack of unsigned negation complicates things.

Now, I accept that you may not want to make unsigned negation common or encouraged behavior. But in that case it also makes no sense to have the `-` operator available at all for unsigned types; users that really want such semantics can replace it by `0-<expression>` in non-generic code. 

My overall point is:

 - If `u32`, `usize`, etc allow negation, i.e., have the `Neg` type implemented, so should `UnsignedInt`;
 - If `UnsignedInt` is not meant to be negatable, neither should be `u32`, `usize`, etc.

### LINKED ISSUE #22985: Maybe Float::{is_positive, is_negative} should return false for 0's?
Over the real numbers, one doesn't usually consider zero to be explicitly positive or negative (one has to qualify as "non-negative" or "non-positive" respectively to get those classes including zero), so it is a little strange to me that we include `0.0` in the former and `-0.0` in the latter.

However, floats are special (signed zero), so maybe the current behaviour is OK. I suppose the "real number" behaviour can be replicated with just `> 0.0` and `>= 0.0`, while these functions are checking the IEEE-754 sign bit.

### PR DESCRIPTION
**Pull request by aturon**
This commit stabilizes the `std::num` module:
- The `Int` and `Float` traits are deprecated in favor of (1) the
  newly-added inherent methods and (2) the generic traits available in
  rust-lang/num.
- The `Zero` and `One` traits are reintroduced in `std::num`, which
  together with various other traits allow you to recover the most
  common forms of generic programming.
- The `FromStrRadix` trait, and associated free function, is deprecated
  in favor of inherent implementations.
- A wide range of methods and constants for both integers and floating
  point numbers are now `#[stable]`, having been adjusted for integer
  guidelines.
- `is_positive` and `is_negative` are renamed to `is_sign_positive` and
  `is_sign_negative`, in order to address #22985
- The `Wrapping` type is moved to `std::num` and stabilized;
  `WrappingOps` is deprecated in favor of inherent methods on the
  integer types, and direct implementation of operations on
  `Wrapping<X>` for each concrete integer type `X`.

Closes #22985
Closes #21069

[breaking-change]

r? @alexcrichton

### CODE REVIEW

**Comment by aturon** [comment]
Note:

1. This is going to require some follow up work: there are a fair number of uses of `Int` and `Float` within the Rust distribution. In some cases, we may want to replace these with different traits, but that design work is left as a future step.

2. Currently, this is failing to build due to strange staging problems with the inherent `wrapping_add` etc methods.

File: src/libcore/num/wrapping.rs [hunk 1]
```diff
@@ -39,6 +52,49 @@ pub trait OverflowingOps {
...
 
+macro_rules! sh_impl {
+    ($t:ty, $f:ty) => (
+        #[stable(feature = "rust1", since = "1.0.0")]
+        impl Shl<$f> for Wrapping<$t> {
+            type Output = Wrapping<$t>;
+
+            #[inline(always)]
+            fn shl(self, other: $f) -> Wrapping<$t> {
+                Wrapping(self.0 << other)
```
Comment (huonw) [inline src/libcore/num/wrapping.rs]: I feel like these aren't actually doing the wrapping operation?

Comment (huonw) [inline src/libcore/num/wrapping.rs]: Actually I suppose they are, nvm.

Comment (aturon) [inline src/libcore/num/wrapping.rs]: Note: https://github.com/rust-lang/rust/issues/22020

**Comment by aturon** [comment]
Update: I've resolved the staging issue. There appears to be a bad interaction between int fallback and inherent impls. In this case adding a single type annotation was enough to solve the problem.

This should probably be investigated separately in a minimal test case.

**Comment by aturon** [comment]
Minimal test case here: https://github.com/rust-lang/rust/issues/23545#issuecomment-83943940

File: src/libcore/iter.rs [hunk 2]
```diff
@@ -2655,6 +2656,7 @@ pub fn range_step<A: Int>(start: A, stop: A, step: A) -> RangeStep<A> {
 }
 
 #[stable(feature = "rust1", since = "1.0.0")]
+#[allow(deprecated)]
```
Comment (alexcrichton) [inline src/libcore/iter.rs]: This seems somewhat worrisome to use these deprecated bounds in stable implementations. I think we had a problem in the past, for example, about an impl of `Iterator` for each concrete primitive type as a type parameter causes type inference to go awry. I forget the details, but we may want to deal with this sort of fallout sooner rather than later.

File: src/libcore/num/wrapping.rs [hunk 3]
```diff
@@ -7,7 +7,13 @@
 // <LICENSE-MIT or http://opensource.org/licenses/MIT>, at your
 // option. This file may not be copied, modified, or distributed
 // except according to those terms.
+
 #![allow(missing_docs)]
+#![allow(deprecated)]
+
+#[unstable(feature = "core", reason = "may be removed, renamed, or relocated")]
+#[deprecated(since = "1.0.0", reason = "moved to std::num")]
+pub use super::Wrapping;
```
Comment (alexcrichton) [inline src/libcore/num/wrapping.rs]: Due to deprecation warnings not working on reexports, I'd be fine just removing this for now.

File: src/libcore/num/wrapping.rs [hunk 4]
```diff
@@ -26,9 +32,16 @@ use intrinsics::{i16_mul_with_overflow, u16_mul_with_overflow};
 use intrinsics::{i32_mul_with_overflow, u32_mul_with_overflow};
 use intrinsics::{i64_mul_with_overflow, u64_mul_with_overflow};
 
+#[unstable(feature = "core", reason = "may be removed, renamed, or relocated")]
+#[deprecated(since = "1.0.0", reason = "moved to inherent methods")]
 pub trait WrappingOps {
+    // Methods stable to avoid warning on use via prelude
```
Comment (alexcrichton) [inline src/libcore/num/wrapping.rs]: Shouldn't the inherent methods be trumping these trait methods?

File: src/libcore/num/wrapping.rs [hunk 5]
```diff
@@ -39,6 +52,49 @@ pub trait OverflowingOps {
...
+
+            #[inline(always)]
+            fn shr(self, other: $f) -> Wrapping<$t> {
+                Wrapping(self.0 >> other)
+            }
+        }
+    )
+}
+
+// FIXME (#23545): uncomment the remaining impls
```
Comment (alexcrichton) [inline src/libcore/num/wrapping.rs]: I'm a little confused, is this intended to allow any type to be shifted by any other type?

File: src/libcore/num/wrapping.rs [hunk 6]
```diff
@@ -61,94 +117,79 @@ macro_rules! wrapping_impl {
...
 
-impl<T:WrappingOps+Shr<uint,Output=T>> Shr<uint> for Wrapping<T> {
-    type Output = Wrapping<T>;
-
-    #[inline(always)]
-    fn shr(self, other: uint) -> Wrapping<T> {
-        Wrapping(self.0 >> other)
-    }
-}
+wrapping_impl! { uint u8 u16 u32 u64 int i8 i16 i32 i64 }
```
Comment (alexcrichton) [inline src/libcore/num/wrapping.rs]: int/uint => isize/usize

File: src/librustc_lint/builtin.rs [hunk 7]
```diff
@@ -41,6 +41,7 @@ use lint::{Level, Context, LintPass, LintArray, Lint};
 
 use std::collections::BitSet;
 use std::collections::hash_map::Entry::{Occupied, Vacant};
+#[allow(deprecated)]
 use std::num::SignedInt;
```
Comment (alexcrichton) [inline src/librustc_lint/builtin.rs]: Shouldn't this be removed? I would figure the inherent methods would be used instead.

Comment (alexcrichton) [inline src/librustc_lint/builtin.rs]: Actually there's a bunch of `#[allow(deprecated)]` imports of these traits, but I'm not sure they all correspond to a generic bound, so it seems like they should be able to be removed?

File: src/libstd/num/f64.rs [hunk 8]
```diff
@@ -83,6 +83,7 @@ mod cmath {
 }
 
 #[stable(feature = "rust1", since = "1.0.0")]
+#[allow(deprecated)]
 impl Float for f64 {
```
Comment (alexcrichton) [inline src/libstd/num/f64.rs]: These should all be redefined as inherent methods, right?

File: src/libcore/iter.rs (hunk 2 above)
Comment (aturon) [inline src/libcore/iter.rs]: Yes, I agree; see https://github.com/rust-lang/rust/pull/23549#issuecomment-83940365

File: src/libcore/num/wrapping.rs (hunk 4 above)
Comment (aturon) [inline src/libcore/num/wrapping.rs]: Yes. I can try removing these attributes again, it may have been resolved by changes elsewhere.

Comment (aturon) [inline src/libcore/num/wrapping.rs]: (Also note, `WrappingOps` should be deprecated, not sure why it's not.)

File: src/libcore/num/wrapping.rs (hunk 5 above)
Comment (aturon) [inline src/libcore/num/wrapping.rs]: In the long run, yes. We do the same thing for the base numeric types. (That's where this macro setup is from.)

File: src/librustc_lint/builtin.rs (hunk 7 above)
Comment (aturon) [inline src/librustc_lint/builtin.rs]: Yes, I tried to remove the ones that were only used for methods, but I may have missed some...

File: src/libstd/num/f64.rs (hunk 8 above)
Comment (aturon) [inline src/libstd/num/f64.rs]: They are, I believe. (Minus a few that are just being dropped, like `zero`.)

File: src/libcore/iter.rs (hunk 2 above)
Comment (alexcrichton) [inline src/libcore/iter.rs]: My only worry is that this sort of usage of `Int` is not warned about in the unstable lint, so we could alter this functionality of code using 100% stable code and we could still break them. This is pretty minor breakage though so it's not necessarily that bad.

File: src/libstd/num/f64.rs (hunk 8 above)
Comment (alexcrichton) [inline src/libstd/num/f64.rs]: Ah, ok!

**Comment by alexcrichton** [comment]
Could this also handle https://github.com/rust-lang/rust/issues/23454? (it seems they should both be removed?)

**Comment by aturon** [comment]
Updated, adding `Zero` and `One`, and removing many imports of `Int` along the way.

@alexcrichton I believe this addresses your concerns.

**Comment by aturon** [comment]
Rebased.

File: src/libcore/iter.rs [hunk 9]
```diff
@@ -2771,29 +2776,22 @@ macro_rules! range_exact_iter_impl {
...
-
-    #[inline]
-    fn size_hint(&self) -> (usize, Option<usize>) {
-        if self.start >= self.end {
-            (0, Some(0))
-        } else {
-            let length = (self.end - self.start).to_usize();
-            (length.unwrap_or(0), length)
-        }
-    }
```
Comment (alexcrichton) [inline src/libcore/iter.rs]: This may end up having unfortunate perf side effects, but we may be able to regain it later

File: src/libcore/num/mod.rs [hunk 10]
```diff
@@ -32,11 +32,66 @@ use option::Option::{self, Some, None};
...
+#[unstable(feature = "zero_one",
+           reason = "unsure of placement, wants to use associated constants")]
+pub trait One {
+    /// The "one" (usually, multiplicative identity) for this type.
+    fn one() -> Self;
+}
+
+macro_rules! zero_one_impl {
+    ($($t:ty)*) => ($(
+        #[inline]
```
Comment (alexcrichton) [inline src/libcore/num/mod.rs]: I don't think this `#[inline]` will affect much up here (e.g. move on method?)

File: src/libcore/num/wrapping.rs (hunk 4 above)
Comment (alexcrichton) [inline src/libcore/num/wrapping.rs]: I think this comment can be removed now

File: src/libcore/num/wrapping.rs (hunk 3 above)
Comment (alexcrichton) [inline src/libcore/num/wrapping.rs]: ping to remove

File: src/librustc_trans/back/lto.rs [hunk 11]
```diff
@@ -22,6 +22,7 @@ use flate;
 
 use std::ffi::CString;
 use std::mem;
+#[allow(deprecated)]
```
Comment (alexcrichton) [inline src/librustc_trans/back/lto.rs]: ping on checking whether these imports can be removed

File: src/libcore/iter.rs (hunk 9 above)
Comment (aturon) [inline src/libcore/iter.rs]: Indeed. There are various possibilities for regaining it (including something like `ToPrimitive`, or perhaps based on our new conversion traits).

That said, do you think we should worry about the hit now? This PR could be tweaked in that direction...

**Comment by alexcrichton** [comment]
A few nits here and there, but otherwise this all looks great to me! r=me with nits updated

File: src/libcore/iter.rs (hunk 9 above)
Comment (alexcrichton) [inline src/libcore/iter.rs]: If we have a solution on hand I think we should implement it now, but otherwise I think we'll just have to hold off and wait.

File: src/librustc_trans/back/lto.rs (hunk 11 above)
Comment (aturon) [inline src/librustc_trans/back/lto.rs]: I removed all of them that could easily be replaced with `One`/`Zero` or were needed only for methods (afaik).

**Comment by theemathas** [comment]
Should `is_sign_positive` and `is_sign_negative` be renamed to `is_sign_bit_positive` and `is_sign_bit_negative`? Just adding "sign" does not clarify anything.

**Comment by huonw** [comment]
> is_positive and is_negative are renamed to is_sign_positive and
is_sign_negative, in order to address #22985

Hm, do we actually need both? They're strict logical negations of each other.

**Comment by aturon** [comment]
@alexcrichton Want to re-review? I've added back the `Step` trait (as unstable), which should pretty clearly be replaced by some other traits in the future.

re: the sign checks, I'm happy to change the name to further clarify, and to drop one of the variants if preferred. e.g., `is_sign_bit_positive` only (though that's a pretty lengthy name...)

**Comment by aturon** [comment]
@bors: r-

Tests failed locally.

**Comment by pitdicker** [comment]
Would it be possible to wait a little bit with stabilizing abs()?
I hope it can give my rfc a chance...
https://github.com/rust-lang/rfcs/pull/1017

**Comment by SSheldon** [comment]
After this lands, will there be any way to get the max value of, for example, `c_int`? Previously that could be done using `Int::max_value`, but I'm not seeing an alternative.

**Comment by japaric** [comment]
@SSheldon you can use `c_int::max_value()` (it already works today) because `c_int` is just a type alias to an integer primitive.

**Comment by SSheldon** [comment]
@japaric, oh wow, I could've sworn you couldn't call static methods through a type alias. Thanks!

**Comment by aturon** [comment]
@bors: r=alexcrichton a680fe3

@pitdicker I will discuss your RFC with the core team, this PR does not preclude the change before 1.0.

**Comment by Manishearth** [comment]
(force wasn't acting a bit quirky)

**Comment by Manishearth** [comment]
```
failures:

---- f32::tan_0 stdout ----
	thread 'f32::tan_0' panicked at 'test executable failed:

thread '<main>' panicked at 'assertion failed: abs_difference < f32::EPSILON', <anon>:9
', /home/ubuntu/src/rust-buildbot/slave/auto-linux-32-nopt-t/build/src/librustdoc/test.rs:246


```
