### PR TITLE
resolve: Preserve reexport chains in `ModChild`ren

### LINKED ISSUE #109424: rustdoc ICE: no resolutions for a doc link
### Code

Panic occurs when running `cargo doc` on my project [here](https://github.com/kyp44/advent-of-code). This is specifically on the current `transfer` branch of the project with commit hash [c1d04db7977d2de43d69ea9f8795905f60b3b8ba](https://github.com/kyp44/advent-of-code/commit/c1d04db7977d2de43d69ea9f8795905f60b3b8ba). Note that this project does include the `Cargo.lock` file, and that the project compiles normally (i.e. with `cargo build`) just fine.

### Meta

`cargo --version --verbose`:
```
cargo 1.70.0-nightly (4a3c588b1 2023-03-14)
release: 1.70.0-nightly
commit-hash: 4a3c588b1f0a8e2dc8dd8789dbf3b6a71b02ed49
commit-date: 2023-03-14
host: x86_64-unknown-linux-gnu
libgit2: 1.5.0 (sys:0.16.0 vendored)
libcurl: 7.86.0-DEV (sys:0.4.59+curl-7.86.0 vendored ssl:OpenSSL/1.1.1q)
os: Ubuntu 22.04 (jammy) [64-bit]
```

`rustc --version --verbose`:
```
rustc 1.70.0-nightly (44f518058 2023-03-20)
binary: rustc
commit-hash: 44f5180584404d18058cbbf224c55255db4fdcbb
commit-date: 2023-03-20
host: x86_64-unknown-linux-gnu
release: 1.70.0-nightly
LLVM version: 15.0.7
```

### Error output

There are numerous panics when running `cargo doc`, but the first one seems to happen while `Checking serde_json v1.0.94`:
```
thread 'rustc' panicked at 'no resolutions for a doc link', compiler/rustc_metadata/src/rmeta/encoder.rs:2235:18
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
stack backtrace:
   0:     0x7f04c0d66bfa - std::backtrace_rs::backtrace::libunwind::trace::h02b863e4bfcd5ee4
                               at /rustc/44f5180584404d18058cbbf224c55255db4fdcbb/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x7f04c0d66bfa - std::backtrace_rs::backtrace::trace_unsynchronized::h00a2c275504a104d
                               at /rustc/44f5180584404d18058cbbf224c55255db4fdcbb/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7f04c0d66bfa - std::sys_common::backtrace::_print_fmt::h026a22e05cf38896
                               at /rustc/44f5180584404d18058cbbf224c55255db4fdcbb/library/std/src/sys_common/backtrace.rs:65:5
   3:     0x7f04c0d66bfa - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h34a8f50cf2d025fa
                               at /rustc/44f5180584404d18058cbbf224c55255db4fdcbb/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x7f04c0dca21e - core::fmt::write::h5b51ab21f7d1e0b3
                               at /rustc/44f5180584404d18058cbbf224c55255db4fdcbb/library/core/src/fmt/mod.rs:1254:17
   5:     0x7f04c0d59a85 - std::io::Write::write_fmt::hf4fa62cadc893d5c
                               at /rustc/44f5180584404d18058cbbf224c55255db4fdcbb/library/std/src/io/mod.rs:1698:15
   6:     0x7f04c0d669c5 - std::sys_common::backtrace::_print::ha17a326a77d0900c
                               at /rustc/44f5180584404d18058cbbf224c55255db4fdcbb/library/std/src/sys_common/backtrace.rs:47:5
   7:     0x7f04c0d669c5 - std::sys_common::backtrace::print::h4547d3fae20fb79a
                               at /rustc/44f5180584404d18058cbbf224c55255db4fdcbb/library/std/src/sys_common/backtrace.rs:34:9
   8:     0x7f04c0d6973f - std::panicking::default_hook::{{closure}}::hc37cfbcbf13dea2f
                               at /rustc/44f5180584404d18058cbbf224c55255db4fdcbb/library/std/src/panicking.rs:271:22
   9:     0x7f04c0d6947b - std::panicking::default_hook::h68329187d8716430
                               at /rustc/44f5180584404d18058cbbf224c55255db4fdcbb/library/std/src/panicking.rs:290:9
  10:     0x7f04c3fb53f5 - <rustc_driver_impl[e865fcce65453e97]::DEFAULT_HOOK::{closure#0}::{closure#0} as core[e92a6e72e88848e6]::ops::function::FnOnce<(&core[e92a6e72e88848e6]::panic::panic_info::PanicInfo,)>>::call_once::{shim:vtable#0}
  11:     0x7f04c0d69f7d - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::he6b1b104583416f4
                               at /rustc/44f5180584404d18058cbbf224c55255db4fdcbb/library/alloc/src/boxed.rs:2002:9
  12:     0x7f04c0d69f7d - std::panicking::rust_panic_with_hook::h89588635866984f2
                               at /rustc/44f5180584404d18058cbbf224c55255db4fdcbb/library/std/src/panicking.rs:696:13
  13:     0x7f04c0d69cf9 - std::panicking::begin_panic_handler::{{closure}}::haf7e5802c3a8728c
                               at /rustc/44f5180584404d18058cbbf224c55255db4fdcbb/library/std/src/panicking.rs:583:13
  14:     0x7f04c0d67066 - std::sys_common::backtrace::__rust_end_short_backtrace::h8100acaef4dcb737
                               at /rustc/44f5180584404d18058cbbf224c55255db4fdcbb/library/std/src/sys_common/backtrace.rs:150:18
  15:     0x7f04c0d69a02 - rust_begin_unwind
                               at /rustc/44f5180584404d18058cbbf224c55255db4fdcbb/library/std/src/panicking.rs:579:5
  16:     0x7f04c0dc6573 - core::panicking::panic_fmt::h176c535e62b8ef16
                               at /rustc/44f5180584404d18058cbbf224c55255db4fdcbb/library/core/src/panicking.rs:64:14
  17:     0x7f04c0dc66e1 - core::panicking::panic_display::h59bc55a12419d24e
                               at /rustc/44f5180584404d18058cbbf224c55255db4fdcbb/library/core/src/panicking.rs:147:5
  18:     0x7f04c0dc668b - core::panicking::panic_str::hf7a9b345df0273a6
                               at /rustc/44f5180584404d18058cbbf224c55255db4fdcbb/library/core/src/panicking.rs:131:5
  19:     0x7f04c0dc62f6 - core::option::expect_failed::ha547da0b831768e9
                               at /rustc/44f5180584404d18058cbbf224c55255db4fdcbb/library/core/src/option.rs:2091:5
  20:     0x7f04c447cb4a - <rustc_metadata[d1c7680efe9369f1]::rmeta::encoder::provide::{closure#0} as core[e92a6e72e88848e6]::ops::function::FnOnce<(rustc_middle[20900d4515e9a17b]::ty::context::TyCtxt, rustc_span[f138f19c2ce8dad]::def_id::DefId)>>::call_once
  21:     0x7f04c487ae5d - rustc_query_system[17296292601d89b2]::query::plumbing::try_execute_query::<rustc_query_impl[f65bb69a3c105d87]::queries::doc_link_resolutions, rustc_query_impl[f65bb69a3c105d87]::plumbing::QueryCtxt>
  22:     0x7f04c490a807 - <rustc_query_impl[f65bb69a3c105d87]::Queries as rustc_middle[20900d4515e9a17b]::ty::query::QueryEngine>::doc_link_resolutions
  23:     0x556b8ea2aeab - <rustdoc[6fdc5879a6c0809c]::passes::collect_intra_doc_links::LinkCollector>::resolve_path
  24:     0x556b8ea2eeab - <rustdoc[6fdc5879a6c0809c]::passes::collect_intra_doc_links::LinkCollector as rustdoc[6fdc5879a6c0809c]::visit::DocVisitor>::visit_item
  25:     0x556b8ea37b6a - <rustdoc[6fdc5879a6c0809c]::passes::collect_intra_doc_links::LinkCollector as rustdoc[6fdc5879a6c0809c]::visit::DocVisitor>::visit_inner_recur
  26:     0x556b8ea31d54 - <rustdoc[6fdc5879a6c0809c]::passes::collect_intra_doc_links::LinkCollector as rustdoc[6fdc5879a6c0809c]::visit::DocVisitor>::visit_item
  27:     0x556b8ea37b6a - <rustdoc[6fdc5879a6c0809c]::passes::collect_intra_doc_links::LinkCollector as rustdoc[6fdc5879a6c0809c]::visit::DocVisitor>::visit_inner_recur
  28:     0x556b8ea31d54 - <rustdoc[6fdc5879a6c0809c]::passes::collect_intra_doc_links::LinkCollector as rustdoc[6fdc5879a6c0809c]::visit::DocVisitor>::visit_item
  29:     0x556b8ea29a9f - rustdoc[6fdc5879a6c0809c]::passes::collect_intra_doc_links::collect_intra_doc_links
  30:     0x556b8e9f166e - <rustc_session[ae3e11cc9a6ced82]::session::Session>::time::<rustdoc[6fdc5879a6c0809c]::clean::types::Crate, rustdoc[6fdc5879a6c0809c]::core::run_global_ctxt::{closure#7}>
  31:     0x556b8eab9390 - rustdoc[6fdc5879a6c0809c]::core::run_global_ctxt
  32:     0x556b8e9f18f9 - <rustc_session[ae3e11cc9a6ced82]::session::Session>::time::<(rustdoc[6fdc5879a6c0809c]::clean::types::Crate, rustdoc[6fdc5879a6c0809c]::config::RenderOptions, rustdoc[6fdc5879a6c0809c]::formats::cache::Cache), rustdoc[6fdc5879a6c0809c]::main_args::{closure#1}::{closure#0}::{closure#0}::{closure#0}>
  33:     0x556b8e9541c7 - <rustc_middle[20900d4515e9a17b]::ty::context::GlobalCtxt>::enter::<rustdoc[6fdc5879a6c0809c]::main_args::{closure#1}::{closure#0}::{closure#0}, core[e92a6e72e88848e6]::result::Result<(), rustc_span[f138f19c2ce8dad]::ErrorGuaranteed>>
  34:     0x556b8e8cb450 - <rustc_interface[cef7fd7d041aab20]::interface::Compiler>::enter::<rustdoc[6fdc5879a6c0809c]::main_args::{closure#1}::{closure#0}, core[e92a6e72e88848e6]::result::Result<(), rustc_span[f138f19c2ce8dad]::ErrorGuaranteed>>
  35:     0x556b8e9f0c0b - rustc_span[f138f19c2ce8dad]::with_source_map::<core[e92a6e72e88848e6]::result::Result<(), rustc_span[f138f19c2ce8dad]::ErrorGuaranteed>, rustc_interface[cef7fd7d041aab20]::interface::run_compiler<core[e92a6e72e88848e6]::result::Result<(), rustc_span[f138f19c2ce8dad]::ErrorGuaranteed>, rustdoc[6fdc5879a6c0809c]::main_args::{closure#1}>::{closure#0}::{closure#0}>
  36:     0x556b8e8cd1e4 - <scoped_tls[99df3e36d6c94ca5]::ScopedKey<rustc_span[f138f19c2ce8dad]::SessionGlobals>>::set::<rustc_interface[cef7fd7d041aab20]::interface::run_compiler<core[e92a6e72e88848e6]::result::Result<(), rustc_span[f138f19c2ce8dad]::ErrorGuaranteed>, rustdoc[6fdc5879a6c0809c]::main_args::{closure#1}>::{closure#0}, core[e92a6e72e88848e6]::result::Result<(), rustc_span[f138f19c2ce8dad]::ErrorGuaranteed>>
  37:     0x556b8e9ff600 - std[f90515c7d1e58fcd]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[cef7fd7d041aab20]::util::run_in_thread_pool_with_globals<rustc_interface[cef7fd7d041aab20]::interface::run_compiler<core[e92a6e72e88848e6]::result::Result<(), rustc_span[f138f19c2ce8dad]::ErrorGuaranteed>, rustdoc[6fdc5879a6c0809c]::main_args::{closure#1}>::{closure#0}, core[e92a6e72e88848e6]::result::Result<(), rustc_span[f138f19c2ce8dad]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[e92a6e72e88848e6]::result::Result<(), rustc_span[f138f19c2ce8dad]::ErrorGuaranteed>>
  38:     0x556b8eaad69d - <<std[f90515c7d1e58fcd]::thread::Builder>::spawn_unchecked_<rustc_interface[cef7fd7d041aab20]::util::run_in_thread_pool_with_globals<rustc_interface[cef7fd7d041aab20]::interface::run_compiler<core[e92a6e72e88848e6]::result::Result<(), rustc_span[f138f19c2ce8dad]::ErrorGuaranteed>, rustdoc[6fdc5879a6c0809c]::main_args::{closure#1}>::{closure#0}, core[e92a6e72e88848e6]::result::Result<(), rustc_span[f138f19c2ce8dad]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[e92a6e72e88848e6]::result::Result<(), rustc_span[f138f19c2ce8dad]::ErrorGuaranteed>>::{closure#1} as core[e92a6e72e88848e6]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  39:     0x7f04c0d73e53 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h75ab31ff38cd6fd4
                               at /rustc/44f5180584404d18058cbbf224c55255db4fdcbb/library/alloc/src/boxed.rs:1988:9
  40:     0x7f04c0d73e53 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h2ba977e91260a719
                               at /rustc/44f5180584404d18058cbbf224c55255db4fdcbb/library/alloc/src/boxed.rs:1988:9
  41:     0x7f04c0d73e53 - std::sys::unix::thread::Thread::new::thread_start::h132d174660c69668
                               at /rustc/44f5180584404d18058cbbf224c55255db4fdcbb/library/std/src/sys/unix/thread.rs:108:17
  42:     0x7f04c0894b43 - start_thread
                               at ./nptl/./nptl/pthread_create.c:442:8
  43:     0x7f04c0926a00 - clone3
                               at ./misc/../sysdeps/unix/sysv/linux/x86_64/clone3.S:81
  44:                0x0 - <unknown>
```

</p>
</details>

### LINKED ISSUE #109614: `cargo doc` panic (No resolutions for a doc link)
### Code

**N/A**

### Meta

`rustc --version --verbose`:
```
rustc 1.70.0-nightly (1459b3128 2023-03-23)
binary: rustc
commit-hash: 1459b3128e288a85fcc4dd1fee7ada2cdcf28794
commit-date: 2023-03-23
host: x86_64-unknown-linux-gnu
release: 1.70.0-nightly
LLVM version: 15.0.7
```

### Error output

```
[...]
 Documenting clap_lex v0.3.3
thread 'rustc' panicked at 'no resolutions for a doc link', compiler/rustc_metadata/src/rmeta/encoder.rs:2251:18
stack backtrace:
   0:     0x7f1e0116580a - std::backtrace_rs::backtrace::libunwind::trace::h3973f51617998fc6
                               at /rustc/1459b3128e288a85fcc4dd1fee7ada2cdcf28794/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x7f1e0116580a - std::backtrace_rs::backtrace::trace_unsynchronized::hc880f45678a36b06
                               at /rustc/1459b3128e288a85fcc4dd1fee7ada2cdcf28794/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7f1e0116580a - std::sys_common::backtrace::_print_fmt::h0c5a990bb8ef31fa
                               at /rustc/1459b3128e288a85fcc4dd1fee7ada2cdcf28794/library/std/src/sys_common/backtrace.rs:65:5
   3:     0x7f1e0116580a - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h55a8e98b4c6161da
                               at /rustc/1459b3128e288a85fcc4dd1fee7ada2cdcf28794/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x7f1e011c947e - core::fmt::write::h4c40d77c4903afa0
                               at /rustc/1459b3128e288a85fcc4dd1fee7ada2cdcf28794/library/core/src/fmt/mod.rs:1254:17
   5:     0x7f1e01158485 - std::io::Write::write_fmt::ha3b362d3dcfb999f
                               at /rustc/1459b3128e288a85fcc4dd1fee7ada2cdcf28794/library/std/src/io/mod.rs:1698:15
   6:     0x7f1e011655d5 - std::sys_common::backtrace::_print::h8269abb9d4b9ac2e
                               at /rustc/1459b3128e288a85fcc4dd1fee7ada2cdcf28794/library/std/src/sys_common/backtrace.rs:47:5
   7:     0x7f1e011655d5 - std::sys_common::backtrace::print::h475ddad52d027480
                               at /rustc/1459b3128e288a85fcc4dd1fee7ada2cdcf28794/library/std/src/sys_common/backtrace.rs:34:9
   8:     0x7f1e0116834f - std::panicking::default_hook::{{closure}}::hdb1a9b91764be170
                               at /rustc/1459b3128e288a85fcc4dd1fee7ada2cdcf28794/library/std/src/panicking.rs:271:22
   9:     0x7f1e0116808b - std::panicking::default_hook::hb3624b5fb0dd82aa
                               at /rustc/1459b3128e288a85fcc4dd1fee7ada2cdcf28794/library/std/src/panicking.rs:290:9
  10:     0x7f1e0448f225 - rustc_driver_impl[159109056ec6dbcd]::DEFAULT_HOOK::{closure#0}::{closure#0}
  11:     0x7f1e01168b8d - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::hce90bfe2d8d3bfad
                               at /rustc/1459b3128e288a85fcc4dd1fee7ada2cdcf28794/library/alloc/src/boxed.rs:2002:9
  12:     0x7f1e01168b8d - std::panicking::rust_panic_with_hook::h34c77a71befec972
                               at /rustc/1459b3128e288a85fcc4dd1fee7ada2cdcf28794/library/std/src/panicking.rs:696:13
  13:     0x7f1e01168909 - std::panicking::begin_panic_handler::{{closure}}::hb5ae8193b4163d8b
                               at /rustc/1459b3128e288a85fcc4dd1fee7ada2cdcf28794/library/std/src/panicking.rs:583:13
  14:     0x7f1e01165c76 - std::sys_common::backtrace::__rust_end_short_backtrace::h53bbfcb82ab0fc3b
                               at /rustc/1459b3128e288a85fcc4dd1fee7ada2cdcf28794/library/std/src/sys_common/backtrace.rs:150:18
  15:     0x7f1e01168612 - rust_begin_unwind
                               at /rustc/1459b3128e288a85fcc4dd1fee7ada2cdcf28794/library/std/src/panicking.rs:579:5
  16:     0x7f1e011c57f3 - core::panicking::panic_fmt::h712e519910af2aa1
                               at /rustc/1459b3128e288a85fcc4dd1fee7ada2cdcf28794/library/core/src/panicking.rs:64:14
  17:     0x7f1e011c5573 - core::panicking::panic_display::h73327eaae8c72270
                               at /rustc/1459b3128e288a85fcc4dd1fee7ada2cdcf28794/library/core/src/panicking.rs:147:5
  18:     0x7f1e011c5573 - core::panicking::panic_str::h5efcc14bd7078c99
                               at /rustc/1459b3128e288a85fcc4dd1fee7ada2cdcf28794/library/core/src/panicking.rs:131:5
  19:     0x7f1e011c5573 - core::option::expect_failed::h378c2f45805bd9f3
                               at /rustc/1459b3128e288a85fcc4dd1fee7ada2cdcf28794/library/core/src/option.rs:2055:5
  20:     0x7f1e0491bc3c - <rustc_metadata[3a094ff839502453]::rmeta::encoder::provide::{closure#0} as core[9d00a47b0220fcc3]::ops::function::FnOnce<(rustc_middle[8aa151a798159f2c]::ty::context::TyCtxt, rustc_span[13ea7f588b3c13d6]::def_id::LocalDefId)>>::call_once
  21:     0x7f1e04d15298 - rustc_query_system[fd8aa6351e8df40e]::query::plumbing::try_execute_query::<rustc_query_impl[eee500123a0977cb]::queries::doc_link_resolutions, rustc_query_impl[eee500123a0977cb]::plumbing::QueryCtxt>
  22:     0x7f1e04da56a7 - <rustc_query_impl[eee500123a0977cb]::Queries as rustc_middle[8aa151a798159f2c]::ty::query::QueryEngine>::doc_link_resolutions
  23:     0x558c6fa9af3f - <rustdoc[853469566b21e95f]::passes::collect_intra_doc_links::LinkCollector>::resolve_path
  24:     0x558c6fa9b108 - <rustdoc[853469566b21e95f]::passes::collect_intra_doc_links::LinkCollector>::resolve
  25:     0x558c6fa9ec64 - <rustdoc[853469566b21e95f]::passes::collect_intra_doc_links::LinkCollector>::resolve_links
  26:     0x558c6faaa150 - <rustdoc[853469566b21e95f]::passes::collect_intra_doc_links::LinkCollector as rustdoc[853469566b21e95f]::visit::DocVisitor>::visit_inner_recur
  27:     0x558c6faaa138 - <rustdoc[853469566b21e95f]::passes::collect_intra_doc_links::LinkCollector as rustdoc[853469566b21e95f]::visit::DocVisitor>::visit_inner_recur
  28:     0x558c6fa99ab9 - rustdoc[853469566b21e95f]::passes::collect_intra_doc_links::collect_intra_doc_links
  29:     0x558c6faac2a1 - <rustc_session[e3b3f8e1183b0336]::session::Session>::time::<rustdoc[853469566b21e95f]::clean::types::Crate, rustdoc[853469566b21e95f]::core::run_global_ctxt::{closure#7}>
  30:     0x558c6fb5bfeb - rustdoc[853469566b21e95f]::core::run_global_ctxt
  31:     0x558c6faac529 - <rustc_session[e3b3f8e1183b0336]::session::Session>::time::<(rustdoc[853469566b21e95f]::clean::types::Crate, rustdoc[853469566b21e95f]::config::RenderOptions, rustdoc[853469566b21e95f]::formats::cache::Cache), rustdoc[853469566b21e95f]::main_args::{closure#1}::{closure#0}::{closure#0}::{closure#0}>
  32:     0x558c6f94c5b7 - <rustc_middle[8aa151a798159f2c]::ty::context::GlobalCtxt>::enter::<rustdoc[853469566b21e95f]::main_args::{closure#1}::{closure#0}::{closure#0}, core[9d00a47b0220fcc3]::result::Result<(), rustc_span[13ea7f588b3c13d6]::ErrorGuaranteed>>
  33:     0x558c6f94b580 - <rustc_interface[3eea5f8e37acaac7]::interface::Compiler>::enter::<rustdoc[853469566b21e95f]::main_args::{closure#1}::{closure#0}, core[9d00a47b0220fcc3]::result::Result<(), rustc_span[13ea7f588b3c13d6]::ErrorGuaranteed>>
  34:     0x558c6fad79cb - rustc_span[13ea7f588b3c13d6]::with_source_map::<core[9d00a47b0220fcc3]::result::Result<(), rustc_span[13ea7f588b3c13d6]::ErrorGuaranteed>, rustc_interface[3eea5f8e37acaac7]::interface::run_compiler<core[9d00a47b0220fcc3]::result::Result<(), rustc_span[13ea7f588b3c13d6]::ErrorGuaranteed>, rustdoc[853469566b21e95f]::main_args::{closure#1}>::{closure#0}::{closure#0}>
  35:     0x558c6f94e9d4 - <scoped_tls[fb9b4801708e8a70]::ScopedKey<rustc_span[13ea7f588b3c13d6]::SessionGlobals>>::set::<rustc_interface[3eea5f8e37acaac7]::interface::run_compiler<core[9d00a47b0220fcc3]::result::Result<(), rustc_span[13ea7f588b3c13d6]::ErrorGuaranteed>, rustdoc[853469566b21e95f]::main_args::{closure#1}>::{closure#0}, core[9d00a47b0220fcc3]::result::Result<(), rustc_span[13ea7f588b3c13d6]::ErrorGuaranteed>>
  36:     0x558c6fae6a60 - std[2b8d1b569764f7c5]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[3eea5f8e37acaac7]::util::run_in_thread_pool_with_globals<rustc_interface[3eea5f8e37acaac7]::interface::run_compiler<core[9d00a47b0220fcc3]::result::Result<(), rustc_span[13ea7f588b3c13d6]::ErrorGuaranteed>, rustdoc[853469566b21e95f]::main_args::{closure#1}>::{closure#0}, core[9d00a47b0220fcc3]::result::Result<(), rustc_span[13ea7f588b3c13d6]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[9d00a47b0220fcc3]::result::Result<(), rustc_span[13ea7f588b3c13d6]::ErrorGuaranteed>>
  37:     0x558c6fb889cd - <<std[2b8d1b569764f7c5]::thread::Builder>::spawn_unchecked_<rustc_interface[3eea5f8e37acaac7]::util::run_in_thread_pool_with_globals<rustc_interface[3eea5f8e37acaac7]::interface::run_compiler<core[9d00a47b0220fcc3]::result::Result<(), rustc_span[13ea7f588b3c13d6]::ErrorGuaranteed>, rustdoc[853469566b21e95f]::main_args::{closure#1}>::{closure#0}, core[9d00a47b0220fcc3]::result::Result<(), rustc_span[13ea7f588b3c13d6]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[9d00a47b0220fcc3]::result::Result<(), rustc_span[13ea7f588b3c13d6]::ErrorGuaranteed>>::{closure#1} as core[9d00a47b0220fcc3]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  38:     0x7f1e01172c03 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h5465857e83d6d8ca
                               at /rustc/1459b3128e288a85fcc4dd1fee7ada2cdcf28794/library/alloc/src/boxed.rs:1988:9
  39:     0x7f1e01172c03 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::ha9ee3b71411efa49
                               at /rustc/1459b3128e288a85fcc4dd1fee7ada2cdcf28794/library/alloc/src/boxed.rs:1988:9
  40:     0x7f1e01172c03 - std::sys::unix::thread::Thread::new::thread_start::hade30c6a6cbcfe88
                               at /rustc/1459b3128e288a85fcc4dd1fee7ada2cdcf28794/library/std/src/sys/unix/thread.rs:108:17
  41:     0x7f1e00e94b43 - <unknown>
  42:     0x7f1e00f26a00 - <unknown>
  43:                0x0 - <unknown>

error: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.70.0-nightly (1459b3128 2023-03-23) running on x86_64-unknown-linux-gnu

note: compiler flags: --crate-type lib

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [doc_link_resolutions] resolutions for documentation links for a module
end of query stack
error: could not document `rustix`

Caused by:
  process didn't exit successfully: `rustdoc --edition=2018 --crate-type lib --crate-name rustix /home/alejandra/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rustix-0.36.11/src/lib.rs --cap-lints allow -o /home/alejandra/git/wawat/cuteness/target/doc --cfg 'feature="default"' --cfg 'feature="io-lifetimes"' --cfg 'feature="libc"' --cfg 'feature="std"' --cfg 'feature="termios"' --cfg 'feature="use-libc-auxv"' --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --diagnostic-width=213 -C metadata=c8bad158e10ac0de -L dependency=/home/alejandra/git/wawat/cuteness/target/debug/deps --extern bitflags=/home/alejandra/git/wawat/cuteness/target/debug/deps/libbitflags-f75283d3dcd3daad.rmeta --extern io_lifetimes=/home/alejandra/git/wawat/cuteness/target/debug/deps/libio_lifetimes-0e896a4daa128e32.rmeta --extern libc=/home/alejandra/git/wawat/cuteness/target/debug/deps/liblibc-8aab922602f2fc15.rmeta --extern linux_raw_sys=/home/alejandra/git/wawat/cuteness/target/debug/deps/liblinux_raw_sys-a31463b73c270e13.rmeta --crate-version 0.36.11 --cfg rustc_attrs --cfg linux_raw --cfg core_intrinsics --cfg asm` (exit status: 101)
warning: build failed, waiting for other jobs to finish...
```

---

Weirdly, the output is longer than the backtrace.

---

<details><summary><strong>Backtrace</strong></summary>
<p>

```
 ~/git/wawat/cuteness  main !1 ▓▒░ RUST_BACKTRACE=1 cargo doc --open                                                                                                                                          ░▒▓ ✔
   Compiling serde_derive v1.0.158
   Compiling thiserror-impl v1.0.40
   Compiling clap_derive v4.1.12
 Documenting rustix v0.36.11
 Documenting log v0.4.17
 Documenting unicase v2.6.0
 Documenting constant_time_eq v0.2.5
 Documenting strsim v0.10.0
    Checking litrs v0.2.3
 Documenting arrayref v0.3.7
 Documenting termcolor v1.2.0
 Documenting litrs v0.2.3
 Documenting arrayvec v0.7.2
 Documenting regex-syntax v0.6.29
 Documenting emojis v0.5.2
 Documenting pulldown-cmark v0.9.2
    Checking regex v1.7.3
    Checking blake3 v1.3.3
   Compiling document-features v0.2.7
 Documenting blake3 v1.3.3
thread 'rustc' panicked at 'no resolutions for a doc link', compiler/rustc_metadata/src/rmeta/encoder.rs:2251:18
stack backtrace:
    Checking pulldown-cmark v0.9.2
   0: rust_begin_unwind
             at /rustc/1459b3128e288a85fcc4dd1fee7ada2cdcf28794/library/std/src/panicking.rs:579:5
   1: core::panicking::panic_fmt
             at /rustc/1459b3128e288a85fcc4dd1fee7ada2cdcf28794/library/core/src/panicking.rs:64:14
   2: core::panicking::panic_display
             at /rustc/1459b3128e288a85fcc4dd1fee7ada2cdcf28794/library/core/src/panicking.rs:147:5
   3: core::panicking::panic_str
             at /rustc/1459b3128e288a85fcc4dd1fee7ada2cdcf28794/library/core/src/panicking.rs:131:5
   4: core::option::expect_failed
             at /rustc/1459b3128e288a85fcc4dd1fee7ada2cdcf28794/library/core/src/option.rs:2055:5
   5: <rustc_metadata::rmeta::encoder::provide::{closure#0} as core::ops::function::FnOnce<(rustc_middle::ty::context::TyCtxt, rustc_span::def_id::LocalDefId)>>::call_once
   6: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::queries::doc_link_resolutions, rustc_query_impl::plumbing::QueryCtxt>
   7: <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::doc_link_resolutions
   8: <rustdoc::passes::collect_intra_doc_links::LinkCollector>::resolve_path
   9: <rustdoc::passes::collect_intra_doc_links::LinkCollector>::resolve
  10: <rustdoc::passes::collect_intra_doc_links::LinkCollector>::resolve_links
  11: <rustdoc::passes::collect_intra_doc_links::LinkCollector as rustdoc::visit::DocVisitor>::visit_inner_recur
  12: <rustdoc::passes::collect_intra_doc_links::LinkCollector as rustdoc::visit::DocVisitor>::visit_inner_recur
  13: rustdoc::passes::collect_intra_doc_links::collect_intra_doc_links
  14: <rustc_session::session::Session>::time::<rustdoc::clean::types::Crate, rustdoc::core::run_global_ctxt::{closure#7}>
  15: rustdoc::core::run_global_ctxt
  16: <rustc_session::session::Session>::time::<(rustdoc::clean::types::Crate, rustdoc::config::RenderOptions, rustdoc::formats::cache::Cache), rustdoc::main_args::{closure#1}::{closure#0}::{closure#0}::{closure#0}>
  17: <rustc_middle::ty::context::GlobalCtxt>::enter::<rustdoc::main_args::{closure#1}::{closure#0}::{closure#0}, core::result::Result<(), rustc_span::ErrorGuaranteed>>
  18: <rustc_interface::interface::Compiler>::enter::<rustdoc::main_args::{closure#1}::{closure#0}, core::result::Result<(), rustc_span::ErrorGuaranteed>>
  19: rustc_span::with_source_map::<core::result::Result<(), rustc_span::ErrorGuaranteed>, rustc_interface::interface::run_compiler<core::result::Result<(), rustc_span::ErrorGuaranteed>, rustdoc::main_args::{closure#1}>::{closure#0}::{closure#0}>
  20: <scoped_tls::ScopedKey<rustc_span::SessionGlobals>>::set::<rustc_interface::interface::run_compiler<core::result::Result<(), rustc_span::ErrorGuaranteed>, rustdoc::main_args::{closure#1}>::{closure#0}, core::result::Result<(), rustc_span::ErrorGuaranteed>>
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

error: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.70.0-nightly (1459b3128 2023-03-23) running on x86_64-unknown-linux-gnu

note: compiler flags: --crate-type lib

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [doc_link_resolutions] resolutions for documentation links for a module
end of query stack
 Documenting document-features v0.2.7
error: could not document `rustix`

Caused by:
  process didn't exit successfully: `rustdoc --edition=2018 --crate-type lib --crate-name rustix /home/alejandra/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rustix-0.36.11/src/lib.rs --cap-lints allow -o /home/alejandra/git/wawat/cuteness/target/doc --cfg 'feature="default"' --cfg 'feature="io-lifetimes"' --cfg 'feature="libc"' --cfg 'feature="std"' --cfg 'feature="termios"' --cfg 'feature="use-libc-auxv"' --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --diagnostic-width=213 -C metadata=c8bad158e10ac0de -L dependency=/home/alejandra/git/wawat/cuteness/target/debug/deps --extern bitflags=/home/alejandra/git/wawat/cuteness/target/debug/deps/libbitflags-f75283d3dcd3daad.rmeta --extern io_lifetimes=/home/alejandra/git/wawat/cuteness/target/debug/deps/libio_lifetimes-0e896a4daa128e32.rmeta --extern libc=/home/alejandra/git/wawat/cuteness/target/debug/deps/liblibc-8aab922602f2fc15.rmeta --extern linux_raw_sys=/home/alejandra/git/wawat/cuteness/target/debug/deps/liblinux_raw_sys-a31463b73c270e13.rmeta --crate-version 0.36.11 --cfg rustc_attrs --cfg linux_raw --cfg core_intrinsics --cfg asm` (exit status: 101)
warning: build failed, waiting for other jobs to finish...
```

</p>
</details>

### LINKED ISSUE #109631: "cargo doc": error: could not document `rustix` v0.36.11
Experimenting with Rocket and learning Rust. Updating this issue is a work in progress.

fekerr@LAPTOP:~/src/boing001$ cat Cargo.toml
``` text 
[package]
name = "boing001"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# rocket = "0.4.11"
rocket = "0.5.0-rc.3"

```

### Code

```Rust
<code>
fekerr@LAPTOP:~/src/boing001$ cat src/main.rs
// 20230325 fekerr
// main.rs
//
// traitobj crate - issues in future?

// Rocket requires rustc nightly, and these two lines.
#![feature(proc_macro_hygiene, decl_macro)]
#[macro_use] extern crate rocket;

fn main() {
    println!("Hello, world!");
}
```

### Meta

`rustc --version --verbose`:
```
 rustc --version --verbose
rustc 1.70.0-nightly (1459b3128 2023-03-23)
binary: rustc
commit-hash: 1459b3128e288a85fcc4dd1fee7ada2cdcf28794
commit-date: 2023-03-23
host: x86_64-unknown-linux-gnu
release: 1.70.0-nightly
LLVM version: 15.0.7

```

### Error output

```
<output>

cargo doc 2> cargo_doc.txt
[cargo_doc.txt](https://github.com/rust-lang/rust/files/11071785/cargo_doc.txt)


```

<details><summary><strong>Backtrace</strong></summary>
<p>

```

<backtrace>

fekerr@LAPTOP:~/src/boing001$ RUST_BACKTRACE=1 cargo build 2> cargo_build_rbt1.txt
fekerr@LAPTOP:~/src/boing001$ RUST_BACKTRACE=1 cargo build 2> cargo_doc_rbt1.txt
[cargo_build_rbt1.txt](https://github.com/rust-lang/rust/files/11071820/cargo_build_rbt1.txt)
[cargo_doc_rbt1.txt](https://github.com/rust-lang/rust/files/11071821/cargo_doc_rbt1.txt)

```

</p>
</details>

### PR DESCRIPTION
**Pull request by petrochenkov**
This may be potentially useful for
- avoiding uses of `hir::ItemKind::Use` (which usually lead to correctness issues)
- preserving documentation comments on all reexports, including those from other crates
- preserving and checking stability/deprecation info on reexports
- all kinds of diagnostics

The second commit then migrates some hacky logic from rustdoc to `module_reexports` to make it simpler and more correct.
Ideally rustdoc should use `module_reexports` immediately at the top level, so `hir::ItemKind::Use`s are never used.
The second commit also fixes issues with https://github.com/rust-lang/rust/pull/109330 and therefore
Fixes https://github.com/rust-lang/rust/issues/109631
Fixes https://github.com/rust-lang/rust/issues/109614
Fixes https://github.com/rust-lang/rust/issues/109424

### CODE REVIEW

**Comment by petrochenkov** [comment]
cc @GuillaumeGomez

**Comment by petrochenkov** [comment]
The second commit shows some motivation for the first commit, but otherwise they are not related and I can split this PR into two for reviewing by different people if necessary.

**Comment by petrochenkov** [comment]
@notriddle 
>Can you construct a test case that triggers one of these new warnings?

The warnings are not new, they are existing, they are just heavily using `module_children` for traversing the whole crate tree, and `module_children` just got more expensive due to the new field in `ModChild`.

**Review by GuillaumeGomez — APPROVED** [review]

**Comment by GuillaumeGomez** [comment]
Looks good to me but still need approval from someone on the compiler team.

File: compiler/rustc_resolve/src/imports.rs [hunk 1]
```diff
@@ -1252,12 +1265,20 @@ impl<'a, 'tcx> Resolver<'a, 'tcx> {
...
+                        next_binding = binding;
+                    }
+
                     reexports.push(ModChild {
                         ident,
                         res,
                         vis: binding.vis,
                         span: binding.span,
                         macro_rules: false,
+                        reexports: reexport_chain,
```
Comment (oli-obk) [inline compiler/rustc_resolve/src/imports.rs:1281]: maybe name the field `reexport_chain`, while the docs clarify it, the field can just have that name, too

File: src/librustdoc/clean/mod.rs [hunk 2]
```diff
@@ -2066,141 +2067,44 @@ fn clean_bare_fn_ty<'tcx>(
...
-        self.map
-    }
-
-    fn visit_item(&mut self, item: &'hir hir::Item<'hir>) {
-        if self.item.is_none()
-            && item.ident == self.looking_for
-            && (matches!(item.kind, hir::ItemKind::Use(_, _))
-                || item.owner_id.def_id == self.target_def_id)
+) -> &'tcx [Reexport] {
+    for child in tcx.module_reexports(tcx.local_parent(import_def_id)).unwrap_or_default() {
```
Comment (oli-obk) [inline src/librustdoc/clean/mod.rs:2075]: side note: `module_reexports` should probably do the unwrap_or_default inside and not return an `Option<&[T]>`, but that's very orthogonal to this PR

**Review by oli-obk — CHANGES_REQUESTED** [review]

File: compiler/rustc_middle/src/metadata.rs [hunk 3]
```diff
@@ -5,13 +5,32 @@ use rustc_macros::HashStable;
 use rustc_span::def_id::DefId;
 use rustc_span::symbol::Ident;
 use rustc_span::Span;
+use smallvec::SmallVec;
+
+#[derive(Clone, Copy, Debug, TyEncodable, TyDecodable, HashStable)]
+pub enum Reexport {
```
[the remark this answers is not in the document]
Comment (petrochenkov) [reply compiler/rustc_middle/src/metadata.rs:11]: No!
Those are `DefId`s of the `use` and `extern crate` items themselves, not their targets, that's the point.
So we can query attributes, spans, etc of those import items.
I'll add the docs.

**Review by notriddle — APPROVED** [review]

**Review by oli-obk — APPROVED** [review]

**Comment by oli-obk** [comment]
@bors r+ rollup=never

About perf: This regresses a few test cases because there's a bit more rustdoc metadata in our metadata files and that just needs a bit more time to decode. These changes are needed to fix ICEs in rustdoc, which is why I'm landing it tregardless of the perf regressions. We should evaluate how to avoid regressions from rustdoc-specific metadata in general and not on an individual PR basis.

**Comment by rylev** [comment]
There are a few more regressions in the post merge perf run, but they seem to follow the same pattern as the regressions found pre-merge. I think we can just take this as a necessary trade off we need to make for the fixes that landed (as identified by @oli-obk [here](https://github.com/rust-lang/rust/pull/109500#issuecomment-1501119286)).

**Comment by petrochenkov** [comment]
These perf regressions were partially mitigated by https://github.com/rust-lang/rust/pull/109772.
