### PR TITLE
Make SIGSEGV handler emit nicer backtraces

### LINKED ISSUE #102248: rustc segfault (on ridiculous unlikely code)
rustc seems to segfault on my machine with this code. It's admittedly very ridiculous, so maybe this is a complete non-issue, but I'd expect it to pop up anything fancier than a raw unclear spam of what looks like a stack trace and then segfaulting.

The code and the compiler outputs are too large for GitHub's issue body 65536 character limit, so here it is as a gist: https://gist.github.com/Architector4/a862e017ac291649e9911652c28336f9#file-unitblock-rs

The code has unnecessary `println!` statements, but they don't seem to affect the error.

Effectively, this code can be reproduced by taking this line: `{X}()` and recursively putting it into itself at X a few thousand times, at some point replacing it with nothing instead.

# Version

Checked with both stable and nightly versions.

rustc stable version (from `rustup` on Arch Linux):
```
$ rustc --version --verbose
rustc 1.64.0 (a55dd71d5 2022-09-19)
binary: rustc
commit-hash: a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52
commit-date: 2022-09-19
host: x86_64-unknown-linux-gnu
release: 1.64.0
LLVM version: 14.0.6
```

rustc nightly version (from `rustup` on Arch Linux):
```
$ rustc --version --verbose
rustc 1.66.0-nightly (4a1467723 2022-09-23)
binary: rustc
commit-hash: 4a14677239bbd9a3892d165ee24513c1a05820e4
commit-date: 2022-09-23
host: x86_64-unknown-linux-gnu
release: 1.66.0-nightly
LLVM version: 15.0.0
```

# Output

Stable compiler output: https://gist.github.com/Architector4/a862e017ac291649e9911652c28336f9#file-rustc-stable-crash-log

Nightly compiler output: https://gist.github.com/Architector4/a862e017ac291649e9911652c28336f9#file-rustc-nightly-crash-log

There does not appear to be any change in the output from setting `RUST_BACKTRACE=1` in environment.

### LINKED ISSUE #109648: Excessively chaining operators causes a stack overflow in rustc
Excessive (_extremely excessive_) chaining of operators causes a stack overflow in rustc. In my experimenting I found that this happens with precisely 6115 chained operators in the playground, but it appears to depend on your compilation environment as it took approx. 8000 on my machine. This is easily avoided by splitting the chain (or having an iota of sanity), but I would expect `rustc` to at least exit gracefully in this case. The code below uses only the Not (`!`) operator, but at least the Neg (`-`) operator also works, as does mixing the two (ie `-!-!-!`).

[Playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=4dcf0beb31d3d8100a81e15d37813736)

<details><summary>Code</summary>

```rust
fn main() {
    // 6115 chained operators. This should crash the playground. If you remove
    // one or more of the `!`s, it should compile.
    let _ = 
    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!true;
}
```

</details>

<details><summary>Local (Windows) Error Message</summary>

```
PS C:\usr\Programming\atira-bevy> cargo run -p bugtest
   Compiling bugtest v0.1.0 (C:\usr\Programming\atira-bevy\apps\bugtest)

thread 'rustc' has overflowed its stack
error: could not compile `bugtest`

Caused by:
  process didn't exit successfully: `rustc --crate-name bugtest --edition=2021 apps\bugtest\src\main.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --diagnostic-width=278 --crate-type bin --emit=dep-info,link -C embed-bitcode=no -C debuginfo=2 -C metadata=62598a30bcc4eedd --out-dir C:\usr\Programming\atira-bevy\target\debug\deps -C incremental=C:\usr\Programming\atira-bevy\target\debug\incremental -L dependency=C:\usr\Programming\atira-bevy\target\debug\deps` (exit code: 0xc00000fd, STATUS_STACK_OVERFLOW)
```
</details>

The playground error message was too long to include here, but a copy can be found in this gist: https://gist.github.com/grind086/703b519f8ff02f32b164d9388abed59b

### Meta

The above code was tested in the playground (Debug, Stable, v1.68.1), and a version with 8000 chained operators crashed `rustc` on my local machine with the following `rustc --version --verbose`:

```
rustc 1.67.1 (d5a82bbd2 2023-02-07)
binary: rustc
commit-hash: d5a82bbd26e1ad8b7401f6a718a9c57c96905483
commit-date: 2023-02-07
host: x86_64-pc-windows-msvc
release: 1.67.1
LLVM version: 15.0.6
```

### PR DESCRIPTION
**Pull request by workingjubilee**
This annotates the code heavily with comments to explain what is going on, for the benefit of other compiler contributors. The backtrace also emits appropriate comments to clarify, to a programmer who may not know why a bunch of file paths and hexadecimal blather was just dumped into stderr, what is going on. Finally, it detects cycles and uses their regularity to avoid repeating a bunch of text. The previous backtraces we were emitting was extremely unfriendly, potentially confusing, and often alarming, and this makes things almost "nice".

We can't necessarily make them much nicer than this, because a signal handler must use "signal-safe" functions. This precludes conveniences like dynamic allocations. Fortunately, Rust's stdlib has allocation-free formatting, but it may hinder integrating this error with our localization middleware, as I wasn't able to clearly ascertain, at a glance, whether there was a zero-alloc path through it.

r? @Nilstrieb

### CODE REVIEW

**Comment by workingjubilee** [comment]
Ah.
```rust
impl<'args> TranslateError<'args> {
    // some code
    // then...
    pub fn fluent(
        id: &'args Cow<'args, str>,
        args: &'args FluentArgs<'args>,
        errs: Vec<FluentError>,
    ) -> Self {
```

I looked into it. The answer is it should almost certainly not be without changes to the Fluent API surface, which uses Vecs and the like. We do not want to touch those while inside a signal handler. Allocating or deallocating anything is forbidden. We probably don't want to even think about Boxes. ( Sorry Boxy. )

File: compiler/rustc_driver_impl/src/lib.rs [hunk 1]
```diff
@@ -1439,17 +1439,32 @@ mod signal_handler {
 
     extern "C" fn print_stack_trace(_: libc::c_int) {
```
Comment (Nilstrieb) [inline compiler/rustc_driver_impl/src/lib.rs:1440]: can we move this module into separate files?

File: compiler/rustc_driver_impl/src/lib.rs [hunk 2]
```diff
@@ -1439,17 +1439,32 @@ mod signal_handler {
...
+            // Collect return addresses
             let depth = libc::backtrace(STACK_TRACE.as_mut_ptr(), MAX_FRAMES as i32);
             if depth == 0 {
                 return;
             }
-            backtrace_symbols_fd(STACK_TRACE.as_ptr(), depth, 2);
+            // Just a stack trace is cryptic. Explain what we're doing.
+            write_raw_err("error: rustc interrupted by SIGSEGV, printing stack trace:\n\n");
+            // Elaborate return addrs into symbols and write them directly to stderr
+            backtrace_symbols_fd(STACK_TRACE.as_ptr(), depth, libc::STDERR_FILENO);
```
Comment (Nilstrieb) [inline compiler/rustc_driver_impl/src/lib.rs:1454]: can we print a message here reminding people that this could be a stackoverflow and there's a backtrace above? you don't immediately see the message above and when you see "oh no rustc segfaulted what the hell went wrong??" you're immediately assured by "don't worry it's probably just a stackoverflow". Rust users (like me) are not used to segfaults from stackoverflows (thanks, std^^).

**Review by Noratrieb — COMMENTED** [review]
thanks, that already looks better

File: compiler/rustc_driver_impl/src/lib.rs (hunk 1 above)
Comment (workingjubilee) [reply compiler/rustc_driver_impl/src/lib.rs]: Done~

**Comment by workingjubilee** [comment]
The tail of the error now looks like:
```

error: stack trace dumped due to SIGSEGV, possible stack overflow
error: please report a bug to https://github.com/rust-lang/rust
Segmentation fault (core dumped)
```

**Comment by workingjubilee** [comment]
New output now looks like... no trimming, this was previously a large backtrace that maxed out the 256 frames via stack overflow:

```
$ ./build/x86_64-unknown-linux-gnu/stage1/bin/rustc overflowy.rs
error: rustc interrupted by SIGSEGV, printing backtrace

./build/x86_64-unknown-linux-gnu/stage1/bin/../lib/librustc_driver-edec4982b354a535.so(+0x8ca553)[0x7f394028a553]
/usr/lib/libc.so.6(+0x39ab0)[0x7f393f628ab0]
./build/x86_64-unknown-linux-gnu/stage1/bin/../lib/librustc_driver-edec4982b354a535.so(+0x24db98a)[0x7f3941e9b98a]

### cycle encountered after 3 frames with period 5
./build/x86_64-unknown-linux-gnu/stage1/bin/../lib/librustc_driver-edec4982b354a535.so(+0x24d4663)[0x7f3941e94663]
./build/x86_64-unknown-linux-gnu/stage1/bin/../lib/librustc_driver-edec4982b354a535.so(+0x251c8ae)[0x7f3941edc8ae]
./build/x86_64-unknown-linux-gnu/stage1/bin/../lib/librustc_driver-edec4982b354a535.so(+0x251ccd8)[0x7f3941edccd8]
./build/x86_64-unknown-linux-gnu/stage1/bin/../lib/librustc_driver-edec4982b354a535.so(+0x251cda3)[0x7f3941edcda3]
./build/x86_64-unknown-linux-gnu/stage1/bin/../lib/librustc_driver-edec4982b354a535.so(+0x24db9a4)[0x7f3941e9b9a4]
### recursed 50 times

./build/x86_64-unknown-linux-gnu/stage1/bin/../lib/librustc_driver-edec4982b354a535.so(+0x24d4663)[0x7f3941e94663]
./build/x86_64-unknown-linux-gnu/stage1/bin/../lib/librustc_driver-edec4982b354a535.so(+0x251c8ae)[0x7f3941edc8ae]
./build/x86_64-unknown-linux-gnu/stage1/bin/../lib/librustc_driver-edec4982b354a535.so(+0x251ccd8)[0x7f3941edccd8]

note: rustc unexpectedly overflowed its stack! this is a bug
note: maximum backtrace depth reached, frames may have been lost
note: we would appreciate a report at https://github.com/rust-lang/rust
Segmentation fault (core dumped)
```

File: compiler/rustc_driver_impl/src/signal_handler.rs [hunk 3]
```diff
@@ -0,0 +1,143 @@
...
+        let mut alt_stack: libc::stack_t = mem::zeroed();
+        alt_stack.ss_sp = alloc(Layout::from_size_align(alt_stack_size, 1).unwrap()).cast();
+        alt_stack.ss_size = alt_stack_size;
+        libc::sigaltstack(&alt_stack, ptr::null_mut());
+
+        let mut sa: libc::sigaction = mem::zeroed();
+        sa.sa_sigaction = print_stack_trace as libc::sighandler_t;
+        sa.sa_flags = libc::SA_NODEFER | libc::SA_RESETHAND | libc::SA_ONSTACK;
+        libc::sigemptyset(&mut sa.sa_mask);
+        libc::sigaction(libc::SIGSEGV, &sa, ptr::null_mut());
```
Comment (thomcc) [inline compiler/rustc_driver_impl/src/signal_handler.rs:124]: We should probably backtrace on SIGBUS too, since wild pointers can trigger sigbus just as easily (okay, maybe not *just* as easily, but, easily).

File: compiler/rustc_driver_impl/src/signal_handler.rs [hunk 4]
```diff
@@ -0,0 +1,143 @@
...
+    if written > 24 {
+        // We probably just scrolled the earlier "we got SIGSEGV" message off the terminal
+        raw_errln!("note: backtrace dumped due to SIGSEGV! resuming signal");
+    };
+}
+
+/// When SIGSEGV is delivered to the process, print a stack trace and then exit.
+pub(super) fn install() {
+    unsafe {
+        let alt_stack_size: usize = min_sigstack_size() + 64 * 1024;
```
Comment (thomcc) [inline compiler/rustc_driver_impl/src/signal_handler.rs:114]: Is 64k still definitely enough stack space for this more complicated handler to run in?

Comment (workingjubilee) [reply compiler/rustc_driver_impl/src/signal_handler.rs:114]: So far on my machine yes, but then again my machine is probably answering `getauxval(AT_MINSIGSTKSZ)` with a nonzero value.

**Comment by thomcc** [comment]
We should also consider having an env var[^1] or something you can set to symbolicate that output with `backtrace_symbols`, since it's often enough fine.

(Note that we should just leak the result of `backtrace_symbols` though -- technically you can free it with `free` but this crashes a shocking amount of the time, expecially if you're using an overridden malloc impl)

[^1]: Ofc, we should read it when installing the handler, not inside the handler.

File: compiler/rustc_driver_impl/src/signal_handler.rs (hunk 3 above)
Comment (workingjubilee) [reply compiler/rustc_driver_impl/src/signal_handler.rs:124]: I was going to look into what sort of signals we wanted to extend to after, since what I really started digging into the signal handler for is to set up a SIGILL handler for when ~~the compiler needs a hot pad and some soup~~ LLVM, running in our process space, runs into one of its `llvm_unreachable`s that on x86-64, thanks to the CMake options we build LLVM with, are compiled into `ud2` instead of UB (because they're `@llvm.trap()`).

**Comment by workingjubilee** [comment]
I was thinking about making that the `RUST_BACKTRACE=full` behavior.

File: compiler/rustc_driver_impl/src/signal_handler.rs (hunk 4 above)
Comment (workingjubilee) [reply compiler/rustc_driver_impl/src/signal_handler.rs:112]: This was a good question to ask because I found a spot where a small change removes an entire panic branch.

File: compiler/rustc_driver_impl/src/signal_handler.rs [hunk 5]
```diff
@@ -0,0 +1,141 @@
...
+            consumed += period * cycles;
+            cyclic = true;
+        };
+    }
+    let rem = &stack[consumed..];
+    backtrace_stderr(rem);
+    raw_errln!("");
+    written += rem.len() + 1;
+
+    if cyclic || stack.len() == 256 {
```
Comment (erikdesjardins) [inline compiler/rustc_driver_impl/src/signal_handler.rs:90]:
```suggestion
    if cyclic || stack.len() == MAX_FRAMES {
```

File: compiler/rustc_driver_impl/src/signal_handler.rs [hunk 6]
```diff
@@ -0,0 +1,141 @@
...
+        // technically speculation, but assert it with confidence anyway.
+        // rustc only arrived in this signal handler because bad things happened
+        // and this message is for explaining it's not the programmer's fault
+        raw_errln!("note: rustc unexpectedly overflowed its stack! this is a bug");
+        written += 1;
+    }
+    if stack.len() == 256 {
```
Comment (erikdesjardins) [inline compiler/rustc_driver_impl/src/signal_handler.rs:97]:
```suggestion
    if stack.len() == MAX_FRAMES {
```

File: compiler/rustc_driver_impl/src/signal_handler.rs (hunk 5 above)
Comment (workingjubilee) [reply compiler/rustc_driver_impl/src/signal_handler.rs:90]: This one isn't actually related, it's a genuinely arbitrary number.

File: compiler/rustc_driver_impl/src/signal_handler.rs (hunk 6 above)
Comment (workingjubilee) [reply compiler/rustc_driver_impl/src/signal_handler.rs:97]: This one is, sure.

**Comment by workingjubilee** [comment]
I'm sorry?

**Comment by workingjubilee** [comment]
Oh, HEAD is fucked again.

**Comment by workingjubilee** [comment]
Nils is /afk
r? compiler

**Comment by workingjubilee** [comment]
orz
r? compiler

File: compiler/rustc_driver_impl/src/signal_handler.rs [hunk 7]
```diff
@@ -2,43 +2,108 @@
...
+    };
+
+    // Just a stack trace is cryptic. Explain what we're doing.
+    raw_errln!("error: rustc interrupted by SIGSEGV, printing backtrace\n");
+    let mut written = 1;
+    let mut consumed = 0;
+    // Begin elaborating return addrs into symbols and writing them directly to stderr
+    // Most backtraces are stack overflow, most stack overflows are from recursion
+    // Check for cycles before writing 250 lines of the same ~5 symbols
+    let cycled = |(runner, walker)| runner == walker;
```
Comment (pnkfelix) [inline compiler/rustc_driver_impl/src/signal_handler.rs:57]: This is interesting... I'm trying to decide whether there's any world where the "normal" stack backtrace mechanism could benefit from an attempt to compress its presentation in the same manner that you are doing here. (e.g. if code is tracking a depth counter or some other exhaustion-prevention mechanism, and then panicking explicitly rather than allowing the stack to actually overflow...)

But I suspect that this code belongs here and only here because in vast majority of cases, that kind of unrestricted recursion is going to end with a SIGSEGV and handled here.

File: compiler/rustc_driver_impl/src/signal_handler.rs [hunk 8]
```diff
@@ -2,43 +2,108 @@
...
+    let mut cyclic = false;
+    if let Some(period) = stack.iter().skip(1).step_by(2).zip(stack).position(cycled) {
+        let period = period.saturating_add(1); // avoid "what if wrapped?" branches
+        let Some(offset) = stack.iter().skip(period).zip(stack).position(cycled) else {
+            // impossible.
+            return;
+        };
+
```
Comment (pnkfelix) [inline compiler/rustc_driver_impl/src/signal_handler.rs:65]: the code inside here might benefit from an ascii-art diagram or something.

My main concern is that even though I have passing familiarity with [Floyd's tortoise and hare algorithm](https://en.wikipedia.org/wiki/Cycle_detection#Floyd's_tortoise_and_hare), I nonetheless cannot immediate tell whether you are e.g. reporting the *minimal* period λ, or if you are only guaranteeing that you are reporting *some* period ν that is a multiple of λ. (See the linked wikipedia page for where those greek letter cames from.)

... or better still: Would it make any sense to factor this out into its own generic routine that can have concrete unit tests, and then instantiate it here?

... anyway, on the other hand, this code has waited long enough to land, and it certainly looks like an improvement. Further improvements like what I am suggesting here can be follow-on PR's.

File: compiler/rustc_driver_impl/src/signal_handler.rs [hunk 9]
```diff
@@ -87,14 +87,15 @@ extern "C" fn print_stack_trace(_: libc::c_int) {
     raw_errln!("");
     written += rem.len() + 1;
 
-    if cyclic || stack.len() == 256 {
+    let random_depth = || 8 * 16; // chosen by random diceroll (2d20)
```
Comment (pnkfelix) [inline compiler/rustc_driver_impl/src/signal_handler.rs:90]: (... I don't understand why this is a closure versus just a let-bound usize.)

File: compiler/rustc_driver_impl/src/signal_handler.rs (hunk 8 above)
Comment (workingjubilee) [reply compiler/rustc_driver_impl/src/signal_handler.rs:65]: Sure! I want rustc to have a SIGILL handler as well, so I'm definitely going to be doing some followups here and imposing better factorization. It just seemed premature to do anything like that.

File: compiler/rustc_driver_impl/src/signal_handler.rs (hunk 7 above)
Comment (workingjubilee) [reply compiler/rustc_driver_impl/src/signal_handler.rs:57]: I think we could lift cycle-detection algorithms up into other parts of rustc, since in many cases we run afoul of essentially unbounded recursion, but it's probably not the case that this one is sufficiently general yet to be used thusly.
