### PR TITLE
Fix a typo in `test/ui/hrtb/hrtb-just-for-static.rs`

### LINKED ISSUE #97934: typo in `src/test/ui/hrtb/hrtb-just-for-static.rs`
```
// AnyInt implements Foo<&'a isize> for any 'a, so it is a match.   <- HERE, should not be AnyInt
impl<'a> Foo<&'a isize> for &'a u32 { }
fn give_some<'a>() {
    want_hrtb::<&'a u32>()
    //~^ ERROR lifetime may not live long enough
    //~| ERROR implementation of `Foo` is not general enough
}

```

### PR DESCRIPTION
**Pull request by TaKO8Ki**
closes #97934

### CODE REVIEW

File: src/test/ui/hrtb/hrtb-just-for-static.rs [hunk 1]
```diff
@@ -28,7 +28,7 @@ fn give_static() {
     want_hrtb::<StaticInt>() //~ ERROR
 }
 
-// AnyInt implements Foo<&'a isize> for any 'a, so it is a match.
+// &'a u32 implements Foo<&'a isize> for any 'a, so it is a match.
```
Comment (eggyal) [inline src/test/ui/hrtb/hrtb-just-for-static.rs:31]: `&'a u32` only implements `Foo<&'a isize>` for *specific `'a`*, so it is **an error**.

**Review by eggyal — CHANGES_REQUESTED** [review]
