### PR TITLE
Ship MinGW-w64 runtime DLLs along with `rust-lld.exe` for `-pc-windows-gnu` targets

### LINKED ISSUE #125809: rust stable 1.78 using 'x86_64-pc-windows-gnu' host tool to build 'thumbv7em-none-eabihf' arm bare metal target got rust-lld failed
Failed reason is can't find 'libgcc_s_seh-1.dll' and 'libwinpthread-1.dll'
when fallback to 1.77.2 or using 'x86_64-pc-windows-msvc' host tool then every thing is ok

### PR DESCRIPTION
**Pull request by ColinFinck**
`rust-lld.exe` built for `x86_64-pc-windows-gnu` depends on `libgcc_s_seh-1.dll` and `libwinpthread-1.dll` from MinGW-w64. Until now, they were not shipped alongside `rust-lld.exe`, and you could not run `rust-lld.exe` on most systems.

This problem didn't surface until now because:
* Most targets don't use `rust-lld` by default.
* Some people had these DLLs in their `PATH` from some other MinGW binary.
* `rustup` used to add `bin` to the `PATH`, which contains these DLLs for `rustc.exe`. But it no longer does that: https://github.com/rust-lang/rustup/commit/ce3c09a0cb126e2c65a3bb2a3bbf3f098b4c23a2

Fixes #125809

try-job: dist-x86_64-mingw

### CODE REVIEW

**Review by Kobzol — COMMENTED** [review]
Bootstrap-wise, these changes look OK, but I don't know a lot about windows-gnu and don't have Windows prepared for testing this.

@jieyouxu could you please try to check it on Windows?

**Comment by ChrisDenton** [comment]
cc @mati865

**Comment by jieyouxu** [comment]
> @jieyouxu could you please try to check it on Windows?

I can try a bit later, but no guarantees to reproduce ci environment

**Comment by jieyouxu** [comment]
@Kobzol wait what am I supposed to be testing here?

**Comment by Kobzol** [comment]
I suppose that the goal is to check whether LLD can be used on windows-gnu if you also meet all the requirements described in this PR's description :sweat_smile: @ColinFinck Could you describe some reproduction guide to make it easier to test whether this works as intended on Windows?

**Comment by jieyouxu** [comment]
Oh in particular, am I supposed to try reproduce the failure outside of msys2 msys? Because if I try to run the `cortex-m-example` with suitable cross-compile targets added, I can't reproduce the missing dll failure presumably because msys2. I'll need some more guidance on what environment outside of msys2 I would try to reproduce the failure with.

**Comment by jieyouxu** [comment]
Oh apparently those dlls *are* somehow available through my `PATH`s. If I set

```
$env:PATH = "C:\Users\Administrator\.cargo\bin"
```

then the build fails with

```
error: linking with `rust-lld` failed: exit code: 0xc0000135
```

weirdly the `note:` is empty.

**Comment by jieyouxu** [comment]
Yeah I need a bit of help here for testing steps, what's the minimal build I can use to test it? As in, do I have to do the full `./x dist`?

**Comment by ColinFinck** [comment]
@Kobzol @jieyouxu To reproduce the problem for the current Rust 1.80.0 release, follow these steps on a Windows Command Prompt (`cmd`):

```
rustup default 1.80.0-x86_64-pc-windows-gnu
set PATH=%USERPROFILE%\.cargo\bin

cargo new testproject
cd testproject
set RUSTFLAGS=-Clinker=rust-lld
cargo build
```

This will show a message box about a DLL not being found, followed by a `linking with rust-lld failed: exit code: 0xc0000135` error on the command line.
`set PATH` is important here to ensure that only Rust-provided DLLs are tried.

My PR fixes this by putting the missing DLLs into the right place.

**Comment by jieyouxu** [comment]
Discussed with @ColinFinck on zulip, to test locally I needed to:

```
# config.toml
[rust]
lld = true
use-lld = false

[build]
build = "x86_64-pc-windows-gnu"
host = ["x86_64-pc-windows-gnu"]
```

then

```
./x dist
```

to actually produce the rust-lld executable as part of a very late dist step. Then I would need to `rustup toolchain link stage1 build/host/stage1` to alias a `stage1` toolchain. Then in CMD:

```
set PATH = %USERPROFILE%\.cargo\bin
cargo +stage1 new testproject
cd testproject
set RUSTFLAGS=-Clinker=rust-lld
cargo +stage1 build
```

(Note: still trying to test atm)

**Comment by ColinFinck** [comment]
@mati865 Could you possibly have a look?
Thank you in advance!

**Comment by jieyouxu** [comment]
@rustbot ping windows

Dear Windows experts, is anyone able to try to build a `windows-gnu` toolchain locally with these https://github.com/rust-lang/rust/pull/128876#issuecomment-2286079065 reproduction steps, and double check if the produced `rust-lld` can now be successfully run with a very restricted `PATH` to make sure the libraries aren't available elsewhere?

**Comment by jieyouxu** [comment]
@Kobzol the reproduction steps around `./x dist` is a bit wonky, I wasn't able to follow through all of it, are there any docs on how to produce a full toolchain (that includes rust-lld)?

**Comment by Kobzol** [comment]
I think that it should be enough to configure `[rust] lld = true` in `config.toml` and then do `./x dist`.

**Comment by ChrisDenton** [comment]
Can't we do a try build of dust in CI then people could just download the artefacts (via [`rustup-toolchain-install-master](https://github.com/kennytm/rustup-toolchain-install-master))?

**Comment by mati865** [comment]
Sorry for being M.I.A. for so long. Had a crazy week and couldn't allocate any free time to OSS.
I can do a build tomorrow or Wednesday, but I do agree with Chris. Running CI dist build and testing the artifacts would be quickest and simplest.

**Comment by petrochenkov** [comment]
So now we have
- 3 copies of `libwinpthread-1.dll` - for `rustc.exe`, for self-contained `rust-lld.exe`, and for self-contained `ld.exe`
- 2 copies of `libgcc_s_*-1.dll` for `rustc.exe`, and for self-contained `rust-lld.exe`

Apparently `ld.exe` doesn't need `libgcc_s_*-1.dll` for some reason.
Or maybe it does but we never noticed it before https://github.com/rust-lang/rustup/commit/ce3c09a0cb126e2c65a3bb2a3bbf3f098b4c23a2, it would be good to check.

This should be fine, `libwinpthread-1.dll` in only  52KB, and `libgcc_s_seh-1.dll` is 97KB, we shouldn't bother setting `PATH`s to save a copy (I'm not sure if they are actually shipped as hardlinks or not).

When fine-grained `-Clink-self` contained is fully implemented this will decrease to 2 copies (1 for rustc, and 1 for self-contained linkers) because the linkers will live in the same directory inside `bin/self-contained`.

File: src/bootstrap/src/core/build_steps/dist.rs [hunk 1]
```diff
@@ -268,34 +268,45 @@ fn make_win_dist(
     let target_libs = find_files(&target_libs, &lib_path);
 
     // Copy runtime dlls next to rustc.exe
-    let dist_bin_dir = rust_root.join("bin/");
```
Comment (petrochenkov) [inline src/bootstrap/src/core/build_steps/dist.rs:271]: I'm not sure the renamings are improvements (besides adding the missing `self_contained`s).

**Comment by petrochenkov** [comment]
r=me after testing what you wanted to test.
@rustbot author

File: src/bootstrap/src/core/build_steps/dist.rs (hunk 1 above)
Comment (ColinFinck) [reply src/bootstrap/src/core/build_steps/dist.rs:271]: I wanted to prefix paths derived from `rust_root` with `rust_`, and paths derived from `plat_root` with `plat_`.

I mixed up both on my first attempt and I wanted to make sure that this doesn't happen again, hence the renames.

**Comment by ChrisDenton** [comment]
I'll do a try build so people can download the artefact if they like. Once done it can be installed using [`rustup-toolchain-install-master`](https://github.com/kennytm/rustup-toolchain-install-master)

@bors try

**Comment by ChrisDenton** [comment]
Ok, so if anyone wants to try this then they can install it locally using:

```
cargo install rustup-toolchain-install-master
rustup-toolchain-install-master 7f116c7f3b8cb1aebb226f1a978e9ebb2fda04a5 -i x86_64-pc-windows-gnu -c cargo
```

**Comment by mati865** [comment]
> Apparently `ld.exe` doesn't need `libgcc_s_*-1.dll` for some reason.

It's written in C, so it doesn't pull in libstdc++. LLVM (and therefore LLD) built by Rust has statically linked libstdc++.

**Comment by jieyouxu** [comment]
> My PR fixes this by putting the missing DLLs into the right place.

@ColinFinck just to confirm, it should look like this right (using the CI-built toolchain because I cannot for the life of me figure out how to build the windows-gnu toolchain locally)? Since AFAICT this means `lld` *itself* is okay.

```
  = note: lld: error: unable to find library -lkernel32␍
          lld: error: unable to find library -lkernel32␍
          lld: error: unable to find library -ladvapi32␍
          lld: error: unable to find library -lntdll␍
          lld: error: unable to find library -luserenv␍
          lld: error: unable to find library -lws2_32␍
          lld: error: unable to find library -lgcc_eh␍
          lld: error: unable to find library -l:libpthread.a␍
          lld: error: unable to find library -lmsvcrt␍
          lld: error: unable to find library -lmingwex␍
          lld: error: unable to find library -lmingw32␍
          lld: error: unable to find library -lgcc␍
          lld: error: unable to find library -lmsvcrt␍
          lld: error: unable to find library -lmingwex␍
          lld: error: unable to find library -luser32␍
          lld: error: unable to find library -lkernel32␍
```

**Comment by ChrisDenton** [comment]
I think I missed some needed components from my install instructions. I've updated them. You may need to also use `--force` to reinstall.

**Comment by jieyouxu** [comment]
> I think I missed some needed components from my install instructions. I've [updated them](https://github.com/rust-lang/rust/pull/128876?notification_referrer_id=NT_kwDOAEQNYrMxMTg4MTk0MjQxNTo0NDU5ODc0#issuecomment-2299747708). You may need to also use `--force` to reinstall.

I can confirm whatever the CI built Works On My Machine:tm:. So this LGTM (insofar as whatever the CI built is what the end users get)!

**Comment by jieyouxu** [comment]
Feel free to also r=me, but this will need a rebase when I tried to build this PR locally.

**Review by jieyouxu — APPROVED** [review]

**Comment by jieyouxu** [comment]
AFAICT this is good to go, therefore:

@bors r=Kobzol,petrochenkov,jieyouxu

**Comment by jieyouxu** [comment]
May the machine gods bless `windows-gnu` and may this target be free from bugs 🙏

**Review by petrochenkov — APPROVED** [review]

**Comment by mati865** [comment]
> May the machine gods bless `windows-gnu` and may this target be free from bugs 🙏

Sorry, could not resist: https://youtu.be/EIWHvPP0U64?si=ZpitnEb2lNjQSSJ9
