### PR TITLE
Better closure requirement propagation.

### LINKED ISSUE #104477: overly restrictive closure borrow-checking
Both of these test cases should pass borrowck: https://play.rust-lang.org/?version=nightly&mode=debug&edition=2015&gist=50a263a9626cb0b08f5cee334df8a852
```rust
mod case1 {
    struct MyTy<'x, 'a, 'b>(std::cell::Cell<(&'x &'a u8, &'x &'b u8)>);
    fn wf<T>(_: T) {}
    fn test<'a, 'b>() {
        |_: &'a u8, x: MyTy<'_, 'a, 'b>| wf(x); // FAIL!
        |x: MyTy<'_, 'a, 'b>, _: &'a u8| wf(x); // PASS!!!
    }
}

mod case2 {
    struct MyTy<'a, 'b, 'x>(std::cell::Cell<(&'a &'x u8, &'b &'x u8)>);
    fn wf<T>(_: T) {}
    fn test<'a, 'b>() {
        |x: MyTy<'a, 'b, '_>| wf(x); // FAIL!
    }
}
```

They both fail because of the unnecessarily restrictive algorithm in [try_propagate_universal_region_error](https://github.com/rust-lang/rust/blob/79146baa9c7e00b716cc41f8660a56cd2acdf8bd/compiler/rustc_borrowck/src/region_infer/mod.rs#L1629):

- `case1` fails because `'_` has multiple "non-local **upper** bounds" `['a, 'b]` and we do propagate the error to **both** of them while choosing a single one would be sufficient.
- `case2` fails because `'_` has multiple "non-local **lower** bounds" `['a, 'b]` and the call to [non_lcal_lower_bound](https://github.com/rust-lang/rust/blob/79146baa9c7e00b716cc41f8660a56cd2acdf8bd/compiler/rustc_borrowck/src/region_infer/mod.rs#L1639) simply returns `None` in this case!

@rustbot label C-bug T-types A-NLL NLL-complete A-borrow-checker

### LINKED ISSUE #148289: unnecessary closure constraint propagation
```rust
#[derive(Clone, Copy)]
struct Inv<'a>(*mut &'a ());
impl<'a> Inv<'a> {
    fn outlived_by<'b: 'a>(self, _: Inv<'b>) {}
}
struct OutlivedBy<'a, 'b: 'a>(Inv<'a>, Inv<'b>);
fn closure_arg<'b, 'c, 'd>(_: impl for<'a> FnOnce(Inv<'a>, OutlivedBy<'a, 'b>, OutlivedBy<'a, 'c>, Inv<'d>)) {}
fn foo<'b, 'c, 'd: 'b>() {
    closure_arg::<'b, 'c, 'd>(|a, b, c, d| {
        a.outlived_by(b.1);
        a.outlived_by(c.1);
        b.1.outlived_by(d);
    });
}
```
should compile but results in the following error
```rust
error: lifetime may not live long enough
  --> src/main.rs:9:5
   |
 8 |   fn foo<'b, 'c, 'd: 'b>() {
   |              --  -- lifetime `'d` defined here
   |              |
   |              lifetime `'c` defined here
 9 | /     closure_arg::<'b, 'c, 'd>(|a, b, c, d| {
10 | |         a.outlived_by(b.1);
11 | |         a.outlived_by(c.1);
12 | |         b.1.outlived_by(d);
13 | |     });
   | |______^ argument requires that `'d` must outlive `'c`
   |
   = help: consider adding the following bound: `'d: 'c`
   = note: requirement occurs because of the type `Inv<'_>`, which makes the generic argument `'_` invariant
   = note: the struct `Inv<'a>` is invariant over the parameter `'a`
   = help: see <https://doc.rust-lang.org/nomicon/subtyping.html> for more information about variance
```

What's going on is that the closure has the signature `for<'a> fn(Inv<'a>, OutlivedBy<'a, 'b>, OutlivedBy<'a, 'c>, Inv<'d>)` where `'b`, `'c`, and `'d` are external regions.

We have assumptions `'b: 'a` and `'c: 'a`.

Borrow checking the closure results in requirements `'b: 'a`, `'c: 'a`, `'d: 'b`.

https://github.com/rust-lang/rust/blob/72fe2ffb391f397efdfafb2216028ed9952e8078/compiler/rustc_borrowck/src/region_infer/mod.rs#L1222-L1227

`fn check_universal_region` then checks for every universal region in the closure, whether it *transitively* outlives any other regions. We check `'b: 'a`, `'c: 'a`, `'d: 'b` AND `'d: 'a` (transitive)

`'b: 'a` and `'c: 'a` are implied by our assumptions. We can propagate `'d: 'b` to the parent without issues.

Propagating `'d: 'a` is scuffed. Figuring out how to propagate this looks at upper bounds on `'a`: `'b` and `'c` and simply requires `'d` to outlive both. This is unnecessary and results in the incorrect outlives error in the parent.

### PR DESCRIPTION
**Pull request by LorrensP-2158466**
Fixes rust-lang/rust#148289
Fixes rust-lang/rust#104477
Should unblock rust-lang/rust#148187

When propagating closure requirements we:
- no longer try to find a post dominiting region for the list of non-local lower bounds of `longer_fr`.
- we filter the list of `longer_fr-: shorter_fr+` to only these constraints between external regions which are required regardless. If no such constraint exists, we fall back to propagating all of them.

See the [FCP](https://github.com/rust-lang/rust/pull/148329#issuecomment-3581019253) for more information.

r? @lcnr

### CODE REVIEW

File: compiler/rustc_borrowck/src/region_infer/mod.rs [hunk 1]
```diff
@@ -1290,17 +1290,44 @@ impl<'tcx> RegionInferenceContext<'tcx> {
...
+                // a --> b --> d
+                //  \
+                //   \-> c
+                // Here `shorter_fr_plusses` == `['b, 'c]`.
+                // Propagating `'d: 'b` is correct and should happen; `'d: 'c` is redundant and can reject valid code.
+                // We can come closer to this "optimal subset" by checking if the `shorter_fr+` should be outlived by `fr-`.
+                // NOTE: [] is *not* a valid subset, so we check for that as well.
+                if single_region
+                    || shorter_fr_plus == fr_static // `fr-: 'static` should be propogated
+                    || self.eval_outlives(fr_minus, shorter_fr_plus)
```
Comment (LorrensP-2158466) [inline compiler/rustc_borrowck/src/region_infer/mod.rs]: I couldn't find anything else that would give me the behaviour that is intended.
Is there something more correct perhaps?

Comment (lcnr) [reply compiler/rustc_borrowck/src/region_infer/mod.rs]: Two things are odd here:
- why special case `'static`?
- How does this handle cases where none of the `fr_minus: shorter_fr_plus` hold?

I would instead expect: check whether any in `fr_plus` is outlived by `fr_minus`, and if so emit outlives only for these regions, otherwise for all of them

Comment (LorrensP-2158466) [reply compiler/rustc_borrowck/src/region_infer/mod.rs]: Ah right 🤦. I forgot that this doesn't account for
> How does this handle cases where none of the fr_minus: shorter_fr_plus hold

And I included those extra checks because of it...

Comment (LorrensP-2158466) [reply compiler/rustc_borrowck/src/region_infer/mod.rs]: update: fixed, same test behaviour and nicer diff :)

**Comment by LorrensP-2158466** [comment]
> Then I/we need to write an FCP proposal 😁

BTW, I would love to help with this if isn't to much to ask. I have never done it, so I might as well get some experience. :)

**Comment by lcnr** [comment]
@craterbot check

File: tests/ui/regions/closure-prop-issue-148289.rs [hunk 2]
```diff
@@ -0,0 +1,22 @@
+//@ check-pass
+
```
Comment (lcnr) [inline tests/ui/regions/closure-prop-issue-148289.rs:6]: pls add a comment explaining this test and where it's from

File: tests/ui/regions/closure-prop-issue-104477-case1.rs [hunk 3]
```diff
@@ -0,0 +1,11 @@
+//@ check-pass
+
+
```
Comment (lcnr) [inline tests/ui/regions/closure-prop-issue-104477-case1.rs:6]: same here

File: tests/ui/regions/closure-prop-issue-148289.rs (hunk 2 above)
Comment (LorrensP-2158466) [reply tests/ui/regions/closure-prop-issue-148289.rs:6]: Will do!

But I thought that referencing the issue was enough is ui tests, since that explains it pretty well.

Comment (lcnr) [reply tests/ui/regions/closure-prop-issue-148289.rs:6]: I think adding one or two sentences explaining what's going on tends to still be useful, as looking up the issue is one more step which can be annoying.

File: tests/ui/regions/closure-prop-issue-104477-case1.rs (hunk 3 above)
Comment (LorrensP-2158466) [reply tests/ui/regions/closure-prop-issue-104477-case1.rs:6]: I'm actually not quiet sure what happens here.

`'_` is a local lifetime with non-local upperbounds `['a, 'b]`. So as a graph:
```
 -> a 
/
_
\
 -> b
```

then we try to propagate `'a: '_`, we get `fr_shorter+` for `'_` is `['a, 'b]`.
Does this result in the requirement `'a: 'b`?

Comment (lcnr) [reply tests/ui/regions/closure-prop-issue-104477-case1.rs:6]: also a good reason to write explanations for tests :> apparently we don't explain things well enough in issues some times xd

we have `'a: '_` and. For `fr_longer` the non-local lower bound of `'a` is `'a`.

> then we try to propagate 'a: '_, we get fr_shorter+ for '_ is ['a, 'b].
> Does this result in the requirement 'a: 'b?

Yes. On stable we propagate both `'a: 'a` and `'a: 'b`.

As `'a: 'a` is required anyways and `'a: 'b` is not we now only propagate `'a: 'a` and drop `'a: 'b`.

Comment (LorrensP-2158466) [reply tests/ui/regions/closure-prop-issue-104477-case1.rs:6]: > also a good reason to write explanations for tests :> apparently we don't explain things well enough in issues some times xd

Yeah, when writing this explanation I noticed it too 😄.

> Yes. On stable we propagate both 'a: 'a and 'a: 'b.
> 
> As 'a: 'a is required anyways and 'a: 'b is not we now only propagate 'a: 'a and drop 'b: 'b.

Aha, alright thanks!

File: tests/ui/regions/closure-prop-issue-148289.rs [hunk 4]
```diff
@@ -0,0 +1,26 @@
+//@ check-pass
+// This test checks that the compiler does not propagate 'd: 'c when propagating region errors
+// for the closure argument. If it did, this would fail to compile, eventhough it's a valid program.
+// It should only propagate 'd: 'c.
```
Comment (lcnr) [inline tests/ui/regions/closure-prop-issue-148289.rs]: this comment is wrong :> we should only propagate `'d: 'b`

**Comment by LorrensP-2158466** [comment]
I added @lcnr's suggestion from [#t-types > work on FCP proposal for closure requirements](https://rust-lang.zulipchat.com/#narrow/channel/144729-t-types/topic/work.20on.20FCP.20proposal.20for.20closure.20requirements/with/554996915). We now consider every non-local lower found for `fr_longer` when propagating `fr_longer: fr_shorter`, instead of the post-dominating one.

We should probably run crater with these changes again, right?

File: tests/ui/nll/closure-requirements/propagate-approximated-fail-no-postdom.rs
Comment (LorrensP-2158466) [inline tests/ui/nll/closure-requirements/propagate-approximated-fail-no-postdom.rs:1]: Because we don't approximate to the post-dominating region of `fr_longer`, this now behaves differently.

TODO: change file name, but i'll do that once this is approved.

Comment (lcnr) [inline tests/ui/nll/closure-requirements/propagate-approximated-fail-no-postdom.rs]:
```suggestion
// Test what happens for closure constraints where the longer region
// has multiple non-local lower bounds without any postdominating one.
```

or sth

**Comment by lcnr** [comment]
I don't actually think we need to run crater. This should allow strictly more code to compile :>

File: tests/ui/nll/closure-requirements/propagate-approximated-fail-no-postdom.rs
Comment (LorrensP-2158466) [reply tests/ui/nll/closure-requirements/propagate-approximated-fail-no-postdom.rs]: alright thanks!

File: compiler/rustc_borrowck/src/region_infer/mod.rs
Comment (lcnr) [inline compiler/rustc_borrowck/src/region_infer/mod.rs]:
```suggestion
// Grow `shorter_fr` until we find some non-local regions. 
// We will always find at least one: `'static`. We'll call
// them `shorter_fr+` -- they're ever so slightly larger
// than `shorter_fr`.
```

File: compiler/rustc_borrowck/src/region_infer/mod.rs [hunk 5]
```diff
@@ -1293,11 +1299,46 @@ impl<'tcx> RegionInferenceContext<'tcx> {
...
+
+            // We then create constraints `longer_fr-: shorter_fr+` that may or may not be propagated (see below).
+            let mut constraints = vec![];
+            for fr_minus in longer_fr_minus {
+                for shorter_fr_plus in &shorter_fr_plus {
+                    constraints.push((fr_minus, *shorter_fr_plus));
+                }
+            }
+
+            // If any of the `shorter_fr+` regions are already outlived by `longer_fr-`, we propagate only those.
```
Comment (lcnr) [inline compiler/rustc_borrowck/src/region_infer/mod.rs]:
```suggestion
            // We only need to propagate at least one of the constraints for
            // soundness. However, we want to avoid arbitrary choices here
            // and currently don't support returning OR constraints.
            //
            // If any of the `shorter_fr+` regions are already outlived by `longer_fr-`, we propagate only those.
```

File: compiler/rustc_borrowck/src/region_infer/mod.rs [hunk 6]
```diff
@@ -1293,11 +1299,46 @@ impl<'tcx> RegionInferenceContext<'tcx> {
...
+            // Consider this example (`'b: 'a` == `a -> b`), where we try to propagate `'d: 'a`:
+            // a --> b --> d
+            //  \
+            //   \-> c
+            // Here, `shorter_fr+` of `'a` == `['b, 'c]`.
+            // Propagating `'d: 'b` is correct and should occur; `'d: 'c` is redundant because of `'d: 'b`
+            // and could reject valid code.
+            //
+            // So we filter the constraints to regions already outlived by `longer_fr-`, but if the filter yields an empty set,
+            // we fall back to the original one.
```
Comment (lcnr) [inline compiler/rustc_borrowck/src/region_infer/mod.rs]:
```suggestion
            // So we filter the constraints to regions already outlived by `longer_fr-`, but if
            // the filter yields an empty set, we fall back to the original one.
```
or sth. surprised tidy doens't complain here, or maybe it does 🤷

**Review by lcnr — APPROVED** [review]

**Comment by lcnr** [comment]
This FCP has been written in collaboration of @LorrensP-2158466 and myself. We've tried to follow [the stabilization report template](https://github.com/rust-lang/rustc-dev-guide/blob/main/src/stabilization_report_template.md). Separate from the content of this specific FCP, I would love to get some feedback on the use of that template.

@rfcbot fcp merge types

## Summary

### Background

While we borrowck closures and their parent body in the same query to handle opaque types, each body is otherwise handled separately. When checking closures (and const blocks), we don't know the region constraints of the parent body, so we don't know anything about non-late bound regions of the closure.

These regions are represented as *external universal regions* of the closure, e.g. in 
```rust
fn foo<'a>(mut x: &'a str) {
    let upvar = "hi there";
    let _: Box<dyn FnOnce(&mut &'a str) -> &'a str> = Box::new(|s| {
        let prev = *s;
        *s = upvar;
        prev
    });
}
```
When borrow checking the closure, it's signature is `for<'anon> fn(&'anon &'ext0 str) -> &'ext1 str)` and it has an upvar of type `&'ext2 str`.

Because of its signature it can assume that `'ext0: 'anon` holds. It does not know anything else about its external regions. Notably even though the expected signature will use `'a` twice, we still use two separate external regions here.

Borrow checking the closure now requires `'ext0: 'ext1` because of the return statement and `'ext2: 'ext0` because of the assignment. We don't know whether these outlive requirements hold and we propagate them to the parent function instead.

If both regions we have to propagate are already external, that's easy. However, we may also have to handle constraints which reference regions internal to the closure. In this case, we can't propagate the constraint to the caller, as the caller cannot name these regions of the closure. In these cases we propagate constrains which *imply* the constraint we actually have to prove.

E.g. in the above example if the closure ended up requiring `'ext2: 'anon` we can't propagate this to the caller directly. However, as we know that `'ext0: 'anon` holds, we can instead propagate `'ext2: 'ext0` which then transitively implies `'ext2: 'anon`.

Given `longer_fr: shorter_fr` we need to propagate at least one constraint `fr-: shorter_fr+` for which the closure knows that `longer_fr: longer_fr-` and `shorter_fr+: 'shorter_fr` hold.

### The behavior on stable

When propagating a region error `longer_fr: shorter_fr` for a closure, we currently propagate every requirement `fr-: shorter_fr+` we find, where `fr-` is the postdominating external lower bound of `longer_fr`. `'shorter_fr+` are all external upper bounds of `'shorter_fr`. However, this can cause some valid programs to fail to compile. See https://rustc-dev-guide.rust-lang.org/borrow_check/region_inference/closure_constraints.html for more details.

### The behavior of this PR

Instead of trying to compute a unique `fr-` by using the postdominating lower bound of `'longer_fr` we use all external lower bounds of `'longer_fr`, propagating separate constraints for each of them.

This allows code to compile where `'longer_fr` does multiple external lower bounds but no postdominator. 

We also filter the list of all `'longer_fr-: shorter_fr+` to only these constraints between external regions which are required regardless. If no such constraint exists, we fall back to propagating all of them. This avoids any non-determinism while also fixing the main source of spurious errors here.

### Example 

Consider this simple program:
```rust
#[derive(Clone, Copy)]
struct Inv<'a>(*mut &'a ());
impl<'a> Inv<'a> {
    fn outlived_by<'b: 'a>(self, _: Inv<'b>) {}
}
struct OutlivedBy<'a, 'b: 'a>(Inv<'a>, Inv<'b>);

fn closure_arg<'b, 'c, 'd>(_: impl for<'a> FnOnce(
    Inv<'a>,
    OutlivedBy<'a, 'b>,
    OutlivedBy<'a, 'c>,
    Inv<'d>,
)) {}

fn foo<'b, 'c, 'd: 'b>() {
    closure_arg::<'b, 'c, 'd>(|a, b, c, d| {
        a.outlived_by(b.1);
        a.outlived_by(c.1);
        b.1.outlived_by(d);
    });
}
```

It currently fails to compile and gives the following error:
```
error: lifetime may not live long enough
  --> src/main.rs:9:5
   |
 8 |   fn foo<'b, 'c, 'd: 'b>() {
   |              --  -- lifetime `'d` defined here
   |              |
   |              lifetime `'c` defined here
 9 | /     closure_arg::<'b, 'c, 'd>(|a, b, c, d| {
10 | |         a.outlived_by(b.1);
11 | |         a.outlived_by(c.1);
12 | |         b.1.outlived_by(d);
13 | |     });
   | |______^ argument requires that `'d` must outlive `'c`
```

The closure has a local region `'a` and external regions `'b`, `'c` and `'d`.

It's assumptions are `'d: 'a` and `'c: 'a`. Borrow checking results in the requirements: `'b: 'a`, `'c: 'a`, `'d: 'b`. This also transitively requires `'d: 'a`.

When encountering `'d: 'a` in [fn check_universal_region_relation](https://github.com/rust-lang/rust/blob/6840234806e4a57e14112a1137783c885b7a23db/compiler/rustc_borrowck/src/region_infer/mod.rs#L1246) this errors and we need to propagate the constraint to the parent body via [fn try_propagate_universal_region_error](https://github.com/rust-lang/rust/blob/c8f22ca269a1f2653ac962fe2bc21105065fd6cd/compiler/rustc_borrowck/src/region_infer/mod.rs#L1272). If we visualize the outlives requirements, where `'b: 'a` == `a -> b`, we get the following outlives graph:
```
a -> b -> d
|
+ -> c
```

On stable, we compute the [postdominating non-local lower bound of `'d`](https://github.com/rust-lang/rust/blob/c8f22ca269a1f2653ac962fe2bc21105065fd6cd/compiler/rustc_borrowck/src/region_infer/mod.rs#L1282) (`'fr-`) and [*all* non-local upper bounds of `'a`](https://github.com/rust-lang/rust/blob/c8f22ca269a1f2653ac962fe2bc21105065fd6cd/compiler/rustc_borrowck/src/region_infer/mod.rs#L1294) (`'fr_shorter+`).

The `shorter_fr+` of `'a` are `['b, 'c]` and the algorithm conservatively requires that `'d` should outlive both of them. Propagating `'d: 'c` then results in a compilation failure.

This PR filters the constraint list (point 1) of `longer_fr-: shorter_fr+` to the regions that are already required to be outlived by `'longer_fr-` (only `'d` in this example) and then only propagates those requirements (`'d: 'b` in this example).

If there are no regions which are already required to be outlived by `longer_fr-`, we still propagate all constraints just to be safe.

### What is stabilized n/a

### What isn't stabilized n/a

## Design

### Reference

We currently don't document borrowck in the reference. Once we do this, this is PR requires a localized change to how we propagate requirements from nested bodies.

### RFC history n/a
### Answers to unresolved questions n/a
### Post-RFC changes n/a
### Key points n/a

### Nightly extensions n/a

### Doors closed n/a

## Feedback

### Call for testing n/a

### Nightly use n/a

## Implementation n/a see summary

### Major parts n/a

### Coverage

See the tests added in this PR for things which now compile.

If we incorrectly do not propagate any constraints if there are no `longer_fr-` then the test TODO fails.

If we incorrectly propagate no constraints in case none of them are already
required, i.e. the subset is empty, then the test TODO fails.

### Outstanding bugs

We sometimes still propagate multiple constraints even though a single one would be sufficient, potentially causing unnecessary errors.

To avoid any such errors here, we'd probably have to support OR constraints. There may also be some future improvements to closure constraint propagation, but :shrug: we want to avoid introducing non-determinstic or surprising behavior here.

### Outstanding FIXMEs n/a

### Tool changes n/a

### Breaking changes n/a

## Type system, opsem

### Compile-time checks n/a

### Type system rules n/a

### Sound by default? n/a

### Breaks the AM? n/a

## Common interactions

### Temporaries n/a

### Drop order n/a

### Pre-expansion / post-expansion n/a

### Edition hygiene n/a

### SemVer implications n/a

### Exposing other features n/a

## History

Propagating closure requirements was originally implemented by @nikomatsakis in https://github.com/rust-lang/rust/pull/46509 and then improved by @matthewjasper in https://github.com/rust-lang/rust/pull/58347.

## Acknowledgments

## Open items

None

File: tests/ui/nll/closure-requirements/propagate-approximated-fail-no-postdom.rs
Comment (lcnr) [reply tests/ui/nll/closure-requirements/propagate-approximated-fail-no-postdom.rs:1]: relevant

File: compiler/rustc_borrowck/src/region_infer/mod.rs [hunk 7]
```diff
@@ -1275,29 +1275,76 @@ impl<'tcx> RegionInferenceContext<'tcx> {
...
+                })
+                .copied()
+                .collect();
+            let propagated_constraints = if subset.is_empty() { constraints } else { subset };
+            debug!(
+                "try_propagate_universal_region_error: constraints={:?}",
+                propagated_constraints
+            );
+
+            for (fr_minus, fr_plus) in propagated_constraints {
```
Comment (lcnr) [inline compiler/rustc_borrowck/src/region_infer/mod.rs:1348]: can you add an assert that `propagated_constraints` is not empty before the `for` here?

File: tests/ui/regions/closure-prop-issue-104477-case2.rs
Comment (lcnr) [inline tests/ui/regions/closure-prop-issue-104477-case2.rs]: relevant :3

`'_` has `'a` and `'b` as non-local lower bounds.

**Review by lcnr — COMMENTED** [review]
nits, then r=me

*[View changes since this review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/rust/148329/0b329f801a09004dacb19aaf09d5cb8b4c51d3f8..402f3e0653645db96ae4bc2839f2b4a8ee6c6052)*

File: tests/ui/regions/closure-prop-issue-104477-case2.rs [hunk 8]
```diff
@@ -0,0 +1,10 @@
+//@ check-pass
+// FIXME: add explanation.
```
Comment (lqd) [inline tests/ui/regions/closure-prop-issue-104477-case2.rs]: 👀

File: tests/ui/regions/closure-prop-issue-148289.rs [hunk 9]
```diff
@@ -0,0 +1,26 @@
+//@ check-pass
+// This test checks that the compiler does not propagate 'd: 'c when propagating region errors
+// for the closure argument. If it did, this would fail to compile, eventhough it's a valid program.
+// It should only propagate 'd: 'b.
+// PR #148329 explains this in detail.
```
Comment (lqd) [inline tests/ui/regions/closure-prop-issue-148289.rs:5]: do you mean the stabilization report, or the new comments in `try_propagate_universal_region_error`?

Comment (LorrensP-2158466) [reply tests/ui/regions/closure-prop-issue-148289.rs:5]: Just te pr in general, like the information contained in it.
Is this not really done in tests?
