### PR TITLE
Recover `import` instead of `use` in item

### LINKED ISSUE #97788: rust could suggest "use" if it finds something like "import ... crate::"
Given the following code: 

```rust
mod a;
import crate::a::*;

fn main() {
    a();
    println!("Hello, world!");
}

```

The current output is:

```
error: expected one of `!` or `::`, found keyword `crate`
 --> src/main.rs:2:8
  |
2 | import crate::a::*;
  |        ^^^^^ expected one of `!` or `::`
```

Ideally the output should look like:

```
found keyword `import` did you instead intend to use `use` instead?
```

### PR DESCRIPTION
**Pull request by compiler-errors**
When we definitely don't have a macro invocation (i.e. when we don't have `import ::`), then it's more productive to parse `import` as if it was incorrectly mistaken for `use`.

Not sure if this needs to be a verbose suggestion, but it renders strangely when it's not verbose:
```
error: expected item, found `import`
 --> /home/michael/test.rs:1:1
  |
1 | import std::{io::{self, Write}, rc::Rc};
  | ^^^^^^ help: items are imported using the `use` keyword: `use`
```

Happy to change it to `span_suggestion` instead of `span_suggestion_verbose` though.

Fixes #97788

### CODE REVIEW

File: compiler/rustc_parse/src/parser/item.rs [hunk 1]
```diff
@@ -291,6 +273,8 @@ impl<'a> Parser<'a> {
         } else if vis.kind.is_pub() && self.isnt_macro_invocation() {
             self.recover_missing_kw_before_item()?;
             return Ok(None);
+        } else if self.token.is_ident_named(sym::import) && self.isnt_macro_invocation() {
```
Comment (wesleywiser) [inline compiler/rustc_parse/src/parser/item.rs:276]: I love this diagnostic improvement! Could we also consider doing the same thing for `using`? That keyword is used by C++ and C# for similar purposes (for instance: `using System.Collections.Generic;`). If you don't want to do that in this PR, that's totally fine! I can file an issue. 🙂

File: compiler/rustc_span/src/symbol.rs [hunk 2]
```diff
@@ -770,6 +770,7 @@ symbols! {
         impl_lint_pass,
         impl_macros,
         impl_trait_in_bindings,
+        import,
```
Comment (wesleywiser) [inline compiler/rustc_span/src/symbol.rs:773]: Just a thought, but I wonder if we should not intern this symbol since it's only used in error recovery and the cost of interning at runtime when we're going to fail anyway basically doesn't matter. There might be some small cost to having the symbol always interned, but I'm not 100% sure of that. Just thought I'd throw that idea out there 😄

File: src/test/ui/did_you_mean/use_instead_of_import.rs [hunk 3]
```diff
@@ -0,0 +1,10 @@
+import std::{
```
Comment (wesleywiser) [inline src/test/ui/did_you_mean/use_instead_of_import.rs:1]: Probably doesn't matter but it might be good to include the other style of path as well for completeness (`import std::sync::Arc;`)

**Review by wesleywiser — APPROVED** [review]
r=me with or without feedback implemented

File: compiler/rustc_parse/src/parser/item.rs (hunk 1 above)
Comment (compiler-errors) [reply compiler/rustc_parse/src/parser/item.rs:276]: Nah, that should be super easy.

File: compiler/rustc_span/src/symbol.rs (hunk 2 above)
Comment (compiler-errors) [reply compiler/rustc_span/src/symbol.rs:773]: Hm... my understanding is that interning a symbol is very cheap... I'll look into it.

**Comment by ChayimFriedman2** [comment]
Now what about dots instead of `::`? :P

**Comment by compiler-errors** [comment]
> Now what about dots instead of `::`? :P

That would be a separate and more complicated recovery than what we currently have. Feel free to file an issue or take a stab if you're interested.
