### PR TITLE
rustdoc: fix a few spots where emit isn't respected

### LINKED ISSUE #155298: rustdoc: List of issues related to Markdown input files
I didn't feel like opening ~~3~~ 2 GH issues for these niche issues, so here's a single one.

- [ ] ~~Given a Markdown input file and `--markdown-css file.css`, the depinfo (`--emit=depinfo -Zunstable-options`) doesn't list `file.css`~~
- [ ] Given a Markdown input file and `--markdown-css file.css`, the generated HTML document contains `<link rel="stylesheet" href="file.css">` but that path won't resolve unless you set `-o.` / `--output-dir=.` since it doesn't properly account for the output directory (which is `doc/` by default)
- [ ] Given a Markdown input file and `--emit=html-static-files` or `--emit=dep-info` or `--emit=html-static-files,dep-info`, we still emit a non-static HTML file, e.g, `doc/file.html` (which should only be emitted if `--emit` contains `html-non-static-files` which it implicitly does by default)

### PR DESCRIPTION
**Pull request by notriddle**
Addresses the third list item of rust-lang/rust#155298

### CODE REVIEW

File: src/librustdoc/html/render/write_shared.rs [hunk 1]
```diff
@@ -190,6 +190,10 @@ fn write_static_files(
     css_file_extension: Option<&Path>,
     resource_suffix: &str,
 ) -> Result<(), Error> {
+    if !opt.emit.is_empty() && !opt.emit.contains(&EmitType::HtmlStaticFiles) {
+        return Ok(());
+    }
```
Comment (notriddle) [inline src/librustdoc/html/render/write_shared.rs]: Alternatively, custom css should be considered non-static for the purpose of the `--emit` flag. In that case, the custom css emit code would be wrapped in `if opt.should_emit_crate() { ... }` and the built-in emit code below would be left alone.

Which one should it be?

*[View changes since the review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/rust/155374/e8e4541ff19649d95afab52fdde2c2eaa6829965..d8cecaca2e7ea7c499b39c482ef327c1e00d3df0)*

File: src/librustdoc/html/render/write_shared.rs [hunk 2]
```diff
@@ -183,43 +183,45 @@ fn write_rendered_cross_crate_info(
...
-    for entry in style_files {
-        let theme = entry.basename()?;
-        let extension =
-            try_none!(try_none!(entry.path.extension(), &entry.path).to_str(), &entry.path);
-
-        // Skip the official themes. They are written below as part of STATIC_FILES_LIST.
-        if matches!(theme.as_str(), "light" | "dark" | "ayu") {
-            continue;
-        }
+    if opt.emit.is_empty() || opt.emit.contains(&EmitType::HtmlNonStaticFiles) {
```
Comment (fmease) [inline src/librustdoc/html/render/write_shared.rs:193]: If we were to eagerly set `opt.emit` to `[HtmlNonStaticFiles, HtmlStaticFiles]` in the CLI parser if `--emit` wasn't passed, then later stages wouldn't need to know that "absence of emission types means two emission types" & thus wouldn't need to remember to check `opt.emit.is_empty()`. That'd make fn `should_emit_crate` unnecessary, too.

~~`opt.emit` could be a bitset even to avoid having to allocate 2×`EmitType` in the common case (peanuts ofc)~~ (won't work because `DepInfo` has a payload; well `SmallVec<_, 2>` would do).

Anyway just some thoughts for a potential future cleanup to make all of this more robust.

**Review by fmease — APPROVED** [review]
Thanks! I've updated the PR description since it doesn't fully fix #155298; list item (2) doesn't get addressed.

@bors r+ rollup

*[View changes since this review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/rust/155374/8da2d28cbd5a4e2b93e028e709afe09541671663..de48fc6a5620f804a5c7facf3b0274a1d807686e)*

File: src/librustdoc/html/render/write_shared.rs (hunk 2 above)
Comment (fmease) [reply src/librustdoc/html/render/write_shared.rs:193]: While trying to implement my suggestion I realized that I can't just replace the `is_empty && contains_html_non_static_files` checks under this scheme since the `is_empty` condition also accounts for "JSON non-static files", e.g., in `run_format` that's executed by both the HTML & the JSON backend.

I guess we could push a `EmitType::EmitJsonNonStaticFiles` under `output_format == OutputFormat::Json` that doesn't necessarily have a corresponding "surface syntax" (so no `--emit=json-non-static-files` unless we want to). Tho then I'd have to introduce `FormatRenderer::NON_STATIC_FILES: EmitType`, I guess that's fine.

Alternatively, we could also have a "lower" `EmitType` that just has `EmitNonStaticFiles` for Html+Json+Doctests but that seems really overengineered at this point.

Hmm, that makes me question the `html-` prefix of these options :thinking:. I need to reread the meeting messages.
