### PR TITLE
normalize substs while inlining

### LINKED ISSUE #68347: [MIR-opt] error: internal compiler error: src/librustc/traits/codegen/mod.rs:57: Encountered error `OutputTypeParameterMismatch(...) during codegen
```
error: internal compiler error: src/librustc/traits/codegen/mod.rs:57: Encountered error `OutputTypeParameterMismatch(
    Binder(<[closure@server/src/cmd.rs:985:19: 1030:10 sim:&&veloren_world::sim::WorldSim, wpos:&vek::vec::repr_c::vec2::Vec2<i32>, sampler:&veloren_world::column::ColumnGen] as std::ops::Fn<()>>),
    Binder(<[closure@server/src/cmd.rs:985:19: 1030:10 sim:&&veloren_world::sim::WorldSim, wpos:&vek::vec::repr_c::vec2::Vec2<i32>, sampler:&impl veloren_world::util::sampler::Sampler] as std::ops::Fn<()>>),
    Sorts(ExpectedFound {
        expected: impl veloren_world::util::sampler::Sampler,
        found: veloren_world::column::ColumnGen
    })
)` selecting `Binder(<
    [closure@server/src/cmd.rs:985:19: 1030:10 sim:&&veloren_world::sim::WorldSim, wpos:&vek::vec::repr_c::vec2::Vec2<i32>, sampler:&impl veloren_world::util::sampler::Sampler]
    as
    std::ops::Fn<()>
>)` during codegen
```

```
$ git clone https://gitlab.com/veloren/veloren
$ git checkout 8d2c69673dd63e3cb689f1df5574eabfed7826af
$ RUSTFLAGS="-Zmir-opt-level=3" cargo build
[...]
error: internal compiler error: src/librustc/traits/codegen/mod.rs:57: Encountered error `OutputTypeParameterMismatch(Binder(<[closure@server/src/cmd.rs:985:19: 1030:10 sim:&&veloren_world::sim::WorldSim, wpos:&vek::vec::repr_c::vec2::Vec2<i32>, sampler:&veloren_world::column::ColumnGen] as std::ops::Fn<()>>), Binder(<[closure@server/src/cmd.rs:985:19: 1030:10 sim:&&veloren_world::sim::WorldSim, wpos:&vek::vec::repr_c::vec2::Vec2<i32>, sampler:&impl veloren_world::util::sampler::Sampler] as std::ops::Fn<()>>), Sorts(ExpectedFound { expected: impl veloren_world::util::sampler::Sampler, found: veloren_world::column::ColumnGen }))` selecting `Binder(<[closure@server/src/cmd.rs:985:19: 1030:10 sim:&&veloren_world::sim::WorldSim, wpos:&vek::vec::repr_c::vec2::Vec2<i32>, sampler:&impl veloren_world::util::sampler::Sampler] as std::ops::Fn<()>>)` during codegen

thread 'rustc' panicked at 'Box<Any>', src/librustc_errors/lib.rs:872:9
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:77
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1057
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1426
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:195
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:215
  10: rustc_driver::report_ice
  11: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:467
  12: std::panicking::begin_panic
  13: rustc_errors::HandlerInner::bug
  14: rustc_errors::Handler::bug
  15: rustc::util::bug::opt_span_bug_fmt::{{closure}}
  16: rustc::ty::context::tls::with_opt::{{closure}}
  17: rustc::ty::context::tls::with_opt
  18: rustc::util::bug::opt_span_bug_fmt
  19: rustc::util::bug::bug_fmt
  20: rustc::ty::context::GlobalCtxt::enter_local
  21: rustc::traits::codegen::codegen_fulfill_obligation
  22: rustc::ty::query::__query_compute::codegen_fulfill_obligation
  23: rustc::ty::query::<impl rustc::ty::query::config::QueryAccessors for rustc::ty::query::queries::codegen_fulfill_obligation>::compute
  24: rustc::dep_graph::graph::DepGraph::with_task_impl
  25: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt>::get_query
  26: rustc::ty::instance::Instance::resolve
  27: rustc_mir::transform::inline::Inliner::run_pass
  28: <rustc_mir::transform::inline::Inline as rustc_mir::transform::MirPass>::run_pass
  29: rustc_mir::transform::run_passes
  30: rustc_mir::transform::run_optimization_passes
  31: rustc_mir::transform::optimized_mir
  32: rustc::ty::query::<impl rustc::ty::query::config::QueryAccessors for rustc::ty::query::queries::optimized_mir>::compute
  33: rustc::dep_graph::graph::DepGraph::with_task_impl
  34: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt>::get_query
  35: rustc::ty::<impl rustc::ty::context::TyCtxt>::instance_mir
  36: rustc_mir::monomorphize::collector::collect_items_rec
  37: rustc_mir::monomorphize::collector::collect_items_rec
  38: rustc_mir::monomorphize::collector::collect_items_rec
  39: rustc_mir::monomorphize::collector::collect_items_rec
  40: rustc_mir::monomorphize::collector::collect_items_rec
  41: rustc_mir::monomorphize::collector::collect_items_rec
  42: rustc_mir::monomorphize::collector::collect_items_rec
  43: rustc_mir::monomorphize::collector::collect_items_rec
  44: rustc_mir::monomorphize::collector::collect_items_rec
  45: rustc_mir::monomorphize::collector::collect_items_rec
  46: rustc_mir::monomorphize::collector::collect_items_rec
  47: rustc_session::utils::<impl rustc_session::session::Session>::time
  48: rustc_mir::monomorphize::collector::collect_crate_mono_items
  49: rustc_mir::monomorphize::partitioning::collect_and_partition_mono_items
  50: rustc::ty::query::__query_compute::collect_and_partition_mono_items
  51: rustc::dep_graph::graph::DepGraph::with_task_impl
  52: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt>::get_query
  53: rustc_codegen_cranelift::driver::codegen_crate
  54: <rustc_codegen_cranelift::CraneliftCodegenBackend as rustc_codegen_utils::codegen_backend::CodegenBackend>::codegen_crate
  55: rustc_session::utils::<impl rustc_session::session::Session>::time
  56: rustc_interface::passes::QueryContext::enter
  57: rustc_interface::queries::Queries::ongoing_codegen
  58: rustc_interface::interface::run_compiler_in_existing_thread_pool
  59: scoped_tls::ScopedKey<T>::set
  60: syntax::with_globals
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.42.0-nightly (31dd4f4ac 2020-01-13) running on x86_64-unknown-linux-gnu

note: compiler flags: -Z panic-abort-tests -Z codegen-backend=/home/bjorn/Documenten/cg_clif/target/release/librustc_codegen_cranelift.so -Z mir-opt-level=3 -C opt-level=2 -C panic=abort -C codegen-units=8 -C debug-assertions=on -C incremental -C panic=abort -C debuginfo=2 --crate-type lib

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [codegen_fulfill_obligation] checking if `std::ops::Fn` fulfills its obligations
#1 [optimized_mir] processing `cmd::handle_debug_column`
#2 [collect_and_partition_mono_items] collect_and_partition_mono_items
end of query stack
error: aborting due to previous error

error: could not compile `veloren-server`.
```

@rustbot modify labels: +A-mir +C-bug +requires-nightly

### PR DESCRIPTION
**Pull request by lcnr**
fixes #68347 or more precisely, this fixes the same ICE in rust analyser as veloren is pinned to a specific nightly
and had an error with the current one.

I didn't look into creating an MVCE here as that seems fairly annoying, will spend a few minutes doing so rn. (failed)

r? @eddyb cc @bjorn3

### CODE REVIEW

**Comment by eddyb** [comment]
Hmm, this might be expensive. What I would do is assert that normalizing doesn't change the type, then track down the source of the unnormalized type and fix *that*. But just to see what impact it has on its own:

@bors try @rust-timer queue

**Comment by eddyb** [comment]
LGTM but r? @nikomatsakis or @matthewjasper (this feels like a matter of policy, i.e. fixing bugs or working around them).

**Comment by lcnr** [comment]
will spend a bit of time looking at where we fail to normalize this week to fix his bug at its origin

**Review by nikomatsakis — APPROVED** [review]

**Comment by nikomatsakis** [comment]
The change itself seems harmless. I am of two minds about whether this sort of workaround is acceptable. In general I prefer to normalize at the source but I also feel like being pragmatic may make sense. It's too bad there is no test here but I see that @lcnr already tried to create one and failed.

**Comment by nikomatsakis** [comment]
I guess I would say that if some effort at investigation fails, I am inclined to r+

**Comment by lcnr** [comment]
Minimization
```rust
pub fn write() {
    create()()
}

pub fn create() -> impl FnOnce() {
   || ()
}
```

**Comment by lqd** [comment]
Here's a reduction of the veloren error:

```rust
pub fn main() {
    let _x: fn() = handle_debug_column;
}

fn handle_debug_column() {
    let sampler = sample_columns();

    let foo = || {
        sampler.get(17);
    };
    foo();
}

fn sample_columns() -> impl Sampler {
    ColumnGen {}
}

struct ColumnGen {}

trait Sampler {
    fn get(&self, index: i32);
}

impl Sampler for ColumnGen {
    fn get(&self, _index: i32) {}
}
```

**Comment by lcnr** [comment]
added the test by @lqd 

@bors r=eddyb

**Comment by lzutao** [comment]
(*test-pass to build-fail during beta week*)

@rustbot modify labels: S-block

**Comment by lqd** [comment]
(rls and rustfmt are what is now failing to build)

**Comment by lcnr** [comment]
looks like we have another missing normalization in this case, will look into this

**Comment by lqd** [comment]
The rustfmt ICE in `normalize_erasing_regions` for `rustc_parse` looked very similar to the one introduced by the "MirSource PR" but is actually older, so here's a reduction of it:

```rust
struct Cursor {}
struct TokenTree {}

impl Iterator for Cursor {
    type Item = TokenTree;

    fn next(&mut self) -> Option<TokenTree> {
        unimplemented!()
    }
}

fn tokenstream_probably_equal_for_proc_macro() {
    fn break_tokens(_tree: TokenTree) -> impl Iterator<Item = TokenTree> {
        let token_trees: Vec<TokenTree> = vec![];
        token_trees.into_iter()
    }

    let c1 = Cursor {};
    let c2 = Cursor {};

    let mut t1 = c1.flat_map(break_tokens);
    let mut t2 = c2.flat_map(break_tokens);

    for (_t1, _t2) in t1.by_ref().zip(t2.by_ref()) {}
}

fn main() {
    tokenstream_probably_equal_for_proc_macro();
}
```

**Comment by lcnr** [comment]
blocked on #77568, we have to use `tcx.param_env_reveal_all_normalized` instead of `tcx.param_env` here.

File: src/test/ui/mir/mir-inlining/ice-issue-77306-2.rs [hunk 1]
```diff
@@ -0,0 +1,32 @@
+// check-pass
```
Comment (lcnr) [inline src/test/ui/mir/mir-inlining/ice-issue-77306-2.rs:1]: uff

sometimes I am not as clever as I would like to be

**Review by eddyb — APPROVED** [review]
