### PR TITLE
Pretty-print inherent projections correctly

### LINKED ISSUE #111390: ICE: inherent_associated_types: `Unexpected parameter Type(S<'a>) when substituting in region 'a (index=0)`  with -Zdump-mir=all
### Code
`rustc -Zdump-mir=all late-bound-regions.rs`
```Rust
#![feature(inherent_associated_types)]

type Function = for<'a> fn(&'a i32) -> S<'a>::P;

struct S<'a>(&'a ());

impl<'a> S<'a> {
    type P = &'a i32;
}

fn ret_ref_local<'e>() -> &'e i32 {
    let f: Function = |x| x;

    let local = 0;
    f(&local) 
}

fn main() {}

```

### Meta

`rustc --version --verbose`:
```
rustc 1.71.0-nightly (2f2c438dc 2023-05-08)
binary: rustc
commit-hash: 2f2c438dce75d8cc532c3baa849eeddc0901802c
commit-date: 2023-05-08
host: x86_64-unknown-linux-gnu
release: 1.71.0-nightly
LLVM version: 16.0.2
```

### Error output

```
<output>
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
error: internal compiler error: compiler/rustc_middle/src/ty/subst.rs:810:13: Unexpected parameter Type(S<'a>) when substituting in region 'a (index=0)

thread 'rustc' panicked at 'Box<dyn Any>', /rustc/2f2c438dce75d8cc532c3baa849eeddc0901802c/compiler/rustc_errors/src/lib.rs:1650:9
stack backtrace:
   0:     0x7ff285946361 - std::backtrace_rs::backtrace::libunwind::trace::he9e9030cf5bcddaa
                               at /rustc/2f2c438dce75d8cc532c3baa849eeddc0901802c/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x7ff285946361 - std::backtrace_rs::backtrace::trace_unsynchronized::hb5e44a77ff0586eb
                               at /rustc/2f2c438dce75d8cc532c3baa849eeddc0901802c/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7ff285946361 - std::sys_common::backtrace::_print_fmt::h38e8723c5d83f22f
                               at /rustc/2f2c438dce75d8cc532c3baa849eeddc0901802c/library/std/src/sys_common/backtrace.rs:65:5
   3:     0x7ff285946361 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h5e394c4b1f1cb045
                               at /rustc/2f2c438dce75d8cc532c3baa849eeddc0901802c/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x7ff2859a66ff - core::fmt::rt::Argument::fmt::ha5dde4cb71578cc2
                               at /rustc/2f2c438dce75d8cc532c3baa849eeddc0901802c/library/core/src/fmt/rt.rs:138:9
   5:     0x7ff2859a66ff - core::fmt::write::hb1413899fd777907
                               at /rustc/2f2c438dce75d8cc532c3baa849eeddc0901802c/library/core/src/fmt/mod.rs:1094:21
   6:     0x7ff2859395c1 - std::io::Write::write_fmt::h08b4eac68313bb0d
                               at /rustc/2f2c438dce75d8cc532c3baa849eeddc0901802c/library/std/src/io/mod.rs:1712:15
   7:     0x7ff285946175 - std::sys_common::backtrace::_print::h2bb25f41b1777226
                               at /rustc/2f2c438dce75d8cc532c3baa849eeddc0901802c/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x7ff285946175 - std::sys_common::backtrace::print::ha21981aa5a1c5802
                               at /rustc/2f2c438dce75d8cc532c3baa849eeddc0901802c/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x7ff285948e07 - std::panicking::default_hook::{{closure}}::h603ce04329232051
  10:     0x7ff285948bf4 - std::panicking::default_hook::hd4285764fbdb24e1
                               at /rustc/2f2c438dce75d8cc532c3baa849eeddc0901802c/library/std/src/panicking.rs:288:9
  11:     0x7ff2847bf94b - <rustc_driver_impl[27c68de0ac55b06a]::install_ice_hook::{closure#0} as core[3afeaedfb140cde7]::ops::function::FnOnce<(&core[3afeaedfb140cde7]::panic::panic_info::PanicInfo,)>>::call_once::{shim:vtable#0}
  12:     0x7ff285949527 - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h401f21a7538313bc
                               at /rustc/2f2c438dce75d8cc532c3baa849eeddc0901802c/library/alloc/src/boxed.rs:1999:9
  13:     0x7ff285949527 - std::panicking::rust_panic_with_hook::h2322eda2481f33bc
                               at /rustc/2f2c438dce75d8cc532c3baa849eeddc0901802c/library/std/src/panicking.rs:695:13
  14:     0x7ff284cae031 - std[53b54636b4f52653]::panicking::begin_panic::<rustc_errors[2afb0e2cc7c4c42d]::ExplicitBug>::{closure#0}
  15:     0x7ff284caa7e6 - std[53b54636b4f52653]::sys_common::backtrace::__rust_end_short_backtrace::<std[53b54636b4f52653]::panicking::begin_panic<rustc_errors[2afb0e2cc7c4c42d]::ExplicitBug>::{closure#0}, !>
  16:     0x7ff284caa6d6 - std[53b54636b4f52653]::panicking::begin_panic::<rustc_errors[2afb0e2cc7c4c42d]::ExplicitBug>
  17:     0x7ff284ca5264 - <rustc_errors[2afb0e2cc7c4c42d]::HandlerInner>::bug::<alloc[a4f318becb59a05]::string::String>
  18:     0x7ff284ca4d76 - <rustc_errors[2afb0e2cc7c4c42d]::Handler>::bug::<alloc[a4f318becb59a05]::string::String>
  19:     0x7ff284d31bac - rustc_middle[232bd29a687eeda3]::util::bug::opt_span_bug_fmt::<rustc_span[811089187935bcb6]::span_encoding::Span>::{closure#0}
  20:     0x7ff284d3137a - rustc_middle[232bd29a687eeda3]::ty::context::tls::with_opt::<rustc_middle[232bd29a687eeda3]::util::bug::opt_span_bug_fmt<rustc_span[811089187935bcb6]::span_encoding::Span>::{closure#0}, !>::{closure#0}
  21:     0x7ff284d3134a - rustc_middle[232bd29a687eeda3]::ty::context::tls::with_context_opt::<rustc_middle[232bd29a687eeda3]::ty::context::tls::with_opt<rustc_middle[232bd29a687eeda3]::util::bug::opt_span_bug_fmt<rustc_span[811089187935bcb6]::span_encoding::Span>::{closure#0}, !>::{closure#0}, !>
  22:     0x7ff2829c8f8d - rustc_middle[232bd29a687eeda3]::util::bug::bug_fmt
  23:     0x7ff284cb7731 - <rustc_middle[232bd29a687eeda3]::ty::subst::SubstFolder as rustc_type_ir[cc09a4b81b2ca552]::fold::TypeFolder<rustc_middle[232bd29a687eeda3]::ty::context::TyCtxt>>::fold_region::region_param_invalid
  24:     0x7ff2827ae0c9 - <rustc_middle[232bd29a687eeda3]::ty::subst::GenericArg as rustc_type_ir[cc09a4b81b2ca552]::fold::TypeFoldable<rustc_middle[232bd29a687eeda3]::ty::context::TyCtxt>>::try_fold_with::<rustc_middle[232bd29a687eeda3]::ty::subst::SubstFolder>
  25:     0x7ff2827abe46 - <rustc_middle[232bd29a687eeda3]::ty::Ty as rustc_type_ir[cc09a4b81b2ca552]::fold::TypeSuperFoldable<rustc_middle[232bd29a687eeda3]::ty::context::TyCtxt>>::super_fold_with::<rustc_middle[232bd29a687eeda3]::ty::subst::SubstFolder>
  26:     0x7ff28290ae4b - <rustc_middle[232bd29a687eeda3]::ty::print::pretty::FmtPrinter as rustc_middle[232bd29a687eeda3]::ty::print::Printer>::print_def_path
  27:     0x7ff28290a7c6 - <rustc_middle[232bd29a687eeda3]::ty::print::pretty::FmtPrinter as rustc_middle[232bd29a687eeda3]::ty::print::Printer>::print_def_path
  28:     0x7ff282907f2b - <rustc_middle[232bd29a687eeda3]::ty::print::pretty::FmtPrinter as rustc_middle[232bd29a687eeda3]::ty::print::pretty::PrettyPrinter>::pretty_print_type
  29:     0x7ff284d38036 - <rustc_middle[232bd29a687eeda3]::ty::print::pretty::FmtPrinter as rustc_middle[232bd29a687eeda3]::ty::print::pretty::PrettyPrinter>::pretty_fn_sig
  30:     0x7ff284cfae2f - <rustc_middle[232bd29a687eeda3]::ty::sty::FnSig as rustc_middle[232bd29a687eeda3]::ty::print::Print<rustc_middle[232bd29a687eeda3]::ty::print::pretty::FmtPrinter>>::print
  31:     0x7ff284d409f2 - <rustc_middle[232bd29a687eeda3]::ty::print::pretty::FmtPrinter>::pretty_in_binder::<rustc_middle[232bd29a687eeda3]::ty::sty::FnSig>
  32:     0x7ff28290903b - <rustc_middle[232bd29a687eeda3]::ty::print::pretty::FmtPrinter as rustc_middle[232bd29a687eeda3]::ty::print::pretty::PrettyPrinter>::pretty_print_type
  33:     0x7ff28290752c - <rustc_middle[232bd29a687eeda3]::ty::Ty as core[3afeaedfb140cde7]::fmt::Display>::fmt
  34:     0x7ff284d51a28 - <rustc_middle[232bd29a687eeda3]::ty::Ty as core[3afeaedfb140cde7]::fmt::Debug>::fmt
  35:     0x7ff2859a360c - core::fmt::builders::DebugTuple::field::{{closure}}::hae8bf7adeee9f6a5
                               at /rustc/2f2c438dce75d8cc532c3baa849eeddc0901802c/library/core/src/fmt/builders.rs:322:17
  36:     0x7ff2859a360c - core::result::Result<T,E>::and_then::h929eb9fc8e20a049
                               at /rustc/2f2c438dce75d8cc532c3baa849eeddc0901802c/library/core/src/result.rs:1319:22
  37:     0x7ff2859a360c - core::fmt::builders::DebugTuple::field::h3d7fca7c97960413
                               at /rustc/2f2c438dce75d8cc532c3baa849eeddc0901802c/library/core/src/fmt/builders.rs:309:35
  38:     0x7ff2859a7b1b - core::fmt::Formatter::debug_tuple_field1_finish::h4e6f73694bf6c84f
                               at /rustc/2f2c438dce75d8cc532c3baa849eeddc0901802c/library/core/src/fmt/mod.rs:2023:9
  39:     0x7ff284c64cea - <rustc_middle[232bd29a687eeda3]::ty::typeck_results::UserType as core[3afeaedfb140cde7]::fmt::Debug>::fmt
  40:     0x7ff2859a3379 - core::fmt::builders::DebugStruct::field::{{closure}}::h473ac448a7c4116a
                               at /rustc/2f2c438dce75d8cc532c3baa849eeddc0901802c/library/core/src/fmt/builders.rs:141:17
  41:     0x7ff2859a3379 - core::result::Result<T,E>::and_then::hbb9e091b5a5e90dc
                               at /rustc/2f2c438dce75d8cc532c3baa849eeddc0901802c/library/core/src/result.rs:1319:22
  42:     0x7ff2859a3379 - core::fmt::builders::DebugStruct::field::h4e3ae4a6f27f2d47
                               at /rustc/2f2c438dce75d8cc532c3baa849eeddc0901802c/library/core/src/fmt/builders.rs:124:35
  43:     0x7ff2859a7696 - core::fmt::Formatter::debug_struct_field3_finish::h38cd8cf3f886f443
                               at /rustc/2f2c438dce75d8cc532c3baa849eeddc0901802c/library/core/src/fmt/mod.rs:1911:9
  44:     0x7ff284cf81ed - <rustc_middle[232bd29a687eeda3]::infer::canonical::Canonical<rustc_middle[232bd29a687eeda3]::ty::typeck_results::UserType> as core[3afeaedfb140cde7]::fmt::Debug>::fmt
  45:     0x7ff2859a66ff - core::fmt::rt::Argument::fmt::ha5dde4cb71578cc2
                               at /rustc/2f2c438dce75d8cc532c3baa849eeddc0901802c/library/core/src/fmt/rt.rs:138:9
  46:     0x7ff2859a66ff - core::fmt::write::hb1413899fd777907
                               at /rustc/2f2c438dce75d8cc532c3baa849eeddc0901802c/library/core/src/fmt/mod.rs:1094:21
  47:     0x7ff284e79100 - <std[53b54636b4f52653]::io::buffered::bufwriter::BufWriter<std[53b54636b4f52653]::fs::File> as std[53b54636b4f52653]::io::Write>::write_fmt
  48:     0x7ff284c8fd4b - rustc_middle[232bd29a687eeda3]::mir::pretty::write_user_type_annotations
  49:     0x7ff284e587ee - rustc_middle[232bd29a687eeda3]::mir::pretty::dump_matched_mir_node::<rustc_mir_transform[bd425728c1433367]::pass_manager::dump_mir_for_phase_change::{closure#0}>
  50:     0x7ff283840fc6 - rustc_mir_transform[bd425728c1433367]::mir_const
  51:     0x7ff28383e853 - rustc_query_system[8be5ea0cc4c28ea6]::query::plumbing::try_execute_query::<rustc_query_impl[94005537e54250be]::queries::mir_const, rustc_query_impl[94005537e54250be]::plumbing::QueryCtxt>
  52:     0x7ff28383e4f5 - rustc_query_impl[94005537e54250be]::get_query::mir_const
  53:     0x7ff2836541a1 - rustc_mir_transform[bd425728c1433367]::mir_promoted
  54:     0x7ff28318dbea - rustc_query_system[8be5ea0cc4c28ea6]::query::plumbing::try_execute_query::<rustc_query_impl[94005537e54250be]::queries::mir_promoted, rustc_query_impl[94005537e54250be]::plumbing::QueryCtxt>
  55:     0x7ff28318cf5c - rustc_borrowck[2561add2bcb16522]::mir_borrowck
  56:     0x7ff28318b748 - rustc_query_system[8be5ea0cc4c28ea6]::query::plumbing::try_execute_query::<rustc_query_impl[94005537e54250be]::queries::mir_borrowck, rustc_query_impl[94005537e54250be]::plumbing::QueryCtxt>
  57:     0x7ff283bef386 - rustc_data_structures[fba7df231146955e]::sync::par_for_each_in::<&[rustc_span[811089187935bcb6]::def_id::LocalDefId], <rustc_middle[232bd29a687eeda3]::hir::map::Map>::par_body_owners<rustc_interface[1005215f39c21569]::passes::analysis::{closure#1}::{closure#0}>::{closure#0}>
  58:     0x7ff283be9f80 - rustc_interface[1005215f39c21569]::passes::analysis
  59:     0x7ff283f2bd47 - rustc_query_system[8be5ea0cc4c28ea6]::query::plumbing::try_execute_query::<rustc_query_impl[94005537e54250be]::queries::analysis, rustc_query_impl[94005537e54250be]::plumbing::QueryCtxt>
  60:     0x7ff283f2ba63 - rustc_query_impl[94005537e54250be]::get_query::analysis
  61:     0x7ff2839ccbcf - <rustc_middle[232bd29a687eeda3]::ty::context::GlobalCtxt>::enter::<rustc_driver_impl[27c68de0ac55b06a]::run_compiler::{closure#1}::{closure#2}::{closure#4}, core[3afeaedfb140cde7]::result::Result<(), rustc_span[811089187935bcb6]::ErrorGuaranteed>>
  62:     0x7ff2839cbcaf - <rustc_interface[1005215f39c21569]::interface::Compiler>::enter::<rustc_driver_impl[27c68de0ac55b06a]::run_compiler::{closure#1}::{closure#2}, core[3afeaedfb140cde7]::result::Result<core[3afeaedfb140cde7]::option::Option<rustc_interface[1005215f39c21569]::queries::Linker>, rustc_span[811089187935bcb6]::ErrorGuaranteed>>
  63:     0x7ff2839c933b - std[53b54636b4f52653]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[1005215f39c21569]::util::run_in_thread_pool_with_globals<rustc_interface[1005215f39c21569]::interface::run_compiler<core[3afeaedfb140cde7]::result::Result<(), rustc_span[811089187935bcb6]::ErrorGuaranteed>, rustc_driver_impl[27c68de0ac55b06a]::run_compiler::{closure#1}>::{closure#0}, core[3afeaedfb140cde7]::result::Result<(), rustc_span[811089187935bcb6]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[3afeaedfb140cde7]::result::Result<(), rustc_span[811089187935bcb6]::ErrorGuaranteed>>
  64:     0x7ff284098f55 - <<std[53b54636b4f52653]::thread::Builder>::spawn_unchecked_<rustc_interface[1005215f39c21569]::util::run_in_thread_pool_with_globals<rustc_interface[1005215f39c21569]::interface::run_compiler<core[3afeaedfb140cde7]::result::Result<(), rustc_span[811089187935bcb6]::ErrorGuaranteed>, rustc_driver_impl[27c68de0ac55b06a]::run_compiler::{closure#1}>::{closure#0}, core[3afeaedfb140cde7]::result::Result<(), rustc_span[811089187935bcb6]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[3afeaedfb140cde7]::result::Result<(), rustc_span[811089187935bcb6]::ErrorGuaranteed>>::{closure#1} as core[3afeaedfb140cde7]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  65:     0x7ff2859539d5 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h20fe0a24dda744f1
                               at /rustc/2f2c438dce75d8cc532c3baa849eeddc0901802c/library/alloc/src/boxed.rs:1985:9
  66:     0x7ff2859539d5 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hb11b4529d66356f4
                               at /rustc/2f2c438dce75d8cc532c3baa849eeddc0901802c/library/alloc/src/boxed.rs:1985:9
  67:     0x7ff2859539d5 - std::sys::unix::thread::Thread::new::thread_start::h896be1b4ceadbc98
                               at /rustc/2f2c438dce75d8cc532c3baa849eeddc0901802c/library/std/src/sys/unix/thread.rs:108:17
  68:     0x7ff281465bb5 - <unknown>
  69:     0x7ff2814e7d90 - <unknown>
  70:                0x0 - <unknown>

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.71.0-nightly (2f2c438dc 2023-05-08) running on x86_64-unknown-linux-gnu

note: compiler flags: -Z dump-mir=all

query stack during panic:
#0 [mir_const] preparing `ret_ref_local` for borrow checking
#1 [mir_promoted] promoting constants in MIR for `ret_ref_local`
#2 [mir_borrowck] borrow-checking `ret_ref_local`
#3 [analysis] running analysis passes on this crate
end of query stack
error: aborting due to previous error
```

</p>
</details>

### LINKED ISSUE #111397: ICE: `expected const for .. but found Type(..) when substituting`
### Code
`rustc treereduce.out -Zdump-mir=all`
```Rust
#![feature(inherent_associated_types, generic_const_exprs)]

struct Parent<const O: usize>;

impl<const O: usize> Parent<O> {
    type Mapping<const I: usize> = Store<{ O + I }>
    where
        [(); O + I]:
    ;
}

struct Store<const N: usize>;

impl<const N: usize> Store<N> {
    fn reify() -> usize {
        N
    }
}

fn main() {
    let _ = Parent::<1>::Mapping::<{ 2 * 5 }>::reify();
}

```

### Meta

`rustc --version --verbose`:
```
rustc 1.71.0-nightly (f7b831ac8 2023-05-09)
binary: rustc
commit-hash: f7b831ac8a897273f78b9f47165cf8e54066ce4b
commit-date: 2023-05-09
host: x86_64-unknown-linux-gnu
release: 1.71.0-nightly
LLVM version: 16.0.2
```

### Error output

```
<output>
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
warning: the feature `inherent_associated_types` is incomplete and may not be safe to use and/or cause compiler crashes
 --> treereduce.out:1:12
  |
1 | #![feature(inherent_associated_types, generic_const_exprs)]
  |            ^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: see issue #8995 <https://github.com/rust-lang/rust/issues/8995> for more information
  = note: `#[warn(incomplete_features)]` on by default

warning: the feature `generic_const_exprs` is incomplete and may not be safe to use and/or cause compiler crashes
 --> treereduce.out:1:39
  |
1 | #![feature(inherent_associated_types, generic_const_exprs)]
  |                                       ^^^^^^^^^^^^^^^^^^^
  |
  = note: see issue #76560 <https://github.com/rust-lang/rust/issues/76560> for more information

error: internal compiler error: compiler/rustc_middle/src/ty/subst.rs:920:9: expected const for `O/#0` (Const { ty: usize, kind: Param(O/#0) }/0) but found Type(Parent<1>) when substituting substs=[Parent<1>]

thread 'rustc' panicked at 'Box<dyn Any>', /rustc/f7b831ac8a897273f78b9f47165cf8e54066ce4b/compiler/rustc_errors/src/lib.rs:1650:9
stack backtrace:
   0:     0x7f4ad6b694d1 - std::backtrace_rs::backtrace::libunwind::trace::hf22881449f4c68af
                               at /rustc/f7b831ac8a897273f78b9f47165cf8e54066ce4b/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x7f4ad6b694d1 - std::backtrace_rs::backtrace::trace_unsynchronized::h417481a63a93417b
                               at /rustc/f7b831ac8a897273f78b9f47165cf8e54066ce4b/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7f4ad6b694d1 - std::sys_common::backtrace::_print_fmt::h5cc94e0371544b1c
                               at /rustc/f7b831ac8a897273f78b9f47165cf8e54066ce4b/library/std/src/sys_common/backtrace.rs:65:5
   3:     0x7f4ad6b694d1 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h6d4cf29c389416a4
                               at /rustc/f7b831ac8a897273f78b9f47165cf8e54066ce4b/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x7f4ad6bc987f - core::fmt::rt::Argument::fmt::h88c7f669523ab3d4
                               at /rustc/f7b831ac8a897273f78b9f47165cf8e54066ce4b/library/core/src/fmt/rt.rs:138:9
   5:     0x7f4ad6bc987f - core::fmt::write::hba6d4469c94dff09
                               at /rustc/f7b831ac8a897273f78b9f47165cf8e54066ce4b/library/core/src/fmt/mod.rs:1094:21
   6:     0x7f4ad6b5c731 - std::io::Write::write_fmt::h03fb3302511e0a07
                               at /rustc/f7b831ac8a897273f78b9f47165cf8e54066ce4b/library/std/src/io/mod.rs:1712:15
   7:     0x7f4ad6b692e5 - std::sys_common::backtrace::_print::h2774acb74125ebca
                               at /rustc/f7b831ac8a897273f78b9f47165cf8e54066ce4b/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x7f4ad6b692e5 - std::sys_common::backtrace::print::h24788cefb69f6c5e
                               at /rustc/f7b831ac8a897273f78b9f47165cf8e54066ce4b/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x7f4ad6b6bf77 - std::panicking::default_hook::{{closure}}::h83831eb75dbc7abb
  10:     0x7f4ad6b6bd64 - std::panicking::default_hook::haabe5769614bc6ad
                               at /rustc/f7b831ac8a897273f78b9f47165cf8e54066ce4b/library/std/src/panicking.rs:288:9
  11:     0x7f4ad9de6e9b - rustc_driver_impl[c6ed467a5333ba7a]::install_ice_hook::{closure#0}
  12:     0x7f4ad6b6c697 - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::hf6cbf19e675e5bec
                               at /rustc/f7b831ac8a897273f78b9f47165cf8e54066ce4b/library/alloc/src/boxed.rs:1999:9
  13:     0x7f4ad6b6c697 - std::panicking::rust_panic_with_hook::he447f218b926b874
                               at /rustc/f7b831ac8a897273f78b9f47165cf8e54066ce4b/library/std/src/panicking.rs:695:13
  14:     0x7f4ada2d56f1 - std[67990bb9926e756e]::panicking::begin_panic::<rustc_errors[65753a741d5cdd19]::ExplicitBug>::{closure#0}
  15:     0x7f4ada2d1ea6 - std[67990bb9926e756e]::sys_common::backtrace::__rust_end_short_backtrace::<std[67990bb9926e756e]::panicking::begin_panic<rustc_errors[65753a741d5cdd19]::ExplicitBug>::{closure#0}, !>
  16:     0x7f4ada2d1d96 - std[67990bb9926e756e]::panicking::begin_panic::<rustc_errors[65753a741d5cdd19]::ExplicitBug>
  17:     0x7f4ada2cc924 - <rustc_errors[65753a741d5cdd19]::HandlerInner>::bug::<alloc[7c1d58d8972e9afb]::string::String>
  18:     0x7f4ada2cc436 - <rustc_errors[65753a741d5cdd19]::Handler>::bug::<alloc[7c1d58d8972e9afb]::string::String>
  19:     0x7f4ada35926c - rustc_middle[6e1fd99800ba9ae7]::util::bug::opt_span_bug_fmt::<rustc_span[21b0d36d0183fdef]::span_encoding::Span>::{closure#0}
  20:     0x7f4ada358a3a - rustc_middle[6e1fd99800ba9ae7]::ty::context::tls::with_opt::<rustc_middle[6e1fd99800ba9ae7]::util::bug::opt_span_bug_fmt<rustc_span[21b0d36d0183fdef]::span_encoding::Span>::{closure#0}, !>::{closure#0}
  21:     0x7f4ada358a0a - rustc_middle[6e1fd99800ba9ae7]::ty::context::tls::with_context_opt::<rustc_middle[6e1fd99800ba9ae7]::ty::context::tls::with_opt<rustc_middle[6e1fd99800ba9ae7]::util::bug::opt_span_bug_fmt<rustc_span[21b0d36d0183fdef]::span_encoding::Span>::{closure#0}, !>::{closure#0}, !>
  22:     0x7f4ad80febfd - rustc_middle[6e1fd99800ba9ae7]::util::bug::bug_fmt
  23:     0x7f4ada2df002 - <rustc_middle[6e1fd99800ba9ae7]::ty::subst::SubstFolder>::const_param_expected
  24:     0x7f4ad7dac35a - <rustc_middle[6e1fd99800ba9ae7]::ty::subst::GenericArg as rustc_type_ir[6de004e23d25d05]::fold::TypeFoldable<rustc_middle[6e1fd99800ba9ae7]::ty::context::TyCtxt>>::try_fold_with::<rustc_middle[6e1fd99800ba9ae7]::ty::subst::SubstFolder>
  25:     0x7f4ad7daa056 - <rustc_middle[6e1fd99800ba9ae7]::ty::Ty as rustc_type_ir[6de004e23d25d05]::fold::TypeSuperFoldable<rustc_middle[6e1fd99800ba9ae7]::ty::context::TyCtxt>>::super_fold_with::<rustc_middle[6e1fd99800ba9ae7]::ty::subst::SubstFolder>
  26:     0x7f4ad801694b - <rustc_middle[6e1fd99800ba9ae7]::ty::print::pretty::FmtPrinter as rustc_middle[6e1fd99800ba9ae7]::ty::print::Printer>::print_def_path
  27:     0x7f4ad80162c6 - <rustc_middle[6e1fd99800ba9ae7]::ty::print::pretty::FmtPrinter as rustc_middle[6e1fd99800ba9ae7]::ty::print::Printer>::print_def_path
  28:     0x7f4ad801646c - <rustc_middle[6e1fd99800ba9ae7]::ty::print::pretty::FmtPrinter as rustc_middle[6e1fd99800ba9ae7]::ty::print::Printer>::print_def_path
  29:     0x7f4ad8013a2b - <rustc_middle[6e1fd99800ba9ae7]::ty::print::pretty::FmtPrinter as rustc_middle[6e1fd99800ba9ae7]::ty::print::pretty::PrettyPrinter>::pretty_print_type
  30:     0x7f4ad801302c - <rustc_middle[6e1fd99800ba9ae7]::ty::Ty as core[58897794ec39d39e]::fmt::Display>::fmt
  31:     0x7f4ada378fa8 - <rustc_middle[6e1fd99800ba9ae7]::ty::Ty as core[58897794ec39d39e]::fmt::Debug>::fmt
  32:     0x7f4ad6bc64f9 - core::fmt::builders::DebugStruct::field::{{closure}}::h1b5711af9127a301
                               at /rustc/f7b831ac8a897273f78b9f47165cf8e54066ce4b/library/core/src/fmt/builders.rs:141:17
  33:     0x7f4ad6bc64f9 - core::result::Result<T,E>::and_then::hf6cb78cbc9b86fd8
                               at /rustc/f7b831ac8a897273f78b9f47165cf8e54066ce4b/library/core/src/result.rs:1319:22
  34:     0x7f4ad6bc64f9 - core::fmt::builders::DebugStruct::field::h6d1f5b7ebb59c1db
                               at /rustc/f7b831ac8a897273f78b9f47165cf8e54066ce4b/library/core/src/fmt/builders.rs:124:35
  35:     0x7f4ad6bca75f - core::fmt::Formatter::debug_struct_field2_finish::h5a977166d5337886
                               at /rustc/f7b831ac8a897273f78b9f47165cf8e54066ce4b/library/core/src/fmt/mod.rs:1892:9
  36:     0x7f4ada2d90e8 - <&rustc_middle[6e1fd99800ba9ae7]::ty::subst::UserSelfTy as core[58897794ec39d39e]::fmt::Debug>::fmt
  37:     0x7f4ad6bc678c - core::fmt::builders::DebugTuple::field::{{closure}}::hd9f6bf7ecf71f62e
                               at /rustc/f7b831ac8a897273f78b9f47165cf8e54066ce4b/library/core/src/fmt/builders.rs:322:17
  38:     0x7f4ad6bc678c - core::result::Result<T,E>::and_then::hb7129ea632b5a35e
                               at /rustc/f7b831ac8a897273f78b9f47165cf8e54066ce4b/library/core/src/result.rs:1319:22
  39:     0x7f4ad6bc678c - core::fmt::builders::DebugTuple::field::he2df6437bada7158
                               at /rustc/f7b831ac8a897273f78b9f47165cf8e54066ce4b/library/core/src/fmt/builders.rs:309:35
  40:     0x7f4ad6bcac9b - core::fmt::Formatter::debug_tuple_field1_finish::h002916c2201e1156
                               at /rustc/f7b831ac8a897273f78b9f47165cf8e54066ce4b/library/core/src/fmt/mod.rs:2023:9
  41:     0x7f4ada342b57 - <&core[58897794ec39d39e]::option::Option<rustc_middle[6e1fd99800ba9ae7]::ty::subst::UserSelfTy> as core[58897794ec39d39e]::fmt::Debug>::fmt
  42:     0x7f4ad6bc64f9 - core::fmt::builders::DebugStruct::field::{{closure}}::h1b5711af9127a301
                               at /rustc/f7b831ac8a897273f78b9f47165cf8e54066ce4b/library/core/src/fmt/builders.rs:141:17
  43:     0x7f4ad6bc64f9 - core::result::Result<T,E>::and_then::hf6cb78cbc9b86fd8
                               at /rustc/f7b831ac8a897273f78b9f47165cf8e54066ce4b/library/core/src/result.rs:1319:22
  44:     0x7f4ad6bc64f9 - core::fmt::builders::DebugStruct::field::h6d1f5b7ebb59c1db
                               at /rustc/f7b831ac8a897273f78b9f47165cf8e54066ce4b/library/core/src/fmt/builders.rs:124:35
  45:     0x7f4ad6bca75f - core::fmt::Formatter::debug_struct_field2_finish::h5a977166d5337886
                               at /rustc/f7b831ac8a897273f78b9f47165cf8e54066ce4b/library/core/src/fmt/mod.rs:1892:9
  46:     0x7f4ada2d9148 - <&rustc_middle[6e1fd99800ba9ae7]::ty::subst::UserSubsts as core[58897794ec39d39e]::fmt::Debug>::fmt
  47:     0x7f4ad6bc678c - core::fmt::builders::DebugTuple::field::{{closure}}::hd9f6bf7ecf71f62e
                               at /rustc/f7b831ac8a897273f78b9f47165cf8e54066ce4b/library/core/src/fmt/builders.rs:322:17
  48:     0x7f4ad6bc678c - core::result::Result<T,E>::and_then::hb7129ea632b5a35e
                               at /rustc/f7b831ac8a897273f78b9f47165cf8e54066ce4b/library/core/src/result.rs:1319:22
  49:     0x7f4ad6bc678c - core::fmt::builders::DebugTuple::field::he2df6437bada7158
                               at /rustc/f7b831ac8a897273f78b9f47165cf8e54066ce4b/library/core/src/fmt/builders.rs:309:35
  50:     0x7f4ad6bcad78 - core::fmt::Formatter::debug_tuple_field2_finish::h3b28de4e053bb763
                               at /rustc/f7b831ac8a897273f78b9f47165cf8e54066ce4b/library/core/src/fmt/mod.rs:2039:9
  51:     0x7f4ada28c3e2 - <rustc_middle[6e1fd99800ba9ae7]::ty::typeck_results::UserType as core[58897794ec39d39e]::fmt::Debug>::fmt
  52:     0x7f4ad6bc64f9 - core::fmt::builders::DebugStruct::field::{{closure}}::h1b5711af9127a301
                               at /rustc/f7b831ac8a897273f78b9f47165cf8e54066ce4b/library/core/src/fmt/builders.rs:141:17
  53:     0x7f4ad6bc64f9 - core::result::Result<T,E>::and_then::hf6cb78cbc9b86fd8
                               at /rustc/f7b831ac8a897273f78b9f47165cf8e54066ce4b/library/core/src/result.rs:1319:22
  54:     0x7f4ad6bc64f9 - core::fmt::builders::DebugStruct::field::h6d1f5b7ebb59c1db
                               at /rustc/f7b831ac8a897273f78b9f47165cf8e54066ce4b/library/core/src/fmt/builders.rs:124:35
  55:     0x7f4ad6bca816 - core::fmt::Formatter::debug_struct_field3_finish::h6e1213564da9e75a
                               at /rustc/f7b831ac8a897273f78b9f47165cf8e54066ce4b/library/core/src/fmt/mod.rs:1911:9
  56:     0x7f4ada31f8ad - <rustc_middle[6e1fd99800ba9ae7]::infer::canonical::Canonical<rustc_middle[6e1fd99800ba9ae7]::ty::typeck_results::UserType> as core[58897794ec39d39e]::fmt::Debug>::fmt
  57:     0x7f4ad6bc987f - core::fmt::rt::Argument::fmt::h88c7f669523ab3d4
                               at /rustc/f7b831ac8a897273f78b9f47165cf8e54066ce4b/library/core/src/fmt/rt.rs:138:9
  58:     0x7f4ad6bc987f - core::fmt::write::hba6d4469c94dff09
                               at /rustc/f7b831ac8a897273f78b9f47165cf8e54066ce4b/library/core/src/fmt/mod.rs:1094:21
  59:     0x7f4ada4a06b0 - <std[67990bb9926e756e]::io::buffered::bufwriter::BufWriter<std[67990bb9926e756e]::fs::File> as std[67990bb9926e756e]::io::Write>::write_fmt
  60:     0x7f4ada2b740b - rustc_middle[6e1fd99800ba9ae7]::mir::pretty::write_user_type_annotations
  61:     0x7f4ada47ff1e - rustc_middle[6e1fd99800ba9ae7]::mir::pretty::dump_matched_mir_node::<rustc_mir_transform[31de03d9ff6cd65]::pass_manager::dump_mir_for_phase_change::{closure#0}>
  62:     0x7f4ad8e60b26 - rustc_mir_transform[31de03d9ff6cd65]::mir_const
  63:     0x7f4ad8e5e3b3 - rustc_query_system[d6abf6a541e94d]::query::plumbing::try_execute_query::<rustc_query_impl[9e8d88dd882a1237]::queries::mir_const, rustc_query_impl[9e8d88dd882a1237]::plumbing::QueryCtxt>
  64:     0x7f4ad8e5e055 - rustc_query_impl[9e8d88dd882a1237]::get_query::mir_const
  65:     0x7f4ad8c75a71 - rustc_mir_transform[31de03d9ff6cd65]::mir_promoted
  66:     0x7f4ad87bfdfa - rustc_query_system[d6abf6a541e94d]::query::plumbing::try_execute_query::<rustc_query_impl[9e8d88dd882a1237]::queries::mir_promoted, rustc_query_impl[9e8d88dd882a1237]::plumbing::QueryCtxt>
  67:     0x7f4ad87bf16c - rustc_borrowck[a0259e2eb90fe2e2]::mir_borrowck
  68:     0x7f4ad87bd958 - rustc_query_system[d6abf6a541e94d]::query::plumbing::try_execute_query::<rustc_query_impl[9e8d88dd882a1237]::queries::mir_borrowck, rustc_query_impl[9e8d88dd882a1237]::plumbing::QueryCtxt>
  69:     0x7f4ad9211946 - rustc_data_structures[e1401ea5d1349582]::sync::par_for_each_in::<&[rustc_span[21b0d36d0183fdef]::def_id::LocalDefId], <rustc_middle[6e1fd99800ba9ae7]::hir::map::Map>::par_body_owners<rustc_interface[aaea7ef87a85e665]::passes::analysis::{closure#1}::{closure#0}>::{closure#0}>
  70:     0x7f4ad920c540 - rustc_interface[aaea7ef87a85e665]::passes::analysis
  71:     0x7f4ad9555727 - rustc_query_system[d6abf6a541e94d]::query::plumbing::try_execute_query::<rustc_query_impl[9e8d88dd882a1237]::queries::analysis, rustc_query_impl[9e8d88dd882a1237]::plumbing::QueryCtxt>
  72:     0x7f4ad9555443 - rustc_query_impl[9e8d88dd882a1237]::get_query::analysis
  73:     0x7f4ad8fd4aaf - <rustc_middle[6e1fd99800ba9ae7]::ty::context::GlobalCtxt>::enter::<rustc_driver_impl[c6ed467a5333ba7a]::run_compiler::{closure#1}::{closure#2}::{closure#4}, core[58897794ec39d39e]::result::Result<(), rustc_span[21b0d36d0183fdef]::ErrorGuaranteed>>
  74:     0x7f4ad8fd3b8f - <rustc_interface[aaea7ef87a85e665]::interface::Compiler>::enter::<rustc_driver_impl[c6ed467a5333ba7a]::run_compiler::{closure#1}::{closure#2}, core[58897794ec39d39e]::result::Result<core[58897794ec39d39e]::option::Option<rustc_interface[aaea7ef87a85e665]::queries::Linker>, rustc_span[21b0d36d0183fdef]::ErrorGuaranteed>>
  75:     0x7f4ad8fd122b - std[67990bb9926e756e]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[aaea7ef87a85e665]::util::run_in_thread_pool_with_globals<rustc_interface[aaea7ef87a85e665]::interface::run_compiler<core[58897794ec39d39e]::result::Result<(), rustc_span[21b0d36d0183fdef]::ErrorGuaranteed>, rustc_driver_impl[c6ed467a5333ba7a]::run_compiler::{closure#1}>::{closure#0}, core[58897794ec39d39e]::result::Result<(), rustc_span[21b0d36d0183fdef]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[58897794ec39d39e]::result::Result<(), rustc_span[21b0d36d0183fdef]::ErrorGuaranteed>>
  76:     0x7f4ad96bbf95 - <<std[67990bb9926e756e]::thread::Builder>::spawn_unchecked_<rustc_interface[aaea7ef87a85e665]::util::run_in_thread_pool_with_globals<rustc_interface[aaea7ef87a85e665]::interface::run_compiler<core[58897794ec39d39e]::result::Result<(), rustc_span[21b0d36d0183fdef]::ErrorGuaranteed>, rustc_driver_impl[c6ed467a5333ba7a]::run_compiler::{closure#1}>::{closure#0}, core[58897794ec39d39e]::result::Result<(), rustc_span[21b0d36d0183fdef]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[58897794ec39d39e]::result::Result<(), rustc_span[21b0d36d0183fdef]::ErrorGuaranteed>>::{closure#1} as core[58897794ec39d39e]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  77:     0x7f4ad6b76b45 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h75a0f7a2d96fc847
                               at /rustc/f7b831ac8a897273f78b9f47165cf8e54066ce4b/library/alloc/src/boxed.rs:1985:9
  78:     0x7f4ad6b76b45 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h4f2621012beea0ce
                               at /rustc/f7b831ac8a897273f78b9f47165cf8e54066ce4b/library/alloc/src/boxed.rs:1985:9
  79:     0x7f4ad6b76b45 - std::sys::unix::thread::Thread::new::thread_start::h2acc7d12a3234e8d
                               at /rustc/f7b831ac8a897273f78b9f47165cf8e54066ce4b/library/std/src/sys/unix/thread.rs:108:17
  80:     0x7f4ad6913bb5 - <unknown>
  81:     0x7f4ad6995d90 - <unknown>
  82:                0x0 - <unknown>

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.71.0-nightly (f7b831ac8 2023-05-09) running on x86_64-unknown-linux-gnu

note: compiler flags: -Z dump-mir=all

query stack during panic:
#0 [mir_const] preparing `main` for borrow checking
#1 [mir_promoted] promoting constants in MIR for `main`
#2 [mir_borrowck] borrow-checking `main`
#3 [analysis] running analysis passes on this crate
end of query stack
error: aborting due to previous error; 2 warnings emitted
```

</p>
</details>

### PR DESCRIPTION
**Pull request by fmease**
Previously, we were trying to pretty-print inherent projections with `Printer::print_def_path` which is incorrect since
it expects the substitutions to be of a certain format (parents substs followed by own substs) which doesn't hold for
inherent projections (self type subst followed by own substs).
Now we print inherent projections manually.

Fixes #111390.
Fixes #111397.

Lacking tests! Is there a test suite / compiletest flags for the pretty-printer? In most if not all cases,
inherent projections are normalized away before they get the chance to appear in diagnostics.

If I were to create regression tests for linked issues, they would need to be `mir-opt` tests to exercise
`-Zdump-mir=all` (right?) which doesn't feel quite adequate to me.

@rustbot label F-inherent_associated_types

### CODE REVIEW

File: compiler/rustc_middle/src/ty/print/mod.rs [hunk 1]
```diff
@@ -128,16 +129,27 @@ pub trait Printer<'tcx>: Sized {
...
             }
 
-            _ => {
+            def_path_data => {
                 let parent_def_id = DefId { index: key.parent.unwrap(), ..def_id };
 
+                // Inherent projections
+                if let DefPathData::TypeNs(_) = def_path_data
+                    && let DefKind::Impl { of_trait: false } = self.tcx().def_kind(parent_def_id)
+                    && let Some(self_ty) = substs.get(0).and_then(|subst| subst.as_type())
```
Comment (fmease) [inline compiler/rustc_middle/src/ty/print/mod.rs:138]: In some cases the substs only contains consts or are empty which surprised me quite a bit.
This seems to happen when we print anon consts (which I'm not that familiar with).

E.g. for `<impl at dump_mir_1.rs:5:1: 5:31>::Mapping::{constant#0}`, the substs were empty or for
`Parent::<1>::Mapping::<{ 2 * 5 }>::{constant#0}` the substs were `[Const { ty: usize, kind: Value(Leaf(0x0000000000000001)) }, Const { ty: usize, kind: Value(Leaf(0x000000000000000a)) }]`.

I guess this is how anon consts are encoded. Their “encoding” shouldn't be able to clash with the
one of inherent projections though I would judge.

Comment (fmease) [reply compiler/rustc_middle/src/ty/print/mod.rs:138]: Ah, ok. For the `[Const, Const]` case, the 1st const embodies the parent substs (here for `Parent`) and the 2nd one corresponds to the GAT substs. Makes sense

**Comment by fmease** [comment]
This isn't the correct approach

**Comment by fmease** [comment]
I've changed the approach (over at fmease/rust#4, you can see an explanation why the previous one wasn't correct).

File: compiler/rustc_middle/src/ty/print/pretty.rs [hunk 2]
```diff
@@ -2821,7 +2838,11 @@ define_print_and_forward_display! {
     }
 
     ty::AliasTy<'tcx> {
-        p!(print_def_path(self.def_id, self.substs));
+        if self.kind(cx.tcx()) == ty::Inherent {
```
Comment (fmease) [inline compiler/rustc_middle/src/ty/print/pretty.rs:2841]: It's intentional that I do this check here in the `AliasTy` branch instead of removing `ty::Inherent` from the
match arm `ty::Alias(ty::Projection | ty::Inherent, ref data)` in fn `pretty_print_type` moving it into a new arm
`ty::Alias(ty::Inherent, ref alias_ty)`.

If someone wants to print a bare `AliasTy` that represents an inh proj, then it would just work instead of ICEing.
This case is probably quite rare compared to printing the corresp. `Ty` but let's be robust.

File: compiler/rustc_middle/src/ty/print/pretty.rs [hunk 3]
```diff
@@ -2821,7 +2838,11 @@ define_print_and_forward_display! {
     }
 
     ty::AliasTy<'tcx> {
-        p!(print_def_path(self.def_id, self.substs));
+        if let DefKind::Impl { of_trait: false } = cx.tcx().def_kind(cx.tcx().parent(self.def_id)) {
```
Comment (fmease) [inline compiler/rustc_middle/src/ty/print/pretty.rs:2841]: I'm no longer using `AliasTy::kind()` here since it ICEs on `AssocConst`s. `AliasTy`s can actually be `AssocConst`s for associated const projections even though it's not properly documented anywhere as I assume it to be a temporary hack to make `#![feature(associated_const_equality)]` work until `AliasTerm` is introduced.

**Comment by fmease** [comment]
Alright, now it should be ready for review! Apologies for the spam. I've added some `bug!()`s for some `ty::Alias(ty::Inherent, _)` match arms that shouldn't be reachable in practice which previously would've called `print_def_path` on an inherent projections which strictly speaking wouldn't be correct.

If those cases are every reached (which I don't believe) the proper solution would be to uplift `pretty_print_inherent_projection` from `PrettyPrinter` to `Printer`, to rename it & and to call it instead. I'm not doing that rn since it'd require a bit of boilerplate w/o any obvious benefit.

**Comment by petrochenkov** [comment]
r=me after writing a more readable commit message
@rustbot author
