### PR TITLE
Accept underscores in unicode escapes

### LINKED ISSUE #43692: Allow underscores in unicode escapes
Underscores are supported in all numeric types in Rust, and a recent clippy update actually warns on not using underscores for long numbers.

However, underscores are not supported for Unicode Escape literals. Therefore, it is not possible to write the first character of the 16th plane as `\u{10_0000}`, while `\u{100000}` is not easy to read and can be misread as `\u{10000}`.

At the moment, underscore results in an error like this:
```rust
error: invalid character in unicode escape: _
  --> unic/tests/basics_test.rs:31:23
   |
31 |         Age::of('\u{10_FFFF}'),
   |                       ^
```
meaning that there's no backward-compatibility issue and supporting underscores would be a compatible enhancement.

Unicode already has clear definition of Planes, numbered 0 to 16, which hint to write literals as `\u{<plane>_<4-hex-digits>}` sequences.

Optionally, we can opt-in to only allow underscore in a specific position, like the aforementioned format. But I think that would just make it too complicate for no apparent reason. Such a check could be a clippy rule, of course.

What do you think?

### PR DESCRIPTION
**Pull request by MaloJaffre**
Fixes #43692.

I don't know if this need an RFC, but at least the impl is here!

### CODE REVIEW

File: src/libsyntax/parse/lexer/mod.rs [hunk 1]
```diff
@@ -963,10 +963,10 @@ impl<'a> StringReader<'a> {
         true
     }
 
-    /// Scan over a \u{...} escape
+    /// Scan over a `\u{...}` escape with `_` separators
     ///
-    /// At this point, we have already seen the \ and the u, the { is the current character. We
-    /// will read at least one digit, and up to 6, and pass over the }.
+    /// At this point, we have already seen the `\` and the `u`, the `{` is the current character. We
```
Comment (kennytm) [inline src/libsyntax/parse/lexer/mod.rs]: The CI is unhappy with this line because it is too long 🙂 

```
[00:03:14] tidy error: /checkout/src/libsyntax/parse/lexer/mod.rs:968: line longer than 100 chars
[00:03:15] some tidy checks failed
```

**Comment by kennytm** [comment]
`issue-43692.rs` should be a **run-pass** test, not a **compile-fail** test. It should check (`assert_eq`) if `'\u{10__FFFF}'` and `"\u{10_F0FF}foo\u{1_0_0_0}"` are equivalent to their no-underscore counterparts.

**Comment by petrochenkov** [comment]
@SimonSapin what do you think about this?

Also ping @rust-lang/lang
This probably doesn't need a full RFC, but certainly will need an FCP.

**Comment by SimonSapin** [comment]
Making numeric escape sequences consistent with integer literals makes sense to me. 👍

**Comment by joshtriplett** [comment]
Please don't allow prefixes or suffixes, but otherwise this seems like a great idea.

**Comment by petrochenkov** [comment]
@MaloJaffre 
Could you somehow share the lexing code between unicode escapes and normal hexadecimal literals to ensure the rules are identical?
For example, `scan_digits` can be reused for unicode escapes.
Unicode escapes are more restrictive, but the restrictions could be enforced after a unicode escape is lexed (this can also give better error reporting and recovery).

**Comment by MaloJaffre** [comment]
Thanks for the suggestion @petrochenkov.
I have also rebased on master.

File: src/libsyntax/parse/lexer/mod.rs [hunk 2]
```diff
@@ -963,60 +963,67 @@ impl<'a> StringReader<'a> {
...
             self.err_span_(start_bpos,
                            self.pos,
-                           "overlong unicode escape (can have at most 6 hex digits)");
+                           "overlong unicode escape (must have at most 6 hex digits)");
             valid = false;
         }
+        loop {
+            match self.ch {
+                Some('}') => {
+                    if valid && count == 0 {
```
Comment (petrochenkov) [inline src/libsyntax/parse/lexer/mod.rs]: `if count == 0` would give the same result

File: src/libsyntax/parse/lexer/mod.rs [hunk 3]
```diff
@@ -963,60 +963,67 @@ impl<'a> StringReader<'a> {
...
+                    if c == delim {
+                        self.err_span_(self.pos,
+                                       self.pos,
+                                       "unterminated unicode escape (needed a `}`)");
+                        break;
+                    } else {
+                        self.err_span_char(start_bpos,
+                                           self.pos,
+                                           "invalid character in unicode escape",
+                                           c);
```
Comment (petrochenkov) [inline src/libsyntax/parse/lexer/mod.rs]: This error can now be reported *a lot* of times in case of unterminated unicode escapes.
It probably should be reported only the first time.

File: src/libsyntax/parse/mod.rs [hunk 4]
```diff
@@ -230,37 +239,52 @@ pub fn stream_to_parser(sess: &ParseSess, stream: TokenStream) -> Parser {
...
+                let s = lit.chars().filter(|&c| c != '_').collect::<String>();
+                let v = u32::from_str_radix(&s, 16).unwrap();
+                match char::from_u32(v) {
+                    Some(c) => Some(c),
+                    None => {
+                        err!(diag, |span, diag| {
+                            diag.struct_span_err(span, "invalid unicode character escape")
+                                .help("unicode escape must be at most 10FFFF")
+                                .emit();
+                                None
```
Comment (petrochenkov) [inline src/libsyntax/parse/mod.rs]: I think you can avoid an changing the return type to option here and just return something like [Replacement character](https://en.wikipedia.org/wiki/Specials_(Unicode_block)#Replacement_character) `U+FFFD`.

File: src/libsyntax/parse/lexer/mod.rs (hunk 2 above)
Comment (MaloJaffre) [inline src/libsyntax/parse/lexer/mod.rs]: No, because in the case `\u{#}`, we don't want to say that the escape is empty, so we check there was no invalid characters before.

Comment (petrochenkov) [inline src/libsyntax/parse/lexer/mod.rs]: Ah, right, this is in a loop, okay then.

**Comment by petrochenkov** [comment]
Implementation LGTM, modulo comments.

@rfcbot fcp merge

**Comment by petrochenkov** [comment]
I have no rights for @rfcbot, could someone start an FCP?

File: src/libsyntax/parse/mod.rs (hunk 4 above)
Comment (petrochenkov) [inline src/libsyntax/parse/mod.rs]: @MaloJaffre 
Could you also squash commits after updating the PR?

Comment (MaloJaffre) [inline src/libsyntax/parse/mod.rs]: Thanks for the review @petrochenkov!
Ok, I will do another round of changes and squash everything.

**Comment by MaloJaffre** [comment]
Squashed, I've also added a more precise help message for surrogates.

**Review by petrochenkov — APPROVED** [review]

**Comment by MaloJaffre** [comment]
Friendly ping @rust-lang/lang, to start a FCP, if there are no concerns about the implementation.

**Comment by petrochenkov** [comment]
@MaloJaffre 
There's one more thing that I forgot about - this needs a feature gate (unless the lang team decides it doesn't), `#[feature(unicode_escape_underscores)]` or something.
See https://github.com/rust-lang/rust/pull/37547/commits/50ecee241008a17a3d296f0a0d2a4ff9080a5c57 for an example of how to add it.

**Comment by SimonSapin** [comment]
I think this is fine without a feature gate.

**Comment by SimonSapin** [comment]
I think this is fine without a feature gate. (Though I’m not in any time that would make that decision.)

**Comment by aturon** [comment]
@rfcbot fcp merge

File: src/libsyntax/parse/lexer/mod.rs [hunk 5]
```diff
@@ -963,60 +963,67 @@ impl<'a> StringReader<'a> {
...
-                                       "invalid character in unicode escape",
-                                       c);
-                }
-                valid = false;
-                0
-            });
-            self.bump();
-            count += 1;
+        if let Some('_') = self.ch {
+            // disallow leading `_`
```
Comment (pnkfelix) [inline src/libsyntax/parse/lexer/mod.rs]: do we need a `compile-fail` test checking that leading `_` is disallowed?

Comment (MaloJaffre) [reply src/libsyntax/parse/lexer/mod.rs]: There is already a `parse-fail` test that checks that, do I need to move it to `compile-fail`?

**Comment by petrochenkov** [comment]
>The final comment period is now complete.

@bors r+

**Comment by chris-morgan** [comment]
It is worth noting that most syntax highlighters will need updating to support this.

We need something like a mailing list for syntax highlighters where syntax changes can be announced.
