### PR TITLE
Ensure nested statics have a HIR node to prevent various queries from ICEing

### LINKED ISSUE #3389: ICE: hir: index out of bounds
I suspect this is related to https://github.com/rust-lang/rust/issues/122399.

I pushed a minimal test case to https://github.com/andyleiserson/miri/commit/4c9d9ac10667aee405c5cf6be262f772c182e9d7. I'm including the content of the test case below. But to get the issue to reproduce, I had to add it as a crate in test-cargo-miri -- adding it as a regular test was not sufficient. My original repro (from which I distilled this test case) was `git clone -b v0.12.1 https://github.com/rustls/rcgen.git && cd rcgen && cargo +nightly miri test`.

```
const OID_RSA_ENCRYPTION: &[u64] = &[1, 2, 840, 113549, 1, 1, 1];

pub struct SignatureAlgorithm {
    pub oids: &'static [&'static [u64]],
}

pub static PKCS_RSA_SHA256: SignatureAlgorithm = SignatureAlgorithm {
    // Does not repro with this constant inlined.
    oids: &[&OID_RSA_ENCRYPTION],
};
```

The observed behavior is an ICE (reported as stderr mismatch when running run-test.py):
```
thread 'rustc' panicked at /rustc/a615cea3339046c7ab2d75cd253727d1fd42dd0b/compiler/rustc_middle/src/hir/mod.rs:157:84:
index out of bounds: the len is 7 but the index is 7
```

The ICE also includes the following context:
```
query stack during panic:
#0 [local_def_id_to_hir_id] getting HIR ID of `PKCS_RSA_SHA256::{constant#0}`
#1 [exported_symbols] collecting exported symbols for crate `0`
end of query stack
``` 

[rustc-ice-2024-03-18T21_21_30-94784.txt](https://github.com/rust-lang/miri/files/14644584/rustc-ice-2024-03-18T21_21_30-94784.txt)

### PR DESCRIPTION
**Pull request by oli-obk**
fixes https://github.com/rust-lang/miri/issues/3389

### CODE REVIEW

**Comment by RalfJung** [comment]
Does that test repo the issue? The reporter wrote

> But to get the issue to reproduce, I had to add it as a crate in test-cargo-miri -- adding it as a regular test was not sufficient.

**Comment by oli-obk** [comment]
oh fun. I didn't check.

**Comment by oli-obk** [comment]
I removed the test. The change is useful on its own. We should always have HIR available for all `DefId`s

**Comment by RalfJung** [comment]
Will this also fix the codegen ICEs related to nested statics?

**Comment by oli-obk** [comment]
no, just make better ICEs

File: compiler/rustc_hir/src/hir.rs [hunk 1]
```diff
@@ -3531,7 +3526,8 @@ pub enum Node<'hir> {
     WhereBoundPredicate(&'hir WhereBoundPredicate<'hir>),
     // FIXME: Merge into `Node::Infer`.
     ArrayLenInfer(&'hir InferArg),
-    AssocOpaqueTy(&'hir AssocOpaqueTy),
+    // Created by query feeding
+    Synthetic,
```
Comment (petrochenkov) [inline compiler/rustc_hir/src/hir.rs:3530]: In https://github.com/rust-lang/rust/pull/120206 and https://github.com/rust-lang/rust/pull/120943 I specifically wanted to avoid having a non-specific "dummy" node kind.
If we have some `HirId` or `DefId` then it's better to know whether it refers to an associated opaque type, or implicit static, or some specific non-synthesized HIR node, at least for debugging.

Comment (oli-obk) [reply compiler/rustc_hir/src/hir.rs:3530]: I can give it a field where we can encode the kind of synthetic node that we have here. Then it can be handled the same everywhere and get custom handling where desirable

We usually can get this information by asking for the `DefId` and then the `DefKind`, but that's not always immediately there I guess

**Review by fee1-dead — APPROVED** [review]
LGTM. FWIW, I don't think it is necessary to add any info that distinguishes nested statics from associated types coming from RPITITs, since the `def_kind` already has it, and we rarely print the HIR after the queries are fed.

r=me
