### PR TITLE
[MSP430] Do not generate '@' character in symbol names.

### LINKED ISSUE #38116: MSP430, unrecognized character `@' in symbol names.
So I tried to compile core and I get this errors from assembler:

```
core.s: Assembler messages:
core.s:9468: Error: junk at end of line, first unrecognized character is `@'
core.s:9740: Error: junk at end of line, first unrecognized character is `@'
...
```

the code on line 9468 looks like this:

``` asm
_ZN4core3num7dec2flt5rawfp10prev_float14_MSG_FILE_LINE17h5bcd06a3b0d78233E:
    .short  str.3@
    .short  27
    .short  str.1v
```

I tried both `msp430-gcc` (4.6.3) and `msp430-elf-gcc` (5.3.0) and both give the same errors. Then I've renamed symbol `str.3@` to `str.3_at` in assembly and it compiled successfully. I think msp430 assembler just does not like `@` character in symbol names. So I see 2 options:
1. Modify MSP430 target in LLVM so it will rename symbols with `@`
2. Modify [`generate_local_symbol_name`](https://github.com/rust-lang/rust/blob/bb35d50cad5f452e80ff88ee957962966c28a9f6/src/librustc_trans/context.rs#L961) to not emit `@` on MSP430

### PR DESCRIPTION
**Pull request by pftbest**
MSP430 assembler does not like '@' character in symbol names, so we need
to replace it with some other character.

Fixes #38116

### CODE REVIEW

**Comment by japaric** [comment]
cc @eddyb @michaelwoerister you may have some thoughts about this. I don't know if having a single target that uses a different format for symbol names would cause problems in debuginfo or incr. compilation or somewhere else.

This target, msp430, is a little weird though because llvm can't generate object files for it so we are making llvm emit assembly (.s files) and then converting those into object files using gcc (msp430-gcc). So ... I think that means we can't even embed debuginfo into the object file in the first place (?).

File: src/librustc_trans/context.rs [hunk 1]
```diff
@@ -967,6 +967,12 @@ impl<'b, 'tcx> CrateContext<'b, 'tcx> {
         name.push_str(prefix);
         name.push_str(".");
         base_n::push_str(idx as u64, base_n::MAX_BASE, &mut name);
+
+        // MSP430 assembler does not like '@' character in symbol names.
+        if self.sess().target.target.arch == "msp430" {
+            name = str::replace(&name[..], "@", "_");
```
Comment (eddyb) [inline src/librustc_trans/context.rs]: Where does the `@` even come from? `prefix`?

Comment (eddyb) [inline src/librustc_trans/context.rs]: Aaaah. What is even `MAX_BASE`? FWIW `@` is one of the characters we "escape" in symbols, on all targets.
So we don't actually consider it safe enough to use, although here it doesn't matter as much because it's unexported.

Another question nagging me is: do we really need this function? LLVM can handle multiple definitions with no name or with the same "informative" name without us needing to keep our own counters. Where are we keeping these `String`s generated here, and if they're stored in `CrateContext`, why isn't the `ValueRef` kept instead?

Comment (michaelwoerister) [inline src/librustc_trans/context.rs]: The function could probably be refactored away, yes.

As to MAX_BASE and `@`: Using a base64 encoding for the counter was an attempt to keep IR small after people complaining that it was too big. An unnecessary optimization as it turned out because it made no real difference.

**Review by michaelwoerister — COMMENTED** [review]
Thanks for the PR!

Since the counter containing the `@` is something purely cosmetic this could also easily be handled consistently for all platforms. My suggestion would be:

- Add a `pub const ALPHA_NUMERIC_ONLY = 62` to `base_n` ...
- ... and use that instead of `MAX_BASE` in `generate_local_symbol_name`.

@pftbest, would you mind adapting the PR in this way?

**Comment by pftbest** [comment]
@michaelwoerister Updated the PR

**Comment by michaelwoerister** [comment]
@bors r+

Thanks, @pftbest, that should do the trick `:)`
