### PR TITLE
consider item bounds for non-yet-defined opaque types

### LINKED ISSUE #182: reblessive regression
```
async fn mirror<T>(t: T) -> T {
    let x = Box::pin(mirror(String::new())).await;
    let recur = x.len();
    
    t
}
```

Recursive non-defining use. Old solver can solve `{opaque#0}::<String>: Future<Output = ?x>` and constrains the type of variable `x`.

### LINKED ISSUE #196: poem: normalization of not-yet-defined opaques using blanket impls
```rust
[INFO] [stdout] error[E0282]: type annotations needed
[INFO] [stdout]    --> /opt/rustwide/cargo-home/registry/src/index.crates.io-1949cf8c6b5b557f/poem-3.0.4/src/route/router_method.rs:186:33
[INFO] [stdout]     |
[INFO] [stdout] 186 | ...                   let mut resp = self.call(req).await?;
[INFO] [stdout]     |                           ^^^^^^^^
[INFO] [stdout] 187 | ...                   resp.set_body(());
[INFO] [stdout]     |                            -------- type must be known at this point
[INFO] [stdout]     |
[INFO] [stdout] help: consider giving `resp` an explicit type
[INFO] [stdout]     |
[INFO] [stdout] 186 |                             let mut resp: /* Type */ = self.call(req).await?;
[INFO] [stdout]     |                                         ++++++++++++
[INFO] [stdout] 
[INFO] [stdout] 
[INFO] [stdout] error[E0271]: type mismatch resolving `impl Future<Output = Result<<RouteMethod as Endpoint>::Output, Error>> + Send normalizes-to _`
[INFO] [stdout]    --> /opt/rustwide/cargo-home/registry/src/index.crates.io-1949cf8c6b5b557f/poem-3.0.4/src/route/router_method.rs:186:44
[INFO] [stdout]     |
[INFO] [stdout] 186 | ...                   let mut resp = self.call(req).await?;
[INFO] [stdout]     |                                      ^^^^^^^^^^^^^^ types differ
[INFO] [stdout] 
```

### LINKED ISSUE #205: `cedar-policy-2.4.2`: type error when applying the `?` operator
```
[INFO] [stdout] error[E0277]: `?` couldn't convert the error to `serde_json::Error`
[INFO] [stdout]     --> /opt/rustwide/cargo-home/registry/src/index.crates.io-1949cf8c6b5b557f/cedar-policy-2.4.2/src/api.rs:1410:76
[INFO] [stdout]      |
[INFO] [stdout] 1410 |             parsed.into_euid(|| JsonDeserializationErrorContext::EntityUid)?,
[INFO] [stdout]      |                    --------------------------------------------------------^ the trait `From<cedar_policy_core::entities::JsonDeserializationError>` is not implemented for `serde_json::Error`
[INFO] [stdout]      |                    |
[INFO] [stdout]      |                    this can't be annotated with `?` because it has type `Result<_, cedar_policy_core::entities::JsonDeserializationError>`
[INFO] [stdout]      |
[INFO] [stdout]      = note: the question mark operation (`?`) implicitly performs a conversion on the error value using the `From` trait
[INFO] [stdout] 
[INFO] [stdout] 
[INFO] [stdout] error[E0308]: mismatched types
[INFO] [stdout]     --> /opt/rustwide/cargo-home/registry/src/index.crates.io-1949cf8c6b5b557f/cedar-policy-2.4.2/src/api.rs:1409:9
[INFO] [stdout]      |
[INFO] [stdout] 1406 |       pub fn from_json(json: serde_json::Value) -> Result<Self, impl std::error::Error> {
[INFO] [stdout]      |                                                    ------------------------------------ expected `Result<api::EntityUid, impl StdError>` because of return type
[INFO] [stdout] ...
[INFO] [stdout] 1409 | /         Ok::<Self, entities::JsonDeserializationError>(Self(
[INFO] [stdout] 1410 | |             parsed.into_euid(|| JsonDeserializationErrorContext::EntityUid)?,
[INFO] [stdout] 1411 | |         ))
[INFO] [stdout]      | |__________^ types differ
[INFO] [stdout]      |
[INFO] [stdout]      = note: expected enum `Result<_, serde_json::Error>`
[INFO] [stdout]                 found enum `Result<_, cedar_policy_core::entities::JsonDeserializationError>`
```

### PR DESCRIPTION
**Pull request by lcnr**
Based on rust-lang/rust#140405.

fixes https://github.com/rust-lang/trait-system-refactor-initiative/issues/182
fixes https://github.com/rust-lang/trait-system-refactor-initiative/issues/196
fixes https://github.com/rust-lang/trait-system-refactor-initiative/issues/205

there's some jank here, see https://github.com/rust-lang/trait-system-refactor-initiative/issues/229

## Design

If the self type is an inference variable which has been sub-unified with am opaque type, we need to incompletely guide inference to avoid breakage.

In this case, we
- look at the item bounds of all sub-unified opaque types, and
- blanket impls which do not constrain the self type

Even if there are applicable candidates, we always force their certainty to be `Maybe`, so they will always have to be reproven once we've constrained the inference variable.

This is a bit iffy, see the added tests. 

r? @BoxyUwU

### CODE REVIEW

File: tests/ui/impl-trait/non-defining-uses/whatever-this-is.rs [hunk 1]
```diff
@@ -0,0 +1,32 @@
...
+
+fn should_be_ambig<T, U>(x: U) -> impl IntoIterator<T, Item = u32>
+where
+    U: IntoIterator<T, Item = u32> + Copy + IntoIterator<(), Item = u32> + Copy,
+{
+    // `<opaque<?t, U> as IntoIterator<()>>::Assoc
+    assoc(should_be_ambig(x)).count_zeros();
+    x
+}
+fn main() {}
```
Comment (lcnr) [inline tests/ui/impl-trait/non-defining-uses/whatever-this-is.rs]: need to rename this test, still unsure whether to support this :thinking:

File: compiler/rustc_next_trait_solver/src/solve/assembly/mod.rs [hunk 2]
```diff
@@ -187,6 +188,7 @@ where
         ecx: &mut EvalCtxt<'_, D>,
         goal: Goal<I, Self>,
         impl_def_id: I::ImplId,
+        finalize: impl FnOnce(&mut EvalCtxt<'_, D>, Certainty) -> QueryResult<I>,
```
Comment (lcnr) [inline compiler/rustc_next_trait_solver/src/solve/assembly/mod.rs]: `then` vs `finalize` :< naming

File: compiler/rustc_next_trait_solver/src/solve/eval_ctxt/mod.rs [hunk 3]
```diff
@@ -1176,6 +1180,33 @@ where
     ) -> bool {
         may_use_unstable_feature(&**self.delegate, param_env, symbol)
     }
+
+    pub(crate) fn find_sup_as_registered_opaque(
```
Comment (lcnr) [inline compiler/rustc_next_trait_solver/src/solve/eval_ctxt/mod.rs]: `fn opaque_types_with_sub_unified_hidden_type`

File: compiler/rustc_next_trait_solver/src/solve/assembly/mod.rs [hunk 4]
```diff
@@ -943,6 +957,110 @@ where
...
+    /// impls. This is used to incompletely guide type inference when handling
+    /// non-defining uses in the defining scope.
+    ///
+    /// We otherwise just fail fail with ambiguity. Even if we're using an
+    /// opaque type item bound or a blank impls, we still force its certainty
+    /// to be `Maybe` so that we properly prove this goal later.
+    ///
+    /// See <https://github.com/rust-lang/trait-system-refactor-initiative/issues/182>
+    /// for why this is necessary.
+    fn try_assemble_bounds_via_registered_opaque<G: GoalKind<D>>(
```
Comment (lcnr) [inline compiler/rustc_next_trait_solver/src/solve/assembly/mod.rs]: opaques!

File: compiler/rustc_next_trait_solver/src/solve/assembly/mod.rs [hunk 5]
```diff
@@ -943,6 +957,110 @@ where
...
+        &mut self,
+        goal: Goal<I, G>,
+        assemble_from: AssembleCandidatesFrom,
+        candidates: &mut Vec<Candidate<I>>,
+    ) {
+        let self_ty = goal.predicate.self_ty();
+        let mut is_hidden_type_of_alias = false;
+        for alias_ty in self.find_sup_as_registered_opaque(self_ty) {
```
Comment (lcnr) [inline compiler/rustc_next_trait_solver/src/solve/assembly/mod.rs]: needs test where a var is sub unified with multiple opaque types :3

File: compiler/rustc_next_trait_solver/src/solve/assembly/mod.rs [hunk 6]
```diff
@@ -943,6 +957,110 @@ where
...
+    /// See <https://github.com/rust-lang/trait-system-refactor-initiative/issues/182>
+    /// for why this is necessary.
+    fn try_assemble_bounds_via_registered_opaque<G: GoalKind<D>>(
+        &mut self,
+        goal: Goal<I, G>,
+        assemble_from: AssembleCandidatesFrom,
+        candidates: &mut Vec<Candidate<I>>,
+    ) {
+        let self_ty = goal.predicate.self_ty();
+        let mut is_hidden_type_of_alias = false;
```
Comment (lcnr) [inline compiler/rustc_next_trait_solver/src/solve/assembly/mod.rs]: rename to `assemble_blanket_impls`

File: compiler/rustc_next_trait_solver/src/solve/assembly/mod.rs [hunk 7]
```diff
@@ -943,6 +957,110 @@ where
...
+            // in a `?x: Trait<u32>` alias-bound candidate.
+            for item_bound in self
+                .cx()
+                .item_self_bounds(alias_ty.def_id)
+                .iter_instantiated(self.cx(), alias_ty.args)
+            {
+                let assumption =
+                    item_bound.fold_with(&mut ReplaceOpaque { cx: self.cx(), alias_ty, self_ty });
+                // We want to reprove this goal once we've inferred the hidden type,
+                // so we force the certainty to `Maybe`.
```
Comment (lcnr) [inline compiler/rustc_next_trait_solver/src/solve/assembly/mod.rs]: move into the closure

File: compiler/rustc_next_trait_solver/src/solve/assembly/mod.rs [hunk 8]
```diff
@@ -943,6 +957,110 @@ where
...
+        // See tests/ui/impl-trait/non-defining-uses/use-blanket-impl.rs for an example.
+        if is_hidden_type_of_alias && assemble_from.should_assemble_impl_candidates() {
+            let cx = self.cx();
+            cx.for_each_blanket_impl(goal.predicate.trait_def_id(cx), |impl_def_id| {
+                // For every `default impl`, there's always a non-default `impl`
+                // that will *also* apply. There's no reason to register a candidate
+                // for this impl, since it is *not* proof that the trait goal holds.
+                if cx.impl_is_default(impl_def_id) {
+                    return;
+                }
```
Comment (lcnr) [inline compiler/rustc_next_trait_solver/src/solve/assembly/mod.rs:1042]: move this into `for_each_impl :3`

File: compiler/rustc_next_trait_solver/src/solve/assembly/mod.rs [hunk 9]
```diff
@@ -943,6 +957,110 @@ where
...
+
+                // We force the certainty of impl candidates to be `Maybe`.
```
Comment (lcnr) [inline compiler/rustc_next_trait_solver/src/solve/assembly/mod.rs]: move

File: tests/ui/impl-trait/non-defining-uses/avoid-inference-constraints-from-blanket.rs [hunk 10]
```diff
@@ -0,0 +1,24 @@
...
+impl<T> Trait<T> for T {}
+impl Trait<u32> for u64 {}
+
+fn impls_trait<T: Trait<U>, U>() -> T {
+    todo!()
+}
+
+fn foo() -> impl Sized {
+    if false {
+        return impls_trait::<_, u32>();
```
Comment (lcnr) [inline tests/ui/impl-trait/non-defining-uses/avoid-inference-constraints-from-blanket.rs:21]: > // `opaque: Trait<u32>` shouldn't constrain opaque to `u32` via the blanket impl

**Comment by lcnr** [comment]
damn, these regressions are tiny. gamer!

**Comment by BoxyUwU** [comment]
gamer!
