### PR TITLE
Addressed #51602

### LINKED ISSUE #51602: Compiler suggests using the removed placement syntax
So I'm writing a hangman app in Rust and I get this weird error message. It doesn't make sense since `<-` isn't even in Rust anymore.

```   Compiling hangman v0.1.0 (file:///home/toot/Projects/hangman)
error: expected `{`, found `in`
  --> src/main.rs:8:17
   |
8  |           if line in words {
   |  _________________-^
9  | |             println!("Success");
10 | |         } else {
   | |_________- help: try placing this code inside a block: `{ words <- { println!("Success"); }; }`

error: aborting due to previous error

error: Could not compile `hangman`.
```

### PR DESCRIPTION
**Pull request by PramodBisht**
Fixed #51602 
r? @estebank 

here I have addressed the case where `in` was not expected right after `if` block. Speaking of `type ascription` I am not sure if this the best approach which I have implemented. Plus I think one more test case can be added to test `type-ascription` case, though I don't have any at this point of time. I will ping you again if all existing testcases pass.

### CODE REVIEW

**Comment by estebank** [comment]
LGTM. I'll await for the ping.

File: src/libsyntax/parse/parser.rs [hunk 1]
```diff
@@ -4719,6 +4719,10 @@ impl<'a> Parser<'a> {
         if !self.eat(&token::OpenDelim(token::Brace)) {
             let sp = self.span;
             let tok = self.this_token_to_string();
+            let mut do_not_suggest_help = false;
+            if self.token.is_keyword(keywords::In) || self.token == token::Colon {
+                do_not_suggest_help = true;
+            }
             let mut e = self.span_fatal(sp, &format!("expected `{{`, found `{}`", tok));
```
Comment (estebank) [inline src/libsyntax/parse/parser.rs]: While you're doing this, could you add this here?

```
e.span_label(sp, "expected `{`");
```

Comment (PramodBisht) [reply src/libsyntax/parse/parser.rs]: @estebank sure!
