### PR TITLE
Dynamically size sigaltstk in std

### LINKED ISSUE #107795: How to enable Intel AMX in `asm!` on Linux?
Hi,

I want to use in Rust (via inline assembly) [Intel AMX instruction set](https://software.intel.com/content/dam/develop/external/us/en/documents-tps/architecture-instruction-set-extensions-programming-reference.pdf).
AMX support is by default disabled in Linux Kernel due to significant amount of memory(~10KB) that has to be save on stack when there is context switching for programs using AMX. To enable AMX we need processor
with this capability (sapphirerapids), recent enough Linux kernel (5.16+) and stacks of FPU&sigalt to be of a size enough to be able to store AMX tiles (registers). Article on enabling AMX is [here](https://lwn.net/Articles/874846/).
I have implemented a programs to enable and test AMX: one in C++ and the other in Rust. The one in C++ does initialize AMX properly, but the Rust program is not able to initialize AMX properly (likely due to stack sizes being not big enough, see "PROGRAM EXITS HERE in Rust example"). Similar problem was [described](https://bugs.python.org/issue46968) for python programming language. Please advice how to have AMX support enabled in Rust on SapphireRapids under Linux.

#### C++ program:

```
#include <iostream>
                       
namespace {
#include <unistd.h>
#include <sys/syscall.h>

#define XFEATURE_XTILECFG 17
#define XFEATURE_XTILEDATA 18
#define XFEATURE_MASK_XTILECFG (1 << XFEATURE_XTILECFG)
#define XFEATURE_MASK_XTILEDATA (1 << XFEATURE_XTILEDATA)
#define XFEATURE_MASK_XTILE (XFEATURE_MASK_XTILECFG | XFEATURE_MASK_XTILEDATA)
#define ARCH_GET_XCOMP_PERM 0x1022
#define ARCH_REQ_XCOMP_PERM 0x1023

bool init() {
    unsigned long bitmask = 0;
    long status = syscall(SYS_arch_prctl, ARCH_GET_XCOMP_PERM, &bitmask);
    if (0 != status) return false;
    if (bitmask & XFEATURE_MASK_XTILEDATA) return true;

    status = syscall(SYS_arch_prctl, ARCH_REQ_XCOMP_PERM, XFEATURE_XTILEDATA);
    if (0 != status)
        return false; // XFEATURE_XTILEDATA setup is failed, TMUL usage is not allowed
    status = syscall(SYS_arch_prctl, ARCH_GET_XCOMP_PERM, &bitmask);

    // XFEATURE_XTILEDATA setup is failed, can't use TMUL
    if (0 != status || !(bitmask & XFEATURE_MASK_XTILEDATA)) return false;

    // XFEATURE_XTILEDATA set successfully, TMUL usage is allowed
    return true;
}
}

int main(int argc, char **argv) {

    puts("Using system call to enable AMX...");
    if (!init()) { 
      printf("Error: AMX is not available\n");
      return 1;
    }
    puts("...AMX is now enabled!\n");
}

```
##### main:rs:
```
use syscalls::*;

fn initialize_amx_if_available() -> bool {
    const ARCH_GET_XCOMP_PERM: usize = 0x1022;
    const ARCH_REQ_XCOMP_PERM: usize = 0x1023;
    const XFEATURE_XTILECFG: usize = 17;
    const XFEATURE_XTILEDATA: usize = 18;
    const XFEATURE_MASK_XTILEDATA: usize = 1 << XFEATURE_XTILEDATA;
    const XFEATURE_MASK_XTILECFG: usize = 1 << XFEATURE_XTILECFG;
    const XFEATURE_MASK_XTILE: usize = XFEATURE_MASK_XTILECFG | XFEATURE_MASK_XTILEDATA;

    let bitmask: [usize; 1] = [0; 1];
    let mut status: usize = 0;
    unsafe {
        let maybe_status = syscall!(Sysno::arch_prctl, ARCH_GET_XCOMP_PERM, bitmask.as_ptr());
        match maybe_status {
            Ok(s) => status = s,
            Err(_) => {
                println!("AMX not supported!");
                return false;
            }
        }
    }

    if (bitmask[0] & XFEATURE_MASK_XTILEDATA) != 0 {
        return true;
    }

    unsafe {
        let maybe_status = syscall!(Sysno::arch_prctl, ARCH_REQ_XCOMP_PERM, XFEATURE_XTILEDATA);
        match maybe_status {
            Ok(s) => status = s,
            Err(err) => {
                println!("AMX Error: XFEATURE_XTILEDATA setup is failed, TMUL usage is not allowed! Error: {}",err);
                return false;          //<========================================== PROGRAM EXITS HERE!!!
            }
        }
    }

    unsafe {
        status = syscall!(Sysno::arch_prctl, ARCH_GET_XCOMP_PERM, bitmask.as_ptr())
            .expect("Error: ARCH_PRCTL syscall failed!");
    }
    if status != 0 || ((bitmask[0] & XFEATURE_MASK_XTILEDATA) == 0) {
        println!("AMX not supported!");
        return false;   
    }

    // XFEATURE_XTILEDATA set successfully, TMUL usage is allowed
    true
}

fn main() {
  if initialize_amx_if_available() == true {
      println!("Success: AMX Enabled!");
  } else {
      println!("ERROR: Could not enable AMX!");
  }
}
```

##### Cargo.toml
```
[package]
name = "test-enable-amx"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
syscalls = "0.6.7"

```

**building:**`RUSTFLAGS='-C target-cpu=sapphirerapids -C target-feature=+amx-int8,+amx-bf16,+amx-tile' cargo build`
**toolchains used:** 1.67.0 , 1.69.0-nightly
**Linux kernel:** 5.19.0-1.el8.elrepo.x86_64
**OS:** Centos 8.5

### PR DESCRIPTION
**Pull request by workingjubilee**
On modern Linux with Intel AMX and 1KiB matrices,
Arm SVE with potentially 2KiB vectors,
and RISCV Vectors with up to 16KiB vectors,
we must handle dynamic signal stack sizes.

We can do so unconditionally by using getauxval,
but assuming it may return 0 as an answer,
thus falling back to the old constant if needed.

Fixes https://github.com/rust-lang/rust/issues/107795

### CODE REVIEW

File: library/std/src/sys/unix/stack_overflow.rs [hunk 1]
```diff
@@ -171,21 +179,41 @@ mod imp {
...
+        // so take the higher of the "constant" and auxval.
+        // This transparently supports older kernels which don't provide AT_MINSIGSTKSZ
+        libc::SIGSTKSZ.max(dynamic_sigstksz as _)
+    }
+
+    /// Not all OS support hardware where this is needed.
+    #[cfg(not(any(target_os = "linux", target_os = "android")))]
+    fn sigstack_size() -> usize {
+        libc::SIGSTKSZ
+    }
```
Comment (workingjubilee) [inline library/std/src/sys/unix/stack_overflow.rs:216]: Though "support hardware where this is needed" is confounded: on Darwin e.g. they simply define MINSIGSTKSZ and SIGSTKSZ to be values with actually decent sizes since they have a strong idea of the lower and upper bound for their hardware support.

File: library/std/src/sys/unix/stack_overflow.rs [hunk 2]
```diff
@@ -129,28 +129,36 @@ mod imp {
         drop_handler(MAIN_ALTSTACK.load(Ordering::Relaxed));
     }
 
-    unsafe fn get_stackp() -> *mut libc::c_void {
+    unsafe fn get_stack() -> libc::stack_t {
         // OpenBSD requires this flag for stack mapping
         // otherwise the said mapping will fail as a no-op on most systems
         // and has a different meaning on FreeBSD
         #[cfg(any(target_os = "openbsd", target_os = "netbsd", target_os = "linux",))]
         let flags = MAP_PRIVATE | MAP_ANON | libc::MAP_STACK;
```
Comment (the8472) [inline library/std/src/sys/unix/stack_overflow.rs:137]: Tangentially, should this also include android?

Comment (workingjubilee) [reply library/std/src/sys/unix/stack_overflow.rs:137]: afaik it doesn't do anything on Linux, it's just defined, which is not the same thing.

Comment (workingjubilee) [reply library/std/src/sys/unix/stack_overflow.rs:137]: If we wanted to use it on everything where it's defined, we would also do Fuchsia:

https://github.com/rust-lang/libc/blob/9bfa899501d25f9eff56a0a67ed5b13a13126a23/src/fuchsia/mod.rs#L2936

And neutrino:
https://github.com/rust-lang/libc/blob/9bfa899501d25f9eff56a0a67ed5b13a13126a23/src/unix/nto/mod.rs#L2485

And also Dragonfly and FreeBSD.
However, our libc doesn't declare that value for Android. There's a lot of aberrations like that where something available on both Linux and Android isn't enabled for Android, unfortunately.

**Review by m-ou-se — APPROVED** [review]
r=me after rebasing!

**Comment by workingjubilee** [comment]
ayo!
