### PR TITLE
Suggest deref when coercing `ty::Ref` to `ty::RawPtr`

### LINKED ISSUE #32122: Deref coercions and &-to-* coercions don't compose
Minimal repro:

``` rust
use std::ops::Deref;

struct A (u8);

impl Deref for A {
    type Target = u8;
    fn deref(&self) -> &Self::Target {
        &self.0
    }
}

fn main() {
    let a = A(0);

    //compiles
    let b: &u8 = &a;
    let c: *const u8 = b;

    //error
    let d: *const u8 = &a;
}
```

Compile error:

``` rust
coerce.rs:15:24: 15:26 error: mismatched types:
 expected `*const u8`,
    found `&A`
(expected u8,
    found struct `A`) [E0308]
coerce.rs:15     let c: *const u8 = &a;
                                    ^~
coerce.rs:15:24: 15:26 help: run `rustc --explain E0308` to see a detailed explanation
error: aborting due to previous error
```

### PR DESCRIPTION
**Pull request by ldm0**
Fixes #32122 

Currently we do autoderef when casting `ty::Ref` ->`ty::Ref`, but we don't autoderef when casting `ty::Ref` -> `ty::RawPtr`. This PR make the compiler suggests deref when coercing `ty::Ref` to `ty::RawPtr`

### CODE REVIEW

File: src/librustc_typeck/check/coercion.rs [hunk 1]
```diff
@@ -774,24 +774,54 @@ impl<'f, 'tcx> Coerce<'f, 'tcx> {
...
+                        Ok(ok) => Some(ok),
+                        Err(err) => {
+                            if first_error.is_none() {
+                                first_error = Some(err);
+                            }
+                            None
+                        }
+                    }
+                })
+                .next()
```
Comment (cuviper) [inline src/librustc_typeck/check/coercion.rs:799]: This is a small thing, but `filter_map(f).next()` is basically `find_map(f)`.

With your `first_error` handling on the side, I guess you would really want `try_find_map`. I might try to implement that.

Comment (ldm0) [reply src/librustc_typeck/check/coercion.rs:800]: Ah thanks! That would be convenient! I'll try to move to `find_map` first.

**Comment by ldm0** [comment]
cc @oli-obk 
Since <https://github.com/rust-lang/rust/issues/32122#issuecomment-578420992>
What do you think?

**Comment by oli-obk** [comment]
I don't think we should permit it (at least not without an RFC). But you can use your logic to determine whether we *could* do it and then use a different error variant to signal that a suggestion should be generated to use a user-written deref.

**Comment by ldm0** [comment]
> I don't think we should permit it (at least not without an RFC). But you can use your logic to determine whether we _could_ do it and then use a different error variant to signal that a suggestion should be generated to use a user-written deref.

Thanks for reviewing! I'll work on it.

**Comment by ldm0** [comment]
Now it can even suggest `&*******var`! XD

File: src/librustc_typeck/check/demand.rs [hunk 2]
```diff
@@ -539,6 +541,41 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
...
+                            coerce
+                                .unify(
+                                    coerce.tcx.mk_ptr(ty::TypeAndMut {
+                                        mutbl: hir::Mutability::Not,
+                                        ty: referent_ty,
+                                    }),
+                                    expected,
+                                )
+                                .is_ok()
+                        })
```
Comment (oli-obk) [inline src/librustc_typeck/check/demand.rs:565]: This took me a moment to untangle. The filter is always executed, so I think it would be better formulated as

```suggestion
                            coerce
                                .unify(
                                    coerce.tcx.mk_ptr(ty::TypeAndMut {
                                        mutbl: hir::Mutability::Not,
                                        ty: referent_ty,
                                    }),
                                    expected,
                                )
                                .ok().map(|_| steps)
```

File: src/librustc_typeck/check/demand.rs [hunk 3]
```diff
@@ -539,6 +541,41 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
                     return Some((sp, "consider removing the borrow", code));
                 }
             }
+            (
+                _,
+                &ty::RawPtr(TypeAndMut { ty: _, mutbl: hir::Mutability::Not }),
+                &ty::Ref(_, _, hir::Mutability::Not),
```
Comment (oli-obk) [inline src/librustc_typeck/check/demand.rs:547]: While I believe we could also do something for mutable references (both for staying in the same mutability and moving to const), this requires some care to get right without false positives, so maybe just leave a FIXME or open an issue?

**Comment by oli-obk** [comment]
This is great! just an impl nit then this lgtm

File: src/librustc_typeck/check/demand.rs (hunk 2 above)
Comment (ldm0) [reply src/librustc_typeck/check/demand.rs]: Nice! I didn't expect to write like that.

File: src/librustc_typeck/check/demand.rs (hunk 3 above)
Comment (ldm0) [reply src/librustc_typeck/check/demand.rs:547]: Yes, I missed the mutable references situation. I'll open another issue.

**Comment by lilred** [comment]
Thank you @ldm0 for getting around to this!!
