### PR TITLE
Fix `VecDeque::shrink_to` UB when `handle_alloc_error` unwinds.

### LINKED ISSUE #123369: `VecDeque::shrink_to` leads to UB if `handle_alloc_error` unwinds.
I tried this code:
https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=a2e4bd9f59882c88c4f232379cbb0001

I expected to see this happen:
`shrink_to_fit` causes an alloc error, the thread unwinds, `Foo(0)` and `Foo(1)` are dropped in some order.

Instead, this happened:
```
thread 'main' panicked at src/main.rs:37:30:
alloc error
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Dropping Foo(1)
Dropping Foo(3472329422384804195)
```
(the exact value printed differs between runs, which makes sense if it's reading uninit memory)

This occurs because of the way `VecDeque::shrink_to` is implemented: It first moves the memory around to fit the new capacity, then calls `RawVec::shrink_to_fit(new_capacity)` with no regards to potential unwinding. Specifically, this would look something like this:

1. After initialization, the deque buffer looks like this:
```
[Foo(0), <uninit> * 13, Foo(1)]
 ^                      ^
last                   head      
```
2. `shrink_to` copies the head to just behind the tail:
```
[Foo(0), Foo(1), <uninit> * 13]
 ^       ^
last    head
```
3. `shrink_to` calls `RawVec::shrink_to_fit` calls `Allocator::shrink` which returns an alloc error, the error handler unwinds, leaving the buffer looking like this:
```
[Foo(0), Foo(1), <uninit>, <uninit> * 12]
         ^       ^
        head    last
```
4. The `Drop` impl of `VecDeque` drops its elements, reading the uninit memory.
### Meta

While this specific setup requires nightly to manually set the alloc error handle hook and to trigger the alloc error in `shrink`, this same bug could occur on stable if `shrink` OOMs. The docs for `handle_alloc_error` also explicitly state that it may either abort or unwind.

I'm not sure what would be the best way to fix this. Maybe just `catch_unwind` the call to `RawVec::shrink_to_fit` and manually abort the process would work well enough?

### PR DESCRIPTION
**Pull request by Sp00ph**
Fixes #123369

For `VecDeque` it's relatively simple to restore the buffer into a consistent state so this PR does just that.

Note that with its current implementation, `shrink_to` may change the internal arrangement of elements in the buffer, so e.g. `[D, <uninit>, A, B, C]` will become `[<uninit>, A, B, C, D]` and `[<uninit>, <uninit>, A, B, C]` may become `[B, C, <uninit>, <uninit>, A]` if `shrink_to` unwinds. This shouldn't be an issue though as we don't make any guarantees about the stability of the internal buffer arrangement (and this case is impossible to hit on stable anyways).

This PR also includes a test with code adapted from #123369 which fails without the new `shrink_to` code. Does this suffice or do we maybe need more exhaustive tests like in #108475?

cc @Amanieu 

@rustbot label +T-libs

### CODE REVIEW

**Comment by MarkusEverling** [comment]
Hmm, so is this just blocked on rust-lang/miri#3439 then? Or should I just slap a `#[cfg(not(miri))]` on the test for now?

**Comment by Sp00ph** [comment]
Woops, didn't mean to comment here from that account lol.

File: library/alloc/src/collections/vec_deque/tests.rs [hunk 1]
```diff
@@ -790,6 +797,52 @@ fn test_shrink_to() {
...
+            _old_layout: Layout,
+            _new_layout: Layout,
+        ) -> Result<NonNull<[u8]>, AllocError> {
+            Err(AllocError)
+        }
+    }
+
+    // preserve the old error hook just in case.
+    let old_error_hook = take_alloc_error_hook();
+    set_alloc_error_hook(|_| panic!("alloc error"));
```
Comment (RalfJung) [inline library/alloc/src/collections/vec_deque/tests.rs:832]: This changes the alloc error hook for all concurrently running tests... is that really a good idea?

**Comment by RalfJung** [comment]
> Hmm, so is this just blocked on [rust-lang/miri#3439](https://github.com/rust-lang/miri/issues/3439) then? Or should I just slap a `#[cfg(not(miri))]` on the test for now?

Yeah disabling the test in Miri is fine for now, but please ping `@rust-lang/miri` when you do that so we can keep tabs of these tests and re-enable them when the underlying issue is fixed.

File: library/alloc/src/collections/vec_deque/tests.rs (hunk 1 above)
Comment (Sp00ph) [reply library/alloc/src/collections/vec_deque/tests.rs:832]: Hm, is there another mechanism to allow what I want to test there? Something like compiling this specific test with `-Zoom=unwind` maybe?

Comment (RalfJung) [reply library/alloc/src/collections/vec_deque/tests.rs:832]: You can make it a separate test crate by adding a file like `alloc/tests/vec_deque_alloc_error.rs` and add it to `alloc/Cargo.toml` separately.
