### PR TITLE
Fix binding unsized expressions to ref patterns

### LINKED ISSUE #23605: LLVM assertion on "let ref a = someArray[..];"
```rust
let someArray = [1,2,3];

let a = &someArray; // The variable 'a' has a type &'static [i32, 3]
let ref b = someArray; // The variable 'b' has a type &'static [i32, 3]
```
I've tried to write:
```rust
let ref a = someArray[..]; // I thought maybe it equals to &someArray[..];
```
The line above gives LLVM assertion.
I think this must show some syntax error.
```
Assertion failed!

Program: C:\rust\bin\rustc.exe
File: C:/bot/slave/nightly-dist-rustc-win-64/build/src/llvm/lib/IR/Instructions.
cpp, Line 1083

Expression: getOperand(0)->getType() == cast<PointerType>(getOperand(1)->getType
())->getElementType() && "Ptr must be a pointer to Val type!"

This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.
```

### PR DESCRIPTION
**Pull request by petrochenkov**
After this patch code like `let ref a = *"abcdef"` doesn't cause ICE anymore.
Required for #23121

There are still places in rustc_trans where pointers are always assumed to be thin. In particular, #19064 is not resolved by this patch.

Fixes #23605.

### CODE REVIEW

File: src/librustc_trans/trans/_match.rs [hunk 1]
```diff
@@ -1677,8 +1696,22 @@ fn bind_irrefutable_pat<'blk, 'tcx>(bcx: Block<'blk, 'tcx>,
 
                             ast::BindByRef(_) => {
                                 // By ref binding: the value of the variable
-                                // is the pointer `val` itself.
-                                Store(bcx, val, llval);
+                                // is the pointer `val` itself or fat pointer referenced by `val`
+                                if let ty::ty_rptr(_, ty::mt { ty: inner_ty, .. }) = ty.sty {
```
Comment (jakub-) [inline src/librustc_trans/trans/_match.rs]: Could we here and below use `base::store_ty` in place of the whole code block?

```rust
store_ty(bcx, val, llval, inner_ty);
```

Comment (petrochenkov) [inline src/librustc_trans/trans/_match.rs]: `store_ty`? It looks like it is not supposed to be used with fat pointers (or non-immediate types in general).

Comment (petrochenkov) [inline src/librustc_trans/trans/_match.rs]: It would be simpler to `Load` and `Store` the whole fat pointer as a first-class aggregate, but for some reason I've never seen it done in rustc_trans, so I followed the tradition and splitted it into pointer and length.

**Comment by petrochenkov** [comment]
Refactored the code a bit.
