### PR TITLE
Check normalized call signature for WF in mir typeck

### LINKED ISSUE #114936: Soundness regression with `for<'lt>` closure having an implied bound from return type
Bug originally found by @ast-ral, [over Discord](https://discord.com/channels/273534239310479360/1120175689124036669/1141229090603552910), which I've then reduced.

### Code

I tried this code:

```rust
fn whoops(
    s: String,
    f: impl for<'s> FnOnce(&'s str) -> (&'static str, [&'static &'s (); 0]),
) -> &'static str
{
    f(&s).0
}
```

I expected to see this happen:

```rust
error[E0597]: `s` does not live long enough
 --> <source>:6:7
  |
6 |     f(&s).0
  |     --^^-
  |     | |
  |     | borrowed value does not live long enough
  |     argument requires that `s` is borrowed for `'static`
7 | }
  | - `s` dropped here while still borrowed

error: aborting due to previous error

For more information about this error, try `rustc --explain E0597`.
```

Instead, this happened: **code compiles successfully**

### Version it soundly rejected this code:

[1.64.0](https://rust.godbolt.org/z/7G4x1PW94)

### Version with soundness regression

[1.65.0](https://rust.godbolt.org/z/G6vv7rzev) and onwards

### Proof of unsoundness:

```rs
fn static_str_identity()
  -> impl for<'s> FnOnce(&'s str) -> (
        [&'static &'s (); 0],
        &'static str,
    )
{
    |s: &/* 's */ str| ( // <----------------+ inputs restricted to `'s`.
        [], // `: [&'static &'s (); 0]`,     |
            //   thus `'s : 'static` ->------+
            //            +-<----------------+
            //            |
            //            v
        s, // `: &'s str <: &'static str`
    )
}
​
fn main()
{
    let f = static_str_identity();
    let local = String::from("...");
    let s: &'static str = f(&local).1; // <- should be rejected!
    drop(local);
    let _unrelated = String::from("UB!");
    dbg!(s); // <- compiles and prints `"UB!"`
}
```

@rustbot modify labels: +I-unsound +regression-from-stable-to-stable -regression-untriaged

### Observations

  - This does not occur if the implied-lifetime-bounds array is in closure _parameter_ position; so it looks like a bug w.r.t. not properly checking the closure _output_ type implied bounds?

  - `-Ztrait-solver=next` does not help (as of `2023-08-16`)

### LINKED ISSUE #118876: `&'a T` → `&'static T` in safe code
(Originally found [here](https://github.com/rust-lang/rust/issues/25860#issuecomment-1850192624))

I tried this code:

```rust
fn extend<T>(input: &T) -> &'static T {
    struct Bounded<'a, 'b: 'static, T>(&'a T, [&'b (); 0]);
    let n: Box<dyn FnOnce(&T) -> Bounded<'static, '_, T>> = Box::new(|x| Bounded(x, []));
    n(input).0
}

fn extend_mut<'a, T>(input: &'a mut T) -> &'static mut T {
    struct Bounded<'a, 'b: 'static, T>(&'a mut T, [&'b (); 0]);
    let mut n: Box<dyn FnMut(&mut T) -> Bounded<'static, '_, T>> = Box::new(|x| Bounded(x, []));
    n(input).0
}
```

I expected to see this happen: *lifetime error, `'a` is not `'static`*

Instead, this happened: *compiles*

### Meta

Regression in nightly-2022-08-10

found 7 bors merge commits in the specified range
  commit[0] 2022-08-08: Auto merge of #98863 - compiler-errors:projection-msg, r=estebank
  commit[1] 2022-08-09: Auto merge of #100205 - cjgillot:noice-doc, r=camelid
  commit[2] 2022-08-09: Auto merge of #100304 - matthiaskrgr:rollup-gs56vlw, r=matthiaskrgr
  commit[3] 2022-08-09: Auto merge of #100089 - JakobDegen:no-invalidate-visitor, r=tmiasko
  commit[4] 2022-08-09: Auto merge of #100318 - Dylan-DPC:rollup-18tzp6q, r=Dylan-DPC
  commit[5] 2022-08-09: Auto merge of #99217 - lcnr:implied-bounds-pre-norm, r=lcnr
  commit[6] 2022-08-09: Auto merge of #100150 - notriddle:notriddle/implementors-js, r=GuillaumeGomez

@rustbot label T-types regression-from-stable-to-stable I-unsound A-lifetimes

### PR DESCRIPTION
**Pull request by compiler-errors**
Unfortunately we don't check that the built-in implementations for `Fn*` traits are actually well-formed in the same way that we do for user-provided impls.

Essentially, when checking a call terminator, we end up with a signature that references an unnormalized `<[closure] as FnOnce<...>>::Output` in its output. That output type, due to the built-in impl, doesn't follow the expected rule that `WF(ty)` implies `WF(normalized(ty))`. We fix this by also checking the normalized signature here. 

**See** boxy's detailed and useful explanation comment which explains this in more detail: https://github.com/rust-lang/rust/issues/114936#issuecomment-1710388741

Fixes #114936
Fixes #118876

r? types
cc @BoxyUwU @lcnr

### CODE REVIEW

**Review by estebank — APPROVED** [review]

File: compiler/rustc_borrowck/src/type_check/mod.rs [hunk 1]
```diff
@@ -1413,6 +1413,18 @@ impl<'a, 'tcx> TypeChecker<'a, 'tcx> {
                     ConstraintCategory::Boring,
                 );
                 let sig = self.normalize(sig, term_location);
+                // HACK(#114936): `WF(sig)` does not imply `WF(normalized(sig))`
+                // with built-in `Fn` implementations, since the impl may not be
+                // well-formed itself.
+                self.prove_predicates(
```
Comment (lcnr) [inline compiler/rustc_borrowck/src/type_check/mod.rs:1419]: nit: do we want to only emit those in case normalization actually changed the arg/ret ty

**Comment by lcnr** [comment]
@craterbot check

**Comment by lcnr** [comment]
@craterbot ping

**Comment by compiler-errors** [comment]
@craterbot check

**Comment by compiler-errors** [comment]
@craterbot check start=master#27d8a577138c0d319a572cd1a464c2b755e577de end=try#8bdbfd41bed26c4938a9f14bd20556eac1de8437

**Comment by compiler-errors** [comment]
Regression:

```rust
use std::iter::FromIterator;

struct Foo;

impl<'a, U: Clone> FromIterator<&'a U> for Foo {
    fn from_iter<T: IntoIterator<Item = &'a U>>(iter: T) -> Self { 
        for x in iter {}

        Foo
     }
}

fn main() {}
```

```
error[E0309]: the parameter type `U` may not live long enough
 --> /home/gh-compiler-errors/test.rs:7:18
  |
5 | impl<'a, U: Clone> FromIterator<&'a U> for Foo {
  |      -- the parameter type `U` must be valid for the lifetime `'a` as defined here...
6 |     fn from_iter<T: IntoIterator<Item = &'a U>>(iter: T) -> Self { 
7 |         for x in iter {}
  |                  ^^^^ ...so that the type `U` will meet its required lifetime bounds
  |
help: consider adding an explicit lifetime bound
  |
5 | impl<'a, U: Clone + 'a> FromIterator<&'a U> for Foo {
  |                   ++++
```

**Comment by aliemjay** [comment]
> Regression:

fixed by #104098?

**Comment by compiler-errors** [comment]
@aliemjay: Yes it looks clear that the PR would fix it!

**Comment by lcnr** [comment]
marking as blocked on #104098 then

**Comment by fmease** [comment]
#120019 (#104098's replacement) has been merged. Unblocking

**Comment by lcnr** [comment]
do we want to rerun crater to check that there are no other regressions?

**Comment by compiler-errors** [comment]
@bors try

not totally sure if we should full crater or just rerun the regressions given the changes in #120019, but i am also gonna sleep now so will figure that out tomorrow

**Comment by lcnr** [comment]
@craterbot check p=1 crates=https://crater-reports.s3.amazonaws.com/pr-118882/retry-regressed-list.txt

**Comment by lcnr** [comment]
> Unfortunately we don't check that the built-in implementations for `Fn*` traits are actually well-formed in the same way that we do for user-provided impls.
> 
> Essentially, when checking a call terminator, we end up with a signature that references an unnormalized `<[closure] as FnOnce<...>>::Output` in its output. That output type, due to the built-in impl, doesn't follow the expected rule that `WF(ty)` implies `WF(normalized(ty))`. We fix this by also checking the normalized signature here.
> 
> **See** boxy's detailed and useful explanation comment which explains this in more detail: [#114936 (comment)](https://github.com/rust-lang/rust/issues/114936#issuecomment-1710388741)
> 
> Fixes #114936 Fixes #118876

from the PR description. This does not result in any crater regressions and fixes a soundness regression. While it a bit hacky, properly restoring the invariant `WF(ty)` implies `WF(normalized(ty))` relies on explicit where clauses on binders, which will still take quite a while.

@rfcbot fcp merge

**Comment by lcnr** [comment]
r=me after fixing CI

**Comment by alexcrichton** [comment]
I've opened https://github.com/rust-lang/rust/issues/124984 which cargo bisect-rustc points to this PR as the cause of the regression so wanted to flag it here as well.
