### PR TITLE
Don't call a function in function-arguments-naked.rs

### LINKED ISSUE #75096: Assertion `MFI.isCalleeSavedInfoValid() && "CalleeSavedInfo not calculated"' failed on AArch64
The `debuginfo/function-arguments-naked.rs` test is failing on AArch64's CI:

```
---- [debuginfo-gdb] debuginfo/function-arguments-naked.rs stdout ----
NOTE: compiletest thinks it is using GDB with native rust support

error: compilation failed!
status: signal: 6
command: "/checkout/obj/build/aarch64-unknown-linux-gnu/stage2/bin/rustc" "/checkout/src/test/debuginfo/function-arguments-naked.rs" "-Zthreads=1" "--target=aarch64-unknown-linux-gnu" "-C" "prefer-dynamic" "-o" "/checkout/obj/build/aarch64-unknown-linux-gnu/test/debuginfo/function-arguments-naked.gdb/a" "-Crpath" "-Zunstable-options" "-Lnative=/checkout/obj/build/aarch64-unknown-linux-gnu/native/rust-test-helpers" "-g" "-L" "/checkout/obj/build/aarch64-unknown-linux-gnu/test/debuginfo/function-arguments-naked.gdb/auxiliary"
stdout:
------------------------------------------

------------------------------------------
stderr:
------------------------------------------
warning: unused variable: `x`
  --> /checkout/src/test/debuginfo/function-arguments-naked.rs:36:10
   |
36 | fn naked(x: usize, y: usize) {
   |          ^ help: if this is intentional, prefix it with an underscore: `_x`
   |
   = note: `#[warn(unused_variables)]` on by default

warning: unused variable: `y`
  --> /checkout/src/test/debuginfo/function-arguments-naked.rs:36:20
   |
36 | fn naked(x: usize, y: usize) {
   |                    ^ help: if this is intentional, prefix it with an underscore: `_y`

rustc: /checkout/src/llvm-project/llvm/lib/Target/AArch64/AArch64MachineFunctionInfo.h:197: unsigned int llvm::AArch64FunctionInfo::getCalleeSavedStackSize(const llvm::MachineFrameInfo&) const: Assertion `MFI.isCalleeSavedInfoValid() && "CalleeSavedInfo not calculated"' failed.

------------------------------------------
```

### PR DESCRIPTION
**Pull request by Aaron1011**
Fixes #75096

It's U.B. to use anything other than inline assmebling in a naked
function. Fortunately, the `#break` directive works fine without
anything in the function body.

### CODE REVIEW

**Comment by Amanieu** [comment]
It is also UB to not have anything in a naked function. You *need* an `asm!` since `#[naked]` will not emit a return instruction for you.

**Comment by Aaron1011** [comment]
@Amanieu: I've added a `ret` instruction, and make the test`x86_64` only.

File: src/test/debuginfo/function-arguments-naked.rs [hunk 1]
```diff
@@ -34,7 +38,5 @@ fn main() {
 
 #[naked]
 fn naked(x: usize, y: usize) {
```
Comment (Amanieu) [inline src/test/debuginfo/function-arguments-naked.rs:40]:
```suggestion
extern "C" fn naked(x: usize, y: usize) {
```

Some calling conventions (e.g. `stdcall`) require a stack adjustment on return. Since the Rust calling convention is unspecified, it's better to explicitly use "C".
