### PR TITLE
bypass linker configuration and cross target check on `x check`

### LINKED ISSUE #133840: `./x check std --target aarch64-apple-ios` fails when cross-checking due to missing `xcrun`
On a non-mac host, checking std for an ios target fails with the following error:

```
> ./x check std --target aarch64-apple-ios                                                                                                                          
Building bootstrap
    Finished `dev` profile [unoptimized] target(s) in 0.8s


error occurred: Failed to find tool. Is `xcrun` installed? (see https://docs.rs/cc/latest/cc/#compile-time-requirements for help)


Build completed unsuccessfully in 0:00:01
```

Ideally I should be able to check any target from any host.

### PR DESCRIPTION
**Pull request by onur-ozkan**
I was going to handle this using the untracked env approach, but I realized it somehow doesn't regress https://github.com/rust-lang/rust/issues/130108 anymore...

Anyway, if it works, it works. 😄 No need to dig deeper but my guess is we moved some cache-invalidating env from these functions to others.

Fixes https://github.com/rust-lang/rust/issues/133840

try-job: aarch64-apple

### CODE REVIEW

File: src/bootstrap/src/core/builder/cargo.rs [hunk 1]
```diff
@@ -114,7 +114,7 @@ impl Cargo {
         match cmd_kind {
             // No need to configure the target linker for these command types,
             // as they don't invoke rustc at all.
```
Comment (clubby789) [inline src/bootstrap/src/core/builder/cargo.rs:116]: Could you update this comment since we're now invoking rustc?

Comment (onur-ozkan) [reply src/bootstrap/src/core/builder/cargo.rs:116]: Good point

**Comment by onur-ozkan** [comment]
Rerolling due to inactivity. r? bootstrap

**Comment by clubby789** [comment]
🥲 Sorry, I typed out an r=me when green but guess I forgot to hit comment

@bors r+ rollup

**Comment by jieyouxu** [comment]
Failed in [rollup](https://github.com/rust-lang/rust/pull/140635#issuecomment-2849238236) on `aarch64-apple`:

```
2025-05-04T14:02:40.9144850Z failures:
2025-05-04T14:02:40.9145110Z 
2025-05-04T14:02:40.9145350Z ---- utils::cc_detect::tests::test_find stdout ----
2025-05-04T14:02:40.9145610Z 
2025-05-04T14:02:40.9145950Z thread 'utils::cc_detect::tests::test_find' panicked at src/bootstrap/src/utils/cc_detect/tests.rs:272:9:
2025-05-04T14:02:40.9146440Z CC not set for target x86_64-unknown-linux-gnu
2025-05-04T14:02:40.9146660Z 
2025-05-04T14:02:40.9146660Z 
2025-05-04T14:02:40.9146790Z failures:
2025-05-04T14:02:40.9147090Z     utils::cc_detect::tests::test_find
```

@bors r-

**Comment by clubby789** [comment]
This:
https://github.com/rust-lang/rust/blob/62c5f58f57670ce65e7fec34f8c4ba00c27da2d9/src/bootstrap/src/utils/cc_detect/tests.rs#L265

and other instances may need to be changed to `"build"` now?

**Comment by onur-ozkan** [comment]
> This:
> 
> https://github.com/rust-lang/rust/blob/62c5f58f57670ce65e7fec34f8c4ba00c27da2d9/src/bootstrap/src/utils/cc_detect/tests.rs#L265
> 
> and other instances may need to be changed to `"build"` now?

Yeah, seems like.
