### PR TITLE
Fix `doc_cfg` not working as expected on trait impls

### LINKED ISSUE #153655: `rustdoc` reports wrong config conditions for `impl LowerExp for integers`
*[View all comments](https://triagebot.infra.rust-lang.org/gh-comments/rust-lang/rust/issues/153655)*

# Actual Output

In the generated documentation for the core library, it reports `LowerExp` to be only implemented for integers on WebAssembly. See: https://doc.rust-lang.org/1.94.0/core/fmt/trait.LowerExp.html#impl-LowerExp-for-i8.

Show 'Available on WebAssembly only.'

This probably affects other trait implementations as well.

# Expected Outcome

`LowerExp` is available for all integer types on all platforms, therefore I expect it to report nothing regarding configs.

# Version

1.94.0

# Additional Details

In my understanding the problem is a combination of:

1. First, how the implementation is generated: https://github.com/rust-lang/rust/blob/3bc6ea5673e3e292db1e5b6ecaaaa883ca5af0b8/library/core/src/fmt/num.rs#L594-L612

    In the end the trait is implemented for all pointer sizes, but it is different depending on the pointer size.

2. And second that the pointer size configs are hidden: https://github.com/rust-lang/rust/blob/3bc6ea5673e3e292db1e5b6ecaaaa883ca5af0b8/library/core/src/lib.rs#L54-L74

If I remove the `target_pointer_width`s from the `doc(auto_cfg(hide(...`, then it gets shown like this (which is not really better tbh):

Show 'Available on 64-bit or WebAssembly only.'

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Fixes https://github.com/rust-lang/rust/issues/153655.

I spent waaaaay too much time on this fix. So the current issue is that rustdoc gets its items in two passes:
1. All items
2. Trait/blanket/auto impls

Because of that, the trait impls are not stored "correctly" in the rustdoc AST, meaning that the `propagate_doc_cfg` pass doesn't work correctly on them. So initially, I tried to "clean" the impls at the same time as the other items. However, it created a monstruous amount of bugs and issues and after two days, I decided to give up on this approach (might be worth fixing that in the future!). You can see what I tried [here](https://github.com/rust-lang/rust/compare/main...GuillaumeGomez:trait-impls-doc_cfg?expand=1).

So instead, since the impls are stored at the end, I create placeholders for impls and in `propagate_doc_cfg`, I store the `cfg` "context" (more clear when reading the code :stuck_out_tongue:) and re-use it later on when the "real" impl comes up.

r? @lolbinarycat

### CODE REVIEW

File: src/librustdoc/clean/mod.rs [hunk 1]
```diff
@@ -2909,10 +2911,27 @@ fn clean_impl<'tcx>(
     impl_: &hir::Impl<'tcx>,
     def_id: LocalDefId,
     cx: &mut DocContext<'tcx>,
+    // If `renamed` is some, then this is an inlined impl and it will be handled later on in the
```
Comment (lolbinarycat) [inline src/librustdoc/clean/mod.rs]: nit: ambiguous pronoun, this would be less ambiguous if "this" was replaced with an actual name.

File: src/librustdoc/json/conversions.rs [hunk 2]
```diff
@@ -353,6 +353,7 @@ fn from_clean_item(item: &clean::Item, renderer: &JsonRenderer<'_>) -> ItemEnum
             name: name.as_ref().unwrap().to_string(),
             rename: src.map(|x| x.to_string()),
         },
+        PlaceholderImplItem => unreachable!(),
```
Comment (lolbinarycat) [inline src/librustdoc/json/conversions.rs:357]: I would like an explanation for why this is unreachable.

File: src/librustdoc/passes/calculate_doc_coverage.rs [hunk 3]
```diff
@@ -199,7 +199,7 @@ impl DocVisitor<'_> for CoverageCalculator<'_, '_> {
         }
 
         match i.kind {
-            clean::StrippedItem(..) => {
+            clean::StrippedItem(..) | clean::PlaceholderImplItem => {
                 // don't count items in stripped modules
```
Comment (lolbinarycat) [inline src/librustdoc/passes/calculate_doc_coverage.rs:203]: nit: this comment is now slightly out of date.

File: src/librustdoc/passes/stripper.rs [hunk 4]
```diff
@@ -120,6 +120,9 @@ impl DocFolder for Stripper<'_, '_> {
 
             clean::ImplItem(..) => {}
 
+            // They have no use anymore, so always remove them.
```
Comment (lolbinarycat) [inline src/librustdoc/passes/stripper.rs]: nit: great comments explain *why* code does something.

File: tests/rustdoc-html/doc-cfg/trait-impls.rs [hunk 5]
```diff
@@ -0,0 +1,59 @@
+// This test ensures that `doc_cfg` feature is working as expected on trait impls.
```
Comment (lolbinarycat) [inline tests/rustdoc-html/doc-cfg/trait-impls.rs:1]: just to be sure: we do have a test for non-trait impls, right? we definitely don't want to regress that.

also, do we have a test for non-auto `doc(cfg(...))` on trait items?

File: src/librustdoc/clean/mod.rs [hunk 6]
```diff
@@ -2776,7 +2776,9 @@ fn clean_maybe_renamed_item<'tcx>(
         // These kinds of item either don't need a `name` or accept a `None` one so we handle them
         // before.
         match item.kind {
-            ItemKind::Impl(ref impl_) => return clean_impl(impl_, item.owner_id.def_id, cx),
+            ItemKind::Impl(ref impl_) => {
+                return clean_impl(impl_, item.owner_id.def_id, cx, renamed);
```
Comment (lolbinarycat) [inline src/librustdoc/clean/mod.rs]: what does it mean for an impl to be renamed?

**Review by lolbinarycat — COMMENTED** [review]
Code looks good to me but I still need to do a more in-depth investigation of the logic.  For now, here's some nits and clarifying questions.

*[View changes since this review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/rust/153964/ec15ca96ff2a5b733ab142ecc3744daed751c440..ce71ac833d73706e55ed3e72fd0aed083085a415)*

File: src/librustdoc/clean/mod.rs (hunk 6 above)
Comment (GuillaumeGomez) [reply src/librustdoc/clean/mod.rs]: The explanation is on the `clean_impl` function but I can copy/paste it here too.

File: tests/rustdoc-html/doc-cfg/trait-impls.rs (hunk 5 above)
Comment (GuillaumeGomez) [reply tests/rustdoc-html/doc-cfg/trait-impls.rs:1]: Doesn't hurt to add one in the same test I guess. Gonna add a test for non-auto `doc(cfg(...))` too.

File: src/librustdoc/passes/check_doc_test_visibility.rs [hunk 7]
```diff
@@ -79,6 +79,7 @@ pub(crate) fn should_have_doc_example(cx: &DocContext<'_>, item: &clean::Item) -
                 | clean::ProvidedAssocConstItem(..)
                 | clean::ImplAssocConstItem(..)
                 | clean::RequiredAssocTypeItem(..)
+                | clean::PlaceholderImplItem
```
Comment (lolbinarycat) [inline src/librustdoc/passes/check_doc_test_visibility.rs:83]: This made me realize that we don't actually have a test for how `rustdoc::missing_doc_code_examples` interacts with inherent impls (we do have them for *trait impls*, which is what is relevant to this PR, and what I was initially checking).

[here's a search for all the test files using that lint](https://github.com/search?q=repo%3Arust-lang%2Frust+path%3Atests+%22rustdoc%3A%3Amissing_doc_code_examples%22+path%3A*.rs&type=code)

File: src/librustdoc/passes/calculate_doc_coverage.rs [hunk 8]
```diff
@@ -203,6 +203,10 @@ impl DocVisitor<'_> for CoverageCalculator<'_, '_> {
...
                 return;
             }
+            clean::PlaceholderImplItem => {
+                // The "real" impl items are handled below.
+                return;
+            }
```
Comment (lolbinarycat) [inline src/librustdoc/passes/calculate_doc_coverage.rs:209]: note: we do have test coverage for doc coverage involving both types of impl.  good.

File: src/librustdoc/passes/propagate_doc_cfg.rs [hunk 9]
```diff
@@ -78,7 +84,22 @@ impl DocFolder for CfgPropagator<'_, '_> {
...
-        self.merge_with_parent_attributes(&mut item);
+        // If we have an impl, we check if it has an associated `cfg` "context", and if so we will
+        // use this context instead of the actual (wrong) one.
+        if let ItemKind::ImplItem(_) = item.kind
+            && let Some(cfg_info) = self.impl_cfg_info.remove(&item.item_id)
+        {
+            self.cfg_info = cfg_info;
+        }
+
+        if let ItemKind::PlaceholderImplItem = item.kind {
```
Comment (lolbinarycat) [inline src/librustdoc/passes/propagate_doc_cfg.rs:95]: nit: `if let` with no new bindings introduced.  might be more intuitive if these were written with `matches!`? but this pattern is used a bit around rustdoc, so if you'd rather keep it how it is that's fine.

File: src/librustdoc/visit_ast.rs [hunk 10]
```diff
@@ -426,12 +426,16 @@ impl<'a, 'tcx> RustdocVisitor<'a, 'tcx> {
...
+            if let hir::ItemKind::Impl(impl_) = item.kind {
+                self.add_to_current_mod(
+                    item,
+                    if impl_.of_trait.is_none() {
+                        None
+                    } else {
+                        Some(rustc_span::symbol::kw::Impl)
+                    },
+                    None,
+                );
```
Comment (lolbinarycat) [inline src/librustdoc/visit_ast.rs]: This seems like a little bit of a magic value, I'd at least like if this special value was documented somewhere, perhaps on the doc comment of `Module::items`.  I understand the use of a sentinel here because the alternative involves adding a new field to the tuple in the `items` Vec, or refactoring that into a more principled enum, which I'm sure would be quite the undertaking.

Actually, this isn't quite a sentinel value, is it, because `Impl` items in this context don't actually care about the inner value of `renamed`, just if it is `None`, correct?

**Review by lolbinarycat — COMMENTED** [review]
I took a closer look at the actual logic this time and it seems solid and straightforwards, I can't come up with any edge cases that it would cause problems in.

My only issue of immediate relevance is `rustc_span::symbol::kw::Impl` and `renamed` being used in a somewhat unintuitive way, not sure what the best way to address that is but it definitely has an impact on code readability.  I also found some missing test coverage but that's mostly unrelated so that can be handled in a followup PR if you want.

*[View changes since this review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/rust/153964/b711f95f86b6489b91fdc55c876ed5f95a8d4560..2dd7677b4288cf540babfc7886ea3c9f05003ea6)*

File: src/librustdoc/passes/propagate_doc_cfg.rs (hunk 9 above)
Comment (GuillaumeGomez) [reply src/librustdoc/passes/propagate_doc_cfg.rs:95]: I tend to prefer inline code over macros if I can, and I have to admit I find this `let` binding funny. Brain fart of the day I guess. ^^'

File: src/librustdoc/visit_ast.rs (hunk 10 above)
Comment (GuillaumeGomez) [reply src/librustdoc/visit_ast.rs]: Yeah. I'll add a comment to make that clear though because it really comes out of nowhere.

File: src/librustdoc/passes/check_doc_test_visibility.rs (hunk 7 above)
Comment (GuillaumeGomez) [reply src/librustdoc/passes/check_doc_test_visibility.rs:83]: Gonna send another PR for it then. :)

File: src/librustdoc/visit_ast.rs [hunk 11]
```diff
@@ -426,12 +426,20 @@ impl<'a, 'tcx> RustdocVisitor<'a, 'tcx> {
...
+                    item,
+                    // The symbol here is used as a "sentinel" value and has no meaning in
+                    // itself. It just tells that this is an inlined impl and that it should not
+                    // be cleaned as a normal `ImplItem` but instead as a `PlaceholderImplItem`.
+                    // It's to ensure that `doc_cfg` inheritance works as expected.
+                    if impl_.of_trait.is_none() {
+                        None
+                    } else {
+                        Some(rustc_span::symbol::kw::Impl)
+                    },
```
Comment (fmease) [inline src/librustdoc/visit_ast.rs]: Would replacing parameter type `Option<Symbol>` with `Option<BikeshedTy>` be possible / much of a hassle where `BikeshedTy` is a new type that could be defined like `enum BikeshedTy { BikeshedName(Symbol), BikeshedAnon }`? I haven't read the rest of the diff, lol

Comment (GuillaumeGomez) [reply src/librustdoc/visit_ast.rs]: Context: this argument is what an inlined item is renamed into. So no, I don't want to rename it. :stuck_out_tongue_closed_eyes:

**Comment by GuillaumeGomez** [comment]
Fixed merge conflict.

File: src/librustdoc/clean/mod.rs [hunk 12]
```diff
@@ -2909,10 +2914,27 @@ fn clean_impl<'tcx>(
     impl_: &hir::Impl<'tcx>,
     def_id: LocalDefId,
     cx: &mut DocContext<'tcx>,
+    // If `renamed` is some, then `impl_` is an inlined impl and it will be handled later on in the
+    // code. In here, we will generate a placeholder for it in order to be able to compute its
+    // `doc_cfg` info.
+    renamed: Option<Symbol>,
```
Comment (lolbinarycat) [inline src/librustdoc/clean/mod.rs]: After some reflection I think this should probably just be a boolean parameter called something like `is_inlined`.  I feel like too often rustdoc just passes variables along as function parameters with the same name, even when they don't really make sense in that context.  Although why are we saying "inlined" and not "trait" here? Is there some subtle difference I'm missing?

If this item is renamed, we can probably remove the comment, but we'll definitely need to make sure that the comment in `clean_maybe_renamed_item` is updated to still make sense.

File: src/librustdoc/passes/propagate_doc_cfg.rs [hunk 13]
```diff
@@ -26,6 +28,10 @@ pub(crate) fn propagate_doc_cfg(cr: Crate, cx: &mut DocContext<'_>) -> Crate {
 struct CfgPropagator<'a, 'tcx> {
     cx: &'a mut DocContext<'tcx>,
     cfg_info: CfgInfo,
+
+    /// To ensure the `doc_cfg` feature works with how `rustdoc` handles impl, we need to store
```
Comment (lolbinarycat) [inline src/librustdoc/passes/propagate_doc_cfg.rs]:
```suggestion
    /// To ensure the `doc_cfg` feature works with how `rustdoc` handles impls, we need to store
```

nit: typo

File: src/librustdoc/passes/propagate_doc_cfg.rs [hunk 14]
```diff
@@ -78,7 +84,22 @@ impl DocFolder for CfgPropagator<'_, '_> {
     fn fold_item(&mut self, mut item: Item) -> Option<Item> {
         let old_cfg_info = self.cfg_info.clone();
 
-        self.merge_with_parent_attributes(&mut item);
+        // If we have an impl, we check if it has an associated `cfg` "context", and if so we will
+        // use this context instead of the actual (wrong) one.
```
Comment (lolbinarycat) [inline src/librustdoc/passes/propagate_doc_cfg.rs]:
```suggestion
        // If we have an impl, we check if it has an associated `cfg` "context", and if so we will
        // use that context instead of the actual (wrong) one.
```

very minor and somewhat subjective nit

File: src/librustdoc/visit_ast.rs [hunk 15]
```diff
@@ -530,10 +538,22 @@ impl<'a, 'tcx> RustdocVisitor<'a, 'tcx> {
                 }
             }
             hir::ItemKind::Impl(impl_) => {
-                // Don't duplicate impls when inlining or if it's implementing a trait, we'll pick
+                // Don't duplicate impls when inlining, we'll pick
                 // them up regardless of where they're located.
-                if !self.inlining && impl_.of_trait.is_none() {
-                    self.add_to_current_mod(item, None, None);
+                if !self.inlining {
```
Comment (lolbinarycat) [inline src/librustdoc/visit_ast.rs:544]: Instead of copy-pasting this code, I'd like to see it refactored into a utility method `add_impl_to_current_mod`.

**Review by lolbinarycat — COMMENTED** [review]
One last review pass, two points of substance and two very tiny nits about word choice in comments.

*[View changes since this review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/rust/153964/461e9738a47e313e4457957fa95ff6a19a4b88d4..2752dc5857593e73d4f00879c2b305111524e253)*

File: src/librustdoc/clean/mod.rs (hunk 12 above)
Comment (GuillaumeGomez) [reply src/librustdoc/clean/mod.rs]: Fair enough.

File: src/librustdoc/visit_ast.rs (hunk 15 above)
Comment (GuillaumeGomez) [reply src/librustdoc/visit_ast.rs:544]: Good idea.
