### PR TITLE
use `--exact` on `--skip` to avoid unintended substring matches

### LINKED ISSUE #117721: Some tests are incorrectly skipped for macOS CI
CI specifies these two jobs for x86_64-apple-darwin:

https://github.com/rust-lang/rust/blob/341efb10174bdd22912aae487917c9213255b20f/src/ci/github-actions/ci.yml#L528-L544

Note these two lines (with padding I've added):

```
./x.py --stage 2 test --skip tests/ui --skip tests/rustdoc --skip tests/run-make-fulldeps 
./x.py --stage 2 test        tests/ui        tests/rustdoc        tests/run-make-fulldeps 
```

It appears that the intent was for the first job to run a subset of the tests and the second job to run the complementary subset. However, it seems that `--skip` performs a **substring match** while the list of directories is an **exact match**. This means that the tests in `rustdoc-js`, `rustdoc-json`, and `rustdoc-ui` are never run on macOS CI — they are excluded by `--skip` and never explicitly added back. 

Surprisingly, it seems that tests in `rustdoc-js-std` *are* run. That seems like a secondary bug as it isn't behaving the same.

### PR DESCRIPTION
**Pull request by onur-ozkan**
Without the `--exact` flag, using `--skip tests/rustdoc` can unintentionally skip other tests that match as substrings such as `rustdoc-gui`, `rustdoc-js`, etc.

For debugging, run: `./x.py --stage 2 test rustdoc-ui --skip tests/rustdoc` and `./x.py --stage 2 test rustdoc-ui --skip tests/rustdoc -- --exact`

Resolves https://github.com/rust-lang/rust/issues/117721

try-job: x86_64-apple-1

### CODE REVIEW

**Comment by jieyouxu** [comment]
Thanks!
r? jieyouxu
@bors r+ rollup

**Comment by GuillaumeGomez** [comment]
Failed in https://github.com/rust-lang/rust/pull/132989.

@bors r-

**Comment by jieyouxu** [comment]
```
Unknown flag --exact
The build system of cg_clif.

USAGE:
    ./y.sh prepare [--out-dir DIR] [--download-dir DIR]
    ./y.sh build [--sysroot none|clif|llvm] [--out-dir DIR] [--download-dir DIR] [--no-unstable-features] [--frozen]
    ./y.sh test [--sysroot none|clif|llvm] [--out-dir DIR] [--download-dir DIR] [--no-unstable-features] [--frozen] [--skip-test TESTNAME]
    ./y.sh abi-cafe [--sysroot none|clif|llvm] [--out-dir DIR] [--download-dir DIR] [--no-unstable-features] [--frozen]
    ./y.sh bench [--sysroot none|clif|llvm] [--out-dir DIR] [--download-dir DIR] [--no-unstable-features] [--frozen]
OPTIONS:
```

Hm, that might've been passed down to cg_clif somehow...?

**Comment by onur-ozkan** [comment]
It seems that this part:

https://github.com/rust-lang/rust/blob/65b3877488ccfef3b1a903bfdd269559c59b957c/src/bootstrap/src/core/build_steps/test.rs#L3408

is passing all test arguments to `cg_clif` which doesn't seem right as we can't know if they are supported or not. We should only pass specific arguments explicitly.

File: src/bootstrap/src/core/build_steps/test.rs [hunk 1]
```diff
@@ -3600,13 +3599,10 @@ impl Step for TestFloatParse {
...
-        cargo_run.arg("--");
-        if builder.config.args().is_empty() {
+        cargo_run
+            .arg("--")
             // By default, exclude tests that take longer than ~1m.
-            cargo_run.arg("--skip-huge");
-        } else {
-            cargo_run.args(builder.config.args());
-        }
+            .arg("--skip-huge");
```
Comment (onur-ozkan) [inline src/bootstrap/src/core/build_steps/test.rs:3605]: cc @tgross35

File: src/bootstrap/src/core/build_steps/test.rs [hunk 2]
```diff
@@ -3405,7 +3405,6 @@ impl Step for CodegenCranelift {
             // FIXME remove once vendoring is handled
             .arg("--skip-test")
             .arg("testsuite.extended_sysroot");
-        cargo.args(builder.config.test_args());
```
Comment (onur-ozkan) [inline src/bootstrap/src/core/build_steps/test.rs:3408]: cc @bjorn3

**Review by onur-ozkan — COMMENTED** [review]
I just want to make sure they know about this change before we go for merge.

**Review by jieyouxu — APPROVED** [review]
LGTM, you can r=me now, or after I guess @tgross35 and @bjorn3 has a change to look at the change.

File: src/bootstrap/src/core/build_steps/test.rs (hunk 1 above)
Comment (tgross35) [reply src/bootstrap/src/core/build_steps/test.rs:3605]: Doesn't this unconditionally pass `--skip-huge` rather than only if no other arguments are specified? In CI we always want this passed, but I need a way to not pass this in order to run exhaustive tests locally.

Comment (jieyouxu) [reply src/bootstrap/src/core/build_steps/test.rs:3605]: I'll try to carry this PR forward since Onur is on vacation.

**Comment by jieyouxu** [comment]
Rolling another bootstrap reviewer because I plan to modify this PR to address Trevor's concern.

@rustbot author
r? bootstrap

**Comment by onur-ozkan** [comment]
Can you have another look on https://github.com/rust-lang/rust/compare/11dca9eac3c5a5dbb905ef9b0f06e287da0ed464..ff8ce5181db1e4284f0891aeb4d0ea525e26dff0 ? @tgross35 

@rustbot ready

File: src/bootstrap/src/core/build_steps/test.rs [hunk 3]
```diff
@@ -3600,12 +3599,11 @@ impl Step for TestFloatParse {
             &[],
         );
 
-        cargo_run.arg("--");
-        if builder.config.args().is_empty() {
-            // By default, exclude tests that take longer than ~1m.
-            cargo_run.arg("--skip-huge");
-        } else {
-            cargo_run.args(builder.config.args());
+        if env::var("FLOAT_PARSE_TESTS_SKIP_HUGE").unwrap() == "1" {
```
Comment (jieyouxu) [inline src/bootstrap/src/core/build_steps/test.rs:3602]: Suggestion: wouldn't this panic if the env var is unset in other CI jobs?

```suggestion
        if env::var("FLOAT_PARSE_TESTS_SKIP_HUGE").is_some() {
```

File: src/bootstrap/src/core/build_steps/test.rs [hunk 4]
```diff
@@ -3600,12 +3599,11 @@ impl Step for TestFloatParse {
...
-        if builder.config.args().is_empty() {
-            // By default, exclude tests that take longer than ~1m.
-            cargo_run.arg("--skip-huge");
-        } else {
-            cargo_run.args(builder.config.args());
+        if env::var("FLOAT_PARSE_TESTS_SKIP_HUGE").unwrap_or_default() == "1" {
+            cargo_run
+                .arg("--")
+                // By default, exclude tests that take longer than ~1m.
+                .arg("--skip-huge");
```
Comment (tgross35) [inline src/bootstrap/src/core/build_steps/test.rs:3606]: I think this might be missing another branch here - with the change change it looks like the tests don't run at all unless `FLOAT_PARSE_TESTS_SKIP_HUGE=1`.

The logic should be: always run by default with `--skip-huge`. If the user somehow indicates that slow tests should _not_ be skipped, don't pass `--skip-huge`. (So if this is done via env it should be something like `FLOAT_PARSE_TESTS_NO_SKIP_HUGE`).

Comment (onur-ozkan) [reply src/bootstrap/src/core/build_steps/test.rs:3606]: I think it's quite annoying not to run all tests by default and to have to pass something like `NO_SKIP_HUGE`. If we don't want to run them by default, why the tool itself doesn't do it by default instead of requiring bootstrap to pass `--skip-huge`? Anyway, not a big deal — I can do that.

Comment (tgross35) [reply src/bootstrap/src/core/build_steps/test.rs]: The reasoning is that when running the whole testsuite or in CI, about a minute of tests here is good enough. However, if it is run on its own, you probably don't want to forget to run the more thorough tests because of not passing a flag. I don't know what is best here, maybe the test should skip huge if RUSTC_BOOTSTRAP is set? (If you want to do that here it's easy enough, just set [`cfg.skip_huge`](https://github.com/rust-lang/rust/blob/dff3e7ccd4a18958c938136c4ccdc853fcc86194/src/etc/test-float-parse/src/main.rs#L72-L73) if the env is set).

Anyway the change looks good as-is 👍
