### PR TITLE
Fallback `{float}` to `f32` when `f32: From<{float}>` and add `impl From<f16> for f32`

### LINKED ISSUE #123831: `f32::from(<untyped float>)` inference with `f16` and `f128`
Adding a `From<f16> for f32` impl breaks some inference that currently works. From https://github.com/rust-lang/rust/issues/123824:

```rust
fn main() {
    let x = f32::from(3.14);
}
``` 

The new float types are a long way from being stable, but it may be good to decide how to handle things if we would like this implementation one day. Per @fmease at https://github.com/rust-lang/rust/issues/123824#issuecomment-2050628184, there are three options:

1. Accept this regression since technically, no stable API is broken
2. Say that we do not want `From<f16> for f32`
3. Make this implementation available starting with the new edition

I'll mark this with the edition label so it can at least come into consideration, but this is the lowest priority thing on any list.

Known failure points from adding this directly:
- Fuchsia: https://cs.opensource.google/fuchsia/fuchsia/+/main:src/recovery/lib/recovery-ui/src/keyboard.rs;l=111;drc=e1ed8a47e77b0ea1d6f83b93830c4e975a8a6089 (from https://github.com/rust-lang/rust/issues/123824#issuecomment-2050836467)
-  `taffy`: https://github.com/DioxusLabs/taffy/blob/f1e4edab96ee13f7d1fbc2536ac31633b0e620d6/src/style_helpers.rs#L58 (from https://github.com/rust-lang/rust/issues/123824#issuecomment-2052506991)
- `contour-rs`: https://github.com/mthh/contour-rs/blob/08c1d83a1461aa19543ed402d23908eb55234fd1/src/lib.rs#L488-L491 (from https://github.com/mthh/contour-rs/pull/13#issuecomment-2051652708)
- Bevy: https://github.com/rust-lang/rust/issues/123831#issuecomment-2052981580
- egui: https://github.com/emilk/egui/issues/4352

@rustbot label +T-lang +T-libs +A-edition-2024 +F-f16_and_f128

### PR DESCRIPTION
**Pull request by beetrees**
*[View all comments](https://triagebot.infra.rust-lang.org/gh-comments/rust-lang/rust/pull/139087)*

Currently, the following code compiles:
```rust
fn foo<T: Into<f32>>(_: T) {}

fn main() {
    foo(1.0);
}
```

This is because the only `From<{float}>` impl for `f32` is currently `From<f32>`. However, once `impl From<f16> for f32` is added this is no longer the case. This would cause the float literal to fallback to `f64`, subsequently causing a type error as `f32` does not implement `From<f64>`. While this kind of change to type inference isn't technically a breaking change according to Rust's breaking change policy, the previous attempt to add `impl From<f16> for f32` was removed rust-lang/rust#123830 due to the large number of crates affected (by my count, there were root regressions in 42 crates and 52 GitHub repos, not including duplicates). This PR solves this problem by using `f32` as the fallback type for `{float}` when there is a trait predicate of `f32: From<{float}>`. This allows adding `impl From<f16> for f32` without affecting the code that currently compiles (such as the example above; this PR shouldn't affect what is possible on stable).

This PR also allows adding a future-incompatibility warning for the fallback to `f32` (currently implemented in the third commit) if the lang team wants one (allowing the `f32` fallback to be removed in the future); alternatively this could be expanded in the future into something more general like @tgross35 suggested in https://github.com/rust-lang/rust/issues/123831#issuecomment-2064728053. I think it would be also possible to disallow the `f32` fallback in a future edition.

As expected, a crater check showed [no non-spurious regressions](https://github.com/rust-lang/rust/pull/139087#issuecomment-2764732580).

For reference, I've based the implementation loosely on the existing `calculate_diverging_fallback`. This first commit adds the `f32` fallback, the second adds `impl From<f16> for f32`, and the third adds a FCW lint for the `f32` fallback. I think this falls under the types team, so
r? types

Fixes: rust-lang/rust#123831
Tracking issue: rust-lang/rust#116909

@rustbot label +T-lang +T-types +T-libs-api +F-f16_and_f128

To decide on whether a future-incompatibility warning is desired or otherwise (see above):
@rustbot label +I-lang-nominated

cc https://github.com/rust-lang/rust/issues/154024 https://github.com/rust-lang/rust/issues/154005

### CODE REVIEW

**Comment by compiler-errors** [comment]
@craterbot check

**Comment by compiler-errors** [comment]
@craterbot retry-report

File: compiler/rustc_hir_typeck/src/fallback.rs [hunk 1]
```diff
@@ -160,6 +167,61 @@ impl<'tcx> FnCtxt<'_, 'tcx> {
...
+        if roots.is_empty() {
+            // Most functions have no `f32: From<{float}>` predicates, so short-circuit and return
+            // an empty set when this is the case.
+            return UnordSet::new();
+        }
+        let fallback_to_f32 = unresolved_variables
+            .iter()
+            .flat_map(|ty| ty.float_vid())
+            .filter(|vid| roots.contains(&self.root_float_var(*vid)))
+            .collect();
```
Comment (lcnr) [inline compiler/rustc_hir_typeck/src/fallback.rs:220]: Why do the mapping from root to all unified infer vars here instead of looking at the root in `fallback_if_possible`? Please add a comment

**Comment by lcnr** [comment]
Somewhat hacky, but that feels required unfortunately :sweat_smile:

Unlike an additional general fallback mechanism, this is not a breaking change as `f32: From<{float}>` currently only compiles when inferring to `f32`. So there is no way to end up with the case of "some other fallback requires the a *newly fallback'd var* to be something different from its fallback variable". 

I would like us to future compat warn here and to potentially remove this fallback in future, or future editions. I think our current fallback rules are kinda iffy and could imagine us wanting to change our approach in more fundamental ways at some point in the future.

**Comment by lcnr** [comment]
This PR does two changes

## add `impl From<f16> for f32` to the standard library (T-libs)

Adds an impl to std. Seems non-controversial to me as long as it does not cause inference breakage. For that, we've got a type system change which fixes all practical breakage

## Fallback `{float}` to `f32` when `f32: From<{float}>` (T-types)

Unlike an additional general fallback mechanism, this is not a breaking change as `f32: From<{float}>` currently only compiles when inferring to `f32`. So there is no way to end up with the case of "some other fallback requires the a *newly fallback'd var* to be something different from its fallback".

I am in favor of this change if it enables us to land the above impl and

### Future compat lint when applying this fallback and disable fallback in future editions

While this fallback does not break any existing code, it does add a small amount of complexity to the type system and may result in slightly surprising behavior. With this, I do think we should future compat lint it with the goal of removing it in the future.

@rfcbot fcp merge cc @rust-lang/lang I consider the fallback change to be owned by T-types.

**Comment by lcnr** [comment]
@rfcbot cancel

**Comment by lcnr** [comment]
@rfcbot fcp merge

**Comment by BoxyUwU** [comment]
Even with fallback this is still technically breaking if the `f32: From<?float>` goal was being used to constrain `?float=u32` which was then relied upon in method lookup :thinking: That seems acceptable to me given the lack of crater regressions if libs is interested in adding `impl From<f16> for f32` (which seems reasonable given `f64: From<f32>` is an existing impl)

**Comment by nikomatsakis** [comment]
@rfcbot concern niko-is-nervous

This is a tough one to separate our my types and lang team hats, but let me do my best.

**Types.** Wearing my types team hat, I have a few concerns about this change. It seems pretty tied into how the curent trait solver "flattens" obligations. I can certainly *imagine* how it would be supported in the new trait solver (and indeed we may have to do something similar for `!` fallback), but it makes me nervous. I don't really understand the plan for how we are going to remove it in the future -- is it that the FCW will irritate people enough that they'll add an explicit `f16`? I think so.

@rfcbot concern lang-wants-in

**Lang.** And now we get to the lang hat concern. From a lang perspective, the part of this PR I like the least is the part where we remove the change later. In short, it feels like a *good thing* for code like this to compile:

```rust
fn foo<T: Into<f32>>(_: T) {}
fn main() {
    foo(1.0);
}
```

and indeed I would want that to continue being true into the future, even with the new impl. I would *also* like code like *this* to compile (it currently does not):

```rust
fn foo<T: Into<u32>>(_: T) {}
fn main() {
    foo(1);
}
```

In our discussion in the lang team meeting, we felt like changes to fallback were definitely going to have an impact on how user's experience the language and we'd like to be involved in the FCP. (This concern is best resolved by canceling the FCP and restarting it with T-lang...)

I'm going to share some more detailed thoughts in a bit, but I wanted to start by filing these concerns.

**Comment by nikomatsakis** [comment]
Hmm. Thanks for voicing that @BoxyUwU. I don't personally want to get too hung up on which has "jurisdiction" or whatever. For me the bottom line is that this PR is proposing a narrow "scenario solving" sort of change (which would be subsequently reverted), and so the high order bit is that I  (wearing my "Rust" hat) feel we should think a bit bigger.

(And, when you start looking at those bigger problems, e.g., trying to make int literals overloadable, that seems clearly lang to me.)

Rather than argue which team does what, i'd rather we argue about whether bigger changes are feasible.

**Comment by nikomatsakis** [comment]
(Also, to the PR author, I think this is a well thought-out proposal, no disrespect meant.)

**Comment by BoxyUwU** [comment]
In regards to the technical feedback:

> I guess the concluion I'm reaching here is that, in my ideal world, we would think a bit bigger. Rather than doing a kind of niche change to coercion that we hope to remove later, we'd aim to address the root problems we keep running into that are preventing us from adding this impl.

I generally agree with this. I think we should make bigger changes to the language around the 1-impl rule and literals too. I don't think we should block std being able to add this impl on that though. We can experiment with such things at any point in time, and they're likely to take a *long* time to get anywhere.

> It seems pretty tied into how the curent trait solver "flattens" obligations

My understanding is that we already have problems around looking at unsolved obligations during hir typeck and the new trait solver already has ways of being compatible with such things. Though trying to find examples of that I'm coming up dry, @lcnr probably knows exactly where that ended up :thinking:

**Comment by nikomatsakis** [comment]
I would imagine perhaps to do with closure inference (which also works pretty poorly).

**Comment by BoxyUwU** [comment]
Ah right that's it. `obligations_for_self_ty_next` is the new solver compatible way of looking at current unsolved goals' potential nested goals to use to aid inference. Which is used when deducing closuring signatures.

**Comment by BoxyUwU** [comment]
I thought <https://github.com/rust-lang/rust/pull/139087#issuecomment-2764732580> was the breakage from not FCWing but it seems like that's the spurrious failures *with* the FCW instead of an inference error... The PR description says:
> by my count, there were root regressions in 42 crates and 52 GitHub repos, not including duplicates

Though I can't see where that count is coming from

**Comment by nikomatsakis** [comment]
Some pretty prominent crates there. e.g., bevy.

**Comment by nikomatsakis** [comment]
@BoxyUwU btw, on the topic of lang vs types, the way I see it is this:

lang always has the power to overrule types if lang feels the problems for user-facing impact. Obviously types makes calls but if the impact is high it's expected they'll clue lang in.

types always has the power to overrule lang if types feels the problems for complexity, implementability, or soundness is too much. Obviously lang makes calls but if the impact is high it's expected they'll clue types in.

So yeah, it's good for types to move forward with user-facing breakage. It's also ok for lang to step in sometimes and say "hmm, this one seems off". And it's fine for you to argue and say "no, it's not, let's not block a targeted change on some big years-long project". I'm still pondering that one.

I *think* my types concerns are largely resolved now, I'm now more just pondering "is this the right thing to do" -- e.g., if bevy relies on this, are we really going to want to have them migrate to `_f16`? How many places are impacted and in what way? 

If the answer is "probably not", then the question is, are we comfortable with this change if it's permanent? If we try to do something more general, will we hit a problem due to this change? I'd like to think that through at least a bit.

**Comment by jackh726** [comment]
My thoughts here:

First, procedurally, it is frustrating that this sat as lang-nominated for a while and that lang only chimed in *after* an pFCP was started. That being said, it's only a month, which is not *that* long. *And* I personally really do think that lang should be involved in this decision for the points Niko highlighted - unlike other decisions types decisions, this seems much more "user-facing" rather than just an implementation detail. Anyways, this is neither here nor there - if lang wants in, then I think it'd be weird for someone to say "no that's not okay".

Now, technically: I don't really like adding the extra complexity of this fallback, in large part because I think *removing* that fallback would take a while, even with a FCW. This has a wide impact. So, I'm going to "second" nikos "niko-is-nervous" concern.

**Comment by joshtriplett** [comment]
FWIW, personally, regardless of *how* we implement it, I think this code should *work* in the future:

```rust
fn func(_: impl Into<f32>) {}
fn main() { func(1.0); }
```

I also think *this* code should work, and today it doesn't:

```rust
fn func(_: impl Into<u16>) {}
fn main() { func(1); }
```

Whether we do that via a fallback mechanism, or some more general solution for literals, I think those should work and continue working forever. If we decide to remove the fallback mechanism being proposed here, it should only be because we added something *else* that makes that code continue working.

**Comment by jackh726** [comment]
I guess, for me to feel comfortable about this, I would want the FCW to land first, and to see 1) that the impact of that is not too large and 2) that it causes a significant reduction in the use of this fallback, indicating a strong likelihood that we will eventually be able to remove this hack.

**Comment by traviscross** [comment]
> I guess, for me to feel comfortable about this, I would want the FCW to land first, and to see 1) that the impact of that is not too large and 2) that it causes a significant reduction in the use of this fallback, indicating a strong likelihood that we will eventually be able to remove this hack.

Agree with this, and would add that ideally it'd work well enough that we don't need to add the hack at all.

**Comment by tgross35** [comment]
I think Boxy may have hinted at this, but is implementation complexity across both solvers the reason we can't do a more general solution at this time? At a surface level it seems "easy" to solve both the float and int examples by trying `T` (i.e. no conversion) if `Into<T>` is ambiguous. But I admittedly know very little about the inner workings here.

**Comment by tgross35** [comment]
Talked to @compiler-errors about the more general fallback at all hands. My understanding of the problem is that by the time the solver knows there is an unfulfilled obligation, it is already done solving and has no way to backtrack. So (aiui) it might be possible to infer the type of the literal at the location of the `Into` bound, but if it’s assigned to a variable then other things relying on the type of the variable would still act as if the type is unknown.

@Amanieu suggested there might be a way to keep track of the two possible solutions.

**Comment by traviscross** [comment]
In the spirit of brainstorming, I wonder whether pattern types could ever have a role to play here.  E.g., in

```rust
fn f<T: Into<u32>>(_: T) {}
fn main() {
    f(1);
}
```

maybe we could say that the literal falls back to `i32 is 1..=1`, and then we have an `impl From<i32 is 0..> for u32`.

Of course, pattern types are hard, and are I'm sure especially challenging to combine with floats.

cc @oli-obk

**Comment by beetrees** [comment]
> I guess, for me to feel comfortable about this, I would want the FCW to land first, and to see 1) that the impact of that is not too large and 2) that it causes a significant reduction in the use of this fallback, indicating a strong likelihood that we will eventually be able to remove this hack.

Adding a FCW without the trait impl would require a completely different implementation as the FCW as implemented relies on the float var reaching the fallback stage in order to warn about it. As the added trait impl (`From<f16> for f32`) will only be available on nightly until `f16` is stabilised, this PR could be reverted at any point until `f16` is stabilised without breaking backwards compatibility guarantees - is that sufficient? In regards to (1): I referenced a Crater run in https://github.com/rust-lang/rust/pull/139087#issuecomment-2842637439 from a year ago which had root regressions in 42 crates and 52 GitHub repos, but I'm happy to put up a PR with just the `From<f16> for f32` impl to run Crater on if more recent results are desired.

> maybe we could say that the literal falls back to i32 is 1..=1, and then we have an impl From<i32 is 0..> for u32. (This wouldn't allow literals bigger than i32::MAX to work, but maybe that's OK.)
>
> Of course, pattern types are hard, and are I'm sure especially challenging to combine with floats.

I don't think this would work for float literals due to double rounding.

**Comment by beetrees** [comment]
There seems to be a bit of a split of opinion between "add a FCW and eventually remove the `f32` fallback" and "don't add a FCW and expand the fallback so that it works for all literals constrained by `From<{float}> for fN` or `From<{integer}> for iN/uN`". I'm guessing this needs to be nominated lang team and/or types team discussion to decide which direction to head in?

**Comment by beetrees** [comment]
I've opened a PR to run Crater to measure the impact of the trait impl and FCW at #142723.

**Comment by joshtriplett** [comment]
> There seems to be a bit of a split of opinion between "add a FCW and eventually remove the `f32` fallback" and "don't add a FCW and expand the fallback so that it works for all literals constrained by `From<{float}> for fN` or `From<{integer}> for iN/uN`". I'm guessing this needs to be nominated lang team and/or types team discussion to decide which direction to head in?

Yes.

**Comment by traviscross** [comment]
We talked about this in the lang call.  We're interested in unblocking the stabilization of `f16`.  At the same time, some had reservations about doing that without some plan for being able to add this impl in a finite amount of time.

The option we discussed in the meeting went as follows:

If we could add an FCW against reliance on the fallback behavior when that fallback would be a problem for adding this impl (and it's OK if it approximates on this), then we can move maintained code off of this reliance.  Then, after some time, we can take the minor (in an RFC 1105 sense) breakage due to adding this impl.

(This plan uses our normal tools for evolving the language and doesn't require us to speculate about future features.  We're doing something similar to this for stabilizing the never type.)

Such a plan would give us confidence that we can likely add the impl in a finite amount of time, and that confidence would give us confidence to ship `f16` today.

@folkertdev, what do you think?  Is such a lint feasible?  What would you propose in terms of how it could be best targeted at this problem?

File: compiler/rustc_lint_defs/src/builtin.rs [hunk 2]
```diff
@@ -5021,3 +5022,52 @@ declare_lint! {
...
+    ///
+    /// [issue #FIXME]: https://github.com/rust-lang/rust/issues/FIXME
+    pub FLOAT_LITERAL_F32_FALLBACK,
+    Warn,
+    "detects unsuffixed floating point literals whose type fallback to `f32`",
+    @future_incompatible = FutureIncompatibleInfo {
+        reason: FutureIncompatibilityReason::FutureReleaseError,
+        reference: "issue #FIXME <https://github.com/rust-lang/rust/issues/FIXME>",
+    };
+}
```
Comment (folkertdev) [inline compiler/rustc_lint_defs/src/builtin.rs:5696]: @traviscross this PR already includes a FCW, @beetrees did all of the hard work already. I think this can be extracted (needs an update given all of the merge conflicts) and then that should do?

At least reading through the comments the T-types folks don't seem to have major issues with the approach here, though we'll see if anything else pops up.

note to self: I like the example from the issue better https://github.com/rust-lang/rust/issues/123824

Comment (folkertdev) [reply compiler/rustc_lint_defs/src/builtin.rs:5696]: Ah, the lint here only works when adding the additional `f16` instance (creating the ambiguity).

I'll push the rebased version anyway in case it's helpful, but a different approach to trigger the lint is needed and my knowledge of the type checker is insufficient to know what that would look like, so I'll need some help there.

File: Cargo.lock
Comment (jackh726) [inline Cargo.lock:1]: Cargo.lock changes probably unintended

**Review by jackh726 — COMMENTED** [review]
Is there a test something that ensures that `f32: From<f16>` doesn't hold on stable?

*[View changes since this review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/rust/139087/b711f95f86b6489b91fdc55c876ed5f95a8d4560..8a10d5847d33a86cfa86f8af3d3c23b1facef0c6)*

File: tests/ui/feature-gates/feature-gate-f32_from_f16.rs [hunk 3]
```diff
@@ -0,0 +1,7 @@
+#![feature(f16)]
+#![allow(unused)]
+
+pub fn main() {
+    let _: f32 = 1.0f16.into();
+    //~^ ERROR use of unstable library feature `f32_from_f16`
+}
```
Comment (folkertdev) [inline tests/ui/feature-gates/feature-gate-f32_from_f16.rs:7]: @jackh726 I've added a test for it here now.

File: compiler/rustc_lint_defs/src/builtin.rs [hunk 4]
```diff
@@ -5595,3 +5612,52 @@ declare_lint! {
...
+    /// has been tempoarily adjusted to fallback to `f32` in this scenario.
+    ///
+    /// The lint will automatically provide a machine-applicable suggestion to add a `_f32` suffix
+    /// to the literal, which will fix the problem.
+    ///
+    /// This is a [future-incompatible] lint to transition this to a hard error in the future. See
+    /// [issue #FIXME] for more details.
+    ///
+    /// [issue #FIXME]: https://github.com/rust-lang/rust/issues/FIXME
+    pub FLOAT_LITERAL_F32_FALLBACK,
```
Comment (traviscross) [inline compiler/rustc_lint_defs/src/builtin.rs:5689]: I had mused about whether this should be pluralized in the spirit of our RFC 0344 rules (and mentioned this at the end of the lang meeting today), but reflecting after the meeting, I agree the name as-is is correct.

In this case, "float literal" is an attributive noun.  I.e., we're answering the question, "what kind of fallback is this?"

Normally when we pluralize under the RFC 0344 rules, we're modifying the *head noun*, e.g., "unused variables".  But attributive nouns stay singular in English, e.g., "buffer overflow".

(The word "fallback" stays singular because it names a phenomenon, not a language construct, in the same spirit as `arithmetic-overflow`, `const-item-mutation`, and `unconditional-recursion`.)

**Comment by folkertdev** [comment]
This is already marked as ready for review but I think it truly is ready for review now.

File: compiler/rustc_lint_defs/src/builtin.rs [hunk 5]
```diff
@@ -5643,3 +5643,52 @@ declare_lint! {
...
+    /// falling back to `f64` would cause a compilation error; therefore, the float type fallback
+    /// has been tempoarily adjusted to fallback to `f32` in this scenario.
+    ///
+    /// The lint will automatically provide a machine-applicable suggestion to add a `_f32` suffix
+    /// to the literal, which will fix the problem.
+    ///
+    /// This is a [future-incompatible] lint to transition this to a hard error in the future. See
+    /// [issue #FIXME] for more details.
+    ///
+    /// [issue #FIXME]: https://github.com/rust-lang/rust/issues/FIXME
```
Comment (jackh726) [inline compiler/rustc_lint_defs/src/builtin.rs]: FIXME here needs to be updated.

File: tests/ui/feature-gates/feature-gate-f32_from_f16.rs [hunk 6]
```diff
@@ -0,0 +1,7 @@
+#![feature(f16)]
+#![allow(unused)]
+
+pub fn main() {
+    let _: f32 = 1.0f16.into();
+    //~^ ERROR use of unstable library feature `f32_from_f16`
```
Comment (jackh726) [inline tests/ui/feature-gates/feature-gate-f32_from_f16.rs:6]: Probably worth adding a test with both features on.

**Review by jackh726 — APPROVED** [review]
A couple small things, but r=me after.

*[View changes since this review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/rust/139087/17584a181979f04f2aaad867332c22db1caa511a..15fe926aaf88e7bed9dcac561166d5d6b294a26b)*

File: tests/ui/float/f16-into-f32.rs [hunk 7]
```diff
@@ -0,0 +1,17 @@
...
+// the correct location, and can be `expect`ed or `allow`ed.
+fn convert(x: impl Into<f32>) -> f32 {
+    x.into()
+}
+
+pub fn main() {
+    let _ = convert(1.0f32);
+    let _ = convert(1.0f16);
+    #[expect(float_literal_f32_fallback)]
+    let _ = convert(1.0);
```
Comment (folkertdev) [inline tests/ui/float/f16-into-f32.rs:16]: I ran into an issue here where the lint was emitted, but I could not `expect` it here. That's because the `HirId` used for the lint was `CRATE_HIR_ID`, hence the only way to silence the lint is at the crate level.

So now I've threaded through the `HirId` of the source expression. I think that should generally be available or propagated? I hope that is sufficient, I guess we can refine it if not.

@jackh726 can you quickly look at that commit? It doesn't do anything special but I might be overlooking something.

*[View changes since the review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/rust/139087/a5c825cd824ee0ef9463021078a2f464b4cc1a0d..534ffe36e6a69512ab87392e2ec055167e70ad6f)*

**Comment by Kobzol** [comment]
For some reason this seems to regress perf. with the new trait solver a bit. @lcnr Do you think it's worth digging into this?
