### PR TITLE
Fix bad diagnostics for anon params with ref and/or qualified paths

### LINKED ISSUE #82729: Upgrading to 2018 edition with nameless trait arguments gives opaque error message.
Given the following code: https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=2d5990f9266a843f299cffb49ea24f36

The current output is:
```
error: expected one of `(`, `...`, `..=`, `..`, `::`, `:`, `{`, or `|`, found `)`
 --> src/main.rs:3:46
  |
3 |     fn apply(&self, &mut <Self::G as Game>::S);
  |                                              ^ expected one of 8 possible tokens
```

Ideally the output should look like:
```
error: traits require argument names
```

This was very painful to debug, because there's some type shenanigans going on, and it wasn't clear if some of those didn't work in the 2018 edition now.

### PR DESCRIPTION
**Pull request by JohnTitor**
Fixes #82729
It's easier to review with hiding whitespace changes.

### CODE REVIEW

File: compiler/rustc_parse/src/parser/diagnostics.rs [hunk 1]
```diff
@@ -1613,42 +1613,65 @@ impl<'a> Parser<'a> {
...
+                PatKind::Ref(ref pat, mutab) => {
+                    if let PatKind::Ident(_, ident, _) = pat.clone().into_inner().kind {
+                        let mutab = mutab.prefix_str();
+                        (
+                            ident,
+                            format!("self: &{}{}", mutab, ident),
+                            format!("{}: &{}TypeName", ident, mutab),
+                            format!("_: &{}{}", mutab, ident),
+                        )
+                    } else {
```
Comment (estebank) [inline compiler/rustc_parse/src/parser/diagnostics.rs:1638]: @JohnTitor can you also add a test case for a fully qualified path, like in the original report? I get the feeling that the new code will work well _only_ for the case of `fn foo(&bar)` and not for `fn foo(&<Bar as T>::Baz)`. To handle the later, we might want to add a Parser snapshot here and try to parse a type. If successful, we know we can suggest `_: <Ty>` and recover the parser state.

Comment (JohnTitor) [reply compiler/rustc_parse/src/parser/diagnostics.rs:1638]: Good point! Yeah, the current `parameter_without_type` doesn't handle it with/without refs (1082ced). Should we address that case in this PR?

Comment (estebank) [reply compiler/rustc_parse/src/parser/diagnostics.rs]: You can see an example of what I mean here:

https://github.com/rust-lang/rust/blob/6f43f4c3fbc99c3a6699ed8d44608c8f086b10af/compiler/rustc_parse/src/parser/diagnostics.rs#L749-L761

You have a bounded lookahead to see that you might be in a weird known situation that will for sure emit an error. You clone the parser and try an alternative parse. If it is successful, you emit a targeted error, otherwise you "revert" the parser by overriding the parser state with your snapshot. Doing this you gain a lot of confidence in any suggestions you give because you _know_ that the alternative parse worked.

File: compiler/rustc_parse/src/parser/diagnostics.rs [hunk 2]
```diff
@@ -1613,42 +1613,75 @@ impl<'a> Parser<'a> {
...
-                        Applicability::HasPlaceholders,
-                    );
+                // Also catches `fn foo(<Bar as T>::Baz)`
+                PatKind::Path(..) => {
+                    err.note("anonymous parameters are removed in the 2018 edition (see RFC 1685)");
+                    return None;
                 }
+                // Ignore other `PatKind`.
+                _ => return None,
+            };
```
Comment (estebank) [inline compiler/rustc_parse/src/parser/diagnostics.rs:1654]: Using the snapshot strategy this can then be replaced with something like:

```rust
                PatKind::Ref(ref pat, mutab) if matches!(pat.clone().into_inner().kind, PatKind::Ident(_, ident, _)) => {
                    match pat.clone().into_inner().kind {
                        PatKind::Ident(_, ident, _) => {
                            let mutab = mutab.prefix_str();
                            (
                                ident,
                                format!("self: &{}{}", mutab, ident),
                                format!("{}: &{}TypeName", ident, mutab),
                                format!("_: &{}{}", mutab, ident),
                            )
                        }
                        _ => unreachable!(),
                    }
                }
                _ => {
                    let snapshot = self.clone();
                    match self.parse_ty_common(
                        AllowPlus::No,
                        AllowCVariadic::No,
                        RecoverQPath::No,
                        RecoverReturnSign::No,
                    ) {
                        Ok(ty) => {
                            err.span_suggestion_verbose(
                                pat.span,
                                "explicitly ignore the parameter name",
                                format!("_: {}", ty),
                                Applicability::MachineApplicable,
                            );
                            err.note("anonymous parameters are removed in the 2018 edition (see RFC 1685)");
                            return None;
                        }
                        Err(mut inner_err) => {
                            inner_err.cancel();
                            *self = snapshot;
                        }
                    }
                    return None,
                }
            };
```

Comment (estebank) [reply compiler/rustc_parse/src/parser/diagnostics.rs:1654]: Doing that we can even go further and actually bubble up the `ty` and continue to the type checking _as if_ the user _had_ written `_: `, but that is not entirely necessary.

Comment (JohnTitor) [reply compiler/rustc_parse/src/parser/diagnostics.rs]: Thanks for the pointer! Just copy-pasted your suggestion but the diagnostics don't seem to be changed (a6c75e8). Am I missing something?

Comment (estebank) [reply compiler/rustc_parse/src/parser/diagnostics.rs]: I think that `parse_ty_common` might not be the right thing to call then. Try using `parse_ty_for_param` (which should be almost the same thing, only `Yes` passed to all `parse_ty_common` arguments. Can you change the `inner_err.cancel();` to `inner_err.emit();`? I'm wondering whether it is taking that branch always and _why_.

Comment (JohnTitor) [reply compiler/rustc_parse/src/parser/diagnostics.rs]: Suggestions are applied via 01adaef. So looks like the parser looks at `)` and cannot find a type.

Comment (JohnTitor) [reply compiler/rustc_parse/src/parser/diagnostics.rs]: I've come up with another approach: call `to_ty()` and emit a suggestion if it successes, implemented via 2d99e68940087c7696a5d4919ba1456d6415fb9b.
@estebank Could you check it?

Comment (estebank) [reply compiler/rustc_parse/src/parser/diagnostics.rs]: Oh, that seems to work. Do we have a test for `fn foo(<A as B>::X, <C as D>::Y)`? I wonder how well this new method works with multiple arguments. Reviewing now, but I think it'll be ready to merge (and you can add a test if you have the time and r=me).

**Comment by estebank** [comment]
@bors r+

Feel free to update this PR with a multiple arg test if you get to it before bors does its thing.

File: compiler/rustc_parse/src/parser/diagnostics.rs (hunk 2 above)
Comment (JohnTitor) [reply compiler/rustc_parse/src/parser/diagnostics.rs]: Sure, added via 55bdf7f. The current rustc emits errors for each arg (https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=1a7575e24dd5fd79ad045613426147c2) and this PR's suggestion is also applied to both.
