### PR TITLE
Fix optimization regressions for operations on [x; n]-initialized arrays.

### LINKED ISSUE #35662: LLVM pointer range loop / autovectorization regression
The benchmarks in crate [matrixmultiply](https://github.com/bluss/matrixmultiply) version 0.1.8 degrade with MIR enabled. (commit https://github.com/bluss/matrixmultiply/commit/3d83647e7a4366e4483d711326f0f5cc07a61090)

Tested using `rustc 1.12.0-nightly (1deb02ea6 2016-08-12)`.

Typical output:

```
// -C target-cpu=native
test mat_mul_f32::m127             ... bench:   2,703,773 ns/iter (+/- 636,432)
// -Z orbit=off -C target-cpu=native
test mat_mul_f32::m127             ... bench:     648,817 ns/iter (+/- 22,379)
```

Sure, the matrix multiplication kernel uses some [major muckery](https://github.com/bluss/matrixmultiply/blob/3d83647e7a4366e4483d711326f0f5cc07a61090/src/sgemm_kernel.rs#L65-L92) that it expects the compiler to optimize down and autovectorize, but since it technically is a regression, it gets a report.

### PR DESCRIPTION
**Pull request by eddyb**
Fixes #35662 by using `!=` instead of `<` as the stop condition for `[x; n]` initialization loops.
Also included is https://github.com/eddyb/llvm/commit/cc2009f02d3b9a3c05be939978212e832310b3d6, a hack to run the GVN pass twice, another time after InstCombine.
This hack results in removal of redundant `memset` and `memcpy` calls (from loops over arrays).

cc @nrc Can we get performance numbers on this? Not sure if it regresses anything else.

### CODE REVIEW

**Comment by bluss** [comment]
Nice find. It should be much better this way, the optimizer prefers < / <= for an integer-counted loop and != for a pointer loop.

**Comment by eddyb** [comment]
@bluss You sure? Overflow shenanigans apply to both pointers and integers.
With `!=`, the distance for a monotonic loop is *guaranteed* to be `end - start`.
But with `<` or `<=` you don't know the `end` directly, you have to infer it (and sometimes you can't).
You can't even know if it loops at least once!
That is, `start != start + len` iff `len != 0` whereas `start < start + len` depends on `start` too.
In our case, it would be UB to cross the end of the address space, but still, it's more complicated.

**Comment by eddyb** [comment]
On IRC @nrc seems to think that it's easier to see what perf impact this has by getting it merged.
Also, @arielb1 mentioned that GVN is so fast we likely won't notice any change at all.

r? @alexcrichton

**Comment by alexcrichton** [comment]
Ok I've merged the LLVM commit, @eddyb wanna update the commit here?

**Comment by eddyb** [comment]
@alexcrichton @nrc @nikomatsakis This caused [a 4% regression](http://perf.rust-lang.org/graphs.html?start=Sat%20Sep%2003%202016%2018%3A24%3A01%20GMT%2B0000%20(UTC)&end=Sun%20Sep%2004%202016%2021%3A03%3A01%20GMT%2B0000%20(UTC)&kind=rustc&crates=total&phases=total&group_by=crate) in bootstrap time. Hopefully it's worth it.

**Comment by nikomatsakis** [comment]
The patch is tiny. I think it's worth backporting. I don't know what to make of the 4% regression. Could be a lot of things.

cc @rust-lang/compiler

**Comment by pnkfelix** [comment]
From skimming the [perf benchmarks](http://perf.rust-lang.org/graphs.html?start=2016-08-02T03%3A05%3A57%2B00%3A00&end=2016-09-20T15%3A01%3A01%2B00%3A00&kind=benchmarks&crates=futures-rs-test-all%2Chelloworld%2Chtml5ever-2016-08-25%2Chyper.0.5.0%2Cinflate-0.1.0%2Cissue-32062-equality-relations-complexity%2Cissue-32278-big-array-of-strings%2Cjld-day15-parser%2Cpiston-image-0.10.3%2Cpiston-image-0.3.11%2Cregex-macros.0.1.30%2Cregex.0.1.30%2Crust-encoding-0.3.0%2Crust-encoding.0.2.32%2Csyntex-0.42.2%2Csyntex-0.42.2-incr-clean&phases=total&group_by=crate) (rather than bootstrap) times, I think we can accept the risk associated with backporting this.

(There is a weird regression of the piston-image-0.10.3 benchmark, but if I understand the graph correctly, that is due to a commit that came *after* this PR...)

File: src/librustc_trans/tvec.rs [hunk 1]
```diff
@@ -52,7 +52,7 @@ pub fn slice_for_each<'blk, 'tcx, F>(bcx: Block<'blk, 'tcx>,
     let current = Phi(header_bcx, val_ty(start), &[start], &[bcx.llbb]);
 
     let keep_going =
-        ICmp(header_bcx, llvm::IntULT, current, end, DebugLoc::None);
```
Comment (nagisa) [inline src/librustc_trans/tvec.rs]: This is the only line that has to be applied to beta for backport.

Comment (eddyb) [inline src/librustc_trans/tvec.rs]: Without the LLVM change the regression isn't fully fixed, but yeah, this is the main part of it.
It might be in different places, so searching for `IntULT` used in an iteration loop condition should help.

Comment (nagisa) [inline src/librustc_trans/tvec.rs]: Beta is on LLVM commit further ahead now due to previous backport.

**Comment by nikomatsakis** [comment]
OK, I will go ahead and mark as beta-accepted. Backporter should note that backport can be quite minimum, per [@nagisa's comments here](https://github.com/rust-lang/rust/pull/36124#discussion_r79858356).

**Comment by brson** [comment]
I've started a backport.
