### PR TITLE
some additional `need_type_info.rs` cleanup

### LINKED ISSUE #97698: ICE: compiler/rustc_infer/src/infer/error_reporting/need_type_info.rs: unexpected path
### Code
kinda garbish-y but it reproduces the ICE :shrug: 
```Rust
use std::path::Path;

pub use self::imp::Lock;

#[cfg(unix)]
mod imp {
    use std::ffi::{CString, OsStr};
    use std::os::unix::prelude::*;
    use std::path::Path;
    use std::io;
    use libc;

  

    #[derive(Debug)]
    pub struct Lock {
        fd: libc::c_int,
    }

    impl Lock {
        pub fn new(p: &Path,
                   wait: bool,
                   create: bool,
                   exclusive: bool)
                   -> io::Result<Lock> {
            let os: &OsStr = p.as_ref();
            let buf = CString::new(os.as_bytes()).unwrap();
            let open_flags = if create {
                libc::O_RDWR | libc::O_CREAT
            } else {
                libc::O_RDWR
            };

            let fd = unsafe {
                libc::open(buf.as_ptr(), open_flags,
                           libc::S_IRWXU as libc::c_int)
            };

            let cmd = if wait { os::F_SETLKW } else { os::F_SETLK };
            let ret = unsafe {
                
            };
            if ret == -1 {
                let err = io::Error::last_os_error();
                unsafe { libc::close(fd); }
                Err(err)
            } else {
                Ok(Lock { fd: fd })
            }

        }
    }

}
```

### Meta

`rustc --version --verbose`:

IMPORTANT: this reproduces with MASTER but not yet with NIGHTLY `rustc 1.63.0-nightly (e71440575 2022-06-02)`
```
rustc 1.63.0-nightly (e40d5e83d 2022-06-03)
binary: rustc
commit-hash: e40d5e83dc133d093c22c7ff016b10daa4f40dcf
commit-date: 2022-06-03
host: x86_64-unknown-linux-gnu
release: 1.63.0-nightly
LLVM version: 14.0.4
```

### Error output

```
error[E0432]: unresolved import `libc`
  --> ./510c9ceef0960a8c8b6a20e3625ee6c2e10b4052.rs:11:9
   |
11 |     use libc;
   |         ^^^^ no `libc` in the root

error[E0433]: failed to resolve: use of undeclared crate or module `os`
  --> ./510c9ceef0960a8c8b6a20e3625ee6c2e10b4052.rs:39:33
   |
39 |             let cmd = if wait { os::F_SETLKW } else { os::F_SETLK };
   |                                 ^^ use of undeclared crate or module `os`

error[E0433]: failed to resolve: use of undeclared crate or module `os`
  --> ./510c9ceef0960a8c8b6a20e3625ee6c2e10b4052.rs:39:55
   |
39 |             let cmd = if wait { os::F_SETLKW } else { os::F_SETLK };
   |                                                       ^^ use of undeclared crate or module `os`

warning: unused import: `std::path::Path`
 --> ./510c9ceef0960a8c8b6a20e3625ee6c2e10b4052.rs:1:5
  |
1 | use std::path::Path;
  |     ^^^^^^^^^^^^^^^
  |
  = note: `#[warn(unused_imports)]` on by default

error[E0601]: `main` function not found in crate `510c9ceef0960a8c8b6a20e3625ee6c2e10b4052`
  --> ./510c9ceef0960a8c8b6a20e3625ee6c2e10b4052.rs:54:2
   |
54 | }
   |  ^ consider adding a `main` function to `./510c9ceef0960a8c8b6a20e3625ee6c2e10b4052.rs`

error[E0308]: mismatched types
  --> ./510c9ceef0960a8c8b6a20e3625ee6c2e10b4052.rs:43:23
   |
43 |             if ret == -1 {
   |                       ^^ expected `()`, found integer

error: internal compiler error: compiler/rustc_infer/src/infer/error_reporting/need_type_info.rs:856:33: unexpected path: def=alloc::ffi::c_str::CString substs=[] path=Path { span: ./510c9ceef0960a8c8b6a20e3625ee6c2e10b4052.rs:27:23: 27:30 (#0), res: Def(TyAlias, DefId(1:2774 ~ std[4f4f]::ffi::CString)), segments: [PathSegment { ident: CString#0, hir_id: Some(HirId { owner: DefId(0:28 ~ 510c9ceef0960a8c8b6a20e3625ee6c2e10b4052[d1fc]::imp::{impl#0}::new), local_id: 22 }), res: Some(Err), args: None, infer_args: true }] }

thread 'rustc' panicked at 'Box<dyn Any>', /rustc/e40d5e83dc133d093c22c7ff016b10daa4f40dcf/compiler/rustc_errors/src/lib.rs:1335:9
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
error: internal compiler error: compiler/rustc_infer/src/infer/error_reporting/need_type_info.rs:856:33: unexpected path: def=alloc::ffi::c_str::CString substs=[] path=Path { span: ./510c9ceef0960a8c8b6a20e3625ee6c2e10b4052.rs:27:23: 27:30 (#0), res: Def(TyAlias, DefId(1:2774 ~ std[4f4f]::ffi::CString)), segments: [PathSegment { ident: CString#0, hir_id: Some(HirId { owner: DefId(0:28 ~ 510c9ceef0960a8c8b6a20e3625ee6c2e10b4052[d1fc]::imp::{impl#0}::new), local_id: 22 }), res: Some(Err), args: None, infer_args: true }] }

thread 'rustc' panicked at 'Box<dyn Any>', /rustc/e40d5e83dc133d093c22c7ff016b10daa4f40dcf/compiler/rustc_errors/src/lib.rs:1335:9
stack backtrace:
   0:     0x7f6b6ec9decd - std::backtrace_rs::backtrace::libunwind::trace::hfcd45b45ae488cd5
                               at /rustc/e40d5e83dc133d093c22c7ff016b10daa4f40dcf/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x7f6b6ec9decd - std::backtrace_rs::backtrace::trace_unsynchronized::h405dac851f6cc6a8
                               at /rustc/e40d5e83dc133d093c22c7ff016b10daa4f40dcf/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7f6b6ec9decd - std::sys_common::backtrace::_print_fmt::h5f6c74a63449dd3f
                               at /rustc/e40d5e83dc133d093c22c7ff016b10daa4f40dcf/library/std/src/sys_common/backtrace.rs:66:5
   3:     0x7f6b6ec9decd - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h7d487462c277bf24
                               at /rustc/e40d5e83dc133d093c22c7ff016b10daa4f40dcf/library/std/src/sys_common/backtrace.rs:45:22
   4:     0x7f6b6ecf9bac - core::fmt::write::h832d0c8909aada18
                               at /rustc/e40d5e83dc133d093c22c7ff016b10daa4f40dcf/library/core/src/fmt/mod.rs:1196:17
   5:     0x7f6b6ec8f5c1 - std::io::Write::write_fmt::h65c8c1822edc4894
                               at /rustc/e40d5e83dc133d093c22c7ff016b10daa4f40dcf/library/std/src/io/mod.rs:1654:15
   6:     0x7f6b6eca0bb5 - std::sys_common::backtrace::_print::h560a0f4f262236c1
                               at /rustc/e40d5e83dc133d093c22c7ff016b10daa4f40dcf/library/std/src/sys_common/backtrace.rs:48:5
   7:     0x7f6b6eca0bb5 - std::sys_common::backtrace::print::h0080326ddadae76c
                               at /rustc/e40d5e83dc133d093c22c7ff016b10daa4f40dcf/library/std/src/sys_common/backtrace.rs:35:9
   8:     0x7f6b6eca0bb5 - std::panicking::default_hook::{{closure}}::hc726d21ea0224885
                               at /rustc/e40d5e83dc133d093c22c7ff016b10daa4f40dcf/library/std/src/panicking.rs:295:22
   9:     0x7f6b6eca08d6 - std::panicking::default_hook::hdcc52b852804bb0b
                               at /rustc/e40d5e83dc133d093c22c7ff016b10daa4f40dcf/library/std/src/panicking.rs:314:9
  10:     0x7f6b6f4f9f11 - rustc_driver[c7c8f2fedff45b54]::DEFAULT_HOOK::{closure#0}::{closure#0}
  11:     0x7f6b6eca128a - std::panicking::rust_panic_with_hook::h48930cf2efbb5ae2
                               at /rustc/e40d5e83dc133d093c22c7ff016b10daa4f40dcf/library/std/src/panicking.rs:702:17
  12:     0x7f6b705e7ae1 - std[4f4f1627d3880017]::panicking::begin_panic::<rustc_errors[65331a6f7e432222]::ExplicitBug>::{closure#0}
  13:     0x7f6b705e7556 - std[4f4f1627d3880017]::sys_common::backtrace::__rust_end_short_backtrace::<std[4f4f1627d3880017]::panicking::begin_panic<rustc_errors[65331a6f7e432222]::ExplicitBug>::{closure#0}, !>
  14:     0x7f6b7054ecf6 - std[4f4f1627d3880017]::panicking::begin_panic::<rustc_errors[65331a6f7e432222]::ExplicitBug>
  15:     0x7f6b70572b26 - std[4f4f1627d3880017]::panic::panic_any::<rustc_errors[65331a6f7e432222]::ExplicitBug>
  16:     0x7f6b705722e5 - <rustc_errors[65331a6f7e432222]::HandlerInner>::bug::<&alloc[31c74b9f3315cbc6]::string::String>
  17:     0x7f6b70571dc0 - <rustc_errors[65331a6f7e432222]::Handler>::bug::<&alloc[31c74b9f3315cbc6]::string::String>
  18:     0x7f6b705e4acd - rustc_middle[83233ac63f698a09]::ty::context::tls::with_opt::<rustc_middle[83233ac63f698a09]::util::bug::opt_span_bug_fmt<rustc_span[b73b5b7a1d5e4b08]::span_encoding::Span>::{closure#0}, ()>
  19:     0x7f6b705e4bc6 - rustc_middle[83233ac63f698a09]::util::bug::opt_span_bug_fmt::<rustc_span[b73b5b7a1d5e4b08]::span_encoding::Span>
  20:     0x7f6b705e4b43 - rustc_middle[83233ac63f698a09]::util::bug::bug_fmt
  21:     0x7f6b704a82ba - <rustc_infer[78bfaa2976d36a75]::infer::error_reporting::need_type_info::FindInferSourceVisitor>::path_inferred_subst_iter
  22:     0x7f6b704a8833 - <rustc_infer[78bfaa2976d36a75]::infer::error_reporting::need_type_info::FindInferSourceVisitor as rustc_hir[a9ca4d4e6c54b339]::intravisit::Visitor>::visit_expr
  23:     0x7f6b704a86cc - <rustc_infer[78bfaa2976d36a75]::infer::error_reporting::need_type_info::FindInferSourceVisitor as rustc_hir[a9ca4d4e6c54b339]::intravisit::Visitor>::visit_expr
  24:     0x7f6b704beb92 - rustc_hir[a9ca4d4e6c54b339]::intravisit::walk_expr::<rustc_infer[78bfaa2976d36a75]::infer::error_reporting::need_type_info::FindInferSourceVisitor>
  25:     0x7f6b704a86de - <rustc_infer[78bfaa2976d36a75]::infer::error_reporting::need_type_info::FindInferSourceVisitor as rustc_hir[a9ca4d4e6c54b339]::intravisit::Visitor>::visit_expr
  26:     0x7f6b704bb80c - rustc_hir[a9ca4d4e6c54b339]::intravisit::walk_local::<rustc_infer[78bfaa2976d36a75]::infer::error_reporting::need_type_info::FindInferSourceVisitor>
  27:     0x7f6b704a8348 - <rustc_infer[78bfaa2976d36a75]::infer::error_reporting::need_type_info::FindInferSourceVisitor as rustc_hir[a9ca4d4e6c54b339]::intravisit::Visitor>::visit_local
  28:     0x7f6b704bb657 - rustc_hir[a9ca4d4e6c54b339]::intravisit::walk_block::<rustc_infer[78bfaa2976d36a75]::infer::error_reporting::need_type_info::FindInferSourceVisitor>
  29:     0x7f6b704a86de - <rustc_infer[78bfaa2976d36a75]::infer::error_reporting::need_type_info::FindInferSourceVisitor as rustc_hir[a9ca4d4e6c54b339]::intravisit::Visitor>::visit_expr
  30:     0x7f6b70460f84 - <rustc_infer[78bfaa2976d36a75]::infer::InferCtxt>::emit_inference_failure_err
  31:     0x7f6b703b30c2 - <rustc_infer[78bfaa2976d36a75]::infer::InferCtxt as rustc_trait_selection[ae7a9636b275321f]::traits::error_reporting::InferCtxtPrivExt>::maybe_report_ambiguity
  32:     0x7f6b703a6c87 - <rustc_infer[78bfaa2976d36a75]::infer::InferCtxt as rustc_trait_selection[ae7a9636b275321f]::traits::error_reporting::InferCtxtExt>::report_fulfillment_errors
  33:     0x7f6b70af7af3 - <rustc_infer[78bfaa2976d36a75]::infer::InferCtxtBuilder>::enter::<&rustc_middle[83233ac63f698a09]::ty::context::TypeckResults, <rustc_typeck[412d93c49a5cfb7d]::check::inherited::InheritedBuilder>::enter<rustc_typeck[412d93c49a5cfb7d]::check::typeck_with_fallback<rustc_typeck[412d93c49a5cfb7d]::check::typeck::{closure#0}>::{closure#1}, &rustc_middle[83233ac63f698a09]::ty::context::TypeckResults>::{closure#0}>
  34:     0x7f6b70aa6efa - rustc_typeck[412d93c49a5cfb7d]::check::typeck
  35:     0x7f6b7109bbb4 - rustc_query_system[cd54684135f7aede]::query::plumbing::try_execute_query::<rustc_query_impl[5d43592eeec5f58a]::plumbing::QueryCtxt, rustc_query_system[cd54684135f7aede]::query::caches::DefaultCache<rustc_span[b73b5b7a1d5e4b08]::def_id::LocalDefId, &rustc_middle[83233ac63f698a09]::ty::context::TypeckResults>>
  36:     0x7f6b7107623e - <rustc_query_impl[5d43592eeec5f58a]::Queries as rustc_middle[83233ac63f698a09]::ty::query::QueryEngine>::typeck
  37:     0x7f6b70b55ee8 - <rustc_middle[83233ac63f698a09]::hir::map::Map>::par_body_owners::<rustc_typeck[412d93c49a5cfb7d]::check::typeck_item_bodies::{closure#0}>
  38:     0x7f6b71936a7c - rustc_typeck[412d93c49a5cfb7d]::check::typeck_item_bodies
  39:     0x7f6b71c303ac - rustc_query_system[cd54684135f7aede]::query::plumbing::try_execute_query::<rustc_query_impl[5d43592eeec5f58a]::plumbing::QueryCtxt, rustc_query_system[cd54684135f7aede]::query::caches::DefaultCache<(), ()>>
  40:     0x7f6b71c5a8b1 - rustc_query_system[cd54684135f7aede]::query::plumbing::get_query::<rustc_query_impl[5d43592eeec5f58a]::queries::typeck_item_bodies, rustc_query_impl[5d43592eeec5f58a]::plumbing::QueryCtxt>
  41:     0x7f6b7196d3f3 - <rustc_session[3dcad23083b71834]::session::Session>::time::<(), rustc_typeck[412d93c49a5cfb7d]::check_crate::{closure#7}>
  42:     0x7f6b7194a77b - rustc_typeck[412d93c49a5cfb7d]::check_crate
  43:     0x7f6b716e3a57 - rustc_interface[d21641337a9fbe3]::passes::analysis
  44:     0x7f6b71c2649f - rustc_query_system[cd54684135f7aede]::query::plumbing::try_execute_query::<rustc_query_impl[5d43592eeec5f58a]::plumbing::QueryCtxt, rustc_query_system[cd54684135f7aede]::query::caches::DefaultCache<(), core[e20aa153a98323b0]::result::Result<(), rustc_errors[65331a6f7e432222]::ErrorGuaranteed>>>
  45:     0x7f6b71c6ce2e - rustc_query_system[cd54684135f7aede]::query::plumbing::get_query::<rustc_query_impl[5d43592eeec5f58a]::queries::analysis, rustc_query_impl[5d43592eeec5f58a]::plumbing::QueryCtxt>
  46:     0x7f6b716c6a07 - <rustc_interface[d21641337a9fbe3]::passes::QueryContext>::enter::<rustc_driver[c7c8f2fedff45b54]::run_compiler::{closure#1}::{closure#2}::{closure#3}, core[e20aa153a98323b0]::result::Result<(), rustc_errors[65331a6f7e432222]::ErrorGuaranteed>>
  47:     0x7f6b716b0cc8 - <rustc_interface[d21641337a9fbe3]::interface::Compiler>::enter::<rustc_driver[c7c8f2fedff45b54]::run_compiler::{closure#1}::{closure#2}, core[e20aa153a98323b0]::result::Result<core[e20aa153a98323b0]::option::Option<rustc_interface[d21641337a9fbe3]::queries::Linker>, rustc_errors[65331a6f7e432222]::ErrorGuaranteed>>
  48:     0x7f6b716d44df - rustc_span[b73b5b7a1d5e4b08]::with_source_map::<core[e20aa153a98323b0]::result::Result<(), rustc_errors[65331a6f7e432222]::ErrorGuaranteed>, rustc_interface[d21641337a9fbe3]::interface::create_compiler_and_run<core[e20aa153a98323b0]::result::Result<(), rustc_errors[65331a6f7e432222]::ErrorGuaranteed>, rustc_driver[c7c8f2fedff45b54]::run_compiler::{closure#1}>::{closure#1}>
  49:     0x7f6b716b18f2 - <scoped_tls[f8b3eb90e665007e]::ScopedKey<rustc_span[b73b5b7a1d5e4b08]::SessionGlobals>>::set::<rustc_interface[d21641337a9fbe3]::interface::run_compiler<core[e20aa153a98323b0]::result::Result<(), rustc_errors[65331a6f7e432222]::ErrorGuaranteed>, rustc_driver[c7c8f2fedff45b54]::run_compiler::{closure#1}>::{closure#0}, core[e20aa153a98323b0]::result::Result<(), rustc_errors[65331a6f7e432222]::ErrorGuaranteed>>
  50:     0x7f6b716c708f - std[4f4f1627d3880017]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[d21641337a9fbe3]::util::run_in_thread_pool_with_globals<rustc_interface[d21641337a9fbe3]::interface::run_compiler<core[e20aa153a98323b0]::result::Result<(), rustc_errors[65331a6f7e432222]::ErrorGuaranteed>, rustc_driver[c7c8f2fedff45b54]::run_compiler::{closure#1}>::{closure#0}, core[e20aa153a98323b0]::result::Result<(), rustc_errors[65331a6f7e432222]::ErrorGuaranteed>>::{closure#0}, core[e20aa153a98323b0]::result::Result<(), rustc_errors[65331a6f7e432222]::ErrorGuaranteed>>
  51:     0x7f6b716c71c9 - <<std[4f4f1627d3880017]::thread::Builder>::spawn_unchecked_<rustc_interface[d21641337a9fbe3]::util::run_in_thread_pool_with_globals<rustc_interface[d21641337a9fbe3]::interface::run_compiler<core[e20aa153a98323b0]::result::Result<(), rustc_errors[65331a6f7e432222]::ErrorGuaranteed>, rustc_driver[c7c8f2fedff45b54]::run_compiler::{closure#1}>::{closure#0}, core[e20aa153a98323b0]::result::Result<(), rustc_errors[65331a6f7e432222]::ErrorGuaranteed>>::{closure#0}, core[e20aa153a98323b0]::result::Result<(), rustc_errors[65331a6f7e432222]::ErrorGuaranteed>>::{closure#1} as core[e20aa153a98323b0]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  52:     0x7f6b6ecab1b3 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h3752e20e7af2922b
                               at /rustc/e40d5e83dc133d093c22c7ff016b10daa4f40dcf/library/alloc/src/boxed.rs:1951:9
  53:     0x7f6b6ecab1b3 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hea44272e5391750e
                               at /rustc/e40d5e83dc133d093c22c7ff016b10daa4f40dcf/library/alloc/src/boxed.rs:1951:9
  54:     0x7f6b6ecab1b3 - std::sys::unix::thread::Thread::new::thread_start::h6d31b3f92a2b25ea
                               at /rustc/e40d5e83dc133d093c22c7ff016b10daa4f40dcf/library/std/src/sys/unix/thread.rs:108:17
  55:     0x7f6b6ea835c2 - start_thread
  56:     0x7f6b6eb08584 - __clone
  57:                0x0 - <unknown>

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.63.0-nightly (e40d5e83d 2022-06-03) running on x86_64-unknown-linux-gnu

query stack during panic:
#0 [typeck] type-checking `imp::<impl at ./510c9ceef0960a8c8b6a20e3625ee6c2e10b4052.rs:20:5: 52:6>::new`
#1 [typeck_item_bodies] type-checking all item bodies
#2 [analysis] running analysis passes on this crate
end of query stack
error: aborting due to 6 previous errors; 1 warning emitted

Some errors have detailed explanations: E0308, E0432, E0433, E0601.
For more information about an error, try `rustc --explain E0308`.
```

</p>
</details>

### LINKED ISSUE #97806: ICE: need_type_info unexpected path
### Code

```Rust
struct TestErr<T> {
     field: std::marker::PhantomData<T>,
}

impl<T> TestErr<T> {
    fn func_a() {}

    fn func_b() {
        Self::func_a();

        let variable = None;
    }
}
```

This may be related to https://github.com/rust-lang/rust/issues/97698

### Meta

`rustc --version --verbose`:
```
rustc 1.63.0-nightly (fee3a459d 2022-06-05)
binary: rustc
commit-hash: fee3a459dd6aba8e34a5b99f0fbcb4218a1e2401
commit-date: 2022-06-05
host: x86_64-pc-windows-msvc
release: 1.63.0-nightly
LLVM version: 14.0.5
```

### Error output

```
error: internal compiler error: compiler\rustc_infer\src\infer\error_reporting\need_type_info.rs:856:33: unexpected path
: def=TestErr substs=[_] path=Path { span: src\lib.rs:9:9: 9:13 (#0), res: SelfTy { trait_: None, alias_to: Some((DefId(
0:6 ~ test2[211d]::{impl#0}), false)) }, segments: [PathSegment { ident: Self#0, hir_id: Some(HirId { owner: DefId(0:9 ~
 test2[211d]::{impl#0}::func_b), local_id: 3 }), res: Some(SelfTy { trait_: None, alias_to: Some((DefId(0:6 ~ test2[211d
]::{impl#0}), false)) }), args: None, infer_args: true }] }

thread 'rustc' panicked at 'Box<dyn Any>', /rustc/fee3a459dd6aba8e34a5b99f0fbcb4218a1e2401\compiler\rustc_errors\src\lib
.rs:1335:9

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler
&template=ice.md

note: rustc 1.63.0-nightly (fee3a459d 2022-06-05) running on x86_64-pc-windows-msvc

note: compiler flags: --crate-type lib -C embed-bitcode=no -C debuginfo=2 -C incremental -C target-cpu=native

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [typeck] type-checking `<impl at src\lib.rs:5:1: 13:2>::func_b`
#1 [typeck_item_bodies] type-checking all item bodies
#2 [analysis] running analysis passes on this crate
end of query stack
error: could not compile `test2`
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
stack backtrace:
   0:     0x7ffbf81d9d1f - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hf9140f961
aae3bca
   1:     0x7ffbf8214d1a - core::fmt::write::h83e4325296b41ee9
   2:     0x7ffbf81cc119 - <std::io::IoSliceMut as core::fmt::Debug>::fmt::h3cbc46f9c04c9110
   3:     0x7ffbf81dd60b - std::panicking::default_hook::h4ed310d63b7aad19
   4:     0x7ffbf81dd28b - std::panicking::default_hook::h4ed310d63b7aad19
   5:     0x7ffbdecfa0f6 - rustc_driver[5ceae6c45f539b20]::pretty::print_after_hir_lowering
   6:     0x7ffbf81dddb2 - std::panicking::rust_panic_with_hook::hb7db12ea91edbe64
   7:     0x7ffbe3313bc5 - <rustc_middle[b17ff1f261c866a1]::mir::visit::PlaceContext as core[2f4fddafc238f4ec]::fmt::Deb
ug>::fmt
   8:     0x7ffbe33120d9 - <rustc_middle[b17ff1f261c866a1]::mir::visit::PlaceContext as core[2f4fddafc238f4ec]::fmt::Deb
ug>::fmt
   9:     0x7ffbe3801c09 - rustc_middle[b17ff1f261c866a1]::util::bug::bug_fmt
  10:     0x7ffbe32b19e9 - <rustc_middle[b17ff1f261c866a1]::ty::sty::TypeAndMut as rustc_middle[b17ff1f261c866a1]::ty::c
ontext::Lift>::lift_to_tcx
  11:     0x7ffbe3298083 - <rustc_middle[b17ff1f261c866a1]::ty::sty::TypeAndMut as rustc_middle[b17ff1f261c866a1]::ty::c
ontext::Lift>::lift_to_tcx
  12:     0x7ffbe3295db2 - <rustc_middle[b17ff1f261c866a1]::ty::sty::TypeAndMut as rustc_middle[b17ff1f261c866a1]::ty::c
ontext::Lift>::lift_to_tcx
  13:     0x7ffbe331fbc9 - <rustc_middle[b17ff1f261c866a1]::ty::consts::int::ScalarInt as core[2f4fddafc238f4ec]::fmt::D
isplay>::fmt
  14:     0x7ffbe331fc4c - <rustc_middle[b17ff1f261c866a1]::ty::consts::int::ScalarInt as core[2f4fddafc238f4ec]::fmt::D
isplay>::fmt
  15:     0x7ffbe3801bb8 - rustc_middle[b17ff1f261c866a1]::util::bug::bug_fmt
  16:     0x7ffbe3152219 - <rustc_infer[6954ca37551801a9]::infer::error_reporting::need_type_info::TypeAnnotationNeeded
as core[2f4fddafc238f4ec]::convert::Into<rustc_errors[62a8d79a6ebe4f2c]::diagnostic::DiagnosticId>>::into
  17:     0x7ffbe315296a - <rustc_infer[6954ca37551801a9]::infer::error_reporting::need_type_info::FindInferSourceVisito
r as rustc_hir[329a2e92ed33dca0]::intravisit::Visitor>::visit_expr
  18:     0x7ffbe3152720 - <rustc_infer[6954ca37551801a9]::infer::error_reporting::need_type_info::FindInferSourceVisito
r as rustc_hir[329a2e92ed33dca0]::intravisit::Visitor>::visit_expr
  19:     0x7ffbe3179c0d - <rustc_middle[b17ff1f261c866a1]::ty::sty::ProjectionTy as rustc_infer[6954ca37551801a9]::infe
r::at::ToTrace>::to_trace
  20:     0x7ffbe3152734 - <rustc_infer[6954ca37551801a9]::infer::error_reporting::need_type_info::FindInferSourceVisito
r as rustc_hir[329a2e92ed33dca0]::intravisit::Visitor>::visit_expr
  21:     0x7ffbe309df11 - <rustc_infer[6954ca37551801a9]::infer::InferCtxt>::emit_inference_failure_err
  22:     0x7ffbe3054dac - <rustc_infer[6954ca37551801a9]::infer::InferCtxt as rustc_trait_selection[2cc1a302a0c8a46f]::
traits::error_reporting::InferCtxtPrivExt>::maybe_report_ambiguity
  23:     0x7ffbe3041115 - <rustc_infer[6954ca37551801a9]::infer::InferCtxt as rustc_trait_selection[2cc1a302a0c8a46f]::
traits::error_reporting::InferCtxtExt>::report_fulfillment_errors
  24:     0x7ffbe16a6514 - <rustc_typeck[1da886d7d77884b0]::check::fn_ctxt::FnCtxt>::apply_adjustments
  25:     0x7ffbe173401b - <rustc_typeck[1da886d7d77884b0]::collect::type_of::find_opaque_ty_constraints::ConstraintLoca
tor as rustc_hir[329a2e92ed33dca0]::intravisit::Visitor>::visit_trait_item
  26:     0x7ffbe16fbe02 - rustc_typeck[1da886d7d77884b0]::check::provide
  27:     0x7ffbe227b628 - <rustc_query_impl[4eb9394896c41b4e]::queries::generator_diagnostic_data as rustc_query_system
[93ec4419bf33f6fc]::query::config::QueryDescription<rustc_query_impl[4eb9394896c41b4e]::plumbing::QueryCtxt>>::describe
  28:     0x7ffbe25a6222 - <&[rustc_span[f3561307c7d48550]::def_id::LocalDefId] as rustc_serialize[d89fb95351769db2]::se
rialize::Decodable<rustc_query_impl[4eb9394896c41b4e]::on_disk_cache::CacheDecoder>>::decode
  29:     0x7ffbe241bbb7 - <&[rustc_span[f3561307c7d48550]::def_id::LocalDefId] as rustc_serialize[d89fb95351769db2]::se
rialize::Decodable<rustc_query_impl[4eb9394896c41b4e]::on_disk_cache::CacheDecoder>>::decode
  30:     0x7ffbe2562e08 - <&[rustc_span[f3561307c7d48550]::def_id::LocalDefId] as rustc_serialize[d89fb95351769db2]::se
rialize::Decodable<rustc_query_impl[4eb9394896c41b4e]::on_disk_cache::CacheDecoder>>::decode
  31:     0x7ffbe1561521 - <rustc_typeck[1da886d7d77884b0]::check::upvar::InferBorrowKind as rustc_typeck[1da886d7d77884
b0]::expr_use_visitor::Delegate>::mutate
  32:     0x7ffbe17022a3 - <rustc_typeck[1da886d7d77884b0]::check::MaybeInProgressTables>::borrow_mut
  33:     0x7ffbe227d41e - <rustc_query_impl[4eb9394896c41b4e]::queries::generator_diagnostic_data as rustc_query_system
[93ec4419bf33f6fc]::query::config::QueryDescription<rustc_query_impl[4eb9394896c41b4e]::plumbing::QueryCtxt>>::describe
  34:     0x7ffbe25ce68f - <&[rustc_span[f3561307c7d48550]::def_id::LocalDefId] as rustc_serialize[d89fb95351769db2]::se
rialize::Decodable<rustc_query_impl[4eb9394896c41b4e]::on_disk_cache::CacheDecoder>>::decode
  35:     0x7ffbe24b44b9 - <&[rustc_span[f3561307c7d48550]::def_id::LocalDefId] as rustc_serialize[d89fb95351769db2]::se
rialize::Decodable<rustc_query_impl[4eb9394896c41b4e]::on_disk_cache::CacheDecoder>>::decode
  36:     0x7ffbe252d599 - <&[rustc_span[f3561307c7d48550]::def_id::LocalDefId] as rustc_serialize[d89fb95351769db2]::se
rialize::Decodable<rustc_query_impl[4eb9394896c41b4e]::on_disk_cache::CacheDecoder>>::decode
  37:     0x7ffbe157d8cf - <rustc_typeck[1da886d7d77884b0]::expr_use_visitor::ExprUseVisitor>::consume_body
  38:     0x7ffbe155bdd6 - rustc_typeck[1da886d7d77884b0]::check_crate
  39:     0x7ffbdede960f - rustc_interface[6179e6dd00003194]::passes::analysis
  40:     0x7ffbe227cf0e - <rustc_query_impl[4eb9394896c41b4e]::queries::generator_diagnostic_data as rustc_query_system
[93ec4419bf33f6fc]::query::config::QueryDescription<rustc_query_impl[4eb9394896c41b4e]::plumbing::QueryCtxt>>::describe
  41:     0x7ffbe25c503f - <&[rustc_span[f3561307c7d48550]::def_id::LocalDefId] as rustc_serialize[d89fb95351769db2]::se
rialize::Decodable<rustc_query_impl[4eb9394896c41b4e]::on_disk_cache::CacheDecoder>>::decode
  42:     0x7ffbe249e3bb - <&[rustc_span[f3561307c7d48550]::def_id::LocalDefId] as rustc_serialize[d89fb95351769db2]::se
rialize::Decodable<rustc_query_impl[4eb9394896c41b4e]::on_disk_cache::CacheDecoder>>::decode
  43:     0x7ffbe2563216 - <&[rustc_span[f3561307c7d48550]::def_id::LocalDefId] as rustc_serialize[d89fb95351769db2]::se
rialize::Decodable<rustc_query_impl[4eb9394896c41b4e]::on_disk_cache::CacheDecoder>>::decode
  44:     0x7ffbdecaf6af - <rustc_driver[5ceae6c45f539b20]::args::Error as core[2f4fddafc238f4ec]::fmt::Debug>::fmt
  45:     0x7ffbdec87370 - <rustc_lint[88f370ff989524bb]::BuiltinCombinedLateLintPass as rustc_lint[88f370ff989524bb]::p
asses::LateLintPass>::check_local
  46:     0x7ffbded08895 - <rustc_driver[5ceae6c45f539b20]::Compilation as core[2f4fddafc238f4ec]::fmt::Debug>::fmt
  47:     0x7ffbdec885cd - <rustc_lint[88f370ff989524bb]::BuiltinCombinedLateLintPass as rustc_lint[88f370ff989524bb]::p
asses::LateLintPass>::check_local
  48:     0x7ffbdecef5c6 - <rustc_metadata[bf9ab9df0d2c4d9d]::rmeta::encoder::EncodeContext as rustc_serialize[d89fb9535
1769db2]::serialize::Encoder>::emit_raw_bytes
  49:     0x7ffbdecb2798 - <rustc_driver[5ceae6c45f539b20]::args::Error as core[2f4fddafc238f4ec]::fmt::Debug>::fmt
  50:     0x7ffbf81eef5c - std::sys::windows::thread::Thread::new::hf6581a2a4a7d3e64
  51:     0x7ffc34017034 - BaseThreadInitThunk
  52:     0x7ffc34942651 - RtlUserThreadStart
```

</p>
</details>

### PR DESCRIPTION
**Pull request by lcnr**
also fixes #97698, fixes #97806

cc @estebank

### CODE REVIEW

File: compiler/rustc_infer/src/infer/error_reporting/need_type_info.rs [hunk 1]
```diff
@@ -853,12 +854,20 @@ impl<'a, 'tcx> FindInferSourceVisitor<'a, 'tcx> {
...
-                                );
+                                match path.res {
+                                    Res::Def(DefKind::TyAlias, _) => {
+                                        // FIXME: Ideally we should support this. For that
+                                        // we have to map back from the self type to the
+                                        // type alias though. That's difficult.
+                                        //
+                                        // See the `need_type_info/type-alias.rs` test for
+                                        // some examples.
+                                    }
```
Comment (estebank) [inline compiler/rustc_infer/src/infer/error_reporting/need_type_info.rs:865]: @oli-obk you might want to chime in here

File: compiler/rustc_infer/src/infer/error_reporting/need_type_info.rs [hunk 2]
```diff
@@ -853,12 +854,20 @@ impl<'a, 'tcx> FindInferSourceVisitor<'a, 'tcx> {
...
+                                    _ => warn!(
+                                        "unexpected path: def={:?} substs={:?} path={:?}",
+                                        def, substs, path,
+                                    ),
```
Comment (estebank) [inline compiler/rustc_infer/src/infer/error_reporting/need_type_info.rs:869]: Is turning this into a `warn` instead of `bug` intended?

File: compiler/rustc_infer/src/infer/error_reporting/need_type_info.rs [hunk 3]
```diff
@@ -958,26 +967,8 @@ impl<'a, 'tcx> Visitor<'tcx> for FindInferSourceVisitor<'a, 'tcx> {
...
-                            default.subst(tcx, substs) == substs[param.index as usize]
-                        } else {
-                            false
-                        }
-                    })
-                    .count();
-                let generic_args =
-                    &generics.own_substs(substs)[generics.own_counts().lifetimes..][..num_args];
+                let generic_args = &generics.own_substs_no_defaults(tcx, substs)
+                    [generics.own_counts().lifetimes..];
```
Comment (estebank) [inline compiler/rustc_infer/src/infer/error_reporting/need_type_info.rs:971]: Weird rustfmt 👀

File: compiler/rustc_infer/src/infer/error_reporting/need_type_info.rs (hunk 2 above)
Comment (lcnr) [reply compiler/rustc_infer/src/infer/error_reporting/need_type_info.rs:869]: yeah, don't want to ICE here and it only worsens diagnostics.

feels safer than using a `bug!`

File: compiler/rustc_middle/src/ty/generics.rs [hunk 4]
```diff
@@ -228,8 +228,43 @@ impl<'tcx> Generics {
         })
     }
 
+    /// Returns the substs corresponding to the generic parameters
+    /// of this item, excluding `Self`.
+    pub fn own_substs_no_defaults(
```
Comment (estebank) [inline compiler/rustc_middle/src/ty/generics.rs:233]: Let's make it clear in the naming and docs that this is only meant for use in diagnostics code.

File: compiler/rustc_infer/src/infer/error_reporting/need_type_info.rs (hunk 1 above)
Comment (oli-obk) [reply compiler/rustc_infer/src/infer/error_reporting/need_type_info.rs:865]: @GuillaumeGomez is working on it

Comment (GuillaumeGomez) [reply compiler/rustc_infer/src/infer/error_reporting/need_type_info.rs:865]: Moving slowly but surely! (you can take a look at my work in progress there: https://github.com/rust-lang/rust/compare/master...GuillaumeGomez:rustc-middle-ty-alias?expand=1)

File: src/test/ui/const-generics/defaults/rp_impl_trait_fail.stderr [hunk 5]
```diff
@@ -6,21 +6,21 @@ LL | fn rawr() -> impl Trait {
    |
    = help: the trait `Trait` is implemented for `Uwu<N>`
 
-error[E0277]: the trait bound `u32: Traitor<N, N>` is not satisfied
+error[E0277]: the trait bound `u32: Traitor<N>` is not satisfied
   --> $DIR/rp_impl_trait_fail.rs:17:26
    |
 LL | fn uwu<const N: u8>() -> impl Traitor<N> {
-   |                          ^^^^^^^^^^^^^^^ the trait `Traitor<N, N>` is not implemented for `u32`
+   |                          ^^^^^^^^^^^^^^^ the trait `Traitor<N>` is not implemented for `u32`
```
Comment (estebank) [inline src/test/ui/const-generics/defaults/rp_impl_trait_fail.stderr:13]: The output for the full trait path seems off. Why are we only showing a single const now in these files?

File: compiler/rustc_infer/src/infer/error_reporting/need_type_info.rs (hunk 2 above)
Comment (estebank) [reply compiler/rustc_infer/src/infer/error_reporting/need_type_info.rs:869]: What about using `delay_span_bug` instead?

File: src/test/ui/const-generics/defaults/rp_impl_trait_fail.stderr (hunk 5 above)
Comment (lcnr) [reply src/test/ui/const-generics/defaults/rp_impl_trait_fail.stderr:13]: because it's `Traitor<N = 1, M = N>`. So we now correctly elide defaults here.

The previous code only looked at type defaults

File: compiler/rustc_infer/src/infer/error_reporting/need_type_info.rs (hunk 2 above)
Comment (lcnr) [reply compiler/rustc_infer/src/infer/error_reporting/need_type_info.rs:869]: `delay_span_bug` won't ever trigger, considering that we're always emitting an error

File: compiler/rustc_middle/src/ty/generics.rs (hunk 4 above)
Comment (lcnr) [reply compiler/rustc_middle/src/ty/generics.rs:233]: added a comment, don't want to make these method names even more unwieldy :sweat_smile:

File: compiler/rustc_infer/src/infer/error_reporting/need_type_info.rs [hunk 6]
```diff
@@ -958,26 +970,8 @@ impl<'a, 'tcx> Visitor<'tcx> for FindInferSourceVisitor<'a, 'tcx> {
...
-                            // then use `infcx.can_eq`. That probably should be a separate method
-                            // generally used during error reporting.
-                            default.subst(tcx, substs) == substs[param.index as usize]
-                        } else {
-                            false
-                        }
-                    })
-                    .count();
-                let generic_args =
-                    &generics.own_substs(substs)[generics.own_counts().lifetimes..][..num_args];
```
Comment (lcnr) [inline compiler/rustc_infer/src/infer/error_reporting/need_type_info.rs:980]: that causes the ICE in https://github.com/rust-lang/rust/issues/97698#issuecomment-1146565300. Writing big PRs sure is difficult :sweat_smile:
