### PR TITLE
Fix regression introduced by jQuery removal

### LINKED ISSUE #42078: Nightly documentation is broken
In particular, now it is unable to use the search in it.

Screenshots:

* [stable std](http://c2n.me/3KvUan4.png) page: [search works](http://c2n.me/3KvUjLk.png)
* [nightly std](http://c2n.me/3KvUfB3.png) page

Looks like it was due to #41307 which source was in #39159.

Unfortunately these changes broke some browsers.

@frewsxcv 

>  I'm not really in favor of the removal personally unless we have thorough testing on all the browsers we support

Where I can see a list of supported browsers? Because the whole Rust-related documentation (doc.rust-lang.org, docs.rs, crate docs) are broken now due to "Let's rewrite anything!" impulse.

cc @steveklabnik 

> As long as we don't regress browsers badly (which I don't think we do)

Unfortunately it happened.

### PR DESCRIPTION
**Pull request by pravic**
Fixes #42078.
Follows #41307.

r? @steveklabnik 
cc @frewsxcv

### CODE REVIEW

File: src/librustdoc/html/static/main.js [hunk 1]
```diff
@@ -215,14 +215,14 @@
         } else if (ev.target.tagName === 'SPAN' && hasClass(ev.target.parentNode, 'line-numbers')) {
             var prev_id = 0;
 
-            function set_fragment(name) {
```
Comment (frewsxcv) [inline src/librustdoc/html/static/main.js]: why is this change needed?

File: src/librustdoc/html/static/main.js [hunk 2]
```diff
@@ -685,7 +685,7 @@
         }
 
         function escape(content) {
-            let h1 = document.createElement('h1');
```
Comment (frewsxcv) [inline src/librustdoc/html/static/main.js]: out of curiosity, which browser are you using that doesn't support `let`?

Comment (pravic) [inline src/librustdoc/html/static/main.js]: Opera 12.

File: src/librustdoc/html/static/main.js (hunk 1 above)
Comment (pravic) [inline src/librustdoc/html/static/main.js]: Because ES5 do not allow function declaration here.

Comment (frewsxcv) [inline src/librustdoc/html/static/main.js]: it's not clear to me why ES5 wouldn't accept this, but not a big deal, seems fine to me

File: src/librustdoc/html/static/main.js (hunk 2 above)
Comment (steveklabnik) [inline src/librustdoc/html/static/main.js]: Opera 12 is from 2012, so that makes sense. 😅 I don't mind making this change, as it's pretty small, but it is very unlikely that we won't end up doing something that breaks it in the future.

File: src/librustdoc/html/static/main.js (hunk 1 above)
Comment (pravic) [inline src/librustdoc/html/static/main.js]: For example: http://stackoverflow.com/a/25111212

Comment (frewsxcv) [inline src/librustdoc/html/static/main.js]: oh interesting! wasn't aware of that detail, thanks for sharing!
