### PR TITLE
Tweak borrow error on `FnMut` when `Fn` is expected

### LINKED ISSUE #31701: Not sufficiently useful error message when FnMut is needed instead of Fn
This code:

``` rust
fn counter() -> Box<Fn() -> usize> {
    let mut x = 0;
    Box::new(move || {
        x += 1;
        x
    })
}
```

results in [the following error messages](https://play.rust-lang.org/?gist=7381046af7c70d49d344&version=stable) in stable:

```
<anon>:4:9: 4:15 error: cannot assign to captured outer variable in an `Fn` closure
<anon>:4         x += 1;
                 ^~~~~~
<anon>:3:14: 6:6 help: consider changing this closure to take self by mutable reference
<anon>:3     Box::new(move || {
<anon>:4         x += 1;
<anon>:5         x
<anon>:6     })
```

The problem here is that we're using `Fn()` instead of `FnMut()`, but the phrase "consider changing this closure to take self by mutable reference" is not particularly useful in telling us that that specifically is the problem. That is, the fact that we cannot assign to the captured outer variable is because we are trying to return `Box<Fn() -> usize>` instead of `Box<FnMut() -> usize>`, but that's not immediately clear from the original error message.

I'm not _entirely_ sure how this would be rectified, but at the very least mentioning `FnMut` somewhere would be useful. @eddyb mentioned that this issue was "because a bound/trait object of `Fn()` was used but only `FnMut()` allows mutable borrows", so I think some variation on that would be reasonably sufficient to clarify the error.

### LINKED ISSUE #66097: Confusing span in `FnMut` closure diagnostic
```rust
#![feature(unboxed_closures)]

fn to_fn<A, F:Fn<A>>(f: F) -> F { f }

fn main() {
    let mut x = 0;
    let _f = to_fn(|| x = 42); //~ ERROR cannot assign to `x`
}
```
```
help: consider changing this to accept closures that implement `FnMut`
  --> $DIR/borrow-immutable-upvar-mutation.rs:15:24
   |
LL |         let _f = to_fn(|| x = 42);
   |                        ^^^^^^^^^
```
This is confusing, as it appears to suggest the user change the *closure* to "accept closures". [The span is incorrect](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=191c8aeaf6733be948b56d7e0ae508b8): we should use the span of the function `to_fn`, not the span of the closure.

### PR DESCRIPTION
**Pull request by estebank**
Fix #31701, fix #66097.

### CODE REVIEW

File: src/librustc_mir/borrow_check/diagnostics/mutability_errors.rs [hunk 1]
```diff
@@ -448,6 +444,100 @@ impl<'a, 'tcx> MirBorrowckCtxt<'a, 'tcx> {
 
         err.buffer(&mut self.errors_buffer);
     }
+
+    /// Targetted error when encountering an `FnMut` closure where an `Fn` closure was expected.
+    fn expected_fn_found_fn_mut_call(&self, err: &mut DiagnosticBuilder<'_>, sp: Span, act: &str) {
+        err.span_label(sp, format!("cannot {ACT}", ACT = act));
```
Comment (varkor) [inline src/librustc_mir/borrow_check/diagnostics/mutability_errors.rs]: Any reason for using a named parameter here?

File: src/test/ui/borrowck/borrow-immutable-upvar-mutation.stderr [hunk 2]
```diff
@@ -1,76 +1,101 @@
...
+   |                                                   |
+   |                                                   expects `Fn` instead of `FnMut`
+
+error[E0594]: cannot assign to `x`, as it is a captured variable in a `Fn` closure
+  --> $DIR/borrow-immutable-upvar-mutation.rs:43:9
+   |
+LL |   fn foo() -> Box<dyn Fn() -> usize> {
+   |      ---      ---------------------- ...to return `FnMut` instead of `Fn`
+   |      |
+   |      you might have to change this...
```
Comment (varkor) [inline src/test/ui/borrowck/borrow-immutable-upvar-mutation.stderr]: The order of this message seems reversed with the message above.

**Review by varkor — COMMENTED** [review]
The changes look good! Just one comment.

File: src/test/ui/borrowck/borrow-immutable-upvar-mutation.stderr (hunk 2 above)
Comment (estebank) [reply src/test/ui/borrowck/borrow-immutable-upvar-mutation.stderr]: What about `in this function...`/`...you might have to change this to return FnMut instead`?

File: src/librustc_mir/borrow_check/diagnostics/mutability_errors.rs (hunk 1 above)
Comment (estebank) [reply src/librustc_mir/borrow_check/diagnostics/mutability_errors.rs]: That was the code already there ^_^'

File: src/test/ui/borrowck/borrow-immutable-upvar-mutation.stderr (hunk 2 above)
Comment (varkor) [reply src/test/ui/borrowck/borrow-immutable-upvar-mutation.stderr]: The actual text is fine — I'm just inclined to read the topmost line first:
```
...to return `FnMut` instead of `Fn`
you might have to change this...
```
when it's intended to be read in the opposite order.

File: src/librustc_mir/borrow_check/diagnostics/mutability_errors.rs (hunk 1 above)
Comment (varkor) [reply src/librustc_mir/borrow_check/diagnostics/mutability_errors.rs]: Let's just use `{}`: the named parameter doesn't aid readability at all here :P

File: src/test/ui/borrowck/borrow-immutable-upvar-mutation.stderr (hunk 2 above)
Comment (estebank) [reply src/test/ui/borrowck/borrow-immutable-upvar-mutation.stderr]: I kept the span for the method ident with no label and shortened the wording to `change this to return FnMut instead of Fn`, as it seems more consistent with the terseness of the other suggestions we give.
