### PR TITLE
Suggest removing semicolon in last expression only if it's type is known

### LINKED ISSUE #67971: Spurious incorrect "consider removing this semicolon" help when accessing nonexistent field
```rust
struct S {}

fn f(ctx: &mut S) -> String {
    ctx.sleep = 0;
}
```
```
error[E0609]: no field `sleep` on type `&mut S`
 --> src/lib.rs:4:9
  |
4 |     ctx.sleep = 0;
  |         ^^^^^ unknown field

error[E0308]: mismatched types
 --> src/lib.rs:3:22
  |
3 | fn f(ctx: &mut S) -> String {
  |    -                 ^^^^^^ expected struct `std::string::String`, found `()`
  |    |
  |    implicitly returns `()` as its body has no tail or `return` expression
4 |     ctx.sleep = 0;
  |                  - help: consider removing this semicolon
```

Both of these errors are correct, but the second one should not suggest to remove the semicolon, since that won't fix anything here.

### PR DESCRIPTION
**Pull request by mibac138**
Fixes #67971

Is there a syntax for explicitly checking if a note doesn't exist in test output? Something like `//~ !NOTE ...`

I believe r? @estebank deals with diagnostics.

### CODE REVIEW

File: src/librustc_typeck/check/mod.rs [hunk 1]
```diff
@@ -5387,7 +5387,9 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
             _ => return None,
         };
         let last_expr_ty = self.node_ty(last_expr.hir_id);
-        if self.can_sub(self.param_env, last_expr_ty, expected_ty).is_err() {
+        if last_expr_ty.is_error()
```
Comment (estebank) [inline src/librustc_typeck/check/mod.rs:5390]: Instead of adding a method change this to `if matches!(last_expr_ty.kind, ty::Error)`

Comment (mibac138) [reply src/librustc_typeck/check/mod.rs]: Changed it
