### PR TITLE
`rustdoc --test`: Prevent reaching the maximum size of command-line by using files for arguments if there are too many

### LINKED ISSUE #122722: ICE: `rustdoc`'s `--test` option may call `rustc` with too many arguments
`rustdoc`'s `--test` option may call `rustc` with too many arguments, e.g. due to `--cfg`s, ICE'ing with:

```text
thread 'x.rs - S (line 1)' panicked at src/librustdoc/doctest.rs:407:38:
Failed to spawn rustc process: Os { code: 7, kind: ArgumentListTooLong, message: "Argument list too long" }
```

In particular, the original call to `rustdoc` (i.e. the user's call) may not suffer from this if they used `@args` to pass many arguments, but `rustdoc` will then try to spawn `rustc` passing them as parameters, and thus failing.

A reproducer may look like, for large enough N:

```sh
echo -e '//! ```\n//! ```' > x.rs
yes -- --cfg=A | head -n $N > cfgs
rustdoc --test @cfgs x.rs
```

Since different systems may have different limits, it may be best to have `rustdoc` use a temporary file for all arguments that come from unbounded lists. Or perhaps using the original `@args`, if that is possible, since users using too many e.g. `--cfg`s are probably using them already.

In the kernel we are close to hitting the limit: we have 28k+ `--cfg`s arguments in big configurations, and we may start soon passing `--check-cfg`s for those too. Passing our `@cfgs` twice already hits the limit.

### Meta

Can be reproduced with both the latest stable (1.76.0) and the latest nightly (1.79.0-nightly (3c85e5624 2024-03-18)).

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Fixes #122722.

Thanks to this I discovered that rust was using `@` to add arguments from a file, quite convenient.

If there are too many `cfg` arguments given to `rustdoc --test`, it'll now put them into a temporary file and passing it as argument to the rustc command.

I added a test with 100_000 `cfg` arguments to ensure it'll not break again.

r? @notrid

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
Github auto-complete being broken is very annoying...

r? @notriddle

File: src/librustdoc/doctest.rs [hunk 1]
```diff
@@ -348,13 +351,49 @@ fn run_test(
...
-        compiler.arg("--cfg").arg(&cfg);
+
+    let mut needs_unstable_options = false;
+    let mut written_cfg_args = false;
+    #[allow(unused_variables)]
+    let tmp_dir;
+
+    // If there are too many `cfg` arguments, instead of risking reaching `Command`'s limit on
+    // the number of arguments, we put them into a file which we then pass as `@` argument.
+    if rustdoc_options.cfgs.len() + rustdoc_options.check_cfgs.len() > 1_000
```
Comment (Urgau) [inline src/librustdoc/doctest.rs:362]: Thing can become unreadable and have a perf impact way lower, I suggest switching at 50. It should be enough to handle most crates without the argfile while switch sooner rather than latter for bigger crate.
```suggestion
    if rustdoc_options.cfgs.len() + rustdoc_options.check_cfgs.len() > 50
```

Comment (ojeda) [reply src/librustdoc/doctest.rs:362]: Yeah, some operating systems may have low limits on the number of arguments and/or total length, so it is best to be conservative.

File: tests/run-make/rustdoc-test-args/Makefile [hunk 2]
```diff
@@ -0,0 +1,10 @@
+include ../tools.mk
+
+# Test that rustdoc will properly load in a theme file and display it in the theme selector.
```
Comment (ojeda) [inline tests/run-make/rustdoc-test-args/Makefile:3]: Copy-pasted title :)

**Comment by Urgau** [comment]
While this is certainly a solution for `--cfg` and `--check-cfg`, it isn't a general solution to the issue, which would be to retry the command when it fails by putting all the args into a argfile.

Cargo utilize that mechanism internaly, [`ProcessBuilder::retry_with_argfile`](https://doc.rust-lang.org/nightly/nightly-rustc/cargo_util/process_builder/struct.ProcessBuilder.html#method.retry_with_argfile)

File: src/librustdoc/doctest.rs (hunk 1 above)
Comment (GuillaumeGomez) [reply src/librustdoc/doctest.rs:362]: At this point I think I'll simply put all arguments into a file directly and pass it to all doctests. :)

File: tests/run-make/rustdoc-test-args/Makefile (hunk 2 above)
Comment (GuillaumeGomez) [reply tests/run-make/rustdoc-test-args/Makefile:3]: Oups. ^^'

**Comment by GuillaumeGomez** [comment]
I was planning to generalize the creation of a file containing all arguments instead of checking if there are too many of them. Will make things simpler.

One thing I wonder though is how I will be able to test it...

File: tests/run-make/rustdoc-test-args/Makefile (hunk 2 above)
Comment (jieyouxu) [reply tests/run-make/rustdoc-test-args/Makefile:3]: Can this also be written as `rmake.rs` instead of introducing a new Makefile-based test?

**Comment by GuillaumeGomez** [comment]
I moved more arguments into the arg file and even better: it allows to prevent recomputing some arguments for each doctest, which will likely improve doctest performance nicely.

I took the opportunity to also stop cloning `RustdocOptions` completely and instead only clone what I need and move it into a new `RustdocTestOptions` type.

File: src/librustdoc/doctest.rs [hunk 3]
```diff
@@ -897,6 +933,61 @@ fn partition_source(s: &str, edition: Edition) -> (String, String, String) {
     (before, after, crates)
 }
 
+pub(crate) struct RustdocTestOptions {
```
Comment (Urgau) [inline src/librustdoc/doctest.rs:936]:
```suggestion
pub(crate) struct IndividualTestOptions {
```
to mirror [`GlobalTestOptions`](https://github.com/rust-lang/rust/blob/7776678bef8ca178b63d4aa50f734d72f419757d/src/librustdoc/doctest.rs#L44)

File: src/librustdoc/doctest.rs [hunk 4]
```diff
@@ -118,6 +165,15 @@ pub(crate) fn run(options: RustdocOptions) -> Result<(), ErrorGuaranteed> {
     let externs = options.externs.clone();
     let json_unused_externs = options.json_unused_externs;
 
+    let temp_dir = match tempdir()
```
Comment (Urgau) [inline src/librustdoc/doctest.rs:168]: Could your reuse the same output directory ?
https://github.com/rust-lang/rust/blob/7776678bef8ca178b63d4aa50f734d72f419757d/src/librustdoc/doctest.rs#L966-L968

**Review by Urgau — COMMENTED** [review]
Looks pretty good. I would still like to see a `rmake.rs` test[^1]  with at least 50000 different cfgs, it won't be perfect but it should at least validate RfL usage.

[^1]: if our still encountering issue with tmp dir not being writtable, I suggest using the `$(TMPDIR)` env var.

File: src/librustdoc/doctest.rs (hunk 3 above)
Comment (GuillaumeGomez) [reply src/librustdoc/doctest.rs:936]: Good idea!

File: src/librustdoc/doctest.rs (hunk 4 above)
Comment (GuillaumeGomez) [reply src/librustdoc/doctest.rs:168]: I'll make a new function to be called in both places.

**Comment by GuillaumeGomez** [comment]
Implemented all suggestions and added back the `run-make` test using `rmake.rs` this time. Hopefully it'll work in the CI this time. :)

File: tests/run-make/rustdoc-test-args/rmake.rs [hunk 5]
```diff
@@ -0,0 +1,21 @@
...
+
+fn main() -> Result<(), ()> {
+    let arg_file = out_dir().join("args");
+    generate_a_lot_of_cfgs(&arg_file);
+
+    let arg_file = format!("@{}", arg_file.display());
+    if !rustdoc().arg("--test").arg(&arg_file).arg("foo.rs").run().status.success() {
+        return Err(());
+    }
+    Ok(())
```
Comment (Urgau) [inline tests/run-make/rustdoc-test-args/rmake.rs:20]: nit: but the `run` function already takes care of aborting in case of failure, therefor this dance shouldn't be necessary.
```suggestion
    rustdoc().arg("--test").arg(&arg_file).arg("foo.rs").run();
```

File: tests/run-make/rustdoc-test-args/rmake.rs [hunk 6]
```diff
@@ -0,0 +1,21 @@
...
+use run_make_support::{out_dir, rustdoc};
+use std::{fs, iter};
+use std::path::Path;
+
+fn generate_a_lot_of_cfgs(path: &Path) {
+    let content = iter::repeat("--cfg=a\n").take(75_000).collect::<String>();
+    fs::write(path, content.as_bytes()).expect("failed to create args file");
+}
+
+fn main() -> Result<(), ()> {
```
Comment (Urgau) [inline tests/run-make/rustdoc-test-args/rmake.rs:12]: and this shouldn't be necessary anymore.
```suggestion
fn main() {
```

**Review by Urgau — APPROVED** [review]
Looks good to me.

*raced with `@notriddle`* :smile:

File: src/tools/run-make-support/src/lib.rs [hunk 7]
```diff
@@ -97,6 +101,35 @@ impl AuxBuildInvocationBuilder {
     }
 }
 
+#[derive(Debug)]
+pub struct RustdocInvocationBuilder {
```
Comment (jieyouxu) [inline src/tools/run-make-support/src/lib.rs:105]: nit: this can just be called `Rustdoc`, I have a pending PR that simplifies `RustcInvocationBuilder` to `Rustc` (no need for such a long name).

**Comment by ojeda** [comment]
> with at least 50000 different cfgs, it won't be perfect but it should at least validate RfL usage.

I am not sure it does, e.g. with very small `--cfg` flags like the one in the test now (`A`), 50000 or even 75000 do not hit the limit for me with my reproducer. I would suggest something substantially bigger.

**Comment by GuillaumeGomez** [comment]
I'll increase the number then. :)

I'm r-ing it for now. I'll re-r+ it once the suggested changes are done.

@bors r-

**Comment by GuillaumeGomez** [comment]
All done!

@bors r=notriddle,Urgau,jieyouxu

**Comment by RalfJung** [comment]
I think this is causing issues in Miri... https://github.com/rust-lang/miri/pull/3401

**Comment by GuillaumeGomez** [comment]
Please open an issue and tag me on it. I'll try to take a look in the week (rust nation conf so maybe not very fast...).
