### PR TITLE
Recover form missing expression in `for` loop

### LINKED ISSUE #78537: Better diagnostics for missing iterator in for-loop
Spot the bug:
```rust
fn f() -> usize {
    for i in {
        println!("{}", i);
    }
    1
}
```
Unfortunately, instead of pointing to the missing iterator, rust points to the 1:
```
error: expected `{`, found `1`
 --> src/lib.rs:5:5
  |
5 |     1
  |     ^
  |     |
  |     expected `{`
  |     help: try placing this code inside a block: `{ 1 }`
```
I'd love it to instead say 'missing iterator for loop':
```
error: expected iterator, found block
 --> src/lib.rs
  |
2 |    for i in {
  |             ^ this starts a block expression ...
5 |     1
  |     ^ ... so there is no body for the loop
  =     help: try adding an iterator to the for-loop: `for i in iter {`
```

Other variants of this with less than ideal errors:
```rust
fn f() {
    for i in {
        println!("{}", i);
    }
}
```
```
error: expected `{`, found `}`
 --> src/lib.rs:5:1
  |
5 | }
  | ^ expected `{`
```
```rust
fn f() -> usize {
    for i in {
        println!("{}", i);
    }
    return 1;
}
```
```
error: expected `{`, found keyword `return`
 --> src/lib.rs:5:5
  |
5 |     return 1;
  |     ^^^^^^---
  |     |
  |     expected `{`
  |     help: try placing this code inside a block: `{ return 1; }`
```

### PR DESCRIPTION
**Pull request by obeis**
Close #78537
r? @estebank

### CODE REVIEW

File: compiler/rustc_parse/src/parser/expr.rs [hunk 1]
```diff
@@ -2466,6 +2466,19 @@ impl<'a> Parser<'a> {
...
+        if self.token == token::OpenDelim(token::Delimiter::Brace)
+            && self.prev_token.is_keyword(kw::In)
+            && self.may_recover()
+        {
+            let mut err = self.struct_span_err(self.token.span, "expected expression, found block");
+            err.help(
+                "try adding an expression to the `for` loop: `for PATTERN in EXPRESSION { BODY }`",
+            );
+            return Err(err);
+        }
```
Comment (compiler-errors) [inline compiler/rustc_parse/src/parser/expr.rs:2480]: Doesn't this recovery break the following example:

```rust
for _ in { 0..10 } {}
```

**Comment by compiler-errors** [comment]
Esteban is out for a few weeks. r? @compiler-errors

File: compiler/rustc_parse/src/parser/expr.rs (hunk 1 above)
Comment (obeis) [reply compiler/rustc_parse/src/parser/expr.rs:2480]: Will break it, How can i avoid that?

**Comment by obeis** [comment]
@compiler-errors 
```
// run-pass

#![deny(unused_mut)]
#![allow(unreachable_code)]

fn main() {
    for _ in { return (); 0..3 } {} // ok
}
```
How can this situation be avoided?

File: compiler/rustc_parse/src/parser/expr.rs (hunk 1 above)
Comment (compiler-errors) [reply compiler/rustc_parse/src/parser/expr.rs:2480]: Only emit an error if:
1. The `loop_block` that is being parsed at 2487 doesn't start with `{` (you can do the check on 2486)
2. *and* the `expr` we parsed on 2483 is a block expression.

Comment (obeis) [reply compiler/rustc_parse/src/parser/expr.rs]: Thanks :)

File: compiler/rustc_parse/src/parser/expr.rs [hunk 2]
```diff
@@ -2466,11 +2466,25 @@ impl<'a> Parser<'a> {
...
             self.error_missing_in_for_loop();
         }
+        let expr_token = self.token.clone();
         self.check_for_for_in_in_typo(self.prev_token.span);
         let expr = self.parse_expr_res(Restrictions::NO_STRUCT_LITERAL, None)?;
 
         let pat = self.recover_parens_around_for_head(pat, begin_paren);
 
+        // Recover from missing expression in `for` loop
+        if matches!(expr_token.kind, token::OpenDelim(token::Delimiter::Brace))
```
Comment (compiler-errors) [inline compiler/rustc_parse/src/parser/expr.rs:2476]: We don't need to use `expr_token` here, we should be able to check that the `expr`'s kind is a `ExprKind::Block` or something like that.

File: compiler/rustc_parse/src/parser/expr.rs [hunk 3]
```diff
@@ -2466,11 +2466,25 @@ impl<'a> Parser<'a> {
...
+            && !matches!(self.token.kind, token::OpenDelim(token::Delimiter::Brace))
+            && matches!(expr.kind, ExprKind::Block(..))
+            && self.may_recover()
+        {
+            let mut err = self.struct_span_err(expr_token.span, "expected expression, found block");
+            err.help(
+                "try adding an expression to the `for` loop: `for PATTERN in EXPRESSION { BODY }`",
+            );
```
Comment (compiler-errors) [inline compiler/rustc_parse/src/parser/expr.rs:2484]: Can you migrate this to a diagnostic derive? https://rustc-dev-guide.rust-lang.org/diagnostics/diagnostic-structs.html

File: compiler/rustc_parse/src/parser/expr.rs [hunk 4]
```diff
@@ -2466,11 +2466,25 @@ impl<'a> Parser<'a> {
...
+            return Err(err);
```
Comment (compiler-errors) [inline compiler/rustc_parse/src/parser/expr.rs:2485]: We should be able to recover by returning a for loop that looks like `for pat in <ERROR> { expr }`, where we reinterpret the `expr` we parsed on line 2471 as a block, and insert an error expression instead. You can make an error expression with `this.mk_expr(span, ExprKind::Err)`).

File: compiler/rustc_parse/src/parser/expr.rs [hunk 5]
```diff
@@ -2466,11 +2466,26 @@ impl<'a> Parser<'a> {
...
+            && !matches!(self.token.kind, token::OpenDelim(token::Delimiter::Brace))
+            && self.may_recover()
+        {
+            let mut diag = self.sess.struct_err("expected expression, found block");
+            diag.set_span(expr_span);
+            diag.help(
+                "try adding an expression to the `for` loop: `for PATTERN in EXPRESSION { BODY }`",
+            );
+            self.mk_expr(expr_span, ExprKind::Err);
+            return Err(diag);
```
Comment (compiler-errors) [inline compiler/rustc_parse/src/parser/expr.rs:2486]: Copying this from the resolved comment:

> We should be able to recover by returning a for loop that looks like for pat in <ERROR> { expr }, where we reinterpret the expr we parsed on line 2471 as a block, and insert an error expression instead. You can make an error expression with this.mk_expr(span, ExprKind::Err)).

When I said that, I meant -- instead of returning `Err`, we can *emit* the diagnostic, and instead return `Ok(self.mk_expr(...))`, with a properly constructed `for` loop expression. We would use the `ExprKind::Err` expression in the `EXPRESSION` part of `for PATTERN in EXPRESSION { BODY }`.

File: compiler/rustc_parse/src/parser/expr.rs [hunk 6]
```diff
@@ -2466,11 +2466,26 @@ impl<'a> Parser<'a> {
...
         let expr = self.parse_expr_res(Restrictions::NO_STRUCT_LITERAL, None)?;
 
         let pat = self.recover_parens_around_for_head(pat, begin_paren);
 
+        // Recover from missing expression in `for` loop
+        if matches!(expr.kind, ExprKind::Block(..))
+            && !matches!(self.token.kind, token::OpenDelim(token::Delimiter::Brace))
+            && self.may_recover()
+        {
+            let mut diag = self.sess.struct_err("expected expression, found block");
```
Comment (compiler-errors) [inline compiler/rustc_parse/src/parser/expr.rs:2480]: You still didn't migrate this to a diagnostic derive :sweat_smile:, it just went from `struct_span_err` to `struct_err`?

You need to make a struct, adding `derive(Diagnostic)` and adding the corresponding entries to the `parser.ftl` file. There should be lots of example in the git history for https://github.com/rust-lang/rust/commits/master/compiler/rustc_parse/src/errors.rs

File: compiler/rustc_parse/src/parser/expr.rs [hunk 7]
```diff
@@ -2466,11 +2466,26 @@ impl<'a> Parser<'a> {
         if !self.eat_keyword(kw::In) {
             self.error_missing_in_for_loop();
         }
+        let expr_span = self.token.span;
```
Comment (compiler-errors) [inline compiler/rustc_parse/src/parser/expr.rs:2469]: I don't think we need this -- I think `expr.span` works fine too to use below.

**Review by compiler-errors — CHANGES_REQUESTED** [review]

File: tests/ui/parser/missing-expression-in-for-loop.stderr [hunk 8]
```diff
@@ -0,0 +1,13 @@
+error: expected expression, found block
```
Comment (estebank) [inline tests/ui/parser/missing-expression-in-for-loop.stderr:1]: It is *marginally* misleading to say this, because blocks that have a tail expression *are* allowed, but I feel that it might be fine. If we were to change anything, I'd likely change this to
```suggestion
error: missing expression to iterate on in `for` loop
```
and maybe point at the space between `in` and the `{`. *But* that span could be potentially incorrect if that was indeed the iterating expression... 🤔 

I'm ok with this as is, I guess.

File: tests/ui/parser/missing-expression-in-for-loop.stderr [hunk 9]
```diff
@@ -0,0 +1,13 @@
...
+  --> $DIR/missing-expression-in-for-loop.rs:2:14
+   |
+LL |       for i in {
+   |  ______________^
+LL | |
+LL | |     }
+   | |_____^
+   |
+   = help: try adding an expression to the `for` loop: `for PATTERN in EXPRESSION`
```
Comment (estebank) [inline tests/ui/parser/missing-expression-in-for-loop.stderr:10]: Could we turn this into a structured suggestion for the following? It would be easy to find the right span (`in_kw.span.between(block.span)`).

```
for i in /* expression */ {
```

File: compiler/rustc_parse/src/parser/expr.rs [hunk 10]
```diff
@@ -2481,6 +2481,15 @@ impl<'a> Parser<'a> {
...
         let pat = self.recover_parens_around_for_head(pat, begin_paren);
 
+        // Recover from missing expression in `for` loop
+        if matches!(expr.kind, ExprKind::Block(..))
+            && !matches!(self.token.kind, token::OpenDelim(token::Delimiter::Brace))
+            && self.may_recover()
+        {
+            self.sess.emit_err(MissingExpressionInForLoop { span: expr.span });
+            return Ok(self.mk_expr(expr.span, ExprKind::Err));
+        }
```
Comment (compiler-errors) [inline compiler/rustc_parse/src/parser/expr.rs:2491]: One last suggestion: We should be constructing a *for loop* here. Do something approximately like this--

```suggestion
        if let ExprKind::Block(block, label) = expr.kind
            && !matches!(self.token.kind, token::OpenDelim(token::Delimiter::Brace))
            && self.may_recover()
        {
            self.sess.emit_err(MissingExpressionInForLoop { span: expr.span });
            let err_expr = self.mk_expr(expr.span, ExprKind::Err);
            return Ok(self.mk_expr(lo.to(self.prev_token.span), ExprKind::ForLoop(pat, err_expr, block, label)));
        }
```

You *might* need to clone some stuff, I haven't checked if it compiles.

File: tests/ui/parser/missing-expression-in-for-loop.stderr (hunk 9 above)
Comment (compiler-errors) [reply tests/ui/parser/missing-expression-in-for-loop.stderr:10]: @obeis, you marked this as resolved but didn't implement this?

File: compiler/rustc_parse/src/parser/expr.rs [hunk 11]
```diff
@@ -2481,6 +2481,15 @@ impl<'a> Parser<'a> {
 
         let pat = self.recover_parens_around_for_head(pat, begin_paren);
 
+        // Recover from missing expression in `for` loop
+        if matches!(expr.kind, ExprKind::Block(..))
+            && !matches!(self.token.kind, token::OpenDelim(token::Delimiter::Brace))
+            && self.may_recover()
+        {
+            self.sess.emit_err(MissingExpressionInForLoop { span: expr.span });
```
Comment (compiler-errors) [inline compiler/rustc_parse/src/parser/expr.rs:2489]: I wouldn't use `expr.span` here -- maybe use `expr.span.shrink_to_lo()` or something?

That's also the span you can use for the `/* expression */` suggestion that esteban gave.

File: tests/ui/parser/missing-expression-in-for-loop.stderr (hunk 9 above)
Comment (obeis) [reply tests/ui/parser/missing-expression-in-for-loop.stderr:10]: What does he mean by `structured suggestion`?

Comment (compiler-errors) [reply tests/ui/parser/missing-expression-in-for-loop.stderr:10]: providing a suggestion, like:

```
help: try adding an expression to the `for` loop

| for i in /* expression */ {
           ++++++++++++++++
```

This is achieved with `#[suggestion(.....)]` in diagnostics derive.

File: compiler/rustc_parse/src/errors.rs [hunk 12]
```diff
@@ -433,6 +433,18 @@ pub(crate) enum MissingInInForLoopSub {
     AddIn(#[primary_span] Span),
 }
 
+#[derive(Diagnostic)]
+#[diag(parse_missing_expression_in_for_loop)]
+pub(crate) struct MissingExpressionInForLoop {
+    #[primary_span]
+    #[suggestion(
+        code = "/* expression */ ",
+        applicability = "machine-applicable",
```
Comment (compiler-errors) [inline compiler/rustc_parse/src/errors.rs:442]: This suggestion is not machine-applicable, because the suggestion is not valid syntax after it's applied. It's just there to help the user understand the issue.

```suggestion
        applicability = "has-placeholders",
```

**Comment by obeis** [comment]
Does this need to approve again?
@estebank @compiler-errors
