### PR TITLE
fixes move analysis

### LINKED ISSUE #48962: internal compiler error: librustc_mir/transform/elaborate_drops.rs — drop of untracked, uninitialized value
```rust
#![feature(nll)]

struct Node {
    elem: i32,
    next: Option<Box<Node>>,
}

fn main() {
    let mut node = Node {
        elem: 5,
        next: None,
    };

    let mut src = &mut node;
    while let Some(node) = {src}.next.as_mut().map(|node| &mut *node) {
        src = node;
    }
    src.next = None;
}
```

```
$ RUST_BACKTRACE=1 rustc +nightly a.rs
warning: field is never used: `elem`
 --> a.rs:4:5
  |
4 |     elem: i32,
  |     ^^^^^^^^^
  |
  = note: #[warn(dead_code)] on by default

error: internal compiler error: librustc_mir/transform/elaborate_drops.rs:384: drop of untracked, uninitialized value bb7, place ((*_3).1: std::option::Option<std::boxed::Box<Node>>) (Parent(Some(mp3)))
  --> a.rs:18:5
   |
18 |     src.next = None;
   |     ^^^^^^^^

thread 'rustc' panicked at 'Box<Any>', librustc_errors/lib.rs:482:9
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
   1: std::sys_common::backtrace::_print
   2: std::panicking::default_hook::{{closure}}
   3: std::panicking::default_hook
   4: core::ops::function::Fn::call
   5: std::panicking::rust_panic_with_hook
   6: std::panicking::begin_panic
   7: rustc_errors::Handler::span_bug
   8: rustc::session::opt_span_bug_fmt::{{closure}}
   9: rustc::ty::context::tls::with_opt::{{closure}}
  10: <std::thread::local::LocalKey<T>>::try_with
  11: <std::thread::local::LocalKey<T>>::with
  12: rustc::ty::context::tls::with
  13: rustc::ty::context::tls::with_opt
  14: rustc::session::opt_span_bug_fmt
  15: rustc::session::span_bug_fmt
  16: <rustc_mir::transform::elaborate_drops::ElaborateDrops as rustc_mir::transform::MirPass>::run_pass
  17: rustc_mir::transform::optimized_mir::{{closure}}
  18: rustc_mir::transform::optimized_mir
  19: rustc::dep_graph::graph::DepGraph::with_task_impl
  20: rustc::ty::maps::<impl rustc::ty::maps::queries::optimized_mir<'tcx>>::force
  21: rustc::ty::maps::<impl rustc::ty::maps::queries::optimized_mir<'tcx>>::try_get
  22: rustc::ty::maps::TyCtxtAt::optimized_mir
  23: rustc::ty::<impl rustc::ty::context::TyCtxt<'a, 'gcx, 'tcx>>::instance_mir
  24: rustc_mir::monomorphize::collector::collect_items_rec
  25: rustc_mir::monomorphize::collector::collect_crate_mono_items
  26: rustc_trans::base::collect_and_partition_translation_items
  27: rustc::dep_graph::graph::DepGraph::with_task_impl
  28: rustc::ty::maps::<impl rustc::ty::maps::queries::collect_and_partition_translation_items<'tcx>>::force
  29: rustc::ty::maps::<impl rustc::ty::maps::queries::collect_and_partition_translation_items<'tcx>>::try_get
  30: rustc::ty::maps::TyCtxtAt::collect_and_partition_translation_items
  31: rustc::ty::maps::<impl rustc::ty::context::TyCtxt<'a, 'tcx, 'lcx>>::collect_and_partition_translation_items
  32: rustc_trans::base::trans_crate
  33: <rustc_trans::LlvmTransCrate as rustc_trans_utils::trans_crate::TransCrate>::trans_crate
  34: rustc_driver::driver::phase_4_translate_to_llvm
  35: rustc_driver::driver::compile_input::{{closure}}
  36: rustc::ty::context::TyCtxt::create_and_enter
  37: rustc_driver::driver::compile_input
  38: rustc_driver::run_compiler

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.26.0-nightly (2789b067d 2018-03-06) running on x86_64-apple-darwin
```

### PR DESCRIPTION
**Pull request by hrvolapeter**
Fixed compiler error by correct checking when dereferencing

Fix #48962

r? @nikomatsakis

### CODE REVIEW

**Comment by shepmaster** [comment]
Ping from triage, @nikomatsakis ! Will you have time to review this soon?

File: src/librustc_mir/borrow_check/mod.rs [hunk 1]
```diff
@@ -1454,8 +1492,6 @@ impl<'cx, 'gcx, 'tcx> MirBorrowckCtxt<'cx, 'gcx, 'tcx> {
                 Place::Projection(ref proj) => {
                     let Projection { ref base, ref elem } = **proj;
                     match *elem {
-                        ProjectionElem::Deref |
-                        // assigning to *P requires `P` initialized.
                         ProjectionElem::Index(_/*operand*/) |
                         ProjectionElem::ConstantIndex { .. } |
                         // assigning to P[i] requires `P` initialized.
```
Comment (arielb1) [inline src/librustc_mir/borrow_check/mod.rs]: This comment is wrong. Should be
```Rust
// assigning to P[i] requires P to be valid
```

File: src/librustc_mir/borrow_check/mod.rs [hunk 2]
```diff
@@ -1465,6 +1501,12 @@ impl<'cx, 'gcx, 'tcx> MirBorrowckCtxt<'cx, 'gcx, 'tcx> {
                         // FIXME: is this true even if P is a adt with a dtor?
                         { }
 
+                        ProjectionElem::Deref => {
```
Comment (arielb1) [inline src/librustc_mir/borrow_check/mod.rs]: Should have a comment
```Rust
// assigning to (*P) requires P to be initialized
```

File: src/librustc_mir/borrow_check/mod.rs [hunk 3]
```diff
@@ -1465,6 +1501,12 @@ impl<'cx, 'gcx, 'tcx> MirBorrowckCtxt<'cx, 'gcx, 'tcx> {
...
+                            self.check_if_path_is_moved(
+                                context, InitializationRequiringAction::Use,
+                                (base, span), flow_state);
```
Comment (arielb1) [inline src/librustc_mir/borrow_check/mod.rs]: You can add a `break` here if you want - we already force the base to be initialized, so there is no need to further check.

Maybe in that case you would also not need the new error deduplication code.

File: src/librustc_mir/borrow_check/mod.rs [hunk 4]
```diff
@@ -1320,18 +1324,17 @@ impl<'cx, 'gcx, 'tcx> MirBorrowckCtxt<'cx, 'gcx, 'tcx> {
         //
```
Comment (arielb1) [inline src/librustc_mir/borrow_check/mod.rs]: Maybe rename `check_if_path_is_moved` to `check_if_full_path_is_moved`?

**Comment by arielb1** [comment]
Sorry for the delay in reviewing. This is a bit of an embarrassing bug.

If adding a `break` in the `check_if_assigned_path_is_moved` loop fixes the error deduplication, then pretty much r+ from me with the nits addressed.

**Comment by retep007** [comment]
@arielb1 Unfortunately adding a break won't fix duplicate errors.  Let's have expression `w[5] = 0;` it translates to mir similar to
```
        _3 = Len((*_1));                 // bb0[3]: scope 1 at borrowck-use-in-index-lvalue.rs:16:5: 16:9
                                         | Live variables on entry to bb0[4]: [_1, _2, _3]
        _4 = Lt(_2, _3);                 // bb0[4]: scope 1 at borrowck-use-in-index-lvalue.rs:16:5: 16:9
                                         | Live variables on entry to bb0[5]: [_1, _2, _3, _4]
        assert(move _4, "index out of bounds: the len is {} but the index is {}", move _3, _2) -> [success: bb2, unwind: bb1]; // bb0[5]: scope 1 at borrowck-use-in-index-lvalue.rs:16:5: 16:9
    }

    | Live variables on entry to bb1: []
    bb1: {                               // cleanup
                                         | Live variables on entry to bb1[0]: []
        resume;                          // bb1[0]: scope 0 at borrowck-use-in-index-lvalue.rs:14:1: 22:2
    }

    | Live variables on entry to bb2: [_1, _2]
    bb2: {                              
                                         | Live variables on entry to bb2[0]: [_1, _2]
        (*_1)[_2] = const 0isize;  
```
first error is printed from `_3 = Len((*_1));` and second (which we are trying to surpress) is from `(*_1)[_2] = const 0isize;`

**Comment by arielb1** [comment]
@retep007 

In that case, could you deduplicate based on `(Place, Span)` instead of only `Place`? That makes e.g. writing tests to much easier.

File: src/librustc_mir/borrow_check/error_reporting.rs [hunk 5]
```diff
@@ -37,6 +37,23 @@ impl<'cx, 'gcx, 'tcx> MirBorrowckCtxt<'cx, 'gcx, 'tcx> {
...
         if mois.is_empty() {
+            let root_place = self.prefixes(&place, PrefixSet::All)
+                .last()
+                .unwrap();
+
+            if self.moved_error_reported
+                .contains(&root_place.clone())
+            {
+                debug!(
+                    "report_use_of_moved_or_uninitialized place: {:?} errors was suppressed",
```
Comment (arielb1) [inline src/librustc_mir/borrow_check/error_reporting.rs]: english fix: error about `{:?}` suppressed.

**Comment by arielb1** [comment]
I think this code is OK, but I didn't touch this code long enough that I would rather

r? @nikomatsakis

**Comment by retep007** [comment]
@arielb1 `_3 = Len((*_1));` and `(*_1)[_2] = const 0isize;` have also different spans from [previous comment](https://github.com/rust-lang/rust/pull/49392#issuecomment-377770720) first one has span only of `w[5]` but second has `w[5] = 0`.

I also think that second error actually says better what's the problem, but It would require to first refactor how the errors are reported.
First:
```
w[5] = 0; //[ast]~ ERROR use of possibly uninitialized variable: `w` [E0381]
^^^^ use of possibly uninitialized `*w`
```
Second:
```
w[5] = 0; //[ast]~ ERROR use of possibly uninitialized variable: `w` [E0381]
^^^^^^^^ use of possibly uninitialized `w`
```

File: src/librustc_mir/borrow_check/mod.rs [hunk 6]
```diff
@@ -1372,18 +1375,52 @@ impl<'cx, 'gcx, 'tcx> MirBorrowckCtxt<'cx, 'gcx, 'tcx> {
...
+    }
+
+    fn check_if_path_or_subpath_is_moved(
+        &mut self,
+        context: Context,
+        desired_action: InitializationRequiringAction,
+        place_span: (&Place<'tcx>, Span),
+        flow_state: &Flows<'cx, 'gcx, 'tcx>,
+    ) {
+        // FIXME: analogous code in check_loans first maps `place` to
```
Comment (nikomatsakis) [inline src/librustc_mir/borrow_check/mod.rs]: what code are you referring to exactly?

**Review by nikomatsakis — APPROVED** [review]

**Comment by nikomatsakis** [comment]
This code looks good to me!

File: src/librustc_mir/borrow_check/mod.rs (hunk 6 above)
Comment (retep007) [reply src/librustc_mir/borrow_check/mod.rs]: Exactly same code `let place = self.base_path(place_span.0);` is in `check_if_full_path_is_moved` also with the comment. So If somebody decides to refactor this he will probably do both `check_if_full_path_is_moved`, `check_if_path_or_subpath_is_moved`
