### PR TITLE
Fix build on Solaris where fd-lock cannot be used.

### LINKED ISSUE #113085: error: unused import - when building Rust on Solaris where isn't fd-lock available
```
error: unused import: `std::fs::OpenOptions`
 --> bin/main.rs:8:5
  |
8 | use std::fs::OpenOptions;
  |     ^^^^^^^^^^^^^^^^^^^^
  |
  = note: `-D unused-imports` implied by `-D warnings`

error: unused import: `std::io::Write`
 --> bin/main.rs:9:5
  |
9 | use std::io::Write;
  |     ^^^^^^^^^^^^^^

error: unused imports: `fs`, `process`
  --> bin/main.rs:10:16
   |
10 | use std::{env, fs, process};
   |                ^^  ^^^^^^^

error: could not compile `bootstrap` due to 3 previous errors
warning: build failed, waiting for other jobs to finish...
Building bootstrap
failed to run: /builds/psumbera/rust-lang-build/build/x86_64-pc-solaris/stage0/bin/cargo build --manifest-path /builds/psumbera/rust-lang-build/src/bootstrap/Cargo.toml
Build completed unsuccessfully in 0:01:26
```

This is regression from: https://github.com/rust-lang/rust/commit/e7e584b7d9d4eba8b9655b255840ef9caf9b40c0

Prposed fix: https://github.com/rust-lang/rust/pull/113048

### PR DESCRIPTION
**Pull request by psumbera**
This fixes build regression after https://github.com/rust-lang/rust/commit/e7e584b7d9d4eba8b9655b255840ef9caf9b40c0.

Resolves #113085

### CODE REVIEW

File: src/bootstrap/bin/main.rs [hunk 1]
```diff
@@ -5,9 +5,13 @@
...
 //! directory in each respective module.
 
+use std::env;
+#[cfg(all(any(unix, windows), not(target_os = "solaris")))]
 use std::fs::OpenOptions;
+#[cfg(all(any(unix, windows), not(target_os = "solaris")))]
 use std::io::Write;
-use std::{env, fs, process};
+#[cfg(all(any(unix, windows), not(target_os = "solaris")))]
+use std::{fs, process};
```
Comment (ozkanonur) [inline src/bootstrap/bin/main.rs:14]: You can import `fs` for all and update `std::fs` to `fs` directly.

File: src/bootstrap/bin/main.rs [hunk 2]
```diff
@@ -5,9 +5,13 @@
 //! parent directory, and otherwise documentation can be found throughout the `build`
 //! directory in each respective module.
 
+use std::env;
+#[cfg(all(any(unix, windows), not(target_os = "solaris")))]
 use std::fs::OpenOptions;
```
Comment (ozkanonur) [inline src/bootstrap/bin/main.rs:10]: `OpenOptions` only used once, so you could consider using it as `std::fs::OpenOptions` instead. So we can avoid conditional import for this which makes the code a bit more difficult to read.

**Review by onur-ozkan — CHANGES_REQUESTED** [review]
Thank you for the PR :)

I haven't tested this. I will try to test it during this week. Adding a reference to the problem/error that this PR fix would be great.

File: src/bootstrap/bin/main.rs (hunk 1 above)
Comment (ozkanonur) [reply src/bootstrap/bin/main.rs:12]: Patch for resolving this note

```diff
diff --git a/src/bootstrap/bin/main.rs b/src/bootstrap/bin/main.rs
index 67b707d5833..30dfa81c6f7 100644
--- a/src/bootstrap/bin/main.rs
+++ b/src/bootstrap/bin/main.rs
@@ -5,11 +5,11 @@
 //! parent directory, and otherwise documentation can be found throughout the `build`
 //! directory in each respective module.
 
-use std::env;
 #[cfg(all(any(unix, windows), not(target_os = "solaris")))]
 use std::io::Write;
 #[cfg(all(any(unix, windows), not(target_os = "solaris")))]
-use std::{fs, process};
+use std::process;
+use std::{env, fs};
 
 #[cfg(all(any(unix, windows), not(target_os = "solaris")))]
 use bootstrap::t;
@@ -33,10 +33,8 @@ fn main() {
             Err(_) => String::new(),
         };
 
-        build_lock = fd_lock::RwLock::new(t!(std::fs::OpenOptions::new()
-            .write(true)
-            .create(true)
-            .open(&path)));
+        build_lock =
+            fd_lock::RwLock::new(t!(fs::OpenOptions::new().write(true).create(true).open(&path)));
         _build_lock_guard = match build_lock.try_write() {
             Ok(mut lock) => {
                 t!(lock.write(&process::id().to_string().as_ref()));
@@ -89,7 +87,7 @@ fn main() {
     // HACK: Since the commit script uses hard links, we can't actually tell if it was installed by x.py setup or not.
     // We could see if it's identical to src/etc/pre-push.sh, but pre-push may have been modified in the meantime.
     // Instead, look for this comment, which is almost certainly not in any custom hook.
-    if std::fs::read_to_string(pre_commit).map_or(false, |contents| {
+    if fs::read_to_string(pre_commit).map_or(false, |contents| {
         contents.contains("https://github.com/rust-lang/rust/issues/77620#issuecomment-705144570")
     }) {
         println!(
```

**Review by onur-ozkan — APPROVED** [review]
