### PR TITLE
Use root obligation on E0277 for some cases

### LINKED ISSUE #79359: Fn is assumed when reference is passed as Pattern
Sorry, I don't exactly understand why this happened, so I can't provide much more detail.
```
error[E0277]: expected a `std::ops::Fn<(char,)>` closure, found `char`
  --> hglfgp_glsl/src/lib.rs:21:42
   |
21 |     s.chars().filter(|c| !(" \n\t".contains(c))).collect::<String>()
   |                                             ^ expected an `Fn<(char,)>` closure, found `char`
```
The correct solution to fix this was to change `|c|` to `|&c|`, however the error message did not indicate what was wrong at all.
Please inform me if I need to change the format of this issue.

### LINKED ISSUE #118779: Other missing bounds required to meet a trait's blanket impl are displayed too prominently
### Code

```Rust
pub trait Add {
    fn add(&self, left: usize, right: usize) -> usize;
}

impl<F> Add for F
where
    F: Fn(usize, usize) -> usize,
{
    fn add(&self, left: usize, right: usize) -> usize {
        self(left, right)
    }
}

pub struct NotAdd;

pub fn needs_add<A: Add>(add: &A) -> usize {
    add.add(1, 2)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn it_works() {
        assert_eq!(needs_add(&NotAdd), 3);
    }
}
```

### Current output

```Shell
error[E0277]: expected a `Fn<(usize, usize)>` closure, found `NotAdd`
  --> src/lib.rs:26:30
   |
26 |         assert_eq!(needs_add(&NotAdd), 3);
   |                    --------- ^^^^^^^ expected an `Fn<(usize, usize)>` closure, found `NotAdd`
   |                    |
   |                    required by a bound introduced by this call
   |
   = help: the trait `Fn<(usize, usize)>` is not implemented for `NotAdd`
note: required for `NotAdd` to implement `Add`
  --> src/lib.rs:5:9
   |
5  | impl<F> Add for F
   |         ^^^     ^
6  | where
7  |     F: Fn(usize, usize) -> usize,
   |        ------------------------- unsatisfied trait bound introduced here
note: required by a bound in `needs_add`
  --> src/lib.rs:16:21
   |
16 | pub fn needs_add<A: Add>(add: &A) -> usize {
   |                     ^^^ required by this bound in `needs_add`

For more information about this error, try `rustc --explain E0277`.
error: could not compile `fn-trait-error-test` (lib test) due to previous error
```

### Desired output

```Shell
error[E0277]: `NotAdd` doesn't implement `Add`
  --> src/lib.rs:26:30
   |
26 |         assert_eq!(needs_add(&NotAdd), 3);
   |                    --------- ^^^^^^^ `NotAdd` doesn't implement `Add`
   |                    |
   |                    required by a bound introduced by this call
   |
   = help: the trait `Fn<(usize, usize)>` is not implemented for `NotAdd`
note: required for `NotAdd` to implement `Add`
  --> src/lib.rs:5:9
   |
5  | impl<F> Add for F
   |         ^^^     ^
6  | where
7  |     F: Fn(usize, usize) -> usize,
   |        ------------------------- unsatisfied trait bound introduced here
note: required by a bound in `needs_add`
  --> src/lib.rs:16:21
   |
16 | pub fn needs_add<A: Add>(add: &A) -> usize {
   |                     ^^^ required by this bound in `needs_add`

For more information about this error, try `rustc --explain E0277`.
error: could not compile `fn-trait-error-test` (lib test) due to previous error
```

### Rationale and extra context

The first thing the error should make extremely obvious is the Trait that is required.

_Then_ the existing (very useful and clever!) other bounds required to satisfy a blanket impl should be noted.

The fact that a type is implemented by a Blanket impl is often not in the forefront of a user's mind when they encounter this kind of error. They first need to realise that the type they probably think _ought_ to impl a trait, definitely does not in fact impl that trait.

This becomes more important the more traits and types implementing those traits there are in scope, and the more bounds that might not be met.

### Other cases

_No response_

### Anything else?

_No response_

### LINKED ISSUE #119983: Confusing E0277 diagnostic with blanket implementations
### Code

```Rust
pub trait A {}
pub trait B {}
impl<T> A for T where T: B {}
fn f<T>(_: T) where T: A {}
fn g() { f(()) }
```

### Current output

```Shell
error[E0277]: the trait bound `(): B` is not satisfied
 --> <source>:5:12
  |
5 | fn g() { f(()) }
  |          - ^^ the trait `B` is not implemented for `()`
  |          |
  |          required by a bound introduced by this call
  |
note: required for `()` to implement `A`
 --> <source>:3:9
  |
3 | impl<T> A for T where T: B {}
  |         ^     ^          - unsatisfied trait bound introduced here
note: required by a bound in `f`
 --> <source>:4:24
  |
4 | fn f<T>(_: T) where T: A {}
  |                        ^ required by this bound in `f`
```

### Desired output

```Shell
error[E0277]: the trait bound `(): A` is not satisfied
 --> <source>:5:12
  |
5 | fn g() { f(()) }
  |          - ^^ the trait `A` is not implemented for `()`
  |          |
  |          required by a bound introduced by this call
  |
note: required by a bound in `f`
 --> <source>:4:24
  |
4 | fn f<T>(_: T) where T: A {}
  |                        ^ required by this bound in `f`
```

### Rationale and extra context

`impl A for () {}` and `impl B for () {}` are both valid solutions, but the diagnostic focuses only on the latter. A suggestion to implement `A` is arguably easier to understand, as it directly implements the trait that the bound on `f` requires, rather than indirectly. In fact, given no knowledge about the intended semantics for `A` and `B`, for any given type `T`, `impl B for T {}` is less likely to be correct than `impl A for T {}`, since `B` may pose additional informal (e.g. safety, documented invariants) requirements on top of those posed by `A`.

### Other cases

_No response_

### Rust Version

```Shell
rustc 1.73.0 (cc66ad468 2023-10-03)
binary: rustc
commit-hash: cc66ad468955717ab92600c770da8c1601a4ff33
commit-date: 2023-10-03
host: x86_64-unknown-linux-gnu
release: 1.73.0
LLVM version: 17.0.2
```

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by estebank**
When encountering trait bound errors that satisfy some heuristics that tell us that the relevant trait for the user comes from the root obligation and not the current obligation, we use the root predicate for the main message.

This allows to talk about "X doesn't implement Pattern<'_>" over the most specific case that just happened to fail, like  "char doesn't implement Fn(&mut char)" in
`tests/ui/traits/suggest-dereferences/root-obligation.rs`

The heuristics are:

 - the type of the leaf predicate is (roughly) the same as the type from the root predicate, as a proxy for "we care about the root"
 - the leaf trait and the root trait are different, so as to avoid talking about `&mut T: Trait` and instead remain talking about `T: Trait` instead
 - the root trait is not `Unsize`, as to avoid talking about it in `tests/ui/coercion/coerce-issue-49593-box-never.rs`.

```
error[E0277]: the trait bound `&char: Pattern<'_>` is not satisfied
  --> $DIR/root-obligation.rs:6:38
   |
LL |         .filter(|c| "aeiou".contains(c))
   |                             -------- ^ the trait `Fn<(char,)>` is not implemented for `&char`, which is required by `&char: Pattern<'_>`
   |                             |
   |                             required by a bound introduced by this call
   |
   = note: required for `&char` to implement `FnOnce<(char,)>`
   = note: required for `&char` to implement `Pattern<'_>`
note: required by a bound in `core::str::<impl str>::contains`
  --> $SRC_DIR/core/src/str/mod.rs:LL:COL
help: consider dereferencing here
   |
LL |         .filter(|c| "aeiou".contains(*c))
   |                                      +
```

Fix #79359, fix #119983, fix #118779, cc #118415 (the suggestion needs to change), cc #121398 (doesn't fix the underlying issue).

### CODE REVIEW

**Comment by estebank** [comment]
CC @lcnr, @compiler-errors, @oli-obk & @fmease. This is an attempt to mitigate the issue highlighted at https://rust-lang.zulipchat.com/#narrow/stream/144729-t-types/topic/Change.20to.20default.20E0277.20message and the linked tickets. There are many more things to be fixed in these errors, but this seemed like a small enough change that could pull its weight to stop confusing people in cases like the `T: Pattern<'_>` one.

File: library/core/src/iter/traits/collect.rs [hunk 1]
```diff
@@ -236,6 +236,49 @@ pub trait FromIterator<A>: Sized {
 /// ```
 #[rustc_diagnostic_item = "IntoIterator"]
 #[rustc_skip_array_during_method_dispatch]
+#[rustc_on_unimplemented(
```
Comment (oli-obk) [inline library/core/src/iter/traits/collect.rs:239]: are these copied from iterator or is there a difference? Maybe document that with a normal comment

File: compiler/rustc_trait_selection/src/traits/error_reporting/type_err_ctxt_ext.rs [hunk 2]
```diff
@@ -409,9 +409,44 @@ impl<'tcx> TypeErrCtxt<'_, 'tcx> {
...
+                            // We rely on a few heuristics to identify cases where this root
+                            // obligation is more important than the leaf obligation:
+                            //
+                            //  - the type of the leaf predicate is (roughly) the same as the type
+                            //    from the root predicate, as a proxy for "we care about the root"
+                            //  - the leaf trait and the root trait are different, so as to avoid
+                            //    talking about `&mut T: Trait` and instead remain talking about
+                            //    `T: Trait` instead
+                            //  - the root trait is not `Unsize`, as to avoid talking about it in
+                            //    `tests/ui/coercion/coerce-issue-49593-box-never.rs`.
```
Comment (oli-obk) [inline compiler/rustc_trait_selection/src/traits/error_reporting/type_err_ctxt_ext.rs:434]: inline these heuristics with their actual checks above, to help keep them in sync with future changes

File: library/core/src/iter/traits/collect.rs (hunk 1 above)
Comment (estebank) [reply library/core/src/iter/traits/collect.rs:239]: Yes, I took them straight from Iterator and Future. I can iterate on whether removing the others is needed or if only a subset of conditions are needed. I strongly suspect we need to keep all on Iterator and only need a subset on IntoIterator

File: compiler/rustc_trait_selection/src/traits/error_reporting/type_err_ctxt_ext.rs (hunk 2 above)
Comment (estebank) [reply compiler/rustc_trait_selection/src/traits/error_reporting/type_err_ctxt_ext.rs:434]: Will do. I prefer that style as well, I've moved away from it recently because it messes up with rustfmt.

File: tests/ui/traits/suggest-dereferences/root-obligation.stderr [hunk 3]
```diff
@@ -1,12 +1,11 @@
-error[E0277]: expected a `Fn(char)` closure, found `char`
+error[E0277]: the trait bound `&char: Pattern<'_>` is not satisfied
```
Comment (estebank) [inline tests/ui/traits/suggest-dereferences/root-obligation.stderr:1]: This error, in the future (not this PR) it should actually be:

```
error[E0277]: the trait bound `&char: Pattern<'_>` is not satisfied
  --> $DIR/root-obligation.rs:6:38
   |
LL |         .filter(|c| "aeiou".contains(c))
   |                             -------- ^ the trait `Pattern<'_>` is not implemented for `&char`
   |                             |
   |                             required by a bound introduced by this call
   |
note: required by a bound in `core::str::contains`
  --> $SRC_DIR/core/src/str/mod.rs:LL:COL
help: consider dereferencing here
   |
LL |         .filter(|c| "aeiou".contains(*c))
   |                                      +
```

instead of

```
error[E0277]: the trait bound `&char: Pattern<'_>` is not satisfied
  --> $DIR/root-obligation.rs:6:38
   |
LL |         .filter(|c| "aeiou".contains(c))
   |                             -------- ^ the trait `Fn<(char,)>` is not implemented for `&char`, which is required by `&char: Pattern<'_>`
   |                             |
   |                             required by a bound introduced by this call
   |
   = note: required for `&char` to implement `FnOnce<(char,)>`
   = note: required for `&char` to implement `Pattern<'_>`
note: required by a bound in `core::str::<impl str>::contains`
  --> $SRC_DIR/core/src/str/mod.rs:LL:COL
help: consider dereferencing here
   |
LL |         .filter(|c| "aeiou".contains(*c))
   |                                      +
```

File: library/core/src/iter/traits/collect.rs (hunk 1 above)
Comment (estebank) [reply library/core/src/iter/traits/collect.rs:239]: So I took a quick look and funnily enough this change actually improves the situation of not knowing when the error is coming from an expression desugaring or type context, because all desugaring uses the `Into*` traits, while most normal code uses the actual traits, so we can leave the expression level suggestions in the conversion traits (almost, deref would need to be accounted, as per the `FIXME` comment) exclusively.

File: compiler/rustc_trait_selection/src/traits/error_reporting/type_err_ctxt_ext.rs [hunk 4]
```diff
@@ -409,9 +409,51 @@ impl<'tcx> TypeErrCtxt<'_, 'tcx> {
...
+                            ty::ClauseKind::Trait(root_pred)
+                        ) = root_obligation.predicate.kind().skip_binder()
+                            // The type of the leaf predicate is (roughly) the same as the type
+                            // from the root predicate, as a proxy for "we care about the root"
+                            // FIXME: this doesn't account for trivial derefs, but works as a first
+                            // approximation.
+                            && (
+                                // `T: Trait` && `&&T: OtherTrait`, we want `OtherTrait`
+                                trait_predicate.self_ty().skip_binder()
+                                    == root_pred.self_ty().peel_refs()
```
Comment (oli-obk) [inline compiler/rustc_trait_selection/src/traits/error_reporting/type_err_ctxt_ext.rs:429]: is it intended that we treat types with lifetimes differently if their lifetimes differ? We'll just have fewer cases where we switch to the root obligation, but I'm not sure whether it'll miss out on cases where we'd want to use the root.

I'll give it a more thorough look next week, but if you have ideas here, maybe add some tests where the self type has lifetimes

Comment (estebank) [reply compiler/rustc_trait_selection/src/traits/error_reporting/type_err_ctxt_ext.rs:429]: We could use `can_eq` instead here.

Comment (oli-obk) [reply compiler/rustc_trait_selection/src/traits/error_reporting/type_err_ctxt_ext.rs:429]: Yea good point. If that shows some tests that are affected, good, otherwise we need to write some

File: tests/ui/associated-types/substs-ppaux.normal.stderr [hunk 5]
```diff
@@ -70,13 +70,12 @@ help: use parentheses to call this function
 LL |     let x: () = foo::<'static>();
    |                               ++
 
-error[E0277]: the size for values of type `str` cannot be known at compilation time
+error[E0277]: the trait bound `str: Foo<'_, '_, u8>` is not satisfied
   --> $DIR/substs-ppaux.rs:49:6
    |
 LL |     <str as Foo<u8>>::bar;
-   |      ^^^ doesn't have a size known at compile-time
+   |      ^^^ the trait `Sized` is not implemented for `str`, which is required by `str: Foo<'_, '_, u8>`
```
Comment (fmease) [inline tests/ui/associated-types/substs-ppaux.normal.stderr:77]: I haven't read the implementation or the most recent Zulip comment and just saw this stderr diff, so sorry if this has been discussed already.

Is this intentional? Shouldn't we still use the `[rustc_on_unimplemented]`/`#[diagnostic::on_unimplemented]` message here despite the derived/root obligation changes?

Comment (estebank) [reply tests/ui/associated-types/substs-ppaux.normal.stderr:77]: It is somewhat intentional. When you have `T: Sized` then you want `T` to have a compile time known size. When you have `T: Foo, Foo: Sized`, I think it makes sense to go back to "`T` does not implement `Sized`", it's a subtle difference of "what does the user care about".

Comment (estebank) [reply tests/ui/associated-types/substs-ppaux.normal.stderr:77]: Also, I do want to do a full refactor of this logic, too many ad-hoc hacks have piled beyond maintainability (in no small part due to me), but now that we know what the *output* we want to keep and change is, it will be easier to clean this up in a way that makes sense. This PR is about putting the output piece closer to that "ideal end state" in anticipation of that work.

File: compiler/rustc_trait_selection/src/traits/error_reporting/type_err_ctxt_ext.rs (hunk 4 above)
Comment (estebank) [reply compiler/rustc_trait_selection/src/traits/error_reporting/type_err_ctxt_ext.rs]: None of new tests were affected (after I checked for no escaping vars). I'll have to think of a case where lifetime divergence is the issue *but* that doesn't manifest as an `OutlivesPredicate` clause.
