### PR TITLE
emit "align 1" metadata on loads/stores of packed structs

### LINKED ISSUE #39376: rustc_trans doesn't emit alignment information causing llvm to assume abi alignment
commit 7bc10545d635bc1f4a5632703823a6f18113df9c attempted to fix unaligned loads, but appears to have only resolved part of the problem and may have unintentionally left things a little broken on architectures with strict alignment requirements.

That commit changed bytes_to_words to return `&[Unaligned<u32>]`, but made that type `#[repr(packed)]`.

I'm currently working with a fellow colleague on a port of rust to another architecture and we hit this:

```rust
Thread 4 received signal SIGSEGV, Segmentation fault.
[Switching to Thread 2 (LWP 2)]
0xffffffff50037b34 in rustc_metadata::schema::LazySeq<rustc_metadata::index::Index>::lookup (self=0xffffffff7b861df0, bytes=..., def_index=...)
    at /builds/rust.git/src/librustc_metadata/index.rs:73
73              let position = u32::from_le(words[index].get());
(gdb) print words
$37 = &[rustc_metadata::index::Unaligned<u32>] {data_ptr: 0xffffffff793ae6b6, length: 6908}
(gdb) print index
$38 = 5283
(gdb) print words[index]
$39 = rustc_metadata::index::Unaligned<u32> (4092795392)
```

A disassembly of the call site shows this:

```rust
(gdb) disassemble 0xffffffff50037b34-16,+32
Dump of assembler code from 0xffffffff50037b24 to 0xffffffff50037b44:
   0xffffffff50037b24 <rustc_metadata::schema::LazySeq<rustc_metadata::index::Index>::lookup+864>:      nop 
   0xffffffff50037b28 <rustc_metadata::schema::LazySeq<rustc_metadata::index::Index>::lookup+868>:      ldx  [ %fp + 0x627 ], %i0
   0xffffffff50037b2c <rustc_metadata::schema::LazySeq<rustc_metadata::index::Index>::lookup+872>:      ldx  [ %fp + 0x537 ], %i1
   0xffffffff50037b30 <rustc_metadata::schema::LazySeq<rustc_metadata::index::Index>::lookup+876>:      sllx  %i1, 2, %i2
=> 0xffffffff50037b34 <rustc_metadata::schema::LazySeq<rustc_metadata::index::Index>::lookup+880>:      ld  [ %i0 + %i2 ], %i0
   0xffffffff50037b38 <rustc_metadata::schema::LazySeq<rustc_metadata::index::Index>::lookup+884>:      st  %i0, [ %fp + 0x6e7 ]
   0xffffffff50037b3c <rustc_metadata::schema::LazySeq<rustc_metadata::index::Index>::lookup+888>:      st  %i0, [ %fp + 0x7d7 ]
   0xffffffff50037b40 <rustc_metadata::schema::LazySeq<rustc_metadata::index::Index>::lookup+892>:      call  0xffffffff50038054 <rustc_metadata::index::Unaligned<u32>::get<u32>>
(gdb) print/a $i0    
$40 = 0xffffffff793ae6b6
(gdb) print/a $i2
$41 = 0x528c
(gdb) print/a ($i0+$i2)
$42 = 0xffffffff793b3942
(gdb) print/x *($i0+$i2)
$44 = 0xf3f31a00
```

Now, if I'm not mistaken it looks like it's trying to perform an `ld` (aka `lduw`; load unsigned word) and a word is 4 bytes, but the offset of the memory address it's trying to read from is byte-aligned, not word-aligned, due to the `#[repr(packed)]`, which I believe is causing the fault since what seems like a valid value appears to be there.

I suspect this is another case of issue #27060, but while we're waiting for that to be fixed, should the packed directive be removed instead?

I plan to try that fix myself soon, but wanted confirmation that was a reasonable change before attempting it.

### PR DESCRIPTION
**Pull request by arielb1**
According to the LLVM reference:
> A value of 0 or an omitted align argument means that the operation has
the ABI alignment for the target.

So loads/stores of fields of packed structs need to have their align set
to 1. Implement that by tracking the alignment of `LvalueRef`s.

Fixes #39376.

r? @eddyb

### CODE REVIEW

File: src/librustc_trans/intrinsic.rs [hunk 1]
```diff
@@ -243,7 +245,7 @@ pub fn trans_intrinsic_call<'a, 'tcx>(bcx: &Builder<'a, 'tcx>,
                 bcx.volatile_store(llargs[2], get_meta(bcx, llargs[0]));
             } else {
                 let val = if fn_ty.args[1].is_indirect() {
-                    bcx.load(llargs[1])
+                    bcx.load(llargs[1], None) // FIXME: this is incorrect
```
Comment (eddyb) [inline src/librustc_trans/intrinsic.rs]: Are you going to do something about this?

**Comment by eddyb** [comment]
LGTM, except for that one FIXME. f? @aatch, r=me if no other concerns are raised.

File: src/librustc_trans/intrinsic.rs (hunk 1 above)
Comment (arielb1) [inline src/librustc_trans/intrinsic.rs]: This is hard to fix without a refactor.

**Comment by arielb1** [comment]
And the FIXME turned out to be unneeded - ABI indirect arguments are always aligned.

@bors r=eddyb

**Comment by arielb1** [comment]
rebased

@bors r=eddyb

**Comment by binarycrusader** [comment]
Unfortunately, this patch doesn't seem to resolve the issue fully.  See #39376 for an example test case that appears to still fail.

**Comment by binarycrusader** [comment]
This is seen in the RUST_LOG=4 output when building the referenced example:

```
DEBUG:rustc_trans::builder: Store (%"Unaligned<u32>" = type <{ i32 }>:  %27 = load %"Unaligned<u32>", %"Unaligned<u32>"* %26, !dbg !85) -> (%"Unaligned<u32>"*:  %_14 = alloca %"Unaligned<u32>")
DEBUG:rustc_trans::builder: Store (%"Unaligned<u32>" = type <{ i32 }>:  %28 = load %"Unaligned<u32>", %"Unaligned<u32>"* %_14, !dbg !85) -> (%"Unaligned<u32>"*:  %arg1 = alloca %"Unaligned<u32>")
```

**Comment by arielb1** [comment]
@binarycrusader 

I compile your example using your patch - that's it, 

```Rust
use std::slice;
use std::u32;

#[repr(packed)]
#[derive(Copy, Clone)]
struct Unaligned<T>(T);

impl<T> Unaligned<T> {
    fn get(self) -> T { self.0 }
}

fn bytes_to_words(b: &[u8]) -> &[Unaligned<u32>] {
    unsafe { slice::from_raw_parts(b.as_ptr() as *const Unaligned<u32>, b.len() / 4) }
}

fn main() {
        let values = String::from("fedcba98765432100123456789abcdef");
        let bytes = values.as_bytes();
        let mut words = &bytes_to_words(&bytes[1..]);
        let index = 1;
        let position = u32::from_le(words[index].get());
}
```

and it works (emits align metadata on the necessary loads).

Is there some other example you are talking about?

**Comment by binarycrusader** [comment]
Would someone be willing to beta-nominate this?  This patch has been used successfully against 1.16 beta for almost two weeks and resolved the last code generation issue we encountered on sparc (and I suspect would help other architectures too).  I believe it applies cleanly without any changes to current beta tip.
