### PR TITLE
Make the enum check work for negative discriminants

### LINKED ISSUE #143218: New enum discrimintant check doesn't work for negative numbers
I tried this code:

```rust
#[derive(Debug, PartialEq, Eq)]
enum Foo {
    Negative = -1,
    Positive = 1,
}

#[test]
fn t() {
    let transmuted: Foo = unsafe {
        std::mem::transmute::<i8, Foo>(-1)
    };
    
    assert_eq!(transmuted, Foo::Negative);
}
```

I expected to see this happen: The test passes

Instead, this happened: 

```
thread 't' panicked at src/lib.rs:10:9:
trying to construct an enum from an invalid value 0xffffffffffffffffffffffffffffffff
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread caused non-unwinding panic. aborting.
```

### Meta

`rustc --version --verbose`:
```
rustc 1.90.0-nightly (11ad40bb8 2025-06-28)
binary: rustc
commit-hash: 11ad40bb839ca16f74784b4ab72596ad85587298
commit-date: 2025-06-28
host: x86_64-unknown-linux-gnu
release: 1.90.0-nightly
LLVM version: 20.1.7
```

Playground link: https://play.rust-lang.org/?version=nightly&mode=debug&edition=2024&gist=c5012dd5ec0afc1bea52e85e81ff28e9

Seems to be related to https://github.com/rust-lang/rust/pull/141759

</p>
</details>

### PR DESCRIPTION
**Pull request by 1c3t3a**
The discriminant check was not working correctly for negative numbers. This change fixes that by masking out the relevant bits correctly.

Fixes rust-lang/rust#143218.

### CODE REVIEW

File: tests/ui/mir/enum/negative_discr_ok.rs [hunk 1]
```diff
@@ -0,0 +1,15 @@
...
+//@ compile-flags: -C debug-assertions
+
+#[allow(dead_code)]
+enum Foo {
+    A = -2,
+    B = 1,
+}
+
+fn main() {
+    let _val: Foo =
```
Comment (compiler-errors) [inline tests/ui/mir/enum/negative_discr_ok.rs]: This is a run-pass test so it should probably actually be comparing the transmuted value to ensure they are correct? Just for certainty.

File: tests/ui/mir/enum/negative_discr_ok.rs [hunk 2]
```diff
@@ -0,0 +1,15 @@
+//@ run-pass
+//@ compile-flags: -C debug-assertions
+
+#[allow(dead_code)]
+enum Foo {
+    A = -2,
+    B = 1,
```
Comment (compiler-errors) [inline tests/ui/mir/enum/negative_discr_ok.rs]: Could we test more values than 2 of them? And more discriminant sizes?

File: compiler/rustc_mir_transform/src/check_enums.rs [hunk 3]
```diff
@@ -349,13 +350,41 @@ fn insert_direct_enum_check<'tcx>(
...
 
+    // Mask out the bits of the discriminant type.
+    let mask = match discr.size.bytes() {
+        1 => u8::MAX as u128,
+        2 => u16::MAX as u128,
+        4 => u32::MAX as u128,
+        8 => u64::MAX as u128,
+        16 => u128::MAX as u128,
+        invalid => bug!("Found discriminant with invalid size, has {} bytes", invalid),
+    };
```
Comment (scottmcm) [inline compiler/rustc_mir_transform/src/check_enums.rs]: Is this just <https://doc.rust-lang.org/nightly/nightly-rustc/rustc_abi/struct.Size.html#method.unsigned_int_max>?

File: compiler/rustc_mir_transform/src/check_enums.rs [hunk 4]
```diff
@@ -349,13 +350,41 @@ fn insert_direct_enum_check<'tcx>(
...
+
     // Branch based on the discriminant value.
     block_data.terminator = Some(Terminator {
         source_info,
         kind: TerminatorKind::SwitchInt {
-            discr: Operand::Copy(discr),
+            discr: Operand::Copy(discr_masked),
             targets: SwitchTargets::new(
-                discriminants.into_iter().map(|discr| (discr, new_block)),
+                discriminants.into_iter().map(|discr| (discr & mask, new_block)),
```
Comment (scottmcm) [inline compiler/rustc_mir_transform/src/check_enums.rs]: Note that if you have a constant that you want to mask (rather than the runtime value as previous) then there's also <https://doc.rust-lang.org/nightly/nightly-rustc/rustc_abi/struct.Size.html#method.truncate>.

File: tests/ui/mir/enum/negative_discr_ok.rs (hunk 1 above)
Comment (1c3t3a) [reply tests/ui/mir/enum/negative_discr_ok.rs]: Done!

File: tests/ui/mir/enum/negative_discr_ok.rs (hunk 2 above)
Comment (1c3t3a) [reply tests/ui/mir/enum/negative_discr_ok.rs]: Done! I added more values and another i64 enum.

File: compiler/rustc_mir_transform/src/check_enums.rs (hunk 3 above)
Comment (1c3t3a) [reply compiler/rustc_mir_transform/src/check_enums.rs]: Yes!! Thanks a lot, that's helpful!

File: compiler/rustc_mir_transform/src/check_enums.rs (hunk 4 above)
Comment (1c3t3a) [reply compiler/rustc_mir_transform/src/check_enums.rs]: Thanks, I am using that now :)

**Comment by compiler-errors** [comment]
Please fix the submodules you've updated

**Comment by 1c3t3a** [comment]
Upps sorry, here we go!

**Review by SparrowLii — APPROVED** [review]
LGTM， thanks for the fix!
