### PR TITLE
Fix too restrictive checks on Drop impls

### LINKED ISSUE #34426: Spurious error "The requirement ... is added only by the Drop impl"
It seems like it's not possible to implement `Drop` for types that have higher ranked trait bounds on their type arguments.

``` rust
trait WithLifetime<'a> {
}

struct Foo<A: for<'a> WithLifetime<'a>> {
    a: A,
}

impl<A: for<'a> WithLifetime<'a>> Drop for Foo<A> {
    fn drop(&mut self) {}
}
```

This gives the error _"The requirement `for<'a> A: WithLifetime<'a>` is added only by the Drop impl"_ which is obviously untrue. Removing that bound from the `Drop` impl gives the error _"the trait bound `for<'a> A: WithLifetime<'a>` is not satisfied"_ as it should.

### LINKED ISSUE #58311: Erroneous E0367 on struct containing a closure returning an array
The following code fails in the playground, on the latest stable (1.32.0), latest beta (1.33.0-beta.6) and latest nightly (2019-02-07):
```rust
struct S<F: Fn() -> [u8; 1]>(F);

impl<F: Fn() -> [u8; 1]> Drop for S<F> {
    fn drop(&mut self) {}
}

fn main() {}
```
The error is the following:
```
error[E0367]: The requirement `<F as std::ops::FnOnce<()>>::Output == [u8; _]` is added only by the Drop impl.
 --> src/main.rs:3:1
  |
3 | / impl<F: Fn() -> [u8; 1]> Drop for S<F> {
4 | |     fn drop(&mut self) {}
5 | | }
  | |_^
  |
note: The same requirement must be part of the struct/enum definition
 --> src/main.rs:1:1
  |
1 | struct S<F: Fn() -> [u8; 1]>(F);
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```
The error seems to be the same regardless of rust version, and regardless of whether the function is an `Fn`, an `FnMut`, or an `FnOnce` (in particular, the error mentions `std::ops::FnOnce<()>>::Output` even when `F` isn't an `FnOnce`, if that's relevant).

The error does not occur when the return type `[u8; 1]` is replaced with, for example, `u8` or `(u8, u8)`, but still occurs with a more complex type still containing an array such as `(u8, [u8; 1], u8)`;

Have a nice day.

### PR DESCRIPTION
**Pull request by TommasoBianchi**
Fixes #34426. Fixes #58311.

This PR completes and extends #59497 (which has been inactive for a while now).
The problem generating both issues was that when checking that the `Predicate`s of the `Drop` impl are exactly the same as the ones of the struct definition, the check was essentially performed by a simple `==` operator, which was not handling correctly HRTBs and involved `Fn` types.

The implemented solution relies on the `relate` machinery to more correctly equate `Predicate`s, and on `anonymize_late_bound_regions` to handle HRTB in a more general way. As the `Relate` trait currently is implemented only for `TraitPredicate` and `ProjectionPredicate` (and as they were the ones generating problems), `relate` is used only for them while for other `Predicate`s the equality check is kept. I'm currently considering whether it would make sense to implement the `Relate` trait also for all other `Predicate`s to render the proposed solution more general.

### CODE REVIEW

**Comment by Centril** [comment]
cc @arielb1 @matthewjasper

File: src/librustc_typeck/check/dropck.rs [hunk 1]
```diff
@@ -83,10 +87,7 @@ fn ensure_drop_params_and_item_params_correspond<'tcx>(
         let fresh_impl_self_ty = drop_impl_ty.subst(tcx, fresh_impl_substs);
 
         let cause = &ObligationCause::misc(drop_impl_span, drop_impl_hir_id);
-        match infcx
```
Comment (pnkfelix) [inline src/librustc_typeck/check/dropck.rs]: please try to avoid making pure-formatting changes in the same commit that has effectual semantic changes.

(If the reformatting is being injected by e.g. running `rustfmt`, then try to do those runs in a separate commit, please.)

File: src/librustc_typeck/check/dropck.rs [hunk 2]
```diff
@@ -97,12 +98,13 @@ fn ensure_drop_params_and_item_params_correspond<'tcx>(
...
                     "Implementations of Drop cannot be specialized"
-                ).span_note(
+                )
+                .span_note(
                     item_span,
                     "Use same sequence of generic type and region \
                      parameters that is on the struct/enum definition",
                 )
-                    .emit();
+                .emit();
```
Comment (pnkfelix) [inline src/librustc_typeck/check/dropck.rs]: follow-up to other note about formatting changes: while I stand by my claim that I prefer formatting changes to be segregated into their own commits, I will say that if the formatting "fixes" were solely to formatting "bugs" that are this egregious, I myself would probably leave them in the same commit too.

File: src/librustc_typeck/check/dropck.rs (hunk 1 above)
Comment (pnkfelix) [reply src/librustc_typeck/check/dropck.rs]: (the reason I'm asking for it to be in a separate commit is that it eases review: It allows the reviewer to just quickly skim the commits that are formatting fixes, while diving into the commits that have the real meat!)

File: src/librustc_typeck/check/dropck.rs [hunk 3]
```diff
@@ -212,20 +216,40 @@ fn ensure_drop_predicates_are_implied_by_item_defn<'tcx>(
         // the analysis together via the fulfill , rather than the
         // repeated `contains` calls.
```
Comment (pnkfelix) [inline src/librustc_typeck/check/dropck.rs]: there is comment here that only makes sense based on the prior version of the code that called `.contains(..)`. Can you update the comment accordingly for future code readers?

**Comment by pnkfelix** [comment]
this looks good. r=me once the formatting changes are factored out and the noted comment about `contains` is updated in some reasonable way.

**Comment by TommasoBianchi** [comment]
r=@pnkfelix thank you for the review, I should have fixed both problems.
I am still curious about whether it would be beneficial to implement equality for all `Predicate`s using the `Relate` trait; probably it is better to just be conservative and change as little as possible while still fixing the open issues.

File: src/librustc_typeck/check/dropck.rs (hunk 1 above)
Comment (Centril) [reply src/librustc_typeck/check/dropck.rs]: Btw, ticking the "hide whitespace changes" checkbox usually helps a bit with this when reviewing.
