### PR TITLE
btree: avoid forcing the allocator to be a reference

### LINKED ISSUE #98176: ICE: invalid scalar pair layout
[This test in Miri](https://github.com/rust-lang/miri/blob/3d634c975c7d7faf92a46d7d9a1a0267bd48e86a/tests/pass/btreemap.rs) recently started ICEing:
```
error: internal compiler error: /rustc/6ec3993ef4a4eb72bc20477fe9a4d92acd53f2c6/compiler/rustc_const_eval/src/interpret/place.rs:771:68: write_immediate_to_mplace: invalid ScalarPair layout: TyAndLayout {
                                    ty: *mut alloc::collections::btree::node::LeafNode<Foo, ()>,
                                    layout: Layout {
                                        fields: Primitive,
                                        variants: Single {
                                            index: 0,
                                        },
                                        abi: Scalar(
                                            Initialized {
                                                value: Pointer,
                                                valid_range: 0..=18446744073709551615,
                                            },
                                        ),
                                        largest_niche: None,
                                        align: AbiAndPrefAlign {
                                            abi: Align(8 bytes),
                                            pref: Align(8 bytes),
                                        },
                                        size: Size(8 bytes),
                                    },
                                }
  --> /home/r/.rustup/toolchains/miri/lib/rustlib/src/rust/library/alloc/src/collections/btree/node.rs:84:28
   |
84 |             LeafNode::init(leaf.as_mut_ptr());
   |                            ^^^^^^^^^^^^^^^^^
```
So we have a ScalarPair value with Scalar layout. Clearly something went wrong somewhere earlier when that value was constructed.

<details><summary>Backtrace</summary>

```
thread 'rustc' panicked at 'Box<dyn Any>', /rustc/6ec3993ef4a4eb72bc20477fe9a4d92acd53f2c6/compiler/rustc_errors/src/lib.rs:1331:9
stack backtrace:
   0:     0x7f5e230ae4cd - std::backtrace_rs::backtrace::libunwind::trace::ha65f46174cdb360a
                               at /rustc/6ec3993ef4a4eb72bc20477fe9a4d92acd53f2c6/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x7f5e230ae4cd - std::backtrace_rs::backtrace::trace_unsynchronized::hfbfbd995eed88907
                               at /rustc/6ec3993ef4a4eb72bc20477fe9a4d92acd53f2c6/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7f5e230ae4cd - std::sys_common::backtrace::_print_fmt::hb9a4b91d9836896b
                               at /rustc/6ec3993ef4a4eb72bc20477fe9a4d92acd53f2c6/library/std/src/sys_common/backtrace.rs:66:5
   3:     0x7f5e230ae4cd - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h74b81077de211a85
                               at /rustc/6ec3993ef4a4eb72bc20477fe9a4d92acd53f2c6/library/std/src/sys_common/backtrace.rs:45:22
   4:     0x7f5e2310a30c - core::fmt::write::h79f47bb3504917f6
                               at /rustc/6ec3993ef4a4eb72bc20477fe9a4d92acd53f2c6/library/core/src/fmt/mod.rs:1196:17
   5:     0x7f5e2309fa91 - std::io::Write::write_fmt::h3937ab33a0b333dc
                               at /rustc/6ec3993ef4a4eb72bc20477fe9a4d92acd53f2c6/library/std/src/io/mod.rs:1654:15
   6:     0x7f5e230b11a5 - std::sys_common::backtrace::_print::h93abfd2adb3fdfb0
                               at /rustc/6ec3993ef4a4eb72bc20477fe9a4d92acd53f2c6/library/std/src/sys_common/backtrace.rs:48:5
   7:     0x7f5e230b11a5 - std::sys_common::backtrace::print::h35a3573fe2a0b616
                               at /rustc/6ec3993ef4a4eb72bc20477fe9a4d92acd53f2c6/library/std/src/sys_common/backtrace.rs:35:9
   8:     0x7f5e230b11a5 - std::panicking::default_hook::{{closure}}::h0e88dc5c1d6b72c1
                               at /rustc/6ec3993ef4a4eb72bc20477fe9a4d92acd53f2c6/library/std/src/panicking.rs:295:22
   9:     0x7f5e230b0ec6 - std::panicking::default_hook::h472eb815610d1ad9
                               at /rustc/6ec3993ef4a4eb72bc20477fe9a4d92acd53f2c6/library/std/src/panicking.rs:314:9
  10:     0x7f5e23888d81 - rustc_driver[f30206aada3619d2]::DEFAULT_HOOK::{closure#0}::{closure#0}
  11:     0x7f5e230b187a - std::panicking::rust_panic_with_hook::h65d3a31645b7d9c0
                               at /rustc/6ec3993ef4a4eb72bc20477fe9a4d92acd53f2c6/library/std/src/panicking.rs:702:17
  12:     0x55940784c023 - std::panicking::begin_panic::{{closure}}::h3cd7d2520ba0a39c
                               at /rustc/6ec3993ef4a4eb72bc20477fe9a4d92acd53f2c6/library/std/src/panicking.rs:617:9
  13:     0x55940784bff6 - std::sys_common::backtrace::__rust_end_short_backtrace::hf2f19a7d201a3078
                               at /rustc/6ec3993ef4a4eb72bc20477fe9a4d92acd53f2c6/library/std/src/sys_common/backtrace.rs:138:18
  14:     0x5594076b6a96 - std::panicking::begin_panic::h6814c3cf587ca3fb
                               at /rustc/6ec3993ef4a4eb72bc20477fe9a4d92acd53f2c6/library/std/src/panicking.rs:616:12
  15:     0x559407819b66 - std::panic::panic_any::hfff2880ea7eb7866
                               at /rustc/6ec3993ef4a4eb72bc20477fe9a4d92acd53f2c6/library/std/src/panic.rs:61:5
  16:     0x559407819013 - rustc_errors::HandlerInner::span_bug::h08b5b6a6c06108aa
                               at /rustc/6ec3993ef4a4eb72bc20477fe9a4d92acd53f2c6/compiler/rustc_errors/src/lib.rs:1331:9
  17:     0x559407819b0a - rustc_errors::Handler::span_bug::h43e80d1caefd13a6
                               at /rustc/6ec3993ef4a4eb72bc20477fe9a4d92acd53f2c6/compiler/rustc_errors/src/lib.rs:912:9
  18:     0x559407845549 - rustc_middle::util::bug::opt_span_bug_fmt::{{closure}}::hc07de1ff7ee9cfd9
                               at /rustc/6ec3993ef4a4eb72bc20477fe9a4d92acd53f2c6/compiler/rustc_middle/src/util/bug.rs:34:40
  19:     0x559407845549 - rustc_middle::ty::context::tls::with_opt::{{closure}}::hd7fb4337a1bf88f4
                               at /rustc/6ec3993ef4a4eb72bc20477fe9a4d92acd53f2c6/compiler/rustc_middle/src/ty/context.rs:1900:40
  20:     0x559407845549 - rustc_middle::ty::context::tls::with_context_opt::h8ef810eb8003f5f6
                               at /rustc/6ec3993ef4a4eb72bc20477fe9a4d92acd53f2c6/compiler/rustc_middle/src/ty/context.rs:1852:22
  21:     0x559407845549 - rustc_middle::ty::context::tls::with_opt::h93bb0b3d4802b0e9
                               at /rustc/6ec3993ef4a4eb72bc20477fe9a4d92acd53f2c6/compiler/rustc_middle/src/ty/context.rs:1900:9
  22:     0x5594078455a9 - rustc_middle::util::bug::opt_span_bug_fmt::hc158fe01d3cd1e01
                               at /rustc/6ec3993ef4a4eb72bc20477fe9a4d92acd53f2c6/compiler/rustc_middle/src/util/bug.rs:31:5
  23:     0x5594076b6a57 - rustc_middle::util::bug::span_bug_fmt::h7b911efb8d56e467
                               at /rustc/6ec3993ef4a4eb72bc20477fe9a4d92acd53f2c6/compiler/rustc_middle/src/util/bug.rs:22:5
  24:     0x559407781814 - rustc_const_eval::interpret::place::<impl rustc_const_eval::interpret::eval_context::InterpCx<M>>::write_immediate_to_mplace_no_validate::h0638e32f5165e0c1
  25:     0x5594077809cb - rustc_const_eval::interpret::place::<impl rustc_const_eval::interpret::eval_context::InterpCx<M>>::write_immediate_no_validate::h69bc9b8a733970d8
                               at /rustc/6ec3993ef4a4eb72bc20477fe9a4d92acd53f2c6/compiler/rustc_const_eval/src/interpret/place.rs:733:9
  26:     0x559407780422 - rustc_const_eval::interpret::place::<impl rustc_const_eval::interpret::eval_context::InterpCx<M>>::copy_op_no_validate::h3950ffa7c8a7eabe
                               at /rustc/6ec3993ef4a4eb72bc20477fe9a4d92acd53f2c6/compiler/rustc_const_eval/src/interpret/place.rs:872:24
  27:     0x55940777ea1d - rustc_const_eval::interpret::place::<impl rustc_const_eval::interpret::eval_context::InterpCx<M>>::copy_op::hbb10dc29e60e83fa
                               at /rustc/6ec3993ef4a4eb72bc20477fe9a4d92acd53f2c6/compiler/rustc_const_eval/src/interpret/place.rs:836:9
  28:     0x55940777ea1d - rustc_const_eval::interpret::place::<impl rustc_const_eval::interpret::eval_context::InterpCx<M>>::copy_op_transmute::h2e5a425a97c34a82
                               at /rustc/6ec3993ef4a4eb72bc20477fe9a4d92acd53f2c6/compiler/rustc_const_eval/src/interpret/place.rs:903:20
  29:     0x55940776c770 - rustc_const_eval::interpret::eval_context::InterpCx<M>::pop_stack_frame::h88260ac54a8018a0
                               at /rustc/6ec3993ef4a4eb72bc20477fe9a4d92acd53f2c6/compiler/rustc_const_eval/src/interpret/eval_context.rs:814:13
  30:     0x559407775bdb - rustc_const_eval::interpret::terminator::<impl rustc_const_eval::interpret::eval_context::InterpCx<M>>::eval_terminator::h662a1237dfdb504c
  31:     0x559407775bdb - rustc_const_eval::interpret::step::<impl rustc_const_eval::interpret::eval_context::InterpCx<M>>::terminator::hf0cbf184e1be5a2d
                               at /rustc/6ec3993ef4a4eb72bc20477fe9a4d92acd53f2c6/compiler/rustc_const_eval/src/interpret/step.rs:305:9
  32:     0x559407747db7 - rustc_const_eval::interpret::step::<impl rustc_const_eval::interpret::eval_context::InterpCx<M>>::step::h2611461c9f6f7522
                               at /rustc/6ec3993ef4a4eb72bc20477fe9a4d92acd53f2c6/compiler/rustc_const_eval/src/interpret/step.rs:71:9
  33:     0x559407747db7 - miri::eval::eval_entry::{{closure}}::h9cce92f32328283b
                               at /home/r/src/rust/miri.2/src/eval.rs:338:29
  34:     0x559407747db7 - miri::eval::eval_entry::hc2a5923a148b7ccd
                               at /home/r/src/rust/miri.2/src/eval.rs:332:38
```

</details>

Good commit: 1f34da9ec8a85b6f86c5fa1c121ab6f88f2f4966
ICE: 6ec3993ef4a4eb72bc20477fe9a4d92acd53f2c6

### PR DESCRIPTION
**Pull request by RalfJung**
The previous code forces the actual allocator used to be some `&A`. This generalizes the code to allow any `A: Copy`. If people truly want to use a reference, they can use `&A` themselves.

Fixes https://github.com/rust-lang/rust/issues/98176

### CODE REVIEW

**Comment by RalfJung** [comment]
Ah there are still some `&` somewhere that create a non-ZST allocator. Not sure what the best way is to find them... but I think we should get rid of them all, since we want this to be truly zero-cost.

**Comment by Amanieu** [comment]
Could this be changed to require `Clone` instead of `Copy`? This is in line with what `HashMap` currently requires.

**Comment by RalfJung** [comment]
I figured Copy would be simpler and good enough since every allocator can be made Copy by using &A. But yeah it can probably be Clone. Not sure when I will get around to do that.

**Comment by thomcc** [comment]
I agree Clone sounds better, at least if it's what HashMap does.

@rustbot label +S-waiting-on-author -S-waiting-on-review

**Comment by RalfJung** [comment]
Okay I made it `Clone`. This is super annoying as many things need to be cloned manually, and I don't quite see how an allocator would be `Clone` but not `Copy`... I hope I did not introduce too many unnecessary clones, as those are hard to find. It is also very hard to be sure that there is not accidentally a `&A` somewhere. Having `impl<A: Allocator> for &A` is suboptimal here.

File: library/alloc/src/collections/btree/map/entry.rs [hunk 1]
```diff
@@ -49,21 +49,21 @@ pub struct VacantEntry<
...
-    #[unstable(feature = "allocator_api", issue = "32838")] A: Allocator = Global,
+    #[unstable(feature = "allocator_api", issue = "32838")] A: Allocator + Clone = Global,
 > {
     pub(super) key: K,
     /// `None` for a (empty) map without root
     pub(super) handle: Option<Handle<NodeRef<marker::Mut<'a>, K, V, marker::Leaf>, marker::Edge>>,
     pub(super) dormant_map: DormantMutRef<'a, BTreeMap<K, V, A>>,
 
-    pub(super) alloc: &'a A,
+    pub(super) alloc: A,
```
Comment (RalfJung) [inline library/alloc/src/collections/btree/map/entry.rs:59]: Should this be `ManuallyDrop<A>`? It is in the btree itself, presumably due to drop ordering concerns. (If `A: Copy` then this would also not be a problem...)

**Comment by thomcc** [comment]
> I don't quite see how an allocator would be Clone but not Copy

It holding an `Arc` internally is a common example.

**Comment by TennyZhuang** [comment]
> I figured Copy would be simpler and good enough since every allocator can be made Copy by using &A. But yeah it can probably be Clone. Not sure when I will get around to do that.

In fact, it's always hard to use `&A`, the main question is who owned the allocator, which has to introduce a self-referential struct. For convenience, we have to use an `Arc<A>`.

**Comment by RalfJung** [comment]
This is blocking getting Miri to work again (https://github.com/rust-lang/rust/issues/98107), so would be good to get it landed soon. :)

**Comment by thomcc** [comment]
Thanks, this looks fine to me.

@bors r+

**Comment by RalfJung** [comment]
@bors p=1
unblocks Miri

**Comment by joboet** [comment]
The `Clone` bound concerns me, as it is called often, so it will impact performance for not-so-cheap clones like `Arc`. Also, it makes it impossible to store allocator data inline, which might be nice for things like slab-allocators in kernels. Couldn't this use a wrapper struct like this:
```rust
struct AllocRef<'a, A> {
    allocator: [&'a A; (size_of::<A> > 0) as usize],
}

impl<'a, A: Alllcator> Deref for AllocRef<'a, A> {
    type Target = A;

    fn deref(&self) -> &A {
        // This should be fine?
        self.allocator.get(0).unwrap_or_else(|| unsafe { NonNull::dangling().as_ref })
    }
}

impl<'a, A> Copy for AllocRef<'a, A> {}

impl<'a, A> Clone for AllocRef<'a, A> {
    ...
}
```
which preserves the size of ZSTs but doesn't unnecessarily require `Clone`.

**Comment by RalfJung** [comment]
This sounds like something a user of BTreeMap / HashMap could also do?

**Comment by joboet** [comment]
> This sounds like something a user of BTreeMap / HashMap could also do?

No, because that would require the allocator to be a reference. The problem is that some allocators cannot be cloned, but the `BTreeMap` should own the allocator. For example, if I used a bump allocator to speed up allocations, I cannot return the map.

If something like `AllocRef` were used internally to refer to the allocator, only one instance of the allocator would need to be stored.

**Comment by thomcc** [comment]
@joboet That's very clever. Are you interested in submitting a PR for it?

**Comment by RalfJung** [comment]
> No, because that would require the allocator to be a reference. The problem is that some allocators cannot be cloned, but the BTreeMap should own the allocator. For example, if I used a bump allocator to speed up allocations, I cannot return the map.

Oh I see, so you want BTreeMap to own the allocator but the `Box`es it creates to just borrow it? I thought the idea was the `A` would just be propagated everywhere, but sure -- as long as ZST allocators lead only to ZST allocators, I think this should all be fine.

**Comment by ssomers** [comment]
Allowing `BTreeMap` to own any kind of allocator is one thing, but when the `BTreeMap` temporarily passes its allocator to internal helper functions, does it have to be cloned? Isn't that what call-by-reference is meant to do?

**Comment by RalfJung** [comment]
If that internal helper function creates a `Box<T, A>`, you want to maintain the zero-sizedness of `A`.

IOW, but the default allocator `Global`, `clone` is actually *cheaper* than pass-by-reference.

**Comment by ssomers** [comment]
I understand. But then I don't understand the use of Allocator + Clone everywhere and not Allocator + Copy (obviously, it would be [better without Clone](https://github.com/rust-lang/hashbrown/issues/309) but I sure don't know how). An allocator is used for efficiency, as far as I know. A allocator used in a BTreeMap (and I assume in hashbrown too) can only be used efficiently if it is cheap to clone, because cloning happens all over the place. If people are prepared to implement Clone but not to commit to Copy, why lure them into using it in a map?

**Comment by RalfJung** [comment]
Yeah, well, I was in favor of `Allocator + Copy` but I was asked to use `Clone` instead so I did. This is consistent with what `HashMap` does. I don't know if `HashMap` also needs to do as much cloning as `BTreeMap`.

Anyway discussions on closed PRs are not usually a good idea, so it'd probably be better if you opened a new issue for this.

**Comment by TennyZhuang** [comment]
I found it’s really hard to implement an allocator with reference but without Arc. The struct who owned the map will also owns the allocator itself, which means that it’s unavoidable to introduce Pin, pin_project, and many other complicated and even unsafe codes to implement the self-referential data structure. Using Arc here at least can make it simple and clear.
