### PR TITLE
Fix incorrect LLVM Linkage enum

### LINKED ISSUE #33992: Panic in LLVM when using #[linkage] even with supported targets
```
λ cargo new test-linkage
λ cd test-linkage
λ cat src/lib.rs
#![feature(linkage)]

#[linkage = "extern_weak"]
pub static TEST: bool = false;

λ env RUST_BACKTRACE=1 cargo build --verbose # OR
λ env RUST_BACKTRACE=1 cargo build --verbose --target x86_64-unknown-linux-gnu
   Compiling test-linkage v0.1.0 (file:///C:/Users/Matt%20Ickstadt/Code/Rust/test-linkage)
     Running `rustc src\lib.rs --crate-name test_linkage --crate-type lib -g --out-dir "C:\Users\Matt Ickstadt\Code\Rust\test-linkage\target\x86_64-unknown-linux-gnu\debug" --emit=dep-info,link --target x86_64-unknown-linux-gnu -L "dependency=C:\Users\Matt Ickstadt\Code\Rust\test-linkage\target\x86_64-unknown-linux-gnu\debug" -L "dependency=C:\Users\Matt Ickstadt\Code\Rust\test-linkage\target\x86_64-unknown-linux-gnu\debug\deps"`
Don't know how to emit these
UNREACHABLE executed at C:/bot/slave/nightly-dist-rustc-win-gnu-32/build/src/llvm/lib/CodeGen/AsmPrinter/AsmPrinter.cpp:336!

This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.
error: Could not compile `test-linkage`.

Caused by:
  Process didn't exit successfully: `rustc src\lib.rs --crate-name test_linkage --crate-type lib -g --out-dir C:\Users\Matt Ickstadt\Code\Rust\test-linkage\target\x86_64-unknown-linux-gnu\debug --emit=dep-info,link --target x86_64-unknown-linux-gnu -L dependency=C:\Users\Matt Ickstadt\Code\Rust\test-linkage\target\x86_64-unknown-linux-gnu\debug -L dependency=C:\Users\Matt Ickstadt\Code\Rust\test-linkage\target\x86_64-unknown-linux-gnu\debug\deps` (exit code: 3)
```

Nothing too unexpected, since most targets don't support weak linkage. The error message could be a bit better though, rather than panicing in LLVM.

I was a bit surprised that this problem persists when cross compiling to supported targets, but I suppose that its an LLVM limitation, and a very niche one at that.

cc #29603

### PR DESCRIPTION
**Pull request by mattico**
Followup of #33994 to actually work.

The `Linkage` enum in librustc_llvm got out of sync with the version in LLVM and it caused two variants of the `#[linkage=""]` attribute to break.

This adds the functions `LLVMRustGetLinkage` and `LLVMRustSetLinkage` which convert between the Rust Linkage enum and the LLVM one, which should stop this from breaking every time LLVM changes it.

Possible remaining concerns:
1. There could be a codegen test to make sure that the attributes are applied correctly (I don't know how to do this).
2. ~~The test does not exercise the `appending` linkage. I can't figure out how to make a global static raw pointer to an array. This might not even be possible? If not we should probably remove appending linkage as its unusable in rust.~~ Appending linkage is not 'emittable' anyway.
3. The test only runs on Linux.

Fixes #33992

r? @alexcrichton

### CODE REVIEW

**Comment by alexcrichton** [comment]
@bors: r+ 5897dcc8bba54ebd382a0fbf7afa20ea7b790963

Thanks!

**Comment by mattico** [comment]
4ce90a2 - Fixed tidy

**Comment by TimNN** [comment]
failures:

```
---- [run-pass] run-pass/issue-33992.rs stdout ----
	
error: compilation failed!
status: signal: 6
command: /buildslave/rust-buildbot/slave/auto-linux-64-opt-rustbuild/build/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc /buildslave/rust-buildbot/slave/auto-linux-64-opt-rustbuild/build/src/test/run-pass/issue-33992.rs -L /buildslave/rust-buildbot/slave/auto-linux-64-opt-rustbuild/build/obj/build/x86_64-unknown-linux-gnu/test/run-pass --target=x86_64-unknown-linux-gnu --error-format json -L /buildslave/rust-buildbot/slave/auto-linux-64-opt-rustbuild/build/obj/build/x86_64-unknown-linux-gnu/test/run-pass/issue-33992.stage2-x86_64-unknown-linux-gnu.run-pass.libaux -C prefer-dynamic -o /buildslave/rust-buildbot/slave/auto-linux-64-opt-rustbuild/build/obj/build/x86_64-unknown-linux-gnu/test/run-pass/issue-33992.stage2-x86_64-unknown-linux-gnu -Crpath -O -Lnative=/buildslave/rust-buildbot/slave/auto-linux-64-opt-rustbuild/build/obj/build/x86_64-unknown-linux-gnu/rust-test-helpers
stdout:
------------------------------------------

------------------------------------------
stderr:
------------------------------------------
Should never emit this
UNREACHABLE executed at /buildslave/rust-buildbot/slave/auto-linux-64-opt-rustbuild/build/src/llvm/lib/CodeGen/AsmPrinter/AsmPrinter.cpp:336!

------------------------------------------
```

**Comment by arielb1** [comment]
But `LLVMLinkage` is a part of the supposedly backwards-compatible C ABI! Should we wrap everything?

**Comment by TimNN** [comment]
To quote the llvm source file:

```cpp
  case GlobalValue::ExternalWeakLinkage:
    llvm_unreachable("Should never emit this");
  }
```

File: src/rustllvm/RustWrapper.cpp [hunk 1]
```diff
@@ -1232,3 +1232,72 @@ extern "C" void LLVMRustUnsetComdat(LLVMValueRef V) {
     GlobalObject *GV = unwrap<GlobalObject>(V);
     GV->setComdat(nullptr);
 }
+
+extern "C" unsigned LLVMRustGetLinkage(LLVMValueRef V) {
+    switch (LLVMGetLinkage(V)) {
+        case LLVMExternalLinkage:
```
Comment (arielb1) [inline src/rustllvm/RustWrapper.cpp]: Use an enum (see `LLVMRustDiagnosticKind`).

**Comment by mattico** [comment]
@TimNN AppendingLinkage is part of the same case and should also be removed, I guess.

**Comment by mattico** [comment]
Updated to address issues.

File: src/librustc_llvm/ffi.rs [hunk 2]
```diff
@@ -49,6 +49,10 @@ pub enum CallConv {
 
 /// LLVMLinkage
 ///
+/// This does not attempt to mirror the similar enum in LLVM, as this is fragile
```
Comment (arielb1) [inline src/librustc_llvm/ffi.rs]: nit: comment should be just `/// LLVMRustLinkage`  - see e.g. `LLVMRustAsmDialect`. While you're at it, maybe also convert the other non-LLVMRust enums before they bite us?

File: src/rustllvm/RustWrapper.cpp [hunk 3]
```diff
@@ -1232,3 +1232,86 @@ extern "C" void LLVMRustUnsetComdat(LLVMValueRef V) {
     GlobalObject *GV = unwrap<GlobalObject>(V);
     GV->setComdat(nullptr);
 }
+
```
Comment (arielb1) [inline src/rustllvm/RustWrapper.cpp]: Could you use `from_rust`/`to_rust` functions?

Comment (mattico) [inline src/rustllvm/RustWrapper.cpp]: @arielb1 Can you clarify? I'm not sure what you mean.

Comment (arielb1) [inline src/rustllvm/RustWrapper.cpp]: See the rest of the file, e.g.

```C++

static AtomicOrdering from_rust(LLVMAtomicOrdering Ordering) {
  switch (Ordering) {
    case LLVMAtomicOrderingNotAtomic:
        return AtomicOrdering::NotAtomic;
    case LLVMAtomicOrderingUnordered:
        return AtomicOrdering::Unordered;
    case LLVMAtomicOrderingMonotonic:
        return AtomicOrdering::Monotonic;
    case LLVMAtomicOrderingAcquire:
        return AtomicOrdering::Acquire;
    case LLVMAtomicOrderingRelease:
        return AtomicOrdering::Release;
    case LLVMAtomicOrderingAcquireRelease:
        return AtomicOrdering::AcquireRelease;
    case LLVMAtomicOrderingSequentiallyConsistent:
        return AtomicOrdering::SequentiallyConsistent;
  }

  llvm_unreachable("Invalid LLVMAtomicOrdering value!");
}
```

**Comment by mattico** [comment]
Nits addressed, tests fixed, tidy passed, travis works! :four_leaf_clover:
