### PR TITLE
Keep going if normalized projection has unevaluated consts in `QueryNormalizer`

### LINKED ISSUE #73298: "error: linking with `cc` failed: exit code: 1" regression in release build with const generics
Const generics and release mode and Hc128Rng::seed_from_u64 and rustc 1.45.0-nightly (4bd32c980 2020-05-29) or later cause cc linking error.

To avoid the error, do any of:
- use rustc 1.45.0-nightly (a74d1862d 2020-05-14) or earlier
- remove the `#![feature(const_generics)]`
- remove the `Hc128Rng::seed_from_u64(42)` line
- compile in debug mode

I'm guessing that Hc128Rng::seed_from_u64 is not the only thing that will trigger this, but I have not been able to find any other examples.

### Source code

```rust
#![feature(const_generics)]
use rand::SeedableRng;
use rand_hc::Hc128Rng;

fn main() {
    let _ = Hc128Rng::seed_from_u64(42);
}
```
### Dependancies
```
rand = "0.7.3"
rand_hc = "0.2.0"
```

### Error:
```
error: linking with `cc` failed: exit code: 1
  |
  = note: "cc" "-Wl,--as-needed" "-Wl,-z,noexecstack" "-m64" "-L" "/home/isaac/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "/home/isaac/go/src/github.com/is8ac/cc_err_demo/target/release/deps/cc_err_demo-949370c0c3e7c5b4.cc_err_demo.5gfojped-cgu.0.rcgu.o" "/home/isaac/go/src/github.com/is8ac/cc_err_demo/target/release/deps/cc_err_demo-949370c0c3e7c5b4.cc_err_demo.5gfojped-cgu.1.rcgu.o" "/home/isaac/go/src/github.com/is8ac/cc_err_demo/target/release/deps/cc_err_demo-949370c0c3e7c5b4.cc_err_demo.5gfojped-cgu.2.rcgu.o" "/home/isaac/go/src/github.com/is8ac/cc_err_demo/target/release/deps/cc_err_demo-949370c0c3e7c5b4.cc_err_demo.5gfojped-cgu.3.rcgu.o" "/home/isaac/go/src/github.com/is8ac/cc_err_demo/target/release/deps/cc_err_demo-949370c0c3e7c5b4.cc_err_demo.5gfojped-cgu.4.rcgu.o" "-o" "/home/isaac/go/src/github.com/is8ac/cc_err_demo/target/release/deps/cc_err_demo-949370c0c3e7c5b4" "/home/isaac/go/src/github.com/is8ac/cc_err_demo/target/release/deps/cc_err_demo-949370c0c3e7c5b4.3rdszsq7ibbmb3tn.rcgu.o" "-Wl,--gc-sections" "-pie" "-Wl,-zrelro" "-Wl,-znow" "-Wl,-O1" "-nodefaultlibs" "-L" "/home/isaac/go/src/github.com/is8ac/cc_err_demo/target/release/deps" "-L" "/home/isaac/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-Wl,-Bstatic" "/home/isaac/go/src/github.com/is8ac/cc_err_demo/target/release/deps/librand_hc-a144c651cd5437de.rlib" "/home/isaac/go/src/github.com/is8ac/cc_err_demo/target/release/deps/librand-bec2ad1f072a8aa0.rlib" "/home/isaac/go/src/github.com/is8ac/cc_err_demo/target/release/deps/librand_chacha-542ae1a91c9af789.rlib" "/home/isaac/go/src/github.com/is8ac/cc_err_demo/target/release/deps/libppv_lite86-6c3f11be887055bf.rlib" "/home/isaac/go/src/github.com/is8ac/cc_err_demo/target/release/deps/librand_core-2e34a4d1d07e0522.rlib" "/home/isaac/go/src/github.com/is8ac/cc_err_demo/target/release/deps/libgetrandom-f56bf65617cc4079.rlib" "/home/isaac/go/src/github.com/is8ac/cc_err_demo/target/release/deps/liblibc-dc8395e94d7842f0.rlib" "/home/isaac/go/src/github.com/is8ac/cc_err_demo/target/release/deps/libcfg_if-bd1d23d91bf28674.rlib" "-Wl,--start-group" "/home/isaac/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd-0df9faf88e74ed3b.rlib" "/home/isaac/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libpanic_unwind-f9e6a5fb2e2e8cbc.rlib" "/home/isaac/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libhashbrown-05b3477ba39b37d9.rlib" "/home/isaac/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_std_workspace_alloc-fd43f1008ae3de7b.rlib" "/home/isaac/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libbacktrace-c69fd8a874cc6882.rlib" "/home/isaac/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libbacktrace_sys-4f9ba7dc6471f5d2.rlib" "/home/isaac/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_demangle-a3adee158d70a602.rlib" "/home/isaac/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libunwind-36aa33d5b51fea85.rlib" "/home/isaac/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcfg_if-8ffb67928670fecf.rlib" "/home/isaac/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/liblibc-95ea48ddc44a311b.rlib" "/home/isaac/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/liballoc-4f5122dbbdcc70ab.rlib" "/home/isaac/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_std_workspace_core-68f423c59dc48a40.rlib" "/home/isaac/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcore-54580c7798bf2225.rlib" "-Wl,--end-group" "/home/isaac/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcompiler_builtins-e805fea8b8005cb4.rlib" "-Wl,-Bdynamic" "-lc" "-lm" "-lrt" "-lpthread" "-lutil" "-ldl" "-lutil" "-ldl" "-lrt" "-lpthread" "-lgcc_s" "-lc" "-lm" "-lrt" "-lpthread" "-lutil" "-ldl" "-lutil"
  = note: /usr/bin/ld: /home/isaac/go/src/github.com/is8ac/cc_err_demo/target/release/deps/cc_err_demo-949370c0c3e7c5b4.cc_err_demo.5gfojped-cgu.4.rcgu.o: in function `cc_err_demo::main':
          cc_err_demo.5gfojped-cgu.4:(.text._ZN11cc_err_demo4main17h83b85daad37728b4E+0x27): undefined reference to `core::array::<impl core::convert::AsMut<[T]> for [T; N]>::as_mut'
          /usr/bin/ld: /home/isaac/go/src/github.com/is8ac/cc_err_demo/target/release/deps/cc_err_demo-949370c0c3e7c5b4: hidden symbol `_ZN4core5array92_$LT$impl$u20$core..convert..AsMut$LT$$u5b$T$u5d$$GT$$u20$for$u20$$u5b$T$u3b$$u20$N$u5d$$GT$6as_mut17h6128af6739856507E' isn't defined
          /usr/bin/ld: final link failed: bad value
          collect2: error: ld returned 1 exit status
          

error: aborting due to previous error; 1 warning emitted

error: could not compile `cc_err_demo`.

Caused by:
  process didn't exit successfully: `rustc --crate-name cc_err_demo --edition=2018 src/main.rs --error-format=json --json=diagnostic-rendered-ansi --crate-type bin --emit=dep-info,link -C opt-level=3 -Cembed-bitcode=no -C metadata=949370c0c3e7c5b4 -C extra-filename=-949370c0c3e7c5b4 --out-dir /home/isaac/go/src/github.com/is8ac/cc_err_demo/target/release/deps -L dependency=/home/isaac/go/src/github.com/is8ac/cc_err_demo/target/release/deps --extern rand=/home/isaac/go/src/github.com/is8ac/cc_err_demo/target/release/deps/librand-bec2ad1f072a8aa0.rlib --extern rand_hc=/home/isaac/go/src/github.com/is8ac/cc_err_demo/target/release/deps/librand_hc-a144c651cd5437de.rlib` (exit code: 1)
```

### Version
```
rustc 1.46.0-nightly (feb3536eb 2020-06-09)
binary: rustc
commit-hash: feb3536eba10c2e4585d066629598f03d5ddc7c6
commit-date: 2020-06-09
host: x86_64-unknown-linux-gnu
release: 1.46.0-nightly
LLVM version: 10.0
```

### LINKED ISSUE #82268: linker error with `feature(generic_const_exprs)`
*edit: current minimal repro https://github.com/rust-lang/rust/issues/82268#issuecomment-1165530277*

## Error Message

```
   Compiling playground v0.0.1 (/playground)
warning: the feature `const_generics` is incomplete and may not be safe to use and/or cause compiler crashes
 --> src/main.rs:1:12
  |
1 | #![feature(const_generics, const_evaluatable_checked)]
  |            ^^^^^^^^^^^^^^
  |
  = note: `#[warn(incomplete_features)]` on by default
  = note: see issue #44580 <https://github.com/rust-lang/rust/issues/44580> for more information

warning: the feature `const_evaluatable_checked` is incomplete and may not be safe to use and/or cause compiler crashes
 --> src/main.rs:1:28
  |
1 | #![feature(const_generics, const_evaluatable_checked)]
  |                            ^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: see issue #76560 <https://github.com/rust-lang/rust/issues/76560> for more information

error: internal compiler error: compiler/rustc_middle/src/ty/subst.rs:568:17: const parameter `MASK/#2` (Const { ty: u32, val: Param(MASK/#2) }/2) out of range when substituting substs=[]

thread 'rustc' panicked at 'Box<Any>', /rustc/5fa22fe6f821ac3801d05f624b123dda25fde32c/library/std/src/panic.rs:59:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.52.0-nightly (5fa22fe6f 2021-02-14) running on x86_64-unknown-linux-gnu

note: compiler flags: -C embed-bitcode=no -C codegen-units=1 -C debuginfo=2 --crate-type bin

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [check_item_well_formed] checking that `<(H, T) as Collate<MASK>>` is well-formed
#1 [analysis] running analysis passes on this crate
end of query stack
thread 'rustc' panicked at 'Box<Any>', /rustc/5fa22fe6f821ac3801d05f624b123dda25fde32c/library/std/src/panic.rs:59:5

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.52.0-nightly (5fa22fe6f 2021-02-14) running on x86_64-unknown-linux-gnu

note: compiler flags: -C embed-bitcode=no -C codegen-units=1 -C debuginfo=2 --crate-type bin

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [eval_to_allocation_raw] const-evaluating + checking `<(H, T) as Collate<MASK>>::{constant#0}`
#1 [eval_to_const_value_raw] simplifying constant for the type system `<(H, T) as Collate<MASK>>::{constant#0}`
end of query stack
error: aborting due to previous error; 2 warnings emitted

error: could not compile `playground`

To learn more, run the command again with --verbose.
```

## Code

```
#![feature(const_generics, const_evaluatable_checked)]

struct True;
struct False;

trait ConstBool {
    type Val;
}
struct TypeBool<const X: bool>;

impl ConstBool for TypeBool<true> {
    type Val = True;
}

impl ConstBool for TypeBool<false> {
    type Val = False;
}

trait Collate<const MASK: u32> {
    type Pass;
    type Fail;

    fn collate(self) -> (Self::Pass, Self::Fail);
}

impl<const MASK: u32> Collate<MASK> for () {
    type Pass = ();
    type Fail = ();

    fn collate(self) -> ((), ()) {
        ((), ())
    }
}

trait CollateStep<X, Prev> {
    type Pass;
    type Fail;
    fn collate_step(x: X, prev: Prev) -> (Self::Pass, Self::Fail);
}

impl<X, P, F> CollateStep<X, (P, F)> for TypeBool<true> {
    type Pass = (X, P);
    type Fail = F;

    fn collate_step(x: X, (p, f): (P, F)) -> ((X, P), F) {
        ((x, p), f)
    }
}

impl<X, P, F> CollateStep<X, (P, F)> for TypeBool<false> {
    type Pass = P;
    type Fail = (X, F);

    fn collate_step(x: X, (p, f): (P, F)) -> (P, (X, F)) {
        (p, (x, f))
    }
}

impl<H, T: Collate<{ MASK >> 1 }>, const MASK: u32> Collate<MASK> for (H, T)
where
    TypeBool<{ 1 == MASK & 1 }>: CollateStep<H, (T::Pass, T::Fail)>,
{
    type Pass =
        <TypeBool<{ 1 == MASK & 1 }> as CollateStep<H, (T::Pass, T::Fail)>>::Pass;
    type Fail =
        <TypeBool<{ 1 == MASK & 1 }> as CollateStep<H, (T::Pass, T::Fail)>>::Fail;

    fn collate(self) -> (Self::Pass, Self::Fail) {
        <TypeBool<{ 1 == MASK & 1 }>
         as CollateStep<H, (T::Pass, T::Fail)>>
         ::collate_step(self.0, self.1.collate())
    }
}

fn collate<X,const MASK:u32>(x:X)->(X::Pass, X::Fail)
where X:Collate<MASK> {
    x.collate()
}

fn main() {
    dbg!(collate::<_,3>((4, ('!',()))));
}
```
([Playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=405c97e46c71c0ab9749ef23bbdb04cb))

### LINKED ISSUE #83972: const_generics: link fails with undefined reference, hidden symbol isn't defined
This code [(playground)](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=95832c231ba907ef3491428a04f0f0f8)

```rust
#![feature(const_generics)]

pub trait Foo {
    fn foo(&self);
}

pub struct FooImpl<const N: usize>;
impl<const N: usize> Foo for FooImpl<N> {
    fn foo(&self) {}
}

pub trait Bar: 'static {
    type Foo: Foo;
    fn get() -> &'static Self::Foo;
}

struct BarImpl;
impl Bar for BarImpl {
    type Foo = FooImpl<{ 4 }>;
    fn get() -> &'static Self::Foo {
        &FooImpl
    }
}

pub fn boom<B: Bar>() {
    B::get().foo();
}

fn main() {
    boom::<BarImpl>();
}

```

fails to link with

```

error: linking with `cc` failed: exit status: 1
  |
  = note: "cc" "-m64" "-Wl,--eh-frame-hdr" "-Wl,-znoexecstack" "-Wl,--as-needed" "-L" "/playground/.rustup/toolchains/nightly-x86_*snip*own-linux-gnu/lib/libcompiler_builtins-8b33f9cbbc9652fe.rlib" "-Wl,-Bdynamic" "-lgcc_s" "-lutil" "-lrt" "-lpthread" "-lm" "-ldl" "-lc"
  = note: /usr/bin/ld: /playground/target/debug/deps/playground-dea6a74639071602.playground.27snrtcg-cgu.0.rcgu.o: in function `playground::boom':
          /playground/src/main.rs:26: undefined reference to `<playground::FooImpl<_> as playground::Foo>::foo'
          /usr/bin/ld: /playground/target/debug/deps/playground-dea6a74639071602: hidden symbol `_ZN64_$LT$playground..FooImpl$LT$_$GT$$u20$as$u20$playground..Foo$GT$3foo17hc9e5ef50b3fc24d9E' isn't defined
          /usr/bin/ld: final link failed: bad value
          collect2: error: ld returned 1 exit status
```

`rustc --version --verbose`:
```
rustc 1.53.0-nightly (c051c5ddd 2021-04-06)
binary: rustc
commit-hash: c051c5ddda79f45fad196ca3a4690251e377d043
commit-date: 2021-04-06
host: x86_64-unknown-linux-gnu
release: 1.53.0-nightly
LLVM version: 12.0.0
```

### LINKED ISSUE #84669: more generic const expr linker errors
You can also see a somewhat similar compilation error on Rust Playground [here](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=b7143007ecb6190ca675d0112f83a99f).

### Code

I tried this code:

```rust
#![feature(associated_type_bounds, const_generics)]
#![allow(incomplete_features)]

trait Foo {
    type Output;

    fn foo() -> Self::Output;
}

impl Foo for [u8; 3] {
    type Output = [u8; 1 + 2];

    fn foo() -> [u8; 3] {
        [1u8; 3]
    }
}

fn bug<const N: usize>()
where [u8; N]: Foo<Output: AsRef<[u8]>> {
    <[u8; N]>::foo().as_ref();
}

fn main() {
    bug::<3>();
}
```

And I get this compilation error:
```
error: linking with `cc` failed: exit status: 1
  |
  = note: "cc" "-arch" "arm64" "-L" "/Users/myname/.rustup/toolchains/nightly-2021-03-28-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/lib" "/Users/myname/bugtest/target/debug/deps/bugtest.1l75jh480o98q933.rcgu.o" "/Users/myname/bugtest/target/debug/deps/bugtest.29be2t6ezmvhm7x2.rcgu.o" "/Users/myname/bugtest/target/debug/deps/bugtest.29of54finq6ox97.rcgu.o" "/Users/myname/bugtest/target/debug/deps/bugtest.2iaggdnd2g35tj31.rcgu.o" "/Users/myname/bugtest/target/debug/deps/bugtest.2wo69rum8xfzuiqs.rcgu.o" "/Users/myname/bugtest/target/debug/deps/bugtest.3cltyvso2dds2imp.rcgu.o" "/Users/myname/bugtest/target/debug/deps/bugtest.3e4w749tfnwu28u1.rcgu.o" "/Users/myname/bugtest/target/debug/deps/bugtest.40osd4py8cczi6yx.rcgu.o" "/Users/myname/bugtest/target/debug/deps/bugtest.4hmr4l0vej5j5cb5.rcgu.o" "/Users/myname/bugtest/target/debug/deps/bugtest.ckraeqngv8n20df.rcgu.o" "/Users/myname/bugtest/target/debug/deps/bugtest.d2f9yytss8rozrq.rcgu.o" "-o" "/Users/myname/bugtest/target/debug/deps/bugtest" "/Users/myname/bugtest/target/debug/deps/bugtest.1dy116sy1e7uommm.rcgu.o" "-Wl,-dead_strip" "-nodefaultlibs" "-L" "/Users/myname/bugtest/target/debug/deps" "-L" "/Users/myname/.rustup/toolchains/nightly-2021-03-28-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/lib" "/Users/myname/.rustup/toolchains/nightly-2021-03-28-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/lib/libstd-48f9d8def3882461.rlib" "/Users/myname/.rustup/toolchains/nightly-2021-03-28-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/lib/libpanic_unwind-6079d1139c997fe3.rlib" "/Users/myname/.rustup/toolchains/nightly-2021-03-28-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/lib/libobject-c2e7b03d6524647a.rlib" "/Users/myname/.rustup/toolchains/nightly-2021-03-28-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/lib/libaddr2line-6d367b36defa47f3.rlib" "/Users/myname/.rustup/toolchains/nightly-2021-03-28-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/lib/libgimli-2805d7b872f6e3af.rlib" "/Users/myname/.rustup/toolchains/nightly-2021-03-28-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/lib/librustc_demangle-2ecadf20a5fa947b.rlib" "/Users/myname/.rustup/toolchains/nightly-2021-03-28-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/lib/libhashbrown-a5a4c3d34eaf9770.rlib" "/Users/myname/.rustup/toolchains/nightly-2021-03-28-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/lib/librustc_std_workspace_alloc-27919dc680852c01.rlib" "/Users/myname/.rustup/toolchains/nightly-2021-03-28-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/lib/libunwind-8af13a9ae07830cf.rlib" "/Users/myname/.rustup/toolchains/nightly-2021-03-28-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/lib/libcfg_if-13e83b8b77a460a7.rlib" "/Users/myname/.rustup/toolchains/nightly-2021-03-28-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/lib/liblibc-517771ac81b6a136.rlib" "/Users/myname/.rustup/toolchains/nightly-2021-03-28-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/lib/liballoc-2d719eb433b05a5a.rlib" "/Users/myname/.rustup/toolchains/nightly-2021-03-28-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/lib/librustc_std_workspace_core-d3b246a19a31e168.rlib" "/Users/myname/.rustup/toolchains/nightly-2021-03-28-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/lib/libcore-91a60db5335b92da.rlib" "/Users/myname/.rustup/toolchains/nightly-2021-03-28-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/lib/libcompiler_builtins-f02722469d4c1a9c.rlib" "-lSystem" "-lresolv" "-lc" "-lm" "-liconv"
  = note: Undefined symbols for architecture arm64:
            "core::array::_$LT$impl$u20$core..convert..AsRef$LT$$u5b$T$u5d$$GT$$u20$for$u20$$u5b$T$u3b$$u20$N$u5d$$GT$::as_ref::hf637b91746c7c47d", referenced from:
                bugtest::bug::h9267a81d6c91b555 in bugtest.ckraeqngv8n20df.rcgu.o
          ld: symbol(s) not found for architecture arm64
          clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

### Version it worked on

It most recently worked on: rustc 1.53.0-nightly (5e65467ef 2021-03-26)

### Version with regression

`rustc --version --verbose`:
```
rustc 1.53.0-nightly (9b0edb7fd 2021-03-27)
binary: rustc
commit-hash: 9b0edb7fddacd6a60a380c1ce59159de597ab270
commit-date: 2021-03-27
host: aarch64-apple-darwin
release: 1.53.0-nightly
LLVM version: 12.0.0
```

@rustbot modify labels: +regression-from-stable-to-nightly -regression-untriaged

### LINKED ISSUE #86710: Link fails with hidden symbol isn't defined
This code [(playground)](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=3b264f273b6331f72d7cf3ef3d253457)

```rust
#![allow(incomplete_features)]
#![feature(const_evaluatable_checked)]
#![feature(const_generics)]

use std::marker::PhantomData;

fn main() {
    let x = FooImpl::<BarImpl<1>> {
        phantom: PhantomData,
    };
    let _ = x.foo::<BarImpl<1>>();
}

trait Foo<T>
where
    T: Bar,
{
    fn foo<U>(&self)
    where
        T: Operation<U>,
        <T as Operation<U>>::Output: Bar;
}

struct FooImpl<T>
where
    T: Bar,
{
    phantom: PhantomData<T>,
}

impl<T> Foo<T> for FooImpl<T>
where
    T: Bar,
{
    fn foo<U>(&self)
    where
        T: Operation<U>,
        <T as Operation<U>>::Output: Bar,
    {
        <<T as Operation<U>>::Output as Bar>::error_occurs_here();
    }
}

trait Bar {
    fn error_occurs_here();
}

struct BarImpl<const N: usize>;

impl<const N: usize> Bar for BarImpl<N> {
    fn error_occurs_here() {}
}

trait Operation<Rhs> {
    type Output;
}

//// Part-A: This causes error.
impl<const M: usize, const N: usize> Operation<BarImpl<M>> for BarImpl<N>
where
    BarImpl<{ N + M }>: Sized,
{
    type Output = BarImpl<{ N + M }>;
}

//// Part-B: This doesn't cause error.
// impl<const M: usize, const N: usize> Operation<BarImpl<M>> for BarImpl<N> {
//     type Output = BarImpl<M>;
// }

//// Part-C: This also doesn't cause error.
// impl<const M: usize, const N: usize> Operation<BarImpl<M>> for BarImpl<N> {
//     type Output = BarImpl<{ M }>;
// }
```

could not be compiled due to the following linker error:

```
error: linking with `cc` failed: exit status: 1
  |
  = note: "cc" "-m64" "/playground/target/debug/deps/playground-9e6e8e1c38e39d0a.playground.1o3xt69o-cgu.0.rcgu.o" "/playground/target/debug/deps/playground-9e6e8e1c38e39d0a.3tb83olt5p35wugo.rcgu.o" "-Wl,--as-needed" "-L" "/playground/target/debug/deps" "-L" "/playground/target/debug/build/libsqlite3-sys-d6ebd997e97c2f71/out" "-L" "/playground/target/debug/build/ring-0f34a5d678bd7990/out" "-L" "/playground/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-Wl,--start-group" "-Wl,-Bstatic" "/playground/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd-fe747fceaa31b38a.rlib" "/playground/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libpanic_unwind-5f5ff14665a8d5c5.rlib" "/playground/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libminiz_oxide-12d0fbc5e9627456.rlib" "/playground/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libadler-1e1b451846357b80.rlib" "/playground/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libobject-844126776fe6ca1c.rlib" "/playground/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libaddr2line-04e683b2eadd5848.rlib" "/playground/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libgimli-9bb1f4aeee9adc2d.rlib" "/playground/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd_detect-e7854498379a317c.rlib" "/playground/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_demangle-652931817310ff98.rlib" "/playground/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libhashbrown-15dd18e98e8fe12b.rlib" "/playground/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_std_workspace_alloc-227c54975f77a73b.rlib" "/playground/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libunwind-64e063177653d86f.rlib" "/playground/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcfg_if-bfd62449f4013547.rlib" "/playground/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/liblibc-1079ae9f5c548531.rlib" "/playground/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/liballoc-3bca990b4e08c950.rlib" "/playground/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_std_workspace_core-2588c44e3ecacf72.rlib" "/playground/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcore-c8ded1707ad10767.rlib" "-Wl,--end-group" "/playground/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcompiler_builtins-b4feacc7dd8903c2.rlib" "-Wl,-Bdynamic" "-lgcc_s" "-lutil" "-lrt" "-lpthread" "-lm" "-ldl" "-lc" "-Wl,--eh-frame-hdr" "-Wl,-znoexecstack" "-L" "/playground/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-o" "/playground/target/debug/deps/playground-9e6e8e1c38e39d0a" "-Wl,--gc-sections" "-pie" "-Wl,-zrelro" "-Wl,-znow" "-nodefaultlibs"
  = note: /usr/bin/ld: /playground/target/debug/deps/playground-9e6e8e1c38e39d0a.playground.1o3xt69o-cgu.0.rcgu.o: in function `<playground::FooImpl<T> as playground::Foo<T>>::foo':
          /playground/src/main.rs:40: undefined reference to `<playground::BarImpl<_> as playground::Bar>::error_occurs_here'
          /usr/bin/ld: /playground/target/debug/deps/playground-9e6e8e1c38e39d0a: hidden symbol `_ZN64_$LT$playground..BarImpl$LT$_$GT$$u20$as$u20$playground..Bar$GT$17error_occurs_here17h8ba8c706699797a1E' isn't defined
          /usr/bin/ld: final link failed: bad value
          collect2: error: ld returned 1 exit status
```

This error disappears by commenting out part A and uncommenting either part B or part C.

### Meta

`rustc --version --verbose`:

```
rustc 1.55.0-nightly (5a7834050 2021-06-23)
binary: rustc
commit-hash: 5a7834050f3a0ebcd117b4ddf0bc1e8459594309
commit-date: 2021-06-23
host: x86_64-unknown-linux-gnu
release: 1.55.0-nightly
LLVM version: 12.0.1
```

### LINKED ISSUE #100217: generic_const_exprs: associated type with const parameter set by associated const gives "undefined reference" linker errors
MVCE:

```rust
#![allow(incomplete_features)]
#![feature(generic_const_exprs)]

trait TraitOne {
    const MY_NUM:usize;
    type MyErr : std::fmt::Debug;

    fn do_one_stuff(arr: [u8; Self::MY_NUM]) -> Result<(), Self::MyErr>;
}

trait TraitTwo {
    fn do_two_stuff();
}

impl<O: TraitOne> TraitTwo for O
where [(); Self::MY_NUM]: {
    fn do_two_stuff() { O::do_one_stuff([5; Self::MY_NUM]).unwrap() }
}

struct Blargotron;

#[derive(Debug)]
struct ErrTy<const N:usize> ([(); N]);

impl TraitOne for Blargotron {
    const MY_NUM:usize = 3;
    type MyErr = ErrTy<{Self::MY_NUM}>;

    fn do_one_stuff(_arr: [u8; Self::MY_NUM]) -> Result<(), Self::MyErr> { Ok(()) }
}

fn main() {
    Blargotron::do_two_stuff();
}
```

(longer than I'd usually like an MVCE to be, but I couldn't find any more ways to shorten it)

<details><summary>Output with linker error:</summary>

```
$ cargo +nightly run
   Compiling rustbugrepro v0.1.0 (/home/shelvacu/rustbugrepro)
error: linking with `cc` failed: exit status: 1
  |
  = note: "cc" "-m64" "/tmp/rustcpdm3oV/symbols.o" "/home/shelvacu/rustbugrepro/target/debug/deps/rustbugrepro-b454c4cbfd8105b6.1ihqumwagrufjop0.rcgu.o" "/home/shelvacu/rustbugrepro/target/debug/deps/rustbugrepro-b454c4cbfd8105b6.1mup2xyy24n4gk36.rcgu.o" "/home/shelvacu/rustbugrepro/target/debug/deps/rustbugrepro-b454c4cbfd8105b6.23s252vpk659ujid.rcgu.o" "/home/shelvacu/rustbugrepro/target/debug/deps/rustbugrepro-b454c4cbfd8105b6.2stlozizc5uxjd7b.rcgu.o" "/home/shelvacu/rustbugrepro/target/debug/deps/rustbugrepro-b454c4cbfd8105b6.32r5fw7gu7hn650.rcgu.o" "/home/shelvacu/rustbugrepro/target/debug/deps/rustbugrepro-b454c4cbfd8105b6.3m9r4hpnytp8i5eg.rcgu.o" "/home/shelvacu/rustbugrepro/target/debug/deps/rustbugrepro-b454c4cbfd8105b6.3y6kclqhz0icogsf.rcgu.o" "/home/shelvacu/rustbugrepro/target/debug/deps/rustbugrepro-b454c4cbfd8105b6.4gqxo0wsc252b81i.rcgu.o" "/home/shelvacu/rustbugrepro/target/debug/deps/rustbugrepro-b454c4cbfd8105b6.5gj6i7t0wm9u39r7.rcgu.o" "/home/shelvacu/rustbugrepro/target/debug/deps/rustbugrepro-b454c4cbfd8105b6.8gtzyztqdis5wfk.rcgu.o" "/home/shelvacu/rustbugrepro/target/debug/deps/rustbugrepro-b454c4cbfd8105b6.b2wiaz2930r642i.rcgu.o" "/home/shelvacu/rustbugrepro/target/debug/deps/rustbugrepro-b454c4cbfd8105b6.h4vu5fvuiuflzws.rcgu.o" "/home/shelvacu/rustbugrepro/target/debug/deps/rustbugrepro-b454c4cbfd8105b6.20c23rlj3dtxnb5h.rcgu.o" "-Wl,--as-needed" "-L" "/home/shelvacu/rustbugrepro/target/debug/deps" "-L" "/home/shelvacu/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-Wl,--start-group" "-Wl,-Bstatic" "/home/shelvacu/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd-9a60c77fcb3cb120.rlib" "/home/shelvacu/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libpanic_unwind-5b44c7aad80856ae.rlib" "/home/shelvacu/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libobject-ff65b550b4dcd2ac.rlib" "/home/shelvacu/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libmemchr-7f1169f253822fce.rlib" "/home/shelvacu/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libaddr2line-a981dbda6aeca1f9.rlib" "/home/shelvacu/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libgimli-fc1281d9e6392569.rlib" "/home/shelvacu/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_demangle-1fbfdea3abefe497.rlib" "/home/shelvacu/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd_detect-9c50e59a7c82c7d4.rlib" "/home/shelvacu/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libhashbrown-49ab78c1bdf400c6.rlib" "/home/shelvacu/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libminiz_oxide-640f18ffcf376a48.rlib" "/home/shelvacu/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libadler-8448e4d3e976ee3c.rlib" "/home/shelvacu/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_std_workspace_alloc-cb13682f9c2a7246.rlib" "/home/shelvacu/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libunwind-cfa8f6cd7fbf314f.rlib" "/home/shelvacu/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcfg_if-0f3268324638da83.rlib" "/home/shelvacu/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/liblibc-9dba3f083c9eb142.rlib" "/home/shelvacu/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/liballoc-aaaa00ed48be7dc8.rlib" "/home/shelvacu/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_std_workspace_core-522518611024dce5.rlib" "/home/shelvacu/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcore-05898138a596088a.rlib" "-Wl,--end-group" "/home/shelvacu/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcompiler_builtins-6088bc0426d36242.rlib" "-Wl,-Bdynamic" "-lgcc_s" "-lutil" "-lrt" "-lpthread" "-lm" "-ldl" "-lc" "-Wl,--eh-frame-hdr" "-Wl,-znoexecstack" "-L" "/home/shelvacu/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-o" "/home/shelvacu/rustbugrepro/target/debug/deps/rustbugrepro-b454c4cbfd8105b6" "-Wl,--gc-sections" "-pie" "-Wl,-zrelro,-znow" "-nodefaultlibs"
  = note: /usr/lib/gcc/x86_64-pc-linux-gnu/11.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: /home/shelvacu/rustbugrepro/target/debug/deps/rustbugrepro-b454c4cbfd8105b6.b2wiaz2930r642i.rcgu.o: in function `<O as rustbugrepro::TraitTwo>::do_two_stuff':
          /home/shelvacu/rustbugrepro/src/main.rs:17: undefined reference to `core::result::Result<T,E>::unwrap'
          /usr/lib/gcc/x86_64-pc-linux-gnu/11.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: /home/shelvacu/rustbugrepro/target/debug/deps/rustbugrepro-b454c4cbfd8105b6: hidden symbol `_ZN4core6result19Result$LT$T$C$E$GT$6unwrap17h3f789d9c8ef9bb3fE' isn't defined
          /usr/lib/gcc/x86_64-pc-linux-gnu/11.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: final link failed: bad value
          collect2: error: ld returned 1 exit status
          
  = help: some `extern` functions couldn't be found; some native libraries may need to be installed or have their path specified
  = note: use the `-l` flag to specify native libraries to link
  = note: use the `cargo:rustc-link-lib` directive to specify the native libraries to link with Cargo (see https://doc.rust-lang.org/cargo/reference/build-scripts.html#cargorustc-link-libkindname)

error: could not compile `rustbugrepro` due to previous error
```
</details>

Rustc version:
```text
$ rustc +nightly -vV
rustc 1.65.0-nightly (2befdefdd 2022-08-06)
binary: rustc
commit-hash: 2befdefdda0f2bc5ff93f7f95633c98841409098
commit-date: 2022-08-06
host: x86_64-unknown-linux-gnu
release: 1.65.0-nightly
LLVM version: 14.0.6
```

Also looked at other issues, one of these may be a dupe but none match the structure of the MVCE or the same linker error:
* #83972 - also tried with `RUSTC_FLAGS="-Zsymbol-mangling-version=v0"`, no difference
* #84669
* #86710
* #82268
* #73298

### PR DESCRIPTION
**Pull request by compiler-errors**
#100312 was the wrong approach, I think this is the right one.

When normalizing a type, if we see that it's a projection, we currently defer to `tcx.normalize_projection_ty`, which normalizes the projections away but doesn't touch the unevaluated constants. So now we just continue to fold the type if it has unevaluated constants so we make sure to evaluate those too, if we can. 

Fixes #100217
Fixes #83972
Fixes #84669
Fixes #86710
Fixes #82268
Fixes #73298

### CODE REVIEW

File: compiler/rustc_trait_selection/src/traits/query/normalize.rs [hunk 1]
```diff
@@ -317,6 +317,13 @@ impl<'cx, 'tcx> FallibleTypeFolder<'tcx> for QueryNormalizer<'cx, 'tcx> {
 
             _ => ty.try_super_fold_with(self),
         })()?;
+
+        // `tcx.normalize_projection_ty` may normalize to a type that still has
+        // unevaluated consts, so keep normalizing here if that's the case.
+        if res != ty && res.has_type_flags(ty::TypeFlags::HAS_CT_PROJECTION) {
+            res = res.try_super_fold_with(self)?;
```
Comment (lcnr) [inline compiler/rustc_trait_selection/src/traits/query/normalize.rs:324]: can you instead move this into the `ty::Projection` branches

I think that's where this should happen conceptually.

after that r=me, gj on figuring this out :+1:
