### PR TITLE
diagnostics: account for glob shadowing when linting redundant imports

### LINKED ISSUE #92904: rustc incorrectly suggests removing imports that shadow shadowing glob imports
Given the following code: https://godbolt.org/z/vdc4YYafK

```rust
pub struct Foo(bar::Bar);

pub mod bar {
  pub struct Foo(pub Bar);
  pub struct Bar(pub char);
}

pub fn warning() -> Foo {
  use bar::*;
  use self::Foo;
  Foo(Bar('a'))
}

pub fn error() -> Foo {
  use bar::*;
  // use self::Foo;
  Foo(Bar('a'))
}
```

The current output is:

```
warning: the item `Foo` is imported redundantly
  --> <source>:10:7
   |
1  | pub struct Foo(bar::Bar);
   | ------------------------- the item `Foo` is already defined here
...
10 |   use self::Foo;
   |       ^^^^^^^^^
   |
   = note: `#[warn(unused_imports)]` on by default

error[E0308]: mismatched types
  --> <source>:17:3
   |
14 | pub fn error() -> Foo {
   |                   --- expected `Foo` because of return type
...
17 |   Foo(Bar('a'))
   |   ^^^^^^^^^^^^^ expected struct `Foo`, found struct `bar::Foo`

error: aborting due to previous error; 1 warning emitted

For more information about this error, try `rustc --explain E0308`.
```

The warning for redundant import is incorrect, and is required for code to compile: `bar::*` shadows the implicit `self::Foo` in this scope, so making it explicit shadows the implicit `bar::*`. This should either be an error or not a warning; the latter is probably correct.

The non-glob version is handled correctly: https://godbolt.org/z/653K6svve

### PR DESCRIPTION
**Pull request by notriddle**
Fixes #92904

### CODE REVIEW

**Comment by lcnr** [comment]
r? compiler

File: compiler/rustc_resolve/src/imports.rs [hunk 1]
```diff
@@ -1168,8 +1168,15 @@ impl<'a, 'tcx> Resolver<'a, 'tcx> {
                     target_bindings[ns].get(),
                 ) {
                     Ok(other_binding) => {
+                        let key = this.new_key(target, ns);
                         is_redundant[ns] = Some(
-                            binding.res() == other_binding.res() && !other_binding.is_ambiguity(),
+                            binding.res() == other_binding.res()
```
Comment (petrochenkov) [inline compiler/rustc_resolve/src/imports.rs:1173]: Why does this condition hold for #92904 if the `Foo`s imported by ` use bar::*` and `use self::Foo` are clearly different?

Comment (petrochenkov) [reply compiler/rustc_resolve/src/imports.rs:1173]: This lint is *supposed* to report single imports that can be removed because a glob imports the same thing.
The `!other_binding.is_ambiguity()` condition makes sure that single imports are not removed in situations where they are used for disambiguation.

#92904, however, is not about disambiguation, so there's some other bug responsible for reporting the wrong warning here (maybe in accumulation over 3 namespaces or something).

File: compiler/rustc_resolve/src/ident.rs [hunk 2]
```diff
@@ -952,6 +954,14 @@ impl<'a, 'tcx> Resolver<'a, 'tcx> {
             if !self.is_accessible_from(import_vis, parent_scope.module) {
                 continue;
             }
+            if let Some(ignored) = ignore_binding &&
+                let NameBindingKind::Import { import, .. } = ignored.kind &&
+                ptr::eq(import, &**single_import) {
+                // Ignore not just the binding itself, but if it has a shadowed_glob,
+                // ignore that, too, because this loop is supposed to only process
+                // named imports.
```
Comment (petrochenkov) [inline compiler/rustc_resolve/src/ident.rs:962]: Ah, yes, that's probably the culprit, if we have an ignored binding then we should ignore the `single_import` associated with it as well.

Comment (petrochenkov) [reply compiler/rustc_resolve/src/ident.rs:962]: The whole setup can also be simplified by filtering away the ignored binding right away - https://github.com/petrochenkov/rust/commit/b19701dd29bd7b0b2ab024f2b7abefbf054e9b95?w=1
