### PR TITLE
[r+] coherence: Allow impls of builtin traits just on structs/enums

### LINKED ISSUE #21080: 3-tuple gets inferred to internal test runner types with --test if certain type is marked Send
```rust
// wtf-testrunner.rs

#![allow(unstable)]

pub fn join<J: ToJoin<T>, T: Send /* WTF */>(_: J) -> Future<T> {
    unimplemented!()
}
pub trait ToJoin<T> {}

impl<A1, T1, A2, T2> ToJoin<(T1, T2)> for (A1, A2) {}

impl<A1, T1, A2, T2, A3, T3> ToJoin<(T1, T2, T3)> for (A1, A2, A3) {}
impl<A1, T1, A2, T2, A3, T3, A4, T4> ToJoin<(T1, T2, T3, T4)> for (A1, A2, A3, A4) {}

pub struct Future<T>;

pub fn all_ok() {
    let f1 = Future::<i32>;
    let f2 = Future::<i32>;

    let _: Future<(i32, i32)> = join((f1, f2));
}
pub fn also_ok() {
    let f1 = Future::<i32>;
    let f2 = Future::<i32>;
    let f3 = Future::<i32>;
    let f4 = Future::<i32>;

    let _: Future<(i32, i32, i32, i32)> = join((f1, f2, f3, f4));
}

pub fn wtf() {
    let f1 = Future::<i32>;
    let f2 = Future::<i32>;
    let f3 = Future::<i32>;

    let _: Future<(i32, i32, i32)> = join((f1, f2, f3));
}

fn main() {}
```

Compiling with `rustc wtf-testrunner.rs` works fine, `rustc --test wtf-testrunner.rs` definitely does not, though:

```rust
wtf-testrunner.rs:35:38: 35:56 error: mismatched types: expected `Future<(i32, i32, i32)>`, found `Future<(test::TestDesc, test::TestResult, collections::vec::Vec<u8>)>` (expected i32, found struct test::TestDesc)
wtf-testrunner.rs:35     let _: Future<(i32, i32, i32)> = join((f1, f2, f3));
                                                          ^~~~~~~~~~~~~~~~~~
error: aborting due to previous error
```

And, if the `Send` bound in `join` is removed, the code compiles fine with or without `--test`.

So... somehow the test runner is causing a tuple of arity 3 specifically to be inferred to something completely ridiculous.

### PR DESCRIPTION
**Pull request by flaper87**
Fixes #21080 

r? @nikomatsakis 

[breaking-change]

### CODE REVIEW

File: src/librustc_typeck/coherence/impls.rs [hunk 1]
```diff
@@ -0,0 +1,51 @@
...
+            ast::ItemImpl(_, _, _, Some(ref opt_trait), _, _) => {
+                let trait_ref = ty::node_id_to_trait_ref(self.tcx, opt_trait.ref_id);
+                if let Some(_) = self.tcx.lang_items.to_builtin_kind(trait_ref.def_id) {
+                    match trait_ref.self_ty().sty {
+                        ty::ty_struct(..) | ty::ty_enum(..) => {}
+                        _ => {
+                            self.tcx.sess.span_err(
+                                item.span,
+                                &format!("builtin traits can only be \
+                                          implemented on `structs` or `enums`")[]);
```
Comment (nikomatsakis) [inline src/librustc_typeck/coherence/impls.rs]: I think we can remove the "`" quotes here

File: src/test/compile-fail/coherence-impls-builtin.rs [hunk 2]
```diff
@@ -0,0 +1,28 @@
...
+enum TestE {
+  A
+}
+
+struct MyType;
+
+unsafe impl Send for TestE {}
+unsafe impl Send for MyType {}
+unsafe impl Send for (MyType, MyType) {}
+//~^ ERROR builtin traits can only be implemented on `structs` or `enums`
```
Comment (nikomatsakis) [inline src/test/compile-fail/coherence-impls-builtin.rs]: Let's add a few more impls for good measure. For example `&MyType`, `[MyType]`, and `&[MyType]`.
