### PR TITLE
Stop parsing "-" as integer, fixes #22745

### LINKED ISSUE #22745: Parsing "-" as integer incorrectly gives Ok(0)
Assertion in the following code is accepted, which breaks the behaviour I was relying on.

```rust
fn main() {
	assert_eq!("-".parse(), Ok(0));	
}
```

This bug has been present already on 2014-11-21.

It's one-line fix, I'll try making a PR.

### PR DESCRIPTION
**Pull request by krdln**
Makes Rust less amusing by fixing [#22745](https://github.com/rust-lang/rust/issues/22745)

### CODE REVIEW

File: src/libcoretest/num/mod.rs [hunk 1]
```diff
@@ -122,4 +122,9 @@ mod test {
         assert_eq!("-9223372036854775808".parse::<i64>().ok(), Some(i64_val));
         assert_eq!("-9223372036854775809".parse::<i64>().ok(), None);
     }
+
+    #[test]
+    test_int_from_minus_sign() {
```
Comment (lifthrasiir) [inline src/libcoretest/num/mod.rs]: Missing `fn`?

Comment (krdln) [inline src/libcoretest/num/mod.rs]: Sorry, forgot to push after testing.
