### PR TITLE
rustdoc: restructure type search engine to pick-and-use IDs

### LINKED ISSUE #110029: rustdoc search: invalid "in parameters" results for "streaming"
Steps to reproduce:

1. Search for "streaming" in the hyper docs: https://docs.rs/hyper/0.14.25/hyper/index.html?search=streaming (built with 2023-03-09 nightly rustdoc).

Expected results:

Either a struct with Streaming in the name appears, or no results.

Actual results:

Search page automatically shows the "In parameters" tab, and it contains results for several functions that don't mention "streaming" in their parameters.

image

### PR DESCRIPTION
**Pull request by notriddle**
Fixes #110029

Preview: https://notriddle.com/rustdoc-demo-html-3/search-corrections/std/index.html?search=-%3E%20streaming

image

This change makes it so, instead of mixing string distance with type unification, function signature search works by mapping names to IDs at the start, reporting to the user any cases where it had to make corrections, and then matches with IDs when going through the items.

This only changes function searches. Name searches are left alone, and corrections are only done when there's a single item in the search query.

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
Instead of just writing `Showing result for "x"`, I think it'd be a good idea to add context, like `No function with arguments "String", showing results for the closest instead: "x"` (or something along the line).

Also, when are making this correction? In case no item is named `streaming` or in case there is no `streaming` item in any function arguments?

**Comment by GuillaumeGomez** [comment]
@notriddle I think you forgot to update your demo since the sentence doesn't match what I see in the diff.

**Review by GuillaumeGomez — APPROVED** [review]

File: src/librustdoc/html/static/js/search.js [hunk 1]
```diff
@@ -1191,162 +1208,82 @@ function initSearch(rawSearchIndex) {
...
-                // In this case, we were expecting generics but there isn't so we simply reject this
-                // one.
-                return maxEditDistance + 1;
+                return true;
+            }
+
+            // If the current item does not match, try [unboxing] the generic.
+            // [unboxing]:
+            //   https://ndmitchell.com/downloads/slides-hoogle_fast_type_searching-09_aug_2008.pdf
+            if (checkIfInGenerics(row, elem)) {
```
Comment (GuillaumeGomez) [inline src/librustdoc/html/static/js/search.js:1230]: I think you can simply return `checkIfGenerics` in here instead of keep this condition.

File: src/librustdoc/html/static/js/search.js [hunk 2]
```diff
@@ -1671,6 +1591,50 @@ function initSearch(rawSearchIndex) {
...
+                        parsedQuery.correction = matchName;
+                    }
+                    elem.id = match;
+                }
+                for (const elem2 of elem.generics) {
+                    convertNameToId(elem2);
+                }
+            }
+
+            for (const elem of parsedQuery.elems) {
```
Comment (GuillaumeGomez) [inline src/librustdoc/html/static/js/search.js:1631]: I thought we only ran this in case there is one element? That seems a bit weird to apply this on multiple elements no?

File: src/librustdoc/html/static/js/search.js [hunk 3]
```diff
@@ -1671,6 +1591,50 @@ function initSearch(rawSearchIndex) {
...
+             * "In Params", "In Returns", and "In Function Signature" tabs.
+             *
+             * If there is no matching item, but a close-enough match, this
+             * function also that correction.
+             *
+             * See `buildTypeMapIndex` for more information.
+             *
+             * @param {QueryElement} elem
+             */
+            function convertNameToId(elem) {
```
Comment (GuillaumeGomez) [inline src/librustdoc/html/static/js/search.js:1606]: So I understand correctly, if multiple items give the same distance, we pick the first one we encountered right? I'm not sure if it's a good idea either. Not against it, just not sure.

Comment (GuillaumeGomez) [reply src/librustdoc/html/static/js/search.js:1602]: That's already a nice improvement. :+1: 

The problem here in my opinion is that it'll still "not make sense" for users. I think just rewording the sentence could help with it? So currently we have:

```
Type "streaming" not found. Showing results for "string" instead.
```

What do you think instead of:

```
Type "streaming" not found. Showing results for closest type name "string" instead.
```

?

**Comment by GuillaumeGomez** [comment]
Thanks for applying the changes! I think the current version is good so approving it.

**Comment by jsha** [comment]
Concept and UI looks great! Thanks for working on this.
