### PR TITLE
rustc_codegen_llvm: replace the first argument early in FnType::new_vtable.

### LINKED ISSUE #51907: ICE when using an object-safe trait with methods marked as extern
This [snippet](https://play.rust-lang.org/?gist=2f2277e3297b73230b2c07337c9d4477&version=nightly&mode=debug) causes rustc to ICE:

```Rust
trait Foo {
    extern fn method(&self);
}

struct Bar;
impl Foo for Bar { 
    extern fn method(&self) { }
}

fn main() {
    let foo: Box<dyn Foo> = Box::new(Bar);
    foo.method();
}
```
rustc version: rustc 1.28.0-nightly (2a1c4eec4 2018-06-25)

Error message: 
```
error: internal compiler error: librustc_codegen_llvm/abi.rs:304: FnType::new_vtable: non-pair self ArgType { layout: TyLayout { ty: &Foo, details: LayoutDetails { variants: Single { index: 0 }, fields: Arbitrary { offsets: [Size { raw: 0 }, Size { raw: 8 }], memory_index: [0, 1] }, abi: ScalarPair(Scalar { value: Pointer, valid_range: 1..=18446744073709551615 }, Scalar { value: Pointer, valid_range: 1..=18446744073709551615 }), align: Align { abi_pow2: 3, pref_pow2: 3 }, size: Size { raw: 16 } } }, pad: None, mode: Direct(ArgAttributes { regular: (empty), pointee_size: Size { raw: 0 }, pointee_align: None }) }
```

### PR DESCRIPTION
**Pull request by eddyb**
Fixes #51907 by removing the vtable pointer before the `ArgType` is even created.
This allows any ABI to support trait object method calls, regardless of how it passes `*dyn Trait`.

r? @nikomatsakis

### CODE REVIEW

File: src/librustc_codegen_llvm/abi.rs [hunk 1]
```diff
@@ -285,40 +288,40 @@ impl<'a, 'tcx> FnTypeExt<'a, 'tcx> for FnType<'tcx, Ty<'tcx>> {
...
+            // Instead, pass just the (thin pointer) first field of `*dyn Trait`.
+            if arg_idx == Some(0) {
+                // FIXME(eddyb) `layout.field(cx, 0)` is not enough because e.g.
+                // `Box<dyn Trait>` has a few newtype wrappers around the raw
+                // pointer, so we'd have to "dig down" to find `*dyn Trait`.
+                let pointee = layout.ty.builtin_deref(true)
+                    .unwrap_or_else(|| {
+                        bug!("FnType::new_vtable: non-pointer self {:?}", layout)
+                    }).ty;
+                let fat_ptr_ty = cx.tcx.mk_mut_ptr(pointee);
```
Comment (nagisa) [inline src/librustc_codegen_llvm/abi.rs]: This variable name is confusing, given that this is not a type of a fat pointer, but rather its data pointer only.

Comment (nagisa) [reply src/librustc_codegen_llvm/abi.rs]: Oh, never mind, I think I got it wrong myself lol.

**Comment by pnkfelix** [comment]
compiler team discussed. Since #51907 is a stable-to-stable regression, we decided we are better off letting the fix wait another ~6 weeks rather than put this into the beta, especially so close to when the beta is going to be cut for the next stable release.
