### PR TITLE
[10/n] Split constants and functions' arguments into disjoint bodies.

### LINKED ISSUE #24414: Improve "no type for local variable" error when in check_const_with_ty
The control flow for `rustc_typeck::check::check_const_with_ty` can end up spitting out an error of the form:

```
non-constant-expr-for-fixed-len-vec.rs:15:25: 15:26 error: no type for local variable 10
non-constant-expr-for-fixed-len-vec.rs:15         let _x: [isize; n];
```

With the compiler as it stands today, this is usually coupled with an error of the form:

``` rust
error: array length constant evaluation error: non-constant path in constant expr
```

but other changes being made may lead to _only_ the "no type for local variable" message being emitted.

We can do better here, e.g. by passing along knowledge that we are looking at a const-expr and then reporting that local variables simply are invalid within const-exprs.

### PR DESCRIPTION
**Pull request by eddyb**
_This is part of a series ([prev](https://github.com/rust-lang/rust/pull/38053) | [next](https://github.com/rust-lang/rust/pull/38813)) of patches designed to rework rustc into an out-of-order on-demand pipeline model for both better feature support (e.g. [MIR-based](https://github.com/solson/miri) early constant evaluation) and incremental execution of compiler passes (e.g. type-checking), with beneficial consequences to IDE support as well.
If any motivation is unclear, please ask for additional PR description clarifications or code comments._

<hr>

Finishes the signature-body split started in #37918, namely:
* `trait` items are separated just like `impl` items were, for uniformity, closing #37712
* `static`s, `const`s (including associated ones), `enum` discriminants and array lengths get bodies
  * even the count in "repeat expressions", i.e. `n` in `[x; n]`, which fixes #24414
* arguments' patterns are moved to the bodies, with the types staying in `FnDecl`
  * `&self` now desugars to `self: &Self` instead of `self: &_` (similarly for other `self` forms)
  * `astconv`'s and metadata's (for rustdoc) informative uses are explicitly ignored for the purposes of the dep graph. this could be fixed in the future by hashing the exact information being extracted about the arguments as opposed to generating a dependency on *the whole body*

### CODE REVIEW

**Comment by michaelwoerister** [comment]
> astconv's and metadata's (for rustdoc) informative uses are explicitly ignored for the purposes of the dep graph.

That sounds a bit troubling.

**Comment by eddyb** [comment]
@michaelwoerister AFAIK `astconv`'s use, which is only in case of error, couldn't be observed. But that one is fixable if need be, by representing the elision information in terms of the `BodyId`, not the data extracted from it.

The rustdoc use is more problematic. I'm not sure there is a scenario in which it could go wrong, but long-term we should *really* move away from the current cross-crate docs model which is becoming unsustainable. I'm leaning towards the save-analysis solution, more so for rustdoc than IDEs even.

**Comment by michaelwoerister** [comment]
Are you sure that compilation really aborts in case `find_implied_output_region()` returns `Err`? If it does, it should not make a difference anyway because we don't save the dep-graph in that case.

**Comment by eddyb** [comment]
@michaelwoerister The information (argument names) is only used in case of (elision) error, later on (and printed verbatim, not used in any decision).

**Comment by michaelwoerister** [comment]
I still think this is problematic. What you say, might be true for now, but lots of people are modifying this code without global understanding. Can this be refactored to just access that information in case an actual occurs? (Alternatively, for cases like this, we could have some opaque `ErrorReportingInfo` type that implements `Display` and makes it explicit this must only be used for error reporting). 

Regarding metadata: Isn't this kind of a premature optimization? Metadata is full of overconservative edges anyway. I think it would better to review this together with the rest when the time comes. Or does it break existing tests?

**Comment by eddyb** [comment]
@michaelwoerister Alright I'll try to see what I can do to `astconv`. As for the metadata thing, it breaks all the tests that modify the body, making the body separation sort of pointless metadata-wise.
I would prefer to somehow hash the actual data being encoded (the argument names), as it has a much much smaller footprint and it would cause less of a hassle overall (@nikomatsakis said he wanted this too).

**Comment by michaelwoerister** [comment]
> Alright I'll try to see what I can do to astconv.

Cool `:)` Thanks!

> I would prefer to somehow hash the actual data being encoded (the argument names), as it has a much much smaller footprint and it would cause less of a hassle overall.

I would prefer that too. I suspect we'll move away from monolithic `Entry`s in metadata and put independent things into separate tables. Or have individual `DepNodes` for `Entry` fields. In this case, where the data is just a list of plain strings, it would be easy to just hash that. However, it would require that we start refactoring metadata dep-tracking already, which is a bit much for this PR.

As long as this is just used in rustdoc, we should be fine. How about just adding an assertion to `CrateMetadata::get_fn_arg_names()` that incremental compilation is turned off?

**Comment by eddyb** [comment]
> How about just adding an assertion to `CrateMetadata::get_fn_arg_names()` that incremental compilation is turned off?

Oh that is brilliant, thanks for the idea! I assume it would replace the usual `read(Metadata(def_id))`?

**Comment by michaelwoerister** [comment]
> Oh that is brilliant, thanks for the idea! I assume it would replace the usual read(Metadata(def_id))?

Sounds reasonable.

File: src/librustc_borrowck/borrowck/mod.rs [hunk 1]
```diff
@@ -68,7 +68,7 @@ impl<'a, 'tcx> Visitor<'tcx> for BorrowckCtxt<'a, 'tcx> {
     }
 
     fn visit_fn(&mut self, fk: FnKind<'tcx>, fd: &'tcx hir::FnDecl,
-                b: hir::ExprId, s: Span, id: ast::NodeId) {
+                b: hir::BodyId, s: Span, id: ast::NodeId) {
```
Comment (nikomatsakis) [inline src/librustc_borrowck/borrowck/mod.rs]: so I can't find a way to make an error out of this (yet), but it seems like we are failing to borrowck embedded bodies -- e.g., in an expression like `[22; X]`, we don't borrowck the expression X, right? The main reason I can't make an error here is that the set of constant expressions we accept in that context is pretty limited, but it seems like it wouldn't necessarily stay that way...

I did run across this, which seems like a bug, but a pre-existing one (this code [compiles on nightly today](https://is.gd/5SDSWz)...but it shouldn't...):

```rust
#![feature(const_fn)]

struct Foo(usize);

const fn get(x: Foo) -> usize {
    x.0
}

const X: Foo = Foo(22);
static Y: usize = get(*&X);

fn main() {
}
```

File: src/librustc_metadata/encoder.rs [hunk 2]
```diff
@@ -839,7 +839,9 @@ impl<'a, 'tcx> EncodeContext<'a, 'tcx> {
                 _ => None,
             },
             mir: match item.node {
-                hir::ItemStatic(..) |
+                hir::ItemStatic(..) if self.tcx.sess.opts.debugging_opts.always_encode_mir => {
```
Comment (nikomatsakis) [inline src/librustc_metadata/encoder.rs]: was this just a pre-existing bug?

File: src/test/compile-fail/associated-const-type-parameter-arrays.rs [hunk 3]
```diff
@@ -26,7 +26,9 @@ impl Foo for Def {
 
 pub fn test<A: Foo, B: Foo>() {
     let _array: [u32; <A as Foo>::Y];
-    //~^ ERROR the trait bound `A: Foo` is not satisfied
+    //~^ ERROR cannot use an outer type parameter in this context [E0402]
```
Comment (nikomatsakis) [inline src/test/compile-fail/associated-const-type-parameter-arrays.rs]: Is there a backwards compatibility concern here?  Probably not, since this sort of doesn't work now -- but I feel like it *should* work someday, so it seems odd to be considering `A` as an "outer" type parameter.

File: src/test/incremental/hashes/consts.rs [hunk 4]
```diff
@@ -66,8 +66,10 @@ const CONST_CHANGE_TYPE_2: Option<u64> = None;
 const CONST_CHANGE_VALUE_1: i16 = 1;
 
 #[cfg(not(cfail1))]
-#[rustc_dirty(label="Hir", cfg="cfail2")]
+#[rustc_clean(label="Hir", cfg="cfail2")]
```
Comment (nikomatsakis) [inline src/test/incremental/hashes/consts.rs]: 👍

File: src/test/incremental/hashes/trait_defs.rs [hunk 5]
```diff
@@ -303,7 +303,7 @@ trait TraitChangeModeSelfOwnToMut: Sized {
 #[cfg(not(cfail1))]
 #[rustc_clean(label="Hir", cfg="cfail2")]
 #[rustc_clean(label="Hir", cfg="cfail3")]
-#[rustc_metadata_dirty(cfg="cfail2")]
+#[rustc_metadata_clean(cfg="cfail2")]
```
Comment (nikomatsakis) [inline src/test/incremental/hashes/trait_defs.rs]: Can we make an ICH test targeting exactly this change? Seems easily do-able. In particular, if you have something like `fn foo(x: u32) { }` and you change it to `fn foo(y: u32) { }`, the hash of the trait should not change (just the body). Right?

That said, if you don't provide a default, based on my read of the code above, then the fn names would still be included in the hash... which doesn't seem exactly *right*. We could I guess just ignore them manually in the hasher code.

**Review by nikomatsakis — COMMENTED** [review]
Waiting on the commit to come. Looks good; we chatted about some of my comments on IRC. The thing about omitting the repeat expressions etc from borrowck is my biggest concern, though I'm not sure the best way to test it right now. Still seems like we should do it right.

File: src/librustc/hir/map/def_collector.rs [hunk 6]
```diff
@@ -10,22 +10,15 @@
...
-use middle::cstore::InlinedItem;
+use hir::def_id::{CRATE_DEF_INDEX, DefIndex};
 
 use syntax::ast::*;
 use syntax::ext::hygiene::Mark;
 use syntax::visit;
 use syntax::symbol::{Symbol, keywords};
 
-/// Creates def ids for nodes in the HIR.
+/// Creates def ids for nodes in the AST.
```
Comment (eddyb) [inline src/librustc/hir/map/def_collector.rs]: Yeah, since it never touches the HIR anymore.

File: src/librustc_borrowck/borrowck/mod.rs (hunk 1 above)
Comment (eddyb) [inline src/librustc_borrowck/borrowck/mod.rs]: Why shouldn't it? That's equivalent to `({*&Foo(22)}).0` which is perfectly fine AFAIK.
The problem would be if `X` where `static` (and only until we get miri).

File: src/librustc_metadata/encoder.rs (hunk 2 above)
Comment (eddyb) [inline src/librustc_metadata/encoder.rs]: Indeed it was, there were a few things in the PR introducing this that are less than ideal. They skipped review because they weren't in the original PR state but rather in "fixes for tests".

File: src/test/compile-fail/associated-const-type-parameter-arrays.rs (hunk 3 above)
Comment (eddyb) [inline src/test/compile-fail/associated-const-type-parameter-arrays.rs]: Yeah, I didn't really make anything worse, just better encoded the existing semantics.
We'll be able to clean this up in the future, when everything is body-based.

File: src/test/incremental/hashes/trait_defs.rs (hunk 5 above)
Comment (eddyb) [inline src/test/incremental/hashes/trait_defs.rs]: I think @nikomatsakis meant the `fn` *argument* names.

Comment (michaelwoerister) [inline src/test/incremental/hashes/trait_defs.rs]: Oh, that makes sense then.

File: src/librustc_borrowck/borrowck/mod.rs (hunk 1 above)
Comment (nikomatsakis) [inline src/librustc_borrowck/borrowck/mod.rs]: It should not because `Foo` is not `Copy`, and we are moving it from a `&Foo` -- e.g., this does not compile: https://is.gd/zU2BVo

Comment (nikomatsakis) [inline src/librustc_borrowck/borrowck/mod.rs]: Filed https://github.com/rust-lang/rust/issues/38520

**Comment by nikomatsakis** [comment]
This all looks good to me I think except that I'd still like to run borrowck expressions like the `N` in `[T; N]` etc. It annoys me that I cannot find a way to write a test for this though, because constant expressions are too restrictive. Still it seems like we should try to get it right. =)

**Comment by alexcrichton** [comment]
@bors: retry

* https://github.com/rust-lang/rust/pull/38619 (hopefully)
