### PR TITLE
Use constant for 180/π in to_degrees

### LINKED ISSUE #29944: to_degrees/to_radians aren't rounded correctly
``` rust
#![feature(float_extras)]

fn main() {
    let exact = 57.2957795130823208767981548141051703324054724665643215491602438612028471483215526324409689958511109441862233816328648932;

    assert_eq!(1_f32.to_degrees(), exact);
}
```

```
thread '<main>' panicked at 'assertion failed: `(left == right)` (left: `57.295776`, right: `57.29578`)', <anon>:6
playpen: application terminated with error code 101
```

That computed answer is just one bit wrong.

The above case would be addressed by having the 180/pi value used in the conversion being a correctly rounded constant, rather than computed as `180.0 / consts::PI`, although I'm not sure this will get the right answer in all cases. If we decide to care about this, then we'll need an exact multiplication algorithm such as [Brisebarre and Muller (2008) _Correctly rounded multiplication by arbitrary precision constants_](http://perso.ens-lyon.fr/jean-michel.muller/MultFmacArith.pdf). Let `C` be the exact (i.e. infinite precision) value of 180 / pi, then:

``` rust
// C as f32
const C_H: f32 = 57.295780181884765625;
// (C - C_H) as f32
const C_L: f32 = -6.6880244276035227812826633453369140625e-7;

fn exact_mul(x: f32) -> f32 {
    let a = C_L * x;
    let b = C_H.mul_add(x, a);
    b
}

fn main() {
    let exact = 57.2957795130823208767981548141051703324054724665643215491602438612028471483215526324409689958511109441862233816328648932;
    assert_eq!(exact_mul(1.0), exact);
}
```

(There's some conditions on the constant `C` for this to work for all `x`, and I don't know/haven't yet checked if 180/pi satisfies them.)

This will is noticably slower than the naive method, especially if there's not hardware support for FMA (`mul_add`), however, if we do implement this, people who don't care about accuracy can use the naive method trivially. That said, `to_degrees` is almost always used for output for humans, and is often rounded to many fewer decimal places than full precision, so loss of precision doesn't matter... but also, speed probably doesn't matter so much (the formatting will almost certainly be much slower than the multiplication). On the other hand, `to_radians` won't be used for human output, typically.

``` rust
#![feature(test, float_extras)]
extern crate test;

// C as f32
const C_H: f32 = 57.295780181884765625;
// (C - C_H) as f32
const C_L: f32 = -6.6880244276035227812826633453369140625e-7;

fn exact_mul(x: f32) -> f32 {
    let a = C_L * x;
    let b = C_H.mul_add(x, a);
    b
}

const FLOATS: &'static [f32] = &[-360.0, -359.99, -100.0, -1.001, 0.001, -1e-40,
                                 0.0,
                                 1e-40, 0.001, 1.001, 100.0, 359.99, 360.0];

#[bench]
fn exact(b: &mut test::Bencher) {
    b.iter(|| {
        for x in test::black_box(FLOATS) {
            test::black_box(exact_mul(*x));
        }
    })
}

#[bench]
fn inexact(b: &mut test::Bencher) {
    b.iter(|| {
        for x in test::black_box(FLOATS) {
            test::black_box(x.to_degrees());
        }
    })
}

#[bench]
fn format(b: &mut test::Bencher) {
    b.iter(|| {
        let mut buf = [0u8; 100];
        for x in test::black_box(FLOATS) {
            use std::io::prelude::*;
            let _ = write!(&mut buf as &mut [_], "{:.0}", x);
            test::black_box(&buf);
        }
    })
}
```

```
test exact   ... bench:         169 ns/iter (+/- 6)
test format  ... bench:       1,238 ns/iter (+/- 41)
test inexact ... bench:          84 ns/iter (+/- 3)
```

(It's likely that `to_radians` suffers similarly, since pi / 180 is just as transcendental as 180 / pi, but I haven't found an example with a few tests.)

---

This issue is somewhat of a policy issue: how much do we care about getting correctly rounded floating point answers? This case is pretty simple, but we almost certainly _don't_ want to guarantee 100% precise answers for functions like `sin`/`exp` etc., since this is non-trivial/slow to do, and IEEE754 (and typical libm's) don't guarantee exact rounding for all inputs.

### PR DESCRIPTION
**Pull request by varkor**
The current `f32|f64.to_degrees` implementation uses a division to calculate `180/π`, which causes a loss of precision. Using a constant is still not perfect (implementing a maximally-precise algorithm would come with a high performance cost), but improves precision with a minimal change.

As per the discussion in #29944, this fixes #29944 (the costs of improving the precision further would not outweigh the gains).

### CODE REVIEW

**Comment by shepmaster** [comment]
r? @rkruppe 

you seemed in favor of this.

File: src/libcore/num/f32.rs [hunk 1]
```diff
@@ -239,7 +239,9 @@ impl Float for f32 {
     /// Converts to degrees, assuming the number is in radians.
     #[inline]
     fn to_degrees(self) -> f32 {
-        self * (180.0f32 / consts::PI)
+        // Use a constant for better precision.
+        let pis_in_180 = 57.2957795130823208767981548141051703_f32;
```
Comment (shepmaster) [inline src/libcore/num/f32.rs]: Why not an actual `const`?

File: src/libcore/num/f64.rs [hunk 2]
```diff
@@ -237,7 +237,9 @@ impl Float for f64 {
     /// Converts to degrees, assuming the number is in radians.
     #[inline]
     fn to_degrees(self) -> f64 {
-        self * (180.0f64 / consts::PI)
+        // Use a constant for better precision.
+        let pis_in_180 = 57.2957795130823208767981548141051703_f64;
```
Comment (shepmaster) [inline src/libcore/num/f64.rs]: Shouldn't there be more digits here than in `f32`?

**Comment by rkruppe** [comment]
Curiously, f64::to_degrees already passes the test without this change and `180.0 / f64::consts::PI` is exactly equal to the `exact` value given in #29944 -- which is of course double rounded (since it's a transcendental reduced to a finite decimal string and then converted to a short binary float). I wonder whether that double rounding is significant and we just need a different test case to exhibit the problem, or whether it means we don't need this change for f64::to_degrees at all.

File: src/libcore/num/f64.rs (hunk 2 above)
Comment (varkor) [reply src/libcore/num/f64.rs]: Both literals actually have more digits than necessary: they both have 36 significant figures, which was chosen to be consistent with the existing definitions of mathematical constants (for both `f32` and `f64`).

File: src/libcore/num/f32.rs (hunk 1 above)
Comment (varkor) [reply src/libcore/num/f32.rs]: Yeah, that makes more sense stylistically.

**Comment by varkor** [comment]
I think in this case, double rounding should not be an issue, because the precision to which the number is rounded in decimal form is significantly higher than the floating-point precision. I imagine the change isn't actually necessary for `f64`, but probably makes sense for consistency.

**Comment by rkruppe** [comment]
Double rounding can be an issue regardless of what intermediate precision you round to. Suppose the full binary expansion of a number looks like this:

```
...0100000100...
    ^  ^
    A  B
```

If we first round (half-to-even) to position `B` and then to position `A`, the result ends in `01`. If we round to `A` directly without double rounding, we round up and the result ends in `10`. This can happen regardless of how far apart A and B are, what's important is that there digits A...B are zeros, which of course becomes less likely as the distance increases.

**Comment by varkor** [comment]
If we truncate/round to `B` and then try flipping the bit, if there's no difference in the value when rounded to `A` (before and after flipping the bit), then we can determine the first rounding caused no loss of precision relative to rounding to `A`, because regardless of the bits following `B`, the result would still be the same. Am I right in thinking this? This would suggest that the approximation in the value of the `f32`/`f64` constants are as close to the correct value of `180/π` as possible, even taking it being transcendental into consideration.

**Comment by rkruppe** [comment]
I'm not quite sure if I understand correctly, but if you produce anything other than `...0100000000...`, you're not rounding to bit B. So whatever you're describing, if it arrives at the correctly rounded result (`...1000000000...`), then it's not *double rounding*, i.e., it's not properly rounding to some precision and then afterwards rounding again to some smaller precision.

But this is a theroetical discussion. The actual interesting part is whether the f64 produced from the decimal literal in this code is the correct rounding of the actual value of 180/pi. I'm rather busy now so I don't know when I'll have the time to verify that.
@nagisa, @est31: does one of you have the tools and time to verify?

**Comment by varkor** [comment]
I guess my real question is that, this code compiles:
```rust
fn main() {
    let pis_in_180_below = 57.29577951308232087679815_f64;
    let pis_in_180_above = 57.29577951308232087679816_f64;
    // pis_in_180_below < pis_in_180 < pis_in_180_above (in terms of their literals)
    assert_eq!(pis_in_180_below, pis_in_180_above);
}
```
so assuming the floating-point literal parser is well-behaved, then any literal value (including a hypothetically-infinite sequence) between these two values is equal to the constant in this code. This assumes that the parser always produces the closest floating-point number to the literal provided (which seems like a reasonable assumption, given that Rust even allows literals with more precision than `f64` recognises). But if that's true, then this constant is correct.

**Comment by nagisa** [comment]
In both previous and new code, the division is evaluated during the construction of LLVM-IR and obtains following representations (the hexidecimal form used is whatever the IEEE standard specifies):

* f32 division = 0x404CA5DC00000000
* f32 constant = 0x404CA5DC20000000
* f64 division = 0x404CA5DC1A63C1F8
* f64 constant = 0x404CA5DC1A63C1F8

So at least for f64, the result is equivalent.

**Comment by rkruppe** [comment]
@nagisa Thanks! But I believe that just confirms what was observed earlier in this thread? The tricky question is whether you'd also get `double 0x404CA5DC1A63C1F8` if you took the transcendental real numner 180/PI and rounded it to f64 precision directly.

@varkor's last comment, however, settles the question with less effort than what I had in mind. I'm convinced now the dedicated constant is both correct and unnecessary for f64.

File: src/libcore/num/f64.rs [hunk 3]
```diff
@@ -237,7 +237,9 @@ impl Float for f64 {
     /// Converts to degrees, assuming the number is in radians.
     #[inline]
     fn to_degrees(self) -> f64 {
-        self * (180.0f64 / consts::PI)
+        // Use a constant for better precision.
+        const PIS_IN_180: f64 = 57.2957795130823208767981548141051703_f64;
```
Comment (rkruppe) [inline src/libcore/num/f64.rs]: You mentioned consistency as reason to have the constant here as well but I'd rather not have an opaque magic number duplicated for no functional reason. I think it's better to leave the code in place and add a comment saying that `180.0f64 / consts::PI` is correctly rounded.

**Review by hanna-kruppe — CHANGES_REQUESTED** [review]

File: src/libcore/num/f64.rs (hunk 3 above)
Comment (rkruppe) [reply src/libcore/num/f64.rs]: ... and probably call out that this differs from f32::to_degrees.

Comment (varkor) [reply src/libcore/num/f64.rs]: Okay, sure :+1:

**Comment by rkruppe** [comment]
Great, thanks! r=me after squashing

**Comment by ranma42** [comment]
Would it make sense to compute the f64 constant and convert it to f32 in the f32 impl?
This would avoid having a magic number in the code.

**Comment by rkruppe** [comment]
@ranma42 It's possible that this doesn't give the right result (because it's double rounding differently than the ways examined in previously in this discussion, which turned out to be fine) and it doesn't seem easier to verify that it gives the right result than to verify that the constant is correct.
