### PR TITLE
handle ConstKind::Unresolved after monomorphizing

### LINKED ISSUE #70125: [const_generics]: encountered bad ConstKind in codegen
### Code

```rust
#![feature(const_generics)]

const L: usize = 3;

fn main() {
    let p = Printer {};
    p.print(&[1, 2, 3]);
}

trait Print<const LEN: usize> {
    fn print(&self, _data: &[u8; LEN]) {
        for _ in 0..LEN {}
    }
}

struct Printer {}
impl Print<L> for Printer {}
```

### Meta

`rustc --version --verbose`:
```
rustc 1.44.0-nightly (f509b26a7 2020-03-18)
binary: rustc
commit-hash: f509b26a7730d721ef87423a72b3fdf8724b4afa
commit-date: 2020-03-18
host: x86_64-unknown-linux-gnu
release: 1.44.0-nightly
LLVM version: 9.0
```

### Error output

```
error: internal compiler error: src/librustc_codegen_ssa/mir/constant.rs:65: encountered bad ConstKind in codegen: Const { ty: usize, val: Unevaluated(DefId(0:11 ~ ice[1944]::{{impl}}[0]::{{constant}}[0]), [], None) }
  --> src/main.rs:12:21
   |
12 |         for _ in 0..LEN {}
   |                     ^^^

thread 'rustc' panicked at 'Box<Any>', src/librustc_codegen_llvm/lib.rs:1:1
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.44.0-nightly (f509b26a7 2020-03-18) running on x86_64-unknown-linux-gnu

note: compiler flags: -C debuginfo=2 -C incremental --crate-type bin

note: some of the compiler flags provided by cargo are hidden

error: aborting due to previous error

error: could not compile `ice`.
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
error: internal compiler error: src/librustc_codegen_ssa/mir/constant.rs:65: encountered bad ConstKind in codegen: Const { ty: usize, val: Unevaluated(DefId(0:11 ~ ice[1944]::{{impl}}[0
]::{{constant}}[0]), [], None) }
  --> src/main.rs:12:21
   |
12 |         for _ in 0..LEN {}
   |                     ^^^

thread 'rustc' panicked at 'Box<Any>', src/librustc_codegen_llvm/lib.rs:1:1
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.44/src/backtrace/libunwind.rs:86
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.44/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:78
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1069
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1427
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:198
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:218
  10: rustc_driver::report_ice
  11: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:515
  12: std::panicking::begin_panic
  13: rustc_errors::HandlerInner::span_bug
  14: rustc_errors::Handler::span_bug
  15: rustc::util::bug::opt_span_bug_fmt::{{closure}}
  16: rustc::ty::context::tls::with_opt::{{closure}}
  17: rustc::ty::context::tls::with_opt
  18: rustc::util::bug::opt_span_bug_fmt
  19: rustc::util::bug::span_bug_fmt
  20: rustc_codegen_ssa::mir::constant::<impl rustc_codegen_ssa::mir::FunctionCx<Bx>>::eval_mir_constant
  21: rustc_codegen_ssa::mir::operand::<impl rustc_codegen_ssa::mir::FunctionCx<Bx>>::codegen_operand
  22: rustc_codegen_ssa::mir::rvalue::<impl rustc_codegen_ssa::mir::FunctionCx<Bx>>::codegen_rvalue
  23: rustc_codegen_ssa::mir::block::<impl rustc_codegen_ssa::mir::FunctionCx<Bx>>::codegen_block
  24: rustc_codegen_ssa::base::codegen_instance
  25: <rustc::mir::mono::MonoItem as rustc_codegen_ssa::mono_item::MonoItemExt>::define
  26: rustc_codegen_llvm::base::compile_codegen_unit::module_codegen
  27: rustc::dep_graph::graph::DepGraph::with_task
  28: rustc_codegen_llvm::base::compile_codegen_unit
  29: rustc_codegen_ssa::base::codegen_crate
  30: <rustc_codegen_llvm::LlvmCodegenBackend as rustc_codegen_utils::codegen_backend::CodegenBackend>::codegen_crate
  31: rustc_session::utils::<impl rustc_session::session::Session>::time
  32: rustc_interface::passes::start_codegen
  33: rustc::ty::context::tls::enter_global
  34: rustc_interface::queries::Queries::ongoing_codegen
  35: rustc_interface::interface::run_compiler_in_existing_thread_pool
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.44.0-nightly (f509b26a7 2020-03-18) running on x86_64-unknown-linux-gnu

note: compiler flags: -C debuginfo=2 -C incremental --crate-type bin

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
error: aborting due to previous error

error: could not compile `ice`.
```

</p>
</details>

This issue has been assigned to @lcnr via [this comment](https://github.com/rust-lang/rust/issues/70125#issuecomment-602041732).

### PR DESCRIPTION
**Pull request by lcnr**
fixes #70125 

r? @bjorn3

### CODE REVIEW

**Comment by Centril** [comment]
cc @eddyb @varkor

File: src/librustc_codegen_ssa/mir/constant.rs [hunk 1]
```diff
@@ -40,29 +40,37 @@ impl<'a, 'tcx, Bx: BuilderMethods<'a, 'tcx>> FunctionCx<'a, 'tcx, Bx> {
...
-            }
-            ty::ConstKind::Value(value) => Ok(value),
-            _ => {
-                let const_ = self.monomorphize(&constant.literal);
-                if let ty::ConstKind::Value(value) = const_.val {
-                    Ok(value)
-                } else {
-                    span_bug!(constant.span, "encountered bad ConstKind in codegen: {:?}", const_);
+        // repeatedly monomorphize generic parameters until we either
+        // reach a value or an error.
```
Comment (eddyb) [inline src/librustc_codegen_ssa/mir/constant.rs]: This is in the wrong direction. You should *never* monomorphize more than once.
If the result isn't monomorphic, *something went very wrong*.

File: src/librustc_codegen_ssa/mir/constant.rs [hunk 2]
```diff
@@ -40,29 +40,37 @@ impl<'a, 'tcx, Bx: BuilderMethods<'a, 'tcx>> FunctionCx<'a, 'tcx, Bx> {
...
-                                .tcx()
-                                .sess
-                                .span_err(constant.span, "erroneous constant encountered");
-                        }
-                        err
-                    })
-            }
-            ty::ConstKind::Value(value) => Ok(value),
-            _ => {
-                let const_ = self.monomorphize(&constant.literal);
```
Comment (eddyb) [inline src/librustc_codegen_ssa/mir/constant.rs]: What you could try is first always `monomorphize`-ing, and *then* checking for `Unevaluated` (you'd need to remove `let substs = self.monomorphize(&substs);`).

It's not the right fix here (see https://github.com/rust-lang/rust/issues/70125#issuecomment-602133708), but it could be useful for handling the erroring constant case.

File: src/librustc_codegen_ssa/mir/constant.rs (hunk 1 above)
Comment (eddyb) [reply src/librustc_codegen_ssa/mir/constant.rs]: @davidtwco and I recently spent some time tracking down multiple monomorphizations, as they broke down their "polymorphization" work (right now nothing happens if you apply the same substitutions more than once in codegen, because the substitutions themselves are monomorphic, but that doesn't make it *correct*, and it certainly breaks down with polymorphization).

File: src/librustc_codegen_ssa/mir/constant.rs (hunk 2 above)
Comment (lcnr) [reply src/librustc_codegen_ssa/mir/constant.rs]: ok, this already seems to fix all tests :thinking: Will still look into your comment on #70125

File: src/librustc_codegen_ssa/mir/constant.rs [hunk 3]
```diff
@@ -40,31 +40,36 @@ impl<'a, 'tcx, Bx: BuilderMethods<'a, 'tcx>> FunctionCx<'a, 'tcx, Bx> {
...
-                                .span_err(constant.span, "erroneous constant encountered");
-                        }
-                        err
-                    })
+                ty::ConstKind::Unevaluated(def_id, substs, promoted)
             }
+            ty::ConstKind::Value(value) => ty::ConstKind::Value(value),
+            ty::ConstKind::Param(_) => self.monomorphize(&constant.literal).val,
+            _ => span_bug!(constant.span, "encountered bad Const in codegen: {:?}", constant),
+        };
```
Comment (eddyb) [inline src/librustc_codegen_ssa/mir/constant.rs]: My suggestion was to have `let const_ = self.monomorphize(&constant.literal);` instead of this `match`, btw, no need to check cases.

File: src/test/ui/const-generics/normalization_failure.rs [hunk 4]
```diff
@@ -0,0 +1,16 @@
+// run-pass
```
Comment (eddyb) [inline src/test/ui/const-generics/normalization_failure.rs]: Can you name this test `issue-70125-2.rs`? It's just a reduced version of the original testcase.

File: src/librustc_codegen_ssa/mir/constant.rs [hunk 5]
```diff
@@ -40,31 +40,26 @@ impl<'a, 'tcx, Bx: BuilderMethods<'a, 'tcx>> FunctionCx<'a, 'tcx, Bx> {
...
+                .const_eval_resolve(ty::ParamEnv::reveal_all(), def_id, substs, promoted, None)
+                .map_err(|err| {
+                    if promoted.is_none() {
+                        self.cx
+                            .tcx()
+                            .sess
+                            .span_err(constant.span, "erroneous constant encountered");
+                    }
+                    err
+                }),
```
Comment (eddyb) [inline src/librustc_codegen_ssa/mir/constant.rs]: @oli-obk @wesleywiser @varkor @yodaldevoid NB: this `Unevaluated` handling should, after https://github.com/rust-lang/rust/issues/70125#issuecomment-602133708 is fixed, only handle the *error* case, whereas success should result in `monomorphize` itself doing the evaluation.

What do you think about merging this PR before that root cause is fixed?

Comment (varkor) [reply src/librustc_codegen_ssa/mir/constant.rs]: I'm happy to merge this interim fix if it addresses one of the existing ICEs :+1:.
