### PR TITLE
fallback to lstat when stat fails on Windows

### LINKED ISSUE #109106: `std::fs` incorrect behavior when dealing with UNIX domain socket on Windows
I tried this code:

```rust
use std::path::Path;
use std::env::args_os;

fn main() {
    let p = args_os().skip(1).next().expect("to have a path argument");
    let p: &Path = p.as_ref();

    dbg!(p.display());
    dbg!(p.exists());
    dbg!(p.metadata());
    dbg!(p.symlink_metadata());
    dbg!(p.is_file());
    dbg!(p.is_dir());
    dbg!(p.is_symlink());
}
```

I expected to see this happen: 

The API should report the given path exists.

Instead, this happened:

When passed a path to a UNIX domain socket on Windows, I get:

```
[src\main.rs:22] p.display() = "<REDACTED>\\socket"
[src\main.rs:23] p.exists() = false
[src\main.rs:24] p.metadata() = Err(
    Os {
        code: 1920,
        kind: Uncategorized,
        message: "The file cannot be accessed by the system.",
    },
)
[src\main.rs:25] p.symlink_metadata() = Ok(
    Metadata {
        file_type: FileType(
            FileType {
                attributes: 1056,
                reparse_tag: 2147483683,
            },
        ),
        is_dir: false,
        is_file: true,
        permissions: Permissions(
            FilePermissions {
                attrs: 1056,
            },
        ),
        modified: Ok(
            SystemTime {
                intervals: 133232173107398736,
            },
        ),
        accessed: Ok(
            SystemTime {
                intervals: 133232173107398736,
            },
        ),
        created: Ok(
            SystemTime {
                intervals: 133172157242066860,
            },
        ),
        ..
    },
)
[src\main.rs:26] p.is_file() = false
[src\main.rs:27] p.is_dir() = false
[src\main.rs:28] p.is_symlink() = false
```

### Meta

`rustc --version --verbose`:
```
rustc --version --verbose
rustc 1.68.0 (2c8cc3432 2023-03-06)
binary: rustc
commit-hash: 2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74
commit-date: 2023-03-06
host: x86_64-pc-windows-msvc
release: 1.68.0
LLVM version: 15.0.6
```

----

## Analysis

I think this is simply an unintended consequence of supporting symlinks on Windows. It is interesting that `symlink_metadata` seems to be producing a correct result here (IMO this metadata should be returned by `metadata()`).

The differences between `stat` (`metadata`) and `lstat` (`symlink_metadata`) is the `ReparsePoint` flag.

https://github.com/rust-lang/rust/blob/8d4adad953edef2ef94b02e2bb1ed9b22bb1d975/library/std/src/sys/windows/fs.rs#L1152-L1158

On Windows, UNIX domain sockets are implemented as reparse points just like symlink. However Rust is only setting the `FILE_FLAG_OPEN_REPARSE_POINT` flag when we are testing for symlink. Without this flag `CreateFileW` is going to return the access error above.

I think the issue is that, the standard library didn't consider that the possibility to have other type of files that are reparse points but not symlinks. 

I'm not sure what is the best fix for this, but this is kinda surprising.

### PR DESCRIPTION
**Pull request by chaitanyav**
Fixes #109106 
@ChrisDenton please let me know if this is the expected behavior for stat on windows

### CODE REVIEW

File: library/std/src/sys/windows/fs.rs [hunk 1]
```diff
@@ -1236,7 +1236,20 @@ pub fn link(_original: &Path, _link: &Path) -> io::Result<()> {
 }
 
 pub fn stat(path: &Path) -> io::Result<FileAttr> {
-    metadata(path, ReparsePoint::Follow)
+    match metadata(path, ReparsePoint::Follow) {
+        Err(err) => {
+            if e.raw_os_error() == Some(c::ERROR_CANNOT_ACCESS_FILE as u32) {
+                return lstat(path);
```
Comment (ChrisDenton) [inline library/std/src/sys/windows/fs.rs:1242]: So this `lstat` result should be tested to see if it's a symlink.

File: library/std/src/sys/windows/fs.rs [hunk 2]
```diff
@@ -1236,7 +1236,20 @@ pub fn link(_original: &Path, _link: &Path) -> io::Result<()> {
...
+            }
+            Err(err)
+        }
+        Ok(attrs) => {
+            if attrs.file_type.is_symlink() {
+                return lstat(path);
+            }
+            Ok(attrs)
+        }
```
Comment (ChrisDenton) [inline library/std/src/sys/windows/fs.rs:1251]: And this part should just always return `Ok(attrs)`

**Review by ChrisDenton — COMMENTED** [review]
Almost! But if the `metadata` call returns `Ok` then we always want to return that. We only want to test if `lstat` returned a symlink or not.

File: library/std/src/sys/windows/fs.rs [hunk 3]
```diff
@@ -1236,7 +1236,19 @@ pub fn link(_original: &Path, _link: &Path) -> io::Result<()> {
 }
 
 pub fn stat(path: &Path) -> io::Result<FileAttr> {
-    metadata(path, ReparsePoint::Follow)
+    match metadata(path, ReparsePoint::Follow) {
+        Err(err) => {
+            if err.raw_os_error() == Some(c::ERROR_CANT_ACCESS_FILE as i32) {
```
Comment (ChrisDenton) [inline library/std/src/sys/windows/fs.rs:1241]: You could move the `Err(err)` and first `if` on to the same line to reduce rightward drift a bit.
```rust
Err(err) if err.raw_os_error() == Some(c::ERROR_CANT_ACCESS_FILE as i32) => {
```

File: library/std/src/sys/windows/fs.rs [hunk 4]
```diff
@@ -1236,7 +1236,19 @@ pub fn link(_original: &Path, _link: &Path) -> io::Result<()> {
...
+                if let Ok(attrs) = lstat(path) {
+                    if !attrs.file_type().is_symlink() {
+                        return Ok(attrs);
+                    }
+                }
+            }
+            Err(err)
+        }
+        Ok(attrs) => Ok(attrs),
```
Comment (ChrisDenton) [inline library/std/src/sys/windows/fs.rs:1250]: Which would mean this would need to become something like `result => result,`

**Review by ChrisDenton — COMMENTED** [review]
Looks good to me! I just have one small style suggestion but otherwise this looks ready to be merged.

**Comment by ChrisDenton** [comment]
Thanks for fixing this! If all goes well with the full suite of CI tests, this should be released in Rust 1.70.

@bors r+ rollup
