### PR TITLE
Avoid ICE when the generic_span is empty

### LINKED ISSUE #107998: ICE: -Wsingle-use-lifetimes: `Span must not be empty and have no suggestion` with debug assertions
### Code

```Rust
fn with<R>(f: &fn<'a>(x: &'a int) -> R) -> R {
    f(&3)
}

fn return_it<'a>() -> &'a int {
    with(|o| o)
}

fn main() {
    let x = return_it();
}
```

### Meta

`rustc --version --verbose`:
```
5b8f284536d00ba649ca968584bedab4820d8527
```

### Error output
Needs a rustc built with debug assertions, `rustc -Wsingle-use-lifetimes <file>`
```
error: function pointer types may not have generic parameters
 --> ee6ed3b0d76f631f872a8993a91541f02a62d1af.rs:1:18
  |
1 | fn with<R>(f: &fn<'a>(x: &'a int) -> R) -> R {
  |                  ^^^^
  |
help: consider moving the lifetime parameter to a `for` parameter list
  |
1 - fn with<R>(f: &fn<'a>(x: &'a int) -> R) -> R {
1 + fn with<R>(f: &for<'a> fn(x: &'a int) -> R) -> R {
  |

error[E0412]: cannot find type `int` in this scope
 --> ee6ed3b0d76f631f872a8993a91541f02a62d1af.rs:1:30
  |
1 | fn with<R>(f: &fn<'a>(x: &'a int) -> R) -> R {
  |                              ^^^
  |                              |
  |                              not found in this scope
  |                              help: perhaps you intended to use this type: `i32`

error[E0412]: cannot find type `int` in this scope
 --> ee6ed3b0d76f631f872a8993a91541f02a62d1af.rs:5:27
  |
5 | fn return_it<'a>() -> &'a int {
  |                           ^^^
  |                           |
  |                           not found in this scope
  |                           help: perhaps you intended to use this type: `i32`
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
thread 'rustc' panicked at 'assertion failed: `(left == right)`
  left: `Some(SubstitutionPart { span: ee6ed3b0d76f631f872a8993a91541f02a62d1af.rs:1:16: 1:16 (#0), snippet: "" })`,
 right: `None`: Span must not be empty and have no suggestion', /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_errors/src/diagnostic.rs:627:9
stack backtrace:
   0:     0x7f7c45b6e141 - std::backtrace_rs::backtrace::libunwind::trace::h57c700f2e7064cc9
                               at /home/matthias/vcs/github/rust_debug_assertions/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x7f7c45b6e141 - std::backtrace_rs::backtrace::trace_unsynchronized::h3bd6f8115b3aef84
                               at /home/matthias/vcs/github/rust_debug_assertions/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7f7c45b6e141 - std::sys_common::backtrace::_print_fmt::h4e3cd4a1386ea18b
                               at /home/matthias/vcs/github/rust_debug_assertions/library/std/src/sys_common/backtrace.rs:65:5
   3:     0x7f7c45b6e141 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::ha4399f941a901f68
                               at /home/matthias/vcs/github/rust_debug_assertions/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x7f7c45be4b08 - core::fmt::write::h3693e9c93ce31d95
                               at /home/matthias/vcs/github/rust_debug_assertions/library/core/src/fmt/mod.rs:1232:17
   5:     0x7f7c45b3920f - std::io::Write::write_fmt::h7cd08f6496a9e03d
                               at /home/matthias/vcs/github/rust_debug_assertions/library/std/src/io/mod.rs:1684:15
   6:     0x7f7c45b6df35 - std::sys_common::backtrace::_print::h1ea264f371a6489b
                               at /home/matthias/vcs/github/rust_debug_assertions/library/std/src/sys_common/backtrace.rs:47:5
   7:     0x7f7c45b6df35 - std::sys_common::backtrace::print::h43e663fef4567fcf
                               at /home/matthias/vcs/github/rust_debug_assertions/library/std/src/sys_common/backtrace.rs:34:9
   8:     0x7f7c45b320be - std::panicking::default_hook::{{closure}}::h94496c5e3b8314dc
   9:     0x7f7c45b320be - std::panicking::default_hook::h62ce584520972394
                               at /home/matthias/vcs/github/rust_debug_assertions/library/std/src/panicking.rs:286:9
  10:     0x7f7c486d7102 - <alloc[88ef48cbf1494855]::boxed::Box<dyn for<'a, 'b> core[3a7799eb5b53fe42]::ops::function::Fn<(&'a core[3a7799eb5b53fe42]::panic::panic_info::PanicInfo<'b>,), Output = ()> + core[3a7799eb5b53fe42]::marker::Sync + core[3a7799eb5b53fe42]::marker::Send> as core[3a7799eb5b53fe42]::ops::function::Fn<(&core[3a7799eb5b53fe42]::panic::panic_info::PanicInfo,)>>::call
                               at /home/matthias/vcs/github/rust_debug_assertions/library/alloc/src/boxed.rs:2002:9
  11:     0x7f7c486d7102 - rustc_driver_impl[ebb6d565ed784687]::DEFAULT_HOOK::{closure#0}::{closure#0}
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_driver_impl/src/lib.rs:1163:17
  12:     0x7f7c45b32b8b - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h20060c80854d9f26
                               at /home/matthias/vcs/github/rust_debug_assertions/library/alloc/src/boxed.rs:2002:9
  13:     0x7f7c45b32b8b - std::panicking::rust_panic_with_hook::hf3310e5853e10814
                               at /home/matthias/vcs/github/rust_debug_assertions/library/std/src/panicking.rs:692:13
  14:     0x7f7c45b6f629 - std::panicking::begin_panic_handler::{{closure}}::hb76bc4aa6a51e144
                               at /home/matthias/vcs/github/rust_debug_assertions/library/std/src/panicking.rs:579:13
  15:     0x7f7c45b6e25e - std::sys_common::backtrace::__rust_end_short_backtrace::h76df651326f0b61a
                               at /home/matthias/vcs/github/rust_debug_assertions/library/std/src/sys_common/backtrace.rs:137:18
  16:     0x7f7c45b326a2 - rust_begin_unwind
                               at /home/matthias/vcs/github/rust_debug_assertions/library/std/src/panicking.rs:575:5
  17:     0x7f7c45bebb33 - core::panicking::panic_fmt::ha9472d71642ed08e
                               at /home/matthias/vcs/github/rust_debug_assertions/library/core/src/panicking.rs:64:14
  18:     0x7f7c45bec113 - core::panicking::assert_failed_inner::h08d1d4ab99760b32
  19:     0x7f7c4925a679 - core[3a7799eb5b53fe42]::panicking::assert_failed::<core[3a7799eb5b53fe42]::option::Option<&rustc_errors[7deb60bbfdd1de15]::SubstitutionPart>, core[3a7799eb5b53fe42]::option::Option<&rustc_errors[7deb60bbfdd1de15]::SubstitutionPart>>
                               at /home/matthias/vcs/github/rust_debug_assertions/library/core/src/panicking.rs:211:5
  20:     0x7f7c4926df0e - <rustc_errors[7deb60bbfdd1de15]::diagnostic::Diagnostic>::multipart_suggestion_with_style::<&str>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_errors/src/diagnostic.rs:627:9
  21:     0x7f7c4926458f - <rustc_errors[7deb60bbfdd1de15]::diagnostic::Diagnostic>::multipart_suggestion::<&str>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_errors/src/diagnostic.rs:588:9
  22:     0x7f7c4926458f - <rustc_errors[7deb60bbfdd1de15]::diagnostic_builder::DiagnosticBuilder<()>>::multipart_suggestion::<&str>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_errors/src/diagnostic_builder.rs:481:13
  23:     0x7f7c4926458f - <rustc_lint[f3e4522c2a4d1eb3]::context::EarlyContext as rustc_lint[f3e4522c2a4d1eb3]::context::LintContext>::lookup_with_diagnostics::<rustc_error_messages[87ef96e77df7413c]::MultiSpan, rustc_error_messages[87ef96e77df7413c]::DiagnosticMessage, <rustc_lint[f3e4522c2a4d1eb3]::early::EarlyContextAndPass<rustc_lint[f3e4522c2a4d1eb3]::BuiltinCombinedEarlyLintPass>>::inlined_check_id::{closure#0}>::{closure#0}
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_lint/src/context.rs:840:25
  24:     0x7f7c4926458f - <<rustc_lint[f3e4522c2a4d1eb3]::context::EarlyContext as rustc_lint[f3e4522c2a4d1eb3]::context::LintContext>::lookup_with_diagnostics<rustc_error_messages[87ef96e77df7413c]::MultiSpan, rustc_error_messages[87ef96e77df7413c]::DiagnosticMessage, <rustc_lint[f3e4522c2a4d1eb3]::early::EarlyContextAndPass<rustc_lint[f3e4522c2a4d1eb3]::BuiltinCombinedEarlyLintPass>>::inlined_check_id::{closure#0}>::{closure#0} as core[3a7799eb5b53fe42]::ops::function::FnOnce<(&mut rustc_errors[7deb60bbfdd1de15]::diagnostic_builder::DiagnosticBuilder<()>,)>>::call_once::{shim:vtable#0}
                               at /home/matthias/vcs/github/rust_debug_assertions/library/core/src/ops/function.rs:250:5
  25:     0x7f7c4925cf88 - <alloc[88ef48cbf1494855]::boxed::Box<dyn for<'a, 'b> core[3a7799eb5b53fe42]::ops::function::FnOnce<(&'a mut rustc_errors[7deb60bbfdd1de15]::diagnostic_builder::DiagnosticBuilder<'b, ()>,), Output = &'a mut rustc_errors[7deb60bbfdd1de15]::diagnostic_builder::DiagnosticBuilder<'b, ()>>> as core[3a7799eb5b53fe42]::ops::function::FnOnce<(&mut rustc_errors[7deb60bbfdd1de15]::diagnostic_builder::DiagnosticBuilder<()>,)>>::call_once
                               at /home/matthias/vcs/github/rust_debug_assertions/library/alloc/src/boxed.rs:1988:9
  26:     0x7f7c4925cf88 - rustc_middle[ebb8a7eed001d673]::lint::struct_lint_level::struct_lint_level_impl::<rustc_error_messages[87ef96e77df7413c]::DiagnosticMessage>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_middle/src/lint.rs:457:9
  27:     0x7f7c4925aa84 - rustc_middle[ebb8a7eed001d673]::lint::struct_lint_level::<rustc_error_messages[87ef96e77df7413c]::DiagnosticMessage, <rustc_lint[f3e4522c2a4d1eb3]::context::EarlyContext as rustc_lint[f3e4522c2a4d1eb3]::context::LintContext>::lookup_with_diagnostics<rustc_error_messages[87ef96e77df7413c]::MultiSpan, rustc_error_messages[87ef96e77df7413c]::DiagnosticMessage, <rustc_lint[f3e4522c2a4d1eb3]::early::EarlyContextAndPass<rustc_lint[f3e4522c2a4d1eb3]::BuiltinCombinedEarlyLintPass>>::inlined_check_id::{closure#0}>::{closure#0}>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_middle/src/lint.rs:461:5
  28:     0x7f7c492d92d2 - <rustc_lint[f3e4522c2a4d1eb3]::levels::LintLevelsBuilder<rustc_lint[f3e4522c2a4d1eb3]::levels::TopDown>>::struct_lint::<rustc_error_messages[87ef96e77df7413c]::DiagnosticMessage, <rustc_lint[f3e4522c2a4d1eb3]::context::EarlyContext as rustc_lint[f3e4522c2a4d1eb3]::context::LintContext>::lookup_with_diagnostics<rustc_error_messages[87ef96e77df7413c]::MultiSpan, rustc_error_messages[87ef96e77df7413c]::DiagnosticMessage, <rustc_lint[f3e4522c2a4d1eb3]::early::EarlyContextAndPass<rustc_lint[f3e4522c2a4d1eb3]::BuiltinCombinedEarlyLintPass>>::inlined_check_id::{closure#0}>::{closure#0}>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_lint/src/levels.rs:1019:9
  29:     0x7f7c4930a799 - <rustc_lint[f3e4522c2a4d1eb3]::context::EarlyContext as rustc_lint[f3e4522c2a4d1eb3]::context::LintContext>::lookup::<rustc_error_messages[87ef96e77df7413c]::MultiSpan, rustc_error_messages[87ef96e77df7413c]::DiagnosticMessage, <rustc_lint[f3e4522c2a4d1eb3]::context::EarlyContext as rustc_lint[f3e4522c2a4d1eb3]::context::LintContext>::lookup_with_diagnostics<rustc_error_messages[87ef96e77df7413c]::MultiSpan, rustc_error_messages[87ef96e77df7413c]::DiagnosticMessage, <rustc_lint[f3e4522c2a4d1eb3]::early::EarlyContextAndPass<rustc_lint[f3e4522c2a4d1eb3]::BuiltinCombinedEarlyLintPass>>::inlined_check_id::{closure#0}>::{closure#0}>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_lint/src/context.rs:1068:9
  30:     0x7f7c4930a799 - <rustc_lint[f3e4522c2a4d1eb3]::context::EarlyContext as rustc_lint[f3e4522c2a4d1eb3]::context::LintContext>::lookup_with_diagnostics::<rustc_error_messages[87ef96e77df7413c]::MultiSpan, rustc_error_messages[87ef96e77df7413c]::DiagnosticMessage, <rustc_lint[f3e4522c2a4d1eb3]::early::EarlyContextAndPass<rustc_lint[f3e4522c2a4d1eb3]::BuiltinCombinedEarlyLintPass>>::inlined_check_id::{closure#0}>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_lint/src/context.rs:601:9
  31:     0x7f7c4930a799 - <rustc_lint[f3e4522c2a4d1eb3]::early::EarlyContextAndPass<rustc_lint[f3e4522c2a4d1eb3]::BuiltinCombinedEarlyLintPass>>::inlined_check_id
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_lint/src/early.rs:47:13
  32:     0x7f7c4930a799 - <rustc_lint[f3e4522c2a4d1eb3]::early::EarlyContextAndPass<rustc_lint[f3e4522c2a4d1eb3]::BuiltinCombinedEarlyLintPass>>::with_lint_attrs::<<rustc_lint[f3e4522c2a4d1eb3]::early::EarlyContextAndPass<rustc_lint[f3e4522c2a4d1eb3]::BuiltinCombinedEarlyLintPass> as rustc_ast[67da8ea2e7591207]::visit::Visitor>::visit_generic_param::{closure#0}>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_lint/src/early.rs:73:14
  33:     0x7f7c4930a799 - <rustc_lint[f3e4522c2a4d1eb3]::early::EarlyContextAndPass<rustc_lint[f3e4522c2a4d1eb3]::BuiltinCombinedEarlyLintPass> as rustc_ast[67da8ea2e7591207]::visit::Visitor>::visit_generic_param
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_lint/src/early.rs:239:9
  34:     0x7f7c49369fcc - rustc_ast[67da8ea2e7591207]::visit::walk_ty::<rustc_lint[f3e4522c2a4d1eb3]::early::EarlyContextAndPass<rustc_lint[f3e4522c2a4d1eb3]::BuiltinCombinedEarlyLintPass>>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_ast/src/visit.rs:410:13
  35:     0x7f7c49306222 - <rustc_lint[f3e4522c2a4d1eb3]::early::EarlyContextAndPass<rustc_lint[f3e4522c2a4d1eb3]::BuiltinCombinedEarlyLintPass> as rustc_ast[67da8ea2e7591207]::visit::Visitor>::visit_param::{closure#0}
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_lint/src/early.rs:87:13
  36:     0x7f7c49306222 - <rustc_lint[f3e4522c2a4d1eb3]::early::EarlyContextAndPass<rustc_lint[f3e4522c2a4d1eb3]::BuiltinCombinedEarlyLintPass>>::with_lint_attrs::<<rustc_lint[f3e4522c2a4d1eb3]::early::EarlyContextAndPass<rustc_lint[f3e4522c2a4d1eb3]::BuiltinCombinedEarlyLintPass> as rustc_ast[67da8ea2e7591207]::visit::Visitor>::visit_param::{closure#0}>::{closure#0}
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_lint/src/early.rs:76:36
  37:     0x7f7c49306222 - stacker[12027ce31fbb92f0]::maybe_grow::<(), <rustc_lint[f3e4522c2a4d1eb3]::early::EarlyContextAndPass<rustc_lint[f3e4522c2a4d1eb3]::BuiltinCombinedEarlyLintPass>>::with_lint_attrs<<rustc_lint[f3e4522c2a4d1eb3]::early::EarlyContextAndPass<rustc_lint[f3e4522c2a4d1eb3]::BuiltinCombinedEarlyLintPass> as rustc_ast[67da8ea2e7591207]::visit::Visitor>::visit_param::{closure#0}>::{closure#0}>
                               at /home/matthias/.cargo/registry/src/github.com-1ecc6299db9ec823/stacker-0.1.15/src/lib.rs:55:9
  38:     0x7f7c49306222 - rustc_data_structures[3154e4d7ef9f97f8]::stack::ensure_sufficient_stack::<(), <rustc_lint[f3e4522c2a4d1eb3]::early::EarlyContextAndPass<rustc_lint[f3e4522c2a4d1eb3]::BuiltinCombinedEarlyLintPass>>::with_lint_attrs<<rustc_lint[f3e4522c2a4d1eb3]::early::EarlyContextAndPass<rustc_lint[f3e4522c2a4d1eb3]::BuiltinCombinedEarlyLintPass> as rustc_ast[67da8ea2e7591207]::visit::Visitor>::visit_param::{closure#0}>::{closure#0}>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_data_structures/src/stack.rs:17:5
  39:     0x7f7c49306222 - <rustc_lint[f3e4522c2a4d1eb3]::early::EarlyContextAndPass<rustc_lint[f3e4522c2a4d1eb3]::BuiltinCombinedEarlyLintPass>>::with_lint_attrs::<<rustc_lint[f3e4522c2a4d1eb3]::early::EarlyContextAndPass<rustc_lint[f3e4522c2a4d1eb3]::BuiltinCombinedEarlyLintPass> as rustc_ast[67da8ea2e7591207]::visit::Visitor>::visit_param::{closure#0}>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_lint/src/early.rs:76:9
  40:     0x7f7c49306222 - <rustc_lint[f3e4522c2a4d1eb3]::early::EarlyContextAndPass<rustc_lint[f3e4522c2a4d1eb3]::BuiltinCombinedEarlyLintPass> as rustc_ast[67da8ea2e7591207]::visit::Visitor>::visit_param
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_lint/src/early.rs:85:9
  41:     0x7f7c4936944c - rustc_ast[67da8ea2e7591207]::visit::walk_fn_decl::<rustc_lint[f3e4522c2a4d1eb3]::early::EarlyContextAndPass<rustc_lint[f3e4522c2a4d1eb3]::BuiltinCombinedEarlyLintPass>>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_ast/src/visit.rs:649:9
  42:     0x7f7c4936944c - rustc_ast[67da8ea2e7591207]::visit::walk_fn::<rustc_lint[f3e4522c2a4d1eb3]::early::EarlyContextAndPass<rustc_lint[f3e4522c2a4d1eb3]::BuiltinCombinedEarlyLintPass>>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_ast/src/visit.rs:659:13
  43:     0x7f7c4936edf9 - <rustc_lint[f3e4522c2a4d1eb3]::early::EarlyContextAndPass<rustc_lint[f3e4522c2a4d1eb3]::BuiltinCombinedEarlyLintPass> as rustc_ast[67da8ea2e7591207]::visit::Visitor>::visit_fn
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_lint/src/early.rs:159:9
  44:     0x7f7c4936edf9 - rustc_ast[67da8ea2e7591207]::visit::walk_item::<rustc_lint[f3e4522c2a4d1eb3]::early::EarlyContextAndPass<rustc_lint[f3e4522c2a4d1eb3]::BuiltinCombinedEarlyLintPass>>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_ast/src/visit.rs:315:13
  45:     0x7f7c493043eb - <rustc_lint[f3e4522c2a4d1eb3]::early::EarlyContextAndPass<rustc_lint[f3e4522c2a4d1eb3]::BuiltinCombinedEarlyLintPass> as rustc_ast[67da8ea2e7591207]::visit::Visitor>::visit_item::{closure#0}
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_lint/src/early.rs:94:13
  46:     0x7f7c493043eb - <rustc_lint[f3e4522c2a4d1eb3]::early::EarlyContextAndPass<rustc_lint[f3e4522c2a4d1eb3]::BuiltinCombinedEarlyLintPass>>::with_lint_attrs::<<rustc_lint[f3e4522c2a4d1eb3]::early::EarlyContextAndPass<rustc_lint[f3e4522c2a4d1eb3]::BuiltinCombinedEarlyLintPass> as rustc_ast[67da8ea2e7591207]::visit::Visitor>::visit_item::{closure#0}>::{closure#0}
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_lint/src/early.rs:76:36
  47:     0x7f7c493043eb - stacker[12027ce31fbb92f0]::maybe_grow::<(), <rustc_lint[f3e4522c2a4d1eb3]::early::EarlyContextAndPass<rustc_lint[f3e4522c2a4d1eb3]::BuiltinCombinedEarlyLintPass>>::with_lint_attrs<<rustc_lint[f3e4522c2a4d1eb3]::early::EarlyContextAndPass<rustc_lint[f3e4522c2a4d1eb3]::BuiltinCombinedEarlyLintPass> as rustc_ast[67da8ea2e7591207]::visit::Visitor>::visit_item::{closure#0}>::{closure#0}>
                               at /home/matthias/.cargo/registry/src/github.com-1ecc6299db9ec823/stacker-0.1.15/src/lib.rs:55:9
  48:     0x7f7c493043eb - rustc_data_structures[3154e4d7ef9f97f8]::stack::ensure_sufficient_stack::<(), <rustc_lint[f3e4522c2a4d1eb3]::early::EarlyContextAndPass<rustc_lint[f3e4522c2a4d1eb3]::BuiltinCombinedEarlyLintPass>>::with_lint_attrs<<rustc_lint[f3e4522c2a4d1eb3]::early::EarlyContextAndPass<rustc_lint[f3e4522c2a4d1eb3]::BuiltinCombinedEarlyLintPass> as rustc_ast[67da8ea2e7591207]::visit::Visitor>::visit_item::{closure#0}>::{closure#0}>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_data_structures/src/stack.rs:17:5
  49:     0x7f7c493043eb - <rustc_lint[f3e4522c2a4d1eb3]::early::EarlyContextAndPass<rustc_lint[f3e4522c2a4d1eb3]::BuiltinCombinedEarlyLintPass>>::with_lint_attrs::<<rustc_lint[f3e4522c2a4d1eb3]::early::EarlyContextAndPass<rustc_lint[f3e4522c2a4d1eb3]::BuiltinCombinedEarlyLintPass> as rustc_ast[67da8ea2e7591207]::visit::Visitor>::visit_item::{closure#0}>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_lint/src/early.rs:76:9
  50:     0x7f7c493043eb - <rustc_lint[f3e4522c2a4d1eb3]::early::EarlyContextAndPass<rustc_lint[f3e4522c2a4d1eb3]::BuiltinCombinedEarlyLintPass> as rustc_ast[67da8ea2e7591207]::visit::Visitor>::visit_item
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_lint/src/early.rs:92:9
  51:     0x7f7c4936237c - rustc_ast[67da8ea2e7591207]::visit::walk_crate::<rustc_lint[f3e4522c2a4d1eb3]::early::EarlyContextAndPass<rustc_lint[f3e4522c2a4d1eb3]::BuiltinCombinedEarlyLintPass>>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_ast/src/visit.rs:266:5
  52:     0x7f7c492f4dae - <&rustc_ast[67da8ea2e7591207]::ast::Crate as rustc_lint[f3e4522c2a4d1eb3]::early::EarlyCheckNode>::check::<rustc_lint[f3e4522c2a4d1eb3]::BuiltinCombinedEarlyLintPass>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_lint/src/early.rs:359:9
  53:     0x7f7c492f4dae - rustc_lint[f3e4522c2a4d1eb3]::early::check_ast_node_inner::<rustc_lint[f3e4522c2a4d1eb3]::BuiltinCombinedEarlyLintPass, &rustc_ast[67da8ea2e7591207]::ast::Crate>::{closure#0}
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_lint/src/early.rs:423:66
  54:     0x7f7c492f4dae - <rustc_lint[f3e4522c2a4d1eb3]::early::EarlyContextAndPass<rustc_lint[f3e4522c2a4d1eb3]::BuiltinCombinedEarlyLintPass>>::with_lint_attrs::<rustc_lint[f3e4522c2a4d1eb3]::early::check_ast_node_inner<rustc_lint[f3e4522c2a4d1eb3]::BuiltinCombinedEarlyLintPass, &rustc_ast[67da8ea2e7591207]::ast::Crate>::{closure#0}>::{closure#0}
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_lint/src/early.rs:76:36
  55:     0x7f7c492f4dae - stacker[12027ce31fbb92f0]::maybe_grow::<(), <rustc_lint[f3e4522c2a4d1eb3]::early::EarlyContextAndPass<rustc_lint[f3e4522c2a4d1eb3]::BuiltinCombinedEarlyLintPass>>::with_lint_attrs<rustc_lint[f3e4522c2a4d1eb3]::early::check_ast_node_inner<rustc_lint[f3e4522c2a4d1eb3]::BuiltinCombinedEarlyLintPass, &rustc_ast[67da8ea2e7591207]::ast::Crate>::{closure#0}>::{closure#0}>
                               at /home/matthias/.cargo/registry/src/github.com-1ecc6299db9ec823/stacker-0.1.15/src/lib.rs:55:9
  56:     0x7f7c492f4dae - rustc_data_structures[3154e4d7ef9f97f8]::stack::ensure_sufficient_stack::<(), <rustc_lint[f3e4522c2a4d1eb3]::early::EarlyContextAndPass<rustc_lint[f3e4522c2a4d1eb3]::BuiltinCombinedEarlyLintPass>>::with_lint_attrs<rustc_lint[f3e4522c2a4d1eb3]::early::check_ast_node_inner<rustc_lint[f3e4522c2a4d1eb3]::BuiltinCombinedEarlyLintPass, &rustc_ast[67da8ea2e7591207]::ast::Crate>::{closure#0}>::{closure#0}>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_data_structures/src/stack.rs:17:5
  57:     0x7f7c492f4dae - <rustc_lint[f3e4522c2a4d1eb3]::early::EarlyContextAndPass<rustc_lint[f3e4522c2a4d1eb3]::BuiltinCombinedEarlyLintPass>>::with_lint_attrs::<rustc_lint[f3e4522c2a4d1eb3]::early::check_ast_node_inner<rustc_lint[f3e4522c2a4d1eb3]::BuiltinCombinedEarlyLintPass, &rustc_ast[67da8ea2e7591207]::ast::Crate>::{closure#0}>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_lint/src/early.rs:76:9
  58:     0x7f7c492f4dae - rustc_lint[f3e4522c2a4d1eb3]::early::check_ast_node_inner::<rustc_lint[f3e4522c2a4d1eb3]::BuiltinCombinedEarlyLintPass, &rustc_ast[67da8ea2e7591207]::ast::Crate>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_lint/src/early.rs:423:5
  59:     0x7f7c492f4dae - rustc_lint[f3e4522c2a4d1eb3]::early::check_ast_node::<rustc_lint[f3e4522c2a4d1eb3]::BuiltinCombinedEarlyLintPass, &rustc_ast[67da8ea2e7591207]::ast::Crate>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_lint/src/early.rs:406:9
  60:     0x7f7c492d4cfd - rustc_interface[4594c92845ad297a]::passes::configure_and_expand::{closure#8}
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_interface/src/passes.rs:448:9
  61:     0x7f7c492d4cfd - <rustc_data_structures[3154e4d7ef9f97f8]::profiling::VerboseTimingGuard>::run::<(), rustc_interface[4594c92845ad297a]::passes::configure_and_expand::{closure#8}>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_data_structures/src/profiling.rs:726:9
  62:     0x7f7c492d4cfd - <rustc_session[5d167e6afbd1bddd]::session::Session>::time::<(), rustc_interface[4594c92845ad297a]::passes::configure_and_expand::{closure#8}>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_session/src/utils.rs:10:50
  63:     0x7f7c4928d930 - rustc_interface[4594c92845ad297a]::passes::configure_and_expand
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_interface/src/passes.rs:446:5
  64:     0x7f7c492f11a3 - <rustc_interface[4594c92845ad297a]::queries::Queries>::expansion::{closure#0}::{closure#0}
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_interface/src/queries.rs:189:17
  65:     0x7f7c492f11a3 - <rustc_interface[4594c92845ad297a]::passes::boxed_resolver::BoxedResolver>::access::<<rustc_interface[4594c92845ad297a]::queries::Queries>::expansion::{closure#0}::{closure#0}, core[3a7799eb5b53fe42]::result::Result<rustc_ast[67da8ea2e7591207]::ast::Crate, rustc_errors[7deb60bbfdd1de15]::ErrorGuaranteed>>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_interface/src/passes.rs:131:13
  66:     0x7f7c492f11a3 - <rustc_interface[4594c92845ad297a]::queries::Queries>::expansion::{closure#0}
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_interface/src/queries.rs:188:25
  67:     0x7f7c492f11a3 - <rustc_interface[4594c92845ad297a]::queries::Query<(alloc[88ef48cbf1494855]::rc::Rc<rustc_ast[67da8ea2e7591207]::ast::Crate>, alloc[88ef48cbf1494855]::rc::Rc<core[3a7799eb5b53fe42]::cell::RefCell<rustc_interface[4594c92845ad297a]::passes::boxed_resolver::BoxedResolver>>, alloc[88ef48cbf1494855]::rc::Rc<rustc_lint[f3e4522c2a4d1eb3]::context::LintStore>)>>::compute::<<rustc_interface[4594c92845ad297a]::queries::Queries>::expansion::{closure#0}>::{closure#0}::{closure#0}
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_interface/src/queries.rs:43:41
  68:     0x7f7c492f11a3 - <core[3a7799eb5b53fe42]::option::Option<core[3a7799eb5b53fe42]::result::Result<rustc_data_structures[3154e4d7ef9f97f8]::steal::Steal<(alloc[88ef48cbf1494855]::rc::Rc<rustc_ast[67da8ea2e7591207]::ast::Crate>, alloc[88ef48cbf1494855]::rc::Rc<core[3a7799eb5b53fe42]::cell::RefCell<rustc_interface[4594c92845ad297a]::passes::boxed_resolver::BoxedResolver>>, alloc[88ef48cbf1494855]::rc::Rc<rustc_lint[f3e4522c2a4d1eb3]::context::LintStore>)>, rustc_errors[7deb60bbfdd1de15]::ErrorGuaranteed>>>::get_or_insert_with::<<rustc_interface[4594c92845ad297a]::queries::Query<(alloc[88ef48cbf1494855]::rc::Rc<rustc_ast[67da8ea2e7591207]::ast::Crate>, alloc[88ef48cbf1494855]::rc::Rc<core[3a7799eb5b53fe42]::cell::RefCell<rustc_interface[4594c92845ad297a]::passes::boxed_resolver::BoxedResolver>>, alloc[88ef48cbf1494855]::rc::Rc<rustc_lint[f3e4522c2a4d1eb3]::context::LintStore>)>>::compute<<rustc_interface[4594c92845ad297a]::queries::Queries>::expansion::{closure#0}>::{closure#0}::{closure#0}>
                               at /home/matthias/vcs/github/rust_debug_assertions/library/core/src/option.rs:1593:49
  69:     0x7f7c492f11a3 - <rustc_interface[4594c92845ad297a]::queries::Query<(alloc[88ef48cbf1494855]::rc::Rc<rustc_ast[67da8ea2e7591207]::ast::Crate>, alloc[88ef48cbf1494855]::rc::Rc<core[3a7799eb5b53fe42]::cell::RefCell<rustc_interface[4594c92845ad297a]::passes::boxed_resolver::BoxedResolver>>, alloc[88ef48cbf1494855]::rc::Rc<rustc_lint[f3e4522c2a4d1eb3]::context::LintStore>)>>::compute::<<rustc_interface[4594c92845ad297a]::queries::Queries>::expansion::{closure#0}>::{closure#0}
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_interface/src/queries.rs:43:17
  70:     0x7f7c492f11a3 - <core[3a7799eb5b53fe42]::cell::RefMut<core[3a7799eb5b53fe42]::option::Option<core[3a7799eb5b53fe42]::result::Result<rustc_data_structures[3154e4d7ef9f97f8]::steal::Steal<(alloc[88ef48cbf1494855]::rc::Rc<rustc_ast[67da8ea2e7591207]::ast::Crate>, alloc[88ef48cbf1494855]::rc::Rc<core[3a7799eb5b53fe42]::cell::RefCell<rustc_interface[4594c92845ad297a]::passes::boxed_resolver::BoxedResolver>>, alloc[88ef48cbf1494855]::rc::Rc<rustc_lint[f3e4522c2a4d1eb3]::context::LintStore>)>, rustc_errors[7deb60bbfdd1de15]::ErrorGuaranteed>>>>::filter_map::<rustc_data_structures[3154e4d7ef9f97f8]::steal::Steal<(alloc[88ef48cbf1494855]::rc::Rc<rustc_ast[67da8ea2e7591207]::ast::Crate>, alloc[88ef48cbf1494855]::rc::Rc<core[3a7799eb5b53fe42]::cell::RefCell<rustc_interface[4594c92845ad297a]::passes::boxed_resolver::BoxedResolver>>, alloc[88ef48cbf1494855]::rc::Rc<rustc_lint[f3e4522c2a4d1eb3]::context::LintStore>)>, <rustc_interface[4594c92845ad297a]::queries::Query<(alloc[88ef48cbf1494855]::rc::Rc<rustc_ast[67da8ea2e7591207]::ast::Crate>, alloc[88ef48cbf1494855]::rc::Rc<core[3a7799eb5b53fe42]::cell::RefCell<rustc_interface[4594c92845ad297a]::passes::boxed_resolver::BoxedResolver>>, alloc[88ef48cbf1494855]::rc::Rc<rustc_lint[f3e4522c2a4d1eb3]::context::LintStore>)>>::compute<<rustc_interface[4594c92845ad297a]::queries::Queries>::expansion::{closure#0}>::{closure#0}>
                               at /home/matthias/vcs/github/rust_debug_assertions/library/core/src/cell.rs:1588:15
  71:     0x7f7c492f11a3 - <rustc_interface[4594c92845ad297a]::queries::Query<(alloc[88ef48cbf1494855]::rc::Rc<rustc_ast[67da8ea2e7591207]::ast::Crate>, alloc[88ef48cbf1494855]::rc::Rc<core[3a7799eb5b53fe42]::cell::RefCell<rustc_interface[4594c92845ad297a]::passes::boxed_resolver::BoxedResolver>>, alloc[88ef48cbf1494855]::rc::Rc<rustc_lint[f3e4522c2a4d1eb3]::context::LintStore>)>>::compute::<<rustc_interface[4594c92845ad297a]::queries::Queries>::expansion::{closure#0}>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_interface/src/queries.rs:40:9
  72:     0x7f7c492f11a3 - <rustc_interface[4594c92845ad297a]::queries::Queries>::expansion
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_interface/src/queries.rs:177:9
  73:     0x7f7c492f1850 - <rustc_interface[4594c92845ad297a]::queries::Queries>::global_ctxt::{closure#0}
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_interface/src/queries.rs:214:49
  74:     0x7f7c492f1850 - <rustc_interface[4594c92845ad297a]::queries::Query<&rustc_middle[ebb8a7eed001d673]::ty::context::GlobalCtxt>>::compute::<<rustc_interface[4594c92845ad297a]::queries::Queries>::global_ctxt::{closure#0}>::{closure#0}::{closure#0}
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_interface/src/queries.rs:43:41
  75:     0x7f7c492f1850 - <core[3a7799eb5b53fe42]::option::Option<core[3a7799eb5b53fe42]::result::Result<rustc_data_structures[3154e4d7ef9f97f8]::steal::Steal<&rustc_middle[ebb8a7eed001d673]::ty::context::GlobalCtxt>, rustc_errors[7deb60bbfdd1de15]::ErrorGuaranteed>>>::get_or_insert_with::<<rustc_interface[4594c92845ad297a]::queries::Query<&rustc_middle[ebb8a7eed001d673]::ty::context::GlobalCtxt>>::compute<<rustc_interface[4594c92845ad297a]::queries::Queries>::global_ctxt::{closure#0}>::{closure#0}::{closure#0}>
                               at /home/matthias/vcs/github/rust_debug_assertions/library/core/src/option.rs:1593:49
  76:     0x7f7c492f1850 - <rustc_interface[4594c92845ad297a]::queries::Query<&rustc_middle[ebb8a7eed001d673]::ty::context::GlobalCtxt>>::compute::<<rustc_interface[4594c92845ad297a]::queries::Queries>::global_ctxt::{closure#0}>::{closure#0}
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_interface/src/queries.rs:43:17
  77:     0x7f7c492f1850 - <core[3a7799eb5b53fe42]::cell::RefMut<core[3a7799eb5b53fe42]::option::Option<core[3a7799eb5b53fe42]::result::Result<rustc_data_structures[3154e4d7ef9f97f8]::steal::Steal<&rustc_middle[ebb8a7eed001d673]::ty::context::GlobalCtxt>, rustc_errors[7deb60bbfdd1de15]::ErrorGuaranteed>>>>::filter_map::<rustc_data_structures[3154e4d7ef9f97f8]::steal::Steal<&rustc_middle[ebb8a7eed001d673]::ty::context::GlobalCtxt>, <rustc_interface[4594c92845ad297a]::queries::Query<&rustc_middle[ebb8a7eed001d673]::ty::context::GlobalCtxt>>::compute<<rustc_interface[4594c92845ad297a]::queries::Queries>::global_ctxt::{closure#0}>::{closure#0}>
                               at /home/matthias/vcs/github/rust_debug_assertions/library/core/src/cell.rs:1588:15
  78:     0x7f7c492f1850 - <rustc_interface[4594c92845ad297a]::queries::Query<&rustc_middle[ebb8a7eed001d673]::ty::context::GlobalCtxt>>::compute::<<rustc_interface[4594c92845ad297a]::queries::Queries>::global_ctxt::{closure#0}>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_interface/src/queries.rs:40:9
  79:     0x7f7c492f1850 - <rustc_interface[4594c92845ad297a]::queries::Queries>::global_ctxt
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_interface/src/queries.rs:212:9
  80:     0x7f7c4875432a - rustc_driver_impl[ebb6d565ed784687]::run_compiler::{closure#1}::{closure#2}
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_driver_impl/src/lib.rs:326:13
  81:     0x7f7c4875432a - <rustc_interface[4594c92845ad297a]::interface::Compiler>::enter::<rustc_driver_impl[ebb6d565ed784687]::run_compiler::{closure#1}::{closure#2}, core[3a7799eb5b53fe42]::result::Result<core[3a7799eb5b53fe42]::option::Option<rustc_interface[4594c92845ad297a]::queries::Linker>, rustc_errors[7deb60bbfdd1de15]::ErrorGuaranteed>>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_interface/src/queries.rs:387:19
  82:     0x7f7c48789085 - rustc_driver_impl[ebb6d565ed784687]::run_compiler::{closure#1}
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_driver_impl/src/lib.rs:288:22
  83:     0x7f7c48789085 - rustc_interface[4594c92845ad297a]::interface::run_compiler::<core[3a7799eb5b53fe42]::result::Result<(), rustc_errors[7deb60bbfdd1de15]::ErrorGuaranteed>, rustc_driver_impl[ebb6d565ed784687]::run_compiler::{closure#1}>::{closure#0}::{closure#0}
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_interface/src/interface.rs:300:21
  84:     0x7f7c48789085 - rustc_span[bb644a7833b5c27d]::with_source_map::<core[3a7799eb5b53fe42]::result::Result<(), rustc_errors[7deb60bbfdd1de15]::ErrorGuaranteed>, rustc_interface[4594c92845ad297a]::interface::run_compiler<core[3a7799eb5b53fe42]::result::Result<(), rustc_errors[7deb60bbfdd1de15]::ErrorGuaranteed>, rustc_driver_impl[ebb6d565ed784687]::run_compiler::{closure#1}>::{closure#0}::{closure#0}>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_span/src/lib.rs:1026:5
  85:     0x7f7c48754e79 - rustc_interface[4594c92845ad297a]::interface::run_compiler::<core[3a7799eb5b53fe42]::result::Result<(), rustc_errors[7deb60bbfdd1de15]::ErrorGuaranteed>, rustc_driver_impl[ebb6d565ed784687]::run_compiler::{closure#1}>::{closure#0}
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_interface/src/interface.rs:294:13
  86:     0x7f7c48754e79 - <scoped_tls[3e8267cb6b5069b8]::ScopedKey<rustc_span[bb644a7833b5c27d]::SessionGlobals>>::set::<rustc_interface[4594c92845ad297a]::interface::run_compiler<core[3a7799eb5b53fe42]::result::Result<(), rustc_errors[7deb60bbfdd1de15]::ErrorGuaranteed>, rustc_driver_impl[ebb6d565ed784687]::run_compiler::{closure#1}>::{closure#0}, core[3a7799eb5b53fe42]::result::Result<(), rustc_errors[7deb60bbfdd1de15]::ErrorGuaranteed>>
                               at /home/matthias/.cargo/registry/src/github.com-1ecc6299db9ec823/scoped-tls-1.0.0/src/lib.rs:137:9
  87:     0x7f7c486fb00f - rustc_span[bb644a7833b5c27d]::create_session_globals_then::<core[3a7799eb5b53fe42]::result::Result<(), rustc_errors[7deb60bbfdd1de15]::ErrorGuaranteed>, rustc_interface[4594c92845ad297a]::interface::run_compiler<core[3a7799eb5b53fe42]::result::Result<(), rustc_errors[7deb60bbfdd1de15]::ErrorGuaranteed>, rustc_driver_impl[ebb6d565ed784687]::run_compiler::{closure#1}>::{closure#0}>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_span/src/lib.rs:111:5
  88:     0x7f7c486fb00f - rustc_interface[4594c92845ad297a]::util::run_in_thread_pool_with_globals::<rustc_interface[4594c92845ad297a]::interface::run_compiler<core[3a7799eb5b53fe42]::result::Result<(), rustc_errors[7deb60bbfdd1de15]::ErrorGuaranteed>, rustc_driver_impl[ebb6d565ed784687]::run_compiler::{closure#1}>::{closure#0}, core[3a7799eb5b53fe42]::result::Result<(), rustc_errors[7deb60bbfdd1de15]::ErrorGuaranteed>>::{closure#0}::{closure#0}
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_interface/src/util.rs:147:38
  89:     0x7f7c486fb00f - std[a3e1a1d40e09fad4]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[4594c92845ad297a]::util::run_in_thread_pool_with_globals<rustc_interface[4594c92845ad297a]::interface::run_compiler<core[3a7799eb5b53fe42]::result::Result<(), rustc_errors[7deb60bbfdd1de15]::ErrorGuaranteed>, rustc_driver_impl[ebb6d565ed784687]::run_compiler::{closure#1}>::{closure#0}, core[3a7799eb5b53fe42]::result::Result<(), rustc_errors[7deb60bbfdd1de15]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[3a7799eb5b53fe42]::result::Result<(), rustc_errors[7deb60bbfdd1de15]::ErrorGuaranteed>>
                               at /home/matthias/vcs/github/rust_debug_assertions/library/std/src/sys_common/backtrace.rs:121:18
  90:     0x7f7c486e42d3 - <std[a3e1a1d40e09fad4]::thread::Builder>::spawn_unchecked_::<rustc_interface[4594c92845ad297a]::util::run_in_thread_pool_with_globals<rustc_interface[4594c92845ad297a]::interface::run_compiler<core[3a7799eb5b53fe42]::result::Result<(), rustc_errors[7deb60bbfdd1de15]::ErrorGuaranteed>, rustc_driver_impl[ebb6d565ed784687]::run_compiler::{closure#1}>::{closure#0}, core[3a7799eb5b53fe42]::result::Result<(), rustc_errors[7deb60bbfdd1de15]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[3a7799eb5b53fe42]::result::Result<(), rustc_errors[7deb60bbfdd1de15]::ErrorGuaranteed>>::{closure#1}::{closure#0}
                               at /home/matthias/vcs/github/rust_debug_assertions/library/std/src/thread/mod.rs:558:17
  91:     0x7f7c486e42d3 - <core[3a7799eb5b53fe42]::panic::unwind_safe::AssertUnwindSafe<<std[a3e1a1d40e09fad4]::thread::Builder>::spawn_unchecked_<rustc_interface[4594c92845ad297a]::util::run_in_thread_pool_with_globals<rustc_interface[4594c92845ad297a]::interface::run_compiler<core[3a7799eb5b53fe42]::result::Result<(), rustc_errors[7deb60bbfdd1de15]::ErrorGuaranteed>, rustc_driver_impl[ebb6d565ed784687]::run_compiler::{closure#1}>::{closure#0}, core[3a7799eb5b53fe42]::result::Result<(), rustc_errors[7deb60bbfdd1de15]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[3a7799eb5b53fe42]::result::Result<(), rustc_errors[7deb60bbfdd1de15]::ErrorGuaranteed>>::{closure#1}::{closure#0}> as core[3a7799eb5b53fe42]::ops::function::FnOnce<()>>::call_once
                               at /home/matthias/vcs/github/rust_debug_assertions/library/core/src/panic/unwind_safe.rs:271:9
  92:     0x7f7c486e42d3 - std[a3e1a1d40e09fad4]::panicking::try::do_call::<core[3a7799eb5b53fe42]::panic::unwind_safe::AssertUnwindSafe<<std[a3e1a1d40e09fad4]::thread::Builder>::spawn_unchecked_<rustc_interface[4594c92845ad297a]::util::run_in_thread_pool_with_globals<rustc_interface[4594c92845ad297a]::interface::run_compiler<core[3a7799eb5b53fe42]::result::Result<(), rustc_errors[7deb60bbfdd1de15]::ErrorGuaranteed>, rustc_driver_impl[ebb6d565ed784687]::run_compiler::{closure#1}>::{closure#0}, core[3a7799eb5b53fe42]::result::Result<(), rustc_errors[7deb60bbfdd1de15]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[3a7799eb5b53fe42]::result::Result<(), rustc_errors[7deb60bbfdd1de15]::ErrorGuaranteed>>::{closure#1}::{closure#0}>, core[3a7799eb5b53fe42]::result::Result<(), rustc_errors[7deb60bbfdd1de15]::ErrorGuaranteed>>
                               at /home/matthias/vcs/github/rust_debug_assertions/library/std/src/panicking.rs:483:40
  93:     0x7f7c486e42d3 - std[a3e1a1d40e09fad4]::panicking::try::<core[3a7799eb5b53fe42]::result::Result<(), rustc_errors[7deb60bbfdd1de15]::ErrorGuaranteed>, core[3a7799eb5b53fe42]::panic::unwind_safe::AssertUnwindSafe<<std[a3e1a1d40e09fad4]::thread::Builder>::spawn_unchecked_<rustc_interface[4594c92845ad297a]::util::run_in_thread_pool_with_globals<rustc_interface[4594c92845ad297a]::interface::run_compiler<core[3a7799eb5b53fe42]::result::Result<(), rustc_errors[7deb60bbfdd1de15]::ErrorGuaranteed>, rustc_driver_impl[ebb6d565ed784687]::run_compiler::{closure#1}>::{closure#0}, core[3a7799eb5b53fe42]::result::Result<(), rustc_errors[7deb60bbfdd1de15]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[3a7799eb5b53fe42]::result::Result<(), rustc_errors[7deb60bbfdd1de15]::ErrorGuaranteed>>::{closure#1}::{closure#0}>>
                               at /home/matthias/vcs/github/rust_debug_assertions/library/std/src/panicking.rs:447:19
  94:     0x7f7c486e42d3 - std[a3e1a1d40e09fad4]::panic::catch_unwind::<core[3a7799eb5b53fe42]::panic::unwind_safe::AssertUnwindSafe<<std[a3e1a1d40e09fad4]::thread::Builder>::spawn_unchecked_<rustc_interface[4594c92845ad297a]::util::run_in_thread_pool_with_globals<rustc_interface[4594c92845ad297a]::interface::run_compiler<core[3a7799eb5b53fe42]::result::Result<(), rustc_errors[7deb60bbfdd1de15]::ErrorGuaranteed>, rustc_driver_impl[ebb6d565ed784687]::run_compiler::{closure#1}>::{closure#0}, core[3a7799eb5b53fe42]::result::Result<(), rustc_errors[7deb60bbfdd1de15]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[3a7799eb5b53fe42]::result::Result<(), rustc_errors[7deb60bbfdd1de15]::ErrorGuaranteed>>::{closure#1}::{closure#0}>, core[3a7799eb5b53fe42]::result::Result<(), rustc_errors[7deb60bbfdd1de15]::ErrorGuaranteed>>
                               at /home/matthias/vcs/github/rust_debug_assertions/library/std/src/panic.rs:140:14
  95:     0x7f7c486e42d3 - <std[a3e1a1d40e09fad4]::thread::Builder>::spawn_unchecked_::<rustc_interface[4594c92845ad297a]::util::run_in_thread_pool_with_globals<rustc_interface[4594c92845ad297a]::interface::run_compiler<core[3a7799eb5b53fe42]::result::Result<(), rustc_errors[7deb60bbfdd1de15]::ErrorGuaranteed>, rustc_driver_impl[ebb6d565ed784687]::run_compiler::{closure#1}>::{closure#0}, core[3a7799eb5b53fe42]::result::Result<(), rustc_errors[7deb60bbfdd1de15]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[3a7799eb5b53fe42]::result::Result<(), rustc_errors[7deb60bbfdd1de15]::ErrorGuaranteed>>::{closure#1}
                               at /home/matthias/vcs/github/rust_debug_assertions/library/std/src/thread/mod.rs:557:30
  96:     0x7f7c486e42d3 - <<std[a3e1a1d40e09fad4]::thread::Builder>::spawn_unchecked_<rustc_interface[4594c92845ad297a]::util::run_in_thread_pool_with_globals<rustc_interface[4594c92845ad297a]::interface::run_compiler<core[3a7799eb5b53fe42]::result::Result<(), rustc_errors[7deb60bbfdd1de15]::ErrorGuaranteed>, rustc_driver_impl[ebb6d565ed784687]::run_compiler::{closure#1}>::{closure#0}, core[3a7799eb5b53fe42]::result::Result<(), rustc_errors[7deb60bbfdd1de15]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[3a7799eb5b53fe42]::result::Result<(), rustc_errors[7deb60bbfdd1de15]::ErrorGuaranteed>>::{closure#1} as core[3a7799eb5b53fe42]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
                               at /home/matthias/vcs/github/rust_debug_assertions/library/core/src/ops/function.rs:250:5
  97:     0x7f7c45b207f8 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h1de6d10e235e916d
                               at /home/matthias/vcs/github/rust_debug_assertions/library/alloc/src/boxed.rs:1988:9
  98:     0x7f7c45b207f8 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h7d484493755f58f7
                               at /home/matthias/vcs/github/rust_debug_assertions/library/alloc/src/boxed.rs:1988:9
  99:     0x7f7c45b05c25 - std::sys::unix::thread::Thread::new::thread_start::hc0cec0ea00f343dd
                               at /home/matthias/vcs/github/rust_debug_assertions/library/std/src/sys/unix/thread.rs:108:17
 100:     0x7f7c45c9f8fd - <unknown>
 101:     0x7f7c45d21d20 - <unknown>
 102:                0x0 - <unknown>

error: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.69.0-dev running on x86_64-unknown-linux-gnu

query stack during panic:
end of query stack
thread 'rustc' panicked at 'Found a `push` without a `pop`.', compiler/rustc_lint/src/levels.rs:509:9
stack backtrace:
   0:     0x7f7c45b6e141 - std::backtrace_rs::backtrace::libunwind::trace::h57c700f2e7064cc9
                               at /home/matthias/vcs/github/rust_debug_assertions/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x7f7c45b6e141 - std::backtrace_rs::backtrace::trace_unsynchronized::h3bd6f8115b3aef84
                               at /home/matthias/vcs/github/rust_debug_assertions/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7f7c45b6e141 - std::sys_common::backtrace::_print_fmt::h4e3cd4a1386ea18b
                               at /home/matthias/vcs/github/rust_debug_assertions/library/std/src/sys_common/backtrace.rs:65:5
   3:     0x7f7c45b6e141 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::ha4399f941a901f68
                               at /home/matthias/vcs/github/rust_debug_assertions/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x7f7c45be4b08 - core::fmt::write::h3693e9c93ce31d95
                               at /home/matthias/vcs/github/rust_debug_assertions/library/core/src/fmt/mod.rs:1232:17
   5:     0x7f7c45b3920f - std::io::Write::write_fmt::h7cd08f6496a9e03d
                               at /home/matthias/vcs/github/rust_debug_assertions/library/std/src/io/mod.rs:1684:15
   6:     0x7f7c45b6df35 - std::sys_common::backtrace::_print::h1ea264f371a6489b
                               at /home/matthias/vcs/github/rust_debug_assertions/library/std/src/sys_common/backtrace.rs:47:5
   7:     0x7f7c45b6df35 - std::sys_common::backtrace::print::h43e663fef4567fcf
                               at /home/matthias/vcs/github/rust_debug_assertions/library/std/src/sys_common/backtrace.rs:34:9
   8:     0x7f7c45b320be - std::panicking::default_hook::{{closure}}::h94496c5e3b8314dc
   9:     0x7f7c45b320be - std::panicking::default_hook::h62ce584520972394
                               at /home/matthias/vcs/github/rust_debug_assertions/library/std/src/panicking.rs:286:9
  10:     0x7f7c486d7102 - <alloc[88ef48cbf1494855]::boxed::Box<dyn for<'a, 'b> core[3a7799eb5b53fe42]::ops::function::Fn<(&'a core[3a7799eb5b53fe42]::panic::panic_info::PanicInfo<'b>,), Output = ()> + core[3a7799eb5b53fe42]::marker::Sync + core[3a7799eb5b53fe42]::marker::Send> as core[3a7799eb5b53fe42]::ops::function::Fn<(&core[3a7799eb5b53fe42]::panic::panic_info::PanicInfo,)>>::call
                               at /home/matthias/vcs/github/rust_debug_assertions/library/alloc/src/boxed.rs:2002:9
  11:     0x7f7c486d7102 - rustc_driver_impl[ebb6d565ed784687]::DEFAULT_HOOK::{closure#0}::{closure#0}
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_driver_impl/src/lib.rs:1163:17
  12:     0x7f7c45b32b8b - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h20060c80854d9f26
                               at /home/matthias/vcs/github/rust_debug_assertions/library/alloc/src/boxed.rs:2002:9
  13:     0x7f7c45b32b8b - std::panicking::rust_panic_with_hook::hf3310e5853e10814
                               at /home/matthias/vcs/github/rust_debug_assertions/library/std/src/panicking.rs:692:13
  14:     0x7f7c45b6f5e2 - std::panicking::begin_panic_handler::{{closure}}::hb76bc4aa6a51e144
                               at /home/matthias/vcs/github/rust_debug_assertions/library/std/src/panicking.rs:577:13
  15:     0x7f7c45b6e25e - std::sys_common::backtrace::__rust_end_short_backtrace::h76df651326f0b61a
                               at /home/matthias/vcs/github/rust_debug_assertions/library/std/src/sys_common/backtrace.rs:137:18
  16:     0x7f7c45b326a2 - rust_begin_unwind
                               at /home/matthias/vcs/github/rust_debug_assertions/library/std/src/panicking.rs:575:5
  17:     0x7f7c45bebb33 - core::panicking::panic_fmt::ha9472d71642ed08e
                               at /home/matthias/vcs/github/rust_debug_assertions/library/core/src/panicking.rs:64:14
  18:     0x7f7c49459cb9 - <rustc_lint[f3e4522c2a4d1eb3]::levels::BuilderPush as core[3a7799eb5b53fe42]::ops::drop::Drop>::drop
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_lint/src/levels.rs:509:9
  19:     0x7f7c492f42f7 - core[3a7799eb5b53fe42]::ptr::drop_in_place::<rustc_lint[f3e4522c2a4d1eb3]::levels::BuilderPush>
                               at /home/matthias/vcs/github/rust_debug_assertions/library/core/src/ptr/mod.rs:490:1
  20:     0x7f7c4930ae2f - <rustc_lint[f3e4522c2a4d1eb3]::early::EarlyContextAndPass<rustc_lint[f3e4522c2a4d1eb3]::BuiltinCombinedEarlyLintPass>>::with_lint_attrs::<<rustc_lint[f3e4522c2a4d1eb3]::early::EarlyContextAndPass<rustc_lint[f3e4522c2a4d1eb3]::BuiltinCombinedEarlyLintPass> as rustc_ast[67da8ea2e7591207]::visit::Visitor>::visit_generic_param::{closure#0}>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_lint/src/early.rs:80:5
  21:     0x7f7c4930ae2f - <rustc_lint[f3e4522c2a4d1eb3]::early::EarlyContextAndPass<rustc_lint[f3e4522c2a4d1eb3]::BuiltinCombinedEarlyLintPass> as rustc_ast[67da8ea2e7591207]::visit::Visitor>::visit_generic_param
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_lint/src/early.rs:239:9
  22:     0x7f7c49369fcc - rustc_ast[67da8ea2e7591207]::visit::walk_ty::<rustc_lint[f3e4522c2a4d1eb3]::early::EarlyContextAndPass<rustc_lint[f3e4522c2a4d1eb3]::BuiltinCombinedEarlyLintPass>>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_ast/src/visit.rs:410:13
  23:     0x7f7c49306222 - <rustc_lint[f3e4522c2a4d1eb3]::early::EarlyContextAndPass<rustc_lint[f3e4522c2a4d1eb3]::BuiltinCombinedEarlyLintPass> as rustc_ast[67da8ea2e7591207]::visit::Visitor>::visit_param::{closure#0}
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_lint/src/early.rs:87:13
  24:     0x7f7c49306222 - <rustc_lint[f3e4522c2a4d1eb3]::early::EarlyContextAndPass<rustc_lint[f3e4522c2a4d1eb3]::BuiltinCombinedEarlyLintPass>>::with_lint_attrs::<<rustc_lint[f3e4522c2a4d1eb3]::early::EarlyContextAndPass<rustc_lint[f3e4522c2a4d1eb3]::BuiltinCombinedEarlyLintPass> as rustc_ast[67da8ea2e7591207]::visit::Visitor>::visit_param::{closure#0}>::{closure#0}
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_lint/src/early.rs:76:36
  25:     0x7f7c49306222 - stacker[12027ce31fbb92f0]::maybe_grow::<(), <rustc_lint[f3e4522c2a4d1eb3]::early::EarlyContextAndPass<rustc_lint[f3e4522c2a4d1eb3]::BuiltinCombinedEarlyLintPass>>::with_lint_attrs<<rustc_lint[f3e4522c2a4d1eb3]::early::EarlyContextAndPass<rustc_lint[f3e4522c2a4d1eb3]::BuiltinCombinedEarlyLintPass> as rustc_ast[67da8ea2e7591207]::visit::Visitor>::visit_param::{closure#0}>::{closure#0}>
                               at /home/matthias/.cargo/registry/src/github.com-1ecc6299db9ec823/stacker-0.1.15/src/lib.rs:55:9
  26:     0x7f7c49306222 - rustc_data_structures[3154e4d7ef9f97f8]::stack::ensure_sufficient_stack::<(), <rustc_lint[f3e4522c2a4d1eb3]::early::EarlyContextAndPass<rustc_lint[f3e4522c2a4d1eb3]::BuiltinCombinedEarlyLintPass>>::with_lint_attrs<<rustc_lint[f3e4522c2a4d1eb3]::early::EarlyContextAndPass<rustc_lint[f3e4522c2a4d1eb3]::BuiltinCombinedEarlyLintPass> as rustc_ast[67da8ea2e7591207]::visit::Visitor>::visit_param::{closure#0}>::{closure#0}>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_data_structures/src/stack.rs:17:5
  27:     0x7f7c49306222 - <rustc_lint[f3e4522c2a4d1eb3]::early::EarlyContextAndPass<rustc_lint[f3e4522c2a4d1eb3]::BuiltinCombinedEarlyLintPass>>::with_lint_attrs::<<rustc_lint[f3e4522c2a4d1eb3]::early::EarlyContextAndPass<rustc_lint[f3e4522c2a4d1eb3]::BuiltinCombinedEarlyLintPass> as rustc_ast[67da8ea2e7591207]::visit::Visitor>::visit_param::{closure#0}>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_lint/src/early.rs:76:9
  28:     0x7f7c49306222 - <rustc_lint[f3e4522c2a4d1eb3]::early::EarlyContextAndPass<rustc_lint[f3e4522c2a4d1eb3]::BuiltinCombinedEarlyLintPass> as rustc_ast[67da8ea2e7591207]::visit::Visitor>::visit_param
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_lint/src/early.rs:85:9
  29:     0x7f7c4936944c - rustc_ast[67da8ea2e7591207]::visit::walk_fn_decl::<rustc_lint[f3e4522c2a4d1eb3]::early::EarlyContextAndPass<rustc_lint[f3e4522c2a4d1eb3]::BuiltinCombinedEarlyLintPass>>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_ast/src/visit.rs:649:9
  30:     0x7f7c4936944c - rustc_ast[67da8ea2e7591207]::visit::walk_fn::<rustc_lint[f3e4522c2a4d1eb3]::early::EarlyContextAndPass<rustc_lint[f3e4522c2a4d1eb3]::BuiltinCombinedEarlyLintPass>>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_ast/src/visit.rs:659:13
  31:     0x7f7c4936edf9 - <rustc_lint[f3e4522c2a4d1eb3]::early::EarlyContextAndPass<rustc_lint[f3e4522c2a4d1eb3]::BuiltinCombinedEarlyLintPass> as rustc_ast[67da8ea2e7591207]::visit::Visitor>::visit_fn
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_lint/src/early.rs:159:9
  32:     0x7f7c4936edf9 - rustc_ast[67da8ea2e7591207]::visit::walk_item::<rustc_lint[f3e4522c2a4d1eb3]::early::EarlyContextAndPass<rustc_lint[f3e4522c2a4d1eb3]::BuiltinCombinedEarlyLintPass>>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_ast/src/visit.rs:315:13
  33:     0x7f7c493043eb - <rustc_lint[f3e4522c2a4d1eb3]::early::EarlyContextAndPass<rustc_lint[f3e4522c2a4d1eb3]::BuiltinCombinedEarlyLintPass> as rustc_ast[67da8ea2e7591207]::visit::Visitor>::visit_item::{closure#0}
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_lint/src/early.rs:94:13
  34:     0x7f7c493043eb - <rustc_lint[f3e4522c2a4d1eb3]::early::EarlyContextAndPass<rustc_lint[f3e4522c2a4d1eb3]::BuiltinCombinedEarlyLintPass>>::with_lint_attrs::<<rustc_lint[f3e4522c2a4d1eb3]::early::EarlyContextAndPass<rustc_lint[f3e4522c2a4d1eb3]::BuiltinCombinedEarlyLintPass> as rustc_ast[67da8ea2e7591207]::visit::Visitor>::visit_item::{closure#0}>::{closure#0}
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_lint/src/early.rs:76:36
  35:     0x7f7c493043eb - stacker[12027ce31fbb92f0]::maybe_grow::<(), <rustc_lint[f3e4522c2a4d1eb3]::early::EarlyContextAndPass<rustc_lint[f3e4522c2a4d1eb3]::BuiltinCombinedEarlyLintPass>>::with_lint_attrs<<rustc_lint[f3e4522c2a4d1eb3]::early::EarlyContextAndPass<rustc_lint[f3e4522c2a4d1eb3]::BuiltinCombinedEarlyLintPass> as rustc_ast[67da8ea2e7591207]::visit::Visitor>::visit_item::{closure#0}>::{closure#0}>
                               at /home/matthias/.cargo/registry/src/github.com-1ecc6299db9ec823/stacker-0.1.15/src/lib.rs:55:9
  36:     0x7f7c493043eb - rustc_data_structures[3154e4d7ef9f97f8]::stack::ensure_sufficient_stack::<(), <rustc_lint[f3e4522c2a4d1eb3]::early::EarlyContextAndPass<rustc_lint[f3e4522c2a4d1eb3]::BuiltinCombinedEarlyLintPass>>::with_lint_attrs<<rustc_lint[f3e4522c2a4d1eb3]::early::EarlyContextAndPass<rustc_lint[f3e4522c2a4d1eb3]::BuiltinCombinedEarlyLintPass> as rustc_ast[67da8ea2e7591207]::visit::Visitor>::visit_item::{closure#0}>::{closure#0}>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_data_structures/src/stack.rs:17:5
  37:     0x7f7c493043eb - <rustc_lint[f3e4522c2a4d1eb3]::early::EarlyContextAndPass<rustc_lint[f3e4522c2a4d1eb3]::BuiltinCombinedEarlyLintPass>>::with_lint_attrs::<<rustc_lint[f3e4522c2a4d1eb3]::early::EarlyContextAndPass<rustc_lint[f3e4522c2a4d1eb3]::BuiltinCombinedEarlyLintPass> as rustc_ast[67da8ea2e7591207]::visit::Visitor>::visit_item::{closure#0}>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_lint/src/early.rs:76:9
  38:     0x7f7c493043eb - <rustc_lint[f3e4522c2a4d1eb3]::early::EarlyContextAndPass<rustc_lint[f3e4522c2a4d1eb3]::BuiltinCombinedEarlyLintPass> as rustc_ast[67da8ea2e7591207]::visit::Visitor>::visit_item
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_lint/src/early.rs:92:9
  39:     0x7f7c4936237c - rustc_ast[67da8ea2e7591207]::visit::walk_crate::<rustc_lint[f3e4522c2a4d1eb3]::early::EarlyContextAndPass<rustc_lint[f3e4522c2a4d1eb3]::BuiltinCombinedEarlyLintPass>>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_ast/src/visit.rs:266:5
  40:     0x7f7c492f4dae - <&rustc_ast[67da8ea2e7591207]::ast::Crate as rustc_lint[f3e4522c2a4d1eb3]::early::EarlyCheckNode>::check::<rustc_lint[f3e4522c2a4d1eb3]::BuiltinCombinedEarlyLintPass>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_lint/src/early.rs:359:9
  41:     0x7f7c492f4dae - rustc_lint[f3e4522c2a4d1eb3]::early::check_ast_node_inner::<rustc_lint[f3e4522c2a4d1eb3]::BuiltinCombinedEarlyLintPass, &rustc_ast[67da8ea2e7591207]::ast::Crate>::{closure#0}
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_lint/src/early.rs:423:66
  42:     0x7f7c492f4dae - <rustc_lint[f3e4522c2a4d1eb3]::early::EarlyContextAndPass<rustc_lint[f3e4522c2a4d1eb3]::BuiltinCombinedEarlyLintPass>>::with_lint_attrs::<rustc_lint[f3e4522c2a4d1eb3]::early::check_ast_node_inner<rustc_lint[f3e4522c2a4d1eb3]::BuiltinCombinedEarlyLintPass, &rustc_ast[67da8ea2e7591207]::ast::Crate>::{closure#0}>::{closure#0}
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_lint/src/early.rs:76:36
  43:     0x7f7c492f4dae - stacker[12027ce31fbb92f0]::maybe_grow::<(), <rustc_lint[f3e4522c2a4d1eb3]::early::EarlyContextAndPass<rustc_lint[f3e4522c2a4d1eb3]::BuiltinCombinedEarlyLintPass>>::with_lint_attrs<rustc_lint[f3e4522c2a4d1eb3]::early::check_ast_node_inner<rustc_lint[f3e4522c2a4d1eb3]::BuiltinCombinedEarlyLintPass, &rustc_ast[67da8ea2e7591207]::ast::Crate>::{closure#0}>::{closure#0}>
                               at /home/matthias/.cargo/registry/src/github.com-1ecc6299db9ec823/stacker-0.1.15/src/lib.rs:55:9
  44:     0x7f7c492f4dae - rustc_data_structures[3154e4d7ef9f97f8]::stack::ensure_sufficient_stack::<(), <rustc_lint[f3e4522c2a4d1eb3]::early::EarlyContextAndPass<rustc_lint[f3e4522c2a4d1eb3]::BuiltinCombinedEarlyLintPass>>::with_lint_attrs<rustc_lint[f3e4522c2a4d1eb3]::early::check_ast_node_inner<rustc_lint[f3e4522c2a4d1eb3]::BuiltinCombinedEarlyLintPass, &rustc_ast[67da8ea2e7591207]::ast::Crate>::{closure#0}>::{closure#0}>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_data_structures/src/stack.rs:17:5
  45:     0x7f7c492f4dae - <rustc_lint[f3e4522c2a4d1eb3]::early::EarlyContextAndPass<rustc_lint[f3e4522c2a4d1eb3]::BuiltinCombinedEarlyLintPass>>::with_lint_attrs::<rustc_lint[f3e4522c2a4d1eb3]::early::check_ast_node_inner<rustc_lint[f3e4522c2a4d1eb3]::BuiltinCombinedEarlyLintPass, &rustc_ast[67da8ea2e7591207]::ast::Crate>::{closure#0}>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_lint/src/early.rs:76:9
  46:     0x7f7c492f4dae - rustc_lint[f3e4522c2a4d1eb3]::early::check_ast_node_inner::<rustc_lint[f3e4522c2a4d1eb3]::BuiltinCombinedEarlyLintPass, &rustc_ast[67da8ea2e7591207]::ast::Crate>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_lint/src/early.rs:423:5
  47:     0x7f7c492f4dae - rustc_lint[f3e4522c2a4d1eb3]::early::check_ast_node::<rustc_lint[f3e4522c2a4d1eb3]::BuiltinCombinedEarlyLintPass, &rustc_ast[67da8ea2e7591207]::ast::Crate>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_lint/src/early.rs:406:9
  48:     0x7f7c492d4cfd - rustc_interface[4594c92845ad297a]::passes::configure_and_expand::{closure#8}
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_interface/src/passes.rs:448:9
  49:     0x7f7c492d4cfd - <rustc_data_structures[3154e4d7ef9f97f8]::profiling::VerboseTimingGuard>::run::<(), rustc_interface[4594c92845ad297a]::passes::configure_and_expand::{closure#8}>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_data_structures/src/profiling.rs:726:9
  50:     0x7f7c492d4cfd - <rustc_session[5d167e6afbd1bddd]::session::Session>::time::<(), rustc_interface[4594c92845ad297a]::passes::configure_and_expand::{closure#8}>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_session/src/utils.rs:10:50
  51:     0x7f7c4928d930 - rustc_interface[4594c92845ad297a]::passes::configure_and_expand
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_interface/src/passes.rs:446:5
  52:     0x7f7c492f11a3 - <rustc_interface[4594c92845ad297a]::queries::Queries>::expansion::{closure#0}::{closure#0}
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_interface/src/queries.rs:189:17
  53:     0x7f7c492f11a3 - <rustc_interface[4594c92845ad297a]::passes::boxed_resolver::BoxedResolver>::access::<<rustc_interface[4594c92845ad297a]::queries::Queries>::expansion::{closure#0}::{closure#0}, core[3a7799eb5b53fe42]::result::Result<rustc_ast[67da8ea2e7591207]::ast::Crate, rustc_errors[7deb60bbfdd1de15]::ErrorGuaranteed>>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_interface/src/passes.rs:131:13
  54:     0x7f7c492f11a3 - <rustc_interface[4594c92845ad297a]::queries::Queries>::expansion::{closure#0}
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_interface/src/queries.rs:188:25
  
<snip>

error: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.69.0-dev running on x86_64-unknown-linux-gnu

query stack during panic:
end of query stack
thread panicked while panicking. aborting.
[1]    311014 IOT instruction  ~/.rustup/toolchains/local-debug-assertions/bin/rustc  -Wsingle-use-lifetimes
```

</p>
</details>

### PR DESCRIPTION
**Pull request by chenyukang**
Fixes #107998
r? @TaKO8Ki

### CODE REVIEW

File: tests/ui/single-use-lifetime/issue-107998.rs [hunk 1]
```diff
@@ -0,0 +1,18 @@
+#![deny(single_use_lifetimes)]
+#![allow(dead_code)]
+#![allow(unused_variables)]
+
+fn with<R>(f: &fn<'a>(x: &'a int) -> R) -> R {
+    //~^ ERROR function pointer types may not have generic parameters
+    //~| ERROR cannot find type `int` in this scope
```
Comment (compiler-errors) [inline tests/ui/single-use-lifetime/issue-107998.rs:7]: Is this second error needed to reproduce the ICE? Can we suppress the `int` error? Also, is the `return_it` function needed? It's best to minimize this as far as possible, I think.

Comment (chenyukang) [reply tests/ui/single-use-lifetime/issue-107998.rs]: cleaned up!

File: tests/ui/single-use-lifetime/issue-107998.rs [hunk 2]
```diff
@@ -0,0 +1,10 @@
+#![deny(single_use_lifetimes)]
+#![allow(dead_code)]
+#![allow(unused_variables)]
```
Comment (compiler-errors) [inline tests/ui/single-use-lifetime/issue-107998.rs:3]:
```suggestion
#![deny(single_use_lifetimes)]
```

File: compiler/rustc_resolve/src/late/diagnostics.rs [hunk 3]
```diff
@@ -2181,6 +2181,11 @@ impl<'a: 'ast, 'ast> LateResolutionVisitor<'a, '_, 'ast> {
         generics_span: Span,
         params: &[ast::GenericParam],
     ) {
+        if generics_span.is_empty() {
```
Comment (compiler-errors) [inline compiler/rustc_resolve/src/late/diagnostics.rs:2184]: Hm... maybe we should put this check into the `deletion_span` closure instead, and just return `None`? It's still kind of nice to be able to emit this lint.

**Review by compiler-errors — COMMENTED** [review]
r=me with nit or not

File: compiler/rustc_resolve/src/late/diagnostics.rs (hunk 3 above)
Comment (chenyukang) [reply compiler/rustc_resolve/src/late/diagnostics.rs:2184]: How about we delay the check to this position, so we can emit more possible lint

https://github.com/rust-lang/rust/blob/5348a89a77a49f6f57c13c0edf7f493fd410159a/compiler/rustc_lint/src/context.rs#L842

Comment (compiler-errors) [reply compiler/rustc_resolve/src/late/diagnostics.rs:2184]: That works too probably

File: tests/ui/single-use-lifetime/issue-107998.stderr [hunk 4]
```diff
@@ -0,0 +1,30 @@
...
+   |
+
+error: lifetime parameter `'a` only used once
+  --> $DIR/issue-107998.rs:3:19
+   |
+LL | fn with<R>(f: &fn<'a>(x: &'a i32) -> R) -> R {
+   |                   ^^      ---
+   |                   |       |
+   |                   |       ...is used only here
+   |                   |       help: elide the single-use lifetime
```
Comment (compiler-errors) [inline tests/ui/single-use-lifetime/issue-107998.stderr:20]: This is still a bit unsatisfying, but oh well

**Review by compiler-errors — COMMENTED** [review]
r=me when ci is green
