### PR TITLE
Make generic parameters always use modern hygiene

### LINKED ISSUE #58307: Const generic parameters have incorrect hygiene
Const generic parameters are treated as hygienic by `macro_rule` because it uses "`let` variable hygiene" rather than "item hygiene".

See https://github.com/rust-lang/rust/issues/57523#issuecomment-453788106 and https://github.com/rust-lang/rust/pull/58191#discussion_r254251259.

cc @petrochenkov

### LINKED ISSUE #60746: Const generic in macros_rules unable to be found in function scope
`nightly 2019-05-10 d595b113584f8f446957`

https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=8ed8182c5ced88e5436ba074014283c1

```rust
#![feature(const_generics)]

macro_rules! compile {
    ($t:ty; $e:expr) => {{
        fn compiletime<const N: $t>() -> $t {
            N
        }
        compiletime::<{ $e }>()
    }};
}

const fn square(x: usize) -> usize {
    x * x
}

fn main() {
    let mut x = compile! { usize;
        square(4) + square(5)
    };

    x += 1;
    println!("{}", x);
}
```
Produces the error:
```
error[E0425]: cannot find value `N` in this scope
  --> src/main.rs:6:13
   |
6  |               N
   |               ^ not found in this scope
...
17 |       let mut x = compile! { usize;
   |  _________________-
18 | |         square(4) + square(5)
19 | |     };
   | |_____- in this macro invocation
```

Without the macro:
https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=3bc031a4b607a3128a5ce1f53564c181

```
42
```

### LINKED ISSUE #61574: 'Cannot find value in this scope' on macro expansion with generic over const `impl` block inside.
I kinda hoped that snippet below will be compiled:
```rust
#![feature(const_generics)]

use std::ops::Add;

struct VectorLike<T, const SIZE: usize>([T; {SIZE}]);

macro_rules! impl_operator_overload {
    ($trait_ident:ident, $method_ident:ident) => {
    
        impl<T, const SIZE: usize> $trait_ident for VectorLike<T, {SIZE}> 
        where
            T: $trait_ident,
        {
            type Output = VectorLike<T, {SIZE}>;
            
            fn $method_ident(self, _: VectorLike<T, {SIZE}>) -> VectorLike<T, {SIZE}> {
                unimplemented!()
            }
        }
        
    }
}

impl_operator_overload!(Add, add);
```

Instead I got a bunch of errors like
```
error[E0425]: cannot find value `SIZE` in this scope
```
for `SIZE` in every occurrence of `{SIZE}` inside macro body, and one
```
the const parameter `SIZE` is not constrained by the impl trait, self type, or predicates
```
for `SIZE` in `impl<T, const SIZE: usize>`.

[Playground permalink](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=e7c0f610b995727536424624cfbc43a0)

Unlike snippet with "const variable" above, this one with "const value" compiles without any 
issues:
```rust
#![feature(const_generics)]

use std::ops::Add;

struct VectorLike<T, const SIZE: usize>([T; {SIZE}]);

macro_rules! impl_operator_overload {
    ($trait_ident:ident, $method_ident:ident) => {
    
        impl<T> $trait_ident for VectorLike<T, 3> 
        where
            T: $trait_ident,
        {
            type Output = VectorLike<T, 3>;
            
            fn $method_ident(self, _: VectorLike<T, 3>) -> VectorLike<T, 3> {
                unimplemented!()
            }
        }
        
    }
}

impl_operator_overload!(Add, add);
```

This issue seems to be related to #58307.

Rustc version: `1.37.0-nightly (2019-06-04 5d8f59f4b1473217c2de)`.

### LINKED ISSUE #62433: Something weird with const generic resolution in macro_rules
This works, so const generic resolution works through macros (https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=e93e583bc759379eae9dac80ed011361)
```rust
#![feature(const_generics)]
trait Foo {}
struct Bar<T, const N: usize>(T);
trait Qux<const N: usize> {}
macro_rules! bar {
    ($t:ty) => {
        impl<T, const N: usize> Foo for $t
        {}
    }
}
bar!(Bar<T, {N}>);
```

This also works, so const generics work in a where guard (https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=cde12aadff1355221b94beef0782da9c)
```rust
#![feature(const_generics)]
trait Foo {}
struct Bar<T, const N: usize>(T);
trait Qux<const N: usize> {}
impl<T, const N: usize> Foo for Bar<T, {N}>
    where (): Qux<{N}>
{}
```

But if I combine those together, all of a sudden it has name resolution problems (https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=c11ade7c9cc0f31a0fc538816bbe0719)
```rust
#![feature(const_generics)]
trait Foo {}
struct Bar<T, const N: usize>(T);
trait Qux<const N: usize> {}
macro_rules! bar {
    ($t:ty) => {
        impl<T, const N: usize> Foo for $t
            where (): Qux<{N}>
        {}
    }
}
bar!(Bar<T, {N}>);
```

```rust
error[E0425]: cannot find value `N` in this scope
  --> src/lib.rs:8:28
   |
8  |             where (): Qux<{N}>
   |                            ^ not found in this scope
...
12 | bar!(Bar<T, {N}>);
   | ------------------ in this macro invocation
```

So something seems weird, but I have no idea what it could be

### PR DESCRIPTION
**Pull request by matthewjasper**
* E0263 (lifetime parameter declared twice in the same scope) now compares modernized identifiers.
* Const parameters are now resolved with modern hygiene.

Closes #58307
Closes #60746
Closes #61574
Closes #62433

### CODE REVIEW

**Comment by petrochenkov** [comment]
@matthewjasper 
Could you check whether this fixes other related issues - https://github.com/rust-lang/rust/issues/60746, https://github.com/rust-lang/rust/issues/61574 (perhaps some test cases are missing?).

File: src/librustc_resolve/lib.rs [hunk 1]
```diff
@@ -872,8 +872,7 @@ impl<'a, 'tcx> Visitor<'tcx> for Resolver<'a> {
         debug!("(resolving function) entering function");
         let rib_kind = match function_kind {
             FnKind::ItemFn(..) => FnItemRibKind,
-            FnKind::Method(..) => AssocItemRibKind,
-            FnKind::Closure(_) => NormalRibKind,
+            FnKind::Method(..) | FnKind::Closure(_) => NormalRibKind,
```
Comment (petrochenkov) [inline src/librustc_resolve/lib.rs]: Why is this changed, and why did it work previously?
I don't quite remember all the differences between many kinds of ribs that act as "barriers" for names.

Comment (matthewjasper) [reply src/librustc_resolve/lib.rs]: So the reason that this has little effect is that there is already an AssocItemRib around all associated items that holds any generic parameters. Since generic parameters can be seen through associated items, this rib isn't stopping any names from being visible.
The reason for the change is so that function parameters don't end up in an associated item rib, and get resolved with the wrong hygiene.
