### PR TITLE
mGCA: Make trait object types with type-level associated consts dyn compatible

### LINKED ISSUE #130300: Permit trait object types where all (non-generic) associated constants are specified (via assoc item bindings)
> **Important context**: Inherently, this would only become legal under the ongoing lang experiment [associated const equality](https://github.com/rust-lang/rust/issues/92827).

We permit trait object types where all (non-generic) associated *types* are specified (via assoc item bindings). We should extend this to cover (non-generic[^1]) associated *constants*, too.

Note that I haven't spent much time thinking about *soundness* yet. I still need to iron out the exact rules.
Implementation-wise, I'm almost certain that any advances are blocked by #120905 which I presume we would need to fix first for correctness.

Minimal example of something that would start compiling:

```rs
#![feature(associated_const_equality)]

trait Trait {
    const K: ();
}

fn main() {
    let _: dyn Trait<K = { () }>;
}
```

Presently, this gets rejected and we emit E0038 (*cannot be made into an object*).

---

Lastly, lest I forget, we should emit the lint `unused_associated_type_bounds`[^2] (cc #112319) for assoc const bindings where the corresp. assoc const is 'disabled' via `where Self: Sized` which is possible to write under [generic const items](https://github.com/rust-lang/rust/issues/113521).

---

[^1]: Generic ACs (GACs) are only possible under [generic const items](https://github.com/rust-lang/rust/issues/113521) anyway.
[^2]: Indeed, the name would no longer be accurate. Ideally, we would rename the lint when generalizing it.

### LINKED ISSUE #136063: ICE: fast reject: `kind mismatch: {type error} 3_u8`
auto-reduced (treereduce-rust):
````rust
#![feature(generic_const_exprs)]
trait Traitor<const N: u8 = 1, const M: u8 = repeat_36> {}

impl Traitor<2, 3> for bool {}

fn bar<const N: u8>(arg: &dyn Traitor<N>) -> u8 {
    arg.owo()
}

fn main() {
    bar(&true);
}

````

original:
````rust
trait Trait<const N: u8 = 12> {
    fn uwu(&self) -> u8 {
        N
    }
}

impl Trait<2> for u32 {}

fn foo(arg: &dyn Trait) -> isize {
    arg.uwu()
}

trait Traitor<const N: u8 = 1, const M: u8 = repeat_36> {
    fn owo(&self) -> u8 {
        M
    }
}

impl Traitor<2, 3> for bool {}

fn bar<const N: u8>(arg: &dyn Traitor<N>) -> u8 {
    arg.owo()
}

fn main() {
    foo(&10_u32);
    //~^ error: the trait bound `u32: Trait` is not satisfied
    bar(&true);
    //~^ error: the trait bound `bool: Traitor<_>` is not satisfied
}

````

Version information
````
rustc 1.86.0-nightly (203e6c127 2025-01-25)
binary: rustc
commit-hash: 203e6c127c50c499be53731a39fe36d24f544502
commit-date: 2025-01-25
host: x86_64-unknown-linux-gnu
release: 1.86.0-nightly
LLVM version: 19.1.7

````

Command:
`/home/matthias/.rustup/toolchains/master/bin/rustc -Zcrate-attr=feature(generic_const_exprs)`

<details><summary><strong>Program output</strong></summary>
<p>

```
error[E0425]: cannot find value `repeat_36` in this scope
 --> /tmp/icemaker_global_tempdir.WTfAIAh7lsb4/rustc_testrunner_tmpdir_reporting.MvFPhVMEvs6Q/mvce.rs:1:46
  |
1 | trait Traitor<const N: u8 = 1, const M: u8 = repeat_36> {}
  |                                              ^^^^^^^^^ not found in this scope

warning: the feature `generic_const_exprs` is incomplete and may not be safe to use and/or cause compiler crashes
 --> <crate attribute>:1:9
  |
1 | feature(generic_const_exprs)
  |         ^^^^^^^^^^^^^^^^^^^
  |
  = note: see issue #76560 <https://github.com/rust-lang/rust/issues/76560> for more information
  = note: `#[warn(incomplete_features)]` on by default

error[E0393]: the type parameter `M` must be explicitly specified
 --> /tmp/icemaker_global_tempdir.WTfAIAh7lsb4/rustc_testrunner_tmpdir_reporting.MvFPhVMEvs6Q/mvce.rs:5:31
  |
1 | trait Traitor<const N: u8 = 1, const M: u8 = repeat_36> {}
  | ------------------------------------------------------- type parameter `M` must be specified for this
...
5 | fn bar<const N: u8>(arg: &dyn Traitor<N>) -> u8 {
  |                               ^^^^^^^^^^ missing reference to `M`
  |
  = note: because the parameter default references `Self`, the parameter must be specified on the object type


thread 'rustc' panicked at /rustc/203e6c127c50c499be53731a39fe36d24f544502/compiler/rustc_type_ir/src/fast_reject.rs:254:22:
kind mismatch: {type error} 3_u8
stack backtrace:
   0:     0x7b60dde902a0 - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::hdfdabc38b8669c9f
   1:     0x7b60de6150e6 - core::fmt::write::h85841a8a9f23dd59
   2:     0x7b60df5594d1 - std::io::Write::write_fmt::hf2e4fe8e168db1b7
   3:     0x7b60dde90102 - std::sys::backtrace::BacktraceLock::print::h14149197b7c0de32
   4:     0x7b60dde92582 - std::panicking::default_hook::{{closure}}::h9943e5f3f0626409
   5:     0x7b60dde9240a - std::panicking::default_hook::hdd3968de3a098232
   6:     0x7b60dd0459e9 - std[57730b54ef401f3]::panicking::update_hook::<alloc[f5830c3c5cfb9e11]::boxed::Box<rustc_driver_impl[238e9adc12ab3263]::install_ice_hook::{closure#1}>>::{closure#0}
   7:     0x7b60dde93103 - std::panicking::rust_panic_with_hook::h73ef51d9a205dc0a
   8:     0x7b60dde92dfa - std::panicking::begin_panic_handler::{{closure}}::hed515db6078dd255
   9:     0x7b60dde90789 - std::sys::backtrace::__rust_end_short_backtrace::h8ba760917d95b5b1
  10:     0x7b60dde92abd - rust_begin_unwind
  11:     0x7b60dab98400 - core::panicking::panic_fmt::h5ecc779537f0304d
  12:     0x7b60db43899b - <rustc_trait_selection[4ba0541b438290d2]::traits::select::SelectionContext>::assemble_candidates_from_impls
  13:     0x7b60db415705 - <rustc_trait_selection[4ba0541b438290d2]::traits::select::SelectionContext>::candidate_from_obligation::{closure#0}::{closure#0}
  14:     0x7b60dae5c32e - <rustc_trait_selection[4ba0541b438290d2]::traits::select::SelectionContext>::poly_select::{closure#0}
  15:     0x7b60deee6030 - <rustc_trait_selection[4ba0541b438290d2]::traits::fulfill::FulfillProcessor as rustc_data_structures[b1621f9a8426d32f]::obligation_forest::ObligationProcessor>::process_obligation
  16:     0x7b60de610882 - <rustc_data_structures[b1621f9a8426d32f]::obligation_forest::ObligationForest<rustc_trait_selection[4ba0541b438290d2]::traits::fulfill::PendingPredicateObligation>>::process_obligations::<rustc_trait_selection[4ba0541b438290d2]::traits::fulfill::FulfillProcessor>
  17:     0x7b60de79f0e4 - <rustc_hir_typeck[f3c634e21e25c7e1]::fn_ctxt::FnCtxt>::confirm_builtin_call
  18:     0x7b60df390bc8 - <rustc_hir_typeck[f3c634e21e25c7e1]::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
  19:     0x7b60df389dcf - <rustc_hir_typeck[f3c634e21e25c7e1]::fn_ctxt::FnCtxt>::check_expr_block
  20:     0x7b60df3916d4 - <rustc_hir_typeck[f3c634e21e25c7e1]::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
  21:     0x7b60dec88780 - rustc_hir_typeck[f3c634e21e25c7e1]::check::check_fn
  22:     0x7b60dec9163d - rustc_hir_typeck[f3c634e21e25c7e1]::typeck_with_inspect::{closure#0}
  23:     0x7b60dec8f64c - rustc_query_impl[db064f70679e7e57]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[db064f70679e7e57]::query_impl::typeck::dynamic_query::{closure#2}::{closure#0}, rustc_middle[e5994b11539d1088]::query::erase::Erased<[u8; 8usize]>>
  24:     0x7b60de981a4e - rustc_query_system[acb98781fee9c8ed]::query::plumbing::try_execute_query::<rustc_query_impl[db064f70679e7e57]::DynamicConfig<rustc_data_structures[b1621f9a8426d32f]::vec_cache::VecCache<rustc_span[573b00108592c307]::def_id::LocalDefId, rustc_middle[e5994b11539d1088]::query::erase::Erased<[u8; 8usize]>, rustc_query_system[acb98781fee9c8ed]::dep_graph::graph::DepNodeIndex>, false, false, false>, rustc_query_impl[db064f70679e7e57]::plumbing::QueryCtxt, false>
  25:     0x7b60de97ff51 - rustc_query_impl[db064f70679e7e57]::query_impl::typeck::get_query_non_incr::__rust_end_short_backtrace
  26:     0x7b60de97fc0b - <rustc_middle[e5994b11539d1088]::hir::map::Map>::par_body_owners::<rustc_hir_analysis[f7ab43cc31358404]::check_crate::{closure#4}>::{closure#0}
  27:     0x7b60de97dcbf - rustc_hir_analysis[f7ab43cc31358404]::check_crate
  28:     0x7b60de97a2e2 - rustc_interface[a9a02922dc001c32]::passes::run_required_analyses
  29:     0x7b60df554bde - rustc_interface[a9a02922dc001c32]::passes::analysis
  30:     0x7b60df554baf - rustc_query_impl[db064f70679e7e57]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[db064f70679e7e57]::query_impl::analysis::dynamic_query::{closure#2}::{closure#0}, rustc_middle[e5994b11539d1088]::query::erase::Erased<[u8; 0usize]>>
  31:     0x7b60df541b55 - rustc_query_system[acb98781fee9c8ed]::query::plumbing::try_execute_query::<rustc_query_impl[db064f70679e7e57]::DynamicConfig<rustc_query_system[acb98781fee9c8ed]::query::caches::SingleCache<rustc_middle[e5994b11539d1088]::query::erase::Erased<[u8; 0usize]>>, false, false, false>, rustc_query_impl[db064f70679e7e57]::plumbing::QueryCtxt, false>
  32:     0x7b60df54188e - rustc_query_impl[db064f70679e7e57]::query_impl::analysis::get_query_non_incr::__rust_end_short_backtrace
  33:     0x7b60df603969 - rustc_interface[a9a02922dc001c32]::passes::create_and_enter_global_ctxt::<core[bef17dfe197dbeb2]::option::Option<rustc_interface[a9a02922dc001c32]::queries::Linker>, rustc_driver_impl[238e9adc12ab3263]::run_compiler::{closure#0}::{closure#2}>::{closure#2}::{closure#0}
  34:     0x7b60df5ad513 - rustc_interface[a9a02922dc001c32]::interface::run_compiler::<(), rustc_driver_impl[238e9adc12ab3263]::run_compiler::{closure#0}>::{closure#1}
  35:     0x7b60df4a7235 - std[57730b54ef401f3]::sys::backtrace::__rust_begin_short_backtrace::<rustc_interface[a9a02922dc001c32]::util::run_in_thread_with_globals<rustc_interface[a9a02922dc001c32]::util::run_in_thread_pool_with_globals<rustc_interface[a9a02922dc001c32]::interface::run_compiler<(), rustc_driver_impl[238e9adc12ab3263]::run_compiler::{closure#0}>::{closure#1}, ()>::{closure#0}, ()>::{closure#0}::{closure#0}, ()>
  36:     0x7b60df4a6f19 - <<std[57730b54ef401f3]::thread::Builder>::spawn_unchecked_<rustc_interface[a9a02922dc001c32]::util::run_in_thread_with_globals<rustc_interface[a9a02922dc001c32]::util::run_in_thread_pool_with_globals<rustc_interface[a9a02922dc001c32]::interface::run_compiler<(), rustc_driver_impl[238e9adc12ab3263]::run_compiler::{closure#0}>::{closure#1}, ()>::{closure#0}, ()>::{closure#0}::{closure#0}, ()>::{closure#1} as core[bef17dfe197dbeb2]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  37:     0x7b60df4a66af - std::sys::pal::unix::thread::Thread::new::thread_start::h58ab2ce80d2171c1
  38:     0x7b60d98a339d - <unknown>
  39:     0x7b60d992849c - <unknown>
  40:                0x0 - <unknown>

error: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: please make sure that you have updated to the latest nightly

note: rustc 1.86.0-nightly (203e6c127 2025-01-25) running on x86_64-unknown-linux-gnu

note: compiler flags: -Z crate-attr=feature(generic_const_exprs) -Z dump-mir-dir=dir

query stack during panic:
#0 [typeck] type-checking `main`
#1 [analysis] running analysis passes on this crate
end of query stack
error: aborting due to 2 previous errors; 1 warning emitted

Some errors have detailed explanations: E0393, E0425.
For more information about an error, try `rustc --explain E0393`.

```

</p>
</details>

@rustbot label +F-generic_const_exprs

### LINKED ISSUE #137260: ICE: `impossible case reached: can't relate: UnevaluatedConst`
auto-reduced (treereduce-rust):
````rust
#![feature(generic_const_exprs)]
trait Iter<const FN: fn() = { || {} }> {}

fn needs_iter<'a, T: Iter<'a, I> + ?Sized, I: 'a>(_: &T) {}

fn test(x: &dyn Iter<'_, ()>) {
    needs_iter(x);
}

````

original:
````rust
//@ compile-flags: -Znext-solver
//@ check-pass

trait Iter<const FN: fn() = { || {} }>: Iterator<Item = &'a I> {}

fn needs_iter<'a, T: Iter<'a, I> + ?Sized, I: 'a>(_: &T) {}

fn test(x: &dyn Iter<'_, ()>) {
    needs_iter(x);
}

fn main() {}

````

Version information
````
rustc 1.87.0-nightly (17c1c329a 2025-02-19)
binary: rustc
commit-hash: 17c1c329a5512d718b67ef6797538b154016cd34
commit-date: 2025-02-19
host: x86_64-unknown-linux-gnu
release: 1.87.0-nightly
LLVM version: 20.1.0

````

Command:
`/home/matthias/.rustup/toolchains/master/bin/rustc -Zcrate-attr=feature(generic_const_exprs)`

<details><summary><strong>Program output</strong></summary>
<p>

```
warning: the feature `generic_const_exprs` is incomplete and may not be safe to use and/or cause compiler crashes
 --> <crate attribute>:1:9
  |
1 | feature(generic_const_exprs)
  |         ^^^^^^^^^^^^^^^^^^^
  |
  = note: see issue #76560 <https://github.com/rust-lang/rust/issues/76560> for more information
  = note: `#[warn(incomplete_features)]` on by default

error[E0601]: `main` function not found in crate `mvce`
 --> /tmp/icemaker_global_tempdir.ffNkrQVFC034/rustc_testrunner_tmpdir_reporting.XReiXIhsphr5/mvce.rs:7:2
  |
7 | }
  |  ^ consider adding a `main` function to `/tmp/icemaker_global_tempdir.ffNkrQVFC034/rustc_testrunner_tmpdir_reporting.XReiXIhsphr5/mvce.rs`

error: using function pointers as const generic parameters is forbidden
 --> /tmp/icemaker_global_tempdir.ffNkrQVFC034/rustc_testrunner_tmpdir_reporting.XReiXIhsphr5/mvce.rs:1:22
  |
1 | trait Iter<const FN: fn() = { || {} }> {}
  |                      ^^^^
  |
  = note: the only supported types are integers, `bool`, and `char`

error[E0107]: trait takes 0 lifetime arguments but 1 lifetime argument was supplied
 --> /tmp/icemaker_global_tempdir.ffNkrQVFC034/rustc_testrunner_tmpdir_reporting.XReiXIhsphr5/mvce.rs:3:22
  |
3 | fn needs_iter<'a, T: Iter<'a, I> + ?Sized, I: 'a>(_: &T) {}
  |                      ^^^^ -- help: remove the lifetime argument
  |                      |
  |                      expected 0 lifetime arguments
  |
note: trait defined here, with 0 lifetime parameters
 --> /tmp/icemaker_global_tempdir.ffNkrQVFC034/rustc_testrunner_tmpdir_reporting.XReiXIhsphr5/mvce.rs:1:7
  |
1 | trait Iter<const FN: fn() = { || {} }> {}
  |       ^^^^

error: overly complex generic constant
 --> /tmp/icemaker_global_tempdir.ffNkrQVFC034/rustc_testrunner_tmpdir_reporting.XReiXIhsphr5/mvce.rs:1:29
  |
1 | trait Iter<const FN: fn() = { || {} }> {}
  |                             ^^-----^^
  |                               |
  |                               pointer casts are not allowed in generic constants
  |
  = help: consider moving this anonymous constant into a `const` function

error[E0107]: trait takes 0 lifetime arguments but 1 lifetime argument was supplied
 --> /tmp/icemaker_global_tempdir.ffNkrQVFC034/rustc_testrunner_tmpdir_reporting.XReiXIhsphr5/mvce.rs:5:17
  |
5 | fn test(x: &dyn Iter<'_, ()>) {
  |                 ^^^^ -- help: remove the lifetime argument
  |                 |
  |                 expected 0 lifetime arguments
  |
note: trait defined here, with 0 lifetime parameters
 --> /tmp/icemaker_global_tempdir.ffNkrQVFC034/rustc_testrunner_tmpdir_reporting.XReiXIhsphr5/mvce.rs:1:7
  |
1 | trait Iter<const FN: fn() = { || {} }> {}
  |       ^^^^

error[E0393]: the type parameter `FN` must be explicitly specified
 --> /tmp/icemaker_global_tempdir.ffNkrQVFC034/rustc_testrunner_tmpdir_reporting.XReiXIhsphr5/mvce.rs:5:17
  |
1 | trait Iter<const FN: fn() = { || {} }> {}
  | -------------------------------------- type parameter `FN` must be specified for this
...
5 | fn test(x: &dyn Iter<'_, ()>) {
  |                 ^^^^^^^^^^^^ missing reference to `FN`
  |
  = note: because the parameter default references `Self`, the parameter must be specified on the object type

error: internal compiler error: /rustc/17c1c329a5512d718b67ef6797538b154016cd34/compiler/rustc_middle/src/ty/relate.rs:189:18: impossible case reached: can't relate: UnevaluatedConst { def: DefId(0:5 ~ mvce[6cd1]::Iter::{constant#0}), args: [dyn [Binder { value: Trait(Iter<{type error}>), bound_vars: [] }] + '?3] } with {type error}


thread 'rustc' panicked at /rustc/17c1c329a5512d718b67ef6797538b154016cd34/compiler/rustc_middle/src/ty/relate.rs:189:18:
Box<dyn Any>
stack backtrace:
   0:     0x78000fd93754 - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::h058e0db08db4e308
   1:     0x78001041a2ac - core::fmt::write::h2896c353be594058
   2:     0x780011385a51 - std::io::Write::write_fmt::hb6d7e57799357016
   3:     0x78000fd935b2 - std::sys::backtrace::BacktraceLock::print::hf0f361819cf671ee
   4:     0x78000fd95dbe - std::panicking::default_hook::{{closure}}::ha203bbe1c0eab45f
   5:     0x78000fd95994 - std::panicking::default_hook::h241a0f75f184c349
   6:     0x78000eee2c77 - std[e8f7047bf536a035]::panicking::update_hook::<alloc[f5c9241a34fc739f]::boxed::Box<rustc_driver_impl[9b799b2b9a90c5eb]::install_ice_hook::{closure#1}>>::{closure#0}
   7:     0x78000fd96633 - std::panicking::rust_panic_with_hook::h05db98a78b8e5ccb
   8:     0x78000ef1e321 - std[e8f7047bf536a035]::panicking::begin_panic::<rustc_errors[c739bb8b16ec05ea]::ExplicitBug>::{closure#0}
   9:     0x78000ef12736 - std[e8f7047bf536a035]::sys::backtrace::__rust_end_short_backtrace::<std[e8f7047bf536a035]::panicking::begin_panic<rustc_errors[c739bb8b16ec05ea]::ExplicitBug>::{closure#0}, !>
  10:     0x78000ef12513 - std[e8f7047bf536a035]::panicking::begin_panic::<rustc_errors[c739bb8b16ec05ea]::ExplicitBug>
  11:     0x78000ef27ca1 - <rustc_errors[c739bb8b16ec05ea]::diagnostic::BugAbort as rustc_errors[c739bb8b16ec05ea]::diagnostic::EmissionGuarantee>::emit_producing_guarantee
  12:     0x78000f4f7906 - rustc_middle[85d9e04ee4b4f524]::util::bug::opt_span_bug_fmt::<rustc_span[c6f95d766fcdd5b1]::span_encoding::Span>::{closure#0}
  13:     0x78000f4e0b7a - rustc_middle[85d9e04ee4b4f524]::ty::context::tls::with_opt::<rustc_middle[85d9e04ee4b4f524]::util::bug::opt_span_bug_fmt<rustc_span[c6f95d766fcdd5b1]::span_encoding::Span>::{closure#0}, !>::{closure#0}
  14:     0x78000f4e0a0b - rustc_middle[85d9e04ee4b4f524]::ty::context::tls::with_context_opt::<rustc_middle[85d9e04ee4b4f524]::ty::context::tls::with_opt<rustc_middle[85d9e04ee4b4f524]::util::bug::opt_span_bug_fmt<rustc_span[c6f95d766fcdd5b1]::span_encoding::Span>::{closure#0}, !>::{closure#0}, !>
  15:     0x78000db333c0 - rustc_middle[85d9e04ee4b4f524]::util::bug::bug_fmt
  16:     0x7800105bc812 - <rustc_infer[19c2b605c1a9a127]::infer::at::At>::eq_trace::<rustc_type_ir[c72b4e181bbac7a3]::predicate::TraitRef<rustc_middle[85d9e04ee4b4f524]::ty::context::TyCtxt>>
  17:     0x78000d15e2c5 - <rustc_trait_selection[5a6c0c637d1e74d2]::traits::select::SelectionContext>::match_normalize_trait_ref
  18:     0x78000d12e13f - <rustc_trait_selection[5a6c0c637d1e74d2]::traits::select::SelectionContext>::candidate_from_obligation::{closure#0}::{closure#0}
  19:     0x78000cd60446 - <rustc_trait_selection[5a6c0c637d1e74d2]::traits::select::SelectionContext>::poly_select::{closure#0}
  20:     0x780010da98e7 - <rustc_trait_selection[5a6c0c637d1e74d2]::traits::fulfill::FulfillProcessor as rustc_data_structures[f70c9a795d99fea2]::obligation_forest::ObligationProcessor>::process_obligation
  21:     0x78001040f13f - <rustc_data_structures[f70c9a795d99fea2]::obligation_forest::ObligationForest<rustc_trait_selection[5a6c0c637d1e74d2]::traits::fulfill::PendingPredicateObligation>>::process_obligations::<rustc_trait_selection[5a6c0c637d1e74d2]::traits::fulfill::FulfillProcessor>
  22:     0x78001059c12d - <rustc_hir_typeck[6b1c2ee04c45e7a8]::fn_ctxt::FnCtxt>::confirm_builtin_call
  23:     0x780011016863 - <rustc_hir_typeck[6b1c2ee04c45e7a8]::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
  24:     0x78001100f94b - <rustc_hir_typeck[6b1c2ee04c45e7a8]::fn_ctxt::FnCtxt>::check_expr_block
  25:     0x78001101750f - <rustc_hir_typeck[6b1c2ee04c45e7a8]::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
  26:     0x7800106e85a0 - rustc_hir_typeck[6b1c2ee04c45e7a8]::check::check_fn
  27:     0x7800106f12bf - rustc_hir_typeck[6b1c2ee04c45e7a8]::typeck_with_inspect::{closure#0}
  28:     0x7800106ef388 - rustc_query_impl[86fa617db73557a2]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[86fa617db73557a2]::query_impl::typeck::dynamic_query::{closure#2}::{closure#0}, rustc_middle[85d9e04ee4b4f524]::query::erase::Erased<[u8; 8usize]>>
  29:     0x7800107c6b8c - rustc_query_system[b2c9516ca03027bf]::query::plumbing::try_execute_query::<rustc_query_impl[86fa617db73557a2]::DynamicConfig<rustc_data_structures[f70c9a795d99fea2]::vec_cache::VecCache<rustc_span[c6f95d766fcdd5b1]::def_id::LocalDefId, rustc_middle[85d9e04ee4b4f524]::query::erase::Erased<[u8; 8usize]>, rustc_query_system[b2c9516ca03027bf]::dep_graph::graph::DepNodeIndex>, false, false, false>, rustc_query_impl[86fa617db73557a2]::plumbing::QueryCtxt, false>
  30:     0x7800107c565c - rustc_query_impl[86fa617db73557a2]::query_impl::typeck::get_query_non_incr::__rust_end_short_backtrace
  31:     0x7800107c52ff - <rustc_middle[85d9e04ee4b4f524]::ty::context::TyCtxt>::par_hir_body_owners::<rustc_hir_analysis[de8b4722af89528a]::check_crate::{closure#3}>::{closure#0}
  32:     0x7800107c4979 - rustc_hir_analysis[de8b4722af89528a]::check_crate
  33:     0x7800107ce75c - rustc_interface[d30adf414c41a3da]::passes::run_required_analyses
  34:     0x7800113819fa - rustc_interface[d30adf414c41a3da]::passes::analysis
  35:     0x7800113819d9 - rustc_query_impl[86fa617db73557a2]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[86fa617db73557a2]::query_impl::analysis::dynamic_query::{closure#2}::{closure#0}, rustc_middle[85d9e04ee4b4f524]::query::erase::Erased<[u8; 0usize]>>
  36:     0x78001140c483 - rustc_query_system[b2c9516ca03027bf]::query::plumbing::try_execute_query::<rustc_query_impl[86fa617db73557a2]::DynamicConfig<rustc_query_system[b2c9516ca03027bf]::query::caches::SingleCache<rustc_middle[85d9e04ee4b4f524]::query::erase::Erased<[u8; 0usize]>>, false, false, false>, rustc_query_impl[86fa617db73557a2]::plumbing::QueryCtxt, false>
  37:     0x78001140c153 - rustc_query_impl[86fa617db73557a2]::query_impl::analysis::get_query_non_incr::__rust_end_short_backtrace
  38:     0x78001149117c - rustc_interface[d30adf414c41a3da]::passes::create_and_enter_global_ctxt::<core[f14dc92e3f316e7]::option::Option<rustc_interface[d30adf414c41a3da]::queries::Linker>, rustc_driver_impl[9b799b2b9a90c5eb]::run_compiler::{closure#0}::{closure#2}>::{closure#2}::{closure#0}
  39:     0x780011484a6b - rustc_interface[d30adf414c41a3da]::interface::run_compiler::<(), rustc_driver_impl[9b799b2b9a90c5eb]::run_compiler::{closure#0}>::{closure#1}
  40:     0x780011309c48 - std[e8f7047bf536a035]::sys::backtrace::__rust_begin_short_backtrace::<rustc_interface[d30adf414c41a3da]::util::run_in_thread_with_globals<rustc_interface[d30adf414c41a3da]::util::run_in_thread_pool_with_globals<rustc_interface[d30adf414c41a3da]::interface::run_compiler<(), rustc_driver_impl[9b799b2b9a90c5eb]::run_compiler::{closure#0}>::{closure#1}, ()>::{closure#0}, ()>::{closure#0}::{closure#0}, ()>
  41:     0x78001130a074 - <<std[e8f7047bf536a035]::thread::Builder>::spawn_unchecked_<rustc_interface[d30adf414c41a3da]::util::run_in_thread_with_globals<rustc_interface[d30adf414c41a3da]::util::run_in_thread_pool_with_globals<rustc_interface[d30adf414c41a3da]::interface::run_compiler<(), rustc_driver_impl[9b799b2b9a90c5eb]::run_compiler::{closure#0}>::{closure#1}, ()>::{closure#0}, ()>::{closure#0}::{closure#0}, ()>::{closure#1} as core[f14dc92e3f316e7]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  42:     0x78001130aa2f - std::sys::pal::unix::thread::Thread::new::thread_start::had6426447ba59d7e
  43:     0x78000b6a370a - <unknown>
  44:     0x78000b727aac - <unknown>
  45:                0x0 - <unknown>

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: please make sure that you have updated to the latest nightly

note: rustc 1.87.0-nightly (17c1c329a 2025-02-19) running on x86_64-unknown-linux-gnu

note: compiler flags: -Z crate-attr=feature(generic_const_exprs) -Z dump-mir-dir=dir

query stack during panic:
#0 [typeck] type-checking `test`
#1 [analysis] running analysis passes on this crate
end of query stack
error: aborting due to 7 previous errors; 1 warning emitted

Some errors have detailed explanations: E0107, E0393, E0601.
For more information about an error, try `rustc --explain E0107`.

```

</p>
</details>

@rustbot label +F-generic_const_exprs

### LINKED ISSUE #137514: ICE: `args not compatible with generics for ..`
auto-reduced (treereduce-rust):
````rust
#![feature(generic_const_exprs)]

trait Bar<const N: usize> {}

trait BB = Bar<{ 1i32 + 1 }>;

fn foo(x: &dyn BB) {}

````

original:
````rust
#![allow(incomplete_features)]
#![feature(generic_const_exprs)]
#![feature(trait_alias)]

trait Bar<const N: usize> {}

trait BB = Bar<{ 1i32 + 1 }>;

fn foo(x: &dyn BB) {}
//~^ ERROR the trait alias `BB` is not dyn compatible [E0038]

fn main(&String) {}

````

Version information
````
rustc 1.87.0-dev
binary: rustc
commit-hash: unknown
commit-date: unknown
host: x86_64-unknown-linux-gnu
release: 1.87.0-dev
LLVM version: 20.1.0

````

Possibly related line of code:
https://github.com/rust-lang/rust/blob/unknown/compiler/rustc_middle/src/ty/context.rs#L2724-L2736

Command:
`/home/gh-matthiaskrgr/.rustup/toolchains/local-debug-assertions/bin/rustc `

Version information
````
rustc 1.87.0-dev
binary: rustc
commit-hash: b522e7c5ea8334fbccb9dd7f9b33759304743fd0
commit-date: unknown
host: x86_64-unknown-linux-gnu
release: 1.87.0-dev
LLVM version: 20.1.0

````

Possibly related line of code:
https://github.com/rust-lang/rust/blob/b522e7c5ea8334fbccb9dd7f9b33759304743fd0/compiler/rustc_middle/src/ty/context.rs#L2724-L2736

Command:
`/home/gh-matthiaskrgr/.rustup/toolchains/local-debug-assertions/bin/rustc `

@rustbot label +F-generic_const_exprs +F-trait_alias

### PR DESCRIPTION
**Pull request by fmease**
Under feature `min_generic_const_args` (mGCA) (rust-lang/rust#132980), render traits with non-parametrized type-level associated constants (i.e., `#[type_const]` ones) dyn compatible but force the user to specify all type-level associated consts in the trait object type via bindings (either directly, via supertrait bounds and/or behind trait aliases) just like associated types, their sibling.

Fixes rust-lang/rust#130300 (feature request).
Fixes rust-lang/rust#136063 (bug).
Fixes rust-lang/rust#137260 (bug).
Fixes rust-lang/rust#137514 (bug).

While I'm accounting for most illegal `Self` references via const projections & params, I'm intentionally ignoring RUST-123140 (and duplicates) in this PR which is to be tackled some other time.

Additional context: Crate `rustc-demangle` had to be updated to fix v0 demangling. I've patched it in PR https://github.com/rust-lang/rustc-demangle/pull/87 which was was released in version 0.1.27 via PR https://github.com/rust-lang/rustc-demangle/pull/88.

### CODE REVIEW

File: compiler/rustc_hir_analysis/src/hir_ty_lowering/dyn_trait.rs
Comment (fmease) [inline compiler/rustc_hir_analysis/src/hir_ty_lowering/dyn_trait.rs]: Update commit message: Refer to those assoc consts as *type-level* ones.

File: tests/ui/const-generics/associated-const-bindings/dyn-compat-self-const-projections-in-methods.rs
Comment (fmease) [inline tests/ui/const-generics/associated-const-bindings/dyn-compat-self-const-projections-in-methods.rs:1]: This is the test that required me to fix symbol mangling & to temporarily include PR RUST-150799. I would have to temporarily downgrade it to `//@ check-pass`, `//@ build-pass` or `//@ ignore-test` if I didn't patch symbol mangling in this PR but in a follow-up one @ Boxy.

File: compiler/rustc_hir_analysis/src/hir_ty_lowering/dyn_trait.rs [hunk 1]
```diff
@@ -301,35 +298,33 @@ impl<'tcx> dyn HirTyLowerer<'tcx> + '_ {
...
-        let mut missing_assoc_types = FxIndexSet::default();
-        let projection_bounds: Vec<_> = ordered_associated_types
+        // The user has to constrain all associated types & consts via bindings unless the
+        // corresponding associated item has a `where Self: Sized` clause. This can be done
+        // in the `dyn Trait` directly, in the supertrait bounds or behind trait aliases.
+        //
+        // Collect all associated items that weren't specified and compute the list of projection
+        // bounds which we'll later turn into existential ones.
+        // For why we keep projections whose associated item has a `Self: Sized` bound,
+        // see <https://github.com/rust-lang/rust/pull/140684>.
```
Comment (BoxyUwU) [inline compiler/rustc_hir_analysis/src/hir_ty_lowering/dyn_trait.rs]: can we say sth like "we keep them around so that we the resulting ty after HIR ty lowering still contains the user written types on the rhs of the assoc item binding, see <https://github.com/...>". clicking the link is annoying :sweat_smile:

File: tests/ui/const-generics/associated-const-bindings/dyn-compat-non-type-assoc-const.rs [hunk 2]
```diff
@@ -0,0 +1,15 @@
...
+#![feature(min_generic_const_args)]
+#![expect(incomplete_features)]
+
+trait Trait {
+    const K: usize;
+    //~^ NOTE it contains associated const `K` that's not marked `#[type_const]`
+}
+
+fn main() {
+    let _: dyn Trait; //~ ERROR the trait `Trait` is not dyn compatible
```
Comment (BoxyUwU) [inline tests/ui/const-generics/associated-const-bindings/dyn-compat-non-type-assoc-const.rs:14]: can you add another case with `dyn Trait<K = 0>` and check that errors

File: tests/ui/const-generics/associated-const-bindings/dyn-compat-symbol-mangling.rs [hunk 3]
```diff
@@ -0,0 +1,27 @@
+// Ensure that we can successfully mangle & demangle trait object types w/ assoc const bindings.
+
+// FIXME(fmease): Legacy mangling still crashes.
```
Comment (BoxyUwU) [inline tests/ui/const-generics/associated-const-bindings/dyn-compat-symbol-mangling.rs]: FIXME(mgca)

i wanna know this when looking at mgca issues not jsut when looking at your FIXMEs :3

File: tests/ui/const-generics/associated-const-bindings/dyn-compat-self-const-projections.rs [hunk 4]
```diff
@@ -0,0 +1,56 @@
+// While mentioning `Self` in the method signature of dyn compatible traits is generally forbidden
+// due to type erasure, we can make an exception for const projections from `Self` where the trait
+// is the trait in question or a supertrait thereof. That's sound because we force users to specify
+// all associated consts in the trait object type, so the projections are all normalizable.
+//
+// Check that we can define & use dyn compatible traits that reference `Self` const projections.
+
+// This is a run-pass test to ensure that codegen can actually deal with such method instances
+// (e.g., const projections normalize flawlessly to something concrete, symbols get mangled
+// properly properly) and to ensure that the generated code "received" the correct values from
```
Comment (BoxyUwU) [inline tests/ui/const-generics/associated-const-bindings/dyn-compat-self-const-projections.rs]: properly properly

File: compiler/rustc_hir_analysis/src/hir_ty_lowering/errors.rs [hunk 5]
```diff
@@ -1010,97 +1025,114 @@ impl<'tcx> dyn HirTyLowerer<'tcx> + '_ {
...
-            .collect::<Vec<String>>();
+            .collect();
         names.sort();
         let names = names.join(", ");
 
+        let descr = match descr.unwrap() {
+            // FIXME(fmease): Create `ty::AssocTag::descr`.
+            Descr::Tag(ty::AssocTag::Type) => "associated type",
+            Descr::Tag(ty::AssocTag::Const) => "associated constant",
+            _ => "associated item",
```
Comment (BoxyUwU) [inline compiler/rustc_hir_analysis/src/hir_ty_lowering/errors.rs]: exhaustive match + unreachable arm for `ty::AssocTag::Fn`?

File: compiler/rustc_hir_analysis/src/hir_ty_lowering/errors.rs [hunk 6]
```diff
@@ -1010,97 +1025,114 @@ impl<'tcx> dyn HirTyLowerer<'tcx> + '_ {
...
+                // The user wrote `Trait`, so we don't have a term we can suggest, but at least we
+                // can clue them to the correct syntax `Trait<Item = /* ... */>`.
+                format!("{}<{}>", snippet, bindings.join(", "))
             };
             suggestions.push((principal_span, code));
         } else if dupes {
             where_constraints.push(principal_span);
         }
 
+        // FIXME(fmease): Get rid of this note outright, it is utter nonsense! Maybe mentioning
```
Comment (BoxyUwU) [inline compiler/rustc_hir_analysis/src/hir_ty_lowering/errors.rs]: snarky!

**Review by BoxyUwU — APPROVED** [review]
I've looked over all the commits, got some nits and you've still got the other thing to fix with type consts' types having Self in them until approval though

*[View changes since this review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/rust/150843/a6acf0f07f0ed1c12e26dc0db3b9bf1d0504a0bb..7e656f393784f0707b61fbeb35bebd55bb256159)*

File: compiler/rustc_hir_analysis/src/hir_ty_lowering/errors.rs (hunk 5 above)
Comment (fmease) [reply compiler/rustc_hir_analysis/src/hir_ty_lowering/errors.rs]: This gets replaced with `Descr::Tag(tag) => tag.descr(), Descr::Item => "associated item"` in the next commit anyway.

File: compiler/rustc_hir_analysis/src/hir_ty_lowering/dyn_trait.rs (hunk 1 above)
Comment (fmease) [reply compiler/rustc_hir_analysis/src/hir_ty_lowering/dyn_trait.rs]: I now say:

> We intentionally keep around projections whose associated item has a `Self: Sized`
> bound in order to be able to wfcheck the RHS, allow the RHS to constrain generic
> parameters and to imply bounds.
> See also <https://github.com/rust-lang/rust/pull/140684>.

https://github.com/rust-lang/rust/pull/150843/files#diff-c15dc5fc785375aaa6be6b5168da389dbcf933c328a8bace5fdb9950bf2d40a1R310-R313

File: compiler/rustc_hir_analysis/src/hir_ty_lowering/errors.rs (hunk 6 above)
Comment (fmease) [reply compiler/rustc_hir_analysis/src/hir_ty_lowering/errors.rs]: Reworded.

**Comment by fmease** [comment]
Thx, will address once I'm on my machine again in ~1h.
