### PR TITLE
Fix a leak in `DiagnosticBuilder::into_diagnostic`.

### LINKED ISSUE #69600: memory leak in DiagnosticBuilder.into_diagnostic()
This code leaks the `Box` at `self.0`:

https://github.com/rust-lang/rust/blob/d3c79346a3e7ddbb5fb417810f226ac5a9209007/src/librustc_errors/diagnostic_builder.rs#L141-L144

The leak was introduced in 2fcd870711ce267c79408ec631f7eba8e0afcdf6. cc @nnethercote

### PR DESCRIPTION
**Pull request by nnethercote**
Fixes #69600.

r? @Centril

### CODE REVIEW

**Comment by nnethercote** [comment]
I did a local perf run and the change had absolutely no effect on perf, as you'd hope. I suspect the code in question isn't even run unless an error is issued, which is relatively rare.

File: src/librustc_errors/diagnostic_builder.rs [hunk 1]
```diff
@@ -135,13 +135,9 @@ impl<'a> DiagnosticBuilder<'a> {
         }
 
         let handler = self.0.handler;
+        let dummy = Diagnostic::new(Level::Help, "");
+        let diagnostic = std::mem::replace(&mut self.0.diagnostic, dummy);
```
Comment (dwrensha) [inline src/librustc_errors/diagnostic_builder.rs]: Shouldn't we do `self.cancel()` here, to prevent the dummy diagnostic from being emitted? And maybe the `Level` should be `Bug`, so that we catch if it does get emitted?

Comment (Centril) [reply src/librustc_errors/diagnostic_builder.rs]: `Diagnostic` does not have a `Drop` impl and we are consuming `self` by value so I don't see how it matters.

**Comment by Centril** [comment]
Pretty unfortunate that we cannot just do `let DiagnosticBuilderInner { handler, diagnostic, .. } = *self.0;` -- one wonders whether that language restriction causes more harm than good...

r=me when https://github.com/rust-lang/rust/pull/69628#discussion_r386173221 has resolved itself.

File: src/librustc_errors/diagnostic_builder.rs (hunk 1 above)
Comment (dwrensha) [reply src/librustc_errors/diagnostic_builder.rs]: I just tested this code out on the input consisting of a single closing closing brace:
```rust
}
```

and I get: "internal compiler error: the following error was constructed but not emitted"

Comment (Centril) [reply src/librustc_errors/diagnostic_builder.rs]: Hmm yes, good point. That is happening because `Drop` is called on `self`, so we do indeed have to do `self.cancel();`.

Comment (nnethercote) [reply src/librustc_errors/diagnostic_builder.rs]: Bleh, this code caused lots of test failures. I fixed it by changing the level to `Level::Cancelled`, which avoids the need for the explicit `self.cancel()` call. But I forgot to `git commit -a --amend`... I really wish git wouldn't let you push when uncommitted changes are present. I have now pushed that change.

**Comment by Centril** [comment]
@nnethercote btw, `Diagnostic::new` will always allocate, so if you are concerned about that, which you could reasonably not be, then a struct literal might be more efficient.

**Comment by nnethercote** [comment]
Thanks for the tip! The code is cold enough that the additional allocation doesn't matter, I think. But let's double-check that...

@bors try @rust-timer queue

**Comment by nnethercote** [comment]
Yep, the perf impact is just noise.

@bors r=Centril
@bors rollup=always

**Comment by nnethercote** [comment]
Should this be backported onto beta?

**Comment by pnkfelix** [comment]
beta-accepted
