### PR TITLE
std: Force `Instant::now()` to be monotonic

### LINKED ISSUE #48514: thread 'rustc' panicked at 'other was less than the current instant'
I created hello.rs file with copy of example on https://www.rust-lang.org/en-US/
then

rustc hello.rs 
error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.20.0 running on x86_64-unknown-openbsd

thread 'rustc' panicked at 'other was less than the current instant', /usr/obj/ports/rust-1.20.0/rustc-1.20.0-src/src/libstd/sys/unix/time.rs:276:16
note: Run with `RUST_BACKTRACE=1` for a backtrace.

I'm on OpenBSD 6.2 amd64 with rust-1.20.0

### LINKED ISSUE #49281: unexpected panic while compiling firefox on arm64
Hi, I see this strange error while trying to compile firefox-59.0.1 with rust-1.23 on arm64 laptop running gentoo linux. It says, my bug report would be appreciated. I'd also appreciate any feedback.

I would be happy to provide any additional information.

```
   Compiling quote v0.3.15
   Compiling peeking_take_while v0.1.2
   Compiling glob v0.2.11
error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.23.0-dev running on aarch64-unknown-linux-gnu

note: run with `RUST_BACKTRACE=1` for a backtrace

thread 'rustc' panicked at 'other was less than the current instant', src/libstd/sys/unix/time.rs:284:16
stack backtrace:
   0:       0x7f9e7de973 - rust_metadata_std_5958eddae63d6947e0733521fc5435ed
   1:       0x7f9e7da9d7 - rust_metadata_std_5958eddae63d6947e0733521fc5435ed
   2:       0x7f9e7e9f3f - rust_metadata_std_5958eddae63d6947e0733521fc5435ed
   3:       0x7f9e7e9c4f - rust_metadata_std_5958eddae63d6947e0733521fc5435ed
   4:       0x7f9e7ea443 - std::panicking::rust_panic_with_hook::h22b280fc4fc0de87
   5:       0x7f9e7ea303 - rust_metadata_std_5958eddae63d6947e0733521fc5435ed
   6:       0x7f9e7d9eb7 - std::time::Instant::elapsed::hf802fe319eded9b8
   7:       0x7f9da24283 - <unknown>
   8:       0x7f9da4965b - <unknown>
   9:       0x7f9cd3199b - rust_metadata_rustc_3ea30897d9dddf7b5fa3a6c2523637e7
  10:       0x7f9cf028f7 - rust_metadata_rustc_3ea30897d9dddf7b5fa3a6c2523637e7
  11:       0x7f9cc1cd2b - rust_metadata_rustc_3ea30897d9dddf7b5fa3a6c2523637e7
  12:       0x7f9d09b153 - <unknown>
  13:       0x7f9cd31a33 - rust_metadata_rustc_3ea30897d9dddf7b5fa3a6c2523637e7
  14:       0x7f9cd320ff - rustc::ty::maps::<impl rustc::ty::maps::queries::symbol_name<'tcx>>::try_get::hf71dec19792cb774
  15:       0x7f9ce83073 - rustc::ty::maps::TyCtxtAt::symbol_name::hf81eb960dfd03136
  16:       0x7f9d0ae4f3 - rustc::ty::maps::<impl rustc::ty::context::TyCtxt<'a, 'tcx, 'lcx>>::symbol_name::hd40df66149759931
  17:       0x7f9d984003 - <unknown>
  18:       0x7f9d9609c7 - <unknown>
  19:       0x7f9d984fc3 - <unknown>
  20:       0x7f9cd7a433 - rust_metadata_rustc_3ea30897d9dddf7b5fa3a6c2523637e7
  21:       0x7f9cf0ad07 - rust_metadata_rustc_3ea30897d9dddf7b5fa3a6c2523637e7
  22:       0x7f9cc1e81b - rust_metadata_rustc_3ea30897d9dddf7b5fa3a6c2523637e7
  23:       0x7f9d081dbb - <unknown>
  24:       0x7f9cd7a4af - rust_metadata_rustc_3ea30897d9dddf7b5fa3a6c2523637e7
  25:       0x7f9cd7a9df - rustc::ty::maps::<impl rustc::ty::maps::queries::exported_symbols<'tcx>>::try_get::h7cd7159316d987b4
  26:       0x7f9ce870e3 - rustc::ty::maps::TyCtxtAt::exported_symbols::h35b6eb150f9aa7b2
  27:       0x7f9d0af0df - rustc::ty::maps::<impl rustc::ty::context::TyCtxt<'a, 'tcx, 'lcx>>::exported_symbols::h69dd1a8087b4ddb7
  28:       0x7f9da0be0f - <unknown>
  29:       0x7f9da0b253 - rustc_trans::back::write::start_async_translation::hd810efc5779dac71
  30:       0x7f9da4ea93 - rustc_trans::base::trans_crate::h1ab479cd2e56d359
  31:       0x7f9d9f930f - <rustc_trans::LlvmTransCrate as rustc_trans_utils::trans_crate::TransCrate>::trans_crate::hf0c11cb959ccfc0e
  32:       0x7f9e9b987f - <unknown>
  33:       0x7f9e949f1b - <unknown>
  34:       0x7f9e9a949f - <unknown>
  35:       0x7f9e9a1967 - <unknown>
  36:       0x7f9e99ed5f - <unknown>
  37:       0x7f9e910633 - <unknown>
  38:       0x7f9e9462ff - rustc_driver::driver::compile_input::h10487c1bd068aca0
  39:       0x7f9e9952bb - rustc_driver::run_compiler::h90c48c1cfea93e36
  40:       0x7f9e92682b - <unknown>
  41:       0x7f9e7f5d17 - __rust_maybe_catch_panic
  42:       0x7f9e988733 - <unknown>
  43:       0x7f9e7e8e6f - rust_metadata_std_5958eddae63d6947e0733521fc5435ed
  44:       0x7f9c3f25bb - <unknown>

error: Could not compile `glob`.
warning: build failed, waiting for other jobs to finish...
error: build failed
gmake[4]: *** [/var/tmp/portage/www-client/firefox-59.0.1/work/mozilla-release-3db9e3d52b17563efca181ccbb50deb8660c59ae/config/rules.mk:972: force-cargo-library-build] Error 101
gmake[3]: *** [/var/tmp/portage/www-client/firefox-59.0.1/work/mozilla-release-3db9e3d52b17563efca181ccbb50deb8660c59ae/config/recurse.mk:73: toolkit/library/rust/target] Error 2
gmake[2]: *** [/var/tmp/portage/www-client/firefox-59.0.1/work/mozilla-release-3db9e3d52b17563efca181ccbb50deb8660c59ae/config/recurse.mk:33: compile] Error 2
gmake[1]: *** [/var/tmp/portage/www-client/firefox-59.0.1/work/mozilla-release-3db9e3d52b17563efca181ccbb50deb8660c59ae/config/rules.mk:434: default] Error 2
gmake: *** [client.mk:168: build] Error 2
0 compiler warnings present.
```

### LINKED ISSUE #56612: Instant::now can go backward
As in https://github.com/rust-lang/rust/issues/51648#issuecomment-441063768.

I've seen "specified instant was later than self" panics in the wild, in particular on Windows (32-bit x86). Googling reveals stuff like https://stackoverflow.com/questions/44020619/queryperformancecounter-on-multi-core-processor-under-windows-10-behaves-erratic which suggests that QueryPerformanceCounter can't really be relied on... frustratingly.

Perhaps libstd should work around this and enforce that `Instant::now()` never go backward (with an atomic global, or something?)

### LINKED ISSUE #56940: ICE 'specified instant was less than self' and BorrowMutError on aarch64-linux-unknown-gnu
When compiling code on an aarch64 system (a [pine a64](https://www.pine64.org/?product=pine-a64-lts)) I get a compiler panic 'specified instant was less than self', which I'm guessing is because the accuracy of the timer given on this system isn't very reliable and the `std::time::Instant` guarantee that a new one won't be earlier than an old one isn't upheld. This problem occurs somewhat reliably. Usually several crates will compile successfully in a long compile job before a panic happens. This problem has been happening to me since around 1.26 nightly.

Here's a backtrace I get
```
thread 'main' panicked at 'specified instant was later than self', libstd/sys/unix/time.rs:292:17
stack backtrace:                                                                                                
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace                                                 
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49                                                   
   1: std::sys_common::backtrace::print                                                                         
             at libstd/sys_common/backtrace.rs:71                                                               
             at libstd/sys_common/backtrace.rs:59                                                               
   2: std::panicking::default_hook::{{closure}}                                                                 
             at libstd/panicking.rs:211                                                                         
   3: std::panicking::default_hook                                                                              
             at libstd/panicking.rs:227                                                                         
   4: rustc::util::common::panic_hook                                                                           
   5: std::panicking::rust_panic_with_hook                                                                      
             at libstd/panicking.rs:480                                                                         
   6: std::panicking::begin_panic                                                                               
             at libstd/panicking.rs:410                                                                         
   7: std::sys::unix::time::inner::Instant::sub_instant::{{closure}}                                            
             at libstd/sys/unix/time.rs:292                                                                     
   8: std::time::Instant::elapsed                                                                               
             at libcore/result.rs:774                                                                           
             at libstd/sys/unix/time.rs:291                                                                     
             at libstd/time.rs:185                                                                              
             at libstd/time.rs:250                                                                              
             at libstd/time.rs:209                                                                              
   9: rustc::util::profiling::SelfProfiler::start_activity                                                      
  10: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt<'a, 'gcx, 'tcx>>::ensure_query               
  11: rustc::ty::util::<impl rustc::ty::context::TyCtxt<'a, 'gcx, 'tcx>>::calculate_dtor                        
  12: rustc_typeck::check::adt_destructor                                                                       
  13: rustc::ty::query::<impl rustc::ty::query::config::QueryAccessors<'tcx> for rustc::ty::query::queries::adt_destructor<'tcx>>::compute
  14: rustc::dep_graph::graph::DepGraph::with_task_impl                                                         
  15: <rustc::ty::query::plumbing::JobOwner<'a, 'tcx, Q>>::start                                                
  16: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt<'a, 'gcx, 'tcx>>::force_query_with_job       
  17: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt<'a, 'gcx, 'tcx>>::get_query                  
  18: rustc_typeck::check::check_item_type                                                                      
  19: rustc::hir::Crate::visit_all_item_likes                                                                   
  20: rustc_typeck::check::check_item_types                                                                     
  21: rustc::util::common::time                                                                                 
  22: rustc_typeck::check_crate                                                                                 
  23: rustc::ty::context::tls::enter_context                                                                    
  24: <std::thread::local::LocalKey<T>>::with                                                                   
  25: rustc::ty::context::TyCtxt::create_and_enter                                                              
  26: rustc_driver::driver::compile_input                                                                       
  27: rustc_driver::run_compiler_with_pool                                                                      
  28: rustc_driver::driver::spawn_thread_pool                                                                   
  29: rustc_driver::run_compiler                                                                                
  30: <scoped_tls::ScopedKey<T>>::set                                                                           
  31: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once                           
  32: __rust_maybe_catch_panic                                                                                  
             at libpanic_unwind/lib.rs:102                                                                      
  33: rustc_driver::run                                                                                         
  34: rustc_driver::main                                                                                        
  35: std::rt::lang_start::{{closure}}                                                                          
  36: std::panicking::try::do_call                                                                              
             at libstd/rt.rs:59                                                                                 
             at libstd/panicking.rs:310                                                                         
  37: __rust_maybe_catch_panic                                                                                  
             at libpanic_unwind/lib.rs:102                                                                      
  38: std::rt::lang_start_internal                                                                              
             at libstd/panicking.rs:289                                                                         
             at libstd/panic.rs:392                                                                             
             at libstd/rt.rs:58                                                                                 
  39: main                                                                                                      
  40: __libc_start_main                                                                                         
query stack during panic:                                                                                       
#0 [adt_destructor] processing `de::impls::PathVisitor`                                                         
end of query stack
```

When I first tried compiling with `-j 1` I instantly got the same panic plus a `BorrowMutError`, shown next:

```
thread 'main' panicked at 'specified instant was later than self', libstd/sys/unix/time.rs:292:17               
stack backtrace:                                                                                                
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace                                                 
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49                                                   
   1: std::sys_common::backtrace::print                                                                         
             at libstd/sys_common/backtrace.rs:71                                                               
             at libstd/sys_common/backtrace.rs:59                                                               
   2: std::panicking::default_hook::{{closure}}                                                                 
             at libstd/panicking.rs:211                                                                         
   3: std::panicking::default_hook                                                                              
             at libstd/panicking.rs:227                                                                         
   4: rustc::util::common::panic_hook                                                                           
   5: std::panicking::rust_panic_with_hook                                                                      
             at libstd/panicking.rs:480                                                                         
   6: std::panicking::begin_panic                                                                               
             at libstd/panicking.rs:410                                                                         
   7: std::sys::unix::time::inner::Instant::sub_instant::{{closure}}                                            
             at libstd/sys/unix/time.rs:292                                                                     
   8: std::time::Instant::elapsed                                                                               
             at libcore/result.rs:774                                                                           
             at libstd/sys/unix/time.rs:291                                                                     
             at libstd/time.rs:185                                                                              
             at libstd/time.rs:250                                                                              
             at libstd/time.rs:209                                                                              
   9: rustc::util::profiling::SelfProfiler::start_activity                                                      
  10: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt<'a, 'gcx, 'tcx>>::force_query_with_job       
  11: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt<'a, 'gcx, 'tcx>>::get_query                  
  12: rustc::traits::specialize::specialization_graph::Children::insert_blindly                                 
  13: rustc::traits::specialize::specialization_graph_provider                                                  
  14: rustc::ty::query::<impl rustc::ty::query::config::QueryAccessors<'tcx> for rustc::ty::query::queries::specialization_graph_of<'tcx>>::compute
  15: rustc::dep_graph::graph::DepGraph::with_task_impl                                                         
  16: <rustc::ty::query::plumbing::JobOwner<'a, 'tcx, Q>>::start                                                
  17: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt<'a, 'gcx, 'tcx>>::force_query_with_job       
  18: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt<'a, 'gcx, 'tcx>>::get_query                  
  19: rustc::traits::specialize::find_associated_item                                                           
  20: rustc::ty::instance::Instance::resolve                                                                    
  21: rustc_mir::monomorphize::collector::visit_fn_use                                                          
  22: <rustc_mir::monomorphize::collector::MirNeighborCollector<'a, 'tcx> as rustc::mir::visit::Visitor<'tcx>>::visit_terminator_kind
  23: rustc_mir::monomorphize::collector::collect_items_rec                                                     
  24: rustc_mir::monomorphize::collector::collect_items_rec                                                     
  25: rustc_mir::monomorphize::collector::collect_items_rec                                                     
  26: rustc_mir::monomorphize::collector::collect_items_rec                                                     
  27: rustc_mir::monomorphize::collector::collect_items_rec                                                     
  28: rustc_mir::monomorphize::collector::collect_items_rec                                                     
  29: rustc_mir::monomorphize::collector::collect_items_rec                                                     
  30: rustc_mir::monomorphize::collector::collect_items_rec                                                     
  31: rustc_mir::monomorphize::collector::collect_items_rec                                                     
  32: rustc_mir::monomorphize::collector::collect_items_rec                                                     
  33: rustc_mir::monomorphize::collector::collect_items_rec                                                     
  34: rustc_mir::monomorphize::collector::collect_items_rec                                                     
  35: rustc_mir::monomorphize::collector::collect_items_rec                                                     
  36: rustc_mir::monomorphize::collector::collect_items_rec                                                     
  37: rustc_mir::monomorphize::collector::collect_crate_mono_items::{{closure}}                                 
  38: rustc_mir::monomorphize::collector::collect_crate_mono_items                                              
  39: rustc::util::common::time                                                                                 
  40: rustc_codegen_llvm::base::collect_and_partition_mono_items                                                
  41: rustc::ty::query::<impl rustc::ty::query::config::QueryAccessors<'tcx> for rustc::ty::query::queries::collect_and_partition_mono_items<'tcx>>::compute
  42: rustc::dep_graph::graph::DepGraph::with_task_impl                                                         
  43: <rustc::ty::query::plumbing::JobOwner<'a, 'tcx, Q>>::start                                                
  44: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt<'a, 'gcx, 'tcx>>::force_query_with_job       
  45: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt<'a, 'gcx, 'tcx>>::get_query                  
  46: rustc_codegen_llvm::back::symbol_export::exported_symbols_provider_local                                  
  47: rustc::ty::query::<impl rustc::ty::query::config::QueryAccessors<'tcx> for rustc::ty::query::queries::exported_symbols<'tcx>>::compute
  48: rustc::dep_graph::graph::DepGraph::with_task_impl                                                         
  49: <rustc::ty::query::plumbing::JobOwner<'a, 'tcx, Q>>::start                                                
  50: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt<'a, 'gcx, 'tcx>>::force_query_with_job       
  51: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt<'a, 'gcx, 'tcx>>::get_query                  
  52: rustc_metadata::encoder::encode_metadata                                                                  
  53: rustc_codegen_llvm::base::write_metadata                                                                  
  54: rustc::util::common::time                                                                                 
  55: rustc_codegen_llvm::base::codegen_crate                                                                   
  56: <rustc_codegen_llvm::LlvmCodegenBackend as rustc_codegen_utils::codegen_backend::CodegenBackend>::codegen_crate
  57: rustc::util::common::time                                                                                 
  58: rustc_driver::driver::phase_4_codegen                                                                     
  59: rustc_driver::driver::compile_input::{{closure}}                                                          
  60: rustc::ty::context::tls::enter_context                                                                    
  61: <std::thread::local::LocalKey<T>>::with                                                                   
  62: rustc::ty::context::TyCtxt::create_and_enter                                                              
  63: rustc_driver::driver::compile_input                                                                       
  64: rustc_driver::run_compiler_with_pool                                                                      
  65: rustc_driver::driver::spawn_thread_pool                                                                   
  66: rustc_driver::run_compiler                                                                                
  67: <scoped_tls::ScopedKey<T>>::set                                                                           
  68: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once                           
  69: __rust_maybe_catch_panic                                                                                  
             at libpanic_unwind/lib.rs:102                                                                      
  70: rustc_driver::run                                                                                         
  71: rustc_driver::main                                                                                        
  72: std::rt::lang_start::{{closure}}                                                                          
  73: std::panicking::try::do_call                                                                              
             at libstd/rt.rs:59                                                                                 
             at libstd/panicking.rs:310                                                                         
  74: __rust_maybe_catch_panic                                                                                  
             at libpanic_unwind/lib.rs:102                                                                      
  75: std::rt::lang_start_internal                                                                              
             at libstd/panicking.rs:289                                                                         
             at libstd/panic.rs:392                                                                             
             at libstd/rt.rs:58                                                                                 
  76: main                                                                                                      
  77: __libc_start_main                                                                                         
query stack during panic:                                                                                       
thread 'main' panicked at 'already borrowed: BorrowMutError', libcore/result.rs:1009:5                          
stack backtrace:                                                                                                
   0:       0x7fa19be11b - std::sys::unix::backtrace::tracing::imp::unwind_backtrace::h4d215aadcaa52ebe         
                               at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49                                 
   1:       0x7fa19a7737 - std::sys_common::backtrace::print::h82720234d7357f67                                 
                               at libstd/sys_common/backtrace.rs:71                                             
                               at libstd/sys_common/backtrace.rs:59                                             
   2:       0x7fa1999c1f - std::panicking::default_hook::{{closure}}::h1cc6e7f2777dc182                         
                               at libstd/panicking.rs:211                                                       
   3:       0x7fa19999d7 - std::panicking::default_hook::hcfca097092607890                                      
                               at libstd/panicking.rs:227                                                       
   4:       0x7fa040ec77 - rustc::util::common::panic_hook::h306b1084c22d63a7                                   
   5:       0x7fa199a34b - std::panicking::rust_panic_with_hook::hb4c40b3721cfbfb0                              
                               at libstd/panicking.rs:480                                                       
   6:       0x7fa1999f57 - std::panicking::continue_panic_fmt::h7e84a0a182ce9c2d                                
                               at libstd/panicking.rs:390                                                       
   7:       0x7fa1999e63 - rust_begin_unwind                                                                    
                               at libstd/panicking.rs:325                                                       
   8:       0x7fa19da90b - core::panicking::panic_fmt::h0c93626b89c38af6                                        
                               at libcore/panicking.rs:77                                                       
   9:       0x7fa039f93f - core::result::unwrap_failed::h0f2804ccdceb1057                                       
  10:       0x7fa028eb93 - rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt<'a, 'gcx, 'tcx>>::get_query::haa28e0723665833b
  11:       0x7fa01b7cd7 - rustc::ty::item_path::<impl rustc::ty::context::TyCtxt<'a, 'gcx, 'tcx>>::push_item_path::hf208625ff68cfb69
  12:       0x7fa04ed63b - <M as rustc::ty::query::config::QueryDescription<'tcx>>::describe::h89c6f088ab3a41ca 
  13:       0x7fa041bb27 - rustc::ty::query::Query::describe::h329b8f02606e812d                                 
  14:       0x7fa012152f - rustc::ty::context::tls::with_context_opt::h2126d91cee343ea8                         
  15:       0x7fa040ed03 - rustc::util::common::panic_hook::h306b1084c22d63a7                                   
  16:       0x7fa199a34b - std::panicking::rust_panic_with_hook::hb4c40b3721cfbfb0                              
                               at libstd/panicking.rs:480                                                       
  17:       0x7fa199a163 - std::panicking::begin_panic::h795f8aed5d383695                                       
                               at libstd/panicking.rs:410                                                       
  18:       0x7fa199337b - std::sys::unix::time::inner::Instant::sub_instant::{{closure}}::h18563395bbed46b0    
                               at libstd/sys/unix/time.rs:292                                                   
  19:       0x7fa19a6ebb - std::time::Instant::elapsed::h5d7a80e72662292b                                       
                               at libcore/result.rs:774                                                         
                               at libstd/sys/unix/time.rs:291                                                   
                               at libstd/time.rs:185                                                            
                               at libstd/time.rs:250                                                            
                               at libstd/time.rs:209                                                            
  20:       0x7f9ffe1677 - rustc::util::profiling::SelfProfiler::start_activity::h986ad6359f81d55a              
  21:       0x7fa01d6cb7 - rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt<'a, 'gcx, 'tcx>>::force_query_with_job::hc4af5870698c60ab
  22:       0x7fa0269933 - rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt<'a, 'gcx, 'tcx>>::get_query::h6f683a66c5cd04fc
  23:       0x7f9ff82c1b - rustc::traits::specialize::specialization_graph::Children::insert_blindly::ha890e94c48b0285e
  24:       0x7f9ffcec8f - rustc::traits::specialize::specialization_graph_provider::hd7f0b5a2ff57c920          
  25:       0x7fa01a34e7 - rustc::ty::query::<impl rustc::ty::query::config::QueryAccessors<'tcx> for rustc::ty::query::queries::specialization_graph_of<'tcx>>::compute::h55791f060255075c
  26:       0x7f9ff4f86b - rustc::dep_graph::graph::DepGraph::with_task_impl::h992bebda7ff9cd47                 
  27:       0x7fa00e3753 - <rustc::ty::query::plumbing::JobOwner<'a, 'tcx, Q>>::start::h7d7a156d9f36ae7c        
  28:       0x7fa01c226b - rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt<'a, 'gcx, 'tcx>>::force_query_with_job::h47db5b7f6268c68d
  29:       0x7fa0248b1f - rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt<'a, 'gcx, 'tcx>>::get_query::h460854c56198ad02
  30:       0x7f9ffcd8f3 - rustc::traits::specialize::find_associated_item::hdcb76f43f4e084c9                   
  31:       0x7f9ffdfeaf - rustc::ty::instance::Instance::resolve::hcf7331f6719090cf                            
  32:       0x7fa0a29e93 - rustc_mir::monomorphize::collector::visit_fn_use::h0b7ff6013ac91264                  
  33:       0x7fa0a29a47 - <rustc_mir::monomorphize::collector::MirNeighborCollector<'a, 'tcx> as rustc::mir::visit::Visitor<'tcx>>::visit_terminator_kind::h273825cee5b9efef
  34:       0x7fa0a28733 - rustc_mir::monomorphize::collector::collect_items_rec::h3640dedea6ef9cd7             
  35:       0x7fa0a28bf3 - rustc_mir::monomorphize::collector::collect_items_rec::h3640dedea6ef9cd7             
  36:       0x7fa0a28bf3 - rustc_mir::monomorphize::collector::collect_items_rec::h3640dedea6ef9cd7             
  37:       0x7fa0a28bf3 - rustc_mir::monomorphize::collector::collect_items_rec::h3640dedea6ef9cd7             
  38:       0x7fa0a28bf3 - rustc_mir::monomorphize::collector::collect_items_rec::h3640dedea6ef9cd7             
  39:       0x7fa0a28bf3 - rustc_mir::monomorphize::collector::collect_items_rec::h3640dedea6ef9cd7             
  40:       0x7fa0a28bf3 - rustc_mir::monomorphize::collector::collect_items_rec::h3640dedea6ef9cd7             
  41:       0x7fa0a28bf3 - rustc_mir::monomorphize::collector::collect_items_rec::h3640dedea6ef9cd7             
  42:       0x7fa0a28bf3 - rustc_mir::monomorphize::collector::collect_items_rec::h3640dedea6ef9cd7             
  43:       0x7fa0a28bf3 - rustc_mir::monomorphize::collector::collect_items_rec::h3640dedea6ef9cd7             
  44:       0x7fa0a28bf3 - rustc_mir::monomorphize::collector::collect_items_rec::h3640dedea6ef9cd7             
  45:       0x7fa0a28bf3 - rustc_mir::monomorphize::collector::collect_items_rec::h3640dedea6ef9cd7             
  46:       0x7fa0a28bf3 - rustc_mir::monomorphize::collector::collect_items_rec::h3640dedea6ef9cd7             
  47:       0x7fa0a28bf3 - rustc_mir::monomorphize::collector::collect_items_rec::h3640dedea6ef9cd7             
  48:       0x7fa0a27beb - rustc_mir::monomorphize::collector::collect_crate_mono_items::{{closure}}::ha18316921a9b2907
  49:       0x7fa0a27027 - rustc_mir::monomorphize::collector::collect_crate_mono_items::h4032ae4d8b75f166      
  50:       0x7f9c8a8cbb - rustc::util::common::time::h8666e011e51fe9e5                                         
  51:       0x7f9c92d283 - rustc_codegen_llvm::base::collect_and_partition_mono_items::h89d01ebc8f4a3923        
  52:       0x7fa01a3f2b - rustc::ty::query::<impl rustc::ty::query::config::QueryAccessors<'tcx> for rustc::ty::query::queries::collect_and_partition_mono_items<'tcx>>::compute::heb56783bba3b818d
  53:       0x7f9ff5aa2b - rustc::dep_graph::graph::DepGraph::with_task_impl::hc7a605db5928df4b                 
  54:       0x7fa00cb96b - <rustc::ty::query::plumbing::JobOwner<'a, 'tcx, Q>>::start::h3aca894fac9418e0        
  55:       0x7fa01bfb87 - rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt<'a, 'gcx, 'tcx>>::force_query_with_job::h2ef87316503525e3
  56:       0x7fa02685d3 - rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt<'a, 'gcx, 'tcx>>::get_query::h6ef566902fcecd63
  57:       0x7f9c975fbf - rustc_codegen_llvm::back::symbol_export::exported_symbols_provider_local::h303bba7f92d3a4af
  58:       0x7fa01a3f07 - rustc::ty::query::<impl rustc::ty::query::config::QueryAccessors<'tcx> for rustc::ty::query::queries::exported_symbols<'tcx>>::compute::h022e11021971ef4b
  59:       0x7f9ff6a563 - rustc::dep_graph::graph::DepGraph::with_task_impl::hfd5ef0a8a156fdd0                 
  60:       0x7fa00ff177 - <rustc::ty::query::plumbing::JobOwner<'a, 'tcx, Q>>::start::hcc8cf0c3a9318e29        
  61:       0x7fa01cf38f - rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt<'a, 'gcx, 'tcx>>::force_query_with_job::h8fb67b1f85c56b70
  62:       0x7fa02458c3 - rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt<'a, 'gcx, 'tcx>>::get_query::h3ea93f0537b81797
  63:       0x7fa0fcd827 - rustc_metadata::encoder::encode_metadata::h3974ec048e66b56c                          
  64:       0x7f9c92aeb7 - rustc_codegen_llvm::base::write_metadata::ha006227f86f20551                          
  65:       0x7f9c8a883f - rustc::util::common::time::h46b0a789d4fd44de                                         
  66:       0x7f9c92b57b - rustc_codegen_llvm::base::codegen_crate::h4f47006aaff274ca                           
  67:       0x7f9c97b50f - <rustc_codegen_llvm::LlvmCodegenBackend as rustc_codegen_utils::codegen_backend::CodegenBackend>::codegen_crate::h1b5e0a36777f0f8c
  68:       0x7fa1b064a3 - rustc::util::common::time::ha03eb7179adf5641                                         
  69:       0x7fa1afa8a7 - rustc_driver::driver::phase_4_codegen::h986e03d93b5cf4ce                             
  70:       0x7fa1ad1adf - rustc_driver::driver::compile_input::{{closure}}::hf98165e0c1a4801e                  
  71:       0x7fa1abb253 - rustc::ty::context::tls::enter_context::hf5a4819238d513a2                            
  72:       0x7fa1b3c2b3 - <std::thread::local::LocalKey<T>>::with::h93386544071cc3f1                           
  73:       0x7fa1b80e43 - rustc::ty::context::TyCtxt::create_and_enter::h93142bd23c49dd05                      
  74:       0x7fa1af4b8b - rustc_driver::driver::compile_input::hca1fa21f74ba205b                               
  75:       0x7fa1b9afef - rustc_driver::run_compiler_with_pool::ha0c892e478210d0a                              
  76:       0x7fa1af31c7 - rustc_driver::driver::spawn_thread_pool::hbbcb33985c15d20b                           
  77:       0x7fa1b9a3c3 - rustc_driver::run_compiler::hdb819c346db8c5be                                        
  78:       0x7fa1adff9b - <scoped_tls::ScopedKey<T>>::set::h6fcbf427d45c73d6                                   
  79:       0x7fa1ad4d57 - <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::hf3c2e500cf26088e
  80:       0x7fa19cd4db - __rust_maybe_catch_panic                                                             
                               at libpanic_unwind/lib.rs:102                                                    
  81:       0x7fa1b98d2f - rustc_driver::run::ha33a97a6629d40ce                                                 
  82:       0x7fa1ba364f - rustc_driver::main::hf36dd058a5421ad9                                                
  83:       0x558499bc27 - std::rt::lang_start::{{closure}}::h2c591498ace73137                                  
  84:       0x7fa1999dc7 - std::panicking::try::do_call::he4712eb84191fb3b                                      
                               at libstd/rt.rs:59                                                               
                               at libstd/panicking.rs:310                                                       
  85:       0x7fa19cd4db - __rust_maybe_catch_panic                                                             
                               at libpanic_unwind/lib.rs:102                                                    
  86:       0x7fa198fd07 - std::rt::lang_start_internal::h76f990c2b2c74932                                      
                               at libstd/panicking.rs:289                                                       
                               at libstd/panic.rs:392                                                           
                               at libstd/rt.rs:58                                                               
  87:       0x558499bc83 - main                                                                                 
  88:       0x7fa180ed87 - __libc_start_main                                                                    
query stack during panic:                                                                                       
thread panicked while processing panic. aborting.                                                               
error: Could not compile `semver-parser`.
```

Strangely though, the next time I tried compiling with `-j 1`, it compiled fine. I'm pretty confused about this, and I guess I should really be cross compiling but it was much easier to just compile on the target than figure out how to cross compile openssl and stuff.

rustc 1.31.0 (abe02cefd 2018-12-04)
binary: rustc
commit-hash: abe02cefd6cd1916df62ad7dc80161bea50b72e8
commit-date: 2018-12-04
host: aarch64-unknown-linux-gnu
release: 1.31.0
LLVM version: 8.0

### PR DESCRIPTION
**Pull request by alexcrichton**
This commit is an attempt to force `Instant::now` to be monotonic
through any means possible. We tried relying on OS/hardware/clock
implementations, but those seem buggy enough that we can't rely on them
in practice. This commit implements the same hammer Firefox recently
implemented (noted in #56612) which is to just keep whatever the lastest
`Instant::now()` return value was in memory, returning that instead of
the OS looks like it's moving backwards.

Closes #48514
Closes #49281
cc #51648
cc #56560
Closes #56612
Closes #56940

### CODE REVIEW

**Comment by wesleywiser** [comment]
Thanks for fixing this so quickly @alexcrichton!

File: src/libstd/time.rs [hunk 1]
```diff
@@ -160,7 +162,45 @@ impl Instant {
...
+        }
+
+        static LOCK: Mutex = Mutex::new();
+        static mut LAST_NOW: time::Instant = time::Instant::zero();
+        unsafe {
+            let _lock = LOCK.lock();
+            let now = cmp::max(LAST_NOW, os_now);
+            LAST_NOW = now;
+            Instant(now)
+        }
```
Comment (the8472) [inline src/libstd/time.rs]: A mutex seems a bit heavy-handed. Many uses of rdtsc (where available) are for minimal-overhead, thread-local timing of functions.
Wouldn't rdtsc + some atomic ops that prevent things from going backwards be much lighter than potential thread suspension?

Comment (alexcrichton) [reply src/libstd/time.rs]: I agree that a full-on mutex is quite a heavy hammer for this use case! I wasn't sure though how to best to minimize the cost here.

The [Windows documentation](https://docs.microsoft.com/en-us/windows/desktop/SysInfo/acquiring-high-resolution-time-stamps) at least "strongly discourages" rdtsc for handling VM migration issues as well as some supposed hardware. If that's the case I think we probably want to avoid that?

I figured it'd probably be best to start from a conservative position and we can always come in later as necessary and try to use atomics and/or different tricks.

**Comment by Mark-Simulacrum** [comment]
Is there a reason we're using the "internal" Mutex for the implementation though? I'd kind of expect that we could just use `std::sync::Mutex`?

File: src/libstd/time.rs (hunk 1 above)
Comment (the8472) [reply src/libstd/time.rs]: I didn't mean to use `rdtsc` directly. We can still defer to `QueryPerformanceCounter`/`clock_gettime`, i.e. the current `Instant` implementation which in the end boils down to rdtsc on many x86 systems.
Just tack on a sanity check/correction with atomics instead of a mutex.

I'm mostly concerned that thread-contention might unexpectedly hit people if they litter their code with instants because it used to be fast. I have no concrete examples, just experience with gratuitous use of timing functions that were fast on linux suddenly making an application slow on windows because it decided to not use rdtsc.

**Comment by alexcrichton** [comment]
@Mark-Simulacrum the `sync::Mutex` type doesn't have a `const` constructor, whereas the internal mutex type does

File: src/libstd/time.rs (hunk 1 above)
Comment (alexcrichton) [reply src/libstd/time.rs]: Oh I'm all for adding a more lightweight implementation, do you have one in mind? `Instant` has a varying size across platforms, which makes it difficult to select an appropriate atomic and/or more lightweight method

Comment (the8472) [reply src/libstd/time.rs]: I had sizeof checks, some type punning and AtomicU128/U64 in mind. Beyond that it would be your standard read, check, CAS. similar to what you're now doing in the lock's critical section, except in a loop.

The mutex would still be needed as fallback if the checks don't work out.

Comment (the8472) [reply src/libstd/time.rs]: An atomic will still be cheaper than a lock, but yeah, rdtsc is just a few dozen clock cycles on modern chips, even a single contended cas could make it an order of magnitude slower, not to mention the unbounded retry loop.

Other options are

* making this change opt-in (via ENV?)
* an opportunistic check using thread-locals and switching to the locked approach if a violation is detected. not 100% reliable.
* blacklist approach for platforms instead of whitelist

Comment (alexcrichton) [reply src/libstd/time.rs]: I agree we should optimize for the common case of not going backwards, I'm open to alternative implementations! I can't think of one, though.

@the8472 I'm not sure what you mean by thread locals? How would that be able to speed up this check?

Comment (the8472) [reply src/libstd/time.rs]: Thread-local storage shouldn't involve any atomic operations and thus wouldn't suffer from contention. The downside is that it only catches violations of monotonicity when a thread migrates between CPU cores. This is assuming the problem stems from cores being out of sync while individual cores are still monotonic. It wouldn't prevent the case of two `Instant`s created on different threads seeing time go backwards. 

Another question is how big the errors are. If they are huge they could be detected when starting new threads by comparing with what its parent sees before invoking the thread spawn method.

Comment (alexcrichton) [reply src/libstd/time.rs]: Ah ok, that's what I thought, and yeah my worry about that is that it wouldn't solve the original problem of monotonic clocks going backwards, so I'm afraid we'd still end up a the solution proposed in this PR.

We, as far as I know, don't have a great handle on how big the errors are.

Comment (the8472) [reply src/libstd/time.rs]: I have thought some more about optimization potential

1. we can use relaxed atomics everywhere. Justification: One thread cannot observe another thread's `Instant`s without some external synchronization happening, e.g. other ordered loads and stores. So until those happen only intra-thread ordering is relevant, Relaxed is sufficient for that.
2. in the good case we only need to do a test and return from the perspective of the main sequence of instructions. There's no dependency on the writes to global state happening, so this should be friendly to instruction parallelism.
3. we can limit the XCHG loop by bailing out early if it fails because another thread updated it to a larger value than we are trying. it doesn't prevent the cache-line from bouncing around but at least can allow multiple threads to make progress simultaneously.


It could approximately look like this:

```rust
static mut LAST_NOW: AtomicU128 = 0.into();
let last_now = LAST_NOW.load(Relaxed);  // insert type punning here
let os_now = time::Instant::now();
if likely(os_now > last_now) {
  loop {
    match LAST_NOW.compare_exchange_weak(last_now, os_now, Relaxed, Relaxed) {
      Ok(_) => break,
      Err(x) if x >= os_now => break, // some other thread is ahead of us, no need to update
      _ => {}
    }
  return os_now;
}
return last_now
```

It's a bit smaller hammer but still not the rubber kind. To soften it further we either need a *I (don't) care about broken systems* switch somewhere or use better platform detection.

File: src/libstd/time.rs [hunk 2]
```diff
@@ -160,7 +162,45 @@ impl Instant {
...
+        // * #48514 - OpenBSD, x86_64
+        // * #49281 - linux arm64 and s390x
+        // * #51648 - windows, x86
+        // * #56560 - windows, x86_64, AWS
+        // * #56612 - windows, x86, vm (?)
+        // * #56940 - linux, arm64
+        // * https://bugzilla.mozilla.org/show_bug.cgi?id=1487778 - a similar
+        //   Firefox bug
+        //
+        // It simply seems that this it just happens so that a lot in the wild
```
Comment (stjepang) [inline src/libstd/time.rs]: Delete 'this'?

File: src/libstd/time.rs (hunk 1 above)
Comment (alexcrichton) [reply src/libstd/time.rs]: @the8472 yes that's all possible but 128-bit atomics are only available on a few platforms, so we can't use them generally.

Comment (alexcrichton) [reply src/libstd/time.rs]: @nikic I think it's incorrect to avoid the full lock though? If the time is less than a thread-local version than you definitely have to acquire the lock, but even if it's greater than a thread local version you need to check the lock for the global one as well. Right now the bug primarily happens on one thread, but the documented guarantees of this API are that it works across all threads

**Comment by the8472** [comment]
Maybe we should get a perf run on this for a system where `actually_monotonic == false`?

File: src/libstd/time.rs [hunk 3]
```diff
@@ -160,7 +162,45 @@ impl Instant {
...
+        // to fix things up. We keep a global "latest now" instance which is
+        // returned instead of what the OS says if the OS goes backwards.
+        //
+        // To hopefully mitigate the impact of this though a few platforms are
+        // whitelisted as "these at least haven't gone backwards yet".
+        if time::Instant::actually_monotonic() {
+            return Instant(os_now)
+        }
+
+        static LOCK: Mutex = Mutex::new();
```
Comment (gnzlbg) [inline src/libstd/time.rs]: Do we have dead-code elimination in MIR debug builds ? Otherwise LLVM-IR for this code will always be emitted independently of the result of `actually_monotonic`, and whether that code will end up generating machine code will depend on the optimization level.

Comment (alexcrichton) [reply src/libstd/time.rs]: We don't, now, but `actually_monotonic` is a function that'll be trivially inlined so LLVM will optimize this away

**Comment by sfackler** [comment]
Hardware Is Bad

@bors r+

File: src/libstd/sys/unix/time.rs [hunk 4]
```diff
@@ -258,19 +267,26 @@ mod inner {
...
             Instant { t: now(libc::CLOCK_MONOTONIC) }
         }
 
+        pub const fn zero() -> Instant {
+            Instant {
+                t: Timespec::zero(),
+            }
+        }
+
+        pub fn actually_monotonic() -> bool {
```
Comment (lu-zero) [inline src/libstd/sys/unix/time.rs]: @edelsonh Can you confirm ppc/ppc64 has a reliable monotonic clock?

**Comment by sanxiyn** [comment]
My understanding of adjtime is that they specifically do not cause any monotonicity problems. That is, adjtime can't be the cause. If we trust manual pages.

**Comment by spacejam** [comment]
NTP can just yank a clock backwards of the higher stratum side if the delta is over 128ms. https://github.com/ntp-project/ntp/blob/stable/parseutil/dcfd.c#L1059

**Comment by programmerjake** [comment]
I know this is a little late, but an atomic umax would be better than the compare-exchange this currently uses. LLVM has the [atomicrmw umax](https://releases.llvm.org/7.0.1/docs/LangRef.html#atomicrmw-instruction) instruction and RISC-V and probably other architectures have an instruction for that. Using the atomic umax instruction allows the atomic operation to be executed wherever the memory is cached (TileLink has special support for that) instead of having to move the cached memory, saving time.

**Comment by vi** [comment]
Does it affect `cargo bench`? Will it start benching a synchronisation primitive instead of actual code?

**Comment by programmerjake** [comment]
It would have an atomic op either way.

**Comment by alexcrichton** [comment]
@vi `cargo bench` does indeed use `Instant::now()`, and afaik measurements haven't been done to evaluate the impact of this.

**Comment by Saruspete** [comment]
Hello there,

It's a bit late, and I'm more on the system than dev side, but anyway here's some hints / events / configurations on x86 & Linux that may (or may not) help you work on this matter (to be aware of the bad things that can happen).

So for Linux, you have multiple timing functions (some are available since a more recent kernel)
Each of these have its caveat and the choice depends on your use case:

**CS** = Clock Source (incremental monotonic counter)
**TO** = Time offset (value to add to CS to get the real human time)
**ADJ** = Minor Adjustments to CS (ntp, ptp)
**TZ** = Timezone

Source | Precision | Get from | Value
---- | ---- |  ---- | ----
clock_gettime( CLOCK_REALTIME) | ns | vdso & syscall fallback | CS + TO + ADJ
clock_gettime( CLOCK_REALTIME_COARSE) | ms | vdso | CS + TO + ADJ
clock_gettime( CLOCK_MONOTONIC) | ns | vdso | CS + ADJ
clock_gettime( CLOCK_MONOTONIC_COARSE) | ms | vdso | CS + ADJ
clock_gettime( CLOCK_MONOTONIC_RAW) | | vdso | CS
gettimeofday() | us | vsdo override | CS + TO + ADJ + TZ
time() |  sec | syscall | compat over gettimeofday
Assembly RDTSC | cpu base freq, eg 3GHz = 0.33ns | memory read | CS
Assembly RDTSCP | cpu base freq | memory read | CS 

On modern x86, most of the selection work is done in `arch/x86/entry/vdso/vclock_gettime.c :: __vdso_clock_gettime()`.
vDSO aims to give faster than syscall results when available, using common values contained in the structure `arch/x86/include/asm/vgtod.h:: vsyscall_gtod_data` (for timing, among other things). 
This structure and system-wide clocks are managed by timekeeper kernel' structure, located in `time/timekeeper.c`. 
You may want to check the timekeeping_update() code (called by settimeofday, change_clocksource, and many other events) to update the system time values.
You can check/set the underlying timekeeper clocksource through `/sys/devices/system/clocksource/clocksource0/current_clocksource`.

Standard calls for time (so, the non-coarse) means to deliver precise timing, and calling for a time delta between the last timekeeper update and the effective function call. To speedup things, these standard calls also try to use direct hardware: vread_pvclock (para-virtualized) vread_hvclock (hyper-v), vread_tsc() or vendor-supplied [timeeking in VMware](https://www.vmware.com/files/pdf/techpaper/Timekeeping-In-VirtualMachines.pdf)
The coarse types will simply return the value of the last timekeeper update (which is defined by constant HZ of the kernel, most of the time 1000Hz). This means just 1 or 2 values to read, no syscall and time diff, so super fast... but also way less precise.

So, here's how I choose which one depending on the use-case:

- REALTIME : precise wall-clock time (precise log, events timediff)
- REALTIME_COARSE : simple wall-clock time (to the second or ms) like for system logs.
- MONOTONIC : precise duration measurement (benchmark, security related...)
- MONOTONIC_COARSE : Not used.
- MONOTONIC_RAW : system-wide stable counter.
- RDTSC : precise function timing (but not for micro-benchmark) on stable CPUs (avoid process migration and VM)
- RDTSCP / RDTSC + [lm]fence : precise benchmark. The serializing instruction avoid CPU Reordering, that would screw the micro-benchmark results. 

### some pitfalls

- Beware of "human time clocks", as they will include the Leap-Second special case. It'll also depend on the [type of adjustment requested by sysadmin](https://developers.redhat.com/blog/2015/06/01/five-different-ways-handle-leap-seconds-ntp/): let kernel step back, let the ntp daemon step back, slew the clock during the whole day, add a new second (23:59:60)
- The 128ms clock limit for slowing the time is only valid for ntpd, but some other daemons does not have this limit, like [chrony](https://chrony.tuxfamily.org/comparison.html).
- The RealTime Linux variant (whose many features were included upstream) also have special features, like a dedicated thread for doing the timekeeping, tickless CPUs, and other constraints relative to the handling of time. You might want to ask these guys, especially Thomas Gleixner and Steven Rostedt.
- Some CPU might go offline, and the processes that were in his runqueue are migrated to another one. 
- the clock calls might get in unbound retry
- Some very exotic x86 hardware, like Bullion or SuperDome are multiple independant systems / blades made into a single one. This might have implications on the timing measurement depending on the OS & version



Whatever the OS, at the lower level, timing may be found from multiple hardware sources:

### TimeStampCounter (TSC)
An incremental counter based on each cpu, value read by RDTSC or RDTSCP
As it's CPU based, when your reading process is migrated from a socket to another, or when the underlying hardware changes (like a Virtual Machine), the TSC value **may** have a very different value.
Some other scenarios can also lead to issues when using it (+ cpuflags to check if the feature is safe)

- CPU provides frequency-scaling (PState) or CPU Sleep States (CState) to dynamically adjust frequency and/or power-saving, as long as CPU is kept in ACP-S0 (cpuflag: constant_tsc).
- TSC will stop and reset upon standby (S3) or hybernation (S4) (cpuflag: nonstop_tsc).
- The underlying Hypervisor will stop the VM and resume it, like for motion, snapshot, etc...

### High Precision Event Timer (HPET)
It's composed of a single counter (fixed frequency), and many comparators that will generate an interrupt when the counter reaches a value they are waiting for. The counter frequency should just be higher than 10MHz. 
This have multiple issues, like time drift, skew, missed interrupts, 
 
### Real Time Clock (RTC)
Well, not used anymore...



I know you have to cover multiple arches, and OS types, and OS versions, so always keep a skeptical eye when you implement a low-level feature :)

A feature I do on all language I use: a timing function/class that asks for what I intend to measure, and choose the right function for me. Maybe you can integrate it directly.
