### PR TITLE
Silence unecessary !Sized binding error

### LINKED ISSUE #117846: Wrong underlined argument in tuple returned by function
### Code

```Rust
fn get_arguments(data: &[u8]) -> (Vec<String>, &[u8]) {
    (Vec::new(), data)
}

let x = true;
let cmd = &[1, 2, 3, 4];
let (cmd, proc_args) = if x {
    get_arguments(cmd)
} else {
    (Vec::new(), &[])
};
```

### Current output

```Shell
error[E0277]: the size for values of type `[_]` cannot be known at compilation time
   --> src/unix/apple/macos/process.rs:581:10
    |
581 |     let (cmd, proc_args) = if x {
    |          ^^^ doesn't have a size known at compile-time
    |
    = help: the trait `Sized` is not implemented for `[_]`
    = note: all local variables must have a statically known size
    = help: unsized locals are gated as an unstable feature
```

### Desired output

```Shell
error[E0277]: the size for values of type `[_]` cannot be known at compilation time
   --> src/unix/apple/macos/process.rs:581:10
    |
581 |     let (cmd, proc_args) = if x {
    |               ^^^^^^^^^ doesn't have a size known at compile-time
    |
    = help: the trait `Sized` is not implemented for `[_]`
    = note: all local variables must have a statically known size
    = help: unsized locals are gated as an unstable feature
```

### Rationale and extra context

It's underlining the wrong argument.

### Other cases

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by estebank**
When gathering locals, we introduce a `Sized` obligation for each
binding in the pattern. *After* doing so, we typecheck the init
expression. If this has a type failure, we store `{type error}`, for
both the expression and the pattern. But later we store an inference
variable for the pattern.

We now avoid any override of an existing type on a hir node when they've
already been marked as `{type error}`, and on E0277, when it comes from
`VariableType` we silence the error in support of the type error.

Fix https://github.com/rust-lang/rust/issues/117846

### CODE REVIEW

File: compiler/rustc_hir_typeck/src/fn_ctxt/_impl.rs [hunk 1]
```diff
@@ -138,7 +138,21 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
...
+        let mut typeck = self.typeck_results.borrow_mut();
+        let mut node_ty = typeck.node_types_mut();
+        if let Some(ty) = node_ty.remove(id)
+            && let ty::Error(e) = ty.kind()
+        {
+            // Do not overwrite nodes that were already marked as `{type error}`. This allows us to
+            // silence unnecessary errors from obligations that were set earlier than a type error
+            // was produced, but that is overwritten by later analysis.  This happens in particular
+            // for `Sized` obligations introduced in gather_locals.  (#117846)
+            node_ty.insert(id, ty);
```
Comment (Nadrieril) [inline compiler/rustc_hir_typeck/src/fn_ctxt/_impl.rs:150]: Why not `node_ty.get(id)` instead of `remove`+`insert`?

File: compiler/rustc_trait_selection/src/traits/error_reporting/suggestions.rs [hunk 2]
```diff
@@ -2915,6 +2915,16 @@ impl<'tcx> TypeErrCtxt<'_, 'tcx> {
                 }
             }
             ObligationCauseCode::VariableType(hir_id) => {
+                if let Some(typeck_results) = &self.typeck_results
+                    && let Some(ty) = typeck_results.node_type_opt(hir_id)
+                    && let ty::Error(_) = ty.kind()
+                {
+                    err.note(format!(
+                        "`{predicate}` isn't satisfied, but type type of this pattern is \
```
Comment (Nadrieril) [inline compiler/rustc_trait_selection/src/traits/error_reporting/suggestions.rs:2923]:
```suggestion
                        "`{predicate}` isn't satisfied, but the type of this pattern is \
```

File: compiler/rustc_hir_typeck/src/fn_ctxt/_impl.rs [hunk 3]
```diff
@@ -138,7 +138,21 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
     #[inline]
     pub fn write_ty(&self, id: hir::HirId, ty: Ty<'tcx>) {
         debug!("write_ty({:?}, {:?}) in fcx {}", id, self.resolve_vars_if_possible(ty), self.tag());
-        self.typeck_results.borrow_mut().node_types_mut().insert(id, ty);
+        let mut typeck = self.typeck_results.borrow_mut();
+        let mut node_ty = typeck.node_types_mut();
+        if let Some(ty) = node_ty.remove(id)
+            && let ty::Error(e) = ty.kind()
```
[the remark this answers is not in the document]
Comment (estebank) [reply compiler/rustc_hir_typeck/src/fn_ctxt/_impl.rs:144]: Isn't it enough to check we have an `ErrorGuaranteed` for that?

[the remark this answers is not in the document]
Comment (Nadrieril) [reply compiler/rustc_hir_typeck/src/fn_ctxt/_impl.rs:144]: `error_reported()` looks for `ty::Error` even deep within the type, so it would also catch e.g. `(T, {type error})`. I don't know if that's relevant to this check tho

File: compiler/rustc_hir_typeck/src/fn_ctxt/_impl.rs (hunk 1 above)
Comment (estebank) [reply compiler/rustc_hir_typeck/src/fn_ctxt/_impl.rs:150]: [We don't have `LocalTableInContextMut::get`.](https://github.com/rust-lang/rust/blob/010f3944e0f0baac8d738da49772fd06acd3701b/compiler/rustc_middle/src/ty/typeck_results.rs#L565-L595)

Comment (Nadrieril) [reply compiler/rustc_hir_typeck/src/fn_ctxt/_impl.rs]: Wouldn't `get_mut` work here?

Comment (estebank) [reply compiler/rustc_hir_typeck/src/fn_ctxt/_impl.rs]: It would. It's just that the type would get discarded and overwritten regardless of the success or not of the let chain, but yeah, I can make it use `get_mut`.

Comment (Nadrieril) [reply compiler/rustc_hir_typeck/src/fn_ctxt/_impl.rs]: Ah, my surprise came from the fact that you're reinserting the `ty` you just removed. I guess you intended to insert the `ty` you got as input to the function?

Comment (Nadrieril) [reply compiler/rustc_hir_typeck/src/fn_ctxt/_impl.rs]: I see. I would indeed prefer if you used `get_mut`

Comment (Nadrieril) [reply compiler/rustc_hir_typeck/src/fn_ctxt/_impl.rs]: Or implemented `get` tbh

Comment (Nadrieril) [reply compiler/rustc_hir_typeck/src/fn_ctxt/_impl.rs]: If you really prefer `remove`+`insert` could you then name the variable something like `err_ty` to clarify the intent?

**Comment by Nadrieril** [comment]
r=me once the `remove`+`insert` is clarified in one way or another
