### PR TITLE
std: refactor explanation of `NonNull`

### LINKED ISSUE #141933: Reexplain `NonNull`'s covariance details more concisely
### Location

std::ptr::NonNull
https://doc.rust-lang.org/stable/std/ptr/struct.NonNull.html

### Summary

This page spills a lot of digital ink on the matter of covariance versus invariance. The fact of the matter is it is usually correct to use, which is why it was chosen to be like that. There are abstractions that require invariance, but they must be designed carefully to begin with, and the current format of the description is very repetitive. In practice, we have not seen an explosion of bugs from people using `NonNull` incorrectly over the past 60 versions, and I do not believe it is primarily because of the documented cautions. I do, however, see people incorrectly using `&mut T`, `&T` when they want `NonNull<T>`.

A more precise summarization would be more useful and less intimidating.

### PR DESCRIPTION
**Pull request by xizheyin**
Fixes rust-lang/rust#141933 

I cut out the excessive explanation and used an example to explain how to maintain invariance, but I think what is quoted in the *rust reference* in the document needs to be added with a more layman's explanation and example.

(I'm not sure if I deleted too much)

r? @workingjubilee

### CODE REVIEW

File: library/core/src/ptr/non_null.rs [hunk 1]
```diff
@@ -11,36 +11,23 @@ use crate::{fmt, hash, intrinsics, mem, ptr};
...
+/// use std::ptr::NonNull;
 ///
-/// If your type cannot safely be covariant, you must ensure it contains some
-/// additional field to provide invariance. Often this field will be a [`PhantomData`]
-/// type like `PhantomData<Cell<T>>` or `PhantomData<&'a mut T>`.
+/// struct MyCell<T> {
+///     ptr: NonNull<T>,
+///     _invariant: PhantomData<Cell<T>>,
+/// }
+/// ```
```
Comment (workingjubilee) [inline library/core/src/ptr/non_null.rs]: I feel this made it too vague.

File: library/core/src/ptr/non_null.rs [hunk 2]
```diff
@@ -11,36 +11,23 @@ use crate::{fmt, hash, intrinsics, mem, ptr};
...
 ///
-/// Notice that `NonNull<T>` has a `From` instance for `&T`. However, this does
-/// not change the fact that mutating through a (pointer derived from a) shared
-/// reference is undefined behavior unless the mutation happens inside an
-/// [`UnsafeCell<T>`]. The same goes for creating a mutable reference from a shared
-/// reference. When using this `From` instance without an `UnsafeCell<T>`,
-/// it is your responsibility to ensure that `as_mut` is never called, and `as_ptr`
-/// is never used for mutation.
+/// In most cases, you should use `NonNull<T>` when you want a non-null pointer. If you are unsure, using a raw pointer (`*mut T`) is also fine.
```
Comment (workingjubilee) [inline library/core/src/ptr/non_null.rs]: This isn't about variance so it probably shouldn't have been removed the same way.

Comment (xizheyin) [reply library/core/src/ptr/non_null.rs]: Indeed, less content needs to be removed.

File: library/core/src/ptr/non_null.rs (hunk 1 above)
Comment (workingjubilee) [reply library/core/src/ptr/non_null.rs]: What we should focus on is that variance is required if the implementation exposes a way to mutate `T`, because otherwise if `T` is actually `&'long U` then covariance allows writing `&'short U`.

**Comment by xizheyin** [comment]
I've avoided big changes this time, removing some of the “scary” descriptions and replacing them with more practical advice, and adding more specific explanations for the examples.

**Comment by workingjubilee** [comment]
Hm. I know I filed the issues but I wasn't really expecting to get two PRs immediately and requested on them, I kinda expected them to hit the rotation, and this is a slightly more tricky PR to judge when biased by being the reporter. So I'm going to pass them onto the rotation, sorry! ^^;

r? libs

**Comment by workingjubilee** [comment]
lol
r? libs
