### PR TITLE
typeck: always expose repeat count `AnonConst`s' parent in `generics_of`.

### LINKED ISSUE #66706: Closure type error during const-eval (array len context)
The following code ICE's on stable, beta and nightly
```Rust
fn bug() {
    [0; [|f @ &ref _| {} ; 0 ].len() ];
}
```

<details>
<summary>Backtrace:</summary>

```
error: expected identifier, found reserved identifier `_`
 --> src/lib.rs:3:20
  |
3 |     [0; [|f @ &ref _| {} ; 0 ].len() ];
  |                    ^ expected identifier, found reserved identifier

error: internal compiler error: src/librustc_mir/hair/cx/expr.rs:518: closure expr w/o closure type: [type error]
 --> src/lib.rs:3:10
  |
3 |     [0; [|f @ &ref _| {} ; 0 ].len() ];
  |          ^^^^^^^^^^^^^^^

thread 'rustc' panicked at 'Box<Any>', src/librustc_errors/lib.rs:851:9
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:84
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:61
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1030
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1412
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:65
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:50
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:188
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:205
  10: rustc_driver::report_ice
  11: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:468
  12: std::panicking::begin_panic
  13: rustc_errors::HandlerInner::span_bug
  14: rustc_errors::Handler::span_bug
  15: rustc::util::bug::opt_span_bug_fmt::{{closure}}
  16: rustc::ty::context::tls::with_opt::{{closure}}
  17: rustc::ty::context::tls::with_opt
  18: rustc::util::bug::opt_span_bug_fmt
  19: rustc::util::bug::span_bug_fmt
  20: rustc_mir::hair::cx::expr::make_mirror_unadjusted
  21: rustc_mir::hair::cx::expr::<impl rustc_mir::hair::Mirror for &rustc::hir::Expr>::make_mirror
  22: <rustc_mir::hair::ExprRef as rustc_mir::hair::Mirror>::make_mirror
  23: rustc_mir::build::expr::as_rvalue::<impl rustc_mir::build::Builder>::expr_as_rvalue
  24: rustc_mir::build::expr::into::<impl rustc_mir::build::Builder>::into_expr
  25: rustc_mir::build::expr::as_temp::<impl rustc_mir::build::Builder>::expr_as_temp
  26: rustc_mir::build::expr::as_place::<impl rustc_mir::build::Builder>::expr_as_place
  27: rustc_mir::build::expr::into::<impl rustc_mir::build::Builder>::into_expr
  28: rustc_mir::build::expr::as_temp::<impl rustc_mir::build::Builder>::expr_as_temp
  29: rustc_mir::build::expr::as_operand::<impl rustc_mir::build::Builder>::expr_as_operand
  30: rustc_mir::build::expr::as_rvalue::<impl rustc_mir::build::Builder>::expr_as_rvalue
  31: rustc_mir::build::expr::into::<impl rustc_mir::build::Builder>::into_expr
  32: rustc_mir::build::expr::as_temp::<impl rustc_mir::build::Builder>::expr_as_temp
  33: rustc_mir::build::expr::as_operand::<impl rustc_mir::build::Builder>::expr_as_operand
  34: rustc_mir::build::expr::as_operand::<impl rustc_mir::build::Builder>::expr_as_operand
  35: rustc_mir::build::expr::as_operand::<impl rustc_mir::build::Builder>::as_local_operand
  36: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::fold
  37: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter
  38: rustc_mir::build::expr::into::<impl rustc_mir::build::Builder>::into_expr
  39: rustc_mir::build::expr::into::<impl rustc_mir::build::Builder>::into_expr
  40: rustc_mir::build::expr::into::<impl rustc_mir::build::Builder>::into_expr
  41: rustc_mir::build::construct_const
  42: rustc::ty::context::tls::with_context::{{closure}}
  43: rustc_mir::build::mir_build
  44: rustc_mir::transform::mir_built
  45: rustc::ty::query::__query_compute::mir_built
  46: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt>::get_query
  47: rustc_mir::transform::check_unsafety::unsafety_check_result
  48: rustc::ty::query::__query_compute::unsafety_check_result
  49: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt>::get_query
  50: rustc_mir::transform::mir_const
  51: rustc::ty::query::__query_compute::mir_const
  52: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt>::get_query
  53: rustc_mir::transform::mir_const_qualif
  54: rustc::ty::query::__query_compute::mir_const_qualif
  55: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt>::get_query
  56: rustc_mir::transform::mir_validated
  57: rustc::ty::query::__query_compute::mir_validated
  58: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt>::get_query
  59: rustc_mir::borrow_check::mir_borrowck
  60: rustc::ty::query::__query_compute::mir_borrowck
  61: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt>::get_query
  62: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt>::ensure_query
  63: rustc_mir::transform::optimized_mir
  64: rustc::ty::query::__query_compute::optimized_mir
  65: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt>::get_query
  66: rustc_mir::interpret::eval_context::InterpCx<M>::load_mir
  67: rustc_mir::const_eval::const_eval_raw_provider
  68: rustc::ty::query::__query_compute::const_eval_raw
  69: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt>::get_query
  70: rustc_mir::const_eval::const_eval_provider
  71: rustc::ty::query::__query_compute::const_eval
  72: rustc::ty::query::<impl rustc::ty::query::config::QueryAccessors for rustc::ty::query::queries::const_eval>::compute
  73: rustc::dep_graph::graph::DepGraph::with_task_impl
  74: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt>::get_query
  75: rustc_typeck::check::expr::<impl rustc_typeck::check::FnCtxt>::check_expr_kind
  76: rustc_typeck::check::expr::<impl rustc_typeck::check::FnCtxt>::check_expr_with_expectation_and_needs
  77: rustc_typeck::check::FnCtxt::check_stmt
  78: rustc_typeck::check::FnCtxt::check_block_with_expected
  79: rustc_typeck::check::expr::<impl rustc_typeck::check::FnCtxt>::check_expr_kind
  80: rustc_typeck::check::expr::<impl rustc_typeck::check::FnCtxt>::check_expr_with_expectation_and_needs
  81: rustc_typeck::check::expr::<impl rustc_typeck::check::FnCtxt>::check_return_expr
  82: rustc_typeck::check::check_fn
  83: rustc::ty::context::tls::with_context::{{closure}}
  84: rustc_typeck::check::typeck_tables_of
  85: rustc::ty::query::__query_compute::typeck_tables_of
  86: rustc::ty::query::<impl rustc::ty::query::config::QueryAccessors for rustc::ty::query::queries::typeck_tables_of>::compute
  87: rustc::dep_graph::graph::DepGraph::with_task_impl
  88: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt>::get_query
  89: rustc::ty::<impl rustc::ty::context::TyCtxt>::par_body_owners
  90: rustc_typeck::check::typeck_item_bodies
  91: rustc::ty::query::__query_compute::typeck_item_bodies
  92: rustc::dep_graph::graph::DepGraph::with_task_impl
  93: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt>::get_query
  94: rustc::util::common::time
  95: rustc_typeck::check_crate
  96: rustc_interface::passes::analysis
  97: rustc::ty::query::__query_compute::analysis
  98: rustc::dep_graph::graph::DepGraph::with_task_impl
  99: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt>::get_query
 100: rustc_interface::passes::BoxedGlobalCtxt::access::{{closure}}
 101: rustc_interface::passes::create_global_ctxt::{{closure}}
 102: rustc_interface::passes::BoxedGlobalCtxt::enter
 103: rustc_interface::interface::run_compiler_in_existing_thread_pool
 104: std::thread::local::LocalKey<T>::with
 105: scoped_tls::ScopedKey<T>::set
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.41.0-nightly (0c987c5c0 2019-11-23) running on x86_64-unknown-linux-gnu

note: compiler flags: -C codegen-units=1 -C debuginfo=2 --crate-type lib

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [mir_built] processing `bug::{{constant}}#0`
#1 [unsafety_check_result] processing `bug::{{constant}}#0`
#2 [mir_const] processing `bug::{{constant}}#0`
#3 [mir_const_qualif] const checking `bug::{{constant}}#0`
#4 [mir_validated] processing `bug::{{constant}}#0`
#5 [mir_borrowck] processing `bug::{{constant}}#0`
#6 [optimized_mir] processing `bug::{{constant}}#0`
#7 [const_eval_raw] const-evaluating `bug::{{constant}}#0`
#8 [const_eval] const-evaluating + checking `bug::{{constant}}#0`
#9 [typeck_tables_of] processing `bug`
#10 [typeck_item_bodies] type-checking all item bodies
#11 [analysis] running analysis passes on this crate
end of query stack
error: aborting due to 2 previous errors

```
 </details>

### LINKED ISSUE #70773: MIR type-checking ICE ("is not a subtype of") from lifetime parameter in scope of AnonConst.
This example was found in #70452 (where it *does not* require `#![feature(const_generics)]`, the only reason I have it here is to get around #43408) ([playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=5510e878230c498ec9925b6e3a457927)):
```rust
#![feature(const_generics)]

const HASH_LEN: usize = 20;
struct Hash([u8; HASH_LEN]);

pub fn foo<'a>() -> &'a () {
    Hash([0; HASH_LEN]);
    &()
}
```
The ICE is:
```rust
error: internal compiler error:
    broken MIR in DefId(0:8 ~ playground[8116]::foo[0]) (Hash(move _2,)):
        [u8; _] is not a subtype of [u8; 20]: NoSolution
```

The ICE goes away when the lifetime parameter (`'a`) is removed, *or* when replaced with a type parameter, so my guess is that the MIR type-checker triggers an attempt at normalization (otherwise it would also ICE with a type parameter) but has lifetime *inference* variables in the `Substs` of the `ConstKind::Unevaluated`, and that prevents the normalization.

It really shouldn't, I thought we both erased lifetimes *and* fell back on fully polymorphic evaluation (which should also succeed here), if there are any inference variables.

### PR DESCRIPTION
**Pull request by eddyb**
This should reduce some of the confusion around #43408, although, if you look at the changed test outputs (for the last commit), they all hit #68436, so nothing new will start compiling.

We can let counts of "repeat expressions" (`N` in `[x; N]`) always have the correct generics parenting, because they're always in a body, so nothing in the `where` clauses or `impl` trait/type of the parent can use it, and therefore no query cycles can occur.

<hr/>

Other potential candidates we might want to apply the same approach to, are:
* ~~(easy) `enum` discriminants (see also #70453)~~ opened #70825
* (trickier) array *type* (not *expression*) lengths nested in:
  * bodies
  * types of (associated or not) `const`/`static`
  * RHS of `type` aliases and associated `type`s
  * `fn` signatures

We should've done so from the start, the only reason we haven't is because I was squeamish about blacklisting some of the cases, but if we whitelist instead we should be fine.
Also, lazy normalization is taking forever :disappointed:.

<hr/>

There's also 5 other commits here:
* "typeck: track any errors injected during writeback and taint tables appropriately." - fixes #66706, as the next commit would otherwise trigger an ICE again
* "typeck: workaround WF hole in `to_const`." - its purpose is to emulate most of #70107's direct effect, at least in the case of repeat expressions, where the count always goes through `to_const`
  * this is the reason no new code can really compile, as the WF checks require #68436 to bypass
  * however, this has more test changes than I hoped, so it should be reviewed separately, and maybe even landed separately (as #70107 might take a while, as it's blocked on a few of my PRs)
* "ty: erase lifetimes early in `ty::Const::eval`." - first attempt at fixing #70773
  * still useful, I believe the new approach is less likely to cause issues long-term
  * I could take this out or move it into another PR if desired or someone else could take over (cc @skinny121)
* "traits/query/normalize: add some `debug!` logging for the result." - debugging aid for #70773
* "borrow_check/type_check: normalize `Aggregate` and `Call` operands." - actually fixes #70773

r? @nikomatsakis cc @pnkfelix @varkor @yodaldevoid @oli-obk @estebank

### CODE REVIEW

**Comment by eddyb** [comment]
Why is there no diff in the test output? That's bizarre. Anyway, I'm rebasing in case that's it.

File: src/librustc_typeck/check/writeback.rs [hunk 1]
```diff
@@ -658,6 +669,7 @@ impl<'cx, 'tcx> TypeFolder<'tcx> for Resolver<'cx, 'tcx> {
                 debug!("Resolver::fold_const: input const `{:?}` not fully resolvable", ct);
                 // FIXME: we'd like to use `self.report_error`, but it doesn't yet
                 // accept a &'tcx ty::Const.
+                self.replaced_with_error = true;
```
Comment (estebank) [inline src/librustc_typeck/check/writeback.rs]: I think the comment is now handled by this change?

File: src/test/ui/const-generics/issues/issue-62456.stderr [hunk 2]
```diff
@@ -6,3 +6,13 @@ LL | #![feature(const_generics)]
    |
    = note: `#[warn(incomplete_features)]` on by default
 
+error: constant expression depends on a generic parameter
+  --> $DIR/issue-62456.rs:5:20
+   |
+LL |     let _ = [0u64; N + 1];
+   |                    ^^^^^
+   |
+   = note: this may fail depending on what value the parameter takes
```
Comment (estebank) [inline src/test/ui/const-generics/issues/issue-62456.stderr]: I think we should improve the wording of the error. In my eyes I would prefer something along the lines of

```
error: constant expression can't depend on generic parameter
  --> $DIR/issue-62456.rs:5:20
   |
LL |     let _ = [0u64; N + 1];
   |                    ^^^^^ depends on a generic parameter
   |
   = note: this will be supported in the future, but isn't now
```

preferably with a link to documentation, tracking issue or its own error code so that we explain _why_ we don't support it yet and when it might be done.

File: src/librustc_typeck/check/writeback.rs (hunk 1 above)
Comment (eddyb) [reply src/librustc_typeck/check/writeback.rs]: No, `report_error` is for an user-facing error message.

File: src/test/ui/const-generics/issues/issue-62456.stderr (hunk 2 above)
Comment (eddyb) [reply src/test/ui/const-generics/issues/issue-62456.stderr]: The error is indeed misleading, because what you're suggesting isn't what the error means.

The error is trying to say that *evaluating* the constant expression may only succeed for some "values" of the generic parameter.
The missing piece of the puzzle is a way to put that expression in a `where` clause to force the caller to evaluate it, ruling out post-monomorphization errors (#68436).

Note that [expressions using generics can still evaluate](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=ba0ae8e0eb712b342a61a776ac52c62f) just fine while remaining polymorphic.

cc @varkor

Comment (varkor) [reply src/test/ui/const-generics/issues/issue-62456.stderr]: I agree that this diagnostic could be improved, especially as it was misinterpreted. How about something like:
```
error: constant expression may not depend on a generic parameter
  --> $DIR/issue-62456.rs:5:20
   |
LL |     let _ = [0u64; N + 1];
   |                    ^^^^^
   |
   = note: this expression may only be valid for some values of `N`, which `N` is guaranteed to take
```
This is a bit long, though this sort of thing hopefully gets the intention across better.

Comment (eddyb) [reply src/test/ui/const-generics/issues/issue-62456.stderr]: "constant expression may **not** depend on a generic parameter"? (emphasis mine)

Comment (Centril) [reply src/test/ui/const-generics/issues/issue-62456.stderr]:
```
   = note: this will be supported in the future, but isn't now
```
(Let's not make promises. ^^)

> "constant expression may **not** depend on a generic parameter"? (emphasis mine)

I think we tend to prefer **cannot* over **may not**. The former is more definitive.

Comment (varkor) [reply src/test/ui/const-generics/issues/issue-62456.stderr]: Maybe `is not allowed to depend`, which makes clear whether the constant expression is supposed to or not.

Comment (eddyb) [reply src/test/ui/const-generics/issues/issue-62456.stderr]: But it *can* depend on generic parameters, the only problem is we have no *guarantor* for it *evaluating* successfully.

So perhaps a better phrasing for the error itself might be "cannot prove/determine/guarantee/etc. that constant expression will evaluate successfully" and then we can search its `Substs` for parameters and list them out to give the more helpful information.

We should also link [`https://github.com/rust-lang/rust/issues/68436`](https://github.com/rust-lang/rust/issues/68436), in some sort of help messaging along the lines of "there is no way to currently write the necessary `where` clause, watch this space".

Comment (varkor) [reply src/test/ui/const-generics/issues/issue-62456.stderr]: Well, I suppose I meant that it could not depend on an "unrestricted" generic parameter (or "guaranteed well-formed"). Yes, it's quite difficult to use language that's both intuitive, and doesn't take up a lot of space. Linking to the issue would be good.

File: src/librustc_typeck/check/writeback.rs (hunk 1 above)
Comment (estebank) [reply src/librustc_typeck/check/writeback.rs]: I see, I got confused when I saw `self.tables.tainted_by_errors |= resolver.replaced_with_error;` and I thought this referred to that.

File: src/test/ui/const-generics/issues/issue-62456.stderr (hunk 2 above)
Comment (estebank) [reply src/test/ui/const-generics/issues/issue-62456.stderr]: +1 on linking to that issue. I would say I've come around to the position that reducing verbosity is a goal, but much lower than correct understandable wording.

**Comment by eddyb** [comment]
Got back to this and it looks like the build failure (https://github.com/rust-lang/rust/pull/70452#issuecomment-604963582) is a pre-existing bug in the MIR type-checker, for which I've opened #70773 and will now attempt to fix in this PR.

File: src/librustc_middle/ty/sty.rs [hunk 3]
```diff
@@ -2400,43 +2400,41 @@ impl<'tcx> Const<'tcx> {
...
+                // can leak through `val` into the const we return.
+                Ok(val) => Const::from_value(tcx, val, self.ty),
+
+                Err(_) => self,
             }
-            _ => self,
+        } else {
+            self
         }
     }
```
Comment (eddyb) [inline src/librustc_middle/ty/sty.rs:2439]: @nikomatsakis NB: this is the entirety of the commit that I mentioned in the PR description as being a false start for fixing #70773 and doesn't have to be in this PR. Let me know what you prefer.

**Comment by eddyb** [comment]
Now that `git2-rs` compiles fine with this PR:

@bors try @rust-timer queue (we'll also want `check-only` crater, but only if perf isn't terrible)

**Comment by eddyb** [comment]
That looks like some bug in toolstate (`KeyError: u'rustc-dev-guide'`).

**Comment by eddyb** [comment]
@craterbot check

**Comment by bjorn3** [comment]
Rand is the root regression for all regressions I checked:

```
[INFO] [stderr] error: internal compiler error: broken MIR in DefId(0:521 ~ rand[bbc7]::prng[0]::chacha[0]::{{impl}}[2]::reseed[0]) (Terminator { source_info: SourceInfo { span: /opt/rustwide/cargo-home/registry/src/github.com-1ecc6299db9ec823/rand-0.4.6/src/prng/chacha.rs:205:9: 205:38, scope: scope[0] }, kind: _3 = const prng::chacha::ChaChaRng::init(move _4, move _5) -> [return: bb2, unwind: bb1] }): bad arg #1 (&[u32; 8] <- &[u32; _]): NoSolution
[INFO] [stderr]    --> /opt/rustwide/cargo-home/registry/src/github.com-1ecc6299db9ec823/rand-0.4.6/src/prng/chacha.rs:205:19
[INFO] [stderr]     |
[INFO] [stderr] 205 |         self.init(&[0u32; KEY_WORDS]);
[INFO] [stderr]     |                   ^^^^^^^^^^^^^^^^^^
[INFO] [stderr] 
[INFO] [stderr] thread 'rustc' panicked at 'no errors encountered even though `delay_span_bug` issued', src/librustc_errors/lib.rs:360:17
```

**Comment by bjorn3** [comment]
Rand has [3548 direct reverse dependencies](https://crates.io/crates/rand/reverse_dependencies) on crates.io, so including indirect reverse depencencies, it is possible that all regressions are caused by rand.

**Comment by eddyb** [comment]
There's only 2734 crates.io regressions, the rest are the user repos. Thanks a lot, this clears it up!

And yeah it looks like the `git2` bug, but for some reason we never use `rand` in our builds *sigh*.

**Comment by eddyb** [comment]
Forgot to say, I can reproduce that with `0.4.5` but not `0.5.0` (but it's clearly just another case of #70773).

**Comment by bjorn3** [comment]
> I can reproduce with `rand 0.4.5` but not `0.5.0`

`0.5.0` rewrote a large part of the chacha implementation to drop a dependency on `c2-chacha`, which isn't maintained anymore.

**Comment by lqd** [comment]
in addition to `rand-0.3.10` to `rand-0.4.6`, on crates.io there's also:
- some versions of [`hibitset`](https://crater-reports.s3.amazonaws.com/pr-70452/try%239c7f5dda251978784558093956db78b4cfe784db/gh/DanvdEnde.hello-rltk/log.txt)
- [`ratman-identity`](https://crater-reports.s3.amazonaws.com/pr-70452/try%239c7f5dda251978784558093956db78b4cfe784db/reg/netmod-mem-0.1.0/log.txt)
- some versions of [`snow`](https://crater-reports.s3.amazonaws.com/pr-70452/try%239c7f5dda251978784558093956db78b4cfe784db/reg/snow-0.7.0-alpha4/log.txt)
- [`stringsext`](https://crater-reports.s3.amazonaws.com/pr-70452/try%239c7f5dda251978784558093956db78b4cfe784db/reg/stringsext-2.3.1/log.txt)

(and a handful of other projects on github)

that's pretty much it

**Comment by eddyb** [comment]
@lqd That's great to know, thanks! All of those look like calls and the ICE mentions "bad arg", so I think it's exactly the same bug.

**Comment by eddyb** [comment]
`rand 0.4.5` and friends should be fixed now:
@bors try @rust-timer queue

**Comment by eddyb** [comment]
@lqd Would it be possible to crater just the (slightly under 10%) subset that regressed on the previous run? Without listing the over-9000 packages individually, that is.

**Comment by eddyb** [comment]
In the meanwhile, let's throw it into the queue:
@craterbot check

**Comment by eddyb** [comment]
@craterbot abort

**Comment by eddyb** [comment]
@lqd told me on IRC about this new crater feature (the exported list of regressions), let's see if it works:

@craterbot check crates=https://crater-reports.s3.amazonaws.com/pr-70452/retry-regressed-list.txt

**Comment by eddyb** [comment]
@nikomatsakis This has cleared Crater and is ready for review.

File: src/librustc_middle/ty/sty.rs (hunk 3 above)
Comment (nikomatsakis) [reply src/librustc_middle/ty/sty.rs:2397]: I don't really understand what this commit is doing exactly. It's erasing lifetimes -- why exactly? And why we do want to do it before checking for inference variables?

**Review by nikomatsakis — APPROVED** [review]
So this all makes sense but I have some questions about the one commit. Still, the code looks cleaner than the original there, so... r=me as is.

**Comment by nikomatsakis** [comment]
But I'd be happy to talk over the role of that commit.

File: src/librustc_middle/ty/sty.rs (hunk 3 above)
Comment (eddyb) [reply src/librustc_middle/ty/sty.rs:2397]: It's erasing lifetimes that would be erased later, just to increase the chances of the inference variable check passing (and doing fully specific evaluation instead of the polymorphic evaluation attempt with identity substs).

Comment (nikomatsakis) [reply src/librustc_middle/ty/sty.rs:2397]: How could it lead to the inference variable check passing when it wouldn't have passed otherwise?

Comment (eddyb) [reply src/librustc_middle/ty/sty.rs:2397]: By erasing *lifetime* inference variables?

Comment (nikomatsakis) [reply src/librustc_middle/ty/sty.rs:2397]: Oh, I see, duh.

Comment (nikomatsakis) [reply src/librustc_middle/ty/sty.rs:2397]: OK, makes sense I guess. Might as well keep it.

File: src/test/ui/const-generics/issues/issue-62456.stderr (hunk 2 above)
Comment (eddyb) [reply src/test/ui/const-generics/issues/issue-62456.stderr:15]: Opened #71142 for this subthread.
