### PR TITLE
Fixing bad suggestion for `_` in `const` type when a function #81885

### LINKED ISSUE #81885: Bad suggestion for `_` in `const` type
As noted in [#81509](https://github.com/rust-lang/rust/pull/81509/files/81ed4cfd0138e68d370873281f53f4e63e5a223f#diff-8bb87d2edef38133d2180f7f80bb3161f1dd9e2cd05071bc7e3a4466e3cb1131), [we currently emit the following suggestion](https://github.com/rust-lang/rust/blob/921ec4b3fca17cc777766c240038d7d50ba98e0d/src/test/ui/typeck/typeck_type_placeholder_item_help.stderr#L28-L35), which is incorrect:

```
error[E0121]: the type placeholder `_` is not allowed within types on item signatures
  --> $DIR/typeck_type_placeholder_item_help.rs:13:22
   |
LL | const TEST4: fn() -> _ = 42;
   |                      ^
   |                      |
   |                      not allowed in type signatures
   |                      help: use type parameters instead: `T`
```

This can be solved by not suggesting type params ever, or at least when `fn()` types are involved.

### PR DESCRIPTION
**Pull request by kper**
Closes #81885

```
error[E0121]: the type placeholder `_` is not allowed within types on item signatures
  --> $DIR/typeck_type_placeholder_item_help.rs:13:22
   |
LL | const TEST4: fn() -> _ = 42;
   |                      ^
   |                      |
   |                      not allowed in type signatures
   |                      help: use type parameters instead: `T`
```

Do not show the suggestion `help: use type parameters instead: T` when `fn`

### CODE REVIEW

File: compiler/rustc_typeck/src/collect.rs [hunk 1]
```diff
@@ -171,7 +172,9 @@ crate fn placeholder_type_error(
     }
 
     let mut err = bad_placeholder_type(tcx, placeholder_types);
-    if suggest {
+
+    // Suggest, but only if it is not a function
+    if suggest && !is_fn {
```
Comment (estebank) [inline compiler/rustc_typeck/src/collect.rs:177]: Ideally we would have a more targeted filter...

File: src/test/ui/did_you_mean/bad-assoc-ty.stderr [hunk 2]
```diff
@@ -129,33 +129,18 @@ LL | fn foo<X: K<_, _>>(x: X) {}
...
 error[E0121]: the type placeholder `_` is not allowed within types on item signatures
   --> $DIR/bad-assoc-ty.rs:52:34
    |
 LL | fn bar<F>(_: F) where F: Fn() -> _ {}
    |                                  ^ not allowed in type signatures
-   |
-help: use type parameters instead
-   |
-LL | fn bar<F, T>(_: F) where F: Fn() -> T {}
-   |         ^^^                         ^
```
Comment (estebank) [inline src/test/ui/did_you_mean/bad-assoc-ty.stderr:147]: ...if you look at these errors, there _are_ cases where we suggest a type parameter correctly. The big problem only happens on `static`s and `const`s are the enclosing item.

File: src/test/ui/typeck/typeck_type_placeholder_item.stderr [hunk 3]
```diff
@@ -92,64 +92,36 @@ error[E0121]: the type placeholder `_` is not allowed within types on item signa
...
-   |         ^^^    ^
 
 error[E0121]: the type placeholder `_` is not allowed within types on item signatures
   --> $DIR/typeck_type_placeholder_item.rs:33:22
    |
 LL | fn test8(_f: fn() -> _) { }
-   |                      ^
-   |                      |
-   |                      not allowed in type signatures
-   |                      help: use type parameters instead: `T`
```
Comment (estebank) [inline src/test/ui/typeck/typeck_type_placeholder_item.stderr:141]: Except for _this_ case where the enclosing item is an `fn`, but we for some reason don't find the right place to add the type parameter.

**Review by estebank — COMMENTED** [review]
I originally thought that a simple filter as you're doing here would be enough, but looking at the result I feel like we might have to do something a bit more involved to be accurate and remain helpful. Would you be interested in exploring alternatives we could have here?

**Comment by kper** [comment]
Thank you for your comments. I will look into it.

**Comment by kper** [comment]
I am currently thinking of ways to implement this filter. But, how can a [function](https://github.com/rust-lang/rust/blob/master/compiler/rustc_typeck/src/astconv/mod.rs#L2332) know that it is in a context of `type`?
Do I have to change something in typing context? https://github.com/rust-lang/rust/blob/master/compiler/rustc_typeck/src/collect.rs#L756

**Comment by kper** [comment]
> I am currently thinking of ways to implement this filter. But, how can a function know that it is in a context of type?
Do I have to change something in typing context? https://github.com/rust-lang/rust/blob/master/compiler/rustc_typeck/src/collect.rs#L756

Nevermind that, I passed the `hir::Ty` which has a reference to the parent_node. This node can I check if it is const or static. 

However, this is not working for `impl` yet

```
fn main() {}
struct MyStruct;

trait Test {
}

impl Test for MyStruct {
    const TEST: fn() -> _ = 42; 
}
``` 

```
error[E0438]: const `TEST` is not a member of trait `Test`
  --> main_test.rs:10:5
   |
10 |     const TEST: fn() -> _ = 42; 
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^ not a member of trait `Test`

error[E0121]: the type placeholder `_` is not allowed within types on item signatures
  --> main_test.rs:10:25
   |
10 |     const TEST: fn() -> _ = 42; 
   |                         ^
   |                         |
   |                         not allowed in type signatures
   |                         help: use type parameters instead: `T`
```

**Comment by estebank** [comment]
@kper that is ok about associated `const`s. The other improvements in the output are more than great.

@bors r+
