### PR TITLE
tidy: split dots in filename not the entire path when checking for stray stdout/stderr files

### LINKED ISSUE #121986: Tons of tidy failures on master
Running `./x.py test tidy` on my checkout with the current master commit fails with tons of errors. here's the last few screens of messages:
```
tidy error: found output file `/home/r/src/rust/rustc.2/tests/ui/borrowck/issue-114374-invalid-help-fmt-args.stderr` for unexpected revision `2/tests/ui/borrowck/issue-114374-invalid-help-fmt-args` of test `/home/r/src/rust/rustc.2/tests/ui/borrowck/unboxed-closures-move-upvar-from-non-once-ref-closure.rs`
tidy error: found output file `/home/r/src/rust/rustc.2/tests/ui/borrowck/issue-11493.stderr` for unexpected revision `2/tests/ui/borrowck/issue-11493` of test `/home/r/src/rust/rustc.2/tests/ui/borrowck/unboxed-closures-move-upvar-from-non-once-ref-closure.rs`
tidy error: found output file `/home/r/src/rust/rustc.2/tests/ui/borrowck/issue-115259-suggest-iter-mut.stderr` for unexpected revision `2/tests/ui/borrowck/issue-115259-suggest-iter-mut` of test `/home/r/src/rust/rustc.2/tests/ui/borrowck/unboxed-closures-move-upvar-from-non-once-ref-closure.rs`
tidy error: found output file `/home/r/src/rust/rustc.2/tests/ui/borrowck/issue-119915-bad-clone-suggestion.stderr` for unexpected revision `2/tests/ui/borrowck/issue-119915-bad-clone-suggestion` of test `/home/r/src/rust/rustc.2/tests/ui/borrowck/unboxed-closures-move-upvar-from-non-once-ref-closure.rs`
tidy error: found output file `/home/r/src/rust/rustc.2/tests/ui/borrowck/issue-17545.stderr` for unexpected revision `2/tests/ui/borrowck/issue-17545` of test `/home/r/src/rust/rustc.2/tests/ui/borrowck/unboxed-closures-move-upvar-from-non-once-ref-closure.rs`
tidy error: found output file `/home/r/src/rust/rustc.2/tests/ui/borrowck/issue-17718-static-move.stderr` for unexpected revision `2/tests/ui/borrowck/issue-17718-static-move` of test `/home/r/src/rust/rustc.2/tests/ui/borrowck/unboxed-closures-move-upvar-from-non-once-ref-closure.rs`
tidy error: found output file `/home/r/src/rust/rustc.2/tests/ui/borrowck/issue-20801.stderr` for unexpected revision `2/tests/ui/borrowck/issue-20801` of test `/home/r/src/rust/rustc.2/tests/ui/borrowck/unboxed-closures-move-upvar-from-non-once-ref-closure.rs`
tidy error: found output file `/home/r/src/rust/rustc.2/tests/ui/borrowck/issue-24267-flow-exit.stderr` for unexpected revision `2/tests/ui/borrowck/issue-24267-flow-exit` of test `/home/r/src/rust/rustc.2/tests/ui/borrowck/unboxed-closures-move-upvar-from-non-once-ref-closure.rs`
tidy error: found output file `/home/r/src/rust/rustc.2/tests/ui/borrowck/issue-25793.stderr` for unexpected revision `2/tests/ui/borrowck/issue-25793` of test `/home/r/src/rust/rustc.2/tests/ui/borrowck/unboxed-closures-move-upvar-from-non-once-ref-closure.rs`
tidy error: found output file `/home/r/src/rust/rustc.2/tests/ui/borrowck/issue-31287-drop-in-guard.stderr` for unexpected revision `2/tests/ui/borrowck/issue-31287-drop-in-guard` of test `/home/r/src/rust/rustc.2/tests/ui/borrowck/unboxed-closures-move-upvar-from-non-once-ref-closure.rs`
tidy error: found output file `/home/r/src/rust/rustc.2/tests/ui/borrowck/issue-33819.stderr` for unexpected revision `2/tests/ui/borrowck/issue-33819` of test `/home/r/src/rust/rustc.2/tests/ui/borrowck/unboxed-closures-move-upvar-from-non-once-ref-closure.rs`
tidy error: found output file `/home/r/src/rust/rustc.2/tests/ui/borrowck/issue-36082.stderr` for unexpected revision `2/tests/ui/borrowck/issue-36082` of test `/home/r/src/rust/rustc.2/tests/ui/borrowck/unboxed-closures-move-upvar-from-non-once-ref-closure.rs`
tidy error: found output file `/home/r/src/rust/rustc.2/tests/ui/borrowck/issue-41962.stderr` for unexpected revision `2/tests/ui/borrowck/issue-41962` of test `/home/r/src/rust/rustc.2/tests/ui/borrowck/unboxed-closures-move-upvar-from-non-once-ref-closure.rs`
tidy error: found output file `/home/r/src/rust/rustc.2/tests/ui/borrowck/issue-42344.stderr` for unexpected revision `2/tests/ui/borrowck/issue-42344` of test `/home/r/src/rust/rustc.2/tests/ui/borrowck/unboxed-closures-move-upvar-from-non-once-ref-closure.rs`
tidy error: found output file `/home/r/src/rust/rustc.2/tests/ui/borrowck/issue-45199.stderr` for unexpected revision `2/tests/ui/borrowck/issue-45199` of test `/home/r/src/rust/rustc.2/tests/ui/borrowck/unboxed-closures-move-upvar-from-non-once-ref-closure.rs`
tidy error: found output file `/home/r/src/rust/rustc.2/tests/ui/borrowck/issue-45983.stderr` for unexpected revision `2/tests/ui/borrowck/issue-45983` of test `/home/r/src/rust/rustc.2/tests/ui/borrowck/unboxed-closures-move-upvar-from-non-once-ref-closure.rs`
tidy error: found output file `/home/r/src/rust/rustc.2/tests/ui/borrowck/issue-46471.stderr` for unexpected revision `2/tests/ui/borrowck/issue-46471` of test `/home/r/src/rust/rustc.2/tests/ui/borrowck/unboxed-closures-move-upvar-from-non-once-ref-closure.rs`
tidy error: found output file `/home/r/src/rust/rustc.2/tests/ui/borrowck/issue-47215-ice-from-drop-elab.stderr` for unexpected revision `2/tests/ui/borrowck/issue-47215-ice-from-drop-elab` of test `/home/r/src/rust/rustc.2/tests/ui/borrowck/unboxed-closures-move-upvar-from-non-once-ref-closure.rs`
tidy error: found output file `/home/r/src/rust/rustc.2/tests/ui/borrowck/issue-47646.stderr` for unexpected revision `2/tests/ui/borrowck/issue-47646` of test `/home/r/src/rust/rustc.2/tests/ui/borrowck/unboxed-closures-move-upvar-from-non-once-ref-closure.rs`
tidy error: found output file `/home/r/src/rust/rustc.2/tests/ui/borrowck/issue-51117.stderr` for unexpected revision `2/tests/ui/borrowck/issue-51117` of test `/home/r/src/rust/rustc.2/tests/ui/borrowck/unboxed-closures-move-upvar-from-non-once-ref-closure.rs`
tidy error: found output file `/home/r/src/rust/rustc.2/tests/ui/borrowck/issue-51301.stderr` for unexpected revision `2/tests/ui/borrowck/issue-51301` of test `/home/r/src/rust/rustc.2/tests/ui/borrowck/unboxed-closures-move-upvar-from-non-once-ref-closure.rs`
tidy error: found output file `/home/r/src/rust/rustc.2/tests/ui/borrowck/issue-51415.stderr` for unexpected revision `2/tests/ui/borrowck/issue-51415` of test `/home/r/src/rust/rustc.2/tests/ui/borrowck/unboxed-closures-move-upvar-from-non-once-ref-closure.rs`
tidy error: found output file `/home/r/src/rust/rustc.2/tests/ui/borrowck/issue-52713-bug.stderr` for unexpected revision `2/tests/ui/borrowck/issue-52713-bug` of test `/home/r/src/rust/rustc.2/tests/ui/borrowck/unboxed-closures-move-upvar-from-non-once-ref-closure.rs`
tidy error: found output file `/home/r/src/rust/rustc.2/tests/ui/borrowck/issue-53432-nested-closure-outlives-borrowed-value.stderr` for unexpected revision `2/tests/ui/borrowck/issue-53432-nested-closure-outlives-borrowed-value` of test `/home/r/src/rust/rustc.2/tests/ui/borrowck/unboxed-closures-move-upvar-from-non-once-ref-closure.rs`
tidy error: found output file `/home/r/src/rust/rustc.2/tests/ui/borrowck/issue-54499-field-mutation-marks-mut-as-used.stderr` for unexpected revision `2/tests/ui/borrowck/issue-54499-field-mutation-marks-mut-as-used` of test `/home/r/src/rust/rustc.2/tests/ui/borrowck/unboxed-closures-move-upvar-from-non-once-ref-closure.rs`
tidy error: found output file `/home/r/src/rust/rustc.2/tests/ui/borrowck/issue-54499-field-mutation-of-moved-out-with-mut.stderr` for unexpected revision `2/tests/ui/borrowck/issue-54499-field-mutation-of-moved-out-with-mut` of test `/home/r/src/rust/rustc.2/tests/ui/borrowck/unboxed-closures-move-upvar-from-non-once-ref-closure.rs`
tidy error: found output file `/home/r/src/rust/rustc.2/tests/ui/borrowck/issue-54499-field-mutation-of-moved-out.stderr` for unexpected revision `2/tests/ui/borrowck/issue-54499-field-mutation-of-moved-out` of test `/home/r/src/rust/rustc.2/tests/ui/borrowck/unboxed-closures-move-upvar-from-non-once-ref-closure.rs`
tidy error: found output file `/home/r/src/rust/rustc.2/tests/ui/borrowck/issue-54499-field-mutation-of-never-init.stderr` for unexpected revision `2/tests/ui/borrowck/issue-54499-field-mutation-of-never-init` of test `/home/r/src/rust/rustc.2/tests/ui/borrowck/unboxed-closures-move-upvar-from-non-once-ref-closure.rs`
tidy error: found output file `/home/r/src/rust/rustc.2/tests/ui/borrowck/issue-54597-reject-move-out-of-borrow-via-pat.stderr` for unexpected revision `2/tests/ui/borrowck/issue-54597-reject-move-out-of-borrow-via-pat` of test `/home/r/src/rust/rustc.2/tests/ui/borrowck/unboxed-closures-move-upvar-from-non-once-ref-closure.rs`
tidy error: found output file `/home/r/src/rust/rustc.2/tests/ui/borrowck/issue-55492-borrowck-migrate-scans-parents.stderr` for unexpected revision `2/tests/ui/borrowck/issue-55492-borrowck-migrate-scans-parents` of test `/home/r/src/rust/rustc.2/tests/ui/borrowck/unboxed-closures-move-upvar-from-non-once-ref-closure.rs`
tidy error: found output file `/home/r/src/rust/rustc.2/tests/ui/borrowck/issue-58776-borrowck-scans-children.stderr` for unexpected revision `2/tests/ui/borrowck/issue-58776-borrowck-scans-children` of test `/home/r/src/rust/rustc.2/tests/ui/borrowck/unboxed-closures-move-upvar-from-non-once-ref-closure.rs`
tidy error: found output file `/home/r/src/rust/rustc.2/tests/ui/borrowck/issue-62107-match-arm-scopes.stderr` for unexpected revision `2/tests/ui/borrowck/issue-62107-match-arm-scopes` of test `/home/r/src/rust/rustc.2/tests/ui/borrowck/unboxed-closures-move-upvar-from-non-once-ref-closure.rs`
tidy error: found output file `/home/r/src/rust/rustc.2/tests/ui/borrowck/issue-62387-suggest-iter-mut-2.stderr` for unexpected revision `2/tests/ui/borrowck/issue-62387-suggest-iter-mut-2` of test `/home/r/src/rust/rustc.2/tests/ui/borrowck/unboxed-closures-move-upvar-from-non-once-ref-closure.rs`
tidy error: found output file `/home/r/src/rust/rustc.2/tests/ui/borrowck/issue-62387-suggest-iter-mut.stderr` for unexpected revision `2/tests/ui/borrowck/issue-62387-suggest-iter-mut` of test `/home/r/src/rust/rustc.2/tests/ui/borrowck/unboxed-closures-move-upvar-from-non-once-ref-closure.rs`
tidy error: found output file `/home/r/src/rust/rustc.2/tests/ui/borrowck/issue-64453.stderr` for unexpected revision `2/tests/ui/borrowck/issue-64453` of test `/home/r/src/rust/rustc.2/tests/ui/borrowck/unboxed-closures-move-upvar-from-non-once-ref-closure.rs`
tidy error: found output file `/home/r/src/rust/rustc.2/tests/ui/borrowck/issue-69789-iterator-mut-suggestion.stderr` for unexpected revision `2/tests/ui/borrowck/issue-69789-iterator-mut-suggestion` of test `/home/r/src/rust/rustc.2/tests/ui/borrowck/unboxed-closures-move-upvar-from-non-once-ref-closure.rs`
tidy error: found output file `/home/r/src/rust/rustc.2/tests/ui/borrowck/issue-7573.stderr` for unexpected revision `2/tests/ui/borrowck/issue-7573` of test `/home/r/src/rust/rustc.2/tests/ui/borrowck/unboxed-closures-move-upvar-from-non-once-ref-closure.rs`
tidy error: found output file `/home/r/src/rust/rustc.2/tests/ui/borrowck/issue-81365-1.stderr` for unexpected revision `2/tests/ui/borrowck/issue-81365-1` of test `/home/r/src/rust/rustc.2/tests/ui/borrowck/unboxed-closures-move-upvar-from-non-once-ref-closure.rs`
tidy error: found output file `/home/r/src/rust/rustc.2/tests/ui/borrowck/issue-81365-10.stderr` for unexpected revision `2/tests/ui/borrowck/issue-81365-10` of test `/home/r/src/rust/rustc.2/tests/ui/borrowck/unboxed-closures-move-upvar-from-non-once-ref-closure.rs`
tidy error: found output file `/home/r/src/rust/rustc.2/tests/ui/borrowck/issue-81365-11.stderr` for unexpected revision `2/tests/ui/borrowck/issue-81365-11` of test `/home/r/src/rust/rustc.2/tests/ui/borrowck/unboxed-closures-move-upvar-from-non-once-ref-closure.rs`
tidy error: found output file `/home/r/src/rust/rustc.2/tests/ui/borrowck/issue-81365-2.stderr` for unexpected revision `2/tests/ui/borrowck/issue-81365-2` of test `/home/r/src/rust/rustc.2/tests/ui/borrowck/unboxed-closures-move-upvar-from-non-once-ref-closure.rs`
tidy error: found output file `/home/r/src/rust/rustc.2/tests/ui/borrowck/issue-81365-3.stderr` for unexpected revision `2/tests/ui/borrowck/issue-81365-3` of test `/home/r/src/rust/rustc.2/tests/ui/borrowck/unboxed-closures-move-upvar-from-non-once-ref-closure.rs`
tidy error: found output file `/home/r/src/rust/rustc.2/tests/ui/borrowck/issue-81365-4.stderr` for unexpected revision `2/tests/ui/borrowck/issue-81365-4` of test `/home/r/src/rust/rustc.2/tests/ui/borrowck/unboxed-closures-move-upvar-from-non-once-ref-closure.rs`
tidy error: found output file `/home/r/src/rust/rustc.2/tests/ui/borrowck/issue-81365-5.stderr` for unexpected revision `2/tests/ui/borrowck/issue-81365-5` of test `/home/r/src/rust/rustc.2/tests/ui/borrowck/unboxed-closures-move-upvar-from-non-once-ref-closure.rs`
tidy error: found output file `/home/r/src/rust/rustc.2/tests/ui/borrowck/issue-81365-6.stderr` for unexpected revision `2/tests/ui/borrowck/issue-81365-6` of test `/home/r/src/rust/rustc.2/tests/ui/borrowck/unboxed-closures-move-upvar-from-non-once-ref-closure.rs`
tidy error: found output file `/home/r/src/rust/rustc.2/tests/ui/borrowck/issue-81365-7.stderr` for unexpected revision `2/tests/ui/borrowck/issue-81365-7` of test `/home/r/src/rust/rustc.2/tests/ui/borrowck/unboxed-closures-move-upvar-from-non-once-ref-closure.rs`
tidy error: found output file `/home/r/src/rust/rustc.2/tests/ui/borrowck/issue-81365-8.stderr` for unexpected revision `2/tests/ui/borrowck/issue-81365-8` of test `/home/r/src/rust/rustc.2/tests/ui/borrowck/unboxed-closures-move-upvar-from-non-once-ref-closure.rs`
tidy error: found output file `/home/r/src/rust/rustc.2/tests/ui/borrowck/issue-81365-9.stderr` for unexpected revision `2/tests/ui/borrowck/issue-81365-9` of test `/home/r/src/rust/rustc.2/tests/ui/borrowck/unboxed-closures-move-upvar-from-non-once-ref-closure.rs`
tidy error: found output file `/home/r/src/rust/rustc.2/tests/ui/borrowck/issue-81899.stderr` for unexpected revision `2/tests/ui/borrowck/issue-81899` of test `/home/r/src/rust/rustc.2/tests/ui/borrowck/unboxed-closures-move-upvar-from-non-once-ref-closure.rs`
tidy error: found output file `/home/r/src/rust/rustc.2/tests/ui/borrowck/issue-82032.stderr` for unexpected revision `2/tests/ui/borrowck/issue-82032` of test `/home/r/src/rust/rustc.2/tests/ui/borrowck/unboxed-closures-move-upvar-from-non-once-ref-closure.rs`
tidy error: found output file `/home/r/src/rust/rustc.2/tests/ui/borrowck/issue-82126-mismatched-subst-and-hir.stderr` for unexpected revision `2/tests/ui/borrowck/issue-82126-mismatched-subst-and-hir` of test `/home/r/src/rust/rustc.2/tests/ui/borrowck/unboxed-closures-move-upvar-from-non-once-ref-closure.rs`
tidy error: found output file `/home/r/src/rust/rustc.2/tests/ui/borrowck/issue-82462.stderr` for unexpected revision `2/tests/ui/borrowck/issue-82462` of test `/home/r/src/rust/rustc.2/tests/ui/borrowck/unboxed-closures-move-upvar-from-non-once-ref-closure.rs`
tidy error: found output file `/home/r/src/rust/rustc.2/tests/ui/borrowck/issue-83309-ice-immut-in-for-loop.stderr` for unexpected revision `2/tests/ui/borrowck/issue-83309-ice-immut-in-for-loop` of test `/home/r/src/rust/rustc.2/tests/ui/borrowck/unboxed-closures-move-upvar-from-non-once-ref-closure.rs`
tidy error: found output file `/home/r/src/rust/rustc.2/tests/ui/borrowck/issue-83760.stderr` for unexpected revision `2/tests/ui/borrowck/issue-83760` of test `/home/r/src/rust/rustc.2/tests/ui/borrowck/unboxed-closures-move-upvar-from-non-once-ref-closure.rs`
tidy error: found output file `/home/r/src/rust/rustc.2/tests/ui/borrowck/issue-83924.stderr` for unexpected revision `2/tests/ui/borrowck/issue-83924` of test `/home/r/src/rust/rustc.2/tests/ui/borrowck/unboxed-closures-move-upvar-from-non-once-ref-closure.rs`
tidy error: found output file `/home/r/src/rust/rustc.2/tests/ui/borrowck/issue-85581.stderr` for unexpected revision `2/tests/ui/borrowck/issue-85581` of test `/home/r/src/rust/rustc.2/tests/ui/borrowck/unboxed-closures-move-upvar-from-non-once-ref-closure.rs`
tidy error: found output file `/home/r/src/rust/rustc.2/tests/ui/borrowck/issue-85765-closure.stderr` for unexpected revision `2/tests/ui/borrowck/issue-85765-closure` of test `/home/r/src/rust/rustc.2/tests/ui/borrowck/unboxed-closures-move-upvar-from-non-once-ref-closure.rs`
tidy error: found output file `/home/r/src/rust/rustc.2/tests/ui/borrowck/issue-85765.stderr` for unexpected revision `2/tests/ui/borrowck/issue-85765` of test `/home/r/src/rust/rustc.2/tests/ui/borrowck/unboxed-closures-move-upvar-from-non-once-ref-closure.rs`
tidy error: found output file `/home/r/src/rust/rustc.2/tests/ui/borrowck/issue-87456-point-to-closure.stderr` for unexpected revision `2/tests/ui/borrowck/issue-87456-point-to-closure` of test `/home/r/src/rust/rustc.2/tests/ui/borrowck/unboxed-closures-move-upvar-from-non-once-ref-closure.rs`
tidy error: found output file `/home/r/src/rust/rustc.2/tests/ui/borrowck/issue-88434-minimal-example.stderr` for unexpected revision `2/tests/ui/borrowck/issue-88434-minimal-example` of test `/home/r/src/rust/rustc.2/tests/ui/borrowck/unboxed-closures-move-upvar-from-non-once-ref-closure.rs`
tidy error: found output file `/home/r/src/rust/rustc.2/tests/ui/borrowck/issue-88434-removal-index-should-be-less.stderr` for unexpected revision `2/tests/ui/borrowck/issue-88434-removal-index-should-be-less` of test `/home/r/src/rust/rustc.2/tests/ui/borrowck/unboxed-closures-move-upvar-from-non-once-ref-closure.rs`
tidy error: found output file `/home/r/src/rust/rustc.2/tests/ui/borrowck/issue-91206.stderr` for unexpected revision `2/tests/ui/borrowck/issue-91206` of test `/home/r/src/rust/rustc.2/tests/ui/borrowck/unboxed-closures-move-upvar-from-non-once-ref-closure.rs`
tidy error: found output file `/home/r/src/rust/rustc.2/tests/ui/borrowck/issue-92015.stderr` for unexpected revision `2/tests/ui/borrowck/issue-92015` of test `/home/r/src/rust/rustc.2/tests/ui/borrowck/unboxed-closures-move-upvar-from-non-once-ref-closure.rs`
tidy error: found output file `/home/r/src/rust/rustc.2/tests/ui/borrowck/issue-92157.stderr` for unexpected revision `2/tests/ui/borrowck/issue-92157` of test `/home/r/src/rust/rustc.2/tests/ui/borrowck/unboxed-closures-move-upvar-from-non-once-ref-closure.rs`
tidy error: found output file `/home/r/src/rust/rustc.2/tests/ui/borrowck/issue-93078.stderr` for unexpected revision `2/tests/ui/borrowck/issue-93078` of test `/home/r/src/rust/rustc.2/tests/ui/borrowck/unboxed-closures-move-upvar-from-non-once-ref-closure.rs`
tidy error: found output file `/home/r/src/rust/rustc.2/tests/ui/borrowck/issue-93093.stderr` for unexpected revision `2/tests/ui/borrowck/issue-93093` of test `/home/r/src/rust/rustc.2/tests/ui/borrowck/unboxed-closures-move-upvar-from-non-once-ref-closure.rs`
tidy error: found output file `/home/r/src/rust/rustc.2/tests/ui/borrowck/issue-95079-missing-move-in-nested-closure.stderr` for unexpected revision `2/tests/ui/borrowck/issue-95079-missing-move-in-nested-closure` of test `/home/r/src/rust/rustc.2/tests/ui/borrowck/unboxed-closures-move-upvar-from-non-once-ref-closure.rs`
tidy error: found output file `/home/r/src/rust/rustc.2/tests/ui/borrowck/let_underscore_temporary.stderr` for unexpected revision `2/tests/ui/borrowck/let_underscore_temporary` of test `/home/r/src/rust/rustc.2/tests/ui/borrowck/unboxed-closures-move-upvar-from-non-once-ref-closure.rs`
tidy error: found output file `/home/r/src/rust/rustc.2/tests/ui/borrowck/many-mutable-borrows.stderr` for unexpected revision `2/tests/ui/borrowck/many-mutable-borrows` of test `/home/r/src/rust/rustc.2/tests/ui/borrowck/unboxed-closures-move-upvar-from-non-once-ref-closure.rs`
tidy error: found output file `/home/r/src/rust/rustc.2/tests/ui/borrowck/move-error-in-promoted-2.stderr` for unexpected revision `2/tests/ui/borrowck/move-error-in-promoted-2` of test `/home/r/src/rust/rustc.2/tests/ui/borrowck/unboxed-closures-move-upvar-from-non-once-ref-closure.rs`
tidy error: found output file `/home/r/src/rust/rustc.2/tests/ui/borrowck/move-error-in-promoted.stderr` for unexpected revision `2/tests/ui/borrowck/move-error-in-promoted` of test `/home/r/src/rust/rustc.2/tests/ui/borrowck/unboxed-closures-move-upvar-from-non-once-ref-closure.rs`
tidy error: found output file `/home/r/src/rust/rustc.2/tests/ui/borrowck/move-error-snippets.stderr` for unexpected revision `2/tests/ui/borrowck/move-error-snippets` of test `/home/r/src/rust/rustc.2/tests/ui/borrowck/unboxed-closures-move-upvar-from-non-once-ref-closure.rs`
tidy error: found output file `/home/r/src/rust/rustc.2/tests/ui/borrowck/move-from-union-field-issue-66500.stderr` for unexpected revision `2/tests/ui/borrowck/move-from-union-field-issue-66500` of test `/home/r/src/rust/rustc.2/tests/ui/borrowck/unboxed-closures-move-upvar-from-non-once-ref-closure.rs`
tidy error: found output file `/home/r/src/rust/rustc.2/tests/ui/borrowck/move-in-pattern-mut-in-loop.stderr` for unexpected revision `2/tests/ui/borrowck/move-in-pattern-mut-in-loop` of test `/home/r/src/rust/rustc.2/tests/ui/borrowck/unboxed-closures-move-upvar-from-non-once-ref-closure.rs`
tidy error: found output file `/home/r/src/rust/rustc.2/tests/ui/borrowck/move-in-pattern-mut.stderr` for unexpected revision `2/tests/ui/borrowck/move-in-pattern-mut` of test `/home/r/src/rust/rustc.2/tests/ui/borrowck/unboxed-closures-move-upvar-from-non-once-ref-closure.rs`
tidy error: found output file `/home/r/src/rust/rustc.2/tests/ui/borrowck/move-in-pattern.stderr` for unexpected revision `2/tests/ui/borrowck/move-in-pattern` of test `/home/r/src/rust/rustc.2/tests/ui/borrowck/unboxed-closures-move-upvar-from-non-once-ref-closure.rs`
tidy error: found output file `/home/r/src/rust/rustc.2/tests/ui/borrowck/move-in-static-initializer-issue-38520.stderr` for unexpected revision `2/tests/ui/borrowck/move-in-static-initializer-issue-38520` of test `/home/r/src/rust/rustc.2/tests/ui/borrowck/unboxed-closures-move-upvar-from-non-once-ref-closure.rs`
tidy error: found output file `/home/r/src/rust/rustc.2/tests/ui/borrowck/mut-borrow-in-loop-2.stderr` for unexpected revision `2/tests/ui/borrowck/mut-borrow-in-loop-2` of test `/home/r/src/rust/rustc.2/tests/ui/borrowck/unboxed-closures-move-upvar-from-non-once-ref-closure.rs`
tidy error: found output file `/home/r/src/rust/rustc.2/tests/ui/borrowck/mut-borrow-in-loop.stderr` for unexpected revision `2/tests/ui/borrowck/mut-borrow-in-loop` of test `/home/r/src/rust/rustc.2/tests/ui/borrowck/unboxed-closures-move-upvar-from-non-once-ref-closure.rs`
tidy error: found output file `/home/r/src/rust/rustc.2/tests/ui/borrowck/mut-borrow-of-mut-ref.stderr` for unexpected revision `2/tests/ui/borrowck/mut-borrow-of-mut-ref` of test `/home/r/src/rust/rustc.2/tests/ui/borrowck/unboxed-closures-move-upvar-from-non-once-ref-closure.rs`
tidy error: found output file `/home/r/src/rust/rustc.2/tests/ui/borrowck/mut-borrow-outside-loop.stderr` for unexpected revision `2/tests/ui/borrowck/mut-borrow-outside-loop` of test `/home/r/src/rust/rustc.2/tests/ui/borrowck/unboxed-closures-move-upvar-from-non-once-ref-closure.rs`
tidy error: found output file `/home/r/src/rust/rustc.2/tests/ui/borrowck/mutability-errors.stderr` for unexpected revision `2/tests/ui/borrowck/mutability-errors` of test `/home/r/src/rust/rustc.2/tests/ui/borrowck/unboxed-closures-move-upvar-from-non-once-ref-closure.rs`
tidy error: found output file `/home/r/src/rust/rustc.2/tests/ui/borrowck/or-patterns.stderr` for unexpected revision `2/tests/ui/borrowck/or-patterns` of test `/home/r/src/rust/rustc.2/tests/ui/borrowck/unboxed-closures-move-upvar-from-non-once-ref-closure.rs`
tidy error: found output file `/home/r/src/rust/rustc.2/tests/ui/borrowck/promote-ref-mut-in-let-issue-46557.stderr` for unexpected revision `2/tests/ui/borrowck/promote-ref-mut-in-let-issue-46557` of test `/home/r/src/rust/rustc.2/tests/ui/borrowck/unboxed-closures-move-upvar-from-non-once-ref-closure.rs`
tidy error: found output file `/home/r/src/rust/rustc.2/tests/ui/borrowck/reassignment_immutable_fields.stderr` for unexpected revision `2/tests/ui/borrowck/reassignment_immutable_fields` of test `/home/r/src/rust/rustc.2/tests/ui/borrowck/unboxed-closures-move-upvar-from-non-once-ref-closure.rs`
tidy error: found output file `/home/r/src/rust/rustc.2/tests/ui/borrowck/reassignment_immutable_fields_overlapping.stderr` for unexpected revision `2/tests/ui/borrowck/reassignment_immutable_fields_overlapping` of test `/home/r/src/rust/rustc.2/tests/ui/borrowck/unboxed-closures-move-upvar-from-non-once-ref-closure.rs`
tidy error: found output file `/home/r/src/rust/rustc.2/tests/ui/borrowck/reassignment_immutable_fields_twice.stderr` for unexpected revision `2/tests/ui/borrowck/reassignment_immutable_fields_twice` of test `/home/r/src/rust/rustc.2/tests/ui/borrowck/unboxed-closures-move-upvar-from-non-once-ref-closure.rs`
tidy error: found output file `/home/r/src/rust/rustc.2/tests/ui/borrowck/reborrow-sugg-move-then-borrow.stderr` for unexpected revision `2/tests/ui/borrowck/reborrow-sugg-move-then-borrow` of test `/home/r/src/rust/rustc.2/tests/ui/borrowck/unboxed-closures-move-upvar-from-non-once-ref-closure.rs`
tidy error: found output file `/home/r/src/rust/rustc.2/tests/ui/borrowck/regions-bound-missing-bound-in-impl.stderr` for unexpected revision `2/tests/ui/borrowck/regions-bound-missing-bound-in-impl` of test `/home/r/src/rust/rustc.2/tests/ui/borrowck/unboxed-closures-move-upvar-from-non-once-ref-closure.rs`
tidy error: found output file `/home/r/src/rust/rustc.2/tests/ui/borrowck/regions-escape-bound-fn-2.stderr` for unexpected revision `2/tests/ui/borrowck/regions-escape-bound-fn-2` of test `/home/r/src/rust/rustc.2/tests/ui/borrowck/unboxed-closures-move-upvar-from-non-once-ref-closure.rs`
tidy error: found output file `/home/r/src/rust/rustc.2/tests/ui/borrowck/regions-escape-bound-fn.stderr` for unexpected revision `2/tests/ui/borrowck/regions-escape-bound-fn` of test `/home/r/src/rust/rustc.2/tests/ui/borrowck/unboxed-closures-move-upvar-from-non-once-ref-closure.rs`
tidy error: found output file `/home/r/src/rust/rustc.2/tests/ui/borrowck/regions-escape-unboxed-closure.stderr` for unexpected revision `2/tests/ui/borrowck/regions-escape-unboxed-closure` of test `/home/r/src/rust/rustc.2/tests/ui/borrowck/unboxed-closures-move-upvar-from-non-once-ref-closure.rs`
tidy error: found output file `/home/r/src/rust/rustc.2/tests/ui/borrowck/return-local-binding-from-desugaring.stderr` for unexpected revision `2/tests/ui/borrowck/return-local-binding-from-desugaring` of test `/home/r/src/rust/rustc.2/tests/ui/borrowck/unboxed-closures-move-upvar-from-non-once-ref-closure.rs`
tidy error: found output file `/home/r/src/rust/rustc.2/tests/ui/borrowck/slice-index-bounds-check-invalidation.stderr` for unexpected revision `2/tests/ui/borrowck/slice-index-bounds-check-invalidation` of test `/home/r/src/rust/rustc.2/tests/ui/borrowck/unboxed-closures-move-upvar-from-non-once-ref-closure.rs`
tidy error: found output file `/home/r/src/rust/rustc.2/tests/ui/borrowck/suggest-as-ref-on-mut-closure.stderr` for unexpected revision `2/tests/ui/borrowck/suggest-as-ref-on-mut-closure` of test `/home/r/src/rust/rustc.2/tests/ui/borrowck/unboxed-closures-move-upvar-from-non-once-ref-closure.rs`
tidy error: found output file `/home/r/src/rust/rustc.2/tests/ui/borrowck/suggest-assign-rvalue.stderr` for unexpected revision `2/tests/ui/borrowck/suggest-assign-rvalue` of test `/home/r/src/rust/rustc.2/tests/ui/borrowck/unboxed-closures-move-upvar-from-non-once-ref-closure.rs`
tidy error: found output file `/home/r/src/rust/rustc.2/tests/ui/borrowck/suggest-local-var-double-mut.stderr` for unexpected revision `2/tests/ui/borrowck/suggest-local-var-double-mut` of test `/home/r/src/rust/rustc.2/tests/ui/borrowck/unboxed-closures-move-upvar-from-non-once-ref-closure.rs`
tidy error: found output file `/home/r/src/rust/rustc.2/tests/ui/borrowck/suggest-local-var-for-vector.stderr` for unexpected revision `2/tests/ui/borrowck/suggest-local-var-for-vector` of test `/home/r/src/rust/rustc.2/tests/ui/borrowck/unboxed-closures-move-upvar-from-non-once-ref-closure.rs`
tidy error: found output file `/home/r/src/rust/rustc.2/tests/ui/borrowck/suggest-local-var-imm-and-mut.stderr` for unexpected revision `2/tests/ui/borrowck/suggest-local-var-imm-and-mut` of test `/home/r/src/rust/rustc.2/tests/ui/borrowck/unboxed-closures-move-upvar-from-non-once-ref-closure.rs`
tidy error: found output file `/home/r/src/rust/rustc.2/tests/ui/borrowck/suggest-lt-on-ty-alias-w-generics.stderr` for unexpected revision `2/tests/ui/borrowck/suggest-lt-on-ty-alias-w-generics` of test `/home/r/src/rust/rustc.2/tests/ui/borrowck/unboxed-closures-move-upvar-from-non-once-ref-closure.rs`
tidy error: found output file `/home/r/src/rust/rustc.2/tests/ui/borrowck/suggest-mut-iterator.stderr` for unexpected revision `2/tests/ui/borrowck/suggest-mut-iterator` of test `/home/r/src/rust/rustc.2/tests/ui/borrowck/unboxed-closures-move-upvar-from-non-once-ref-closure.rs`
tidy error: found output file `/home/r/src/rust/rustc.2/tests/ui/borrowck/suggest-storing-local-var-for-vector.stderr` for unexpected revision `2/tests/ui/borrowck/suggest-storing-local-var-for-vector` of test `/home/r/src/rust/rustc.2/tests/ui/borrowck/unboxed-closures-move-upvar-from-non-once-ref-closure.rs`
tidy error: found output file `/home/r/src/rust/rustc.2/tests/ui/borrowck/tainted-promoteds.stderr` for unexpected revision `2/tests/ui/borrowck/tainted-promoteds` of test `/home/r/src/rust/rustc.2/tests/ui/borrowck/unboxed-closures-move-upvar-from-non-once-ref-closure.rs`
tidy error: found output file `/home/r/src/rust/rustc.2/tests/ui/borrowck/two-phase-across-loop.stderr` for unexpected revision `2/tests/ui/borrowck/two-phase-across-loop` of test `/home/r/src/rust/rustc.2/tests/ui/borrowck/unboxed-closures-move-upvar-from-non-once-ref-closure.rs`
tidy error: found output file `/home/r/src/rust/rustc.2/tests/ui/borrowck/two-phase-activation-sharing-interference.nll_target.stderr` for unexpected revision `2/tests/ui/borrowck/two-phase-activation-sharing-interference` of test `/home/r/src/rust/rustc.2/tests/ui/borrowck/unboxed-closures-move-upvar-from-non-once-ref-closure.rs`
tidy error: found output file `/home/r/src/rust/rustc.2/tests/ui/borrowck/two-phase-allow-access-during-reservation.nll_target.stderr` for unexpected revision `2/tests/ui/borrowck/two-phase-allow-access-during-reservation` of test `/home/r/src/rust/rustc.2/tests/ui/borrowck/unboxed-closures-move-upvar-from-non-once-ref-closure.rs`
tidy error: found output file `/home/r/src/rust/rustc.2/tests/ui/borrowck/two-phase-cannot-nest-mut-self-calls.stderr` for unexpected revision `2/tests/ui/borrowck/two-phase-cannot-nest-mut-self-calls` of test `/home/r/src/rust/rustc.2/tests/ui/borrowck/unboxed-closures-move-upvar-from-non-once-ref-closure.rs`
tidy error: found output file `/home/r/src/rust/rustc.2/tests/ui/borrowck/two-phase-multi-mut.stderr` for unexpected revision `2/tests/ui/borrowck/two-phase-multi-mut` of test `/home/r/src/rust/rustc.2/tests/ui/borrowck/unboxed-closures-move-upvar-from-non-once-ref-closure.rs`
tidy error: found output file `/home/r/src/rust/rustc.2/tests/ui/borrowck/two-phase-nonrecv-autoref.base.stderr` for unexpected revision `2/tests/ui/borrowck/two-phase-nonrecv-autoref` of test `/home/r/src/rust/rustc.2/tests/ui/borrowck/unboxed-closures-move-upvar-from-non-once-ref-closure.rs`
tidy error: found output file `/home/r/src/rust/rustc.2/tests/ui/borrowck/two-phase-reservation-sharing-interference-2.stderr` for unexpected revision `2/tests/ui/borrowck/two-phase-reservation-sharing-interference-2` of test `/home/r/src/rust/rustc.2/tests/ui/borrowck/unboxed-closures-move-upvar-from-non-once-ref-closure.rs`
tidy error: found output file `/home/r/src/rust/rustc.2/tests/ui/borrowck/two-phase-reservation-sharing-interference.nll_target.stderr` for unexpected revision `2/tests/ui/borrowck/two-phase-reservation-sharing-interference` of test `/home/r/src/rust/rustc.2/tests/ui/borrowck/unboxed-closures-move-upvar-from-non-once-ref-closure.rs`
tidy error: found output file `/home/r/src/rust/rustc.2/tests/ui/borrowck/two-phase-sneaky.stderr` for unexpected revision `2/tests/ui/borrowck/two-phase-sneaky` of test `/home/r/src/rust/rustc.2/tests/ui/borrowck/unboxed-closures-move-upvar-from-non-once-ref-closure.rs`
tidy error: found output file `/home/r/src/rust/rustc.2/tests/ui/borrowck/two-phase-surprise-no-conflict.stderr` for unexpected revision `2/tests/ui/borrowck/two-phase-surprise-no-conflict` of test `/home/r/src/rust/rustc.2/tests/ui/borrowck/unboxed-closures-move-upvar-from-non-once-ref-closure.rs`
tidy error: found output file `/home/r/src/rust/rustc.2/tests/ui/borrowck/unboxed-closures-move-upvar-from-non-once-ref-closure.stderr` for unexpected revision `2/tests/ui/borrowck/unboxed-closures-move-upvar-from-non-once-ref-closure` of test `/home/r/src/rust/rustc.2/tests/ui/borrowck/unboxed-closures-move-upvar-from-non-once-ref-closure.rs`
tidy error: found output file `/home/r/src/rust/rustc.2/tests/ui/borrowck/alias-liveness/escaping-bounds-2.stderr` for unexpected revision `2/tests/ui/borrowck/alias-liveness/escaping-bounds-2` of test `/home/r/src/rust/rustc.2/tests/ui/borrowck/alias-liveness/rtn-static.rs`
tidy error: found output file `/home/r/src/rust/rustc.2/tests/ui/borrowck/alias-liveness/higher-ranked-outlives-for-capture.stderr` for unexpected revision `2/tests/ui/borrowck/alias-liveness/higher-ranked-outlives-for-capture` of test `/home/r/src/rust/rustc.2/tests/ui/borrowck/alias-liveness/rtn-static.rs`
tidy error: found output file `/home/r/src/rust/rustc.2/tests/ui/borrowck/alias-liveness/opaque-type-param.stderr` for unexpected revision `2/tests/ui/borrowck/alias-liveness/opaque-type-param` of test `/home/r/src/rust/rustc.2/tests/ui/borrowck/alias-liveness/rtn-static.rs`
tidy error: found output file `/home/r/src/rust/rustc.2/tests/ui/borrowck/alias-liveness/rtn-static.stderr` for unexpected revision `2/tests/ui/borrowck/alias-liveness/rtn-static` of test `/home/r/src/rust/rustc.2/tests/ui/borrowck/alias-liveness/rtn-static.rs`
tidy error: found output file `/home/r/src/rust/rustc.2/tests/ui/functional-struct-update/functional-struct-update-noncopyable.stderr` for unexpected revision `2/tests/ui/functional-struct-update/functional-struct-update-noncopyable` of test `/home/r/src/rust/rustc.2/tests/ui/functional-struct-update/functional-struct-update-respects-privacy.rs`
tidy error: found output file `/home/r/src/rust/rustc.2/tests/ui/functional-struct-update/functional-struct-update-respects-privacy.stderr` for unexpected revision `2/tests/ui/functional-struct-update/functional-struct-update-respects-privacy` of test `/home/r/src/rust/rustc.2/tests/ui/functional-struct-update/functional-struct-update-respects-privacy.rs`
tidy error: found output file `/home/r/src/rust/rustc.2/tests/ui/errors/issue-104621-extern-bad-file.stderr` for unexpected revision `2/tests/ui/errors/issue-104621-extern-bad-file` of test `/home/r/src/rust/rustc.2/tests/ui/errors/remap-path-prefix.rs`
tidy error: found output file `/home/r/src/rust/rustc.2/tests/ui/errors/issue-104621-extern-not-file.stderr` for unexpected revision `2/tests/ui/errors/issue-104621-extern-not-file` of test `/home/r/src/rust/rustc.2/tests/ui/errors/remap-path-prefix.rs`
tidy error: found output file `/home/r/src/rust/rustc.2/tests/ui/errors/issue-89280-emitter-overflow-splice-lines.stderr` for unexpected revision `2/tests/ui/errors/issue-89280-emitter-overflow-splice-lines` of test `/home/r/src/rust/rustc.2/tests/ui/errors/remap-path-prefix.rs`
tidy error: found output file `/home/r/src/rust/rustc.2/tests/ui/errors/issue-99572-impl-trait-on-pointer.stderr` for unexpected revision `2/tests/ui/errors/issue-99572-impl-trait-on-pointer` of test `/home/r/src/rust/rustc.2/tests/ui/errors/remap-path-prefix.rs`
tidy error: found output file `/home/r/src/rust/rustc.2/tests/ui/errors/remap-path-prefix-macro.normal.run.stdout` for unexpected revision `2/tests/ui/errors/remap-path-prefix-macro` of test `/home/r/src/rust/rustc.2/tests/ui/errors/remap-path-prefix.rs`
tidy error: found output file `/home/r/src/rust/rustc.2/tests/ui/errors/remap-path-prefix-macro.with-macro-scope.run.stdout` for unexpected revision `2/tests/ui/errors/remap-path-prefix-macro` of test `/home/r/src/rust/rustc.2/tests/ui/errors/remap-path-prefix.rs`
tidy error: found output file `/home/r/src/rust/rustc.2/tests/ui/errors/remap-path-prefix-macro.without-macro-scope.run.stdout` for unexpected revision `2/tests/ui/errors/remap-path-prefix-macro` of test `/home/r/src/rust/rustc.2/tests/ui/errors/remap-path-prefix.rs`
tidy error: found output file `/home/r/src/rust/rustc.2/tests/ui/errors/remap-path-prefix-reverse.local-self.stderr` for unexpected revision `2/tests/ui/errors/remap-path-prefix-reverse` of test `/home/r/src/rust/rustc.2/tests/ui/errors/remap-path-prefix.rs`
tidy error: found output file `/home/r/src/rust/rustc.2/tests/ui/errors/remap-path-prefix-reverse.remapped-self.stderr` for unexpected revision `2/tests/ui/errors/remap-path-prefix-reverse` of test `/home/r/src/rust/rustc.2/tests/ui/errors/remap-path-prefix.rs`
tidy error: found output file `/home/r/src/rust/rustc.2/tests/ui/errors/remap-path-prefix.normal.stderr` for unexpected revision `2/tests/ui/errors/remap-path-prefix` of test `/home/r/src/rust/rustc.2/tests/ui/errors/remap-path-prefix.rs`
tidy error: found output file `/home/r/src/rust/rustc.2/tests/ui/errors/remap-path-prefix.with-diagnostic-scope.stderr` for unexpected revision `2/tests/ui/errors/remap-path-prefix` of test `/home/r/src/rust/rustc.2/tests/ui/errors/remap-path-prefix.rs`
tidy error: found output file `/home/r/src/rust/rustc.2/tests/ui/errors/remap-path-prefix.without-diagnostic-scope.stderr` for unexpected revision `2/tests/ui/errors/remap-path-prefix` of test `/home/r/src/rust/rustc.2/tests/ui/errors/remap-path-prefix.rs`
tidy error: found output file `/home/r/src/rust/rustc.2/tests/ui/errors/traits/blame-trait-error-spans-on-exprs.stderr` for unexpected revision `2/tests/ui/errors/traits/blame-trait-error-spans-on-exprs` of test `/home/r/src/rust/rustc.2/tests/ui/errors/traits/blame-trait-error-spans-on-exprs.rs`
tidy error: found output file `/home/r/src/rust/rustc.2/tests/ui/errors/trait-bound-error-spans/blame-trait-error.stderr` for unexpected revision `2/tests/ui/errors/trait-bound-error-spans/blame-trait-error` of test `/home/r/src/rust/rustc.2/tests/ui/errors/trait-bound-error-spans/blame-trait-error.rs`
tidy error: found output file `/home/r/src/rust/rustc.2/tests/ui/intrinsics/bad-intrinsic-monomorphization.stderr` for unexpected revision `2/tests/ui/intrinsics/bad-intrinsic-monomorphization` of test `/home/r/src/rust/rustc.2/tests/ui/intrinsics/unchecked_math_unstable.rs`
tidy error: found output file `/home/r/src/rust/rustc.2/tests/ui/intrinsics/const-eval-select-backtrace-std.run.stderr` for unexpected revision `2/tests/ui/intrinsics/const-eval-select-backtrace-std` of test `/home/r/src/rust/rustc.2/tests/ui/intrinsics/unchecked_math_unstable.rs`
tidy error: found output file `/home/r/src/rust/rustc.2/tests/ui/intrinsics/const-eval-select-backtrace.run.stderr` for unexpected revision `2/tests/ui/intrinsics/const-eval-select-backtrace` of test `/home/r/src/rust/rustc.2/tests/ui/intrinsics/unchecked_math_unstable.rs`
tidy error: found output file `/home/r/src/rust/rustc.2/tests/ui/intrinsics/const-eval-select-bad.stderr` for unexpected revision `2/tests/ui/intrinsics/const-eval-select-bad` of test `/home/r/src/rust/rustc.2/tests/ui/intrinsics/unchecked_math_unstable.rs`
tidy error: found output file `/home/r/src/rust/rustc.2/tests/ui/intrinsics/const-eval-select-stability.stderr` for unexpected revision `2/tests/ui/intrinsics/const-eval-select-stability` of test `/home/r/src/rust/rustc.2/tests/ui/intrinsics/unchecked_math_unstable.rs`
tidy error: found output file `/home/r/src/rust/rustc.2/tests/ui/intrinsics/feature-gate-safe-intrinsic.stderr` for unexpected revision `2/tests/ui/intrinsics/feature-gate-safe-intrinsic` of test `/home/r/src/rust/rustc.2/tests/ui/intrinsics/unchecked_math_unstable.rs`
tidy error: found output file `/home/r/src/rust/rustc.2/tests/ui/intrinsics/intrinsic-raw_eq-const-bad.stderr` for unexpected revision `2/tests/ui/intrinsics/intrinsic-raw_eq-const-bad` of test `/home/r/src/rust/rustc.2/tests/ui/intrinsics/unchecked_math_unstable.rs`
tidy error: found output file `/home/r/src/rust/rustc.2/tests/ui/intrinsics/issue-28575.stderr` for unexpected revision `2/tests/ui/intrinsics/issue-28575` of test `/home/r/src/rust/rustc.2/tests/ui/intrinsics/unchecked_math_unstable.rs`
tidy error: found output file `/home/r/src/rust/rustc.2/tests/ui/intrinsics/non-integer-atomic.stderr` for unexpected revision `2/tests/ui/intrinsics/non-integer-atomic` of test `/home/r/src/rust/rustc.2/tests/ui/intrinsics/unchecked_math_unstable.rs`
tidy error: found output file `/home/r/src/rust/rustc.2/tests/ui/intrinsics/safe-intrinsic-mismatch.stderr` for unexpected revision `2/tests/ui/intrinsics/safe-intrinsic-mismatch` of test `/home/r/src/rust/rustc.2/tests/ui/intrinsics/unchecked_math_unstable.rs`
tidy error: found output file `/home/r/src/rust/rustc.2/tests/ui/intrinsics/unchecked_math_unsafe.stderr` for unexpected revision `2/tests/ui/intrinsics/unchecked_math_unsafe` of test `/home/r/src/rust/rustc.2/tests/ui/intrinsics/unchecked_math_unstable.rs`
tidy error: found output file `/home/r/src/rust/rustc.2/tests/ui/intrinsics/unchecked_math_unstable.stderr` for unexpected revision `2/tests/ui/intrinsics/unchecked_math_unstable` of test `/home/r/src/rust/rustc.2/tests/ui/intrinsics/unchecked_math_unstable.rs`
tidy error: found output file `/home/r/src/rust/rustc.2/tests/ui/transmutability/issue-101739-1.stderr` for unexpected revision `2/tests/ui/transmutability/issue-101739-1` of test `/home/r/src/rust/rustc.2/tests/ui/transmutability/transmute-padding-ice.rs`
tidy error: found output file `/home/r/src/rust/rustc.2/tests/ui/transmutability/issue-101739-2.stderr` for unexpected revision `2/tests/ui/transmutability/issue-101739-2` of test `/home/r/src/rust/rustc.2/tests/ui/transmutability/transmute-padding-ice.rs`
tidy error: found output file `/home/r/src/rust/rustc.2/tests/ui/transmutability/issue-110892.stderr` for unexpected revision `2/tests/ui/transmutability/issue-110892` of test `/home/r/src/rust/rustc.2/tests/ui/transmutability/transmute-padding-ice.rs`
tidy error: found output file `/home/r/src/rust/rustc.2/tests/ui/transmutability/region-infer.stderr` for unexpected revision `2/tests/ui/transmutability/region-infer` of test `/home/r/src/rust/rustc.2/tests/ui/transmutability/transmute-padding-ice.rs`
tidy error: found output file `/home/r/src/rust/rustc.2/tests/ui/transmutability/transmute-padding-ice.stderr` for unexpected revision `2/tests/ui/transmutability/transmute-padding-ice` of test `/home/r/src/rust/rustc.2/tests/ui/transmutability/transmute-padding-ice.rs`
tidy error: found output file `/home/r/src/rust/rustc.2/tests/ui/transmutability/alignment/align-fail.stderr` for unexpected revision `2/tests/ui/transmutability/alignment/align-fail` of test `/home/r/src/rust/rustc.2/tests/ui/transmutability/alignment/align-pass.rs`
tidy error: found output file `/home/r/src/rust/rustc.2/tests/ui/transmutability/enums/should_pad_variants.stderr` for unexpected revision `2/tests/ui/transmutability/enums/should_pad_variants` of test `/home/r/src/rust/rustc.2/tests/ui/transmutability/enums/should_respect_endianness.rs`
tidy error: found output file `/home/r/src/rust/rustc.2/tests/ui/transmutability/enums/should_respect_endianness.stderr` for unexpected revision `2/tests/ui/transmutability/enums/should_respect_endianness` of test `/home/r/src/rust/rustc.2/tests/ui/transmutability/enums/should_respect_endianness.rs`
tidy error: found output file `/home/r/src/rust/rustc.2/tests/ui/transmutability/enums/repr/primitive_reprs_should_have_correct_length.stderr` for unexpected revision `2/tests/ui/transmutability/enums/repr/primitive_reprs_should_have_correct_length` of test `/home/r/src/rust/rustc.2/tests/ui/transmutability/enums/repr/should_require_well_defined_layout.rs`
tidy error: found output file `/home/r/src/rust/rustc.2/tests/ui/transmutability/enums/repr/should_require_well_defined_layout.stderr` for unexpected revision `2/tests/ui/transmutability/enums/repr/should_require_well_defined_layout` of test `/home/r/src/rust/rustc.2/tests/ui/transmutability/enums/repr/should_require_well_defined_layout.rs`
tidy error: found output file `/home/r/src/rust/rustc.2/tests/ui/transmutability/malformed-program-gracefulness/feature-missing.stderr` for unexpected revision `2/tests/ui/transmutability/malformed-program-gracefulness/feature-missing` of test `/home/r/src/rust/rustc.2/tests/ui/transmutability/malformed-program-gracefulness/wrong-type-assume.rs`
tidy error: found output file `/home/r/src/rust/rustc.2/tests/ui/transmutability/malformed-program-gracefulness/unknown_dst.stderr` for unexpected revision `2/tests/ui/transmutability/malformed-program-gracefulness/unknown_dst` of test `/home/r/src/rust/rustc.2/tests/ui/transmutability/malformed-program-gracefulness/wrong-type-assume.rs`
tidy error: found output file `/home/r/src/rust/rustc.2/tests/ui/transmutability/malformed-program-gracefulness/unknown_src.stderr` for unexpected revision `2/tests/ui/transmutability/malformed-program-gracefulness/unknown_src` of test `/home/r/src/rust/rustc.2/tests/ui/transmutability/malformed-program-gracefulness/wrong-type-assume.rs`
tidy error: found output file `/home/r/src/rust/rustc.2/tests/ui/transmutability/malformed-program-gracefulness/unknown_src_field.stderr` for unexpected revision `2/tests/ui/transmutability/malformed-program-gracefulness/unknown_src_field` of test `/home/r/src/rust/rustc.2/tests/ui/transmutability/malformed-program-gracefulness/wrong-type-assume.rs`
tidy error: found output file `/home/r/src/rust/rustc.2/tests/ui/transmutability/malformed-program-gracefulness/wrong-type-assume.stderr` for unexpected revision `2/tests/ui/transmutability/malformed-program-gracefulness/wrong-type-assume` of test `/home/r/src/rust/rustc.2/tests/ui/transmutability/malformed-program-gracefulness/wrong-type-assume.rs`
tidy error: found output file `/home/r/src/rust/rustc.2/tests/ui/transmutability/references/recursive-wrapper-types-bit-compatible-mut.stderr` for unexpected revision `2/tests/ui/transmutability/references/recursive-wrapper-types-bit-compatible-mut` of test `/home/r/src/rust/rustc.2/tests/ui/transmutability/references/unit-to-u8.rs`
tidy error: found output file `/home/r/src/rust/rustc.2/tests/ui/transmutability/references/recursive-wrapper-types-bit-incompatible.stderr` for unexpected revision `2/tests/ui/transmutability/references/recursive-wrapper-types-bit-incompatible` of test `/home/r/src/rust/rustc.2/tests/ui/transmutability/references/unit-to-u8.rs`
tidy error: found output file `/home/r/src/rust/rustc.2/tests/ui/transmutability/references/unit-to-u8.stderr` for unexpected revision `2/tests/ui/transmutability/references/unit-to-u8` of test `/home/r/src/rust/rustc.2/tests/ui/transmutability/references/unit-to-u8.rs`
tidy error: found output file `/home/r/src/rust/rustc.2/tests/ui/transmutability/unions/should_pad_variants.stderr` for unexpected revision `2/tests/ui/transmutability/unions/should_pad_variants` of test `/home/r/src/rust/rustc.2/tests/ui/transmutability/unions/should_reject_intersecting.rs`
tidy error: found output file `/home/r/src/rust/rustc.2/tests/ui/transmutability/unions/should_reject_contraction.stderr` for unexpected revision `2/tests/ui/transmutability/unions/should_reject_contraction` of test `/home/r/src/rust/rustc.2/tests/ui/transmutability/unions/should_reject_intersecting.rs`
tidy error: found output file `/home/r/src/rust/rustc.2/tests/ui/transmutability/unions/should_reject_disjoint.stderr` for unexpected revision `2/tests/ui/transmutability/unions/should_reject_disjoint` of test `/home/r/src/rust/rustc.2/tests/ui/transmutability/unions/should_reject_intersecting.rs`
tidy error: found output file `/home/r/src/rust/rustc.2/tests/ui/transmutability/unions/should_reject_intersecting.stderr` for unexpected revision `2/tests/ui/transmutability/unions/should_reject_intersecting` of test `/home/r/src/rust/rustc.2/tests/ui/transmutability/unions/should_reject_intersecting.rs`
tidy error: found output file `/home/r/src/rust/rustc.2/tests/ui/transmutability/unions/repr/should_require_well_defined_layout.stderr` for unexpected revision `2/tests/ui/transmutability/unions/repr/should_require_well_defined_layout` of test `/home/r/src/rust/rustc.2/tests/ui/transmutability/unions/repr/should_require_well_defined_layout.rs`
tidy error: found output file `/home/r/src/rust/rustc.2/tests/ui/transmutability/structs/repr/should_require_well_defined_layout.stderr` for unexpected revision `2/tests/ui/transmutability/structs/repr/should_require_well_defined_layout` of test `/home/r/src/rust/rustc.2/tests/ui/transmutability/structs/repr/transmute_infinitely_recursive_type.rs`
tidy error: found output file `/home/r/src/rust/rustc.2/tests/ui/transmutability/structs/repr/transmute_infinitely_recursive_type.stderr` for unexpected revision `2/tests/ui/transmutability/structs/repr/transmute_infinitely_recursive_type` of test `/home/r/src/rust/rustc.2/tests/ui/transmutability/structs/repr/transmute_infinitely_recursive_type.rs`
tidy error: found output file `/home/r/src/rust/rustc.2/tests/ui/transmutability/arrays/huge-len.stderr` for unexpected revision `2/tests/ui/transmutability/arrays/huge-len` of test `/home/r/src/rust/rustc.2/tests/ui/transmutability/arrays/should_require_well_defined_layout.rs`
tidy error: found output file `/home/r/src/rust/rustc.2/tests/ui/transmutability/arrays/issue-103783-array-length.stderr` for unexpected revision `2/tests/ui/transmutability/arrays/issue-103783-array-length` of test `/home/r/src/rust/rustc.2/tests/ui/transmutability/arrays/should_require_well_defined_layout.rs`
tidy error: found output file `/home/r/src/rust/rustc.2/tests/ui/transmutability/arrays/should_require_well_defined_layout.stderr` for unexpected revision `2/tests/ui/transmutability/arrays/should_require_well_defined_layout` of test `/home/r/src/rust/rustc.2/tests/ui/transmutability/arrays/should_require_well_defined_layout.rs`
tidy error: found output file `/home/r/src/rust/rustc.2/tests/ui/transmutability/safety/should_reject_if_dst_has_safety_invariant.stderr` for unexpected revision `2/tests/ui/transmutability/safety/should_reject_if_dst_has_safety_invariant` of test `/home/r/src/rust/rustc.2/tests/ui/transmutability/safety/should_reject_if_ref_src_has_safety_invariant.rs`
tidy error: found output file `/home/r/src/rust/rustc.2/tests/ui/transmutability/safety/should_reject_if_ref_src_has_safety_invariant.stderr` for unexpected revision `2/tests/ui/transmutability/safety/should_reject_if_ref_src_has_safety_invariant` of test `/home/r/src/rust/rustc.2/tests/ui/transmutability/safety/should_reject_if_ref_src_has_safety_invariant.rs`
tidy error: found output file `/home/r/src/rust/rustc.2/tests/ui/transmutability/primitives/bool-mut.stderr` for unexpected revision `2/tests/ui/transmutability/primitives/bool-mut` of test `/home/r/src/rust/rustc.2/tests/ui/transmutability/primitives/unit.rs`
tidy error: found output file `/home/r/src/rust/rustc.2/tests/ui/transmutability/primitives/bool.current.stderr` for unexpected revision `2/tests/ui/transmutability/primitives/bool` of test `/home/r/src/rust/rustc.2/tests/ui/transmutability/primitives/unit.rs`
tidy error: found output file `/home/r/src/rust/rustc.2/tests/ui/transmutability/primitives/bool.next.stderr` for unexpected revision `2/tests/ui/transmutability/primitives/bool` of test `/home/r/src/rust/rustc.2/tests/ui/transmutability/primitives/unit.rs`
tidy error: found output file `/home/r/src/rust/rustc.2/tests/ui/transmutability/primitives/numbers.current.stderr` for unexpected revision `2/tests/ui/transmutability/primitives/numbers` of test `/home/r/src/rust/rustc.2/tests/ui/transmutability/primitives/unit.rs`
tidy error: found output file `/home/r/src/rust/rustc.2/tests/ui/transmutability/primitives/numbers.next.stderr` for unexpected revision `2/tests/ui/transmutability/primitives/numbers` of test `/home/r/src/rust/rustc.2/tests/ui/transmutability/primitives/unit.rs`
tidy error: found output file `/home/r/src/rust/rustc.2/tests/ui/transmutability/primitives/unit.current.stderr` for unexpected revision `2/tests/ui/transmutability/primitives/unit` of test `/home/r/src/rust/rustc.2/tests/ui/transmutability/primitives/unit.rs`
tidy error: found output file `/home/r/src/rust/rustc.2/tests/ui/transmutability/primitives/unit.next.stderr` for unexpected revision `2/tests/ui/transmutability/primitives/unit` of test `/home/r/src/rust/rustc.2/tests/ui/transmutability/primitives/unit.rs`
tidy error: found output file `/home/r/src/rust/rustc.2/tests/ui/fmt/closing-brace-as-fill.stderr` for unexpected revision `2/tests/ui/fmt/closing-brace-as-fill` of test `/home/r/src/rust/rustc.2/tests/ui/fmt/unicode-escape-spans.rs`
tidy error: found output file `/home/r/src/rust/rustc.2/tests/ui/fmt/format-args-argument-span.stderr` for unexpected revision `2/tests/ui/fmt/format-args-argument-span` of test `/home/r/src/rust/rustc.2/tests/ui/fmt/unicode-escape-spans.rs`
tidy error: found output file `/home/r/src/rust/rustc.2/tests/ui/fmt/format-args-capture-first-literal-is-macro.stderr` for unexpected revision `2/tests/ui/fmt/format-args-capture-first-literal-is-macro` of test `/home/r/src/rust/rustc.2/tests/ui/fmt/unicode-escape-spans.rs`
tidy error: found output file `/home/r/src/rust/rustc.2/tests/ui/fmt/format-args-capture-from-pm-first-arg-macro.stderr` for unexpected revision `2/tests/ui/fmt/format-args-capture-from-pm-first-arg-macro` of test `/home/r/src/rust/rustc.2/tests/ui/fmt/unicode-escape-spans.rs`
tidy error: found output file `/home/r/src/rust/rustc.2/tests/ui/fmt/format-args-capture-issue-102057.stderr` for unexpected revision `2/tests/ui/fmt/format-args-capture-issue-102057` of test `/home/r/src/rust/rustc.2/tests/ui/fmt/unicode-escape-spans.rs`
tidy error: found output file `/home/r/src/rust/rustc.2/tests/ui/fmt/format-args-capture-issue-93378.stderr` for unexpected revision `2/tests/ui/fmt/format-args-capture-issue-93378` of test `/home/r/src/rust/rustc.2/tests/ui/fmt/unicode-escape-spans.rs`
tidy error: found output file `/home/r/src/rust/rustc.2/tests/ui/fmt/format-args-capture-issue-94010.stderr` for unexpected revision `2/tests/ui/fmt/format-args-capture-issue-94010` of test `/home/r/src/rust/rustc.2/tests/ui/fmt/unicode-escape-spans.rs`
tidy error: found output file `/home/r/src/rust/rustc.2/tests/ui/fmt/format-args-capture-macro-hygiene.stderr` for unexpected revision `2/tests/ui/fmt/format-args-capture-macro-hygiene` of test `/home/r/src/rust/rustc.2/tests/ui/fmt/unicode-escape-spans.rs`
tidy error: found output file `/home/r/src/rust/rustc.2/tests/ui/fmt/format-args-capture-missing-variables.stderr` for unexpected revision `2/tests/ui/fmt/format-args-capture-missing-variables` of test `/home/r/src/rust/rustc.2/tests/ui/fmt/unicode-escape-spans.rs`
tidy error: found output file `/home/r/src/rust/rustc.2/tests/ui/fmt/format-expanded-string.stderr` for unexpected revision `2/tests/ui/fmt/format-expanded-string` of test `/home/r/src/rust/rustc.2/tests/ui/fmt/unicode-escape-spans.rs`
tidy error: found output file `/home/r/src/rust/rustc.2/tests/ui/fmt/format-raw-string-error.stderr` for unexpected revision `2/tests/ui/fmt/format-raw-string-error` of test `/home/r/src/rust/rustc.2/tests/ui/fmt/unicode-escape-spans.rs`
tidy error: found output file `/home/r/src/rust/rustc.2/tests/ui/fmt/format-string-error-2.stderr` for unexpected revision `2/tests/ui/fmt/format-string-error-2` of test `/home/r/src/rust/rustc.2/tests/ui/fmt/unicode-escape-spans.rs`
tidy error: found output file `/home/r/src/rust/rustc.2/tests/ui/fmt/format-string-error.stderr` for unexpected revision `2/tests/ui/fmt/format-string-error` of test `/home/r/src/rust/rustc.2/tests/ui/fmt/unicode-escape-spans.rs`
tidy error: found output file `/home/r/src/rust/rustc.2/tests/ui/fmt/format-string-wrong-order.stderr` for unexpected revision `2/tests/ui/fmt/format-string-wrong-order` of test `/home/r/src/rust/rustc.2/tests/ui/fmt/unicode-escape-spans.rs`
tidy error: found output file `/home/r/src/rust/rustc.2/tests/ui/fmt/ifmt-bad-arg.stderr` for unexpected revision `2/tests/ui/fmt/ifmt-bad-arg` of test `/home/r/src/rust/rustc.2/tests/ui/fmt/unicode-escape-spans.rs`
tidy error: found output file `/home/r/src/rust/rustc.2/tests/ui/fmt/ifmt-bad-format-args.stderr` for unexpected revision `2/tests/ui/fmt/ifmt-bad-format-args` of test `/home/r/src/rust/rustc.2/tests/ui/fmt/unicode-escape-spans.rs`
tidy error: found output file `/home/r/src/rust/rustc.2/tests/ui/fmt/ifmt-unimpl.stderr` for unexpected revision `2/tests/ui/fmt/ifmt-unimpl` of test `/home/r/src/rust/rustc.2/tests/ui/fmt/unicode-escape-spans.rs`
tidy error: found output file `/home/r/src/rust/rustc.2/tests/ui/fmt/ifmt-unknown-trait.stderr` for unexpected revision `2/tests/ui/fmt/ifmt-unknown-trait` of test `/home/r/src/rust/rustc.2/tests/ui/fmt/unicode-escape-spans.rs`
tidy error: found output file `/home/r/src/rust/rustc.2/tests/ui/fmt/incorrect-separator.stderr` for unexpected revision `2/tests/ui/fmt/incorrect-separator` of test `/home/r/src/rust/rustc.2/tests/ui/fmt/unicode-escape-spans.rs`
tidy error: found output file `/home/r/src/rust/rustc.2/tests/ui/fmt/issue-103826.stderr` for unexpected revision `2/tests/ui/fmt/issue-103826` of test `/home/r/src/rust/rustc.2/tests/ui/fmt/unicode-escape-spans.rs`
tidy error: found output file `/home/r/src/rust/rustc.2/tests/ui/fmt/issue-104142.stderr` for unexpected revision `2/tests/ui/fmt/issue-104142` of test `/home/r/src/rust/rustc.2/tests/ui/fmt/unicode-escape-spans.rs`
tidy error: found output file `/home/r/src/rust/rustc.2/tests/ui/fmt/issue-75307.stderr` for unexpected revision `2/tests/ui/fmt/issue-75307` of test `/home/r/src/rust/rustc.2/tests/ui/fmt/unicode-escape-spans.rs`
tidy error: found output file `/home/r/src/rust/rustc.2/tests/ui/fmt/issue-86085.stderr` for unexpected revision `2/tests/ui/fmt/issue-86085` of test `/home/r/src/rust/rustc.2/tests/ui/fmt/unicode-escape-spans.rs`
tidy error: found output file `/home/r/src/rust/rustc.2/tests/ui/fmt/issue-89173.stderr` for unexpected revision `2/tests/ui/fmt/issue-89173` of test `/home/r/src/rust/rustc.2/tests/ui/fmt/unicode-escape-spans.rs`
tidy error: found output file `/home/r/src/rust/rustc.2/tests/ui/fmt/issue-91556.stderr` for unexpected revision `2/tests/ui/fmt/issue-91556` of test `/home/r/src/rust/rustc.2/tests/ui/fmt/unicode-escape-spans.rs`
tidy error: found output file `/home/r/src/rust/rustc.2/tests/ui/fmt/raw-idents.stderr` for unexpected revision `2/tests/ui/fmt/raw-idents` of test `/home/r/src/rust/rustc.2/tests/ui/fmt/unicode-escape-spans.rs`
tidy error: found output file `/home/r/src/rust/rustc.2/tests/ui/fmt/respanned-literal-issue-106191.stderr` for unexpected revision `2/tests/ui/fmt/respanned-literal-issue-106191` of test `/home/r/src/rust/rustc.2/tests/ui/fmt/unicode-escape-spans.rs`
tidy error: found output file `/home/r/src/rust/rustc.2/tests/ui/fmt/send-sync.stderr` for unexpected revision `2/tests/ui/fmt/send-sync` of test `/home/r/src/rust/rustc.2/tests/ui/fmt/unicode-escape-spans.rs`
tidy error: found output file `/home/r/src/rust/rustc.2/tests/ui/fmt/struct-field-as-captured-argument.stderr` for unexpected revision `2/tests/ui/fmt/struct-field-as-captured-argument` of test `/home/r/src/rust/rustc.2/tests/ui/fmt/unicode-escape-spans.rs`
tidy error: found output file `/home/r/src/rust/rustc.2/tests/ui/fmt/suggest-inline-args.stderr` for unexpected revision `2/tests/ui/fmt/suggest-inline-args` of test `/home/r/src/rust/rustc.2/tests/ui/fmt/unicode-escape-spans.rs`
tidy error: found output file `/home/r/src/rust/rustc.2/tests/ui/fmt/unicode-escape-spans.stderr` for unexpected revision `2/tests/ui/fmt/unicode-escape-spans` of test `/home/r/src/rust/rustc.2/tests/ui/fmt/unicode-escape-spans.rs`
tidy error: found output file `/home/r/src/rust/rustc.2/tests/ui/annotate-snippet/missing-type.stderr` for unexpected revision `2/tests/ui/annotate-snippet/missing-type` of test `/home/r/src/rust/rustc.2/tests/ui/annotate-snippet/multispan.rs`
tidy error: found output file `/home/r/src/rust/rustc.2/tests/ui/annotate-snippet/multiple-files.stderr` for unexpected revision `2/tests/ui/annotate-snippet/multiple-files` of test `/home/r/src/rust/rustc.2/tests/ui/annotate-snippet/multispan.rs`
tidy error: found output file `/home/r/src/rust/rustc.2/tests/ui/annotate-snippet/multispan.stderr` for unexpected revision `2/tests/ui/annotate-snippet/multispan` of test `/home/r/src/rust/rustc.2/tests/ui/annotate-snippet/multispan.rs`
tidy error: found output file `/home/r/src/rust/rustc.2/tests/ui/shell-argfiles/shell-argfiles-badquotes-windows.stderr` for unexpected revision `2/tests/ui/shell-argfiles/shell-argfiles-badquotes-windows` of test `/home/r/src/rust/rustc.2/tests/ui/shell-argfiles/shell-argfiles.rs`
tidy error: found output file `/home/r/src/rust/rustc.2/tests/ui/shell-argfiles/shell-argfiles-badquotes.stderr` for unexpected revision `2/tests/ui/shell-argfiles/shell-argfiles-badquotes` of test `/home/r/src/rust/rustc.2/tests/ui/shell-argfiles/shell-argfiles.rs`
tidy error: found output file `/home/r/src/rust/rustc.2/tests/ui/json/json-and-color.stderr` for unexpected revision `2/tests/ui/json/json-and-color` of test `/home/r/src/rust/rustc.2/tests/ui/json/json-short.rs`
tidy error: found output file `/home/r/src/rust/rustc.2/tests/ui/json/json-and-error-format.stderr` for unexpected revision `2/tests/ui/json/json-and-error-format` of test `/home/r/src/rust/rustc.2/tests/ui/json/json-short.rs`
tidy error: found output file `/home/r/src/rust/rustc.2/tests/ui/json/json-bom-plus-crlf-multifile.stderr` for unexpected revision `2/tests/ui/json/json-bom-plus-crlf-multifile` of test `/home/r/src/rust/rustc.2/tests/ui/json/json-short.rs`
tidy error: found output file `/home/r/src/rust/rustc.2/tests/ui/json/json-bom-plus-crlf.stderr` for unexpected revision `2/tests/ui/json/json-bom-plus-crlf` of test `/home/r/src/rust/rustc.2/tests/ui/json/json-short.rs`
tidy error: found output file `/home/r/src/rust/rustc.2/tests/ui/json/json-invalid.stderr` for unexpected revision `2/tests/ui/json/json-invalid` of test `/home/r/src/rust/rustc.2/tests/ui/json/json-short.rs`
tidy error: found output file `/home/r/src/rust/rustc.2/tests/ui/json/json-multiple.polonius.stderr` for unexpected revision `2/tests/ui/json/json-multiple` of test `/home/r/src/rust/rustc.2/tests/ui/json/json-short.rs`
tidy error: found output file `/home/r/src/rust/rustc.2/tests/ui/json/json-multiple.stderr` for unexpected revision `2/tests/ui/json/json-multiple` of test `/home/r/src/rust/rustc.2/tests/ui/json/json-short.rs`
tidy error: found output file `/home/r/src/rust/rustc.2/tests/ui/json/json-options.polonius.stderr` for unexpected revision `2/tests/ui/json/json-options` of test `/home/r/src/rust/rustc.2/tests/ui/json/json-short.rs`
tidy error: found output file `/home/r/src/rust/rustc.2/tests/ui/json/json-options.stderr` for unexpected revision `2/tests/ui/json/json-options` of test `/home/r/src/rust/rustc.2/tests/ui/json/json-short.rs`
tidy error: found output file `/home/r/src/rust/rustc.2/tests/ui/json/json-short.stderr` for unexpected revision `2/tests/ui/json/json-short` of test `/home/r/src/rust/rustc.2/tests/ui/json/json-short.rs`
tidy error: found output file `/home/r/src/rust/rustc.2/tests/ui/meta/expected-error-correct-rev.a.stderr` for unexpected revision `2/tests/ui/meta/expected-error-correct-rev` of test `/home/r/src/rust/rustc.2/tests/ui/meta/rustc-env.rs`
tidy error: found output file `/home/r/src/rust/rustc.2/tests/ui/meta/meta-expected-error-wrong-rev.a.stderr` for unexpected revision `2/tests/ui/meta/meta-expected-error-wrong-rev` of test `/home/r/src/rust/rustc.2/tests/ui/meta/rustc-env.rs`
tidy error: found output file `/home/r/src/rust/rustc.2/tests/ui/custom_test_frameworks/mismatch.stderr` for unexpected revision `2/tests/ui/custom_test_frameworks/mismatch` of test `/home/r/src/rust/rustc.2/tests/ui/custom_test_frameworks/mismatch.rs`
some tidy checks failed
Build completed unsuccessfully in 0:00:01
```

### PR DESCRIPTION
**Pull request by jieyouxu**
I committed a path crime by splitting the entire path on `.`, when I meant to split on the filename. This means that any parent folders which contain `.` will cause tidy failure. Added a regression test so that doesn't happen again.

### Follow-up

- [x] Adjust rustc-dev-guide to document assert on test name not containing dots. https://github.com/rust-lang/rustc-dev-guide/pull/1927

Fixes #121986.

### CODE REVIEW

File: src/tools/tidy/src/tests_revision_unpaired_stdout_stderr.rs [hunk 1]
```diff
@@ -84,7 +84,9 @@ pub fn check(tests_path: impl AsRef<Path>, bad: &mut bool) {
                 }
             });
 
-            let Some((test_name, _)) = test.to_str().map(|s| s.split_once('.')).flatten() else {
```
Comment (Nilstrieb) [inline src/tools/tidy/src/tests_revision_unpaired_stdout_stderr.rs:87]: You want https://doc.rust-lang.org/stable/std/path/struct.Path.html#method.file_prefix which is sadly unstable

https://doc.rust-lang.org/stable/std/path/struct.Path.html#method.with_extension should work too, and be nicer than... split 😭

Comment (jieyouxu) [reply src/tools/tidy/src/tests_revision_unpaired_stdout_stderr.rs:87]: I *think* I actually want `file_stem` semantics here, because I want to keep the test name which is everything but the "rs" extension. This `split_once` doesn't seem right. E.g. `a.b.rs`, the test name is should be `a.b` not `a`. Revisioned output gets additional `.[rev].std{out,err}` after the test name to the best of my knowledge.

Comment (jieyouxu) [reply src/tools/tidy/src/tests_revision_unpaired_stdout_stderr.rs:87]: > Could we not use some unstable features?

Tidy requires stable no?

Comment (ChrisDenton) [reply src/tools/tidy/src/tests_revision_unpaired_stdout_stderr.rs:87]: Oh 😢

File: src/tools/tidy/src/tests_revision_unpaired_stdout_stderr.rs [hunk 2]
```diff
@@ -98,14 +98,20 @@ pub fn check(tests_path: impl AsRef<Path>, bad: &mut bool) {
...
-            let filename_components = sibling.to_str().unwrap().split('.').collect::<Vec<_>>();
-            let file_prefix = filename_components[0];
+            let Some(filename) = sibling.file_name().map(OsStr::to_str).flatten() else {
+                continue;
+            };
+
+            let filename_components = filename.split('.').collect::<Vec<_>>();
+            let [file_prefix, ..] = &filename_components[..] else {
+                continue;
+            };
```
Comment (jieyouxu) [inline src/tools/tidy/src/tests_revision_unpaired_stdout_stderr.rs:108]: I think this logic here isn't robust either. If a test name is `a.b.rs`, and previously we use `file_stem`, the test name becomes `a.b`. But now this sibling check produces `a` which will silent let `a.b.unknown-revision.stdout` go through because there is no entry in `test_info`. I'll have to think about this part of the logic a bit.

Comment (jieyouxu) [reply src/tools/tidy/src/tests_revision_unpaired_stdout_stderr.rs:108]: I'm actually not sure if we *can* properly check here, if we don't assume test name itself to not have any dots.

According to rustc-dev-guide, a test output can take the form

```
<test_name>[.<revision>][.<compare_mode>].<extension>
```

- but `<extension>` can be:
    - `stderr`, `stdout`
    - `run.stderr`, `run.stdout`
    - `64bit.stderr`, `32bit.stderr`
- but `<test_name>` can also have dots if we don't assume it can't have dots.

Maybe it's just better to just say "we assume a test's name don't contain dots or else this tidy check won't catch stray stdout/stderr files for that test"?

Comment (workingjubilee) [reply src/tools/tidy/src/tests_revision_unpaired_stdout_stderr.rs:108]: Yes, I think that's necessary to assume for file names. We can assume that of a file name even if we can't assume that for the full path.

Comment (onur-ozkan) [reply src/tools/tidy/src/tests_revision_unpaired_stdout_stderr.rs:108]: > we assume a test's name don't contain dots or else this tidy check won't catch stray stdout/stderr files for that test

We may need to add an assertion with a message to ensure that it doesn't happen.

Comment (jieyouxu) [reply src/tools/tidy/src/tests_revision_unpaired_stdout_stderr.rs:108]: I'll add an aasert for if the test name contains dots, and update the dev-guide to describe this behavior.

Comment (workingjubilee) [reply src/tools/tidy/src/tests_revision_unpaired_stdout_stderr.rs:108]: Probably a good idea. A lot of the test infra assumes that things like e.g. `.64bit.stderr` remain coherent.

**Comment by jieyouxu** [comment]
Is there a way to force tidy to rerun on all test files, regardless of if they are modified or not?

**Comment by onur-ozkan** [comment]
> > Did you try `--force-rerun` ?
> 
> As in `./x test tidy --force-rerun`? That didn't _seem_ to check all the test files, at least not from the "formatting xxx" messages. Unless it did check, but didn't print anything?

Probably doesn't work then

**Comment by jieyouxu** [comment]
> Probably doesn't do anything then

I'll just write an external script to go through all the test files to check if there's any multi-dot test names.

**Comment by onur-ozkan** [comment]
> Is there a way to force tidy to rerun on all test files, regardless of if they are modified or not?

As far as I see we already doing this. Could you tell what made you think that tidy doesn't already do that?
