### PR TITLE
Only include `dyn Trait<Assoc = ...>` associated type bounds for `Self: Sized` associated types if they are provided

### LINKED ISSUE #140645: "Unused" associated type bounds in `dyn` no longer parameterize the type
### Code

[I tried this code:](https://play.rust-lang.org/?version=beta&mode=debug&edition=2024&gist=c64206db60dd7134b805059cc68927f2)

```rust
#![allow(unused_associated_type_bounds)]

pub trait Other {}
pub trait Trait {
    type Assoc where Self: Sized;
}

impl Other for dyn Trait {}
impl Other for dyn Trait<Assoc = ()> {}
impl<T> dyn Trait<Assoc = T> {}
```

I expected to see this happen: successful compilation.

Instead, this happened:
```rust
error[E0119]: conflicting implementations of trait `Other` for type `(dyn Trait + 'static)`
 --> src/lib.rs:9:1
  |
8 | impl Other for dyn Trait {}
  | ------------------------ first implementation here
9 | impl Other for dyn Trait<Assoc = ()> {}
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ conflicting implementation for `(dyn Trait + 'static)`

error[E0207]: the type parameter `T` is not constrained by the impl trait, self type, or predicates
  --> src/lib.rs:10:6
   |
10 | impl<T> dyn Trait<Assoc = T> {}
   |      ^ unconstrained type parameter

Some errors have detailed explanations: E0119, E0207.
For more information about an error, try `rustc --explain E0119`.
```

### Version it worked on

It most recently worked on: Rust 1.86.0

### Version with regression

Playground: Beta version: 1.87.0-beta.8 (2025-05-03 973ec11f61ba77123aaf)

### More notes

CC #125560

Before Beta, `dyn Trait` and `dyn Trait<Assoc = ()>` were different types.  [Now they are the same type.](https://play.rust-lang.org/?version=beta&mode=debug&edition=2024&gist=252cdcd76531bcd2f422f49f61dda214)

[Here's a more complete example](https://play.rust-lang.org/?version=stable&mode=debug&edition=2024&gist=6d60976e6ef9e694924df834d333453c) that makes practical (albeit contrived) use of distinct `dyn Trait<Assoc = ...>` types.

Considering the release notes, #136458 may be the cause (but there's no discussion about this change in particular).  Assuming this is the case and the use case that broke is considered unimportant, this aspect of the change could at least be mentioned in the release notes.

Incidentally, this also means [`dyn Trait<Assoc = &'can_be_non_static str>` meets a `'static` bound now.](https://play.rust-lang.org/?version=beta&mode=debug&edition=2024&gist=31f40e5acf39b7175be37199844cc40e)  Hopefully irrelevant, but it does seem like an exception to outlive bounds being syntactical.

@rustbot modify labels: +regression-from-stable-to-beta, -regression-untriaged

### PR DESCRIPTION
**Pull request by compiler-errors**
Since #136458, we began filtering out associated types with `Self: Sized` bounds when constructing the list of associated type bounds to put into our `dyn Trait` types. For example, given:

```rust
trait Trait {
    type Assoc where Self: Sized;
}
```

After #136458, even if a user writes `dyn Trait<Assoc = ()>`, the lowered ty would have an empty projection list, and thus be equivalent to `dyn Trait`. However, this has the side effect of no longer constraining any types in the RHS of `Assoc = ...`, not implying any WF implied bounds, and not requiring that they hold when unsizing.

After this PR, we include these bounds, but (still) do not require that they are provided. If the are not provided, they are skipped from the projections list.

This results in `dyn Trait` types that have differing numbers of projection bounds. This will lead to re-introducing type mismatches e.g. between `dyn Trait` and `dyn Trait<Assoc = ()>`. However, this is expected and doesn't suffer from any of the deduplication unsoundness from before #136458.

We may want to begin to ignore thse bounds in the future by bumping `unused_associated_type_bounds` to an FCW. I don't want to tangle that up into the fix that was originally intended in #136458, so I'm doing a "fix-forward" in this PR and deferring thinking about this for the future.

Fixes #140645

r? lcnr

### CODE REVIEW

File: compiler/rustc_hir_analysis/src/hir_ty_lowering/dyn_compatibility.rs [hunk 1]
```diff
@@ -204,9 +204,6 @@ impl<'tcx> dyn HirTyLowerer<'tcx> + '_ {
                                 .filter(|item| item.is_type())
```
Comment (lcnr) [inline compiler/rustc_hir_analysis/src/hir_ty_lowering/dyn_compatibility.rs:204]: it's not rly `needed_associated_types` anymore, is it. It's `ordered_associated_types` or whatever. Pls rename the variable and add a comment explaining the approach of

- collect all associated types in a stable order by walking over the dyn trait with identity substitutions
- then use that to order user annotations
- then with elaborated super bounds, not replying user annotations

File: tests/ui/traits/object/constrain-via-unnecessary-bound.rs [hunk 2]
```diff
@@ -0,0 +1,24 @@
...
+pub trait Other {}
+
+pub trait Trait {
+    type Assoc
+    where
+        Self: Sized;
+}
+
+impl Other for dyn Trait {}
+// `dyn Trait<Assoc = ()>` is a different "nominal type" than `dyn Traiat`.
```
Comment (lcnr) [inline tests/ui/traits/object/constrain-via-unnecessary-bound.rs:16]:
```suggestion
// `dyn Trait<Assoc = ()>` is a different "nominal type" than `dyn Trait`.
```

**Comment by pietroalbini** [comment]
Accepting for beta backport (directly into the stable PR) given the vote in [Zulip](https://rust-lang.zulipchat.com/#narrow/channel/131828-t-compiler/topic/Async.20backport.20nominations).
