### PR TITLE
Restrict recursive opaque type check

### LINKED ISSUE #113314: recursive `type_alias_impl_trait` unsoundly allows different underlying types
*edit: minimized*
```rust
#![feature(type_alias_impl_trait)]

type Op = impl std::fmt::Display;
fn foo() -> Op { &"hello world" }

fn transform<S>() -> impl std::fmt::Display {
    &0usize
}
fn bad() -> Op {
    transform::<Op>()
}

fn main() {
    let mut x = foo();
    println!("{x}");
    x = bad();
    println!("{x}");
}
```
see https://github.com/rust-lang/rust/issues/113314#issuecomment-1620466648 for more details

---

I tried this code:

```rust
#![feature(type_alias_impl_trait)]
#![feature(generators)]
#![feature(stmt_expr_attributes)]
#![feature(proc_macro_hygiene)]

use anyhow::{anyhow, Result};
use futures::stream::Stream;
use futures_async_stream::{stream, for_await};

type Op = impl Stream<Item = Result<usize>>;
async fn iter() -> Op {
    futures::stream::iter(vec![Ok(1), Err(anyhow!(""))])
}

#[stream(item = Result<usize>)]
async fn transform<S>(stream: S)
where
    S: Stream<Item = Result<usize>> + Unpin,
{
    #[for_await]
    for i in stream {
        yield i;
    }
}

async fn bad() -> Op {
    transform(Box::pin(iter().await))
}

#[allow(dead_code)]
#[stream(item = Result<usize>)]
async fn good() {
    #[for_await]
    for i in transform(Box::pin(iter().await)) {
        yield i;
    }
}

#[tokio::main]
async fn main() {
    let s = bad().await;
    // let s = good(); // may comment this out, this works instead.
    #[for_await]
    for i in s {
        println!("{:#?}", i);
    }
}
```

I expected to see this happen: Compilation should fail, because different generator types should be generated by calling `transform`, meaning `bad` and `iter` should not share the same type `Op`.

Instead, compilation passes, and `SEGFAULT` occurs during runtime:

```
    Finished dev [unoptimized + debuginfo] target(s) in 0.05s
     Running `target/debug/async-stream-min`
Ok(
    2334106421097295465,
)
Err(
zsh: segmentation fault  cargo run --bin async-stream-min
```

More context: https://github.com/risingwavelabs/risingwave/pull/10266/files#r1244771828

### Meta

`rustc --version --verbose`:
```
rustc 1.69.0-nightly (31f858d9a 2023-02-28)
binary: rustc
commit-hash: 31f858d9a511f24fedb8ed997b28304fec809630
commit-date: 2023-02-28
host: aarch64-apple-darwin
release: 1.69.0-nightly
LLVM version: 15.0.7
```

<details><summary>No Backtrace from running it</summary>
<p>

```
$ RUST_BACKTRACE=1 cargo run --bin async-stream-min
    Finished dev [unoptimized + debuginfo] target(s) in 0.05s
     Running `target/debug/async-stream-min`
Ok(
    2334106421097295465,
)
Err(
zsh: segmentation fault  RUST_BACKTRACE=1 cargo run --bin async-stream-min
noelkwan@Noels-MacBook-Pro rust-experiments % 

```

</p>
</details>

### LINKED ISSUE #113596: TAIT: typed patterns don't count as defining uses
The following code compiles successfully:

```rust
#![feature(type_alias_impl_trait)]

pub struct Foo {
    field: (),
}

pub type Tait = impl Sized;

pub fn func1(input: Tait) {
    let Foo { .. } = input;
}

pub fn func2(input: Tait) {
    let Foo { field: _ } = input;
}

pub fn func3(input: Tait) {
    let Foo { field } = input;
}
```

However, if `func3` is commented out, then neither `func1` nor `func2` suffices to constrain `Tait`:

```
error: unconstrained opaque type
 --> src/lib.rs:7:17
  |
7 | pub type Tait = impl Sized;
  |                 ^^^^^^^^^^
  |
  = note: `Tait` must be used in combination with a concrete type within the same module
```

It seems that the pattern only counts as actually constraining the type if one of the fields is actually destructured. The same behavior happens for tuple types; e.g. `let () = input;` does not constrain.

Of course, it would be difficult for this to actually matter, since nothing ever _produces_ a value of type `Tait`, so none of the functions can be called, but this might be a sign of a deeper problem (or just something to nail down about TAIT semantics), so I figured I'd report it anyway. I discovered it while minimizing #113594.

### Meta

`rustc --version --verbose`:
```
rustc 1.73.0-nightly (8ca44ef9c 2023-07-10)
binary: rustc
commit-hash: 8ca44ef9caa4049d584fbbce218c219cdca33a2f
commit-date: 2023-07-10
host: x86_64-apple-darwin
release: 1.73.0-nightly
LLVM version: 16.0.5
```

@rustbot label +A-impl-trait +F-type_alias_impl_trait

### LINKED ISSUE #113619: Type alias impl trait resolves to different concrete types
I tried this code:

```rust
#![feature(type_alias_impl_trait)]

trait Test {}

struct A;

impl Test for A {}

struct B<T> {
  inner: T,
}

impl<T: Test> Test for B<T> {}

type TestImpl = impl Test;
fn test() -> TestImpl {
  A
}

fn make_option() -> Option<TestImpl> {
  Some(test())
}

fn make_option2() -> Option<TestImpl> {
  let inner = make_option().unwrap();

  B { inner }.into()
}

```

I expected to see this happen: compile error that said the `make_option2` return type is wrong.

Instead, this happened: compiled without error

### Meta

`rustc --version --verbose`:
```
rustc 1.72.0-nightly (37998ab50 2023-06-11)
binary: rustc
commit-hash: 37998ab508d5d9fa0d465d7b535dc673087dda8f
commit-date: 2023-06-11
host: x86_64-pc-windows-msvc
release: 1.72.0-nightly
LLVM version: 16.0.5
```

### PR DESCRIPTION
**Pull request by compiler-errors**
We have a recursive opaque check in writeback to avoid inferring the hidden of an opaque type to be itself:

https://github.com/rust-lang/rust/blob/33a2c2487ac5d9927830ea4c1844335c6b9f77db/compiler/rustc_hir_typeck/src/writeback.rs#L556-L575

Issue #113619 treats `make_option2` as not defining the TAIT `TestImpl` since it is inferred to have the definition `TestImpl := B<TestImpl>`, which fails this check. This regressed in #102700 (5d15beb5919e4ed481c44a1ac19c2ad04a36ee8a), I think due to the refactoring that made us record the hidden types of TAITs during writeback.

However, nothing actually seems to go bad if we relax this recursion checker to only check for directly recursive definitions. This PR fixes #113619 by changing this recursive check from being a visitor to just checking that the hidden type is exactly the same as the opaque being inferred.

Alternatively, we may be able to fix #113619 by restricting this recursion check only to RPITs/async fns. It seems to only be possible to use misuse the recursion check to cause ICEs for TAITs (though I didn't try too hard to create a bad RPIT example... may be possible, actually.)

r? @oli-obk

-- 

Fixes #113314

### CODE REVIEW

**Comment by compiler-errors** [comment]
@craterbot check

**Review by oli-obk — APPROVED** [review]

**Comment by oli-obk** [comment]
All regressions are spurious disk failures

@bors r+

File: compiler/rustc_hir_typeck/src/writeback.rs [hunk 1]
```diff
@@ -565,23 +563,9 @@ impl<'cx, 'tcx> WritebackCx<'cx, 'tcx> {
...
-                    }
-                    t.super_visit_with(self)
-                }
-            }
-            if hidden_type
-                .visit_with(&mut RecursionChecker { def_id: opaque_type_key.def_id })
-                .is_break()
+            if let ty::Alias(ty::Opaque, alias_ty) = hidden_type.ty.kind()
+                && alias_ty.def_id == opaque_type_key.def_id.to_def_id()
+                && alias_ty.substs == opaque_type_key.substs
```
Comment (cjgillot) [inline compiler/rustc_hir_typeck/src/writeback.rs:568]: The previous check was only checking the def_id.
This would accept `TAIT<T, U>` being inferred to `Tait<u32, u32>`.
Do we want to accept that?
