### PR TITLE
Add an attribute that makes the spans from a macro edition 2021, and fix pin on edition 2024 with it

### LINKED ISSUE #138596: pin macro no longer lifetime extends argument
### Code

I tried this code:

```rust
fn main() {
    match std::pin::pin!(foo(&mut 0)) {
        _f => {}
    }
}

async fn foo(_s: &mut usize) {}
```

I expected to see this happen: Compiles without error

Instead, this happened: 

```
error[E0716]: temporary value dropped while borrowed
 --> src/main.rs:2:35
  |
2 |     match std::pin::pin!(foo(&mut 0)) {
  |           ------------------------^--
  |           |                       ||
  |           |                       |temporary value is freed at the end of this statement
  |           |                       creates a temporary value which is freed while still in use
  |           borrow later used here
  |
  = note: consider using a `let` binding to create a longer lived value
```

### Version it worked on

It most recently worked on: `1.86.0-beta.6 (2025-03-16 8c7969a3ae4a292789a4)`

### Version with regression

`rustc --version --verbose`:
```
rustc 1.87.0-nightly (227690a25 2025-03-16)
binary: rustc
commit-hash: 227690a258492c84ae9927d18289208d0180e62f
commit-date: 2025-03-16
host: aarch64-apple-darwin
release: 1.87.0-nightly
LLVM version: 20.1.0
```

### PR DESCRIPTION
**Pull request by jdonszelmann**
Fixes a regression, see issue below. This is a temporary fix, super let is the real solution.

Closes #138596

### CODE REVIEW

**Review by WaffleLapkin — APPROVED** [review]

**Comment by WaffleLapkin** [comment]
r? WaffleLapkin
r=me with green CI

**Comment by petrochenkov** [comment]
What are you people doing 🤦 
I really hope this is temporary.

**Comment by Noratrieb** [comment]
@petrochenkov do you have a constructive suggestion for this issue or just unconstructive complaints?

**Comment by Noratrieb** [comment]
Good, then think. Next time maybe think first.

**Comment by petrochenkov** [comment]
One alternative not requiring compiler hacks is to put it into a separate 2021 edition crate and then reexport it from libcore, but that may (or may not) cause some larger build/infrastructure issues.

**Comment by workingjubilee** [comment]
Probably will. And no one wants to spend a day debugging the CI issues when it does. And speaking from my POV as libs reviewer, I strongly prefer core's current dependency graph to it having any dependencies at all.

**Comment by m-ou-se** [comment]
> What are you people doing 🤦 
> I really hope this is temporary.

It really should be. If this isn't temporary, it means that Rust 2024 isn't as expressive as Rust 2021. That would be a problem!

Opened https://github.com/rust-lang/rust/issues/138718 to track that.

**Comment by m-ou-se** [comment]
> One alternative not requiring compiler hacks is to put it into a separate 2021 edition crate and then reexport it from libcore, but that may (or may not) cause some larger build/infrastructure issues. 

Definitely considered that. But adding a dependency to core isn't trivial. Luckily this attribute is very simple to implement, and thus simple to remove again. (It just sets the SyntaxExtension::edition field.)

**Comment by m-ou-se** [comment]
> Is it reasonable to try running crater with the identity() fix to see how much code breaks? Broken code probably would need to look like `pin!(&mut temporary())`, which is kinda silly, and hopefully doesn't come up often enough to be an issue.

Considering that pin!() is used often in aync application code (not just libraries), I think crater might not be very representative, as there might be a lot of uses in code that is not on (public) github or crates.io.

**Comment by BoxyUwU** [comment]
> What are you people doing 🤦 I really hope this is temporary.

@petrochenkov  Why on earth would you think this is an acceptable way to speak other project members..? I will be having you blocked from now on since you seem to repeatedly be unable to interact with other project members in a reasonable manner. cc @rust-lang/mods

File: compiler/rustc_resolve/src/macros.rs [hunk 1]
```diff
@@ -1125,6 +1125,10 @@ impl<'ra, 'tcx> Resolver<'ra, 'tcx> {
             edition,
         );
 
+        if find_attr!(attrs.iter(), AttributeKind::RustcMacroEdition2021 {}) {
```
[the remark this answers is not in the document]
Comment (compiler-errors) [reply compiler/rustc_resolve/src/macros.rs:1128]: Also are those braces necessary? 🤔

File: library/coretests/tests/pin.rs [hunk 2]
```diff
@@ -81,3 +84,14 @@ mod pin_coerce_unsized {
...
+#[test]
+#[cfg(not(bootstrap))]
+fn temp_lifetime() {
+    // Check that temporary lifetimes work as in Rust 2021.
+    // Regression test for https://github.com/rust-lang/rust/issues/138596
+    match std::pin::pin!(foo(&mut 0)) {
+        _ => {}
+    }
+    async fn foo(_: &mut usize) {}
+}
```
Comment (danielhenrymantilla) [inline library/coretests/tests/pin.rs:97]: When I tried to work on this with my failed attempt, I thought of extra tests which seem important for `pin`, so you may want to add them if you like them 🙂:

```rs
fn transitive_extension {
    async fn temporary() {}

    // `pin!` used out there in such cases (instead of `Pin::new()`)
    // precisely because it lifespan-of-temps-extends `temporary()` as well.
    let p = pin!(&mut temporary());
    let _use = p;
}
```

as well as the following things which have to fail to compile to guarantee the soundness of `pin!`: `pin!` needs to consume ownership of the argument given to it, by having moved that value to its own `super let` local, or by having funneled it through a value expression such as `{ $value }`.

  - ```rs
    #[allow(unused_mut)]
    let mut pointee = core::marker::PhantomPinned;
    pin!(pointee);
    let _moved = pointee; // Error, use of moved value.
    ```

  - ```rs
    struct NotCopy<T>(T);
    let mut pointee = NotCopy(core::marker::PhantomPinned);
    pin!(*&mut pointee); // Error, cannot move out of `&mut`, `NotCopy` is not `Copy`.
    let _moved = pointee;
    ```

Comment (m-ou-se) [reply library/coretests/tests/pin.rs:97]: Thanks! Would you mind putting that in a PR?

Comment (m-ou-se) [reply library/coretests/tests/pin.rs:97]: I've put them in https://github.com/rust-lang/rust/pull/139097
