### PR TITLE
Properly handle postfix inc/dec in standalone and subexpr scenarios

### LINKED ISSUE #104867: postfix_increment show both type of suggestion for single statement
Story from [here](https://twitter.com/ekuber/status/1596011865867710465)

Given the [following code](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=0f59310a5430459491c5925f13dba28b):

```rust
fn main() {
    let mut i = 0;
    i++;
    println!("i: {:?}", i);
}
```

The current output is:

```
error: Rust has no postfix increment operator
 --> ./p/inc.rs:3:6
  |
3 |     i++;
  |      ^^ not a valid postfix operator
  |
help: use `+= 1` instead
  |
3 |     { let tmp = i; i += 1; tmp };
  |     +++++++++++  ~~~~~~~~~~~~~~~
3 |     i += 1;
  |       ~~~~
```

Ideally the output should look like:

```
error: Rust has no postfix increment operator
 --> ./p/inc.rs:3:6
  |
3 |     i++;
  |      ^^ not a valid postfix operator
  |
help: use `+= 1` instead
3 |     i += 1;
  |       ~~~~
```

### PR DESCRIPTION
**Pull request by chenyukang**
Fixes #104867
r? @estebank

### CODE REVIEW

File: src/test/ui/parser/increment-notfixed.rs [hunk 1]
```diff
@@ -1,3 +1,5 @@
+// run-rustfix
```
Comment (estebank) [inline src/test/ui/parser/increment-notfixed.rs:1]: Given this, we might want to change the name (or merge it with the likely existing test that already had rustfix enabled).

File: src/test/ui/parser/issue-104867-inc-dec.rs [hunk 2]
```diff
@@ -0,0 +1,30 @@
...
+fn test4() {
+    let mut i = 0;
+    ++i; //~ ERROR Rust has no prefix increment operator
+}
+
+fn test5() {
+    let mut i = 0;
+    if ++i == 1 { } //~ ERROR Rust has no prefix increment operator
+}
+
```
Comment (estebank) [inline src/test/ui/parser/issue-104867-inc-dec.rs:29]: Can we add a test for

```rust
let mut i = 0;
loop { break; }
i++;
loop { break; }
++i;
```
and one for
```rust
let mut i = 0;
let _ = i + ++i;
let _ = ++i + i;
let _ = ++i + ++i;
let _ = i + i++;
let _ = i++ + i;
let _ = i++ + i++;
let _ = ++i + i++;
let _ = i++ + ++i;
```

(that last one might be problematic and need its own test file)

File: compiler/rustc_parse/src/parser/expr.rs [hunk 3]
```diff
@@ -292,7 +292,15 @@ impl<'a> Parser<'a> {
...
                 self.bump();
-                lhs = self.recover_from_postfix_increment(lhs, op_span)?;
+                let prev_is_semi = {
+                    if let Ok(prev_code) = self.sess.source_map().span_to_prev_source(lhs.span) &&
+                          prev_code.trim_end().ends_with(";") {
+                            true
+                    } else {
+                        false
+                    }
+                };
```
Comment (estebank) [inline compiler/rustc_parse/src/parser/expr.rs:302]: This is a bit of a hack, but fair given where it lives. I would like to do a perf run of an alternative approach: modify `lhs` to hold a `starts_statement: bool` field. I think that it might hit memory a bit, but that would be far less brittle to refactors breaking this heuristic. Would you have time to try doing that as part of this PR?

File: compiler/rustc_parse/src/parser/diagnostics.rs [hunk 4]
```diff
@@ -1314,35 +1305,20 @@ impl<'a> Parser<'a> {
             UnaryFixity::Post => (base.span.shrink_to_lo(), op_span),
         };
 
+        let Ok(base_src) = self.span_to_snippet(base.span)
+        else { return help_base_case(err, base) };
```
Comment (estebank) [inline compiler/rustc_parse/src/parser/diagnostics.rs:1309]: There's a codepath now where we check for access to the snippet when it isn't strictly necessary for `Standalone`, but that only comes into play in macros and foreign code, this should be fine.

File: compiler/rustc_parse/src/parser/expr.rs (hunk 3 above)
Comment (chenyukang) [reply compiler/rustc_parse/src/parser/expr.rs:302]: You means add a field with boolean type to `LhsExpr` type?

Comment (chenyukang) [reply compiler/rustc_parse/src/parser/expr.rs]: Updated the code.
I don't think there is a perf regerssion here, we are at error report codepath,
but you may have a double-check.

File: src/test/ui/parser/issue-104867-inc-dec-2.stderr [hunk 5]
```diff
@@ -0,0 +1,107 @@
...
+help: use `+= 1` instead
+   |
+LL |     let _ = { i += 1; i } + ++i;
+   |             ~   +++++++++
+
+error: Rust has no postfix increment operator
+  --> $DIR/issue-104867-inc-dec-2.rs:18:18
+   |
+LL |     let _ = i + i++;
+   |                  ^^ not a valid postfix operator
```
Comment (chenyukang) [inline src/test/ui/parser/issue-104867-inc-dec-2.stderr:38]: This is the hardest case to handle well, so I removed the suggestion for this scenario.
There maybe a solution to get it right, I think it may not worth to do it.

File: compiler/rustc_parse/src/parser/expr.rs (hunk 3 above)
Comment (chenyukang) [reply compiler/rustc_parse/src/parser/expr.rs]: Yes, maybe cost a little bit more memory.
