### PR TITLE
Fix some suggestions where a `Box<T>` is expected.

### LINKED ISSUE #111011: Wrong suggestion for `Box`xing body of async closure when expected return type of closure to be `Box`
### Code

[playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=57ed92b7fafb8525f6531abd2e256752)

```Rust
#![feature(async_closure)]

fn uwu<X>(x: impl FnOnce() -> Box<X>) {}

fn main() {
    uwu(async move || {})
}
```

### Current output

```Shell
Compiling playground v0.0.1 (/playground)
error[E0308]: mismatched types
 --> src/main.rs:6:23
  |
6 |     uwu(async move || {})
  |                       ^^ expected `Box<_>`, found `async` closure body
  |
  = note:            expected struct `Box<_>`
          found `async` closure body `[async closure body@src/main.rs:6:23: 6:25]`
  = note: for more on the distinction between the stack and the heap, read https://doc.rust-lang.org/book/ch15-01-box.html, https://doc.rust-lang.org/rust-by-example/std/box.html, and https://doc.rust-lang.org/std/boxed/index.html
help: store this in the heap by calling `Box::new`
  |
6 |     uwu(async move || Box::new({}))
  |                       +++++++++  +

For more information about this error, try `rustc --explain E0308`.
error: could not compile `playground` (bin "playground") due to previous error
```

### Desired output

```Shell
Compiling playground v0.0.1 (/playground)
error[E0308]: mismatched types
 --> src/main.rs:6:23
  |
6 |     uwu(async move || {})
  |                       ^^ expected `Box<_>`, found `async` closure body
  |
  = note:            expected struct `Box<_>`
          found `async` closure body `[async closure body@src/main.rs:6:23: 6:25]`
  = note: for more on the distinction between the stack and the heap, read https://doc.rust-lang.org/book/ch15-01-box.html, https://doc.rust-lang.org/rust-by-example/std/box.html, and https://doc.rust-lang.org/std/boxed/index.html

For more information about this error, try `rustc --explain E0308`.
error: could not compile `playground` (bin "playground") due to previous error
```

### Rationale and extra context

_No response_

### Other cases

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by nullptrderef29**
This fixes #111011, and also adds a suggestion for boxing a unit type when a `Box<T>` was expected and an empty block was found.

### CODE REVIEW

File: compiler/rustc_hir_typeck/src/fn_ctxt/suggestions.rs [hunk 1]
```diff
@@ -438,33 +439,58 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
...
+                        suggestion,
+                        Applicability::MachineApplicable,
+                    );
+                }
+                err.note(
+                    "for more on the distinction between the stack and the heap, read \
+                     https://doc.rust-lang.org/book/ch15-01-box.html, \
+                     https://doc.rust-lang.org/rust-by-example/std/box.html, and \
+                     https://doc.rust-lang.org/std/boxed/index.html",
+                );
```
Comment (fee1-dead) [inline compiler/rustc_hir_typeck/src/fn_ctxt/suggestions.rs:470]: by the way, is it possible for you to turn this into [translatable diagnostics](https://rustc-dev-guide.rust-lang.org/diagnostics/translation.html) since you are changing this part of the code already?

Comment (JohnBobbo96) [reply compiler/rustc_hir_typeck/src/fn_ctxt/suggestions.rs]: yeah sorry for taking so long, just pushed a commit adding a `SuggestBoxing` enum.

File: compiler/rustc_hir_typeck/src/fn_ctxt/suggestions.rs [hunk 2]
```diff
@@ -438,33 +439,26 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
     pub(in super::super) fn suggest_boxing_when_appropriate(
         &self,
         err: &mut Diagnostic,
-        expr: &hir::Expr<'_>,
+        span: Span,
+        hir_id: HirId,
```
Comment (compiler-errors) [inline compiler/rustc_hir_typeck/src/fn_ctxt/suggestions.rs:443]: Why did you break this up into two args?

File: compiler/rustc_hir_typeck/src/fn_ctxt/suggestions.rs [hunk 3]
```diff
@@ -438,33 +439,26 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
...
-                 https://doc.rust-lang.org/std/boxed/index.html",
-            );
+        if self.can_coerce(self.tcx.mk_box(found), expected) {
+            let suggest_boxing = match found.kind() {
+                ty::Tuple(tuple) if tuple.is_empty() => SuggestBoxing::Unit { start: span.shrink_to_lo(), end: span, },
+                ty::Generator(def_id, ..) if let Some(def_id) = def_id.as_local() && let Body {
+                    generator_kind: Some(GeneratorKind::Async(AsyncGeneratorKind::Closure)), ..
+                } = map.body(map.body_owned_by(def_id)) => SuggestBoxing::AsyncBody,
+                _ => SuggestBoxing::Other { start: span.shrink_to_lo(), end: span.shrink_to_hi() },
+            };
```
Comment (compiler-errors) [inline compiler/rustc_hir_typeck/src/fn_ctxt/suggestions.rs:459]: Sorry, this is really hard to read without formatting :sweat_smile: 

```suggestion
            let suggest_boxing = match found.kind() {
                ty::Tuple(tuple) if tuple.is_empty() => SuggestBoxing::Unit {
                    start: span.shrink_to_lo(),
                    end: span,
                },
                ty::Generator(def_id, ..)
                    if let Some(def_id) = def_id.as_local()
                        && let Body {
                            generator_kind: Some(GeneratorKind::Async(AsyncGeneratorKind::Closure)),
                            ..
                        } = map.body(map.body_owned_by(def_id)) =>
                {
                    SuggestBoxing::AsyncBody
                }
                _ => SuggestBoxing::Other {
                    start: span.shrink_to_lo(),
                    end: span.shrink_to_hi(),
                },
            };
```

Comment (compiler-errors) [reply compiler/rustc_hir_typeck/src/fn_ctxt/suggestions.rs:459]: Also, you should probably just use `tcx.generator_kind` here and a `match!`

File: compiler/rustc_hir_typeck/messages.ftl [hunk 4]
```diff
@@ -75,3 +75,9 @@ hir_typeck_union_pat_dotdot = `..` cannot be used in union patterns
 
 hir_typeck_arg_mismatch_indeterminate = argument type mismatch was detected, but rustc had trouble determining where
     .note = we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new
+
+hir_typeck_suggest_boxing_note = for more on the distinction between the stack and the heap, see:
+    https://doc.rust-lang.org/book/ch15-01-box.html, https://doc.rust-lang.org/rust-by-example/std/box.html, and
+    https://doc.rust-lang.org/std/boxed/index.html
```
Comment (compiler-errors) [inline compiler/rustc_hir_typeck/messages.ftl:81]: Let's keep the old line wrapping, not convinced the new one is that much easier to parse.

```suggestion
hir_typeck_suggest_boxing_note = for more on the distinction between the stack and the heap, see: \
    https://doc.rust-lang.org/book/ch15-01-box.html, https://doc.rust-lang.org/rust-by-example/std/box.html, and \
    https://doc.rust-lang.org/std/boxed/index.html
```

File: compiler/rustc_hir_typeck/src/demand.rs [hunk 5]
```diff
@@ -51,7 +51,7 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
             || self.suggest_non_zero_new_unwrap(err, expr, expected, expr_ty)
             || self.suggest_calling_boxed_future_when_appropriate(err, expr, expected, expr_ty)
             || self.suggest_no_capture_closure(err, expected, expr_ty)
-            || self.suggest_boxing_when_appropriate(err, expr, expected, expr_ty)
+            || self.suggest_boxing_when_appropriate(err, expr.span, expr.hir_id, expected, expr_ty)
```
Comment (compiler-errors) [inline compiler/rustc_hir_typeck/src/demand.rs:54]: Let's not unnecessarily unpack this expr into its members

```suggestion
            || self.suggest_boxing_when_appropriate(err, expr, expected, expr_ty)
```

File: compiler/rustc_hir_typeck/src/fn_ctxt/suggestions.rs (hunk 3 above)
Comment (JohnBobbo96) [reply compiler/rustc_hir_typeck/src/fn_ctxt/suggestions.rs]: Thank you! i wish i had known about that earlier.

File: compiler/rustc_hir_typeck/messages.ftl (hunk 4 above)
Comment (JohnBobbo96) [reply compiler/rustc_hir_typeck/messages.ftl:81]: That is originally what i had, it doesn't actually cause the line to wrap, instead it will ouput this:
```
   = note: for more on the distinction between the stack and the heap, see: \
           https://doc.rust-lang.org/book/ch15-01-box.html, https://doc.rust-lang.org/rust-by-example/std/box.html, and \
           https://doc.rust-lang.org/std/boxed/index.html
help: try storing this on the heap by calling `Box::new`
```
and i think it looks a bit nicer the way it is now, but it also seems fine? it's also done like 20 lines up for another diagnostic.
https://github.com/rust-lang/rust/blob/b4571bed994a901e6dbd0b28e25e91a57758c549/compiler/rustc_hir_typeck/messages.ftl#L60-L64

File: compiler/rustc_hir_typeck/src/fn_ctxt/checks.rs [hunk 6]
```diff
@@ -1591,6 +1590,15 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
...
                         &mut |err| {
                             if let Some(expected_ty) = expected.only_has_type(self) {
+                                if blk.stmts.is_empty() && blk.expr.is_none() {
+                                    self.suggest_boxing_when_appropriate(
+                                        err,
+                                        blk.span,
+                                        blk.hir_id,
+                                        expected_ty,
+                                        self.tcx.mk_unit(),
+                                    );
```
Comment (JohnBobbo96) [inline compiler/rustc_hir_typeck/src/fn_ctxt/checks.rs:1600]: @compiler-errors this is why i split up the arguments, it was the only way i could figure out to pass both the `expr` and `blk` to `suggest_boxing_when_appropriate`, and the function only uses the span and hir_id anyways.

File: compiler/rustc_hir_typeck/messages.ftl (hunk 4 above)
Comment (JohnBobbo96) [reply compiler/rustc_hir_typeck/messages.ftl:81]: I can put it all on the one line, that way it would wrap like before?

Comment (compiler-errors) [reply compiler/rustc_hir_typeck/messages.ftl:81]: Not sure if understand what you mean by "it's also done lines 20 lines up" -- that `hir_typeck_fru_suggestion` diagnostic doesn't (or... shouldn't) have any newlines in it.

Comment (JohnBobbo96) [reply compiler/rustc_hir_typeck/messages.ftl:81]: it.. appears to have newlines to me, it even has one directly after the `=`, but like i said, i can but it all on the one line that way it should wrap like before i think. would that be better?

Comment (clubby789) [reply compiler/rustc_hir_typeck/messages.ftl:81]: The newlines there split up the Fluent branches but don't actually appear in the output

Comment (JohnBobbo96) [reply compiler/rustc_hir_typeck/messages.ftl:81]: Ahh, okay that does make more sense, thank you. I didn't find the fluent syntax guide up until a few minutes ago (originally i was just reading the [translation](https://rustc-dev-guide.rust-lang.org/diagnostics/translation.html) and the [diagnostic structs](https://rustc-dev-guide.rust-lang.org/diagnostics/diagnostic-structs.html) pages), specifically this page explains what `hir_typeck_fru_suggestion` is doing: https://projectfluent.org/fluent/guide/selectors.html, which definitely makes more sense now.

But to make `hir_typeck_suggest_boxing_note` easier to parse and also to make the line wrap like before, i can put it all on the one line, should i do that?

Comment (compiler-errors) [reply compiler/rustc_hir_typeck/messages.ftl:81]: Sure, do that please

Comment (JohnBobbo96) [reply compiler/rustc_hir_typeck/messages.ftl]: done.

File: tests/ui/issues/auxiliary/issue-111011.rs [hunk 7]
```diff
@@ -0,0 +1,13 @@
+#![feature(async_closure)]
+
+// edition:2021
+// check-fail
```
Comment (compiler-errors) [inline tests/ui/issues/auxiliary/issue-111011.rs:4]:
```suggestion
```

this is implied

File: tests/ui/impl-trait/dyn-trait-return-should-be-impl-trait.stderr [hunk 8]
```diff
@@ -148,8 +148,8 @@ LL |         return Struct;
    |
    = note: expected struct `Box<(dyn Trait + 'static)>`
               found struct `Struct`
-   = note: for more on the distinction between the stack and the heap, read https://doc.rust-lang.org/book/ch15-01-box.html, https://doc.rust-lang.org/rust-by-example/std/box.html, and https://doc.rust-lang.org/std/boxed/index.html
-help: store this in the heap by calling `Box::new`
+   = note: for more on the distinction between the stack and the heap, see: https://doc.rust-lang.org/book/ch15-01-box.html, https://doc.rust-lang.org/rust-by-example/std/box.html, and https://doc.rust-lang.org/std/boxed/index.html
+help: try storing this on the heap by calling `Box::new`
```
Comment (compiler-errors) [inline tests/ui/impl-trait/dyn-trait-return-should-be-impl-trait.stderr:152]: I don't really like these drive-by tweaks of diagnostic messages. It makes the PR larger and doesn't really make things better IMO.

Comment (JohnBobbo96) [reply tests/ui/impl-trait/dyn-trait-return-should-be-impl-trait.stderr]: that is fair, fixed in newest commit.

**Review by compiler-errors — APPROVED** [review]
Please squash this into one commit, then I think this is fine to land.

**Comment by JohnBobbo96** [comment]
commits have been squashed.
