### PR TITLE
[RFC-3086] Restrict the parsing of `count`

### LINKED ISSUE #111904: `${count(t,)}` is interpreted as `${count(t, 0)}`
I tried this code:

```rust
#![feature(macro_metavar_expr)]

macro_rules! foo {
    ( $( $($t:ident),* );* ) => { ${count(t,)} }
}

fn test() {
    foo!(a, a; b, b);
}
```

I expected to see this happen:

Either:
- The macro definition is rejected, leading to a compile error.
- `${count(t,)}` is interpreted as `${count(t)}`, the macro call is expanded to `4`.

Instead, this happened:
Compiled successfully, `${count(t,)}` is interpreted as `${count(t, 0)}`, the macro call is expanded to `2`.

This form of `${count()}` metavar expression is not specified in [RFC 3086], so this is more of an ask for clarification than a bug report.

### Meta

`rustc --version --verbose`:
```
1.71.0-nightly (2023-05-23 5ea3f0ae08c07472239a)
```

cc #83527
@rustbot label requires-nightly F-macro-metavar-expr

[RFC 3086]: https://github.com/rust-lang/rfcs/pull/3086

### PR DESCRIPTION
**Pull request by c410-f3r**
Fix #111904

The original RFC didn't mention the possibility of using `${count(t,)}` and such thing isn't very semantically accurate which can lead to confusion.

### CODE REVIEW

**Comment by PatchMixolydic** [comment]
This change seems to be inconsistent with other comma separated lists in the language, which permit trailing commas. I believe `${count(t,)}` should be allowed and should behave identically to `${count(t)}` if at all possible.

**Comment by c410-f3r** [comment]
r? compiler

**Comment by compiler-errors** [comment]
Yeah, I agree with @PatchMixolydic here. Why is `count(t,)` being recovered to `count(t, 0)`? Is there a way we could get it to just act like `count(t)` and have this incongruency?

**Comment by compiler-errors** [comment]
I may be misremembering, but I think petrochenkov reviewed previous RFC3086 work? Maybe you have more opinions about how to handle this and whether to error here.

r? petrochenkov

**Comment by petrochenkov** [comment]
>This change seems to be inconsistent with other comma separated lists in the language, which permit trailing commas.

At which points something becomes a list though?
[Standard library macros](https://doc.rust-lang.org/stable/std/#macros) take it to absurd and consider even `mac!(single_argument)` a list, and therefore accept `mac!(single_argument,)` as well.

Neither `${count(t)}`/`${count(t, N)}`, nor `${index(N)}` or `${length(N)}` are convincingly lists, so for now I think it's fine to report this as error instead of accepting things like `${count(t,)}`, `${count(t, N,)}`, `${index(N,)}` and `${length(N,)}`.

(But we could accept all the commas here too, just need to do it consistently.)

File: compiler/rustc_expand/src/mbe/metavar_expr.rs [hunk 1]
```diff
@@ -93,7 +93,16 @@ fn parse_count<'sess>(
     span: Span,
 ) -> PResult<'sess, MetaVarExpr> {
     let ident = parse_ident(iter, sess, span)?;
-    let depth = if try_eat_comma(iter) { Some(parse_depth(iter, sess, span)?) } else { None };
+    let depth = if try_eat_comma(iter) {
+        if iter.look_ahead(0).is_none() {
+            return Err(sess
+                .span_diagnostic
+                .struct_span_err(span, "invalid meta-variable `count` expression"));
```
Comment (petrochenkov) [inline compiler/rustc_expand/src/mbe/metavar_expr.rs:100]: The wording here is entirely unhelpful, need to say something about what was expected.

**Comment by Dylan-DPC** [comment]
@c410-f3r any updates on this?

**Comment by c410-f3r** [comment]
Sorry, life happened. I will return to this PR tomorrow.

File: compiler/rustc_expand/src/mbe/metavar_expr.rs (hunk 1 above)
Comment (c410-f3r) [reply compiler/rustc_expand/src/mbe/metavar_expr.rs]: Thanks @petrochenkov

**Comment by c410-f3r** [comment]
A little late but here it is
