### PR TITLE
fix(suggestion): insert projection to associated types

### LINKED ISSUE #98562: Help for missing trait method suggests unstable code
I tried this code:

```rust
use core::iter::Sum;

struct Summer;

impl Sum<i32> for Summer {
}
```
[Playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=cb4011a952a69b65d449f1bebd6e9329)

I expected to see this happen: an error which either just shows the error itself or the compilable sugestion for change.

Instead, this happened: the error is like following:
```
error[E0046]: not all trait items implemented, missing: `sum`
 --> src/lib.rs:5:1
  |
5 | impl Sum<i32> for Summer {
  | ^^^^^^^^^^^^^^^^^^^^^^^^ missing `sum` in implementation
  |
  = help: implement the missing item: `fn sum<I>(_: I) -> Self where I: Iterator, std::iter::Iterator::Item = A { todo!() }`
```

Now, if I add the code from the `help` block into the trait, I'll get another error:
```
error: equality constraints are not yet supported in `where` clauses
 --> src/lib.rs:6:44
  |
6 | fn sum<I>(_: I) -> Self where I: Iterator, std::iter::Iterator::Item = A { todo!() }
  |                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ not supported
  |
  = note: [see issue #20041 <https://github.com/rust-lang/rust/issues/20041>](https://github.com/rust-lang/rust/issues/20041) for more information

error[E0412]: cannot find type `A` in this scope
 --> src/lib.rs:6:72
  |
6 | fn sum<I>(_: I) -> Self where I: Iterator, std::iter::Iterator::Item = A { todo!() }
  |        - similarly named type parameter `I` defined here               ^ help: a type parameter with a similar name exists: `I`
```
The first one is the one I'm worried about, since it shows that the suggest was using a nightly-only feature on stable.

Noting also that rust-analyzer seems to do this correctly - it creates an intention to insert `fn sum<I: Iterator<Item = i32>>(_: I) { todo!(); }`, which compiles immediately.

### PR DESCRIPTION
**Pull request by bvanjoi**
Fixes #98562

This PR has fixed some help suggestions for unsupported syntax, such as ﻿`fn f<T>(_:T) where T: IntoIterator, std::iter::IntoIterator::Item = () {}` to `﻿fn f<T: IntoIterator<Item = ()>>(_T) {}`.

### CODE REVIEW

File: compiler/rustc_hir_analysis/src/check/mod.rs [hunk 1]
```diff
@@ -319,36 +319,70 @@ fn bounds_from_generic_predicates<'tcx>(
...
+                            let bound_def_path = tcx.def_path_str(bound);
+                            if projections_str.is_empty() {
+                                where_clauses.push(format!("{}: {}", ty, bound_def_path));
+                                None
+                            } else {
+                                Some(format!("{}<{}>", bound_def_path, projections_str))
+                            }
+                        })
+                        .collect::<Vec<_>>()
+                        .join(" + ");
```
[the remark this answers is not in the document]
Comment (WaffleLapkin) [reply compiler/rustc_hir_analysis/src/check/mod.rs:363]: You'd need `.intersperse(" + ".to_owned())` though, which is meh

File: compiler/rustc_hir_analysis/src/check/mod.rs [hunk 2]
```diff
@@ -319,36 +319,70 @@ fn bounds_from_generic_predicates<'tcx>(
...
     let generics = if types.is_empty() {
         "".to_string()
     } else {
-        format!(
-            "<{}>",
-            types
-                .keys()
-                .filter_map(|t| match t.kind() {
-                    ty::Param(_) => Some(t.to_string()),
+        let types_str = types
```
Comment (WaffleLapkin) [inline compiler/rustc_hir_analysis/src/check/mod.rs:327]: This is a bit too convoluted imo...

Can this be restructured into a loop that pushes to multiple vecs?

File: compiler/rustc_hir_analysis/src/check/mod.rs [hunk 3]
```diff
@@ -319,41 +319,56 @@ fn bounds_from_generic_predicates<'tcx>(
...
-        // FIXME: this is not currently supported syntax, we should be looking at the `types` and
-        // insert the associated types where they correspond, but for now let's be "lazy" and
-        // propose this instead of the following valid resugaring:
-        // `T: Trait, Trait::Assoc = K` → `T: Trait<Assoc = K>`
-        where_clauses.push(format!("{} = {}", tcx.def_path_str(p.projection_ty.def_id), p.term));
+        if let ty::Param(_) = ty.kind() {
+            let mut bounds_str = vec![];
+            for bound in bounds {
+                let mut projections_str = vec![];
+                for projection in &projections {
```
Comment (bvanjoi) [inline compiler/rustc_hir_analysis/src/check/mod.rs:330]: This change has increased the time complexity of ﻿`bounds_from_generic_predicates` from O(n^2) to O(n^3)

File: compiler/rustc_hir_analysis/src/check/mod.rs [hunk 4]
```diff
@@ -319,41 +319,56 @@ fn bounds_from_generic_predicates<'tcx>(
...
+            );
+        }
     }
+
+    let generics =
+        if types_str.is_empty() { "".to_string() } else { format!("<{}>", types_str.join(", ")) };
+
     let where_clauses = if where_clauses.is_empty() {
-        String::new()
+        "".to_string()
```
Comment (bvanjoi) [inline compiler/rustc_hir_analysis/src/check/mod.rs:367]: There is no actual effect of the change, just making it consistent with the way it is written above

**Comment by WaffleLapkin** [comment]
r? wg-diagnostics

**Comment by TaKO8Ki** [comment]
I'll review it when I have time.

**Comment by Dylan-DPC** [comment]
@bvanjoi any updates on this?

**Comment by bvanjoi** [comment]
Hello @TaKO8Ki, just a friendly reminder when you have time, could you please review this?

File: compiler/rustc_hir_analysis/src/check/mod.rs [hunk 5]
```diff
@@ -319,41 +319,56 @@ fn bounds_from_generic_predicates<'tcx>(
...
+            for bound in bounds {
+                let mut projections_str = vec![];
+                for projection in &projections {
+                    let p = projection.skip_binder();
+                    let alias_ty = p.projection_ty;
+                    if bound == tcx.parent(alias_ty.def_id) && alias_ty.self_ty() == ty {
+                        let def_path = tcx.def_path(alias_ty.def_id);
+                        projections_str.push(format!(
+                            "{} = {}",
+                            def_path.data.last().unwrap(),
```
Comment (bvanjoi) [inline compiler/rustc_hir_analysis/src/check/mod.rs:337]: I'm uncertain whether it's safe to use ﻿`unwrap` in this context

Comment (compiler-errors) [reply compiler/rustc_hir_analysis/src/check/mod.rs:337]: I think it's easier to just get `tcx.item_name(alias_ty.def_id)` to get the name of the associated type

Comment (cjgillot) [reply compiler/rustc_hir_analysis/src/check/mod.rs:337]: Should RPITIT be skipped here?

Comment (compiler-errors) [reply compiler/rustc_hir_analysis/src/check/mod.rs:337]: RPITITs shouldn't show up here anyways, or else I'd consider that a bug in the caller?

**Comment by bvanjoi** [comment]
It appears that TaKO8Ki is busy, so r? @compiler-errors

**Comment by compiler-errors** [comment]
For the record, this is still waiting on author.

File: compiler/rustc_hir_analysis/src/check/mod.rs (hunk 5 above)
Comment (bvanjoi) [reply compiler/rustc_hir_analysis/src/check/mod.rs]: > RPITITs shouldn't show up here anyways

Sorry, I am slightly perplexed by this case. To clarify, considering the following code:

```rs
trait TraitA {
     type A;
}

trait TraitB<T> {
    fn f(&self) -> impl TraitA<Item = T>;
}

struct X;
impl TraitB<u8> for X {}
```

Are you suggesting that we should avoid displaying the help message for `﻿implement the missing item: 'fn f(&self) -> impl TraitB<Item = u8> { todo!() }' `?

File: compiler/rustc_hir_analysis/src/check/mod.rs (hunk 3 above)
Comment (compiler-errors) [reply compiler/rustc_hir_analysis/src/check/mod.rs:331]: This doesn't matter -- it's a diagnostic-only function after all.

**Review by compiler-errors — APPROVED** [review]

**Comment by compiler-errors** [comment]
Sorry @bvanjoi -- next time, please ping me when I fail to review your PRs in a timely fashion.

@bors r+

**Comment by bvanjoi** [comment]
I'm unsure why the CI failed, as I couldn't reproduce this error when executing ﻿`./x.py test src/book`.

Nonetheless, I've rebased with the master and forcefully pushed the changes again.
