### PR TITLE
Fix span of redundant generic arguments

### LINKED ISSUE #71563: Confusing error message with “^^unexpected lifetime argument” pointing to non-lifetime argument.
```rust
type Foo<'a, T> = &'a T;

struct Bar;

fn foo() {
    let x: Foo<'static, Bar, 'static>;
}
```

([Playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=094fb6a9240a66b36a2f8c6b58e5c183))

Errors:

```
   Compiling playground v0.0.1 (/playground)
error[E0107]: wrong number of lifetime arguments: expected 1, found 2
 --> src/lib.rs:6:25
  |
6 |     let x: Foo<'static, Bar, 'static>;
  |                         ^^^ unexpected lifetime argument

error: aborting due to previous error

For more information about this error, try `rustc --explain E0107`.
error: could not compile `playground`.

To learn more, run the command again with --verbose.

```

@rustbot modify labels: A-diagnostics, D-confusing, T-compiler, D-papercut, C-bug

### PR DESCRIPTION
**Pull request by 0yoyoyo**
Fixes #71563

Above issue is about lifetime arguments, but generic arguments also have same problem.
This PR fixes both help messages.

### CODE REVIEW

File: compiler/rustc_typeck/src/structured_errors/wrong_number_of_generic_args.rs [hunk 1]
```diff
@@ -626,32 +626,42 @@ impl<'a, 'tcx> WrongNumberOfGenericArgs<'a, 'tcx> {
...
-            let idx_first_redundant_lt_args = self.num_expected_lifetime_args();
+            let mut lt_arg_indices = Vec::new();
+            let mut found_redundant = false;
+            for (i, arg) in self.gen_args.args.iter().enumerate() {
+                if let hir::GenericArg::Lifetime(_) = arg {
+                    if i > self.num_expected_lifetime_args() - 1 {
+                        found_redundant = true;
+                    }
+                    lt_arg_indices.push(i);
+                } else if found_redundant == true {
```
Comment (petrochenkov) [inline compiler/rustc_typeck/src/structured_errors/wrong_number_of_generic_args.rs:637]:
```suggestion
                } else if found_redundant {
```

File: compiler/rustc_typeck/src/structured_errors/wrong_number_of_generic_args.rs [hunk 2]
```diff
@@ -626,32 +626,42 @@ impl<'a, 'tcx> WrongNumberOfGenericArgs<'a, 'tcx> {
...
         let remove_lifetime_args = |err: &mut DiagnosticBuilder<'_>| {
-            let idx_first_redundant_lt_args = self.num_expected_lifetime_args();
+            let mut lt_arg_indices = Vec::new();
+            let mut found_redundant = false;
+            for (i, arg) in self.gen_args.args.iter().enumerate() {
+                if let hir::GenericArg::Lifetime(_) = arg {
+                    if i > self.num_expected_lifetime_args() - 1 {
+                        found_redundant = true;
+                    }
+                    lt_arg_indices.push(i);
```
Comment (petrochenkov) [inline compiler/rustc_typeck/src/structured_errors/wrong_number_of_generic_args.rs:636]:
```suggestion
                    lt_arg_spans.push(arg.span());
```
Spans are the only thing for which `lt_arg_indices` is used, so we can just collect spans.

File: compiler/rustc_typeck/src/structured_errors/wrong_number_of_generic_args.rs [hunk 3]
```diff
@@ -626,32 +626,42 @@ impl<'a, 'tcx> WrongNumberOfGenericArgs<'a, 'tcx> {
...
-                    .shrink_to_hi();
-                span_lo_redundant_lt_args.to(span_hi)
-            } else {
-                span_lo_redundant_lt_args.to(span_hi_redundant_lt_args)
-            };
+            let idx_last_redundant_lt_args = lt_arg_indices[lt_arg_indices.len() - 1];
+            let span_hi_redundant_lt_args =
+                self.gen_args.args[idx_last_redundant_lt_args].span().shrink_to_hi();
+
+            let span_redundant_lt_args = span_lo_redundant_lt_args.to(span_hi_redundant_lt_args);
```
Comment (petrochenkov) [inline compiler/rustc_typeck/src/structured_errors/wrong_number_of_generic_args.rs:655]: `shrink_to_hi` above shouldn't be necessary, `to` alone will do the same thing.

File: compiler/rustc_typeck/src/structured_errors/wrong_number_of_generic_args.rs [hunk 4]
```diff
@@ -626,32 +626,42 @@ impl<'a, 'tcx> WrongNumberOfGenericArgs<'a, 'tcx> {
...
 
+            let num_redundant_lifetime_args =
+                lt_arg_indices.len() - self.num_expected_lifetime_args();
             let msg_lifetimes = format!(
                 "remove {} {} argument{}",
-                if num_redundant_args == 1 { "this" } else { "these" },
+                if num_redundant_lifetime_args == 1 { "this" } else { "these" },
                 "lifetime",
-                pluralize!(num_redundant_lt_args),
+                pluralize!(num_redundant_lifetime_args),
```
Comment (petrochenkov) [inline compiler/rustc_typeck/src/structured_errors/wrong_number_of_generic_args.rs:664]:
```suggestion
                pluralize!(num_redundant_lt_args),
```
Nit: other variables above use `lt`, so renaming this variable alone seems inconsistent.

File: compiler/rustc_typeck/src/structured_errors/wrong_number_of_generic_args.rs (hunk 2 above)
Comment (petrochenkov) [reply compiler/rustc_typeck/src/structured_errors/wrong_number_of_generic_args.rs:636]: Same applies to the logic for type/const parameters below.

File: compiler/rustc_typeck/src/structured_errors/wrong_number_of_generic_args.rs [hunk 5]
```diff
@@ -663,26 +673,38 @@ impl<'a, 'tcx> WrongNumberOfGenericArgs<'a, 'tcx> {
...
+            let mut found_redundant = false;
+            for (i, arg) in self.gen_args.args.iter().enumerate() {
+                match arg {
+                    hir::GenericArg::Type(_) | hir::GenericArg::Const(_) => {
+                        if i > self.num_expected_lifetime_args() - 1 {
+                            found_redundant = true;
+                        }
+                        gen_arg_indices.push(i);
+                    }
+                    _ if found_redundant == true => break,
```
Comment (petrochenkov) [inline compiler/rustc_typeck/src/structured_errors/wrong_number_of_generic_args.rs:686]:
```suggestion
                    _ if found_redundant => break,
```

File: compiler/rustc_typeck/src/structured_errors/wrong_number_of_generic_args.rs (hunk 3 above)
Comment (petrochenkov) [reply compiler/rustc_typeck/src/structured_errors/wrong_number_of_generic_args.rs:655]: Same applies to the logic for type/const parameters below.

**Comment by 0yoyoyo** [comment]
Thank you for your review. I have fixed the code.

@rustbot label -S-waiting-on-author +S-waiting-on-review

File: compiler/rustc_typeck/src/structured_errors/wrong_number_of_generic_args.rs [hunk 6]
```diff
@@ -626,30 +626,35 @@ impl<'a, 'tcx> WrongNumberOfGenericArgs<'a, 'tcx> {
...
-                    .shrink_to_hi();
-                span_lo_redundant_lt_args.to(span_hi)
-            } else {
-                span_lo_redundant_lt_args.to(span_hi_redundant_lt_args)
-            };
+            let mut lt_arg_spans = Vec::new();
+            let mut found_redundant = false;
+            for (i, arg) in self.gen_args.args.iter().enumerate() {
+                if let hir::GenericArg::Lifetime(_) = arg {
+                    if i > self.num_expected_lifetime_args() - 1 {
```
Comment (petrochenkov) [inline compiler/rustc_typeck/src/structured_errors/wrong_number_of_generic_args.rs:633]:
```suggestion
                    if i >= self.num_expected_lifetime_args() {
```
Looks the case of 0 expected lifetime arguments is possible, the the current logic won't behave correctly.
(It would be good to add a test case for this.)

File: compiler/rustc_typeck/src/structured_errors/wrong_number_of_generic_args.rs [hunk 7]
```diff
@@ -663,26 +668,34 @@ impl<'a, 'tcx> WrongNumberOfGenericArgs<'a, 'tcx> {
...
         let remove_type_or_const_args = |err: &mut DiagnosticBuilder<'_>| {
-            let idx_first_redundant_type_or_const_args = self.get_lifetime_args_offset()
-                + num_redundant_lt_args
-                + self.num_expected_type_or_const_args();
+            let mut gen_arg_spans = Vec::new();
+            let mut found_redundant = false;
+            for (i, arg) in self.gen_args.args.iter().enumerate() {
+                match arg {
+                    hir::GenericArg::Type(_) | hir::GenericArg::Const(_) => {
+                        if i > self.num_expected_lifetime_args() - 1 {
```
Comment (petrochenkov) [inline compiler/rustc_typeck/src/structured_errors/wrong_number_of_generic_args.rs:676]:
```suggestion
                        if i >= self.num_expected_type_or_const_args() {
```

**Comment by petrochenkov** [comment]
r=me after addressing the remaining comments and squashing commits.

File: compiler/rustc_typeck/src/structured_errors/wrong_number_of_generic_args.rs (hunk 7 above)
Comment (0yoyoyo) [reply compiler/rustc_typeck/src/structured_errors/wrong_number_of_generic_args.rs]: Thanks. It is obviously my mistake.

File: compiler/rustc_typeck/src/structured_errors/wrong_number_of_generic_args.rs (hunk 6 above)
Comment (0yoyoyo) [reply compiler/rustc_typeck/src/structured_errors/wrong_number_of_generic_args.rs]: Thank you for checking. And I also found that `lt_arg_spans.len()` instead of `i` should be used to get the number of lifetime arguments.

**Comment by 0yoyoyo** [comment]
Thanks a lot. I addressed the comments and squashed my commits.

@rustbot label -S-waiting-on-author +S-waiting-on-review
