### PR TITLE
[rustdoc] Fix system theme detection

### LINKED ISSUE #63830: Automatic dark theme doesn't work
Requested in #61079 and implemented in #61236, the automatic theme switching doesn't seem to do anything: If I visit <https://doc.rust-lang.org/nightly/std/> while the system is in dark mode, I can see in the developer tools that the `<html>` element has the style `content: "dark";`, but the page is still showing as the light theme. Local storage is empty for doc.rust-lang.org, and the issue affects private windows as well.

Tested on:

* Firefox 68.0.2 on macOS 10.14.6
* Firefox 68.0.2 on Windows 10
* Chrome 76.0.3809.100 on Windows 10

cc @GuillaumeGomez

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Fixes #63830 

The problem is that it returns the property "entirely" (so with the quotes in our case). Removing them fixes the issue.

cc @fenhl

r? @kinnison

### CODE REVIEW

File: src/librustdoc/html/static/storage.js [hunk 1]
```diff
@@ -118,7 +118,8 @@ function switchTheme(styleElem, mainStyleElem, newTheme, saveTheme) {
 }
 
 function getSystemValue() {
-    return getComputedStyle(document.documentElement).getPropertyValue('content');
+    var property = getComputedStyle(document.documentElement).getPropertyValue('content');
+    return property.replace(/\"/g, "").replace(/\'/g, "");
```
Comment (bjorn3) [inline src/librustdoc/html/static/storage.js]:
```suggestion
    return property.replace(/[\"\']/g, "");
```

**Comment by kinnison** [comment]
I'm afraid I have no way to know for certain if this functions correctly.

File: src/librustdoc/html/static/storage.js (hunk 1 above)
Comment (GuillaumeGomez) [reply src/librustdoc/html/static/storage.js]: In case we change the css for whatever reason, I'd prefer to keep the replace of single quotes as well. Let's avoid surprising regressions if possible.

**Comment by GuillaumeGomez** [comment]
You can run the code of the function in your browser directly (yes, again... sorry...). You just need to ensure it returns "dark" or "light" without double quotes.

File: src/librustdoc/html/static/storage.js (hunk 1 above)
Comment (kinnison) [reply src/librustdoc/html/static/storage.js]: Surely @bjorn3's suggestion replaces both double and single quotes, just in one .replace() call?

**Comment by kinnison** [comment]
Okay, so with the direct browser intervention I can confirm this works, either the way originally written, or the way that @bjorn3 suggests.  I'm fine with either.

@bors r=kinnison

File: src/librustdoc/html/static/storage.js (hunk 1 above)
Comment (GuillaumeGomez) [reply src/librustdoc/html/static/storage.js]: Oh indeed! Completely missed it... Sorry @bjorn3...

**Comment by GuillaumeGomez** [comment]
Updated with @bjorn3's suggestion.

**Comment by fenhl** [comment]
Any updates on this? Do we need to find a different reviewer since @kinnison doesn't have access?

**Comment by GuillaumeGomez** [comment]
No, I think @kinnison's approval is enough considering this is quite a small PR with a very small impact. I was waiting for CI and forgot about this PR...

@bors: r=kinnison rollup
