### PR TITLE
Fix ICE for unexpected `<` in pattern

### LINKED ISSUE #22426: Panic: "internal compiler error: ident only path should have been covered already"
This error is triggered by providing type parameters to a generic type in a `match` pattern.

e.g.
```rust
#![crate_type = "staticlib"]

pub struct Foo<T>(T, T);

impl<T> Foo<T> {
    fn foo(&self) {
        match *self {
            Foo<T>(x, y) => println!("Goodbye, World!")
        }
    }
}
```
[Playpen here.](http://is.gd/qUaQmI)

### PR DESCRIPTION
**Pull request by bombless**
Closes https://github.com/rust-lang/rust/issues/22426

I'm not sure which is better:
- simply "unexpected token `<`"
- "unexpected token `<`, expect one of `=>`, `:`, `(`"

But this PR is actually mergable now

### CODE REVIEW

File: src/test/run-pass/issue-22426.rs [hunk 1]
```diff
@@ -0,0 +1,28 @@
...
+// <LICENSE-MIT or http://opensource.org/licenses/MIT>, at your
+// option. This file may not be copied, modified, or distributed
+// except according to those terms.
+
+struct Foo<T>(T, T);
+
+impl<T> Foo<T> {
+    fn foo(&self) {
+        match *self {
+            Foo::<T>(ref x, ref y) => {
```
Comment (pnkfelix) [inline src/test/run-pass/issue-22426.rs]: hmm, I'm not actually sure we should accept this syntax in a pattern ...

Comment (pnkfelix) [inline src/test/run-pass/issue-22426.rs]: (of course it could be that we're *already* accepting this syntax in a pattern.  But nonetheless, I'm not sure I want to validate such acceptance in a formal test.)

Comment (bombless) [inline src/test/run-pass/issue-22426.rs]: But current nightly accept it.
I was surprising too.

Comment (pnkfelix) [inline src/test/run-pass/issue-22426.rs]: Well, lets bring up this up as a separate question to the team.  (We have a triage meeting in 1.5 hours; I'll file a ticket for it.)

**Comment by pnkfelix** [comment]
@bombless r=me if you remove the aforementioned questionable run-pass test.

**Comment by bombless** [comment]
r=@pnkfelix

**Comment by bombless** [comment]
@bors r=pnkfelix 
https://github.com/rust-lang/rust/pull/22172 seems that rebase will be needed soon.

**Comment by bombless** [comment]
r=pnkfelix
@bors: retry
