### PR TITLE
make memrchr use align_offset

### LINKED ISSUE #50567: miri: printing with full mir doesn't work because of pointer aligning inside memrchr
https://github.com/rust-lang/rust/blob/13e07a4e180e964717a0f71f0fc40260bab7d84a/src/libcore/slice/memchr.rs#L106

```
error: a raw memory access tried to access part of a pointer value as raw bytes

error[E0080]: constant evaluation error
   --> /Users/bjorn/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/src/libcore/slice/memchr.rs:106:21
    |
106 |     let end_align = (ptr as usize + len) & (usize_bytes - 1);
    |                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ a raw memory access tried to access part of a pointer value as raw bytes
    |
note: inside call to `core::slice::memchr::memrchr`
   --> /Users/bjorn/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/src/libstd/sys/unix/memchr.rs:53:9
    |
53  |         ::core::slice::memchr::memrchr(needle, haystack)
    |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
note: inside call to `std::sys::unix::memchr::memrchr::memrchr_specific`
   --> /Users/bjorn/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/src/libstd/sys/unix/memchr.rs:56:5
    |
56  |     memrchr_specific(needle, haystack)
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
note: inside call to `std::sys::unix::memchr::memrchr`
   --> /Users/bjorn/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/src/libstd/memchr.rs:55:5
    |
55  |     ::sys::memchr::memrchr(needle, haystack)
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
note: inside call to `std::memchr::memrchr`
   --> /Users/bjorn/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/src/libstd/io/buffered.rs:905:23
    |
905 |         let i = match memchr::memrchr(b'/n', buf) {
    |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
note: inside call to `<std::io::LineWriter<W> as std::io::Write><std::io::stdio::Maybe<std::io::stdio::StdoutRaw>>::write`
   --> /Users/bjorn/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/src/libstd/io/stdio.rs:465:9
    |
465 |         self.inner.borrow_mut().write(buf)
    |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
note: inside call to `<std::io::StdoutLock<'a> as std::io::Write>::write`
   --> /Users/bjorn/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/src/libstd/io/mod.rs:1111:19
    |
1111|             match self.write(buf) {
    |                   ^^^^^^^^^^^^^^^
[...]
```

### PR DESCRIPTION
**Pull request by RalfJung**
I hope I did not screw that up...

Cc @oli-obk who authored the original https://github.com/rust-lang/rust/pull/44537

Fixes #50567 (thanks @bjorn3)

### CODE REVIEW

File: src/libcore/slice/memchr.rs [hunk 1]
```diff
@@ -102,8 +102,24 @@ pub fn memrchr(x: u8, text: &[u8]) -> Option<usize> {
     let ptr = text.as_ptr();
     let usize_bytes = mem::size_of::<usize>();
 
+    // a version of align_offset that says how much must be *subtracted*
+    // from a pointer to be aligned.
+    #[inline(always)]
+    fn align_offset_down(ptr: *const u8, align: usize) -> usize {
```
Comment (nagisa) [inline src/libcore/slice/memchr.rs]: Consider `slice::align_to::<usize>()`? I believe that does exactly what a large part of this code does.

File: src/libcore/slice/memchr.rs [hunk 2]
```diff
@@ -102,8 +102,24 @@ pub fn memrchr(x: u8, text: &[u8]) -> Option<usize> {
...
+        let align_offset = ptr.align_offset(align);
+        if align_offset > align {
+            // Not possible to align
+            usize::max_value()
+        } else if align_offset == 0 {
+            0
+        } else {
+            // E.g. if align=8 and we have to add 1, then we can also subtract 7.
+            align - align_offset
```
Comment (eddyb) [inline src/libcore/slice/memchr.rs]: You probably want `(align - align_offset) & (align - 1)` (or `% align` if you're sure it will optimize) instead of the last if/else. Not sure about the first one though, seems kinda fine as-is.

File: src/libcore/slice/memchr.rs (hunk 1 above)
Comment (RalfJung) [reply src/libcore/slice/memchr.rs]: Hm, plausible. Should I then also do that for `memchr`?

Comment (RalfJung) [reply src/libcore/slice/memchr.rs]: Actually it's not so easy, we want to do the main loop on a `u8` slice, not `usize` (or actually pairs of `usize`, which is the steps that the loop is taking).

**Comment by RalfJung** [comment]
Now we just have to hope that `align_to` gets inline, but that [seems to be the case](https://play.rust-lang.org/?gist=7144d9e64fcdf2fc28a5549eb48aecc8&version=nightly&mode=release&edition=2015).

**Comment by bjorn3** [comment]
closes #50567
