### PR TITLE
Fix O(tests) stack usage in edition 2024 mergeable doctests

### LINKED ISSUE #138248: Stack overflow on large doctests in edition 2024 on Windows
Over in https://github.com/rust-lang/rust/pull/138162 I am trying to update the standard library to Rust 2024. I'm running into a problem where core's doctests are failing on x86_64-pc-windows-msvc.

The behavior is:

1. Rustdoc prints `thread 'main' has overflowed its stack`
2. It then starts running the tests: `running 1672 tests`
3. After they are all done, it prints `test result: ok. 1671 passed; 0 failed; 1 ignored; 0 measured; 0 filtered out; finished in 109.68s`
4. After all the tests complete, it exits 101.

From what I can tell, there is a `const TESTS: [test::TestDescAndFn; 3641]` array in the combined test code. When calling `test::test_main`, it fails somewhere in there. I'm struggling a bit figuring out a good way to debug exactly where the stack is overflowing.

There are a few issues here:

1. Obviously it shouldn't overflow its stack.
2. The "has overflowed its stack" message has no context, and doesn't explain where it is coming from (it is coming from executing the combined suite, but for some reason I guess rustdoc continues to run the uncombined tests?).
3. The error is at the beginning of the output, but there is no summary at the end to explain what has happened (like the normal test runner would do if an individual test would fail). In fact, it prints a summary that says "everything was okay" when it was not.

I haven't put together an isolated repro. I wonder if just creating something with 4,000 doctests would suffice? So far, I've been using `--persist-doctests` to get a copy of core's combined suite, and then running `rustc` directly on that.

cc @notriddle @GuillaumeGomez

### PR DESCRIPTION
**Pull request by saethlin**
Fixes https://github.com/rust-lang/rust/issues/138248

The important change here is that we are not passing a potentially-large array by value. Between the fact that `TestFn` cannot be `Clone` and `test_main` takes a `Vec<TestDescAndFn>`, the only way to call `test::test_main` without O(tests) stack use is to call `Vec::push` many times.

The normal test harness does not have this problem because it calls `test_main_static` or `test_main_static_abort`, which take `&[TestDescAndFn]`. Changing `test::test_main` to take a slice is not a simple change, so I'm avoiding doing it here.

### CODE REVIEW

**Review by GuillaumeGomez — APPROVED** [review]

**Comment by saethlin** [comment]
Took me a while to figure out what was going on; I broke the test runner and somehow that made rustdoc fall back to not merging doctests. Should be good now, and I had to redesign the approach a bit to get it to compile :facepalm:

File: src/librustdoc/doctest/runner.rs [hunk 1]
```diff
@@ -136,19 +133,23 @@ mod __doctest_mod {{
 
 #[rustc_main]
 fn main() -> std::process::ExitCode {{
-const TESTS: [test::TestDescAndFn; {nb_tests}] = [{ids}];
+let tests = {{
+    let mut tests = Vec::new();
```
Comment (GuillaumeGomez) [inline src/librustdoc/doctest/runner.rs:137]: Can you at least use `with_capacity` since we already have `nb_tests`?

Comment (saethlin) [reply src/librustdoc/doctest/runner.rs]: Yeah!

**Review by GuillaumeGomez — APPROVED** [review]

**Comment by GuillaumeGomez** [comment]
Thanks!

@bors r+
