### PR TITLE
Suggest adding semicolon in user code rather than macro impl details

### LINKED ISSUE #139049: Misleading compiler suggestion: Add semicolon in rustlib due to missing `;` in user code
### Code

```Rust
use std::fmt::{self, Display};

struct Mutex;

impl Mutex {
    fn lock(&self) -> MutexGuard {
        MutexGuard(self)
    }
}

struct MutexGuard<'a>(&'a Mutex);

impl<'a> Drop for MutexGuard<'a> {
    fn drop(&mut self) {
    }
}

struct Out;

impl Out {
    fn write_fmt(&self, _args: fmt::Arguments) {}
}

impl<'a> Display for MutexGuard<'a> {
    fn fmt(&self, _formatter: &mut fmt::Formatter) -> fmt::Result {
        Ok(())
    }
}

fn main() {
    let _write = {
        let mutex = Mutex;
        write!(Out, "{}", mutex.lock())
    };
}
```

### Current output

```Shell
error[E0597]: `mutex` does not live long enough
  --> .\test.rs:35:27
   |
34 |         let mutex = Mutex;
   |             ----- binding `mutex` declared here
35 |         write!(Out, "{}", mutex.lock())
   |                           ^^^^^-------
   |                           |
   |                           borrowed value does not live long enough
   |                           a temporary with access to the borrow is created here ...
36 |     };
   |     -- ... and the borrow might be used here, when that temporary is dropped and runs the `Drop` code for type `MutexGuard`
   |     |
   |     `mutex` dropped here while still borrowed
   |
help: consider adding semicolon after the expression so its temporaries are dropped sooner, before the local variables declared by the block are dropped
  --> C:\Users\jjl98\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib/rustlib/src/rust\library\core\src\macros\mod.rs:650:55
   |
650|         $dst.write_fmt($crate::format_args!($($arg)*));
   |                                                       +

error: aborting due to 1 previous error

For more information about this error, try `rustc --explain E0597`.
```

### Desired output

```Shell
error[E0597]: `mutex` does not live long enough
  --> .\test.rs:35:27
   |
34 |         let mutex = Mutex;
   |             ----- binding `mutex` declared here
35 |         write!(Out, "{}", mutex.lock())
   |                           ^^^^^-------
   |                           |
   |                           borrowed value does not live long enough
   |                           a temporary with access to the borrow is created here ...
36 |     };
   |     -- ... and the borrow might be used here, when that temporary is dropped and runs the `Drop` code for type `MutexGuard`
   |     |
   |     `mutex` dropped here while still borrowed
   |
help: consider adding semicolon after the expression so its temporaries are dropped sooner, before the local variables declared by the block are dropped
  --> .\test.rs:35:40
   |
35 |         write!(Out, "{}", mutex.lock());
   |                                        +

error: aborting due to 1 previous error

For more information about this error, try `rustc --explain E0597`.
```

### Rationale and extra context

_No response_

### Other cases

```Rust

```

### Rust Version

```Shell
rustc 1.85.1 (4eb161250 2025-03-15)
binary: rustc
commit-hash: 4eb161250e340c8f48f66e2b929ef4a5bed7c181
commit-date: 2025-03-15
host: x86_64-pc-windows-msvc
release: 1.85.1
LLVM version: 19.1.7
```

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by Urgau**
This PR tries to find the right span (by peeling expansion) so that the suggestion for adding a semicolon is suggested in user code rather than in the expanded code (in the example a macro impl).

Fixes rust-lang/rust#139049
r? @fmease

### CODE REVIEW

File: compiler/rustc_borrowck/src/diagnostics/explain_borrow.rs [hunk 1]
```diff
@@ -349,7 +349,10 @@ impl<'tcx> BorrowExplanation<'tcx> {
                                     old.to(info.span.shrink_to_hi()).contains(new)
                                 }) {
                                     err.span_suggestion_verbose(
-                                        info.span.shrink_to_hi(),
+                                        info.span
```
Comment (fmease) [inline compiler/rustc_borrowck/src/diagnostics/explain_borrow.rs]: Could you also do something similar in the `else` branch of `if info.tail_result_is_ignored`? It currently has a very similar issue:

```rs
//- snip -//

fn main() {
    use std::io::Write as _;

    let _write = {
        let mutex = Mutex;
        write!(std::io::stdout(), "{}", mutex.lock())
    };
}
```

(the difference between the original snippet and this one is the fact that `std::io::Write::write_fmt` returns something other than `()`)

```
help: for example, you could save the expression's value in a new local variable `x` and then make `x` be the expression at the end of the block
  --> /playground/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/macros/mod.rs:624:9
   |
624|         let x = $dst.write_fmt($crate::format_args!($($arg)*)); x
   |         +++++++                                               +++

```

File: tests/ui/borrowck/span-semicolon-issue-139049.fixed
Comment (fmease) [inline tests/ui/borrowck/span-semicolon-issue-139049.fixed:1]: I wonder if we should reduce the file size of this regression test by using `Mutex` and `MutexGuard` from `std`. Right now, it's a bit unwieldy..

**Review by fmease — APPROVED** [review]
Thanks! r=me with two nits addressed in one way or another

**Comment by fmease** [comment]
Ah, we also need a test bless / and the sysroot sources are not available / suppressed in tests IIRC, you might need an aux crate for a custom `write!` maybe, i didn't look too closely

File: compiler/rustc_borrowck/src/diagnostics/explain_borrow.rs (hunk 1 above)
Comment (Urgau) [reply compiler/rustc_borrowck/src/diagnostics/explain_borrow.rs]: Good idea, also fixed the "else" branch.

File: tests/ui/borrowck/span-semicolon-issue-139049.fixed
Comment (Urgau) [reply tests/ui/borrowck/span-semicolon-issue-139049.fixed:1]: I rather keep it the same as the issue, just in case something changes in the standard library or elsewhere.

File: tests/ui/borrowck/span-semicolon-issue-139049.rs [hunk 2]
```diff
@@ -0,0 +1,52 @@
...
+    }
+}
+
+fn main() {
+    let _write = {
+        let mutex = Mutex;
+        write!(Out, "{}", mutex.lock())
+        //~^ ERROR `mutex` does not live long enough
+        //~| SUGGESTION ;
+    };
```
Comment (m-ou-se) [inline tests/ui/borrowck/span-semicolon-issue-139049.rs:42]: ~~@Urgau #140748 makes this just work, so this new test blocks me from merging that PR. Should I remove it? Is there a different way to test what you want to test?~~

No wait, the error still appears. Only the suggestion doesn't appear. Investigating..

Comment (m-ou-se) [reply tests/ui/borrowck/span-semicolon-issue-139049.rs:42]: I just noticed that this test passes in _Rust 2024_, due to the new rules for temporaries in tail expressions.

Comment (fmease) [reply tests/ui/borrowck/span-semicolon-issue-139049.rs:42]: > I just noticed that this test passes in Rust 2024

Sure, but we still want to provide non-butchered / good diagnostics in older editions, they have "long-term support".

Comment (fmease) [reply tests/ui/borrowck/span-semicolon-issue-139049.rs:42]: We could replace that test with the following one:

```rs
// Make sure the generated suggestion suggest editing the user code instead of
// the macro implementation (which might come from an external crate).
// issue: <https://github.com/rust-lang/rust/issues/139049>

// You could assume that this comes from an extern crate (it doesn't
// because an aux crate would be overkill for this test).
macro_rules! perform { ($e:expr) => { D(&$e).end() } }

fn main() {
    { let l = (); perform!(l) }; //~ ERROR does not live long enough
    //~^ SUGGESTION ;
    let _x = { let l = (); perform!(l) }; //~ ERROR does not live long enough
    //~| SUGGESTION let x
}

struct D<T>(T);
impl<T> Drop for D<T> { fn drop(&mut self) {} }
impl<T> D<T> { fn end(&self) -> String { String::new()} }
```

Comment (fmease) [reply tests/ui/borrowck/span-semicolon-issue-139049.rs:42]: Or modify `tests/ui/nll/issue-54556-used-vs-unused-tails.rs` and add it there

Comment (m-ou-se) [reply tests/ui/borrowck/span-semicolon-issue-139049.rs:42]: @fmease That test doesn't work. Then it just suggests to add the `;` inside the macro definition.
