### PR TITLE
Fix race condition when allocating source files in SourceMap

### LINKED ISSUE #69261: librustc_span has a concurrency bug
librustc_span contains a concurrency bug. Even though, rustc works without any problem.
(I guess rustc process does not use multiples threads to load file to sourcemap.)

https://github.com/rust-lang/rust/blob/0176a9eef845e7421b7e2f7ef015333a41a7c027/src/librustc_span/source_map.rs#L216-L261

When multiple threads invoked this method at a time, it results in overlapping spans. 
(Because the lock is released while analyzing the source file)

### Meta
Simple fix: https://github.com/swc-project/swc/pull/672/files#diff-8d69cef1163ff9667c130830b15da62bL181-L188

### PR DESCRIPTION
**Pull request by Zoxc**
This makes allocating address space in the source map an atomic operation. `rustc` does not currently do this in parallel, so this bug can't trigger, but parsing files in parallel could trigger it, and that is something we want to do.

Fixes https://github.com/rust-lang/rust/issues/69261.

r? @wesleywiser

### CODE REVIEW

**Comment by Zoxc** [comment]
cc @petrochenkov

File: src/librustc_span/source_map.rs [hunk 1]
```diff
@@ -194,12 +209,25 @@ impl SourceMap {
...
     }
 
-    fn next_start_pos(&self) -> usize {
-        match self.files.borrow().source_files.last() {
-            None => 0,
-            // Add one so there is some space between files. This lets us distinguish
-            // positions in the `SourceMap`, even in the presence of zero-length files.
-            Some(last) => last.end_pos.to_usize() + 1,
+    fn allocate_address_space(&self, size: usize) -> Result<usize, OffsetOverflowError> {
+        let size = u32::try_from(size).map_err(|_| OffsetOverflowError)?;
```
Comment (wesleywiser) [inline src/librustc_span/source_map.rs]: I think you can do 

```suggestion
        // Add one so there is some space between files. This lets us distinguish
        // positions in the `SourceMap`, even in the presence of zero-length files.
        let size = u32::try_from(size + 1).map_err(|_| OffsetOverflowError)?;
```

here which avoids needing to `and_then()` the `checked_add` below.

**Review by wesleywiser — APPROVED** [review]
One small comment. If you don't think it's worthwhile, feel free to r=me this.

**Comment by petrochenkov** [comment]
cc @matklad

File: src/librustc_span/source_map.rs (hunk 1 above)
Comment (Zoxc) [reply src/librustc_span/source_map.rs]: That addition could also overflow though.

Comment (wesleywiser) [reply src/librustc_span/source_map.rs]: Yeah, that's true. That would imply `src` is `usize::max` long though. Wouldn't we already have OOM'd trying to read that in?

File: src/librustc_span/source_map.rs [hunk 2]
```diff
@@ -131,6 +133,9 @@ pub(super) struct SourceMapFiles {
 }
 
 pub struct SourceMap {
+    /// The address space below this value is currently used by the files in the sorce map.
```
Comment (mlodato517) [inline src/librustc_span/source_map.rs]:
```suggestion
    /// The address space below this value is currently used by the files in the source map.
```

File: src/librustc_span/source_map.rs (hunk 1 above)
Comment (mlodato517) [inline src/librustc_span/source_map.rs]: Just trying to learn here, hope I'm not adding noise to the PR - what is happening here? Is this basically handling the case where `usize` is larger than 32 bits and so `size` is larger than what fits in a `u32`?

File: src/librustc_span/source_map.rs [hunk 3]
```diff
@@ -194,12 +209,25 @@ impl SourceMap {
...
+            let next = current
+                .checked_add(size)
+                // Add one so there is some space between files. This lets us distinguish
+                // positions in the `SourceMap`, even in the presence of zero-length files.
+                .and_then(|next| next.checked_add(1))
+                .ok_or(OffsetOverflowError)?;
+
+            if self
+                .used_address_space
+                .compare_exchange(current, next, Ordering::Relaxed, Ordering::Relaxed)
```
Comment (mlodato517) [inline src/librustc_span/source_map.rs]: I'm having a hard time grokking [the docs](https://doc.rust-lang.org/std/sync/atomic/struct.AtomicUsize.html#method.compare_exchange). Can you give me a tl;dr for this? Is this updating `used_address_space` if it already equals `current` or something? If so, then can you explain if/how `current` is changing between loop iterations? (I'm assuming(⚠️) `checked_add` isn't mutating `current`).

File: src/librustc_span/lib.rs [hunk 4]
```diff
@@ -1089,14 +1089,12 @@ impl SourceFile {
             hasher.finish::<u128>()
         };
         let end_pos = start_pos.to_usize() + src.len();
-        if end_pos > u32::max_value() as usize {
-            return Err(OffsetOverflowError);
-        }
+        assert!(end_pos <= u32::max_value() as usize);
```
Comment (mlodato517) [inline src/librustc_span/lib.rs]: Is there any benefit/are we able to type `end_pos` as a `u32` if we're going to assert that it fits in a `u32` or, for indexing purposes (or something else) is it important that it's a `usize` that can fit in a `u32`?

**Review by mlodato517 — COMMENTED** [review]
Found a minor typo and am interested in trying to learn a little more about rust if you have the time to answer some questions :-) Also, I don't see any notes in `CONTRIBUTING.md` about reviewing PRs so I hope I'm not out of line in reviewing this. If there are some docs regarding when/how to review PRs - please link me to them so I don't make the mistake again.

File: src/librustc_span/source_map.rs (hunk 1 above)
Comment (wesleywiser) [reply src/librustc_span/source_map.rs]: Yes, exactly. `u32` is always 32bits, `u64` is always 64bits but `usize` is basically the size of a reference/pointer on the target platform. So for 32 bit environments, `usize` will be 32bits and for 64 bit environments, `usize` will be 64bits. So in a 64 bit environment, this conversion might fail because the value of `size` is larger than will fit in a 32 bit integer.

Comment (mlodato517) [reply src/librustc_span/source_map.rs]: Thanks!

File: src/librustc_span/source_map.rs (hunk 3 above)
Comment (wesleywiser) [reply src/librustc_span/source_map.rs]: > Is this updating used_address_space if it already equals current or something?

Yes. To understand why you'd want to do this, think about the use case for atomics. Typically the alternative to atomics is to use some kind of lock. In that scenario, you acquire a read/write lock on a value, perform a calculation, update the value and then release the lock. This kind of design is usually correct and easy to understand but can be bad for performance in some situations because you have to acquire a lock just to read the current value.

Atomics on the other hand, don't lock. Your CPU typically gives you special instructions or guarantees about existing instructions for certain sizes of data. These allow you to do things like read the entire value or write the entire value without the reads\writes becoming mangled with data from other threads. `compare_exchange` uses an instruction that says "if this is the same as the value I'm providing then update it". This lets you do things like the above where we read the value, perform a calculation to get a new value and if the value hasn't changed since we read it, then we can write the new value. If the value has changed, we loop around again and redo the operation until it succeeds.

This operation is sometimes called [compare and swap](https://en.wikipedia.org/wiki/Compare-and-swap).

Comment (mlodato517) [reply src/librustc_span/source_map.rs]: > if the value hasn't changed since we read it

Thank you _so_ much! This makes way more sense. I was reading this as "if the value I'm providing is the same as the value it already is, then update it" which made _no_ sense because you'd always be updating values to the values they already are :-P

File: src/librustc_span/lib.rs (hunk 4 above)
Comment (wesleywiser) [reply src/librustc_span/lib.rs]: The type we use [here](https://github.com/rust-lang/rust/pull/69266/files#diff-ec48da82b30ef2b77de7ef58ea62ccbcR137) is 32bit so it this needs to fit within it. The reason that's an `AtomicU32` is because `AtomicU64` is not available on 32 bit platforms.

**Comment by wesleywiser** [comment]
@mlodato517 If you have additional questions feel free to ask! Otherwise I'm going to mark those parts of your review resolved to keep this PR clean.

File: src/librustc_span/lib.rs (hunk 4 above)
Comment (mlodato517) [reply src/librustc_span/lib.rs]: Oh, sorry, I think my run-on-sentence question was confusing :-)

I guess I'm wondering why `end_pos` is typed as a `usize` instead of a `u32`.

I guess the `usize` could be smaller than 32bit? Or is this just because rust forces us to use `usize` when doing memory stuff?

Comment (wesleywiser) [reply src/librustc_span/lib.rs]: Oh, it's because `end_pos as u32 <= u32::max_value()` is always `true`. Even on 64 bit environments because the value will be truncated. Doing it this way means it's essentially a `no-op` on 32 bit platforms and it works correctly on 64 bit platforms. 

The very cautious thing to do would be to use `checked_add` here as well but this should already have been checked down [here](https://github.com/rust-lang/rust/pull/69266/files/cc4375b5110e7395efbc803c60dbc2ef83bb2604#diff-ec48da82b30ef2b77de7ef58ea62ccbcR217-R218) where we use `checked_add`

Comment (mlodato517) [reply src/librustc_span/lib.rs]: Oh hmmm yeah maybe this was the wrong line to put the comment on. I wasn't thinking
```rs
end_pos as u32 <= u32::max_value()
```
as much as
```rs
let end_pos: u32 = start_pos.to_u32() + src.len().to_u32();
```
or something. But if I'm reading you correctly it sounds like `to_u32()` would truncate the value instead of panicking saying, "This can't be safely cast to `u32`!"?

Comment (wesleywiser) [reply src/librustc_span/lib.rs]: There's no `usize::to_u32()` :)

If you do `u32::try_from()` you get `Option<u32>` which is `None` if the value is too large. If you do `foo as u32` that never fails but will truncate data if it's too large.

There's no convenience method because `u32::try_from(val).expect("too large")` is simple enough.

Comment (mlodato517) [reply src/librustc_span/lib.rs]: ❗️Ah! Thank you :-). Okay so I think I'm all caught up on this :-). Just to check that I've got it all:
1. First we make sure that when we instantiate a new `SourceFile`, it never has an `end_pos` greater than `u32::max_value()` (which, I assume (⚠️) means that the `SourceFile`'s total space is never more than `u32::max_value()`).
1. Then we can use `AtomicU32` to represent the used space of the `SourceFile`.
1. Then, when `SourceMap` is allocating space for `SourceFile`s, we ensure that the `size` we're allocating fits in 32bits and we can than leverage `AtomicU32` to update that value safely?

Comment (wesleywiser) [reply src/librustc_span/lib.rs]: Yes, exactly!

File: src/librustc_span/source_map.rs (hunk 1 above)
Comment (Zoxc) [reply src/librustc_span/source_map.rs]: Probably, but that fact isn't very local and would require a comment =P
