### PR TITLE
Fall back to the unoptimized implementation in read_binary_file if File::metadata lies

### LINKED ISSUE #115458: #115296 broke include_bytes! on paths with untrustworthy metadata
In https://github.com/rust-lang/rust/pull/115296 this diff is subtly broken:
```diff
-    fn read_binary_file(&self, path: &Path) -> io::Result<Vec<u8>> {
-        fs::read(path)
+    fn read_binary_file(&self, path: &Path) -> io::Result<Lrc<[u8]>> {
+        let mut file = fs::File::open(path)?;
+        let len = file.metadata()?.len();

+        let mut bytes = Lrc::new_uninit_slice(len as usize);
+        let mut buf = BorrowedBuf::from(Lrc::get_mut(&mut bytes).unwrap());
+        file.read_buf_exact(buf.unfilled())?;
+        // SAFETY: If the read_buf_exact call returns Ok(()), then we have
+        // read len bytes and initialized the buffer.
+        Ok(unsafe { bytes.assume_init() })
```
because it trusts that the size of the file returned by `File::metadata` is trustworthy, and it does not need to be. The correct implementation is to call `read` until EOF is reached.

This can be observed by trying to `include_bytes!("/dev/random")` (just be sure to use the resultant `const`).

### PR DESCRIPTION
**Pull request by saethlin**
Fixes https://github.com/rust-lang/rust/issues/115458

r? @jackh726 because you approved the previous PR

### CODE REVIEW

File: compiler/rustc_span/src/source_map.rs [hunk 1]
```diff
@@ -133,7 +133,29 @@ impl FileLoader for RealFileLoader {
         file.read_buf_exact(buf.unfilled())?;
```
Comment (programmerjake) [inline compiler/rustc_span/src/source_map.rs:133]: this is wrong because some files lie and have metadata size much larger than the actual file's size:
e.g. on linux `/sys/class/tty/console/dev` is like that:
full contents:
```
5:1
```
`stat` gives:
```
  File: /sys/class/tty/console/dev
  Size: 4096            Blocks: 0          IO Block: 4096   regular file
Device: 17h/23d Inode: 15051       Links: 1
Access: (0444/-r--r--r--)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2023-09-04 17:01:42.101801391 -0700
Modify: 2023-09-04 17:01:42.101801391 -0700
Change: 2023-09-04 17:01:42.101801391 -0700
 Birth: -
```

Comment (saethlin) [reply compiler/rustc_span/src/source_map.rs:133]:
```
error: couldn't read /sys/class/tty/console/dev: failed to fill buffer
 --> demo.rs:1:22
  |
1 | const BYTES: &[u8] = include_bytes!("/sys/class/tty/console/dev");
  |                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: this error originates in the macro `include_bytes` (in Nightly builds, run with -Z macro-backtrace for more info)

error: aborting due to previous error
```
I've been wondering if there was such a case! I'll adjust this in a bit...
(does this work here?)
@rustbot author

**Comment by petrochenkov** [comment]
This code was previously using `fs::read`.
Whatever changes you intend to do, they should probably be go to `fs::read` first, and then copypasted to the compiler with the `Lrc` adaptation.

**Comment by saethlin** [comment]
I do not think that is possible. The whole point of this change is to allow reading large files without peak memory use which is twice the size of the file. `fs::read` returns a `Vec<u8>` which cannot be turned into an `Lrc<[u8]>` without copying all the data because those types have different alignment requirements for their heap allocations.

**Comment by Mark-Simulacrum** [comment]
https://github.com/rust-lang/rust/blob/272cd384e8d1006240ecaed5077fe2990f576dbb/compiler/rustc_span/src/source_map.rs#L274

It looks like we're allocating a String (i.e., `Vec<u8>`) anyway in the only(?) code path using this function -- maybe it makes sense to make that reuse the allocation from fs::read and make the copy for `Lrc<[u8]>`? I suppose that doesn't help for files that aren't UTF-8 where the String isn't allocated, but seems like there might be something to this.

**Comment by jackh726** [comment]
I thought I had done a review on this. Maybe i was just looking into this. 

I don't really like that we are essentially just duplicating the logic in std for this. Is there a way to reuse the same code?

Or, at the very least, we should do our best to point to std as a "reference impl" for future maintenance.

**Comment by saethlin** [comment]
> I don't really like that we are essentially just duplicating the logic in std for this. Is there a way to reuse the same code?

The whole point of this is to read file bytes into an `Lrc<[u8]>` without at some time having two copies of the whole allocation in memory. There is no sound way to convert between a `Vec<u8>` and an `Lrc<[u8]>` without creating a second allocation, because the header for the `Lrc` needs the same alignment as `usize` so that it can store the reference counts, and allocations must be allocated and deallocated with the same alignment.

So unless the standard library produces an API to read a file into a `Rc<[u8]>` and `Arc<[u8]>` or to resize one of those types, I do not think we have a better option here. I tried to ask about this in Zulip: https://rust-lang.zulipchat.com/#narrow/stream/219381-t-libs/topic/Growing.20an.20Rc.3C.5BMaybeUninit.3Cu8.3E.5D.3E and the only responses were ways to avoid that whole issue.

**Comment by jackh726** [comment]
Is there a test we can add?

If so, can we add it. Otherwise, r=me.

**Comment by programmerjake** [comment]
for testing on linux, you could try reading: `/sys/class/tty/console/dev` (smaller than advertised) and `/proc/self/cmdline` (bigger than advertised). try reading using both `std::fs` and `read_binary_file` and check if the contents match. both of those are files that should be available on basically all linux systems and have stable contents for the duration of the test executable's lifetime. do note that `/sys/...` isn't available on android though...

**Comment by programmerjake** [comment]
turns out `/sys/devices/system/cpu/kernel_max` is available on android (and other linux) and has the same property of being smaller than advertised and having a stable value.

**Comment by saethlin** [comment]
I tried to make them reasonably resilient, but I can imagine the tests going wrong on the numerous platforms I don't understand.
@bors r=jackh726 rollup=iffy

File: compiler/rustc_span/src/source_map/tests.rs [hunk 2]
```diff
@@ -567,3 +567,30 @@ fn test_next_point() {
     assert_eq!(span.hi().0, 6);
     assert!(sm.span_to_snippet(span).is_err());
 }
+
+#[cfg(unix)]
```
Comment (programmerjake) [inline compiler/rustc_span/src/source_map/tests.rs:571]: this should be `#[cfg(linux)]` since those files aren't available on some other systems, e.g. I'd be surprised it they were on Apple or BSDs.
