### PR TITLE
misc coercion cleanups and handle safety correctly

### LINKED ISSUE #233: `FulfillmentErrorCode::Project` ICE for opaques
- tests/ui/coercion/issue-88097.rs
```rust
fn peculiar() -> impl Fn(u8) -> u8 {
    return |x| x + 1
}
```

this 1) should compile 2) not ICE :3

```
thread 'rustc' panicked at /home/lcnr/rust/compiler/rustc_type_ir/src/predicate.rs:680:9:
expected a projection
stack backtrace:
   0: __rustc::rust_begin_unwind
             at /rustc/788da80fcfcef3f34c90def5baa32813e39a1a41/library/std/src/panicking.rs:697:5
   1: core::panicking::panic_fmt
             at /rustc/788da80fcfcef3f34c90def5baa32813e39a1a41/library/core/src/panicking.rs:75:14
   2: trait_def_id<rustc_middle::ty::context::TyCtxt>
             at /home/lcnr/rust/compiler/rustc_type_ir/src/predicate.rs:680:9
   3: maybe_detailed_projection_msg
             at /home/lcnr/rust/compiler/rustc_trait_selection/src/error_reporting/traits/fulfillment_errors.rs:1660:44
   4: {closure#1}
             at /home/lcnr/rust/compiler/rustc_trait_selection/src/error_reporting/traits/fulfillment_errors.rs:1537:26
   5: and_then<(rustc_type_ir::predicate::AliasTerm<rustc_middle::ty::context::TyCtxt>, rustc_middle::ty::Term, rustc_middle::ty::Term), (alloc::string::String, rustc_span::span_encoding::Span, core::option::Option<rustc_span::span_encoding::Span>), rustc_trait_selection::error_reporting::traits::fulfillment_errors::{impl#2}::report_projection_error::{closure#0}::{closure_env#1}>
             at /rustc/788da80fcfcef3f34c90def5baa32813e39a1a41/library/core/src/option.rs:1537:24
   6: {closure#0}
             at /home/lcnr/rust/compiler/rustc_trait_selection/src/error_reporting/traits/fulfillment_errors.rs:1536:18
   7: probe<rustc_span::ErrorGuaranteed, rustc_trait_selection::error_reporting::traits::fulfillment_errors::{impl#2}::report_projection_error::{closure_env#0}>
             at /home/lcnr/rust/compiler/rustc_infer/src/infer/snapshot/mod.rs:106:17
   8: report_projection_error
             at /home/lcnr/rust/compiler/rustc_trait_selection/src/error_reporting/traits/fulfillment_errors.rs:1443:14
   9: report_fulfillment_error
             at /home/lcnr/rust/compiler/rustc_trait_selection/src/error_reporting/traits/mod.rs:277:22
  10: report_fulfillment_errors
             at /home/lcnr/rust/compiler/rustc_trait_selection/src/error_reporting/traits/mod.rs:228:37
  11: select_obligations_where_possible<rustc_hir_typeck::fallback::{impl#0}::type_inference_fallback::{closure_env#0}>
             at /home/lcnr/rust/compiler/rustc_hir_typeck/src/fn_ctxt/_impl.rs:667:29
  12: type_inference_fallback
             at /home/lcnr/rust/compiler/rustc_hir_typeck/src/fallback.rs:47:14
```

### LINKED ISSUE #132765: [ICE]: index out of bounds
### Code

```rust
trait LendingIterator {
    type Item<'q>: 'a;
    fn for_each(mut self, mut f: Box<dyn FnMut(Self::Item<'_>) + 'static>) {}
}
struct Query<'q> {}
impl<'static> Query<'q> {
    pub fn new() -> Self {}
}
fn data() {
    LendingIterator::for_each(Box::new(&data), Box::new);
}
pub fn main() {}

```

### Affected release channels

- [ ] Previous Stable
- [ ] Current Stable
- [ ] Current Beta
- [x] Current Nightly

### Rust Version

rustc 1.84.0-nightly (b91a3a056 2024-11-07)
binary: rustc
commit-hash: b91a3a05609a46f73d23e0995ae7ebb4a4f429a5
commit-date: 2024-11-07
host: x86_64-unknown-linux-gnu
release: 1.84.0-nightly
LLVM version: 19.1.3

### Current error output

error[E0261]: use of undeclared lifetime name `'a`
 --> mutant.rs:2:20
  |
2 |     type Item<'q>: 'a;
  |                    ^^ undeclared lifetime
  |
help: consider introducing lifetime `'a` here
  |
2 |     type Item<'a, 'q>: 'a;
  |               +++
help: consider introducing lifetime `'a` here
  |
1 | trait LendingIterator<'a> {
  |                      ++++

error[E0262]: invalid lifetime parameter name: `'static`
 --> mutant.rs:6:6
  |
6 | impl<'static> Query<'q> {
  |      ^^^^^^^ 'static is a reserved lifetime name

error[E0261]: use of undeclared lifetime name `'q`
 --> mutant.rs:6:21
  |
6 | impl<'static> Query<'q> {
  |      -              ^^ undeclared lifetime
  |      |
  |      help: consider introducing lifetime `'q` here: `'q,`

error[E0392]: lifetime parameter `'q` is never used
 --> mutant.rs:5:14
  |
5 | struct Query<'q> {}
  |              ^^ unused lifetime parameter
  |
  = help: consider removing `'q`, referring to it in a field, or using a marker such as `PhantomData`

error[E0277]: the size for values of type `Self` cannot be known at compilation time
 --> mutant.rs:3:21
  |
3 |     fn for_each(mut self, mut f: Box<dyn FnMut(Self::Item<'_>) + 'static>) {}
  |                     ^^^^ doesn't have a size known at compile-time
  |
  = help: unsized fn params are gated as an unstable feature
help: consider further restricting `Self`
  |
3 |     fn for_each(mut self, mut f: Box<dyn FnMut(Self::Item<'_>) + 'static>) where Self: Sized {}
  |                                                                            +++++++++++++++++
help: function arguments must have a statically known size, borrowed types always have a known size
  |
3 |     fn for_each(mut &self, mut f: Box<dyn FnMut(Self::Item<'_>) + 'static>) {}
  |                     +

error[E0277]: the trait bound `Box<&fn() {data}>: LendingIterator` is not satisfied
  --> mutant.rs:10:31
   |
10 |     LendingIterator::for_each(Box::new(&data), Box::new);
   |     ------------------------- ^^^^^^^^^^^^^^^ the trait `LendingIterator` is not implemented for `Box<&fn() {data}>`
   |     |
   |     required by a bound introduced by this call
   |
help: this trait has no implementations, consider adding one
  --> mutant.rs:1:1
   |
1  | trait LendingIterator {
   | ^^^^^^^^^^^^^^^^^^^^^

thread 'rustc' panicked at /rust/deps/ena-0.14.3/src/snapshot_vec.rs:199:10:
index out of bounds: the len is 7 but the index is 7
stack backtrace:
   0:     0x7f719d25517a - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::hfadad24fb33e3d1a
   1:     0x7f719da040a6 - core::fmt::write::h42d25fbda60cd99f
   2:     0x7f719edc3351 - std::io::Write::write_fmt::hc2819193e80b365e
   3:     0x7f719d254fd2 - std::sys::backtrace::BacktraceLock::print::h9450230402d77664
   4:     0x7f719d2574d6 - std::panicking::default_hook::{{closure}}::h739047d4d787c596
   5:     0x7f719d257320 - std::panicking::default_hook::h203d1229480f37a5
   6:     0x7f719c2d2269 - std[56fe22ad9ea837fd]::panicking::update_hook::<alloc[b5641001d343df5f]::boxed::Box<rustc_driver_impl[945e9afaf49c7d35]::install_ice_hook::{closure#0}>>::{closure#0}
   7:     0x7f719d257be8 - std::panicking::rust_panic_with_hook::h657fdcc17f7e2546
   8:     0x7f719d2579ba - std::panicking::begin_panic_handler::{{closure}}::h6c1a7592f2611ed5
   9:     0x7f719d255629 - std::sys::backtrace::__rust_end_short_backtrace::h3e1efd1ff0b15465
  10:     0x7f719d25767c - rust_begin_unwind
  11:     0x7f7199ccd320 - core::panicking::panic_fmt::h41647251c9f15c53
  12:     0x7f719b9f0b1b - core::panicking::panic_bounds_check::h66515744fb563c4b
  13:     0x7f719dacc1f6 - <rustc_middle[f0eb6ba890d0a9bb]::ty::Ty as rustc_type_ir[8408d34320f8a6fb]::fold::TypeSuperFoldable<rustc_middle[f0eb6ba890d0a9bb]::ty::context::TyCtxt>>::try_super_fold_with::<rustc_infer[21ddc8b2a5f19898]::infer::resolve::OpportunisticVarResolver>
  14:     0x7f719dac6323 - <&rustc_middle[f0eb6ba890d0a9bb]::ty::list::RawList<(), rustc_middle[f0eb6ba890d0a9bb]::ty::generic_args::GenericArg> as rustc_type_ir[8408d34320f8a6fb]::fold::TypeFoldable<rustc_middle[f0eb6ba890d0a9bb]::ty::context::TyCtxt>>::try_fold_with::<rustc_infer[21ddc8b2a5f19898]::infer::resolve::OpportunisticVarResolver>
  15:     0x7f719dac9e17 - <rustc_middle[f0eb6ba890d0a9bb]::ty::Ty as rustc_type_ir[8408d34320f8a6fb]::fold::TypeSuperFoldable<rustc_middle[f0eb6ba890d0a9bb]::ty::context::TyCtxt>>::try_super_fold_with::<rustc_infer[21ddc8b2a5f19898]::infer::resolve::OpportunisticVarResolver>
  16:     0x7f719dac8554 - <rustc_middle[f0eb6ba890d0a9bb]::ty::Ty as rustc_type_ir[8408d34320f8a6fb]::fold::TypeSuperFoldable<rustc_middle[f0eb6ba890d0a9bb]::ty::context::TyCtxt>>::try_super_fold_with::<rustc_infer[21ddc8b2a5f19898]::infer::resolve::OpportunisticVarResolver>
  17:     0x7f719d01a962 - <rustc_infer[21ddc8b2a5f19898]::infer::resolve::OpportunisticVarResolver as rustc_type_ir[8408d34320f8a6fb]::fold::FallibleTypeFolder<rustc_middle[f0eb6ba890d0a9bb]::ty::context::TyCtxt>>::try_fold_ty
  18:     0x7f719d087548 - <rustc_trait_selection[c0f45c4e16f8dab6]::error_reporting::TypeErrCtxt>::same_type_modulo_infer::<rustc_middle[f0eb6ba890d0a9bb]::ty::Ty>
  19:     0x7f719d0fcaba - <rustc_trait_selection[c0f45c4e16f8dab6]::error_reporting::TypeErrCtxt>::note_type_err
  20:     0x7f719d084350 - <rustc_trait_selection[c0f45c4e16f8dab6]::error_reporting::TypeErrCtxt>::report_and_explain_type_error
  21:     0x7f719c62446e - <rustc_hir_typeck[9dbf9add14d719fd]::fn_ctxt::FnCtxt>::report_arg_errors
  22:     0x7f719a103be3 - <rustc_hir_typeck[9dbf9add14d719fd]::fn_ctxt::FnCtxt>::confirm_builtin_call
  23:     0x7f719e6fa2bf - <rustc_hir_typeck[9dbf9add14d719fd]::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
  24:     0x7f719e6f4736 - <rustc_hir_typeck[9dbf9add14d719fd]::fn_ctxt::FnCtxt>::check_block_with_expected
  25:     0x7f719e6fabb4 - <rustc_hir_typeck[9dbf9add14d719fd]::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
  26:     0x7f719dc4df5b - rustc_hir_typeck[9dbf9add14d719fd]::check::check_fn
  27:     0x7f719dc43bac - rustc_hir_typeck[9dbf9add14d719fd]::typeck
  28:     0x7f719dc43553 - rustc_query_impl[1357963d8dd30e8b]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[1357963d8dd30e8b]::query_impl::typeck::dynamic_query::{closure#2}::{closure#0}, rustc_middle[f0eb6ba890d0a9bb]::query::erase::Erased<[u8; 8usize]>>
  29:     0x7f719e123681 - rustc_query_system[887bb79932b1d8c1]::query::plumbing::try_execute_query::<rustc_query_impl[1357963d8dd30e8b]::DynamicConfig<rustc_query_system[887bb79932b1d8c1]::query::caches::VecCache<rustc_span[db86d96c2ae2e3a4]::def_id::LocalDefId, rustc_middle[f0eb6ba890d0a9bb]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[1357963d8dd30e8b]::plumbing::QueryCtxt, false>
  30:     0x7f719e121b4d - rustc_query_impl[1357963d8dd30e8b]::query_impl::typeck::get_query_non_incr::__rust_end_short_backtrace
  31:     0x7f719e1217c7 - <rustc_middle[f0eb6ba890d0a9bb]::hir::map::Map>::par_body_owners::<rustc_hir_analysis[af6e6fecb0b5810e]::check_crate::{closure#4}>::{closure#0}
  32:     0x7f719e11f799 - rustc_hir_analysis[af6e6fecb0b5810e]::check_crate
  33:     0x7f719e268aca - rustc_interface[5fea8bf9cd0b71b5]::passes::run_required_analyses
  34:     0x7f719e80861e - rustc_interface[5fea8bf9cd0b71b5]::passes::analysis
  35:     0x7f719e8085ef - rustc_query_impl[1357963d8dd30e8b]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[1357963d8dd30e8b]::query_impl::analysis::dynamic_query::{closure#2}::{closure#0}, rustc_middle[f0eb6ba890d0a9bb]::query::erase::Erased<[u8; 1usize]>>
  36:     0x7f719e992cee - rustc_query_system[887bb79932b1d8c1]::query::plumbing::try_execute_query::<rustc_query_impl[1357963d8dd30e8b]::DynamicConfig<rustc_query_system[887bb79932b1d8c1]::query::caches::SingleCache<rustc_middle[f0eb6ba890d0a9bb]::query::erase::Erased<[u8; 1usize]>>, false, false, false>, rustc_query_impl[1357963d8dd30e8b]::plumbing::QueryCtxt, false>
  37:     0x7f719e9929ce - rustc_query_impl[1357963d8dd30e8b]::query_impl::analysis::get_query_non_incr::__rust_end_short_backtrace
  38:     0x7f719e88707a - rustc_interface[5fea8bf9cd0b71b5]::interface::run_compiler::<core[5ba82ee3405aa490]::result::Result<(), rustc_span[db86d96c2ae2e3a4]::ErrorGuaranteed>, rustc_driver_impl[945e9afaf49c7d35]::run_compiler::{closure#0}>::{closure#1}
  39:     0x7f719e8cd5d0 - std[56fe22ad9ea837fd]::sys::backtrace::__rust_begin_short_backtrace::<rustc_interface[5fea8bf9cd0b71b5]::util::run_in_thread_with_globals<rustc_interface[5fea8bf9cd0b71b5]::util::run_in_thread_pool_with_globals<rustc_interface[5fea8bf9cd0b71b5]::interface::run_compiler<core[5ba82ee3405aa490]::result::Result<(), rustc_span[db86d96c2ae2e3a4]::ErrorGuaranteed>, rustc_driver_impl[945e9afaf49c7d35]::run_compiler::{closure#0}>::{closure#1}, core[5ba82ee3405aa490]::result::Result<(), rustc_span[db86d96c2ae2e3a4]::ErrorGuaranteed>>::{closure#0}, core[5ba82ee3405aa490]::result::Result<(), rustc_span[db86d96c2ae2e3a4]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[5ba82ee3405aa490]::result::Result<(), rustc_span[db86d96c2ae2e3a4]::ErrorGuaranteed>>
  40:     0x7f719e8cd9eb - <<std[56fe22ad9ea837fd]::thread::Builder>::spawn_unchecked_<rustc_interface[5fea8bf9cd0b71b5]::util::run_in_thread_with_globals<rustc_interface[5fea8bf9cd0b71b5]::util::run_in_thread_pool_with_globals<rustc_interface[5fea8bf9cd0b71b5]::interface::run_compiler<core[5ba82ee3405aa490]::result::Result<(), rustc_span[db86d96c2ae2e3a4]::ErrorGuaranteed>, rustc_driver_impl[945e9afaf49c7d35]::run_compiler::{closure#0}>::{closure#1}, core[5ba82ee3405aa490]::result::Result<(), rustc_span[db86d96c2ae2e3a4]::ErrorGuaranteed>>::{closure#0}, core[5ba82ee3405aa490]::result::Result<(), rustc_span[db86d96c2ae2e3a4]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[5ba82ee3405aa490]::result::Result<(), rustc_span[db86d96c2ae2e3a4]::ErrorGuaranteed>>::{closure#1} as core[5ba82ee3405aa490]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  41:     0x7f719e8ce4b9 - std::sys::pal::unix::thread::Thread::new::thread_start::hb3d6392adeea417c
  42:     0x7f7198a6bac3 - start_thread
                               at ./nptl/pthread_create.c:442:8
  43:     0x7f7198afd850 - __GI___clone3
                               at ./misc/../sysdeps/unix/sysv/linux/x86_64/clone3.S:81
  44:                0x0 - <unknown>

error: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: please make sure that you have updated to the latest nightly

note: please attach the file at `/data/xieym/workspace/perses-private/perses-fuzzer/nightly-kitten-noice/check_again/ice/crash_20241107_061430_000f/rustc-ice-2024-11-08T08_59_50-2322567.txt` to your bug report

note: compiler flags: --crate-type staticlib -C link-dead-code -C debuginfo=2 -C opt-level=3 -Z mir-opt-level=3

query stack during panic:
#0 [typeck] type-checking `data`
#1 [analysis] running analysis passes on this crate
end of query stack
error: aborting due to 6 previous errors

Some errors have detailed explanations: E0261, E0262, E0277, E0392.
For more information about an error, try `rustc --explain E0261`.

### Backtrace

   |
1  | trait LendingIterator {
   | ^^^^^^^^^^^^^^^^^^^^^

thread 'rustc' panicked at /rust/deps/ena-0.14.3/src/snapshot_vec.rs:199:10:
index out of bounds: the len is 7 but the index is 7
stack backtrace:
   0:     0x7f719d25517a - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::hfadad24fb33e3d1a
   1:     0x7f719da040a6 - core::fmt::write::h42d25fbda60cd99f
   2:     0x7f719edc3351 - std::io::Write::write_fmt::hc2819193e80b365e
   3:     0x7f719d254fd2 - std::sys::backtrace::BacktraceLock::print::h9450230402d77664
   4:     0x7f719d2574d6 - std::panicking::default_hook::{{closure}}::h739047d4d787c596
   5:     0x7f719d257320 - std::panicking::default_hook::h203d1229480f37a5
   6:     0x7f719c2d2269 - std[56fe22ad9ea837fd]::panicking::update_hook::<alloc[b5641001d343df5f]::boxed::Box<rustc_driver_impl[945e9afaf49c7d35]::install_ice_hook::{closure#0}>>::{clos
   7:     0x7f719d257be8 - std::panicking::rust_panic_with_hook::h657fdcc17f7e2546
   8:     0x7f719d2579ba - std::panicking::begin_panic_handler::{{closure}}::h6c1a7592f2611ed5
   9:     0x7f719d255629 - std::sys::backtrace::__rust_end_short_backtrace::h3e1efd1ff0b15465
  10:     0x7f719d25767c - rust_begin_unwind
  11:     0x7f7199ccd320 - core::panicking::panic_fmt::h41647251c9f15c53
  12:     0x7f719b9f0b1b - core::panicking::panic_bounds_check::h66515744fb563c4b
  13:     0x7f719dacc1f6 - <rustc_middle[f0eb6ba890d0a9bb]::ty::Ty as rustc_type_ir[8408d34320f8a6fb]::fold::TypeSuperFoldable<rustc_middle[f0eb6ba890d0a9bb]::ty::context::TyCtxt>>::try_
  14:     0x7f719dac6323 - <&rustc_middle[f0eb6ba890d0a9bb]::ty::list::RawList<(), rustc_middle[f0eb6ba890d0a9bb]::ty::generic_args::GenericArg> as rustc_type_ir[8408d34320f8a6fb]::fold:
  15:     0x7f719dac9e17 - <rustc_middle[f0eb6ba890d0a9bb]::ty::Ty as rustc_type_ir[8408d34320f8a6fb]::fold::TypeSuperFoldable<rustc_middle[f0eb6ba890d0a9bb]::ty::context::TyCtxt>>::try_
  16:     0x7f719dac8554 - <rustc_middle[f0eb6ba890d0a9bb]::ty::Ty as rustc_type_ir[8408d34320f8a6fb]::fold::TypeSuperFoldable<rustc_middle[f0eb6ba890d0a9bb]::ty::context::TyCtxt>>::try_
  17:     0x7f719d01a962 - <rustc_infer[21ddc8b2a5f19898]::infer::resolve::OpportunisticVarResolver as rustc_type_ir[8408d34320f8a6fb]::fold::FallibleTypeFolder<rustc_middle[f0eb6ba890d0
  18:     0x7f719d087548 - <rustc_trait_selection[c0f45c4e16f8dab6]::error_reporting::TypeErrCtxt>::same_type_modulo_infer::<rustc_middle[f0eb6ba890d0a9bb]::ty::Ty>
  19:     0x7f719d0fcaba - <rustc_trait_selection[c0f45c4e16f8dab6]::error_reporting::TypeErrCtxt>::note_type_err
  20:     0x7f719d084350 - <rustc_trait_selection[c0f45c4e16f8dab6]::error_reporting::TypeErrCtxt>::report_and_explain_type_error
  21:     0x7f719c62446e - <rustc_hir_typeck[9dbf9add14d719fd]::fn_ctxt::FnCtxt>::report_arg_errors
  22:     0x7f719a103be3 - <rustc_hir_typeck[9dbf9add14d719fd]::fn_ctxt::FnCtxt>::confirm_builtin_call
  23:     0x7f719e6fa2bf - <rustc_hir_typeck[9dbf9add14d719fd]::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
  24:     0x7f719e6f4736 - <rustc_hir_typeck[9dbf9add14d719fd]::fn_ctxt::FnCtxt>::check_block_with_expected
  25:     0x7f719e6fabb4 - <rustc_hir_typeck[9dbf9add14d719fd]::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
  26:     0x7f719dc4df5b - rustc_hir_typeck[9dbf9add14d719fd]::check::check_fn
  27:     0x7f719dc43bac - rustc_hir_typeck[9dbf9add14d719fd]::typeck
  28:     0x7f719dc43553 - rustc_query_impl[1357963d8dd30e8b]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[1357963d8dd30e8b]::query_impl::typeck::dynamic_query::{closure#2}::{closure#0}, rustc_middle[f0eb6ba890d0a9bb]::query::erase::Erased<[u8; 8usize]>>
  29:     0x7f719e123681 - rustc_query_system[887bb79932b1d8c1]::query::plumbing::try_execute_query::<rustc_query_impl[1357963d8dd30e8b]::DynamicConfig<rustc_query_system[887bb79932b1d8c1]::query::caches::VecCache<rustc_span[db86d96c2ae2e3a4]::def_id::LocalDefId, rustc_middle[f0eb6ba890d0a9bb]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[1357963d8dd30e8b]::plumbing::QueryCtxt, false>
  30:     0x7f719e121b4d - rustc_query_impl[1357963d8dd30e8b]::query_impl::typeck::get_query_non_incr::__rust_end_short_backtrace
  31:     0x7f719e1217c7 - <rustc_middle[f0eb6ba890d0a9bb]::hir::map::Map>::par_body_owners::<rustc_hir_analysis[af6e6fecb0b5810e]::check_crate::{closure#4}>::{closure#0}
  32:     0x7f719e11f799 - rustc_hir_analysis[af6e6fecb0b5810e]::check_crate
  33:     0x7f719e268aca - rustc_interface[5fea8bf9cd0b71b5]::passes::run_required_analyses
  34:     0x7f719e80861e - rustc_interface[5fea8bf9cd0b71b5]::passes::analysis
  35:     0x7f719e8085ef - rustc_query_impl[1357963d8dd30e8b]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[1357963d8dd30e8b]::query_impl::analysis::dynamic_query::{closure#2}::{closure#0}, rustc_middle[f0eb6ba890d0a9bb]::query::erase::Erased<[u8; 1usize]>>
  36:     0x7f719e992cee - rustc_query_system[887bb79932b1d8c1]::query::plumbing::try_execute_query::<rustc_query_impl[1357963d8dd30e8b]::DynamicConfig<rustc_query_system[887bb79932b1d8c1]::query::caches::SingleCache<rustc_middle[f0eb6ba890d0a9bb]::query::erase::Erased<[u8; 1usize]>>, false, false, false>, rustc_query_impl[1357963d8dd30e8b]::plumbing::QueryCtxt, false>
  37:     0x7f719e9929ce - rustc_query_impl[1357963d8dd30e8b]::query_impl::analysis::get_query_non_incr::__rust_end_short_backtrace
  38:     0x7f719e88707a - rustc_interface[5fea8bf9cd0b71b5]::interface::run_compiler::<core[5ba82ee3405aa490]::result::Result<(), rustc_span[db86d96c2ae2e3a4]::ErrorGuaranteed>, rustc_driver_impl[945e9afaf49c7d35]::run_compiler::{closure#0}>::{closure#1}
  39:     0x7f719e8cd5d0 - std[56fe22ad9ea837fd]::sys::backtrace::__rust_begin_short_backtrace::<rustc_interface[5fea8bf9cd0b71b5]::util::run_in_thread_with_globals<rustc_interface[5fea8bf9cd0b71b5]::util::run_in_thread_pool_with_globals<rustc_interface[5fea8bf9cd0b71b5]::interface::run_compiler<core[5ba82ee3405aa490]::result::Result<(), rustc_span[db86d96c2ae2e3a4]::ErrorGuaranteed>, rustc_driver_impl[945e9afaf49c7d35]::run_compiler::{closure#0}>::{closure#1}, core[5ba82ee3405aa490]::result::Result<(), rustc_span[db86d96c2ae2e3a4]::ErrorGuaranteed>>::{closure#0}, core[5ba82ee3405aa490]::result::Result<(), rustc_span[db86d96c2ae2e3a4]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[5ba82ee3405aa490]::result::Result<(), rustc_span[db86d96c2ae2e3a4]::ErrorGuaranteed>>
  40:     0x7f719e8cd9eb - <<std[56fe22ad9ea837fd]::thread::Builder>::spawn_unchecked_<rustc_interface[5fea8bf9cd0b71b5]::util::run_in_thread_with_globals<rustc_interface[5fea8bf9cd0b71b5]::util::run_in_thread_pool_with_globals<rustc_interface[5fea8bf9cd0b71b5]::interface::run_compiler<core[5ba82ee3405aa490]::result::Result<(), rustc_span[db86d96c2ae2e3a4]::ErrorGuaranteed>, rustc_driver_impl[945e9afaf49c7d35]::run_compiler::{closure#0}>::{closure#1}, core[5ba82ee3405aa490]::result::Result<(), rustc_span[db86d96c2ae2e3a4]::ErrorGuaranteed>>::{closure#0}, core[5ba82ee3405aa490]::result::Result<(), rustc_span[db86d96c2ae2e3a4]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[5ba82ee3405aa490]::result::Result<(), rustc_span[db86d96c2ae2e3a4]::ErrorGuaranteed>>::{closure#1} as core[5ba82ee3405aa490]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  41:     0x7f719e8ce4b9 - std::sys::pal::unix::thread::Thread::new::thread_start::hb3d6392adeea417c
  42:     0x7f7198a6bac3 - start_thread
                               at ./nptl/pthread_create.c:442:8
  43:     0x7f7198afd850 - __GI___clone3
                               at ./misc/../sysdeps/unix/sysv/linux/x86_64/clone3.S:81
  44:                0x0 - <unknown>

### Anything else?

This issue is similar to https://github.com/rust-lang/rust/issues/122098; however, https://github.com/rust-lang/rust/issues/122098 does not report an ICE on the current nightly version. The difference is the addition of a `main` function.

### PR DESCRIPTION
**Pull request by BoxyUwU**
r? lcnr

### "remove normalize call"

Fixes rust-lang/rust#132765

If the normalization fails we would sometimes get a `TypeError` containing inference variables created inside of the probe used by coercion. These would then get leaked out causing ICEs in diagnostics logic

### "leak check and lub for closure<->closure coerce-lubs of same defids"

Fixes https://github.com/rust-lang/trait-system-refactor-initiative/issues/233 
```rust
fn peculiar() -> impl Fn(u8) -> u8 {
    return |x| x + 1
}
```
the `|x| x + 1` expr has a type of `Closure(?31t)` which we wind up inferring the RPIT to. The `CoerceMany` `ret_coercion` for the whole `peculiar` typeck has an expected type of `RPIT` (unnormalized). When we type check the `return |x| x + 1` expr we go from the never type to `Closure(?31t)` which then participates in the `ret_coercion` giving us a `coerce-lub(RPIT, Closure(?31t))`. 

Normalizing `RPIT` gives us some `Closure(?50t)` where `?31t` and `?50t` have been unified with `?31t` as the root var. `resolve_vars_if_possible` doesn't resolve infer vars to their roots so these wind up with different structural identities so the fast path doesn't apply and we fall back to coercing to a `fn` ptr. cc rust-lang/rust#147193 which also fixes this

New solver probably just gets more inference variables here because canonicalization + generally different approach to normalization of opaques. Idk :3

### FCP worthy stuffy

there are some other FCP worthy things but they're in my FCP comment which also contains some analysis of the breaking nature of the previously listed changes in this PR: https://github.com/rust-lang/rust/pull/148602#issuecomment-3503497467

### CODE REVIEW

File: compiler/rustc_middle/src/ty/adjustment.rs [hunk 1]
```diff
@@ -9,8 +9,9 @@ use crate::ty::{Ty, TyCtxt};
 
 #[derive(Clone, Copy, Debug, PartialEq, Eq, TyEncodable, TyDecodable, Hash, HashStable)]
 pub enum PointerCoercion {
-    /// Go from a fn-item type to a fn-pointer type.
-    ReifyFnPointer,
+    /// Go from a fn-item type to a fn pointer or an unsafe fn pointer.
+    /// It cannot convert an unsafe fn-item to a safe fn pointer.
+    ReifyFnPointer(hir::Safety),
```
Comment (BoxyUwU) [inline compiler/rustc_middle/src/ty/adjustment.rs:14]: I've gone and allowed `ReifyFnPointer` coercions to coerce safe fndefs to unsafe fn pointers directly instead of needing to compose two coercions. This made handling safety in `coerce-lub` simpler/nicer.

File: compiler/rustc_hir_typeck/src/coercion.rs [hunk 2]
```diff
@@ -223,21 +223,20 @@ impl<'f, 'tcx> Coerce<'f, 'tcx> {
...
+        // Examine the target type and consider type-specific coercions, such
+        // as auto-borrowing, coercing pointer mutability, or pin-ergonomics.
         match *b.kind() {
             ty::RawPtr(_, b_mutbl) => {
-                return self.coerce_raw_ptr(a, b, b_mutbl);
+                return self.coerce_to_raw_ptr(a, b, b_mutbl);
             }
             ty::Ref(r_b, _, mutbl_b) => {
-                return self.coerce_borrowed_pointer(a, b, r_b, mutbl_b);
+                return self.coerce_to_ref(a, b, mutbl_b, r_b);
```
Comment (lcnr) [inline compiler/rustc_hir_typeck/src/coercion.rs]: why switch args? :thinking: feels like the previous order matched the order used in the `ty` itself?

File: compiler/rustc_hir_typeck/src/coercion.rs [hunk 3]
```diff
@@ -281,22 +280,21 @@ impl<'f, 'tcx> Coerce<'f, 'tcx> {
...
+                    ty::Binder::dummy(ty::PredicateKind::Coerce(ty::CoercePredicate { a, b })),
+                ));
+            };
+
+            let target_ty = self.use_lub.then(|| self.next_ty_var(self.cause.span)).unwrap_or(b);
+
+            push_coerce_obligation(a, target_ty);
+            if self.use_lub {
+                push_coerce_obligation(b, target_ty);
             }
```
Comment (lcnr) [inline compiler/rustc_hir_typeck/src/coercion.rs]:
```rust
let target_ty = if self.use_lub {
    // When computing the lub, we create a new target
    // and coerce both `a` and `b` to it.
    let target_ty = self.next_ty_var(self.cause.span);
    push_coerce_obligation(a, target_ty);
    push_coerce_obligation(b, target_ty);
    target_ty
} else {
    // When subtyping, we don't need to create a new target
    // as we only coerce `a` to `b`.
    push_coerce_obligation(a, b);
    b
};
```
your code felt a bit unclear to me initially

File: compiler/rustc_hir_typeck/src/coercion.rs [hunk 4]
```diff
@@ -488,25 +430,25 @@ impl<'f, 'tcx> Coerce<'f, 'tcx> {
...
         obligations.extend(autoderef.into_obligations());
 
-        // Now apply the autoref. We have to extract the region out of
-        // the final ref type we got.
-        let ty::Ref(..) = ty.kind() else {
-            span_bug!(span, "expected a ref type, got {:?}", ty);
+        // Now apply the autoref
+        let ty::Ref(..) = coerced_a.kind() else {
+            span_bug!(self.cause.span, "expected a ref type, got {:?}", coerced_a);
         };
```
Comment (lcnr) [inline compiler/rustc_hir_typeck/src/coercion.rs]: convert this to an `assert_matches!`/`assert!(matches!(..))`?

File: compiler/rustc_hir_typeck/src/coercion.rs [hunk 5]
```diff
@@ -890,9 +887,10 @@ impl<'f, 'tcx> Coerce<'f, 'tcx> {
                     }
                 }
 
-                let InferOk { value: a_sig, obligations: o1 } =
+                // FIXME: we shouldn't be normalizing here as coercion is inside of
+                // a probe. This can probably cause ICEs.
```
Comment (lcnr) [inline compiler/rustc_hir_typeck/src/coercion.rs]: I don't understand that FIXME. Normalizing inside of a probe is totally fine as long as we don't leak the infer vars. This happens for errors of `commit_if_ok` but I don't think *not normalizing* is the solution here.

More specifically, we *have* to normalize here as the fn-sig is the unnnormalized one from a function definition

File: tests/ui/coercion/hr_alias_normalization_leaking_vars.rs [hunk 6]
```diff
@@ -0,0 +1,36 @@
...
+//
+// The first coercion infers `?0=()`. Previously when handling
+// the second coercion we wound *re-normalize* the alias, which
+// now that `?0` has been inferred allowed us to determine this
+// alias is not wellformed and normalize it to some infer var `?1`.
+//
+// We would then see that `FnDef(f)` can't be coerced to `Box<fn(?1)>`
+// and return a `TypeError` referencing this new variable `?1`. This
+// then caused ICEs as diagnostics would encounter inferences variables
+// from the result of normalization inside of the probe used be coercion.
```
Comment (lcnr) [inline tests/ui/coercion/hr_alias_normalization_leaking_vars.rs:23]: add comment that regression test for #132765?

File: compiler/rustc_hir_typeck/src/coercion.rs [hunk 7]
```diff
@@ -113,6 +113,11 @@ fn success<'tcx>(
     Ok(InferOk { value: (adj, target), obligations })
 }
 
+enum LeakCheck {
+    Yes,
+    Default,
```
Comment (lcnr) [inline compiler/rustc_hir_typeck/src/coercion.rs]: `Default` seems weird. Maybe
```rust
/// Whether to explicitly leak check in `Coerce::unify_raw`.
///
/// FIMXE: We may want to change type relations to always leak-check
/// after exiting a binder, at which point we will always do so and
/// no longer need to handle this explicitly
enum ExplicitLeakCheck {
   Yes,
   No,
}
```

File: compiler/rustc_hir_typeck/src/coercion.rs [hunk 8]
```diff
@@ -1193,34 +1194,51 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
...
+                    })
+                };
+
+                match (prev_ty.kind(), new_ty.kind()) {
+                    // Don't coerce pairs of fndefs or pairs of closures to fn ptrs
+                    // if they can just be lubbed.
+                    //
+                    // See #88097 or `lub_closures_before_fnptr_coercion.rs` for where
+                    // we would erroneously coerce closures to fnptrs when attempting to
+                    // coerce a closure to itself.
```
Comment (lcnr) [inline compiler/rustc_hir_typeck/src/coercion.rs]: maybe move this comment above `let lubbed_tys`. Right now this is kinda confusing. It not immediately clear why we have a closure without arguments here.

Or alternatively, maybe explicitly pass in `prev_ty` and `new_ty` to it :thinking:

File: tests/ui/coercion/leak_check_fndef_lub.rs [hunk 9]
```diff
@@ -0,0 +1,32 @@
...
+fn fndef_lub_leak_check() {
+    macro_rules! lub {
+        ($lhs:expr, $rhs:expr) => {
+            if true { $lhs } else { $rhs }
+        };
+    }
+
+    // These don't currently lub but could in theory one day.
+    // If that happens this test should be adjusted to use
+    // fn ptrs that can't be lub'd.
```
Comment (lcnr) [inline tests/ui/coercion/leak_check_fndef_lub.rs]: hmm what? :thinking:

- "fn ptrs that can't be lub'd" u mean fn defs?
- why can they in theory be lubbed at some point? their arg is invariant so there's no way to lub them, is there?

File: tests/ui/coercion/lub_closures_before_fnptr_coercion.rs [hunk 10]
```diff
@@ -0,0 +1,70 @@
...
+
+// Test that when lubbing two equal closure tys with different
+// structural identities (i.e. `PartialEq::eq` on `ty::Ty` would be false)
+// we don't coerce-lub to a fnptr.
+//
+// Most of this test is involved jank to be able to leak the hidden type
+// of an opaque with a hidden type of `Closure<C1, C2>`. This then allows
+// us to substitute `C1` and `C2` for arbitrary types in the parent scope.
+//
+// See: <https://github.com/lcnr/random-rust-snippets/issues/13>
```
Comment (lcnr) [inline tests/ui/coercion/lub_closures_before_fnptr_coercion.rs]: i think this test is cool given the amount of jank necessary to get it to work and it felt really good to get this to work.

I don't think it's useful for our UI suite however and will likely be annoying to handle if its behavior ever changes (which feels likely) :thinking: 

I would prefer to just have that snippet somewhere else, e.g. add it to https://github.com/lcnr/random-rust-snippets/issues/13 or sth, instead of keeping it in our ui test suite

File: compiler/rustc_hir_typeck/src/coercion.rs (hunk 8 above)
Comment (lcnr) [reply compiler/rustc_hir_typeck/src/coercion.rs]: resolved in a later commit

File: compiler/rustc_hir_typeck/src/coercion.rs (hunk 2 above)
Comment (BoxyUwU) [reply compiler/rustc_hir_typeck/src/coercion.rs]: ah it was less switching args and more that i initially removed `r_b` because its only used for the weird syntacitcal lifetime equality hack we do. and then I couldn't remove that hack and readded it so it ended up on the end. In theory this fn should really only accept the first three args. will revert this

File: compiler/rustc_hir_typeck/src/coercion.rs (hunk 4 above)
Comment (BoxyUwU) [reply compiler/rustc_hir_typeck/src/coercion.rs]: ~~long~~ short live `let else`

File: compiler/rustc_hir_typeck/src/coercion.rs (hunk 5 above)
Comment (BoxyUwU) [reply compiler/rustc_hir_typeck/src/coercion.rs]: In the long term we just wind up not normalizing here under the new solver because lazy norm right? :thinking: I guess ur right that the real problem is TypeError infer var leakage moreso than normalizing :thinking: gonna remove this FIXME

File: tests/ui/coercion/leak_check_fndef_lub.rs (hunk 9 above)
Comment (BoxyUwU) [reply tests/ui/coercion/leak_check_fndef_lub.rs]: i did mean fndefs :thinking: and ah yeah you're right the param is unused so it gets made invariant. need to adjust this test

File: compiler/rustc_hir_typeck/src/coercion.rs (hunk 7 above)
Comment (BoxyUwU) [reply compiler/rustc_hir_typeck/src/coercion.rs]: I don't like this because it feel easy to misread `ExplicitLeakCheck::No` as meaning "no leak check" . The naming i picked feels quite clear to me that `LeakCheck::Default` is doing something a little subtle even if it does read kinda oddly :thinking:

Comment (BoxyUwU) [reply compiler/rustc_hir_typeck/src/coercion.rs]: Maybe `ForceLeakCheck`
