### PR TITLE
Break critical edges in inline asm before code generation

### LINKED ISSUE #137867: asm_goto_with_outputs miscompilation
This should return `7`, but returns `a`, with or without optimizations.
```rust
#![feature(asm_goto)]
#![feature(asm_goto_with_outputs)]

#[unsafe(no_mangle)]
pub fn asm_goto_test(
    mut a: i16,
) -> i16 {
    unsafe {
        std::arch::asm!(
            "jmp {op}",
            inout("eax") a,
            op = label { a = 7; },
            options(nostack,nomem)
        );
        a
    }
}
```
https://godbolt.org/z/Efze66G84

As far as I can tell, the MIR looks correct:
```rust
fn asm_goto_test(_1: i16) -> i16 {
    debug a => _1;
    let mut _0: i16;

    bb0: {
        asm!("jmp {1}", inout("ax") copy _1 => _1, label 1, options(NOMEM | NOSTACK)) -> [return: bb1, label: bb2, unwind unreachable];
    }

    bb1: {
        _0 = copy _1;
        return;
    }

    bb2: {
        _1 = const 7_i16;
        goto -> bb1;
    }
}
```
In particular, the value assigned to `_1` in `bb2` is returned in `bb1`.

The LLVM-IR is incorrect, as `bb2` stores the value to `ptr %a`, but `bb1` then overwrites that with the previous value in `%2`.
```llvm
define i16 @asm_goto_test(i16 %0) unnamed_addr {
start:
  %a = alloca [2 x i8], align 2
  store i16 %0, ptr %a, align 2
  %1 = load i16, ptr %a, align 2
  %2 = callbr i16 asm sideeffect inteldialect "jmp ${2:l}", "=&{ax},0,!i,~{dirflag},~{fpsr},~{flags}"(i16 %1) #1
          to label %bb1 [label %bb2]

bb2:
  store i16 %2, ptr %a, align 2
  store i16 7, ptr %a, align 2
  br label %bb1

bb1:
  store i16 %2, ptr %a, align 2
  %_0 = load i16, ptr %a, align 2
  ret i16 %_0
}
```

`rustc --version --verbose`:
```
rustc 1.86.0-nightly (f85c6de55 2025-01-26)
binary: rustc
commit-hash: f85c6de55206dbee5ffedfd821df1503a7b92346
commit-date: 2025-01-26
host: x86_64-unknown-linux-gnu
release: 1.86.0-nightly
LLVM version: 19.1.7
```

asm_goto tracking issue: https://github.com/rust-lang/rust/issues/119364

@rustbot label +F-asm +A-inline-assembly +T-compiler

### PR DESCRIPTION
**Pull request by tmiasko**
An inline asm terminator defines outputs along its target edges -- a
fallthrough target and labeled targets. Code generation implements this
by inserting code directly into the target blocks. This approach works
only if the target blocks don't have other predecessors.

Establish required invariant by extending existing code that breaks
critical edges before code generation.

Fixes #137867.

r? @bjorn3

### CODE REVIEW

File: compiler/rustc_mir_transform/src/add_call_guards.rs [hunk 1]
```diff
@@ -53,19 +63,33 @@ impl<'tcx> crate::MirPass<'tcx> for AddCallGuards {
...
+                        },
+                    source_info,
+                }) if self == &CriticalCallEdges => {
+                    let has_outputs = operands.iter().any(|op| {
+                        matches!(op, InlineAsmOperand::InOut { .. } | InlineAsmOperand::Out { .. })
+                    });
+                    let has_labels =
+                        operands.iter().any(|op| matches!(op, InlineAsmOperand::Label { .. }));
+                    let invoke =
+                        matches!(unwind, UnwindAction::Cleanup(_) | UnwindAction::Terminate(_));
```
Comment (bjorn3) [inline compiler/rustc_mir_transform/src/add_call_guards.rs:85]: I did rather write this as not continue and not unreachable. That way if we add another variant it will have a safe default of being considered an invoke.

File: tests/codegen/asm/critical.rs [hunk 2]
```diff
@@ -0,0 +1,27 @@
...
+
+// Regression test for #137867. Check that critical edges have been split before code generation,
+// and so all labels in callbr lead to distinct blocks (CHECK-DAG matches are non-overlapping).
+//
+// CHECK-LABEL: @f(
+// CHECK:       callbr i32 asm
+// CHECK-NEXT:  to label %[[BB0:.*]] [label %[[BB1:.*]], label %[[BB2:.*]]],
+// CHECK-DAG:   [[BB0]]:
+// CHECK-DAG:   [[BB1]]:
+// CHECK-DAG:   [[BB2]]:
```
Comment (bjorn3) [inline tests/codegen/asm/critical.rs:16]: Can you assert that the jump instructions are correct? Even before this PR it would already result in branching to different blocks. It was just that one of the target blocks then jumps to another of the target blocks rather than both target blocks jumping to a common block.

Comment (bjorn3) [reply tests/codegen/asm/critical.rs:16]: That only has the same target twice because of optimizations. With `-Zmir-opt-level=0` I get two different targets on nightly: https://rust.godbolt.org/z/xvasqP79e

File: tests/codegen/asm/critical.rs [hunk 3]
```diff
@@ -0,0 +1,37 @@
+//@ only-x86_64
+//@ compile-flags: -C no-prepopulate-passes
+#![feature(asm_goto)]
+#![feature(asm_goto_with_outputs)]
+#![crate_type = "lib"]
+use std::arch::asm;
+
+// Regression test for #137867. Check that critical edges have been split before code generation,
+// and so all labels in callbr lead to distinct blocks.
```
Comment (bjorn3) [inline tests/codegen/asm/critical.rs:9]:
```suggestion
// and so all labels in callbr lead to distinct blocks without any of them jumping to another callbr label.
```

**Comment by bjorn3** [comment]
r=me with the comment clarified.
