### PR TITLE
Don't immediately error for cycles during normalization

### LINKED ISSUE #74868: Unexpected trait resolution overflow error
Trying to compile [`wundergraph_example`](https://github.com/weiznich/wundergraph/tree/ffbb883eea169d1750659e038d7051a84b21f6e7/wundergraph_example) with recent nightly's or the current beta (` rustc 1.46.0-beta.2 (6f959902b 2020-07-23`) compiler fails with the attached error message. The compilation suceeds without warning using the latest stable (`rustc 1.45.0 (5c1f21c3b 2020-07-13)`) release.

<details><summary>Error message</summary>
<p>

```
error[E0275]: overflow evaluating the requirement `<<Hero_table as diesel::query_builder::AsQuery>::Query as diesel::query_dsl::boxed_dsl::BoxedDsl<'_, DB>>::Output`
  --> wundergraph_example/src/mutations.rs:73:1
   |
73 | / wundergraph::mutation_object! {
74 | |     /// Global mutation object for the schema
75 | |     Mutation {
76 | |         Hero(insert = NewHero, update = HeroChangeset,),
...  |
81 | |     }
82 | | }
   | |_^
   |
   = note: required because of the requirements on the impl of `wundergraph::query_builder::mutations::HandleUpdate<hero::Hero, mutations::HeroChangeset, DB, Ctx>` for `Hero_table`
   = note: required because of the requirements on the impl of `juniper::GraphQLType<wundergraph::scalar::WundergraphScalarValue>` for `mutations::Mutation<Ctx>`
   = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0275]: overflow evaluating the requirement `<<Hero_table as diesel::query_builder::AsQuery>::Query as diesel::query_dsl::boxed_dsl::BoxedDsl<'_, DB>>::Output`
  --> wundergraph_example/src/mutations.rs:73:1
   |
73 | / wundergraph::mutation_object! {
74 | |     /// Global mutation object for the schema
75 | |     Mutation {
76 | |         Hero(insert = NewHero, update = HeroChangeset,),
...  |
81 | |     }
82 | | }
   | |_^
   |
   = note: required because of the requirements on the impl of `wundergraph::query_builder::mutations::HandleUpdate<hero::Hero, mutations::HeroChangeset, DB, Ctx>` for `Hero_table`
   = note: required because of the requirements on the impl of `juniper::GraphQLType<wundergraph::scalar::WundergraphScalarValue>` for `mutations::Mutation_wrapper<'a, Ctx>`
   = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0275]: overflow evaluating the requirement `<<Hero_table as diesel::query_builder::AsQuery>::Query as diesel::query_dsl::boxed_dsl::BoxedDsl<'_, DB>>::Output`
  --> wundergraph_example/src/mutations.rs:73:1
   |
73 | / wundergraph::mutation_object! {
74 | |     /// Global mutation object for the schema
75 | |     Mutation {
76 | |         Hero(insert = NewHero, update = HeroChangeset,),
...  |
81 | |     }
82 | | }
   | |_^
   |
   = note: required because of the requirements on the impl of `wundergraph::query_builder::mutations::HandleUpdate<hero::Hero, mutations::HeroChangeset, DB, Ctx>` for `Hero_table`
   = note: required because of the requirements on the impl of `juniper::GraphQLType<wundergraph::scalar::WundergraphScalarValue>` for `mutations::Mutation_inner<'a, Ctx>`
   = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0275]: overflow evaluating the requirement `<<Hero_table as diesel::query_builder::AsQuery>::Query as diesel::query_dsl::boxed_dsl::BoxedDsl<'_, DB>>::Output`
  --> wundergraph_example/src/mutations.rs:73:1
   |
73 | / wundergraph::mutation_object! {
74 | |     /// Global mutation object for the schema
75 | |     Mutation {
76 | |         Hero(insert = NewHero, update = HeroChangeset,),
...  |
81 | |     }
82 | | }
   | |_^
   |
   = note: required because of the requirements on the impl of `wundergraph::query_builder::mutations::HandleUpdate<hero::Hero, mutations::HeroChangeset, DB, Ctx>` for `Hero_table`
   = note: required because of the requirements on the impl of `juniper::GraphQLType<wundergraph::scalar::WundergraphScalarValue>` for `mutations::Mutation<Ctx>`
   = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0275]: overflow evaluating the requirement `<<Hero_table as diesel::query_builder::AsQuery>::Query as diesel::query_dsl::boxed_dsl::BoxedDsl<'_, DB>>::Output`
  --> wundergraph_example/src/mutations.rs:73:1
   |
73 | / wundergraph::mutation_object! {
74 | |     /// Global mutation object for the schema
75 | |     Mutation {
76 | |         Hero(insert = NewHero, update = HeroChangeset,),
...  |
81 | |     }
82 | | }
   | |_^
   |
   = note: required because of the requirements on the impl of `wundergraph::query_builder::mutations::HandleUpdate<hero::Hero, mutations::HeroChangeset, DB, Ctx>` for `Hero_table`
   = note: required because of the requirements on the impl of `juniper::GraphQLType<wundergraph::scalar::WundergraphScalarValue>` for `mutations::Mutation<Ctx>`
   = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0275]: overflow evaluating the requirement `<<Hero_table as diesel::query_builder::AsQuery>::Query as diesel::query_dsl::boxed_dsl::BoxedDsl<'_, DB>>::Output`
  --> wundergraph_example/src/mutations.rs:73:1
   |
73 | / wundergraph::mutation_object! {
74 | |     /// Global mutation object for the schema
75 | |     Mutation {
76 | |         Hero(insert = NewHero, update = HeroChangeset,),
...  |
81 | |     }
82 | | }
   | |_^
   |
   = note: required because of the requirements on the impl of `wundergraph::query_builder::mutations::HandleUpdate<hero::Hero, mutations::HeroChangeset, DB, Ctx>` for `Hero_table`
   = note: required because of the requirements on the impl of `juniper::GraphQLType<wundergraph::scalar::WundergraphScalarValue>` for `mutations::Mutation<Ctx>`
   = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0275]: overflow evaluating the requirement `<<Hero_table as diesel::query_builder::AsQuery>::Query as diesel::query_dsl::boxed_dsl::BoxedDsl<'_, DB>>::Output`
  --> wundergraph_example/src/mutations.rs:73:1
   |
73 | / wundergraph::mutation_object! {
74 | |     /// Global mutation object for the schema
75 | |     Mutation {
76 | |         Hero(insert = NewHero, update = HeroChangeset,),
...  |
81 | |     }
82 | | }
   | |_^
   |
   = note: required because of the requirements on the impl of `wundergraph::query_builder::mutations::HandleUpdate<hero::Hero, mutations::HeroChangeset, DB, Ctx>` for `Hero_table`
   = note: required because of the requirements on the impl of `juniper::GraphQLType<wundergraph::scalar::WundergraphScalarValue>` for `mutations::Mutation_wrapper<'a, Ctx>`
   = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0275]: overflow evaluating the requirement `<<Hero_table as diesel::query_builder::AsQuery>::Query as diesel::query_dsl::boxed_dsl::BoxedDsl<'_, DB>>::Output`
  --> wundergraph_example/src/mutations.rs:73:1
   |
73 | / wundergraph::mutation_object! {
74 | |     /// Global mutation object for the schema
75 | |     Mutation {
76 | |         Hero(insert = NewHero, update = HeroChangeset,),
...  |
81 | |     }
82 | | }
   | |_^
   |
   = note: required because of the requirements on the impl of `wundergraph::query_builder::mutations::HandleUpdate<hero::Hero, mutations::HeroChangeset, DB, Ctx>` for `Hero_table`
   = note: required because of the requirements on the impl of `juniper::GraphQLType<wundergraph::scalar::WundergraphScalarValue>` for `mutations::Mutation_wrapper<'a, Ctx>`
   = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0275]: overflow evaluating the requirement `<<Hero_table as diesel::query_builder::AsQuery>::Query as diesel::query_dsl::boxed_dsl::BoxedDsl<'_, DB>>::Output`
  --> wundergraph_example/src/mutations.rs:73:1
   |
73 | / wundergraph::mutation_object! {
74 | |     /// Global mutation object for the schema
75 | |     Mutation {
76 | |         Hero(insert = NewHero, update = HeroChangeset,),
...  |
81 | |     }
82 | | }
   | |_^
   |
   = note: required because of the requirements on the impl of `wundergraph::query_builder::mutations::HandleUpdate<hero::Hero, mutations::HeroChangeset, DB, Ctx>` for `Hero_table`
   = note: required because of the requirements on the impl of `juniper::GraphQLType<wundergraph::scalar::WundergraphScalarValue>` for `mutations::Mutation_wrapper<'a, Ctx>`
   = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0275]: overflow evaluating the requirement `<<Hero_table as diesel::query_builder::AsQuery>::Query as diesel::query_dsl::boxed_dsl::BoxedDsl<'_, DB>>::Output`
  --> wundergraph_example/src/mutations.rs:73:1
   |
73 | / wundergraph::mutation_object! {
74 | |     /// Global mutation object for the schema
75 | |     Mutation {
76 | |         Hero(insert = NewHero, update = HeroChangeset,),
...  |
81 | |     }
82 | | }
   | |_^
   |
   = note: required because of the requirements on the impl of `wundergraph::query_builder::mutations::HandleUpdate<hero::Hero, mutations::HeroChangeset, DB, Ctx>` for `Hero_table`
   = note: required because of the requirements on the impl of `juniper::GraphQLType<wundergraph::scalar::WundergraphScalarValue>` for `mutations::Mutation_inner<'a, Ctx>`
   = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0275]: overflow evaluating the requirement `<<Hero_table as diesel::query_builder::AsQuery>::Query as diesel::query_dsl::boxed_dsl::BoxedDsl<'_, DB>>::Output`
  --> wundergraph_example/src/mutations.rs:73:1
   |
73 | / wundergraph::mutation_object! {
74 | |     /// Global mutation object for the schema
75 | |     Mutation {
76 | |         Hero(insert = NewHero, update = HeroChangeset,),
...  |
81 | |     }
82 | | }
   | |_^
   |
   = note: required because of the requirements on the impl of `wundergraph::query_builder::mutations::HandleUpdate<hero::Hero, mutations::HeroChangeset, DB, Ctx>` for `Hero_table`
   = note: required because of the requirements on the impl of `juniper::GraphQLType<wundergraph::scalar::WundergraphScalarValue>` for `mutations::Mutation_inner<'a, Ctx>`
   = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0275]: overflow evaluating the requirement `<<Hero_table as diesel::query_builder::AsQuery>::Query as diesel::query_dsl::boxed_dsl::BoxedDsl<'_, DB>>::Output`
  --> wundergraph_example/src/mutations.rs:73:1
   |
73 | / wundergraph::mutation_object! {
74 | |     /// Global mutation object for the schema
75 | |     Mutation {
76 | |         Hero(insert = NewHero, update = HeroChangeset,),
...  |
81 | |     }
82 | | }
   | |_^
   |
   = note: required because of the requirements on the impl of `wundergraph::query_builder::mutations::HandleUpdate<hero::Hero, mutations::HeroChangeset, DB, Ctx>` for `Hero_table`
   = note: required because of the requirements on the impl of `juniper::GraphQLType<wundergraph::scalar::WundergraphScalarValue>` for `mutations::Mutation_inner<'a, Ctx>`
   = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

error: aborting due to 12 previous errors

For more information about this error, try `rustc --explain E0275`.
error: could not compile `wundergraph_example`.
```
</p>
</details>

`cargo bisect-rustc` found that the regression happened in `nightly-2020-06-21`

### PR DESCRIPTION
**Pull request by matthewjasper**
#73452 meant some normalization cycles could be detected earlier, breaking some code.
This PR makes defers errors for normalization cycles to fulfillment, fixing said code.

Fixes #74868 

r? @nikomatsakis

### CODE REVIEW

File: src/librustc_trait_selection/traits/project.rs [hunk 1]
```diff
@@ -143,10 +145,13 @@ impl<'tcx> ProjectionTyCandidateSet<'tcx> {
 ///
 /// If successful, this may result in additional obligations. Also returns
 /// the projection cache key used to track these additional obligations.
-pub fn poly_project_and_unify_type<'cx, 'tcx>(
+pub(super) fn poly_project_and_unify_type<'cx, 'tcx>(
     selcx: &mut SelectionContext<'cx, 'tcx>,
     obligation: &PolyProjectionObligation<'tcx>,
-) -> Result<Option<Vec<PredicateObligation<'tcx>>>, MismatchedProjectionTypes<'tcx>> {
+) -> Result<
```
Comment (nikomatsakis) [inline src/librustc_trait_selection/traits/project.rs:151]: Nit: this is a complex return type! I thnk the doc comment could be extended to explain what the various return values mean.

**Comment by spastorino** [comment]
@bors p=1

Once approved we want this to be in ASAP.

File: src/librustc_trait_selection/traits/fulfill.rs [hunk 2]
```diff
@@ -622,15 +622,20 @@ impl<'a, 'b, 'tcx> FulfillProcessor<'a, 'b, 'tcx> {
...
                     self.selcx,
                     project_obligation.predicate.to_poly_trait_ref(self.selcx.tcx()),
                 );
                 ProcessResult::Unchanged
             }
-            Ok(Some(os)) => ProcessResult::Changed(mk_pending(os)),
+            // Let the caller handle the recursion
+            Ok(Err(project::InProgress)) => ProcessResult::Changed(mk_pending(vec![
+                project_obligation.with(project_obligation.predicate.to_predicate(tcx)),
+            ])),
```
Comment (nikomatsakis) [inline src/librustc_trait_selection/traits/fulfill.rs:638]: ok, I see, so we basically just push the project predicate back up to the caller... interesting...

**Review by nikomatsakis — APPROVED** [review]
OK, I understand the strategy now, it's not once I had ever considered. Interesting. Also, a good example to try throwing at chalk, I've been wanting to create realistic examples of cycles (or near cycles) that arise during projection.

**Comment by nikomatsakis** [comment]
Er, @bors r-

r=me with the nit addressed

**Comment by nikomatsakis** [comment]
Or just r+ if we think it's important enough

**Comment by spastorino** [comment]
[heavily discussed](https://zulip-archive.rust-lang.org/238009tcompilermeetings/79848weeklymeeting2020082054818.html#207525792) in T-compiler meeting.

This is a subtle change to subtle code. We've also agreed on backporting it and fire a crater run as soon as possible, which probably won't be on time but would give as an advantage to act quickly if there are bad consequences.

@rustbot modify labels: beta-accepted
