### PR TITLE
Closure argument mismatch tweaks

### LINKED ISSUE #44150: Better error for missing tuple pattern in args
[Playground link](https://play.rust-lang.org/?gist=aaab1a247c878964fe6f228d354464ce&version=stable)

```rust
fn main() {
    let v = vec![1, 2, 3];
    let v2: Vec<_> = v.into_iter().enumerate().map(|i, x| i).collect();
    println!("{:?}", v2);
}
```

Currently, this produces a somewhat confusing error:

```
error[E0593]: closure takes 2 arguments but 1 argument is required
 --> src/main.rs:3:48
  |
3 |     let v2: Vec<_> = v.into_iter().enumerate().map(|i, x| i).collect();
  |                                                ^^^ -------- takes 2 arguments
  |                                                |
  |                                                expected closure that takes 1 argument
```

which could potentially be improved for this common case (an N-tuple was expected, but the closure takes N arguments instead). This could extend to other cases where there is a tuple : multiple arguments mismatch.

### PR DESCRIPTION
**Pull request by estebank**
- use consistent phrasing for expected and found arguments
 - suggest changing arguments to tuple if possible
 - suggest changing single tuple argument to arguments if possible

Fix #44150.

### CODE REVIEW

File: src/librustc/traits/error_reporting.rs [hunk 1]
```diff
@@ -845,94 +792,134 @@ impl<'a, 'gcx, 'tcx> InferCtxt<'a, 'gcx, 'tcx> {
...
+                .map(|arg| {
+                    if let hir::Pat {
+                        node: hir::PatKind::Tuple(args, _),
+                        span,
+                        ..
+                    } = arg.pat.clone().into_inner() {
+                        ArgKind::Tuple(
+                            span,
+                            args.iter().map(|pat| {
+                                let snippet = self.tcx.sess.codemap().span_to_snippet(pat.span).unwrap();
```
Comment (varkor) [inline src/librustc/traits/error_reporting.rs]: Tidy error for this line.

**Review by nikomatsakis — APPROVED** [review]
r=me once travis errors are fixed

File: src/librustc/traits/error_reporting.rs (hunk 1 above)
Comment (estebank) [reply src/librustc/traits/error_reporting.rs]: Yeah, there're a bunch of code I'm none too happy with, I'll clean it up as much as possible before merging.
