### PR TITLE
fix: Unexpected trait bound not satisfied in HRTB and Associated Type

### LINKED ISSUE #103563: Unexpected trait bound not satisfied in GAT & HRTB
I tried this code:

```rust
fn main() {
    let mut log_service = LogService { inner: Inner };
    log_service.call(());
}

pub trait Service<Request> {
    type Response;

    fn call(&mut self, req: Request) -> Self::Response;
}

pub struct LogService<S> {
    inner: S,
}

impl<T, U, S> Service<T> for LogService<S>
where
    S: Service<T, Response = U>,
    U: Extension + 'static,
    for<'a> U::Item<'a>: std::fmt::Debug,
{
    type Response = S::Response;

    fn call(&mut self, req: T) -> Self::Response {
        self.inner.call(req)
    }
}

pub struct Inner;

impl Service<()> for Inner {
    type Response = Resp;

    fn call(&mut self, req: ()) -> Self::Response {
        Resp::A(req)
    }
}

pub trait Extension {
    type Item<'a>;

    fn touch<F>(self, f: F) -> Self
    where
        for<'a> F: Fn(Self::Item<'a>);
}

pub enum Resp {
    A(()),
}

impl Extension for Resp {
    type Item<'a> = RespItem<'a>;
    fn touch<F>(self, _f: F) -> Self
    where
        for<'a> F: Fn(Self::Item<'a>),
    {
        match self {
            Self::A(a) => Self::A(a),
        }
    }
}

pub enum RespItem<'a> {
    A(&'a ()),
}

impl<'a> std::fmt::Debug for RespItem<'a> {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::A(arg0) => f.debug_tuple("A").field(arg0).finish(),
        }
    }
}

```

### Meta

`rustc --version --verbose`:
```
rustc 1.66.0-nightly (bed4ad65b 2022-10-25)
binary: rustc
commit-hash: bed4ad65bf7a1cef39e3d66b3670189581b3b073
commit-date: 2022-10-25
host: x86_64-unknown-linux-gnu
release: 1.66.0-nightly
LLVM version: 15.0.2
```

<details><summary>Backtrace</summary>
<p>

```
error[E0599]: the method `call` exists for struct `LogService<Inner>`, but its trait bounds were not satisfied
  --> src/main.rs:3:17
   |
3  |     log_service.call(());
   |                 ^^^^ method cannot be called on `LogService<Inner>` due to unsatisfied trait bounds
...
12 | pub struct LogService<S> {
   | ------------------------
   | |
   | method `call` not found for this struct
   | doesn't satisfy `LogService<Inner>: Service<_>`
   |
note: trait bound `<_ as Extension>::Item<'a>: Debug` was not satisfied
  --> src/main.rs:20:26
   |
16 | impl<T, U, S> Service<T> for LogService<S>
   |               ----------     -------------
...
20 |     for<'a> U::Item<'a>: std::fmt::Debug,
   |                          ^^^^^^^^^^^^^^^ unsatisfied trait bound introduced here

For more information about this error, try `rustc --explain E0599`.
```

</p>
</details>

### PR DESCRIPTION
**Pull request by LYF1999**
fix https://github.com/rust-lang/rust/issues/103563

### CODE REVIEW

**Comment by LYF1999** [comment]
hm... I can not reproduce this CI error on my machine

**Comment by compiler-errors** [comment]
@LYF1999, please provide a more thorough description in the PR for why you think this fixes the issue, since the change is in some pretty fundamental trait selection code.

**Comment by LYF1999** [comment]
there is code can produce this bug. And it's not about GAT.
```rust 
use std::fmt::Debug;

fn main() {
    let mut log_service = LogService { inner: Inner };
    log_service.call(Struct1 {});
}

pub trait Service<Request> {
    type Response;

    fn call(&mut self, req: Request) -> Self::Response;
}

pub struct LogService<S> {
    inner: S,
}

impl<T, S, U> Service<T> for LogService<S>
where
    S: Service<T, Response = U>,
    U: for<'a> Extension<'a>,
    for<'a> <U as Extension<'a>>::Item: std::fmt::Debug,
{
    type Response = S::Response;

    fn call(&mut self, req: T) -> Self::Response {
        self.inner.call(req)
    }
}

pub struct Inner;

impl Service<Struct1> for Inner {
    type Response = Resp;

    fn call(&mut self, req: Struct1) -> Self::Response {
        Resp::A(req)
    }
}

pub trait Extension<'a> {
    type Item;
}

pub trait E2
where
    Self: for<'a> Extension<'a>,
{
    fn touch<F>(self, f: F) -> Self
    where
        F: for<'b> Fn(<Self as Extension<'b>>::Item);
}

#[derive(Debug)]
pub struct Struct1 {}

pub enum Resp {
    A(Struct1),
}

impl<'a> Extension<'a> for Resp {
    type Item = RespItem<'a>;
}

impl E2 for Resp {
    fn touch<F>(self, f: F) -> Self
    where
        F: for<'b> Fn(<Self as Extension<'b>>::Item),
    {
        match &self {
            Resp::A(a) => f(RespItem::A(a)),
        }
        self
    }
}

pub enum RespItem<'a> {
    A(&'a Struct1),
}

impl Debug for RespItem<'_> {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::A(arg0) => f.debug_tuple("A").field(arg0).finish(),
        }
    }
}
```

compiler try to evaluate predicate `for<'a> <U as Extension<'a>>::Item: std::fmt::Debug`.   
in this context, `fn evaluate_trait_predicate_recursively` gets a obligation `<Resp<'a> as Extension<'a>>::Item: Debug`.
but `fn candidate_from_obligation` assemble 0 candidate for `<Resp<'a> as Extension<'a>>::Item: Debug`.
So this code failed.
there are some ways to resolve that:
1. normalize `<Resp<'a> as Extension<'a>>::Item: Debug` to `RespItem<'a>: Debug` and evaluate it.
2. normalize `<Resp<'a> as Extension<'a>>::Item: Debug` in `candidate_from_obligation` and assemble 1 candidate `ImplCandidate`. but `fn rematch_impl` will check `ImplCandidate`.

@compiler-errors

**Comment by davidtwco** [comment]
r? rust-lang/types

**Comment by LYF1999** [comment]
benchmarks passed @jackh726 PTAL

**Comment by jackh726** [comment]
Here are my general thoughts:

This solves the issue linked in the OP. It probably solves some other related issues. However, it does so at the cost of an extra normalization call in a core solver function. This isn't *that* unheard of (given I've even added such in the past), but additions like this should be weighed on balance.

To add to this, the specific placement of this call seems curious to me. It's *in between* two cache checks? I would expect it to be at the beginning of this function, or moved up to a function higher up.

That being said, I'm short on time to review this well, and I trust anyone from the types team to review this, so let's r? types

**Comment by oli-obk** [comment]
I've been crawling through some tracing logs for an hour and haven't gotten any new insights... Mainly I agree with jack that this is the wrong place to normalize, but I'm not sure what the right place is. Maybe we should wait until the trait solver stalls and would report ambiguous, then normalize all leftover obligations and try again. If it's immediately ambiguous again, bail out as normal, otherwise continue and potentially do another normalization round later.

**Comment by LYF1999** [comment]
I have moved the normalization to the evaluation failed place. @oli-obk please take a look~

**Comment by oli-obk** [comment]
I'm on vacation for two weeks, will review after that

**Comment by oli-obk** [comment]
The implementation lgtm.

This change makes the compiler accept more code. An example is given in https://github.com/rust-lang/rust/pull/103695#issuecomment-1295256183. In short: sometimes we have to prove trait bounds on projections, but do not have enough information about the projection to actually prove this bound, but we have enough information to normalize it to a more specific type, and then the bound may hold. This PR changes trait solving to normalize if a trait bound does not hold and there are projections involved.

@rfcbot merge

I'm not sure if this is significant enough to warrant including the lang team, I don't think so, but please do raise a concern if you would feel more comfortable with additional eyes on the language change here.

File: compiler/rustc_trait_selection/src/traits/select/mod.rs [hunk 1]
```diff
@@ -1017,7 +1018,31 @@ impl<'cx, 'tcx> SelectionContext<'cx, 'tcx> {
             return Ok(cycle_result);
         }
 
-        let (result, dep_node) = self.in_task(|this| this.evaluate_stack(&stack));
+        let (result, dep_node) = self.in_task(|this| {
+            let mut result = this.evaluate_stack(&stack)?;
+
+            // if evaluate failed, try to normalize the predicate and evaluate again.
+            if EvaluationResult::EvaluatedToErr == result
```
Comment (lcnr) [inline compiler/rustc_trait_selection/src/traits/select/mod.rs:1025]: this doesn't feel like the right place to do this. The caller of evaluate should ideally have already normalized the predicate.

I feel like we're missing a normalize call somewhere and that this change is merely hiding that issue.

Haven't read the discussion in this PR so this may have already been brought up, sorry in that case.

File: compiler/rustc_trait_selection/src/traits/select/mod.rs [hunk 2]
```diff
@@ -1017,7 +1018,31 @@ impl<'cx, 'tcx> SelectionContext<'cx, 'tcx> {
...
+                && fresh_trait_pred.has_projections()
+                && fresh_trait_pred.is_global()
+            {
+                let predicate = try_normalize_with_depth_to(
+                    this,
+                    param_env,
+                    obligation.cause.clone(),
+                    obligation.recursion_depth + 1,
+                    fresh_trait_pred,
+                    &mut Vec::new(),
```
Comment (lcnr) [inline compiler/rustc_trait_selection/src/traits/select/mod.rs:1035]: ignoring nested obligations is pretty much always unsound. This needs at least a comment for why its sound.

File: compiler/rustc_trait_selection/src/traits/select/mod.rs (hunk 1 above)
Comment (lcnr) [reply compiler/rustc_trait_selection/src/traits/select/mod.rs:1025]: alright :sweat_smile: actually looked at the previous comments and saw this already mentioned. We intend to replace evaluate with a new solver in the near future at which point this issue should be fixed without needing any additional work.

Until then I am always a bit concerned when making evaluate stronger as this provides more places where the specific behavior of evaluate is actually more powerful than the new solver making it more difficult to switch. I don't think this PR adds any such issues cause it should just work™

File: compiler/rustc_trait_selection/src/traits/select/mod.rs (hunk 2 above)
Comment (LYF1999) [reply compiler/rustc_trait_selection/src/traits/select/mod.rs]: indeed, it's unsound at here, we can evaluate those nested obligations and ensure they all are ok

File: compiler/rustc_trait_selection/src/traits/select/mod.rs [hunk 3]
```diff
@@ -1017,7 +1018,41 @@ impl<'cx, 'tcx> SelectionContext<'cx, 'tcx> {
...
+                );
+                if predicate != fresh_trait_pred {
+                    let obligation = obligation.with(this.tcx(), predicate);
+                    let nested_obligations_result = nested_obligations
+                        .into_iter()
+                        .map(|obligation| {
+                            this.evaluate_predicate_recursively(stack.list(), obligation)
+                        })
+                        .collect::<Result<Vec<_>, _>>()?;
+                    if nested_obligations_result.iter().all(|result| *result == EvaluatedToOk) {
```
Comment (lcnr) [inline compiler/rustc_trait_selection/src/traits/select/mod.rs:1046]: don't check for `EvaluatedToOk`, instead merge all evaluation results.

Checking for `EvaluatedToOk` for behavior is kinda bad as it causes code to break the moment it adds a lifetime parameter, evne if it is fully unconstrained.

File: compiler/rustc_trait_selection/src/traits/select/mod.rs [hunk 4]
```diff
@@ -1017,7 +1018,43 @@ impl<'cx, 'tcx> SelectionContext<'cx, 'tcx> {
...
+                            nested_result,
+                        );
+                    }
+
+                    if nested_result.must_apply_modulo_regions() {
+                        let obligation = obligation.with(this.tcx(), predicate);
+                        result =
+                            this.evaluate_trait_predicate_recursively(stack.list(), obligation)?;
+                    }
+                }
```
Comment (lcnr) [inline compiler/rustc_trait_selection/src/traits/select/mod.rs:1052]: also "and" the `predicate` here together with the nested obligations from normalizing, a `must_apply_modulo_regions()` influencing behavior inside of the solver is pretty much always wrong.

Comment (lcnr) [reply compiler/rustc_trait_selection/src/traits/select/mod.rs]: ah woops, `must_apply_modulo_regions()` (forgot what `modulo` means for a second, sorry) is actually alright. `considering_regions` is the variant which breaks even if just add an unused region parameter. Even if the nested result doesn't apply, you coudl still do `result = nested_result.max(this.evaluate_trait_predicate_recursively(stack.list(), obligation)?)` which is needed if the nested result could have region obligations.

**Comment by lcnr** [comment]
fine with landing this after extending the comment by 1) referencing a test that fails without that and 2) mentioning something like the below explanation.

One place where we don't normalize is when proving nested obligations while normalizing. Normalization doesn't normalize the arguments to projections as it uses them for `TraitDef` candidates (i.e. using bounds on assoc items as assumptions) and then doesn't normalize nested obligations before proving them. This might not be the only place where we don't normalize obligations before solving them, but probably the biggest one. I am fine with just keeping that weird behavior until we replace evaluate with the new solver.

**Comment by LYF1999** [comment]
@lcnr Hi, I had updated the comments, ping for review

File: compiler/rustc_trait_selection/src/traits/select/mod.rs [hunk 5]
```diff
@@ -1017,7 +1018,47 @@ impl<'cx, 'tcx> SelectionContext<'cx, 'tcx> {
             return Ok(cycle_result);
         }
 
-        let (result, dep_node) = self.in_task(|this| this.evaluate_stack(&stack));
+        let (result, dep_node) = self.in_task(|this| {
+            let mut result = this.evaluate_stack(&stack)?;
+
+            // fix issue #103563, we don't normalize nested obligations which produced by `TraitDef` candidate (i.e. using bounds on assoc items as assumptions).
+            // because we don't have enough information to normalize these obligations before evaluating. so we will try to normalize the obligation and evaluate again.
+            // we will replace it with new solver in the future.
```
Comment (lcnr) [inline compiler/rustc_trait_selection/src/traits/select/mod.rs:1026]: why does tidy not complain about the line length here :sweat_smile: please keep it at around 90 :grin: looks fine :+1:

Comment (LYF1999) [reply compiler/rustc_trait_selection/src/traits/select/mod.rs]: thanks, I have updated this.

**Comment by lcnr** [comment]
This is waiting on FCP, r=me on the impl once that's done.

**Comment by LYF1999** [comment]
hm... I don't have the privileges, I guess I need a r+

**Comment by lcnr** [comment]
this is waiting on the FCP in https://github.com/rust-lang/rust/pull/103695#issuecomment-1376885403 we should not merge this yet

File: compiler/rustc_trait_selection/src/traits/select/mod.rs [hunk 6]
```diff
@@ -1017,7 +1018,51 @@ impl<'cx, 'tcx> SelectionContext<'cx, 'tcx> {
...
+                && fresh_trait_pred.has_projections()
+                && fresh_trait_pred.is_global()
+            {
+                let mut nested_obligations = Vec::new();
+                let predicate = try_normalize_with_depth_to(
+                    this,
+                    param_env,
+                    obligation.cause.clone(),
+                    obligation.recursion_depth + 1,
+                    fresh_trait_pred,
```
Comment (lcnr) [inline compiler/rustc_trait_selection/src/traits/select/mod.rs:1041]: don't use the `fresh_trait_pred` here but `obligation.predicate` instead.

**Review by lcnr — COMMENTED** [review]
r=me after the final change

File: compiler/rustc_trait_selection/src/traits/select/mod.rs (hunk 6 above)
Comment (LYF1999) [reply compiler/rustc_trait_selection/src/traits/select/mod.rs:1041]: why shouldn't we use `fresh_trait_pred`?

Comment (lcnr) [reply compiler/rustc_trait_selection/src/traits/select/mod.rs:1041]: because the `fresh_trait_pred` has inference variables replaced with fresh inference variables and the trait solver cannot deal with those.

Comment (LYF1999) [reply compiler/rustc_trait_selection/src/traits/select/mod.rs]: Oh, I get it, thanks!

File: compiler/rustc_trait_selection/src/traits/select/mod.rs [hunk 7]
```diff
@@ -1017,7 +1018,51 @@ impl<'cx, 'tcx> SelectionContext<'cx, 'tcx> {
...
+                    obligation.cause.clone(),
+                    obligation.recursion_depth + 1,
+                    obligation.predicate,
+                    &mut nested_obligations,
+                );
+                if predicate != obligation.predicate {
+                    let mut nested_result = EvaluationResult::EvaluatedToOk;
+                    for obligation in nested_obligations {
+                        nested_result = cmp::max(
+                            this.evaluate_predicate_recursively(stack.list(), obligation)?,
```
Comment (lcnr) [inline compiler/rustc_trait_selection/src/traits/select/mod.rs:1048]: this uses the stack which already includes the current goal, so we get a coinductive cycle in #108897. Have to pop the element pushed in line 988 before recursing so that the stack isn't invalid.

Comment (LYF1999) [reply compiler/rustc_trait_selection/src/traits/select/mod.rs:1048]: thanks~
