### PR TITLE
rustc_target/riscv: Fix passing of transparent unions with only one non-ZST member

### LINKED ISSUE #115481: riscv64gc-unknown-linux-gnu `extern "C"` ABI violates repr(transparent) on unions
The types `(i32, f32)` and `MaybeUninit<T>` do not have the same ABI, as demonstrated by this testcase:
```rust
#![feature(rustc_attrs)]

type T = (i32, f32);

#[rustc_abi(debug)]
extern "C" fn test1(_x: T) {}

#[rustc_abi(debug)]
extern "C" fn test2(_x: std::mem::MaybeUninit<T>) {}

fn main() {}
```
The first is
```
                   mode: Cast(
                       CastTarget {
                           prefix: [
                               Some(
                                   Reg {
                                       kind: Integer,
                                       size: Size(4 bytes),
                                   },
                               ),
                               None,
                               None,
                               None,
                               None,
                               None,
                               None,
                               None,
                           ],
                           rest: Uniform {
                               unit: Reg {
                                   kind: Float,
                                   size: Size(4 bytes),
                               },
                               total: Size(4 bytes),
                           },
                           attrs: ArgAttributes {
                               regular: (empty),
                               arg_ext: None,
                               pointee_size: Size(0 bytes),
                               pointee_align: None,
                           },
                       },
                       false,
                   ),
```
The second is
```
                   mode: Cast(
                       CastTarget {
                           prefix: [
                               None,
                               None,
                               None,
                               None,
                               None,
                               None,
                               None,
                               None,
                           ],
                           rest: Uniform {
                               unit: Reg {
                                   kind: Integer,
                                   size: Size(8 bytes),
                               },
                               total: Size(8 bytes),
                           },
                           attrs: ArgAttributes {
                               regular: (empty),
                               arg_ext: None,
                               pointee_size: Size(0 bytes),
                               pointee_align: None,
                           },
                       },
                       false,
                   ),
```

Not sure whom to ping for RISC-V issues.

### PR DESCRIPTION
**Pull request by msizanoen1**
This ensures that `MaybeUninit<T>` has the same ABI as `T` when passed through an `extern "C"` function.

Fixes https://github.com/rust-lang/rust/issues/115481.

r? @RalfJung

### CODE REVIEW

File: compiler/rustc_target/src/abi/call/riscv.rs [hunk 1]
```diff
@@ -87,7 +87,31 @@ where
             FieldsShape::Primitive => {
                 unreachable!("aggregates can't have `FieldsShape::Primitive`")
             }
-            FieldsShape::Union(_) => {
+            FieldsShape::Union(count) => {
+                if arg_layout.is_transparent() {
+                    let mut non_zst_elem = None;
+                    for i in 0..count.get() {
+                        let elem_layout = arg_layout.field(cx, i);
+                        if elem_layout.is_zst() {
```
Comment (RalfJung) [inline compiler/rustc_target/src/abi/call/riscv.rs:95]:
```suggestion
                        if elem_layout.is_1zst() {
```

File: compiler/rustc_target/src/abi/call/riscv.rs [hunk 2]
```diff
@@ -87,7 +87,31 @@ where
...
+                            continue;
+                        }
+                        // There can only be one.
+                        if non_zst_elem.is_some() {
+                            return Err(CannotUseFpConv);
```
Comment (RalfJung) [inline compiler/rustc_target/src/abi/call/riscv.rs:100]:
```suggestion
                            bug!("two non-1-ZST fields in repr(transparent) union");
```

**Review by RalfJung — COMMENTED** [review]
I can confirm that this fixes the testcase in https://github.com/rust-lang/rust/pull/115372.

I just got some nits, but I would prefer if someone more knowledgeable on ABIs would take a look... Cc @bjorn3 @Lokathor 

Also do we have to worry about this being an ABI-breaking change?

File: compiler/rustc_target/src/abi/call/riscv.rs (hunk 1 above)
Comment (msizanoen1) [reply compiler/rustc_target/src/abi/call/riscv.rs]: Done

File: compiler/rustc_target/src/abi/call/riscv.rs (hunk 2 above)
Comment (msizanoen1) [reply compiler/rustc_target/src/abi/call/riscv.rs]: `bug!` is not available in `rustc_target` (as it's defined in `rustc_middle` which is not depended on by `rustc_target`) so I used `unreachable!` instead.

**Comment by RalfJung** [comment]
LGTM but let's get another pair of eyes on it and hopefully someone who knows our process for breaking ABI. This affects `extern "C" fn` after all, albeit only when non-`repr(C)` types are involved.

r? compiler

**Comment by compiler-errors** [comment]
Gonna pass to someone who knows more about ABIs. Sorry for not getting to this sooner.

r? @bjorn3

File: compiler/rustc_target/src/abi/call/riscv.rs [hunk 3]
```diff
@@ -87,7 +87,31 @@ where
...
+                        let elem_layout = arg_layout.field(cx, i);
+                        if elem_layout.is_1zst() {
+                            continue;
+                        }
+                        // There can only be one.
+                        if non_1zst_elem.is_some() {
+                            unreachable!("two non-1-ZST fields in repr(transparent) union");
+                        }
+                        non_1zst_elem = Some(elem_layout);
+                    }
```
Comment (bjorn3) [inline compiler/rustc_target/src/abi/call/riscv.rs:103]: Would the `non_1zst_field()` function introduced by #115798 work here? Also I think you will have to recursively unwrap transparent types.

Comment (RalfJung) [reply compiler/rustc_target/src/abi/call/riscv.rs:103]: This is already recursive, it calls `should_use_fp_conv_helper` on the non-1-ZST field.

**Comment by bjorn3** [comment]
Thanks!

@bors r+
