### PR TITLE
const-eval interning: accept interior mutable pointers in final value

### LINKED ISSUE #121610: regression: encountered mutable pointer in final value when "outer scope" rule applies in const/static with interior mutability
* https://crater-reports.s3.amazonaws.com/beta-1.77-3/beta-2024-02-18/gh/adrianromero.rustexamples/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.77-3/beta-2024-02-18/gh/emirror-de.boa-test/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.77-3/beta-2024-02-18/gh/glenfordwilliams.rustybrain/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.77-3/beta-2024-02-18/gh/traxys.pac_proxy/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.77-3/beta-2024-02-18/reg/Boa-0.13.1/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.77-3/beta-2024-02-18/reg/epo-1.0.1/log.txt

```
[INFO] [stdout] error: encountered mutable pointer in final value of constant
[INFO] [stdout]    --> /opt/rustwide/cargo-home/registry/src/index.crates.io-6f17d22bba15001f/Boa-0.13.0/src/builtins/map/mod.rs:341:9
[INFO] [stdout]     |
[INFO] [stdout] 341 |         const JS_ZERO: &JsValue = &JsValue::Rational(0f64);
[INFO] [stdout]     |         ^^^^^^^^^^^^^^^^^^^^^^^
```

### LINKED ISSUE #122153: Tracking issue for future-incompatibility lint `const_eval_mutable_ptr_in_final_value`
This is a tracking issue for the `CONST_EVAL_MUTABLE_PTR_IN_FINAL_VALUE` lint, which is being added in https://github.com/rust-lang/rust/pull/122204. The lint detects cases where a const expression evaluates to a value that holds a pointer to mutable state, which is undefined behavior and may be rejected by a future version of the compiler.

### Example

This lint will trigger for code like this:

```rust
use std::cell::Cell;

pub enum JsValue {
    Undefined,
    Object(Cell<bool>),
}

impl ::std::ops::Drop for JsValue {
    fn drop(&mut self) {}
}

const UNDEFINED: &JsValue = &JsValue::Undefined;

fn main() {
}
```

Cc #121610

### PR DESCRIPTION
**Pull request by RalfJung**
…but keep rejecting mutable references

This fixes https://github.com/rust-lang/rust/issues/121610 by no longer firing the lint when there is a pointer with interior mutability in the final value of the constant. On stable, such pointers can be created with code like:
```rust
pub enum JsValue {
    Undefined,
    Object(Cell<bool>),
}
impl Drop for JsValue {
    fn drop(&mut self) {}
}
// This does *not* get promoted since `JsValue` has a destructor.
// However, the outer scope rule applies, still giving this 'static lifetime.
const UNDEFINED: &JsValue = &JsValue::Undefined;
```
It's not great to accept such values since people *might* think that it is legal to mutate them with unsafe code. (This is related to how "infectious" `UnsafeCell` is, which is a [wide open question](https://github.com/rust-lang/unsafe-code-guidelines/issues/236).) However, we [explicitly document](https://doc.rust-lang.org/reference/behavior-considered-undefined.html) that things created by `const` are immutable. Furthermore, we also accept the following even more questionable code without any lint today:
```rust
let x: &'static Option<Cell<i32>> = &None;
```
This is even more questionable since it does *not* involve a `const`, and yet still puts the data into immutable memory. We could view this as promotion [potentially introducing UB](https://github.com/rust-lang/unsafe-code-guidelines/issues/493). However, we've accepted this since ~forever and it's [too late to reject this now](https://github.com/rust-lang/rust/pull/122789); the pattern is just too useful.

So basically, if you think that `UnsafeCell` should be tracked fully precisely, then you should want the lint we currently emit to be removed, which this PR does. If you think `UnsafeCell` should "infect" surrounding `enum`s, the big problem is really https://github.com/rust-lang/unsafe-code-guidelines/issues/493 which does not trigger the lint -- the cases the lint triggers on are actually the "harmless" ones as there is an explicit surrounding `const` explaining why things end up being immutable.

What all this goes to show is that the hard error added in https://github.com/rust-lang/rust/pull/118324 (later turned into the future-compat lint that I am now suggesting we remove) was based on some wrong assumptions, at least insofar as it concerns shared references. Furthermore, that lint does not help at all for the most problematic case here where the potential UB is completely implicit. (In fact, the lint is actively in the way of [my preferred long-term strategy](https://github.com/rust-lang/unsafe-code-guidelines/issues/493#issuecomment-2028674105) for dealing with this UB.) So I think we should go back to square one and remove that error/lint for shared references. For mutable references, it does seem to work as intended, so we can keep it. Here it serves as a safety net in case the static checks that try to contain mutable references to the inside of a const initializer are not working as intended; I therefore made the check ICE to encourage users to tell us if that safety net is triggered.

Closes https://github.com/rust-lang/rust/issues/122153 by removing the lint.

Cc @rust-lang/opsem @rust-lang/lang

### CODE REVIEW

**Comment by nnethercote** [comment]
I don't feel comfortable reviewing this. @saethlin, are you a suitable reviewer? (I ask based on your membership of the opsem group combined with your r+ privileges.)

**Comment by saethlin** [comment]
Me or @oli-obk

**Comment by nnethercote** [comment]
Oli is away, so: r? @saethlin 

Thanks!

File: compiler/rustc_middle/src/mir/interpret/pointer.rs [hunk 1]
```diff
@@ -117,10 +128,38 @@ impl CtfeProvenance {
...
+    }
+
+    pub fn into_parts(self) -> (AllocId, bool, bool) {
+        (self.alloc_id(), self.immutable(), self.shared_ref())
+    }
+
+    pub fn from_parts((alloc_id, immutable, shared_ref): (AllocId, bool, bool)) -> Self {
+        let prov = CtfeProvenance::from(alloc_id);
+        if immutable {
+            // This sets both flas, so we don't even have to check `shared_ref`.
```
Comment (fee1-dead) [inline compiler/rustc_middle/src/mir/interpret/pointer.rs:144]:
```suggestion
            // This sets both flags, so we don't even have to check `shared_ref`.
```

File: tests/ui/consts/refs-to-cell-in-final.rs [hunk 2]
```diff
@@ -28,10 +28,8 @@ impl Drop for JsValue {
     fn drop(&mut self) {}
 }
 const UNDEFINED: &JsValue = &JsValue::Undefined;
-//~^ WARNING: mutable pointer in final value of constant
-//~| WARNING: this was previously accepted by the compiler but is being phased out
 
-// In contrast, this one works since it is being promoted.
+// Here's a variant of the above that uses promotion instead of the "outer scope rule" rule.
```
Comment (fee1-dead) [inline tests/ui/consts/refs-to-cell-in-final.rs:32]:
```suggestion
// Here's a variant of the above that uses promotion instead of the "outer scope" rule.
```

**Review by fee1-dead — CHANGES_REQUESTED** [review]

**Review by fee1-dead — APPROVED** [review]
Overall the compiler changes LGTM.

There is the ultimate question of "do we really want to do this". I don't personally like it, but you've probably sat on this for a while. r=me if there is official approval from T-lang.

Though question: is this needed for stabilizing mut refs in consts? The changes look tangential to me.

**Comment by RalfJung** [comment]
> Though question: is this needed for stabilizing mut refs in consts? The changes look tangential to me.

I think it is, as it makes certain things hard errors that one will be able to write on stable with const_mut_refs.

**Comment by RalfJung** [comment]
> There is the ultimate question of "do we really want to do this". I don't personally like it, but you've probably sat on this for a while.

Are you suggesting we should just accept such code and risk the UB, or we should accept the code and make it somehow well-defined?

Anyway, if we want to discuss this we should take it to Zulip.

**Comment by fee1-dead** [comment]
> Are you suggesting we should just accept such code and risk the UB, or we should accept the code and make it somehow well-defined?

Not sure what you're asking. I meant whether this approach (allowing code like this) should be taken to solve the JsValue issue. Happy to clarify more on Zulip if you want.

**Comment by fee1-dead** [comment]
Had more comments so started a thread at https://rust-lang.zulipchat.com/#narrow/stream/146212-t-compiler.2Fconst-eval/topic/const-eval.20interning.3A.20accept.20interior.20mutable.20pointers.20in.20fi

**Comment by RalfJung** [comment]
> > Though question: is this needed for stabilizing mut refs in consts? The changes look tangential to me.
> 
> I think it is, as it makes certain things hard errors that one will be able to write on stable with const_mut_refs.

In writing this I forgot that that's only true for "miri-unleashed" mode. I am not fully trusting the checks that avoid hitting this condition on stable, but I also don't know a concrete gap in those checks -- I just know they are making some pretty subtle assumptions about `StorageLive`/`StorageDead` placement.

File: tests/ui/consts/const-eval/heap/alloc_intrinsic_untyped.rs [hunk 3]
```diff
@@ -1,11 +1,12 @@
+// We unleash Miri here since this test demonstrates code that bypasses the checks against interning
+// mutable pointers, which currently ICEs. Unleashing Miri silence the ICE.
```
Comment (fee1-dead) [inline tests/ui/consts/const-eval/heap/alloc_intrinsic_untyped.rs:2]: I'd like to see a test in `tests/crashes` to track this (to make sure that it does ICE with the current state of this PR)

File: compiler/rustc_const_eval/src/interpret/intern.rs [hunk 4]
```diff
@@ -223,45 +224,59 @@ pub fn intern_const_alloc_recursive<'tcx, M: CompileTimeMachine<'tcx, const_eval
             continue;
         }
 
-        // Crucially, we check this *before* checking whether the `alloc_id`
-        // has already been interned. The point of this check is to ensure that when
-        // there are multiple pointers to the same allocation, they are *all* immutable.
-        // Therefore it would be bad if we only checked the first pointer to any given
-        // allocation.
+        // Ensure that this is is derived from a shared reference. Crucially, we check this *before*
```
Comment (fee1-dead) [inline compiler/rustc_const_eval/src/interpret/intern.rs:227]:
```suggestion
        // Ensure that this is derived from a shared reference. Crucially, we check this *before*
```

File: compiler/rustc_const_eval/src/interpret/intern.rs [hunk 5]
```diff
@@ -223,45 +224,59 @@ pub fn intern_const_alloc_recursive<'tcx, M: CompileTimeMachine<'tcx, const_eval
...
+        // checking whether the `alloc_id` has already been interned. The point of this check is to
+        // ensure that when there are multiple pointers to the same allocation, they are *all*
+        // derived from a shared reference. Therefore it would be bad if we only checked the first
+        // pointer to any given allocation.
         // (It is likely not possible to actually have multiple pointers to the same allocation,
         // so alternatively we could also check that and ICE if there are multiple such pointers.)
+        // See <https://github.com/rust-lang/rust/pull/128543> for why we are checking for "shared
+        // reference" and not "immutable", i.e., for why we are allowed interior-mutable shared
```
Comment (fee1-dead) [inline compiler/rustc_const_eval/src/interpret/intern.rs:235]:
```suggestion
        // reference" and not "immutable", i.e., for why we are allowing interior-mutable shared
```

**Review by fee1-dead — CHANGES_REQUESTED** [review]

**Comment by nikomatsakis** [comment]
@RalfJung I'm curious what would make people think that it's ok to change from one variant to another. The best way I can understand your statement here:

> It's not great to accept such values since people might think that it is legal to mutate them with unsafe code (there is a `Cell`, after all).

...is that because `Cell` in miri "infects" the entire object it's embedded in, they might make this assumption?

I have generally felt that while having `Cell` grow in scope may be a necessity, it's in that grey area that I would still like to call UB, even if the rules we've devised for detecting UB allow it. It seems like *to humans* it's quite easy to see what memory is "enclosed" in a Cell.

**Comment by RalfJung** [comment]
> ...is that because Cell in miri "infects" the entire object it's embedded in, they might make this assumption?

Yes, and not just in Miri -- AFAIK nobody is currently serious pursuing an aliasing model that would "contain" an UnsafeCell inside an enum variant.

> I have generally felt that while having Cell grow in scope may be a necessity, it's in that grey area that I would still like to call UB, even if the rules we've devised for detecting UB allow it (i.e., accept that our "UB state machine" is not going to be complete). It seems like to humans it's quite easy to see what memory is "enclosed" in a Cell.

That is the subject of https://github.com/rust-lang/unsafe-code-guidelines/issues/236. I would like to make progress on const_mut_refs and const_refs_to_cell without having to resolve this very tricky opsem question. So we should not rely on this being UB when we argue for soundness of these features.

**Comment by RalfJung** [comment]
I'll wait for what t-lang thinks before resolving conflicts here.

@pnkfelix since you added the lint I am removing here, I am particularly wondering if you have any comments about this. :)

**Comment by pnkfelix** [comment]
My only comment is sort of a "big picture" one. The lang team spent some time trying to dissect the overall experience here, see [these notes](https://hackmd.io/9Jpc-qoxQPqGcuLkLuFpEw#const-eval-interning-accept-interior-mutable-pointers-in-final-value-rust128543) ...

... and one thing I'm not clear about is: Under your preferred solution, @RalfJung , are we planning to start checking for a class of provenace-like UB, but those checks have not yet been implemented?

I.e. I don't want to fall into the trap of: there's some class of code (call it X) that is UB, but X is currently statically disallowed due to the current rules about interior mutable pointers, and so with PR 128543 we start accepting X, with an intent to reject it once the more sophisticated check is implemented...

**Comment by nikomatsakis** [comment]
OK, we discussed this, and I would like to propose 

@rfcbot fcp merge

However, I also want @RalfJung to confirm that my understanding of the situation is accurate. I believe it comes down to this:

* According to whatever provenance system we create (Tree Borrows, Stack Borrows, etc), `Cell` is considered infectious. This means that if your object (in the C sense) is typed with some type `T` that has a `Cell` embedded anywhere in it, then shared references can at least *potentially* mutate any of its fields (via unsafe code) without UB.
* However, when code seeks to perform a mutation not possible with safe Rust (i.e., mutating a field, including the discriminant, that is outside the scope of the `Cell`), the "borrow permissions" are not the only thing you must consider. The reference could for example point into static memory using a read-only data segment, and that is *always* UB to write. We would not put this value into such a segment if it creates a `Cell` accessible from safe code (e.g., a `JSObject::Value` variant), but we will if there is interior mutability obtained via infection and not actually embedded in the value (e.g., a `JSObject::Undefined` variant). I think this implies that users with unsafe code could also (safely) put `JSObject::Undefined` in some other form of memory segment where writes are disallowed.

I consider this scenario to be fine -- knowing where your pointer points and hence what kind of access permissions exist on that memory is just part of the "correctness contract" when doing a raw-pointer write. Some kinds of raw-pointer writes are always valid (e.g., to `Cell` values that can be obtained via safe code) but other kinds require extra information not encoded in the type.

**Comment by nikomatsakis** [comment]
FML, I don't think this needs such a long list.

@rfcbot fcp cancel

**Comment by nikomatsakis** [comment]
OK, we discussed this, and I would like to propose 

@rfcbot fcp merge

However, I also want @RalfJung to confirm that my understanding of the situation is accurate. I believe it comes down to this:

* According to whatever provenance system we create (Tree Borrows, Stack Borrows, etc), `Cell` is considered infectious. This means that if your object (in the C sense) is typed with some type `T` that has a `Cell` embedded anywhere in it, then shared references can at least *potentially* mutate any of its fields (via unsafe code) without UB.
* However, when code seeks to perform a mutation not possible with safe Rust (i.e., mutating a field, including the discriminant, that is outside the scope of the `Cell`), the "borrow permissions" are not the only thing you must consider. The reference could for example point into static memory using a read-only data segment, and that is *always* UB to write. We would not put this value into such a segment if it creates a `Cell` accessible from safe code (e.g., a `JSObject::Value` variant), but we will if there is interior mutability obtained via infection and not actually embedded in the value (e.g., a `JSObject::Undefined` variant). I think this implies that users with unsafe code could also (safely) put `JSObject::Undefined` in some other form of memory segment where writes are disallowed.

I consider this scenario to be fine -- knowing where your pointer points and hence what kind of access permissions exist on that memory is just part of the "correctness contract" when doing a raw-pointer write. Some kinds of raw-pointer writes are always valid (e.g., to `Cell` values that can be obtained via safe code) but other kinds require extra information not encoded in the type.

**Comment by RalfJung** [comment]
Sorry that the problem statement was apparently not sufficiently clearly stated! I should have written another essay, it seems. ;)

@scottmcm 

> ... and one thing I'm not clear about is: Under your preferred solution, @RalfJung , are we planning to start checking for a class of provenace-like UB, but those checks have not yet been implemented?

I'm afraid I don't understand the question.

> I.e. I don't want to fall into the trap of: there's some class of code (call it X) that is UB, but X is currently statically disallowed due to the current rules about interior mutable pointers, and so with PR 128543 we start accepting X, with an intent to reject it once the more sophisticated check is implemented...

The code I am most concerned about having UB when it shouldn't is [this](https://github.com/rust-lang/unsafe-code-guidelines/issues/493). It is entirely unaffected by this PR -- it never triggered the lint that this PR removes. The lint was ineffective at pointing at the actually problematic cases.

So... I don't think this PR can be part of that trap? But I also don't think I fully understand your concern.

@nikomatsakis 

> According to whatever provenance system we create (Tree Borrows, Stack Borrows, etc), Cell is considered infectious. This means that if your object (in the C sense) is typed with some type T that has a Cell embedded anywhere in it, then shared references can at least potentially mutate any of its fields (via unsafe code) without UB.

No, not quite. In Tree Borrows, Cell is fully infectious. In Stacked Borrows, Cell infects surrounding enums and unions, but the mutability of fields in of product types (structs, tuples, closures, ...) are tracked precisely. One day I'll try to work out a variant of Tree Borrows that does this, just so that option is on the table, but I wanted to first finish working out basic Tree Borrows. But there is fairly broad agreement that Cell will be *somewhat* infectious, since making Cell fully precise inside enums requires doing extra reads to determine the active enum variant and many people, including myself, think that would be a bad idea.

> However, when code seeks to perform a mutation not possible with safe Rust (i.e., mutating a field, including the discriminant, that is outside the scope of the Cell), the "borrow permissions" are not the only thing you must consider. The reference could for example point into static memory using a read-only data segment, and that is always UB to write. We would not put this value into such a segment if it creates a Cell accessible from safe code (e.g., a JSObject::Value variant), but we will if there is interior mutability obtained via infection and not actually embedded in the value (e.g., a JSObject::Undefined variant).

Yes, that sounds correct. It is an interesting new way to describe the situation, thanks for that perspective.

> I think this implies that users with unsafe code could also (safely) put JSObject::Undefined in some other form of memory segment where writes are disallowed.

It is definitely okay for unsafe code to put `JSObject::Undefined` in read-only memory and give that to safe code. My proposal would be that we let users write this explicitly as `const { &JSObject::Undefined }`.

The concern [here](https://github.com/rust-lang/unsafe-code-guidelines/issues/493) is unsafe code *thinking* it put `JSObject::Undefined` into mutable memory (as typically the memory of `let`-bound variables is mutable... though that is also a somewhat contentious open question), because it didn't ask for read-only memory, but then the compiler decided to use read-only memory anyway. That's what I would really like to lint against, but the current lint does not trigger in these cases, and I don't know how to write a lint that triggers in these cases. (It likely requires running the borrow checker twice.)

To give some context here:
My position on this lint and the entire question surrounding https://github.com/rust-lang/rust/issues/121610 has changed over the last half a year. When I wrote https://github.com/rust-lang/rust/pull/119044, I still thought we should reject such code. But I didn't realize the extent of what we already accept on stable, so my original plan was just completely incompatible with reality. That plan also would not have provided a way for programmers to easily say "yes please put this in read-only memory even if that rules out mutation that would otherwise have been permitted by the borrow model". So when the original plan I had with #119044 got in [contact](https://github.com/rust-lang/rust/issues/121610) with [reality](https://github.com/rust-lang/unsafe-code-guidelines/issues/493), it changed to a new plan: let's make it so that programmers *can* explicitly ask for things to be put in read-only memory even if that rules out mutation that would otherwise have been permitted by the borrow model. Let's use the existing syntax,  `const { &JSObject::Undefined }`, for this -- it seems like the obvious way to express this. However, right now, that code actually triggers a lint! (And as mentioned above, the actually problematic code does not trigger the lint.) So, let's get rid of that lint. Also, maybe, hopefully, long-term let's reduce the number of cases where we put things *implicitly* into read-only memory -- that would resolve https://github.com/rust-lang/unsafe-code-guidelines/issues/493 and is tracked at https://github.com/rust-lang/rust/issues/124328.

**Comment by tmandry** [comment]
@rfcbot reviewed

**Comment by RalfJung** [comment]
Based on [this](https://github.com/rust-lang/rust/pull/128543#pullrequestreview-2244120709)
@bors r=fee1-dead

File: compiler/rustc_const_eval/src/interpret/intern.rs [hunk 6]
```diff
@@ -223,45 +224,59 @@ pub fn intern_const_alloc_recursive<'tcx, M: CompileTimeMachine<'tcx, const_eval
...
+            let dangling = !is_already_global && !ecx.memory.alloc_map.contains_key(&alloc_id);
+            if !dangling {
+                // Found a mutable reference inside a const where inner allocations should be
+                // immutable.
+                if !ecx.tcx.sess.opts.unstable_opts.unleash_the_miri_inside_of_you {
+                    span_bug!(
+                        ecx.tcx.span,
+                        "the static const safety checks accepted mutable references they should not have accepted"
+                    );
+                }
```
Comment (matthiaskrgr) [inline compiler/rustc_const_eval/src/interpret/intern.rs:268]: this one is reachable as well but from what I have seen all the snippets involve `intrinsics::const_allocate()` abuse :shrug: 
```rust
#![feature(const_heap)]
const BAR: *mut i32 = unsafe { std::intrinsics::const_allocate(4, 4) as *mut i32 };
```

Comment (RalfJung) [reply compiler/rustc_const_eval/src/interpret/intern.rs:268]: Yeah, I know -- I made the test that reaches this set "unleash miri" to keep it working.

const_heap has a bunch of unsolved open problems, this is just one of them. If this is at some point the *last* open problem, we can consider removing the check here, since it is anyway supposed to be just a safety net. But meanwhile having this ICE will help us ensure that just using mutable references, on cannot cause problems here.
