### PR TITLE
Give better diagnostic when using a private tuple struct constructor

### LINKED ISSUE #75907: [diagnostics] Attempting to destructure a private field in a public tuple struct yields confusing error message
_This is the destructure counterpart of https://github.com/rust-lang/rust/issues/75906_

## Overview

Attempting to destructure a private field in a public tuple struct yields a confusing error message. Given the following code:

```rust
mod foo {
    pub(crate) struct Bar{inner: u8}
    
    pub(crate) fn make_bar() -> Bar {
        Bar{ inner: 12 }
    }
}

use foo::{Bar, make_bar};

fn main() {
    let Bar{ inner } = make_bar();
    dbg!(inner);
}
```

The following error is generated:

```txt
error[E0451]: field `inner` of struct `foo::Bar` is private
  --> src/main.rs:12:14
   |
12 |     let Bar{ inner } = make_bar();
   |              ^^^^^ private field
```

This seems quite helpful: some field is private, so we can infer we probably should make it public instead. However when we convert the code to a tuple struct things become more confusing:

```rust
mod foo {
    pub(crate) struct Bar(u8);
    
    pub(crate) fn make_bar() -> Bar {
        Bar(12)
    }
}

use foo::{Bar, make_bar};

fn main() {
    let Bar(y) = make_bar();
}
```
The following error is generated:

```txt
error[E0532]: expected tuple struct or tuple variant, found struct `Bar`
  --> src/main.rs:12:9
   |
12 |     let Bar(y) = make_bar();
   |         ^^^ constructor is not visible here due to private fields
```

The error message itself doesn't point us to the problem (`expected tuple struct or tuple variant, found struct Bar`), and mentioning a constructor in the code block isn't helpful either. After all we're not trying to construct anything; we're trying to _destruct_.

## Proposed solution

When accessing a private field in a tuple struct rustc already generates pretty good errors:

```rust
    let x = make_bar();
    dbg!(x.0);
```

```txt
error[E0616]: field `0` of struct `foo::Bar` is private
  --> src/main.rs:13:12
   |
13 |     dbg!(x.0);
   |            ^ private field
```

When destructuring tuple structs these errors would be accurate as well:

```txt
error[E0616]: field `0` of struct `foo::Bar` is private
  --> src/main.rs:12:9
   |
12 |     let Bar(y) = make_bar();
   |             ^ private field
```

We could take it even further and suggest a fix for this as well:

```txt
error[E0616]: field `0` of struct `foo::Bar` is private
  --> src/main.rs:12:9
   |
12 |     let Bar(y) = make_bar();
   |             ^ private field
   |             |
   |             help: declare the struct's fields as public: `struct Bar(pub(crate) u8);`
```

## Conclusion

In this issue I've shown an incorrect error message that occurs when attempting to destructure a private field in a tuple-struct, and made suggestions on how we can improve this.

I hope this is helpful. Thanks!

### PR DESCRIPTION
**Pull request by guswynn**
Fixes #75907 

Some notes:
1. This required some deep changes, including removing a Copy impl for PatKind. If some tests fail, I would still appreciate review on the overall approach
2. this only works with basic patterns (no wildcards for example), and fails if there is any problems getting the visibility of the fields (i am not sure what the failure that can happen in resolve_visibility_speculative, but we check the length of our fields in both cases against each other, so if anything goes wrong, we fall back to the worse error. This could be extended to more patterns
3. this does not yet deal with #75906, but I believe it will be similar
4. let me know if you want more tests
5. doesn't yet at the suggestion that @yoshuawuyts suggested at the end of their issue, but that could be added relatively easily (i believe)

### CODE REVIEW

**Comment by jyn514** [comment]
I'd be interested whether this affects perf.

**Comment by guswynn** [comment]
@jyn514 I think the clones are the same as the original Copy's, but not sure, is there a way to queue a perf check?

**Comment by jyn514** [comment]
Yes, but I'd prefer not to until someone familiar with this part of the compiler agrees this is the right approach (the perf server has a tendency to fall behind master).

**Comment by Aaron1011** [comment]
There's currently only one job in the perf queue, so I think it should be fine. Also, the total perf job running time was decreased last month in https://github.com/rust-lang/rustc-perf/pull/740, and I haven't seen the perf queue growing out of control since them.

@bors try @rust-timer queue

**Comment by jyn514** [comment]
Oh nice, I didn't realize perf was no longer running script-servo :)

**Comment by jyn514** [comment]
Perf results look like noise, it says max-rss went down but since you _added_ more fields here that can't be right.

File: compiler/rustc_resolve/src/late.rs [hunk 1]
```diff
@@ -175,7 +175,7 @@ crate enum AliasPossibility {
     Maybe,
 }
 
-#[derive(Copy, Clone, Debug)]
+#[derive(Clone, Debug)]
```
[the remark this answers is not in the document]
Comment (guswynn) [reply compiler/rustc_resolve/src/late.rs:178]: Would I need to add an arena to ResolverArenas?

**Comment by petrochenkov** [comment]
This PR hides the correct error that attempts to teach you the actual language rules ("private fields make the constructor private") and masks it with something plausibly looking, but not really correct.

File: compiler/rustc_resolve/src/late.rs (hunk 1 above)
[the remark this answers is not in the document]
Comment (petrochenkov) [reply compiler/rustc_resolve/src/late.rs:178]: Yes.

**Comment by petrochenkov** [comment]
It would be better to keep the current primary message and add a note to it with a multi-span pointing to those private fields that it mention.

File: compiler/rustc_resolve/src/late.rs (hunk 1 above)
[the remark this answers is not in the document]
Comment (petrochenkov) [reply compiler/rustc_resolve/src/late.rs:178]: After looking at the PR in more detail, `PathSource::TupleStruct` doesn't need to be changed at all.

File: compiler/rustc_resolve/src/lib.rs [hunk 2]
```diff
@@ -999,7 +999,7 @@ pub struct Resolver<'a> {
 
     /// Table for mapping struct IDs into struct constructor IDs,
     /// it's not used during normal resolution, only for better error reporting.
-    struct_constructors: DefIdMap<(Res, ty::Visibility)>,
+    struct_constructors: DefIdMap<(Res, ty::Visibility, Vec<(ast::StructField, ty::Visibility)>)>,
```
Comment (petrochenkov) [inline compiler/rustc_resolve/src/lib.rs:1002]:
```suggestion
    struct_constructors: DefIdMap<(Res, Vec<(ty::Visibility, Span)>)>,
```
The more detailed field visibilities make the constructor visibility redundant, and we don't need the whole `ast::StructField`, only its span.

Comment (guswynn) [reply compiler/rustc_resolve/src/lib.rs:1002]: Isn't that the span of the definition of the field? We want the span of the actual pattern, which is why I add the pattern idents to the pattern source

Comment (petrochenkov) [reply compiler/rustc_resolve/src/lib.rs:1002]: Ah, right, so we can just use `Vec<ty::Visibility>`.

File: compiler/rustc_resolve/src/late.rs (hunk 1 above)
[the remark this answers is not in the document]
Comment (guswynn) [reply compiler/rustc_resolve/src/late.rs:178]: How can I avoid adding this info?

[the remark this answers is not in the document]
Comment (petrochenkov) [reply compiler/rustc_resolve/src/late.rs:178]: That's a consequence of me mixing definition and use sites (https://github.com/rust-lang/rust/pull/76499#discussion_r485880451).
`PathSource::TupleStruct` does need to be extended with a vector of `Span`s (allocated on the resolver arena).

The message I'm suggesting in https://github.com/rust-lang/rust/pull/76499#issuecomment-689779913 will look roughly like
```
error[E0451]: constructor is not visible here due to private fields
  --> $DIR/issue-75907.rs:14:16
   |
LL |     let Bar(x, y) = make_bar();
   |             ^  ^ field 0 and 1 are private
```
with the `^  ^` pointing to spans kept in `PathSource::TupleStruct`.

**Comment by guswynn** [comment]
Genuinely astounded that adding 'a: 'ast bounds in 3 places resolved the errors i got, that said, i suppose nothing lives longer than the ast

File: compiler/rustc_resolve/src/late/diagnostics.rs [hunk 3]
```diff
@@ -744,15 +744,40 @@ impl<'a> LateResolutionVisitor<'a, '_, '_> {
...
+                                    }
+                                }).collect();
+                                // Extra check to be sure
+                                if non_visible_spans.len() > 0 {
+                                    let first_span = non_visible_spans[0];
+                                    err.set_span(non_visible_spans);
+                                    err.span_label(first_span, "private field");
+                                    err.set_primary_message(
+                                    "constructor is not visible here due to private fields".to_string(),
+                                    );
```
Comment (guswynn) [inline compiler/rustc_resolve/src/late/diagnostics.rs:769]: this gives the weird format

   ^ ^
   |    message

@petrochenkov how do I get your suggestion:

   ^ ^ message

Comment (petrochenkov) [reply compiler/rustc_resolve/src/late/diagnostics.rs:769]: I wrote `^ ^ message` from memory, so it probably won't look like that, but the goal is to use `span_labels` or `span_note` which accept multiple spans, and they will lay out the diagnostics in some way that is optimal from their point of view.

Comment (guswynn) [reply compiler/rustc_resolve/src/late/diagnostics.rs:769]: ok this is using span_label so I think its about as optimal as it can get, but I will check in wg-diagnostics on zulip if there is a better way

Comment (jyn514) [reply compiler/rustc_resolve/src/late/diagnostics.rs:769]: Maybe instead of `set_primary_message` use `span_note`? https://doc.rust-lang.org/nightly/nightly-rustc/rustc_errors/struct.Diagnostic.html#method.span_note

Comment (guswynn) [reply compiler/rustc_resolve/src/late/diagnostics.rs:769]: ok this is using span_label so I think its about as optimal as it can get, but I will check in wg-diagnostics on zulip if there is a better way

Comment (guswynn) [reply compiler/rustc_resolve/src/late/diagnostics.rs:769]: @jyn514 span_note adds a new diagnostic with a top level message

File: compiler/rustc_resolve/src/late.rs [hunk 4]
```diff
@@ -1539,8 +1539,24 @@ impl<'a, 'b, 'ast> LateResolutionVisitor<'a, 'b, 'ast> {
...
+                PatKind::TupleStruct(ref path, ref sub_patterns) => {
+                    let mut ident_bindings = vec![];
+                    for p in sub_patterns {
+                        if let PatKind::Ident(_, ref ident, None) = p.kind {
+                            ident_bindings.push(ident.clone())
+                        } else {
+                            // NOTE: Only handles patterns of the form
+                            // TupleStruct(a, b, ref c)
+                            ident_bindings.clear();
+                            break;
```
Comment (estebank) [inline compiler/rustc_resolve/src/late.rs:1551]: It seems to me that instead of trying to do it only for idents you can store either the patterns themselves or their spans, right? Trying to destructure `Foo(Bar(Baz(())))` when the field in Foo is not visible should be an error.

File: compiler/rustc_resolve/src/late/diagnostics.rs (hunk 3 above)
Comment (estebank) [reply compiler/rustc_resolve/src/late/diagnostics.rs:769]: It seems to me that only using a single call to span label for each non-visible field would be enough to address the issue. That being said you can create a new MultiSpan, use push_label on it to have span messages to them in the subwindow and then a span_note call with that MultiSpan that will have a message. The API is a bit involved, but it wasn't originally intended for this.

Comment (estebank) [reply compiler/rustc_resolve/src/late/diagnostics.rs:769]: To clarify, the `set_primary_message` is not really intended to be used, so if we can improve things with a span_note, lets do that.

File: compiler/rustc_resolve/src/late.rs (hunk 4 above)
Comment (guswynn) [reply compiler/rustc_resolve/src/late.rs:1551]: I can see if this is very difficult to add

**Comment by guswynn** [comment]
@estebank do you think it will be not too noisy to add a span_label for every private field? Other than question, your idea to make a multispan from the span's, label them, add a note, and set the span and primary message seems good to me!

File: compiler/rustc_resolve/src/lib.rs [hunk 5]
```diff
@@ -999,7 +999,8 @@ pub struct Resolver<'a> {
 
     /// Table for mapping struct IDs into struct constructor IDs,
     /// it's not used during normal resolution, only for better error reporting.
-    struct_constructors: DefIdMap<(Res, ty::Visibility)>,
+    /// Also includes of list of each fields visibility
+    struct_constructors: DefIdMap<(Res, ty::Visibility, Vec<ty::Visibility>)>,
```
Comment (petrochenkov) [inline compiler/rustc_resolve/src/lib.rs:1003]:
```suggestion
    struct_constructors: DefIdMap<(Res, Vec<ty::Visibility>)>,
```
The more detailed field visibilities make the constructor visibility redundant.

File: compiler/rustc_resolve/src/late/diagnostics.rs (hunk 3 above)
Comment (petrochenkov) [reply compiler/rustc_resolve/src/late/diagnostics.rs]: The choice here is probably between `span_label` for the first private field and `span_labels` for all private fields.
`span_note` will look worse in the context of this specific diagnostic, and `set_primary_message` is not necessary, you certainly can construct the error with an immediate message here.

File: compiler/rustc_resolve/src/build_reduced_graph.rs [hunk 6]
```diff
@@ -796,6 +796,8 @@ impl<'a, 'b> BuildReducedGraphVisitor<'a, 'b> {
                         vis
                     };
 
+                    let mut ret_fields = vec![];
```
Comment (petrochenkov) [inline compiler/rustc_resolve/src/build_reduced_graph.rs:799]:
```suggestion
                    let mut field_visibilities = Vec::with_capacity(vdata.fields().len());
```

File: compiler/rustc_resolve/src/build_reduced_graph.rs [hunk 7]
```diff
@@ -805,14 +807,15 @@ impl<'a, 'b> BuildReducedGraphVisitor<'a, 'b> {
                             if ctor_vis.is_at_least(field_vis, &*self.r) {
                                 ctor_vis = field_vis;
                             }
+                            ret_fields.push(field_vis);
                         }
```
Comment (petrochenkov) [inline compiler/rustc_resolve/src/build_reduced_graph.rs:811]:
```suggestion
                    let field_vis = self.resolve_visibility_speculative(&field.vis, true).unwrap_or(ty::Visibility::Public);
                    field_visibilities.push(field_vis);
                    if ctor_vis.is_at_least(field_vis, &*self.r) {
                        ctor_vis = field_vis;
                    }
```
The length of `field_visibilities` should ideally match the number of fields to be robust against other resolution errors, and here it's easy to make sure that they match.

File: compiler/rustc_resolve/src/late.rs [hunk 8]
```diff
@@ -197,7 +197,7 @@ impl<'a> PathSource<'a> {
     fn namespace(self) -> Namespace {
         match self {
             PathSource::Type | PathSource::Trait(_) | PathSource::Struct => TypeNS,
-            PathSource::Expr(..) | PathSource::Pat | PathSource::TupleStruct(_) => ValueNS,
+            PathSource::Expr(..) | PathSource::Pat | PathSource::TupleStruct(_, _) => ValueNS,
```
Comment (petrochenkov) [inline compiler/rustc_resolve/src/late.rs:200]:
```suggestion
            PathSource::Expr(..) | PathSource::Pat | PathSource::TupleStruct(..) => ValueNS,
```
Here and in other places.

File: compiler/rustc_resolve/src/late.rs [hunk 9]
```diff
@@ -1539,8 +1539,18 @@ impl<'a, 'b, 'ast> LateResolutionVisitor<'a, 'b, 'ast> {
...
+                PatKind::TupleStruct(ref path, ref sub_patterns) => {
+                    let pattern_spans: Vec<Span> =
+                        sub_patterns.iter().map(|p| p.span.clone()).collect();
+                    self.smart_resolve_path(
+                        pat.id,
+                        None,
+                        path,
+                        PathSource::TupleStruct(
+                            pat.span,
+                            self.r.arenas.alloc_pattern_spans(&pattern_spans),
```
Comment (petrochenkov) [inline compiler/rustc_resolve/src/late.rs:1551]:
```suggestion
                            self.r.arenas.alloc_pattern_spans(sub_patterns.iter().map(|p| p.span)),
```
You can feed an iterator directly to `alloc_pattern_spans`.

File: compiler/rustc_resolve/src/lib.rs [hunk 10]
```diff
@@ -1067,6 +1069,9 @@ impl<'a> ResolverArenas<'a> {
     fn alloc_ast_paths(&'a self, paths: &[ast::Path]) -> &'a [ast::Path] {
         self.ast_paths.alloc_from_iter(paths.iter().cloned())
     }
+    fn alloc_pattern_spans(&'a self, spans: &[Span]) -> &'a [Span] {
```
Comment (petrochenkov) [inline compiler/rustc_resolve/src/lib.rs:1072]:
```suggestion
    fn alloc_pattern_spans(&'a self, spans: impl Iterator<Item = Span>) -> &'a [Span] {
```

File: compiler/rustc_resolve/src/late/diagnostics.rs [hunk 11]
```diff
@@ -744,15 +744,50 @@ impl<'a> LateResolutionVisitor<'a, '_, '_> {
                 }
             }
             (Res::Def(DefKind::Struct, def_id), _) if ns == ValueNS => {
-                if let Some((ctor_def, ctor_vis)) = self.r.struct_constructors.get(&def_id).cloned()
+                if let Some((ctor_def, ctor_vis, fields)) =
+                    self.r.struct_constructors.get(&def_id).cloned()
                 {
                     let accessible_ctor =
                         self.r.is_accessible_from(ctor_vis, self.parent_scope.module);
                     if is_expected(ctor_def) && !accessible_ctor {
```
Comment (petrochenkov) [inline compiler/rustc_resolve/src/late/diagnostics.rs:752]: The `accessible_ctor` check can be eliminated if you are already checking the fields.

File: compiler/rustc_resolve/src/late/diagnostics.rs [hunk 12]
```diff
@@ -744,15 +744,50 @@ impl<'a> LateResolutionVisitor<'a, '_, '_> {
                 }
             }
             (Res::Def(DefKind::Struct, def_id), _) if ns == ValueNS => {
-                if let Some((ctor_def, ctor_vis)) = self.r.struct_constructors.get(&def_id).cloned()
+                if let Some((ctor_def, ctor_vis, fields)) =
```
Comment (petrochenkov) [inline compiler/rustc_resolve/src/late/diagnostics.rs:747]: You can first obtain the list or private field spans for the `def_id`.
If the list is not empty, then "constructor is not visible here due to private fields" can be reported, otherwise we need to fallback to `bad_struct_syntax_suggestion` below.

File: compiler/rustc_resolve/src/lib.rs (hunk 5 above)
Comment (guswynn) [reply compiler/rustc_resolve/src/lib.rs:1003]: I am not sure how I'd handle this case: https://github.com/rust-lang/rust/blob/e3ac611b828d579944709e9bf6fe2aede263a7af/compiler/rustc_resolve/src/build_reduced_graph.rs#L970

(also this seems to suggest resolution happens differently across crates? is there a way I can do a ui test with 2 crates?

File: compiler/rustc_resolve/src/late/diagnostics.rs (hunk 3 above)
Comment (guswynn) [reply compiler/rustc_resolve/src/late/diagnostics.rs]: I am not sure I understand, what do you mean "i can can construct the error with an immediate message here"?

File: compiler/rustc_resolve/src/lib.rs (hunk 5 above)
Comment (petrochenkov) [reply compiler/rustc_resolve/src/lib.rs:1003]: Ah, I see.
Collecting field visibilities here would require decoding them from other crate's metadata, which is better avoided.
It's ok to keep the constructor visibility here then.

File: compiler/rustc_resolve/src/late/diagnostics.rs (hunk 3 above)
Comment (petrochenkov) [reply compiler/rustc_resolve/src/late/diagnostics.rs]: You can disregard this message entirely, I didn't look where the `err` was constructed.

**Comment by guswynn** [comment]
This doesn't work cross-crate :((( I added a test that shows that

File: compiler/rustc_resolve/src/build_reduced_graph.rs (hunk 6 above)
Comment (petrochenkov) [reply compiler/rustc_resolve/src/build_reduced_graph.rs]: Not addressed yet.

File: compiler/rustc_resolve/src/build_reduced_graph.rs (hunk 7 above)
Comment (petrochenkov) [reply compiler/rustc_resolve/src/build_reduced_graph.rs:815]: Both `push` and `if ctor_vis.is_at_least ...` can be moved to outside of the `resolve_visibility_speculative` condition, as the suggestion snippet shows.

File: compiler/rustc_resolve/src/late.rs (hunk 8 above)
Comment (petrochenkov) [reply compiler/rustc_resolve/src/late.rs]: >and in other places.

Not addressed yet.

**Comment by petrochenkov** [comment]
I'll try to check what can be done in the cross-crate case, but it's better done in a separate PR.
We should be able to decode fields and their visibilities from other crates if necessary for error reporting, but it should not be done on happy path (if no errors are reported).

**Comment by estebank** [comment]
@guswynn I think that the new output looks reasonable and informative.

> I'll try to check what can be done in the cross-crate case, but it's better done in a separate PR.

+100

**Comment by petrochenkov** [comment]
r=me after addressing the remaining nits (https://github.com/rust-lang/rust/pull/76499#discussion_r486660519, https://github.com/rust-lang/rust/pull/76499#discussion_r486661457) and squashing commits.

**Comment by guswynn** [comment]
@petrochenkov thank you so much for the detailed review and help on the most complicated rust-lang/rust pr I have ever done!

**Comment by petrochenkov** [comment]
Thanks!
@bors r+
