### PR TITLE
Try normalizing types without RevealAll in ParamEnv in MIR validation

### LINKED ISSUE #99866: broken MIR in Item (nightly)
### Code

```Rust
#[derive(Debug)]
pub struct HalSetLayouts {
    vertex_layout: <B as hal::Backend>::DescriptorSetLayout,
    fragment_layout: <B as hal::Backend>::DescriptorSetLayout,
    fragment_sampler_layout: <B as hal::Backend>::DescriptorSetLayout,
}

impl HalSetLayouts {
    fn iter<DSL>(&self) -> impl ExactSizeIterator<Item = &DSL> + '_
    where
        // rust 1.37 fails to typecheck `iter` without this. This is fixed in nightly.
        B: hal::Backend<DescriptorSetLayout = DSL>,
        DSL: std::fmt::Debug + Send + Sync + 'static,
    {
        std::iter::once(&self.vertex_layout)
            .chain(std::iter::once(&self.fragment_layout))
            .chain(std::iter::once(&self.fragment_sampler_layout))
            .exact(3)
    }
}
```

### Meta

`rustc --version --verbose`:
```
rustc 1.64.0-nightly (2643b1646 2022-07-27)
binary: rustc
commit-hash: 2643b16468fda787470340890212591d8bc832b7
commit-date: 2022-07-27
host: x86_64-apple-darwin
release: 1.64.0-nightly
LLVM version: 14.0.6
```

### Error output

```
error: internal compiler error: no errors encountered even though `delay_span_bug` issued

error: internal compiler error: broken MIR in Item(WithOptConstParam { did: DefId(0:3021 ~ renderer[c01e]::shader::{impl#11}::iter), const_param_did: None }) (end of phase transition to Optimized) at bb0[0]:
                                Field projection `(*_1).field[0]` specified type `DSL`, but actual type is <gfx_backend_metal::Backend as gfx_hal::Backend>::DescriptorSetLayout
   --> brainstorm/src/renderer/src/shader.rs:642:25
    |
642 |         std::iter::once(&self.vertex_layout)
    |                         ^^^^^^^^^^^^^^^^^^^
    |
    = note: delayed at compiler/rustc_const_eval/src/transform/validate.rs:129:36

error: internal compiler error: broken MIR in Item(WithOptConstParam { did: DefId(0:3021 ~ renderer[c01e]::shader::{impl#11}::iter), const_param_did: None }) (end of phase transition to Optimized) at bb1[0]:
                                Field projection `(*_1).field[1]` specified type `DSL`, but actual type is <gfx_backend_metal::Backend as gfx_hal::Backend>::DescriptorSetLayout
   --> brainstorm/src/renderer/src/shader.rs:643:36
    |
643 |             .chain(std::iter::once(&self.fragment_layout))
    |                                    ^^^^^^^^^^^^^^^^^^^^^
    |
    = note: delayed at compiler/rustc_const_eval/src/transform/validate.rs:129:36

error: internal compiler error: broken MIR in Item(WithOptConstParam { did: DefId(0:3021 ~ renderer[c01e]::shader::{impl#11}::iter), const_param_did: None }) (end of phase transition to Optimized) at bb3[0]:
                                Field projection `(*_1).field[2]` specified type `DSL`, but actual type is <gfx_backend_metal::Backend as gfx_hal::Backend>::DescriptorSetLayout
   --> brainstorm/src/renderer/src/shader.rs:644:36
    |
644 |             .chain(std::iter::once(&self.fragment_sampler_layout))
    |                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: delayed at compiler/rustc_const_eval/src/transform/validate.rs:129:36

```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
thread 'rustc' panicked at 'Box<dyn Any>', compiler/rustc_errors/src/lib.rs:1426:13
stack backtrace:
   0: std::panicking::begin_panic::<rustc_errors::ExplicitBug>
   1: std::panic::panic_any::<rustc_errors::ExplicitBug>
   2: <rustc_errors::HandlerInner as core::ops::drop::Drop>::drop
   3: core::ptr::drop_in_place::<rustc_session::parse::ParseSess>
   4: <alloc::rc::Rc<rustc_session::session::Session> as core::ops::drop::Drop>::drop
   5: core::ptr::drop_in_place::<rustc_interface::interface::Compiler>
   6: rustc_span::with_source_map::<core::result::Result<(), rustc_errors::ErrorGuaranteed>, rustc_interface::interface::create_compiler_and_run<core::result::Result<(), rustc_errors::ErrorGuaranteed>, rustc_driver::run_compiler::{closure#1}>::{closure#1}>
   7: rustc_interface::interface::create_compiler_and_run::<core::result::Result<(), rustc_errors::ErrorGuaranteed>, rustc_driver::run_compiler::{closure#1}>
   8: <scoped_tls::ScopedKey<rustc_span::SessionGlobals>>::set::<rustc_interface::interface::run_compiler<core::result::Result<(), rustc_errors::ErrorGuaranteed>, rustc_driver::run_compiler::{closure#1}>::{closure#0}, core::result::Result<(), rustc_errors::ErrorGuaranteed>>
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

</p>
</details>

This came from a workaround for what seems to be an old compiler bug. removing the workaround gets ride of the ICE:

```Rust
#[derive(Debug)]
pub struct HalSetLayouts {
    vertex_layout: <B as hal::Backend>::DescriptorSetLayout,
    fragment_layout: <B as hal::Backend>::DescriptorSetLayout,
    fragment_sampler_layout: <B as hal::Backend>::DescriptorSetLayout,
}

impl HalSetLayouts {
    fn iter(
        &self,
    ) -> impl ExactSizeIterator<Item = &<B as hal::Backend>::DescriptorSetLayout> + '_ {
        std::iter::once(&self.vertex_layout)
            .chain(std::iter::once(&self.fragment_layout))
            .chain(std::iter::once(&self.fragment_sampler_layout))
            .exact(3)
    }
}
```

### PR DESCRIPTION
**Pull request by Noratrieb**
Before, the MIR validator used RevealAll in its ParamEnv for type
checking. This could cause false negatives in some cases due to
RevealAll ParamEnvs not always use all predicates as expected here.

Since some MIR passes like inlining use RevealAll as well, keep using
it in the MIR validator too, but when it fails usign RevealAll, also
try the check without it, to stop false negatives.

Fixes #99866

cc @compiler-errors who nicely helped me on zulip

### CODE REVIEW

File: compiler/rustc_const_eval/src/transform/validate.rs [hunk 1]
```diff
@@ -183,16 +183,29 @@ impl<'a, 'tcx> TypeChecker<'a, 'tcx> {
...
         }
+
+        let try_equal_with_param_env = |param_env| {
+            let src = self.tcx.normalize_erasing_regions(param_env, src);
+            let dest = self.tcx.normalize_erasing_regions(param_env, dest);
+            // Type-changing assignments can happen when subtyping is used. While
+            // all normal lifetimes are erased, higher-ranked types with their
+            // late-bound lifetimes are still around and can lead to type
+            // differences. So we compare ignoring lifetimes.
+            equal_up_to_regions(self.tcx, param_env, src, dest)
```
Comment (compiler-errors) [inline compiler/rustc_const_eval/src/transform/validate.rs:194]: equal up to regions already calls normalize I think -- those normalize calls can probably be removed and the `equal_up_to_regions` call can be used instead?

Comment (Nilstrieb) [reply compiler/rustc_const_eval/src/transform/validate.rs]: yes, it does already

File: compiler/rustc_const_eval/src/transform/validate.rs [hunk 2]
```diff
@@ -183,16 +183,24 @@ impl<'a, 'tcx> TypeChecker<'a, 'tcx> {
...
         // late-bound lifetimes are still around and can lead to type
         // differences. So we compare ignoring lifetimes.
-        equal_up_to_regions(self.tcx, param_env, src, dest)
+
+        // First, try with reveal_all. This might not work in some cases, as the predicates
+        // can be cleared in reveal_all mode. We try the reveal first anyways as it is used
+        // by some other passes like inlining as well.
+        let param_env = self.param_env.with_reveal_all_normalized(self.tcx);
+        let result = equal_up_to_regions(self.tcx, param_env, src, dest);
+        if result {
```
Comment (oli-obk) [inline compiler/rustc_const_eval/src/transform/validate.rs:198]: The extra variable is not necessary

```suggestion
        if equal_up_to_regions(self.tcx, param_env, src, dest) {
```

**Comment by oli-obk** [comment]
r=me with style nit

**Comment by Nilstrieb** [comment]
@oli-obk I fixed it (hopefully CI passes)

**Comment by RalfJung** [comment]
Is it possible that this caused https://github.com/rust-lang/rust/issues/101344 ?

**Comment by tmandry** [comment]
We're seeing a related-looking ICE on Fuchsia that I think is likely caused by this PR (none of the other changes in #101333 seem to be likely candidates). https://github.com/rust-lang/rust/issues/101344#issuecomment-1235974564
