### PR TITLE
Report `CONST_ERR` lint in external macros

### LINKED ISSUE #61058: external macros don't evaluate panicking consts when crate-local ones do.
I have a proc macro crate which produces a panicking constant in its generate code.

For some reason the constant outputed by the proc-macro doesn't get evaluated in `cargo check`,even though it gets evaluated when the macro is manually expanded.

This is the conversation that motivated me to write this issue:https://github.com/dtolnay/case-studies/pull/6

I've put all the code [in this repository](https://github.com/rodrimati1992/const_panic_issue).

All of these were tried using the current stable.

Commands to run:
```
git clone https://github.com/rodrimati1992/const_panic_issue.git
cd ./const_panic_issue/using_const_panic/
cargo check --bin with_proc_macro
cargo check --bin manually_expanded
cargo check --bin with_internal_macro_rules
cargo check --bin with_external_macro_rules
```

### With a proc macro

`const_panic_proc_macro` crate:

```rust
use proc_macro::TokenStream;
use quote::quote;

#[proc_macro]
pub fn const_panicking(_input: TokenStream) -> TokenStream {
    TokenStream::from(quote! {
        const E0: usize = [0][3];
    })
}

```

`using_proc_macro` crate:
```rust
const_panic_proc_macro::const_panicking!{}
```

**The compiler detects no const errors,even though there is an out of bounds error in the constant.**

Output:
```
cargo check --bin with_proc_macro
    Checking using_const_panic v0.1.0 (/home/matias/Documents/eclipse_workspace/tmp/panic_in_const/using_const_panic)
    Finished dev [unoptimized + debuginfo] target(s) in 0.19s

```

### Manually expanded version

Here is the manually expanded version of the macro (in the `manually_expanded` binary in `using_const_panic`):
```rust
const E0: usize = [0][3];
```

**When compiled with `cargo check` outputs the out of bounds error.**

Output:
```
cargo check --bin manually_expanded
   Compiling const_panic_proc_macro v0.1.0 (/home/matias/Documents/eclipse_workspace/tmp/panic_in_const/const_panic_proc_macro)
    Checking using_const_panic v0.1.0 (/home/matias/Documents/eclipse_workspace/tmp/panic_in_const/using_const_panic)
warning: constant item is never used: `E0`
 --> src/bin/manually_expanded/main.rs:1:1
  |
1 | const E0: usize = [0][3];
  | ^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: #[warn(dead_code)] on by default

error: any use of this value will cause an error
 --> src/bin/manually_expanded/main.rs:1:1
  |
1 | const E0: usize = [0][3];
  | ^^^^^^^^^^^^^^^^^^------^
  |                   |
  |                   index out of bounds: the len is 1 but the index is 3
  |
  = note: #[deny(const_err)] on by default

error: aborting due to previous error

```

### With macro_rules in the same crate

With a macro_rule declared in the `with_internal_macro_rules` binary in `using_const_panic`:

```rust
mod local_panic{
    #[macro_export]
    macro_rules! local_panic_const_panicking{
        ()=>{
            const E0: usize = [0][3];
        }
    }
}
local_panic_const_panicking!{}
```

**When compiled with `cargo check` it produces the intended const error.**

Output:
```
cargo check --bin with_internal_macro_rules
    Checking using_const_panic v0.1.0 (/home/matias/Documents/eclipse_workspace/tmp/panic_in_const/using_const_panic)
warning: constant item is never used: `E0`
 --> src/bin/with_internal_macro_rules/main.rs:5:13
  |
5 |             const E0: usize = [0][3];
  |             ^^^^^^^^^^^^^^^^^^^^^^^^^
...
9 | local_panic_const_panicking!{}
  | ------------------------------ in this macro invocation
  |
  = note: #[warn(dead_code)] on by default

error: any use of this value will cause an error
 --> src/bin/with_internal_macro_rules/main.rs:5:13
  |
5 |             const E0: usize = [0][3];
  |             ^^^^^^^^^^^^^^^^^^------^
  |                               |
  |                               index out of bounds: the len is 1 but the index is 3
...
9 | local_panic_const_panicking!{}
  | ------------------------------ in this macro invocation
  |
  = note: #[deny(const_err)] on by default

error: aborting due to previous error

error: Could not compile `using_const_panic`.

```

### With macro_rules from another crate

With a macro_rule declared in another crate:

`macro_rules_panic` crate:

```rust
#[macro_export]
macro_rules! const_panicking{
    ()=>{
        const E0: usize = [0][3];
    }
}
```

`with_external_macro_rules` binary in `using_const_panic`:

```rust
macro_rules_panic::const_panicking!{}
```

**This code `cargo check`s without errors,even though it has an out of bounds error in the constant.**

Output:
```
cargo check --bin with_external_macro_rules
    Checking using_const_panic v0.1.0 (/home/matias/Documents/eclipse_workspace/tmp/panic_in_const/using_const_panic)
    Finished dev [unoptimized + debuginfo] target(s) in 0.17s
```

### LINKED ISSUE #65300: `rustc_data_structures::static_assert!(false)` does not error
`1.40.0-nightly 2019-10-09 20cc75272619cc452e3a`

 The following does not error locally / on the playground https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=9dde03338a31e2f40491a66dc3a18761

```rust
#![feature(rustc_private)]

extern crate rustc_data_structures;
use rustc_data_structures::static_assert;

fn main() {
    // doesn't error, but should
    static_assert!(2 + 2 == 5);

    // correctly errors when uncommented
    // const _: () = [()][!(2 + 2 == 5) as usize];

    // https://doc.rust-lang.org/nightly/nightly-rustc/src/rustc_data_structures/macros.rs.html#4-11
}
```

If I copy paste the macro into the same file, it errors as expected https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=bec79345cfe7cecf1b92eed6c2736152

```
error: any use of this value will cause an error
  --> src/main.rs:11:23
   |
11 |         const _: () = [()][!($test: bool) as usize];
   |         --------------^^^^^^^^^^^^^^^^^^^^^^^^^^^^^-
   |                       |
   |                       index out of bounds: the len is 1 but the index is 1
...
16 |     static_assert!(2 + 2 == 5);
   |     --------------------------- in this macro invocation
   |
   = note: `#[deny(const_err)]` on by default

```

Checking other macros, [`rustc_data_structures::static_assert_size`](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_data_structures/macro.static_assert_size.html) (which is defined next to `static_assert`) and [`static_assertions::const_assert`](https://docs.rs/static_assertions/1.0.0/static_assertions/macro.const_assert.html) error as expected.

### PR DESCRIPTION
**Pull request by memoryruins**
fixes #65300
fixes #61058

r? @oli-obk

### CODE REVIEW

File: src/test/ui/consts/const-external-macro-const-err.rs [hunk 1]
```diff
@@ -0,0 +1,13 @@
...
+
+// Ensure that CONST_ERR lint errors
+// are not silenced in external macros.
+// https://github.com/rust-lang/rust/issues/65300
+
+extern crate external_macro;
+use external_macro::static_assert;
+
+fn main() {
+    static_assert!(2 + 2 == 5); //~ ERROR
```
Comment (Mark-Simulacrum) [inline src/test/ui/consts/const-external-macro-const-err.rs]: This works outside "expression" scope too, right? Can we test it there? I seem to recall some differences, but maybe that was a transient state...

Comment (memoryruins) [reply src/test/ui/consts/const-external-macro-const-err.rs]: As in the following?
```rust
static_assert!(false); //~ ERROR
fn main() { /* ... */ }
```
