### PR TITLE
Fix size_hint for EncodeUtf16

### LINKED ISSUE #113897: Incorrect `size_hint()` on `EncodeUtf16`
I tried this code:

```rust
println!("{:?}", "12345678901234".encode_utf16().size_hint());

let mut it = "\u{101234}".encode_utf16();
it.next().unwrap();
println!("{:?}", it.size_hint());
```

I expected to see this happen:
```none
(5, Some(14))
(1, Some(1))
```

Instead, this happened:
```none
(4, Some(28))
(0, Some(0))
```

### Meta

`rustc --version --verbose`:
```
rustc 1.73.0-nightly (39f42ad9e 2023-07-19)
binary: rustc
commit-hash: 39f42ad9e8430a8abb06c262346e89593278c515
commit-date: 2023-07-19
host: x86_64-pc-windows-msvc
release: 1.73.0-nightly
LLVM version: 16.0.5
```

The reason is that the `EncodeUtf16` iterator calculates its size hint in terms of the contained `Chars` iterator size hint, assuming that each character can correspond to either 1 or 2 code units.

In the case that the iterator is NOT in the middle of a surrogate pair, this leads to too-low lower bounds and too high upper-bounds.
In the case that the iterator IS in the middle of a surrogate pair, the remaining code unit is not taken into account as the iterator has advanced past this point.

The actual calculation should be done in terms of the remaining bytes:

- The lower bound is achieved by assuming the remaining bytes consist of as many 3-byte sequences as possible, optionally followed by a 1 or 2-byte sequence, leading to a lower bound of `(bytes_remaining + 2) / 3`
- The upper bound is achieved by assuming the remaining bytes consist of 1-byte sequences, leading to an upper bound of `bytes_remaining`.

In the case of the iterator being positioned in the middle of a surrogate pair, both these values should be increased by 1.

### PR DESCRIPTION
**Pull request by ajtribick**
More realistic upper and lower bounds, and handle the case where the iterator is located within a surrogate pair.

Resolves #113897

### CODE REVIEW

File: library/core/src/str/iter.rs [hunk 1]
```diff
@@ -1439,11 +1439,20 @@ impl<'a> Iterator for EncodeUtf16<'a> {
 
     #[inline]
     fn size_hint(&self) -> (usize, Option<usize>) {
-        let (low, high) = self.chars.size_hint();
-        // every char gets either one u16 or two u16,
-        // so this iterator is between 1 or 2 times as
-        // long as the underlying iterator.
-        (low, high.and_then(|n| n.checked_mul(2)))
+        let len = self.chars.iter.len();
+        // The highest bytes:code units ratio occurs for 3-byte sequences, so
```
Comment (cuviper) [inline library/core/src/str/iter.rs:1443]: I think this could explicitly mention surrogates, something like "because a 4-byte sequence will map to 2 code units as a surrogate pair," so we're covering the prior misconception about the output being twice as long.

Everything else looks good to me!

Comment (ajtribick) [reply library/core/src/str/iter.rs]: Added some extra details.

**Comment by cuviper** [comment]
Thanks!

@bors r+
