### PR TITLE
Ignore fake borrows for packed field check

### LINKED ISSUE #137250: ‘reference to packed field is unaligned’ in nested field of `match` pattern
Consider (https://godbolt.org/z/x39GzMKz4):

```rust
#[repr(packed)]
#[derive(PartialEq)]
pub struct Packed(i32);

enum Y {
    Foo { id: Packed, },
    Bar(i32)
}

fn pred(_: &i32) -> bool {
    return true;
}

fn f(x: Y) {
    match &x {
        Y::Foo { id: Packed(4), .. } => {},
        Y::Bar(s) if pred(s) => {},
        _ => {}
    }
}
```

This results in an error:
```console
error[E0793]: reference to packed field is unaligned
  --> <source>:14:11
   |
14 |     match &x {
   |           ^^
   |
```

I don’t really know what the problem is here, but it might be the match on the `id` field in the first match arm that triggers the error. Moving `Packed(4)` into a local variable works, but if I declare it as a `const` variable instead the error resurfaces. Alternatively, removing the `Y::Bar` match arm for some reason also makes the error go away.

This currently errors on nightly and some testing on godbolt shows that this code results in an error since Rust 1.62. Before that, we still get the same diagnostic; it’s just treated as a warning instead.

### PR DESCRIPTION
**Pull request by compiler-errors**
We should not emit unaligned packed field reference errors for the fake borrows that we generate during match lowering. 

These fake borrows are there to ensure in *borrow-checking* that we don't modify the value being matched (which is why this only occurs when there's a match guard, in this case `if true`), but they are removed after the MIR is processed by `CleanupPostBorrowck`, since they're really just there to cause borrowck errors if necessary.

I modified `PlaceContext::is_borrow` since that's used by the packed field check:
https://github.com/rust-lang/rust/blob/17c1c329a5512d718b67ef6797538b154016cd34/compiler/rustc_mir_transform/src/check_packed_ref.rs#L40

It's only used in one other place, in the SROA optimization (by which fake borrows are removed, so it doesn't matter):
https://github.com/rust-lang/rust/blob/17c1c329a5512d718b67ef6797538b154016cd34/compiler/rustc_mir_dataflow/src/value_analysis.rs#L922

Fixes https://github.com/rust-lang/rust/issues/137250

### CODE REVIEW

**Comment by compiler-errors** [comment]
cc @ralfjung who added this check

**Comment by compiler-errors** [comment]
r? oli-obk who reviewed it

File: compiler/rustc_middle/src/mir/visit.rs [hunk 1]
```diff
@@ -1394,9 +1394,8 @@ impl PlaceContext {
     pub fn is_borrow(self) -> bool {
```
Comment (RalfJung) [inline compiler/rustc_middle/src/mir/visit.rs:1394]: Might be worth updating the doc comment to explicitly say that only "real" borrows (that exist operationally) are considered here?

Another option might be to move the packed-place-borrow-checker to after SharedBorrow deletion, but that might be a bit too late.

Comment (compiler-errors) [reply compiler/rustc_middle/src/mir/visit.rs:1394]: Yeah, I presumed that the packed checker was early on so as to avoid any optimizations getting in the way, though we shouldn't be applying any semantics-affecting optimizations until *after* borrowck, so perhaps this could be moved to right after post-borrowck cleanup 🤔

Comment (compiler-errors) [reply compiler/rustc_middle/src/mir/visit.rs:1394]: I'll change the docs anyways.

Comment (RalfJung) [reply compiler/rustc_middle/src/mir/visit.rs:1394]: Do fake borrows get removed somewhere within analysis MIR? As ling as we can stay on analysis MIR, it should be fine, that one should not be affected by optimizations at all, right?

**Comment by oli-obk** [comment]
r=me with docs. I was just being overly conservative, looking at the uses of `is_borrow` I don't see why we need to handle the fake borrows
