### PR TITLE
53956 panic on include bytes of own file

### LINKED ISSUE #53956: `cargo build` panics with include_bytes!() of the file itself
This code looks meaningless, but it's still valid code. However it can cause `cargo` to panic.

```rust
// This file is: main.rs
fn main() {
    let mut bytes = vec![];
    bytes.append(&mut include_bytes!("main.rs").to_vec());
    println!("Byte count: {}", bytes.len());
}
```

First build is ok. Then call shell `touch main.rs` and build again, `cargo` will crash with:

```shell
thread 'main' panicked at 'index out of bounds: the len is 0 but the index is 1',
/checkout/src/libcore/slice/mod.rs:2079:10
```

Version: `cargo 1.28.0 (96a2c7d16 2018-07-13)`

### PR DESCRIPTION
**Pull request by matthew-russo**
fix #53956

When using `include_bytes!` on a source file in the project, compiler would panic on subsequent compilations because `expand_include_bytes` would overwrite files in the source_map with no source. This PR changes `expand_include_bytes` to check source_map and use the already existing src, if any.

### CODE REVIEW

**Comment by mcr431** [comment]
Will do a full stage 2 build/test and debug

**Comment by mcr431** [comment]
@eddyb

**Comment by michaelwoerister** [comment]
Hm, ok, I think I understand the root cause now. I'll need to think a little more before I can decide if this is a good fix. Thanks for looking into this, @mcr431!

**Comment by michaelwoerister** [comment]
OK, so the underlying problem is that the same file can get added to the source map twice, once via the regular parser and once via an include macro. If the macro includes the file after the parser has already added it, it will overwrite the entry in the source map's `stable_id_to_source_file` map.

The changes in the PR fix this problem by passing the correct source to the duplicate entry. However, I think the cleaner fix would be to safeguard `SourceMap::new_source_file()` against duplication and then to only pass `None` for `src` if `String::from_utf8(bytes)` fails in `expand_include_bytes()`.

You'll probably need to add another constructor to `StableFilemapId` that takes the data it needs directly instead of reading them from the `SourceFile`. 

Would you be up to adapting your PR accordingly, @mcr431?

**Comment by mcr431** [comment]
@michaelwoerister thanks for the feedback. I’ll make the updates and then tag you when it’s ready for review.

**Comment by michaelwoerister** [comment]
Thanks, @mcr431!

**Comment by mcr431** [comment]
@michaelwoerister can i get some help from you or someone else on this? I made the changes so `new_source_file` doesn't insert duplicates and it resolves the problem. Test suite stage 1 seems to run fine but fails on stage 2 on a few proc macro tests. I'm not sure how this is getting affected and I've been having some trouble debugging. If you have any tips or places I should look to, that would be really helpful

File: src/libsyntax/ext/source_util.rs [hunk 1]
```diff
@@ -182,9 +182,12 @@ pub fn expand_include_bytes(cx: &mut ExtCtxt, sp: Span, tts: &[tokenstream::Toke
             DummyResult::expr(sp)
         }
         Ok(..) => {
-            // Add this input file to the code map to make it available as
-            // dependency information, but don't enter it's contents
-            cx.source_map().new_source_file(file.into(), String::new());
+            let src = match String::from_utf8(bytes.clone()) {
```
Comment (michaelwoerister) [inline src/libsyntax/ext/source_util.rs]: You shouldn't need to clone the `bytes` vec.

File: src/libsyntax/source_map.rs [hunk 2]
```diff
@@ -118,6 +118,18 @@ impl StableFilemapId {
 
         StableFilemapId(hasher.finish())
```
Comment (michaelwoerister) [inline src/libsyntax/source_map.rs]: I would be good to make `new` just call `new_from_pieces`.

File: src/libsyntax/source_map.rs [hunk 3]
```diff
@@ -118,6 +118,18 @@ impl StableFilemapId {
...
     }
+
+    pub fn new_from_pieces(name: &FileName,
+                           name_was_remapped: bool,
+                           unmapped_path: Option<FileName>) -> StableFilemapId {
```
Comment (michaelwoerister) [inline src/libsyntax/source_map.rs]: `unmapped_path` should be passed as a reference (either `&Option<FileName>` or `Option<&FileName>`). Then you don't have to clone it. You can use `Option::as_ref()` to convert from `Option<T>` to `Option<&T>`.

**Comment by michaelwoerister** [comment]
Hm, I don't know yet why this is failing. Maybe proc-macros rely on being able to "overwrite" files in the `SourceMap` somehow.

**Comment by mcr431** [comment]
> Hm, I don't know yet why this is failing. Maybe proc-macros rely on being able to "overwrite" files in the `SourceMap` somehow.

That was my initial assumption. I naively tried to have new_source_file just update the src property if it already existed but it wasn't working because there was another mutable reference to it elsewhere. I'll make the adjustments you commented on

**Comment by michaelwoerister** [comment]
So, yes, it looks like proc-macros all have the same "filename" and rely on the source map for parsing. I'm surprised that this hasn't caused any problems with incremental compilation yet.

**Comment by mcr431** [comment]
@michaelwoerister Good to know. Where did you find that just so I can get a better idea? And should I change it so each proc macro gets its own file or did you have a different idea?

**Comment by michaelwoerister** [comment]
`FileName` is an enum with a special case of proc-macros:
https://github.com/rust-lang/rust/blob/d74b40205f7ecf30c680dc77e62cf4f127f2db09/src/libsyntax_pos/lib.rs#L86-L106
Since the `ProcMacroSourceCode` variant has no field to differentiate between different invocations, all "file names" of `SourceFile`s generated for proc-macro invocations will be the same.

We could add a field that somehow identifies the invocation but that has implications for incremental compilation. I'm not sure yet how to best solve this.

File: src/libsyntax/ext/source_util.rs (hunk 1 above)
Comment (mcr431) [reply src/libsyntax/ext/source_util.rs]: This is cloned because `bytes` is also used to make both the src string and the LitKind::ByteStr ast node at the end of the method.

**Comment by mcr431** [comment]
@michaelwoerister noted. I made a couple of the changes you suggested. `bytes` is cloned because its consumed to make the src string and also to make the ast node at the end of the method

File: src/libsyntax/ext/source_util.rs (hunk 1 above)
Comment (michaelwoerister) [reply src/libsyntax/ext/source_util.rs]: Oh right, I didn't see that. Nevermind then.

**Comment by mcr431** [comment]
@michaelwoerister Sounds good. I'll tag you when its ready for review

File: src/libsyntax_pos/lib.rs [hunk 4]
```diff
@@ -112,12 +112,13 @@ impl std::fmt::Display for FileName {
...
-            ProcMacroSourceCode => write!(fmt, "<proc-macro source code>"),
-            CfgSpec => write!(fmt, "cfgspec"),
-            CliCrateAttr => write!(fmt, "<crate attribute>"),
+            QuoteExpansion(fingerprint) => write!(fmt, "<{} quote expansion>", fingerprint),
+            MacroExpansion(fingerprint) => write!(fmt, "<{} macro expansion>", fingerprint),
+            Anon(fingerprint) => write!(fmt, "<{} anon>", fingerprint),
+            ProcMacroSourceCode(fingerprint) =>
+                write!(fmt, "<{} proc-macro source code>", fingerprint),
+            CfgSpec(fingerprint) => write!(fmt, "<{} cfgspec>", fingerprint),
+            CliCrateAttr(fingerprint) => write!(fmt, "<{} crate attribute>", fingerprint),
```
Comment (michaelwoerister) [inline src/libsyntax_pos/lib.rs]: Since these are strings visible to the user, I would not add the fingerprint to them. And we don't need them for correctness here.

Comment (mcr431) [reply src/libsyntax_pos/lib.rs]: Noted. I just fixed this and rebased with master to resolve conflicts. There will still be a test failure(s) -- something related to converting expression to string and then back to expression and making sure they are the same. Will look into it but my local git setup is now pretty screwed and nothing will build because one of the submodules is missing things

**Comment by mcr431** [comment]
Resolved issues with rebasing and submodules, fixed display fingerprints, still failing on two tests -- `pprust-expr-roundtrip` and `ast_stmt_expr_attr`. will need to look into where this is going wrong

**Comment by michaelwoerister** [comment]
Yes, a backtrace might help. Not sure why these fail.

**Comment by michaelwoerister** [comment]
Nice find!

**Comment by michaelwoerister** [comment]
This could be relevant: 
https://github.com/rust-lang/rust/blob/f90aab7aa9bb5834b340eaef0326994e5e09b933/src/librustdoc/test.rs#L627

All tests in one file get the same filename.

**Comment by mcr431** [comment]
@michaelwoerister yes it definitely seems to be related to that. Thanks for pointing it out. I'll fiddle around with it and see if I can make any progress.

**Comment by Mark-Simulacrum** [comment]
@mcr431 Triage update: Have you had a chance to look at this? Do you need some help?

**Comment by mcr431** [comment]
@Mark-Simulacrum sorry I was moving this past week. I just started looked at it again this morning. I’m still not 100% sure what’s going wrong with the doctest. I’ll continue looking at it but another set of eyes would be helpful.

**Comment by mcr431** [comment]
@Mark-Simulacrum @QuietMisdreavus I think it has to do with the include! macro. when I remove that line, the test passes but when its there it seems like its pulling source in from somewhere else other than the named file. 

When the function's name in the doc comment is `main` it hits the recursion limit and say main is redefined in the exact same spot, but when its named anything else, it fails with a different error: 
```
error: an inner attribute is not permitted in this context
 --> src/test/rustdoc/issue-43153.rs:15:3
  |
1 | #![allow(unused)]
  |   ^
  |
  = note: inner attributes, like `#![no_std]`, annotate the item enclosing them, and are usually found at the beginning of source files. Outer attributes, like `#[test]`, annotate the item following them.

error: expected expression, found keyword `fn`
 --> src/test/rustdoc/issue-43153.rs:16:1
  |
2 | fn main() {
  | ^^ expected expression

thread 'src/test/rustdoc/issue-43153.rs - Foo (line 16)' panicked at 'couldn't compile the test', librustdoc/test.rs:346:13
note: Run with `RUST_BACKTRACE=1` for a backtrace.


failures:
    src/test/rustdoc/issue-43153.rs - Foo (line 16)

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out
```

Nowhere in this file or the included file is the attribute or in this case, the main method either. This PR changes how Files are stored across compilations and was working on weird edge cases where src was previously being overwritten/duplicate entries in the source map but now are not being changed which is having unforeseen consequences when some other part of the compiler later on is expecting the src in the source map to have been updated. I'm going to look into the include macro but so far only found the macro rules definition that just says compiler builtin so need to keep looking for the actual code. Will also keep looking through how librustdoc is tested because it could also not be updating the source of the tests properly.

**Comment by QuietMisdreavus** [comment]
The `include!()` macro is implemented in libsyntax:

https://github.com/rust-lang/rust/blob/6b9b97bd9b704f85f0184f7a213cc4d62bd9654c/src/libsyntax/ext/source_util.rs#L95-L130

The `#![allow(unused)]` and the `fn main()` that it's complaining about are probably coming from the ones that rustdoc adds itself, which means that the `include!()` in that doctest is confusing [the parsing that rustdoc does to find an existing `fn main`](https://github.com/rust-lang/rust/blob/6b9b97bd9b704f85f0184f7a213cc4d62bd9654c/src/librustdoc/test.rs#L398).

As i'm not familiar with the modifications in this PR, i'm not sure what the interaction is, but i can at least point you at those samples while i do more reading.

**Comment by mcr431** [comment]
@QuietMisdreavus thanks for the insight. Will take another look given the context and see what I can find.

**Comment by mcr431** [comment]
Update:
I had been adding debug calls but only recently found out that the bootstrapper wasn't running in debug mode when testing so I had been looking in the wrong place. I have been just been running the tests manually and have been tracing the issue back through the compiler to pinpoint where exactly things are going wrong. I feel like I'm getting closer so hopefully can resolve this sometime this week

**Comment by michaelwoerister** [comment]
You can use `eprintln!()` calls for unconditional debug output, I think.

**Comment by mcr431** [comment]
@michaelwoerister I finally found what was causing it and then unearthed more broken tests afterwards so will need to address those but want to get some input on this issue. 

So the doctest hit the include! macro which would then load a file using this code:
```
     pub fn load_file(&self, path: &Path) -> io::Result<Lrc<SourceFile>> {
         let src = self.file_loader.read_file(path)?;
         let filename = if let Some((ref name, _)) = self.doctest_offset {
             name.clone()
         } else {
             path.to_owned().into()
         };
         Ok(self.new_source_file(filename, src))
     }
``` 
so filename would end up being the test file instead of the included file which then wouldnt get updated since it was already in the source map but then it would consistently recurse through the same code and consistently hit the same include! statement and rinse and repeat. Just to test things, I changed it to:

```
     pub fn load_file(&self, path: &Path) -> io::Result<Lrc<SourceFile>> {
         let src = self.file_loader.read_file(path)?;
         let filename = path.to_owned().into();
         Ok(self.new_source_file(filename, src))
     }
```

and it works but I'm assuming this check exists for a specific reason but I'm not sure what that is. Any insight would be helpful and what you think an ideal solution would be.

**Comment by michaelwoerister** [comment]
The `doctest_offset` construct does not seem like a good solution to me. It would be better if there was a `DocTest(path, line)` variant in `FileName`. Right now, as you noted, `doctest_offset` weirdly causes all files in the `SourceMap` to have the same filename. If the offset was encoded in a `FileName` variant, the uses of `SourceMap::doctest_offset_line()` in https://github.com/rust-lang/rust/blob/36a50c29f6c5c386fba6ab685818755ac55152e5/src/librustc_errors/emitter.rs would have to be adapted. And then `doctest_offset` could be removed completely from `SourceMap`.

**Comment by mcr431** [comment]
@michaelwoerister noted. I'll make the changes and fix the remaining test failures (hopefully last) and update the PR for you to review

**Comment by michaelwoerister** [comment]
Awesome, thank you!

**Comment by mcr431** [comment]
So i finalized the broken tests and did the refactor and ran the test suite again and `src/test/run-make-fulldeps/rustdoc-error-lines` is failing but im a bit confused because I think it should be failing? The test is:

```
/// ```rust
/// #![feature(nll)]
/// let x: char = 1;
/// ```
pub fn foo() {
```

`let x: char = 1` is not valid so I'm not sure how this would ever be working?

**Comment by mcr431** [comment]
@michaelwoerister

**Comment by mcr431** [comment]
Hmmm. something smells off. everything is green locally. will debug and update

**Comment by mcr431** [comment]
WOOHOOOO finally! @michaelwoerister can you check it out and make sure my code changes are acceptable?
