### PR TITLE
resolve: Support imports of associated types and glob imports from traits

### LINKED ISSUE #138711: `import_trait_associated_functions` is not very compatible with `min_generic_const_args`
The implementation of `use Trait::AssocItem;` in https://github.com/rust-lang/rust/pull/134754 didn't update any type checking code, and it still sometimes relies on associated items having at least 2 segments.

I tried this code:

```rust
#![feature(import_trait_associated_functions)]
#![feature(min_generic_const_args)]
#![allow(incomplete_features)]

trait Trait {
    const CONST: usize;
}

use Trait::CONST;
type Alias = [u8; CONST];
```

I expected to see this happen:
```
error[E0283]: type annotations needed
  --> src/lib.rs:10:19
   |
10 | type Alias = [u8; CONST];
   |                   ^^^^^
   |                   |
   |                   cannot infer type
   |                   help: use the fully qualified path to an implementation: `<Type as Trait>::CONST`
   |
   = note: cannot satisfy `_: Trait`
   = note: associated constants cannot be accessed directly on a `trait`, they can only be accessed through a specific `impl`

```
That's what happen without `min_generic_const_args`.

Instead, this happened:
```
   Compiling playground v0.0.1 (/playground)

thread 'rustc' panicked at compiler/rustc_hir_analysis/src/hir_ty_lowering/mod.rs:2399:34:
range end index 18446744073709551615 out of range for slice of length 1
stack backtrace:
   0:     0x76928e6417c3 - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::h2137b6342f1d7514
   1:     0x76928ee05a58 - core::fmt::write::hc09fda18d9ba7e13
   2:     0x769290175b11 - std::io::Write::write_fmt::hc5178d2f7c502de3
   3:     0x76928e641622 - std::sys::backtrace::BacktraceLock::print::hd3aa20f1625542d3
   4:     0x76928e643eda - std::panicking::default_hook::{{closure}}::h27a178e455c58e1c
   5:     0x76928e643a5f - std::panicking::default_hook::hf315b1d4878133c6
   6:     0x76928d6aa5af - std[a455c0feae62ef3e]::panicking::update_hook::<alloc[d50818bc7158f075]::boxed::Box<rustc_driver_impl[9bf04f5a5b9a98a2]::install_ice_hook::{closure#1}>>::{closure#0}
   7:     0x76928e644753 - std::panicking::rust_panic_with_hook::hab1c27c56ca0369e
   8:     0x76928e64444a - std::panicking::begin_panic_handler::{{closure}}::h22745f64f0ff8046
   9:     0x76928e641c99 - std::sys::backtrace::__rust_end_short_backtrace::he285cf1e051c592f
  10:     0x76928e64410d - __rustc[1b65734bf76d56e4]::rust_begin_unwind
  11:     0x76928b06e490 - core::panicking::panic_fmt::h7c7d882b734bf2b1
  12:     0x76928d098fd7 - core::slice::index::slice_end_index_len_fail::do_panic::runtime::he87c3fd5f000934e
  13:     0x76928c68f37a - core::slice::index::slice_end_index_len_fail::hbcaba4a9e05935e0
  14:     0x76928f2f430e - <dyn rustc_hir_analysis[129c891c4e7c9399]::hir_ty_lowering::HirTyLowerer>::lower_const_arg
  15:     0x76928f308278 - <dyn rustc_hir_analysis[129c891c4e7c9399]::hir_ty_lowering::HirTyLowerer>::lower_ty
  16:     0x76928f2f6bba - rustc_hir_analysis[129c891c4e7c9399]::collect::type_of::type_of
  17:     0x76928ee2487a - rustc_query_impl[557d20f0471ac7fb]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[557d20f0471ac7fb]::query_impl::type_of::dynamic_query::{closure#2}::{closure#0}, rustc_middle[d978a2fb9e6b5c57]::query::erase::Erased<[u8; 8usize]>>
  18:     0x76928ee236f3 - rustc_query_system[a206187ad3385ddc]::query::plumbing::try_execute_query::<rustc_query_impl[557d20f0471ac7fb]::DynamicConfig<rustc_query_system[a206187ad3385ddc]::query::caches::DefIdCache<rustc_middle[d978a2fb9e6b5c57]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[557d20f0471ac7fb]::plumbing::QueryCtxt, false>
  19:     0x76928ee2329f - rustc_query_impl[557d20f0471ac7fb]::query_impl::type_of::get_query_non_incr::__rust_end_short_backtrace
  20:     0x76928f32d879 - <rustc_hir_analysis[129c891c4e7c9399]::collect::CollectItemTypesVisitor as rustc_hir[bbd719823169cc1]::intravisit::Visitor>::visit_item
  21:     0x76928f321db7 - rustc_hir_analysis[129c891c4e7c9399]::check::wfcheck::check_well_formed
  22:     0x76928f321bd1 - rustc_query_impl[557d20f0471ac7fb]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[557d20f0471ac7fb]::query_impl::check_well_formed::dynamic_query::{closure#2}::{closure#0}, rustc_middle[d978a2fb9e6b5c57]::query::erase::Erased<[u8; 1usize]>>
  23:     0x76928f321688 - rustc_query_system[a206187ad3385ddc]::query::plumbing::try_execute_query::<rustc_query_impl[557d20f0471ac7fb]::DynamicConfig<rustc_data_structures[14db4f6db8291246]::vec_cache::VecCache<rustc_span[e6986606ccadc511]::def_id::LocalDefId, rustc_middle[d978a2fb9e6b5c57]::query::erase::Erased<[u8; 1usize]>, rustc_query_system[a206187ad3385ddc]::dep_graph::graph::DepNodeIndex>, false, false, false>, rustc_query_impl[557d20f0471ac7fb]::plumbing::QueryCtxt, false>
  24:     0x76928f321143 - rustc_query_impl[557d20f0471ac7fb]::query_impl::check_well_formed::get_query_non_incr::__rust_end_short_backtrace
  25:     0x76928f31e5d5 - rustc_hir_analysis[129c891c4e7c9399]::check::wfcheck::check_mod_type_wf
  26:     0x76928f31e3df - rustc_query_impl[557d20f0471ac7fb]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[557d20f0471ac7fb]::query_impl::check_mod_type_wf::dynamic_query::{closure#2}::{closure#0}, rustc_middle[d978a2fb9e6b5c57]::query::erase::Erased<[u8; 1usize]>>
  27:     0x76928fdac9c7 - rustc_query_system[a206187ad3385ddc]::query::plumbing::try_execute_query::<rustc_query_impl[557d20f0471ac7fb]::DynamicConfig<rustc_query_system[a206187ad3385ddc]::query::caches::DefaultCache<rustc_span[e6986606ccadc511]::def_id::LocalModDefId, rustc_middle[d978a2fb9e6b5c57]::query::erase::Erased<[u8; 1usize]>>, false, false, false>, rustc_query_impl[557d20f0471ac7fb]::plumbing::QueryCtxt, false>
  28:     0x76928fdac74a - rustc_query_impl[557d20f0471ac7fb]::query_impl::check_mod_type_wf::get_query_non_incr::__rust_end_short_backtrace
  29:     0x76928f3020ed - rustc_hir_analysis[129c891c4e7c9399]::check_crate
  30:     0x76928f2027dd - rustc_interface[17fa272660c8b10c]::passes::run_required_analyses
  31:     0x76928fdbb49e - rustc_interface[17fa272660c8b10c]::passes::analysis
  32:     0x76928fdbb46d - rustc_query_impl[557d20f0471ac7fb]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[557d20f0471ac7fb]::query_impl::analysis::dynamic_query::{closure#2}::{closure#0}, rustc_middle[d978a2fb9e6b5c57]::query::erase::Erased<[u8; 0usize]>>
  33:     0x76928ff0a0c1 - rustc_query_system[a206187ad3385ddc]::query::plumbing::try_execute_query::<rustc_query_impl[557d20f0471ac7fb]::DynamicConfig<rustc_query_system[a206187ad3385ddc]::query::caches::SingleCache<rustc_middle[d978a2fb9e6b5c57]::query::erase::Erased<[u8; 0usize]>>, false, false, false>, rustc_query_impl[557d20f0471ac7fb]::plumbing::QueryCtxt, false>
  34:     0x76928ff09db4 - rustc_query_impl[557d20f0471ac7fb]::query_impl::analysis::get_query_non_incr::__rust_end_short_backtrace
  35:     0x7692900d77fd - rustc_interface[17fa272660c8b10c]::passes::create_and_enter_global_ctxt::<core[26e2193dfb565039]::option::Option<rustc_interface[17fa272660c8b10c]::queries::Linker>, rustc_driver_impl[9bf04f5a5b9a98a2]::run_compiler::{closure#0}::{closure#2}>::{closure#2}::{closure#0}
  36:     0x76928ff31751 - rustc_interface[17fa272660c8b10c]::interface::run_compiler::<(), rustc_driver_impl[9bf04f5a5b9a98a2]::run_compiler::{closure#0}>::{closure#1}
  37:     0x76928fdc0cc8 - std[a455c0feae62ef3e]::sys::backtrace::__rust_begin_short_backtrace::<rustc_interface[17fa272660c8b10c]::util::run_in_thread_with_globals<rustc_interface[17fa272660c8b10c]::util::run_in_thread_pool_with_globals<rustc_interface[17fa272660c8b10c]::interface::run_compiler<(), rustc_driver_impl[9bf04f5a5b9a98a2]::run_compiler::{closure#0}>::{closure#1}, ()>::{closure#0}, ()>::{closure#0}::{closure#0}, ()>
  38:     0x76928fdc15b4 - <<std[a455c0feae62ef3e]::thread::Builder>::spawn_unchecked_<rustc_interface[17fa272660c8b10c]::util::run_in_thread_with_globals<rustc_interface[17fa272660c8b10c]::util::run_in_thread_pool_with_globals<rustc_interface[17fa272660c8b10c]::interface::run_compiler<(), rustc_driver_impl[9bf04f5a5b9a98a2]::run_compiler::{closure#0}>::{closure#1}, ()>::{closure#0}, ()>::{closure#0}::{closure#0}, ()>::{closure#1} as core[26e2193dfb565039]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  39:     0x76928fdc29b7 - std::sys::pal::unix::thread::Thread::new::thread_start::h2bd0c059cc6cccbb
  40:     0x7692914eda94 - <unknown>
  41:     0x76929157aa34 - clone
  42:                0x0 - <unknown>

error: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: please make sure that you have updated to the latest nightly

note: please attach the file at `/playground/rustc-ice-2025-03-19T14_34_33-43.txt` to your bug report

note: compiler flags: --crate-type lib -C embed-bitcode=no -C codegen-units=1 -C debuginfo=2

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [type_of] expanding type alias `Alias`
#1 [check_well_formed] checking that `Alias` is well-formed
... and 2 other queries... use `env RUST_BACKTRACE=1` to see the full query stack
error: could not compile `playground` (lib)

Caused by:
  process didn't exit successfully: `/playground/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/rustc --crate-name playground --edition=2024 src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --crate-type lib --emit=dep-info,metadata,link -C embed-bitcode=no -C codegen-units=1 -C debuginfo=2 --check-cfg 'cfg(docsrs,test)' --check-cfg 'cfg(feature, values())' -C metadata=d7ab49d9ed59cffd -C extra-filename=-cfc3e4d0a2a75fcc --out-dir /playground/target/debug/deps -L dependency=/playground/target/debug/deps --extern addr2line=/playground/target/debug/deps/libaddr2line-a58b26028ebdd286.rmeta --extern adler2=/playground/target/debug/deps/libadler2-6f793c5ec1b5055f.rmeta --extern ahash=/playground/target/debug/deps/libahash-fd545d99ab992b9b.rmeta --extern aho_corasick=/playground/target/debug/deps/libaho_corasick-f404b2cf592cafa6.rmeta --extern aligned_vec=/playground/target/debug/deps/libaligned_vec-0c1e769729f6956d.rmeta --extern allocator_api2=/playground/target/debug/deps/liballocator_api2-06602b85c92a05eb.rmeta --extern ansi_term=/playground/target/debug/deps/libansi_term-8b066d1d8b60870b.rmeta --extern anstream=/playground/target/debug/deps/libanstream-8b61efc834fc4d66.rmeta --extern anstyle=/playground/target/debug/deps/libanstyle-aefa23177e2c22ce.rmeta --extern anstyle_parse=/playground/target/debug/deps/libanstyle_parse-3285bd9377d430f1.rmeta --extern anstyle_query=/playground/target/debug/deps/libanstyle_query-cf828da32de3eedd.rmeta --extern anyhow=/playground/target/debug/deps/libanyhow-7336551d3141afea.rmeta --extern approx=/playground/target/debug/deps/libapprox-f8667ecc1ce8a6f1.rmeta --extern arc_swap=/playground/target/debug/deps/libarc_swap-15171b01af3937ad.rmeta --extern arg_enum_proc_macro=/playground/target/debug/deps/libarg_enum_proc_macro-4efc337aa08413e8.so --extern arrayvec=/playground/target/debug/deps/libarrayvec-0a83ca20b888b616.rmeta --extern async_trait=/playground/target/debug/deps/libasync_trait-05a775693ce508a5.so --extern atomic=/playground/target/debug/deps/libatomic-360f71dcf888672b.rmeta --extern atomic_waker=/playground/target/debug/deps/libatomic_waker-0cdb97624137bcfb.rmeta --extern autocfg=/playground/target/debug/deps/libautocfg-65e6e0673e7e9a27.rmeta --extern av1_grain=/playground/target/debug/deps/libav1_grain-3f7517535db68ff9.rmeta --extern avif_serialize=/playground/target/debug/deps/libavif_serialize-27326ad091002d45.rmeta --extern aws_lc_rs=/playground/target/debug/deps/libaws_lc_rs-08f01e77c2ad6e71.rmeta --extern aws_lc_sys=/playground/target/debug/deps/libaws_lc_sys-bba60fc48808c3a6.rmeta --extern backtrace=/playground/target/debug/deps/libbacktrace-51e20bf6f3c5b083.rmeta --extern base64=/playground/target/debug/deps/libbase64-31a61120b61ae6dc.rmeta --extern bit_set=/playground/target/debug/deps/libbit_set-ff02b9c967451bad.rmeta --extern bit_vec=/playground/target/debug/deps/libbit_vec-6347e14da918bcf5.rmeta --extern bit_field=/playground/target/debug/deps/libbit_field-694817e51a2930c1.rmeta --extern bitflags_1_3_2=/playground/target/debug/deps/libbitflags-e74c0948331056ef.rmeta --extern bitflags=/playground/target/debug/deps/libbitflags-9834d050a6efe0c2.rmeta --extern bitstream_io=/playground/target/debug/deps/libbitstream_io-a43603ec1d2b0016.rmeta --extern block_buffer=/playground/target/debug/deps/libblock_buffer-a7d3cf84c57330d8.rmeta --extern borsh=/playground/target/debug/deps/libborsh-0bcadbc34ff24ee8.rmeta --extern built=/playground/target/debug/deps/libbuilt-c4718f933b1e0f39.rmeta --extern bumpalo=/playground/target/debug/deps/libbumpalo-af2e7e838956e031.rmeta --extern bytemuck=/playground/target/debug/deps/libbytemuck-143790b30f41d414.rmeta --extern bytemuck_derive=/playground/target/debug/deps/libbytemuck_derive-c83b79a24437eebb.so --extern byteorder=/playground/target/debug/deps/libbyteorder-f89bcde6f1e2352a.rmeta --extern byteorder_lite=/playground/target/debug/deps/libbyteorder_lite-13db135683c331a4.rmeta --extern bytes_0_4_12=/playground/target/debug/deps/libbytes-f1120e7d6d9a5eee.rmeta --extern bytes=/playground/target/debug/deps/libbytes-80854f7731f6005b.rmeta --extern cc=/playground/target/debug/deps/libcc-a8eab60ce727ec20.rmeta --extern cfg_if=/playground/target/debug/deps/libcfg_if-91a45a1aff4aae5a.rmeta --extern cfg_aliases=/playground/target/debug/deps/libcfg_aliases-3f829bf49deda5a7.rmeta --extern chrono=/playground/target/debug/deps/libchrono-ebfbfcb1a207a243.rmeta --extern clap=/playground/target/debug/deps/libclap-3f1d0673f404cab9.rmeta --extern clap_builder=/playground/target/debug/deps/libclap_builder-347efc20989e3579.rmeta --extern clap_derive=/playground/target/debug/deps/libclap_derive-2a671aaa85937e01.so --extern clap_lex=/playground/target/debug/deps/libclap_lex-ad3c8e368802e5d1.rmeta --extern cmake=/playground/target/debug/deps/libcmake-003f7a61c08b6350.rmeta --extern color_quant=/playground/target/debug/deps/libcolor_quant-b37e32f0613756c3.rmeta --extern colorchoice=/playground/target/debug/deps/libcolorchoice-d00f5c74c3097457.rmeta --extern const_default=/playground/target/debug/deps/libconst_default-9070b74538de1c4e.rmeta --extern cookie=/playground/target/debug/deps/libcookie-6a21fdf3e7afd3cd.rmeta --extern cookie_store=/playground/target/debug/deps/libcookie_store-836ff6a13820a3a3.rmeta --extern cpufeatures=/playground/target/debug/deps/libcpufeatures-6ebe4431a91b597a.rmeta --extern crc32fast=/playground/target/debug/deps/libcrc32fast-ee50b3e115e4e41e.rmeta --extern crossbeam=/playground/target/debug/deps/libcrossbeam-bf17a1f64fe2176b.rmeta --extern crossbeam_channel=/playground/target/debug/deps/libcrossbeam_channel-4e4a1b5aa482602e.rmeta --extern crossbeam_deque=/playground/target/debug/deps/libcrossbeam_deque-64db80a0961b9e56.rmeta --extern crossbeam_epoch=/playground/target/debug/deps/libcrossbeam_epoch-3eefd1020e466249.rmeta --extern crossbeam_queue=/playground/target/debug/deps/libcrossbeam_queue-c1f4832240b9a2ec.rmeta --extern crossbeam_utils=/playground/target/debug/deps/libcrossbeam_utils-899c3fd0f02d63fd.rmeta --extern crypto_common=/playground/target/debug/deps/libcrypto_common-36a6b967c84a1d29.rmeta --extern cssparser=/playground/target/debug/deps/libcssparser-a9531ba17b1aa10b.rmeta --extern cssparser_macros=/playground/target/debug/deps/libcssparser_macros-035ddfec8ccce88a.so --extern csv=/playground/target/debug/deps/libcsv-1604f96f2992134a.rmeta --extern csv_core=/playground/target/debug/deps/libcsv_core-0327c1131f797fc0.rmeta --extern data_encoding=/playground/target/debug/deps/libdata_encoding-50e7e60afc459ad7.rmeta --extern deranged=/playground/target/debug/deps/libderanged-9f05b3496e63f9ca.rmeta --extern derivative=/playground/target/debug/deps/libderivative-a9fdaee068ca3051.so --extern destructure_traitobject=/playground/target/debug/deps/libdestructure_traitobject-829f77be92d9b6be.rmeta --extern digest=/playground/target/debug/deps/libdigest-1fe562d0cbdc82e7.rmeta --extern displaydoc=/playground/target/debug/deps/libdisplaydoc-4cb632f6d2702078.so --extern document_features=/playground/target/debug/deps/libdocument_features-0a636d019c1fc741.so --extern dtoa=/playground/target/debug/deps/libdtoa-545f21489abed9e0.rmeta --extern dtoa_short=/playground/target/debug/deps/libdtoa_short-d5cd918d962d2f00.rmeta --extern dunce=/playground/target/debug/deps/libdunce-b10e6a36dfbf7930.rmeta --extern ego_tree=/playground/target/debug/deps/libego_tree-73f40f45b6a4e570.rmeta --extern either=/playground/target/debug/deps/libeither-9cd7ef43580545b5.rmeta --extern encoding_rs=/playground/target/debug/deps/libencoding_rs-7f495812610d6ce0.rmeta --extern env_filter=/playground/target/debug/deps/libenv_filter-5deacffa15dcd400.rmeta --extern env_logger=/playground/target/debug/deps/libenv_logger-6b2f833050adcdc5.rmeta --extern equivalent=/playground/target/debug/deps/libequivalent-0aa8633503843b1d.rmeta --extern errno=/playground/target/debug/deps/liberrno-07a3fdab5c2e9af0.rmeta --extern exr=/playground/target/debug/deps/libexr-ff3923b4d4407304.rmeta --extern fallible_iterator_0_2_0=/playground/target/debug/deps/libfallible_iterator-78181c302fe2a95d.rmeta --extern fallible_iterator=/playground/target/debug/deps/libfallible_iterator-e0d7ba2356bc3941.rmeta --extern fallible_streaming_iterator=/playground/target/debug/deps/libfallible_streaming_iterator-4d43113dcd7e624e.rmeta --extern faster_hex=/playground/target/debug/deps/libfaster_hex-e8bafc1485bf698a.rmeta --extern fastrand=/playground/target/debug/deps/libfastrand-7facbaa3cdec1804.rmeta --extern fdeflate=/playground/target/debug/deps/libfdeflate-079253eb0d115276.rmeta --extern filetime=/playground/target/debug/deps/libfiletime-ff7a254036c9d80d.rmeta --extern fixedbitset_0_4_2=/playground/target/debug/deps/libfixedbitset-e884c2cdbc2b28f7.rmeta --extern fixedbitset=/playground/target/debug/deps/libfixedbitset-c0ce8b456c751122.rmeta --extern flate2=/playground/target/debug/deps/libflate2-f155a650cc6f54b0.rmeta --extern fnv=/playground/target/debug/deps/libfnv-c83dd288116d22a3.rmeta --extern foldhash=/playground/target/debug/deps/libfoldhash-6d4b61ae779a4b80.rmeta --extern foreign_types=/playground/target/debug/deps/libforeign_types-21cfd0509e60997a.rmeta --extern foreign_types_shared=/playground/target/debug/deps/libforeign_types_shared-54300d37a1dc9e86.rmeta --extern form_urlencoded=/playground/target/debug/deps/libform_urlencoded-1d6f9ec2be47d02e.rmeta --extern fs_extra=/playground/target/debug/deps/libfs_extra-2b0e42d21600b1d9.rmeta --extern futf=/playground/target/debug/deps/libfutf-daad7ce55e2e3a40.rmeta --extern futures_0_1_31=/playground/target/debug/deps/libfutures-d15221489a7c75be.rmeta --extern futures=/playground/target/debug/deps/libfutures-d400e1d131613332.rmeta --extern futures_channel=/playground/target/debug/deps/libfutures_channel-8b2b65985a27d04b.rmeta --extern futures_core=/playground/target/debug/deps/libfutures_core-36b4650629fb76bb.rmeta --extern futures_executor=/playground/target/debug/deps/libfutures_executor-33b124fa9eeafa90.rmeta --extern futures_io=/playground/target/debug/deps/libfutures_io-dff1125e2cfb2bd8.rmeta --extern futures_macro=/playground/target/debug/deps/libfutures_macro-8d077559c4896615.so --extern futures_sink=/playground/target/debug/deps/libfutures_sink-c9de3ece2487f0ce.rmeta --extern futures_task=/playground/target/debug/deps/libfutures_task-e47d7289a7587cc8.rmeta --extern futures_util=/playground/target/debug/deps/libfutures_util-0d3563be81dcbe94.rmeta --extern fxhash=/playground/target/debug/deps/libfxhash-6d362db88fc991f3.rmeta --extern generic_array_0_14_7=/playground/target/debug/deps/libgeneric_array-656f6e5bcae7fbc7.rmeta --extern generic_array=/playground/target/debug/deps/libgeneric_array-425e969cb61e0c99.rmeta --extern getopts=/playground/target/debug/deps/libgetopts-c96eceeba00edb39.rmeta --extern getrandom_0_2_15=/playground/target/debug/deps/libgetrandom-2cb9f34f8f217548.rmeta --extern getrandom=/playground/target/debug/deps/libgetrandom-8cb2558ba736034d.rmeta --extern gif=/playground/target/debug/deps/libgif-39d9198ce416fb76.rmeta --extern gimli=/playground/target/debug/deps/libgimli-1d505c6c29655131.rmeta --extern glob=/playground/target/debug/deps/libglob-e0cdb4504dc4ebf4.rmeta --extern h2=/playground/target/debug/deps/libh2-0d7067089a691012.rmeta --extern half=/playground/target/debug/deps/libhalf-ad82a0728b30c4bc.rmeta --extern hash32=/playground/target/debug/deps/libhash32-b0c5224ce9f3d1c8.rmeta --extern hashbrown=/playground/target/debug/deps/libhashbrown-72198d3e079c033f.rmeta --extern hashlink=/playground/target/debug/deps/libhashlink-7f37434cf77db5d8.rmeta --extern hdrhistogram=/playground/target/debug/deps/libhdrhistogram-2606997a0ff73a04.rmeta --extern heapless=/playground/target/debug/deps/libheapless-4d9a1f10b7fc7ae9.rmeta --extern heck=/playground/target/debug/deps/libheck-634e4b5da59437af.rmeta --extern hmac=/playground/target/debug/deps/libhmac-84d759cbbb567bac.rmeta --extern html5ever_0_26_0=/playground/target/debug/deps/libhtml5ever-0407daed447e2088.rmeta --extern html5ever=/playground/target/debug/deps/libhtml5ever-1dabb20c37243423.rmeta --extern http=/playground/target/debug/deps/libhttp-f8ccb494f1a172bf.rmeta --extern http_body=/playground/target/debug/deps/libhttp_body-c6b237a07062eb01.rmeta --extern http_body_util=/playground/target/debug/deps/libhttp_body_util-72f4081660f9ce4a.rmeta --extern httparse=/playground/target/debug/deps/libhttparse-bd16e2c5bef35668.rmeta --extern httpdate=/playground/target/debug/deps/libhttpdate-01e485a0cc7a20c3.rmeta --extern humantime=/playground/target/debug/deps/libhumantime-17938c5d3ee2ab2a.rmeta --extern hyper=/playground/target/debug/deps/libhyper-3b02731d394e23e0.rmeta --extern hyper_rustls=/playground/target/debug/deps/libhyper_rustls-819f242219a0ffa0.rmeta --extern hyper_tls=/playground/target/debug/deps/libhyper_tls-b856bee447a148aa.rmeta --extern hyper_util=/playground/target/debug/deps/libhyper_util-4d4652de3d346a22.rmeta --extern iana_time_zone=/playground/target/debug/deps/libiana_time_zone-51a0de7ead50ff37.rmeta --extern icu_collections=/playground/target/debug/deps/libicu_collections-e9c5c3493c330861.rmeta --extern icu_locid=/playground/target/debug/deps/libicu_locid-a963a3a524e6c820.rmeta --extern icu_locid_transform=/playground/target/debug/deps/libicu_locid_transform-291dbe81ef1cf2eb.rmeta --extern icu_locid_transform_data=/playground/target/debug/deps/libicu_locid_transform_data-c5ec318681865c50.rmeta --extern icu_normalizer=/playground/target/debug/deps/libicu_normalizer-a9f968aadfcd9d97.rmeta --extern icu_normalizer_data=/playground/target/debug/deps/libicu_normalizer_data-eeb083fb082f581d.rmeta --extern icu_properties=/playground/target/debug/deps/libicu_properties-ef5e45c1576addc7.rmeta --extern icu_properties_data=/playground/target/debug/deps/libicu_properties_data-db2fc06f332eae30.rmeta --extern icu_provider=/playground/target/debug/deps/libicu_provider-b13d003d3ff47b4f.rmeta --extern icu_provider_macros=/playground/target/debug/deps/libicu_provider_macros-bfaed4805a30597d.so --extern idna=/playground/target/debug/deps/libidna-a365fb9f3c6d618a.rmeta --extern idna_adapter=/playground/target/debug/deps/libidna_adapter-195f3fc2f041620d.rmeta --extern image=/playground/target/debug/deps/libimage-d80cfcc68e4e7d1b.rmeta --extern image_webp=/playground/target/debug/deps/libimage_webp-45317848bc841771.rmeta --extern imgref=/playground/target/debug/deps/libimgref-6e8e9f5ade712c4a.rmeta --extern indexmap=/playground/target/debug/deps/libindexmap-f2442d3216eefce3.rmeta --extern iovec=/playground/target/debug/deps/libiovec-0e550eb8fdd51c7c.rmeta --extern ipnet=/playground/target/debug/deps/libipnet-ba350b5bc091e431.rmeta --extern is_terminal_polyfill=/playground/target/debug/deps/libis_terminal_polyfill-64fd6da2b8238d8a.rmeta --extern itertools_0_12_1=/playground/target/debug/deps/libitertools-703563d0bdbf2ab7.rmeta --extern itertools=/playground/target/debug/deps/libitertools-50261479facfbca2.rmeta --extern itoa=/playground/target/debug/deps/libitoa-76364ae43bdd8853.rmeta --extern jiff=/playground/target/debug/deps/libjiff-7313db223ad143e2.rmeta --extern jobserver=/playground/target/debug/deps/libjobserver-92b63f69fff16c20.rmeta --extern jpeg_decoder=/playground/target/debug/deps/libjpeg_decoder-e1f63bfa9de69637.rmeta --extern lazy_static=/playground/target/debug/deps/liblazy_static-9a7119a03c0f9c42.rmeta --extern lebe=/playground/target/debug/deps/liblebe-2ec7290190725f20.rmeta --extern libc=/playground/target/debug/deps/liblibc-e552ba911aa9827b.rmeta --extern libm=/playground/target/debug/deps/liblibm-265248f93a4f88dd.rmeta --extern libsqlite3_sys=/playground/target/debug/deps/liblibsqlite3_sys-d7081246503211a5.rmeta --extern linux_raw_sys=/playground/target/debug/deps/liblinux_raw_sys-216e941233cf2874.rmeta --extern litemap=/playground/target/debug/deps/liblitemap-4ccdfbfa14c4f241.rmeta --extern litrs=/playground/target/debug/deps/liblitrs-e24cb8d6c3d9c239.rmeta --extern lock_api=/playground/target/debug/deps/liblock_api-f119a55ef9ac928a.rmeta --extern log=/playground/target/debug/deps/liblog-21e90a0c181a5ae2.rmeta --extern log_mdc=/playground/target/debug/deps/liblog_mdc-b137fedca9e6dd88.rmeta --extern log4rs=/playground/target/debug/deps/liblog4rs-0a9641c1707634c9.rmeta --extern loop9=/playground/target/debug/deps/libloop9-9e13a3bf63240e6f.rmeta --extern mac=/playground/target/debug/deps/libmac-28a60312f0b25a6e.rmeta --extern markup5ever_0_11_0=/playground/target/debug/deps/libmarkup5ever-275f8bf90acbb1a7.rmeta --extern markup5ever=/playground/target/debug/deps/libmarkup5ever-e3eaad7408e37d7e.rmeta --extern markup5ever_rcdom=/playground/target/debug/deps/libmarkup5ever_rcdom-717c6e1d8f10e38f.rmeta --extern matrixmultiply=/playground/target/debug/deps/libmatrixmultiply-cd8836d9973805d8.rmeta --extern maybe_rayon=/playground/target/debug/deps/libmaybe_rayon-ab0fee5c4060d8f9.rmeta --extern md5=/playground/target/debug/deps/libmd5-b3498d09250fc32e.rmeta --extern memchr=/playground/target/debug/deps/libmemchr-27e63ea8af2db3a4.rmeta --extern memmap=/playground/target/debug/deps/libmemmap-a37e5c042a133df9.rmeta --extern memoffset=/playground/target/debug/deps/libmemoffset-7a784d3f2b16031b.rmeta --extern mime=/playground/target/debug/deps/libmime-47c1f0fe5b106f57.rmeta --extern mime_guess=/playground/target/debug/deps/libmime_guess-993e05ba9716a765.rmeta --extern minimal_lexical=/playground/target/debug/deps/libminimal_lexical-b368051a83dbe595.rmeta --extern miniz_oxide=/playground/target/debug/deps/libminiz_oxide-2e26f480730fe65a.rmeta --extern mio=/playground/target/debug/deps/libmio-98761e5f7e82d35c.rmeta --extern nalgebra=/playground/target/debug/deps/libnalgebra-55248be26c2456a2.rmeta --extern nalgebra_macros=/playground/target/debug/deps/libnalgebra_macros-cde3b719f2ddf501.so --extern native_tls=/playground/target/debug/deps/libnative_tls-6f0607916d91f666.rmeta --extern ndarray=/playground/target/debug/deps/libndarray-48efe4498eb41ddd.rmeta --extern debug_unreachable=/playground/target/debug/deps/libdebug_unreachable-67101fabcd8f048d.rmeta --extern nom=/playground/target/debug/deps/libnom-f0ca65f73fa0f456.rmeta --extern noop_proc_macro=/playground/target/debug/deps/libnoop_proc_macro-3b682bfd5c2986cf.so --extern num=/playground/target/debug/deps/libnum-573d0f709eb0d328.rmeta --extern num_bigint=/playground/target/debug/deps/libnum_bigint-e07342c98643df1b.rmeta --extern num_complex=/playground/target/debug/deps/libnum_complex-7498e67f5eac7581.rmeta --extern num_conv=/playground/target/debug/deps/libnum_conv-ad475ce6bb892599.rmeta --extern num_derive=/playground/target/debug/deps/libnum_derive-f6318263ad0d2da0.so --extern num_integer=/playground/target/debug/deps/libnum_integer-67f03b8decace28f.rmeta --extern num_iter=/playground/target/debug/deps/libnum_iter-518668afda0eadfa.rmeta --extern num_rational=/playground/target/debug/deps/libnum_rational-8137a272bc85e709.rmeta --extern num_traits=/playground/target/debug/deps/libnum_traits-1aa5e9de6bb4a6e0.rmeta --extern num_cpus=/playground/target/debug/deps/libnum_cpus-daf316d9d0577ca9.rmeta --extern object=/playground/target/debug/deps/libobject-ef9fe2d717602311.rmeta --extern once_cell=/playground/target/debug/deps/libonce_cell-080fd27b751589a9.rmeta --extern openssl=/playground/target/debug/deps/libopenssl-dcd970b3efa0dcdc.rmeta --extern openssl_macros=/playground/target/debug/deps/libopenssl_macros-a409ca89939f2db5.so --extern openssl_probe=/playground/target/debug/deps/libopenssl_probe-fa4ea0707081b1ab.rmeta --extern openssl_sys=/playground/target/debug/deps/libopenssl_sys-641d17abbb4e89e6.rmeta --extern ordered_float=/playground/target/debug/deps/libordered_float-654c3b7695e74b18.rmeta --extern parking_lot=/playground/target/debug/deps/libparking_lot-d140c287a1812292.rmeta --extern parking_lot_core=/playground/target/debug/deps/libparking_lot_core-3b514df2026f8180.rmeta --extern paste=/playground/target/debug/deps/libpaste-63e1d8a3628c17ee.so --extern percent_encoding=/playground/target/debug/deps/libpercent_encoding-db366209d1b00722.rmeta --extern petgraph_0_6_5=/playground/target/debug/deps/libpetgraph-914d3141b3ef2554.rmeta --extern petgraph=/playground/target/debug/deps/libpetgraph-42b36680baa5cb0a.rmeta --extern phf_0_10_1=/playground/target/debug/deps/libphf-aae50f175cb1559a.rmeta --extern phf=/playground/target/debug/deps/libphf-b953d790d9b49176.rmeta --extern phf_codegen_0_10_0=/playground/target/debug/deps/libphf_codegen-4afaf011a905b1fe.rmeta --extern phf_codegen=/playground/target/debug/deps/libphf_codegen-2d5de41cf1fdb1eb.rmeta --extern phf_generator_0_10_0=/playground/target/debug/deps/libphf_generator-e0798a6fd3601a8f.rmeta --extern phf_generator=/playground/target/debug/deps/libphf_generator-f3cb2fa0037f68cc.rmeta --extern phf_macros=/playground/target/debug/deps/libphf_macros-5d82197c4cce1d92.so --extern phf_shared_0_10_0=/playground/target/debug/deps/libphf_shared-b5438fced6496711.rmeta --extern phf_shared=/playground/target/debug/deps/libphf_shared-9ed5559afa5857b2.rmeta --extern pin_project_lite=/playground/target/debug/deps/libpin_project_lite-e592cb65c274c83b.rmeta --extern pin_utils=/playground/target/debug/deps/libpin_utils-c5428260280d5cb2.rmeta --extern pkg_config=/playground/target/debug/deps/libpkg_config-e04c5071b23480ce.rmeta --extern png=/playground/target/debug/deps/libpng-d5eec755b4d18cf8.rmeta --extern postgres=/playground/target/debug/deps/libpostgres-4f9f08dd661c5d89.rmeta --extern postgres_protocol=/playground/target/debug/deps/libpostgres_protocol-3ddd1fc7754cac26.rmeta --extern postgres_types=/playground/target/debug/deps/libpostgres_types-bc10261acba96f1e.rmeta --extern powerfmt=/playground/target/debug/deps/libpowerfmt-73f7befc01795dfb.rmeta --extern ppv_lite86=/playground/target/debug/deps/libppv_lite86-47cfcd3fb270be10.rmeta --extern precomputed_hash=/playground/target/debug/deps/libprecomputed_hash-79eaef263cdc8ef4.rmeta --extern proc_macro2=/playground/target/debug/deps/libproc_macro2-ab92929a340bac7a.rmeta --extern profiling=/playground/target/debug/deps/libprofiling-964219c9a7ef2d05.rmeta --extern profiling_procmacros=/playground/target/debug/deps/libprofiling_procmacros-51b5378b1163db18.so --extern psl_types=/playground/target/debug/deps/libpsl_types-221477247deb62ee.rmeta --extern publicsuffix=/playground/target/debug/deps/libpublicsuffix-a4c9d1bc41448538.rmeta --extern qoi=/playground/target/debug/deps/libqoi-abeae1a23040d90f.rmeta --extern quick_error=/playground/target/debug/deps/libquick_error-3db4f8b19b38b0d6.rmeta --extern quote=/playground/target/debug/deps/libquote-bde0daca20738c4e.rmeta --extern rand_0_8_5=/playground/target/debug/deps/librand-40178acdf3dc8c64.rmeta --extern rand=/playground/target/debug/deps/librand-57ba754c7489fb0d.rmeta --extern rand_chacha_0_3_1=/playground/target/debug/deps/librand_chacha-366eb4635a52a84a.rmeta --extern rand_chacha=/playground/target/debug/deps/librand_chacha-7ef7eeb7e0cbd8b1.rmeta --extern rand_core_0_6_4=/playground/target/debug/deps/librand_core-a0e4a6ad4c994f84.rmeta --extern rand_core=/playground/target/debug/deps/librand_core-4c59bf16498267d3.rmeta --extern rand_distr=/playground/target/debug/deps/librand_distr-14be566d4f7485a0.rmeta --extern rav1e=/playground/target/debug/deps/librav1e-733565956bd09fe8.rmeta --extern ravif=/playground/target/debug/deps/libravif-f0e8de4468463b7f.rmeta --extern rawpointer=/playground/target/debug/deps/librawpointer-19589c4be5c36778.rmeta --extern rayon=/playground/target/debug/deps/librayon-414e38a99b7a9a17.rmeta --extern rayon_core=/playground/target/debug/deps/librayon_core-a4823e9857275e01.rmeta --extern regex=/playground/target/debug/deps/libregex-60d741f71d77774c.rmeta --extern regex_automata=/playground/target/debug/deps/libregex_automata-342b5bdb384f47c2.rmeta --extern regex_syntax=/playground/target/debug/deps/libregex_syntax-7458411f3c2d4667.rmeta --extern reqwest=/playground/target/debug/deps/libreqwest-9408df99b1d085b9.rmeta --extern rgb=/playground/target/debug/deps/librgb-f539a23b132b35f7.rmeta --extern ring=/playground/target/debug/deps/libring-594a73dc1c2d8632.rmeta --extern rusqlite=/playground/target/debug/deps/librusqlite-f61566ef947d4e1b.rmeta --extern rustc_demangle=/playground/target/debug/deps/librustc_demangle-ef469d2072d1871e.rmeta --extern rustc_version=/playground/target/debug/deps/librustc_version-ebd14f4469fd02ee.rmeta --extern rustix=/playground/target/debug/deps/librustix-81f4cac1f032af32.rmeta --extern rustls=/playground/target/debug/deps/librustls-5dd19ad3a54180d6.rmeta --extern rustls_pemfile=/playground/target/debug/deps/librustls_pemfile-fa6c002523e36419.rmeta --extern rustls_pki_types=/playground/target/debug/deps/librustls_pki_types-37dbad996f83a08d.rmeta --extern webpki=/playground/target/debug/deps/libwebpki-4a19335f5f71279c.rmeta --extern rustversion=/playground/target/debug/deps/librustversion-bb9f4ddfc08b62b6.so --extern ryu=/playground/target/debug/deps/libryu-4a4fd40082b5de27.rmeta --extern safe_arch=/playground/target/debug/deps/libsafe_arch-b7e32108fd806e28.rmeta --extern same_file=/playground/target/debug/deps/libsame_file-0cea9fd0e1629f3d.rmeta --extern scopeguard=/playground/target/debug/deps/libscopeguard-9215752600491415.rmeta --extern scraper=/playground/target/debug/deps/libscraper-96ac846d7a48ad5c.rmeta --extern select=/playground/target/debug/deps/libselect-801582947d685079.rmeta --extern selectors=/playground/target/debug/deps/libselectors-27af78182082f902.rmeta --extern semver=/playground/target/debug/deps/libsemver-8cb100746b137d67.rmeta --extern serde=/playground/target/debug/deps/libserde-5f12162f45910ec9.rmeta --extern serde_value=/playground/target/debug/deps/libserde_value-dc35b6339f58d0a1.rmeta --extern serde_derive=/playground/target/debug/deps/libserde_derive-24ab67f33415d0a3.so --extern serde_json=/playground/target/debug/deps/libserde_json-31af1a4fbe512fe0.rmeta --extern serde_spanned=/playground/target/debug/deps/libserde_spanned-fb98e06f73dd4eeb.rmeta --extern serde_urlencoded=/playground/target/debug/deps/libserde_urlencoded-98586de3f3d768ee.rmeta --extern serde_yaml=/playground/target/debug/deps/libserde_yaml-de6fae6a73833726.rmeta --extern servo_arc=/playground/target/debug/deps/libservo_arc-e3ed02c801366e5d.rmeta --extern sha1_smol=/playground/target/debug/deps/libsha1_smol-d9bf14ed0aaa0905.rmeta --extern sha2=/playground/target/debug/deps/libsha2-487b28eba4c4e79f.rmeta --extern shlex=/playground/target/debug/deps/libshlex-6599caf05ae1039c.rmeta --extern signal_hook_registry=/playground/target/debug/deps/libsignal_hook_registry-eeb40b94469dd066.rmeta --extern simba=/playground/target/debug/deps/libsimba-2fb6f9610a8ba178.rmeta --extern simd_adler32=/playground/target/debug/deps/libsimd_adler32-3f65fc997753015c.rmeta --extern simd_helpers=/playground/target/debug/deps/libsimd_helpers-235fada243a70b6e.so --extern siphasher_0_3_11=/playground/target/debug/deps/libsiphasher-472c2df808d8e46e.rmeta --extern siphasher=/playground/target/debug/deps/libsiphasher-93567ba0af5c9471.rmeta --extern slab=/playground/target/debug/deps/libslab-f126333d7718cc17.rmeta --extern smallvec=/playground/target/debug/deps/libsmallvec-8133aa0c796c2c7d.rmeta --extern socket2=/playground/target/debug/deps/libsocket2-4f50fd58b3c33ed7.rmeta --extern spin=/playground/target/debug/deps/libspin-5b034f110b1626d9.rmeta --extern sptr=/playground/target/debug/deps/libsptr-d9e0cac27b0bea56.rmeta --extern stable_deref_trait=/playground/target/debug/deps/libstable_deref_trait-e695dbe29822b356.rmeta --extern string_cache=/playground/target/debug/deps/libstring_cache-f98a90e8268f50d6.rmeta --extern string_cache_codegen=/playground/target/debug/deps/libstring_cache_codegen-8cfe579fc3dab847.rmeta --extern stringprep=/playground/target/debug/deps/libstringprep-e6f17665de927f22.rmeta --extern strsim=/playground/target/debug/deps/libstrsim-f9b0a05515226f87.rmeta --extern subtle=/playground/target/debug/deps/libsubtle-7da494fecbd869c7.rmeta --extern syn_1_0_109=/playground/target/debug/deps/libsyn-9271466881e83745.rmeta --extern syn=/playground/target/debug/deps/libsyn-d0da9502f956ccb6.rmeta --extern sync_wrapper=/playground/target/debug/deps/libsync_wrapper-d91853e2098ed83a.rmeta --extern synstructure=/playground/target/debug/deps/libsynstructure-fced4095fecaacd1.rmeta --extern tar=/playground/target/debug/deps/libtar-5bb91f9186bdd5a3.rmeta --extern tempfile=/playground/target/debug/deps/libtempfile-9314bdcd4d3eb05f.rmeta --extern tendril=/playground/target/debug/deps/libtendril-f3e2cb5dd958cf07.rmeta --extern terminal_size=/playground/target/debug/deps/libterminal_size-41e7ef22aecdfd93.rmeta --extern thiserror_1_0_69=/playground/target/debug/deps/libthiserror-821605eb355ac7ee.rmeta --extern thiserror=/playground/target/debug/deps/libthiserror-3d22a74a73bbed40.rmeta --extern thiserror_impl_1_0_69=/playground/target/debug/deps/libthiserror_impl-327e8cb8adf0d42b.so --extern thiserror_impl=/playground/target/debug/deps/libthiserror_impl-cf8543ba64478065.so --extern thread_id=/playground/target/debug/deps/libthread_id-62ceeb134dd9c2fd.rmeta --extern threadpool=/playground/target/debug/deps/libthreadpool-9043da4e10e867d2.rmeta --extern tiff=/playground/target/debug/deps/libtiff-ba6fe75e1892c687.rmeta --extern time=/playground/target/debug/deps/libtime-ae501d1a83b39d32.rmeta --extern time_core=/playground/target/debug/deps/libtime_core-95adb190deed6df7.rmeta --extern time_macros=/playground/target/debug/deps/libtime_macros-adf699f081487e47.so --extern tinystr=/playground/target/debug/deps/libtinystr-7ec676ce05ce2fed.rmeta --extern tinyvec=/playground/target/debug/deps/libtinyvec-75a8e4ef2f1010dd.rmeta --extern tinyvec_macros=/playground/target/debug/deps/libtinyvec_macros-c493a7607347b438.rmeta --extern tokio=/playground/target/debug/deps/libtokio-9f33ac83e0b3c631.rmeta --extern tokio_io=/playground/target/debug/deps/libtokio_io-c51c9936d5163590.rmeta --extern tokio_macros=/playground/target/debug/deps/libtokio_macros-a072e7ea6564dc33.so --extern tokio_native_tls=/playground/target/debug/deps/libtokio_native_tls-9dfa9141df00ba53.rmeta --extern tokio_postgres=/playground/target/debug/deps/libtokio_postgres-8165f0e517963070.rmeta --extern tokio_rustls=/playground/target/debug/deps/libtokio_rustls-63f6afe587c6a156.rmeta --extern tokio_stream=/playground/target/debug/deps/libtokio_stream-d4d24d1ca7477b64.rmeta --extern tokio_util=/playground/target/debug/deps/libtokio_util-50116d2d84a80483.rmeta --extern toml=/playground/target/debug/deps/libtoml-5e7d53ea64f30a45.rmeta --extern toml_datetime=/playground/target/debug/deps/libtoml_datetime-4fca537494bd6f24.rmeta --extern toml_edit=/playground/target/debug/deps/libtoml_edit-af80009d24a82c50.rmeta --extern tower=/playground/target/debug/deps/libtower-e5de19509a0806a6.rmeta --extern tower_layer=/playground/target/debug/deps/libtower_layer-de18ea94c6a041d6.rmeta --extern tower_service=/playground/target/debug/deps/libtower_service-8a3ebed63e1e495e.rmeta --extern tracing=/playground/target/debug/deps/libtracing-b0b85d4ec8f54a9d.rmeta --extern tracing_attributes=/playground/target/debug/deps/libtracing_attributes-00f6cb11cd2bbe49.so --extern tracing_core=/playground/target/debug/deps/libtracing_core-ac7b3742664863df.rmeta --extern trpl=/playground/target/debug/deps/libtrpl-11f74edd6f560f9d.rmeta --extern try_lock=/playground/target/debug/deps/libtry_lock-e98c118bd2ea891e.rmeta --extern typemap_ors=/playground/target/debug/deps/libtypemap_ors-e01b04bb13b92f74.rmeta --extern typenum=/playground/target/debug/deps/libtypenum-0cdf5a5451a57c45.rmeta --extern unicase=/playground/target/debug/deps/libunicase-2d9e6a0db4b2d3fe.rmeta --extern unicode_bidi=/playground/target/debug/deps/libunicode_bidi-fb88fa06210965de.rmeta --extern unicode_ident=/playground/target/debug/deps/libunicode_ident-70c08c035ba677b4.rmeta --extern unicode_normalization=/playground/target/debug/deps/libunicode_normalization-6bc6ee47ad673328.rmeta --extern unicode_properties=/playground/target/debug/deps/libunicode_properties-40b24c06531e3bc9.rmeta --extern unicode_segmentation=/playground/target/debug/deps/libunicode_segmentation-83fa2183b1f760fb.rmeta --extern unicode_width_0_1_14=/playground/target/debug/deps/libunicode_width-589b20c04b3ff0f5.rmeta --extern unicode_width=/playground/target/debug/deps/libunicode_width-6ce2bca4734e88fd.rmeta --extern unicode_xid=/playground/target/debug/deps/libunicode_xid-ad1679f653d44fdb.rmeta --extern unsafe_any_ors=/playground/target/debug/deps/libunsafe_any_ors-15506b7b5a161017.rmeta --extern unsafe_libyaml=/playground/target/debug/deps/libunsafe_libyaml-f6122d38af7695f0.rmeta --extern untrusted=/playground/target/debug/deps/libuntrusted-a0e2fe1720fa3cd1.rmeta --extern url=/playground/target/debug/deps/liburl-78640dad357d4eba.rmeta --extern utf8=/playground/target/debug/deps/libutf8-b3eafb012370ed64.rmeta --extern utf16_iter=/playground/target/debug/deps/libutf16_iter-33fd7dbc3fefc122.rmeta --extern utf8_iter=/playground/target/debug/deps/libutf8_iter-e1c5c172df6f0786.rmeta --extern utf8parse=/playground/target/debug/deps/libutf8parse-149a297d12eed339.rmeta --extern uuid=/playground/target/debug/deps/libuuid-6a3b0b85a2aa311d.rmeta --extern v_frame=/playground/target/debug/deps/libv_frame-5846a93b88573c75.rmeta --extern vcpkg=/playground/target/debug/deps/libvcpkg-95ea934bb1f2c6d6.rmeta --extern version_check=/playground/target/debug/deps/libversion_check-0baa7a5dd740a136.rmeta --extern walkdir=/playground/target/debug/deps/libwalkdir-bf3faf8af3d7ca2b.rmeta --extern want=/playground/target/debug/deps/libwant-ed934ad7866c919d.rmeta --extern wasm_bindgen=/playground/target/debug/deps/libwasm_bindgen-addd10328d6ca504.rmeta --extern wasm_bindgen_backend=/playground/target/debug/deps/libwasm_bindgen_backend-9847007e927c123d.rmeta --extern wasm_bindgen_macro=/playground/target/debug/deps/libwasm_bindgen_macro-476a69be50a64433.so --extern wasm_bindgen_macro_support=/playground/target/debug/deps/libwasm_bindgen_macro_support-aa195c7cf70a410d.rmeta --extern wasm_bindgen_shared=/playground/target/debug/deps/libwasm_bindgen_shared-825e7bb49561848c.rmeta --extern weezl=/playground/target/debug/deps/libweezl-d93f023850a8c8d5.rmeta --extern whoami=/playground/target/debug/deps/libwhoami-0bc76542ce3d0803.rmeta --extern wide=/playground/target/debug/deps/libwide-b8c07eb6a4b2b977.rmeta --extern windows_sys=/playground/target/debug/deps/libwindows_sys-6d8b079afb431f18.rmeta --extern windows_targets=/playground/target/debug/deps/libwindows_targets-dfc8a935783f0bf5.rmeta --extern windows_x86_64_gnu_0_52_6=/playground/target/debug/deps/libwindows_x86_64_gnu-20e665c6f522e8e6.rmeta --extern windows_x86_64_gnu=/playground/target/debug/deps/libwindows_x86_64_gnu-c84d0c8cec6b0351.rmeta --extern windows_x86_64_msvc=/playground/target/debug/deps/libwindows_x86_64_msvc-83057a536dac80fe.rmeta --extern winnow=/playground/target/debug/deps/libwinnow-a58677272f372bb9.rmeta --extern write16=/playground/target/debug/deps/libwrite16-fb7ab632a8555fcb.rmeta --extern writeable=/playground/target/debug/deps/libwriteable-e1248744421baace.rmeta --extern xattr=/playground/target/debug/deps/libxattr-6d28df7085ee9e83.rmeta --extern xml5ever=/playground/target/debug/deps/libxml5ever-134b189effeaace7.rmeta --extern yoke=/playground/target/debug/deps/libyoke-90d4d094bd6207eb.rmeta --extern yoke_derive=/playground/target/debug/deps/libyoke_derive-2f8d5fc73e540c63.so --extern zerocopy_0_7_35=/playground/target/debug/deps/libzerocopy-a4d7dbbf498e4ddb.rmeta --extern zerocopy=/playground/target/debug/deps/libzerocopy-056906f1f514e712.rmeta --extern zerocopy_derive_0_7_35=/playground/target/debug/deps/libzerocopy_derive-1c6ad7781af5ba9d.so --extern zerocopy_derive=/playground/target/debug/deps/libzerocopy_derive-46e4caf0d73b6d81.so --extern zerofrom=/playground/target/debug/deps/libzerofrom-e35119dfd38effa3.rmeta --extern zerofrom_derive=/playground/target/debug/deps/libzerofrom_derive-d9082ad15010f926.so --extern zeroize=/playground/target/debug/deps/libzeroize-40c140434eac1034.rmeta --extern zerovec=/playground/target/debug/deps/libzerovec-9f599a123403ea6c.rmeta --extern zerovec_derive=/playground/target/debug/deps/libzerovec_derive-bad093afb2d6c9b1.so --extern zune_core=/playground/target/debug/deps/libzune_core-40bc3b5e42e66a94.rmeta --extern zune_inflate=/playground/target/debug/deps/libzune_inflate-96d8e24854fb8db9.rmeta --extern zune_jpeg=/playground/target/debug/deps/libzune_jpeg-c1f5c3f6ba1634f2.rmeta -L native=/playground/target/debug/build/aws-lc-sys-826e5cfa0fa05f29/out -L native=/playground/target/debug/build/libsqlite3-sys-8835bc530b0c2b0e/out -L native=/playground/target/debug/build/ring-25bf22c02e948417/out -L native=/playground/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/windows_x86_64_gnu-0.52.6/lib -L native=/playground/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/windows_x86_64_gnu-0.53.0/lib -L native=/playground/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/windows_x86_64_msvc-0.53.0/lib` (exit status: 101)
```

### PR DESCRIPTION
**Pull request by petrochenkov**
Follow up to https://github.com/rust-lang/rust/pull/134754, part of https://github.com/rust-lang/rust/issues/134691.
This PR also closes https://github.com/rust-lang/rust/issues/138711 now.

Prohibiting `use Trait::AssocType;` at name resolution stage doesn't make sense, the name itself is perfectly resolveable.
It's a type checker's problem that the necessary generic args are not passed when the imported `AssocType` is used, so an error should be reported there.

And since we can import associated trait items now, glob imports from traits can also be allowed.

### CODE REVIEW

File: compiler/rustc_hir_analysis/src/hir_ty_lowering/mod.rs [hunk 1]
```diff
@@ -2177,7 +2177,13 @@ impl<'tcx> dyn HirTyLowerer<'tcx> + '_ {
                 }
             }
             Res::Def(DefKind::AssocTy, def_id) => {
-                debug_assert!(path.segments.len() >= 2);
+                if path.segments.len() < 2 {
+                    let guar = self
+                        .dcx()
+                        .struct_span_err(span, "cannot infer type, type annotations needed")
```
Comment (petrochenkov) [inline compiler/rustc_hir_analysis/src/hir_ty_lowering/mod.rs:2183]: #138711 is an issue for reporting some proper error here instead of this stub.

File: compiler/rustc_hir_analysis/src/hir_ty_lowering/mod.rs [hunk 2]
```diff
@@ -2394,7 +2400,13 @@ impl<'tcx> dyn HirTyLowerer<'tcx> + '_ {
                 ty::Const::new_unevaluated(tcx, ty::UnevaluatedConst::new(did, args))
             }
             Res::Def(DefKind::AssocConst, did) => {
-                debug_assert!(path.segments.len() >= 2);
+                if path.segments.len() < 2 {
+                    let guar = self
+                        .dcx()
+                        .struct_span_err(span, "cannot infer type, type annotations needed")
```
Comment (fbstj) [inline compiler/rustc_hir_analysis/src/hir_ty_lowering/mod.rs:2406]:
```suggestion
                        .struct_span_err(span, "cannot infer value")
```
from what I can tell of [`tests/ui/use/import_trait_associated_item_bad.rs`](https://github.com/rust-lang/rust/pull/138712/files#diff-0e2aa8759cbed2eb814cd98817fe4add695262c07791bd175cea0e1d3bfd5bcdR14) the  error isn't really type related?

https://github.com/rust-lang/rust/pull/138712/files#diff-0e2aa8759cbed2eb814cd98817fe4add695262c07791bd175cea0e1d3bfd5bcdR14

Comment (petrochenkov) [reply compiler/rustc_hir_analysis/src/hir_ty_lowering/mod.rs:2406]: The error is copypasted from the non-`min_generic_const_args` case, see #138711.
(It's the `Self` type that cannot be inferred here.)

File: compiler/rustc_hir_analysis/src/hir_ty_lowering/mod.rs
Comment (fmease) [inline compiler/rustc_hir_analysis/src/hir_ty_lowering/mod.rs:1]: I'm currently strongly leaning towards blocking this PR "on fixing #138711". I.e., implementing this in a slightly more principled manner rather than emitting artificial type inference error diagnostics depending on path segment counts which is quite fragile.

For example while e.g., `[T; ASSOC_CONST]` and `AssocTy` lead to your custom errors getting emitted, a simple change like `[T; self::ASSOC_CONST]` and `self::AssocTy` respectively — trivially bringing the segment count up to 2 — demonstrates that HIR ty lowering is already perfectly able to deal with such inputs if nudged a bit, emitting `ambiguous associated constant` and `ambiguous associated type` respectively (which originates from `probe_single_bound_for_assoc_item`).

Could you experiment with adjusting the necessary lowering methods to enable the existing machinery to handle these sorts of paths? To be totally transparent with you, I haven't thought *that* much about how much code that would affect.

Comment (fmease) [reply compiler/rustc_hir_analysis/src/hir_ty_lowering/mod.rs:1]: > I'm currently strongly leaning towards blocking this PR

The fact that the feature import_trait_associated_functions is quite recent (in design and implementation) and — for the AssocConst case — feature min_generic_const_args is still highly experimental and not yet backed by an RFC should be enough to justify my tentative decision.

File: compiler/rustc_hir_analysis/src/hir_ty_lowering/mod.rs (hunk 1 above)
Comment (fmease) [inline compiler/rustc_hir_analysis/src/hir_ty_lowering/mod.rs:2183]: This might seem minor but the phrasing "cannot infer type" isn't quite 'right' in this context since HIR ty lowering doesn't actually use type inference (in the `rustc_infer` sense) or trait solving in ItemCtxts (roughly "contexts where `_` is not permitted") when resolving associated types to projections, hence the phrasing "**ambiguous** associated type/constant" as used by `probe_single_bound…`

**Review by fmease — CHANGES_REQUESTED** [review]
I'm fine with lifting the restrictions from the resolver and with making HIR ty lowering responsible for dealing with it, although this PR would allow more code to compile under the unstable feature (`trait T { type A; } use T::A;` would start compiling (notice the lack of any use sites of `A`!)) plus glob imports, of course.

This deviates from the RFC. IIRC it's fine for me as a T-compiler member to approve such a change regardless and without T-lang input as long as we **clearly state all of this** in the tracking issue #134691, so any hypothetical future stabilization report and T-lang stabilization FCP can pick up on it.

File: compiler/rustc_hir_analysis/src/hir_ty_lowering/mod.rs
Comment (petrochenkov) [reply compiler/rustc_hir_analysis/src/hir_ty_lowering/mod.rs:1]: Ok, I'll look in a few days.

**Review by fmease — APPROVED** [review]
Thanks! One stylistic nit, then r=me
