### PR TITLE
Fix linking stage1 toolchain in `./x.py setup`

### LINKED ISSUE #92319: `x.py setup` stopped being able to link toolchains at some point
I tried this code on a fresh git clone of rust-lang/rust:

```
x.py setup library
```

I expected to see this happen: setup works without errors.

Instead, this happened: x.py gives an error:

```
Welcome to the Rust project! What do you want to do with x.py?
a) library: Contribute to the standard library
b) compiler: Contribute to the compiler itself
c) codegen: Contribute to the compiler, and also modify LLVM or codegen
d) tools: Contribute to tools which depend on the compiler, but do not modify it directly (e.g. rustdoc, clippy, miri)
e) user: Install Rust from source
Please choose one (a/b/c/d/e): b
`x.py` will now use the configuration at .../rust/src/bootstrap/defaults/config.compiler.toml

`rustup` failed to link stage 1 build to `stage1` toolchain
To manually link stage 1 build to `stage1` toolchain, run:

            `rustup toolchain link stage1 build/x86_64-unknown-linux-gnu/stage1`
```

### Meta

This feature was introduced in https://github.com/rust-lang/rust/pull/89212 and worked at that time. @Sl1mb0 do you have time to look into this? The original bug report was from Nazar Mokrynskyi [on Zulip](https://rust-lang.zulipchat.com/#narrow/stream/122652-new-members/topic/Building.2Ftesting.20rust.20itself.20for.20the.20first.20time), not sure their github username.

### PR DESCRIPTION
**Pull request by yerke**
Closes [92319](https://github.com/rust-lang/rust/issues/92319)

Fix linking stage1 toolchain in `./x.py setup`. I guess this can be considered a follow up to https://github.com/rust-lang/rust/pull/89212 by @Sl1mb0.

We create 2 directories and 1 file that are required by rustup to [link a custom toolchain from path](https://github.com/rust-lang/rustup/blob/5225e87a5d974ab5f1626bcb2a7b43f76ab883f0/src/toolchain.rs#L479-L497).

cc @jyn514 and @Mark-Simulacrum as they were active in https://github.com/rust-lang/rust/issues/89206

### CODE REVIEW

File: src/bootstrap/setup.rs [hunk 1]
```diff
@@ -219,6 +229,38 @@ fn try_link_toolchain(stage_path: &str) -> bool {
         .map_or(false, |output| output.status.success())
 }
 
+fn create_stage1_toolchain_placeholder_if_it_does_not_already_exist(stage_path: &str) -> bool {
```
Comment (Mark-Simulacrum) [inline src/bootstrap/setup.rs:232]:
```suggestion
fn ensure_stage1_toolchain_placeholder_exists(stage_path: &str) -> bool {
```

File: src/bootstrap/setup.rs [hunk 2]
```diff
@@ -219,6 +229,38 @@ fn try_link_toolchain(stage_path: &str) -> bool {
...
+    let mut pathbuf = PathBuf::from(stage_path);
+
+    pathbuf.push("lib");
+    if fs::create_dir_all(&pathbuf).is_err() {
+        return false;
+    };
+    pathbuf.pop();
```
Comment (Mark-Simulacrum) [inline src/bootstrap/setup.rs:239]: Rather than push/popping, I suspect a .join(...) may work essentially just as well.

File: src/bootstrap/setup.rs [hunk 3]
```diff
@@ -219,6 +229,38 @@ fn try_link_toolchain(stage_path: &str) -> bool {
...
+
+    pathbuf.push("bin");
+    if fs::create_dir_all(&pathbuf).is_err() {
+        return false;
+    };
+
+    pathbuf.push(format!("rustc{}", EXE_SUFFIX));
+
+    let file_already_exists =
+        fs::metadata(&pathbuf).ok().as_ref().map(fs::Metadata::is_file) == Some(true);
```
Comment (Mark-Simulacrum) [inline src/bootstrap/setup.rs:249]: I doubt we need to worry about it not being a file? path.exists() should be sufficient, I think.

Comment (yerke) [reply src/bootstrap/setup.rs:249]: I just checked that `path.exists()` returns true if the path is actually a directory and not a file. So I don't actually see harm in checking if it's a file.

File: src/bootstrap/setup.rs (hunk 2 above)
Comment (yerke) [reply src/bootstrap/setup.rs:239]: I borrowed code from https://github.com/rust-lang/rustup/blob/5225e87a5d974ab5f1626bcb2a7b43f76ab883f0/src/toolchain.rs#L479-L497. I will change it to use `.join()` instead.

File: src/bootstrap/setup.rs (hunk 3 above)
Comment (Mark-Simulacrum) [reply src/bootstrap/setup.rs:249]: This is just more complex and not really all that more helpful -- I'd prefer to avoid the extra complexity here.

Comment (yerke) [reply src/bootstrap/setup.rs]: Updated

File: src/bootstrap/setup.rs (hunk 2 above)
Comment (yerke) [reply src/bootstrap/setup.rs]: Updated

File: src/bootstrap/setup.rs (hunk 1 above)
Comment (yerke) [reply src/bootstrap/setup.rs]: Updated

**Comment by yerke** [comment]
@Mark-Simulacrum I resolved all your comments. Thanks.

**Comment by Mark-Simulacrum** [comment]
r=me once commits are squashed

**Comment by yerke** [comment]
r=Mark-Simulacrum

**Comment by yerke** [comment]
@Mark-Simulacrum That didn't work unfortunately...
