### PR TITLE
CFI: Fix types that implement Fn, FnMut, or FnOnce

### LINKED ISSUE #144641: Invalid CFI failure for and indirect call through a `Box<dyn Fn()>`
I tried this code and compiled it with CFI enabled (`-Clinker-plugin-lto -Clink-arg=-fuse-ld=lld -Zsanitizer=cfi`):

```rust
fn foo(a: u32) {}

struct Foo {
    a: Option<Box<dyn Fn(u32) + Sync + Send>>,
}

impl Foo {
    fn doit(&mut self) {
        let function = {
            if self.a.is_none() {
                self.a = Some(Box::new(foo));
            }
            Box::new(self.a.as_deref().unwrap())
        };
        function(0_u32);
    }
}

fn main() {
    let mut foo = Foo { a: None };
    foo.doit();
}
```

I expected to see this happen: the program executes successfully

Instead, this happened: I see a CFI failure.

### Meta

`rustc --version --verbose`:
```
rustc 1.87.0 (17067e9ac 2025-05-09)
binary: rustc
commit-hash: 17067e9ac6d7ecb70e50f92c1944e545188d2359
commit-date: 2025-05-09
host: x86_64-unknown-linux-gnu
release: 1.87.0
LLVM version: 20.1.1
```

This was initially found when compiling the [png](https://docs.rs/png/latest/png/) crate's example code.

### PR DESCRIPTION
**Pull request by rcvalle**
When looking for instances which could either be dynamically called through a vtable or through a concrete trait method, we missed `FnPtrShim`, instead only looking at `Item` and closure-likes. Fixes rust-lang/rust#144641.

cc @1c3t3a @Jakob-Koschel

### CODE REVIEW

File: compiler/rustc_sanitizers/src/cfi/typeid/itanium_cxx_abi/transform.rs [hunk 1]
```diff
@@ -453,6 +453,35 @@ pub(crate) fn transform_instance<'tcx>(
...
+            (LangItem::Fn, sym::call),
+            (LangItem::FnMut, sym::call_mut),
+            (LangItem::FnOnce, sym::call_once),
+        ];
+        for (lang_item, method_sym) in fn_traits {
+            if let Some(trait_id) = tcx.lang_items().get(lang_item) {
+                let items = tcx.associated_items(trait_id);
+                if let Some(call_method) =
+                    items.in_definition_order().find(|item| item.name() == method_sym)
+                {
```
Comment (compiler-errors) [inline compiler/rustc_sanitizers/src/cfi/typeid/itanium_cxx_abi/transform.rs]: This logic does a ton of unnecessary work. 

Just compute `if let Some(trait_def_id) = tcx.trait_of_assoc(instance.def_id())`, use `tcx.as_lang_item()` to turn it into a `LangItem`, and match on `Fn`/`FnMut`/`FnOnce`.

File: compiler/rustc_sanitizers/src/cfi/typeid/itanium_cxx_abi/transform.rs [hunk 2]
```diff
@@ -453,6 +453,35 @@ pub(crate) fn transform_instance<'tcx>(
...
+                    if instance.def_id() == call_method.def_id {
```
Comment (compiler-errors) [inline compiler/rustc_sanitizers/src/cfi/typeid/itanium_cxx_abi/transform.rs]: What kind of `InstanceKind` are we expecting here? This seems like it would perhaps overlap or interact with the logic above what you added, which seems problematic.

**Review by compiler-errors — CHANGES_REQUESTED** [review]
I'd like to see more explanation for the fix in this PR. Specifically, the issue and the PR don't actually describe what kind of CFI violation was being encountered here before, or how it's being fixed by this erasure?

The comment in https://github.com/rust-lang/rust/issues/144641#issuecomment-3153040732 mentions:

> The only special handling in the code is for closures, coroutines, and coroutine closures, but not for arbitrary types that implement these traits.

Does this make the code that *is* special-cased for closure-like types redundant?

**Comment by compiler-errors** [comment]
@maurer wrote a lot of this erasure logic, I'd be interested if he has a take on this approach as well

**Comment by maurer** [comment]
My first reaction here is that I think this is a bug in `implemented_method` rather than something that should be fixed via an additional clause in transform_instance - `implemented_method` should detect the `call_mut` implementation as an implemented method, and so the first non-closure clause should be triggering. I'll take a more in depth look in an hour or two when I get in to work.

**Comment by maurer** [comment]
Specifically, https://github.com/rust-lang/rust/commit/d5bf25c20edc1d383350b904d7fee650607bd3d2 seems to address this more simply - basically, it looks like I missed `FnPtrShim(def_id, _)`. I'm still taking a look over the other instance kinds to make sure that not casing out on only `Item` and `FnPtrShim` won't accidentally apply somewhere it shouldn't, but this seems to fix it a bit more cleanly - the problem was an unaccounted-for instance kind, not an unaccounted-for trait.

Update: It looks like the adjustment I'm proposing would also cause:
* `Virtual` and `VTableShim` to get double-processed, because we've already dealt with them. The generalization is mostly a no-op, except that the `InstanceKind` for `VTableShim` will become `Virtual`, which is perhaps misleading but should have no effect and `Virtual` instances will get their method index zeroed out.
* `ReifyShim` would get erased into `Virtual` - this would be a problem for KCFI, except this code is guarded by `USE_CONCRETE_SELF`, which gets forcibly enabled for `ReifyReason::FnPtr`.
* `ClosureOnceShim` and `ConstructCoroutineInClosureShim` should trip this, and occur *before* the check if something is closure-like. I wasn't able to easily detect any differences in behavior here, but I didn't do deep tracing. I think handling these via the closure-like code vs via the default impl code normalizes them the same way. We still need the closure normalizing code because *true* closures can't be normalized this way.
* `FutureDropPollShim`, `CloneShim`, `FnPtrAddrShim`, and `AsyncDropGlueCtorShim` would all match initially, but then be discarded because the traits they implement are not object safe.

This looks OK to me, and has the added benefit of automatically picking up new shim types when added.

If we wanted to be more conservative, we could instead do https://github.com/rust-lang/rust/commit/0026b9c666e0eb825f1755ae30b8a34b23ed78a8 which fixes the tests in question with a minimal change - it only re-normalizes `FnPtrShim`, and would require any future shims we want normalized to be explicitly added to the `default_or_shim` checker.

**Comment by rcvalle** [comment]
@maurer Thank you for your time looking at it! Much appreciated. I'm wondering whether we should change approach in this code and cover each case explicitly (like we do for encoding) so we could express our intent clearly and know when something is handled (or not) and the side effects of it (also clearly).

**Comment by rcvalle** [comment]
@maurer If you put a commit message on https://github.com/rust-lang/rust/commit/0026b9c666e0eb825f1755ae30b8a34b23ed78a8, I could cherry pick it into this PR, or if you have time to, feel free to send a PR for it. Thanks a lot! Much appreciated.

**Comment by maurer** [comment]
I added a commit message at https://github.com/maurer/rust/tree/cfi-fix - I hadn't bothered because I just expected you to squash it onto your commit if you agreed with the direction.

Re: being more explicit with casing out, I think maybe the way to do that (which should definitely be a future PR if at all) would be:

1. Split out `InstanceKind`s into
  a. Always vtable (or `Virtual`) (these should be unconditionally rewritten)
  b. Sometimes vtable (these should be rewritten only when the concrete flag isn't passed)
  c. Passthrough
2. Check to see if it would be possible to simplify the flow of our existing code based on that - right now, everything in the "always vtable" section still possibly falls through and gets processed by the "sometimes vtable" section when concrete isn't set, but I don't think that's load bearing, and probably just confuses things
3. Create an explicit enum that looks something like
```
enum RewriteKind {
  // Always rewrite
  Drop,
  Virtual(DefId),
  VTableShim(DefId),
  // Sometimes rewrite
  Default(DefId),
  Impl(DefId),
  Shim(DefId),
  Closure(InstanceKind),
  // Never rewrite
  Passthrough(InstanceKind),
}
```
4. We do the exhaustive careful conversion from `InstanceKind` to `RewriteKind`, and then have a separate method that takes the `RewriteKind` and actually does the (possible) rewrite.

I don't know how much maintenance this saves us, mostly depends on how often we're sprinkling new `InstanceKind`s in or whether we've missed any other `InstanceKind`s

**Comment by rcvalle** [comment]
@maurer Just picked it into this PR. Thank you! (I had to fix some compilation errors, but I believe the PR is going to be squashed before being merged anyway so it should be fine.)

I'll take a look at covering each case explicitly and your suggestion,  and send a separate PR and CC you when I've something. Thanks again!

File: compiler/rustc_sanitizers/src/cfi/typeid/itanium_cxx_abi/transform.rs [hunk 3]
```diff
@@ -458,6 +458,15 @@ pub(crate) fn transform_instance<'tcx>(
     instance
 }
 
+fn default_or_shim<'tcx>(tcx: TyCtxt<'tcx>, instance: Instance<'tcx>) -> Option<DefId> {
+    match instance.def {
+        ty::InstanceKind::Item(def_id) | ty::InstanceKind::FnPtrShim(def_id, _) => {
+            tcx.opt_associated_item(def_id).map(|item| item.def_id)
```
Comment (lcnr) [inline compiler/rustc_sanitizers/src/cfi/typeid/itanium_cxx_abi/transform.rs:464]: does `def_id` and `item.def_id` actually differ? I would expect these two to be the same.

File: compiler/rustc_sanitizers/src/cfi/typeid/itanium_cxx_abi/transform.rs [hunk 4]
```diff
@@ -458,6 +458,15 @@ pub(crate) fn transform_instance<'tcx>(
...
+        }
+        _ => None,
+    }
+}
+
 fn implemented_method<'tcx>(
```
Comment (lcnr) [inline compiler/rustc_sanitizers/src/cfi/typeid/itanium_cxx_abi/transform.rs:485]: comment pls

**Review by lcnr — COMMENTED** [review]
so if I understand this correctly, the issue here is that CFI doesn't allow calling methods which are not part of the the allowed list of `typeid`s?

So anything that intentionally enables dynamic calls, i.e. trait objects, needs to be converted to get a single shared typeid.

`transform_instance` does seem questionable to me :thinking: the resulting instance must never be used except to get the `fn_abi_of_instance` :thinking:

I feel like we do want an exhaustive match on the `InstanceKind` here. We have to handle async drop shims the same way as normal drops, don't we?

r=me on the change in the PR itself, it seems innocent enough

*[View changes since this review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/rust/144936/0060d5a2a8a86a31f6299311fe64b1d755a91c4f..fd887d36a2526af4b60925ad457c8e342a0a8318)*

File: compiler/rustc_sanitizers/src/cfi/typeid/itanium_cxx_abi/transform.rs (hunk 3 above)
Comment (rcvalle) [reply compiler/rustc_sanitizers/src/cfi/typeid/itanium_cxx_abi/transform.rs:464]: Unfortunately not, here we're getting the def_id of the default method implementation (or trait method definition). I even double checked and tried def_id to make sure they're not the same and it doesn't work.

File: compiler/rustc_sanitizers/src/cfi/typeid/itanium_cxx_abi/transform.rs (hunk 4 above)
Comment (rcvalle) [reply compiler/rustc_sanitizers/src/cfi/typeid/itanium_cxx_abi/transform.rs:485]: Done.
