### PR TITLE
miri: treat non-memory local variables properly for data race detection

### LINKED ISSUE #3242: Data race false positive due to delayed allocation optimization
The following code should be fine, but Miri raises an error:
```rust
use std::sync::atomic::Ordering::*;
use std::sync::atomic::*;

static P: AtomicPtr<u8> = AtomicPtr::new(core::ptr::null_mut());

fn main() {
    // Create the local variable, and initialize it.
    let mut val: u8 = 0;

    let t1 = std::thread::spawn(|| {
        while P.load(Relaxed).is_null() {
            std::hint::spin_loop();
        }
        unsafe {
            // Initialize `*P`.
            let ptr = P.load(Relaxed);
            *ptr = 127;
        }
    });

    // Actually generate memory for the local variable.
    // This is the time its value is actually written to memory:
    // that's *after* the thread above was spawned!
    P.store(std::ptr::addr_of_mut!(val), Relaxed);
    
    // Wait for the thread to be done.
    t1.join().unwrap();

    // Read initialized value.
    assert_eq!(val, 127);
}
```
The issue has been described well by CAD97 [here](https://internals.rust-lang.org/t/possible-false-positive-in-miri-race-detector/20081/10?u=ralfjung):

> Without having dived into Miri, it likely is a false positive due to places not being allocated into memory until their reference is taken. It's an optimization for most cases (there's a lot of bookkeeping happening for allocations in Miri) but results in a false positive here. Assuming that's a correct assessment, the fix would be to assign a timestamp corresponding to the local place initialization when reifying into an allocation, instead of the timestamp of the reification itself.

### PR DESCRIPTION
**Pull request by RalfJung**
Fixes https://github.com/rust-lang/miri/issues/3242

Miri has an optimization where some local variables are not represented in memory until something forces them to be stored in memory (most notably, creating a pointer/reference to the local will do that). However, for a subsystem triggering on memory accesses -- such as the data race detector -- this means that the memory access seems to happen only when the local is moved to memory, instead of at the time that it actually happens. This can lead to UB reports in programs that do not actually have UB.

This PR fixes that by adding machine hooks for reads and writes to such efficiently represented local variables. The data race system tracks those very similar to how it would track reads and writes to addressable memory, and when a local is moved to memory, the clocks get overwritten with the information stored for the local.

### CODE REVIEW

**Comment by saethlin** [comment]
I'll steal the review
r? saethlin

File: src/tools/miri/src/concurrency/data_race.rs [hunk 1]
```diff
@@ -1121,6 +1122,103 @@ impl VClockAlloc {
...
+    fn default() -> Self {
+        Self { write: VTimestamp::ZERO, write_type: NaWriteType::Allocate, read: VTimestamp::ZERO }
+    }
+}
+
+impl FrameState {
+    pub fn local_write(&self, local: mir::Local, storage_live: bool, machine: &MiriMachine<'_>) {
+        let current_span = machine.current_span();
+        let global = machine.data_race.as_ref().unwrap();
+        if global.race_detecting() {
```
Comment (saethlin) [inline src/tools/miri/src/concurrency/data_race.rs:1152]: I prefer writing these as an early return; I find it really helps prevent code running to the right and there's no hunting for the close brace to see if this covers the whole function.

File: compiler/rustc_const_eval/src/interpret/place.rs [hunk 2]
```diff
@@ -646,9 +647,13 @@ where
         assert!(dest.layout().is_sized(), "Cannot write unsized immediate data");
 
         match self.as_mplace_or_mutable_local(&dest.to_place())? {
-            Right((local_val, local_layout)) => {
+            Right((local_val, local_layout, local)) => {
                 // Local can be updated in-place.
                 *local_val = src;
+                // Call the machine hook (the data race detector needs to know about this write).
+                if !self.validation_in_progress() {
```
Comment (saethlin) [inline compiler/rustc_const_eval/src/interpret/place.rs:654]: Are these checks for `valiation_in_progress()` just an optimization, or are they required for correctness?

Comment (RalfJung) [reply compiler/rustc_const_eval/src/interpret/place.rs:654]: This matches the equivalent logic in `memory.rs`. There it is definitely required; we have some "administrative reads" that we don't want to show up in the aliasing model (specifically, the ones added in https://github.com/rust-lang/rust/pull/128942).

Here I am not sure if it is required, but it would seem odd to not make this consistent with the logic in `memory.rs`.
