### PR TITLE
transmute: use diagnostic item

### LINKED ISSUE #66075: Complete move to "diagnostic items"
With https://github.com/rust-lang/rust/pull/60966, we can avoid lang items and manual path matching for lints, and instead mark them in the code. But I think there are some places that could still be ported to the new system:

* [ ] The `InvalidValue` lint uses `match_def_path` for `transmute` -- somehow, using a diagnostic item did not work (`is_diagnostic_item` returns false).
* [x] Aren't `Rc` and `Arc` lang items just for diagnostics? Here's where they get used: https://github.com/rust-lang/rust/blob/f49f38871389041671cc710a044e8360091840a3/src/librustc_typeck/check/expr.rs#L879-L880
    And, indirectly, at
    https://github.com/rust-lang/rust/blob/f49f38871389041671cc710a044e8360091840a3/src/librustc_mir/borrow_check/error_reporting.rs#L720-L723
    So, I am not sure if those should be lang items or diagnostic items now? No language semantics is attached to them, the uses above are just in error messages from what I can see. 
* [x] There's also no language semantics attached to `MaybeUninit`; it is a lang item because it gets used in layout construction for generators. Doesn't really fit "diagnostics item" either, though. (EDIT: decided this makes more sense to remain a lang item)

@oli-obk @Centril any thoughts?

### PR DESCRIPTION
**Pull request by lcnr**
closes #66075, we now have no remaining uses of `match_def_path`  in the compiler while some uses still remain in `clippy`.

cc @RalfJung

### CODE REVIEW

**Comment by RalfJung** [comment]
> closes #66075, we now have no remaining uses of match_def_path in the compiler while some uses still remain in clippy.

Cool! However, this does not close #66075 as that one is also about making `Rc` and `Arc` not be lang items any more.

File: compiler/rustc_lint/src/context.rs [hunk 1]
```diff
@@ -720,6 +720,8 @@ impl<'tcx> LateContext<'tcx> {
     /// Anonymous scopes such as `extern` imports are matched with `kw::Invalid`;
     /// inherent `impl` blocks are matched with the name of the type.
     ///
+    /// If possible, consider using a `rustc_diagnostic_item` instead.
```
Comment (RalfJung) [inline compiler/rustc_lint/src/context.rs:723]: "possible" is a bit vague. This should only be done when it really is about diagnostics.

File: compiler/rustc_passes/src/diagnostic_items.rs [hunk 2]
```diff
@@ -100,6 +100,18 @@ fn collect<'tcx>(tcx: TyCtxt<'tcx>) -> FxHashMap<Symbol, DefId> {
 
     // Collect diagnostic items in this crate.
     tcx.hir().krate().visit_all_item_likes(&mut collector);
+    // FIXME(visit_all_item_likes): Foreign items are not visited
+    // here, so we have to manually look at them for now.
+    for foreign_module in tcx.foreign_modules(LOCAL_CRATE) {
```
Comment (RalfJung) [inline compiler/rustc_passes/src/diagnostic_items.rs:105]: Ah I guess this is why using a diagnostic item didn't work when I tried it?

The rest of the PR LGTM (aside from the comment nit), but this here I cannot review I'm afraid. Cc @oli-obk

File: library/core/src/intrinsics.rs [hunk 3]
```diff
@@ -1071,6 +1071,7 @@ extern "rust-intrinsic" {
     // NOTE: While this makes the intrinsic const stable, we have some custom code in const fn
     // checks that prevent its use within `const fn`.
     #[rustc_const_stable(feature = "const_transmute", since = "1.46.0")]
+    #[cfg(not(bootstrap), rustc_diagnostic_item = "transmute")]
```
Comment (RalfJung) [inline library/core/src/intrinsics.rs:1074]: Does this *have* to be `cfg(not(bootstrap))`? Seems like it would just be an unused diagnostic item otherwise which seems fine?

**Comment by lcnr** [comment]
`Rc` and `Arc` are already only `diagnostic_item`s, it seems like this has already been fixed

File: library/core/src/intrinsics.rs (hunk 3 above)
Comment (lcnr) [reply library/core/src/intrinsics.rs]: It is an unused attribute otherwise, as we never even look at this without the change to the collector.

Comment (oli-obk) [reply library/core/src/intrinsics.rs]: diagnostic items are all used. Rustc doesn't know whether clippy is going to use them.

File: compiler/rustc_lint/src/context.rs [hunk 4]
```diff
@@ -720,6 +720,9 @@ impl<'tcx> LateContext<'tcx> {
     /// Anonymous scopes such as `extern` imports are matched with `kw::Invalid`;
     /// inherent `impl` blocks are matched with the name of the type.
     ///
+    /// Instead of using this method, it is often preferable to instead use
+    /// `rustc_diagnostic_item` or a `lang_item`, which is less prone to errors.
```
Comment (jyn514) [inline compiler/rustc_lint/src/context.rs:724]: Can you explain why diagnostic items are less prone to errors? Is it because they're not tricked by re-exporting under a different name?

Comment (lcnr) [reply compiler/rustc_lint/src/context.rs:724]: It is both harder to have a typo and resilient to refactorings. Should I mention that in the docs directly?

Comment (jyn514) [reply compiler/rustc_lint/src/context.rs:724]: That would be great :)
