### PR TITLE
Compute the layout of uninhabited structs

### LINKED ISSUE #64506: ICE when const evaluating UB
This ICEs on stable, probably since March 2018, but it requires the user to do UB in constants, so...

I think a possible fix would be to enable validation in const eval (cc @RalfJung 	), though we should benchmark the perf considerations around that first. Alternatively we can just not ICE here and instead emit an error.

```rust
#[derive(Copy, Clone)]
pub struct ChildStdin {
    inner: AnonPipe,
}

#[derive(Copy, Clone)]
enum AnonPipe {}

const FOO: () = {
    union Foo {
        a: ChildStdin,
        b: (),
    }
    let x = unsafe { Foo { b: () }.a };
    let x = &x.inner;
};

fn main() {}

```

([Playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=61deca72fdd9f46ae61a1e5cfdcee9a9))

Errors:

```
   Compiling playground v0.0.1 (/playground)
warning: field is never used: `inner`
 --> src/main.rs:3:5
  |
3 |     inner: AnonPipe,
  |     ^^^^^^^^^^^^^^^
  |
  = note: #[warn(dead_code)] on by default

warning: constant item is never used: `FOO`
  --> src/main.rs:9:1
   |
9  | / const FOO: () = {
10 | |     union Foo {
11 | |         a: ChildStdin,
12 | |         b: (),
...  |
15 | |     let x = &x.inner;
16 | | };
   | |__^

thread 'rustc' panicked at 'Tried to access field 0 of union with 0 fields', src/librustc_mir/interpret/place.rs:360:17
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.37.0 (eae3437df 2019-08-13) running on x86_64-unknown-linux-gnu

note: compiler flags: -C codegen-units=1 -C debuginfo=2 --crate-type bin

note: some of the compiler flags provided by cargo are hidden

error: Could not compile `playground`.

To learn more, run the command again with --verbose.

```

### PR DESCRIPTION
**Pull request by oli-obk**
fixes #64506

r? @eddyb

### CODE REVIEW

File: src/test/ui/issues/issue-64506.rs [hunk 1]
```diff
@@ -0,0 +1,20 @@
+// check-pass
```
Comment (Centril) [inline src/test/ui/issues/issue-64506.rs]: Can we move the test to `ui/consts/`?

File: src/librustc/ty/layout.rs [hunk 2]
```diff
@@ -825,10 +825,18 @@ impl<'tcx> LayoutCx<'tcx, TyCtxt<'tcx>> {
                     });
                     (present_variants.next(), present_variants.next())
                 };
-                if present_first.is_none() {
-                    // Uninhabited because it has no variants, or only absent ones.
-                    return tcx.layout_raw(param_env.and(tcx.types.never));
-                }
+                let present_first = if present_first.is_none() {
```
Comment (Centril) [inline src/librustc/ty/layout.rs]: This would be cleaner as a `match` with a guard on `None if def.is_enum() =>` imo.

File: src/librustc_mir/interpret/place.rs [hunk 3]
```diff
@@ -377,20 +377,17 @@ where
...
             }
             layout::FieldPlacement::Union(count) => {
-                // FIXME(#64506) `UninhabitedValue` can be removed when this issue is resolved
-                if base.layout.abi == Abi::Uninhabited {
-                    throw_unsup!(UninhabitedValue);
-                }
                 assert!(field < count as u64,
-                        "Tried to access field {} of union with {} fields", field, count);
+                        "Tried to access field {} of union {:#?} with {} fields",
+                        field, base.layout, count);
```
Comment (eddyb) [inline src/librustc_mir/interpret/place.rs]: Can you add this assert to `FieldPlacement::offset`? And even add an `offset_u64`, if you want (I guess `offset(i)` can just call `offset_u64(i as u64)`? or maybe we just want an `i: impl Into<u64>` on `offset`).

Comment (oli-obk) [reply src/librustc_mir/interpret/place.rs]: `u64` does not implement `From<usize>` :(

**Review by eddyb — APPROVED** [review]

**Comment by alex** [comment]
@Centril I assume you noticed, but just in case, FYI every single build appears to be failing on a connection error to the azure ubuntu apt repos.

**Comment by pietroalbini** [comment]
@bors treeclosed-

This build seems to be ok.
