### PR TITLE
Fix `-Z print-type-sizes` for generators with discriminant field ordered first

### LINKED ISSUE #105589: Nightly 1.68.0 failed to compile tokio with `-Zprint-type-sizes`
When running `RUSTFLAGS=-Zprint-type-sizes cargo +nightly build --release >/tmp/output` on [`cargo-binstall`](https://github.com/cargo-bins/cargo-binstall), `rustc` failed to compile tokio 1.23.0 with features sync, macros, time, io-util, net, time, rt, rt-multi-thread, fs, parking_lot, process and signal.

### Meta

`rustc --version --verbose`:
```
rustc 1.68.0-nightly (bdb07a8ec 2022-12-11)
binary: rustc
commit-hash: bdb07a8ec8e77aa10fb84fae1d4ff71c21180bb4
commit-date: 2022-12-11
host: aarch64-apple-darwin
release: 1.68.0-nightly
LLVM version: 15.0.6
```

### Error output

Command `RUSTFLAGS=-Zprint-type-sizes cargo +nightly build --release >/tmp/output`:

```
thread 'rustc' panicked at 'max_variant_size 145 > 144 overall_size', compiler/rustc_session/src/code_stat
s.rs:177:25
stack backtrace:
   0:        0x1012da874 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::f
mt::hc6661a943383350c
   1:        0x10132bb2c - core::fmt::write::hc08c1be3b97e4ce1
   2:        0x1012cdf2c - std::io::Write::write_fmt::he580cbfa9bcbf52a
   3:        0x1012da688 - std::sys_common::backtrace::print::h4528ca61d4f80cf9
   4:        0x1012dd138 - std::panicking::default_hook::{{closure}}::haca2542124caa09a
   5:        0x1012dce90 - std::panicking::default_hook::h8935004a9fbeb3ac
   6:        0x1094d4894 - rustc_driver[99fe8fd09beedb97]::DEFAULT_HOOK::{closure#0}::{closure#0}
   7:        0x1012dd830 - std::panicking::rust_panic_with_hook::h45cd5cdcffa82620
   8:        0x1012dd628 - std::panicking::begin_panic_handler::{{closure}}::h48e9312c235b6ab0
   9:        0x1012dacdc - std::sys_common::backtrace::__rust_end_short_backtrace::h5673d65f31c7265c
  10:        0x1012dd384 - _rust_begin_unwind
  11:        0x101357660 - core::panicking::panic_fmt::h9e2ef469fe5ca9e4
  12:        0x10d3e1ae8 - <rustc_session[7b5d2ae7e7b7fd4b]::code_stats::CodeStats>::print_type_sizes
  13:        0x1094b1358 - rustc_span[7ba562c801adb65a]::with_source_map::<core[4ca30972f44092a6]::result:
:Result<(), rustc_errors[5a4db3fef831c659]::ErrorGuaranteed>, rustc_interface[559bb8e04aee6111]::interface
::run_compiler<core[4ca30972f44092a6]::result::Result<(), rustc_errors[5a4db3fef831c659]::ErrorGuaranteed>
, rustc_driver[99fe8fd09beedb97]::run_compiler::{closure#1}>::{closure#0}::{closure#0}>
  14:        0x1094a4dd8 - <scoped_tls[cd5ab3257e1c42c]::ScopedKey<rustc_span[7ba562c801adb65a]::SessionGl
obals>>::set::<rustc_interface[559bb8e04aee6111]::interface::run_compiler<core[4ca30972f44092a6]::result::
Result<(), rustc_errors[5a4db3fef831c659]::ErrorGuaranteed>, rustc_driver[99fe8fd09beedb97]::run_compiler:
:{closure#1}>::{closure#0}, core[4ca30972f44092a6]::result::Result<(), rustc_errors[5a4db3fef831c659]::Err
orGuaranteed>>
  15:        0x109479ae0 - std[6cca96a9eb021ef0]::sys_common::backtrace::__rust_begin_short_backtrace::<ru
stc_interface[559bb8e04aee6111]::util::run_in_thread_pool_with_globals<rustc_interface[559bb8e04aee6111]::
interface::run_compiler<core[4ca30972f44092a6]::result::Result<(), rustc_errors[5a4db3fef831c659]::ErrorGu
aranteed>, rustc_driver[99fe8fd09beedb97]::run_compiler::{closure#1}>::{closure#0}, core[4ca30972f44092a6]
::result::Result<(), rustc_errors[5a4db3fef831c659]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[4ca
30972f44092a6]::result::Result<(), rustc_errors[5a4db3fef831c659]::ErrorGuaranteed>>
  16:        0x109460740 - <<std[6cca96a9eb021ef0]::thread::Builder>::spawn_unchecked_<rustc_interface[559
bb8e04aee6111]::util::run_in_thread_pool_with_globals<rustc_interface[559bb8e04aee6111]::interface::run_co
mpiler<core[4ca30972f44092a6]::result::Result<(), rustc_errors[5a4db3fef831c659]::ErrorGuaranteed>, rustc_
driver[99fe8fd09beedb97]::run_compiler::{closure#1}>::{closure#0}, core[4ca30972f44092a6]::result::Result<
(), rustc_errors[5a4db3fef831c659]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[4ca30972f44092a6]::r
esult::Result<(), rustc_errors[5a4db3fef831c659]::ErrorGuaranteed>>::{closure#1} as core[4ca30972f44092a6]
::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  17:        0x1012e5c4c - std::sys::unix::thread::Thread::new::thread_start::h6a3ce04994adbf58
  18:        0x18062e06c - __pthread_deallocate

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE
%2C+T-compiler&template=ice.md

note: rustc 1.68.0-nightly (bdb07a8ec 2022-12-11) running on aarch64-apple-darwin

note: compiler flags: --crate-type lib -C opt-level=z -C panic=abort -C linker-plugin-lto -C codegen-units
=1 -C strip=symbols -Z print-type-sizes

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
   Compiling chrono v0.4.23
error: could not compile `tokio`
warning: build failed, waiting for other jobs to finish...

```

### LINKED ISSUE #105591: ICE: -Zprint-type-sizes:  generators: overlap-locals.rs
### Code
from `src/test/ui/generator/overlap-locals.rs`
```Rust
// run-pass

#![feature(generators)]

fn main() {
    let a = || {
        {
            let w: i32 = 4;
            yield;
            println!("{:?}", w);
        }
        {
            let z: i32 = 7;
            yield;
            println!("{:?}", z);
        }
    };
    assert_eq!(8, std::mem::size_of_val(&a));
}
```

### Meta

`rustc --version --verbose`:
```
rustc 1.68.0-nightly (bdb07a8ec 2022-12-11)
binary: rustc
commit-hash: bdb07a8ec8e77aa10fb84fae1d4ff71c21180bb4
commit-date: 2022-12-11
host: x86_64-unknown-linux-gnu
release: 1.68.0-nightly
LLVM version: 15.0.6
```

### Error output
`rustc src/test/ui/generator/overlap-locals.rs  -Zprint-type-sizes`
```
<output>
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
print-type-size type: `std::fmt::Formatter<'_>`: 64 bytes, alignment: 8 bytes
print-type-size     field `.buf`: 16 bytes
print-type-size     field `.width`: 16 bytes
print-type-size     field `.precision`: 16 bytes
print-type-size     field `.flags`: 4 bytes
print-type-size     field `.fill`: 4 bytes
print-type-size     field `.align`: 1 bytes
print-type-size     end padding: 7 bytes
print-type-size type: `std::fmt::Arguments<'_>`: 48 bytes, alignment: 8 bytes
print-type-size     field `.fmt`: 16 bytes
print-type-size     field `.pieces`: 16 bytes
print-type-size     field `.args`: 16 bytes
print-type-size type: `std::option::Option<std::fmt::Arguments<'_>>`: 48 bytes, alignment: 8 bytes
print-type-size     variant `Some`: 48 bytes
print-type-size         field `.0`: 48 bytes
print-type-size     variant `None`: 0 bytes
print-type-size type: `unwind::libunwind::_Unwind_Exception`: 32 bytes, alignment: 8 bytes
print-type-size     field `.exception_class`: 8 bytes
print-type-size     field `.exception_cleanup`: 8 bytes
print-type-size     field `.private`: 16 bytes
print-type-size type: `std::panic::Location<'_>`: 24 bytes, alignment: 8 bytes
print-type-size     field `.file`: 16 bytes
print-type-size     field `.line`: 4 bytes
print-type-size     field `.col`: 4 bytes
print-type-size type: `std::option::Option<&[std::fmt::rt::v1::Argument]>`: 16 bytes, alignment: 8 bytes
print-type-size     variant `Some`: 16 bytes
print-type-size         field `.0`: 16 bytes
print-type-size     variant `None`: 0 bytes
print-type-size type: `std::option::Option<usize>`: 16 bytes, alignment: 8 bytes
print-type-size     discriminant: 8 bytes
print-type-size     variant `Some`: 8 bytes
print-type-size         field `.0`: 8 bytes
print-type-size     variant `None`: 0 bytes
print-type-size type: `[closure@std::rt::lang_start<()>::{closure#0}]`: 8 bytes, alignment: 8 bytes
print-type-size     end padding: 8 bytes
print-type-size type: `[generator@/home/matthias/vcs/github/rust/src/test/ui/generator/overlap-locals.rs:6:13: 6:15]`: 8 bytes, alignment: 4 bytes
print-type-size     discriminant: 1 bytes
print-type-size     variant `Suspend0`: 8 bytes
print-type-size         padding: 3 bytes
print-type-size         field `.w`: 4 bytes, alignment: 4 bytes
print-type-size     variant `Suspend1`: 8 bytes
print-type-size         padding: 3 bytes
print-type-size         field `.z`: 4 bytes, alignment: 4 bytes
print-type-size     variant `Unresumed`: 0 bytes
print-type-size     variant `Returned`: 0 bytes
print-type-size     variant `Panicked`: 0 bytes
thread '<unnamed>' panicked at 'max_variant_size 9 > 8 overall_size', compiler/rustc_session/src/code_stats.rs:177:25
stack backtrace:
   0:     0x7fb6295667da - std::backtrace_rs::backtrace::libunwind::trace::h3bfe63c4aecfa0e2
                               at /rustc/bdb07a8ec8e77aa10fb84fae1d4ff71c21180bb4/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x7fb6295667da - std::backtrace_rs::backtrace::trace_unsynchronized::h978c02637c6cb8f9
                               at /rustc/bdb07a8ec8e77aa10fb84fae1d4ff71c21180bb4/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7fb6295667da - std::sys_common::backtrace::_print_fmt::h86a708dcb1665377
                               at /rustc/bdb07a8ec8e77aa10fb84fae1d4ff71c21180bb4/library/std/src/sys_common/backtrace.rs:65:5
   3:     0x7fb6295667da - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hdbf89765373fb801
                               at /rustc/bdb07a8ec8e77aa10fb84fae1d4ff71c21180bb4/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x7fb6295c92ee - core::fmt::write::hbf11a3bb4e6d2aba
                               at /rustc/bdb07a8ec8e77aa10fb84fae1d4ff71c21180bb4/library/core/src/fmt/mod.rs:1208:17
   5:     0x7fb629556c65 - std::io::Write::write_fmt::hd68261eacc348bbd
                               at /rustc/bdb07a8ec8e77aa10fb84fae1d4ff71c21180bb4/library/std/src/io/mod.rs:1682:15
   6:     0x7fb6295665a5 - std::sys_common::backtrace::_print::ha8e375b58cdeca4a
                               at /rustc/bdb07a8ec8e77aa10fb84fae1d4ff71c21180bb4/library/std/src/sys_common/backtrace.rs:47:5
   7:     0x7fb6295665a5 - std::sys_common::backtrace::print::he3086c07df1167ca
                               at /rustc/bdb07a8ec8e77aa10fb84fae1d4ff71c21180bb4/library/std/src/sys_common/backtrace.rs:34:9
   8:     0x7fb6295692ef - std::panicking::default_hook::{{closure}}::h0c12a9095c948e43
                               at /rustc/bdb07a8ec8e77aa10fb84fae1d4ff71c21180bb4/library/std/src/panicking.rs:267:22
   9:     0x7fb62956902b - std::panicking::default_hook::h1ae5478ad617eb24
                               at /rustc/bdb07a8ec8e77aa10fb84fae1d4ff71c21180bb4/library/std/src/panicking.rs:286:9
  10:     0x7fb629569b0c - std::panicking::rust_panic_with_hook::h63a24f957ccb5d93
                               at /rustc/bdb07a8ec8e77aa10fb84fae1d4ff71c21180bb4/library/std/src/panicking.rs:688:13
  11:     0x7fb6295698a9 - std::panicking::begin_panic_handler::{{closure}}::h1499194b322f3b28
                               at /rustc/bdb07a8ec8e77aa10fb84fae1d4ff71c21180bb4/library/std/src/panicking.rs:579:13
  12:     0x7fb629566c8c - std::sys_common::backtrace::__rust_end_short_backtrace::h5569dab7b5c29ca8
                               at /rustc/bdb07a8ec8e77aa10fb84fae1d4ff71c21180bb4/library/std/src/sys_common/backtrace.rs:137:18
  13:     0x7fb6295695b2 - rust_begin_unwind
                               at /rustc/bdb07a8ec8e77aa10fb84fae1d4ff71c21180bb4/library/std/src/panicking.rs:575:5
  14:     0x7fb6295c5cd3 - core::panicking::panic_fmt::h81b99a9e904184d4
                               at /rustc/bdb07a8ec8e77aa10fb84fae1d4ff71c21180bb4/library/core/src/panicking.rs:64:14
  15:     0x7fb62d29e324 - <rustc_session[8c69ddbebe7c913d]::code_stats::CodeStats>::print_type_sizes
  16:     0x7fb62ba7f3ce - <rustc_interface[649c07bcaa826da7]::interface::Compiler>::enter::<rustc_driver[c8d19d3afee4bdc9]::run_compiler::{closure#1}::{closure#2}, core[5029ced7f280b950]::result::Result<core[5029ced7f280b950]::option::Option<rustc_interface[649c07bcaa826da7]::queries::Linker>, rustc_errors[4c9e772a36c84051]::ErrorGuaranteed>>
  17:     0x7fb62ba79f78 - rustc_span[61aa4dc18b27dd6c]::with_source_map::<core[5029ced7f280b950]::result::Result<(), rustc_errors[4c9e772a36c84051]::ErrorGuaranteed>, rustc_interface[649c07bcaa826da7]::interface::run_compiler<core[5029ced7f280b950]::result::Result<(), rustc_errors[4c9e772a36c84051]::ErrorGuaranteed>, rustc_driver[c8d19d3afee4bdc9]::run_compiler::{closure#1}>::{closure#0}::{closure#0}>
  18:     0x7fb62ba79a65 - <scoped_tls[5892410b08f734b5]::ScopedKey<rustc_span[61aa4dc18b27dd6c]::SessionGlobals>>::set::<rustc_interface[649c07bcaa826da7]::interface::run_compiler<core[5029ced7f280b950]::result::Result<(), rustc_errors[4c9e772a36c84051]::ErrorGuaranteed>, rustc_driver[c8d19d3afee4bdc9]::run_compiler::{closure#1}>::{closure#0}, core[5029ced7f280b950]::result::Result<(), rustc_errors[4c9e772a36c84051]::ErrorGuaranteed>>
  19:     0x7fb62ba79052 - std[ebc28cf04754cd8d]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[649c07bcaa826da7]::util::run_in_thread_pool_with_globals<rustc_interface[649c07bcaa826da7]::interface::run_compiler<core[5029ced7f280b950]::result::Result<(), rustc_errors[4c9e772a36c84051]::ErrorGuaranteed>, rustc_driver[c8d19d3afee4bdc9]::run_compiler::{closure#1}>::{closure#0}, core[5029ced7f280b950]::result::Result<(), rustc_errors[4c9e772a36c84051]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[5029ced7f280b950]::result::Result<(), rustc_errors[4c9e772a36c84051]::ErrorGuaranteed>>
  20:     0x7fb62c0ecfee - <<std[ebc28cf04754cd8d]::thread::Builder>::spawn_unchecked_<rustc_interface[649c07bcaa826da7]::util::run_in_thread_pool_with_globals<rustc_interface[649c07bcaa826da7]::interface::run_compiler<core[5029ced7f280b950]::result::Result<(), rustc_errors[4c9e772a36c84051]::ErrorGuaranteed>, rustc_driver[c8d19d3afee4bdc9]::run_compiler::{closure#1}>::{closure#0}, core[5029ced7f280b950]::result::Result<(), rustc_errors[4c9e772a36c84051]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[5029ced7f280b950]::result::Result<(), rustc_errors[4c9e772a36c84051]::ErrorGuaranteed>>::{closure#1} as core[5029ced7f280b950]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  21:     0x7fb62d5da623 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::heae35e1afc4b24eb
                               at /rustc/bdb07a8ec8e77aa10fb84fae1d4ff71c21180bb4/library/alloc/src/boxed.rs:2000:9
  22:     0x7fb62d5da623 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h82b51f76f931d41c
                               at /rustc/bdb07a8ec8e77aa10fb84fae1d4ff71c21180bb4/library/alloc/src/boxed.rs:2000:9
  23:     0x7fb62d5da623 - std::sys::unix::thread::Thread::new::thread_start::h66d484584973ef33
                               at /rustc/bdb07a8ec8e77aa10fb84fae1d4ff71c21180bb4/library/std/src/sys/unix/thread.rs:108:17
  24:     0x7fb6293068fd - <unknown>
  25:     0x7fb629388a60 - <unknown>
  26:                0x0 - <unknown>
```

</p>
</details>

### PR DESCRIPTION
**Pull request by compiler-errors**
Fixes #105589
Fixes #105591

### CODE REVIEW

**Comment by compiler-errors** [comment]
Confirmed manually that #105589 is fixed by this by running `RUSTFLAGS=-Zprint-type-sizes cargo +rust build --release`.

File: src/test/ui/print_type_sizes/generator_discr_placement.rs [hunk 1]
```diff
@@ -0,0 +1,25 @@
+// compile-flags: -Z print-type-sizes
+// build-pass
+// ignore-pass
+
+// Tests a generator that has its discriminant as the *final* field.
+
+// Avoid emitting panic handlers, like the rest of these tests...
```
Comment (Nilstrieb) [inline src/test/ui/print_type_sizes/generator_discr_placement.rs:7]: If the other tests do this already as it says it's fine but this should probably be a lib crate instead.

File: compiler/rustc_ty_utils/src/layout.rs [hunk 2]
```diff
@@ -975,12 +975,15 @@ fn variant_info_for_generator<'tcx>(
...
                 variant_size = upvars_size;
             }
-            // We need to add the discriminant size back into min_size, since it is subtracted
-            // later during printing.
-            variant_size += match tag_encoding {
-                TagEncoding::Direct => tag.size(cx),
-                _ => Size::ZERO,
-            };
+
+            if layout.fields.offset(tag_field) >= variant_size {
```
Comment (Nilstrieb) [inline compiler/rustc_ty_utils/src/layout.rs:979]: Nit: It took me a while to understand why this change was correct, probably mostly because the `variant_size` variable is a little confusingly named. Maybe something like `last_field_end` would better?

Thinking about this a little more, what this code really wants to do is `variant_size.max(tag_end)`, maybe that would also make it simpler.

**Review by Noratrieb — CHANGES_REQUESTED** [review]

File: compiler/rustc_ty_utils/src/layout.rs (hunk 2 above)
Comment (Nilstrieb) [reply compiler/rustc_ty_utils/src/layout.rs:979]: This is true, all of this code is trying to fit generator layout into a normal layout shaped hole and it's not going great. The current name is fine too and yeah, spending too much time on this is probably not worth it.

Comment (Nilstrieb) [reply compiler/rustc_ty_utils/src/layout.rs:979]: But a quick comment would be nice.

**Review by Noratrieb — APPROVED** [review]
Thanks for adding the comment, r=me once CI is green.
