### PR TITLE
rust_trans: struct argument over ffi were passed incorrectly in some situations. Change cabi_x86_64 to better model the sysv abi.

### LINKED ISSUE #25594: FFI:  wrong argument passing order on linux x86_64 C ABI
On linux x86_64, FFI passes arguments in wrong order if the function has more than 6 arguments, with struct (passed by value) mixed.

## Reproduce

`bug.c`

```c
#include <stdio.h>

struct Rect {
        int l;
        int t;
        int r;
        int b;
};

void bug(int a, int b, int c, int d,
        int e, struct Rect f, int g, int h) {
        fprintf(stderr, "%d %d %d %d %d\n",
                a, b, c, d, e);
        fprintf(stderr, "%d %d %d %d\n",
                f.l, f.t, f.r, f.b);
        fprintf(stderr, "%d %d\n", g, h);
}
```

`bug.rs`

```rust
#[repr(C)]
struct Rect {
    l: i32,
    t: i32,
    r: i32,
    b: i32,
}

#[link(name = "bug")]
extern "C" {
    fn bug(a: i32, b: i32, c: i32, d: i32,
           e: i32, f: Rect, g: i32, h: i32);
}

fn main() {
    let r = Rect {
        l: 10,
        t: 20,
        r: 30,
        b: 40
    };
    unsafe { bug(1, 2, 3, 4, 5, r, 6, 7); }
}
```

```bash
gcc -fPIC -o libbug.so -shared bug.c
rustc -L. bug.rs
./bug
```

Rust version

```
rustc 1.0.0 (a59de37e9 2015-05-13) (built 2015-05-14)
binary: rustc
commit-hash: a59de37e99060162a2674e3ff45409ac73595c0e
commit-date: 2015-05-13
build-date: 2015-05-14
host: x86_64-unknown-linux-gnu
release: 1.0.0
```

Expected output:
1 2 3 4 5
10 20 30 40
6 7

Actual output:
1 2 3 4 5
30 40 6 32740
10 7

## Reason
Only 6 arguments can be passed by registers (see http://www.x86-64.org/documentation/abi.pdf).
In the above example, `a, b, c, d, e, g` should be passed in registers, `f & h` should be passed on stack.

But Rust FFI mistakenly passes `a, b, c, d, e` and lower 8bytes of `f` in registers. This is wrong
according to [abi.pdf](http://www.x86-64.org/documentation/abi.pdf), page 20:

> If there are no registers available for any eightbyte of an argument, the whole
> argument is passed on the stack. If registers have already been assigned for some
> eightbytes of such an argument, the assignments get reverted.

### PR DESCRIPTION
**Pull request by luqmana**
Fixes #25594.

### CODE REVIEW

File: src/test/run-make/extern-fn-struct-passing-abi/test.c [hunk 1]
```diff
@@ -0,0 +1,118 @@
...
+// SysV ABI:
+// a, b, c, d, e should be in registers
+// s should be byval pointer
+void byval_rect(int a, int b, int c, int d, int e, struct Rect s) {
+    assert(a == 1);
+    assert(b == 2);
+    assert(c == 3);
+    assert(d == 4);
+    assert(e == 5);
+    assert(s.a == 1);
```
Comment (arielb1) [inline src/test/run-make/extern-fn-struct-passing-abi/test.c]: I would prefer to use different numeric values here (and in all other tests).

File: src/test/run-make/extern-fn-struct-passing-abi/test.rs [hunk 2]
```diff
@@ -0,0 +1,78 @@
...
+    fn sret_byval_struct(a: i32, b: i32, c: i32, d: i32, s: Rect) -> BiggerRect;
+
+    // SysV ABI:
+    // a, b should be in registers
+    // return should be in a hidden sret pointer
+    // s should be split across 2 registers
+    fn sret_split_struct(a: i32, b: i32, s: Rect) -> BiggerRect;
+}
+
+fn main() {
```
Comment (arielb1) [inline src/test/run-make/extern-fn-struct-passing-abi/test.rs]: I would prefer to assert on the return values.

**Comment by brson** [comment]
Nice fixes and good test coverage. Thanks @luqmana

File: src/test/run-make/extern-fn-struct-passing-abi/test.rs (hunk 2 above)
Comment (luqmana) [inline src/test/run-make/extern-fn-struct-passing-abi/test.rs]: Added some `assert_eq`.

File: src/librustc_trans/trans/cabi_x86_64.rs [hunk 3]
```diff
@@ -410,18 +410,46 @@ pub fn compute_abi_info(ccx: &CrateContext,
         }
     }
 
-    let mut arg_tys = Vec::new();
-    for t in atys {
-        let ty = x86_64_ty(ccx, *t, |cls| cls.is_pass_byval(), Attribute::ByVal);
-        arg_tys.push(ty);
-    }
+    let mut avail_regs = 6; // RDI, RSI, RDX, RCX, R8, R9
```
Comment (eefriedman) [inline src/librustc_trans/trans/cabi_x86_64.rs]: The ABI rules require counting both integer and floating-point registers.

Comment (luqmana) [inline src/librustc_trans/trans/cabi_x86_64.rs]: Yes but, this is a kinda simplistic approach similar to what clang does since we need to explicitly tell LLVM whether a struct is passed via some hidden pointer (marked byval) or split up/passed as a FCA. The actual specifics of which register or whether it goes on the stack is handled by LLVM.

Comment (eefriedman) [inline src/librustc_trans/trans/cabi_x86_64.rs]: You still need to track them separately... suppose you have a struct which contains a `long long` and a `double`.  If you run out of xmm registers, the struct needs to be explicitly byval instead of being split up: otherwise, the integer part of the struct ends up in a register.  (clang has similar logic; see https://github.com/llvm-mirror/clang/blob/335cc9e22d8b977d83a12297fc85b6f6be965689/lib/CodeGen/TargetInfo.cpp#L2804 .)

Comment (luqmana) [inline src/librustc_trans/trans/cabi_x86_64.rs]: Right, forget about that. Updated, thanks!

File: src/librustc_trans/trans/cabi_x86_64.rs [hunk 4]
```diff
@@ -410,18 +410,53 @@ pub fn compute_abi_info(ccx: &CrateContext,
...
+            } else {
+                // split into sized chunks passed individually
+                int_regs -= needed_int;
+                sse_regs -= needed_sse;
+            }
+            in_mem
+        }, Attribute::ByVal);
+        arg_tys.push(ty);
+
+        // An integer or pointer parameter
```
Comment (eefriedman) [inline src/librustc_trans/trans/cabi_x86_64.rs]: This comment needs to be updated.

**Comment by huonw** [comment]
cc @rust-lang/compiler

File: src/test/run-make/extern-fn-struct-passing-abi/test.c [hunk 5]
```diff
@@ -0,0 +1,191 @@
...
+// Licensed under the Apache License, Version 2.0 <LICENSE-APACHE or
+// http://www.apache.org/licenses/LICENSE-2.0> or the MIT license
+// <LICENSE-MIT or http://opensource.org/licenses/MIT>, at your
+// option. This file may not be copied, modified, or distributed
+// except according to those terms.
+
+#include <assert.h>
+
+struct Rect {
+    int a;
```
Comment (nagisa) [inline src/test/run-make/extern-fn-struct-passing-abi/test.c]: Could this use `int32_t` rather than `int`? Rust counterpart uses explicitly sized integers.

**Comment by nagisa** [comment]
I would also like to see a test with a struct which is so big it doesn’t fit into the registers (i.e. 7 integers and/or 9 floats). Other than that, I don’t see anything wrong with this patch.

**Comment by luqmana** [comment]
@nagisa Added a big struct case.

**Comment by bkoropoff** [comment]
Looks good, thanks.

r+

**Comment by bkoropoff** [comment]
@bors r+

Nice test coverage.  Thanks!

**Comment by brson** [comment]
@bors r+

Not sure why @bors ignored @bkoropoff

**Comment by SimonSapin** [comment]
What happened to this? http://buildbot.rust-lang.org/builders/auto-win-gnu-64-opt/builds/912 is now a 404 error.

**Comment by luqmana** [comment]
#29012 should address the windows failure. Updated the test comments and the test makefile to use not call gcc and friends directly but instead use the utilities that abstract platform differences.
