### PR TITLE
Detect confusing unicode characters and show the alternative...

### LINKED ISSUE #25957: Better Error Message When Parsing Greek Question Mark (and similar confusing characters)
Current:

```rust
fn main() {
    let a = 5;
}
```

```
<anon>:2:14: 2:15 error: unknown start of token: \u{37e}
<anon>:2     let a = 5;
                      ^
playpen: application terminated with error code 101
```

Do *you* know what the error message is here? It's that I'm using the [Greek Question Mark](http://www.fileformat.info/info/unicode/char/037e/index.htm) instead of a semicolon, causing a parse error. And while there is an error message, it's extremely opaque.

A better error message would actually print the token that is in error directly in the error message, e.g. as @niconii suggsted:

```
error: expected one of `.`, `;`, or an operator, found unicode character U+37E `;`
```

Using the human readable U+37E over the Rust encoding thing (`\u{37E}`) would definitely help.

In the specific case of the Greek Question Mark, it looks exactly like a semicolon, and symbols that look like other symbols are pretty common in Unicode, but perfectly enumerable. If we had a table of unicode point to actually used symbol, we could display an even better notice message:

```
error: expected one of `.`, `;`;, or an operator, found unicode character U+37E `;`

note: Unicode character U+37E (Greek Question Mark) looks like a semicolon, but is not.
```

### PR DESCRIPTION
**Pull request by ghost**
fixes #25957

### CODE REVIEW

**Comment by Wafflespeanut** [comment]
@Manishearth So, here's some rough artwork for you :)

I suppose we have to add tests for that?

**Comment by Wafflespeanut** [comment]
Ah! limited to 100 chars (unlike Servo)...

File: src/libsyntax/parse/lexer/unicode_chars.rs [hunk 1]
```diff
@@ -0,0 +1,156 @@
+const ASCII_ARRAY: &'static [(char, &'static str)] = &[('_', "Low Line"), ('-', "Hyphen-Minus"),
```
Comment (Manishearth) [inline src/libsyntax/parse/lexer/unicode_chars.rs]: This needs the MPL header

File: src/libsyntax/parse/lexer/unicode_chars.rs [hunk 2]
```diff
@@ -0,0 +1,156 @@
...
+                                                       ('{', "Left Curly Bracket"),
+                                                       ('}', "Right Curly Bracket"),
+                                                       ('*', "Asterisk"), ('/', "Solidus"),
+                                                       ('\\', "Reverse Solidus"),
+                                                       ('&', "Ampersand"), ('+', "Plus Sign"),
+                                                       ('<', "Less-Than Sign"),
+                                                       ('=', "Equals Sign"),
+                                                       ('>', "Greater-Than Sign"), ];
+
+const UNICODE_ARRAY: &'static [char] = &['ߺ', '﹍', '﹎', '﹏', '‐', '‑', '‒', '–', '﹘', '⁃', '˗',
```
Comment (Manishearth) [inline src/libsyntax/parse/lexer/unicode_chars.rs]: For readability I'd rather have an array which has the format `(unicode_char, unicode_name, ascii_char)`, and search the ascii array to find the string. Indexes are brittle and hard to tweak.

File: src/libsyntax/parse/lexer/unicode_chars.rs [hunk 3]
```diff
@@ -0,0 +1,156 @@
+const ASCII_ARRAY: &'static [(char, &'static str)] = &[('_', "Low Line"), ('-', "Hyphen-Minus"),
+                                                       (',', "Comma"), (';', "Semicolon"),
```
Comment (Manishearth) [inline src/libsyntax/parse/lexer/unicode_chars.rs]: I'd also like a link to the source list of unicode thingies

File: src/libsyntax/parse/lexer/unicode_chars.rs [hunk 4]
```diff
@@ -0,0 +1,156 @@
...
+                                                      (14, "Coptic Capital Letter Old Coptic Esh"), ];
+
+pub fn check_for_substitution(ch: char) -> Option<String> {
+    UNICODE_ARRAY
+    .iter()
+    .position(|&c| c == ch)
+    .map(|idx| {
+        let (ascii_pos, u_name) = SUB_ARRAY[idx];
+        let (sub_char, sub_name) = ASCII_ARRAY[ascii_pos];
+        format!("Unicode character '{}' ({}) looks much like a '{}' ({}), but it's not.",
```
Comment (Manishearth) [inline src/libsyntax/parse/lexer/unicode_chars.rs]: I don't think the "a" is necessary. "Unicode char 'f' (...) looks much like 'g' (..), but it's not"

**Comment by Manishearth** [comment]
Also, yes, there should be some parse-fail tests for this.

File: src/libsyntax/parse/lexer/unicode_chars.rs [hunk 5]
```diff
@@ -0,0 +1,178 @@
...
+    ('?', "Question Mark"),
+    ('.', "Period"),
+    ('\'', "Quote"),
+    ('(', "Left Parenthesis"),
+    (')', "Right Parenthesis"),
+    ('{', "Left Curly Brace"),
+    ('}', "Right Curly Brace"),
+    ('*', "Asterisk"),
+    ('/', "Slash"),
+    ('\\', "Back Slash"),
```
Comment (Manishearth) [inline src/libsyntax/parse/lexer/unicode_chars.rs]: single word

File: src/libsyntax/parse/lexer/unicode_chars.rs [hunk 6]
```diff
@@ -0,0 +1,178 @@
...
+const ASCII_ARRAY: &'static [(char, &'static str)] = &[
+    ('_', "Underscore"),
+    ('-', "Minus/Hyphen"),
+    (',', "Comma"),
+    (';', "Semicolon"),
+    (':', "Colon"),
+    ('!', "Exclamation Mark"),
+    ('?', "Question Mark"),
+    ('.', "Period"),
+    ('\'', "Quote"),
```
Comment (Manishearth) [inline src/libsyntax/parse/lexer/unicode_chars.rs]: "Single quote"

File: src/libsyntax/parse/lexer/unicode_chars.rs [hunk 7]
```diff
@@ -0,0 +1,178 @@
...
+    .position(|&(c, _, _)| c == ch)
+    .map(|idx| {
+        let (_, u_name, ascii_char) = UNICODE_ARRAY[idx];
+        match ASCII_ARRAY.iter().position(|&(c, _)| c == ascii_char) {
+            Some(i) => {
+                let (_, ascii_name) = ASCII_ARRAY[i];
+                format!("Unicode character '{}' ({}) looks much like '{}' ({}), but it's not.",
+                        ch, u_name, ascii_char, ascii_name)
+            },
+            None => panic!("substitution character not found for '{}'", ch),
```
Comment (Manishearth) [inline src/libsyntax/parse/lexer/unicode_chars.rs]: Perhaps we should just return `None` here? I don't like panicking.

Alternatively, call `span_bug`.

File: src/libsyntax/parse/lexer/unicode_chars.rs [hunk 8]
```diff
@@ -0,0 +1,178 @@
...
+pub fn check_for_substitution(ch: char) -> Option<String> {
+    UNICODE_ARRAY
+    .iter()
+    .position(|&(c, _, _)| c == ch)
+    .map(|idx| {
+        let (_, u_name, ascii_char) = UNICODE_ARRAY[idx];
+        match ASCII_ARRAY.iter().position(|&(c, _)| c == ascii_char) {
+            Some(i) => {
+                let (_, ascii_name) = ASCII_ARRAY[i];
+                format!("Unicode character '{}' ({}) looks much like '{}' ({}), but it's not.",
```
Comment (Manishearth) [inline src/libsyntax/parse/lexer/unicode_chars.rs]: Do this after adding the test so that you don't have to rebuild, but this error message should start lowercase and not have a period at the end. (be sure to update the test with the error message)

**Comment by Wafflespeanut** [comment]
@Manishearth I've made the changes and now I've gone for a variation of what you'd suggested (I've used `StringReader` in our checking method, which emits stuff based on the situation). Also, I need some clarification regarding the test. In the test, I'm checking for an error which is something `rustc` was doing even before the change. Since I've only added the `help` comment along with it, is the test really necessary? or, should we test this in a different way?

File: src/test/parse-fail/unicode-chars.rs [hunk 9]
```diff
@@ -0,0 +1,16 @@
...
+// http://www.apache.org/licenses/LICENSE-2.0> or the MIT license
+// <LICENSE-MIT or http://opensource.org/licenses/MIT>, at your
+// option. This file may not be copied, modified, or distributed
+// except according to those terms.
+
+// compile-flags: -Z parse-only
+
+fn main() {
+    let y = 0;
+    //~^ ERROR unknown start of token: \u{37e}
```
Comment (Manishearth) [inline src/test/parse-fail/unicode-chars.rs]: put the help message here too

**Comment by Wafflespeanut** [comment]
@Manishearth r?

File: src/libsyntax/parse/lexer/unicode_chars.rs [hunk 10]
```diff
@@ -0,0 +1,188 @@
...
+    ('>', "Greater-Than Sign"), ];
+
+pub fn check_for_substitution(reader: &StringReader, ch: char) {
+    UNICODE_ARRAY
+    .iter()
+    .position(|&(c, _, _)| c == ch)
+    .map(|idx| {
+        let (_, u_name, ascii_char) = UNICODE_ARRAY[idx];
+        let span = make_span(reader.last_pos, reader.pos);
+        match ASCII_ARRAY.iter().position(|&(c, _)| c == ascii_char) {
```
Comment (Manishearth) [inline src/libsyntax/parse/lexer/unicode_chars.rs]: use `.find`, not `.position`.

File: src/libsyntax/parse/lexer/unicode_chars.rs [hunk 11]
```diff
@@ -0,0 +1,188 @@
...
+    ('&', "Ampersand"),
+    ('+', "Plus Sign"),
+    ('<', "Less-Than Sign"),
+    ('=', "Equals Sign"),
+    ('>', "Greater-Than Sign"), ];
+
+pub fn check_for_substitution(reader: &StringReader, ch: char) {
+    UNICODE_ARRAY
+    .iter()
+    .position(|&(c, _, _)| c == ch)
```
Comment (Manishearth) [inline src/libsyntax/parse/lexer/unicode_chars.rs]: `.find`, not `.position`

**Comment by Manishearth** [comment]
LGTM, small nits involving style.

For future reference, you should be rarely indexing arrays and things in Rust. Most of the time you should use iterators (`.position`+indexing doesn't count :smile: ), and iterators are safer in that they can't cause additional panics due to out of bounds indexing.

**Comment by nikomatsakis** [comment]
This patch looks pretty decent. I second @Manishearth's suggestions. Also, note that there is a tidy error because some of the lines in the `parse-fail` test are more than 100 characters. You can add a comment like `// ignore-tidy-linelength` on that file.

**Comment by Wafflespeanut** [comment]
@nikomatsakis @Manishearth Agreed, thanks! (and done). r?

File: src/libsyntax/diagnostic.rs [hunk 12]
```diff
@@ -174,6 +174,9 @@ impl SpanHandler {
         self.handler.emit(Some((&self.cm, sp)), msg, Bug);
         panic!(ExplicitBug);
     }
+    pub fn span_bug_no_panic(&self, sp: Span, msg: &str) {
+        self.handler.emit(Some((&self.cm, sp)), msg, Bug);
+    }
```
Comment (Manishearth) [inline src/libsyntax/diagnostic.rs]: I forgot to mention, can we add `self.handler.bump_err_count();` here too?

**Comment by Manishearth** [comment]
@bors r+

thanks!

**Comment by Wafflespeanut** [comment]
@Manishearth Thank you! :)

**Comment by Havvy** [comment]
:heart: :heartbeat: :heart:

**Comment by Manishearth** [comment]
:grinning: Congrats on your first PR!

**Comment by brson** [comment]
Nice polish.

**Comment by huonw** [comment]
Is there a reason this doesn't include U+201C LEFT DOUBLE QUOTATION MARK `“` and U+201D RIGHT DOUBLE QUOTATION MARK `”` as possible subsitutions for `"`? (If not, I can submit a patch to add them.)

**Comment by Manishearth** [comment]
No reason. It contains the single quotes. I did Ctrl-F for those, but didn't bother to check the double quotes.

Go ahead!

**Comment by Wafflespeanut** [comment]
It's again worth mentioning that this still doesn't have all the substitutions - only the printable ones from http://www.unicode.org/Public/security/revision-06/confusables.txt. So, feel free to add more :)

**Comment by huonw** [comment]
Oh, I think I see why QUOTATION MARK was missed: things (including that) are considered confusable with APOSTROPHE, APOSTROPHE rather than ".

**Comment by Manishearth** [comment]
The universe is starting to hit and appreciate this feature https://twitter.com/joeranweiler/status/678691374292590593 :D
