### PR TITLE
Fix inconsistent rounding of 0.5 when formatted to 0 decimal places

### LINKED ISSUE #70336: Float Display with fixed precision output uses inconsistent rounding rules
Rust's f32 formatting seems to follow inconsistent rounding rules when rounding to a fixed output precision.

```rust
fn main() {
  for i in 0..=10 {
      let nf = (i as f32) + 0.5f32;
      println!("{:4} -> {:2.0} ; {:5} -> {:3.0}", nf, nf, -nf, -nf);
  }
}
```

Output ([Playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=05bcc5570b84b256ce15347fb776451b)):

```plain
 0.5 ->  1 ;  -0.5 ->  -1
 1.5 ->  2 ;  -1.5 ->  -2
 2.5 ->  2 ;  -2.5 ->  -2
 3.5 ->  4 ;  -3.5 ->  -4
 4.5 ->  4 ;  -4.5 ->  -4
 5.5 ->  6 ;  -5.5 ->  -6
 6.5 ->  6 ;  -6.5 ->  -6
 7.5 ->  8 ;  -7.5 ->  -8
 8.5 ->  8 ;  -8.5 ->  -8
 9.5 -> 10 ;  -9.5 -> -10
10.5 -> 10 ; -10.5 -> -10
```

I get this output on Linux x86-64 with both rustc 1.42.0 (b8cedc004 2020-03-09) and rustc 1.44.0-nightly (f509b26a7 2020-03-18). I have not tested on other systems, and have not yet tested with f64.

Most inputs are rounded following the rule of rounding half to the nearest integer, but 0.5 and -0.5 are rounded away from zero instead.

When rounding 0.5 to an integer both 0 or 1 are correct outputs, so this may not be a bug. However it seems strange that the round-half-to-even rule should be followed for 1.5, 2.5, and up while a different rule is followed for 0.5.

By comparison, my Python and C versions followed round-half-to-even consistently (rounding 0.5 to 0), though I don't know that they provide any *guarantee* to follow that rule.

Cross-reference: I originally posted about this on the user forum. [Rounding mode for fixed precision float Display format?](https://users.rust-lang.org/t/rounding-mode-for-fixed-precision-float-display-format/39799)

### PR DESCRIPTION
**Pull request by ajtribick**
As described in #70336, when displaying values to zero decimal places the value of 0.5 is rounded to 1, which is inconsistent with the display of other half-integer values which round to even.

From testing the flt2dec implementation, it looks like this comes down to the condition in the fixed-width Dragon implementation where an empty buffer is treated as a case to apply rounding up. I believe the change below fixes it and updates only the relevant tests.

Nevertheless I am aware this is very much a core piece of functionality, so please take a very careful look to make sure I haven't missed anything. I hope this change does not break anything in the wider ecosystem as having a consistent rounding behaviour in floating point formatting is in my opinion a useful feature to have.

Resolves #70336

### CODE REVIEW

**Comment by ajtribick** [comment]
I've run a comparison for the formats `{:.0}` `{:.1}` and `{:.9}` for all positive finite `f32` values, the only example affected was 0.5 in format `{:.0}`.

**Comment by ajtribick** [comment]
It would probably also make sense to document the round-ties-to-even behaviour, any preferences for where to do that?

**Comment by scottmcm** [comment]
Oh!  I hadn't realized it was *just* `0.5` with the problem.  That pushes me to "this is just a bug", not really a decision to be made.  (Still worth a relnotes mention, but might not even need an FCP.)

@rust-lang/libs-api would you be comfortable calling this a bug that can just be fixed, or do you need an FCP for it?
@rustbot label +I-libs-api-nominated

File: library/core/tests/fmt/float.rs [hunk 1]
```diff
@@ -5,7 +5,7 @@ fn test_format_f64() {
     assert_eq!("10", format!("{:.0}", 9.9f64));
     assert_eq!("9.8", format!("{:.1}", 9.849f64));
     assert_eq!("9.9", format!("{:.1}", 9.851f64));
-    assert_eq!("1", format!("{:.0}", 0.5f64));
+    assert_eq!("0", format!("{:.0}", 0.5f64));
```
Comment (scottmcm) [inline library/core/tests/fmt/float.rs:8]: Suggestion: in addition to this change here, add s new `test_format_rounds_ties_to_even` test with a whole bunch of examples like those now in the PR discussion.  Just as a pseudo-documentation way of communicating to anyone tweaking things in future that, yes, this definitely is supposed to be working like this.

Comment (ajtribick) [reply library/core/tests/fmt/float.rs:8]: Thanks, have added these for `f32` and `f64`, including some exponentials for good measure. Let me know if you want any specific additional examples.

**Comment by blueglyph** [comment]
> Quick demonstration that .0 is rounding odd while the other numbers of decimal places are rounding even:
> 
> ```
> [src/main.rs:2] format!("{:.0}", 0.5) = "1"
> [src/main.rs:3] format!("{:.1}", 0.25) = "0.2"
> [src/main.rs:4] format!("{:.1}", 0.75) = "0.8"
> [src/main.rs:5] format!("{:.2}", 0.125) = "0.12"
> [src/main.rs:6] format!("{:.2}", 0.875) = "0.88"
> [src/main.rs:7] format!("{:.3}", 0.0625) = "0.062"
> ```
> 
> https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=a0ee562de13b361cc6a729d64e482ae8

I'm sorry if I'm misunderstanding, I found a lot of other values, as shown in #70336 (for "to even" as well as "away from zero"). I was originally thinking it was supposed to round away from zero, but if fmt is supposed to round to even, I can adapt my test to hunt all the values down.

[For example](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=228bac8ebc6c10947b4a6ba935e0127a):

> [src/main.rs:9] format!("{:.1}", 0.35) = "0.3"
> [src/main.rs:10] format!("{:.2}", 0.155) = "0.15"
> [src/main.rs:11] format!("{:.2}", 0.165) = "0.17"

**Comment by scottmcm** [comment]
> `[src/main.rs:9] format!("{:.1}", 0.35) = "0.3"`
> `[src/main.rs:10] format!("{:.2}", 0.155) = "0.15"`
> `[src/main.rs:11] format!("{:.2}", 0.165) = "0.17"`

Remember that anything that's not an integer power of two doesn't actually exist.

`0.35_f64` is the most convenient way to write the floating point value that's *exactly* 

0.34999999999999997779553950749686919152736663818359375​

And thus it rounds down <https://float.exposed/0x3fd6666666666666>

Similarly, 0.155 and 0.165 are

0.1549999999999999988897769753748434595763683319091796875​
0.1650000000000000077715611723760957829654216766357421875​

And thus they're not actually ties either.

It makes sense that you'd get about 50% of them rounding the other way, because for things that aren't representable exactly, you'd expect about 50% of them to be slightly too big and 50% of them to be slightly too small.

(I also made this mistake originally, but realized in time, and thus [my examples above](https://github.com/rust-lang/rust/pull/102935#issuecomment-1285988234) all use fractions where the denominator is a power of two -- ½, ¼, ¾, ⅛, ⅞, 1⁄16.)

**Comment by ajtribick** [comment]
@blueglyph - none of your examples is actually a tie, as they cannot be represented exactly in a finite-length binary floating point format. A necessary condition for a number to have a finite-length binary floating point representation is that they are rational numbers that can be written as an irreducible fraction $p/q, q=2^a, a \in \mathbb{N}_0$.[^1] In the case of your examples, the irreducible representations are:

* 0.35 = 35/100 = 7/20
* 0.155 = 155/1000 = 31/200
* 0.165 = 165/1000 = 33/200

In each case, the denominator contains at least one factor of 5, therefore it cannot be represented exactly in a finite-length binary floating point format. The actual value that is stored is an approximation that may be slightly larger or smaller than the value you requested: for an `f64` (which is the default type here):

```
[src/main.rs:39] write_exact_normal_f64(0.35) = "0.34999999999999997779553950749686919152736663818359375"
[src/main.rs:40] write_exact_normal_f64(0.155) = "0.1549999999999999988897769753748434595763683319091796875"
[src/main.rs:41] write_exact_normal_f64(0.165) = "0.1650000000000000077715611723760957829654216766357421875"
```
https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=e54cb125d214b3a7556d1a211e2b1542

As you can see, the exact value resulting from `0.35` is slightly less than 0.35, so rounds down to `0.3`. The exact value resulting from `0.155` is slightly less than 0.155, so rounds down to `0.15`. The exact value resulting from `0.165` is slightly greater than 0.165, so rounds up to `0.17`.

[^1]: this is not sufficient for a format like `f32` or `f64`, which can only store a limited number of binary digits.

**Comment by blueglyph** [comment]
@scottmcm @ajtribick 
You're right that they are not round values, but I thought it was precisely the problem solved by those algorithms. I'm not familiar enough with Grisu3/Dragon4 but if I take the decoded significand and base-10 exponent in the case of Dragonbox, I get those (u64, i32) values:

```text
0.35  => sig=3500000000000000, exp=-16
0.155 => sig=1550000000000000, exp=-16
0.175 => sig=1750000000000000, exp=-16
```

I suppose the current algorithms operate differently. Yet it's strange that it fails on 50% of the ties, that's a lot.

**Comment by ajtribick** [comment]
@blueglyph - as I understand it, Dragonbox is an algorithm for producing the shortest representation of a floating point value (i.e. the operation corresponding to the `{}` format string: without a specified precision), not a floating point value rounded to a specified number of decimal places. This is a different operation and not necessarily the same as what you would get by operating on the decimal representation produced by the shortest representation algorithm.

**Comment by blueglyph** [comment]
> @blueglyph - as I understand it, Dragonbox is an algorithm for producing the shortest roundtrippable representation of a floating point value (i.e. the operation corresponding to the `{}` format string: without a specified precision), not a floating point value rounded to a specified number of decimal places. This is a different operation and not necessarily the same as what you would get by operating on the decimal representation produced by the shortest representation algorithm.
> 

Dragonbox is an algorithm to convert a binary floating-point value into a correctly rounded decimal representation. From there I don't see what you wouldn't be able to reduce the precision as you wish. But it is arguably another algorithm than the one used.

**Comment by blueglyph** [comment]
> @blueglyph Note that floating-point algorithms are expected to treat the floating point number as if the represented value was exactly the desired value, and not to attempt to divine whether it came from rounding something else.
 
I would agree for _operations_ on floating-points (*), but I'm not convinced it's true for their _decimal representation_, since we know the base 2 representation is not exactly the desired value, as we saw earlier.

(*) although they are rounded to even to prevent bias errors, so in a way we are already "attempting to divine" whether they should be pre-processed in the case of accumulation.

> That's why, for example, it's absolutely correct that [`PI.sin()` is not zero](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=90ead6809724faeda49c9b614342dc06). `PI` is very close to π, but is not exactly π. So "turn it into a rounded string" also follows those rules, and even if there's a tie in the ±½ULP range around the exact floating point number, that doesn't mean it follows the tie rules. It's only a tie if the floating-point number itself is _exactly_ on a tie.

PI is an irrational number, so the problem is different, and we're not applying the perfect `sin` function either but only an approximation. But I see what you mean by that.

**Comment by ajtribick** [comment]
> Dragonbox is an algorithm to convert a binary floating-point value into a correctly rounded decimal representation. From there I don't see what you wouldn't be able to reduce the precision as you wish. But it is arguably another algorithm than the one used.

The output of Dragonbox is "correctly rounded" in the sense that it gives the shortest possible decimal representation of the value that can be parsed to give back the exact same input. It does not produce the exact representation of the numerical value of the variable. Note that rounding twice is *not* equivalent to rounding once, e.g. in decimal mathematics:

* 1.47 rounded to 1 decimal place is 1.5, 1.5 rounded to 0 decimal places is 2.
* 1.47 rounded to 0 decimal places is 1.

Reducing the precision of the Dragonbox output is likewise performing double rounding, and will lead to different results than rounding the value directly. The value of `0.35_f64` *is* less than 0.35, and thus should be rounded down.

**Comment by scottmcm** [comment]
> but I'm not convinced it's true for their _decimal representation_, since we know the base 2 representation is not exactly the desired value, as we saw earlier.

I'm not sure what you mean by decimal representation here.

Do you agree that this is correct?
```
format!("{:.1}", 3152519739159347.0 / 9007199254740992.0) => "0.3"
```
<https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=57517cb288ef19ff42707ea1e866e4dc>

**Comment by blueglyph** [comment]
I'm sorry this is going out of the initial topic, but this claims to solve #70336 and my argument is about that part. If more appropriate, it could be discussed elsewhere.

Grisu, like Dragonbox, aim to convert a binary-coded floating points to a decimal representation which is correct (in the sense mentioned earlier, the parsed decimal representation yields the same binary coding). Here the coding is typically IEEE-754, with a current focus on double precision.

The above conclusion "thus should be rounded down when rounding to 1 decimal place" seems strange to me, because there is no way to assert that.

For example, 0.35 is coded like this:

`6305039478318694*2^-54 or 0x16666666666666*2^0xffca => 0.34999999999999997779553950749686919152736663818359375`

The value has been rounded to the 54-bit normalized mantissa using the round-even method, and indeed it's not a tie anymore (in decimal representation). If I increase the mantissa, I get this value:

`6305039478318695*2^-54 or 0x16666666666667*2^0xffca => 0.350000000000000033306690738754696212708950042724609375` 

which is on the other side of the tie. So we see here that the error introduced when parsing "0.35" and initially rounding the value to code it as an f64 doesn't allow us to deduce on which side of the tie the initial value was.

Thus the operation that Dragonbox (or Grisu, Ryu, etc) does to minimize the output length while preserving the information and keeping a "correct" output, is not wrong. And it looks like it's more likely to be what the initial value was when it matters:
- if the initial value was 0.35, that is what we get
- if the initial value was 0.349999999999999978, likely as a result of a calculation, does it matter if the displayed value is 0.35? No, because the error margin is the same.

At least that's how I understand the asymmetric problem of coding and displaying floating-point values respectively in base 2 and 10.

If we come back to the initial problem to solve, the current solution seems to be wrong in about 50% of the cases, which is a lot. So I'm only wondering whether there could be another problem than just the case of 0.5, but maybe in the scope of another code change.

I'll stop here, however, and sorry again if that was not the place.

> I'm not sure what you mean by decimal representation here.
> 
> Do you agree that this is correct?
> 
> ```
> format!("{:.1}", 3152519739159347.0 / 9007199254740992.0) => "0.3"
> ```

I mean by that the decimal interpretation of the value which is coded in binary (IEEE-754). How the value is printed, if you will. Hopefully the first part of my post already clarified that. :)

I don't see the point of the last question.

**Comment by ajtribick** [comment]
> I'm sorry this is going out of the initial topic, but this claims to solve #70336 and my argument is about that part. If more appropriate, it could be discussed elsewhere.

I claim this issue claims to solve #70336 because it addresses the issue as described in the very first post of that issue: the rounding of half-integer values follows round-ties-to-even rules except for the case of 0.5.

If you need to have 0.35 behave as exactly halfway between 0.3 and 0.4, finite-length binary floating point types like `f32` and `f64` are not appropriate since they cannot represent these values, you should use a decimal floating point type instead.

**Comment by m-ou-se** [comment]
> **libs-api**  would you be comfortable calling this a bug that can just be fixed, or do you need an FCP for it?

We discussed this last week. We don't think this needs an FCP, it seems like a regular bug fix.

**Comment by Manishearth** [comment]
If you might want it as a bisection point it probably ought to be rollup=never, i was about to include it in a rollup :smile: 

@bors rollup=never

**Comment by scottmcm** [comment]
I couldn't find any actual failures here, and apparently neither could @rust-log-analyzer, so
@bors retry
