### PR TITLE
fix soundness issue in `make_contiguous`

### LINKED ISSUE #79808: VecDeque: length 0 underflow and bogus values from pop_front(), triggered by a certain sequence of reserve(), push_back(), make_contiguous(), pop_front()
This is my first bug report, so please correct me s if I miss anything :-)

I use VecDeque<u8> in a toy application (https://github.com/ayourtch/flex-sftp-server) which is handling external reads in a loop, and does possible partial handling of the input.

My pattern is I call reserve(N) before push_back() N times, then make_contiguous(), then doing some pop_front(). I noticed the app was behaving badly, and was able to generate a stand-alone test case which shows the bug.

The code is pretty boring and repetitive, so I put it at https://github.com/ayourtch/deq-bug/ to avoid spamming here.

Just issue "cargo run" after cloning out that code, and look for the word "BUG" within the terminal output:

According to the docs, pop_front() on an empty VecDeque should return None. 

Instead, this happens: 

```
pop: Some(75)
pop: Some(6e)
pop: Some(74)
pop: Some(75)
deq len: 0
pop: Some(2f)
BUG ^^^
deq len: 31
pop: Some(75)
pop: Some(62)
pop: Some(75)
pop: Some(6e)
```

If I set the boolean "do_reserve" to be false, thus getting rid of all the reserve() calls, I get the expected behavior:

```
pop: Some(75)
pop: Some(6e)
pop: Some(74)
pop: Some(75)
deq len: 0
pop: None
BUG ^^^
deq len: 0
pop: None
pop: None
pop: None
pop: None
pop: None
```

The same happens if I set "do_make_contiguous" to false as well - so calling both functions is a prerequisite to trigger the bug.
The same thing happens in debug and release builds.

### Meta

The below is the version I found it in, but thanks a lot to Steve Klabnik for also testing it on nightly and getting the same buggy behavior.

`rustc --version --verbose`:
```
rustc 1.48.0 (7eac88abb 2020-11-16)
binary: rustc
commit-hash: 7eac88abb2e57e752f3302f02be5f3ce3d7adfb4
commit-date: 2020-11-16
host: x86_64-unknown-linux-gnu
release: 1.48.0
LLVM version: 11.0

```

### PR DESCRIPTION
**Pull request by lcnr**
fixes #79808

### CODE REVIEW

File: library/alloc/src/collections/vec_deque/mod.rs [hunk 1]
```diff
@@ -2839,7 +2839,7 @@ impl<T> From<VecDeque<T>> for Vec<T> {
             let len = other.len();
             let cap = other.cap();
 
-            if other.head != 0 {
+            if other.tail != 0 {
```
Comment (lcnr) [inline library/alloc/src/collections/vec_deque/mod.rs:2842]: this bug was previously unreachable because `is_contiguous` returned false if the `head` was `0`.

uff

File: library/alloc/src/collections/vec_deque/tests.rs [hunk 2]
```diff
@@ -210,6 +210,20 @@ fn make_contiguous_small_free() {
...
+    dq.push_front('B');
+    dq.push_front('A');
+    dq.push_back('C');
+    dq.make_contiguous();
+    let expected_tail = 0;
+    let expected_head = 3;
+    assert_eq!(expected_tail, dq.tail);
+    assert_eq!(expected_head, dq.head);
+    assert_eq!((&['A', 'B', 'C'] as &[_], &[] as &[_]), dq.as_slices());
+}
```
Comment (camelid) [inline library/alloc/src/collections/vec_deque/tests.rs:225]: Do you want to write a version of this that uses `Box`es so that we ensure it doesn't segfault?

Comment (lcnr) [reply library/alloc/src/collections/vec_deque/tests.rs:225]: that shouldn't matter i think. The reason this could segfault is if the result is wrong. But as the used algorithm doesn't depend on `T` asserting that it is correct for `i32` also means that it would be correct for `Box` and therefore can't segfault.

Comment (camelid) [reply library/alloc/src/collections/vec_deque/tests.rs:225]: Probably, but I figured better safe than sorry :)

Comment (lcnr) [reply library/alloc/src/collections/vec_deque/tests.rs:225]: yeah, don't have the capacity for this rn though.

**Comment by spastorino** [comment]
[discussed](https://zulip-archive.rust-lang.org/238009tcompilermeetings/51074weeklymeeting2020121054818.html#219487424) in T-compiler meeting.

@rustbot modify labels: beta-accepted

**Comment by Mark-Simulacrum** [comment]
This seems ok, I'd like to get it merged ASAP so we can get testing to the extent possible. @bors r+ p=1

I admit the code is pretty high-context I think in terms of being able to follow it.

**Comment by spastorino** [comment]
[discussed](https://zulip-archive.rust-lang.org/238009tcompilermeetings/51074weeklymeeting2020121054818.html#219490333) in T-compiler meeting.

@rustbot modify labels: stable-accepted

**Comment by camelid** [comment]
(I removed `stable-nominated` because it's been accepted.)

**Comment by Mark-Simulacrum** [comment]
The process for stable and beta nominations is the same - until they happen, both nominated and stable should be left. Reading.

**Comment by camelid** [comment]
Oops, didn't realize that! Sorry.
