### PR TITLE
Drop temporaries created in a condition, even if it's a let chain

### LINKED ISSUE #100513: let_chains desugaring is wrong
I tried this code: [playground](https://play.rust-lang.org/?version=beta&mode=debug&edition=2021&gist=c1ff3da556b18b34f63727a9db54540f)

```rust
struct LoudDrop(&'static str);

impl Drop for LoudDrop {
    fn drop(&mut self) {
        println!("Dropped! {}", self.0);
    }
}

fn get_drop(str: &'static str) -> Option<LoudDrop> {
    Some(LoudDrop(str))
}

fn main() {
    println!("1");
    if get_drop("first").is_some() && get_drop("1.5").is_some() && let None = get_drop("last") {
        println!("2");
    } else {
        println!("2");
    }
    println!("3");
}
```

This prints
```
1
Dropped! 1.5
Dropped! last
2
Dropped! first
3
```

According to [RFC 2497](https://rust-lang.github.io/rfcs/2497-if-let-chains.html), it should desugar to this: [playground](https://play.rust-lang.org/?version=beta&mode=debug&edition=2021&gist=314b080d0eb54cd4561cdd6bfc7dada7)
```rust
fn main() {
    println!("1");
    'FRESH_LABEL: {
        if get_drop("first").is_some() {
            if get_drop("1.5").is_some() {
                if let None = get_drop("last") {
                    break 'FRESH_LABEL { println!("2") }
                }
            }
        }
        { println!("2") }
    }
    println!("3");
}
```
But this prints
```
1
Dropped! first
Dropped! 1.5
Dropped! last
2
3
```

### Meta
Wrong on the current beta
```
1.64.0-beta.1

(2022-08-09 56714e5332f5f21c39d7)
```

### PR DESCRIPTION
**Pull request by nathanwhit**
Fixes #100513.

During the lowering from AST to HIR we wrap expressions acting as conditions in a `DropTemps` expression so that any temporaries created in the condition are dropped after the condition is executed. Effectively this means we transform

```rust
if Some(1).is_some() { .. }
``` 

into (roughly)

```rust
if { let _t = Some(1).is_some(); _t } { .. }
```

so that if we create any temporaries, they're lifted into the new scope surrounding the condition, so for example something along the lines of

```rust
if { let temp = Some(1); let _t = temp.is_some(); _t }.
```

Before this PR, if the condition contained any let expressions we would not introduce that new scope, instead leaving the condition alone. This meant that in a let-chain like

```rust
if get_drop("first").is_some() && let None = get_drop("last") {
        println!("second");
} else { .. }
```

the temporary created for `get_drop("first")` would be lifted into the _surrounding block_, which caused it to be dropped after the execution of the entire `if` expression.

After this PR, we wrap everything but the `let` expression in terminating scopes. The upside to this solution is that it's minimally invasive, but the downside is that in the worst case, an expression with `let` exprs interspersed like

```rust
if get_drop("first").is_some() 
    && let Some(_a) = get_drop("fifth") 
    && get_drop("second").is_some() 
    && let Some(_b) = get_drop("fourth") { .. }
```

gets _multiple_ new scopes, roughly

```rust
if { let _t = get_drop("first").is_some(); _t } 
    && let Some(_a) = get_drop("fifth") 
    && { let _t = get_drop("second").is_some(); _t }
    && let Some(_b) = get_drop("fourth") { .. }
```

so instead of all of the temporaries being dropped at the end of the entire condition, they will be dropped right after they're evaluated (before the subsequent `let` expr). So while I'd say the drop behavior around let-chains is _less_ surprising after this PR, it still might not exactly match what people might expect.

For tests, I've just extended the drop order tests added in #100526. I'm not sure if that's the best way to go about it, though, so suggestions are welcome.

### CODE REVIEW

**Comment by nathanwhit** [comment]
Hmmm not sure what that ICE in CI is about, I can’t reproduce it locally. I’ll have to take a deeper look later.

File: src/test/ui/drop/drop_order.rs [hunk 1]
```diff
@@ -1,4 +1,5 @@
 // run-pass
```
Comment (est31) [inline src/test/ui/drop/drop_order.rs:1]: Could you add MIR validation to this test, like e.g. done [here](https://github.com/rust-lang/rust/pull/102394/files#diff-5f549293fd7dba2a7e7429b9513d703e0c3f615d49e5369623a31c3a73725caaR3)? There have been errors for let else related to invalid MIR, better to test for it.

File: compiler/rustc_ast_lowering/src/expr.rs [hunk 2]
```diff
@@ -397,22 +397,45 @@ impl<'hir> LoweringContext<'_, 'hir> {
...
+        // We have to take special care for `let` exprs in the condition, e.g. in
+        // `if let pat = val` or `if foo && let pat = val`, as we _do_ want `val` to live beyond the
+        // condition in this case.
+        //
+        // In order to mantain the drop behavior for the non `let` parts of the condition,
+        // we still wrap them in terminating scopes, e.g. `if foo && let pat = val` essentially
+        // gets transformed into `if { let _t = foo; _t } && let pat = val`
+        match cond.kind {
+            hir::ExprKind::Binary(
+                op @ Spanned { node: hir::BinOpKind::And | hir::BinOpKind::Or, .. },
```
Comment (compiler-errors) [inline compiler/rustc_ast_lowering/src/expr.rs:420]: We don't support `Or` in let chains?

**Comment by Nilstrieb** [comment]
Does this also fix #100276?

**Comment by compiler-errors** [comment]
I am not qualified to approve this PR i think 😂

r? compiler

also returning to author to fix the bug

@rustbot author

**Comment by eholk** [comment]
> Hmmm not sure what that ICE in CI is about, I can’t reproduce it locally. I’ll have to take a deeper look later.

I ran into an issue recently that only showed up in CI. I was able to repro it locally by runner the tests in docker: https://rustc-dev-guide.rust-lang.org/tests/docker.html

Maybe that would help here?

File: compiler/rustc_ast_lowering/src/expr.rs [hunk 3]
```diff
@@ -397,22 +397,45 @@ impl<'hir> LoweringContext<'_, 'hir> {
...
+                lhs,
+                rhs,
+            ) if has_let_expr(cond) => {
+                let lhs = self.wrap_cond_in_drop_scope(lhs);
+                let rhs = self.wrap_cond_in_drop_scope(rhs);
+
+                self.arena.alloc(self.expr(
```
[the remark this answers is not in the document]
Comment (nathanwhit) [reply compiler/rustc_ast_lowering/src/expr.rs:429]: Ah yeah that makes sense, I pushed a commit to lower the condition directly from AST -> HIR instead of lowering to HIR and then transforming to the new HIR.

File: src/test/ui/drop/drop_order.rs (hunk 1 above)
Comment (nathanwhit) [reply src/test/ui/drop/drop_order.rs:1]: Done!

**Comment by nathanwhit** [comment]
> Does this also fix #100276?

Hmm unfortunately not, it seems to be a separate bug. (Though now that I'm looking at it, I think I actually _might_ know the problem there - I'll try to open a separate PR, hopefully soon-ish).

**Comment by nathanwhit** [comment]
> > Hmmm not sure what that ICE in CI is about, I can’t reproduce it locally. I’ll have to take a deeper look later.
> 
> I ran into an issue recently that only showed up in CI. I was able to repro it locally by runner the tests in docker: https://rustc-dev-guide.rust-lang.org/tests/docker.html
> 
> Maybe that would help here?

Ah, I was actually able to fix it based on @compiler-errors comment, but thanks for the point! I'm sure it'll come in handy in the future.

With the latest commits I _think_ this should be ready for review, so
@rustbot ready

**Comment by joshtriplett** [comment]
The behavior change *seems* correct to me. (No comment on the implementation.)

**Comment by eholk** [comment]
The implementation seems reasonable to me, so this PR seems good to go.

@bors r+

File: src/test/ui/drop/drop_order.rs [hunk 4]
```diff
@@ -116,6 +118,58 @@ impl DropOrderCollector {
...
+            && self.option_loud_drop(10).is_some() // 2
+            && let Some(_e) = self.option_loud_drop(12) { // 4
+            self.print(11); // 3
+        }
+
+        // let exprs first
+        if let Some(_d) = self.option_loud_drop(18) // 5
+            && let Some(_e) = self.option_loud_drop(17) // 4
+            && self.option_loud_drop(14).is_some() // 1
+            && self.option_loud_drop(15).is_some() { // 2
```
Comment (cjgillot) [inline src/test/ui/drop/drop_order.rs:150]: The drop order is a bit surprising. IIUC, we start by dropping the first regular conditions in *reverse* source order, then other regular conditions in *forward* source order, then the block, then the let conditions. 

Why the forward/reverse mix?

Comment (nathanwhit) [reply src/test/ui/drop/drop_order.rs:150]: Yeah that's definitely a quirk. It's pretty much because for that condition we go from an AST like

```rust
// Fake notation - the numbers correspond to the argument to `option_loud_drop`
Binary(And, Binary(And, Binary(And, Let(18), Let(17)), MethodCall(14)), MethodCall(15)
```

to

```rust
Binary(And, Binary(And, Binary(And, Let(18), Let(17)), DropTemps(MethodCall(14))), DropTemps(MethodCall(15)))
```

If we could group
```rust
self.option_loud_drop(14).is_some() // 1
            && self.option_loud_drop(15).is_some() // 2
```
into the same `DropTemps` then they would drop in reverse source order, but due to the nesting, I couldn't see a way to wrap them in the same `DropTemps` without the let conditions being lumped in.

If the regular conditions come first, like

```rust
self.option_loud_drop(14).is_some()
    && self.option_loud_drop(15).is_some()
    && let Some(_d) = self.option_loud_drop(18)
    && let Some(_e) = self.option_loud_drop(17)
```

we can (and do) wrap them in the same `DropTemps`, and so they drop in reverse source order.

Comment (est31) [reply src/test/ui/drop/drop_order.rs:150]: FTR there is also pretty weird behaviour for vanilla non-let if chains. Drop behaviour is currently like:

```
        if self.option_loud_drop(5).is_some()
            && self.option_loud_drop(1).is_some()
            && self.option_loud_drop(2).is_some()
            && self.option_loud_drop(3).is_some()
            && self.option_loud_drop(4).is_some() {
            self.print(6);
        }
```

Same goes if you put the expression into a `let _= ...`, or replace the `&&` with a `||` (while changing the is_some to is_none so that all partial exprs get evaluated). So second sub-expression is first, then it goes in normal direction, until the end. Then comes the first sub-expression. Non-short-circuiting & and | drop more consistently in inverse order (5,4,3,2,1). I'm not sure how to resolve this, and how to integrate this with let chains. There is the danger of furthering technical debt on one hand, on the other hand there is the danger of adding exceptions.

_____

A bit unrelated: *Generally* I think that dropping the temporaries of the if let expression after the `else` block is entered was a mistake. Ideally it should be changed to always pre-drop, like what if is doing. I think let chains give us a good opportunity to switch to the new behaviour, at least for let chains, and I'm very happy that currently this is what this PR seems to be doing: drop all temporaries, from let or from an expression, before the `else` block is entered. Just as a positive feedback :).
