### PR TITLE
copy the correct version of LLVM into the stage0 sysroot

### LINKED ISSUE #109314: `x test rustc_interface --stage 0` is broken again
I tried this code:

```rust
x test --stage 0 rustc_interface
```

I expected to see this happen: All tests pass.

Instead, this happened:
```
     Running unittests src/lib.rs (build/x86_64-unknown-linux-gnu/stage0-rustc/x86_64-unknown-linux-gnu/release/deps/rustc_interface-a5db7347e5f1d566)
/home/jyn/src/rust2/build/x86_64-unknown-linux-gnu/stage0-rustc/x86_64-unknown-linux-gnu/release/deps/rustc_interface-a5db7347e5f1d566: error while loading shared libraries: libLLVM-15-rust-1.70.0-nightly.so: cannot open shared object file: No such file or directory
error: test failed, to rerun pass `-p rustc_interface --lib`
```

### Meta

HEAD is branched from https://github.com/rust-lang/rust/commit/13afbdaa0655dda23d7129e59ac48f1ec88b2084

### PR DESCRIPTION
**Pull request by onur-ozkan**
In some cases(see https://github.com/rust-lang/rust/issues/109314), when the stage0
compiler relies on more recent version of LLVM than the beta compiler, it may not
be able to locate the correct LLVM in the sysroot. This situation typically occurs
when we upgrade LLVM version while the beta compiler continues to use an older version.

Fixes #109314

### CODE REVIEW

File: src/bootstrap/compile.rs [hunk 1]
```diff
@@ -1390,6 +1390,18 @@ impl Step for Sysroot {
         let _ = fs::remove_dir_all(&sysroot);
         t!(fs::create_dir_all(&sysroot));
 
+        // When bootstrap relies on a more recent version of LLVM than the beta compiler,
```
Comment (Mark-Simulacrum) [inline src/bootstrap/compile.rs:1393]: "bootstrap relies on a more recent version of LLVM" -- can you say more about what you mean by relies on here? How are we relying on LLVM from bootstrap? The linked issue seems like it's not about bootstrap relying but rather that stage0 compiler tests do, if I intuited right at a glance?

(Code seems OK, but a comment update would be good).

**Comment by Mark-Simulacrum** [comment]
@bors r+ rollup=iffy

I'm going to go ahead and approve but let's keep an eye out for any regressions and back out if needed.
