### PR TITLE
Don't leave a comma at the start of argument list when removing arguments

### LINKED ISSUE #109425: Left suffix comma when suggesting remove extra arguments
### Code

```Rust
fn main() {
    {
        let mut mutex: libc() = std::mem::zeroed(
            file.as_raw_fd(),
            0,
            0,
            libc::SYNC_FILE_RANGE_WAIT_BEFORE,
        );
    }
}
```

### Current output

```Shell
error[E0433]: failed to resolve: use of undeclared crate or module `libc`
 --> ./p/debug.rs:7:13
  |
7 |             libc::SYNC_FILE_RANGE_WAIT_BEFORE,
  |             ^^^^ use of undeclared crate or module `libc`

error[E0412]: cannot find type `libc` in this scope
 --> ./p/debug.rs:3:24
  |
3 |         let mut mutex: libc() = std::mem::zeroed(
  |                        ^^^^ not found in this scope

error[E0423]: expected value, found macro `file`
 --> ./p/debug.rs:4:13
  |
4 |             file.as_raw_fd(),
  |             ^^^^ not a value

error[E0061]: this function takes 0 arguments but 4 arguments were supplied
   --> ./p/debug.rs:3:33
    |
3   |         let mut mutex: libc() = std::mem::zeroed(
    |                                 ^^^^^^^^^^^^^^^^
4   |             file.as_raw_fd(),
    |             ---------------- unexpected argument
5   |             0,
    |             - unexpected argument of type `{integer}`
6   |             0,
    |             - unexpected argument of type `{integer}`
7   |             libc::SYNC_FILE_RANGE_WAIT_BEFORE,
    |             --------------------------------- unexpected argument
    |
note: function defined here
   --> /Users/yukang/rust/library/core/src/mem/mod.rs:643:15
    |
643 | pub unsafe fn zeroed<T>() -> T {
    |               ^^^^^^
help: remove the extra arguments
    |
4   -             file.as_raw_fd(),
4   +             ,
    |

error: aborting due to 4 previous errors
```

### Desired output

```Shell
error[E0433]: failed to resolve: use of undeclared crate or module `libc`
 --> ./p/debug.rs:7:13
  |
7 |             libc::SYNC_FILE_RANGE_WAIT_BEFORE,
  |             ^^^^ use of undeclared crate or module `libc`

error[E0412]: cannot find type `libc` in this scope
 --> ./p/debug.rs:3:24
  |
3 |         let mut mutex: libc() = std::mem::zeroed(
  |                        ^^^^ not found in this scope

error[E0423]: expected value, found macro `file`
 --> ./p/debug.rs:4:13
  |
4 |             file.as_raw_fd(),
  |             ^^^^ not a value

error[E0061]: this function takes 0 arguments but 4 arguments were supplied
   --> ./p/debug.rs:3:33
    |
3   |         let mut mutex: libc() = std::mem::zeroed(
    |                                 ^^^^^^^^^^^^^^^^
4   |             file.as_raw_fd(),
    |             ---------------- unexpected argument
5   |             0,
    |             - unexpected argument of type `{integer}`
6   |             0,
    |             - unexpected argument of type `{integer}`
7   |             libc::SYNC_FILE_RANGE_WAIT_BEFORE,
    |             --------------------------------- unexpected argument
    |
note: function defined here
   --> /Users/yukang/rust/library/core/src/mem/mod.rs:643:15
    |
643 | pub unsafe fn zeroed<T>() -> T {
    |               ^^^^^^
help: remove the extra arguments
    |
4   -             file.as_raw_fd(),
4   +             
    |

error: aborting due to 4 previous errors
```

### Rationale and extra context

From https://github.com/rust-lang/rust/pull/109403#issuecomment-1477077848
Maybe a possible way is don't suggestion help when there are multiple arguments need to be removed, because we already have `error[E0061]` for those details?

### Other cases

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by WaffleLapkin**
Fixes #109425

Quite a dirty hack, but at least it works ig.

### CODE REVIEW

File: compiler/rustc_hir_typeck/src/fn_ctxt/checks.rs [hunk 1]
```diff
@@ -941,10 +946,37 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
...
+                        //     fn f() {}
+                        //   - f(0, 1,)
+                        //   + f()
+                        if only_extras_so_far
+                            && errors
+                                .peek()
+                                .map_or(true, |next_error| !matches!(next_error, Error::Extra(_)))
+                        {
+                            let next = provided_arg_tys
+                                .get(arg_idx.plus(1))
```
Comment (compiler-errors) [inline compiler/rustc_hir_typeck/src/fn_ctxt/checks.rs:966]: `ProvidedIdx: Add<usize>`, so you can just do `arg_idx + 1` I think

File: compiler/rustc_hir_typeck/src/fn_ctxt/checks.rs [hunk 2]
```diff
@@ -941,10 +946,37 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
...
+                                .map(|&(_, sp)| sp)
+                                .unwrap_or_else(|| {
+                                    // Subtract one to move before `)`
+                                    call_expr
+                                        .span
+                                        .shrink_to_hi()
```
Comment (oli-obk) [inline compiler/rustc_hir_typeck/src/fn_ctxt/checks.rs:972]: is this necessary (or doing anything at all) considering the `with_lo` below?

Comment (WaffleLapkin) [reply compiler/rustc_hir_typeck/src/fn_ctxt/checks.rs:972]: I don't think this is necessary. IIRC this was left from when I was using some span combinators like `to`.
