### PR TITLE
MIR-borrowck: fix diagnostics for closures

### LINKED ISSUE #45362: MIR-borrowck: diagnostics for closures are much worse compared to AST-borrowck
When compiling with MIR-borrowck via `-Z borrowck-mir`, the diagnostics printed when errors involves borrows/moves into the bodies of closures (where the origin path is from the outside of that closure) are pretty bad.

For example, for the test `src/test/compile-fail/borrowck/borrowck-closures-two-mut.rs`, the AST-borrowck error messages tend to highlight the particular uses within the closure body, while the MIR-borrowck error messages just treat the whole closure as a black box.

Specifically, look at this AST-borrowck error:

```
error[E0499]: cannot borrow `x` as mutable more than once at a time (Ast)
  --> ../src/test/compile-fail/borrowck/borrowck-closures-two-mut.rs:55:24
   |
54 |     let c1 = to_fn_mut(|| set(&mut *x.f));
   |                        --           - previous borrow occurs due to use of `x` in closure
   |                        |
   |                        first mutable borrow occurs here
55 |     let c2 = to_fn_mut(|| set(&mut *x.f));
   |                        ^^           - borrow occurs due to use of `x` in closure
   |                        |
   |                        second mutable borrow occurs here
56 |     //~^ ERROR cannot borrow `x` as mutable more than once
57 | }
   | - first borrow ends here
```

and compare that to the corresponding MIR-borrowck error:

```
error[E0499]: cannot borrow `x` as mutable more than once at a time (Mir)
  --> ../src/test/compile-fail/borrowck/borrowck-closures-two-mut.rs:55:24
   |
54 |     let c1 = to_fn_mut(|| set(&mut *x.f));
   |                        ----------------- first mutable borrow occurs here
55 |     let c2 = to_fn_mut(|| set(&mut *x.f));
   |                        ^^^^^^^^^^^^^^^^^ second mutable borrow occurs here
56 |     //~^ ERROR cannot borrow `x` as mutable more than once
57 | }
   | - first borrow ends here
```

What MIR-borrowck needs, if we can somehow get it, is the equivalent to the "previous borrow occurs due to use of `x` in closure" and "borrow occurs due to use of `x` in closure" messages, with the corresponding (very) precise spans.

### PR DESCRIPTION
**Pull request by sinkuu**
Emit notes for captured variables in the same manner as AST borrowck.

```
error[E0499]: cannot borrow `x` as mutable more than once at a time (Ast)
  --> $DIR/borrowck-closures-two-mut.rs:24:24
   |
23 |     let c1 = to_fn_mut(|| x = 4);
   |                        -- - previous borrow occurs due to use of `x` in closure
   |                        |
   |                        first mutable borrow occurs here
24 |     let c2 = to_fn_mut(|| x = 5); //~ ERROR cannot borrow `x` as mutable more than once
   |                        ^^ - borrow occurs due to use of `x` in closure
   |                        |
   |                        second mutable borrow occurs here
25 | }
   | - first borrow ends here

error[E0499]: cannot borrow `x` as mutable more than once at a time (Mir)
  --> $DIR/borrowck-closures-two-mut.rs:24:24
   |
23 |     let c1 = to_fn_mut(|| x = 4);
   |                        -- - previous borrow occurs due to use of `x` in closure
   |                        |
   |                        first mutable borrow occurs here
24 |     let c2 = to_fn_mut(|| x = 5); //~ ERROR cannot borrow `x` as mutable more than once
   |                        ^^ - borrow occurs due to use of `x` in closure
   |                        |
   |                        second mutable borrow occurs here
25 | }
   | - first borrow ends here
```

 
Fixes #45362.

### CODE REVIEW

File: src/test/ui/borrowck/borrowck-closures-two-mut.rs [hunk 1]
```diff
@@ -0,0 +1,62 @@
+// Copyright 2014 The Rust Project Developers. See the COPYRIGHT
```
Comment (estebank) [inline src/test/ui/borrowck/borrowck-closures-two-mut.rs]: Update copyright year

File: src/librustc_mir/borrow_check.rs [hunk 2]
```diff
@@ -1169,8 +1169,70 @@ impl<'c, 'b, 'a: 'b+'c, 'gcx, 'tcx: 'a> MirBorrowckCtxt<'c, 'b, 'a, 'gcx, 'tcx>
         err.emit();
     }
 
+    /// Finds the span of arguments of aclosure (within `maybe_closure_span`) and its usage of
+    /// the local assigned at `location`.
+    fn find_closure_span(
```
Comment (estebank) [inline src/librustc_mir/borrow_check.rs]: It'd be nice to add some comments explaining _what_ is being done in the code, but this method is short enough that it is not _necessary_.

**Review by estebank — COMMENTED** [review]
r=me after updating the copyright year.
