### PR TITLE
Refactor and fix intra-doc link diagnostics, and fix links to primitives

### LINKED ISSUE #76692: Intra-doc links to items in `std::primitive` are broken
For example ``[`std::primitive::i32`]`` generates a link to https://doc.rust-lang.org/nightly/std/primitive.std::primitive::i32.html.

### LINKED ISSUE #76693: ICE generating intra-doc link to `std::primitive::i32::MAX`
### Code

```Rust
//! [`std::primitive::i32::MAX`]
```

### Meta

Backtrace is from a local build of a055c5a1bd95e029e9b31891db63b6dc8258b472 but this also reproduces on at least `rustdoc 1.48.0-nightly (dbb73f8f7 2020-09-12)`.

### Error output

```
thread 'rustc' panicked at 'internal error: entered unreachable code: primitives are covered above and other `Res` variants aren't possible at module scope: PrimTy(Int(I32))', src\librustdoc\passes\collect_intra_doc_links.rs:1617:34
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.48.0-dev running on x86_64-pc-windows-msvc
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
thread 'rustc' panicked at 'internal error: entered unreachable code: primitives are covered above and other `Res` variants aren't possible at module scope: PrimTy(Int(I32))', src\librustdoc\passes\collect_intra_doc_links.rs:1617:34
stack backtrace:
   0: std::panicking::begin_panic_handler
             at C:\Source\rust\library\std\src\panicking.rs:483
   1: std::panicking::begin_panic_fmt
             at C:\Source\rust\library\std\src\panicking.rs:437
   2: rustdoc::passes::collect_intra_doc_links::resolution_failure::{{closure}}
             at C:\Source\rust\src\librustdoc\passes\collect_intra_doc_links.rs:1617
   3: rustdoc::passes::collect_intra_doc_links::report_diagnostic::{{closure}}
             at C:\Source\rust\src\librustdoc\passes\collect_intra_doc_links.rs:1484
   4: core::ops::function::FnOnce::call_once<closure-0,tuple<rustc_middle::lint::LintDiagnosticBuilder>>
             at C:\Source\rust\library\core\src\ops\function.rs:227
   5: alloc::boxed::{{impl}}::call_once
             at C:\Source\rust\library\alloc\src\boxed.rs:1042
   6: rustc_middle::lint::struct_lint_level::struct_lint_level_impl
             at C:\Source\rust\compiler\rustc_middle\src\lint.rs:331
   7: rustc_middle::lint::struct_lint_level
             at C:\Source\rust\compiler\rustc_middle\src\lint.rs:333
   8: rustc_middle::ty::context::TyCtxt::struct_span_lint_hir<rustc_span::span_encoding::Span,closure-0>
             at C:\Source\rust\compiler\rustc_middle\src\ty\context.rs:2585
   9: rustdoc::passes::collect_intra_doc_links::report_diagnostic
             at C:\Source\rust\src\librustdoc\passes\collect_intra_doc_links.rs:1454
  10: rustdoc::passes::collect_intra_doc_links::resolution_failure
             at C:\Source\rust\src\librustdoc\passes\collect_intra_doc_links.rs:1499
  11: rustdoc::passes::collect_intra_doc_links::{{impl}}::fold_item
             at C:\Source\rust\src\librustdoc\passes\collect_intra_doc_links.rs:1062
  12: rustdoc::fold::DocFolder::fold_crate::{{closure}}
             at C:\Source\rust\src\librustdoc\fold.rs:93
  13: core::option::Option::and_then
             at C:\Source\rust\library\core\src\option.rs:646
  14: rustdoc::fold::DocFolder::fold_crate
             at C:\Source\rust\src\librustdoc\fold.rs:93
  15: rustdoc::passes::collect_intra_doc_links::collect_intra_doc_links
             at C:\Source\rust\src\librustdoc\passes\collect_intra_doc_links.rs:46
  16: rustdoc::core::run_global_ctxt::{{closure}}
             at C:\Source\rust\src\librustdoc\core.rs:552
  17: rustc_data_structures::profiling::VerboseTimingGuard::run
             at C:\Source\rust\compiler\rustc_data_structures\src\profiling.rs:573
  18: rustc_session::session::Session::time
             at C:\Source\rust\compiler\rustc_session\src\utils.rs:9
  19: rustdoc::core::run_global_ctxt
             at C:\Source\rust\src\librustdoc\core.rs:654
  20: rustdoc::core::run_core::{{closure}}::{{closure}}::{{closure}}::{{closure}}
             at C:\Source\rust\src\librustdoc\core.rs:469
  21: rustc_interface::passes::{{impl}}::enter::{{closure}}
             at C:\Source\rust\compiler\rustc_interface\src\passes.rs:722
  22: rustc_middle::ty::context::tls::enter_context::{{closure}}
             at C:\Source\rust\compiler\rustc_middle\src\ty\context.rs:1725
  23: rustc_middle::ty::context::tls::set_tlv
             at C:\Source\rust\compiler\rustc_middle\src\ty\context.rs:1709
  24: rustc_middle::ty::context::tls::enter_context
             at C:\Source\rust\compiler\rustc_middle\src\ty\context.rs:1725
  25: rustc_interface::passes::QueryContext::enter<closure-0,tuple<rustdoc::clean::types::Crate, rustdoc::config::RenderInfo, rustdoc::config::RenderOptions>>
             at C:\Source\rust\compiler\rustc_interface\src\passes.rs:722
  26: rustdoc::core::run_core::{{closure}}::{{closure}}::{{closure}}
             at C:\Source\rust\src\librustdoc\core.rs:468
  27: rustc_data_structures::profiling::VerboseTimingGuard::run
             at C:\Source\rust\compiler\rustc_data_structures\src\profiling.rs:573
  28: rustc_session::session::Session::time
             at C:\Source\rust\compiler\rustc_session\src\utils.rs:9
  29: rustdoc::core::run_core::{{closure}}::{{closure}}
             at C:\Source\rust\src\librustdoc\core.rs:467
  30: rustc_interface::interface::Compiler::enter
             at C:\Source\rust\compiler\rustc_interface\src\queries.rs:385
  31: rustdoc::core::run_core::{{closure}}
             at C:\Source\rust\src\librustdoc\core.rs:426
  32: rustc_interface::interface::create_compiler_and_run::{{closure}}
             at C:\Source\rust\compiler\rustc_interface\src\interface.rs:191
  33: rustc_span::with_source_map
             at C:\Source\rust\compiler\rustc_span\src\lib.rs:750
  34: rustc_interface::interface::create_compiler_and_run<tuple<rustdoc::clean::types::Crate, rustdoc::config::RenderInfo, rustdoc::config::RenderOptions, alloc::rc::Rc<rustc_session::session::Session>>,closure-4>
             at C:\Source\rust\compiler\rustc_interface\src\interface.rs:185
  35: rustdoc::core::run_core
             at C:\Source\rust\src\librustdoc\core.rs:425
  36: rustdoc::main_options
             at C:\Source\rust\src\librustdoc\lib.rs:504
  37: rustdoc::main_args::{{closure}}
             at C:\Source\rust\src\librustdoc\lib.rs:438
  38: rustc_interface::util::setup_callbacks_and_run_in_thread_pool_with_globals::{{closure}}::{{closure}}
             at C:\Source\rust\compiler\rustc_interface\src\util.rs:149
  39: scoped_tls::ScopedKey::set
             at C:\Users\Oliver\AppData\Local\Cargo\registry\src\github.com-1ecc6299db9ec823\scoped-tls-1.0.0\src\lib.rs:137
  40: rustc_span::with_session_globals<core::result::Result<tuple<>, rustc_errors::ErrorReported>,closure-0>
             at C:\Source\rust\compiler\rustc_span\src\lib.rs:91
  41: rustc_interface::util::setup_callbacks_and_run_in_thread_pool_with_globals::{{closure}}
             at C:\Source\rust\compiler\rustc_interface\src\util.rs:145
  42: rustc_interface::util::scoped_thread::{{closure}}
             at C:\Source\rust\compiler\rustc_interface\src\util.rs:120
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.48.0-dev running on x86_64-pc-windows-msvc

query stack during panic:
end of query stack
```

</p>
</details>

### LINKED ISSUE #76925: Intra-doc diagnostics are wrong with a disambiguator that's not in the value namespace
I tried this code:

```rust
/// [type@std::io::not::here]
pub fn f() {}
```

I expected to the same diagnostic as without a disambiguator:

```
warning: unresolved link to `std::io::not::here`
 --> tmp.rs:2:6
  |
2 | /// [std::io::not::here]
  |      ^^^^^^^^^^^^^^^^^^ the module `io` has no inner item named `not`
```

Instead, rustdoc gave a diagnostic that made no sense:

```rust

warning: unresolved link to `std::io::not::here`
 --> tmp.rs:1:6
  |
1 | /// [type@std::io::not::here]
  |      ^^^^^^^^^^^^^^^^^^^^^^^ the module `io` has no type named `std::io`
```

### Meta

`rustc --version --verbose`:
```
rustdoc 1.48.0-nightly (bbc677480 2020-09-18)
```

Relevant code: https://github.com/rust-lang/rust/blob/8a13fc494d4365e57d8f343219f0201458b68591/src/librustdoc/passes/collect_intra_doc_links.rs#L209-L230
The issue is that `variant_field` is only called for the value namespace, but it's in charge of giving diagnostics for intermediate paths. That logic should instead be moved to `fn resolution_failure`.

### PR DESCRIPTION
**Pull request by jyn514**
Closes https://github.com/rust-lang/rust/issues/76925, closes https://github.com/rust-lang/rust/issues/76693, closes https://github.com/rust-lang/rust/issues/76692.

Originally I only meant to fix #76925. But the hack with `has_primitive` was so bad it was easier to fix the primitive issues than to try and work around it.

Note that this still has one bug: `std::primitive::i32::MAX` does not resolve. However, this fixes the ICE so I'm fine with fixing the link in a later PR.

This is part of a series of refactors to make #76467 possible.

This is best reviewed commit-by-commit; it has detailed commit messages.

r? @euclio

### CODE REVIEW

File: src/librustdoc/passes/collect_intra_doc_links.rs [hunk 1]
```diff
@@ -261,16 +223,22 @@ impl<'a, 'tcx> LinkCollector<'a, 'tcx> {
...
                 }
             }
-            None
+            Err(ResolutionFailure::NotResolved {
+                module_id,
+                partial_res: None,
+                unresolved: path_str.into(),
+            })
         })
+        /*
```
Comment (jyn514) [inline src/librustdoc/passes/collect_intra_doc_links.rs:235]: Whoops, I need to remove all this commented out code.

File: src/librustdoc/passes/collect_intra_doc_links.rs [hunk 2]
```diff
@@ -411,25 +390,14 @@ impl<'a, 'tcx> LinkCollector<'a, 'tcx> {
         let ty_res = match ty_res {
             Err(()) | Ok(Res::Err) => {
                 return if ns == Namespace::ValueNS {
-                    self.variant_field(path_str, current_item, module_id, extra_fragment)
+                    self.variant_field(path_str, current_item, module_id)
                 } else {
-                    // See if it only broke because of the namespace.
```
Comment (jyn514) [inline src/librustdoc/passes/collect_intra_doc_links.rs:416]: Hmm, I need to double check this didn't impact anything - `resolution_failure` doesn't look in different namespaces. There might not be tests for this path?

File: src/librustdoc/passes/collect_intra_doc_links.rs [hunk 3]
```diff
@@ -1556,53 +1533,142 @@ fn resolution_failure(
...
+                    let last_found_module = match *partial_res {
+                        Some(Res::Def(DefKind::Mod, id)) => Some(id),
+                        None => Some(module_id),
+                        _ => None,
+                    };
+                    // See if this was a module: `[path]` or `[std::io::nope]`
+                    if let Some(module) = last_found_module {
+                        let module_name = collector.cx.tcx.item_name(module);
+                        let note = format!(
+                            "the module `{}` has no inner item named `{}`",
```
Comment (euclio) [inline src/librustdoc/passes/collect_intra_doc_links.rs:1591]: nit: I prefer "contains" over "has". Consider ``module `{}` does not contain an item `{}` ``

**Review by euclio — COMMENTED** [review]
LGTM with other comments addressed.

File: src/librustdoc/passes/collect_intra_doc_links.rs (hunk 2 above)
Comment (jyn514) [reply src/librustdoc/passes/collect_intra_doc_links.rs:416]: Ok I lied, it does look in different namespaces: https://github.com/rust-lang/rust/blob/66a9cfadf89439ad3ea1b67b996c0a90ca4763bf/src/librustdoc/passes/collect_intra_doc_links.rs#L1569-L1572
So this is handled properly:
```
warning: unresolved link to `file::into_iter`
 --> tmp.rs:1:6
  |
1 | /// [type@file::into_iter]
  |      ^^^^^^^^^^^^^^^^^^^^ `file` is a macro, not a module or type, and cannot have associated items
```
What's going on is it only looks at other namespaces _if there are multiple path segments_. So https://github.com/rust-lang/rust/blob/66a9cfadf89439ad3ea1b67b996c0a90ca4763bf/src/librustdoc/passes/collect_intra_doc_links.rs#L1114 and https://github.com/rust-lang/rust/blob/66a9cfadf89439ad3ea1b67b996c0a90ca4763bf/src/librustdoc/passes/collect_intra_doc_links.rs#L1242-L1244 are still necessary, because they handle cases like `value@file` and `type@file`. I could probably clean that up at some point, but it's not causing any bugs so I think I'll leave it be for now.

File: src/librustdoc/passes/collect_intra_doc_links.rs (hunk 3 above)
Comment (jyn514) [reply src/librustdoc/passes/collect_intra_doc_links.rs]: Sure, done.

File: src/librustdoc/passes/collect_intra_doc_links.rs (hunk 2 above)
Comment (euclio) [reply src/librustdoc/passes/collect_intra_doc_links.rs:416]: Please file an issue so we don't forget.

**Review by euclio — APPROVED** [review]

File: src/librustdoc/passes/collect_intra_doc_links.rs (hunk 2 above)
Comment (jyn514) [reply src/librustdoc/passes/collect_intra_doc_links.rs:416]: Opened https://github.com/rust-lang/rust/issues/77150
