### PR TITLE
Display short types for unimplemented trait

### LINKED ISSUE #121687: Very wide type shows up in error output
### Code

```Rust
pub fn foo() -> impl std::fmt::Display {
    Some(Some(Some(Some(Some(Some(Some(Some(Some(Some(Some(
        Some(Some(Some(Some(Some(Some(Some(Some(Some(Some(Some(
            Some(Some(Some(Some(Some(Some(Some(Some(Some(Some(Some(
                Some(Some(Some(Some(Some(Some(Some(Some(Some(Some(Some(
                    Some(Some(Some(Some(Some(Some(Some(Some(())))))))),
                ))))))))))),
            ))))))))))),
        ))))))))))),
    )))))))))))
}
```

### Current output

```Shell
Compiling repr v0.1.0 (/home/pacak/tmp/repr)
error[E0277]: `Option<Option<Option<Option<Option<Option<Option<Option<Option<Option<Option<Option<Option<Option<Option<Option<Option<Option<Option<Option<Option<Option<Option<Option<Option<Option<Option<Option<Option<Option<Option<Option<Option<Option<Option<Option<Option<Option<Option<Option<Option<Option<Option<Option<Option<Option<Option<Option<Option<Option<Option<Option<()>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>` doesn't implement `std::fmt::Display`
  --> src/lib.rs:1:17
   |
1  |   pub fn foo() -> impl std::fmt::Display {
   |                   ^^^^^^^^^^^^^^^^^^^^^^ `Option<Option<Option<Option<Option<Option<Option<Option<Option<Option<Option<Option<Option<Option<Option<Option<Option<Option<Option<Option<Option<Option<Option<Option<Option<Option<Option<Option<Option<Option<Option<Option<Option<Option<Option<Option<Option<Option<Option<Option<Option<Option<Option<Option<Option<Option<Option<Option<Option<Option<Option<Option<()>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>` cannot be formatted with the default formatter
2  | /     Some(Some(Some(Some(Some(Some(Some(Some(Some(Some(Some(
3  | |         Some(Some(Some(Some(Some(Some(Some(Some(Some(Some(Some(
4  | |             Some(Some(Some(Some(Some(Some(Some(Some(Some(Some(Some(
5  | |                 Some(Some(Some(Some(Some(Some(Some(Some(Some(Some(Some(
...  |
9  | |         ))))))))))),
10 | |     )))))))))))
   | |_______________- return type was inferred to be `Option<Option<Option<Option<Option<Option<Option<Option<Option<Option<Option<Option<Option<Option<Option<Option<Option<Option<Option<Option<Option<Option<Option<Option<Option<Option<Option<Option<Option<Option<Option<Option<Option<Option<Option<Option<Option<Option<Option<Option<Option<Option<Option<Option<Option<Option<Option<Option<Option<Option<Option<Option<()>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>` here
   |
   = help: the trait `std::fmt::Display` is not implemented for `Option<Option<Option<Option<Option<Option<Option<Option<Option<Option<Option<Option<Option<Option<Option<Option<Option<Option<Option<Option<Option<Option<Option<Option<Option<...>>>>>>>>>>>>>>>>>>>>>>>>>`
   = note: in format strings you may be able to use `{:?}` (or {:#?} for pretty-print) instead

For more information about this error, try `rustc --explain E0277`.
error: could not compile `repr` (lib test) due to 1 previous error
```

### Desired output

```Shell
Anything that fits on a single line
```

### Rationale and extra context

https://hachyderm.io/@ekuber/112004179050519020

### Other cases

_No response_

### Rust Version

```Shell
rustc 1.78.0-nightly (1a648b397 2024-02-11)
binary: rustc
commit-hash: 1a648b397dedc98ada3dd3360f6d661ec2436c56
commit-date: 2024-02-11
host: x86_64-unknown-linux-gnu
release: 1.78.0-nightly
LLVM version: 17.0.6


rustc 1.76.0 (07dca489a 2024-02-04)
binary: rustc
commit-hash: 07dca489ac2d933c78d3c5158e3f43beefeb02ce
commit-date: 2024-02-04
host: x86_64-unknown-linux-gnu
release: 1.76.0
LLVM version: 17.0.6
```

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by jieyouxu**
Shortens unimplemented trait diagnostics. Now shows:

```
error[E0277]: `Option<Option<Option<...>>>` doesn't implement `std::fmt::Display`
  --> $DIR/on_unimplemented_long_types.rs:4:17
   |
LL |   pub fn foo() -> impl std::fmt::Display {
   |                   ^^^^^^^^^^^^^^^^^^^^^^ `Option<Option<Option<...>>>` cannot be formatted with the default formatter
LL |
LL | /     Some(Some(Some(Some(Some(Some(Some(Some(Some(S...
LL | |         Some(Some(Some(Some(Some(Some(Some(Some(So...
LL | |             Some(Some(Some(Some(Some(Some(Some(Som...
LL | |                 Some(Some(Some(Some(Some(Some(Some...
...  |
LL | |         ))))))))))),
LL | |     )))))))))))
   | |_______________- return type was inferred to be `Option<Option<Option<...>>>` here
   |
   = help: the trait `std::fmt::Display` is not implemented for `Option<Option<Option<...>>>`
   = note: in format strings you may be able to use `{:?}` (or {:#?} for pretty-print) instead

error: aborting due to 1 previous error

For more information about this error, try `rustc --explain E0277`.
```

I'm not 100% sure if this is desirable, or if we should just let the long types remain long. This is also kinda a short-term bandaid solution. The real long term solution is to properly migrate `rustc_trait_selection`'s error reporting to use translatable diagnostics and then properly handle type name printing.

Fixes #121687.

### CODE REVIEW

File: compiler/rustc_trait_selection/src/traits/error_reporting/suggestions.rs [hunk 1]
```diff
@@ -3507,7 +3507,8 @@ impl<'tcx> TypeErrCtxt<'_, 'tcx> {
             }
             ObligationCauseCode::OpaqueReturnType(expr_info) => {
                 if let Some((expr_ty, expr_span)) = expr_info {
-                    let expr_ty = with_forced_trimmed_paths!(self.ty_to_string(expr_ty));
+                    let expr_ty =
+                        with_forced_trimmed_paths!(self.tcx.short_ty_string(expr_ty, &mut None));
```
Comment (estebank) [inline compiler/rustc_trait_selection/src/traits/error_reporting/suggestions.rs:3511]: I think we can remove the macro annotation if we're using `short_ty_string` already:

```suggestion
                    let expr_ty = self.tcx.short_ty_string(expr_ty, &mut None);
```

File: compiler/rustc_trait_selection/src/traits/error_reporting/on_unimplemented.rs [hunk 2]
```diff
@@ -824,7 +825,11 @@ impl<'tcx> OnUnimplementedFormatString {
             .filter_map(|param| {
                 let value = match param.kind {
                     GenericParamDefKind::Type { .. } | GenericParamDefKind::Const { .. } => {
-                        trait_ref.args[param.index as usize].to_string()
+                        if let Some(ty) = trait_ref.args[param.index as usize].as_type() {
+                            tcx.short_ty_string(ty, &mut None)
```
Comment (estebank) [inline compiler/rustc_trait_selection/src/traits/error_reporting/on_unimplemented.rs:829]: I think you should modify `format` to take an extra `file: &mut None` parameter to pass in here and modify `OnUnimplementedNote` to carry `file` as well. You can see how we present that [in other places](https://github.com/rust-lang/rust/blob/86a7fc840f11cd1f20fdf26d3071e34a2d4bc313/compiler/rustc_trait_selection/src/traits/error_reporting/suggestions.rs#L1272-L1289), which makes it so that if the user is interested in looking at the full type for whatever reason, they can. Ideally we'd have a single `file` for the entire error, and pass that around everywhere that we use `short_ty_string` for E0277, particularly `note_obligation_cause_code`, but that doesn't *need* to be addressed in this PR, but since you're adding another use there it might be a good idea to do so. Then we can remove all of the redundant "the full type name has been written to '{}'" notes and push them to the top-most call of `note_obligation_cause_code`.

File: compiler/rustc_trait_selection/src/traits/error_reporting/suggestions.rs (hunk 1 above)
Comment (estebank) [reply compiler/rustc_trait_selection/src/traits/error_reporting/suggestions.rs:3511]: (The other comment about `&mut None` applies here too.)

**Review by estebank — COMMENTED** [review]
r? @estebank

Thank you for taking this on!

I have a bunch of nitpicks that I'd like to address. In particular, shortening the type with no way to see the full type anywhere (which we stored to disk) can cause issues for people. Most of the time people don't care about the full type, but when they do, they *really* do. Also if we can try and pass the file being written to so that we only create one file per error instead of one per shortened type, that will be less disruptive, both on the user's disk as well as in the terminal output (because we'd only have a single `note: full type written to...` to display, instead of multiple).

@petrochenkov, I know you have a bunch of things on your plate, taking it on to ease your load.

**Comment by jieyouxu** [comment]
Thanks for reviewing!
> r? @estebank
> 
> Thank you for taking this on!
> 
> I have a bunch of nitpicks that I'd like to address. In particular, shortening the type with no way to see the full type anywhere (which we stored to disk) can cause issues for people. Most of the time people don't care about the full type, but when they do, they _really_ do. Also if we can try and pass the file being written to so that we only create one file per error instead of one per shortened type, that will be less disruptive, both on the user's disk as well as in the terminal output (because we'd only have a single `note: full type written to...` to display, instead of multiple).
> 
> @petrochenkov, I know you have a bunch of things on your plate, taking it on to ease your load.

**Comment by jieyouxu** [comment]
Thanks for reviewing!

> I have a bunch of nitpicks that I'd like to address.

I will try to address them one-by-one.

> In particular, shortening the type with no way to see the full type anywhere (which we stored to
> disk) can cause issues for people. Most of the time people don't care about the full type, but
> when they do, they _really_ do.

I strongly agree with this, because I have ran into issues with big types too.

> Also if we can try and pass the file being written to so that we only create one file per error
> instead of one per shortened type, that will be less disruptive, both on the user's disk as well
> as in the terminal output (because we'd only have a single `note: full type written to...` to
> display, instead of multiple).

Yeah, I need to fix that. I noticed multiple loooong-type files being created for the same type
when making the change, which was already annoying.

File: compiler/rustc_trait_selection/src/traits/error_reporting/on_unimplemented.rs (hunk 2 above)
Comment (jieyouxu) [reply compiler/rustc_trait_selection/src/traits/error_reporting/on_unimplemented.rs:829]: Not-within-the-scope-of-this-PR remark: the long type names when written to disk is... still incredibly long. I previously saw some issue proposing that the long types written to disk should be pretty printed (but now I cannot find it) and I think that might be good as an option (not necessarily default-behavior because it's probably easier to diff two long types when they are in single lines).

**Comment by jieyouxu** [comment]
I've unified (I think) the long type output file in `note_obligation_cause_code`, and moved the filename note to the end of `note_obligation_cause_code`. The long type output file probably should be passed even further up the call chain. Although further up in the call chain, there are also various examples of scattered output file / filename notes (esp. in `rustc_hir_typeck`) which probably should eventually be somehow unified too (probably not in this PR).

File: compiler/rustc_trait_selection/src/traits/error_reporting/suggestions.rs [hunk 3]
```diff
@@ -2676,6 +2676,8 @@ impl<'tcx> TypeErrCtxt<'_, 'tcx> {
     ) where
         T: ToPredicate<'tcx>,
     {
+        let mut long_ty_file = None;
```
Comment (estebank) [inline compiler/rustc_trait_selection/src/traits/error_reporting/suggestions.rs:2679]: Where is the path of this file being printed?

File: compiler/rustc_trait_selection/src/traits/error_reporting/on_unimplemented.rs [hunk 4]
```diff
@@ -111,6 +112,8 @@ impl<'tcx> TypeErrCtxt<'_, 'tcx> {
         trait_ref: ty::PolyTraitRef<'tcx>,
         obligation: &PredicateObligation<'tcx>,
     ) -> OnUnimplementedNote {
+        let mut long_ty_file = None;
```
Comment (estebank) [inline compiler/rustc_trait_selection/src/traits/error_reporting/on_unimplemented.rs:115]: Where is the path of this file being printed?

**Review by estebank — APPROVED** [review]
Other than one (seemingly?) missing note, r=me

File: compiler/rustc_trait_selection/src/traits/error_reporting/on_unimplemented.rs (hunk 4 above)
Comment (jieyouxu) [reply compiler/rustc_trait_selection/src/traits/error_reporting/on_unimplemented.rs]: So this is a bit awkward, I tried to make sure I don't miss any silent type name being written to file, but now there seems to be a duplicate written to file note lol

Comment (estebank) [reply compiler/rustc_trait_selection/src/traits/error_reporting/on_unimplemented.rs]: That... should be fine for now. We need to bubble the printing of the file (and passing the file down) more than we do now, but it being duplicated is better than out right losing it.

Comment (jieyouxu) [reply compiler/rustc_trait_selection/src/traits/error_reporting/on_unimplemented.rs]: > That... should be fine for now. We need to bubble the printing of the file (and passing the file down) more than we do now, but it being duplicated is better than out right losing it.

Yeah, there's `let mut file = None` a bit all over the place right now lol
