### PR TITLE
Don't assemble non-env/bound candidates if projection is rigid

### LINKED ISSUE #173: leptos regression
edit: While this looks like a regression with tachys, turns out that leptos has its own fork of tachys: https://github.com/leptos-rs/leptos/tree/main/tachys

~~Not yet minimized.~~

https://crater-reports.s3.amazonaws.com/pr-133502-1/try%23fa8e241660363f48d64b66b05eea58c93ab828fb/reg/leptos-0.7.8/log.txt

```
[INFO] [stdout] error[E0391]: cycle detected when computing type of `reactive_graph::<impl at /opt/rustwide/cargo-home/registry/src/index.crates.io-1949cf8c6b5b557f/tachys-0.1.8/src/reactive_graph/mod.rs:124:1: 128:23>::{synthetic#0}`
[INFO] [stdout]    --> /opt/rustwide/cargo-home/registry/src/index.crates.io-1949cf8c6b5b557f/tachys-0.1.8/src/reactive_graph/mod.rs:138:5
[INFO] [stdout]     |
[INFO] [stdout] 138 |     async fn resolve(mut self) -> Self::AsyncOutput {
[INFO] [stdout]     |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[INFO] [stdout]     |
[INFO] [stdout] note: ...which requires comparing an impl and trait method signature, inferring any hidden `impl Trait` types in the process...
[INFO] [stdout]    --> /opt/rustwide/cargo-home/registry/src/index.crates.io-1949cf8c6b5b557f/tachys-0.1.8/src/reactive_graph/mod.rs:138:5
[INFO] [stdout]     |
[INFO] [stdout] 138 |     async fn resolve(mut self) -> Self::AsyncOutput {
[INFO] [stdout]     |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[INFO] [stdout] note: ...which requires computing type of `reactive_graph::<impl at /opt/rustwide/cargo-home/registry/src/index.crates.io-1949cf8c6b5b557f/tachys-0.1.8/src/reactive_graph/mod.rs:124:1: 128:23>::resolve::{opaque#0}`...
[INFO] [stdout]    --> /opt/rustwide/cargo-home/registry/src/index.crates.io-1949cf8c6b5b557f/tachys-0.1.8/src/reactive_graph/mod.rs:138:5
[INFO] [stdout]     |
[INFO] [stdout] 138 |     async fn resolve(mut self) -> Self::AsyncOutput {
[INFO] [stdout]     |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[INFO] [stdout] note: ...which requires computing type of opaque `reactive_graph::<impl at /opt/rustwide/cargo-home/registry/src/index.crates.io-1949cf8c6b5b557f/tachys-0.1.8/src/reactive_graph/mod.rs:124:1: 128:23>::resolve::{opaque#0}`...
[INFO] [stdout]    --> /opt/rustwide/cargo-home/registry/src/index.crates.io-1949cf8c6b5b557f/tachys-0.1.8/src/reactive_graph/mod.rs:138:5
[INFO] [stdout]     |
[INFO] [stdout] 138 |     async fn resolve(mut self) -> Self::AsyncOutput {
[INFO] [stdout]     |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[INFO] [stdout] note: ...which requires borrow-checking `reactive_graph::<impl at /opt/rustwide/cargo-home/registry/src/index.crates.io-1949cf8c6b5b557f/tachys-0.1.8/src/reactive_graph/mod.rs:124:1: 128:23>::resolve`...
[INFO] [stdout]    --> /opt/rustwide/cargo-home/registry/src/index.crates.io-1949cf8c6b5b557f/tachys-0.1.8/src/reactive_graph/mod.rs:138:5
[INFO] [stdout]     |
[INFO] [stdout] 138 |     async fn resolve(mut self) -> Self::AsyncOutput {
[INFO] [stdout]     |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[INFO] [stdout] note: ...which requires promoting constants in MIR for `reactive_graph::<impl at /opt/rustwide/cargo-home/registry/src/index.crates.io-1949cf8c6b5b557f/tachys-0.1.8/src/reactive_graph/mod.rs:124:1: 128:23>::resolve`...
[INFO] [stdout]    --> /opt/rustwide/cargo-home/registry/src/index.crates.io-1949cf8c6b5b557f/tachys-0.1.8/src/reactive_graph/mod.rs:138:5
[INFO] [stdout]     |
[INFO] [stdout] 138 |     async fn resolve(mut self) -> Self::AsyncOutput {
[INFO] [stdout]     |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[INFO] [stdout] note: ...which requires checking if `reactive_graph::<impl at /opt/rustwide/cargo-home/registry/src/index.crates.io-1949cf8c6b5b557f/tachys-0.1.8/src/reactive_graph/mod.rs:124:1: 128:23>::resolve` contains FFI-unwind calls...
[INFO] [stdout]    --> /opt/rustwide/cargo-home/registry/src/index.crates.io-1949cf8c6b5b557f/tachys-0.1.8/src/reactive_graph/mod.rs:138:5
[INFO] [stdout]     |
[INFO] [stdout] 138 |     async fn resolve(mut self) -> Self::AsyncOutput {
[INFO] [stdout]     |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[INFO] [stdout] note: ...which requires building MIR for `reactive_graph::<impl at /opt/rustwide/cargo-home/registry/src/index.crates.io-1949cf8c6b5b557f/tachys-0.1.8/src/reactive_graph/mod.rs:124:1: 128:23>::resolve`...
[INFO] [stdout]    --> /opt/rustwide/cargo-home/registry/src/index.crates.io-1949cf8c6b5b557f/tachys-0.1.8/src/reactive_graph/mod.rs:138:5
[INFO] [stdout]     |
[INFO] [stdout] 138 |     async fn resolve(mut self) -> Self::AsyncOutput {
[INFO] [stdout]     |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[INFO] [stdout] note: ...which requires match-checking `reactive_graph::<impl at /opt/rustwide/cargo-home/registry/src/index.crates.io-1949cf8c6b5b557f/tachys-0.1.8/src/reactive_graph/mod.rs:124:1: 128:23>::resolve`...
[INFO] [stdout]    --> /opt/rustwide/cargo-home/registry/src/index.crates.io-1949cf8c6b5b557f/tachys-0.1.8/src/reactive_graph/mod.rs:138:5
[INFO] [stdout]     |
[INFO] [stdout] 138 |     async fn resolve(mut self) -> Self::AsyncOutput {
[INFO] [stdout]     |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[INFO] [stdout] note: ...which requires type-checking `reactive_graph::<impl at /opt/rustwide/cargo-home/registry/src/index.crates.io-1949cf8c6b5b557f/tachys-0.1.8/src/reactive_graph/mod.rs:124:1: 128:23>::resolve`...
[INFO] [stdout]    --> /opt/rustwide/cargo-home/registry/src/index.crates.io-1949cf8c6b5b557f/tachys-0.1.8/src/reactive_graph/mod.rs:138:5
[INFO] [stdout]     |
[INFO] [stdout] 138 |     async fn resolve(mut self) -> Self::AsyncOutput {
[INFO] [stdout]     |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[INFO] [stdout]     = note: ...which again requires computing type of `reactive_graph::<impl at /opt/rustwide/cargo-home/registry/src/index.crates.io-1949cf8c6b5b557f/tachys-0.1.8/src/reactive_graph/mod.rs:124:1: 128:23>::{synthetic#0}`, completing the cycle
[INFO] [stdout] note: cycle used when checking assoc item `html::<impl at /opt/rustwide/cargo-home/registry/src/index.crates.io-1949cf8c6b5b557f/tachys-0.1.8/src/html/mod.rs:53:1: 53:28>::resolve` is compatible with trait definition
[INFO] [stdout]    --> /opt/rustwide/cargo-home/registry/src/index.crates.io-1949cf8c6b5b557f/tachys-0.1.8/src/html/mod.rs:60:5
[INFO] [stdout]     |
[INFO] [stdout] 60  |     async fn resolve(self) -> Self::AsyncOutput {
[INFO] [stdout]     |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[INFO] [stdout]     = note: see https://rustc-dev-guide.rust-lang.org/overview.html#queries and https://rustc-dev-guide.rust-lang.org/query.html for more information
```

### PR DESCRIPTION
**Pull request by compiler-errors**
Putting this up for an initial review, it's still missing comments, clean-up, and possibly a tweak to deal with ambiguities in the `BestObligation` folder.

This PR fixes https://github.com/rust-lang/trait-system-refactor-initiative/issues/173. Specifically, we're creating an unnecessary query cycle in normalization by assembling an *impl candidate* even if we know later on during `merge_candidates` that we'll be filtering out that impl candidate.

This PR adjusts the `merge_candidates` to assemble *only* env/bound candidates if we have `TraitGoalProvenVia::ParamEnv | TraitGoalProvenVia::AliasBound`.

I'll leave some thoughts/comments in the code.

r? lcnr

### CODE REVIEW

File: compiler/rustc_next_trait_solver/src/solve/assembly/mod.rs [hunk 1]
```diff
@@ -310,25 +311,40 @@ where
...
+    }
 
-        self.assemble_param_env_candidates(goal, &mut candidates);
+    pub(super) fn assemble_and_evaluate_candidates_from_env_and_bounds<G: GoalKind<D>>(
+        &mut self,
+        goal: Goal<I, G>,
+    ) -> Vec<Candidate<I>> {
+        self.assemble_and_evaluate_candidates_with_normalized_goal(goal, |ecx, goal| {
+            let mut candidates = vec![];
+            ecx.assemble_alias_bound_candidates(goal, &mut candidates);
```
Comment (compiler-errors) [inline compiler/rustc_next_trait_solver/src/solve/assembly/mod.rs:329]: Bit unsatisfying that we have to keep this in sync w/ below. Could introduce another helper function, I guess.

File: compiler/rustc_next_trait_solver/src/solve/assembly/mod.rs [hunk 2]
```diff
@@ -310,25 +311,40 @@ where
...
+    }
 
-        candidates
+    pub(super) fn assemble_and_evaluate_candidates<G: GoalKind<D>>(
+        &mut self,
+        goal: Goal<I, G>,
+    ) -> Vec<Candidate<I>> {
+        self.assemble_and_evaluate_candidates_with_normalized_goal(goal, |ecx, goal| {
+            let mut candidates = vec![];
+            ecx.assemble_impl_candidates(goal, &mut candidates);
```
Comment (compiler-errors) [inline compiler/rustc_next_trait_solver/src/solve/assembly/mod.rs:341]: It's a bit subtle b/c we could inadvertently assemble some *other* kind of bound/candidate outside of the `alias_bound_candidates`/`param_env_candidates` functions. 

We could move those to the end and assert that all the candidates assembled *before* aren't env/bound candidates, to make sure we're not subtly incomplete here?

File: compiler/rustc_next_trait_solver/src/solve/assembly/mod.rs [hunk 3]
```diff
@@ -289,9 +289,10 @@ where
     D: SolverDelegate<Interner = I>,
     I: Interner,
 {
-    pub(super) fn assemble_and_evaluate_candidates<G: GoalKind<D>>(
+    fn assemble_and_evaluate_candidates_with_normalized_goal<G: GoalKind<D>>(
```
Comment (compiler-errors) [inline compiler/rustc_next_trait_solver/src/solve/assembly/mod.rs:292]: Need comment.

File: compiler/rustc_next_trait_solver/src/solve/assembly/mod.rs [hunk 4]
```diff
@@ -310,25 +311,40 @@ where
...
-        self.assemble_builtin_impl_candidates(goal, &mut candidates);
-
-        self.assemble_alias_bound_candidates(goal, &mut candidates);
-
-        self.assemble_object_bound_candidates(goal, &mut candidates);
+        assemble(self, goal)
+    }
 
-        self.assemble_param_env_candidates(goal, &mut candidates);
+    pub(super) fn assemble_and_evaluate_candidates_from_env_and_bounds<G: GoalKind<D>>(
```
Comment (compiler-errors) [inline compiler/rustc_next_trait_solver/src/solve/assembly/mod.rs:323]: Need comment that people who modify this function must ensure it remains complete.

File: compiler/rustc_next_trait_solver/src/solve/assembly/mod.rs [hunk 5]
```diff
@@ -778,10 +794,10 @@ where
     ///
     /// See trait-system-refactor-initiative#124 for more details.
     #[instrument(level = "debug", skip(self, inject_normalize_to_rigid_candidate), ret)]
-    pub(super) fn merge_candidates(
+    pub(super) fn assemble_and_merge_candidates<G: GoalKind<D>>(
```
Comment (compiler-errors) [inline compiler/rustc_next_trait_solver/src/solve/assembly/mod.rs:797]: Need to adjust above comment to mention that this is also doing the assembly.

File: compiler/rustc_trait_selection/src/solve/fulfill/derive_errors.rs [hunk 6]
```diff
@@ -269,7 +269,7 @@ impl<'tcx> BestObligation<'tcx> {
         goal: &inspect::InspectGoal<'_, 'tcx>,
         self_ty: Ty<'tcx>,
     ) -> ControlFlow<PredicateObligation<'tcx>> {
-        assert!(!self.consider_ambiguities);
+        //assert!(!self.consider_ambiguities);
```
Comment (compiler-errors) [inline compiler/rustc_trait_selection/src/solve/fulfill/derive_errors.rs:272]: We now assemble no candidates if the trait goal for an normalizes-to is ambiguous. 

We could wrap the ambiguity in that `let Some(proven_via) = proven_via else {` line above with a candidate kind to fix this assertion, or otherwise just remove it.

**Comment by lcnr** [comment]
This PR has two separate effects
- we avoid fetching the type of impl associated items if they are shadowed anyways
  - avoid the query cycle in `leptos`, and generally avoids an unnecessary query dependency
- we avoid reassembling impl candidates if stuff is proven via where-bound, likely positively impacting perf

I feel :shrug: about the first case. I think we should fix https://github.com/rust-lang/rust/issues/139788 regardless as using RPITITs recursively shouldn't cycle even if they are actually needed. It does match the behavior of the old solver so it feels generally reasonable to do so.

The second one is a bit worrying. I would be opposed/far more hesitant if it were to do the same when assembling trait goals as that definitely has an exponential performance impact (e.g. it would fix https://github.com/rust-lang/trait-system-refactor-initiative/issues/109). I want to be very careful here as I expect us to consider impl candidates in more cases in the future and ideally doing so won't introduce new hangs :<

I expect that in theory we may have exponential performance differences depending on whether or not we check impl item bounds. I don't know if they are likely enough to actually cause issues for us in the future. I am still a bit on the fence about this PR, but generally in favor I think.

**Comment by compiler-errors** [comment]
> I would be opposed/far more hesitant if it were to do the same when assembling trait goals as that definitely has an exponential performance impact (e.g. it would fix https://github.com/rust-lang/trait-system-refactor-initiative/issues/109).

Well part of the point of this approach is we're already doing all the work of proving the trait goal in order to even compute the `TraitGoalProvenVia`, so my *vibe* is that all of the additional extra possibly exponential computational work here that we're winnowing out *today* would be due to GAT bounds and any alias bounds.

Totally unrelated side-note that it would be nice if *query* cycles were recoverable, lol.

**Comment by lcnr** [comment]
>  so my vibe is that all of the additional extra possibly exponential computational work here that we're winnowing out today would be due to GAT bounds.

yeah, exactly, the only hangs we'd be avoiding this way are due to GAT bounds. I guess this seems acceptable to me, so yeah. Let's go ahead with this change

**Review by lcnr — COMMENTED** [review]
an alternative structure would be to change `assemble_and_evaluate_candidates` to also take
```rust
enum AssembledCandidates {
   All,
   /// Only assemble candidates from the environment,
   /// ignoring impls. We only look for `ParamEnv` and
   /// `AliasBound` candidates.
   FromEnv,
}
```
and then put `assemble_impl_candidates` behind an if/match :thinking: 

I feel like splitting assembly into multiple functions is making this a bit harder to reason about.

thoughts?

**Comment by compiler-errors** [comment]
Yeah, that would work too.

File: compiler/rustc_next_trait_solver/src/solve/assembly/mod.rs [hunk 7]
```diff
@@ -778,47 +792,41 @@ where
...
-                // tests/ui/next-solver/alias-bound-shadowed-by-env.rs.
-                //
+                // `tests/ui/next-solver/alias-bound-shadowed-by-env.rs`.
+                let candidates_from_env_and_bounds: Vec<_> = self
+                    .assemble_and_evaluate_candidates(goal, AssembleCandidatesFrom::EnvAndBounds);
+
                 // We still need to prefer where-bounds over alias-bounds however.
-                // See tests/ui/winnowing/norm-where-bound-gt-alias-bound.rs.
-                //
-                // FIXME(const_trait_impl): should this behavior also be used by
```
Comment (compiler-errors) [inline compiler/rustc_next_trait_solver/src/solve/assembly/mod.rs:811]: AFAICT this fixme is no longer relevant? We use `assemble_and_merge` for host preds now.

File: compiler/rustc_next_trait_solver/src/solve/assembly/mod.rs [hunk 8]
```diff
@@ -284,6 +284,14 @@ where
     ) -> Vec<Candidate<I>>;
 }
 
+pub(super) enum AssembleCandidatesFrom {
+    All,
+    /// Only assemble candidates from the environment and alias bounds, ignoring
+    /// /user-written and built-in impls. We only expect `ParamEnv` and `AliasBound`
```
Comment (lcnr) [inline compiler/rustc_next_trait_solver/src/solve/assembly/mod.rs:290]: /user-written

also, pls add a quick comment to the enum itself describing why its necessary

File: compiler/rustc_next_trait_solver/src/solve/assembly/mod.rs [hunk 9]
```diff
@@ -778,47 +792,41 @@ where
...
-        candidates: Vec<Candidate<I>>,
+        goal: Goal<I, G>,
         inject_normalize_to_rigid_candidate: impl FnOnce(&mut EvalCtxt<'_, D>) -> QueryResult<I>,
     ) -> QueryResult<I> {
         let Some(proven_via) = proven_via else {
             // We don't care about overflow. If proving the trait goal overflowed, then
             // it's enough to report an overflow error for that, we don't also have to
             // overflow during normalization.
-            return Ok(self.make_ambiguous_response_no_constraints(MaybeCause::Ambiguity));
+            return Ok(self.forced_ambiguity(MaybeCause::Ambiguity)?.result);
```
Comment (lcnr) [inline compiler/rustc_next_trait_solver/src/solve/assembly/mod.rs:805]: any case where `make_ambiguous_response_no_constraints` was causing issues? or just general consistency. Also isn't this just `return self.forced_ambiguity()`? :<

Comment (compiler-errors) [reply compiler/rustc_next_trait_solver/src/solve/assembly/mod.rs:805]: > any case where make_ambiguous_response_no_constraints was causing issues? 

`make_ambiguous_response_no_constraints` was causing us not to register a *candidate kind*, which is the reason why I had commented out that assertion in the `BestObligation` folder above.

https://github.com/rust-lang/rust/pull/139762#discussion_r2041200133

I prefer just actually assembling a built-in candidate for ambiguity here, but if you care a lot about this then we could just remove the assertion I linked above, but it does mean unnecessarily stepping into the "search for failures due to no candidates assembled" code in the best obligation folder.

> lso isn't this just return self.forced_ambiguity()? :<

Nope, since we need to unwrap the candidate and return its query response.

i.e. `return Ok(x?.field)` is not `return x`.

Comment (lcnr) [reply compiler/rustc_next_trait_solver/src/solve/assembly/mod.rs:812]: `return x.map(|c| c.result)` then?
