### PR TITLE
Fix blessing of rmake tests

### LINKED ISSUE #129038: Blessing `rmake.rs` tests silently does nothing
While working on #129037, I noticed that running an `rmake.rs` test with `--bless` appears to succeed, but doesn't actually update the snapshot file(s).

This seems to be a side-effect of #126097. The test does successfully bless the temporary copy of the snapshot file in `build/`, but that has no effect on the original snapshot file in `tests/run-make/`.

### PR DESCRIPTION
**Pull request by Zalathar**
Fixes #129038.

When running in `--bless` mode, we now set the value of `RUSTC_BLESS_TEST` to the current test's source directory. This allows the diff helper in `run_make_support` to find the original snapshot file in the source directory and bless that, instead of unhelpfully blessing the temporary copy in `build`.

r? @jieyouxu

### CODE REVIEW

**Comment by Zalathar** [comment]
I thought about using a different variable to communicate the path, but `RUSTC_BLESS_TEST` is *right there*, and its value isn't being used for any other purpose anyway, so this avoids adding an extra moving piece.

File: src/tools/run-make-support/src/diff/mod.rs [hunk 1]
```diff
@@ -134,19 +128,33 @@ impl Diff {
...
             )
         }
     }
+
+    /// If we have an expected file to write into, and `RUSTC_BLESS_TEST` is
+    /// set, then write the actual output into the file and return `true`.
+    ///
+    /// We assume that `RUSTC_BLESS_TEST` contains the path to the original
+    /// test's source directory. That lets us bless the original snapshot file
+    /// in the source tree, not the copy in `build` that we would normally use.
```
Comment (jieyouxu) [inline src/tools/run-make-support/src/diff/mod.rs:146]: Nit: I would avoid stating `build` (as in the verbatim folder name) because I think CI uses a different root "build" folder, probably just `rmake_out` under build directory.

**Review by jieyouxu — APPROVED** [review]
Thanks for the fix!

**Comment by jieyouxu** [comment]
I'll r+ after PR CI is green

**Comment by jieyouxu** [comment]
Actually I can just let you r=me after PR CI is green

@bors delegate+

**Comment by jieyouxu** [comment]
*Ideally* we would want some kind of self-test, but I don't think we want to muck about in actual sources directories.

File: src/tools/run-make-support/src/diff/mod.rs (hunk 1 above)
Comment (Zalathar) [reply src/tools/run-make-support/src/diff/mod.rs:146]: Fixed.

**Comment by Zalathar** [comment]
Yeah, automatically testing this seems disproportionately hard, so for this PR I didn't bother.

**Comment by jieyouxu** [comment]
Yeah, feel free to r=me, I think we can just YOLO it (it was YOLO'd before anyway, so...)

**Comment by Zalathar** [comment]
CI is green.

@bors r=jieyouxu
