### PR TITLE
fix: prefer `(*p).clone` to `p.clone` if the `p` is a raw pointer

### LINKED ISSUE #126863: Unhelpful compiler suggestion when trying to dereference a pointer that is not `Copy`
### Code

```Rust
fn main() {
    let val = String::from("test");
    let p = std::ptr::addr_of!(val);
    unsafe {
        let inner: String = *p;
        dbg!(inner);
        std::mem::forget(val);
    }
}
```

### Current output

```Shell
error[E0507]: cannot move out of `*p` which is behind a raw pointer
 --> src/main.rs:5:29
  |
5 |         let inner: String = *p;
  |                             ^^ move occurs because `*p` has type `String`, which does not implement the `Copy` trait
  |
help: consider removing the dereference here
  |
5 -         let inner: String = *p;
5 +         let inner: String = p;
  |
help: consider cloning the value if the performance cost is acceptable
  |
5 -         let inner: String = *p;
5 +         let inner: String = p.clone();
  |

For more information about this error, try `rustc --explain E0507`.
```

### Desired output

```Shell
error[E0507]: cannot move out of `*p` which is behind a raw pointer
 --> src/main.rs:5:29
  |
5 |         let inner: String = *p;
  |                             ^^ move occurs because `*p` has type `String`, which does not implement the `Copy` trait
  |
help: consider using `ptr::read` to get the value the pointer refers to
  |
5 -         let inner: String = *p;
5 +         let inner: String = p.read();  
  |

For more information about this error, try `rustc --explain E0507`.
```

### Rationale and extra context

Cloning the pointer doesn't make sense in that situation and would cause a type mismatch error. I'm not sure whether any of the two current suggestions should be kept or removed in this case.

### Other cases

_No response_

### Rust Version

```Shell
rustc 1.79.0 (129f3b996 2024-06-10)
binary: rustc
commit-hash: 129f3b9964af4d4a709d1383930ade12dfe7c081
commit-date: 2024-06-10
host: x86_64-unknown-linux-gnu
release: 1.79.0
LLVM version: 18.1.7
```

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by linyihai**
Fixes https://github.com/rust-lang/rust/issues/126863

I wonder if there is a better way to solve the regression problem of this test case:
`tests/ui/borrowck/issue-20801.rs`.
It's okay to drop the dereference symbol in this scenario.

But it's not correct in https://github.com/rust-lang/rust/issues/126863

```
help: consider removing the dereference here
  |
5 -         let inner: String = *p;
5 +         let inner: String = p;
```

I haven't found out how to tell if clone pointer is allowed, i.e. no type mismatch occurs

### CODE REVIEW

File: compiler/rustc_borrowck/src/diagnostics/conflict_errors.rs [hunk 1]
```diff
@@ -1306,14 +1307,33 @@ impl<'tcx> MirBorrowckCtxt<'_, '_, '_, 'tcx> {
...
+                if matches!(inner_type.kind(), ty::RawPtr(..)) {
+                    is_raw_ptr = true;
+                    break;
+                }
+            }
         }
-        if inner_expr.span.lo() != expr.span.lo() {
+        // Cloning the raw pointer doesn't make sense in some cases and would cause a type mismatch error. (see #126863)
+        if inner_expr.span.lo() != expr.span.lo() && !is_raw_ptr {
+            // Romove "(*" or "(&"
```
Comment (Nadrieril) [inline compiler/rustc_borrowck/src/diagnostics/conflict_errors.rs:1320]:
```suggestion
            // Remove "(*" or "(&"
```

File: compiler/rustc_borrowck/src/diagnostics/conflict_errors.rs [hunk 2]
```diff
@@ -1306,14 +1307,33 @@ impl<'tcx> MirBorrowckCtxt<'_, '_, '_, 'tcx> {
                 return false;
             }
             inner_expr = inner;
+            let typeck_result = self.infcx.tcx.typeck(self.mir_def_id());
```
Comment (Nadrieril) [inline compiler/rustc_borrowck/src/diagnostics/conflict_errors.rs:1310]: nit: move that query out of the loop

**Review by Nadrieril — COMMENTED** [review]
Hi! LGTM except two nits

File: compiler/rustc_borrowck/src/diagnostics/conflict_errors.rs (hunk 2 above)
Comment (linyihai) [reply compiler/rustc_borrowck/src/diagnostics/conflict_errors.rs]: OK, thank your for your swift review. :)

**Comment by Nadrieril** [comment]
Thanks!

@bors r+
