### PR TITLE
Fix missing attribute merge on glob foreign re-exports

### LINKED ISSUE #113982: Doc feature banners won't show up when re-exporting items with wildcard
### Problem

I'm building a big library crate, composed of multiple sub-crates. These sub-crates are gated through [Cargo features](https://doc.rust-lang.org/cargo/reference/features.html), so the user can choose what to import.

My goal is to have "fruits" and "colors" feature banners in the docs, for each item, like this:

banners

However, I'm only achieving this by manually declaring each member of each sub-crate:

```rust
#[cfg(feature = "colors")]
pub use colors::{
    blue,
    red,
    white,
};

#[cfg(feature = "fruits")]
pub use fruits::{
    banana,
    grape,
};
```

There will be hundreds of declarations, so this is very error-prone. When using wildcards to the declare the members, the feature banners won't show up:

no-banners

```rust
#[cfg(feature = "colors")]
pub use colors::*;

#[cfg(feature = "fruits")]
pub use fruits::*;
```

Is this a bug or am I missing something?

Minimal reproducible example:

* https://github.com/rodrigocfd/big-lib

### Steps

1. Generate the docs with:

```
RUSTDOCFLAGS="--cfg docsrs" cargo +nightly doc --all-features --no-deps -p big-lib
```

### Possible Solution(s)

_No response_

### Notes

_No response_

### Version

```text
cargo 1.71.0 (cfd3bbd8f 2023-06-08)
release: 1.71.0
commit-hash: cfd3bbd8fe4fd92074dfad04b7eb9a923646839f
commit-date: 2023-06-08
host: x86_64-pc-windows-msvc
libgit2: 1.6.4 (sys:0.17.1 vendored)
libcurl: 8.0.1-DEV (sys:0.4.61+curl-8.0.1 vendored ssl:Schannel)
os: Windows 10.0.19045 (Windows 10 Pro) [64-bit]
```

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Fixes https://github.com/rust-lang/rust/issues/113982.

The attributes were not merged with the import's in case of glob re-export of foreign items.

r? @notriddle

### CODE REVIEW

File: src/librustdoc/clean/inline.rs [hunk 1]
```diff
@@ -125,7 +125,11 @@ pub(crate) fn try_inline(
         _ => return None,
     };
 
+    eprintln!(">>>>>> {name:?} {:?}", did);
+    eprintln!("2>>>>> {:?}", attrs);
```
Comment (Urgau) [inline src/librustdoc/clean/inline.rs:129]:
```suggestion
```

File: src/librustdoc/clean/inline.rs [hunk 2]
```diff
@@ -125,7 +125,11 @@ pub(crate) fn try_inline(
...
     let (attrs, cfg) = merge_attrs(cx, load_attrs(cx, did), attrs);
+    eprintln!("3>>>>> {attrs:?}");
+    eprintln!("4>>>>> {cfg:?}");
```
Comment (Urgau) [inline src/librustdoc/clean/inline.rs:132]:
```suggestion
```

File: src/librustdoc/clean/inline.rs (hunk 1 above)
Comment (GuillaumeGomez) [reply src/librustdoc/clean/inline.rs]: Monday...
