### PR TITLE
Make `--force-warns` a normal lint level option

### LINKED ISSUE #86958: force-warns panics with unknown lint name
Using the `--force-warns` option with an unknown lint name causes an ICE.

```
rustc +nightly --force-warns=abc -Zunstable-options foo.rs
```

I expected to see this happen: Issue a E0602 error.

### Meta

`rustc --version --verbose`:
```
rustc 1.55.0-nightly (885399992 2021-07-06)
binary: rustc
commit-hash: 885399992c4c1dde37b506b8507a7d69415646b9
commit-date: 2021-07-06
host: x86_64-apple-darwin
release: 1.55.0-nightly
LLVM version: 12.0.1
```

<details><summary>Backtrace</summary>
<p>

```
thread 'rustc' panicked at 'compiler/rustc_lint/src/levels.rs:117:37: A valid lint failed to produce a lint ids', compiler/rustc_middle/src/util/bug.rs:35:26
stack backtrace:
   0: std::panicking::begin_panic
   1: std::panic::panic_any
   2: rustc_middle::util::bug::opt_span_bug_fmt::{{closure}}
   3: rustc_middle::ty::context::tls::with_opt::{{closure}}
   4: rustc_middle::ty::context::tls::with_opt
   5: rustc_middle::util::bug::opt_span_bug_fmt
   6: rustc_middle::util::bug::bug_fmt
   7: rustc_lint::levels::LintLevelsBuilder::process_command_line::{{closure}}
   8: rustc_lint::levels::LintLevelsBuilder::new
   9: rustc_lint::context::EarlyContext::new
  10: rustc_lint::early::check_ast_crate
  11: rustc_interface::passes::pre_expansion_lint
  12: rustc_interface::passes::configure_and_expand
  13: rustc_interface::queries::Queries::expansion
  14: rustc_interface::queries::<impl rustc_interface::interface::Compiler>::enter
  15: rustc_span::with_source_map
  16: rustc_interface::interface::create_compiler_and_run
  17: scoped_tls::ScopedKey<T>::set
```

</p>
</details>

cc @rylev

### PR DESCRIPTION
**Pull request by inquisitivecrystal**
Now that `ForceWarn` is a lint level, there's no reason `--force-warns` should be treated differently from other options that set lint levels. This merges the `ForceWarn` handling in with the other lint level command line options. It also unifies all of the relevant selection logic in `compiler/rustc_lint/src/levels.rs`, rather than having some of it weirdly elsewhere.

Fixes #86958, which arose from the special-cased handling of `ForceWarn` having had an error in it.

### CODE REVIEW

File: compiler/rustc_lint/src/levels.rs [hunk 1]
```diff
@@ -104,23 +104,18 @@ impl<'s> LintLevelsBuilder<'s> {
                 Err(_) => continue, // errors handled in check_lint_name_cmdline above
             };
             for id in ids {
+                // ForceWarn and Forbid cannot be overriden
+                match specs.get(&id) {
+                    Some((Level::ForceWarn | Level::Forbid, _)) => continue,
+                    _ => (),
+                }
```
Comment (rylev) [inline compiler/rustc_lint/src/levels.rs:111]: Nit:
```suggestion
                if let Some((Level::ForceWarn | Level::Forbid, _)) = specs.get(&id) {
                     continue;
                }
```

**Review by rylev — CHANGES_REQUESTED** [review]
Awesome! We should add some tests. Specifically:
* --force-warns works with a bogus lint name 
* --force-warns and -F are not overwritten by later lint options

**Comment by rylev** [comment]
Now that force-warns is processed with other lints, you'll need to make sure that `--cap-lints` doesn't cap `force-warns`. This is somewhat duplicate logic found [here](https://github.com/rust-lang/rust/blob/2daa26b7caad3742c9c61849c67d7341c3df5b97/compiler/rustc_middle/src/lint.rs#L114-L120).

Also, this PR should partially fix https://github.com/rust-lang/rust/issues/70819 (the command line part of it) and thus it partially supersedes https://github.com/rust-lang/rust/pull/85298.

**Comment by inquisitivecrystal** [comment]
I think I've made all the requested changes. Let me know if I missed anything!

**Comment by rylev** [comment]
Unfortunately, I don't have review rights. I'll do a review though, but someone else will have to invoke bors. 

r? @davidtwco

File: src/test/ui/lint/cli-unknown-force-warn.stderr [hunk 2]
```diff
@@ -0,0 +1,15 @@
+error[E0602]: unknown lint: `foo_qux`
+   |
+   = note: requested on the command line with `--force-warns foo_qux`
+
+error[E0602]: unknown lint: `foo_qux`
```
Comment (rylev) [inline src/test/ui/lint/cli-unknown-force-warn.stderr:5]: Any idea why this error gets emitted multiple times?

File: compiler/rustc_lint/src/levels.rs [hunk 3]
```diff
@@ -91,36 +89,24 @@ impl<'s> LintLevelsBuilder<'s> {
...
-
             let lint_flag_val = Symbol::intern(lint_name);
 
             let ids = match store.find_lints(&lint_name) {
                 Ok(ids) => ids,
                 Err(_) => continue, // errors handled in check_lint_name_cmdline above
             };
             for id in ids {
+                // ForceWarn and Forbid cannot be overriden
+                if let Some((Level::ForceWarn | Level::Forbid, _)) = specs.get(&id) {
```
Comment (rylev) [inline compiler/rustc_lint/src/levels.rs:100]: Is this behavior documented anywhere?

**Review by rylev — APPROVED** [review]
Looking good! The issue with the E0602 being emitted multiple times is strange, but I don't think it's a blocker.

**Review by davidtwco — APPROVED** [review]
LGTM too, I'd like to see @rylev's comments resolved but I don't think those comments ought to block this landing.

File: src/test/ui/lint/cli-unknown-force-warn.stderr (hunk 2 above)
Comment (inquisitivecrystal) [reply src/test/ui/lint/cli-unknown-force-warn.stderr:5]: This happens for [some other cases as well](https://github.com/rust-lang/rust/blob/40c1623b16fb28f7625cab13570752d04513815c/src/test/ui/lint/lint-unknown-lint-cmdline.stderr). I think it's an artifact of the way the test is run, though I'm not totally sure?

File: compiler/rustc_lint/src/levels.rs (hunk 3 above)
Comment (inquisitivecrystal) [reply compiler/rustc_lint/src/levels.rs:100]: [Sort of.](https://doc.rust-lang.org/rustc/lints/levels.html#via-compiler-flag) However, the fact that forbid currently overrides the others isn't specified, and `force-warns` isn't documented at all because it's unstable. Given that the behavior is intrinsic to the definition of these lint levels, I don't think it's too surprising. It might be worth documenting it in the long run though?

**Comment by inquisitivecrystal** [comment]
Rebased!
