### PR TITLE
[MIR Borrowck] Moveck inline asm statements

### LINKED ISSUE #45695: MIR: asm statements don't participate in moveck
For example, 
```Rust
#![feature(asm)]

fn main() {
    let y: &mut isize;
    let x = &mut 0isize;
    unsafe {
        asm!("mov $1, $0" : "=r"(y) : "r"(x));
    }
    println!("{} {}", x, y);
}
```

This errors out in this way (with MIR borrowck enabled):
```
error[E0382]: use of moved value: `x` (Ast)
 --> fail.rs:9:23
  |
7 |         asm!("mov $1, $0" : "=r"(y) : "r"(x));
  |                                           - value moved here
8 |     }
9 |     println!("{} {}", x, y);
  |                       ^ value used here after move
  |
  = note: move occurs because `x` has type `&mut isize`, which does not implement the `Copy` trait

error[E0381]: borrow of possibly uninitialized variable: `x` (Mir)
 --> fail.rs:9:23
  |
9 |     println!("{} {}", x, y);
  |                       ^ use of possibly uninitialized `x`

error[E0381]: borrow of possibly uninitialized variable: `y` (Mir)
 --> fail.rs:9:26
  |
9 |     println!("{} {}", x, y);
  |                          ^ use of possibly uninitialized `y`

error: aborting due to 3 previous errors
```

Where only `x` is uninitialized with the AST borrowck, but both are uninitialized with MIR borrowck

Also, if there's a destructor for an input, it will run *right after the asm statement is executed*, which doesn't make any sense (the assertion there should *fail*, not *succeed*)
```Rust
#![feature(asm)]

use std::cell::Cell;

#[repr(C)]
struct NoisyDrop<'a>(&'a Cell<&'static str>);
impl<'a> Drop for NoisyDrop<'a> {
    fn drop(&mut self) {
        self.0.set("destroyed!");
    }
}

fn main() {
    let status = Cell::new("alive");
    let _y: Box<NoisyDrop>;
    let x = Box::new(NoisyDrop(&status));
    unsafe {
        asm!("mov $1, $0" : "=r"(_y) : "r"(x));
    }
    assert_eq!(status.get(), "destroyed!"); // this makes 0 sense
}
```

This is because move checking just ignores inline asm, while it should treat them like AST borrowck does (inputs move data out, outputs move data in)

### PR DESCRIPTION
**Pull request by matthewjasper**
Closes #45695

New behavior:
* Input operands to `asm!` are moved, direct output operands are initialized.
* Direct, non-read-write outputs match the assignment changes in #46752 (Shallow writes, end borrows).

### CODE REVIEW

File: src/test/run-pass/asm-in-moved.rs [hunk 1]
```diff
@@ -0,0 +1,42 @@
...
+// file at the top-level directory of this distribution and at
+// http://rust-lang.org/COPYRIGHT.
+//
+// Licensed under the Apache License, Version 2.0 <LICENSE-APACHE or
+// http://www.apache.org/licenses/LICENSE-2.0> or the MIT license
+// <LICENSE-MIT or http://opensource.org/licenses/MIT>, at your
+// option. This file may not be copied, modified, or distributed
+// except according to those terms.
+
+// ignore-s390x
```
Comment (arielb1) [inline src/test/run-pass/asm-in-moved.rs]: Most tests use this instead:
```
#[cfg(any(target_arch = "x86", target_arch = "x86_64"))]
```

see e.g. the asm-out-assign test

**Comment by arielb1** [comment]
r=me with tests fixed to use
```
#[cfg(any(target_arch = "x86", target_arch = "x86_64"))]
```

**Comment by matthewjasper** [comment]
Done. The compile-fail test still uses `ignore`, as cfg isn't understood by the test-runner.
