### PR TITLE
Shortcuts for min/max on ordinary BTreeMap/BTreeSet iterators

### LINKED ISSUE #59947: Max & Min on BTreeMap are unexpectedly slow
Hello,

The use of iterator's `max` and `min` function do not seams to take advantage of the specific ordering of BTreeMap and looks like it is browsing the whole container.
Although it is still possible to have fast access to minimum and maximum element by using `first` and `first_back`, this is not semantically explicite and you can expect that developers may not know the subtilities regarding BTreeMap's implementation and could assume the complexity should be the same.

Here is the benchmark result
```
running 4 tests
test bench_first ... bench:           9 ns/iter (+/- 0)
test bench_last  ... bench:           8 ns/iter (+/- 0)
test bench_max   ... bench:       3,603 ns/iter (+/- 536)
test bench_min   ... bench:       3,755 ns/iter (+/- 328)
```

and here is the benchmark code:
```
#![feature(test)]

extern crate test;
#[macro_use]
extern crate lazy_static;

use test::Bencher;
use std::collections::BTreeMap;

lazy_static! {
    static ref MAP: BTreeMap<i32, i32> = {
        let mut map = BTreeMap::new();

        for i in 0..1000 {map.insert(i, i);}

        map
    };
}
#[bench]
fn bench_max(b: &mut Bencher) {

    b.iter(|| {MAP.iter().max()});
}

#[bench]
fn bench_first(b: &mut Bencher) {

    b.iter(|| {MAP.iter().next()});
}

#[bench]
fn bench_last(b: &mut Bencher) {
    b.iter(|| {MAP.iter().next_back()});
}

#[bench]
fn bench_min(b: &mut Bencher) {
    b.iter(|| {MAP.iter().min()});
}
```

I don't know the details of the trait implementation, but I think it would be very nice for the community if you can make `std::collections::btree_map::Iter` take advantage of the ordering. :)

### PR DESCRIPTION
**Pull request by ssomers**
Closes #59947: a performance tweak that might benefit some. Optimizes `min` and `max ` on all btree double-ended iterators that do not drop, i.e. the iterators created by:

- `BTreeMap::iter`
- `BTreeMap::iter_mut`
- `BTreeMap::keys` and `BTreeSet::iter`
- `BTreeMap::range` and `BTreeSet::range`
- `BTreeMap::range_mut`

Also in these (currently) single-ended iterators, but obviously for `min` only:
- `BTreeSet::difference`
- `BTreeSet::intersection`
- `BTreeSet::symmetric_difference`
- `BTreeSet::union`

Did not do this in iterators created by `into_iter` to preserve drop order, as outlined in #62316.

Did not do this in iterators created by `drain_filter`, possibly to preserve drop order, possibly to preserve predicate invocation, mostly to not have to think about it too hard (I guess maybe it wouldn't be a change for `min`, which is the only shortcut possible in this single-ended iterator).

### CODE REVIEW

File: src/liballoc/tests/btree/map.rs [hunk 1]
```diff
@@ -309,6 +309,41 @@ fn test_iter_mixed() {
...
+    assert!(a.range(..).min().is_none());
+    assert!(a.range(..).max().is_none());
+    assert!(a.range_mut(..).min().is_none());
+    assert!(a.range_mut(..).max().is_none());
+    assert!(a.keys().min().is_none());
+    assert!(a.keys().max().is_none());
+    assert!(a.values().min().is_none());
+    assert!(a.values().max().is_none());
+    assert!(a.values_mut().min().is_none());
+    assert!(a.values_mut().max().is_none());
```
Comment (ssomers) [inline src/liballoc/tests/btree/map.rs:328]: Why did I not write `assert_eq!(..., None)`? Some invisible force told me to, possibly aliens, possibly the unit test framework of some other language that rejects a typeless None as ambiguous.

**Comment by Mark-Simulacrum** [comment]
Could you provide a summary of the affected impls and which ones are left out of scope?

**Comment by ssomers** [comment]
I couldn't come up with a reasonable reason to leave them out, so added some more. Also straightened out the test code.

**Comment by Mark-Simulacrum** [comment]
Okay, that set of iterators does look correct to me. However, I think the implementation here is a bit wrong if we want to avoid a behavior change. In particular, this makes `min()` and `max()` not consume the iterator. I personally think that's fine, but I would like to check in with @rust-lang/libs -- do we have guarantees about whether methods like min/max exhaust iterators today (in cases where they can be implemented more efficiently)?

One downside (or upside, I guess) of the current implementation is that you can call `min()` multiple times and it'll keep returning "the next minimum" which is both nice but also perhaps not what the user expected.

**Comment by sfackler** [comment]
> In particular, this makes `min()` and `max()` not consume the iterator.

For a generic iterator, we do need min() and max() to advance past every element of the iterator, but since these iterators are specific ones where iteration does not have a side effect the change isn't observable.

min() and max() consume the iterator by value, so you can't call them multiple times.

**Comment by Mark-Simulacrum** [comment]
Ah for some reason I thought by_ref() let you magically have ownership but that doesn't make any sense now that I think about it some more. Yes, this seems fine then.

@bors r+

**Comment by RalfJung** [comment]
I think this PR caused a regression: https://github.com/rust-lang/rust/issues/73915
