### PR TITLE
Ensure that statics are always ByRef

### LINKED ISSUE #50706: const_val_field on non-field
Compiler version: `rustc 1.27.0-nightly (ff2ac35db 2018-05-12)`

Stack trace:
```
thread 'main' panicked at 'const_val_field on non-field', libcore/option.rs:914:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:211
   3: std::panicking::default_hook
             at libstd/panicking.rs:227
   4: rustc::util::common::panic_hook
   5: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:467
   6: std::panicking::begin_panic_fmt
             at libstd/panicking.rs:350
   7: rust_begin_unwind
             at libstd/panicking.rs:328
   8: core::panicking::panic_fmt
             at libcore/panicking.rs:71
   9: core::option::expect_failed
             at libcore/option.rs:914
  10: rustc_mir::interpret::const_eval::const_val_field
  11: rustc_mir::hair::pattern::PatternContext::const_to_pat::{{closure}}
  12: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T, I>>::from_iter
  13: rustc_mir::hair::pattern::PatternContext::const_to_pat
  14: rustc_mir::hair::pattern::PatternContext::lower_path
  15: rustc_mir::hair::pattern::PatternContext::lower_pattern
  16: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &'a mut F>::call_once
  17: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T, I>>::from_iter
  18: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T, I>>::from_iter
  19: <rustc_mir::hair::pattern::check_match::MatchVisitor<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_expr
  20: <rustc_mir::hair::pattern::check_match::MatchVisitor<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_expr
  21: <rustc_mir::hair::pattern::check_match::MatchVisitor<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_body
  22: rustc::session::Session::track_errors
  23: rustc_mir::hair::pattern::check_match::check_match
  24: rustc::dep_graph::graph::DepGraph::with_task_impl
  25: rustc::ty::context::tls::with_related_context
  26: rustc::ty::maps::plumbing::<impl rustc::ty::context::TyCtxt<'a, 'gcx, 'tcx>>::force_query_with_job
  27: rustc::ty::maps::plumbing::<impl rustc::ty::context::TyCtxt<'a, 'gcx, 'tcx>>::get_query
  28: rustc::hir::intravisit::Visitor::visit_nested_body
  29: rustc::hir::Crate::visit_all_item_likes
  30: rustc_mir::hair::pattern::check_match::check_crate
  31: rustc::util::common::time
  32: rustc::ty::context::tls::enter_context
  33: <std::thread::local::LocalKey<T>>::with
  34: rustc::ty::context::TyCtxt::create_and_enter
  35: rustc_driver::driver::compile_input
  36: rustc_driver::run_compiler_impl
  37: <scoped_tls::ScopedKey<T>>::set
  38: syntax::with_globals
  39: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
  40: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:105
  41: rustc_driver::run
  42: rustc_driver::main
  43: std::rt::lang_start::{{closure}}
  44: std::panicking::try::do_call
             at libstd/rt.rs:59
             at libstd/panicking.rs:310
  45: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:105
  46: std::rt::lang_start_internal
             at libstd/panicking.rs:289
             at libstd/panic.rs:374
             at libstd/rt.rs:58
  47: main
  48: __libc_start_main
  49: <unknown>
query stack during panic:
#0 [check_match] processing `Stat::from_index`
end of query stack

error: internal compiler error: unexpected panic
```

Code:
```rust
pub struct Stats;

#[derive(PartialEq, Eq)]
pub struct StatVariant {
    pub id: u8,
    _priv: (),
}

#[derive(PartialEq, Eq)]
pub struct Stat {
    pub variant: StatVariant,
    pub index: usize,
    _priv: (),
}

impl Stats {

    pub const TEST: StatVariant = StatVariant{id: 0, _priv: (),};
    #[allow(non_upper_case_globals)]
    pub const A: Stat = Stat{
         variant: Self::TEST,
         index: 0,
         _priv: (),};
}

impl Stat {
    pub fn from_index(variant: StatVariant, index: usize) -> Option<Stat> {
        let stat = Stat{variant, index, _priv: (),};
        match stat {
            Stats::A => Some(Stats::A),
            _ => None,
        }
    }
}

fn main() {

}
```

I tried to reduce it as it was originally generated by a macro, this is about as small as I could get it.

### PR DESCRIPTION
**Pull request by oli-obk**
Statics aren't values to be used, they are names for memory locations.

r? @eddyb

cc @Zoxc 

fixes #50706

### CODE REVIEW

File: src/librustc_trans/mir/constant.rs [hunk 1]
```diff
@@ -171,11 +128,11 @@ pub fn trans_static_initializer<'a, 'tcx>(
     let param_env = ty::ParamEnv::reveal_all();
     let static_ = cx.tcx.const_eval(param_env.and(cid))?;
```
Comment (eddyb) [inline src/librustc_trans/mir/constant.rs]: I'm thinking `const_eval` isn't the best, but it's probably an okay compromise.

Comment (oli-obk) [reply src/librustc_trans/mir/constant.rs]: We could create a separate query for statics.

**Comment by Zoxc** [comment]
This makes `ConstValue` for statics special cased to avoid the optimizations in `ConstValue`. This reduces performance and adds unnecessary complexity.

File: src/librustc_mir/interpret/const_eval.rs [hunk 2]
```diff
@@ -98,44 +98,20 @@ pub fn value_to_const_value<'a, 'tcx>(
     val: Value,
     ty: Ty<'tcx>,
 ) -> &'tcx ty::Const<'tcx> {
-    let layout = tcx.layout_of(ty::ParamEnv::reveal_all().and(ty)).unwrap();
-
-    if layout.is_zst() {
-        return ty::Const::from_const_value(
-            tcx,
-            ConstValue::ByVal(PrimVal::Undef),
```
Comment (Zoxc) [inline src/librustc_mir/interpret/const_eval.rs]: Is ZST always `ByVal(PrimVal::Undef)` in Miri?

Comment (oli-obk) [reply src/librustc_mir/interpret/const_eval.rs]: No. Accessing a zst field of a ByRef will return a ByRef

Comment (Zoxc) [reply src/librustc_mir/interpret/const_eval.rs]: Then this code should still be here.

File: src/librustc_mir/interpret/const_eval.rs [hunk 3]
```diff
@@ -98,44 +98,20 @@ pub fn value_to_const_value<'a, 'tcx>(
...
-                ConstValue::ByVal(val)
-            } else {
-                bug!("expected ByVal value, got {:?}", val);
-            }
-        }
-        layout::Abi::ScalarPair(..) => {
-            if let Value::ByValPair(a, b) = val {
-                ConstValue::ByValPair(a, b)
-            } else {
-                bug!("expected ByValPair value, got {:?}", val);
```
Comment (Zoxc) [inline src/librustc_mir/interpret/const_eval.rs]: Please keep these sanity checks. At least when debug-assertions is on. I really don't trust Miri code to be correct.

File: src/librustc_mir/interpret/const_eval.rs (hunk 2 above)
Comment (oli-obk) [reply src/librustc_mir/interpret/const_eval.rs]: Why? Won't we simply get an empty allocation in the ByRef?

**Comment by oli-obk** [comment]
@bors r-

more sanity checks

File: src/librustc_mir/interpret/const_eval.rs (hunk 2 above)
Comment (Zoxc) [reply src/librustc_mir/interpret/const_eval.rs]: Each Rust value should only map to one `ConstValue`. so a ZST type cannot be both `ByVal(PrimVal::Undef)` and `ByRef`.

Comment (oli-obk) [reply src/librustc_mir/interpret/const_eval.rs]: that would require us to spray is_zst checks everywhere. Miri already "violates" your assumption left and right.

The current code tries to reduce special cases, only ignoring zst memory reads in Memory, not earlier.

Comment (oli-obk) [reply src/librustc_mir/interpret/const_eval.rs]: Wait. wouldn't it actually make more sense to ~~try to~~ move to ByRef for zst everywhere? You can't ever have a zst value. They have no values (well one value, but we don't ever read/write it).

**Comment by oli-obk** [comment]
@eddyb @Zoxc this now also fixes #50706 (fix included here because without this PR the fix might do stupid things when accessing the fields of statics)

File: src/librustc/mir/interpret/value.rs [hunk 4]
```diff
@@ -9,12 +9,12 @@ use super::{EvalResult, MemoryPointer, PointerArithmetic, Allocation};
...
-    // Used only for types with layout::abi::Scalar ABI and ZSTs which use PrimVal::Undef
+    /// Used only for types with layout::abi::Scalar ABI and ZSTs which use PrimVal::Undef
     ByVal(PrimVal),
-    // Used only for types with layout::abi::ScalarPair
+    /// Used only for types with layout::abi::ScalarPair
     ByValPair(PrimVal, PrimVal),
-    // Used only for the remaining cases
-    ByRef(&'tcx Allocation),
+    /// Used only for the remaining cases. An allocation + offset into the allocation
+    ByRef(&'tcx Allocation, u64),
```
Comment (eddyb) [inline src/librustc/mir/interpret/value.rs]: Please use `Size` for offsets.

Comment (oli-obk) [reply src/librustc/mir/interpret/value.rs]: done

File: src/librustc/mir/interpret/mod.rs [hunk 5]
```diff
@@ -109,42 +109,42 @@ impl<T: layout::HasDataLayout> PointerArithmetic for T {}
...
-    pub fn new(alloc_id: AllocId, offset: u64) -> Self {
+    pub fn new(alloc_id: AllocId, offset: Size) -> Self {
         MemoryPointer { alloc_id, offset }
     }
 
     pub(crate) fn wrapping_signed_offset<C: HasDataLayout>(self, i: i64, cx: C) -> Self {
         MemoryPointer::new(
             self.alloc_id,
-            cx.data_layout().wrapping_signed_offset(self.offset, i),
+            Size::from_bytes(cx.data_layout().wrapping_signed_offset(self.offset.bytes(), i)),
```
Comment (eddyb) [inline src/librustc/mir/interpret/mod.rs]: Why would `wrapping_signed_offset` not work on a `Size`?

Comment (oli-obk) [reply src/librustc/mir/interpret/mod.rs]: because `SIze` doesn't have a sign. I mean we could create an `Offset` type (which would then also be the `Output` of `impl Sub for Size`)...
