### PR TITLE
Don't mark `#[target_feature]` safe fns as unsafe in rustdoc JSON.

### LINKED ISSUE #142655: rustdoc-json: `#[target_feature]` incorrectly causes safe functions to be listed as `unsafe`
I tried this code:

```rust
#[target_feature(enable = "sse2")]
pub fn compute(x: u32) -> u32 {
    x + 1
}
```

I expected to see this happen: rustdoc JSON should contain an entry for `compute` whose `header` field says:
```
"header": {
    "is_const": false,
    "is_unsafe": false,
    "is_async": false,
    "abi": "Rust"
},
```

Instead, this happened: the rustdoc JSON entry for `compute` incorrectly lists it as `unsafe`. Here's its entire item entry from a `format_version: 46` rustdoc JSON file:
```json5
"0": {
    "id": 0,
    "crate_id": 0,
    "name": "compute",
    "span": {
        "filename": "src/lib.rs",
        "begin": [
            2,
            1
        ],
        "end": [
            4,
            2
        ]
    },
    "visibility": "public",
    "docs": null,
    "links": {},
    "attrs": [
        "#[target_feature(enable = \"sse2\")]"
    ],
    "deprecation": null,
    "inner": {
        "function": {
            "sig": {
                "inputs": [
                    [
                        "x",
                        {
                            "primitive": "u32"
                        }
                    ]
                ],
                "output": {
                    "primitive": "u32"
                },
                "is_c_variadic": false
            },
            "generics": {
                "params": [],
                "where_predicates": []
            },
            "header": {
                "is_const": false,
                "is_unsafe": true,  # <--- BUG!
                "is_async": false,
                "abi": "Rust"
            },
            "has_body": true
        }
    }
},
```

### Meta

`rustc --version --verbose`:
```
rustc 1.89.0-nightly (45acf54ee 2025-06-16)
binary: rustc
commit-hash: 45acf54eea118ed27927282b5e0bfdcd80b7987c
commit-date: 2025-06-16
host: x86_64-unknown-linux-gnu
release: 1.89.0-nightly
LLVM version: 20.1.5
```

@rustbot label +A-rustdoc-json

cc @aDotInTheVoid

### PR DESCRIPTION
**Pull request by obi1kenobi**
Fixes https://github.com/rust-lang/rust/issues/142655 by explicitly checking whether functions are safe but using `#[target_feature]`, instead of relying on the `FnHeader::is_unsafe()` method which considers such functions unsafe.

I don't believe this merits a bump of the rustdoc JSON `FORMAT_VERSION` constant, since the format is unchanged and this is just a small bugfix.

r? aDotInTheVoid

### CODE REVIEW

**Comment by obi1kenobi** [comment]
While reading up on the overall context, I noticed that @oli-obk had considered changing the `Safety` enum to express the `#[target_feature]` complexity in https://github.com/rust-lang/rust/pull/134317 and appears to have decided in favor of a smaller change in https://github.com/rust-lang/rust/pull/134353.

I'm not qualified to decide whether refactoring `Safety` or `FnHeader` to fully capture `#[target_feature]`'s complexity is worth it, nor what the best way to do it is. I just wanted to raise the fact that we now know the fix from https://github.com/rust-lang/rust/pull/134353 isn't entirely without its own "easy to get wrong" aspects, so it may be worth another look.

File: src/librustdoc/json/conversions.rs [hunk 1]
```diff
@@ -383,10 +384,16 @@ impl FromClean<clean::Union> for Union {
 
 impl FromClean<rustc_hir::FnHeader> for FunctionHeader {
     fn from_clean(header: &rustc_hir::FnHeader, renderer: &JsonRenderer<'_>) -> Self {
+        // The type system's internal implementation details consider
+        // safe functions with the `#[target_feature]` attribute as analogous to unsafe functions.
+        // `header.is_unsafe()` returns `true` for them. But that's not the right decision
+        // for rustdoc, so we specifically exclude that case.
+        let is_unsafe =
+            header.is_unsafe() && !matches!(header.safety, HeaderSafety::SafeTargetFeatures);
```
Comment (oli-obk) [inline src/librustdoc/json/conversions.rs]: Make this an exhaustive match on `header.safety` (not not `header.safety()`!).

Tho long term I think we'll want to change the `rustdoc::json::FunctionHeader` to just fully have the header safety information. Even normal rustdoc rendering should probably distinguish between safe functions and safe-in-some-contexts functions and have appropriate hints somewhere.

File: src/librustdoc/json/conversions.rs [hunk 2]
```diff
@@ -383,10 +384,16 @@ impl FromClean<clean::Union> for Union {
 
 impl FromClean<rustc_hir::FnHeader> for FunctionHeader {
     fn from_clean(header: &rustc_hir::FnHeader, renderer: &JsonRenderer<'_>) -> Self {
+        // The type system's internal implementation details consider
+        // safe functions with the `#[target_feature]` attribute as analogous to unsafe functions.
+        // `header.is_unsafe()` returns `true` for them. But that's not the right decision
+        // for rustdoc, so we specifically exclude that case.
```
Comment (aDotInTheVoid) [inline src/librustdoc/json/conversions.rs]: NIT: It might be nice to link back to https://github.com/rust-lang/rust/issues/142655 here

**Comment by aDotInTheVoid** [comment]
Thanks!

r=me with oli's match thing changed. (You don't need to handle my nit).

@bors delegate+

File: src/librustdoc/json/conversions.rs (hunk 2 above)
Comment (obi1kenobi) [reply src/librustdoc/json/conversions.rs]: Done inside the exhaustive match's `HeaderSafety::SafeTargetFeatures` arm.

File: src/librustdoc/json/conversions.rs (hunk 1 above)
Comment (obi1kenobi) [reply src/librustdoc/json/conversions.rs]: Sounds good, thanks Oli!
