### PR TITLE
derive(SmartPointer): assume pointee from the single generic and better error messages

### LINKED ISSUE #129465: The `#[pointee]` attribute is required even if there is only one generic parameter
Currently, the following code triggers a compilation failure.
```rs
#![feature(derive_smart_pointer)]
use core::marker::SmartPointer;

#[repr(transparent)]
#[derive(SmartPointer)]
struct MyArc<T: ?Sized> {
    inner: *mut T,
}
```
```text
error: At least one generic type should be designated as `#[pointee]` in order to derive `SmartPointer` traits
 --> src/lib.rs:5:10
  |
5 | #[derive(SmartPointer)]
  |          ^^^^^^^^^^^^
  |
  = note: this error originates in the derive macro `SmartPointer` (in Nightly builds, run with -Z macro-backtrace for more info)
```
However, [the RFC](https://rust-lang.github.io/rfcs/3621-derive-smart-pointer.html) says that specifying `#[pointee]` when the struct has only one type parameter is allowed, but not required.

See also [this patch on the LKML](https://lore.kernel.org/all/20240823-derive-smart-pointer-v1-1-53769cd37239@google.com/).

Tracking issue: #123430
cc @dingxiangfei2009

### PR DESCRIPTION
**Pull request by dingxiangfei2009**
Fix #129465 

Actually RFC says that `#[pointee]` can be inferred when there is no ambiguity, or there is only one generic type parameter so to say.

cc @Darksonn 

r? @compiler-errors

### CODE REVIEW

File: compiler/rustc_builtin_macros/src/deriving/smart_ptr.rs [hunk 1]
```diff
@@ -78,33 +84,59 @@ pub fn expand_deriving_smart_ptr(
...
+                    }
+                } else {
+                    match pointee_param {
+                        PointeeChoice::None => pointee_param = PointeeChoice::Assumed(idx),
+                        PointeeChoice::Assumed(_) | PointeeChoice::Ambiguous => {
+                            pointee_param = PointeeChoice::Ambiguous
+                        }
+                        PointeeChoice::Exactly(_, _)
+                        | PointeeChoice::MultiplePointeeChoice(_, _) => {}
                     }
```
Comment (Darksonn) [inline compiler/rustc_builtin_macros/src/deriving/smart_ptr.rs:106]: I wonder if we can simplify these map operations with side effects by iterating multiple times. For example: (untested)
```rs
let self_params = generics
    .params
    .iter()
    .enumerate()
    .map(|(idx, p)| match p.kind {
        GenericParamKind::Lifetime => GenericArg::Lifetime(cx.lifetime(p.span(), p.ident)),
        GenericParamKind::Type { .. } => GenericArg::Type(cx.ty_ident(p.span(), p.ident)),
        GenericParamKind::Const { .. } => GenericArg::Const(cx.const_ident(p.span(), p.ident)),
    })
    .collect::<Vec<_>>();

let all_type_params = generics
    .params
    .iter()
    .enumerate()
    .filter_map(|(idx, p)| match p.kind {
        GenericParamKind::Type { .. } => Some((idx, p.span())),
        _ => None,
    })
    .collect::<Vec<(usize, Span)>>();

let pointee_params = generics
    .params
    .iter()
    .enumerate()
    .filter_map(|(idx, p)| match p.kind {
        GenericParamKind::Type { .. } if p.attrs().iter().any(|attr| attr.has_name(sym::pointee)) => Some((idx, p.span())),
        _ => None,
    })
    .collect::<Vec<(usize, Span)>>();

let pointee_param = match (pointee_params.as_slice(), all_type_params.as_slice()) {
    ([(idx, _span)], _) => idx,
    ([], [(idx, _span)]) => idx,
    ([], []) => {
        cx.dcx().struct_span_err(span, "`SmartPointer` requires a generic parameter").emit();
        return;
    }
    ([], _) => {
        let all_type_spans = all_type_params.into_iter().map(|(idx,span)| span).collect();
        cx.dcx().struct_span_err(all_type_spans, "you must use `#[pointee]` to specify which parameter is the `SmartPointer` pointee").emit();
        return;
    }
    (_, _) => {
        let pointee_spans = pointee_params.into_iter().map(|(idx,span)| span).collect();
        cx.dcx().struct_span_err(pointee_spans, "you can only use `#[pointee]` once").emit();
        return;
    }
};
```

Comment (dingxiangfei2009) [reply compiler/rustc_builtin_macros/src/deriving/smart_ptr.rs]: Applied with slight adaptation

So now we one pass through the generics to get ourserlves the `self_params`. One more pass through the iterator is used to collect only the type parameters.
- If we find zero type parameters, err with diagnosis
- If we find exactly one type parameter, use it as `#[pointee]`
- Otherwise, filter through type parameters on whether there is `#[pointee]` designation and err when more than one such parameters are found

File: compiler/rustc_builtin_macros/src/deriving/smart_ptr.rs [hunk 2]
```diff
@@ -68,43 +67,65 @@ pub fn expand_deriving_smart_ptr(
...
+        let mut pointees = type_params
+            .iter()
+            .filter_map(|&(idx, span, is_pointee)| is_pointee.then_some((idx, span)))
+            .fuse();
+        match (pointees.next(), pointees.next()) {
+            (Some((idx, _span)), None) => idx,
+            (None, _) => {
+                cx.dcx().struct_span_err(
+                    span,
+                    "Exactly one generic parameters when there are at least two generic type parameters \
```
Comment (compiler-errors) [inline compiler/rustc_builtin_macros/src/deriving/smart_ptr.rs:113]: diagnostics should not be capitalized

also this message could be tweaked:

> exactly one generic type parameter must be marked as `#[pointee]` to derive `SmartPointer` traits

File: compiler/rustc_builtin_macros/src/deriving/smart_ptr.rs [hunk 3]
```diff
@@ -68,43 +67,65 @@ pub fn expand_deriving_smart_ptr(
...
         ).emit();
         return;
-    };
-    if !multiple_pointee_diag.is_empty() {
-        for diag in multiple_pointee_diag {
-            diag.emit();
-        }
-        return;
     }
+    let pointee_param_idx = if type_params.len() == 1 {
```
Comment (compiler-errors) [inline compiler/rustc_builtin_macros/src/deriving/smart_ptr.rs:100]: could you special case the `== 0` case?

File: compiler/rustc_builtin_macros/src/deriving/smart_ptr.rs (hunk 2 above)
Comment (compiler-errors) [reply compiler/rustc_builtin_macros/src/deriving/smart_ptr.rs:113]: also, there is no test for this message?

File: compiler/rustc_builtin_macros/src/deriving/smart_ptr.rs [hunk 4]
```diff
@@ -68,43 +67,65 @@ pub fn expand_deriving_smart_ptr(
...
+                    "Exactly one generic parameters when there are at least two generic type parameters \
+                    should be designated as `#[pointee]` in order to derive `SmartPointer` traits",
+                ).emit();
+                return;
+            }
+            (Some((_, one)), Some((_, another))) => {
+                cx.dcx()
+                    .struct_span_err(
+                        vec![one, another],
+                        "`SmartPointer` can only admit one type as pointee",
```
Comment (compiler-errors) [inline compiler/rustc_builtin_macros/src/deriving/smart_ptr.rs:122]: Can you adjust this message?

> only one type parameter can be marked as `#[pointee]` when deriving `SmartPointer` traits

sounds more natural that way

**Comment by dingxiangfei2009** [comment]
@rustbot ready

- Ran through the test and made sure that all diagnostic messages appeared, or have been used, at least once
- Applied suggestions on wording

File: compiler/rustc_builtin_macros/src/deriving/smart_ptr.rs (hunk 4 above)
Comment (dingxiangfei2009) [reply compiler/rustc_builtin_macros/src/deriving/smart_ptr.rs]: Applied

File: compiler/rustc_builtin_macros/src/deriving/smart_ptr.rs (hunk 3 above)
Comment (dingxiangfei2009) [reply compiler/rustc_builtin_macros/src/deriving/smart_ptr.rs]: Applied. Moved the check above into here.

File: compiler/rustc_builtin_macros/src/deriving/smart_ptr.rs (hunk 2 above)
Comment (dingxiangfei2009) [reply compiler/rustc_builtin_macros/src/deriving/smart_ptr.rs]: Oops. Added.

**Review by compiler-errors — APPROVED** [review]

File: compiler/rustc_builtin_macros/src/deriving/smart_ptr.rs (hunk 2 above)
Comment (dingxiangfei2009) [reply compiler/rustc_builtin_macros/src/deriving/smart_ptr.rs]: I forgot to add the hunk with the updated message as per your suggestion. It is checked in now.

File: compiler/rustc_builtin_macros/src/deriving/smart_ptr.rs [hunk 5]
```diff
@@ -68,43 +67,63 @@ pub fn expand_deriving_smart_ptr(
...
-        for diag in multiple_pointee_diag {
-            diag.emit();
+    } else if type_params.len() == 1 {
+        // Regardless of the only type param being designed as `#[pointee]` or not, we can just use it as such
+        type_params[0].0
+    } else {
+        let mut pointees = type_params
+            .iter()
+            .filter_map(|&(idx, span, is_pointee)| is_pointee.then_some((idx, span)))
+            .fuse();
```
Comment (nnethercote) [inline compiler/rustc_builtin_macros/src/deriving/smart_ptr.rs:106]: Why is this `fuse` here? `type_params` is a `Vec` so there is no way that this iterator could return `None` and then later return `Some`.
