### PR TITLE
tests: add sanity-check assembly test for every target

### LINKED ISSUE #119910: powerpc64-unknown-linux-musl target data-layout does not match LLVM, making the target useless
```
cargo +nightly build -Zbuild-std=core --target=powerpc64-unknown-linux-musl
```
```
error: internal compiler error: compiler/rustc_codegen_llvm/src/context.rs:178:13: data-layout for target
`powerpc64-unknown-linux-musl`,
`E-m:e-Fi64-i64:64-n32:64-S128-v256:256:256-v512:512:512`, differs from
LLVM target's `powerpc64-unknown-linux-musl` default layout,
`E-m:e-Fn32-i64:64-n32:64-S128-v256:256:256-v512:512:512`
```
(wrapped by hand to make the problem clear)

The function pointer alignment is the same as our powerpc64-unknown-linux-gnu target, so the discrepancy must be in LLVM.

While this _is_ a tier 3 target, we are completely unable to generate code for it, so at some point this part of the target tier policy will become relevant (emphasis mine):

If a tier 3 target stops meeting these requirements, or the target maintainers no longer have interest or time, **or the target shows no signs of activity and has not built for some time**, or removing the target would improve the quality of the Rust codebase, **we may post a PR to remove it; any such PR will be CCed to the target maintainers (there are none, not even for the Tier 2 -gnu variant)** (and potentially other people who have previously worked on the target), to check potential interest in improving the situation.

---

I have trawled the issue tracker and I cannot find any evidence that this target is in use; all issues seem related to `powerpc-unknown-linux-gnu` or the `powerpc64le-` targets.

### PR DESCRIPTION
**Pull request by davidtwco**
Fixes #119910.

Adds a basic assembly test checking that each target can produce assembly and update the target tier policy to require this.

cc rust-lang/compiler-team#655
r? @wesleywiser

### CODE REVIEW

File: tests/assembly/targets.rs [hunk 1]
```diff
@@ -0,0 +1,700 @@
...
+// [x86_64_uwp_windows_gnu]: needs-llvm-components: x86
+// revisions: x86_64_uwp_windows_msvc
+// [x86_64_uwp_windows_msvc]: compile-flags: --target x86_64-uwp-windows-msvc
+// [x86_64_uwp_windows_msvc]: needs-llvm-components: x86
+// revisions: x86_64_wrs_vxworks
+// [x86_64_wrs_xworks]: compile-flags: --target x86_64-wrs-xworks
+// [x86_64_wrs_xworks]: needs-llvm-components: x86
+// revisions: x86_64h_apple_darwin
+// [x86_64h_apple_darwin]: compile-flags: --target x86_64h-apple-darwin
+// [x86_64h_apple_darwin]: needs-llvm-components: x86
```
Comment (Mark-Simulacrum) [inline tests/assembly/targets.rs:684]: ...Was this auto-generated? It looks like tidy is perhaps enforcing all of these lines exist, maybe we can add a --bless-ability to that?

I guess when targets are added it's fairly easy to update this list, and we remove targets relatively rarely.

**Comment by Mark-Simulacrum** [comment]
r=me

File: tests/assembly/targets.rs (hunk 1 above)
Comment (davidtwco) [reply tests/assembly/targets.rs:684]: It was vaguely auto-generated, a handful of editor macros on the output from `ls`. I don't know that we need bless-ability for this quite yet, tidy will enforce that targets are added when they're added to the compiler, and the test will fail when targets are removed because the targets are removed. Both happen infrequently enough that it should be fine.

**Comment by davidtwco** [comment]
@bors r=Mark-Simulacrum

Rebased after some new targets were added but otherwise no meaningful changes.

**Comment by davidtwco** [comment]
There have been no meaningful changes since last approval, just updating the test being added with targets that have been added recently.

@bors=wesleywiser

**Comment by davidtwco** [comment]
So the error for incompatible data layouts doesn't happen locally because of..

https://github.com/rust-lang/rust/blob/16f4b02dd8a2e16b8fb0a236399088e2cf301e63/src/bootstrap/src/core/build_steps/compile.rs#L1113-L1115

..which prevents the ICE...

https://github.com/rust-lang/rust/blob/16f4b02dd8a2e16b8fb0a236399088e2cf301e63/compiler/rustc_codegen_llvm/src/context.rs#L159-L177

cc #34960 #33446
