### PR TITLE
mark calls in the unwind path as !noinline

### LINKED ISSUE #41696: Long compilation time due to LLVM creating excessive landing pads
Long compilation time (almost infinity on real project) with every nightly versions after 2017-03-18.

I tried this:
```
git clone https://github.com/not-fl3/incremental_bug
CARGO_INCREMENTAL=1 cargo build --release
```

I expected to see this happen: 
On 2017-03-18 it compiles for less than a second (in 0.59 secs on my machine)

Instead, this happened: 

With every version newer than 2017-03-18 it compiles for 389+ seconds on my machine. 

## Meta

`rustc --version --verbose`:
```
rustc 1.19.0-nightly (06fb4d256 2017-04-30)
binary: rustc
commit-hash: 06fb4d25642a3f223db1441972dd5962085cfba1
commit-date: 2017-04-30
host: x86_64-unknown-linux-gnu
release: 1.19.0-nightly
LLVM version: 4.0
```

Also same behaviour on this versions:
```nightly-2017-03-28-x86_64-unknown-linux-gnu```
```nightly-2017-04-22-x86_64-unknown-linux-gnu```
```nightly-2017-04-30-x86_64-unknown-linux-gnu```

Backtrace:

log of -Z time-asses: https://gist.github.com/not-fl3/8c4ee411fe6c23d4b4abb9a3b6a263d0

### PR DESCRIPTION
**Pull request by arielb1**
The unwind path is always cold, so that should not have bad performance
implications.  This avoids catastrophic exponential inlining, and also
decreases the size of librustc.so by 1.5% (OTOH, the size of `libstd.so`
increased by 0.5% for some reason).

Fixes #41696.

r? @nagisa

### CODE REVIEW

**Comment by nagisa** [comment]
Any reason noinline over cold was used?

**Comment by nagisa** [comment]
Either way, can always change later if there any benefits to do so.

@bors r+

File: src/test/run-pass/issue-41696.rs [hunk 1]
```diff
@@ -10,7 +10,6 @@
 
 // this used to cause exponential code-size blowup during LLVM passes.
 // ignore-test FIXME #41696
```
Comment (kennytm) [inline src/test/run-pass/issue-41696.rs]: Should this `ignore-test` comment be removed, or is the test still failing?

**Comment by arielb1** [comment]
> Should this `ignore-test` comment be removed, or is the test still failing?

Indeed.

@bors r=nagisa

**Comment by arielb1** [comment]
> Should this `ignore-test` comment be removed, or is the test still failing?

Indeed.

@bors r=nagisa

**Comment by arielb1** [comment]
Had an accidental push

@bors r=nagisa
