### PR TITLE
Document guarantees of poisoning

### LINKED ISSUE #143471: Is mutex poisoning guaranteed to always work properly?
Is this code sound?

```rust
// Represents an abstract type with safety invariants
struct Corruptee { is_corrupted: bool }
impl Corruptee {
    // SAFETY: must be non-corrupted
    unsafe fn witness_uncorrupted(&self) {
        unsafe { core::hint::assert_unchecked(!self.is_corrupted) }
    }
    fn corrupt(&mut self) { self.is_corrupted = true; }
    fn uncorrupt(&mut self) { self.is_corrupted = false; }
}

struct Worker {
    corruptee: Mutex<Corruptee>,
}

impl Worker {
    fn do_work(&self, f: impl FnOnce()) {
        let mut corruptee = self.corruptee.lock().expect("poisoned");
        // SAFETY: `corruptee` can only be corrupted if `f` has ever panicked, but if it did, the
        // mutex would be poisoned and `expect` would panic.
        unsafe {
            corruptee.witness_uncorrupted();
        }
        corruptee.corrupt();
        f();
        corruptee.uncorrupt();
    }
}
```

I'm aware that poisoning is advisory in the sense that anyone with access to the `Mutex` can remove the poison if they wish. But in this example, `Mutex` is never revealed to users of the safe abstraction, and is only used an implementation detail.

Do we want to guarantee that poisoning can be relied upon for safety, like in this example, and never has false negatives?

I'm asking because [mutex poisoning doesn't always work](https://play.rust-lang.org/?version=stable&mode=debug&edition=2024&gist=786f08d82e8720e1bf23f688d55795d0) currently. But it's also never explicitly documented to be best-effort.

@workingjubilee 

@rustbot label +A-concurrency +C-discussion +T-libs-api

(If poisoning was considered reliable, this would be T-libs I-unsound.)

### PR DESCRIPTION
**Pull request by purplesyringa**
This mostly documents the current behavior of `Mutex` and `RwLock` (rust-lang/rust#143471) as imperfect. It's unlikely that the situation improves significantly in the future, and even if it does, the rules will probably be more complicated than "poisoning is completely reliable", so this is a conservative guarantee.

We also explicitly specify that `OnceLock` never poisons, even though it has an API similar to mutexes.

Fixes rust-lang/rust#143471 by improving documentation.

r? @Amanieu

### CODE REVIEW

File: library/std/src/sync/poison/rwlock.rs [hunk 1]
```diff
@@ -46,10 +46,10 @@ use crate::sys::sync as sys;
...
 /// # Poisoning
 ///
-/// An `RwLock`, like [`Mutex`], will become poisoned on a panic. Note, however,
-/// that an `RwLock` may only be poisoned if a panic occurs while it is locked
-/// exclusively (write mode). If a panic occurs in any reader, then the lock
-/// will not be poisoned.
+/// An `RwLock`, like [`Mutex`], will usually become poisoned on a panic. Note,
+/// however, that an `RwLock` may only be poisoned if a panic occurs while it is
+/// locked exclusively (write mode). If a panic occurs in any reader, then the
+/// lock will not be poisoned.
```
Comment (Amanieu) [inline library/std/src/sync/poison/rwlock.rs:52]: This should point to the module-level documentation to explain the "usually".

File: library/std/src/sync/poison.rs [hunk 2]
```diff
@@ -34,14 +35,15 @@
 //! - [`Mutex`]: Mutual Exclusion mechanism, which ensures that at
 //!   most one thread at a time is able to access some data.
 //!
-//!   [`Mutex::lock()`] returns a [`LockResult`],
-//!   providing a way to deal with the poisoned state.
-//!   See [`Mutex`'s documentation](Mutex#poisoning) for more.
+//!   Panicking while holding the lock typically poisons the mutex, but it is
+//!   not guaranteed to detect this condition in all circumstances.
```
Comment (Amanieu) [inline library/std/src/sync/poison.rs:39]: It would be good to clarify that poisoning is only unreliable when you have multiple pending panics or foreign exceptions. In particular it works fine in the "normal" case of a single panic.

Comment (purplesyringa) [reply library/std/src/sync/poison.rs:39]: I wasn't sure if we wanted to commit to that guarantee. Consider the following situation:

- A panic is thrown.
- A drop guard locks a mutex and stores the guard into a cell. The guard records `panicking: true`.
- The drop guard exists and the panic is caught and dropped.
- Another panic is thrown.
- Another drop guard loads the guard from the cell and drops it. Since the guard has `panicking: true` and we're currently panicking as well, the mutex is not poisoned.

Yet there's never two active panics at the same time. Only one panic has been thrown while the mutex was locked -- the other panic was only *caught*.

That's a lot of detail I don't know if I can formalize in a few words in the docs without making a mistake and guaranteeing something we can't provide.

File: library/std/src/sync/poison/rwlock.rs (hunk 1 above)
Comment (purplesyringa) [reply library/std/src/sync/poison/rwlock.rs:52]: My PR describes the pitfalls in Mutex docs, rather than module-level docs, since they are specific to Mutex/RwLock and not other poisoning locks. I'll make "usually" point to the "Poisoning" section in Mutex docs instead, if that's okay with you.

File: library/std/src/sync/poison.rs (hunk 2 above)
Comment (Amanieu) [reply library/std/src/sync/poison.rs:39]: The problem with your suggested docs is that the semantics are too vague to be of any use. Essentially we're saying that if a panic occurs while a `MutexGuard` is live then the lock may or may not be poisoned. While it's fine to not make hard guarantees, it would be nice to have a reassuring sentence along the lines of "if you're not doing fancy things like multiple live panics or preserving a `MutexGuard` across a `catch_unwind` then it will usually work as you expect".

Comment (Amanieu) [reply library/std/src/sync/poison.rs:39]: Or alternatively give *specific* examples of cases where poisoning doesn't work properly, with a note that this list isn't exhaustive. This will at least reassure people that poisoning probably works if they're not doing those things.

Comment (purplesyringa) [reply library/std/src/sync/poison.rs:39]: Makes sense, I've added a list. Does this look good?

Comment (Amanieu) [reply library/std/src/sync/poison.rs:39]: Perfect! I'd just add another bullet point about foreign exceptions and this should be good to go.

Comment (purplesyringa) [reply library/std/src/sync/poison.rs:39]: Totally forgot about that, thanks for the reminder. I added a note.

Comment (purplesyringa) [reply library/std/src/sync/poison.rs:39]: @Amanieu sorry for pinging -- could I get an r+?
