### PR TITLE
Serialize span hygiene data

### LINKED ISSUE #68686: Span hygiene data should be serialized to crate metadata
When we serialize a `Span` to crate metadata, we currently throw away the `SyntaxContext`: https://github.com/rust-lang/rust/blob/34700c15c7a49d400951da385b2eacab6fb6fe86/src/librustc_span/lib.rs#L631-L650

This is because the backing `HygieneData` is stored in a thread-local in `rustc_span`, and not serialized into crate metadata.

The result is that spans deserialized from crate metadata may have less information available than spans from the current crate. If the MIR inlining pass decides to inline a function from another crate, we may end up with suboptimal messages when we invoke `span.ctxt()` (e.g. when emitting debuginfo, and when evaluating the `caller_location` intrinsic).

It would be useful if we were to serialize `HygieneData` into crate metadata, and deserialize spans with the proper `SyntaxContext`. This will also ensure that parallel compilation works properly, since storing `HygieneData` in a thread local will cause problems if a `Span` is used on multiple threads.

I'm not really sure how best to go about doing this. `ExpnId`s are currently unique per-crate, since they are never serialized. We need some way of making `ExpnIds` globally unique.

### LINKED ISSUE #70963: regression on span for panics due to track-caller in cross-crate macros
This example has regressed (including on stable by now): ([playground](
https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=d5d1dd7fc4b97a199f8501d9cbabcfa0))
```rust
fn main() {
    std::collections::VecDeque::<String>::with_capacity(!0);
}
```
The location reported is now `<::core::macros::panic macros>:3:10` (or on nightly, `src/libcore/macros/mod.rs:34:9`).
(the choice of `VecDeque::with_capacity` is arbitrary, it just happens to have an `assert!` inside, and it will be codegen'd in the user crate because it's generic)

In general, we don't track enough information to recover the invocation site, when we have to codegen the MIR cross-crate.

A cheap hack we could do is replace the macro span with the invocation one, when serializing `Span`s inside MIR (or `Span`s in general?).

_Originally posted by @eddyb in https://github.com/rust-lang/rust/issues/47809#issuecomment-583784847_

### PR DESCRIPTION
**Pull request by Aaron1011**
Fixes #68686
Fixes #70963

This PR serializies global hygiene data into both the incremental compilation cache and the crate metadata. This allows hygiene information to be preserved across compilation sessions (both incremental and cross-crate).

When serializing a `SyntaxContext`, we simply write out the raw id from the current compilation session. Whenever we deserialize a `SyntaxContext`, we 'remap' the id to a fresh id in our current compilation session, and load the associated `SyntaxContextData`.

As a result, some 'upstream' `SyntaxContextData` will end up getting duplicated in 'downstream' crates. This only happens when we actually need to use an 'upstream' `SyntaxContext`, which occurs when we deserialize a `Span` that requires it.

We serialize an `ExpnData` into the metadata of the crate which generated it. An `ExpnId` is serialized as a reference into the crate which 'owns' the corresponding `ExpnData`, which avoids duplication in downstream crates.

I've included a macros 2.0 test which requires hygiene serialization to compile successfully.

TODO:

- [x] <strike>Determine how many additional `DefId`s we end up creating for `ExpnId`s - this may be significant for `libcore`, which uses macros heavily. Alternatively, we could try to compute a `DefPathHash` without making a corresponding `DefId` - however, this might significantly complicate the implementation.</strike> (We no longer create `DefId`s)
- [x] Investigate the overhead of duplicating `SyntaxContextData` in crate metadata.
- [x] Investigate how `resolve_crate_root` behaves with deserialized hygiene data - the current logic may be wrong.
- [x] Add additional tests. The effects of this PR are usually only noticeable when working with headache-inducing macro expansions (e.g. macros expanding to macros), so there are lots of corner cases to test.
- [x] Determine what to do about this:

https://github.com/rust-lang/rust/blob/4774f9b523c942cb5c0236542b5bcac76f6b6b9a/src/librustc_resolve/build_reduced_graph.rs#L892

- [x] Determine if we need to do anything here - I think the fact that `src/test/ui/hygiene/cross_crate_hygiene.rs` passes means that this is working.

https://github.com/rust-lang/rust/blob/3d5d0f898c2f3998e50c2180c6202f193c3acdbc/src/librustc_resolve/imports.rs#L1389-L1392

### CODE REVIEW

**Comment by Aaron1011** [comment]
Let's see if there are any obvious performance issues with this approach:

@bors try @rust-timer queue

**Comment by Aaron1011** [comment]
This is going to require more work to reduce the performance impact. It may be necessary to re-visit assigning `DefId`s to each `ExpnId`.

**Comment by petrochenkov** [comment]
I did a first pass, some thoughts:
- This works as a proof of concept and I think we can proceed with the approach.
- Question 1: Where is the slowdown coming from? Is it localized? Is it possible to hide it under a `-Z` option and proceed with optimization after the merge?
- Question 2: How to split this PR into multiple parts? The PR is too large to review carefully. (Some parts like `DefId` -> `LocalDefId` and removal of `macro_defs` certainly look orthogonal, it would be great to split any preparatory refactorings as well.)
- Nit: it would be nice to run rustfmt on each commit instead of having separate formatting commits.

**Comment by Aaron1011** [comment]
This is blocked on reaching a decision on https://github.com/rust-lang/rust/pull/72284

**Comment by Aaron1011** [comment]
@petrochenkov: I'm starting to wonder how much benefit we're getting from assigning a `DefId` to each `ExpnId`. If I understand correctly, the idea is to ensure that non-structural changes (e.g. moving a function around in a file) don't necessarily invalidate an `ExpnData`. As long as the parent item (e.g. a function) and the `ExpnData`'s position within the function is unchanged, the `DefId` will be too.

However, I'm not sure if there's any realistic scenario where this stability allows us to skip invalidating anything. `ExpnData` is only exposed through `SyntaxContextData`, which in turn is only exposed by a `Span`. In order for an `ExpnData`'s `DefID` to be an improvement over a raw id, there would need to be a case where a `Span's` `HashStable` hash is only changed due to an `ExpnId` changing. However, any modification that would affect `ExpnId`s is almost certainly going to affect the containing `Span`. Moving a function around in a file, changing the order of macro invocations, or adding a new macro invocation will all cause some `Spans` to change their position (if only because of the `call_site` span).

The only case I can think of where this *wouldn't* happen is where a proc-macro is deliberately overwriting the `Span`s to keep them unchanged in the face of modifications made by the user. However, we would still be left with the issue of the `call_site` span, which is necessarily going to be extremely sensitive to any changes involving the macro invocation.

Instead, I think we might want to store an `Option<(CrateNum, u32)>` in `ExpnData`, which tracks the original crate and `ExpnId` that an `ExpnData` was deserialized from. We would then serialize all `ExpnId`s as `(CrateNum, u32)`, using `(LOCAL_CRATE, expn_id.as_u32())` for `ExpnIds` created during the compilation session. This would allow us to avoid duplicating the underlying `ExpnData` when serializing a foreign `ExpnId`, since it can be looked up from its owning crate. A similar scheme could be used for `SyntaxContext`/`SyntaxContextData` to further reduce duplication.

This would cut the additional work done during expansion to zero, since we no longer need to create `DefId`s for each `ExpnId` we encounter. This should help with several of the performance regressions, since many are due `expand_crate` taking longer.

**Comment by petrochenkov** [comment]
So, the slowdown from creating `DefId`s represents a significant portion of the slowdown from this PR, but mostly happens on `incr-unchanged` benchmarks and on tiny crates, larger crates like servo are unaffected.

**Comment by petrochenkov** [comment]
The obvious suggestion is to create def paths lazily only when we actually need to encode an `ExpnId` into metadata.

@Aaron1011 
I'm pretty sure we will need a stable encoding like def paths for `ExpnId` sooner or later.
Other problems with spans exist, but that only means that they also need to be solved to produce incremental compilation that works well.

Many variants were suggested - making locations in spans item-relative, splitting hygiene from locations (because the former is needed always and the latter only when we report errors, modulo debuginfo which will probably need some special treatment), moving spans into side tables like https://github.com/rust-lang/rust/pull/72015 does, etc.

I don't actually have anything against serializing hygiene data in incremental-unfriendly way, if it helps to split this large work into multiple smaller parts and if we'll be able to migrate to an incremental-friendly scheme later.

**Comment by Mark-Simulacrum** [comment]
@rust-timer build 7aa151655fe006fb8905d58190233e69dbd0da82

**Comment by Aaron1011** [comment]
@rust-timer build 4ed6e362cfe703b3b5930bf219ad1532c2d47d54

**Comment by Mark-Simulacrum** [comment]
@rust-timer build 4ed6e362cfe703b3b5930bf219ad1532c2d47d54

**Comment by Aaron1011** [comment]
@rust-timer build ad57ba5a7491ef83fd080f05c0ba99208f928a72

**Comment by Aaron1011** [comment]
@rust-timer build ad57ba5a7491ef83fd080f05c0ba99208f928a72

**Comment by kennytm** [comment]
@rust-timer build ad57ba5a7491ef83fd080f05c0ba99208f928a72

**Comment by Mark-Simulacrum** [comment]
@rust-timer build ad57ba5a7491ef83fd080f05c0ba99208f928a72

**Comment by Aaron1011** [comment]
This is an improvement over the last commit, but we still have regressions of up to `4.4%`. I think some amount of regression is inevitable, since we need to hash things (serialized/deserialized `SyntaxContextData` and `ExpnData`) that we previously weren't. I'll see if I can improve the performance any more.

**Comment by petrochenkov** [comment]
Looks like more or less acceptable range for the slowdown, given that we outright didn't do the necessary work previously.

The question from https://github.com/rust-lang/rust/pull/72121#issuecomment-629663433 still holds though - where are the main sources of the slowdown in code?

(I also need to re-review this because I have no idea what this PR does now when it's rewritten.)

**Comment by mati865** [comment]
Worth noting most slowdowns are most noticeable for check. Debug and opt builds do codegen and because of that the slowdown is small compared to the overall build.

I looked at a few cases, the slowdown often seems to be coming from: `metadata_register_crate`, `metadata_decode_entry`, `generate_crate_metadata` and `expand_crate`.

**Comment by petrochenkov** [comment]
@Aaron1011 
Do you plan to make any significant changes to this PR?
I want to run it through crater before landing.

@bors try

**Comment by Aaron1011** [comment]
@petrochenkov: I don't plan on making any major changes - this should be ready for a Crater run.

**Comment by petrochenkov** [comment]
@craterbot check

**Comment by petrochenkov** [comment]
Crater is broken?
cc @pietroalbini

**Comment by Aaron1011** [comment]
Yeah, I have no idea how a run could take only 13 hours

**Comment by Aaron1011** [comment]
There are tens of thousands of 'error' jobs with output like this:

```
[INFO] updating cached repository https://github.com/22shubh22/Pong-Tetra
[INFO] running `"git" "-c" "credential.helper=" "-c" "credential.helper=/workspace/cargo-home/bin/git-credential-null" "-c" "remote.origin.fetch=refs/heads/*:refs/heads/*" "fetch" "origin" "--force" "--prune"`
[INFO] running `"git" "rev-parse" "HEAD"`
[INFO] [stdout] 9c1f82f9108b4f78cddbf2856866c4b17a5f3bcd
[ERROR] this task or one of its parent failed!
[ERROR] command `"/workspace/cargo-home/bin/cargo" "+a37c32e2d5fb186627ffe99a391c7fd6fd159334" "fetch" "--locked" "--manifest-path" "Cargo.toml"` failed
[ERROR] note: run with `RUST_BACKTRACE=1` to display a backtrace.
```

Maybe there was a network issue or Github outage during the run?

**Comment by pietroalbini** [comment]
Pretty sure this was caused by https://github.com/rust-lang/cargo/issues/8351, as the try build was done after the regression landed but before the fix was merged. I recommend doing a fresh try build before starting Crater again.

**Comment by Aaron1011** [comment]
@craterbot check

**Comment by Aaron1011** [comment]
I've minimized the `solana-genesis-programs` regression in https://github.com/Aaron1011/cross-dollar-crate:

```rust
// def-crate/src/lib.rs

#[macro_export]
macro_rules! define_macro {
    () => {
        #[macro_export]
        macro_rules! constructed_macro {
            () => {
                $crate::IN_DEF_CRATE;
            }
        }
    }
}

// src/lib.rs
pub const IN_DEF_CRATE: &str = "In library crate!";

def_crate::define_macro!();

// src/main.rs
fn main() {
    cross_dollar_crate::constructed_macro!();
}
```

This compiles on the latest nightly, but errors with the branch.
When we expand `define_macro`, we mark all of the tokens in the attribute with `Transparency::SemiTransparent` - including all of the tokens in `            () => {
                $crate::IN_DEF_CRATE;
            }
`.

Previously, these marks would have been lost when we serialized the crate for `src/lib.rs`. However, we now retain the `Transparency::SemiTransparent` (and associated definition site in `def-crate`) when we call `constructed_macro` in `src/main.rs`. This causes us to fail to resolve `$crate::IN_DEF_CRATE`, since we resolve it in the context of `def-crate/src/lib.rs`, not `src/main.rs`

This behavior seems somewhat surprising to me. The Rust Reference would seem to suggest that this code should compile (https://doc.rust-lang.org/nightly/reference/macros-by-example.html#hygiene):

> By default, all identifiers referred to in a macro are expanded as-is, and are looked up at the macro's invocation site. This can lead to issues if a macro refers to an item or macro which isn't in scope at the invocation site. To alleviate this, the $crate metavariable can be used at the start of a path to force lookup to occur inside the crate defining the macro.

I think 'inside the crate defining the macro' is wrong - it should be "the crate which produced the $crate" token. In fact, using `constructed_macro` within `src/lib.rs` will fail to compile on nightly, since we will have the proper hygiene information available.

**Comment by Aaron1011** [comment]
`xtp` and `the-rust-programming-language-2nd-edition` were both spurious failures, so `solana-genesis-programs` is the only regression.

**Comment by petrochenkov** [comment]
The new behavior of `solana-genesis-programs` is correct, or at least consistent with other nested uses of `$crate`, i.e. the `$crate` should ultimately point to `def-crate/src/lib.rs` ("transitive def-site").

I encountered this case in the past and changing this caused breakage, see https://github.com/rust-lang/rust/commit/b69d51162b5391119e86d1c6e884aa09292a7806.

**Comment by petrochenkov** [comment]
r=me after rebase.
This could use some cleanup, but it's more important to have it landed.

Could you also
- update the PR description to the current state of the PR
- make an issue for the main optimization that needs to be done here - encoding data only for expansion and syntax context IDs that were previously used during encoding of everything else.

**Comment by Aaron1011** [comment]
Patching `solana-genesis-programs` in a backwards-compatible way will be quite tricky without https://github.com/rust-lang/rust/pull/73569, so I think it would be best to block this PR on https://github.com/rust-lang/rust/pull/73569.

**Comment by petrochenkov** [comment]
@Aaron1011 
I'm not sure what you wanted to do with `solana-genesis-programs` before merging this, but https://github.com/rust-lang/rust/pull/73569 has landed.

**Comment by Aaron1011** [comment]
@petrochenkov: I opened https://github.com/solana-labs/solana/pull/10905 to fix `solana-genesis-programs`

**Comment by Aaron1011** [comment]
@petrochenkov: I made some additional changes to how this PR handles serialization in incr-cmp vs crate-metadata: see the most recent commits.

**Comment by petrochenkov** [comment]
I asked WG-incremental to review the `on_disk_cache.rs` part.
https://rust-lang.zulipchat.com/#narrow/stream/241847-t-compiler.2Fwg-incr-comp/topic/Reviewing.20.22Serialize.20span.20hygiene.20data.22/near/202864449
r? @spastorino

**Comment by petrochenkov** [comment]
My my concern is about things like `ExpnDataEncodeMode::IncrComp => expn.0.encode(e)`.

The `u32` value of `ExpnId` (and `SyntaxContext` as well) should never be used for stable hashing, because the same index may mean entirely different expansions in two separate compilations.
I don't know, however, in which places in the compiler stable hashing is supposed to be used and in which not.

**Comment by Aaron1011** [comment]
> My my concern is about things like ExpnDataEncodeMode::IncrComp => expn.0.encode(e).

This is only when writing out the serialized incremental cache data. These raw ids get used for lookup purposes when decoding a serialize `SyntaxContextData`, but I'm careful to only ever create an `ExpnId` with a raw `u32` that is valid in the *current* session. See `decode_expn_id` for how we 'remap' old ids to fresh ids in the current session.

File: src/librustc_span/hygiene.rs [hunk 1]
```diff
@@ -848,14 +880,234 @@ impl DesugaringKind {
...
+    // Do this after decoding, so that we decode a `CrateNum`
+    // if necessary
+    if index == ExpnId::root().as_u32() {
+        debug!("decode_expn_id: deserialized root");
+        return Ok(ExpnId::root());
+    }
+
+    let outer_expns = &context.remapped_expns;
+
+    // Ensure that the lock() temporary is dropped early
```
Comment (pnkfelix) [inline src/librustc_span/hygiene.rs:935]: I believe these braces you have added here have no effect.

The current r-value lifetime rules will cause the lock() temporary to be dropped at the end of the evaluation of the expression; we do not extend it to the end of the containing block (which in this case would be the `fn` body of `decode_expn_id` itself).

(The place where you *do* need such braces is when you `let`-bind the value, as you do below with `let mut expns = outer_expns.lock();`.)

----

I would say that if your goal is to make the dynamic extent of the `lock()` temporary as clear as possible to future readers of this code, then I would keep the braces but I would also add a let-binding of the temporary, so that the braces are meaningful.

Comment (pnkfelix) [reply src/librustc_span/hygiene.rs:935]: Oh, here is a [playground demo](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=d94962ae31ffe9dbe414251177b31ef9) illustrating what I mean when I say that these braces have no effect.

(The demo also points out a potentially surprising difference in the semantics of `if` vs `if let` in terms of what the r-value lifetime rules yield, but that is just a side-note; it does not contradict my main point that these braces have no effect.)

Comment (Aaron1011) [reply src/librustc_span/hygiene.rs:935]: > I would say that if your goal is to make the dynamic extent of the lock() temporary as clear as possible to future readers of this code, then I would keep the braces

That was my intention - I didn't want anyone reading the code to need to be aware of the exact rules for when temporaries are dropped.

> I would also add a let-binding of the temporary, so that the braces are meaningful.

I think the code looks cleaner as written - the important things is that the lock is dropped before calling `decode_data`, which the brackets make visually clear.

**Comment by Aaron1011** [comment]
Now that https://github.com/solana-labs/solana/pull/10905 has been merged, all of the Crater regressions should be fixed!

File: src/librustc_span/hygiene.rs (hunk 1 above)
Comment (pnkfelix) [reply src/librustc_span/hygiene.rs:934]: I still think that if you want to make things explicit with braces,, then it should be braces that have an effect.

Putting braces in like this may lead people reading the code to think erroneously that these braces are *necessary* to encode the dynamic extent you desire here. I would prefer to avoid fueling such misunderstanding.

But given that the project does not have official guidance as to coding style in cases like this, I will not block landing the PR based on this disagreement.

**Comment by pnkfelix** [comment]
At this point I don't have any useful feedback on the approach used for handling the expn-id's.

(I have a suspicion that this pattern occurs elsewhere in the compiler, in other spots where we need to remap data that has been serialized in some fashion to the local executing context, but I wasn't able to find a proper match with a quick search, so I'm leaving that as a random musing for now.)

I think I understand @petrochenkov 's concern about stable-hashing, except for one detail: I don't think that `ExpnId` even implements `HashStable` ... ; `SyntaxContext` does implement it, yes, but I think that implementation is careful to avoid the problem @petrochenkov describes.
 * Am I wrong here? Does `ExpnId` indirectly implement `HashStable` somehow?

**Comment by pnkfelix** [comment]
anyway I think I'd be okay with r+'ing this PR, once its in a building state according to the CI.

I would definitely want to avoid including it in a rollup, though.

@bors rollup=never

**Comment by Aaron1011** [comment]
Let's try to avoid invaliding *every* `Span`:

@bors try @rust-timer queue

**Comment by Aaron1011** [comment]
The 214% regression was actually caused by a bug in how I was deserializing from the incremental cache. This caused the wrong hygiene information to be loaded under certain circumstances, which caused a MIR body fingerprint to change.

**Comment by Aaron1011** [comment]
There's still some perf impact, but it's now much smaller.

File: src/librustc_span/hygiene.rs [hunk 2]
```diff
@@ -711,9 +711,16 @@ pub struct ExpnData {
...
     /// An `ExpnData` can be created before being assigned an `ExpnId`,
     /// so this might be `None` until `set_expn_data` is called
+    // This is used only for serialization/deserialization purposes:
+    // two `ExpnData`s that differ only in their `orig_id` should
+    // be considered equivalent.
+    #[stable_hasher(ignore)]
     pub orig_id: Option<u32>,
 }
 
+// This would require special handling of `orig_id` and `parent`
```
Comment (petrochenkov) [inline src/librustc_span/hygiene.rs:721]: `parent` probably shouldn't be ignored, it was ignored just because we couldn't stable-hash an `ExpnId` previously.
(This can be done in a separate PR with a separate perf measurement.)

File: src/librustc_span/hygiene.rs [hunk 3]
```diff
@@ -889,32 +890,91 @@ impl DesugaringKind {
...
+            let latest_ctxts = self.latest_ctxts.take();
+
+            // It's fine to iterate over a HashMap, because thw serialization
+            // of the table that we insert data into doesn't depend on insertion
+            // order
+            for_all_ctxts_in(latest_ctxts.into_iter(), |(index, ctxt, data)| {
+                if self.serialized_ctxts.borrow_mut().insert(ctxt) {
+                    encode_ctxt(encoder, index, data)?;
+                    //syntax_contexts.set(index, self.lazy(data));
+                    //num_serialized += 1;
```
Comment (petrochenkov) [inline src/librustc_span/hygiene.rs:941]: Commented out code can be removed.

**Comment by petrochenkov** [comment]
r=me
It would be great to squash commits to cleanup history before merging (no fmt commits, no `Lock` -> `RefCell` -> `Lock` back and forth).

File: src/librustc_span/hygiene.rs [hunk 4]
```diff
@@ -847,14 +886,320 @@ impl DesugaringKind {
...
+                "encode_hygiene: Serializing a round of {:?} SyntaxContextDatas: {:?}",
+                self.latest_ctxts.lock().len(),
+                self.latest_ctxts
+            );
+
+            // Consume the current round of SyntaxContexts.
+            // Drop the lock() temporary early
+            let latest_ctxts = { std::mem::take(&mut *self.latest_ctxts.lock()) };
+
+            // It's fine to iterate over a HashMap, because thw serialization
```
Comment (bjorn3) [inline src/librustc_span/hygiene.rs:934]: *the

**Comment by Aaron1011** [comment]
@petrochenkov: I've squashed the changes into more meaningful commits.

**Comment by petrochenkov** [comment]
Thanks!
@bors r+

cc @nnethercote, this is a planned perf regression

**Comment by petrochenkov** [comment]
Missing `// no-prefer-dynamic` in `make-macro.rs` maybe?

**Comment by Aaron1011** [comment]
I had an unnecessary `extern crate` staement.

@bors r=petrochenkov

**Comment by Aaron1011** [comment]
@petrochenkov: It looks like the output of several existing tests (e.g. `src/test/ui/proc-macro/dollar-crate.rs`) is now dependent on the libstd target platform, probably due to target-specific cfgs causing different macros to be expanded. This affects the raw SyntaxContexts ids shown when we debug-print spans, as well as the output of `-Z unpretty=expanded,hygiene`

**Comment by Aaron1011** [comment]
@petrochenkov: I think there are two options here:

1. Use `normalize-stdout-test` to strip out the raw SyntaxContext numbers, and avoid using `-Zunpretty=expanded,hygiene` in any test that depends on `libcore`
2. Limit the relevant tests to one platform, and keep the `SyntaxContext` ids and `-Zunpretty=expanded,hygiene` data in the outout.

I think that the first option is better for now. However, I'll open an issue to track coming up with a better way to handle this.

**Comment by Aaron1011** [comment]
I've opened https://github.com/rust-lang/rust/issues/74800 to track improvements to the way we normalize the test output.

@bors r=petrochenkov

**Comment by Mark-Simulacrum** [comment]
@Aaron1011 Could you update the pull request description as well? It looks inconsistent with the current state and since bors will include it in the final merge commit would be good to get that updated.

**Comment by Aaron1011** [comment]
@Mark-Simulacrum Updated.

**Comment by Dylan-DPC** [comment]
yielding to other pr to avoid conflicts 

@bors retry

**Comment by Aaron1011** [comment]
@Dylan-DPC: I think this PR and https://github.com/rust-lang/rust/pull/73265 shouldn't conflict.

**Comment by Dylan-DPC** [comment]
I think so as well but it's more as a precatuionary measure. that pr has been trying to get merged for a while now so don't want to add more latency.

**Comment by nnethercote** [comment]
This was a [perf loss](https://perf.rust-lang.org/compare.html?start=c70986264b4d534e35992fc64ecd9139700b5071&end=fa36f960687c41caf5b260ab7610ebd83a7860dd&stat=instructions:u), as expected.
