### PR TITLE
Regression test for rust-lang/rust#53675.

### LINKED ISSUE #53675: Macro resolution regression when a #[test] is named 'panic'
Test case:

```rust
#[test]
fn panic() {
    assert!(true)
}
```

```rust
$ rustc +nightly -V
rustc 1.30.0-nightly (63d66494a 2018-08-23)
$ cargo +nightly test
error: cannot determine resolution for the macro `panic`
 --> src/lib.rs:3:5
  |
3 |     assert!(true)
  |     ^^^^^^^^^^^^^
  |
  = note: import resolution is stuck, try simplifying macro imports

error: aborting due to previous error

error: Could not compile `foo`.
```

CC @petrochenkov

### PR DESCRIPTION
**Pull request by pnkfelix**
(Includes a couple variations on the theme. I confirmed that the ones
in `in_expression_position` and `what_if_we_use_panic_directly_in_expr`
both failed back on "rustc 1.30.0-nightly (0f063aef6 2018-09-03)".)

Fix #53675

### CODE REVIEW

File: src/test/ui/issues/issue-53675-a-test-called-panic.rs [hunk 1]
```diff
@@ -0,0 +1,35 @@
+// rust-lang/rust#53675: At one point the compiler errored when a test
+// named `panic` used the `assert!` macro in expression position.
+
+// compile-flags: --test
```
Comment (petrochenkov) [inline src/test/ui/issues/issue-53675-a-test-called-panic.rs]: Missing `compile-pass`.

**Comment by petrochenkov** [comment]
r=me rollup with `compile-pass` added

File: src/test/ui/issues/issue-53675-a-test-called-panic.rs (hunk 1 above)
Comment (pnkfelix) [reply src/test/ui/issues/issue-53675-a-test-called-panic.rs]: Face palm. Will fix.

Comment (pnkfelix) [reply src/test/ui/issues/issue-53675-a-test-called-panic.rs]: (Well, I did make it work as a run-pass test I think. But I don’t mind it being compile-pass.)
