### PR TITLE
Fix control flow check for breaking with diverging values

### LINKED ISSUE #77156: rustc does not recognize a return inside a break expression for purposes of checking that every code path has the function return type
I tried this code:

```rust
fn test() -> i32 {
    let loop_value = loop { break (return 5); };
}
fn main() {
    println!("{}", test());
}
```

I expected that this would compile. Instead rustc says (on 1.48.0 nightly 2020-09-23):
```
error[E0308]: mismatched types
 --> src/main.rs:1:14
  |
1 | fn test() -> i32 {
  |    ----      ^^^ expected `i32`, found `()`
  |    |
  |    implicitly returns `()` as its body has no tail or `return` expression
```

As a sanity check, I also tested this:

```rust
fn test() -> i32 {
    let loop_value = loop { break (return 5); };
    return 0;
}
fn main() {
    println!("{}", test());
}
```

This compiles and when run prints `5`, indicating that that expression is indeed the place the function returns. Looking at the function it's also clearly an unconditionally reached return. Compare

```rust
fn test() -> i32 {
    let loop_value = loop { return 5; };
}
fn main() {
    println!("{}", test());
}
```

which also compiles and runs without error.

On the same theme, I was worried that this might erroneously typecheck:
```rust
fn test() -> i32 {
    let loop_value = loop { break (return Some(5)); };
    return 0;
}
fn main() {
    println!("{}", test());
}
```
but it doesn't, indicating the compiler is quite cognizant that the value returned in this position has to unify with the return type.

### PR DESCRIPTION
**Pull request by varkor**
Fixes https://github.com/rust-lang/rust/issues/77156.

### CODE REVIEW

**Comment by varkor** [comment]
This is slightly more subtle than I hoped; I'll fix the issue tomorrow.

**Comment by varkor** [comment]
This is now ready to review.

**Comment by lcnr** [comment]
LGTM

don't have much experience with this part of the code though, so r? @eddyb for a final review/approval

File: compiler/rustc_typeck/src/check/expr.rs [hunk 1]
```diff
@@ -626,7 +626,10 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
                 assert!(expr_opt.is_none() || self.tcx.sess.has_errors());
             }
 
-            ctxt.may_break = true;
+            // If we encountered a `break`, then (no surprise) it may be possible to break from the
+            // loop... unless the value being returned from the loop diverges itself, e.g.
+            // `break return 5` or `break loop {}`.
+            ctxt.may_break |= !e_ty.is_never();
```
Comment (eddyb) [inline compiler/rustc_typeck/src/check/expr.rs:632]: Is `is_never()` correct? I would've expected something more general.

Comment (eddyb) [reply compiler/rustc_typeck/src/check/expr.rs:632]: Like `self.diverges` (was looking for it).

Comment (varkor) [reply compiler/rustc_typeck/src/check/expr.rs:632]: My understanding is that the value of the break expression (i.e. the `x` in `break x`) will always have type `!` if it is known to diverge (in which case we'll never exit the loop). If we break somewhere inside `x`, then `may_break` will be set to `true` already by the subexpression. In there's a case you can think of that for which this might not hold, I can add another test?

Comment (nikomatsakis) [reply compiler/rustc_typeck/src/check/expr.rs:632]: I guess one example might be something like `break { return; () }`?

Comment (nikomatsakis) [reply compiler/rustc_typeck/src/check/expr.rs:632]: Another question would be something like

```rust
enum Void { }
fn foo() -> Void { panic!() }
break foo()
```

(To be honest, I'm not entirely sure what behavior I expect in *that* case.)

Comment (varkor) [reply compiler/rustc_typeck/src/check/expr.rs:633]: @nikomatsakis: I've added those examples, and also an analogous test with `!`, which behave how I would expect (i.e. return `Void` does not work, but returning `!` does).

File: src/test/ui/break-diverging-value.rs [hunk 2]
```diff
@@ -0,0 +1,38 @@
...
+fn loop_break_loop() -> i32 {
+    let loop_value = loop { break loop {} }; // ok
+}
+
+fn loop_break_break() -> i32 { //~ ERROR mismatched types
+    let loop_value = loop { break break };
+}
+
+fn loop_break_return_2() -> i32 { //~ ERROR mismatched types
+    let loop_value = loop { break { return; () } };
```
Comment (nikomatsakis) [inline src/test/ui/break-diverging-value.rs:16]: Can you change this to `break { return 0; () }`?

I think in this case I expect `// ok`, same as `break return 0`, do you agree?

**Review by nikomatsakis — CHANGES_REQUESTED** [review]

File: src/test/ui/break-diverging-value.rs (hunk 2 above)
Comment (varkor) [reply src/test/ui/break-diverging-value.rs:16]: I agree. However, apparently `break { return 0 }` (and your example) behave differently than `break return 0`, so I shall have to investigate.

Comment (nikomatsakis) [reply src/test/ui/break-diverging-value.rs:16]: I believe this is because of the point that @eddyb raised earlier.

File: compiler/rustc_typeck/src/check/expr.rs (hunk 1 above)
Comment (nikomatsakis) [reply compiler/rustc_typeck/src/check/expr.rs:633]:
```suggestion
            ctxt.may_break |= !self.diverges.is_always();
```
I think this is the change that @eddyb was proposing and I suspect it will fix the `break { return 0; () }` example.

File: src/test/ui/break-diverging-value.rs (hunk 2 above)
Comment (nikomatsakis) [reply src/test/ui/break-diverging-value.rs:16]: See [this comment](https://github.com/rust-lang/rust/pull/77317/files#r510467463)

Comment (varkor) [reply src/test/ui/break-diverging-value.rs]: That did fix it, thanks both. I added the test and it's working as expected now.
