### PR TITLE
lint: emit proper diagnostic for unsafe binders in improper_ctypes instead of ICE

### LINKED ISSUE #149719: ICE: improper ctypes: extern unsafe binders
code:
````rust
#![feature(unsafe_binders)]
unsafe extern {
    fn exit_2(_x: unsafe<'a> &'a ()) ;

}
fn main() {}

````

Version information
````
rustc 1.94.0-nightly (fbab541a7 2025-12-06)
binary: rustc
commit-hash: fbab541a7ad1c22fc51783d03c7d75fa577f5633
commit-date: 2025-12-06
host: x86_64-unknown-linux-gnu
release: 1.94.0-nightly
LLVM version: 21.1.5

````

Possibly related line of code:
https://github.com/rust-lang/rust/blob/fbab541a7ad1c22fc51783d03c7d75fa577f5633/compiler/rustc_lint/src/types/improper_ctypes.rs#L666-L678

Command:
`/home/matthias/.rustup/toolchains/master/bin/rustc `

<details><summary><strong>Program output</strong></summary>
<p>

```
warning: the feature `unsafe_binders` is incomplete and may not be safe to use and/or cause compiler crashes
 --> /tmp/icemaker_global_tempdir.tKW9U9H846f8/rustc_testrunner_tmpdir_reporting.MKyXcvUuo4CJ/mvce.rs:1:12
  |
1 | #![feature(unsafe_binders)]
  |            ^^^^^^^^^^^^^^
  |
  = note: see issue #130516 <https://github.com/rust-lang/rust/issues/130516> for more information
  = note: `#[warn(incomplete_features)]` on by default

warning: function `exit_2` is never used
 --> /tmp/icemaker_global_tempdir.tKW9U9H846f8/rustc_testrunner_tmpdir_reporting.MKyXcvUuo4CJ/mvce.rs:3:8
  |
3 |     fn exit_2(_x: unsafe<'a> &'a ());
  |        ^^^^^^
  |
  = note: `#[warn(dead_code)]` (part of `#[warn(unused)]`) on by default


thread 'rustc' (1663257) panicked at compiler/rustc_lint/src/types/improper_ctypes.rs:672:36:
not yet implemented: FIXME(unsafe_binder)
stack backtrace:
   0:     0x7faa1c684f63 - <<std[30d1384522680fe8]::sys::backtrace::BacktraceLock>::print::DisplayBacktrace as core[21868c0c5a10a1a4]::fmt::Display>::fmt
   1:     0x7faa1ce106c8 - core[21868c0c5a10a1a4]::fmt::write
   2:     0x7faa1c69b686 - <std[30d1384522680fe8]::sys::stdio::unix::Stderr as std[30d1384522680fe8]::io::Write>::write_fmt
   3:     0x7faa1c65b728 - std[30d1384522680fe8]::panicking::default_hook::{closure#0}
   4:     0x7faa1c678e33 - std[30d1384522680fe8]::panicking::default_hook
   5:     0x7faa1b6d70e7 - std[30d1384522680fe8]::panicking::update_hook::<alloc[fe25149d2e0f3b49]::boxed::Box<rustc_driver_impl[ee712ad3fe927a50]::install_ice_hook::{closure#1}>>::{closure#0}
   6:     0x7faa1c679112 - std[30d1384522680fe8]::panicking::panic_with_hook
   7:     0x7faa1c65b81a - std[30d1384522680fe8]::panicking::panic_handler::{closure#0}
   8:     0x7faa1c6528a9 - std[30d1384522680fe8]::sys::backtrace::__rust_end_short_backtrace::<std[30d1384522680fe8]::panicking::panic_handler::{closure#0}, !>
   9:     0x7faa1c65d39d - __rustc[4a386ae28c721ec5]::rust_begin_unwind
  10:     0x7faa19b3c42c - core[21868c0c5a10a1a4]::panicking::panic_fmt
  11:     0x7faa1e8833f5 - <rustc_lint[a598aad53486b051]::types::improper_ctypes::ImproperCTypesVisitor>::visit_type.cold
  12:     0x7faa1d287fb6 - <rustc_lint[a598aad53486b051]::types::improper_ctypes::ImproperCTypesVisitor>::check_type
  13:     0x7faa1d287c4c - <rustc_lint[a598aad53486b051]::types::improper_ctypes::ImproperCTypesLint>::check_foreign_fn
  14:     0x7faa1d41787f - <rustc_lint[a598aad53486b051]::late::LateContextAndPass<rustc_lint[a598aad53486b051]::BuiltinCombinedModuleLateLintPass> as rustc_hir[91393a13b1bdc727]::intravisit::Visitor>::visit_nested_item
  15:     0x7faa1d4154cc - rustc_lint[a598aad53486b051]::lint_mod
  16:     0x7faa1d415089 - rustc_query_impl[6539629e9b074ede]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[6539629e9b074ede]::query_impl::lint_mod::dynamic_query::{closure#2}::{closure#0}, rustc_middle[46cb312bf8ccc4ab]::query::erase::Erased<[u8; 0usize]>>
  17:     0x7faa1dbb06f1 - rustc_query_system[98fd9767c01187d]::query::plumbing::try_execute_query::<rustc_query_impl[6539629e9b074ede]::DynamicConfig<rustc_query_system[98fd9767c01187d]::query::caches::DefaultCache<rustc_span[2b8dbcee9da39f6c]::def_id::LocalModDefId, rustc_middle[46cb312bf8ccc4ab]::query::erase::Erased<[u8; 0usize]>>, false, false, false>, rustc_query_impl[6539629e9b074ede]::plumbing::QueryCtxt, false>
  18:     0x7faa1dbac5bd - rustc_query_impl[6539629e9b074ede]::query_impl::lint_mod::get_query_non_incr::__rust_end_short_backtrace
  19:     0x7faa1dbac150 - rustc_lint[a598aad53486b051]::late::check_crate::{closure#1}
  20:     0x7faa1dbabd3a - rustc_lint[a598aad53486b051]::late::check_crate
  21:     0x7faa1d070748 - rustc_interface[abf69827c14388d7]::passes::analysis
  22:     0x7faa1d06fedb - rustc_query_impl[6539629e9b074ede]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[6539629e9b074ede]::query_impl::analysis::dynamic_query::{closure#2}::{closure#0}, rustc_middle[46cb312bf8ccc4ab]::query::erase::Erased<[u8; 0usize]>>
  23:     0x7faa1df5ab20 - rustc_query_system[98fd9767c01187d]::query::plumbing::try_execute_query::<rustc_query_impl[6539629e9b074ede]::DynamicConfig<rustc_query_system[98fd9767c01187d]::query::caches::SingleCache<rustc_middle[46cb312bf8ccc4ab]::query::erase::Erased<[u8; 0usize]>>, false, false, false>, rustc_query_impl[6539629e9b074ede]::plumbing::QueryCtxt, false>
  24:     0x7faa1df5a776 - rustc_query_impl[6539629e9b074ede]::query_impl::analysis::get_query_non_incr::__rust_end_short_backtrace
  25:     0x7faa1e14c750 - <rustc_interface[abf69827c14388d7]::passes::create_and_enter_global_ctxt<core[21868c0c5a10a1a4]::option::Option<rustc_interface[abf69827c14388d7]::queries::Linker>, rustc_driver_impl[ee712ad3fe927a50]::run_compiler::{closure#0}::{closure#2}>::{closure#2} as core[21868c0c5a10a1a4]::ops::function::FnOnce<(&rustc_session[cbac929be9e0488c]::session::Session, rustc_middle[46cb312bf8ccc4ab]::ty::context::CurrentGcx, alloc[fe25149d2e0f3b49]::sync::Arc<rustc_data_structures[bd3d9d7ab9b00a56]::jobserver::Proxy>, &std[30d1384522680fe8]::sync::once_lock::OnceLock<rustc_middle[46cb312bf8ccc4ab]::ty::context::GlobalCtxt>, &rustc_data_structures[bd3d9d7ab9b00a56]::sync::worker_local::WorkerLocal<rustc_middle[46cb312bf8ccc4ab]::arena::Arena>, &rustc_data_structures[bd3d9d7ab9b00a56]::sync::worker_local::WorkerLocal<rustc_hir[91393a13b1bdc727]::Arena>, rustc_driver_impl[ee712ad3fe927a50]::run_compiler::{closure#0}::{closure#2})>>::call_once::{shim:vtable#0}
  26:     0x7faa1df94405 - rustc_interface[abf69827c14388d7]::interface::run_compiler::<(), rustc_driver_impl[ee712ad3fe927a50]::run_compiler::{closure#0}>::{closure#1}
  27:     0x7faa1df10916 - std[30d1384522680fe8]::sys::backtrace::__rust_begin_short_backtrace::<rustc_interface[abf69827c14388d7]::util::run_in_thread_with_globals<rustc_interface[abf69827c14388d7]::util::run_in_thread_pool_with_globals<rustc_interface[abf69827c14388d7]::interface::run_compiler<(), rustc_driver_impl[ee712ad3fe927a50]::run_compiler::{closure#0}>::{closure#1}, ()>::{closure#0}, ()>::{closure#0}::{closure#0}, ()>
  28:     0x7faa1df106e9 - <std[30d1384522680fe8]::thread::lifecycle::spawn_unchecked<rustc_interface[abf69827c14388d7]::util::run_in_thread_with_globals<rustc_interface[abf69827c14388d7]::util::run_in_thread_pool_with_globals<rustc_interface[abf69827c14388d7]::interface::run_compiler<(), rustc_driver_impl[ee712ad3fe927a50]::run_compiler::{closure#0}>::{closure#1}, ()>::{closure#0}, ()>::{closure#0}::{closure#0}, ()>::{closure#1} as core[21868c0c5a10a1a4]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  29:     0x7faa1df0eb38 - <std[30d1384522680fe8]::sys::thread::unix::Thread>::new::thread_start
  30:     0x7faa178969cb - <unknown>
  31:     0x7faa1791aa0c - <unknown>
  32:                0x0 - <unknown>

error: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: please make sure that you have updated to the latest nightly

note: rustc 1.94.0-nightly (fbab541a7 2025-12-06) running on x86_64-unknown-linux-gnu

query stack during panic:
#0 [lint_mod] linting top-level module
#1 [analysis] running analysis passes on crate `mvce`
end of query stack
warning: 2 warnings emitted


```

</p>
</details>

@rustbot label +F-unsafe_binders

### PR DESCRIPTION
**Pull request by SATVIKsynopsis**
Fixes rust-lang/rust#149719

This PR replaces the `todo!("FIXME(unsafe_binder)")` branch in the `improper_ctypes` lint with a proper diagnostic.

Previously, using an unsafe binder inside an extern `"C"` block caused an internal compiler error.
This fix now ensures that the compiler now emits a clear and stable error message explaining that types containing unsafe binders are not yet supported in FFI.

A new UI test `(unsafe-binder-basic.rs)` is included to ensure this behavior remains stable and prevent regressions.

### CODE REVIEW

File: compiler/rustc_lint/src/types/improper_ctypes.rs [hunk 1]
```diff
@@ -669,7 +669,17 @@ impl<'a, 'tcx> ImproperCTypesVisitor<'a, 'tcx> {
                 FfiSafe
             }
 
-            ty::UnsafeBinder(_) => todo!("FIXME(unsafe_binder)"),
+            ty::UnsafeBinder(binder) => {
+                let ty = binder.skip_binder(); // extract the inner type
+                let _vars = binder.bound_vars(); // get bound vars if needed
```
Comment (mati865) [inline compiler/rustc_lint/src/types/improper_ctypes.rs]: When using a chatbot to generate the code, you have to at least review it afterwards. `_var` is unused and should be removed.

File: tests/ui/lint/improper-ctypes/unsafe-binder-basic.rs [hunk 2]
```diff
@@ -0,0 +1,11 @@
+// build-fail
+#![feature(unsafe_binders)]
+//~^ WARN the feature `unsafe_binders` is incomplete
+#![deny(improper_ctypes)]
```
Comment (reddevilmidzy) [inline tests/ui/lint/improper-ctypes/unsafe-binder-basic.rs]: `// build-fail  comment is not necessary. And if you use `#![expect(incomplete_features)]`, the WARN will not occur.

Comment (reddevilmidzy) [inline tests/ui/lint/improper-ctypes/unsafe-binder-basic.rs]: `// build-fail` comment is not necessary. And if you use `#![expect(incomple_feature)]`, the WARN will not occur.

File: tests/ui/lint/improper-ctypes/unsafe-binder-basic.stderr [hunk 3]
```diff
@@ -0,0 +1,24 @@
+warning: the feature `unsafe_binders` is incomplete and may not be safe to use and/or cause compiler crashes
+  --> $DIR/unsafe-binder-basic.rs:2:12
+   |
+LL | #![feature(unsafe_binders)]
+   |            ^^^^^^^^^^^^^^
+   |
+   = note: see issue #130516 <https://github.com/rust-lang/rust/issues/130516> for more information
+   = note: `#[warn(incomplete_features)]` on by default
+
+error: `extern` block uses type `&()`, which is not FFI-safe
```
Comment (Kivooeo) [inline tests/ui/lint/improper-ctypes/unsafe-binder-basic.stderr]: Because, as you could see here, to me, it seems not correct, I would like to see something like `unsafe<'a> &'a ()` here instead of just `&()`

File: compiler/rustc_lint/src/types/improper_ctypes.rs [hunk 4]
```diff
@@ -669,7 +669,16 @@ impl<'a, 'tcx> ImproperCTypesVisitor<'a, 'tcx> {
                 FfiSafe
             }
 
-            ty::UnsafeBinder(_) => todo!("FIXME(unsafe_binder)"),
+            ty::UnsafeBinder(binder) => {
+                let ty = binder.skip_binder(); // extract the inner type
```
Comment (Kivooeo) [inline compiler/rustc_lint/src/types/improper_ctypes.rs]: Is there particular reason why do we want to skip binders here and not just use `ty`?

**Review by Kivooeo — COMMENTED** [review]
Hi, I see this is your first pull request - thank you for taking the time to submit it.

I’ve noticed the reasonable concerns raised by Mateusz above that this may have been AI-generated. If you'd like, you’re welcome to join the discussion below and help explain the reasoning behind the code decisions you made.

---

Also, I’d like to mention that we recently adopted a policy aimed at keeping reviews sustainable. 

In short, it allows reviewers to redirect or close contributions that are overly burdensome to review - for example, when code or explanations appear inconsistent, contradictory, or don’t demonstrate an understanding of the existing codebase. You can read the full details here:

https://github.com/rust-lang/compiler-team/issues/893

*[View changes since this review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/rust/149730/aa301763000fd65db235b2d6e4c04da99abf8cd8..22a10e199b89b268eb87816e8188bc450ed672a8)*

File: compiler/rustc_lint/src/types/improper_ctypes.rs [hunk 5]
```diff
@@ -1016,7 +1025,6 @@ impl<'tcx> LateLintPass<'tcx> for ImproperCTypesLint {
             | hir::ItemKind::ExternCrate(..) => {}
         }
     }
-
```
Comment (Kivooeo) [inline compiler/rustc_lint/src/types/improper_ctypes.rs:1019]: This line was removed by an accident right?

File: compiler/rustc_lint/src/types/improper_ctypes.rs [hunk 6]
```diff
@@ -669,7 +669,16 @@ impl<'a, 'tcx> ImproperCTypesVisitor<'a, 'tcx> {
                 FfiSafe
             }
 
-            ty::UnsafeBinder(_) => todo!("FIXME(unsafe_binder)"),
+            ty::UnsafeBinder(binder) => {
+                let ty = binder.skip_binder(); // extract the inner type
+
+                FfiUnsafe {
+                    ty,
+                    reason: "types containing `unsafe` binders are not yet fully supported in FFI"
```
Comment (Kivooeo) [inline compiler/rustc_lint/src/types/improper_ctypes.rs]: As you can see above, all other arms are uses `fluent` to pass error messages and not just `&str`

Can you please take a look at other arms to see how they handle it

**Review by Kivooeo — COMMENTED** [review]
And some nits I'm less concerned about, but still think are worth mentioning

*[View changes since this review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/rust/149730/aa301763000fd65db235b2d6e4c04da99abf8cd8..22a10e199b89b268eb87816e8188bc450ed672a8)*

**Comment by SATVIKsynopsis** [comment]
thanks for asking and happy to explain and answer your questions

i used skip_binder() because i only wanted to check the inner type that actually reaches the FFI boundary. The binder itself doesn’t matter for the FFI-safety check, since C doesn’t understand those binders. if I used the whole ty without skipping the binder, the lint wouldn’t look at the real inner type.

i understand your point about the diagnostic looking like just &().  
if you prefer that the message keeps the unsafe<a> part visible, i can update the code to print it that way.

File: tests/ui/lint/improper-ctypes/unsafe-binder-basic.stderr [hunk 7]
```diff
@@ -0,0 +1,14 @@
...
+  --> $DIR/unsafe-binder-basic.rs:6:18
+   |
+LL |     fn exit_2(x: unsafe<'a> &'a ());
+   |                  ^^^^^^^^^^^^^^^^^ not FFI-safe
```
Comment (Kivooeo) [inline tests/ui/lint/improper-ctypes/unsafe-binder-basic.stderr:5]: Yes, but if we look closer here - this highlighting (we call this `span`) points to the entire type, including the unsafe binder. That already signals to the programmer that the whole binder construct is unsafe for FFI, right?

So, purely for consistency, I'd like the diagnostic to say `unsafe<'a> &'a ()` and point to the same `unsafe<'a> &'a ()`.

Right now there's a slight mismatch: it says `&()` but shows `unsafe<'a> &'a ()`.

**Comment by SATVIKsynopsis** [comment]
I see your point about using the fluent error messages instead of a raw string. I will take a look at the other arms and update this one to follow the same pattern so the diagnostic style stays consistent.

I will push the fixes shortly.

**Comment by SATVIKsynopsis** [comment]
that makes sense.

the current output only shows &(), while the span highlights the full unsafe<a> &a (). I agree that the diagnostic should refer to the same type for consistency.

I will update the diagnostic to report unsafe<a> &a () instead of just &(), and then adjust the .stder file to match the updated message.

Thanks for your clear explanation and feedback. it is really helpful as i am learning my way around the compiler codebase.

File: compiler/rustc_lint/src/types/improper_ctypes.rs [hunk 8]
```diff
@@ -669,13 +669,10 @@ impl<'a, 'tcx> ImproperCTypesVisitor<'a, 'tcx> {
...
 
-            ty::UnsafeBinder(binder) => {
-                let ty = binder.skip_binder(); // extract the inner type
-
+            ty::UnsafeBinder(_binder) => {
                 FfiUnsafe {
-                    ty,
-                    reason: "types containing `unsafe` binders are not yet fully supported in FFI"
-                        .into(),
+                    ty, // changesd to show the full unsafe<a> &a() type
```
Comment (Kivooeo) [inline compiler/rustc_lint/src/types/improper_ctypes.rs]: Redundant comment 

Squash commits please after removing this comment, to keep git history clean

File: compiler/rustc_lint/messages.ftl [hunk 9]
```diff
@@ -360,7 +360,6 @@ lint_implicit_unsafe_autorefs = implicit autoref creates a reference to the dere
 lint_improper_ctypes = `extern` {$desc} uses type `{$ty}`, which is not FFI-safe
     .label = not FFI-safe
     .note = the type is defined here
-
```
Comment (Kivooeo) [inline compiler/rustc_lint/messages.ftl:363]: Also accidentally removed line

File: compiler/rustc_lint/messages.ftl [hunk 10]
```diff
@@ -416,6 +415,8 @@ lint_improper_ctypes_union_layout_help = consider adding a `#[repr(C)]` or `#[re
 lint_improper_ctypes_union_layout_reason = this union has unspecified layout
 lint_improper_ctypes_union_non_exhaustive = this union is non-exhaustive
 
+lint_improper_ctypes_unsafe_binder = types containing `unsafe` binders are not yet fully supported in FFI
```
Comment (Kivooeo) [inline compiler/rustc_lint/messages.ftl]: I feel like this is not best wording here, I don't like "not yet fully supported" part, it creates wrong feeling that this will be supported in future or something, but it's wrong

Maybe something more straightforward like:

> `unsafe` binders are incompatible with FFI

File: compiler/rustc_lint/src/types/improper_ctypes.rs [hunk 11]
```diff
@@ -1016,7 +1018,6 @@ impl<'tcx> LateLintPass<'tcx> for ImproperCTypesLint {
             | hir::ItemKind::ExternCrate(..) => {}
         }
     }
-
```
Comment (Kivooeo) [inline compiler/rustc_lint/src/types/improper_ctypes.rs:1019]: Here

File: compiler/rustc_lint/messages.ftl (hunk 9 above)
Comment (Kivooeo) [inline compiler/rustc_lint/messages.ftl:363]: And here

**Review by Kivooeo — COMMENTED** [review]
It would be great if you could restore the two lines that were accidentally removed

*[View changes since this review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/rust/149730/03d7ad7dd67d71f1ef1a790fcb4ceb2484ced761..8423d120d68a8711202a5274fc62f608ba75865e)*

File: compiler/rustc_lint/messages.ftl [hunk 12]
```diff
@@ -360,7 +360,7 @@ lint_implicit_unsafe_autorefs = implicit autoref creates a reference to the dere
 lint_improper_ctypes = `extern` {$desc} uses type `{$ty}`, which is not FFI-safe
     .label = not FFI-safe
     .note = the type is defined here
-
+
```
Comment (Kivooeo) [inline compiler/rustc_lint/messages.ftl]: This line should be just empty without spaces, or I don't know why github shows it like this? is there some spaces in this line?

File: compiler/rustc_lint/src/types/improper_ctypes.rs [hunk 13]
```diff
@@ -1053,4 +1055,4 @@ impl<'tcx> LateLintPass<'tcx> for ImproperCTypesLint {
             self.check_fn_for_external_abi_fnptr(cx, CItemKind::Definition, id, decl);
         }
     }
-}
+}
```
Comment (Kivooeo) [inline compiler/rustc_lint/src/types/improper_ctypes.rs]: Why did you removed this last line in this file? It should stay here

File: compiler/rustc_lint/src/types/improper_ctypes.rs [hunk 14]
```diff
@@ -669,7 +669,9 @@ impl<'a, 'tcx> ImproperCTypesVisitor<'a, 'tcx> {
                 FfiSafe
             }
 
-            ty::UnsafeBinder(_) => todo!("FIXME(unsafe_binder)"),
+            ty::UnsafeBinder(_binder) => {
```
Comment (Kivooeo) [inline compiler/rustc_lint/src/types/improper_ctypes.rs]: Thanks! Last one nit and we good to go! 


```suggestion
            ty::UnsafeBinder(_) => {
```
