### PR TITLE
Make the BUG_REPORT_URL configurable by tools 

### LINKED ISSUE #109486: Make the BUG_REPORT_URL configurable for tools
Right now, `install_ice_hook` hard-codes the bug report url to `"https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md"`:
https://github.com/rust-lang/rust/blob/6502613a8199cab4cb68b08c7ddce6f210d8d69c/compiler/rustc_driver_impl/src/lib.rs#L1192

For tools, this is not correct; rustdoc at least wants `T-rustdoc` instead of `T-compiler`, and other tools want different repositories altogether. I'm opening this bug here because it's relevant to all tools, even though the original context was for clippy.

Fixing this seems a little tricky since `DEFAULT_HOOK` can't take an argument and doesn't have access to TyCtxt, but maybe we can solve this with thread-locals or something similar?

cc @rust-lang/rustdoc @rust-lang/clippy @rust-lang/miri @rust-lang/rustfmt
_Originally posted by @ingomancer in https://github.com/rust-lang/rust-clippy/issues/10529

### PR DESCRIPTION
**Pull request by jyn514**
This greatly simplifies how hard it is to set a custom bug report url; previously tools had to copy
the entire hook implementation.

I haven't changed clippy in case they want to make the change upstream instead of the subtree, but
I'm happy to do so here if the maintainers want - cc @rust-lang/clippy

Fixes https://github.com/rust-lang/rust/issues/109486.

### CODE REVIEW

File: compiler/rustc_driver_impl/src/lib.rs [hunk 1]
```diff
@@ -1195,35 +1192,62 @@ pub fn catch_with_exit_code(f: impl FnOnce() -> interface::Result<()>) -> i32 {
...
-            if let Some(msg) = info.payload().downcast_ref::<String>() {
-                if msg.starts_with("failed printing to stdout: ") && msg.ends_with("(os error 232)")
-                {
-                    early_error_no_abort(ErrorOutputType::default(), &msg);
-                    return;
-                }
-            };
+/// Stores the default panic hook, from before [`set_default_hook`] was called.
+static DEFAULT_HOOK: OnceLock<Box<dyn Fn(&panic::PanicInfo<'_>) + Sync + Send + 'static>> =
+    OnceLock::new();
```
Comment (jyn514) [inline compiler/rustc_driver_impl/src/lib.rs:1197]: in retrospect this change wasn't actually necessary, I can revert it if you want. The previous code was very confusing wrt the order it set and unset the hooks.

**Comment by Manishearth** [comment]
Subtree is fine!

**Comment by jyn514** [comment]
I see the current hook also includes clippy's version, which can be different from rustc's version - I'll see if I can add a custom callback to the hook so clippy can keep that info. https://github.com/rust-lang/rust/blob/8ce92daa854e329f4fb7ac75c28dbeea3f5bb125/src/tools/clippy/src/driver.rs#L242

**Comment by jyn514** [comment]
cc @rust-lang/rustdoc as well but the changes to rustdoc are very minor

**Review by notriddle — APPROVED** [review]
Yeah, rustdoc changes look fine.

File: src/tools/miri/src/bin/miri.rs [hunk 2]
```diff
@@ -309,6 +308,9 @@ fn main() {
         )
     }
 
+    // Add an ICE bug report hook.
+    rustc_driver::install_ice_hook(Some("https://github.com/rust-lang/miri/issues/new"), None);
```
Comment (RalfJung) [inline src/tools/miri/src/bin/miri.rs:312]: Do we usually link to the 'new issue' page or just the issue list? IMO the latter makes more sense to avoid duplicates.

File: compiler/rustc_driver_impl/src/lib.rs [hunk 3]
```diff
@@ -1195,35 +1192,62 @@ pub fn catch_with_exit_code(f: impl FnOnce() -> interface::Result<()>) -> i32 {
...
+        std::env::set_var("RUST_BACKTRACE", "full");
+    }
 
-                // Separate the output with an empty line
-                eprintln!();
+    let _ = DEFAULT_HOOK.set(panic::take_hook());
+    let bug_report_url = bug_report_url.unwrap_or(
+        "https://github.com/rust-lang/rust/issues/new\
+        ?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md",
+    );
```
Comment (WaffleLapkin) [inline compiler/rustc_driver_impl/src/lib.rs:1225]: Can we just use this string on the `install_ice_hook` call-site, instead of using an option?

File: compiler/rustc_driver_impl/src/lib.rs [hunk 4]
```diff
@@ -1195,35 +1192,62 @@ pub fn catch_with_exit_code(f: impl FnOnce() -> interface::Result<()>) -> i32 {
...
+    // by the user. Compiler developers and other rustc users can
+    // opt in to less-verbose backtraces by manually setting "RUST_BACKTRACE"
+    // (e.g. `RUST_BACKTRACE=1`)
+    if std::env::var("RUST_BACKTRACE").is_err() {
+        std::env::set_var("RUST_BACKTRACE", "full");
+    }
 
-                // Separate the output with an empty line
-                eprintln!();
+    let _ = DEFAULT_HOOK.set(panic::take_hook());
```
Comment (WaffleLapkin) [inline compiler/rustc_driver_impl/src/lib.rs:1221]: this can probably be `get_or_init`, so that we don't need `if let Some(hook) = DEFAULT_HOOK.get()` in the closure below

File: src/tools/miri/src/bin/miri.rs [hunk 5]
```diff
@@ -309,6 +308,9 @@ fn main() {
         )
     }
 
+    // Add an ICE bug report hook.
+    rustc_driver::install_ice_hook(Some("https://github.com/rust-lang/miri/issues/new"));
```
Comment (WaffleLapkin) [inline src/tools/miri/src/bin/miri.rs]: doesn't this call `install_ice_hook` twice in case of `MIRI_BE_RUSTC`?

File: compiler/rustc_driver_impl/src/lib.rs [hunk 6]
```diff
@@ -1300,6 +1309,12 @@ pub fn report_ice(info: &panic::PanicInfo<'_>, bug_report_url: &str) {
 
     interface::try_print_query_stack(&handler, num_frames);
 
+    // We don't trust this callback not to panic itself, so run it at the end after we're sure we've
+    // printed all the relevant info.
+    if let Some(extra_info) = extra_info {
+        extra_info(&handler);
+    }
```
Comment (WaffleLapkin) [inline compiler/rustc_driver_impl/src/lib.rs:1316]: Again, we can pass `drop` or `|_| {}` and not use an option

File: src/tools/miri/src/bin/miri.rs (hunk 2 above)
Comment (WaffleLapkin) [reply src/tools/miri/src/bin/miri.rs:312]: For rustc we use https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md, so I'd say we usually link 'new issue'.

I guess the point is that duplicates are better than an unreported problem.

File: src/tools/miri/src/bin/miri.rs (hunk 5 above)
Comment (WaffleLapkin) [reply src/tools/miri/src/bin/miri.rs]: Ah, okay

File: compiler/rustc_driver_impl/src/lib.rs (hunk 3 above)
Comment (jyn514) [reply compiler/rustc_driver_impl/src/lib.rs:1225]: If we do that, the string has to be duplicated between rustc and miri, which seems unfortunate since Miri shouldn't need to care if we change the ICE issue template.

Comment (jyn514) [reply compiler/rustc_driver_impl/src/lib.rs:1225]: oh, I can have a public `DEFAULT_BUG_REPORT_URL` constant in rustc_driver, I'll do that so we can remove the option.

File: compiler/rustc_driver_impl/src/lib.rs (hunk 4 above)
Comment (jyn514) [reply compiler/rustc_driver_impl/src/lib.rs]: good idea, done :)

**Review by WaffleLapkin — APPROVED** [review]
The code changes look good to me. r=me once tool maintainers are satisfied.

**Review by flip1995 — APPROVED** [review]
Clippy changes look awesome!

**Review by RalfJung — APPROVED** [review]
:+1: on the Miri changes

**Review by calebcartwright — APPROVED** [review]
rustfmt changes lgtm

**Comment by uweigand** [comment]
The new `tests/rustdoc-ui/ice-bug-report-url.rs` test fails for me on `s390x-unknown-linux-gnu` due to the following difference in stderr output:
```
---- [ui] tests/rustdoc-ui/ice-bug-report-url.rs stdout ----
diff of stderr:

5          |          ^ expected one of `->`, `where`, or `{`
6
7       thread panicked at 'aborting due to `-Z treat-err-as-bug`'
-       stack backtrace:
-       error: the compiler unexpectedly panicked. this is a bug.
+       stack backtrace:                             error: the compiler unexpectedly panicked. this is a bug.
10
11      note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-rustdoc&template=ice.md
12


The actual stderr differed from the expected stderr.
```

Not sure why this happens, could this be some issue with the `normalize-stderr-test` rules?

The complete (unnormalized) output is:
```
error: expected one of `->`, `where`, or `{`, found `<eof>`
  --> /home/uweigand/rust/tests/rustdoc-ui/ice-bug-report-url.rs:13:10
   |
LL | fn wrong()
   |          ^ expected one of `->`, `where`, or `{`

thread 'rustc' panicked at 'aborting due to `-Z treat-err-as-bug=1`', compiler/rustc_errors/src/lib.rs:1711:30
stack backtrace:
   0:      0x3ffec4992a2 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h413b3b0f9de3326b
   1:      0x3ffec56739e - core::fmt::write::h84c7cedca7777db7
   2:      0x3ffec4ade78 - std::panicking::default_hook::h89c76c4bb766adfe
   3:      0x3ffed577204 - rustc_driver_impl[b094fb3383cea06f]::install_ice_hook::{closure#0}
   4:      0x3ffec4af758 - std::panicking::rust_panic_with_hook::h3b0cf6703ee96eed
   5:      0x3ffec499854 - std::panicking::begin_panic_handler::{{closure}}::h36b73881ffb76e47
   6:      0x3ffec4995d0 - std::sys_common::backtrace::__rust_end_short_backtrace::h9f7578507492eb4f
   7:      0x3ffec4af2ae - rust_begin_unwind
   8:      0x3ffec47058c - core::panicking::panic_fmt::h9c206364a104a065
   9:      0x3fff4944962 - <rustc_errors[23e277f92d39e05]::HandlerInner>::emit_diagnostic::{closure#2}
  10:      0x3fff4943c28 - <rustc_errors[23e277f92d39e05]::HandlerInner>::emit_diagnostic
  11:      0x3fff49b3be6 - <rustc_span[fa50c18a7876c42a]::ErrorGuaranteed as rustc_errors[23e277f92d39e05]::diagnostic_builder::EmissionGuarantee>::diagnostic_builder_emit_producing_guarantee
  12:      0x3ffed6acba2 - <rustc_interface[6001cdef06e51c04]::queries::Queries>::pre_configure
  13:      0x3ffed6ad5f8 - <rustc_interface[6001cdef06e51c04]::queries::Queries>::global_ctxt
  14:      0x2aa0048f836 - <rustc_interface[6001cdef06e51c04]::interface::Compiler>::enter::<rustdoc[9110c6921b1a8d2a]::main_args::{closure#1}::{closure#0}, core[1e85ed23d5535b8b]::result::Result<(), rustc_span[fa50c18a7876c42a]::ErrorGuaranteed>>
  15:      0x2aa001f4318 - rustc_span[fa50c18a7876c42a]::set_source_map::<core[1e85ed23d5535b8b]::result::Result<(), rustc_span[fa50c18a7876c42a]::ErrorGuaranteed>, rustc_interface[6001cdef06e51c04]::interface::run_compiler<core[1e85ed23d5535b8b]::result::Result<(), rustc_span[fa50c18a7876c42a]::ErrorGuaranteed>, rustdoc[9110c6921b1a8d2a]::main_args::{closure#1}>::{closure#0}::{closure#0}>
  16:      0x2aa004915d8 - <scoped_tls[de53d4204225384f]::ScopedKey<rustc_span[fa50c18a7876c42a]::SessionGlobals>>::set::<rustc_interface[6001cdef06e51c04]::interface::run_compiler<core[1e85ed23d5535b8b]::result::Result<(), rustc_span[fa50c18a7876c42a]::ErrorGuaranteed>, rustdoc[9110c6921b1a8d2a]::main_args::{closure#1}>::{closure#0}, core[1e85ed23d5535b8b]::result::Result<(), rustc_span[fa50c18a7876c42a]::ErrorGuaranteed>>
  17:      0x2aa000f1cf8 - std[4f5ed56b8f53302d]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[6001cdef06e51c04]::util::run_in_thread_pool_with_globals<rustc_interface[6001cdef06e51c04]::interface::run_compiler<core[1e85ed23d5535b8b]::result::Result<(), rustc_span[fa50c18a7876c42a]::ErrorGuaranteed>, rustdoc[9110c6921b1a8d2a]::main_args::{closure#1}>::{closure#0}, core[1e85ed23d5535b8b]::result::Result<(), rustc_span[fa50c18a7876c42a]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[1e85ed23d5535b8b]::result::Result<(), rustc_span[fa50c18a7876c42a]::ErrorGuaranteed>>
  18:      0x2aa000f35ae - std[4f5ed56b8f53302d]::panicking::try::do_call::<core[1e85ed23d5535b8b]::panic::unwind_safe::AssertUnwindSafe<<std[4f5ed56b8f53302d]::thread::Builder>::spawn_unchecked_<rustc_interface[6001cdef06e51c04]::util::run_in_thread_pool_with_globals<rustc_interface[6001cdef06e51c04]::interface::run_compiler<core[1e85ed23d5535b8b]::result::Result<(), rustc_span[fa50c18a7876c42a]::ErrorGuaranteed>, rustdoc[9110c6921b1a8d2a]::main_args::{closure#1}>::{closure#0}, core[1e85ed23d5535b8b]::result::Result<(), rustc_span[fa50c18a7876c42a]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[1e85ed23d5535b8b]::result::Result<(), rustc_span[fa50c18a7876c42a]::ErrorGuaranteed>>::{closure#1}::{closure#0}>, core[1e85ed23d5535b8b]::result::Result<(), rustc_span[fa50c18a7876c42a]::ErrorGuaranteed>>
  19:      0x2aa0014c090 - __rust_try.llvm.11562562457469458502
  20:      0x2aa003315aa - <<std[4f5ed56b8f53302d]::thread::Builder>::spawn_unchecked_<rustc_interface[6001cdef06e51c04]::util::run_in_thread_pool_with_globals<rustc_interface[6001cdef06e51c04]::interface::run_compiler<core[1e85ed23d5535b8b]::result::Result<(), rustc_span[fa50c18a7876c42a]::ErrorGuaranteed>, rustdoc[9110c6921b1a8d2a]::main_args::{closure#1}>::{closure#0}, core[1e85ed23d5535b8b]::result::Result<(), rustc_span[fa50c18a7876c42a]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[1e85ed23d5535b8b]::result::Result<(), rustc_span[fa50c18a7876c42a]::ErrorGuaranteed>>::{closure#1} as core[1e85ed23d5535b8b]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  21:      0x3ffec4fe0b0 - std::sys::unix::thread::Thread::new::thread_start::ha67c2f2eda1f7e3b
  22:      0x3ffec09f5c8 - start_thread
                               at /usr/src/debug/glibc-2.36-9.1.ibm.fc37.s390x/nptl/pthread_create.c:442:8
  23:      0x3ffec11b51e - <unknown>
                               at /usr/src/debug/glibc-2.36-9.1.ibm.fc37.s390x/misc/../sysdeps/unix/sysv/linux/s390/s390-64/clone.S:66
  24:                0x0 - <unknown>

error: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-rustdoc&template=ice.md

note: rustc 1.71.0-dev running on s390x-unknown-linux-gnu

note: compiler flags: -Z threads=1 -C codegen-units=1 -Z ui-testing -Z simulate-remapped-rust-src-base=/rustc/FAKE_PREFIX -Z translate-remapped-path-to-local-path=no -Z deduplicate-diagnostics=no -C strip=debuginfo -C debuginfo=0 -Z treat-err-as-bug

query stack during panic:
end of query stack
```

**Comment by jyn514** [comment]
@uweigand that test should not be platform-specific. I don't know why it would fail only on s390x.

**Comment by jyn514** [comment]
By chance, does s390x have \r\n line endings?

**Comment by jyn514** [comment]
This is the relevant normalization: `// normalize-stderr-test "\s*\d{1,}: .*\n" -> ""`

it should remove the line completely, but somehow it's being replaced with a space instead.

**Comment by uweigand** [comment]
> By chance, does s390x have \r\n line endings?

No, it's just \n like on other Linux platforms.

> it should remove the line completely, but somehow it's being replaced with a space instead.

It looks like it is removing the line ending of the `stack backtrace: ` line for some reason, merging the next line into it?

```
-       stack backtrace:
-       error: the compiler unexpectedly panicked. this is a bug.
+       stack backtrace:                             error: the compiler unexpectedly panicked. this is a bug.
```

Not sure how that could happen ...

**Comment by uweigand** [comment]
Ah, I think I see what the problem is.   The `\s` in a Rust regex matches any whitespace, *including* newline.  Therefore, when looking at these two lines:
```
// normalize-stderr-test "\s*\d{1,}: .*\n" -> ""
// normalize-stderr-test "\s at .*\n" -> ""
```
the first one will remove (multiple) newlines *before* the line (because of the `\s*`) *and* one newline after the line (because of the `\n`).   However, the second one has just a single `\s`, which due to its position relative to the ` at ` can never match a newline, just a space.

You can see that when removing the second of those `normalize-stderr-test`, the output is:
```
thread panicked at 'aborting due to `-Z treat-err-as-bug`'
stack backtrace:                               at /usr/src/debug/glibc-2.36-9.1.ibm.fc37.s390x/nptl/pthread_create.c:442:8                               at /usr/src/debug/glibc-2.36-9.1.ibm.fc37.s390x/misc/../sysdeps/unix/sysv/linux/s390/s390-64/clone.S:66
error: the compiler unexpectedly panicked. this is a bug.
```
So if we add the second `normalize-stderr-test` back, it will merge remove everything from two spaces before the first ` at ` up to and including the newline at the end, which results in the merged output we see.

Note that this only happens if the *last* line in the backtrace is one of lines with an address - if it is one of the lines with an ` at `, the result will be different.  This would explain why the effect is platform-specific.

(We see that last line with address 0 on s390x - that's probably a bug in our backtrace implementation that should be fixed, but really those regexes should handle that case too ...)

I think the whitespace in the backtrace output is actually always just plain spaces, so maybe we can simply use:
```
// normalize-stderr-test " +\d{1,}: .*\n" -> ""
// normalize-stderr-test " + at .*\n" -> ""
```
This works for me (we also need to add one blank line to the stderr output that isn't removed any more now).

**Comment by jyn514** [comment]
sounds great! @uweigand could you make a PR with that change, please? :)

**Comment by uweigand** [comment]
> sounds great! @uweigand could you make a PR with that change, please? :)

https://github.com/rust-lang/rust/pull/111439
