### PR TITLE
Properly define va_arg and va_list for aarch64-apple-darwin

### LINKED ISSUE #78092: Variadic FFI test fails on aarch64-apple-darwin
```
x.py test --stage 2 src/test/ui/abi/variadic-ffi
```

```
---- [ui] ui/abi/variadic-ffi.rs stdout ----

error: test run failed!
status: exit code: 101
command: "/Users/shepmaster/Projects/rust/full/build/aarch64-apple-darwin/test/ui/abi/variadic-ffi/a"
stdout:
------------------------------------------

------------------------------------------
stderr:
------------------------------------------
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `3078109020`,
 right: `30`', /Users/shepmaster/Projects/rust/src/test/ui/abi/variadic-ffi.rs:78:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

------------------------------------------
```

### Meta

Fails in e3051d8c24467b54c81da9d9ad70a3e82e106ec1

### PR DESCRIPTION
**Pull request by shepmaster**
From [Apple][]:

> Because of these changes, the type `va_list` is an alias for `char*`,
> and not for the struct type in the generic procedure call standard.

With this change `/x.py test --stage 1 src/test/ui/abi/variadic-ffi`
passes.

Fixes #78092

[Apple]: https://developer.apple.com/documentation/xcode/writing_arm64_code_for_apple_platforms

### CODE REVIEW

**Comment by shepmaster** [comment]
Please double check my configuration attributes. I definitely screwed them up two times during development.

File: compiler/rustc_codegen_llvm/src/va_arg.rs [hunk 1]
```diff
@@ -186,8 +186,8 @@ pub(super) fn emit_va_arg(
         ("aarch64", true) => {
             emit_ptr_va_arg(bx, addr, target_ty, false, Align::from_bytes(8).unwrap(), false)
         }
-        // iOS AArch64
-        ("aarch64", _) if target.target_os == "ios" => {
+        // macOS/iOS AArch64
+        ("aarch64", _) if target.target_os == "macos" || target.target_os == "ios" => {
```
Comment (dlrobertson) [inline compiler/rustc_codegen_llvm/src/va_arg.rs:190]: AFAIK in both the `target_os == "macos"` and in the `target_os == "ios"` case `target.options.is_like_osx == true`. I wonder if it would be simpler to have `("aarch64", _) if target.options.is_like_osx` instead of checking on the string of the OS. Is there a case where `target.options.is_like_osx == true` and the target arch is `"aarch64"`, but the va_list isn't a `char*`? I can't think of one, but I may be missing one.

**Review by dlrobertson — COMMENTED** [review]
Good catch! I thought the only case we needed to force a void pointer variant of a `va_list` for apple was on iOS.

**Comment by shepmaster** [comment]
> was on iOS.

You **were** right! 😉 The new `aarch64-appled-darwin` target didn't exist when this code was written. :-)

File: compiler/rustc_codegen_llvm/src/va_arg.rs (hunk 1 above)
Comment (shepmaster) [reply compiler/rustc_codegen_llvm/src/va_arg.rs]: Updated!

**Comment by dlrobertson** [comment]
Looks good to me!

File: compiler/rustc_codegen_llvm/src/va_arg.rs [hunk 2]
```diff
@@ -173,26 +173,26 @@ pub(super) fn emit_va_arg(
...
         }
         // Windows AArch64
-        ("aarch64", true) => {
+        ("aarch64", true, _) => {
             emit_ptr_va_arg(bx, addr, target_ty, false, Align::from_bytes(8).unwrap(), false)
         }
-        // iOS AArch64
-        ("aarch64", _) if target.target_os == "ios" => {
+        // macOS/iOS AArch64
+        ("aarch64", _, true) => {
```
Comment (nagisa) [inline compiler/rustc_codegen_llvm/src/va_arg.rs:190]: Minor style nit: matching on forever increasing tuple elements seems untenable in the future. It seems to me like `if target.options.is_like_osx` would result in slightly more maintainable code.

**Comment by nagisa** [comment]
r=me, your call if you want to do anything about the style comment.

File: library/core/src/ffi.rs [hunk 3]
```diff
@@ -190,7 +194,7 @@ pub struct VaList<'a, 'f: 'a> {
 
     #[cfg(all(
         any(target_arch = "aarch64", target_arch = "powerpc", target_arch = "x86_64"),
-        any(not(target_arch = "aarch64"), not(target_os = "ios")),
+        any(not(target_arch = "aarch64"), all(not(target_os = "macos"), not(target_os = "ios"))),
```
Comment (nagisa) [inline library/core/src/ffi.rs:197]: Minor style nit `not(any(...))` instead of `all(not(...), not(...))`?

File: compiler/rustc_codegen_llvm/src/va_arg.rs (hunk 2 above)
Comment (shepmaster) [reply compiler/rustc_codegen_llvm/src/va_arg.rs:190]: Would you like me to change the windows one as well?

File: library/core/src/ffi.rs (hunk 3 above)
Comment (shepmaster) [reply library/core/src/ffi.rs:197]: Can do! Was just trying to adhere to existing style.

File: compiler/rustc_codegen_llvm/src/va_arg.rs (hunk 2 above)
Comment (nagisa) [reply compiler/rustc_codegen_llvm/src/va_arg.rs:190]: Entirely your call, but I believe doing so for all kinds of effective guards will produce nicer code overall.

File: library/core/src/ffi.rs (hunk 3 above)
Comment (shepmaster) [reply library/core/src/ffi.rs]: Changed!

File: compiler/rustc_codegen_llvm/src/va_arg.rs (hunk 2 above)
Comment (shepmaster) [reply compiler/rustc_codegen_llvm/src/va_arg.rs]: Did this in a first commit.

**Review by dlrobertson — COMMENTED** [review]
Thanks for updating the match statement to use a match arm guard instead of the tuple matching! I think it looks a good bit cleaner.

File: library/core/src/ffi.rs [hunk 4]
```diff
@@ -223,7 +227,7 @@ impl<'f> VaListImpl<'f> {
 
 #[cfg(all(
     any(target_arch = "aarch64", target_arch = "powerpc", target_arch = "x86_64"),
-    any(not(target_arch = "aarch64"), not(target_os = "ios")),
+    any(not(target_arch = "aarch64"), all(not(target_os = "macos"), not(target_os = "ios"))),
```
Comment (nagisa) [inline library/core/src/ffi.rs:230]: minor nit: this is another instance of `all(not(...), not(...))`

Comment (shepmaster) [reply library/core/src/ffi.rs]: Changed!
