### PR TITLE
Fix built-in indexing not being used where index type wasn't "obviously" usize

### LINKED ISSUE #33903: Builtin indexing not used with non-trivial indices.
It appears that when it's not obvious the index type is `usize`, we fall back to overloaded indexing:

``` rust
const FOO: i32 = [12, 34][0 + 1];
```

Fails in constant checking, [on stable](https://play.rust-lang.org/?gist=d3adc745a7d0c6d3c0fe1ac3d8f2e6c9&version=stable&backtrace=0):

``` rust
<anon>:1:18: 1:33 error: user-defined operators are not allowed in constants [E0011]
<anon>:1 const FOO: i32 = [12, 34][0 + 1];
                          ^~~~~~~~~~~~~~~
```

And also with the new MIR-based constant checker, [on nightly](https://play.rust-lang.org/?gist=f293a4ee614960dd73d8bae54b0057db&version=nightly&backtrace=0):

``` rust
error: calls in constants are limited to constant functions, struct and enum constructors [E0015]
 --> <anon>:1:18
1 |> const FOO: i32 = [12, 34][0 + 1];
  |>                  ^^^^^^^^^^^^^^^
```

### LINKED ISSUE #46095: Mutability issue while indexing static immutable array
Hello, today we've found some weird behaviour of array indexing. 
Here is the [example](https://play.rust-lang.org/?gist=30339eb4524ff5678f1c23ef097af029&version=stable)
Code snippet:
```rust
fn foo<'a>(a1: &'a mut Bar, a2: &'a mut Bar)
{
	let a = [a1, a2];
	for i in 0..42
	{
		let index = i % 2;
		//a[i % 2].bar(); //<= error
		a[index].bar(); //<= no error
	}
}
```
The question is, why is the indexing operator behaves depending on whether we evaluate `index` in place or not.

### PR DESCRIPTION
**Pull request by ivanbakel**
Fixes #33903
Fixes #46095

This PR was made possible thanks to the generous help of @eddyb 

Following the example of binary operators, builtin checking for indexing has been moved from the typecheck stage to a writeback stage, after type constraints have been resolved.

### CODE REVIEW

File: src/librustc_typeck/check/writeback.rs [hunk 1]
```diff
@@ -159,8 +160,56 @@ impl<'cx, 'gcx, 'tcx> WritebackCx<'cx, 'gcx, 'tcx> {
...
+                    base_ty
+                }
+            };
+
+            let index_ty = tables.expr_ty_adjusted(&index);
+            let index_ty = self.fcx.resolve_type_vars_if_possible(&index_ty);
+
+            if base_ty.builtin_index().is_some() && index_ty.is_uint() {
+                // Remove the method call record, which blocks use in
+                // constant or static cases
```
Comment (eddyb) [inline src/librustc_typeck/check/writeback.rs]: This comment is far too specific IMO, without this logic `Index<usize> for [T]` `impl` would infinitely recurse, for example.

File: src/librustc_typeck/check/writeback.rs [hunk 2]
```diff
@@ -159,8 +160,56 @@ impl<'cx, 'gcx, 'tcx> WritebackCx<'cx, 'gcx, 'tcx> {
...
+    fn fix_index_builtin_expr(&mut self, e: &hir::Expr) {
+        if let hir::ExprIndex(ref base, ref index) = e.node {
+            let mut tables = self.fcx.tables.borrow_mut();
+
+            let base_ty = {
+                let base_ty = tables.expr_ty_adjusted(&base);
+                // When unsizing, the final type of the expression is taken
+                // from the first argument of the indexing operator, which
+                // is a &self, and has to be deconstructed
+                if let TypeVariants::TyRef(_, ref ref_to) = base_ty.sty {
```
Comment (eddyb) [inline src/librustc_typeck/check/writeback.rs]: We always write this as `ty::TyRef`

File: src/librustc_typeck/check/writeback.rs [hunk 3]
```diff
@@ -159,8 +160,56 @@ impl<'cx, 'gcx, 'tcx> WritebackCx<'cx, 'gcx, 'tcx> {
...
+                    ref_to.ty
+                } else {
+                    base_ty
+                }
+            };
+
+            let index_ty = tables.expr_ty_adjusted(&index);
+            let index_ty = self.fcx.resolve_type_vars_if_possible(&index_ty);
+
+            if base_ty.builtin_index().is_some() && index_ty.is_uint() {
```
Comment (eddyb) [inline src/librustc_typeck/check/writeback.rs]: `index_ty` should be compared to `tcx.types.usize`.

Comment (ivanbakel) [reply src/librustc_typeck/check/writeback.rs]: The `is_uint()` does that, from my understanding - would a direct comparison work in the case of the index being just literals?

Comment (eddyb) [reply src/librustc_typeck/check/writeback.rs]: Since you resolved the type, it can't be `TyInfer(IntVar(_))` anymore, only an `usize`. `is_uint` is pretty useless IMO, and misleading nowadays, when `uint` typically means "any unsigned integer" not `usize`.

File: src/librustc_typeck/check/writeback.rs [hunk 4]
```diff
@@ -159,8 +160,56 @@ impl<'cx, 'gcx, 'tcx> WritebackCx<'cx, 'gcx, 'tcx> {
...
+            let base_ty = {
+                let base_ty = tables.expr_ty_adjusted(&base);
+                // When unsizing, the final type of the expression is taken
+                // from the first argument of the indexing operator, which
+                // is a &self, and has to be deconstructed
+                if let ty::TyRef(_, ref ref_to) = base_ty.sty {
+                    ref_to.ty
+                } else {
+                    base_ty
+                }
```
Comment (nikomatsakis) [inline src/librustc_typeck/check/writeback.rs]: This makes me a bit ... nervous. It seems strange to strip out the `&T` based purely on the type involved. That is, if we were looking at the *adjustment* and deciding to strip off a layer of references, that'd be one thing, but I deciding based on the type alone makes me nervous. Can you give some examples of why this line of code was needed?

Comment (eddyb) [reply src/librustc_typeck/check/writeback.rs]: I'd guess `TyError`, but we should probably skip doing this at all if there are any errors.

**Comment by nikomatsakis** [comment]
@ivanbakel if you have a build of this branch handy, could you tell me the result of running `rustc` on this test case:

```rust
fn main() {
    let mut i = [1,2,3];
    i[i[0] - 1] = 0;
}
```

Does it compile? I'm just curious to see if it fixes another random bug. Thanks =)

File: src/librustc_typeck/check/writeback.rs (hunk 4 above)
Comment (ivanbakel) [reply src/librustc_typeck/check/writeback.rs]: The Unsize adjustment made by the index typechecking code (`2252-2257` in this codebase) doesn't have the unsized type as the `target`, instead taking `method.sig.inputs()[0]`, a `&self`. This is, to my understanding, the only way for the result of `expr_ty_adjusted` to result in a `TyRef`, since otherwise a reference would be deref'd, and you can't do an `impl<'a, T> Index<usize> for &'a [T]` of some kind.

`builtin_index()` returns `None` on `TyRef`, regardless of the underlying type - I considered changing this instead, but I felt this would confuse the dereferencing logic. Alternatively, I could introduce some kind of `fn unsize_type` to use in place of the trait argument, which would return `TySlice` for `TyArray`, which is the only case I can think of that matters.

Comment (ivanbakel) [reply src/librustc_typeck/check/writeback.rs]: Actually, on a second closer look, this just requires using `self_ty`, which *is* the correct unsized type, and not `method.sigs.inputs()[0]`, in that adjustment.

Comment (eddyb) [reply src/librustc_typeck/check/writeback.rs]: Unsizing coercions happen on references and raw/smart pointers, so you first have a borrow to get `&[T; N]` and then an unsizing of that reference to `&[T]`.

**Comment by ivanbakel** [comment]
Compiles, and from a little bit of `println` it does what I'd expect.

File: src/librustc_typeck/check/writeback.rs (hunk 4 above)
Comment (nikomatsakis) [reply src/librustc_typeck/check/writeback.rs]: @ivanbakel my point was that I would feel more comfortbale "skipping" the ref if we only did it when the coercion was an `Unsize` coercion -- i.e., I don't like deciding to skip based on the *type*, that feels like it could misfire and skip when we didn't expect.

Comment (ivanbakel) [reply src/librustc_typeck/check/writeback.rs]: What @eddyb said made me re-examine the behaviour, and this ref skip is always necessary, because it's always introduced in the indexing logic even without an `Unsize`. I've rewritten the code to reflect that. Let me know if you still have the same concern.

File: src/librustc_typeck/check/writeback.rs [hunk 5]
```diff
@@ -159,8 +160,52 @@ impl<'cx, 'gcx, 'tcx> WritebackCx<'cx, 'gcx, 'tcx> {
...
+                            match a.pop() {
+                                // Extra adjustment made when indexing causes a drop
+                                // of size information - we need to get rid of it
+                                // Since this is "after" the other adjustment to be
+                                // discarded, we do an extra `pop()`
+                                Some(Adjustment { kind: Adjust::Unsize, .. }) => {
+                                    // So the borrow discard actually happens here
+                                    a.pop();
+                                },
+                                _ => {}
```
Comment (nikomatsakis) [inline src/librustc_typeck/check/writeback.rs]: Can we add some kind of assertion here? That is, the adjustment we are popping, will it always be a ref adjustment or something similar?

**Review by nikomatsakis — COMMENTED** [review]
This looks much better. One last question is whether there is some form of assertion we can add that would be helpful.

File: src/librustc_typeck/check/writeback.rs (hunk 5 above)
Comment (nikomatsakis) [reply src/librustc_typeck/check/writeback.rs]: Eh, looking at the other cases, this looks similarly paranoid (or not paranoid). Seems fine.

**Comment by SimonSapin** [comment]
Is this change intended to reject during borrow-checking programs that were previously accepted? https://github.com/rust-lang/rust/issues/47349

**Comment by nikomatsakis** [comment]
Adding relnotes tag because, as @SimonSapin noted, this did cause a regression (https://github.com/rust-lang/rust/issues/47349), though it appears to be a genuine bug fix. In particular, I would summarize it as:

> The borrow checker was sometimes incorrectly permitting overlapping borrows around indexing operations (see #47349). This has been fixed (which also enabled some correct code that used to cause errors (e.g. #33903 and #46095).
