### PR TITLE
Point at enclosing match when expecting `()` in arm

### LINKED ISSUE #40799: Incorrect parser error when match statement is missing its ;
I found an analog of bug #40006 (Forty thousand bugs, you've gotta be kidding me! :D You've put in a lot of work there!) and @sanxiyn asked me to file my own report, so here it is.

If you don't put a ; at the end of a match block then the compiler tells you very unrelated things: https://play.rust-lang.org/?gist=ab74d4c0f3dce8c095f79469bc69b072&version=nightly&backtrace=0

### PR DESCRIPTION
**Pull request by estebank**
When encountering code like the following:

```rust
fn main() {
    match 3 {
        4 => 1,
        3 => {
            println!("Yep it maches.");
            2
        }
        _ => 2
    }
    println!("Bye!")
}
```

point at the enclosing `match` expression and suggest ignoring the
returned value:

```
error[E0308]: mismatched types
  --> $DIR/match-needing-semi.rs:8:13
   |
LL | /     match 3 {
LL | |         4 => 1,
LL | |         3 => {
LL | |             2
   | |             ^ expected (), found integer
LL | |         }
LL | |         _ => 2
LL | |     }
   | |     -- help: consider using a semicolon here
   | |_____|
   |       expected this to be `()`
   |
   = note: expected type `()`
              found type `{integer}
```

Fix #40799.

### CODE REVIEW

File: src/librustc/hir/map/mod.rs [hunk 1]
```diff
@@ -804,6 +804,27 @@ impl<'hir> Map<'hir> {
         }
     }
 
+    pub fn get_match_if_cause(&self, hir_id: HirId) -> Option<&Expr> {
```
Comment (Centril) [inline src/librustc/hir/map/mod.rs]: Could use a doc comment.

File: src/librustc_typeck/check/coercion.rs [hunk 2]
```diff
@@ -1163,18 +1163,20 @@ impl<'tcx, 'exprs, E: AsCoercionSite> CoerceMany<'tcx, 'exprs, E> {
...
-                                                  self.merged_ty(),
-                                                  expression,
-                                                  expression_ty),
-                    Expressions::UpFront(ref coercion_sites) =>
-                        fcx.try_find_coercion_lub(cause,
-                                                  &coercion_sites[0..self.pushed],
-                                                  self.merged_ty(),
-                                                  expression,
-                                                  expression_ty),
+                    Expressions::Dynamic(ref exprs) => fcx.try_find_coercion_lub(
```
Comment (Centril) [inline src/librustc_typeck/check/coercion.rs]: Btw, in general, I would leave rustfmt-ing alone since we will rustfmt the whole repo eventually anyways...

File: src/librustc_typeck/check/mod.rs [hunk 3]
```diff
@@ -3881,7 +3881,15 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
             hir::StmtKind::Item(_) => {}
             hir::StmtKind::Expr(ref expr) => {
                 // Check with expected type of `()`.
-                self.check_expr_has_type_or_error(&expr, self.tcx.mk_unit());
+
+                self.check_expr_has_type_or_error(&expr, self.tcx.mk_unit(), |err| {
+                    err.span_suggestion_short(
+                        expr.span.shrink_to_hi(),
+                        "consider using a semicolon here",
```
Comment (Centril) [inline src/librustc_typeck/check/mod.rs]: Would be good to refactor the suggestion into a method since you've used it twice in this PR. I have a feeling it's used elsewhere also.

**Comment by estebank** [comment]
Needs to be rebased on top of #64802.

File: src/librustc_typeck/check/coercion.rs [hunk 4]
```diff
@@ -1302,6 +1304,21 @@ impl<'tcx, 'exprs, E: AsCoercionSite> CoerceMany<'tcx, 'exprs, E> {
                 blk_id,
             );
             let parent = fcx.tcx.hir().get(parent_id);
+            if let (Some(match_expr), true, false) = (
+                fcx.tcx.hir().get_match_if_cause(expr.hir_id),
+                expected.is_unit(),
+                pointing_at_return_type,
+            ) {
+                if match_expr.span.desugaring_kind().is_none() {
+                    db.span_label(match_expr.span, "expected this to be `()`");
```
Comment (Centril) [inline src/librustc_typeck/check/coercion.rs]: Aside... we usually use the convention `err` instead of `db` -- would be good to fix for better readability.

File: src/test/ui/suggestions/match-needing-semi.fixed [hunk 5]
```diff
@@ -0,0 +1,18 @@
+// check-fail
```
Comment (Centril) [inline src/test/ui/suggestions/match-needing-semi.fixed]: There's no check-fail?

File: src/librustc_typeck/check/coercion.rs (hunk 2 above)
Comment (estebank) [reply src/librustc_typeck/check/coercion.rs]: Usually I do formatting close to the code I'm touching. Often during writing a PR I back out of a functional change but leave the formatting changes I made seeing them as a no-op that leaves the codebase a bit cleaner than before :)

I can certainly stop doing that.

Comment (Centril) [reply src/librustc_typeck/check/coercion.rs]: Not a big deal anyways =) I sometimes cannot resist the urge to format some myself so I should take my own advice. ;)

**Comment by Manishearth** [comment]
So this is breaking clippy tests since we rely on this span to test if for loops are coming from a macro. Might be able to work around this, but it could be tricky.

**Comment by Manishearth** [comment]
Ah, figured it out.

**Comment by estebank** [comment]
Cool!
