### PR TITLE
don't ICE when encountering an extern type field during validation

### LINKED ISSUE #126814: Internal Compiler Error when using extern types
code that caused the ICE: https://codeberg.org/binarycat/counted_str/src/commit/e04084bfcb9f33dcf5fc44ffb84ca3684e3496b6

backtrace: [rustc-ice-2024-06-21T21_39_57-71546.txt](https://github.com/user-attachments/files/15933977/rustc-ice-2024-06-21T21_39_57-71546.txt)

### PR DESCRIPTION
**Pull request by RalfJung**
"extern type" is a pain that keeps on giving...

Fixes https://github.com/rust-lang/rust/issues/126814

r? @oli-obk

### CODE REVIEW

File: compiler/rustc_const_eval/src/errors.rs [hunk 1]
```diff
@@ -425,7 +425,7 @@ pub struct ValidationFailure {
     #[primary_span]
     pub span: Span,
     #[note(const_eval_validation_failure_note)]
-    pub ub_note: Option<()>,
+    pub ub_note: (),
```
Comment (RalfJung) [inline compiler/rustc_const_eval/src/errors.rs:428]: There's probably something else that should be done instead of a `()` field here...? I don't know enough about our diagnostics stuff, unfortunately.

Comment (compiler-errors) [reply compiler/rustc_const_eval/src/errors.rs:428]: `()` is fine. You could put `#[note]` on the struct itself but it changes the ordering of the labels/notes.

**Review by compiler-errors — APPROVED** [review]

**Comment by compiler-errors** [comment]
r? compiler-errors @bors r+ rollup
