### PR TITLE
save-analysis: Fix ICE when processing associated constant

### LINKED ISSUE #59134: RLS ICE: "node_type: no type for node" when building bitflags
When using this branch of bitflags: https://github.com/bitflags/bitflags/pull/172 through a patch in a local directory rls crashes with the following errors:

```
{"message":"src/librustc/ty/context.rs:539: node_type: no type for node `expr <Self>::IDENTITY (id=18847)`","code":null,"level":"error: internal compiler error","spans":[],"children":[],"rendered":"error: internal compiler error: src/librustc/ty/context.rs:539: node_type: no type for node `expr <Self>::IDENTITY (id=18847)`\n\n"}
thread 'rustc' panicked at 'Box<Any>', src/librustc_errors/lib.rs:635:9
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
{"message":"aborting due to previous error","code":null,"level":"error","spans":[],"children":[],"rendered":"error: aborting due to previous error\n\n"}

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.35.0-nightly (e68bf8ae1 2019-03-11) running on x86_64-unknown-linux-gnu

note: compiler flags: -C opt-level=3 -C codegen-units=16 -C debuginfo=2 -C debug-assertions=on --crate-type lib

note: some of the compiler flags provided by cargo are hidden

{"message":"src/librustc/ty/context.rs:539: node_type: no type for node `expr <Self>::Shift (id=43075)`","code":null,"level":"error: internal compiler error","spans":[],"children":[],"rendered":"error: internal compiler error: src/librustc/ty/context.rs:539: node_type: no type for node `expr <Self>::Shift (id=43075)`\n\n"}
thread 'rustc' panicked at 'Box<Any>', src/librustc_errors/lib.rs:635:9
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
{"message":"aborting due to previous error","code":null,"level":"error","spans":[],"children":[],"rendered":"error: aborting due to previous error\n\n"}

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.35.0-nightly (e68bf8ae1 2019-03-11) running on x86_64-unknown-linux-gnu

note: compiler flags: -C opt-level=3 -C codegen-units=16 -C debuginfo=2 -C debug-assertions=on --crate-type lib

note: some of the compiler flags provided by cargo are hidden

{"message":"src/librustc/ty/context.rs:539: node_type: no type for node `expr <Self>::ZIGZAG_SUBDIVISION (id=144317)`","code":null,"level":"error: internal compiler error","spans":[],"children":[],"rendered":"error: internal compiler error: src/librustc/ty/context.rs:539: node_type: no type for node `expr <Self>::ZIGZAG_SUBDIVISION (id=144317)`\n\n"}
thread 'rustc' panicked at 'Box<Any>', src/librustc_errors/lib.rs:635:9
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
thread 'rustc' panicked at 'Box<Any>', src/librustc_errors/lib.rs:635:9
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.35.0-nightly (e68bf8ae1 2019-03-11) running on x86_64-unknown-linux-gnu

{"message":"aborting due to previous error","code":null,"level":"error","spans":[],"children":[],"rendered":"error: aborting due to previous error\n\n"}

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.35.0-nightly (e68bf8ae1 2019-03-11) running on x86_64-unknown-linux-gnu

note: compiler flags: -C opt-level=3 -C codegen-units=16 -C debuginfo=2 -C debug-assertions=on --crate-type lib

note: some of the compiler flags provided by cargo are hidden
```

### PR DESCRIPTION
**Pull request by Xanewok**
Closes #59134 
Closes https://github.com/rust-lang/rls/issues/1449

Thanks @swgillespie for helping tracking this down and fixing it!

r? @eddyb

### CODE REVIEW

**Comment by Xanewok** [comment]
@rust-lang/infra this fixes a widespread ICE (any crate that transitively depends on bitflags 1.0.5, which is quite a few, currently yanked for this reason) in the RLS - any chance this can be backported to stable or at least to beta?

cc @KodrAus

**Comment by KodrAus** [comment]
A back port to `beta` sounds good to me, I’m also happy to just sit on our current `master` branch in `bitflags` for a while until it is available on the latest `stable`.

**Comment by Centril** [comment]
cc @rust-lang/compiler @rust-lang/release 

Beta & stable nominating based on https://github.com/rust-lang/rust/pull/60649#issuecomment-490674756.

File: src/librustc_save_analysis/dump_visitor.rs [hunk 1]
```diff
@@ -463,10 +463,12 @@ impl<'l, 'tcx: 'l, 'll, O: DumpOutput + 'll> DumpVisitor<'l, 'tcx, 'll, O> {
         }
 
         // walk type and init value
-        self.visit_ty(typ);
-        if let Some(expr) = expr {
-            self.visit_expr(expr);
-        }
+        self.nest_tables(id, |v| {
```
Comment (oli-obk) [inline src/librustc_save_analysis/dump_visitor.rs]: `nest_tables` is used inconsistently in this file. The type of constant and static items is inside the `nest_tables` closure, while the return type for function items is outside. I don't think it's a problem for function/const/static items, since they all have their own generics, but e.g. an associated constant's type can depend on associated types.

I think the `visit_ty` should be outside the `nest_tables`, but I'm not sure it changes anything. The following test should expose any lingering problems I think.

```rust
pub fn g() {
    trait Sup {
        type Assoc;
    }
    trait Trait: Sup {}
    impl Trait {
        const FLAG: <Self as Sup>::Assoc = bogus.field;
    }
}
```

alternatively try


```rust
pub fn g() {
    trait Trait {}
    impl<T> Trait {
        const FLAG: T = bogus.field;
    }
}
```

**Comment by pietroalbini** [comment]
Note that a point release is likely not going to happen. We're two weeks from the next release and since this isn't merged yet the most likely target is May 16th, one week before 1.35 is out.

File: src/librustc_save_analysis/dump_visitor.rs (hunk 1 above)
Comment (Xanewok) [reply src/librustc_save_analysis/dump_visitor.rs]: @oli-obk when `visit_ty` was outside `nest_tables`, the snippet in https://github.com/rust-lang/rust/issues/59134#issuecomment-490655542 still ICE'd, so I believe we should nest the tables when visiting assoc const's type as well?

**Comment by Xanewok** [comment]
@pietroalbini ah, my release math was way off, sorry. Assuming this will be merged soon, is beta backport still on the table?

**Comment by pietroalbini** [comment]
Yep, the deadline for beta backports to be merged is Sunday 19th.

File: src/librustc_save_analysis/dump_visitor.rs (hunk 1 above)
Comment (oli-obk) [reply src/librustc_save_analysis/dump_visitor.rs]: Hmm... I just looked through this file and couldn't find any place where trait items are wrapped in `nest_tables` with the id of the impl block or trait block. I think https://github.com/rust-lang/rust/blob/bf36208a10f5bd06a2cf3f35d8f92e43e3ec4fb3/src/librustc_save_analysis/dump_visitor.rs#L765-L768 should have a `nest_tables` with the id of the impl/trait block. The same for https://github.com/rust-lang/rust/blob/bf36208a10f5bd06a2cf3f35d8f92e43e3ec4fb3/src/librustc_save_analysis/dump_visitor.rs#L684-L687

Once that has been done, it should be possible to just wrap the constant body in `nest_tables` here

**Comment by Xanewok** [comment]
Added a test for both ICEs (when processing const with associated type and when processing assoc const with bogus field access).
I tried to apply the patch from https://github.com/rust-lang/rust/pull/60649#discussion_r282414537 but it didn't fix the ICEs so didn't include it here.

**Comment by nikomatsakis** [comment]
Discussed in compiler meeting. Marking as beta-accepted.

**Comment by nikomatsakis** [comment]
Seems like a point release won't happen, so we didn't discuss that.

**Comment by Xanewok** [comment]
I'll drop the stable-nominated label then

**Comment by mouse07410** [comment]
Pardon a naive question, but when can we hope to see this fix added to the stable...!

**Comment by lzutao** [comment]
@mouse07410 Probably next stable, 1.35.

**Comment by Xanewok** [comment]
@oli-obk what do you think?
