### PR TITLE
rustc_mir: don't build unused unwind cleanup blocks

### LINKED ISSUE #43511: 25% regression in compile time of issue-20936-deep-vector benchmark
[According to perf.rust-lang.org](https://perf.rust-lang.org/graphs.html?start=2017-06-15T00%3A00%3A00%2B00%3A00&end=2017-06-22T00%3A00%3A00%2B00%3A00&crates=%7B%22list%22%3A%22List%22%2C%22content%22%3A%5B%22issue-20936-deep-vector%22%5D%7D&phases=%7B%22list%22%3A%22All%22%2C%22content%22%3Anull%7D&group_by=crate&type=time&yaxis=pct) this benchmarked experienced a >25% regressoin in compile time due to https://github.com/rust-lang/rust/pull/39409

Seems bad!

cc @pnkfelix, @rust-lang/compiler

### PR DESCRIPTION
**Pull request by arielb1**
When building a scope exit, don't build unwind cleanup blocks unless they will actually be used by the unwind path of a drop - the unused blocks are removed by SimplifyCfg, but they can cause a significant performance slowdown before they are removed. That fixes #43511.

Also a few other small MIR cleanups & optimizations.

r? @eddyb

### CODE REVIEW

**Comment by eddyb** [comment]
r=me with the Travis build fixed

File: src/librustc_mir/build/scope.rs [hunk 1]
```diff
@@ -366,6 +383,15 @@ impl<'a, 'gcx, 'tcx> Builder<'a, 'gcx, 'tcx> {
         let len = self.scopes.len();
         assert!(scope_count < len, "should not use `exit_scope` to pop ALL scopes");
         let tmp = self.get_unit_temp();
+
+        // If we are emitting a `drop` statement, we need to have the cached
+        // diverge cleanup pads ready in case that drop panics.
+        let may_panic =
+            self.scopes[(len - scope_count)..].iter().any(|s| s.drops.iter().any(|s| s.kind.may_panic()));
```
Comment (kennytm) [inline src/librustc_mir/build/scope.rs]: This line is >100 chars, failing `tidy`. (I consider a for-loop + break is easier to read here.)

```
[00:03:50] tidy error: /checkout/src/librustc_mir/build/scope.rs:390: line longer than 100 chars
[00:03:51] some tidy checks failed
```
