### PR TITLE
Expand Attributes on Statements and Expressions

### LINKED ISSUE #41475: Attribute macros can't be applied to statements
If `my_attr` is an attribute proc macro which otherwise resolves in a given context, 
`#[my_attr] let foo: i32;` will fail to resolve. 

I'm on mobile because my home internet is down so I can't really provide a better example. Will update later if necessary. 

cc @jseyfried

### LINKED ISSUE #43988: Known but incorrect attributes over statements/expressions are ignored.
I tried to look for this, but I couldn't find an existing issue. Or is this expected behaviour?

Putting attributes that exist (though the arguments can be bogus) seem to be ignored when one would expect an error, or at least a warning. E.g like this: 
```rust
#[repr(bogus_statement)]
let x = 0;
```

or 
```rust
#[inline(bogus_statement)]
let x = 0;
```

This seems to be the case on stable, beta and nightly.

More examples here: https://play.rust-lang.org/?gist=b48bfc076d29c770d8d2c81f2f99f0bb

### PR DESCRIPTION
**Pull request by abonander**
This enables attribute-macro expansion on statements and expressions while retaining the `stmt_expr_attributes` feature requirement for attributes on expressions.

closes #41475 
cc #38356  @petrochenkov @jseyfried 
r? @nrc

### CODE REVIEW

**Comment by abonander** [comment]
This is the error that doesn't make any sense (others are breakages that I haven't fixed cause I've only been running the one test): https://travis-ci.org/rust-lang/rust/builds/354876674#L2899

The only attribute being expanded is `#[expect_let]` which should be returning the statement verbatim.

**Comment by abonander** [comment]
I understand the problem now.

**Comment by nrc** [comment]
Looks fine to me, but I'm somewhat out of touch with the compiler nowadays.

r? @petrochenkov

**Comment by abonander** [comment]
Turns out #43988 isn't related to this bit of the code.

**Comment by abonander** [comment]
@petrochenkov Squashed and ready for review.

**Comment by petrochenkov** [comment]
I'll likely leave this until weekend.

**Comment by petrochenkov** [comment]
Also, Travis fails
>[00:45:12] failures:
>[00:45:12]     [ui] ui/feature-gate-stmt_expr_attributes.rs

**Comment by abonander** [comment]
Oh yeah that's because I changed the error message since attributes on statements are stable.

**Comment by abonander** [comment]
@petrochenkov build is green

**Comment by pietroalbini** [comment]
Ping from triage @petrochenkov! This PR still needs your review.

**Comment by petrochenkov** [comment]
I'd like to see a couple more compile fail tests:
- Expression attribute expanding into 0 or >1 expressions in a position where such expansion is not supported.
- Attribute expanding into 0 or >1 things applied to a trailing expression/statement in a block.

r=me after adding those tests

**Comment by TimNN** [comment]
Your PR [failed on Travis](https://travis-ci.org/rust-lang/rust/jobs/360785081). Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.

<details><summary><i>Click to expand the log.</i></summary>

```plain
[00:00:42] configure: rust.quiet-tests     := True
---
[00:35:42] .........................................................................i..........................
[00:35:48] ................i...................................................................................
---
[00:36:21] ............................................................................................i.......
[00:36:27] ................................................................i...................................
---
[00:37:17] .............................................i......................................................
---
[00:40:47] .............................i......................................................................
[00:41:00] ..............................................................i.....................................
[00:41:15] ...............................................i....................................................
[00:41:33] ....................................................................................................
[00:41:53] ....................................................................................................
[00:42:12] ....................................................................................................
[00:42:35] .i................................................................................................i.
[00:43:05] ..............................................................................................test [run-pass] run-pass/mir_heavy_promoted.rs has been running for over 60 seconds
[00:43:08] ......
[00:43:35] ....................................................................................................
[00:44:07] ...............................................................ii...................................
[00:44:52] ..........................i....................................................i.ii.................
[00:45:28] .......................................................................................iiiiiii......
---
[00:47:20] ....................................i...............................................................
[00:47:27] ....................................................................................................
[00:47:34] ..................i............................................................ii.iii...............
[00:47:41] ....................................................................................................
[00:47:48] ........i..............................i............................................................
[00:47:55] ....................................................................................................
[00:48:02] .....................i..............................................................................
[00:48:09] ....................................................................................................
[00:48:19] ....................................................................................................
[00:48:28] ....................................................................................................
[00:48:38] ....................................................................................................
[00:48:50] ....................................................................................................
[00:48:58] ..............i.....................................................................................
[00:49:07] .................i..ii..............................................................................
[00:49:16] ....................................................................................................
[00:49:25] ....................................................................................................
[00:49:34] ....................................................................................i...............
[00:49:44] ..............................i.....................................................................
---
[00:50:18] ............................i.......................................................................
[00:50:20] ....................................................................i...............................
[00:50:21] .................i......................................................
---
[00:50:34] ...........i........................
---
[00:51:03] i...i..ii....i.............ii........iii......i..i...i...ii..i..i..ii.....
---
[00:51:06] i.......i......................i......
---
[00:51:40] iiii.......i..i........i..i.i.............i..........iiii...........i...i..........ii.i.i.......ii..
[00:51:41] ....ii...
---
[00:56:01] ..................F....F...........................
[00:56:01] failures:
[00:56:01] thread 'main' panicked at 'Some tests failed', tools/compiletest/src/main.rs:478:22
[00:56:01]
[00:56:01] ---- [compile-fail] compile-fail-fulldeps/proc-macro/attr-invalid-exprs.rs stdout ----
[00:56:01]
[00:56:01] error: /checkout/src/test/compile-fail-fulldeps/proc-macro/attr-invalid-exprs.rs:22: unexpected error: '22:13: 22:25: attributes on expressions are experimental. (see issue #15701) [E0658]'
[00:56:01]
[00:56:01] error: /checkout/src/test/compile-fail-fulldeps/proc-macro/attr-invalid-exprs.rs:25: unexpected error: '25:5: 25:17: attributes on expressions are experimental. (see issue #15701) [E0658]'
[00:56:01]
[00:56:01] error: /checkout/src/test/compile-fail-fulldeps/proc-macro/attr-invalid-exprs.rs:25: unexpected error: '25:5: 25:17: macro expansion ignores token `,` and any following'
[00:56:01]
[00:56:01] error: /checkout/src/test/compile-fail-fulldeps/proc-macro/attr-invalid-exprs.rs:22: expected error not found: asdf
[00:56:01]
[00:56:01] error: /(
[00:56:01]             Error
[00:56:01]         ),
[00:56:01]         msg: "34:5: 34:17: attributes on expressions are experimental. (see issue #15701) [E0658]"
---
[00:56:01]         msg: "34:5: 34:17: add #![feature(stmt_expr_attributes)] to the crate attributes to enable"
---
[00:56:01]         msg: "attributes on expressions are experimental"
---
[00:56:01]         msg: "add #![feature(stmt_expr_attributes)] to the crate attributes to enable"
[00:56:01]     }
[00:56:01] ]
[00:56:01]
[00:56:01] thread '[compile-fail] compile-fail-fulldeps/proc-macro/attr-stmt-expr.rs' panicked at 'explicit panic', tools/compiletest/src/runtest.rs:1253:13
---
$ cat obj/tmp/sccache.log
```

</details><p></p>

I'm a bot! I can only do what humans tell me to, so if this was not helpful or you have suggestions for improvements, please ping or otherwise contact **`@TimNN`**.

**Comment by abonander** [comment]
@TimNN suggestion: only send a message if the user doesn't push another commit within X hours. I'm watching these builds and I know how to interpret them so the bot's not really adding anything.

**Comment by TimNN** [comment]
@abonander: Thanks for the feedback, I'll look into implementing something like that.

File: src/test/compile-fail-fulldeps/proc-macro/attr-invalid-exprs.rs [hunk 1]
```diff
@@ -0,0 +1,27 @@
...
+#![feature(proc_macro, stmt_expr_attributes)]
+
+extern crate attr_stmt_expr;
+use attr_stmt_expr::duplicate;
+
+fn main() {
+    let _ = #[no_output] "Hello, world!";
+    //~^ ERROR asdf
+
+    let _ = #[duplicate] "Hello, world!";
```
Comment (abonander) [inline src/test/compile-fail-fulldeps/proc-macro/attr-invalid-exprs.rs]: @petrochenkov 
https://travis-ci.org/rust-lang/rust/builds/360794617#L1905
> 25:13: 25:25: macro expansion ignores token `,` and any following

So it seems that the parser currently doesn't support directly expanding into >1 expressions.

File: src/test/compile-fail-fulldeps/proc-macro/attr-invalid-exprs.rs [hunk 2]
```diff
@@ -0,0 +1,27 @@
...
+
+//! Attributes producing expressions in invalid locations
+
+#![feature(proc_macro, stmt_expr_attributes)]
+
+extern crate attr_stmt_expr;
+use attr_stmt_expr::duplicate;
+
+fn main() {
+    let _ = #[no_output] "Hello, world!";
```
Comment (abonander) [inline src/test/compile-fail-fulldeps/proc-macro/attr-invalid-exprs.rs]: This didn't produce an error, which is concerning.

Comment (abonander) [reply src/test/compile-fail-fulldeps/proc-macro/attr-invalid-exprs.rs]: Nevermind, it hits later than the other one, but the UX is pretty bad:

    1:1: 1:1: expected expression, found `<eof>`

Comment (abonander) [reply src/test/compile-fail-fulldeps/proc-macro/attr-invalid-exprs.rs]: Either that, or just re-span the parse error. That'd probably be easier.

**Comment by petrochenkov** [comment]
Still needs a test for

>Attribute expanding into 0 or >1 things applied to a trailing expression/statement in a block.

\+ squashing + green Travis.
Possibly suboptimal diagnostics for tests from https://github.com/rust-lang/rust/pull/49124#issuecomment-376630945 are okay.

@bors delegate+

**Comment by abonander** [comment]
I'm at least gonna try to get it to point to the problematic invocation. The current error message has a dummy span.

**Comment by TimNN** [comment]
Your PR [failed on Travis](https://travis-ci.org/rust-lang/rust/jobs/360997605). Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.

<details><summary><i>Click to expand the log.</i></summary>

```plain
Resolving deltas: 100% (613643/613643), completed with 4863 local objects.
---
[00:00:29] configure: rust.quiet-tests     := True
---
[00:38:45] .........................................................................i..........................
[00:38:51] ................i...................................................................................
---
[00:39:26] ............................................................................................i.......
[00:39:33] ................................................................i...................................
---
[00:40:26] .............................................i......................................................
---
[00:44:13] .............................i......................................................................
[00:44:27] ..............................................................i.....................................
[00:44:42] ...............................................i....................................................
[00:45:02] ....................................................................................................
[00:45:23] ....................................................................................................
[00:45:44] ....................................................................................................
[00:46:08] .i................................................................................................i.
[00:46:36] .....................................................................................test [run-pass] run-pass/mir_heavy_promoted.rs has been running for over 60 seconds
[00:46:44] ...............
[00:47:14] ....................................................................................................
[00:47:49] ...............................................................ii...................................
[00:48:34] ..........................i....................................................i.ii......test [run-pass] run-pass/saturating-float-casts.rs has been running for over 60 seconds
[00:48:38] ...........
[00:49:17] .......................................................................................iiiiiii......
---
[00:51:17] ....................................i...............................................................
[00:51:24] ....................................................................................................
[00:51:32] ..................i............................................................ii.iii...............
[00:51:39] ....................................................................................................
[00:51:47] ........i..............................i............................................................
[00:51:54] ....................................................................................................
[00:52:01] .....................i..............................................................................
[00:52:09] ....................................................................................................
[00:52:18] ....................................................................................................
[00:52:28] ....................................................................................................
[00:52:39] ....................................................................................................
[00:52:53] ....................................................................................................
[00:53:01] ..............i.....................................................................................
[00:53:11] .................i..ii..............................................................................
[00:53:20] ....................................................................................................
[00:53:31] ....................................................................................................
[00:53:40] ....................................................................................i...............
[00:53:50] ..............................i.....................................................................
---
[00:54:27] ...........................i........................................................................
[00:54:28] ....................................................................i...............................
[00:54:30] ................i.......................................................
---
[00:54:44] ...........i........................
---
[00:55:14] i...i..ii....i.............ii........iii......i..i...i...ii..i..i..ii.....
---
[00:55:17] i.......i......................i......
---
[00:55:54] iiii.......i..i........i..i.i.............i..........iiii...........i...i..........ii.i.i.......ii..
[00:55:55] ....ii...
---
[01:01:05] ...................F...............................
[01:01:05] failures:
[01:01:05]
[01:01:05] ---- [compile-fail] compile-fail-fulldeps/proc-macro/attr-invalid-exprs.rs stdout ----
[01:01:05]
[01:01:05] error: /checkout/src/test/compile-fail-fulldeps/proc-macro/attr-invalid-exprs.rs:25: unexpected error: '25:13: 25:25: macro expansion ignores token `,` and any following'
[01:01:05]
[01:01:05] error: 1 unexpected errors found, 0 expected errors not found
[01:01:05] status: exit code: 101
[01:01:05] command: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc" "/checkout/src/test/compile-fail-fulldeps/proc-macro/attr-invalid-exprs.rs" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/compile-fail-fulldeps" "--target=x86_64-unknown-linux-gnu" "--error-format" "json" "-Zui-testing" "-C" "prefer-dynamic" "-o" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/compile-fail-fulldeps/proc-macro/attr-invalid-exprs.stage2-x86_64-unknown-linux-gnu" "-Crpath" "-O" "-Zmiri" "-Zunstable-options" "-Lnative=/checkout/obj/build/x86_64-unknown-linux-gnle-fail-fulldeps" "--stage-id" "stage2-x86_64-unknown-linux-gnu" "--mode" "compile-fail" "--target" "x86_64-unknown-linux-gnu" "--host" "x86_64-unknown-linux-gnu" "--llvm-filecheck" "/usr/lib/llvm-3.9/bin/FileCheck" "--host-rustcflags" "-Crpath -O -Zmiri -Zunstable-options " "--target-rustcflags" "-Crpath -O -Zmiri -Zunstable-options  -Lnative=/checkout/obj/build/x86_64-unknown-linux-gnu/native/rust-test-helpers" "--docck-python" "/usr/bin/python2.7" "--lldb-python" "/usr/bin/python2.7" "--gdb" "/usr/bin/gdb" "--quiet" "--llvm-version" "3.9.1\n" "--system-llvm" "--cc" "" "--cxx" "" "--cflags" "" "--llvm-components" "" "--llvm-cxxflags" "" "--adb-path" "adb" "--adb-test-dir" "/data/tmp/work" "--android-cross-path" "" "--color" "always"
[01:01:05] expected success, got: exit code: 101
[01:01:05]
[01:01:05]
[01:01:05] failed to run: /checkout/obj/build/bootstrap/debug/bootstrap test
[01:01:05] Build completed unsuccessfully in 0:23:10
[01:01:05] make: *** [check] Error 1
[01:01:05] Makefile:58: recipe for target 'check' failed
---
$ cat obj/tmp/sccache.log
```

</details><p></p>

I'm a bot! I can only do what humans tell me to, so if this was not helpful or you have suggestions for improvements, please ping or otherwise contact **`@TimNN`**.

**Comment by TimNN** [comment]
Your PR [failed on Travis](https://travis-ci.org/rust-lang/rust/jobs/361028376). Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.

<details><summary><i>Click to expand the log.</i></summary>

```plain
Resolving deltas: 100% (613649/613649), completed with 4863 local objects.
---
[00:00:45] configure: rust.quiet-tests     := True
---
[00:43:18] .........................................................................i..........................
[00:43:24] ................i...................................................................................
---
[00:44:01] ............................................................................................i.......
[00:44:08] ................................................................i...................................
---
[00:45:05] .............................................i......................................................
---
[00:49:07] .............................i......................................................................
[00:49:22] ..............................................................i.....................................
[00:49:38] ...............................................i....................................................
[00:49:59] ....................................................................................................
[00:50:22] ....................................................................................................
[00:50:44] ....................................................................................................
[00:51:10] .i................................................................................................i.
[00:51:35] ............................................................................test [run-pass] run-pass/mir_heavy_promoted.rs has been running for over 60 seconds
[00:51:48] ........................
[00:52:20] ....................................................................................................
[00:52:57] ...............................................................ii...................................
[00:53:42] ..........................i....................................................i.iitest [run-pass] run-pass/saturating-float-casts.rs has been running for over 60 seconds
[00:53:48] .................
[00:54:30] .......................................................................................iiiiiii......
---
[00:56:32] ....................................i...............................................................
[00:56:40] ....................................................................................................
[00:56:48] ..................i............................................................ii.iii...............
[00:56:55] ....................................................................................................
[00:57:03] ........i..............................i............................................................
[00:57:11] ....................................................................................................
[00:57:18] .....................i..............................................................................
[00:57:26] ....................................................................................................
[00:57:37] ....................................................................................................
[00:57:47] ....................................................................................................
[00:57:58] ....................................................................................................
[00:58:12] ....................................................................................................
[00:58:22] ..............i.....................................................................................
[00:58:32] .................i..ii..............................................................................
[00:58:42] ....................................................................................................
[00:58:53] ....................................................................................................
[00:59:02] ....................................................................................i...............
[00:59:13] ..............................i.....................................................................
---
[00:59:51] ............................i.......................................................................
[00:59:53] ....................................................................i...............................
[00:59:54] ................i.......................................................
---
[01:00:09] ...........i........................
---
[01:00:41] i...i..ii....i.............ii........iii......i..i...i...ii..i..i..ii.....
---
[01:00:44] i.......i......................i......
---
[01:01:23] iiii.......i..i........i..i.i.............i..........iiii...........i...i..........ii.i.i.......ii..
[01:01:24] ....ii...
---
est/compile-fail-fulldeps/proc-macro/attr-invalid-exprs.stage2-x86_64-unknown-linux-gnu" "-Crpath" "-O" "-Zmiri" "-Zunstable-options" "-Lnative=/checkout/obj/build/x86_64-unknown-linux-gnu/native/rust-test-helpers" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/compile-fail-fulldeps/proc-macro/attr-invalid-exprs.stage2-x86_64-unknown-linux-gnu.aux" "-A" "unused"
[01:07:07] unexpected errors (from JSON output): [
[01:07:07]     Error {
[01:07:07]         line_num: 34,
[01:07:07]         kind: Some(
[01:07:07]             Error
[01:07:07]         ),
[01:07:07]         msg: "34:9: 34:21: macro expansion ignores token `,` and any following"
---
[01:07:07]         msg: "macro expansion ignores token `,` and any following"
[01:07:07]     }
[01:07:07] ]
[01:07:07]
[01:07:07] thread '[compile-fail] compile-fail-fulldeps/proc-macro/attr-invalid-exprs.rs' panicked at 'explicit panic', tools/compiletest/src/runtest.rs:1253:13
---
[01:07:07] thread 'main' panicked at 'Some tests failed', tools/compiletest/src/main.rs:478:22
[01:07:07] command did not execute successfully: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-tools-bin/compiletest" "--compile-lib-path" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/lib" "--run-lib-path" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/lib/rustlib/x86_64-unknown-linux-gnu/lib" "--rustc-path" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc" "--src-base" "/checkout/src/test/compile-fail-fulldeps" "--build-base" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/compile-fail-fulldeps" "--stage-id" "stage2-x86_64-unknown-linux-gnu" "--mode" "compile-fail" "--target" "x86_64-unknown-linux-gnu" "--host" "x86_64-unknown-linux-gnu" "--llvm-filecheck" "/usr/lib/llvm-3.9/bin/FileCheck" "--host-rustcflags" "-Crpath -O -Zmiri -Zunstable-options " "--target-rustcflags" "-Crpath -O -Zmiri -Zunstable-options  -Lnative=/checkout/obj/build/x86_64-unknown-linux-gnu/native/rust-test-helpers" "--docck-python" "/usr/bin/python2.7" "--lldb-python" "/usr/bin/python2.7" "--gdb" "/usr/bin/gdb" "--quiet" "--llvm-version" "3.9.1\n" "--system-llvm" "--cc" "" "--cxx" "" "--cflags" "" "--llvm-components" "" "--llvm-cxxflags" "" "--adb-path" "adb" "--adb-test-dir" "/data/tmp/work" "--android-cross-path" "" "--color" "always"
[01:07:07] expected success, got: exit code: 101
[01:07:07]
[01:07:07]
[01:07:07] failed to run: /checkout/obj/build/bootstrap/debug/bootstrap test
[01:07:07] Build completed unsuccessfully in 0:24:48
[01:07:07] Makefile:58: recipe for target 'check' failed
[01:07:07] make: *** [check] Error 1
/incremental/bootstrap-1xj36c8o119z7
113580 ./obj/build/bootstrap/debug/incremental/bootstrap-1xj36c8o119z7/s-ezq7nnjkjd-1qawgcj-1qldka3x57wek
112704 ./obj/build/x86_64-unknown-linux-gnu/test/mir-opt
108032 ./obj/build/x86_64-unknown-linux-gnu/stage0/lib/rustlib/x86_64-unknown-linux-gnu/codegen-backends
102612 ./obj/build/x86_64-unknown-linux-gnu/stage1-std/x86_64-unknown-linux-gnu/release/incremental/core-1sv8kuz0m8z0z
102608 ./obj/build/x86_64-unknown-linux-gnu/stage1-std/x86_64-unknown-linux-gnu/release/incremental/core-1sv8kuz0m8z0z/s-ezq8pbn7od-17kdcob-mx3hb8bwcwpv
---
$ cat obj/tmp/sccache.log
---
$ ls -lat $HOME/Library/Logs/DiagnosticReports/
ls: cannot access /home/travis/Library/Logs/DiagnosticReports/: No such file or directory
travis_time:end:0d961061:start=1522636287567666826,finish=1522636287574938720,duration=7271894
travis_fold:end:after_failure.4
travis_fold:start:after_failure.5
travis_time:start:1450e71c
$ find $HOME/Library/Logs/DiagnosticReports -type f -name '*.crash' -not -name '*.stage2-*.crash' -not -name 'com.apple.CoreSimulator.CoreSimulatorService-*.crash' -exec printf travis_fold":start:crashlog\n\033[31;1m%s\033[0m\n" {} \; -exec head -750 {} \; -exec echo travis_fold":"end:crashlog \; || true
find: `/home/travis/Library/Logs/DiagnosticReports': No such file or directory
travis_time:end:1450e71c:start=1522636287581513151,finish=1522636287588508769,duration=6995618
travis_fold:end:after_failure.5
travis_fold:start:after_failure.6
travis_time:start:01a41bcb
$ dmesg | grep -i kill
[   10.954591] init: failsafe main process (1094) killed by TERM signal
```

</details><p></p>

I'm a bot! I can only do what humans tell me to, so if this was not helpful or you have suggestions for improvements, please ping or otherwise contact **`@TimNN`**.

File: src/test/compile-fail-fulldeps/proc-macro/attr-invalid-exprs.rs [hunk 3]
```diff
@@ -0,0 +1,38 @@
...
+    //~^ ERROR expected expression, found `<eof>`
+
+    let _ = #[duplicate] "Hello, world!";
+    //~^ ERROR macro expansion ignores token `,` and any following
+
+    let _ = {
+        #[no_output]
+        "Hello, world!"
```
Comment (petrochenkov) [inline src/test/compile-fail-fulldeps/proc-macro/attr-invalid-exprs.rs]: So, you can cfg-out a trailing expression and implicit `()` will be used instead? Fun.
At least this is consistent with existing behavior of `#[cfg]`.

Comment (abonander) [reply src/test/compile-fail-fulldeps/proc-macro/attr-invalid-exprs.rs]: I think that's just the behavior of an empty block, no?

Comment (abonander) [reply src/test/compile-fail-fulldeps/proc-macro/attr-invalid-exprs.rs]: https://play.rust-lang.org/?gist=46ec7b69960efe58ea7e55a8c05159cd&version=stable
