### PR TITLE
Fix the span of generated `#[derive_*]` attributes

### LINKED ISSUE #33571: The error message for trying to derive an unsafe trait impl doesn't mention the trait name
I tried to derive every possible trait on an enum and received this error:

```
enum-derive.rs:3:1: 3:112 note: in this expansion of #[derive] (defined in enum-derive.rs)
enum-derive.rs:3:1: 3:112 error: this unsafe trait should be implemented explicitly
enum-derive.rs:3 #[derive(PartialEq, PartialOrd, Clone, Copy, Hash, RustcEncodable, RustcDecodable, Eq, Ord, Debug, Send, Sync)]
                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

which isn't as helpful as it could be because it doesn't tell me which of the traits is the one it's complaining about.

### PR DESCRIPTION
**Pull request by jseyfried**
Fixes #33571.
r? @nrc

### CODE REVIEW

**Comment by jseyfried** [comment]
c.f. #32791 (specifically [this commit](https://github.com/rust-lang/rust/pull/32791/commits/03ab057f97910769846f06ef904eb3eedc20134e)), which caused #33571.
cc @nikomatsakis @LeoTestard

File: src/libsyntax_ext/deriving/mod.rs [hunk 1]
```diff
@@ -158,6 +139,35 @@ fn expand_derive(cx: &mut ExtCtxt,
...
+                // `$attr == deriving(Eq)`. In that case, the
+                // "#[structural_match]" would be considered to
+                // originate not from the deriving call but from
+                // text outside the deriving call, and hence would
+                // be forbidden from using unstable
+                // content.
+                //
+                // See tests src/run-pass/rfc1445 for
+                // examples. --nmatsakis
+                let span = Span { expn_id: cx.backtrace(), .. span };
```
Comment (LeoTestard) [inline src/libsyntax_ext/deriving/mod.rs]: Why is it still necessary to have a special case for the `PartialEq` and `Eq` traits? Is the span generated in the loop above not sufficient?

Comment (jseyfried) [inline src/libsyntax_ext/deriving/mod.rs]: Good point, fixed.

File: src/libsyntax_ext/deriving/mod.rs [hunk 2]
```diff
@@ -131,48 +125,26 @@ fn expand_derive(cx: &mut ExtCtxt,
...
-                // inherit the "allows unstable" from the
-                // backtrace.  But in fact this is not always the
-                // case. The actual source text that led to
-                // deriving can be `#[$attr]`, for example, where
-                // `$attr == deriving(Eq)`. In that case, the
-                // "#[structural_match]" would be considered to
-                // originate not from the deriving call but from
-                // text outside the deriving call, and hence would
-                // be forbidden from using unstable
-                // content.
```
Comment (LeoTestard) [inline src/libsyntax_ext/deriving/mod.rs]: Oh, uh, forget what I just said. This comment explains why this case indeed needs a special span.

Comment (LeoTestard) [inline src/libsyntax_ext/deriving/mod.rs]: Errmmm... Or maybe not, since the span taht we compute in the loop has `allow_internal_unstable` set? I must admit I'm a bit confused.

Comment (LeoTestard) [inline src/libsyntax_ext/deriving/mod.rs]: Well okay, no, now that you eplicitly set `allow_internal_unstable`, which wasn't the case before I think, it should be okay. But you should definitely add a test like what the comment suggests and make sure it compiles. Something like:

```
macro_rules! foo() (
    ($attr:tt) => (
        #[deriving($attr, PartialEq)] strut S;
    )
);

foo!(Eq);
```

Comment (jseyfried) [inline src/libsyntax_ext/deriving/mod.rs]: @LeoTestard c.f. [this test](https://github.com/rust-lang/rust/blob/master/src/test/run-pass/rfc1445/eq-allows-match-on-ty-in-macro.rs)

Comment (LeoTestard) [inline src/libsyntax_ext/deriving/mod.rs]: Ok fine. Looks good to me then. :)
