### PR TITLE
Pass list of defineable opaque types into canonical queries

### LINKED ISSUE #108498: ICE when equating TAIT and RPIT in canonical queries
### Code

https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=ec86c1b56e1fe08951cf0dbb67ea7d7b

```Rust
#![feature(type_alias_impl_trait)]

type Opaque = impl Sized;

fn get_rpit() -> impl Clone {}

fn query(_: impl FnOnce() -> Opaque) {}

fn test() -> Opaque {
    query(get_rpit);
    get_rpit()
}
```

While trying to prove the predicate `<get_rpit as FnOnce>::Output == Opaque`, we end up equating `get_rpit::opaque#0 == Opaque::opaque#0`. Because inside canonical queries we know nothing about the defining scope (`DefiningAnchor::Bubble`), we register the hidden type as `get_rpit::opaque := Opaque::opaque` instead of `Opaque::opaque := get_rpit::opaque`.

Cc @oli-obk.

### Meta

Nightly version: 1.69.0-nightly (2023-02-25 34e6673a0473e90ef01a)

### Error output

<details><summary><strong>Backtrace</strong></summary>
<p>

```
warning: type alias `Opaque` is never used
 --> src/lib.rs:3:6
  |
3 | type Opaque = impl Sized;
  |      ^^^^^^
  |
  = note: `#[warn(dead_code)]` on by default

warning: function `get_rpit` is never used
 --> src/lib.rs:5:4
  |
5 | fn get_rpit() -> impl Clone {}
  |    ^^^^^^^^

warning: function `query` is never used
 --> src/lib.rs:7:4
  |
7 | fn query(_: impl FnOnce() -> Opaque) {}
  |    ^^^^^

warning: function `test` is never used
 --> src/lib.rs:9:4
  |
9 | fn test() -> Opaque {
  |    ^^^^

error: internal compiler error: no errors encountered even though `delay_span_bug` issued

error: internal compiler error: VecMap([(OpaqueTypeKey { def_id: DefId(0:8 ~ playground[4e8e]::get_rpit::{opaque#0}), substs: [] }, OpaqueTypeDecl { hidden_type: OpaqueHiddenType { span: no-location (#0), ty: Opaque }, origin: FnReturn(DefId(0:4 ~ playground[4e8e]::get_rpit)) })])
  |
  = note: delayed at    0: <rustc_errors::HandlerInner>::emit_diagnostic
             1: <rustc_errors::Handler>::delay_span_bug::<rustc_span::span_encoding::Span, &alloc::string::String>
             2: core::ptr::drop_in_place::<rustc_infer::infer::InferCtxt>
             3: <rustc_infer::infer::InferCtxtBuilder as rustc_trait_selection::infer::InferCtxtBuilderExt>::enter_canonical_trait_query::<rustc_middle::ty::ParamEnvAnd<rustc_middle::traits::query::type_op::ProvePredicate>, (), rustc_traits::type_op::type_op_prove_predicate::{closure#0}>
             4: rustc_query_system::query::plumbing::get_query::<rustc_query_impl::queries::type_op_prove_predicate, rustc_query_impl::plumbing::QueryCtxt, rustc_middle::dep_graph::dep_node::DepKind>
             5: <rustc_middle::ty::ParamEnvAnd<rustc_middle::traits::query::type_op::ProvePredicate> as rustc_trait_selection::traits::query::type_op::TypeOp>::fully_perform
             6: <rustc_borrowck::type_check::TypeChecker>::normalize_and_prove_instantiated_predicates
             7: <rustc_borrowck::type_check::TypeVerifier as rustc_middle::mir::visit::Visitor>::visit_constant
             8: <rustc_borrowck::type_check::TypeVerifier as rustc_middle::mir::visit::Visitor>::visit_body
             9: rustc_borrowck::type_check::type_check
            10: rustc_borrowck::nll::compute_regions
            11: rustc_borrowck::do_mir_borrowck
            12: rustc_borrowck::mir_borrowck
            13: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::queries::mir_borrowck, rustc_query_impl::plumbing::QueryCtxt>
            14: <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::mir_borrowck
            15: <rustc_hir_analysis::collect::type_of::find_opaque_ty_constraints_for_tait::ConstraintLocator>::check
            16: <rustc_hir_analysis::collect::type_of::find_opaque_ty_constraints_for_tait::ConstraintLocator as rustc_hir::intravisit::Visitor>::visit_nested_item
            17: rustc_hir::intravisit::walk_mod::<rustc_hir_analysis::collect::type_of::find_opaque_ty_constraints_for_tait::ConstraintLocator>
            18: rustc_hir_analysis::collect::type_of::find_opaque_ty_constraints_for_tait
            19: rustc_hir_analysis::collect::type_of::type_of
            20: rustc_query_system::query::plumbing::get_query::<rustc_query_impl::queries::type_of, rustc_query_impl::plumbing::QueryCtxt, rustc_middle::dep_graph::dep_node::DepKind>
            21: rustc_hir_analysis::check::check::check_mod_item_types
            22: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::queries::check_mod_item_types, rustc_query_impl::plumbing::QueryCtxt>
            23: <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::check_mod_item_types
            24: <rustc_middle::hir::map::Map>::for_each_module::<rustc_hir_analysis::check_crate::{closure#6}::{closure#0}>
            25: rustc_hir_analysis::check_crate
            26: rustc_interface::passes::analysis
            27: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::queries::analysis, rustc_query_impl::plumbing::QueryCtxt>
            28: <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::analysis
            29: <rustc_middle::ty::context::GlobalCtxt>::enter::<rustc_driver_impl::run_compiler::{closure#1}::{closure#2}::{closure#4}, core::result::Result<(), rustc_errors::ErrorGuaranteed>>
            30: <rustc_interface::interface::Compiler>::enter::<rustc_driver_impl::run_compiler::{closure#1}::{closure#2}, core::result::Result<core::option::Option<rustc_interface::queries::Linker>, rustc_errors::ErrorGuaranteed>>
            31: rustc_span::with_source_map::<core::result::Result<(), rustc_errors::ErrorGuaranteed>, rustc_interface::interface::run_compiler<core::result::Result<(), rustc_errors::ErrorGuaranteed>, rustc_driver_impl::run_compiler::{closure#1}>::{closure#0}::{closure#0}>
            32: std::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface::util::run_in_thread_pool_with_globals<rustc_interface::interface::run_compiler<core::result::Result<(), rustc_errors::ErrorGuaranteed>, rustc_driver_impl::run_compiler::{closure#1}>::{closure#0}, core::result::Result<(), rustc_errors::ErrorGuaranteed>>::{closure#0}::{closure#0}, core::result::Result<(), rustc_errors::ErrorGuaranteed>>
            33: <<std::thread::Builder>::spawn_unchecked_<rustc_interface::util::run_in_thread_pool_with_globals<rustc_interface::interface::run_compiler<core::result::Result<(), rustc_errors::ErrorGuaranteed>, rustc_driver_impl::run_compiler::{closure#1}>::{closure#0}, core::result::Result<(), rustc_errors::ErrorGuaranteed>>::{closure#0}::{closure#0}, core::result::Result<(), rustc_errors::ErrorGuaranteed>>::{closure#1} as core::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
            34: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
                       at /rustc/34e6673a0473e90ef01a18eb575392c9e3859747/library/alloc/src/boxed.rs:1988:9
            35: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
                       at /rustc/34e6673a0473e90ef01a18eb575392c9e3859747/library/alloc/src/boxed.rs:1988:9
            36: std::sys::unix::thread::Thread::new::thread_start
                       at /rustc/34e6673a0473e90ef01a18eb575392c9e3859747/library/std/src/sys/unix/thread.rs:108:17
            37: start_thread
            38: clone
          

error: internal compiler error: broken MIR in DefId(0:6 ~ playground[4e8e]::test) (NoSolution): could not prove Binder(ProjectionPredicate(AliasTy { substs: [fn() -> impl std::clone::Clone {get_rpit}, ()], def_id: DefId(2:2923 ~ core[df15]::ops::function::FnOnce::Output) }, Term::Ty(Opaque)), [])
  |
  = note: delayed at    0: <rustc_errors::HandlerInner>::emit_diagnostic
             1: <rustc_errors::Handler>::delay_span_bug::<rustc_span::span_encoding::Span, &str>
             2: <rustc_borrowck::type_check::TypeChecker>::normalize_and_prove_instantiated_predicates
             3: <rustc_borrowck::type_check::TypeVerifier as rustc_middle::mir::visit::Visitor>::visit_constant
             4: <rustc_borrowck::type_check::TypeVerifier as rustc_middle::mir::visit::Visitor>::visit_body
             5: rustc_borrowck::type_check::type_check
             6: rustc_borrowck::nll::compute_regions
             7: rustc_borrowck::do_mir_borrowck
             8: rustc_borrowck::mir_borrowck
             9: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::queries::mir_borrowck, rustc_query_impl::plumbing::QueryCtxt>
            10: <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::mir_borrowck
            11: <rustc_hir_analysis::collect::type_of::find_opaque_ty_constraints_for_tait::ConstraintLocator>::check
            12: <rustc_hir_analysis::collect::type_of::find_opaque_ty_constraints_for_tait::ConstraintLocator as rustc_hir::intravisit::Visitor>::visit_nested_item
            13: rustc_hir::intravisit::walk_mod::<rustc_hir_analysis::collect::type_of::find_opaque_ty_constraints_for_tait::ConstraintLocator>
            14: rustc_hir_analysis::collect::type_of::find_opaque_ty_constraints_for_tait
            15: rustc_hir_analysis::collect::type_of::type_of
            16: rustc_query_system::query::plumbing::get_query::<rustc_query_impl::queries::type_of, rustc_query_impl::plumbing::QueryCtxt, rustc_middle::dep_graph::dep_node::DepKind>
            17: rustc_hir_analysis::check::check::check_mod_item_types
            18: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::queries::check_mod_item_types, rustc_query_impl::plumbing::QueryCtxt>
            19: <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::check_mod_item_types
            20: <rustc_middle::hir::map::Map>::for_each_module::<rustc_hir_analysis::check_crate::{closure#6}::{closure#0}>
            21: rustc_hir_analysis::check_crate
            22: rustc_interface::passes::analysis
            23: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::queries::analysis, rustc_query_impl::plumbing::QueryCtxt>
            24: <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::analysis
            25: <rustc_middle::ty::context::GlobalCtxt>::enter::<rustc_driver_impl::run_compiler::{closure#1}::{closure#2}::{closure#4}, core::result::Result<(), rustc_errors::ErrorGuaranteed>>
            26: <rustc_interface::interface::Compiler>::enter::<rustc_driver_impl::run_compiler::{closure#1}::{closure#2}, core::result::Result<core::option::Option<rustc_interface::queries::Linker>, rustc_errors::ErrorGuaranteed>>
            27: rustc_span::with_source_map::<core::result::Result<(), rustc_errors::ErrorGuaranteed>, rustc_interface::interface::run_compiler<core::result::Result<(), rustc_errors::ErrorGuaranteed>, rustc_driver_impl::run_compiler::{closure#1}>::{closure#0}::{closure#0}>
            28: std::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface::util::run_in_thread_pool_with_globals<rustc_interface::interface::run_compiler<core::result::Result<(), rustc_errors::ErrorGuaranteed>, rustc_driver_impl::run_compiler::{closure#1}>::{closure#0}, core::result::Result<(), rustc_errors::ErrorGuaranteed>>::{closure#0}::{closure#0}, core::result::Result<(), rustc_errors::ErrorGuaranteed>>
            29: <<std::thread::Builder>::spawn_unchecked_<rustc_interface::util::run_in_thread_pool_with_globals<rustc_interface::interface::run_compiler<core::result::Result<(), rustc_errors::ErrorGuaranteed>, rustc_driver_impl::run_compiler::{closure#1}>::{closure#0}, core::result::Result<(), rustc_errors::ErrorGuaranteed>>::{closure#0}::{closure#0}, core::result::Result<(), rustc_errors::ErrorGuaranteed>>::{closure#1} as core::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
            30: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
                       at /rustc/34e6673a0473e90ef01a18eb575392c9e3859747/library/alloc/src/boxed.rs:1988:9
            31: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
                       at /rustc/34e6673a0473e90ef01a18eb575392c9e3859747/library/alloc/src/boxed.rs:1988:9
            32: std::sys::unix::thread::Thread::new::thread_start
                       at /rustc/34e6673a0473e90ef01a18eb575392c9e3859747/library/std/src/sys/unix/thread.rs:108:17
            33: start_thread
            34: clone
          

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.69.0-nightly (34e6673a0 2023-02-25) running on x86_64-unknown-linux-gnu

note: compiler flags: --crate-type lib -C embed-bitcode=no -C codegen-units=1 -C debuginfo=2

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
warning: `playground` (lib) generated 4 warnings
error: could not compile `playground`; 4 warnings emitted
```

</p>
</details>

@rustbot label F-type_alias_impl_trait T-types

### LINKED ISSUE #116877: regression when relating two opaque types in canonical queries
Each revision of this test is an ICE in 1.75.0-nightly (2023-10-17 09df6108c84fdec40004):
```rust
// revisions: sized clone

#[cfg(sized)] fn rpit() -> impl Sized {}
#[cfg(clone)] fn rpit() -> impl Clone {}

fn same_output<Out>(_: impl Fn() -> Out, _: impl Fn() -> Out) {}

pub fn foo() -> impl Sized {
    same_output(rpit, foo);
    same_output(foo, rpit);
    rpit()
}
```

Both revisions have a somewhat convoluted history best shown in a table form:

|   | `sized` | `clone`
|---|---|---|
| stable 1.73 | PASS :ok: | ICE :ice_cube: 
| #114586 (1.74.0-beta) | PASS :ok: | PASS :ok:
| #116530 (1.75.0-nightly)| ICE :ice_cube:  | ICE :ice_cube:

While it may seem like #116530 is the culprit, I'd argue that the PR #114586 introduced an incomplete fix that I don't believe we should commit to in stable. Additionally, reverting #114586 while keeping #116530 would fix `sized` version as well as an other regression https://github.com/rust-lang/rust/pull/114586#issuecomment-1751967321, making it the right choice in my opinion.

### PR DESCRIPTION
**Pull request by oli-obk**
This eliminates `DefiningAnchor::Bubble` for good and brings the old solver closer to the new one wrt cycles and nested obligations. At that point the difference between `DefiningAnchor::Bind([])` and `DefiningAnchor::Error` was academic. We only used the difference for some sanity checks, which actually had to be worked around in places, so I just removed `DefiningAnchor` entirely and just stored the list of opaques that may be defined.

fixes #108498
fixes https://github.com/rust-lang/rust/issues/116877

* [x] run crater
  - https://github.com/rust-lang/rust/pull/122077#issuecomment-2013293931

### CODE REVIEW

File: compiler/rustc_trait_selection/src/solve/mod.rs [hunk 1]
```diff
@@ -320,5 +320,6 @@ fn response_no_constraints_raw<'tcx>(
             external_constraints: tcx.mk_external_constraints(ExternalConstraintsData::default()),
             certainty,
         },
+        defining_anchor: Default::default(),
```
Comment (oli-obk) [inline compiler/rustc_trait_selection/src/solve/mod.rs:323]: This one is fishy, we can probably always pass in the anchor from the InferCtxt

File: compiler/rustc_trait_selection/src/infer.rs [hunk 2]
```diff
@@ -133,9 +133,8 @@ impl<'tcx> InferCtxtBuilder<'tcx> {
         R: Debug + TypeFoldable<TyCtxt<'tcx>>,
         Canonical<'tcx, QueryResponse<'tcx, R>>: ArenaAllocatable<'tcx>,
     {
-        let (infcx, key, canonical_inference_vars) = self
-            .with_opaque_type_inference(DefiningAnchor::Bubble)
-            .build_with_canonical(DUMMY_SP, canonical_key);
+        let (infcx, key, canonical_inference_vars) =
+            self.build_with_canonical(DUMMY_SP, canonical_key);
```
Comment (oli-obk) [inline compiler/rustc_trait_selection/src/infer.rs:137]: This is the core change of this PR. Canonical queries now always use the anchor of their caller

File: compiler/rustc_middle/src/query/plumbing.rs [hunk 3]
```diff
@@ -340,10 +340,10 @@ macro_rules! define_callbacks {
                     <$($K)* as keys::Key>::CacheSelector as CacheSelector<'tcx, Erase<$V>>
                 >::Cache;
 
-                // Ensure that keys grow no larger than 64 bytes
+                // Ensure that keys grow no larger than 72 bytes
```
Comment (compiler-errors) [inline compiler/rustc_middle/src/query/plumbing.rs:343]: Is this not a hard limit? Why was this added in the first place?

Comment (oli-obk) [reply compiler/rustc_middle/src/query/plumbing.rs:343]: probably perf, but I'm trying to resolve it anyway before going out of draft

Comment (oli-obk) [reply compiler/rustc_middle/src/query/plumbing.rs:343]: So I'm a bit stuck on CanonicalTypeOpAscribeUserTypeGoal. It's 8 bytes too large now, but there's also nothing that stands out as "this should be interned". Just moving something onto a TyCtxt arena doesn't really seem right to me, that's just avoiding the above size check without adhering to its spirit.

**Comment by oli-obk** [comment]
@craterbot check

**Comment by oli-obk** [comment]
primary regression is in `write_dep_info`, which is unavoidable. We just have more edges in the dep graph now

secondary regressions look like legitimately more invocations of `type_op_prove_predicate`, which is to be expected of any opaque type heavy code. We can probably improve on that by first running without opaques in the defineable list, and if it fails due to opaque type equality, we rerun it with opaques. That should avoid duplicating all the query invocations where the opaques don't matter.

I would prefer to leave such (potentially unsound, so needing lots of care) optimizations to the future, especially since the performance effect isn't very large, and this PR fixes long standing bugs and enables fixing several more.

File: compiler/rustc_infer/src/infer/opaque_types/mod.rs [hunk 4]
```diff
@@ -109,48 +109,44 @@ impl<'tcx> InferCtxt<'tcx> {
...
+                // similar situation with closure return types
+                // today:
+                //
+                // ```rust
+                // fn foo() -> impl Iterator { .. }
+                // fn bar() {
+                //     let x = || foo(); // returns the Opaque assoc with `foo`
+                // }
+                // ```
+                if self.opaque_type_origin(def_id).is_none() {
```
Comment (lcnr) [inline compiler/rustc_infer/src/infer/opaque_types/mod.rs:146]: that's just `self.defining_opaque_types.contains(def_id)`? :thinking: I would like to move all the `infcx.opaque_type_origin(def_id).is_some/none()` calls to `self.defining_opaque_types.contains` :thinking: or even a separate `fn opaque_in_defining_scope(&self, def_id: LocalDefId) -> bool` function.

Ideally the core type system™ does not know what kind of opaque type - or alias - it's dealing with unless strictly necessary

File: compiler/rustc_middle/src/traits/solve.rs [hunk 5]
```diff
@@ -114,7 +114,6 @@ impl MaybeCause {
 #[derive(Debug, PartialEq, Eq, Clone, Copy, Hash, HashStable, TypeFoldable, TypeVisitable)]
 pub struct QueryInput<'tcx, T> {
     pub goal: Goal<'tcx, T>,
```
Comment (lcnr) [inline compiler/rustc_middle/src/traits/solve.rs:116]: maybe keep the `defining_opaque_types` in the `QueryInput` (as it's unnecessary to canonicalize it again in the output) and use a `trait QueryInput { fn defining_opaque_types(&self) -> &'tcx List<LocalDefId> }`

File: tests/ui/type-alias-impl-trait/issue-53398-cyclic-types.rs [hunk 6]
```diff
@@ -1,10 +1,9 @@
 #![feature(type_alias_impl_trait)]
 
-//@ check-pass
-
 type Foo = impl Fn() -> Foo;
```
Comment (lcnr) [inline tests/ui/type-alias-impl-trait/issue-53398-cyclic-types.rs:3]: :thinking: mind changing this to `//@ known-bug: #109268` and also adding the test for that issue?

Comment (lcnr) [reply tests/ui/type-alias-impl-trait/issue-53398-cyclic-types.rs:3]: also, this test exists twice. This file and tests/ui/type-alias-impl-trait/type-alias-impl-trait-with-cycle-error.rs please remove this one :thinking:

please add the test from #109268 as `tests/ui/type-alias-impl-trait/type-alias-impl-trait-with-cycle-error-3.rs`, adjusting the names of the other two tests as well

**Review by lcnr — COMMENTED** [review]
some nits

very happy about this change, thanks for your work :heart:

File: compiler/rustc_middle/src/traits/solve.rs (hunk 5 above)
Comment (oli-obk) [reply compiler/rustc_middle/src/traits/solve.rs:116]: I tried this, it does not spark joy. I then need to make all other things that are ever used in a `Canonical` take `defining_opaque_types`, which is all `TypeOp`s, as well as their corresponding queries that just take a `ParamEnvAnd<'tcx, some_tuple>`. Doing that would require some groundwork bringing all of these under a common struct... which basically means having a second kind of `Canonical` for the non-`solve::QueryInput` queries.

Comment (oli-obk) [reply compiler/rustc_middle/src/traits/solve.rs:116]: see https://github.com/rust-lang/rust/commit/697f167652db232e79a32098f4af853ad4fb3afe for the (very) unfinished work

**Comment by oli-obk** [comment]
hmm fun, crater won't get to this until next week. Still, thanks for the quick review above ^^

**Review by lcnr — COMMENTED** [review]
can you add a test for https://github.com/rust-lang/trait-system-refactor-initiative/issues/43 as tests/ui/type-alias-impl-trait/type-alias-impl-trait-with-cycle-error-4.rs

```rust
#![feature(type_alias_impl_trait)]

trait Id {
    type Assoc;
}
impl<T> Id for T {
    type Assoc = T;
}

type Ty where Ty: Id<Assoc = Ty> = impl Sized;
fn define() -> Ty {}
fn main() {}
```

**Comment by oli-obk** [comment]
The rebase required me to add [6c33462](https://github.com/rust-lang/rust/pull/122077/commits/6c33462fb498ed84e7096aa9bdb2dc1d300fedbb), which would absolutely benefit from a larger refactoring. To keep this PR simple all I did was change a delayed bug into an error for RPITs

**Comment by oli-obk** [comment]
Huh I just tried to rebase, and after the first commit now

```rust
fn test() -> Option<impl Sized> {
    Some("")
}

fn main() {
    test();
}
```

fails under the new solver with

```
error[E0308]: mismatched types
  --> /home/ubuntu/rustc/rust1/tests/ui/impl-trait/reveal-during-codegen.rs:7:5
   |
LL | fn test() -> Option<impl Sized> {
   |              ------------------
   |              |      |
   |              |      the expected opaque type
   |              expected `Option<impl Sized>` because of return type
LL |     Some("")
   |     ^^^^^^^^ types differ
   |
   = note: expected enum `Option<impl Sized>`
              found enum `Option<&str>`
```

I'm very confused 😆

**Comment by oli-obk** [comment]
maybe https://github.com/rust-lang/rust/pull/122687 ?

**Comment by oli-obk** [comment]
ok... running the same test in a loop sometimes produces two diagnostics, sometimes one. Only in the new solver so far.

**Comment by oli-obk** [comment]
A test that fails sometimes, fails with

```
                  ├─┐rustc_trait_selection::solve::eval_ctxt::evaluate_canonical_goal canonical_input=Canonical { value: QueryInput { goal: Goal { predicate: Binder { value: AliasRelate(Term::Ty(^1_0), Equate, Term::Ty(Alias(Opaque, AliasTy { args: [^1_1, ^1_2], def_id: DefId(0:14 ~ dont_remap_tait_substs[6986]::Foo::{opaque#0}) }))), bound_vars: [] }, param_env: ParamEnv { caller_bounds: [Binder { value: TraitPredicate(<^1_1 as std::marker::Send>, polarity:Positive), bound_vars: [] }, Binder { value: TraitPredicate(<^1_1 as std::marker::Sized>, polarity:Positive), bound_vars: [] }, Binder { value: TraitPredicate(<^1_2 as std::marker::Sized>, polarity:Positive), bound_vars: [] }], reveal: UserFacing } }, predefined_opaques_in_body: PredefinedOpaques(PredefinedOpaquesData { opaque_types: [] }) }, max_universe: U0, variables: [CanonicalVarInfo { kind: Ty(General(U0)) }, CanonicalVarInfo { kind: PlaceholderTy(!1) }, CanonicalVarInfo { kind: PlaceholderTy(!2) }] }
                    ├─┐rustc_trait_selection::solve::search_graph::on_cache_hit additional_depth=1, encountered_overflow=false
                    ├─┘
                    ├─  0ms DEBUG rustc_trait_selection::solve::eval_ctxt return=Ok(Canonical { value: Response { certainty: Maybe(Ambiguity), var_values: CanonicalVarValues { var_values: [^0, ^1, ^2] }, external_constraints: ExternalConstraints(ExternalConstraintsData { region_constraints: QueryRegionConstraints { outlives: [], member_constraints: [] }, opaque_types: [], normalization_nested_goals: NestedNormalizationGoals([]) }) }, max_universe: U0, variables: [CanonicalVarInfo { kind: Ty(General(U0)) }, CanonicalVarInfo { kind: PlaceholderTy(!1) }, CanonicalVarInfo { kind: PlaceholderTy(!2) }] })
                  ├─┘
```

but passes with

```

                  ├─┐rustc_trait_selection::solve::eval_ctxt::evaluate_canonical_goal canonical_input=Canonical { value: QueryInput { goal: Goal { predicate: Binder { value: AliasRelate(Term::Ty(^1_0), Equate, Term::Ty(Alias(Opaque, AliasTy { args: [^1_1, ^1_2], def_id: DefId(0:14 ~ dont_remap_tait_substs[6986]::Foo::{opaque#0}) }))), bound_vars: [] }, param_env: ParamEnv { caller_bounds: [Binder { value: TraitPredicate(<^1_1 as std::marker::Send>, polarity:Positive), bound_vars: [] }, Binder { value: TraitPredicate(<^1_1 as std::marker::Sized>, polarity:Positive), bound_vars: [] }, Binder { value: TraitPredicate(<^1_2 as std::marker::Sized>, polarity:Positive), bound_vars: [] }], reveal: UserFacing } }, predefined_opaques_in_body: PredefinedOpaques(PredefinedOpaquesData { opaque_types: [] }) }, max_universe: U0, variables: [CanonicalVarInfo { kind: Ty(General(U0)) }, CanonicalVarInfo { kind: PlaceholderTy(!1) }, CanonicalVarInfo { kind: PlaceholderTy(!2) }] }
                    ├─  0ms DEBUG rustc_infer::infer::type_variable new_var(index=?0t, universe=U0, origin=TypeVariableOrigin { kind: MiscVariable, span: no-location (#0) })
                    ├─  0ms DEBUG rustc_middle::ty::fold shift_vars(value=?0t, amount=1)
                    ├─  0ms DEBUG rustc_middle::ty::fold shift_vars(value=!1, amount=1)
                    ├─  0ms DEBUG rustc_middle::ty::fold shift_vars(value=!2, amount=1)
                    ├─  0ms DEBUG rustc_middle::ty::fold shift_vars(value=!1, amount=1)
                    ├─  0ms DEBUG rustc_middle::ty::fold shift_vars(value=!1, amount=1)
                    ├─  0ms DEBUG rustc_middle::ty::fold shift_vars(value=!2, amount=1)
                    ├─┐rustc_trait_selection::solve::alias_relate::compute_alias_relate_goal goal=Goal { predicate: (Term::Ty(?0t), Term::Ty(Alias(Opaque, AliasTy { args: [!1, !2], def_id: DefId(0:14 ~ dont_remap_tait_substs[6986]::Foo::{opaque#0}) })), Equate), param_env: ParamEnv { caller_bounds: [Binder { value: TraitPredicate(<!1 as std::marker::Send>, polarity:Positive), bound_vars: [] }, Binder { value: TraitPredicate(<!1 as std::marker::Sized>, polarity:Positive), bound_vars: [] }, Binder { value: TraitPredicate(<!2 as std::marker::Sized>, polarity:Positive), bound_vars: [] }], reveal: UserFacing } }
                      ├─┐rustc_trait_selection::solve::alias_relate::try_normalize_term term=Term::Ty(?0t)
                        ├─┐rustc_trait_selection::solve::alias_relate::try_normalize_ty_recur depth=0, ty=?0t
                          ├─  0ms DEBUG rustc_trait_selection::solve::alias_relate return=Some(?0t)
                        ├─┘
                        ├─  0ms DEBUG rustc_trait_selection::solve::alias_relate return=Ok(Some(Term::Ty(?0t)))
                      ├─┘
                      ├─┐rustc_trait_selection::solve::alias_relate::try_normalize_term term=Term::Ty(Alias(Opaque, AliasTy { args: [!1, !2], def_id: DefId(0:14 ~ dont_remap_tait_substs[6986]::Foo::{opaque#0}) }))
                        ├─┐rustc_trait_selection::solve::alias_relate::try_normalize_ty_recur depth=0, ty=Alias(Opaque, AliasTy { args: [!1, !2], def_id: DefId(0:14 ~ dont_remap_tait_substs[6986]::Foo::{opaque#0}) })
                          ├─┐rustc_infer::infer::snapshot::commit_if_ok 
                            ├─  0ms DEBUG rustc_infer::infer::snapshot start_snapshot()
                            ├─  0ms DEBUG rustc_infer::infer::region_constraints RegionConstraintCollector: start_snapshot
                            ├─  0ms DEBUG rustc_infer::infer::type_variable new_var(index=?1t, universe=U0, origin=TypeVariableOrigin { kind: MiscVariable, span: no-location (#0) })
                            ├─┐rustc_trait_selection::solve::add_goal source=Misc, goal=Goal { predicate: Binder { value: NormalizesTo(AliasTy { args: [!1, !2], def_id: DefId(0:14 ~ dont_remap_tait_substs[6986]::Foo::{opaque#0}) }, Term::Ty(?1t)), bound_vars: [] }, param_env: ParamEnv { caller_bounds: [Binder { value: TraitPredicate(<!1 as std::marker::Send>, polarity:Positive), bound_vars: [] }, Binder { value: TraitPredicate(<!1 as std::marker::Sized>, polarity:Positive), bound_vars: [] }, Binder { value: TraitPredicate(<!2 as std::marker::Sized>, polarity:Positive), bound_vars: [] }], reveal: UserFacing } }
                            ├─┘
                            ├─┐rustc_trait_selection::solve::eval_ctxt::try_evaluate_added_goals 
                              ├─┐rustc_trait_selection::solve::eval_ctxt::evaluate_canonical_goal canonical_input=Canonical { value: QueryInput { goal: Goal { predicate: Binder { value: NormalizesTo(AliasTy { args: [^1_0, ^1_1], def_id: DefId(0:14 ~ dont_remap_tait_substs[6986]::Foo::{opaque#0}) }, Term::Ty(^1_2)), bound_vars: [] }, param_env: ParamEnv { caller_bounds: [Binder { value: TraitPredicate(<^1_0 as std::marker::Send>, polarity:Positive), bound_vars: [] }, Binder { value: TraitPredicate(<^1_0 as std::marker::Sized>, polarity:Positive), bound_vars: [] }, Binder { value: TraitPredicate(<^1_1 as std::marker::Sized>, polarity:Positive), bound_vars: [] }], reveal: UserFacing } }, predefined_opaques_in_body: PredefinedOpaques(PredefinedOpaquesData { opaque_types: [] }) }, max_universe: U0, variables: [CanonicalVarInfo { kind: PlaceholderTy(!0) }, CanonicalVarInfo { kind: PlaceholderTy(!1) }, CanonicalVarInfo { kind: Ty(General(U0)) }] }
                                ├─  0ms DEBUG rustc_infer::infer::type_variable new_var(index=?0t, universe=U0, origin=TypeVariableOrigin { kind: MiscVariable, span: no-location (#0) })
                                ├─  0ms DEBUG rustc_middle::ty::fold shift_vars(value=!0, amount=1)
                                ├─  0ms DEBUG rustc_middle::ty::fold shift_vars(value=!1, amount=1)
                                ├─  0ms DEBUG rustc_middle::ty::fold shift_vars(value=?0t, amount=1)
                                ├─  0ms DEBUG rustc_middle::ty::fold shift_vars(value=!0, amount=1)
                                ├─  0ms DEBUG rustc_middle::ty::fold shift_vars(value=!0, amount=1)
                                ├─  0ms DEBUG rustc_middle::ty::fold shift_vars(value=!1, amount=1)
                                ├─┐rustc_trait_selection::solve::normalizes_to::compute_normalizes_to_goal goal=Goal { predicate: NormalizesTo(AliasTy { args: [!0, !1], def_id: DefId(0:14 ~ dont_remap_tait_substs[6986]::Foo::{opaque#0}) }, Term::Ty(?0t)), param_env: ParamEnv { caller_bounds: [Binder { value: TraitPredicate(<!0 as std::marker::Send>, polarity:Positive), bound_vars: [] }, Binder { value: TraitPredicate(<!0 as std::marker::Sized>, polarity:Positive), bound_vars: [] }, Binder { value: TraitPredicate(<!1 as std::marker::Sized>, polarity:Positive), bound_vars: [] }], reveal: UserFacing } }
                                  ├─  0ms DEBUG rustc_trait_selection::solve::normalizes_to return=Err(NoSolution)
                                ├─┘
                                ├─┐rustc_infer::infer::take_opaque_types 
                                  ├─  0ms DEBUG rustc_infer::infer return={}
                                ├─┘
                                ├─  0ms DEBUG rustc_trait_selection::solve::eval_ctxt return=Err(NoSolution)
                              ├─┘
                            ├─┘
                            ├─  0ms DEBUG rustc_infer::infer::snapshot commit_if_ok() -- r.is_ok() = false
                            ├─┐rustc_infer::infer::snapshot::rollback_to 
                              ├─  0ms DEBUG rustc_infer::infer::snapshot::undo_log rollback_to(0)
                              ├─  0ms DEBUG rustc_infer::infer::region_constraints RegionConstraintCollector: rollback_to(RegionSnapshot)
                            ├─┘
                          ├─┘
                          ├─  0ms DEBUG rustc_trait_selection::solve::alias_relate return=Some(Alias(Opaque, AliasTy { args: [!1, !2], def_id: DefId(0:14 ~ dont_remap_tait_substs[6986]::Foo::{opaque#0}) }))
                        ├─┘
                        ├─  0ms DEBUG rustc_trait_selection::solve::alias_relate return=Ok(Some(Term::Ty(Alias(Opaque, AliasTy { args: [!1, !2], def_id: DefId(0:14 ~ dont_remap_tait_substs[6986]::Foo::{opaque#0}) }))))
                      ├─┘
                      ├─┐rustc_trait_selection::solve::alias_relate::relate_rigid_alias_non_alias alias=AliasTy { args: [!1, !2], def_id: DefId(0:14 ~ dont_remap_tait_substs[6986]::Foo::{opaque#0}) }, variance=o, term=Term::Ty(?0t)
                        ├─  0ms DEBUG rustc_infer::infer::type_variable new_var(index=?1t, universe=U0, origin=TypeVariableOrigin { kind: TypeParameterDefinition("T", DefId(0:4 ~ dont_remap_tait_substs[6986]::Foo::T)), span: no-location (#0) })
                        ├─  0ms DEBUG rustc_infer::infer::type_variable new_var(index=?2t, universe=U0, origin=TypeVariableOrigin { kind: TypeParameterDefinition("U", DefId(0:5 ~ dont_remap_tait_substs[6986]::Foo::U)), span: no-location (#0) })
                        ├─┐rustc_trait_selection::solve::eval_ctxt::eq_structurally_relating_aliases lhs=Term::Ty(?0t), rhs=Term::Ty(Alias(Opaque, AliasTy { args: [?1t, ?2t], def_id: DefId(0:14 ~ dont_remap_tait_substs[6986]::Foo::{opaque#0}) }))
                          ├─┐rustc_infer::infer::at::eq_structurally_relating_aliases a=Term::Ty(?0t), b=Term::Ty(Alias(Opaque, AliasTy { args: [?1t, ?2t], def_id: DefId(0:14 ~ dont_remap_tait_substs[6986]::Foo::{opaque#0}) }))
                            ├─┐rustc_infer::infer::relate::type_relating::tys a=?0t, b=Alias(Opaque, AliasTy { args: [?1t, ?2t], def_id: DefId(0:14 ~ dont_remap_tait_substs[6986]::Foo::{opaque#0}) })
                              ├─┐rustc_infer::infer::relate::generalize::instantiate_ty_var target_is_expected=true, target_vid=?0t, instantiation_variance=o, source_ty=Alias(Opaque, AliasTy { args: [?1t, ?2t], def_id: DefId(0:14 ~ dont_remap_tait_substs[6986]::Foo::{opaque#0}) })
                                ├─┐rustc_infer::infer::relate::generalize::tys t=Alias(Opaque, AliasTy { args: [?1t, ?2t], def_id: DefId(0:14 ~ dont_remap_tait_substs[6986]::Foo::{opaque#0}) })
                                  ├─┐rustc_middle::ty::relate::structurally_relate_tys a=Alias(Opaque, AliasTy { args: [?1t, ?2t], def_id: DefId(0:14 ~ dont_remap_tait_substs[6986]::Foo::{opaque#0}) }), b=Alias(Opaque, AliasTy { args: [?1t, ?2t], def_id: DefId(0:14 ~ dont_remap_tait_substs[6986]::Foo::{opaque#0}) })
                                    ├─┐rustc_infer::infer::relate::generalize::relate_with_variance _info=None, a=?1t
                                      ├─  0ms DEBUG rustc_infer::infer::relate::generalize new ambient variance, self.ambient_variance=o
                                      ├─┐rustc_infer::infer::relate::generalize::tys t=?1t
                                        ├─  0ms DEBUG rustc_infer::infer::relate::generalize return=Ok(?1t)
                                      ├─┘
                                      ├─  0ms DEBUG rustc_infer::infer::relate::generalize return=Ok(?1t)
                                    ├─┘
                                    ├─┐rustc_infer::infer::relate::generalize::relate_with_variance _info=None, a=?2t
                                      ├─  0ms DEBUG rustc_infer::infer::relate::generalize new ambient variance, self.ambient_variance=o
                                      ├─┐rustc_infer::infer::relate::generalize::tys t=?2t
                                        ├─  0ms DEBUG rustc_infer::infer::relate::generalize return=Ok(?2t)
                                      ├─┘
                                      ├─  0ms DEBUG rustc_infer::infer::relate::generalize return=Ok(?2t)
                                    ├─┘
                                    ├─  0ms TRACE rustc_middle::ty::relate return=Ok(Alias(Opaque, AliasTy { args: [?1t, ?2t], def_id: DefId(0:14 ~ dont_remap_tait_substs[6986]::Foo::{opaque#0}) }))
                                  ├─┘
                                  ├─  0ms DEBUG rustc_infer::infer::relate::generalize return=Ok(Alias(Opaque, AliasTy { args: [?1t, ?2t], def_id: DefId(0:14 ~ dont_remap_tait_substs[6986]::Foo::{opaque#0}) }))
                                ├─┘
                                ├─┐rustc_infer::infer::relate::type_relating::tys a=Alias(Opaque, AliasTy { args: [?1t, ?2t], def_id: DefId(0:14 ~ dont_remap_tait_substs[6986]::Foo::{opaque#0}) }), b=Alias(Opaque, AliasTy { args: [?1t, ?2t], def_id: DefId(0:14 ~ dont_remap_tait_substs[6986]::Foo::{opaque#0}) })
                                ├─┘
                              ├─┘
                            ├─┘
                          ├─┘
                          ├─  0ms DEBUG rustc_trait_selection::solve::eval_ctxt return=Ok(())
                        ├─┘
                        ├─┐rustc_trait_selection::solve::eval_ctxt::eq lhs=AliasTy { args: [!1, !2], def_id: DefId(0:14 ~ dont_remap_tait_substs[6986]::Foo::{opaque#0}) }, rhs=AliasTy { args: [?1t, ?2t], def_id: DefId(0:14 ~ dont_remap_tait_substs[6986]::Foo::{opaque#0}) }
                          ├─┐rustc_infer::infer::at::eq define_opaque_types=No, a=AliasTy { args: [!1, !2], def_id: DefId(0:14 ~ dont_remap_tait_substs[6986]::Foo::{opaque#0}) }, b=AliasTy { args: [?1t, ?2t], def_id: DefId(0:14 ~ dont_remap_tait_substs[6986]::Foo::{opaque#0}) }
                            ├─  0ms DEBUG rustc_infer::infer::relate::type_relating new ambient variance, self.ambient_variance=o
                            ├─┐rustc_infer::infer::relate::type_relating::tys a=!1, b=?1t
                              ├─┐rustc_infer::infer::relate::generalize::instantiate_ty_var target_is_expected=false, target_vid=?1t, instantiation_variance=o, source_ty=!1
                                ├─┐rustc_infer::infer::relate::generalize::tys t=!1
                                  ├─  0ms DEBUG rustc_infer::infer::relate::generalize return=Ok(!1)
                                ├─┘
                                ├─  0ms DEBUG rustc_infer::infer::relate::generalize flip relation
                                ├─┐rustc_infer::infer::relate::type_relating::tys a=!1, b=!1
                                ├─┘
                              ├─┘
                            ├─┘
                            ├─  0ms DEBUG rustc_infer::infer::relate::type_relating new ambient variance, self.ambient_variance=o
                            ├─┐rustc_infer::infer::relate::type_relating::tys a=!2, b=?2t
                              ├─┐rustc_infer::infer::relate::generalize::instantiate_ty_var target_is_expected=false, target_vid=?2t, instantiation_variance=o, source_ty=!2
                                ├─┐rustc_infer::infer::relate::generalize::tys t=!2
                                  ├─  0ms DEBUG rustc_infer::infer::relate::generalize return=Ok(!2)
                                ├─┘
                                ├─  0ms DEBUG rustc_infer::infer::relate::generalize flip relation
                                ├─┐rustc_infer::infer::relate::type_relating::tys a=!2, b=!2
                                ├─┘
                              ├─┘
                            ├─┘
                          ├─┘
                          ├─┐rustc_trait_selection::solve::add_goals source=Misc
                          ├─┘
                          ├─  0ms DEBUG rustc_trait_selection::solve::eval_ctxt return=Ok(())
                        ├─┘
                        ├─┐rustc_trait_selection::solve::eval_ctxt::canonical::evaluate_added_goals_and_make_canonical_response certainty=Yes
                          ├─┐rustc_trait_selection::solve::eval_ctxt::try_evaluate_added_goals 
                          ├─┘
                          ├─┐rustc_trait_selection::solve::eval_ctxt::canonical::compute_external_query_constraints normalization_nested_goals=NestedNormalizationGoals([])
                            ├─┐rustc_infer::infer::region_constraints::leak_check::leak_check outer_universe=U0, max_universe=U0
                              ├─  0ms DEBUG rustc_infer::infer::region_constraints::leak_check return=Ok(())
                            ├─┘
                            ├─  0ms DEBUG rustc_infer::infer::canonical::query_response constraints=[]
                            ├─  0ms DEBUG rustc_trait_selection::solve::eval_ctxt::canonical return=Ok(ExternalConstraintsData { region_constraints: QueryRegionConstraints { outlives: [], member_constraints: [] }, opaque_types: [], normalization_nested_goals: NestedNormalizationGoals([]) })
                          ├─┘
                          ├─  0ms DEBUG rustc_trait_selection::solve::eval_ctxt::canonical return=Ok(Canonical { value: Response { certainty: Yes, var_values: CanonicalVarValues { var_values: [Alias(Opaque, AliasTy { args: [^0, ^1], def_id: DefId(0:14 ~ dont_remap_tait_substs[6986]::Foo::{opaque#0}) }), ^0, ^1] }, external_constraints: ExternalConstraints(ExternalConstraintsData { region_constraints: QueryRegionConstraints { outlives: [], member_constraints: [] }, opaque_types: [], normalization_nested_goals: NestedNormalizationGoals([]) }) }, max_universe: U0, variables: [CanonicalVarInfo { kind: PlaceholderTy(!1) }, CanonicalVarInfo { kind: PlaceholderTy(!2) }] })
                        ├─┘
                        ├─  0ms DEBUG rustc_trait_selection::solve::alias_relate return=Ok(Canonical { value: Response { certainty: Yes, var_values: CanonicalVarValues { var_values: [Alias(Opaque, AliasTy { args: [^0, ^1], def_id: DefId(0:14 ~ dont_remap_tait_substs[6986]::Foo::{opaque#0}) }), ^0, ^1] }, external_constraints: ExternalConstraints(ExternalConstraintsData { region_constraints: QueryRegionConstraints { outlives: [], member_constraints: [] }, opaque_types: [], normalization_nested_goals: NestedNormalizationGoals([]) }) }, max_universe: U0, variables: [CanonicalVarInfo { kind: PlaceholderTy(!1) }, CanonicalVarInfo { kind: PlaceholderTy(!2) }] })
                      ├─┘
                      ├─  0ms DEBUG rustc_trait_selection::solve::alias_relate return=Ok(Canonical { value: Response { certainty: Yes, var_values: CanonicalVarValues { var_values: [Alias(Opaque, AliasTy { args: [^0, ^1], def_id: DefId(0:14 ~ dont_remap_tait_substs[6986]::Foo::{opaque#0}) }), ^0, ^1] }, external_constraints: ExternalConstraints(ExternalConstraintsData { region_constraints: QueryRegionConstraints { outlives: [], member_constraints: [] }, opaque_types: [], normalization_nested_goals: NestedNormalizationGoals([]) }) }, max_universe: U0, variables: [CanonicalVarInfo { kind: PlaceholderTy(!1) }, CanonicalVarInfo { kind: PlaceholderTy(!2) }] })
                    ├─┘
                    ├─┐rustc_infer::infer::take_opaque_types 
                      ├─  0ms DEBUG rustc_infer::infer return={}
                    ├─┘
                    ├─  0ms DEBUG rustc_trait_selection::solve::eval_ctxt return=Ok(Canonical { value: Response { certainty: Yes, var_values: CanonicalVarValues { var_values: [Alias(Opaque, AliasTy { args: [^0, ^1], def_id: DefId(0:14 ~ dont_remap_tait_substs[6986]::Foo::{opaque#0}) }), ^0, ^1] }, external_constraints: ExternalConstraints(ExternalConstraintsData { region_constraints: QueryRegionConstraints { outlives: [], member_constraints: [] }, opaque_types: [], normalization_nested_goals: NestedNormalizationGoals([]) }) }, max_universe: U0, variables: [CanonicalVarInfo { kind: PlaceholderTy(!1) }, CanonicalVarInfo { kind: PlaceholderTy(!2) }] })
                  ├─┘
```

**Comment by oli-obk** [comment]
Note how the `evaluate_canonical_goal` is exactly the same

**Comment by compiler-errors** [comment]
Most of the regressions seem to a missing `scrape_region_constraints` call in borrowck (or something similar) leading to leftover region obligations in the infcx at the end of borrowck. Shouldn't be too hard to find out why that's happening.

File: compiler/rustc_borrowck/src/region_infer/opaque_types.rs [hunk 7]
```diff
@@ -227,6 +227,17 @@ impl<'tcx> RegionInferenceContext<'tcx> {
                 opaque_type_key,
                 universal_concrete_type,
             );
+
+            // Sometimes, when the hidden type is an inference variable, it can happen that
+            // the hidden type becomes the opaque type itself. In this case, this was an opaque
+            // usage of the opaque type and we can ignore it. This check is mirrored in typeck's
+            // writeback.
```
Comment (lcnr) [inline compiler/rustc_borrowck/src/region_infer/opaque_types.rs:233]:
```suggestion
            // FIXME(-Znext-solver): This should be unnecessary with the new solver.
```
Also, can this not result in an overflow? If you have `Opaque = OPaque` in the storage and then equate it with `u32`.

It tries to assign `u32` to `Opaque`, which fetches the hidden type of `Opaque` which is `OPaque` again, causing the equate of the previous hidden type with `u32` to use `handle_opaque_type` again?

File: compiler/rustc_borrowck/src/region_infer/opaque_types.rs [hunk 8]
```diff
@@ -372,13 +404,13 @@ fn check_opaque_type_well_formed<'tcx>(
         parent_def_id = tcx.local_parent(parent_def_id);
     }
 
-    // FIXME(-Znext-solver): We probably should use `DefiningAnchor::Bind(&[])`
+    // FIXME(-Znext-solver): We probably should use `&[]` instead of
```
Comment (lcnr) [inline compiler/rustc_borrowck/src/region_infer/opaque_types.rs:407]:
```suggestion
    // FIXME(-Znext-solver): We probably should use `&[]` instead
```

File: compiler/rustc_middle/src/traits/solve.rs [hunk 9]
```diff
@@ -114,7 +114,6 @@ impl MaybeCause {
...
-    pub anchor: DefiningAnchor<'tcx>,
```
[the remark this answers is not in the document]
Comment (lcnr) [reply compiler/rustc_middle/src/traits/solve.rs:117]: should look at the entire `Canonical`.

**Comment by lcnr** [comment]
r=me modulo the first two commits, don't feel confident in them and would like someone else, either @compiler-errors or @aliemjay to look at them

**Comment by oli-obk** [comment]
Note that all the first two commits do is turn a delayed bug into an error

File: compiler/rustc_borrowck/src/region_infer/opaque_types.rs [hunk 10]
```diff
@@ -275,11 +293,13 @@ impl<'tcx> RegionInferenceContext<'tcx> {
                     None => {
                         // Nothing exact found, so we pick the first one that we find.
                         let scc = self.constraint_sccs.scc(vid);
-                        for vid in self.rev_scc_graph.as_ref().unwrap().upper_bounds(scc) {
-                            match self.definitions[vid].external_name {
-                                None => {}
-                                Some(region) if region.is_static() => {}
-                                Some(region) => return region,
+                        if let Some(rev_scc_graph) = &self.rev_scc_graph {
```
Comment (lcnr) [inline compiler/rustc_borrowck/src/region_infer/opaque_types.rs:306]: when is the `rev_scc_graph` `None` here?

**Comment by lcnr** [comment]
yeah 🤔 after my last question, r=me. This does need an FCP though 😁

**Comment by oli-obk** [comment]
what's the FCP for specifically? 😆 I need to know that to write a summary that isn't just an explanation of how the impl is nicer now

**Comment by lcnr** [comment]
ICE to compiles and also should also avoid some ambiguity errors in trait selection for goals referencing an opaque outside of its defining scope

File: compiler/rustc_borrowck/src/region_infer/opaque_types.rs (hunk 7 above)
Comment (aliemjay) [reply compiler/rustc_borrowck/src/region_infer/opaque_types.rs:233]: By taking a glance, I guess it makes this fixes the first example of #115017. Please add it as a test.
It is interesting to see how it interacts with this issue as a whole.

**Review by aliemjay — COMMENTED** [review]
I approve the first commit. Regarding the second commit, "Work around delayed bugs not emitting errors for RPIT", the workaround would be unnecessary when #116891 lands, and thus it looks good to me as a temporary hack.

**Comment by oli-obk** [comment]
@rfcbot fcp merge

I propose to merge this change (modulo some minor bugfixes and additional tests). Effectively what changes is that we now perform hidden type registration in queries iff we are actually in a defining scope. Before this PR we opportunistically always assumed any opaque type (from the current crate) could be in its defining scope and returned the hidden types from the query. It was then the caller's obligation to check if these hidden types were actually legal to register and error if not.

This change thus has 3 effects:

* the implementation of opaque type handling in the old solver becomes more similar to the one in the new solver
* If you compare an opaque type with another type in a probe (that you then immediately roll back) in a query, you don't just get a successful type equality check, but properly check the defining scope. This means the compiler doesn't see different results depending on whether you do some operation in a query or not. This fixes some long-standing ICEs
* fewer opaque types (meaning those outside their defining scope) get treated as something that could be equal to anything else by the solver, and thus predicates with the opaque type as the `Self` type immediately error out or succeed, instead of resulting in ambiguity.

An example for an ICE that is now avoided:

```rust
fn rpit() -> impl Clone {}
fn same_output<Out>(_: impl Fn() -> Out, _: impl Fn() -> Out) {}
pub fn foo() -> impl Sized {
    same_output(rpit, foo);
    same_output(foo, rpit);
    //^ This used to ICE because we ended up registering a hidden type for `rpit`'s return type 
    rpit()
}
```

File: compiler/rustc_trait_selection/src/traits/query/type_op/mod.rs [hunk 11]
```diff
@@ -159,53 +159,66 @@ where
...
-                        progress = true;
-                        if let Certainty::Ambiguous = certainty {
-                            obligations.push(obligation);
+
+        let (mut output, _) = scrape_region_constraints(
+            infcx,
+            |_ocx| {
+                let (output, ei, mut obligations, _) =
+                    Q::fully_perform_into(self, infcx, &mut region_constraints, span)?;
+                error_info = ei;
```
Comment (oli-obk) [inline compiler/rustc_trait_selection/src/traits/query/type_op/mod.rs:170]: `fully_performwinto` invokes `instantiate_nll_query_response_and_region_obligations`, which then bubbles up hidden types found in the query.

While we already return region obligations directly from that query, bubbling up of opaque types can create new obligations when comparing an opaque type with its hidden type or when comparing a new hidden type against an already registered one.

**Comment by nikomatsakis** [comment]
@rfcbot reviewed

File: compiler/rustc_trait_selection/src/traits/query/type_op/mod.rs (hunk 11 above)
Comment (compiler-errors) [reply compiler/rustc_trait_selection/src/traits/query/type_op/mod.rs:170]: Can you put a FIXME here so that we can clean this up? Using the "full" `scrape_regions` seems really expensive here lol.

File: compiler/rustc_borrowck/src/region_infer/opaque_types.rs (hunk 10 above)
Comment (oli-obk) [reply compiler/rustc_borrowck/src/region_infer/opaque_types.rs]: Resolved by removing the relevant commits now that https://github.com/rust-lang/rust/pull/116891 has landed

File: compiler/rustc_borrowck/src/region_infer/opaque_types.rs (hunk 7 above)
Comment (oli-obk) [reply compiler/rustc_borrowck/src/region_infer/opaque_types.rs:139]: The first example already works on master

File: compiler/rustc_middle/src/infer/canonical.rs [hunk 12]
```diff
@@ -344,7 +342,8 @@ impl<'tcx> CanonicalParamEnvCache<'tcx> {
                 *canonical
             }
             Entry::Vacant(e) => {
-                let canonical = canonicalize_op(tcx, key, state);
+                let mut canonical = canonicalize_op(tcx, key, state);
+                canonical.defining_opaque_types = defining_opaque_types;
```
Comment (aliemjay) [inline compiler/rustc_middle/src/infer/canonical.rs:346]: The cache can be poisoned because the same ParamEnv can have different `defining_opaque_types`.

I prefer this method not to be concerned with `defining_opaque_types` at all and instead pass the responsibility to the caller.

File: compiler/rustc_infer/src/infer/canonical/canonicalizer.rs [hunk 13]
```diff
@@ -609,7 +611,12 @@ impl<'cx, 'tcx> Canonicalizer<'cx, 'tcx> {
             .max()
             .unwrap_or(ty::UniverseIndex::ROOT);
 
-        Canonical { max_universe, variables: canonical_variables, value: (base.value, out_value) }
+        Canonical {
```
Comment (aliemjay) [inline compiler/rustc_infer/src/infer/canonical/canonicalizer.rs:614]:
```suggestion
        assert!(!infcx.is_some_and(|infcx| infcx.defining_opaque_types != base.defining_opaque_types))
        Canonical {
```
This assertion would've caught this bug.

**Review by aliemjay — CHANGES_REQUESTED** [review]

File: compiler/rustc_middle/src/infer/canonical.rs (hunk 12 above)
Comment (oli-obk) [reply compiler/rustc_middle/src/infer/canonical.rs:346]: I don't understand the problem you're describing. i'll investigate caches to see if I can find more issues.

Note that handling it at the caller site is a huge footgun and we'll be chasing missing forwarding cases forever

Comment (aliemjay) [reply compiler/rustc_middle/src/infer/canonical.rs:346]: Here is a POC ICE. Please add it as regression test.
```rust
pub fn poison1() -> impl Sized where (): 'static, {}
pub fn poison2() -> impl Sized where (): 'static, {
    define_by_query((poison2, ()));
}
pub fn poison3() -> impl Sized where (): 'static, {}

trait Query {}
impl<Out, F: Fn() -> Out> Query for (F, Out) {}
fn define_by_query(_: impl Query) {}

fn main() {}
```

Comment (aliemjay) [reply compiler/rustc_middle/src/infer/canonical.rs:346]: Oh, I missed your comment.

> I don't understand the problem you're describing. i'll investigate caches to see if I can find more issues.

Here the cached value for `ParamEnv{(): 'static}`  would be `Canonical{ defining_opaque_types=poison1::opaque#1, value = _ }` which is not valid when used in fn `poison2`

> Note that handling it at the caller site is a huge footgun and we'll be chasing missing forwarding cases forever

With the assertion in `canonicalize_with_base`, I think it is safe enough. Either this or use set the field `define_opaque_types` in the case of cache hit as well.

**Comment by oli-obk** [comment]
hmm weird, a previous perf run was clean. I must have changed something since then. I'll investigate.

**Comment by oli-obk** [comment]
Ah... https://github.com/rust-lang/rust/pull/122077/commits/dd72bf922adae10276013b408c96f913331916e8

Scraping regions is expensive.

I'll implement an alternative. Let's not revert this PR, it's an important bugfix and blocker of a lot of follow up work
