### PR TITLE
remove expect() in `unnecessary_transmutes`

### LINKED ISSUE #140277: Path remapping ICE from `unnecessary_transmutes` suggestion
```
thread 'rustc' panicked at compiler/rustc_mir_transform/src/check_unnecessary_transmutes.rs:92:65:
ok: SourceNotAvailable { filename: Real(Remapped { local_path: None, virtual_name: "index.crates.io-1949cf8c6b5b557f/zerocopy-0.8.24/src/macros.rs" }) }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: please make sure that you have updated to the latest nightly

note: rustc 1.88.0-nightly (d7ea436a0 2025-04-24) running on x86_64-apple-darwin

note: compiler flags: --crate-type lib -C embed-bitcode=no -Z unstable-options -Z remap-path-scope=all -C prefer-dynamic -C debug-assertions=off -C overflow-checks=on -C rpath -C strip=debuginfo -Z unstable-options -C prefer-dynamic -C target-cpu=native -Z tune-cpu=native -Z binary-dep-depinfo -Z checksum-hash-algorithm=blake3

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [mir_built] building MIR for `x86_64::sse2::<impl at index.crates.io-1949cf8c6b5b557f/ppv-lite86-0.2.21/src/x86_64/sse2.rs:887:1: 887:64>::to_scalars`
#1 [check_unsafety] unsafety-checking `x86_64::sse2::<impl at index.crates.io-1949cf8c6b5b557f/ppv-lite86-0.2.21/src/x86_64/sse2.rs:887:1: 887:64>::to_scalars`
... and 1 other queries... use `env RUST_BACKTRACE=1` to see the full query stack

thread 'rustc' panicked at compiler/rustc_mir_transform/src/check_unnecessary_transmutes.rs:92:65:
ok: SourceNotAvailable { filename: Real(Remapped { local_path: None, virtual_name: "index.crates.io-1949cf8c6b5b557f/zerocopy-0.8.24/src/macros.rs" }) }

error: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: please make sure that you have updated to the latest nightly

note: rustc 1.88.0-nightly (d7ea436a0 2025-04-24) running on x86_64-apple-darwin

note: compiler flags: --crate-type lib -C embed-bitcode=no -Z unstable-options -Z remap-path-scope=all -C prefer-dynamic -C debug-assertions=off -C overflow-checks=on -C rpath -C strip=debuginfo -Z unstable-options -C prefer-dynamic -C target-cpu=native -Z tune-cpu=native -Z binary-dep-depinfo -Z checksum-hash-algorithm=blake3

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [mir_built] building MIR for `x86_64::sse2::avx2::<impl at index.crates.io-1949cf8c6b5b557f/ppv-lite86-0.2.21/src/x86_64/sse2.rs:1683:5: 1683:58>::to_scalars`
#1 [check_unsafety] unsafety-checking `x86_64::sse2::avx2::<impl at index.crates.io-1949cf8c6b5b557f/ppv-lite86-0.2.21/src/x86_64/sse2.rs:1683:5: 1683:58>::to_scalars`
```

### PR DESCRIPTION
**Pull request by bend-n**
removes expect() from #136083 and fixes #140277
includes regression test

r? lcnr

### CODE REVIEW

**Review by jieyouxu — CHANGES_REQUESTED** [review]
This needs a regression test, both to check that this fix indeed fixes the reported regression, and to make sure it doesn't regress in the future.

**Comment by jieyouxu** [comment]
#140277 has `-Z remap-path-scope=all`, that's probably necessarily for any smaller reproducer from that report

**Comment by jieyouxu** [comment]
r? jieyouxu

File: compiler/rustc_mir_transform/src/check_unnecessary_transmutes.rs [hunk 1]
```diff
@@ -89,7 +89,7 @@ impl<'tcx> Visitor<'tcx> for UnnecessaryTransmuteChecker<'_, 'tcx> {
             && let span = self.body.source_info(location).span
             && let Some(lint) = self.is_unnecessary_transmute(
                 func,
-                self.tcx.sess.source_map().span_to_snippet(arg).expect("ok"),
+                self.tcx.sess.source_map().span_to_snippet(arg).as_deref().unwrap_or("…"),
                 span,
             )
```
Comment (jieyouxu) [inline compiler/rustc_mir_transform/src/check_unnecessary_transmutes.rs:94]: Question: also, this fallback seems not ideal to me. I feel like we should not be making a *suggestion* if we don't have the source snippet to work with?

Comment (bend-n) [reply compiler/rustc_mir_transform/src/check_unnecessary_transmutes.rs:94]: im not sure. when i [searched up uses of span_to_snippet](https://github.com/search?q=repo%3Arust-lang%2Frust%20source_map().span_to_snippet&type=code), i found some examples of `let Ok() = ..to_snippet()` and some examples of `unwrap_or`... i think in the specific case of our repro, we do want this to lint, because it is part of the users problem.

Comment (jieyouxu) [reply compiler/rustc_mir_transform/src/check_unnecessary_transmutes.rs:94]: Or rather, stylistically, I would prefer to be faithful in `is_unnecessary_transmute` and report that we don't have a source snippet for `arg` to work with. And in `is_unnecessary_transmute`, there we *explicitly* change the suggestion level:

- If `arg` source snippet is `Some`, we make an `MaybeIncorrect` suggestion.
- However, if `arg` source snippet is N/A, we make an `HasPlaceholder` suggestion.

Comment (jieyouxu) [reply compiler/rustc_mir_transform/src/check_unnecessary_transmutes.rs:94]: EDIT: I don't mean not firing the *lint*, I mean the *suggestion* of the lint.

Comment (bend-n) [reply compiler/rustc_mir_transform/src/check_unnecessary_transmutes.rs:94]: i dont actually know if it matters, it seems that in our case it doesnt end up linting?

File: tests/ui/transmute/issue-140277.rs
Comment (jieyouxu) [inline tests/ui/transmute/issue-140277.rs:1]: Yeah, please call this and the aux file something more descriptive. Like idk `unnecessary-transmute-path-remap-ice-140277`

File: compiler/rustc_mir_transform/src/check_unnecessary_transmutes.rs (hunk 1 above)
Comment (jieyouxu) [reply compiler/rustc_mir_transform/src/check_unnecessary_transmutes.rs:94]: Hm, I think in this ICE we never even reach `is_unnecessary_transmute`, because it's the callsite `span_to_snippet` that ICEs. Still, I don't think we should use a dummy value here to paper over not having an `arg` snippet to work with. Instead of doing the `MaybeIncorrect`/`HasPlaceholder` dance, I'm also okay with just skipping the suggestion if we don't have an `arg` snippet to work with.

File: compiler/rustc_mir_transform/src/check_unnecessary_transmutes.rs [hunk 2]
```diff
@@ -87,11 +87,8 @@ impl<'tcx> Visitor<'tcx> for UnnecessaryTransmuteChecker<'_, 'tcx> {
             && let Some((func_def_id, _)) = func.const_fn_def()
             && self.tcx.is_intrinsic(func_def_id, sym::transmute)
             && let span = self.body.source_info(location).span
-            && let Some(lint) = self.is_unnecessary_transmute(
-                func,
-                self.tcx.sess.source_map().span_to_snippet(arg).expect("ok"),
-                span,
-            )
+            && let Ok(snippet) = self.tcx.sess.source_map().span_to_snippet(arg)
```
[the remark this answers is not in the document]
Comment (jieyouxu) [reply compiler/rustc_mir_transform/src/check_unnecessary_transmutes.rs:90]: I'm not sure if the original impl actually had tests for cross-crate tests involving macros and path remapping but yeah.

[the remark this answers is not in the document]
Comment (bend-n) [reply compiler/rustc_mir_transform/src/check_unnecessary_transmutes.rs:90]: > this can skip places where this lint previously could have linted
really? i figured there were no such places

[the remark this answers is not in the document]
Comment (jieyouxu) [reply compiler/rustc_mir_transform/src/check_unnecessary_transmutes.rs:90]: I can't immediately come up with a counter-example, and there isn't test coverage for this scenario, so I guess we can try to land this more blunt version until someone finds a counter-example.

File: tests/ui/transmute/unnecessary-transmute-path-remap-ice-140277.rs [hunk 3]
```diff
@@ -0,0 +1,7 @@
+//@ aux-crate: zerocopy=unnecessary-transmute-path-remap-ice-140277-trans.rs
+#![deny(unnecessary_transmutes)]
```
Comment (jieyouxu) [inline tests/ui/transmute/unnecessary-transmute-path-remap-ice-140277.rs:2]: Problem: we never fire the lint against this combination in the first place, this should be `//@ check-pass`. Please also add a comment to describe the test intention, i.e. regression test for #140277 where there was a `span_to_snippet` invocation prior to checking if transmute is unnecessary.

Comment (bend-n) [reply tests/ui/transmute/unnecessary-transmute-path-remap-ice-140277.rs:2]: whoops i forgot to remove that

**Review by jieyouxu — APPROVED** [review]
Thanks

**Comment by jieyouxu** [comment]
r=me after PR CI is green

@bors delegate+ rollup
