### PR TITLE
Fix popping singleton paths in when generating E0433

### LINKED ISSUE #82156: ICE instead of syntax error while calling super()
I tried to call default trait implementation from overriden method. Googling was not so useful as wanted so I started playing with "super" keyword and found this bug.

### Code
```Rust
fn main() {
    super();
}
```

### Meta
Bug appears both on stable and nightly

`rustc --version --verbose`:
```
rustc 1.50.0 (cb75ad5db 2021-02-10)
binary: rustc
commit-hash: cb75ad5db02783e8b0222fee363c5f63f7e2cf5b
commit-date: 2021-02-10
host: x86_64-unknown-linux-gnu
release: 1.50.0

rustc 1.52.0-nightly (e9920ef77 2021-02-11)
binary: rustc
commit-hash: e9920ef7749d11fc71cc32ca4ba055bcfeaab945
commit-date: 2021-02-11
host: x86_64-unknown-linux-gnu
release: 1.52.0-nightly
LLVM version: 11.0.1
```

### Error output

```
thread 'rustc' panicked at 'called `Option::unwrap()` on a `None` value', compiler/rustc_resolve/src/late/diagnostics.rs:138:36
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.50.0 (cb75ad5db 2021-02-10) running on x86_64-unknown-linux-gnu

query stack during panic:
end of query stack
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
stack backtrace:
   0: rust_begin_unwind
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/panicking.rs:493:5
   1: core::panicking::panic_fmt
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/core/src/panicking.rs:92:14
   2: core::panicking::panic
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/core/src/panicking.rs:50:5
   3: rustc_resolve::late::diagnostics::<impl rustc_resolve::late::LateResolutionVisitor>::smart_resolve_report_errors
   4: rustc_resolve::late::LateResolutionVisitor::smart_resolve_path_fragment
   5: rustc_resolve::late::LateResolutionVisitor::resolve_expr
   6: rustc_resolve::late::LateResolutionVisitor::resolve_expr
   7: <rustc_resolve::late::LateResolutionVisitor as rustc_ast::visit::Visitor>::visit_block
   8: <rustc_resolve::late::LateResolutionVisitor as rustc_ast::visit::Visitor>::visit_fn
   9: rustc_ast::visit::walk_item
  10: rustc_resolve::late::LateResolutionVisitor::resolve_item
  11: rustc_resolve::Resolver::resolve_crate
  12: rustc_interface::passes::configure_and_expand_inner
  13: rustc_interface::passes::configure_and_expand::{{closure}}
  14: rustc_data_structures::box_region::PinnedGenerator<I,A,R>::new
  15: rustc_interface::passes::configure_and_expand
  16: rustc_interface::queries::Queries::expansion
  17: rustc_interface::queries::<impl rustc_interface::interface::Compiler>::enter
  18: rustc_span::with_source_map
  19: rustc_interface::interface::create_compiler_and_run
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

</p>
</details>

### PR DESCRIPTION
**Pull request by osa1**
Fixes #82156

---

This was introduced with #72923, so pinging @Patryk27 for reviews.

### CODE REVIEW

File: compiler/rustc_resolve/src/late.rs [hunk 1]
```diff
@@ -1841,8 +1841,9 @@ impl<'a: 'ast, 'b, 'ast> LateResolutionVisitor<'a, 'b, 'ast> {
 
             // Before we start looking for candidates, we have to get our hands
             // on the type user is trying to perform invocation on; basically:
-            // we're transforming `HashMap::new` into just `HashMap`
-            let path = if let Some((_, path)) = path.split_last() {
+            // we're transforming `HashMap::new` into just `HashMap`.
+            let path = if path.len() >= 2 {
+                let (_, path) = path.split_last().unwrap();
```
Comment (Patryk27) [inline compiler/rustc_resolve/src/late.rs:1846]: How about `path.split_last().unwrap().1`?

**Review by Patryk27 — APPROVED** [review]
Hah, I wouldn't have figured out `super();` in the world 🙂

File: compiler/rustc_resolve/src/late.rs (hunk 1 above)
Comment (petrochenkov) [reply compiler/rustc_resolve/src/late.rs:1846]: I'd prefer to avoid an unwrap and keep the match, e.g.
```rust
match path.split_last() {
    ((_, path)) if !path.is_empty() => path,
    _ => return ...
}
```

File: src/test/ui/issues/issue-82156.rs [hunk 2]
```diff
@@ -0,0 +1,3 @@
+fn main() {
+    super(); //~ ERROR
```
Comment (petrochenkov) [inline src/test/ui/issues/issue-82156.rs:2]:
```suggestion
    super(); //~ ERROR failed to resolve: there are too many leading `super` keywords
```
Could you also move this test from `ui/issues` to `ui/resolve`?

File: compiler/rustc_resolve/src/late.rs (hunk 1 above)
Comment (osa1) [reply compiler/rustc_resolve/src/late.rs:1846]: Avoiding unwrap makes sense. Will update.

File: src/test/ui/issues/issue-82156.rs (hunk 2 above)
Comment (osa1) [reply src/test/ui/issues/issue-82156.rs:2]: I tried adding this message but for some reason the test runner wouldn't accept it. I'll try again.

Comment (osa1) [reply src/test/ui/issues/issue-82156.rs:2]: @petrochenkov what is the difference between 'resolve' and 'issues'?

**Comment by osa1** [comment]
@petrochenkov all done.

@rustbot label: +S-waiting-on-review -S-waiting-on-author

File: src/test/ui/issues/issue-82156.rs (hunk 2 above)
Comment (petrochenkov) [reply src/test/ui/issues/issue-82156.rs]: @osa1 
Grouping tests into the `issues` subdirectory is meaningless.
The general idea is for test subdirectories to be related to specific compiler or language areas, so they could have "owners" from the corresponding maintainers and working groups.
Also see https://github.com/rust-lang/rust/issues/73494 and related issues.

**Comment by apiraino** [comment]
beta nomination accepted, stable declined ([zulip discussion](https://rust-lang.zulipchat.com/#narrow/stream/238009-t-compiler.2Fmeetings/topic/.5Bweekly.20meeting.5D.202021-03-04.20.2354818/near/228788846))
