### PR TITLE
Don't allow upcasting to a supertype in the type of the match

### LINKED ISSUE #23116: ref mut bindings fail to enforce invariance
As originally "reported" [here](https://github.com/rust-lang/rfcs/pull/803#issuecomment-77545262), ref mut bindings are not working properly:

```rust
#![allow(dead_code)]
use std::fmt::Debug;
struct S(Box<Debug + 'static>);
impl S {
    fn bar<'a>(&'a mut self)->&'a mut Box<Debug + 'a> {
        match self.0 { ref mut x => x } // should not compile, but does
    }
}
fn main() {}
```

### PR DESCRIPTION
**Pull request by nikomatsakis**
Don't allow upcasting to a supertype in the type of the match discriminant. Fixes #23116.

This is a [breaking-change] in that it closes a type hole that previously existed.

r? @pnkfelix

### CODE REVIEW

File: src/test/compile-fail/match-ref-mut-invariance.rs [hunk 1]
```diff
@@ -0,0 +1,23 @@
...
+// Check that when making a ref mut binding with type `&mut T`, the
+// type `T` must match precisely the type `U` of the value being
+// matched, and in particular cannot be some supertype of `U`. Issue
+// #23116.
+
+#![allow(dead_code)]
+struct S<'b>(&'b i32);
+impl<'b> S<'b> {
+    fn bar<'a>(&'a mut self) -> &'a mut &'a i32 {
+        match self.0 { ref mut x => x }
```
Comment (jakub-) [inline src/test/compile-fail/match-ref-mut-invariance.rs]: Should this have an error message directive `//~ ERROR`?

**Comment by nikomatsakis** [comment]
Actually, there is a more serious problem here. In particular, it's not covering the case of `let ref mut x = ...`, which has a similar bug.

**Comment by nikomatsakis** [comment]
@pnkfelix ok I pushed a more comprehensive fix. See the comment.

**Comment by nikomatsakis** [comment]
Definitely wants re-review.

File: src/librustc/middle/pat_util.rs [hunk 2]
```diff
@@ -119,6 +119,24 @@ pub fn pat_contains_bindings(dm: &DefMap, pat: &ast::Pat) -> bool {
...
+    pat_bindings(dm, pat, |mode, _, _, _| {
+        match mode {
+            ast::BindingMode::BindByRef(_) => { result = true; }
+            ast::BindingMode::BindByValue(_) => { }
+        }
+    });
+    result
+}
+
+/// Checks if the pattern contains any patterns that bind something to
```
Comment (jakub-) [inline src/librustc/middle/pat_util.rs]: This comment seems wrong? It talks about by-value bindings.

**Comment by nrc** [comment]
lgtm, but I have no idea about match checking so probably better for Jakub to r? this

**Comment by nikomatsakis** [comment]
rebased, addressed nit by @jakub-
