### PR TITLE
rustc_target: avoid negative register counts in the SysV x86_64 ABI.

### LINKED ISSUE #62350: FFI broken with many parameters
We encountered this with WebRender, where we exposed a method in Rust to the Gecko, and the last parameters supplied appeared random on the Rust side. I made a reduced test case adapted from it that you can grab at:

https://github.com/aosmond/myrustffi

It is a very simple test case where the C++ program puts all the parameters on the stack, prints the expected values of some of them, and calls the Rust method. The Rust method prints the values it received. We have enough parameters to fill up the registers used in the calling convention, and once we get to pushing things on the stack, it goes wrong. You can see from the output that they mismatch.

./build-debug.sh && ./run-debug.sh

outputs

c++ expect width=7 height=8
c++ expect slice=9 10 11 12
c++ expect outset=13.000000 13.100000 13.200000 13.300000
c++ expect repeat h=0 v=0

got rust image 6 width 7 height 8
got rust slice SideOffsets { top: 9, right: 10, bottom: 11, left: 12 }
got rust outset LayoutGeometry { top: 0.0, left: 0.0, width: 0.0, height: 0.0 }
got rust repeat h=26 v=58

Note that the earlier parameters are correct, but the last 3 (outset, repeat h and repeat v) are all incorrect.

### PR DESCRIPTION
**Pull request by eddyb**
Because `needed_{int,sse}` and `{int,sse}_regs` were only used with integer literals, they were inferred to `i32` and `{int,sse}_regs` could therefore be negative.
There was a check which prevented that, but *only* for aggregate arguments, not scalars.

Fixes #62350.

r? @nagisa or @rkruppe

### CODE REVIEW

File: src/librustc_target/abi/call/x86_64.rs [hunk 1]
```diff
@@ -171,25 +171,34 @@ pub fn compute_abi_info<'a, Ty, C>(cx: &C, fty: &mut FnType<'a, Ty>)
...
                     match c {
                         Some(Class::Int) => needed_int += 1,
                         Some(Class::Sse) => needed_sse += 1,
                         _ => {}
                     }
                 }
-                if arg.layout.is_aggregate() && (int_regs < needed_int || sse_regs < needed_sse) {
-                    cls_or_mem = Err(Memory);
+                if int_regs >= needed_int && sse_regs >= needed_sse {
+                    int_regs -= needed_int;
```
Comment (nagisa) [inline src/librustc_target/abi/call/x86_64.rs]: Should this be `wrapping_sub`?

File: src/test/run-pass/issues/issue-62350.rs [hunk 2]
```diff
@@ -0,0 +1,46 @@
+// run-pass
```
Comment (nagisa) [inline src/test/run-pass/issues/issue-62350.rs]: How is this test different from code added to `abi-sysv64-arg-passing`?

Comment (eddyb) [reply src/test/run-pass/issues/issue-62350.rs]: That test contains duplicates of all the SysV x64 tests, this is the real test.

File: src/librustc_target/abi/call/x86_64.rs (hunk 1 above)
Comment (eddyb) [reply src/librustc_target/abi/call/x86_64.rs]: Definitely not, we don't want it to wrap around.
In fact, I could replace the compares and subtracts with `checked_sub`s.

**Comment by Centril** [comment]
cc https://github.com/rust-lang/rust/issues/62401

**Comment by eddyb** [comment]
Nominated for backporting to beta as per https://github.com/rust-lang/rust/issues/62350#issuecomment-510385292 and @Gankro's reply.
