### PR TITLE
Make the specialized Fuse still deal with None

### LINKED ISSUE #85863: iter::Fuse is unsound with how specialization currently behaves around HRTB fn pointers
## New high-level explanation of this issue, also covering #85873

`Fuse<T>` and `Zip<T, U>` have optimizations relying on specialization if their type parameters implement a trait (`FusedIterator` or `TrustedRandomAccess`, respectively).

These optimizations fundamentally change the way the iterator operates.

All type arguments are covariant. Coercing e.g. `Fuse<T>` to `Fuse<U>` if `U` is a subtype of `T` can “switch between” these fundamentally different ways of operation if `T: !FusedIterator` and `U: FusedIterator` which can bring the iterator into an invalid state that can cause UB; the same kind of problem exists for `Zip`.

For `Zip`, this problem can be avoided if `TrustedRandomAccess` never differs between types and subtypes. `Copy`-dependent impls for e.g. `vec::IntoIter` have to be removed (PR #85874).

Regarding `Fuse`: `FusedIterator` is a safe public trait, this is problematic. Some possible fixes: Either change `Fuse` to not get into a UB-causing invalid state by such a coercion (which kills some (or perhaps most) of the optimization offered by `Fuse`), or make `Fuse` invariant (but that’s a breaking change!). [Here’s another possible approach, but this one requires new language features](https://github.com/rust-lang/rust/issues/85863#issuecomment-853927262) and could be done in the future if an immediate fix that just makes `Fuse` less performant is taken now.

Specialization not differentiating between e.g. `Foo<'a>` and `Foo<'b>` made this issue harder to spot.
But `fn(&())` (that is, `for<'a> fn(&'a ())`) is a ~supertype~ _[edited:] subtype_ of `fn(&'static ())` and those are entirely different types.

<hr>

#### Previous start of issue description
<br>

```rust
use std::{
    iter::{Fuse, FusedIterator},
    marker::PhantomData,
};

struct MyEmptyIterator<T>(PhantomData<T>, &'static str);
impl<T> Iterator for MyEmptyIterator<T> {
    type Item = T;

    fn next(&mut self) -> Option<Self::Item> {
        println!("called next, {}", self.1);
        None
    }
}

impl FusedIterator for MyEmptyIterator<fn(&'static ())> {}

fn main() {
    let mut f = MyEmptyIterator::<fn(&())>(PhantomData, "Hello, World").fuse();
    f.next();
    let mut f = f as Fuse<MyEmptyIterator<fn(&'static ())>>;
    f.next();
}
```
```
   Compiling playground v0.0.1 (/playground)
    Finished dev [unoptimized + debuginfo] target(s) in 1.74s
     Running `target/debug/playground`
timeout: the monitored command dumped core
/playground/tools/entrypoint.sh: line 11:     8 Segmentation fault      timeout --signal=KILL ${timeout} "$@"
Standard Output
called next, Hello, World
```
([playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=454884ffffcb4e6ba611712d7a929433))

@rustbot label T-libs, T-libs-impl, T-compiler, A-specialization, A-iterators, A-typesystem, A-lifetimes, A-traits, C-bug
~~someone please add the unsound label~~ thanks

## Explanation
The types `for<'a> fn(&'a ())` (i.e. `fn(&())`) and `fn(&'static ())` do seem to be distinguished by rust’s specialization. (I.e. the difference between the two types is not erased before the trait impl for specializing on `FusedIterator` is chosen.) But it’s also possible to convert `Fuse<MyEmptyIterator<fn(&i32)>>` into `Fuse<MyEmptyIterator<fn(&'static i32)>>`. This way, the first call to `.next()` will use unspecialized code and write a `None` value into the field of `Fuse`, whereas the second call will use the specialized version that uses `intrinsics::unreachable()` to unwrap the contained `Option`.

~~I haven’t tested it, but I’d guess that~~ the same thing might be possible using HRTB trait objects instead of function pointers. _(See comment [below](https://github.com/rust-lang/rust/issues/85863#issuecomment-852326566).)_

## Possible fixes
This soundness issue would probably go away if, somehow, specialization would also consider types such as `fn(&())` and `fn(&'static ())` to be “the same type”. _**Edit2:** I don’t think that this approach is reasonable, and it’s probably even impossible._

The easiest / fastest fix for now would probably be to remove all the `intrinsics::unreachable()` assertions in the implementation of `Fuse` and replace them either with `panic`s (which results in unexpected panicking but at least no unsoundness), or replace them with code that “properly” handles the `None` case as the iterator being empty. In either case, performance benefits from `FusedIterator` implementations could probably somewhat be retained by somehow marking the `Some` case as the hot path and the `None` case as a cold path. (In the approach with the `None` case panicking, this would probably be automatically considered the cold path due to the panic.)

_Edit:_ Yet another alternative fix is to make `Fuse<T>` invariant over `T`.

### PR DESCRIPTION
**Pull request by cuviper**
Fixes #85863 by removing the assumption that we'll never see a cleared iterator in the `I: FusedIterator` specialization. Now all `Fuse` methods check for the possibility that `self.iter` is `None`, and the specialization only avoids _setting_ that to `None` in `&mut self` methods.

### CODE REVIEW

**Comment by cuviper** [comment]
Queuing for a performance run, especially relative to #86766.

@bors try @rust-timer queue

File: library/core/src/iter/adapters/fuse.rs [hunk 1]
```diff
@@ -507,43 +422,6 @@ where
...
-{
-    type Source = S;
-
-    #[inline]
-    unsafe fn as_inner(&mut self) -> &mut S {
-        match self.iter {
-            // SAFETY: unsafe function forwarding to unsafe function with the same requirements
-            Some(ref mut iter) => unsafe { SourceIter::as_inner(iter) },
-            // SAFETY: the specialized iterator never sets `None`
-            None => unsafe { intrinsics::unreachable() },
```
Comment (the8472) [inline library/core/src/iter/adapters/fuse.rs:543]: The trait impl is being removed due to the unreachable here, right? I think it might be possible to replace this with a panic instead.

If someone pulled the HRTB shenaningans then it would only lead to a panic, not to unsafety. If that's not good enough then maybe `SourceIter` could be changed to return an `Option<&mut>`.

**Comment by joshtriplett** [comment]
Reviewing on the basis of the code here looking reasonable, relying on other statements that this fixes the underlying problem it intends to fix.

@bors r+

File: library/core/src/iter/adapters/fuse.rs (hunk 1 above)
Comment (cuviper) [reply library/core/src/iter/adapters/fuse.rs:543]: I personally don't think we should use a panic for code that is otherwise allowable, however weird it may be.

Changing `SourceIter` to return an `Option` sounds promising, assuming there actually is a reasonable fallback at the caller -- I suppose going back to normal not-in-place collection. Then you wouldn't even need the seemingly-unrelated `I: FusedIterator` constraint here.

Comment (the8472) [reply library/core/src/iter/adapters/fuse.rs:543]: >  I suppose going back to normal not-in-place collection. 

That would probably be bad for compile times since it would have to add two different code paths in that case.

If we can assume that `None` implies an exhausted iterator then it could work and simply return an empty Vec. But I'll have to look through all the implementations to see if that's a valid assumption.

Comment (the8472) [reply library/core/src/iter/adapters/fuse.rs:543]: > Then you wouldn't even need the seemingly-unrelated I: FusedIterator constraint here.

In place iteration works roughly like this

1. retrieve source iter to get a write pointer
2. perform loop that gets elements through tie iterators and writes to the pointer
3. retrieve source iter again to drop the remainder and then steal the allocation

Which means that once we have started iterating the source must stay retrievable. Which means the iterator cannot be fused through the option because that would drop the source. So it can only work for `FusedIterator` which doesn't switch the option variant.

Under those circumstances it should be safe since user code doesn't have access to the iterator during that time and can't do the variance coercion.

Comment (cuviper) [reply library/core/src/iter/adapters/fuse.rs:543]: OK, yeah, you need it to not drop. I agree the user doesn't have access during your steps, but they could have played the variance game before it got there at all, so it might be `None` to start with. Then an empty collection is fine.
