### PR TITLE
Fix error codes check run and ensure it will not go unnoticed again

### LINKED ISSUE #83268: Error code linter should detect when an error code isn't checked in its explanation
From this [comment](https://github.com/rust-lang/rust/pull/83213/files/a4d729a6d8d4e5c003de65b7599e6f1f75bdb7d2#diff-3080a67cb86325ee79bb8a820e1f4f533616730880ad3dd741219638cd0a0744).

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Fixes #83268.

The error codes explanations were not checked anymore. I fixed this issue and also added variables to ensure that this won't happen again (at least not silently).

### CODE REVIEW

File: src/tools/tidy/src/main.rs [hunk 1]
```diff
@@ -31,7 +31,7 @@ fn main() {
 
     // Checks that only make sense for the compiler.
     errors::check(&compiler_path, &mut bad);
-    error_codes_check::check(&src_path, &mut bad);
+    error_codes_check::check(&[&src_path, &compiler_path], &mut bad);
```
Comment (Mark-Simulacrum) [inline src/tools/tidy/src/main.rs:34]: Hm, what error codes exist under src/? Should we actually split this into two separate passes, one to collect tests under src/test/ui/error-codes and the other for errors in the compiler?

Comment (GuillaumeGomez) [reply src/tools/tidy/src/main.rs:34]: Under `src` are the tests. We check that all error codes are emitted at least in one test. I think it'd be hard to split the two parts considering that on one side we iterate over all emitted error codes and on the other we list all error codes. At the end, we check that all listed error codes have been tested once.

**Comment by GuillaumeGomez** [comment]
ping @Mark-Simulacrum

**Comment by Mark-Simulacrum** [comment]
OK, seems reasonable enough. Thanks.

@bors r+ rollup=iffy

**Comment by GuillaumeGomez** [comment]
Fixed conflicts.

@bors: r=Mark-Simulacrum
