### PR TITLE
impl Pattern for char array

### LINKED ISSUE #39511: Literal `&[char]` patterns clumsily require an `as` conversion
Many `str` methods accept patterns of any type that implements the `std::str::pattern::Pattern` trait. One such type is `&[char]`, which matches any single character mentioned in the pattern slice.

However, `&[char]` patterns are not as nice to use as one might hope. This does not compile:
```
        let code = "\t    function noodle() { ";
        assert_eq!(code.trim_left_matches(&[' ', '\t']),
                   "function noodle() { ");
```
Rust complains:
```
error[E0277]: the trait bound `[char; 2]: std::ops::Fn<(char,)>` is not satisfied
   --> lib.rs:689:29
    |
689 |             assert_eq!(code.trim_left_matches(&[' ', '\t']),
    |                             ^^^^^^^^^^^^^^^^^ the trait `std::ops::Fn<(char,)>` is not implemented for `[char; 2]`
    |
    = note: required because of the requirements on the impl of `std::ops::FnOnce<(char,)>` for `&[char; 2]`
    = note: required because of the requirements on the impl of `std::str::pattern::Pattern<'_>` for `&[char; 2]`
```
The `trim_left_matches` method constrains its argument type `P` with `P: Pattern`, and Rust won't apply the usual type coercions like `&[T; N]` to `&[T]` in order to satisfy trait bounds.

One must instead write:
```
            let code = "\t    function noodle() { ";
            assert_eq!(code.trim_left_matches(&[' ', '\t'] as &[char]),
                       "function noodle() { ");
```
It's not a tragedy, but it's not pretty either.

CC @alexcrichton

### LINKED ISSUE #86329: `&[char;_]:` doesn't implement `Pattern` while `&[char]` does
I tried this code:

```rust
fn main(){
    println!("{}","foo:bar".split(&[':']).collect::<Vec<_>>())
}
```

I expected to see this happen: Outputs `["foo","bar"]`

Instead, this happened (playground output: https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018):
```
rror[E0277]: expected a `Fn<(char,)>` closure, found `[char; 1]`
 --> src/main.rs:1:44
  |
1 | fn main(){println!("{:?}",{"foo:bar".split(&[':']).collect::<Vec<_>>()});}
  |                                            ^^^^^^ expected an `Fn<(char,)>` closure, found `[char; 1]`
  |
  = help: the trait `Fn<(char,)>` is not implemented for `[char; 1]`
  = note: required because of the requirements on the impl of `FnOnce<(char,)>` for `&[char; 1]`
  = note: required because of the requirements on the impl of `Pattern<'_>` for `&[char; 1]`

error[E0599]: the method `collect` exists for struct `std::str::Split<'_, &[char; 1]>`, but its trait bounds were not satisfied
   --> src/main.rs:1:52
    |
1   |   fn main(){println!("{:?}",{"foo:bar".split(&[':']).collect::<Vec<_>>()});}
    |                                                      ^^^^^^^ method cannot be called on `std::str::Split<'_, &[char; 1]>` due to unsatisfied trait bounds
    |
    = note: the following trait bounds were not satisfied:
            `&[char; 1]: Pattern<'_>`
            which is required by `std::str::Split<'_, &[char; 1]>: Iterator`
            `std::str::Split<'_, &[char; 1]>: Iterator`
            which is required by `&mut std::str::Split<'_, &[char; 1]>: Iterator`

error: aborting due to 2 previous errors

Some errors have detailed explanations: E0277, E0599.
For more information about an error, try `rustc --explain E0277`.
```

### Meta

`rustc --version --verbose`:
```
rustc 1.55.0 nightly (2021.06.14)
```

No backtrace for diagnostic

</p>
</details>

### Further Information

There are two issues here, for one, the diagnostic is somewhat confusing. I expect that an array is not a closure, but I would expect it to be a pattern (Thus, telling me it isn't a closure isn't helpful to me). The second is the actual issue that references to arrays aren't Patterns.
According to the `.split` docs, it's valid to pass a slice of `char` to `split` as the pattern. It should follow that you can pass a reference to an array to `.split`, because references to arrays coerce to references to slices. 

Both issues could be fixed with `impl<const N: usize> Pattern for &[char;N]{...}` in the stdlib. It may also be useful (and was brought up in discussion on the Rust Community Discord), for a non-reference impl `impl<const N: usize> Pattern for [char;N]{...}`. In the former case, it should be achievable by delegating to the slice impl. I am unfamiliar with the implementation in particular, but the same may also be reasonable for the by-value array case.

### PR DESCRIPTION
**Pull request by camsteffen**
Closes #39511
Closes #86329

### CODE REVIEW

File: library/core/src/str/pattern.rs [hunk 1]
```diff
@@ -601,6 +608,17 @@ where
...
 }
 
+impl<const N: usize> MultiCharEq for &[char; N] {
+    #[inline]
+    fn matches(&mut self, c: char) -> bool {
+        match N {
+            0 => false,
+            1 => self[0] == c,
+            _ => self.iter().any(|&m| m == c),
+        }
```
Comment (camsteffen) [inline library/core/src/str/pattern.rs:618]: Actually I think I should leave the N optimization to the compiler...

File: library/core/src/str/pattern.rs [hunk 2]
```diff
@@ -601,6 +608,17 @@ where
     }
 }
 
+impl<const N: usize> MultiCharEq for &[char; N] {
```
Comment (scottmcm) [inline library/core/src/str/pattern.rs:611]: This might be a silly question, but why `for &[char; N]` instead of `for [char; N]`?

File: library/core/src/str/pattern.rs [hunk 3]
```diff
@@ -79,6 +81,11 @@ use crate::slice::memchr;
 /// assert_eq!("abaaa".find('b'), Some(1));
 /// assert_eq!("abaaa".find('c'), None);
 ///
+/// // &[char; N]
+/// assert_eq!("ab".find(&['b', 'a']), Some(0));
```
Comment (scottmcm) [inline library/core/src/str/pattern.rs:85]: Could this be made to work with `assert_eq!("ab".find(['b', 'a']), Some(0));` too?  (AKA no `&`.)

File: library/core/src/str/pattern.rs (hunk 2 above)
Comment (camsteffen) [reply library/core/src/str/pattern.rs:611]: Actually that's what I started with, but then I figured this is more flexible/performant for large arrays. Definitely open to discussion on that. Maybe add both?

Comment (cuviper) [reply library/core/src/str/pattern.rs:611]: I think you do want the reference to solve those bugs where one intends to write a literal `&[char]` slice pattern, but it's really `&[char; N]`.

Comment (scottmcm) [reply library/core/src/str/pattern.rs:611]: I think both -- `['o', 'l']` for the simple case, and `&[...]` for the case cuviper mentions.

(I might just delegate both to the impl for slices, though, if there's an easy way to do that.)

File: library/core/src/str/pattern.rs (hunk 1 above)
Comment (scottmcm) [reply library/core/src/str/pattern.rs:618]: That makes sense to me -- especially since `.find(&[])` feels rather unlikely anyway.

File: library/core/src/str/pattern.rs (hunk 2 above)
Comment (camsteffen) [reply library/core/src/str/pattern.rs:618]: Okay, added both. Unfortunately lifetimes force a lot of separate impls to satisfy `into_searcher`.

**Review by dtolnay — APPROVED** [review]

**Comment by dtolnay** [comment]
@rust-lang/libs-api:
@rfcbot fcp merge

This PR adds `impl<'a, const N: usize> Pattern<'a> for [char; N]` and `impl<'a, 'b, const N: usize> Pattern<'a> for &'b [char; N]`, which allows `str::find` and similar methods based on `Pattern` to work as:

```rust
"...".find([' ', '\r', '\n'])
// or:
"...".find(&[' ', '\r', '\n'])
```

whereas before, due to #39511, it would have had to be written as:

```rust
"...".find(&[' ', '\r', '\n'][..])
```

**Comment by camsteffen** [comment]
Squashed a fixup commit

**Comment by camelid** [comment]
Should `relnotes` be added since IIUC this is insta-stable (even though `Pattern` itself is not stable)?

**Comment by camsteffen** [comment]
@dtolnay you approved the changes in Github. Is that grounds to `r=yoself`?

**Comment by camelid** [comment]
(Adding `relnotes` since this is insta-stable.)

**Comment by pnkfelix** [comment]
visiting for triage.

The only benchmarks that regressed did so by a small amount, percentage wise 0.2-0.6%; the benchmarks that did regress in that fashion are deeply-nested-async, helloworld, unify-linearly.

I am surprised that this change caused even this minor regression, but I don't think its worth investing effort trying to figure out why, unless someone wants to take it on as a self-educating exercise.

@rustbot label: +perf-regression-triaged
