### PR TITLE
Recover most `impl Trait` and `dyn Trait` lifetime bound suggestions under NLL

### LINKED ISSUE #96277: [NLL] Loss of suggestions to change/fix trait object lifetime bound
For tests like:
* [src/test/ui/regions/regions-close-object-into-object-2.rs](https://github.com/rust-lang/rust/tree/master/src/test/ui/regions/regions-close-object-into-object-2.rs)

In NLL mode, we loose suggestions to change trait object lifetime bound like:
```
help: consider changing the trait object's explicit `'static` bound to the lifetime of argument `v`
   |
LL | fn g<'a, T: 'static>(v: Box<dyn A<T> + 'a>) -> Box<dyn X + 'a> {
   |                                                            ~~
```
or
```
help: alternatively, add an explicit `'static` bound to this reference
   |
LL | fn g<'a, T: 'static>(v: Box<(dyn A<T> + 'static)>) -> Box<dyn X + 'static> {
   |                         ~~~~~~~~~~~~~~~~~~~~~~~~~
```
The latter mentions a reference which is a bit wrong in this case since only `Box`-es are involved but it can probably be solved separately.
In any case, we should re-instate those suggestions in NLL mode.

@rustbot label +A-NLL +NLL-diagnostics

### PR DESCRIPTION
**Pull request by marmeladema**
This is done by replacing the duplicated (and very partial) implementation from borrowck with one inspsired from `NiceRegionError::try_report_static_impl_trait` and by re-using `suggest_new_region_bound`.

Fixes #96277

r? @jackh726

### CODE REVIEW

File: compiler/rustc_infer/src/infer/error_reporting/nice_region_error/util.rs [hunk 1]
```diff
@@ -22,76 +23,83 @@ pub(super) struct AnonymousParamInfo<'tcx> {
...
+// &hir::Param of the function parameter corresponding to the anonymous
+// region and the Ty corresponding to the named region.
+// Currently only the case where the function declaration consists of
+// one named region and one anonymous region is handled.
+// Consider the example `fn foo<'a>(x: &'a i32, y: &i32) -> &'a i32`
+// Here, we would return the hir::Param for y, we return the type &'a
+// i32, which is the type of y but with the anonymous region replaced
+// with 'a, the corresponding bound region and is_first which is true if
+// the hir::Param is the first parameter in the function declaration.
+pub fn find_param_with_region<'tcx>(
```
Comment (marmeladema) [inline compiler/rustc_infer/src/infer/error_reporting/nice_region_error/util.rs:37]: This has just been split out from `NiceRegionError::find_param_with_region` as a free standing function.

**Comment by jackh726** [comment]
Good job on this :) Did you bless with compare-mode=nll? (CI will catch it, but figured I would bring it up if you didn't and there's potentially anything that changes) 

@bors r+
