### PR TITLE
stabilize `const_extern_fn`

### LINKED ISSUE #64926: Tracking issue for `const extern fn` and `const unsafe extern fn`
This is a tracking issue for implementing and stabilizing defining a `const extern fn` and `const unsafe extern fn`

- [X] Add a test according to https://github.com/rust-lang/rust/pull/64906#issuecomment-539902772 (added in https://github.com/rust-lang/rust/pull/68370)

## Summary

This allows writing `const unsafe extern "calling-convention" fn` and `const extern "calling-convention" fn`:

Today Rust and C calling conventions are stable (as of 1.62, see #95346). All other calling conventions are still unstable.

```rust
const extern fn foo1(val: u8) -> u8 { val + 1 }
const extern "C" fn foo2(val: u8) -> u8 { val + 1}
const unsafe extern fn bar1(val: bool) -> bool { !val }
const unsafe extern "C" fn bar2(val: bool) -> bool { !val }
```

This can be used to const-ify an `extern fn` (or equivalently, to make a `const fn` callable from external code).

## Test cases

1. Test for defining and calling in Rust code: https://github.com/rust-lang/rust/blob/master/src/test/ui/consts/const-extern-fn/const-extern-fn.rs
2. Test that calling with the wrong calling convention (from a `const` context) leads to an error: https://github.com/rust-lang/rust/blob/master/src/test/ui/consts/miri_unleashed/abi-mismatch.rs

### PR DESCRIPTION
**Pull request by folkertdev**
closes https://github.com/rust-lang/rust/issues/64926

tracking issue: https://github.com/rust-lang/rust/issues/64926
reference PR: https://github.com/rust-lang/reference/pull/1596

### Summary

Using `const extern "Rust"` and `const extern "C"` was already stabilized (since version 1.62.0, see https://github.com/rust-lang/rust/pull/95346). This PR stabilizes the other calling conventions: it is now possible to write  `const unsafe extern "calling-convention" fn` and `const extern "calling-convention" fn` for any supported calling convention:

```rust
const extern "C-unwind" fn foo1(val: u8) -> u8 { val + 1}
const extern "stdcall" fn foo2(val: u8) -> u8 { val + 1}
const unsafe extern "C-unwind" fn bar1(val: bool) -> bool { !val }
const unsafe extern "stdcall" fn bar2(val: bool) -> bool { !val }
```

This can be used to const-ify an `extern fn`, or conversely, to make a `const fn` callable from external code.

r? T-lang

cc @RalfJung

### CODE REVIEW

**Comment by RalfJung** [comment]
The unstable book is auto-generated, AFAIK.

Cc @rust-lang/wg-const-eval 
As already mentioned in https://github.com/rust-lang/rust/issues/64926, I see no reason why other ABIs would somehow behave differently here.

File: tests/ui/consts/const-extern-fn/const-extern-fn.rs
Comment (RalfJung) [inline tests/ui/consts/const-extern-fn/const-extern-fn.rs:1]: Can you add a `C-unwind` function in this test?

**Comment by traviscross** [comment]
@folkertdev: Perhaps you're working on it in parallel, but you'll want to add more in the way of a stabilization report to the PR description here (see e.g. the recent stabilizations from RalfJ for some examples).

File: src/tools/clippy/clippy_config/src/msrvs.rs [hunk 1]
```diff
@@ -17,7 +17,8 @@ macro_rules! msrv_aliases {
 
 // names may refer to stabilized feature flags or library items
 msrv_aliases! {
-    1,81,0  { LINT_REASONS_STABILIZATION }
+    1,82,0 { CONST_EXTERN_FN }
+    1,81,0 { LINT_REASONS_STABILIZATION }
```
Comment (folkertdev) [inline src/tools/clippy/clippy_config/src/msrvs.rs:21]: if anyone from clippy is following along, is there some equivalent of `CURRENT_RUSTC_VERSION` here? In any case given that we're close to a rust release this may or may not be accurate when merged

**Comment by folkertdev** [comment]
@traviscross allright I copied and slightly updated some text from the tracking issue. Let me know if there's something else that should be included.

**Comment by traviscross** [comment]
Why hadn't we stabilized this any sooner?  I.e., are there any tricky questions here, open questions that have recently been answered, or recent implementation work done to make this ready?

**Comment by RalfJung** [comment]
I have no idea why https://github.com/rust-lang/rust/pull/95346 only stabilized "Rust" and "C". Maybe @Aaron1011 remembers?

**Comment by traviscross** [comment]
@rfcbot fcp merge

We talked about this in triage, and this sounded good to us all.

**Comment by traviscross** [comment]
@rfcbot fcp cancel

**Comment by traviscross** [comment]
@rfcbot fcp merge

We talked about this in triage, and this sounded good to us all.

**Comment by nikomatsakis** [comment]
@rfcbot reviewed

**Comment by folkertdev** [comment]
cool, just fixed a merge conflict and squashed all commits into one

File: src/tools/clippy/tests/ui/missing_const_for_fn/could_be_const_with_const_extern_fn.fixed
Comment (RalfJung) [inline src/tools/clippy/tests/ui/missing_const_for_fn/could_be_const_with_const_extern_fn.fixed:1]: This seems like it should now be merged into `could_be_const.rs`? They were previously separate because this test enabled the feature gate, and the other did not.

**Comment by RalfJung** [comment]
r=me for the rustc side. The clippy side seems reasonably simple but I think the test can be merged with another test file now.

File: src/tools/clippy/tests/ui/missing_const_for_fn/could_be_const_with_const_extern_fn.fixed
Comment (folkertdev) [reply src/tools/clippy/tests/ui/missing_const_for_fn/could_be_const_with_const_extern_fn.fixed:1]: true, done
