### PR TITLE
Delay specific span_bug() call until abort_if_errors()

### LINKED ISSUE #22897: ICE: cat_expr Errd from array of unconstrained type -- { []; }
Test case:

    fn main() { []; }

Output:

    $ RUST_BACKTRACE=1 rustc test.rs 
    test.rs:1:13: 1:15 error: internal compiler error: cat_expr Errd
    test.rs:1 fn main() { []; }
                          ^~
    note: the compiler unexpectedly panicked. this is a bug.
    note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
    note: run with `RUST_BACKTRACE=1` for a backtrace
    thread 'rustc' panicked at 'Box<Any>', /home/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libsyntax/diagnostic.rs:129

    stack backtrace:
       1:         0xcc029720 - sys::backtrace::write::h66f3f2784d0f6c5ddgA
       2:         0xcc051b80 - panicking::on_panic::h6fdde9e4e9166fe6jaJ
       3:         0xcbf91c30 - rt::unwind::begin_unwind_inner::hba10c536ef2aae75MQI
       4:         0xc92a10c0 - rt::unwind::begin_unwind::h11287547919384241778
       5:         0xc92a1050 - diagnostic::SpanHandler::span_bug::h551f703868554ecfUBD
       6:         0xc9e32fe0 - session::Session::span_bug::h10f6b5fdbea6485fbjp
       7:         0xcb6c5920 - check::regionck::visit_expr::hc78138689559ecf8Yrd
       8:         0xcb6c35c0 - check::regionck::Rcx<'a, 'tcx>::visit_fn_body::h75e2fac33dc50b43a4c
       9:         0xcb75ee50 - check::check_bare_fn::hf42e5aabaa5cb880Oan
      10:         0xcb756f40 - check::check_item::hdbe569c101f96905stn
      11:         0xcb822f10 - check_crate::closure.36015
      12:         0xcb81d9c0 - check_crate::h9d44bf3fde687089EXB
      13:         0xcc6a38c0 - driver::phase_3_run_analysis_passes::h36c633d41f11ca74wFa
      14:         0xcc689ec0 - driver::compile_input::h0de317319ab5c701Hba
      15:         0xcc754e20 - run_compiler::hffa0c0711e361de8E5b
      16:         0xcc753720 - thunk::F.Invoke<A, R>::invoke::h12673221910893163557
      17:         0xcc752610 - rt::unwind::try::try_fn::h15130568597725528481
      18:         0xcc0bd740 - rust_try_inner
      19:         0xcc0bd730 - rust_try
      20:         0xcc752910 - thunk::F.Invoke<A, R>::invoke::h3924406537784056782
      21:         0xcc03d990 - sys::thread::thread_start::h3734be2229bd3edegEE
      22:         0xc5f650c0 - start_thread
      23:         0xcbc0a449 - __clone
      24:                0x0 - <unknown>

Compiler version:

    rustc 1.0.0-nightly (b47aebe3f 2015-02-26) (built 2015-02-27)
    binary: rustc
    commit-hash: b47aebe3fc2da06c760fd8ea19f84cbc41d34831
    commit-date: 2015-02-26
    build-date: 2015-02-27
    host: x86_64-unknown-linux-gnu
    release: 1.0.0-nightly

I modified the test case in #22894 by moving the `&*""` into `fn main()`, and I saw the same ICE.  I then changed the `""` to the similar `&[]`, and I saw an ICE with a different error message and a different stack trace (e.g. phase 3 instead of phase 4).  The `&` and `*` are unnecessary.

I also see the `cat_expr Errd` message in #22037, but there are differences -- this issue happens in phase 3 rather than 4, and there is no "fictitious type" message.

### LINKED ISSUE #23041: internal compiler error: cat_expr Errd when downcasting
```rust
#![feature(box_syntax)]
use std::any::Any;
fn main()
{
    fn bar(x:i32) ->i32 { 3*x };
    let b:Box<Any> = box {bar as fn(_)->_};
    b.downcast_ref::<fn(_)->_>();
}
```

### LINKED ISSUE #23729: compiler unexpectedly panicked
I tried this code:

```rust
fn main() {
    let fib = {
        struct Recurrence {
            mem: [u64; 2],
            pos: usize,
        }

        impl Iterator for Recurrence {
            #[inline]
            fn next(&mut self) -> Option<u64> {
                if self.pos < 2 {
                    let next_val = self.mem[self.pos];
                    self.pos += 1;
                    Some(next_val)
                } else {
                    let next_val = (self.mem[0] + self.mem[1]);
                    self.mem[0] = self.mem[1];
                    self.mem[1] = next_val;
                    Some(next_val)
                }
            }
        }

        Recurrence { mem: [0, 1], pos: 0 }
    };

    for e in fib.take(10) {
        println!("{}", e)
    }
}
```

I expected to see this happen:

0
1
1
2
3
5
8
13
21
34

Instead, this happened:

```
$ RUST_BACKTRACE=1 cargo run
   Compiling hello_world v0.0.1 (file:///Users/dls/ac4/hello_world)
src/main.rs:27:5: 30:2 error: internal compiler error: cat_expr Errd
src/main.rs:27     for e in fib.take(10) {
src/main.rs:28         println!("{}", e)
src/main.rs:29     }
src/main.rs:30 }
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
note: run with `RUST_BACKTRACE=1` for a backtrace
thread 'rustc' panicked at 'Box<Any>', /Users/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-mac/build/src/libsyntax/diagnostic.rs:130
```

## Meta

rustc 1.0.0-nightly (123a754cb 2015-03-24) (built 2015-03-25)
binary: rustc
commit-hash: 123a754cb8356d0e78837dd4e58103ad801309ff
commit-date: 2015-03-24
build-date: 2015-03-25
host: x86_64-apple-darwin
release: 1.0.0-nightly

Backtrace:

```
stack backtrace:
   1:        0x108671ea4 - sys::backtrace::write::h78053bbfb550960cgjD
   2:        0x10869d358 - panicking::on_panic::hc4e82bbd2a46726dR8I
   3:        0x1085ba76e - rt::unwind::begin_unwind_inner::h5e8e19c0097ac0cdBRI
   4:        0x107dcbcbe - rt::unwind::begin_unwind::h8176364159252686369
   5:        0x107dcbc6b - diagnostic::SpanHandler::span_bug::hdcd6dc2adc048426AaB
   6:        0x1055bdcec - session::Session::span_bug::hd2e8d90e6e32fe5bTHn
   7:        0x104d624db - check::regionck::visit_expr::h67ec4d109373a14f2Dd
   8:        0x104d69e7a - visit::walk_expr::h4641389526047920594
   9:        0x104d61353 - check::regionck::visit_expr::h67ec4d109373a14f2Dd
  10:        0x104d610c1 - check::regionck::visit_expr::h67ec4d109373a14f2Dd
  11:        0x104d69ecb - visit::walk_expr::h4641389526047920594
  12:        0x104d61353 - check::regionck::visit_expr::h67ec4d109373a14f2Dd
  13:        0x104d62e41 - check::regionck::visit_local::hd93c3707d09d90fd7Ad
  14:        0x104d69f5c - visit::walk_expr::h4641389526047920594
  15:        0x104d61783 - check::regionck::visit_expr::h67ec4d109373a14f2Dd
  16:        0x104d5d3c5 - check::regionck::Rcx<'a, 'tcx>::visit_fn_body::h91b65695e5e98981fgd
  17:        0x104dee2da - check::check_bare_fn::h4d8e30b5b0012b734jn
  18:        0x104de6184 - check::check_item::h4b4a2b730b65c17cMCn
  19:        0x104ebd782 - check_crate::closure.35881
  20:        0x104eb83da - check_crate::h4e5a2f60ebec7dccblC
  21:        0x104bf9417 - driver::phase_3_run_analysis_passes::h00707ed732905e83rGa
  22:        0x104bdf816 - driver::compile_input::h22976530edbb8120Rba
  23:        0x104c99313 - run_compiler::h6f6a07f7c4e7d147s2b
  24:        0x104c96ea5 - thunk::F.Invoke<A, R>::invoke::h5399241532089372082
  25:        0x104c96267 - rt::unwind::try::try_fn::h14095088624371570858
  26:        0x108723468 - rust_try_inner
  27:        0x108723455 - rust_try
  28:        0x104c96605 - thunk::F.Invoke<A, R>::invoke::h14770910994046267349
  29:        0x10868825d - sys::thread::create::thread_start::h3a4e0027cd5d22bdqPH
  30:     0x7fff902a9267 - _pthread_body
  31:     0x7fff902a91e4 - _pthread_start
```

### LINKED ISSUE #23827: ICE trying to port to new ops::Fn with trait-parametrized impl
Script to reproduce:

```
#!/bin/bash

cat > /tmp/fn_ice.rs << EOF
#![feature(core, unboxed_closures)]

pub struct Prototype {
    pub target: u32
}

trait Component {
    fn apply(self, e: u32);
}

impl<C: Component> Fn<(C,)> for Prototype {
    extern "rust-call" fn call(&self, (comp,): (C,)) -> Prototype {
        comp.apply(self.target);
        *self
    }
}

impl<C: Component> FnMut<(C,)> for Prototype {
    extern "rust-call" fn call_mut(&mut self, (comp,): (C,)) -> Prototype {
        Fn::call(*&self, (comp,))
    }
}

impl<C: Component> FnOnce<(C,)> for Prototype {
    extern "rust-call" fn call_once(self, (comp,): (C,)) -> Prototype {
        Fn::call(&self, (comp,))
    }
}

fn main() {}
EOF

RUST_BACKTRACE=1 rustc /tmp/fn_ice.rs
rustc --version
```

Output:

```
/tmp/fn_ice.rs:20:9: 20:34 error: internal compiler error: cat_expr Errd
/tmp/fn_ice.rs:20         Fn::call(*&self, (comp,))
                          ^~~~~~~~~~~~~~~~~~~~~~~~~
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
note: run with `RUST_BACKTRACE=1` for a backtrace
thread 'rustc' panicked at 'Box<Any>', /home/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libsyntax/diagnostic.rs:130

stack backtrace:
   1:     0x7fded6be1af9 - sys::backtrace::write::h8fb4e343117fc1c5HyD
   2:     0x7fded6c09718 - panicking::on_panic::h93647013dcbd3994ZOJ
   3:     0x7fded6b3d803 - rt::unwind::begin_unwind_inner::hd1fc6b2d31010710GuJ
   4:     0x7fded3ff706d - rt::unwind::begin_unwind::h8658016321657282922
   5:     0x7fded3ff7013 - diagnostic::SpanHandler::span_bug::had6443bf384adbf3JaB
   6:     0x7fded4879fa3 - session::Session::span_bug::h6a7a032f0a598052BRn
   7:     0x7fded58b3ecf - check::regionck::visit_expr::hdfd865c1888e71cf1Hd
   8:     0x7fded58af2fe - check::regionck::Rcx<'a, 'tcx>::visit_fn_body::haec01bb8e2116544ekd
   9:     0x7fded593c006 - check::check_bare_fn::h661e8d61a11643593nn
  10:     0x7fded5941136 - check::check_method_body::h58ab2862cf5cc872TVn
  11:     0x7fded5938972 - check::check_item::h399c12ee5fd19c10OGn
  12:     0x7fded5a08dd6 - check_crate::closure.35999
  13:     0x7fded5a03c4a - check_crate::h609b704cb69c3426OmC
  14:     0x7fded723dcc8 - driver::phase_3_run_analysis_passes::h93ff07476d50900drGa
  15:     0x7fded7223e3f - driver::compile_input::hbb8012e70cc155f0Rba
  16:     0x7fded72d42e2 - run_compiler::h31d988b263419921s2b
  17:     0x7fded72d20e3 - thunk::F.Invoke<A, R>::invoke::h12881802307748552982
  18:     0x7fded72d1579 - rt::unwind::try::try_fn::h10611962194889117110
  19:     0x7fded6c835b8 - rust_try_inner
  20:     0x7fded6c835a5 - rust_try
  21:     0x7fded72d189c - thunk::F.Invoke<A, R>::invoke::h15479254083495500308
  22:     0x7fded6bf6248 - sys::thread::create::thread_start::h21751a1d907ece81soI
  23:     0x7fded0ae2373 - start_thread
  24:     0x7fded67b327c - __clone
  25:                0x0 - <unknown>

rustc 1.0.0-nightly (199bdcfef 2015-03-26) (built 2015-03-27)
```

## Meta

rustc 1.0.0-nightly (199bdcfef 2015-03-26) (built 2015-03-27)
binary: rustc
commit-hash: 199bdcfeff5cfafd1f8e8ff583d7209272469879
commit-date: 2015-03-26
build-date: 2015-03-27
host: x86_64-unknown-linux-gnu
release: 1.0.0-nightly

### LINKED ISSUE #23966: ICE when calling Iterator::fold, error: cat_expr Errd
```rust
fn main() {"".chars().fold(|_, _| (), ());}
```
```
icea.rs:1:12: 1:42 error: internal compiler error: cat_expr Errd
icea.rs:1 fn main() {"".chars().fold(|_, _| (), ());}
                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
note: run with `RUST_BACKTRACE=1` for a backtrace
thread 'rustc' panicked at 'Box<Any>', C:/msys64/home/bombless/freshrustc/src/libsyntax\diagnostic.rs:130

stack backtrace:
   1:         0x7121cab3 - sys::backtrace::write::h65e8c3e2848bc8b9cQD
   2:         0x71231e3a - rt::unwind::register::h75c149df7638e28eonJ
   3:         0x71183210 - rt::unwind::begin_unwind_inner::h56069089577e9797ykJ
   4:           0x7c5fb9 - diagnostic::SpanHandler::span_bug::hd3a58a67988f3bb75cB
   5:           0x7c5f83 - diagnostic::SpanHandler::span_bug::hd3a58a67988f3bb75cB
   6:           0xdf24c2 - session::Session::span_bug::h5e300cd633c01cdfn2n
   7:          0x1778980 - check::regionck::Rcx<'a, 'tcx>.Visitor<'v>::visit_item::h864371e0b5e2bfcdhCd
   8:          0x1773a14 - check::regionck::Rcx<'a, 'tcx>.Visitor<'v>::visit_expr::h95e4b6b54e048f17wCd
   9:          0x18042f3 - check::CheckItemTypesVisitor<'a, 'tcx>.Visitor<'tcx>::visit_ty::h0e2bd0c28fcfea0bkin
  10:          0x17fc221 - check::CheckItemTypesVisitor<'a, 'tcx>.Visitor<'tcx>::visit_item::h40648275ef199a02Yhn
  11:          0x18d8d78 - check_crate::hbeb5b259fa92a914tlC
  12:          0x18d2fec - check_crate::hbeb5b259fa92a914tlC
  13:         0x652df75b - driver::phase_3_run_analysis_passes::hbf2e5a40425b2605oGa
  14:         0x652c2a45 - driver::compile_input::h7257ac3eadeade5aQba
  15:         0x65376d13 - run_compiler::h7927ca3bbb67862dp2b
  16:         0x65374be0 - run::hd85a769d156fbe5b51b
  17:         0x65373dea - run::hd85a769d156fbe5b51b
  18:         0x71269dec - rust_try
  19:         0x71269dc9 - rust_try
  20:         0x65374158 - run::hd85a769d156fbe5b51b
  21:         0x71225b04 - sys::tcp::TcpListener::bind::hb9cf5a229a477da7SLH
  22:     0x7ffda0f816ad - BaseThreadInitThunk
```
```
rustc 1.0.0-dev (14192d6df 2015-03-30) (built 2015-04-01)
binary: rustc
commit-hash: 14192d6df5cc714e5c9a3ca70b08f2514d977be2
commit-date: 2015-03-30
build-date: 2015-04-01
host: x86_64-pc-windows-gnu
release: 1.0.0-dev
```

### LINKED ISSUE #24013: ICE: cat_expr Errd
maybe a bug in type inference?

I tried this code:

```rust
fn main() {
    use std::mem::*;
    let a = 1;
    let b = 2;
    unsafe {swap::<&mut _>(transmute(&a), transmute(&b))};
}
```
and [playpen](http://is.gd/G6d2ta)

## Meta

`rustc --version --verbose`: 
```
rustc 1.0.0-nightly (d17d6e7f1 2015-04-02) (built 2015-04-03)
binary: rustc
commit-hash: d17d6e7f1f05fbdd4d9d246400ffebf768878c7a
commit-date: 2015-04-02
build-date: 2015-04-03
host: x86_64-unknown-linux-gnu
release: 1.0.0-nightly
```

Backtrace:

```
thread 'rustc' panicked at 'Box<Any>', /home/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libsyntax/diagnostic.rs:130

stack backtrace:
   1:     0x7faee32be3b8 - sys::backtrace::write::he4dda5a986f8dfc9IJC
   2:     0x7faee32e9760 - panicking::on_panic::h5b2db6d96c6af729sXI
   3:     0x7faee3221493 - rt::unwind::begin_unwind_inner::h312dab2a9cc03afbACI
   4:     0x7faee05e705d - rt::unwind::begin_unwind::h8552855983279226119
   5:     0x7faee05e7003 - diagnostic::SpanHandler::span_bug::h047bbb0d01e0a28bjnB
   6:     0x7faee0e88b53 - session::Session::span_bug::h8e85b4257a239e266Xq
   7:     0x7faee1f4acad - check::regionck::visit_expr::ha7a7caa6308adb39PJd
   8:     0x7faee1f5327e - visit::walk_expr::h7711135408040361563
   9:     0x7faee1f4a522 - check::regionck::visit_expr::ha7a7caa6308adb39PJd
  10:     0x7faee1f536f8 - visit::walk_expr::h7711135408040361563
  11:     0x7faee1f4a059 - check::regionck::visit_expr::ha7a7caa6308adb39PJd
  12:     0x7faee1f49920 - check::regionck::visit_expr::ha7a7caa6308adb39PJd
  13:     0x7faee1f4a059 - check::regionck::visit_expr::ha7a7caa6308adb39PJd
  14:     0x7faee1f5367d - visit::walk_expr::h7711135408040361563
  15:     0x7faee1f49c31 - check::regionck::visit_expr::ha7a7caa6308adb39PJd
  16:     0x7faee1f49983 - check::regionck::visit_expr::ha7a7caa6308adb39PJd
  17:     0x7faee1f5367d - visit::walk_expr::h7711135408040361563
  18:     0x7faee1f49c31 - check::regionck::visit_expr::ha7a7caa6308adb39PJd
  19:     0x7faee1f4b7da - check::regionck::visit_local::h1d3e9df070391b34UGd
  20:     0x7faee1f53710 - visit::walk_expr::h7711135408040361563
  21:     0x7faee1f4a059 - check::regionck::visit_expr::ha7a7caa6308adb39PJd
  22:     0x7faee1f45ccf - check::regionck::Rcx<'a, 'tcx>::visit_fn_body::he16da04e9c53d9f6amd
  23:     0x7faee1fe0b31 - check::check_bare_fn::h4ed57fcdf8abf23cUQn
  24:     0x7faee1fda614 - check::check_item::h66f023fd6d694e3fF9n
  25:     0x7faee1fded52 - visit::walk_item::h16105192910878993865
  26:     0x7faee1fded5d - visit::walk_item::h16105192910878993865
  27:     0x7faee20b2a41 - check_crate::closure.36300
  28:     0x7faee20ace13 - check_crate::ha6e679122aa8dfb5bwC
  29:     0x7faee393e5cd - driver::phase_3_run_analysis_passes::h001143095bbfc525gGa
  30:     0x7faee3922425 - driver::compile_input::h982ca27ddfea1322Qba
  31:     0x7faee39d99d5 - run_compiler::h46e3b1adb4d7a56fV4b
  32:     0x7faee39d72ed - boxed::F.FnBox<A>::call_box::h10231365352816203841
  33:     0x7faee39d6829 - rt::unwind::try::try_fn::h6438714248533661505
  34:     0x7faee3365c58 - rust_try_inner
  35:     0x7faee3365c45 - rust_try
  36:     0x7faee39d6afb - boxed::F.FnBox<A>::call_box::h8924274584753923957
  37:     0x7faee32d4771 - sys::thread::create::thread_start::h1fdda6dc8c80280aExH
  38:     0x7faedd0c5373 - start_thread
  39:     0x7faee2e9427c - __clone
  40:                0x0 - <unknown>
```

### LINKED ISSUE #24356: Internal compiler error from an incorrect Deref impl
[This code](http://is.gd/WGEmQI) produces an ICE for both beta and nightly. The code and backtrace are reproduced below:
```rust
fn main() {
    {
        use std::ops::Deref;
        
        struct Thing(i8);
        
        /*
        // Correct impl
        impl Deref for Thing {
            type Target = i8;
            fn deref(&self) -> &i8 { &self.0 }
        }
        */

        // Causes ICE
        impl Deref for Thing {
            fn deref(&self) -> i8 { self.0 }
        }
        
        let thing = Thing(72);
        
        *thing
    };
}
```
```
ice.rs:2:5: 23:6 error: internal compiler error: cat_expr Errd
ice.rs:2     {
ice.rs:3         use std::ops::Deref;
ice.rs:4 
ice.rs:5         struct Thing(i8);
ice.rs:6 
ice.rs:7         /*
         ...
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
note: run with `RUST_BACKTRACE=1` for a backtrace
thread 'rustc' panicked at 'Box<Any>', /home/rustbuild/src/rust-buildbot/slave/beta-dist-rustc-linux/build/src/libsyntax/diagnostic.rs:130

stack backtrace:
   1:     0x7f759aea23c8 - sys::backtrace::write::h179e141147f9ee14IJC
   2:     0x7f759aecd770 - panicking::on_panic::h6aa569d33389f0cfsXI
   3:     0x7f759ae054a3 - rt::unwind::begin_unwind_inner::h082f07869f4b9731ACI
   4:     0x7f75981cb04d - rt::unwind::begin_unwind::h13428428822164950735
   5:     0x7f75981caff3 - diagnostic::SpanHandler::span_bug::he82cb6427e6a50a8jnB
   6:     0x7f7598a6cb63 - session::Session::span_bug::h460607360e8bf7cc5Xq
   7:     0x7f7599b2ed0d - check::regionck::visit_expr::hfc7cf3e25c050a92PJd
   8:     0x7f7599b29ce0 - check::regionck::Rcx<'a, 'tcx>::visit_fn_body::hd4da730c0cf65ac9amd
   9:     0x7f7599bc4b91 - check::check_bare_fn::hb43e600383cf2ee2UQn
  10:     0x7f7599bbe674 - check::check_item::h77d9b4d4612f23cfF9n
  11:     0x7f7599c96a96 - check_crate::closure.36300
  12:     0x7f7599c90e73 - check_crate::h4b0848761f18a2bcbwC
  13:     0x7f759b5215cd - driver::phase_3_run_analysis_passes::hf7cad4098b28ceb1gGa
  14:     0x7f759b505425 - driver::compile_input::h7c62c2870ff901f6Qba
  15:     0x7f759b5bca25 - run_compiler::hc815b49ce638c28eV4b
  16:     0x7f759b5ba33d - boxed::F.FnBox<A>::call_box::h4290333406520961126
  17:     0x7f759b5b9879 - rt::unwind::try::try_fn::h13999576404798567721
  18:     0x7f759af49c68 - rust_try_inner
  19:     0x7f759af49c55 - rust_try
  20:     0x7f759b5b9b4b - boxed::F.FnBox<A>::call_box::h14489442628055152240
  21:     0x7f759aeb8781 - sys::thread::create::thread_start::h02b7da32b4d7a4aaExH
  22:     0x7f7594ca9373 - start_thread
  23:     0x7f759aa7827c - __clone
  24:                0x0 - <unknown>
```

### PR DESCRIPTION
**Pull request by ebfull**
An actual typeck error is the cause of many failed compilations but an
unrelated bug is being reported instead. It is triggered because a typeck
error is presumably not yet identified during compiler execution, which
would normally bypass an invariant in the presence of other errors. In
this particular situation, we delay the reporting of the bug until
abort_if_errors().

Closes #23827, closes #24356, closes #23041, closes #22897, closes #23966,
closes #24013, and closes #23729

**There is at least one situation where this bug may still be genuinely
triggered (#23437).**

### CODE REVIEW

File: src/librustc_typeck/check/regionck.rs [hunk 1]
```diff
@@ -544,7 +544,7 @@ fn visit_expr(rcx: &mut Rcx, expr: &ast::Expr) {
                 if tcx.sess.has_errors() {
                     // cannot run dropck; okay b/c in error state anyway.
                 } else {
-                    tcx.sess.span_bug(expr.span, "cat_expr_unadjusted Errd");
+                    tcx.sess.delay_span_bug(expr.span, "cat_expr Errd");
```
Comment (pnkfelix) [inline src/librustc_typeck/check/regionck.rs]: don't change the message here; it is still a call to `cat_expr_unadjusted` up above, which is info I wanted to capture in the ICE message.

**Comment by pnkfelix** [comment]
My reasoning behind calling `span_bug` in the first place was that I wanted to be notified about cases where the call to `cat_expr`.

I guess as long as such cases continue to emit an ICE, then its not *wrong* to make this change.

But I wonder if it might be simpler (and more correct) to try to identify an earlier spot in the control flow to add an additional call to `abort_if_errors`.

**Comment by pnkfelix** [comment]
@arielb1 points out that inserting a new call to `abort_if_errors` would not be ideal, since it will continue to cause us to abort, when we really want to allow compilation to keep going and find *more* (independent) errors

The real problem here, @arielb1 points out, is that the guard on the `span_bug` here is only checking the `tcx.sess` to see if any errors have been emitted, but the `fcx` itself may also have errors registered that are not reflected in the `tcx.sess`.

**Comment by pnkfelix** [comment]
(actually, another potential way to go here would be to use the same strategy employed in this PR, *except* with the refinement that the `Some` arm for the `match *delayed_bug` should *only* ICE if `!self.diagnostic().handler().has_errors()`.

That is, if we did end up reporting at least one error, then we could just say "okay, lets pretend that was the error that caused `cat_expr` to Err.

(Though I do worry about the potential for circular reasoning here, where a `cat_expr Err` that has gone undetected could then yield a spurious error downstream, and then that's reported, but is useless to the user and at the same time we get no ICE bug report...)

**Comment by ebfull** [comment]
> Actually, another potential way to go here would be to use the same strategy employed in this PR, except with the refinement that the Some arm for the match *delayed_bug should only ICE if !self.diagnostic().handler().has_errors().
> That is, if we did end up reporting at least one error, then we could just say "okay, lets pretend that was the error that caused cat_expr to Err.

If I'm reading your comment right, that's what the code currently does. It should abort before the match *delayed_bug if there are any errors.

**Comment by arielb1** [comment]
I say remove the `tcx.sess.has_errors()` check in that case.

**Comment by ebfull** [comment]
Done with both your recommendations, but it'd be nicer if these ICEs can be avoided by changing mem_categorization somehow.

**Comment by pnkfelix** [comment]
@ebfull after discussion with @arielb1 on IRC, I think we can indeed avoid many of the ICE's, not by changing mem_categorization, but rather by restructuring the type checker to do high-level signature-matching checks (e.g. that trait impls define all necessary items from the trait definitions) before checking any bodies.  I have a prototype that does that in development right now.

We may indeed still want to put in this PR, but i am not certain of that yet; I, like you, would prefer to get rid of this ICE entirely.  (And indeed, the path to get there may still involve changes to mem_categorization; I am not sure yet.)

**Comment by pnkfelix** [comment]
@ebull btw you were correct when you wrote:
> If I'm reading your comment right, that's what the code currently does. It should abort before the match *delayed_bug if there are any errors.

that is, my comment was based on a misreading of your code.

**Comment by pnkfelix** [comment]
I have opened #24422 , which adopts the strategy outlined in an earlier comment.

However, it does not address all of the ICE's listed in this ticket.  So we may still indeed want to adopt this change.  I will look into it.

**Comment by ebull** [comment]
@pnkfelix ebfull != ebull :)
________________________________

**Comment by pnkfelix** [comment]
@huonw well, i was half-hoping to find a way to fix all of the known ICE's without adopting the strategy outlined in this PR.  But its probably a better plan to adopt it at this point.

File: src/test/compile-fail/typeck-before-dropck-bug.rs [hunk 2]
```diff
@@ -0,0 +1,31 @@
...
+// except according to those terms.
+
+fn main() { }
+
+// Before these errors would ICE as "cat_expr Errd" because the errors
+// were unknown when the bug was triggered.
+
+fn unconstrained_type() {
+    [];
+    //~^ ERROR cannot determine a type for this expression: unconstrained type
```
Comment (pnkfelix) [inline src/test/compile-fail/typeck-before-dropck-bug.rs]: @ebfull you'll need to update the test; the compiler has changed now with #24422 so that this error message is no longer emitted (since the problem in the `impl` below is signaled first).

**Comment by ebfull** [comment]
Done, I stopped testing against what you fixed in #24422 as well.

**Comment by ebfull** [comment]
Should this be backported to beta like #24422?

**Comment by pnkfelix** [comment]
triage: beta-nominated 

(I am personally on fence, but it is worth discussing)

**Comment by pnkfelix** [comment]
not accepted for beta backport.
