### PR TITLE
Maintain broken symlink behaviour for the Windows exe resolver

### LINKED ISSUE #91177: The new Windows exe resolver has changed broken symlink behaviour
The old resolver would try to run broken symlinks. The new one skips them and continues searching.

To test this I created the simplest program that will run successfully.

```
Z:\test> mkdir exists
Z:\test> cd exists
Z:\test\exists> gc exe_exists.rs
fn main() {}
Z:\test\exists> rustc exe_exists.rs
Z:\test\exists> cd ..
Z:\test> 
```

Then I used the following test program:

```rust
// run_symlink.rs
use std::process::Command;
use std::os::windows::fs::symlink_file;
use std::env;
use std::fs;

fn main() -> std::io::Result<()> {
    // Get the directory of the working exe
    let mut exists = env::current_dir()?;
    exists.push("exists");

    // Set up a directory for the broken symlink...
    let mut bins = env::current_dir()?;
    bins.push("bins");
    fs::create_dir(&bins)?;

    // ...and create the symlink.
    let mut exe_path = bins.clone();
    exe_path.push("exe_exists.exe");
    symlink_file("DOES NOT EXIST", &exe_path)?;

    // Set up the `PATH` environment variable with our paths.
    let paths = env::join_paths(&[&bins, &exists]).unwrap();
    env::set_var("PATH", paths);

    // Try to run the file. It will try the broken symlink first.
    let result = Command::new("exe_exists.exe").spawn();
    println!("{:?}", result);

    // Cleanup
    fs::remove_dir_all(&bins)?;
    Ok(())
}
```

The result of compiling and running this program:

```
Z:\test> rustc +stable run_symlink.rs
Z:\test> ./run_symlink
Err(Os { code: 2, kind: NotFound, message: "The system cannot find the file specified." })
Z:\test> rustc +nightly run_symlink.rs
Z:\test> ./run_symlink
Ok(Child { stdin: None, stdout: None, stderr: None, .. })
```

@rustbot claim
@rustbot label +O-windows

### PR DESCRIPTION
**Pull request by ChrisDenton**
When the resolver was updated to remove the current directory from the search path (see #87704), care was take to avoid unintentional changes that hadn't been discussed. However, I missed the broken symlink behaviour. This PR fixes that.

**Edit** This turned out to be more important than I first realised. There are some types of application stubs that will redirect to the actual process when run using `CreateProcessW`, but due to the way they're implemented they cannot be opened normally using a `File::open` that follows reparse points. So this doesn't work with our current `exists` and `try_exists` methods.

Fixes #91177

### CODE REVIEW

File: library/std/src/sys/windows/process.rs [hunk 1]
```diff
@@ -700,13 +699,15 @@ enum Quote {
...
     // Encode the command and arguments in a command line string such
     // that the spawned process may recover them using CommandLineToArgvW.
     let mut cmd: Vec<u16> = Vec::new();
-    // Always quote the program name so CreateProcess doesn't interpret args as
-    // part of the name if the binary wasn't found first time.
-    append_arg(&mut cmd, prog, Quote::Always)?;
+    // Always quote the program name so CreateProcess to avoid ambiguity when
+    // the child process parses its arguments.
+    cmd.push(b'"' as u16);
+    cmd.extend_from_slice(prog.strip_suffix(&[0]).unwrap_or(prog));
```
Comment (bjorn3) [inline library/std/src/sys/windows/process.rs:739]: This doesn't escape `\` and `"` anymore.

Comment (ChrisDenton) [reply library/std/src/sys/windows/process.rs:739]: That is intentional. The [zeroth argument is special](https://docs.microsoft.com/en-us/cpp/cpp/main-function-command-line-args?view=msvc-160#parsing-c-command-line-arguments):

> The first argument (argv[0]) is treated specially. It represents the program name. Because it must be a valid pathname, parts surrounded by double quote marks (") are allowed. The double quote marks aren't included in the argv[0] output. The parts surrounded by double quote marks prevent interpretation of a space or tab character as the end of the argument. The later rules in this list don't apply.

Essentially argv[0] does not have escape characters but that's ok because [`"` is not allowed in Windows paths](https://docs.microsoft.com/en-us/windows/win32/fileio/naming-a-file#naming-conventions). See also, our parsing of the command line:

https://github.com/rust-lang/rust/blob/4fb45245840ad129b305023995a886cf8ec3e279/library/std/src/sys/windows/args.rs#L73-L86)

**Comment by m-ou-se** [comment]
Sorry for the delay.

@bors r+

> Maybe even beta backported if that's an option.

It's a bit late for that, as beta is splitting off in a day or two.

Do you have an example of a situation that's broken and fixed by this PR? Did you or anyone else run into that issue?

**Comment by ChrisDenton** [comment]
I mean, nobody has reported an issue through all the time it spent in nightly, beta then stable. So it's not a common situation. It would be frustrating however if someone does encounter it because it may not be obvious what went wrong.

So I don't think this is absolutely urgent but I do think it's important enough to be rolled into a release whenever the next opportunity happens to be.
