### PR TITLE
[NLL] Dangly paths for box

### LINKED ISSUE #45696: MIR-borrowck: behavior around Box<T> is different from AST borrowck
MIR borrowck treats `Box<T>` differently from AST borrowck (not that AST borrowck is terribly consistent there), for example, in the (simplified) test for #17263:

```Rust
struct Foo { a: isize, b: isize }

fn main() {
    let mut x: Box<_> = Box::new(Foo { a: 1, b: 2 });
    let (_a, _b) = (&mut x.a, &mut x.b);
    //~^ ERROR cannot borrow `x` (via `x.b`) as mutable more than once at a time
    //~| NOTE first mutable borrow occurs here (via `x.a`)
    //~| NOTE second mutable borrow occurs here (via `x.b`)

    let mut foo: Box<_> = Box::new(Foo { a: 1, b: 2 });
    let (_c, _d) = (&mut foo.a, &foo.b);
    //~^ ERROR cannot borrow `foo` (via `foo.b`) as immutable
    //~| NOTE mutable borrow occurs here (via `foo.a`)
    //~| NOTE immutable borrow occurs here (via `foo.b`)
}
//~^ NOTE first borrow ends here
//~^^ NOTE mutable borrow ends here
```

AST borrowck reports an error on both lines, but MIR borrowck lets the code pass:
```
error[E0499]: cannot borrow `x` (via `x.b`) as mutable more than once at a time (Ast)
  --> ../src/test/compile-fail/issue-17263.rs:15:36
   |
15 |     let (_a, _b) = (&mut x.a, &mut x.b);
   |                          ---       ^^^ second mutable borrow occurs here (via `x.b`)
   |                          |
   |                          first mutable borrow occurs here (via `x.a`)
...
25 | }
   | - first borrow ends here

error[E0502]: cannot borrow `foo` (via `foo.b`) as immutable because `foo` is also borrowed as mutable (via `foo.a`) (Ast)
  --> ../src/test/compile-fail/issue-17263.rs:21:34
   |
21 |     let (_c, _d) = (&mut foo.a, &foo.b);
   |                          -----   ^^^^^ immutable borrow occurs here (via `foo.b`)
   |                          |
   |                          mutable borrow occurs here (via `foo.a`)
...
25 | }
   | - mutable borrow ends here

error: aborting due to 2 previous errors
```

This should be investigated and solved

### PR DESCRIPTION
**Pull request by pnkfelix**
Special-case `Box` in `rustc_mir::borrow_check`.

Since we know dropping a box will not access any `&mut` or `&` references, it is safe to model its destructor as only touching the contents *owned* by the box.

----

There are three main things going on here:

1. The first main thing, this PR is fixing a bug in NLL where `rustc` previously would issue a diagnostic error in a case like this:
```rust
fn foo(x: Box<&mut i32>) -> &mut i32 { &mut **x } 
```

such code was accepted by the AST-borrowck in the past, but NLL was rejecting it with the following message ([playground](https://play.rust-lang.org/?gist=13c5560f73bfb16d6dab3ceaad44c0f8&version=nightly&mode=release&edition=2015))
```
error[E0597]: `**x` does not live long enough
 --> src/main.rs:3:40
  |
3 | fn foo(x: Box<&mut i32>) -> &mut i32 { &mut **x }
  |                                        ^^^^^^^^ - `**x` dropped here while still borrowed
  |                                        |
  |                                        borrowed value does not live long enough
  |
note: borrowed value must be valid for the anonymous lifetime #1 defined on the function body at 3:1...
 --> src/main.rs:3:1
  |
3 | fn foo(x: Box<&mut i32>) -> &mut i32 { &mut **x }
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: aborting due to previous error
```

2. The second main thing: The reason such code was previously rejected was because NLL (MIR-borrowck) incorporates a fix for issue #31567, where it models a destructor's execution as potentially accessing any borrows held by the thing being destructed. The tests with `Scribble` model this, showing that the compiler now catches such unsoundness.

However, that fix for issue #31567 is too strong, in that NLL (MIR-borrowck) includes `Box` as one of the types with a destructor that potentially accesses any borrows held by the box. This thus was the cause of the main remaining discrepancy between AST-borrowck and MIR-borrowck, as documented in issue #45696, specifically in [the last example of this comment](https://github.com/rust-lang/rust/issues/45696#issuecomment-345367873), which I have adapted into the `fn foo` shown above.

We did close issue #45696 back in December of 2017, but AFAICT that example was not fixed by PR #46268. (And we did not include a test, etc etc.)

This PR fixes that case, by trying to model the so-called `DerefPure` semantics of `Box<T>` when we traverse the type of the input to `visit_terminator_drop`.

3. The third main thing is that during a review of the first draft of this PR, @matthewjasper pointed out that the new traversal of `Box<T>` could cause the compiler to infinite loop. I have adjusted the PR to avoid this (by tracking what types we have previously seen), and added a much needed test of this somewhat odd scenario. (Its an odd scenario because the particular case only arises for things like `struct A(Box<A>);`, something which cannot be constructed in practice.)

Fix #45696.

### CODE REVIEW

**Comment by pnkfelix** [comment]
Btw this PR illustrates a second breaking change to the static semantics  associated with the move to NLL (the first breaking change being #27282), and thus provides extra justification for the migrantion mode (#46908) we are deploying with the 2018 edition.

File: src/librustc_mir/borrow_check/mod.rs [hunk 1]
```diff
@@ -897,6 +902,53 @@ impl<'cx, 'gcx, 'tcx> MirBorrowckCtxt<'cx, 'gcx, 'tcx> {
...
+                );
+
+                // Third, we model dropping any content owned by the
+                // box by recurring on box contents. This catches
+                // cases like `Box<Box<ScribbleWhenDropped<&mut T>>>`,
+                // while still restricting Write to *owned* content.
+                let ty = erased_drop_place_ty.boxed_ty();
+                debug!("visit_terminator_drop drop-box-content deref_place: {:?} ty: {:?}",
+                       deref_place, ty);
+                self.visit_terminator_drop(loc, term, flow_state, &deref_place, ty, span);
```
Comment (matthewjasper) [inline src/librustc_mir/borrow_check/mod.rs]: This looks like unconditional recursion when dropping `struct A(Box<A>, ...)`

Comment (pnkfelix) [reply src/librustc_mir/borrow_check/mod.rs]: Note you didn’t put an `Option<Box<A>>` there

Doesn’t the compiler already reject such infinite types? Let me check

Comment (pnkfelix) [reply src/librustc_mir/borrow_check/mod.rs]: Hmm okay this may indeed be a problem for me. You can define such types. You won’t be able to make an instance of one, but I imagine one could make a `let a: Option<A> = None;` and then the compiler would possibly infinite loop while trying to deal with the drop of the `Option<A>` ...

Comment (pnkfelix) [reply src/librustc_mir/borrow_check/mod.rs]: Note that there are already existing bugs where infinitely sized types can cause the compiler, often specifically dropck, to hang.

Here are a couple (that are still open/unresolved) that I found by skimming over the results when I searched for "recursive" in our issues list: #44933, and #52852

(Plus there is #4287, which I might argue that example falls into in the long term, since our users might like getting a nice warning about the problem.)

Comment (pnkfelix) [reply src/librustc_mir/borrow_check/mod.rs]: Also, it turns out that the infinite loop here does allocate memory on each iteration, so we will eventually exhaust our available memory and error out due to that. I don't know whether people think that is better or worse than just diverging execution... :)

Despite the existence of bugs like #44933 and #52852, I will go ahead and try to fix this PR to detect the recursion...

Comment (pnkfelix) [reply src/librustc_mir/borrow_check/mod.rs]: Hmm, actually, the existing compiler *already* appears to infinite loop on an example like

```rust
struct A(Box<A>, &'static str);

fn impossible_to_call(a: A) { }
```

(note i'm observing this with AST-borrowck.)

So I'm back to wondering if this is worth trying to fix in this PR. I guess I should strive to avoid introducing new instances of infinite loops...

Comment (pnkfelix) [reply src/librustc_mir/borrow_check/mod.rs]: (but I won't be able to include a test, since that would just cause other parts of the compiler to infinite loop...)

**Comment by pnkfelix** [comment]
I'm going to assign this review to @nagisa since @nikomatsakis  is on PTO.

@nagisa : do feel free to reassign to someone else if you do not feel comfortable with it. I *could* just let someone from the WG-compiler-nll working group look at it (indeed it seems like @matthewjasper has done at least enough of a review to point out something deep that I overlooked).

File: src/librustc_mir/borrow_check/mod.rs (hunk 1 above)
Comment (pnkfelix) [reply src/librustc_mir/borrow_check/mod.rs]: hmm maybe I was mistaken in my earlier claim that that example currently causes the compiler to infinite loop. I was observing an infinite loop but I'm no longer sure what version of the compiler I was testing at that time. Will investigate...

Comment (pnkfelix) [reply src/librustc_mir/borrow_check/mod.rs]: (ah I might have gotten confused because I was also checking the behavior of #52852, so I might have thought the infinite loops I was seeing there also applied to this `struct A(Box<A>);` case...)

Comment (pnkfelix) [reply src/librustc_mir/borrow_check/mod.rs]: (fixed, and added corresponding test.)

File: src/test/ui/issue-45696-no-variant-box-recur.rs [hunk 2]
```diff
@@ -0,0 +1,66 @@
...
+// direct non-regular recursion with indirect ownership via box
+struct D { field: Box<(D, D)> }
+
+// indirect regular recursion with indirect ownership via box.
+struct E { field: F }
+struct F { field: Box<E> }
+
+// indirect non-regular recursion with indirect ownership via box.
+struct G { field: (F, F) }
+struct H { field: Box<E> }
```
Comment (MaloJaffre) [inline src/test/ui/issue-45696-no-variant-box-recur.rs]: These two lines seem to be incorrect, there is no actual recursion.

Comment (nagisa) [reply src/test/ui/issue-45696-no-variant-box-recur.rs]: Well, there is, in a sense that you cannot construct either `E` or `F` due to them being recursive. It is just that they are not mutually recursive, but perhaps ought to be?

**Review by nagisa — APPROVED** [review]
I looked over most of the code, but couldn’t finish looking over the tests. I’ll delegate to @eddyb to r+ this, as I believe they looked over the tests and/or semantics.

File: src/test/ui/issue-45696-no-variant-box-recur.rs (hunk 2 above)
Comment (pnkfelix) [reply src/test/ui/issue-45696-no-variant-box-recur.rs]: This was a typo. I meant for `G` to refer to `H` and `H` to refer to `G`.

(I had gone through a couple iterations of this and I added cases above... maybe I'll put these into individual inner modules to try to prevent this kind of mistake.)

File: src/librustc_mir/borrow_check/mod.rs [hunk 3]
```diff
@@ -830,6 +835,37 @@ impl InitializationRequiringAction {
     }
 }
 
+/// A simple linked-list threaded up the stack of recursive calls in `visit_terminator_drop`.
```
Comment (eddyb) [inline src/librustc_mir/borrow_check/mod.rs]: cc @nikomatsakis this is starting to quickly become the rustc team's favorite hack!

File: src/librustc_mir/borrow_check/mod.rs [hunk 4]
```diff
@@ -830,6 +835,37 @@ impl InitializationRequiringAction {
...
+#[derive(Debug)]
+struct SeenTy<'a, 'gcx: 'a>(ty::Ty<'gcx>, Option<&'a SeenTy<'a, 'gcx>>);
```
Comment (eddyb) [inline src/librustc_mir/borrow_check/mod.rs]: nit: `Ty` not `ty::Ty`.

Comment (eddyb) [inline src/librustc_mir/borrow_check/mod.rs]: You can rearrange this to have `Option` around a pair of `Ty` and `&SeenTy`, bypassing the problems needing `Option` around it later.

File: src/librustc_mir/borrow_check/mod.rs [hunk 5]
```diff
@@ -897,6 +976,55 @@ impl<'cx, 'gcx, 'tcx> MirBorrowckCtxt<'cx, 'gcx, 'tcx> {
...
                     .for_each(|field| drop_field(self, field));
             }
+
+            // #45696: special-case Box<T> by treating its dtor as
+            // only deep *across owned content*. Namely, we know
+            // dropping a box does not touch data behind any
+            // references it holds (which a Deep Write would touch).
+            ty::TyAdt(def, _) if def.is_box() => {
+                // First, we model the loss of the reference itself
+                // via a shallow write.
```
Comment (eddyb) [inline src/librustc_mir/borrow_check/mod.rs]: "the loss of the reference itself"?

File: src/librustc_mir/borrow_check/mod.rs [hunk 6]
```diff
@@ -897,6 +976,55 @@ impl<'cx, 'gcx, 'tcx> MirBorrowckCtxt<'cx, 'gcx, 'tcx> {
...
+                    (&deref_place, span),
+                    (ShallowOrDeep::Shallow(None), Write(WriteKind::StorageDeadOrDrop)),
+                    LocalMutationIsAllowed::Yes,
+                    flow_state,
+                );
+
+                // Third, we model dropping any content owned by the
+                // box by recurring on box contents. This catches
+                // cases like `Box<Box<ScribbleWhenDropped<&mut T>>>`,
+                // while still restricting Write to *owned* content.
```
Comment (eddyb) [inline src/librustc_mir/borrow_check/mod.rs]: Why is this last? Doesn't dropping the contents happen *before* deallocating the box?

File: src/librustc_mir/borrow_check/mod.rs (hunk 5 above)
Comment (pnkfelix) [reply src/librustc_mir/borrow_check/mod.rs]: That is, the dropping of the representation of the box-pointer

How would you prefer to phrase this?

File: src/librustc_mir/borrow_check/mod.rs (hunk 6 above)
Comment (pnkfelix) [reply src/librustc_mir/borrow_check/mod.rs]: If you want the drop of the box contents to happen first, that should be easy to do. For some reason I thought the presentation was more "natural" from the view point of someone reading the code.
 * I didn't think the order in which we did these three steps would actually matter ...
 * (but now you've got me wondering if it could ... I'll do some experiments...)

I do remember playing with moving around the order to see if that got rid of the deltas to `dropck.nll.stderr` and `dropck-object-cycle.nll.stderr`. (But it didn't.)

So, anyway, I'll try putting it first as part of other changes I'm making in response to your feedback.

File: src/librustc_mir/borrow_check/mod.rs (hunk 4 above)
Comment (pnkfelix) [reply src/librustc_mir/borrow_check/mod.rs]: Okay I will try that.

File: src/librustc_mir/borrow_check/mod.rs (hunk 3 above)
Comment (pnkfelix) [reply src/librustc_mir/borrow_check/mod.rs]: Indeed, in the [commit message](https://github.com/rust-lang/rust/pull/52782/commits/31c05979f935aeeabe99712e862c7affb821561b) I even wrote: 
```
Note: A similar style stack-only linked-list definition can be found
in `rustc_mir::borrow_check::places_conflict`. It might be good at
some point in the future to unify the two types and put the resulting
definition into `librustc_data_structures/`.
```

File: src/librustc_mir/borrow_check/mod.rs (hunk 4 above)
Comment (pnkfelix) [reply src/librustc_mir/borrow_check/mod.rs]: yeah I guess we've hit the number of occurrences where we can add `Ty` to the `use` at the top.

File: src/librustc_mir/borrow_check/mod.rs (hunk 6 above)
Comment (pnkfelix) [reply src/librustc_mir/borrow_check/mod.rs]: One argument for why the order shouldn't matter here: Given `a_box: Box<T>`, In theory someone should be allowed to move the contents out of `*a_box`, and have those contents get dropped at a time that is disconnected from the (shallow) drop of `a_box`.

Of course that would be totally broken if the drop of `a_box` *did* attempt to dereference and drop the contents at `*a_box`. But that's why the shallow/deep distinction is important here.

Comment (pnkfelix) [reply src/librustc_mir/borrow_check/mod.rs]: > (but now you've got me wondering if it could ... I'll do some experiments...)

i played around a little to try to see if I could create a struct with a recursive self-reference inside a box and somehow throw in a destructor that would allow us to in some way observe the access order here. But perhaps unsurprisingly I was unable to make such a thing due to dropck rules...

File: src/librustc_mir/borrow_check/mod.rs (hunk 3 above)
Comment (eddyb) [reply src/librustc_mir/borrow_check/mod.rs]: back in my day... https://github.com/rust-lang/rust/pull/12162/files#diff-87946a10679226d1e5b4d6f9c30ab133R47

File: src/librustc_mir/borrow_check/mod.rs (hunk 5 above)
Comment (eddyb) [reply src/librustc_mir/borrow_check/mod.rs]: Do you mean the allocation? Or the library-side newtype around the pointer? I would not call either a "reference" unless you mean the `&mut Box<T>` that a `Drop::drop` impl would get.

File: src/librustc_mir/borrow_check/mod.rs [hunk 7]
```diff
@@ -897,6 +974,56 @@ impl<'cx, 'gcx, 'tcx> MirBorrowckCtxt<'cx, 'gcx, 'tcx> {
...
+                // Second, we model the drop of the box-pointer itself
+                // via a shallow write.
+                //
+                // FIXME: Could we just get by with the last step
+                // below? (This second step seems like a good thing to
+                // do just as a matter of principle; but none of our
+                // testsuite complained when I tried leaving it out.)
+                self.access_place(
+                    ContextKind::Drop.new(loc),
+                    (drop_place, span),
```
Comment (eddyb) [inline src/librustc_mir/borrow_check/mod.rs]: Wait, why do we need to do anything to the dereference, as opposed to the `Box` itself?
If you implemented `Box` in a library, you would recurse in an ADT and see a raw pointer... and not go further.

Comment (pnkfelix) [reply src/librustc_mir/borrow_check/mod.rs]: Yes, and that's the whole problem.

If you implement `MyBox` as a library, then we see that that there is an `impl Drop for MyBox` and then fail to accept code like:
```rust
fn foo(x: MyBox<&mut i32>) -> &mut i32 { &mut **x } 
```

If you *want* to be able to implement `MyBox` as a library, then we will need to generalize the functionality described here via some means (be it `DerefPure` or `#[dangly_path]` or something else), and then have `MyBox` use that generalized functionality.

This PR is taking the expedient path of treating `Box` as a special case where we *know* its destructor is special.

Comment (eddyb) [reply src/librustc_mir/borrow_check/mod.rs]: But is the shallow `*x` access even necessary? Doesn't owned `*x` + shallow `x` suffice?
Also, isn't this similar to `unsafe impl<#[may_dangle] T> Drop for Box<T>`?

Comment (pnkfelix) [reply src/librustc_mir/borrow_check/mod.rs]: Ah I understand your question now.

The shallow `*x` access is definitely necessary. If you leave that out, you miss cases like a drop of `a_box: Box<i32>`, where the drop of the box *needs* to invalidate borrows of `&*a_box` and `&mut *a_box`

Notably, the shallow `x` access does not invalidate such borrows. (And the step that recurs on the box contents doesn't help there either, because when the original type was `Box<i32>` then we're just looking at `i32`...) 

Because all the shallow `x` access touches is the fields of the box representation, i.e.

Comment (pnkfelix) [reply src/librustc_mir/borrow_check/mod.rs]: One might be able to argue that the special case handling here should be attached to `Unique<T>` rather than `Box<T>`. I haven't thought terribly hard about that option.

Comment (pnkfelix) [reply src/librustc_mir/borrow_check/mod.rs]: The more I think about @eddyb's question/complaint, the more I wonder about my own response that:
> (And the step that recurs on the box contents doesn't help there either, because when the original type was Box<i32> then we're just looking at i32...)

Because that may be the heart of what's confusing here, and I suspect I didn't actually get the details right in that parenthetical above. Let me see if I can make a better explanation (but first I want to make sure that my claim is 100% solid...)

Comment (pnkfelix) [reply src/librustc_mir/borrow_check/mod.rs]: So the recursive call to `visit_terminator_drop` will bottom out here at this code: 

https://github.com/rust-lang/rust/blob/f89817997ac0aa100bf91997194ad85a7e59f743/src/librustc_mir/borrow_check/mod.rs#L900-L914

I.e. `visit_terminator_drop` is just meant to model the actions of destructors. If you hand it the place `*a_box`, that is just an i32. Dropping that has no effect.

So my shallow write to `*a_box` is an attempt to model the effect of the box destructor.

Comment (pnkfelix) [reply src/librustc_mir/borrow_check/mod.rs]: @eddyb asked:
> Also, isn't this similar to unsafe impl<#[may_dangle] T> Drop for Box<T>?

Yes it is. That is in part why I called these things "dangly paths" in https://github.com/nikomatsakis/nll-rfc/issues/40

Comment (eddyb) [reply src/librustc_mir/borrow_check/mod.rs]: Okay, so the "owned drop" part of `*a_box` *does not* invalidate borrows to `*a_box` for at least some types, that helps a bit.

I wish the "shallow write" done to`*a_box` was more of a `StorageDead` effect (instead of just being called a "write"), because it's really destroying the backing storage, without necessarily writing to it.

Comment (pnkfelix) [reply src/librustc_mir/borrow_check/mod.rs]: (Further review/discussion led to me pointing out that the effect encoded here is inded tagged as `Write(WriteKind::StorageDeadOrDrop)`)

File: src/librustc_mir/borrow_check/mod.rs (hunk 5 above)
Comment (pnkfelix) [reply src/librustc_mir/borrow_check/mod.rs]: I mean the library-side newtype around the pointer.  I tried rephrasing as "StorageDead of the box-pointer representation" in my updated comments.

File: src/librustc_mir/borrow_check/mod.rs [hunk 8]
```diff
@@ -980,10 +980,27 @@ impl<'cx, 'gcx, 'tcx> MirBorrowckCtxt<'cx, 'gcx, 'tcx> {
             // dropping a box does not touch data behind any
             // references it holds (which a Deep Write would touch).
             ty::TyAdt(def, _) if def.is_box() => {
+                // There are three main steps modelled here for
+                // dropping `a_box: Box<T`>`:
```
Comment (eddyb) [inline src/librustc_mir/borrow_check/mod.rs]: Stray backtick after `T`.

File: src/librustc_mir/borrow_check/mod.rs [hunk 9]
```diff
@@ -980,10 +980,27 @@ impl<'cx, 'gcx, 'tcx> MirBorrowckCtxt<'cx, 'gcx, 'tcx> {
...
+                // 1. run the destructor for `*a_box`,
+                // 2. deallocate the backing storage of `*a_box`,
+                // 3. the StorageDead of `a_box` itself
+                //
+                // When/if we add a `&own T` type, step 1 would be
+                // like running the destructor of the `&own T` (and
+                // the owner of backing storage referenced by the
+                // `&own T` would be responsible for steps 2 and 3).
```
Comment (eddyb) [inline src/librustc_mir/borrow_check/mod.rs]: At the lowest (unsafe?) level, yes, step 2 would *technically* be in `Drop for Box<T>`.
*However*, from the point of view of the code using `DerefOwn` + `Drop`, step 2 would be *part of* dropping the `&own T`.

That is, dropping `&own T` invalidates it as backing storage for the code using it, so there would potentially be a gap in between dropping the `&own T` you got from `DerefOwn` and calling `free` (via `Drop for Box<T>`), in which *you can't use the allocation* even though it still exists.

This is *quite distinct* from *moving out* of the `&own T`, which would allow moving back in, or assigning to the `T` inside, which would drop the `T` *but not invalidate* the `&own T`.

File: src/librustc_mir/borrow_check/mod.rs [hunk 10]
```diff
@@ -992,36 +1009,39 @@ impl<'cx, 'gcx, 'tcx> MirBorrowckCtxt<'cx, 'gcx, 'tcx> {
...
-                // such a deref.
+                // Third, we model the StorageDead of the box-pointer
+                // representation itself via a shallow write.
                 //
-                // (We use a shallow write because a Deep one would
-                // touch `&mut` references in `T`.)
+                // FIXME: Could we just get by with just steps 1 and 2
+                // above? (This last step seems like a good thing to
+                // do just as a matter of principle; but none of our
+                // testsuite complained when I tried leaving it out.)
```
Comment (eddyb) [inline src/librustc_mir/borrow_check/mod.rs]: I think it's relevant if part of liballoc did `&a_box.0` (for whatever reason) - without this last step, `a_box` could be dropped without that borrow being invalidated, right? You could probably use a `#![no_std]` test to check for this, by definition your own `Box` lang item.

File: src/librustc_mir/borrow_check/mod.rs (hunk 9 above)
Comment (pnkfelix) [reply src/librustc_mir/borrow_check/mod.rs]: Hmm so you’re interpreting step 2 as solely invalidating the backing storage, while I was interpreting it as both invalidating the backing storage *and* deallocating the backing storage

Do I have that right? Where does the deallocation happen in your mental model, as part of step 3?

Comment (pnkfelix) [reply src/librustc_mir/borrow_check/mod.rs]: Or, rereading my comment in the code, maybe I was interpreting step 2 as solely deallocating the backing storage, and I didn’t have the invalidation in any explicit step.

While you are pointing out that the invalidation happens, in the code here, as part of step 2

Comment (eddyb) [reply src/librustc_mir/borrow_check/mod.rs]: > While you are pointing out that the invalidation happens, in the code here, as part of step 2

Yes, in terms of borrowck, you *can only* observe that "backing storage" invalidation, since the deallocation is a FFI call with a raw pointer, it's not something borrowck can understand directly.

Comment (eddyb) [reply src/librustc_mir/borrow_check/mod.rs]: Talking to @RalfJung, I reached a point where I'm wondering whether `Drop(x: T)`  being a noop when `!needs_drop(T)` is a bad idea, since it makes some sense that it'd have an effect similar to `Operand::Move(x)` (i.e. invalidation of the source value).

I thought something like `StorageDead(*a_box)` was needed, but `Move(*a_box)` should do and `Drop(*x)` should *maybe* imply it as well.
For the `&own T` model, that means that `Drop(x: &own T)` only needs to invalidate *the value at* `*x`, *not* the underlying memory. However, that memory is no longer reachable, as `x` had the unique path to it (which the `Drop(x)` should have invalidated), and invalidating the value at `*x` should prevent any other borrows from pointing to it.

In less words, we only need `StorageLive` / `StorageDead` for locals *specifically because* they're not behind indirection we can create/destroy in ways that would directly enable/disable access to the value.

OTOH we don't generate `Drop` at all sometimes, as an optimization, so we have to rely on `StorageDead` instead for invalidating at least *some* of the locals.

**Comment by eddyb** [comment]
@bors r+

I hope @nikomatsakis agrees and we can revert it otherwise.

File: src/librustc_mir/borrow_check/mod.rs [hunk 11]
```diff
@@ -847,14 +881,57 @@ impl<'cx, 'gcx, 'tcx> MirBorrowckCtxt<'cx, 'gcx, 'tcx> {
...
+            //   and constructable in finite time (since the recursion can bottom out with `None`).
+            //   This is an obvious instance of something the compiler must accept.
+            //
+            // Since some of the above impossible cases like `C` and
+            // `D` are accepted by the compiler, we must take care not
+            // to infinite-loop while processing them. But since such
+            // cases cannot actually arise, it is sound for us to just
+            // skip them during drop. If the developer uses unsafe
+            // code to construct them, they should not be surprised by
+            // weird drop behavior in their resulting code.
```
Comment (RalfJung) [inline src/librustc_mir/borrow_check/mod.rs]: Uh, can we not fall-back-to-error instead of fall-back-to-accept? Seems like a disaster waiting to happen.^^

Comment (pnkfelix) [reply src/librustc_mir/borrow_check/mod.rs]: We cannot fallback to error, at least not to hard error. That could break hypothetical code.

We could issue a future compatibility warning.

Or we could *try* to emit drop code that error dynamically ... maybe that is what you are asking for?

(When I wrote "skip them during drop", I meant during this static analysis. I believe the actual dynamic behavior here will be to ... infinite loop ... i think... )

Comment (pnkfelix) [reply src/librustc_mir/borrow_check/mod.rs]: ([This is the test case](https://github.com/rust-lang/rust/blob/c02c00b8455d6ec6eff50ae94bebb4a424c95e02/src/test/ui/issue-45696-no-variant-box-recur.rs) showing the kind of case that concerns me. It is currently marked as `run-pass`; we could make a variant of it that actually conjures up one of this infinitely regressed things, but I'm pretty sure that the unsafe code guidelines group would tag such a test as having undefined behavior, no?)

Comment (RalfJung) [reply src/librustc_mir/borrow_check/mod.rs]: > I'm pretty sure that the unsafe code guidelines group would tag such a test as having undefined behavior,

Yeah, I agree.

> When I wrote "skip them during drop", I meant during this static analysis. I believe the actual dynamic behavior here will be to ... infinite loop ... i think... 

Probably it'll fill up the stack. ;)
What does it mean for the static analysis to skip this? Does it not consider this a use, or so? That seems problematic.^^

Comment (pnkfelix) [reply src/librustc_mir/borrow_check/mod.rs]: It considers the first one it sees a use, but not the second one encountered via the recursive descent.

But to even get to that code during dynamic execution you’d have to already built the invalid thing and be witnessing UB.

Maybe I should make a more complete illustrative test case for us to discuss, with the aforementioned construction...?

Comment (RalfJung) [reply src/librustc_mir/borrow_check/mod.rs]: > It considers the first one it sees a use, but not the second one encountered via the recursive descent.

I see. Yes, without knowing any of the details, this does make some sense.

File: src/librustc_mir/borrow_check/mod.rs (hunk 7 above)
Comment (pnkfelix) [reply src/librustc_mir/borrow_check/mod.rs]: See also PR #54310
