### PR TITLE
Display spans correctly when there are zero-width or wide characters

### LINKED ISSUE #8706: Bad span computations with unicode characters, should be handling them as graphemes
``` rust
use std::io;

fn main() {
    let s = ~"ZͨA͑ͦ͒͋ͤ͑̚L̄͑͋Ĝͨͥ̿͒̽̈́Oͥ͛ͭ!̏"; while true { break; }
    io::println(s);
}
```

```
main.rs:4:46: 4:67 warning: denote infinite loops with loop { ... }, #[warn(while_true)] on by default
main.rs:4     let s = ~"ZͨA͑ͦ͒͋ͤ̚L̄͑͋Ĝͨͥ̿͒̽̈́Oͥ͛ͭ!̏"; while true { break; }
                                                       ^~~~~~~~~~~~~~~~~~~~~
```

The proper fix for this requires grapheme handling (#7043), e.g. some graphemes are double width.

### LINKED ISSUE #45211: Error span is in incorrect place due to Unicode fullwidth characters
```sh
$ rustc +nightly --version
rustc 1.22.0-nightly (d6d711dd8 2017-10-10)
$ uname -sri
Linux 4.2.0-42-generic x86_64
```
Code:
```rust
fn main() {
    let _ = ("こんにちは", 100i40);
}
```
rustc output:
```
error: invalid width `40` for integer literal
 --> main.rs:2:23
  |
2 |     let _ = ("こんにちは", 100i40);
  |                       ^^^^^^
  |
  = help: valid widths are 8, 16, 32, 64 and 128

error: aborting due to previous error
```

### PR DESCRIPTION
**Pull request by tirr-c**
Hopefully...
* fixes #45211
* fixes #8706

---

Before:
```
error: invalid width `7` for integer literal
  --> unicode_2.rs:12:25
   |
12 |     let _ = ("a̐éö̲", 0u7);
   |                         ^^^
   |
   = help: valid widths are 8, 16, 32, 64 and 128

error: invalid width `42` for integer literal
  --> unicode_2.rs:13:20
   |
13 |     let _ = ("아あ", 1i42);
   |                    ^^^^
   |
   = help: valid widths are 8, 16, 32, 64 and 128

error: aborting due to 2 previous errors
```

After:
```
error: invalid width `7` for integer literal
  --> unicode_2.rs:12:25
   |
12 |     let _ = ("a̐éö̲", 0u7);
   |                     ^^^
   |
   = help: valid widths are 8, 16, 32, 64 and 128

error: invalid width `42` for integer literal
  --> unicode_2.rs:13:20
   |
13 |     let _ = ("아あ", 1i42);
   |                      ^^^^
   |
   = help: valid widths are 8, 16, 32, 64 and 128

error: aborting due to 2 previous errors
```

Spans might display incorrectly on the browser.

r? @estebank

### CODE REVIEW

**Comment by tirr-c** [comment]
Is this failure a travis issue?

**Comment by est31** [comment]
@tirr-c its no travis issue:
```
[00:03:44] tidy error: /checkout/src/libsyntax_pos/lib.rs:829: TODO is deprecated; use FIXME

[00:03:46] some tidy checks failed
```

You should also read [contributing.md](https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#pull-requests).

As one thing to check, does your code compute the correct number of ^ as well? E.g. in something like `let _ = (42, a̐é);` where should underline the `a̐é` with two ^ markers.

File: src/libsyntax_pos/lib.rs [hunk 1]
```diff
@@ -798,6 +818,27 @@ impl FileMap {
         self.multibyte_chars.borrow_mut().push(mbc);
     }
 
+    pub fn record_width(&self, pos: BytePos, ch: char) {
+        let width = match ch {
+            '\t' | '\n' =>
+                // Tabs will be printed as half-width spaces.
```
Comment (est31) [inline src/libsyntax_pos/lib.rs]: Is U+0020 really a full-width space? I'm not sure about the terminology, but its not a specially narrow character or something.

Comment (est31) [reply src/libsyntax_pos/lib.rs]: Oh sorry disregard, its a specific Unicode term. The comment is okay.

**Comment by tirr-c** [comment]
Oh, I've run tidy test before adding some comments. I thought the failure is because of travis since I didn't see any build logs after failure. Fixed.

And yes, it displays two ^'s:

```
error: non-ascii idents are not fully supported. (see issue #28979)
 --> test.rs:2:18
  |
2 |     let _ = (42, a̐é);
  |                  ^^
  |
  = help: add #![feature(non_ascii_idents)] to the crate attributes to enable
```

**Comment by tirr-c** [comment]
Maybe I need to rename fields and variables. The term "narrow" seems more appropriate than "half-width" here.

**Comment by est31** [comment]
"half-width" is an actual term so IMO it is okay: https://en.wikipedia.org/wiki/Halfwidth_and_fullwidth_forms

**Comment by tirr-c** [comment]
My understanding is that the term "narrow" is broader than "halfwidth." Also, most ASCII characters are defined as narrow, not halfwidth, so narrow will be better than halfwidth.

http://www.unicode.org/reports/tr11/

File: src/test/ui/codemap_tests/unicode_2.stderr [hunk 2]
```diff
@@ -0,0 +1,18 @@
...
+12 |     let _ = ("a̐éö̲", 0u7);
+   |                     ^^^
+   |
+   = help: valid widths are 8, 16, 32, 64 and 128
+
+error: invalid width `42` for integer literal
+  --> $DIR/unicode_2.rs:13:20
+   |
+13 |     let _ = ("아あ", 1i42);
+   |                      ^^^^
```
Comment (estebank) [inline src/test/ui/codemap_tests/unicode_2.stderr]: As per @est31's comment, could you add a case that points at the string itself to make sure regressions would get caught?

**Review by estebank — APPROVED** [review]
I'm ok with the approach, but I can't shake the feeling that performing the translation from bytepos to visual column in `src/librustc_errors/emitter.rs`'s `render_source_line` by looking at the line itself and fixing the annotation positions there might be slightly less/more straightforward code.

That being said, the current approach is sound. Could you add the requested test? Once that's done, r=me.

File: src/libsyntax_pos/lib.rs [hunk 3]
```diff
@@ -618,7 +634,7 @@ impl Encodable for FileMap {
 impl Decodable for FileMap {
     fn decode<D: Decoder>(d: &mut D) -> Result<FileMap, D::Error> {
 
-        d.read_struct("FileMap", 6, |d| {
```
[the remark this answers is not in the document]
Comment (tirr-c) [reply src/libsyntax_pos/lib.rs]: I have no idea, but for me `6` there didn't make sense. There were total of 7 (now 8) fields.

File: src/libsyntax_pos/lib.rs [hunk 4]
```diff
@@ -494,6 +496,15 @@ pub struct MultiByteChar {
...
 }
 
+/// Identifies an offset of a non-narrow character in a FileMap
+#[derive(Copy, Clone, RustcEncodable, RustcDecodable, Eq, PartialEq)]
+pub struct NonNarrowChar {
+    /// The absolute offset of the character in the CodeMap
+    pub pos: BytePos,
+    /// The width of the character, 0 (zero-width) or 2 (full-width)
+    pub width: usize,
+}
```
[the remark this answers is not in the document]
Comment (tirr-c) [reply src/libsyntax_pos/lib.rs]: I totally agree!

**Comment by tirr-c** [comment]
Made `NonNarrowChar` into a enum, and added a new test.

File: src/libsyntax_pos/lib.rs [hunk 5]
```diff
@@ -494,6 +496,63 @@ pub struct MultiByteChar {
...
+            2 => NonNarrowChar::Wide(pos),
+            _ => panic!("width {} given for non-narrow character", width),
+        }
+    }
+
+    /// Returns the absolute offset of the character in the CodeMap
+    pub fn pos(&self) -> BytePos {
+        match *self {
+            NonNarrowChar::ZeroWidth(p) => p,
+            NonNarrowChar::Wide(p) => p,
```
Comment (estebank) [inline src/libsyntax_pos/lib.rs]: This can be simplified to
```rust
match *self {
    NonNarrowChar::ZeroWidth(p) |
    NonNarrowChar::Wide(p) => p,
}
```

**Review by estebank — APPROVED** [review]
