### PR TITLE
Don't try to promote already promoted out temporaries

### LINKED ISSUE #53201: miri ICE promote const: impossible case reached
[Playground](https://play.rust-lang.org/?gist=904a700fead099ae8534f3bfa67e7e9d&version=nightly&mode=debug&edition=2015):

```rust
#![feature(const_fn, rustc_attrs, attr_literals, untagged_unions)] 

/// A single unconstrained byte (0-255).
#[derive(Copy, Clone, Debug)]
pub struct ImmByte(u8);
impl ImmByte {
    /// Constructor
    #[inline]
    #[rustc_args_required_const(0)]
    pub const fn new(value: u8) -> Self {
        ImmByte(value)
    }
}

pub struct v128([u8; 16]);

impl v128 {
    #[inline]
    #[rustc_args_required_const(0)]
    pub const unsafe fn const_(imm: [ImmByte; 16]) -> v128 {
        union U {
            imm: [ImmByte; 16],
            vec: v128,
        }
        U { imm }.vec
    }
}

fn main() {
    let _a = v128::const_([
        ImmByte::new(0),
        ImmByte::new(1),
        ImmByte::new(2),
        ImmByte::new(3),
        ImmByte::new(4),
        ImmByte::new(5),
        ImmByte::new(6),
        ImmByte::new(7),
        ImmByte::new(8),
        ImmByte::new(9),
        ImmByte::new(10),
        ImmByte::new(11),
        ImmByte::new(12),
        ImmByte::new(13),
        ImmByte::new(14),
        ImmByte::new(15),
    ]);
}
```

produces

```shell
error: internal compiler error: librustc_mir/transform/promote_consts.rs:334: impossible case reached

thread 'main' panicked at 'Box<Any>', librustc_errors/lib.rs:578:9
note: Run with `RUST_BACKTRACE=1` for a backtrace.
error: aborting due to previous error
```

cc @oli-obk

### PR DESCRIPTION
**Pull request by oli-obk**
fixes #53201

r? @eddyb

### CODE REVIEW

**Comment by TimNN** [comment]
Ping from triage @eddyb: This PR requires your review.

**Comment by alexreg** [comment]
@oli-obk I don't have r+ powers. Unless you just want me to review the code...

**Comment by oli-obk** [comment]
Oh I guess that's why I can't r? you :D

Yes a review would be great. You've been in that code a lot lately so I assumed you're the best one to review right now

**Comment by oli-obk** [comment]
@bors delegate=alexreg

let's see if that works

File: src/librustc_mir/transform/qualify_consts.rs [hunk 1]
```diff
@@ -974,7 +979,9 @@ impl<'a, 'tcx> Visitor<'tcx> for Qualifier<'a, 'tcx, 'tcx> {
                     if !constant_arguments.contains(&i) {
                         return
                     }
-                    if this.qualif.is_empty() {
+                    // if the argument requires a constant, we care about constness, not
```
Comment (alexreg) [inline src/librustc_mir/transform/qualify_consts.rs]: This could do with elaboration. What do we mean by "requires a constant"? Where is this checked for?

**Review by alexreg — CHANGES_REQUESTED** [review]

**Comment by alexreg** [comment]
Generally looks fine otherwise though...

File: src/librustc_mir/transform/qualify_consts.rs [hunk 2]
```diff
@@ -974,7 +979,16 @@ impl<'a, 'tcx> Visitor<'tcx> for Qualifier<'a, 'tcx, 'tcx> {
...
+                    // Since the argument is required to be constant,
+                    // we care about constness, not promotability.
+                    // If we checked for promotability, we'd miss out on
+                    // the results of function calls (which are never promoted)
+                    // This is not a problem, because the argument explicitly
+                    // requests constness, in contrast to regular promotion
+                    // which happens even without the user requesting it.
+                    // We can error out with a hard error if the argument is not
+                    // constant here.
+                    if (this.qualif - Qualif::NOT_PROMOTABLE).is_empty() {
```
Comment (alexreg) [inline src/librustc_mir/transform/qualify_consts.rs]: Thanks for expanding on this. I still think the terminology is a bit confusing: it seems to suggest "return values are never promotable but we're going to promote one here anyway, because it's const."

File: src/librustc_mir/transform/qualify_consts.rs [hunk 3]
```diff
@@ -1003,7 +1021,6 @@ impl<'a, 'tcx> Visitor<'tcx> for Qualifier<'a, 'tcx, 'tcx> {
                     // Be conservative about the returned value of a const fn.
                     let tcx = self.tcx;
                     let ty = dest.ty(self.mir, tcx).to_ty(tcx);
-                    self.qualif = Qualif::empty();
```
Comment (alexreg) [inline src/librustc_mir/transform/qualify_consts.rs]: Why did you remove this line?

**Review by alexreg — CHANGES_REQUESTED** [review]

File: src/librustc_mir/transform/qualify_consts.rs (hunk 2 above)
Comment (oli-obk) [reply src/librustc_mir/transform/qualify_consts.rs]: Well... yes. The rules for automatic promotion don't include function calls. The rules for constants do include function calls. Since the current function requires a constant here, if we did something like `0usize - 1` we'd get an error. If you just do `&(0usize - 1)` in normal runtime code, you get a warning and a panic at runtime (in debug mode).

Comment (alexreg) [reply src/librustc_mir/transform/qualify_consts.rs]: Yeah sure, I agree this makes sense, but could we just change the comment to "never promoted for runtime-evaluated/non-const functions" or such, just to be super-clear and make me happy? :-)

File: src/librustc_mir/transform/qualify_consts.rs (hunk 3 above)
Comment (oli-obk) [reply src/librustc_mir/transform/qualify_consts.rs]: Otherwise we'd be erasing the `NOT_PROMOTABLE` qualification we added above.

Comment (alexreg) [reply src/librustc_mir/transform/qualify_consts.rs]: Yep, but I think you want to reset all fields apart from that one, no? Alternatively, just make sure that's set after `self.qualif` is reset.

File: src/librustc_mir/transform/promote_consts.rs [hunk 4]
```diff
@@ -332,6 +332,14 @@ impl<'a, 'tcx> Promoter<'a, 'tcx> {
                             let operand = Operand::Copy(promoted_place(ty, span));
                             mem::replace(&mut args[index], operand)
                         }
+                        // We expected a `TerminatorKind::Call` for which we'd like to promote an
+                        // argument. Since `qualify_consts` saw a `TerminatorKind::Call` here, but
+                        // we are seeing a `Goto`, that means that the `promote_temps` method
+                        // already promoted this call away entirely. This case occurs when calling
+                        // a function requiring a constant argument and as that constant value
+                        // providing a value whose computation contains another call to a function
+                        // requiring a constant argument.
```
Comment (alexreg) [inline src/librustc_mir/transform/promote_consts.rs]: Thanks for adding this. Sorry to nitpick, but this 2nd sentence doesn't parse grammatically.

**Comment by RalfJung** [comment]
Cc @eddyb this touched const qualification.

**Comment by eddyb** [comment]
@RalfJung I should've said something, but I reviewed this and it appears to be a sound relaxation.
