### PR TITLE
NLL fails to suggest "try removing `&mut` here"

### LINKED ISSUE #51191: NLL fails to suggest "try removing `&mut` here"
For the following tests, AST-borrowck suggests removing `&mut`, while NLL fails to make such a suggestion:

 * [ ] [did_you_mean/issue-31424.rs](https://github.com/rust-lang/rust/blob/master/src/test/ui/did_you_mean/issue-31424.rs) / [NLL output](https://github.com/rust-lang/rust/blob/master/src/test/ui/did_you_mean/issue-31424.nll.stderr) (partially fixed in #51275)
 * [x] [did_you_mean/issue-34337.rs](https://github.com/rust-lang/rust/blob/master/src/test/ui/did_you_mean/issue-34337.rs) / [NLL output](https://github.com/rust-lang/rust/blob/master/src/test/ui/did_you_mean/issue-34337.nll.stderr) (fixed in #51275)
 * [x] [did_you_mean/issue-37139.rs](https://github.com/rust-lang/rust/blob/master/src/test/ui/did_you_mean/issue-37139.rs) / [NLL output](https://github.com/rust-lang/rust/blob/master/src/test/ui/did_you_mean/issue-37139.nll.stderr) (fixed in #51275)

### PR DESCRIPTION
**Pull request by davidtwco**
Fixes #51191.

This PR adds ``try removing `&mut` here`` suggestions to functions where a mutable borrow is being taken of a `&mut self` or a `self: &mut Self`. This PR also enables the suggestion for adding a `mut` pattern to by-value implicit self arguments without `mut` patterns already.

r? @nikomatsakis

### CODE REVIEW

File: src/librustc/ich/impls_hir.rs [hunk 1]
```diff
@@ -349,14 +349,22 @@ impl_stable_hash_for!(struct hir::FnDecl {
     inputs,
     output,
     variadic,
-    has_implicit_self
+    implicit_self
```
Comment (nikomatsakis) [inline src/librustc/ich/impls_hir.rs]: pre-existing, but it's kind of weird that we call this an "implicit" self, given that we're talking about an explicitly written `self` annotation

File: src/librustc_mir/borrow_check/mutability_errors.rs [hunk 2]
```diff
@@ -217,6 +218,40 @@ impl<'a, 'gcx, 'tcx> MirBorrowckCtxt<'a, 'gcx, 'tcx> {
         debug!("report_mutability_error: act={:?}, acted_on={:?}", act, acted_on);
 
         match the_place_err {
+            // Suggest removing a `&mut` from the use of a mutable reference.
+            Place::Local(local)
+                if {
+                    self.mir.local_decls.get(*local).map(|local_decl| {
```
Comment (nikomatsakis) [inline src/librustc_mir/borrow_check/mutability_errors.rs]: woah that is one big if guard :)

**Review by nikomatsakis — APPROVED** [review]

**Comment by nikomatsakis** [comment]
r=me but the incremental tests are unhappy. Looks like the test just needs to be updated though. You probably just need to change

```rust
#[cfg(not(cfail1))]
#[rustc_clean(label="Hir", cfg="cfail2")]
#[rustc_clean(label="Hir", cfg="cfail3")]
trait TraitChangeModeSelfOwnToMut: Sized {
    #[rustc_clean(label="Hir", cfg="cfail2")]
    #[rustc_clean(label="Hir", cfg="cfail3")]
    #[rustc_dirty(label="HirBody", cfg="cfail2")]
    #[rustc_clean(label="HirBody", cfg="cfail3")]
    fn method(mut self) {}
}
```

to

```rust
#[cfg(not(cfail1))]
#[rustc_clean(label="Hir", cfg="cfail2")]
#[rustc_clean(label="Hir", cfg="cfail3")]
trait TraitChangeModeSelfOwnToMut: Sized {
    #[rustc_dirty(label="Hir", cfg="cfail2")] // changed!
    #[rustc_clean(label="Hir", cfg="cfail3")]
    #[rustc_dirty(label="HirBody", cfg="cfail2")]
    #[rustc_clean(label="HirBody", cfg="cfail3")]
    fn method(mut self) {}
}
```

In particular, in the old system, the `Hir` didn't reflect the `mut` in the signature, but now it does.

File: src/librustc/ich/impls_hir.rs (hunk 1 above)
Comment (davidtwco) [reply src/librustc/ich/impls_hir.rs]: I think it makes sense if you consider the "implicit"-ness of it that you don't specify the type, whereas in the explicit case you do.

File: src/librustc_mir/borrow_check/mutability_errors.rs [hunk 3]
```diff
@@ -217,6 +218,40 @@ impl<'a, 'gcx, 'tcx> MirBorrowckCtxt<'a, 'gcx, 'tcx> {
...
+                                false
+                            }
+                        } else {
+                            false
+                        }
+                    }).unwrap_or(false)
+                } =>
+            {
+                err.span_label(span, format!("cannot {ACT}", ACT = act));
+                err.span_label(span, "try removing `&mut` here");
```
Comment (estebank) [inline src/librustc_mir/borrow_check/mutability_errors.rs]: I believe that if we use `local_decl.source_info.span` here it would point at `&mut self` instead of `(&mut self)`, which would let you make it a machine applicable suggestion instead of a label. Changing this will likely require you to change the above condition, but marginally so.

Comment (davidtwco) [reply src/librustc_mir/borrow_check/mutability_errors.rs]: I might be misunderstanding but, wouldn't `local_decl.source_info.span` point to the argument not the use of it as `span` does?

File: src/librustc/hir/mod.rs [hunk 4]
```diff
@@ -1769,9 +1769,34 @@ pub struct FnDecl {
     pub inputs: HirVec<Ty>,
     pub output: FunctionRetTy,
     pub variadic: bool,
-    /// True if this function has an `self`, `&self` or `&mut self` receiver
-    /// (but not a `self: Xxx` one).
-    pub has_implicit_self: bool,
+    /// Does the function have an implicit self?
+    pub implicit_self: ImplicitSelfKind,
```
Comment (eddyb) [inline src/librustc/hir/mod.rs]: This is a bit sad, I was hoping this could stay out of the HIR permanently.

File: src/librustc/mir/mod.rs [hunk 5]
```diff
@@ -583,11 +583,27 @@ pub enum BindingForm<'tcx> {
     /// This is a binding for a non-`self` binding, or a `self` that has an explicit type.
     Var(VarBindingForm<'tcx>),
     /// Binding for a `self`/`&self`/`&mut self` binding where the type is implicit.
-    ImplicitSelf,
+    ImplicitSelf(ImplicitSelfKind),
     /// Reference used in a guard expression to ensure immutability.
     RefForGuard,
 }
```
Comment (eddyb) [inline src/librustc/mir/mod.rs]: I guess the ideal of lowering away pattern-matching completely is too naive in the face of diagnostics :sob:

File: src/librustc/mir/mod.rs [hunk 6]
```diff
@@ -583,11 +583,27 @@ pub enum BindingForm<'tcx> {
...
 
+/// Represents what type of implicit self a function has, if any.
+#[derive(Clone, Copy, PartialEq, Eq, Hash, Debug, RustcEncodable, RustcDecodable)]
+pub enum ImplicitSelfKind {
+    /// Represents a `fn x(self);`.
+    Imm,
+    /// Represents a `fn x(mut self);`.
+    Mut,
```
Comment (eddyb) [inline src/librustc/mir/mod.rs]: Can't these two be distinguished by `binding_mode`?

File: src/librustc/mir/mod.rs [hunk 7]
```diff
@@ -583,11 +583,27 @@ pub enum BindingForm<'tcx> {
...
+    /// Represents a `fn x(&self);`.
+    ImmRef,
+    /// Represents a `fn x(&mut self);`.
+    MutRef,
```
Comment (eddyb) [inline src/librustc/mir/mod.rs]: Can't these two be distinguished by type? (maybe even distinguish `&self` from `self` by type?)
