### PR TITLE
Remap impl-trait lifetimes on HIR instead of AST lowering

### LINKED ISSUE #125249: ICE: `assertion failed: unique`
auto-reduced (treereduce-rust):
````rust
#![feature(return_position_impl_trait_in_trait, return_type_notation)]

trait IntFactory {
    fn stream(&self) -> impl IntFactory<stream(): IntFactory<stream(): Send> + Send>;
}


````

original:
````rust
#![feature(return_position_impl_trait_in_trait, return_type_notation)]

trait IntFactory {
    fn stream(&self) -> impl IntFactory<stream(): IntFactory<stream(): Send> + Send>;
}
trait SendIntFactory: IntFactory<stream(): Send> + Send {}
````

Version information
````
rustc 1.80.0-nightly (36c0a6d40 2024-05-18)
binary: rustc
commit-hash: 36c0a6d40fb6aae9c450305085d64e2ba55c6c58
commit-date: 2024-05-18
host: x86_64-unknown-linux-gnu
release: 1.80.0-nightly
LLVM version: 18.1.4

````

Command:
`/home/matthias/.rustup/toolchains/master/bin/rustc --crate-type=lib`

<details><summary><strong>Program output</strong></summary>
<p>

```
warning: the feature `return_type_notation` is incomplete and may not be safe to use and/or cause compiler crashes
 --> /tmp/icemaker_global_tempdir.m4kvtvaNzsSJ/rustc_testrunner_tmpdir_reporting.sI91r3JGKfet/mvce.rs:1:49
  |
1 | #![feature(return_position_impl_trait_in_trait, return_type_notation)]
  |                                                 ^^^^^^^^^^^^^^^^^^^^
  |
  = note: see issue #109417 <https://github.com/rust-lang/rust/issues/109417> for more information
  = note: `#[warn(incomplete_features)]` on by default

warning: the feature `return_position_impl_trait_in_trait` has been stable since 1.75.0 and no longer requires an attribute to enable
 --> /tmp/icemaker_global_tempdir.m4kvtvaNzsSJ/rustc_testrunner_tmpdir_reporting.sI91r3JGKfet/mvce.rs:1:12
  |
1 | #![feature(return_position_impl_trait_in_trait, return_type_notation)]
  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: `#[warn(stable_features)]` on by default

warning: trait `IntFactory` is never used
 --> /tmp/icemaker_global_tempdir.m4kvtvaNzsSJ/rustc_testrunner_tmpdir_reporting.sI91r3JGKfet/mvce.rs:3:7
  |
3 | trait IntFactory {
  |       ^^^^^^^^^^
  |
  = note: `#[warn(dead_code)]` on by default

thread 'rustc' panicked at compiler/rustc_lint/src/impl_trait_overcaptures.rs:171:21:
assertion failed: unique
stack backtrace:
   0:     0x7e9f17fe69e5 - std::backtrace_rs::backtrace::libunwind::trace::hf2bc7f5038b3e369
                               at /rustc/36c0a6d40fb6aae9c450305085d64e2ba55c6c58/library/std/src/../../backtrace/src/backtrace/libunwind.rs:105:5
   1:     0x7e9f17fe69e5 - std::backtrace_rs::backtrace::trace_unsynchronized::h231bca9ebdb2d476
                               at /rustc/36c0a6d40fb6aae9c450305085d64e2ba55c6c58/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7e9f17fe69e5 - std::sys_common::backtrace::_print_fmt::hb8880a770a528751
                               at /rustc/36c0a6d40fb6aae9c450305085d64e2ba55c6c58/library/std/src/sys_common/backtrace.rs:68:5
   3:     0x7e9f17fe69e5 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h33a25d9d3cddcff1
                               at /rustc/36c0a6d40fb6aae9c450305085d64e2ba55c6c58/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x7e9f18035b9b - core::fmt::rt::Argument::fmt::hb79968a3099c2b80
                               at /rustc/36c0a6d40fb6aae9c450305085d64e2ba55c6c58/library/core/src/fmt/rt.rs:165:63
   5:     0x7e9f18035b9b - core::fmt::write::h87de2705f4fdde46
                               at /rustc/36c0a6d40fb6aae9c450305085d64e2ba55c6c58/library/core/src/fmt/mod.rs:1169:21
   6:     0x7e9f17fdb77f - std::io::Write::write_fmt::habafebc10fded2ab
                               at /rustc/36c0a6d40fb6aae9c450305085d64e2ba55c6c58/library/std/src/io/mod.rs:1835:15
   7:     0x7e9f17fe67be - std::sys_common::backtrace::_print::hb1d61293da984960
                               at /rustc/36c0a6d40fb6aae9c450305085d64e2ba55c6c58/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x7e9f17fe67be - std::sys_common::backtrace::print::h2131b88f8087e7b2
                               at /rustc/36c0a6d40fb6aae9c450305085d64e2ba55c6c58/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x7e9f17fe91b9 - std::panicking::default_hook::{{closure}}::h68cf6ae540909963
  10:     0x7e9f17fe8efd - std::panicking::default_hook::h4b57c10c74892259
                               at /rustc/36c0a6d40fb6aae9c450305085d64e2ba55c6c58/library/std/src/panicking.rs:298:9
  11:     0x7e9f148fba8f - std[4409b2d227107481]::panicking::update_hook::<alloc[62996783038b3a10]::boxed::Box<rustc_driver_impl[ec6cf89b952751b7]::install_ice_hook::{closure#0}>>::{closure#0}
  12:     0x7e9f17fe98eb - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::hf3d7594c845607a3
                               at /rustc/36c0a6d40fb6aae9c450305085d64e2ba55c6c58/library/alloc/src/boxed.rs:2036:9
  13:     0x7e9f17fe98eb - std::panicking::rust_panic_with_hook::he223310e59b58621
                               at /rustc/36c0a6d40fb6aae9c450305085d64e2ba55c6c58/library/std/src/panicking.rs:799:13
  14:     0x7e9f17fe962b - std::panicking::begin_panic_handler::{{closure}}::h2b1c193a81afbc45
                               at /rustc/36c0a6d40fb6aae9c450305085d64e2ba55c6c58/library/std/src/panicking.rs:656:13
  15:     0x7e9f17fe6ea9 - std::sys_common::backtrace::__rust_end_short_backtrace::h4f10616ff00feb98
                               at /rustc/36c0a6d40fb6aae9c450305085d64e2ba55c6c58/library/std/src/sys_common/backtrace.rs:171:18
  16:     0x7e9f17fe9397 - rust_begin_unwind
                               at /rustc/36c0a6d40fb6aae9c450305085d64e2ba55c6c58/library/std/src/panicking.rs:652:5
  17:     0x7e9f18032163 - core::panicking::panic_fmt::hcc56f9541c31fe59
                               at /rustc/36c0a6d40fb6aae9c450305085d64e2ba55c6c58/library/core/src/panicking.rs:72:14
  18:     0x7e9f1803220c - core::panicking::panic::h5c79f86ebaa4ce23
                               at /rustc/36c0a6d40fb6aae9c450305085d64e2ba55c6c58/library/core/src/panicking.rs:146:5
  19:     0x7e9f1634d56c - <rustc_lint[18589ef7f21dc6df]::impl_trait_overcaptures::VisitOpaqueTypes as rustc_type_ir[fcc5e9d53e164095]::visit::TypeVisitor<rustc_middle[94c1eba9c157edd1]::ty::context::TyCtxt>>::visit_ty
  20:     0x7e9f1634cf09 - <rustc_lint[18589ef7f21dc6df]::impl_trait_overcaptures::VisitOpaqueTypes as rustc_type_ir[fcc5e9d53e164095]::visit::TypeVisitor<rustc_middle[94c1eba9c157edd1]::ty::context::TyCtxt>>::visit_ty
  21:     0x7e9f1634bda6 - <rustc_lint[18589ef7f21dc6df]::impl_trait_overcaptures::VisitOpaqueTypes as rustc_type_ir[fcc5e9d53e164095]::visit::TypeVisitor<rustc_middle[94c1eba9c157edd1]::ty::context::TyCtxt>>::visit_binder::<rustc_type_ir[fcc5e9d53e164095]::ty_kind::FnSig<rustc_middle[94c1eba9c157edd1]::ty::context::TyCtxt>>
  22:     0x7e9f1634b18c - rustc_lint[18589ef7f21dc6df]::impl_trait_overcaptures::check_fn
  23:     0x7e9f15e7c4b8 - <rustc_lint[18589ef7f21dc6df]::late::LateContextAndPass<rustc_lint[18589ef7f21dc6df]::BuiltinCombinedModuleLateLintPass> as rustc_hir[38c888bf6a6f703]::intravisit::Visitor>::visit_nested_item
  24:     0x7e9f15e7ab29 - rustc_lint[18589ef7f21dc6df]::lint_mod
  25:     0x7e9f15e7a921 - rustc_query_impl[98154bf48ac5ed09]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[98154bf48ac5ed09]::query_impl::lint_mod::dynamic_query::{closure#2}::{closure#0}, rustc_middle[94c1eba9c157edd1]::query::erase::Erased<[u8; 0usize]>>
  26:     0x7e9f1674297d - rustc_query_system[8e8a87f940666368]::query::plumbing::try_execute_query::<rustc_query_impl[98154bf48ac5ed09]::DynamicConfig<rustc_query_system[8e8a87f940666368]::query::caches::DefaultCache<rustc_span[744739c6604e47db]::def_id::LocalModDefId, rustc_middle[94c1eba9c157edd1]::query::erase::Erased<[u8; 0usize]>>, false, false, false>, rustc_query_impl[98154bf48ac5ed09]::plumbing::QueryCtxt, false>
  27:     0x7e9f167407ff - rustc_query_impl[98154bf48ac5ed09]::query_impl::lint_mod::get_query_non_incr::__rust_end_short_backtrace
  28:     0x7e9f167403d9 - rustc_lint[18589ef7f21dc6df]::late::check_crate::{closure#1}
  29:     0x7e9f1673fe00 - rustc_lint[18589ef7f21dc6df]::late::check_crate
  30:     0x7e9f16749453 - rustc_interface[ada677875731fed0]::passes::analysis
  31:     0x7e9f1674895b - rustc_query_impl[98154bf48ac5ed09]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[98154bf48ac5ed09]::query_impl::analysis::dynamic_query::{closure#2}::{closure#0}, rustc_middle[94c1eba9c157edd1]::query::erase::Erased<[u8; 1usize]>>
  32:     0x7e9f169abee5 - rustc_query_system[8e8a87f940666368]::query::plumbing::try_execute_query::<rustc_query_impl[98154bf48ac5ed09]::DynamicConfig<rustc_query_system[8e8a87f940666368]::query::caches::SingleCache<rustc_middle[94c1eba9c157edd1]::query::erase::Erased<[u8; 1usize]>>, false, false, false>, rustc_query_impl[98154bf48ac5ed09]::plumbing::QueryCtxt, false>
  33:     0x7e9f169abc49 - rustc_query_impl[98154bf48ac5ed09]::query_impl::analysis::get_query_non_incr::__rust_end_short_backtrace
  34:     0x7e9f16822fce - rustc_interface[ada677875731fed0]::interface::run_compiler::<core[b65be67b0b9d2881]::result::Result<(), rustc_span[744739c6604e47db]::ErrorGuaranteed>, rustc_driver_impl[ec6cf89b952751b7]::run_compiler::{closure#0}>::{closure#1}
  35:     0x7e9f1680da49 - std[4409b2d227107481]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[ada677875731fed0]::util::run_in_thread_with_globals<rustc_interface[ada677875731fed0]::util::run_in_thread_pool_with_globals<rustc_interface[ada677875731fed0]::interface::run_compiler<core[b65be67b0b9d2881]::result::Result<(), rustc_span[744739c6604e47db]::ErrorGuaranteed>, rustc_driver_impl[ec6cf89b952751b7]::run_compiler::{closure#0}>::{closure#1}, core[b65be67b0b9d2881]::result::Result<(), rustc_span[744739c6604e47db]::ErrorGuaranteed>>::{closure#0}, core[b65be67b0b9d2881]::result::Result<(), rustc_span[744739c6604e47db]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[b65be67b0b9d2881]::result::Result<(), rustc_span[744739c6604e47db]::ErrorGuaranteed>>
  36:     0x7e9f1680d7f6 - <<std[4409b2d227107481]::thread::Builder>::spawn_unchecked_<rustc_interface[ada677875731fed0]::util::run_in_thread_with_globals<rustc_interface[ada677875731fed0]::util::run_in_thread_pool_with_globals<rustc_interface[ada677875731fed0]::interface::run_compiler<core[b65be67b0b9d2881]::result::Result<(), rustc_span[744739c6604e47db]::ErrorGuaranteed>, rustc_driver_impl[ec6cf89b952751b7]::run_compiler::{closure#0}>::{closure#1}, core[b65be67b0b9d2881]::result::Result<(), rustc_span[744739c6604e47db]::ErrorGuaranteed>>::{closure#0}, core[b65be67b0b9d2881]::result::Result<(), rustc_span[744739c6604e47db]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[b65be67b0b9d2881]::result::Result<(), rustc_span[744739c6604e47db]::ErrorGuaranteed>>::{closure#2} as core[b65be67b0b9d2881]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  37:     0x7e9f17ff378b - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hd707e428c387a32b
                               at /rustc/36c0a6d40fb6aae9c450305085d64e2ba55c6c58/library/alloc/src/boxed.rs:2022:9
  38:     0x7e9f17ff378b - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h5849656bb97cf604
                               at /rustc/36c0a6d40fb6aae9c450305085d64e2ba55c6c58/library/alloc/src/boxed.rs:2022:9
  39:     0x7e9f17ff378b - std::sys::pal::unix::thread::Thread::new::thread_start::h493d13a7185ac4a0
                               at /rustc/36c0a6d40fb6aae9c450305085d64e2ba55c6c58/library/std/src/sys/pal/unix/thread.rs:108:17
  40:     0x7e9f17d9255a - <unknown>
  41:     0x7e9f17e0fa3c - <unknown>
  42:                0x0 - <unknown>

error: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: please make sure that you have updated to the latest nightly

note: rustc 1.80.0-nightly (36c0a6d40 2024-05-18) running on x86_64-unknown-linux-gnu

note: compiler flags: --crate-type lib -Z dump-mir-dir=dir

query stack during panic:
#0 [lint_mod] linting top-level module
#1 [analysis] running analysis passes on this crate
end of query stack
warning: 3 warnings emitted


```

</p>
</details>

@rustbot label +F-return_position_impl_trait_in_trait +F-return_type_notation

### LINKED ISSUE #126850: ICE: `no def-id for fresh lifetime`
auto-reduced (treereduce-rust):
````rust
fn bug<T>() -> impl Iterator<
    Item = [(); {
               |found: &String| Some(false);
               4
           }],
> {
    std::iter::empty()
}

fn main() {}


````

original:
````rust
#![allow(unused_must_use)]
fn bug<T>() -> impl Iterator<Item = [(); { |found: &String| Some(false); 4 }]> {
    std::iter::empty()
}

fn ok<T>() -> Box<dyn Iterator<Item = [(); { |x: u32| { x }; 4 }]>> {
    Box::new(std::iter::empty())
}

fn main() {
    for _item in ok::<u32>() {}
    for _item in bug::<u32>() {}
}

````

Version information
````
rustc 1.81.0-nightly (acb62737a 2024-06-23)
binary: rustc
commit-hash: acb62737aca7045f331e7a05adc38bed213e278d
commit-date: 2024-06-23
host: x86_64-unknown-linux-gnu
release: 1.81.0-nightly
LLVM version: 18.1.7

````

Command:
`/home/matthias/.rustup/toolchains/master/bin/rustc -Zincremental-verify-ich=yes -Cincremental=<dir> -Cdebuginfo=2`

<details><summary><strong>Program output</strong></summary>
<p>

```
warning: unused variable: `found`
 --> /tmp/icemaker_global_tempdir.fh96CiIOsxK3/rustc_testrunner_tmpdir_reporting.U9ifJLvY9ftQ/mvce.rs:3:17
  |
3 |                |found: &String| Some(false);
  |                 ^^^^^ help: if this is intentional, prefix it with an underscore: `_found`
  |
  = note: `#[warn(unused_variables)]` on by default

warning: function `bug` is never used
 --> /tmp/icemaker_global_tempdir.fh96CiIOsxK3/rustc_testrunner_tmpdir_reporting.U9ifJLvY9ftQ/mvce.rs:1:4
  |
1 | fn bug<T>() -> impl Iterator<
  |    ^^^
  |
  = note: `#[warn(dead_code)]` on by default

warning: unused closure that must be used
 --> /tmp/icemaker_global_tempdir.fh96CiIOsxK3/rustc_testrunner_tmpdir_reporting.U9ifJLvY9ftQ/mvce.rs:3:16
  |
3 |                |found: &String| Some(false);
  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: closures are lazy and do nothing unless called
  = note: `#[warn(unused_must_use)]` on by default

warning: 3 warnings emitted

note: no errors encountered even though delayed bugs were created

note: those delayed bugs will now be shown as internal compiler errors

error: internal compiler error: no def-id for fresh lifetime
 --> /tmp/icemaker_global_tempdir.fh96CiIOsxK3/rustc_testrunner_tmpdir_reporting.U9ifJLvY9ftQ/mvce.rs:3:24
  |
3 |                |found: &String| Some(false);
  |                        ^^^^^^^
  |
note: delayed at compiler/rustc_ast_lowering/src/lib.rs:1650:30 - disabled backtrace
 --> /tmp/icemaker_global_tempdir.fh96CiIOsxK3/rustc_testrunner_tmpdir_reporting.U9ifJLvY9ftQ/mvce.rs:3:24
  |
3 |                |found: &String| Some(false);
  |                        ^^^^^^^

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: please make sure that you have updated to the latest nightly

note: rustc 1.81.0-nightly (acb62737a 2024-06-23) running on x86_64-unknown-linux-gnu

note: compiler flags: -Z incremental-verify-ich=yes -C incremental=[REDACTED] -C debuginfo=2

query stack during panic:
end of query stack

```

</p>
</details>

### PR DESCRIPTION
**Pull request by cjgillot**
Current AST->HIR lowering goes out of its way to remap lifetimes for opaque types. This is complicated and leaks into upstream and downstream code.

This PR stops trying to be clever during lowering, and prefers to do this remapping during the HIR->ty lowering. The remapping computation easily fits into the bound var resolution code. Its result can be used in by `generics_of` and `hir_ty_lowering::new_opaque` to add the proper parameters and arguments.

See an example on the doc for query `opaque_captured_lifetimes`.

Based on https://github.com/rust-lang/rust/pull/129244/

Fixes https://github.com/rust-lang/rust/issues/125249 
Fixes https://github.com/rust-lang/rust/issues/126850

cc @compiler-errors @spastorino 
r? @petrochenkov

### CODE REVIEW

**Comment by petrochenkov** [comment]
Blocked on https://github.com/rust-lang/rust/pull/129244.
@rustbot blocked

**Comment by cjgillot** [comment]
@compiler-errors do you mind taking a look? I'm not sure I correctly implemented the logic around `use` bounds.

**Comment by compiler-errors** [comment]
Sure. If I don't look at this in a day or two, please ping me. Do you have any specific concerns, like any code that you are suspicious that may act differently than before or needs some input, or do you just want a general review?

File: tests/ui/impl-trait/precise-capturing/capturing-implicit.rs [hunk 1]
```diff
@@ -6,9 +6,8 @@
 #![rustc_variance_of_opaques]
 
 fn foo(x: &()) -> impl IntoIterator<Item = impl Sized> + use<> {
-    //~^ ERROR ['_: o]
-    //~| ERROR ['_: o]
-    //~| ERROR `impl Trait` captures lifetime parameter
+    //~^ ERROR []
```
Comment (compiler-errors) [inline tests/ui/impl-trait/precise-capturing/capturing-implicit.rs:9]: Ah, this doesn't seem right. Or at least, it changes the semantics of what we mean by "capture all in-scope parameters" for nested opaques.

Without having yet looked at the code, I assume what's happening here is that the nested opaque doesn't see any nested lifetimes because of the `use<>` from the outer opaque. Is that right?

Comment (compiler-errors) [reply tests/ui/impl-trait/precise-capturing/capturing-implicit.rs:9]: I'm not actually certain if https://rust-lang.github.io/rfcs/3617-precise-capturing.html#summary prescribes what should happen here 🤔 -- it doesn't seem to do so, after having done a brief scan.

Comment (cjgillot) [reply tests/ui/impl-trait/precise-capturing/capturing-implicit.rs]: I changed the code to recurse and capture all in-scope lifetimes when we have nested opaques.

Comment (cjgillot) [reply tests/ui/impl-trait/precise-capturing/capturing-implicit.rs]: @compiler-errors I have re-implemented the resolution to walk the scopes and not stop at the closest opaque. Is this closer to what you had in mind?

Comment (compiler-errors) [reply tests/ui/impl-trait/precise-capturing/capturing-implicit.rs]: Yeah, I believe so. If in the future we want opaque type captures to stop at the closest opaque, we can do so; that actually seems like the right behavior, but this should mean there are no *observable* changes.

**Review by compiler-errors — APPROVED** [review]

**Comment by compiler-errors** [comment]
r=me,petrochenkov after rebase
