### PR TITLE
Do not use global caches if opaque types can be defined

### LINKED ISSUE #105787: occurs check with aliases results in error, not ambiguity
*edit: this issue has been partially fixed in #117088, so any remaining incompleteness (and therefore incorrectly accepted overflow) is a lot harder to trigger. See https://github.com/rust-lang/trait-system-refactor-initiative/issues/8 for a list of known issues with generalization. Keeping this issue open as is to track this, but we should try to write a test which relies on one of the other problems of that issue, now that the problem case 2 has been fixed.*

---
```rust
// Using the higher ranked projection hack to prevent us from replacing the projection
// with an inference variable.
trait ToUnit<'a> {
    type Unit;
}

struct LocalTy;
impl<'a> ToUnit<'a> for *const LocalTy {
    type Unit = ();
}

impl<'a, T: Copy + ?Sized> ToUnit<'a> for *const T {
    type Unit = ();
}

trait Overlap<T> {
    type Assoc;
}

type Assoc<'a, T> = <*const T as ToUnit<'a>>::Unit;

impl<T> Overlap<T> for T {
    type Assoc = usize;
}

impl<T> Overlap<for<'a> fn(&'a (), Assoc<'a, T>)> for T
where
    for<'a> *const T: ToUnit<'a>,
{
    type Assoc = Box<usize>;
}

fn foo<T: Overlap<U>, U>(x: T::Assoc) -> T::Assoc {
    x
}

fn main() {
    foo::<for<'a> fn(&'a (), ()), for<'a> fn(&'a (), ())>(3usize);
}
```

`for<'a> fn(&'a (), ())>: Overlap<for<'a> fn(&'a (), ())>>` can be satisfied using both impls, ignoring a deficiency of the current normalization routine which means that right now the second impl pretty much never applies.

Currently inference constraints from equating the self type are not used to normalize the trait argument so we fail when equating `()` with `Assoc<'a, for<'a> fn(&'a (), ())>` even those these two are the same type. This will change once deferred projection equality is implemented.

## why this currently passes coherence

Coherence does a pairwise check for all relevant impls. It starts by instantiating the impl parameters with inference vars and equating the impl headers. When we do that with `Overlap<T> for T` and `Overlap<for<'a> fn(&'a (), Assoc<'a, T>)> for T` we have:

- `eq(?0: Overflap<?0>, ?1: Overlap<for<'a> fn(&'a (), <*const ?1 as ToUnit<'a>>::Unit)>)`
    - `eq(?0, ?1)` constrains `?1` to be equal to `?0`
    - `eq(?0, for<'a> fn(&'a (), <*const ?0 as ToUnit<'a>>::Unit)>)`: this now fails the occurs check

The occurs check is necessary to prevent ourselves from creating infinitely large types, e.g. `?0 = Vec<?0>`. But it does mean that coherence considers these two impls to be disjoint. Because the inference var only occurs inside of a projection, there's a way to equate these two types without resulting in an infinitely large type by normalizing the projection.

### LINKED ISSUE #119272: ICE: `unexpected ambiguity: Canonical..`
auto-reduced (treereduce-rust):
````rust
#![feature(type_alias_impl_trait)]
mod defining_scope {
    use super::*;
    pub type Alias<T> = impl Sized;

    pub fn cast<T>(x: Container<Alias<T>, T>) -> Container<T, T> {
        x
    }
}

struct Container<T: Trait<U>, U> {
    x: <T as Trait<U>>::Assoc,
}

trait Trait<T> {
    type Assoc;
}

impl<T> Trait<T> for T {
    type Assoc = Box<u32>;
}
impl<T> Trait<T> for defining_scope::Alias<T> {
    type Assoc = usize;
}

fn main() {}


````

original:
````rust
//revisions: old next
//[next] compile-flags: -Znext-solver

// A regression test for #105787

//[old] known-bug: #105787
//[old] check-pass
#![feature(type_alias_impl_trait)]
mod defining_scope {
    use super::*;
    pub type Alias<T> = impl Sized;

    pub fn cast<T>(x: Container<Alias<T>, T>) -> Container<T, T> {
        x
    }
}

struct Container<T: Trait<U>, U> {
    x: <T as Trait<U>>::Assoc,
}

trait Trait<T> {
    type Assoc;
}

impl<T> Trait<T> for T {
    type Assoc = Box<u32>;
}
impl<T> Trait<T> for defining_scope::Alias<T> {
    //[next]~^ ERROR conflicting implementations of trait
    type Assoc = usize;
}

fn main() {
        Default::default()
    }

````

Version information
````
rustc 1.77.0-nightly (2d7be7393 2023-12-23)
binary: rustc
commit-hash: 2d7be73931e0978c8758a672cc7258b417a7e999
commit-date: 2023-12-23
host: x86_64-unknown-linux-gnu
release: 1.77.0-nightly
LLVM version: 17.0.6

````

Command:
`/home/matthias/.rustup/toolchains/master/bin/rustc `

<details><summary><strong>Program output</strong></summary>
<p>

```
warning: struct `Container` is never constructed
  --> /tmp/icemaker_global_tempdir.fzzOAlARA6tK/rustc_testrunner_tmpdir_reporting.utiWfmv9NFbE/mvce.rs:11:8
   |
11 | struct Container<T: Trait<U>, U> {
   |        ^^^^^^^^^
   |
   = note: `#[warn(dead_code)]` on by default

warning: function `cast` is never used
 --> /tmp/icemaker_global_tempdir.fzzOAlARA6tK/rustc_testrunner_tmpdir_reporting.utiWfmv9NFbE/mvce.rs:6:12
  |
6 |     pub fn cast<T>(x: Container<Alias<T>, T>) -> Container<T, T> {
  |            ^^^^

error: internal compiler error: no errors encountered even though `span_delayed_bug` issued

error: internal compiler error: unexpected ambiguity: Canonical { value: ParamEnvAnd { param_env: ParamEnv { caller_bounds: [Binder { value: TraitPredicate(<T as std::marker::Sized>, polarity:Positive), bound_vars: [] }], reveal: All }, value: AliasTy { args: [T/#0, T/#0], def_id: DefId(0:15 ~ mvce[8437]::Trait::Assoc) } }, max_universe: U0, variables: [] } Canonical { value: QueryResponse { var_values: CanonicalVarValues { var_values: [] }, region_constraints: QueryRegionConstraints { outlives: [], member_constraints: [] }, certainty: Ambiguous, opaque_types: [], value: NormalizationResult { normalized_ty: ^0 } }, max_universe: U0, variables: [CanonicalVarInfo { kind: Ty(General(U0)) }] }
  |
  = note: delayed at compiler/rustc_trait_selection/src/traits/query/normalize.rs:295:34
             0: <rustc_errors::DiagCtxtInner>::emit_diagnostic_without_consuming
             1: <rustc_errors::DiagCtxt>::emit_diagnostic_without_consuming
             2: <rustc_errors::DiagCtxt>::emit_diagnostic
             3: <rustc_session::session::Session>::span_delayed_bug::<rustc_span::span_encoding::Span, alloc::string::String>
             4: <rustc_trait_selection::traits::query::normalize::QueryNormalizer as rustc_type_ir::fold::FallibleTypeFolder<rustc_middle::ty::context::TyCtxt>>::try_fold_ty
             5: <rustc_traits::normalize_erasing_regions::provide::{closure#0} as core::ops::function::FnOnce<(rustc_middle::ty::context::TyCtxt, rustc_middle::ty::ParamEnvAnd<rustc_middle::ty::generic_args::GenericArg>)>>::call_once
             6: rustc_query_impl::plumbing::__rust_begin_short_backtrace::<rustc_query_impl::query_impl::try_normalize_generic_arg_after_erasing_regions::dynamic_query::{closure#2}::{closure#0}, rustc_middle::query::erase::Erased<[u8; 8]>>
             7: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::DynamicConfig<rustc_query_system::query::caches::DefaultCache<rustc_middle::ty::ParamEnvAnd<rustc_middle::ty::generic_args::GenericArg>, rustc_middle::query::erase::Erased<[u8; 8]>>, false, false, false>, rustc_query_impl::plumbing::QueryCtxt, false>
             8: rustc_query_impl::query_impl::try_normalize_generic_arg_after_erasing_regions::get_query_non_incr::__rust_end_short_backtrace
             9: <rustc_middle::ty::normalize_erasing_regions::TryNormalizeAfterErasingRegionsFolder as rustc_type_ir::fold::FallibleTypeFolder<rustc_middle::ty::context::TyCtxt>>::try_fold_ty
            10: rustc_ty_utils::needs_drop::needs_drop_raw
            11: rustc_query_impl::plumbing::__rust_begin_short_backtrace::<rustc_query_impl::query_impl::needs_drop_raw::dynamic_query::{closure#2}::{closure#0}, rustc_middle::query::erase::Erased<[u8; 1]>>
            12: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::DynamicConfig<rustc_query_system::query::caches::DefaultCache<rustc_middle::ty::ParamEnvAnd<rustc_middle::ty::Ty>, rustc_middle::query::erase::Erased<[u8; 1]>>, false, false, false>, rustc_query_impl::plumbing::QueryCtxt, false>
            13: rustc_query_impl::query_impl::needs_drop_raw::get_query_non_incr::__rust_end_short_backtrace
            14: <rustc_mir_transform::elaborate_drops::ElaborateDrops as rustc_middle::mir::MirPass>::run_pass
            15: rustc_mir_transform::run_analysis_to_runtime_passes
            16: rustc_mir_transform::mir_drops_elaborated_and_const_checked
            17: rustc_query_impl::plumbing::__rust_begin_short_backtrace::<rustc_query_impl::query_impl::mir_drops_elaborated_and_const_checked::dynamic_query::{closure#2}::{closure#0}, rustc_middle::query::erase::Erased<[u8; 8]>>
            18: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::DynamicConfig<rustc_query_system::query::caches::VecCache<rustc_span::def_id::LocalDefId, rustc_middle::query::erase::Erased<[u8; 8]>>, false, false, false>, rustc_query_impl::plumbing::QueryCtxt, false>
            19: rustc_query_impl::query_impl::mir_drops_elaborated_and_const_checked::get_query_non_incr::__rust_end_short_backtrace
            20: rustc_interface::passes::analysis
            21: rustc_query_impl::plumbing::__rust_begin_short_backtrace::<rustc_query_impl::query_impl::analysis::dynamic_query::{closure#2}::{closure#0}, rustc_middle::query::erase::Erased<[u8; 1]>>
            22: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::DynamicConfig<rustc_query_system::query::caches::SingleCache<rustc_middle::query::erase::Erased<[u8; 1]>>, false, false, false>, rustc_query_impl::plumbing::QueryCtxt, false>
            23: rustc_query_impl::query_impl::analysis::get_query_non_incr::__rust_end_short_backtrace
            24: rustc_interface::interface::run_compiler::<core::result::Result<(), rustc_span::ErrorGuaranteed>, rustc_driver_impl::run_compiler::{closure#0}>::{closure#0}
            25: std::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface::util::run_in_thread_with_globals<rustc_interface::util::run_in_thread_pool_with_globals<rustc_interface::interface::run_compiler<core::result::Result<(), rustc_span::ErrorGuaranteed>, rustc_driver_impl::run_compiler::{closure#0}>::{closure#0}, core::result::Result<(), rustc_span::ErrorGuaranteed>>::{closure#0}, core::result::Result<(), rustc_span::ErrorGuaranteed>>::{closure#0}::{closure#0}, core::result::Result<(), rustc_span::ErrorGuaranteed>>
            26: <<std::thread::Builder>::spawn_unchecked_<rustc_interface::util::run_in_thread_with_globals<rustc_interface::util::run_in_thread_pool_with_globals<rustc_interface::interface::run_compiler<core::result::Result<(), rustc_span::ErrorGuaranteed>, rustc_driver_impl::run_compiler::{closure#0}>::{closure#0}, core::result::Result<(), rustc_span::ErrorGuaranteed>>::{closure#0}, core::result::Result<(), rustc_span::ErrorGuaranteed>>::{closure#0}::{closure#0}, core::result::Result<(), rustc_span::ErrorGuaranteed>>::{closure#1} as core::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
            27: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
                       at /rustc/2d7be73931e0978c8758a672cc7258b417a7e999/library/alloc/src/boxed.rs:2015:9
            28: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
                       at /rustc/2d7be73931e0978c8758a672cc7258b417a7e999/library/alloc/src/boxed.rs:2015:9
            29: std::sys::unix::thread::Thread::new::thread_start
                       at /rustc/2d7be73931e0978c8758a672cc7258b417a7e999/library/std/src/sys/unix/thread.rs:108:17
            30: <unknown>
            31: <unknown>
          

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.77.0-nightly (2d7be7393 2023-12-23) running on x86_64-unknown-linux-gnu

query stack during panic:
end of query stack
error: aborting due to 2 previous errors; 2 warnings emitted


```

</p>
</details>

### PR DESCRIPTION
**Pull request by oli-obk**
fixes #119272

r? @lcnr

This is certainly a crude way to make the cache sound wrt opaque types, but since perf lets us get away with this, let's do it in the old solver and let the new solver fix this correctly once and for all.

cc https://github.com/rust-lang/rust/pull/122192#issuecomment-2149252655

### CODE REVIEW

**Comment by lcnr** [comment]
this is unfortunately still not tracking the current hidden type for the opaque afaict: `Projection(<T as Trait>::Assoc, impl Foo)` should have a different result on the hidden type of `impl Foo`.

Have you tried entirely disabling the global cache, only using the one local to the current `infcx` if we're defining at least one opaque types?

**Comment by oli-obk** [comment]
That would require duplicating the cache data structures, but i'll give it a shot. Just disabling caching entirely was too bad to land https://github.com/rust-lang/rust/pull/126024#issuecomment-2149855388

**Comment by oli-obk** [comment]
> this is unfortunately still not tracking the current hidden type for the opaque afaict: `Projection(<T as Trait>::Assoc, impl Foo)` should have a different result on the hidden type of `impl Foo`.

Huh? only in reveal all mode, where it doesn't matter anyway. We don't use the hidden type in projections in the old solver iirc

**Comment by lcnr** [comment]
https://github.com/rust-lang/rust/blob/2d28b6384e5e0a2c9d1500a1f65e35423453fbf6/compiler/rustc_trait_selection/src/traits/project.rs#L271-L276

**Comment by lcnr** [comment]
> That would require duplicating the cache data structures, but i'll give it a shot. Just disabling caching entirely was too bad to land [#126024 (comment)](https://github.com/rust-lang/rust/pull/126024#issuecomment-2149855388)

wait, can we not use the `infcx` local cache at this point? without storing the list of defined opaque types?

**Comment by lcnr** [comment]
we already do that for stuff referencing inference variables, so i can imagine changing it to "mentions infer var || has opaque types" (which is incorrect for TAIT as you can insert it via impl candidates, but :shrug:)

**Comment by oli-obk** [comment]
Without https://github.com/rust-lang/rust/pull/121848 that reintroduces https://github.com/rust-lang/rust/issues/105787#issuecomment-1750112388

@rustbot blocked

**Comment by lcnr** [comment]
> Without #121848 that reintroduces [#105787 (comment)](https://github.com/rust-lang/rust/issues/105787#issuecomment-1750112388)
> 
> @rustbot blocked

why? caching fewer goals shouldn't change any behavior :thinking:

**Comment by oli-obk** [comment]
No idea, didn't debug yet, but the issue doesn't occur if I just disable all caching (https://github.com/rust-lang/rust/commit/07141681cbcc097718003ad64e0c87bf1d8d56cd), so something v fishy is going on.

**Comment by oli-obk** [comment]
Ah... the issue is that I'm *caching fewer things*, but still loading things from the cache. So `RPIT as Trait` is loaded from the cache during typeck of the defining function if it was inserted by a non-defining function.

**Comment by oli-obk** [comment]
Not blocked anymore. After a rebase the issue went away. Gonna assume it was some intermediate nightly bug that we were aware of and fixed independently of this PR

**Comment by lcnr** [comment]
r=me after comment nit

**Comment by oli-obk** [comment]
> r=me after comment nit

did you forget to submit a github review?

File: compiler/rustc_trait_selection/src/traits/select/mod.rs [hunk 1]
```diff
@@ -1509,6 +1509,11 @@ impl<'cx, 'tcx> SelectionContext<'cx, 'tcx> {
             return false;
         }
 
+        // Avoid using the global cache when we're defining opaque types.
```
Comment (lcnr) [inline compiler/rustc_trait_selection/src/traits/select/mod.rs:1512]:
```suggestion
        // Avoid using the global cache when we're defining opaque types
        // as their hidden type may impact the result of candidate selection.
```

**Comment by oli-obk** [comment]
😭 fuchsia "overflow evaluating requirement"

```
error[E0275]: overflow evaluating the requirement `ManuallyDrop<ReleaseGuard<FsNode>>: std::marker::Send`
Error:    --> ../../src/starnix/kernel/runner/component_runner.rs:169:21
    |
169 |       let weak_task = execute_task_with_prerun_result(
    |  _____________________^
170 | |         current_task,
171 | |         {
172 | |             let mount_record = mount_record.clone();
...   |
237 | |         None,
238 | |     )?;
    | |_____^
    |
    = help: consider increasing the recursion limit by adding a `#![recursion_limit = "256"]` attribute to your crate (`starnix_kernel_runner`)
note: required because it appears within the type `starnix_lifecycle::delayed_releaser::ObjectReleaser<FsNode, FsNodeReleaserAction>`
   --> ./../../src/starnix/kernel/lifecycle/delayed_releaser.rs:16:12
    = note: required for `std::sync::Weak<starnix_lifecycle::delayed_releaser::ObjectReleaser<FsNode, FsNodeReleaserAction>>` to implement `std::marker::Sync`
note: required because it appears within the type `FsNode`
   --> ./../../src/starnix/kernel/vfs/fs_node.rs:120:12
note: required because it appears within the type `ReleaseGuard<FsNode>`
   --> ./../../src/starnix/lib/starnix-uapi/src/ownership.rs:445:12
note: required because it appears within the type `ManuallyDrop<ReleaseGuard<FsNode>>`
   --> /checkout/library/core/src/mem/manually_drop.rs:50:12
    |
50  | pub struct ManuallyDrop<T: ?Sized> {
    |            ^^^^^^^^^^^^
note: required by a bound in `execute_task_with_prerun_result`
   --> ./../../src/starnix/kernel/execution/restricted_executor.rs:413:1
```

**Comment by oli-obk** [comment]
@craterbot check

**Comment by oli-obk** [comment]
cc @c6c7 are you the right person to ping about fuchsia issues?

**Comment by oli-obk** [comment]
cc @tmandry help! I am breaking fuchsia when fixing soundness bugs, what do I do?

**Comment by lcnr** [comment]
the underlying issue: if you first have some stack `A: Trait -> B: Trait -> ...` and that caches with some depth `n`, and then you later use the cache entry of `A: Trait` at depth `m`, this doesn't hit the overflow limit even if `n + m` if greater than it.

This does not cache query instability, as overflow is always fatal (which it has to be because of that). It should be fixed by increasing the recursion limit in fuchsia and then landing this PR

**Comment by lcnr** [comment]
fuchsia has two options:
- increase the recursion limit
- un-perfect-derive the affected auto traits[^1]
```rust
#[non_structural_derive(Send)]
struct Foo<T>(T, Box<Option<Foo<T>>>);

// expands to
const _: () = {
    unsafe impl<T: Send> Send for Foo<T> {}
    fn _validate<T: Send>() {
        non_structural_derive::check_send::<T>();
        non_structural_derive::check_send::<Box<Option<Foo<T>>>>();
    }
};
```
[^1]: this doesn't yet exist as a crate, but potentially should

**Comment by tmandry** [comment]
Thanks for the ping, we should have a change up for testing soon.

As a reminder you can do `@rustbot ping fuchsia` to get more than just me.

**Comment by oli-obk** [comment]
none of the failures are related.

@bors r=lcnr

**Comment by lcnr** [comment]
need the recursion limit increase in more (probably pretty much all) fuchsia crates

**Comment by oli-obk** [comment]
@tmandry could you create a patch for fuchsia that works on 19a6f8191b33025dc4b394801d2d2e85432c752c ?

**Comment by mk12** [comment]
@oli-obk I've done it in https://fxrev.dev/1087892. I reproduced the failures before and had a successful build after.

File: src/ci/docker/host-x86_64/x86_64-fuchsia/build-fuchsia.sh [hunk 2]
```diff
@@ -29,7 +29,7 @@ KEEP_CHECKOUT=
 # Gerrit changes from https://fxrev.dev during development (click the "Download"
 # button on a changelist to see the cherry pick ref). Example:
 # PICK_REFS=(refs/changes/71/1054071/2 refs/changes/74/1054574/2)
-PICK_REFS=()
+PICK_REFS=(refs/changes/93/1082793/1)
```
Comment (tmandry) [inline src/ci/docker/host-x86_64/x86_64-fuchsia/build-fuchsia.sh:32]:
```suggestion
PICK_REFS=(refs/changes/93/1082793/1 refs/changes/92/1087892/1)
```

**Comment by tmandry** [comment]
Thanks @mk12! This should work now..

@bors r=lcnr

**Comment by tmandry** [comment]
Flake

@bors retry

**Comment by mk12** [comment]
CI is showing a merge conflict in src/starnix/kernel/runner/lib.rs. What base commit does it apply PICK_REFS on top of? https://fxrev.dev/1087892 was submitted at 4:33pm and rolled at 4:36pm PT, right around the same time as CI ran.

**Comment by tmandry** [comment]
@mk12 it's the one in build-fuchsia.sh.

Opened #128127 to bump the commit instead of using cherry picks.

**Comment by Kobzol** [comment]
https://github.com/rust-lang/rust/pull/128127 was merged.

**Comment by oli-obk** [comment]
Hmm... I forgot to rerun perf... But, this PR does fix a lingering soundness issue that we just don't have a reproduction for. The caches are now sound, but not used globally if an item has opaques. That's obviously a bulldozing way of solving this issue, but I'm not sure we can fix it in a robust way in the old solver.

**Comment by pnkfelix** [comment]
Hmm... this PR claims that it fixes #119272 , but the ICE listed there is still occurring.

Is the idea that there is an unsoundness that is somehow being illustrated by the test case in that issue, and this PR is addressing that unsoundness (via a blunt hammer) while the ICE itself is still not addressed? (Or was the wrong issue simply linked here?)
