### PR TITLE
Fix stray notes when the source code is not available

### LINKED ISSUE #87060: "note: deref defined here", but it doesn't actually show anything
Given the following code: ([playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=42fbfa2bb5053ea312d329c7c2cbe55d))

```rust
fn main() {
    let x = std::path::PathBuf::new();
    std::fs::create_dir(x);
    dbg!(x.join("x"));
}
```

The current output is:

```
error[E0382]: borrow of moved value: `x`
    --> src/main.rs:4:10
     |
2    |     let x = std::path::PathBuf::new();
     |         - move occurs because `x` has type `PathBuf`, which does not implement the `Copy` trait
3    |     std::fs::create_dir(x);
     |                         - value moved here
4    |     dbg!(x.join("x"));
     |          ^^^^^^^^^^^ value borrowed here after move
     |
     = note: borrow occurs due to deref coercion to `Path`
note: deref defined here
```

It would seem as if something is supposed to come after "deref defined here".

### PR DESCRIPTION
**Pull request by FabianWolff**
Fixes #87060. To reproduce it with a local build of rustc, you have to copy the compiler (e.g. `build/x86_64-unknown-linux-gnu/stage1/`) somewhere and then rename the compiler source directory (maybe there is a smarter way as well). Then, rustc won't find the standard library sources and report stray notes such as
```
note: deref defined here
```
with no location for "here". Another example I've found is this:
```rust
use std::ops::Add;

fn foo<T: Add<Output=()>>(x: T) {
    x + x;
}

fn main() {}
```
```
error[E0382]: use of moved value: `x`
  --> binop.rs:4:9
   |
3  | fn foo<T: Add<Output=()>>(x: T) {
   |                           - move occurs because `x` has type `T`, which does not implement the `Copy` trait
4  |     x + x;
   |     ----^
   |     |   |
   |     |   value used here after move
   |     `x` moved due to usage in operator
   |
note: calling this operator moves the left-hand side
help: consider further restricting this bound
   |
3  | fn foo<T: Add<Output=()> + Copy>(x: T) {
   |                          ^^^^^^

error: aborting due to previous error
```
where, again, the note is supposed to point somewhere but doesn't. I have fixed this by checking whether the corresponding source code is actually available before emitting the note.

### CODE REVIEW

**Comment by jackh726** [comment]
Any way to write a test for this?

File: compiler/rustc_mir/src/borrow_check/diagnostics/conflict_errors.rs [hunk 1]
```diff
@@ -192,7 +192,19 @@ impl<'cx, 'tcx> MirBorrowckCtxt<'cx, 'tcx> {
...
-                                    self_arg.span,
+                                    // Check whether the source is accessible
+                                    if self
+                                        .infcx
+                                        .tcx
+                                        .sess
+                                        .source_map()
+                                        .span_to_snippet(self_arg.span)
+                                        .is_ok()
+                                    {
```
Comment (estebank) [inline compiler/rustc_mir/src/borrow_check/diagnostics/conflict_errors.rs:203]: It would be nice if we could add something akin to `span_note_with_alternative` so that we could provide a fallback span.

**Review by estebank — APPROVED** [review]
r=me after rebase

**Comment by estebank** [comment]
> Any way to write a test for this?

It would likely require a `Makefile` test that uses extern crates and mucks around with its path after building.
