### PR TITLE
optimize reassignment immutable state

### LINKED ISSUE #53189: [nll] optimize + fix `check_if_reassignment_to_immutable_state`
`check_if_reassignment_to_immutable_state` has the of handling assignments to immutable local variables. These are a bit tricky: you are allowed to assign to an immutable local variable, but only if it has never been assigned to before. Actually, the logic implemented in the NLL borrow checker is kind of wrong (or at least inconsistent with the AST checker). It's also just slow.

Here is an example of the sort of assignments that should be accepted ([playground](https://play.rust-lang.org/?gist=ea1288910f0a2d7c35c4987908e500dd&version=nightly&mode=debug&edition=2015)):

```rust
#![feature(nll)]

fn main() {
    let x: (u32, u32);
    
    if true {
        x = (1, 2);
    } else {
        x = (3, 4);
    }
    
    drop(x);
}
```

This example is **rightly rejected** (but we should check to ensure we have a test) ([playground](https://play.rust-lang.org/?gist=5d731471b5de93c6e15d198feb5fc102&version=nightly&mode=debug&edition=2015)):

```rust
#![feature(nll)]

fn main() {
    let x: (u32, u32);
    x = (1, 2);
    x = (3, 4);
    drop(x);
}
```

This example **should be rejected but currently is not** ([playground](https://play.rust-lang.org/?gist=bddb5e348fd76c46b13b5a71eea1df59&version=nightly&mode=debug&edition=2015)):

```rust
#![feature(nll)]

fn main() {
    let x: (u32, u32);
    
    x.0 = 22;
}
```

In addition to being slightly wrong, the current implementation is also slow. It iterates over all initialized paths and checks that the path being assigned to (e.g., `x.0` in the third example) is disjoint from all of them:

https://github.com/rust-lang/rust/blob/52c785bfc24e43c668c9022cc1e79edcd6dcfd7c/src/librustc_mir/borrow_check/mod.rs#L1612-L1619

I will write below how I think it *should* work.

### PR DESCRIPTION
**Pull request by nikomatsakis**
This is the "simple fix" when it comes to checking for reassignment. We just shoot for compatibility with the AST-based checker. Makes no attempt to solve #21232.

I opted for this simpler fix because I didn't want to think about complications [like the ones described here](https://github.com/rust-lang/rust/issues/21232#issuecomment-412219247).

Let's do some profiling measurements.

Fixes #53189 

r? @pnkfelix

### CODE REVIEW

**Comment by kennytm** [comment]
@rust-timer build 1cb82c2cd55f855bf84a37a9c20236fab3e9c685

**Comment by ljedrz** [comment]
Perf results are in; looking good, especially for keccak.

**Comment by nikomatsakis** [comment]
I was a bit disturbed since no tests broke when I changed this code. So I added some tests for various interesting scenarios (cc #21232).

File: src/test/ui/nll/assign_mutable_fields.rs [hunk 1]
```diff
@@ -0,0 +1,34 @@
...
+// option. This file may not be copied, modified, or distributed
+// except according to those terms.
+
+// Currently, we permit you to assign to individual fields of a mut
+// var, but we do not permit you to use the complete var afterwards.
+// We hope to fix this at some point.
+//
+// FIXME(#21232)
+
+#![feature(nll)]
```
Comment (pnkfelix) [inline src/test/ui/nll/assign_mutable_fields.rs]: it might be good to promote these tests outside of the `nll/` directory, and let the `compare-mode=nll` encode the differences in behavior between NLL and AST-borrowck. Just a thought.

Comment (pnkfelix) [reply src/test/ui/nll/assign_mutable_fields.rs]: (clearly I didn't care enough about whether this comment was addressed to let it hold up my r+. Still, feel free to incorporate this change if you can get to it before bors merges this.)

**Comment by kennytm** [comment]
UI test failures.

<details><summary>ui\immut-function-arguments.rs#mir</summary>

```diff
 ---- [ui] ui\immut-function-arguments.rs#mir stdout ----
 diff of stderr:
-	error[E0384]: cannot assign to immutable argument `y`
+	error[E0594]: cannot assign to `*y`, as `y` is not declared as mutable
2	  --> $DIR/immut-function-arguments.rs:15:5
3	   |
4	LL | fn f(y: Box<isize>) {
-	   |      - consider changing this to `mut y`
+	   |      - help: consider changing this to be mutable: `mut y`
6	LL |     *y = 5; //[ast]~ ERROR cannot assign
-	   |     ^^^^^^ cannot assign to immutable argument
+	   |     ^^^^^^ cannot assign
8	
-	error[E0384]: cannot assign to immutable argument `q`
+	error[E0594]: cannot assign to `*q`, as `q` is not declared as mutable
10	  --> $DIR/immut-function-arguments.rs:20:35
11	   |
12	LL |     let _frob = |q: Box<isize>| { *q = 2; }; //[ast]~ ERROR cannot assign
-	   |                  -                ^^^^^^ cannot assign to immutable argument
+	   |                  -                ^^^^^^ cannot assign
14	   |                  |
-	   |                  consider changing this to `mut q`
+	   |                  help: consider changing this to be mutable: `mut q`
16	
17	error: aborting due to 2 previous errors
18	
-	For more information about this error, try `rustc --explain E0384`.
+	For more information about this error, try `rustc --explain E0594`.
20	
```

</details>

<details><summary>ui\mut\mutable-class-fields.rs#mir</summary>

```diff
 ---- [ui] ui\mut\mutable-class-fields.rs#mir stdout ----
 diff of stderr:
-	error[E0384]: cannot assign twice to immutable variable `nyan`
+	error[E0594]: cannot assign to `nyan.how_hungry`, as `nyan` is not declared as mutable
2	  --> $DIR/mutable-class-fields.rs:28:3
3	   |
4	LL |   let nyan : cat = cat(52, 99);
-	   |       ----
-	   |       |
-	   |       first assignment to `nyan`
-	   |       consider changing this to `mut nyan`
+	   |       ---- help: consider changing this to be mutable: `mut nyan`
9	LL |   nyan.how_hungry = 0; //[ast]~ ERROR cannot assign
-	   |   ^^^^^^^^^^^^^^^^^^^ cannot assign twice to immutable variable
+	   |   ^^^^^^^^^^^^^^^^^^^ cannot assign
11	
12	error: aborting due to previous error
13	
-	For more information about this error, try `rustc --explain E0384`.
+	For more information about this error, try `rustc --explain E0594`.
15	
```

</details>
