### PR TITLE
compiler: Apply target features to the entry function

### LINKED ISSUE #146143: Global `-Ctarget-feature` flags not applied to entry function
I encountered an issue where global `-Ctarget-feature` flags are not consistently applied to the program’s entry function (e.g. main).

When passing `-Ctarget-feature=-avx`, the compiler does not attach the expected function-level `target-features` attributes to the entry function. As a result, the AVX feature is not fully disabled in that context. This leads to inconsistencies between global target feature settings and the actual function attributes emitted by `rustc`.

This discrepancy becomes particularly problematic under LTO. In cases where a feature is explicitly disabled in the Rust frontend but implicitly enabled by the LLVM backend for the target architecture, the entry function ends up with mismatched assumptions, potentially causing miscompilation or unexpected behavior.

I tried this code:

```rust
fn main() {}
```

```sh
rustc -O --emit llvm-ir -o - t.rs -C target-feature=-avx
```

I expected to see this happen:

The global target features should be applied to the entry function.

```
...

define void @main() unnamed_addr #5 personality ptr @rust_eh_personality {
  ...
}

attributes #5 = { nonlazybind "probe-stack"="inline-asm" "target-cpu"="x86-64" "target-features"="-avx,..." }

...
```

Instead, this happened:

The global target features were not applied to the entry function.

```
...

define void @main() unnamed_addr #5 personality ptr @rust_eh_personality {
  ...
}

attributes #5 = { nonlazybind "probe-stack"="inline-asm" "target-cpu"="x86-64" }

...
```

### Meta

`rustc --version --verbose`:
```
rustc 1.91.0-nightly (51ff89506 2025-09-02)
binary: rustc
commit-hash: 51ff895062ba60a7cba53f57af928c3fb7b0f2f4
commit-date: 2025-09-02
host: x86_64-unknown-linux-gnu
release: 1.91.0-nightly
LLVM version: 21.1.0
```

### PR DESCRIPTION
**Pull request by heiher**
Fixes rust-lang/rust#146143

### CODE REVIEW

File: compiler/rustc_codegen_ssa/src/traits/misc.rs [hunk 1]
```diff
@@ -23,6 +23,7 @@ pub trait MiscCodegenMethods<'tcx>: BackendTypes {
     fn sess(&self) -> &Session;
     fn set_frame_pointer_type(&self, llfn: Self::Function);
     fn apply_target_cpu_attr(&self, llfn: Self::Function);
+    fn apply_target_features(&self, llfn: Self::Function);
```
Comment (WaffleLapkin) [inline compiler/rustc_codegen_ssa/src/traits/misc.rs]: please write a doc comment explaining what this function is supposed to do

File: compiler/rustc_codegen_llvm/src/context.rs [hunk 2]
```diff
@@ -846,6 +846,16 @@ impl<'ll, 'tcx> MiscCodegenMethods<'tcx> for CodegenCx<'ll, 'tcx> {
...
 
+    fn apply_target_features(&self, llfn: &'ll Value) {
+        let mut attrs = SmallVec::<[_; 2]>::new();
+        let global_features = self.tcx.global_backend_features(()).iter().map(|s| s.as_str());
+        let target_features: String = global_features.intersperse(",").collect();
+        if !target_features.is_empty() {
+            attrs.push(llvm::CreateAttrStringValue(self.llcx, "target-features", &target_features));
+        }
+        attributes::apply_to_llfn(llfn, llvm::AttributePlace::Function, &attrs);
+    }
```
Comment (petrochenkov) [inline compiler/rustc_codegen_llvm/src/context.rs]: Looks like this was copied from `fn llfn_attrs_from_instance`, which lives in `rustc_codegen_llvm`, and is used only in `rustc_codegen_llvm`.
So I'd suggest to 1) keep this inside llvm codegen and do not introduce a new interface to codegen ssa, and 2) reuse the code in both `llfn_attrs_from_instance` and `create_entry_fn` without copypaste.

File: compiler/rustc_codegen_ssa/src/base.rs [hunk 3]
```diff
@@ -524,6 +524,7 @@ pub fn maybe_create_entry_wrapper<'a, 'tcx, Bx: BuilderMethods<'a, 'tcx>>(
         // `main` should respect same config for frame pointer elimination as rest of code
         cx.set_frame_pointer_type(llfn);
         cx.apply_target_cpu_attr(llfn);
+        cx.apply_target_features(llfn);
```
Comment (bjorn3) [inline compiler/rustc_codegen_ssa/src/base.rs]: Maybe the `apply_target_*` calls and `set_frame_pointer_type` should be grouped together into a single function.

I noticed that `gen_fn` inside `compiler/rustc_codegen_llvm/src/intrinsic.rs` is also missing the `apply_target_features` by the way.

Comment (heiher) [reply compiler/rustc_codegen_ssa/src/base.rs]: > I noticed that `gen_fn` inside `compiler/rustc_codegen_llvm/src/intrinsic.rs` is also missing the `apply_target_features` by the way.

I also noticed `gen_fn` in `compiler/rustc_codegen_llvm/src/intrinsic.rs`, but it appears to apply target features through `fn_abi.apply_attrs_llfn(self, llfn, instance);`.

File: compiler/rustc_codegen_llvm/src/context.rs (hunk 2 above)
Comment (heiher) [reply compiler/rustc_codegen_llvm/src/context.rs]: @rustbot ready

File: compiler/rustc_codegen_llvm/src/context.rs [hunk 4]
```diff
@@ -853,15 +853,19 @@ impl<'ll, 'tcx> MiscCodegenMethods<'tcx> for CodegenCx<'ll, 'tcx> {
...
                 llvm::CallConv::from_conv(
                     self.sess().target.entry_abi,
                     self.sess().target.arch.borrow(),
                 ),
                 llvm::UnnamedAddr::Global,
                 fn_type,
-            ))
+            );
+            if let Some(attr) = attributes::target_features_attr(self, vec![]) {
+                attributes::apply_to_llfn(llfn, llvm::AttributePlace::Function, &[attr])
```
Comment (petrochenkov) [inline compiler/rustc_codegen_llvm/src/context.rs]:
```suggestion
            attributes::apply_to_llfn(llfn, llvm::AttributePlace::Function, attr.as_slice());
```
Nit: can use https://doc.rust-lang.org/stable/std/option/enum.Option.html#method.as_slice here.

Comment (heiher) [reply compiler/rustc_codegen_llvm/src/context.rs]: @rustbot ready
