### PR TITLE
use correct LLVM intrinsic for min/max on floats

### LINKED ISSUE #149537: f*::min/max do not behave as documented for signaling NaN on aarch64, or with optimizations
*[View all comments](https://triagebot.infra.rust-lang.org/gh-comments/rust-lang/rust/issues/149537)*

Our documentation says that `max(SNaN, 0.0)` should return `0.0`. On x86_64, this is [indeed what happens](https://play.rust-lang.org/?version=stable&mode=debug&edition=2024&gist=d0369ba3993d5531a22b5af3a3183fc3). However, on aarch64, we get a QNaN as a result instead. On Android, the reported result for this test is:
```
F32::from(F32::nan(Sign::Pos, NaNKind::Signaling, 1).as_f32().max(0.0)) = 0x7fc00001 (NaN: Pos, Quiet, payload = 0x1)
```

It seems that LLVM never actually correctly implemented the promise that "if exactly one argument is NaN, the other argument is returned". Recently things got a lot more messy (see https://github.com/llvm/llvm-project/issues/170082 and also [this discussion](https://discourse.llvm.org/t/rfc-a-consistent-set-of-semantics-for-the-floating-point-minimum-and-maximum-operations/89006)), but apparently things were already broken before this recent chaos.

Also, since [Rust 1.91](https://rust.godbolt.org/z/PxvbW5abE) optimizations seem to fold `max(SNaN, x)` into NaN.

It is also worth noting that glibc fmin/fmax were deliberately [patched](https://sourceware.org/bugzilla/show_bug.cgi?id=20947) so that SNaN inputs produce NaN results. (However, not all libc do that; the C standard generally says very little about SNaN.)

So it might just be worth dropping that promise and allowing NaN outputs when there is an SNaN input (but also continue to allow returning the other input).

Cc @tgross35 @valadaptive @nikic  @workingjubilee  @rust-lang/libs-api

### LINKED ISSUE #151286: fmax optimization on aarch64 unexpectedly working for signaling NaN
Related LLVM issue: https://github.com/llvm/llvm-project/issues/176624

I tried this code:

```rust
#[inline]
pub fn hypot(coords: &[f64]) -> f64 {
    let mut max = 0.0_f64;
    let mut found_nan = false;
    let mut abs_coords = Vec::with_capacity(10);

    for &x in coords {
        let ax = x.abs();
        abs_coords.push(ax);
        found_nan |= ax.is_nan();
        if ax > max {
            max = ax;
        }
    }

    vector_norm(&abs_coords, max, found_nan)
}

unsafe extern "C" {
    pub fn frexp(n: f64, exp: *mut i32) -> f64;
}

/// Compute the Euclidean norm of a vector with high precision.
pub fn vector_norm(vec: &[f64], max: f64, found_nan: bool) -> f64 {
    let n = vec.len();

    if max.is_infinite() {
        return max;
    }
    if found_nan {
        return f64::NAN;
    }

    let mut max_e: i32 = 0;
    unsafe { frexp(max, &mut max_e) };

    // the code below is totally unreachable, but making recursive call is important
    if max_e < -1023 {
        // When max_e < -1023, ldexp(1.0, -max_e) would overflow.
        // TODO: This can be in-place ops, but we allocate a copy since we take &[f64].
        // This is acceptable because subnormal inputs are extremely rare in practice.
        let vec_copy: Vec<f64> = vec.iter().map(|&x| x / f64::MIN_POSITIVE).collect();
        let r = f64::MIN_POSITIVE * vector_norm(&vec_copy, max / f64::MIN_POSITIVE, found_nan);
        unreachable!();
        return r;
    }

    unreachable!();
}

#[cfg(test)]
mod tests {
    use super::*;

    pub const SNAN: f64 = f64::from_bits(0x7FF0_0000_0000_0001);

    fn test_hypot(coords: &[f64]) {
        let rs_result = hypot(coords);

        // SNAN + INFINITY should return INFINITY
        if coords[0].to_bits() == SNAN.to_bits() && coords[1].to_bits() == f64::INFINITY.to_bits() {
            assert_eq!(
                rs_result.to_bits(),
                0x7ff0000000000000,
                "hypot([SNAN, INFINITY]) should return INFINITY, got 0x{:x}",
                rs_result.to_bits()
            );
        }

        // Minimal serde_json usage - required for bug to manifest
        // This code path is never executed for SNAN test case
        if rs_result.is_nan() {
            return;
        }

        let _json = serde_json::to_string(&rs_result).unwrap();
    }

    pub const EDGE_VALUES: &[f64] = &[SNAN, f64::INFINITY];

    #[test]
    fn edgetest_hypot() {
        for &x in EDGE_VALUES {
            for &y in EDGE_VALUES {
                test_hypot(&[x, y]);
            }
        }
    }
}

```
Full cargo: [math_bug.zip](https://github.com/user-attachments/files/24693677/math_bug.zip)

The code size is looking not small, but I couldn't cut it anymore.

I expected to see the debug profile and release profile takes same control path.
Instead, it hits different path on aarch64 with release profile

```shell
$ cargo +nightly test --lib
   Compiling math_bug v0.1.0 (/Users/user/Projects/rust/math_bug)
...
warning: `math_bug` (lib test) generated 3 warnings (run `cargo fix --lib -p math_bug --tests` to apply 2 suggestions)
    Finished `test` profile [unoptimized + debuginfo] target(s) in 1.04s
     Running unittests src/lib.rs (target/debug/deps/math_bug-0ebeb571c288fb81)

running 1 test
test tests::edgetest_hypot ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s
```

```
cargo +nightly test --lib --release

warning: `math_bug` (lib test) generated 3 warnings (run `cargo fix --lib -p math_bug --tests` to apply 2 suggestions)
    Finished `release` profile [optimized] target(s) in 0.06s
     Running unittests src/lib.rs (target/release/deps/math_bug-9708721fabfaa446)

running 1 test
test tests::edgetest_hypot ... FAILED

failures:

---- tests::edgetest_hypot stdout ----

thread 'tests::edgetest_hypot' (37720335) panicked at src/lib.rs:62:13:
assertion `left == right` failed: hypot([SNAN, INFINITY]) should return INFINITY, got 0x7ff8000000000000
  left: 9221120237041090560
 right: 9218868437227405312
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    tests::edgetest_hypot

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

error: test failed, to rerun pass `--lib`
```

### Meta

`rustc --version --verbose`:
```
$ cargo +nightly --version --verbose
cargo 1.94.0-nightly (6d1bd93c4 2026-01-10)
release: 1.94.0-nightly
commit-hash: 6d1bd93c47f059ec1344cb31e68a2fb284cbc6b1
commit-date: 2026-01-10
host: aarch64-apple-darwin
libgit2: 1.9.2 (sys:0.20.3 vendored)
libcurl: 8.7.1 (sys:0.4.84+curl-8.17.0 system ssl:(SecureTransport) LibreSSL/3.3.6)
ssl: OpenSSL 3.5.4 30 Sep 2025
os: Mac OS 26.0.1 [64-bit]
```

<details><summary>Backtrace</summary>
<p>

```
<backtrace>
```

</p>
</details>

### PR DESCRIPTION
**Pull request by RalfJung**
*[View all comments](https://triagebot.infra.rust-lang.org/gh-comments/rust-lang/rust/pull/153343)*

The Rust `minnum`/`maxnum` intrinsics are documented to return the other argument when one input is an SNaN. However, the LLVM lowering we currently choose for them does not match those semantics: we lower them to `minnum`/`maxnum`, which (since https://github.com/llvm/llvm-project/pull/172012) is documented to non-deterministically return the other argument or NaN when one input is an SNaN.

LLVM does have an intrinsic with the intended semantics: `minimumnum`/`maximumnum`. Let's use that instead. We can set the `nsz` flag since we treat signed zero ordering as non-deterministic.

Also rename the intrinsics to follow the IEEE 2019 naming, since that is mostly (and in particular, as far as NaN are concerned) now what we do. Also, `minimum_number` and `minimum` are less easy to mix up than `minnum` and `minimum`.

r? @nikic 
Cc @tgross35 
Fixes https://github.com/rust-lang/rust/issues/149537
Fixes https://github.com/rust-lang/rust/issues/151286
(The issues are only fixed when using the latest supported LLVM, but I don't think we usually track problems specific to people compiling rustc with old versions of LLVM)

### CODE REVIEW

File: compiler/rustc_codegen_llvm/src/intrinsic.rs [hunk 1]
```diff
@@ -196,6 +186,29 @@ impl<'ll, 'tcx> IntrinsicCallBuilderMethods<'tcx> for Builder<'_, 'll, 'tcx> {
...
+                    "llvm.maximumnum"
+                };
+                let call = self.call_intrinsic(
+                    intrinsic_name,
+                    &[args[0].layout.immediate_llvm_type(self.cx)],
+                    &[args[0].immediate(), args[1].immediate()],
+                );
+                // `nsz` in minimumnum/maximumnum is special: its only effect is to make signed-zero
+                // ordering non-deterministic.
+                unsafe { llvm::LLVMRustSetNoSignedZeros(call) };
```
Comment (RalfJung) [inline compiler/rustc_codegen_llvm/src/intrinsic.rs:211]: I have no idea if the way I wired up `nsz` is correct.^^

File: compiler/rustc_codegen_cranelift/src/intrinsics/mod.rs [hunk 2]
```diff
@@ -1267,74 +1267,90 @@ fn codegen_regular_intrinsic_call<'tcx>(
...
         }
 
-        sym::minnumf16 => {
+        sym::minimum_numberf16 => {
             intrinsic_args!(fx, args => (a, b); intrinsic);
             let a = a.load_scalar(fx);
             let b = b.load_scalar(fx);
 
+            // FIXME: make sure this has the intended behavior for SNaN
+            // (returning the other argument).
```
Comment (RalfJung) [inline compiler/rustc_codegen_cranelift/src/intrinsics/mod.rs]: @bjorn3 does cranelift have intrinsics that have the intended guarantee re: SNaN?
Or should we use the fallback impl here?

File: compiler/rustc_codegen_gcc/src/intrinsic/mod.rs [hunk 3]
```diff
@@ -72,8 +72,10 @@ fn get_simple_intrinsic<'gcc, 'tcx>(
         sym::fmuladdf64 => "fma",  // TODO: use gcc intrinsic analogous to llvm.fmuladd.f64
         sym::fabsf32 => "fabsf",
         sym::fabsf64 => "fabs",
-        sym::minnumf32 => "fminf",
-        sym::minnumf64 => "fmin",
+        // FIXME: this does not guarantee the intended behavior for SNaN
```
Comment (RalfJung) [inline compiler/rustc_codegen_gcc/src/intrinsic/mod.rs]: @antoyo @GuillaumeGomez `fmin` and friends are no longer the right functions to call here as they don't make the SNaN guarantee. Should we call `fminimum_num` and friends instead? Those are much more recent.

File: compiler/rustc_llvm/llvm-wrapper/RustWrapper.cpp [hunk 4]
```diff
@@ -722,6 +722,13 @@ extern "C" void LLVMRustSetAllowReassoc(LLVMValueRef V) {
   }
 }
 
+// Enable the NSZ flag on the given instruction.
+extern "C" void LLVMRustSetNoSignedZeros(LLVMValueRef V) {
+  if (auto I = dyn_cast<Instruction>(unwrap<Value>(V))) {
+    I->setHasNoSignedZeros(true);
+  }
+}
```
Comment (nikic) [inline compiler/rustc_llvm/llvm-wrapper/RustWrapper.cpp:720]: The C bindings have a native LLVMSetFastMathFlags(), we should probably switch to that. But I guess we should do that consistently for the existing LLVMRustSetAlgebraicMath/LLVMRustSetAllowReassoc/LLVMRustSetFastMath as well, so I don't particularly mind this in the meantime.

**Review by nikic — COMMENTED** [review]
r=me once the questions for other backends are answered.

*[View changes since this review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/rust/153343/1b7d722f429f09c87b08b757d89c689c6cf7f6e7..685c6e99a50cd0ada21121eca0dd1732fbe79d0e)*

**Comment by RalfJung** [comment]
There are some odd things happening in CI
```
2026-03-03T12:31:32.4740066Z rustc-LLVM ERROR: Cannot select: 0xff67d41c22a0: f128 = fcanonicalize nsz 0xff67d41c2a10
2026-03-03T12:31:32.4740629Z   0xff67d41c2a10: f128 = AArch64ISD::CSEL 0xff67d41c5660, 0xff67d41c52e0, Constant:i32<11>, 0xff67d41c2930:1
```
Why did fcanonicalize end up with nsz? That was meant just for minimumnum.
And also it seems like f128 minimumnum is just broken on aarch64?

File: compiler/rustc_llvm/llvm-wrapper/RustWrapper.cpp (hunk 4 above)
Comment (RalfJung) [reply compiler/rustc_llvm/llvm-wrapper/RustWrapper.cpp:720]: Yeah I don't know why we have a separate wrapper for each flag configuration here, but I figured I'd follow the existing pattern.

File: library/core/src/intrinsics/mod.rs [hunk 5]
```diff
@@ -2999,10 +3001,12 @@ pub const unsafe fn write_bytes<T>(dst: *mut T, val: u8, count: usize);
 /// The stabilized version of this intrinsic is [`f16::min`].
 #[rustc_nounwind]
 #[rustc_intrinsic]
-pub const fn minnumf16(x: f16, y: f16) -> f16;
+pub const fn minimum_numberf16(x: f16, y: f16) -> f16;
```
Comment (RalfJung) [inline library/core/src/intrinsics/mod.rs]: One option for the other backends would be to add a default body that behaves the way we want.
```rust
if x.is_nan() {
    y
} else if y.is_nan() {
    x
} else if x < y {
    x
} else {
    y
}
```
That might also be an option for old LLVM versions -- we know `minnum` already doesn't always do the right thing there, despite what the docs said at the time.

File: compiler/rustc_codegen_gcc/src/intrinsic/mod.rs (hunk 3 above)
Comment (antoyo) [reply compiler/rustc_codegen_gcc/src/intrinsic/mod.rs]: Yes, we can do that.
If those are not GCC builtins, you would need to move them to `get_simple_function` instead.

Comment (RalfJung) [reply compiler/rustc_codegen_gcc/src/intrinsic/mod.rs]: @antoyo  I don't know if they are GCC builtins or how I'd figure that out. Please let me know how you'd like to see this implemented. (I also added a fallback impl so just not implementing them at all for now is an option.)

File: library/core/src/intrinsics/mod.rs [hunk 6]
```diff
@@ -2987,6 +2987,8 @@ pub const unsafe fn write_bytes<T>(dst: *mut T, val: u8, count: usize);
 
 /// Returns the minimum of two `f16` values, ignoring NaN.
 ///
+/// This behaves like IEEE 754-2019 minimumNumber, *except* that it does not order signed
+/// zeros deterministically. In particular:
 /// If one of the arguments is NaN (quiet or signaling), then the other argument is returned. If
 /// both arguments are NaN, returns NaN. If the inputs compare equal (such as for the case of `+0.0`
 /// and `-0.0`), either input may be returned non-deterministically.
```
Comment (tgross35) [inline library/core/src/intrinsics/mod.rs:2994]: I think this will get displayed with odd capitalization as `In particular: If one of ...` (not that it really matters)

File: library/core/src/intrinsics/mod.rs [hunk 7]
```diff
@@ -2999,10 +3001,19 @@ pub const unsafe fn write_bytes<T>(dst: *mut T, val: u8, count: usize);
 /// The stabilized version of this intrinsic is [`f16::min`].
 #[rustc_nounwind]
 #[rustc_intrinsic]
-pub const fn minnumf16(x: f16, y: f16) -> f16;
+pub const fn minimum_numberf16(x: f16, y: f16) -> f16 {
```
Comment (tgross35) [inline library/core/src/intrinsics/mod.rs]: Regarding the renaming, could we call these minimum_number_nszf16 or similar? It's a bit confusing currently since we don't actually support the IEEE op.

File: library/coretests/tests/floats/mod.rs [hunk 8]
```diff
@@ -724,11 +737,20 @@ float_test! {
...
-        assert_biteq!(flt(9.0).min(Float::NAN), 9.0);
-        assert_biteq!(flt(-9.0).min(Float::NAN), -9.0);
+        // We add black_box for the NAN tests as that used to be able to trigger miscompilations.
+        assert_biteq!(Float::NAN.min(black_box(9.0)), 9.0);
+        assert_biteq!(black_box(Float::NAN).min(-9.0), -9.0);
+        assert_biteq!(flt(9.0).min(black_box(Float::NAN)), 9.0);
+        assert_biteq!(black_box(flt(-9.0)).min(Float::NAN), -9.0);
         assert!(Float::NAN.min(Float::NAN).is_nan());
+        if !cfg!(target_arch = "aarch64") { // LLVM pre v21 miscompiled this on aarch64
+            // FIXME Remove ^ check when we require LLVM 21
```
Comment (tgross35) [inline library/coretests/tests/floats/mod.rs]: Fwiw I've been using `FIXME(llvm20)` and similar when there's something that should be greppable when we do LLVM version updates

**Comment by RalfJung** [comment]
For that try build I added a hack in the backend to always use the fallback impl. That's also what I did to reproduce this on the dev desktop.

**Comment by RalfJung** [comment]
@nikic thanks a ton, you just saved me a lot of digging. :)

File: library/core/src/intrinsics/mod.rs (hunk 6 above)
Comment (RalfJung) [reply library/core/src/intrinsics/mod.rs:2994]: When there's a full sentence after a `:`, the first word gets capitalized. So I don't see anything odd with the capitalization?

File: compiler/rustc_codegen_gcc/src/intrinsic/mod.rs (hunk 3 above)
Comment (antoyo) [reply compiler/rustc_codegen_gcc/src/intrinsic/mod.rs]: There builtins are defined in [this file](https://github.com/gcc-mirror/gcc/blob/master/gcc/builtins.def).
Usually, a builtin starts with `__builtin_`, but some of them, like `fmin` are also builtins (that's when `BOTH_P` is true).
Does the fallback call `fminimum_num` from compiler-builtins? If so, I'm OK with the fallback.

File: library/core/src/intrinsics/mod.rs (hunk 6 above)
Comment (tgross35) [reply library/core/src/intrinsics/mod.rs:2994]: Huh, TIL it's dependent on style guide (I never capitalize after and feel like that's more popular, interesting).

File: compiler/rustc_codegen_gcc/src/intrinsic/mod.rs (hunk 3 above)
Comment (RalfJung) [reply compiler/rustc_codegen_gcc/src/intrinsic/mod.rs]: I don't see any fminimum_num in that file so it seems like there's no builtin for this.

> Does the fallback call fminimum_num from compiler-builtins?

No, the fallback just implements the check directly, similar to the existing fallback for `minimum`/`maximum`.
```rust
pub const fn minimum_number_nsz_f32(x: f32, y: f32) -> f32 {
    if x.is_nan() || y <= x {
        y
    } else {
        // Either y > x or y is a NaN.
        x
    }
}
```

Comment (antoyo) [reply compiler/rustc_codegen_gcc/src/intrinsic/mod.rs]: Ok, I don't have any preference for the implementation: either use the fallback or call the function from `compiler-builtins`.

Comment (RalfJung) [reply compiler/rustc_codegen_gcc/src/intrinsic/mod.rs]: What would I do to call the compiler-builtins function? Just put "fminimum_num" etc in the string here?

I don't know either what works better. :shrug: The fallback is probably less risky.

Comment (antoyo) [reply compiler/rustc_codegen_gcc/src/intrinsic/mod.rs]: > What would I do to call the compiler-builtins function? Just put "fminimum_num" etc in the string here?

You would need to add it in `get_simple_function` with the parameter types and return type.

> I don't know either what works better. 🤷 The fallback is probably less risky.

I'm OK with using the fallback.

Comment (RalfJung) [reply compiler/rustc_codegen_gcc/src/intrinsic/mod.rs]: I am inclined to match what you do for `maximum`/`minimum`, which seems to be calling the compiler-builtin implementation.

However, looking at that implementation, I see this comment:
```
//! Excluded from our implementation is sNaN handling.
```
@tgross35 the implementations look correct for SNaN (in that they treat it like QNaN) -- any idea what that comment is about?

File: library/coretests/tests/floats/mod.rs [hunk 9]
```diff
@@ -724,11 +743,22 @@ float_test! {
...
-        assert_biteq!(Float::NAN.min(-9.0), -9.0);
-        assert_biteq!(flt(9.0).min(Float::NAN), 9.0);
-        assert_biteq!(flt(-9.0).min(Float::NAN), -9.0);
+        // We add black_box for the NAN tests as that used to be able to trigger miscompilations.
+        assert_biteq!(Float::NAN.min(black_box(9.0)), 9.0);
+        assert_biteq!(black_box(Float::NAN).min(-9.0), -9.0);
+        assert_biteq!(flt(9.0).min(black_box(Float::NAN)), 9.0);
+        assert_biteq!(black_box(flt(-9.0)).min(Float::NAN), -9.0);
         assert!(Float::NAN.min(Float::NAN).is_nan());
+        if !cfg!(target_arch = "aarch64") {
```
Comment (nikic) [inline library/coretests/tests/floats/mod.rs]: I expect this is going to happen not just for aarch64, but also other targets with IEEE 754-2008 maxNum instructions. Maybe we can drop the sNaN tests from here and instead have a separate UI test for that, so we can check the LLVM version?

File: compiler/rustc_codegen_gcc/src/intrinsic/mod.rs (hunk 3 above)
Comment (RalfJung) [reply compiler/rustc_codegen_gcc/src/intrinsic/mod.rs]: I am confused, there is `get_simple_intrinsic` and `get_simple_function` and some functions are handled in both of them...
but also `get_simple_function` has a comment saying "We can probably remove these and use the fallback intrinsic implementation" so indeed I'll just do that then after all.

Comment (antoyo) [reply compiler/rustc_codegen_gcc/src/intrinsic/mod.rs]: > but also `get_simple_function` has a comment saying "We can probably remove these and use the fallback intrinsic implementation" so indeed I'll just do that then after all.

I'm good with that.

File: library/coretests/tests/floats/mod.rs (hunk 9 above)
Comment (RalfJung) [reply library/coretests/tests/floats/mod.rs]: That's going to be duplicating a lot of code as here we have all the nice infrastructure to test something across all float types. :/

File: compiler/rustc_codegen_gcc/src/intrinsic/mod.rs (hunk 3 above)
Comment (tgross35) [reply compiler/rustc_codegen_gcc/src/intrinsic/mod.rs]: > @tgross35 the implementations look correct for SNaN (in that they treat it like QNaN) -- any idea what that comment is about?

I think this predates changes from the discussion around https://github.com/rust-lang/compiler-builtins/pull/939#discussion_r2132611727 and I forgot to update it. Opened https://github.com/rust-lang/compiler-builtins/pull/1104 to make sure it's tested and adjust the docs.

File: compiler/rustc_codegen_cranelift/src/intrinsics/mod.rs (hunk 2 above)
Comment (bjorn3) [reply compiler/rustc_codegen_cranelift/src/intrinsics/mod.rs]: The implementation is at https://github.com/rust-lang/rust/blob/69370dc4a8862b8401615a2a7b950704ba66c495/compiler/rustc_codegen_cranelift/src/num.rs#L501-L521 which avoids propagating any NaN if neither argument is a NaN. fmin/fmax follows the wasm spec:

https://webassembly.github.io/spec/core/exec/numerics.html#op-fmin

> * If either 𝑧1 or 𝑧2 is a NaN, then return an element of [nans](https://webassembly.github.io/spec/core/exec/numerics.html#aux-nans)𝑁{𝑧1,𝑧2}.
> * Else if either 𝑧1 or 𝑧2 is a negative infinity, then return negative infinity.
> * Else if either 𝑧1 or 𝑧2 is a positive infinity, then return the other value.
> * Else if both 𝑧1 and 𝑧2 are zeroes of opposite signs, then return negative zero.
> * Else return the smaller value of 𝑧1 and 𝑧2.

(and similar for fmax)

Comment (RalfJung) [reply compiler/rustc_codegen_cranelift/src/intrinsics/mod.rs]: That implementation looks pretty much identical to the fallback impl that's now in libcore. Would you prefer to keep the current lowering or use the fallback impl?

Comment (bjorn3) [reply compiler/rustc_codegen_cranelift/src/intrinsics/mod.rs]: The current lowering is probably slightly faster as cg_clif doesn't have inlining.

**Comment by RalfJung** [comment]
I think this answers all questions regarding other backends, so as per previous review
@bors r=nikic rollup=never

**Comment by RalfJung** [comment]
Well, let's just land it with the fallback impl for LLVM 21 then, since `minimumnum` apparently still has issues. https://github.com/rust-lang/rust/pull/153866 landed so this should be good to go.

@bors r=nikic rollup=never
