### PR TITLE
Show packed field alignment in mir_transform_unaligned_packed_ref

### LINKED ISSUE #147528: Confusing error message with unaligned access to `packed(n > 1)` fields
### Code

```Rust
#[repr(C, packed(4))]
pub struct Data {
    oxide_magic: u32,
    header_version: u32,
    monotonic_counter: u64,
    slot_select: u32,
}

fn main() {
    let d = Data {
        oxide_magic: 1,
        header_version: 1,
        monotonic_counter: 4,
        slot_select: 15,
    };
    println!("{}", d.monotonic_counter);
}
```

### Current output

```Shell
error[E0793]: reference to packed field is unaligned
  --> src/main.rs:16:20
   |
16 |     println!("{}", d.monotonic_counter);
   |                    ^^^^^^^^^^^^^^^^^^^
   |
   = note: packed structs are only aligned by one byte, and many modern architectures penalize unaligned field accesses
   = note: creating a misaligned reference is undefined behavior (even if that reference is never dereferenced)
   = help: copy the field contents to a local variable, or replace the reference with a raw pointer and use `read_unaligned`/`write_unaligned` (loads and stores via `*p` must be properly aligned even when using raw pointers)
   = note: this error originates in the macro `$crate::format_args_nl` which comes from the expansion of the macro `println` (in Nightly builds, run with -Z macro-backtrace for more info)

For more information about this error, try `rustc --explain E0793`.
error: could not compile `playground` (bin "playground") due to 1 previous er
```

### Desired output
Something along the lines of
```Shell
   = note: this struct is aligned to 4 bytes, but the variable requires 8-byte alignment
   = note: many modern architectures penalize unaligned field accesses
   = ...etc
```

### Rationale and extra context

It's confusing to see `packed structs are only aligned by one byte` when I have specified `packed(4)`

### Rust Version

```Shell
rustc 1.90.0 (1159e78c4 2025-09-14)
binary: rustc
commit-hash: 1159e78c4747b02ef996e55082b704c09b970588
commit-date: 2025-09-14
host: aarch64-apple-darwin
release: 1.90.0
LLVM version: 20.1.8
```

### PR DESCRIPTION
**Pull request by 21aslade**
Fixes rust-lang/rust#147528

I left the expected padding for the field out of the error message so the message would be the same on all platforms. It also isn't always possible to know the expected alignment, so this makes the message simpler.

### CODE REVIEW

File: compiler/rustc_mir_transform/src/errors.rs [hunk 1]
```diff
@@ -99,6 +99,8 @@ pub(crate) enum ConstMutate {
 pub(crate) struct UnalignedPackedRef {
     #[primary_span]
     pub span: Span,
+    pub actual: u64,
+    pub expected: u64,
```
Comment (21aslade) [inline compiler/rustc_mir_transform/src/errors.rs]: Currently this uses 0 as a sentinel value for "unknown expected alignment", because it seems that optional fields can't be used in diagnostics. Is there a better way to do this?

File: compiler/rustc_mir_transform/messages.ftl [hunk 2]
```diff
@@ -70,7 +70,7 @@ mir_transform_tail_expr_local = {$is_generated_name ->
     }
 
 mir_transform_unaligned_packed_ref = reference to packed field is unaligned
-    .note = packed structs are only aligned by one byte, and many modern architectures penalize unaligned field accesses
+    .note = this field is only {$actual}-byte aligned, but its type requires more alignment
```
Comment (madsmtm) [inline compiler/rustc_mir_transform/messages.ftl]:
```suggestion
    .note = this field is only {$actual}-byte aligned, but its type requires higher alignment
```

File: compiler/rustc_mir_transform/messages.ftl [hunk 3]
```diff
@@ -70,7 +70,7 @@ mir_transform_tail_expr_local = {$is_generated_name ->
     }
 
 mir_transform_unaligned_packed_ref = reference to packed field is unaligned
-    .note = packed structs are only aligned by one byte, and many modern architectures penalize unaligned field accesses
```
Comment (madsmtm) [inline compiler/rustc_mir_transform/messages.ftl:73]: What's the rationale for dropping the "many modern architectures penalize unaligned field accesses" part?

Maybe keep it as another `note`?

File: compiler/rustc_const_eval/src/util/alignment.rs [hunk 4]
```diff
@@ -40,12 +39,12 @@ where
                 layout.align.bytes(),
                 pack.bytes()
             );
-            false
+            None
         }
         _ => {
             // We cannot figure out the layout. Conservatively assume that this is disaligned.
             debug!("is_disaligned({:?}) - true", place);
-            true
```
Comment (madsmtm) [inline compiler/rustc_const_eval/src/util/alignment.rs:48]: Nit: Fix the `debug!` message above

File: compiler/rustc_const_eval/src/util/alignment.rs [hunk 5]
```diff
@@ -3,22 +3,21 @@ use rustc_middle::mir::*;
 use rustc_middle::ty::{self, TyCtxt};
 use tracing::debug;
 
-/// Returns `true` if this place is allowed to be less aligned
-/// than its containing struct (because it is within a packed
-/// struct).
+/// Returns the packed alignment if this place is allowed to be less aligned
+/// than its type normally requires (because it is within a packed struct).
 pub fn is_disaligned<'tcx, L>(
```
Comment (madsmtm) [inline compiler/rustc_const_eval/src/util/alignment.rs]: Nit: The `is_` part is kinda wrong now, maybe the function should be renamed?

Maybe something like `misalignment`? (would also fix my problem with the use of "disaligned" here which sounds weird, the proper term is "misaligned").

**Review by madsmtm — CHANGES_REQUESTED** [review]
Thanks, and welcome to working on the compiler! Have a few comments, see below. Remember to squash once you're done.

Also, I see that you originally implemented the full message as discussed by the referenced issue, but then decided to do something simpler - could you edit your top-level comment to discuss why this wasn't done in the end? (see [the review policy](https://forge.rust-lang.org/compiler/reviews.html) for why to put stuff in the PR message).

*[View changes since this review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/rust/147743/3f2a5921a451378f219edec28810f5f2f45cf1be..e314e04a3e804e93fe1642c8e45d287339c249fc)*

File: compiler/rustc_const_eval/src/util/alignment.rs (hunk 5 above)
Comment (RalfJung) [reply compiler/rustc_const_eval/src/util/alignment.rs]: "misaligned" is the term for "alignment violated". But this function can't know if alignment is truly violated, it only checks if alignment *may* be violated.

So maybe "unaligned" is a better term.

File: tests/ui/binding/issue-53114-safety-checks.stderr [hunk 6]
```diff
@@ -4,7 +4,7 @@ error[E0793]: reference to packed field is unaligned
 LL |     let _ = &p.b;
    |             ^^^^
    |
-   = note: packed structs are only aligned by one byte, and many modern architectures penalize unaligned field accesses
+   = note: this field is only 1-byte aligned, but its type requires more alignment
```
Comment (RalfJung) [inline tests/ui/binding/issue-53114-safety-checks.stderr]: So if I have a `packed(8)` struct with a field whose type cannot be determined, the error will say
> this field is only 8-byte aligned, but its type requires more alignment

That's not correct though -- the type *may* require higher alignment, but we don't actually know that for sure.

File: compiler/rustc_mir_transform/messages.ftl (hunk 3 above)
Comment (RalfJung) [reply compiler/rustc_mir_transform/messages.ftl:73]: I'm actually happy to see that disappear -- no idea when or why it was added, but I don't see why it is relevant at all here. The most likely effect it has is to reinforce the common misconception that the alignment requirements in Rust arise because of hardware alignment requirements.

Comment (RalfJung) [reply compiler/rustc_mir_transform/messages.ftl:73]: Seems this was added in https://github.com/rust-lang/rust/pull/110973. This was supposedly meant to resolve https://github.com/rust-lang/rust/issues/110199 but https://github.com/rust-lang/rust/issues/110199 was about
> point out that #[packed] makes the struct itself have lower alignment

so still not sure why the part about penalizing unaligned accesses would be relevant.

Comment (RalfJung) [reply compiler/rustc_mir_transform/messages.ftl:73]: However, the new message arguably regresses talking about the struct type. So maybe this should say
> reference to field of packed struct is unaligned

(since arguably it's not the field that's packed, it's the struct)

> the struct is at most {$actual}-byte aligned, but the type of this field may require higher alignment

Comment (21aslade) [reply compiler/rustc_mir_transform/messages.ftl:73]: I initially removed "this struct" because it's ambiguous - in the expression `&a.b.c`, it could be either `a` or `b` that causes the unalignment. (It's also technically incorrect, because unions can also be packed.) 

I'm happy with this final message in spite of that though, so I'll go ahead and implement it.

Comment (RalfJung) [reply compiler/rustc_mir_transform/messages.ftl:73]: Deep inside `is_within_packed` we know the actual ADT this is talking about; this could be exposed to call `adt.descr()` instead of just saying "struct".

File: tests/ui/binding/issue-53114-safety-checks.stderr (hunk 6 above)
Comment (RalfJung) [reply tests/ui/binding/issue-53114-safety-checks.stderr]: > Should be good now. The message still says "only x-byte aligned" because the alignment reported here should always be the minimum alignment, not the maximum.

That sounds like this problem remains unresolved then?

Comment (RalfJung) [reply tests/ui/binding/issue-53114-safety-checks.stderr]: To make things concrete, consider:
("a packed(8) struct with a field whose type cannot be determined", as I said above)
```rust
#[repr(packed(8))]
struct Packed<T>(T);

fn do_thing<T>(x: &Packed<T>) {
    let _r = &x.0;
}
```
Your code will say something like
"this struct is only 8-aligned, but the type of this field requires higher alignment"

That's not correct though. `T` might be `u8`, in which case `Packed` is 1-aligned.

Comment (21aslade) [reply tests/ui/binding/issue-53114-safety-checks.stderr]: Oh, oops, I thought I had changed that. I'll fix that real quick. That final note refers to changing "at most x-byte aligned" to "only x-byte aligned", because it will always be at least x-byte aligned (but the concrete address may happen to be more aligned).

Comment (RalfJung) [reply tests/ui/binding/issue-53114-safety-checks.stderr]: >  it will always be at least x-byte aligned 

No, it won't. That's the entire point of my example. That's what I already said in the first comment in this thread.

Please don't resolve comments unless you're really sure they are resolved; when in doubt, leave them open and ask. It's a lot of overhead for the reviewer to try to catch incorrectly resolved discussions.

Comment (21aslade) [reply tests/ui/binding/issue-53114-safety-checks.stderr]: Oh, you're right. It's a different concern than the field requiring an unknown alignment, but that is correct. Sorry for making the change without discussing it, thanks for your patience!

File: compiler/rustc_mir_transform/messages.ftl [hunk 7]
```diff
@@ -69,8 +69,8 @@ mir_transform_tail_expr_local = {$is_generated_name ->
         *[false] `{$name}` calls a custom destructor
     }
 
-mir_transform_unaligned_packed_ref = reference to packed field is unaligned
-    .note = packed structs are only aligned by one byte, and many modern architectures penalize unaligned field accesses
+mir_transform_unaligned_packed_ref = reference to field of packed {$ty_descr} is unaligned
+    .note = this {$ty_descr} is at most {$align}-byte aligned, but the type of this field may require higher alignment
```
Comment (madsmtm) [inline compiler/rustc_mir_transform/messages.ftl]: Nit: Could you add a test that triggers this diagnostic with a union? Just to ensure that the `$ty_descr` we track is the correct one.

**Review by madsmtm — APPROVED** [review]
Looks good to me now, but since Ralf had input, I'll let him have the final say.
r? RalfJung

Feel free to r=me as well if you're happy with the message.

*[View changes since this review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/rust/147743/bd4a8004c2f3b73795cb4c03bf8e7634e4d89677..5e6ea434c70ba7ab72070941ec0870b7b23ce609)*

File: compiler/rustc_const_eval/src/util/alignment.rs [hunk 8]
```diff
@@ -30,31 +30,31 @@ where
...
-            true
+            // We cannot figure out the layout. Conservatively assume that this is unaligned.
+            debug!("unalignment({:?}) - unaligned", place);
+            Some((descr, pack))
         }
     }
 }
 
-pub fn is_within_packed<'tcx, L>(
+pub fn most_packed_projection<'tcx, L>(
```
Comment (RalfJung) [inline compiler/rustc_const_eval/src/util/alignment.rs:56]: Please add a comment explaining what "most packed" means.

File: compiler/rustc_const_eval/src/util/alignment.rs [hunk 9]
```diff
@@ -1,24 +1,24 @@
...
 use tracing::debug;
 
-/// Returns `true` if this place is allowed to be less aligned
-/// than its containing struct (because it is within a packed
-/// struct).
-pub fn is_disaligned<'tcx, L>(
+/// If the place may be less aligned than its type requires
+/// (because it is in a packed type), returns the AdtDef
+/// and packed alignment of its most-unaligned projection.
+pub fn unalignment<'tcx, L>(
```
Comment (RalfJung) [inline compiler/rustc_const_eval/src/util/alignment.rs]: Since we're changing the name anyway, maybe call this `place_unalignment`? Just "unalignment" is a bit non-descriptive IMO.

File: tests/ui/binding/issue-53114-safety-checks.stderr [hunk 10]
```diff
@@ -1,20 +1,20 @@
-error[E0793]: reference to packed field is unaligned
+error[E0793]: reference to field of packed struct is unaligned
   --> $DIR/issue-53114-safety-checks.rs:23:13
    |
 LL |     let _ = &p.b;
    |             ^^^^
    |
-   = note: packed structs are only aligned by one byte, and many modern architectures penalize unaligned field accesses
+   = note: this struct is at most 1-byte aligned, but the type of this field may require higher alignment
```
Comment (RalfJung) [inline tests/ui/binding/issue-53114-safety-checks.stderr]: Should we have a special case that drops the "at most" when the alignment is 1? It can't be less than 1, after all...

File: compiler/rustc_mir_transform/messages.ftl (hunk 7 above)
Comment (RalfJung) [reply compiler/rustc_mir_transform/messages.ftl]: Good idea.

**Comment by RalfJung** [comment]
Ah, that was the npm network issue.
@rustbot ready
@bors r+

File: tests/ui/packed/packed-union-borrow-element.stderr [hunk 11]
```diff
@@ -0,0 +1,23 @@
+error[E0793]: reference to field of packed struct is unaligned
+  --> $DIR/packed-union-borrow-element.rs:20:24
+   |
+LL |     let brw = unsafe { &bar.foo1.0 };
+   |                        ^^^^^^^^^^^
+   |
+   = note: this struct is 1-byte aligned, but the type of this field may require higher alignment
```
Comment (RalfJung) [inline tests/ui/packed/packed-union-borrow-element.stderr:7]: When there are multiple projections it is not clear which one it means... further improvements are possible here, e.g. by saying "the struct `Name` is 1-byte aligned". But that can be left to a future PR.
