### PR TITLE
More intra-doc links, add explicit exception list to linkchecker

### LINKED ISSUE #32553: Missing `Methods from Deref<Target={primitive}>` section in documentation for types in `#![no_std]` crates
The links to [`as_ptr`](https://doc.rust-lang.org/nightly/collections/string/struct.String.html#representation) and [`chars`](https://doc.rust-lang.org/nightly/collections/string/struct.String.html#utf-8) on the collection crates page of String are broken.

This is because they refer to methods of [`str`](https://doc.rust-lang.org/nightly/std/primitive.str.html) but link to the same page (`String`), relying on the [`Methods from Deref<Target=str>`](https://doc.rust-lang.org/nightly/std/string/struct.String.html#deref-methods) section which is missing for some reason (seems to apply to the entire [`collections`](https://doc.rust-lang.org/nightly/collections/index.html) crate).

### PR DESCRIPTION
**Pull request by Manishearth**
Fixes the broken links behind #32553

Progress on #32130 and #32129 except for a small number of links. Instead of whitelisting entire files, I've changed the code to whitelist specific links in specific files, and added a comment requesting people explain the reasons they add exceptions. I'm not sure if we should close those issues in favor of the already filed intra-doc link issues.

### CODE REVIEW

**Comment by ollie27** [comment]
> Fixes #32553

This won't actually fix #32553 because it is about the missing [`Methods from Deref<Target=str>`](https://doc.rust-lang.org/nightly/std/string/struct.String.html#deref-methods) section on the [`alloc::string::String`](https://doc.rust-lang.org/nightly/alloc/string/struct.String.html) page. This may be able to fix the broken links that were caused by that though.

**Comment by Manishearth** [comment]
@ollie27 oh heh I just copied the issue number from the source when I deleted the linkcheck line

File: src/liballoc/string.rs [hunk 1]
```diff
@@ -67,12 +63,12 @@ use crate::vec::Vec;
 /// contents of the string. It has a close relationship with its borrowed
 /// counterpart, the primitive [`str`].
 ///
-/// [`str`]: ../../std/primitive.str.html
-///
 /// # Examples
 ///
 /// You can create a `String` from a literal string with [`String::from`]:
 ///
+/// [`String::from`]: From::from
```
Comment (jyn514) [inline src/liballoc/string.rs:70]: Let's link to the relevant impl, not just the trait (this is `&'_ str`)

```suggestion
/// [`String::from`]: #impl-From<%26%27_%20str>
```

File: src/liballoc/string.rs [hunk 2]
```diff
@@ -1567,9 +1534,6 @@ impl String {
     /// Panics if the starting point or end point do not lie on a [`char`]
     /// boundary, or if they're out of bounds.
     ///
-    /// [`char`]: ../../std/primitive.char.html
-    /// [`Vec::splice`]: ../../std/vec/struct.Vec.html#method.splice
```
Comment (jyn514) [inline src/liballoc/string.rs:1571]: nit: before you linked to core::vec::Vec, but now this uses the imported type (implicitly, through [`Vec::splice`] in the text). Can you use them consistently?

File: src/libstd/collections/hash/map.rs [hunk 3]
```diff
@@ -148,14 +148,11 @@ use crate::sys;
...
-/// [`Hash`]: ../../std/hash/trait.Hash.html
-/// [`PartialEq`]: ../../std/cmp/trait.PartialEq.html
-/// [`RefCell`]: ../../std/cell/struct.RefCell.html
-/// [`Cell`]: ../../std/cell/struct.Cell.html
-/// [`default`]: #method.default
-/// [`with_hasher`]: #method.with_hasher
-/// [`with_capacity_and_hasher`]: #method.with_capacity_and_hasher
+/// [`RefCell`]: crate::cell::RefCell
+/// [`Cell`]: crate::cell::Cell
+/// [`default`]: Default::default
```
Comment (jyn514) [inline src/libstd/collections/hash/map.rs:153]: This now goes to the trait page, instead of the list of implementations. I know `HashMap::default` doesn't currently work, can we keep `#method.default` until then? We don't have the ambiguity of String::from because there can only be one Default impl.

File: src/libstd/io/mod.rs [hunk 4]
```diff
@@ -1480,19 +1449,16 @@ pub trait Write {
     /// encountered.
     ///
     /// This method is primarily used to interface with the
-    /// [`format_args!`][formatargs] macro, but it is rare that this should
-    /// explicitly be called. The [`write!`][write] macro should be favored to
+    /// [`format_args!()`] macro, but it is rare that this should
+    /// explicitly be called. The [`write!()`][write] macro should be favored to
```
Comment (jyn514) [inline src/libstd/io/mod.rs:1453]:
```suggestion
    /// explicitly be called. The [`write!()`] macro should be favored to
```

File: src/tools/linkchecker/main.rs [hunk 5]
```diff
@@ -23,6 +23,31 @@ use std::rc::Rc;
 
 use crate::Redirect::*;
 
+// Add linkcheck exceptions here
+// If at all possible you should use intra-doc links to avoid linkcheck issues. These
+// are cases where that does not work
+const LINKCHECK_EXCEPTIONS: &[(&str, &[&str])] = &[
+    // These are methods on slice, and `Self` does not work on primitive impls
+    // in intra-doc links (intra-doc links are weird)
+    // https://github.com/rust-lang/rust/issues/62834 is necessary to be
```
Comment (jyn514) [inline src/tools/linkchecker/main.rs:32]: I think you meant the issue on primitive types.
```suggestion
    // https://github.com/rust-lang/rust/issues/63351 is necessary to be
```

File: src/tools/linkchecker/main.rs [hunk 6]
```diff
@@ -23,6 +23,31 @@ use std::rc::Rc;
 
 use crate::Redirect::*;
 
+// Add linkcheck exceptions here
+// If at all possible you should use intra-doc links to avoid linkcheck issues. These
+// are cases where that does not work
+const LINKCHECK_EXCEPTIONS: &[(&str, &[&str])] = &[
+    // These are methods on slice, and `Self` does not work on primitive impls
+    // in intra-doc links (intra-doc links are weird)
```
Comment (jyn514) [inline src/tools/linkchecker/main.rs:31]: 😆

File: src/tools/linkchecker/main.rs [hunk 7]
```diff
@@ -23,6 +23,31 @@ use std::rc::Rc;
 
 use crate::Redirect::*;
 
+// Add linkcheck exceptions here
+// If at all possible you should use intra-doc links to avoid linkcheck issues. These
+// are cases where that does not work
+const LINKCHECK_EXCEPTIONS: &[(&str, &[&str])] = &[
```
Comment (jyn514) [inline src/tools/linkchecker/main.rs:29]:
```suggestion
// [(generated_documentation_page, &[broken_links])]
const LINKCHECK_EXCEPTIONS: &[(&str, &[&str])] = &[
```

**Review by jyn514 — COMMENTED** [review]
Thanks for working on this!

File: src/liballoc/string.rs (hunk 1 above)
Comment (Manishearth) [reply src/liballoc/string.rs:70]: the exact impl doesn't have special docs and the point is to _reduce_ the direct links :)

File: src/liballoc/string.rs (hunk 2 above)
Comment (Manishearth) [reply src/liballoc/string.rs:1571]: It doesn't matter? They'll link to the same thing

File: src/libstd/collections/hash/map.rs (hunk 3 above)
Comment (Manishearth) [reply src/libstd/collections/hash/map.rs:153]: IMO the trait page is fine but I'd rather get rid of the #s and have links work over having them link to the trait impl instead of the trait. I don't see a difference in utility there

File: src/tools/linkchecker/main.rs (hunk 6 above)
Comment (Manishearth) [reply src/tools/linkchecker/main.rs:31]: I actually meant to say "primitive impls are weird" lol

File: src/libstd/collections/hash/map.rs (hunk 3 above)
Comment (jyn514) [reply src/libstd/collections/hash/map.rs:153]: The difference is that going to the trait takes you to a new page and away from the docs you were originally reading. `#method.default` loads  basically instantaneously.

File: src/liballoc/string.rs (hunk 2 above)
Comment (jyn514) [reply src/liballoc/string.rs:1571]: Ok, nbd then.

File: src/liballoc/string.rs (hunk 1 above)
Comment (jyn514) [reply src/liballoc/string.rs:70]: I think linking to the type is helpful though. It's not clear that 'literal string' means `&'_ str`, especially to beginners.

Also, same comment as below about fragments loading faster than different pages.

File: src/tools/linkchecker/main.rs (hunk 5 above)
Comment (Manishearth) [reply src/tools/linkchecker/main.rs:33]: oh, in my mind the generic issue is also what blocks slice, but your thing works

File: src/liballoc/string.rs (hunk 1 above)
Comment (Manishearth) [reply src/liballoc/string.rs:70]: We can just fix that with an `&str` link :)

**Comment by jyn514** [comment]
@bors r+ rollup=iffy

The changes to linkchecker will mean any PR with broken links would break during rollup but not in a check build.
