### PR TITLE
resolve: fix the visibility of extern crates

### LINKED ISSUE #26775: `extern crate` is always treated as `pub` within the crate, but is not visible outside it; `pub extern crate` makes no difference
Two examples:

```rust
#![feature(core)]
#![crate_type = "lib"]
pub extern crate core;
```

That is accepted but `core` cannot be accessed from outside the crate.

```rust
#![feature(core)]
#![crate_type = "lib"]

mod foo {
    extern crate core;
    // behaves identically
    // pub extern crate core;
}

pub use foo::core;
```

That *is* accepted and reexports `core`.

In other words, `extern crate` is always public to other modules, but can never be made public to other crates.

There are no tests for `pub extern crate` so I suspect this is not intentional.

### PR DESCRIPTION
**Pull request by jseyfried**
This PR changes the visibility of extern crate declarations to match that of items (fixes #26775).
To avoid breakage, the PR makes it a `public_in_private` lint to reexport a private extern crate, and it adds the lint `inaccessible_extern_crate` for uses of an inaccessible extern crate.

The lints can be avoided by making the appropriate `extern crate` declaration public.

### CODE REVIEW

**Comment by jseyfried** [comment]
cc @nikomatsakis @petrochenkov

**Comment by petrochenkov** [comment]
>except that it allows private extern crate declarations to be re-exported. This exception considerably reduces breakage

It doesn't necessarily have to be a hard error immediately, you can mark such reexports with `private_in_public` warning (see https://github.com/rust-lang/rust/blob/master/src/librustc_resolve/resolve_imports.rs#L504 for example).
It's not like this warning is going to become an error any time soon.

**Comment by jseyfried** [comment]
@petrochenkov Good point.

**Comment by nrc** [comment]
cc @rust-lang/lang

File: src/librustc_resolve/resolve_imports.rs [hunk 1]
```diff
@@ -491,12 +491,22 @@ impl<'a, 'b:'a, 'tcx:'b> ImportResolver<'a, 'b, 'tcx> {
...
-                    let msg = format!("`{}` is private, and cannot be reexported", source);
-                    let note_msg =
-                        format!("Consider declaring type or module `{}` with `pub`", source);
-                    struct_span_err!(self.resolver.session, directive.span, E0365, "{}", &msg)
-                        .span_note(directive.span, &note_msg)
-                        .emit();
+                    if name_binding.is_extern_crate() {
+                        let msg = format!("extern crate `{}` is private, and cannot be reexported \
+                                           (error E0364), consider declaring with `pub`",
+                                           source);
```
Comment (nrc) [inline src/librustc_resolve/resolve_imports.rs]: can you move the `consider...` bit to a note please

Comment (nrc) [inline src/librustc_resolve/resolve_imports.rs]: oh wait, you can't it's a lint, nvm

File: src/test/compile-fail/extern-crate-visibility.rs [hunk 2]
```diff
@@ -0,0 +1,23 @@
...
+//
+// Licensed under the Apache License, Version 2.0 <LICENSE-APACHE or
+// http://www.apache.org/licenses/LICENSE-2.0> or the MIT license
+// <LICENSE-MIT or http://opensource.org/licenses/MIT>, at your
+// option. This file may not be copied, modified, or distributed
+// except according to those terms.
+
+mod foo {
+    extern crate core;
+    pub use self::core as reexported_core; // Check that private extern crates can be reexported
```
Comment (nrc) [inline src/test/compile-fail/extern-crate-visibility.rs]: this should be a warning right?

**Comment by nrc** [comment]
The PR lgtm. I'll wait for a crater run and for the lang team to see this before giving r+ though.

**Comment by aturon** [comment]
Seems to match our previous decision on this question, so LGTM as well.

File: src/test/compile-fail/extern-crate-visibility.rs (hunk 2 above)
Comment (petrochenkov) [inline src/test/compile-fail/extern-crate-visibility.rs]: The `private_in_public` warning is reported during lint pass, much later than resolve.
It looks like it's tested separately in `private-variant-and-crate-reexport.rs`.

File: src/librustc/lib.rs [hunk 3]
```diff
@@ -68,6 +68,7 @@ extern crate serialize as rustc_serialize; // used by deriving
 #[cfg(test)]
 extern crate test;
 
+#[allow(private_in_public)]
```
Comment (petrochenkov) [inline src/librustc/lib.rs]: Is `pub extern crate` very buggy? I think it can be used here instead of suppressing the warning. It will report the "`pub extern crate` does not work as expected" warning during `stage0`, but that's ok.

Comment (jseyfried) [inline src/librustc/lib.rs]: Good point, for some reason I thought that the warnings weren't ok.
`pub extern crate` works fine except that it are not visible to other crates right now. That doesn't appear to be a problem for stage0 though.

**Comment by jseyfried** [comment]
rebased

**Comment by jseyfried** [comment]
This also closes #22146.

**Comment by nrc** [comment]
@brson or @alexcrichton could we get a crater run for this PR please?

**Comment by alexcrichton** [comment]
I've kicked off a crater run

**Comment by alexcrichton** [comment]
Crater reports [12 regressions](https://gist.github.com/alexcrichton/78cf7d4740391546e2d5) unfortunately all of which look legitimate :(

Although I didn't check to see if they were duplicates of one another

**Comment by jseyfried** [comment]
Of there 12 regressions, one was from a public in private warning with `#[deny(public_in_private)]` and five were unique.
The above commit makes it a warning to use an inaccessible extern crate instead of a hard error.

**Comment by nrc** [comment]
cc @rust-lang/lang do we want to make this change with a warning cycle or leave it as a warning forever or just leave it broken? I reckon warning cycle.

**Comment by jseyfried** [comment]
rebased

**Comment by aturon** [comment]
+1 for warning cycle.

**Comment by nikomatsakis** [comment]
If we're going to use a warning cycle -- which seems correct -- we should make sure we add the lint to the "forwards incompatibility" set.

**Comment by jseyfried** [comment]
@nikomatsakis makes sense -- I amended last commit to emit a new future incompatible lint.

**Comment by jseyfried** [comment]
@nikomatsakis makes sense -- I amended last commit to emit a new future incompatible lint.

**Comment by jseyfried** [comment]
rebased

File: src/librustc_resolve/resolve_imports.rs [hunk 4]
```diff
@@ -424,12 +424,22 @@ impl<'a, 'b:'a, 'tcx:'b> ImportResolver<'a, 'b, 'tcx> {
...
+                        self.resolver.session.add_lint(lint::builtin::PRIVATE_IN_PUBLIC,
+                                                       directive.id,
+                                                       directive.span,
+                                                       msg);
+                    } else {
+                        let msg = format!("`{}` is private, and cannot be reexported", source);
+                        let note_msg =
+                            format!("Consider declaring type or module `{}` with `pub`", source);
```
Comment (nikomatsakis) [inline src/librustc_resolve/resolve_imports.rs]: Nit: should be "consider", not "Consider"

**Comment by nikomatsakis** [comment]
r=me modulo nit

**Comment by jseyfried** [comment]
@nikomatsakis I fixed the nit

**Comment by jseyfried** [comment]
rebased

**Comment by jseyfried** [comment]
rebased

**Comment by nikomatsakis** [comment]
Huh: 

```
Zombie process: "\Device\HarddiskVolume1\dojob.exe"
make: *** No rule to make target 'i686-pc-windows-gnu/test/run-make/issue-26995-2-T-i686-pc-windows-gnu-H-i686-pc-windows-gnu.ok', needed by 'tmp/check-stage2-T-i686-pc-windows-gnu-H-i686-pc-windows-gnu-rmake.ok'.  Stop.
program finished with exit code 2
```

**Comment by jseyfried** [comment]
Looks like #31793 is failing for the same reason

**Comment by alexcrichton** [comment]
@bors: retry

ah just a dirty buildbot
