### PR TITLE
std: Don't assume thread::current() works on panic

### LINKED ISSUE #24313: Panicking in the drop function of a struct that is stored in a thread local causes a stack overflow
When thread locals are dropped, the thread is not valid anymore so accessing `thread::current()` will panic, however, `begin_unwind` calls `thread::current()` which will cause an infinite loop and a stack overflow.

The follow example has been tested to crash with an out of memory error on OS X:

```rust
use std::thread;

struct Handle {
    i: i32,
}

impl Drop for Handle {
    fn drop(&mut self) {
        panic!("BOOM");
    }
}

thread_local!(static HANDLE: Handle = new_handle());

fn new_handle() -> Handle {
    Handle { i: 0 }
}

pub fn main() {
    let _ = thread::scoped(|| {
        HANDLE.with(|h| {
            println!("HANDLE: {}", h.i);
        });
    });
}
```

cc @alexcrichton

### PR DESCRIPTION
**Pull request by alexcrichton**
Inspecting the current thread's info may not always work due to the TLS value
having been destroyed (or is actively being destroyed). The code for printing
a panic message assumed, however, that it could acquire the thread's name
through this method.

Instead this commit propagates the `Option` outwards to allow the
`std::panicking` module to handle the case where the current thread isn't
present.

While it solves the immediate issue of #24313, there is still another underlying
issue of panicking destructors in thread locals will abort the process.

Closes #24313

### CODE REVIEW

File: src/libstd/thread/local.rs [hunk 1]
```diff
@@ -18,7 +18,6 @@ use cell::UnsafeCell;
 
 // Sure wish we had macro hygiene, no?
 #[doc(hidden)]
-#[unstable(feature = "thread_local_internals")]
```
Comment (sfackler) [inline src/libstd/thread/local.rs]: Were these accidentally stripped?

**Comment by alexcrichton** [comment]
I've opened #24479 about panicking destructors in TLS aborting the process, which I believe is a separable issue.

File: src/libstd/thread/local.rs (hunk 1 above)
Comment (alexcrichton) [inline src/libstd/thread/local.rs]: The module at the top-level has an `#[unstable]` attribute which everything inside inherits from by default. (it was intentional)
