### PR TITLE
 rustc_codegen_ssa: fix range check in codegen_get_discr.

### LINKED ISSUE #61696: Soundness hole in pattern matching on enums with an uninhabited variant
Playground link: https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=7a8a62d7a736d6bd54273422da29d7af

<details>
<summary> Click to see the example code from above link </summary>

```rust
#[derive(Debug)]
enum A {
    B(B),
    C(C),
    A1,
    A2,
}

#[derive(Debug)]
enum B {
    B1,
    B2,
    B3,
    B4,
    B5,
}

#[derive(Debug)]
enum C {}

fn main() {
    let a = A::B(B::B5);
    match a {
        A::B(_) => println!("success"),
        _ => println!("error: {:?}", a),
    }
}
```

</details>

Expected output: `success`

Actual output:
```
timeout: the monitored command dumped core
/root/entrypoint.sh: line 8:     7 Illegal instruction     timeout --signal=KILL ${timeout} "$@"
```

Running the above code on both Rust stable and nightly on my machine returns `illegal hardware instruction (core dumped)` with some number different on each run prefixing the output.

Some experimentations:
* Implementing variants for enum `C` solves this issue.
* Remove variants `A1` and `A2` solves this issue.
* Use any variant of `B` other than `B5` works.

I assume this is a bug in the compiler?

### PR DESCRIPTION
**Pull request by eddyb**
Fixes #61696, see https://github.com/rust-lang/rust/issues/61696#issuecomment-505473018 for more details.

In short, I had wanted to use `x - a <= b - a` to check whether `x` is in `a..=b` (as it's 1 comparison instead of 2 *and* `b - a` is guaranteed to fit in the same data type, while `b` itself might not), but I ended up with `x - a + c <= b - a + c` instead, because `x - a + c` was the final value needed.

That latter comparison is equivalent to checking that `x` is in `(a - c)..=b`, i.e. it also includes `(a - c)..a`, not just `a..=b`, so if `c` is not `0`, it will cause false positives.

This presented itself as the non-niche ("dataful") variant sometimes being treated like a niche variant, in the presence of uninhabited variants (which made `c`, aka the index of the first niche variant, arbitrarily large).

r? @nagisa, @rkruppe or @oli-obk

### CODE REVIEW

File: src/librustc_codegen_ssa/mir/place.rs [hunk 1]
```diff
@@ -240,38 +243,49 @@ impl<'a, 'tcx, V: CodegenObject> PlaceRef<'tcx, V> {
...
             layout::DiscriminantKind::Niche {
                 dataful_variant,
                 ref niche_variants,
                 niche_start,
             } => {
-                let niche_llty = bx.cx().immediate_backend_type(discr.layout);
-                if niche_variants.start() == niche_variants.end() {
+                let niche_llty = bx.cx().immediate_backend_type(encoded_discr.layout);
+                let encoded_discr = encoded_discr.immediate();
+                let (is_niche, niche_discr) = if niche_variants.start() == niche_variants.end() {
```
Comment (pnkfelix) [inline src/librustc_codegen_ssa/mir/place.rs]: Personally, I find the use of a tuple pretty hard to read in code like this, because of how far away the tuple-constructing expressions are.

Did you consider doing:

```rust
let is_niche;
let niche_discr;
if  ... { ... is_niche = A; niche_discr = B; } else { ... is_niche = C; niche_discr = D; }
```
?

Comment (eddyb) [reply src/librustc_codegen_ssa/mir/place.rs]: That's fair, but I don't think the second commit keeps a tuple anyway.

File: src/librustc_codegen_ssa/mir/place.rs [hunk 2]
```diff
@@ -250,37 +250,61 @@ impl<'a, 'tcx, V: CodegenObject> PlaceRef<'tcx, V> {
...
-                let (is_niche, niche_discr) = if niche_variants.start() == niche_variants.end() {
-                    // Special case for when we can use a simple equality check,
-                    // which covers null pointers, and needs simpler codegen.
-                    // FIXME(eddyb): check the actual primitive type here.
-                    let encoded_niche = if niche_start == 0 {
-                        // HACK(eddyb): using `c_null` as it works on all types.
+
+                // We first compute the "relative discriminant" (wrt `niche_variants`),
+                // that is, if `n = niche_variants.end() - niche_variants.start()`,
+                // we remap (maybe wrap-around!) `niche_start..=niche_start + n`
```
Comment (pnkfelix) [inline src/librustc_codegen_ssa/mir/place.rs]: nit: the wording here is slightly awkward, because I read the phrase "wrap-around" as a verb first rather than an adjective, and so  I initially interpret "we remap (maybe wrap-around!) `niche_start..=niche_start + n` as meaning "the remapping we are doing here might wrap-around").

Its role as an adjective becomes clearer after one finishes reading the whole sentence, but I would prefer if you maybe said:

"we remap (the potentially wrapping-around!) `niche_start..=niche_start + n`"
or maybe
"we remap (the potentially overflowing!) `niche_start..=niche_start + n`"

Comment (eddyb) [reply src/librustc_codegen_ssa/mir/place.rs]: "wraparound range" is a specific thing that validity ranges are (e.g. `2..=0` includes everything except `1`).

Maybe this would make more sense if we had a special type for them, but then the `a..=b` syntax wouldn't work...

I think I tried to be terse here to make things fit but I don't think I really have to, so I can reword it a bit.

File: src/librustc_codegen_ssa/mir/place.rs [hunk 3]
```diff
@@ -250,37 +250,61 @@ impl<'a, 'tcx, V: CodegenObject> PlaceRef<'tcx, V> {
...
                         bx.cx().const_null(niche_llty)
                     } else {
-                        bx.cx().const_uint_big(niche_llty, niche_start)
+                        bx.cx().const_uint(niche_llty, relative_max as u64)
+                    };
+                    bx.icmp(IntPredicate::IntULE, relative_discr, relative_max)
+                };
+
+                // NOTE(eddyb) this addition needs to be performed on the final
+                // type, in case the niche itself can't represent all variant
```
Comment (pnkfelix) [inline src/librustc_codegen_ssa/mir/place.rs]: can you add a test for this case where the niche itself cannot represent all the variant indices it needs to?

(I believe I understand what you've outlined here, but if I understand this diff correctly, we were not handling that case before this PR, right?)

Comment (eddyb) [reply src/librustc_codegen_ssa/mir/place.rs]: Will do, probably by generating like 300 variants from a script (most of them uninhabited).

File: src/librustc_codegen_ssa/mir/place.rs (hunk 1 above)
Comment (pnkfelix) [reply src/librustc_codegen_ssa/mir/place.rs]: Ah you are right

File: src/librustc_codegen_ssa/mir/place.rs (hunk 2 above)
Comment (pnkfelix) [reply src/librustc_codegen_ssa/mir/place.rs]: Ah okay I didn't know the adjective use here was a specific term-of-art

**Comment by pnkfelix** [comment]
This looks good, r=me once the test has been added (for the case where the niche would not be able to represent the uninhabited variants if they were actually assigned distinct discriminant values).

File: src/librustc_codegen_ssa/mir/place.rs (hunk 2 above)
Comment (eddyb) [reply src/librustc_codegen_ssa/mir/place.rs]: I wish it was more of a term of art tbh, right now it's kinda niche (pun not intended).

File: src/librustc_codegen_ssa/mir/place.rs [hunk 4]
```diff
@@ -240,38 +243,73 @@ impl<'a, 'tcx, V: CodegenObject> PlaceRef<'tcx, V> {
...
+                let is_niche = {
+                    let relative_max = if relative_max == 0 {
+                        // Avoid calling `const_uint`, which wouldn't work for pointers.
+                        // FIXME(eddyb) check the actual primitive type here.
                         bx.cx().const_null(niche_llty)
                     } else {
-                        bx.cx().const_uint_big(niche_llty, niche_start)
+                        bx.cx().const_uint(niche_llty, relative_max as u64)
+                    };
+                    bx.icmp(IntPredicate::IntULE, relative_discr, relative_max)
```
Comment (nagisa) [inline src/librustc_codegen_ssa/mir/place.rs]: If `relative_discr` is re-projected to `0..=n`, doesn’t this actually compute `is_proper_variant` rather than `is_niche`? That is, I would expect any niche discriminant to be in `n+1..niche_llty::max_value()` and this appears to check `0..=n <= n`.

This appears to be reinforced by the `bx.select` below, which selects `niche_discr` when `is_niche == 0`.

Comment (eddyb) [reply src/librustc_codegen_ssa/mir/place.rs]: `select` is `c ? a : b` I'm pretty sure.

In `0..=n`, `n` is the number of niche(-using) variants, i.e. `relative_discr == 0` is the first niche-using variant, and it goes up from there.

File: src/test/run-pass/issues/issue-61696.rs [hunk 5]
```diff
@@ -0,0 +1,14 @@
+pub enum Infallable {}
```
Comment (Centril) [inline src/test/run-pass/issues/issue-61696.rs]:
```suggestion
pub enum Infallible {}
```

File: src/test/run-pass/issues/issue-61696.rs [hunk 6]
```diff
@@ -0,0 +1,14 @@
...
+
+pub enum E1 {
+    V1 { f: bool },
+    V2 { f: Infallable },
```
Comment (Centril) [inline src/test/run-pass/issues/issue-61696.rs]:
```suggestion
    V2 { f: Infallible },
```

**Review by Centril — COMMENTED** [review]
nits (typos)
