### PR TITLE
Prevent name collisions with internal implementation details

### LINKED ISSUE #144940: panic about linkage `external` and static variables `_rust_extern_with_linkage_*`
### Code
This is simplified from https://github.com/rust-lang/rust/blob/master/tests/ui/linkage-attr/linkage-detect-local-generated-name-collision.rs

It's normal to report errors ``error: symbol `collision` is already defined`` if `_rust_extern_with_linkage_collision ` before the main.

However once I moved `_rust_extern_with_linkage_collision` after the main function, I got a panic.

[Playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2015&gist=903283235e2cb0f6daef874a7aa49752)

```Rust
#![feature(linkage)]

unsafe extern "C" {
    #[linkage = "external"]
    #[no_mangle]
    pub static collision: *const i32;
}

// #[no_mangle]
// pub static _rust_extern_with_linkage_collision: i32 = 0;  // original code, before main.

pub fn main() {
    unsafe {
        println!("{:p}", &collision);
    }
}

#[no_mangle]
pub static _rust_extern_with_linkage_collision: i32 = 0;
```

### Meta

`rustc --version --verbose`:
```
rustc 1.91.0-nightly (0060d5a2a 2025-08-04)
binary: rustc
commit-hash: 0060d5a2a8a86a31f6299311fe64b1d755a91c4f
commit-date: 2025-08-04
host: x86_64-pc-windows-msvc
release: 1.91.0-nightly
LLVM version: 20.1.8
```

### Error output

```
warning: `#[no_mangle]` has no effect on a foreign static
 --> .\src\example.rs:5:5
  |
5 |     #[no_mangle]
  |     ^^^^^^^^^^^^ help: remove this attribute
6 |     pub static collision: *const i32;
  |     --------------------------------- foreign static
  |
  = warning: this was previously accepted by the compiler but is being phased out; it will become a hard error in a future release!
  = note: symbol names in extern blocks are not mangled
  = note: `#[warn(unused_attributes)]` on by default

thread 'rustc' panicked at compiler\rustc_codegen_llvm\src\consts.rs:399:9:
assertion failed: llvm::LLVMGetInitializer(self.instances.borrow().get(&Instance::mono(self.tcx,
                        def_id)).unwrap()).is_none()
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/0060d5a2a8a86a31f6299311fe64b1d755a91c4f/library\std\src\panicking.rs:697
   1: core::panicking::panic_fmt
             at /rustc/0060d5a2a8a86a31f6299311fe64b1d755a91c4f/library\core\src\panicking.rs:75
   2: core::panicking::panic
             at /rustc/0060d5a2a8a86a31f6299311fe64b1d755a91c4f/library\core\src\panicking.rs:145
   3: <rustc_codegen_llvm::context::GenericCx<rustc_codegen_llvm::context::FullCx> as rustc_codegen_ssa::traits::statics::StaticCodegenMethods>::codegen_static
   4: <rustc_target::callconv::FnAbi<rustc_middle::ty::Ty> as rustc_codegen_llvm::abi::FnAbiLlvmExt>::apply_attrs_callsite
   5: <rustc_codegen_llvm::LlvmCodegenBackend as rustc_codegen_ssa::traits::backend::ExtraBackendMethods>::compile_codegen_unit
   6: std::vector<std::basic_string<char,std::char_traits<char>,std::allocator<char> >,std::allocator<std::basic_string<char,std::char_traits<char>,std::allocator<char> > > >::_Construct_n<std::basic_string<char,std::char_traits<char>,std::allocator<char> > * __
   7: <rustc_codegen_llvm::LlvmCodegenBackend as rustc_codegen_ssa::traits::backend::CodegenBackend>::codegen_crate
   8: <rustc_interface::queries::Linker>::codegen_and_build_linker
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

</p>
</details>

### PR DESCRIPTION
**Pull request by bjorn3**
The implementation of the linkage attribute inside extern blocks defines symbols starting with _rust_extern_with_linkage_. If someone tries to also define this symbol you will get a symbol conflict or even an ICE. By adding an unpredictable component to the symbol name, this becomes less of an issue.

Spawned from the discussion at [#t-compiler > About static variables &#96;_rust_extern_with_linkage_&#42;&#96;](https://rust-lang.zulipchat.com/#narrow/channel/131828-t-compiler/topic/About.20static.20variables.20.60_rust_extern_with_linkage_*.60) cc @ywxt

Fixes https://github.com/rust-lang/rust/issues/144940

### CODE REVIEW

**Comment by ywxt** [comment]
Issue: #144940

Thanks for your great work.

File: tests/ui/linkage-attr/linkage-detect-extern-generated-name-collision.rs [hunk 1]
```diff
@@ -1,26 +0,0 @@
-// rust-lang/rust#61232: We used to ICE when trying to detect a
```
Comment (petrochenkov) [inline tests/ui/linkage-attr/linkage-detect-extern-generated-name-collision.rs:1]: Any specific reasons to remove the tests?

File: compiler/rustc_codegen_cranelift/src/constant.rs [hunk 2]
```diff
@@ -310,7 +310,10 @@ fn data_id_for_static(
         // `extern_with_linkage_foo` will instead be initialized to
         // zero.
 
-        let ref_name = format!("_rust_extern_with_linkage_{}", symbol_name);
+        let ref_name = format!(
+            "_rust_extern_with_linkage_{:x}_{symbol_name}",
+            tcx.stable_crate_id(LOCAL_CRATE).as_u64()
```
Comment (petrochenkov) [inline compiler/rustc_codegen_cranelift/src/constant.rs]: I have some vague memory of performance fluctuations caused by symbol name (?) lengths or something similar randomly changing after small changes in the crate.
Perhaps format it with a fixed length?

Also `StableCrateId` itself seems to have a `fmt::LowerHex` impl, so no need to convert to u64.

File: tests/ui/linkage-attr/linkage-detect-extern-generated-name-collision.rs (hunk 1 above)
Comment (bjorn3) [reply tests/ui/linkage-attr/linkage-detect-extern-generated-name-collision.rs:1]: There is no way to force a collision anymore in the test that works across rustc versions.

File: compiler/rustc_codegen_cranelift/src/constant.rs (hunk 2 above)
Comment (bjorn3) [reply compiler/rustc_codegen_cranelift/src/constant.rs]: Added fixed width formatting and removed the `.as_u64()` call.
