### PR TITLE
Don't leak sysroot crates through dependencies

### LINKED ISSUE #147966: regression: ICE no resolution found for import
- https://crater-reports.s3.amazonaws.com/beta-1.91-2/beta-2025-09-21/gh/gruberb.ohttp-gateway/log.txt
- https://crater-reports.s3.amazonaws.com/beta-1.91-3/beta-2025-09-21/reg/jitash-bdk-0.28.1/log.txt

```
[INFO] [stdout] error: internal compiler error: no resolution for an import
[INFO] [stdout]  --> tests/config_handler_tests.rs:1:5
[INFO] [stdout]   |
[INFO] [stdout] 1 | use hyper::StatusCode;
[INFO] [stdout]   |     ^^^^^^^^^^^^^^^^^
[INFO] [stdout]   |
[INFO] [stdout] note: delayed at compiler/rustc_ast_lowering/src/lib.rs:760:24
```

### PR DESCRIPTION
**Pull request by bjorn3**
Previously if a dependency of the current crate depended on a sysroot crate, then `extern crate` would in the current crate would pick the first loaded version of said sysroot crate even in case of an ambiguity. This is surprising and brittle. For `-Ldependency=` we already blocked this since rust-lang/rust#110229, but the fix didn't account for sysroot crates.

Should fix https://github.com/rust-lang/rust/issues/147966

### CODE REVIEW

File: compiler/rustc_metadata/src/creader.rs [hunk 1]
```diff
@@ -551,37 +550,19 @@ impl CStore {
...
-                return Some(cnum);
-            } else {
-                debug!(
-                    "failed to load existing crate {}; kind {:?} did not match prev_kind {:?}",
-                    name, kind, prev_kind
-                );
-            }
+            // While the crate name matched, no --extern crate_name=path matched. It is possible
+            // that we have already loaded the target crate, but if that happens CStore::load will
+            // indicate so and we gracefully handle this, just potentially wasting a bit of time.
```
Comment (petrochenkov) [inline compiler/rustc_metadata/src/creader.rs]: So technically we could eliminate `existing_match` entirely, and it wouldn't change the logic, only potentially introduce perf regressions?

If that's the case, then why do the new ambiguity errors appear?

Also, if that's the case, I wonder if we actually get any perf gains from the `if let Some(entry) = externs.get(name.as_str()) {` logic above.
That logic is also able to hide legitimate ambiguity errors - https://github.com/rust-lang/rust/issues/147966#issuecomment-3444198198.

File: compiler/rustc_metadata/src/locator.rs [hunk 2]
```diff
@@ -798,21 +798,21 @@ impl<'a> CrateLocator<'a> {
             };
             if file.starts_with("lib") {
                 if file.ends_with(".rlib") {
-                    rlibs.insert(loc_canon.clone(), PathKind::ExternFlag);
```
Comment (petrochenkov) [inline compiler/rustc_metadata/src/locator.rs:801]: Looks like `PathKind::ExternFlag` is no longer used anywhere.

File: compiler/rustc_metadata/src/creader.rs (hunk 1 above)
Comment (bjorn3) [reply compiler/rustc_metadata/src/creader.rs]: > If that's the case, then why do the new ambiguity errors appear?

Because the old `existing_match` accidentally resolved sysroot ambiguities in favor of the first loaded crate with the given name. The point of this PR is to remove this accidental ambiguity resolution.

> So technically we could eliminate existing_match entirely, and it wouldn't change the logic, only potentially introduce perf regressions?

If `existing_match` is bug free, then yes it should merely be a perf optimization.

Comment (bjorn3) [reply compiler/rustc_metadata/src/creader.rs]: > That logic is also able to hide legitimate ambiguity errors - https://github.com/rust-lang/rust/issues/147966#issuecomment-3444198198.

Ignoring speculatively loaded crates in `existing_match` when no crate hash is given would work I presume?

Comment (petrochenkov) [reply compiler/rustc_metadata/src/creader.rs]: > > That logic is also able to hide legitimate ambiguity errors - [#147966 (comment)](https://github.com/rust-lang/rust/issues/147966#issuecomment-3444198198).
> 
> Ignoring speculatively loaded crates in `existing_match` when no crate hash is given would work I presume?

I don't know :)
Need to investigate.

Comment (petrochenkov) [reply compiler/rustc_metadata/src/creader.rs]: I just tried to remove `fn existing_match` and hit the `locator.hash.is_none()` assert in `CStore::load`.
Upd: ah, I see, it's just assumed that `locator.hash.is_some()` searches always hit the `existing_match` cache, which is not the case now.

Comment (petrochenkov) [reply compiler/rustc_metadata/src/creader.rs]: > I just tried to remove `fn existing_match` and hit the `locator.hash.is_none()` assert in `CStore::load`. Upd: ah, I see, it's just assumed that `locator.hash.is_some()` searches always hit the `existing_match` cache, which is not the case now.

Otherwise ui and run-make tests suites pass with `existing_match` removed, except this one test
```diff
--- i/tests/ui/panic-runtime/need-unwind-got-immediate-abort.rs
+++ w/tests/ui/panic-runtime/need-unwind-got-immediate-abort.rs
@@ -1,4 +1,3 @@
-//@ build-fail
 //@ aux-build:needs-unwind-immediate-abort.rs
 //@ compile-flags:-C panic=immediate-abort -Zunstable-options
 //@ no-prefer-dynamic
@@ -12,10 +11,9 @@

 extern crate minicore;
 extern crate needs_unwind_immediate_abort;
+//~^ ERROR can't find crate for `minicore` which `needs_unwind_immediate_abort` depends on

 #[no_mangle]
 extern "C" fn main(_argc: i32, _argv: *const *const u8) -> i32 {
     0
 }
-
-//~? ERROR the crate `needs_unwind_immediate_abort` was compiled with a panic strategy which is incompatible with `immediate-abort`
```

Comment (bjorn3) [reply compiler/rustc_metadata/src/creader.rs]: I can't reproduce that test failure with

<details>

```diff
diff --git a/compiler/rustc_metadata/src/creader.rs b/compiler/rustc_metadata/src/creader.rs
index 250aa076902..c549d0a67f4 100644
--- a/compiler/rustc_metadata/src/creader.rs
+++ b/compiler/rustc_metadata/src/creader.rs
@@ -534,35 +534,6 @@ fn existing_match(
                 }
                 None => {}
             }
-
-            // When the hash is None we're dealing with a top-level dependency
-            // in which case we may have a specification on the command line for
-            // this library. Even though an upstream library may have loaded
-            // something of the same name, we have to make sure it was loaded
-            // from the exact same location as well.
-            //
-            // We're also sure to compare *paths*, not actual byte slices. The
-            // `source` stores paths which are normalized which may be different
-            // from the strings on the command line.
-            let source = data.source();
-            if let Some(entry) = externs.get(name.as_str()) {
-                // Only use `--extern crate_name=path` here, not `--extern crate_name`.
-                if let Some(mut files) = entry.files() {
-                    if files.any(|l| {
-                        let l = l.canonicalized();
-                        source.dylib.as_ref() == Some(l)
-                            || source.rlib.as_ref() == Some(l)
-                            || source.rmeta.as_ref() == Some(l)
-                    }) {
-                        return Some(cnum);
-                    }
-                }
-                continue;
-            }
-
-            // While the crate name matched, no --extern crate_name=path matched. It is possible
-            // that we have already loaded the target crate, but if that happens CStore::load will
-            // indicate so and we gracefully handle this, just potentially wasting a bit of time.
         }
 
         None
```

</details>

Comment (bjorn3) [reply compiler/rustc_metadata/src/creader.rs]: Curiously enough I can reproduce the ICE from https://github.com/rust-lang/rust/issues/147966 with a test case I wrote, but only when I add `if !data.used() { continue; }`. Without it, the test case compiles fine. And if I remove everything in `existing_match` except for the crate hash lookup case, it correctly reports the ambiguity error.

**Comment by bjorn3** [comment]
That turns out to be much better than I expected. It is a small perf win rather than a perf hit as I was afraid of. I've now cleaned up `existing_match` and made it immediately return `None` when no crate hash is given rather than still iterating over all crates, which should improve perf even more.

@rustbot ready

**Comment by bjorn3** [comment]
Oops, pushed to the wrong branch. Force pushed it back to the approved state.

@bors r=petrochenkov

**Comment by jieyouxu** [comment]
Tagging this with compat relnotes, since it does break the crates that relied on this accidental behavior before.

@rustbot label: +relnotes
