### PR TITLE
Account for use of `try!()` in 2018 edition and guide users in the right direction

### LINKED ISSUE #71155: Account for use of `try!()` in 2018 edition and guide users in the right direction
Old documentation and blogposts will never be updated to not talk about the `try` macro. [The current output of the following code](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=3761918397ede5963c3803f3c3e43201)

```rust
fn foo() -> Result<(), ()> {
    Ok(try!(Ok(())))
    
}
```

is

```
error: expected expression, found reserved keyword `try`
 --> src/main.rs:2:8
  |
2 |     Ok(try!(Ok(())))
  |        ^^^ expected expression
```

It should provide structured suggestions to either use `r#try` or `?`:

```
error: use of deprecated `try` macro
 --> src/main.rs:2:8
  |
2 |     Ok(try!(Ok(())))
  |        ^^^^^      ^
  |        |
  |        deprecated `try` macro
  = note: in the 2018 edition `try` is a reserved keyword, and the `try!()` macro is deprecated
help: you can use the `?` operator instead
  |
2 |     Ok(Ok(())?))
  |        --      ^
help: alternatively, you can still access the deprecated `try!()` macro using the "raw identifier" syntax
  |
2 |     Ok(r#try!(Ok(())))
  |        ^^
```

This request is similar in spirit to #67204 and feels like a subset of #65148.

This issue has been assigned to @Duddino via [this comment](https://github.com/rust-lang/rust/issues/71155#issuecomment-614616832).

### PR DESCRIPTION
**Pull request by Duddino**
fixes #71155

### CODE REVIEW

**Comment by Duddino** [comment]
I'm not sure how this works, should I pick @estebank since he opened the issue?

File: src/librustc_parse/parser/expr.rs [hunk 1]
```diff
@@ -1001,11 +1001,13 @@ impl<'a> Parser<'a> {
 
     fn parse_lit_expr(&mut self, attrs: AttrVec) -> PResult<'a, P<Expr>> {
         let lo = self.token.span;
+        let is_try = self.token.is_keyword(kw::Try);
         match self.parse_opt_lit() {
             Some(literal) => {
                 let expr = self.mk_expr(lo.to(self.prev_token.span), ExprKind::Lit(literal), attrs);
                 self.maybe_recover_from_bad_qpath(expr, true)
             }
+            None if is_try => Err(self.try_macro_suggestion()),
```
Comment (estebank) [inline src/librustc_parse/parser/expr.rs:1010]: If we move the check for `try` into `try_macro_suggestion` we call it unconditionally.

File: src/librustc_parse/parser/diagnostics.rs [hunk 2]
```diff
@@ -1054,6 +1054,39 @@ impl<'a> Parser<'a> {
...
+                    Applicability::MachineApplicable,
+                );
+                err.span_suggestion(lo.shrink_to_lo(), "alternatively, you can still access the deprecated `try!()` macro using the \"raw identifier\" syntax", "r#".to_string(), Applicability::MachineApplicable);
+            } else {
+                //if the try! macro is empty, it isn't possible to suggest something using the `?` operator
+                err.span_suggestion(lo.shrink_to_lo(), "you can still access the deprecated `try!()` macro using the \"raw identifier\" syntax", "r#".to_string(), Applicability::MachineApplicable);
+            }
+            err
+        } else {
+            self.expected_expression_found() // The user isn't trying to invoke the try! macro
```
Comment (estebank) [inline src/librustc_parse/parser/diagnostics.rs:1087]:
```suggestion
            Err(self.expected_expression_found()) // The user isn't trying to invoke the try! macro
```

File: src/librustc_parse/parser/diagnostics.rs [hunk 3]
```diff
@@ -1054,6 +1054,39 @@ impl<'a> Parser<'a> {
...
+                    "you can use the `?` operator instead",
+                    vec![(try_span, "".to_owned()), (hi, "?".to_owned())],
+                    Applicability::MachineApplicable,
+                );
+                err.span_suggestion(lo.shrink_to_lo(), "alternatively, you can still access the deprecated `try!()` macro using the \"raw identifier\" syntax", "r#".to_string(), Applicability::MachineApplicable);
+            } else {
+                //if the try! macro is empty, it isn't possible to suggest something using the `?` operator
+                err.span_suggestion(lo.shrink_to_lo(), "you can still access the deprecated `try!()` macro using the \"raw identifier\" syntax", "r#".to_string(), Applicability::MachineApplicable);
+            }
+            err
```
Comment (estebank) [inline src/librustc_parse/parser/diagnostics.rs:1085]:
```suggestion
            err.emit();
            self.mk_expr_err(lo.to(self.prev_span));
```

If we do that then you don't need to wrap the call in `Err()` and the AST will have a proper node for bad `try`. We could even try to properly parse it as a real macro call, which would let the type checker to run on it (but we don't need to do that now).

**Review by estebank — APPROVED** [review]
It looks really good!

I left some nitpicks.

File: src/librustc_parse/parser/diagnostics.rs (hunk 3 above)
Comment (Duddino) [reply src/librustc_parse/parser/diagnostics.rs:1085]: It says `self.prev_span` is an unknown field

Comment (Duddino) [reply src/librustc_parse/parser/diagnostics.rs:1085]: I'm returning this `Ok(self.mk_expr_err(lo.to(hi)))`

File: src/librustc_parse/parser/diagnostics.rs [hunk 4]
```diff
@@ -1054,6 +1054,41 @@ impl<'a> Parser<'a> {
...
+            if !is_empty {
+                err.multipart_suggestion(
+                    "you can use the `?` operator instead",
+                    vec![(try_span, "".to_owned()), (hi, "?".to_owned())],
+                    Applicability::MachineApplicable,
+                );
+                err.span_suggestion(lo.shrink_to_lo(), "alternatively, you can still access the deprecated `try!()` macro using the \"raw identifier\" syntax", "r#".to_string(), Applicability::MachineApplicable);
+            } else {
+                //if the try! macro is empty, it isn't possible to suggest something using the `?` operator
+                err.span_suggestion(lo.shrink_to_lo(), "you can still access the deprecated `try!()` macro using the \"raw identifier\" syntax", "r#".to_string(), Applicability::MachineApplicable);
```
Comment (estebank) [inline src/librustc_parse/parser/diagnostics.rs:1083]: Because these two suggestions are the same only with a different message, you can have

```
let prefix = if !is_empty {
    ...
    "alternatively, "
} else {
    ""
};
err.span_suggestion(
    lo.shrink_to_lo(),
    &format!("{}your message", prefix),
    "r#".to_string(),
```

Also, you will need to run `./x.py fmt` for the formatting to be accepted by CI. And because of limitations in `rustfmt`, you will have to split long strings yourself before running it:

```
let x =
    "this is a long \
     multiline \
     string";

File: src/librustc_parse/parser/diagnostics.rs [hunk 5]
```diff
@@ -1054,6 +1054,39 @@ impl<'a> Parser<'a> {
...
+            self.bump(); //remove !
+            let try_span = lo.to(self.token.span); //we take the try!( span
+            self.bump(); //remove (
+            let is_empty = self.token == token::CloseDelim(token::Paren); //check if the block is empty
+            self.consume_block(token::Paren, ConsumeClosingDelim::No); //eat the block
+            let hi = self.token.span;
+            self.bump(); //remove )
+            let mut err = self.struct_span_err(lo.to(hi), "use of deprecated `try` macro");
+            err.note("in the 2018 edition `try` is a reserved keyword, and the `try!()` macro is deprecated");
+            let prefix = if is_empty { "alternatively, " } else { "" };
```
Comment (estebank) [inline src/librustc_parse/parser/diagnostics.rs:1074]: The logic here is reversed :)
