### PR TITLE
enforce user annotations in closure signatures

### LINKED ISSUE #54124: Lifetime inference failed on HRTB input
[The following code](https://play.rust-lang.org/?gist=73fa21e0d08fb40b58be11266d4d359d&version=stable&mode=debug&edition=2015)

```rust
use std::marker::PhantomData;

trait Lt<'a> {
    type T;
}
impl<'a> Lt<'a> for () {
    type T = PhantomData<&'a ()>;
}

fn test<'a>() {
    let _:fn(<() as Lt<'_>>::T) = |_:PhantomData<&'a ()>| {};
}

fn main() {
    test();
}
```
gives 
```text
error[E0495]: cannot infer an appropriate lifetime for lifetime parameter `'a` due to conflicting requirements
  --> src/main.rs:11:59
   |
11 |     let _:fn(<() as Lt<'_>>::T) = |_:PhantomData<&'a ()>| {};
   |                                                           ^^
   |
note: first, the lifetime cannot outlive the lifetime 'a as defined on the function body at 10:1...
  --> src/main.rs:10:1
   |
10 | fn test<'a>() {
   | ^^^^^^^^^^^^^
   = note: ...so that the types are compatible:
           expected std::marker::PhantomData<&()>
              found std::marker::PhantomData<&'a ()>
note: but, the lifetime must be valid for the anonymous lifetime #2 defined on the body at 11:35...
  --> src/main.rs:11:35
   |
11 |     let _:fn(<() as Lt<'_>>::T) = |_:PhantomData<&'a ()>| {};
   |                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
   = note: ...so that the types are compatible:
           expected Lt<'_>
              found Lt<'_>
```
(this is a slightly different version of [this stackoverflow question](https://stackoverflow.com/questions/52267575/why-can-this-lifetime-not-outlive-the-closure))

# Analysis

The error message suggest that the type inference engine consider the *upper* bound of `'_` is the lifetime of the closure. This is incorrect, because this lifetime is in an input argument, so it should consider the *lower* bound to be `'a` instead.

This issue may have relation with #53420, but I am not sure yet.

### LINKED ISSUE #54692: NLL doesn't respect user types in closure signatures
For example, the following code compiles

```rust
#![feature(nll)]
fn foo<'a>() {
    |x: &'a i32| -> &'static i32 {
        return &x;
    };
}
```
cc #47184

### PR DESCRIPTION
**Pull request by nikomatsakis**
Not *quite* ready yet but I'm opening anyway. Still have to finish running tests locally.

Fixes #54692 
Fixes #54124 

r? @matthewjasper

### CODE REVIEW

**Comment by nikomatsakis** [comment]
OK, should work now. We'll see what Travis thinks.

File: src/test/ui/nll/user-annotations/closure-substs.rs [hunk 1]
```diff
@@ -0,0 +1,29 @@
...
+
+// Test that we enforce user-provided type annotations on closures.
+
+fn foo<'a>() {
+    |x: &'a i32| -> &'static i32 {
+        return x; //~ ERROR
+    };
+}
+
+fn bar<'a>() {
```
Comment (matthewjasper) [inline src/test/ui/nll/user-annotations/closure-substs.rs]: Is this lifetime supposed to be used?

**Review by matthewjasper — APPROVED** [review]
One thing that I'm not sure about. r=me with that addressed

File: src/test/incremental/hashes/closure_expressions.rs [hunk 2]
```diff
@@ -95,7 +95,7 @@ pub fn add_type_ascription_to_parameter() {
 }
 
 #[cfg(not(cfail1))]
-#[rustc_clean(cfg="cfail2", except="HirBody")]
+#[rustc_clean(cfg="cfail2", except="HirBody, TypeckTables")]
```
[the remark this answers is not in the document]
Comment (nikomatsakis) [reply src/test/incremental/hashes/closure_expressions.rs]: It is correct.

[the remark this answers is not in the document]
Comment (nikomatsakis) [reply src/test/incremental/hashes/closure_expressions.rs]: To say a bit more: Before, we were not (fully) capturing the user-given type annotations for closures in the typeck tables. So adding a type annotation did not change the hash of typeck tables. But now we are, so it is good that adding a type annotation changes the hash of typeck tables, since that indicates that things which consume the typeck tables (like MIR borrow check) will have to re-execute if those annotations change. =)

File: src/test/ui/nll/user-annotations/closure-substs.rs (hunk 1 above)
Comment (nikomatsakis) [reply src/test/ui/nll/user-annotations/closure-substs.rs]: No, the point was to test without the explicit `'a`. I'll remove it.

Comment (nikomatsakis) [reply src/test/ui/nll/user-annotations/closure-substs.rs]: Well, I guess I was testing  two distinct things. Perhaps I should add some more tests to tile the space.

File: src/test/ui/nll/user-annotations/closure-substs.stderr [hunk 3]
```diff
@@ -0,0 +1,42 @@
...
+   |         ^^^^ `x` escapes the closure body here
+
+error: unsatisfied lifetime constraints
+  --> $DIR/closure-substs.rs:23:9
+   |
+LL |     |x: &i32, b: fn(&'static i32)| {
+   |     ------------------------------
+   |     |   |
+   |     |   let's call the lifetime of this reference `'1`
+   |     lifetime `'2` represents this closure's body
```
[the remark this answers is not in the document]
Comment (nikomatsakis) [reply src/test/ui/nll/user-annotations/closure-substs.stderr]: I fixed it.

File: src/test/ui/nll/user-annotations/closure-substs.rs (hunk 1 above)
Comment (nikomatsakis) [reply src/test/ui/nll/user-annotations/closure-substs.rs]: Done.

**Comment by nikomatsakis** [comment]
@bors r=MatthewJasper p=1 

Giving p=1 because this is an RC2 blocker.

**Comment by matthewjasper** [comment]
I think bors is back now. @bors r=matthewjasper

**Comment by nikomatsakis** [comment]
Is this the reason the run failed?

```
The state of "rls" has changed from "test-pass" to "test-fail"
The state of "rls" has regressed from "test-pass" to "test-fail"
```

If so...interesting and unexpected. =)

**Comment by nikomatsakis** [comment]
@bors r=MatthewJasper

Let's see if this is spurious or not.

**Comment by nikomatsakis** [comment]
I can't reproduce locally.
