### PR TITLE
Tidy: disallow TODO in other in-tree projects

### LINKED ISSUE #152280: Tracking issue for MCP 963: Extend the ` x.py` policy for `TODO` and `FIXME` to other in-tree projects
This is a tracking issue for MCP "Extend the ` x.py` policy for `TODO` and `FIXME` to other in-tree projects" (rust-lang/compiler-team#963).

> [!NOTE]
> Tracking issues are used to record the overall progress of implementation.
> They are also used as hubs connecting to other relevant issues, e.g., bugs or open design questions.
>
> A tracking issue is however *not* meant for large scale discussion, questions, or bug reports.
> Instead, open a dedicated issue for the specific matter, link to this tracking issue and ping the MCP author.
> Alternatively, post in the Zulip stream linked from the MCP.
>
> Discussion comments will get marked as off-topic or deleted.
> Repeated discussions on the tracking issue may lead to the tracking issue getting locked.

### Steps

- [ ] Implement the MCP
- [ ] Adjust documentation
  - [ ] In the [Rust Compiler Development Guide] if applicable (e.g., for refactorings)
  - [ ] In the [Rust Forge] if applicable (e.g., for policy changes)
  - [ ] In the [rustc book] if applicable (e.g., for target tier or CLI changes)

[Rust Compiler Development Guide]: https://rustc-dev-guide.rust-lang.org/
[Rust Forge]: https://forge.rust-lang.org/compiler/index.html
[rustc book]: https://doc.rust-lang.org/rustc/index.html

### Unresolved questions

*None so far.*

### Implementation history

*Empty so far.*

---

@lcnr, consider `@rustbot claim`'ing the work.

### PR DESCRIPTION
**Pull request by reddevilmidzy**
Fixes: https://github.com/rust-lang/rust/issues/152280
MCP: https://github.com/rust-lang/compiler-team/issues/963

TODO

* [x] Add ci check to `cg_clif`: https://github.com/rust-lang/rustc_codegen_cranelift/pull/1632
* [x] Add ci check to `cg_gcc`: https://github.com/rust-lang/rustc_codegen_gcc/pull/861

r? lcnr

### CODE REVIEW

File: src/tools/tidy/src/alphabetical.rs [hunk 1]
```diff
@@ -261,6 +262,8 @@ pub fn check(path: &Path, tidy_ctx: TidyCtx) {
 
     let skip = |path: &_, _is_dir| {
         filter_dirs(path)
+            // Patch files may include tidy markers unrelated to source ordering.
+            || path.extension() == Some(OsStr::new("patch"))
```
Comment (reddevilmidzy) [inline src/tools/tidy/src/alphabetical.rs]: The `.patch` was allowed because of this file.

https://github.com/rust-lang/rust/blob/6a979b3e32522049d0acb4a47f7ae44b7c8abfd5/compiler/rustc_codegen_cranelift/patches/0027-sysroot_tests-128bit-atomic-operations.patch#L16-L20

File: compiler/rustc_codegen_gcc/tools/generate_intrinsics.py [hunk 2]
```diff
@@ -87,6 +88,7 @@ def update_intrinsics(llvm_path):
     with open(output_file, "w", encoding="utf8") as out:
         out.write("""// File generated by `rustc_codegen_gcc/tools/generate_intrinsics.py`
 // DO NOT EDIT IT!
+// ignore-tidy-filelength
```
Comment (reddevilmidzy) [inline compiler/rustc_codegen_gcc/tools/generate_intrinsics.py]: I added `// ignore-tidy-filelength` here and also manually added it to `compiler/rustc_codegen_gcc/src/intrinsic/archs.rs`.

File: src/tools/tidy/src/unit_tests.rs [hunk 3]
```diff
@@ -65,6 +65,7 @@ pub fn check(root_path: &Path, stdlib: bool, tidy_ctx: TidyCtx) {
                 || path.ends_with("library/alloc/src/collections/vec_deque/tests.rs")
                 || path.ends_with("library/alloc/src/raw_vec/tests.rs")
                 || path.ends_with("library/alloc/src/wtf8/tests.rs")
+                || path.ends_with("compiler/rustc_codegen_gcc/build_system/src/utils.rs")
```
Comment (reddevilmidzy) [inline src/tools/tidy/src/unit_tests.rs]: https://github.com/rust-lang/rust/blob/6a979b3e32522049d0acb4a47f7ae44b7c8abfd5/compiler/rustc_codegen_gcc/build_system/src/utils.rs#L426-L442

Because of this test, should I move the test or allow this?
It felt like a strong unit test, and I didn't see a good place for it, so I allowed it for now.

File: src/tools/tidy/src/codegen.rs
Comment (reddevilmidzy) [inline src/tools/tidy/src/codegen.rs:1]: I tried to add cg_* checks to [`style.rs`](https://github.com/rust-lang/rust/blob/main/src/tools/tidy/src/style.rs), which checks TODOs in tidy, but since it also checks other things besides TODOs, I separated it into `codegen.rs`.

File: compiler/rustc_session/src/parse.rs [hunk 4]
```diff
@@ -79,7 +79,7 @@ impl SymbolGallery {
     }
 }
 
-// todo: this function now accepts `Session` instead of `ParseSess` and should be relocated
```
Comment (reddevilmidzy) [inline compiler/rustc_session/src/parse.rs:82]: lowercase 👀

**Review by reddevilmidzy — COMMENTED** [review]
I've also added a TODO check to the CI for `cg_*` (https://github.com/rust-lang/rustc_codegen_cranelift/pull/1632, https://github.com/rust-lang/rustc_codegen_gcc/pull/861). 



*[View changes since this review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/rust/153166/ea5573a6c6e5e932f917ec4a8e6d8efdeb9f394d..2617d54c0915c2c5994ee0f330c8567297c338d5)*

File: compiler/rustc_codegen_gcc/src/type_.rs [hunk 5]
```diff
@@ -110,7 +110,7 @@ impl<'gcc, 'tcx> CodegenCx<'gcc, 'tcx> {
             .iter()
             .enumerate()
             .map(|(index, field)| {
-                self.context.new_field(None, *field, format!("field{}_TODO", index))
+                self.context.new_field(None, *field, format!("field{}_FIXME", index))
```
Comment (lcnr) [inline compiler/rustc_codegen_gcc/src/type_.rs:113]: is that fine?

File: src/tools/tidy/src/style.rs [hunk 6]
```diff
@@ -378,11 +378,16 @@ pub fn check(path: &Path, tidy_ctx: TidyCtx) {
...
+    let codegen_file = Path::new("src/tools/tidy/src/codegen.rs");
 
     walk(path, skip, &mut |entry, contents| {
         let file = entry.path();
         let path_str = file.to_string_lossy();
         let filename = file.file_name().unwrap().to_string_lossy();
+        let is_codegen_tidy_file = file.ends_with(codegen_file);
+        if is_codegen_tidy_file {
+            return;
+        }
```
Comment (lcnr) [inline src/tools/tidy/src/style.rs]: why this?

Comment (reddevilmidzy) [reply src/tools/tidy/src/style.rs]: https://github.com/rust-lang/rust/pull/153166/changes/a035848ddd9bd8d60d7184d78b8aacf97aca7431#diff-2877cff958f18d248fbdb0e5f924a453e3911e7e8340139125911d3bdd8e5a62R49-R53

I'm using the "TODO" character here and top line, this is the part that was added to skip TODO check

File: compiler/rustc_codegen_gcc/src/type_.rs (hunk 5 above)
Comment (reddevilmidzy) [reply compiler/rustc_codegen_gcc/src/type_.rs:113]: Oh, I'll check this again. Thank you

Comment (reddevilmidzy) [reply compiler/rustc_codegen_gcc/src/type_.rs:113]: I changed TODO to FIXME and tested it and it worked.

https://github.com/rust-lang/rustc_codegen_gcc/pull/861/changes/d82d2421f741bf8656718a6e131bd07661dc6d57

cc: @antoyo

Comment (antoyo) [reply compiler/rustc_codegen_gcc/src/type_.rs:113]: Yes, this should be OK.

File: src/tools/tidy/src/style.rs (hunk 6 above)
Comment (lcnr) [reply src/tools/tidy/src/style.rs]: we already do it for `this_file` separately, can you the checks for these two?

after that r=me
