### PR TITLE
compiler: Stop reexporting stuff in cg_llvm::abi

### LINKED ISSUE #137209: rustdoc chooses an odd canonical path for rustc_target::callconv::PassMode
To reproduce, visit https://doc.rust-lang.org/nightly/nightly-rustc/?search=PassMode. The main PassMode type used all over the compiler is shown as `rustc_codegen_llvm::abi::PassMode`. That is quite misleading since it makes it look like the type is specific to the LLVM codegen backend, when it is not! rustdoc should instead pick the path in `rustc_target` and show that.

It seems to me this changed recently. I am fairly sure I searched for `PassMode` before and it never used `rustc_codegen_llvm` as the canonical path. Not sure if it is rustdoc that changed or the rustc crate organization.

Cc @rust-lang/rustdoc @workingjubilee

### PR DESCRIPTION
**Pull request by workingjubilee**
The reexports confuse tooling like rustdoc into thinking cg_llvm is the source of key types that originate in rustc_target.

Avoids #137209 but does not fix the underlying bug.
r? @RalfJung

### CODE REVIEW

**Comment by RalfJung** [comment]
These are just `pub(crate)` re-exports that you are removing here though, right? They are not public, so they should not affect rustdoc.

**Comment by workingjubilee** [comment]
Correct.

Yes, the bug seems quite bad.

**Comment by RalfJung** [comment]
Okay, let's not close the issue then.

@bors r+ rollup

**Comment by workingjubilee** [comment]
sounds good to me

File: compiler/rustc_codegen_llvm/src/abi.rs [hunk 1]
```diff
@@ -2,19 +2,18 @@ use std::borrow::Borrow;
...
-pub(crate) use rustc_abi::ExternAbi;
-use rustc_abi::{HasDataLayout, Primitive, Reg, RegKind, Size};
+use rustc_abi::{BackendRepr, HasDataLayout, Primitive, Reg, RegKind, Size};
 use rustc_codegen_ssa::MemFlags;
 use rustc_codegen_ssa::mir::operand::{OperandRef, OperandValue};
 use rustc_codegen_ssa::mir::place::{PlaceRef, PlaceValue};
 use rustc_codegen_ssa::traits::*;
 use rustc_middle::ty::Ty;
 use rustc_middle::ty::layout::LayoutOf;
-pub(crate) use rustc_middle::ty::layout::{WIDE_PTR_ADDR, WIDE_PTR_EXTRA};
```
Comment (workingjubilee) [inline compiler/rustc_codegen_llvm/src/abi.rs:14]: this is the funniest diff in this PR, to me, because it was absolutely being reexported here but not actually used here.
