### PR TITLE
Better error message for inner attribute following doc comment

### LINKED ISSUE #34516: Clearer error messages when parser encounters an outer attribute when parsing inner attributes.
Consider this example:

```
/**
 * My mod
 */

#![recursion_limit = "100"]
fn main() {}
```

Produces:

```
error: an inner attribute is not permitted in this context
 --> <anon>:5:3
  |>
5 |> #![recursion_limit = "100"]
  |>   ^
help: place inner attribute at the top of the module or block

error: aborting due to previous error

Compilation failed.
```

It's quite impossible to understand what's going on if you don't know that `/** */` is an outer attribute. Unfortunately after looking at the parser a bit it's not obvious what to do to make this situation clearer. Possibly `parse_outer_attributes` should emit a new error if its call to to `parse_attribute` fails. It can look at whether it has a previously-parsed attribute, and whether it was a doc comment, and emit better errors, e.g.

For non-doc comments: "inner attributes may not follow outer attributes"; for doc comments: "inner attributes may not follow outer doc-comments". A good comparison to draw is with the existing error in `parser_outer_attributes` when it encounters a incorrect inner doc comment. The errors should be similar for incorrect inner attributes vs. incorrect inner doc comments.

[Original issue](https://github.com/rust-lang/rust/issues/2789#issuecomment-44718206).

### PR DESCRIPTION
**Pull request by aravind-pg**
Before it was always just "an inner attribute is not permitted in this context", whereas now we add a special case for when an inner attr follows an outer attr. If the outer attr is a doc comment, then the error is "an inner attr is not permitted following a doc comment", and otherwise it's "an inner attr is not permitted following an outer attribute". In all other cases it's still  "an inner attribute is not permitted in this context". 

Note that the public API and behaviour of `parse_attribute` is unchanged. Also, all new names are very open to bikeshedding -- they're arguably clunky.

Fixes #34516. cc @brson

### CODE REVIEW

**Comment by brson** [comment]
Thanks @aravind-pg! This looks good to me. My only reservation is the text "an inner attr is not permitted following a doc comment". Technically what's invalid is following an *outer* doc comment - there are both inner and outer doc comments. Although raising the distinction is potentially confusion, I *think* it's probably better to be explicit about it. Can you update the text to say "outer doc comment"?

f? @mikedilger @Manishearth @jonathandturner trying to make a confusing parse error understandable.

**Comment by aravind-pg** [comment]
Makes sense, updated now.

**Comment by Manishearth** [comment]
inner/outer attrs aren't a well-known term, could we also display notes explaining what each is?

**Comment by aravind-pg** [comment]
Sure. Any suggestions on what the notes should be so as to be friendly to users? Given that in this error message we're distinguishing general outer attributes from outer doc comments anyway, maybe something very explicit like the following?
- "an inner attribute is one of the form `#![foo]` in `mod bar { #![foo] }`, modifying the item _enclosing_ it (`mod bar` in our example), whereas an outer attribute is one of the form `#[foo]` in `#[foo] struct Baz`, modifying the item _following_ it (`struct Baz` in our example)".

Alternatively maybe we should just link to https://doc.rust-lang.org/book/attributes.html. I'd like that better actually.

**Comment by Manishearth** [comment]
Sounds good. I prefer things like this to be inline.

**Comment by aravind-pg** [comment]
Added notes now, may need further wordsmithing, PTAL.

File: src/libsyntax/parse/attr.rs [hunk 1]
```diff
@@ -55,26 +76,49 @@ impl<'a> Parser<'a> {
...
-                                             "an inner attribute is not permitted in this context")
+                            .struct_span_err(span, reason)
                             .help("place inner attribute at the top of the module or \
                                    block")
+                            .note("an inner attribute is one of the form `#![foo]` in \
+                                   `mod bar { #![foo] }`, modifying the item enclosing it \
+                                   (`mod` bar in our example)")
+                            .note("an outer attribute is either of the form `#[foo]` in \
+                                   `#[foo] struct Baz` or is an outer doc comment, modifying \
+                                   the item following it (`struct Baz` in our example)")
```
Comment (brson) [inline src/libsyntax/parse/attr.rs]: This is a lot of spew. Let's try to condense a bit. First, let's remove the 'help'. I think with the new explanation it is pretty useless.

For the 'note' it would be good to indicate that inner attributes can be comments and are usually encountered at the crate level.

What about this: "inner attributes and doc comments, like `#![no_std]` or `//! My crate`, annotate the enclosing item, and are usually found at the crate root. Outer attributes and doc comments, like `#[test]` and `/// My function`, annotate the following item."

Comment (aravind-pg) [inline src/libsyntax/parse/attr.rs]: Yeah, I do agree that this is a lot of spew, unfortunately. But I also think the 'help' is pretty useful here since it is actually actionable, and especially so for a beginner.

Your suggestion for the note sounds pretty good to me, and I'm happy to change mine, but I have a vague worry that the sentence structure doesn't quite emphasize the "enclosing vs. following" distinction enough (when used as adjectives like that it somehow seems they don't stand out enough, if that makes any sense). Maybe it would be good to get the opinion of @steveklabnik on this? Also @Manishearth since he was the one who suggested the note.

Also, would you like it to be two separate notes or one long sentence/note?

Comment (brson) [inline src/libsyntax/parse/attr.rs]: I'd prefer one note if possible.

Comment (Manishearth) [inline src/libsyntax/parse/attr.rs]: Fix it to be a single note and r=me

Comment (aravind-pg) [inline src/libsyntax/parse/attr.rs]: Sounds good. And should the 'help' stay or go?

Comment (Manishearth) [inline src/libsyntax/parse/attr.rs]: keep it

**Comment by aravind-pg** [comment]
Updated with @brson's suggested note now, with a minor change (s/following item/item following them, because otherwise it reads like it might be referring to something following the note itself. Similarly s/enclosing item/item enclosing them). Should be good to go now?

File: src/libsyntax/parse/attr.rs [hunk 2]
```diff
@@ -55,26 +76,48 @@ impl<'a> Parser<'a> {
...
                         let span = self.span;
                         self.diagnostic()
-                            .struct_span_err(span,
-                                             "an inner attribute is not permitted in this context")
+                            .struct_span_err(span, reason)
                             .help("place inner attribute at the top of the module or \
                                    block")
+                            .note("inner attributes and doc comments, like `#![no_std]` or \
+                                   `//! My crate`, annotate the item enclosing them, and are \
+                                   usually found at the crate root. Outer attributes and doc \
```
Comment (pnkfelix) [inline src/libsyntax/parse/attr.rs]: Inner attributes are also often found at the start of files for any module at all, not just the crate root, no?

Maybe it would be simpler to just say "usually found at the start of Rust source files", which would cover both crate roots and non-root modules housed in their own files?

Comment (brson) [inline src/libsyntax/parse/attr.rs]: Agreed. @aravind-pg can you make one more update?

I also strongly feel that the help is redundant now. Help says 'place inner attribute at X'; note says 'inner attributes annotate the item enclosing them'. The two statements are semantically similar. If there is important information missing from the note then the wording can be tweaked slightly. I'd like to remove the note.

Comment (brson) [inline src/libsyntax/parse/attr.rs]: Hm, on second thought this is a rare error, so one extra note isn't going to matter much. I do think it would be cleaner to say what we're trying to say in once sentence than two.

Comment (aravind-pg) [inline src/libsyntax/parse/attr.rs]: Not completely clear what your final call is here. I can definitely get rid of the help, not strongly attached to it by any means. Will also make the change that @pnkfelix pointed out.

**Comment by aravind-pg** [comment]
Updated to remove the help and make the change that @pnkfelix suggested.

**Comment by brson** [comment]
@bors r+

Thanks @aravind-pg !

**Comment by aravind-pg** [comment]
Fixed trailing whitespace tidy error.

@bors r=brson

**Comment by Manishearth** [comment]
@bors-servo r=brson

only reviewers can do that :smile:

**Comment by Manishearth** [comment]
Er.

@bors r=brson

**Comment by aravind-pg** [comment]
Haha yeah I figured, was just about to pop by #rust-internals to ask someone. Also, kinda cool that @bors-servo can stand in like that for @bors, huh.

**Comment by Manishearth** [comment]
Homu/bors has a very simple parser that just throws out things it doesn't understand. As long as the line starts with bors, in Rust's case, it is fine. On servo it has to start with bors-servo.

I'm involved in both projects so I often ping the wrong bot. This works on Rust, but not servo.
