### PR TITLE
Aarch64 call abi does not zeroext (and one cannot assume it does so)

### LINKED ISSUE #97463: Wrong cast of u16 to usize on aarch64
Hello,

A cast of a u16 value returned from a C function to a usize is invalid when enabling optimization.

I tried this code (with cargo flag --release):

```c
#include <stdlib.h>
#include <stdint.h>
#include <stdio.h>

struct bloc {
    uint16_t a;
    uint16_t b;
    uint16_t c;
};

uint16_t c_read_value(void) {
    struct bloc *data = malloc(sizeof(struct bloc));
    data->a = rand() & 0xFFFF;
    data->b = rand() & 0xFFFF;
    data->c = rand() & 0xFFFF;

    printf("C struct: a = %u, b = %u, c = %u\n",
        (unsigned) data->a, (unsigned) data->b, (unsigned) data->c);
    printf("C function returns %u\n", (unsigned) data->b);

    return data->b; /* leak data */
}
```
```rust
//#![feature(bench_black_box)]

#[link(name = "bad")]
extern "C" {
    pub fn c_read_value() -> u16;
}

fn main() {
    let value = unsafe { c_read_value() };
    dbg!(value); // ok
    dbg!(value as usize); // nok
    dbg!(usize::from(value)); // nok
    dbg!((value as usize) & 0xFFFF); // nok

    //dbg!(std::hint::black_box(value) as usize); // ok
}
```

I expected to print the same value when casting to usize.

Instead, the value is wrong, the cast seems to "absorb" the neighboring bytes. Worse, I cannot even mask with `& 0xFFFF`!

```
C struct: a = 17767, b = 9158, c = 39017
C function returns 9158
[src/main.rs:10] value = 9158
[src/main.rs:11] value as usize = 846930886
[src/main.rs:12] usize::from(value) = 846930886
[src/main.rs:13] (value as usize) & 0xFFFF = 846930886
```

Using black_box with nightly on the value fixes the issue. I'd like to find a good workaround for stable though.

No issue in debug mode.

To reproduce, this repo can be used: https://github.com/fparat/badcast

### Meta

Bug present on stable and nightly.
Found on Linux aarch64 (Jetson Nano). No issue found on amd64 or armv7.

`rustc +nightly --version --verbose`:
```
rustc 1.63.0-nightly (490324f7b 2022-05-26)
binary: rustc
commit-hash: 490324f7b29d5f1a1e063a563045d790091ed639
commit-date: 2022-05-26
host: aarch64-unknown-linux-gnu
release: 1.63.0-nightly
LLVM version: 14.0.4
```

Same issue with both gcc and clang for the C code
```
clang version 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
gcc (Ubuntu/Linaro 7.5.0-3ubuntu1~18.04) 7.5.0
```

Backtrace: N.A.

### PR DESCRIPTION
**Pull request by pnkfelix**
Fix #97463

### CODE REVIEW

File: src/test/run-make-fulldeps/issue-97463-abi-param-passing/Makefile [hunk 1]
```diff
@@ -0,0 +1,9 @@
+-include ../tools.mk
+
+all:
+#	$(call COMPILE_OBJ,$(TMPDIR)/bad.o,bad.c)
+	$(CC) -c -O3 -o $(TMPDIR)/bad.o bad.c
```
Comment (luqmana) [inline src/test/run-make-fulldeps/issue-97463-abi-param-passing/Makefile:5]: Maybe leave a comment for why you call `CC` directly instead of with `COMPILE_OBJ`?

Comment (pnkfelix) [reply src/test/run-make-fulldeps/issue-97463-abi-param-passing/Makefile:5]: Oh yeah, that was because the bug didn't replicate if I didn't pass *some* optimization flags in. I noted it my surprise about this (and my concern about what that implies for the rest of the `run-make` test suite) on the issue https://github.com/rust-lang/rust/issues/97463#issuecomment-1146308440 , but you're right, it would be good to have a note about this in the `Makefile` itself. Will fix.

Comment (pnkfelix) [reply src/test/run-make-fulldeps/issue-97463-abi-param-passing/Makefile]: resolved via f5bbb8c187971452540888fc653485f5277309e6

**Comment by Mark-Simulacrum** [comment]
I'm probably not a good reviewer for this, so going to r? rust-lang/compiler

**Comment by apiraino** [comment]
beta backport discussed in T-compiler and postponed to next week ([Zulip discussion](https://rust-lang.zulipchat.com/#narrow/stream/238009-t-compiler.2Fmeetings/topic/.5Bweekly.5D.202022-06-09/near/285544367))

stable backport declined

@rustbot label -stable-nominated

File: compiler/rustc_target/src/abi/call/aarch64.rs [hunk 2]
```diff
@@ -30,7 +30,6 @@ where
     C: HasDataLayout,
 {
     if !ret.layout.is_aggregate() {
-        ret.extend_integer_width_to(32);
```
Comment (nbdd0121) [inline compiler/rustc_target/src/abi/call/aarch64.rs:33]: Do we have special handling for Apple platforms? As I pointed out in https://github.com/rust-lang/rust/issues/97463#issuecomment-1144995863, Apple uses a [non-standard calling convention](https://developer.apple.com/documentation/xcode/writing-arm64-code-for-apple-platforms#:~:text=The%20caller%20of%20a%20function%20is%20responsible%20for%20signing%20or%20zero%2Dextending%20any%20argument%20with%20fewer%20than%2032%20bits.%20The%20standard%20ABI%20expects%20the%20callee%20to%20sign%20or%20zero%2Dextend%20those%20arguments.) so that this extension is still needed.

File: src/test/run-make-fulldeps/issue-97463-abi-param-passing/bad.c [hunk 3]
```diff
@@ -0,0 +1,24 @@
...
+#include <stdio.h>
+
+
+struct bloc {
+    uint16_t a;
+    uint16_t b;
+    uint16_t c;
+};
+
+uint16_t c_read_value(uint32_t a, uint32_t b, uint32_t c) {
```
[the remark this answers is not in the document]
Comment (pnkfelix) [reply src/test/run-make-fulldeps/issue-97463-abi-param-passing/bad.c:12]: let me go inspect that.

(whatever it is, it will need to use `-O` to replicate the problems here...)

File: compiler/rustc_target/src/abi/call/aarch64.rs (hunk 2 above)
Comment (pnkfelix) [reply compiler/rustc_target/src/abi/call/aarch64.rs:33]: I'll look into this.

Comment (pnkfelix) [reply compiler/rustc_target/src/abi/call/aarch64.rs:33]: (also, the use of `32` there is almost certainly a cut-and-paste bug, as pointed out by @spastorino in yesterday's T-compiler meeting.)

Comment (nbdd0121) [reply compiler/rustc_target/src/abi/call/aarch64.rs:33]: No, 32 is correct. The Apple doc says "The caller of a function is responsible for signing or zero-extending any argument with fewer than 32 bits".

**Comment by nbdd0121** [comment]
I think the test should really be a couple of codegen test (instead of testing using run-make-fulldeps) to ensure that we emit the same function signature as Clang does for a `extern "C"` function.

**Comment by nagisa** [comment]
I disagree – the test should be a codegen test _in addition_ to a test that actually verifies that the assumptions hold in practice. There's a good reason why we have a bunch of ABI tests that exercise behaviour at runtime.

File: compiler/rustc_target/src/abi/call/aarch64.rs (hunk 2 above)
Comment (pnkfelix) [reply compiler/rustc_target/src/abi/call/aarch64.rs:33]: hmm, okay; the use of 32 is not as "obviously wrong" as I had thought.

Some questions that came up for me while looking further into this:
 * As noted by @HeroicKatora in their [comment on the issue](https://github.com/rust-lang/rust/issues/97463#issuecomment-1140210248), it is unclear whether one is supposed to apply those rules to the return values in same manner as the function arguments
 * I am reading and re-reading the section of the Windows ABI doc (supposedly excerpted directly from ARM's docs) on ["Prepadding and extension of arguments"](https://docs.microsoft.com/en-us/cpp/build/arm64-windows-abi-conventions?view=msvc-170#stage-b--pre-padding-and-extension-of-arguments) and the subsequent ["Assignment of arguments to registers and stack"](https://docs.microsoft.com/en-us/cpp/build/arm64-windows-abi-conventions?view=msvc-170#stage-c--assignment-of-arguments-to-registers-and-stack); from the titles I had expected to see a bullet specifying at least one case where (sign-or-zero) extension occurs, but I think it pretty clearly indicates that each value is copied into the least significant bits of the corresponding register or stack, and the remaining bits are left as unspecified values.
 * In the section dedicated to [return values](https://docs.microsoft.com/en-us/cpp/build/arm64-windows-abi-conventions?view=msvc-170#return-values), it doesn't say anything about sign or zero extension...

Comment (nbdd0121) [reply compiler/rustc_target/src/abi/call/aarch64.rs:33]: As for the return value, https://github.com/ARM-software/abi-aa/blob/main/aapcs64/aapcs64.rst#65result-return says:
> If the type, T, of the result of a function is such that
> ```c
> void func(T arg)
> ```
> would require that arg be passed as a value in a register (or set of registers) according to the rules in [Parameter passing](https://github.com/ARM-software/abi-aa/blob/main/aapcs64/aapcs64.rst#parameter-passing), then the result is returned in the same registers as would be used for such an argument.

So the same rule should apply regardless parameter or return value.

So using a language lawyer reasoning, if Apple adds a rule to the parameter passing then the standard AArch64 rule that mandates parameter and return value be passed the same way kicks in and adds that rule to the return value too. This is consistent with the behaviour of clang. I agree that Apple should be explicit about this though.

For the Windows ARM64 ABI doc, I suppose it lacks mentioning about sign-extension or zero-extension because there're no such requirements. If you look at the ARM ABI doc it does mention about such extensions.

**Comment by pnkfelix** [comment]
Yes, I agree with @nagisa : the run-make-fulldeps test is very fragile (in the sense that changes to the optimizations can cause the test to stop actually exercising that the proper change is in place), but it is a proper integration test.

I have now confirmed on my Apple M1 that the existing codegen tests even *catch* the mistake injected by this PR. Namely, I just tried to do a local `x.py test src/test/codegen` on my Apple M1, and got:

```
failures:
    [codegen] src/test/codegen/abi-repr-ext.rs
    [codegen] src/test/codegen/pic-relocation-model.rs
```

However, I think it will improve things a bit if I add a set of codegen tests specifically checking how `i8`/`i16`/`u8`/`u16` are passed and returned. (I'm not quite sure yet how best to encode the *variation* between different targets on this front; it seems like the current strategy is to put variations into distinct files, each with the right set of `// ignore-*` directives.)

**Comment by pnkfelix** [comment]
>  (I'm not quite sure yet how best to encode the _variation_ between different targets on this front; it seems like the current strategy is to put variations into distinct files, each with the right set of `// ignore-*` directives.)

Ah, thank goodness: that is not the only strategy available. I just discovered that in addition to the usual `// CHECK:` prefix, we also have target-specific checks, like so:

https://github.com/rust-lang/rust/blob/ca983054e19afd74d63c3ed37997f3bf30fe85d0/src/test/codegen/abi-efiapi.rs#L27-L33

**Comment by apiraino** [comment]
Beta backport revisited and declined as per compiler team [on Zulip](https://rust-lang.zulipchat.com/#narrow/stream/238009-t-compiler.2Fmeetings/topic/.5Bweekly.5D.202022-06-16/near/286359638)

@rustbot label -beta-nominated

File: compiler/rustc_target/src/abi/call/aarch64.rs (hunk 2 above)
Comment (pnkfelix) [reply compiler/rustc_target/src/abi/call/aarch64.rs:33]: okay thanks for spelling this all out for me, it saved me quite a bit of time trying to double check it all myself.

File: src/test/run-make-fulldeps/issue-97463-abi-param-passing/bad.c (hunk 3 above)
[the remark this answers is not in the document]
Comment (pnkfelix) [reply src/test/run-make-fulldeps/issue-97463-abi-param-passing/bad.c:12]: `auxiliary/rust_test_helpers.c` doesn't currently include `<stdlib.h>`, which is "needed" here if we want to reproduce the original test faithfully, in that it calls `malloc`. (And given how sensitive reproducing the failure is to small changes, I'm inclined to assume that `malloc` is a necessity.)

@nagisa do you know offhand if we are deliberately trying to avoid introducing a dependence from `rust_test_helpers.c` upon `stdlib.h` and/or `malloc` itself, perhaps to ensure we can compile the file on esoteric targets that do not have that available? Just curious.

I'll keep moving forward with trying to move this test into `auxiliary/rust_test_helpers.c`, under the assumption that we *can* add such a dependence. But given the amount of work I put into getting the codegen tests working, I'm sort of inclined to just live with a run-make test here, if I encounter any hurdles on the way...

File: src/test/codegen/some-abis-do-extend-params-to-32-bits.rs [hunk 4]
```diff
@@ -0,0 +1,204 @@
+// compile-flags: -Cno-prepopulate-passes
+
+// revisions:x86_64 i686 aarch64-apple aarch64-windows aarch64-linux arm riscv
+
+//[x86_64] compile-flags: --target x86_64-unknown-uefi
+//[x86_64] needs-llvm-components:
+//[i686] compile-flags: --target i686-unknown-linux-musl
+//[i686] needs-llvm-components: i686
```
Comment (nagisa) [inline src/test/codegen/some-abis-do-extend-params-to-32-bits.rs:8]: I believe the LLVM component is called `x86` for both of the above targets.

**Review by nbdd0121 — COMMENTED** [review]
I suppose for the test it's easier to trigger with a C and Rust roundtripping:
```rust
extern "C" {
    fn return_u16() -> u16;
}

#[no_mangle]
extern "C" fn return_u32() -> u32 {
	0xdeadbeef
}

#[inline(never)]
pub fn return_u32_cvt() -> u32 {
    unsafe { return_u16() as u32 }
}

pub fn main() {
    assert_eq!(return_u32_cvt(), 0xbeef);
}
```
and 
```c
unsigned int return_u32();

unsigned short return_u16() {
    return return_u32();
}
```

File: src/test/codegen/some-abis-do-extend-params-to-32-bits.rs (hunk 4 above)
Comment (workingjubilee) [reply src/test/codegen/some-abis-do-extend-params-to-32-bits.rs:8]: Correct, as seen here:
https://github.com/rust-lang/rust/commit/493fe8008b33c576240bfa6979760e0e5482d5af

File: compiler/rustc_target/src/abi/call/aarch64.rs [hunk 5]
```diff
@@ -1,6 +1,25 @@
...
 
+/// Given integer-types M and register width N (e.g. M=u16 and N=32 bits), the
+/// `ParamExtensionPolicy` specifies how a uM value should be treated when
+/// passed via register or stack-slot of width N. See also rust-lang/rust#97463.
+#[derive(Copy, Clone, PartialEq)]
+pub enum ParamExtensionPolicy {
+    /// Indicates that when passing an i8/i16, either as a function argument or
+    /// as a return value, it must be sign-extended to 32 bits, and likewise a
+    /// u8/u16 must be zero-extended to 32-bits. (This variant is here to
+    /// accommodate Apple's deviates from the usual AArch64 ABI as defined by
```
[the remark this answers is not in the document]
Comment (pnkfelix) [reply compiler/rustc_target/src/abi/call/aarch64.rs]: done in https://github.com/rust-lang/rust/pull/97800/commits/1b288e8de7fd60a7d6f26c4e4e960d94031a8b9e

File: compiler/rustc_target/src/abi/call/aarch64.rs [hunk 6]
```diff
@@ -1,6 +1,25 @@
...
+    /// ARM.)
+    ParamsSignOrZeroExtendTo32Bits,
```
[the remark this answers is not in the document]
Comment (pnkfelix) [reply compiler/rustc_target/src/abi/call/aarch64.rs]: done in https://github.com/rust-lang/rust/pull/97800/commits/d3a19c519a5d1f292d96dda7c24d94f5bdd0719f

**Comment by pnkfelix** [comment]
At this point I don't think its worth trying to coax a regression test out of some combination of ui + `rust_test_helpers.c`.

The original test case, as captured in the run-make-fulldeps test, is *very* fragile. I managed to replicate the problem but it is very sensitive to optimization settings for *both* the C and the Rust sides of things.

(I'm leaving in the work I did on trying to encode the existing regression test in that context, but I want to make it clear here that the provided encoding does *not* suffice to expose a regression here. That is, I cherry-picked it to a build without the commit that has the fix, and the test does not fail, which means its not a sufficient regression test on its own. Making it a proper regression test might be a simple matter of compiling `rust_test_helpers.c` with optimizations turned on; it is not clear.)

If someone wants to try to come up with an end-to-end test that is significant advance over what we have today, that is fine; but that can happen in a follow up PR. It should not block landing this PR, which does have sufficient tests now in my opinion.

File: src/test/codegen/some-abis-do-extend-params-to-32-bits.rs (hunk 4 above)
Comment (pnkfelix) [reply src/test/codegen/some-abis-do-extend-params-to-32-bits.rs]: Incorporated into https://github.com/rust-lang/rust/pull/97800/commits/7913b8543e90602e98092f23be31259841671ff1

**Comment by workingjubilee** [comment]
I agree that preference should be given to landing this fix over a complete regression test, as really, certain test suites should probably verify they cover multiple optimization levels automatically and ask for opt-out rather than opt-in to specific levels of optimization testing.

File: compiler/rustc_target/src/abi/call/aarch64.rs [hunk 7]
```diff
@@ -46,13 +70,16 @@ where
...
 where
     Ty: TyAbiInterface<'a, C> + Copy,
     C: HasDataLayout,
 {
     if !arg.layout.is_aggregate() {
-        arg.extend_integer_width_to(32);
+        match param_policy {
+            ParamExtension::ExtendTo32Bits => arg.extend_integer_width_to(32),
+            ParamExtension::NoExtension => {}
+        }
```
Comment (wesleywiser) [inline compiler/rustc_target/src/abi/call/aarch64.rs:82]: Nit: I wonder if we should pull this logic into a method on `ParamExtension` instead of duplicating it at these two places?

File: src/test/run-make-fulldeps/issue-97463-abi-param-passing/param_passing.rs [hunk 8]
```diff
@@ -0,0 +1,38 @@
...
+    const C1: usize = 0x327b23c6;
+    const C2: usize = C1 & 0xFFFF;
+
+    let r1: usize = 0x0;
+    let r2: usize = C1;
+    let r3: usize = 0x0;
+    let value: u16 = unsafe { c_read_value(r1 as u32, r2 as u32, r3 as u32) };
+
+    // NOTE: as an example of the sensitivity of this test to optimization choices,
+    // uncommenting this block of code makes the bug go away on pnkfeix's machine.
```
Comment (wesleywiser) [inline src/test/run-make-fulldeps/issue-97463-abi-param-passing/param_passing.rs:20]:
```suggestion
    // uncommenting this block of code makes the bug go away on pnkfelix's machine.
```

😄

**Review by wesleywiser — APPROVED** [review]
> If someone wants to try to come up with an end-to-end test that is significant advance over what we have today, that is fine; but that can happen in a follow up PR. It should not block landing this PR, which does have sufficient tests now in my opinion.

I agree and I think we should land the fix even if the tests aren't sufficient to expose the bug. 

r=me with or without the few nits I found

File: src/test/ui/abi/issues/issue-97463-broken-abi-leaked-uninit-data.rs [hunk 9]
```diff
@@ -0,0 +1,38 @@
+// run-pass
```
Comment (wesleywiser) [inline src/test/ui/abi/issues/issue-97463-broken-abi-leaked-uninit-data.rs:1]:
```suggestion
// run-pass
// ignore-wasm
```

**Comment by wesleywiser** [comment]
Ignored test on wasm.

@bors r+

**Comment by pnkfelix** [comment]
@wesleywiser says now that PR #100260 has landed, the `// ignore-wasm` directive may now actually get respected.

@bors retry

**Comment by pnkfelix** [comment]
(I'm trying to look at this again now.)

**Comment by pnkfelix** [comment]
woot, I've replicated the problem on my AArch64 cloud desktop. So I'm pretty confident I can figure out what's up.

(With luck this will be "just" a matter of revising the test to reflect the actual expected reality.)

**Comment by matthiaskrgr** [comment]
@bors r- failed in a rollup
 https://github.com/rust-lang/rust/pull/100805#issuecomment-1221374410
 https://github.com/rust-lang-ci/rust/runs/7933052480?check_suite_focus=true#step:25:37020

File: compiler/rustc_target/src/abi/call/aarch64.rs [hunk 10]
```diff
@@ -1,6 +1,27 @@
...
+/// passed via register or stack-slot of width N. See also rust-lang/rust#97463.
+#[derive(Copy, Clone, PartialEq)]
+pub enum ParamExtension {
+    /// Indicates that when passing an i8/i16, either as a function argument or
+    /// as a return value, it must be sign-extended to 32 bits, and likewise a
+    /// u8/u16 must be zero-extended to 32-bits. (This variant is here to
+    /// accommodate Apple's deviation from the usual AArch64 ABI as defined by
+    /// ARM.)
+    ///
+    /// See also: https://developer.apple.com/documentation/xcode/writing-arm64-code-for-apple-platforms#Pass-Arguments-to-Functions-Correctly
```
Comment (wesleywiser) [inline compiler/rustc_target/src/abi/call/aarch64.rs:15]:
```suggestion
    /// See also: <https://developer.apple.com/documentation/xcode/writing-arm64-code-for-apple-platforms#Pass-Arguments-to-Functions-Correctly>
```

Comment (pnkfelix) [reply compiler/rustc_target/src/abi/call/aarch64.rs]: should we make `x.py tidy` try to catch this? Even an imperfect check from `x.py tidy` is way better than the development cycle I experienced here...

**Comment by pnkfelix** [comment]
ha ha ha ha ha this pull request is never going to land ha ha ha ha ha. 😵‍💫

File: src/test/ui/abi/issues/issue-97463-broken-abi-leaked-uninit-data.rs [hunk 11]
```diff
@@ -0,0 +1,39 @@
...
+    const C1: usize = 0x327b23c6;
+    const C2: usize = C1 & 0xFFFF;
+
+    let r1: usize = 0x0;
+    let r2: usize = C1;
+    let r3: usize = 0x0;
+    let value: u16 = unsafe { issue_97463_leak_uninit_data(r1 as u32, r2 as u32, r3 as u32) };
+
+    // NOTE: as an example of the sensitivity of this test to optimization choices,
+    // uncommenting this block of code makes the bug go away on pnkfeix's machine.
```
Comment (bjorn3) [inline src/test/ui/abi/issues/issue-97463-broken-abi-leaked-uninit-data.rs:21]: *pnkfelix
