### PR TITLE
Give a better error when `std` or `core` are missing

### LINKED ISSUE #84418: When `std` is missing the error message is very poor
A newbie Rustacean was trying to use the `gba` crate and they forgot to put `#![no_std]` in the `lib.rs` of their downstream project. The GBA uses a Tier 3 target with `build-std`, and so they landed on this error:
```
error[E0463]: can't find crate for `std`
  |
  = note: the `thumbv4t-none-eabi` target may not be installed

error: aborting due to previous error

For more information about this error, try `rustc --explain E0463`.
error: could not compile `gba-rust`
```

This is a poor experience. It's pretty vague about what went wrong, and has no suggestion of what the person can do to try and fix it.

Ideally, the error message should say something like:

> `std` is required by `cratenamehere` because it does not declare `#![no_std]`

And then the user can have at least an idea of what to investigate.

### PR DESCRIPTION
**Pull request by jyn514**
- Suggest using `rustup target add` if `RUSTUP_HOME` is set. I don't know if there's any precedent for doing this, but it seems harmless enough and it will be a big help.
- On nightly, suggest using `cargo build -Z build-std` if `CARGO` is set
- Add a note about `#![no_std]` if `std` is missing but not core
- Add a note that std may be unsupported if `std` is missing but not core

Fixes https://github.com/rust-lang/rust/issues/84418.

r? @petrochenkov

### CODE REVIEW

**Comment by jyn514** [comment]
Oh. Well. I guess there aren't any tests for missing std/core :/

**Comment by petrochenkov** [comment]
Is it possible to add a test for this?
For example using some target that is built-in, but tier 3 so it doesn't have a standard library.

File: compiler/rustc_metadata/src/locator.rs [hunk 1]
```diff
@@ -882,8 +882,28 @@ crate enum CrateError {
     NonDylibPlugin(Symbol),
 }
 
+// Used to work around a borrowck issue where the session can't be borrowed at the same time as the loader.
+crate enum LoaderOrSess<'a, 'b> {
+    Loader(&'b mut CrateLoader<'a>),
+    Session(&'b Session),
+}
```
Comment (petrochenkov) [inline compiler/rustc_metadata/src/locator.rs:889]: This looks pretty bad.
Could the resolution of `core` be moved to the call site of `err.report()` instead? (So `missing_core: bool` will be passed as a flag to `report`.)

Comment (jyn514) [reply compiler/rustc_metadata/src/locator.rs:889]: Agreed, I'm not super happy with it either.

>  Could the resolution of core be moved to the call site of err.report() instead? (So missing_core: bool will be passed as a flag to report.)

That means it will try loading `core` unconditionally on crate errors - is that ok?

Comment (petrochenkov) [reply compiler/rustc_metadata/src/locator.rs:889]: That's ok.

Of course, you can optimize and load it only in the case of `matches!(err, CrateError::LocatorCombined(..)) && crate_name != sym::core`, but it shouldn't be necessary because it only happens during erroneous compilation and `core` usually is already loaded and in the cache anyway.

Comment (jyn514) [reply compiler/rustc_metadata/src/locator.rs]: Ok, the logic is a lot simpler now :)

File: src/test/ui/resolve/missing-std.rs [hunk 2]
```diff
@@ -0,0 +1,8 @@
+// compile-flags: --target x86_64-unknown-uefi
+// rustc-env:CARGO=/usr/bin/cargo
+// rustc-env:RUSTUP_HOME=/home/bors/.rustup
+// error-pattern: can't find crate for `std`
+// error-pattern: target may not be installed
+// error-pattern: consider building the standard library from source with `cargo build -Zbuild-std`
+// error-pattern: consider downloading the target with `rustup target add x86_64-unknown-uefi`
```
Comment (petrochenkov) [inline src/test/ui/resolve/missing-std.rs:7]: Test output is predictable here, so it should be able to use regular `//~ ERROR` annotations instead of `// error-pattern`?

Also, could you move the test from `resolve` to `crate-loading`?

Comment (jyn514) [reply src/test/ui/resolve/missing-std.rs:7]: > it should be able to use regular //~ ERROR annotations instead of // error-pattern?

I used error-pattern because the error didn't have a span. But I think now that I added `#![no_std]` and `extern crate std` it should have a span and I can use `ERROR` annotations.

That also made me notice that right now I suggest using `#![no_std]` unconditionally; I switched it to only suggesting no_std if this didn't come from `extern crate std`.

> Also, could you move the test from resolve to crate-loading?

Done.

Comment (jyn514) [reply src/test/ui/resolve/missing-std.rs]: > That also made me notice that right now I suggest using #![no_std] unconditionally; I switched it to only suggesting no_std if this didn't come from extern crate std.

I'm not sure how to test this (because it requires building core but not std), but I tested locally with `-Zbuild-std=core` and it appears to work correctly:

```
$ cargo +stage1 build --target x86_64-unknown-uefi -Zbuild-std=core -q
error[E0463]: can't find crate for `std`
 --> src/main.rs:2:1
  |
2 | extern crate std;
  | ^^^^^^^^^^^^^^^^^ can't find crate
  |
  = note: the `x86_64-unknown-uefi` target may not support the standard library
  = help: consider building the standard library from source with `cargo build -Zbuild-std`
  = help: consider downloading the target with `rustup target add x86_64-unknown-uefi`
```

File: compiler/rustc_metadata/src/locator.rs [hunk 3]
```diff
@@ -1068,7 +1069,37 @@ impl CrateError {
...
+                                sess.opts.crate_name.as_deref().unwrap_or("<unknown>");
+                            err.note(&format!(
+                                "`std` is required by `{}` because it does not declare `#![no_std]`",
+                                current_crate
+                            ));
+                        }
+                        if sess.is_nightly_build() && std::env::var("CARGO").is_ok() {
+                            err.help("consider building the standard library from source with `cargo build -Zbuild-std`");
+                        }
+                        if std::env::var("RUSTUP_HOME").is_ok() {
```
Comment (petrochenkov) [inline compiler/rustc_metadata/src/locator.rs:1097]:
```suggestion
                        if missing_core && std::env::var("RUSTUP_HOME").is_ok() {
```

File: compiler/rustc_metadata/src/locator.rs [hunk 4]
```diff
@@ -1068,7 +1069,37 @@ impl CrateError {
...
+                        // If it's not a dummy, that means someone added `extern crate std` explicitly and `#![no_std]` won't help.
+                        if !missing_core && span.is_dummy() {
+                            let current_crate =
+                                sess.opts.crate_name.as_deref().unwrap_or("<unknown>");
+                            err.note(&format!(
+                                "`std` is required by `{}` because it does not declare `#![no_std]`",
+                                current_crate
+                            ));
+                        }
+                        if sess.is_nightly_build() && std::env::var("CARGO").is_ok() {
```
Comment (petrochenkov) [inline compiler/rustc_metadata/src/locator.rs:1094]:
```suggestion
                        if missing_core && sess.is_nightly_build() && std::env::var("CARGO").is_ok() {
```

File: compiler/rustc_metadata/src/locator.rs (hunk 3 above)
Comment (petrochenkov) [reply compiler/rustc_metadata/src/locator.rs:1097]: Also, this advice is more often the right solution than "consider building the standard library ...", so it should probably go first.

**Comment by petrochenkov** [comment]
Could you also squash commits after addressing the remaining comments?

File: compiler/rustc_metadata/src/locator.rs (hunk 4 above)
Comment (jyn514) [reply compiler/rustc_metadata/src/locator.rs:1094]: Hmm, I'm not sure this is correct - if you have core but not std, std could still be supported if you only built core with `-Z build-std=core`.

Comment (petrochenkov) [reply compiler/rustc_metadata/src/locator.rs:1094]: Ok.
