### PR TITLE
[NLL] Rework checking for borrows conflicting with drops

### LINKED ISSUE #53569: [nll] attr-0.1.0 regression
Found during a crater run

[Minimized reproduction](https://play.rust-lang.org/?gist=46146e256a3e138cbd42d0ee34b43571&version=nightly&mode=debug&edition=2015)

### PR DESCRIPTION
**Pull request by matthewjasper**
Previously, we would split the drop access into multiple checks for each
field of a struct/tuple/closure and through `Box` dereferences. This
changes this to check if the borrow is accessed by the drop in
`places_conflict`.

We also now handle enums containing `Drop` types.

Closes #53569

r? @nikomatsakis 
cc @pnkfelix

### CODE REVIEW

File: src/librustc_mir/borrow_check/places_conflict.rs [hunk 1]
```diff
@@ -179,16 +179,26 @@ fn place_components_conflict<'gcx, 'tcx>(
...
-                        //
-                        // I'm not sure why we are tracking these borrows - shared
-                        // references can *always* be aliased, which means the
-                        // permission check already account for this borrow.
-                        debug!("places_conflict: behind a shared ref");
+                        // Shouldn't be tracked
+                        bug!("Tracking borrow behind shared reference.");
+                    }
+                    (ProjectionElem::Deref, ty::Ref(_, _, hir::MutMutable), AccessDepth::Drop) => {
+                        // Values behind a mutatble reference are not access either by Dropping a
```
Comment (pnkfelix) [inline src/librustc_mir/borrow_check/places_conflict.rs]: nit: typo here.

File: src/test/ui/nll/enum-drop-access.rs [hunk 2]
```diff
@@ -0,0 +1,51 @@
...
+enum DropOption<T> {
+    Some(T),
+    None,
+}
+
+impl<T> Drop for DropOption<T> {
+    fn drop(&mut self) {}
+}
+
+// Dropping opt could access the value behind the reference,
```
Comment (pnkfelix) [inline src/test/ui/nll/enum-drop-access.rs]: (GIven that the type `T` has no trait bounds and the type carries no closures of type `Fn(T)`, I think this comment about whether the drop could access the value is **only** true if the code were makes use of specialization. Or at least, we used to have some complicated arguments about what `Drop` on a parametric type was actually capable of.)

Comment (pnkfelix) [reply src/test/ui/nll/enum-drop-access.rs]: But that's just me being pedantic. I have no problem with you leaving this code and comment as it stands.

**Comment by pnkfelix** [comment]
(I left some nits, but none of my critiques are worth blocking this PR. If there's a bors conflict and you happen to get a chance to fix them, then that would be great.  Or if I follow through on doing a rollup of the NLL PR's, maybe I'll adjust the typos there...)

**Comment by nnethercote** [comment]
This was a [small perf win](https://perf.rust-lang.org/compare.html?start=e5c6575801028f5e089ef2e7720aa1af9d452334&end=a072d1bca6282d1d2fbec103d12393527eb5a868&stat=instructions:u) for NLL builds.
