### PR TITLE
Preserve unused pointer to address casts

### LINKED ISSUE #97421: Pointer to integer casts that expose provenance are incorrectly removed
The pointer to integer cast has an implicit side effect of exposing the provenance, so it cannot be removed under strict provenance model.

Example of an incorrect transformation:

```rust
pub fn expose_addr<T>(a: &T) {
    a as *const T as usize;
}
```

```diff
-// MIR for `expose_addr` before SimplifyLocals
+// MIR for `expose_addr` after SimplifyLocals
 
 fn expose_addr(_1: &T) -> () {
     debug a => _1;                       // in scope 0 at a.rs:1:23: 1:24
     let mut _0: ();                      // return place in scope 0 at a.rs:1:30: 1:30
-    let _2: usize;                       // in scope 0 at a.rs:2:5: 2:27
-    let mut _3: *const T;                // in scope 0 at a.rs:2:5: 2:18
 
     bb0: {
-        _3 = &raw const (*_1);           // scope 0 at a.rs:2:5: 2:6
-        _2 = move _3 as usize (Misc);    // scope 0 at a.rs:2:5: 2:27
         return;                          // scope 0 at a.rs:3:2: 3:2
     }
 }
```

### PR DESCRIPTION
**Pull request by tmiasko**
Fixes #97421.

cc @RalfJung

### CODE REVIEW

File: compiler/rustc_middle/src/mir/mod.rs [hunk 1]
```diff
@@ -2605,9 +2605,30 @@ pub enum Rvalue<'tcx> {
...
-    pub fn is_pointer_int_cast(&self) -> bool {
-        matches!(self, Rvalue::Cast(CastKind::PointerAddress, _, _))
+    pub fn may_have_side_effects(&self) -> bool {
+        match self {
+            // Pointer to int casts may be side-effects due to exposing the provenance.
+            // While the model is undecided, we should be conservative. See
+            // <https://www.ralfj.de/blog/2022/04/11/provenance-exposed.html>
+            Rvalue::Cast(CastKind::PointerAddress, _, _) => true,
+
+            Rvalue::Use(_)
```
Comment (RalfJung) [inline compiler/rustc_middle/src/mir/mod.rs:2617]: `Use` can potentially mutate memory if it uses an `Operand::Move` (which is proposed to de-initialize the memory it reads from).
Removing a `Move` with unused result is still okay, but e.g. reordering it with other reads/writes is not if they might overlap.

File: compiler/rustc_middle/src/mir/mod.rs [hunk 2]
```diff
@@ -2605,9 +2605,30 @@ pub enum Rvalue<'tcx> {
...
+            | Rvalue::Repeat(_, _)
+            | Rvalue::Ref(_, _, _)
+            | Rvalue::ThreadLocalRef(_)
+            | Rvalue::AddressOf(_, _)
+            | Rvalue::Len(_)
+            | Rvalue::Cast(CastKind::Misc | CastKind::Pointer(_), _, _)
```
Comment (RalfJung) [inline compiler/rustc_middle/src/mir/mod.rs:2623]: Int-to-ptr casts should be considered as making a non-deterministic choice (angelically) and reading mutable machine state (namely the set of exposed provenances), which can prevent them from being reordered with other operations.

Though I assume reads from mutable machine state are fine here since otherwise `Use` would also be out entirely. So my guess is the property you care about here is "can this rvalue be removed if we don't care about the result of the computation"?

**Comment by RalfJung** [comment]
Thanks, LGTM. :)

**Comment by RalfJung** [comment]
I'm happy with the 'general' part of this PR, but cannot say if the specific changes in 3 optimizations are correct, or if they need a different notion of 'no side-effect'.

The changes in liveness and DSE are obviously not changing behavior (so at least I am sure they are not making anything less correct than it was before), but I have no idea what the `super_statement` call in 'simplify' is about.
@rust-lang/wg-mir-opt hopefully one of you can complete the review. :)

**Comment by JakobDegen** [comment]
Fwiw lgtm too, but obviously no r+ so doesn't count for much

**Comment by tmiasko** [comment]
Thanks for review @RalfJung, @JakobDegen.

@bors r=RalfJung,JakobDegen

**Comment by Dylan-DPC** [comment]
failed in [rollup ci] (https://github.com/rust-lang/rust/runs/6777182021) 

@bors r-

**Comment by tmiasko** [comment]
Rebased and updated match pattern to cover recently added cast kind.

@bors r=RalfJung,JakobDegen
