### PR TITLE
Fix suggestions for missing return type lifetime specifiers

### LINKED ISSUE #84592: Malformed suggestion for filling in multiple placeholder return lifetimes
[Playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=9e30134f99564e5092d0d3656558a43a).

I tried this code:

```rust
struct TwoLifetimes<'x, 'y> {
    x: &'x (),
    y: &'y (),
}

fn two_lifetimes_needed(a: &(), b: &()) -> TwoLifetimes<'_, '_> {
    TwoLifetimes { x: &(), y: &() }
}
```

I expected to see an error message suggesting adding a named lifetime `'a` to the returned type `TwoLifetimes<'a, 'a>`.

Instead, the suggested substitution is the malformed `TwoLifetimes<'_<'a, 'a>, '_>`.

```
error[E0106]: missing lifetime specifiers
  --> src/main.rs:11:57
   |
11 | fn two_lifetimes_needed(a: &(), b: &()) -> TwoLifetimes<'_, '_> {
   |                            ---     ---                  ^^ expected 2 lifetime parameters
   |
   = help: this function's return type contains a borrowed value, but the signature does not say whether it is borrowed from `a` or `b`
help: consider introducing a named lifetime parameter
   |
11 | fn two_lifetimes_needed<'a>(a: &'a (), b: &'a ()) -> TwoLifetimes<'_<'a, 'a>, '_> {
   |                        ^^^^    ^^^^^^     ^^^^^^                  ^^^^^^^^^^
```

The linked playground shows that the output is correct when the return type lifetimes are elided (a bare `TwoLifetimes`), and also if only one placeholder lifetime is used (`OneLifetime<'_>`).

### Meta
Reproduced on 1.53.0-nightly (2021-04-25 3709ae324c9daabbdabe), on 1.51.0 stable, and 1.47.0 stable.

### PR DESCRIPTION
**Pull request by FabianWolff**
This pull request aims to fix #84592. The issue is that the current code seems to assume that there is only a single relevant span pointing to the missing lifetime, and only looks at the first one:
https://github.com/rust-lang/rust/blob/e5f83d24aee866a14753a7cedbb4e301dfe5bef5/compiler/rustc_resolve/src/late/lifetimes.rs#L2959

This is incorrect, though, and leads to incorrect error messages and invalid suggestions. For instance, the example from #84592:
```rust
struct TwoLifetimes<'x, 'y> {
    x: &'x (),
    y: &'y (),
}

fn two_lifetimes_needed(a: &(), b: &()) -> TwoLifetimes<'_, '_> {
    TwoLifetimes { x: &(), y: &() }
}
```
currently leads to:
```
error[E0106]: missing lifetime specifiers
 --> src/main.rs:6:57
  |
6 | fn two_lifetimes_needed(a: &(), b: &()) -> TwoLifetimes<'_, '_> {
  |                            ---     ---                  ^^ expected 2 lifetime parameters
  |
  = help: this function's return type contains a borrowed value, but the signature does not say whether it is borrowed from `a` or `b`
help: consider introducing a named lifetime parameter
  |
6 | fn two_lifetimes_needed<'a>(a: &'a (), b: &'a ()) -> TwoLifetimes<'_<'a, 'a>, '_> {
  |                        ^^^^    ^^^^^^     ^^^^^^                  ^^^^^^^^^^
```
There are two problems:
- The error message is wrong. There is only _one_ lifetime parameter expected at the location pointed to by the error message (and another one at a separate location).
- The suggestion is incorrect and will not lead to correct code.

With the changes in this PR, I get the following output:
```
error[E0106]: missing lifetime specifiers
 --> p.rs:6:57
  |
6 | fn two_lifetimes_needed(a: &(), b: &()) -> TwoLifetimes<'_, '_> {
  |                            ---     ---                  ^^  ^^ expected named lifetime parameter
  |                                                         |
  |                                                         expected named lifetime parameter
  |
  = help: this function's return type contains a borrowed value, but the signature does not say whether it is borrowed from `a` or `b`
help: consider introducing a named lifetime parameter
  |
6 | fn two_lifetimes_needed<'a>(a: &'a (), b: &'a ()) -> TwoLifetimes<'a, 'a> {
  |                        ^^^^    ^^^^^^     ^^^^^^                  ^^  ^^

error: aborting due to previous error

For more information about this error, try `rustc --explain E0106`.
```
Mainly, I changed `add_missing_lifetime_specifiers_label()` to receive a _vector_ of spans (and counts) instead of just one, and adjusted its body accordingly.

### CODE REVIEW

File: compiler/rustc_resolve/src/late/diagnostics.rs [hunk 1]
```diff
@@ -1821,81 +1821,107 @@ impl<'tcx> LifetimeContext<'_, 'tcx> {
...
-            err.span_suggestion_verbose(
-                span,
-                &format!("consider using the `{}` lifetime", lifetime_names.iter().next().unwrap()),
-                formatter(name),
-                Applicability::MaybeIncorrect,
-            );
-        };
-        let suggest_new = |err: &mut DiagnosticBuilder<'_>, sugg: &str| {
+                let mut spans_suggs: Vec<_> = Vec::new();
+                for (span, fmt) in spans.iter().copied().zip(formatters.iter()) {
```
Comment (jackh726) [inline compiler/rustc_resolve/src/late/diagnostics.rs:1909]: filter_map and collect instead?

File: compiler/rustc_resolve/src/late/diagnostics.rs [hunk 2]
```diff
@@ -1821,81 +1821,107 @@ impl<'tcx> LifetimeContext<'_, 'tcx> {
...
-                    (b'a'..=b'z').map(move |c| {
-                        let mut s = '\''.to_string();
-                        s.extend(std::iter::repeat(char::from(c)).take(n));
-                        s
-                    })
-                };
+        let suggest_existing =
+            |err: &mut DiagnosticBuilder<'_>,
+             name: &str,
+             formatters: &Vec<Option<Box<dyn Fn(&str) -> String>>>| {
```
Comment (jackh726) [inline compiler/rustc_resolve/src/late/diagnostics.rs:1850]: This bothers me, but I can't think if this is the only way to do this or the best way to do this (right now)

File: compiler/rustc_resolve/src/late/diagnostics.rs [hunk 3]
```diff
@@ -1821,81 +1821,107 @@ impl<'tcx> LifetimeContext<'_, 'tcx> {
...
+                    &format!(
+                        "consider using the `{}` lifetime",
+                        lifetime_names.iter().next().unwrap()
+                    ),
+                    spans_suggs,
+                    Applicability::MaybeIncorrect,
+                    SuggestionStyle::ShowAlways,
+                );
+            };
+        let suggest_new = |err: &mut DiagnosticBuilder<'_>, suggs: &Vec<Option<String>>| {
```
Comment (jackh726) [inline compiler/rustc_resolve/src/late/diagnostics.rs:1924]: Do we have to make this an owned String here?

File: compiler/rustc_resolve/src/late/diagnostics.rs [hunk 4]
```diff
@@ -1986,77 +2018,104 @@ impl<'tcx> LifetimeContext<'_, 'tcx> {
...
+                    } else {
+                        suggs.push(None);
+                    }
+                }
+                suggest_existing(err, &name.as_str()[..], &suggs);
+            }
+            [] => {
+                let mut suggs: Vec<Option<String>> = Vec::new();
+                for (snippet, count) in snippets.iter().cloned().zip(counts.iter().copied()) {
+                    if snippet == Some("&".to_string()) {
```
Comment (jackh726) [inline compiler/rustc_resolve/src/late/diagnostics.rs:2073]: Similarly don't really like the fact that we now have to nest this. Oh well. I think a match would be cleaner still though.

File: compiler/rustc_resolve/src/late/lifetimes.rs [hunk 5]
```diff
@@ -3035,18 +3034,26 @@ impl<'a, 'tcx> LifetimeContext<'a, 'tcx> {
             }
         };
 
-        let mut err = self.report_missing_lifetime_specifiers(span, lifetime_refs.len());
+        let mut spans: Vec<_> = lifetime_refs.iter().map(|lt| lt.span).collect();
+        spans.sort();
```
Comment (jackh726) [inline compiler/rustc_resolve/src/late/lifetimes.rs:3038]: Why do we have to sort and dedup here?

**Review by jackh726 — CHANGES_REQUESTED** [review]
Initial comments

File: compiler/rustc_resolve/src/late/lifetimes.rs (hunk 5 above)
Comment (FabianWolff) [reply compiler/rustc_resolve/src/late/lifetimes.rs:3038]: My understanding is that `dedup()` only removes _consecutive_ duplicates, i.e. for full deduplication, we have to sort first.

If your question is why we have to deduplicate `spans` at all: The reason is that there can be multiple lifetimes missing in the same spot, e.g.:
```rust
struct S<'a, 'b> {
    a: &'a i32,
    b: &'b i32,
}

fn foo(a: &i32, b: &i32) -> S {todo!()}
```
```
error[E0106]: missing lifetime specifiers
 --> src/main.rs:6:29
  |
6 | fn foo(a: &i32, b: &i32) -> S {todo!()}
  |           ----     ----     ^ expected 2 lifetime parameters
```
Here, we want a _single_ error message, stating that _two_ lifetime parameters are missing at the indicated location. Therefore, we deduplicate the spans (so that only one error message is constructed) and count how many duplicates there were (so that we can say how many lifetime parameters are expected, e.g. 2 above).

File: compiler/rustc_resolve/src/late/diagnostics.rs (hunk 3 above)
Comment (FabianWolff) [reply compiler/rustc_resolve/src/late/diagnostics.rs:1924]: Yes, because we are passing in formatted strings built [here](https://github.com/FabianWolff/rust/blob/439ef6d76279268eb80e33afffafa22597e22776/compiler/rustc_resolve/src/late/diagnostics.rs#L2078-L2088) which don't live long enough to be passed by reference.

**Comment by FabianWolff** [comment]
Thanks for your suggestions, @jackh726! I have just pushed a commit addressing your comments (those that I did not reply to above).

File: compiler/rustc_resolve/src/late/diagnostics.rs [hunk 6]
```diff
@@ -1905,12 +1903,12 @@ impl<'tcx> LifetimeContext<'_, 'tcx> {
...
-                let mut spans_suggs: Vec<_> = Vec::new();
-                for (span, fmt) in spans.iter().copied().zip(formatters.iter()) {
-                    if let Some(formatter) = fmt {
-                        spans_suggs.push((span, formatter(name)));
-                    }
-                }
+                let spans_suggs: Vec<_> = formatters
+                    .into_iter()
+                    .filter_map(|fmt| fmt)
+                    .zip(spans_with_counts.iter())
```
Comment (jackh726) [inline compiler/rustc_resolve/src/late/diagnostics.rs:1909]: I'm not sure if this is right...think we need to zip *then* filter_map

File: compiler/rustc_errors/src/diagnostic.rs [hunk 7]
```diff
@@ -299,6 +299,30 @@ impl Diagnostic {
         self
     }
 
+    /// [`Diagnostic::multipart_suggestion()`] but you can set the [`SuggestionStyle`].
+    pub fn multipart_suggestion_with_style(
```
Comment (jackh726) [inline compiler/rustc_errors/src/diagnostic.rs:303]: Can you make `multipart_suggestion` call this with `SuggestionStyle::ShowCode`

File: src/test/ui/return-elided-lifetime.rs [hunk 8]
```diff
@@ -0,0 +1,37 @@
+/* Checks all four scenarios possible in report_elision_failure() of
```
Comment (jackh726) [inline src/test/ui/return-elided-lifetime.rs:1]: Maybe put this test under `src/test/ui/suggestions`?

File: src/test/ui/return-elided-lifetime.stderr [hunk 9]
```diff
@@ -0,0 +1,198 @@
...
+   |
+   = help: this function's return type contains a borrowed value, but the signature does not say whether it is borrowed from `a` or `b`
+note: these named lifetimes are available to use
+  --> $DIR/return-elided-lifetime.rs:25:7
+   |
+LL | fn f4<'a, 'b>(a: &'a i32, b: &'b i32) -> &i32 { loop {} }
+   |       ^^  ^^
+help: consider using one of the available lifetimes here
+   |
+LL | fn f4<'a, 'b>(a: &'a i32, b: &'b i32) -> &'lifetime i32 { loop {} }
```
Comment (jackh726) [inline src/test/ui/return-elided-lifetime.stderr:123]: `'lifetime`...is this preexisting? I would expect something like `'a` here?

**Review by jackh726 — CHANGES_REQUESTED** [review]
I think last comments :)

File: src/test/ui/return-elided-lifetime.stderr (hunk 9 above)
Comment (jackh726) [reply src/test/ui/return-elided-lifetime.stderr]: 👍That's what I figured.

**Review by jackh726 — APPROVED** [review]

**Comment by FabianWolff** [comment]
> @FabianWolff in the future, it's best not to tag someone in the commit message itself, because they get pinged as the commit goes through CI and such :)

Ah, I see. Sorry about that!

**Comment by jackh726** [comment]
> Ah, I see. Sorry about that!

No worries, just wanted to let you know :)
