### PR TITLE
change definitely unproductive cycles to error

### LINKED ISSUE #114: inductive cycles as ambig causes unintended breakage
```rust
pub trait Trait {
    type Item;
}

fn foo<A: Trait, B: Trait>()
where
    A::Item: Trait<Item = u32>,
    B::Item: Trait<Item = i32>,
{}
```
this should compile but fails with
```
error[E0283]: type annotations needed: cannot satisfy `<A as Trait>::Item: Trait`
 --> <source>:7:14
  |
7 |     A::Item: Trait<Item = u32>,
  |              ^^^^^^^^^^^^^^^^^
  |
```
The underlying issue is trying to prove `<A as Trait>::Item: Trait` normalizes the self type:
- `normalizes-to(<A as Trait>::Item)`
   - candidate `A::Item: Trait<Item = u32>`
     - `alias-relate(A::Item, A)`
        - `normalizes-to(<A as Trait>::Item)` inductive cycle
   - candidate `B::Item: Trait<Item = i32>`
     - `alias-relate(B::Item, A)`
        - `normalizes-to(<B as Trait>::Item)`
          - candidate `A::Item: Trait<Item = u32>`
            - `alias-relate(A::Item, B)`
              - `normalizes-to(<A as Trait>::Item)` inductive cycle
          - candidate `B::Item: Trait<Item = i32>`
            - `alias-relate(B::Item, B)`
              - `normalizes-to(<B as Trait>::Item)` inductive cycle

### PR DESCRIPTION
**Pull request by lcnr**
builds on top of #136824 by adding a third variant to `PathKind` for paths which may change to be coinductive in the future but must not be so right now. Most notably, impl where-clauses of not yet coinductive traits.

With this, we can change cycles which are definitely unproductive to a proper error. This fixes https://github.com/rust-lang/trait-system-refactor-initiative/issues/114. This does not affect stable as we keep these cycles as ambiguous during coherence.

r? @compiler-errors @nikomatsakis

### CODE REVIEW

File: compiler/rustc_type_ir/src/search_graph/mod.rs [hunk 1]
```diff
@@ -111,21 +112,29 @@ pub trait Delegate {
...
+    Unknown,
+    /// A path with at least one coinductive step. Such cycles hold.
+    Coinductive,
 }
+
 impl PathKind {
     /// Returns the path kind when merging `self` with `rest`.
     ///
     /// Given an inductive path `self` and a coinductive path `rest`,
     /// the path `self -> rest` would be coinductive.
```
Comment (compiler-errors) [inline compiler/rustc_type_ir/src/search_graph/mod.rs:132]: Note additive property of these paths

**Review by lcnr — COMMENTED** [review]
- better document `Inductive` goal sources, explain WHY that's correct and the that it's safer to be `Unknown`
- this impacts coherence, write test

**Review by compiler-errors — APPROVED** [review]
ty for the comments
