### PR TITLE
Fix unreachable_code warnings for try{} block ok-wrapped expressions

### LINKED ISSUE #54165: Misleading unreachable code warning from return in try blocks
```rust
#![feature(try_blocks)]

fn first_some() -> Option<()> {
    let _: Option<_> = try { return Some(foo()?) };
    let _: Option<_> = try { return Some(bar()?) };
    None
}
```
https://play.rust-lang.org/?gist=363157c898e0d067260e711db131b256&version=nightly&edition=2018
```
warning: unreachable expression
 --> src/main.rs:4:30
  |
4 |     let _: Option<_> = try { return Some(foo()?) };
  |                              ^^^^^^^^^^^^^^^^^^^
  |
  = note: #[warn(unreachable_code)] on by default

warning: unreachable expression
 --> src/main.rs:5:30
  |
5 |     let _: Option<_> = try { return Some(bar()?) };
  |                              ^^^^^^^^^^^^^^^^^^^
```
The desugar should probably just suppress this warning for the code it generates.

### LINKED ISSUE #63324: Incorrect `unreachable_code` lint for loops in `try_blocks`
```rust
#![feature(try_blocks)]

pub fn foo() {
    let _: Result<(), ()> = try {
        loop {
            // anything here
        }
    };
}
```
Here, the entire `loop` expression is reported unreachable, despite not being so.
This is similar to https://github.com/rust-lang/rust/issues/54165, and probably has the same underlying issue.

### PR DESCRIPTION
**Pull request by ztlpn**
Fixes #54165 and fixes #63324.

### CODE REVIEW

File: src/librustc_typeck/check/expr.rs [hunk 1]
```diff
@@ -147,8 +148,22 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
         debug!(">> type-checking: expr={:?} expected={:?}",
                expr, expected);
 
+        // If when desugaring the try block we ok-wrapped an expression that diverges
+        // (e.g. `try { return }`) then technically the ok-wrapping expression is unreachable.
+        // But since it is autogenerated code the resulting warning is confusing for the user
+        // so we want avoid generating it.
+        // Ditto for the autogenerated `Try::from_ok(())` at the end of e.g. `try { return; }`.
+        let (is_try_block_ok_wrapped_expr, is_try_block_generated_expr) = match expr.node {
+            ExprKind::Call(_, ref args) if expr.span.is_desugaring(DesugaringKind::TryBlock) => {
```
Comment (ztlpn) [inline src/librustc_typeck/check/expr.rs]: This code is rather brittle. I wonder if it would be better to just ok-wrap the whole try-block rather than the final expression.

File: src/librustc/hir/lowering/expr.rs [hunk 2]
```diff
@@ -394,30 +394,49 @@ impl LoweringContext<'_> {
...
     fn lower_expr_try_block(&mut self, body: &Block) -> hir::ExprKind {
         self.with_catch_scope(body.id, |this| {
-            let unstable_span = this.mark_span_with_reason(
+            let mut block = this.lower_block(body, true).into_inner();
+
+            let tail_expr = block.expr.take().map_or_else(
+                || {
+                    let unit_span = this.mark_span_with_reason(
+                        DesugaringKind::TryBlock,
+                        this.sess.source_map().end_point(body.span),
```
Comment (Centril) [inline src/librustc/hir/lowering/expr.rs]: Would be good to leave a comment here (and elsewhere in the method).

File: src/librustc_typeck/check/expr.rs [hunk 3]
```diff
@@ -159,13 +174,15 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
...
 
         // Warn for non-block expressions with diverging children.
-        match expr.node {
-            ExprKind::Block(..) | ExprKind::Loop(..) | ExprKind::Match(..) => {},
-            ExprKind::Call(ref callee, _) =>
-                self.warn_if_unreachable(expr.hir_id, callee.span, "call"),
-            ExprKind::MethodCall(_, ref span, _) =>
-                self.warn_if_unreachable(expr.hir_id, *span, "call"),
-            _ => self.warn_if_unreachable(expr.hir_id, expr.span, "expression"),
+        if !is_try_block_ok_wrapped_expr {
```
Comment (Centril) [inline src/librustc_typeck/check/expr.rs]: Use a guard on `ExprKind::Call` instead?

File: src/test/ui/try-block/try-block-bad-type.stderr [hunk 4]
```diff
@@ -32,18 +32,18 @@ LL |     let res: Result<i32, i32> = try { };
               found type `()`
 
 error[E0277]: the trait bound `(): std::ops::Try` is not satisfied
-  --> $DIR/try-block-bad-type.rs:17:23
+  --> $DIR/try-block-bad-type.rs:17:25
    |
 LL |     let res: () = try { };
-   |                       ^^^ the trait `std::ops::Try` is not implemented for `()`
+   |                         ^ the trait `std::ops::Try` is not implemented for `()`
```
Comment (Centril) [inline src/test/ui/try-block/try-block-bad-type.stderr]: This change in spans seems unfortunate.

Comment (ztlpn) [reply src/test/ui/try-block/try-block-bad-type.stderr]: Ok, I'll bring the old spans back, just thought it weird that the generated `from_ok` method got the span of the whole block. Of course the best span here is the one containing the type name :)

File: src/librustc/hir/lowering/expr.rs (hunk 2 above)
Comment (ztlpn) [reply src/librustc/hir/lowering/expr.rs]: Ok.

File: src/librustc_typeck/check/expr.rs (hunk 3 above)
Comment (ztlpn) [reply src/librustc_typeck/check/expr.rs]: Do you mean something like
```rust
match expr.node {
    ...
    ExprKind::Call(ref callee, _) if !expr.span.is_desugaring(DesugaringKind::TryBlock) =>
        self.warn_if_unreachable(expr.hir_id, callee.span, "call"),
    ...
}
```
?

Comment (Centril) [reply src/librustc_typeck/check/expr.rs]: Yea, that or `... if !is_try_block_ok_wrapped_expr =>`.

Comment (ztlpn) [reply src/librustc_typeck/check/expr.rs]: Well that didn't quite work because of the catch-all arm :) But it can be done with a separate arm.

File: src/librustc_typeck/check/expr.rs (hunk 1 above)
Comment (ztlpn) [reply src/librustc_typeck/check/expr.rs]: Well I tried that (desugaring `try {...}` to `{ Try::from_ok({...}) }`) and the resulting code is indeed simpler (didn't push yet). The downside is that type errors now refer to the whole block and not to the tail expression (e.g. [here](https://github.com/rust-lang/rust/blob/9b9d2aff8de4d499b4ba7ca406e000f8d3754ea7/src/test/ui/try-block/try-block-type-error.rs#L10)). Thoughts?

**Comment by Centril** [comment]
Will schedule some time over the weekend to review this some more. :)

**Comment by ztlpn** [comment]
@Centril hope you'll find some time to look at this!

**Comment by Centril** [comment]
Sorry about the delay. Finally got around to this. It looks good, thanks!

@bors r+

**Review by Centril — APPROVED** [review]

**Comment by Centril** [comment]
Failed in https://github.com/rust-lang/rust/pull/64951#issuecomment-537005090, @bors r-

(Will need to rebase to make `.node` into `.kind`.)

**Review by Centril — APPROVED** [review]
