### PR TITLE
Fix auto-hide for implementations and implementors.

### LINKED ISSUE #85411: "Auto-hide trait implementation documentation" does nothing
beta and nightly ignore the default-on configuration of "Auto-hide trait implementation documentation"

On stable [`std::future::Pending`](https://doc.rust-lang.org/stable/std/future/struct.Pending.html) looks like:

image

While [on beta](https://doc.rust-lang.org/beta/std/future/struct.Pending.html) it looks like:

image

And [on nightly](https://doc.rust-lang.org/nightly/std/future/struct.Pending.html) (as of 2021-05-17):

image

Going to https://doc.rust-lang.org/nightly/settings.html and toggling "Auto-hide trait implementation documentation" off makes stable look the same as beta, so it definitely seems like beta/nightly are just ignoring this toggle.

### PR DESCRIPTION
**Pull request by jsha**
This sets their toggles to be closed in the HTML (matching the default
setting), and opens them if the setting indicates to do so.

This distinguishes between implementations and implementors based on
being descendants of certain named elements.

Demo https://hoffman-andrews.com/rust/fix-toggle-settings/std/io/trait.Read.html#implementors
and https://hoffman-andrews.com/rust/fix-toggle-settings/std/string/struct.String.html#trait-implementations

Fixes #85411

r? @GuillaumeGomez

### CODE REVIEW

File: src/test/rustdoc/manual_impl.rs [hunk 1]
```diff
@@ -65,7 +65,7 @@ impl T for S2 {
 }
 
 // @has manual_impl/struct.S3.html '//*[@class="trait"]' 'T'
-// @has  - '//details[@open=""]/div[@class="docblock"]' 'Docs associated with the S3 trait implementation.'
+// @has  - '//details/div[@class="docblock"]' 'Docs associated with the S3 trait implementation.'
```
Comment (GuillaumeGomez) [inline src/test/rustdoc/manual_impl.rs:68]: Can you also add another check where you ensure with `@!has` the same thing but with the `@open=""` attribute please?

**Comment by GuillaumeGomez** [comment]
Also, that be nice to have a GUI test to enforce it. I can write it if you want (so then we merge this PR directly and open an issue), as your prefer.

**Comment by jsha** [comment]
If you could write the GUI test I'd appreciate it. I haven't yet learned how to make those. I'll need to learn, but I'd also like to get this regression fixed quick-ish. :-)

**Comment by GuillaumeGomez** [comment]
Then please open an issue for it. Once done, you can r=me this PR. ;)

**Comment by jsha** [comment]
Thanks! #85592

@bors r=GuillaumeGomez

**Comment by GuillaumeGomez** [comment]
Actually, it broke something. I can't wait for #84586 to be finally merged. T_T

Sending a fix...
