### PR TITLE
fix `#[loop_match]` on diverging loop

### LINKED ISSUE #144492: ICE: loop match: broken MIR: `bad assignment`
snippet:
````rust
#![feature(loop_match)]
#![crate_type = "lib"]

fn test(mut state: u8) {
    #[loop_match]
    loop {
        state = 'blk: {
            match state {
                ARRAY => dbg!(ARRAY),
            }
        }
    }
}

````

Version information
````
rustc 1.90.0-nightly (f32b23204 2025-07-26)
binary: rustc
commit-hash: f32b23204a0efe2fe8383ed4be1a30b56c1bbf94
commit-date: 2025-07-26
host: x86_64-unknown-linux-gnu
release: 1.90.0-nightly
LLVM version: 20.1.8

````

Command:
`/home/matthias/.rustup/toolchains/master/bin/rustc -Zcrate-attr=feature(loop_match)`

<details><summary><strong>Program output</strong></summary>
<p>

```
warning: the feature `loop_match` is incomplete and may not be safe to use and/or cause compiler crashes
 --> <crate attribute>:1:12
  |
1 | #![feature(loop_match)]
  |            ^^^^^^^^^^
  |
  = note: see issue #132306 <https://github.com/rust-lang/rust/issues/132306> for more information
  = note: `#[warn(incomplete_features)]` on by default

warning: unused label
 --> /tmp/icemaker_global_tempdir.Mh0izylGtxSo/rustc_testrunner_tmpdir_reporting.mzbHvU9juaja/mvce.rs:6:17
  |
6 |         state = 'blk: {
  |                 ^^^^
  |
  = note: `#[warn(unused_labels)]` on by default

warning: variable does not need to be mutable
 --> /tmp/icemaker_global_tempdir.Mh0izylGtxSo/rustc_testrunner_tmpdir_reporting.mzbHvU9juaja/mvce.rs:3:9
  |
3 | fn test(mut state: u8) {
  |         ----^^^^^
  |         |
  |         help: remove this `mut`
  |
  = note: `#[warn(unused_mut)]` on by default

warning: function `test` is never used
 --> /tmp/icemaker_global_tempdir.Mh0izylGtxSo/rustc_testrunner_tmpdir_reporting.mzbHvU9juaja/mvce.rs:3:4
  |
3 | fn test(mut state: u8) {
  |    ^^^^
  |
  = note: `#[warn(dead_code)]` on by default

warning: variable `ARRAY` should have a snake case name
 --> /tmp/icemaker_global_tempdir.Mh0izylGtxSo/rustc_testrunner_tmpdir_reporting.mzbHvU9juaja/mvce.rs:8:17
  |
8 |                 ARRAY => dbg!(ARRAY),
  |                 ^^^^^ help: convert the identifier to snake case: `array`
  |
  = note: `#[warn(non_snake_case)]` on by default

warning: 5 warnings emitted

note: no errors encountered even though delayed bugs were created

note: those delayed bugs will now be shown as internal compiler errors

error: internal compiler error: broken MIR in DefId(0:3 ~ mvce[7ffe]::test) (_2 = copy _4): bad assignment (! = u8): NoSolution
 --> /tmp/icemaker_global_tempdir.Mh0izylGtxSo/rustc_testrunner_tmpdir_reporting.mzbHvU9juaja/mvce.rs:8:26
  |
8 |                 ARRAY => dbg!(ARRAY),
  |                          ^^^^^^^^^^^
  |
note: delayed at compiler/rustc_borrowck/src/type_check/mod.rs:662:21
         0: <rustc_errors::DiagCtxtInner>::emit_diagnostic
         1: <rustc_errors::DiagCtxtHandle>::emit_diagnostic
         2: <rustc_span::ErrorGuaranteed as rustc_errors::diagnostic::EmissionGuarantee>::emit_producing_guarantee
         3: <rustc_errors::DiagCtxtHandle>::span_delayed_bug::<rustc_span::span_encoding::Span, alloc::string::String>
         4: <rustc_borrowck::type_check::TypeChecker as rustc_middle::mir::visit::Visitor>::visit_body
         5: rustc_borrowck::type_check::type_check
         6: rustc_borrowck::do_mir_borrowck
         7: rustc_borrowck::mir_borrowck
         8: rustc_query_impl::plumbing::__rust_begin_short_backtrace::<rustc_query_impl::query_impl::mir_borrowck::dynamic_query::{closure#2}::{closure#0}, rustc_middle::query::erase::Erased<[u8; 8]>>
         9: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::DynamicConfig<rustc_data_structures::vec_cache::VecCache<rustc_span::def_id::LocalDefId, rustc_middle::query::erase::Erased<[u8; 8]>, rustc_query_system::dep_graph::graph::DepNodeIndex>, false, false, false>, rustc_query_impl::plumbing::QueryCtxt, false>
        10: rustc_query_impl::query_impl::mir_borrowck::get_query_non_incr::__rust_end_short_backtrace
        11: <rustc_middle::ty::context::TyCtxt>::par_hir_body_owners::<rustc_interface::passes::run_required_analyses::{closure#1}::{closure#0}>::{closure#0}
        12: rustc_interface::passes::analysis
        13: rustc_query_impl::plumbing::__rust_begin_short_backtrace::<rustc_query_impl::query_impl::analysis::dynamic_query::{closure#2}::{closure#0}, rustc_middle::query::erase::Erased<[u8; 0]>>
        14: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::DynamicConfig<rustc_query_system::query::caches::SingleCache<rustc_middle::query::erase::Erased<[u8; 0]>>, false, false, false>, rustc_query_impl::plumbing::QueryCtxt, false>
        15: rustc_query_impl::query_impl::analysis::get_query_non_incr::__rust_end_short_backtrace
        16: rustc_interface::passes::create_and_enter_global_ctxt::<core::option::Option<rustc_interface::queries::Linker>, rustc_driver_impl::run_compiler::{closure#0}::{closure#2}>::{closure#2}::{closure#0}
        17: rustc_interface::interface::run_compiler::<(), rustc_driver_impl::run_compiler::{closure#0}>::{closure#1}
        18: std::sys::backtrace::__rust_begin_short_backtrace::<rustc_interface::util::run_in_thread_with_globals<rustc_interface::util::run_in_thread_pool_with_globals<rustc_interface::interface::run_compiler<(), rustc_driver_impl::run_compiler::{closure#0}>::{closure#1}, ()>::{closure#0}, ()>::{closure#0}::{closure#0}, ()>
        19: <<std::thread::Builder>::spawn_unchecked_<rustc_interface::util::run_in_thread_with_globals<rustc_interface::util::run_in_thread_pool_with_globals<rustc_interface::interface::run_compiler<(), rustc_driver_impl::run_compiler::{closure#0}>::{closure#1}, ()>::{closure#0}, ()>::{closure#0}::{closure#0}, ()>::{closure#1} as core::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
        20: std::sys::pal::unix::thread::Thread::new::thread_start
        21: <unknown>
        22: <unknown>
 --> /tmp/icemaker_global_tempdir.Mh0izylGtxSo/rustc_testrunner_tmpdir_reporting.mzbHvU9juaja/mvce.rs:8:26
  |
8 |                 ARRAY => dbg!(ARRAY),
  |                          ^^^^^^^^^^^
  = note: this error: internal compiler error originates in the macro `dbg` (in Nightly builds, run with -Z macro-backtrace for more info)

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: please make sure that you have updated to the latest nightly

note: rustc 1.90.0-nightly (f32b23204 2025-07-26) running on x86_64-unknown-linux-gnu

note: compiler flags: -Z crate-attr=feature(loop_match) -Z dump-mir-dir=dir

query stack during panic:
end of query stack

```

</p>
</details>

@rustbot label +F-loop_match

### LINKED ISSUE #144493: ICE: loop match: encountered `Assign((..))` with incompatible types `!` / `i32`
auto-reduced (treereduce-rust):
````rust
//@compile-flags: -Zvalidate-mir
#![feature(loop_match)]
#![crate_type = "lib"]

fn const_continue_to_block() -> u8 {
    let state = 0;
    #[loop_match]
    loop {
        state = 'blk: {
            match state {
                _ => 'b: {
                    break 'b 2;
                }
            }
        }
    }
}

````

original:
````rust
// Test that a `#[const_continue]` that breaks to a normal labeled block (that
// is not part of a `#[loop_match]`) produces an error.

#![allow(incomplete_features)]
#![feature(loop_match)]
#![crate_type = "lib"]

fn const_continue_to_block() -> u8 {
    let state = 0;
    #[loop_match]
    loop {
        state = 'blk: {
            match state {
                0 => {
                    #[const_continue]
                    break 'blk 1;
                }
                _ => 'b: {
                    #[crate_type = "lib"]
                    break 'b 2;
                    //~^ ERROR `#[const_continue]` must break to a labeled block that participates in a `#[loop_match]`
                }
            }
        }
    }
}

````

Version information
````
rustc 1.90.0-nightly (f32b23204 2025-07-26)
binary: rustc
commit-hash: f32b23204a0efe2fe8383ed4be1a30b56c1bbf94
commit-date: 2025-07-26
host: x86_64-unknown-linux-gnu
release: 1.90.0-nightly
LLVM version: 20.1.8

````

Possibly related line of code:
https://github.com/rust-lang/rust/blob/f32b23204a0efe2fe8383ed4be1a30b56c1bbf94/compiler/rustc_mir_transform/src/validate.rs#L74-L86

Command:
`/home/matthias/.rustup/toolchains/master/bin/rustc -Zvalidate-mir`

<details><summary><strong>Program output</strong></summary>
<p>

```
warning: the feature `loop_match` is incomplete and may not be safe to use and/or cause compiler crashes
 --> /tmp/icemaker_global_tempdir.NERJrGeXVE9F/rustc_testrunner_tmpdir_reporting.XYMauV5bvN5f/mvce.rs:1:12
  |
1 | #![feature(loop_match)]
  |            ^^^^^^^^^^
  |
  = note: see issue #132306 <https://github.com/rust-lang/rust/issues/132306> for more information
  = note: `#[warn(incomplete_features)]` on by default

warning: unused label
 --> /tmp/icemaker_global_tempdir.NERJrGeXVE9F/rustc_testrunner_tmpdir_reporting.XYMauV5bvN5f/mvce.rs:8:17
  |
8 |         state = 'blk: {
  |                 ^^^^
  |
  = note: `#[warn(unused_labels)]` on by default

error: internal compiler error: compiler/rustc_mir_transform/src/validate.rs:80:25: broken MIR in Item(DefId(0:3 ~ mvce[7ffe]::const_continue_to_block)) (after pass CheckForceInline) at bb2[0]:
                                encountered `Assign((_2, const 2_i32))` with incompatible types:
                                left-hand side has type: !
                                right-hand side has type: i32
  --> /tmp/icemaker_global_tempdir.NERJrGeXVE9F/rustc_testrunner_tmpdir_reporting.XYMauV5bvN5f/mvce.rs:11:30
   |
11 |                     break 'b 2;
   |                              ^


thread 'rustc' panicked at compiler/rustc_mir_transform/src/validate.rs:80:25:
Box<dyn Any>
stack backtrace:
   0:     0x769967bbc083 - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::h2e79a3b5565365ab
   1:     0x769968402d77 - core::fmt::write::hd73b6fbae87cd0cb
   2:     0x769967bb1ca3 - std::io::Write::write_fmt::he5af8bea889f5f24
   3:     0x769967bbbee2 - std::sys::backtrace::BacktraceLock::print::he742169d5c6a0e72
   4:     0x769967bbf987 - std::panicking::default_hook::{{closure}}::h4f20ca5ebdb93a0c
   5:     0x769967bbf4eb - std::panicking::default_hook::h44f7c84a44bb8706
   6:     0x769966c31323 - std[8e1e6a238be51b8a]::panicking::update_hook::<alloc[2dda5eaef825109e]::boxed::Box<rustc_driver_impl[da72802e545f2ca3]::install_ice_hook::{closure#1}>>::{closure#0}
   7:     0x769967bc01ce - std::panicking::rust_panic_with_hook::hedc500e28e47629e
   8:     0x769966c6a751 - std[8e1e6a238be51b8a]::panicking::begin_panic::<rustc_errors[877e7036bb87205d]::ExplicitBug>::{closure#0}
   9:     0x769966c5f6e6 - std[8e1e6a238be51b8a]::sys::backtrace::__rust_end_short_backtrace::<std[8e1e6a238be51b8a]::panicking::begin_panic<rustc_errors[877e7036bb87205d]::ExplicitBug>::{closure#0}, !>
  10:     0x769966c5f577 - std[8e1e6a238be51b8a]::panicking::begin_panic::<rustc_errors[877e7036bb87205d]::ExplicitBug>
  11:     0x769966c741c1 - <rustc_errors[877e7036bb87205d]::diagnostic::BugAbort as rustc_errors[877e7036bb87205d]::diagnostic::EmissionGuarantee>::emit_producing_guarantee
  12:     0x7699671e2eac - <rustc_errors[877e7036bb87205d]::DiagCtxtHandle>::span_bug::<rustc_span[eff6a45f3ede5b92]::span_encoding::Span, alloc[2dda5eaef825109e]::string::String>
  13:     0x769967276b17 - rustc_middle[b1846daf6b6bf63c]::util::bug::opt_span_bug_fmt::<rustc_span[eff6a45f3ede5b92]::span_encoding::Span>::{closure#0}
  14:     0x769967256f0a - rustc_middle[b1846daf6b6bf63c]::ty::context::tls::with_opt::<rustc_middle[b1846daf6b6bf63c]::util::bug::opt_span_bug_fmt<rustc_span[eff6a45f3ede5b92]::span_encoding::Span>::{closure#0}, !>::{closure#0}
  15:     0x769967256d7b - rustc_middle[b1846daf6b6bf63c]::ty::context::tls::with_context_opt::<rustc_middle[b1846daf6b6bf63c]::ty::context::tls::with_opt<rustc_middle[b1846daf6b6bf63c]::util::bug::opt_span_bug_fmt<rustc_span[eff6a45f3ede5b92]::span_encoding::Span>::{closure#0}, !>::{closure#0}, !>
  16:     0x769964a9f7b7 - rustc_middle[b1846daf6b6bf63c]::util::bug::span_bug_fmt::<rustc_span[eff6a45f3ede5b92]::span_encoding::Span>
  17:     0x7699657bd198 - <rustc_mir_transform[ed3e24971c04db5f]::validate::CfgChecker>::fail::<alloc[2dda5eaef825109e]::string::String>
  18:     0x7699696c7c0a - <rustc_mir_transform[ed3e24971c04db5f]::validate::Validator as rustc_mir_transform[ed3e24971c04db5f]::pass_manager::MirPass>::run_pass
  19:     0x769966472e45 - rustc_mir_transform[ed3e24971c04db5f]::pass_manager::validate_body
  20:     0x769968409e09 - rustc_mir_transform[ed3e24971c04db5f]::mir_built
  21:     0x7699684098c7 - rustc_query_impl[9907fe0a1f275b0]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[9907fe0a1f275b0]::query_impl::mir_built::dynamic_query::{closure#2}::{closure#0}, rustc_middle[b1846daf6b6bf63c]::query::erase::Erased<[u8; 8usize]>>
  22:     0x769968bd5d6e - rustc_query_system[50be2b71774c51e0]::query::plumbing::try_execute_query::<rustc_query_impl[9907fe0a1f275b0]::DynamicConfig<rustc_data_structures[54fa4801653428e4]::vec_cache::VecCache<rustc_span[eff6a45f3ede5b92]::def_id::LocalDefId, rustc_middle[b1846daf6b6bf63c]::query::erase::Erased<[u8; 8usize]>, rustc_query_system[50be2b71774c51e0]::dep_graph::graph::DepNodeIndex>, false, false, false>, rustc_query_impl[9907fe0a1f275b0]::plumbing::QueryCtxt, false>
  23:     0x769968bd57c9 - rustc_query_impl[9907fe0a1f275b0]::query_impl::mir_built::get_query_non_incr::__rust_end_short_backtrace
  24:     0x769968aa42be - rustc_mir_build[c967dd777340e99d]::check_unsafety::check_unsafety
  25:     0x769968aa401f - rustc_query_impl[9907fe0a1f275b0]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[9907fe0a1f275b0]::query_impl::check_unsafety::dynamic_query::{closure#2}::{closure#0}, rustc_middle[b1846daf6b6bf63c]::query::erase::Erased<[u8; 0usize]>>
  26:     0x769968a9cd47 - rustc_query_system[50be2b71774c51e0]::query::plumbing::try_execute_query::<rustc_query_impl[9907fe0a1f275b0]::DynamicConfig<rustc_data_structures[54fa4801653428e4]::vec_cache::VecCache<rustc_span[eff6a45f3ede5b92]::def_id::LocalDefId, rustc_middle[b1846daf6b6bf63c]::query::erase::Erased<[u8; 0usize]>, rustc_query_system[50be2b71774c51e0]::dep_graph::graph::DepNodeIndex>, false, false, false>, rustc_query_impl[9907fe0a1f275b0]::plumbing::QueryCtxt, false>
  27:     0x769968a9ca3d - rustc_query_impl[9907fe0a1f275b0]::query_impl::check_unsafety::get_query_non_incr::__rust_end_short_backtrace
  28:     0x769968bd4903 - <rustc_middle[b1846daf6b6bf63c]::ty::context::TyCtxt>::par_hir_body_owners::<rustc_interface[4e12820ca0b2e764]::passes::run_required_analyses::{closure#1}::{closure#0}>::{closure#0}
  29:     0x769968bd24d7 - rustc_interface[4e12820ca0b2e764]::passes::analysis
  30:     0x769968bd1a49 - rustc_query_impl[9907fe0a1f275b0]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[9907fe0a1f275b0]::query_impl::analysis::dynamic_query::{closure#2}::{closure#0}, rustc_middle[b1846daf6b6bf63c]::query::erase::Erased<[u8; 0usize]>>
  31:     0x76996943003c - rustc_query_system[50be2b71774c51e0]::query::plumbing::try_execute_query::<rustc_query_impl[9907fe0a1f275b0]::DynamicConfig<rustc_query_system[50be2b71774c51e0]::query::caches::SingleCache<rustc_middle[b1846daf6b6bf63c]::query::erase::Erased<[u8; 0usize]>>, false, false, false>, rustc_query_impl[9907fe0a1f275b0]::plumbing::QueryCtxt, false>
  32:     0x76996942fc04 - rustc_query_impl[9907fe0a1f275b0]::query_impl::analysis::get_query_non_incr::__rust_end_short_backtrace
  33:     0x7699694d550b - rustc_interface[4e12820ca0b2e764]::passes::create_and_enter_global_ctxt::<core[527c20722825abac]::option::Option<rustc_interface[4e12820ca0b2e764]::queries::Linker>, rustc_driver_impl[da72802e545f2ca3]::run_compiler::{closure#0}::{closure#2}>::{closure#2}::{closure#0}
  34:     0x7699696abd1e - rustc_interface[4e12820ca0b2e764]::interface::run_compiler::<(), rustc_driver_impl[da72802e545f2ca3]::run_compiler::{closure#0}>::{closure#1}
  35:     0x7699695652c1 - std[8e1e6a238be51b8a]::sys::backtrace::__rust_begin_short_backtrace::<rustc_interface[4e12820ca0b2e764]::util::run_in_thread_with_globals<rustc_interface[4e12820ca0b2e764]::util::run_in_thread_pool_with_globals<rustc_interface[4e12820ca0b2e764]::interface::run_compiler<(), rustc_driver_impl[da72802e545f2ca3]::run_compiler::{closure#0}>::{closure#1}, ()>::{closure#0}, ()>::{closure#0}::{closure#0}, ()>
  36:     0x769969564fa2 - <<std[8e1e6a238be51b8a]::thread::Builder>::spawn_unchecked_<rustc_interface[4e12820ca0b2e764]::util::run_in_thread_with_globals<rustc_interface[4e12820ca0b2e764]::util::run_in_thread_pool_with_globals<rustc_interface[4e12820ca0b2e764]::interface::run_compiler<(), rustc_driver_impl[da72802e545f2ca3]::run_compiler::{closure#0}>::{closure#1}, ()>::{closure#0}, ()>::{closure#0}::{closure#0}, ()>::{closure#1} as core[527c20722825abac]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  37:     0x76996956af7d - std::sys::pal::unix::thread::Thread::new::thread_start::h511a30c1a1da8f57
  38:     0x769962ea57eb - <unknown>
  39:     0x769962f2918c - <unknown>
  40:                0x0 - <unknown>

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: please make sure that you have updated to the latest nightly

note: rustc 1.90.0-nightly (f32b23204 2025-07-26) running on x86_64-unknown-linux-gnu

note: compiler flags: -Z validate-mir -Z dump-mir-dir=dir

query stack during panic:
#0 [mir_built] building MIR for `const_continue_to_block`
#1 [check_unsafety] unsafety-checking `const_continue_to_block`
#2 [analysis] running analysis passes on this crate
end of query stack
error: aborting due to 1 previous error; 2 warnings emitted


```

</p>
</details>

@rustbot label +F-loop_match +-Zvalidate-mir

### PR DESCRIPTION
**Pull request by folkertdev**
tracking issue: https://github.com/rust-lang/rust/issues/132306

fixes https://github.com/rust-lang/rust/issues/144492
fixes https://github.com/rust-lang/rust/issues/144493

fixes https://github.com/rust-lang/rust/issues/144781

this generated invalid MIR before. issue https://github.com/rust-lang/rust/issues/143806 still has an issue where we assign `state = state` which is invalid in MIR. Fixing that problem is tricky, so I'd like to do that separately.

r? @bjorn3

### CODE REVIEW

File: tests/ui/loop-match/diverges.rs [hunk 1]
```diff
@@ -0,0 +1,44 @@
+//@ build-pass
+//@compile-flags: -Zvalidate-mir
```
Comment (bjorn3) [inline tests/ui/loop-match/diverges.rs]:
```suggestion
//@ compile-flags: -Zvalidate-mir

```
nit

**Comment by bjorn3** [comment]
r? compiler

given that this was debugged by the both of us.

**Comment by folkertdev** [comment]
I guess but also we have all the context here, it's a one-liner, and has no consequences outside of loop-match code.

File: compiler/rustc_mir_build/src/builder/expr/into.rs [hunk 2]
```diff
@@ -295,9 +295,11 @@ impl<'a, 'tcx> Builder<'a, 'tcx> {
                     this.diverge_from(loop_block);
 
                     // Logic for `match`.
-                    let scrutinee_place_builder =
-                        unpack!(body_block = this.as_place_builder(body_block, scrutinee));
                     let scrutinee_span = this.thir.exprs[scrutinee].span;
+                    let scrutinee_place_builder = unpack!(
+                        body_block = this.lower_scrutinee(body_block, scrutinee, scrutinee_span)
+                    );
+
```
Comment (folkertdev) [inline compiler/rustc_mir_build/src/builder/expr/into.rs:302]: this change adds a place mention of the scrutinee that was missing before.

File: tests/ui/loop-match/diverges.rs
Comment (cjgillot) [inline tests/ui/loop-match/diverges.rs:1]: Do you mind making some of those tests MIR building tests? In `tests/mir-opt/building`.

**Review by SparrowLii — COMMENTED** [review]
LGTM

*[View changes since this review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/rust/144783/8712e4567551a2714efa66dac204ec7137bc5605..3e76b58453461a7ac04db4914caff584345d8448)*
