### PR TITLE
Don't emit delayed good-path bugs on panic

### LINKED ISSUE #117381: "no warnings or errors encountered even though `delayed_good_path_bugs` issued" after panic
I'm getting a panic
```
thread 'rustc' panicked at compiler/rustc_ty_utils/src/abi.rs:360:21:
`PassMode::Direct` for aggregates only allowed on wasm and `extern "ptx-kernel"` fns
Problematic type: TyAndLayout {
    ty: ReprC1<*const i32>,
...
```
(that's expected, I'm working on that part of the compiler)
and after that I am getting a second error
```
error: internal compiler error: no warnings or errors encountered even though `delayed_good_path_bugs` issued

error: internal compiler error: trimmed_def_paths constructed but no error emitted; use `DelayDm` for lints or `with_no_trimmed_paths` for debugging
```
That's bad, it makes the panic message harder to find. It's also wrong, there was an error encountered, a panic even!

Cc @compiler-errors  -- that's one of the trimmed-path issues I encountered recently (but might be unrelated to https://github.com/rust-lang/rust/pull/117373)

### PR DESCRIPTION
**Pull request by compiler-errors**
This should fix #117381, cc @RalfJung

As opposed to delayed bugs, delayed *good path* bugs really don't make sense to show on panics.

### CODE REVIEW

File: compiler/rustc_errors/src/lib.rs [hunk 1]
```diff
@@ -556,7 +556,7 @@ impl Drop for HandlerInner {
         // instead of "require some error happened". Sadly that isn't ideal, as
         // lints can be `#[allow]`'d, potentially leading to this triggering.
         // Also, "good path" should be replaced with a better naming.
-        if !self.has_any_message() && !self.suppressed_expected_diag {
+        if !self.has_any_message() && !self.suppressed_expected_diag && !std::thread::panicking() {
```
Comment (RalfJung) [inline compiler/rustc_errors/src/lib.rs:559]: It might make sense to also add this at delayed_span_bugs? When there's a panic, I'm much more likely to be interested in the panic than the delayed bug. The delayed bug is actually not a bug if compilation stops with an error later -- they are used for cases where "if this happens we must never produce an output file, but we can't `bug!` here and now since compilation continues when an error was found, to report more than one error at a time". In those cases, when a panic occurred, all is good -- no output file is produced, after all.

Comment (compiler-errors) [reply compiler/rustc_errors/src/lib.rs:559]: I'm gonna leave that up to another PR.

I actually slighlty disagree, or at least think it needs a bit more nuance than the delayed_good_path_bug case -- I think that *some* delayed span bugs are noise (e.g. dropping opaque type storage), but some others are actually pretty important in understanding why the compiler got so messed up that it's now panicking (e.g. diagnostics that are `.delay_as_bug()`'d).
