### PR TITLE
rustdoc: Resolve module-level doc references more locally

### LINKED ISSUE #55364: rustdoc intra links: Module-level doc uses parent module's namespace instead of own
```Rust
pub mod sub {
    //! See either [foo] or [bar].

    /// See [bar]
    pub fn foo() {}
    /// See [foo]
    pub fn bar() {}
}
```
```
2 |     //! See either [foo] or [bar].
  |                     ^^^ cannot be resolved, ignoring
```

I don't know if this is an accidental regression, or an intentional change, but this used to resolve.

I argue that module-level docs should have the same namespace as the module they are referring to, since referring to the items of the documented module is much more common than referring to items in the parent module.

Ref #43466

### PR DESCRIPTION
**Pull request by kinnison**
Module level docs should resolve intra-doc links as locally as
possible.  As such, this commit alters the heuristic for finding
intra-doc links such that we attempt to resolve names mentioned
in *inner* documentation comments within the (sub-)module rather
that from the context of its parent.

I'm hoping that this fixes #55364 though right now I'm not sure it's the right fix.

r? @GuillaumeGomez

### CODE REVIEW

**Comment by kinnison** [comment]
Given where the code is, is it worth @QuietMisdreavus or @Manishearth reviewing this?

**Comment by GuillaumeGomez** [comment]
With this change, I'm afraid it might not find items located in the parents. Could you provide tests alongside please? (we should have added them from the start...)

> Given where the code is, is it worth @QuietMisdreavus or @Manishearth reviewing this?

Their opinion would be very valuable indeed!

**Comment by kinnison** [comment]
> With this change, I'm afraid it might not find items located in the parents. Could you provide tests alongside please? (we should have added them from the start...)

I 100% agree with the need for tests, but I'm unsure about how the rustdoc tests quite work -- all the `@has` stuff.

If you can give me an example of what you mean by "not find items located in the parents" in terms of an example bit of Rust, I'll add tests for the stuff in the original issue, and also your test cases.  I'm fairly sure that all the existing stuff passes though.

**Comment by kinnison** [comment]
I found `htmldocck.py` and have written what I hope is a reasonable test so far.  Further guidance gratefully received.

File: src/test/rustdoc/issue-55364.rs [hunk 1]
```diff
@@ -0,0 +1,50 @@
+// @has issue_55364/index.html
+// @has - '//a[@class="mod"]' 'subone'
+// @has issue_55364/subone/index.html
+// These foo/bar links should refer inside `subone`
+// @has - '//div[@class="docblock"]//a/@href' 'subone/fn.foo.html'
```
Comment (GuillaumeGomez) [inline src/test/rustdoc/issue-55364.rs]: To check an attribute, we use: `//a[@href="...]`. However, I wonder if the current check is working...

**Comment by GuillaumeGomez** [comment]
The test looks good but I'd feel more at ease if you used the syntax I provided you to check the href. :)

Also, do you mind checking with bigger modules levels (like 4 or even 5 levels down?). Thanks in advance!

File: src/test/rustdoc/issue-55364.rs (hunk 1 above)
Comment (kinnison) [reply src/test/rustdoc/issue-55364.rs]: I've managed to change this to look like:

```suggestion
// @has - '//div[@class="docblock"]//a[@href="../../issue_55364/subone/fn.foo.html"]' 'foo'
```

Is that the sort of thing you were hoping for?

**Comment by kinnison** [comment]
@GuillaumeGomez To ease review I've pushed two fixup commits.  The first changes the XPATHs the way you asked for (and I think they're better this way yes, so thank you).  The second adds a five level deep submodule set which refers to sibling modules by means of `crate::` and `super::super...` names to try and cover all bases.

Any other tests you'd like me to add?  I'm quite liking the `htmldocck.py` stuff now.

**Comment by kinnison** [comment]
The third fixup is just to quiet `tidy` which I didn't realise also ran against test code.

Once things look good, I'll obviously rebase these into a nice commit.

**Review by Manishearth — APPROVED** [review]
r=me with a comment explaining what base_node is

File: src/librustdoc/passes/collect_intra_doc_links.rs [hunk 2]
```diff
@@ -322,9 +322,26 @@ impl<'a, 'tcx> DocFolder for LinkCollector<'a, 'tcx> {
                     continue;
                 }
 
+                // In order to correctly resolve intra-doc-links we need to
```
Comment (GuillaumeGomez) [inline src/librustdoc/passes/collect_intra_doc_links.rs]: Thanks a lot for this comment, this is very helpful!

File: src/test/rustdoc/issue-55364.rs [hunk 3]
```diff
@@ -0,0 +1,69 @@
+// @has issue_55364/index.html
+// @has - '//a[@class="mod"]' 'subone'
+// @has issue_55364/subone/index.html
+// These foo/bar links should refer inside `subone`
+// @has - '//div[@class="docblock"]//a[@href="../../issue_55364/subone/fn.foo.html"]' 'foo'
```
Comment (GuillaumeGomez) [inline src/test/rustdoc/issue-55364.rs]: This check is a bit too generic. Elements such as functions/methods or anything **have** a class/id, please use it so we are sure the link is where it should.

Comment (GuillaumeGomez) [reply src/test/rustdoc/issue-55364.rs]: Oh also you might need `// ignore-tidy-linelength` at some point (it's limited to 100 chars and I think you'll overpass it).

Comment (GuillaumeGomez) [reply src/test/rustdoc/issue-55364.rs]: And to specify [`String::from_utf16`](https://doc.rust-lang.org/nightly/std/string/struct.String.html#method.from_utf16), you can use this xpath: `//h4[@id=method.from_utf16"]`. However I just realised that docblocks aren't embedded into the element (I should finish that experiment some day...).

Comment (GuillaumeGomez) [reply src/test/rustdoc/issue-55364.rs]: Ok, explanation about `@has`. The argument right after it (`-` in most cases) is the file (and `-` means "same as previously set). Please replace it when required. For example, for modules, please refer to their file precisely.

File: src/librustdoc/passes/collect_intra_doc_links.rs (hunk 2 above)
Comment (kinnison) [reply src/librustdoc/passes/collect_intra_doc_links.rs]: You're welcome :D

File: src/test/rustdoc/issue-55364.rs (hunk 3 above)
Comment (kinnison) [reply src/test/rustdoc/issue-55364.rs]: Thanks for that, it was helpful.  I have now pushed a squashed commit where I've made the selectors as specific as I can.  I fear any more specific and they'll start to depend on the exact rendering of markdown which isn't really what we're testing here.

File: src/test/rustdoc/issue-55364.rs [hunk 4]
```diff
@@ -0,0 +1,85 @@
+// ignore-tidy-linelength
+
+// First check the four top level modules are present
+// @has issue_55364/index.html
+// @has - '//section[@id="main"]/table//tr[@class="module-item"]/td/a[@class="mod"][@href="subone/index.html"]' 'subone'
```
Comment (GuillaumeGomez) [inline src/test/rustdoc/issue-55364.rs]: I think that checking if the modules are present is a bit too much. :)

File: src/test/rustdoc/issue-55364.rs [hunk 5]
```diff
@@ -0,0 +1,85 @@
...
+// Now a module with inner documentation
+
+// @has issue_55364/subone/index.html
+// These foo/bar links in the module's documentation should refer inside `subone`
+// @has - '//section[@id="main"]/div[@class="docblock"]//a[@href="../../issue_55364/subone/fn.foo.html"]' 'foo'
+// @has - '//section[@id="main"]/div[@class="docblock"]//a[@href="../../issue_55364/subone/fn.bar.html"]' 'bar'
+pub mod subone {
+    //! See either [foo] or [bar].
+
+    /// See [bar]
```
Comment (GuillaumeGomez) [inline src/test/rustdoc/issue-55364.rs]: Can you check for those two functions too please?

File: src/test/rustdoc/issue-55364.rs [hunk 6]
```diff
@@ -0,0 +1,85 @@
...
+// @has - '//section[@id="main"]/div[@class="docblock"]//a[@href="../../issue_55364/fn.foo.html"]' 'foo'
+// @has - '//section[@id="main"]/div[@class="docblock"]//a[@href="../../issue_55364/fn.bar.html"]' 'bar'
+// Though there should be such links later
+// @has - '//section[@id="main"]/table//tr[@class="module-item"]/td/a[@class="fn"][@href="fn.foo.html"]' 'foo'
+// @has - '//section[@id="main"]/table//tr[@class="module-item"]/td/a[@class="fn"][@href="fn.bar.html"]' 'bar'
+/// See either [foo] or [bar].
+pub mod subtwo {
+
+    /// See [bar]
+    pub fn foo() {}
```
Comment (GuillaumeGomez) [inline src/test/rustdoc/issue-55364.rs]: Can you check for those two functions too please?

File: src/test/rustdoc/issue-55364.rs [hunk 7]
```diff
@@ -0,0 +1,85 @@
...
+    /// See [foo]
+    pub fn bar() {}
+}
+
+// These are the function referred to by the module above with outer docs
+
+// @has issue_55364/index.html
+// These two functions should refer to each other
+// @has - '//section[@id="main"]/table//a[@href="fn.foo.html"]' 'foo'
```
Comment (GuillaumeGomez) [inline src/test/rustdoc/issue-55364.rs]: You're currently checking that the module has a function url. Functions have pages on their own as well. For example: https://doc.rust-lang.org/nightly/std/mem/fn.drop.html

Please update your test to check for the functions' doc and not if the module has a link to the function. :)

File: src/test/rustdoc/issue-55364.rs (hunk 4 above)
Comment (kinnison) [reply src/test/rustdoc/issue-55364.rs]: Fair, I'll take these out.

File: src/test/rustdoc/issue-55364.rs (hunk 5 above)
Comment (kinnison) [reply src/test/rustdoc/issue-55364.rs]: I've added checks that these functions refer to one another inside `subone`

File: src/test/rustdoc/issue-55364.rs (hunk 6 above)
Comment (kinnison) [reply src/test/rustdoc/issue-55364.rs]: I've added checks that these two refer to one another inside `subtwo` despite the module itself referring to the outer foo/bar.

File: src/test/rustdoc/issue-55364.rs (hunk 7 above)
Comment (kinnison) [reply src/test/rustdoc/issue-55364.rs]: I figure given the above two tests, I can just remove these particular checks.  Is that okay?

**Comment by GuillaumeGomez** [comment]
Thanks a lot!

@bors: r=Manisheart,GuillaumeGomez
