### PR TITLE
Fix normalization overflow ICEs in monomorphization

### LINKED ISSUE #92004: ICE when working with infinitely nesting types and ?-operator
### Code

I've hacked it down from an advent of code solution. When 

```Rust
    let version = extend_number(0, itr, 3)?;
    let type_id = extend_number(0, itr, 3)?;
```

is replaced with u32 literals the compiler emits a (correct) compilation error due to infinitely nesting types.

```Rust
use std::vec::Vec;
use std::iter::Peekable;

pub fn main() {
    let packet = decode(vec![1,0,1,0]);
}

pub fn decode(bitstream: Vec<u64>) -> Packet {
    let mut bitstream_itr = bitstream.into_iter().peekable();
    return match decode_packet(&mut bitstream_itr) {
        Some(p) => p,
        None    => panic!("expected outer packet"),
    }
}

pub fn decode_packets<I: Iterator<Item = u64>>(itr: &mut Peekable<I>) -> Vec<Packet> {
    let mut res = Vec::new();
    loop {
        match decode_packet(itr) {
            Some(p) => { res.push(p); },
            None    => break
        }
    }

    return res;
}

pub fn decode_packet<I: Iterator<Item = u64>>(itr: &mut Peekable<I>) -> Option<Packet> {
    // get version digits
    let version = extend_number(0, itr, 3)?;
    let type_id = extend_number(0, itr, 3)?;
    return operator_packet(version, type_id, itr);
}

pub fn operator_packet<I: Iterator<Item = u64>>(version: u64, type_id: u64, itr: &mut Peekable<I>) -> Option<Packet> {
    let p = OperatorPacket {
        version: version,
        type_id: type_id,
        packets: decode_packets(&mut itr.take(0).peekable()),
    };

    return Some(Packet::Operator(p));
}

pub fn extend_number<I: Iterator<Item = u64>>(num: u64, itr: &mut Peekable<I>, take: u64) -> Option<u64> {
    let mut value = num;
    for _ in 0..take {
        value *= 2;
        value += itr.next()?;
    }

    return Some(value);
}

#[derive(Debug)]
pub enum Packet {
    Operator(OperatorPacket),
}

#[derive(Debug)]
pub struct OperatorPacket {
    version: u64,
    type_id: u64,
    packets: Vec<Packet>
}
```

### Meta

`rustc --version --verbose`:
```
rustc 1.59.0-nightly (db9d361a4 2021-11-28)
binary: rustc
commit-hash: db9d361a4731ca0bb48533fab6297a8fea75696f
commit-date: 2021-11-28
host: aarch64-apple-darwin
release: 1.59.0-nightly
LLVM version: 13.0.0
```

### Error output

```
thread 'rustc' panicked at 'index out of bounds: the len is 0 but the index is 0', /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/ena-0.14.0/src/snapshot_vec.rs:199:10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.59.0-nightly (db9d361a4 2021-11-28) running on aarch64-apple-darwin

note: compiler flags: -C embed-bitcode=no -C split-debuginfo=unpacked -C debuginfo=2 -C incremental --crate-type bin

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [is_copy_raw] computing whether `core::option::Option<core::option::Option<_>>` is `Copy`
#1 [needs_drop_raw] computing whether `core::option::Option<core::option::Option<_>>` needs drop
end of query stack
warning: `aoc-uh-oh` (bin "aoc-uh-oh") generated 4 warnings
error: could not compile `aoc-uh-oh`; 4 warnings emitted
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
stack backtrace:
   0: _rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::panicking::panic_bounds_check
   3: <rustc_infer::infer::type_variable::TypeVariableTable>::probe
   4: <rustc_infer::infer::InferCtxt>::probe_ty_var
   5: <rustc_infer::infer::canonical::canonicalizer::Canonicalizer as rustc_middle::ty::fold::TypeFolder>::fold_ty
   6: <&rustc_middle::ty::list::List<rustc_middle::ty::subst::GenericArg> as rustc_middle::ty::fold::TypeFoldable>::fold_with::<rustc_infer::infer::canonical::canonicalizer::Canonicalizer>
   7: <&rustc_middle::ty::TyS as rustc_middle::ty::fold::TypeFoldable>::super_fold_with::<rustc_infer::infer::canonical::canonicalizer::Canonicalizer>
   8: <&rustc_middle::ty::list::List<rustc_middle::ty::subst::GenericArg> as rustc_middle::ty::fold::TypeFoldable>::fold_with::<rustc_infer::infer::canonical::canonicalizer::Canonicalizer>
   9: <&rustc_middle::ty::TyS as rustc_middle::ty::fold::TypeFoldable>::super_fold_with::<rustc_infer::infer::canonical::canonicalizer::Canonicalizer>
  10: <&rustc_middle::ty::list::List<rustc_middle::ty::subst::GenericArg> as rustc_middle::ty::fold::TypeFoldable>::fold_with::<rustc_infer::infer::canonical::canonicalizer::Canonicalizer>
  11: <rustc_middle::ty::PredicateKind as rustc_middle::ty::fold::TypeFoldable>::fold_with::<rustc_infer::infer::canonical::canonicalizer::Canonicalizer>
  12: <rustc_infer::infer::canonical::canonicalizer::Canonicalizer>::canonicalize::<rustc_middle::ty::ParamEnvAnd<rustc_middle::ty::Predicate>>
  13: <rustc_infer::infer::InferCtxt as rustc_trait_selection::traits::query::evaluate_obligation::InferCtxtExt>::evaluate_obligation
  14: <rustc_infer::infer::InferCtxt as rustc_trait_selection::traits::query::evaluate_obligation::InferCtxtExt>::evaluate_obligation_no_overflow
  15: rustc_trait_selection::traits::type_known_to_meet_bound_modulo_regions
  16: <rustc_infer::infer::InferCtxtBuilder>::enter::<bool, rustc_ty_utils::common_traits::is_item_raw::{closure#0}>
  17: rustc_ty_utils::common_traits::is_copy_raw
  18: <rustc_query_system::dep_graph::graph::DepGraph<rustc_middle::dep_graph::dep_node::DepKind>>::with_task::<rustc_middle::ty::context::TyCtxt, rustc_middle::ty::ParamEnvAnd<&rustc_middle::ty::TyS>, bool>
  19: rustc_data_structures::stack::ensure_sufficient_stack::<(bool, rustc_query_system::dep_graph::graph::DepNodeIndex), rustc_query_system::query::plumbing::execute_job<rustc_query_impl::plumbing::QueryCtxt, rustc_middle::ty::ParamEnvAnd<&rustc_middle::ty::TyS>, bool>::{closure#3}>
  20: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::plumbing::QueryCtxt, rustc_query_system::query::caches::DefaultCache<rustc_middle::ty::ParamEnvAnd<&rustc_middle::ty::TyS>, bool>>
  21: rustc_query_system::query::plumbing::get_query::<rustc_query_impl::queries::is_copy_raw, rustc_query_impl::plumbing::QueryCtxt>
  22: <rustc_middle::ty::TyS>::is_copy_modulo_regions
  23: rustc_ty_utils::needs_drop::needs_drop_raw
  24: <rustc_query_system::dep_graph::graph::DepGraph<rustc_middle::dep_graph::dep_node::DepKind>>::with_task::<rustc_middle::ty::context::TyCtxt, rustc_middle::ty::ParamEnvAnd<&rustc_middle::ty::TyS>, bool>
  25: rustc_data_structures::stack::ensure_sufficient_stack::<(bool, rustc_query_system::dep_graph::graph::DepNodeIndex), rustc_query_system::query::plumbing::execute_job<rustc_query_impl::plumbing::QueryCtxt, rustc_middle::ty::ParamEnvAnd<&rustc_middle::ty::TyS>, bool>::{closure#3}>
  26: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::plumbing::QueryCtxt, rustc_query_system::query::caches::DefaultCache<rustc_middle::ty::ParamEnvAnd<&rustc_middle::ty::TyS>, bool>>
  27: rustc_query_system::query::plumbing::get_query::<rustc_query_impl::queries::needs_drop_raw, rustc_query_impl::plumbing::QueryCtxt>
  28: rustc_ty_utils::instance::inner_resolve_instance
  29: rustc_ty_utils::instance::resolve_instance
  30: <rustc_middle::dep_graph::dep_node::DepKind as rustc_query_system::dep_graph::DepKind>::with_deps::<<rustc_query_system::dep_graph::graph::DepGraph<rustc_middle::dep_graph::dep_node::DepKind>>::with_task_impl<rustc_middle::ty::context::TyCtxt, rustc_middle::ty::ParamEnvAnd<(rustc_span::def_id::DefId, &rustc_middle::ty::list::List<rustc_middle::ty::subst::GenericArg>)>, core::result::Result<core::option::Option<rustc_middle::ty::instance::Instance>, rustc_errors::ErrorReported>>::{closure#0}, core::result::Result<core::option::Option<rustc_middle::ty::instance::Instance>, rustc_errors::ErrorReported>>
  31: <rustc_query_system::dep_graph::graph::DepGraph<rustc_middle::dep_graph::dep_node::DepKind>>::with_task::<rustc_middle::ty::context::TyCtxt, rustc_middle::ty::ParamEnvAnd<(rustc_span::def_id::DefId, &rustc_middle::ty::list::List<rustc_middle::ty::subst::GenericArg>)>, core::result::Result<core::option::Option<rustc_middle::ty::instance::Instance>, rustc_errors::ErrorReported>>
  32: rustc_data_structures::stack::ensure_sufficient_stack::<(core::result::Result<core::option::Option<rustc_middle::ty::instance::Instance>, rustc_errors::ErrorReported>, rustc_query_system::dep_graph::graph::DepNodeIndex), rustc_query_system::query::plumbing::execute_job<rustc_query_impl::plumbing::QueryCtxt, rustc_middle::ty::ParamEnvAnd<(rustc_span::def_id::DefId, &rustc_middle::ty::list::List<rustc_middle::ty::subst::GenericArg>)>, core::result::Result<core::option::Option<rustc_middle::ty::instance::Instance>, rustc_errors::ErrorReported>>::{closure#3}>
  33: rustc_query_system::query::plumbing::get_query::<rustc_query_impl::queries::resolve_instance, rustc_query_impl::plumbing::QueryCtxt>
  34: <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::resolve_instance
  35: <rustc_middle::ty::instance::Instance>::resolve_opt_const_arg
  36: <rustc_middle::ty::instance::Instance>::resolve_drop_in_place
  37: <rustc_monomorphize::collector::MirNeighborCollector as rustc_middle::mir::visit::Visitor>::visit_terminator
  38: rustc_monomorphize::collector::collect_neighbours
  39: rustc_monomorphize::collector::collect_items_rec
  40: rustc_monomorphize::collector::collect_items_rec
  41: rustc_monomorphize::collector::collect_items_rec
  42: rustc_monomorphize::collector::collect_items_rec
  43: rustc_monomorphize::collector::collect_items_rec
  44: rustc_monomorphize::collector::collect_items_rec
  45: rustc_monomorphize::collector::collect_items_rec
  46: rustc_monomorphize::collector::collect_items_rec
  47: rustc_monomorphize::collector::collect_items_rec
  48: rustc_monomorphize::collector::collect_items_rec
  49: rustc_monomorphize::collector::collect_items_rec
  50: rustc_monomorphize::collector::collect_items_rec
  51: rustc_monomorphize::collector::collect_items_rec
  52: rustc_monomorphize::collector::collect_items_rec
  53: rustc_monomorphize::collector::collect_items_rec
  54: rustc_monomorphize::collector::collect_items_rec
  55: rustc_monomorphize::collector::collect_items_rec
  56: rustc_monomorphize::collector::collect_items_rec
  57: rustc_monomorphize::collector::collect_items_rec
  58: rustc_monomorphize::collector::collect_items_rec
  59: rustc_monomorphize::collector::collect_items_rec
  60: rustc_monomorphize::collector::collect_items_rec
  61: rustc_monomorphize::collector::collect_items_rec
  62: rustc_monomorphize::collector::collect_items_rec
  63: rustc_monomorphize::collector::collect_items_rec
  64: rustc_monomorphize::collector::collect_items_rec
  65: rustc_monomorphize::collector::collect_items_rec
  66: rustc_monomorphize::collector::collect_items_rec
  67: rustc_monomorphize::collector::collect_items_rec
  68: rustc_monomorphize::collector::collect_items_rec
  69: rustc_monomorphize::collector::collect_items_rec
  70: rustc_monomorphize::collector::collect_items_rec
  71: rustc_monomorphize::collector::collect_items_rec
  72: rustc_monomorphize::collector::collect_items_rec
  73: rustc_monomorphize::collector::collect_items_rec
  74: rustc_monomorphize::collector::collect_items_rec
  75: rustc_monomorphize::collector::collect_items_rec
  76: rustc_monomorphize::collector::collect_items_rec
  77: rustc_monomorphize::collector::collect_items_rec
  78: rustc_monomorphize::collector::collect_items_rec
  79: rustc_monomorphize::collector::collect_items_rec
  80: rustc_monomorphize::collector::collect_items_rec
  81: rustc_monomorphize::collector::collect_items_rec
  82: rustc_monomorphize::collector::collect_items_rec
  83: rustc_monomorphize::collector::collect_items_rec
  84: rustc_monomorphize::collector::collect_items_rec
  85: rustc_monomorphize::collector::collect_items_rec
  86: rustc_monomorphize::collector::collect_items_rec
  87: rustc_monomorphize::collector::collect_items_rec
  88: rustc_monomorphize::collector::collect_items_rec
  89: rustc_monomorphize::collector::collect_items_rec
  90: rustc_monomorphize::collector::collect_items_rec
  91: rustc_monomorphize::collector::collect_items_rec
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.59.0-nightly (db9d361a4 2021-11-28) running on aarch64-apple-darwin

note: compiler flags: -C embed-bitcode=no -C split-debuginfo=unpacked -C debuginfo=2 -C incremental --crate-type bin

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [is_copy_raw] computing whether `core::option::Option<core::option::Option<_>>` is `Copy`
#1 [needs_drop_raw] computing whether `core::option::Option<core::option::Option<_>>` needs drop
#2 [resolve_instance] resolving instance `core::ptr::drop_in_place::<core::option::Option<core::option::Option<_>>>`
#3 [collect_and_partition_mono_items] collect_and_partition_mono_items
end of query stack
```

</p>
</details>

### LINKED ISSUE #92470: ICE: bincode v2 alpha cannot be used with nightly rustc
See: https://github.com/kdy1/wasm-perf/pull/1

### Code

```Rust
use swc_common::input::SourceFileInput;
use swc_ecmascript::{
    ast::{EsVersion, Program},
    parser::{lexer::Lexer, Parser},
};

fn input() -> Program {
    testing::run_test(false, |cm, _handler| {
        let fm = cm.load_file(Path::new("benches/input.js")).unwrap();

        let lexer = Lexer::new(
            Default::default(),
            EsVersion::latest(),
            SourceFileInput::from(&*fm),
            None,
        );
        let mut parser = Parser::new_from(lexer);

        let program = parser.parse_program().unwrap();

        Ok(program)
    })
    .unwrap()
}

let program = input();

let config = bincode::Configuration::standard();
let ast_bincode = bincode::encode_to_vec(program, config.clone()).unwrap();

Ok(())
```

minimal reproduction.

I'll see if I can reduce further.

### Meta

`rustc --version --verbose`:
```
rustc 1.58.0-nightly (ad4423997 2021-11-14)
binary: rustc
commit-hash: ad442399756573dccacb314b6bf8079964bcc72a
commit-date: 2021-11-14
host: x86_64-apple-darwin
release: 1.58.0-nightly
LLVM version: 13.0.0
```

### Error output

```
thread 'rustc' panicked at 'index out of bounds: the len is 0 but the index is 0', /cargo/registry/src/gi
thub.com-1ecc6299db9ec823/ena-0.14.0/src/snapshot_vec.rs:199:10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-IC
E%2C+T-compiler&template=ice.md

note: rustc 1.58.0-nightly (ad4423997 2021-11-14) running on x86_64-unknown-linux-gnu

note: compiler flags: -C embed-bitcode=no -C debuginfo=2 -C incremental --crate-type lib

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [codegen_fulfill_obligation] checking if `bincode::config::internal::InternalIntEncodingConfig` fulfil
ls its obligations
#1 [resolve_instance] resolving instance `<_ as bincode::config::internal::InternalIntEncodingConfig>::IN
T_ENCODING`
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
thread 'rustc' panicked at 'index out of bounds: the len is 0 but the index is 0', /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/ena-0.14.0/src/snapshot_vec.rs:199:10
stack backtrace:
   0: _rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::panicking::panic_bounds_check
   3: <rustc_infer::infer::type_variable::TypeVariableTable>::probe
   4: <rustc_infer::infer::freshen::TypeFreshener as rustc_middle::ty::fold::TypeFolder>::fold_ty
   5: <&rustc_middle::ty::list::List<rustc_middle::ty::subst::GenericArg> as rustc_middle::ty::fold::TypeFoldable>::fold_with::<rustc_infer::infer::freshen::TypeFreshener>
   6: <rustc_trait_selection::traits::select::SelectionContext>::select_from_obligation
   7: <rustc_trait_selection::traits::select::SelectionContext>::select
   8: <rustc_infer::infer::InferCtxtBuilder>::enter::<core::result::Result<rustc_middle::traits::ImplSource<()>, rustc_errors::ErrorReported>, rustc_trait_selection::traits::codegen::codegen_fulfill_obligation::{closure#0}>
   9: rustc_trait_selection::traits::codegen::codegen_fulfill_obligation
  10: rustc_data_structures::stack::ensure_sufficient_stack::<core::result::Result<rustc_middle::traits::ImplSource<()>, rustc_errors::ErrorReported>, rustc_query_system::query::plumbing::execute_job<rustc_query_impl::plumbing::QueryCtxt, (rustc_middle::ty::ParamEnv, rustc_middle::ty::sty::Binder<rustc_middle::ty::sty::TraitRef>), core::result::Result<rustc_middle::traits::ImplSource<()>, rustc_errors::ErrorReported>>::{closure#0}>
  11: rustc_query_system::query::plumbing::get_query::<rustc_query_impl::queries::codegen_fulfill_obligation, rustc_query_impl::plumbing::QueryCtxt>
  12: <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::codegen_fulfill_obligation
  13: rustc_ty_utils::instance::inner_resolve_instance
  14: rustc_ty_utils::instance::resolve_instance
  15: rustc_query_system::query::plumbing::get_query::<rustc_query_impl::queries::resolve_instance, rustc_query_impl::plumbing::QueryCtxt>
  16: <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::resolve_instance
  17: <rustc_middle::ty::instance::Instance>::resolve_opt_const_arg
  18: <rustc_middle::ty::context::TyCtxt>::const_eval_resolve
  19: <rustc_monomorphize::collector::MirNeighborCollector as rustc_middle::mir::visit::Visitor>::visit_constant
  20: <rustc_monomorphize::collector::MirNeighborCollector as rustc_middle::mir::visit::Visitor>::visit_operand
  21: rustc_monomorphize::collector::collect_neighbours
  22: rustc_monomorphize::collector::collect_items_rec
  23: rustc_monomorphize::collector::collect_items_rec
  24: rustc_monomorphize::collector::collect_items_rec
  25: rustc_monomorphize::collector::collect_items_rec
  26: rustc_monomorphize::collector::collect_items_rec
  27: rustc_monomorphize::collector::collect_items_rec
  28: rustc_monomorphize::collector::collect_items_rec
  29: rustc_monomorphize::collector::collect_items_rec
  30: rustc_monomorphize::collector::collect_items_rec
  31: rustc_monomorphize::collector::collect_items_rec
  32: rustc_monomorphize::collector::collect_items_rec
  33: rustc_monomorphize::collector::collect_items_rec
  34: rustc_monomorphize::collector::collect_items_rec
  35: rustc_monomorphize::collector::collect_items_rec
  36: rustc_monomorphize::collector::collect_items_rec
  37: rustc_monomorphize::collector::collect_items_rec
  38: rustc_monomorphize::collector::collect_items_rec
  39: rustc_monomorphize::collector::collect_items_rec
  40: rustc_monomorphize::collector::collect_items_rec
  41: rustc_monomorphize::collector::collect_items_rec
  42: rustc_monomorphize::collector::collect_items_rec
  43: rustc_monomorphize::collector::collect_items_rec
  44: rustc_monomorphize::collector::collect_items_rec
  45: rustc_monomorphize::collector::collect_items_rec
  46: rustc_monomorphize::collector::collect_items_rec
  47: rustc_monomorphize::collector::collect_items_rec
  48: rustc_monomorphize::collector::collect_items_rec
  49: rustc_monomorphize::collector::collect_items_rec
  50: rustc_monomorphize::collector::collect_items_rec
  51: rustc_monomorphize::collector::collect_items_rec
  52: rustc_monomorphize::collector::collect_items_rec
  53: rustc_monomorphize::collector::collect_items_rec
  54: rustc_monomorphize::collector::collect_items_rec
  55: rustc_monomorphize::collector::collect_items_rec
  56: rustc_monomorphize::collector::collect_items_rec
  57: rustc_monomorphize::collector::collect_items_rec
  58: rustc_monomorphize::collector::collect_items_rec
  59: rustc_monomorphize::collector::collect_items_rec
  60: rustc_monomorphize::collector::collect_items_rec
  61: rustc_monomorphize::collector::collect_items_rec
  62: rustc_monomorphize::collector::collect_items_rec
  63: rustc_monomorphize::collector::collect_items_rec
  64: rustc_monomorphize::collector::collect_items_rec
  65: rustc_monomorphize::collector::collect_items_rec
  66: rustc_monomorphize::collector::collect_items_rec
  67: rustc_monomorphize::collector::collect_items_rec
  68: rustc_monomorphize::collector::collect_items_rec
  69: rustc_monomorphize::collector::collect_items_rec
  70: rustc_monomorphize::collector::collect_items_rec
  71: rustc_monomorphize::collector::collect_items_rec
  72: rustc_monomorphize::collector::collect_items_rec
  73: rustc_monomorphize::collector::collect_items_rec
  74: rustc_monomorphize::collector::collect_items_rec
  75: rustc_monomorphize::collector::collect_items_rec
  76: rustc_monomorphize::collector::collect_items_rec
  77: rustc_monomorphize::collector::collect_items_rec
  78: rustc_monomorphize::collector::collect_items_rec
  79: rustc_monomorphize::collector::collect_items_rec
  80: rustc_monomorphize::collector::collect_items_rec
  81: rustc_monomorphize::collector::collect_items_rec
  82: rustc_monomorphize::collector::collect_items_rec
  83: rustc_monomorphize::collector::collect_items_rec
  84: rustc_monomorphize::collector::collect_items_rec
  85: rustc_monomorphize::collector::collect_items_rec
  86: rustc_monomorphize::collector::collect_items_rec
  87: rustc_monomorphize::collector::collect_items_rec
  88: rustc_monomorphize::collector::collect_items_rec
  89: rustc_monomorphize::collector::collect_items_rec
  90: rustc_monomorphize::collector::collect_items_rec
  91: rustc_monomorphize::collector::collect_items_rec
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

</p>
</details>

### LINKED ISSUE #95134: ICE: 'index out of bounds: the len is 0 but the index is 0'
### Code

Minimized code

```Rust
pub fn encode_num<Writer: ExampleWriter>(n: u32, mut writer: Writer) -> Result<(), Writer::Error> {
    if n > 15 {
        encode_num(n / 16, &mut writer)?;
    }
    Ok(())
}

pub trait ExampleWriter {
    type Error;
}

impl<'a, T: ExampleWriter> ExampleWriter for &'a mut T {
    type Error = T::Error;
}

struct EmptyWriter;

impl ExampleWriter for EmptyWriter {
    type Error = ();
}

fn main() {
    encode_num(69, &mut EmptyWriter).unwrap();
}

```

### Meta

`rustc --version --verbose`:
```
rustc 1.61.0-nightly (8d60bf427 2022-03-19)
binary: rustc
commit-hash: 8d60bf427a4b055f464122062e76b3ec34d4f8ba
commit-date: 2022-03-19
host: x86_64-unknown-linux-gnu
release: 1.61.0-nightly
LLVM version: 14.0.0
```

### Error output

```
thread 'rustc' panicked at 'index out of bounds: the len is 0 but the index is 0', /cargo/registry/src/github.com-1ecc6299db9ec823/ena-0.14.0/src/snapshot_vec.rs:199:10

<backtrace>

query stack during panic:
#0 [codegen_fulfill_obligation] checking if `core::ops::try_trait::Try` fulfills its obligations
#1 [resolve_instance] resolving instance `<core::result::Result<(), _> as core::ops::try_trait::Try>::branch`
#2 [collect_and_partition_mono_items] collect_and_partition_mono_items
end of query stack
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
stack backtrace:
   0: rust_begin_unwind
             at /rustc/8d60bf427a4b055f464122062e76b3ec34d4f8ba/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/8d60bf427a4b055f464122062e76b3ec34d4f8ba/library/core/src/panicking.rs:143:14
   2: core::panicking::panic_bounds_check
             at /rustc/8d60bf427a4b055f464122062e76b3ec34d4f8ba/library/core/src/panicking.rs:84:5
   3: <rustc_middle::ty::Ty as rustc_middle::ty::fold::TypeFoldable>::try_fold_with::<rustc_infer::infer::freshen::TypeFreshener>
   4: <rustc_infer::infer::freshen::TypeFreshener as rustc_middle::ty::fold::TypeFolder>::fold_ty
   5: <rustc_trait_selection::traits::select::SelectionContext>::select
   6: <rustc_infer::infer::InferCtxtBuilder>::enter::<core::result::Result<&rustc_middle::traits::ImplSource<()>, rustc_errors::ErrorGuaranteed>, rustc_trait_selection::traits::codegen::codegen_fulfill_obligation::{closure#0}>
   7: rustc_trait_selection::traits::codegen::codegen_fulfill_obligation
   8: <rustc_query_system::dep_graph::graph::DepGraph<rustc_middle::dep_graph::dep_node::DepKind>>::with_task::<rustc_middle::ty::context::TyCtxt, (rustc_middle::ty::ParamEnv, rustc_middle::ty::sty::Binder<rustc_middle::ty::sty::TraitRef>), core::result::Result<&rustc_middle::traits::ImplSource<()>, rustc_errors::ErrorGuaranteed>>
   9: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::plumbing::QueryCtxt, rustc_query_system::query::caches::DefaultCache<(rustc_middle::ty::ParamEnv, rustc_middle::ty::sty::Binder<rustc_middle::ty::sty::TraitRef>), core::result::Result<&rustc_middle::traits::ImplSource<()>, rustc_errors::ErrorGuaranteed>>>
  10: <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::codegen_fulfill_obligation
  11: rustc_ty_utils::instance::inner_resolve_instance
  12: rustc_ty_utils::instance::resolve_instance
  13: <rustc_query_system::dep_graph::graph::DepGraph<rustc_middle::dep_graph::dep_node::DepKind>>::with_task::<rustc_middle::ty::context::TyCtxt, rustc_middle::ty::ParamEnvAnd<(rustc_span::def_id::DefId, &rustc_middle::ty::list::List<rustc_middle::ty::subst::GenericArg>)>, core::result::Result<core::option::Option<rustc_middle::ty::instance::Instance>, rustc_errors::ErrorGuaranteed>>
  14: rustc_query_system::query::plumbing::get_query::<rustc_query_impl::queries::resolve_instance, rustc_query_impl::plumbing::QueryCtxt>
  15: <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::resolve_instance
  16: <rustc_middle::ty::instance::Instance>::resolve
  17: rustc_monomorphize::collector::collect_neighbours
  18: rustc_monomorphize::collector::collect_items_rec
  19: rustc_monomorphize::collector::collect_items_rec
  20: rustc_monomorphize::collector::collect_items_rec
  21: rustc_monomorphize::collector::collect_items_rec
  22: rustc_monomorphize::collector::collect_items_rec
  23: rustc_monomorphize::collector::collect_items_rec
  24: rustc_monomorphize::collector::collect_items_rec
  25: rustc_monomorphize::collector::collect_items_rec
  26: rustc_monomorphize::collector::collect_items_rec
  27: rustc_monomorphize::collector::collect_items_rec
  28: rustc_monomorphize::collector::collect_items_rec
  29: rustc_monomorphize::collector::collect_items_rec
  30: rustc_monomorphize::collector::collect_items_rec
  31: rustc_monomorphize::collector::collect_items_rec
  32: rustc_monomorphize::collector::collect_items_rec
  33: rustc_monomorphize::collector::collect_items_rec
  34: rustc_monomorphize::collector::collect_items_rec
  35: rustc_monomorphize::collector::collect_items_rec
  36: rustc_monomorphize::collector::collect_items_rec
  37: rustc_monomorphize::collector::collect_items_rec
  38: rustc_monomorphize::collector::collect_items_rec
  39: rustc_monomorphize::collector::collect_items_rec
  40: rustc_monomorphize::collector::collect_items_rec
  41: rustc_monomorphize::collector::collect_items_rec
  42: rustc_monomorphize::collector::collect_items_rec
  43: rustc_monomorphize::collector::collect_items_rec
  44: rustc_monomorphize::collector::collect_items_rec
  45: rustc_monomorphize::collector::collect_items_rec
  46: rustc_monomorphize::collector::collect_items_rec
  47: rustc_monomorphize::collector::collect_items_rec
  48: rustc_monomorphize::collector::collect_items_rec
  49: rustc_monomorphize::collector::collect_items_rec
  50: rustc_monomorphize::collector::collect_items_rec
  51: rustc_monomorphize::collector::collect_items_rec
  52: rustc_monomorphize::collector::collect_items_rec
  53: rustc_monomorphize::collector::collect_items_rec
  54: rustc_monomorphize::collector::collect_items_rec
  55: rustc_monomorphize::collector::collect_items_rec
  56: rustc_monomorphize::collector::collect_items_rec
  57: rustc_monomorphize::collector::collect_items_rec
  58: rustc_monomorphize::collector::collect_items_rec
  59: rustc_monomorphize::collector::collect_items_rec
  60: rustc_monomorphize::collector::collect_items_rec
  61: rustc_monomorphize::collector::collect_items_rec
  62: rustc_monomorphize::collector::collect_items_rec
  63: rustc_monomorphize::collector::collect_items_rec
  64: rustc_monomorphize::collector::collect_items_rec
  65: rustc_monomorphize::collector::collect_items_rec
  66: rustc_monomorphize::collector::collect_items_rec
  67: rustc_monomorphize::collector::collect_items_rec
  68: rustc_monomorphize::collector::collect_items_rec
  69: rustc_monomorphize::collector::collect_items_rec
  70: rustc_monomorphize::collector::collect_items_rec
  71: rustc_monomorphize::collector::collect_items_rec
  72: rustc_monomorphize::collector::collect_items_rec
  73: rustc_monomorphize::collector::collect_items_rec
  74: rustc_monomorphize::collector::collect_items_rec
  75: rustc_monomorphize::collector::collect_items_rec
  76: rustc_monomorphize::collector::collect_items_rec
  77: rustc_monomorphize::collector::collect_items_rec
  78: rustc_monomorphize::collector::collect_items_rec
  79: rustc_monomorphize::collector::collect_items_rec
  80: rustc_monomorphize::collector::collect_items_rec
  81: rustc_monomorphize::collector::collect_items_rec
  82: rustc_monomorphize::collector::collect_items_rec
  83: rustc_monomorphize::collector::collect_items_rec
  84: rustc_monomorphize::collector::collect_items_rec
  85: rustc_monomorphize::collector::collect_items_rec
  86: rustc_monomorphize::collector::collect_items_rec
  87: rustc_monomorphize::collector::collect_items_rec
  88: rustc_monomorphize::collector::collect_items_rec
  89: rustc_monomorphize::collector::collect_items_rec
  90: rustc_monomorphize::collector::collect_items_rec
  91: rustc_monomorphize::collector::collect_items_rec
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

</p>
</details>

### LINKED ISSUE #105275: ICE `            debug_assert!(!erased.needs_infer(), "{:?}", erased);`
### Code

```Rust
// build-fail
// compile-flags: -Copt-level=0
//~^^ ERROR overflow evaluating the requirement

pub fn encode_num<Writer: ExampleWriter>(n: u32, mut writer: Writer) -> Result<(), Writer::Error> {
    if n > 15 {
        encode_num(n / 16, &mut writer)?;
    }
    Ok(())
}

pub trait ExampleWriter {
    type Error;
}

impl<'a, T: ExampleWriter> ExampleWriter for &'a mut T {
    type Error = T::Error;
}

struct Error;

impl ExampleWriter for Error {
    type Error = ();
}

fn main() {
    encode_num(69, &mut Error).unwrap();
}
```
So with vanilla rustc 
````
rustc 1.67.0-nightly (234151769 2022-12-03)
binary: rustc
commit-hash: 23415176968e81e0aac92d0218612a89c4e68a82
commit-date: 2022-12-03
host: x86_64-unknown-linux-gnu
release: 1.67.0-nightly
LLVM version: 15.0.4
````
you will get the good ol' 
`thread '<unnamed>' panicked at 'index out of bounds: the len is 0 but the index is 0', /cargo/registry/src/github.com-1ecc6299db9ec823/ena-0.14.0/src/snapshot_vec.rs:199:10` assertion which I have already seen a bunch of times.

````
thread '<unnamed>' panicked at 'index out of bounds: the len is 0 but the index is 0', /cargo/registry/src/github.com-1ecc6299db9ec823/ena-0.14.0/src/snapshot_vec.rs:199:10
stack backtrace:
   0:     0x7f6d3a56625a - std::backtrace_rs::backtrace::libunwind::trace::h39c51bcedb139b44
                               at /rustc/23415176968e81e0aac92d0218612a89c4e68a82/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x7f6d3a56625a - std::backtrace_rs::backtrace::trace_unsynchronized::h9cf890f6f509d0c3
                               at /rustc/23415176968e81e0aac92d0218612a89c4e68a82/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7f6d3a56625a - std::sys_common::backtrace::_print_fmt::h4a0d7673c4689a86
                               at /rustc/23415176968e81e0aac92d0218612a89c4e68a82/library/std/src/sys_common/backtrace.rs:65:5
   3:     0x7f6d3a56625a - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hed99d8097fd95926
                               at /rustc/23415176968e81e0aac92d0218612a89c4e68a82/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x7f6d3a5c8e4e - core::fmt::write::hdab16ae0136a16af
                               at /rustc/23415176968e81e0aac92d0218612a89c4e68a82/library/core/src/fmt/mod.rs:1208:17
   5:     0x7f6d3a556675 - std::io::Write::write_fmt::h9619f0289bf5af21
                               at /rustc/23415176968e81e0aac92d0218612a89c4e68a82/library/std/src/io/mod.rs:1682:15
   6:     0x7f6d3a566025 - std::sys_common::backtrace::_print::h2fbe09348ca97657
                               at /rustc/23415176968e81e0aac92d0218612a89c4e68a82/library/std/src/sys_common/backtrace.rs:47:5
   7:     0x7f6d3a566025 - std::sys_common::backtrace::print::h72058f5ceb813403
                               at /rustc/23415176968e81e0aac92d0218612a89c4e68a82/library/std/src/sys_common/backtrace.rs:34:9
   8:     0x7f6d3a568d6f - std::panicking::default_hook::{{closure}}::h1542b395e584376b
                               at /rustc/23415176968e81e0aac92d0218612a89c4e68a82/library/std/src/panicking.rs:267:22
   9:     0x7f6d3a568aab - std::panicking::default_hook::hf92492522bb6bc51
                               at /rustc/23415176968e81e0aac92d0218612a89c4e68a82/library/std/src/panicking.rs:286:9
  10:     0x7f6d3a56958c - std::panicking::rust_panic_with_hook::h8e3ba576266d6126
                               at /rustc/23415176968e81e0aac92d0218612a89c4e68a82/library/std/src/panicking.rs:688:13
  11:     0x7f6d3a569329 - std::panicking::begin_panic_handler::{{closure}}::h5718d689762256a1
                               at /rustc/23415176968e81e0aac92d0218612a89c4e68a82/library/std/src/panicking.rs:579:13
  12:     0x7f6d3a56670c - std::sys_common::backtrace::__rust_end_short_backtrace::hb4469c61f2390e29
                               at /rustc/23415176968e81e0aac92d0218612a89c4e68a82/library/std/src/sys_common/backtrace.rs:137:18
  13:     0x7f6d3a569032 - rust_begin_unwind
                               at /rustc/23415176968e81e0aac92d0218612a89c4e68a82/library/std/src/panicking.rs:575:5
  14:     0x7f6d3a5c5863 - core::panicking::panic_fmt::h4dafe9d2577d7060
                               at /rustc/23415176968e81e0aac92d0218612a89c4e68a82/library/core/src/panicking.rs:64:14
  15:     0x7f6d3a5c5a32 - core::panicking::panic_bounds_check::hf370cb7cb7f7e64d
                               at /rustc/23415176968e81e0aac92d0218612a89c4e68a82/library/core/src/panicking.rs:147:5
  16:     0x7f6d3b8359c8 - <rustc_middle[eef20b0c23bc8b9b]::ty::Ty as rustc_middle[eef20b0c23bc8b9b]::ty::fold::TypeSuperFoldable>::super_fold_with::<rustc_infer[84fbd1c9bd9414bc]::infer::freshen::TypeFreshener>
  17:     0x7f6d3babf0a3 - <rustc_trait_selection[69a4b2fab63ed72e]::traits::select::SelectionContext>::select
  18:     0x7f6d3c15b0fd - rustc_trait_selection[69a4b2fab63ed72e]::traits::codegen::codegen_select_candidate
  19:     0x7f6d3c2fa17b - rustc_query_system[c6fc551e4ef2763b]::query::plumbing::try_execute_query::<rustc_query_impl[935dec28a6523c17]::plumbing::QueryCtxt, rustc_query_system[c6fc551e4ef2763b]::query::caches::DefaultCache<(rustc_middle[eef20b0c23bc8b9b]::ty::ParamEnv, rustc_middle[eef20b0c23bc8b9b]::ty::sty::Binder<rustc_middle[eef20b0c23bc8b9b]::ty::sty::TraitRef>), core[ec9ef0a26f3cf28]::result::Result<&rustc_middle[eef20b0c23bc8b9b]::traits::ImplSource<()>, rustc_middle[eef20b0c23bc8b9b]::traits::CodegenObligationError>>>
  20:     0x7f6d3c2381c1 - rustc_ty_utils[e127af94daa6312b]::instance::inner_resolve_instance
  21:     0x7f6d3bf9da2f - rustc_query_system[c6fc551e4ef2763b]::query::plumbing::get_query::<rustc_query_impl[935dec28a6523c17]::queries::resolve_instance, rustc_query_impl[935dec28a6523c17]::plumbing::QueryCtxt>
  22:     0x7f6d3c2b39e9 - rustc_monomorphize[41c382e3ba61d756]::collector::collect_neighbours
  23:     0x7f6d3c2abf59 - rustc_monomorphize[41c382e3ba61d756]::collector::collect_items_rec
  24:     0x7f6d3c2ac3c4 - rustc_monomorphize[41c382e3ba61d756]::collector::collect_items_rec
  25:     0x7f6d3c2ac3c4 - rustc_monomorphize[41c382e3ba61d756]::collector::collect_items_rec
  26:     0x7f6d3c2ac3c4 - rustc_monomorphize[41c382e3ba61d756]::collector::collect_items_rec
  27:     0x7f6d3c2ac3c4 - rustc_monomorphize[41c382e3ba61d756]::collector::collect_items_rec
  28:     0x7f6d3c2ac3c4 - rustc_monomorphize[41c382e3ba61d756]::collector::collect_items_rec
  29:     0x7f6d3c2ac3c4 - rustc_monomorphize[41c382e3ba61d756]::collector::collect_items_rec
  30:     0x7f6d3c2ac3c4 - rustc_monomorphize[41c382e3ba61d756]::collector::collect_items_rec
  31:     0x7f6d3c2ac3c4 - rustc_monomorphize[41c382e3ba61d756]::collector::collect_items_rec
  32:     0x7f6d3c2ac3c4 - rustc_monomorphize[41c382e3ba61d756]::collector::collect_items_rec
  33:     0x7f6d3c2ac3c4 - rustc_monomorphize[41c382e3ba61d756]::collector::collect_items_rec
  34:     0x7f6d3c2ac3c4 - rustc_monomorphize[41c382e3ba61d756]::collector::collect_items_rec
  35:     0x7f6d3c2ac3c4 - rustc_monomorphize[41c382e3ba61d756]::collector::collect_items_rec
  36:     0x7f6d3c2ac3c4 - rustc_monomorphize[41c382e3ba61d756]::collector::collect_items_rec
  37:     0x7f6d3c2ac3c4 - rustc_monomorphize[41c382e3ba61d756]::collector::collect_items_rec
  38:     0x7f6d3c2ac3c4 - rustc_monomorphize[41c382e3ba61d756]::collector::collect_items_rec
  39:     0x7f6d3c2ac3c4 - rustc_monomorphize[41c382e3ba61d756]::collector::collect_items_rec
  40:     0x7f6d3c2ac3c4 - rustc_monomorphize[41c382e3ba61d756]::collector::collect_items_rec
  41:     0x7f6d3c2ac3c4 - rustc_monomorphize[41c382e3ba61d756]::collector::collect_items_rec
  42:     0x7f6d3c2ac3c4 - rustc_monomorphize[41c382e3ba61d756]::collector::collect_items_rec
  43:     0x7f6d3c2ac3c4 - rustc_monomorphize[41c382e3ba61d756]::collector::collect_items_rec
  44:     0x7f6d3c2ac3c4 - rustc_monomorphize[41c382e3ba61d756]::collector::collect_items_rec
  45:     0x7f6d3c2ac3c4 - rustc_monomorphize[41c382e3ba61d756]::collector::collect_items_rec
  46:     0x7f6d3c2ac3c4 - rustc_monomorphize[41c382e3ba61d756]::collector::collect_items_rec
  47:     0x7f6d3c2ac3c4 - rustc_monomorphize[41c382e3ba61d756]::collector::collect_items_rec
  48:     0x7f6d3c2ac3c4 - rustc_monomorphize[41c382e3ba61d756]::collector::collect_items_rec
  49:     0x7f6d3c2ac3c4 - rustc_monomorphize[41c382e3ba61d756]::collector::collect_items_rec
  50:     0x7f6d3c2ac3c4 - rustc_monomorphize[41c382e3ba61d756]::collector::collect_items_rec
  51:     0x7f6d3c2ac3c4 - rustc_monomorphize[41c382e3ba61d756]::collector::collect_items_rec
  52:     0x7f6d3c2ac3c4 - rustc_monomorphize[41c382e3ba61d756]::collector::collect_items_rec
  53:     0x7f6d3c2ac3c4 - rustc_monomorphize[41c382e3ba61d756]::collector::collect_items_rec
  54:     0x7f6d3c2ac3c4 - rustc_monomorphize[41c382e3ba61d756]::collector::collect_items_rec
  55:     0x7f6d3c2ac3c4 - rustc_monomorphize[41c382e3ba61d756]::collector::collect_items_rec
  56:     0x7f6d3c2ac3c4 - rustc_monomorphize[41c382e3ba61d756]::collector::collect_items_rec
  57:     0x7f6d3c2ac3c4 - rustc_monomorphize[41c382e3ba61d756]::collector::collect_items_rec
  58:     0x7f6d3c2ac3c4 - rustc_monomorphize[41c382e3ba61d756]::collector::collect_items_rec
  59:     0x7f6d3c2ac3c4 - rustc_monomorphize[41c382e3ba61d756]::collector::collect_items_rec
  60:     0x7f6d3c2ac3c4 - rustc_monomorphize[41c382e3ba61d756]::collector::collect_items_rec
  61:     0x7f6d3c2ac3c4 - rustc_monomorphize[41c382e3ba61d756]::collector::collect_items_rec
  62:     0x7f6d3c2ac3c4 - rustc_monomorphize[41c382e3ba61d756]::collector::collect_items_rec
  63:     0x7f6d3c2ac3c4 - rustc_monomorphize[41c382e3ba61d756]::collector::collect_items_rec
  64:     0x7f6d3c2ac3c4 - rustc_monomorphize[41c382e3ba61d756]::collector::collect_items_rec
  65:     0x7f6d3c2ac3c4 - rustc_monomorphize[41c382e3ba61d756]::collector::collect_items_rec
  66:     0x7f6d3c2ac3c4 - rustc_monomorphize[41c382e3ba61d756]::collector::collect_items_rec
  67:     0x7f6d3c2ac3c4 - rustc_monomorphize[41c382e3ba61d756]::collector::collect_items_rec
  68:     0x7f6d3c2ac3c4 - rustc_monomorphize[41c382e3ba61d756]::collector::collect_items_rec
  69:     0x7f6d3c2ac3c4 - rustc_monomorphize[41c382e3ba61d756]::collector::collect_items_rec
  70:     0x7f6d3c2ac3c4 - rustc_monomorphize[41c382e3ba61d756]::collector::collect_items_rec
  71:     0x7f6d3c2ac3c4 - rustc_monomorphize[41c382e3ba61d756]::collector::collect_items_rec
  72:     0x7f6d3c2ac3c4 - rustc_monomorphize[41c382e3ba61d756]::collector::collect_items_rec
  73:     0x7f6d3c2ac3c4 - rustc_monomorphize[41c382e3ba61d756]::collector::collect_items_rec
  74:     0x7f6d3c2ac3c4 - rustc_monomorphize[41c382e3ba61d756]::collector::collect_items_rec
  75:     0x7f6d3c2ac3c4 - rustc_monomorphize[41c382e3ba61d756]::collector::collect_items_rec
  76:     0x7f6d3c2ac3c4 - rustc_monomorphize[41c382e3ba61d756]::collector::collect_items_rec
  77:     0x7f6d3c2ac3c4 - rustc_monomorphize[41c382e3ba61d756]::collector::collect_items_rec
  78:     0x7f6d3c2ac3c4 - rustc_monomorphize[41c382e3ba61d756]::collector::collect_items_rec
  79:     0x7f6d3c2ac3c4 - rustc_monomorphize[41c382e3ba61d756]::collector::collect_items_rec
  80:     0x7f6d3c2ac3c4 - rustc_monomorphize[41c382e3ba61d756]::collector::collect_items_rec
  81:     0x7f6d3c2ac3c4 - rustc_monomorphize[41c382e3ba61d756]::collector::collect_items_rec
  82:     0x7f6d3c2ac3c4 - rustc_monomorphize[41c382e3ba61d756]::collector::collect_items_rec
  83:     0x7f6d3c2ac3c4 - rustc_monomorphize[41c382e3ba61d756]::collector::collect_items_rec
  84:     0x7f6d3c2ac3c4 - rustc_monomorphize[41c382e3ba61d756]::collector::collect_items_rec
  85:     0x7f6d3c2ac3c4 - rustc_monomorphize[41c382e3ba61d756]::collector::collect_items_rec
  86:     0x7f6d3c2ac3c4 - rustc_monomorphize[41c382e3ba61d756]::collector::collect_items_rec
  87:     0x7f6d3c2ac3c4 - rustc_monomorphize[41c382e3ba61d756]::collector::collect_items_rec
  88:     0x7f6d3c2ac3c4 - rustc_monomorphize[41c382e3ba61d756]::collector::collect_items_rec
  89:     0x7f6d3c2ac3c4 - rustc_monomorphize[41c382e3ba61d756]::collector::collect_items_rec
  90:     0x7f6d3c2ac3c4 - rustc_monomorphize[41c382e3ba61d756]::collector::collect_items_rec
  91:     0x7f6d3c2ac3c4 - rustc_monomorphize[41c382e3ba61d756]::collector::collect_items_rec
  92:     0x7f6d3c2ac3c4 - rustc_monomorphize[41c382e3ba61d756]::collector::collect_items_rec
  93:     0x7f6d3c2ac3c4 - rustc_monomorphize[41c382e3ba61d756]::collector::collect_items_rec
  94:     0x7f6d3c2ac3c4 - rustc_monomorphize[41c382e3ba61d756]::collector::collect_items_rec
  95:     0x7f6d3c2ac3c4 - rustc_monomorphize[41c382e3ba61d756]::collector::collect_items_rec
  96:     0x7f6d3c2ac3c4 - rustc_monomorphize[41c382e3ba61d756]::collector::collect_items_rec
  97:     0x7f6d3c2ac3c4 - rustc_monomorphize[41c382e3ba61d756]::collector::collect_items_rec
  98:     0x7f6d3c2ac3c4 - rustc_monomorphize[41c382e3ba61d756]::collector::collect_items_rec
  99:     0x7f6d3c2ac3c4 - rustc_monomorphize[41c382e3ba61d756]::collector::collect_items_rec
 100:     0x7f6d3c2ac3c4 - rustc_monomorphize[41c382e3ba61d756]::collector::collect_items_rec
 101:     0x7f6d3c2ac3c4 - rustc_monomorphize[41c382e3ba61d756]::collector::collect_items_rec
 102:     0x7f6d3c2ac3c4 - rustc_monomorphize[41c382e3ba61d756]::collector::collect_items_rec
 103:     0x7f6d3c2ac3c4 - rustc_monomorphize[41c382e3ba61d756]::collector::collect_items_rec
 104:     0x7f6d3c2ac3c4 - rustc_monomorphize[41c382e3ba61d756]::collector::collect_items_rec
 105:     0x7f6d3c2ac3c4 - rustc_monomorphize[41c382e3ba61d756]::collector::collect_items_rec
 106:     0x7f6d3c2ac3c4 - rustc_monomorphize[41c382e3ba61d756]::collector::collect_items_rec
 107:     0x7f6d3c2ac3c4 - rustc_monomorphize[41c382e3ba61d756]::collector::collect_items_rec
 108:     0x7f6d3c2ac3c4 - rustc_monomorphize[41c382e3ba61d756]::collector::collect_items_rec
 109:     0x7f6d3c2ac3c4 - rustc_monomorphize[41c382e3ba61d756]::collector::collect_items_rec
 110:     0x7f6d3c2ac3c4 - rustc_monomorphize[41c382e3ba61d756]::collector::collect_items_rec
 111:     0x7f6d3c2ac3c4 - rustc_monomorphize[41c382e3ba61d756]::collector::collect_items_rec
 112:     0x7f6d3c2ac3c4 - rustc_monomorphize[41c382e3ba61d756]::collector::collect_items_rec
 113:     0x7f6d3c2ac3c4 - rustc_monomorphize[41c382e3ba61d756]::collector::collect_items_rec
 114:     0x7f6d3c2ac3c4 - rustc_monomorphize[41c382e3ba61d756]::collector::collect_items_rec
 115:     0x7f6d3c2ac3c4 - rustc_monomorphize[41c382e3ba61d756]::collector::collect_items_rec
 116:     0x7f6d3c2ac3c4 - rustc_monomorphize[41c382e3ba61d756]::collector::collect_items_rec
 117:     0x7f6d3c2ac3c4 - rustc_monomorphize[41c382e3ba61d756]::collector::collect_items_rec
 118:     0x7f6d3c2ac3c4 - rustc_monomorphize[41c382e3ba61d756]::collector::collect_items_rec
 119:     0x7f6d3c2ac3c4 - rustc_monomorphize[41c382e3ba61d756]::collector::collect_items_rec
 120:     0x7f6d3c2ac3c4 - rustc_monomorphize[41c382e3ba61d756]::collector::collect_items_rec
 121:     0x7f6d3c2ac3c4 - rustc_monomorphize[41c382e3ba61d756]::collector::collect_items_rec
 122:     0x7f6d3c2ac3c4 - rustc_monomorphize[41c382e3ba61d756]::collector::collect_items_rec
 123:     0x7f6d3c2ac3c4 - rustc_monomorphize[41c382e3ba61d756]::collector::collect_items_rec
 124:     0x7f6d3c2ac3c4 - rustc_monomorphize[41c382e3ba61d756]::collector::collect_items_rec
 125:     0x7f6d3c2ac3c4 - rustc_monomorphize[41c382e3ba61d756]::collector::collect_items_rec
 126:     0x7f6d3c2ac3c4 - rustc_monomorphize[41c382e3ba61d756]::collector::collect_items_rec
 127:     0x7f6d3c2ac3c4 - rustc_monomorphize[41c382e3ba61d756]::collector::collect_items_rec
 128:     0x7f6d3c2ac3c4 - rustc_monomorphize[41c382e3ba61d756]::collector::collect_items_rec
 129:     0x7f6d3c2ac3c4 - rustc_monomorphize[41c382e3ba61d756]::collector::collect_items_rec
 130:     0x7f6d3c2ac3c4 - rustc_monomorphize[41c382e3ba61d756]::collector::collect_items_rec
 131:     0x7f6d3c2ac3c4 - rustc_monomorphize[41c382e3ba61d756]::collector::collect_items_rec
 132:     0x7f6d3c2ac3c4 - rustc_monomorphize[41c382e3ba61d756]::collector::collect_items_rec
 133:     0x7f6d3c2ac3c4 - rustc_monomorphize[41c382e3ba61d756]::collector::collect_items_rec
 134:     0x7f6d3c2ac3c4 - rustc_monomorphize[41c382e3ba61d756]::collector::collect_items_rec
 135:     0x7f6d3c2ac3c4 - rustc_monomorphize[41c382e3ba61d756]::collector::collect_items_rec
 136:     0x7f6d3c2ac3c4 - rustc_monomorphize[41c382e3ba61d756]::collector::collect_items_rec
 137:     0x7f6d3c2ac3c4 - rustc_monomorphize[41c382e3ba61d756]::collector::collect_items_rec
 138:     0x7f6d3c2ac3c4 - rustc_monomorphize[41c382e3ba61d756]::collector::collect_items_rec
 139:     0x7f6d3c2ac3c4 - rustc_monomorphize[41c382e3ba61d756]::collector::collect_items_rec
 140:     0x7f6d3c2ac3c4 - rustc_monomorphize[41c382e3ba61d756]::collector::collect_items_rec
 141:     0x7f6d3c2ac3c4 - rustc_monomorphize[41c382e3ba61d756]::collector::collect_items_rec
 142:     0x7f6d3c2ac3c4 - rustc_monomorphize[41c382e3ba61d756]::collector::collect_items_rec
 143:     0x7f6d3c2ac3c4 - rustc_monomorphize[41c382e3ba61d756]::collector::collect_items_rec
 144:     0x7f6d3c2ac3c4 - rustc_monomorphize[41c382e3ba61d756]::collector::collect_items_rec
 145:     0x7f6d3c2ac3c4 - rustc_monomorphize[41c382e3ba61d756]::collector::collect_items_rec
 146:     0x7f6d3c2ac3c4 - rustc_monomorphize[41c382e3ba61d756]::collector::collect_items_rec
 147:     0x7f6d3c2ac3c4 - rustc_monomorphize[41c382e3ba61d756]::collector::collect_items_rec
 148:     0x7f6d3c2ac3c4 - rustc_monomorphize[41c382e3ba61d756]::collector::collect_items_rec
 149:     0x7f6d3c2ac3c4 - rustc_monomorphize[41c382e3ba61d756]::collector::collect_items_rec
 150:     0x7f6d3c2ac3c4 - rustc_monomorphize[41c382e3ba61d756]::collector::collect_items_rec
 151:     0x7f6d3c2ac3c4 - rustc_monomorphize[41c382e3ba61d756]::collector::collect_items_rec
 152:     0x7f6d3c2ac3c4 - rustc_monomorphize[41c382e3ba61d756]::collector::collect_items_rec
 153:     0x7f6d3cc88e65 - <rustc_session[87f0d63408877899]::session::Session>::time::<(), rustc_monomorphize[41c382e3ba61d756]::collector::collect_crate_mono_items::{closure#1}>
 154:     0x7f6d3cc88984 - rustc_monomorphize[41c382e3ba61d756]::collector::collect_crate_mono_items
 155:     0x7f6d3cc87d93 - rustc_monomorphize[41c382e3ba61d756]::partitioning::collect_and_partition_mono_items
 156:     0x7f6d3d062280 - rustc_query_system[c6fc551e4ef2763b]::query::plumbing::try_execute_query::<rustc_query_impl[935dec28a6523c17]::plumbing::QueryCtxt, rustc_query_system[c6fc551e4ef2763b]::query::caches::DefaultCache<(), (&std[b988c8daa9554a2a]::collections::hash::set::HashSet<rustc_span[653636119034ca50]::def_id::DefId, core[ec9ef0a26f3cf28]::hash::BuildHasherDefault<rustc_hash[2230d8a60abf7532]::FxHasher>>, &[rustc_middle[eef20b0c23bc8b9b]::mir::mono::CodegenUnit])>>
 157:     0x7f6d3d061f44 - rustc_query_system[c6fc551e4ef2763b]::query::plumbing::get_query::<rustc_query_impl[935dec28a6523c17]::queries::collect_and_partition_mono_items, rustc_query_impl[935dec28a6523c17]::plumbing::QueryCtxt>
 158:     0x7f6d3d061e7e - <rustc_query_impl[935dec28a6523c17]::Queries as rustc_middle[eef20b0c23bc8b9b]::ty::query::QueryEngine>::collect_and_partition_mono_items
 159:     0x7f6d3cd346eb - rustc_codegen_ssa[6d1b86094529188b]::base::codegen_crate::<rustc_codegen_llvm[503052878b417ad6]::LlvmCodegenBackend>
 160:     0x7f6d3cd3448e - <rustc_codegen_llvm[503052878b417ad6]::LlvmCodegenBackend as rustc_codegen_ssa[6d1b86094529188b]::traits::backend::CodegenBackend>::codegen_crate
 161:     0x7f6d3ca4bdd1 - <rustc_session[87f0d63408877899]::session::Session>::time::<alloc[c9a67e0c95f99b51]::boxed::Box<dyn core[ec9ef0a26f3cf28]::any::Any>, rustc_interface[c57545daadc3fa09]::passes::start_codegen::{closure#0}>
 162:     0x7f6d3ca4b8c5 - rustc_interface[c57545daadc3fa09]::passes::start_codegen
 163:     0x7f6d3ca46fad - <rustc_interface[c57545daadc3fa09]::passes::QueryContext>::enter::<<rustc_interface[c57545daadc3fa09]::queries::Queries>::ongoing_codegen::{closure#0}::{closure#0}, core[ec9ef0a26f3cf28]::result::Result<alloc[c9a67e0c95f99b51]::boxed::Box<dyn core[ec9ef0a26f3cf28]::any::Any>, rustc_errors[57b9e96b8e7428c]::ErrorGuaranteed>>
 164:     0x7f6d3ca447c4 - <rustc_interface[c57545daadc3fa09]::queries::Queries>::ongoing_codegen
 165:     0x7f6d3ca43991 - <rustc_interface[c57545daadc3fa09]::interface::Compiler>::enter::<rustc_driver[d87acf87108c2deb]::run_compiler::{closure#1}::{closure#2}, core[ec9ef0a26f3cf28]::result::Result<core[ec9ef0a26f3cf28]::option::Option<rustc_interface[c57545daadc3fa09]::queries::Linker>, rustc_errors[57b9e96b8e7428c]::ErrorGuaranteed>>
 166:     0x7f6d3ca3e978 - rustc_span[653636119034ca50]::with_source_map::<core[ec9ef0a26f3cf28]::result::Result<(), rustc_errors[57b9e96b8e7428c]::ErrorGuaranteed>, rustc_interface[c57545daadc3fa09]::interface::run_compiler<core[ec9ef0a26f3cf28]::result::Result<(), rustc_errors[57b9e96b8e7428c]::ErrorGuaranteed>, rustc_driver[d87acf87108c2deb]::run_compiler::{closure#1}>::{closure#0}::{closure#0}>
 167:     0x7f6d3ca3e465 - <scoped_tls[2510ce566f7fd87d]::ScopedKey<rustc_span[653636119034ca50]::SessionGlobals>>::set::<rustc_interface[c57545daadc3fa09]::interface::run_compiler<core[ec9ef0a26f3cf28]::result::Result<(), rustc_errors[57b9e96b8e7428c]::ErrorGuaranteed>, rustc_driver[d87acf87108c2deb]::run_compiler::{closure#1}>::{closure#0}, core[ec9ef0a26f3cf28]::result::Result<(), rustc_errors[57b9e96b8e7428c]::ErrorGuaranteed>>
 168:     0x7f6d3ca3da52 - std[b988c8daa9554a2a]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[c57545daadc3fa09]::util::run_in_thread_pool_with_globals<rustc_interface[c57545daadc3fa09]::interface::run_compiler<core[ec9ef0a26f3cf28]::result::Result<(), rustc_errors[57b9e96b8e7428c]::ErrorGuaranteed>, rustc_driver[d87acf87108c2deb]::run_compiler::{closure#1}>::{closure#0}, core[ec9ef0a26f3cf28]::result::Result<(), rustc_errors[57b9e96b8e7428c]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[ec9ef0a26f3cf28]::result::Result<(), rustc_errors[57b9e96b8e7428c]::ErrorGuaranteed>>
 169:     0x7f6d3d1a6848 - <<std[b988c8daa9554a2a]::thread::Builder>::spawn_unchecked_<rustc_interface[c57545daadc3fa09]::util::run_in_thread_pool_with_globals<rustc_interface[c57545daadc3fa09]::interface::run_compiler<core[ec9ef0a26f3cf28]::result::Result<(), rustc_errors[57b9e96b8e7428c]::ErrorGuaranteed>, rustc_driver[d87acf87108c2deb]::run_compiler::{closure#1}>::{closure#0}, core[ec9ef0a26f3cf28]::result::Result<(), rustc_errors[57b9e96b8e7428c]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[ec9ef0a26f3cf28]::result::Result<(), rustc_errors[57b9e96b8e7428c]::ErrorGuaranteed>>::{closure#1} as core[ec9ef0a26f3cf28]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
 170:     0x7f6d3e6b07f3 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hd24e4095bea58fc3
                               at /rustc/23415176968e81e0aac92d0218612a89c4e68a82/library/alloc/src/boxed.rs:2000:9
 171:     0x7f6d3e6b07f3 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h7c7f47af88aff778
                               at /rustc/23415176968e81e0aac92d0218612a89c4e68a82/library/alloc/src/boxed.rs:2000:9
 172:     0x7f6d3e6b07f3 - std::sys::unix::thread::Thread::new::thread_start::h8d5de08b8b3f2cac
                               at /rustc/23415176968e81e0aac92d0218612a89c4e68a82/library/std/src/sys/unix/thread.rs:108:17
 173:     0x7f6d3a2ca8fd - <unknown>
 174:     0x7f6d3a34ca60 - <unknown>
 175:                0x0 - <unknown>
 ````

### LINKED ISSUE #118590: Compiler panic due to iter adapters
I tried this code:

```rust
use std::io::stdin;

use nom::{
    bytes::complete::{tag, take_until},
    character::complete::{self, digit1},
    multi::{many0, many1},
    sequence::tuple,
    IResult,
};

fn parse_num(input: &str) -> IResult<&str, u32> {
    let (input, _) = many0(complete::char(' '))(input)?;
    let (input, num) = digit1(input)?;
    Ok((input, num.parse().unwrap()))
}

fn parse_card(input: &str) -> IResult<&str, u32> {
    let (input, _) = tuple((take_until(":"), tag(":")))(input)?;
    let (input, mut winning_nums) = many1(parse_num)(input)?;
    let (input, _) = tag(" | ")(input)?;
    let (input, mut my_nums) = many1(parse_num)(input)?;

    winning_nums.sort();
    my_nums.sort();

    Ok((input, calc_score(winning_nums, my_nums, 0)))
}

fn calc_score(
    winning_nums: impl IntoIterator<Item = u32>,
    my_nums: impl IntoIterator<Item = u32>,
    points: u32,
) -> u32 {
    let mut winning_nums = winning_nums.into_iter().peekable();
    let mut my_nums = my_nums.into_iter().peekable();
    if let (Some(&w), Some(&m)) = (winning_nums.peek(), my_nums.peek()) {
        if w > m {
            calc_score(winning_nums, my_nums.skip(1), points)
        } else if w < m {
            calc_score(winning_nums.skip(1), my_nums, points)
        } else {
            calc_score(
                winning_nums,
                my_nums.skip(1),
                if points == 0 { 1 } else { points * 2 },
            )
        }
    } else {
        points
    }
}

fn part1() -> u32 {
    stdin().lines().into_iter().fold(0, |acc, line| {
        acc + parse_card(line.unwrap().as_str()).unwrap().1
    })
}

fn main() {
    println!("{}", part1());
}
```

I expected to see this happen: cargo should compile successfully or with an error message

Instead, this happened: compiler panicked

### Meta

`rustc --version --verbose`:
```
rustc 1.74.0 (79e9716c9 2023-11-13)
binary: rustc
commit-hash: 79e9716c980570bfd1f666e3b16ac583f0168962
commit-date: 2023-11-13
host: x86_64-unknown-linux-gnu
release: 1.74.0
LLVM version: 17.0.4
```

<details><summary>Backtrace</summary>
<p>

```
   Compiling advent-of-code-2023 v0.1.0 (/home/jason/projects/advent-of-code-2023)
thread 'rustc' panicked at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/compiler/rustc_type_ir/src/lib.rs:759:17:
type variables should not be hashed: ?0t
stack backtrace:
   0: rust_begin_unwind
             at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/panicking.rs:597:5
   1: core::panicking::panic_fmt
             at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/panicking.rs:72:14
   2: <rustc_type_ir::InferTy as rustc_data_structures::stable_hasher::HashStable<rustc_query_system::ich::hcx::StableHashingContext>>::hash_stable
   3: <rustc_type_ir::ty_info::WithCachedTypeInfo<rustc_type_ir::sty::TyKind<rustc_middle::ty::context::TyCtxt>> as rustc_data_structures::stable_hasher::HashStable<rustc_query_system::ich::hcx::StableHashingContext>>::hash_stable
   4: <&rustc_middle::ty::list::List<rustc_middle::ty::generic_args::GenericArg> as rustc_data_structures::stable_hasher::HashStable<rustc_query_system::ich::hcx::StableHashingContext>>::hash_stable
   5: <rustc_type_ir::ty_info::WithCachedTypeInfo<rustc_type_ir::sty::TyKind<rustc_middle::ty::context::TyCtxt>> as rustc_data_structures::stable_hasher::HashStable<rustc_query_system::ich::hcx::StableHashingContext>>::hash_stable
   6: <rustc_query_impl::query_impl::try_normalize_generic_arg_after_erasing_regions::dynamic_query::{closure#7} as core::ops::function::FnOnce<(&mut rustc_query_system::ich::hcx::StableHashingContext, &rustc_middle::query::erase::Erased<[u8; 8]>)>>::call_once
   7: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::DynamicConfig<rustc_query_system::query::caches::DefaultCache<rustc_middle::ty::ParamEnvAnd<rustc_middle::ty::generic_args::GenericArg>, rustc_middle::query::erase::Erased<[u8; 8]>>, false, false, false>, rustc_query_impl::plumbing::QueryCtxt, true>
   8: <rustc_middle::ty::normalize_erasing_regions::TryNormalizeAfterErasingRegionsFolder as rustc_type_ir::fold::FallibleTypeFolder<rustc_middle::ty::context::TyCtxt>>::try_fold_ty
   9: rustc_ty_utils::needs_drop::needs_drop_raw
      [... omitted 1 frame ...]
  10: rustc_ty_utils::instance::resolve_instance
      [... omitted 1 frame ...]
  11: <rustc_middle::ty::instance::Instance>::resolve_drop_in_place
  12: rustc_monomorphize::collector::collect_used_items
  13: rustc_monomorphize::collector::collect_items_rec
  14: rustc_monomorphize::collector::collect_items_rec
  15: rustc_monomorphize::collector::collect_items_rec
  16: rustc_monomorphize::collector::collect_items_rec
  17: rustc_monomorphize::collector::collect_items_rec
  18: rustc_monomorphize::collector::collect_items_rec
  19: rustc_monomorphize::collector::collect_items_rec
  20: rustc_monomorphize::collector::collect_items_rec
  21: rustc_monomorphize::collector::collect_items_rec
  22: rustc_monomorphize::collector::collect_items_rec
  23: rustc_monomorphize::collector::collect_items_rec
  24: rustc_monomorphize::collector::collect_items_rec
  25: rustc_monomorphize::collector::collect_items_rec
  26: rustc_monomorphize::collector::collect_items_rec
  27: rustc_monomorphize::collector::collect_items_rec
  28: rustc_monomorphize::collector::collect_items_rec
  29: rustc_monomorphize::collector::collect_items_rec
  30: rustc_monomorphize::collector::collect_items_rec
  31: rustc_monomorphize::collector::collect_items_rec
  32: rustc_monomorphize::collector::collect_items_rec
  33: rustc_monomorphize::collector::collect_items_rec
  34: rustc_monomorphize::collector::collect_items_rec
  35: rustc_monomorphize::collector::collect_items_rec
  36: rustc_monomorphize::collector::collect_items_rec
  37: rustc_monomorphize::collector::collect_items_rec
  38: rustc_monomorphize::collector::collect_items_rec
  39: rustc_monomorphize::collector::collect_items_rec
  40: rustc_monomorphize::collector::collect_items_rec
  41: rustc_monomorphize::collector::collect_items_rec
  42: rustc_monomorphize::collector::collect_items_rec
  43: rustc_monomorphize::collector::collect_items_rec
  44: rustc_monomorphize::collector::collect_items_rec
  45: rustc_monomorphize::collector::collect_items_rec
  46: rustc_monomorphize::collector::collect_items_rec
  47: rustc_monomorphize::collector::collect_items_rec
  48: rustc_monomorphize::collector::collect_items_rec
  49: rustc_monomorphize::collector::collect_items_rec
  50: rustc_monomorphize::collector::collect_items_rec
  51: rustc_monomorphize::collector::collect_items_rec
  52: rustc_monomorphize::collector::collect_items_rec
  53: rustc_monomorphize::collector::collect_items_rec
  54: rustc_monomorphize::collector::collect_items_rec
  55: rustc_monomorphize::collector::collect_items_rec
  56: rustc_monomorphize::collector::collect_items_rec
  57: rustc_monomorphize::collector::collect_items_rec
  58: rustc_monomorphize::collector::collect_items_rec
  59: rustc_monomorphize::collector::collect_items_rec
  60: rustc_monomorphize::collector::collect_items_rec
  61: rustc_monomorphize::collector::collect_items_rec
  62: rustc_monomorphize::collector::collect_items_rec
  63: rustc_monomorphize::collector::collect_items_rec
  64: rustc_monomorphize::collector::collect_items_rec
  65: rustc_monomorphize::collector::collect_items_rec
  66: rustc_monomorphize::collector::collect_items_rec
  67: rustc_monomorphize::collector::collect_items_rec
  68: rustc_monomorphize::collector::collect_items_rec
  69: rustc_monomorphize::collector::collect_items_rec
  70: rustc_monomorphize::collector::collect_items_rec
  71: rustc_monomorphize::collector::collect_items_rec
  72: rustc_monomorphize::collector::collect_items_rec
  73: rustc_monomorphize::collector::collect_items_rec
  74: rustc_monomorphize::collector::collect_items_rec
  75: rustc_monomorphize::collector::collect_items_rec
  76: rustc_monomorphize::collector::collect_items_rec
  77: rustc_monomorphize::collector::collect_items_rec
  78: rustc_monomorphize::collector::collect_items_rec
  79: rustc_monomorphize::collector::collect_items_rec
  80: rustc_monomorphize::collector::collect_items_rec
  81: rustc_monomorphize::collector::collect_items_rec
  82: rustc_monomorphize::collector::collect_items_rec
  83: rustc_monomorphize::collector::collect_items_rec
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

error: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.74.0 (79e9716c9 2023-11-13) running on x86_64-unknown-linux-gnu

note: compiler flags: --crate-type bin -C embed-bitcode=no -C debuginfo=2 -C incremental=[REDACTED]

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [try_normalize_generic_arg_after_erasing_regions] normalizing `core::option::Option<<core::iter::adapters::skip::Skip<core::iter::adapters::peekable::Peekable<core::iter::adapters::skip::Skip<core::iter::adapters::peekable::Peekable<core::iter::adapters::skip::Skip<core::iter::adapters::peekable::Peekable<core::iter::adapters::skip::Skip<core::iter::adapters::peekable::Peekable<core::iter::adapters::skip::Skip<core::iter::adapters::peekable::Peekable<core::iter::adapters::skip::Skip<core::iter::adapters::peekable::Peekable<core::iter::adapters::skip::Skip<core::iter::adapters::peekable::Peekable<core::iter::adapters::skip::Skip<core::iter::adapters::peekable::Peekable<core::iter::adapters::skip::Skip<core::iter::adapters::peekable::Peekable<core::iter::adapters::skip::Skip<core::iter::adapters::peekable::Peekable<core::iter::adapters::skip::Skip<core::iter::adapters::peekable::Peekable<core::iter::adapters::skip::Skip<core::iter::adapters::peekable::Peekable<core::iter::adapters::skip::Skip<core::iter::adapters::peekable::Peekable<core::iter::adapters::skip::Skip<core::iter::adapters::peekable::Peekable<core::iter::adapters::skip::Skip<core::iter::adapters::peekable::Peekable<core::iter::adapters::skip::Skip<core::iter::adapters::peekable::Peekable<core::iter::adapters::skip::Skip<core::iter::adapters::peekable::Peekable<core::iter::adapters::skip::Skip<core::iter::adapters::peekable::Peekable<core::iter::adapters::skip::Skip<core::iter::adapters::peekable::Peekable<core::iter::adapters::skip::Skip<core::iter::adapters::peekable::Peekable<core::iter::adapters::skip::Skip<core::iter::adapters::peekable::Peekable<core::iter::adapters::skip::Skip<core::iter::adapters::peekable::Peekable<core::iter::adapters::skip::Skip<core::iter::adapters::peekable::Peekable<core::iter::adapters::skip::Skip<core::iter::adapters::peekable::Peekable<core::iter::adapters::skip::Skip<core::iter::adapters::peekable::Peekable<core::iter::adapters::skip::Skip<core::iter::adapters::peekable::Peekable<core::iter::adapters::skip::Skip<core::iter::adapters::peekable::Peekable<core::iter::adapters::skip::Skip<core::iter::adapters::peekable::Peekable<core::iter::adapters::skip::Skip<core::iter::adapters::peekable::Peekable<core::iter::adapters::skip::Skip<core::iter::adapters::peekable::Peekable<core::iter::adapters::skip::Skip<core::iter::adapters::peekable::Peekable<core::iter::adapters::skip::Skip<core::iter::adapters::peekable::Peekable<core::iter::adapters::skip::Skip<core::iter::adapters::peekable::Peekable<core::iter::adapters::skip::Skip<core::iter::adapters::peekable::Peekable<core::iter::adapters::skip::Skip<core::iter::adapters::peekable::Peekable<core::iter::adapters::skip::Skip<core::iter::adapters::peekable::Peekable<core::iter::adapters::skip::Skip<core::iter::adapters::peekable::Peekable<core::iter::adapters::skip::Skip<core::iter::adapters::peekable::Peekable<core::iter::adapters::skip::Skip<core::iter::adapters::peekable::Peekable<core::iter::adapters::skip::Skip<core::iter::adapters::peekable::Peekable<core::iter::adapters::skip::Skip<core::iter::adapters::peekable::Peekable<core::iter::adapters::skip::Skip<core::iter::adapters::peekable::Peekable<core::iter::adapters::skip::Skip<core::iter::adapters::peekable::Peekable<core::iter::adapters::skip::Skip<core::iter::adapters::peekable::Peekable<core::iter::adapters::skip::Skip<core::iter::adapters::peekable::Peekable<core::iter::adapters::skip::Skip<core::iter::adapters::peekable::Peekable<core::iter::adapters::skip::Skip<core::iter::adapters::peekable::Peekable<core::iter::adapters::skip::Skip<core::iter::adapters::peekable::Peekable<core::iter::adapters::skip::Skip<core::iter::adapters::peekable::Peekable<core::iter::adapters::skip::Skip<core::iter::adapters::peekable::Peekable<core::iter::adapters::skip::Skip<core::iter::adapters::peekable::Peekable<core::iter::adapters::skip::Skip<core::iter::adapters::peekable::Peekable<core::iter::adapters::skip::Skip<core::iter::adapters::peekable::Peekable<core::iter::adapters::skip::Skip<core::iter::adapters::peekable::Peekable<core::iter::adapters::skip::Skip<core::iter::adapters::peekable::Peekable<core::iter::adapters::skip::Skip<core::iter::adapters::peekable::Peekable<core::iter::adapters::skip::Skip<core::iter::adapters::peekable::Peekable<core::iter::adapters::skip::Skip<core::iter::adapters::peekable::Peekable<core::iter::adapters::skip::Skip<core::iter::adapters::peekable::Peekable<core::iter::adapters::skip::Skip<core::iter::adapters::peekable::Peekable<core::iter::adapters::skip::Skip<core::iter::adapters::peekable::Peekable<core::iter::adapters::skip::Skip<core::iter::adapters::peekable::Peekable<core::iter::adapters::skip::Skip<core::iter::adapters::peekable::Peekable<core::iter::adapters::skip::Skip<core::iter::adapters::peekable::Peekable<core::iter::adapters::skip::Skip<core::iter::adapters::peekable::Peekable<alloc::vec::into_iter::IntoIter<u32>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> as core::iter::traits::iterator::Iterator>::Item>`
#1 [needs_drop_raw] computing whether `core::iter::adapters::peekable::Peekable<core::iter::adapters::skip::Skip<core::iter::adapters::peekable::Peekable<core::iter::adapters::skip::Skip<core::iter::adapters::peekable::Peekable<core::iter::adapters::skip::Skip<core::iter::adapters::peekable::Peekable<core::iter::adapters::skip::Skip<core::iter::adapters::peekable::Peekable<core::iter::adapters::skip::Skip<core::iter::adapters::peekable::Peekable<core::iter::adapters::skip::Skip<core::iter::adapters::peekable::Peekable<core::iter::adapters::skip::Skip<core::iter::adapters::peekable::Peekable<core::iter::adapters::skip::Skip<core::iter::adapters::peekable::Peekable<core::iter::adapters::skip::Skip<core::iter::adapters::peekable::Peekable<core::iter::adapters::skip::Skip<core::iter::adapters::peekable::Peekable<core::iter::adapters::skip::Skip<core::iter::adapters::peekable::Peekable<core::iter::adapters::skip::Skip<core::iter::adapters::peekable::Peekable<core::iter::adapters::skip::Skip<core::iter::adapters::peekable::Peekable<core::iter::adapters::skip::Skip<core::iter::adapters::peekable::Peekable<core::iter::adapters::skip::Skip<core::iter::adapters::peekable::Peekable<core::iter::adapters::skip::Skip<core::iter::adapters::peekable::Peekable<core::iter::adapters::skip::Skip<core::iter::adapters::peekable::Peekable<core::iter::adapters::skip::Skip<core::iter::adapters::peekable::Peekable<core::iter::adapters::skip::Skip<core::iter::adapters::peekable::Peekable<core::iter::adapters::skip::Skip<core::iter::adapters::peekable::Peekable<core::iter::adapters::skip::Skip<core::iter::adapters::peekable::Peekable<core::iter::adapters::skip::Skip<core::iter::adapters::peekable::Peekable<core::iter::adapters::skip::Skip<core::iter::adapters::peekable::Peekable<core::iter::adapters::skip::Skip<core::iter::adapters::peekable::Peekable<core::iter::adapters::skip::Skip<core::iter::adapters::peekable::Peekable<core::iter::adapters::skip::Skip<core::iter::adapters::peekable::Peekable<core::iter::adapters::skip::Skip<core::iter::adapters::peekable::Peekable<core::iter::adapters::skip::Skip<core::iter::adapters::peekable::Peekable<core::iter::adapters::skip::Skip<core::iter::adapters::peekable::Peekable<core::iter::adapters::skip::Skip<core::iter::adapters::peekable::Peekable<core::iter::adapters::skip::Skip<core::iter::adapters::peekable::Peekable<core::iter::adapters::skip::Skip<core::iter::adapters::peekable::Peekable<core::iter::adapters::skip::Skip<core::iter::adapters::peekable::Peekable<core::iter::adapters::skip::Skip<core::iter::adapters::peekable::Peekable<core::iter::adapters::skip::Skip<core::iter::adapters::peekable::Peekable<core::iter::adapters::skip::Skip<core::iter::adapters::peekable::Peekable<core::iter::adapters::skip::Skip<core::iter::adapters::peekable::Peekable<core::iter::adapters::skip::Skip<core::iter::adapters::peekable::Peekable<core::iter::adapters::skip::Skip<core::iter::adapters::peekable::Peekable<core::iter::adapters::skip::Skip<core::iter::adapters::peekable::Peekable<core::iter::adapters::skip::Skip<core::iter::adapters::peekable::Peekable<core::iter::adapters::skip::Skip<core::iter::adapters::peekable::Peekable<core::iter::adapters::skip::Skip<core::iter::adapters::peekable::Peekable<core::iter::adapters::skip::Skip<core::iter::adapters::peekable::Peekable<core::iter::adapters::skip::Skip<core::iter::adapters::peekable::Peekable<core::iter::adapters::skip::Skip<core::iter::adapters::peekable::Peekable<core::iter::adapters::skip::Skip<core::iter::adapters::peekable::Peekable<core::iter::adapters::skip::Skip<core::iter::adapters::peekable::Peekable<core::iter::adapters::skip::Skip<core::iter::adapters::peekable::Peekable<core::iter::adapters::skip::Skip<core::iter::adapters::peekable::Peekable<core::iter::adapters::skip::Skip<core::iter::adapters::peekable::Peekable<core::iter::adapters::skip::Skip<core::iter::adapters::peekable::Peekable<core::iter::adapters::skip::Skip<core::iter::adapters::peekable::Peekable<core::iter::adapters::skip::Skip<core::iter::adapters::peekable::Peekable<core::iter::adapters::skip::Skip<core::iter::adapters::peekable::Peekable<core::iter::adapters::skip::Skip<core::iter::adapters::peekable::Peekable<core::iter::adapters::skip::Skip<core::iter::adapters::peekable::Peekable<core::iter::adapters::skip::Skip<core::iter::adapters::peekable::Peekable<core::iter::adapters::skip::Skip<core::iter::adapters::peekable::Peekable<core::iter::adapters::skip::Skip<core::iter::adapters::peekable::Peekable<core::iter::adapters::skip::Skip<core::iter::adapters::peekable::Peekable<core::iter::adapters::skip::Skip<core::iter::adapters::peekable::Peekable<core::iter::adapters::skip::Skip<core::iter::adapters::peekable::Peekable<core::iter::adapters::skip::Skip<core::iter::adapters::peekable::Peekable<core::iter::adapters::skip::Skip<core::iter::adapters::peekable::Peekable<alloc::vec::into_iter::IntoIter<u32>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>` needs drop
#2 [resolve_instance] resolving instance `core::ptr::drop_in_place::<core::iter::adapters::peekable::Peekable<core::iter::adapters::skip::Skip<core::iter::adapters::peekable::Peekable<core::iter::adapters::skip::Skip<core::iter::adapters::peekable::Peekable<core::iter::adapters::skip::Skip<core::iter::adapters::peekable::Peekable<core::iter::adapters::skip::Skip<core::iter::adapters::peekable::Peekable<core::iter::adapters::skip::Skip<core::iter::adapters::peekable::Peekable<core::iter::adapters::skip::Skip<core::iter::adapters::peekable::Peekable<core::iter::adapters::skip::Skip<core::iter::adapters::peekable::Peekable<core::iter::adapters::skip::Skip<core::iter::adapters::peekable::Peekable<core::iter::adapters::skip::Skip<core::iter::adapters::peekable::Peekable<core::iter::adapters::skip::Skip<core::iter::adapters::peekable::Peekable<core::iter::adapters::skip::Skip<core::iter::adapters::peekable::Peekable<core::iter::adapters::skip::Skip<core::iter::adapters::peekable::Peekable<core::iter::adapters::skip::Skip<core::iter::adapters::peekable::Peekable<core::iter::adapters::skip::Skip<core::iter::adapters::peekable::Peekable<core::iter::adapters::skip::Skip<core::iter::adapters::peekable::Peekable<core::iter::adapters::skip::Skip<core::iter::adapters::peekable::Peekable<core::iter::adapters::skip::Skip<core::iter::adapters::peekable::Peekable<core::iter::adapters::skip::Skip<core::iter::adapters::peekable::Peekable<core::iter::adapters::skip::Skip<core::iter::adapters::peekable::Peekable<core::iter::adapters::skip::Skip<core::iter::adapters::peekable::Peekable<core::iter::adapters::skip::Skip<core::iter::adapters::peekable::Peekable<core::iter::adapters::skip::Skip<core::iter::adapters::peekable::Peekable<core::iter::adapters::skip::Skip<core::iter::adapters::peekable::Peekable<core::iter::adapters::skip::Skip<core::iter::adapters::peekable::Peekable<core::iter::adapters::skip::Skip<core::iter::adapters::peekable::Peekable<core::iter::adapters::skip::Skip<core::iter::adapters::peekable::Peekable<core::iter::adapters::skip::Skip<core::iter::adapters::peekable::Peekable<core::iter::adapters::skip::Skip<core::iter::adapters::peekable::Peekable<core::iter::adapters::skip::Skip<core::iter::adapters::peekable::Peekable<core::iter::adapters::skip::Skip<core::iter::adapters::peekable::Peekable<core::iter::adapters::skip::Skip<core::iter::adapters::peekable::Peekable<core::iter::adapters::skip::Skip<core::iter::adapters::peekable::Peekable<core::iter::adapters::skip::Skip<core::iter::adapters::peekable::Peekable<core::iter::adapters::skip::Skip<core::iter::adapters::peekable::Peekable<core::iter::adapters::skip::Skip<core::iter::adapters::peekable::Peekable<core::iter::adapters::skip::Skip<core::iter::adapters::peekable::Peekable<core::iter::adapters::skip::Skip<core::iter::adapters::peekable::Peekable<core::iter::adapters::skip::Skip<core::iter::adapters::peekable::Peekable<core::iter::adapters::skip::Skip<core::iter::adapters::peekable::Peekable<core::iter::adapters::skip::Skip<core::iter::adapters::peekable::Peekable<core::iter::adapters::skip::Skip<core::iter::adapters::peekable::Peekable<core::iter::adapters::skip::Skip<core::iter::adapters::peekable::Peekable<core::iter::adapters::skip::Skip<core::iter::adapters::peekable::Peekable<core::iter::adapters::skip::Skip<core::iter::adapters::peekable::Peekable<core::iter::adapters::skip::Skip<core::iter::adapters::peekable::Peekable<core::iter::adapters::skip::Skip<core::iter::adapters::peekable::Peekable<core::iter::adapters::skip::Skip<core::iter::adapters::peekable::Peekable<core::iter::adapters::skip::Skip<core::iter::adapters::peekable::Peekable<core::iter::adapters::skip::Skip<core::iter::adapters::peekable::Peekable<core::iter::adapters::skip::Skip<core::iter::adapters::peekable::Peekable<core::iter::adapters::skip::Skip<core::iter::adapters::peekable::Peekable<core::iter::adapters::skip::Skip<core::iter::adapters::peekable::Peekable<core::iter::adapters::skip::Skip<core::iter::adapters::peekable::Peekable<core::iter::adapters::skip::Skip<core::iter::adapters::peekable::Peekable<core::iter::adapters::skip::Skip<core::iter::adapters::peekable::Peekable<core::iter::adapters::skip::Skip<core::iter::adapters::peekable::Peekable<core::iter::adapters::skip::Skip<core::iter::adapters::peekable::Peekable<core::iter::adapters::skip::Skip<core::iter::adapters::peekable::Peekable<core::iter::adapters::skip::Skip<core::iter::adapters::peekable::Peekable<core::iter::adapters::skip::Skip<core::iter::adapters::peekable::Peekable<core::iter::adapters::skip::Skip<core::iter::adapters::peekable::Peekable<core::iter::adapters::skip::Skip<core::iter::adapters::peekable::Peekable<core::iter::adapters::skip::Skip<core::iter::adapters::peekable::Peekable<core::iter::adapters::skip::Skip<core::iter::adapters::peekable::Peekable<core::iter::adapters::skip::Skip<core::iter::adapters::peekable::Peekable<alloc::vec::into_iter::IntoIter<u32>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>`
#3 [collect_and_partition_mono_items] collect_and_partition_mono_items
end of query stack
error: could not compile `advent-of-code-2023` (bin "day-04")
```

</p>
</details>

### LINKED ISSUE #122823: ICE: index out of bounds, snapshot vec
### Code

```Rust
use std::vec::Vec;
use std::iter::Peekable;

pub fn main() {
    let packet = decode(vec![1,0,1,0]);
}

pub fn decode(bitstream: Vec<u64>) -> Packet {
    let mut bitstream_itr = bitstream.into_iter().peekable();
    return match decode_packet(&mut bitstream_itr) {
        Some(p) => p,
        None    => panic!("expected outer packet"),
    }
}

pub fn decode_packets<I: Iterator<Item = u64>>(itr: &mut Peekable<I>) -> Vec<Packet> {
    let mut res = Vec::new();
    loop {
        match decode_packet(itr) {
            Some(p) => { res.push(p); },
            None    => break
        }
    }

    return res;
}

pub fn decode_packet<I: Iterator<Item = u64>>(itr: &mut Peekable<I>) -> Option<Packet> {
    // get version digits
    let version = extend_number(0, itr, 3)?;
    let type_id = extend_number(0, itr, 3)?;
    return operator_packet(version, type_id, itr);
}

pub fn operator_packet<I: Iterator<Item = u64>>(version: u64, type_id: u64, itr: &mut Peekable<I>) -> Option<Packet> {
    let p = OperatorPacket {
        version: version,
        type_id: type_id,
        packets: decode_packets(&mut itr.take(0).peekable()),
    };

    return Some(Packet::Operator(p));
}

pub fn extend_number<I: Iterator<Item = u64>>(num: u64, itr: &mut Peekable<I>, take: u64) -> Option<u64> {
    let mut value = num;
    for _ in 0..take {
        value *= 2;
        value += itr.next()?;
    }

    return Some(value);
}

#[derive(Debug)]
pub enum Packet {
    Operator(OperatorPacket),
}

#[derive(Debug)]
pub struct OperatorPacket {
    version: u64,
    type_id: u64,
    packets: Vec<Packet>
}
```

### Meta

`rustc --version --verbose`:
```

```

### Error output

```
warning: the item `Vec` is imported redundantly
   --> ./92004.rs:1:5
    |
1   | use std::vec::Vec;
    |     ^^^^^^^^^^^^^
    |
   ::: /home/gh-matthiaskrgr/.rustup/toolchains/master/lib/rustlib/src/rust/library/std/src/prelude/mod.rs:105:13
    |
105 |     pub use super::v1::*;
    |             --------- the item `Vec` is already defined here
    |
    = note: `#[warn(unused_imports)]` on by default

warning: unused variable: `packet`
 --> ./92004.rs:5:9
  |
5 |     let packet = decode(vec![1,0,1,0]);
  |         ^^^^^^ help: if this is intentional, prefix it with an underscore: `_packet`
  |
  = note: `#[warn(unused_variables)]` on by default

warning: fields `version`, `type_id`, and `packets` are never read
  --> ./92004.rs:62:5
   |
61 | pub struct OperatorPacket {
   |            -------------- fields in this struct
62 |     version: u64,
   |     ^^^^^^^
63 |     type_id: u64,
   |     ^^^^^^^
64 |     packets: Vec<Packet>
   |     ^^^^^^^
   |
   = note: `OperatorPacket` has a derived impl for the trait `Debug`, but this is intentionally ignored during dead code analysis
   = note: `#[warn(dead_code)]` on by default
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
thread 'rustc' panicked at /rust/deps/ena-0.14.2/src/snapshot_vec.rs:199:10:
index out of bounds: the len is 0 but the index is 0
stack backtrace:
   0:     0x7f0eb954ffa5 - std::backtrace_rs::backtrace::libunwind::trace::he2d7e0b4ceae414e
                               at /rustc/df8ac8f1d74cffb96a93ae702d16e224f5b9ee8c/library/std/src/../../backtrace/src/backtrace/libunwind.rs:105:5
   1:     0x7f0eb954ffa5 - std::backtrace_rs::backtrace::trace_unsynchronized::hdaffc19ffc09bde8
                               at /rustc/df8ac8f1d74cffb96a93ae702d16e224f5b9ee8c/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7f0eb954ffa5 - std::sys_common::backtrace::_print_fmt::hd4fb259cf7d0e8e3
                               at /rustc/df8ac8f1d74cffb96a93ae702d16e224f5b9ee8c/library/std/src/sys_common/backtrace.rs:68:5
   3:     0x7f0eb954ffa5 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h762a4aab0b589a4c
                               at /rustc/df8ac8f1d74cffb96a93ae702d16e224f5b9ee8c/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x7f0eb95a0feb - core::fmt::rt::Argument::fmt::hf72a54190dc4baa2
                               at /rustc/df8ac8f1d74cffb96a93ae702d16e224f5b9ee8c/library/core/src/fmt/rt.rs:142:9
   5:     0x7f0eb95a0feb - core::fmt::write::h24784e35e0380a3e
                               at /rustc/df8ac8f1d74cffb96a93ae702d16e224f5b9ee8c/library/core/src/fmt/mod.rs:1153:17
   6:     0x7f0eb9544d3f - std::io::Write::write_fmt::hb24b3a89fb200ddb
                               at /rustc/df8ac8f1d74cffb96a93ae702d16e224f5b9ee8c/library/std/src/io/mod.rs:1843:15
   7:     0x7f0eb954fd7e - std::sys_common::backtrace::_print::h0e48be87587a473e
                               at /rustc/df8ac8f1d74cffb96a93ae702d16e224f5b9ee8c/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x7f0eb954fd7e - std::sys_common::backtrace::print::h078f9026890c0b12
                               at /rustc/df8ac8f1d74cffb96a93ae702d16e224f5b9ee8c/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x7f0eb95529f9 - std::panicking::default_hook::{{closure}}::h19f2ef2f452cda43
  10:     0x7f0eb9552763 - std::panicking::default_hook::h0e9944bdb39da579
                               at /rustc/df8ac8f1d74cffb96a93ae702d16e224f5b9ee8c/library/std/src/panicking.rs:292:9
  11:     0x7f0eb5fceb9f - std[8c61ae4e9dc6f99a]::panicking::update_hook::<alloc[3095c8d5ffc1f53c]::boxed::Box<rustc_driver_impl[50dc0f0ce2053d12]::install_ice_hook::{closure#0}>>::{closure#0}
  12:     0x7f0eb9553150 - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::hfbae6ab25830f7c8
                               at /rustc/df8ac8f1d74cffb96a93ae702d16e224f5b9ee8c/library/alloc/src/boxed.rs:2029:9
  13:     0x7f0eb9553150 - std::panicking::rust_panic_with_hook::h33fb6d06d73e30d6
                               at /rustc/df8ac8f1d74cffb96a93ae702d16e224f5b9ee8c/library/std/src/panicking.rs:783:13
  14:     0x7f0eb9552ea6 - std::panicking::begin_panic_handler::{{closure}}::he600efcf8c3cf12a
                               at /rustc/df8ac8f1d74cffb96a93ae702d16e224f5b9ee8c/library/std/src/panicking.rs:657:13
  15:     0x7f0eb9550469 - std::sys_common::backtrace::__rust_end_short_backtrace::he9a6cadc9215c56f
                               at /rustc/df8ac8f1d74cffb96a93ae702d16e224f5b9ee8c/library/std/src/sys_common/backtrace.rs:171:18
  16:     0x7f0eb9552bd7 - rust_begin_unwind
                               at /rustc/df8ac8f1d74cffb96a93ae702d16e224f5b9ee8c/library/std/src/panicking.rs:645:5
  17:     0x7f0eb959d486 - core::panicking::panic_fmt::hd936952a5927c902
                               at /rustc/df8ac8f1d74cffb96a93ae702d16e224f5b9ee8c/library/core/src/panicking.rs:72:14
  18:     0x7f0eb959d6a7 - core::panicking::panic_bounds_check::h6249d6f447df14c3
                               at /rustc/df8ac8f1d74cffb96a93ae702d16e224f5b9ee8c/library/core/src/panicking.rs:205:5
  19:     0x7f0eb86395e8 - <ena[3fe8f2b21ea0da14]::unify::UnificationTable<ena[3fe8f2b21ea0da14]::unify::backing_vec::InPlace<rustc_infer[d94298ef228ce58b]::infer::type_variable::TyVidEqKey, &mut alloc[3095c8d5ffc1f53c]::vec::Vec<ena[3fe8f2b21ea0da14]::unify::VarValue<rustc_infer[d94298ef228ce58b]::infer::type_variable::TyVidEqKey>>, &mut rustc_infer[d94298ef228ce58b]::infer::snapshot::undo_log::InferCtxtUndoLogs>>>::uninlined_get_root_key.llvm.556618795195803917.cold
  20:     0x7f0eb49d4cee - <rustc_infer[d94298ef228ce58b]::infer::canonical::canonicalizer::Canonicalizer as rustc_type_ir[3b1757e14fa16666]::fold::TypeFolder<rustc_middle[dd5b3b6f0751d1e7]::ty::context::TyCtxt>>::fold_ty
  21:     0x7f0eb49d52a5 - <rustc_infer[d94298ef228ce58b]::infer::canonical::canonicalizer::Canonicalizer as rustc_type_ir[3b1757e14fa16666]::fold::TypeFolder<rustc_middle[dd5b3b6f0751d1e7]::ty::context::TyCtxt>>::fold_ty
  22:     0x7f0eb49d52a5 - <rustc_infer[d94298ef228ce58b]::infer::canonical::canonicalizer::Canonicalizer as rustc_type_ir[3b1757e14fa16666]::fold::TypeFolder<rustc_middle[dd5b3b6f0751d1e7]::ty::context::TyCtxt>>::fold_ty
  23:     0x7f0eb77853c5 - <rustc_infer[d94298ef228ce58b]::infer::canonical::canonicalizer::Canonicalizer as rustc_type_ir[3b1757e14fa16666]::fold::FallibleTypeFolder<rustc_middle[dd5b3b6f0751d1e7]::ty::context::TyCtxt>>::try_fold_predicate
  24:     0x7f0eb48e20af - rustc_ty_utils[818eeb7f16c0446]::common_traits::is_copy_raw
  25:     0x7f0eb78c6265 - rustc_query_impl[103b6eeeb95b654e]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[103b6eeeb95b654e]::query_impl::is_copy_raw::dynamic_query::{closure#2}::{closure#0}, rustc_middle[dd5b3b6f0751d1e7]::query::erase::Erased<[u8; 1usize]>>
  26:     0x7f0eb78c5953 - rustc_query_system[72071770fb0f9e7d]::query::plumbing::try_execute_query::<rustc_query_impl[103b6eeeb95b654e]::DynamicConfig<rustc_query_system[72071770fb0f9e7d]::query::caches::DefaultCache<rustc_middle[dd5b3b6f0751d1e7]::ty::ParamEnvAnd<rustc_middle[dd5b3b6f0751d1e7]::ty::Ty>, rustc_middle[dd5b3b6f0751d1e7]::query::erase::Erased<[u8; 1usize]>>, false, false, false>, rustc_query_impl[103b6eeeb95b654e]::plumbing::QueryCtxt, false>
  27:     0x7f0eb78c560e - rustc_query_impl[103b6eeeb95b654e]::query_impl::is_copy_raw::get_query_non_incr::__rust_end_short_backtrace
  28:     0x7f0eb78c6b18 - rustc_ty_utils[818eeb7f16c0446]::needs_drop::needs_drop_raw
  29:     0x7f0eb78c6547 - rustc_query_impl[103b6eeeb95b654e]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[103b6eeeb95b654e]::query_impl::needs_drop_raw::dynamic_query::{closure#2}::{closure#0}, rustc_middle[dd5b3b6f0751d1e7]::query::erase::Erased<[u8; 1usize]>>
  30:     0x7f0eb78c58fb - rustc_query_system[72071770fb0f9e7d]::query::plumbing::try_execute_query::<rustc_query_impl[103b6eeeb95b654e]::DynamicConfig<rustc_query_system[72071770fb0f9e7d]::query::caches::DefaultCache<rustc_middle[dd5b3b6f0751d1e7]::ty::ParamEnvAnd<rustc_middle[dd5b3b6f0751d1e7]::ty::Ty>, rustc_middle[dd5b3b6f0751d1e7]::query::erase::Erased<[u8; 1usize]>>, false, false, false>, rustc_query_impl[103b6eeeb95b654e]::plumbing::QueryCtxt, false>
  31:     0x7f0eb78c554e - rustc_query_impl[103b6eeeb95b654e]::query_impl::needs_drop_raw::get_query_non_incr::__rust_end_short_backtrace
  32:     0x7f0eb4e6510a - rustc_ty_utils[818eeb7f16c0446]::instance::resolve_instance
  33:     0x7f0eb79a8145 - rustc_query_impl[103b6eeeb95b654e]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[103b6eeeb95b654e]::query_impl::resolve_instance::dynamic_query::{closure#2}::{closure#0}, rustc_middle[dd5b3b6f0751d1e7]::query::erase::Erased<[u8; 32usize]>>
  34:     0x7f0eb79a8484 - rustc_query_system[72071770fb0f9e7d]::query::plumbing::try_execute_query::<rustc_query_impl[103b6eeeb95b654e]::DynamicConfig<rustc_query_system[72071770fb0f9e7d]::query::caches::DefaultCache<rustc_middle[dd5b3b6f0751d1e7]::ty::ParamEnvAnd<(rustc_span[df0a12af4122e9fb]::def_id::DefId, &rustc_middle[dd5b3b6f0751d1e7]::ty::list::List<rustc_middle[dd5b3b6f0751d1e7]::ty::generic_args::GenericArg>)>, rustc_middle[dd5b3b6f0751d1e7]::query::erase::Erased<[u8; 32usize]>>, false, false, false>, rustc_query_impl[103b6eeeb95b654e]::plumbing::QueryCtxt, false>
  35:     0x7f0eb79a80dd - rustc_query_impl[103b6eeeb95b654e]::query_impl::resolve_instance::get_query_non_incr::__rust_end_short_backtrace
  36:     0x7f0eb79aa466 - <rustc_middle[dd5b3b6f0751d1e7]::ty::instance::Instance>::resolve_drop_in_place
  37:     0x7f0eb4afc13f - rustc_monomorphize[cce86ba432f7b2a0]::collector::collect_items_rec::{closure#0}
  38:     0x7f0eb81a0392 - rustc_monomorphize[cce86ba432f7b2a0]::collector::collect_items_rec
  39:     0x7f0eb81a0d50 - rustc_monomorphize[cce86ba432f7b2a0]::collector::collect_items_rec
  40:     0x7f0eb81a0d50 - rustc_monomorphize[cce86ba432f7b2a0]::collector::collect_items_rec
  41:     0x7f0eb81a0d50 - rustc_monomorphize[cce86ba432f7b2a0]::collector::collect_items_rec
  42:     0x7f0eb81a0d50 - rustc_monomorphize[cce86ba432f7b2a0]::collector::collect_items_rec
  43:     0x7f0eb81a0d50 - rustc_monomorphize[cce86ba432f7b2a0]::collector::collect_items_rec
  44:     0x7f0eb81a0d50 - rustc_monomorphize[cce86ba432f7b2a0]::collector::collect_items_rec
  45:     0x7f0eb81a0d50 - rustc_monomorphize[cce86ba432f7b2a0]::collector::collect_items_rec
  46:     0x7f0eb81a0d50 - rustc_monomorphize[cce86ba432f7b2a0]::collector::collect_items_rec
  47:     0x7f0eb81a0d50 - rustc_monomorphize[cce86ba432f7b2a0]::collector::collect_items_rec
  48:     0x7f0eb81a0d50 - rustc_monomorphize[cce86ba432f7b2a0]::collector::collect_items_rec
  49:     0x7f0eb81a0d50 - rustc_monomorphize[cce86ba432f7b2a0]::collector::collect_items_rec
  50:     0x7f0eb81a0d50 - rustc_monomorphize[cce86ba432f7b2a0]::collector::collect_items_rec
  51:     0x7f0eb81a0d50 - rustc_monomorphize[cce86ba432f7b2a0]::collector::collect_items_rec
  52:     0x7f0eb81a0d50 - rustc_monomorphize[cce86ba432f7b2a0]::collector::collect_items_rec
  53:     0x7f0eb81a0d50 - rustc_monomorphize[cce86ba432f7b2a0]::collector::collect_items_rec
  54:     0x7f0eb81a0d50 - rustc_monomorphize[cce86ba432f7b2a0]::collector::collect_items_rec
  55:     0x7f0eb81a0d50 - rustc_monomorphize[cce86ba432f7b2a0]::collector::collect_items_rec
  56:     0x7f0eb81a0d50 - rustc_monomorphize[cce86ba432f7b2a0]::collector::collect_items_rec
  57:     0x7f0eb81a0d50 - rustc_monomorphize[cce86ba432f7b2a0]::collector::collect_items_rec
  58:     0x7f0eb81a0d50 - rustc_monomorphize[cce86ba432f7b2a0]::collector::collect_items_rec
  59:     0x7f0eb81a0d50 - rustc_monomorphize[cce86ba432f7b2a0]::collector::collect_items_rec
  60:     0x7f0eb81a0d50 - rustc_monomorphize[cce86ba432f7b2a0]::collector::collect_items_rec
  61:     0x7f0eb81a0d50 - rustc_monomorphize[cce86ba432f7b2a0]::collector::collect_items_rec
  62:     0x7f0eb81a0d50 - rustc_monomorphize[cce86ba432f7b2a0]::collector::collect_items_rec
  63:     0x7f0eb81a0d50 - rustc_monomorphize[cce86ba432f7b2a0]::collector::collect_items_rec
  64:     0x7f0eb81a0d50 - rustc_monomorphize[cce86ba432f7b2a0]::collector::collect_items_rec
  65:     0x7f0eb81a0d50 - rustc_monomorphize[cce86ba432f7b2a0]::collector::collect_items_rec
  66:     0x7f0eb81a0d50 - rustc_monomorphize[cce86ba432f7b2a0]::collector::collect_items_rec
  67:     0x7f0eb81a0d50 - rustc_monomorphize[cce86ba432f7b2a0]::collector::collect_items_rec
  68:     0x7f0eb81a0d50 - rustc_monomorphize[cce86ba432f7b2a0]::collector::collect_items_rec
  69:     0x7f0eb81a0d50 - rustc_monomorphize[cce86ba432f7b2a0]::collector::collect_items_rec
  70:     0x7f0eb81a0d50 - rustc_monomorphize[cce86ba432f7b2a0]::collector::collect_items_rec
  71:     0x7f0eb81a0d50 - rustc_monomorphize[cce86ba432f7b2a0]::collector::collect_items_rec
  72:     0x7f0eb81a0d50 - rustc_monomorphize[cce86ba432f7b2a0]::collector::collect_items_rec
  73:     0x7f0eb81a0d50 - rustc_monomorphize[cce86ba432f7b2a0]::collector::collect_items_rec
  74:     0x7f0eb81a0d50 - rustc_monomorphize[cce86ba432f7b2a0]::collector::collect_items_rec
  75:     0x7f0eb81a0d50 - rustc_monomorphize[cce86ba432f7b2a0]::collector::collect_items_rec
  76:     0x7f0eb81a0d50 - rustc_monomorphize[cce86ba432f7b2a0]::collector::collect_items_rec
  77:     0x7f0eb81a0d50 - rustc_monomorphize[cce86ba432f7b2a0]::collector::collect_items_rec
  78:     0x7f0eb81a0d50 - rustc_monomorphize[cce86ba432f7b2a0]::collector::collect_items_rec
  79:     0x7f0eb81a0d50 - rustc_monomorphize[cce86ba432f7b2a0]::collector::collect_items_rec
  80:     0x7f0eb81a0d50 - rustc_monomorphize[cce86ba432f7b2a0]::collector::collect_items_rec
  81:     0x7f0eb81a0d50 - rustc_monomorphize[cce86ba432f7b2a0]::collector::collect_items_rec
  82:     0x7f0eb81a0d50 - rustc_monomorphize[cce86ba432f7b2a0]::collector::collect_items_rec
  83:     0x7f0eb81a0d50 - rustc_monomorphize[cce86ba432f7b2a0]::collector::collect_items_rec
  84:     0x7f0eb81a0d50 - rustc_monomorphize[cce86ba432f7b2a0]::collector::collect_items_rec
  85:     0x7f0eb81a0d50 - rustc_monomorphize[cce86ba432f7b2a0]::collector::collect_items_rec
  86:     0x7f0eb81a0d50 - rustc_monomorphize[cce86ba432f7b2a0]::collector::collect_items_rec
  87:     0x7f0eb81a0d50 - rustc_monomorphize[cce86ba432f7b2a0]::collector::collect_items_rec
  88:     0x7f0eb81a0d50 - rustc_monomorphize[cce86ba432f7b2a0]::collector::collect_items_rec
  89:     0x7f0eb81a0d50 - rustc_monomorphize[cce86ba432f7b2a0]::collector::collect_items_rec
  90:     0x7f0eb81a0d50 - rustc_monomorphize[cce86ba432f7b2a0]::collector::collect_items_rec
  91:     0x7f0eb81a0d50 - rustc_monomorphize[cce86ba432f7b2a0]::collector::collect_items_rec
  92:     0x7f0eb81a0d50 - rustc_monomorphize[cce86ba432f7b2a0]::collector::collect_items_rec
  93:     0x7f0eb81a0d50 - rustc_monomorphize[cce86ba432f7b2a0]::collector::collect_items_rec
  94:     0x7f0eb81a0d50 - rustc_monomorphize[cce86ba432f7b2a0]::collector::collect_items_rec
  95:     0x7f0eb81a0d50 - rustc_monomorphize[cce86ba432f7b2a0]::collector::collect_items_rec
  96:     0x7f0eb81a0d50 - rustc_monomorphize[cce86ba432f7b2a0]::collector::collect_items_rec
  97:     0x7f0eb81a0d50 - rustc_monomorphize[cce86ba432f7b2a0]::collector::collect_items_rec
  98:     0x7f0eb81a0d50 - rustc_monomorphize[cce86ba432f7b2a0]::collector::collect_items_rec
  99:     0x7f0eb81a0d50 - rustc_monomorphize[cce86ba432f7b2a0]::collector::collect_items_rec
 100:     0x7f0eb81a0d50 - rustc_monomorphize[cce86ba432f7b2a0]::collector::collect_items_rec
 101:     0x7f0eb81a0d50 - rustc_monomorphize[cce86ba432f7b2a0]::collector::collect_items_rec
 102:     0x7f0eb81a0d50 - rustc_monomorphize[cce86ba432f7b2a0]::collector::collect_items_rec
 103:     0x7f0eb81a0d50 - rustc_monomorphize[cce86ba432f7b2a0]::collector::collect_items_rec
 104:     0x7f0eb81a0d50 - rustc_monomorphize[cce86ba432f7b2a0]::collector::collect_items_rec
 105:     0x7f0eb81a0d50 - rustc_monomorphize[cce86ba432f7b2a0]::collector::collect_items_rec
 106:     0x7f0eb81a0d50 - rustc_monomorphize[cce86ba432f7b2a0]::collector::collect_items_rec
 107:     0x7f0eb81a0d50 - rustc_monomorphize[cce86ba432f7b2a0]::collector::collect_items_rec
 108:     0x7f0eb81a0d50 - rustc_monomorphize[cce86ba432f7b2a0]::collector::collect_items_rec
 109:     0x7f0eb81a0d50 - rustc_monomorphize[cce86ba432f7b2a0]::collector::collect_items_rec
 110:     0x7f0eb81a0d50 - rustc_monomorphize[cce86ba432f7b2a0]::collector::collect_items_rec
 111:     0x7f0eb81a0d50 - rustc_monomorphize[cce86ba432f7b2a0]::collector::collect_items_rec
 112:     0x7f0eb81a0d50 - rustc_monomorphize[cce86ba432f7b2a0]::collector::collect_items_rec
 113:     0x7f0eb81a0d50 - rustc_monomorphize[cce86ba432f7b2a0]::collector::collect_items_rec
 114:     0x7f0eb81a0d50 - rustc_monomorphize[cce86ba432f7b2a0]::collector::collect_items_rec
 115:     0x7f0eb81a0d50 - rustc_monomorphize[cce86ba432f7b2a0]::collector::collect_items_rec
 116:     0x7f0eb81a0d50 - rustc_monomorphize[cce86ba432f7b2a0]::collector::collect_items_rec
 117:     0x7f0eb81a0d50 - rustc_monomorphize[cce86ba432f7b2a0]::collector::collect_items_rec
 118:     0x7f0eb81a0d50 - rustc_monomorphize[cce86ba432f7b2a0]::collector::collect_items_rec
 119:     0x7f0eb81a0d50 - rustc_monomorphize[cce86ba432f7b2a0]::collector::collect_items_rec
 120:     0x7f0eb81a0d50 - rustc_monomorphize[cce86ba432f7b2a0]::collector::collect_items_rec
 121:     0x7f0eb81a0d50 - rustc_monomorphize[cce86ba432f7b2a0]::collector::collect_items_rec
 122:     0x7f0eb81a0d50 - rustc_monomorphize[cce86ba432f7b2a0]::collector::collect_items_rec
 123:     0x7f0eb81a0d50 - rustc_monomorphize[cce86ba432f7b2a0]::collector::collect_items_rec
 124:     0x7f0eb81a0d50 - rustc_monomorphize[cce86ba432f7b2a0]::collector::collect_items_rec
 125:     0x7f0eb81a0d50 - rustc_monomorphize[cce86ba432f7b2a0]::collector::collect_items_rec
 126:     0x7f0eb81a0d50 - rustc_monomorphize[cce86ba432f7b2a0]::collector::collect_items_rec
 127:     0x7f0eb81a0d50 - rustc_monomorphize[cce86ba432f7b2a0]::collector::collect_items_rec
 128:     0x7f0eb81a0d50 - rustc_monomorphize[cce86ba432f7b2a0]::collector::collect_items_rec
 129:     0x7f0eb81a0d50 - rustc_monomorphize[cce86ba432f7b2a0]::collector::collect_items_rec
 130:     0x7f0eb81a0d50 - rustc_monomorphize[cce86ba432f7b2a0]::collector::collect_items_rec
 131:     0x7f0eb81a0d50 - rustc_monomorphize[cce86ba432f7b2a0]::collector::collect_items_rec
 132:     0x7f0eb81a0d50 - rustc_monomorphize[cce86ba432f7b2a0]::collector::collect_items_rec
 133:     0x7f0eb81a0d50 - rustc_monomorphize[cce86ba432f7b2a0]::collector::collect_items_rec
 134:     0x7f0eb81a0d50 - rustc_monomorphize[cce86ba432f7b2a0]::collector::collect_items_rec
 135:     0x7f0eb81a0d50 - rustc_monomorphize[cce86ba432f7b2a0]::collector::collect_items_rec
 136:     0x7f0eb81a0d50 - rustc_monomorphize[cce86ba432f7b2a0]::collector::collect_items_rec
 137:     0x7f0eb81a0d50 - rustc_monomorphize[cce86ba432f7b2a0]::collector::collect_items_rec
 138:     0x7f0eb81a0d50 - rustc_monomorphize[cce86ba432f7b2a0]::collector::collect_items_rec
 139:     0x7f0eb81a0d50 - rustc_monomorphize[cce86ba432f7b2a0]::collector::collect_items_rec
 140:     0x7f0eb81a0d50 - rustc_monomorphize[cce86ba432f7b2a0]::collector::collect_items_rec
 141:     0x7f0eb81a0d50 - rustc_monomorphize[cce86ba432f7b2a0]::collector::collect_items_rec
 142:     0x7f0eb81a0d50 - rustc_monomorphize[cce86ba432f7b2a0]::collector::collect_items_rec
 143:     0x7f0eb81a0d50 - rustc_monomorphize[cce86ba432f7b2a0]::collector::collect_items_rec
 144:     0x7f0eb81a0d50 - rustc_monomorphize[cce86ba432f7b2a0]::collector::collect_items_rec
 145:     0x7f0eb81a0d50 - rustc_monomorphize[cce86ba432f7b2a0]::collector::collect_items_rec
 146:     0x7f0eb81a0d50 - rustc_monomorphize[cce86ba432f7b2a0]::collector::collect_items_rec
 147:     0x7f0eb81a0d50 - rustc_monomorphize[cce86ba432f7b2a0]::collector::collect_items_rec
 148:     0x7f0eb81a0d50 - rustc_monomorphize[cce86ba432f7b2a0]::collector::collect_items_rec
 149:     0x7f0eb81a0d50 - rustc_monomorphize[cce86ba432f7b2a0]::collector::collect_items_rec
 150:     0x7f0eb81a0d50 - rustc_monomorphize[cce86ba432f7b2a0]::collector::collect_items_rec
 151:     0x7f0eb81a0d50 - rustc_monomorphize[cce86ba432f7b2a0]::collector::collect_items_rec
 152:     0x7f0eb81a0d50 - rustc_monomorphize[cce86ba432f7b2a0]::collector::collect_items_rec
 153:     0x7f0eb81a0d50 - rustc_monomorphize[cce86ba432f7b2a0]::collector::collect_items_rec
 154:     0x7f0eb81a0d50 - rustc_monomorphize[cce86ba432f7b2a0]::collector::collect_items_rec
 155:     0x7f0eb81a0d50 - rustc_monomorphize[cce86ba432f7b2a0]::collector::collect_items_rec
 156:     0x7f0eb81a0d50 - rustc_monomorphize[cce86ba432f7b2a0]::collector::collect_items_rec
 157:     0x7f0eb81a0d50 - rustc_monomorphize[cce86ba432f7b2a0]::collector::collect_items_rec
 158:     0x7f0eb81a0d50 - rustc_monomorphize[cce86ba432f7b2a0]::collector::collect_items_rec
 159:     0x7f0eb81a0d50 - rustc_monomorphize[cce86ba432f7b2a0]::collector::collect_items_rec
 160:     0x7f0eb81a0d50 - rustc_monomorphize[cce86ba432f7b2a0]::collector::collect_items_rec
 161:     0x7f0eb81a0d50 - rustc_monomorphize[cce86ba432f7b2a0]::collector::collect_items_rec
 162:     0x7f0eb81a0d50 - rustc_monomorphize[cce86ba432f7b2a0]::collector::collect_items_rec
 163:     0x7f0eb81a0d50 - rustc_monomorphize[cce86ba432f7b2a0]::collector::collect_items_rec
 164:     0x7f0eb81a0d50 - rustc_monomorphize[cce86ba432f7b2a0]::collector::collect_items_rec
 165:     0x7f0eb81a0d50 - rustc_monomorphize[cce86ba432f7b2a0]::collector::collect_items_rec
 166:     0x7f0eb81a0d50 - rustc_monomorphize[cce86ba432f7b2a0]::collector::collect_items_rec
 167:     0x7f0eb81a0d50 - rustc_monomorphize[cce86ba432f7b2a0]::collector::collect_items_rec
 168:     0x7f0eb81a0d50 - rustc_monomorphize[cce86ba432f7b2a0]::collector::collect_items_rec
 169:     0x7f0eb81a0d50 - rustc_monomorphize[cce86ba432f7b2a0]::collector::collect_items_rec
 170:     0x7f0eb81a0d50 - rustc_monomorphize[cce86ba432f7b2a0]::collector::collect_items_rec
 171:     0x7f0eb81a0d50 - rustc_monomorphize[cce86ba432f7b2a0]::collector::collect_items_rec
 172:     0x7f0eb8198df6 - rustc_monomorphize[cce86ba432f7b2a0]::partitioning::collect_and_partition_mono_items
 173:     0x7f0eb81983ee - rustc_query_impl[103b6eeeb95b654e]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[103b6eeeb95b654e]::query_impl::collect_and_partition_mono_items::dynamic_query::{closure#2}::{closure#0}, rustc_middle[dd5b3b6f0751d1e7]::query::erase::Erased<[u8; 24usize]>>
 174:     0x7f0eb81983d3 - <rustc_query_impl[103b6eeeb95b654e]::query_impl::collect_and_partition_mono_items::dynamic_query::{closure#2} as core[db3fd14870e16b34]::ops::function::FnOnce<(rustc_middle[dd5b3b6f0751d1e7]::ty::context::TyCtxt, ())>>::call_once
 175:     0x7f0eb823d6ce - rustc_query_system[72071770fb0f9e7d]::query::plumbing::try_execute_query::<rustc_query_impl[103b6eeeb95b654e]::DynamicConfig<rustc_query_system[72071770fb0f9e7d]::query::caches::SingleCache<rustc_middle[dd5b3b6f0751d1e7]::query::erase::Erased<[u8; 24usize]>>, false, false, false>, rustc_query_impl[103b6eeeb95b654e]::plumbing::QueryCtxt, false>
 176:     0x7f0eb823d3c5 - rustc_query_impl[103b6eeeb95b654e]::query_impl::collect_and_partition_mono_items::get_query_non_incr::__rust_end_short_backtrace
 177:     0x7f0eb82d0af0 - rustc_codegen_ssa[5284b279088479b5]::base::codegen_crate::<rustc_codegen_llvm[3fb2aaf30ffb7008]::LlvmCodegenBackend>
 178:     0x7f0eb82c3e29 - <rustc_codegen_llvm[3fb2aaf30ffb7008]::LlvmCodegenBackend as rustc_codegen_ssa[5284b279088479b5]::traits::backend::CodegenBackend>::codegen_crate
 179:     0x7f0eb82c379f - rustc_interface[f82c04bf8d9e9e5f]::passes::start_codegen
 180:     0x7f0eb82c2f33 - <rustc_interface[f82c04bf8d9e9e5f]::queries::Queries>::codegen_and_build_linker
 181:     0x7f0eb80905d6 - rustc_interface[f82c04bf8d9e9e5f]::interface::run_compiler::<core[db3fd14870e16b34]::result::Result<(), rustc_span[df0a12af4122e9fb]::ErrorGuaranteed>, rustc_driver_impl[50dc0f0ce2053d12]::run_compiler::{closure#0}>::{closure#0}
 182:     0x7f0eb815cac5 - std[8c61ae4e9dc6f99a]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[f82c04bf8d9e9e5f]::util::run_in_thread_with_globals<rustc_interface[f82c04bf8d9e9e5f]::util::run_in_thread_pool_with_globals<rustc_interface[f82c04bf8d9e9e5f]::interface::run_compiler<core[db3fd14870e16b34]::result::Result<(), rustc_span[df0a12af4122e9fb]::ErrorGuaranteed>, rustc_driver_impl[50dc0f0ce2053d12]::run_compiler::{closure#0}>::{closure#0}, core[db3fd14870e16b34]::result::Result<(), rustc_span[df0a12af4122e9fb]::ErrorGuaranteed>>::{closure#0}, core[db3fd14870e16b34]::result::Result<(), rustc_span[df0a12af4122e9fb]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[db3fd14870e16b34]::result::Result<(), rustc_span[df0a12af4122e9fb]::ErrorGuaranteed>>
 183:     0x7f0eb815c8f2 - <<std[8c61ae4e9dc6f99a]::thread::Builder>::spawn_unchecked_<rustc_interface[f82c04bf8d9e9e5f]::util::run_in_thread_with_globals<rustc_interface[f82c04bf8d9e9e5f]::util::run_in_thread_pool_with_globals<rustc_interface[f82c04bf8d9e9e5f]::interface::run_compiler<core[db3fd14870e16b34]::result::Result<(), rustc_span[df0a12af4122e9fb]::ErrorGuaranteed>, rustc_driver_impl[50dc0f0ce2053d12]::run_compiler::{closure#0}>::{closure#0}, core[db3fd14870e16b34]::result::Result<(), rustc_span[df0a12af4122e9fb]::ErrorGuaranteed>>::{closure#0}, core[db3fd14870e16b34]::result::Result<(), rustc_span[df0a12af4122e9fb]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[db3fd14870e16b34]::result::Result<(), rustc_span[df0a12af4122e9fb]::ErrorGuaranteed>>::{closure#1} as core[db3fd14870e16b34]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
 184:     0x7f0eb955c919 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h8bca559b886796e2
                               at /rustc/df8ac8f1d74cffb96a93ae702d16e224f5b9ee8c/library/alloc/src/boxed.rs:2015:9
 185:     0x7f0eb955c919 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h6921d0e12fce02bd
                               at /rustc/df8ac8f1d74cffb96a93ae702d16e224f5b9ee8c/library/alloc/src/boxed.rs:2015:9
 186:     0x7f0eb955c919 - std::sys::pal::unix::thread::Thread::new::thread_start::hba4f4afbe9e3ea3d
                               at /rustc/df8ac8f1d74cffb96a93ae702d16e224f5b9ee8c/library/std/src/sys/pal/unix/thread.rs:108:17
 187:     0x7f0eb2c94ac3 - start_thread
                               at ./nptl/pthread_create.c:442:8
 188:     0x7f0eb2d26850 - __GI___clone3
                               at ./misc/../sysdeps/unix/sysv/linux/x86_64/clone3.S:81
 189:                0x0 - <unknown>

error: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: please attach the file at `/home/gh-matthiaskrgr/vcs/github/glacier2/fixed/rustc-ice-2024-03-21T11_22_20-907115.txt` to your bug report

query stack during panic:
thread panicked while processing panic. aborting.
Aborted (core dumped)
```

</p>
</details>

### LINKED ISSUE #131342: `core::iter::adapters::peekable` + recursion + pattern matching on `peek` causes compiler panic
I tried this code:

```rust
fn main() {
  let mut items = vec![1, 2, 3, 4, 5].into_iter();
  problem_thingy(&mut items);
}

fn problem_thingy(items: &mut impl Iterator<Item = u8>) {
  let mut peeker = items.peekable();
  match peeker.peek() {
    Some(_) => (),
    None => return (),
  }
  problem_thingy(&mut peeker);
}
```

I expected to see this happen: either continuously have the first item be "peeked" at, or return `()` on the final iteration after exhausting other peeks.

Instead, this happened: compiler panicked with an unbearably large error message. I believe this has to do with allocation and pointer safety with `Peekable`, but I could be way off.

### Meta

`rustc --version --verbose`:
```
rustc 1.81.0 (eeb90cda1 2024-09-04)                                                  
binary: rustc                                                                        
commit-hash: eeb90cda1969383f56a2637cbd3037bdf598841c                                
commit-date: 2024-09-04                                                              
host: x86_64-unknown-linux-gnu                                                       
release: 1.81.0                                                                      
LLVM version: 18.1.7        
```

Backtrace and compiler output are unbearably large for this issue, so I've attached them below.

[bare_build.txt](https://github.com/user-attachments/files/17271473/bare_build.txt)
[backtrace_build.txt](https://github.com/user-attachments/files/17271476/backtrace_build.txt)

</p>
</details>

### LINKED ISSUE #139659: ICE: compiler/rustc_middle/src/ty/normalize_erasing_regions.rs:169:13: Failed to normalize Alias(...
### Code

```Rust
trait Trait {
    type Output;
}

impl<O, F: Fn() -> O> Trait for F {
    type Output = O;
}

struct Wrap<P>(P);
struct WrapOutput<O>(O);

impl<P: Trait> Trait for Wrap<P> {
    type Output = WrapOutput<P::Output>;
}

fn wrap<P: Trait>(x: P) -> impl Trait {
    Wrap(x)
}

fn consume<P: Trait>(_: P) -> P::Output {
    unimplemented!()
}

pub fn recurse() -> impl Sized {
    consume(wrap(recurse))
}
```

Note: Reproducing this ICE requires `cargo build`. Using `cargo check` compiles fine.

Minimized from real code written by fearless_process on the rust community discord.

Very similar to #139658, which instead gives "overflow evaluating the requirement".

### Meta

`rustc --version --verbose`:
```
rustc 1.86.0 (05f9846f8 2025-03-31)
binary: rustc
commit-hash: 05f9846f893b09a1be1fc8560e33fc3c815cfecb
commit-date: 2025-03-31
host: aarch64-apple-darwin
release: 1.86.0
LLVM version: 19.1.7
```

The issue also reproduces on `rustc 1.88.0-nightly (0fe8f3454 2025-04-10)`.

### Error output

```
error: internal compiler error: compiler/rustc_middle/src/ty/normalize_erasing_regions.rs:169:13: Failed to normalize Alias(Opaque, AliasTy { args: [], def_id: DefId(0:26 ~ foo[b3e3]::recurse::{opaque#0}), .. }) in typing_env=TypingEnv { typing_mode: PostAnalysis, param_env: ParamEnv { caller_bounds: [] } }, maybe try to call `try_normalize_erasing_regions` instead
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
thread 'rustc' panicked at compiler/rustc_middle/src/ty/normalize_erasing_regions.rs:169:13:
Box<dyn Any>
stack backtrace:
   0: std::panicking::begin_panic::<rustc_errors::ExplicitBug>
   1: <rustc_errors::diagnostic::BugAbort as rustc_errors::diagnostic::EmissionGuarantee>::emit_producing_guarantee
   2: rustc_middle::util::bug::opt_span_bug_fmt::<rustc_span::span_encoding::Span>::{closure#0}
   3: rustc_middle::ty::context::tls::with_opt::<rustc_middle::util::bug::opt_span_bug_fmt<rustc_span::span_encoding::Span>::{closure#0}, !>::{closure#0}
   4: rustc_middle::ty::context::tls::with_context_opt::<rustc_middle::ty::context::tls::with_opt<rustc_middle::util::bug::opt_span_bug_fmt<rustc_span::span_encoding::Span>::{closure#0}, !>::{closure#0}, !>
   5: rustc_middle::util::bug::bug_fmt
   6: rustc_ty_utils::abi::fn_abi_new_uncached
   7: rustc_ty_utils::abi::fn_abi_of_instance
      [... omitted 2 frames ...]
   8: rustc_middle::query::plumbing::query_get_at::<rustc_query_system::query::caches::DefaultCache<rustc_middle::ty::PseudoCanonicalInput<(rustc_middle::ty::instance::Instance, &rustc_middle::ty::list::RawList<(), rustc_middle::ty::Ty>)>, rustc_middle::query::erase::Erased<[u8; 16]>>>
   9: rustc_monomorphize::mono_checks::check_mono_item
      [... omitted 2 frames ...]
  10: rustc_monomorphize::collector::items_of_instance
      [... omitted 2 frames ...]
  11: rustc_monomorphize::collector::collect_items_rec::{closure#0}
  12: rustc_monomorphize::collector::collect_items_rec
  13: rustc_monomorphize::collector::collect_crate_mono_items
  14: rustc_monomorphize::partitioning::collect_and_partition_mono_items
      [... omitted 5 frames ...]
  15: <rustc_metadata::rmeta::encoder::EncodeContext>::encode_crate_root
  16: rustc_metadata::rmeta::encoder::encode_metadata
  17: rustc_metadata::fs::encode_and_write_metadata
  18: <rustc_interface::queries::Linker>::codegen_and_build_linker
  19: rustc_interface::passes::create_and_enter_global_ctxt::<core::option::Option<rustc_interface::queries::Linker>, rustc_driver_impl::run_compiler::{closure#0}::{closure#2}>
  20: rustc_interface::interface::run_compiler::<(), rustc_driver_impl::run_compiler::{closure#0}>::{closure#1}
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.86.0 (05f9846f8 2025-03-31) running on aarch64-apple-darwin

note: compiler flags: --crate-type lib -C embed-bitcode=no -C debuginfo=2 -C split-debuginfo=unpacked -C incremental=[REDACTED]

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [fn_abi_of_instance] computing call ABI of `recurse`
#1 [check_mono_item] monomorphization-time checking
#2 [items_of_instance] collecting items used by `recurse`
#3 [collect_and_partition_mono_items] collect_and_partition_mono_items
#4 [exported_symbols] collecting exported symbols for crate `0`
end of query stack
there was a panic while trying to force a dep node
try_mark_green dep node stack:
#0 exported_symbols(foo[b3e3])
end of try_mark_green dep node stack
error: could not compile `foo` (lib)

Caused by:
  process didn't exit successfully: `/Users/timch/.rustup/toolchains/stable-aarch64-apple-darwin/bin/rustc --crate-name foo --edition=2024 src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --diagnostic-width=204 --crate-type lib --emit=dep-info,metadata,link -C embed-bitcode=no -C debuginfo=2 -C split-debuginfo=unpacked --check-cfg 'cfg(docsrs,test)' --check-cfg 'cfg(feature, values())' -C metadata=61fd0e4f3351c637 -C extra-filename=-2bc4f207b16319e9 --out-dir /Users/timch/foo/target/debug/deps -C incremental=/Users/timch/foo/target/debug/incremental -L dependency=/Users/timch/foo/target/debug/deps` (exit status: 101)
```

</p>
</details>

### PR DESCRIPTION
**Pull request by adwinwhite**
Fixes rust-lang/rust#92004
Fixes rust-lang/rust#92470
Fixes rust-lang/rust#95134
Fixes rust-lang/rust#105275
Fixes rust-lang/rust#105937
Fixes rust-lang/rust#117696-2
Fixes rust-lang/rust#118590
Fixes rust-lang/rust#122823
Fixes rust-lang/rust#131342
Fixes rust-lang/rust#139659

## Analysis:
The causes of these issues are similar. They contain generic recursive functions that can be instantiated with different args infinitely at monomorphization stage. 
Ideally this should be caught by the [`check_recursion_limit`](https://github.com/rust-lang/rust/blob/c0bb3b98bb7aac24a37635e5d36d961e0b14f435/compiler/rustc_monomorphize/src/collector.rs#L468) function. The reality is that normalization can reach recursion limit earlier than monomorphization's check because they calculate depths in different ways. 
Since normalization is called everywhere, ICEs appear in different locations.

## Fix:
If we abort on overflow with `TypingMode::PostAnalysis` in the trait solver, it would also catch these errors. 
The main challenge is providing good diagnostics for them. So it's quite natural to put the check right before these normalization happening.
I first tried to check the whole MIR body's normalization and `references_error`. (As elaborate_drop handles normalization failure by [returning `ty::Error`](https://github.com/rust-lang/rust/blob/c0bb3b98bb7aac24a37635e5d36d961e0b14f435/compiler/rustc_mir_transform/src/elaborate_drop.rs#L514-L519).)
It turns out that checking all `Local`s seems sufficient.
These types are gonna be normalized anyway. So with cache, these checks shouldn't be expensive.

This fixes these ICEs for both the next and old solver, though I'm not sure the change I made to the old solver is proper. Its overflow handling looks convoluted thus I didn't try to fix it more "upstream".

### CODE REVIEW

File: tests/ui/codegen/normalization-overflow/recursion-issue-105937.rs [hunk 1]
```diff
@@ -1,3 +1,4 @@
+//@ build-fail
 //@ known-bug: #105937
```
Comment (bjorn3) [inline tests/ui/codegen/normalization-overflow/recursion-issue-105937.rs]:
```suggestion
```
right? Same elsewhere.

**Comment by adwinwhite** [comment]
I have to make the check a query in order to cache the its result for incremental build.
`collect_and_partition_mono_items` query is `eval always`. So `optimzed_mir` query in `instance_mir` and normalization query always got called. Even with query cache, loading MIR from disk is not that cheap. 
That's why the regressions happened.

File: compiler/rustc_monomorphize/src/collector.rs [hunk 2]
```diff
@@ -603,6 +620,21 @@ fn collect_items_rec<'tcx>(
     }
 }
 
+// Check whether we can normalize the MIR body. Make it a query since decoding MIR from disk cache
+// may be expensive.
+fn has_normalization_error_in_mono<'tcx>(tcx: TyCtxt<'tcx>, instance: Instance<'tcx>) -> bool {
+    let body = tcx.instance_mir(instance.def);
+    body.local_decls.iter().any(|local| {
```
Comment (saethlin) [inline compiler/rustc_monomorphize/src/collector.rs]: Why are you instantiating types seen in local_decls instead of the entire body? I'm worried that an error will sneak by this check because it's hidden somewhere else in the MIR body.

File: compiler/rustc_monomorphize/src/collector.rs [hunk 3]
```diff
@@ -473,6 +473,23 @@ fn collect_items_rec<'tcx>(
...
+                let def_id = instance.def_id();
+                let def_span = tcx.def_span(def_id);
+                let def_path_str = tcx.def_path_str(def_id);
+                tcx.dcx().emit_fatal(RecursionLimit {
+                    span: starting_item.span,
+                    instance,
+                    def_span,
+                    def_path_str,
+                });
+            }
```
Comment (cjgillot) [inline compiler/rustc_monomorphize/src/collector.rs]: Should we move error reporting to the query itself, and make the query return unit?

File: compiler/rustc_monomorphize/src/collector.rs (hunk 2 above)
Comment (adwinwhite) [reply compiler/rustc_monomorphize/src/collector.rs]: I did check the whole body at first. Then I realized that instantiation is not cached and worried that the computational cost is too high if the body is huge, so I tried to scale down the check. 

Ofc this is just speculation, I'm not sure about the real cost.

File: compiler/rustc_monomorphize/src/collector.rs (hunk 3 above)
Comment (adwinwhite) [reply compiler/rustc_monomorphize/src/collector.rs]: If we do so, the query would be dependent on `starting_item.span` which may pollute the cache unnecessarily?

File: compiler/rustc_monomorphize/src/collector.rs (hunk 2 above)
Comment (saethlin) [reply compiler/rustc_monomorphize/src/collector.rs]: This is done in a query, which should provide the requisite level of caching. Switch this to check the whole body and I can submit another perf run before merging.

**Comment by adwinwhite** [comment]
Ready for another perf run. :⁠-⁠)

**Comment by adwinwhite** [comment]
It turns out that I was too optimistic about the perf. 
Even if we can reuse query result in incremental build, we still need to check the color of query dependencies and persist additional nodes for each instance. And our new query consists of many normalization queries. These are not small cost.

**Comment by saethlin** [comment]
That's a perf result I'd be okay approving.

It's a bummer that the additional calls to `normalize_canonicalized_projection_ty` still regress projection-caching, but that's a benchmark of a pathological case, and we aren't regressing the thing it's testing for so it's acceptable.

**Comment by adwinwhite** [comment]
Without the starting span, users can only see the type of the failed instance and have to manually search and check each call to the function to determine whether the call introduces recursion.



One example from test: 
```rust
fn main() {
    recurse(std::iter::empty::<()>())
}
fn recurse(nums: impl Iterator) {
    if true { return }

    recurse(nums.skip(42).peekable())
    //~^ ERROR: reached the recursion limit while instantiating
}
```
Users can only see we fail to instantiate `peekable` but not where. It's not easy to determine the cause if there are many calls to `peekable` in real codebase.

**Comment by saethlin** [comment]
Could you make `items_of_instance` return a `Result` then emit the error with the useful span?

File: compiler/rustc_monomorphize/src/collector.rs [hunk 4]
```diff
@@ -603,6 +621,35 @@ fn collect_items_rec<'tcx>(
...
+                ty::EarlyBinder::bind(t),
+            ) {
+                Ok(_) => ControlFlow::Continue(()),
+                Err(_) => ControlFlow::Break(()),
+            }
+        }
+    }
+
+    let mut checker = NormalizationChecker { tcx, instance };
+    if body.visit_with(&mut checker).is_break() { Err(NormalizationErrorInMono) } else { Ok(()) }
```
Comment (RalfJung) [inline compiler/rustc_monomorphize/src/collector.rs:650]: The PR description says

> I first tried to check the whole MIR body's normalization and references_error. (As elaborate_drop handles normalization failure by [returning ty::Error](https://github.com/rust-lang/rust/blob/c0bb3b98bb7aac24a37635e5d36d961e0b14f435/compiler/rustc_mir_transform/src/elaborate_drop.rs#L514-L519).)
It turns out that checking all Locals seems sufficient.

but this seems to check all types the visitor meets, not just locals?

Even then I wonder if this is enough, e.g. the types of struct fields can require further normalization (that might then overflow) even after the struct type itself has been normalized.

Comment (adwinwhite) [reply compiler/rustc_monomorphize/src/collector.rs:650]: I was suggested by saethlin to check all types in MIR body for completeness. And it does catch one more crash test.

Looking through the [code of place projection](https://doc.rust-lang.org/nightly/nightly-rustc/src/rustc_middle/mir/statement.rs.html#199), it seems that their type computation doesn't involve any additional normalization. 
E.g. field projection has the field ty inside the variant thus it's checked by the visitor. 
But maybe there's something I missed?

Comment (RalfJung) [reply compiler/rustc_monomorphize/src/collector.rs:650]: > I was suggested by saethlin to check all types in MIR body for completeness. And it does catch one more crash test.

Okay, the PR description is outdated then. That's unfortunate as it is now permanently embedded in the git history. For future PRs please try to remember to update the PR description when you change the PR.

> Looking through the [code of place projection](https://doc.rust-lang.org/nightly/nightly-rustc/src/rustc_middle/mir/statement.rs.html#199), it seems that their type computation doesn't involve any additional normalization.

Codegen will invoke normalization on field types. That's required for types like
```rust
struct S(Type::Assoc);
```
even after normalizing `S`, the type of the field will come out as `Type::Assoc` which needs normalization before further processing.

And I presume that could overflow and cause the same issues this PR is intended to fix?

Comment (adwinwhite) [reply compiler/rustc_monomorphize/src/collector.rs:650]: Sorry for the mistake. Didn't know PR descriptions are recorded in git history. I'll keep it mind in the future.




> Codegen will invoke normalization on field types

I'm trying to come up with a test for this case. ~~But it seems that if the field is not used then no normalization is performed.~~
```rust
#![recursion_limit = "32"]

struct A;

trait HasAssoc {
    type Assoc;
}

impl HasAssoc for A {
    type Assoc = ();
}

struct S<T: HasAssoc>(T::Assoc);

impl<T: HasAssoc> HasAssoc for S<T> {
    type Assoc = T::Assoc;
}

// Wrap twice to make sure that projection depth grows faster than instance recursion depth.
fn wrap<T: HasAssoc>(a: T) -> S<S<T>> {
    panic!()
}

fn recurse<T: HasAssoc>(a: T) {
    if false {
        return;
    }

    recurse(wrap(a));
}

fn main() {
    recurse(A);
}
```

Comment (RalfJung) [reply compiler/rustc_monomorphize/src/collector.rs:650]: Even if the field doesn't get used, as long as the type gets used (`S` in your example), the field type has to be normalized as part of layout computation.

Comment (adwinwhite) [reply compiler/rustc_monomorphize/src/collector.rs:650]: Ahh! You're right. I need to use the `Local` to trigger layout computation. The test is updated.
Filed an [issue](https://github.com/rust-lang/rust/issues/147770) for this while searching for better solutions.
