### PR TITLE
rustc: move mir::SourceScopeLocalData to a field of SourceScopeData.

### LINKED ISSUE #51314: Broken MIR: scope[1] index exists, but source_scope_local_data.len() == 1
One test that produces such broken MIR is https://github.com/rust-lang/rust/blob/master/src/test/run-pass/mir-inlining/ice-issue-45885.rs

the MIR is

[log.txt](https://github.com/rust-lang/rust/files/2065378/log.txt)

### PR DESCRIPTION
**Pull request by eddyb**
By having one `ClearCrossCrate<SourceScopeLocalData>` for each scope, as opposed to a single `ClearCrossCrate` for all the `SourceScopeLocalData`s, we can represent the fact that some scopes have `SourceScopeLocalData` associated with them, and some don't.

This is useful when doing MIR inlining across crates, because the `ClearCrossCrate` will be `Clear` for the cross-crate MIR scopes and `Set` for the local ones.

Also see https://github.com/rust-lang/rust/pull/66203#issuecomment-555589574 for some context around this approach.

Fixes #51314.

### CODE REVIEW

File: src/librustc_mir/transform/inline.rs [hunk 1]
```diff
@@ -395,16 +395,25 @@ impl Inliner<'tcx> {
                 let mut local_map = IndexVec::with_capacity(callee_body.local_decls.len());
                 let mut scope_map = IndexVec::with_capacity(callee_body.source_scopes.len());
 
-                for mut scope in callee_body.source_scopes.iter().cloned() {
+                for (callee_idx, scope) in callee_body.source_scopes.iter_enumerated() {
```
Comment (oli-obk) [inline src/librustc_mir/transform/inline.rs]: cc @Centril @wesleywiser this PR may in fact be fixing the inliner ICE encountered during stage2 building
