### PR TITLE
Also walk bindings created by if-let guards

### LINKED ISSUE #119383: Unused variables inside if-let guards don't get detected
I expected the following code to fail to compile due to the unused variable `unused` but it actually compiled successfully:

```rs
#![feature(if_let_guard)]
#![deny(unused_variables)]

fn main() {
    match () {
        () if let Some(unused) = Some(()) => {}
        _ => {}
    }
}
```

### PR DESCRIPTION
**Pull request by est31**
This change makes the `unused_variables` lint pick up unused bindings created by if-let guards.

Fixes #119383

### CODE REVIEW

**Review by compiler-errors — APPROVED** [review]

**Comment by compiler-errors** [comment]
r? compiler-errors @bors r+ rollup

File: tests/ui/lint/unused/issue-119383.rs [hunk 1]
```diff
@@ -0,0 +1,9 @@
+#![feature(if_let_guard)]
```
Comment (Nilstrieb) [inline tests/ui/lint/unused/issue-119383.rs:1]: instead of giving this a meaningless issue number as a name, can we give it a descriptive name like "if-let-guard"?

**Review by Noratrieb — APPROVED** [review]
r=me after the test rename

**Comment by Nilstrieb** [comment]
Oh errs already reviewed it, didn't see that lol. A test rename would still be appreciated as a follow up :)
