### PR TITLE
Defer evaluating type system constants when they use infers or params

### LINKED ISSUE #133066: ICE: `did not expect inference variables here`
auto-reduced (treereduce-rust):
````rust
trait Owner {
    const C<const N: u32>: u32;
}

impl Owner for () {
    ;
}

fn take0<const N: u64>(_: impl Owner<C<N> = { N }>) {}

fn main() {
    take0::<f32, >(());
}

````

original:
````rust
trait Owner {
    const C<const N: u32>: u32;
}

impl Owner for () {
    const C<const N: u32>: u32 = N;
}

fn take0<const N: u64>(_: impl Owner<C<N> = { N }>) {}

fn main() {
    take0::<f32, {Dimension}>(());
}

````

Version information
````
rustc 1.84.0-nightly (251dc8ad8 2024-11-15)
binary: rustc
commit-hash: 251dc8ad84492c792a7600d8c5fef2ec868a36a7
commit-date: 2024-11-15
host: x86_64-unknown-linux-gnu
release: 1.84.0-nightly
LLVM version: 19.1.3

````

Possibly related line of code:
https://github.com/rust-lang/rust/blob/251dc8ad84492c792a7600d8c5fef2ec868a36a7/compiler/rustc_middle/src/mir/interpret/queries.rs#L99-L111

Command:
`/home/matthias/.rustup/toolchains/master/bin/rustc `

<details><summary><strong>Program output</strong></summary>
<p>

```
error: non-item in item list
 --> /tmp/icemaker_global_tempdir.LZacjKgHN0Cn/rustc_testrunner_tmpdir_reporting.fVFwgFbJn0St/mvce.rs:6:5
  |
5 | impl Owner for () {
  |                   - item list starts here
6 |     ;
  |     ^ non-item starts here
7 | }
  | - item list ends here

error[E0658]: associated const equality is incomplete
 --> /tmp/icemaker_global_tempdir.LZacjKgHN0Cn/rustc_testrunner_tmpdir_reporting.fVFwgFbJn0St/mvce.rs:9:38
  |
9 | fn take0<const N: u64>(_: impl Owner<C<N> = { N }>) {}
  |                                      ^^^^^^^^^^^^
  |
  = note: see issue #92827 <https://github.com/rust-lang/rust/issues/92827> for more information
  = help: add `#![feature(associated_const_equality)]` to the crate attributes to enable
  = note: this compiler was built on 2024-11-15; consider upgrading it if it is out of date

error[E0658]: generic const items are experimental
 --> /tmp/icemaker_global_tempdir.LZacjKgHN0Cn/rustc_testrunner_tmpdir_reporting.fVFwgFbJn0St/mvce.rs:2:12
  |
2 |     const C<const N: u32>: u32;
  |            ^^^^^^^^^^^^^^
  |
  = note: see issue #113521 <https://github.com/rust-lang/rust/issues/113521> for more information
  = help: add `#![feature(generic_const_items)]` to the crate attributes to enable
  = note: this compiler was built on 2024-11-15; consider upgrading it if it is out of date

error[E0046]: not all trait items implemented, missing: `C`
 --> /tmp/icemaker_global_tempdir.LZacjKgHN0Cn/rustc_testrunner_tmpdir_reporting.fVFwgFbJn0St/mvce.rs:5:1
  |
2 |     const C<const N: u32>: u32;
  |     -------------------------- `C` from trait
...
5 | impl Owner for () {
  | ^^^^^^^^^^^^^^^^^ missing `C` in implementation

error: the constant `N` is not of type `u32`
 --> /tmp/icemaker_global_tempdir.LZacjKgHN0Cn/rustc_testrunner_tmpdir_reporting.fVFwgFbJn0St/mvce.rs:9:38
  |
9 | fn take0<const N: u64>(_: impl Owner<C<N> = { N }>) {}
  |                                      ^^^^^^^^^^^^ expected `u32`, found `u64`
  |
note: required by a const generic parameter in `Owner::C`
 --> /tmp/icemaker_global_tempdir.LZacjKgHN0Cn/rustc_testrunner_tmpdir_reporting.fVFwgFbJn0St/mvce.rs:2:13
  |
2 |     const C<const N: u32>: u32;
  |             ^^^^^^^^^^^^ required by this const generic parameter in `Owner::C`

error[E0747]: type provided when a constant was expected
  --> /tmp/icemaker_global_tempdir.LZacjKgHN0Cn/rustc_testrunner_tmpdir_reporting.fVFwgFbJn0St/mvce.rs:12:13
   |
12 |     take0::<f32, >(());
   |             ^^^
   |
help: if this generic argument was intended as a const parameter, surround it with braces
   |
12 |     take0::<{ f32 }, >(());
   |             +     +

error: internal compiler error: compiler/rustc_middle/src/mir/interpret/queries.rs:105:13: did not expect inference variables here

thread 'rustc' panicked at compiler/rustc_middle/src/mir/interpret/queries.rs:105:13:
Box<dyn Any>
stack backtrace:
   0:     0x767693e5a3ba - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::h3e8890c320687803
   1:     0x76769460414a - core::fmt::write::h8e02e323e721d5d3
   2:     0x767695a2cc51 - std::io::Write::write_fmt::hfa5fc2d5ad51eab4
   3:     0x767693e5a212 - std::sys::backtrace::BacktraceLock::print::hef9ddff43c45c466
   4:     0x767693e5c716 - std::panicking::default_hook::{{closure}}::he4ae1ef11715c038
   5:     0x767693e5c560 - std::panicking::default_hook::h4571154760051e3a
   6:     0x767692ee4281 - std[575dabc3fc23637d]::panicking::update_hook::<alloc[488fcebc54bee2fb]::boxed::Box<rustc_driver_impl[530468506af41d6d]::install_ice_hook::{closure#0}>>::{closure#0}
   7:     0x767693e5ce28 - std::panicking::rust_panic_with_hook::h99e29fee3fbc2974
   8:     0x767692f1e5d1 - std[575dabc3fc23637d]::panicking::begin_panic::<rustc_errors[6fe58dffe56bd7e6]::ExplicitBug>::{closure#0}
   9:     0x767692f115a6 - std[575dabc3fc23637d]::sys::backtrace::__rust_end_short_backtrace::<std[575dabc3fc23637d]::panicking::begin_panic<rustc_errors[6fe58dffe56bd7e6]::ExplicitBug>::{closure#0}, !>
  10:     0x767692f0ce1d - std[575dabc3fc23637d]::panicking::begin_panic::<rustc_errors[6fe58dffe56bd7e6]::ExplicitBug>
  11:     0x767692f282e1 - <rustc_errors[6fe58dffe56bd7e6]::diagnostic::BugAbort as rustc_errors[6fe58dffe56bd7e6]::diagnostic::EmissionGuarantee>::emit_producing_guarantee
  12:     0x7676935a86d3 - rustc_middle[c94631e3827a547d]::util::bug::opt_span_bug_fmt::<rustc_span[9778d555244491c7]::span_encoding::Span>::{closure#0}
  13:     0x76769358ef1a - rustc_middle[c94631e3827a547d]::ty::context::tls::with_opt::<rustc_middle[c94631e3827a547d]::util::bug::opt_span_bug_fmt<rustc_span[9778d555244491c7]::span_encoding::Span>::{closure#0}, !>::{closure#0}
  14:     0x76769358edab - rustc_middle[c94631e3827a547d]::ty::context::tls::with_context_opt::<rustc_middle[c94631e3827a547d]::ty::context::tls::with_opt<rustc_middle[c94631e3827a547d]::util::bug::opt_span_bug_fmt<rustc_span[9778d555244491c7]::span_encoding::Span>::{closure#0}, !>::{closure#0}, !>
  15:     0x76769195b280 - rustc_middle[c94631e3827a547d]::util::bug::bug_fmt
  16:     0x7676960ab035 - <rustc_middle[c94631e3827a547d]::ty::context::TyCtxt>::const_eval_resolve_for_typeck.cold
  17:     0x76769503e581 - rustc_trait_selection[ae5754708a8b3a46]::traits::try_evaluate_const
  18:     0x767694f92383 - <rustc_trait_selection[ae5754708a8b3a46]::traits::normalize::AssocTypeNormalizer as rustc_type_ir[83e8cfe6e15c3590]::fold::TypeFolder<rustc_middle[c94631e3827a547d]::ty::context::TyCtxt>>::fold_const
  19:     0x7676928336de - <rustc_trait_selection[ae5754708a8b3a46]::traits::normalize::AssocTypeNormalizer>::fold::<rustc_middle[c94631e3827a547d]::ty::Term>
  20:     0x767693d1a9bd - rustc_trait_selection[ae5754708a8b3a46]::traits::normalize::normalize_with_depth_to::<rustc_middle[c94631e3827a547d]::ty::Term>
  21:     0x767693d0f792 - <rustc_trait_selection[ae5754708a8b3a46]::error_reporting::TypeErrCtxt>::report_fulfillment_error
  22:     0x767693cdc889 - <rustc_trait_selection[ae5754708a8b3a46]::error_reporting::TypeErrCtxt>::report_fulfillment_errors
  23:     0x767690d25711 - <rustc_hir_typeck[37bfb0076054673b]::fn_ctxt::FnCtxt>::confirm_builtin_call
  24:     0x76769536b6d8 - <rustc_hir_typeck[37bfb0076054673b]::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
  25:     0x767695365c35 - <rustc_hir_typeck[37bfb0076054673b]::fn_ctxt::FnCtxt>::check_expr_block
  26:     0x76769536bfba - <rustc_hir_typeck[37bfb0076054673b]::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
  27:     0x76769485789c - rustc_hir_typeck[37bfb0076054673b]::check::check_fn
  28:     0x76769484d2ec - rustc_hir_typeck[37bfb0076054673b]::typeck
  29:     0x76769484cc93 - rustc_query_impl[bf1c9f3baad9eabf]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[bf1c9f3baad9eabf]::query_impl::typeck::dynamic_query::{closure#2}::{closure#0}, rustc_middle[c94631e3827a547d]::query::erase::Erased<[u8; 8usize]>>
  30:     0x767694d12001 - rustc_query_system[d5846f7a9cb2c23f]::query::plumbing::try_execute_query::<rustc_query_impl[bf1c9f3baad9eabf]::DynamicConfig<rustc_query_system[d5846f7a9cb2c23f]::query::caches::VecCache<rustc_span[9778d555244491c7]::def_id::LocalDefId, rustc_middle[c94631e3827a547d]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[bf1c9f3baad9eabf]::plumbing::QueryCtxt, false>
  31:     0x767694d1048d - rustc_query_impl[bf1c9f3baad9eabf]::query_impl::typeck::get_query_non_incr::__rust_end_short_backtrace
  32:     0x767694d10107 - <rustc_middle[c94631e3827a547d]::hir::map::Map>::par_body_owners::<rustc_hir_analysis[19f2f9b7f430108f]::check_crate::{closure#4}>::{closure#0}
  33:     0x767694d0e0d9 - rustc_hir_analysis[19f2f9b7f430108f]::check_crate
  34:     0x767694b44fca - rustc_interface[c18496298df4cf52]::passes::run_required_analyses
  35:     0x76769542961e - rustc_interface[c18496298df4cf52]::passes::analysis
  36:     0x7676954295ef - rustc_query_impl[bf1c9f3baad9eabf]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[bf1c9f3baad9eabf]::query_impl::analysis::dynamic_query::{closure#2}::{closure#0}, rustc_middle[c94631e3827a547d]::query::erase::Erased<[u8; 1usize]>>
  37:     0x7676955dee6e - rustc_query_system[d5846f7a9cb2c23f]::query::plumbing::try_execute_query::<rustc_query_impl[bf1c9f3baad9eabf]::DynamicConfig<rustc_query_system[d5846f7a9cb2c23f]::query::caches::SingleCache<rustc_middle[c94631e3827a547d]::query::erase::Erased<[u8; 1usize]>>, false, false, false>, rustc_query_impl[bf1c9f3baad9eabf]::plumbing::QueryCtxt, false>
  38:     0x7676955deb4e - rustc_query_impl[bf1c9f3baad9eabf]::query_impl::analysis::get_query_non_incr::__rust_end_short_backtrace
  39:     0x7676954d963a - rustc_interface[c18496298df4cf52]::interface::run_compiler::<core[678332cb0ee15b78]::result::Result<(), rustc_span[9778d555244491c7]::ErrorGuaranteed>, rustc_driver_impl[530468506af41d6d]::run_compiler::{closure#0}>::{closure#1}
  40:     0x767695532e50 - std[575dabc3fc23637d]::sys::backtrace::__rust_begin_short_backtrace::<rustc_interface[c18496298df4cf52]::util::run_in_thread_with_globals<rustc_interface[c18496298df4cf52]::util::run_in_thread_pool_with_globals<rustc_interface[c18496298df4cf52]::interface::run_compiler<core[678332cb0ee15b78]::result::Result<(), rustc_span[9778d555244491c7]::ErrorGuaranteed>, rustc_driver_impl[530468506af41d6d]::run_compiler::{closure#0}>::{closure#1}, core[678332cb0ee15b78]::result::Result<(), rustc_span[9778d555244491c7]::ErrorGuaranteed>>::{closure#0}, core[678332cb0ee15b78]::result::Result<(), rustc_span[9778d555244491c7]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[678332cb0ee15b78]::result::Result<(), rustc_span[9778d555244491c7]::ErrorGuaranteed>>
  41:     0x76769553326b - <<std[575dabc3fc23637d]::thread::Builder>::spawn_unchecked_<rustc_interface[c18496298df4cf52]::util::run_in_thread_with_globals<rustc_interface[c18496298df4cf52]::util::run_in_thread_pool_with_globals<rustc_interface[c18496298df4cf52]::interface::run_compiler<core[678332cb0ee15b78]::result::Result<(), rustc_span[9778d555244491c7]::ErrorGuaranteed>, rustc_driver_impl[530468506af41d6d]::run_compiler::{closure#0}>::{closure#1}, core[678332cb0ee15b78]::result::Result<(), rustc_span[9778d555244491c7]::ErrorGuaranteed>>::{closure#0}, core[678332cb0ee15b78]::result::Result<(), rustc_span[9778d555244491c7]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[678332cb0ee15b78]::result::Result<(), rustc_span[9778d555244491c7]::ErrorGuaranteed>>::{closure#1} as core[678332cb0ee15b78]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  42:     0x767695533d39 - std::sys::pal::unix::thread::Thread::new::thread_start::h1176f996a4a1b888
  43:     0x767696d5f39d - <unknown>
  44:     0x767696de449c - <unknown>
  45:                0x0 - <unknown>

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: please make sure that you have updated to the latest nightly

note: rustc 1.84.0-nightly (251dc8ad8 2024-11-15) running on x86_64-unknown-linux-gnu

query stack during panic:
#0 [typeck] type-checking `main`
#1 [analysis] running analysis passes on this crate
end of query stack
error: aborting due to 7 previous errors

Some errors have detailed explanations: E0046, E0658, E0747.
For more information about an error, try `rustc --explain E0046`.

```

</p>
</details>

### LINKED ISSUE #133199: [ICE]:  Encountered anon const with inference variable args but no error reported
### Code

```Rust
I encountered an internal compiler error (ICE) while compiling a Rust project using rustc version 1.84.0-nightly (03ee48451 2024-11-18) on the aarch64-apple-darwin platform. The error message indicates that an anonymous constant with inference variable arguments was encountered, but no error was reported. This appears to be an issue within the compiler.

error: internal compiler error: Encountered anon const with inference variable args but no error reported
  |
  = note: delayed at compiler/rustc_trait_selection/src/traits/mod.rs:592:27 - disabled backtrace

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: please make sure that you have updated to the latest nightly

note: please attach the file at `/Users/vinay10949/Projects/decentralization/mishti/rustc-ice-2024-11-19T06_49_51-30490.txt` to your bug report

query stack during panic:
end of query stack
warning: `cli` (bin "cli") generated 2 warnings
error: could not compile `cli` (bin "cli"); 2 warnings emitted
```

### Affected release channels

- [ ] Previous Stable
- [ ] Current Stable
- [ ] Current Beta
- [x] Current Nightly

### Rust Version

```Shell
rustc --version --verbose
  rustc 1.84.0-nightly (03ee48451 2024-11-18)
  binary: rustc
  commit-hash: 03ee48451ff514defe859dd8e879ca1bd835789e
  host: aarch64-apple-darwin
  release: 1.84.0-nightly
  LLVM version: 17.0.0
```

### Current error output

```Shell
delayed bug: Encountered anon const with inference variable args but no error reported
disabled backtrace
delayed bug: Encountered anon const with inference variable args but no error reported
disabled backtrace
delayed bug: Encountered anon const with inference variable args but no error reported
disabled backtrace
delayed bug: Encountered anon const with inference variable args but no error reported
disabled backtrace
delayed bug: Encountered anon const with inference variable args but no error reported
disabled backtrace


rustc version: 1.84.0-nightly (03ee48451 2024-11-18)
platform: aarch64-apple-darwin⏎
```

### Backtrace

```Shell
error: internal compiler error: Encountered anon const with inference variable args but no error reported
  |
  = note: delayed at compiler/rustc_trait_selection/src/traits/mod.rs:592:27
             0: std::backtrace::Backtrace::create
             1: <rustc_errors::DiagCtxtInner>::emit_diagnostic
             2: <rustc_errors::DiagCtxtHandle>::emit_diagnostic
             3: <rustc_errors::diagnostic::Diag>::emit_producing_error_guaranteed
             4: <rustc_errors::DiagCtxtHandle>::delayed_bug::<&str>
             5: rustc_trait_selection::traits::try_evaluate_const
             6: rustc_trait_selection::traits::util::with_replaced_escaping_bound_vars::<rustc_middle::ty::consts::Const, rustc_middle::ty::consts::Const, <rustc_trait_selection::traits::normalize::AssocTypeNormalizer as rustc_type_ir::fold::TypeFolder<rustc_middle::ty::context::TyCtxt>>::fold_const::{closure#0}>
             7: <rustc_trait_selection::traits::normalize::AssocTypeNormalizer as rustc_type_ir::fold::TypeFolder<rustc_middle::ty::context::TyCtxt>>::fold_const
             8: <rustc_type_ir::predicate_kind::PredicateKind<rustc_middle::ty::context::TyCtxt> as rustc_type_ir::fold::TypeFoldable<rustc_middle::ty::context::TyCtxt>>::try_fold_with::<rustc_trait_selection::traits::normalize::AssocTypeNormalizer>
             9: <rustc_middle::ty::predicate::Predicate as rustc_type_ir::fold::TypeSuperFoldable<rustc_middle::ty::context::TyCtxt>>::try_super_fold_with::<rustc_trait_selection::traits::normalize::AssocTypeNormalizer>
            10: alloc::vec::in_place_collect::from_iter_in_place::<core::iter::adapters::GenericShunt<core::iter::adapters::map::Map<alloc::vec::into_iter::IntoIter<rustc_middle::ty::predicate::Clause>, <alloc::vec::Vec<rustc_middle::ty::predicate::Clause> as rustc_type_ir::fold::TypeFoldable<rustc_middle::ty::context::TyCtxt>>::try_fold_with<rustc_trait_selection::traits::normalize::AssocTypeNormalizer>::{closure#0}>, core::result::Result<core::convert::Infallible, !>>, rustc_middle::ty::predicate::Clause>
            11: <rustc_trait_selection::traits::normalize::AssocTypeNormalizer>::fold::<rustc_middle::ty::InstantiatedPredicates>
            12: rustc_trait_selection::traits::normalize::normalize_with_depth::<rustc_middle::ty::InstantiatedPredicates>
            13: <rustc_infer::infer::at::At as rustc_trait_selection::traits::normalize::NormalizeExt>::normalize::<rustc_middle::ty::InstantiatedPredicates>
            14: <rustc_hir_typeck::fn_ctxt::FnCtxt>::instantiate_bounds
            15: <rustc_hir_typeck::fn_ctxt::FnCtxt>::add_required_obligations_for_hir
            16: <rustc_hir_typeck::fn_ctxt::FnCtxt>::instantiate_value_path
            17: <rustc_hir_typeck::fn_ctxt::FnCtxt>::check_expr_path
            18: <rustc_hir_typeck::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
            19: <rustc_hir_typeck::fn_ctxt::FnCtxt>::check_expr_kind
            20: <rustc_hir_typeck::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
            21: <rustc_hir_typeck::fn_ctxt::FnCtxt>::check_expr_kind
            22: <rustc_hir_typeck::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
            23: <rustc_hir_typeck::fn_ctxt::FnCtxt>::check_decl
            24: <rustc_hir_typeck::fn_ctxt::FnCtxt>::check_expr_block
            25: <rustc_hir_typeck::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
            26: <rustc_hir_typeck::fn_ctxt::FnCtxt>::check_expr_kind
            27: <rustc_hir_typeck::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
            28: <rustc_hir_typeck::fn_ctxt::FnCtxt>::check_expr_block
            29: <rustc_hir_typeck::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
            30: <rustc_hir_typeck::fn_ctxt::FnCtxt>::check_expr_kind
            31: <rustc_hir_typeck::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
            32: <rustc_hir_typeck::fn_ctxt::FnCtxt>::check_expr_block
            33: <rustc_hir_typeck::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
            34: <rustc_hir_typeck::fn_ctxt::FnCtxt>::check_expr_kind
            35: <rustc_hir_typeck::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
            36: <rustc_hir_typeck::fn_ctxt::FnCtxt>::check_expr_block
            37: <rustc_hir_typeck::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
            38: <rustc_hir_typeck::fn_ctxt::FnCtxt>::check_expr_kind
            39: <rustc_hir_typeck::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
            40: <rustc_hir_typeck::fn_ctxt::FnCtxt>::check_expr_block
            41: <rustc_hir_typeck::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
            42: <rustc_hir_typeck::fn_ctxt::FnCtxt>::check_expr_kind
            43: <rustc_hir_typeck::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
            44: <rustc_hir_typeck::fn_ctxt::FnCtxt>::check_expr_block
            45: <rustc_hir_typeck::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
            46: <rustc_hir_typeck::fn_ctxt::FnCtxt>::check_return_or_body_tail
            47: rustc_hir_typeck::check::check_fn
            48: <rustc_hir_typeck::fn_ctxt::FnCtxt>::check_expr_kind
            49: <rustc_hir_typeck::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
            50: <rustc_hir_typeck::fn_ctxt::FnCtxt>::check_return_or_body_tail
            51: rustc_hir_typeck::check::check_fn
            52: rustc_hir_typeck::typeck
            53: rustc_query_impl::plumbing::__rust_begin_short_backtrace::<rustc_query_impl::query_impl::typeck::dynamic_query::{closure#2}::{closure#0}, rustc_middle::query::erase::Erased<[u8; 8]>>
            54: <rustc_query_impl::query_impl::typeck::dynamic_query::{closure#2} as core::ops::function::FnOnce<(rustc_middle::ty::context::TyCtxt, rustc_span::def_id::LocalDefId)>>::call_once
            55: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::DynamicConfig<rustc_query_system::query::caches::VecCache<rustc_span::def_id::LocalDefId, rustc_middle::query::erase::Erased<[u8; 8]>>, false, false, false>, rustc_query_impl::plumbing::QueryCtxt, true>
            56: rustc_query_impl::query_impl::typeck::get_query_incr::__rust_end_short_backtrace
            57: rustc_middle::query::plumbing::query_get_at::<rustc_query_system::query::caches::VecCache<rustc_span::def_id::LocalDefId, rustc_middle::query::erase::Erased<[u8; 8]>>>
            58: rustc_hir_analysis::collect::type_of::opaque::find_opaque_ty_constraints_for_rpit
            59: rustc_hir_analysis::collect::type_of::type_of_opaque
            60: rustc_query_impl::plumbing::__rust_begin_short_backtrace::<rustc_query_impl::query_impl::type_of_opaque::dynamic_query::{closure#2}::{closure#0}, rustc_middle::query::erase::Erased<[u8; 8]>>
            61: <rustc_query_impl::query_impl::type_of_opaque::dynamic_query::{closure#2} as core::ops::function::FnOnce<(rustc_middle::ty::context::TyCtxt, rustc_span::def_id::DefId)>>::call_once
            62: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::DynamicConfig<rustc_query_system::query::caches::DefIdCache<rustc_middle::query::erase::Erased<[u8; 8]>>, false, false, false>, rustc_query_impl::plumbing::QueryCtxt, true>
            63: rustc_query_impl::query_impl::type_of_opaque::get_query_incr::__rust_end_short_backtrace
            64: rustc_middle::query::plumbing::query_get_at::<rustc_query_system::query::caches::DefIdCache<rustc_middle::query::erase::Erased<[u8; 8]>>>
            65: rustc_hir_analysis::collect::type_of::type_of
            66: rustc_query_impl::plumbing::__rust_begin_short_backtrace::<rustc_query_impl::query_impl::type_of::dynamic_query::{closure#2}::{closure#0}, rustc_middle::query::erase::Erased<[u8; 8]>>
            67: <rustc_query_impl::query_impl::type_of::dynamic_query::{closure#2} as core::ops::function::FnOnce<(rustc_middle::ty::context::TyCtxt, rustc_span::def_id::DefId)>>::call_once
            68: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::DynamicConfig<rustc_query_system::query::caches::DefIdCache<rustc_middle::query::erase::Erased<[u8; 8]>>, false, false, false>, rustc_query_impl::plumbing::QueryCtxt, true>
            69: rustc_query_impl::query_impl::type_of::get_query_incr::__rust_end_short_backtrace
            70: rustc_middle::query::plumbing::query_get_at::<rustc_query_system::query::caches::DefIdCache<rustc_middle::query::erase::Erased<[u8; 8]>>>
            71: rustc_hir_analysis::check::check::check_item_type
            72: rustc_hir_analysis::check::wfcheck::check_well_formed
            73: rustc_query_impl::plumbing::__rust_begin_short_backtrace::<rustc_query_impl::query_impl::check_well_formed::dynamic_query::{closure#2}::{closure#0}, rustc_middle::query::erase::Erased<[u8; 1]>>
            74: <rustc_query_impl::query_impl::check_well_formed::dynamic_query::{closure#2} as core::ops::function::FnOnce<(rustc_middle::ty::context::TyCtxt, rustc_span::def_id::LocalDefId)>>::call_once
            75: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::DynamicConfig<rustc_query_system::query::caches::VecCache<rustc_span::def_id::LocalDefId, rustc_middle::query::erase::Erased<[u8; 1]>>, false, false, false>, rustc_query_impl::plumbing::QueryCtxt, true>
            76: rustc_query_impl::query_impl::check_well_formed::get_query_incr::__rust_end_short_backtrace
            77: rustc_middle::query::plumbing::query_ensure_error_guaranteed::<rustc_query_system::query::caches::VecCache<rustc_span::def_id::LocalDefId, rustc_middle::query::erase::Erased<[u8; 1]>>, ()>
            78: <rustc_middle::hir::ModuleItems>::par_opaques::<rustc_hir_analysis::check::wfcheck::check_mod_type_wf::{closure#4}>
            79: rustc_hir_analysis::check::wfcheck::check_mod_type_wf
            80: rustc_query_impl::plumbing::__rust_begin_short_backtrace::<rustc_query_impl::query_impl::check_mod_type_wf::dynamic_query::{closure#2}::{closure#0}, rustc_middle::query::erase::Erased<[u8; 1]>>
            81: <rustc_query_impl::query_impl::check_mod_type_wf::dynamic_query::{closure#2} as core::ops::function::FnOnce<(rustc_middle::ty::context::TyCtxt, rustc_span::def_id::LocalModDefId)>>::call_once
            82: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::DynamicConfig<rustc_query_system::query::caches::DefaultCache<rustc_span::def_id::LocalModDefId, rustc_middle::query::erase::Erased<[u8; 1]>>, false, false, false>, rustc_query_impl::plumbing::QueryCtxt, true>
            83: rustc_query_impl::query_impl::check_mod_type_wf::get_query_incr::__rust_end_short_backtrace
            84: <rustc_data_structures::sync::parallel::ParallelGuard>::run::<(), rustc_data_structures::sync::parallel::par_for_each_in<&rustc_hir::hir_id::OwnerId, &[rustc_hir::hir_id::OwnerId], <rustc_middle::hir::map::Map>::par_for_each_module<rustc_hir_analysis::check_crate::{closure#0}::{closure#0}>::{closure#0}>::{closure#0}::{closure#1}::{closure#0}>
            85: rustc_hir_analysis::check_crate
            86: rustc_interface::passes::analysis
            87: rustc_query_impl::plumbing::__rust_begin_short_backtrace::<rustc_query_impl::query_impl::analysis::dynamic_query::{closure#2}::{closure#0}, rustc_middle::query::erase::Erased<[u8; 1]>>
            88: <rustc_query_impl::query_impl::analysis::dynamic_query::{closure#2} as core::ops::function::FnOnce<(rustc_middle::ty::context::TyCtxt, ())>>::call_once
            89: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::DynamicConfig<rustc_query_system::query::caches::SingleCache<rustc_middle::query::erase::Erased<[u8; 1]>>, false, false, false>, rustc_query_impl::plumbing::QueryCtxt, true>
            90: rustc_query_impl::query_impl::analysis::get_query_incr::__rust_end_short_backtrace
            91: <rustc_middle::ty::context::GlobalCtxt>::enter::<rustc_driver_impl::run_compiler::{closure#0}::{closure#1}::{closure#5}, core::result::Result<(), rustc_span::ErrorGuaranteed>>
            92: <rustc_interface::interface::Compiler>::enter::<rustc_driver_impl::run_compiler::{closure#0}::{closure#1}, core::result::Result<core::option::Option<rustc_interface::queries::Linker>, rustc_span::ErrorGuaranteed>>
            93: <scoped_tls::ScopedKey<rustc_span::SessionGlobals>>::set::<rustc_interface::util::run_in_thread_with_globals<rustc_interface::util::run_in_thread_pool_with_globals<rustc_interface::interface::run_compiler<core::result::Result<(), rustc_span::ErrorGuaranteed>, rustc_driver_impl::run_compiler::{closure#0}>::{closure#1}, core::result::Result<(), rustc_span::ErrorGuaranteed>>::{closure#0}, core::result::Result<(), rustc_span::ErrorGuaranteed>>::{closure#0}::{closure#0}::{closure#0}, core::result::Result<(), rustc_span::ErrorGuaranteed>>
            94: rustc_span::create_session_globals_then::<core::result::Result<(), rustc_span::ErrorGuaranteed>, rustc_interface::util::run_in_thread_with_globals<rustc_interface::util::run_in_thread_pool_with_globals<rustc_interface::interface::run_compiler<core::result::Result<(), rustc_span::ErrorGuaranteed>, rustc_driver_impl::run_compiler::{closure#0}>::{closure#1}, core::result::Result<(), rustc_span::ErrorGuaranteed>>::{closure#0}, core::result::Result<(), rustc_span::ErrorGuaranteed>>::{closure#0}::{closure#0}::{closure#0}>
            95: std::sys::backtrace::__rust_begin_short_backtrace::<rustc_interface::util::run_in_thread_with_globals<rustc_interface::util::run_in_thread_pool_with_globals<rustc_interface::interface::run_compiler<core::result::Result<(), rustc_span::ErrorGuaranteed>, rustc_driver_impl::run_compiler::{closure#0}>::{closure#1}, core::result::Result<(), rustc_span::ErrorGuaranteed>>::{closure#0}, core::result::Result<(), rustc_span::ErrorGuaranteed>>::{closure#0}::{closure#0}, core::result::Result<(), rustc_span::ErrorGuaranteed>>
            96: <<std::thread::Builder>::spawn_unchecked_<rustc_interface::util::run_in_thread_with_globals<rustc_interface::util::run_in_thread_pool_with_globals<rustc_interface::interface::run_compiler<core::result::Result<(), rustc_span::ErrorGuaranteed>, rustc_driver_impl::run_compiler::{closure#0}>::{closure#1}, core::result::Result<(), rustc_span::ErrorGuaranteed>>::{closure#0}, core::result::Result<(), rustc_span::ErrorGuaranteed>>::{closure#0}::{closure#0}, core::result::Result<(), rustc_span::ErrorGuaranteed>>::{closure#1} as core::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
            97: std::sys::pal::unix::thread::Thread::new::thread_start
            98: __pthread_joiner_wake
          

error: internal compiler error: Encountered anon const with inference variable args but no error reported
  |
  = note: delayed at compiler/rustc_trait_selection/src/traits/mod.rs:592:27
             0: std::backtrace::Backtrace::create
             1: <rustc_errors::DiagCtxtInner>::emit_diagnostic
             2: <rustc_errors::DiagCtxtHandle>::emit_diagnostic
             3: <rustc_errors::diagnostic::Diag>::emit_producing_error_guaranteed
             4: <rustc_errors::DiagCtxtHandle>::delayed_bug::<&str>
             5: rustc_trait_selection::traits::try_evaluate_const
             6: rustc_trait_selection::traits::util::with_replaced_escaping_bound_vars::<rustc_middle::ty::consts::Const, rustc_middle::ty::consts::Const, <rustc_trait_selection::traits::normalize::AssocTypeNormalizer as rustc_type_ir::fold::TypeFolder<rustc_middle::ty::context::TyCtxt>>::fold_const::{closure#0}>
             7: <rustc_trait_selection::traits::normalize::AssocTypeNormalizer as rustc_type_ir::fold::TypeFolder<rustc_middle::ty::context::TyCtxt>>::fold_const
             8: <rustc_type_ir::predicate_kind::PredicateKind<rustc_middle::ty::context::TyCtxt> as rustc_type_ir::fold::TypeFoldable<rustc_middle::ty::context::TyCtxt>>::try_fold_with::<rustc_trait_selection::traits::normalize::AssocTypeNormalizer>
             9: <rustc_middle::ty::predicate::Predicate as rustc_type_ir::fold::TypeSuperFoldable<rustc_middle::ty::context::TyCtxt>>::try_super_fold_with::<rustc_trait_selection::traits::normalize::AssocTypeNormalizer>
            10: rustc_trait_selection::traits::normalize::normalize_with_depth_to::<rustc_middle::ty::predicate::Predicate>
            11: <rustc_trait_selection::traits::fulfill::FulfillProcessor as rustc_data_structures::obligation_forest::ObligationProcessor>::process_obligation
            12: <rustc_data_structures::obligation_forest::ObligationForest<rustc_trait_selection::traits::fulfill::PendingPredicateObligation>>::process_obligations::<rustc_trait_selection::traits::fulfill::FulfillProcessor>
            13: <rustc_trait_selection::traits::fulfill::FulfillmentContext<rustc_trait_selection::traits::FulfillmentError> as rustc_infer::traits::engine::TraitEngine<rustc_trait_selection::traits::FulfillmentError>>::select_where_possible
            14: <rustc_hir_typeck::fn_ctxt::FnCtxt>::resolve_vars_with_obligations
            15: <rustc_hir_typeck::fn_ctxt::FnCtxt>::try_structurally_resolve_type
            16: <rustc_hir_typeck::fn_ctxt::FnCtxt>::structurally_resolve_type
            17: <rustc_hir_typeck::fn_ctxt::FnCtxt>::check_expr_kind
            18: <rustc_hir_typeck::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
            19: <rustc_hir_typeck::fn_ctxt::FnCtxt>::check_expr_kind
            20: <rustc_hir_typeck::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
            21: <rustc_hir_typeck::fn_ctxt::FnCtxt>::check_decl
            22: <rustc_hir_typeck::fn_ctxt::FnCtxt>::check_expr_block
            23: <rustc_hir_typeck::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
            24: <rustc_hir_typeck::fn_ctxt::FnCtxt>::check_expr_kind
            25: <rustc_hir_typeck::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
            26: <rustc_hir_typeck::fn_ctxt::FnCtxt>::check_expr_block
            27: <rustc_hir_typeck::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
            28: <rustc_hir_typeck::fn_ctxt::FnCtxt>::check_expr_kind
            29: <rustc_hir_typeck::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
            30: <rustc_hir_typeck::fn_ctxt::FnCtxt>::check_expr_block
            31: <rustc_hir_typeck::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
            32: <rustc_hir_typeck::fn_ctxt::FnCtxt>::check_expr_kind
            33: <rustc_hir_typeck::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
            34: <rustc_hir_typeck::fn_ctxt::FnCtxt>::check_expr_block
            35: <rustc_hir_typeck::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
            36: <rustc_hir_typeck::fn_ctxt::FnCtxt>::check_expr_kind
            37: <rustc_hir_typeck::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
            38: <rustc_hir_typeck::fn_ctxt::FnCtxt>::check_expr_block
            39: <rustc_hir_typeck::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
            40: <rustc_hir_typeck::fn_ctxt::FnCtxt>::check_expr_kind
            41: <rustc_hir_typeck::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
            42: <rustc_hir_typeck::fn_ctxt::FnCtxt>::check_expr_block
            43: <rustc_hir_typeck::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
            44: <rustc_hir_typeck::fn_ctxt::FnCtxt>::check_return_or_body_tail
            45: rustc_hir_typeck::check::check_fn
            46: <rustc_hir_typeck::fn_ctxt::FnCtxt>::check_expr_kind
            47: <rustc_hir_typeck::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
            48: <rustc_hir_typeck::fn_ctxt::FnCtxt>::check_return_or_body_tail
            49: rustc_hir_typeck::check::check_fn
            50: rustc_hir_typeck::typeck
            51: rustc_query_impl::plumbing::__rust_begin_short_backtrace::<rustc_query_impl::query_impl::typeck::dynamic_query::{closure#2}::{closure#0}, rustc_middle::query::erase::Erased<[u8; 8]>>
            52: <rustc_query_impl::query_impl::typeck::dynamic_query::{closure#2} as core::ops::function::FnOnce<(rustc_middle::ty::context::TyCtxt, rustc_span::def_id::LocalDefId)>>::call_once
            53: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::DynamicConfig<rustc_query_system::query::caches::VecCache<rustc_span::def_id::LocalDefId, rustc_middle::query::erase::Erased<[u8; 8]>>, false, false, false>, rustc_query_impl::plumbing::QueryCtxt, true>
            54: rustc_query_impl::query_impl::typeck::get_query_incr::__rust_end_short_backtrace
            55: rustc_middle::query::plumbing::query_get_at::<rustc_query_system::query::caches::VecCache<rustc_span::def_id::LocalDefId, rustc_middle::query::erase::Erased<[u8; 8]>>>
            56: rustc_hir_analysis::collect::type_of::opaque::find_opaque_ty_constraints_for_rpit
            57: rustc_hir_analysis::collect::type_of::type_of_opaque
            58: rustc_query_impl::plumbing::__rust_begin_short_backtrace::<rustc_query_impl::query_impl::type_of_opaque::dynamic_query::{closure#2}::{closure#0}, rustc_middle::query::erase::Erased<[u8; 8]>>
            59: <rustc_query_impl::query_impl::type_of_opaque::dynamic_query::{closure#2} as core::ops::function::FnOnce<(rustc_middle::ty::context::TyCtxt, rustc_span::def_id::DefId)>>::call_once
            60: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::DynamicConfig<rustc_query_system::query::caches::DefIdCache<rustc_middle::query::erase::Erased<[u8; 8]>>, false, false, false>, rustc_query_impl::plumbing::QueryCtxt, true>
            61: rustc_query_impl::query_impl::type_of_opaque::get_query_incr::__rust_end_short_backtrace
            62: rustc_middle::query::plumbing::query_get_at::<rustc_query_system::query::caches::DefIdCache<rustc_middle::query::erase::Erased<[u8; 8]>>>
            63: rustc_hir_analysis::collect::type_of::type_of
            64: rustc_query_impl::plumbing::__rust_begin_short_backtrace::<rustc_query_impl::query_impl::type_of::dynamic_query::{closure#2}::{closure#0}, rustc_middle::query::erase::Erased<[u8; 8]>>
            65: <rustc_query_impl::query_impl::type_of::dynamic_query::{closure#2} as core::ops::function::FnOnce<(rustc_middle::ty::context::TyCtxt, rustc_span::def_id::DefId)>>::call_once
            66: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::DynamicConfig<rustc_query_system::query::caches::DefIdCache<rustc_middle::query::erase::Erased<[u8; 8]>>, false, false, false>, rustc_query_impl::plumbing::QueryCtxt, true>
            67: rustc_query_impl::query_impl::type_of::get_query_incr::__rust_end_short_backtrace
            68: rustc_middle::query::plumbing::query_get_at::<rustc_query_system::query::caches::DefIdCache<rustc_middle::query::erase::Erased<[u8; 8]>>>
            69: rustc_hir_analysis::check::check::check_item_type
            70: rustc_hir_analysis::check::wfcheck::check_well_formed
            71: rustc_query_impl::plumbing::__rust_begin_short_backtrace::<rustc_query_impl::query_impl::check_well_formed::dynamic_query::{closure#2}::{closure#0}, rustc_middle::query::erase::Erased<[u8; 1]>>
            72: <rustc_query_impl::query_impl::check_well_formed::dynamic_query::{closure#2} as core::ops::function::FnOnce<(rustc_middle::ty::context::TyCtxt, rustc_span::def_id::LocalDefId)>>::call_once
            73: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::DynamicConfig<rustc_query_system::query::caches::VecCache<rustc_span::def_id::LocalDefId, rustc_middle::query::erase::Erased<[u8; 1]>>, false, false, false>, rustc_query_impl::plumbing::QueryCtxt, true>
            74: rustc_query_impl::query_impl::check_well_formed::get_query_incr::__rust_end_short_backtrace
            75: rustc_middle::query::plumbing::query_ensure_error_guaranteed::<rustc_query_system::query::caches::VecCache<rustc_span::def_id::LocalDefId, rustc_middle::query::erase::Erased<[u8; 1]>>, ()>
            76: <rustc_middle::hir::ModuleItems>::par_opaques::<rustc_hir_analysis::check::wfcheck::check_mod_type_wf::{closure#4}>
            77: rustc_hir_analysis::check::wfcheck::check_mod_type_wf
            78: rustc_query_impl::plumbing::__rust_begin_short_backtrace::<rustc_query_impl::query_impl::check_mod_type_wf::dynamic_query::{closure#2}::{closure#0}, rustc_middle::query::erase::Erased<[u8; 1]>>
            79: <rustc_query_impl::query_impl::check_mod_type_wf::dynamic_query::{closure#2} as core::ops::function::FnOnce<(rustc_middle::ty::context::TyCtxt, rustc_span::def_id::LocalModDefId)>>::call_once
            80: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::DynamicConfig<rustc_query_system::query::caches::DefaultCache<rustc_span::def_id::LocalModDefId, rustc_middle::query::erase::Erased<[u8; 1]>>, false, false, false>, rustc_query_impl::plumbing::QueryCtxt, true>
            81: rustc_query_impl::query_impl::check_mod_type_wf::get_query_incr::__rust_end_short_backtrace
            82: <rustc_data_structures::sync::parallel::ParallelGuard>::run::<(), rustc_data_structures::sync::parallel::par_for_each_in<&rustc_hir::hir_id::OwnerId, &[rustc_hir::hir_id::OwnerId], <rustc_middle::hir::map::Map>::par_for_each_module<rustc_hir_analysis::check_crate::{closure#0}::{closure#0}>::{closure#0}>::{closure#0}::{closure#1}::{closure#0}>
            83: rustc_hir_analysis::check_crate
            84: rustc_interface::passes::analysis
            85: rustc_query_impl::plumbing::__rust_begin_short_backtrace::<rustc_query_impl::query_impl::analysis::dynamic_query::{closure#2}::{closure#0}, rustc_middle::query::erase::Erased<[u8; 1]>>
            86: <rustc_query_impl::query_impl::analysis::dynamic_query::{closure#2} as core::ops::function::FnOnce<(rustc_middle::ty::context::TyCtxt, ())>>::call_once
            87: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::DynamicConfig<rustc_query_system::query::caches::SingleCache<rustc_middle::query::erase::Erased<[u8; 1]>>, false, false, false>, rustc_query_impl::plumbing::QueryCtxt, true>
            88: rustc_query_impl::query_impl::analysis::get_query_incr::__rust_end_short_backtrace
            89: <rustc_middle::ty::context::GlobalCtxt>::enter::<rustc_driver_impl::run_compiler::{closure#0}::{closure#1}::{closure#5}, core::result::Result<(), rustc_span::ErrorGuaranteed>>
            90: <rustc_interface::interface::Compiler>::enter::<rustc_driver_impl::run_compiler::{closure#0}::{closure#1}, core::result::Result<core::option::Option<rustc_interface::queries::Linker>, rustc_span::ErrorGuaranteed>>
            91: <scoped_tls::ScopedKey<rustc_span::SessionGlobals>>::set::<rustc_interface::util::run_in_thread_with_globals<rustc_interface::util::run_in_thread_pool_with_globals<rustc_interface::interface::run_compiler<core::result::Result<(), rustc_span::ErrorGuaranteed>, rustc_driver_impl::run_compiler::{closure#0}>::{closure#1}, core::result::Result<(), rustc_span::ErrorGuaranteed>>::{closure#0}, core::result::Result<(), rustc_span::ErrorGuaranteed>>::{closure#0}::{closure#0}::{closure#0}, core::result::Result<(), rustc_span::ErrorGuaranteed>>
            92: rustc_span::create_session_globals_then::<core::result::Result<(), rustc_span::ErrorGuaranteed>, rustc_interface::util::run_in_thread_with_globals<rustc_interface::util::run_in_thread_pool_with_globals<rustc_interface::interface::run_compiler<core::result::Result<(), rustc_span::ErrorGuaranteed>, rustc_driver_impl::run_compiler::{closure#0}>::{closure#1}, core::result::Result<(), rustc_span::ErrorGuaranteed>>::{closure#0}, core::result::Result<(), rustc_span::ErrorGuaranteed>>::{closure#0}::{closure#0}::{closure#0}>
            93: std::sys::backtrace::__rust_begin_short_backtrace::<rustc_interface::util::run_in_thread_with_globals<rustc_interface::util::run_in_thread_pool_with_globals<rustc_interface::interface::run_compiler<core::result::Result<(), rustc_span::ErrorGuaranteed>, rustc_driver_impl::run_compiler::{closure#0}>::{closure#1}, core::result::Result<(), rustc_span::ErrorGuaranteed>>::{closure#0}, core::result::Result<(), rustc_span::ErrorGuaranteed>>::{closure#0}::{closure#0}, core::result::Result<(), rustc_span::ErrorGuaranteed>>
            94: <<std::thread::Builder>::spawn_unchecked_<rustc_interface::util::run_in_thread_with_globals<rustc_interface::util::run_in_thread_pool_with_globals<rustc_interface::interface::run_compiler<core::result::Result<(), rustc_span::ErrorGuaranteed>, rustc_driver_impl::run_compiler::{closure#0}>::{closure#1}, core::result::Result<(), rustc_span::ErrorGuaranteed>>::{closure#0}, core::result::Result<(), rustc_span::ErrorGuaranteed>>::{closure#0}::{closure#0}, core::result::Result<(), rustc_span::ErrorGuaranteed>>::{closure#1} as core::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
            95: std::sys::pal::unix::thread::Thread::new::thread_start
            96: __pthread_joiner_wake
          

error: internal compiler error: Encountered anon const with inference variable args but no error reported
  |
  = note: delayed at compiler/rustc_trait_selection/src/traits/mod.rs:592:27
             0: std::backtrace::Backtrace::create
             1: <rustc_errors::DiagCtxtInner>::emit_diagnostic
             2: <rustc_errors::DiagCtxtHandle>::emit_diagnostic
             3: <rustc_errors::diagnostic::Diag>::emit_producing_error_guaranteed
             4: <rustc_errors::DiagCtxtHandle>::delayed_bug::<&str>
             5: rustc_trait_selection::traits::try_evaluate_const
             6: rustc_trait_selection::traits::const_evaluatable::is_const_evaluatable
             7: <rustc_trait_selection::traits::fulfill::FulfillProcessor as rustc_data_structures::obligation_forest::ObligationProcessor>::process_obligation
             8: <rustc_data_structures::obligation_forest::ObligationForest<rustc_trait_selection::traits::fulfill::PendingPredicateObligation>>::process_obligations::<rustc_trait_selection::traits::fulfill::FulfillProcessor>
             9: <rustc_trait_selection::traits::fulfill::FulfillmentContext<rustc_trait_selection::traits::FulfillmentError> as rustc_infer::traits::engine::TraitEngine<rustc_trait_selection::traits::FulfillmentError>>::select_where_possible
            10: <rustc_hir_typeck::fn_ctxt::FnCtxt>::resolve_vars_with_obligations
            11: <rustc_hir_typeck::fn_ctxt::FnCtxt>::try_structurally_resolve_type
            12: <rustc_hir_typeck::fn_ctxt::FnCtxt>::structurally_resolve_type
            13: <rustc_hir_typeck::fn_ctxt::FnCtxt>::check_expr_kind
            14: <rustc_hir_typeck::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
            15: <rustc_hir_typeck::fn_ctxt::FnCtxt>::check_expr_kind
            16: <rustc_hir_typeck::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
            17: <rustc_hir_typeck::fn_ctxt::FnCtxt>::check_decl
            18: <rustc_hir_typeck::fn_ctxt::FnCtxt>::check_expr_block
            19: <rustc_hir_typeck::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
            20: <rustc_hir_typeck::fn_ctxt::FnCtxt>::check_expr_kind
            21: <rustc_hir_typeck::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
            22: <rustc_hir_typeck::fn_ctxt::FnCtxt>::check_expr_block
            23: <rustc_hir_typeck::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
            24: <rustc_hir_typeck::fn_ctxt::FnCtxt>::check_expr_kind
            25: <rustc_hir_typeck::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
            26: <rustc_hir_typeck::fn_ctxt::FnCtxt>::check_expr_block
            27: <rustc_hir_typeck::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
            28: <rustc_hir_typeck::fn_ctxt::FnCtxt>::check_expr_kind
            29: <rustc_hir_typeck::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
            30: <rustc_hir_typeck::fn_ctxt::FnCtxt>::check_expr_block
            31: <rustc_hir_typeck::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
            32: <rustc_hir_typeck::fn_ctxt::FnCtxt>::check_expr_kind
            33: <rustc_hir_typeck::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
            34: <rustc_hir_typeck::fn_ctxt::FnCtxt>::check_expr_block
            35: <rustc_hir_typeck::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
            36: <rustc_hir_typeck::fn_ctxt::FnCtxt>::check_expr_kind
            37: <rustc_hir_typeck::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
            38: <rustc_hir_typeck::fn_ctxt::FnCtxt>::check_expr_block
            39: <rustc_hir_typeck::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
            40: <rustc_hir_typeck::fn_ctxt::FnCtxt>::check_return_or_body_tail
            41: rustc_hir_typeck::check::check_fn
            42: <rustc_hir_typeck::fn_ctxt::FnCtxt>::check_expr_kind
            43: <rustc_hir_typeck::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
            44: <rustc_hir_typeck::fn_ctxt::FnCtxt>::check_return_or_body_tail
            45: rustc_hir_typeck::check::check_fn
            46: rustc_hir_typeck::typeck
            47: rustc_query_impl::plumbing::__rust_begin_short_backtrace::<rustc_query_impl::query_impl::typeck::dynamic_query::{closure#2}::{closure#0}, rustc_middle::query::erase::Erased<[u8; 8]>>
            48: <rustc_query_impl::query_impl::typeck::dynamic_query::{closure#2} as core::ops::function::FnOnce<(rustc_middle::ty::context::TyCtxt, rustc_span::def_id::LocalDefId)>>::call_once
            49: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::DynamicConfig<rustc_query_system::query::caches::VecCache<rustc_span::def_id::LocalDefId, rustc_middle::query::erase::Erased<[u8; 8]>>, false, false, false>, rustc_query_impl::plumbing::QueryCtxt, true>
            50: rustc_query_impl::query_impl::typeck::get_query_incr::__rust_end_short_backtrace
            51: rustc_middle::query::plumbing::query_get_at::<rustc_query_system::query::caches::VecCache<rustc_span::def_id::LocalDefId, rustc_middle::query::erase::Erased<[u8; 8]>>>
            52: rustc_hir_analysis::collect::type_of::opaque::find_opaque_ty_constraints_for_rpit
            53: rustc_hir_analysis::collect::type_of::type_of_opaque
            54: rustc_query_impl::plumbing::__rust_begin_short_backtrace::<rustc_query_impl::query_impl::type_of_opaque::dynamic_query::{closure#2}::{closure#0}, rustc_middle::query::erase::Erased<[u8; 8]>>
            55: <rustc_query_impl::query_impl::type_of_opaque::dynamic_query::{closure#2} as core::ops::function::FnOnce<(rustc_middle::ty::context::TyCtxt, rustc_span::def_id::DefId)>>::call_once
            56: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::DynamicConfig<rustc_query_system::query::caches::DefIdCache<rustc_middle::query::erase::Erased<[u8; 8]>>, false, false, false>, rustc_query_impl::plumbing::QueryCtxt, true>
            57: rustc_query_impl::query_impl::type_of_opaque::get_query_incr::__rust_end_short_backtrace
            58: rustc_middle::query::plumbing::query_get_at::<rustc_query_system::query::caches::DefIdCache<rustc_middle::query::erase::Erased<[u8; 8]>>>
            59: rustc_hir_analysis::collect::type_of::type_of
            60: rustc_query_impl::plumbing::__rust_begin_short_backtrace::<rustc_query_impl::query_impl::type_of::dynamic_query::{closure#2}::{closure#0}, rustc_middle::query::erase::Erased<[u8; 8]>>
            61: <rustc_query_impl::query_impl::type_of::dynamic_query::{closure#2} as core::ops::function::FnOnce<(rustc_middle::ty::context::TyCtxt, rustc_span::def_id::DefId)>>::call_once
            62: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::DynamicConfig<rustc_query_system::query::caches::DefIdCache<rustc_middle::query::erase::Erased<[u8; 8]>>, false, false, false>, rustc_query_impl::plumbing::QueryCtxt, true>
            63: rustc_query_impl::query_impl::type_of::get_query_incr::__rust_end_short_backtrace
            64: rustc_middle::query::plumbing::query_get_at::<rustc_query_system::query::caches::DefIdCache<rustc_middle::query::erase::Erased<[u8; 8]>>>
            65: rustc_hir_analysis::check::check::check_item_type
            66: rustc_hir_analysis::check::wfcheck::check_well_formed
            67: rustc_query_impl::plumbing::__rust_begin_short_backtrace::<rustc_query_impl::query_impl::check_well_formed::dynamic_query::{closure#2}::{closure#0}, rustc_middle::query::erase::Erased<[u8; 1]>>
            68: <rustc_query_impl::query_impl::check_well_formed::dynamic_query::{closure#2} as core::ops::function::FnOnce<(rustc_middle::ty::context::TyCtxt, rustc_span::def_id::LocalDefId)>>::call_once
            69: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::DynamicConfig<rustc_query_system::query::caches::VecCache<rustc_span::def_id::LocalDefId, rustc_middle::query::erase::Erased<[u8; 1]>>, false, false, false>, rustc_query_impl::plumbing::QueryCtxt, true>
            70: rustc_query_impl::query_impl::check_well_formed::get_query_incr::__rust_end_short_backtrace
            71: rustc_middle::query::plumbing::query_ensure_error_guaranteed::<rustc_query_system::query::caches::VecCache<rustc_span::def_id::LocalDefId, rustc_middle::query::erase::Erased<[u8; 1]>>, ()>
            72: <rustc_middle::hir::ModuleItems>::par_opaques::<rustc_hir_analysis::check::wfcheck::check_mod_type_wf::{closure#4}>
            73: rustc_hir_analysis::check::wfcheck::check_mod_type_wf
            74: rustc_query_impl::plumbing::__rust_begin_short_backtrace::<rustc_query_impl::query_impl::check_mod_type_wf::dynamic_query::{closure#2}::{closure#0}, rustc_middle::query::erase::Erased<[u8; 1]>>
            75: <rustc_query_impl::query_impl::check_mod_type_wf::dynamic_query::{closure#2} as core::ops::function::FnOnce<(rustc_middle::ty::context::TyCtxt, rustc_span::def_id::LocalModDefId)>>::call_once
            76: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::DynamicConfig<rustc_query_system::query::caches::DefaultCache<rustc_span::def_id::LocalModDefId, rustc_middle::query::erase::Erased<[u8; 1]>>, false, false, false>, rustc_query_impl::plumbing::QueryCtxt, true>
            77: rustc_query_impl::query_impl::check_mod_type_wf::get_query_incr::__rust_end_short_backtrace
            78: <rustc_data_structures::sync::parallel::ParallelGuard>::run::<(), rustc_data_structures::sync::parallel::par_for_each_in<&rustc_hir::hir_id::OwnerId, &[rustc_hir::hir_id::OwnerId], <rustc_middle::hir::map::Map>::par_for_each_module<rustc_hir_analysis::check_crate::{closure#0}::{closure#0}>::{closure#0}>::{closure#0}::{closure#1}::{closure#0}>
            79: rustc_hir_analysis::check_crate
            80: rustc_interface::passes::analysis
            81: rustc_query_impl::plumbing::__rust_begin_short_backtrace::<rustc_query_impl::query_impl::analysis::dynamic_query::{closure#2}::{closure#0}, rustc_middle::query::erase::Erased<[u8; 1]>>
            82: <rustc_query_impl::query_impl::analysis::dynamic_query::{closure#2} as core::ops::function::FnOnce<(rustc_middle::ty::context::TyCtxt, ())>>::call_once
            83: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::DynamicConfig<rustc_query_system::query::caches::SingleCache<rustc_middle::query::erase::Erased<[u8; 1]>>, false, false, false>, rustc_query_impl::plumbing::QueryCtxt, true>
            84: rustc_query_impl::query_impl::analysis::get_query_incr::__rust_end_short_backtrace
            85: <rustc_middle::ty::context::GlobalCtxt>::enter::<rustc_driver_impl::run_compiler::{closure#0}::{closure#1}::{closure#5}, core::result::Result<(), rustc_span::ErrorGuaranteed>>
            86: <rustc_interface::interface::Compiler>::enter::<rustc_driver_impl::run_compiler::{closure#0}::{closure#1}, core::result::Result<core::option::Option<rustc_interface::queries::Linker>, rustc_span::ErrorGuaranteed>>
            87: <scoped_tls::ScopedKey<rustc_span::SessionGlobals>>::set::<rustc_interface::util::run_in_thread_with_globals<rustc_interface::util::run_in_thread_pool_with_globals<rustc_interface::interface::run_compiler<core::result::Result<(), rustc_span::ErrorGuaranteed>, rustc_driver_impl::run_compiler::{closure#0}>::{closure#1}, core::result::Result<(), rustc_span::ErrorGuaranteed>>::{closure#0}, core::result::Result<(), rustc_span::ErrorGuaranteed>>::{closure#0}::{closure#0}::{closure#0}, core::result::Result<(), rustc_span::ErrorGuaranteed>>
            88: rustc_span::create_session_globals_then::<core::result::Result<(), rustc_span::ErrorGuaranteed>, rustc_interface::util::run_in_thread_with_globals<rustc_interface::util::run_in_thread_pool_with_globals<rustc_interface::interface::run_compiler<core::result::Result<(), rustc_span::ErrorGuaranteed>, rustc_driver_impl::run_compiler::{closure#0}>::{closure#1}, core::result::Result<(), rustc_span::ErrorGuaranteed>>::{closure#0}, core::result::Result<(), rustc_span::ErrorGuaranteed>>::{closure#0}::{closure#0}::{closure#0}>
            89: std::sys::backtrace::__rust_begin_short_backtrace::<rustc_interface::util::run_in_thread_with_globals<rustc_interface::util::run_in_thread_pool_with_globals<rustc_interface::interface::run_compiler<core::result::Result<(), rustc_span::ErrorGuaranteed>, rustc_driver_impl::run_compiler::{closure#0}>::{closure#1}, core::result::Result<(), rustc_span::ErrorGuaranteed>>::{closure#0}, core::result::Result<(), rustc_span::ErrorGuaranteed>>::{closure#0}::{closure#0}, core::result::Result<(), rustc_span::ErrorGuaranteed>>
            90: <<std::thread::Builder>::spawn_unchecked_<rustc_interface::util::run_in_thread_with_globals<rustc_interface::util::run_in_thread_pool_with_globals<rustc_interface::interface::run_compiler<core::result::Result<(), rustc_span::ErrorGuaranteed>, rustc_driver_impl::run_compiler::{closure#0}>::{closure#1}, core::result::Result<(), rustc_span::ErrorGuaranteed>>::{closure#0}, core::result::Result<(), rustc_span::ErrorGuaranteed>>::{closure#0}::{closure#0}, core::result::Result<(), rustc_span::ErrorGuaranteed>>::{closure#1} as core::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
            91: std::sys::pal::unix::thread::Thread::new::thread_start
            92: __pthread_joiner_wake
          

error: internal compiler error: Encountered anon const with inference variable args but no error reported
  |
  = note: delayed at compiler/rustc_trait_selection/src/traits/mod.rs:592:27
             0: std::backtrace::Backtrace::create
             1: <rustc_errors::DiagCtxtInner>::emit_diagnostic
             2: <rustc_errors::DiagCtxtHandle>::emit_diagnostic
             3: <rustc_errors::diagnostic::Diag>::emit_producing_error_guaranteed
             4: <rustc_errors::DiagCtxtHandle>::delayed_bug::<&str>
             5: rustc_trait_selection::traits::try_evaluate_const
             6: rustc_trait_selection::traits::util::with_replaced_escaping_bound_vars::<rustc_middle::ty::consts::Const, rustc_middle::ty::consts::Const, <rustc_trait_selection::traits::normalize::AssocTypeNormalizer as rustc_type_ir::fold::TypeFolder<rustc_middle::ty::context::TyCtxt>>::fold_const::{closure#0}>
             7: <rustc_trait_selection::traits::normalize::AssocTypeNormalizer as rustc_type_ir::fold::TypeFolder<rustc_middle::ty::context::TyCtxt>>::fold_const
             8: <rustc_middle::ty::Ty as rustc_type_ir::fold::TypeSuperFoldable<rustc_middle::ty::context::TyCtxt>>::try_super_fold_with::<rustc_trait_selection::traits::normalize::AssocTypeNormalizer>
             9: <&rustc_middle::ty::list::RawList<(), rustc_middle::ty::generic_args::GenericArg> as rustc_type_ir::fold::TypeFoldable<rustc_middle::ty::context::TyCtxt>>::try_fold_with::<rustc_trait_selection::traits::normalize::AssocTypeNormalizer>
            10: <rustc_middle::ty::Ty as rustc_type_ir::fold::TypeSuperFoldable<rustc_middle::ty::context::TyCtxt>>::try_super_fold_with::<rustc_trait_selection::traits::normalize::AssocTypeNormalizer>
            11: rustc_middle::ty::util::fold_list::<rustc_trait_selection::traits::normalize::AssocTypeNormalizer, &rustc_middle::ty::list::RawList<(), rustc_middle::ty::Ty>, rustc_middle::ty::Ty, <&rustc_middle::ty::list::RawList<(), rustc_middle::ty::Ty> as rustc_type_ir::fold::TypeFoldable<rustc_middle::ty::context::TyCtxt>>::try_fold_with<rustc_trait_selection::traits::normalize::AssocTypeNormalizer>::{closure#0}>
            12: <rustc_trait_selection::traits::normalize::AssocTypeNormalizer>::fold::<rustc_type_ir::ty_kind::FnSig<rustc_middle::ty::context::TyCtxt>>
            13: rustc_trait_selection::traits::normalize::normalize_with_depth::<rustc_type_ir::ty_kind::FnSig<rustc_middle::ty::context::TyCtxt>>
            14: <rustc_infer::infer::at::At as rustc_trait_selection::traits::normalize::NormalizeExt>::normalize::<rustc_type_ir::ty_kind::FnSig<rustc_middle::ty::context::TyCtxt>>
            15: <rustc_hir_typeck::fn_ctxt::FnCtxt>::normalize::<rustc_type_ir::ty_kind::FnSig<rustc_middle::ty::context::TyCtxt>>
            16: <rustc_hir_typeck::fn_ctxt::FnCtxt>::confirm_builtin_call
            17: <rustc_hir_typeck::fn_ctxt::FnCtxt>::check_expr_kind
            18: <rustc_hir_typeck::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
            19: <rustc_hir_typeck::fn_ctxt::FnCtxt>::check_expr_kind
            20: <rustc_hir_typeck::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
            21: <rustc_hir_typeck::fn_ctxt::FnCtxt>::check_decl
            22: <rustc_hir_typeck::fn_ctxt::FnCtxt>::check_expr_block
            23: <rustc_hir_typeck::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
            24: <rustc_hir_typeck::fn_ctxt::FnCtxt>::check_expr_kind
            25: <rustc_hir_typeck::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
            26: <rustc_hir_typeck::fn_ctxt::FnCtxt>::check_expr_block
            27: <rustc_hir_typeck::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
            28: <rustc_hir_typeck::fn_ctxt::FnCtxt>::check_expr_kind
            29: <rustc_hir_typeck::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
            30: <rustc_hir_typeck::fn_ctxt::FnCtxt>::check_expr_block
            31: <rustc_hir_typeck::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
            32: <rustc_hir_typeck::fn_ctxt::FnCtxt>::check_expr_kind
            33: <rustc_hir_typeck::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
            34: <rustc_hir_typeck::fn_ctxt::FnCtxt>::check_expr_block
            35: <rustc_hir_typeck::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
            36: <rustc_hir_typeck::fn_ctxt::FnCtxt>::check_expr_kind
            37: <rustc_hir_typeck::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
            38: <rustc_hir_typeck::fn_ctxt::FnCtxt>::check_expr_block
            39: <rustc_hir_typeck::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
            40: <rustc_hir_typeck::fn_ctxt::FnCtxt>::check_expr_kind
            41: <rustc_hir_typeck::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
            42: <rustc_hir_typeck::fn_ctxt::FnCtxt>::check_expr_block
            43: <rustc_hir_typeck::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
            44: <rustc_hir_typeck::fn_ctxt::FnCtxt>::check_return_or_body_tail
            45: rustc_hir_typeck::check::check_fn
            46: <rustc_hir_typeck::fn_ctxt::FnCtxt>::check_expr_kind
            47: <rustc_hir_typeck::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
            48: <rustc_hir_typeck::fn_ctxt::FnCtxt>::check_return_or_body_tail
            49: rustc_hir_typeck::check::check_fn
            50: rustc_hir_typeck::typeck
            51: rustc_query_impl::plumbing::__rust_begin_short_backtrace::<rustc_query_impl::query_impl::typeck::dynamic_query::{closure#2}::{closure#0}, rustc_middle::query::erase::Erased<[u8; 8]>>
            52: <rustc_query_impl::query_impl::typeck::dynamic_query::{closure#2} as core::ops::function::FnOnce<(rustc_middle::ty::context::TyCtxt, rustc_span::def_id::LocalDefId)>>::call_once
            53: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::DynamicConfig<rustc_query_system::query::caches::VecCache<rustc_span::def_id::LocalDefId, rustc_middle::query::erase::Erased<[u8; 8]>>, false, false, false>, rustc_query_impl::plumbing::QueryCtxt, true>
            54: rustc_query_impl::query_impl::typeck::get_query_incr::__rust_end_short_backtrace
            55: rustc_middle::query::plumbing::query_get_at::<rustc_query_system::query::caches::VecCache<rustc_span::def_id::LocalDefId, rustc_middle::query::erase::Erased<[u8; 8]>>>
            56: rustc_hir_analysis::collect::type_of::opaque::find_opaque_ty_constraints_for_rpit
            57: rustc_hir_analysis::collect::type_of::type_of_opaque
            58: rustc_query_impl::plumbing::__rust_begin_short_backtrace::<rustc_query_impl::query_impl::type_of_opaque::dynamic_query::{closure#2}::{closure#0}, rustc_middle::query::erase::Erased<[u8; 8]>>
            59: <rustc_query_impl::query_impl::type_of_opaque::dynamic_query::{closure#2} as core::ops::function::FnOnce<(rustc_middle::ty::context::TyCtxt, rustc_span::def_id::DefId)>>::call_once
            60: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::DynamicConfig<rustc_query_system::query::caches::DefIdCache<rustc_middle::query::erase::Erased<[u8; 8]>>, false, false, false>, rustc_query_impl::plumbing::QueryCtxt, true>
            61: rustc_query_impl::query_impl::type_of_opaque::get_query_incr::__rust_end_short_backtrace
            62: rustc_middle::query::plumbing::query_get_at::<rustc_query_system::query::caches::DefIdCache<rustc_middle::query::erase::Erased<[u8; 8]>>>
            63: rustc_hir_analysis::collect::type_of::type_of
            64: rustc_query_impl::plumbing::__rust_begin_short_backtrace::<rustc_query_impl::query_impl::type_of::dynamic_query::{closure#2}::{closure#0}, rustc_middle::query::erase::Erased<[u8; 8]>>
            65: <rustc_query_impl::query_impl::type_of::dynamic_query::{closure#2} as core::ops::function::FnOnce<(rustc_middle::ty::context::TyCtxt, rustc_span::def_id::DefId)>>::call_once
            66: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::DynamicConfig<rustc_query_system::query::caches::DefIdCache<rustc_middle::query::erase::Erased<[u8; 8]>>, false, false, false>, rustc_query_impl::plumbing::QueryCtxt, true>
            67: rustc_query_impl::query_impl::type_of::get_query_incr::__rust_end_short_backtrace
            68: rustc_middle::query::plumbing::query_get_at::<rustc_query_system::query::caches::DefIdCache<rustc_middle::query::erase::Erased<[u8; 8]>>>
            69: rustc_hir_analysis::check::check::check_item_type
            70: rustc_hir_analysis::check::wfcheck::check_well_formed
            71: rustc_query_impl::plumbing::__rust_begin_short_backtrace::<rustc_query_impl::query_impl::check_well_formed::dynamic_query::{closure#2}::{closure#0}, rustc_middle::query::erase::Erased<[u8; 1]>>
            72: <rustc_query_impl::query_impl::check_well_formed::dynamic_query::{closure#2} as core::ops::function::FnOnce<(rustc_middle::ty::context::TyCtxt, rustc_span::def_id::LocalDefId)>>::call_once
            73: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::DynamicConfig<rustc_query_system::query::caches::VecCache<rustc_span::def_id::LocalDefId, rustc_middle::query::erase::Erased<[u8; 1]>>, false, false, false>, rustc_query_impl::plumbing::QueryCtxt, true>
            74: rustc_query_impl::query_impl::check_well_formed::get_query_incr::__rust_end_short_backtrace
            75: rustc_middle::query::plumbing::query_ensure_error_guaranteed::<rustc_query_system::query::caches::VecCache<rustc_span::def_id::LocalDefId, rustc_middle::query::erase::Erased<[u8; 1]>>, ()>
            76: <rustc_middle::hir::ModuleItems>::par_opaques::<rustc_hir_analysis::check::wfcheck::check_mod_type_wf::{closure#4}>
            77: rustc_hir_analysis::check::wfcheck::check_mod_type_wf
            78: rustc_query_impl::plumbing::__rust_begin_short_backtrace::<rustc_query_impl::query_impl::check_mod_type_wf::dynamic_query::{closure#2}::{closure#0}, rustc_middle::query::erase::Erased<[u8; 1]>>
            79: <rustc_query_impl::query_impl::check_mod_type_wf::dynamic_query::{closure#2} as core::ops::function::FnOnce<(rustc_middle::ty::context::TyCtxt, rustc_span::def_id::LocalModDefId)>>::call_once
            80: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::DynamicConfig<rustc_query_system::query::caches::DefaultCache<rustc_span::def_id::LocalModDefId, rustc_middle::query::erase::Erased<[u8; 1]>>, false, false, false>, rustc_query_impl::plumbing::QueryCtxt, true>
            81: rustc_query_impl::query_impl::check_mod_type_wf::get_query_incr::__rust_end_short_backtrace
            82: <rustc_data_structures::sync::parallel::ParallelGuard>::run::<(), rustc_data_structures::sync::parallel::par_for_each_in<&rustc_hir::hir_id::OwnerId, &[rustc_hir::hir_id::OwnerId], <rustc_middle::hir::map::Map>::par_for_each_module<rustc_hir_analysis::check_crate::{closure#0}::{closure#0}>::{closure#0}>::{closure#0}::{closure#1}::{closure#0}>
            83: rustc_hir_analysis::check_crate
            84: rustc_interface::passes::analysis
            85: rustc_query_impl::plumbing::__rust_begin_short_backtrace::<rustc_query_impl::query_impl::analysis::dynamic_query::{closure#2}::{closure#0}, rustc_middle::query::erase::Erased<[u8; 1]>>
            86: <rustc_query_impl::query_impl::analysis::dynamic_query::{closure#2} as core::ops::function::FnOnce<(rustc_middle::ty::context::TyCtxt, ())>>::call_once
            87: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::DynamicConfig<rustc_query_system::query::caches::SingleCache<rustc_middle::query::erase::Erased<[u8; 1]>>, false, false, false>, rustc_query_impl::plumbing::QueryCtxt, true>
            88: rustc_query_impl::query_impl::analysis::get_query_incr::__rust_end_short_backtrace
            89: <rustc_middle::ty::context::GlobalCtxt>::enter::<rustc_driver_impl::run_compiler::{closure#0}::{closure#1}::{closure#5}, core::result::Result<(), rustc_span::ErrorGuaranteed>>
            90: <rustc_interface::interface::Compiler>::enter::<rustc_driver_impl::run_compiler::{closure#0}::{closure#1}, core::result::Result<core::option::Option<rustc_interface::queries::Linker>, rustc_span::ErrorGuaranteed>>
            91: <scoped_tls::ScopedKey<rustc_span::SessionGlobals>>::set::<rustc_interface::util::run_in_thread_with_globals<rustc_interface::util::run_in_thread_pool_with_globals<rustc_interface::interface::run_compiler<core::result::Result<(), rustc_span::ErrorGuaranteed>, rustc_driver_impl::run_compiler::{closure#0}>::{closure#1}, core::result::Result<(), rustc_span::ErrorGuaranteed>>::{closure#0}, core::result::Result<(), rustc_span::ErrorGuaranteed>>::{closure#0}::{closure#0}::{closure#0}, core::result::Result<(), rustc_span::ErrorGuaranteed>>
            92: rustc_span::create_session_globals_then::<core::result::Result<(), rustc_span::ErrorGuaranteed>, rustc_interface::util::run_in_thread_with_globals<rustc_interface::util::run_in_thread_pool_with_globals<rustc_interface::interface::run_compiler<core::result::Result<(), rustc_span::ErrorGuaranteed>, rustc_driver_impl::run_compiler::{closure#0}>::{closure#1}, core::result::Result<(), rustc_span::ErrorGuaranteed>>::{closure#0}, core::result::Result<(), rustc_span::ErrorGuaranteed>>::{closure#0}::{closure#0}::{closure#0}>
            93: std::sys::backtrace::__rust_begin_short_backtrace::<rustc_interface::util::run_in_thread_with_globals<rustc_interface::util::run_in_thread_pool_with_globals<rustc_interface::interface::run_compiler<core::result::Result<(), rustc_span::ErrorGuaranteed>, rustc_driver_impl::run_compiler::{closure#0}>::{closure#1}, core::result::Result<(), rustc_span::ErrorGuaranteed>>::{closure#0}, core::result::Result<(), rustc_span::ErrorGuaranteed>>::{closure#0}::{closure#0}, core::result::Result<(), rustc_span::ErrorGuaranteed>>
            94: <<std::thread::Builder>::spawn_unchecked_<rustc_interface::util::run_in_thread_with_globals<rustc_interface::util::run_in_thread_pool_with_globals<rustc_interface::interface::run_compiler<core::result::Result<(), rustc_span::ErrorGuaranteed>, rustc_driver_impl::run_compiler::{closure#0}>::{closure#1}, core::result::Result<(), rustc_span::ErrorGuaranteed>>::{closure#0}, core::result::Result<(), rustc_span::ErrorGuaranteed>>::{closure#0}::{closure#0}, core::result::Result<(), rustc_span::ErrorGuaranteed>>::{closure#1} as core::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
            95: std::sys::pal::unix::thread::Thread::new::thread_start
            96: __pthread_joiner_wake
          

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: please make sure that you have updated to the latest nightly

note: please attach the file at `/Users/vinay10949/Projects/decentralization/mishti/rustc-ice-2024-11-19T06_58_39-31408.txt` to your bug report

note: compiler flags: --crate-type bin -C opt-level=1 -C embed-bitcode=no -C codegen-units=16 -C incremental=[REDACTED] -C strip=debuginfo

note: some of the compiler flags provided by cargo are hidden
  process didn't exit successfully: `/Users/vinay10949/.rustup/toolchains/nightly-aarch64-apple-darwin/bin/rustc --crate-name cli --edition=2021 crates/cli/src/main.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --diagnostic-width=214 --crate-type bin --emit=dep-info,link -C opt-level=1 -C embed-bitcode=no -C codegen-units=16 --check-cfg 'cfg(docsrs)' --check-cfg 'cfg(feature, values())' -C metadata=70ab92cf0b9de42f -C extra-filename=-70ab92cf0b9de42f --out-dir /Users/vinay10949/Projects/decentralization/mishti/target/release/deps -C incremental=/Users/vinay10949/Projects/decentralization/mishti/target/release/incremental -C strip=debuginfo -L dependency=/Users/vinay10949/Projects/decentralization/mishti/target/release/deps --extern ark_ed_on_bn254=/Users/vinay10949/Projects/decentralization/mishti/target/release/deps/libark_ed_on_bn254-777124926cde145d.rlib --extern bincode=/Users/vinay10949/Projects/decentralization/mishti/target/release/deps/libbincode-a4f2d93a3bd1ddb3.rlib --extern clap=/Users/vinay10949/Projects/decentralization/mishti/target/release/deps/libclap-1d47a124b7004df9.rlib --extern ethers=/Users/vinay10949/Projects/decentralization/mishti/target/release/deps/libethers-1d79a5372af84fcf.rlib --extern hex=/Users/vinay10949/Projects/decentralization/mishti/target/release/deps/libhex-f69836561b5d2b7a.rlib --extern jsonrpsee=/Users/vinay10949/Projects/decentralization/mishti/target/release/deps/libjsonrpsee-0fa323a445b5abbc.rlib --extern k256=/Users/vinay10949/Projects/decentralization/mishti/target/release/deps/libk256-ac9554dfc2fa9660.rlib --extern lazy_static=/Users/vinay10949/Projects/decentralization/mishti/target/release/deps/liblazy_static-5e8ba3436795d5f4.rlib --extern messages=/Users/vinay10949/Projects/decentralization/mishti/target/release/deps/libmessages-bdc67d924ef483e4.rlib --extern mishti_crypto=/Users/vinay10949/Projects/decentralization/mishti/target/release/deps/libmishti_crypto-902b75e01588415f.rlib --extern rpc=/Users/vinay10949/Projects/decentralization/mishti/target/release/deps/librpc-e5365e8e82434d6b.rlib --extern rpc_trait=/Users/vinay10949/Projects/decentralization/mishti/target/release/deps/librpc_trait-1ab4dd0cb547c6c6.rlib --extern serde=/Users/vinay10949/Projects/decentralization/mishti/target/release/deps/libserde-672fcdd673a9e4af.rlib --extern serde_json=/Users/vinay10949/Projects/decentralization/mishti/target/release/deps/libserde_json-14d850a95cd08348.rlib --extern tokio=/Users/vinay10949/Projects/decentralization/mishti/target/release/deps/libtokio-54ad075d7acae233.rlib -L native=/Users/vinay10949/Projects/decentralization/mishti/target/release/build/ring-86ddefc3f904ee03/out -L native=/Users/vinay10949/Projects/decentralization/mishti/target/release/build/ring-220aa74511dbaf84/out -L native=/Users/vinay10949/Projects/decentralization/mishti/target/release/build/aws-lc-sys-8f36e1429ba5de38/out -L /Library/Developer/CommandLineTools/usr/lib/clang/15.0.0/lib/darwin -L native=/Users/vinay10949/Projects/decentralization/mishti/target/release/build/curl-sys-bd51297106f6900d/out/build -L native=/Users/vinay10949/Projects/decentralization/mishti/target/release/build/libnghttp2-sys-dd553636cd0d1bf6/out/i/lib -L native=/Users/vinay10949/Projects/decentralization/mishti/target/release/build/secp256k1-sys-1c14aa07d67558b4/out` (exit status: 101)
```

### Anything else?

_No response_

### LINKED ISSUE #136894: ICE: GCE: should never serialize an `ErrorGuaranteed`
### Reproducer

```rs
#![feature(generic_const_exprs)]
#![crate_type = "lib"]
#![allow(incomplete_features, dead_code)]

struct X<T>([(); f::<T>()]) where [(); f::<T>()]:;

const fn f<T>() -> usize { panic!() }
```

### Compiler Output (Sans Backtrace)

```
error[E0080]: evaluation of `X::<T>::0::{constant#0}` failed
 --> file.rs:7:28
  |
7 | const fn f<T>() -> usize { panic!() }
  |                            ^^^^^^^^ the evaluated program panicked at 'explicit panic', file.rs:7:28
  |
note: inside `f::<T>`
 --> file.rs:7:28
  |
7 | const fn f<T>() -> usize { panic!() }
  |                            ^^^^^^^^
note: inside `X::<T>::0::{constant#0}`
 --> file.rs:5:18
  |
5 | struct X<T>([(); f::<T>()]) where [(); f::<T>()]:;
  |                  ^^^^^^^^
  = note: this error originates in the macro `$crate::panic::panic_2015` which comes from the expansion of the macro `panic` (in Nightly builds, run with -Z macro-backtrace for more info)


thread 'rustc' panicked at /rustc/8239a37f9c0951a037cfc51763ea52a20e71e6bd/compiler/rustc_span/src/lib.rs:2665:9:
should never serialize an `ErrorGuaranteed`, as we do not write metadata or incremental caches in case errors occurred
```

### Backtrace

<details>

```
stack backtrace:
   0:     0x7a9e3ae2f180 - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::h81d5cbdf1b69611b
   1:     0x7a9e3b614826 - core::fmt::write::h004effb614950758
   2:     0x7a9e3c93a951 - std::io::Write::write_fmt::h71b393f1dd6d3556
   3:     0x7a9e3ae2efe2 - std::sys::backtrace::BacktraceLock::print::ha1521ca4cee64882
   4:     0x7a9e3ae31462 - std::panicking::default_hook::{{closure}}::h4131e4b424b71f39
   5:     0x7a9e3ae312ea - std::panicking::default_hook::hb9ab590f893fbc38
   6:     0x7a9e39f891a9 - std[3aba936f908a5414]::panicking::update_hook::<alloc[63d497d918fea2c7]::boxed::Box<rustc_driver_impl[721d5621d7af7046]::install_ice_hook::{closure#1}>>::{closure#0}
   7:     0x7a9e3ae31fa3 - std::panicking::rust_panic_with_hook::h6c45a78eda21d529
   8:     0x7a9e3ae31c66 - std::panicking::begin_panic_handler::{{closure}}::hf7369b9b7411c9ce
   9:     0x7a9e3ae2f669 - std::sys::backtrace::__rust_end_short_backtrace::hea30991d3cd62b9b
  10:     0x7a9e3ae3195d - rust_begin_unwind
  11:     0x7a9e37a55520 - core::panicking::panic_fmt::hc1e066b7e640f877
  12:     0x7a9e3cd62ecc - <rustc_type_ir[dd9c929f2a6045ff]::const_kind::ConstKind<rustc_middle[7bd58a081650d673]::ty::context::TyCtxt> as rustc_serialize[cbdad422c51ca922]::serialize::Encodable<rustc_metadata[140e3238f6966a11]::rmeta::encoder::EncodeContext>>::encode.cold
  13:     0x7a9e3ba2bf37 - rustc_middle[7bd58a081650d673]::ty::codec::encode_with_shorthand::<rustc_metadata[140e3238f6966a11]::rmeta::encoder::EncodeContext, rustc_middle[7bd58a081650d673]::ty::Ty, <rustc_metadata[140e3238f6966a11]::rmeta::encoder::EncodeContext as rustc_type_ir[dd9c929f2a6045ff]::codec::TyEncoder>::type_shorthands>
  14:     0x7a9e3c19d9fd - <rustc_middle[7bd58a081650d673]::mir::Body as rustc_serialize[cbdad422c51ca922]::serialize::Encodable<rustc_metadata[140e3238f6966a11]::rmeta::encoder::EncodeContext>>::encode
  15:     0x7a9e3c184fdc - <rustc_metadata[140e3238f6966a11]::rmeta::encoder::EncodeContext>::encode_crate_root
  16:     0x7a9e3c5ee24e - rustc_metadata[140e3238f6966a11]::rmeta::encoder::encode_metadata
  17:     0x7a9e3c5fc9f6 - rustc_metadata[140e3238f6966a11]::fs::encode_and_write_metadata
  18:     0x7a9e3c5fb88e - <rustc_interface[8dbe8781a5115760]::queries::Linker>::codegen_and_build_linker
  19:     0x7a9e3c5f219f - rustc_interface[8dbe8781a5115760]::passes::create_and_enter_global_ctxt::<core[58638448a60e4528]::option::Option<rustc_interface[8dbe8781a5115760]::queries::Linker>, rustc_driver_impl[721d5621d7af7046]::run_compiler::{closure#0}::{closure#2}>::{closure#2}::{closure#0}
  20:     0x7a9e3c56cf73 - rustc_interface[8dbe8781a5115760]::interface::run_compiler::<(), rustc_driver_impl[721d5621d7af7046]::run_compiler::{closure#0}>::{closure#1}
  21:     0x7a9e3c4aa9b5 - std[3aba936f908a5414]::sys::backtrace::__rust_begin_short_backtrace::<rustc_interface[8dbe8781a5115760]::util::run_in_thread_with_globals<rustc_interface[8dbe8781a5115760]::util::run_in_thread_pool_with_globals<rustc_interface[8dbe8781a5115760]::interface::run_compiler<(), rustc_driver_impl[721d5621d7af7046]::run_compiler::{closure#0}>::{closure#1}, ()>::{closure#0}, ()>::{closure#0}::{closure#0}, ()>
  22:     0x7a9e3c4aa699 - <<std[3aba936f908a5414]::thread::Builder>::spawn_unchecked_<rustc_interface[8dbe8781a5115760]::util::run_in_thread_with_globals<rustc_interface[8dbe8781a5115760]::util::run_in_thread_pool_with_globals<rustc_interface[8dbe8781a5115760]::interface::run_compiler<(), rustc_driver_impl[721d5621d7af7046]::run_compiler::{closure#0}>::{closure#1}, ()>::{closure#0}, ()>::{closure#0}::{closure#0}, ()>::{closure#1} as core[58638448a60e4528]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  23:     0x7a9e3c4a9e2f - std::sys::pal::unix::thread::Thread::new::thread_start::h87f43e958a0cb0f1
  24:     0x7a9e366a339d - <unknown>
  25:     0x7a9e3672849c - <unknown>
  26:                0x0 - <unknown>

error: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: please make sure that you have updated to the latest nightly

note: rustc 1.86.0-nightly (8239a37f9 2025-02-01) running on x86_64-unknown-linux-gnu

note: compiler flags: --crate-type lib

query stack during panic:
end of query stack
error: aborting due to 1 previous error

For more information about this error, try `rustc --explain E0080`.
error: process exited unsuccessfully: exit status: 101
```

</details>

### LINKED ISSUE #137813: ICE: `did not expect inference variables here` (wfck)
auto-reduced (treereduce-rust):
````rust
//@compile-flags: -Zincremental-verify-ich=yes -Cincremental=<dir> -Cdebuginfo=2 -Clink-dead-code=true -Zvalidate-mir --edition=2024
pub struct NoPin;

pub trait PinA<PER> {
    const A: u8;
}

impl<PER> PinA<PER> for NoPin {
    const A: u8 = 0;
}

pub trait Pins<USART> {}

impl<USART, T> Pins for T where T: PinA<USART, A = { TA }> {}

impl<USART> Serial<USART> where NoPin: Pins<USART> {}

````

<details><summary><strong>original code</strong></summary>
<p>

original:
````rust
// ICE assertion failed: matches!(self.def_kind(ct.def.did), DefKind :: AnonConst)
// issue: rust-lang/rust#108220
//@ check-pass

#![feature(associated_const_equality)]
#![allow(unused)]

use std::marker::PhantomData;

pub struct NoPin;

pub trait SetAlternate<const A: u8> {}

impl SetAlternate<0> for NoPin {}

pub trait PinA<PER> {
    const A: u8;
}

impl<PER> PinA<PER> for NoPin {
    const A: u8 = 0;
}

pub trait Pins<USART> {}

impl<USART, T, const TA: u8> Pins<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S
<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S
<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S
<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S
<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S
<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S
<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S
<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S
<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S
<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S
<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S
<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S
<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S
<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S
<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S
<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S
<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S
<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S
<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S
<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S
<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S
<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S
<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S
<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S
<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S
<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S
<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S
<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S
<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S
<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S
<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S
<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S
<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S
<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S
<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<S<Z>>>>>>>>>>>>>>
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> for T where
    T: PinA<USART, A = { TA }> + SetAlternate<TA>
{
}

struct Serial<USART>(PhantomData<USART>);

impl<USART> Serial<USART> where NoPin: Pins<USART> {}

fn main() {}

````
</p>
</details>

Version information
````
rustc 1.87.0-nightly (2f581937e 2025-02-28)
binary: rustc
commit-hash: 2f581937e1c06adb4607df1b571c0bef6d98e6ec
commit-date: 2025-02-28
host: x86_64-unknown-linux-gnu
release: 1.87.0-nightly
LLVM version: 20.1.0

````

Possibly related line of code:
https://github.com/rust-lang/rust/blob/2f581937e1c06adb4607df1b571c0bef6d98e6ec/compiler/rustc_middle/src/mir/interpret/queries.rs#L99-L111

Command:
`/home/matthias/.rustup/toolchains/master/bin/rustc -Zincremental-verify-ich=yes -Cincremental=<dir> -Cdebuginfo=2 -Clink-dead-code=true -Zvalidate-mir --edition=2024`

<details><summary><strong>Program output</strong></summary>
<p>

```
error[E0425]: cannot find value `TA` in this scope
  --> /tmp/icemaker_global_tempdir.tBkXQn2yGgp5/rustc_testrunner_tmpdir_reporting.jQl3AZtGBbLi/mvce.rs:13:54
   |
13 | impl<USART, T> Pins for T where T: PinA<USART, A = { TA }> {}
   |                                                      ^^ not found in this scope

error[E0412]: cannot find type `Serial` in this scope
  --> /tmp/icemaker_global_tempdir.tBkXQn2yGgp5/rustc_testrunner_tmpdir_reporting.jQl3AZtGBbLi/mvce.rs:15:13
   |
15 | impl<USART> Serial<USART> where NoPin: Pins<USART> {}
   |             ^^^^^^ not found in this scope

error[E0658]: associated const equality is incomplete
  --> /tmp/icemaker_global_tempdir.tBkXQn2yGgp5/rustc_testrunner_tmpdir_reporting.jQl3AZtGBbLi/mvce.rs:13:48
   |
13 | impl<USART, T> Pins for T where T: PinA<USART, A = { TA }> {}
   |                                                ^^^^^^^^^^
   |
   = note: see issue #92827 <https://github.com/rust-lang/rust/issues/92827> for more information
   = help: add `#![feature(associated_const_equality)]` to the crate attributes to enable
   = note: this compiler was built on 2025-02-28; consider upgrading it if it is out of date

error[E0601]: `main` function not found in crate `mvce`
  --> /tmp/icemaker_global_tempdir.tBkXQn2yGgp5/rustc_testrunner_tmpdir_reporting.jQl3AZtGBbLi/mvce.rs:15:54
   |
15 | impl<USART> Serial<USART> where NoPin: Pins<USART> {}
   |                                                      ^ consider adding a `main` function to `/tmp/icemaker_global_tempdir.tBkXQn2yGgp5/rustc_testrunner_tmpdir_reporting.jQl3AZtGBbLi/mvce.rs`

error[E0107]: missing generics for trait `Pins`
  --> /tmp/icemaker_global_tempdir.tBkXQn2yGgp5/rustc_testrunner_tmpdir_reporting.jQl3AZtGBbLi/mvce.rs:13:16
   |
13 | impl<USART, T> Pins for T where T: PinA<USART, A = { TA }> {}
   |                ^^^^ expected 1 generic argument
   |
note: trait defined here, with 1 generic parameter: `USART`
  --> /tmp/icemaker_global_tempdir.tBkXQn2yGgp5/rustc_testrunner_tmpdir_reporting.jQl3AZtGBbLi/mvce.rs:11:11
   |
11 | pub trait Pins<USART> {}
   |           ^^^^ -----
help: add missing generic argument
   |
13 | impl<USART, T> Pins<USART> for T where T: PinA<USART, A = { TA }> {}
   |                    +++++++

error: internal compiler error: compiler/rustc_middle/src/mir/interpret/queries.rs:105:13: did not expect inference variables here


thread 'rustc' panicked at compiler/rustc_middle/src/mir/interpret/queries.rs:105:13:
Box<dyn Any>
stack backtrace:
   0:     0x726a695b8794 - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::h8271bd9d6917c499
   1:     0x726a69e166ec - core::fmt::write::hc10118529572c35a
   2:     0x726a6af0a4d1 - std::io::Write::write_fmt::hd4cd3c690e338654
   3:     0x726a695b85f2 - std::sys::backtrace::BacktraceLock::print::hdbbabde34d7ae3a2
   4:     0x726a695bae2e - std::panicking::default_hook::{{closure}}::ha43c2eef4240d1ec
   5:     0x726a695baa04 - std::panicking::default_hook::h40675286f8693d93
   6:     0x726a687168c7 - std[671130e388b9fe6c]::panicking::update_hook::<alloc[bf8eb75a1b7fb173]::boxed::Box<rustc_driver_impl[91dbdd509552bee2]::install_ice_hook::{closure#1}>>::{closure#0}
   7:     0x726a695bb6a3 - std::panicking::rust_panic_with_hook::h89d32dff83379cbd
   8:     0x726a68753571 - std[671130e388b9fe6c]::panicking::begin_panic::<rustc_errors[498bbaf2ad3cdb45]::ExplicitBug>::{closure#0}
   9:     0x726a68747986 - std[671130e388b9fe6c]::sys::backtrace::__rust_end_short_backtrace::<std[671130e388b9fe6c]::panicking::begin_panic<rustc_errors[498bbaf2ad3cdb45]::ExplicitBug>::{closure#0}, !>
  10:     0x726a68744309 - std[671130e388b9fe6c]::panicking::begin_panic::<rustc_errors[498bbaf2ad3cdb45]::ExplicitBug>
  11:     0x726a6875cf61 - <rustc_errors[498bbaf2ad3cdb45]::diagnostic::BugAbort as rustc_errors[498bbaf2ad3cdb45]::diagnostic::EmissionGuarantee>::emit_producing_guarantee
  12:     0x726a68d312f6 - rustc_middle[5ec6377ace10fe5f]::util::bug::opt_span_bug_fmt::<rustc_span[f0d5d7aa1c3a11e8]::span_encoding::Span>::{closure#0}
  13:     0x726a68d18c0a - rustc_middle[5ec6377ace10fe5f]::ty::context::tls::with_opt::<rustc_middle[5ec6377ace10fe5f]::util::bug::opt_span_bug_fmt<rustc_span[f0d5d7aa1c3a11e8]::span_encoding::Span>::{closure#0}, !>::{closure#0}
  14:     0x726a68d18a7b - rustc_middle[5ec6377ace10fe5f]::ty::context::tls::with_context_opt::<rustc_middle[5ec6377ace10fe5f]::ty::context::tls::with_opt<rustc_middle[5ec6377ace10fe5f]::util::bug::opt_span_bug_fmt<rustc_span[f0d5d7aa1c3a11e8]::span_encoding::Span>::{closure#0}, !>::{closure#0}, !>
  15:     0x726a6729b9a0 - rustc_middle[5ec6377ace10fe5f]::util::bug::bug_fmt
  16:     0x726a6b76eed0 - <rustc_middle[5ec6377ace10fe5f]::ty::context::TyCtxt>::const_eval_resolve_for_typeck.cold
  17:     0x726a6a66f9e5 - rustc_trait_selection[f5f12f31b8a38df8]::traits::try_evaluate_const
  18:     0x726a6a66f5c3 - <rustc_trait_selection[f5f12f31b8a38df8]::traits::normalize::AssocTypeNormalizer as rustc_type_ir[a5adda4a46b2bae1]::fold::TypeFolder<rustc_middle[5ec6377ace10fe5f]::ty::context::TyCtxt>>::fold_const
  19:     0x726a6a1fe71f - rustc_trait_selection[f5f12f31b8a38df8]::traits::project::opt_normalize_projection_term
  20:     0x726a69f64281 - rustc_trait_selection[f5f12f31b8a38df8]::traits::project::poly_project_and_unify_term
  21:     0x726a69f6a151 - <rustc_trait_selection[f5f12f31b8a38df8]::traits::select::SelectionContext>::evaluate_candidate::{closure#0}
  22:     0x726a6ae1e526 - <rustc_trait_selection[f5f12f31b8a38df8]::traits::select::SelectionContext>::candidate_from_obligation::{closure#0}::{closure#0}
  23:     0x726a69fc3ddd - <rustc_trait_selection[f5f12f31b8a38df8]::traits::select::SelectionContext>::poly_select::{closure#0}
  24:     0x726a6a6df86f - <rustc_trait_selection[f5f12f31b8a38df8]::traits::fulfill::FulfillProcessor as rustc_data_structures[24cbe30c54d054aa]::obligation_forest::ObligationProcessor>::process_obligation
  25:     0x726a69e0e1e9 - <rustc_data_structures[24cbe30c54d054aa]::obligation_forest::ObligationForest<rustc_trait_selection[f5f12f31b8a38df8]::traits::fulfill::PendingPredicateObligation>>::process_obligations::<rustc_trait_selection[f5f12f31b8a38df8]::traits::fulfill::FulfillProcessor>
  26:     0x726a6a2c4607 - <rustc_trait_selection[f5f12f31b8a38df8]::traits::fulfill::FulfillmentContext<rustc_trait_selection[f5f12f31b8a38df8]::traits::FulfillmentError> as rustc_infer[6424dac916e4534e]::traits::engine::TraitEngine<rustc_trait_selection[f5f12f31b8a38df8]::traits::FulfillmentError>>::select_all_or_error
  27:     0x726a6a570a47 - rustc_hir_analysis[5ff3dce2dca2fb41]::check::wfcheck::check_well_formed
  28:     0x726a6a56f391 - rustc_query_impl[ee3276488b06594c]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[ee3276488b06594c]::query_impl::check_well_formed::dynamic_query::{closure#2}::{closure#0}, rustc_middle[5ec6377ace10fe5f]::query::erase::Erased<[u8; 1usize]>>
  29:     0x726a6a32e1a1 - rustc_query_system[c27e8fb22d1ec87f]::query::plumbing::try_execute_query::<rustc_query_impl[ee3276488b06594c]::DynamicConfig<rustc_data_structures[24cbe30c54d054aa]::vec_cache::VecCache<rustc_span[f0d5d7aa1c3a11e8]::def_id::LocalDefId, rustc_middle[5ec6377ace10fe5f]::query::erase::Erased<[u8; 1usize]>, rustc_query_system[c27e8fb22d1ec87f]::dep_graph::graph::DepNodeIndex>, false, false, false>, rustc_query_impl[ee3276488b06594c]::plumbing::QueryCtxt, true>
  30:     0x726a6a33292c - rustc_query_impl[ee3276488b06594c]::query_impl::check_well_formed::get_query_incr::__rust_end_short_backtrace
  31:     0x726a6a56c11d - rustc_hir_analysis[5ff3dce2dca2fb41]::check::wfcheck::check_mod_type_wf
  32:     0x726a6a56bf1f - rustc_query_impl[ee3276488b06594c]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[ee3276488b06594c]::query_impl::check_mod_type_wf::dynamic_query::{closure#2}::{closure#0}, rustc_middle[5ec6377ace10fe5f]::query::erase::Erased<[u8; 1usize]>>
  33:     0x726a6add7120 - rustc_query_system[c27e8fb22d1ec87f]::query::plumbing::try_execute_query::<rustc_query_impl[ee3276488b06594c]::DynamicConfig<rustc_query_system[c27e8fb22d1ec87f]::query::caches::DefaultCache<rustc_span[f0d5d7aa1c3a11e8]::def_id::LocalModDefId, rustc_middle[5ec6377ace10fe5f]::query::erase::Erased<[u8; 1usize]>>, false, false, false>, rustc_query_impl[ee3276488b06594c]::plumbing::QueryCtxt, true>
  34:     0x726a6add7b7b - rustc_query_impl[ee3276488b06594c]::query_impl::check_mod_type_wf::get_query_incr::__rust_end_short_backtrace
  35:     0x726a6a42258d - rustc_hir_analysis[5ff3dce2dca2fb41]::check_crate
  36:     0x726a6a41cb1c - rustc_interface[d2de745071f2696f]::passes::run_required_analyses
  37:     0x726a6ae87cfa - rustc_interface[d2de745071f2696f]::passes::analysis
  38:     0x726a6ae87cd9 - rustc_query_impl[ee3276488b06594c]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[ee3276488b06594c]::query_impl::analysis::dynamic_query::{closure#2}::{closure#0}, rustc_middle[5ec6377ace10fe5f]::query::erase::Erased<[u8; 0usize]>>
  39:     0x726a6ae835aa - rustc_query_system[c27e8fb22d1ec87f]::query::plumbing::try_execute_query::<rustc_query_impl[ee3276488b06594c]::DynamicConfig<rustc_query_system[c27e8fb22d1ec87f]::query::caches::SingleCache<rustc_middle[5ec6377ace10fe5f]::query::erase::Erased<[u8; 0usize]>>, false, false, false>, rustc_query_impl[ee3276488b06594c]::plumbing::QueryCtxt, true>
  40:     0x726a6ae82fa2 - rustc_query_impl[ee3276488b06594c]::query_impl::analysis::get_query_incr::__rust_end_short_backtrace
  41:     0x726a6af3fd7c - rustc_interface[d2de745071f2696f]::passes::create_and_enter_global_ctxt::<core[c921f6c857728d82]::option::Option<rustc_interface[d2de745071f2696f]::queries::Linker>, rustc_driver_impl[91dbdd509552bee2]::run_compiler::{closure#0}::{closure#2}>::{closure#2}::{closure#0}
  42:     0x726a6aef6fa0 - rustc_interface[d2de745071f2696f]::interface::run_compiler::<(), rustc_driver_impl[91dbdd509552bee2]::run_compiler::{closure#0}>::{closure#1}
  43:     0x726a6ada9788 - std[671130e388b9fe6c]::sys::backtrace::__rust_begin_short_backtrace::<rustc_interface[d2de745071f2696f]::util::run_in_thread_with_globals<rustc_interface[d2de745071f2696f]::util::run_in_thread_pool_with_globals<rustc_interface[d2de745071f2696f]::interface::run_compiler<(), rustc_driver_impl[91dbdd509552bee2]::run_compiler::{closure#0}>::{closure#1}, ()>::{closure#0}, ()>::{closure#0}::{closure#0}, ()>
  44:     0x726a6adaa074 - <<std[671130e388b9fe6c]::thread::Builder>::spawn_unchecked_<rustc_interface[d2de745071f2696f]::util::run_in_thread_with_globals<rustc_interface[d2de745071f2696f]::util::run_in_thread_pool_with_globals<rustc_interface[d2de745071f2696f]::interface::run_compiler<(), rustc_driver_impl[91dbdd509552bee2]::run_compiler::{closure#0}>::{closure#1}, ()>::{closure#0}, ()>::{closure#0}::{closure#0}, ()>::{closure#1} as core[c921f6c857728d82]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  45:     0x726a6adab477 - std::sys::pal::unix::thread::Thread::new::thread_start::h3507b515c9e14c35
  46:     0x726a64ea370a - <unknown>
  47:     0x726a64f27aac - <unknown>
  48:                0x0 - <unknown>

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: please make sure that you have updated to the latest nightly

note: rustc 1.87.0-nightly (2f581937e 2025-02-28) running on x86_64-unknown-linux-gnu

note: compiler flags: -Z incremental-verify-ich=yes -C incremental=[REDACTED] -C debuginfo=2 -C link-dead-code=true -Z validate-mir

query stack during panic:
#0 [check_well_formed] checking that `<impl at /tmp/icemaker_global_tempdir.tBkXQn2yGgp5/rustc_testrunner_tmpdir_reporting.jQl3AZtGBbLi/mvce.rs:15:1: 15:51>` is well-formed
#1 [check_mod_type_wf] checking that types are well-formed in top-level module
#2 [analysis] running analysis passes on this crate
end of query stack
error: aborting due to 6 previous errors

Some errors have detailed explanations: E0107, E0412, E0425, E0601, E0658.
For more information about an error, try `rustc --explain E0107`.

```

</p>
</details>

### PR DESCRIPTION
**Pull request by BoxyUwU**
Split out of #137972, the parts necessary for associated const equality and min generic const args to make progress and have correct semantics around when CTFE is invoked. According to a [previous perf run](https://perf.rust-lang.org/compare.html?start=93257e2d20809d82d1bc0fcc1942480d1a66d7cd&end=01b4cbf0f47c3f782330db88fa5ba199bba1f8a2&stat=instructions:u) of adding the new `const_arg_kind` query we should expect minor regressions here. 

I think this is acceptable as we should be able to remove this query relatively soon once mgca is more complete as we'll then be able to implement GCE in terms of mgca and rip out `GCEConst` at which point it's trivial to determine what kind of anon const we're dealing with (either it has generics and is a repeat expr hack, or it doesnt and is a normal anon const).

This should only affect unstable code as we handle repeat exprs specially and those are the only kinds of type system consts that are allowed to make use of generic parameters.

Fixes #133066
Fixes #133199
Fixes #136894
Fixes #137813

r? compiler-errors

### CODE REVIEW

File: compiler/rustc_middle/src/ty/consts.rs [hunk 1]
```diff
@@ -259,3 +259,11 @@ impl<'tcx> Const<'tcx> {
         TypeWalker::new(self.into())
     }
 }
+
+#[derive(Copy, Clone, PartialEq, Eq, Hash, Debug, TyEncodable, TyDecodable, HashStable)]
+pub enum AnonConstKind {
```
Comment (compiler-errors) [inline compiler/rustc_middle/src/ty/consts.rs:264]: Brief comment about how each one of these modes affect semantics?

File: compiler/rustc_middle/src/ty/consts.rs [hunk 2]
```diff
@@ -259,3 +259,11 @@ impl<'tcx> Const<'tcx> {
...
+    GCEConst,
```
Comment (compiler-errors) [inline compiler/rustc_middle/src/ty/consts.rs:265]: nit: I feel like `*Const` prefix is redundant

File: compiler/rustc_trait_selection/src/traits/mod.rs [hunk 3]
```diff
@@ -545,73 +545,100 @@ pub fn try_evaluate_const<'tcx>(
...
-                        (args, typing_env)
-                    }
+                } else {
+                    let typing_env = infcx
+                        .typing_env(tcx.erase_regions(param_env))
+                        .with_post_analysis_normalized(tcx);
+                    (uv.args, typing_env)
+                }
+            } else if tcx.def_kind(uv.def) == DefKind::AnonConst
+                && let ty::AnonConstKind::RepeatExprCount = tcx.anon_const_kind(uv.def)
```
[the remark this answers is not in the document]
Comment (BoxyUwU) [reply compiler/rustc_trait_selection/src/traits/mod.rs:598]: ur true :3 can just split this out into a `Option<AnonConstKind>` local

File: compiler/rustc_middle/src/query/mod.rs [hunk 4]
```diff
@@ -2576,6 +2576,12 @@ rustc_queries! {
         desc { "estimating codegen size of `{}`", key }
         cache_on_disk_if { true }
     }
+
+    query anon_const_kind(def_id: DefId) -> ty::AnonConstKind {
+        desc { |tcx| "looking up anon const kind of `{}`", tcx.def_path_str(def_id) }
+        cache_on_disk_if { def_id.is_local() }
```
Comment (compiler-errors) [inline compiler/rustc_middle/src/query/mod.rs:2582]: typically we don't cache on disk unless perf suggests that it's necessary -- esp b/c the query impl looks pretty cheap. Can you remove it, and we'll perf it if it's necessary?

File: compiler/rustc_trait_selection/src/traits/mod.rs (hunk 3 above)
[the remark this answers is not in the document]
Comment (compiler-errors) [reply compiler/rustc_trait_selection/src/traits/mod.rs:598]: either that or merge both elses into a singular `if def_kind == anon_const {}`?

File: compiler/rustc_middle/src/query/mod.rs (hunk 4 above)
Comment (BoxyUwU) [reply compiler/rustc_middle/src/query/mod.rs:2582]: Oh do you not need to do this to get it to work in cross-crate situations? No reason to have it then you're right

Comment (compiler-errors) [reply compiler/rustc_middle/src/query/mod.rs:2582]: No, `cache_on_disk` is just for caching the results of the query for perf.

File: compiler/rustc_trait_selection/src/traits/mod.rs (hunk 3 above)
[the remark this answers is not in the document]
Comment (BoxyUwU) [reply compiler/rustc_trait_selection/src/traits/mod.rs]: Turned it into one big match, not quite what you said but I think this is also good. lmk what u think

**Review by compiler-errors — APPROVED** [review]
:>

**Comment by compiler-errors** [comment]
cool

@bors r+ rollup=never

**Comment by BoxyUwU** [comment]
@bors r- :<
I just remembered that we smuggle const patterns into `ty::Const` so I don't think:
> This should only affect unstable code as we handle repeat exprs specially and those are the only kinds of type system consts that are allowed to make use of generic parameters.

is true

**Comment by BoxyUwU** [comment]
```rust
        // try to resolve e.g. associated constants to their definition on an impl, and then
        // evaluate the const.
        let valtree = match self.tcx.const_eval_resolve_for_typeck(typing_env, uv, self.span) {
```

We don't invoke type system norm on these constants though we just directly call into const eval resolve so this is fine

**Comment by BoxyUwU** [comment]
I think `tests/ui/const-generics/const_eval_unchecked_doesnt_fire_patterns.rs` would fail if we *did* go through type system norm instead of manually calling into ctfe so I don't need to add a test here :thinking: Though honestly it's surprising that we don't have a test that solely exists to demonstrate this corner case of patterns... so I guess I'll add one

**Comment by BoxyUwU** [comment]
Added a test anyway because it seems nice to have one *specifically* for this case instead of only having a test that happens to fail but was meant for something else. @rustbot ready

**Comment by Kobzol** [comment]
The binary size regressions correspond to [metadata getting larger](https://perf.rust-lang.org/compare.html?start=e7f4317ea0e891296163414c6f681ccec976abc3&end=52bf0cf795dfecc8b929ebb1c1e2545c3f41d4c9&stat=size%3Acrate_metadata).

**Comment by compiler-errors** [comment]
Yeah, this is a consequence of encoding a new query into metadata. I believe that this perf regression is okay.

**Comment by SuperSamus** [comment]
This causes a build regression for the alpha version of [fixed](https://docs.rs/fixed/2.0.0-alpha.28.0/fixed/index.html).
```
error[E0308]: mismatched types
    --> /home/user/.local/share/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/fixed-2.0.0-alpha.28.0/src/traits.rs:4143:13
     |
4133 | / macro_rules! trait_delegate {
4134 | |     (fn $method:ident($($param:ident: $Param:ty),*$(,)?) -> $Ret:ty) => {
4135 | |         #[inline]
4136 | |         fn $method($($param: $Param),*) -> $Ret {
...    |
4143 | |             self.$method($($param),*)
     | |             ^^^^^^^^^^^^^^^^^^^^^^^^^ expected `size_of::<Self>()`, found `4`
...    |
4190 | |     };
4191 | | }
     | |_- in this expansion of `trait_delegate!` (#2)
4192 |
4193 | / macro_rules! impl_fixed {
4194 | |     (
4195 | |         $Fixed:ident, $IFixed:ident, $UFixed:ident, $nbits:expr, $Bits:ident, $NonZeroBits:ident,
4196 | |         $Signedness:tt
...    |
4235 | |             trait_delegate! { fn to_le_bytes(self) -> [u8; size_of::<Self>()] }
     | |             ------------------------------------------------------------------- in this macro invocation (#2)
...    |
4786 | |     };
4787 | | }
     | |_- in this expansion of `impl_fixed!` (#1)
...
4791 |   impl_fixed! { FixedI32, FixedI32, FixedU32, 32, i32, NonZeroI32, Signed }
     |   ------------------------------------------------------------------------- in this macro invocation (#1)
     |
     = note: expected constant `size_of::<Self>()`
                found constant `4`
```
The same error is repeated for all the other `impl_fixed!`.

(Bisected with `cargo bisect-rustc`.)
