### PR TITLE
fix(resolve): update shadowed_glob more precision

### LINKED ISSUE #109153: ICE `inconsistent resolution for an import`
### Code

```Rust
use foo::*;

mod foo {
    pub mod bar {
        pub mod bar {
            pub mod bar {}
        }
    }
}

use bar::bar;
use bar::*;
```

### Meta

`rustc --version --verbose`:
```
rustc 1.70.0-nightly (22f247c6f 2023-03-13)
binary: rustc
commit-hash: 22f247c6f3ed388cb702d01c2ff27da658a8b353
commit-date: 2023-03-13
host: x86_64-unknown-linux-gnu
release: 1.70.0-nightly
LLVM version: 15.0.7
```

### Error output

```
<output>
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
thread 'rustc' panicked at 'compiler/rustc_resolve/src/imports.rs:704:25: inconsistent resolution for an import', /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/compiler/rustc_middle/src/util/bug.rs:36:26
stack backtrace:
   0:     0x7f57eb2c259a - std::backtrace_rs::backtrace::libunwind::trace::h595f06c70adcc478
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x7f57eb2c259a - std::backtrace_rs::backtrace::trace_unsynchronized::h177a0149c76cdde9
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7f57eb2c259a - std::sys_common::backtrace::_print_fmt::hc0701fd2c3530c58
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/sys_common/backtrace.rs:65:5
   3:     0x7f57eb2c259a - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hd4cd115d8750fd6c
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x7f57eb32439e - core::fmt::write::h93e2f5923c7eca08
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/core/src/fmt/mod.rs:1213:17
   5:     0x7f57eb2b2be5 - std::io::Write::write_fmt::h8162dbb45f0b9e62
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/io/mod.rs:1682:15
   6:     0x7f57eb2c2365 - std::sys_common::backtrace::_print::h1835ef8a8f9066da
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/sys_common/backtrace.rs:47:5
   7:     0x7f57eb2c2365 - std::sys_common::backtrace::print::hcb5e6388b9235f41
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/sys_common/backtrace.rs:34:9
   8:     0x7f57eb2c512f - std::panicking::default_hook::{{closure}}::h9c084969ccf9a722
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/panicking.rs:267:22
   9:     0x7f57eb2c4e6b - std::panicking::default_hook::h68fa2ba3c3c6c12f
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/panicking.rs:286:9
  10:     0x7f57ea0b56e4 - <rustc_driver[f4ad927b3c57833d]::DEFAULT_HOOK::{closure#0}::{closure#0} as core[d16e85342ea223d9]::ops::function::FnOnce<(&core[d16e85342ea223d9]::panic::panic_info::PanicInfo,)>>::call_once::{shim:vtable#0}
  11:     0x7f57eb2c596a - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h4e6ced11e07d8b24
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/alloc/src/boxed.rs:2002:9
  12:     0x7f57eb2c596a - std::panicking::rust_panic_with_hook::h8d5c434518ef298c
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/panicking.rs:692:13
  13:     0x7f57eaaf07f2 - std[3da461b304582a2c]::panicking::begin_panic::<alloc[5b05b59796bdfb5c]::string::String>::{closure#0}
  14:     0x7f57eaaf032a - std[3da461b304582a2c]::sys_common::backtrace::__rust_end_short_backtrace::<std[3da461b304582a2c]::panicking::begin_panic<alloc[5b05b59796bdfb5c]::string::String>::{closure#0}, !>
  15:     0x7f57eaab8351 - std[3da461b304582a2c]::panicking::begin_panic::<alloc[5b05b59796bdfb5c]::string::String>
  16:     0x7f57eaa9f85d - rustc_middle[eb7209f5870e9fb7]::util::bug::opt_span_bug_fmt::<rustc_span[4bb3e3ecb57f95d5]::span_encoding::Span>::{closure#0}
  17:     0x7f57eaa9f8da - rustc_middle[eb7209f5870e9fb7]::ty::context::tls::with_opt::<rustc_middle[eb7209f5870e9fb7]::util::bug::opt_span_bug_fmt<rustc_span[4bb3e3ecb57f95d5]::span_encoding::Span>::{closure#0}, !>::{closure#0}
  18:     0x7f57eaa9f0c6 - rustc_middle[eb7209f5870e9fb7]::ty::context::tls::with_context_opt::<rustc_middle[eb7209f5870e9fb7]::ty::context::tls::with_opt<rustc_middle[eb7209f5870e9fb7]::util::bug::opt_span_bug_fmt<rustc_span[4bb3e3ecb57f95d5]::span_encoding::Span>::{closure#0}, !>::{closure#0}, !>
  19:     0x7f57eaa9f086 - rustc_middle[eb7209f5870e9fb7]::util::bug::opt_span_bug_fmt::<rustc_span[4bb3e3ecb57f95d5]::span_encoding::Span>
  20:     0x7f57eaa9f044 - rustc_middle[eb7209f5870e9fb7]::util::bug::span_bug_fmt::<rustc_span[4bb3e3ecb57f95d5]::span_encoding::Span>
  21:     0x7f57e92fbd37 - <rustc_resolve[b9ffdbb06ddc059e]::imports::ImportResolver>::finalize_import
  22:     0x7f57e92f9bfd - <rustc_resolve[b9ffdbb06ddc059e]::imports::ImportResolver>::finalize_imports
  23:     0x7f57e92a2132 - <rustc_session[b580c712976fc965]::session::Session>::time::<(), <rustc_resolve[b9ffdbb06ddc059e]::Resolver>::resolve_crate::{closure#0}>
  24:     0x7f57e92a05b1 - rustc_interface[3781616314f5d936]::passes::configure_and_expand
  25:     0x7f57e929fac6 - <rustc_interface[3781616314f5d936]::queries::Queries>::expansion
  26:     0x7f57e929a719 - <rustc_interface[3781616314f5d936]::queries::Queries>::global_ctxt
  27:     0x7f57e929320d - rustc_span[4bb3e3ecb57f95d5]::with_source_map::<core[d16e85342ea223d9]::result::Result<(), rustc_errors[41d09747e2f98dea]::ErrorGuaranteed>, rustc_interface[3781616314f5d936]::interface::run_compiler<core[d16e85342ea223d9]::result::Result<(), rustc_errors[41d09747e2f98dea]::ErrorGuaranteed>, rustc_driver[f4ad927b3c57833d]::run_compiler::{closure#1}>::{closure#0}::{closure#0}>
  28:     0x7f57e928bce4 - <scoped_tls[1a6b834cb64348ef]::ScopedKey<rustc_span[4bb3e3ecb57f95d5]::SessionGlobals>>::set::<rustc_interface[3781616314f5d936]::interface::run_compiler<core[d16e85342ea223d9]::result::Result<(), rustc_errors[41d09747e2f98dea]::ErrorGuaranteed>, rustc_driver[f4ad927b3c57833d]::run_compiler::{closure#1}>::{closure#0}, core[d16e85342ea223d9]::result::Result<(), rustc_errors[41d09747e2f98dea]::ErrorGuaranteed>>
  29:     0x7f57e928b3e2 - std[3da461b304582a2c]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[3781616314f5d936]::util::run_in_thread_pool_with_globals<rustc_interface[3781616314f5d936]::interface::run_compiler<core[d16e85342ea223d9]::result::Result<(), rustc_errors[41d09747e2f98dea]::ErrorGuaranteed>, rustc_driver[f4ad927b3c57833d]::run_compiler::{closure#1}>::{closure#0}, core[d16e85342ea223d9]::result::Result<(), rustc_errors[41d09747e2f98dea]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[d16e85342ea223d9]::result::Result<(), rustc_errors[41d09747e2f98dea]::ErrorGuaranteed>>
  30:     0x7f57e928b18a - <<std[3da461b304582a2c]::thread::Builder>::spawn_unchecked_<rustc_interface[3781616314f5d936]::util::run_in_thread_pool_with_globals<rustc_interface[3781616314f5d936]::interface::run_compiler<core[d16e85342ea223d9]::result::Result<(), rustc_errors[41d09747e2f98dea]::ErrorGuaranteed>, rustc_driver[f4ad927b3c57833d]::run_compiler::{closure#1}>::{closure#0}, core[d16e85342ea223d9]::result::Result<(), rustc_errors[41d09747e2f98dea]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[d16e85342ea223d9]::result::Result<(), rustc_errors[41d09747e2f98dea]::ErrorGuaranteed>>::{closure#1} as core[d16e85342ea223d9]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  31:     0x7f57eb2cf823 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h1c0f3664d7ced314
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/alloc/src/boxed.rs:1988:9
  32:     0x7f57eb2cf823 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h67647c21c6c4968a
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/alloc/src/boxed.rs:1988:9
  33:     0x7f57eb2cf823 - std::sys::unix::thread::Thread::new::thread_start::h355d348ba593a22c
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/sys/unix/thread.rs:108:17
  34:     0x7f57e6c67bb5 - <unknown>
  35:     0x7f57e6ce9d90 - <unknown>
  36:                0x0 - <unknown>

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.68.0 (2c8cc3432 2023-03-06) running on x86_64-unknown-linux-gnu

query stack during panic:
end of query stack
```

</p>
</details>

### LINKED ISSUE #109962: ICE: `assertion failed: import.imported_module.get().is_none()'`
Perhaps similar to #109153, but with a different error stack

### Code

```Rust
mod foo {
    pub mod bar {
        pub mod bar {
            pub mod bar {
              pub mod bar {}
            }
        }
    }
}
use foo::*;
use bar::bar::bar;
use bar::*;

fn main() {}
```

### Meta

`rustc --version --verbose`:
```
rustc 1.70.0-nightly (db0cbc48d 2023-03-26)
binary: rustc
commit-hash: db0cbc48d4aaa300713a95d9b317a365a474490c
commit-date: 2023-03-26
host: aarch64-apple-darwin
release: 1.70.0-nightly
LLVM version: 16.0.0
```

### Error output

```
<output>
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
thread 'rustc' panicked at 'assertion failed: import.imported_module.get().is_none()', compiler/rustc_resolve/src/imports.rs:760:21
stack backtrace:
   0:        0x102b5161c - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hfbd99529d8ecd76d
   1:        0x102ba4744 - core::fmt::write::h9d97190441ee1d43
   2:        0x102b46fd4 - std::io::Write::write_fmt::h8e549a8786c022b9
   3:        0x102b51430 - std::sys_common::backtrace::print::hcdd2ae2f7b4f384b
   4:        0x102b53e44 - std::panicking::default_hook::{{closure}}::h2a46a28a68dc3d98
   5:        0x102b53c04 - std::panicking::default_hook::h9a2d7764b010ec79
   6:        0x10afb37f8 - rustc_driver_impl[36f9eacf6ed4a456]::DEFAULT_HOOK::{closure#0}::{closure#0}
   7:        0x102b54504 - std::panicking::rust_panic_with_hook::h65330bb1b8d3241c
   8:        0x102b542bc - std::panicking::begin_panic_handler::{{closure}}::h343dfc740ec0e358
   9:        0x102b51a3c - std::sys_common::backtrace::__rust_end_short_backtrace::hc5295e27637ab888
  10:        0x102b54090 - _rust_begin_unwind
  11:        0x102bd0160 - core::panicking::panic_fmt::h2fc7f604365b2fbe
  12:        0x102bd01d0 - core::panicking::panic::hf25fee583223a2d0
  13:        0x10d9dbdc4 - <rustc_resolve[ee31f98a99a62d61]::Resolver>::finalize_import
  14:        0x10d9d70c4 - <rustc_resolve[ee31f98a99a62d61]::Resolver>::finalize_imports
  15:        0x10d9b105c - <rustc_session[8cde9655f3fdf5d4]::session::Session>::time::<(), <rustc_resolve[ee31f98a99a62d61]::Resolver>::resolve_crate::{closure#0}>
  16:        0x10d9e8b74 - <rustc_resolve[ee31f98a99a62d61]::Resolver>::resolve_crate
  17:        0x10b05b36c - rustc_interface[3d0cf88b79335b1d]::passes::resolver_for_lowering
  18:        0x10e1b5bf0 - <rustc_middle[3a76e9f875a80391]::dep_graph::dep_node::DepKind as rustc_query_system[cda1a4a7f4fba84]::dep_graph::DepKind>::with_deps::<<rustc_query_system[cda1a4a7f4fba84]::dep_graph::graph::DepGraphData<rustc_middle[3a76e9f875a80391]::dep_graph::dep_node::DepKind>>::with_task<(rustc_query_impl[71d65aa877d6c29f]::plumbing::QueryCtxt, rustc_query_impl[71d65aa877d6c29f]::queries::metadata_loader), (), &rustc_data_structures[dc2bd4f2bdfd8c3a]::steal::Steal<alloc[461e12abd46ebdf1]::boxed::Box<dyn rustc_session[8cde9655f3fdf5d4]::cstore::MetadataLoader + core[1e402bd52f9ef0e1]::marker::Sync + core[1e402bd52f9ef0e1]::marker::Send>>>::{closure#0}, &rustc_data_structures[dc2bd4f2bdfd8c3a]::steal::Steal<alloc[461e12abd46ebdf1]::boxed::Box<dyn rustc_session[8cde9655f3fdf5d4]::cstore::MetadataLoader + core[1e402bd52f9ef0e1]::marker::Sync + core[1e402bd52f9ef0e1]::marker::Send>>>
  19:        0x10e0f0d6c - rustc_query_system[cda1a4a7f4fba84]::query::plumbing::try_execute_query::<rustc_query_impl[71d65aa877d6c29f]::queries::resolver_for_lowering, rustc_query_impl[71d65aa877d6c29f]::plumbing::QueryCtxt>
  20:        0x10e224628 - <rustc_query_impl[71d65aa877d6c29f]::Queries as rustc_middle[3a76e9f875a80391]::ty::query::QueryEngine>::resolver_for_lowering
  21:        0x10af3e934 - <rustc_middle[3a76e9f875a80391]::ty::context::GlobalCtxt>::enter::<rustc_driver_impl[36f9eacf6ed4a456]::run_compiler::{closure#1}::{closure#2}::{closure#2}, &rustc_data_structures[dc2bd4f2bdfd8c3a]::steal::Steal<(rustc_middle[3a76e9f875a80391]::ty::ResolverAstLowering, alloc[461e12abd46ebdf1]::rc::Rc<rustc_ast[72ec421f4741fa9e]::ast::Crate>)>>
  22:        0x10af8ffc0 - <rustc_interface[3d0cf88b79335b1d]::interface::Compiler>::enter::<rustc_driver_impl[36f9eacf6ed4a456]::run_compiler::{closure#1}::{closure#2}, core[1e402bd52f9ef0e1]::result::Result<core[1e402bd52f9ef0e1]::option::Option<rustc_interface[3d0cf88b79335b1d]::queries::Linker>, rustc_span[33b8002dac58b04]::ErrorGuaranteed>>
  23:        0x10af4cd30 - rustc_span[33b8002dac58b04]::with_source_map::<core[1e402bd52f9ef0e1]::result::Result<(), rustc_span[33b8002dac58b04]::ErrorGuaranteed>, rustc_interface[3d0cf88b79335b1d]::interface::run_compiler<core[1e402bd52f9ef0e1]::result::Result<(), rustc_span[33b8002dac58b04]::ErrorGuaranteed>, rustc_driver_impl[36f9eacf6ed4a456]::run_compiler::{closure#1}>::{closure#0}::{closure#0}>
  24:        0x10af5aba8 - std[3de1235cb6134dd8]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[3d0cf88b79335b1d]::util::run_in_thread_pool_with_globals<rustc_interface[3d0cf88b79335b1d]::interface::run_compiler<core[1e402bd52f9ef0e1]::result::Result<(), rustc_span[33b8002dac58b04]::ErrorGuaranteed>, rustc_driver_impl[36f9eacf6ed4a456]::run_compiler::{closure#1}>::{closure#0}, core[1e402bd52f9ef0e1]::result::Result<(), rustc_span[33b8002dac58b04]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[1e402bd52f9ef0e1]::result::Result<(), rustc_span[33b8002dac58b04]::ErrorGuaranteed>>
  25:        0x10af52eec - <<std[3de1235cb6134dd8]::thread::Builder>::spawn_unchecked_<rustc_interface[3d0cf88b79335b1d]::util::run_in_thread_pool_with_globals<rustc_interface[3d0cf88b79335b1d]::interface::run_compiler<core[1e402bd52f9ef0e1]::result::Result<(), rustc_span[33b8002dac58b04]::ErrorGuaranteed>, rustc_driver_impl[36f9eacf6ed4a456]::run_compiler::{closure#1}>::{closure#0}, core[1e402bd52f9ef0e1]::result::Result<(), rustc_span[33b8002dac58b04]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[1e402bd52f9ef0e1]::result::Result<(), rustc_span[33b8002dac58b04]::ErrorGuaranteed>>::{closure#1} as core[1e402bd52f9ef0e1]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  26:        0x102b5cbb4 - std::sys::unix::thread::Thread::new::thread_start::h74bccdd3846674d0
  27:        0x19757a06c - __pthread_deallocate

error: the compiler unexpectedly panicked. this is a bug.
```

</p>
</details>

### PR DESCRIPTION
**Pull request by bvanjoi**
- Fixes #109153
- Fixes #109962

## Why does it panic?

We use #109153 as an illustration. 

The process of `resolve_imports` is:

| Iter | resolve     | resolution of **`(Mod(root), Ident(bar) in type ns)`** | 
| -    | -           | -      |
| 0 | `use foo::*`   | `binding` -> foo::bar, `shallowed_glob` -> `None` |
| 1 | `use bar::bar` | `binding` -> foo::bar::bar, `shallowed_glob` -> foo::bar    |
| 2 | `use bar::*`   | `binding` -> foo::bar::bar, `shallowed_glob` -> foo::bar::bar::bar |

So during `finalize_import`, the `root::bar` in `use bar::bar` had been pointed to `foo::bar::bar::bar`, which is different from the `initial_module` valued of `foo::bar`, therefore, the panic had been triggered.

## Try to solve it

~I think #109153 should check-pass rather than throw an ambiguous error. Following this idea, there are two ways to solve this problem:~

~1. Give up the `initial_module` and update `import.imported_module` after each resolution update. However, I think this method may have too much impact.~
~2. Do not update the `shadowed_glob` when it is defined.~

~To be honest, I am not sure if this is the right way to solve this ICE. Perhaps there is a better resolution.~

Edit: we had made the `resolution.shadowed_glob` update more detailed.

r? @petrochenkov

### CODE REVIEW

File: tests/ui/resolve/issue-109153.rs [hunk 1]
```diff
@@ -0,0 +1,16 @@
+// check-pass
```
Comment (bvanjoi) [inline tests/ui/resolve/issue-109153.rs:1]: Is it necessary to add some runtime check?

File: compiler/rustc_resolve/src/imports.rs [hunk 2]
```diff
@@ -338,7 +338,15 @@ impl<'a, 'tcx> Resolver<'a, 'tcx> {
...
-                        resolution.shadowed_glob = Some(glob_binding);
+
+                        if key.ns == TypeNS
+                            && resolution
+                                .shadowed_glob
+                                .map_or(false, |old| old.res() != glob_binding.res())
+                        {
+                        } else {
+                            resolution.shadowed_glob = Some(glob_binding);
+                        }
```
Comment (petrochenkov) [inline compiler/rustc_resolve/src/imports.rs:349]: I think it would be sufficient to not set shadowed glob if it was already set previously?
```rust
if resolution.shadowed_glob.is_none() { resolution.shadowed_glob = Some(glob_binding); }
```

File: tests/ui/resolve/issue-109153.rs (hunk 1 above)
Comment (petrochenkov) [reply tests/ui/resolve/issue-109153.rs:1]: No

File: compiler/rustc_resolve/src/imports.rs (hunk 2 above)
Comment (petrochenkov) [reply compiler/rustc_resolve/src/imports.rs:349]: What would be even more correct is to treat to competing shadowed globs as two competing regular globs, and do this thing
```rust
                match (old_binding.is_glob_import(), binding.is_glob_import()) {
                    (true, true) => {
                        if res != old_binding.res() {
                            resolution.binding = Some(this.ambiguity(
                                AmbiguityKind::GlobVsGlob,
                                old_binding,
                                binding,
                            ));
                        } else if !old_binding.vis.is_at_least(binding.vis, this.tcx) {
                            // We are glob-importing the same item but with greater visibility.
                            resolution.binding = Some(binding);
                        }
                    }
```
but with `resolution.shadowed_glob` instead of `resolution.binding`.

Comment (petrochenkov) [reply compiler/rustc_resolve/src/imports.rs:349]: It would be compatible with the proper solution

https://github.com/rust-lang/rust/blob/master/compiler/rustc_resolve/src/ident.rs#L874-L876

which requires a larger refactoring.

File: tests/ui/resolve/issue-109962.rs [hunk 3]
```diff
@@ -0,0 +1,17 @@
...
+        pub mod bar {
+            pub mod bar {
+              pub mod bar {}
+            }
+        }
+    }
+}
+
+use foo::*;
+use bar::bar::bar;
```
Comment (bvanjoi) [inline tests/ui/resolve/issue-109962.rs:14]: I will delete this case due to duplicate.

File: tests/ui/resolve/issue-105069.rs [hunk 4]
```diff
@@ -1,5 +1,7 @@
+// check-pass
+
 use self::A::*;
-use V; //~ ERROR `V` is ambiguous
+use V;
```
Comment (bvanjoi) [inline tests/ui/resolve/issue-105069.rs:4]: It is point to ﻿`A::V`, I am concerned that it undermines the principle that order is irrelevant

**Comment by bvanjoi** [comment]
All checks had passed, so @rustbot ready

File: compiler/rustc_resolve/src/imports.rs [hunk 5]
```diff
@@ -348,6 +347,21 @@ impl<'a, 'tcx> Resolver<'a, 'tcx> {
                 resolution.binding = Some(binding);
             }
 
+            if let Some(old_binding) = resolution.shadowed_glob && binding.is_glob_import() {
+                assert!(old_binding.is_glob_import());
+                if res != old_binding.res() && key.ns != TypeNS {
```
Comment (bvanjoi) [inline compiler/rustc_resolve/src/imports.rs:352]: Removing ﻿`key.nx != TypeNS` will cause #109153 to throw an ambiguity error. I am not sure whether it is better to let the check pass or to throw an error.

Comment (petrochenkov) [reply compiler/rustc_resolve/src/imports.rs:352]: >Removing ﻿`key.nx != TypeNS` will cause #109153 to throw an ambiguity error.

That seems entirely fine to me.

Comment (petrochenkov) [reply compiler/rustc_resolve/src/imports.rs]: Although I don't understand why `shadowed_glob` assignment was moved from the place it previously was to here.

File: tests/ui/resolve/issue-105069.stderr [hunk 6]
```diff
@@ -4,17 +4,19 @@ error[E0659]: `V` is ambiguous
 LL | use V;
    |     ^ ambiguous name
    |
-   = note: ambiguous because of multiple potential import sources
-note: `V` could refer to the variant imported here
+   = note: ambiguous because of multiple glob imports of a name in the same module
```
Comment (petrochenkov) [inline tests/ui/resolve/issue-105069.stderr:7]: Looks like you just fixed this FIXME - https://github.com/rust-lang/rust/pull/112086/files#diff-54ebaa0715c94a2acf974077e838aa584186e187f3d01edb1791fd71c78408caR937-R939 and we can now remove `AmbiguityKind::Import` in https://github.com/rust-lang/rust/pull/112086.

File: compiler/rustc_resolve/src/imports.rs (hunk 5 above)
Comment (bvanjoi) [reply compiler/rustc_resolve/src/imports.rs]: > Although I don't understand why shadowed_glob assignment was moved from the place it previously was to here.

The issue seems to be simply a difference in code style? There should be no difference in logic between the two

Comment (bvanjoi) [reply compiler/rustc_resolve/src/imports.rs]: It does lead to useless code execution on both sides and I will put it back
