### PR TITLE
rustdoc options to set default theme (and other settings)

### LINKED ISSUE #77024: rustdoc: Please provide way to set the default theme
When I view rustdoc-generated documents via file:// urls on my own system, the (I think cookie-based) mechanism for saving my doc theme preference does not work.

Can we please have a command-line option or config file setting or something, to change the default theme?  (I guess it might be possible to do this with `--extend-css` but that seems complicated and probably fragile too.)

I imagine implementing this would not be too hard even for someone unfamiliar with the rustdoc code, so I would be happy to do an MR if you like.  I guess the right way would be a `--default-theme` command line option?

### PR DESCRIPTION
**Pull request by ijackson**
Hi.  This is the MR I promised in #77024 

It is a little more general than I envisaged there.  Once I had found the settings-handling machinery it seemed foolish to add this feature just for the theme.

Closes #77024

### CODE REVIEW

**Comment by jyn514** [comment]
ping @GuillaumeGomez

File: src/librustdoc/html/layout.rs [hunk 1]
```diff
@@ -53,6 +55,7 @@ pub fn render<T: Print, S: Print>(
     <link rel=\"stylesheet\" type=\"text/css\" href=\"{static_root_path}rustdoc{suffix}.css\" \
           id=\"mainThemeStyle\">\
     {style_files}\
+    <script id=\"default-settings\"{default_settings}></script>\
```
Comment (GuillaumeGomez) [inline src/librustdoc/html/layout.rs:58]: As a side-note: this ID should be added to the list of IDs that can't be used in the HTML code (look for any other ID, look for `mainThemeStyle` and you should find where you have to add it).

**Comment by GuillaumeGomez** [comment]
You added the `getSettingValue` and replaced a few setting getters, but could you replace all of them please?

**Comment by ijackson** [comment]
Hi.  Thanks for the review.  I have made those changes.  I rebased onto current master, and then made the requested changes as new commits, for ease of your review (and as requested by the highfive bot).  I did them as git autosquash, and when you're happy with the series, will squash it down.

**Comment by ijackson** [comment]
> You added the `getSettingValue` and replaced a few setting getters, but could you replace all of them please?

As requested, I did this.  Unfortunately it didn't get a review before some other changes went in which conflicted.  By its nature, the change to use `getSettingValue` everywhere is very textually intrusive and likely to break.  If I rebase and fix the merge conflicts, will I get a prompt review?

(FTR obviously I approve of #77809 and it should work well in combination with my work in this MR.)

**Comment by jyn514** [comment]
@ijackson is this PR still needed after https://github.com/rust-lang/rust/pull/77809 ? It seems like https://github.com/rust-lang/rust/issues/77024 should be fixed by setting your system theme to the default that you want.

**Comment by ijackson** [comment]
Joshua Nelson writes ("Re: [rust-lang/rust] rustdoc options to set default theme (and other settings) (#77213)"):
> @ijackson is this PR still needed after #77809 ? It seems like #77024 should be
> fixed by setting your system theme to the default that you want.

No, I'm think this is still wanted.  Honouring prefers-color-scheme is
good but:

 * It is not available except on fairly recent browsers
   (caniuse.com says eary-to-mid 2019).

 * It is suppressed by "privacy.resistFingerprinting" [1]

 * It does not address the use case of a shared site-wide default, for
   the person running rustdoc to generate docs for their community.

 * My series allows setting other preferences too which might well be
   useful.

So I intend to rebase this, assuming that it is likely to be accepted.

Thanks,
Ian.

[1] https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme

-- 
Ian Jackson <ijackson@chiark.greenend.org.uk>   These opinions are my own.  

Pronouns: they/he.  If I emailed you from @fyvzl.net or @evade.org.uk,
that is a private address which bypasses my fierce spamfilter.

**Comment by GuillaumeGomez** [comment]
Please rebase to fix merge conflicts then ping me and I'll review again (but it seems mostly good already).

**Comment by ijackson** [comment]
@GuillaumeGomez

> Please rebase to fix merge conflicts then ping me and I'll review again (but it seems mostly good already).

Now done, thanks.  I made some slight improvements to the Rust parts so you may want to re-review them.

File: src/librustdoc/html/layout.rs [hunk 2]
```diff
@@ -172,6 +175,11 @@ pub fn render<T: Print, S: Print>(
         after_content = layout.external_html.after_content,
         sidebar = Buffer::html().to_display(sidebar),
         krate = layout.krate,
+        default_settings = layout
+            .default_settings
+            .iter()
+            .map(|(k, v)| format!(r#" data-{}="{}""#, k.replace('-', "_"), Escape(v),))
```
Comment (GuillaumeGomez) [inline src/librustdoc/html/layout.rs:181]: Small nit: I think that the extra comma at the end is unnecessary. ;)

File: src/librustdoc/lib.rs [hunk 3]
```diff
@@ -269,6 +269,26 @@ fn opts() -> Vec<RustcOptGroup> {
                 "sort modules by where they appear in the program, rather than alphabetically",
             )
         }),
+        unstable("default-theme", |o| {
+            o.optopt(
+                "",
+                "default-theme",
+                "Set the default theme.  THEME should be the theme name, generally lowercase. \
```
Comment (GuillaumeGomez) [inline src/librustdoc/lib.rs:276]: The usage of the double whitespace is bugging me a lot. Is there a reason behind it?

**Comment by GuillaumeGomez** [comment]
Just nits on my end. Maybe you want to take a last look @jyn514 too?

**Comment by ijackson** [comment]
Hi, thanks for the prompt review.

> +            .map(|(k, v)| format!(r#" data-{}="{}""#, k.replace('-', "_"), Escape(v),))
> 
> Small nit: I think that the extra comma at the end is unnecessary. ;)

I think that used to be before a newline but rustfmt deleted the
newline.  I'll get rid of the comma...

> +                "Set the default theme.  THEME should be the theme name, generally lowercase. \
> 
> The usage of the double whitespace is bugging me a lot. Is there a reason
> behind it?

That's what I was taught in school on a manual typewriter :-).  I am
happy to change it.

Would you like a new commit on top to address these nits, or amendment
and force push ?

Ian.

-- 
Ian Jackson <ijackson@chiark.greenend.org.uk>   These opinions are my own.  

Pronouns: they/he.  If I emailed you from @fyvzl.net or @evade.org.uk,
that is a private address which bypasses my fierce spamfilter.

**Comment by GuillaumeGomez** [comment]
In this case it's fine, you're still under the "rebase bar". :p Just push another commit to fix the nits.

**Comment by ijackson** [comment]
@GuillaumeGomez  Done, thanks.

**Review by GuillaumeGomez — APPROVED** [review]

**Comment by GuillaumeGomez** [comment]
All good for me. Just a last check from @jyn514 and then it's good to go!

File: src/librustdoc/lib.rs [hunk 4]
```diff
@@ -269,6 +269,26 @@ fn opts() -> Vec<RustcOptGroup> {
...
+        unstable("default-theme", |o| {
+            o.optopt(
+                "",
+                "default-theme",
+                "Set the default theme. THEME should be the theme name, generally lowercase. \
+                 If an unknown default theme is specified, the builtin default is used. \
+                 The set of themes, and the rustdoc built-in default is not stable.",
+                "THEME",
+            )
+        }),
```
Comment (jyn514) [inline src/librustdoc/lib.rs:281]: Why is default-theme special cased? If you want `default-settings` to work for arbitrary settings, I think it makes sense to use it for themes too. If you want this to be documented, I would rather document settings in the unstable section of the rustdoc book (`src/doc/rustdoc/src/unstable-features.md`).

Comment (jyn514) [reply src/librustdoc/lib.rs:281]: (I would also be ok with getting rid of `default-settings` and only keeping `default-themes`.)

File: src/librustdoc/config.rs [hunk 5]
```diff
@@ -374,6 +377,31 @@ impl Options {
...
+                .map(|theme| {
+                    vec![
+                        ("use-system-theme".to_string(), "false".to_string()),
+                        ("theme".to_string(), theme.to_string()),
+                    ]
+                })
+                .flatten()
+                .collect(),
+            matches
+                .opt_strs("default-setting")
```
Comment (jyn514) [inline src/librustdoc/config.rs:393]: One more thing that `--default-theme` breaks is you now have different behavior for `--default-theme x` and `--default-setting theme=x` - the first will set `use-system-theme=false`, the second will not.

File: src/librustdoc/config.rs [hunk 6]
```diff
@@ -374,6 +377,31 @@ impl Options {
...
+                .iter()
+                .map(|s| {
+                    let mut kv = s.splitn(2, '=');
+                    let k = kv.next().unwrap().to_string();
```
Comment (jyn514) [inline src/librustdoc/config.rs:397]:
```suggestion
                    // never panics because `splitn` always returns at least one element
                    let k = kv.next().unwrap().to_string();
```

File: src/librustdoc/config.rs [hunk 7]
```diff
@@ -374,6 +377,31 @@ impl Options {
...
+                    let v = kv.next().unwrap_or("true").to_string();
+                    (k, v)
+                })
+                .collect(),
+        ];
+        let default_settings = default_settings.drain(..).flatten().collect();
```
Comment (jyn514) [inline src/librustdoc/config.rs:403]: This allows reusing the allocation. Not sure if the standard library does that currently, but it could.
```suggestion
        let default_settings = default_settings.into_iter().flatten().collect();
```

File: src/librustdoc/lib.rs (hunk 4 above)
Comment (ijackson) [reply src/librustdoc/lib.rs:281]: The storage names are rather internal, and `--default-setting` sets them directly.  That's good for flexibility but it is rather too raw.

Indeed, as you can see from the implementation, `--default-theme` doesn't just set the `theme` setting.  Because of the way the "use system theme" option and the light/dark themes operate, since #77809, it is necessary to change the default for "use system theme" to "false" for the `--default-theme` option to work.

Indeed, I think this fact about #77809 shows that my pre-#77809 approach of having a raw `--default-setting` option, and a cooked `--default-theme` option, was correct.  Before #77809, `--default-theme` just set the `theme` setting.  Now it does more.

Notice that the stability caveats for the two options are rather different.  Another aspect of this is that it might easily make sense to stabilise the `--default-theme` option soon, after we've had some experience with it.  Stabilising the raw `--default-setting` option would involve thinking about what additional promises that would imply (maybe none that we care about? but I'm not sure and it's certainly harder to think about)

File: src/librustdoc/config.rs (hunk 5 above)
Comment (ijackson) [reply src/librustdoc/config.rs:393]: Yes.  That is inevitable and deliberate.  As you can see from the usage message we do not make any promises about the particular behaviour of `--default-setting`.  The available settings and their semantics and not documented and not stable.

Whereas the semantics of `--default-theme` are well-defined, and are implemented by setting the two internal settings.

I do think it is worth keeping `--default-setting` even despite these caveats because in practice the storage settings are visible to users via their browser and of course if they look at the JS.

The difference between `--default-setting` and `--default-theme` is like the difference between firefox's `about:config` and `about:preferences`.

Comment (jyn514) [reply src/librustdoc/config.rs:393]: I guess my question is why you would ever want to modify `default-setting`. All those settings are also configurable on a per-user basis on [`settings.html`](https://doc.rust-lang.org/settings.html) - do we really need so much flexibility as to make the 'default defaults' configurable too?

File: src/librustdoc/config.rs (hunk 7 above)
Comment (ijackson) [reply src/librustdoc/config.rs:404]: Thanks.  Perf isn't really important here of course, at least at this level, because this is the command line option parser, but I have no objection to this change.  This change also means getting rid of the `mut` which is actually nicer.  I will add a commit that does both of these things.

Comment (jyn514) [reply src/librustdoc/config.rs]: Right, the perf is not super important to me but I think `into_iter()` is more clear.

**Comment by ijackson** [comment]
> I guess my question is why you would ever want to modify default-setting. All
> those settings are also configurable on a per-user basis on settings.html - do
> we really need so much flexibility as to make the 'default defaults'
> configurable too?

The reasons I gave for the default theme here:
  https://github.com/rust-lang/rust/issues/77024#issuecomment-697817031

apply to all of these default options too.  The same reasons motivate
many of rustdoc's options, such as `--theme`, `--extend-css`,
`--index-page`, etc. etc. etc.

-- 
Ian Jackson <ijackson@chiark.greenend.org.uk>   These opinions are my own.  

Pronouns: they/he.  If I emailed you from @fyvzl.net or @evade.org.uk,
that is a private address which bypasses my fierce spamfilter.

**Comment by jyn514** [comment]
@bors r=jyn514,GuillaumeGomez

In practice I don't expect `--default-settings` to be used often, but since it's perma-unstable I'm ok with adding it. `--default-theme` definitely seems like a good improvement.

**Comment by ijackson** [comment]
> In practice I don't expect --default-settings to be used often, but
> since it's perma-unstable I'm ok with adding it. --default-theme
> definitely seems like a good improvement.

Thanks.  I will probably propose stabilising --default-theme after
it's had a chance to bed in.  Many of the other options which interact
with details of the CSS are already stable.

Ian.

-- 
Ian Jackson <ijackson@chiark.greenend.org.uk>   These opinions are my own.  

Pronouns: they/he.  If I emailed you from @fyvzl.net or @evade.org.uk,
that is a private address which bypasses my fierce spamfilter.
