### PR TITLE
Remove unused from_method from rustc_on_unimplemented

### LINKED ISSUE #113439: ICE: `item_name: no name for DefPath`  -Zlower-impl-trait-in-trait-to-assoc-ty + rpitit
### Code

```Rust
#![feature(return_position_impl_trait_in_trait)]

trait Foo<T> {
    fn foo<F2>(self) -> impl Foo<T>;
}

struct Bar;

impl Foo<char> for Bar {
    fn foo<F2: Foo<u8>>(self) -> impl Foo<u8> {
        self
    }
}
```

### Meta

`rustc --version --verbose`:
```
rustc 1.72.0-nightly (921f66974 2023-07-07)
binary: rustc
commit-hash: 921f669749a57ab5936721fdd93b2da57b581381
commit-date: 2023-07-07
host: x86_64-unknown-linux-gnu
release: 1.72.0-nightly
LLVM version: 16.0.5
```

### Error output

```

```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
error: internal compiler error: compiler/rustc_middle/src/ty/mod.rs:2319:13: item_name: no name for DefPath { data: [DisambiguatedDefPathData { data: TypeNs("Foo"), disambiguator: 0 }, DisambiguatedDefPathData { data: ImplTraitAssocTy, disambiguator: 0 }], krate: crate0 }

thread 'rustc' panicked at 'Box<dyn Any>', /rustc/921f669749a57ab5936721fdd93b2da57b581381/compiler/rustc_errors/src/lib.rs:1651:9
stack backtrace:
   0:     0x7f66d9763a71 - std::backtrace_rs::backtrace::libunwind::trace::hb05aa6cc8cc12798
                               at /rustc/921f669749a57ab5936721fdd93b2da57b581381/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x7f66d9763a71 - std::backtrace_rs::backtrace::trace_unsynchronized::h4eb176a26cc1ba04
                               at /rustc/921f669749a57ab5936721fdd93b2da57b581381/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7f66d9763a71 - std::sys_common::backtrace::_print_fmt::h1f61568d68579c4a
                               at /rustc/921f669749a57ab5936721fdd93b2da57b581381/library/std/src/sys_common/backtrace.rs:65:5
   3:     0x7f66d9763a71 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h57dacdd98f67e152
                               at /rustc/921f669749a57ab5936721fdd93b2da57b581381/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x7f66d97c9d7f - core::fmt::rt::Argument::fmt::hc9125659956a317d
                               at /rustc/921f669749a57ab5936721fdd93b2da57b581381/library/core/src/fmt/rt.rs:138:9
   5:     0x7f66d97c9d7f - core::fmt::write::hacfaa5fb24457741
                               at /rustc/921f669749a57ab5936721fdd93b2da57b581381/library/core/src/fmt/mod.rs:1094:21
   6:     0x7f66d97564b7 - std::io::Write::write_fmt::hbd177ac610ea9ddb
                               at /rustc/921f669749a57ab5936721fdd93b2da57b581381/library/std/src/io/mod.rs:1714:15
   7:     0x7f66d9763885 - std::sys_common::backtrace::_print::h794d92bec131f33b
                               at /rustc/921f669749a57ab5936721fdd93b2da57b581381/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x7f66d9763885 - std::sys_common::backtrace::print::h00747b9c9d53fb7c
                               at /rustc/921f669749a57ab5936721fdd93b2da57b581381/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x7f66d9766663 - std::panicking::default_hook::{{closure}}::h974e1e40cc31ef37
                               at /rustc/921f669749a57ab5936721fdd93b2da57b581381/library/std/src/panicking.rs:269:22
  10:     0x7f66d97663f4 - std::panicking::default_hook::h83eab9cf6bc2c1d4
                               at /rustc/921f669749a57ab5936721fdd93b2da57b581381/library/std/src/panicking.rs:288:9
  11:     0x7f66dca51f3b - rustc_driver_impl[7b385e897129221a]::install_ice_hook::{closure#0}
  12:     0x7f66d9766e8e - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h27c942e87a09f23b
                               at /rustc/921f669749a57ab5936721fdd93b2da57b581381/library/alloc/src/boxed.rs:2007:9
  13:     0x7f66d9766e8e - std::panicking::rust_panic_with_hook::hd06db9c2c751c186
                               at /rustc/921f669749a57ab5936721fdd93b2da57b581381/library/std/src/panicking.rs:709:13
  14:     0x7f66dd0040a1 - std[158e0661572bfb70]::panicking::begin_panic::<rustc_errors[aa05a5e1436cb11f]::ExplicitBug>::{closure#0}
  15:     0x7f66dd002db6 - std[158e0661572bfb70]::sys_common::backtrace::__rust_end_short_backtrace::<std[158e0661572bfb70]::panicking::begin_panic<rustc_errors[aa05a5e1436cb11f]::ExplicitBug>::{closure#0}, !>
  16:     0x7f66dd0024a6 - std[158e0661572bfb70]::panicking::begin_panic::<rustc_errors[aa05a5e1436cb11f]::ExplicitBug>
  17:     0x7f66dd00dc34 - <rustc_errors[aa05a5e1436cb11f]::HandlerInner>::bug::<alloc[b8d7d276236dc4dc]::string::String>
  18:     0x7f66dd00dab6 - <rustc_errors[aa05a5e1436cb11f]::Handler>::bug::<alloc[b8d7d276236dc4dc]::string::String>
  19:     0x7f66dcf4d27c - rustc_middle[c8a9aab83046b80]::util::bug::opt_span_bug_fmt::<rustc_span[8207084c985c29b2]::span_encoding::Span>::{closure#0}
  20:     0x7f66dcf4c98a - rustc_middle[c8a9aab83046b80]::ty::context::tls::with_opt::<rustc_middle[c8a9aab83046b80]::util::bug::opt_span_bug_fmt<rustc_span[8207084c985c29b2]::span_encoding::Span>::{closure#0}, !>::{closure#0}
  21:     0x7f66dcf4c95a - rustc_middle[c8a9aab83046b80]::ty::context::tls::with_context_opt::<rustc_middle[c8a9aab83046b80]::ty::context::tls::with_opt<rustc_middle[c8a9aab83046b80]::util::bug::opt_span_bug_fmt<rustc_span[8207084c985c29b2]::span_encoding::Span>::{closure#0}, !>::{closure#0}, !>
  22:     0x7f66db1f9c4d - rustc_middle[c8a9aab83046b80]::util::bug::bug_fmt
  23:     0x7f66daf1a0c6 - <rustc_middle[c8a9aab83046b80]::ty::context::TyCtxt>::item_name
  24:     0x7f66dd623807 - <rustc_infer[a236ad46b001f5a2]::infer::error_reporting::TypeErrCtxt as rustc_trait_selection[e0d33a1107ca6a49]::traits::error_reporting::on_unimplemented::TypeErrCtxtExt>::on_unimplemented_note
  25:     0x7f66dd63b3e8 - <rustc_infer[a236ad46b001f5a2]::infer::error_reporting::TypeErrCtxt as rustc_trait_selection[e0d33a1107ca6a49]::traits::error_reporting::TypeErrCtxtExt>::report_selection_error
  26:     0x7f66dd646f2f - <rustc_infer[a236ad46b001f5a2]::infer::error_reporting::TypeErrCtxt as rustc_trait_selection[e0d33a1107ca6a49]::traits::error_reporting::InferCtxtPrivExt>::report_fulfillment_error
  27:     0x7f66dd639cc4 - <rustc_infer[a236ad46b001f5a2]::infer::error_reporting::TypeErrCtxt as rustc_trait_selection[e0d33a1107ca6a49]::traits::error_reporting::TypeErrCtxtExt>::report_fulfillment_errors
  28:     0x7f66dcbde6a4 - rustc_hir_analysis[2ce2f0004243268f]::check::compare_impl_item::collect_return_position_impl_trait_in_trait_tys
  29:     0x7f66dd33cc8e - rustc_query_impl[1b840d390aceead0]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[1b840d390aceead0]::query_impl::collect_return_position_impl_trait_in_trait_tys::dynamic_query::{closure#2}::{closure#0}, rustc_middle[c8a9aab83046b80]::query::erase::Erased<[u8; 8usize]>>
  30:     0x7f66dd3c1a11 - <rustc_query_impl[1b840d390aceead0]::query_impl::collect_return_position_impl_trait_in_trait_tys::dynamic_query::{closure#2} as core[61f378b86da375b9]::ops::function::FnOnce<(rustc_middle[c8a9aab83046b80]::ty::context::TyCtxt, rustc_span[8207084c985c29b2]::def_id::DefId)>>::call_once
  31:     0x7f66daa696b5 - rustc_query_system[6dbbf163f57784cb]::query::plumbing::try_execute_query::<rustc_query_impl[1b840d390aceead0]::DynamicConfig<rustc_query_system[6dbbf163f57784cb]::query::caches::DefaultCache<rustc_span[8207084c985c29b2]::def_id::DefId, rustc_middle[c8a9aab83046b80]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[1b840d390aceead0]::plumbing::QueryCtxt, false>
  32:     0x7f66dd3734f7 - rustc_query_impl[1b840d390aceead0]::query_impl::collect_return_position_impl_trait_in_trait_tys::get_query_non_incr::__rust_end_short_backtrace
  33:     0x7f66dad6a1d6 - rustc_middle[c8a9aab83046b80]::query::plumbing::query_get_at::<rustc_query_system[6dbbf163f57784cb]::query::caches::DefaultCache<rustc_span[8207084c985c29b2]::def_id::DefId, rustc_middle[c8a9aab83046b80]::query::erase::Erased<[u8; 8usize]>>>
  34:     0x7f66dbbe5434 - rustc_hir_analysis[2ce2f0004243268f]::collect::type_of::type_of
  35:     0x7f66dac3c5a3 - rustc_query_impl[1b840d390aceead0]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[1b840d390aceead0]::query_impl::type_of::dynamic_query::{closure#2}::{closure#0}, rustc_middle[c8a9aab83046b80]::query::erase::Erased<[u8; 8usize]>>
  36:     0x7f66dac3c560 - <rustc_query_impl[1b840d390aceead0]::query_impl::type_of::dynamic_query::{closure#2} as core[61f378b86da375b9]::ops::function::FnOnce<(rustc_middle[c8a9aab83046b80]::ty::context::TyCtxt, rustc_span[8207084c985c29b2]::def_id::DefId)>>::call_once
  37:     0x7f66daa696b5 - rustc_query_system[6dbbf163f57784cb]::query::plumbing::try_execute_query::<rustc_query_impl[1b840d390aceead0]::DynamicConfig<rustc_query_system[6dbbf163f57784cb]::query::caches::DefaultCache<rustc_span[8207084c985c29b2]::def_id::DefId, rustc_middle[c8a9aab83046b80]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[1b840d390aceead0]::plumbing::QueryCtxt, false>
  38:     0x7f66dc3dcd73 - rustc_query_impl[1b840d390aceead0]::query_impl::type_of::get_query_non_incr::__rust_end_short_backtrace
  39:     0x7f66db863f16 - rustc_middle[c8a9aab83046b80]::query::plumbing::query_get_at::<rustc_query_system[6dbbf163f57784cb]::query::caches::DefaultCache<rustc_span[8207084c985c29b2]::def_id::DefId, rustc_middle[c8a9aab83046b80]::query::erase::Erased<[u8; 8usize]>>>
  40:     0x7f66dbe15668 - <core[61f378b86da375b9]::iter::adapters::map::Map<core[61f378b86da375b9]::iter::adapters::flatten::FlatMap<core[61f378b86da375b9]::slice::iter::Iter<rustc_span[8207084c985c29b2]::def_id::DefId>, alloc[b8d7d276236dc4dc]::vec::Vec<rustc_hir_analysis[2ce2f0004243268f]::constrained_generic_params::Parameter>, rustc_hir_analysis[2ce2f0004243268f]::impl_wf_check::enforce_impl_params_are_constrained::{closure#0}>, <hashbrown[4888579ae6f77242]::set::HashSet<rustc_hir_analysis[2ce2f0004243268f]::constrained_generic_params::Parameter, core[61f378b86da375b9]::hash::BuildHasherDefault<rustc_hash[e089d65e23d2da5f]::FxHasher>> as core[61f378b86da375b9]::iter::traits::collect::Extend<rustc_hir_analysis[2ce2f0004243268f]::constrained_generic_params::Parameter>>::extend<core[61f378b86da375b9]::iter::adapters::flatten::FlatMap<core[61f378b86da375b9]::slice::iter::Iter<rustc_span[8207084c985c29b2]::def_id::DefId>, alloc[b8d7d276236dc4dc]::vec::Vec<rustc_hir_analysis[2ce2f0004243268f]::constrained_generic_params::Parameter>, rustc_hir_analysis[2ce2f0004243268f]::impl_wf_check::enforce_impl_params_are_constrained::{closure#0}>>::{closure#0}> as core[61f378b86da375b9]::iter::traits::iterator::Iterator>::fold::<(), core[61f378b86da375b9]::iter::traits::iterator::Iterator::for_each::call<(rustc_hir_analysis[2ce2f0004243268f]::constrained_generic_params::Parameter, ()), <hashbrown[4888579ae6f77242]::map::HashMap<rustc_hir_analysis[2ce2f0004243268f]::constrained_generic_params::Parameter, (), core[61f378b86da375b9]::hash::BuildHasherDefault<rustc_hash[e089d65e23d2da5f]::FxHasher>> as core[61f378b86da375b9]::iter::traits::collect::Extend<(rustc_hir_analysis[2ce2f0004243268f]::constrained_generic_params::Parameter, ())>>::extend<core[61f378b86da375b9]::iter::adapters::map::Map<core[61f378b86da375b9]::iter::adapters::flatten::FlatMap<core[61f378b86da375b9]::slice::iter::Iter<rustc_span[8207084c985c29b2]::def_id::DefId>, alloc[b8d7d276236dc4dc]::vec::Vec<rustc_hir_analysis[2ce2f0004243268f]::constrained_generic_params::Parameter>, rustc_hir_analysis[2ce2f0004243268f]::impl_wf_check::enforce_impl_params_are_constrained::{closure#0}>, <hashbrown[4888579ae6f77242]::set::HashSet<rustc_hir_analysis[2ce2f0004243268f]::constrained_generic_params::Parameter, core[61f378b86da375b9]::hash::BuildHasherDefault<rustc_hash[e089d65e23d2da5f]::FxHasher>> as core[61f378b86da375b9]::iter::traits::collect::Extend<rustc_hir_analysis[2ce2f0004243268f]::constrained_generic_params::Parameter>>::extend<core[61f378b86da375b9]::iter::adapters::flatten::FlatMap<core[61f378b86da375b9]::slice::iter::Iter<rustc_span[8207084c985c29b2]::def_id::DefId>, alloc[b8d7d276236dc4dc]::vec::Vec<rustc_hir_analysis[2ce2f0004243268f]::constrained_generic_params::Parameter>, rustc_hir_analysis[2ce2f0004243268f]::impl_wf_check::enforce_impl_params_are_constrained::{closure#0}>>::{closure#0}>>::{closure#0}>::{closure#0}>
  41:     0x7f66dbe14008 - rustc_hir_analysis[2ce2f0004243268f]::impl_wf_check::check_mod_impl_wf
  42:     0x7f66db73429c - rustc_query_impl[1b840d390aceead0]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[1b840d390aceead0]::query_impl::check_mod_impl_wf::dynamic_query::{closure#2}::{closure#0}, rustc_middle[c8a9aab83046b80]::query::erase::Erased<[u8; 0usize]>>
  43:     0x7f66db73427e - <rustc_query_impl[1b840d390aceead0]::query_impl::check_mod_impl_wf::dynamic_query::{closure#2} as core[61f378b86da375b9]::ops::function::FnOnce<(rustc_middle[c8a9aab83046b80]::ty::context::TyCtxt, rustc_span[8207084c985c29b2]::def_id::LocalDefId)>>::call_once
  44:     0x7f66db1669af - rustc_query_system[6dbbf163f57784cb]::query::plumbing::try_execute_query::<rustc_query_impl[1b840d390aceead0]::DynamicConfig<rustc_query_system[6dbbf163f57784cb]::query::caches::VecCache<rustc_span[8207084c985c29b2]::def_id::LocalDefId, rustc_middle[c8a9aab83046b80]::query::erase::Erased<[u8; 0usize]>>, false, false, false>, rustc_query_impl[1b840d390aceead0]::plumbing::QueryCtxt, false>
  45:     0x7f66dc3c2674 - rustc_query_impl[1b840d390aceead0]::query_impl::check_mod_impl_wf::get_query_non_incr::__rust_end_short_backtrace
  46:     0x7f66dbead0d7 - <rustc_middle[c8a9aab83046b80]::hir::map::Map>::for_each_module::<rustc_hir_analysis[2ce2f0004243268f]::check_crate::{closure#2}::{closure#0}::{closure#0}>
  47:     0x7f66dbeaccd2 - <rustc_session[6a2016e5065eb503]::session::Session>::track_errors::<rustc_hir_analysis[2ce2f0004243268f]::check_crate::{closure#2}, ()>
  48:     0x7f66dbeab312 - rustc_hir_analysis[2ce2f0004243268f]::check_crate
  49:     0x7f66dbea23fa - rustc_interface[685a07e484656f4a]::passes::analysis
  50:     0x7f66dbf2beba - rustc_query_impl[1b840d390aceead0]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[1b840d390aceead0]::query_impl::analysis::dynamic_query::{closure#2}::{closure#0}, rustc_middle[c8a9aab83046b80]::query::erase::Erased<[u8; 1usize]>>
  51:     0x7f66dbf2bea9 - <rustc_query_impl[1b840d390aceead0]::query_impl::analysis::dynamic_query::{closure#2} as core[61f378b86da375b9]::ops::function::FnOnce<(rustc_middle[c8a9aab83046b80]::ty::context::TyCtxt, ())>>::call_once
  52:     0x7f66dc0a2f58 - rustc_query_system[6dbbf163f57784cb]::query::plumbing::try_execute_query::<rustc_query_impl[1b840d390aceead0]::DynamicConfig<rustc_query_system[6dbbf163f57784cb]::query::caches::SingleCache<rustc_middle[c8a9aab83046b80]::query::erase::Erased<[u8; 1usize]>>, false, false, false>, rustc_query_impl[1b840d390aceead0]::plumbing::QueryCtxt, false>
  53:     0x7f66dc0a2d29 - rustc_query_impl[1b840d390aceead0]::query_impl::analysis::get_query_non_incr::__rust_end_short_backtrace
  54:     0x7f66dbc76d35 - <rustc_middle[c8a9aab83046b80]::ty::context::GlobalCtxt>::enter::<rustc_driver_impl[7b385e897129221a]::run_compiler::{closure#1}::{closure#2}::{closure#4}, core[61f378b86da375b9]::result::Result<(), rustc_span[8207084c985c29b2]::ErrorGuaranteed>>
  55:     0x7f66dbc76362 - <rustc_interface[685a07e484656f4a]::interface::Compiler>::enter::<rustc_driver_impl[7b385e897129221a]::run_compiler::{closure#1}::{closure#2}, core[61f378b86da375b9]::result::Result<core[61f378b86da375b9]::option::Option<rustc_interface[685a07e484656f4a]::queries::Linker>, rustc_span[8207084c985c29b2]::ErrorGuaranteed>>
  56:     0x7f66dbc6d075 - rustc_span[8207084c985c29b2]::set_source_map::<core[61f378b86da375b9]::result::Result<(), rustc_span[8207084c985c29b2]::ErrorGuaranteed>, rustc_interface[685a07e484656f4a]::interface::run_compiler<core[61f378b86da375b9]::result::Result<(), rustc_span[8207084c985c29b2]::ErrorGuaranteed>, rustc_driver_impl[7b385e897129221a]::run_compiler::{closure#1}>::{closure#0}::{closure#0}>
  57:     0x7f66dbc6cae6 - <scoped_tls[bbce240ef0a64b5f]::ScopedKey<rustc_span[8207084c985c29b2]::SessionGlobals>>::set::<rustc_interface[685a07e484656f4a]::interface::run_compiler<core[61f378b86da375b9]::result::Result<(), rustc_span[8207084c985c29b2]::ErrorGuaranteed>, rustc_driver_impl[7b385e897129221a]::run_compiler::{closure#1}>::{closure#0}, core[61f378b86da375b9]::result::Result<(), rustc_span[8207084c985c29b2]::ErrorGuaranteed>>
  58:     0x7f66dbc6c0ac - std[158e0661572bfb70]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[685a07e484656f4a]::util::run_in_thread_pool_with_globals<rustc_interface[685a07e484656f4a]::interface::run_compiler<core[61f378b86da375b9]::result::Result<(), rustc_span[8207084c985c29b2]::ErrorGuaranteed>, rustc_driver_impl[7b385e897129221a]::run_compiler::{closure#1}>::{closure#0}, core[61f378b86da375b9]::result::Result<(), rustc_span[8207084c985c29b2]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[61f378b86da375b9]::result::Result<(), rustc_span[8207084c985c29b2]::ErrorGuaranteed>>
  59:     0x7f66dbc6be75 - <<std[158e0661572bfb70]::thread::Builder>::spawn_unchecked_<rustc_interface[685a07e484656f4a]::util::run_in_thread_pool_with_globals<rustc_interface[685a07e484656f4a]::interface::run_compiler<core[61f378b86da375b9]::result::Result<(), rustc_span[8207084c985c29b2]::ErrorGuaranteed>, rustc_driver_impl[7b385e897129221a]::run_compiler::{closure#1}>::{closure#0}, core[61f378b86da375b9]::result::Result<(), rustc_span[8207084c985c29b2]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[61f378b86da375b9]::result::Result<(), rustc_span[8207084c985c29b2]::ErrorGuaranteed>>::{closure#1} as core[61f378b86da375b9]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  60:     0x7f66d9771305 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hfa7c9203707b95b4
                               at /rustc/921f669749a57ab5936721fdd93b2da57b581381/library/alloc/src/boxed.rs:1993:9
  61:     0x7f66d9771305 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hfff12c5df8b973a7
                               at /rustc/921f669749a57ab5936721fdd93b2da57b581381/library/alloc/src/boxed.rs:1993:9
  62:     0x7f66d9771305 - std::sys::unix::thread::Thread::new::thread_start::hb792ef8e1c27dbc6
                               at /rustc/921f669749a57ab5936721fdd93b2da57b581381/library/std/src/sys/unix/thread.rs:108:17
  63:     0x7f66d950444b - <unknown>
  64:     0x7f66d9587e40 - <unknown>
  65:                0x0 - <unknown>

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.72.0-nightly (921f66974 2023-07-07) running on x86_64-unknown-linux-gnu

note: compiler flags: -Z lower-impl-trait-in-trait-to-assoc-ty

query stack during panic:
#0 [collect_return_position_impl_trait_in_trait_tys] comparing an impl and trait method signature, inferring any hidden `impl Trait` types in the process
#1 [type_of] computing type of `<impl at treereduce.out:9:1: 9:23>::{opaque#0}`
#2 [check_mod_impl_wf] checking that impls are well-formed in top-level module
#3 [analysis] running analysis passes on this crate
end of query stack
error: aborting due to 2 previous errors

For more information about this error, try `rustc --explain E0601`.
```

</p>
</details>

### PR DESCRIPTION
**Pull request by spastorino**
Fixes #113439

`on_unimplemented_note` was calling `item_name` for RPITITs and that produced ICEs. I've added a regression test for that but also have removed `from_method` symbol entirely because it wasn't even used and by doing that the `item_name` call was also removed.

r? @compiler-errors

### CODE REVIEW

File: compiler/rustc_trait_selection/src/traits/error_reporting/on_unimplemented.rs [hunk 1]
```diff
@@ -182,7 +182,9 @@ impl<'tcx> TypeErrCtxtExt<'tcx> for TypeErrCtxt<'_, 'tcx> {
             // which we might want to be some sort of hygienic.
             //
             // Currently I'm leaving it for what I need for `try`.
-            if self.tcx.trait_of_item(item) == Some(trait_ref.def_id) {
+            if !self.tcx.is_impl_trait_in_trait(item)
+                && self.tcx.trait_of_item(item) == Some(trait_ref.def_id)
+            {
                 let method = self.tcx.item_name(item);
                 flags.push((sym::from_method, None));
```
Comment (compiler-errors) [inline compiler/rustc_trait_selection/src/traits/error_reporting/on_unimplemented.rs:189]: I'm pretty certain that nothing uses `from_method`. Can you verify this, and then just delete this whole if statement, and all references to `sym::from_method` from within the compiler?

**Review by compiler-errors — CHANGES_REQUESTED** [review]

**Review by compiler-errors — APPROVED** [review]
Please change the title and leave a PR description saying what this does, then r=me
