### PR TITLE
rustdoc: don't ignore path distance for doc aliases

### LINKED ISSUE #146214: rustdoc search ignores path distance when considering doc aliases
# Reproduction Steps
search for [`usize::popcount`](https://doc.rust-lang.org/nightly/std/?search=usize%3A%3Apopcount) in nightly std docs.

# Expected Outcome
only `usize::count_ones` (and possibly isize::count_ones, due to low edit distances) should show up.

# Actual Output
every `count_ones` method shows up.

screenshot

# Version
rustdoc 1.91.0-nightly (a1208bf76 2025-09-03)

# Additional Details
related: #141475 #145829

### PR DESCRIPTION
**Pull request by lolbinarycat**
Ran into a bit of an issue due to the overloading of space (it needs to be a metachar for most searches, but not for doc aliases that have space in them).  Not sure if I need to also need to account for other whitespace chars.

screenshot

fixes https://github.com/rust-lang/rust/issues/146214

r? @GuillaumeGomez

### CODE REVIEW

File: src/librustdoc/html/static/js/search.js [hunk 1]
```diff
@@ -3933,16 +3933,25 @@ class DocSearch {
                  * @returns {Promise<rustdoc.PlainResultObject?>}
                  */
                 const handleAlias = async(name, alias, dist, index) => {
+                    const item = nonnull(await this.getRow(alias, false));
+                    // space both is an alias for ::,
```
Comment (yotamofek) [inline src/librustdoc/html/static/js/search.js:3937]: I think you meant "a space is both an alias...", but not sure

Comment (lolbinarycat) [reply src/librustdoc/html/static/js/search.js:3937]: I believe either is grammatically correct.

File: tests/rustdoc-js/alias-path-distance-146214.js [hunk 2]
```diff
@@ -0,0 +1,19 @@
...
+        'others': [
+            { 'path': 'alias_path_distance::Foo', 'name': 'baz' },
+        ],
+    },
+    {
+        'query': '"Foo::zzz"',
+        'others': [
+            { 'path': 'alias_path_distance::Foo', 'name': 'baz' },
+        ],
+    },
```
Comment (GuillaumeGomez) [inline tests/rustdoc-js/alias-path-distance-146214.js:18]: Can you add a fuzzy query test like `z` and `Foo::z` so we can confirm it works as well please?

Comment (lolbinarycat) [reply tests/rustdoc-js/alias-path-distance-146214.js:18]: Added, tho used `zzzz` instead so it wouldn't just match the z in "baz".

**Review by GuillaumeGomez — APPROVED** [review]

**Comment by GuillaumeGomez** [comment]
Thanks!

@bors r+ rollup
