### PR TITLE
Recover when unclosed char literal is parsed as a lifetime in some positions

### LINKED ISSUE #101278: Unterminated char literal complains about lifetimes
Given the following code

```rust
let _ = ['1','2,'3'];
```

the current output is

```
error: lifetimes cannot start with a number
 --> src/main.rs:2:18
  |
2 |     let _ = ['1','2,'3'];
  |                  ^^

error: expected `while`, `for`, `loop` or `{` after a label
 --> src/main.rs:2:20
  |
2 |     let _ = ['1','2,'3'];
  |                    ^ expected `while`, `for`, `loop` or `{` after a label
```

It should instead recognize that a char literal was intended:

```
error: unterminated char literal
 --> src/main.rs:2:18
  |
2 |     let _ = ['1','2,'3'];
  |                  ^^
help: add a closing `'`
  |
2 |     let _ = ['1','2','3'];
  |                    +
```

_https://internals.rust-lang.org/t/error-message-for-vec-1-2-3/17309_

### PR DESCRIPTION
**Pull request by compiler-errors**
Fixes #101278

### CODE REVIEW

**Comment by compiler-errors** [comment]
Lol, accidentally pushed the RPITIT branch. One sec.

File: compiler/rustc_parse/src/parser/expr.rs [hunk 1]
```diff
@@ -1516,6 +1518,15 @@ impl<'a> Parser<'a> {
             || self.token.is_whole_block()
         {
             self.parse_block_expr(label, lo, BlockCheckMode::Default)
+        } else if !ate_colon
+            && (matches!(self.token.kind, token::CloseDelim(_) | token::Comma)
```
Comment (compiler-errors) [inline compiler/rustc_parse/src/parser/expr.rs:1522]: I'm using "close delim or comma or operator" here as a heuristic, because if we use something like "next token isn't colon" then we suggest `'a 0` => `'a' 0` which is nonsense.

File: compiler/rustc_parse/src/parser/pat.rs [hunk 2]
```diff
@@ -394,6 +394,21 @@ impl<'a> Parser<'a> {
             } else {
                 PatKind::Path(qself, path)
             }
+        } else if matches!(self.token.kind, token::Lifetime(_))
+            && !self.look_ahead(1, |token| matches!(token.kind, token::Colon))
```
Comment (compiler-errors) [inline compiler/rustc_parse/src/parser/pat.rs:398]: In pattern position, we're totally fine with using "next token isn't colon" as a heuristic. We could probably just _always_ try to recover if it's a lifetime, because we never have `'a: label {}` in a pattern position anyways.

File: src/test/ui/parser/issues/issue-93282.stderr [hunk 3]
```diff
@@ -3,6 +3,11 @@ error: expected `while`, `for`, `loop` or `{` after a label
    |
 LL |     f<'a,>
    |         ^ expected `while`, `for`, `loop` or `{` after a label
+   |
+help: add `'` to close the char literal
+   |
+LL |     f<'a',>
```
Comment (compiler-errors) [inline src/test/ui/parser/issues/issue-93282.stderr:9]: This is somewhat unfortunate, but teaching the parser to avoid suggesting this is just as hard as solving the turbofish problem I think, because at this point we're parsing `f < $EXPR`

**Comment by compiler-errors** [comment]
I'm gonna re-roll this since it's been almost two months.

r? compiler

**Comment by compiler-errors** [comment]
r? compiler

rustbot wake up

**Comment by compiler-errors** [comment]
@jackh726 is also a busy person :rofl: 

r? diagnostics

File: src/test/ui/parser/issues/issue-93282.stderr (hunk 3 above)
Comment (compiler-errors) [reply src/test/ui/parser/issues/issue-93282.stderr:9]: Hm, maybe I can avoid this if the prev token is `<`. Or maybe this suggestion is just nonsense and the PR needs to be scrapped.

File: compiler/rustc_parse/src/parser/expr.rs [hunk 4]
```diff
@@ -1603,6 +1618,39 @@ impl<'a> Parser<'a> {
...
     }
 
+    /// Emit an error when a char is parsed as a lifetime because of a missing quote
+    pub(super) fn recover_unclosed_char(
+        &mut self,
+        lifetime: Ident,
+        err: impl FnOnce(&mut Self) -> DiagnosticBuilder<'a, ErrorGuaranteed>,
+    ) -> ast::Lit {
+        if let Some(mut diag) =
+            self.sess.span_diagnostic.steal_diagnostic(lifetime.span, StashKey::LifetimeIsChar)
```
Comment (estebank) [inline compiler/rustc_parse/src/parser/expr.rs:1628]: I missed the introduction of this more principled version of this mechanism :)

File: compiler/rustc_parse/src/parser/pat.rs (hunk 2 above)
Comment (estebank) [reply compiler/rustc_parse/src/parser/pat.rs:406]: Could we include this as a comment?

File: src/test/ui/parser/issues/issue-93282.stderr (hunk 3 above)
Comment (estebank) [reply src/test/ui/parser/issues/issue-93282.stderr:9]: It's fine, this is best effort.

**Review by estebank — APPROVED** [review]

File: compiler/rustc_parse/src/parser/pat.rs (hunk 2 above)
Comment (compiler-errors) [reply compiler/rustc_parse/src/parser/pat.rs:406]: Can do
