### PR TITLE
resolve: Preserve ambiguous glob reexports in crate metadata

### LINKED ISSUE #36837: item_like_imports: Can "ambiguity error" items be reexported?
Is the next code well formed or not?

```
#![feature(item_like_imports)]

mod ty1 {
    pub type A = u8;
}
mod ty2 {
    pub type A = u8;
}
mod ambig {
    // Create an ambiguity item in type namespace.
    pub use ty1::*;
    pub use ty2::*;
}
mod merge {
    pub use ambig::*; // <- reexports an ambiguity error, or reexports nothing?
    pub use ty1::*; // <- does this contribute to the ambiguity error or create a valid name?
}

fn main() {
    let _: merge::A; // <- Valid or an ambiguity error?
}
```

Currently the behavior of this code depends on whether the "merge" step is done in the same crate or in some other crate.
In a single crate scenario the snippet above fails to compile with `A is ambiguous` error.
If `merge` is moved to another crate, then all erroneous resolutions are filtered away and are not represented in metadata, `pub use ambig::*` becomes an empty import and `merge::A` unambiguously means `ty1::A`.
Supposedly, local and cross-crate behavior should be the same.

cc @jseyfried @nrc

### PR DESCRIPTION
**Pull request by petrochenkov**
So in cross-crate scenarios they can work in the same way as in crate-local scenarios.

Change Description: https://github.com/rust-lang/rust/pull/147984#issuecomment-3455514826

Resurrection of https://github.com/rust-lang/rust/pull/114682.
One of unblocking steps for https://github.com/rust-lang/rust/pull/145108.
Fixes https://github.com/rust-lang/rust/issues/36837.

### CODE REVIEW

**Comment by petrochenkov** [comment]
That's a lot of breakage.
Mostly from dependencies, including various version of `openssl` that we've seen previously.
I'll demote this error to always be reported as a lint in cross-crate scenarios, and then rerun crater.

**Comment by petrochenkov** [comment]
@bors try

`@craterbot run mode=check-only p=1 crates=https://crater-reports.s3.amazonaws.com/pr-147984/retry-regressed-list.txt`

**Comment by petrochenkov** [comment]
#### Change description for the lang team

This PR implements a long stanging missing piece in cross-crate reexports.

Currently ambiguous glob imports/reexports produce an error like this on local use.

```rust
// Crate `mylib`

mod m1 {
    pub struct S {}
}
mod m2 {
    pub struct S {}
}

pub use m1::*;
pub use m2::*;

fn main() {
	let s = self::S {}; // ERROR `S` is ambiguous
}
```

However, from other crates such reexports are entirely invisible, because they are ignored when encoding rlib metadata.

```rust
let s = mylib::S {}; // ERROR cannot resolve `S` in module `mylib`

use mylib::*; // OK, empty glob import, puts no names into the current module
```

This PR implements the missing metadata encoding and the reexports can now be observed from other crates, so the behavior becomes identical in cross-crate and crate-local scenarios.
```rust
let s = mylib::S {}; // ERROR `S` is ambiguous

use mylib::*; // OK, puts one name `S` into the current module, that will produce errors on actual use

// In particular, if we had another glob import importing `S` here, then there will be a new conflict (only on actual use).
// That's why the change is potentially breaking, see the breakage analysis in the comment above.
use thylib::*; // Also imports `S`
```

**Comment by traviscross** [comment]
The FCP, as proposed, is to accept that soft breakage.

(I.e., "soft breakage" due to this being from a deny-by-default lint, that could be allowed and is affected by `cap-lints`, rather than due to a hard error.)

**Comment by traviscross** [comment]
cc @yaahc @rust-lang/lang-docs @rust-lang/fls

**Comment by jdonszelmann** [comment]
@rustbot reroll

sorry, am not sure I can review this right now

File: compiler/rustc_resolve/src/build_reduced_graph.rs [hunk 1]
```diff
@@ -244,17 +265,31 @@ impl<'ra, 'tcx> Resolver<'ra, 'tcx> {
...
+            let span = child_span(self, reexport_chain, res);
+            let res = res.expect_non_local();
+            let ambig_kind = match ambig_kind {
+                AmbigModChildKind::GlobVsGlob => AmbiguityKind::GlobVsGlob,
+                AmbigModChildKind::GlobVsExpanded => AmbiguityKind::GlobVsExpanded,
+            };
+            (self.arenas.new_res_binding(res, vis, span, expansion), ambig_kind)
+        });
         // Record primary definitions.
         match res {
```
Comment (yaahc) [inline compiler/rustc_resolve/src/build_reduced_graph.rs:298]: NIT: When I was reviewing this section I felt like there was a high signal to noise ratio with the way this match is structured. As far as I can tell the only difference between the different `define_extern` calls is the namespace argument. I'd recommend changing this match to evaluate to the namespace and pass that ns local into a single shared invocation of `define_extern` regardless of res defkind.

Especially with the new field changing the formatting to be one line per argument, its even more difficult now to visually tell what is different and what isn't between those invocations.

Feel free to ignore this one, just thought I'd share my experience.

File: compiler/rustc_resolve/src/build_reduced_graph.rs [hunk 2]
```diff
@@ -232,9 +241,21 @@ impl<'ra, 'tcx> Resolver<'ra, 'tcx> {
...
-            let parent_scope = ParentScope::module(module, self.arenas);
-            self.build_reduced_graph_for_external_crate_res(child, parent_scope, i)
+        let def_id = module.def_id();
+        let children = self.tcx.module_children(def_id);
+        let parent_scope = ParentScope::module(module, self.arenas);
+        for (i, child) in children.iter().enumerate() {
+            self.build_reduced_graph_for_external_crate_res(child, parent_scope, i, None)
+        }
+        for (i, child) in
+            self.cstore().ambig_module_children_untracked(def_id, self.tcx.sess).enumerate()
```
Comment (yaahc) [inline compiler/rustc_resolve/src/build_reduced_graph.rs]: Why does this need to be untracked?

I did some digging and as far as I can tell this is referring to how it's not being accessed through the query system unlike the `module_children` access above, that it'd break incremental compilation, and that it should only be called pre-HIR (during resolve). I'm not super familiar with the query system though or the later stages of resolution so I want to double check that I understand this properly.

My understanding is that this is satisfying the "should only be called" pre-HIR requirement because all of these ambig children are materialized into their appropriate scopes during early resolution and this untracked method is never called after that.

What I don't understand is how this would interact with incremental compilation and break things and what differences there are between the module children and ambig module children that make us only want to track calls to one of them.

File: compiler/rustc_resolve/src/diagnostics.rs [hunk 3]
```diff
@@ -145,12 +145,13 @@ impl<'ra, 'tcx> Resolver<'ra, 'tcx> {
         for ambiguity_error in &self.ambiguity_errors {
             let diag = self.ambiguity_diagnostics(ambiguity_error);
             if ambiguity_error.warning {
-                let NameBindingKind::Import { import, .. } = ambiguity_error.b1.0.kind else {
-                    unreachable!()
+                let node_id = match ambiguity_error.b1.0.kind {
+                    NameBindingKind::Import { import, .. } => import.root_id,
+                    NameBindingKind::Res(_) => CRATE_NODE_ID,
```
Comment (yaahc) [inline compiler/rustc_resolve/src/diagnostics.rs:153]: I want to make sure I understand why this changed.

My understanding is that previously we'd only hit this code path via ambiguity errors produced from glob imports in `try_define_local`. Now we can create them from the ambiguity_children of extern crates, but these only contain a simplified copy of the original import chain and the final res from the original nested set of namebindings. Since you couldn't reasonably recreate the original nested set of namebindings you instead construct a new namebinding from just the underlying Res which you mark as an ambiguity warning.

Let me know if that sounds right

The remaining question I have is how does the NodeId selected here impact the diagnostic we emit? From what I can tell the span in use is that of the outermost import in the re-export chain. I would assume that the diagnostic would be able to point to the external ambiguous pub use declaration but I'm not familiar enough with our diagnostic logic to know how the nodeid comes in. I tried poking around and it seems like it may impact the way the lints are buffered and emitted. I'd guess this might impact the order in which this warning is emitted relative to other diagnostics but I stopped digging when I saw that the rustc_dev_guide said that nodeid was being phased out. I'm guessing this is relatively inconsequential.

File: tests/ui/imports/glob-conflict-cross-crate-1.rs [hunk 4]
```diff
@@ -3,10 +3,8 @@
...
 fn main() {
-    glob_conflict::f(); //~ ERROR cannot find function `f` in crate `glob_conflict`
-    //^ FIXME: `glob_conflict::f` should raise an
-    // ambiguity error instead of a not found error.
-    glob_conflict::glob::f(); //~ ERROR cannot find function `f` in module `glob_conflict::glob`
-    //^ FIXME: `glob_conflict::glob::f` should raise an
-    // ambiguity error instead of a not found error.
+    glob_conflict::f(); //~ ERROR `f` is ambiguous
+                        //~| WARN this was previously accepted
+    glob_conflict::glob::f(); //~ ERROR `f` is ambiguous
```
Comment (yaahc) [inline tests/ui/imports/glob-conflict-cross-crate-1.rs:9]: I honestly have no idea how this is resolving, the glob import this is resolving through looks like nonsense to me: https://github.com/rust-lang/rust/blob/66428d92bec337ed4785d695d0127276a482278c/tests/ui/imports/auxiliary/glob-conflict.rs#L12-L17

when I try to do this in a test crate it says "cannot export all crates". I wouldn't expect f to be in scope for re-exportation due to the `mod glob {..}` boundary. How does this work? I'm thoroughly stumped

File: tests/ui/imports/glob-conflict-cross-crate-3.rs [hunk 5]
```diff
@@ -12,5 +11,8 @@ use a::*;
 
 fn main() {
     let _a: C = 1;
-    //^ FIXME: `C` should be identified as an ambiguous item.
+    //~^ ERROR `C` is ambiguous
+    //~| ERROR `C` is ambiguous
+    //~| WARN this was previously accepted
+    //~| WARN this was previously accepted
```
Comment (yaahc) [inline tests/ui/imports/glob-conflict-cross-crate-3.rs:17]: why does this emit so many duplicate warnings? It looks like theres two unique ones, the one for the local ambiguity and the one for the external ambiguity, but the stderr file looks like its emitting each of those twice for a total of four warnings. Why isn't this being prevented by the warning deduplication logic?

https://github.com/rust-lang/rust/blob/743dc68f9317551c44669745e73f9b2d63124b05/compiler/rustc_resolve/src/lib.rs#L2072-L2075

File: tests/ui/imports/issue-114682-2.rs [hunk 6]
```diff
@@ -3,17 +3,10 @@
...
-type A = issue_114682_2_extern::max;
-//~^ ERROR: expected type, found function `issue_114682_2_extern::max`
-// FIXME:
-// The above error was emitted due to `(Mod(issue_114682_2_extern), Namespace(Type), Ident(max))`
-// being identified as an ambiguous item.
-// However, there are two points worth discussing:
-// First, should this ambiguous item be omitted considering the maximum visibility
-// of `issue_114682_2_extern::m::max` in the type namespace is only within the extern crate.
-// Second, if we retain the ambiguous item of the extern crate, should it be treated
-// as an ambiguous item within the local crate for the same reasoning?
```
Comment (yaahc) [inline tests/ui/imports/issue-114682-2.rs:17]: Can you link to where the decision on these questions was made?

From my understanding of the PR it's looking like you went with

1. no
2. no

Is that right?

File: tests/ui/imports/issue-114682-3.rs [hunk 7]
```diff
@@ -19,6 +18,5 @@ pub use self::auto::*;
 fn main() {
     let a: u8 = 1;
     a.ext();
-    //^ FIXME: it should report `ext` not found because `SettingsExt`
-    // is an ambiguous item in `issue-114682-3-extern.rs`.
+    //~^ ERROR no method named `ext` found for type `u8` in the current scope
```
Comment (yaahc) [inline tests/ui/imports/issue-114682-3.rs:21]: I've not yet looked into how ambiguous imports interact with which traits are in scope so the logic for this is unfamiliar to me but I find this behavior surprising. I would have expected this to report an ambiguity error while selecting the innermost[^1] candidate and continuing, not for it to block the selection of all three candidates in scope with no mention of ambiguity.

This doesn't seem like an ideal diagnostic experience. Is there some structural issue that makes it hard to identify and report that this error was caused by an interaction with ambiguious imports?

[^1]: I know this is a globvsglob/globvsexpanded issue where they're ambiguous within a single scope so I'm not sure innermost is accurate, but I don't remember off hand how the candidates for this kind of ambiguity are stored and its nearing the end of the day so I wanna get my first review pass posted rather than diving in more deeply.

File: tests/ui/imports/issue-114682-4.rs [hunk 8]
```diff
@@ -1,12 +1,13 @@
-//@ check-pass
 //@ aux-build: issue-114682-4-extern.rs
 // https://github.com/rust-lang/rust/pull/114682#issuecomment-1880755441
 
 extern crate issue_114682_4_extern;
 
 use issue_114682_4_extern::*;
 
-fn a() -> Result<i32, ()> { // FIXME: `Result` should be identified as an ambiguous item.
+//~v ERROR type alias takes 1 generic argument but 2 generic arguments were supplied
```
Comment (yaahc) [inline tests/ui/imports/issue-114682-4.rs:8]: yeah see, this one picks one of the extern results and prints this error, that's how I'd expect things to work normally, the previous one with the traits in scope resolution was super inconsistent w/ my previous experience.

File: compiler/rustc_middle/src/metadata.rs [hunk 9]
```diff
@@ -44,3 +44,17 @@ pub struct ModChild {
     /// Empty if the module child is a proper item.
     pub reexport_chain: SmallVec<[Reexport; 2]>,
 }
+
+#[derive(Debug, TyEncodable, TyDecodable, HashStable)]
+pub enum AmbigModChildKind {
+    GlobVsGlob,
+    GlobVsExpanded,
```
Comment (yaahc) [inline compiler/rustc_middle/src/metadata.rs:51]: I'm assuming this means logic should be able to preserve globvsexpanded ambiguities across crate boundaries but I don't see any tests exercising this logic. Can you add one?

**Comment by tmandry** [comment]
@yaahc Just checking you mean this one. Correct, I don't consider it a blocker.

> nikomatsakis made a suggestion to lint anytime we glob export from two different crates, which I liked.

File: tests/ui/imports/glob-conflict-cross-crate-1.rs (hunk 4 above)
Comment (yaahc) [reply tests/ui/imports/glob-conflict-cross-crate-1.rs:9]: @P1n3appl3 pointed out that this is a 2015 edition thing

File: compiler/rustc_middle/src/metadata.rs (hunk 9 above)
Comment (petrochenkov) [reply compiler/rustc_middle/src/metadata.rs:51]: I'll add a test.
In any case, cross-crate `GlobVsExpanded` is unnecessary and will be removed in https://github.com/rust-lang/rust/pull/149681.

File: compiler/rustc_resolve/src/build_reduced_graph.rs (hunk 2 above)
Comment (petrochenkov) [reply compiler/rustc_resolve/src/build_reduced_graph.rs]: Name resolution happens before incremental compilation starts, so we can just read things from `CStore` instead of using queries, see other uses of `.cstore()` in `rustc_resolve`.

File: compiler/rustc_resolve/src/build_reduced_graph.rs (hunk 1 above)
Comment (petrochenkov) [reply compiler/rustc_resolve/src/build_reduced_graph.rs:298]: I can factor the `define_extern` calls into a closure.
I'd like to preserve the exhaustive match because of the `bug!("unexpected resolution: {:?}", res)` part.

File: compiler/rustc_resolve/src/diagnostics.rs (hunk 3 above)
Comment (petrochenkov) [reply compiler/rustc_resolve/src/diagnostics.rs:153]: >Let me know if that sounds right

Sounds right, some parts of the original chain are minimally preserved just to report nice diagnostics.

>The remaining question I have is how does the NodeId selected here impact the diagnostic we emit?

It determines the placement of `allow`/`warn`/`deny` attributes.
`CRATE_NODE_ID` means that only crate level allow-warn-deny would work (other crates don't have node ids, so crate id here is used as a fallback).
The node id selection here is not good in general, it would be better to use some use-site node id here, but it's a larger change, and I wouldn't bother doing it in this PR.

File: tests/ui/imports/glob-conflict-cross-crate-1.rs (hunk 4 above)
Comment (petrochenkov) [reply tests/ui/imports/glob-conflict-cross-crate-1.rs:9]: Yes, `use *` on 2015 edition is just `use crate::*`.

File: tests/ui/imports/glob-conflict-cross-crate-3.rs (hunk 5 above)
Comment (petrochenkov) [reply tests/ui/imports/glob-conflict-cross-crate-3.rs:17]: `fn record_use_inner` walks the import chain and reports an ambiguity at every step.
I think we could only report the first one (if it's an error).
I look at the PR introducing the deduplication logic, and I don't think the author really understood what they were doing, not sure why it doesn't deduplicate this specific case.
In any case, probably off-topic for this PR.

Upd: also `record_use` can run twice on the same "use", at least for imports (for other diagnostic reasons).

File: tests/ui/imports/issue-114682-2.rs (hunk 6 above)
Comment (petrochenkov) [reply tests/ui/imports/issue-114682-2.rs:17]: 1. Correct, seems to be the simplest and conservative choice.
2. I don't quite understand the sentence, but it seems like the answer is "yes", because `issue_114682_2_extern::max` is indeed treated as ambiguous in this test (= local crate).

File: tests/ui/imports/issue-114682-3.rs (hunk 7 above)
Comment (petrochenkov) [reply tests/ui/imports/issue-114682-3.rs:21]: This is a separate issue (https://github.com/rust-lang/rust/issues/147992), there are several possible ways to address it, and the latest development can be found in https://github.com/rust-lang/rust/pull/149058.

Comment (petrochenkov) [reply tests/ui/imports/issue-114682-3.rs:21]: I think this PR and that PR combined will result in .ext() producing a compatibility warning about the method call being ambiguous.

File: tests/ui/imports/ambiguous-glob-vs-expanded-extern.stderr [hunk 10]
```diff
@@ -0,0 +1,45 @@
...
+note: `mac` could refer to the macro defined here
+  --> $DIR/auxiliary/glob-vs-expanded.rs:18:9
+   |
+LL | pub use m::*;
+   |         ^
+note: `mac` could also refer to the macro defined here
+  --> $DIR/auxiliary/glob-vs-expanded.rs:18:9
+   |
+LL | pub use m::*;
+   |         ^
```
Comment (yaahc) [inline tests/ui/imports/ambiguous-glob-vs-expanded-extern.stderr]: This seems to be emitting the diagnostic as though it were a globvsglob rather than a globvsexpanded ambiguity.

I would expect it to say:

```
= note: ambiguous because of a conflict between a name from a glob import and a macro-expanded name in the same module during import or macro resolution
  note: `mac` could refer to the macro imported here
```

Comment (petrochenkov) [reply tests/ui/imports/ambiguous-glob-vs-expanded-extern.stderr]: Removed the unnecessary glob reexport from the test for now.
The root issue here is sort of hard to fix, for that you need https://github.com/petrochenkov/rust/tree/neverwrite, but it is mostly blocked on https://github.com/rust-lang/rust/pull/149195.

**Comment by petrochenkov** [comment]
cc @Razaekel 
Together with diesel `noise-0.7.0` is the largest source of ambiguous reexports here (it's also the largest source of regressions in https://github.com/rust-lang/rust/pull/149195).
If you are willing to release a `0.7.1` version with a fix, then I will prepare a pull request.

The error typically looks like this.
```rust
error: `Perlin` is ambiguous
 --> src/terrain.rs:2:22
  |
2 | use noise::{NoiseFn, Perlin, Seedable};
  |                      ^^^^^^ ambiguous name
  |
  = warning: this was previously accepted by the compiler but is being phased out; it will become a hard error in a future release!
  = note: for more information, see issue #114095 <https://github.com/rust-lang/rust/issues/114095>
  = note: ambiguous because of multiple glob imports of a name in the same module
note: `Perlin` could refer to the struct defined here
 --> /opt/rustwide/cargo-home/registry/src/index.crates.io-1949cf8c6b5b557f/noise-0.7.0/src/noise_fns/generators.rs:6:9
  |
6 | pub use self::perlin::*;
  |         ^^^^^^^^^^^^
note: `Perlin` could also refer to the struct defined here
 --> /opt/rustwide/cargo-home/registry/src/index.crates.io-1949cf8c6b5b557f/noise-0.7.0/src/noise_fns/generators.rs:7:9
  |
7 | pub use self::perlin_surflet::*;
  |         ^^^^^^^^^^^^^^^^^^^^
  = note: `#[deny(ambiguous_glob_imports)]` (part of `#[deny(future_incompatible)]`) on by default
```
