### PR TITLE
Fix span of byte-escaped left format args brace

### LINKED ISSUE #102057: `format!` error has wrong span when using encoded `{`
I tried this code:

```rust
format!("\x7Ba}")
```

I expected to see this happen: a "no value found" error pointing at the `a` token

Instead, this happened: a "no value found" error pointing at the `x7Ba`:

```
error[E0425]: cannot find value `a` in this scope
 --> src/main.rs:2:11
  |
2 | format!("\x7Ba}")
  |           ^^^^ not found in this scope
```

### PR DESCRIPTION
**Pull request by cassaundra**
Fix #102057 (see issue for example).

Previously, the use of escaped left braces (`\x7B`) in format args resulted in an incorrectly offset span. This patch fixes that by considering any escaped characters within the string instead of using a constant offset.

### CODE REVIEW

File: compiler/rustc_parse_format/src/lib.rs [hunk 1]
```diff
@@ -224,7 +224,7 @@ impl<'a> Iterator for Parser<'a> {
                 '{' => {
                     let curr_last_brace = self.last_opening_brace;
                     let byte_pos = self.to_span_index(pos);
-                    let lbrace_end = InnerOffset(byte_pos.0 + 1);
+                    let lbrace_end = self.to_span_index(pos + 1);
```
Comment (cjgillot) [inline compiler/rustc_parse_format/src/lib.rs:227]: There is a manual creation of an `InnerOffset` just below (github won't let me comment on it).  Could it trigger a similar bug?  Should it be changed in a similar way?

Comment (cassaundra) [reply compiler/rustc_parse_format/src/lib.rs:227]: That's a good point. Originally I had assumed not since I wasn't able to find any breaking examples, but I just found that following:

```rust
println!("{\x7D");
```

gives the following error:

```
error: 1 positional argument in format string, but no arguments were given
 --> src/main.rs:2:15
  |
2 |     println!("{\x7D");
  |  
```

I can go ahead and apply the fix to that line as well, and add some more tests.

Comment (cjgillot) [reply compiler/rustc_parse_format/src/lib.rs:227]: Yes, please, with the test if possible.  That's a good opportunity to fix several identical bugs at once.  I'll approve once this is done.

Comment (cassaundra) [reply compiler/rustc_parse_format/src/lib.rs:227]: Fixed in efc6df2.

**Comment by cassaundra** [comment]
Looking more into this issue, it seems like the way that format strings handle skipped characters erases some necessary information about the source string.

Consider these two statements:
```rust
println!("{\x7D"};

println!("{}\


");
```

In both cases, the resultant interned string looks like `{}`, with skips at positions 2, 3, and 4, so we can't correctly determine the width of `}` by just looking at the skips.

I'm thinking that it would be best to refactor this skipping mechanism to instead deal with a sequence of character widths (essentially squashing together some of the skips). It would make this PR larger than it initially was, but that's fine with me. Thoughts?

**Comment by cjgillot** [comment]
@cassaundra a follow-up PR sounds good.  If you don't mind, let's go back to the previous version of the patch, so we can get it merged in the mean time.

**Comment by cassaundra** [comment]
Okay! Back to e5096d4cba0.
