### PR TITLE
Resolve instance for SymFn in global/naked asm

### LINKED ISSUE #140373: Link-time error when referencing symbols through generic types in `naked_asm!` block
When trying to reference a method on a generic type parameter from within a `naked_asm!` block, `rust-lld` reports a link-time error indicating that a symbol could not be resolved. This used to work on a Rust nightly from 2024-11-16, but no longer does on a recent nightly (2025-04-26), where `naked_functions` has been stabilized (#134213). 

Here's a link to a Rust playground that results in the link-time error:
https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=9de6dd640b6e55f857e8d65bafb82ab1

A minimal example to trigger this bug:
```rust
trait T {
    extern "C" fn t();
}

enum E<const C: usize> {}

impl<const C: usize> T for E<C> {
    extern "C" fn t() {
        println!("Const generic: {}", C);
    }
}

#[unsafe(naked)]
extern "C" fn foo<U: T>() {
    core::arch::naked_asm!(
        "push rax",
        "call {fn}",
        "pop rax",
        "ret",
        fn = sym <U as T>::t,
    );
}

fn main() {
    foo::<E<42>>();
}
```

I expected to see this happen: correctly reference the proper, monomorphized function symbol `<E<42> as T>::t`.

Instead, this happened:
```
error: linking with `cc` failed: exit status: 1
  |
  = note:  "cc" "-m64" "/tmp/rustcQVxPkQ/symbols.o" "<2 object files omitted>" "-Wl,--as-needed" "-Wl,-Bstatic" "<sysroot>/lib/rustlib/x86_64-unknown-linux-gnu/lib/{libstd-*,libpanic_unwind-*,libobject-*,libmemchr-*,libaddr2line-*,libgimli-*,librustc_demangle-*,libstd_detect-*,libhashbrown-*,librustc_std_workspace_alloc-*,libminiz_oxide-*,libadler2-*,libunwind-*,libcfg_if-*,liblibc-*,liballoc-*,librustc_std_workspace_core-*,libcore-*,libcompiler_builtins-*}.rlib" "-Wl,-Bdynamic" "-lgcc_s" "-lutil" "-lrt" "-lpthread" "-lm" "-ldl" "-lc" "-L" "/tmp/rustcQVxPkQ/raw-dylibs" "-B<sysroot>/lib/rustlib/x86_64-unknown-linux-gnu/bin/gcc-ld" "-fuse-ld=lld" "-Wl,-znostart-stop-gc" "-Wl,--eh-frame-hdr" "-Wl,-z,noexecstack" "-L" "/playground/target/debug/build/aws-lc-sys-a7b8dbb98ccb03f8/out" "-L" "/playground/target/debug/build/libsqlite3-sys-f8b7023b84d9d43f/out" "-L" "/playground/target/debug/build/ring-75909fa7c1b7acce/out" "-L" "/playground/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/windows_x86_64_gnu-0.52.6/lib" "-L" "/playground/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/windows_aarch64_msvc-0.53.0/lib" "-L" "/playground/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/windows_i686_gnu-0.53.0/lib" "-L" "/playground/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/windows_i686_msvc-0.53.0/lib" "-L" "/playground/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/windows_x86_64_gnu-0.53.0/lib" "-L" "/playground/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/windows_x86_64_msvc-0.53.0/lib" "-L" "<sysroot>/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-o" "/playground/target/debug/deps/playground-72b3069f10cc7f34" "-Wl,--gc-sections" "-pie" "-Wl,-z,relro,-z,now" "-nodefaultlibs"
  = note: some arguments are omitted. use `--verbose` to show all linker arguments
  = note: rust-lld: error: undefined hidden symbol: playground::T::t::h9639b9475488f044
          >>> referenced by playground.5e532e3d8d2adfd6-cgu.0
          >>>               /playground/target/debug/deps/playground-72b3069f10cc7f34.playground.5e532e3d8d2adfd6-cgu.0.rcgu.o:(playground::foo::hebf1c66e7ecb3c3d)
          collect2: error: ld returned 1 exit status
```

What's weird is that the symbol being referenced is not related to the actual type instantiation `playground::E::<42>`, but only the trait-method `playground::T::t`. Instead, on `nightly-2024-11-16`, the generated assembly references the concrete type, as one would expect:

```
0000000000014e00 <_ZN29naked_asm_generic_symbol_test3foo17h05ccf99589ca4161E>:
;       core::arch::naked_asm!(
   14e00: 50                            pushq   %rax
   14e01: e8 5a ff ff ff                callq   0x14d60 <_ZN94_$LT$naked_asm_generic_symbol_test..E$LT$_$GT$$u20$as$u20$naked_asm_generic_symbol_test..T$GT$1t17h182ea722fc2c8c77E>
   14e06: 58                            popq    %rax
   14e07: c3                            retq
   14e08: 0f 0b                         ud2
```

Hopefully the above should be sufficient information to reproduce this bug. ~In the meantime, I can try to bisect which nightly channel update (and perhaps which `rustc` change) broke this.~ EDIT: this error first started showing up on `rustc 1.85.0-nightly (d4025ee45 2024-12-12)`, `rustc 1.85.0-nightly (21fe748be 2024-12-11)` works correctly.

### Meta

`rustc --version --verbose`:
```
rustc 1.88.0-nightly (b4c8b0c3f 2025-04-25)
binary: rustc
commit-hash: b4c8b0c3f0533bb342a4873ff59bdad3883ab8e3
commit-date: 2025-04-25
host: x86_64-unknown-linux-gnu
release: 1.88.0-nightly
LLVM version: 20.1.2
```

### PR DESCRIPTION
**Pull request by compiler-errors**
`Instance::expect_resolve` ensures that we're actually going from trait item -> impl item.

Fixes #140373

### CODE REVIEW

File: tests/ui/asm/naked-asm-mono-sym-fn.rs [hunk 1]
```diff
@@ -0,0 +1,35 @@
+// Regression test for <https://github.com/rust-lang/rust/issues/140373>.
+// Test that we're properly monomorphizing sym args in naked asm blocks
+// that point to associated items.
+
+//@ edition: 2021
+//@ needs-asm-support
+//@ only-x86_64
+//@ build-pass
+
+trait T {
```
Comment (lcnr) [inline tests/ui/asm/naked-asm-mono-sym-fn.rs:10]: pls rename `T` to `Tr` or whatever

File: compiler/rustc_middle/src/ty/instance.rs [hunk 2]
```diff
@@ -426,7 +426,10 @@ impl<'tcx> fmt::Display for Instance<'tcx> {
 }
 
 impl<'tcx> Instance<'tcx> {
-    pub fn new(def_id: DefId, args: GenericArgsRef<'tcx>) -> Instance<'tcx> {
+    /// Creates a new [`InstanceKind::Item`] from the `def_id` and `args`. Note that this
+    /// does not resolve trait items to their corresponding impl items -- to do that, use
+    /// [`Instance::expect_resolve`] instead.
```
Comment (RalfJung) [inline compiler/rustc_middle/src/ty/instance.rs:431]: As a compiler dev I would be rather clueless about whether I want to "resolve trait items to their corresponding impl items" or not -- I'm not even sure what exactly this means. So I'm afraid this comment isn't very helpful in terms of giving guidance to when I should use which of these functions.

Comment (compiler-errors) [reply compiler/rustc_middle/src/ty/instance.rs:431]: Do you have a suggestion for a new comment? Because just saying it is not very helpful as a comment is... well, also not very actionable 😆

Comment (compiler-errors) [reply compiler/rustc_middle/src/ty/instance.rs:431]: See the comment on https://doc.rust-lang.org/nightly/nightly-rustc/rustc_middle/ty/struct.Instance.html#method.try_resolve to understand what it means to resolve a trait item to its corresponding impl item.

Comment (RalfJung) [reply compiler/rustc_middle/src/ty/instance.rs:431]: > Do you have a suggestion for a new comment? Because just saying it is not very helpful as a comment is... well, also not very actionable 😆

I'm not sure how to suggest a better comment without having any clue about when this function should and should not be used.^^ You made const-eval use `new_raw` so I guess it is the right thing to use for anything I encountered in the compiler so far...

Comment (compiler-errors) [reply compiler/rustc_middle/src/ty/instance.rs:431]: > You made const-eval use new_raw so I guess it is the right thing to use for anything I encountered in the compiler so far...

CTFE uses `Instance::expect_resolve` all throughout, so that's definitely not true. The only usage sites I've touched are the ones that attempt to directly evaluate const bodies.

Comment (RalfJung) [reply compiler/rustc_middle/src/ty/instance.rs:431]: > I guess what matters is: "Are you certain that the body of `def_id` is the actual body you want to use. This is not the case for trait methods or functions we may stub out with a separate implementation"

That sounds helpful. Are there docs for the concept of "resolve" that we can link to? I guess it refers to going from a trait-method pair to the actual impl? Also, is there ever a downside to using `resolve` when we don't have to?

`new_raw` is scary as a name so now I feel like every use of this function needs a comment justifying it, but I'm not sure what the justification looks like in the interpreter.

File: compiler/rustc_middle/src/ty/instance.rs [hunk 3]
```diff
@@ -426,7 +426,15 @@ impl<'tcx> fmt::Display for Instance<'tcx> {
...
 impl<'tcx> Instance<'tcx> {
-    pub fn new(def_id: DefId, args: GenericArgsRef<'tcx>) -> Instance<'tcx> {
+    /// Creates a new [`InstanceKind::Item`] from the `def_id` and `args`.
+    ///
+    /// Note that this item corresponds to the body of `def_id` directly, which
+    /// likely does not make sense for trait items which need to be resolved to an
+    /// implementation, and which may not even have a body themselves. Usages of
+    /// this function should probably use [`Instance::expect_resolve`], or if run
+    /// in a polymorphic environment or within a lint (that may encounter ambiguity)
+    /// [`Instance::expect_resolve`] instead.
```
Comment (RalfJung) [inline compiler/rustc_middle/src/ty/instance.rs:436]:
```suggestion
    /// implementation, and which may not even have a body themselves. Instead of
    /// this function, you probably should use use [`Instance::expect_resolve`], or if run
    /// in a polymorphic environment or within a lint (that may encounter ambiguity)
    /// [`Instance::expect_resolve`] instead.
```
Also, this recommends `expect_resolve` twice now...

**Comment by ChrisDenton** [comment]
failed in rollup https://github.com/rust-lang/rust/pull/140411#issuecomment-2836791987

@bors r-
