### PR TITLE
Fix most ui tests on emscripten target

### LINKED ISSUE #131666: emcc and wasm-ld can't link our ui tests for `wasm32-unknown-emscripten`?
Perhaps I'm holding it wrong? About a fifth of the rustc UI test suite to fail on wasm32-unknown-emscripten when trying to run `./x.py test --target wasm32-unknown-emscripten`. In all cases we get an error like this:

```

error: linking with `emcc` failed: exit status: 1
   |
   = note: "emcc" "-s" "EXPORTED_FUNCTIONS=[\"_main\"]" "/home/jubilee/rust/rustc/build/x86_64-unknown-linux-gnu/test/ui/array-slice-vec/vector-no-ann-2/a.vector_no_ann_2.86c223511763191d-cgu.0.rcgu.o" "/home/jubilee/rust/rustc/build/x86_64-unknown-linux-gnu/test/ui/array-slice-vec/vector-no-ann-2/a.1t3t8w654vioaffrv2c1spxg2.rcgu.o" "/home/jubilee/rust/rustc/build/x86_64-unknown-linux-gnu/stage1/lib/rustlib/wasm32-unknown-emscripten/lib/libstd-6499696fb99a9577.rlib" "/home/jubilee/rust/rustc/build/x86_64-unknown-linux-gnu/stage1/lib/rustlib/wasm32-unknown-emscripten/lib/libpanic_unwind-0c3cc3cd32c2b4b3.rlib" "/home/jubilee/rust/rustc/build/x86_64-unknown-linux-gnu/stage1/lib/rustlib/wasm32-unknown-emscripten/lib/libmemchr-e7a6f41ef20fcc54.rlib" "/home/jubilee/rust/rustc/build/x86_64-unknown-linux-gnu/stage1/lib/rustlib/wasm32-unknown-emscripten/lib/librustc_demangle-d35e921e53f26e9e.rlib" "/home/jubilee/rust/rustc/build/x86_64-unknown-linux-gnu/stage1/lib/rustlib/wasm32-unknown-emscripten/lib/libstd_detect-a7a77daaad248f5e.rlib" "/home/jubilee/rust/rustc/build/x86_64-unknown-linux-gnu/stage1/lib/rustlib/wasm32-unknown-emscripten/lib/libhashbrown-e0e54cdb8e75fbf2.rlib" "/home/jubilee/rust/rustc/build/x86_64-unknown-linux-gnu/stage1/lib/rustlib/wasm32-unknown-emscripten/lib/librustc_std_workspace_alloc-9f19c89c353a136f.rlib" "/home/jubilee/rust/rustc/build/x86_64-unknown-linux-gnu/stage1/lib/rustlib/wasm32-unknown-emscripten/lib/libminiz_oxide-ffd1c27bbffc4236.rlib" "/home/jubilee/rust/rustc/build/x86_64-unknown-linux-gnu/stage1/lib/rustlib/wasm32-unknown-emscripten/lib/libadler-4452dbe2564d6cb8.rlib" "/home/jubilee/rust/rustc/build/x86_64-unknown-linux-gnu/stage1/lib/rustlib/wasm32-unknown-emscripten/lib/libunwind-684258862f7c352d.rlib" "/home/jubilee/rust/rustc/build/x86_64-unknown-linux-gnu/stage1/lib/rustlib/wasm32-unknown-emscripten/lib/libcfg_if-0f4ad8f59845e58a.rlib" "/home/jubilee/rust/rustc/build/x86_64-unknown-linux-gnu/stage1/lib/rustlib/wasm32-unknown-emscripten/lib/liblibc-2be890f74433405e.rlib" "/home/jubilee/rust/rustc/build/x86_64-unknown-linux-gnu/stage1/lib/rustlib/wasm32-unknown-emscripten/lib/liballoc-48460e2c05fc2c62.rlib" "/home/jubilee/rust/rustc/build/x86_64-unknown-linux-gnu/stage1/lib/rustlib/wasm32-unknown-emscripten/lib/librustc_std_workspace_core-841075126ac27f05.rlib" "/home/jubilee/rust/rustc/build/x86_64-unknown-linux-gnu/stage1/lib/rustlib/wasm32-unknown-emscripten/lib/libcore-ee3c0a07d74de06f.rlib" "/home/jubilee/rust/rustc/build/x86_64-unknown-linux-gnu/stage1/lib/rustlib/wasm32-unknown-emscripten/lib/libcompiler_builtins-c113413e38c4b290.rlib" "-l" "c" "-B/home/jubilee/rust/rustc/build/x86_64-unknown-linux-gnu/stage1/lib/rustlib/x86_64-unknown-linux-gnu/bin/gcc-ld" "--target=wasm32-unknown-emscripten" "-s" "DISABLE_EXCEPTION_CATCHING=0" "-L" "/home/jubilee/rust/rustc/build/wasm32-unknown-emscripten/native/rust-test-helpers" "-L" "/home/jubilee/rust/rustc/build/x86_64-unknown-linux-gnu/test/ui/array-slice-vec/vector-no-ann-2/auxiliary" "-L" "/home/jubilee/rust/rustc/build/x86_64-unknown-linux-gnu/stage1/lib/rustlib/wasm32-unknown-emscripten/lib/self-contained" "-o" "/home/jubilee/rust/rustc/build/x86_64-unknown-linux-gnu/test/ui/array-slice-vec/vector-no-ann-2/a.wasm" "-O2" "-g0" "-sABORTING_MALLOC=0"
   = note: wasm-ld: error: /home/jubilee/.emscripten_cache/sysroot/lib/wasm32-emscripten/libstandalonewasm.a(__main_void.o): undefined symbol: main

```

### PR DESCRIPTION
**Pull request by hoodmane**
To fix the linker errors, we need to set the output extension to `.js` instead of `.wasm`. Setting the output to a `.wasm` file puts Emscripten into standalone mode which is effectively a distinct target. We need to set the runner to be `node` as well.

This fixes most of the ui tests. I fixed 4 additional tests with simple problems:

- `intrinsics/intrinsic-alignment.rs` -- Two `#[cfg]` macros match for Emscripten so we got duplicate definition
- `structs-enums/rec-align-u64.rs` -- same problem
- `issues/issue-12699.rs` -- hangs so I disabled it
- `process/process-sigpipe.rs` -- Not expected to work on Emscripten so I disabled it

Resolves #131666.

There are 7 more failing tests. I'll try to investigate more and see if I can fix them or at least understand why they happen.

- abi/numbers-arithmetic/return-float.rs (problem with [wasm treatment of noncanonical floats](https://webassembly.github.io/spec/core/exec/numerics.html#nan-propagation)?)
- async-await/issue-60709.rs -- linker error related to memcpy. Possible Emscripten bug?
- backtrace/dylib-dep.rs -- Says "Not supported"
- backtrace/line-tables-only.rs -- Says "Not supported"
- no_std/no-std-unwind-binary.rs -- compiler says `error: lang item required, but not found: eh_catch_typeinfo`
- structs-enums/enum-rec/issue-17431-6.rs -- One of the two compiler errors is missing
- test-attrs/test-passed.rs

    r?workingjubilee r?jieyouxu

### CODE REVIEW

**Comment by workingjubilee** [comment]
> This fixes most of the ui tests. I fixed 4 additional tests with simple problems:

Nice!

> There are 7 more failing tests. I'll try to investigate more and see if I can fix them or at least understand why they happen.

No requirement that you fix them in this PR. I expect the backtrace tests may get an ignore for emscripten. It sounds like the only one of particular interest is async-await/issue-60709.rs

File: tests/ui/issues/issue-12699.rs [hunk 1]
```diff
@@ -1,9 +1,16 @@
...
 
+#[cfg(not(target_os = "emscripten"))]
 fn main() {
     thread::sleep_ms(250);
 }
+
+#[cfg(target_os = "emscripten")]
+fn main() {
+    // Test hangs on emscripten, let it go.
+}
```
Comment (jieyouxu) [inline tests/ui/issues/issue-12699.rs:16]: Suggestion: can this be `//@ ignore-emscripten` instead (if that doesn't exist, could you please add it to compiletest as I imagine other tests that need to be skipped on emscripten could benefit from it)? Otherwise, the test will appear to have "passed" even though it's actually ignored. Once you do so, please leave a FIXME next to the `//@ ignore-emscripten`:

```rs
//@ ignore-emscripten
// FIXME: test hangs on emscripten
```

File: tests/ui/issues/issue-12699.rs
Comment (jieyouxu) [inline tests/ui/issues/issue-12699.rs:1]: Suggestion: please also rename this test to something more meaningful (like `thread-sleep`) and move it to a more meaningful subdirectory.

File: tests/ui/process/process-sigpipe.rs [hunk 2]
```diff
@@ -35,7 +35,7 @@ fn main() {
     assert!(output.stderr.len() == 0);
 }
 
-#[cfg(not(unix))]
+#[cfg(any(not(unix), target_os = "emscripten"))]
 fn main() {
     // Not worried about signal masks on other platforms
 }
```
Comment (jieyouxu) [inline tests/ui/process/process-sigpipe.rs:41]: Suggestion: this should use both:

1. `//@ only-unix`, and
2. `//@ ignore-emscripten`

So they get properly registered as ignored instead of stubbing out what's being tested. Please also leave a remark of why the `only-*` and `ignore-emscripten` are needed.

File: tests/ui/structs-enums/rec-align-u64.rs [hunk 3]
```diff
@@ -77,7 +77,7 @@ mod m {
     }
 }
 
-#[cfg(target_family = "wasm")]
+#[cfg(all(target_family = "wasm", not(target_os = "emscripten")))]
```
Comment (jieyouxu) [inline tests/ui/structs-enums/rec-align-u64.rs:80]: Suggestion: please add a brief remark for why this is special on `empscripten` (FIXME of unknown root cause is fine).

File: tests/ui/intrinsics/intrinsic-alignment.rs [hunk 4]
```diff
@@ -65,7 +65,7 @@ mod m {
     }
 }
 
-#[cfg(target_family = "wasm")]
+#[cfg(all(target_family = "wasm", not(target_os = "emscripten")))]
```
Comment (jieyouxu) [inline tests/ui/intrinsics/intrinsic-alignment.rs:68]: Suggestion: please leave a remark on why this specifically skips emscripten.

**Review by jieyouxu — COMMENTED** [review]
Thanks for the PR. I left some suggestions. The other failing tests are fine (i.e. not needed to be addressed in this PR). I would encourage opening a tracking issue for the remaining failing ui tests on emscripten targets for tracking purposes so they aren't lost when this PR is merged.

**Review by jieyouxu — APPROVED** [review]
Thanks, this LGTM now. I'll approve once PR CI is green.

**Comment by hoodmane** [comment]
Thanks for the review @jieyouxu!
