### PR TITLE
Explicitly build proc macro test with panic=unwind

### LINKED ISSUE #135223: Test crate-type-flag.rs#proc_dash_macro is failing
`tests/ui/invalid-compile-flags/crate-type-flag.rs#proc_dash_macro` is failing as of [this commit](https://github.com/rust-lang/rust/pull/134906/commits/92e8e84e7d85a17e8c32a9c6874fa5e655c16872), and seems to have been disabled with [this commit](https://github.com/rust-lang/rust/pull/135125/commits/918acafef682d0d0ca30b47de4768210417ff362).

The Fuchsia team (fuchsia.dev) runs this test suite before rolling the latest rust compiler into our codebase, but the above method of disabling the test does not seems to disable the test for Fuchsia. **Can we disable this test in a way that would disable it for Fuchsia as well?**

### PR DESCRIPTION
**Pull request by erickt**
Fuchsia explicitly builds rust and all rust targets with `-C panic=abort` to minimize code generation size. However, when compiling a proc-macro with this setting it can cause a warning to be emitted, which breaks `tests/ui/invalid-compile-flags/crate-type-flag.rs`. This hasn't been a problem in the past for us since we compile our proc macros on host, rather than inside Fuchsia.

This attempts to fix the issue by explicitly requiring that we're using the unwinder when compiling this test to avoid the warning being emitted.

Fixes #135223

### CODE REVIEW

File: tests/ui/invalid-compile-flags/crate-type-flag.rs [hunk 1]
```diff
@@ -30,7 +30,7 @@
 //@[bin] check-pass
 
 //@[proc_dash_macro] ignore-wasm (proc-macro is not supported)
-//@[proc_dash_macro] compile-flags: --crate-type=proc-macro
+//@[proc_dash_macro] compile-flags: --crate-type=proc-macro -C panic=unwind
```
Comment (bjorn3) [inline tests/ui/invalid-compile-flags/crate-type-flag.rs:33]: Mind adding `//@[proc_dash_macro] needs-unwind` to ignore this test when panic=unwind is not supported by the target or codegen backend?

Comment (jieyouxu) [reply tests/ui/invalid-compile-flags/crate-type-flag.rs:33]: Yeah, please just add //@ needs-unwind to check if that is sufficient, the -C panic=unwind is entirely irrelevant to this test and is a distraction. Alternatively, just ignore-fuchsia.

**Comment by erickt** [comment]
Thanks for the suggestions! That's much better than manually specifying `-C panic=unwind`. I updated it, and also removed the line from cg_clif.

**Comment by jieyouxu** [comment]
Thanks!
@bors r+ rollup

**Comment by jieyouxu** [comment]
FTR, this test *actually* wants a proper supports-crate-type directive i.e. https://github.com/rust-lang/rust/issues/132309, I had a bunch of these needs-* directive as a poor man's emulation to that effect.
