### PR TITLE
Fix mod_inv termination for the last iteration

### LINKED ISSUE #103361: `align_offset` infinite loop
I tried this code: [(Playground)](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=7d6bab35469fb1da274bb283e3cc1b7a)

```rust
fn main() {
    struct HugeSize([u8; (1 << 47) - 1]);
    let _ = ((1usize << 47) as *const HugeSize).align_offset(1 << 47);
}
```

I expected to see this happen: The program terminates.

Instead, this happened: The program loops indefinitely.

I encountered this while working on https://github.com/rust-lang/rust/pull/102795

### Meta

`rustc --version --verbose`:
```
rustc 1.66.0-nightly (dcb376115 2022-10-20)
binary: rustc
commit-hash: dcb376115066d111dbf5f13d5ac2a2dbe8c12add
commit-date: 2022-10-20
host: x86_64-unknown-linux-gnu
release: 1.66.0-nightly
LLVM version: 15.0.2
```

### PR DESCRIPTION
**Pull request by nagisa**
On usize=u64 platforms, the 4th iteration would overflow the `mod_gate` back to 0. Similarly for usize=u32 platforms, the 3rd iteration would overflow much the same way.

I tested various approaches to resolving this, including approaches with `saturating_mul` and `widening_mul` to a double usize. Turns out LLVM likes `mul_with_overflow` the best. In fact now, that LLVM can see the iteration count is limited, it will happily unroll the loop into a nice linear sequence.

You will also notice that the code around the loop got simplified somewhat. Now that LLVM is handling the loop nicely, there isn’t any more reasons to manually unroll the first iteration out of the loop (though looking at the code today I’m not sure all that complexity was necessary in the first place).

Fixes #103361

### CODE REVIEW

File: library/core/src/ptr/mod.rs [hunk 1]
```diff
@@ -1592,36 +1592,38 @@ pub(crate) unsafe fn align_offset<T: Sized>(p: *const T, a: usize) -> usize {
         const INV_TABLE_MOD_16: [u8; 8] = [1, 11, 13, 7, 9, 3, 5, 15];
         /// Modulo for which the `INV_TABLE_MOD_16` is intended.
         const INV_TABLE_MOD: usize = 16;
-        /// INV_TABLE_MOD²
-        const INV_TABLE_MOD_SQUARED: usize = INV_TABLE_MOD * INV_TABLE_MOD;
 
-        let table_inverse = INV_TABLE_MOD_16[(x & (INV_TABLE_MOD - 1)) >> 1] as usize;
         // SAFETY: `m` is required to be a power-of-two, hence non-zero.
         let m_minus_one = unsafe { unchecked_sub(m, 1) };
```
Comment (scottmcm) [inline library/core/src/ptr/mod.rs:1597]: Sadly `unchecked` is useless here today -- LLVM turns `sub nuw %m, 1` into `add %m, -1` during normalization :(

(Doesn't need to change here, though.  I'm just sad about https://github.com/llvm/llvm-project/issues/53377.)

**Comment by scottmcm** [comment]
Thanks!  Really nice to hear that LLVM is smart enough to realize that this lets LLVM fully unroll it.

@bors r+

File: library/core/tests/ptr.rs [hunk 2]
```diff
@@ -455,6 +455,18 @@ fn align_offset_various_strides() {
...
+#[test]
+fn align_offset_issue_103361() {
+    #[cfg(target_pointer_width = "64")]
+    const SIZE: usize = 1 << 47;
+    #[cfg(target_pointer_width = "32")]
+    const SIZE: usize = 1 << 30;
+    #[cfg(target_pointer_width = "16")]
+    const SIZE: usize = 1 << 13;
+    struct HugeSize([u8; SIZE - 1]);
+    let _ = (SIZE as *const HugeSize).align_offset(SIZE);
```
Comment (RalfJung) [inline library/core/tests/ptr.rs:467]: We usually prefer the strict provenance APIs in libcore -- https://github.com/rust-lang/rust/pull/104632

Note sure if the lint against int2ptr casts ever got implemented? If yes we should probably enable it here.

Comment (nagisa) [reply library/core/tests/ptr.rs:467]: Ah, I basically just copy-pasted over the reproducer from the issue…
