### PR TITLE
Prevent spurious `unreachable pattern` lints

### LINKED ISSUE #78057: Incorrect "unreachable pattern" warning with opaque constant
I tried this code ([playground link](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=81b06fa562674b849e41115b8309e43f)):

```rust
#[derive(PartialEq)]
struct Opaque(i32);

impl Eq for Opaque {}

const FOO: Opaque = Opaque(42);

fn foo() {
    match Opaque(0) {
        FOO => {},
        _ => {}
    }
}
```

This emits an "unreachable pattern" warning on the second branch of the match, even though it is clearly reachable. This gives the same warning for current nightly and beta, as well as stable 1.47.0 and 1.40.0.

This was uncovered while discussing https://github.com/rust-lang/rust/pull/77390.

### Meta

`rustc --version --verbose`:
```
rustc 1.47.0 (18bf6b4f0 2020-10-07)
binary: rustc
commit-hash: 18bf6b4f01a6feaf7259ba7cdae58031af1b7b39
commit-date: 2020-10-07
host: x86_64-unknown-linux-gnu
release: 1.47.0
LLVM version: 11.0
```

### PR DESCRIPTION
**Pull request by oli-obk**
But it means we'll get more `non-exhaustive` patterns

fixes https://github.com/rust-lang/rust/issues/78057

r? @Nadrieril @RalfJung

### CODE REVIEW

**Comment by RalfJung** [comment]
Hm, that's not clearly better, is it? Just replacing one spurious error by another. I guess there is no way around an 'Error' variant.

**Comment by oli-obk** [comment]
An error variant will be equivalent to skipping `non-exhaustive` patterns errors if any patterns return true for `has_error` (which such an error constant will do).

I can try adding this here

**Comment by Nadrieril** [comment]
> An error variant will be equivalent to skipping `non-exhaustive` patterns errors if any patterns return true for `has_error` (which such an error constant will do).
> 
> I can try adding this here

I'd like that, that feels cleanest to me

File: tests/ui/pattern/usefulness/consts-opaque.rs [hunk 1]
```diff
@@ -51,56 +49,47 @@ fn main() {
...
 
     match BAZ {
         BAZ => {}
         //~^ ERROR must be annotated with `#[derive(PartialEq, Eq)]`
-        Baz::Baz2 => {} // should not be emitting unreachable warning
-        //~^ ERROR unreachable pattern
-        _ => {} // should not be emitting unreachable warning
-        //~^ ERROR unreachable pattern
+        Baz::Baz2 => {}
+        _ => {}
```
Comment (RalfJung) [inline tests/ui/pattern/usefulness/consts-opaque.rs:92]: This one actually is unreachable, right? BAZ is Baz1, and then we also cover Baz2, and then all variants are covered.

But I guess it's fine not to also emit that error here, seems better than emitting too many errors in other cases.

File: compiler/rustc_mir_build/src/thir/pattern/check_match.rs [hunk 2]
```diff
@@ -682,6 +682,12 @@ fn non_exhaustive_match<'p, 'tcx>(
     arms: &[ArmId],
     expr_span: Span,
 ) -> ErrorGuaranteed {
+    for &arm in arms {
+        if let Err(err) = thir[arm].pattern.error_reported() {
```
[the remark this answers is not in the document]
Comment (oli-obk) [reply compiler/rustc_mir_build/src/thir/pattern/check_match.rs:686]: this will also go into constants and check if they have an error flag.

[the remark this answers is not in the document]
Comment (RalfJung) [reply compiler/rustc_mir_build/src/thir/pattern/check_match.rs:686]: But where do we set the error flag when a constant doesn't `derive(PartialEq, Eq)`?

File: compiler/rustc_mir_build/src/thir/pattern/const_to_pat.rs [hunk 3]
```diff
@@ -191,8 +191,15 @@ impl<'tcx> ConstToPat<'tcx> {
                         }
                     } else {
                         let err = InvalidPattern { span: self.span, non_sm_ty };
-                        self.tcx().sess.emit_err(err);
-                        return Box::new(Pat { span: self.span, ty: cv.ty(), kind: PatKind::Wild });
+                        let e = self.tcx().sess.emit_err(err);
+                        let kind = PatKind::Constant {
+                            value: mir::ConstantKind::Ty(ty::Const::new_error(
```
Comment (RalfJung) [inline compiler/rustc_mir_build/src/thir/pattern/const_to_pat.rs:196]: Oh I had missed the `new_error` here, that explains my confusion in the other thread.

File: compiler/rustc_mir_build/src/thir/pattern/check_match.rs (hunk 2 above)
[the remark this answers is not in the document]
Comment (RalfJung) [reply compiler/rustc_mir_build/src/thir/pattern/check_match.rs:686]: Oh sorry, I had missed the `ty::Const::new_error`.

File: tests/ui/pattern/usefulness/consts-opaque.rs (hunk 1 above)
Comment (Nadrieril) [reply tests/ui/pattern/usefulness/consts-opaque.rs:92]: That would mean using structural match semantics on `Baz`, which is the whole point we're trying to avoid, right? I think treating `BAZ` as opaque is correct here

Comment (RalfJung) [reply tests/ui/pattern/usefulness/consts-opaque.rs:92]: Ah, that's fair... I forgot that we require PartialEq *and* Eq to be derived. Yeah that makes sense. This will likely change when we clean that up but that's for the future.

File: compiler/rustc_mir_build/src/thir/pattern/const_to_pat.rs [hunk 4]
```diff
@@ -180,23 +180,26 @@ impl<'tcx> ConstToPat<'tcx> {
...
+                                .emit_fatal(TypeNotStructural { span: self.span, non_sm_ty })
                         }
                     } else {
                         let err = InvalidPattern { span: self.span, non_sm_ty };
-                        self.tcx().sess.emit_err(err);
-                    }
+                        self.tcx().sess.emit_err(err)
+                    };
                     // All branches above emitted an error. Don't print any more lints.
                     // The pattern we return is irrelevant since we errored.
```
Comment (Nadrieril) [inline compiler/rustc_mir_build/src/thir/pattern/const_to_pat.rs:198]:
```suggestion
                    // We errored. Signal that in the pattern, so that follow up errors can be silenced.
```

File: tests/ui/const-generics/generic_const_exprs/typeid-equality-by-subtyping.stderr [hunk 5]
```diff
@@ -7,5 +7,17 @@ LL |         WHAT_A_TYPE => 0,
...
+   |
+LL |         WHAT_A_TYPE => 0,
+   |         ^^^^^^^^^^^
+   |
+   = note: `TypeId` cannot be compared in compile-time, and therefore cannot be used in `match`es
+note: impl defined here, but it is not `const`
+  --> $SRC_DIR/core/src/any.rs:LL:COL
+   = note: calls in constant functions are limited to constant functions, tuple structs and tuple variants
+
+error: aborting due to 2 previous errors
```
Comment (Nadrieril) [inline tests/ui/const-generics/generic_const_exprs/typeid-equality-by-subtyping.stderr:21]: Where is this error coming from? I guess it was there before but got skipped because of previous errors?

File: tests/ui/pattern/usefulness/consts-opaque.rs (hunk 1 above)
Comment (Nadrieril) [reply tests/ui/pattern/usefulness/consts-opaque.rs:92]: Looking forward to the cleanups :D

**Comment by Nadrieril** [comment]
Oops I missed that I got assigned :smile: 

LGTM! The behavior is what I hoped, and const-to-pat looks good. Just the error propagation machinery is out of my expertise. r=me if you're confident about that bit, unless @RalfJung has more comments.

This will fix https://github.com/rust-lang/rust/issues/78057

**Comment by Nadrieril** [comment]
I found another case of spurious such lints in https://github.com/rust-lang/rust/pull/116623 (in the tests I added). Whichever PR gets merged first, the other can add a fix.

File: tests/ui/const-generics/generic_const_exprs/typeid-equality-by-subtyping.stderr (hunk 5 above)
Comment (oli-obk) [reply tests/ui/const-generics/generic_const_exprs/typeid-equality-by-subtyping.stderr:21]: oh yea. We're actually generating a `PartialEq` call for it now, because we have an actual pattern now instead of a wildcard, which has no additional code.

**Comment by Nadrieril** [comment]
Looks like the perf drop exactly mirrors the [surprising perf gain](https://github.com/rust-lang/rust/pull/116623#issuecomment-1757711735) I got in my previous PR
