### PR TITLE
On type mismatch involving associated type, suggest constraint

### LINKED ISSUE #71035: Improve compiler error on associated types
If you have a variable with type `impl TryStream<Ok=T, Error=E>` and want to use it as a `impl Stream<Item=Result<T,E>>`, the compiler complains.
The  compiler does not take you by the hand and helps you with helpful hints.

I tried (roughly) this code: (EDIT: find a self-contained example [here](https://github.com/rust-lang/rust/issues/71035#issuecomment-612627037))

```rust
use bytes;
use std::io;
use futures::channel::mpsc;
use async_std::task;

//pub fn my_rx(sock: std::sync::Arc<UdpSocket>) -> impl futures::Stream<Item=Result<(bytes::Bytes, std::net::SocketAddr), std::io::Error>> { // WORKS
pub fn my_rx(sock: std::sync::Arc<UdpSocket>) -> impl futures::TryStream<Ok=(bytes::Bytes, std::net::SocketAddr), Error=std::io::Error> { // ERROR
    ...
}

fn main() {
    let inet_rx = my_rx();
    let (tx1, inet_rx1) = mpsc::unbounded();
    let (tx2, inet_rx2) = mpsc::unbounded();
    let mut tx = tx1.fanout(tx2).sink_map_err(|_| io::Error::new(io::ErrorKind::Other, "Send Error"));
    let foo = inet_rx.forward(tx);
    let _ = task::spawn(foo);
}
```

I expected to see this happen:
I would like the compiler to tell me that that that while there exists an implementation of `TryStream<Ok=T, Error=E>` as `Stream<Result<T,E>>`, there might exist other implementations and therefore this code is not accepted. Using `Stream<Result<T,E>>` instead of `TryStream<Ok=T, Error=E>` would solve the error.

Instead, this happened:
There are no hints by the compiler.

### Meta
`rustc --version --verbose`:
```
rustc 1.41.0-nightly (6d77e45f0 2019-12-04)
binary: rustc
commit-hash: 6d77e45f01079fe3d40180b3e256e414ab379f63
commit-date: 2019-12-04
host: x86_64-unknown-linux-gnu
release: 1.41.0-nightly
LLVM version: 9.0
```

### PR DESCRIPTION
**Pull request by estebank**
When an associated type is found when a specific type was expected, if
possible provide a structured suggestion constraining the associated
type in a bound.

```
error[E0271]: type mismatch resolving `<T as Foo>::Y == i32`
  --> $DIR/associated-types-multiple-types-one-trait.rs:13:5
   |
LL |     want_y(t);
   |     ^^^^^^ expected `i32`, found associated type
...
LL | fn want_y<T:Foo<Y=i32>>(t: &T) { }
   |                 ----- required by this bound in `want_y`
   |
   = note:         expected type `i32`
           found associated type `<T as Foo>::Y`
help: consider constraining the associated type `<T as Foo>::Y` to `i32`
   |
LL | fn have_x_want_y<T:Foo<X=u32, Y = i32>>(t: &T)
   |                             ^^^^^^^^^
```

```
error[E0308]: mismatched types
  --> $DIR/trait-with-missing-associated-type-restriction.rs:12:9
   |
LL |     qux(x.func())
   |         ^^^^^^^^ expected `usize`, found associated type
   |
   = note:         expected type `usize`
           found associated type `<impl Trait as Trait>::A`
help: consider constraining the associated type `<impl Trait as Trait>::A` to `usize`
   |
LL | fn foo(x: impl Trait<A = usize>) {
   |                     ^^^^^^^^^^
```

Fix #71035. Related to #70908.

### CODE REVIEW

File: src/librustc_middle/ty/error.rs [hunk 1]
```diff
@@ -492,4 +505,115 @@ impl Trait for X {
...
+                            values,
+                            msg,
+                        ) {
+                            return true;
+                        }
+                    }
+                }
+                for param in hir_generics.params {
+                    if self.hir().opt_local_def_id(param.hir_id).map(|id| id.to_def_id())
+                        == Some(def_id)
```
Comment (estebank) [inline src/librustc_middle/ty/error.rs:561]: I would love it if we had a better way of doing this, but I guess this works 🤷.

File: src/test/ui/suggestions/trait-with-missing-associated-type-restriction-fixable.stderr [hunk 2]
```diff
@@ -0,0 +1,94 @@
...
+   |
+LL |         qux(x.func())
+   |             ^^^^^^^^ expected `usize`, found associated type
+   |
+   = note:         expected type `usize`
+           found associated type `<impl Trait as Trait>::A`
+help: consider constraining the associated type `<impl Trait as Trait>::A` to `usize`
+   |
+LL |     fn foo<'a, T: Trait + 'a>(&self, _: impl Trait, x: impl Trait<A = usize>, _: T) {
+   |                                                                  ^^^^^^^^^^^
```
Comment (estebank) [inline src/test/ui/suggestions/trait-with-missing-associated-type-restriction-fixable.stderr:12]: This was the case I wanted to tackle.

File: src/test/ui/specialization/specialization-default-types.stderr [hunk 3]
```diff
@@ -21,7 +21,7 @@ LL |     Example::generate(t)
    |
    = note:       expected struct `std::boxed::Box<T>`
            found associated type `<T as Example>::Output`
-   = note: consider constraining the associated type `<T as Example>::Output` to `std::boxed::Box<T>`
+   = help: consider constraining the associated type `<T as Example>::Output` to `std::boxed::Box<T>`
```
Comment (estebank) [inline src/test/ui/specialization/specialization-default-types.stderr:24]: We should eventually handle the case of `#![feature(specialization)]`, but I won't on this PR.

File: src/librustc_middle/ty/error.rs [hunk 4]
```diff
@@ -392,7 +392,10 @@ impl<'tcx> TyCtxt<'tcx> {
                     (ty::Param(_), ty::Projection(_)) | (ty::Projection(_), ty::Param(_)) => {
                         db.note("you might be missing a type parameter or trait bound");
                     }
-                    (ty::Param(p), _) | (_, ty::Param(p)) => {
+                    (ty::Param(p), ty::Dynamic(..))
+                    | (ty::Dynamic(..), ty::Param(p))
+                    | (ty::Param(p), ty::Opaque(..))
+                    | (ty::Opaque(..), ty::Param(p)) => {
```
Comment (Centril) [inline src/librustc_middle/ty/error.rs:398]:
```suggestion
                    (ty::Param(p), ty::Dynamic(..) | ty::Opaque(..))
                    | (ty::Dynamic(..) | ty::Opaque(..), ty::Param(p)) => {
```

Comment (estebank) [reply src/librustc_middle/ty/error.rs]: done

File: src/test/ui/associated-types/issue-26681.stderr [hunk 5]
```diff
@@ -6,7 +6,7 @@ LL |     const C: <Self::Fv as Foo>::Bar = 6665;
    |
    = note: expected associated type `<<Self as Baz>::Fv as Foo>::Bar`
                          found type `{integer}`
-   = note: consider constraining the associated type `<<Self as Baz>::Fv as Foo>::Bar` to `{integer}` or calling a method that returns `<<Self as Baz>::Fv as Foo>::Bar`
+   = help: consider constraining the associated type `<<Self as Baz>::Fv as Foo>::Bar` to `{integer}`
```
Comment (estebank) [inline src/test/ui/associated-types/issue-26681.stderr:9]: Complex projections keep the prior output.

File: src/test/ui/suggestions/trait-with-missing-associated-type-restriction.stderr [hunk 6]
```diff
@@ -0,0 +1,103 @@
...
+                         found type `{integer}`
+help: a method is available that returns `<T as Trait<i32>>::A`
+  --> $DIR/trait-with-missing-associated-type-restriction.rs:8:5
+   |
+LL |     fn func(&self) -> Self::A;
+   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^ consider calling `Trait::func`
+help: consider constraining the associated type `<T as Trait<i32>>::A` to `{integer}`
+   |
+LL | fn bar2<T: Trait<i32, A = {integer}>>(x: T) {
+   |                     ^^^^^^^^^^^^^^^
```
Comment (estebank) [inline src/test/ui/suggestions/trait-with-missing-associated-type-restriction.stderr:56]: For this suggestion to use `i32` instead of `{integer}` we need to run `resolve_vars_if_possible`, but that's not available in `rustc_middle` :-|

File: src/librustc_middle/ty/error.rs (hunk 1 above)
Comment (oli-obk) [reply src/librustc_middle/ty/error.rs:569]: if it occurs more often, we can introduce a helper for it.

Comment (oli-obk) [reply src/librustc_middle/ty/error.rs:569]: Maybe `LocalDefId` just needs to implement `PartialEq<DefId>` and vice versa?

File: src/librustc_middle/ty/error.rs [hunk 7]
```diff
@@ -513,4 +513,344 @@ impl Trait for X {
...
+                                }
+                            }
+                            _ => {}
+                        }
+                    }
+                }
+                _ => {}
+            }
+        }
+        if let ty::Opaque(def_id, _) = proj_ty.self_ty().kind {
```
Comment (oli-obk) [inline src/librustc_middle/ty/error.rs:757]: why is this done without a condition on `suggested`?

File: src/librustc_middle/ty/error.rs [hunk 8]
```diff
@@ -513,4 +513,344 @@ impl Trait for X {
...
+        proj_ty: &ty::ProjectionTy<'tcx>,
+        values: &ExpectedFound<Ty<'tcx>>,
+        body_owner_def_id: DefId,
+        cause_code: &ObligationCauseCode<'_>,
+    ) {
+        let msg = format!(
+            "consider constraining the associated type `{}` to `{}`",
+            values.expected, values.found
+        );
+        let mut suggested = false;
```
Comment (oli-obk) [inline src/librustc_middle/ty/error.rs:612]: modulo my comment about why opaque types don't check `suggested`, this flag is unnecessary and the function could just use early returns.

File: src/librustc_middle/ty/error.rs [hunk 9]
```diff
@@ -513,4 +513,344 @@ impl Trait for X {
...
+                })
+                | hir::Node::TraitItem(hir::TraitItem {
+                    kind: hir::TraitItemKind::Const(..) | hir::TraitItemKind::Type(..),
+                    ..
+                })
+                | hir::Node::ImplItem(hir::ImplItem {
+                    kind: hir::ImplItemKind::Const(..) | hir::ImplItemKind::TyAlias(..),
+                    ..
+                }),
+            ) => false,
```
Comment (oli-obk) [inline src/librustc_middle/ty/error.rs:637]: I'm not too happy about the above blacklist, it seems like we could easily regress this diagnostic without realizing it. A whitelist would be better I think.

File: src/librustc_middle/ty/error.rs [hunk 10]
```diff
@@ -513,4 +513,344 @@ impl Trait for X {
...
+            ObligationCauseCode::CompareImplMethodObligation { .. }
+                | ObligationCauseCode::CompareImplTypeObligation { .. }
+                | ObligationCauseCode::CompareImplConstObligation
+        );
+        let assoc = self.associated_item(proj_ty.item_def_id);
+        if !callable_scope || impl_comparison {
+            // We do not want to suggest calling functions when the reason of the
+            // type error is a comparison of an `impl` with its `trait` or when the
+            // scope is outside of a `Body`.
+        } else {
```
Comment (oli-obk) [inline src/librustc_middle/ty/error.rs:651]: this block and the other big `if` statement later in this function could become their own functions, making it easier to read this function.

File: src/librustc_middle/ty/error.rs [hunk 11]
```diff
@@ -513,4 +513,344 @@ impl Trait for X {
...
+                            db, ptr.span, assoc, ty, msg,
+                        )
+                    {
+                        return true;
+                    }
+                }
+                _ => {}
+            }
+        }
+        false
```
Comment (oli-obk) [inline src/librustc_middle/ty/error.rs:828]:
```suggestion
		bounds.iter().any(|bound| match bound {
                hir::GenericBound::Trait(ptr, hir::TraitBoundModifier::None) => {
                    // Relate the type param against `T` in `<A as T>::Foo`.
                    ptr.trait_ref.trait_def_id() == Some(trait_ref.def_id)
                        && self.constrain_associated_type_structured_suggestion(
                            db, ptr.span, assoc, ty, msg,
                        )
                }
                _ => false,
            })
```

File: src/test/ui/issues/issue-69306.stderr [hunk 12]
```diff
@@ -8,8 +8,6 @@ LL |     const C: S0<u8> = Self(0);
    |
    = note: expected type parameter `T`
                         found type `{integer}`
-   = help: type parameters must be constrained to match other types
```
Comment (oli-obk) [inline src/test/ui/issues/issue-69306.stderr:11]: maybe we should keep a `help` around that informs the user that a type parameter can never be equal to a concrete type, even if the caller would always choose that specific type?

Comment (estebank) [reply src/test/ui/issues/issue-69306.stderr:11]: I would prefer for us to detect these kind of cases proactively and give a more targeted error. In the case of

```rust
struct S0<T>(T);
impl<T> S0<T> {
    const C: S0<u8> = Self(0);

    fn foo() {
        Self(0);
    }
}
```

we should come up with a more extensive explanation of what `Self` resolves to, something closer to

```
error[E0308]: mismatched types
  --> $DIR/issue-69306.rs:5:28
   |
LL | impl<T> S0<T> {
   |      - this type parameter
LL |     const C: S0<u8> = Self(0);
   |                       ---- ^ expected type parameter `T`, found integer
   |                       |
   |                       expected `T` because of this
   |
   = note: expected type parameter `T`
                        found type `{integer}`
note: `Self` resolves to `S0<T>`, which doesn't match `S0<{integer}>` becaue it is more general
   |
LL |     const C: S0<u8> = Self(0);
   |                       ^^^^

error[E0308]: mismatched types
  --> $DIR/issue-69306.rs:5:28
   |
LL | impl<T> S0<T> {
   |      - this type parameter
LL |     const C: S0<u8> = Self(0);
   |              ------   ^^^^^^^ expected `u8`, found type parameter `T`
   |              |
   |              expected `u8` because of this
   |
   = note: expected type parameter `T`
                        found type `{integer}`
note: `Self` resolves to `S0<T>`, which doesn't match `S0<u8>` becaue it is more general
   |
LL |     const C: S0<u8> = Self(0);
   |                       ^^^^

error[E0308]: mismatched types
  --> $DIR/issue-69306.rs:10:14
   |
LL | impl<T> S0<T> {
   |      - this type parameter
...
LL |         Self(0);
   |              ^ expected type parameter `T`, found integer
   |
   = note: expected type parameter `T`
                        found type `{integer}`
```

File: src/librustc_middle/ty/error.rs (hunk 7 above)
Comment (estebank) [reply src/librustc_middle/ty/error.rs:759]: The logic for the suggestions was already mutually exclusive. Now with the change to early returns this shouldn't be ambiguous anymore.
