### PR TITLE
Replace tuple of infer vars for upvar_tys with single infer var

### LINKED ISSUE #4: Always make the "upvar types" a tuple of the actual upvar types (Parent issue#53488)
**Updated by nikomatsakis with current status:**

In https://github.com/rust-lang/rust/pull/69968, @eddyb landed the "first step" here of introducing a tuple into the upvar types. However, in current rustc, we create that tuple "eagerly", as soon as we create the closure type:

https://github.com/rust-lang/rust/blob/1a87c49e33d87955e28fa92a8d59a17264ac6044/src/librustc_typeck/check/closure.rs#L90-L103

The next step is to move that tuple creation "late", so that it occurs during the "upvar analysis" code, so somewhere around here:

https://github.com/rust-lang/rust/blob/1a87c49e33d87955e28fa92a8d59a17264ac6044/src/librustc_typeck/check/upvar.rs#L194-L202

The problem with *this* is that the current accessor, [`ClosureSubsts::upvar_tys`](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_middle/ty/struct.ClosureSubsts.html#method.upvar_tys), assumes that the upvar types are a tuple with known arity. Thus any calls to `upvar_tys` that occur before the upvar analysis code runs will ICE. 

Last time, we added an accessor `upvar_tuple_ty` that returned the *tuple itself* (or an unbound type variable), since it turned out that many of the calls to `upvar_tys` could be replaced by a call that operated on the tuple. Most notably, in the trait system, for example here:

https://github.com/rust-lang/rust/blob/1a87c49e33d87955e28fa92a8d59a17264ac6044/src/librustc_trait_selection/traits/select.rs#L2239-L2242

We changed this to yield the tuple always. The problem with *that* was that it was effecting the error messages, because the tuple was being introduced into the "backtrace" and we somehow never got things *quiite* right to remove it.

I still think that is perhaps the right approach, but there is an alternative we could try: we could get the tuple ty and check whether it's been "resolved" yet (via a call to [`self.infcx.shallow_resolve`](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_infer/infer/struct.InferCtxt.html#method.shallow_resolve)). If so, we can put each of its components as we do today, but if not, we can return `Ambiguous`, [as we do here](https://github.com/rust-lang/rust/blob/1a87c49e33d87955e28fa92a8d59a17264ac6044/src/librustc_trait_selection/traits/select.rs#L2249-L2254).

### PR DESCRIPTION
**Pull request by roxelo**
This commit allows us to decide the number of captures required after
completing capture ananysis, which is required as part of implementing
RFC-2229.

closes https://github.com/rust-lang/project-rfc-2229/issues/4
r? @nikomatsakis

### CODE REVIEW

File: compiler/rustc_trait_selection/src/traits/select/mod.rs [hunk 1]
```diff
@@ -1700,11 +1706,31 @@ impl<'cx, 'tcx> SelectionContext<'cx, 'tcx> {
                 tys.iter().map(|k| k.expect_ty()).collect()
             }
 
-            ty::Closure(_, ref substs) => substs.as_closure().upvar_tys().collect(),
+            ty::Closure(_, ref substs) => {
+                let ty = self.infcx.shallow_resolve(substs.as_closure().tupled_upvars_ty());
+                if let ty::Infer(ty::TyVar(_)) = ty.kind() {
```
Comment (nikomatsakis) [inline compiler/rustc_trait_selection/src/traits/select/mod.rs]: I think I would rather just return `vec![ty]` always

File: compiler/rustc_trait_selection/src/traits/select/mod.rs [hunk 2]
```diff
@@ -1700,11 +1706,31 @@ impl<'cx, 'tcx> SelectionContext<'cx, 'tcx> {
...
-                substs.as_generator().upvar_tys().chain(iter::once(witness)).collect()
+                let upvar_tys_resolved =
+                    self.infcx.shallow_resolve(substs.as_generator().tupled_upvars_ty());
+
+                if let ty::Infer(ty::TyVar(_)) = upvar_tys_resolved.kind() {
+                    // The inference variable will be replaced by a tuple once capture analysis
+                    // completes, if the tuple meets a bound, so do all the elements within it.
+                    let witness_resolved =
+                        self.infcx.shallow_resolve(substs.as_generator().witness());
+                    vec![upvar_tys_resolved, witness_resolved]
```
Comment (nikomatsakis) [inline compiler/rustc_trait_selection/src/traits/select/mod.rs]: As above, if we can just do the same thing every time, seems better

File: compiler/rustc_traits/src/dropck_outlives.rs [hunk 3]
```diff
@@ -210,12 +210,20 @@ fn dtorck_constraint_for_ty<'tcx>(
...
         })?,
 
-        ty::Closure(_, substs) => rustc_data_structures::stack::ensure_sufficient_stack(|| {
-            for ty in substs.as_closure().upvar_tys() {
-                dtorck_constraint_for_ty(tcx, span, for_ty, depth + 1, ty, constraints)?;
+        ty::Closure(_, substs) => {
+            if !substs.as_closure().is_valid() {
+                // By the time this code runs, all type variables ought to
+                // be fully resolved.
+                return Err(NoSolution);
```
Comment (nikomatsakis) [inline compiler/rustc_traits/src/dropck_outlives.rs:217]: It would I think be better to use `delay_span_bug` here

File: compiler/rustc_traits/src/dropck_outlives.rs [hunk 4]
```diff
@@ -241,6 +249,12 @@ fn dtorck_constraint_for_ty<'tcx>(
             // derived from lifetimes attached to the upvars and resume
             // argument, and we *do* incorporate those here.
 
+            if !substs.as_generator().is_valid() {
+                // By the time this code runs, all type variables ought to
+                // be fully resolved.
+                return Err(NoSolution);
```
Comment (nikomatsakis) [inline compiler/rustc_traits/src/dropck_outlives.rs:255]: Again, `delay_span_bug`

**Review by nikomatsakis — COMMENTED** [review]
This looks great -- I left some comments on how we could simplify, some of which I see now were outdated by later commits, but not all of them I think.

File: compiler/rustc_trait_selection/src/traits/select/mod.rs (hunk 1 above)
Comment (roxelo) [reply compiler/rustc_trait_selection/src/traits/select/mod.rs]: I think this is already been addressed

File: compiler/rustc_trait_selection/src/traits/select/mod.rs (hunk 2 above)
Comment (roxelo) [reply compiler/rustc_trait_selection/src/traits/select/mod.rs]: I think this has already been addressed

**Comment by arora-aman** [comment]
@nikomatsakis updated

**Review by nikomatsakis — APPROVED** [review]

**Review by nikomatsakis — APPROVED** [review]

**Comment by Mark-Simulacrum** [comment]
This appears to be a 3% [regression](https://perf.rust-lang.org/compare.html?start=19e1aac6ea9879c6d10eed7106b3bc883e5bf9a5&end=93deabce03dc10a80244f5da3e3819452744da2a&stat=instructions:u) on the wg-grammar benchmark, though wall times look like they're overall an improvement. Since this is appears to be a functional (not perf-related) change I am inclined to not do anything further here.
