### PR TITLE
Fix constant propagation for scalar pairs

### LINKED ISSUE #66339: ICE in const_prop.rs:633: 'index out of bounds: the len is 1 but the index is 1'
This code results in an ICE when compiling using `-Z mir-opt-level=3`.
```rust
trait Write {
    fn write();
}

impl Write for () {
    fn write() {
        let none = |_| { None };
        let _: Option<()> = none("blink");
    }
}
```

```
thread 'rustc' panicked at 'index out of bounds: the len is 1 but the index is 1', src/librustc_mir/transform/const_prop.rs:633:42
stack backtrace:
   0: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
   1: core::fmt::write
   2: std::io::Write::write_fmt
   3: std::panicking::default_hook::{{closure}}
   4: std::panicking::default_hook
   5: rustc_driver::report_ice
   6: std::panicking::rust_panic_with_hook
   7: std::panicking::continue_panic_fmt
   8: rust_begin_unwind
   9: core::panicking::panic_fmt
  10: core::panicking::panic_bounds_check
  11: <rustc_mir::transform::const_prop::ConstPropagator as rustc::mir::visit::MutVisitor>::visit_statement
  12: <rustc_mir::transform::const_prop::ConstProp as rustc_mir::transform::MirPass>::run_pass
  13: rustc_mir::transform::run_passes
  14: rustc_mir::transform::run_optimization_passes
  15: rustc_mir::transform::optimized_mir
  16: rustc::ty::query::<impl rustc::ty::query::config::QueryAccessors for rustc::ty::query::queries::optimized_mir>::compute
  17: rustc::dep_graph::graph::DepGraph::with_task_impl
  18: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt>::get_query
  19: rustc_mir::monomorphize::collector::collect_items_rec
  20: rustc_mir::monomorphize::collector::collect_crate_mono_items::{{closure}}
  21: rustc::util::common::time
  22: rustc_mir::monomorphize::collector::collect_crate_mono_items
  23: rustc::util::common::time
  24: rustc_mir::monomorphize::partitioning::collect_and_partition_mono_items
  25: rustc::ty::query::__query_compute::collect_and_partition_mono_items
  26: rustc::dep_graph::graph::DepGraph::with_task_impl
  27: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt>::get_query
  28: rustc_codegen_ssa::base::codegen_crate
  29: <rustc_codegen_llvm::LlvmCodegenBackend as rustc_codegen_utils::codegen_backend::CodegenBackend>::codegen_crate
  30: rustc_interface::passes::start_codegen::{{closure}}
  31: rustc_interface::passes::start_codegen
  32: rustc::ty::context::tls::enter_global
  33: rustc_interface::passes::BoxedGlobalCtxt::access::{{closure}}
  34: rustc_interface::passes::create_global_ctxt::{{closure}}
  35: rustc_interface::passes::BoxedGlobalCtxt::enter
  36: rustc_interface::queries::Query<T>::compute
  37: rustc_interface::queries::<impl rustc_interface::interface::Compiler>::ongoing_codegen
  38: rustc_interface::interface::run_compiler_in_existing_thread_pool
  39: std::thread::local::LocalKey<T>::with
  40: scoped_tls::ScopedKey<T>::set
  41: syntax::with_globals
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.40.0-nightly (3fc30d884 2019-11-10) running on x86_64-apple-darwin

note: compiler flags: -Z mir-opt-level=3 -C opt-level=3 --crate-type lib

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [optimized_mir] processing `<() as Write>::write`
#1 [collect_and_partition_mono_items] collect_and_partition_mono_items
end of query stack
```

### LINKED ISSUE #66971: Miscompilation of tuple arguments with mir-opt-level=2
This reduced testcase is getting miscompiled with `mir-opt-level=2`. I bisected it to #64890.

```rust
fn encode(this: ((), u8, u8)) {
    // this assert panics although this.2 is 0
    assert!(this.2 == 0);
}

fn emit() {
    encode(((), 0, 0));
}

fn emit_inc() -> Box<()> {
    emit();
    Box::new(())
}

fn main() {
    emit_inc();
}
```

Rust version:
```
rustc 1.41.0-nightly (4007d4ef2 2019-12-01)
binary: rustc
commit-hash: 4007d4ef26eab44bdabc2b7574d032152264d3ad
commit-date: 2019-12-01
host: x86_64-apple-darwin
release: 1.41.0-nightly
LLVM version: 9.0
```

### LINKED ISSUE #67019: ICE with mir-opt-level=2 in program with scalar pair value
```rust
fn test(this: ((u8, u8),)) {
    assert!((this.0).1 == 0);
}

fn main() {
    test(((1, 2),));
}
```

Build:

```
$ /home/omer/rust/rust/build/x86_64-unknown-linux-gnu/stage1/bin/rustc --edition 2018 test2.rs -Zmir-opt-level=2
```

ICE:

```
thread 'rustc' panicked at 'index out of bounds: the len is 1 but the index is 1', src/librustc_mir/transform/const_prop.rs:648:42
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.41.0-dev running on x86_64-unknown-linux-gnu

note: compiler flags: -Z mir-opt-level=2
```

### PR DESCRIPTION
**Pull request by osa1**
We now only propagate a scalar pair if the Rvalue is a tuple with two scalars. This for example avoids propagating a (u8, u8) value when Rvalue has type `((), u8, u8)` (see the regression test). While this is a correct thing to do, implementation is tricky and will be done later.

Fixes #66971
Fixes #66339
Fixes #67019

### CODE REVIEW

**Comment by osa1** [comment]
(fixed a long line)

File: src/librustc_mir/transform/const_prop.rs [hunk 1]
```diff
@@ -636,18 +643,40 @@ impl<'mir, 'tcx> ConstPropagator<'mir, 'tcx> {
...
+                        let mut aggregate_values = vec![];
+                        // Iterate fields, for zsts a zsg scalar, for others use the values from
+                        // the pair
+                        for i in 0 .. layout.fields.count() {
+                            let field_layout = layout.field(self, i).unwrap();
+                            debug!("field {} layout={:#?}", i, field_layout);
+                            let scalar = if field_layout.details.size == Size::ZERO {
+                                Scalar::zst()
+                            } else {
+                                pair_values.pop().unwrap()
```
Comment (tmiasko) [inline src/librustc_mir/transform/const_prop.rs]: I think there might be a need for an additional check that the field actually
has `Abi::Scalar` layout. Otherwise it could end up with an assignment between
`Scalar` and `ScalarPair` layouts, for example in something like `test(((1, 2),))`,
when propagating the value of the outermost tuple.

Comment (osa1) [reply src/librustc_mir/transform/const_prop.rs]: Amazing, your example uncovers another bug. I reported it as #67019.

I'll try to fix it in this PR too.

File: src/librustc_mir/transform/const_prop.rs [hunk 2]
```diff
@@ -636,18 +643,40 @@ impl<'mir, 'tcx> ConstPropagator<'mir, 'tcx> {
                     ScalarMaybeUndef::Scalar(one),
                     ScalarMaybeUndef::Scalar(two)
                 ) => {
-                    let ty = &value.layout.ty.kind;
+                    // Value represented as a pair, but we still want to generate zsts for rest of
+                    // the fields.
+                    let layout = &value.layout;
+                    debug!("replace_with_const: value layout={:#?}", layout);
```
Comment (wesleywiser) [inline src/librustc_mir/transform/const_prop.rs]: We should probably take these `debug!()` calls out.

File: src/librustc_mir/transform/const_prop.rs [hunk 3]
```diff
@@ -636,18 +643,40 @@ impl<'mir, 'tcx> ConstPropagator<'mir, 'tcx> {
...
+                    debug!("replace_with_const: value field count={}", layout.fields.count());
+                    let ty = &layout.ty.kind;
                     if let ty::Tuple(substs) = ty {
+                        // Values from the pair will be popped from this vec when we see a non-zst
+                        // type in the layout
+                        let mut pair_values = vec![two, one];
```
Comment (wesleywiser) [inline src/librustc_mir/transform/const_prop.rs]: Instead of allocating a new vector, we could do something like `let mut pair_values = &[one, two].iter()` and then around line 666 below, you'd just do `pair_values.next().unwrap()`.

File: src/librustc_mir/transform/const_prop.rs [hunk 4]
```diff
@@ -636,18 +643,40 @@ impl<'mir, 'tcx> ConstPropagator<'mir, 'tcx> {
...
+                        // Final values in the aggregate
+                        let mut aggregate_values = vec![];
+                        // Iterate fields, for zsts a zsg scalar, for others use the values from
```
Comment (wesleywiser) [inline src/librustc_mir/transform/const_prop.rs]: sp `zsg` -> `zst`? I'd also expand that a bit: "for ZSTs, create a ZST scalar"

**Review by wesleywiser — COMMENTED** [review]
Nice work overall!

**Comment by wesleywiser** [comment]
Can you also check if this fixes #66339?

**Comment by osa1** [comment]
> Can you also check if this fixes #66339?

It does not, but it changes the error. For actually fixing these both I think it'd be good to first decide whether we should be changing tuple reprs in const-prop (hence the [Zulip topic](https://rust-lang.zulipchat.com/#narrow/stream/189540-t-compiler.2Fwg-mir-opt/topic/Is.20changing.20tuple.20reprs.20in.20const_prop.20OK.3F)).

**Comment by wesleywiser** [comment]
> I think it'd be good to first decide whether we should be changing tuple reprs in const-prop

We definitely should not be doing that. Beyond the ICEs we're seeing here, it would complicate other MIR passes to have to deal with constants that are valid for the layout but potentially not the logical layout.

**Comment by osa1** [comment]
OK, in that case I think this PR will change quite a bit and the final PR should fix both of these issues. I'm running out of time for today but I'll try to update sometime later this week. I hope this is not blocking anyone?

**Comment by wesleywiser** [comment]
@osa1 Sorry, my point was supposed to be that I think your PR is overall the right direction to go in. I think there's probably a few small tweaks you should make per the above feedback and then we can land this.

File: src/librustc_mir/transform/const_prop.rs [hunk 5]
```diff
@@ -636,18 +643,40 @@ impl<'mir, 'tcx> ConstPropagator<'mir, 'tcx> {
...
+                        // the pair
+                        for i in 0 .. layout.fields.count() {
+                            let field_layout = layout.field(self, i).unwrap();
+                            debug!("field {} layout={:#?}", i, field_layout);
+                            let scalar = if field_layout.details.size == Size::ZERO {
```
Comment (oli-obk) [inline src/librustc_mir/transform/const_prop.rs]: There's a [dedicated function](https://doc.rust-lang.org/nightly/nightly-rustc/rustc/ty/layout/struct.TyLayout.html#method.is_zst) for this:

```suggestion
                            let scalar = if field_layout.is_zst() {
```

**Review by wesleywiser — COMMENTED** [review]
I think the tests for #66339 and #67019 should either include the expected MIR or we should make them ui tests. IMO we shouldn't have `mir-opt` tests that don't verify the MIR.

**Comment by wesleywiser** [comment]
The build is failing due to tidy:

> tidy error: /checkout/src/librustc_mir/transform/const_prop.rs:651: line longer than 100 chars

**Comment by osa1** [comment]
@wesleywiser 

> I think the tests for #66339 and #67019 should either include the expected MIR or we should make them ui tests. IMO we shouldn't have mir-opt tests that don't verify the MIR.

I'd be happy with either but I wonder if we should be including MIRs just yet because as far as I understand from the Zulip discussion we want to optimize scalar pairs more aggressively in the future so MIRs for these tests are currently not final. Same goes for the test for #66971 too actually.

Opinions?

**Comment by oli-obk** [comment]
Well... in that case you can just move the tests to `ui` tests and add a `// build-pass` comment to them.

**Comment by osa1** [comment]
Yes, that's what @wesleywiser suggested also. I'm just asking whether I should do that, or include current MIRs and keep the tests in current location.

**Comment by osa1** [comment]
Let's add the MIRs. I'll update.

**Comment by oli-obk** [comment]
Including more MIR tests indeed is a good idea, we don't have enough of these tests and random stuff keeps changing there

**Comment by wesleywiser** [comment]
I personally would lean toward including the MIR because then when you open that other PR, it's a lot easier to see the improvement because the tests will change.

**Comment by osa1** [comment]
I added MIR for #67019. I didn't add MIR for #66339 because the MIR is large and noisy -- it's just full of debug stuff and moves values around without doing anything interesting. I moved the test to `ui/` instead.

**Review by wesleywiser — APPROVED** [review]
Looks great to me, thanks!

**Comment by wesleywiser** [comment]
I'm completely unfamiliar with this part of the CI process. It looks like we're testing various crates from the ecosystem and one of the `xsv` tests is failing:

```
[/checkout/obj/build/ct/xsv/target/debug/xit/cat_cols/test-11]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "/checkout/obj/build/ct/xsv/target/debug/xsv" "cat" "columns" "in1.csv" "in2.csv" "--no-headers"
thread 'test_cat::prop_cat_cols' panicked at 'assertion failed: `(left == right)`
  left: `[["z\u{82}$", ""], ["w\'", ">R"], ["쭄爾", "ŉ\u{85}\u{8}*"], ["=", ""]]`,
 right: `[["\u{feff}z\u{82}$", ""], ["w\'", ">R"], ["쭄爾", "ŉ\u{85}\u{8}*"], ["=", ""]]`', tests/test_cat.rs:86:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

`\u{feff}` is the Unicode byte order mark. I'm not really sure what's going on...

**Comment by oli-obk** [comment]
@bors retry

This PR makes an optimization less aggressive, I don't see how it could be causing this new failure

**Comment by osa1** [comment]
So that was an intermittent (non-deterministic?) test failure? I guess every project has them :sweat_smile:

**Comment by eddyb** [comment]
Did we never run perf on this?

My guess is that [this regression](https://perf.rust-lang.org/compare.html?start=7dbfb0a8ca4ab74ee3111e57a024f9e6257ce37c&end=033662dfbca088937b9cdfd3d9584015b5e375b2&stat=instructions:u) was caused by this PR.

**Comment by wesleywiser** [comment]
We didn't but I'm not sure this PR is responsible because there are so many check regressions. When we turned on const prop by default, we only really saw improvements on debug & release builds not check builds because check builds don't query for optimized mir.
