### PR TITLE
Use of unimplemented!() causing ICE with NLL

### LINKED ISSUE #51345: Use of unimplemented!() causing ICE with NLL
Here is a fairly small test case ([playground](http://play.rust-lang.org/?gist=cd668d431e2aab78ac92f1061979f524&version=nightly&mode=debug)):

```rust
#![feature(nll)]
fn main() {
    use std::collections::HashMap;
    let mut m: HashMap<(), ()> = HashMap::new();
    m.insert((), unimplemented!());
}
```

The error message is

```text
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `Some((_4, bw0))`,
 right: `None`: never found an activation for this borrow!', librustc_mir/borrow_check/borrow_set.rs:121:9
```

### PR DESCRIPTION
**Pull request by davidtwco**
Fixes #51345.

r? @nikomatsakis

### CODE REVIEW

File: src/librustc_mir/borrow_check/borrow_set.rs [hunk 1]
```diff
@@ -116,19 +113,6 @@ impl<'tcx> BorrowSet<'tcx> {
...
-            visitor
-                .pending_activations
-                .iter()
-                .find(|&(_local, &borrow_index)| visitor.idx_vec[borrow_index]
-                    .activation_location
-                    .is_none()),
-            None,
-            "never found an activation for this borrow!",
-        );
-
```
Comment (nikomatsakis) [inline src/librustc_mir/borrow_check/borrow_set.rs]: I am a bit concerned here because I don't know where two-phase borrows that wind up unactivated will be set to `TwoPhaseActivation::NotActivated`. I think they will erroneously be recorded as not two phase. This means we will get an error with e.g. this code:

```rust
fn main() {
    let mut vec = vec![];
    vec.push((vec.len(), panic!()));
}
```

I expect this to error because the borrow of `vec` for calling `push` will incorrectly be considered "not two phase".

Comment (nikomatsakis) [reply src/librustc_mir/borrow_check/borrow_set.rs]: To fix this, I think we can modify `insert_as_pending_if_two_phase` to set the `activation_location` field to `NotActivated` instead of `NotTwoPhase`. Then when we *do* find an activation we can assert that the field is "not activated".

Comment (nikomatsakis) [reply src/librustc_mir/borrow_check/borrow_set.rs]: If I am correct about all this btw please add that above test. =)

**Review by nikomatsakis — CHANGES_REQUESTED** [review]

File: src/librustc_mir/borrow_check/borrow_set.rs (hunk 1 above)
Comment (davidtwco) [reply src/librustc_mir/borrow_check/borrow_set.rs]: Pushed a commit that addresses this.

File: src/librustc_mir/borrow_check/borrow_set.rs [hunk 2]
```diff
@@ -237,6 +237,14 @@ impl<'a, 'gcx, 'tcx> Visitor<'tcx> for GatherBorrows<'a, 'gcx, 'tcx> {
                             TwoPhaseActivation::NotActivated
                         }
                         _ => {
+                            // Double check: We should have found an activation for every pending
```
Comment (nikomatsakis) [inline src/librustc_mir/borrow_check/borrow_set.rs]: I think this commit is not *quite* correct -- that is, what we are checking here is that (a) this is indeed a 2-phase borrow and (b) we've not found some other activation (though we also check that above), right?

File: src/librustc_mir/borrow_check/borrow_set.rs [hunk 3]
```diff
@@ -322,6 +330,10 @@ impl<'a, 'gcx, 'tcx> GatherBorrows<'a, 'gcx, 'tcx> {
             );
         };
 
+        // Consider the borrow not activated.
```
Comment (nikomatsakis) [inline src/librustc_mir/borrow_check/borrow_set.rs]: I'd say "Consider the borrow not activated to start. When we find an activation, we'll update this field."

**Review by nikomatsakis — CHANGES_REQUESTED** [review]

File: src/librustc_mir/borrow_check/borrow_set.rs (hunk 2 above)
Comment (davidtwco) [reply src/librustc_mir/borrow_check/borrow_set.rs]: Pushed improved comments.

File: src/librustc_mir/borrow_check/borrow_set.rs (hunk 3 above)
Comment (davidtwco) [reply src/librustc_mir/borrow_check/borrow_set.rs]: Pushed improved comments.

**Review by nikomatsakis — APPROVED** [review]

**Review by nikomatsakis — APPROVED** [review]
