### PR TITLE
Do not discard constraints on overflow if there was candidate ambiguity

### LINKED ISSUE #201: demiu/aoc regression - overflow too eagerly dropping constraints
https://crater-reports.s3.amazonaws.com/pr-133502-11/try%2328f13ad7c79d80decb5a3d54595a8b4105f397a3/gh/Demiu.AoC2021/log.txt

```rust
trait Intersect<U> {
    type Output;
}

impl<T, U> Intersect<Vec<U>> for T
where
    T: Intersect<U>,
{
    type Output = T;
}

impl Intersect<Cuboid> for Cuboid {
    type Output = Cuboid;
}

fn intersect<T, U>(_: &T, _: &U) -> T::Output
where
    T: Intersect<U>,
{
    todo!()
}
```
struct Cuboid;
impl Cuboid {
    fn method(&self) {}
}

fn main() {
    let x = vec![];
    let y = intersect(&Cuboid, &x);
    y.method();
    let x: Vec<Cuboid> = x;
}
```

### PR DESCRIPTION
**Pull request by compiler-errors**
Fixes https://github.com/rust-lang/trait-system-refactor-initiative/issues/201.

There's a pretty chunky justification in the test.

r? lcnr

### CODE REVIEW

File: tests/ui/traits/next-solver/overflow-plus-ambiguity-normalizes-to-response.rs [hunk 1]
```diff
@@ -0,0 +1,54 @@
...
+fn main() {
+    let x = vec![];
+    // Here we end up trying to normalize `<Cuboid as Intersect<Vec<?0>>>::Output`
+    // for the return type of the function, to constrain `y`. The impl then requires
+    // `Cuboid: Intersect<?0>`, which has two candidates. One that constrains
+    // `?0 = Vec<?1>`, which itself has the same two candidates and ends up leading
+    // to a recursion depth overflow. In the second impl, we constrain `?0 = Cuboid`.
+    // Floundering leads to us combining the overflow candidate and yes candidate to
+    // overflow. Because the response was overflow, we used to bubble it up to the
+    // parent normalizes-to goal, which caused us to drop the constraint that would
```
Comment (lcnr) [inline tests/ui/traits/next-solver/overflow-plus-ambiguity-normalizes-to-response.rs:43]:
```suggestion
    // parent alias-relate goal, which caused us to drop the constraint that would
```

**Review by lcnr — COMMENTED** [review]
pls breakup big comment block

thx for pr, r=me

**Comment by lcnr** [comment]
interesting, why did rustbot not pick up this PR and ping us/add the relevant labels?
