### PR TITLE
rustdoc: Stop unconditionally evaluating the initializer of associated consts

### LINKED ISSUE #131625: rustdoc panics while documenting panicking associated constant
I have the following code:

```rust
pub trait Foo {
    const BAR: ();
}

impl Foo for () {
    const BAR: () = panic!("intentional PME");
}
```

While this is contrived, this pattern is used in real codebases to take advantage of post-monomorphization errors (PME's), for example [here](https://github.com/google/zerocopy/blob/5452c3d787486603e57bd191571ad05525c181b0/src/pointer/ptr.rs#L674-L679).

When running `cargo doc`, rustdoc seems to try to evaluate the constant, and crashes:

```text
$ cargo doc
 Documenting tmp v0.1.0 (.../tmp)
error[E0080]: evaluation of constant value failed
 --> src/lib.rs:6:21
  |
6 |     const BAR: () = panic!("intentional PME");
  |                     ^^^^^^^^^^^^^^^^^^^^^^^^^ the evaluated program panicked at 'intentional PME', src/lib.rs:6:21
  |
  = note: this error originates in the macro `$crate::panic::panic_2021` which comes from the expansion of the macro `panic` (in Nightly builds, run with -Z macro-backtrace for more info)
```

## Miscellaneous

```text
$ cargo version
cargo 1.78.0 (54d8815d0 2024-03-26)
```

### LINKED ISSUE #150312: Weird representation of trait const of associated type
Consider the following code as `lib.rs`:

```rust
pub trait Foo {
    type AssocType;
    const THE_CONST: Self::AssocType;
}

pub struct Bar;

impl Foo for Bar {
    type AssocType = u32;

    const THE_CONST: Self::AssocType = 1;
}
```

Running `cargo doc` and opening the generated html, one sees

Image

Note
```
const THE_CONST: Self::AssocType = {transmute(0x00000001): <Bar as Foo>::AssocType}
```

Instead of the more reasonably expected
```
const THE_CONST: Self::AssocType = 1u32
```
or, barring that, just nothing instead of the confusing `transmute` string.

### Meta

`rustc --version --verbose`:
```
rustc 1.91.0 (f8297e351 2025-10-28)
binary: rustc
commit-hash: f8297e351a40c1439a467bbbb6879088047f50b3
commit-date: 2025-10-28
host: x86_64-unknown-linux-gnu
release: 1.91.0
LLVM version: 21.1.2
```

### See also
- [Zulip chat](https://rust-lang.zulipchat.com/#narrow/channel/266220-t-rustdoc/topic/Weird.20repr.20for.20associated.20consts.20on.20traits/with/564908717)
- [Existing similar issue](https://github.com/rust-lang/rust/issues/113863)
- Manual bisection points to the issue being introduced in 1.62

---

### Possible workaround

Explicitly setting the const's concrete type instead of using the trait's associated type
```
impl Foo for Bar {
    type AssocType = u32;

    const THE_CONST: u32 = 1;
}
```
yields a more reasonable representation in the doc:
Image

### PR DESCRIPTION
**Pull request by fmease**
See the descriptions of the added tests for details.

Fixes rust-lang/rust#131625.
Fixes [after beta-1.93 backport] rust-lang/rust#149635.
Fixes rust-lang/rust#150312.

Supersedes rust-lang/rust#150629 IINM.

CC @cuviper (https://github.com/rust-lang/rust/issues/149635#issuecomment-3761125727)
r? @GuillaumeGomez or @yotamofek (rust-lang/rust#150629)

### CODE REVIEW

File: tests/rustdoc-html/constant/assoc-const-has-projection-ty.rs [hunk 1]
```diff
@@ -0,0 +1,31 @@
+// Ensure that we properly print the value `1` as `1` in the initializer of associated constants
+// that have user type "projection".
+//
+// We once used to evaluate the initializer in rustdoc and use rustc's MIR pretty-printer to
+// render the resulting MIR const value. This pretty printer matches on the type to interpret
+// the data and falls back to a cryptic `"{transmute(0x$data): $ty}"` for types it can't handle.
+// Crucially, when constructing the MIR const We passed the unnormalized type of the initializer,
```
Comment (fmease) [inline tests/rustdoc-html/constant/assoc-const-has-projection-ty.rs]:
```suggestion
// Crucially, when constructing the MIR const we passed the unnormalized type of the initializer,
```

**Comment by fmease** [comment]
This should theoretically have a positive impact on performance.

@bors try @rust-timer queue

File: tests/rustdoc-ui/diverging-assoc-consts.rs [hunk 2]
```diff
@@ -0,0 +1,26 @@
...
+//
+// We once used to evaluate them so we could display more kinds of expressions
+// (like `1 + 1` as `2`) given the fact that we generally only want to render
+// literals (otherwise we would risk dumping extremely large exprs or leaking
+// private struct fields).
+//
+// However, that deviated from rustc's behavior, made rustdoc accept less code
+// and was understandably surprising to users. So let's not.
+//
+// In the future we *might* provide users a mechanism to users to control this behavior.
```
Comment (fmease) [inline tests/rustdoc-ui/diverging-assoc-consts.rs]:
```suggestion
// In the future we *might* provide users a mechanism to control this behavior.
```

File: tests/rustdoc-ui/diverging-assoc-consts.rs [hunk 3]
```diff
@@ -0,0 +1,26 @@
...
+// E.g., via a new `#[doc(...)]` attribute.
+//
+// See also:
+// issue: <https://github.com/rust-lang/rust/issues/131625>
+// issue: <https://github.com/rust-lang/rust/issues/149635>
+
+//@ check-pass
+
+pub struct Type;
```
Comment (fmease) [inline tests/rustdoc-ui/diverging-assoc-consts.rs:20]: also test assoc consts in traits and trait impls

**Comment by fmease** [comment]
CI was green but I've just force-pushed again to tweak the commit message slightly.

r? yotamofek @bors r=yotamofek

**Comment by fmease** [comment]
Beta backport accepted as per [#t-rustdoc > beta-nominated: #151232 @ 💬](https://rust-lang.zulipchat.com/#narrow/channel/266220-t-rustdoc/topic/beta-nominated.3A.20.23151232/near/568543129).
