### PR TITLE
Centralize and clean type error reporting

### LINKED ISSUE #31173: ICE when attempting to split error message that contains " found" before "expected" into lines
In [librustc::session::split_msg_into_multiline()](https://github.com/rust-lang/rust/blob/d8869d3487a569b4a6b86c1b585cc15db48abc4a/src/librustc/session/mod.rs#L331).

With the error "type mismatch resolving \``for<'r> <F2 as core::ops::FnOnce<(&'r mut core::option::Option<T>, found_opts::FoundOpt)>>::Output == core::result::Result<(), collections::string::String>`\`: expected type parameter, found ()",

it finds the " found" in " found_opts::" before " found ()".

Then pos1 becomes (182, 191) and pos2= (91, 97), which makes `&msg[pos1.1..pos2.0]` [at line 360](https://github.com/rust-lang/rust/blob/d8869d3487a569b4a6b86c1b585cc15db48abc4a/src/librustc/session/mod.rs#L360) fail.

### PR DESCRIPTION
**Pull request by arielb1**
Refactors the code that handles type errors to be cleaner and fixes various edge cases.

This made the already-bad "type mismatch resolving" error message somewhat uglier. I want to fix that in another commit before this PR is merged.

Fixes #31173

r? @jonathandturner, cc @nikomatsakis

### CODE REVIEW

**Comment by arielb1** [comment]
Few more errors to modernize:
```
expected constant integer for repeat count, but mismatched types
array length constant evaluation error: mismatched types
implemented const has an incompatible type for trait
```

Will fix these tomorrow.

**Comment by arielb1** [comment]
All type errors now look like:

```
// newskool
error: mismatched types [--explain E0308]
 --> ../build-debug-assertions/fail.rs:3:32
  |>
3 |>     let x: Option<Option<_>> = y;
  |>                                ^ expected enum `std::option::Option`, found enum `std::result::Result`
note: expected type `std::option::Option<std::option::Option<_>>`
note:    found type `std::option::Option<std::result::Result<_, ()>>`
// oldskool

```../build-debug-assertions/fail.rs:3:32: 3:33 error: mismatched types [E0308]
../build-debug-assertions/fail.rs:3     let x: Option<Option<_>> = y;
                                                                   ^
../build-debug-assertions/fail.rs:3:32: 3:33 help: run `rustc --explain E0308` to see a detailed explanation
../build-debug-assertions/fail.rs:3:32: 3:33 note: expected type `std::option::Option<std::option::Option<_>>` 
../build-debug-assertions/fail.rs:3:32: 3:33 note:    found type `std::option::Option<std::result::Result<_, ()>>` 
../build-debug-assertions/fail.rs:3:32: 3:33 note: expected enum `std::option::Option`, found enum `std::result::Result` 
../build-debug-assertions/fail.rs:3     let x: Option<Option<_>> = y;
```

File: src/test/compile-fail/issue-13033.rs [hunk 1]
```diff
@@ -16,7 +16,9 @@ struct Baz;
 
 impl Foo for Baz {
     fn bar(&mut self, other: &Foo) {}
-    //~^ ERROR method `bar` has an incompatible type for trait: values differ in mutability [E0053]
```
Comment (nikomatsakis) [inline src/test/compile-fail/issue-13033.rs]: it's hard for me to tell from this diff: has the "values differ in mutability" part of the message been entirely removed?

File: src/test/compile-fail/issue-26194.rs [hunk 2]
```diff
@@ -12,7 +12,7 @@ struct S(String);
 
 impl S {
     fn f(self: *mut S) -> String { self.0 }
-    //~^ ERROR mismatched method receiver
```
Comment (nikomatsakis) [inline src/test/compile-fail/issue-26194.rs]: similarly here, I'm wondering if the information about "method receivers" is showing up, but in a different place now?

**Comment by nikomatsakis** [comment]
So I'm 👍 on removing the hack around newlines and centralizing the error reporting infrastructure here to go through a more common set of methods. That said, it seems like the new messages may be less specific and quite possibly less helpful than the old ones. 

It might be though that if we combined this patch with something that gives intelligent diffs, that would be the best of both worlds.

Basically I think we want to avoid presenting people with two types and having them find the difference: so if we used to point out that the problem has to do with mutability, but now we make you figure it out for yourself, that could be a regression in usability. I also think that we calling everything "mismatched types" might be confused for people, if we can give a more specific indicator of where the type problem is. 

Also, @arielb1, you mention this:

> This made the already-bad "type mismatch resolving" error message somewhat uglier. I want to fix that in another commit before this PR is merged.

How does it look now? Can you give an example of what got uglier?

File: src/test/compile-fail/issue-13033.rs (hunk 1 above)
Comment (arielb1) [inline src/test/compile-fail/issue-13033.rs]: See the error message above ^. It is now a label in new-skool and a single note in old-skool.

**Comment by arielb1** [comment]
ready for review. I would like @nikomatsakis to look at the last commit (1a632a3).

**Comment by arielb1** [comment]
added a commit to remove the RFC1592 warnings (#33242, #33243) - they are there since 1.10 and I am planning to make more modifications to `traits::error_reporting`.

**Comment by GuillaumeGomez** [comment]
:+1:

**Comment by nikomatsakis** [comment]
OK, so I think this patch is looking good. I have three concerns:

- [ ] this goes ahead and makes the RFC1592 warnings into errors without any procedure (no FCP, etc). I think this is...maybe fine, but I want to review that. I had hoped to talk about it in the compiler team mtg last night but we ran out of time. I'd be more comfortable with that in a separate PR, I'm not sure how important it is to this one.
- [ ] the handling of constant evaluation errors seems better, but I think it could be improved further (see below).
- [ ] method receiver type mismatch errors seem potentially quite confusing (see below).

**Constant evaluation errors.** This is what we report before this PR:

```
error: constant evaluation error: mismatched types:
 expected `u64`,
    found `i64` [--explain E0080]
   --> discrim-ill-typed.rs:118:16
    |>
118 |>         OhNo = 0_i64,
    |>    
```

This is what the PR does:

```rust
error[E0080]: constant evaluation error
   --> discrim-ill-typed.rs:118:16
    |
118 |         OhNo = 0_i64,
    |                ^^^^^ mismatched types
    |
    = note: expected `u64`
    = note: found `i64`
```

But I think the heading of "constant evaluation error" isn't great -- the headline text should be something pertinent and actionable, and not just a general note of the context in which the error occurred. To be honest, I don't think we should even say mismatched types, but rather something pithier like "expected u64, found i64", but I'd change that in a separate PR. For now, it'd be better to headline with "mismatched types" and then not lose the "helpful short text", something like:

```
error[E0080]: mismatched types in constant
   --> discrim-ill-typed.rs:118:16
    |
118 |         OhNo = 0_i64,
    |                ^^^^^ expected u64, found i64
```

(Note that there is some logic, I think, to avoid printing out the notes in the case that there are two integral types.)

To me, it doesn't even seem *essential* to say "in constant", but it doesn't hurt, and in other cases may help to clarify. @jonathandturner may have more of an opinion here.

I haven't reviewed this part of the code but I imagine this wouldn't be that hard to change.

**Method receivers.** This is the one case where it seemed like we were losing an important part of the message, but one I think could be readily improved with better span info, or possibly some other tweaks. Output today (from stage0):

```
error: mismatched method receiver [--explain E0211]
  --> issue-26194.rs:14:5
   |>
14 |>     fn f(self: *mut S) -> String { self.0 }
   |>     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected struct `S`, found *-ptr
note: expected type `S`
note:    found type `*mut S`
```

Output after this PR:

```
error[E0308]: mismatched types
  --> issue-26194.rs:14:5
   |
14 |     fn f(self: *mut S) -> String { self.0 }
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected struct `S`, found *-ptr
   |
   = note: expected type `S`
   = note:    found type `*mut S`
```

Honestly, neither of these is great, but the old message at least tells you that the problem is with the method receiver. Ideally, we'd modify the error report to have the span be the `self: *mut S` declaration, but if not we ought to be able to trace enough info to say "mismatched types in method receiver", maybe?

**Comment by jonathandturner** [comment]
A general 👍 to @nikomatsakis's suggestions.  I can go either way on adding "in constant".  As Niko points out, if the span gets long it's nice to have at least a little more information so you know what you're looking for, like that method example.

We may actually want to make sure the short form is in the error message.  Looking at the diff, I noticed match-range-fail.rs:

```
-    //~^^^ ERROR mismatched types in range
-    //~| expected char, found integral variable
+    //~^^^ ERROR mismatched types
+    //~| expected type `_`
+    //~| found type `char`
```

Speaking of which you probably want to make sure these are checked using 'NOTE', which Niko reminded me the other day is required at least once in a unit test for the labels to be checked.

```
-    //~^^^ ERROR mismatched types in range
-    //~| NOTE expected char, found integral variable
+    //~^^^ ERROR mismatched types
+    //~| NOTE expected type `_`
+    //~| NOTE found type `char`
```

So we're actually losing the information that it's an integral value (unless that's captured elsewhere).  Ideally, we wouldn't lose that information.

The issue-24356.rs changes also looks like it's losing information.  Is this no longer an error?

```
-            //~^ ERROR method `deref` has an incompatible type for trait
-            //~| expected &-ptr
-            //~| found i8 [E0053]
```

**Comment by arielb1** [comment]
> So we're actually losing the information that it's an integral value (unless that's captured elsewhere). Ideally, we wouldn't lose that information.

We don't lose that information. It goes on the label (or on a note with old-skool errors).

> The issue-24356.rs changes also looks like it's losing information. Is this no longer an error?

It is a derived error that is correctly suppressed (the expected type is `&[type error]`, not that you can see it with the old-style errors).

**Comment by jonathandturner** [comment]
Yeah, with updates r=me.  @nikomatsakis?

**Comment by nikomatsakis** [comment]
Nice work @arielb1

**Comment by nikomatsakis** [comment]
Heh, r=me. :) Should modify bors to detect that...

**Comment by arielb1** [comment]
The RFC1592 work is now #34982.

**Comment by arielb1** [comment]
```
command timed out: 1200 seconds without output, attempting to kill
SIGKILL failed to kill process
using fake rc=-1
program finished with exit code -1
```

cc @alexcrichton 

@bors retry

**Comment by alexcrichton** [comment]
@bors: retry

*weeps*
