### PR TITLE
Recover from function pointer types with generic parameter list

### LINKED ISSUE #103487: Provide a better error message for function pointers with generic parameters
Newcomers might attempt to write a “generic” function pointer like `fn<T>(T) -> bool`. In such case, the compiler should provide a better error message. Inspired by a recent Reddit thread I sadly cannot find anymore.

### `fn<'a>`

Given the following code:

```rust
fn main() {
    let _: fn<'a>(&'a str) -> bool;
}
```

The compiler should **mention** that *function pointers may not be generic* or *[…] may not have generic parameters*, **suggest** to move the lifetime(s) to a `for<>` parameter list (this should be machine-applicable in my judgement) and be able to **recover**:

```patch
- fn<'a>(&'a str) -> bool
+ for<'a> fn(&'a str) -> bool
```

For later reference, the current output is:

```
error: expected `(`, found `<`
 --> src/main.rs:2:14
  |
2 |     let _: fn<'a>(&'a str) -> bool;
  |         -    ^ expected `(`
  |         |
  |         while parsing the type for `_`
```

### `fn<T>` / `fn<const C: T>`

Given the following code:

```rust
fn main() {
    let _: fn<T>(T) -> bool;
    let _: fn<const N: usize>([u8; N]);
}
```

The compiler should **mention** that *function pointers may not be generic* or *[…] may not have generic parameters* and be able to **recover** emitting two diagnostics, one for each line.

The compiler *could* also suggest moving the generic parameter list further up to the owning function, struct, etc. if available. Note that this might not be what the user intended (since there is a semantic difference between hypothetical higher-ranked generics and normal ones) and therefore shouldn't be machine-applicable. 

For later reference, the current output is:

```
error: expected `(`, found `<`
 --> src/main.rs:2:14
  |
2 |     let _: fn<T>(T) -> bool;
  |         -    ^ expected `(`
  |         |
  |         while parsing the type for `_`
```

@rustbot label A-parser A-suggestion-diagnostics D-newcomer-roadblock

### PR DESCRIPTION
**Pull request by fmease**
Give a more helpful error when encountering function pointer types with a generic parameter list like `fn<'a>(&'a str) -> bool` or `fn<T>(T) -> T` and suggest moving lifetime parameters to a `for<>` parameter list.

I've added a bunch of extra code to properly handle (unlikely?) corner cases like `for<'a> fn<'b>()` (where there already exists a `for<>` parameter list) correctly suggesting `for<'a, 'b> fn()` (merging the lists). If you deem this useless, I can simplify the code by suggesting nothing at all in this case.

I am quite open to suggestions regarding the wording of the diagnostic messages.

Fixes #103487.
@rustbot label A-diagnostics
r? diagnostics

### CODE REVIEW

File: compiler/rustc_parse/src/parser/ty.rs [hunk 1]
```diff
@@ -544,6 +554,53 @@ impl<'a> Parser<'a> {
...
+                for_param_list_exists: param_insertion_point.is_some(),
+            })
+        } else {
+            None
+        };
+
+        self.sess.emit_err(FnPtrWithGenerics { span: generics.span, sugg });
+
+        // Only pass along lifetime parameters since type & const parameters aren't
+        // allowed to appear in `for` parameter lists.
```
Comment (fmease) [inline compiler/rustc_parse/src/parser/ty.rs:598]: I'd like to clarify this comment (I should probably reword it): I could easily pass along every kind of parameter (lt, ty, ct).

However, the subsequent error message would be *only lifetime parameters can be used in this context* pointing at the incorrectly positioned parameter list which clearly isn't great (in my eyes, it's confusing & contradictory). If the message was sth. akin to *$kind parameter cannot be used in this context* (similar to the *lifetime bounds cannot be used in this context* message), it would be better in this scenario (it's neutral). I am not suggesting we should change it though.
