### PR TITLE
Revert #51601

### LINKED ISSUE #55985: step_by + skip produce incorrect results
The following snippet demonstrates the problem:
```rust
println!("first");
for i in (0..640).step_by(128) {
    println!("{}", i)
}
println!("second");
for i in (0..640).step_by(128).skip(1) {
    println!("{}", i)
}
println!("third");
for i in (0..640).step_by(128).map(|i| i).skip(1) {
    println!("{}", i)
}
```

It prints:
```
first
0
128
256
384
512
second
128
129
257
385
513
third
128
256
384
512
```

I expect second iterator to produce the same result as for the third one.

### PR DESCRIPTION
**Pull request by newpavlov**
Closes: #55985

Specialization of `StepBy<Range(Inclusive)>` results in an incorrectly behaving code when `step_by` is combined with `skip` or `nth`.

If this will get merged we probably should reopen issues previously closed by #51601 (if there was any).

### CODE REVIEW

File: src/libcore/tests/iter.rs [hunk 1]
```diff
@@ -1619,11 +1619,8 @@ fn test_range_step() {
 }
 
 #[test]
-fn test_range_inclusive_step() {
```
Comment (sfackler) [inline src/libcore/tests/iter.rs]: This test should be able to stay.

**Comment by nikomatsakis** [comment]
cc @rust-lang/libs -- might be good to beta-accept this (or not, as you choose)

**Comment by alexcrichton** [comment]
Yeah this looks fine to backport, tagged as such

**Comment by alexcrichton** [comment]
@bors: p=1 

beta nominated
