### PR TITLE
Fix doctest output json

### LINKED ISSUE #144798: [rustdoc] Non-json time diagnostics in stdout when using `--format json`
### Location

https://github.com/rust-lang/rust/blob/4b55fe199cfe9c710555a5af7f2a49491ad38254/src/librustdoc/doctest.rs#L405

or

https://github.com/rust-lang/rust/blob/4b55fe199cfe9c710555a5af7f2a49491ad38254/src/librustdoc/doctest.rs#L411

### Summary

I have not done too much investigation into source code. [First posted the issue here](https://github.com/rust-lang/rust/pull/144308#issuecomment-3145693106)

But I noticed #144308 breaks the `--format json` unstable option, since the time displayed goes to stdout. as a result, if you run something like:

```rust
cargo +nightly test --doc -- -Z unstable-options --format json > doc-test.json
```

then

```json
...
{ "type": "suite", "event": "ok", "passed": 0, "failed": 0, "ignored": 5, "measured": 0, "filtered_out": 0, "exec_time": 0.000229133 }
all doctests ran in 0.17s; merged doctests compilation took 0.17s
```

this line is at the end of each output. in addition, when using the `--workspace` flag, it appears after every library is doc-tested.

It can easily be dealt with, but I realized my CICD started failing when parsing this output so I wanted to ask/report

@GuillaumeGomez

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Fixes rust-lang/rust#144798.

Hopefully it will work with the new changes in `libtest` without needing to do both at once.

This PR moves the `rustdoc` merged doctest extra information directly into `libtest` to ensure they share the same rendering to prevent the bug uncovered in rust-lang/rust#144798.

cc @lolbinary (as you reviewed the first PR)

And since we're making changes to `libtest`:

r? @Amanieu

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
This is very frustrating that `libtest` cannot be used like any other dependency. Is there a reason to that @Kobzol ?

**Comment by Kobzol** [comment]
Well, that is kind one of the outputs of the stage0 redesign. `cfg(bootstrap)` has moved from the stdlib to the compiler (so rustc and rustdoc). If you need to use new unstable library APIs (which includes libtest) in rustc/rustdoc, you have to support both stage0 and stage1 with `cfg(bootstrap)` until beta is bumped.

**Comment by GuillaumeGomez** [comment]
Like usual, I will wait for the separate PR I opened to be merged and available.

**Comment by lolbinarycat** [comment]
We could just decide stage 1 rustdoc shouldn't exist, though that would mean that testing rustdoc would be slightly more work if you're not using download-rustc, since you could no longer just run the tests against stage1 rustdoc to prevent an extra rebuild of rustc (useful when making changes to compiler queries only used by rustdoc)

**Comment by GuillaumeGomez** [comment]
I'd rather not. ^^'

Once upon a time, changing `libtest` worked fine with `rustdoc` stage 1. Not sure when and why it changed, makes things more convoluted.

**Comment by Kobzol** [comment]
It changed with the stage0 redesign. Before building in-tree libstd was required to build rustc, but not anymore (https://blog.rust-lang.org/inside-rust/2025/05/29/redesigning-the-initial-bootstrap-sequence/).

**Comment by GuillaumeGomez** [comment]
Since new `libtest` version was released, CI is now happy. Still need to change how `libtest` is handled in bootstrap.

File: tests/run-make/rustdoc-doctest-output-format/rmake.rs [hunk 1]
```diff
@@ -0,0 +1,79 @@
...
+fn run_test(edition: &str, format: Option<&str>) -> String {
+    let mut r = rustdoc();
+    r.input("file.rs").edition(edition).arg("--test");
+    if let Some(format) = format {
+        r.args(&["--test-args", "-Zunstable-options"]).args(&[
+            "--test-args",
+            "--format",
+            "--test-args",
+            format,
+        ]);
```
Comment (fmease) [inline tests/run-make/rustdoc-doctest-output-format/rmake.rs]: This could be

```suggestion
        r.args(&[
            "--test-args",
            &format!("-Zunstable-options --format {format}"),
        ]);
```

or

```suggestion
        r.args(&[
            "--test-args",
            "-Zunstable-options".
            "--test-args",
            "--format",
            "--test-args",
            format,
        ]);
```

but it doesn't really matter

**Review by fmease — APPROVED** [review]

**Comment by fmease** [comment]
Thanks! @bors r+ rollup

**Comment by Zalathar** [comment]
Failed in rollup: https://github.com/rust-lang/rust/pull/147316#issuecomment-3367865861

@bors r-

File: tests/run-make/rustdoc-doctest-output-format/rmake.rs (hunk 1 above)
Comment (GuillaumeGomez) [reply tests/run-make/rustdoc-doctest-output-format/rmake.rs]: Nah it's more beautiful so let's use it. :)

**Comment by Zalathar** [comment]
Failed in rollup (`test-various`): https://github.com/rust-lang/rust/pull/147352#issuecomment-3368654632

@bors r-

**Comment by fmease** [comment]
Needs `ignore-cross-compile` instead of `needs-std`

**Comment by GuillaumeGomez** [comment]
Seems like it fixed the issue, thanks @fmease!

@bors r=fmease rollup
