### PR TITLE
Error out of layout calculation if a non-last struct field is unsized

### LINKED ISSUE #121473: ICE: `SizeOf MIR operator called for unsized type`
auto-reduced (treereduce-rust):
````rust
use std::mem::{align_of, size_of};

#[repr(C)]

pub struct p0f_api_query {
    pub magic: u32,
    pub addr_type: str,
    pub addr: [u8; 16],
}

pub fn main() {
    assert_eq!(size_of::<p0f_api_query>(), 21);
}


````

<details><summary><strong>original code</strong></summary>
<p>

original:
````rust
//@ run-pass

#![allow(dead_code)]

use std::mem::{size_of, align_of};
use std::os::raw::c_int;

// The two enums that follow are designed so that bugs trigger layout optimization.
// Specifically, if either of the following reprs used here is not detected by the compiler,
// then the sizes will be wrong.

#[repr(C, u8)]
enum E1 {
    A(u8, u16, u8),
    B(u8, u16, u8)
}

#[repr(u8, irving)]
enum E2 {
    A(u8, X),
    B(u8, u16, u8)
}

// Check that repr(int) and repr(C) are in fact different from the above

#[repr(u8)]
enum E3 {
    A(u8, u16, u8),
    B([u8; 7], bool)
}

#[repr(u16)]
enum E4 {
    A(u8, u16, u8),
    Bar {
        a: isize,
        b: isize
    }
}

#[repr(u32)]
enum E5 {
    A(u8, u16, u8),
    B(u8, u16, u8)
}

#[repr(u64)]
enum E6 {
    A(u8, u16, u8),
    B(u8, u16, u8)
}

#[repr(C)]
enum E7 {
    A(u8, u16, u8),
    B(u8, u16, u8)
}

// From pr 37429

#[repr(C,packed)]
pub struct p0f_api_query {
    pub magic: u32,
    pub addr_type: str,
    pub addr: [u8; 16],
}

pub fn main() {
    assert_eq!(size_of::<E1>(), 8);
    assert_eq!(size_of::<E2>(), 8);
    assert_eq!(size_of::<E3>(), 6);
    assert_eq!(size_of::<E4>(), 8);
    assert_eq!(size_of::<E5>(), align_size(10, align_of::<u32>()));
    assert_eq!(size_of::<E6>(), align_size(14, align_of::<u64>()));
    assert_eq!(size_of::<E7>(), align_size(6 + size_of::<c_int>(), align_of::<c_int>()));
    assert_eq!(size_of::<p0f_api_query>(), 21);
}

fn align_size(size: usize, align: usize) -> usize {
    if size % align != 0 {
        size + (align - (size % align))
    } else {
        size
    }
}

````
</p>
</details>

Version information
````
rustc 1.78.0-nightly (f8131a48a 2024-02-21)
binary: rustc
commit-hash: f8131a48a46ac3bc8a3d0fe0477055b132cffdc3
commit-date: 2024-02-21
host: x86_64-unknown-linux-gnu
release: 1.78.0-nightly
LLVM version: 18.1.0

````

Command:
`/home/matthias/.rustup/toolchains/master/bin/rustc `

<details><summary><strong>Program output</strong></summary>
<p>

```
warning: unused import: `align_of`
 --> /tmp/icemaker_global_tempdir.TBHuutByqHGC/rustc_testrunner_tmpdir_reporting.9iS1p4GVIV9c/mvce.rs:1:16
  |
1 | use std::mem::{align_of, size_of};
  |                ^^^^^^^^
  |
  = note: `#[warn(unused_imports)]` on by default

error[E0277]: the size for values of type `str` cannot be known at compilation time
 --> /tmp/icemaker_global_tempdir.TBHuutByqHGC/rustc_testrunner_tmpdir_reporting.9iS1p4GVIV9c/mvce.rs:7:20
  |
7 |     pub addr_type: str,
  |                    ^^^ doesn't have a size known at compile-time
  |
  = help: the trait `Sized` is not implemented for `str`
  = note: only the last field of a struct may have a dynamically sized type
  = help: change the field's type to have a statically known size
help: borrowed types always have a statically known size
  |
7 |     pub addr_type: &str,
  |                    +
help: the `Box` type always has a statically known size and allocates its contents in the heap
  |
7 |     pub addr_type: Box<str>,
  |                    ++++   +

error: internal compiler error: compiler/rustc_const_eval/src/interpret/step.rs:243:21: SizeOf MIR operator called for unsized type p0f_api_query
   --> /home/matthias/.rustup/toolchains/master/lib/rustlib/src/rust/library/core/src/mem/mod.rs:313:5
    |
313 |     intrinsics::size_of::<T>()
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^

thread 'rustc' panicked at /rustc/f8131a48a46ac3bc8a3d0fe0477055b132cffdc3/compiler/rustc_middle/src/util/bug.rs:34:50:
Box<dyn Any>
stack backtrace:
   0:     0x7f7bfab8caf6 - std::backtrace_rs::backtrace::libunwind::trace::hbec2edc838b433e2
                               at /rustc/f8131a48a46ac3bc8a3d0fe0477055b132cffdc3/library/std/src/../../backtrace/src/backtrace/libunwind.rs:104:5
   1:     0x7f7bfab8caf6 - std::backtrace_rs::backtrace::trace_unsynchronized::h88c30257ee0dd166
                               at /rustc/f8131a48a46ac3bc8a3d0fe0477055b132cffdc3/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7f7bfab8caf6 - std::sys_common::backtrace::_print_fmt::h9176654d509e3088
                               at /rustc/f8131a48a46ac3bc8a3d0fe0477055b132cffdc3/library/std/src/sys_common/backtrace.rs:68:5
   3:     0x7f7bfab8caf6 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h671feaee1776bf19
                               at /rustc/f8131a48a46ac3bc8a3d0fe0477055b132cffdc3/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x7f7bfabdda7c - core::fmt::rt::Argument::fmt::h59605c83ae32d935
                               at /rustc/f8131a48a46ac3bc8a3d0fe0477055b132cffdc3/library/core/src/fmt/rt.rs:142:9
   5:     0x7f7bfabdda7c - core::fmt::write::hf7af8dfcfd20db5b
                               at /rustc/f8131a48a46ac3bc8a3d0fe0477055b132cffdc3/library/core/src/fmt/mod.rs:1120:17
   6:     0x7f7bfab814bf - std::io::Write::write_fmt::h92a5dbf489025e71
                               at /rustc/f8131a48a46ac3bc8a3d0fe0477055b132cffdc3/library/std/src/io/mod.rs:1846:15
   7:     0x7f7bfab8c8a4 - std::sys_common::backtrace::_print::h00080302d23998ae
                               at /rustc/f8131a48a46ac3bc8a3d0fe0477055b132cffdc3/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x7f7bfab8c8a4 - std::sys_common::backtrace::print::h6b23124445400245
                               at /rustc/f8131a48a46ac3bc8a3d0fe0477055b132cffdc3/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x7f7bfab8f5eb - std::panicking::default_hook::{{closure}}::hd67b2f9d36675a28
  10:     0x7f7bfab8f339 - std::panicking::default_hook::h10a39ef11c714e42
                               at /rustc/f8131a48a46ac3bc8a3d0fe0477055b132cffdc3/library/std/src/panicking.rs:292:9
  11:     0x7f7bfda7a94c - std[5a8e7f94216a9138]::panicking::update_hook::<alloc[e14ab1f516d287ab]::boxed::Box<rustc_driver_impl[e279e4f1fedd9109]::install_ice_hook::{closure#0}>>::{closure#0}
  12:     0x7f7bfab8fd50 - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h37ba37dc48823c1d
                               at /rustc/f8131a48a46ac3bc8a3d0fe0477055b132cffdc3/library/alloc/src/boxed.rs:2030:9
  13:     0x7f7bfab8fd50 - std::panicking::rust_panic_with_hook::he3e3bc7c345bf54b
                               at /rustc/f8131a48a46ac3bc8a3d0fe0477055b132cffdc3/library/std/src/panicking.rs:786:13
  14:     0x7f7bfdaa7524 - std[5a8e7f94216a9138]::panicking::begin_panic::<rustc_errors[34364e5c712fab73]::ExplicitBug>::{closure#0}
  15:     0x7f7bfdaa4176 - std[5a8e7f94216a9138]::sys_common::backtrace::__rust_end_short_backtrace::<std[5a8e7f94216a9138]::panicking::begin_panic<rustc_errors[34364e5c712fab73]::ExplicitBug>::{closure#0}, !>
  16:     0x7f7bfda9f936 - std[5a8e7f94216a9138]::panicking::begin_panic::<rustc_errors[34364e5c712fab73]::ExplicitBug>
  17:     0x7f7bfc417631 - <rustc_errors[34364e5c712fab73]::diagnostic::BugAbort as rustc_errors[34364e5c712fab73]::diagnostic::EmissionGuarantee>::emit_producing_guarantee
  18:     0x7f7bfda01f60 - rustc_middle[446dd094ad85939e]::util::bug::opt_span_bug_fmt::<rustc_span[adb133ac03280fc1]::span_encoding::Span>::{closure#0}
  19:     0x7f7bfda0217a - rustc_middle[446dd094ad85939e]::ty::context::tls::with_opt::<rustc_middle[446dd094ad85939e]::util::bug::opt_span_bug_fmt<rustc_span[adb133ac03280fc1]::span_encoding::Span>::{closure#0}, !>::{closure#0}
  20:     0x7f7bfd9f8e48 - rustc_middle[446dd094ad85939e]::ty::context::tls::with_context_opt::<rustc_middle[446dd094ad85939e]::ty::context::tls::with_opt<rustc_middle[446dd094ad85939e]::util::bug::opt_span_bug_fmt<rustc_span[adb133ac03280fc1]::span_encoding::Span>::{closure#0}, !>::{closure#0}, !>
  21:     0x7f7bfd050f54 - rustc_middle[446dd094ad85939e]::util::bug::span_bug_fmt::<rustc_span[adb133ac03280fc1]::span_encoding::Span>
  22:     0x7f7bffcfbef6 - rustc_const_eval[b7e9a6566b8f5ff6]::const_eval::eval_queries::eval_body_using_ecx::{closure#0}
  23:     0x7f7bffc76f23 - rustc_const_eval[b7e9a6566b8f5ff6]::const_eval::eval_queries::eval_in_interpreter
  24:     0x7f7bff1fa938 - rustc_const_eval[b7e9a6566b8f5ff6]::const_eval::eval_queries::eval_to_allocation_raw_provider
  25:     0x7f7bff1fa706 - rustc_query_impl[9d4c51777e2bb749]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[9d4c51777e2bb749]::query_impl::eval_to_allocation_raw::dynamic_query::{closure#2}::{closure#0}, rustc_middle[446dd094ad85939e]::query::erase::Erased<[u8; 24usize]>>
  26:     0x7f7bff80ba51 - rustc_query_system[9b2ccfe41ae3bb1b]::query::plumbing::try_execute_query::<rustc_query_impl[9d4c51777e2bb749]::DynamicConfig<rustc_query_system[9b2ccfe41ae3bb1b]::query::caches::DefaultCache<rustc_middle[446dd094ad85939e]::ty::ParamEnvAnd<rustc_middle[446dd094ad85939e]::mir::interpret::GlobalId>, rustc_middle[446dd094ad85939e]::query::erase::Erased<[u8; 24usize]>>, false, false, false>, rustc_query_impl[9d4c51777e2bb749]::plumbing::QueryCtxt, false>
  27:     0x7f7bff80b62c - rustc_query_impl[9d4c51777e2bb749]::query_impl::eval_to_allocation_raw::get_query_non_incr::__rust_end_short_backtrace
  28:     0x7f7bff1fb60d - rustc_const_eval[b7e9a6566b8f5ff6]::const_eval::eval_queries::eval_to_const_value_raw_provider
  29:     0x7f7bff1fb40c - rustc_query_impl[9d4c51777e2bb749]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[9d4c51777e2bb749]::query_impl::eval_to_const_value_raw::dynamic_query::{closure#2}::{closure#0}, rustc_middle[446dd094ad85939e]::query::erase::Erased<[u8; 24usize]>>
  30:     0x7f7bff80ba14 - rustc_query_system[9b2ccfe41ae3bb1b]::query::plumbing::try_execute_query::<rustc_query_impl[9d4c51777e2bb749]::DynamicConfig<rustc_query_system[9b2ccfe41ae3bb1b]::query::caches::DefaultCache<rustc_middle[446dd094ad85939e]::ty::ParamEnvAnd<rustc_middle[446dd094ad85939e]::mir::interpret::GlobalId>, rustc_middle[446dd094ad85939e]::query::erase::Erased<[u8; 24usize]>>, false, false, false>, rustc_query_impl[9d4c51777e2bb749]::plumbing::QueryCtxt, false>
  31:     0x7f7bff80b530 - rustc_query_impl[9d4c51777e2bb749]::query_impl::eval_to_const_value_raw::get_query_non_incr::__rust_end_short_backtrace
  32:     0x7f7bfd01c265 - <rustc_middle[446dd094ad85939e]::ty::context::TyCtxt>::const_eval_resolve
  33:     0x7f7bfc6400a0 - <rustc_mir_transform[2f80b166b66099ac]::known_panics_lint::ConstPropagator as rustc_middle[446dd094ad85939e]::mir::visit::Visitor>::visit_operand
  34:     0x7f7bfc641835 - <rustc_mir_transform[2f80b166b66099ac]::known_panics_lint::ConstPropagator as rustc_middle[446dd094ad85939e]::mir::visit::Visitor>::visit_assign
  35:     0x7f7bff40911b - <rustc_mir_transform[2f80b166b66099ac]::known_panics_lint::ConstPropagator as rustc_middle[446dd094ad85939e]::mir::visit::Visitor>::visit_body
  36:     0x7f7bfc63cc69 - <rustc_mir_transform[2f80b166b66099ac]::known_panics_lint::KnownPanicsLint as rustc_mir_transform[2f80b166b66099ac]::pass_manager::MirLint>::run_lint
  37:     0x7f7bfee12689 - rustc_mir_transform[2f80b166b66099ac]::pass_manager::run_passes_inner
  38:     0x7f7bff042806 - rustc_mir_transform[2f80b166b66099ac]::mir_drops_elaborated_and_const_checked
  39:     0x7f7bff04213d - rustc_query_impl[9d4c51777e2bb749]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[9d4c51777e2bb749]::query_impl::mir_drops_elaborated_and_const_checked::dynamic_query::{closure#2}::{closure#0}, rustc_middle[446dd094ad85939e]::query::erase::Erased<[u8; 8usize]>>
  40:     0x7f7bfef098b0 - rustc_query_system[9b2ccfe41ae3bb1b]::query::plumbing::try_execute_query::<rustc_query_impl[9d4c51777e2bb749]::DynamicConfig<rustc_query_system[9b2ccfe41ae3bb1b]::query::caches::VecCache<rustc_span[adb133ac03280fc1]::def_id::LocalDefId, rustc_middle[446dd094ad85939e]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[9d4c51777e2bb749]::plumbing::QueryCtxt, false>
  41:     0x7f7bfef0919e - rustc_query_impl[9d4c51777e2bb749]::query_impl::mir_drops_elaborated_and_const_checked::get_query_non_incr::__rust_end_short_backtrace
  42:     0x7f7bff8a333f - rustc_interface[7ca501d7f8f3a34f]::passes::analysis
  43:     0x7f7bff8a2a29 - rustc_query_impl[9d4c51777e2bb749]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[9d4c51777e2bb749]::query_impl::analysis::dynamic_query::{closure#2}::{closure#0}, rustc_middle[446dd094ad85939e]::query::erase::Erased<[u8; 1usize]>>
  44:     0x7f7bffb3d4a5 - rustc_query_system[9b2ccfe41ae3bb1b]::query::plumbing::try_execute_query::<rustc_query_impl[9d4c51777e2bb749]::DynamicConfig<rustc_query_system[9b2ccfe41ae3bb1b]::query::caches::SingleCache<rustc_middle[446dd094ad85939e]::query::erase::Erased<[u8; 1usize]>>, false, false, false>, rustc_query_impl[9d4c51777e2bb749]::plumbing::QueryCtxt, false>
  45:     0x7f7bffb3d209 - rustc_query_impl[9d4c51777e2bb749]::query_impl::analysis::get_query_non_incr::__rust_end_short_backtrace
  46:     0x7f7bffb4c719 - rustc_interface[7ca501d7f8f3a34f]::interface::run_compiler::<core[85b4fd477ce5bb21]::result::Result<(), rustc_span[adb133ac03280fc1]::ErrorGuaranteed>, rustc_driver_impl[e279e4f1fedd9109]::run_compiler::{closure#0}>::{closure#0}
  47:     0x7f7bffdbe705 - std[5a8e7f94216a9138]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[7ca501d7f8f3a34f]::util::run_in_thread_with_globals<rustc_interface[7ca501d7f8f3a34f]::util::run_in_thread_pool_with_globals<rustc_interface[7ca501d7f8f3a34f]::interface::run_compiler<core[85b4fd477ce5bb21]::result::Result<(), rustc_span[adb133ac03280fc1]::ErrorGuaranteed>, rustc_driver_impl[e279e4f1fedd9109]::run_compiler::{closure#0}>::{closure#0}, core[85b4fd477ce5bb21]::result::Result<(), rustc_span[adb133ac03280fc1]::ErrorGuaranteed>>::{closure#0}, core[85b4fd477ce5bb21]::result::Result<(), rustc_span[adb133ac03280fc1]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[85b4fd477ce5bb21]::result::Result<(), rustc_span[adb133ac03280fc1]::ErrorGuaranteed>>
  48:     0x7f7bffdbe532 - <<std[5a8e7f94216a9138]::thread::Builder>::spawn_unchecked_<rustc_interface[7ca501d7f8f3a34f]::util::run_in_thread_with_globals<rustc_interface[7ca501d7f8f3a34f]::util::run_in_thread_pool_with_globals<rustc_interface[7ca501d7f8f3a34f]::interface::run_compiler<core[85b4fd477ce5bb21]::result::Result<(), rustc_span[adb133ac03280fc1]::ErrorGuaranteed>, rustc_driver_impl[e279e4f1fedd9109]::run_compiler::{closure#0}>::{closure#0}, core[85b4fd477ce5bb21]::result::Result<(), rustc_span[adb133ac03280fc1]::ErrorGuaranteed>>::{closure#0}, core[85b4fd477ce5bb21]::result::Result<(), rustc_span[adb133ac03280fc1]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[85b4fd477ce5bb21]::result::Result<(), rustc_span[adb133ac03280fc1]::ErrorGuaranteed>>::{closure#1} as core[85b4fd477ce5bb21]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  49:     0x7f7bfab99725 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h1bff3efb61c3fa6b
                               at /rustc/f8131a48a46ac3bc8a3d0fe0477055b132cffdc3/library/alloc/src/boxed.rs:2016:9
  50:     0x7f7bfab99725 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h83141cf549dced8a
                               at /rustc/f8131a48a46ac3bc8a3d0fe0477055b132cffdc3/library/alloc/src/boxed.rs:2016:9
  51:     0x7f7bfab99725 - std::sys::pal::unix::thread::Thread::new::thread_start::hbe9287fdd7c325bc
                               at /rustc/f8131a48a46ac3bc8a3d0fe0477055b132cffdc3/library/std/src/sys/pal/unix/thread.rs:108:17
  52:     0x7f7bfa94b9eb - <unknown>
  53:     0x7f7bfa9cf7cc - <unknown>
  54:                0x0 - <unknown>

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.78.0-nightly (f8131a48a 2024-02-21) running on x86_64-unknown-linux-gnu

query stack during panic:
#0 [eval_to_allocation_raw] const-evaluating + checking `main::promoted[1]`
#1 [eval_to_const_value_raw] simplifying constant for the type system `main::promoted[1]`  |  = note: this failure-note originates in the macro `assert_eq` (in Nightly builds, run with -Z macro-backtrace for more info)

#2 [mir_drops_elaborated_and_const_checked] elaborating drops for `main`
#3 [analysis] running analysis passes on this crate
end of query stack
error: aborting due to 2 previous errors; 1 warning emitted

For more information about this error, try `rustc --explain E0277`.

```

</p>
</details>

### LINKED ISSUE #123152: ICE: `offset of unsized field (type S) cannot be computed statically`
### Code

(reduced)

```Rust
use std::mem::offset_of;

struct C<T> {
    v: T,
    w: T,
}

struct S {
    v: str,
    w: u16,
}

impl S {
    fn offs_in_c_colon() -> usize {
        offset_of!(C::<Self>, w)
    }
}

fn main() {}
```

(original)

<details><summary><strong>Original Code</strong></summary>
<p>

```Rust
#![feature(offset_of_nested)]

use std::mem::offset_of;

struct C<T> {
    v: T,
    w: T,
}

struct S {
    v: str,
    w: u16,
}

impl S {
    fn v_offs() -> usize {
        offset_of!(Self, v)
    }
    fn v_offs_wrong_syntax() {
        offset_of!(Self, Self::v); //~ offset_of expects dot-separated field and variant names
        offset_of!(S, Self); //~ no field `Self` on type `S`
    }
    fn offs_in_c() -> usize {
        offset_of!(C<Self>, w)
    }
    fn offs_in_c_colon() -> usize {
        offset_of!(C::<Self>, w)
    }
}

mod m {
    use std::mem::offset_of;
    fn off() {
        offset_of!(self::S, v); //~ ERROR cannot find type `S` in module
        offset_of!(super::S, v);
        offset_of!(crate::S, v);
    }
    impl super::n::T {
        fn v_offs_self() -> usize {
            offset_of!(Self, v) //~ ERROR field `v` of struct `T` is private
        }
    }
}

mod n {
    pub struct T {
        v: u8,
    }
}

fn main() {
    offset_of!(self::S, v);
    offset_of!(Self, v); //~ ERROR cannot find type `Self` in this scope

    offset_of!(S, self); //~ no field `self` on type `S`
    offset_of!(S, v.self); //~ no field `self` on type `u8`
}

```

</p>
</details>

### Note
I guess the original code is mutated from [`tests/ui/offset-of/offset-of-self.rs`](https://github.com/rust-lang/rust/blob/c9f8f3438a8134a413aa5d4903e0196e44e37bbc/tests/ui/offset-of/offset-of-self.rs), 
where the type of field `v` of `struct S` is tweaked from `u8` to `str`.

### Meta

`rustc --version --verbose`:
```
rustc 1.79.0-nightly (c9f8f3438 2024-03-27)
binary: rustc
commit-hash: c9f8f3438a8134a413aa5d4903e0196e44e37bbc
commit-date: 2024-03-27
host: x86_64-apple-darwin
release: 1.79.0-nightly
LLVM version: 18.1.2
```

### Command
`rustc` with no other options

### Error output

```
error[E0277]: the size for values of type `str` cannot be known at compilation time
 --> 0327/reduced_125C0267.rs:9:8
  |
9 |     v: str,
  |        ^^^ doesn't have a size known at compile-time
  |
  = help: the trait `Sized` is not implemented for `str`
  = note: only the last field of a struct may have a dynamically sized type
  = help: change the field's type to have a statically known size
help: borrowed types always have a statically known size
  |
9 |     v: &str,
  |        +
help: the `Box` type always has a statically known size and allocates its contents in the heap
  |
9 |     v: Box<str>,
  |        ++++   +

```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
thread 'rustc' panicked at /rustc/c9f8f3438a8134a413aa5d4903e0196e44e37bbc/compiler/rustc_target/src/abi/mod.rs:270:13:
offset of unsized field (type S) cannot be computed statically
stack backtrace:
   0: _rust_begin_unwind
   1: core::panicking::panic_fmt
   2: <rustc_target::abi::TyAndLayout<rustc_middle::ty::Ty>>::offset_of_subfield::<rustc_mir_transform::known_panics_lint::ConstPropagator, core::iter::adapters::copied::Copied<core::slice::iter::Iter<(rustc_target::abi::VariantIdx, rustc_target::abi::FieldIdx)>>>
   3: <rustc_mir_transform::known_panics_lint::ConstPropagator as rustc_middle::mir::visit::Visitor>::visit_assign
   4: <rustc_mir_transform::known_panics_lint::ConstPropagator as rustc_middle::mir::visit::Visitor>::visit_basic_block_data
   5: <rustc_mir_transform::known_panics_lint::ConstPropagator as rustc_middle::mir::visit::Visitor>::visit_body
   6: <rustc_mir_transform::known_panics_lint::KnownPanicsLint as rustc_mir_transform::pass_manager::MirLint>::run_lint
   7: rustc_mir_transform::pass_manager::run_passes_inner
   8: rustc_mir_transform::run_analysis_to_runtime_passes
   9: rustc_mir_transform::mir_drops_elaborated_and_const_checked
      [... omitted 1 frame ...]
  10: rustc_interface::passes::analysis
      [... omitted 1 frame ...]
  11: <rustc_interface::queries::QueryResult<&rustc_middle::ty::context::GlobalCtxt>>::enter::<core::result::Result<(), rustc_span::ErrorGuaranteed>, rustc_driver_impl::run_compiler::{closure#0}::{closure#1}::{closure#3}>
  12: rustc_interface::interface::run_compiler::<core::result::Result<(), rustc_span::ErrorGuaranteed>, rustc_driver_impl::run_compiler::{closure#0}>::{closure#0}
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

error: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: please attach the file at `/Volumes/T7/workspace/placeholder_rustexec/rustc-ice-2024-03-28T05_00_14-68115.txt` to your bug report

query stack during panic:
#0 [mir_drops_elaborated_and_const_checked] elaborating drops for `<impl at 0327/reduced_125C0267.rs:13:1: 13:7>::offs_in_c_colon`
#1 [analysis] running analysis passes on this crate
end of query stack
error: aborting due to 1 previous error

For more information about this error, try `rustc --explain E0277`.
```

</p>
</details>

### Related Issues
I can find various [`offset_of` related ICEs](https://github.com/rust-lang/rust/issues?q=is%3Aissue+label%3AI-ICE+offset_of), but none of them has the same ICE location as this one.

### PR DESCRIPTION
**Pull request by gurry**
Fixes #121473 
Fixes #123152

### CODE REVIEW

File: compiler/rustc_ty_utils/src/layout.rs [hunk 1]
```diff
@@ -503,6 +505,23 @@ fn layout_of_uncached<'tcx>(
...
+            };
+
+            if def.is_struct()
+                && let Some((_, fields_except_last)) =
+                    def.non_enum_variant().fields.raw.split_last()
+                && fields_except_last.iter().any(is_unsized_field)
+            {
+                cx.tcx.dcx().span_delayed_bug(
+                    tcx.def_span(def.did()),
+                    "only the last field of a a struct can be unsized",
```
Comment (matthiaskrgr) [inline compiler/rustc_ty_utils/src/layout.rs:520]: "a  a"

**Review by matthiaskrgr — CHANGES_REQUESTED** [review]

File: compiler/rustc_ty_utils/src/layout.rs (hunk 1 above)
Comment (gurry) [reply compiler/rustc_ty_utils/src/layout.rs:520]: Oops

Comment (gurry) [reply compiler/rustc_ty_utils/src/layout.rs]: Fixed

**Comment by gurry** [comment]
> The job **`x86_64-gnu-llvm-16`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/actions/runs/8035693617/job/21948608414) [(plain)](https://github.com/rust-lang/rust/commit/586d57eae88fb54ee5f64c6f53ed21b07fb95b60/checks/21948608414/logs)
> 
> Click to see the possible cause of the failure (guessed by this bot)
> ```
> <snip>
> ---
>    Compiling object v0.32.2
>    Compiling icu_provider_adapters v1.4.0
>    Compiling icu_list v1.4.0
>    Compiling rustc_fluent_macro v0.0.0 (/checkout/compiler/rustc_fluent_macro)
> note: no errors encountered even though delayed bugs were created
> 
> note: those delayed bugs will now be shown as internal compiler errors
> error: internal compiler error: only the last field of a struct can be unsized
>     --> /cargo/registry/src/index.crates.io-6f17d22bba15001f/serde-1.0.196/src/private/de.rs:2194:5
>      |
>      |
> 2194 |     struct SeqRefDeserializer<'a, 'de: 'a, E>
>      |
> note: delayed at compiler/rustc_ty_utils/src/layout.rs:518:30
> note: delayed at compiler/rustc_ty_utils/src/layout.rs:518:30
>          0: <rustc_errors::DiagCtxtInner>::emit_diagnostic
>          1: <rustc_errors::DiagCtxt>::emit_diagnostic
>          2: <rustc_errors::diagnostic::DiagnosticBuilder>::emit_producing_error_guaranteed
>          3: rustc_ty_utils::layout::layout_of_uncached
>          4: rustc_ty_utils::layout::layout_of
>          5: rustc_query_impl::plumbing::__rust_begin_short_backtrace::<rustc_query_impl::query_impl::layout_of::dynamic_query::{closure#2}::{closure#0}, rustc_middle::query::erase::Erased<[u8; 16]>>
>          6: <rustc_query_impl::query_impl::layout_of::dynamic_query::{closure#2} as core::ops::function::FnOnce<(rustc_middle::ty::context::TyCtxt, rustc_middle::ty::ParamEnvAnd<rustc_middle::ty::Ty>)>>::call_once
>          7: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::DynamicConfig<rustc_query_system::query::caches::DefaultCache<rustc_middle::ty::ParamEnvAnd<rustc_middle::ty::Ty>, rustc_middle::query::erase::Erased<[u8; 16]>>, false, true, false>, rustc_query_impl::plumbing::QueryCtxt, false>
>          8: rustc_query_impl::query_impl::layout_of::get_query_non_incr::__rust_end_short_backtrace
>          9: rustc_middle::query::plumbing::query_get_at::<rustc_query_system::query::caches::DefaultCache<rustc_middle::ty::ParamEnvAnd<rustc_middle::ty::Ty>, rustc_middle::query::erase::Erased<[u8; 16]>>>
>         10: <rustc_mir_transform::known_panics_lint::KnownPanicsLint as rustc_mir_transform::pass_manager::MirLint>::run_lint
>         12: rustc_mir_transform::run_analysis_to_runtime_passes
>         13: rustc_mir_transform::mir_drops_elaborated_and_const_checked
>         14: rustc_query_impl::plumbing::__rust_begin_short_backtrace::<rustc_query_impl::query_impl::mir_drops_elaborated_and_const_checked::dynamic_query::{closure#2}::{closure#0}, rustc_middle::query::erase::Erased<[u8; 8]>>
>         15: <rustc_query_impl::query_impl::mir_drops_elaborated_and_const_checked::dynamic_query::{closure#2} as core::ops::function::FnOnce<(rustc_middle::ty::context::TyCtxt, rustc_span::def_id::LocalDefId)>>::call_once
> <snip>

This ICE occurs because the `is_unsized_field` lambda I have added in this PR returns `true` for an `Alias` type such as `<&'a [i32] as IntoIterator>::IntoIter` . The following snippet reproduces the problem:

```rust
struct GoodStruct<'a>
{
    field1: <&'a [i32] as IntoIterator>::IntoIter,
    field2: i32
}

fn main() {
    let _s = GoodStruct { field1: [1, 3].iter(), field2: 3 };
}
```

`field1` here is an `Alias` type and should be sized but `is_unsized_field` concludes it is unsized. And since it's not the last field, we end up raising the delayed bug. 

Here's is the current implementation of `is_unsized_field`:
https://github.com/rust-lang/rust/blob/586d57eae88fb54ee5f64c6f53ed21b07fb95b60/compiler/rustc_ty_utils/src/layout.rs#L508-L511

How should I change it so that it returns `false` for `Alias` types? I don't presume it is safe to just dumbly return `false` if the type is an `Alias` type. Please help @matthiaskrgr @oli-obk

**Comment by oli-obk** [comment]
You need to use the param env passed to the layout_of query, not a new one.

I'll give this a real review later today

**Comment by gurry** [comment]
> You need to use the param env passed to the layout_of query, not a new one.

I tried with the param_env passed in, but still got the same ICE's :(

Will await your review

File: compiler/rustc_ty_utils/src/layout.rs [hunk 2]
```diff
@@ -503,6 +505,23 @@ fn layout_of_uncached<'tcx>(
                 ));
             }
 
+            let is_unsized_field = |field: &FieldDef| {
+                let param_env = tcx.param_env(def.did());
+                !tcx.type_of(field.did).instantiate_identity().is_sized(tcx, param_env)
```
Comment (oli-obk) [inline compiler/rustc_ty_utils/src/layout.rs:510]: The issue with projections is that they must implement `Sized` on their own, meaning they must not have a `?Sized` if generic, or normalize to something that is known to be `Sized`.

So... basically what we'll have to do is invoke the query machinery and let it solve this for us:

```rust
tcx.infer_ctxt().build().type_implements_trait(sized_trait, [field_type], param_env).must_apply_modulo_regions()
```

side-note: you're right in using the struct's `param_env` as well as `instantiate_identity`, we need to only know this of the generic trait, not after instantiating its generic params.

Comment (gurry) [reply compiler/rustc_ty_utils/src/layout.rs:510]: Thanks. Will try it out.

Comment (gurry) [reply compiler/rustc_ty_utils/src/layout.rs:510]: I've changed the implementation of `is_unsized_field` to this:
```rust
            let is_unsized_field = |field: &FieldDef| {
                let param_env = tcx.param_env(def.did());
                let field_ty = tcx.type_of(field.did).skip_binder();
                let sized_trait = tcx.require_lang_item(hir::LangItem::Sized, None);
                !tcx.infer_ctxt().build().type_implements_trait(sized_trait, [field_ty], param_env).must_apply_modulo_regions()
            };
```
All the ICEs while building stdlib are gone but when I tried to build the below code `is_unsized_field` still returns `true` (i.e. `trait_implements_trait(...).must_apply_modulo_regions()` returns `false`) for the `StructWithProjections` struct below and it triggers may span delayed bug causing the ICE:

```rust
use std::mem::size_of;

struct StructWithProjections<'a>
{
    field1: i32,
    field2: <&'a [i32] as IntoIterator>::IntoIter,
    pub field3: [u8; 16],
}

pub fn main() {
    assert_eq!(size_of::<StructWithProjections>(), 21);
}
```

I couldn't figure out what I'm doing wrong.

Comment (oli-obk) [reply compiler/rustc_ty_utils/src/layout.rs:510]: My next step would be to set `RUSTC_LOG=[evaluate_obligation]` (only for the command line the failing test is showing, and remember to dump to a file). This is a lot of info, and hard to process, but it should have all the info needed to see what's wrong. If you want we can do a screen share pairing session so you don't have to sit infront of this wall of text

Comment (gurry) [reply compiler/rustc_ty_utils/src/layout.rs:510]: Thanks Oli. I'll try that out on my own first and contact you if I get stuck.

Comment (gurry) [reply compiler/rustc_ty_utils/src/layout.rs:510]: I analyzed the logs of the compilation of the above snippet of code containing `StructWithProjections` having `field2` as a projection of type `<&'a [i32] as IntoIterator>::IntoIter`. The root cause of the failure seems to be a `Sorts` error while trying to relate `<<&[i32] as std::iter::IntoIterator>::IntoIter as std::marker::Sized>`  as the super type of  `<std::slice::Iter<'_, i32> as std::marker::Sized>` (wherein the latter was obtained by normalizing the former). 

Here's the relevant subset of the logs:
```text
[compiler\rustc_ty_utils\src\layout.rs:514:17] ">>> is_unsized_field" = ">>> is_unsized_field"
[compiler\rustc_ty_utils\src\layout.rs:514:17] field.name = "field2"
│ │ │ │ │ │ │ │ ├─┐rustc_trait_selection::infer::type_implements_trait trait_def_id=DefId(2:31977 ~ core[f031]::marker::Sized), param_env=ParamEnv { caller_bounds: [], reveal: UserFacing }
│ │ │ │ │ │ │ │ │ ├─  0ms DEBUG rustc_middle::ty::region type_flags(ReBound(DebruijnIndex(1), BoundRegion { var: 0, kind: BrAnon })) = TypeFlags(HAS_RE_BOUND)
│ │ │ │ │ │ │ │ │ ├─  0ms DEBUG rustc_traits::evaluate_obligation evaluate_obligation(canonical_goal=Canonical {
│ │ │ │ │ │ │ │ │ │     value: ParamEnvAnd {
│ │ │ │ │ │ │ │ │ │         param_env: ParamEnv {
│ │ │ │ │ │ │ │ │ │             caller_bounds: [],
│ │ │ │ │ │ │ │ │ │             reveal: UserFacing,
│ │ │ │ │ │ │ │ │ │         },
│ │ │ │ │ │ │ │ │ │         value: Binder { value: TraitPredicate(<<&[i32] as std::iter::IntoIterator>::IntoIter as std::marker::Sized>, polarity:Positive), bound_vars: [] },
│ │ │ │ │ │ │ │ │ │     },
│ │ │ │ │ │ │ │ │ │     max_universe: U0,
│ │ │ │ │ │ │ │ │ │     variables: [
│ │ │ │ │ │ │ │ │ │         CanonicalVarInfo {
│ │ │ │ │ │ │ │ │ │             kind: Region(
│ │ │ │ │ │ │ │ │ │                 U0,
│ │ │ │ │ │ │ │ │ │             ),
│ │ │ │ │ │ │ │ │ │         },
│ │ │ │ │ │ │ │ │ │     ],
│ │ │ │ │ │ │ │ │ │ })
│ │ │ │ │ │ │ │ │ ├─  0ms DEBUG rustc_infer::infer::region_constraints created new region variable '?0 in U0 with origin MiscVariable(no-location (#0))
│ │ │ │ │ │ │ │ │ ├─  0ms DEBUG rustc_middle::ty::region type_flags('?0) = TypeFlags(HAS_RE_INFER | HAS_FREE_LOCAL_REGIONS | HAS_FREE_REGIONS)
│ │ │ │ │ │ │ │ │ ├─  0ms DEBUG rustc_traits::evaluate_obligation evaluate_obligation: goal=ParamEnvAnd {
│ │ │ │ │ │ │ │ │ │     param_env: ParamEnv {
│ │ │ │ │ │ │ │ │ │         caller_bounds: [],
│ │ │ │ │ │ │ │ │ │         reveal: UserFacing,
│ │ │ │ │ │ │ │ │ │     },
│ │ │ │ │ │ │ │ │ │     value: Binder { value: TraitPredicate(<<&[i32] as std::iter::IntoIterator>::IntoIter as std::marker::Sized>, polarity:Positive), bound_vars: [] },
│ │ │ │ │ │ │ │ │ │ }
│ │ │ │ │ │ │ │ │ ├─  0ms DEBUG rustc_trait_selection::traits::select with_query_mode, query_mode=Canonical
│ │ │ │ │ │ │ │ │ ├─┐rustc_infer::infer::probe 
│ │ │ │ │ │ │ │ │ │ ├─  0ms DEBUG rustc_infer::infer start_snapshot()
│ │ │ │ │ │ │ │ │ │ ├─  0ms DEBUG rustc_infer::infer::region_constraints RegionConstraintCollector: start_snapshot
│ │ │ │ │ │ │ │ │ │ ├─┐rustc_trait_selection::traits::select::evaluate_predicate_recursively obligation=Obligation(predicate=Binder { value: TraitPredicate(<<&[i32] as std::iter::IntoIterator>::IntoIter as std::marker::Sized>, polarity:Positive), bound_vars: [] }, depth=0), previous_stack=None
│ │ │ │ │ │ │ │ │ │ │ ├─┐rustc_trait_selection::traits::select::evaluate_trait_predicate_recursively obligation=Obligation(predicate=Binder { value: TraitPredicate(<<&[i32] as std::iter::IntoIterator>::IntoIter as std::marker::Sized>, polarity:Positive), bound_vars: [] }, depth=0)
│ │ │ │ │ │ │ │ │ │ │ │ ├─  0ms DEBUG rustc_trait_selection::traits::select fresh_trait_pred=Binder { value: TraitPredicate(<<&[i32] as std::iter::IntoIterator>::IntoIter as std::marker::Sized>, polarity:Positive), bound_vars: [] }
│ │ │ │ │ │ │ │ │ │ │ │ ├─  0ms DEBUG rustc_trait_selection::traits::select get_provisional = None, fresh_trait_pred=Binder { value: TraitPredicate(<<&[i32] as std::iter::IntoIterator>::IntoIter as std::marker::Sized>, polarity:Positive), bound_vars: [] }
│ │ │ │ │ │ │ │ │ │ │ │ ├─┐rustc_trait_selection::traits::select::candidate_from_obligation stack=TraitObligationStack(Obligation(predicate=Binder { value: TraitPredicate(<<&[i32] as std::iter::IntoIterator>::IntoIter as std::marker::Sized>, polarity:Positive), bound_vars: [] }, depth=0))
│ │ │ │ │ │ │ │ │ │ │ │ │ ├─  0ms DEBUG rustc_trait_selection::traits::select cache_fresh_trait_pred=Binder { value: TraitPredicate(<<&[i32] as std::iter::IntoIterator>::IntoIter as std::marker::Sized>, polarity:Positive), bound_vars: [] }
│ │ │ │ │ │ │ │ │ │ │ │ │ ├─  0ms DEBUG rustc_trait_selection::traits::select is_knowable(intercrate=false)
│ │ │ │ │ │ │ │ │ │ │ │ │ ├─┐rustc_trait_selection::traits::select::candidate_assembly::assemble_candidates 
[compiler\rustc_trait_selection\src\traits\select\candidate_assembly.rs:42:9] &obligation = Obligation(predicate=Binder { value: TraitPredicate(<<&[i32] as std::iter::IntoIterator>::IntoIter as std::marker::Sized>, polarity:Positive), bound_vars: [] }, depth=0)
[compiler\rustc_trait_selection\src\traits\select\candidate_assembly.rs:66:13] ">>> positive polarity" = ">>> positive polarity"
│ │ │ │ │ │ │ │ │ │ │ │ │ │ ├─┐rustc_trait_selection::traits::select::candidate_assembly::assemble_candidates_for_trait_alias 
│ │ │ │ │ │ │ │ │ │ │ │ │ │ │ ├─  0ms DEBUG rustc_trait_selection::traits::select::candidate_assembly self_ty=Alias(Projection, AliasTy { args: [&'?0 [i32]], def_id: DefId(2:8110 ~ core[f031]::iter::traits::collect::IntoIterator::IntoIter) })
│ │ │ │ │ │ │ │ │ │ │ │ │ │ ├─┘
[compiler\rustc_trait_selection\src\traits\select\candidate_assembly.rs:72:13] &obligation.predicate = Binder {
    value: TraitPredicate(<<&[i32] as std::iter::IntoIterator>::IntoIter as std::marker::Sized>, polarity:Positive),
    bound_vars: [],
}
[compiler\rustc_trait_selection\src\traits\select\candidate_assembly.rs:95:17] ">>> sized_trait" = ">>> sized_trait"
[compiler\rustc_trait_selection\src\traits\select\mod.rs:2104:9] &self_ty.kind() = Alias(
    Projection,
    AliasTy {
        args: [
        &'?0 [i32],
        ],
        def_id: DefId(2:8110 ~ core[f031]::iter::traits::collect::IntoIterator::IntoIter),
    },
)
[compiler\rustc_trait_selection\src\traits\select\candidate_assembly.rs:99:17] &sized_conditions = None
│ │ │ │ │ │ │ │ │ │ │ │ │ │ ├─┐rustc_trait_selection::traits::select::candidate_assembly::assemble_builtin_bound_candidates conditions=None
│ │ │ │ │ │ │ │ │ │ │ │ │ │ ├─┘
│ │ │ │ │ │ │ │ │ │ │ │ │ │ ├─┐rustc_trait_selection::traits::select::candidate_assembly::assemble_candidates_from_projected_tys obligation=Obligation(predicate=Binder { value: TraitPredicate(<<&[i32] as std::iter::IntoIterator>::IntoIter as std::marker::Sized>, polarity:Positive), bound_vars: [] }, depth=0)
│ │ │ │ │ │ │ │ │ │ │ │ │ │ │ ├─┐rustc_infer::infer::probe 
│ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ ├─  0ms DEBUG rustc_infer::infer start_snapshot()
│ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ ├─  0ms DEBUG rustc_infer::infer::region_constraints RegionConstraintCollector: start_snapshot
│ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ ├─┐rustc_infer::infer::relate::higher_ranked::enter_forall_and_leak_universe binder=Binder { value: TraitPredicate(<<&[i32] as std::iter::IntoIterator>::IntoIter as std::marker::Sized>, polarity:Positive), bound_vars: [] }
│ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ ├─  0ms DEBUG rustc_infer::infer::relate::higher_ranked return=TraitPredicate(<<&[i32] as std::iter::IntoIterator>::IntoIter as std::marker::Sized>, polarity:Positive)
│ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ ├─┘
│ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ ├─  0ms DEBUG rustc_trait_selection::traits::select::candidate_assembly placeholder_trait_predicate=TraitPredicate(<<&[i32] as std::iter::IntoIterator>::IntoIter as std::marker::Sized>, polarity:Positive)
│ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ ├─  0ms DEBUG rustc_infer::traits::util super_predicates, data=TraitPredicate(<<Self as std::iter::IntoIterator>::IntoIter as std::iter::Iterator>, polarity:Positive), obligations=Map { iter: Enumerate { iter: Iter([]), count: 0 } }
│ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ ├─  0ms DEBUG rustc_infer::traits::util super_predicates, data=TraitPredicate(<<Self as std::iter::IntoIterator>::IntoIter as std::marker::Sized>, polarity:Positive), obligations=Map { iter: Enumerate { iter: Iter([]), count: 0 } }
│ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ ├─  0ms DEBUG rustc_middle::ty::generic_args shift_vars(val=&'?0 [i32], binders_passed=1, has_escaping_bound_vars=false)
│ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ ├─  0ms DEBUG rustc_middle::ty::generic_args shift_vars(val=&'?0 [i32], binders_passed=1, has_escaping_bound_vars=false)
│ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ ├─  0ms DEBUG rustc_middle::ty::generic_args shift_vars(val=&'?0 [i32], binders_passed=1, has_escaping_bound_vars=false)
│ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ ├─  0ms DEBUG rustc_middle::ty::generic_args shift_vars(val=&'?0 [i32], binders_passed=1, has_escaping_bound_vars=false)
[compiler\rustc_trait_selection\src\traits\select\candidate_assembly.rs:199:21] &bound = Binder { value: ProjectionPredicate(AliasTy { args: [Alias(Projection, AliasTy { args: [&'?0 [i32]], def_id: DefId(2:8110 ~ core[f031]::iter::traits::collect::IntoIterator::IntoIter) })], def_id: DefId(2:8256 ~ core[f031]::iter::traits::iterator::Iterator::Item) }, Term::Ty(Alias(Projection, AliasTy { args: [&'?0 [i32]], def_id: DefId(2:8109 ~ core[f031]::iter::traits::collect::IntoIterator::Item) }))), bound_vars: [] }
[compiler\rustc_trait_selection\src\traits\select\candidate_assembly.rs:201:25] ">>> as_trait_clause()" = ">>> as_trait_clause()"
[compiler\rustc_trait_selection\src\traits\select\candidate_assembly.rs:199:21] &bound = Binder { value: TraitPredicate(<<&[i32] as std::iter::IntoIterator>::IntoIter as std::iter::Iterator>, polarity:Positive), bound_vars: [] }
│ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ ├─┐rustc_infer::infer::probe 
│ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ ├─  0ms DEBUG rustc_infer::infer start_snapshot()
│ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ ├─  0ms DEBUG rustc_infer::infer::region_constraints RegionConstraintCollector: start_snapshot
│ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ ├─┐rustc_trait_selection::traits::select::match_normalize_trait_ref obligation=Obligation(predicate=Binder { value: TraitPredicate(<<&[i32] as std::iter::IntoIterator>::IntoIter as std::marker::Sized>, polarity:Positive), bound_vars: [] }, depth=0), trait_bound=Binder { value: <<&[i32] as std::iter::IntoIterator>::IntoIter as std::iter::Iterator>, bound_vars: [] }, placeholder_trait_ref=<<&[i32] as std::iter::IntoIterator>::IntoIter as std::marker::Sized>
[compiler\rustc_trait_selection\src\traits\select\mod.rs:1661:9] ">> match_normalize_trait_ref" = ">> match_normalize_trait_ref"
[compiler\rustc_trait_selection\src\traits\select\mod.rs:1661:9] &obligation = Obligation(predicate=Binder { value: TraitPredicate(<<&[i32] as std::iter::IntoIterator>::IntoIter as std::marker::Sized>, polarity:Positive), bound_vars: [] }, depth=0)
[compiler\rustc_trait_selection\src\traits\select\mod.rs:1661:9] &trait_bound = Binder {
    value: <<&[i32] as std::iter::IntoIterator>::IntoIter as std::iter::Iterator>,
    bound_vars: [],
}
[compiler\rustc_trait_selection\src\traits\select\mod.rs:1661:9] &placeholder_trait_ref = <<&[i32] as std::iter::IntoIterator>::IntoIter as std::marker::Sized>
[compiler\rustc_trait_selection\src\traits\select\mod.rs:1664:13] ">> match_normalize_trait_ref returning early" = ">> match_normalize_trait_ref returning early"
│ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ ├─  0ms DEBUG rustc_trait_selection::traits::select return=Err(())
│ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ ├─┘
│ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ ├─┐rustc_infer::infer::rollback_to 
│ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ ├─  0ms DEBUG rustc_infer::infer::undo_log rollback_to(0)
│ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ ├─  0ms DEBUG rustc_infer::infer::region_constraints RegionConstraintCollector: rollback_to(RegionSnapshot)
│ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ ├─┘
│ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ ├─┘
[compiler\rustc_trait_selection\src\traits\select\candidate_assembly.rs:199:21] &bound = Binder { value: TraitPredicate(<<&[i32] as std::iter::IntoIterator>::IntoIter as std::marker::Sized>, polarity:Positive), bound_vars: [] }
│ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ ├─┐rustc_infer::infer::probe 
│ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ ├─  0ms DEBUG rustc_infer::infer start_snapshot()
│ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ ├─  0ms DEBUG rustc_infer::infer::region_constraints RegionConstraintCollector: start_snapshot
│ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ ├─┐rustc_trait_selection::traits::select::match_normalize_trait_ref obligation=Obligation(predicate=Binder { value: TraitPredicate(<<&[i32] as std::iter::IntoIterator>::IntoIter as std::marker::Sized>, polarity:Positive), bound_vars: [] }, depth=0), trait_bound=Binder { value: <<&[i32] as std::iter::IntoIterator>::IntoIter as std::marker::Sized>, bound_vars: [] }, placeholder_trait_ref=<<&[i32] as std::iter::IntoIterator>::IntoIter as std::marker::Sized>
[compiler\rustc_trait_selection\src\traits\select\mod.rs:1661:9] ">> match_normalize_trait_ref" = ">> match_normalize_trait_ref"
[compiler\rustc_trait_selection\src\traits\select\mod.rs:1661:9] &obligation = Obligation(predicate=Binder { value: TraitPredicate(<<&[i32] as std::iter::IntoIterator>::IntoIter as std::marker::Sized>, polarity:Positive), bound_vars: [] }, depth=0)
[compiler\rustc_trait_selection\src\traits\select\mod.rs:1661:9] &trait_bound = Binder {
    value: <<&[i32] as std::iter::IntoIterator>::IntoIter as std::marker::Sized>,
    bound_vars: [],
}
[compiler\rustc_trait_selection\src\traits\select\mod.rs:1661:9] &placeholder_trait_ref = <<&[i32] as std::iter::IntoIterator>::IntoIter as std::marker::Sized>
[compiler\rustc_trait_selection\src\traits\select\mod.rs:1670:13] ">>> normalize_with_depth" = ">>> normalize_with_depth"
│ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ ├─┐rustc_trait_selection::traits::normalize::normalize_with_depth_to depth=1, value=Binder { value: <<&[i32] as std::iter::IntoIterator>::IntoIter as std::marker::Sized>, bound_vars: [] }
│ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ ├─  0ms DEBUG rustc_trait_selection::traits::normalize obligations.len=0
│ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ ├─  0ms DEBUG rustc_trait_selection::traits::normalize value=Binder { value: <<&[i32] as std::iter::IntoIterator>::IntoIter as std::marker::Sized>, bound_vars: [] }
│ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ ├─┐rustc_trait_selection::traits::project::opt_normalize_projection_type projection_ty=AliasTy { args: [&'?0 [i32]], def_id: DefId(2:8110 ~ core[f031]::iter::traits::collect::IntoIterator::IntoIter) }, depth=1
│ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ ├─  0ms DEBUG rustc_trait_selection::traits::project no cache
│ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ ├─┐rustc_trait_selection::traits::project::project obligation=Obligation(predicate=AliasTy { args: [&'?0 [i32]], def_id: DefId(2:8110 ~ core[f031]::iter::traits::collect::IntoIterator::IntoIter) }, depth=1)
│ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ ├─┐rustc_trait_selection::traits::project::assemble_candidates_from_predicates obligation=Obligation(predicate=AliasTy { args: [&'?0 [i32]], def_id: DefId(2:8110 ~ core[f031]::iter::traits::collect::IntoIterator::IntoIter) }, depth=1)
│ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ ├─┘
│ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ ├─  0ms DEBUG rustc_trait_selection::traits::project assemble_candidates_from_trait_def(..)
│ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ ├─  0ms DEBUG rustc_trait_selection::traits::project assemble_candidates_from_object_ty(..)
│ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ ├─┐rustc_trait_selection::traits::project::assemble_candidates_from_impls 
│ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ ├─┐rustc_infer::infer::commit_if_ok 
│ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ ├─  0ms DEBUG rustc_infer::infer start_snapshot()
│ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ ├─  0ms DEBUG rustc_infer::infer::region_constraints RegionConstraintCollector: start_snapshot
│ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ ├─┐rustc_trait_selection::traits::select::poly_select obligation=Obligation(predicate=Binder { value: TraitPredicate(<&[i32] as std::iter::IntoIterator>, polarity:Positive), bound_vars: [] }, depth=1)
│ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ ├─┐rustc_trait_selection::traits::select::candidate_from_obligation stack=TraitObligationStack(Obligation(predicate=Binder { value: TraitPredicate(<&[i32] as std::iter::IntoIterator>, polarity:Positive), bound_vars: [] }, depth=1))
│ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ ├─  0ms DEBUG rustc_trait_selection::traits::select cache_fresh_trait_pred=Binder { value: TraitPredicate(<&[i32] as std::iter::IntoIterator>, polarity:Positive), bound_vars: [] }
│ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ ├─  0ms DEBUG rustc_trait_selection::traits::select CACHE HIT
│ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ ├─  0ms DEBUG rustc_trait_selection::traits::select return=Ok(Some(ImplCandidate(DefId(2:10987 ~ core[f031]::slice::iter::{impl#0}))))
│ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ ├─┘
│ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ ├─┐rustc_trait_selection::traits::select::confirmation::confirm_candidate obligation=Obligation(predicate=Binder { value: TraitPredicate(<&[i32] as std::iter::IntoIterator>, polarity:Positive), bound_vars: [] }, depth=1), candidate=ImplCandidate(DefId(2:10987 ~ core[f031]::slice::iter::{impl#0}))
│ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ ├─  0ms DEBUG rustc_trait_selection::traits::select::confirmation confirm_impl_candidate, obligation=Obligation(predicate=Binder { value: TraitPredicate(<&[i32] as std::iter::IntoIterator>, polarity:Positive), bound_vars: [] }, depth=1), impl_def_id=DefId(2:10987 ~ core[f031]::slice::iter::{impl#0})
│ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ ├─┐rustc_trait_selection::traits::select::match_impl impl_def_id=DefId(2:10987 ~ core[f031]::slice::iter::{impl#0}), impl_trait_header=EarlyBinder { value: ImplTraitHeader { trait_ref: <&'a [T] as std::iter::IntoIterator>, polarity: Positive, unsafety: Normal } }, obligation=Obligation(predicate=Binder { value: TraitPredicate(<&[i32] as std::iter::IntoIterator>, polarity:Positive), bound_vars: [] }, depth=1)
│ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ ├─┐rustc_infer::infer::relate::higher_ranked::enter_forall_and_leak_universe binder=Binder { value: TraitPredicate(<&[i32] as std::iter::IntoIterator>, polarity:Positive), bound_vars: [] }
│ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ ├─  0ms DEBUG rustc_infer::infer::relate::higher_ranked return=TraitPredicate(<&[i32] as std::iter::IntoIterator>, polarity:Positive)
│ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ ├─┘
│ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ ├─  0ms DEBUG rustc_infer::infer::region_constraints created new region variable '?1 in U0 with origin RegionParameterDefinition(no-location (#0), "'a")
│ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ ├─  0ms DEBUG rustc_infer::infer::type_variable new_var(index=?0t, universe=U0, origin=TypeVariableOrigin { kind: TypeParameterDefinition("T", DefId(2:10989 ~ core[f031]::slice::iter::{impl#0}::T)), span: no-location (#0) })
│ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ ├─  0ms DEBUG rustc_middle::ty::generic_args shift_vars(val=?0t, binders_passed=0, has_escaping_bound_vars=false)
│ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ ├─  0ms DEBUG rustc_middle::ty::region type_flags('?1) = TypeFlags(HAS_RE_INFER | HAS_FREE_LOCAL_REGIONS | HAS_FREE_REGIONS)
│ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ ├─  0ms DEBUG rustc_trait_selection::traits::select impl_trait_header=ImplTraitHeader { trait_ref: <&[_] as std::iter::IntoIterator>, polarity: Positive, unsafety: Normal }
│ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ ├─┐rustc_trait_selection::traits::normalize::normalize_with_depth_to depth=2, value=<&[_] as std::iter::IntoIterator>
│ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ ├─  0ms DEBUG rustc_trait_selection::traits::normalize obligations.len=0
│ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ ├─  0ms DEBUG rustc_trait_selection::traits::normalize value=<&[_] as std::iter::IntoIterator>
│ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ ├─  0ms DEBUG rustc_trait_selection::traits::normalize result=<&[_] as std::iter::IntoIterator>, obligations.len=0
│ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ ├─  0ms DEBUG rustc_trait_selection::traits::normalize normalizer.obligations=[]
│ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ ├─┘
│ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ ├─  0ms DEBUG rustc_trait_selection::traits::select impl_trait_ref=<&[_] as std::iter::IntoIterator>, placeholder_obligation_trait_ref=<&[i32] as std::iter::IntoIterator>
│ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ ├─┐rustc_infer::infer::at::eq define_opaque_types=No, a=<&[i32] as std::iter::IntoIterator>, b=<&[_] as std::iter::IntoIterator>
│ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ ├─┐rustc_infer::infer::relate::equate::tys a=&'?0 [i32], b=&'?1 [?0t]
│ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ ├─  0ms DEBUG rustc_infer::infer::relate::equate Equate.regions('?0, '?1)
│ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ ├─┐rustc_infer::infer::region_constraints::make_subregion sub='?0, sup='?1
│ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ ├─  0ms DEBUG rustc_infer::infer::region_constraints origin = Subtype(
│ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │     TypeTrace {
│ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │         cause: ObligationCause {
│ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │             span: no-location (#0),
│ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │             body_id: DefId(0:0 ~ ice_non_last_unsized_field_issue_121473[4941]),
│ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │             code: MatchImpl(
│ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │                 ObligationCause {
│ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │                     span: no-location (#0),
│ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │                     body_id: DefId(0:0 ~ ice_non_last_unsized_field_issue_121473[4941]),
│ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │                     code: MiscObligation,
│ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │                 },
│ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │                 DefId(2:10987 ~ core[f031]::slice::iter::{impl#0}),
│ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │             ),
│ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │         },
│ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │         values: PolyTraitRefs(
│ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │             ExpectedFound {
│ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │                 expected: Binder {
│ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │                     value: <&[i32] as std::iter::IntoIterator>,
│ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │                     bound_vars: [],
│ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │                 },
│ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │                 found: Binder {
│ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │                     value: <&[_] as std::iter::IntoIterator>,
│ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │                     bound_vars: [],
│ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │                 },
│ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │             },
│ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │         ),
│ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │     },
│ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ )
│ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ ├─  0ms DEBUG rustc_infer::infer::region_constraints RegionConstraintCollector: add_constraint(VarSubVar('?0, '?1))
│ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ ├─┘
│ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ ├─┐rustc_infer::infer::region_constraints::make_subregion sub='?1, sup='?0
│ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ ├─  0ms DEBUG rustc_infer::infer::region_constraints origin = Subtype(
│ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │     TypeTrace {
│ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │         cause: ObligationCause {
│ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │             span: no-location (#0),
│ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │             body_id: DefId(0:0 ~ ice_non_last_unsized_field_issue_121473[4941]),
│ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │             code: MatchImpl(
│ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │                 ObligationCause {
│ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │                     span: no-location (#0),
│ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │                     body_id: DefId(0:0 ~ ice_non_last_unsized_field_issue_121473[4941]),
│ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │                     code: MiscObligation,
│ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │                 },
│ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │                 DefId(2:10987 ~ core[f031]::slice::iter::{impl#0}),
│ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │             ),
│ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │         },
│ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │         values: PolyTraitRefs(
│ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │             ExpectedFound {
│ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │                 expected: Binder {
│ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │                     value: <&[i32] as std::iter::IntoIterator>,
│ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │                     bound_vars: [],
│ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │                 },
│ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │                 found: Binder {
│ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │                     value: <&[_] as std::iter::IntoIterator>,
│ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │                     bound_vars: [],
│ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │                 },
│ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │             },
│ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │         ),
│ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │     },
│ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ )
│ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ ├─  0ms DEBUG rustc_infer::infer::region_constraints RegionConstraintCollector: add_constraint(VarSubVar('?1, '?0))
│ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ ├─┘
│ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ ├─  0ms DEBUG rustc_infer::infer::region_constraints make_eqregion: unifying '?0 with '?1
│ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ ├─  0ms DEBUG rustc_middle::ty::relate Equate.mts(TypeAndMut { ty: [i32], mutbl: Not }, TypeAndMut { ty: [?0t], mutbl: Not })
│ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ ├─┐rustc_infer::infer::relate::equate::tys a=[i32], b=[?0t]
│ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ ├─┐rustc_infer::infer::relate::equate::tys a=i32, b=?0t
│ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ ├─┐rustc_infer::infer::relate::generalize::instantiate_ty_var target_is_expected=false, target_vid=?0t, instantiation_variance=o, source_ty=i32
│ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ ├─┐rustc_infer::infer::relate::generalize::tys t=i32
│ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ ├─  0ms DEBUG rustc_infer::infer::relate::generalize return=Ok(i32)
│ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ ├─┘
│ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ ├─  0ms DEBUG rustc_infer::infer::relate::generalize flip relation
│ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ ├─┐rustc_infer::infer::relate::equate::tys a=i32, b=i32
│ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ ├─┘
│ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ ├─┘
│ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ ├─┘
│ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ ├─┘
│ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ ├─┘
│ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ ├─┘
│ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ ├─  0ms DEBUG rustc_trait_selection::traits::select return=Ok(Normalized(['?1, ?0t], []))
│ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ ├─┘
│ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ ├─  0ms DEBUG rustc_trait_selection::traits::select::confirmation impl args, args=Normalized(['?1, ?0t], [])
│ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ ├─  0ms DEBUG rustc_trait_selection::traits::select::confirmation vtable_impl, impl_def_id=DefId(2:10987 ~ core[f031]::slice::iter::{impl#0}), args=Normalized(['?1, ?0t], []), recursion_depth=2
│ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ ├─┐rustc_trait_selection::traits::select::impl_or_trait_obligations recursion_depth=2, def_id=DefId(2:10987 ~ core[f031]::slice::iter::{impl#0}), args=['?1, ?0t], parent_trait_pred=Binder { value: TraitPredicate(<&[i32] as std::iter::IntoIterator>, polarity:Positive), bound_vars: [] }
│ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ ├─  0ms DEBUG rustc_middle::ty::generic_args shift_vars(val=?0t, binders_passed=1, has_escaping_bound_vars=false)
│ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ ├─┐rustc_trait_selection::traits::normalize::normalize_with_depth_to depth=2, value=Binder { value: TraitPredicate(<_ as std::marker::Sized>, polarity:Positive), bound_vars: [] }
│ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ ├─  0ms DEBUG rustc_trait_selection::traits::normalize obligations.len=0
│ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ ├─  0ms DEBUG rustc_trait_selection::traits::normalize value=Binder { value: TraitPredicate(<i32 as std::marker::Sized>, polarity:Positive), bound_vars: [] }
│ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ ├─  0ms DEBUG rustc_trait_selection::traits::normalize result=Binder { value: TraitPredicate(<i32 as std::marker::Sized>, polarity:Positive), bound_vars: [] }, obligations.len=0
│ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ ├─  0ms DEBUG rustc_trait_selection::traits::normalize normalizer.obligations=[]
│ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ ├─┘
│ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ ├─┘
│ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ ├─  0ms DEBUG rustc_trait_selection::traits::select::confirmation vtable_impl, impl_obligations=[Obligation(predicate=Binder { value: TraitPredicate(<i32 as std::marker::Sized>, polarity:Positive), bound_vars: [] }, depth=2)]
│ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ ├─┘
│ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ ├─  0ms DEBUG rustc_trait_selection::traits::select return=Ok(Some(ImplSourceUserDefinedData(impl_def_id=DefId(2:10987 ~ core[f031]::slice::iter::{impl#0}), args=['?1, ?0t], nested=[Obligation(predicate=Binder { value: TraitPredicate(<i32 as std::marker::Sized>, polarity:Positive), bound_vars: [] }, depth=2)])))
│ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ ├─┘
│ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ ├─  0ms DEBUG rustc_infer::infer commit_if_ok() -- r.is_ok() = true
│ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ ├─┐rustc_infer::infer::commit_from 
│ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ ├─  0ms DEBUG rustc_infer::infer::undo_log commit(1)
│ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ ├─┘
│ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ ├─┘
│ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ ├─┘
│ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ ├─  0ms DEBUG rustc_trait_selection::traits::project confirm_candidate, obligation=Obligation(predicate=AliasTy { args: [&'?0 [i32]], def_id: DefId(2:8110 ~ core[f031]::iter::traits::collect::IntoIterator::IntoIter) }, depth=1), candidate=Select(ImplSourceUserDefinedData(impl_def_id=DefId(2:10987 ~ core[f031]::slice::iter::{impl#0}), args=['?1, ?0t], nested=[Obligation(predicate=Binder { value: TraitPredicate(<i32 as std::marker::Sized>, polarity:Positive), bound_vars: [] }, depth=2)]))
│ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ ├─  0ms DEBUG rustc_trait_selection::traits::specialize translate_args(ParamEnv { caller_bounds: [], reveal: UserFacing }, DefId(2:10987 ~ core[f031]::slice::iter::{impl#0}), ['?1, ?0t], Impl(DefId(2:10987 ~ core[f031]::slice::iter::{impl#0})))
│ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ ├─  0ms DEBUG rustc_middle::ty::generic_args shift_vars(val=?0t, binders_passed=0, has_escaping_bound_vars=false)
│ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ ├─  0ms DEBUG rustc_middle::ty::generic_args shift_vars(val=?0t, binders_passed=0, has_escaping_bound_vars=false)
│ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ ├─  0ms DEBUG rustc_middle::ty::region type_flags('?1) = TypeFlags(HAS_RE_INFER | HAS_FREE_LOCAL_REGIONS | HAS_FREE_REGIONS)
│ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ ├─┘
│ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ ├─  0ms DEBUG rustc_middle::ty::region type_flags('?1) = TypeFlags(HAS_RE_INFER | HAS_FREE_LOCAL_REGIONS | HAS_FREE_REGIONS)
│ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ ├─  0ms DEBUG rustc_infer::traits::project ProjectionCacheEntry::insert_ty: adding cache entry: key=ProjectionCacheKey { ty: AliasTy { args: [&'?0 [i32]], def_id: DefId(2:8110 ~ core[f031]::iter::traits::collect::IntoIterator::IntoIter) } }, value=Normalized(Term::Ty(std::slice::Iter<'?1, i32>), [Obligation(predicate=Binder { value: TraitPredicate(<i32 as std::marker::Sized>, polarity:Positive), bound_vars: [] }, depth=2)])
│ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ ├─┘
│ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ ├─  0ms DEBUG rustc_trait_selection::traits::normalize AssocTypeNormalizer: normalized type, self.depth=1, ty=Alias(Projection, AliasTy { args: [&'?0 [i32]], def_id: DefId(2:8110 ~ core[f031]::iter::traits::collect::IntoIterator::IntoIter) }), normalized_ty=Term::Ty(std::slice::Iter<'?1, i32>), obligations.len=1
│ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ ├─  0ms DEBUG rustc_trait_selection::traits::normalize result=Binder { value: <std::slice::Iter<'_, i32> as std::marker::Sized>, bound_vars: [] }, obligations.len=1
│ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ ├─  0ms DEBUG rustc_trait_selection::traits::normalize normalizer.obligations=[Obligation(predicate=Binder { value: TraitPredicate(<i32 as std::marker::Sized>, polarity:Positive), bound_vars: [] }, depth=2)]
│ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ ├─┘
[compiler\rustc_trait_selection\src\traits\select\mod.rs:1679:9] &trait_bound = Binder {
    value: <std::slice::Iter<'_, i32> as std::marker::Sized>,
    bound_vars: [],
}
│ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ ├─┐rustc_infer::infer::at::sub define_opaque_types=No, a=Binder { value: <std::slice::Iter<'_, i32> as std::marker::Sized>, bound_vars: [] }, b=Binder { value: <<&[i32] as std::iter::IntoIterator>::IntoIter as std::marker::Sized>, bound_vars: [] }
│ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ ├─┐rustc_infer::infer::relate::higher_ranked::higher_ranked_sub sub=Binder { value: <std::slice::Iter<'_, i32> as std::marker::Sized>, bound_vars: [] }, sup=Binder { value: <<&[i32] as std::iter::IntoIterator>::IntoIter as std::marker::Sized>, bound_vars: [] }, sub_is_expected=false
│ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ ├─┐rustc_infer::infer::relate::higher_ranked::enter_forall forall=Binder { value: <<&[i32] as std::iter::IntoIterator>::IntoIter as std::marker::Sized>, bound_vars: [] }
│ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ ├─┐rustc_infer::infer::relate::higher_ranked::enter_forall_and_leak_universe binder=Binder { value: <<&[i32] as std::iter::IntoIterator>::IntoIter as std::marker::Sized>, bound_vars: [] }
│ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ ├─  0ms DEBUG rustc_infer::infer::relate::higher_ranked return=<<&[i32] as std::iter::IntoIterator>::IntoIter as std::marker::Sized>
│ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ ├─┘
│ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ ├─  0ms DEBUG rustc_infer::infer::relate::higher_ranked ?value
│ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ ├─  0ms DEBUG rustc_infer::infer::relate::higher_ranked a_prime=<std::slice::Iter<'_, i32> as std::marker::Sized>
│ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ ├─  0ms DEBUG rustc_infer::infer::relate::higher_ranked b_prime=<<&[i32] as std::iter::IntoIterator>::IntoIter as std::marker::Sized>
│ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ ├─┐rustc_infer::infer::relate::equate::tys a=std::slice::Iter<'?1, i32>, b=Alias(Projection, AliasTy { args: [&'?0 [i32]], def_id: DefId(2:8110 ~ core[f031]::iter::traits::collect::IntoIterator::IntoIter) })
│ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ ├─┘
│ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ ├─┘
│ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ ├─┘
│ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ ├─┘
[compiler\rustc_trait_selection\src\traits\select\mod.rs:1695:17] ">>> sup relate failed" = ">>> sup relate failed"
[compiler\rustc_trait_selection\src\traits\select\mod.rs:1695:17] &e = Sorts(
    ExpectedFound {
        expected: Alias(
            Projection,
            AliasTy {
                args: [
                &'?0 [i32],
                ],
                def_id: DefId(2:8110 ~ core[f031]::iter::traits::collect::IntoIterator::IntoIter),
            },
        ),
        found: std::slice::Iter<'?1, i32>,
    },
)
│ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ ├─  0ms DEBUG rustc_trait_selection::traits::select return=Err(())
│ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ ├─┘
│ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ ├─┐rustc_infer::infer::rollback_to 
│ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ ├─  0ms DEBUG rustc_infer::infer::undo_log rollback_to(0)
│ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ ├─  0ms DEBUG rustc_infer::infer::region_constraints RegionConstraintCollector: rollback_to(RegionSnapshot)
│ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ ├─┘
│ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ ├─┘
│ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ ├─┐rustc_infer::infer::rollback_to 
│ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ ├─  0ms DEBUG rustc_infer::infer::undo_log rollback_to(0)
│ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ ├─  0ms DEBUG rustc_infer::infer::region_constraints RegionConstraintCollector: rollback_to(RegionSnapshot)
│ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ ├─┘
│ │ │ │ │ │ │ │ │ │ │ │ │ │ │ ├─┘
│ │ │ │ │ │ │ │ │ │ │ │ │ │ ├─┘
│ │ │ │ │ │ │ │ │ │ │ │ │ │ ├─┐rustc_trait_selection::traits::select::candidate_assembly::assemble_candidates_from_caller_bounds 
│ │ │ │ │ │ │ │ │ │ │ │ │ │ │ ├─  0ms DEBUG rustc_trait_selection::traits::select::candidate_assembly stack.obligation=Obligation(predicate=Binder { value: TraitPredicate(<<&[i32] as std::iter::IntoIterator>::IntoIter as std::marker::Sized>, polarity:Positive), bound_vars: [] }, depth=0)
│ │ │ │ │ │ │ │ │ │ │ │ │ │ ├─┘
│ │ │ │ │ │ │ │ │ │ │ │ │ │ ├─  1ms DEBUG rustc_trait_selection::traits::select::candidate_assembly assemble_candidates_from_auto_impls, self_ty=Alias(Projection, AliasTy { args: [&'?0 [i32]], def_id: DefId(2:8110 ~ core[f031]::iter::traits::collect::IntoIterator::IntoIter) })
│ │ │ │ │ │ │ │ │ │ │ │ │ │ ├─  1ms DEBUG rustc_trait_selection::traits::select::candidate_assembly candidate list size: 0
│ │ │ │ │ │ │ │ │ │ │ │ │ ├─┘
│ │ │ │ │ │ │ │ │ │ │ │ │ ├─  1ms DEBUG rustc_trait_selection::traits::select assembled 0 candidates, stack=TraitObligationStack(Obligation(predicate=Binder { value: TraitPredicate(<<&[i32] as std::iter::IntoIterator>::IntoIter as std::marker::Sized>, polarity:Positive), bound_vars: [] }, depth=0)), candidates=[]
│ │ │ │ │ │ │ │ │ │ │ │ │ ├─┐rustc_trait_selection::traits::select::filter_impls obligation=Obligation(predicate=Binder { value: TraitPredicate(<<&[i32] as std::iter::IntoIterator>::IntoIter as std::marker::Sized>, polarity:Positive), bound_vars: [] }, depth=0)
│ │ │ │ │ │ │ │ │ │ │ │ │ ├─┘
│ │ │ │ │ │ │ │ │ │ │ │ │ ├─  1ms DEBUG rustc_trait_selection::traits::select winnowed to 0 candidates, stack=TraitObligationStack(Obligation(predicate=Binder { value: TraitPredicate(<<&[i32] as std::iter::IntoIterator>::IntoIter as std::marker::Sized>, polarity:Positive), bound_vars: [] }, depth=0)), candidates=[]
│ │ │ │ │ │ │ │ │ │ │ │ │ ├─  1ms DEBUG rustc_trait_selection::traits::select CACHE MISS
│ │ │ │ │ │ │ │ │ │ │ │ │ ├─┐rustc_trait_selection::traits::select::insert_candidate_cache candidate=Err(Unimplemented)
│ │ │ │ │ │ │ │ │ │ │ │ │ │ ├─  0ms DEBUG rustc_trait_selection::traits::select insert_candidate_cache global, pred=TraitPredicate(<<&[i32] as std::iter::IntoIterator>::IntoIter as std::marker::Sized>, polarity:Positive), candidate=Err(Unimplemented)
│ │ │ │ │ │ │ │ │ │ │ │ │ ├─┘
│ │ │ │ │ │ │ │ │ │ │ │ │ ├─  1ms DEBUG rustc_trait_selection::traits::select return=Err(Unimplemented)
│ │ │ │ │ │ │ │ │ │ │ │ ├─┘
│ │ │ │ │ │ │ │ │ │ │ │ ├─  1ms DEBUG rustc_trait_selection::traits::select on_failure, dfn=0
│ │ │ │ │ │ │ │ │ │ │ │ ├─  1ms DEBUG rustc_trait_selection::traits::select CACHE MISS
│ │ │ │ │ │ │ │ │ │ │ │ ├─  1ms DEBUG rustc_trait_selection::traits::select insert_evaluation_cache global, trait_pred=Binder { value: TraitPredicate(<<&[i32] as std::iter::IntoIterator>::IntoIter as std::marker::Sized>, polarity:Positive), bound_vars: [] }, result=EvaluatedToErr
│ │ │ │ │ │ │ │ │ │ │ │ ├─  1ms DEBUG rustc_trait_selection::traits::select on_completion, dfn=0
│ │ │ │ │ │ │ │ │ │ │ │ ├─  1ms DEBUG rustc_trait_selection::traits::select return=Ok(EvaluatedToErr)
│ │ │ │ │ │ │ │ │ │ │ ├─┘
│ │ │ │ │ │ │ │ │ │ │ ├─  1ms DEBUG rustc_trait_selection::traits::select return=Ok(EvaluatedToErr)
│ │ │ │ │ │ │ │ │ │ ├─┘
│ │ │ │ │ │ │ │ │ │ ├─┐rustc_infer::infer::region_constraints::leak_check::leak_check outer_universe=U0, max_universe=U0
│ │ │ │ │ │ │ │ │ │ │ ├─  0ms DEBUG rustc_infer::infer::region_constraints::leak_check return=Ok(())
│ │ │ │ │ │ │ │ │ │ ├─┘
│ │ │ │ │ │ │ │ │ │ ├─┐rustc_infer::infer::rollback_to 
│ │ │ │ │ │ │ │ │ │ │ ├─  0ms DEBUG rustc_infer::infer::undo_log rollback_to(0)
│ │ │ │ │ │ │ │ │ │ │ ├─  0ms DEBUG rustc_infer::infer::region_constraints RegionConstraintCollector: rollback_to(RegionSnapshot)
│ │ │ │ │ │ │ │ │ │ ├─┘
│ │ │ │ │ │ │ │ │ ├─┘
│ │ │ │ │ │ │ │ │ ├─  1ms DEBUG rustc_trait_selection::infer return=EvaluatedToErr
│ │ │ │ │ │ │ │ ├─┘

```

Comment (gurry) [reply compiler/rustc_ty_utils/src/layout.rs:510]: The summary of the above trace is that while trying to relate `Binder { value: <std::slice::Iter<'_, i32> as std::marker::Sized>, bound_vars: [] }` to `Binder { value: <<&[i32] as std::iter::IntoIterator>::IntoIter as std::marker::Sized>, bound_vars: [] }` as a subtype infcx goes through various motions and ultimately tries to relate them structurally in which it fails which causes the evaluate machinery to deduce that the projection type is unsized.

This seems to be a pre-existing issue though. In fact the `is_sized()` call in the existing code in `layout.rs` shown below https://github.com/rust-lang/rust/blob/dc2ffa405407ffb3654658c50ab3dfda124fbdfd/compiler/rustc_ty_utils/src/layout.rs#L524-L528
uses the exact same evaluate logic as the above and fails precisely the same way. That is, `is_sized()` too returns `false` when called on a projection type like `<&'a [i32] as IntoIterator>::IntoIter`. This does not lead to a catastrophic failure however. It merely causes a slightly different layout to be chosen as the below logic over in 'rustc_abi` gets skipped: https://github.com/rust-lang/rust/blob/dc2ffa405407ffb3654658c50ab3dfda124fbdfd/compiler/rustc_abi/src/layout.rs#L97
However, in our case it causes a delay bug to be triggered.

@oli-obk In your opinion is this failure to relate `Binder { value: <std::slice::Iter<'_, i32> as std::marker::Sized>, bound_vars: [] }`  to `Binder { value: <<&[i32] as std::iter::IntoIterator>::IntoIter as std::marker::Sized>, bound_vars: [] }` as a subtype a bug or expected behaviour?

Comment (oli-obk) [reply compiler/rustc_ty_utils/src/layout.rs:510]: kind of. I expect these to be different, I just don't expect the latter to actually occur, and instead expected it to get normalized. I mean, something got normalized somewhere as we got the `slice::Iter`.

Note that we do already normalize at the start of the `layout_of` query, so maybe what we actually need to do is to invoke `layout_of` on the instantiated type and ask the layout whether it is sized?

Comment (gurry) [reply compiler/rustc_ty_utils/src/layout.rs:510]: I tried `layout_of(field_ty).is_sized()` as shown below:

```rust
            let is_unsized_field = |field: &FieldDef| {
                let param_env = tcx.param_env(def.did());
                let field_ty = tcx.type_of(field.did).instantiate_identity();
                tcx.layout_of(ParamEnvAnd { param_env, value: field_ty })
                    .map(|field_layout| !field_layout.is_sized())
                    .or(Err(error(cx, LayoutError::Unknown(ty))))
            };
```

but it unfortunately also causes loads of ICEs.

Wonder if we have to change the approach and try to taint the typeck results instead. Perhaps that is a general strategy we should adopt to keep malformed types from reaching the const eval/mir building stage as #121097 might also be helped by something like that.

Comment (oli-obk) [reply compiler/rustc_ty_utils/src/layout.rs:510]: > Wonder if we have to change the approach and try to taint the typeck results instead

Comment (gurry) [reply compiler/rustc_ty_utils/src/layout.rs:510]: If we let wfcheck set a flag on, say `hir::Ty`, that the type is not WF then typeck can use that to taint its results. 

For example, let's say we add a `wf_check_failed` flag to `hir::Ty`:

```rust
pub struct Ty<'hir> {
    pub hir_id: HirId,
    pub kind: TyKind<'hir>,
    pub span: Span,
    pub bool: wf_check_failed,
}
```

And then in wfcheck set this flag on failure:

```rust
if /* wf check failed for ty */ {
    ty.wf_check_failed = true
}
```

Then somewhere in typeck check the flag and taint the results:
```rust
if ty.wf_check_failed && /* some other appropriate condition */ {
   // taint typeck results
}
```
Something like that can provide a general way to fix MIR ICEs caused early errors.

Comment (oli-obk) [reply compiler/rustc_ty_utils/src/layout.rs:510]: that's mutation of global state which violates all kinds of incremental/query-caching rules we have. Even if technically fine due to we already being in an erroring compilation and will never write it to the cache anyway.

the main reason we shouldn't do it is that the result of typeck would then differ depending on whether wfcheck had already been run.

Comment (gurry) [reply compiler/rustc_ty_utils/src/layout.rs:510]: Ah, make sense.

File: compiler/rustc_ty_utils/src/layout.rs [hunk 3]
```diff
@@ -506,6 +508,33 @@ fn layout_of_uncached<'tcx>(
                 ));
             }
 
+            let is_unsized_field = |field: &FieldDef| {
+                let field_ty = tcx.type_of(field.did);
+                tcx.try_instantiate_and_normalize_erasing_regions(args, cx.param_env, field_ty)
+                    .map(|f| !f.is_sized(tcx, cx.param_env))
```
Comment (gurry) [inline compiler/rustc_ty_utils/src/layout.rs:514]: Had missed adding this `!` operator in my previous attempt 🤣

**Comment by gurry** [comment]
@oli-obk I've finally made it work. Please review.

I'm simply normalizing the field type before calling `is_sized()` on it. I had tried that before (https://github.com/rust-lang/rust/pull/121546#issuecomment-1963378874) but made a dumb mistake which was that I had missed adding the `!` operator before `is_sized()` :|

File: compiler/rustc_ty_utils/src/layout.rs [hunk 4]
```diff
@@ -506,6 +508,33 @@ fn layout_of_uncached<'tcx>(
...
+                    .map_err(|e| {
+                        error(
+                            cx,
+                            LayoutError::NormalizationFailure(field_ty.instantiate_identity(), e),
+                        )
+                    })
+            };
+
+            if def.is_struct()
```
Comment (oli-obk) [inline compiler/rustc_ty_utils/src/layout.rs:523]: Will we now have the same issue with enums and unions?

Please add some tests for enums. I don't think unions are a problem without anonymous struct fields.

You can walk all variants and then iterate over their fields to handle enums, too

Comment (gurry) [reply compiler/rustc_ty_utils/src/layout.rs:523]: I've added tests for enums and unions and they are passing. So looks like the ICE does not occur for them. Let me know if you want me to still add the logic to handle them in layout.

Comment (oli-obk) [reply compiler/rustc_ty_utils/src/layout.rs:523]: It does fail for single-variant enums:

```rust
use std::mem::size_of;

enum BadEnum {
    Variant1 {
        field1: i32,
        field2: str, // Unsized
        //~^ ERROR the size for values of type `str` cannot be known at compilation time
        field3: [u8; 16],
    },
}

pub fn main() {
    let _a = &size_of::<BadEnum>();
    assert_eq!(size_of::<BadEnum>(), 21);
}
```

It may be possible to construct a multi-enum version, too, but I can't come up with it right now

Comment (gurry) [reply compiler/rustc_ty_utils/src/layout.rs:523]: You're right. it does fail with single variant enums, but I too couldn't find a way to repro for multi-variant ones.

I've now added the logic to handle enums and relevant tests.

**Comment by gurry** [comment]
This PR will fix #123152 also

File: compiler/rustc_ty_utils/src/layout.rs [hunk 5]
```diff
@@ -506,6 +508,45 @@ fn layout_of_uncached<'tcx>(
...
+                        cx.tcx.dcx().span_delayed_bug(
+                            tcx.def_span(def.did()),
+                            "only the last field of a struct can be unsized",
+                        );
+                        return Err(error(cx, LayoutError::Unknown(ty)));
+                    }
+                }
+            }
+
+            if def.is_enum() {
```
Comment (oli-obk) [inline compiler/rustc_ty_utils/src/layout.rs:538]:
```suggestion
            } else {
```

File: compiler/rustc_ty_utils/src/layout.rs [hunk 6]
```diff
@@ -506,6 +508,45 @@ fn layout_of_uncached<'tcx>(
...
+                && let Some((_, fields_except_last)) =
+                    def.non_enum_variant().fields.raw.split_last()
+            {
+                for f in fields_except_last {
+                    if is_unsized_field(f)? {
+                        cx.tcx.dcx().span_delayed_bug(
+                            tcx.def_span(def.did()),
+                            "only the last field of a struct can be unsized",
+                        );
+                        return Err(error(cx, LayoutError::Unknown(ty)));
```
Comment (oli-obk) [inline compiler/rustc_ty_utils/src/layout.rs:533]: move this into the closure

**Comment by oli-obk** [comment]
@bors delegate+

r=me with nits
