### PR TITLE
black_box doc corrections for clarification - Issue #107957

### LINKED ISSUE #107957: black_box docs correctness claim incorrect
### Location

https://doc.rust-lang.org/stable/std/hint/fn.black_box.html

### Summary

The documentation of `black_box` states: 

> Programs cannot rely on black_box for correctness in any way.

but this is not accurate since programs can rely on it behaving like the identity function.
It would be better to reword this as 

> Programs cannot rely on black_box for correctness beyond it behaving as the identity function.

or similar, e.g., 

> Programs cannot rely on the optimisation-inhibiting effects of black_box for correctness.

### PR DESCRIPTION
**Pull request by pat-nel87**
Made a complete pass through the docs to help resolve https://github.com/rust-lang/rust/issues/107957

No code changes, just documentation

@rustbot label +T-libs-api -T-libs

### CODE REVIEW

File: library/core/src/hint.rs [hunk 1]
```diff
@@ -223,12 +223,12 @@ pub fn spin_loop() {
 ///
 /// # When is this useful?
 ///
-/// First and foremost: `black_box` does _not_ guarantee any exact behavior and, in some cases, may
-/// do nothing at all. As such, it **must not be relied upon to control critical program behavior.**
+/// First and foremost: `black_box` does _not_ guarantee any exact behavior beyond behaving as the identity function
+/// and, in some cases, does nothing at all. As such, it **must not be relied upon to control critical program behavior.**
```
Comment (tgross35) [inline library/core/src/hint.rs:227]: Fwiw, I think this is a bit redundant because it's mentioned one line above https://github.com/rust-lang/rust/blob/6f7ca32ae7f5cd9159a986ca0c30b77420cce933/library/core/src/hint.rs#L219-L220

Comment (pat-nel87) [reply library/core/src/hint.rs]: @tgross35 Thanks for reviewing this PR. I've adjusted wording to be a bit less redundant.

**Comment by pat-nel87** [comment]
> ☔ The latest upstream changes (presumably #109626) made this pull request unmergeable. Please [resolve the merge conflicts](https://rustc-dev-guide.rust-lang.org/git.html#rebasing-and-conflicts).

Resolved! @bors

**Comment by jyn514** [comment]
Thanks!

@bors r+ rollup
