### PR TITLE
std:win: avoid WSA_FLAG_NO_INHERIT flag and don't use SetHandleInformation on UWP

### LINKED ISSUE #26518: error UDP socket
I have that code:

``` rust
fn main() {
    let socket = UdpSocket::bind("127.0.0.1:23451").ok().expect("fail bind");
    let mut buf = [0; 2];
    buf[0]=11;
    buf[1]=22;
    socket.send_to(&buf, "127.0.0.1:23451").ok().expect("fail send");
    println!("{:?}", buf);
}
```

and I start it in 2 different PC with OS win7 32 , and have 2 different error:
1)thread '' panicked at 'called Result::unwrap() on an Err value: Error { repr: Os(10022) }',
C:/bot/slave/stable-dist-rustc-win-32/build/src/libcore\result.rs:729
2)thread '' panicked at 'fail bind', C:/bot/slave/stable-dist-rustc-win-32/b
uild/src/libcore\option.rs:330
This errors com in after first string:

``` rust
let socket = UdpSocket::bind("127.0.0.1:23451").ok().expect("fail bind");
```

### LINKED ISSUE #26543: TcpListener::bind broken under Windows 7
Creating a TCP listener socket will result in error under Windows 7. Minimal test case:

```rust
fn main() {
    use std::net::TcpListener;
    let listener = TcpListener::bind("127.0.0.1:8000").unwrap();
}
```

This will produce an error with code 10041 (`WSAEPROTOTYPE`).

This was tested on stable Rust (1.0.0).

After a bit digging, turns out [this particular piece of code](https://github.com/rust-lang/rust/blob/a59de37e99060162a2674e3ff45409ac73595c0e/src/libstd/sys/windows/net.rs#L82-L84) might be the cause of the breakage. According to the Winsock docs, The `WSA_FLAG_NO_HANDLE_INHERIT` flag is [supported on at least Windows 7 *SP1*](https://msdn.microsoft.com/en-us/library/windows/desktop/ms742212%28v=vs.85%29.aspx), so running on vanilla Windows 7 would not work and would apparently break your program.

### PR DESCRIPTION
**Pull request by AviKozokin**
This flag is not supported on Windows 7 before SP1, and on windows server 2008 SP2. This breaks Socket creation & duplication.
This was fixed in a previous PR. cc #26658

This PR: cc #60260 reuses this flag to support UWP, and makes an attempt to handle the potential error.
This version still fails to create a socket, as the error returned by WSA on this case is WSAEINVAL (invalid argument). and not WSAEPROTOTYPE.

MSDN page for WSASocketW (that states the platform support for WSA_FLAG_NO_HANDLE_INHERIT): https://docs.microsoft.com/en-us/windows/win32/api/winsock2/nf-winsock2-wsasocketw

CC #26543
CC #26518

### CODE REVIEW

**Comment by alexcrichton** [comment]
Thanks for the PR! I think it'd be best to keep the current structure though because it atomically creates a socket and sets the no-inherit flag. The current code looks like it already tries to handle the case that it fails and falls back to creating a socket and then setting the no-inherit flag. Does that fallback not seem to work for you? Is there a way we can tweak the fallback to work for you?

**Comment by AviKozokin** [comment]
@alexcrichton 
The fallback does not work, because the error value returned from `WSASocketW` in this case (passing an unsupported value to `dwFlags`) is not the error value assumed in the code. (`WSAEPROTOTYPE`).

**Comment by alexcrichton** [comment]
Can the list of error codes recognized to trigger the fallback get updated?

File: src/libstd/sys/windows/net.rs [hunk 1]
```diff
@@ -1,4 +1,4 @@
-#![unstable(issue = "0", feature = "windows_net")]
+![unstable(issue = "0", feature = "windows_net")]
```
Comment (lzutao) [inline src/libstd/sys/windows/net.rs]: ?

File: src/libstd/sys/windows/net.rs [hunk 2]
```diff
@@ -422,4 +419,4 @@ impl IntoInner<c::SOCKET> for Socket {
         mem::forget(self);
         ret
     }
-}
+}
```
Comment (lzutao) [inline src/libstd/sys/windows/net.rs]: ?

**Review by tesuji — COMMENTED** [review]
What is the CALL file and clippy submodule update?

**Comment by alexcrichton** [comment]
@bors: r+

Thanks!
