### PR TITLE
Expand `NtExpr` tokens only in key-value attributes

### LINKED ISSUE #43860: resolve_macro_to_def panics
`rustc 1.19.0 (0ade33941 2017-07-17)`

I have 3 crates

crate a:

```rust
#[proc_macro_derive(EthabiContract, attributes(ethabi_contract_options))]
pub fn ethabi_derive(input: TokenStream) -> TokenStream {
// do something
}
```

crate b:

```rust
#[macro_export]
macro_rules! use_contract {
	($name: ident, $path: expr) => {
		#[derive(EthabiContract)]
		#[ethabi_contract_options(path = $path)]
		pub struct $name<T, C> {
			api: T,
			contract: C,
		}
	}
}
```

crate c:

```rust
use_contract!(ContractName, file!());
```

building crate c results in compiler panic

```
error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: run with `RUST_BACKTRACE=1` for a backtrace

thread 'rustc' panicked at 'no entry found for key', src/libcore/option.rs:823
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
   1: std::panicking::default_hook::{{closure}}
   2: std::panicking::default_hook
   3: std::panicking::rust_panic_with_hook
   4: std::panicking::begin_panic
   5: std::panicking::begin_panic_fmt
   6: rust_begin_unwind
   7: core::panicking::panic_fmt
   8: core::option::expect_failed
   9: rustc_resolve::macros::<impl rustc_resolve::Resolver<'a>>::resolve_macro_to_def
  10: rustc_resolve::macros::<impl syntax::ext::base::Resolver for rustc_resolve::Resolver<'a>>::resolve_invoc
  11: syntax::ext::expand::MacroExpander::expand
  12: syntax::ext::expand::MacroExpander::expand_crate
  13: rustc_driver::driver::phase_2_configure_and_expand::{{closure}}
  14: rustc_driver::driver::phase_2_configure_and_expand
  15: rustc_driver::driver::compile_input
  16: rustc_driver::run_compiler

error: Could not compile `ethabi_contract`.
```

### LINKED ISSUE #55414: ICE in macro: doc meta with expr on an item, string concat, stringify!(...)
## code

```rust
macro_rules! bug {
    () => {
        bug!("bug" + stringify!(found));
    };
    ($test:expr) => {
        #[doc = $test]
        struct Test {} // looks like any item works
    };
}

bug!();
```

## description

Any of the following actions stop the panic:
- Removing or commenting the `doc` attribute:
  ```rust
  // #[doc = $test]
  ```
- Replacing macro call with:
  ```rust
  bug!("");
  ```
- Removing concatenation:
  ```rust
  () => {
      bug!(stringify!(anything));
  };
  ```
- Replacing `stringify!(...)`:
  ```rust
  () => {
      bug!("bug" + "test");
  };
  ```

## stderr
<details><summary>Show output</summary>

```console
thread 'main' panicked at 'no entry found for key', libcore/option.rs:1000:5
stack backtrace:
   0:     0x7f381365575e - std::sys::unix::backtrace::tracing::imp::unwind_backtrace::hf5316c67202e23c8
                               at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1:     0x7f381362e946 - std::sys_common::backtrace::print::h3068ed2a6dc7ac86
                               at libstd/sys_common/backtrace.rs:71
                               at libstd/sys_common/backtrace.rs:59
   2:     0x7f381362c54d - std::panicking::default_hook::{{closure}}::h1b9d29cc09d41897
                               at libstd/panicking.rs:211
   3:     0x7f381362c2c0 - std::panicking::default_hook::h3a27b204a313406b
                               at libstd/panicking.rs:227
   4:     0x7f380fe769f1 - rustc::util::common::panic_hook::hf9d72254884e6e21
   5:     0x7f381362cc53 - std::panicking::rust_panic_with_hook::h0e12cb2fc86d00fa
                               at libstd/panicking.rs:481
   6:     0x7f381362c7b9 - std::panicking::continue_panic_fmt::h141671b29fe0e27d
                               at libstd/panicking.rs:391
   7:     0x7f381362c6b5 - rust_begin_unwind
                               at libstd/panicking.rs:326
   8:     0x7f38136a55db - core::panicking::panic_fmt::h429a06507aba9228
                               at libcore/panicking.rs:77
   9:     0x7f38136a5671 - core::option::expect_failed::h4c79c3aae6612643
                               at libcore/option.rs:1000
  10:     0x7f38128de274 - rustc_resolve::macros::<impl syntax::ext::base::Resolver for rustc_resolve::Resolver<'a, 'crateloader>>::resolve_macro_invocation::hcacc2b568dda6de5
  11:     0x7f380eecdf28 - syntax::ext::expand::MacroExpander::expand_fragment::h26fd612375b32814
  12:     0x7f380eecd6b1 - syntax::ext::expand::MacroExpander::expand_crate::h3497aacb05bd8e53
  13:     0x7f38139c0303 - rustc_driver::driver::phase_2_configure_and_expand_inner::{{closure}}::h3d4d02fec2b68db2
  14:     0x7f38139bedda - rustc::util::common::time::ha1804c2290179406
  15:     0x7f38139d7b54 - rustc_driver::driver::phase_2_configure_and_expand::h2c60f5950dd2995f
  16:     0x7f38139d356b - rustc_driver::driver::compile_input::h6a302c45b9b8d410
  17:     0x7f3813a7b20c - rustc_driver::run_compiler_with_pool::h2a396394cdff52b0
  18:     0x7f38139d2f34 - rustc_driver::driver::spawn_thread_pool::h5dec0f6efcb9456b
  19:     0x7f3813a7a221 - rustc_driver::run_compiler::he4a6ce0f80da709f
  20:     0x7f38139c169c - <scoped_tls::ScopedKey<T>>::set::h0d2c211708f72196
  21:     0x7f38139fd651 - syntax::with_globals::hcc4912b6b554b6a2
  22:     0x7f381366c469 - __rust_maybe_catch_panic
                               at libpanic_unwind/lib.rs:103
  23:     0x7f3813a7847c - rustc_driver::run::h9e76da7d522d5bdd
  24:     0x7f3813a864ba - rustc_driver::main::h979d81f5800d15a6
  25:     0x55b562390992 - std::rt::lang_start::{{closure}}::h5cee4df267a41ddd
  26:     0x7f381362c652 - std::panicking::try::do_call::h572dc6f90deb1a4d
                               at libstd/rt.rs:59
                               at libstd/panicking.rs:310
  27:     0x7f381366c469 - __rust_maybe_catch_panic
                               at libpanic_unwind/lib.rs:103
  28:     0x7f3813642b45 - std::rt::lang_start_internal::hce01021c3c1cf20d
                               at libstd/panicking.rs:289
                               at libstd/panic.rs:392
                               at libstd/rt.rs:58
  29:     0x55b562390983 - main
  30:     0x7f3813400222 - __libc_start_main
  31:     0x55b562390838 - <unknown>
query stack during panic:
end of query stack

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.30.0 (da5f414c2 2018-10-24) running on x86_64-unknown-linux-gnu
```

</details>

## rustc

```console
$ rustc --version --verbose
rustc 1.30.0 (da5f414c2 2018-10-24)
binary: rustc
commit-hash: da5f414c2c0bfe5198934493f04c676e2b23ff2e
commit-date: 2018-10-24
host: x86_64-unknown-linux-gnu
release: 1.30.0
LLVM version: 8.0
```

### PR DESCRIPTION
**Pull request by petrochenkov**
Implement the experiment described in https://github.com/rust-lang/rust/issues/55414#issuecomment-554005412

This PR also removes some customization points and token visiting functionality from AST visitors.
Read-only visitor no longer visits tokens, mutable visitor visits tokens only when specifically enabled, mutable token visiting is restricted to its single intended use case.

I haven't changed the representation of `MacArgs::Eq` yet, but it potentially can use a `TokenTree` or a `Token` instead of `TokenStream`.
It's hard to get rid of `Nonterminal::NtExpr` there (and e.g. replace it with `ast::Expr`) due to the dual nature of key-value attributes (the value is both an expression and a token stream, depending on context), and `Nonterminal` has all the machinery for maintaining both representations in sync.

Fixes https://github.com/rust-lang/rust/issues/55414
Fixes https://github.com/rust-lang/rust/issues/43860

### CODE REVIEW

**Comment by petrochenkov** [comment]
@craterbot check

**Comment by petrochenkov** [comment]
No non-spurious regressions from crater - this is an excellent news, I expected worse given the one case found in libcore.
It means we can eliminate this pretty fundamental issue from our expansion model.

**Comment by petrochenkov** [comment]
r? @Aaron1011 
This should be ready for review now.

(https://github.com/rust-lang/rust/pull/78610 needs to land before this PR though.)

File: compiler/rustc_ast/src/mut_visit.rs [hunk 1]
```diff
@@ -375,11 +366,31 @@ pub fn visit_mac_args<T: MutVisitor>(args: &mut MacArgs, vis: &mut T) {
...
+                if let Some(TokenTree::Token(token)) = tokens.trees_ref().next() {
+                    if let token::Interpolated(..) = token.kind {
+                        // ^^ Do not `make_mut` unless we have to.
+                        match Lrc::make_mut(&mut tokens.0).get_mut(0) {
+                            Some((TokenTree::Token(token), _spacing)) => match &mut token.kind {
+                                token::Interpolated(nt) => match Lrc::make_mut(nt) {
+                                    token::NtExpr(expr) => vis.visit_expr(expr),
+                                    t => panic!("unexpected token in key-value attribute: {:?}", t),
+                                },
+                                token::Literal(..) | token::Ident(..) => {}
```
Comment (Aaron1011) [inline compiler/rustc_ast/src/mut_visit.rs:386]: Shouldn't this case be impossible, since the outer check already confirmed that this is a `token::Interpolated`?

Comment (petrochenkov) [reply compiler/rustc_ast/src/mut_visit.rs:386]: Yes, this was necessary before I added the optimization check, and then I forgot to remove it.

**Comment by Aaron1011** [comment]
@petrochenkov: Are there any tests for the non-key-value case with a proc macro? E.g. `#[my_attr(first, line!(), second)]`

**Comment by petrochenkov** [comment]
No, I'll add something like this.
These are the cases which can be broken by this PR, so they do need testing.

**Comment by petrochenkov** [comment]
This PR will have no effect if `my_attr` is a proc macro though, proc macro will get its arguments literally as `first, line!(), second` because it will expand first.
Expansion can happen only inside inert attributes due to expansion order.

**Comment by petrochenkov** [comment]
I wonder if removing token visiting improved performance.
@bors try @rust-timer queue

**Comment by petrochenkov** [comment]
`codegen_crate` regressions? Look unrelated to this PR.

File: compiler/rustc_ast/src/mut_visit.rs (hunk 1 above)
Comment (petrochenkov) [reply compiler/rustc_ast/src/mut_visit.rs]: Done.

**Comment by petrochenkov** [comment]
Updated.

File: src/test/ui/proc-macro/nonterminal-expansion.rs [hunk 2]
```diff
@@ -0,0 +1,33 @@
+// check-pass
+// aux-build:test-macros.rs
```
Comment (Aaron1011) [inline src/test/ui/proc-macro/nonterminal-expansion.rs:2]: Could you add:

```rust
// compile-flags: -Z span-debug

#![no_std] // Don't load unnecessary hygiene information from std
extern crate std;
```

to this test? That will make the output print actual span numbers, which makes it much easier to determine if any future change to the stdout is legitimate or not.

Unfortunately, I don't know a better way other than copy-pasting this header into all of the tests that using `test_macros`

**Comment by Aaron1011** [comment]
@petrochenkov: r=me with the comment addressed.

**Comment by XAMPPRocky** [comment]
@Aaron1011 What's the user facing change in this PR? It's hard to tell from the discussion and diff.

**Comment by Aaron1011** [comment]
I think this might not have any impact beyond fixing some ICEs. I may have confused this with the follow-up PR that allows arbitrary expressions in key-value attributes pre-expansion.
