### PR TITLE
Recover `param: Ty = EXPR`

### LINKED ISSUE #137310: Unsupported default dunction parameters should have an explicit diagnostic
### Code

```Rust
fn f(x: u8 = 0) {}
```

### Current output

```Shell
error: expected parameter name, found `=`
 --> src/lib.rs:1:12
  |
1 | fn f(x: u8 = 0) {
  |            ^ expected parameter name

error: expected one of `!`, `(`, `)`, `+`, `,`, `::`, or `<`, found `=`
 --> src/lib.rs:1:12
  |
1 | fn f(x: u8 = 0) {
  |           -^ expected one of 7 possible tokens
  |           |
  |           help: missing `,`
```

### Desired output

```Shell
error: default function parameters are not supported
```

### Rationale and extra context

especially since `#![feature(default_field_values)]` uses the same syntax, this seems plausible to try

### Other cases

```Rust

```

### Rust Version

```Shell
1.87.0-nightly

(2025-02-19 f280acf4c743806abbbb)
```

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by compiler-errors**
Fixes #137310

Pretty basic recovery here, but better than giving an unexpected token error.

### CODE REVIEW

File: compiler/rustc_parse/src/parser/ty.rs [hunk 1]
```diff
@@ -132,14 +132,38 @@ impl<'a> Parser<'a> {
...
             RecoverQPath::Yes,
             RecoverReturnSign::Yes,
             None,
             RecoverQuestionMark::Yes,
-        )
+        )?;
+
+        // Recover a trailing `= EXPR` if present.
+        if self.may_recover() {
+            let snapshot = self.create_snapshot_for_diagnostic();
```
Comment (fmease) [inline compiler/rustc_parse/src/parser/ty.rs:146]: This clones the entire parser in the happy path which may incur a perf hit. Any reason why you don't gate the snapshot behind `check_noexpect(Eq)`/`==Eq` (followed by `bump`)?

Comment (compiler-errors) [reply compiler/rustc_parse/src/parser/ty.rs:146]: Oh, d'oh. Of course lmao. Yeah. I was thinking about doing this then just forgor.

Comment (fmease) [reply compiler/rustc_parse/src/parser/ty.rs:146]: nw, r=me then

**Comment by BoxyUwU** [comment]
r? fmease

File: compiler/rustc_parse/src/parser/ty.rs
Comment (fmease) [inline compiler/rustc_parse/src/parser/ty.rs:1]: On a second glance, I would think `parse_param_general` is 'a better fit' for this compared to `parse_ty_for_param` (which should probably only concern itself with parsing types).

Mostly an organizational nitpick since it shouldn't be able to affect behavior (CC anon params in Rust 2015). I was only able to find `trait T { fn f(Some(x)=0 fn) {} }` (Rust 2015) which will emit two errors under this PR (`parameter defaults are not supported` and `` expected `:`, found `=` ``) instead of one (and should keep emitting one if the logic was moved into `parse_param_general` I think) but that's hardly interesting.

> nw, r=me then

r=me with or without moving the logic into `parse_param_general`. Sorry for the churn / wrong signal there.

Comment (fmease) [reply compiler/rustc_parse/src/parser/ty.rs:1]: (preexisting: the suggestion provided by the `patterns aren't allowed in methods without bodies` parser recovery is already butchered: it literally suggests `_: )=0 fn` for `trait T { fn f(Some(x)=0 fn); }` under Rust 2015)

**Review by fmease — APPROVED** [review]
