### PR TITLE
Fix ICE when using Box<T, A> with pointer sized A

### LINKED ISSUE #78459: ICE when using Box<T, A> with non-zero sized A
While working on #77438, I've run into the following ICE. ~~It seems to be caused by the type layout code not expecting `Box` to have more than 3 fields, in this case the fat pointer containing two fields, plus the `AllocRef` instance.~~ On further consideration, the issue also appears with `Box<T, A>` as long as `A` is non zero sized.

This ICE was likely not encountered during testing of #77187 because in the case of `Box<T, Global>`, `Global` is zero sized. In the example below, removing the borrow of `Global` will cause the compilation to succeed. 

@eddyb could you take a look at this? :)

cc @TimDiekmann you may run into this as well on `RawVec`

#### Old code
[Playground link](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=c75dfcd513b4b096cae70b1573a6a0d6)
```Rust
#![feature(allocator_api)]

fn main() {
    Box::new_in(&[0, 1], &std::alloc::Global);
}
```
#### New, more minimal code
[Playground link](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=389ae1cfe83cce69cabd968846eaab5a)
```Rust
#![feature(allocator_api)]

fn main() {
    Box::new_in((), &std::alloc::Global);
}
```

### Meta

`rustc --version --verbose`:
```
rustc 1.49.0-nightly (fd542592f 2020-10-26) running on x86_64-unknown-linux-gnu - playground
rustc 1.48.0-beta.3 (4708ac76e 2020-10-15) running on x86_64-unknown-linux-gnu - local dev environment
```

### Error output
https://github.com/rust-lang/rust/blob/07e968b640e8ff76fa8be4b48b70ab80ea577800/compiler/rustc_middle/src/ty/layout.rs#L2056

```
thread 'rustc' panicked at 'assertion failed: i < this.fields.count()', /rustc/fd542592f08ca0d1f7255600115c2eafdf6b5da7/compiler/rustc_middle/src/ty/layout.rs:2056:17
```

<details><summary><strong>Backtrace</strong></summary>
<p> From playground

```
thread 'rustc' panicked at 'assertion failed: i < this.fields.count()', /rustc/fd542592f08ca0d1f7255600115c2eafdf6b5da7/compiler/rustc_middle/src/ty/layout.rs:2056:17
stack backtrace:
   0: std::panicking::begin_panic
   1: rustc_middle::ty::layout::<impl rustc_target::abi::TyAndLayoutMethods<C> for &rustc_middle::ty::TyS>::field
   2: <rustc_target::abi::TyAndLayout<&rustc_middle::ty::TyS> as rustc_codegen_llvm::type_of::LayoutLlvmExt>::scalar_pair_element_llvm_type
   3: <rustc_target::abi::TyAndLayout<&rustc_middle::ty::TyS> as rustc_codegen_llvm::type_of::LayoutLlvmExt>::scalar_pair_element_llvm_type
   4: <rustc_target::abi::call::FnAbi<&rustc_middle::ty::TyS> as rustc_codegen_llvm::abi::FnAbiLlvmExt>::llvm_type
   5: rustc_codegen_llvm::mono_item::<impl rustc_codegen_ssa::traits::declare::PreDefineMethods for rustc_codegen_llvm::context::CodegenCx>::predefine_fn
   6: rustc_codegen_llvm::base::compile_codegen_unit::module_codegen
   7: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task
   8: rustc_codegen_llvm::base::compile_codegen_unit
   9: rustc_codegen_ssa::base::codegen_crate
  10: <rustc_codegen_llvm::LlvmCodegenBackend as rustc_codegen_ssa::traits::backend::CodegenBackend>::codegen_crate
  11: rustc_interface::passes::QueryContext::enter
  12: rustc_interface::queries::Queries::ongoing_codegen
  13: rustc_interface::queries::<impl rustc_interface::interface::Compiler>::enter
  14: rustc_span::with_source_map
  15: scoped_tls::ScopedKey<T>::set
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

</p>
</details>

### PR DESCRIPTION
**Pull request by beepster4096**
Fixes #78459

Note that using `Box<T, A>` with a more than pointer sized `A` or using a pointer sized `A` with a Box of a DST will produce a different ICE (#92054) which is not fixed by this PR.

### CODE REVIEW

File: compiler/rustc_codegen_llvm/src/type_of.rs [hunk 1]
```diff
@@ -330,7 +330,7 @@ impl<'tcx> LayoutLlvmExt<'tcx> for TyAndLayout<'tcx> {
             ty::Ref(..) | ty::RawPtr(_) => {
                 return self.field(cx, index).llvm_type(cx);
             }
-            ty::Adt(def, _) if def.is_box() => {
+            ty::Adt(def, substs) if def.is_box() && cx.layout_of(substs.type_at(1)).is_zst() => {
```
Comment (oli-obk) [inline compiler/rustc_codegen_llvm/src/type_of.rs:333]: Please leave a comment here stating that we only handle wide pointer boxes as pointers, not thin pointer boxes with a scalar allocator. That case is handled in the general logic below

File: compiler/rustc_codegen_llvm/src/type_of.rs [hunk 2]
```diff
@@ -330,7 +330,9 @@ impl<'tcx> LayoutLlvmExt<'tcx> for TyAndLayout<'tcx> {
             ty::Ref(..) | ty::RawPtr(_) => {
                 return self.field(cx, index).llvm_type(cx);
             }
-            ty::Adt(def, _) if def.is_box() => {
+            // only wide pointer boxes are handled as pointers
+            // thin pointer boxes with scalar allocators are handled by the general logic below
+            ty::Adt(def, substs) if def.is_box() && cx.layout_of(substs.type_at(1)).is_zst() => {
```
Comment (bjorn3) [inline compiler/rustc_codegen_llvm/src/type_of.rs:335]: cc @antoyo I think cg_gcc needs the same fix.

Comment (antoyo) [reply compiler/rustc_codegen_llvm/src/type_of.rs:335]: Seems like applying the same fix cause another [issue](https://github.com/rust-lang/rustc_codegen_gcc/runs/5471850624?check_suite_focus=true).
Do you think there is the same issue for the LLVM codegen?
cc @DrMeepster

Comment (DrMeepster) [reply compiler/rustc_codegen_llvm/src/type_of.rs:335]: Looks like the problem is that in the `mini_core` test, Box doesn't have the allocator type parameter.

Comment (bjorn3) [reply compiler/rustc_codegen_llvm/src/type_of.rs:335]: Yeah, fixed it in cg_clif in https://github.com/bjorn3/rustc_codegen_cranelift/commit/401b03443b087e08779878381a170003e2018371. Feel free to copy the changes.

Comment (antoyo) [reply compiler/rustc_codegen_llvm/src/type_of.rs:335]: Unfortunately, that doesn't solve the issue. I made changes more similar to liballoc itself, but got another ICE:
```
thread 'rustc' panicked at 'assertion failed: sig.c_variadic || extra_args.is_empty()', compiler/rustc_middle/src/ty/layout.rs:3027:13
```

Comment (bjorn3) [reply compiler/rustc_codegen_llvm/src/type_of.rs:335]: Did you change `Box` to include an extra field (eg `()`) **and** change `box_free` to add an extra argument of the same type? They need to be in sync. I got the exact same error when I hadn't changed `box_free` yet.

Comment (antoyo) [reply compiler/rustc_codegen_llvm/src/type_of.rs:335]: Yes.
What I meant is that I still get the error fixed by this PR with your changes:
```
thread 'rustc' panicked at 'index out of bounds: the len is 1 but the index is 1', /rustc/4b043faba34ccc053a4d0110634c323f6c03765e/compiler/rustc_middle/src/ty/subst.rs:364:43
```

Comment (antoyo) [reply compiler/rustc_codegen_llvm/src/type_of.rs:335]: Oh, I see what you mean.
My own fixes miss the change you made to `box_free`.
Thanks. It works now!
