### PR TITLE
Reword OpenOptions::{create, create_new} doc.

### LINKED ISSUE #69254: OpenOptions: create() and create_new() are flip flopped
I tried this code:

```rust
OpenOptions::new()
        .write(true)
        .create(true)
        .open(&args.target)
```
and it creates a file even if it already exists
```rust
OpenOptions::new()
        .write(true)
        .create_new(true)
        .open(&args.target)
```
This code creates a file only if the file does not exist

But look at the docs
For create()
image

For create_new()
image

I expected to see this happen: *explanation*
The functions to match their docs
Instead, this happened: *explanation*
They each do what the other is described to do
### Meta

`rustc --version --verbose`:
```
rustc 1.41.0 (5e1a79984 2020-01-27)
binary: rustc
commit-hash: 5e1a799842ba6ed4a57e91f7ab9435947482f7d8
commit-date: 2020-01-27
host: x86_64-unknown-linux-gnu
release: 1.41.0
LLVM version: 9.0
```

<details><summary>Backtrace</summary>
<p>

```
gitpod /workspace/nushell $ RUST_BACKTRACE=1 cargo build
   Compiling nu v0.9.1 (/workspace/nushell)
    Finished dev [unoptimized + debuginfo] target(s) in 26.35s
```
</p>
</details>

### PR DESCRIPTION
**Pull request by jumbatm**
Closes #69254.

Currently, the doc comment for `fs::OpenOptions::create` doesn't mention its behaviour when opening an existing file, and `fs::OpenOptions::create_new`'s doc comment is worded in a way that doesn't make it clear that it actually _fails_ if the file already exists, not overwrite the existing file with a new one.

This PR addresses addresses this by rewording the doc comments to be more explicit.

r? @GuillaumeGomez

### CODE REVIEW

File: src/libstd/fs.rs [hunk 1]
```diff
@@ -844,10 +844,7 @@ impl OpenOptions {
         self
     }
 
-    /// Sets the option for creating a new file.
-    ///
-    /// This option indicates whether a new file will be created if the file
-    /// does not yet already exist.
+    /// Sets the option to create a new file, or open it if it already exists.
```
Comment (LeSeulArtichaut) [inline src/libstd/fs.rs]: I think this could be shortened to
```suggestion
    /// Sets the option to create a new file if it doesn't already exist.
```

**Review by LeSeulArtichaut — APPROVED** [review]

File: src/libstd/fs.rs (hunk 1 above)
Comment (jumbatm) [reply src/libstd/fs.rs]: That's essentially what the comment previously said, but I thought it valuable to explicitly say what happens if the file exists, so a reader can easily contrast it with the description of what happens for `create_new` if the file exists.

Comment (Dylan-DPC) [reply src/libstd/fs.rs]: Yeah the change by the author looks good to me
