### PR TITLE
Find the right lower bound region in the scenario of partial order relations

### LINKED ISSUE #104639: lifetime order breaks member constraints
The following code should pass regardless of the declaration order of lifetimes: https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=88e227f9f7a5b516bffe21e09b18cd5e
```rust
async fn fail<'a, 'b, 'c>(_: &'static str) where 'a: 'c, 'b: 'c, {}
async fn pass<'a, 'c, 'b>(_: &'static str) where 'a: 'c, 'b: 'c, {}
```

This is related to #63033 but it's different in that we *do* have a lower bound region, `'c`, but we fail to recognize that because [the algorithm here](https://github.com/rust-lang/rust/blob/e07425d55b77fde99af2092a92109a0da0860692/compiler/rustc_borrowck/src/region_infer/mod.rs#L760), which is responsible for calculating `min_choice` from `choice_regions = ['static, 'a, 'b, 'c]`, assumes that the outlive relation is a total order, which is not true.

Here is the graph of `self.universal_region_relations`: lXMdKPzIUUNTRnjy

So we need an efficient algorithm that works for partial order relations, but the one that comes to mind is `O(n^2)`. The perf may not be really important here but I'm curious to see the alternatives.

@rustbot label C-bug T-compiler A-borrow-checker E-mentor E-help-wanted

### PR DESCRIPTION
**Pull request by chenyukang**
Fixes #104639

### CODE REVIEW

**Comment by chenyukang** [comment]
@aliemjay

File: compiler/rustc_borrowck/src/region_infer/mod.rs [hunk 1]
```diff
@@ -758,27 +758,14 @@ impl<'tcx> RegionInferenceContext<'tcx> {
...
-                (true, false) => Some(r2),
-                (false, true) => Some(r1),
-                (false, false) => None,
-            }
+        let Some((_, &min_choice)) = choice_regions.iter().enumerate().find(|(i, &r1)| {
+            choice_regions.iter().enumerate().all(|(j, &r2)| {
+                *i == j || self.universal_region_relations.outlives(r1, r2)
+            })
+        }) else {
+            debug!("no choice region outlived all others");
```
Comment (aliemjay) [inline compiler/rustc_borrowck/src/region_infer/mod.rs:766]:
```suggestion
            debug!("no choice region outlived by all others");
```

**Review by aliemjay — APPROVED** [review]
Looks good! Thanks!

**Comment by aliemjay** [comment]
cc @lqd @nikomatsakis
r? types

File: compiler/rustc_borrowck/src/region_infer/mod.rs [hunk 2]
```diff
@@ -758,27 +758,14 @@ impl<'tcx> RegionInferenceContext<'tcx> {
...
-            let r2_outlives_r1 = self.universal_region_relations.outlives(r2, r1);
-            match (r1_outlives_r2, r2_outlives_r1) {
-                (true, true) => Some(r1.min(r2)),
-                (true, false) => Some(r2),
-                (false, true) => Some(r1),
-                (false, false) => None,
-            }
+        let Some((_, &min_choice)) = choice_regions.iter().enumerate().find(|(i, &r1)| {
+            choice_regions.iter().enumerate().all(|(j, &r2)| {
+                *i == j || self.universal_region_relations.outlives(r1, r2)
```
Comment (aliemjay) [inline compiler/rustc_borrowck/src/region_infer/mod.rs:763]:
```suggestion
                self.universal_region_relations.outlives(r2, r1)
```
The `min_choice` should be _outlived by_ all others, not _outlives_ all others. I'll be worried if we don't have tests that tripped for this.

There's also no need to check `i == j` because universal_region_relations is reflexive, so `outlives(r1, r1) == true`.

**Review by aliemjay — CHANGES_REQUESTED** [review]
Oops, I missed that.

File: compiler/rustc_borrowck/src/region_infer/mod.rs (hunk 2 above)
Comment (chenyukang) [reply compiler/rustc_borrowck/src/region_infer/mod.rs:763]: I just found a local test failed for my change:

```rust
async fn async_ret_impl_trait2<'a, 'b>(a: &'a u8, b: &'b u8) -> impl Trait<'a>
where
    'b: 'a,
{
    (a, b)
}
```

Will fix it.

**Review by aliemjay — APPROVED** [review]

**Comment by lqd** [comment]
The regressions above are likely current noise on these benchmarks -- and the O(N²) change here is probably fine at the low Ns we're expecting to see here ?

**Comment by oli-obk** [comment]
@rfcbot merge

This PR removes an order dependence in lifetime outlives checks. Most notably, the following two functions now both pass

```rust
async fn fail<'a, 'b, 'c>(_: &'static str) where 'a: 'c, 'b: 'c, {}
async fn pass<'a, 'c, 'b>(_: &'static str) where 'a: 'c, 'b: 'c, {}
```

while before this PR `fail` would not compile because the previous algorithm linearly walked the bounds instead of trying all combinations. So it would do

1. pick `'a` as current min
2. check `'b` and `'a`. No relation, so we bail out, causing an error

while the `pass` version does

1. pick `'a` as current min
2. check `'c` and `'a`. `'a: 'c`, so we pick `'c`
3. check `'b` and `'c`. `'b: 'c`, so we pick `'c` again

But with this PR, the algorithm simply check, for each lifetime, whether it outlives all other lifetimes and picks that one. This is a quadratic algorithm, but considering that there's very little use case for having many lifetimes, and even going through 10 lifetimes would just need a hundred trivial table lookups, this seems like
* it won't bite us
* it simplifies the implementation
* it avoids weird edge case in the language

**Comment by compiler-errors** [comment]
Wait I didn't notice there was a perf run already oops

**Comment by compiler-errors** [comment]
bors never seemed to register this

@bors r=oli-obk rollup=never
