### PR TITLE
Parse & reject postfix operators after casts

### LINKED ISSUE #35813: Failure to parse "value as Type[index]"
Summary:

Parsing `value as Type[index]` leads to the error:

```
expected one of `!`, `(`, `::`, `;`, or `<`, found `[`
```

It is currently impossible for a cast expression to have a trailing index expression without surrounding the cast expression by parenthesis. This however seems to be a parser limitation, not a grammar limitation.

As currently the macro language guarantees that ty/path expressions can be followed by a "[", this seems like a bug in the parser to me, as it seems to be parsing it as `value as (Type[index])` which makes no grammatical sense, compared to parsing it as (value as Type)[index] which should be valid if I read the lexical structure specification correctly.

```
rustc --version
>>> rustc 1.12.0-nightly (576f76659 2016-08-09)
```

### PR DESCRIPTION
**Pull request by daboross**
This adds an explicit error messages for when parsing `x as Type[0]` or similar expressions. Our add an extra parse case for parsing any postfix operator (dot, indexing, method calls, await) that triggers directly after parsing `as` expressions.

My friend and I worked on this together, but they're still deciding on a github username and thus I'm submitting this for both of us.

It will immediately error out, but will also provide the rest of the parser with a useful parse tree to deal with.

There's one decision we made in how this produces the parse tree. In the situation `&x as T[0]`, one could imagine this parsing as either `&((x as T)[0])` or `((&x) as T)[0]`. We chose the latter for ease of implementation, and as it seemed the most intuitive.

Feedback welcome! This is our first change to the parser section, and it might be completely horrible.

Fixes #35813.

### CODE REVIEW

File: src/librustc_parse/parser/expr.rs [hunk 1]
```diff
@@ -621,7 +621,44 @@ impl<'a> Parser<'a> {
...
+
+            let msg = format!(
+                "casts followed by {} are not supported",
+                match with_postfix.kind {
+                    ExprKind::Index(_, _) => "index operators",
+                    ExprKind::Try(_) => "try operators",
+                    ExprKind::Field(_, _) => "field access expressions",
+                    ExprKind::MethodCall(_, _) => "method call expressions",
+                    ExprKind::Await(_) => "awaits",
+                    _ => "expressions",
```
Comment (daboross) [inline src/librustc_parse/parser/expr.rs]: For someone who's more familiar with the parser codebase: is there a way to generate these en mass? We found some description functions for other AST types (like `ItemKind`), but none for `ExprKind`. Or if there isn't, should we add one?

**Comment by daboross** [comment]
Just force pushed to fix some whitespace errors in the .stderr test file; didn't want to do extra commits 3 minutes into the PR...

File: src/librustc_parse/parser/expr.rs [hunk 2]
```diff
@@ -621,7 +621,44 @@ impl<'a> Parser<'a> {
...
+        };
+
+        // Disallow postfix operators such as `.`, `?` or index (`[]`) after casts.
+        // Parses the postfix operator and emits an error.
+        let expr = type_result?;
+        let span = expr.span;
+
+        // The resulting parse tree for `&x as T[0]` has a precedence of `((&x) as T)[0]`.
+        let with_postfix = self.parse_dot_or_call_expr_with_(expr, span)?;
+        if !matches!(with_postfix.kind, ExprKind::Cast(_, _)) {
```
Comment (petrochenkov) [inline src/librustc_parse/parser/expr.rs]: What is this condition for? It's either unnecessary (always true) or incorrect.
We must always report an error if we parsed something postfix after the cast/ascription expression, but here it looks like we may accept things like `expr as Type1.field as Type2` without an error.

(Also `ExprCast` and `ExprType` should always do the same thing synctactically, e.g. if `expr as Type1 as Type2` work, then `expr as Type1: Type2` should also work.)

Comment (daboross) [reply src/librustc_parse/parser/expr.rs]: I believe we call too far down into the parse chain to ever parse another `as` expression here. If we've read the code correctly, `parse_dot_or_call_expr_with_` will only ever parse things starting with `.`, `[` or `(` after an existing expression. We would have had to call into `parse_assoc_expr` in order to parse another `as` expression.

On parsing any expression, I think it goes something like - leaving out intermediate methods like all the ones which are `_with ` and `_`:

- `parse_expr` -> parses outer attributes, forwards to `parse_assoc_expr`
- `parse_assoc_expr` -> parses `*,+,||,&&` as well as any other binary operators and `as`. Calls helpers like `parse_assoc_expr_cast` when it encounters these. Calls into `parse_prefix_expr` to parse the left hand side of the operator.
- `parse_assoc_expr_*` (`assoc`, `ascribe`, `parse_range_expr`): these parse the thing they're named for, using the lhs parse from `parse_assoc_expr`
- `parse_prefix_expr`: this parses prefix expressions (`!`,`-`,`*`,`&`) then calls: `parse_bottom_expr` and  `parse_dot_or_call_expr_with` (passing in argument from `parse_bottom_expr`)
- `parse_bottom_expr`: parses single things like return expressions, parenthesized expressions, etc.
- `parse_dot_or_call_expr_with`: parses function calls, index operators, `?` operators and field operators, and applies those to the result passed in (usually from `parse_bottom_expr`)

By jumping directly to `parse_dot_or_call_expr_with`, we shouldn't be able to parse any associative operators, including `as X`, and only parse postfix things like indexing, function calls, and and field access/method calls/.await.

Do you think it's worth adding a comment along these lines explaining why we're doing this?

File: src/librustc_parse/parser/expr.rs [hunk 3]
```diff
@@ -621,7 +621,44 @@ impl<'a> Parser<'a> {
                     }
                 }
             }
-        }
+        };
+
+        // Disallow postfix operators such as `.`, `?` or index (`[]`) after casts.
```
Comment (Centril) [inline src/librustc_parse/parser/expr.rs]:
```suggestion
        // Disallow postfix operators such as `.`, `?`, or index (`[]`) after casts.
```

File: src/librustc_parse/parser/expr.rs [hunk 4]
```diff
@@ -621,7 +621,44 @@ impl<'a> Parser<'a> {
...
+                    ExprKind::Index(_, _) => "index operators",
+                    ExprKind::Try(_) => "try operators",
+                    ExprKind::Field(_, _) => "field access expressions",
+                    ExprKind::MethodCall(_, _) => "method call expressions",
+                    ExprKind::Await(_) => "awaits",
+                    _ => "expressions",
+                }
+            );
+            let mut err = self.struct_span_err(with_postfix.span, &msg);
+            let suggestion = "try surrounding the expression with parentheses";
```
Comment (Centril) [inline src/librustc_parse/parser/expr.rs]:
```suggestion
            let suggestion = "try surrounding the expression in parentheses";
```

File: src/librustc_parse/parser/expr.rs [hunk 5]
```diff
@@ -621,7 +621,44 @@ impl<'a> Parser<'a> {
                     }
                 }
             }
-        }
+        };
+
+        // Disallow postfix operators such as `.`, `?` or index (`[]`) after casts.
+        // Parses the postfix operator and emits an error.
+        let expr = type_result?;
```
Comment (Centril) [inline src/librustc_parse/parser/expr.rs]: Style: Avoid the temporary here and put `return`'s where needed above (and consequently remove the `Ok(...)` rewrappings). Also, `expr.span` can be used in each place.

File: src/librustc_parse/parser/expr.rs [hunk 6]
```diff
@@ -621,7 +621,44 @@ impl<'a> Parser<'a> {
...
+                    span,
+                    suggestion,
+                    format!("({})", expr_str),
+                    Applicability::MachineApplicable,
+                )
+            } else {
+                err.span_help(span, suggestion)
+            }
+            .emit();
+        };
```
Comment (Centril) [inline src/librustc_parse/parser/expr.rs]: Let's move all the recovery logic to its own method (this is general advice for hacking on the compiler: always clearly delineate the happy path from the unhappy ones).

File: src/test/ui/parser/issue-35813-postfix-after-cast.rs [hunk 7]
```diff
@@ -0,0 +1,63 @@
+// edition:2018
```
Comment (Centril) [inline src/test/ui/parser/issue-35813-postfix-after-cast.rs]: Please also exercise `::Try` and `::Call`, with the latter being e.g.
```rust
    type F = fn(u8);
    drop as F();
```

Comment (Centril) [reply src/test/ui/parser/issue-35813-postfix-after-cast.rs]: Let's also exercise type ascription (`drop: F()`) for each case (+ the ones I've noted above) you've exercised for `as` here.

File: src/librustc_parse/parser/expr.rs [hunk 8]
```diff
@@ -621,7 +621,44 @@ impl<'a> Parser<'a> {
...
+
+        // The resulting parse tree for `&x as T[0]` has a precedence of `((&x) as T)[0]`.
+        let with_postfix = self.parse_dot_or_call_expr_with_(expr, span)?;
+        if !matches!(with_postfix.kind, ExprKind::Cast(_, _)) {
+            let expr_str = self.span_to_snippet(span);
+
+            let msg = format!(
+                "casts followed by {} are not supported",
+                match with_postfix.kind {
+                    ExprKind::Index(_, _) => "index operators",
```
Comment (Centril) [inline src/librustc_parse/parser/expr.rs]:
```suggestion
                    ExprKind::Index(_, _) => "indexing",
```

File: src/librustc_parse/parser/expr.rs [hunk 9]
```diff
@@ -621,7 +621,44 @@ impl<'a> Parser<'a> {
...
+                    ExprKind::Try(_) => "try operators",
```
Comment (Centril) [inline src/librustc_parse/parser/expr.rs]:
```suggestion
                    ExprKind::Try(_) => "?",
```

File: src/librustc_parse/parser/expr.rs [hunk 10]
```diff
@@ -621,7 +621,44 @@ impl<'a> Parser<'a> {
...
+                    ExprKind::Field(_, _) => "field access expressions",
```
Comment (Centril) [inline src/librustc_parse/parser/expr.rs]:
```suggestion
                    ExprKind::Field(_, _) => "a field access",
```

File: src/librustc_parse/parser/expr.rs [hunk 11]
```diff
@@ -621,7 +621,44 @@ impl<'a> Parser<'a> {
...
+                    ExprKind::MethodCall(_, _) => "method call expressions",
```
Comment (Centril) [inline src/librustc_parse/parser/expr.rs]:
```suggestion
                    ExprKind::MethodCall(_, _) => "a method call",
```

File: src/librustc_parse/parser/expr.rs [hunk 12]
```diff
@@ -621,7 +621,44 @@ impl<'a> Parser<'a> {
...
+                    ExprKind::Await(_) => "awaits",
```
Comment (Centril) [inline src/librustc_parse/parser/expr.rs]:
```suggestion
                    ExprKind::Await(_) => "`.await`",
```

File: src/librustc_parse/parser/expr.rs (hunk 1 above)
Comment (Centril) [inline src/librustc_parse/parser/expr.rs]:
```suggestion
                    ExprKind::Call(..) => "a function call",
                    _ => unreachable!("parse_dot_or_call_expr_with_ shouldn't produce this"),
```

File: src/librustc_parse/parser/expr.rs (hunk 2 above)
Comment (Centril) [reply src/librustc_parse/parser/expr.rs]: It's correct that `parse_dot_or_call_expr_with_` cannot possibly result in `::Cast` or `::Type` again and will give back the expression passed to it in those cases. However, this is also relying on facts on the ground that may change with time. To prevent such accidents in the future, I think we should make some enhancements:

- Let's make sure there's a test for `expr :/as Type1 :/as Type2` (4 cases, test all of them) and that these are parse failures.
- When `parse_dot_or_call_expr_with_` passes back the expression, it does not reallocate. This means that you should be able to hash the address before the call and after and they should be the same. So this can be added as an `||`-ed condition after the `!matches(...)`. This shouldn't change the semantics, but it does add a measure of robustness.

> But this introduces new test failures, so we've clearly done something wrong. Maybe this is it?

The failures come from not anticipating that this function is also used for type ascriptions (as noted by @petrochenkov), e.g. `foo: Vec<u8>`. (See the function right below this one for how that happens.)

File: src/librustc_parse/parser/expr.rs [hunk 13]
```diff
@@ -621,7 +621,44 @@ impl<'a> Parser<'a> {
...
+        let expr = type_result?;
+        let span = expr.span;
+
+        // The resulting parse tree for `&x as T[0]` has a precedence of `((&x) as T)[0]`.
+        let with_postfix = self.parse_dot_or_call_expr_with_(expr, span)?;
+        if !matches!(with_postfix.kind, ExprKind::Cast(_, _)) {
+            let expr_str = self.span_to_snippet(span);
+
+            let msg = format!(
+                "casts followed by {} are not supported",
```
Comment (Centril) [inline src/librustc_parse/parser/expr.rs]:
```suggestion
                "casts cannot be followed by {}",
```

File: src/librustc_parse/parser/expr.rs (hunk 2 above)
Comment (daboross) [reply src/librustc_parse/parser/expr.rs]: Makes sense that we want to make it more reliable- we've added in address hashing, or at least what I think is good address hashing.

As for `expr :/as Type1 :/as Type2`, I've added tests, but they don't fail. Looking at how this behaves prior to these changes, I don't think these are expected to fail? `x as T1 as T2` is valid today. This doesn't change that, it'll still just parse `x as T1`, then fail to see any postfix, then go back up to `parse_assoc_expr` and parse the second `as T2` (or `: T2`).

Given that we test the expr pointer hash now, if `parse_dot_or_call_expr_with_` ever changes to start parsing type ascriptions or casts, then these tests _should_ start to fail because we'll trigger our error message. I think this is OK?

---

> The failures come from not anticipating that this function is also used for type ascriptions (as noted by @petrochenkov), e.g. foo: Vec<u8>. (See the function right below this one for how that happens.)

We've gone through and fixed this, I think.

File: src/librustc_parse/parser/expr.rs (hunk 6 above)
Comment (daboross) [reply src/librustc_parse/parser/expr.rs]: That sounds like good general advice! We've moved the behavior out to a separate method.

File: src/test/ui/parser/issue-35813-postfix-after-cast.rs (hunk 7 above)
Comment (daboross) [reply src/test/ui/parser/issue-35813-postfix-after-cast.rs]: Test cases added!

**Comment by daboross** [comment]
We've updated this with suggestions & more test fixes.

The checking that we've not reallocated sounds good, but like it might be more strict than this code really needs. I was thinking hashing the whole struct would be more reliable and more exactly what we want. Would that extra reliability be worth the expense, or do you think hashing just the pointer is better?

Besides that, we've done all the improvements we can think of for this PR.

File: src/librustc_parse/parser/expr.rs [hunk 14]
```diff
@@ -606,17 +606,83 @@ impl<'a> Parser<'a> {
...
+            if self.last_type_ascription.map_or(false, |last_ascription| last_ascription.1) {
+                self.maybe_annotate_with_ascription(&mut err, false);
+            } else {
+                if let Ok(expr_str) = expr_str {
+                    err.span_suggestion(
+                        span,
+                        suggestion,
+                        format!("({})", expr_str),
+                        Applicability::MachineApplicable,
+                    );
```
Comment (estebank) [inline src/librustc_parse/parser/expr.rs]: Consider using the following instead:
```suggestion
                    let suggestions = vec![(span.shrink_to_lo(), "(".to_string()), (span.shrink_to_hi(), ")".to_string())];
                    err.span_suggestions(suggestion, suggestions, Applicability::MachineApplicable);
```

This will make the suggestion never to be inline, but it will point at the places where the braces get added. This makes it easier to see what the suggestion is at a glance.

File: src/test/ui/parser/issue-35813-postfix-after-cast.rs [hunk 15]
```diff
@@ -0,0 +1,141 @@
...
+    }
+    if 5u64: u64: u64 == 0u64 {
+
+    }
+    let _ = 5u64: u64: u64 as u8 as i8 == 9i8;
+    let _ = 0i32: i32: i32;
+    let _ = 0 as i32: i32;
+    let _ = 0i32: i32 as i32;
+    let _ = 0 as i32 as i32;
+    let _ = 0i32: i32: i32 as u32 as i32;
```
Comment (estebank) [inline src/test/ui/parser/issue-35813-postfix-after-cast.rs]: Should we also have these tests with trailing method calls?

Comment (daboross) [reply src/test/ui/parser/issue-35813-postfix-after-cast.rs]: Added!

File: src/librustc_parse/parser/expr.rs (hunk 14 above)
Comment (daboross) [reply src/librustc_parse/parser/expr.rs]: We had to use multipart_suggestion rather than span_suggestions here to accept a `Vec<(Span, String)>`, but besides that this is implemented!

File: src/librustc_parse/parser/expr.rs (hunk 5 above)
Comment (daboross) [reply src/librustc_parse/parser/expr.rs]: Fixed the temporary/Ok wrapping!

As for `expr.span`, couldn't get that to work. We pass ownership of cast_expr into parse_dot_or_call_with_, and it seemed nicer to just save the span than to try to save the whole expr?

**Comment by daboross** [comment]
Added latest suggestions!

File: src/librustc_parse/parser/expr.rs [hunk 16]
```diff
@@ -606,17 +606,79 @@ impl<'a> Parser<'a> {
...
+                    ExprKind::Try(_) => "?",
+                    ExprKind::Field(_, _) => "a field access",
+                    ExprKind::MethodCall(_, _) => "a method call",
+                    ExprKind::Call(_, _) => "a function call",
+                    ExprKind::Await(_) => "`.await`",
+                    _ => unreachable!("parse_dot_or_call_expr_with_ shouldn't produce this"),
+                }
+            );
+            let mut err = self.struct_span_err(span, &msg);
+            // if type ascription is "likely an error", the user will already be getting a useful
```
Comment (Centril) [inline src/librustc_parse/parser/expr.rs]:
```suggestion
            // If type ascription is "likely an error", the user will already be getting a useful
```

**Comment by daboross** [comment]
Fixes for those last two suggestions applied!

**Review by Centril — APPROVED** [review]
Looks good; I'll leave final approval to @estebank in case they have any other remarks; otherwise r=me

**Comment by Centril** [comment]
Ping @estebank :)

File: src/test/ui/parser/issue-35813-postfix-after-cast.stderr [hunk 17]
```diff
@@ -0,0 +1,392 @@
...
+LL |     (Err(0u64) as Result<u64,u64>)?;
+   |     ^                            ^
+
+error: casts cannot be followed by ?
+  --> $DIR/issue-35813-postfix-after-cast.rs:121:5
+   |
+LL |     Err(0u64): Result<u64,u64>?;
+   |     ^^^^^^^^^-^^^^^^^^^^^^^^^^
+   |              |
+   |              help: maybe write a path separator here: `::`
```
Comment (estebank) [inline src/test/ui/parser/issue-35813-postfix-after-cast.stderr]: This case seems to be unhandled (but that might be ok).

File: src/librustc_parse/parser/expr.rs [hunk 18]
```diff
@@ -606,17 +606,70 @@ impl<'a> Parser<'a> {
...
+        &mut self,
+        cast_expr: P<Expr>,
+    ) -> PResult<'a, P<Expr>> {
+        // Save the memory location of expr before parsing any following postfix operators.
+        // This will be compared with the memory location of the output expression.
+        // If they different we can assume we parsed another expression because the existing expression is not reallocated.
+        let addr_before = &*cast_expr as *const _ as usize;
+        let span = cast_expr.span;
+        let with_postfix = self.parse_dot_or_call_expr_with_(cast_expr, span)?;
+        let changed = addr_before != &*with_postfix as *const _ as usize;
```
Comment (estebank) [inline src/librustc_parse/parser/expr.rs]: It feels weird to me to use the memory addresses for this, but I don't see a reason for it to ever fail...

**Review by estebank — APPROVED** [review]
LGTM overall, other than a couple of nitpicks.

r? @Centril r=Centril
