### PR TITLE
Analyse storage liveness and preserve it during generator transformation

### LINKED ISSUE #44179: StorageLive and StorageDead annotations in generators are wrong
The generator

```rust
|| {
        if { yield; false } {
            yield;
            loop {}
        }
        yield
    }
```

produces the following MIR:

```
fn main::{{closure}}(_1: &mut [generator@src/main.rs:20:15: 26:6 ((), bool)]) -> std::ops::GeneratorState<(), ()> {
    let mut _0: std::ops::GeneratorState<(), ()>; // return pointer
    let mut _2: ();
    let mut _3: bool;
    let mut _4: ();
    let mut _5: ();
    let mut _6: ();
    let mut _7: ();
    let mut _8: ();
    let mut _9: ();
    let mut _10: ();

    bb0: {
        switchInt(((*_1).0: u32)) -> [2u32: bb2, 0u32: bb1, 3u32: bb5, 4u32: bb7, 1u32: bb11, 5u32: bb9, otherwise: bb9]; // scope 0 at src/main.rs:20:15: 26:6
    }

    bb1: {
        StorageLive(_3);                 // scope 0 at src/main.rs:21:12: 21:28
        StorageLive(_5);                 // scope 0 at src/main.rs:21:14: 21:19
        _5 = ();                         // scope 0 at src/main.rs:21:14: 21:19
        ((*_1).0: u32) = const 2u32;     // scope 0 at src/main.rs:21:14: 21:19
        _0 = std::ops::GeneratorState<(), ()>::Yielded(_5,); // scope 0 at src/main.rs:21:14: 21:19
        return;                          // scope 0 at src/main.rs:21:14: 21:19
    }

    bb2: {
        _4 = ();                         // scope 0 at src/main.rs:21:14: 21:19
        StorageDead(_5);                 // scope 0 at src/main.rs:21:19: 21:19
        _3 = const false;                // scope 0 at src/main.rs:21:21: 21:26
        switchInt(_3) -> [0u8: bb4, otherwise: bb3]; // scope 0 at src/main.rs:21:9: 24:10
    }

    bb3: {
        StorageLive(_7);                 // scope 0 at src/main.rs:22:13: 22:18
        _7 = ();                         // scope 0 at src/main.rs:22:13: 22:18
        ((*_1).0: u32) = const 3u32;     // scope 0 at src/main.rs:22:13: 22:18
        _0 = std::ops::GeneratorState<(), ()>::Yielded(_7,); // scope 0 at src/main.rs:22:13: 22:18
        return;                          // scope 0 at src/main.rs:22:13: 22:18
    }

    bb4: {
        _2 = ();                         // scope 0 at src/main.rs:21:9: 24:10
        StorageDead(_3);                 // scope 0 at src/main.rs:24:10: 24:10
        StorageLive(_9);                 // scope 0 at src/main.rs:25:9: 25:14
        _9 = ();                         // scope 0 at src/main.rs:25:9: 25:14
        ((*_1).0: u32) = const 4u32;     // scope 0 at src/main.rs:25:9: 25:14
        _0 = std::ops::GeneratorState<(), ()>::Yielded(_9,); // scope 0 at src/main.rs:25:9: 25:14
        return;                          // scope 0 at src/main.rs:25:9: 25:14
    }

    bb5: {
        _6 = ();                         // scope 0 at src/main.rs:22:13: 22:18
        StorageDead(_7);                 // scope 0 at src/main.rs:22:18: 22:18
        goto -> bb6;                     // scope 0 at src/main.rs:23:13: 23:20
    }

    bb6: {
        _8 = ();                         // scope 0 at src/main.rs:23:18: 23:20
        goto -> bb6;                     // scope 0 at src/main.rs:23:13: 23:20
    }

    bb7: {
        _10 = ();                        // scope 0 at src/main.rs:25:9: 25:14
        StorageDead(_9);                 // scope 0 at src/main.rs:25:14: 25:14
        goto -> bb10;                    // scope 0 at src/main.rs:26:6: 26:6
    }

    bb8: {
        ((*_1).0: u32) = const 5u32;     // scope 0 at src/main.rs:26:6: 26:6
        _0 = std::ops::GeneratorState<(), ()>::Complete(_10,); // scope 0 at src/main.rs:26:6: 26:6
        return;                          // scope 0 at src/main.rs:26:6: 26:6
    }

    bb9: {
        assert(const false, "generator resumed after completion") -> bb9; // scope 0 at src/main.rs:20:15: 26:6
    }

    bb10: {
        goto -> bb8;                     // scope 0 at src/main.rs:26:6: 26:6
    }

    bb11: {
        assert(const false, "generator resumed after panicking") -> bb9; // scope 0 at src/main.rs:20:15: 26:6
    }
}
```

Note the assignment to `_3` in `bb2`, which is not preceded by a `StorageLive` in this invocation of the generator.

Full example in the playground: https://play.rust-lang.org/?gist=680d18fb9f9bdc91ab969fdbd8bb72a2&version=nightly

cc @Zoxc

### LINKED ISSUE #44184: ICE with generators: `Broken MIR: generator contains type ... in MIR, but typeck only knows about ...`
This seems to be some sort of interaction with the `String` inside the `Command` enum in the following code as removing either variant stops the ICE from occuring.

Example:

https://play.rust-lang.org/?gist=1d2672fd04e7df3dccbaf140f99fa7f6&version=nightly

Gives an ICE `internal compiler error: /checkout/src/librustc_mir/transform/generator.rs:340: Broken MIR: generator contains type std::string::String in MIR, but typeck only knows about ((), std::option::Option<Command>, Command)`

## Meta

`rustc --version --verbose`:
```
rustc 1.21.0-nightly (c11f689d2 2017-08-29)
binary: rustc
commit-hash: c11f689d2475dd9ab956e881238d5d7b6b485efb
commit-date: 2017-08-29
host: x86_64-pc-windows-msvc
release: 1.21.0-nightly
LLVM version: 4.0
```

Backtrace:
```
error: internal compiler error: src\librustc_mir\transform\generator.rs:340: Broken MIR: generator contains type std::string::String in MIR, but typeck only knows about ((), std::option::Option<Command>, Command)
  --> src\main.rs:15:5
   |
15 | /     move ||{
16 | |         loop{
17 | |             let val = control_interface_next();
18 | |             if let Some(command) = val{
...  |
30 | |         }
31 | |     }
   | |_____^

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.21.0-nightly (c11f689d2 2017-08-29) running on x86_64-pc-windows-msvc

note: run with `RUST_BACKTRACE=1` for a backtrace

thread 'rustc' panicked at 'Box<Any>', src\librustc_errors\lib.rs:443:8
stack backtrace:
   0: _rdl_shrink_in_place
   1: std::panicking::Location::column
   2: std::panicking::Location::column
   3: std::panicking::rust_panic_with_hook
   4: <unknown>
   5: <unknown>
   6: <rustc_mir::shim::DropShimElaborator<'a, 'tcx> as rustc_mir::util::elaborate_drops::DropElaborator<'a, 'tcx>>::clear_drop_flag
   7: <rustc_mir::shim::DropShimElaborator<'a, 'tcx> as rustc_mir::util::elaborate_drops::DropElaborator<'a, 'tcx>>::clear_drop_flag
   8: <rustc_mir::transform::generator::StateTransform as rustc::mir::transform::MirPass>::run_pass
   9: <rustc_mir::shim::DropShimElaborator<'a, 'tcx> as rustc_mir::util::elaborate_drops::DropElaborator<'a, 'tcx>>::get_drop_flag
  10: <rustc_mir::shim::DropShimElaborator<'a, 'tcx> as rustc_mir::util::elaborate_drops::DropElaborator<'a, 'tcx>>::get_drop_flag
  11: rustc::dep_graph::graph::DepGraph::in_task
  12: rustc::ty::maps::<impl rustc::ty::maps::queries::optimized_mir<'tcx>>::try_get
  13: rustc::ty::maps::TyCtxtAt::optimized_mir
  14: rustc::ty::<impl rustc::ty::context::TyCtxt<'a, 'gcx, 'tcx>>::instance_mir
  15: <rustc_trans::builder::Builder<'a, 'tcx> as core::ops::drop::Drop>::drop
  16: <rustc_trans::builder::Builder<'a, 'tcx> as core::ops::drop::Drop>::drop
  17: rustc_trans::base::trans_crate
  18: rustc_trans::base::trans_crate
  19: rustc_driver::driver::phase_4_translate_to_llvm
  20: rustc_driver::driver::compile_input
  21: <rustc_driver::derive_registrar::Finder as rustc::hir::itemlikevisit::ItemLikeVisitor<'v>>::visit_impl_item
  22: rustc_driver::driver::compile_input
  23: rustc_driver::run_compiler
  24: <unknown>
  25: _rust_maybe_catch_panic
  26: <rustc_driver::derive_registrar::Finder as rustc::hir::itemlikevisit::ItemLikeVisitor<'v>>::visit_impl_item
  27: std::sys::imp::thread::Thread::new
  28: BaseThreadInitThunk

error: Could not compile `generator_ice`.
```

### PR DESCRIPTION
**Pull request by Zoxc**
This uses a dataflow analysis on `StorageLive` and `StorageDead` statements to infer where the storage of locals are live. The result of this analysis is intersected with the regular liveness analysis such that a local is can only be live when its storage is. This fixes https://github.com/rust-lang/rust/issues/44184. If the storage of a local is live across a suspension point, we'll insert a `StorageLive` statement for it after the suspension point so storage liveness is preserved. This fixes https://github.com/rust-lang/rust/issues/44179.

r? @arielb1

### CODE REVIEW

File: src/librustc_mir/transform/generator.rs [hunk 1]
```diff
@@ -222,33 +229,52 @@ impl<'a, 'tcx> MutVisitor<'tcx> for TransformVisitor<'a, 'tcx> {
...
                     self.make_state(state_idx, v)),
             });
+            let state = if let Some(resume) = resume { // Yield
+                let state = 3 + self.suspension_points.len() as u32;
+
+                let liveness = self.storage_liveness.get(&block).unwrap();
+
+                for i in 0..(self.mir_local_count) {
+                    let l = Local::new(i);
+                    if liveness.contains(&l) && !self.remap.contains_key(&l) {
```
Comment (arielb1) [inline src/librustc_mir/transform/generator.rs]: A function return automatically does a `StorageDead` of all locals, so there is no need to insert anything here.

File: src/librustc_mir/transform/generator.rs [hunk 2]
```diff
@@ -308,33 +329,82 @@ fn replace_result_variable<'tcx>(ret_ty: Ty<'tcx>,
...
+    let analysis = MaybeStorageLive::new(mir);
+    let storage_live =
+        dataflow::do_dataflow(tcx, mir, node_id, &[], &dead_unwinds, analysis,
+                              |bd, p| &bd.mir().local_decls[p]);
+
+    let mut ignored = StorageIgnored(IdxSetBuf::new_filled(mir.basic_blocks().len()));
+    ignored.visit_mir(mir);
+
     let mut set = liveness::LocalSet::new_empty(mir.local_decls.len());
     let result = liveness::liveness_of_locals(mir);
```
Comment (arielb1) [inline src/librustc_mir/transform/generator.rs]: nit: I would rename this to `liveness`

File: src/librustc_mir/transform/generator.rs [hunk 3]
```diff
@@ -308,33 +329,82 @@ fn replace_result_variable<'tcx>(ret_ty: Ty<'tcx>,
...
-            set.union(&result.outs[block]);
+            let loc = Location {
+                block: block,
+                statement_index: data.statements.len(),
+            };
+
+            let mut storage_liveness = state_for_location(loc, &analysis, &storage_live);
+
+            storage_liveness_map.insert(block, storage_liveness.clone());
+
```
Comment (arielb1) [inline src/librustc_mir/transform/generator.rs]: ... and also have a `let liveness = storage_liveness;` here. It's free.

File: src/librustc_mir/transform/generator.rs [hunk 4]
```diff
@@ -455,46 +544,29 @@ fn create_generator_drop_shim<'a, 'tcx>(
...
+            };
+            mir.basic_blocks_mut()[block].terminator = Some(term);
+            (point.state, block)
+        })
     }).collect();
 
     cases.insert(0, (0, drop_clean));
 
-    // The poisoned state 1 falls through to the default case which is just to return
+    // The returned state 1 and the  poisoned state 2 falls through to
```
Comment (arielb1) [inline src/librustc_mir/transform/generator.rs]: nit: double space `the  poisoned state`

Comment (arielb1) [inline src/librustc_mir/transform/generator.rs]: nit: double space `the  poisoned state`

**Comment by arielb1** [comment]
Nice! r=me modulo nits.

File: src/librustc_mir/transform/generator.rs [hunk 5]
```diff
@@ -126,6 +127,14 @@ fn self_arg() -> Local {
     Local::new(1)
 }
 
+struct SuspensionPoint {
+    state: u32,
+    resume: BasicBlock,
+    drop: Option<BasicBlock>,
+    storage_liveness: liveness::LocalSet,
```
Comment (arielb1) [inline src/librustc_mir/transform/generator.rs]: I find this a bit ugly. Can you have a

```Rust
fn make_storage_live(..., point: &SuspensionPoint, terminates_to: BasicBlock) {
}
```

And call it from both collects to avoid the ugly mutation? I think you can.

File: src/librustc_mir/transform/generator.rs [hunk 6]
```diff
@@ -781,6 +814,30 @@ impl MirPass for StateTransform {
 
         dump_mir(tcx, None, "generator_post-transform", &0, source, mir);
 
+        // Create StorageLive instruction blocks for suspension points
+        for point in &mut transform.suspension_points {
```
Comment (arielb1) [inline src/librustc_mir/transform/generator.rs]: (this is the part that could be extracted to a function)

**Comment by arielb1** [comment]
I think it's possible to merge the 3 special case states into SuspensionPoint and clean up quite a bit of code, but I can leave that to a further PR.

**Comment by kennytm** [comment]
`i686-gnu-nopt` failed, an error index failed, legit. 

I think you need to build the error index yourself to find out what is happening at line 11731 😓 

```
[01:34:13] failures:
[01:34:13] 
[01:34:13] ---- /checkout/obj/build/i686-unknown-linux-gnu/test/error-index.md - Rust_Compiler_Error_Index (line 11731) stdout ----
[01:34:13] 	thread 'rustc' panicked at 'assertion failed: `(left == right)`
[01:34:13]   left: `2`,
[01:34:13]  right: `1`', /checkout/src/librustc_data_structures/bitslice.rs:119:4
[01:34:13] thread 'rustc' panicked at 'couldn't compile the test', /checkout/src/librustdoc/test.rs:280:12
[01:34:13] 
[01:34:13] 
[01:34:13] failures:
[01:34:13]     /checkout/obj/build/i686-unknown-linux-gnu/test/error-index.md - Rust_Compiler_Error_Index (line 11731)
[01:34:13] 
[01:34:13] test result: FAILED. 660 passed; 1 failed; 18 ignored; 0 measured; 0 filtered out
```
