### PR TITLE
rustdoc: never link to unnamable items

### LINKED ISSUE #143222: `Not Found` error for the hyperlink from `rustc_middle::ty::TypeFlags` to `InternalBitFlags`
### Location

When press `InternalBitFlags` type hyperlink in https://doc.rust-lang.org/stable/nightly-rustc/rustc_middle/ty/struct.TypeFlags.html 

### Summary

The hyperlink links to https://doc.rust-lang.org/stable/nightly-rustc/rustc_type_ir/flags/_/struct.InternalBitFlags.html , which is broken.

The document is rendered like this:
```
pub struct TypeFlags([InternalBitFlags](https://doc.rust-lang.org/stable/nightly-rustc/rustc_type_ir/flags/_/struct.InternalBitFlags.html));
```

I guess `InternalBitFlags` has no dedicated type definition, as `TypeFlags` itself is a struct, not containing other type.

https://github.com/rust-lang/rust/blob/35f6036521777bdc0dcea1f980be4c192962a168/compiler/rustc_type_ir/src/flags.rs#L11-L19

### PR DESCRIPTION
**Pull request by lolbinarycat**
fixes rust-lang/rust#143222

### CODE REVIEW

File: tests/rustdoc/reexport/auxiliary/wrap-unnamable-type.rs [hunk 1]
```diff
@@ -0,0 +1,12 @@
...
+}
+
+pub struct Foo(<Foo as crate::Assoc>::Ty);
+
+const _: () = {
+    impl crate::Assoc for Foo {
+        type Ty = Bar;
+    }
+    pub struct Bar;
+};
```
Comment (GuillaumeGomez) [inline tests/rustdoc/reexport/auxiliary/wrap-unnamable-type.rs:12]: Do we need to have this as a dependency for this test? Can't it be done within the current crate?

Comment (GuillaumeGomez) [reply tests/rustdoc/reexport/auxiliary/wrap-unnamable-type.rs:12]: Also, what happens if the const is named `X`?

Comment (lolbinarycat) [reply tests/rustdoc/reexport/auxiliary/wrap-unnamable-type.rs:12]: The bug only happens during cross-crate re-exports.  Otherwise a separate failsafe kicks in.

I was under the impression that the `_` was a delibraerately injected placeholder, but maybe it is just the constant name, if so we'll need a more principled approach.

Comment (lolbinarycat) [reply tests/rustdoc/reexport/auxiliary/wrap-unnamable-type.rs:12]: Ok, yeah, you're right, my assumptions were wrong.  Just looking at the path isn't enough.

Comment (GuillaumeGomez) [reply tests/rustdoc/reexport/auxiliary/wrap-unnamable-type.rs:12]: Need to check what kind of item (block more precisely) the parent is. If it's not a module, then it's likely wrong.

Comment (lolbinarycat) [reply tests/rustdoc/reexport/auxiliary/wrap-unnamable-type.rs:12]: any idea what datastructure would retain that info in the cross-crate case? I'm somewhat struggling to understand how we even reconstruct path info and such from an rlib.

Comment (GuillaumeGomez) [reply tests/rustdoc/reexport/auxiliary/wrap-unnamable-type.rs:12]: Path doesn't matter here, you need to check what is its parent.

File: src/librustdoc/html/format.rs [hunk 2]
```diff
@@ -490,6 +492,20 @@ fn generate_item_def_id_path(
     Ok((url_parts, shortty, fqp))
 }
 
+/// Checks if the given defid refers to an item that is unnamable, such as one defined in a const block.
+fn is_unnamable(tcx: TyCtxt<'_>, did: DefId) -> bool {
+    let mut cur_did = did;
+    while let Some(parent) = tcx.opt_parent(cur_did) {
```
Comment (GuillaumeGomez) [inline src/librustdoc/html/format.rs:487]: I think this code is wrong: we can link to an impl associated item even if the impl is in a const/function block.

Comment (lolbinarycat) [reply src/librustdoc/html/format.rs:487]: right, i think impls should break with a `return false` and only modules should continue up...

well technically we can only link to an impl item if the thing being impl'd on is nameable, but i'm not sure if that's something observable.

Comment (GuillaumeGomez) [reply src/librustdoc/html/format.rs:487]: Just discovered that we can have modules in any blocks. Dark magic. XD

Comment (GuillaumeGomez) [reply src/librustdoc/html/format.rs:487]: Also, if the item is not public, it'll be stripped so should be fine. (for impl block as parents)

**Review by GuillaumeGomez — APPROVED** [review]

**Comment by GuillaumeGomez** [comment]
Thanks for the fix!

@bors r+ rollup

**Comment by panstromek** [comment]
Ping from triage:

Looks like this PR introduced a regression in https://github.com/rust-lang/rust/pull/144768.

Based on detailed results, the regression is in the `def_kind` query which this PR uses. The number of invocations is increased by 10-20% on some benchmarks.

Is this regression expected or justified?

**Comment by GuillaumeGomez** [comment]
I expected a regression, but not this big. I'll revert the PR for now and we can iterate over the performance improvement.

**Comment by panstromek** [comment]
Ok. It doesn't seem that big to require a revert to me, so just to make sure I didn't add confusion here: 10%-20% change 
is on the number of `def_kind` invocations, but the overall regression is around 0.5% on a few doc benchmarks. 

Here's the perf run: https://perf.rust-lang.org/compare.html?start=6c02dd4eae83befde07dc4782395e2005055e9fa&end=e3ee7f7aea5b45af3b42b5e4713da43876a65ac9&stat=instructions:u

**Comment by GuillaumeGomez** [comment]
Ah I see. Didn't check the report yet so spoke too quickly. Still, we will need to bring down the numbers. :)

**Comment by lolbinarycat** [comment]
Obvious ideas optimizations:
* only run this when `-Znormalize-docs` is enabled
* only run this on types that have been normalized or are being normalized

the former is much easier to implement, but the perf improvement would go away if we ever make normalizing docs the default.  the latter should actually be a substantial improvement, but is slightly trickier to implement.  I'll see what i can do.

**Comment by GuillaumeGomez** [comment]
That's a good start already. I also thought about caching this query with compiler queries.

**Comment by lolbinarycat** [comment]
I suppose caching would improve things if an item is being linked to from multiple locations, but i do think it would be more ideal to try to simply disable normalization when it would cause a situation like this.

**Comment by GuillaumeGomez** [comment]
I meant that in addition to your ideas. I'd like your suggestions to be implemented first, and then we'll see if we need to go further. I'll let you implement your ideas and then we can check perf results on them.

**Comment by lolbinarycat** [comment]
Making it a query would also cache it across incremental builds, right? that might be worth it.

**Comment by lolbinarycat** [comment]
I moved the `is_unnamable` check into `normalize`, and it worked perfectly, except for the fact that it turns out we don't actually need `normalize-docs` to repro this bug, the bad link also shows up in the "trait implementations" section, without any unstable options:

image

Doing the check at normalization is still nice though, since it means we'll just link to the associated item like usual, instead of normalizing to something that can't be linked to:

image

maybe we should turn it into a cached compiler query then call it in both locations? it shouldn't have significant overhead, since it'll be getting cached.
