### PR TITLE
rustbuild: canonicalize prefix `install_sh`

### LINKED ISSUE #36989: `make install` doesn't work correctly with relative directory prefixes
When I configured with  `--prefix=install-prefix` and ran `make install`, my install ended up in `./tmp/empty_dir/install-prefix`.

### PR DESCRIPTION
**Pull request by tamird**
Testing:
```
  $ git diff
  diff --git a/config.toml.example b/config.toml.example
  index 9dd3002506..b47bc490cd 100644
  --- a/config.toml.example
  +++ b/config.toml.example
  @@ -196,7 +196,7 @@
   [install]

   # Instead of installing to /usr/local, install to this path instead.
  -#prefix = "/usr/local"
  +prefix = "install-prefix"

   # Where to install system configuration files
   # If this is a relative path, it will get installed in `prefix` above
  $ mkdir install-prefix
  $ ./x.py install -i --stage 0 --config config.toml.example
  ...
  $ ls install-prefix/
  bin	lib	share
```

Closes #36989.

r? @Mark-Simulacrum

### CODE REVIEW

File: src/bootstrap/install.rs [hunk 1]
```diff
@@ -72,8 +72,11 @@ fn install_sh(
     let bindir_default = PathBuf::from("bin");
     let libdir_default = PathBuf::from("lib");
     let mandir_default = datadir_default.join("man");
-    let prefix = build.config.prefix.as_ref().unwrap_or(&prefix_default);
-    let sysconfdir = build.config.sysconfdir.as_ref().unwrap_or(&sysconfdir_default);
+    let canonicalize = |p: &PathBuf| {
+        fs::canonicalize(p).expect(&format!("could not canonicalize {}", p.display()))
+    };
+    let prefix = build.config.prefix.as_ref().map_or(prefix_default, canonicalize);
+    let sysconfdir = build.config.sysconfdir.as_ref().map_or(sysconfdir_default, canonicalize);
```
Comment (Mark-Simulacrum) [inline src/bootstrap/install.rs]: I think we might have to be more careful about `sysconfdir` here. If it's an absolute path, then canonicalizing it is fine, but if it's relative, it'll be relative to `prefix` per the documentation, which makes this code (I believe) do the wrong thing.

I think I'd probably branch on is_absolute/is_relative on the path after mapping it to the default to determine if we need to canonicalize it (though it might be true that like all of the other paths, there's never a need to do so?).

Comment (tamird) [reply src/bootstrap/install.rs]: Oh, you're absolutely right. I was confused by the default value being `"/etc"` rather than "etc". Fixed.

File: src/bootstrap/install.rs [hunk 2]
```diff
@@ -66,13 +66,15 @@ fn install_sh(
     build.info(&format!("Install {} stage{} ({:?})", package, stage, host));
 
     let prefix_default = PathBuf::from("/usr/local");
-    let sysconfdir_default = PathBuf::from("/etc");
+    let sysconfdir_default = PathBuf::from("etc");
```
Comment (Mark-Simulacrum) [inline src/bootstrap/install.rs]: Er, no, the previous default was correct I think? In that normally you want to have the sysconfdir be `/etc` and the rest of the dirs be relative to `/usr/local`. The confusing part of this is that `Path::new("/usr/local").join("/etc")` evaluates to `/etc` which is somewhat unexpected, though correct.

Comment (tamird) [reply src/bootstrap/install.rs]: Oh, wow - that is very surprising, but of course, you are right. https://play.rust-lang.org/?gist=9fca8ef12a8ac532ceaa12383983c62f&version=stable

Fixed again!
