### PR TITLE
Opaque types' generic params do not imply anything about their hidden type's lifetimes

### LINKED ISSUE #97104: late-bound lifetimes on type-alias-impl-trait can be unsound
```rust
#![feature(type_alias_impl_trait)]

mod lifetime_params {
    type Ty<'a> = impl Sized + 'a;
    fn define(s: &str) -> Ty<'_> { s }

    type BadFnSig = fn(Ty<'_>) -> &str;
    type BadTraitRef = dyn Fn(Ty<'_>) -> &str;
}

mod type_params {
    type Ty<T> = impl Sized;
    fn define<T>(s: T) -> Ty<T> { s }

    type BadFnSig = fn(Ty<&str>) -> &str;
    type BadTraitRef = dyn Fn(Ty<&str>) -> &str;
}
```
[Playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=2ef0fa3e9e041b4330f87277f536411c).

Prior to #96903, these types were rejected with this error:
```rust
error[E0581]: return type references an anonymous lifetime, which is not constrained by the fn input types
 --> /tmp/test9.rs:7:35
  |
7 |     type BadFnSig = fn(Ty<'_>) -> &str;
  |                                   ^^^^
  |
  = note: lifetimes appearing in an associated type are not considered constrained
```

Currently, they're accepted.

Based on the assumption that generic parameters on opaque type are not constrained (see Niko's comment https://github.com/rust-lang/rust/pull/95474#issuecomment-1122953370), I believe the previous behavior is correct.

CC: @oli-obk

@rustbot label F-type_alias_impl_trait A-impl-trait T-compiler A-lifetimes

### PR DESCRIPTION
**Pull request by oli-obk**
fixes #97104

cc @aliemjay

### CODE REVIEW

**Review by aliemjay — APPROVED** [review]
Looks good. Thanks!

I'm thinking if we should consider forcing the hidden type to constrain all generic params of the type alias in TAIT. If so, we won't have such weird differences between opaque types `Adt`s. I'll discuss it further in a zulip stream https://rust-lang.zulipchat.com/#narrow/stream/213817-t-lang/topic/generic.20TAIT.20problems/near/286519266

**Comment by cjgillot** [comment]
r? rust-lang/types

**Comment by aliemjay** [comment]
@lcnr I believe the your reduced is a separate problem, completely orthogonal to the one in hand. 

The  type `dyn for<'a> Callable<Opaque<&'a ()>, Output = &'a str>` must to be rejected because the lifetime `'a` doesn't necessarily constrain the TAIT and thus can't appear in the associated type as dictated by RFC 1214, it's exactly the same reason we reject projection types in `dyn for<'a> Callable<<&'a str as IntoIterator>::Item, Output = &'a str>`.

Meanwhile, the type from your example `dyn for<'a> Foo<&'a str, Assoc = &'a str>`, I believe, is a valid one and should not be rejected per-se, because it requires checking the WF of the TraitRef before each instantiation of `'a`. If anything, we should error in `hr_shit::<DynTrait, _>(x)`

File: src/test/ui/type-alias-impl-trait/constrain_inputs.rs [hunk 1]
```diff
@@ -1,17 +1,33 @@
...
+    //~^ ERROR return type references an anonymous lifetime, which is not constrained by the fn input types
+
+    type BadFnSig = fn(Ty<'_>) -> &str;
+    //~^ ERROR return type references an anonymous lifetime, which is not constrained by the fn input types
+    type BadTraitRef = dyn Fn(Ty<'_>) -> &str;
+    //~^ ERROR binding for associated type `Output` references an anonymous lifetime
 }
 
-mod bar {
+mod type_params {
```
Comment (lcnr) [inline src/test/ui/type-alias-impl-trait/constrain_inputs.rs:15]: are there any `type_params` in this module? :sweat_smile:

File: src/test/ui/type-alias-impl-trait/constrain_inputs_unsound.rs [hunk 2]
```diff
@@ -0,0 +1,31 @@
...
+
+fn extend_lifetime(s: &str) -> Box<dyn AsRef<str> + 'static> {
+    type MalformedTy = dyn for<'a> Callable<Gal<&'a ()>, Output = &'a str>;
+    //~^ ERROR binding for associated type `Output` references lifetime `'a`
+    box_str::<MalformedTy, _>(s)
+}
+
+fn main() {
+    //let extended = extend_lifetime(&String::from("hello"));
+    //println!("{}", extended.as_ref().as_ref());
```
Comment (lcnr) [inline src/test/ui/type-alias-impl-trait/constrain_inputs_unsound.rs:30]:
```suggestion
    let extended = extend_lifetime(&String::from("hello"));
    println!("{}", extended.as_ref().as_ref());
```
or completely remove them imo

File: src/test/ui/type-alias-impl-trait/constrain_inputs_unsound.stderr [hunk 3]
```diff
@@ -0,0 +1,9 @@
+error[E0582]: binding for associated type `Output` references lifetime `'a`, which does not appear in the trait input types
+  --> $DIR/constrain_inputs_unsound.rs:23:58
+   |
+LL |     type MalformedTy = dyn for<'a> Callable<Gal<&'a ()>, Output = &'a str>;
+   |                                                          ^^^^^^^^^^^^^^^^
+
```
Comment (lcnr) [inline src/test/ui/type-alias-impl-trait/constrain_inputs_unsound.stderr:6]: why is the note "lifetimes appearing in an associated type are not considered constrained" not emitted here?

**Review by lcnr — COMMENTED** [review]
seems good, so after my nits are dealt with, r=me

File: src/test/ui/type-alias-impl-trait/constrain_inputs_unsound.stderr (hunk 3 above)
Comment (oli-obk) [reply src/test/ui/type-alias-impl-trait/constrain_inputs_unsound.stderr:6]: We're not checking for higher kinded lifetimes in the diagnostic, we're just checking for names. It would be a larger refactoring to handle the difference between lifetimes on the type alias and lifetimes in a binder.
