### PR TITLE
rustdoc: Don't resolve link to field on different variant

### LINKED ISSUE #107903: Cargo doc spuriously links to random enum variant fields instead of marking links broken
### Problem

In https://github.com/lightningdevkit/rust-lightning/pull/2027 we stumbled across a bug in `cargo doc`, as it checking for broken links didn't work for a now renamed field that is also present in another `enum` variant.

### Steps

A minimal example is this, which doesn't fail, but should:
```Rust
#![deny(broken_intra_doc_links)]

/// Referring to [`TestEnum::Variant1::field_name`]
pub enum TestEnum {
	Variant1 {},
	Variant2 {
		field_name: u64,
	}
}
```

If `TestEnum::Variant1::field_name` is present the docs indeed link to the right variant. If it is missing, `cargo doc` gladly makes the `TestEnum::Variant1::field_name` link point to `TestEnum::Variant2::field_name`, without throwing an error.

### Possible Solution(s)

_No response_

### Notes

_No response_

### Version
```
> cargo --version
cargo 1.65.0 (4bc8f24d3 2022-10-20)
```

### PR DESCRIPTION
**Pull request by clubby789**
Fix #107903

This also gives a more specific diagnostic when the enum has any fields

### CODE REVIEW

**Review by camelid — COMMENTED** [review]
If I understand correctly, this will cause new warnings to appear for paths that previously resolved incorrectly, right?

File: src/librustdoc/passes/collect_intra_doc_links.rs [hunk 1]
```diff
@@ -1674,6 +1675,10 @@ fn resolution_failure(
                     res.descr()
                 )
             };
+            let no_field_on_variant = |variant: Res| {
+                let variant = variant.name(tcx);
+                format!("variant `{variant}` has no such field")
+            };
```
Comment (camelid) [inline src/librustdoc/passes/collect_intra_doc_links.rs:1681]: I'd rather not define a closure for this since it's pretty simple and only used once.

**Comment by clubby789** [comment]
That's right - tested with the example from the linked issue

**Review by GuillaumeGomez — APPROVED** [review]

**Comment by GuillaumeGomez** [comment]
Thanks for this improvement!

@bors r=camelid,GuillaumeGomez rollup
