### PR TITLE
Fix invalid syntax and incomplete suggestion in impl Trait parameter type suggestions for E0311

### LINKED ISSUE #105544: E0311 for `impl Trait` parameter type suggests invalid syntax
Given the following [code](https://play.rust-lang.org/?version=stable&code=fn%20foo%28d%3A%20impl%20Sized%2C%20p%3A%20%26mut%20%28%29%29%20-%3E%20impl%20Sized%20%2B%20%27_%20%7B%0A%20%20%20%20%28d%2C%20p%29%0A%7D%0A):

```rust
fn foo(d: impl Sized, p: &mut ()) -> impl Sized + '_ {
    (d, p)
}
```

The current output is:

```
error[E0311]: the parameter type `impl Sized` may not live long enough
 --> src/lib.rs:2:5
  |
2 |     (d, p)
  |     ^^^^^^
  |
note: the parameter type `impl Sized` must be valid for the anonymous lifetime defined here...
 --> src/lib.rs:1:26
  |
1 | fn foo(d: impl Sized, p: &mut ()) -> impl Sized + '_ {
  |                          ^^^^^^^
note: ...so that the type `impl Sized` will meet its required lifetime bounds
 --> src/lib.rs:2:5
  |
2 |     (d, p)
  |     ^^^^^^
help: consider adding an explicit lifetime bound...
  |
1 | fn foo(d: 'a, impl Sized + 'a, p: &mut ()) -> impl Sized + '_ {
```

Not only the suggested syntax is invalid, it also suggests introducing a fresh lifetime parameter instead of naming the elided one on `p`.

Ping @estebank.

@rustbot modify labels: +A-suggestion-diagnostics +D-invalid-suggestion

### PR DESCRIPTION
**Pull request by yanchen4791**
Fixes #105544

The problems: The suggestion given for E0311 has invalid syntax when the synthetic type parameter is used for Trait type in function declaration:
```rust
fn foo(d: impl Sized) -> impl Sized
```
instead of explicitly specified like the following:
```rust
fn foo<T: Sized>(d: T) -> impl Sized
```
In addition to the syntax error, the suggestions given for E0311 are not complete when multiple elided lifetimes are involved in lifetime bounds, not all involved parameters are given the named lifetime in the suggestions. For the following test case:
```
fn foo(d: impl Sized, p: &mut ()) -> impl Sized + '_ {
    (d, p)
}
```
a good suggestion should add the lifetime 'a to both d and p, instead of d only:
```
fn foo<'a>(d: impl Sized + 'a, p: &'a mut ()) -> impl Sized + '_ {
    (d, p)
}
```

The Solution: Fix the syntax problem in the suggestions when synthetic type parameter is used, and also add lifetimes for all involved parameters.

### CODE REVIEW

**Comment by nagisa** [comment]
r? rust-lang/compiler

File: compiler/rustc_infer/src/infer/error_reporting/mod.rs [hunk 1]
```diff
@@ -2128,18 +2128,24 @@ impl<'tcx> TypeErrCtxt<'_, 'tcx> {
...
         let type_param_span = match bound_kind {
             GenericKind::Param(ref param) => {
                 // Account for the case where `param` corresponds to `Self`,
                 // which doesn't have the expected type argument.
                 if !(generics.has_self && param.index == 0) {
                     let type_param = generics.type_param(param, self.tcx);
+                    is_synthetic = matches!(
+                        type_param.kind,
+                        GenericParamDefKind::Type { synthetic: true, .. }
+                    );
```
Comment (oli-obk) [inline compiler/rustc_infer/src/infer/error_reporting/mod.rs:2142]:
```suggestion
                    is_synthetic = type_param.kind.is_synthetic();
```

File: compiler/rustc_infer/src/infer/error_reporting/mod.rs [hunk 2]
```diff
@@ -2171,11 +2177,67 @@ impl<'tcx> TypeErrCtxt<'_, 'tcx> {
...
+                    matches!(
+                        p.kind,
+                        hir::GenericParamKind::Lifetime { kind: hir::LifetimeParamKind::Explicit }
+                    )
+                }) {
+                    ast_generics.params.first().and_then(|param| Some(param.def_id)).map(
+                        |def_id| {
+                            add_lt_suggs.push(Some((
+                                self.tcx.def_span(def_id).shrink_to_lo(),
+                                format!("{}, ", new_lt),
```
Comment (oli-obk) [inline compiler/rustc_infer/src/infer/error_reporting/mod.rs:2193]:
```suggestion
                                format!("{new_lt}, "),
```

File: compiler/rustc_infer/src/infer/error_reporting/mod.rs [hunk 3]
```diff
@@ -2171,11 +2177,67 @@ impl<'tcx> TypeErrCtxt<'_, 'tcx> {
...
+        let mut add_lt_suggs: Vec<Option<_>> = vec![];
+        if is_synthetic {
+            if let Some(ast_generics) = ast_generics {
+                if ast_generics.params.iter().any(|p| {
+                    matches!(
+                        p.kind,
+                        hir::GenericParamKind::Lifetime { kind: hir::LifetimeParamKind::Explicit }
+                    )
+                }) {
+                    ast_generics.params.first().and_then(|param| Some(param.def_id)).map(
```
Comment (oli-obk) [inline compiler/rustc_infer/src/infer/error_reporting/mod.rs:2189]: Please use an `if let` instead.

File: compiler/rustc_infer/src/infer/error_reporting/mod.rs [hunk 4]
```diff
@@ -2171,11 +2177,67 @@ impl<'tcx> TypeErrCtxt<'_, 'tcx> {
...
+                            )));
+                        },
+                    );
+                } else {
+                    add_lt_suggs
+                        .push(Some((ast_generics.span.shrink_to_hi(), format!("<{}>", new_lt))));
+                }
+            }
+        } else {
+            generics.params.first().and_then(|param| param.def_id.as_local()).map(|def_id| {
```
Comment (oli-obk) [inline compiler/rustc_infer/src/infer/error_reporting/mod.rs:2203]: use an `if let` instead

File: compiler/rustc_infer/src/infer/error_reporting/mod.rs [hunk 5]
```diff
@@ -2171,11 +2177,67 @@ impl<'tcx> TypeErrCtxt<'_, 'tcx> {
...
+                )));
+            });
+        };
+
+        if let Some(ast_generics) = ast_generics {
+            let _ = ast_generics
+                .params
+                .iter()
+                .filter(|p| p.is_elided_lifetime())
+                .map(|p| {
```
Comment (oli-obk) [inline compiler/rustc_infer/src/infer/error_reporting/mod.rs:2216]: Use a for loop

File: compiler/rustc_infer/src/infer/error_reporting/mod.rs [hunk 6]
```diff
@@ -2171,11 +2177,67 @@ impl<'tcx> TypeErrCtxt<'_, 'tcx> {
...
+                    if self.tcx.sess.source_map()
+                        .span_to_prev_source(p.span.shrink_to_hi())
+                        .ok()
+                        .map_or(false, |s| s.as_bytes()[s.len()-1] == b'&')
```
Comment (oli-obk) [inline compiler/rustc_infer/src/infer/error_reporting/mod.rs:2220]:
```suggestion
                        .map_or(false, |s| s.as_bytes().last().unwrap() == b'&')
```

File: compiler/rustc_infer/src/infer/error_reporting/mod.rs [hunk 7]
```diff
@@ -2171,11 +2177,67 @@ impl<'tcx> TypeErrCtxt<'_, 'tcx> {
...
+                    {
+                        add_lt_suggs
+                            .push(Some(
+                                (
+                                    p.span.shrink_to_hi(),
+                                    if let Ok(snip) = self.tcx.sess.source_map().span_to_next_source(p.span)
+                                        && snip.starts_with(' ')
```
Comment (oli-obk) [inline compiler/rustc_infer/src/infer/error_reporting/mod.rs:2227]: Can this situation be recognized without looking at the source?

**Review by oli-obk — CHANGES_REQUESTED** [review]

File: compiler/rustc_infer/src/infer/error_reporting/mod.rs (hunk 1 above)
Comment (yanchen4791) [reply compiler/rustc_infer/src/infer/error_reporting/mod.rs]: Thanks for reviewing. Changed accordingly.

File: compiler/rustc_infer/src/infer/error_reporting/mod.rs (hunk 2 above)
Comment (yanchen4791) [reply compiler/rustc_infer/src/infer/error_reporting/mod.rs]: Changed.

File: compiler/rustc_infer/src/infer/error_reporting/mod.rs (hunk 3 above)
Comment (yanchen4791) [reply compiler/rustc_infer/src/infer/error_reporting/mod.rs]: Changed.

File: compiler/rustc_infer/src/infer/error_reporting/mod.rs (hunk 4 above)
Comment (yanchen4791) [reply compiler/rustc_infer/src/infer/error_reporting/mod.rs]: Changed.

File: compiler/rustc_infer/src/infer/error_reporting/mod.rs (hunk 6 above)
Comment (yanchen4791) [reply compiler/rustc_infer/src/infer/error_reporting/mod.rs]: Changed.

File: compiler/rustc_infer/src/infer/error_reporting/mod.rs (hunk 5 above)
Comment (yanchen4791) [reply compiler/rustc_infer/src/infer/error_reporting/mod.rs]: Changed.

File: compiler/rustc_infer/src/infer/error_reporting/mod.rs (hunk 7 above)
Comment (yanchen4791) [reply compiler/rustc_infer/src/infer/error_reporting/mod.rs:2236]: Did not find other easy ways to do this.

File: compiler/rustc_infer/src/infer/error_reporting/mod.rs [hunk 8]
```diff
@@ -2187,11 +2190,63 @@ impl<'tcx> TypeErrCtxt<'_, 'tcx> {
...
+        let mut add_lt_suggs: Vec<Option<_>> = vec![];
+        if is_synthetic {
+            if let Some(ast_generics) = ast_generics {
+                if ast_generics.params.iter().any(|p| {
+                    matches!(
+                        p.kind,
+                        hir::GenericParamKind::Lifetime { kind: hir::LifetimeParamKind::Explicit }
+                    )
+                })
+                && let Some(def_id) = ast_generics.params.first().and_then(|param| Some(param.def_id)) {
```
Comment (oli-obk) [inline compiler/rustc_infer/src/infer/error_reporting/mod.rs:2202]: I find this `if` condition very hard to read. Maybe store the values in appropriately named variables first?

File: compiler/rustc_infer/src/infer/error_reporting/mod.rs [hunk 9]
```diff
@@ -2187,11 +2190,63 @@ impl<'tcx> TypeErrCtxt<'_, 'tcx> {
...
+                        self.tcx.def_span(def_id).shrink_to_lo(),
+                        format!("{new_lt}, "),
+                    )));
+                } else {
+                    add_lt_suggs
+                        .push(Some((ast_generics.span.shrink_to_hi(), format!("<{new_lt}>"))));
+                }
+            }
+        } else {
+            if let Some(def_id) = generics.params.first().and_then(|param| param.def_id.as_local())
```
Comment (oli-obk) [inline compiler/rustc_infer/src/infer/error_reporting/mod.rs:2213]: This could be two nested `if let` or something like 

```suggestion
            if let [param, ..] = generics.params && let Some(def_id) = param.def_id.as_local()
```

File: compiler/rustc_infer/src/infer/error_reporting/mod.rs (hunk 8 above)
Comment (yanchen4791) [reply compiler/rustc_infer/src/infer/error_reporting/mod.rs]: Introduced `named_lifetime_exist` variable.

File: compiler/rustc_infer/src/infer/error_reporting/mod.rs (hunk 9 above)
Comment (yanchen4791) [reply compiler/rustc_infer/src/infer/error_reporting/mod.rs]: Changed.

**Comment by dtolnay** [comment]
Rebased to fix conflict with #106458, since this was showing not mergeable in bors.
https://bors.rust-lang.org/queue/rust
@bors r=oli-obk
