### PR TITLE
std: fix doctest and explain for `as_slices` and `as_mut_slices` in `VecDeque`

### LINKED ISSUE #141217: VecDeque documentation for as_slices misleads newbies.
### Location

https://doc.rust-lang.org/std/collections/struct.VecDeque.html#method.as_slices

### Summary

`VecDeque` documentation for [as_slices](https://doc.rust-lang.org/std/collections/struct.VecDeque.html#method.as_slices) method includes misleading test. It does few `push`'es and the asserts a particular shape of deque via `assert_eq!`.

This may mislead people and make them believe there are some guarantees about what particular slices are used for a given deque.

Instead we should add a line that says that particular split of elements between slices is not guaranteed and replace example with something like this:
```
let mut deque = VecDeque::new();

deque.push_back(0);
deque.push_back(1);
deque.push_back(2);

let slices = deque.as_slices();
assert!(slices.0.iter().chain(slices.1.iter()).eq([0, 1, 2].iter()));

deque.push_front(10);
deque.push_front(9);

let slices = deque.as_slices();
assert!(slices.0.iter().chain(slices.1.iter()).eq([9, 10, 0, 1, 2].iter()));
```

That way is would be clear that while content of two returned slices is guaranteed – but particular shape of split between them is not guaranteed.

### PR DESCRIPTION
**Pull request by xizheyin**
Fixes #141217

r? libs

### CODE REVIEW

**Comment by VorfeedCanal** [comment]
https://doc.rust-lang.org/std/collections/struct.VecDeque.html#method.as_mut_slices

as_mut_slices have the same issue, should it be fixed, too? It's more complicates there because example directly changes slices… which can lead to different outcome or even crash, if internal algorithm of `VecDec` would change.

**Comment by xizheyin** [comment]
In the changes, I also fixed the doc of as_mut_slice,but I typo in the pr title. lol

File: library/alloc/src/collections/vec_deque/mod.rs [hunk 1]
```diff
@@ -1313,6 +1313,9 @@ impl<T, A: Allocator> VecDeque<T, A> {
     /// If [`make_contiguous`] was previously called, all elements of the
     /// deque will be in the first slice and the second slice will be empty.
     ///
+    /// Note that the particular split point between the slices is not guaranteed
+    /// and may change based on internal implementation details.
+    ///
```
Comment (tgross35) [inline library/alloc/src/collections/vec_deque/mod.rs:1318]: I think the addition could be a part of the previous paragraph since it's talking about the same thing. E.g.

> If [`make_contiguous`] was previously called ... and the second slice will be empty. Otherwise, the exact split point depends on implementation details and is not guaranteed.

File: library/alloc/src/collections/vec_deque/mod.rs [hunk 2]
```diff
@@ -1326,12 +1329,14 @@ impl<T, A: Allocator> VecDeque<T, A> {
...
-    /// assert_eq!(deque.as_slices(), (&[0, 1, 2][..], &[][..]));
+    /// let slices = deque.as_slices();
+    /// assert!(slices.0.iter().chain(slices.1.iter()).eq([0, 1, 2].iter()));
     ///
     /// deque.push_front(10);
     /// deque.push_front(9);
     ///
-    /// assert_eq!(deque.as_slices(), (&[9, 10][..], &[0, 1, 2][..]));
+    /// let slices = deque.as_slices();
+    /// assert!(slices.0.iter().chain(slices.1.iter()).eq([9, 10, 0, 1, 2].iter()));
```
Comment (tgross35) [inline library/alloc/src/collections/vec_deque/mod.rs:1339]: This is a good example, but the iterators adapters might be bit difficult for newcomers to read. Maybe something like this?

```rust
deque.push_back(0);
deque.push_back(1);
deque.push_back(2);

let expected = [0, 1, 2];
let (front, back) = deque.as_slices();
assert_eq!(&expected[..front.len()], front);
assert_eq!(&expected[front.len()..], back);

deque.push_front(10);
deque.push_front(9);

let expected = [9, 10, 0, 1, 2];
let (front, back) = deque.as_slices();
assert_eq!(&expected[..front.len()], front);
assert_eq!(&expected[front.len()..], back);
```

File: library/alloc/src/collections/vec_deque/mod.rs [hunk 3]
```diff
@@ -1357,15 +1365,20 @@ impl<T, A: Allocator> VecDeque<T, A> {
...
-    /// deque.as_mut_slices().0[0] = 42;
-    /// deque.as_mut_slices().1[0] = 24;
-    /// assert_eq!(deque.as_slices(), (&[42, 10][..], &[24, 1][..]));
+    /// if !front.is_empty() {
+    ///     front[0] = 5;
+    ///     assert_eq!(deque[0], 5);
+    /// } else {
+    ///     back[back.len() - 1] = 5;
+    ///     assert_eq!(deque[deque.len() - 1], 5);
+    /// }
```
Comment (tgross35) [inline library/alloc/src/collections/vec_deque/mod.rs:1381]: Similarly, it may be a bit cleaner to `if` on the indexing and just assert the final result:

```rust
deque.push_back(0);
deque.push_back(1);

deque.push_front(10);
deque.push_front(9);

// Since the split point is not guaranteed, we may need to update
// either slice.
let mut update_nth = |index: usize, val: u32| {
    let (front, back) = deque.as_mut_slices();
    if index > front.len() - 1 {
        back[index - front.len()] = val;
    } else {
        front[index] = val;
    }
};

update_nth(0, 42);
update_nth(2, 24);

let v: Vec<_> = deque.into();
assert_eq!(v, [42, 10, 24, 1]);
```

**Comment by xizheyin** [comment]
Lone time no see. Thanks for your suggestion, I modified the code as you suggested. I have a little concern that `closure` in the example of `as_mut_slices` will be difficult to understand for new comers (I'm not sure if the closure is a required knowledge for new comers).

**Review by tgross35 — APPROVED** [review]
Thanks for the updates, the changes lgtm.

> I have a little concern that closure in the example of as_mut_slices will be difficult to understand for new comers (I'm not sure if the closure is a required knowledge for new comers).

I think they are usually introduced pretty early, but it doesn't have to be a closure. If you prefer, it can be a `fn updat_nth(deque: &mut VecDeque<u32>, index: usize, val: u32)`.

Please squash then r=me with or without changing to a function.

**Comment by xizheyin** [comment]
Oh, I does not have permission to merge it. @tgross35

**Comment by tgross35** [comment]
Thanks!

@bors r+ rollup
