### PR TITLE
fix `extern "aapcs" fn`

### LINKED ISSUE #37810: `aapcs` calling convention isn't passed to LLVM
As @TimNN pointed out currently the compiler does

>  `Aapcs => llvm::CCallConv,`

which happens to work on arm soft float because they are the same but on hard float they are not the same.

While we are at we should add support for `aapcs-vfp` too.

cc @japaric

### PR DESCRIPTION
**Pull request by japaric**
to actually use the AAPCS calling convention

closes #37810

This is technically a [breaking-change] because it changes the ABI of
`extern "aapcs"` functions that (a) involve `f32`/`f64` arguments/return
values and (b) are compiled for arm-eabihf targets from
"aapcs-vfp" (wrong) to "aapcs" (correct).

Appendix:

What these ABIs mean?

- In the "aapcs-vfp" ABI or "hard float" calling convention: Floating
point values are passed/returned through FPU registers (s0, s1, d0, etc.)

- Whereas, in the "aapcs" ABI or "soft float" calling convention:
Floating point values are passed/returned through general purpose
registers (r0, r1, etc.)

Mixing these ABIs can cause problems if the caller assumes that the
routine is using one of these ABIs but it's actually using the other
one.

---

r? @alexcrichton We are going this `extern "aapcs" fn` thing to implement some intrinsics (floatundidf) for the eabihf targets in order to comply with LLVM's calling convention of intrinsics.

Oh, and the value of the enum came from [here](http://llvm.org/docs/doxygen/html/namespacellvm_1_1CallingConv.html).

cc @TimNN @parched

### CODE REVIEW

File: src/librustc_trans/abi.rs [hunk 1]
```diff
@@ -274,10 +274,10 @@ impl FnType {
             C => llvm::CCallConv,
             Win64 => llvm::X86_64_Win64,
             SysV64 => llvm::X86_64_SysV,
+            Aapcs => llvm::AapcsCallConv,
```
Comment (parched) [inline src/librustc_trans/abi.rs]: this doesn't match `ffi.rs` it's missing `Arm`

**Review by parched — CHANGES_REQUESTED** [review]

**Review by parched — APPROVED** [review]

**Comment by japaric** [comment]
It works:

``` rust
#[no_mangle]
pub extern "aapcs" fn foo(x: f64) -> f64 {
    x
}

#[no_mangle]
pub extern "C" fn bar(x: f64) -> f64 {
    x
}
```

``` asm
00000000 <foo>:
   0:   e24dd008        sub     sp, sp, #8
   4:   ec410b10        vmov    d0, r0, r1
   8:   ed8d0b00        vstr    d0, [sp]
   c:   eaffffff        b       10 <foo+0x10>
  10:   ed9d0b00        vldr    d0, [sp]
  14:   ec510b10        vmov    r0, r1, d0
  18:   e28dd008        add     sp, sp, #8
  1c:   e12fff1e        bx      lr

Disassembly of section .text.bar:

00000000 <bar>:
   0:   e24dd008        sub     sp, sp, #8
   4:   ed8d0b00        vstr    d0, [sp]
   8:   eaffffff        b       c <bar+0xc>
   c:   ed9d0b00        vldr    d0, [sp]
  10:   e28dd008        add     sp, sp, #8
  14:   e12fff1e        bx      lr
```

**Comment by TimNN** [comment]
Maybe we should add a note about this (`aapcs` is now always soft float) to the `aapcs` entry in [`reference.md`](https://github.com/rust-lang/rust/blob/master/src/doc/reference.md)?

I'm not sure about the exact policy here, however technically this is a breaking change so should probably tagged as such (`[breaking-change]`).

**Comment by alexcrichton** [comment]
Strictly speaking yeah it's a breaking change but in practice I imagine this will fix more code than it breaks (if it breaks anything...).

@japaric want to edit the commit message and I'll r+?

also cc @rust-lang/compiler, just to be aware

**Comment by japaric** [comment]
> want to edit the commit message and I'll r+?

Done.
