### PR TITLE
rustc: Stabilize options for pipelined compilation

### LINKED ISSUE #60419: Tracking issue for stable `-C emit-artifact-notifications` rustc flag
First added in https://github.com/rust-lang/rust/pull/60006 the `-Z emit-directives` flag is currently intended to be paired with the `--error-format=json` flag. The `emit-directives` flag indicates that the compiler will emit a JSON directive for various things it does, currently only for when an rmeta metadata file is produced.

This issue is intended to track stabilizing this flag! The main use case for this is ["pipelined compilation"](https://github.com/rust-lang/rust/issues/58465) which shows promise for accelerating Cargo's compile of multi-crate graphs.

Current known issues with this flag:

* [ ] It's unclear how Cargo will handle its own `--message-format short` flag with this. Cargo will want to switch to `-Z emit-directives` by default but `--message-format short` in Cargo translates to `--error-format short` in rustc, which means Cargo can't simultaneously get a directive JSON plus a short error format
* [ ] What should the stable form of this flag be called?
* [ ] What should the structure of the JSON directive be? Currently it only gives a path to the artifact emitted, but should the `--emit` kind of that artifact also be emitted?

cc @nnethercote

### LINKED ISSUE #60987: Tracking issue for unstable `--json-rendered` flag
This issue is intended to be a tracking issue for the `--json-rendered` flag implemented in https://github.com/rust-lang/rust/pull/59128. The `--json-rendered` flag can either take `plain` or `termcolor`, and affects whether ANSI color codes are embedded into the `rendered` field of JSON diagnostics. 

Known issues with this:

* [ ] flag not supported in rustdoc yet

Future features:

* [ ] Html output (discussion: https://github.com/rust-lang/rust/pull/59128#discussion_r265675833)
* [ ] Short output (equal to `--error-format=short`)

cc @oli-obk, original author of the feature

### LINKED ISSUE #60988: Tracking issue for stabilizing "pipelined compilation"
This issue is intended to be an overall tracking issue for stabilizing the recently implemented feature of "pipelined compilation". This tracking issue spans both Cargo and rustc, as support currently lives in both. It also builds on top of a number of other tracking issues, since they're unstable features used to implement pipelined compilation!

For a bit of background, pipelined compilation has an [initial set of notes about its implementation](https://github.com/rust-lang/compiler-team/blob/master/working-groups/pipelining/NOTES.md) and initially had these tracking issues:

* [x] https://github.com/rust-lang/cargo/issues/6660
* [x] https://github.com/rust-lang/rust/issues/58465

Currently today everything is implemented and available in nightly rustc. There is a [thread on internals](https://internals.rust-lang.org/t/evaluating-pipelined-rustc-compilation/10199) which is tasked with gaining user experience about pipelining and see the performance impact. A [collation of these measurements](https://docs.google.com/spreadsheets/d/1CU7o3IocPtNAUevvrPsTI77z_AexsRloUgiusiXJWtg/edit#gid=0) is quite promising and I feel personally is convincing enough to push on stabilizing all the sub-features!

Known blockers for stabilization:

* [ ] [`-Z emit-artifact-notifications`](https://github.com/rust-lang/rust/issues/60419) - this is how Cargo learns the moment metadata is ready.
* [ ] [`--json-rendered`](https://github.com/rust-lang/rust/issues/60987) - this is how Cargo continues to provide pretty error messages.
* [ ] There is no way to combine `--message-format=short` in Cargo with pipelining. The compiler currently has `--error-format=json|short|human`, but for this feature in Cargo we'll need something like `--error-format=short-json` or something like that. Basically some way to request that the `rendered` field in the JSON diagnostic is a "short message", not the long one.
* [x] Cargo pipelining is known to break with `sccache`, this should be investigated and fixed one way or another. (fixed in https://github.com/mozilla/sccache/pull/441)
* [x] Pipelining fails with the RLS due to multiple `--error-format` flags (fixed in https://github.com/rust-lang/rust/pull/62176)

Possible future work:

* Should we game out what a "fully pipelined" story might look like? What if rustc blocked waiting for Cargo to tell it to proceed into the linking phase?

### PR DESCRIPTION
**Pull request by alexcrichton**
This commit stabilizes options in the compiler necessary for Cargo to
enable "pipelined compilation" by default. The concept of pipelined
compilation, how it's implemented, and what it means for rustc are
documented in #60988. This PR is coupled with a PR against Cargo
(rust-lang/cargo#7143) which updates Cargo's support for pipelined
compliation to rustc, and also enables support by default in Cargo.
(note that the Cargo PR cannot land until this one against rustc lands).

The technical changes performed here were to stabilize the functionality
proposed in #60419 and #60987, the underlying pieces to enable pipelined
compilation support in Cargo. The issues have had some discussion during
stabilization, but the newly stabilized surface area here is:

* A new `--json` flag was added to the compiler.
* The `--json` flag can be passed multiple times.
* The value of the `--json` flag is a comma-separated list of
  directives.
* The `--json` flag cannot be combined with `--color`
* The `--json` flag must be combined with `--error-format=json`
* The acceptable list of directives to `--json` are:
  * `diagnostic-short` - the `rendered` field of diagnostics will have a
    "short" rendering matching `--error-format=short`
  * `diagnostic-rendered-ansi` - the `rendered` field of diagnostics
    will be colorized with ansi color codes embedded in the string field
  * `artifacts` - JSON blobs will be emitted for artifacts being emitted
    by the compiler

The unstable `-Z emit-artifact-notifications` and `--json-rendered`
flags have also been removed during this commit as well.

Closes #60419
Closes #60987
Closes #60988

### CODE REVIEW

**Comment by alexcrichton** [comment]
It's also worth pointing out that the two tracking issues (https://github.com/rust-lang/rust/issues/60419 and https://github.com/rust-lang/rust/issues/60987) are not done with FCP, so this shouldn't be merged until they're done. I hoped to get this up early though to start feedback sooner.

**Comment by jsgf** [comment]
Are `diagnostic-short` and `diagnostic-rendered-ansi` exclusive?

File: src/bootstrap/test.rs [hunk 1]
```diff
@@ -229,6 +229,9 @@ impl Step for Cargo {
         cargo.env("CFG_DISABLE_CROSS_TESTS", "1");
         // Disable a test that has issues with mingw.
         cargo.env("CARGO_TEST_DISABLE_GIT_CLI", "1");
+        // Forcibly disable tests using nightly features since any changes to
+        // those features won't be able to land.
+        cargo.env("CARGO_TEST_DIABLE_NIGHTLY", "1");
```
Comment (drrlvn) [inline src/bootstrap/test.rs]: I think this is a typo: `CARGO_TEST_DIABLE_NIGHTLY` should be `CARGO_TEST_DISABLE_NIGHTLY` (missing 's' in "disable").

**Comment by eddyb** [comment]
After mentioning my preference for "just adding to the JSON format without an opt-in", I have to say that I like this design! Using `-J` instead of `--json` might also be interesting, but that is likely pushing it too far.

**Comment by alexcrichton** [comment]
@jsgf no they can be combined and both affect how the `rendered` field turns up.

**Comment by ehuss** [comment]
Since this makes the `rendered` field either "short" or "human", I just want to bring up the [cache-messages](https://github.com/rust-lang/cargo/issues/6986) feature again.  I'm still a little concerned about the [issues I raised earlier](https://github.com/rust-lang/rust/issues/60987#issuecomment-502787164).  When swapping between formats, the cache may replay the wrong format.

Does the following proposal sound reasonable?  I think the best option is where cargo and rustc share a rendering library. However, since it will likely be a very long time before that is done, perhaps we can plan to stabilize cache-messages with limited "short" support.  It would cache whatever format was originally requested (human or short).  Then when replaying, it would replay whatever was cached.  This might be a little confusing if the user is switching between formats, but I suspect this should be extremely rare if ever happens.

I'm happy with that plan, I just want to confirm that it sounds reasonable.

**Comment by Centril** [comment]
@alexcrichton When adding `relnotes`, please remember to also add the appropriate milestone (1.38 in this case). :)

**Comment by alexcrichton** [comment]
@ehuss oh sorry to clarify I haven't forgotten about that I just figured that it wasn't something we were going to solve right out the gate (or would rather require further changes to the compiler to fix). 

I don't think what you mention is entirely unreasonable since switching between formats is likely rare, but in some sense rustc/cargo share at least part of "rendering library" by agreeing on what ansi color codes are. That still requires rustc to give Cargo exact text though which is a bit of a bummer.

In any case though I think that this should at least be forwards compatible with a scheme where cargo/rustc agree on a short rendering scheme and Cargo can replay both messages given one invocation of rustc, and otherwise I just wanted to be sure to not couple the stabilizations too closely.

**Comment by alexcrichton** [comment]
I suspect this may be outside of @estebank's wheelhouse as well, so I'll otherwise do...

r? @eddyb

**Comment by alexcrichton** [comment]
Gonna send a ping to @rust-lang/compiler for this as well, it'd be great to get this in for the 1.38 release and it will take some time to land this, land the subsequent Cargo support, and then finally land the Cargo update in rust-lang/rust.

**Comment by alexcrichton** [comment]
Thanks @oli-obk!

**Comment by Arnavion** [comment]
@alexcrichton I guess nightly-2019-07-30 got released without the cargo change, as will future nightlies until cargo is updated? Right now compiling anything with `pipelining = true` in cargo config fails with `error: Unrecognized option: 'json-rendered'`. I guess we have to stop using pipelining until the cargo update is pulled in?

**Comment by alexcrichton** [comment]
That is correct, yes. Pipelining was always a nightly-only feature and this is the breakage that entails. The Cargo update, also mentioned in the description of this PR, is at https://github.com/rust-lang/cargo/pull/7143.

**Comment by Arnavion** [comment]
Cool. Thanks for confirming.
