### PR TITLE
Remove memoization leftovers from constant evaluation machine

### LINKED ISSUE #79667: CTFE: remove memoization leftovers
Since https://github.com/rust-lang/rust/pull/79594, memoization of argumentless functions is restricted to intrinsics, because other functions could perform heap allocations and thus memoization would be incorrect.

I doubt we have any argumentless intrinsic that is expensive enough that memoization is worth it, so I propose we remove the leftovers of that infrastructure.

Cc @rust-lang/wg-const-eval

### PR DESCRIPTION
**Pull request by dvtkrlbs**
Closes #79667

### CODE REVIEW

File: compiler/rustc_mir/src/const_eval/machine.rs [hunk 1]
```diff
@@ -17,60 +15,13 @@ use rustc_span::symbol::{sym, Symbol};
...
-
-        let dest = match ret {
-            Some((dest, _)) => dest,
-            // Don't memoize diverging function calls.
-            None => return Ok(false),
-        };
-
-        let gid = GlobalId { instance, promoted: None };
-
-        let place = self.eval_to_allocation(gid)?;
```
Comment (RalfJung) [inline compiler/rustc_mir/src/const_eval/machine.rs:65]: @oli-obk is there any further cleanup possible due to this? Looks like The const-eval queries support passing in the `Instance` of an argumentless const-fn, and then return the result. I feel like taht would need some special handling *somewhere* and I think we should stop doing that.

Comment (RalfJung) [reply compiler/rustc_mir/src/const_eval/machine.rs:65]: Judging from [the PR that added this](https://github.com/rust-lang/rust/pull/66294/files), 
* `eval_body_using_ecx` had an assertion `assert!(body.arg_count == 0);`. We should get that back... but also it's not enough! Even argumentless functions can do allocations and thus should not be allowed as the subject of a query.
* The doc comment of `GlobalId` needs updating to no longer mention "A const fn where all arguments (if any) are zero-sized types".

Comment (oli-obk) [reply compiler/rustc_mir/src/const_eval/machine.rs:65]: >     * `eval_body_using_ecx` had an assertion `assert!(body.arg_count == 0);`. We should get that back... but also it's not enough! Even argumentless functions can do allocations and thus should not be allowed as the subject of a query.

I think the right way to specify that assertion is

```rust
assert!(promoted.is_some() || matches!(tcx.hir().body_const_context(def_id), Some(ConstContext::Const | ConstContext::Static(_))));
```

Which makes sure that we really only allow promoteds, constants or statics.

Comment (dvtkrlbs) [reply compiler/rustc_mir/src/const_eval/machine.rs:65]:
```rust
assert!(cid.promoted.is_some() || matches!(ecx.tcx.hir().body_const_context(def_id), Some(ConstContext::Const | ConstContext::Static(_))));
```
like this in the `eval_body_using_ecx` right after first debug output ?

Comment (oli-obk) [reply compiler/rustc_mir/src/const_eval/machine.rs:65]: Yes, that is the right place.

File: compiler/rustc_mir/src/const_eval/eval_queries.rs [hunk 2]
```diff
@@ -30,6 +30,13 @@ fn eval_body_using_ecx<'mir, 'tcx>(
     body: &'mir mir::Body<'tcx>,
 ) -> InterpResult<'tcx, MPlaceTy<'tcx>> {
     debug!("eval_body_using_ecx: {:?}, {:?}", cid, ecx.param_env);
+    assert!(
+        cid.promoted.is_some()
+            || matches!(
+                ecx.tcx.hir().body_const_context(def_id),
+                Some(ConstContext::Const | ConstContext::Static(_))
```
Comment (oli-obk) [inline compiler/rustc_mir/src/const_eval/eval_queries.rs:37]: you'll need to add imports for `ConstContext`, it's in `rustc_hir` I believe.

You also need to use `cid.instance.def_id()` instead of just `def_id`, I didn't realize we don't have a variable for the `DefId` anymore.

Comment (dvtkrlbs) [reply compiler/rustc_mir/src/const_eval/eval_queries.rs:37]: oh i completely forgot running ./x.py check before pushing again :D. thank you

Comment (RalfJung) [reply compiler/rustc_mir/src/const_eval/eval_queries.rs:37]: There's also an assertion below that you can drop (the "Assert all args" part).

File: compiler/rustc_mir/src/const_eval/eval_queries.rs [hunk 3]
```diff
@@ -30,6 +30,13 @@ fn eval_body_using_ecx<'mir, 'tcx>(
     body: &'mir mir::Body<'tcx>,
 ) -> InterpResult<'tcx, MPlaceTy<'tcx>> {
     debug!("eval_body_using_ecx: {:?}, {:?}", cid, ecx.param_env);
+    assert!(
+        cid.promoted.is_some()
+            || matches!(
+                ecx.tcx.hir().body_const_context(def_id),
```
Comment (RalfJung) [inline compiler/rustc_mir/src/const_eval/eval_queries.rs:36]: If you move this down a bit you can use the `tcx` variable.

File: compiler/rustc_mir/src/const_eval/eval_queries.rs (hunk 2 above)
Comment (dvtkrlbs) [reply compiler/rustc_mir/src/const_eval/eval_queries.rs:37]: also `body_const_context` expects an `LocalDefId` instead of a `DefId`

Comment (oli-obk) [reply compiler/rustc_mir/src/const_eval/eval_queries.rs:37]: ah yes, but this can only ever be a local def id, so you can run `.expect_local()` on it. If It's not local, then we screwed up the query system :laughing:

Comment (dvtkrlbs) [reply compiler/rustc_mir/src/const_eval/eval_queries.rs:37]: Oh this is a LocalId from `rustc_span`. I thought it was from `rustc_mir` and looking at the docs for that.

Comment (dvtkrlbs) [reply compiler/rustc_mir/src/const_eval/eval_queries.rs:37]: > There's also an assertion below that you can drop (the "Assert all args" part).
i did not understand what you mean? Do you mean i can drop `cid.promoted.is_some()` part?

Comment (oli-obk) [reply compiler/rustc_mir/src/const_eval/eval_queries.rs:37]: No, further down. Ralf meant that you can remove the entire for loop at `// Assert all args (if any) are zero-sized types; `eval_body_using_ecx` doesn't`

Comment (oli-obk) [reply compiler/rustc_mir/src/const_eval/eval_queries.rs:37]: Since we now can't call this on functions at all, we won't ever have arguments, so there's no arguments to check. Thus the loop already does nothing

Comment (dvtkrlbs) [reply compiler/rustc_mir/src/const_eval/eval_queries.rs:38]: > ah yes, but this can only ever be a local def id, so you can run .expect_local() on it. If It's not local, then we screwed up the query system

i run the test suite and got a panic saying def_id isn't local 😕

File: compiler/rustc_mir/src/const_eval/eval_queries.rs [hunk 4]
```diff
@@ -31,6 +31,13 @@ fn eval_body_using_ecx<'mir, 'tcx>(
 ) -> InterpResult<'tcx, MPlaceTy<'tcx>> {
     debug!("eval_body_using_ecx: {:?}, {:?}", cid, ecx.param_env);
     let tcx = *ecx.tcx;
+    assert!(
+        cid.promoted.is_some()
+            || matches!(
+                ecx.tcx.hir().body_const_context(cid.instance.def_id().expect_local()),
+                Some(ConstContext::Const | ConstContext::Static(_))
```
Comment (oli-obk) [inline compiler/rustc_mir/src/const_eval/eval_queries.rs:38]: Ah... I forgot about associated constants. We evaluate associated constants from other crates, because they may depend on generic parameters, so we can't eagerly evaluate them in the crate that defines them. Thus, I have an alternative for you that works across crates.

```suggestion
                ecx.tcx.def_kind(cid.instance.def_id()),
                DefKind::Const | DefKind::Static | DefKind::ConstParam | DefKind::AnonConst | DefKInd::AssocConst
```

I am not sure if that list should also contain `Ctor` or `Variant`, but you'll notice by the fact that the assertion is failing whether you need either.

**Comment by oli-obk** [comment]
@bors r+

Thanks!

**Comment by dvtkrlbs** [comment]
Does this mean i need rebase ?
