### PR TITLE
resolve error when attempting to link a universal library on macOS

### LINKED ISSUE #55235: Cannot link to Apple universal (fat) libraries
I have started modifying a few Rust "-sys" crates to point to some prebuilt C libraries that I currently share between my C and Rust code. For macOS and iOS, my prebuilt libraries are merged into universal libraries, with multiple architectures contained in the same .a static libraries.

For instance, when trying to link against a universal libcurl.a library for iOS, I get the following error:
failed to add native library /opt/wayk/sdk/iOS/curl/lib/libcurl.a: File too small to be an archive

The only other mention of such an issue is https://github.com/rust-lang/rust/issues/50220 but it was meant to fix an issue with compiling Rust, not adding proper support for linking to universal binaries from Rust crates.

For macOS, I could "fix" the issue because we have recently deprecated support for i386 in our prebuilt libraries, and managed to make single-arch x86_64 libraries. Only non-universal binaries work, a universal binary with a single architecture won't work. I had to modify my scripts to avoid calling lipo to merge multiple libraries if there was only one architecture to "merge" and end up with non-universal binaries.

One possible workaround would be to process libraries to be linked such that "lipo -thin" is called to extract single-arch non-universal libraries to a temporary location and then pass those libraries to the linker. It may not be the cleanest patch, but it could work well without much changes.

The exact line throwing the error can be found here:
https://github.com/rust-lang/llvm/blob/caddcd9b9dc9479a20908d93c3e47c49b021379e/lib/Object/Archive.cpp#L554

For reference, I took a screenshot of the first few bytes of a thin library and a fat library. The macOS thin library can be seen on the left with the magic number "CAFEBABE". The iOS fat library can be seen on the right the with magic string "`!<arch>`". The code throwing the error checks for the "`!<arch>`" magic string, so the first step to try to add code specific to universal binaries would be to handle files with the "CAFEBABE" magic number differently.

libcurl_fat_thin

The relevant documentation for the universal binary format can be found here:
http://math-atlas.sourceforge.net/devel/assembly/MachORuntime.pdf#//apple_ref/doc/uid/20001298/TPXREF130

### PR DESCRIPTION
**Pull request by alex**
Previously attempting to link universal libraries into libraries (but not binaries) would produce an error that "File too small to be an archive". This works around this by invoking `lipo -thin` to extract a library for the target platform when passed a univeral library.

Fixes #55235

It's worth acknowledging that this implementation is kind of a horrible hack. Unfortunately I don't know how to do anything better, hopefully this PR will be a jumping off point.

### CODE REVIEW

**Comment by alex** [comment]
This also deseperately needs a test. I've currently just manually validated this against a local project. Any pointer to where in tree would be appropriate for a test would be appreciated!

File: compiler/rustc_codegen_llvm/src/back/archive.rs [hunk 1]
```diff
@@ -65,15 +66,50 @@ impl<'a> ArchiveBuilder<'a> for LlvmArchiveBuilder<'a> {
...
+            let mut f = fs::File::open(&archive)?;
+            let mut prefix = [0; 4];
+            f.read(&mut prefix)?;
+            if prefix == *b"\xCA\xFE\xBA\xBE" {
+                let (_, extracted_path) = tempfile::Builder::new()
+                    .suffix(archive.as_path().file_name().unwrap())
+                    .tempfile()?
+                    .keep()
+                    .unwrap();
+                let result = std::process::Command::new("lipo")
```
Comment (bjorn3) [inline compiler/rustc_codegen_llvm/src/back/archive.rs:80]: I believe the object crate supports reading fat libraries too. Once https://github.com/rust-lang/rust/pull/97485 lands that would allow to avoid writing a temporary file.

**Comment by bjorn3** [comment]
> This also deseperately needs a test. I've currently just manually validated this against a local project. Any pointer to where in tree would be appropriate for a test would be appreciated!

It should probably be a run-make test. Those can be found at `src/test/run-make`.

File: compiler/rustc_codegen_llvm/src/back/archive.rs (hunk 1 above)
Comment (alex) [reply compiler/rustc_codegen_llvm/src/back/archive.rs:80]: Fantastic. That's way less horrifying :-) And it looks like it may in fact support these out of the box! Looking forward to that.

Comment (bjorn3) [reply compiler/rustc_codegen_llvm/src/back/archive.rs:80]: I think some extra code will still be necessary for handling fat libraries. Am I right in that fat libraries use the same wrapper format that fat binaries do except that it wraps an archive instead of a Mach-O binary? There would still need to be some extra code to extract the right archive from the fat library using `object::macho::FatHeader::parse_arch32/64`.

Comment (alex) [reply compiler/rustc_codegen_llvm/src/back/archive.rs:80]: I know nothing about the on disk format (except the CAFEBABE prefix), but I suppose it makes sense that at least a little code will be required to extract sub-archive.

**Comment by bjorn3** [comment]
I'm going to re-assign. I don't have time to look at this for the next 2 weeks.

r? compiler

**Comment by alex** [comment]
Unless someone is eager to land in the current (somewhat hacky) form, my
expectation is that I'll rebase this work after your object PRs land.

בתאריך יום ג׳, 12 ביולי 2022, 12:04, מאת bjorn3 ***@***.***>:

**Comment by cjgillot** [comment]
Marking as blocked on https://github.com/rust-lang/rust/pull/98100 and re-assigning to @bjorn3 once they have time.
r? @bjorn3

**Comment by bjorn3** [comment]
It should be blocked on https://github.com/rust-lang/rust/pull/97485, not https://github.com/rust-lang/rust/pull/98100 I think. The former is for writing archives, while the later is for reading llvm bitcode from archives.

**Comment by alex** [comment]
Since https://github.com/rust-lang/rust/pull/97485 was taking longer than hoped, I ported this to use `object`, but not rely on that PR. I think that makes this reviewable now -- it still has the ugly tempfile usage, but no longer relies on shelling out to `lipo`.

**Review by bjorn3 — APPROVED** [review]
LGTM once parse_arch64 is also tried.

File: compiler/rustc_codegen_llvm/src/back/archive.rs [hunk 2]
```diff
@@ -53,21 +57,57 @@ fn llvm_machine_type(cpu: &str) -> LLVMMachineType {
...
+    sess: &Session,
+    archive_path: &Path,
+) -> io::Result<Option<PathBuf>> {
+    let archive_map = unsafe { Mmap::map(fs::File::open(&archive_path)?)? };
+    let target_arch = match sess.target.arch.as_ref() {
+        "aarch64" => object::Architecture::Aarch64,
+        "x86_64" => object::Architecture::X86_64,
+        _ => return Ok(None),
+    };
+    let archs = object::macho::FatHeader::parse_arch32(&*archive_map)
```
[the remark this answers is not in the document]
Comment (alex) [reply compiler/rustc_codegen_llvm/src/back/archive.rs]: Done! I've never actually found a 64-bit fat archive in the wild!

**Comment by alex** [comment]
I can't seem to find the actual problem that triggered all this in the logs. Halp? :-)

**Comment by bjorn3** [comment]
Uploading artifacts to S3 failed for several jobs. Likely spurious.

@bors retry
