### PR TITLE
Explicitly checking for or-pattern before test

### LINKED ISSUE #72680: "or-patterns should have already been handled" when using feature(or_patterns)
When using the `or_patterns` feature, attempting to match on a tuple creates a compiler panic.

The following code causes the panic.
```rust
#![feature(or_patterns)]

fn f(s: &str, num: usize) {
	match (s, num) {
		("", 0) | ("a" | "b", 1) => (),
		
		_ => ()
	}
}
```
(Also available at the [playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=3df1d388157056c52077d9265787c813))

This occurs both on the playground and on my local machine on a previous version (details below).

## Meta

Rust version from the playground:
> 1.45.0-nightly
> (2020-05-26 5239f5c57bb6eb9e8940)

Local version:
> rustc 1.45.0-nightly (a74d1862d 2020-05-14)
> binary: rustc
> commit-hash: a74d1862d4d87a56244958416fd05976c58ca1a8
> commit-date: 2020-05-14
> host: x86_64-pc-windows-msvc
> release: 1.45.0-nightly
> LLVM version: 9.0

Playground backtrace:
```
  Compiling playground v0.0.1 (/playground)
error: internal compiler error: src/librustc_mir_build/build/matches/test.rs:70: or-patterns should have already been handled

thread 'rustc' panicked at 'Box<Any>', src/librustc_errors/lib.rs:907:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.45.0-nightly (5239f5c57 2020-05-26) running on x86_64-unknown-linux-gnu

note: compiler flags: -C embed-bitcode=no -C codegen-units=1 -C debuginfo=2 --crate-type lib

note: some of the compiler flags provided by cargo are hidden

error: aborting due to previous error

error: could not compile `playground`.

To learn more, run the command again with --verbose.
```
Local backtrace:
```
error: internal compiler error: src\librustc_mir_build\build\matches\test.rs:70: or-patterns should have already been handled

thread 'rustc' panicked at 'Box<Any>', src\librustc_errors\lib.rs:907:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.45.0-nightly (a74d1862d 2020-05-14) running on x86_64-pc-windows-msvc

note: compiler flags: -C embed-bitcode=no -C debuginfo=2 -C incremental --crate-type cdylib

note: some of the compiler flags provided by cargo are hidden
```

EDIT: Added local machine backtrace too

### PR DESCRIPTION
**Pull request by mark-i-m**
Fixes https://github.com/rust-lang/rust/issues/72680

cc https://github.com/rust-lang/rust/issues/54883

r? @varkor

### CODE REVIEW

**Comment by mark-i-m** [comment]
I haven't tried to run these tests locally because it's too slow, so I will wait for CI...

**Comment by mark-i-m** [comment]
cc @matthewjasper

**Comment by mark-i-m** [comment]
Looks ready for review :)

File: compiler/rustc_mir_build/src/build/matches/test.rs [hunk 1]
```diff
@@ -671,6 +671,16 @@ impl<'a, 'tcx> Builder<'a, 'tcx> {
             (&TestKind::Range { .. }, _) => None,
 
             (&TestKind::Eq { .. } | &TestKind::Len { .. }, _) => {
+                // We do call `test()` below to see what kind of test `match_pair` would require.
+                // If it is the same test as `test`, then we can just use `test`.
```
Comment (varkor) [inline compiler/rustc_mir_build/src/build/matches/test.rs:675]: These sentences are hard to read. Maybe it would be clearer without them: if not, I think they ought to be tweaked (there are too many "test"s).

**Review by varkor — COMMENTED** [review]
It's been a while since I dealt with this code, so I'd rather @matthewjasper took a look.

File: src/test/ui/match/issue-72680.rs [hunk 2]
```diff
@@ -0,0 +1,65 @@
...
+#![feature(or_patterns)]
+
+fn main() {
+    assert_eq!(f("", 0), true);
+    assert_eq!(f("a", 1), true);
+    assert_eq!(f("b", 1), true);
+
+    assert_eq!(f("", 1), false);
+    assert_eq!(f("a", 0), false);
+    assert_eq!(f("b", 0), false);
```
Comment (WaffleLapkin) [inline src/test/ui/match/issue-72680.rs:12]: I think it would be clearer if written this way:
```rust
assert!(f("", 0));
assert!(f("a", 1));
assert!(f("b", 1));

assert!(!f("", 1)); // alternatively more explicit `.not()` may be used
assert!(!f("a", 0)); 
assert!(!f("b", 0));
```
(same for the `assert`s below)

File: compiler/rustc_mir_build/src/build/matches/test.rs (hunk 1 above)
Comment (mark-i-m) [reply compiler/rustc_mir_build/src/build/matches/test.rs]: Better now?

**Review by matthewjasper — COMMENTED** [review]
One style nit that would be nice to have fixed before this is merged

**Comment by mark-i-m** [comment]
@matthewjasper Nit addressed :) Good catch!
