### PR TITLE
Fix linking error when compiling for 32-bit watchOS

### LINKED ISSUE #130071: `armv7k-apple-watchos` fails to link
Building project using `armv7k-apple-watchos` should just work, but instead it fails to link to the `_Unwind_VRS_Get` and `_Unwind_VRS_Set` symbols.

```console
$ cargo new foo && cd foo && cargo +nightly build --target=armv7k-apple-watchos -Zbuild-std
// Or
$ ./x test --target=armv7k-apple-watchos
```

The exact error is:

```
  = note: clang: warning: argument unused during compilation: '-pie' [-Wunused-command-line-argument]
          ld: warning: CPU_SUBTYPE_ARM_ALL subtype is deprecated: /var/folders/0j/tk3sfgz540712zgqd1hrry0m0000gn/T/rustczhiAuB/symbols.o
          Undefined symbols for architecture armv7k:
            "__Unwind_VRS_Get", referenced from:
                unwind::libunwind::_Unwind_GetGR::h26feaf89fa048a08 in libunwind-839951f2536ba1be.rlib(unwind-839951f2536ba1be.unwind.e3a3afb176a39428-cgu.0.rcgu.o)
            "__Unwind_VRS_Set", referenced from:
                unwind::libunwind::_Unwind_SetGR::h82dc8386fcb66bbf in libunwind-839951f2536ba1be.rlib(unwind-839951f2536ba1be.unwind.e3a3afb176a39428-cgu.0.rcgu.o)
            "___gnu_unwind_frame", referenced from:
                std::sys::personality::gcc::rust_eh_personality::continue_unwind::hc8efd93df824e471 in libstd-ee4f137c874f1c8a.rlib(std-ee4f137c874f1c8a.std.ffd53844a8cf2cc0-cgu.12.rcgu.o)
          ld: symbol(s) not found for architecture armv7k
          clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

### Meta

`rustc +nightly --version --verbose`:
```
rustc 1.83.0-nightly (26b5599e4 2024-09-06)
binary: rustc
commit-hash: 26b5599e4d6ed2b45152c60493c1788c0a27533d
commit-date: 2024-09-06
host: aarch64-apple-darwin
release: 1.83.0-nightly
LLVM version: 19.1.0
```

This worked with `+nightly-2024-01-15`, I'll try to bisect it myself.

@rustbot label O-watchos

### PR DESCRIPTION
**Pull request by madsmtm**
In https://github.com/rust-lang/rust/pull/124494 (or https://github.com/rust-lang/rust/pull/124748), I mistakenly conflated "not SjLj" to mean "ARM EHABI", which isn't true, 32-bit watchOS uses a third unwinding method called "DWARF CFI".

So this PR is effectively a revert of https://github.com/rust-lang/rust/pull/124494, with a few more comments explaining what's going on.

Fixes https://github.com/rust-lang/rust/issues/130071.

r? Mark-Simulacrum (since you reviewed the original)

### CODE REVIEW

File: library/unwind/src/libunwind.rs [hunk 1]
```diff
@@ -33,10 +33,10 @@ pub const unwinder_private_data_size: usize = 2;
 #[cfg(all(target_arch = "x86_64", target_os = "windows"))]
 pub const unwinder_private_data_size: usize = 6;
 
-#[cfg(all(target_arch = "arm", not(all(target_vendor = "apple", not(target_os = "watchos")))))]
+#[cfg(all(target_arch = "arm", not(target_vendor = "apple")))]
 pub const unwinder_private_data_size: usize = 20;
 
-#[cfg(all(target_arch = "arm", all(target_vendor = "apple", not(target_os = "watchos"))))]
+#[cfg(all(target_arch = "arm", target_vendor = "apple"))]
 pub const unwinder_private_data_size: usize = 5;
```
Comment (madsmtm) [inline library/unwind/src/libunwind.rs:40]: I have verified that this is correct by compiling the following C code on different Apple platforms:
```c
#include <unwind.h>
int SIZE_OF_PRIVATE_DATA = (sizeof(_Unwind_Exception) - sizeof(uint64_t) - sizeof(void*)) / sizeof(void*);
```

File: library/std/src/sys/personality/dwarf/eh.rs [hunk 2]
```diff
@@ -54,10 +54,10 @@ pub enum EHAction {
     Terminate,
 }
 
-/// 32-bit Apple ARM uses SjLj exceptions, except for watchOS.
+/// 32-bit ARM Darwin platforms uses SjLj exceptions.
 ///
-/// I.e. iOS and tvOS, as those are the only Apple OSes that used 32-bit ARM
-/// devices.
+/// The exception is watchOS armv7k (specifically that subarchitecture), which
+/// instead uses DWARF CFI unwinding.
```
Comment (BlackHoleFox) [inline library/std/src/sys/personality/dwarf/eh.rs:60]: Perhaps in this first spot to make it easier to look for:
```suggestion
/// instead uses DWARF Call Frame Information (CFI) unwinding.
```
