### PR TITLE
Normalize projections under binders

### LINKED ISSUE #62529: ICE field: higher-rank trait bounds (HRTB) hit OutputTypeParameterMismatch in librustc/traits/codegen
I have seen many OutputTypeParameterMismatch ICEs  filed, so I decided to try to make a single representative issue for all of them.
 * Its possible that not all of these share the same root cause. But until I see a more fine grain way to categorize them, I'm going to at least try to track them in a single place.

#60070 

#57485

#53420 

#52812 

#50886 
 
#48112 

#42950

#33364 

https://github.com/rust-lang/rust/issues/30860#issuecomment-171075273

#29997

### LINKED ISSUE #70120: Internal compiler error when using associated type from higher ranked trait
Apologies if this is already reported somewhere; couldn't find it during a quick search.

Getting an internal compiler error for this code ([playground](https://play.rust-lang.org/?version=beta&mode=debug&edition=2018&gist=46bc4c30cb87325d092831d8cb2bf7a0)):

```rs
pub trait MyTrait<'a> {
    type Output: 'a;
    fn gimme_value(&self) -> Self::Output;
}

pub struct MyStruct;

impl<'a> MyTrait<'a> for MyStruct {
    type Output = &'a usize;
    fn gimme_value(&self) -> Self::Output {
        unimplemented!()
    }
}

fn meow<T, F>(t: T, f: F)
where
    T: for<'any> MyTrait<'any>,
    F: for<'any2> Fn(<T as MyTrait<'any2>>::Output),
{
    let v = t.gimme_value();
    f(v);
}

fn main() {
    let struc = MyStruct;
    meow(struc, |foo| {
        println!("{:?}", foo);
    })
}
```

The error reads:

```
error: internal compiler error: src/librustc_infer/traits/codegen/mod.rs:61: Encountered error `OutputTypeParameterMismatch(Binder(<[closure@src/main.rs:26:17: 28:6] as std::ops::Fn<(<MyStruct as MyTrait<'_>>::Output,)>>), Binder(<[closure@src/main.rs:26:17: 28:6] as std::ops::Fn<(&usize,)>>), Sorts(ExpectedFound { expected: &usize, found: <MyStruct as MyTrait<'_>>::Output }))` selecting `Binder(<[closure@src/main.rs:26:17: 28:6] as std::ops::Fn<(&usize,)>>)` during codegen
```

Tested in `1.42.0`, `1.43.0-beta.1`, and `1.44.0-nightly (2020-03-17 7ceebd98c6a15ae30e77)`

### LINKED ISSUE #70243: Rust compiler panic
The Rust compiler panicked with the following message. I’m not planning on taking the time to create a minimal repro, so you can immediately close if you’d like. Don’t know how useful just sharing a panic. message is.

```
error: internal compiler error: src/librustc/traits/codegen/mod.rs:57: Encountered error `OutputTypeParameterMismatch(Binder(<[closure@server/universe/schema/types/workspace.rs:66:30: 66:55] as std::ops::FnMut<(<graphql_prepare::prepare::PreparedSelection<model_district_raw::account::Table> as model_core::selection::Selection<'_, model_district_raw::account::Table>>::Data,)>>), Binder(<[closure@server/universe/schema/types/workspace.rs:66:30: 66:55] as std::ops::FnMut<(graphql_prepare::prepare::PreparedData<model_district_raw::account::Table>,)>>), Sorts(ExpectedFound { expected: graphql_prepare::prepare::PreparedData<model_district_raw::account::Table>, found: <graphql_prepare::prepare::PreparedSelection<model_district_raw::account::Table> as model_core::selection::Selection<'_, model_district_raw::account::Table>>::Data }))` selecting `Binder(<[closure@server/universe/schema/types/workspace.rs:66:30: 66:55] as std::ops::FnMut<(graphql_prepare::prepare::PreparedData<model_district_raw::account::Table>,)>>)` during codegen

thread 'rustc' panicked at 'Box<Any>', src/librustc_errors/lib.rs:873:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.42.0 (b8cedc004 2020-03-09) running on x86_64-apple-darwin
```

### LINKED ISSUE #76407: Associated type constraint fails, even if it implements requested trait
Associated type constraint fails, even if it implements requested trait. In the example below, requested trait is `Marker`, `u32` implements it, `<MyStruct as MyTrait>::Item<'a> == u32`, but `<MyStruct as MyTrait>::Item<'a>: Marker` does not pass. (Everything is ok with `<'a>` removed)

The code:

```rust
#![allow(incomplete_features)]
#![feature(generic_associated_types)]

trait Marker {}

impl Marker for u32 {}

trait MyTrait {
    type Item<'a>;
}

struct MyStruct;

impl MyTrait for MyStruct {
    type Item<'a> = u32;
}

fn ty_check<T>()
where
    T: MyTrait,
    for<'a> T::Item<'a>: Marker
{}

fn main() {
    ty_check::<MyStruct>();
}
```

### Meta

`rustc --version --verbose`:
```
rustc 1.48.0-nightly (cdc8f0606 2020-09-05)
binary: rustc
commit-hash: cdc8f0606d0f3c4f3866643382c8a5776d1bdaed
commit-date: 2020-09-05
host: x86_64-unknown-linux-gnu
release: 1.48.0-nightly
LLVM version: 11.0
```

### LINKED ISSUE #76826: ICE when combining GATs and HRTBs
The following code triggers an ICE.

### Code

```Rust
#![feature(generic_associated_types)]

pub trait Iter {
    type Item<'a> where Self: 'a;
    
    fn next<'a>(&'a mut self) -> Option<Self::Item<'a>>;
    
    fn for_each<F>(mut self, mut f: F)
        where Self: Sized, F: for<'a> FnMut(Self::Item<'a>)
    {
        while let Some(item) = self.next() {
            f(item);
        }
    }
}

pub struct Windows<T> {
    items: Vec<T>,
    start: usize,
    len: usize,
}

impl<T> Windows<T> {
    pub fn new(items: Vec<T>, len: usize) -> Self {
        Self { items, start: 0, len }
    }
}

impl<T> Iter for Windows<T> {
    type Item<'a> where T: 'a = &'a mut [T];
    
    fn next<'a>(&'a mut self) -> Option<Self::Item<'a>> {
        let slice = self.items.get_mut(self.start..self.start + self.len)?;
        self.start += 1;
        Some(slice)
    }
}

fn main() {
    Windows::new(vec![1, 2, 3, 4, 5], 3)
        .for_each(|slice| println!("{:?}", slice));
}
```

[Playground version](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=5fc1a17b6b474bca1e584071b06a4613)

This example can no doubt be minimised further, but it should be obvious what I'm attempting to do and why. This would be, I assume, a fairly common use-case for GATs and are likely to be essential if GATs are ever to be integrated into `Iterator`.

### Meta

`rustc --version --verbose`:
```
rustc 1.48.0-nightly (d006f5734 2020-08-28)
```

### Error output

```
error: internal compiler error: src/librustc_trait_selection/traits/codegen/mod.rs:75:17: Encountered error `OutputTypeParameterMismatch(Binder(<[closure@gats.rs:41:19: 41:50] as std::ops::FnMut<(<Windows<i32> as Iter>::Item<'_>,)>>), Binder(<[closure@gats.rs:41:19: 41:50] as std::ops::FnMut<(&mut [i32],)>>), Sorts(ExpectedFound { expected: &mut [i32], found: <Windows<i32> as Iter>::Item<'_> }))` selecting `Binder(<[closure@gats.rs:41:19: 41:50] as std::ops::FnMut<(&mut [i32],)>>)` during codegen

thread 'rustc' panicked at 'Box<Any>', src/librustc_errors/lib.rs:918:9
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
stack backtrace:
   0: std::panicking::begin_panic
   1: rustc_errors::HandlerInner::bug
   2: rustc_errors::Handler::bug
   3: rustc_middle::util::bug::opt_span_bug_fmt::{{closure}}
   4: rustc_middle::ty::context::tls::with_opt::{{closure}}
   5: rustc_middle::ty::context::tls::with_opt
   6: rustc_middle::util::bug::opt_span_bug_fmt
   7: rustc_middle::util::bug::bug_fmt
   8: rustc_infer::infer::InferCtxtBuilder::enter
   9: rustc_trait_selection::traits::codegen::codegen_fulfill_obligation
  10: rustc_middle::ty::query::<impl rustc_query_system::query::config::QueryAccessors<rustc_middle::ty::context::TyCtxt> for rustc_middle::ty::query::queries::codegen_fulfill_obligation>::compute
  11: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl
  12: rustc_data_structures::stack::ensure_sufficient_stack
  13: rustc_query_system::query::plumbing::get_query_impl
  14: rustc_ty::instance::inner_resolve_instance
  15: rustc_ty::instance::resolve_instance
  16: rustc_middle::ty::query::<impl rustc_query_system::query::config::QueryAccessors<rustc_middle::ty::context::TyCtxt> for rustc_middle::ty::query::queries::resolve_instance>::compute
  17: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl
  18: rustc_data_structures::stack::ensure_sufficient_stack
  19: rustc_query_system::query::plumbing::get_query_impl
  20: rustc_middle::ty::instance::Instance::resolve_opt_const_arg
  21: rustc_middle::ty::instance::Instance::resolve
  22: <rustc_mir::monomorphize::collector::MirNeighborCollector as rustc_middle::mir::visit::Visitor>::visit_terminator
  23: rustc_mir::monomorphize::collector::collect_neighbours
  24: rustc_mir::monomorphize::collector::collect_items_rec
  25: rustc_mir::monomorphize::collector::collect_items_rec
  26: rustc_session::utils::<impl rustc_session::session::Session>::time
  27: rustc_mir::monomorphize::collector::collect_crate_mono_items
  28: rustc_mir::monomorphize::partitioning::collect_and_partition_mono_items
  29: rustc_middle::ty::query::<impl rustc_query_system::query::config::QueryAccessors<rustc_middle::ty::context::TyCtxt> for rustc_middle::ty::query::queries::collect_and_partition_mono_items>::compute
  30: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl
  31: rustc_data_structures::stack::ensure_sufficient_stack
  32: rustc_query_system::query::plumbing::get_query_impl
  33: rustc_codegen_ssa::base::codegen_crate
  34: <rustc_codegen_llvm::LlvmCodegenBackend as rustc_codegen_ssa::traits::backend::CodegenBackend>::codegen_crate
  35: rustc_interface::passes::QueryContext::enter
  36: rustc_interface::queries::Queries::ongoing_codegen
  37: rustc_interface::queries::<impl rustc_interface::interface::Compiler>::enter
  38: rustc_span::with_source_map
  39: rustc_interface::interface::create_compiler_and_run
  40: scoped_tls::ScopedKey<T>::set
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.48.0-nightly (d006f5734 2020-08-28) running on x86_64-unknown-linux-gnu

query stack during panic:
#0 [codegen_fulfill_obligation] checking if `std::ops::FnMut` fulfills its obligations
#1 [resolve_instance] resolving instance `<[closure@gats.rs:41:19: 41:50] as std::ops::FnMut<(&mut [i32],)>>::call_mut`
#2 [collect_and_partition_mono_items] collect_and_partition_mono_items
end of query stack
error: aborting due to previous error; 1 warning emitted
```

</p>
</details>

Removing the final line (`.for_each(|slice| println!("{:?}", slice))`) prevents the ICE, implying that this is a codegen issue (as corroborated by the stack trace).

### LINKED ISSUE #87219: ICE: assertion failed: !ty.has_vars_bound_at_or_above() , glacier fixed/76826.rs with --emit=mir -Zpolymorphize=on
### Code
code from glacier  fixed/76826.rs
```Rust
#![feature(generic_associated_types)]

pub trait Iter {
    type Item<'a> where Self: 'a;

    fn next<'a>(&'a mut self) -> Option<Self::Item<'a>>;

    fn for_each<F>(mut self, mut f: F)
        where Self: Sized, F: for<'a> FnMut(Self::Item<'a>)
    {
        while let Some(item) = self.next() {
            f(item);
        }
    }
}

pub struct Windows<T> {
    items: Vec<T>,
    start: usize,
    len: usize,
}

impl<T> Windows<T> {
    pub fn new(items: Vec<T>, len: usize) -> Self {
        Self { items, start: 0, len }
    }
}

impl<T> Iter for Windows<T> {
    type Item<'a> where T: 'a = &'a mut [T];

    fn next<'a>(&'a mut self) -> Option<Self::Item<'a>> {
        let slice = self.items.get_mut(self.start..self.start + self.len)?;
        self.start += 1;
        Some(slice)
    }
}

fn main() {
    Windows::new(vec![1, 2, 3, 4, 5], 3)
        .for_each(|slice| println!("{:?}", slice));
}
```

### Meta

`rustc --version --verbose`:
```
rustc 1.55.0-nightly (74ef0c3e4 2021-07-16)
binary: rustc
commit-hash: 74ef0c3e404cc72c08b2d1e14506f90d9e877269
commit-date: 2021-07-16
host: x86_64-unknown-linux-gnu
release: 1.55.0-nightly
LLVM version: 12.0.1
```

### Error output
`rustc glacier/fixed/76826.rs --emit=mir -Zpolymorphize=on `
```
thread 'rustc' panicked at 'assertion failed: !ty.has_vars_bound_at_or_above(ty::DebruijnIndex::from_usize(self.universes.len()))', compiler/rustc_trait_selection/src/traits/query/normalize.rs:232:17
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.55.0-nightly (74ef0c3e4 2021-07-16) running on x86_64-unknown-linux-gnu

note: compiler flags: -Z polymorphize=on

query stack during panic:
#0 [normalize_generic_arg_after_erasing_regions] normalizing `std::option::Option<<Windows<T> as Iter>::Item<'_>>`
end of query stack
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
thread 'rustc' panicked at 'assertion failed: !ty.has_vars_bound_at_or_above(ty::DebruijnIndex::from_usize(self.universes.len()))', compiler/rustc_trait_selection/src/traits/query/normalize.rs:232:17
stack backtrace:
   0:     0x7f22a1f2af00 - std::backtrace_rs::backtrace::libunwind::trace::h0f5cd2ee8b0d7274
                               at /rustc/74ef0c3e404cc72c08b2d1e14506f90d9e877269/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
   1:     0x7f22a1f2af00 - std::backtrace_rs::backtrace::trace_unsynchronized::h06905b5aeda069a1
                               at /rustc/74ef0c3e404cc72c08b2d1e14506f90d9e877269/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7f22a1f2af00 - std::sys_common::backtrace::_print_fmt::h4fe4c7c875072f30
                               at /rustc/74ef0c3e404cc72c08b2d1e14506f90d9e877269/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x7f22a1f2af00 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hcc0746f004a9b7ef
                               at /rustc/74ef0c3e404cc72c08b2d1e14506f90d9e877269/library/std/src/sys_common/backtrace.rs:46:22
   4:     0x7f22a1f98cec - core::fmt::write::h9a6d9c74526a6c1b
                               at /rustc/74ef0c3e404cc72c08b2d1e14506f90d9e877269/library/core/src/fmt/mod.rs:1115:17
   5:     0x7f22a1f1c655 - std::io::Write::write_fmt::h23dab4cc9ce72ee2
                               at /rustc/74ef0c3e404cc72c08b2d1e14506f90d9e877269/library/std/src/io/mod.rs:1663:15
   6:     0x7f22a1f2ec1b - std::sys_common::backtrace::_print::h173dc702502d65d2
                               at /rustc/74ef0c3e404cc72c08b2d1e14506f90d9e877269/library/std/src/sys_common/backtrace.rs:49:5
   7:     0x7f22a1f2ec1b - std::sys_common::backtrace::print::h61bd27c4742ba817
                               at /rustc/74ef0c3e404cc72c08b2d1e14506f90d9e877269/library/std/src/sys_common/backtrace.rs:36:9
   8:     0x7f22a1f2ec1b - std::panicking::default_hook::{{closure}}::hcaae87f0495ae613
                               at /rustc/74ef0c3e404cc72c08b2d1e14506f90d9e877269/library/std/src/panicking.rs:208:50
   9:     0x7f22a1f2e6f1 - std::panicking::default_hook::h0538e728ee080db0
                               at /rustc/74ef0c3e404cc72c08b2d1e14506f90d9e877269/library/std/src/panicking.rs:225:9
  10:     0x7f22a27051c1 - rustc_driver::DEFAULT_HOOK::{{closure}}::{{closure}}::h432ae30fc20e6372
  11:     0x7f22a1f2f449 - std::panicking::rust_panic_with_hook::h3039e236b6ca482c
                               at /rustc/74ef0c3e404cc72c08b2d1e14506f90d9e877269/library/std/src/panicking.rs:626:17
  12:     0x7f22a1f2eed7 - std::panicking::begin_panic_handler::{{closure}}::h884fbab544ffd91c
                               at /rustc/74ef0c3e404cc72c08b2d1e14506f90d9e877269/library/std/src/panicking.rs:517:13
  13:     0x7f22a1f2b3fc - std::sys_common::backtrace::__rust_end_short_backtrace::hdaf2e18ba3d91210
                               at /rustc/74ef0c3e404cc72c08b2d1e14506f90d9e877269/library/std/src/sys_common/backtrace.rs:141:18
  14:     0x7f22a1f2ee69 - rust_begin_unwind
                               at /rustc/74ef0c3e404cc72c08b2d1e14506f90d9e877269/library/std/src/panicking.rs:515:5
  15:     0x7f22a1ef9e71 - core::panicking::panic_fmt::hcf5f6d96e1dd7099
                               at /rustc/74ef0c3e404cc72c08b2d1e14506f90d9e877269/library/core/src/panicking.rs:92:14
  16:     0x7f22a1ef9dbd - core::panicking::panic::hd695e3b1d0dd4ef4
                               at /rustc/74ef0c3e404cc72c08b2d1e14506f90d9e877269/library/core/src/panicking.rs:50:5
  17:     0x7f22a409d4b5 - <rustc_trait_selection::traits::query::normalize::QueryNormalizer as rustc_middle::ty::fold::TypeFolder>::fold_ty::hc95a20e7cdd22597
  18:     0x7f22a403fa30 - rustc_middle::ty::fold::TypeFoldable::fold_with::h954fc24bdeb2e96e
  19:     0x7f22a408d66a - rustc_middle::ty::structural_impls::<impl rustc_middle::ty::fold::TypeFoldable for &rustc_middle::ty::TyS>::super_fold_with::h8ceca8e018b93ffa
  20:     0x7f22a409c4f6 - <rustc_trait_selection::traits::query::normalize::QueryNormalizer as rustc_middle::ty::fold::TypeFolder>::fold_ty::hc95a20e7cdd22597
  21:     0x7f22a3899970 - <rustc_infer::infer::at::At as rustc_trait_selection::traits::query::normalize::AtExt>::normalize::hb71d72f0ba35c667
  22:     0x7f22a388c99d - rustc_infer::infer::InferCtxtBuilder::enter::hab199ae1631b39e8
  23:     0x7f22a389af68 - core::ops::function::FnOnce::call_once::h24f16da279ed7bd7
  24:     0x7f22a3b1154d - rustc_query_system::query::plumbing::get_query_impl::hd825fc255c29519f
  25:     0x7f22a3b5c53f - <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::normalize_generic_arg_after_erasing_regions::h062c0c4d5027d100
  26:     0x7f22a41841d0 - rustc_middle::ty::normalize_erasing_regions::NormalizeAfterErasingRegionsFolder::normalize_generic_arg_after_erasing_regions::hcd821ce068baf57a
  27:     0x7f22a36095cb - rustc_middle::ty::util::fold_list::h128f20764f893854
  28:     0x7f22a3660f3b - rustc_middle::ty::structural_impls::<impl rustc_middle::ty::fold::TypeFoldable for rustc_middle::ty::sty::Binder<T>>::super_fold_with::hb4b89ad0eb294be5
  29:     0x7f22a36216a4 - rustc_middle::ty::fold::TypeFolder::fold_binder::h3d44401b2d50c4c0
  30:     0x7f22a359dbb5 - rustc_middle::ty::normalize_erasing_regions::<impl rustc_middle::ty::context::TyCtxt>::normalize_erasing_regions::hb7a1178a524e7b35
  31:     0x7f22a41777ec - rustc_middle::ty::layout::<impl rustc_middle::ty::instance::Instance>::fn_sig_for_fn_abi::hd97e417fc8900b14
  32:     0x7f22a3863487 - <rustc_target::abi::call::FnAbi<&rustc_middle::ty::TyS> as rustc_middle::ty::layout::FnAbiExt<C>>::of_instance::h01bf068a1677b1a2
  33:     0x7f22a38571ba - rustc_codegen_llvm::mono_item::<impl rustc_codegen_ssa::traits::declare::PreDefineMethods for rustc_codegen_llvm::context::CodegenCx>::predefine_fn::h9ffd9900040301bc
  34:     0x7f22a3869af3 - rustc_codegen_llvm::base::compile_codegen_unit::module_codegen::hefd9993fd5d8f6af
  35:     0x7f22a42abc07 - rustc_query_system::dep_graph::graph::DepGraph<K>::with_task::h109c11c2d2b2fe9e
  36:     0x7f22a42c31f7 - rustc_codegen_llvm::base::compile_codegen_unit::hd128bb1380560c35
  37:     0x7f22a42b03c6 - <rustc_codegen_llvm::LlvmCodegenBackend as rustc_codegen_ssa::traits::backend::CodegenBackend>::codegen_crate::hc25561f12c31c9af
  38:     0x7f22a423246c - rustc_interface::passes::QueryContext::enter::h21fac079e595ecfb
  39:     0x7f22a422a3a6 - rustc_interface::queries::Queries::ongoing_codegen::h26b62c4c2f9af25f
  40:     0x7f22a42091bf - rustc_interface::queries::<impl rustc_interface::interface::Compiler>::enter::hd3df2f2fd8ee2f9c
  41:     0x7f22a41f7ecc - rustc_span::with_source_map::h4320e6c7562b1c81
  42:     0x7f22a420a32a - rustc_interface::interface::create_compiler_and_run::h8b004a10f044574a
  43:     0x7f22a41fd219 - scoped_tls::ScopedKey<T>::set::hc495f050953f2646
  44:     0x7f22a41f9fdb - std::sys_common::backtrace::__rust_begin_short_backtrace::hf6d64874d4b63366
  45:     0x7f22a41f8865 - core::ops::function::FnOnce::call_once{{vtable.shim}}::h44f63dc93d63fbac
  46:     0x7f22a1f3b9f7 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hd5b860c6542b008a
                               at /rustc/74ef0c3e404cc72c08b2d1e14506f90d9e877269/library/alloc/src/boxed.rs:1572:9
  47:     0x7f22a1f3b9f7 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hc87b98c8a3a585ed
                               at /rustc/74ef0c3e404cc72c08b2d1e14506f90d9e877269/library/alloc/src/boxed.rs:1572:9
  48:     0x7f22a1f3b9f7 - std::sys::unix::thread::Thread::new::thread_start::ha990175c8f3779cc
                               at /rustc/74ef0c3e404cc72c08b2d1e14506f90d9e877269/library/std/src/sys/unix/thread.rs:74:17
  49:     0x7f22a1e47259 - start_thread
  50:     0x7f22a1d5c5e3 - __GI___clone
  51:                0x0 - <unknown>

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.55.0-nightly (74ef0c3e4 2021-07-16) running on x86_64-unknown-linux-gnu

note: compiler flags: -Z polymorphize=on

query stack during panic:
#0 [normalize_generic_arg_after_erasing_regions] normalizing `std::option::Option<<Windows<T> as Iter>::Item<'_>>`
end of query stack
```

</p>
</details>

### PR DESCRIPTION
**Pull request by jackh726**
Fixes #70243
Fixes #70120
Fixes #62529
Fixes #87219 

Issues to followup on after (probably fixed, but no test added here):
#76956
#56556
#79207
#85636

r? @nikomatsakis

### CODE REVIEW

File: compiler/rustc_middle/src/ty/print/pretty.rs [hunk 1]
```diff
@@ -1830,96 +1834,136 @@ impl<F: fmt::Write> FmtPrinter<'_, 'tcx, F> {
...
+                                            &mut binders_string,
+                                            "for<",
+                                            ", ",
+                                        );
+                                        do_continue(&mut self, &mut binders_string, name);
+                                        kind
+                                    }
+                                    ty::BrAnon(_) | ty::BrEnv => {
+                                        return r;
+                                    }
```
Comment (jackh726) [inline compiler/rustc_middle/src/ty/print/pretty.rs:1937]: So, when I did have this, I was getting some new `for<'r> Send` is not implemented for `X` in some async tests. This might be something to look into, but I figured for now we don't need to worry about it.

File: compiler/rustc_trait_selection/src/traits/project.rs [hunk 2]
```diff
@@ -321,6 +323,32 @@ impl<'a, 'b, 'tcx> TypeFolder<'tcx> for AssocTypeNormalizer<'a, 'b, 'tcx> {
...
+    fn fold_binder<T>(&mut self, t: ty::Binder<'tcx, T>) -> ty::Binder<'tcx, T>
+    where
+        T: TypeFoldable<'tcx>,
+    {
+        let infcx = self.selcx.infcx();
+        let bound_vars = t.bound_vars();
+        let (with_placeholders, mapped_regions, mapped_types, mapped_consts) =
+            infcx.replace_bound_vars_with_placeholders_mapped(t);
+        debug!(?with_placeholders);
+        let folded_with_placeholders = with_placeholders.super_fold_with(self);
```
Comment (jackh726) [inline compiler/rustc_trait_selection/src/traits/project.rs:336]: I never implemented the "normalize to an inference variable then quantify the bound vars over the placeholders when the type is fully known" scheme, but seems like it's not needed?

File: src/test/ui/associated-types/hr-associated-type-bound-2.rs [hunk 3]
```diff
@@ -8,14 +8,13 @@ where
     }
 }
 
-impl X<'_> for u32
+impl X<'_> for u32 //~ overflow evaluating the requirement `for<'b> u32: X<'b>`
```
Comment (jackh726) [inline src/test/ui/associated-types/hr-associated-type-bound-2.rs:11]: This is not ideal. This is probably a blocker for merging this PR.

File: src/test/ui/associated-types/hr-associated-type-bound-param-5.rs [hunk 4]
```diff
@@ -25,14 +25,12 @@ where
 
 impl<S, T> X<'_, Vec<T>> for S {
     type U = str;
-    //~^ ERROR the trait bound `for<'b> <Box<T> as X<'b, Box<T>>>::U: Clone` is not satisfied
-    //~| ERROR the trait bound `for<'b> <Vec<T> as X<'b, Vec<T>>>::U: Clone` is not satisfied
+    //~^ ERROR the trait bound `str: Clone` is not satisfied
```
Comment (jackh726) [inline src/test/ui/associated-types/hr-associated-type-bound-param-5.rs:28]: So, because we can now normalize more eagerly, we don't hit a cycle

File: src/test/ui/associated-types/hr-associated-type-bound-param-6.rs [hunk 5]
```diff
@@ -12,7 +12,6 @@ where
 impl<S, T> X<'_, T> for (S,) {
     //~^ ERROR the trait bound `for<'b> T: X<'b, T>` is not satisfied
     type U = str;
-    //~^ ERROR the trait bound `for<'b> <T as X<'b, T>>::U: Clone` is not satisfied
```
Comment (jackh726) [inline src/test/ui/associated-types/hr-associated-type-bound-param-6.rs:15]: We lose this because the prior trait ref isn't satisfied and we fail earlier

File: src/test/ui/associated-types/hr-associated-type-projection-1.rs [hunk 6]
```diff
@@ -11,9 +11,8 @@ where
 }
 
 impl<T: Copy + std::ops::Deref> UnsafeCopy<'_, T> for T {
-    //~^ ERROR the trait bound `<T as UnsafeCopy<'b, T>>::Item: Deref` is not satisfied
+    //~^ type mismatch resolving `<T as Deref>::Target == T`
     type Item = T;
-    //~^ ERROR the trait bound `for<'b> <T as UnsafeCopy<'b, T>>::Item: Deref
```
Comment (jackh726) [inline src/test/ui/associated-types/hr-associated-type-projection-1.rs:16]: Diagnostics here are bad, but I think it is semantically the same

File: src/test/ui/higher-rank-trait-bounds/normalize-under-binder/issue-62529-6.rs [hunk 7]
```diff
@@ -0,0 +1,77 @@
+// check-pass
```
Comment (jackh726) [inline src/test/ui/higher-rank-trait-bounds/normalize-under-binder/issue-62529-6.rs:1]: I got bored of this after 6...

File: compiler/rustc_trait_selection/src/traits/project.rs [hunk 8]
```diff
@@ -321,6 +323,32 @@ impl<'a, 'b, 'tcx> TypeFolder<'tcx> for AssocTypeNormalizer<'a, 'b, 'tcx> {
         self.selcx.tcx()
     }
 
+    #[instrument(level = "debug", skip(self))]
+    fn fold_binder<T>(&mut self, t: ty::Binder<'tcx, T>) -> ty::Binder<'tcx, T>
```
Comment (Aaron1011) [inline compiler/rustc_trait_selection/src/traits/project.rs:327]: I think the comment in `fold_ty` below should be updated (since we now instantiate bound regions here, instead of 'eventually').

File: src/test/ui/recursion/issue-83150.rs [hunk 9]
```diff
@@ -1,3 +1,4 @@
+// ignore-test
```
Comment (jackh726) [inline src/test/ui/recursion/issue-83150.rs:1]: This shouldn't be ignored...looks like it's never ended. Blocker.

File: src/test/ui/type-alias-impl-trait/issue-60371.rs [hunk 10]
```diff
@@ -9,7 +9,7 @@ trait Bug {
 impl Bug for &() {
     type Item = impl Bug; //~ ERROR `impl Trait` in type aliases is unstable
     //~^ ERROR the trait bound `(): Bug` is not satisfied
-    //~^^ ERROR could not find defining uses
+    //~^^ the trait bound `(): Bug` is not satisfied
```
Comment (jackh726) [inline src/test/ui/type-alias-impl-trait/issue-60371.rs:12]: This error is weird

File: src/tools/compiletest/src/runtest.rs [hunk 11]
```diff
@@ -3935,7 +3935,7 @@ fn read2_abbreviated(mut child: Child) -> io::Result<Output> {
     use crate::read2::read2;
     use std::mem::replace;
 
-    const HEAD_LEN: usize = 160 * 1024;
+    const HEAD_LEN: usize = 16000 * 1024;
```
Comment (jackh726) [inline src/tools/compiletest/src/runtest.rs:3938]: Whoops.

**Review by jackh726 — COMMENTED** [review]
Looks like:
- Some cleanup in the pretty code needed
- Overflow evaluating a couple tests; one never finished, the other regresses on diagnostic
- Being able to normalize earlier leads to some errors that would happen later being suppressed; this is probably fine.

Overall though, I think this is close.

**Comment by smmalis37** [comment]
Will this fix https://github.com/rust-lang/rust/issues/76956 as well?

**Comment by jackh726** [comment]
> Will this fix #76956 as well?

Probably

**Comment by SkiFire13** [comment]
I think this also fixes #56556

**Comment by cynecx** [comment]
@jackh726 Does this also fix the "monad" test-case I've mentioned [here](https://github.com/rust-lang/rust/issues/76407#issuecomment-840060469)? Or is that a different matter (because of the type GAT)?

File: compiler/rustc_infer/src/infer/higher_ranked/mod.rs [hunk 12]
```diff
@@ -80,26 +97,36 @@ impl<'a, 'tcx> InferCtxt<'a, 'tcx> {
         // (i.e., if there are no placeholders).
         let next_universe = self.universe().next_universe();
 
+        let mut mapped_regions: BTreeMap<ty::PlaceholderRegion, ty::BoundRegion> = BTreeMap::new();
```
[the remark this answers is not in the document]
Comment (jackh726) [reply compiler/rustc_infer/src/infer/higher_ranked/mod.rs:102]: Can you clarify?

File: src/test/ui/associated-types/hr-associated-type-bound-2.rs (hunk 3 above)
Comment (jackh726) [reply src/test/ui/associated-types/hr-associated-type-bound-2.rs:11]: Actually, this is what we get in the more general case *without* a bound var: https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=f938d8e6a91f2162cf10896d2b5bafb5

I don't think this is blocking (though I think we *can* actually handle this correctly; I don't think that's in scope for this PR though)

File: compiler/rustc_infer/src/infer/higher_ranked/mod.rs (hunk 12 above)
[the remark this answers is not in the document]
Comment (jackh726) [reply compiler/rustc_infer/src/infer/higher_ranked/mod.rs:102]: I think you mean a map of like `GenericArg -> GenericArg` or something. Or some more specific enum. The biggest thing is then we have to match/unwrap the value too. As sad as the somewhat duplication is, I think it's fine tbh.

File: compiler/rustc_middle/src/ty/fold.rs [hunk 13]
```diff
@@ -555,14 +555,14 @@ impl<'tcx> TyCtxt<'tcx> {
...
-    ) -> (T, BTreeMap<ty::BoundRegion, ty::Region<'tcx>>)
+    ) -> (T, BTreeMap<ty::BoundRegionKind, ty::Region<'tcx>>)
     where
         F: FnMut(ty::BoundRegion) -> ty::Region<'tcx>,
         T: TypeFoldable<'tcx>,
     {
         let mut region_map = BTreeMap::new();
         let mut real_fld_r =
-            |br: ty::BoundRegion| *region_map.entry(br).or_insert_with(|| fld_r(br));
+            |br: ty::BoundRegion| *region_map.entry(br.kind).or_insert_with(|| fld_r(br));
```
Comment (jackh726) [inline compiler/rustc_middle/src/ty/fold.rs:565]: This actually might be wrong if we have the region bound at different binder levels

**Comment by jackh726** [comment]
@craterbot check

**Comment by jackh726** [comment]
Actually let's do a full build and test

@craterbot cancel

**Comment by jackh726** [comment]
@craterbot abort name=pr-85499

@craterbot run mode=build-and-test

**Comment by jackh726** [comment]
@craterbot run mode=build-and-test

**Comment by jyn514** [comment]
> Error: Label perf-regression can only be set by Rust team members

fyi @rylev, your new feature for triagebot isn't working

**Comment by jyn514** [comment]
Also, I disagree that this is a regression, it is a *very* large improvement on some cases with moderately large regressions on others. If triagebot isn't sure which, it shouldn't add a label.

**Comment by Manishearth** [comment]
I found a failure in not-yet-published code:

I tried this out on https://github.com/unicode-org/icu4x/pull/833 in the hopes that this would fix https://github.com/rust-lang/rust/issues/86703 

Unfortunately `cargo test` on `utils/yoke` now fails, where it used to pass:

<details>

```
---- src/trait_hack.rs - trait_hack (line 135) stdout ----
error: higher-ranked subtype error
  --> src/trait_hack.rs:186:9
   |
54 | /         Yoke::attach_to_cart_badly(rc_u32, |u| {
55 | |             YokeTraitHack::<<Y as Yokeable>::Output>::demo(*u).0
56 | |         })
   | |__________^

error: aborting due to previous error

Couldn't compile the test.
---- src/trait_hack.rs - trait_hack (line 31) stdout ----
Test compiled successfully, but it's marked `compile_fail`.
---- src/yoke.rs - yoke::Yoke<Y, C>::project (line 488) stdout ----
error: implementation of `Yokeable` is not general enough
 --> src/yoke.rs:493:6
  |
8 |    y.project(move |yk, _| yk.as_bytes())
  |      ^^^^^^^ implementation of `Yokeable` is not general enough
  |
  = note: `&[u8]` must implement `Yokeable<'0>`, for any lifetime `'0`...
  = note: ...but `Yokeable<'_>` is actually implemented for the type `&'static [u8]`

error: aborting due to previous error

Couldn't compile the test.
---- src/yoke.rs - yoke::Yoke<Y, C>::project (line 500) stdout ----
error: implementation of `Yokeable` is not general enough
  --> src/yoke.rs:513:9
   |
16 |     bar.project(|bar, _| bar.string_1)   
   |         ^^^^^^^ implementation of `Yokeable` is not general enough
   |
   = note: `&str` must implement `Yokeable<'0>`, for any lifetime `'0`...
   = note: ...but `Yokeable<'_>` is actually implemented for the type `&'static str`

error: aborting due to previous error
```

</details>


As far as I can tell all of this code should be valid (and used to compile), so this is a regression. However, I'll note that:

 - the `trait_hack` code is only necessary because of https://github.com/rust-lang/rust/issues/85636, which this _seems_ to fix (you can see a `compile_fail` test now passing)
 - the `project` code compiles fine without flags, but when testing with `RUSTDOCFLAGS="-Clink-dead-code"` it triggers an ICE https://github.com/rust-lang/rust/issues/86703


So: potential regressions, but in areas that were always sketchy. Also this PR _might_ also be fixing https://github.com/rust-lang/rust/issues/85636 (yay?)

**Comment by Mark-Simulacrum** [comment]
As noted, disagreement with the assessment should be filed as an issue on rustc-perf so we don't lose track of it. The label setting should be fixed soon - or has maybe already been fixed, not sure if the PR landed yet.

The results here are certainly mixed; but nevertheless there are a number of moderate regressions on real world test cases. Deeply nested async is a stress test and not necessarily as representative. However, when considered on balance with the number of fixed issues it seems reasonable to me that we shouldn't block this PR on performance neutrality.

**Comment by jackh726** [comment]
@Manishearth thanks for the test case. This is looks similar to `src/test/ui/issues/issue-44005.rs`. But I think it's actually different. 

At first, I thought the output seen in the test case is correct. But, after looking at it a bit more, I'm not so sure.

Here were my thoughts as I looked through this:

<details>
  <summary>Thoughts</summary>

So the error:
```rust
`Yokeable<'_>` is actually implemented for the type `&'static [u8]`
```
Well, I see this impl:
```rust
unsafe impl<'a, T: 'static + ?Sized> Yokeable<'a> for &'static T
```
which definitely matches a `&'static [u8]` not a `for<'a> &'a [u8]`

In particular, you have
```rust
y: Yoke<&'static str, Rc<[u8]>>
```
and
```rust
impl<Y: for<'a> Yokeable<'a>> Yoke<Y, Rc<[u8]>>
```
So, for you to be able to call `project`, you have to ask does `Y` equate to `&'static str`. So, `for<'a> Yokeable<'a> == &'static str`. And I guess I see an `for<T> &'static T: for<'a> Yokeable<'a>` impl.


Looking at the error again:
```rust
   = note: `&[u8]` must implement `Yokeable<'0>`, for any lifetime `'0`...
   = note: ...but `Yokeable<'_>` is actually implemented for the type `&'static [u8]`
```
this definitely seems a little weird. That first line, the "any" lifetime is on `Yokeable<'0>`, not `&[u8]`.

I'll look into this a little bit more sometime this week.
</details>

**Comment by Manishearth** [comment]
> which definitely matches a `&'static [u8]` not a `for<'a> &'a [u8]`

Yep, `Yokeable` is basically a way of getting GATs for covariant lifetimes, it's implemented on `'static` things and the `Output` is the lifetime-transformed general version. So `Yokeable::Output` should have pluggable lifetimes

**Comment by lqd** [comment]
Super quick lunch-break look at the results:

The vast majority of regressions are 4490 instances of this ICE: `thread 'rustc' panicked at 'index out of bounds: the len is 1 but the index is 1', /rustc/260f95826eb203db652b67d3652079d9b83d14a5/compiler/rustc_type_ir/src/lib.rs:113:1`

They appear in 6 different queries:
- 3 times in `codegen_fulfill_obligation` , [example](https://crater-reports.s3.amazonaws.com/pr-85499/try%23260f95826eb203db652b67d3652079d9b83d14a5/gh/bbarekas.hyper-service-custom/log.txt)
- 85 times in `dropck_outlives`, [example](https://crater-reports.s3.amazonaws.com/pr-85499/try%23260f95826eb203db652b67d3652079d9b83d14a5/reg/aqueue-1.1.3/log.txt)
- 4 times in `evaluate_obligation`, [example](https://crater-reports.s3.amazonaws.com/pr-85499/try%23260f95826eb203db652b67d3652079d9b83d14a5/gh/lanklaas.panic-test/log.txt)
- 4283 times in `normalize_generic_arg_after_erasing_regions`, [example](https://crater-reports.s3.amazonaws.com/pr-85499/try%23260f95826eb203db652b67d3652079d9b83d14a5/gh/05st.ph-discord-bot/log.txt)
- 2 times in `normalize_projection_ty`, [example](https://crater-reports.s3.amazonaws.com/pr-85499/try%23260f95826eb203db652b67d3652079d9b83d14a5/gh/AsamK.gcm-verification/log.txt)
- 113 times in `typeck`, [example](https://crater-reports.s3.amazonaws.com/pr-85499/try%23260f95826eb203db652b67d3652079d9b83d14a5/gh/5urpher.rusty-bunny/log.txt)

Maybe we can take a look at some of the smaller crates in these categories to try and have minimal examples for each (in case they show different issues in the PR or other potential existing issues that this PR would now surface, maybe like Manish's case above)

ICEs are not root-caused in the report, but some popular crates are hit so there are *not* 4500 root regressions. For example, I'm seeing approximately:
- 50 about actix-web
- 350 about async-tungstenite
- 90 about redis
- 50 about rocket
- 150 about sqlx-core
- 120 about tide
- 230 about tokio-postgres
- 1300 about trust-dns-proto

**Comment by jackh726** [comment]
That's rough. But I'm glad that we did a crater run.

I'm a bit surprised around the "index out of bounds error"; looks like it's happening in `DebruijnIndex`, which suggests maybe some logic around shifting is wrong somewhere is wrong, or we're using the wrong db index. That looks like [here](https://github.com/rust-lang/rust/pull/85499/files#diff-8d11697c196da9f44774488ae0bf353283e5c6466a6dd570d7818431b73d4a44R606). This actually is wrong, I think. Since we can replace multiple levels of bound vars. Really, we should be doing the reverse of [here](https://github.com/rust-lang/rust/pull/85499/files#diff-8d11697c196da9f44774488ae0bf353283e5c6466a6dd570d7818431b73d4a44R489).

It would be nice to get a MCVE of these. If there are any tests that fail where build passes, that's important to know. Also, I'm surprised that Manish's "not general enough" test didn't come up anywhere...

**Comment by lqd** [comment]
Here's a repro for the ICE in the `typeck` query

<details>

```rust
use std::future::Future;
use std::pin::Pin;
pub enum Outcome<S, E> {
    Success((S, E)),
}
pub struct Request<'r> {
    _marker: std::marker::PhantomData<&'r ()>,
}
pub trait FromRequest<'r>: Sized {
    type Error;
    fn from_request<'life0>(
        request: &'r Request<'life0>,
    ) -> Pin<Box<dyn Future<Output = Outcome<Self, Self::Error>>>>;
}
impl<'r, T: FromRequest<'r>> FromRequest<'r> for Option<T> {
    type Error = ();
    fn from_request<'life0>(
        request: &'r Request<'life0>,
    ) -> Pin<Box<dyn Future<Output = Outcome<Self, Self::Error>>>> {
        Box::pin(async move {
            let request = request;
            match T::from_request(request).await {
                _ => todo!(),
            }
        });
        todo!()
    }
}

fn main() {}
```

</details>

and a similar one for the `dropck_outlives` query (downstream from the `typeck` one)

<details>

```rust
use std::future::Future;
use std::pin::Pin;
pub enum Outcome<S, E> {
    Success(S),
    Failure(E),
}
pub struct Request<'r> {
    _marker: std::marker::PhantomData<&'r ()>,
}
pub trait FromRequest<'r>: Sized {
    type Error;
    fn from_request<'life0>(
        request: &'r Request<'life0>,
    ) -> Pin<Box<dyn Future<Output = Outcome<Self, Self::Error>>>>;
}
pub struct S<T> {
    _marker: std::marker::PhantomData<T>,
}
impl<'r, T: FromRequest<'r>> S<T> {
    pub async fn from_request(request: &'r Request<'_>) {
        let _ = T::from_request(request).await;
    }
}

fn main() {}
```

</details>

**Comment by lqd** [comment]
And one for the most common query in the results: `normalize_generic_arg_after_erasing_regions`

<details>

```rust
use std::future::{Future, Ready};
async fn read() {
    let _ = connect(&()).await;
}
async fn connect<A: ToSocketAddr>(addr: A) {
    let _ = addr.to_socket_addr().await;
}
pub trait ToSocketAddr {
    type Future: Future<Output = ()>;
    fn to_socket_addr(&self) -> Self::Future;
}
impl ToSocketAddr for &() {
    type Future = Ready<()>;
    fn to_socket_addr(&self) -> Self::Future {
        unimplemented!()
    }
}
struct Server;
impl Server {
    fn and_then<F>(self, _fun: F) -> AndThen<F> {
        unimplemented!()
    }
}
struct AndThen<F> {
    _marker: std::marker::PhantomData<F>,
}
pub async fn run<F>(_: F) {
}
fn main() {
    let _ = async {
        let server = Server;
        let verification_route = server.and_then(read);
        run(verification_route).await;
    };
}
```

</details>

**Comment by lqd** [comment]
Some analysis of the test regressions, for the 23 crates from crates.io (out of the 50 marked as regressed in the results):
- `async-compat-0.2.1`: it's just the "index out of bounds" ICE in a doctest
- `async-io-1.4.1`: same
- `async-net-1.6.0`: same
- `asyncgit-0.16.2`: these tests look non-deterministic. Locally, I'm seeing some random failures on nightly, and also tests passing with this PR.
- `bmp085-0.1.2`: Tests pass locally on nightly and with this PR.
- `brio-0.2.0`: spurious looking, connection refused failure in `skip_body`. Tests pass locally on nightly and with this PR.
- `cascara-0.1.0`: Tests pass locally on nightly and with this PR.
- `cmd_lib_core-0.4.0`: failure seems to depend on results of local commands. Tests pass locally on nightly and with this PR.
- `crux-0.3.0`: Strange, I'm seeing this one hang/deadlock on nightly and with this PR.
- `docmatic-0.1.2`: looks like an error compiling a doctest because of multiple versions of the rlib. Tests pass locally on nightly and with this PR.
- `exclave-0.2.6`: Tests pass locally on nightly and with this PR.
- `ezhook-0.2.2`: Tests may be non-deterministic, I'm seeing failures and successes both on nightly and with this PR.
- `festive-0.2.2`: Tests pass locally on nightly and with this PR.
- `hyphenation-0.8.3`: Tests pass locally on nightly and with this PR.
- `lyon-weiler-atherton-0.1.0`: Tests may be non-deterministic, I'm seeing random failures and successes both on nightly and with this PR.
- `rsyn-0.0.1`: failure trying to list files. I'm seeing failures on nightly as well.
- `rust-string-random-0.1.0`: failure in doctest that passes locally on nightly and with this PR.
- `shm_open_anonymous-1.0.1`: failure looks system dependent. Fails locally on nightly.
- `snooze-rs-0.0.3`: failure looks timing dependent. Tests pass locally on nightly and with this PR.
- `thread_timer-0.3.0`: failure in `can_be_reused`. Look timing dependent. Random failures and successes locally on nightly and with this PR.
- `timemoji-0.2.0`: Tests may be non-deterministic, I'm seeing random failures and successes both on nightly and with this PR.
- `tracing-bunyan-formatter-0.2.4`: Tests may be non-deterministic, I'm seeing random failures and successes both on nightly and with this PR.

Based on the above, I don't expect to find anything in the other 27 github projects with test regressions, so I won't be looking at them ^^

Overall, despite the scary number of regressions, this run looks pretty good. There's only the ICE to worry about and this should be good to go.

**Comment by jackh726** [comment]
Thank you so much @lqd 

Crazy that we haven't see the `Yokeable` regression pop up. (Given that I was able to find an MCVE that compiles on nightly)

**Comment by Manishearth** [comment]
Yeah, I am doing some gnarly stuff there (and the code with the regression hasn't been published yet)

File: compiler/rustc_mir/src/borrow_check/type_check/input_output.rs [hunk 14]
```diff
@@ -80,6 +82,33 @@ impl<'a, 'tcx> TypeChecker<'a, 'tcx> {
             let local = Local::new(argument_index + 1);
 
             let mir_input_ty = body.local_decls[local].ty;
+            // FIXME(jackh726): This is a hack. It's somewhat like
+            // `rustc_traits::normalize_after_erasing_regions`. Ideally, we'd
+            // like to normalize *before* inserting into `local_decls`, but I
+            // couldn't figure out where the heck that was.
```
Comment (jyn514) [inline compiler/rustc_mir/src/borrow_check/type_check/input_output.rs:88]: I found the following uses of `local_decls`. Not sure which if any are the ones you're looking for.

```
compiler/rustc_mir_build/src/build/mod.rs
792:    let mut local_decls = IndexVec::from_elem_n(LocalDecl::new(ty, span), 1);

compiler/rustc_mir/src/shim.rs
724:    let mut local_decls = local_decls_for_sig(&sig, span);
883:    let local_decls = local_decls_for_sig(&sig, span);

compiler/rustc_mir/src/transform/remove_zsts.rs
16:        let (basic_blocks, local_decls) = body.basic_blocks_and_local_decls_mut();

compiler/rustc_mir/src/transform/instcombine.rs
15:        let (basic_blocks, local_decls) = body.basic_blocks_and_local_decls_mut();

compiler/rustc_mir/src/transform/add_retag.rs
70:        let (basic_blocks, local_decls) = body.basic_blocks_and_local_decls_mut();

compiler/rustc_mir/src/transform/remove_unneeded_drops.rs
19:        let (basic_blocks, local_decls) = body.basic_blocks_and_local_decls_mut();

compiler/rustc_mir/src/transform/lower_slice_len.rs
27:    let (basic_blocks, local_decls) = body.basic_blocks_and_local_decls_mut();

compiler/rustc_mir/src/transform/deaggregator.rs
10:        let (basic_blocks, local_decls) = body.basic_blocks_and_local_decls_mut();
11:        let local_decls = &*local_decls;

compiler/rustc_mir/src/transform/lower_intrinsics.rs
15:        let (basic_blocks, local_decls) = body.basic_blocks_and_local_decls_mut();

compiler/rustc_mir/src/transform/match_branches.rs
51:        let (bbs, local_decls) = body.basic_blocks_and_local_decls_mut();

compiler/rustc_mir/src/transform/generator.rs
287:        let local_decls_len = body.local_decls.push(temp_decl);
387:    body.local_decls.raw[1].ty = ref_gen_ty;
402:    body.local_decls.raw[1].ty = pin_ref_gen_ty;
943:    body.local_decls[RETURN_PLACE] = LocalDecl::with_source_info(tcx.mk_unit(), source_info);
948:    body.local_decls[SELF_ARG] = LocalDecl::with_source_info(

compiler/rustc_mir/src/transform/promote_consts.rs
852:                promoted.local_decls[RETURN_PLACE] = LocalDecl::new(ty, span);
875:            let (blocks, local_decls) = self.source.basic_blocks_and_local_decls_mut();
```

Comment (jackh726) [reply compiler/rustc_mir/src/borrow_check/type_check/input_output.rs:88]: Yeah, that's the real question: which one of those is it? I looked through a couple, but didn't find it.

Comment (jackh726) [reply compiler/rustc_mir/src/borrow_check/type_check/input_output.rs:88]: Just for reference, without this, `normalization-generality` fails with:
```
error: internal compiler error: broken MIR in DefId(0:19 ~ normalization_generality[317d]::slice::{closure#0}) (bb0[0]): equate_normalized_input_or_output: `&'_#2r [slice::{closure#0} closure_kind_ty=i8 closure_sig_as_fn_ptr_ty=for<'r> extern "rust-call" fn((&ReLateBound(DebruijnIndex(0), BoundRegion { var: 0, kind: BrNamed('r) }) (), &ReLateBound(DebruijnIndex(0), BoundRegion { var: 0, kind: BrNamed('r) }) ())) -> &ReLateBound(DebruijnIndex(0), BoundRegion { var: 0, kind: BrNamed('r) }) () upvar_tys=()]==&'_#9r [slice::{closure#0} closure_kind_ty=i8 closure_sig_as_fn_ptr_ty=for<'r> extern "rust-call" fn((&ReLateBound(DebruijnIndex(0), BoundRegion { var: 0, kind: BrNamed('r) }) (), &ReLateBound(DebruijnIndex(0), BoundRegion { var: 0, kind: BrNamed('r) }) ())) -> <&'_#10r () as Yokeable<ReLateBound(DebruijnIndex(0), BoundRegion { var: 0, kind: BrNamed('r) })>>::Output upvar_tys=()]` failed with `NoSolution`
```

File: compiler/rustc_trait_selection/src/traits/query/normalize.rs [hunk 15]
```diff
@@ -65,6 +67,14 @@ impl<'cx, 'tcx> AtExt<'tcx> for At<'cx, 'tcx> {
             universes: vec![],
         };
 
+        if value.has_escaping_bound_vars() {
```
Comment (jackh726) [inline compiler/rustc_trait_selection/src/traits/query/normalize.rs:70]: Doing it this way fixes #87219

**Comment by smmalis37** [comment]
Will this also fix https://github.com/rust-lang/rust/issues/79207?

**Comment by jackh726** [comment]
> Will this also fix #79207?

Probably. Looks like it.

**Comment by jackh726** [comment]
Perf is pretty decent. This is ready for review.

**Comment by Manishearth** [comment]
@jackh726 Hmm, this still doesn't fix https://github.com/rust-lang/rust/issues/86703 (was it supposed to?)

**Comment by Manishearth** [comment]
Seems like this also fixes https://github.com/rust-lang/rust/issues/85636, we could check in the testcase if desired, or could follow up.

**Comment by hellow554** [comment]
Hey @jackh726 do you have time to resolve the merge conflict and try again to merge this?

**Comment by jackh726** [comment]
This is waiting on review. Rebase should be easy.

File: compiler/rustc_middle/src/ty/layout.rs [hunk 16]
```diff
@@ -2483,10 +2483,9 @@ impl<'tcx> ty::Instance<'tcx> {
                 // `src/test/ui/polymorphization/normalized_sig_types.rs`), and codegen not keeping
                 // track of a polymorphization `ParamEnv` to allow normalizing later.
```
Comment (Aaron1011) [inline compiler/rustc_middle/src/ty/layout.rs:2484]: Should this comment be removed?

File: compiler/rustc_trait_selection/src/traits/project.rs [hunk 17]
```diff
@@ -433,22 +428,19 @@ impl<'a, 'b, 'tcx> TypeFolder<'tcx> for AssocTypeNormalizer<'a, 'b, 'tcx> {
...
-                // bound vars and that's a can of worms). Instead, we just
-                // give up and fall back to pretending like we never tried!
+            ty::Projection(data) => {
+                // If there are escaping bound vars, we temporarily replace the
+                // bound vars with placeholders. Note though, that in the cas
+                // that we still can't project for whatever reason (e.g. self
+                // type isn't known enough), we *can't* register an obligation
+                // and return an inference variable (since then that obligation
+                // would have bound vars and that's a can of worms). Instead,
+                // we just give up and fall back to pretending like we never tried!
```
Comment (Aaron1011) [inline compiler/rustc_trait_selection/src/traits/project.rs:438]: I remember this being discussed on Zulip - is this intended to be a 'temporary' hack until we figure out an approach for registering obligations with bound bars?

File: compiler/rustc_middle/src/ty/layout.rs (hunk 16 above)
Comment (jackh726) [reply compiler/rustc_middle/src/ty/layout.rs:2484]: Nope, this just reverts the change here from #86993. I had made this change before because `normalize_erasing_regions` couldn't handle the escaping vars (so it was pushed to only occur with `polymorphize` enabled). But other changes required a different approach in `query/normalize.rs` to allow them anyways. So I reverted this back. *But* theoretically this could stay the same.

File: compiler/rustc_trait_selection/src/traits/project.rs (hunk 17 above)
Comment (jackh726) [reply compiler/rustc_trait_selection/src/traits/project.rs:438]: Yes and no. This specific behavior of giving up if we can't normalize is, yes, somewhat of a hack. Trying to tread the line between normalizing *more* and not blowing things up.

That said, it's not clear if the "correct" approach is registering obligations with bound vars, or maybe just a lazy normalization approach.

Comment (Aaron1011) [reply compiler/rustc_trait_selection/src/traits/project.rs:438]: Could you update the comment to note that this is not necessarily the final approach to dealing with obligations?

File: compiler/rustc_trait_selection/src/traits/project.rs [hunk 18]
```diff
@@ -362,25 +362,25 @@ impl<'a, 'b, 'tcx> TypeFolder<'tcx> for AssocTypeNormalizer<'a, 'b, 'tcx> {
...
-        // should occur eventually).
-
-        let ty = ty.super_fold_with(self);
+
+        // N.b. while we want to call `super_fold_with(self)` on `ty` before
+        // normalization, we wait until we know whether we need to normalize the
+        // current type. If we do, then we only fold the ty *after* replacing bound
+        // vars with placeholders. This means that nested types don't need to replace
+        // bound vars at the current binder level or above. A key assumption here is
+        // that folding the type can't introduce new bound vars.
```
Comment (nikomatsakis) [inline compiler/rustc_trait_selection/src/traits/project.rs:371]: I found this comment a bit hard to understand. It might be nice to give an example.

File: compiler/rustc_trait_selection/src/traits/query/normalize.rs [hunk 19]
```diff
@@ -292,7 +344,7 @@ impl<'cx, 'tcx> TypeFolder<'tcx> for QueryNormalizer<'cx, 'tcx> {
                 )
             }
 
-            _ => ty,
+            _ => ty.super_fold_with(self),
```
Comment (nikomatsakis) [inline compiler/rustc_trait_selection/src/traits/query/normalize.rs:347]: Are you missing a `ty.super_fold_with(self)` on line 334 of this file?

Also, the `replace_placeholders` call on line 337, that's a no-op in the case of `Err`, right?

File: compiler/rustc_trait_selection/src/traits/project.rs [hunk 20]
```diff
@@ -459,7 +451,7 @@ impl<'a, 'b, 'tcx> TypeFolder<'tcx> for AssocTypeNormalizer<'a, 'b, 'tcx> {
                 )
                 .ok()
                 .flatten()
-                .unwrap_or_else(|| ty);
+                .unwrap_or_else(|| ty.super_fold_with(self));
 
                 let normalized_ty = PlaceholderReplacer::replace_placeholders(
```
Comment (nikomatsakis) [inline compiler/rustc_trait_selection/src/traits/project.rs:456]: This is a no-op in the "fallback" case, right? Maybe we want

```rust
.ok()
.flatten()
.map(|ty| PlaceholderReplacer::replace_placeholders(...))
.unwrap_or_else(|| ty.super_fold_with(self))
```

?

File: compiler/rustc_trait_selection/src/traits/query/normalize.rs (hunk 15 above)
Comment (nikomatsakis) [reply compiler/rustc_trait_selection/src/traits/query/normalize.rs:70]: I think this could use a comment, ideally with an example. I think I understand what it's doing, though -- this is kind of a "consequence" of sorts of the lazy fallback, right? We're saying that if we have escaping bound vars, those are universes that we postponed creating, so we have to extend the set of universes here semi-artificially?

(If those were placeholders, they would be handled by default, right?)

If so, maybe we want to .. do the instantiation eagerly here instead? Is that something we can easily do?

**Review by nikomatsakis — CHANGES_REQUESTED** [review]

File: compiler/rustc_trait_selection/src/traits/query/normalize.rs (hunk 19 above)
Comment (jackh726) [reply compiler/rustc_trait_selection/src/traits/query/normalize.rs:347]: Yes, I've missed a couple.

And yes, it's a no-op on Err. I'll move it.

File: compiler/rustc_trait_selection/src/traits/project.rs (hunk 20 above)
Comment (jackh726) [reply compiler/rustc_trait_selection/src/traits/project.rs:456]: Yes, I'll change it.

File: compiler/rustc_trait_selection/src/traits/query/normalize.rs (hunk 15 above)
Comment (jackh726) [reply compiler/rustc_trait_selection/src/traits/query/normalize.rs:70]: No, so this is actually a consequence by the way `normalize_erasing_regions` works. Because it needs to call the `normalize_generic_arg_after_erasing_regions`, it folds through tys and consts in a `TypeFoldable`. Importantly, it skips binders, leaving us with trying to normalize with escaping bound vars.

Here, we just add the universes that we *would* have created had we passed through the binders.

We *could* instantiate eagerly here, but it doesn't seem really necessary to me. The rest of the code is already set up to be lazy about replacing bound vars and only when we actually have to normalize.

**Review by nikomatsakis — APPROVED** [review]

**Comment by Alexendoo** [comment]
The following big list of ICEs are also fixed by this PR 👍

I haven't closed/marked any as needs-test because I'm not sure which would be considered duplicates to the already added ones

- #63031
- #68090
- #79463
- #79628
- #80706
- #80956
- #81809
- #85455
- #86535

**Comment by jackh726** [comment]
Thanks @Alexendoo I'll take a look :)
