### PR TITLE
Revert "use `tcx.used_crates(())` more" before it reaches beta

### LINKED ISSUE #125474: ICE: index out of bounds in rustc_codegen_ssa
### Code

Minimal repro: https://github.com/parasyte/crashy

### Meta

This is the first nightly that the ICE appears in. (Does not appear to affect `2024-05-22` or earlier.)

`rustc --version --verbose`:
```
rustc 1.80.0-nightly (867900499 2024-05-23)
binary: rustc
commit-hash: 8679004993f08807289911d9f400f4ac4391d2bc
commit-date: 2024-05-23
host: aarch64-apple-darwin
release: 1.80.0-nightly
LLVM version: 18.1.6
```

### Error output

<details><summary><strong>Backtrace</strong></summary>
<p>

```
thread 'rustc' panicked at compiler/rustc_codegen_ssa/src/back/link.rs:2700:27:
index out of bounds: the len is 20 but the index is 20
stack backtrace:
   0:        0x102e97260 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hfa1323da475f800d
   1:        0x102ed9d14 - core::fmt::write::heaa8abb186c3047d
   2:        0x102e8d65c - std::io::Write::write_fmt::h3d08850e35aab4bf
   3:        0x102e970b8 - std::sys_common::backtrace::print::h4df82b4992ac1fc1
   4:        0x102e996c0 - std::panicking::default_hook::{{closure}}::h7ff64b2e0b9b22e2
   5:        0x102e9938c - std::panicking::default_hook::h22468db7cd0b8309
   6:        0x10c779e74 - <alloc[b3d7b17f3254a7e4]::boxed::Box<rustc_driver_impl[d78fc4912d252757]::install_ice_hook::{closure#0}> as core[7a0d7fb87c17620e]::ops::function::Fn<(&dyn for<'a, 'b> core[7a0d7fb87c17620e]::ops::function::Fn<(&'a core[7a0d7fb87c17620e]::panic::panic_info::PanicInfo<'b>,), Output = ()> + core[7a0d7fb87c17620e]::marker::Sync + core[7a0d7fb87c17620e]::marker::Send, &core[7a0d7fb87c17620e]::panic::panic_info::PanicInfo)>>::call
   7:        0x102e9a0ac - std::panicking::rust_panic_with_hook::h7f81e6b48edd822e
   8:        0x102e99ac0 - std::panicking::begin_panic_handler::{{closure}}::h61dc216c734bb31b
   9:        0x102e976e4 - std::sys_common::backtrace::__rust_end_short_backtrace::h14d37ee99da8f514
  10:        0x102e99830 - _rust_begin_unwind
  11:        0x102ef5608 - core::panicking::panic_fmt::h879022f43970f0ca
  12:        0x102ef5768 - core::panicking::panic_bounds_check::habf076b85f30241b
  13:        0x10c4d5efc - rustc_codegen_ssa[6b173b5bf0f2b0be]::back::link::linker_with_args
  14:        0x10c4cccac - rustc_codegen_ssa[6b173b5bf0f2b0be]::back::link::link_natively
  15:        0x10c4c8e70 - rustc_codegen_ssa[6b173b5bf0f2b0be]::back::link::link_binary
  16:        0x10c3da0e0 - <rustc_codegen_llvm[21fd93a69a5e3bd5]::LlvmCodegenBackend as rustc_codegen_ssa[6b173b5bf0f2b0be]::traits::backend::CodegenBackend>::link
  17:        0x10cf170a8 - <rustc_interface[9b74dd81a584a30b]::queries::Linker>::link
  18:        0x10c76cca4 - rustc_span[16eba1eb411798eb]::create_session_globals_then::<core[7a0d7fb87c17620e]::result::Result<(), rustc_span[16eba1eb411798eb]::ErrorGuaranteed>, rustc_interface[9b74dd81a584a30b]::util::run_in_thread_with_globals<rustc_interface[9b74dd81a584a30b]::util::run_in_thread_pool_with_globals<rustc_interface[9b74dd81a584a30b]::interface::run_compiler<core[7a0d7fb87c17620e]::result::Result<(), rustc_span[16eba1eb411798eb]::ErrorGuaranteed>, rustc_driver_impl[d78fc4912d252757]::run_compiler::{closure#0}>::{closure#1}, core[7a0d7fb87c17620e]::result::Result<(), rustc_span[16eba1eb411798eb]::ErrorGuaranteed>>::{closure#0}, core[7a0d7fb87c17620e]::result::Result<(), rustc_span[16eba1eb411798eb]::ErrorGuaranteed>>::{closure#0}::{closure#0}::{closure#0}>
  19:        0x10c73a9c8 - std[c992710344e8eb3f]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[9b74dd81a584a30b]::util::run_in_thread_with_globals<rustc_interface[9b74dd81a584a30b]::util::run_in_thread_pool_with_globals<rustc_interface[9b74dd81a584a30b]::interface::run_compiler<core[7a0d7fb87c17620e]::result::Result<(), rustc_span[16eba1eb411798eb]::ErrorGuaranteed>, rustc_driver_impl[d78fc4912d252757]::run_compiler::{closure#0}>::{closure#1}, core[7a0d7fb87c17620e]::result::Result<(), rustc_span[16eba1eb411798eb]::ErrorGuaranteed>>::{closure#0}, core[7a0d7fb87c17620e]::result::Result<(), rustc_span[16eba1eb411798eb]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[7a0d7fb87c17620e]::result::Result<(), rustc_span[16eba1eb411798eb]::ErrorGuaranteed>>
  20:        0x10c706024 - <<std[c992710344e8eb3f]::thread::Builder>::spawn_unchecked_<rustc_interface[9b74dd81a584a30b]::util::run_in_thread_with_globals<rustc_interface[9b74dd81a584a30b]::util::run_in_thread_pool_with_globals<rustc_interface[9b74dd81a584a30b]::interface::run_compiler<core[7a0d7fb87c17620e]::result::Result<(), rustc_span[16eba1eb411798eb]::ErrorGuaranteed>, rustc_driver_impl[d78fc4912d252757]::run_compiler::{closure#0}>::{closure#1}, core[7a0d7fb87c17620e]::result::Result<(), rustc_span[16eba1eb411798eb]::ErrorGuaranteed>>::{closure#0}, core[7a0d7fb87c17620e]::result::Result<(), rustc_span[16eba1eb411798eb]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[7a0d7fb87c17620e]::result::Result<(), rustc_span[16eba1eb411798eb]::ErrorGuaranteed>>::{closure#2} as core[7a0d7fb87c17620e]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  21:        0x102ea2a04 - std::sys::pal::unix::thread::Thread::new::thread_start::h020974cd53976785
  22:        0x195abaf94 - __pthread_joiner_wake
```

</p>
</details>

### LINKED ISSUE #125484: ICE when using `Instant` type with the `time` crate.
### Code

```Rust
type hi_rustc_devs_you_are_the_best = std::time::Instant;
fn main() {}
```
```toml
[dependencies]
time = { version = "=0.3.36", default-features = false }
```

```
rustc 1.80.0-nightly (867900499 2024-05-23)
binary: rustc
commit-hash: 8679004993f08807289911d9f400f4ac4391d2bc
commit-date: 2024-05-23
host: x86_64-unknown-linux-gnu
release: 1.80.0-nightly
LLVM version: 18.1.6
```

make sure to use cargo {build, run, test}.

### Error output

```
thread 'rustc' panicked at compiler/rustc_codegen_ssa/src/back/link.rs:2700:27:
index out of bounds: the len is 19 but the index is 19
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
thread 'rustc' panicked at compiler/rustc_codegen_ssa/src/back/link.rs:2700:27:
index out of bounds: the len is 19 but the index is 19
stack backtrace:
   0:     0x7f4c72d14bd5 - std::backtrace_rs::backtrace::libunwind::trace::hc81ddd892f37780a
                               at /rustc/8679004993f08807289911d9f400f4ac4391d2bc/library/std/src/../../backtrace/src/backtrace/libunwind.rs:105:5
   1:     0x7f4c72d14bd5 - std::backtrace_rs::backtrace::trace_unsynchronized::h25113f8f3907d8be
                               at /rustc/8679004993f08807289911d9f400f4ac4391d2bc/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7f4c72d14bd5 - std::backtrace::Backtrace::create::h4f3748e24e2503eb
                               at /rustc/8679004993f08807289911d9f400f4ac4391d2bc/library/std/src/backtrace.rs:331:13
   3:     0x7f4c72d14b25 - std::backtrace::Backtrace::force_capture::he79a6af8ebf22849
                               at /rustc/8679004993f08807289911d9f400f4ac4391d2bc/library/std/src/backtrace.rs:312:9
   4:     0x7f4c6f713446 - std[c84386057951cdf1]::panicking::update_hook::<alloc[4592256d7c6fc8c3]::boxed::Box<rustc_driver_impl[c7973d17cf87f5de]::install_ice_hook::{closure#0}>>::{closure#0}
   5:     0x7f4c72d2f95b - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h44aa27eef4dccdcb
                               at /rustc/8679004993f08807289911d9f400f4ac4391d2bc/library/alloc/src/boxed.rs:2077:9
   6:     0x7f4c72d2f95b - std::panicking::rust_panic_with_hook::h1aa3c5553cd412a6
                               at /rustc/8679004993f08807289911d9f400f4ac4391d2bc/library/std/src/panicking.rs:799:13
   7:     0x7f4c72d2f6d4 - std::panicking::begin_panic_handler::{{closure}}::ha60e6e6c3ca02408
                               at /rustc/8679004993f08807289911d9f400f4ac4391d2bc/library/std/src/panicking.rs:664:13
   8:     0x7f4c72d2cee9 - std::sys_common::backtrace::__rust_end_short_backtrace::he47d033b604f34e1
                               at /rustc/8679004993f08807289911d9f400f4ac4391d2bc/library/std/src/sys_common/backtrace.rs:171:18
   9:     0x7f4c72d2f407 - rust_begin_unwind
                               at /rustc/8679004993f08807289911d9f400f4ac4391d2bc/library/std/src/panicking.rs:652:5
  10:     0x7f4c72d780c3 - core::panicking::panic_fmt::he0b49d9fe944afab
                               at /rustc/8679004993f08807289911d9f400f4ac4391d2bc/library/core/src/panicking.rs:72:14
  11:     0x7f4c72d782e7 - core::panicking::panic_bounds_check::h4aab5c6abdb84502
                               at /rustc/8679004993f08807289911d9f400f4ac4391d2bc/library/core/src/panicking.rs:274:5
  12:     0x7f4c7182f58e - rustc_codegen_ssa[de9b47d4234be54f]::back::link::linker_with_args
  13:     0x7f4c71824b1e - rustc_codegen_ssa[de9b47d4234be54f]::back::link::link_natively
  14:     0x7f4c71754a0f - rustc_codegen_ssa[de9b47d4234be54f]::back::link::link_binary
  15:     0x7f4c71753f22 - <rustc_codegen_llvm[63b5484f8e8a1abd]::LlvmCodegenBackend as rustc_codegen_ssa[de9b47d4234be54f]::traits::backend::CodegenBackend>::link
  16:     0x7f4c7175737a - <rustc_interface[1555bb895ed40208]::queries::Linker>::link
  17:     0x7f4c715b8aa9 - rustc_interface[1555bb895ed40208]::interface::run_compiler::<core[d780e6c6047fe0c9]::result::Result<(), rustc_span[7e054f7c4ab6d345]::ErrorGuaranteed>, rustc_driver_impl[c7973d17cf87f5de]::run_compiler::{closure#0}>::{closure#1}
  18:     0x7f4c715a3f67 - std[c84386057951cdf1]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[1555bb895ed40208]::util::run_in_thread_with_globals<rustc_interface[1555bb895ed40208]::util::run_in_thread_pool_with_globals<rustc_interface[1555bb895ed40208]::interface::run_compiler<core[d780e6c6047fe0c9]::result::Result<(), rustc_span[7e054f7c4ab6d345]::ErrorGuaranteed>, rustc_driver_impl[c7973d17cf87f5de]::run_compiler::{closure#0}>::{closure#1}, core[d780e6c6047fe0c9]::result::Result<(), rustc_span[7e054f7c4ab6d345]::ErrorGuaranteed>>::{closure#0}, core[d780e6c6047fe0c9]::result::Result<(), rustc_span[7e054f7c4ab6d345]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[d780e6c6047fe0c9]::result::Result<(), rustc_span[7e054f7c4ab6d345]::ErrorGuaranteed>>
  19:     0x7f4c715a3d2a - <<std[c84386057951cdf1]::thread::Builder>::spawn_unchecked_<rustc_interface[1555bb895ed40208]::util::run_in_thread_with_globals<rustc_interface[1555bb895ed40208]::util::run_in_thread_pool_with_globals<rustc_interface[1555bb895ed40208]::interface::run_compiler<core[d780e6c6047fe0c9]::result::Result<(), rustc_span[7e054f7c4ab6d345]::ErrorGuaranteed>, rustc_driver_impl[c7973d17cf87f5de]::run_compiler::{closure#0}>::{closure#1}, core[d780e6c6047fe0c9]::result::Result<(), rustc_span[7e054f7c4ab6d345]::ErrorGuaranteed>>::{closure#0}, core[d780e6c6047fe0c9]::result::Result<(), rustc_span[7e054f7c4ab6d345]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[d780e6c6047fe0c9]::result::Result<(), rustc_span[7e054f7c4ab6d345]::ErrorGuaranteed>>::{closure#2} as core[d780e6c6047fe0c9]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  20:     0x7f4c72d3973b - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::he7419603c6721fe9
                               at /rustc/8679004993f08807289911d9f400f4ac4391d2bc/library/alloc/src/boxed.rs:2063:9
  21:     0x7f4c72d3973b - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hdd889fbd56bc6c7f
                               at /rustc/8679004993f08807289911d9f400f4ac4391d2bc/library/alloc/src/boxed.rs:2063:9
  22:     0x7f4c72d3973b - std::sys::pal::unix::thread::Thread::new::thread_start::hc8faaa9672833890
                               at /rustc/8679004993f08807289911d9f400f4ac4391d2bc/library/std/src/sys/pal/unix/thread.rs:108:17
  23:     0x7f4c6c4a6ded - <unknown>
  24:     0x7f4c6c52a0dc - <unknown>
  25:                0x0 - <unknown>


rustc version: 1.80.0-nightly (867900499 2024-05-23)
platform: x86_64-unknown-linux-gnu
```

</p>
</details>

### LINKED ISSUE #125646: Crash rustc
```
thread 'rustc' panicked at compiler\rustc_codegen_ssa\src\back\link.rs:2700:27:
index out of bounds: the len is 29 but the index is 29
stack backtrace:
   0:     0x7ff8bd9a3b5d - std::backtrace_rs::backtrace::dbghelp64::trace
                               at /rustc/84b40fc908c3adc7e0e470b3fbaa264df0e122b8/library\std\src\..\..\backtrace\src\backtrace\dbghelp64.rs:91
   1:     0x7ff8bd9a3b5d - std::backtrace_rs::backtrace::trace_unsynchronized
                               at /rustc/84b40fc908c3adc7e0e470b3fbaa264df0e122b8/library\std\src\..\..\backtrace\src\backtrace\mod.rs:66
   2:     0x7ff8bd9a3b5d - std::sys_common::backtrace::_print_fmt
                               at /rustc/84b40fc908c3adc7e0e470b3fbaa264df0e122b8/library\std\src\sys_common\backtrace.rs:68
   3:     0x7ff8bd9a3b5d - std::sys_common::backtrace::_print::impl$0::fmt
                               at /rustc/84b40fc908c3adc7e0e470b3fbaa264df0e122b8/library\std\src\sys_common\backtrace.rs:44
   4:     0x7ff8bd9d4af9 - core::fmt::rt::Argument::fmt
                               at /rustc/84b40fc908c3adc7e0e470b3fbaa264df0e122b8/library\core\src\fmt\rt.rs:165
   5:     0x7ff8bd9d4af9 - core::fmt::write
                               at /rustc/84b40fc908c3adc7e0e470b3fbaa264df0e122b8/library\core\src\fmt\mod.rs:1168
   6:     0x7ff8bd99a2e1 - std::io::Write::write_fmt<std::sys::pal::windows::stdio::Stderr>
                               at /rustc/84b40fc908c3adc7e0e470b3fbaa264df0e122b8/library\std\src\io\mod.rs:1835
   7:     0x7ff8bd9a3936 - std::sys_common::backtrace::print
                               at /rustc/84b40fc908c3adc7e0e470b3fbaa264df0e122b8/library\std\src\sys_common\backtrace.rs:34
   8:     0x7ff8bd9a6b08 - std::panicking::default_hook::closure$1
                               at /rustc/84b40fc908c3adc7e0e470b3fbaa264df0e122b8/library\std\src\panicking.rs:271
   9:     0x7ff8bd9a67b6 - std::panicking::default_hook
                               at /rustc/84b40fc908c3adc7e0e470b3fbaa264df0e122b8/library\std\src\panicking.rs:298
  10:     0x7ff8b6b7688c - memchr
  11:     0x7ff8bd9a7[137](https://github.com/nulldotblack/wintun/actions/runs/9266177251/job/25489812616#step:3:138) - alloc::boxed::impl$50::call
                               at /rustc/84b40fc908c3adc7e0e470b3fbaa264df0e122b8/library\alloc\src\boxed.rs:2077
  12:     0x7ff8bd9a7137 - std::panicking::rust_panic_with_hook
                               at /rustc/84b40fc908c3adc7e0e470b3fbaa264df0e122b8/library\std\src\panicking.rs:799
  13:     0x7ff8bd9a6fc7 - std::panicking::begin_panic_handler::closure$0
                               at /rustc/84b40fc908c3adc7e0e470b3fbaa264df0e122b8/library\std\src\panicking.rs:664
  14:     0x7ff8bd9a44cf - std::sys_common::backtrace::__rust_end_short_backtrace<std::panicking::begin_panic_handler::closure_env$0,never$>
                               at /rustc/84b40fc908c3adc7e0e470b3fbaa264df0e122b8/library\std\src\sys_common\backtrace.rs:171
  15:     0x7ff8bd9a6c78 - std::panicking::begin_panic_handler
                               at /rustc/84b40fc908c3adc7e0e470b3fbaa264df0e122b8/library\std\src\panicking.rs:652
  16:     0x7ff8bd9fe344 - core::panicking::panic_fmt
                               at /rustc/84b40fc908c3adc7e0e470b3fbaa264df0e122b8/library\core\src\panicking.rs:72
  17:     0x7ff8bd9fe57e - core::panicking::panic_bounds_check
                               at /rustc/84b40fc908c3adc7e0e470b3fbaa264df0e122b8/library\core\src\panicking.rs:274
  18:     0x7ff8b5504e93 - rustc_codegen_ssa[b16efbcf849bbe15]::back::link::linker_and_flavor
  19:     0x7ff8b54f94b0 - rustc_codegen_ssa[b16efbcf849bbe15]::back::link::each_linked_rlib
  20:     0x7ff8b54f3ddb - rustc_codegen_ssa[b16efbcf849bbe15]::back::link::link_binary
  21:     0x7ff8b2ac2106 - <rustc_codegen_llvm[ae9deb7a2fb2044c]::LlvmCodegenBackend as rustc_codegen_ssa[b16efbcf849bbe15]::traits::backend::CodegenBackend>::link
  22:     0x7ff8b2a[145](https://github.com/nulldotblack/wintun/actions/runs/9266177251/job/25489812616#step:3:146)59 - <rustc_interface[dba02352c3517abd]::queries::Linker>::link
  23:     0x7ff8b29c3bce - llvm::function_ref<void __cdecl(llvm::Value const * __ptr64)>::callback_fn<`llvm::Value::stripInBoundsOffsets'::`1'::<lambda_1_1> >
  24:     0x7ff8b29c06ef - llvm::function_ref<void __cdecl(llvm::Value const * __ptr64)>::callback_fn<`llvm::Value::stripInBoundsOffsets'::`1'::<lambda_1_1> >
  25:     0x7ff8b29c8549 - llvm::function_ref<void __cdecl(llvm::Value const * __ptr64)>::callback_fn<`llvm::Value::stripInBoundsOffsets'::`1'::<lambda_1_1> >
  26:     0x7ff8bd9b818d - alloc::boxed::impl$48::call_once
                               at /rustc/84b40fc908c3adc7e0e470b3fbaa264df0e122b8/library\alloc\src\boxed.rs:2063
  27:     0x7ff8bd9b818d - alloc::boxed::impl$48::call_once
                               at /rustc/84b40fc908c3adc7e0e470b3fbaa264df0e122b8/library\alloc\src\boxed.rs:2063
  28:     0x7ff8bd9b818d - std::sys::pal::windows::thread::impl$0::new::thread_start
                               at /rustc/84b40fc908c3adc7e0e470b3fbaa264df0e122b8/library\std\src\sys\pal\windows\thread.rs:52
  29:     0x7ff8f39c4cb0 - BaseThreadInitThunk
  30:     0x7ff8f481e8ab - RtlUserThreadStart

error: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: please make sure that you have updated to the latest nightly

note: please attach the file at `D:\a\wintun\wintun\rustc-ice-2024-05-28T08_39_42-4064.txt` to your bug report

note: compiler flags: -C embed-bitcode=no -C debuginfo=2 -C incremental=[REDACTED]
```

### LINKED ISSUE #125707: ICE on nightly-2024-05-28 during link stage
This ICE both exists on macOS aarch64 and linux amd64.

### Code

Internal code, cannot public.

### Meta

`rustc --version --verbose`:
```
rustc 1.80.0-nightly (da159eb33 2024-05-28)
binary: rustc
commit-hash: da159eb331b27df528185c616b394bb0e1d2a4bd
commit-date: 2024-05-28
host: aarch64-apple-darwin
release: 1.80.0-nightly
LLVM version: 18.1.6
```

### Error output

```
thread 'rustc' panicked at compiler/rustc_codegen_ssa/src/back/link.rs:2700:27:
index out of bounds: the len is 308 but the index is 308
stack backtrace:
   0:        0x1019253ac - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hee5d3add81f8769b
   1:        0x1019699e4 - core::fmt::write::h9dc0a212068c4487
   2:        0x10191b750 - std::io::Write::write_fmt::h1601e9a4a36351ca
   3:        0x101925204 - std::sys_common::backtrace::print::h9535b2af8a100aec
   4:        0x101927810 - std::panicking::default_hook::{{closure}}::hdd85190914d7518f
   5:        0x1019274dc - std::panicking::default_hook::h9798bf625bf54a9e
   6:        0x10b1a8c70 - <alloc[bce90598dd3f4dd3]::boxed::Box<rustc_driver_impl[c4bab6df5b4b3fba]::install_ice_hook::{closure#0}> as core[9e7a2f7b9a3a4c06]::ops::function::Fn<(&dyn for<'a, 'b> core[9e7a2f7b9a3a4c06]::ops::function::Fn<(&'a core[9e7a2f7b9a3a4c06]::panic::panic_info::PanicInfo<'b>,), Output = ()> + core[9e7a2f7b9a3a4c06]::marker::Sync + core[9e7a2f7b9a3a4c06]::marker::Send, &core[9e7a2f7b9a3a4c06]::panic::panic_info::PanicInfo)>>::call
   7:        0x1019281fc - std::panicking::rust_panic_with_hook::hea32a016165e022b
   8:        0x101927c10 - std::panicking::begin_panic_handler::{{closure}}::he55e42119f08366c
   9:        0x101925830 - std::sys_common::backtrace::__rust_end_short_backtrace::h2ec39936dd320eff
  10:        0x101927980 - _rust_begin_unwind
  11:        0x101985260 - core::panicking::panic_fmt::hdd0a8c3eb8088208
  12:        0x1019853f0 - core::panicking::panic_bounds_check::h4e28ad5c5971d664
  13:        0x10af1668c - rustc_codegen_ssa[b068ff2a868a000c]::back::link::linker_with_args
  14:        0x10af0d504 - rustc_codegen_ssa[b068ff2a868a000c]::back::link::link_natively
  15:        0x10af0978c - rustc_codegen_ssa[b068ff2a868a000c]::back::link::link_binary
  16:        0x10aeaa15c - <rustc_codegen_llvm[7dd9e7fd145dc8ba]::LlvmCodegenBackend as rustc_codegen_ssa[b068ff2a868a000c]::traits::backend::CodegenBackend>::link
  17:        0x10b988674 - <rustc_interface[c016e796069c9104]::queries::Linker>::link
  18:        0x10b170e54 - <scoped_tls[7b6fdb05fca54dc0]::ScopedKey<rustc_span[fb448f34252b061b]::SessionGlobals>>::set::<rustc_interface[c016e796069c9104]::util::run_in_thread_with_globals<rustc_interface[c016e796069c9104]::util::run_in_thread_pool_with_globals<rustc_interface[c016e796069c9104]::interface::run_compiler<core[9e7a2f7b9a3a4c06]::result::Result<(), rustc_span[fb448f34252b061b]::ErrorGuaranteed>, rustc_driver_impl[c4bab6df5b4b3fba]::run_compiler::{closure#0}>::{closure#1}, core[9e7a2f7b9a3a4c06]::result::Result<(), rustc_span[fb448f34252b061b]::ErrorGuaranteed>>::{closure#0}, core[9e7a2f7b9a3a4c06]::result::Result<(), rustc_span[fb448f34252b061b]::ErrorGuaranteed>>::{closure#0}::{closure#0}::{closure#0}, core[9e7a2f7b9a3a4c06]::result::Result<(), rustc_span[fb448f34252b061b]::ErrorGuaranteed>>
  19:        0x10b17afe8 - rustc_span[fb448f34252b061b]::create_session_globals_then::<core[9e7a2f7b9a3a4c06]::result::Result<(), rustc_span[fb448f34252b061b]::ErrorGuaranteed>, rustc_interface[c016e796069c9104]::util::run_in_thread_with_globals<rustc_interface[c016e796069c9104]::util::run_in_thread_pool_with_globals<rustc_interface[c016e796069c9104]::interface::run_compiler<core[9e7a2f7b9a3a4c06]::result::Result<(), rustc_span[fb448f34252b061b]::ErrorGuaranteed>, rustc_driver_impl[c4bab6df5b4b3fba]::run_compiler::{closure#0}>::{closure#1}, core[9e7a2f7b9a3a4c06]::result::Result<(), rustc_span[fb448f34252b061b]::ErrorGuaranteed>>::{closure#0}, core[9e7a2f7b9a3a4c06]::result::Result<(), rustc_span[fb448f34252b061b]::ErrorGuaranteed>>::{closure#0}::{closure#0}::{closure#0}>
  20:        0x10b179a14 - std[aa6988fe294f8aab]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[c016e796069c9104]::util::run_in_thread_with_globals<rustc_interface[c016e796069c9104]::util::run_in_thread_pool_with_globals<rustc_interface[c016e796069c9104]::interface::run_compiler<core[9e7a2f7b9a3a4c06]::result::Result<(), rustc_span[fb448f34252b061b]::ErrorGuaranteed>, rustc_driver_impl[c4bab6df5b4b3fba]::run_compiler::{closure#0}>::{closure#1}, core[9e7a2f7b9a3a4c06]::result::Result<(), rustc_span[fb448f34252b061b]::ErrorGuaranteed>>::{closure#0}, core[9e7a2f7b9a3a4c06]::result::Result<(), rustc_span[fb448f34252b061b]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[9e7a2f7b9a3a4c06]::result::Result<(), rustc_span[fb448f34252b061b]::ErrorGuaranteed>>
  21:        0x10b17a0ac - <<std[aa6988fe294f8aab]::thread::Builder>::spawn_unchecked_<rustc_interface[c016e796069c9104]::util::run_in_thread_with_globals<rustc_interface[c016e796069c9104]::util::run_in_thread_pool_with_globals<rustc_interface[c016e796069c9104]::interface::run_compiler<core[9e7a2f7b9a3a4c06]::result::Result<(), rustc_span[fb448f34252b061b]::ErrorGuaranteed>, rustc_driver_impl[c4bab6df5b4b3fba]::run_compiler::{closure#0}>::{closure#1}, core[9e7a2f7b9a3a4c06]::result::Result<(), rustc_span[fb448f34252b061b]::ErrorGuaranteed>>::{closure#0}, core[9e7a2f7b9a3a4c06]::result::Result<(), rustc_span[fb448f34252b061b]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[9e7a2f7b9a3a4c06]::result::Result<(), rustc_span[fb448f34252b061b]::ErrorGuaranteed>>::{closure#2} as core[9e7a2f7b9a3a4c06]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  22:        0x101930d18 - std::sys::pal::unix::thread::Thread::new::thread_start::h2c9944774d079220
  23:        0x1964baf94 - __pthread_joiner_wake

error: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: please make sure that you have updated to the latest nightly

note: please attach the file at `/Users/purewhite/rust/xxx/rustc-ice-2024-05-29T09_07_49-55168.txt` to your bug report

note: compiler flags: --crate-type bin -C embed-bitcode=no -C debuginfo=2 -C split-debuginfo=unpacked -C incremental=[REDACTED] -C target-cpu=native

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
```

The file: 

[rustc-ice-2024-05-29T09_13_04-56076.txt](https://github.com/rust-lang/rust/files/15481923/rustc-ice-2024-05-29T09_13_04-56076.txt)

<details><summary><strong>Backtrace</strong></summary>
<p>

Backtrace with `RUST_BACKTRACE=full`:

```
thread 'rustc' panicked at compiler/rustc_codegen_ssa/src/back/link.rs:2700:27:
index out of bounds: the len is 308 but the index is 308
stack backtrace:
   0:        0x1058693ac - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hee5d3add81f8769b
   1:        0x1058ad9e4 - core::fmt::write::h9dc0a212068c4487
   2:        0x10585f750 - std::io::Write::write_fmt::h1601e9a4a36351ca
   3:        0x105869204 - std::sys_common::backtrace::print::h9535b2af8a100aec
   4:        0x10586b810 - std::panicking::default_hook::{{closure}}::hdd85190914d7518f
   5:        0x10586b4dc - std::panicking::default_hook::h9798bf625bf54a9e
   6:        0x10f0ecc70 - <alloc[bce90598dd3f4dd3]::boxed::Box<rustc_driver_impl[c4bab6df5b4b3fba]::install_ice_hook::{closure#0}> as core[9e7a2f7b9a3a4c06]::ops::function::Fn<(&dyn for<'a, 'b> core[9e7a2f7b9a3a4c06]::ops::function::Fn<(&'a core[9e7a2f7b9a3a4c06]::panic::panic_info::PanicInfo<'b>,), Output = ()> + core[9e7a2f7b9a3a4c06]::marker::Sync + core[9e7a2f7b9a3a4c06]::marker::Send, &core[9e7a2f7b9a3a4c06]::panic::panic_info::PanicInfo)>>::call
   7:        0x10586c1fc - std::panicking::rust_panic_with_hook::hea32a016165e022b
   8:        0x10586bc10 - std::panicking::begin_panic_handler::{{closure}}::he55e42119f08366c
   9:        0x105869830 - std::sys_common::backtrace::__rust_end_short_backtrace::h2ec39936dd320eff
  10:        0x10586b980 - _rust_begin_unwind
  11:        0x1058c9260 - core::panicking::panic_fmt::hdd0a8c3eb8088208
  12:        0x1058c93f0 - core::panicking::panic_bounds_check::h4e28ad5c5971d664
  13:        0x10ee5a68c - rustc_codegen_ssa[b068ff2a868a000c]::back::link::linker_with_args
  14:        0x10ee51504 - rustc_codegen_ssa[b068ff2a868a000c]::back::link::link_natively
  15:        0x10ee4d78c - rustc_codegen_ssa[b068ff2a868a000c]::back::link::link_binary
  16:        0x10edee15c - <rustc_codegen_llvm[7dd9e7fd145dc8ba]::LlvmCodegenBackend as rustc_codegen_ssa[b068ff2a868a000c]::traits::backend::CodegenBackend>::link
  17:        0x10f8cc674 - <rustc_interface[c016e796069c9104]::queries::Linker>::link
  18:        0x10f0b4e54 - <scoped_tls[7b6fdb05fca54dc0]::ScopedKey<rustc_span[fb448f34252b061b]::SessionGlobals>>::set::<rustc_interface[c016e796069c9104]::util::run_in_thread_with_globals<rustc_interface[c016e796069c9104]::util::run_in_thread_pool_with_globals<rustc_interface[c016e796069c9104]::interface::run_compiler<core[9e7a2f7b9a3a4c06]::result::Result<(), rustc_span[fb448f34252b061b]::ErrorGuaranteed>, rustc_driver_impl[c4bab6df5b4b3fba]::run_compiler::{closure#0}>::{closure#1}, core[9e7a2f7b9a3a4c06]::result::Result<(), rustc_span[fb448f34252b061b]::ErrorGuaranteed>>::{closure#0}, core[9e7a2f7b9a3a4c06]::result::Result<(), rustc_span[fb448f34252b061b]::ErrorGuaranteed>>::{closure#0}::{closure#0}::{closure#0}, core[9e7a2f7b9a3a4c06]::result::Result<(), rustc_span[fb448f34252b061b]::ErrorGuaranteed>>
  19:        0x10f0befe8 - rustc_span[fb448f34252b061b]::create_session_globals_then::<core[9e7a2f7b9a3a4c06]::result::Result<(), rustc_span[fb448f34252b061b]::ErrorGuaranteed>, rustc_interface[c016e796069c9104]::util::run_in_thread_with_globals<rustc_interface[c016e796069c9104]::util::run_in_thread_pool_with_globals<rustc_interface[c016e796069c9104]::interface::run_compiler<core[9e7a2f7b9a3a4c06]::result::Result<(), rustc_span[fb448f34252b061b]::ErrorGuaranteed>, rustc_driver_impl[c4bab6df5b4b3fba]::run_compiler::{closure#0}>::{closure#1}, core[9e7a2f7b9a3a4c06]::result::Result<(), rustc_span[fb448f34252b061b]::ErrorGuaranteed>>::{closure#0}, core[9e7a2f7b9a3a4c06]::result::Result<(), rustc_span[fb448f34252b061b]::ErrorGuaranteed>>::{closure#0}::{closure#0}::{closure#0}>
  20:        0x10f0bda14 - std[aa6988fe294f8aab]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[c016e796069c9104]::util::run_in_thread_with_globals<rustc_interface[c016e796069c9104]::util::run_in_thread_pool_with_globals<rustc_interface[c016e796069c9104]::interface::run_compiler<core[9e7a2f7b9a3a4c06]::result::Result<(), rustc_span[fb448f34252b061b]::ErrorGuaranteed>, rustc_driver_impl[c4bab6df5b4b3fba]::run_compiler::{closure#0}>::{closure#1}, core[9e7a2f7b9a3a4c06]::result::Result<(), rustc_span[fb448f34252b061b]::ErrorGuaranteed>>::{closure#0}, core[9e7a2f7b9a3a4c06]::result::Result<(), rustc_span[fb448f34252b061b]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[9e7a2f7b9a3a4c06]::result::Result<(), rustc_span[fb448f34252b061b]::ErrorGuaranteed>>
  21:        0x10f0be0ac - <<std[aa6988fe294f8aab]::thread::Builder>::spawn_unchecked_<rustc_interface[c016e796069c9104]::util::run_in_thread_with_globals<rustc_interface[c016e796069c9104]::util::run_in_thread_pool_with_globals<rustc_interface[c016e796069c9104]::interface::run_compiler<core[9e7a2f7b9a3a4c06]::result::Result<(), rustc_span[fb448f34252b061b]::ErrorGuaranteed>, rustc_driver_impl[c4bab6df5b4b3fba]::run_compiler::{closure#0}>::{closure#1}, core[9e7a2f7b9a3a4c06]::result::Result<(), rustc_span[fb448f34252b061b]::ErrorGuaranteed>>::{closure#0}, core[9e7a2f7b9a3a4c06]::result::Result<(), rustc_span[fb448f34252b061b]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[9e7a2f7b9a3a4c06]::result::Result<(), rustc_span[fb448f34252b061b]::ErrorGuaranteed>>::{closure#2} as core[9e7a2f7b9a3a4c06]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  22:        0x105874d18 - std::sys::pal::unix::thread::Thread::new::thread_start::h2c9944774d079220
  23:        0x1964baf94 - __pthread_joiner_wake
```

</p>
</details>

### LINKED ISSUE #125934: rustc 1.80.0-nightly crash
### Code

https://github.com/webrtc-rs/webrtc/actions/runs/9354666974/job/25748024701

```Rust
<code>
```

### Meta

`rustc --version --verbose`:
```
  nightly-x86_64-unknown-linux-gnu installed - rustc 1.80.0-nightly (032af18af 2024-06-02)
```

### Error output

```
thread 'rustc' panicked at compiler/rustc_metadata/src/dependency_format.rs:352:24:
index out of bounds: the len is 202 but the index is 212
stack backtrace:
   0:     0x7fc4c40d1cc5 - std::backtrace_rs::backtrace::libunwind::trace::haf0e753fffc1b5a5
                               at /rustc/032af18af578f4283a2927fb43b90df2bbb72b67/library/std/src/../../backtrace/src/backtrace/libunwind.rs:116:5
   1:     0x7fc4c40d1cc5 - std::backtrace_rs::backtrace::trace_unsynchronized::h70f82ab6a4db8cdf
                               at /rustc/032af18af578f4283a2927fb43b90df2bbb72b67/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7fc4c40d1cc5 - std::sys_common::backtrace::_print_fmt::h5a6fce4ae01b1105
                               at /rustc/032af18af578f4283a2927fb43b90df2bbb72b67/library/std/src/sys_common/backtrace.rs:68:5
   3:     0x7fc4c40d1cc5 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h1fa2920817bbbd09
                               at /rustc/032af18af578f4283a2927fb43b90df2bbb72b67/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x7fc4c412246b - core::fmt::rt::Argument::fmt::h5f219a6468ec2c71
                               at /rustc/032af18af578f4283a2927fb43b90df2bbb72b67/library/core/src/fmt/rt.rs:165:63
   5:     0x7fc4c412246b - core::fmt::write::h6731ff0b9c7b8ce8
                               at /rustc/032af18af578f4283a2927fb43b90df2bbb72b67/library/core/src/fmt/mod.rs:1168:21
   6:     0x7fc4c40c6a4f - std::io::Write::write_fmt::hc4268973d8ae94c7
                               at /rustc/032af18af578f4283a2927fb43b90df2bbb72b67/library/std/src/io/mod.rs:1835:15
   7:     0x7fc4c40d1a9e - std::sys_common::backtrace::_print::h419656dfbbb87639
                               at /rustc/032af18af578f4283a2927fb43b90df2bbb72b67/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x7fc4c40d1a9e - std::sys_common::backtrace::print::h09b2[559](https://github.com/webrtc-rs/webrtc/actions/runs/9354666974/job/25748024701#step:5:560)5eb301343
                               at /rustc/032af18af578f4283a2927fb43b90df2bbb72b67/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x7fc4c40d44d9 - std::panicking::default_hook::{{closure}}::hf9ba49d7e1e5f023
  10:     0x7fc4c40d427a - std::panicking::default_hook::heea03dc93b69d475
                               at /rustc/032af18af578f4283a2927fb43b90df2bbb72b67/library/std/src/panicking.rs:298:9
  11:     0x7fc4c094403f - std[69052015ce1b7124]::panicking::update_hook::<alloc[f5014be2e767fdd]::boxed::Box<rustc_driver_impl[1b537cd12afd42a4]::install_ice_hook::{closure#0}>>::{closure#0}
  12:     0x7fc4c40d4c0b - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h6a19a53d0d9b021a
                               at /rustc/032af18af578f4283a2927fb43b90df2bbb72b67/library/alloc/src/boxed.rs:2077:9
  13:     0x7fc4c40d4c0b - std::panicking::rust_panic_with_hook::h642286663fe7c96b
                               at /rustc/032af18af578f4283a2927fb43b90df2bbb72b67/library/std/src/panicking.rs:799:13
  14:     0x7fc4c40d4984 - std::panicking::begin_panic_handler::{{closure}}::h7ce4f616ce330fa6
                               at /rustc/032af18af578f4283a2927fb43b90df2bbb72b67/library/std/src/panicking.rs:664:13
  15:     0x7fc4c40d2189 - std::sys_common::backtrace::__rust_end_short_backtrace::h7035c7c2ee90efed
                               at /rustc/032af18af578f4283a2927fb43b90df2bbb72b67/library/std/src/sys_common/backtrace.rs:171:18
  16:     0x7fc4c40d46b7 - rust_begin_unwind
                               at /rustc/032af18af578f4283a2927fb43b90df2bbb72b67/library/std/src/panicking.rs:652:5
  17:     0x7fc4c411ea03 - core::panicking::panic_fmt::h3ec5d1efb44b5034
                               at /rustc/032af18af[578](https://github.com/webrtc-rs/webrtc/actions/runs/9354666974/job/25748024701#step:5:579)f4283a2927fb43b90df2bbb72b67/library/core/src/panicking.rs:72:14
  18:     0x7fc4c411ec17 - core::panicking::panic_bounds_check::hde89ae76313212b4
                               at /rustc/032af18af578f4283a2927fb43b90df2bbb72b67/library/core/src/panicking.rs:274:5
  19:     0x7fc4c291a746 - <rustc_metadata[5adcf685f19e3a97]::rmeta::decoder::cstore_impl::provide::{closure#5} as core[57dce0d7678ad3a0]::ops::function::FnOnce<(rustc_middle[8bb46b904fcf8bdf]::ty::context::TyCtxt, ())>>::call_once
  20:     0x7fc4c2c1940d - rustc_query_impl[75ba70ce79c8d8ef]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[75ba70ce79c8d8ef]::query_impl::dependency_formats::dynamic_query::{closure#2}::{closure#0}, rustc_middle[8bb46b904fcf8bdf]::query::erase::Erased<[u8; 8usize]>>
  21:     0x7fc4c2c154d2 - rustc_query_system[5ea179786410f179]::query::plumbing::try_execute_query::<rustc_query_impl[75ba70ce79c8d8ef]::DynamicConfig<rustc_query_system[5ea179786410f179]::query::caches::SingleCache<rustc_middle[8bb46b904fcf8bdf]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[75ba70ce79c8d8ef]::plumbing::QueryCtxt, false>
  22:     0x7fc4c2c14d5e - rustc_query_impl[75ba70ce79c8d8ef]::query_impl::dependency_formats::get_query_non_incr::__rust_end_short_backtrace
  23:     0x7fc4c2c162a5 - rustc_codegen_ssa[d59740cb733497b7]::base::allocator_kind_for_codegen
  24:     0x7fc4c2911e05 - rustc_codegen_ssa[d59740cb733497b7]::back::symbol_export::exported_symbols_provider_local
  25:     0x7fc4c1f48e33 - rustc_query_impl[75ba70ce79c8d8ef]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[75ba70ce79c8d8ef]::query_impl::exported_symbols::dynamic_query::{closure#2}::{closure#0}, rustc_middle[8bb46b904fcf8bdf]::query::erase::Erased<[u8; 16usize]>>
  26:     0x7fc4c1f48e09 - <rustc_query_impl[75ba70ce79c8d8ef]::query_impl::exported_symbols::dynamic_query::{closure#2} as core[57dce0d7678ad3a0]::ops::function::FnOnce<(rustc_middle[8bb46b904fcf8bdf]::ty::context::TyCtxt, rustc_span[edacdd56afd4fe4e]::def_id::CrateNum)>>::call_once
  27:     0x7fc4c2a91371 - rustc_query_system[5ea179786410f179]::query::plumbing::try_execute_query::<rustc_query_impl[75ba70ce79c8d8ef]::DynamicConfig<rustc_query_system[5ea179786410f179]::query::caches::VecCache<rustc_span[edacdd56afd4fe4e]::def_id::CrateNum, rustc_middle[8bb46b904fcf8bdf]::query::erase::Erased<[u8; 16usize]>>, false, false, false>, rustc_query_impl[75ba70ce79c8d8ef]::plumbing::QueryCtxt, false>
  28:     0x7fc4c2a90f6b - rustc_query_impl[75ba70ce79c8d8ef]::query_impl::exported_symbols::get_query_non_incr::__rust_end_short_backtrace
  29:     0x7fc4c2a91023 - rustc_middle[8bb46b904fcf8bdf]::query::plumbing::query_get_at::<rustc_query_system[5ea179786410f179]::query::caches::VecCache<rustc_span[edacdd56afd4fe4e]::def_id::CrateNum, rustc_middle[8bb46b904fcf8bdf]::query::erase::Erased<[u8; 16usize]>>>
  30:     0x7fc4c291486d - <rustc_codegen_ssa[d59740cb733497b7]::CrateInfo>::new
  31:     0x7fc4c2b23ba0 - rustc_codegen_ssa[d59740cb733497b7]::back::write::start_async_codegen::<rustc_codegen_llvm[c02d8eeada8a187]::LlvmCodegenBackend>
  32:     0x7fc4c2cffb83 - rustc_codegen_ssa[d59740cb733497b7]::base::codegen_crate::<rustc_codegen_llvm[c02d8eeada8a187]::LlvmCodegenBackend>
  33:     0x7fc4c2cf344c - <rustc_codegen_llvm[c02d8eeada8a187]::LlvmCodegenBackend as rustc_codegen_ssa[d59740cb733497b7]::traits::backend::CodegenBackend>::codegen_crate
  34:     0x7fc4c2cf2ddf - rustc_interface[c4543bcf07cd468e]::passes::start_codegen
                               at /rustc/032af18af578f4283a2927fb43b90df2bbb72b67/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x7fabad78aa9e - std::sys_common::backtrace::print::h09b25[595](https://github.com/webrtc-rs/webrtc/actions/runs/9354666974/job/25748024701#step:5:596)eb301343
                               at /rustc/032af18af578f4283a2927fb43b90df2bbb72b67/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x7fabad78d4d9 - std::panicking::default_hook::{{closure}}::hf9ba49d7e1e5f023
  10:     0x7fabad78d27a - std::panicking::default_hook::heea03dc93b69d475
                               at /rustc/032af18af578f4283a2927fb43b90df2bbb72b67/library/std/src/panicking.rs:298:9
  11:     0x7fabb094403f - std[69052015ce1b7124]::panicking::update_hook::<alloc[f5014be2e767fdd]::boxed::Box<rustc_driver_impl[1b537cd12afd42a4]::install_ice_hook::{closure#0}>>::{closure#0}
  12:     0x7fabad78dc0b - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h6a19a53d0d9b021a
                               at /rustc/032af18af578f4283a2927fb43b90df2bbb72b67/library/alloc/src/boxed.rs:2077:9
  13:     0x7fabad78dc0b - std::panicking::rust_panic_with_hook::h642286663fe7c96b
                               at /rustc/032af18af578f4283a2927fb43b90df2bbb72b67/library/std/src/panicking.rs:799:13
  14:     0x7fabad78d984 - std::panicking::begin_panic_handler::{{closure}}::h7ce4f616ce330fa6
                               at /rustc/032af18af578f4283a2927fb43b90df2bbb72b67/library/std/src/panicking.rs:664:13
  15:     0x7fabad78b189 - std::sys_common::backtrace::__rust_end_short_backtrace::h7035c7c2ee90efed
                               at /rustc/032af18af578f4283a2927fb43b90df2bbb72b67/library/std/src/sys_common/backtrace.rs:171:18
  16:     0x7fabad78d6b7 - rust_begin_unwind
                               at /rustc/032af18af578f4283a2927fb43b90df2bbb72b67/library/std/src/panicking.rs:652:5
  17:     0x7fabad7d7a03 - core::panicking::panic_fmt::h3ec5d1efb44b5034
                               at /rustc/032af18af578f4283a2927fb43b90df2bbb72b67/library/core/src/panicking.rs:72:14
  18:     0x7fabad7d7c17 - core::panicking::panic_bounds_check::hde89ae76313212b4
                               at /rustc/032af18af578f4283a2927fb43b90df2bbb72b67/library/core/src/panicking.rs:274:5
  19:     0x7fabb291a746 - <rustc_metadata[5adcf685f19e3a97]::rmeta::decoder::cstore_impl::provide::{closure#5} as core[57dce0d7678ad3a0]::ops::function::FnOnce<(rustc_middle[8bb46b904fcf8bdf]::ty::context::TyCtxt, ())>>::call_once
  20:     0x7fabb2c1940d - rustc_query_impl[75ba70ce79c8d8ef]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[75ba70ce79c8d8ef]::query_impl::dependency_formats::dynamic_query::{closure#2}::{closure#0}, rustc_middle[8bb46b904fcf8bdf]::query::erase::Erased<[u8; 8usize]>>
  21:     0x7fabb2c154d2 - rustc_query_system[5ea179786410f179]::query::plumbing::try_execute_query::<rustc_query_impl[75ba70ce79c8d8ef]::DynamicConfig<rustc_query_system[5ea179786410f179]::query::caches::SingleCache<rustc_middle[8bb46b904fcf8bdf]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[75ba70ce79c8d8ef]::plumbing::QueryCtxt, false>
  22:     0x7fabb2c14d5e - rustc_query_impl[75ba70ce79c8d8ef]::query_impl::dependency_formats::get_query_non_incr::__rust_end_short_backtrace
  23:     0x7fabb2c162a5 - rustc_codegen_ssa[d[597](https://github.com/webrtc-rs/webrtc/actions/runs/9354666974/job/25748024701#step:5:598)40cb733497b7]::base::allocator_kind_for_codegen
  24:     0x7fabb2911e05 - rustc_codegen_ssa[d59740cb733497b7]::back::symbol_export::exported_symbols_provider_local
  25:     0x7fabb1f48e33 - rustc_query_impl[75ba70ce79c8d8ef]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[75ba70ce79c8d8ef]::query_impl::exported_symbols::dynamic_query::{closure#2}::{closure#0}, rustc_middle[8bb46b904fcf8bdf]::query::erase::Erased<[u8; 16usize]>>
  26:     0x7fabb1f48e09 - <rustc_query_impl[75ba70ce79c8d8ef]::query_impl::exported_symbols::dynamic_query::{closure#2} as core[57dce0d7678ad3a0]::ops::function::FnOnce<(rustc_middle[8bb46b904fcf8bdf]::ty::context::TyCtxt, rustc_span[edacdd56afd4fe4e]::def_id::CrateNum)>>::call_once
  27:     0x7fabb2a91371 - rustc_query_system[5ea179786410f179]::query::plumbing::try_execute_query::<rustc_query_impl[75ba70ce79c8d8ef]::DynamicConfig<rustc_query_system[5ea179786410f179]::query::caches::VecCache<rustc_span[edacdd56afd4fe4e]::def_id::CrateNum, rustc_middle[8bb46b904fcf8bdf]::query::erase::Erased<[u8; 16usize]>>, false, false, false>, rustc_query_impl[75ba70ce79c8d8ef]::plumbing::QueryCtxt, false>
  28:     0x7fabb2a90f6b - rustc_query_impl[75ba70ce79c8d8ef]::query_impl::exported_symbols::get_query_non_incr::__rust_end_short_backtrace
  29:     0x7fabb2a91023 - rustc_middle[8bb46b904fcf8bdf]::query::plumbing::query_get_at::<rustc_query_system[5ea179786410f179]::query::caches::VecCache<rustc_span[edacdd56afd4fe4e]::def_id::CrateNum, rustc_middle[8bb46b904fcf8bdf]::query::erase::Erased<[u8; 16usize]>>>
  30:     0x7fabb291486d - <rustc_codegen_ssa[d59740cb733497b7]::CrateInfo>::new
  31:     0x7fabb2b23ba0 - rustc_codegen_ssa[d59740cb733497b7]::back::write::start_async_codegen::<rustc_codegen_llvm[c02d8eeada8a187]::LlvmCodegenBackend>
  32:     0x7fabb2cffb83 - rustc_codegen_ssa[d59740cb733497b7]::base::codegen_crate::<rustc_codegen_llvm[c02d8eeada8a187]::LlvmCodegenBackend>
  33:     0x7fabb2cf344c - <rustc_codegen_llvm[c02d8eeada8a187]::LlvmCodegenBackend as rustc_codegen_ssa[d59740cb733497b7]::traits::backend::CodegenBackend>::codegen_crate
  34:     0x7fabb2cf2ddf - rustc_interface[c4543bcf07cd468e]::passes::start_codegen
  35:     0x7fabb2cf245a - <rustc_interface[c4543bcf07cd468e]::queries::Queries>::codegen_and_build_linker
  36:     0x7fabb2a7f140 - rustc_interface[c4543bcf07cd468e]::interface::run_compiler::<core[57dce0d7678ad3a0]::result::Result<(), rustc_span[edacdd56afd4fe4e]::ErrorGuaranteed>, rustc_driver_impl[1b537cd12afd42a4]::run_compiler::{closure#0}>::{closure#1}
  37:     0x7fabb2a400c9 - std[69052015ce1b7124]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[c4543bcf07cd468e]::util::run_in_thread_with_globals<rustc_interface[c4543bcf07cd468e]::util::run_in_thread_pool_with_globals<rustc_interface[c4543bcf07cd468e]::interface::run_compiler<core[57dce0d7678ad3a0]::result::Result<(), rustc_span[edacdd56afd4fe4e]::ErrorGuaranteed>, rustc_driver_impl[1b537cd12afd42a4]::run_compiler::{closure#0}>::{closure#1}, core[57dce0d7678ad3a0]::result::Result<(), rustc_span[edacdd56afd4fe4e]::ErrorGuaranteed>>::{closure#0}, core[57dce0d7678ad3a0]::result::Result<(), rustc_span[edacdd56afd4fe4e]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[57dce0d7678ad3a0]::result::Result<(), rustc_span[edacdd56afd4fe4e]::ErrorGuaranteed>>
  38:     0x7fabb2a3fe86 - <<std[69052015ce1b7124]::thread::Builder>::spawn_unchecked_<rustc_interface[c4543bcf07cd468e]::util::run_in_thread_with_globals<rustc_interface[c4543bcf07cd468e]::util::run_in_thread_pool_with_globals<rustc_interface[c4543bcf07cd468e]::interface::run_compiler<core[57dce0d7678ad3a0]::result::Result<(), rustc_span[edacdd56afd4fe4e]::ErrorGuaranteed>, rustc_driver_impl[1b537cd12afd42a4]::run_compiler::{closure#0}>::{closure#1}, core[57dce0d7[678](https://github.com/webrtc-rs/webrtc/actions/runs/9354666974/job/25748024701#step:5:679)ad3a0]::result::Result<(), rustc_span[edacdd56afd4fe4e]::ErrorGuaranteed>>::{closure#0}, core[57dce0d7678ad3a0]::result::Result<(), rustc_span[edacdd56afd4fe4e]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[57dce0d7678ad3a0]::result::Result<(), rustc_span[edacdd56afd4fe4e]::ErrorGuaranteed>>::{closure#2} as core[57dce0d7678ad3a0]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  39:     0x7fabad797bfb - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h0eb2bde6064def81
                               at /rustc/032af18af578f4283a2927fb43b90df2bbb72b67/library/alloc/src/boxed.rs:2063:9
  40:     0x7fabad797bfb - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hcdb0204268e0604a
                               at /rustc/032af18af578f4283a2927fb43b90df2bbb72b67/library/alloc/src/boxed.rs:2063:9
  41:     0x7fabad797bfb - std::sys::pal::unix::thread::Thread::new::thread_start::hd7ebf2795d4ccec5
                               at /rustc/032af18af578f4283a2927fb43b90df2bbb72b67/library/std/src/sys/pal/unix/thread.rs:108:17
  42:     0x7fabad494ac3 - <unknown>
  43:     0x7fabad526850 - <unknown>
  44:                0x0 - <unknown>

error: the compiler unexpectedly panicked. this is a bug.
Error: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: please make sure that you have updated to the latest nightly

note: please attach the file at `/home/runner/work/webrtc/webrtc/rustc-ice-2024-06-03T17_34_57-18114.txt` to your bug report

note: compiler flags: --crate-type bin -C embed-bitcode=no -C debuginfo=2 -Z profile -C codegen-units=1 -C opt-level=0 -C link-dead-code -C overflow-checks=off -Z panic_abort_tests -C panic=abort -C debug-assertions=off

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [dependency_formats] getting the linkage format of all dependencies
#1 [exported_symbols] collecting exported symbols for crate `0`
end of query stack
error: could not compile `examples` (example "play-from-disk-renegotiation")
Error: The process '/home/runner/.cargo/bin/cargo' failed with exit code 101
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
<backtrace>
```

</p>
</details>

### LINKED ISSUE #126021: Ice:  `panicked at compiler/rustc_metadata/src/dependency_format.rs:352:24: index out of bounds: the len is 124 but the index is 128`
With:
`
rust version 1.80.0-nightly (a330e4959 2024-06-04)
`

I don't have a reproducer yet but we haven't been able to build the Rust coreutils with nightly for a few days

```

warning: unexpected `cfg` condition value: `expensive_tests`
    --> tests/common/util.rs:3319:20
     |
3319 |     #[cfg_attr(not(feature = "expensive_tests"), ignore)]
     |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
     |
     = note: expected values for `feature` are: `arch`, `base32`, `base64`, `basename`, `basenc`, `cat`, `chcon`, `chgrp`, `chmod`, `chown`, `chroot`, `cksum`, `comm`, `cp`, `csplit`, `cut`, `date`, `dd`, `default`, `df`, `dir`, `dircolors`, `dirname`, `du`, `echo`, `env`, `expand`, `expr`, `factor`, `false`, `feat_Tier1`, `feat_acl`, `feat_common_core`, `feat_os_macos`, and `feat_os_unix` and 95 more
     = help: consider adding `expensive_tests` as a feature in `Cargo.toml`
     = note: see <https://doc.rust-lang.org/nightly/rustc/check-cfg/cargo-specifics.html> for more information about checking conditional configuration
     = note: `#[warn(unexpected_cfgs)]` on by default
thread 'rustc' panicked at compiler/rustc_metadata/src/dependency_format.rs:352:24:
index out of bounds: the len is 124 but the index is 128
stack backtrace:
   0: rust_begin_unwind
             at /rustc/a330e49593ee890f9197727a3a558b6e6b37f843/library/std/src/panicking.rs:652:5
   1: core::panicking::panic_fmt
             at /rustc/a330e49593ee890f9197727a3a558b6e6b37f843/library/core/src/panicking.rs:72:14
   2: core::panicking::panic_bounds_check
             at /rustc/a330e49593ee890f9197727a3a558b6e6b37f843/library/core/src/panicking.rs:274:5
   3: <rustc_metadata::rmeta::decoder::cstore_impl::provide::{closure#5} as core::ops::function::FnOnce<(rustc_middle::ty::context::TyCtxt, ())>>::call_once
      [... omitted 1 frame ...]
   4: rustc_codegen_ssa::base::allocator_kind_for_codegen
   5: rustc_codegen_ssa::back::symbol_export::exported_symbols_provider_local
      [... omitted 2 frames ...]
   6: rustc_middle::query::plumbing::query_get_at::<rustc_query_system::query::caches::VecCache<rustc_span::def_id::CrateNum, rustc_middle::query::erase::Erased<[u8; 16]>>>
   7: <rustc_codegen_ssa::CrateInfo>::new
   8: rustc_codegen_ssa::back::write::start_async_codegen::<rustc_codegen_llvm::LlvmCodegenBackend>
   9: rustc_codegen_ssa::base::codegen_crate::<rustc_codegen_llvm::LlvmCodegenBackend>
  10: <rustc_codegen_llvm::LlvmCodegenBackend as rustc_codegen_ssa::traits::backend::CodegenBackend>::codegen_crate
  11: rustc_interface::passes::start_codegen
  12: <rustc_interface::queries::Queries>::codegen_and_build_linker
  13: rustc_interface::interface::run_compiler::<core::result::Result<(), rustc_span::ErrorGuaranteed>, rustc_driver_impl::run_compiler::{closure#0}>::{closure#1}
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

error: the compiler unexpectedly panicked. this is a bug.
```

Example:
https://github.com/uutils/coreutils/actions/runs/9381558110/job/25831059999?pr=6452

Maybe it is https://github.com/rust-lang/rust/commit/711338bd9f957b7bd345323033e9037c0e1ca535
from @petrochenkov

### LINKED ISSUE #126066: [Nightly] thread 'rustc' panicked at compiler\rustc_codegen_ssa\src\back\link.rs:2700:27: index out of bounds: the len is 203 but the index is 207
### Code

```Rust
<code>
https://github.com/yuvlian/sphene/tree/main/sphene/src
```

### Meta

`rustc --version --verbose`:
```
<version>
rustc 1.80.0-nightly (72fdf913c 2024-06-05)
binary: rustc
commit-hash: 72fdf913c53dd0e75313ba83e4aa80df3f6e2871
commit-date: 2024-06-05
host: x86_64-pc-windows-msvc
release: 1.80.0-nightly
LLVM version: 18.1.6
```

### Error output

```
<output>
thread 'rustc' panicked at compiler\rustc_codegen_ssa\src\back\link.rs:2700:27:
index out of bounds: the len is 203 but the index is 207
stack backtrace:
   0:     0x7ffe02a23b9d - std::backtrace_rs::backtrace::dbghelp64::trace
                               at /rustc/72fdf913c53dd0e75313ba83e4aa80df3f6e2871/library\std\src\..\..\backtrace\src\backtrace\dbghelp64.rs:91
   1:     0x7ffe02a23b9d - std::backtrace_rs::backtrace::trace_unsynchronized
                               at /rustc/72fdf913c53dd0e75313ba83e4aa80df3f6e2871/library\std\src\..\..\backtrace\src\backtrace\mod.rs:66
   2:     0x7ffe02a23b9d - std::sys_common::backtrace::_print_fmt
                               at /rustc/72fdf913c53dd0e75313ba83e4aa80df3f6e2871/library\std\src\sys_common\backtrace.rs:68
   3:     0x7ffe02a23b9d - std::sys_common::backtrace::_print::impl$0::fmt
                               at /rustc/72fdf913c53dd0e75313ba83e4aa80df3f6e2871/library\std\src\sys_common\backtrace.rs:44
   4:     0x7ffe02a547d9 - core::fmt::rt::Argument::fmt
                               at /rustc/72fdf913c53dd0e75313ba83e4aa80df3f6e2871/library\core\src\fmt\rt.rs:165
   5:     0x7ffe02a547d9 - core::fmt::write
                               at /rustc/72fdf913c53dd0e75313ba83e4aa80df3f6e2871/library\core\src\fmt\mod.rs:1168
   6:     0x7ffe02a1a3f1 - std::io::Write::write_fmt<std::sys::pal::windows::stdio::Stderr>
                               at /rustc/72fdf913c53dd0e75313ba83e4aa80df3f6e2871/library\std\src\io\mod.rs:1835
   7:     0x7ffe02a23976 - std::sys_common::backtrace::print
                               at /rustc/72fdf913c53dd0e75313ba83e4aa80df3f6e2871/library\std\src\sys_common\backtrace.rs:34
   8:     0x7ffe02a26b58 - std::panicking::default_hook::closure$1
                               at /rustc/72fdf913c53dd0e75313ba83e4aa80df3f6e2871/library\std\src\panicking.rs:271
   9:     0x7ffe02a26806 - std::panicking::default_hook
                               at /rustc/72fdf913c53dd0e75313ba83e4aa80df3f6e2871/library\std\src\panicking.rs:298
  10:     0x7ffe074d60fc - memchr
  11:     0x7ffe02a27187 - alloc::boxed::impl$50::call
                               at /rustc/72fdf913c53dd0e75313ba83e4aa80df3f6e2871/library\alloc\src\boxed.rs:2077
  12:     0x7ffe02a27187 - std::panicking::rust_panic_with_hook
                               at /rustc/72fdf913c53dd0e75313ba83e4aa80df3f6e2871/library\std\src\panicking.rs:799
  13:     0x7ffe02a27017 - std::panicking::begin_panic_handler::closure$0
                               at /rustc/72fdf913c53dd0e75313ba83e4aa80df3f6e2871/library\std\src\panicking.rs:664
  14:     0x7ffe02a2450f - std::sys_common::backtrace::__rust_end_short_backtrace<std::panicking::begin_panic_handler::closure_env$0,never$>
                               at /rustc/72fdf913c53dd0e75313ba83e4aa80df3f6e2871/library\std\src\sys_common\backtrace.rs:171
  15:     0x7ffe02a26cc8 - std::panicking::begin_panic_handler
                               at /rustc/72fdf913c53dd0e75313ba83e4aa80df3f6e2871/library\std\src\panicking.rs:652
  16:     0x7ffe02a7e054 - core::panicking::panic_fmt
                               at /rustc/72fdf913c53dd0e75313ba83e4aa80df3f6e2871/library\core\src\panicking.rs:72
  17:     0x7ffe02a7e28e - core::panicking::panic_bounds_check
                               at /rustc/72fdf913c53dd0e75313ba83e4aa80df3f6e2871/library\core\src\panicking.rs:274
  18:     0x7ffe05e22796 - rustc_codegen_ssa[17375fc6d9732a23]::back::link::linker_and_flavor
  19:     0x7ffe05e16d70 - rustc_codegen_ssa[17375fc6d9732a23]::back::link::each_linked_rlib
  20:     0x7ffe05e1167e - rustc_codegen_ssa[17375fc6d9732a23]::back::link::link_binary
  21:     0x7ffe033e4ca6 - <rustc_codegen_llvm[3d446f3b6ccd7211]::LlvmCodegenBackend as rustc_codegen_ssa[17375fc6d9732a23]::traits::backend::CodegenBackend>::link
  22:     0x7ffe033374e9 - <rustc_interface[b17a26a17ab0bfc1]::queries::Linker>::link
  23:     0x7ffe032e58f2 - _LNan_C
  24:     0x7ffe032e256f - _LNan_C
  25:     0x7ffe032ea269 - _LNan_C
  26:     0x7ffe02a3838d - alloc::boxed::impl$48::call_once
                               at /rustc/72fdf913c53dd0e75313ba83e4aa80df3f6e2871/library\alloc\src\boxed.rs:2063
  27:     0x7ffe02a3838d - alloc::boxed::impl$48::call_once
                               at /rustc/72fdf913c53dd0e75313ba83e4aa80df3f6e2871/library\alloc\src\boxed.rs:2063
  28:     0x7ffe02a3838d - std::sys::pal::windows::thread::impl$0::new::thread_start
                               at /rustc/72fdf913c53dd0e75313ba83e4aa80df3f6e2871/library\std\src\sys\pal\windows\thread.rs:52
  29:     0x7ffe714e7614 - BaseThreadInitThunk
  30:     0x7ffe720426b1 - RtlUserThreadStart

error: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: please make sure that you have updated to the latest nightly

note: please attach the file at `C:\AMD\RustProjects\sphene\rustc-ice-2024-06-06T08_35_43-4288.txt` to your bug report

note: compiler flags: --crate-type bin -C embed-bitcode=no -C debuginfo=2 -C incremental=[REDACTED]
note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
error: could not compile `sphene` (bin "sphene")
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
<backtrace>
I dont really understand what to put here. I added "RUST_BACKTRACE=1" but outputs the same as the error message above.
```

</p>
</details>

## File Attachment
[rustc-ice-2024-06-06T08_35_43-4288.txt](https://github.com/user-attachments/files/15612474/rustc-ice-2024-06-06T08_35_43-4288.txt)

### PR DESCRIPTION
**Pull request by lqd**
There are more open issues caused by #124976 than will be fixed by #125493 alone. The beta cut is soon, so let's revert it and buy some time to analyze and fix these issues in our own time.

fixes https://github.com/rust-lang/rust/issues/125474
fixes https://github.com/rust-lang/rust/issues/125484
fixes https://github.com/rust-lang/rust/issues/125646
fixes https://github.com/rust-lang/rust/issues/125707
fixes #126066
fixes #125934
fixes https://github.com/rust-lang/rust/issues/126021

r? @petrochenkov 
@bors p=1

### CODE REVIEW

**Comment by tbu-** [comment]
Nice that you added tests!

**Comment by lqd** [comment]
Only one, though I should probably add the last mcve, that seems doable as an rmake test since ui tests won’t work. The other issues can involve hundreds of crates  so there are no repros unfortunately.

File: tests/run-make/issue-125484-used-dependencies/rmake.rs [hunk 1]
```diff
@@ -0,0 +1,18 @@
+// Non-regression test for issues #125474, #125484, #125646, with the repro taken from #125484. Some
+// queries use "used dependencies" while others use "speculatively loaded dependencies", and an
+// indexing ICE appeared in some cases when these were unexpectedly used in the same context.
+
+// FIXME: this should probably be a UI test instead of a run-make test, but I *cannot* find a way to
+// make compiletest annotations reproduce the ICE with the minimizations from issues #125474 and
+// #125484.
```
Comment (jieyouxu) [inline tests/run-make/issue-125484-used-dependencies/rmake.rs:7]: (UI tests compile the main test file and auxiliary crates with extra flags, especially having to do with library search paths and how the auxiliary crates are linked in and whatnot, so I think it is fine that this stays as a run-make test.)

Comment (lqd) [reply tests/run-make/issue-125484-used-dependencies/rmake.rs:7]: Yeah and it's not clear that these extra flags are what's causing the repro to disappear, so some judicious compile-flags could still work but I don't have the time to look into that at the moment.

Comment (lqd) [reply tests/run-make/issue-125484-used-dependencies/rmake.rs:7]: @jieyouxu actually rmake tests also add an -L flag to rustc's invocations. 

In any case, it's similarly not straightforward to get the #125474 MCVE to ICE _in an rmake test_, I'm not sure what's going on. I'd like to avoid using a makefile.

**Comment by workingjubilee** [comment]
revert during beta week, let's go.
@bors p=7
