### PR TITLE
Resolve associated item bindings by namespace

### LINKED ISSUE #112560: Associated const equality conflicts with associated type equality
I tried this code and it compiled:
```rust
trait Trait2 {}

trait Trait1 {
    const A: u32;
    type A;
}

impl<T: Trait1<A = u32>, const N: usize> Trait2 for [T; N] {}

fn main() {}
```
Then I tried this code and it didn't compile:

```rust
#![feature(associated_const_equality)]

trait Trait2 {}

trait Trait1 {
    const A: u32;
    type A;
}

impl<T: Trait1<A = 12>, const N: usize> Trait2 for [T; N] {}

fn main() {}
```

### Meta

`rustc --version --verbose`:
```
rustc 1.72.0-nightly (37998ab50 2023-06-11)
binary: rustc
commit-hash: 37998ab508d5d9fa0d465d7b535dc673087dda8f
commit-date: 2023-06-11
host: aarch64-apple-darwin
release: 1.72.0-nightly
LLVM version: 16.0.5
```

<details><summary>Backtrace</summary>
<p>

```
error: expected associated type bound, found constant
  --> src/main.rs:10:16
   |
10 | impl<T: Trait1<A = 12>, const N: usize> Trait2 for [T; N] {}
   |                ^^^^^^
   |
note: associated type defined here
  --> src/main.rs:5:5
   |
5  |     type A;
   |     ^^^^^^

error: could not compile `proba2` (bin "proba2") due to previous error
```

</p>
</details>

### Explanation

Rust allows for associated const parameter and associated type parameter to have the same name. So, I expected there would be some way to disambiguate which one I'm referring to when setting the equality constraint but haven't found a way to do so.

This problem is related to [Associated Const Equality](https://github.com/rust-lang/rust/issues/92827)

### PR DESCRIPTION
**Pull request by fmease**
This is the 3rd commit split off from #118360 with tests reblessed (they no longer contain duplicated diags which were caused by 4c0addc80af4666f26d7ad51fe34a0e2dd0b8b74) & slightly adapted (removed supertraits from a UI test, cc #118040).

> * Resolve all assoc item bindings (type, const, fn (feature `return_type_notation`)) by namespace instead of trying to resolve a type first (in the non-RTN case) and falling back to consts afterwards. This is consistent with RTN. E.g., for `Tr<K = {…}>` we now always try to look up assoc consts (this extends to supertrait bounds). This gets rid of assoc tys shadowing assoc consts in assoc item bindings which is undesirable & inconsistent (types and consts live in different namespaces after all)
> * Consolidate the resolution of assoc {ty, const} bindings and RTN (dedup, better diags for RTN)
> * Fix assoc consts being labeled as assoc *types* in several diagnostics 
> * Make a bunch of diagnostics translatable

Fixes #112560 (error → pass).

As discussed
r? @compiler-errors

---

**Addendum**: What I call “associated item bindings” are commonly referred to as “type bindings” for historical reasons. Nowadays, “type bindings” include assoc type bindings, assoc const bindings and RTN (return type notation) which is why I prefer not to use this outdated term.

### CODE REVIEW

File: compiler/rustc_hir_analysis/src/astconv/errors.rs [hunk 1]
```diff
@@ -237,39 +242,101 @@ impl<'o, 'tcx> dyn AstConv<'tcx> + 'o {
...
+                ident.span
+            } else {
+                binding.gen_args.span_ext
+            };
+            Some(lo.between(span.shrink_to_hi()))
+        } else {
+            None
+        };
+
+        // FIXME(associated_const_equality): This has quite a few false positives and negatives.
```
Comment (fmease) [inline compiler/rustc_hir_analysis/src/astconv/errors.rs:305]: (preexisting)

File: compiler/rustc_hir_analysis/src/astconv/mod.rs [hunk 2]
```diff
@@ -2858,3 +2809,11 @@ impl<'o, 'tcx> dyn AstConv<'tcx> + 'o {
         Some(r)
     }
 }
+
+fn assoc_kind_str(kind: ty::AssocKind) -> &'static str {
```
Comment (compiler-errors) [inline compiler/rustc_hir_analysis/src/astconv/mod.rs:2813]: nit: could we use `kind.as_def_kind().descr()` here or something? not blocking

File: tests/ui/associated-consts/assoc-const-eq-missing.stderr [hunk 3]
```diff
@@ -1,20 +1,20 @@
-error[E0220]: associated type `Z` not found for `Foo`
-  --> $DIR/assoc-const-eq-missing.rs:15:16
+error[E0220]: associated constant `Z` not found for `Foo`
+  --> $DIR/assoc-const-eq-missing.rs:14:16
    |
-LL | fn foo1<F: Foo<Z=3>>() {}
-   |                ^ associated type `Z` not found
+LL | fn foo1<F: Foo<Z = 3>>() {}
+   |                ^ help: there is an associated constant with a similar name: `N`
```
Comment (compiler-errors) [inline tests/ui/associated-consts/assoc-const-eq-missing.stderr:5]: this is awesome

File: tests/ui/associated-consts/shadowed-const.stderr [hunk 4]
```diff
@@ -1,8 +1,14 @@
-error: found associated const `BAR` when type was expected
-  --> $DIR/shadowed-const.rs:19:14
+error: expected type, found constant
+  --> $DIR/shadowed-const.rs:19:20
    |
 LL |   const QUX: Self::BAR;
-   |              ^^^^^^^^^
+   |                    ^^^ unexpected constant
+   |
+note: the associated constant is defined here
```
Comment (compiler-errors) [inline tests/ui/associated-consts/shadowed-const.stderr:7]: :D

**Review by compiler-errors — APPROVED** [review]
:100: 

I just had one question about hygeine

r=me though if it's something unfixable at the moment

File: compiler/rustc_hir_analysis/src/astconv/bounds.rs [hunk 5]
```diff
@@ -302,18 +292,11 @@ impl<'tcx> dyn AstConv<'tcx> + '_ {
...
-            find_item_of_kind(ty::AssocKind::Fn)
-        } else {
-            find_item_of_kind(ty::AssocKind::Type)
-                .or_else(|| find_item_of_kind(ty::AssocKind::Const))
-        }
-        .expect("missing associated type");
+        let assoc_item = tcx
+            .associated_items(candidate.def_id())
+            .filter_by_name_unhygienic(assoc_ident.name)
+            .find(|i| i.kind == assoc_kind && i.ident(tcx).normalize_to_macros_2_0() == assoc_ident)
```
[the remark this answers is not in the document]
Comment (fmease) [reply compiler/rustc_hir_analysis/src/astconv/bounds.rs:298]: `find_by_name_and_kind` is semantically identical to the code above but this version is slightly faster in theory since above we only normalize the LHS instead of normalizing both sides. `assoc_ident` has already been normalized above in `adjust_ident_and_get_scope`, so no need to do it again (`adjust_ident_and_get_scope` also returns the `def_scope` which is used later in `is_accessible_from`).

[the remark this answers is not in the document]
Comment (compiler-errors) [reply compiler/rustc_hir_analysis/src/astconv/bounds.rs:298]: pls note this
