### PR TITLE
Unify rustc and rustdoc parsing of `cfg()`

### LINKED ISSUE #84437: Rustdoc and rustc accept different `cfg` syntax
I tried this code:

```rust
#![feature(doc_cfg)]
#[doc(cfg(x, y))]
fn bar() {}
```

I expected to see this happen: An error, to match the behavior on `#[cfg(x, y)]`:

```
error: multiple `cfg` predicates are specified
 --> cfg2.rs:1:10
  |
1 | #[cfg(x, y)]
  |          ^
```

Instead, this happened: Rustdoc silently accepts the code.

Relevant code: https://github.com/rust-lang/rust/blob/88b99dec2a4d103b8153ca9300bf0fbebdf65bda/src/librustdoc/clean/cfg.rs#L62
I think the relevant rustc code is https://github.com/rust-lang/rust/blob/88b99dec2a4d103b8153ca9300bf0fbebdf65bda/compiler/rustc_expand/src/config.rs#L455

### Meta

`rustdoc --version`: rustdoc 1.53.0-nightly (392ba2ba1 2021-04-17)

### PR DESCRIPTION
**Pull request by jyn514**
This extracts a new `parse_cfg` function that's used between both.

- Treat `#[doc(cfg(x), cfg(y))]` the same as `#[doc(cfg(x)]
  #[doc(cfg(y))]`. Previously it would be completely ignored.
- Treat `#[doc(inline, cfg(x))]` the same as `#[doc(inline)]
  #[doc(cfg(x))]`. Previously, the cfg would be ignored.
- Pass the cfg predicate through to rustc_expand to be validated

Technically this is a breaking change, but doc_cfg is still nightly so I don't think it matters.

Fixes https://github.com/rust-lang/rust/issues/84437.

r? @petrochenkov

### CODE REVIEW

**Comment by jyn514** [comment]
cc @Nemo157

**Comment by petrochenkov** [comment]
FWIW, there's one more place with similar logic - `fn parse_cfgspecs`, not sure whether some code can be shared with it or not.

**Comment by jyn514** [comment]
> FWIW, there's one more place with similar logic - fn parse_cfgspecs, not sure whether some code can be shared with it or not.

I don't think so - it only allows idents, not full lists:
```rust
                        match &meta_item.kind {
                            MetaItemKind::List(..) => {
                                error!(r#"expected `key` or `key="value"`"#);
                            }
                            MetaItemKind::NameValue(lit) if !lit.kind.is_str() => {
                                error!("argument value must be a string");
                            }
                            MetaItemKind::NameValue(..) | MetaItemKind::Word => {
                                let ident = meta_item.ident().expect("multi-segment cfg key");
                                return (ident.name, meta_item.value_str());
                            }
                        }
```
and at that point it's only a few lines anyway.

**Comment by jyn514** [comment]
Ok, this is ready for review.

**Comment by jyn514** [comment]
cc @Nemo157 since this now allows `#[doc(cfg(x), cfg(y))]` (but we already chatted and he's fine with it).

File: compiler/rustc_expand/src/config.rs [hunk 1]
```diff
@@ -532,6 +513,32 @@ impl<'a> StripUnconfigured<'a> {
...
 
+pub fn parse_cfg<'a>(meta_item: &'a MetaItem, sess: &Session) -> Option<&'a MetaItem> {
+    let error = |span, msg, suggestion: &str| {
+        let mut err = sess.parse_sess.span_diagnostic.struct_span_err(span, msg);
+        if !suggestion.is_empty() {
+            err.span_suggestion(
+                span,
+                "expected syntax is",
+                suggestion.into(),
+                Applicability::HasPlaceholders,
```
Comment (jyn514) [inline compiler/rustc_expand/src/config.rs:524]: Note that this changed from MaybeCorrect to HasPlaceholders. I think that's the right change, this is only called for `cfg(/* predicate */)`.

File: compiler/rustc_expand/src/config.rs [hunk 2]
```diff
@@ -464,30 +464,11 @@ impl<'a> StripUnconfigured<'a> {
...
-            let error = |span, msg, suggestion: &str| {
-                let mut err = self.sess.parse_sess.span_diagnostic.struct_span_err(span, msg);
-                if !suggestion.is_empty() {
-                    err.span_suggestion(
-                        span,
-                        "expected syntax is",
-                        suggestion.into(),
-                        Applicability::MaybeIncorrect,
-                    );
+            match parse_cfg(&meta_item, &self.sess) {
```
Comment (petrochenkov) [inline compiler/rustc_expand/src/config.rs:467]:
```suggestion
            parse_cfg(&meta_item, &self.sess).map_or(true, |meta_item| attr::cfg_matches(&meta_item, &self.sess.parse_sess, self.features))
```

**Comment by petrochenkov** [comment]
r=me with https://github.com/rust-lang/rust/pull/84442#discussion_r625213379 addressed.
