### PR TITLE
Fix indices and remove some unwraps in arg mismatch algorithm

### LINKED ISSUE #97484: Broke rustc while refactoring method args in async yolo code
This happens with the latest nightly 2022-05-27 and 2022-05-14

### Code

https://github.com/gilescope/dotsamatown/tree/broke-rustc

`fn process_extrisic` had 6 args and I was de-yoloing the code to have only 4 args when rustc got the right hump.

src/datasource.rs line 810, if I change that call to process_extrinsic to have the right number (and type) of arguments then rustc gets happy again:
```rust
                                let entity = process_extrisic(&relay_id,
                                      ex_slice,&extrinsic, DotUrl{ extrinsic: Some(i as u32), ..block_doturl.clone()}).await;
```
Sorry my yolo code broke rustc! I suspect it's pretty obvious what's broken. I don't think this is a subtle thing though I guess it probably is the fact that it's an async fn that helps brake it.

### Error output

```
    Checking bevy_app v0.1.0 (/home/gilescope/git/bevy_webgl_template)
warning: unused import: `FlyCam`
  --> src/movement.rs:16:19
   |
16 | use bevy_flycam::{FlyCam, MovementSettings};
   |                   ^^^^^^
   |
   = note: `#[warn(unused_imports)]` on by default

warning: unused import: `subxt::ClientBuilder`
  --> src/main.rs:30:5
   |
30 | use subxt::ClientBuilder;
   |     ^^^^^^^^^^^^^^^^^^^^

thread 'rustc' panicked at 'called `Option::unwrap()` on a `None` value', compiler/rustc_typeck/src/check/fn_ctxt/checks.rs:433:78
stack backtrace:
   0: rust_begin_unwind
             at /rustc/490324f7b29d5f1a1e063a563045d790091ed639/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/490324f7b29d5f1a1e063a563045d790091ed639/library/core/src/panicking.rs:142:14
   2: core::panicking::panic
             at /rustc/490324f7b29d5f1a1e063a563045d790091ed639/library/core/src/panicking.rs:48:5
   3: <alloc::vec::drain_filter::DrainFilter<rustc_typeck::check::fn_ctxt::arg_matrix::Error, <rustc_typeck::check::fn_ctxt::FnCtxt>::check_argument_types::{closure#4}> as core::ops::drop::Drop>::drop
   4: <rustc_typeck::check::fn_ctxt::FnCtxt>::check_argument_types
   5: <rustc_typeck::check::fn_ctxt::FnCtxt>::check_call
   6: <rustc_typeck::check::fn_ctxt::FnCtxt>::check_expr_kind
   7: <rustc_typeck::check::fn_ctxt::FnCtxt>::check_argument_types
   8: <rustc_typeck::check::fn_ctxt::FnCtxt>::check_call
   9: <rustc_typeck::check::fn_ctxt::FnCtxt>::check_expr_kind
  10: <rustc_typeck::check::fn_ctxt::FnCtxt>::check_expr_with_expectation
  11: <rustc_typeck::check::fn_ctxt::FnCtxt>::check_match
  12: <rustc_typeck::check::fn_ctxt::FnCtxt>::check_expr_kind
  13: <rustc_typeck::check::fn_ctxt::FnCtxt>::check_expr_with_expectation
  14: <rustc_typeck::check::fn_ctxt::FnCtxt>::check_stmt
  15: <rustc_typeck::check::fn_ctxt::FnCtxt>::check_block_with_expected
  16: <rustc_typeck::check::fn_ctxt::FnCtxt>::check_expr_kind
  17: <rustc_typeck::check::fn_ctxt::FnCtxt>::check_expr_with_expectation
  18: <rustc_typeck::check::fn_ctxt::FnCtxt>::check_expr_kind
  19: <rustc_typeck::check::fn_ctxt::FnCtxt>::check_expr_with_expectation
  20: <rustc_typeck::check::fn_ctxt::FnCtxt>::check_block_with_expected
  21: <rustc_typeck::check::fn_ctxt::FnCtxt>::check_expr_kind
  22: <rustc_typeck::check::fn_ctxt::FnCtxt>::check_expr_with_expectation
  23: <rustc_typeck::check::fn_ctxt::FnCtxt>::check_match
  24: <rustc_typeck::check::fn_ctxt::FnCtxt>::check_expr_kind
  25: <rustc_typeck::check::fn_ctxt::FnCtxt>::check_expr_with_expectation
  26: <rustc_typeck::check::fn_ctxt::FnCtxt>::check_stmt
  27: <rustc_typeck::check::fn_ctxt::FnCtxt>::check_block_with_expected
  28: <rustc_typeck::check::fn_ctxt::FnCtxt>::check_expr_kind
  29: <rustc_typeck::check::fn_ctxt::FnCtxt>::check_expr_with_expectation
  30: <rustc_typeck::check::fn_ctxt::FnCtxt>::check_match
  31: <rustc_typeck::check::fn_ctxt::FnCtxt>::check_expr_kind
  32: <rustc_typeck::check::fn_ctxt::FnCtxt>::check_expr_with_expectation
  33: <rustc_typeck::check::fn_ctxt::FnCtxt>::check_expr_kind
  34: <rustc_typeck::check::fn_ctxt::FnCtxt>::check_expr_with_expectation
  35: <rustc_typeck::check::fn_ctxt::FnCtxt>::check_stmt
  36: <rustc_typeck::check::fn_ctxt::FnCtxt>::check_block_with_expected
  37: <rustc_typeck::check::fn_ctxt::FnCtxt>::check_expr_kind
  38: <rustc_typeck::check::fn_ctxt::FnCtxt>::check_expr_with_expectation
  39: <rustc_typeck::check::fn_ctxt::FnCtxt>::check_expr_kind
  40: <rustc_typeck::check::fn_ctxt::FnCtxt>::check_expr_with_expectation
  41: <rustc_typeck::check::fn_ctxt::FnCtxt>::check_block_with_expected
  42: <rustc_typeck::check::fn_ctxt::FnCtxt>::check_expr_kind
  43: <rustc_typeck::check::fn_ctxt::FnCtxt>::check_expr_with_expectation
  44: <rustc_typeck::check::fn_ctxt::FnCtxt>::check_expr_kind
  45: <rustc_typeck::check::fn_ctxt::FnCtxt>::check_expr_with_expectation
  46: <rustc_typeck::check::fn_ctxt::FnCtxt>::check_block_with_expected
  47: <rustc_typeck::check::fn_ctxt::FnCtxt>::check_expr_kind
  48: <rustc_typeck::check::fn_ctxt::FnCtxt>::check_expr_with_expectation
  49: <rustc_typeck::check::fn_ctxt::FnCtxt>::check_block_with_expected
  50: <rustc_typeck::check::fn_ctxt::FnCtxt>::check_expr_kind
  51: <rustc_typeck::check::fn_ctxt::FnCtxt>::check_expr_with_expectation
  52: <rustc_typeck::check::fn_ctxt::FnCtxt>::check_expr_kind
  53: <rustc_typeck::check::fn_ctxt::FnCtxt>::check_expr_with_expectation
  54: <rustc_typeck::check::fn_ctxt::FnCtxt>::check_stmt
  55: <rustc_typeck::check::fn_ctxt::FnCtxt>::check_block_with_expected
  56: <rustc_typeck::check::fn_ctxt::FnCtxt>::check_expr_kind
  57: <rustc_typeck::check::fn_ctxt::FnCtxt>::check_expr_with_expectation
  58: <rustc_typeck::check::fn_ctxt::FnCtxt>::check_expr_kind
  59: <rustc_typeck::check::fn_ctxt::FnCtxt>::check_expr_with_expectation
  60: <rustc_typeck::check::fn_ctxt::FnCtxt>::check_block_with_expected
  61: <rustc_typeck::check::fn_ctxt::FnCtxt>::check_expr_kind
  62: <rustc_typeck::check::fn_ctxt::FnCtxt>::check_expr_with_expectation
  63: <rustc_typeck::check::fn_ctxt::FnCtxt>::check_block_with_expected
  64: <rustc_typeck::check::fn_ctxt::FnCtxt>::check_expr_kind
  65: <rustc_typeck::check::fn_ctxt::FnCtxt>::check_expr_with_expectation
  66: <rustc_typeck::check::fn_ctxt::FnCtxt>::check_expr_kind
  67: <rustc_typeck::check::fn_ctxt::FnCtxt>::check_expr_with_expectation
  68: <rustc_typeck::check::fn_ctxt::FnCtxt>::check_stmt
  69: <rustc_typeck::check::fn_ctxt::FnCtxt>::check_block_with_expected
  70: <rustc_typeck::check::fn_ctxt::FnCtxt>::check_expr_kind
  71: <rustc_typeck::check::fn_ctxt::FnCtxt>::check_expr_with_expectation
  72: <rustc_typeck::check::fn_ctxt::FnCtxt>::check_expr_kind
  73: <rustc_typeck::check::fn_ctxt::FnCtxt>::check_expr_with_expectation
  74: <rustc_typeck::check::fn_ctxt::FnCtxt>::check_block_with_expected
  75: <rustc_typeck::check::fn_ctxt::FnCtxt>::check_expr_kind
  76: <rustc_typeck::check::fn_ctxt::FnCtxt>::check_expr_with_expectation
  77: rustc_typeck::check::check::check_fn
  78: <rustc_typeck::check::fn_ctxt::FnCtxt>::check_expr_closure
  79: <rustc_typeck::check::fn_ctxt::FnCtxt>::check_expr_kind
  80: <rustc_typeck::check::fn_ctxt::FnCtxt>::check_argument_types
  81: <rustc_typeck::check::fn_ctxt::FnCtxt>::check_call
  82: <rustc_typeck::check::fn_ctxt::FnCtxt>::check_expr_kind
  83: <rustc_typeck::check::fn_ctxt::FnCtxt>::check_expr_with_expectation
  84: rustc_typeck::check::check::check_fn
  85: <rustc_infer::infer::InferCtxtBuilder>::enter::<&rustc_middle::ty::context::TypeckResults, <rustc_typeck::check::inherited::InheritedBuilder>::enter<rustc_typeck::check::typeck_with_fallback<rustc_typeck::check::typeck::{closure#0}>::{closure#1}, &rustc_middle::ty::context::TypeckResults>::{closure#0}>
  86: rustc_typeck::check::typeck
  87: <rustc_query_system::dep_graph::graph::DepGraph<rustc_middle::dep_graph::dep_node::DepKind>>::with_task::<rustc_middle::ty::context::TyCtxt, rustc_span::def_id::LocalDefId, &rustc_middle::ty::context::TypeckResults>
  88: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::plumbing::QueryCtxt, rustc_query_system::query::caches::DefaultCache<rustc_span::def_id::LocalDefId, &rustc_middle::ty::context::TypeckResults>>
  89: <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::typeck
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.63.0-nightly (490324f7b 2022-05-26) running on x86_64-unknown-linux-gnu

note: compiler flags: --crate-type bin -C opt-level=1 -C embed-bitcode=no -C debuginfo=1 -C debug-assertions=on -C linker=clang -C incremental -Z share-generics=y

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [typeck] type-checking `datasource::watch_blocks`
#1 [mir_built] building MIR for `datasource::watch_blocks`
#2 [unsafety_check_result] unsafety-checking `datasource::watch_blocks`
#3 [mir_const] processing MIR for `datasource::watch_blocks`
#4 [mir_promoted] processing `datasource::watch_blocks`
#5 [mir_borrowck] borrow-checking `datasource::watch_blocks`
#6 [type_of] computing type of `datasource::watch_blocks::{opaque#0}`
#7 [check_mod_item_types] checking item types in module `datasource`
#8 [analysis] running analysis passes on this crate
end of query stack
```
</p>
</details>

### PR DESCRIPTION
**Pull request by compiler-errors**
This is a more conservative fix than #97542, addressing some indices which were used incorectly and unwraps which are bound to panic (e.g. when the provided and expected arg counts differ). Beta nominating this as it's quite easy to cause ICEs -- I wrote a fuzzer and found hundreds of examples of ICEs.

cc @jackh726 as author of #92364, and @estebank as reviewer of that PR.
fixes #97484
r? @jackh726 this should be _much_ easier to review than the other PR :sweat_smile:

### CODE REVIEW

File: compiler/rustc_typeck/src/check/fn_ctxt/checks.rs [hunk 1]
```diff
@@ -445,16 +445,14 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
             let found_errors = !errors.is_empty();
 
             errors.drain_filter(|error| {
-                let Error::Invalid(input_idx, arg_idx, Compatibility::Incompatible(error)) = error else { return false };
+                let Error::Invalid(input_idx, arg_idx, Compatibility::Incompatible(Some(e))) = error else { return false };
                 let expected_ty = expected_input_tys[*arg_idx];
-                let provided_ty = final_arg_types[*input_idx].map(|ty| ty.0).unwrap();
+                let provided_ty = final_arg_types[*input_idx].map(|ty| ty.0).unwrap_or_else(|| tcx.ty_error());
```
Comment (compiler-errors) [inline compiler/rustc_typeck/src/check/fn_ctxt/checks.rs:450]: `final_arg_types` is a vector of length `provided_args.len()`, but is only populated with `Some` (by `demand_compatible`) up to `expected_input_tys.len()`. This unwrap was panicking in a bunch of cases.

File: compiler/rustc_typeck/src/check/fn_ctxt/checks.rs [hunk 2]
```diff
@@ -888,14 +895,14 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
                     Error::Permutation(args) => {
                         for (dst_arg, dest_input) in args {
                             let expected_ty =
-                                self.resolve_vars_if_possible(expected_input_tys[dest_input]);
-                            let provided_ty = if let Some((ty, _)) = final_arg_types[dst_arg] {
-                                format!(",found `{}`", ty)
+                                self.resolve_vars_if_possible(expected_input_tys[dst_arg]);
```
Comment (compiler-errors) [inline compiler/rustc_typeck/src/check/fn_ctxt/checks.rs:898]: I think these were swapped -- `dst_arg` is an "expected argument"-like index, and `dst_input` is a "provided argument"-like index.

File: compiler/rustc_typeck/src/check/fn_ctxt/checks.rs [hunk 3]
```diff
@@ -585,7 +583,9 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
                 )) = errors.iter().next()
                 {
                     let expected_ty = expected_input_tys[*arg_idx];
-                    let provided_ty = final_arg_types[*arg_idx].map(|ty| ty.0).unwrap();
+                    let provided_ty = final_arg_types[*input_idx]
```
Comment (compiler-errors) [inline compiler/rustc_typeck/src/check/fn_ctxt/checks.rs:586]: Should be using `input_idx`. Not sure if this is "correct" (though I think it is), but regardless, if there are more expected args than provided args, then this might be out of bounds.

File: compiler/rustc_typeck/src/check/fn_ctxt/checks.rs [hunk 4]
```diff
@@ -674,8 +678,11 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
                         self.emit_coerce_suggestions(
                             &mut err,
                             &provided_args[input_idx],
-                            final_arg_types[input_idx].map(|ty| ty.0).unwrap(),
-                            final_arg_types[input_idx].map(|ty| ty.1).unwrap(),
+                            provided_ty,
+                            // FIXME(compiler-errors): expected_ty?
+                            final_arg_types[input_idx]
```
Comment (compiler-errors) [inline compiler/rustc_typeck/src/check/fn_ctxt/checks.rs:683]: This should actually probably be `expected_ty`, but this will just provide a bad suggestion, and not panic.

File: src/test/ui/argument-suggestions/issue-97484.stderr [hunk 5]
```diff
@@ -0,0 +1,27 @@
...
+note: function defined here
+  --> $DIR/issue-97484.rs:9:4
+   |
+LL | fn foo(a: &A, d: D, e: &E, g: G) {}
+   |    ^^^ -----  ----  -----  ----
+help: consider removing the ``
+   |
+LL -     foo(&&A, B, C, D, E, F, G);
+LL +     foo(&&A, B, C, D, E, F, G);
+   |
```
Comment (estebank) [inline src/test/ui/argument-suggestions/issue-97484.stderr:19]: This is buggy (which, fair, you're sidestepping the ICE). Given that after this we suggest removing some args, it tells me that we can better handle this case to not emit it at all.

File: src/test/ui/argument-suggestions/issue-97484.stderr [hunk 6]
```diff
@@ -0,0 +1,27 @@
...
+   |    ^^^ -----  ----  -----  ----
+help: consider removing the ``
+   |
+LL -     foo(&&A, B, C, D, E, F, G);
+LL +     foo(&&A, B, C, D, E, F, G);
+   | 
+help: remove the extra arguments
+   |
+LL |     foo(&&A, D, {&E}, G);
+   |     ~~~~~~~~~~~~~~~~~~~~
```
Comment (estebank) [inline src/test/ui/argument-suggestions/issue-97484.stderr:23]: This tells me that we should teach the suggestion to add and remove borrows as well :)

File: compiler/rustc_typeck/src/check/fn_ctxt/checks.rs (hunk 4 above)
Comment (estebank) [reply compiler/rustc_typeck/src/check/fn_ctxt/checks.rs:683]: What about changing `emit_coerce_suggestions` to take an `Option` here instead (and make it not emit the invalid suggestion when it is `None`)?

File: src/test/ui/argument-suggestions/issue-97484.stderr (hunk 6 above)
Comment (compiler-errors) [reply src/test/ui/argument-suggestions/issue-97484.stderr:23]: This should fall out of coercion suggestions which we attempt when we see an "invalid" argument.

File: src/test/ui/argument-suggestions/issue-97484.stderr (hunk 5 above)
Comment (compiler-errors) [reply src/test/ui/argument-suggestions/issue-97484.stderr:19]: I actually know how to fix this one, and I think I fixed it on the more extensive fix.

Comment (compiler-errors) [reply src/test/ui/argument-suggestions/issue-97484.stderr:19]: The technical explanation is that we're trying to coerce `&&A` into `&&A`, and the current suggestion logic goes "ah yes, dereference it zero times" (well, actually, remove `&` zero times).

File: compiler/rustc_typeck/src/check/fn_ctxt/checks.rs (hunk 4 above)
Comment (compiler-errors) [reply compiler/rustc_typeck/src/check/fn_ctxt/checks.rs:683]: but emit_coerce_suggestions can't do anything if we don't have a target type to coerce to, right?

**Comment by apiraino** [comment]
Beta backport not accepted in favor of #97701. T-compiler [Zulip discussion](https://rust-lang.zulipchat.com/#narrow/stream/238009-t-compiler.2Fmeetings/topic/.5Bweekly.5D.202022-06-02/near/284752327), especially around [this comment](https://rust-lang.zulipchat.com/#narrow/stream/238009-t-compiler.2Fmeetings/topic/.5Bweekly.5D.202022-06-02/near/284755594).

@rustbot label -beta-nominated
