### PR TITLE
Fix ICE when opaque captures a duplicated/invalid lifetime

### LINKED ISSUE #132766: [ICE]: cannot convert `'a/#3` to a region vid
### Code

```Rust
struct Foo;
impl Foo {
    #[allow(dead_code)]
    fn foo(self) {
        panic!("wrong method!")
    }
}
trait Trait {
    fn foo(self);
}
impl<'a, 'b, 'c> Trait for &'a &'b &'c Foo {
    async fn pass2<'a, 'b, 'c>(self) {}
}
fn main() {
    let x = &(&(&Foo));
    x.foo();
}

```

### Meta

`rustc --version --verbose`:
```
rustc 1.84.0-nightly (b91a3a056 2024-11-07)
binary: rustc
commit-hash: b91a3a05609a46f73d23e0995ae7ebb4a4f429a5
commit-date: 2024-11-07
host: x86_64-unknown-linux-gnu
release: 1.84.0-nightly
LLVM version: 19.1.3
```

### Error output

```
error[E0670]: `async fn` is not permitted in Rust 2015
  --> mutant.rs:12:5
   |
12 |     async fn pass2<'a, 'b, 'c>(self) {}
   |     ^^^^^ to use `async fn`, switch to Rust 2018 or later
   |
   = help: pass `--edition 2021` to `rustc`
   = note: for more on editions, read https://doc.rust-lang.org/edition-guide

error[E0496]: lifetime name `'a` shadows a lifetime name that is already in scope
  --> mutant.rs:12:20
   |
11 | impl<'a, 'b, 'c> Trait for &'a &'b &'c Foo {
   |      -- first declared here
12 |     async fn pass2<'a, 'b, 'c>(self) {}
   |                    ^^ lifetime `'a` already in scope

error[E0496]: lifetime name `'b` shadows a lifetime name that is already in scope
  --> mutant.rs:12:24
   |
11 | impl<'a, 'b, 'c> Trait for &'a &'b &'c Foo {
   |          -- first declared here
12 |     async fn pass2<'a, 'b, 'c>(self) {}
   |                        ^^ lifetime `'b` already in scope

error[E0496]: lifetime name `'c` shadows a lifetime name that is already in scope
  --> mutant.rs:12:28
   |
11 | impl<'a, 'b, 'c> Trait for &'a &'b &'c Foo {
   |              -- first declared here
12 |     async fn pass2<'a, 'b, 'c>(self) {}
   |                            ^^ lifetime `'c` already in scope

error[E0407]: method `pass2` is not a member of trait `Trait`
  --> mutant.rs:12:5
   |
12 |     async fn pass2<'a, 'b, 'c>(self) {}
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ not a member of trait `Trait`

error[E0046]: not all trait items implemented, missing: `foo`
  --> mutant.rs:11:1
   |
9  |     fn foo(self);
   |     ------------- `foo` from trait
10 | }
11 | impl<'a, 'b, 'c> Trait for &'a &'b &'c Foo {
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ missing `foo` in implementation

error: internal compiler error: compiler/rustc_borrowck/src/universal_regions.rs:904:36: cannot convert `'a/#3` to a region vid

thread 'rustc' panicked at compiler/rustc_borrowck/src/universal_regions.rs:904:36:
Box<dyn Any>
stack backtrace:
   0:     0x7faaf585517a - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::hfadad24fb33e3d1a
   1:     0x7faaf60040a6 - core::fmt::write::h42d25fbda60cd99f
   2:     0x7faaf73c3351 - std::io::Write::write_fmt::hc2819193e80b365e
   3:     0x7faaf5854fd2 - std::sys::backtrace::BacktraceLock::print::h9450230402d77664
   4:     0x7faaf58574d6 - std::panicking::default_hook::{{closure}}::h739047d4d787c596
   5:     0x7faaf5857320 - std::panicking::default_hook::h203d1229480f37a5
   6:     0x7faaf48d2269 - std[56fe22ad9ea837fd]::panicking::update_hook::<alloc[b5641001d343df5f]::boxed::Box<rustc_driver_impl[945e9afaf49c7d35]::install_ice_hook::{closure#0}>>::{closure#0}
   7:     0x7faaf5857be8 - std::panicking::rust_panic_with_hook::h657fdcc17f7e2546
   8:     0x7faaf490c191 - std[56fe22ad9ea837fd]::panicking::begin_panic::<rustc_errors[43c84716ac990581]::ExplicitBug>::{closure#0}
   9:     0x7faaf48ff166 - std[56fe22ad9ea837fd]::sys::backtrace::__rust_end_short_backtrace::<std[56fe22ad9ea837fd]::panicking::begin_panic<rustc_errors[43c84716ac990581]::ExplicitBug>::{closure#0}, !>
  10:     0x7faaf48feefe - std[56fe22ad9ea837fd]::panicking::begin_panic::<rustc_errors[43c84716ac990581]::ExplicitBug>
  11:     0x7faaf4915e71 - <rustc_errors[43c84716ac990581]::diagnostic::BugAbort as rustc_errors[43c84716ac990581]::diagnostic::EmissionGuarantee>::emit_producing_guarantee
  12:     0x7faaf4f8f2c3 - rustc_middle[f0eb6ba890d0a9bb]::util::bug::opt_span_bug_fmt::<rustc_span[db86d96c2ae2e3a4]::span_encoding::Span>::{closure#0}
  13:     0x7faaf4f758ba - rustc_middle[f0eb6ba890d0a9bb]::ty::context::tls::with_opt::<rustc_middle[f0eb6ba890d0a9bb]::util::bug::opt_span_bug_fmt<rustc_span[db86d96c2ae2e3a4]::span_encoding::Span>::{closure#0}, !>::{closure#0}
  14:     0x7faaf4f7574b - rustc_middle[f0eb6ba890d0a9bb]::ty::context::tls::with_context_opt::<rustc_middle[f0eb6ba890d0a9bb]::ty::context::tls::with_opt<rustc_middle[f0eb6ba890d0a9bb]::util::bug::opt_span_bug_fmt<rustc_span[db86d96c2ae2e3a4]::span_encoding::Span>::{closure#0}, !>::{closure#0}, !>
  15:     0x7faaf31e7300 - rustc_middle[f0eb6ba890d0a9bb]::util::bug::bug_fmt
  16:     0x7faaf75c2ce0 - <rustc_borrowck[de200e79d11a1023]::universal_regions::UniversalRegionIndices>::to_region_vid.cold
  17:     0x7faaf6055b14 - <rustc_borrowck[de200e79d11a1023]::universal_regions::UniversalRegionIndices>::fold_to_region_vids::<rustc_type_ir[8408d34320f8a6fb]::binder::Binder<rustc_middle[f0eb6ba890d0a9bb]::ty::context::TyCtxt, rustc_type_ir[8408d34320f8a6fb]::ty_kind::FnSig<rustc_middle[f0eb6ba890d0a9bb]::ty::context::TyCtxt>>>::{closure#0}
  18:     0x7faaf6051924 - <&rustc_middle[f0eb6ba890d0a9bb]::ty::list::RawList<(), rustc_middle[f0eb6ba890d0a9bb]::ty::generic_args::GenericArg> as rustc_type_ir[8408d34320f8a6fb]::fold::TypeFoldable<rustc_middle[f0eb6ba890d0a9bb]::ty::context::TyCtxt>>::try_fold_with::<rustc_middle[f0eb6ba890d0a9bb]::ty::fold::RegionFolder>
  19:     0x7faaf60527e4 - <rustc_middle[f0eb6ba890d0a9bb]::ty::Ty as rustc_type_ir[8408d34320f8a6fb]::fold::TypeSuperFoldable<rustc_middle[f0eb6ba890d0a9bb]::ty::context::TyCtxt>>::try_super_fold_with::<rustc_middle[f0eb6ba890d0a9bb]::ty::fold::RegionFolder>
  20:     0x7faaf6051da7 - <&rustc_middle[f0eb6ba890d0a9bb]::ty::list::RawList<(), rustc_middle[f0eb6ba890d0a9bb]::ty::Ty> as rustc_type_ir[8408d34320f8a6fb]::fold::TypeFoldable<rustc_middle[f0eb6ba890d0a9bb]::ty::context::TyCtxt>>::try_fold_with::<rustc_middle[f0eb6ba890d0a9bb]::ty::fold::RegionFolder>
  21:     0x7faaf70b3648 - rustc_borrowck[de200e79d11a1023]::do_mir_borrowck
  22:     0x7faaf70b228a - rustc_query_impl[1357963d8dd30e8b]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[1357963d8dd30e8b]::query_impl::mir_borrowck::dynamic_query::{closure#2}::{closure#0}, rustc_middle[f0eb6ba890d0a9bb]::query::erase::Erased<[u8; 8usize]>>
  23:     0x7faaf6723681 - rustc_query_system[887bb79932b1d8c1]::query::plumbing::try_execute_query::<rustc_query_impl[1357963d8dd30e8b]::DynamicConfig<rustc_query_system[887bb79932b1d8c1]::query::caches::VecCache<rustc_span[db86d96c2ae2e3a4]::def_id::LocalDefId, rustc_middle[f0eb6ba890d0a9bb]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[1357963d8dd30e8b]::plumbing::QueryCtxt, false>
  24:     0x7faaf672318d - rustc_query_impl[1357963d8dd30e8b]::query_impl::mir_borrowck::get_query_non_incr::__rust_end_short_backtrace
  25:     0x7faaf69cc8f3 - rustc_middle[f0eb6ba890d0a9bb]::query::plumbing::query_get_at::<rustc_query_system[887bb79932b1d8c1]::query::caches::VecCache<rustc_span[db86d96c2ae2e3a4]::def_id::LocalDefId, rustc_middle[f0eb6ba890d0a9bb]::query::erase::Erased<[u8; 8usize]>>>
  26:     0x7faaf713b05e - rustc_hir_analysis[af6e6fecb0b5810e]::collect::type_of::type_of_opaque
  27:     0x7faaf713aed1 - rustc_query_impl[1357963d8dd30e8b]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[1357963d8dd30e8b]::query_impl::type_of_opaque::dynamic_query::{closure#2}::{closure#0}, rustc_middle[f0eb6ba890d0a9bb]::query::erase::Erased<[u8; 8usize]>>
  28:     0x7faaf6023bb6 - rustc_query_system[887bb79932b1d8c1]::query::plumbing::try_execute_query::<rustc_query_impl[1357963d8dd30e8b]::DynamicConfig<rustc_query_system[887bb79932b1d8c1]::query::caches::DefIdCache<rustc_middle[f0eb6ba890d0a9bb]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[1357963d8dd30e8b]::plumbing::QueryCtxt, false>
  29:     0x7faaf72137f5 - rustc_query_impl[1357963d8dd30e8b]::query_impl::type_of_opaque::get_query_non_incr::__rust_end_short_backtrace
  30:     0x7faaf64f6540 - rustc_middle[f0eb6ba890d0a9bb]::query::plumbing::query_get_at::<rustc_query_system[887bb79932b1d8c1]::query::caches::DefIdCache<rustc_middle[f0eb6ba890d0a9bb]::query::erase::Erased<[u8; 8usize]>>>
  31:     0x7faaf318f449 - rustc_hir_analysis[af6e6fecb0b5810e]::collect::type_of::type_of
  32:     0x7faaf6024ef2 - rustc_query_impl[1357963d8dd30e8b]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[1357963d8dd30e8b]::query_impl::type_of::dynamic_query::{closure#2}::{closure#0}, rustc_middle[f0eb6ba890d0a9bb]::query::erase::Erased<[u8; 8usize]>>
  33:     0x7faaf6023bb6 - rustc_query_system[887bb79932b1d8c1]::query::plumbing::try_execute_query::<rustc_query_impl[1357963d8dd30e8b]::DynamicConfig<rustc_query_system[887bb79932b1d8c1]::query::caches::DefIdCache<rustc_middle[f0eb6ba890d0a9bb]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[1357963d8dd30e8b]::plumbing::QueryCtxt, false>
  34:     0x7faaf6023767 - rustc_query_impl[1357963d8dd30e8b]::query_impl::type_of::get_query_non_incr::__rust_end_short_backtrace
  35:     0x7faaf64f6540 - rustc_middle[f0eb6ba890d0a9bb]::query::plumbing::query_get_at::<rustc_query_system[887bb79932b1d8c1]::query::caches::DefIdCache<rustc_middle[f0eb6ba890d0a9bb]::query::erase::Erased<[u8; 8usize]>>>
  36:     0x7faaf7149109 - rustc_hir_analysis[af6e6fecb0b5810e]::check::check::check_item_type
  37:     0x7faaf3885a93 - rustc_hir_analysis[af6e6fecb0b5810e]::check::wfcheck::check_well_formed
  38:     0x7faaf63ef1c7 - rustc_query_impl[1357963d8dd30e8b]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[1357963d8dd30e8b]::query_impl::check_well_formed::dynamic_query::{closure#2}::{closure#0}, rustc_middle[f0eb6ba890d0a9bb]::query::erase::Erased<[u8; 1usize]>>
  39:     0x7faaf63ee919 - rustc_query_system[887bb79932b1d8c1]::query::plumbing::try_execute_query::<rustc_query_impl[1357963d8dd30e8b]::DynamicConfig<rustc_query_system[887bb79932b1d8c1]::query::caches::VecCache<rustc_span[db86d96c2ae2e3a4]::def_id::LocalDefId, rustc_middle[f0eb6ba890d0a9bb]::query::erase::Erased<[u8; 1usize]>>, false, false, false>, rustc_query_impl[1357963d8dd30e8b]::plumbing::QueryCtxt, false>
  40:     0x7faaf63ee590 - rustc_query_impl[1357963d8dd30e8b]::query_impl::check_well_formed::get_query_non_incr::__rust_end_short_backtrace
  41:     0x7faaf63ef247 - rustc_middle[f0eb6ba890d0a9bb]::query::plumbing::query_ensure_error_guaranteed::<rustc_query_system[887bb79932b1d8c1]::query::caches::VecCache<rustc_span[db86d96c2ae2e3a4]::def_id::LocalDefId, rustc_middle[f0eb6ba890d0a9bb]::query::erase::Erased<[u8; 1usize]>>, ()>
  42:     0x7faaf63ef7f2 - rustc_hir_analysis[af6e6fecb0b5810e]::check::wfcheck::check_mod_type_wf
  43:     0x7faaf63ef26f - rustc_query_impl[1357963d8dd30e8b]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[1357963d8dd30e8b]::query_impl::check_mod_type_wf::dynamic_query::{closure#2}::{closure#0}, rustc_middle[f0eb6ba890d0a9bb]::query::erase::Erased<[u8; 1usize]>>
  44:     0x7faaf6bed0c1 - rustc_query_system[887bb79932b1d8c1]::query::plumbing::try_execute_query::<rustc_query_impl[1357963d8dd30e8b]::DynamicConfig<rustc_query_system[887bb79932b1d8c1]::query::caches::DefaultCache<rustc_span[db86d96c2ae2e3a4]::def_id::LocalModDefId, rustc_middle[f0eb6ba890d0a9bb]::query::erase::Erased<[u8; 1usize]>>, false, false, false>, rustc_query_impl[1357963d8dd30e8b]::plumbing::QueryCtxt, false>
  45:     0x7faaf6bece70 - rustc_query_impl[1357963d8dd30e8b]::query_impl::check_mod_type_wf::get_query_non_incr::__rust_end_short_backtrace
  46:     0x7faaf671f42f - rustc_hir_analysis[af6e6fecb0b5810e]::check_crate
  47:     0x7faaf6868aca - rustc_interface[5fea8bf9cd0b71b5]::passes::run_required_analyses
  48:     0x7faaf6e0861e - rustc_interface[5fea8bf9cd0b71b5]::passes::analysis
  49:     0x7faaf6e085ef - rustc_query_impl[1357963d8dd30e8b]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[1357963d8dd30e8b]::query_impl::analysis::dynamic_query::{closure#2}::{closure#0}, rustc_middle[f0eb6ba890d0a9bb]::query::erase::Erased<[u8; 1usize]>>
  50:     0x7faaf6f92cee - rustc_query_system[887bb79932b1d8c1]::query::plumbing::try_execute_query::<rustc_query_impl[1357963d8dd30e8b]::DynamicConfig<rustc_query_system[887bb79932b1d8c1]::query::caches::SingleCache<rustc_middle[f0eb6ba890d0a9bb]::query::erase::Erased<[u8; 1usize]>>, false, false, false>, rustc_query_impl[1357963d8dd30e8b]::plumbing::QueryCtxt, false>
  51:     0x7faaf6f929ce - rustc_query_impl[1357963d8dd30e8b]::query_impl::analysis::get_query_non_incr::__rust_end_short_backtrace
  52:     0x7faaf6e8707a - rustc_interface[5fea8bf9cd0b71b5]::interface::run_compiler::<core[5ba82ee3405aa490]::result::Result<(), rustc_span[db86d96c2ae2e3a4]::ErrorGuaranteed>, rustc_driver_impl[945e9afaf49c7d35]::run_compiler::{closure#0}>::{closure#1}
  53:     0x7faaf6ecd5d0 - std[56fe22ad9ea837fd]::sys::backtrace::__rust_begin_short_backtrace::<rustc_interface[5fea8bf9cd0b71b5]::util::run_in_thread_with_globals<rustc_interface[5fea8bf9cd0b71b5]::util::run_in_thread_pool_with_globals<rustc_interface[5fea8bf9cd0b71b5]::interface::run_compiler<core[5ba82ee3405aa490]::result::Result<(), rustc_span[db86d96c2ae2e3a4]::ErrorGuaranteed>, rustc_driver_impl[945e9afaf49c7d35]::run_compiler::{closure#0}>::{closure#1}, core[5ba82ee3405aa490]::result::Result<(), rustc_span[db86d96c2ae2e3a4]::ErrorGuaranteed>>::{closure#0}, core[5ba82ee3405aa490]::result::Result<(), rustc_span[db86d96c2ae2e3a4]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[5ba82ee3405aa490]::result::Result<(), rustc_span[db86d96c2ae2e3a4]::ErrorGuaranteed>>
  54:     0x7faaf6ecd9eb - <<std[56fe22ad9ea837fd]::thread::Builder>::spawn_unchecked_<rustc_interface[5fea8bf9cd0b71b5]::util::run_in_thread_with_globals<rustc_interface[5fea8bf9cd0b71b5]::util::run_in_thread_pool_with_globals<rustc_interface[5fea8bf9cd0b71b5]::interface::run_compiler<core[5ba82ee3405aa490]::result::Result<(), rustc_span[db86d96c2ae2e3a4]::ErrorGuaranteed>, rustc_driver_impl[945e9afaf49c7d35]::run_compiler::{closure#0}>::{closure#1}, core[5ba82ee3405aa490]::result::Result<(), rustc_span[db86d96c2ae2e3a4]::ErrorGuaranteed>>::{closure#0}, core[5ba82ee3405aa490]::result::Result<(), rustc_span[db86d96c2ae2e3a4]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[5ba82ee3405aa490]::result::Result<(), rustc_span[db86d96c2ae2e3a4]::ErrorGuaranteed>>::{closure#1} as core[5ba82ee3405aa490]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  55:     0x7faaf6ece4b9 - std::sys::pal::unix::thread::Thread::new::thread_start::hb3d6392adeea417c
  56:     0x7faaf106bac3 - start_thread
                               at ./nptl/pthread_create.c:442:8
  57:     0x7faaf10fd850 - __GI___clone3
                               at ./misc/../sysdeps/unix/sysv/linux/x86_64/clone3.S:81
  58:                0x0 - <unknown>

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: please make sure that you have updated to the latest nightly

note: compiler flags: --crate-type staticlib -C link-dead-code -C debuginfo=2 -C opt-level=3 -Z mir-opt-level=3

query stack during panic:
#0 [mir_borrowck] borrow-checking `<impl at mutant.rs:11:1: 11:43>::pass2`
#1 [type_of_opaque] computing type of opaque `<impl at mutant.rs:11:1: 11:43>::pass2::{opaque#0}`
end of query stack
error: aborting due to 7 previous errors

Some errors have detailed explanations: E0046, E0407, E0496, E0670.
For more information about an error, try `rustc --explain E0046`.
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
stack backtrace:
   0:     0x7faaf585517a - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::hfadad24fb33e3d1a
   1:     0x7faaf60040a6 - core::fmt::write::h42d25fbda60cd99f
   2:     0x7faaf73c3351 - std::io::Write::write_fmt::hc2819193e80b365e
   3:     0x7faaf5854fd2 - std::sys::backtrace::BacktraceLock::print::h9450230402d77664
   4:     0x7faaf58574d6 - std::panicking::default_hook::{{closure}}::h739047d4d787c596
   5:     0x7faaf5857320 - std::panicking::default_hook::h203d1229480f37a5
   6:     0x7faaf48d2269 - std[56fe22ad9ea837fd]::panicking::update_hook::<alloc[b5641001d343df5f]::boxed::Box<rustc_driver_impl[945e9afaf49c7d35]::install_ice_hook::{closure#0}>>::{closure#0}
   7:     0x7faaf5857be8 - std::panicking::rust_panic_with_hook::h657fdcc17f7e2546
   8:     0x7faaf490c191 - std[56fe22ad9ea837fd]::panicking::begin_panic::<rustc_errors[43c84716ac990581]::ExplicitBug>::{closure#0}
   9:     0x7faaf48ff166 - std[56fe22ad9ea837fd]::sys::backtrace::__rust_end_short_backtrace::<std[56fe22ad9ea837fd]::panicking::begin_panic<rustc_errors[43c84716ac990581]::ExplicitBug>::{closure#0}, !>
  10:     0x7faaf48feefe - std[56fe22ad9ea837fd]::panicking::begin_panic::<rustc_errors[43c84716ac990581]::ExplicitBug>
  11:     0x7faaf4915e71 - <rustc_errors[43c84716ac990581]::diagnostic::BugAbort as rustc_errors[43c84716ac990581]::diagnostic::EmissionGuarantee>::emit_producing_guarantee
  12:     0x7faaf4f8f2c3 - rustc_middle[f0eb6ba890d0a9bb]::util::bug::opt_span_bug_fmt::<rustc_span[db86d96c2ae2e3a4]::span_encoding::Span>::{closure#0}
  13:     0x7faaf4f758ba - rustc_middle[f0eb6ba890d0a9bb]::ty::context::tls::with_opt::<rustc_middle[f0eb6ba890d0a9bb]::util::bug::opt_span_bug_fmt<rustc_span[db86d96c2ae2e3a4]::span_encoding::Span>::{closure#0}, !>::{closure#0}
  14:     0x7faaf4f7574b - rustc_middle[f0eb6ba890d0a9bb]::ty::context::tls::with_context_opt::<rustc_middle[f0eb6ba890d0a9bb]::ty::context::tls::with_opt<rustc_middle[f0eb6ba890d0a9bb]::util::bug::opt_span_bug_fmt<rustc_span[db86d96c2ae2e3a4]::span_encoding::Span>::{closure#0}, !>::{closure#0}, !>
  15:     0x7faaf31e7300 - rustc_middle[f0eb6ba890d0a9bb]::util::bug::bug_fmt
  16:     0x7faaf75c2ce0 - <rustc_borrowck[de200e79d11a1023]::universal_regions::UniversalRegionIndices>::to_region_vid.cold
  17:     0x7faaf6055b14 - <rustc_borrowck[de200e79d11a1023]::universal_regions::UniversalRegionIndices>::fold_to_region_vids::<rustc_type_ir[8408d34320f8a6fb]::binder::Binder<rustc_middle[f0eb6ba890d0a9bb]::ty::context::TyCtxt, rustc_type_ir[8408d34320f8a6fb]::ty_kind::FnSig<rustc_middle[f0eb6ba890d0a9bb]::ty::context::TyCtxt>>>::{closure#0}
  18:     0x7faaf6051924 - <&rustc_middle[f0eb6ba890d0a9bb]::ty::list::RawList<(), rustc_middle[f0eb6ba890d0a9bb]::ty::generic_args::GenericArg> as rustc_type_ir[8408d34320f8a6fb]::fold::TypeFoldable<rustc_middle[f0eb6ba890d0a9bb]::ty::context::TyCtxt>>::try_fold_with::<rustc_middle[f0eb6ba890d0a9bb]::ty::fold::RegionFolder>
  19:     0x7faaf60527e4 - <rustc_middle[f0eb6ba890d0a9bb]::ty::Ty as rustc_type_ir[8408d34320f8a6fb]::fold::TypeSuperFoldable<rustc_middle[f0eb6ba890d0a9bb]::ty::context::TyCtxt>>::try_super_fold_with::<rustc_middle[f0eb6ba890d0a9bb]::ty::fold::RegionFolder>
  20:     0x7faaf6051da7 - <&rustc_middle[f0eb6ba890d0a9bb]::ty::list::RawList<(), rustc_middle[f0eb6ba890d0a9bb]::ty::Ty> as rustc_type_ir[8408d34320f8a6fb]::fold::TypeFoldable<rustc_middle[f0eb6ba890d0a9bb]::ty::context::TyCtxt>>::try_fold_with::<rustc_middle[f0eb6ba890d0a9bb]::ty::fold::RegionFolder>
  21:     0x7faaf70b3648 - rustc_borrowck[de200e79d11a1023]::do_mir_borrowck
  22:     0x7faaf70b228a - rustc_query_impl[1357963d8dd30e8b]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[1357963d8dd30e8b]::query_impl::mir_borrowck::dynamic_query::{closure#2}::{closure#0}, rustc_middle[f0eb6ba890d0a9bb]::query::erase::Erased<[u8; 8usize]>>
  23:     0x7faaf6723681 - rustc_query_system[887bb79932b1d8c1]::query::plumbing::try_execute_query::<rustc_query_impl[1357963d8dd30e8b]::DynamicConfig<rustc_query_system[887bb79932b1d8c1]::query::caches::VecCache<rustc_span[db86d96c2ae2e3a4]::def_id::LocalDefId, rustc_middle[f0eb6ba890d0a9bb]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[1357963d8dd30e8b]::plumbing::QueryCtxt, false>
  24:     0x7faaf672318d - rustc_query_impl[1357963d8dd30e8b]::query_impl::mir_borrowck::get_query_non_incr::__rust_end_short_backtrace
  25:     0x7faaf69cc8f3 - rustc_middle[f0eb6ba890d0a9bb]::query::plumbing::query_get_at::<rustc_query_system[887bb79932b1d8c1]::query::caches::VecCache<rustc_span[db86d96c2ae2e3a4]::def_id::LocalDefId, rustc_middle[f0eb6ba890d0a9bb]::query::erase::Erased<[u8; 8usize]>>>
  26:     0x7faaf713b05e - rustc_hir_analysis[af6e6fecb0b5810e]::collect::type_of::type_of_opaque
  27:     0x7faaf713aed1 - rustc_query_impl[1357963d8dd30e8b]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[1357963d8dd30e8b]::query_impl::type_of_opaque::dynamic_query::{closure#2}::{closure#0}, rustc_middle[f0eb6ba890d0a9bb]::query::erase::Erased<[u8; 8usize]>>
  28:     0x7faaf6023bb6 - rustc_query_system[887bb79932b1d8c1]::query::plumbing::try_execute_query::<rustc_query_impl[1357963d8dd30e8b]::DynamicConfig<rustc_query_system[887bb79932b1d8c1]::query::caches::DefIdCache<rustc_middle[f0eb6ba890d0a9bb]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[1357963d8dd30e8b]::plumbing::QueryCtxt, false>
  29:     0x7faaf72137f5 - rustc_query_impl[1357963d8dd30e8b]::query_impl::type_of_opaque::get_query_non_incr::__rust_end_short_backtrace
  30:     0x7faaf64f6540 - rustc_middle[f0eb6ba890d0a9bb]::query::plumbing::query_get_at::<rustc_query_system[887bb79932b1d8c1]::query::caches::DefIdCache<rustc_middle[f0eb6ba890d0a9bb]::query::erase::Erased<[u8; 8usize]>>>
  31:     0x7faaf318f449 - rustc_hir_analysis[af6e6fecb0b5810e]::collect::type_of::type_of
  32:     0x7faaf6024ef2 - rustc_query_impl[1357963d8dd30e8b]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[1357963d8dd30e8b]::query_impl::type_of::dynamic_query::{closure#2}::{closure#0}, rustc_middle[f0eb6ba890d0a9bb]::query::erase::Erased<[u8; 8usize]>>
  33:     0x7faaf6023bb6 - rustc_query_system[887bb79932b1d8c1]::query::plumbing::try_execute_query::<rustc_query_impl[1357963d8dd30e8b]::DynamicConfig<rustc_query_system[887bb79932b1d8c1]::query::caches::DefIdCache<rustc_middle[f0eb6ba890d0a9bb]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[1357963d8dd30e8b]::plumbing::QueryCtxt, false>
  34:     0x7faaf6023767 - rustc_query_impl[1357963d8dd30e8b]::query_impl::type_of::get_query_non_incr::__rust_end_short_backtrace
  35:     0x7faaf64f6540 - rustc_middle[f0eb6ba890d0a9bb]::query::plumbing::query_get_at::<rustc_query_system[887bb79932b1d8c1]::query::caches::DefIdCache<rustc_middle[f0eb6ba890d0a9bb]::query::erase::Erased<[u8; 8usize]>>>
  36:     0x7faaf7149109 - rustc_hir_analysis[af6e6fecb0b5810e]::check::check::check_item_type
  37:     0x7faaf3885a93 - rustc_hir_analysis[af6e6fecb0b5810e]::check::wfcheck::check_well_formed
  38:     0x7faaf63ef1c7 - rustc_query_impl[1357963d8dd30e8b]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[1357963d8dd30e8b]::query_impl::check_well_formed::dynamic_query::{closure#2}::{closure#0}, rustc_middle[f0eb6ba890d0a9bb]::query::erase::Erased<[u8; 1usize]>>
  39:     0x7faaf63ee919 - rustc_query_system[887bb79932b1d8c1]::query::plumbing::try_execute_query::<rustc_query_impl[1357963d8dd30e8b]::DynamicConfig<rustc_query_system[887bb79932b1d8c1]::query::caches::VecCache<rustc_span[db86d96c2ae2e3a4]::def_id::LocalDefId, rustc_middle[f0eb6ba890d0a9bb]::query::erase::Erased<[u8; 1usize]>>, false, false, false>, rustc_query_impl[1357963d8dd30e8b]::plumbing::QueryCtxt, false>
  40:     0x7faaf63ee590 - rustc_query_impl[1357963d8dd30e8b]::query_impl::check_well_formed::get_query_non_incr::__rust_end_short_backtrace
  41:     0x7faaf63ef247 - rustc_middle[f0eb6ba890d0a9bb]::query::plumbing::query_ensure_error_guaranteed::<rustc_query_system[887bb79932b1d8c1]::query::caches::VecCache<rustc_span[db86d96c2ae2e3a4]::def_id::LocalDefId, rustc_middle[f0eb6ba890d0a9bb]::query::erase::Erased<[u8; 1usize]>>, ()>
  42:     0x7faaf63ef7f2 - rustc_hir_analysis[af6e6fecb0b5810e]::check::wfcheck::check_mod_type_wf
  43:     0x7faaf63ef26f - rustc_query_impl[1357963d8dd30e8b]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[1357963d8dd30e8b]::query_impl::check_mod_type_wf::dynamic_query::{closure#2}::{closure#0}, rustc_middle[f0eb6ba890d0a9bb]::query::erase::Erased<[u8; 1usize]>>
  44:     0x7faaf6bed0c1 - rustc_query_system[887bb79932b1d8c1]::query::plumbing::try_execute_query::<rustc_query_impl[1357963d8dd30e8b]::DynamicConfig<rustc_query_system[887bb79932b1d8c1]::query::caches::DefaultCache<rustc_span[db86d96c2ae2e3a4]::def_id::LocalModDefId, rustc_middle[f0eb6ba890d0a9bb]::query::erase::Erased<[u8; 1usize]>>, false, false, false>, rustc_query_impl[1357963d8dd30e8b]::plumbing::QueryCtxt, false>
  45:     0x7faaf6bece70 - rustc_query_impl[1357963d8dd30e8b]::query_impl::check_mod_type_wf::get_query_non_incr::__rust_end_short_backtrace
  46:     0x7faaf671f42f - rustc_hir_analysis[af6e6fecb0b5810e]::check_crate
  47:     0x7faaf6868aca - rustc_interface[5fea8bf9cd0b71b5]::passes::run_required_analyses
  48:     0x7faaf6e0861e - rustc_interface[5fea8bf9cd0b71b5]::passes::analysis
  49:     0x7faaf6e085ef - rustc_query_impl[1357963d8dd30e8b]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[1357963d8dd30e8b]::query_impl::analysis::dynamic_query::{closure#2}::{closure#0}, rustc_middle[f0eb6ba890d0a9bb]::query::erase::Erased<[u8; 1usize]>>
  50:     0x7faaf6f92cee - rustc_query_system[887bb79932b1d8c1]::query::plumbing::try_execute_query::<rustc_query_impl[1357963d8dd30e8b]::DynamicConfig<rustc_query_system[887bb79932b1d8c1]::query::caches::SingleCache<rustc_middle[f0eb6ba890d0a9bb]::query::erase::Erased<[u8; 1usize]>>, false, false, false>, rustc_query_impl[1357963d8dd30e8b]::plumbing::QueryCtxt, false>
  51:     0x7faaf6f929ce - rustc_query_impl[1357963d8dd30e8b]::query_impl::analysis::get_query_non_incr::__rust_end_short_backtrace
  52:     0x7faaf6e8707a - rustc_interface[5fea8bf9cd0b71b5]::interface::run_compiler::<core[5ba82ee3405aa490]::result::Result<(), rustc_span[db86d96c2ae2e3a4]::ErrorGuaranteed>, rustc_driver_impl[945e9afaf49c7d35]::run_compiler::{closure#0}>::{closure#1}
  53:     0x7faaf6ecd5d0 - std[56fe22ad9ea837fd]::sys::backtrace::__rust_begin_short_backtrace::<rustc_interface[5fea8bf9cd0b71b5]::util::run_in_thread_with_globals<rustc_interface[5fea8bf9cd0b71b5]::util::run_in_thread_pool_with_globals<rustc_interface[5fea8bf9cd0b71b5]::interface::run_compiler<core[5ba82ee3405aa490]::result::Result<(), rustc_span[db86d96c2ae2e3a4]::ErrorGuaranteed>, rustc_driver_impl[945e9afaf49c7d35]::run_compiler::{closure#0}>::{closure#1}, core[5ba82ee3405aa490]::result::Result<(), rustc_span[db86d96c2ae2e3a4]::ErrorGuaranteed>>::{closure#0}, core[5ba82ee3405aa490]::result::Result<(), rustc_span[db86d96c2ae2e3a4]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[5ba82ee3405aa490]::result::Result<(), rustc_span[db86d96c2ae2e3a4]::ErrorGuaranteed>>
  54:     0x7faaf6ecd9eb - <<std[56fe22ad9ea837fd]::thread::Builder>::spawn_unchecked_<rustc_interface[5fea8bf9cd0b71b5]::util::run_in_thread_with_globals<rustc_interface[5fea8bf9cd0b71b5]::util::run_in_thread_pool_with_globals<rustc_interface[5fea8bf9cd0b71b5]::interface::run_compiler<core[5ba82ee3405aa490]::result::Result<(), rustc_span[db86d96c2ae2e3a4]::ErrorGuaranteed>, rustc_driver_impl[945e9afaf49c7d35]::run_compiler::{closure#0}>::{closure#1}, core[5ba82ee3405aa490]::result::Result<(), rustc_span[db86d96c2ae2e3a4]::ErrorGuaranteed>>::{closure#0}, core[5ba82ee3405aa490]::result::Result<(), rustc_span[db86d96c2ae2e3a4]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[5ba82ee3405aa490]::result::Result<(), rustc_span[db86d96c2ae2e3a4]::ErrorGuaranteed>>::{closure#1} as core[5ba82ee3405aa490]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  55:     0x7faaf6ece4b9 - std::sys::pal::unix::thread::Thread::new::thread_start::hb3d6392adeea417c
  56:     0x7faaf106bac3 - start_thread
                               at ./nptl/pthread_create.c:442:8
  57:     0x7faaf10fd850 - __GI___clone3
                               at ./misc/../sysdeps/unix/sysv/linux/x86_64/clone3.S:81
  58:                0x0 - <unknown>
```

</p>
</details>

### LINKED ISSUE #133693: ICE: Rustc Crashes on Lifetime Parameter in Async Fn
### Code

```Rust
#![allow(dead_code)]
struct Foo<'static>(&'static u32);
impl<'static> Foo<'static>
{ async fn foo() {} }
fn main(){}
```

### Meta

`rustc --version --verbose`:
```
rustc 1.85.0-nightly (7442931d4 2024-11-30)
binary: rustc
commit-hash: 7442931d49b199ad0a1cc0f8ca54e327b5139b66
commit-date: 2024-11-30
host: x86_64-unknown-linux-gnu
release: 1.85.0-nightly
LLVM version: 19.1.4
```

### Error output

```
$ rustc --edition=2021 test.rs 
error[E0262]: invalid lifetime parameter name: `'static`
 --> test.rs:2:12
  |
2 | struct Foo<'static>(&'static u32);
  |            ^^^^^^^ 'static is a reserved lifetime name

error[E0262]: invalid lifetime parameter name: `'static`
 --> test.rs:3:6
  |
3 | impl<'static> Foo<'static>
  |      ^^^^^^^ 'static is a reserved lifetime name

error: internal compiler error: compiler/rustc_borrowck/src/universal_regions.rs:899:36: cannot convert `'static/#0` to a region vid
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
thread 'rustc' panicked at compiler/rustc_borrowck/src/universal_regions.rs:899:36:
Box<dyn Any>
stack backtrace:
   0:     0x7f57d8dd00da - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::h41650409cfcaa385
   1:     0x7f57d9479c26 - core::fmt::write::h124e50a41a614f35
   2:     0x7f57da4752d1 - std::io::Write::write_fmt::h152c770d77d8200b
   3:     0x7f57d8dcff32 - std::sys::backtrace::BacktraceLock::print::hb77a071b09f7b2d4
   4:     0x7f57d8dd243a - std::panicking::default_hook::{{closure}}::h2289b310e8f70172
   5:     0x7f57d8dd2283 - std::panicking::default_hook::h6b36901e2a542246
   6:     0x7f57d7f45618 - std[562fec4e669516d]::panicking::update_hook::<alloc[86f54b6de7847bb5]::boxed::Box<rustc_driver_impl[754960437973ebe]::install_ice_hook::{closure#0}>>::{closure#0}
   7:     0x7f57d8dd2bf8 - std::panicking::rust_panic_with_hook::hd7b2147b933d3e5b
   8:     0x7f57d7f7ae21 - std[562fec4e669516d]::panicking::begin_panic::<rustc_errors[35a85695d11d5811]::ExplicitBug>::{closure#0}
   9:     0x7f57d7f6fce6 - std[562fec4e669516d]::sys::backtrace::__rust_end_short_backtrace::<std[562fec4e669516d]::panicking::begin_panic<rustc_errors[35a85695d11d5811]::ExplicitBug>::{closure#0}, !>
  10:     0x7f57d7f6fcd3 - std[562fec4e669516d]::panicking::begin_panic::<rustc_errors[35a85695d11d5811]::ExplicitBug>
  11:     0x7f57d7f84e61 - <rustc_errors[35a85695d11d5811]::diagnostic::BugAbort as rustc_errors[35a85695d11d5811]::diagnostic::EmissionGuarantee>::emit_producing_guarantee
  12:     0x7f57d8574d33 - rustc_middle[6e6d053ab00ffe47]::util::bug::opt_span_bug_fmt::<rustc_span[218a417b0d7920e2]::span_encoding::Span>::{closure#0}
  13:     0x7f57d855d1da - rustc_middle[6e6d053ab00ffe47]::ty::context::tls::with_opt::<rustc_middle[6e6d053ab00ffe47]::util::bug::opt_span_bug_fmt<rustc_span[218a417b0d7920e2]::span_encoding::Span>::{closure#0}, !>::{closure#0}
  14:     0x7f57d855d06b - rustc_middle[6e6d053ab00ffe47]::ty::context::tls::with_context_opt::<rustc_middle[6e6d053ab00ffe47]::ty::context::tls::with_opt<rustc_middle[6e6d053ab00ffe47]::util::bug::opt_span_bug_fmt<rustc_span[218a417b0d7920e2]::span_encoding::Span>::{closure#0}, !>::{closure#0}, !>
  15:     0x7f57d6812340 - rustc_middle[6e6d053ab00ffe47]::util::bug::bug_fmt
  16:     0x7f57daa84f60 - <rustc_borrowck[4000f49d4f35c9a9]::universal_regions::UniversalRegionIndices>::to_region_vid.cold
  17:     0x7f57d94bdb85 - <&rustc_middle[6e6d053ab00ffe47]::ty::list::RawList<(), rustc_middle[6e6d053ab00ffe47]::ty::generic_args::GenericArg> as rustc_type_ir[555f37532e32cbd7]::fold::TypeFoldable<rustc_middle[6e6d053ab00ffe47]::ty::context::TyCtxt>>::try_fold_with::<rustc_type_ir[555f37532e32cbd7]::fold::RegionFolder<rustc_middle[6e6d053ab00ffe47]::ty::context::TyCtxt>>
  18:     0x7f57d94bf744 - <rustc_middle[6e6d053ab00ffe47]::ty::Ty as rustc_type_ir[555f37532e32cbd7]::fold::TypeSuperFoldable<rustc_middle[6e6d053ab00ffe47]::ty::context::TyCtxt>>::try_super_fold_with::<rustc_type_ir[555f37532e32cbd7]::fold::RegionFolder<rustc_middle[6e6d053ab00ffe47]::ty::context::TyCtxt>>
  19:     0x7f57d94bedf0 - <&rustc_middle[6e6d053ab00ffe47]::ty::list::RawList<(), rustc_middle[6e6d053ab00ffe47]::ty::Ty> as rustc_type_ir[555f37532e32cbd7]::fold::TypeFoldable<rustc_middle[6e6d053ab00ffe47]::ty::context::TyCtxt>>::try_fold_with::<rustc_type_ir[555f37532e32cbd7]::fold::RegionFolder<rustc_middle[6e6d053ab00ffe47]::ty::context::TyCtxt>>
  20:     0x7f57da5bf2aa - rustc_borrowck[4000f49d4f35c9a9]::do_mir_borrowck
[rustc-ice-2024-12-01T05_05_25-7073.txt](https://github.com/user-attachments/files/17967887/rustc-ice-2024-12-01T05_05_25-7073.txt)
```

</p>
</details>

### LINKED ISSUE #134780: ICE: AFIT with shadowed lifetime parameter: Cannot convert to region vid
[rustc-ice-2024-12-26T04_38_07-1636589.txt](https://github.com/user-attachments/files/18249609/rustc-ice-2024-12-26T04_38_07-1636589.txt)
I have a rustc crash for you.

You will notice that I reference a concrete type that is not defined. I just did that to make it more minimal; I still get the crash even if I define it, ie. with `struct Something { }`. Similarly, this still works (ie. crashes) if I define a `main()`.

With the benefit of hindsight and after reducing it, I understand why this input is not valid Rust, and do not need help debugging the actual thing I was trying to do. In fact, it's quite impressive that the compiler gets so far as to show meaningful error messages before crashing. I just figured you'd, you know, want to know about the crash.

Good luck!

### Code

```Rust
trait Trait {                                                                   
  async fn method<'a>();                                                        
}                                                                               
                                                                                
impl<'a> Trait for Something {                                                  
  async fn method<'a>() { }                                                     
}                                                                               
```

### Meta

`rustc --version --verbose`:
```
rustc 1.85.0-nightly (7c002ff9a 2024-12-25)
binary: rustc
commit-hash: 7c002ff9a70cb84fd1a91bc7b4a0f988cfc36fca
commit-date: 2024-12-25
host: x86_64-unknown-linux-gnu
release: 1.85.0-nightly
LLVM version: 19.1.6
```

### Error output

```
   Compiling cloakroom v0.1.0 (/home/irenes/Projects/cloakroom-reduced)
error[E0496]: lifetime name `'a` shadows a lifetime name that is already in scope
 --> src/main.rs:6:19
  |
5 | impl<'a> Trait for Something {
  |      -- first declared here
6 |   async fn method<'a>() { }
  |                   ^^ lifetime `'a` already in scope

error[E0412]: cannot find type `Something` in this scope
 --> src/main.rs:5:20
  |
5 | impl<'a> Trait for Something {
  |                    ^^^^^^^^^ not found in this scope

error[E0601]: `main` function not found in crate `cloakroom`
 --> src/main.rs:7:2
  |
7 | }
  |  ^ consider adding a `main` function to `src/main.rs`

error: internal compiler error: compiler/rustc_borrowck/src/universal_regions.rs:901:36: cannot convert `'a/#1` to a region vid

thread 'rustc' panicked at compiler/rustc_borrowck/src/universal_regions.rs:901:36:
Box<dyn Any>
stack backtrace:
   0: std::panicking::begin_panic::<rustc_errors::ExplicitBug>
   1: <rustc_errors::diagnostic::BugAbort as rustc_errors::diagnostic::EmissionGuarantee>::emit_producing_guarantee
   2: rustc_middle::util::bug::opt_span_bug_fmt::<rustc_span::span_encoding::Span>::{closure#0}
   3: rustc_middle::ty::context::tls::with_opt::<rustc_middle::util::bug::opt_span_bug_fmt<rustc_span::span_encoding::Span>::{closure#0}, !>::{closure#0}
   4: rustc_middle::ty::context::tls::with_context_opt::<rustc_middle::ty::context::tls::with_opt<rustc_middle::util::bug::opt_span_bug_fmt<rustc_span::span_encoding::Span>::{closure#0}, !>::{closure#0}, !>
   5: rustc_middle::util::bug::bug_fmt
   6: <rustc_borrowck::universal_regions::UniversalRegionIndices>::to_region_vid.cold
   7: <&rustc_middle::ty::list::RawList<(), rustc_middle::ty::generic_args::GenericArg> as rustc_type_ir::fold::TypeFoldable<rustc_middle::ty::context::TyCtxt>>::try_fold_with::<rustc_type_ir::fold::RegionFolder<rustc_middle::ty::context::TyCtxt>>
   8: <rustc_middle::ty::Ty as rustc_type_ir::fold::TypeSuperFoldable<rustc_middle::ty::context::TyCtxt>>::try_super_fold_with::<rustc_type_ir::fold::RegionFolder<rustc_middle::ty::context::TyCtxt>>
   9: <&rustc_middle::ty::list::RawList<(), rustc_middle::ty::Ty> as rustc_type_ir::fold::TypeFoldable<rustc_middle::ty::context::TyCtxt>>::try_fold_with::<rustc_type_ir::fold::RegionFolder<rustc_middle::ty::context::TyCtxt>>
  10: rustc_borrowck::do_mir_borrowck
      [... omitted 1 frame ...]
  11: rustc_middle::query::plumbing::query_get_at::<rustc_data_structures::vec_cache::VecCache<rustc_span::def_id::LocalDefId, rustc_middle::query::erase::Erased<[u8; 8]>, rustc_query_system::dep_graph::graph::DepNodeIndex>>
  12: rustc_hir_analysis::collect::type_of::type_of_opaque
      [... omitted 1 frame ...]
  13: rustc_middle::query::plumbing::query_get_at::<rustc_query_system::query::caches::DefIdCache<rustc_middle::query::erase::Erased<[u8; 8]>>>
  14: rustc_hir_analysis::collect::type_of::type_of
      [... omitted 1 frame ...]
  15: rustc_middle::query::plumbing::query_get_at::<rustc_query_system::query::caches::DefIdCache<rustc_middle::query::erase::Erased<[u8; 8]>>>
  16: rustc_hir_analysis::check::check::check_item_type
  17: rustc_hir_analysis::check::wfcheck::check_well_formed
      [... omitted 1 frame ...]
  18: rustc_middle::query::plumbing::query_ensure_error_guaranteed::<rustc_data_structures::vec_cache::VecCache<rustc_span::def_id::LocalDefId, rustc_middle::query::erase::Erased<[u8; 1]>, rustc_query_system::dep_graph::graph::DepNodeIndex>, ()>
  19: rustc_hir_analysis::check::wfcheck::check_mod_type_wf
      [... omitted 1 frame ...]
  20: rustc_hir_analysis::check_crate
  21: rustc_interface::passes::run_required_analyses
  22: rustc_interface::passes::analysis
      [... omitted 1 frame ...]
  23: rustc_interface::passes::create_and_enter_global_ctxt::<core::option::Option<rustc_interface::queries::Linker>, rustc_driver_impl::run_compiler::{closure#0}::{closure#2}>::{closure#2}::{closure#0}
  24: rustc_interface::interface::run_compiler::<(), rustc_driver_impl::run_compiler::{closure#0}>::{closure#1}
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: please make sure that you have updated to the latest nightly

note: please attach the file at `[redacted]/rustc-ice-2024-12-26T04_38_07-1636589.txt` to your bug report

note: compiler flags: --crate-type bin -C embed-bitcode=no -C debuginfo=2 -C incremental=[REDACTED]
<!-- Failed to upload "rustc-ice-2024-12-26T04_38_07-1636589.txt" -->
<!-- Failed to upload "rustc-ice-2024-12-26T04_38_07-1636589.txt" -->
[rustc-ice-2024-12-26T04_38_07-1636589.txt](https://github.com/user-attachments/files/18249603/rustc-ice-2024-12-26T04_38_07-1636589.txt)

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [mir_borrowck] borrow-checking `<impl at src/main.rs:5:1: 5:29>::method`
#1 [type_of_opaque] computing type of opaque `<impl at src/main.rs:5:1: 5:29>::method::{opaque#0}`
#2 [type_of] computing type of `<impl at src/main.rs:5:1: 5:29>::method::{opaque#0}`
#3 [check_well_formed] checking that `<impl at src/main.rs:5:1: 5:29>::method::{opaque#0}` is well-formed
#4 [check_mod_type_wf] checking that types are well-formed in top-level module
#5 [analysis] running analysis passes on this crate[rustc-ice-2024-12-26T04_38_07-1636589.txt](https://github.com/user-attachments/files/18249606/rustc-ice-2024-12-26T04_38_07-1636589.txt)

end of query stack
Some errors have detailed explanations: E0412, E0496, E0601.
For more information about an error, try `rustc --explain E0412`.
error: could not compile `cloakroom` (bin "cloakroom") due to 3 previous errors
```

The above output was with RUST_BACKTRACE=1, but I get almost the same thing without it; I'm unable to identify which portion of this is the "backtrace" and which is the "error output" so I have put it all together, above. Hope that's okay.

### PR DESCRIPTION
**Pull request by compiler-errors**
See description on test.

Fixes #132766
Fixes #133693
Fixes #134780

### CODE REVIEW

File: tests/ui/impl-trait/captured-invalid-lifetime.rs [hunk 1]
```diff
@@ -0,0 +1,18 @@
+// This uses edition 2024 for new lifetime capture rules.
+//@ edition: 2024
+
+// The problem here is that the presence of the opaque which captures all lifetimes in scope
+// means that the duplicated `'a` (which I'll call the dupe) is considered to be *early-bound*
+// since it shows up in the output but not the inputs. This is paired with the fact that we
+// were previously setting the name of the dupe to `'_` in the generic param definition, which
+// means that the identity args for the function were `['a#0, '_#1]` even though the lifetime
+// for the dupe should've been `'a#1`. This difference in symbol meant that NLL couldn't
+// actually match the lifetime against the identity lifeitmes, leading to an ICE.
```
Comment (lqd) [inline tests/ui/impl-trait/captured-invalid-lifetime.rs:10]:
```suggestion
// actually match the lifetime against the identity lifetimes, leading to an ICE.
```

I'm preventing randos opening PRs in the future to fix this one typo.

**Review by lqd — APPROVED** [review]
IIRC #131295 is not a dupe of the others so it shouldn't be fixed by this PR? Like, someone added an MCVE there by mistake that involved shadowing or something, like you've fixed here.

r=me with the blessed expectations + error annotation in the test, and the "fixes 131295" removed if it indeed shouldn't be present.
