### PR TITLE
QNX Neutrino: exponential backoff when fork/spawn needs a retry

### LINKED ISSUE #108594: Spawning / Forking a process on QNX Neutrino can fail
This only applies to the Tier 3 target `QNX Neutrino OS`  versions 7.1 and before.

When a process runs fork/spawn in one thread and changes existing file descriptors in another thread at the same time, fork/spawn can fail. This seems not to be very common on applications, but happens a lot in Rusts test suites and remote-test-server.

As of https://github.com/rust-lang/rust/pull/106673, Rusts standard library retries four times (as suggested by QNX' documentation), but this can be insufficient. Up to 150 retries have been observed when running the test suite.

See https://github.com/rust-lang/rust/pull/106673 for more details.

cc: @gh-tr

@rustbot label +O-neutrino

### PR DESCRIPTION
**Pull request by flba-eb**
Fixes #108594: When retrying, sleep with an exponential duration. When sleep duration is lower than minimum possible sleeping time, yield instead (this will not be often due to the exponential increase of duration).

Minimum possible sleeping time is determined using `libc::clock_getres` but only when spawn/fork failed the first time in a request. This is cached using a LazyLock.

CC @gh-tr

r? @workingjubilee
@rustbot label +O-neutrino

### CODE REVIEW

File: library/std/src/sys/unix/process/process_unix.rs [hunk 1]
```diff
@@ -481,12 +505,22 @@ impl Command {
             argv: *const *mut c_char,
             envp: *const *mut c_char,
         ) -> i32 {
-            let mut tries_left = MAX_FORKSPAWN_TRIES;
+            let mut minimum_delay = None;
```
Comment (workingjubilee) [inline library/std/src/sys/unix/process/process_unix.rs:508]: Same thought as before, except clearly we should hoist the `static` up to be visible to both of these functions.

File: library/std/src/sys/unix/process/process_unix.rs [hunk 2]
```diff
@@ -163,12 +175,24 @@ impl Command {
...
+                }
+                if delay < minimum_delay.unwrap() {
+                    // We cannot sleep this short (it would be longer).
+                    // Yield instead.
+                    thread::yield_now();
+                } else {
+                    thread::sleep(delay);
+                }
+                delay *= 2;
+                continue;
```
Comment (workingjubilee) [inline library/std/src/sys/unix/process/process_unix.rs:195]: I would like it if we still bailed for `ErrorKind::WouldBlock` or `ErrorKind::Interrupted` after a while, probably if we're getting up to actual seconds between yields.

**Review by workingjubilee — CHANGES_REQUESTED** [review]
Sorry about the long turnaround time, April was apparently not great for thinking.

**Comment by flba-eb** [comment]
Thank you very much @workingjubilee for the good feedback! I'm also a bit busy at the moment and will certainly not be able to work on it next week, but afterwards should be feasible.

**Comment by flba-eb** [comment]
Requested changes have been implemented but should be tested before merging them. Branch is rebased; requested changes are in a separate commit to make the review easier.

**Comment by flba-eb** [comment]
r? @workingjubilee
Requested changes are done and tested on QNX Neutrino.

**Comment by flba-eb** [comment]
@workingjubilee What do you think about giving up after one second? Does it make sense to document this somewhere as QNX Neutrino specific behavior? Where?

**Comment by workingjubilee** [comment]
Yeah, 1 second as the upper bar seems fine. If you wish to document it in the platform support (for now? maybe we should have a "platform quirks" page somewhere...) page, then go ahead. It's an unlikely circumstance, even under kernel stress, that I think having this surface in Rust programs as an unhandled "glitch" is fine, i.e. real programs usually won't hit this. **However**, I feel I should note that EAGAIN is actually specifically defined as a plausible POSIX error for [posix_spawn](https://pubs.opengroup.org/onlinepubs/007904975/functions/posix_spawn.html) due to it including "all the reasons fork/exec would fail", and [fork can EAGAIN](https://pubs.opengroup.org/onlinepubs/007904975/functions/fork.html).

**Review by workingjubilee — APPROVED** [review]

**Comment by workingjubilee** [comment]
Given that, it might actually make more sense to document this as a possible error for _all_ platforms? But any changes for documenting spawn's errors for all platforms should be in another PR, and you might want to document it as specifically likely for Neutrino anyways.

r=me with the platform-specific note, or as-is.

@bors delegate=fiba-eb

**Comment by workingjubilee** [comment]
???

@bors delegate=flba-eb

**Comment by flba-eb** [comment]
Yes I think this should be documented in another PR. With this patch I wasn't able at all to reproduce the issue anymore (before the `ui` test suit always had 4-10 failures). As soon as we're sleeping the problem basically goes away. After thinking about it, I would not even mention it in [nto-qnx.md](https://github.com/rust-lang/rust/pull/109432/files#diff-ddffe8a46971c69f7101e84fa2f0d6b672da67e2d6b1a501212abd0b09080e2d) anymore. Would you agree?

**Comment by workingjubilee** [comment]
Sure! Then let's go with this.

@bors r+
