### PR TITLE
Suggest `!` for bitwise negation when encountering a `~`

### LINKED ISSUE #41679: Suggest `!` for bitwise negation when encountering a `~`
Here's a program:
```rust
fn main() {
    let x = ~1;
}
```
Its output:
```
error: expected expression, found `~`
 --> <anon>:2:13
  |
2 |     let x = ~1;
  |             ^

error: aborting due to previous error
```
Given that this is our only deviation from C-style bitwise operator syntax, it would be nice to have a note of some kind to suggest `!` here.

Ideally the note would only appear when the `~` looks like it's being applied as a unary operator on a numeric type, but if that would require too much machinery then something simpler will suffice.

### PR DESCRIPTION
**Pull request by F001**
Fix #41679 

Here is a program

```rust
fn main() {
    let x = ~1;
}
```

It's output:
```
error: `~` can not be used as an unary operator
 --> /home/fcc/temp/test.rs:4:13
  |
4 |     let x = ~1;
  |             ^^
  |
  = help: use `!` instead of `~` if you meant to bitwise negation
```

cc @bstrie

### CODE REVIEW

**Comment by kennytm** [comment]
You should add a test case (probably in `src/test/ui/did_you_mean`).

**Comment by F001** [comment]
Thank you @kennytm . Test case added.

File: src/libsyntax/parse/parser.rs [hunk 1]
```diff
@@ -2700,6 +2700,17 @@ impl<'a> Parser<'a> {
...
                 (span, self.mk_unary(UnOp::Not, e))
             }
+            // fix issue #41679: Suggest `!` for bitwise negation when encountering a `~`
+            token::Tilde => {
+                self.bump();
+                let e = self.parse_prefix_expr(None);
+                let (span, e) = self.interpolated_or_expr_span(e)?;
+                let mut err = self.diagnostic().struct_span_err(lo.to(span),
+                        "`~` can not be used as an unary operator");
+                err.help("use `!` instead of `~` if you meant to bitwise negation");
```
Comment (petrochenkov) [inline src/libsyntax/parse/parser.rs]: Could you also add `err.span_label(span_of_tilda, "did you mean `!`?")` and use `span_of_tilda` for the primary error as well?

Comment (petrochenkov) [inline src/libsyntax/parse/parser.rs]: >meant to bitwise negation

Redundant "to"

File: src/libsyntax/parse/parser.rs [hunk 2]
```diff
@@ -2700,6 +2700,17 @@ impl<'a> Parser<'a> {
                 let (span, e) = self.interpolated_or_expr_span(e)?;
                 (span, self.mk_unary(UnOp::Not, e))
             }
+            // fix issue #41679: Suggest `!` for bitwise negation when encountering a `~`
```
Comment (petrochenkov) [inline src/libsyntax/parse/parser.rs]: Nit: could you remove "fix issue #41679:"? (Not useful for a reader and the history is available from git if necessary.)

File: src/libsyntax/parse/token.rs [hunk 3]
```diff
@@ -201,6 +201,7 @@ impl Token {
             OpenDelim(..)               => true, // tuple, array or block
             Literal(..)                 => true, // literal
             Not                         => true, // operator not
+            Tilde                       => true, // operator not (incorrect)
```
Comment (petrochenkov) [inline src/libsyntax/parse/token.rs]: This is slightly risky, `can_begin_expr` can affect syntax accepted by parser in general, not only diagnostics.
`~` is not used anywhere right now, so it's ok for now, but it may be used in the future.

**Comment by nagisa** [comment]
I had hoped we could avoid adding a token here.

@petrochenkov I did use `~` a number of times as a separator in macros by example. You sure there’s no way it will affect them?

File: src/libsyntax/parse/parser.rs (hunk 1 above)
Comment (retep998) [inline src/libsyntax/parse/parser.rs]: >meant to bitwise negation

Alternatively `meant to perform bitwise negation`.

**Comment by estebank** [comment]
> I had hoped we could avoid adding a token here.

@nagisa [`Tilde` is already a token](https://github.com/rust-lang/rust/pull/41722/files#diff-74b5ba63896c56c0964426955d2700d1L134), it wasn't added in this PR.

File: src/libsyntax/parse/parser.rs (hunk 1 above)
Comment (F001) [inline src/libsyntax/parse/parser.rs]: Fixed. Thanks.

File: src/libsyntax/parse/parser.rs (hunk 2 above)
Comment (F001) [inline src/libsyntax/parse/parser.rs]: Ok.

File: src/libsyntax/parse/token.rs (hunk 3 above)
Comment (F001) [inline src/libsyntax/parse/token.rs]: Yeah, I agree. I have deleted this line, and the test works fine. At least for this case, it is not necessary  to modify `can_begin_expr` .

**Comment by F001** [comment]
@aidanhs  Comments are resolved. Do you have other concerns?

**Comment by petrochenkov** [comment]
@nagisa 
I could imagine this breaking something like
```rust
macro_rules! m {
    ($x: expr) => {};
    (~ $x: expr) => {};
}

fn main() {
    m!(~x); // ERROR expected expression, found `~`
}
```
but it doesn't seem to work already.

File: src/libsyntax/parse/token.rs (hunk 3 above)
Comment (petrochenkov) [inline src/libsyntax/parse/token.rs]: This will remove the suggestion from something like `return ~0`, but that's more or less ok.

File: src/libsyntax/parse/parser.rs (hunk 1 above)
Comment (petrochenkov) [inline src/libsyntax/parse/parser.rs]: By `span_of_tilda` I actually meant the span of `~` itself (`let span_of_tilda = self.span; self.bump();`)

**Comment by petrochenkov** [comment]
r=me modulo https://github.com/rust-lang/rust/pull/41722#discussion_r114765205

**Comment by F001** [comment]
r? @petrochenkov 
Thanks very much for your patient guidance!

File: src/libsyntax/parse/parser.rs [hunk 4]
```diff
@@ -2700,6 +2700,19 @@ impl<'a> Parser<'a> {
...
                 (span, self.mk_unary(UnOp::Not, e))
             }
+            // Suggest `!` for bitwise negation when encountering a `~`
+            token::Tilde => {
+                self.bump();
+                let e = self.parse_prefix_expr(None);
+                let (span, e) = self.interpolated_or_expr_span(e)?;
+                let span_of_tilde = lo;
+                let mut err = self.diagnostic().struct_span_err(span_of_tilde,
+                        "`~` can not be used as an unary operator");
```
Comment (acdenisSK) [inline src/libsyntax/parse/parser.rs]: Bit of a late review, but won't hurt. Anyway, this should be using "a" because unary doesn't start with a vowel *sound* (As in, it starts with "you").

**Review by arqunis — CHANGES_REQUESTED** [review]

File: src/libsyntax/parse/parser.rs (hunk 4 above)
Comment (bstrie) [inline src/libsyntax/parse/parser.rs]: @acdenisSK Looks like this PR has already been merged, would you like to submit a minor PR to fix this?

Comment (acdenisSK) [inline src/libsyntax/parse/parser.rs]: Ah, i guess, gimme a sec.

**Comment by lfairy** [comment]
@petrochenkov I believe that's covered by #27832
