### PR TITLE
Handle race when coloring nodes concurrently as both green and red

### LINKED ISSUE #142778: ICE: rustc_query_system: dep_graph: assertion failed (dep node index out of range)
No idea how it came into existence, but people in rust discord said it's better to submit the bug.
The code can be found [here](https://github.com/olekspickle/bevy_new_third_person), but I only stumbled on it once so it is not reproducible at least for me.

Version info:
```
rustc 1.89.0-nightly (c68340350 2025-06-18)
binary: rustc
commit-hash: c68340350c78eea402c4a85f8d9c1b7d3d607635
commit-date: 2025-06-18
host: x86_64-unknown-linux-gnu
release: 1.89.0-nightly
LLVM version: 20.1.7
```

Compiler flags:

```
--crate-type lib -C opt-level=1 -C embed-bitcode=no -Z codegen-backend=cranelift -C debuginfo=2 -C debug-assertions=on -C linker=clang -C incremental=[REDACTED] -Z unstable-options -C link-arg=-fuse-ld=mold -Z share-generics=y -Z threads=0
```

Compiler output:

```
thread 'rustc' panicked at /rustc-dev/c68340350c78eea402c4a85f8d9c1b7d3d607635/compiler/rustc_query_system/src/dep_graph/graph.rs:43:1:
assertion failed: value <= 0xFFFF_FF00
```

<details><summary>Full compiler output</summary>

```
thread 'rustc' panicked at /rustc-dev/c68340350c78eea402c4a85f8d9c1b7d3d607635/compiler/rustc_query_system/src/dep_graph/graph.rs:43:1:
assertion failed: value <= 0xFFFF_FF00
stack backtrace:
   0:     0x7a7d6bed9b75 - std::backtrace::Backtrace::create::he5af7a5d59a40e3c
   1:     0x7a7d6bed9ac5 - std::backtrace::Backtrace::force_capture::hcea9d7ed40ac797f
   2:     0x7a7d6afe5e45 - std[f465230902baf24e]::panicking::update_hook::<alloc[5a24e98c206f3295]::boxed::Box<rustc_driver_impl[f7eaba4e4346ab0a]::install_ice_hook::{closure#1}>>::{closure#0}
   3:     0x7a7d6bef3d63 - std::panicking::rust_panic_with_hook::hccb645e1224c3ca9
   4:     0x7a7d6bef3a26 - std::panicking::begin_panic_handler::{{closure}}::h08eda9fea8547d73
   5:     0x7a7d6beeff89 - std::sys::backtrace::__rust_end_short_backtrace::h6189b6d534638e87
   6:     0x7a7d6bef373d - __rustc[f040de39e224b0e1]::rust_begin_unwind
   7:     0x7a7d686987c0 - core::panicking::panic_fmt::hb65b230fa9b6abb2
   8:     0x7a7d6880c97c - core::panicking::panic::h8ea9db73ed4f9b31
   9:     0x7a7d6c625d9f - <rustc_query_system[aa99c3eb613fb748]::dep_graph::graph::DepGraphData<rustc_middle[cb74f7c7c36a888d]::dep_graph::DepsType>>::try_mark_previous_green::<rustc_query_impl[48702a16f9c597ba]::plumbing::QueryCtxt>
  10:     0x7a7d6c6257cc - <rustc_query_system[aa99c3eb613fb748]::dep_graph::graph::DepGraphData<rustc_middle[cb74f7c7c36a888d]::dep_graph::DepsType>>::try_mark_previous_green::<rustc_query_impl[48702a16f9c597ba]::plumbing::QueryCtxt>
  11:     0x7a7d6c6257cc - <rustc_query_system[aa99c3eb613fb748]::dep_graph::graph::DepGraphData<rustc_middle[cb74f7c7c36a888d]::dep_graph::DepsType>>::try_mark_previous_green::<rustc_query_impl[48702a16f9c597ba]::plumbing::QueryCtxt>
  12:     0x7a7d6c7bd3fe - rustc_query_system[aa99c3eb613fb748]::query::plumbing::ensure_must_run::<rustc_query_impl[48702a16f9c597ba]::DynamicConfig<rustc_data_structures[99add3e81104b44c]::vec_cache::VecCache<rustc_span[386b88b018424990]::def_id::LocalDefId, rustc_middle[cb74f7c7c36a888d]::query::erase::Erased<[u8; 0usize]>, rustc_query_system[aa99c3eb613fb748]::dep_graph::graph::DepNodeIndex>, false, false, false>, rustc_query_impl[48702a16f9c597ba]::plumbing::QueryCtxt>
  13:     0x7a7d6c7bd758 - rustc_query_impl[48702a16f9c597ba]::query_impl::mir_drops_elaborated_and_const_checked::get_query_incr::__rust_end_short_backtrace
  14:     0x7a7d6cf64586 - <rustc_middle[cb74f7c7c36a888d]::ty::context::TyCtxt>::par_hir_body_owners::<rustc_interface[df2f81cb2296ca6c]::passes::run_required_analyses::{closure#1}::{closure#0}>::{closure#0}
  15:     0x7a7d6b3cf63c - rustc_data_structures[99add3e81104b44c]::sync::parallel::par_slice::par_rec::<&rustc_span[386b88b018424990]::def_id::LocalDefId, rustc_data_structures[99add3e81104b44c]::sync::parallel::par_for_each_in<&rustc_span[386b88b018424990]::def_id::LocalDefId, &[rustc_span[386b88b018424990]::def_id::LocalDefId], <rustc_middle[cb74f7c7c36a888d]::ty::context::TyCtxt>::par_hir_body_owners<rustc_interface[df2f81cb2296ca6c]::passes::run_required_analyses::{closure#1}::{closure#0}>::{closure#0}>::{closure#0}::{closure#0}>
  16:     0x7a7d6b3e6318 - rayon_core[91bb91cfcd883918]::join::join_context::<rayon_core[91bb91cfcd883918]::join::join::call<(), rustc_data_structures[99add3e81104b44c]::sync::parallel::par_slice::par_rec<&rustc_span[386b88b018424990]::def_id::LocalDefId, rustc_data_structures[99add3e81104b44c]::sync::parallel::par_for_each_in<&rustc_span[386b88b018424990]::def_id::LocalDefId, &[rustc_span[386b88b018424990]::def_id::LocalDefId], <rustc_middle[cb74f7c7c36a888d]::ty::context::TyCtxt>::par_hir_body_owners<rustc_interface[df2f81cb2296ca6c]::passes::run_required_analyses::{closure#1}::{closure#0}>::{closure#0}>::{closure#0}::{closure#0}>::{closure#1}>::{closure#0}, rayon_core[91bb91cfcd883918]::join::join::call<(), rustc_data_structures[99add3e81104b44c]::sync::parallel::par_slice::par_rec<&rustc_span[386b88b018424990]::def_id::LocalDefId, rustc_data_structures[99add3e81104b44c]::sync::parallel::par_for_each_in<&rustc_span[386b88b018424990]::def_id::LocalDefId, &[rustc_span[386b88b018424990]::def_id::LocalDefId], <rustc_middle[cb74f7c7c36a888d]::ty::context::TyCtxt>::par_hir_body_owners<rustc_interface[df2f81cb2296ca6c]::passes::run_required_analyses::{closure#1}::{closure#0}>::{closure#0}>::{closure#0}::{closure#0}>::{closure#2}>::{closure#0}, (), ()>::{closure#0}
  17:     0x7a7d6b3cf6da - rustc_data_structures[99add3e81104b44c]::sync::parallel::par_slice::par_rec::<&rustc_span[386b88b018424990]::def_id::LocalDefId, rustc_data_structures[99add3e81104b44c]::sync::parallel::par_for_each_in<&rustc_span[386b88b018424990]::def_id::LocalDefId, &[rustc_span[386b88b018424990]::def_id::LocalDefId], <rustc_middle[cb74f7c7c36a888d]::ty::context::TyCtxt>::par_hir_body_owners<rustc_interface[df2f81cb2296ca6c]::passes::run_required_analyses::{closure#1}::{closure#0}>::{closure#0}>::{closure#0}::{closure#0}>
  18:     0x7a7d6b400260 - <rayon_core[91bb91cfcd883918]::job::StackJob<rayon_core[91bb91cfcd883918]::latch::SpinLatch, rayon_core[91bb91cfcd883918]::join::join_context::call_b<(), rayon_core[91bb91cfcd883918]::join::join::call<(), rustc_data_structures[99add3e81104b44c]::sync::parallel::par_slice::par_rec<&rustc_span[386b88b018424990]::def_id::LocalDefId, rustc_data_structures[99add3e81104b44c]::sync::parallel::par_for_each_in<&rustc_span[386b88b018424990]::def_id::LocalDefId, &[rustc_span[386b88b018424990]::def_id::LocalDefId], <rustc_middle[cb74f7c7c36a888d]::ty::context::TyCtxt>::par_hir_body_owners<rustc_interface[df2f81cb2296ca6c]::passes::run_required_analyses::{closure#1}::{closure#0}>::{closure#0}>::{closure#0}::{closure#0}>::{closure#2}>::{closure#0}>::{closure#0}, ()> as rayon_core[91bb91cfcd883918]::job::Job>::execute
  19:     0x7a7d6aaf540e - <rayon_core[91bb91cfcd883918]::registry::WorkerThread>::wait_until_cold
  20:     0x7a7d6b3e63a2 - rayon_core[91bb91cfcd883918]::join::join_context::<rayon_core[91bb91cfcd883918]::join::join::call<(), rustc_data_structures[99add3e81104b44c]::sync::parallel::par_slice::par_rec<&rustc_span[386b88b018424990]::def_id::LocalDefId, rustc_data_structures[99add3e81104b44c]::sync::parallel::par_for_each_in<&rustc_span[386b88b018424990]::def_id::LocalDefId, &[rustc_span[386b88b018424990]::def_id::LocalDefId], <rustc_middle[cb74f7c7c36a888d]::ty::context::TyCtxt>::par_hir_body_owners<rustc_interface[df2f81cb2296ca6c]::passes::run_required_analyses::{closure#1}::{closure#0}>::{closure#0}>::{closure#0}::{closure#0}>::{closure#1}>::{closure#0}, rayon_core[91bb91cfcd883918]::join::join::call<(), rustc_data_structures[99add3e81104b44c]::sync::parallel::par_slice::par_rec<&rustc_span[386b88b018424990]::def_id::LocalDefId, rustc_data_structures[99add3e81104b44c]::sync::parallel::par_for_each_in<&rustc_span[386b88b018424990]::def_id::LocalDefId, &[rustc_span[386b88b018424990]::def_id::LocalDefId], <rustc_middle[cb74f7c7c36a888d]::ty::context::TyCtxt>::par_hir_body_owners<rustc_interface[df2f81cb2296ca6c]::passes::run_required_analyses::{closure#1}::{closure#0}>::{closure#0}>::{closure#0}::{closure#0}>::{closure#2}>::{closure#0}, (), ()>::{closure#0}
  21:     0x7a7d6b3cf6da - rustc_data_structures[99add3e81104b44c]::sync::parallel::par_slice::par_rec::<&rustc_span[386b88b018424990]::def_id::LocalDefId, rustc_data_structures[99add3e81104b44c]::sync::parallel::par_for_each_in<&rustc_span[386b88b018424990]::def_id::LocalDefId, &[rustc_span[386b88b018424990]::def_id::LocalDefId], <rustc_middle[cb74f7c7c36a888d]::ty::context::TyCtxt>::par_hir_body_owners<rustc_interface[df2f81cb2296ca6c]::passes::run_required_analyses::{closure#1}::{closure#0}>::{closure#0}>::{closure#0}::{closure#0}>
  22:     0x7a7d6b3e62a9 - rayon_core[91bb91cfcd883918]::join::join_context::<rayon_core[91bb91cfcd883918]::join::join::call<(), rustc_data_structures[99add3e81104b44c]::sync::parallel::par_slice::par_rec<&rustc_span[386b88b018424990]::def_id::LocalDefId, rustc_data_structures[99add3e81104b44c]::sync::parallel::par_for_each_in<&rustc_span[386b88b018424990]::def_id::LocalDefId, &[rustc_span[386b88b018424990]::def_id::LocalDefId], <rustc_middle[cb74f7c7c36a888d]::ty::context::TyCtxt>::par_hir_body_owners<rustc_interface[df2f81cb2296ca6c]::passes::run_required_analyses::{closure#1}::{closure#0}>::{closure#0}>::{closure#0}::{closure#0}>::{closure#1}>::{closure#0}, rayon_core[91bb91cfcd883918]::join::join::call<(), rustc_data_structures[99add3e81104b44c]::sync::parallel::par_slice::par_rec<&rustc_span[386b88b018424990]::def_id::LocalDefId, rustc_data_structures[99add3e81104b44c]::sync::parallel::par_for_each_in<&rustc_span[386b88b018424990]::def_id::LocalDefId, &[rustc_span[386b88b018424990]::def_id::LocalDefId], <rustc_middle[cb74f7c7c36a888d]::ty::context::TyCtxt>::par_hir_body_owners<rustc_interface[df2f81cb2296ca6c]::passes::run_required_analyses::{closure#1}::{closure#0}>::{closure#0}>::{closure#0}::{closure#0}>::{closure#2}>::{closure#0}, (), ()>::{closure#0}
  23:     0x7a7d6b3cf6da - rustc_data_structures[99add3e81104b44c]::sync::parallel::par_slice::par_rec::<&rustc_span[386b88b018424990]::def_id::LocalDefId, rustc_data_structures[99add3e81104b44c]::sync::parallel::par_for_each_in<&rustc_span[386b88b018424990]::def_id::LocalDefId, &[rustc_span[386b88b018424990]::def_id::LocalDefId], <rustc_middle[cb74f7c7c36a888d]::ty::context::TyCtxt>::par_hir_body_owners<rustc_interface[df2f81cb2296ca6c]::passes::run_required_analyses::{closure#1}::{closure#0}>::{closure#0}>::{closure#0}::{closure#0}>
  24:     0x7a7d6b400260 - <rayon_core[91bb91cfcd883918]::job::StackJob<rayon_core[91bb91cfcd883918]::latch::SpinLatch, rayon_core[91bb91cfcd883918]::join::join_context::call_b<(), rayon_core[91bb91cfcd883918]::join::join::call<(), rustc_data_structures[99add3e81104b44c]::sync::parallel::par_slice::par_rec<&rustc_span[386b88b018424990]::def_id::LocalDefId, rustc_data_structures[99add3e81104b44c]::sync::parallel::par_for_each_in<&rustc_span[386b88b018424990]::def_id::LocalDefId, &[rustc_span[386b88b018424990]::def_id::LocalDefId], <rustc_middle[cb74f7c7c36a888d]::ty::context::TyCtxt>::par_hir_body_owners<rustc_interface[df2f81cb2296ca6c]::passes::run_required_analyses::{closure#1}::{closure#0}>::{closure#0}>::{closure#0}::{closure#0}>::{closure#2}>::{closure#0}>::{closure#0}, ()> as rayon_core[91bb91cfcd883918]::job::Job>::execute
  25:     0x7a7d6aaf540e - <rayon_core[91bb91cfcd883918]::registry::WorkerThread>::wait_until_cold
  26:     0x7a7d6aaf2e21 - <rayon_core[91bb91cfcd883918]::registry::ThreadBuilder>::run
  27:     0x7a7d6afdbb7d - std[f465230902baf24e]::sys::backtrace::__rust_begin_short_backtrace::<<rayon_core[91bb91cfcd883918]::ThreadPoolBuilder>::build_scoped<rustc_interface[df2f81cb2296ca6c]::util::run_in_thread_pool_with_globals<rustc_interface[df2f81cb2296ca6c]::interface::run_compiler<(), rustc_driver_impl[f7eaba4e4346ab0a]::run_compiler::{closure#0}>::{closure#1}, ()>::{closure#5}::{closure#0}::{closure#0}, rustc_interface[df2f81cb2296ca6c]::util::run_in_thread_pool_with_globals<rustc_interface[df2f81cb2296ca6c]::interface::run_compiler<(), rustc_driver_impl[f7eaba4e4346ab0a]::run_compiler::{closure#0}>::{closure#1}, ()>::{closure#5}::{closure#0}::{closure#1}, ()>::{closure#0}::{closure#0}::{closure#0}, ()>
  28:     0x7a7d6afea532 - <<std[f465230902baf24e]::thread::Builder>::spawn_unchecked_<<rayon_core[91bb91cfcd883918]::ThreadPoolBuilder>::build_scoped<rustc_interface[df2f81cb2296ca6c]::util::run_in_thread_pool_with_globals<rustc_interface[df2f81cb2296ca6c]::interface::run_compiler<(), rustc_driver_impl[f7eaba4e4346ab0a]::run_compiler::{closure#0}>::{closure#1}, ()>::{closure#5}::{closure#0}::{closure#0}, rustc_interface[df2f81cb2296ca6c]::util::run_in_thread_pool_with_globals<rustc_interface[df2f81cb2296ca6c]::interface::run_compiler<(), rustc_driver_impl[f7eaba4e4346ab0a]::run_compiler::{closure#0}>::{closure#1}, ()>::{closure#5}::{closure#0}::{closure#1}, ()>::{closure#0}::{closure#0}::{closure#0}, ()>::{closure#1} as core[f335c14d4392cab8]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  29:     0x7a7d6d835083 - std::sys::pal::unix::thread::Thread::new::thread_start::hdee893a02c3d3f2e
  30:     0x7a7d6709caa4 - start_thread
                               at ./nptl/pthread_create.c:447:8
  31:     0x7a7d67129c3c - clone3
                               at ./misc/../sysdeps/unix/sysv/linux/x86_64/clone3.S:78:0
  32:                0x0 - <unknown>


rustc version: 1.89.0-nightly (c68340350 2025-06-18)
platform: x86_64-unknown-linux-gnu

query stack during panic:
#0 [analysis] running analysis passes on this crate
end of query stack
```

[rustc-ice-2025-06-19T12_41_08-530758.txt](https://github.com/user-attachments/files/20835584/rustc-ice-2025-06-19T12_41_08-530758.txt)

</details>

### LINKED ISSUE #150018: assertion failed: trying to encode a dep node twice
As I've suspected #149916 revealed a bug in rustc's query system on multiple threads. I was trying to build rustc itself with the nightly toolchain as stage0 after doing `git checkout` build fails while trying to compile `rustc_lint_defs`.

### Error

```
thread 'rustc' (199561) panicked at compiler/rustc_query_system/src/dep_graph/graph.rs:1392:9:
assertion `left == right` failed: trying to encode a dep node twice
  left: 64535
 right: 4294967295
```

<details>

<summary> backtrace </summary>

```
stack backtrace:
   0: __rustc::rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::panicking::assert_failed_inner
   3: core::panicking::assert_failed::<u32, u32>
   4: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::DynamicConfig<rustc_data_structures::vec_cache::VecCache<rustc_span::def_id::LocalDefId, rustc_middle::query::erase::Erased<[u8; 8]>, rustc_query_system::dep_graph::graph::DepNodeIndex>, false, false, false>, rustc_query_impl::plumbing::QueryCtxt, true>
   5: rustc_query_impl::plumbing::force_from_dep_node::<rustc_query_impl::DynamicConfig<rustc_data_structures::vec_cache::VecCache<rustc_span::def_id::LocalDefId, rustc_middle::query::erase::Erased<[u8; 8]>, rustc_query_system::dep_graph::graph::DepNodeIndex>, false, false, false>>
   6: <rustc_query_impl::plumbing::query_callback<rustc_query_impl::query_impl::mir_drops_elaborated_and_const_checked::QueryType>::{closure#0} as core::ops::function::FnOnce<(rustc_middle::ty::context::TyCtxt, rustc_query_system::dep_graph::dep_node::DepNode, rustc_query_system::dep_graph::serialized::SerializedDepNodeIndex)>>::call_once
   7: <rustc_query_system::dep_graph::graph::DepGraphData<rustc_middle::dep_graph::DepsType>>::try_mark_previous_green::<rustc_query_impl::plumbing::QueryCtxt>
   8: <rustc_query_system::dep_graph::graph::DepGraphData<rustc_middle::dep_graph::DepsType>>::try_mark_previous_green::<rustc_query_impl::plumbing::QueryCtxt>
   9: <rustc_query_system::dep_graph::graph::DepGraphData<rustc_middle::dep_graph::DepsType>>::try_mark_previous_green::<rustc_query_impl::plumbing::QueryCtxt>
  10: <rustc_query_system::dep_graph::graph::DepGraphData<rustc_middle::dep_graph::DepsType>>::try_mark_previous_green::<rustc_query_impl::plumbing::QueryCtxt>
  11: <rustc_query_system::dep_graph::graph::DepGraphData<rustc_middle::dep_graph::DepsType>>::try_mark_green::<rustc_query_impl::plumbing::QueryCtxt>
  12: rustc_query_system::query::plumbing::ensure_must_run::<rustc_query_impl::DynamicConfig<rustc_query_system::query::caches::DefIdCache<rustc_middle::query::erase::Erased<[u8; 32]>>, false, false, false>, rustc_query_impl::plumbing::QueryCtxt>
  13: <rustc_middle::ty::context::TyCtxt>::par_hir_body_owners::<rustc_hir_analysis::check_crate::{closure#2}>::{closure#0}
  14: rustc_data_structures::sync::parallel::par_slice::par_rec::<&rustc_span::def_id::LocalDefId, rustc_data_structures::sync::parallel::par_for_each_in<&rustc_span::def_id::LocalDefId, &[rustc_span::def_id::LocalDefId], <rustc_middle::ty::context::TyCtxt>::par_hir_body_owners<rustc_hir_analysis::check_crate::{closure#2}>::{closure#0}>::{closure#0}::{closure#0}>
  15: <rustc_thread_pool::job::StackJob<rustc_thread_pool::latch::SpinLatch, rustc_thread_pool::join::join_context<rustc_thread_pool::join::join::call<(), rustc_data_structures::sync::parallel::par_slice::par_rec<&rustc_span::def_id::LocalDefId, rustc_data_structures::sync::parallel::par_for_each_in<&rustc_span::def_id::LocalDefId, &[rustc_span::def_id::LocalDefId], <rustc_middle::ty::context::TyCtxt>::par_hir_body_owners<rustc_hir_analysis::check_crate::{closure#2}>::{closure#0}>::{closure#0}::{closure#0}>::{closure#1}>::{closure#0}, rustc_thread_pool::join::join::call<(), rustc_data_structures::sync::parallel::par_slice::par_rec<&rustc_span::def_id::LocalDefId, rustc_data_structures::sync::parallel::par_for_each_in<&rustc_span::def_id::LocalDefId, &[rustc_span::def_id::LocalDefId], <rustc_middle::ty::context::TyCtxt>::par_hir_body_owners<rustc_hir_analysis::check_crate::{closure#2}>::{closure#0}>::{closure#0}::{closure#0}>::{closure#2}>::{closure#0}, (), ()>::{closure#0}::{closure#0}, ()> as rustc_thread_pool::job::Job>::execute
  16: <rustc_thread_pool::registry::WorkerThread>::wait_or_steal_until_cold
  17: <rustc_thread_pool::registry::ThreadBuilder>::run
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

error: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: please make sure that you have updated to the latest nightly

note: please attach the file at `/home/huawei/dev/rust/rustc-ice-2025-12-15T10_49_29-199385.txt` to your bug report

note: compiler flags: --crate-type lib -C opt-level=3 -C embed-bitcode=no -C debuginfo=line-tables-only -C debug-assertions=on -C incremental=[REDACTED] -C symbol-mangling-version=v0 -Z annotate-moves -Z unstable-options -Z macro-backtrace -C split-debuginfo=off -C force-frame-pointers=true -C llvm-args=-import-instr-limit=10 -C link-args=-Wl,-z,origin -C link-args=-Wl,-rpath,$ORIGIN/../lib -Z on-broken-pipe=kill -C lto=off -Z threads=24 -Z binary-dep-depinfo -Z tls-model=initial-exec -Z force-unstable-if-unmarked

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [mir_drops_elaborated_and_const_checked] elaborating drops for `<impl at compiler/rustc_lint_defs/src/lib.rs:557:1: 557:10>::default_fields_for_macro`
#1 [analysis] running analysis passes on crate `rustc_lint_defs`
end of query stack
there was a panic while trying to force a dep node
try_mark_green dep node stack:
#0 mir_for_ctfe(rustc_lint_defs[912f]::{impl#9}::default_fields_for_macro)
#1 eval_to_allocation_raw(6a497d626948f9b4-2f772ebace64724b)
#2 eval_to_const_value_raw(6a497d626948f9b4-2f772ebace64724b)
#3 eval_static_initializer(rustc_lint_defs[912f]::builtin::UNCONDITIONAL_PANIC)
end of try_mark_green dep node stack
error: could not compile `rustc_lint_defs` (lib)
```

</details>

It is surprisingly persistent as and ~~I was unable to get it go away just by retriggering the incremental compilation using `touch src/lib.rs` but deleting `incremental` folder fixes this per usual~~ after some rebuilds goes away. We can infer from the error that compiler finds itself in a situation where it tries to mark one dep node as both green and red.

### Rust version

Stage 0:

```
rustc 1.94.0-nightly (0208ee09b 2025-12-14)
binary: rustc
commit-hash: 0208ee09be465f69005a7a12c28d5eccac7d5f34
commit-date: 2025-12-14
host: x86_64-unknown-linux-gnu
release: 1.94.0-nightly
LLVM version: 21.1.5
```

### Steps to reproduce

Do a clean build `x build library --stage 1` at 52fda2e54f805722807c90e91ac3329fe9e7ccb3, then `git checkout` to ba45f0b7d89e3b0722b20d2d25292983a5120fea and without cleaning try rebuilding it the same way again. And don't forget to set `RUSTFLAGS_BOOTSTRAP` to `-Zthreads=n` where n > 1.

### PR DESCRIPTION
**Pull request by Zoxc**
This fixes a race where a duplicate dep node gets written to the dep graph if a node was marked as green and promoted during execution, then marked as red after execution.

This can occur when a `no_hash` query A depends on a query B which cannot be forced so it was not colored when starting execution of query A. During the execution of query A it will execute query B and color it green. Before A finishes another thread tries to mark A green, this time succeeding as B is now green, and A gets promoted and written to metadata. Execution of A then finishes and because it's `no_hash` we assume the result changed and thus we color the node again, now as red and write it to metadata again. This doesn't happen with non-`no_hash` queries as they will be green if all their dependencies are green.

This changes the code coloring nodes red to also use `compare_exchange` to deal with this race ensuring that the coloring of nodes only happens once.

Fixes rust-lang/rust#150018
Fixes rust-lang/rust#142778
Fixes rust-lang/rust#141540

### CODE REVIEW

**Comment by Zoxc** [comment]
As discussed in [Solving big #141540 issue and hunt for bad metadata files](https://rust-lang.zulipchat.com/#narrow/channel/187679-t-compiler.2Fparallel-rustc/topic/Solving.20big.20.23141540.20issue.20and.20hunt.20for.20bad.20metadata.20files/with/554069479), I think the trait selection cache can leave nodes uncolored after execution. This means that we're not able to tell if dependencies are all green in all cases and https://github.com/rust-lang/rust/pull/150156 would be insufficient to fix the race.

File: compiler/rustc_query_system/src/dep_graph/graph.rs [hunk 1]
```diff
@@ -776,17 +776,22 @@ impl<D: Deps> DepGraphData<D> {
         }
     }
 
-    fn promote_node_and_deps_to_current(&self, prev_index: SerializedDepNodeIndex) -> DepNodeIndex {
+    fn promote_node_and_deps_to_current(
+        &self,
+        prev_index: SerializedDepNodeIndex,
+    ) -> Option<DepNodeIndex> {
         self.current.debug_assert_not_in_new_nodes(&self.previous, prev_index);
```
Comment (zetanumbers) [inline compiler/rustc_query_system/src/dep_graph/graph.rs:783]: This check obviously fails with `debug_assertions` enabled.

**Review by zetanumbers — APPROVED** [review]
The `RwLock::try_write` call now fails in `Steal::steal` method.

https://github.com/zetanumbers/rust/blob/f60a0f1bcc5a2a6dd8eb2d2021da79b40f5fbae9/compiler/rustc_data_structures/src/steal.rs#L58

Otherwise this code is good.

*[View changes since this review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/rust/151509/55407b8cdb1457c62e0c852f5b53a9cf63ec4e1b..d8d4d4029fdcd993a77c9f1943cede7a7fe4c628)*

File: compiler/rustc_query_system/src/dep_graph/graph.rs (hunk 1 above)
Comment (Zoxc) [reply compiler/rustc_query_system/src/dep_graph/graph.rs:783]: Not sure what you mean by obviously, but the check is broken (before this PR) on the parallel compiler due to execution/mark-green races. I fixed one related bug in https://github.com/rust-lang/rust/pull/152067.

**Comment by zetanumbers** [comment]
Uuh, it's complicated. See last section of https://github.com/rust-lang/rust/issues/150018#issue-3729967465

File: compiler/rustc_query_system/src/dep_graph/graph.rs (hunk 1 above)
Comment (zetanumbers) [reply compiler/rustc_query_system/src/dep_graph/graph.rs:783]: Yeah, so neither your PR or #152067 fix this assertion's failure.
