### PR TITLE
Uplift `clippy::double_neg` lint as `double_negations`

### LINKED ISSUE #82987: Uplift clippy::double_neg into rustc
See this https://dtolnay.github.io/rust-quiz/17

I agree with our position on the inclusion of --/++ in Rust, however currently we just silently treat --i as -(-i), which means that users who are coming from C++ and C get absolutely no warning that their code is going to do something entirely different than they expect - and there's arguably no use case for an unbracketed - -i : its the same as a literal i.

I expected to see this happen:

A warning, or an error: "attempt to use unsupported post-increment operator. Use +=1 instead". Or something like that.

Instead, this happened: *explanation*

### Meta

I'm not sure what rustc version the rust-quiz website is running.

`rustc --version --verbose`:
```
<version>
```

<details><summary>Backtrace</summary>
<p>

```
<backtrace>
```

</p>
</details>

### PR DESCRIPTION
**Pull request by kadiwa4**
Warns about cases like this:
```rust
fn main() {
    let x = 1;
    let _b = --x; //~ WARN use of a double negation
}
```

The intent is to keep people from thinking that `--x` is a prefix decrement operator. `++x`, `x++` and `x--` are invalid expressions and already have a helpful diagnostic.

I didn't add a machine-applicable suggestion to the lint because it's not entirely clear what the programmer was trying to achieve with the `--x` operation. The code that triggers the lint should always be reviewed manually.

Closes #82987

### CODE REVIEW

File: compiler/rustc_lint/src/builtin.rs [hunk 1]
```diff
@@ -1627,6 +1627,51 @@ impl<'tcx> LateLintPass<'tcx> for TrivialConstraints {
...
+    /// prefix decrement operator.
+    DoubleNegation => [DOUBLE_NEGATION]
+);
+
+impl EarlyLintPass for DoubleNegation {
+    #[inline]
+    fn check_expr(&mut self, cx: &EarlyContext<'_>, expr: &ast::Expr) {
+        if let ExprKind::Unary(UnOp::Neg, ref inner) = expr.kind
+            && let ExprKind::Unary(UnOp::Neg, ref inner2) = inner.kind
+            && !matches!(inner2.kind, ExprKind::Unary(UnOp::Neg, _))
```
[the remark this answers is not in the document]
Comment (kadiwa4) [reply compiler/rustc_lint/src/builtin.rs:1668]: Without the `!matches` part, something like `--—x` would give you two warnings. One for the inner `--` and one for the outer `--`. All that the `!mathes` line does is disable the outer one.
The second-outermost `-` expression will be visted too and will give a warning.

[the remark this answers is not in the document]
Comment (nnethercote) [reply compiler/rustc_lint/src/builtin.rs:1668]: Aha, makes sense. That would be a good thing to put into a comment. Also, what happens with `----x`?

[the remark this answers is not in the document]
Comment (kadiwa4) [reply compiler/rustc_lint/src/builtin.rs:1668]: I'll add a comment.

`----x` will also lint exactly once. It turns out that in C++, `----x` is apparently valid syntax and would be understood as two decrements. So I guess we could emit two lints for that situation. But it doesn't really seem important enough, does it? ^^

File: compiler/rustc_lint/src/builtin.rs [hunk 2]
```diff
@@ -1635,6 +1627,51 @@ impl<'tcx> LateLintPass<'tcx> for TrivialConstraints {
...
+    ///
+    /// ### Explanation
+    ///
+    /// Negating something twice is usually the same as not negating it at all.
+    /// However, a double negation in Rust can easily be confused with the
+    /// prefix decrement operator that exists in many languages derived from C.
+    /// Use `-(-x)` if you really wanted to negate the value twice.
+    ///
+    /// To decrement a value, use `x -= 1` instead.
+    pub DOUBLE_NEGATION,
```
Comment (flip1995) [inline compiler/rustc_lint/src/builtin.rs:1652]: Better name, as by the lint naming conventions:
```suggestion
    pub DOUBLE_NEGATIONS,
```

Comment (kadiwa4) [reply compiler/rustc_lint/src/builtin.rs:1652]: You mean [this](https://rust-lang.github.io/rfcs/0344-conventions-galore.html#lints)? Because `#[allow(double_negation)]` seems grammatically fine to me. But I'll change it anyway, it does say that you should use plurals for lint names

**Comment by nnethercote** [comment]
This needs T-lang approval. The appropriate labels have been applied to summon them.

**Comment by nnethercote** [comment]
Still waiting on T-lang, AFAICT.

**Comment by joshtriplett** [comment]
Sorry that we've gone so long without seeing this.

With my lang hat on, I'm going to start an FCP confirming consensus on this. I'm hoping it'll be uncontroversial.

@rfcbot merge

**Comment by traviscross** [comment]
I looked around on GitHub for anyone using this.  The main use case I found is that people who have implemented `Neg` for a type then tend to write tests or fuzzing code that looks like this:

```rust
fn test_neg_is_own_inverse() {
    let x = MyType::new(..);
    assert_eq!(x, --x);
}
```

It's probably fine to use parentheses there.

@rfcbot reviewed

**Comment by nikomatsakis** [comment]
@rfcbot reviewed

I see no harm in writing `-(-x)` -- I would definitely prefer that.

File: src/tools/clippy/clippy_dev/src/new_lint.rs [hunk 3]
```diff
@@ -455,7 +455,7 @@ fn setup_mod_file(path: &Path, lint: &LintData<'_>) -> io::Result<&'static str>
     });
 
     // Find both the last lint declaration (declare_clippy_lint!) and the lint pass impl
-    while let Some(LintDeclSearchResult { content, .. }) = iter.find(|result| result.token == TokenKind::Ident) {
+    while let Some(LintDeclSearchResult { content, .. }) = iter.find(|result| result.token_kind == TokenKind::Ident) {
```
Comment (kadiwa4) [inline src/tools/clippy/clippy_dev/src/new_lint.rs:458]: These changes were necessary to get the clippy dev tool to compile

File: src/tools/clippy/tests/ui/rename.rs [hunk 4]
```diff
@@ -13,9 +13,8 @@
 #![allow(clippy::disallowed_methods)]
 #![allow(clippy::disallowed_types)]
 #![allow(clippy::mixed_read_write_in_expression)]
-#![allow(clippy::manual_find_map)]
 #![allow(clippy::manual_filter_map)]
-#![allow(unpredictable_function_pointer_comparisons)]
+#![allow(clippy::manual_find_map)]
```
Comment (kadiwa4) [inline src/tools/clippy/tests/ui/rename.rs:17]: This file is supposed to be auto-generated (it has a comment at the top saying so), but most people seem to edit it manually. I used the generator though, that's why so many lines are changed in this file.

**Comment by nnethercote** [comment]
Updated code looks fine to me. I think/hope this has gone through all the appropriate hoops and is ready to be merged.

@bors r+
