### PR TITLE
Fix #95079 unhelpful error when missing move in nested closure

### LINKED ISSUE #95079: unhelpful error when missing `move` in nested closure
Given the following code: https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=1cb8bf9552639abd2a8178105cd3f001

```rust
fn foo(s: &str) -> impl Iterator<Item = String> + '_ {
    None.into_iter()
        .flat_map(move |()| s.chars().map(|c| format!("{}{}", c, s)))
}
```

The current output is:

```
error: captured variable cannot escape `FnMut` closure body
 --> src/lib.rs:3:29
  |
1 | fn foo(s: &str) -> impl Iterator<Item = String> + '_ {
  |        - variable defined here
2 |     None.into_iter()
3 |         .flat_map(move |()| s.chars().map(|c| format!("{}{}", c, s)))
  |                           - -^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |                           | |
  |                           | returns a reference to a captured variable which escapes the closure body
  |                           | variable captured here
  |                           inferred to be a `FnMut` closure
  |
  = note: `FnMut` closures only have access to their captured variables while they are executing...
  = note: ...therefore, they cannot allow references to captured variables to escape

error: could not compile `playground` due to previous error
```
The actually needed fix here is the following, which should ideally be recommended
```rust
fn foo(s: &str) -> impl Iterator<Item = String> + '_ {
    None.into_iter()
        .flat_map(move |()| s.chars().map(move |c| format!("{}{}", c, s)))
}
```

### PR DESCRIPTION
**Pull request by yanchen4791**
Fix #95079 by adding help for missing move in nested closure

### CODE REVIEW

File: compiler/rustc_borrowck/src/diagnostics/region_name.rs [hunk 1]
```diff
@@ -179,6 +179,25 @@ impl RegionName {
...
         }
     }
+
+    pub(crate) fn highlight_region_name_suggestion(&self, diag: &mut Diagnostic) {
+        match &self.source {
+            RegionNameSource::AnonRegionFromOutput(
+                RegionNameHighlight::Occluded(span, type_name),
+                mir_description,
+            ) => {
+                if type_name[..4] == "Map<".to_string() {
```
Comment (compiler-errors) [inline compiler/rustc_borrowck/src/diagnostics/region_name.rs:189]: This probably does not work like it should.

File: src/test/ui/borrowck/issue-95079-missing-move-in-nested-closure.stderr [hunk 2]
```diff
@@ -0,0 +1,31 @@
...
+LL |         .flat_map(move |()| s.chars().map(|c| format!("{}{}", c, s)))
+   |                           - -^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
+   |                           | |
+   |                           | returns a reference to a captured variable which escapes the closure body
+   |                           | variable captured here
+   |                           inferred to be a `FnMut` closure
+   |
+   = note: `FnMut` closures only have access to their captured variables while they are executing...
+   = note: ...therefore, they cannot allow references to captured variables to escape
+   = help: consider adding 'move' keyword before the parameter of closure in `Map<Chars<'_>, [closure@$DIR/issue-95079-missing-move-in-nested-closure.rs:3:43: 3:46]>`
```
Comment (compiler-errors) [inline src/test/ui/borrowck/issue-95079-missing-move-in-nested-closure.stderr:16]: This suggestion still doesn't really make sense, or at least it does not draw my eyes to the inner `|c|` closure.

File: compiler/rustc_borrowck/src/diagnostics/region_name.rs [hunk 3]
```diff
@@ -179,6 +179,25 @@ impl RegionName {
             RegionNameSource::Static => {}
         }
     }
+
+    pub(crate) fn highlight_region_name_suggestion(&self, diag: &mut Diagnostic) {
```
Comment (compiler-errors) [inline compiler/rustc_borrowck/src/diagnostics/region_name.rs:183]: The name `highlight_region_name_suggestion` should be named something a bit more descriptive. In this case, perhaps something like `suggest_move_on_borrowing_closure`, but lots of names work.

File: compiler/rustc_borrowck/src/diagnostics/region_name.rs (hunk 1 above)
Comment (compiler-errors) [reply compiler/rustc_borrowck/src/diagnostics/region_name.rs:189]: That is, we shouldn't be using the typename to tell if we should make this suggestion. It also doesn't work for anything that isn't `Map<` -- lots of other combinators and functions have signatures almost identical to map and should be included in this suggestion.

**Review by compiler-errors — CHANGES_REQUESTED** [review]

File: src/test/ui/borrowck/issue-95079-missing-move-in-nested-closure.stderr (hunk 2 above)
Comment (compiler-errors) [reply src/test/ui/borrowck/issue-95079-missing-move-in-nested-closure.stderr:16]: Preferably we would have a structured suggestion here, like:

```
move |c| ...
++++
```

but it might not be possible in this stage of borrowck...

File: compiler/rustc_borrowck/src/diagnostics/region_name.rs (hunk 3 above)
Comment (yanchen4791) [reply compiler/rustc_borrowck/src/diagnostics/region_name.rs:183]: Sure, `suggest_move_on_borrowing_closure` is a meaningful name for this, since it is used for adding suggestion for cases when a nested closure outlives borrowed variables.

File: compiler/rustc_borrowck/src/diagnostics/region_name.rs (hunk 1 above)
Comment (yanchen4791) [reply compiler/rustc_borrowck/src/diagnostics/region_name.rs:189]: The reason of restricting to map() only (for now) is to exclude those cases when adding `move` is not a correct suggestion. For example, in the test case of #69446 (#72598), adding `move` is not a solution, although the error is the same:
```
error: captured variable cannot escape `FnMut` closure body
  --> /home/ychen/rust.7.22/rust/src/test/ui/async-await/issue-69446-fnmut-capture.rs:19:17
   |
18 |       let mut x = Foo;
   |           ----- variable defined here
19 |       bar(move || async { //~ ERROR captured
   |  _______________-_^
   | |               |
   | |               inferred to be a `FnMut` closure
20 | |         x.foo();
   | |         - variable captured here
21 | |     });
   | |_____^ returns an `async` block that contains a reference to a captured variable, which then escapes the closure body
   |
   = note: `FnMut` closures only have access to their captured variables while they are executing...
   = note: ...therefore, they cannot allow references to captured variables to escape
```
With test case, the signature of typename is "impl Future<Output = ()>".


For `move` keyword suggestion, I thought it is safer to use a "white list" of typename signatures for cases we know will work. such as "Map<" for map(), than use a "black list" to exclude cases we know will not work, like "impl Future" signature for `async`. We can add more signatures to "white list" for cases which can be fixed by adding `move` keyword for sure.

I am not sure if there is any other simple and clean way to tell if a case can be fixed by adding `move` keyword or not.

File: src/test/ui/borrowck/issue-95079-missing-move-in-nested-closure.stderr (hunk 2 above)
Comment (yanchen4791) [reply src/test/ui/borrowck/issue-95079-missing-move-in-nested-closure.stderr:16]: Yes, It is not clear enough. I will try to refine this by printing out exactly where to add `move` in the source.

I thought if users were aware of the line and column number as [closure@...3:43: 3:46] pointed out, they would be able to fig out where to add `move` :-)

**Comment by yanchen4791** [comment]
@compiler-errors Could you review my refined changes? Please see outputs in #95079, thanks!

File: compiler/rustc_borrowck/src/diagnostics/region_errors.rs [hunk 4]
```diff
@@ -899,4 +901,40 @@ impl<'a, 'tcx> MirBorrowckCtxt<'a, 'tcx> {
 
         suggest_adding_lifetime_params(self.infcx.tcx, sub, ty_sup, ty_sub, diag);
     }
+
+    fn suggest_move_on_borrowing_closure(&self, diag: &mut Diagnostic) {
+        let map = self.infcx.tcx.hir();
+        let hir_id = self.mir_hir_id();
+        let body_id = map.body_owned_by(hir_id);
+        let expr = &map.body(body_id).value;
```
Comment (compiler-errors) [inline compiler/rustc_borrowck/src/diagnostics/region_errors.rs:909]: This only works for functions that are of the form:

```
fn test() {
  || ...
}
```

or

```
fn test() {
  expr.method(|| ...)
```

This is not the right strategy, I think. It doesn't actually check that the closure here is part of the actual error, right?

Comment (yanchen4791) [reply compiler/rustc_borrowck/src/diagnostics/region_errors.rs:909]: Thanks for reviewing. This suggest function will be only called when the closure has been identified having the error of borrowing problem, and we have to find where is the beginning of the problematic closure. So we are sure it is problematic closure at this point already. Yes, the current code will only find the span of the closure with above forms (in method, or in block). We can add more forms if any. But worst case is that it will not print the suggestion if the form is not supported yet. Does this makes sense?

Comment (yanchen4791) [reply compiler/rustc_borrowck/src/diagnostics/region_errors.rs:909]: @compiler-errors Any comments/suggestions?

**Comment by compiler-errors** [comment]
This is fine to merge, and if it has lots of false positives then I guess we can adjust or remove it.

@yanchen4791 can you rebase this?

**Comment by yanchen4791** [comment]
@compiler-errors Thanks! It has been rebased to latest master.
