### PR TITLE
[std][BTree] Fix behavior of `::append` to match documentation, `::insert`, and `::extend`

### LINKED ISSUE #145614: `{BTreeMap,BTreeSet}::append` behaves differently to `::insert` and `::extend`
I tried this code:

```rust
#[derive(Debug, Clone)]
struct Key {
    id: u32,
    name: String,
}

use std::cmp::Ordering;

impl PartialEq for Key {
    fn eq(&self, other: &Self) -> bool {
        self.id == other.id
    }
}

impl Eq for Key {}

impl PartialOrd for Key {
    fn partial_cmp(&self, other: &Self) -> Option<Ordering> {
        Some(self.cmp(other))
    }
}

impl Ord for Key {
    fn cmp(&self, other: &Self) -> Ordering {
        self.id.cmp(&other.id)
    }
}

use std::collections::BTreeMap;

fn append(mut lhs: BTreeMap<Key, String>, mut rhs: BTreeMap<Key, String>) {
    lhs.append(&mut rhs);
    println!("append: {lhs:?}");
}
fn insert(mut lhs: BTreeMap<Key, String>, rhs: BTreeMap<Key, String>) {
    for (k, v) in rhs.into_iter() {
        lhs.insert(k, v);
    }
    println!("insert: {lhs:?}");
}

fn main() {
    let mut lhs = BTreeMap::new();
    let mut rhs = BTreeMap::new();

    lhs.insert(Key {
        id: 0,
        name: "lhs_k".to_string(),
    }, "lhs_v".to_string());
    rhs.insert(Key {
        id: 0,
        name: "rhs_k".to_string(),
    }, "rhs_v".to_string());

    append(lhs.clone(), rhs.clone());
    insert(lhs.clone(), rhs.clone());
}
```
The documentation for `BTreeMap::append` says [`If a key from other is already present in self, the respective value from self will be overwritten with the respective value from other.`](https://doc.rust-lang.org/std/collections/struct.BTreeMap.html#method.append). There is no mention of the overwriting of keys, which aligns with the documentation and behaviour of `BTreeMap::insert`. ([`If the map did have this key present, the value is updated, and the old value is returned. The key is not updated, though; this matters for types that can be == without being identical.`](https://doc.rust-lang.org/std/collections/struct.BTreeMap.html#method.insert))

Therefore, I expected to see this happen: 
```
append: {Key { id: 0, name: "lhs_k" }: "rhs_v"}
insert: {Key { id: 0, name: "lhs_k" }: "rhs_v"}
```

Instead, this happened:
```
append: {Key { id: 0, name: "rhs_k" }: "rhs_v"}
insert: {Key { id: 0, name: "lhs_k" }: "rhs_v"}
```

### Meta

Tested on Rust Playground: https://play.rust-lang.org/?version=stable&mode=debug&edition=2024&gist=fa5d69959152003932b622e9f57e9b5e

### PR DESCRIPTION
**Pull request by tinnamchoi**
Resolves rust-lang/rust#145614

### CODE REVIEW

File: library/alloc/src/collections/btree/append.rs [hunk 1]
```diff
@@ -107,6 +107,11 @@ where
     /// If two keys are equal, returns the key-value pair from the right source.
```
Comment (aDotInTheVoid) [inline library/alloc/src/collections/btree/append.rs]: This doc-comment should be updated.

**Comment by Mark-Simulacrum** [comment]
[`BTreeMap::append`](https://doc.rust-lang.org/nightly/std/collections/struct.BTreeMap.html#method.append) is documented as:

> Moves all elements from other into self, leaving other empty.
>
> If a key from other is already present in self, the respective value from self will be overwritten with the respective value from other.

This (IMO) leaves ambiguous whether equal (by Eq/Ord) keys are updated or not in the implementation. Today, append will update the key as well. This PR is proposing that we align the behavior with [`insert`](https://doc.rust-lang.org/nightly/std/collections/struct.BTreeMap.html#method.insert)'s, which is documented as **not** updating the key:

> If the map did have this key present, the value is updated, and the old value is returned. The key is not updated, though; this matters for types that can be == without being identical. See the [module-level documentation](https://doc.rust-lang.org/nightly/std/collections/index.html#insert-and-complex-keys) for more.

This is a breaking change, so nominating for libs-api. We can try running crater, but I'm not sure we'll find much signal given the specific conditions needed to trigger it (BTreeMap, using append, having keys with extra metadata, and writing a test reachable in Crater that exercises this case).

HashMap's `extend` impl uses `insert` internally, so it matches insert behavior. BTreeMap's `extend` *also* calls BTreeMap::insert in a loop and so does not match append today.

@tinnamchoi, can you also update the docs for append to reflect this change?

**Comment by Mark-Simulacrum** [comment]
@craterbot run mode=build-and-test

**Comment by Mark-Simulacrum** [comment]
@craterbot run crates=https://crater-reports.s3.amazonaws.com/pr-145628/retry-regressed-list.txt mode=build-and-test name=pr-145628-retry-1

**Comment by tinnamchoi** [comment]
Can this get a retry? 262 seems like a lot.

**Comment by Mark-Simulacrum** [comment]
@craterbot run crates=https://crater-reports.s3.amazonaws.com/pr-145628-retry-1/retry-regressed-list.txt mode=build-and-test name=pr-145628-retry-2

**Comment by Mark-Simulacrum** [comment]
Re-nominating for libs-api to see if any opinions have changed given Crater results which show at least one regression (see summary in previous comment).

**Comment by Amanieu** [comment]
Pinging @nickelc as the author of `modio`: what are your thoughts on the behavior of `append` here. It seems your code may be relying on behavior that is not explicitly documented.
