### PR TITLE
fix doc path in std::fmt macro

### LINKED ISSUE #137519: Broken doc links for standard library formatting macros
### Location

 `library/std/src/macros.rs`

### Summary

In `library/std/src/macros.rs`, the macros `print`, `println`, `eprint`, `eprintln` all contain the following doc comment:
- `/// See [the formatting documentation in `std::fmt`](../std/fmt/index.html)`

Which resolves to a broken link: [https://doc.rust-lang.org/stable/std/std/fmt/index.html](https://doc.rust-lang.org/stable/std/std/fmt/index.html).

Doc comments should be adjusted to: 
- `/// See [the formatting documentation in `std::fmt`](../fmt/index.html)`

Which would point to the correct online documentation [https://doc.rust-lang.org/stable/std/fmt/index.html](https://doc.rust-lang.org/stable/std/fmt/index.html).

Steps to reproduce: In VSCode, use any of the above macros, hover over the symbol name and click the (broken) link in the popup.

### PR DESCRIPTION
**Pull request by tapanprakasht**
fixes https://github.com/rust-lang/rust/issues/137519

### CODE REVIEW

File: library/std/src/macros.rs [hunk 1]
```diff
@@ -106,7 +106,7 @@ macro_rules! print {
 /// Use `println!` only for the primary output of your program. Use
 /// [`eprintln!`] instead to print error and progress messages.
 ///
-/// See [the formatting documentation in `std::fmt`](../std/fmt/index.html)
+/// See [the formatting documentation in `std::fmt`](../fmt/index.html)
```
Comment (bjorn3) [inline library/std/src/macros.rs:109]: That would make it point to https://doc.rust-lang.org/nightly/fmt/index.html, which is not valid. The current code works fine in the rustdoc generated html. I think rust-analyzer will need to be changed to correctly handle this link instead.

**Comment by Sky9x** [comment]
why is this using an html link in the first place? is there a reason you can't just link directly (ie. `[abc](crate::fmt)`)?

**Comment by bjorn3** [comment]
Likely because it was written before rustdoc supported linking to items.

**Comment by tapanprakasht** [comment]
@bjorn3 I have updated the links without using the direct html. I see using `crate::fmt` format finally linking it to `https://doc.rust-lang.org/nightly/alloc/fmt/index.html`. Is that okay?

**Comment by thomcc** [comment]
This looks good to me. To confirm, you've tested and it works (I don't see a reason that it wouldn't, but wish to make sure).

**Comment by tapanprakasht** [comment]
> This looks good to me. To confirm, you've tested and it works (I don't see a reason that it wouldn't, but wish to make sure).

Yes. I works

**Review by Sky9x — APPROVED** [review]
