### PR TITLE
skip updating when external binding is existed

### LINKED ISSUE #128813: ICE: `inconsistent resolution for an import`
### Code

```Rust
extern crate core;

fn useful_syntax() {
    use ::{{core}, {std}};
}

macro_rules! define_other_core {
    () => {
        extern crate std as core;
    };
}

define_other_core!();

fn main() {}
```
command: `rustc ./file.rs --edition=2021`

### Meta

`rustc --version --verbose`:
```
rustc 1.82.0-nightly (60d146580 2024-08-06)
binary: rustc
commit-hash: 60d146580c10036ce89e019422c6bc2fd9729b65
commit-date: 2024-08-06
host: x86_64-apple-darwin
release: 1.82.0-nightly
LLVM version: 19.1.0
```

### Error output

```
error[E0259]: the name `core` is defined multiple times
  --> ./12995.rs:9:9
   |
1  | extern crate core;
   | ------------------ previous import of the extern crate `core` here
...
9  |         extern crate std as core;
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^ `core` reimported here
...
13 | define_other_core!();
   | -------------------- in this macro invocation
   |
   = note: `core` must be defined only once in the type namespace of this module
   = note: this error originates in the macro `define_other_core` (in Nightly builds, run with -Z macro-backtrace for more info)
help: you can use `as` to change the binding name of the import
   |
9  |         extern crate std as other_core;
   |

```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
error: internal compiler error: compiler/rustc_resolve/src/imports.rs:1095:33: inconsistent resolution for an import
 --> ./12995.rs:4:13
  |
4 |     use ::{{core}, {std}};
  |             ^^^^

thread 'rustc' panicked at compiler/rustc_resolve/src/imports.rs:1095:33:
Box<dyn Any>
stack backtrace:
   0:        0x102a0a7f9 - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::hde541634c76c8424
   1:        0x102a5658b - core::fmt::write::h0a6995bfd5310686
   2:        0x1029ffa32 - std::io::Write::write_fmt::ha44463c63b65871a
   3:        0x102a0d0a8 - std::panicking::default_hook::{{closure}}::h8629ee341b692758
   4:        0x102a0ccee - std::panicking::default_hook::h8703f8d1cc197d13
   5:        0x10c06f0fd - std[513de39480af1bab]::panicking::update_hook::<alloc[88fbee91b568d05e]::boxed::Box<rustc_driver_impl[1a7a7dac5035a0ee]::install_ice_hook::{closure#0}>>::{closure#0}
   6:        0x102a0ded0 - std::panicking::rust_panic_with_hook::h68d7251319b974a6
   7:        0x10c0e28f7 - std[513de39480af1bab]::panicking::begin_panic::<rustc_errors[77d550dff4600411]::ExplicitBug>::{closure#0}
   8:        0x10c0ce7f9 - std[513de39480af1bab]::sys::backtrace::__rust_end_short_backtrace::<std[513de39480af1bab]::panicking::begin_panic<rustc_errors[77d550dff4600411]::ExplicitBug>::{closure#0}, !>
   9:        0x110ca0589 - std[513de39480af1bab]::panicking::begin_panic::<rustc_errors[77d550dff4600411]::ExplicitBug>
  10:        0x10c0f5466 - <rustc_errors[77d550dff4600411]::diagnostic::BugAbort as rustc_errors[77d550dff4600411]::diagnostic::EmissionGuarantee>::emit_producing_guarantee
  11:        0x10d7ced41 - <rustc_errors[77d550dff4600411]::DiagCtxtHandle>::span_bug::<rustc_span[af5dc13a57d4458]::span_encoding::Span, alloc[88fbee91b568d05e]::string::String>
  12:        0x10d823f78 - rustc_middle[ef4ebef1f35b9a45]::util::bug::opt_span_bug_fmt::<rustc_span[af5dc13a57d4458]::span_encoding::Span>::{closure#0}
  13:        0x10d823fb7 - rustc_middle[ef4ebef1f35b9a45]::ty::context::tls::with_opt::<rustc_middle[ef4ebef1f35b9a45]::util::bug::opt_span_bug_fmt<rustc_span[af5dc13a57d4458]::span_encoding::Span>::{closure#0}, !>::{closure#0}
  14:        0x10d806895 - rustc_middle[ef4ebef1f35b9a45]::ty::context::tls::with_context_opt::<rustc_middle[ef4ebef1f35b9a45]::ty::context::tls::with_opt<rustc_middle[ef4ebef1f35b9a45]::util::bug::opt_span_bug_fmt<rustc_span[af5dc13a57d4458]::span_encoding::Span>::{closure#0}, !>::{closure#0}, !>
  15:        0x110e2de12 - rustc_middle[ef4ebef1f35b9a45]::util::bug::span_bug_fmt::<rustc_span[af5dc13a57d4458]::span_encoding::Span>
  16:        0x10d8912a5 - <rustc_resolve[45692f5fb0b81a0]::Resolver>::finalize_import::{closure#2}
  17:        0x10d88c7e2 - <rustc_resolve[45692f5fb0b81a0]::Resolver>::finalize_import
  18:        0x10d90b9bd - <rustc_resolve[45692f5fb0b81a0]::Resolver>::resolve_crate::{closure#0}
  19:        0x10d90a9de - <rustc_resolve[45692f5fb0b81a0]::Resolver>::resolve_crate
  20:        0x10c9a9e24 - rustc_interface[55f0bb586236ba3f]::passes::resolver_for_lowering_raw
  21:        0x10d718c66 - rustc_query_impl[db7d5818ebb544c0]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[db7d5818ebb544c0]::query_impl::resolver_for_lowering_raw::dynamic_query::{closure#2}::{closure#0}, rustc_middle[ef4ebef1f35b9a45]::query::erase::Erased<[u8; 16usize]>>
  22:        0x10d6dbb3e - <rustc_query_impl[db7d5818ebb544c0]::query_impl::resolver_for_lowering_raw::dynamic_query::{closure#2} as core[31c80208252ed77d]::ops::function::FnOnce<(rustc_middle[ef4ebef1f35b9a45]::ty::context::TyCtxt, ())>>::call_once
  23:        0x10d4f4ae8 - rustc_query_system[9c8bd583e072577f]::query::plumbing::try_execute_query::<rustc_query_impl[db7d5818ebb544c0]::DynamicConfig<rustc_query_system[9c8bd583e072577f]::query::caches::SingleCache<rustc_middle[ef4ebef1f35b9a45]::query::erase::Erased<[u8; 16usize]>>, false, false, false>, rustc_query_impl[db7d5818ebb544c0]::plumbing::QueryCtxt, false>
  24:        0x10d7207bc - rustc_query_impl[db7d5818ebb544c0]::query_impl::resolver_for_lowering_raw::get_query_non_incr::__rust_end_short_backtrace
  25:        0x10c019ebe - <rustc_interface[55f0bb586236ba3f]::queries::QueryResult<&rustc_middle[ef4ebef1f35b9a45]::ty::context::GlobalCtxt>>::enter::<&rustc_data_structures[1d7d5eef2915edc]::steal::Steal<(rustc_middle[ef4ebef1f35b9a45]::ty::ResolverAstLowering, alloc[88fbee91b568d05e]::sync::Arc<rustc_ast[6e61105b9f75d832]::ast::Crate>)>, rustc_driver_impl[1a7a7dac5035a0ee]::run_compiler::{closure#0}::{closure#1}::{closure#3}>
  26:        0x10c07559d - rustc_interface[55f0bb586236ba3f]::interface::run_compiler::<core[31c80208252ed77d]::result::Result<(), rustc_span[af5dc13a57d4458]::ErrorGuaranteed>, rustc_driver_impl[1a7a7dac5035a0ee]::run_compiler::{closure#0}>::{closure#1}
  27:        0x10c0619c1 - std[513de39480af1bab]::sys::backtrace::__rust_begin_short_backtrace::<rustc_interface[55f0bb586236ba3f]::util::run_in_thread_with_globals<rustc_interface[55f0bb586236ba3f]::util::run_in_thread_pool_with_globals<rustc_interface[55f0bb586236ba3f]::interface::run_compiler<core[31c80208252ed77d]::result::Result<(), rustc_span[af5dc13a57d4458]::ErrorGuaranteed>, rustc_driver_impl[1a7a7dac5035a0ee]::run_compiler::{closure#0}>::{closure#1}, core[31c80208252ed77d]::result::Result<(), rustc_span[af5dc13a57d4458]::ErrorGuaranteed>>::{closure#0}, core[31c80208252ed77d]::result::Result<(), rustc_span[af5dc13a57d4458]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[31c80208252ed77d]::result::Result<(), rustc_span[af5dc13a57d4458]::ErrorGuaranteed>>
  28:        0x10c078a06 - <<std[513de39480af1bab]::thread::Builder>::spawn_unchecked_<rustc_interface[55f0bb586236ba3f]::util::run_in_thread_with_globals<rustc_interface[55f0bb586236ba3f]::util::run_in_thread_pool_with_globals<rustc_interface[55f0bb586236ba3f]::interface::run_compiler<core[31c80208252ed77d]::result::Result<(), rustc_span[af5dc13a57d4458]::ErrorGuaranteed>, rustc_driver_impl[1a7a7dac5035a0ee]::run_compiler::{closure#0}>::{closure#1}, core[31c80208252ed77d]::result::Result<(), rustc_span[af5dc13a57d4458]::ErrorGuaranteed>>::{closure#0}, core[31c80208252ed77d]::result::Result<(), rustc_span[af5dc13a57d4458]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[31c80208252ed77d]::result::Result<(), rustc_span[af5dc13a57d4458]::ErrorGuaranteed>>::{closure#1} as core[31c80208252ed77d]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  29:        0x102a16afb - std::sys::pal::unix::thread::Thread::new::thread_start::h38612934f7248e43
  30:     0x7ff801f5318b - __pthread_start

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: please make sure that you have updated to the latest nightly

note: please attach the file at `/Users/rustc-ice-2024-08-08T08_02_16-90700.txt` to your bug report

query stack during panic:
#0 [resolver_for_lowering_raw] getting the resolver for lowering
end of query stack
error: aborting due to 2 previous errors

For more information about this error, try `rustc --explain E0259`.
```

</p>
</details>

### Note
<strong> ICE location: </strong>

https://github.com/rust-lang/rust/blob/60d146580c10036ce89e019422c6bc2fd9729b65/compiler/rustc_resolve/src/imports.rs#L1085-L1101

### PR DESCRIPTION
**Pull request by bvanjoi**
Fixes #128813

For following code:

```rs
extern crate core;

fn f() {
    use ::core;
}

macro_rules! m {
    () => {
        extern crate std as core;
    };
}

m!();

fn main() {}
```

- In the first loop, we define `extern crate core` and `use ::core` will be referred to `core` (yes, it does not consider if there are some macros that are not expanded. Ideally, this should be delayed if there are some unexpanded macros in the root, but I didn't change it like that because it seems like a huge change).
- Then `m` is expanded, which makes `extern_prelude('core')` return `std` rather than `core`, causing the inconsistency.

r? @petrochenkov

### CODE REVIEW

File: compiler/rustc_resolve/src/build_reduced_graph.rs [hunk 1]
```diff
@@ -895,8 +895,12 @@ impl<'a, 'b, 'tcx> BuildReducedGraphVisitor<'a, 'b, 'tcx> {
         self.r.potentially_unused_imports.push(import);
         let imported_binding = self.r.import(binding, import);
         if parent == self.r.graph_root {
-            if let Some(entry) = self.r.extern_prelude.get(&ident.normalize_to_macros_2_0()) {
-                if expansion != LocalExpnId::ROOT && orig_name.is_some() && !entry.is_import() {
+            let ident = ident.normalize_to_macros_2_0();
+            if let Some(entry) = self.r.extern_prelude.get(&ident) {
+                if expansion != LocalExpnId::ROOT
+                    && orig_name.is_some()
+                    && entry.binding.map_or(true, |binding| binding.module().is_some())
```
Comment (bvanjoi) [inline compiler/rustc_resolve/src/build_reduced_graph.rs:902]: So I made this change: if the binding already exists, and it refers to a module, then we consider it an ambiguity error.

File: tests/ui/imports/multiple-extern-core-mod-by-macro.rs [hunk 2]
```diff
@@ -0,0 +1,20 @@
+//@ edition: 2021
+
+// issue#128813
+
+extern crate core;
+
+fn f() {
+    use ::core;
```
Comment (petrochenkov) [inline tests/ui/imports/multiple-extern-core-mod-by-macro.rs:8]: Nit: the import can be moved to `fn main` to further simplify the test.

**Comment by petrochenkov** [comment]
Could you also add a test case for a crate that is not originally in the extern prelude due to command line options or built-ins, like `core`?
```rust
extern crate foo;

macro_rules! second_foo {
    () => {
        extern crate std as foo;
    };
}

second_foo!();

fn main() {
    use ::foo;
}
```
@rustbot author

File: compiler/rustc_resolve/src/build_reduced_graph.rs (hunk 1 above)
Comment (bvanjoi) [reply compiler/rustc_resolve/src/build_reduced_graph.rs:902]: > bindings in extern prelude are always modules by definition

There is a special case: it may also refer to `Res::Err` when the external module does not exist.

> we should probably just skip the extern prelude update

I think this is a good solution as well, and I will give it a try.

**Comment by bvanjoi** [comment]
In the latest patch:
- rename `issue-95992-extern-2.rs` into `empty.rs`
- rename `issue-95992-extern-1.rs` into `issue-95992-extern.rs`
- skip updating the external binding if it exists.

File: compiler/rustc_resolve/src/build_reduced_graph.rs [hunk 3]
```diff
@@ -913,14 +914,21 @@ impl<'a, 'b, 'tcx> BuildReducedGraphVisitor<'a, 'b, 'tcx> {
             let entry = self
                 .r
                 .extern_prelude
-                .entry(ident.normalize_to_macros_2_0())
+                .entry(ident)
                 .or_insert(ExternPreludeEntry { binding: None, introduced_by_item: true });
-            // Binding from `extern crate` item in source code can replace
-            // a binding from `--extern` on command line here.
-            entry.binding = Some(imported_binding);
```
Comment (bvanjoi) [inline compiler/rustc_resolve/src/build_reduced_graph.rs:920]: Reorder `entry.introduced_by_item = true;` to avoid borrow checker.

File: compiler/rustc_resolve/src/build_reduced_graph.rs [hunk 4]
```diff
@@ -913,14 +914,21 @@ impl<'a, 'b, 'tcx> BuildReducedGraphVisitor<'a, 'b, 'tcx> {
...
             if orig_name.is_some() {
                 entry.introduced_by_item = true;
             }
+            // Binding from `extern crate` item in source code can replace
+            // a binding from `--extern` on command line here.
+            if ident.name != kw::Underscore && entry.binding.is_some() {
```
Comment (bvanjoi) [inline compiler/rustc_resolve/src/build_reduced_graph.rs:924]: `ident.name != kw::Underscore` is to ensure the following code works well.

```rs
extern core as _;
extern core as _;
fn main() {}

Comment (petrochenkov) [reply compiler/rustc_resolve/src/build_reduced_graph.rs:924]: It's clear that there should be no `span_delayed_bug` in this case, but we probably shouldn't do `entry.binding = Some(imported_binding)` either because `_` can still (?) result in the "inconsistent resolution" ICE.

Comment (petrochenkov) [inline compiler/rustc_resolve/src/build_reduced_graph.rs:924]:
```suggestion
            if ident.name != kw::Underscore && entry.introduced_by_item {
```
`entry.binding.is_some()` can be true for crates passed with `--extern my_crate` and used with `my_crate::something` in the source. 
We only need to skip overwriting for crates previously introduced by `extern crate` items.

Comment (petrochenkov) [reply compiler/rustc_resolve/src/build_reduced_graph.rs:924]: So, basically, the logic as I see it:
```
if !entry.introduced_by_item {
  entry.binding = Some(imported_binding);
} else if ident != kw::Underscore {
  span_delayed_bug();
}
```

Comment (bvanjoi) [reply compiler/rustc_resolve/src/build_reduced_graph.rs:924]: Nice catch, I had forgotten that use ::_ is also valid code.

Comment (petrochenkov) [reply compiler/rustc_resolve/src/build_reduced_graph.rs]: The binding is never set to `extern crate self as core;` in that case?
Looks like a bug.

Comment (petrochenkov) [reply compiler/rustc_resolve/src/build_reduced_graph.rs]: `entry.binding = Some(imported_binding)` should be done even if `entry.binding.is_some()` if the binding points to an `--extern` option (such bindings are lazily created in `fn extern_prelude_get`) and not to an `extern crate` item.

So, updating my condition:
```
if entry.binding.is_none() || !entry.introduced_by_item {
  entry.binding = Some(imported_binding);
} else if ident != kw::Underscore {
  span_delayed_bug();
}
```

Comment (petrochenkov) [reply compiler/rustc_resolve/src/build_reduced_graph.rs]: Changing the meaning of `introduced_by_item` will break the logic in which it is used.

Maybe check the kind of `entry.binding`?
It must be an import for `extern crate`s and not an import for `--extern`s.

Comment (bvanjoi) [reply compiler/rustc_resolve/src/build_reduced_graph.rs]: > Maybe check the kind of entry.binding?

I think the above case is not related to `entry.binding` because the issue is caused by `!entry.introduced_by_item`.

And the changes to `introduced_by_item` I envisioned are about that:

```rs
let old_introduced_by_item = entry.introduced_by_item;
if orig_name.is_some() || item.name == "core || item.name == "std" {
    entry.introduced_by_item = true;
}
// then
if entry.binding.is_none() || !old_introduced_by_item {
  entry.binding = Some(imported_binding);
} else if ident != kw::Underscore {
  span_delayed_bug();
}
```

Comment (petrochenkov) [reply compiler/rustc_resolve/src/build_reduced_graph.rs]: I'm starting to lose the track.
By checking the import kind I meant
```rust
if entry.binding.is_none() || !entry.binding.is_import() {
  entry.binding = Some(imported_binding);
} else if ident != kw::Underscore {
  span_delayed_bug();
}
```
The we either set a new binding, or overwrite binding from `--extern` or builtin `core`/`std` but not any `extern crate`, which seems to cover all the cases.
(The meaning of `entry.introduced_by_item` stays unchanged.)

Comment (bvanjoi) [reply compiler/rustc_resolve/src/build_reduced_graph.rs]: I think I get what you mean: we can use `!entry.is_import()` as the test condition

Comment (petrochenkov) [reply compiler/rustc_resolve/src/build_reduced_graph.rs]: Ah, great, there's even a method for it.

**Comment by petrochenkov** [comment]
Thanks!
@bors r+
