### PR TITLE
proc_macro: Tweak doc comments and negative literals

### LINKED ISSUE #48889: Macros 2.0: Negative numbers as a single token
@ngg ran into some [weird bugs](https://github.com/alexcrichton/proc-macro2/issues/67#issuecomment-371311421) and made an [awesome reduction](https://github.com/ngg/proc_macro_nightly_bug) which boils down to:

```rust
#[proc_macro]
pub fn buggy_macro(_: TokenStream) -> TokenStream {
    TokenNode::Literal(Literal::i32(-1)).into()
}
```

It turns out that when expanding this rustc will print out:

```
error: int literal is too large
```

Originating from [here](https://github.com/rust-lang/rust/blob/fedce67cd21dc08ece5a484fe1a060346acac98a/src/libsyntax/parse/mod.rs#L648-L664) I think that this is actually a misdiagnosed error in the sense that the parse is failing because the string is `"-1"` which isn't parseable as a `u128`, but the current code assumes that it can only fail due to overflow. Generally this is correct because the parser never feeds minus signs to this function!

So the broader issue here I believe is that `Literal::i32` can't actually exist. Our parser, as-is today, (and tokenizer?) dictates that the source string `-1` is lexed as two tokens, the minus and then the `1`. This means that `Literal::i32` pretending it can only be one token isn't actually right!

Should we remove `Literal::i32` and all other signed functions? If so should we also panic on negative floats? If not, should we refactor the AST to support literal tokens with negative integers?

cc @jseyfried, @dtolnay, @nrc

### PR DESCRIPTION
**Pull request by alexcrichton**
This commit tweaks the tokenization of a doc comment to use `#[doc = "..."]`
like `macro_rules!` does (instead of treating it as a `Literal` token).
Additionally it fixes treatment of negative literals in the compiler, for
exapmle `Literal::i32(-1)`. The current fix is a bit of a hack around the
current compiler implementation, providing a fix at the proc-macro layer rather
than the libsyntax layer.

Closes #48889

### CODE REVIEW

**Comment by alexcrichton** [comment]
r? @eddyb 

cc @dtolnay

File: src/libproc_macro/lib.rs [hunk 1]
```diff
@@ -653,37 +651,46 @@ impl TokenTree {
...
-            Literal(..) | DocComment(..) => TokenNode::Literal(self::Literal(token)),
+            Literal(..) => TokenNode::Literal(self::Literal(token)),
+            DocComment(c) => {
+                let stream = vec![
+                    tt!(TokenNode::Term(Term::intern("doc"))),
+                    tt!(op!('=')),
+                    tt!(TokenNode::Literal(self::Literal(Literal(Lit::Str_(c), None)))),
+                ].into_iter().collect();
+                stack.push(tt!(TokenNode::Group(Delimiter::Bracket, stream)));
+                op!('#')
```
Comment (eddyb) [inline src/libproc_macro/lib.rs]: Oh this is easier than I expected. Can't wait to rebase over it!
