### PR TITLE
NLL: cast causes failure to promote to static 

### LINKED ISSUE #55288: NLL:  cast causes failure to promote to static
spawned off of https://github.com/rust-lang/rust/issues/55223#issuecomment-431889938

This example is causing an error in NLL:

[play](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2015&gist=3a4a5bcd339c3974fd41aa1e42b1bfc2)

```rust
struct Slice(&'static [&'static [u8]]);
static MAP: Slice = Slice(&[
    b"CloseEvent" as &'static [u8],
]);
```

but this one does not cause an error:

[play](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2015&gist=acb604c330bb9aace7cbfc9d29b529d0)

```rust
struct Slice(&'static [&'static [u8]]);
static MAP: Slice = Slice(&[
    b"CloseEvent",
]);
```

### PR DESCRIPTION
**Pull request by davidtwco**
Fixes #55288. See commit messages for more details.

r? @oli-obk 
cc @nikomatsakis 
cc @pnkfelix 
cc @RalfJung

### CODE REVIEW

File: src/librustc/mir/visit.rs [hunk 1]
```diff
@@ -880,125 +945,156 @@ pub enum TyContext {
...
+    AscribeUserTy,
+    /// Validation command.
     Validate,
 }
 
+#[derive(Copy, Clone, Debug, PartialEq, Eq)]
+pub enum PlaceContext<'tcx> {
+    NonMutatingUse(NonMutatingUseContext),
+    MutatingUse(MutatingUseContext),
+    MaybeMutatingUse(MaybeMutatingUseContext<'tcx>),
```
Comment (RalfJung) [inline src/librustc/mir/visit.rs]: This is not nice... now we have a mixture of type-based classification and dynamic classification, not getting the benefits of either of them.

Given this, I don't think it makes any sense to separate the enum into 4.

File: src/librustc/mir/visit.rs [hunk 2]
```diff
@@ -880,125 +945,156 @@ pub enum TyContext {
...
+            PlaceContext::NonMutatingUse(NonMutatingUseContext::Inspect) |
+            PlaceContext::MaybeMutatingUse(MaybeMutatingUseContext::Borrow { .. }) |
+            PlaceContext::MaybeMutatingUse(MaybeMutatingUseContext::Projection(..)) |
+            PlaceContext::NonMutatingUse(NonMutatingUseContext::Copy) |
+            PlaceContext::NonMutatingUse(NonMutatingUseContext::Move) |
+            PlaceContext::NonUse(NonUseContext::StorageLive) |
+            PlaceContext::NonUse(NonUseContext::StorageDead) |
+            PlaceContext::NonUse(NonUseContext::AscribeUserTy) |
+            PlaceContext::NonUse(NonUseContext::Validate) => false,
+        }
```
Comment (RalfJung) [inline src/librustc/mir/visit.rs]: What is this used for? It's a new classification, isn't it?

File: src/librustc/mir/visit.rs [hunk 3]
```diff
@@ -880,125 +945,156 @@ pub enum TyContext {
...
-            PlaceContext::Projection(Mutability::Not) |
-            PlaceContext::Copy | PlaceContext::Move |
-            PlaceContext::StorageLive | PlaceContext::StorageDead |
-            PlaceContext::Validate => false,
+            PlaceContext::MutatingUse(..) |
+            PlaceContext::MaybeMutatingUse(MaybeMutatingUseContext::Borrow {
+                kind: BorrowKind::Mut { .. },
+                ..
+            }) |
+            PlaceContext::MaybeMutatingUse(MaybeMutatingUseContext::Projection(Mutability::Mut)) |
```
Comment (RalfJung) [inline src/librustc/mir/visit.rs]: Now we still have two lists of classifications, if only for the `MaybeMutatingUse`. The entire point was to avoid doing that so that *by construction*, it is impossible for a `PlaceContext` to be both a mutating and non-mutating use. Your approach does not achieve that.

File: src/librustc/mir/visit.rs (hunk 1 above)
Comment (RalfJung) [inline src/librustc/mir/visit.rs]: This is not nice... now we have a mixture of type-based classification and dynamic classification, not getting the benefits of either of them.

Given this, I don't think it makes any sense to separate the enum into 4.

File: src/librustc/mir/visit.rs (hunk 3 above)
Comment (oli-obk) [inline src/librustc/mir/visit.rs]: You forgot `=> true` here ;)

**Review by RalfJung — CHANGES_REQUESTED** [review]

File: src/librustc/mir/visit.rs (hunk 1 above)
Comment (oli-obk) [reply src/librustc/mir/visit.rs]: I thought that `PlaceContext` would have 3 variants, where the `MaybeMutatingUse` elements appear both in `NonMutatingUseContext` and `MutatingUseContext`

Is there anything speaking against that?

File: src/librustc_codegen_llvm/mir/analyze.rs [hunk 4]
```diff
@@ -200,16 +216,17 @@ impl Visitor<'tcx> for LocalAnalyzer<'mir, 'a, 'll, 'tcx> {
...
                 self.assign(local, location);
             }
 
-            PlaceContext::StorageLive |
-            PlaceContext::StorageDead |
-            PlaceContext::Validate => {}
+            PlaceContext::NonUse(NonUseContext::StorageLive) |
+            PlaceContext::NonUse(NonUseContext::StorageDead) |
+            PlaceContext::NonUse(NonUseContext::AscribeUserTy) |
+            PlaceContext::NonUse(NonUseContext::Validate) => {}
```
Comment (oli-obk) [inline src/librustc_codegen_llvm/mir/analyze.rs]: could be `NonUse(_) => {}`

File: src/librustc_mir/transform/const_prop.rs [hunk 5]
```diff
@@ -529,17 +532,19 @@ impl<'tcx> Visitor<'tcx> for CanConstProp {
...
-            StorageDead | StorageLive |
-            Validate |
-            Projection(_) |
-            Inspect => {},
+            NonMutatingUse(NonMutatingUseContext::Copy) |
+            NonMutatingUse(NonMutatingUseContext::Move) |
+            NonMutatingUse(NonMutatingUseContext::Inspect) |
+            NonUse(NonUseContext::StorageDead) |
+            NonUse(NonUseContext::StorageLive) |
+            NonUse(NonUseContext::Validate) |
```
Comment (oli-obk) [inline src/librustc_mir/transform/const_prop.rs]: Don't we need `AscribeUserTy` here, too?

File: src/librustc_mir/transform/simplify.rs [hunk 6]
```diff
@@ -331,8 +331,9 @@ struct DeclMarker {
 
 impl<'tcx> Visitor<'tcx> for DeclMarker {
     fn visit_local(&mut self, local: &Local, ctx: PlaceContext<'tcx>, _: Location) {
-        // ignore these altogether, they get removed along with their otherwise unused decls.
-        if ctx != PlaceContext::StorageLive && ctx != PlaceContext::StorageDead {
+        // ignore storage markers altogether, they get removed along with their otherwise unused
+        // decls.
+        if !ctx.is_storage_marker() {
```
Comment (oli-obk) [inline src/librustc_mir/transform/simplify.rs]: leave a FIXME that we'll want to extend this to all non-uses

**Review by oli-obk — CHANGES_REQUESTED** [review]

File: src/librustc/mir/visit.rs (hunk 2 above)
Comment (davidtwco) [reply src/librustc/mir/visit.rs]: I moved this function from another pass that I stumbled upon while making changes, it was used in a handful of places and was being imported from that pass.

File: src/librustc/mir/visit.rs (hunk 3 above)
Comment (davidtwco) [reply src/librustc/mir/visit.rs]: Going to resolve this and respond in the other review comment.

File: src/librustc/mir/visit.rs (hunk 1 above)
Comment (davidtwco) [reply src/librustc/mir/visit.rs]: I've modified this to remove the fourth variant. It's still not ideal, because there are now three borrow variants, but I think it is cleaner than with four variants.

File: src/librustc/mir/visit.rs (hunk 3 above)
Comment (davidtwco) [reply src/librustc/mir/visit.rs]: Fixed.

File: src/librustc_codegen_llvm/mir/analyze.rs (hunk 4 above)
Comment (davidtwco) [reply src/librustc_codegen_llvm/mir/analyze.rs]: Fixed.

File: src/librustc_mir/transform/const_prop.rs (hunk 5 above)
Comment (davidtwco) [reply src/librustc_mir/transform/const_prop.rs]: Fixed.

File: src/librustc_mir/transform/simplify.rs (hunk 6 above)
Comment (davidtwco) [reply src/librustc_mir/transform/simplify.rs]: Fixed.

**Review by oli-obk — APPROVED** [review]

**Comment by nikomatsakis** [comment]
@bors p=1

This is an RC2 "nice to have"

**Comment by pnkfelix** [comment]
@bors p=1

As mentioned above, this is nice to have for RC2, so we are trying to win the race to get it in before beta cutoff
