### PR TITLE
Inform the solver if evaluation is concurrent

### LINKED ISSUE #129112: ICE `assertion failed: prev.is_none()` with nightly `13a52890d 2024-08-14`
Compile with latest Nightly got ICE like below:
```
thread 'rustc' panicked at /rustc/13a52890dde8cfeb95069d77c223ac37c0cf3a46/compiler/rustc_type_ir/src/search_graph/global_cache.rs:62:13:
assertion failed: prev.is_none()

query stack during panic:
#0 [check_well_formed] checking that `pat_arg::Arg` is well-formed
#1 [check_mod_type_wf] checking that types are well-formed in module `pat_arg`
end of query stack
```
when compiling in `#[test]`code
```
thread 'rustc' panicked at /rustc/13a52890dde8cfeb95069d77c223ac37c0cf3a46/compiler/rustc_codegen_ssa/src/back/write.rs:2055:17:
/rustc/13a52890dde8cfeb95069d77c223ac37c0cf3a46/compiler/rustc_codegen_ssa/src/back/write.rs:2055:17: panic during codegen/LLVM phase

thread 'coordinator' panicked at /rustc/13a52890dde8cfeb95069d77c223ac37c0cf3a46/compiler/rustc_codegen_ssa/src/back/write.rs:1643:37:
assertion failed: needs_link.is_empty()
```
OS: x86_64-apple-darwin

### LINKED ISSUE #130088: `-Zthreads=8` starts panicking a lot more frequently since today's nightly
Pretty much what the title says, I've narrowed it down to `-Zthreads=8` and today's nightly with the following:

```
$ rustup toolchain list
nightly-2024-09-05-x86_64-unknown-linux-gnu
nightly-2024-09-06-x86_64-unknown-linux-gnu
nightly-x86_64-unknown-linux-gnu (default)
$ rustc +nightly-2024-09-05 -V
rustc 1.83.0-nightly (4ac7bcbaa 2024-09-04)
$ rustc +nightly-2024-09-06 -V
rustc 1.83.0-nightly (9c01301c5 2024-09-05)
$ rustc -V
rustc 1.83.0-nightly (26b5599e4 2024-09-06)
$ for i in $(seq 1 64); do cargo +nightly-2024-09-05 build -q; cargo clean -q; done
$ echo $?
0
$ for i in $(seq 1 64); do cargo +nightly-2024-09-06 build -q; cargo clean -q; done
$ echo $?
0
$ for i in $(seq 1 64); do env RUSTFLAGS="-Zthreads=1" cargo build -q; cargo clean; done
$ echo $?
0
$ for i in $(seq 1 64); do cargo build -q; cargo clean -q; done
<almost immediately ICEs>
```

I've attached some `rustc` backtraces.
[rustc-ice-2024-09-07T19_02_57-44339.txt](https://github.com/user-attachments/files/16919729/rustc-ice-2024-09-07T19_02_57-44339.txt)
[rustc-ice-2024-09-07T19_40_47-164056.txt](https://github.com/user-attachments/files/16919730/rustc-ice-2024-09-07T19_40_47-164056.txt)
[rustc-ice-2024-09-07T19_40_45-162317.txt](https://github.com/user-attachments/files/16919731/rustc-ice-2024-09-07T19_40_45-162317.txt)
[rustc-ice-2024-09-07T19_40_44-161289.txt](https://github.com/user-attachments/files/16919732/rustc-ice-2024-09-07T19_40_44-161289.txt)

### LINKED ISSUE #130089: Nightly ICE with `linux-raw-sys` when using `-Zthreads=0`
### Code
```sh
cargo new <something>
cd <something>
cargo add linux-raw-sys
```
After adding `-Zthreads=0` to `.cargo/config.toml`, I get the ICE.

The resulting `.cargo/config.toml`:
```toml
[target.x86_64-unknown-linux-gnu]
rustflags = [ "-Zthreads=0"]
```

The full project: https://github.com/nuudlman/rustc-nightly-ice

### Meta

`rustc --version --verbose`:
```
rustc 1.83.0-nightly (26b5599e4 2024-09-06)
binary: rustc
commit-hash: 26b5599e4d6ed2b45152c60493c1788c0a27533d
commit-date: 2024-09-06
host: x86_64-unknown-linux-gnu
release: 1.83.0-nightly
LLVM version: 19.1.0
```

### Error output

```
 cargo b
   Compiling linux-raw-sys v0.6.5
thread 'rustc' panicked at /rustc/26b5599e4d6ed2b45152c60493c1788c0a27533d/compiler/rustc_type_ir/src/search_graph/global_cache.rs:62:13:
assertion failed: prev.is_none()
stack backtrace:
   0:     0x79aa89686d1a - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::h589e65cc8b61d31e
   1:     0x79aa89e038d7 - core::fmt::write::h85feaca529ba6ce1
   2:     0x79aa8b0b2ad1 - std::io::Write::write_fmt::hb87087d89092487e
   3:     0x79aa89686b72 - std::sys::backtrace::BacktraceLock::print::h4189ea7435230bb3
   4:     0x79aa89689091 - std::panicking::default_hook::{{closure}}::h88178407ef4f6ab9
   5:     0x79aa89688ec4 - std::panicking::default_hook::h3ccc334e12568011
   6:     0x79aa887a08ff - std[dbf153a3c4c7da75]::panicking::update_hook::<alloc[9dc6147f1f16c854]::boxed::Box<rustc_driver_impl[82dbab975e01e6e2]::install_ice_hook::{closure#0}>>::{closure#0}
   7:     0x79aa896897b8 - std::panicking::rust_panic_with_hook::h2fbc7848bd138bf1
   8:     0x79aa89689553 - std::panicking::begin_panic_handler::{{closure}}::hc439499884a4b219
   9:     0x79aa896871c9 - std::sys::backtrace::__rust_end_short_backtrace::hcc71b0742078f0c0
  10:     0x79aa89689254 - rust_begin_unwind
  11:     0x79aa8633d843 - core::panicking::panic_fmt::hbf678bbc126bd0af
  12:     0x79aa86687ddc - core::panicking::panic::he668b3d4a4f82e0d
  13:     0x79aa8aaae6ce - <rustc_type_ir[602c0c6c632b65bd]::search_graph::SearchGraph<rustc_next_trait_solver[4ce4681625c4863d]::solve::search_graph::SearchGraphDelegate<rustc_trait_selection[2f3767758f81a9b1]::solve::delegate::SolverDelegate>, rustc_middle[372178d4cf000e51]::ty::context::TyCtxt>>::insert_global_cache::{closure#0}
  14:     0x79aa8aaaf537 - <rustc_type_ir[602c0c6c632b65bd]::search_graph::SearchGraph<rustc_next_trait_solver[4ce4681625c4863d]::solve::search_graph::SearchGraphDelegate<rustc_trait_selection[2f3767758f81a9b1]::solve::delegate::SolverDelegate>, rustc_middle[372178d4cf000e51]::ty::context::TyCtxt>>::with_new_goal::<<rustc_next_trait_solver[4ce4681625c4863d]::solve::eval_ctxt::EvalCtxt<rustc_trait_selection[2f3767758f81a9b1]::solve::delegate::SolverDelegate, rustc_middle[372178d4cf000e51]::ty::context::TyCtxt>>::evaluate_canonical_goal::{closure#0}::{closure#0}::{closure#0}>
  15:     0x79aa8aab551a - <rustc_next_trait_solver[4ce4681625c4863d]::solve::eval_ctxt::EvalCtxt<rustc_trait_selection[2f3767758f81a9b1]::solve::delegate::SolverDelegate, rustc_middle[372178d4cf000e51]::ty::context::TyCtxt>>::evaluate_goal_raw
  16:     0x79aa8aab3ba5 - <rustc_trait_selection[2f3767758f81a9b1]::solve::fulfill::FulfillmentCtxt<rustc_trait_selection[2f3767758f81a9b1]::traits::FulfillmentError> as rustc_infer[40680c918449f221]::traits::engine::TraitEngine<rustc_trait_selection[2f3767758f81a9b1]::traits::FulfillmentError>>::select_where_possible
  17:     0x79aa8aab36f9 - <rustc_trait_selection[2f3767758f81a9b1]::solve::fulfill::FulfillmentCtxt<rustc_trait_selection[2f3767758f81a9b1]::traits::FulfillmentError> as rustc_infer[40680c918449f221]::traits::engine::TraitEngine<rustc_trait_selection[2f3767758f81a9b1]::traits::FulfillmentError>>::select_all_or_error
  18:     0x79aa8a6ae92d - rustc_trait_selection[2f3767758f81a9b1]::traits::coherence::overlap
  19:     0x79aa87072608 - <rustc_middle[372178d4cf000e51]::traits::specialization_graph::Children as rustc_trait_selection[2f3767758f81a9b1]::traits::specialize::specialization_graph::ChildrenExt>::insert
  20:     0x79aa8706fc82 - <rustc_middle[372178d4cf000e51]::traits::specialization_graph::Graph as rustc_trait_selection[2f3767758f81a9b1]::traits::specialize::specialization_graph::GraphExt>::insert
  21:     0x79aa8a117a34 - rustc_trait_selection[2f3767758f81a9b1]::traits::specialize::specialization_graph_provider
  22:     0x79aa8a1173a5 - rustc_query_impl[81d3791697797469]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[81d3791697797469]::query_impl::specialization_graph_of::dynamic_query::{closure#2}::{closure#0}, rustc_middle[372178d4cf000e51]::query::erase::Erased<[u8; 8usize]>>
  23:     0x79aa89e20272 - rustc_query_system[e501ed6d95406675]::query::plumbing::try_execute_query::<rustc_query_impl[81d3791697797469]::DynamicConfig<rustc_query_system[e501ed6d95406675]::query::caches::DefIdCache<rustc_middle[372178d4cf000e51]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[81d3791697797469]::plumbing::QueryCtxt, false>
  24:     0x79aa8a34f336 - rustc_query_impl[81d3791697797469]::query_impl::specialization_graph_of::get_query_non_incr::__rust_end_short_backtrace
  25:     0x79aa8aa74243 - rustc_hir_analysis[3980d319edb0dbc9]::coherence::coherent_trait
  26:     0x79aa8aa73f55 - rustc_query_impl[81d3791697797469]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[81d3791697797469]::query_impl::coherent_trait::dynamic_query::{closure#2}::{closure#0}, rustc_middle[372178d4cf000e51]::query::erase::Erased<[u8; 1usize]>>
  27:     0x79aa8a438b12 - rustc_query_system[e501ed6d95406675]::query::plumbing::try_execute_query::<rustc_query_impl[81d3791697797469]::DynamicConfig<rustc_query_system[e501ed6d95406675]::query::caches::DefIdCache<rustc_middle[372178d4cf000e51]::query::erase::Erased<[u8; 1usize]>>, false, false, false>, rustc_query_impl[81d3791697797469]::plumbing::QueryCtxt, false>
  28:     0x79aa8a4378e3 - rustc_query_impl[81d3791697797469]::query_impl::coherent_trait::get_query_non_incr::__rust_end_short_backtrace
  29:     0x79aa87617595 - rustc_hir_analysis[3980d319edb0dbc9]::check::wfcheck::check_well_formed
  30:     0x79aa8a1cfb27 - rustc_query_impl[81d3791697797469]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[81d3791697797469]::query_impl::check_well_formed::dynamic_query::{closure#2}::{closure#0}, rustc_middle[372178d4cf000e51]::query::erase::Erased<[u8; 1usize]>>
  31:     0x79aa8a1cfdb4 - rustc_query_system[e501ed6d95406675]::query::plumbing::try_execute_query::<rustc_query_impl[81d3791697797469]::DynamicConfig<rustc_query_system[e501ed6d95406675]::query::caches::VecCache<rustc_hir[aef0ef93fa31412]::hir_id::OwnerId, rustc_middle[372178d4cf000e51]::query::erase::Erased<[u8; 1usize]>>, false, false, false>, rustc_query_impl[81d3791697797469]::plumbing::QueryCtxt, false>
  32:     0x79aa8a1cfb06 - rustc_query_impl[81d3791697797469]::query_impl::check_well_formed::get_query_non_incr::__rust_end_short_backtrace
  33:     0x79aa8a1cfa53 - rustc_middle[372178d4cf000e51]::query::plumbing::query_ensure_error_guaranteed::<rustc_query_system[e501ed6d95406675]::query::caches::VecCache<rustc_hir[aef0ef93fa31412]::hir_id::OwnerId, rustc_middle[372178d4cf000e51]::query::erase::Erased<[u8; 1usize]>>, ()>
  34:     0x79aa888a1119 - rayon[417c9448959795c5]::iter::plumbing::bridge_producer_consumer::helper::<rayon[417c9448959795c5]::slice::IterProducer<rustc_hir[aef0ef93fa31412]::hir::ItemId>, rayon[417c9448959795c5]::iter::filter_map::FilterMapConsumer<rayon[417c9448959795c5]::iter::reduce::ReduceConsumer<<core[3eb17ea5b3171a49]::result::Result<(), rustc_span[6380c2f0c7870d7a]::ErrorGuaranteed>>::and<()>, rustc_data_structures[1403dbc241404277]::sync::parallel::enabled::try_par_for_each_in<&[rustc_hir[aef0ef93fa31412]::hir::ItemId], rustc_span[6380c2f0c7870d7a]::ErrorGuaranteed, <rustc_middle[372178d4cf000e51]::hir::ModuleItems>::par_items<rustc_hir_analysis[3980d319edb0dbc9]::check::wfcheck::check_mod_type_wf::{closure#0}>::{closure#0}>::{closure#0}::{closure#1}>, rustc_data_structures[1403dbc241404277]::sync::parallel::enabled::try_par_for_each_in<&[rustc_hir[aef0ef93fa31412]::hir::ItemId], rustc_span[6380c2f0c7870d7a]::ErrorGuaranteed, <rustc_middle[372178d4cf000e51]::hir::ModuleItems>::par_items<rustc_hir_analysis[3980d319edb0dbc9]::check::wfcheck::check_mod_type_wf::{closure#0}>::{closure#0}>::{closure#0}::{closure#0}>>
  35:     0x79aa888c900f - rayon_core[5866a558fa7823cf]::join::join_context::<rayon[417c9448959795c5]::iter::plumbing::bridge_producer_consumer::helper<rayon[417c9448959795c5]::slice::IterProducer<rustc_hir[aef0ef93fa31412]::hir::ItemId>, rayon[417c9448959795c5]::iter::filter_map::FilterMapConsumer<rayon[417c9448959795c5]::iter::reduce::ReduceConsumer<<core[3eb17ea5b3171a49]::result::Result<(), rustc_span[6380c2f0c7870d7a]::ErrorGuaranteed>>::and<()>, rustc_data_structures[1403dbc241404277]::sync::parallel::enabled::try_par_for_each_in<&[rustc_hir[aef0ef93fa31412]::hir::ItemId], rustc_span[6380c2f0c7870d7a]::ErrorGuaranteed, <rustc_middle[372178d4cf000e51]::hir::ModuleItems>::par_items<rustc_hir_analysis[3980d319edb0dbc9]::check::wfcheck::check_mod_type_wf::{closure#0}>::{closure#0}>::{closure#0}::{closure#1}>, rustc_data_structures[1403dbc241404277]::sync::parallel::enabled::try_par_for_each_in<&[rustc_hir[aef0ef93fa31412]::hir::ItemId], rustc_span[6380c2f0c7870d7a]::ErrorGuaranteed, <rustc_middle[372178d4cf000e51]::hir::ModuleItems>::par_items<rustc_hir_analysis[3980d319edb0dbc9]::check::wfcheck::check_mod_type_wf::{closure#0}>::{closure#0}>::{closure#0}::{closure#0}>>::{closure#0}, rayon[417c9448959795c5]::iter::plumbing::bridge_producer_consumer::helper<rayon[417c9448959795c5]::slice::IterProducer<rustc_hir[aef0ef93fa31412]::hir::ItemId>, rayon[417c9448959795c5]::iter::filter_map::FilterMapConsumer<rayon[417c9448959795c5]::iter::reduce::ReduceConsumer<<core[3eb17ea5b3171a49]::result::Result<(), rustc_span[6380c2f0c7870d7a]::ErrorGuaranteed>>::and<()>, rustc_data_structures[1403dbc241404277]::sync::parallel::enabled::try_par_for_each_in<&[rustc_hir[aef0ef93fa31412]::hir::ItemId], rustc_span[6380c2f0c7870d7a]::ErrorGuaranteed, <rustc_middle[372178d4cf000e51]::hir::ModuleItems>::par_items<rustc_hir_analysis[3980d319edb0dbc9]::check::wfcheck::check_mod_type_wf::{closure#0}>::{closure#0}>::{closure#0}::{closure#1}>, rustc_data_structures[1403dbc241404277]::sync::parallel::enabled::try_par_for_each_in<&[rustc_hir[aef0ef93fa31412]::hir::ItemId], rustc_span[6380c2f0c7870d7a]::ErrorGuaranteed, <rustc_middle[372178d4cf000e51]::hir::ModuleItems>::par_items<rustc_hir_analysis[3980d319edb0dbc9]::check::wfcheck::check_mod_type_wf::{closure#0}>::{closure#0}>::{closure#0}::{closure#0}>>::{closure#1}, core[3eb17ea5b3171a49]::result::Result<(), rustc_span[6380c2f0c7870d7a]::ErrorGuaranteed>, core[3eb17ea5b3171a49]::result::Result<(), rustc_span[6380c2f0c7870d7a]::ErrorGuaranteed>>::{closure#0}
  36:     0x79aa888a132c - rayon[417c9448959795c5]::iter::plumbing::bridge_producer_consumer::helper::<rayon[417c9448959795c5]::slice::IterProducer<rustc_hir[aef0ef93fa31412]::hir::ItemId>, rayon[417c9448959795c5]::iter::filter_map::FilterMapConsumer<rayon[417c9448959795c5]::iter::reduce::ReduceConsumer<<core[3eb17ea5b3171a49]::result::Result<(), rustc_span[6380c2f0c7870d7a]::ErrorGuaranteed>>::and<()>, rustc_data_structures[1403dbc241404277]::sync::parallel::enabled::try_par_for_each_in<&[rustc_hir[aef0ef93fa31412]::hir::ItemId], rustc_span[6380c2f0c7870d7a]::ErrorGuaranteed, <rustc_middle[372178d4cf000e51]::hir::ModuleItems>::par_items<rustc_hir_analysis[3980d319edb0dbc9]::check::wfcheck::check_mod_type_wf::{closure#0}>::{closure#0}>::{closure#0}::{closure#1}>, rustc_data_structures[1403dbc241404277]::sync::parallel::enabled::try_par_for_each_in<&[rustc_hir[aef0ef93fa31412]::hir::ItemId], rustc_span[6380c2f0c7870d7a]::ErrorGuaranteed, <rustc_middle[372178d4cf000e51]::hir::ModuleItems>::par_items<rustc_hir_analysis[3980d319edb0dbc9]::check::wfcheck::check_mod_type_wf::{closure#0}>::{closure#0}>::{closure#0}::{closure#0}>>
  37:     0x79aa888c900f - rayon_core[5866a558fa7823cf]::join::join_context::<rayon[417c9448959795c5]::iter::plumbing::bridge_producer_consumer::helper<rayon[417c9448959795c5]::slice::IterProducer<rustc_hir[aef0ef93fa31412]::hir::ItemId>, rayon[417c9448959795c5]::iter::filter_map::FilterMapConsumer<rayon[417c9448959795c5]::iter::reduce::ReduceConsumer<<core[3eb17ea5b3171a49]::result::Result<(), rustc_span[6380c2f0c7870d7a]::ErrorGuaranteed>>::and<()>, rustc_data_structures[1403dbc241404277]::sync::parallel::enabled::try_par_for_each_in<&[rustc_hir[aef0ef93fa31412]::hir::ItemId], rustc_span[6380c2f0c7870d7a]::ErrorGuaranteed, <rustc_middle[372178d4cf000e51]::hir::ModuleItems>::par_items<rustc_hir_analysis[3980d319edb0dbc9]::check::wfcheck::check_mod_type_wf::{closure#0}>::{closure#0}>::{closure#0}::{closure#1}>, rustc_data_structures[1403dbc241404277]::sync::parallel::enabled::try_par_for_each_in<&[rustc_hir[aef0ef93fa31412]::hir::ItemId], rustc_span[6380c2f0c7870d7a]::ErrorGuaranteed, <rustc_middle[372178d4cf000e51]::hir::ModuleItems>::par_items<rustc_hir_analysis[3980d319edb0dbc9]::check::wfcheck::check_mod_type_wf::{closure#0}>::{closure#0}>::{closure#0}::{closure#0}>>::{closure#0}, rayon[417c9448959795c5]::iter::plumbing::bridge_producer_consumer::helper<rayon[417c9448959795c5]::slice::IterProducer<rustc_hir[aef0ef93fa31412]::hir::ItemId>, rayon[417c9448959795c5]::iter::filter_map::FilterMapConsumer<rayon[417c9448959795c5]::iter::reduce::ReduceConsumer<<core[3eb17ea5b3171a49]::result::Result<(), rustc_span[6380c2f0c7870d7a]::ErrorGuaranteed>>::and<()>, rustc_data_structures[1403dbc241404277]::sync::parallel::enabled::try_par_for_each_in<&[rustc_hir[aef0ef93fa31412]::hir::ItemId], rustc_span[6380c2f0c7870d7a]::ErrorGuaranteed, <rustc_middle[372178d4cf000e51]::hir::ModuleItems>::par_items<rustc_hir_analysis[3980d319edb0dbc9]::check::wfcheck::check_mod_type_wf::{closure#0}>::{closure#0}>::{closure#0}::{closure#1}>, rustc_data_structures[1403dbc241404277]::sync::parallel::enabled::try_par_for_each_in<&[rustc_hir[aef0ef93fa31412]::hir::ItemId], rustc_span[6380c2f0c7870d7a]::ErrorGuaranteed, <rustc_middle[372178d4cf000e51]::hir::ModuleItems>::par_items<rustc_hir_analysis[3980d319edb0dbc9]::check::wfcheck::check_mod_type_wf::{closure#0}>::{closure#0}>::{closure#0}::{closure#0}>>::{closure#1}, core[3eb17ea5b3171a49]::result::Result<(), rustc_span[6380c2f0c7870d7a]::ErrorGuaranteed>, core[3eb17ea5b3171a49]::result::Result<(), rustc_span[6380c2f0c7870d7a]::ErrorGuaranteed>>::{closure#0}
  38:     0x79aa888a132c - rayon[417c9448959795c5]::iter::plumbing::bridge_producer_consumer::helper::<rayon[417c9448959795c5]::slice::IterProducer<rustc_hir[aef0ef93fa31412]::hir::ItemId>, rayon[417c9448959795c5]::iter::filter_map::FilterMapConsumer<rayon[417c9448959795c5]::iter::reduce::ReduceConsumer<<core[3eb17ea5b3171a49]::result::Result<(), rustc_span[6380c2f0c7870d7a]::ErrorGuaranteed>>::and<()>, rustc_data_structures[1403dbc241404277]::sync::parallel::enabled::try_par_for_each_in<&[rustc_hir[aef0ef93fa31412]::hir::ItemId], rustc_span[6380c2f0c7870d7a]::ErrorGuaranteed, <rustc_middle[372178d4cf000e51]::hir::ModuleItems>::par_items<rustc_hir_analysis[3980d319edb0dbc9]::check::wfcheck::check_mod_type_wf::{closure#0}>::{closure#0}>::{closure#0}::{closure#1}>, rustc_data_structures[1403dbc241404277]::sync::parallel::enabled::try_par_for_each_in<&[rustc_hir[aef0ef93fa31412]::hir::ItemId], rustc_span[6380c2f0c7870d7a]::ErrorGuaranteed, <rustc_middle[372178d4cf000e51]::hir::ModuleItems>::par_items<rustc_hir_analysis[3980d319edb0dbc9]::check::wfcheck::check_mod_type_wf::{closure#0}>::{closure#0}>::{closure#0}::{closure#0}>>
  39:     0x79aa888fde02 - <rayon_core[5866a558fa7823cf]::job::StackJob<rayon_core[5866a558fa7823cf]::latch::SpinLatch, rayon_core[5866a558fa7823cf]::join::join_context::call_b<core[3eb17ea5b3171a49]::result::Result<(), rustc_span[6380c2f0c7870d7a]::ErrorGuaranteed>, rayon[417c9448959795c5]::iter::plumbing::bridge_producer_consumer::helper<rayon[417c9448959795c5]::slice::IterProducer<rustc_hir[aef0ef93fa31412]::hir::ItemId>, rayon[417c9448959795c5]::iter::filter_map::FilterMapConsumer<rayon[417c9448959795c5]::iter::reduce::ReduceConsumer<<core[3eb17ea5b3171a49]::result::Result<(), rustc_span[6380c2f0c7870d7a]::ErrorGuaranteed>>::and<()>, rustc_data_structures[1403dbc241404277]::sync::parallel::enabled::try_par_for_each_in<&[rustc_hir[aef0ef93fa31412]::hir::ItemId], rustc_span[6380c2f0c7870d7a]::ErrorGuaranteed, <rustc_middle[372178d4cf000e51]::hir::ModuleItems>::par_items<rustc_hir_analysis[3980d319edb0dbc9]::check::wfcheck::check_mod_type_wf::{closure#0}>::{closure#0}>::{closure#0}::{closure#1}>, rustc_data_structures[1403dbc241404277]::sync::parallel::enabled::try_par_for_each_in<&[rustc_hir[aef0ef93fa31412]::hir::ItemId], rustc_span[6380c2f0c7870d7a]::ErrorGuaranteed, <rustc_middle[372178d4cf000e51]::hir::ModuleItems>::par_items<rustc_hir_analysis[3980d319edb0dbc9]::check::wfcheck::check_mod_type_wf::{closure#0}>::{closure#0}>::{closure#0}::{closure#0}>>::{closure#1}>::{closure#0}, core[3eb17ea5b3171a49]::result::Result<(), rustc_span[6380c2f0c7870d7a]::ErrorGuaranteed>> as rayon_core[5866a558fa7823cf]::job::Job>::execute
  40:     0x79aa882be20e - <rayon_core[5866a558fa7823cf]::registry::WorkerThread>::wait_until_cold
  41:     0x79aa882bbd99 - <rayon_core[5866a558fa7823cf]::registry::ThreadBuilder>::run
  42:     0x79aa887a2c27 - <<crossbeam_utils[2a79a005c364b520]::thread::ScopedThreadBuilder>::spawn<<rayon_core[5866a558fa7823cf]::ThreadPoolBuilder>::build_scoped<rustc_interface[9e43cd91206122fc]::util::run_in_thread_pool_with_globals<rustc_interface[9e43cd91206122fc]::interface::run_compiler<core[3eb17ea5b3171a49]::result::Result<(), rustc_span[6380c2f0c7870d7a]::ErrorGuaranteed>, rustc_driver_impl[82dbab975e01e6e2]::run_compiler::{closure#0}>::{closure#1}, core[3eb17ea5b3171a49]::result::Result<(), rustc_span[6380c2f0c7870d7a]::ErrorGuaranteed>>::{closure#3}::{closure#0}::{closure#0}, rustc_interface[9e43cd91206122fc]::util::run_in_thread_pool_with_globals<rustc_interface[9e43cd91206122fc]::interface::run_compiler<core[3eb17ea5b3171a49]::result::Result<(), rustc_span[6380c2f0c7870d7a]::ErrorGuaranteed>, rustc_driver_impl[82dbab975e01e6e2]::run_compiler::{closure#0}>::{closure#1}, core[3eb17ea5b3171a49]::result::Result<(), rustc_span[6380c2f0c7870d7a]::ErrorGuaranteed>>::{closure#3}::{closure#0}::{closure#1}, core[3eb17ea5b3171a49]::result::Result<(), rustc_span[6380c2f0c7870d7a]::ErrorGuaranteed>>::{closure#0}::{closure#0}::{closure#0}, ()>::{closure#0} as core[3eb17ea5b3171a49]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  43:     0x79aa887976ee - std[dbf153a3c4c7da75]::sys::backtrace::__rust_begin_short_backtrace::<alloc[9dc6147f1f16c854]::boxed::Box<dyn core[3eb17ea5b3171a49]::ops::function::FnOnce<(), Output = ()> + core[3eb17ea5b3171a49]::marker::Send>, ()>
  44:     0x79aa887a28ca - <<std[dbf153a3c4c7da75]::thread::Builder>::spawn_unchecked_<alloc[9dc6147f1f16c854]::boxed::Box<dyn core[3eb17ea5b3171a49]::ops::function::FnOnce<(), Output = ()> + core[3eb17ea5b3171a49]::marker::Send>, ()>::{closure#1} as core[3eb17ea5b3171a49]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  45:     0x79aa8ac892eb - std::sys::pal::unix::thread::Thread::new::thread_start::h2c6608fdb287f01f
  46:     0x79aa8c409386 - <unknown>
  47:     0x79aa8c48ab0c - <unknown>
  48:                0x0 - <unknown>

error: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: please make sure that you have updated to the latest nightly

note: please attach the file at `/home/isaac/.cargo/registry/src/index.crates.io-6f17d22bba15001f/linux-raw-sys-0.6.5/rustc-ice-2024-09-07T19_55_30-171727.txt` to your bug report

note: compiler flags: --crate-type lib -C embed-bitcode=no -C debuginfo=2 -Z threads=0

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [specialization_graph_of] building specialization graph of trait `core::cmp::Eq`
#1 [coherent_trait] coherence checking all impls of trait `core::cmp::Eq`
end of query stack
error: could not compile `linux-raw-sys` (lib)

Caused by:
  process didn't exit successfully: `/home/isaac/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/rustc --crate-name linux_raw_sys --edition=2021 /home/isaac/.cargo/registry/src/index.crates.io-6f17d22bba15001f/linux-raw-sys-0.6.5/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --diagnostic-width=100 --crate-type lib --emit=dep-info,metadata,link -C embed-bitcode=no -C debuginfo=2 --warn=unexpected_cfgs --cfg 'feature="default"' --cfg 'feature="errno"' --cfg 'feature="general"' --cfg 'feature="std"' --check-cfg 'cfg(docsrs)' --check-cfg 'cfg(feature, values("bootparam", "compiler_builtins", "core", "default", "elf", "errno", "general", "if_arp", "if_ether", "if_packet", "io_uring", "ioctl", "loop_device", "mempolicy", "net", "netlink", "no_std", "prctl", "rustc-dep-of-std", "std", "system", "xdp"))' --check-cfg 'cfg(target_arch, values("xtensa"))' -C metadata=d92bffb7b181fb71 -C extra-filename=-d92bffb7b181fb71 --out-dir /home/isaac/Work/rust_nightly_ice_repro/target/debug/deps -L dependency=/home/isaac/Work/rust_nightly_ice_repro/target/debug/deps --cap-lints allow -Zthreads=0` (exit status: 101)
```
[rustc-ice-2024-09-07T19_55_30-171727.txt](https://github.com/user-attachments/files/16919787/rustc-ice-2024-09-07T19_55_30-171727.txt)

[rustc-ice-2024-09-07T19_55_30-171727.txt](https://github.com/user-attachments/files/16919787/rustc-ice-2024-09-07T19_55_30-171727.txt)

### PR DESCRIPTION
**Pull request by workingjubilee**
Parallel compilation of a program can cause unexpected event sequencing. Inform the solver when this is true so it can skip invalid asserts.

Recommended by @lcnr in https://github.com/rust-lang/rust/issues/129112#issuecomment-2293456010
Fixes https://github.com/rust-lang/rust/issues/130089
Fixes https://github.com/rust-lang/rust/issues/130088
Fixes https://github.com/rust-lang/rust/issues/129112

r? compiler-errors

### CODE REVIEW

**Review by compiler-errors — COMMENTED** [review]
I am not certain this is sound; I think the new solver legitimately cannot handle parallel computation yet, but idk lol

r? lcnr

File: tests/ui/traits/next-solver/global-cache-and-parallel-frontend.rs [hunk 1]
```diff
@@ -0,0 +1,15 @@
+//@ compile-flags: -Zthreads=16
```
Comment (matthiaskrgr) [inline tests/ui/traits/next-solver/global-cache-and-parallel-frontend.rs:1]: as this only would only fail "sometimes" , this test will be pretty useless im afraid :(

If this one day regresses, it may be a problem only once in a blue moon and then make it seem like other unrelated pr caused the failure.
https://github.com/rust-lang/rust/pull/129799#issuecomment-2322746190 for similar problem.

Comment (workingjubilee) [reply tests/ui/traits/next-solver/global-cache-and-parallel-frontend.rs:1]: You mean like x86_64-msvc-ext?

Comment (workingjubilee) [reply tests/ui/traits/next-solver/global-cache-and-parallel-frontend.rs:1]: In any case, we have already landed tests for the parallel frontend, so it doesn't seem to matter much, really. We can handle thread tests being inconsistent by modifying compiletest if we want.

Comment (matthiaskrgr) [reply tests/ui/traits/next-solver/global-cache-and-parallel-frontend.rs:1]: >You mean like x86_64-msvc-ext?

No, if you reproduce the ICE locally, you will notice that rustc crashes only sometimes and sometimes it doesn't, with -Zthreads=16.. 
You would have to run the test 30-100 times to be somewhat confident that there really is no crash related to parallel frontend.

Comment (workingjubilee) [reply tests/ui/traits/next-solver/global-cache-and-parallel-frontend.rs:1]: I ran `./x.py test --force-rerun` yes.

This doesn't seem to be a problem, given that our test suite will result in running it about 30 times.

File: compiler/rustc_type_ir/src/search_graph/global_cache.rs [hunk 2]
```diff
@@ -50,16 +50,21 @@ impl<X: Cx> GlobalCache<X> {
...
+        concurrency_is_real: bool,
     ) {
         let result = cx.mk_tracked(result, dep_node);
         let entry = self.map.entry(input).or_default();
         if encountered_overflow {
             let with_overflow = WithOverflow { nested_goals, result };
             let prev = entry.with_overflow.insert(additional_depth, with_overflow);
-            assert!(prev.is_none());
+            if !concurrency_is_real {
+                assert!(prev.is_none());
```
Comment (lcnr) [inline compiler/rustc_type_ir/src/search_graph/global_cache.rs:61]: given that `evaluation_is_concurrent` is a method on the `cx`, call it inside of htis function instead of passing it in.

Also, please check that `cx.get_tracked(prev.result) == result`

Comment (workingjubilee) [reply compiler/rustc_type_ir/src/search_graph/global_cache.rs:61]: ...I somehow missed that cx is an arg here too.

**Comment by lcnr** [comment]
> I am not certain this is sound; I think the new solver legitimately cannot handle parallel computation yet, but idk lol

I am fairly confident that overwriting previous cache entries during parallel compilation should not cause issues. We can assert that the results match which should catch any bugs?

File: compiler/rustc_type_ir/src/search_graph/global_cache.rs (hunk 2 above)
Comment (workingjubilee) [reply compiler/rustc_type_ir/src/search_graph/global_cache.rs:61]: Are we asserting `cx.get_tracked(prev.result) == result` unconditionally or only when non-concurrent or?

**Comment by workingjubilee** [comment]
It's a nightly feature colliding with a nightly feature, it's not the worst if it explodes.

File: compiler/rustc_type_ir/src/search_graph/global_cache.rs (hunk 2 above)
Comment (lcnr) [reply compiler/rustc_type_ir/src/search_graph/global_cache.rs:60]: well, always if `prev` is `Some` :grin:

File: compiler/rustc_type_ir/src/search_graph/global_cache.rs [hunk 3]
```diff
@@ -53,14 +53,21 @@ impl<X: Cx> GlobalCache<X> {
     ) {
         let result = cx.mk_tracked(result, dep_node);
         let entry = self.map.entry(input).or_default();
+        let result_tracked = cx.get_tracked(&result);
```
Comment (lcnr) [inline compiler/rustc_type_ir/src/search_graph/global_cache.rs:56]: use the original input result :sweat_smile: maybe call it "raw_result" or whatever

File: compiler/rustc_type_ir/src/search_graph/global_cache.rs [hunk 4]
```diff
@@ -53,14 +53,21 @@ impl<X: Cx> GlobalCache<X> {
...
         if encountered_overflow {
             let with_overflow = WithOverflow { nested_goals, result };
             let prev = entry.with_overflow.insert(additional_depth, with_overflow);
+            if let Some(prev) = &prev {
+                assert_eq!(cx.get_tracked(&prev.result), result_tracked);
+            }
             if !cx.evaluation_is_concurrent() {
```
Comment (lcnr) [inline compiler/rustc_type_ir/src/search_graph/global_cache.rs:63]: pls merge: `assert!(cx.evaluation_is_concurrent())`

File: tests/ui/traits/next-solver/global-cache-and-parallel-frontend.rs [hunk 5]
```diff
@@ -0,0 +1,15 @@
...
+
```
Comment (lcnr) [inline tests/ui/traits/next-solver/global-cache-and-parallel-frontend.rs:2]: please add a comment explaining what this tests (and link to the original issue)

**Review by lcnr — COMMENTED** [review]
r=me after fixing the comment

**Comment by workingjubilee** [comment]
LINE NUMBERS
@bors r=lcnr

**Comment by workingjubilee** [comment]
...uh.

**Comment by workingjubilee** [comment]
that doesn't reproduce locally...

**Comment by workingjubilee** [comment]
...huh.

@bors r=lcnr

File: compiler/rustc_type_ir/src/search_graph/global_cache.rs [hunk 6]
```diff
@@ -44,22 +44,28 @@ impl<X: Cx> GlobalCache<X> {
...
-        let result = cx.mk_tracked(result, dep_node);
+        let result = cx.mk_tracked(origin_result, dep_node);
         let entry = self.map.entry(input).or_default();
         if encountered_overflow {
             let with_overflow = WithOverflow { nested_goals, result };
             let prev = entry.with_overflow.insert(additional_depth, with_overflow);
-            assert!(prev.is_none());
+            if let Some(prev) = &prev {
+                assert!(cx.evaluation_is_concurrent());
+                assert_eq!(cx.get_tracked(&prev.result), origin_result);
```
Comment (zetanumbers) [inline compiler/rustc_type_ir/src/search_graph/global_cache.rs:61]: This allows redundant duplicate work and checks. Ideally the second thread should wait for the first thread to calculate the cached result, but there should be at least a FIXME for this.
