### PR TITLE
Use correct ABI for wasm32 by default

### LINKED ISSUE #291: Status of rust+C bindings for wasm targets
Hi,
There are a lot of important dependencies in the rust ecosystem that use ffi to C fia the `cc` crate or similiar.
which tools and targets currently support that?
in the past `asmjs-unknown-emscripten` worked and together with `cargo-web` you could just run `cargo web test` to know if your library compiles+run on wasm/emscripten. 
Sadly emscripten is broken on stable for a while now https://github.com/rust-lang/rust/issues/66916.

wasm32-unknown-unknown works in combination with `clang-8` only(probably a bug), not before and not later(doesn't work on clang-9 and clang-10) https://github.com/alexcrichton/cc-rs/issues/378
so `wasm-pack` can't be used here.

`wasi` seem to have the same problem, running `cargo wasi test` fails to find the sysroot(`fatal error: 'string.h' file not found`) although it seems like you can download sysroots for wasi or compile them yourself https://bytecodealliance.github.io/wasmtime/wasm-c.html

Is there any tool out there that can test rust+C code out of the box? (We had emscripten tests in the CI until it broke and we want to continue testing for wasm target in the CI)

### PR DESCRIPTION
**Pull request by devsnek**
Introduces `wasm32-unknown-bindgen` for those wishing to use the bindgen compat abi. `wasm32-*` now uses the correct abi by default.

Fixes https://github.com/rustwasm/team/issues/291

### CODE REVIEW

**Comment by nagisa** [comment]
Using an environment variable to control compiler output is probably a no-go. It should be either a per-target option (possibly with a bouquet of new targets where the different ABIs make sense – target strings do have a dedicated ABI component just for this!)  or a compiler flag.

**Comment by devsnek** [comment]
@nagisa is there a specific direction you would prefer, and if so, where would I find the code that needs to be changed?

**Comment by nagisa** [comment]
Adding new targets for this non-bindgen compatible ABI would be the most conventional solution. An option in [target spec's options](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_target/spec/struct.TargetOptions.html) could further facilitate that, though such an option is a question of either adding new targets or using a custom target json.

**Comment by devsnek** [comment]
@nagisa it sounds like you are suggesting that bindgen should continue to be the abi for `wasm32` (that isn't emscripten), is that correct? I'd like to change it so that is not the default choice.

**Comment by nagisa** [comment]
> bindgen should continue to be the abi for wasm32 (that isn't emscripten), is that correct?

Not really. I have little idea about what the requirements this particular tooling has. If there's tooling that requires different ABI/behaviour, make a new target and have the tooling in question (or users interacting with this tooling) use this new target.

---

To expand on why environment variables are not a right solution for this:

* Environment variables are not tracked for changes (i.e. changing their value won't cause a rebuild or flush of an incremental cache);
* Environment variable not being supported is a silent failure;
* Probably many more things...

**Comment by devsnek** [comment]
@nagisa I added the new target, is there anything that needs to be updated in terms of tests?

**Comment by alexcrichton** [comment]
Personally I do not want to be the cause of adding a bindgen target to the compiler. As the author of wasm-bindgen I do not ever want to see that happen. If the C/Rust interop problem is bad enough then I would ask that wasm-bindgen is simply broken. I would consider it a failing of wasm-bindgen if it required a bindgen-specific target to get added to rustc, simply because of an ABI issue.

The current thinking has been that we should not do this. "Soon" (not entirely sure when) the default ABI is expected to change with multi-value and that time the Emscripten/Clang ABIs would match what wasm-bindgen expects.

**Comment by devsnek** [comment]
@alexcrichton if "soon" is not in the next 1-3 months I'd request that we do *something* here.

**Comment by alexcrichton** [comment]
I don't know the timelines on the LLVM side, but I suspect it would be longer than 1-3 months. I personally view the addition of a new target as extremely costly and I don't think wasm-bindgen is anywhere near important enough to warrant its own target in the compiler.

I should also say I don't know how to fix wasm-bindgen. I realize adding a new target is easy to do, but I do not believe it is the correct solution to this problem.

**Comment by devsnek** [comment]
@alexcrichton i'm not personally a fan of adding a target either, that was requested by @nagisa. I'm happy to implement whatever can be agreed on, I just need to know what that is :sweat_smile:.

**Comment by alexcrichton** [comment]
I don't mean to say adding a target is a bad recommendation, it's the best solution *if* this must be solved in the compiler. I just do not think it's a worthwhile solution given the problem here.

**Comment by nagisa** [comment]
Alex, assigning you as the reviewer as you have most context as to what is happening in the bindgen land and it seems like you're against making changes in the compiler.

**Comment by alexcrichton** [comment]
We had some [discussion on Discord](https://discord.com/channels/442252698964721669/443151097398296587/788122506362880041) and the conclusion was that @devsnek was going to test out changes to `bindgen` instead of rustc since the C APIs in use are automatically bound by bindgen, and bindgen can bind the API as `arg: &Foo` instead of `arg: Foo` to get the two ABIs to match.

File: compiler/rustc_target/src/abi/call/mod.rs [hunk 1]
```diff
@@ -605,7 +605,7 @@ impl<'a, Ty> FnAbi<'a, Ty> {
             "nvptx64" => nvptx64::compute_abi_info(self),
             "hexagon" => hexagon::compute_abi_info(self),
             "riscv32" | "riscv64" => riscv::compute_abi_info(cx, self),
-            "wasm32" if cx.target_spec().os != "emscripten" => {
+            "wasm32" if cx.target_spec().os == "bindgen" => {
```
Comment (TheBlueMatt) [inline compiler/rustc_target/src/abi/call/mod.rs:608]: Does it still make sense to change this for WASI and leave `unknown` alone in the short term? While wasm_bindgen may change in the future so that unknown can be changed, it would be nice to go ahead and change the ABI for *some* target so that its possible to build C+WASM code that does struct passing by-value even if it cannot be interoperated with wasm_bindgen immediately.

Comment (alexcrichton) [reply compiler/rustc_target/src/abi/call/mod.rs:608]: Yeah that sounds reasonable to me!

**Comment by devsnek** [comment]
@alexcrichton updated to be wasi-only exception.

**Comment by programmerjake** [comment]
This seems worthy of mention in the release notes.
