### PR TITLE
checksum-freshness: Fix invalid checksum calculation for binary files

### LINKED ISSUE #151090: checksum-freshness: does not work with binary embedded files
I tried this code:

```rust
// random_bytes have to be binary. include_bytes!(".gitignore") does not work, for instance.
pub static CONTENTS: &[u8] = include_bytes!("../random_bytes.bin");
```

I expected to see this happen: subsequent builds of the crate with such static to not trigger a rebuild.

Instead, this happened: crate gets rebuilt over and over

Extra bits:
Cargo's rebuild reason states that file length does not match up:
> Dirty inner v0.1.0 (/Users/hiro/Projects/build_playground/checksum-freshness/inner): file size changed (0 != 40) for `random_bytes.bin`

This means that rustc reports such files as having a length of 0, whereas on a subsequent build Cargo compares that 0 with correct length, triggering a rebuild in a process.

### Meta

`rustc --version --verbose`:
```
rustc 1.94.0-nightly (2f1bd3f37 2026-01-12)
```

<details><summary>Backtrace</summary>
<p>

```
<backtrace>
```

</p>
</details>

### PR DESCRIPTION
**Pull request by osiewicz**
Admittedly this is not the cleanest way to achieve this, but SourceMap is quite intertwined with source files being represented as Strings.
Tracking issue: https://github.com/rust-lang/cargo/issues/14136
Closes: rust-lang/rust#151090

### CODE REVIEW

File: compiler/rustc_builtin_macros/src/source_util.rs [hunk 1]
```diff
@@ -275,7 +275,13 @@ fn load_binary_file(
         }
     };
     match cx.source_map().load_binary_file(&resolved_path) {
-        Ok(data) => Ok(data),
+        Ok(data) => {
+            if let Some(as_str) = resolved_path.to_str() {
```
Comment (xonx4l) [inline compiler/rustc_builtin_macros/src/source_util.rs]: Would using `to_string_lossy()` or interning the path will be safer to ensure these dependencies are always captured for the checksum? since `to_str()` returns None.

File: compiler/rustc_interface/src/passes.rs [hunk 2]
```diff
@@ -586,7 +587,7 @@ fn write_out_deps(tcx: TyCtxt<'_>, outputs: &OutputFilenames, out_filenames: &[P
     let result: io::Result<()> = try {
         // Build a list of files used to compile the output and
         // write Makefile-compatible dependency rules
-        let mut files: Vec<(String, u64, Option<SourceFileHash>)> = sess
+        let mut files: IndexMap<String, (u64, Option<SourceFileHash>)> = sess
```
Comment (bjorn3) [inline compiler/rustc_interface/src/passes.rs:590]: Maybe make this `IndexMap<String, Option<(u64, Option<SourceFileHash>)>>` where `None` indicates that the length and hash haven't been filled in yet?

Comment (osiewicz) [reply compiler/rustc_interface/src/passes.rs:590]: Does that get us anything? This PR makes it so that files with binary contents are inserted into both `source_map.files()` (with null hash unnormalized_source_len equal to 0) and `file_depinfo`; with the use of `IndexMap`, we can override those coming from `source_map.files()` with hashes coming from `file_depinfo`. Thus, the value in that IndexMap would never be `None`.

Now is that the cleanest way? I'm sure not.. but I honestly don't understand implications of removing these "null" binary entries from the sourcemap well enough to make that cut.

Comment (jdonszelmann) [reply compiler/rustc_interface/src/passes.rs:590]: I think it makes some amount of sense to keep them like this, as null entries? Especially if the has can never really be None as Piotr says. @bjorn3 does Piotr's comment convince you? Or d'ya have a good reason why making it an Option makes sense

**Review by jdonszelmann — APPROVED** [review]
This looks good to me, if @bjorn3 's concern is lifted, r=me

*[View changes since this review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/rust/151137/86a49fd71fecd25b0fd20247db0ba95eeceaba28..1d5c70ec9064fccfb5f07b36b544d6bfb4307063)*

File: compiler/rustc_interface/src/passes.rs (hunk 2 above)
Comment (bjorn3) [reply compiler/rustc_interface/src/passes.rs:590]: You are first inserting into `files` with a dummy value of hash 0 + len 0 and later overwriting it with the real value, right? My suggestion is to first insert `None` and later overwrite it with the real value. This way you can unwrap the entry at use and be guaranteed that you didn't accidentally get a dummy value.

Comment (osiewicz) [reply compiler/rustc_interface/src/passes.rs:590]: I see your point. What's tricky about it is that we have no way of knowing whether the items in `files` are "bugged" or not.
That is to say, in the context of that function, we have no way to tell if an entry with `hash 0 + len 0` originated in a `include_bytes!("my_1024mb_file.bin");` call (bugged one, that this PR tries to address) or `include_str!("empty_file.txt")` (legit one). Both of them have a `hash 0 + len 0`, and it is the correct value for the `include_str` one.

Comment (bjorn3) [reply compiler/rustc_interface/src/passes.rs:590]: You can change line 639 to return `None` instead of `(0, None)`, right? And adapt the return type of `hash_iter_files` accordingly. Or am I missing something?

Comment (osiewicz) [reply compiler/rustc_interface/src/passes.rs:590]: I believe that branch (on line 639) is not relevant at all and that's not where we were getting our fake-nulls (`(hash 0, len 0)`) from.
Before this PR, the file path of a binary file (with non-UTF8 contents) was injected into depfile through `source_map().files()`. For non-utf8 files the values were not correct, since SourceMap only accepts Strings as the contents of a source file. See the following snippet, as that's where we "fake out" contents of a binary file when inserting it into a SourceMap: https://github.com/rust-lang/rust/blob/2850ca8295bc253186b291314ddc239632755475/compiler/rustc_span/src/source_map.rs#L279
Crucially, we did not/do not call `hash_iter_files` on these, as we assume that SourceMap calculated the length and a hash correctly.. Which it did not, in some cases (non-utf8 binary files). This then led to binary files having a hash of empty string and a length of 0.

With this PR, that's still the case - binary files are *still* present in `source_map().files()` result, but they're also injected into `file_depinfo` and that lets us call `hash_iter_files` on them and get the correct hash/file length. The change to `files` type let's us override the "faulty" value with a good one. However, as outlined in https://github.com/rust-lang/rust/pull/151137/files#r2726164490 , there's no straightforward way (IMHO) to use an option here, because if we knew which entries from the SourceMap were "faulty", we could just call `hash_iter_files` on them directly without jumping through the hoops.. And line 639 is not really at fault for what we're struggling with.

File: compiler/rustc_interface/src/passes.rs [hunk 3]
```diff
@@ -718,7 +721,7 @@ fn write_out_deps(tcx: TyCtxt<'_>, outputs: &OutputFilenames, out_filenames: &[P
             // Emit a fake target for each input file to the compilation. This
             // prevents `make` from spitting out an error if a file is later
             // deleted. For more info see #28735
-            for (path, _file_len, _checksum_hash_algo) in &files {
+            for (path, (_file_len, _checksum_hash_algo)) in &files {
```
Comment (osiewicz) [inline compiler/rustc_interface/src/passes.rs]: Nit: we can just leave the tuple as a whole unused.
```suggestion
            for (path, _) in &files {
```

Comment (osiewicz) [reply compiler/rustc_interface/src/passes.rs]: Or even:
```suggestion
            for path in files.keys() {
```

File: compiler/rustc_interface/src/passes.rs (hunk 2 above)
Comment (bjorn3) [reply compiler/rustc_interface/src/passes.rs:590]: I see. In that case I'm fine with leaving the code as is.

File: compiler/rustc_builtin_macros/src/source_util.rs (hunk 1 above)
Comment (osiewicz) [reply compiler/rustc_builtin_macros/src/source_util.rs]: It looks like the only other place that inserts into `file_depinfo` simply assumes that Paths are valid UTF-8: https://github.com/osiewicz/rust/blob/1d5c70ec9064fccfb5f07b36b544d6bfb4307063/library/proc_macro/src/lib.rs#L1628
I'm honestly a bit unsure as to what we can do here (is a lossy conversion fine in this case?).

These dependencies will always be captured regardless; at worst, they'll be captured with len 0 and hash value of an empty string (because we don't end up executing this `if` statement).

I believe `to_string_lossy` is indeed the right call here, as that's what `SourceMap` seems to be doing as well.

**Review by osiewicz — COMMENTED** [review]
I have addressed the outstanding review comments and am happy with the code as is; unless anybody objects, I think this PR is good to go (from my side).

*[View changes since this review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/rust/151137/0462e8f7e51f20692b02d68efee68bb28a6f4457..0df94dd94eeb0893d60aee40c9fcdf4d2b43a569)*
