### PR TITLE
Show five traits implementation in help when there are exactly five

### LINKED ISSUE #39802: Unhelpful message abbrevation for E0277
A minor error message snafu:

```
error[E0277]: the trait bound `std::io::Error: std::convert::From<hyper::Error>` is not satisfied
   (code sample elided for brevity)
    = help: the following implementations were found:
              <std::io::Error as std::convert::From<std::ffi::NulError>>
              <std::io::Error as std::convert::From<std::io::IntoInnerError<W>>>
              <std::io::Error as std::convert::From<std::io::ErrorKind>>
              <std::io::Error as std::convert::From<slog::ser::Error>>
            and 1 others
    = note: required by `std::convert::From::from`
    = note: this error originates in a macro outside of the current crate
```

Notice the `and 1 others` line. It doesn't abbreviate anything; the compiler could've inserted the one missing impl and take the same amount of screen space.

### PR DESCRIPTION
**Pull request by seppo0010**
Fixes #39802

### CODE REVIEW

File: src/test/ui/did_you_mean/issue-39802-show-5-trait-impls.rs [hunk 1]
```diff
@@ -0,0 +1,31 @@
...
+impl Foo<u8> for i8 {}
+impl Foo<u16> for i8 {}
+impl Foo<u32> for i8 {}
+impl Foo<u64> for i8 {}
+impl Foo<bool> for i8 {}
+
+fn main() {
+    Foo::<i32>::bar(&1i8);
+
+    //~^ error: the trait `Foo<i32>` is not implemented for `i8``
```
Comment (gralpli) [inline src/test/ui/did_you_mean/issue-39802-show-5-trait-impls.rs]: Are those two backticks at the end of the line intentional?

All other tests within `ui/did_you_mean/` use a separate .stderr file. I think it's not possible to use this inline error notation here.

File: src/test/ui/did_you_mean/issue-39802-show-5-trait-impls.rs [hunk 2]
```diff
@@ -0,0 +1,31 @@
...
+trait Foo<B> {
+    fn bar(&self){}
+}
+
+impl Foo<u8> for i8 {}
+impl Foo<u16> for i8 {}
+impl Foo<u32> for i8 {}
+impl Foo<u64> for i8 {}
+impl Foo<bool> for i8 {}
+
```
Comment (gralpli) [inline src/test/ui/did_you_mean/issue-39802-show-5-trait-impls.rs]: Maybe you could add two more test cases (within this same file): one if there are just four implementations found and one if there are six (so that it says 'and 2 others').

File: src/test/ui/did_you_mean/issue-39802-show-5-trait-impls.rs (hunk 1 above)
Comment (seppo0010) [inline src/test/ui/did_you_mean/issue-39802-show-5-trait-impls.rs]: You are right, I copied it from `src/test/ui/did_you_mean/issue-21659-show-relevant-trait-impls-1.rs` which has both but I did not noticed the stderr file.

File: src/librustc/traits/error_reporting.rs [hunk 3]
```diff
@@ -392,12 +392,16 @@ impl<'a, 'gcx, 'tcx> InferCtxt<'a, 'gcx, 'tcx> {
             return;
         }
 
-        let end = cmp::min(4, impl_candidates.len());
+        let end = if impl_candidates.len() == 5 {
+            5
+        } else {
+            cmp::min(4, impl_candidates.len())
+        };
```
Comment (ranma42) [inline src/librustc/traits/error_reporting.rs]: This looks like a complex way to compute `cmp::min(5, impl_candidates.len())`

Comment (ranma42) [inline src/librustc/traits/error_reporting.rs]: How about

```Rust
        let end = if impl_candidates.len() <= 5 {
            impl_candidates.len()
        } else {
            4
        };
```
? At least for me, it would make it easier to immediately grasp the behaviour.

Comment (seppo0010) [inline src/librustc/traits/error_reporting.rs]: Good idea. I've added it and squashed the commits.

**Comment by jonathandturner** [comment]
Looks good.  Thanks for the PR!

@bors r+
