### PR TITLE
fix(lexer): Only allow horizontal whitespace in frontmatter 

### LINKED ISSUE #145971: `feature(frontmatter)` allows vertical whitespace where only horizontal whitespace is intended
I tried this code:

```rust
---\vcargo
---

fn main() {}
```

I expected to see this happen: error

Instead, this happened: its accepted

This is a shortcoming of the [RFC](https://rust-lang.github.io/rfcs/3503-frontmatter.html#reference-level-explanation) which used a loose term "whitespace" which tends to mean to rustc `Pattern_White_Space` when only the sub-category of horizontal whitespace was intended

### Meta

`rustc --version --verbose`:
```
rustc 1.91.0-nightly (54c581243 2025-08-25)
binary: rustc
commit-hash: 54c581243c977c7662c949b5795c31147f8a60ed
commit-date: 2025-08-25
host: x86_64-unknown-linux-gnu
release: 1.91.0-nightly
LLVM version: 21.1.0
```

<details><summary>Backtrace</summary>
<p>

```
<backtrace>
```

</p>
</details>

### PR DESCRIPTION
**Pull request by epage**
In writing up the reference for frontmatter, I realized that we probably
shouldn't be accepting Unicode Line Ending characters between the code
fence and infostring or trailing after the infostring or a code fence.

In digging into the unicode specification we use for Whitespace, it
divides it up into categories, so I'm deferring to what it says for
horizontal whitespace for what should be used within a line.

Note, I am leaving out support for Unicode Default Ignorable characters.
I figure that can be discussed outside of this change within the
reference and tracking issue.

Fixes rust-lang/rust#145971

Frontmatter tracking issue: rust-lang/rust#136889

### CODE REVIEW

File: tests/ui/frontmatter/frontmatter-contains-whitespace.rs [hunk 1]
```diff
@@ -0,0 +1,22 @@
+#!/usr/bin/env -S cargo -Zscript
+---cargo
+# Beware editing: it has numerous whitespace characters which are important.
+# It contains one ranges from the 'PATTERN_WHITE_SPACE' property outlined in
+# https: //unicode.org/Public/UNIDATA/PropList.txt
```
Comment (bjorn3) [inline tests/ui/frontmatter/frontmatter-contains-whitespace.rs]:
```suggestion
# https://unicode.org/Public/UNIDATA/PropList.txt
```

Comment (epage) [reply tests/ui/frontmatter/frontmatter-contains-whitespace.rs]: Thanks.  Some auto-formatter seemed to have been doing this.
