### PR TITLE
Revise std::thread

### LINKED ISSUE #20807: JoinGuard::join returning an Err is **really** unsafe
Exception safety is a very well-known problem in C++.

Consider this:

```cpp
struct Foo {
    int* ptr;
};

void modify(Foo& value) {
    delete foo.ptr;
    foo.ptr = new int;
}

void error_proof_modify(Foo& value) {
    try {
        modify(value);
    } catch(...) {
        cerr << "Error, but let's continue!";
    }
}
```

If the call to `new` throws an exception, the error gets caught and the execution continue. However the `Foo` object is now in an invalid state with its pointer pointing to memory that has been free'd.

Before #20615 and before the change in `Send` this is not possible in Rust, because when a thread panics all objects that are local to this thread are no longer accessible. It's also the reason why mutexes are poisoned in case of a panic.

But now that it's possible to send local variables to other threads, and ignore when this other thread panics, situations like this can totally happen.

Let's take this code for example:

```rust
pub struct Foo {
    val1: int,
    val2: int,
    val3: int,
    calculation_result: int,    // must always be equal to val1+val2+val3
}

impl Foo {
    pub fn set_val1(&mut self, value: int) {
        self.val1 = value;
        self.update_calculation();
    }
    pub fn set_val2(&mut self, value: int) {
        self.val2 = value;
        self.update_calculation();
    }
    pub fn set_val3(&mut self, value: int) {
        self.val3 = value;
        self.update_calculation();
    }

    fn update_calculation(&mut self) {
        if self.val1 == 127 { panic!("for the sake of this example, we panic") };
        self.calculation_result = self.val1 + self.val2 + self.val3;
    }
}
```

Looks safe, right?

But what if you use that "ignore panics" trick?

```rust
let mut foo: Foo = ...;  // whatever

Thread::scoped(|| {
    foo.set_val1(127);
}).join();   // ignoring the panic

use_foo(&foo);   // continue using `foo`
```

At the end of this code, you have a `Foo` object in an invalid state because `calculation_result` is not equal to `val1+val2+val3` as it should be. Continuing to use the Foo object in this invalid state could lead to weird and hard to debug results (depending on the rest of the code).

With the latest reforms in thread, library writer really have to take exception safety (or "panic safety") into account by avoiding the kind of code written above. You may argue that it's just the fault of the person who wrote the `Foo` struct. The problem is that exception safety is **hard**. Too hard to get right.

In my opinion, `JoinGuard::join` should just panic if the underlying thread panicked, without leaving the choice to the user. The only situation in which a `try_join` function (or another name) is safe is for `JoinGuard<'static>`.

cc @aturon

### PR DESCRIPTION
**Pull request by aturon**
This commit makes several changes to `std::thread` in preparation for
final stabilization:
- It removes the ability to handle panics from `scoped` children; see
  #20807 for discussion
- It adds a `JoinHandle` structure, now returned from `spawn`, which
  makes it possible to join on children that do not share data from
  their parent's stack. The child is automatically detached when the
  handle is dropped, and the handle cannot be copied due to Posix
  semantics.
- It moves all static methods from `std::thread::Thread` to free
  functions in `std::thread`. This was done in part because, due to the
  above changes, there are effectively no direct `Thread` constructors,
  and the static methods have tended to feel a bit awkward.
- Adds an `io::Result` around the `Builder` methods `scoped` and
  `spawn`, making it possible to handle OS errors when creating
  threads. The convenience free functions entail an unwrap.
- Stabilizes the entire module. Despite the fact that the API is
  changing somewhat here, this is part of a long period of baking and
  the changes are addressing all known issues prior to alpha2. If
  absolutely necessary, further breaking changes can be made prior to beta.

Closes #20807

[breaking-change]

r? @alexcrichton

### CODE REVIEW

**Comment by aturon** [comment]
This is WIP because I haven't yet moved the rest of the codebase off of now-deprecated functions. I wanted to get feedback on the direction of the API first.

cc @tomaka @pythonesque @sfackler @wycats @nikomatsakis

**Comment by tomaka** [comment]
:+1: for me!

**Comment by pythonesque** [comment]
Looks great!

**Comment by nikomatsakis** [comment]
:+1:

**Comment by sfackler** [comment]
:+1:

File: src/libstd/thread.rs [hunk 1]
```diff
@@ -316,17 +327,120 @@ impl Builder {
...
+/// it *must* be joined before the relevant stack frame is popped. See the
+/// module documentation for additional details.
+///
+/// # Panics
+///
+/// Panicks if the OS fails to create a thread; use `Builder::scoped`
+/// to recover from such errors.
+#[unstable(feature = "thread", reason = "recently moved")]
+pub fn scoped<'a, T, F>(f: F) -> JoinGuard<'a, T> where
+    T: Send + 'a, F: FnOnce() -> T, F: Send + 'a
```
Comment (alexcrichton) [inline src/libstd/thread.rs]: Is this `'a` bound on `T` required? I would expect that the compiler would already ensure that `T` couldn't refer to anything inside the local environment of `F`. As in, I expect `'a` to only be relevant to the lifetime of the closure and that would in turn imply that it bounds `T`.

File: src/libstd/thread.rs [hunk 2]
```diff
@@ -496,32 +652,32 @@ impl<'a, T: Send + 'a> JoinGuard<'a, T> {
...
 }
 
+#[stable(feature = "rust1", since = "1.0.0")]
 impl<T: Send> JoinGuard<'static, T> {
     /// Detaches the child thread, allowing it to outlive its parent.
-    #[unstable(feature = "std_misc",
-               reason = "unsure whether this API imposes limitations elsewhere")]
+    #[deprecated(since = "1.0.0", reason = "use spawn instead")]
+    #[unstable(feature = "std_misc")]
     pub fn detach(mut self) {
```
Comment (alexcrichton) [inline src/libstd/thread.rs]: This may still be a useful method to have perhaps? We'd probably want to only define it for `T = ()` but we could also just add this at a later ate.

File: src/libstd/thread.rs [hunk 3]
```diff
@@ -58,16 +58,16 @@
 //! ```rust
 //! use std::thread::Thread;
 //!
-//! let thread = Thread::spawn(move || {
+//! Thread::spawn(move || {
```
Comment (alexcrichton) [inline src/libstd/thread.rs]: Shouldn't this be `thread::spawn`?

**Comment by alexcrichton** [comment]
This looks great to me, r=me with a small nits and doc tests passing.

**Comment by alexcrichton** [comment]
I also talked with @aturon today and I would be comfortable marking these functions `#[stable]`.

**Comment by aturon** [comment]
@alexcrichton OK, I've pushed an update including a fallout commit. It hasn't gotten through tests yet, but I think any trouble there should be minor (if you want to stick it in a rollup). I'll keep pushing through the compilation meanwhile.

File: src/libstd/thread.rs [hunk 4]
```diff
@@ -476,52 +575,109 @@ struct Packet<T>(Arc<UnsafeCell<Option<Result<T>>>>);
...
+/// An owned permission to join on a thread (block on its termination).
+///
+/// Unlike a `JoinGuard`, a `JoinHandle` *detaches* the child thread
+/// when it is dropped, rather than automatically joining on drop.
+///
+/// Due to platform restrictions, it is not possible to `Clone` this
+/// handle: the ability to join a child thread is a uniquely-owned
+/// permission.
+#[stable(feature = "rust1", since = "1.0.0")]
+pub struct JoinHandle(JoinInner<()>);
```
Comment (huonw) [inline src/libstd/thread.rs]: Should this be a non-tuple struct per https://github.com/rust-lang/rust/issues/22045?

File: src/libstd/thread.rs [hunk 5]
```diff
@@ -476,52 +575,109 @@ struct Packet<T>(Arc<UnsafeCell<Option<Result<T>>>>);
...
+///
+/// Joining on drop is necessary to ensure memory safety when stack
+/// data is shared between a parent and child thread.
+///
+/// Due to platform restrictions, it is not possible to `Clone` this
+/// handle: the ability to join a child thread is a uniquely-owned
+/// permission.
+#[must_use]
+#[stable(feature = "rust1", since = "1.0.0")]
+pub struct JoinGuard<'a, T: 'a>(JoinInner<T>);
```
Comment (huonw) [inline src/libstd/thread.rs]: This needs a marker for `'a` (#22319 uses `_marker: CovariantType<&'a T>,`).

File: src/libstd/thread.rs (hunk 4 above)
Comment (aturon) [inline src/libstd/thread.rs]: The component is private, so I don't think there's any problem here.

**Comment by tshepang** [comment]
Since `scoped` also starts a thread, shouldn't it be a verb too... maybe something like `spawn_scoped`?

**Comment by sfackler** [comment]
While we're poking at the `Thread` API, there's another change that we may want to consider. Advanced configuration of a `Thread` happens via the `thread::Builder` type, which is constructed via its `new` method. Working with it ends up being a bit verbose: `thread::Builder::new()...` compared to `thread::spawn()`. One thing that Guava does that I think is kind of nice is to add a `builder` static method to the type that's buildable. For example, `ImmutableSet` is constructed via the `ImmutableSet.Builder` inner class. The normal way to work with it would be `new ImmutableSet.Builder().add(1).build()`, but you can instead just do `ImmutableSet.builder().add(1).build()`.

I've done something similar with r2d2's `Config` builder: http://sfackler.github.io/r2d2/doc/r2d2/struct.Config.html#method.builder to allow `Config::builder().pool_size(10).build()` instead of `config::Builder::new().pool_size(10).build()`. Since this change seems to be moving away from static methods on `Thread`, a `builder` free function in `thread` may be more applicable.
