### PR TITLE
Suggest removing `&` when awaiting a reference to a future

### LINKED ISSUE #87211: Confusing error: Immutable reference to future is not a future
Given the following code:

```rust
async fn my_async_fn() {}

async fn foo() {
    tokio::select! {
        _ = &my_async_fn() => {},
    }
}
```
[playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=b7adade3c7dd34b220454c8c4a3b5fc8)

The current output is:

```
error[E0599]: no method named `poll` found for struct `Pin<&mut &impl Future>` in the current scope
 --> src/lib.rs:5:5
  |
5 | /     tokio::select! {
6 | |         _ = &my_async_fn() => {}
7 | |     }
  | |_____^ method not found in `Pin<&mut &impl Future>`
  |
  = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)
```

---

Given the following code:
```rust
async fn my_async_fn() {}

async fn foo() {
    let fut = &my_async_fn();
    tokio::pin!(fut);
    
    fut.await;
}
```
[playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=78cfe7a15e3cbd16ae65d7918743050c)

The current output is:
```
error[E0277]: `&impl Future` is not a future
 --> src/lib.rs:8:5
  |
8 |     fut.await;
  |     ^^^^^^^^^ `&impl Future` is not a future
  |
  = help: the trait `Future` is not implemented for `&impl Future`
  = note: required because of the requirements on the impl of `Future` for `Pin<&mut &impl Future>`
  = note: required by `poll`
```

---

Given the following code:
```rust
async fn my_async_fn() {}

async fn foo() {
    let fut = &my_async_fn();
    
    fut.await;
}
```
[playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=e388bf1a28851e5f3ef57dbaef113ff0)

The current output is:
```
error[E0277]: `&impl Future` is not a future
 --> src/lib.rs:7:5
  |
7 |     fut.await;
  |     ^^^^^^^^^ `&impl Future` is not a future
  |
  = help: the trait `Future` is not implemented for `&impl Future`
  = note: required by `poll`
```

In all three cases, it would be very helpful if the compiler could explicitly call out that an immutable reference to a future is not a future. I see this relatively often in the Tokio discord where people put some extra ampersands in random places and get really confused when the error says "impl future is not future". The ampersand in the error is not enough to clue them in to what the issue is. Especially for the first case.

### PR DESCRIPTION
**Pull request by fru1tworld**
Fixes rust-lang/rust#87211

When `.await`ing `&impl Future`, suggest removing the `&` instead of removing `.await`.

### CODE REVIEW

File: compiler/rustc_trait_selection/src/error_reporting/traits/suggestions.rs [hunk 1]
```diff
@@ -1959,6 +1959,24 @@ impl<'a, 'tcx> TypeErrCtxt<'a, 'tcx> {
...
+            // instead of removing `.await`.
+            if let ty::PredicateKind::Clause(ty::ClauseKind::Trait(pred)) =
+                obligation.predicate.kind().skip_binder()
+                && let ty::Ref(_, inner_ty, hir::Mutability::Not) = *pred.self_ty().kind()
+                && let future_trait =
+                    self.tcx.require_lang_item(LangItem::Future, obligation.cause.span)
+                && self
+                    .type_implements_trait(future_trait, [inner_ty], obligation.param_env)
+                    .must_apply_modulo_regions()
+            {
```
Comment (chenyukang) [inline compiler/rustc_trait_selection/src/error_reporting/traits/suggestions.rs:2041]: maybe you want to use `span_suggestion_verbose` with `Applicability::MaybeIncorrect`.

File: compiler/rustc_trait_selection/src/error_reporting/traits/suggestions.rs [hunk 2]
```diff
@@ -1959,6 +1959,24 @@ impl<'a, 'tcx> TypeErrCtxt<'a, 'tcx> {
...
 
+            // If the type is `&T` where `T: Future`, suggest removing `&`
+            // instead of removing `.await`.
+            if let ty::PredicateKind::Clause(ty::ClauseKind::Trait(pred)) =
+                obligation.predicate.kind().skip_binder()
+                && let ty::Ref(_, inner_ty, hir::Mutability::Not) = *pred.self_ty().kind()
+                && let future_trait =
+                    self.tcx.require_lang_item(LangItem::Future, obligation.cause.span)
+                && self
+                    .type_implements_trait(future_trait, [inner_ty], obligation.param_env)
```
Comment (chenyukang) [inline compiler/rustc_trait_selection/src/error_reporting/traits/suggestions.rs]: This branch should not suggest removing `&` based only on inner_ty: `Future`. That also matches `&dyn Future`, where removing `&` is not a valid fix. Please reuse the existing span-based borrow-removal logic (see `suggest_remove_reference` or extract it into a helper) and only emit the fix-it when there is an actual borrow in the source.

test code for this is like:

```rust
async fn ref_param(fut: &impl Future<Output = ()>) {
    fut.await;
}

async fn dyn_ref_param(fut: &dyn Future<Output = ()>) {
    fut.await;
}

```

Comment (fru1tworld) [reply compiler/rustc_trait_selection/src/error_reporting/traits/suggestions.rs]: Added !matches!(inner_ty.kind(), ty::Dynamic(..)) to skip &dyn Future and added a test.

File: tests/ui/async-await/await-ref-future.stderr [hunk 3]
```diff
@@ -0,0 +1,42 @@
...
+
+error[E0277]: `&impl std::future::Future<Output = ()>` is not a future
+  --> $DIR/await-ref-future.rs:12:9
+   |
+LL |     fut.await;
+   |         ^^^^^ `&impl std::future::Future<Output = ()>` is not a future
+   |
+   = help: the trait `Future` is not implemented for `&impl std::future::Future<Output = ()>`
+   = note: &impl std::future::Future<Output = ()> must be a future or must implement `IntoFuture` to be awaited
+   = help: a reference to a future is not a future; consider removing the leading `&`-reference
```
Comment (chenyukang) [inline tests/ui/async-await/await-ref-future.stderr]: the check does not works since it still suggesting here.

Comment (fru1tworld) [reply tests/ui/async-await/await-ref-future.stderr]: Fixed - it now only suggests when there's an actual '&' in the source

File: tests/ui/async-await/await-ref-future.stderr [hunk 4]
```diff
@@ -0,0 +1,65 @@
+error[E0277]: `&impl Future<Output = ()>` is not a future
+  --> $DIR/await-ref-future.rs:9:9
+   |
+LL |     fut.await;
```
Comment (chenyukang) [inline tests/ui/async-await/await-ref-future.stderr:4]: *[View changes since the review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/rust/154933/c756124775121dea0e640652c5ee3c89e3dd0eb4..fe623c3ee770d44d2ea78f96090797184e7b72cb)*

this test is the code from original issue, now `suggest remove &` not working for it.

as I referred, you may need to reuse the existing span-based borrow-removal logic (see suggest_remove_reference or extract it into a helper)

**Comment by chenyukang** [comment]
nit: 

it's not necessary to request review after each commit, reviewer can receive notification from your git push, and will review it when time available(it's normal to wait several days since a lot of us working in free time). https://rustc-dev-guide.rust-lang.org/contributing.html?highlight=reviewer#waiting-for-reviews

`request review` may makes them feel too pushy.

File: compiler/rustc_trait_selection/src/error_reporting/traits/suggestions.rs [hunk 5]
```diff
@@ -1963,6 +1982,104 @@ impl<'a, 'tcx> TypeErrCtxt<'a, 'tcx> {
...
+                                            true
+                                        }
+                                        _ => false,
+                                    }
+                                }
+                                // Case 3a: `async fn foo(fut: &impl Future) { fut.await }`
+                                // In async fn, params are desugared: `let fut = __arg0;`
+                                // with `LocalSource::AsyncFn`. Follow init back to the
+                                // original parameter.
+                                hir::Node::LetStmt(local)
```
Comment (chenyukang) [inline compiler/rustc_trait_selection/src/error_reporting/traits/suggestions.rs]: This is still a fairly ad hoc reimplementation of borrow-removal logic, and it misses cases that the more general machinery should handle. For example, `let fut = &&my_async_fn(); fut.await;` still falls back to `help: remove the .await`. I think the better direction is to extract the borrow-peeling/span-finding part of `suggest_remove_reference` above and reuse it here, instead of open special handling for cases such as `AddrOf / LetStmt / AsyncFn` cases again.

*[View changes since the review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/rust/154933/e5efd33d2df6bd128be197468b3c6119bf58fe66..9aed706f460ff0d8ebdfdd652fb5c10345db4cd4)*

File: compiler/rustc_trait_selection/src/error_reporting/traits/suggestions.rs [hunk 6]
```diff
@@ -2020,6 +2034,86 @@ impl<'a, 'tcx> TypeErrCtxt<'a, 'tcx> {
...
+                                msg,
+                                suggestions,
+                                Applicability::MachineApplicable,
+                            );
+                            return;
+                        }
+                    }
+
+                    // Try removing `&` from the parameter type.
+                    if let Some(param) = terminal_param {
```
Comment (chenyukang) [inline compiler/rustc_trait_selection/src/error_reporting/traits/suggestions.rs:2102]: thanks, this version sees better.

this test should not suggest removing from parameter?

```rust
async fn ref_param_borrowed_expr(fut: &impl std::future::Future<Output = ()>) {
    (&fut).await; //~ ERROR is not a future
}
```

*[View changes since the review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/rust/154933/bd1e7c79485d6a4113bb11dd98cb8b415cd4a55e..13231643558c0170f871eee1f5ae28d4dcc2be5b)*

**Comment by fru1tworld** [comment]
Fixed — guarded param `&` removal with `peeled_refs.is_empty()` so it's skipped when the expression itself has `&`. Added test for the case.

**Comment by chenyukang** [comment]
Thanks! 

@bors r=chenyukang
