### PR TITLE
rustc: Fix mixing crates with different `share_generics`

### LINKED ISSUE #64319: Symbol names may not correctly account for optimization level differences between crates
On investigating https://github.com/rust-lang/wg-cargo-std-aware/issues/32 I've managed to reduce this down to:

```
$ cat foo.rs
pub fn foo() {
    bar::<usize>();
}

pub fn bar<T>() {
    baz();
}

fn baz() {}
$ cat bar.rs
extern crate foo;

pub fn bar() {
    foo::foo();
}
$ rustc --crate-type rlib foo.rs
$ rustc --crate-type dylib bar.rs -L .
$ rustc --crate-type dylib bar.rs -L .  -C opt-level=2
error: linking with `link.exe` failed: exit code: 1120
  |
  = note: "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.22.27905\\bin\\HostX64\\x64\\link.exe" "/NOLOGO" "/NXCOMPAT" "/LIBPATH:C:\\Users\\alex\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib" "bar.bar.3a1fbbbh-cgu.0.rcgu.o" "/OUT:bar.dll" "/DEF:C:\\Users\\alex\\AppData\\Local\\Temp\\rustcAYUABK\\lib.def" "bar.13x131manznmlae2.rcgu.o" "bar.4hnz5vh12lvh2qha.rcgu.o" "/OPT:REF,ICF" "/DEBUG" "/NATVIS:C:\\Users\\alex\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\etc\\intrinsic.natvis" "/NATVIS:C:\\Users\\alex\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\etc\\liballoc.natvis" "/NATVIS:C:\\Users\\alex\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\etc\\libcore.natvis" "/LIBPATH:." "/LIBPATH:C:\\Users\\alex\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib" "C:\\Users\\alex\\AppData\\Local\\Temp\\rustcAYUABK\\libfoo.rlib" "C:\\Users\\alex\\AppData\\Local\\Temp\\rustcAYUABK\\libstd-b2f27b8d08c4688f.rlib" "C:\\Users\\alex\\AppData\\Local\\Temp\\rustcAYUABK\\libpanic_unwind-9c73c9c2e052b2f1.rlib" "C:\\Users\\alex\\AppData\\Local\\Temp\\rustcAYUABK\\libbacktrace-7a588e8fa018f6bc.rlib" "C:\\Users\\alex\\AppData\\Local\\Temp\\rustcAYUABK\\librustc_demangle-74b71f441b8acffe.rlib" "C:\\Users\\alex\\AppData\\Local\\Temp\\rustcAYUABK\\libhashbrown-42efce06651eab9c.rlib" "C:\\Users\\alex\\AppData\\Local\\Temp\\rustcAYUABK\\librustc_std_workspace_alloc-7518db6030684168.rlib" "C:\\Users\\alex\\AppData\\Local\\Temp\\rustcAYUABK\\libunwind-f7edde5930d50b47.rlib" "C:\\Users\\alex\\AppData\\Local\\Temp\\rustcAYUABK\\libcfg_if-30189c8e78e151e8.rlib" "C:\\Users\\alex\\AppData\\Local\\Temp\\rustcAYUABK\\liblibc-5f5719f1cab83a12.rlib" "C:\\Users\\alex\\AppData\\Local\\Temp\\rustcAYUABK\\liballoc-f297c401e81b90c6.rlib" "C:\\Users\\alex\\AppData\\Local\\Temp\\rustcAYUABK\\librustc_std_workspace_core-f8c80c1aefab6a32.rlib" "C:\\Users\\alex\\AppData\\Local\\Temp\\rustcAYUABK\\libcore-6d66b6e58725d3ed.rlib" "C:\\Users\\alex\\AppData\\Local\\Temp\\rustcAYUABK\\libcompiler_builtins-1f6a73e107798f53.rlib" "advapi32.lib" "ws2_32.lib" "userenv.lib" "msvcrt.lib" "/DLL" "/IMPLIB:bar.dll.lib"
  = note: lib.def : error LNK2001: unresolved external symbol _ZN3foo3bar17h95b7da637b923d2cE
          bar.dll.lib : fatal error LNK1120: 1 unresolved externals


error: aborting due to previous error
```

The platform used here to reproduce the error is x86_64-pc-windows-msvc, but it looks like macOS also generates the same error. The error doesn't appear to manifest on Linux, presumably because the linker options just ignore non-defined symbols.

Here you can see that when both crates are compiled with the same optimization level the link succeeds, but with different optimization levels the wrong symbol name is generated, so the wrong symbol is asked to be exported which causes an error.

### PR DESCRIPTION
**Pull request by alexcrichton**
This commit addresses #64319 by removing the `dylib` crate type from the
list of crate type that exports generic symbols. The bug in #64319
arises because a `dylib` crate type was trying to export a symbol in an
uptream crate but it miscalculated the symbol name of the uptream
symbol. This isn't really necessary, though, since `dylib` crates aren't
that heavily used, so we can just conservatively say that the `dylib`
crate type never exports generic symbols, forcibly removing them from
the exported symbol lists if were to otherwise find them.

The fix here happens in two places:

* First is in the `local_crate_exports_generics` method, indicating that
  it's now `false` for the `Dylib` crate type. Only rlibs actually
  export generics at this point.

* Next is when we load exported symbols from upstream crate. If, for our
  compilation session, the crate may be included from a dynamic library,
  then its generic symbols are removed. When the crate was linked into a
  dynamic library its symbols weren't exported, so we can't consider
  them a candidate to link against.

Overally this should avoid situations where we incorrectly calculate the
upstream symbol names in the face of differnet `share_generics` options,
ultimately...

Closes #64319

### CODE REVIEW

File: src/librustc_codegen_utils/symbol_names.rs [hunk 1]
```diff
@@ -184,7 +184,7 @@ fn symbol_name(tcx: TyCtxt<'tcx>, instance: Instance<'tcx>) -> InternedString {
 
     let instantiating_crate = if avoid_cross_crate_conflicts {
         Some(if is_generic {
-            if !def_id.is_local() && tcx.sess.opts.share_generics() {
+            if !def_id.is_local() && tcx.share_generics(def_id.krate) {
```
Comment (Mark-Simulacrum) [inline src/librustc_codegen_utils/symbol_names.rs]: It seems worthwhile to change all the use sites to the query instead of sess.opts and perhaps rename the method on sess.opts to `share_generics_untracked`.

File: src/test/run-make-fulldeps/issue-64319/Makefile [hunk 2]
```diff
@@ -0,0 +1,10 @@
+-include ../tools.mk
+
+all:
+	$(RUSTC) --crate-type rlib foo.rs
+	$(RUSTC) --crate-type dylib bar.rs
+	$(RUSTC) --crate-type dylib bar.rs -C opt-level=1
+	$(RUSTC) --crate-type dylib bar.rs -C opt-level=2
+	$(RUSTC) --crate-type dylib bar.rs -C opt-level=3
+	$(RUSTC) --crate-type dylib bar.rs -C opt-level=s
+	$(RUSTC) --crate-type dylib bar.rs -C opt-level=z
```
Comment (michaelwoerister) [inline src/test/run-make-fulldeps/issue-64319/Makefile]: Could you also add `$(RUSTC) --crate-type dylib bar.rs -C opt-level=3 -Zshare-generics=on` ?

File: src/librustc_codegen_utils/symbol_names.rs (hunk 1 above)
Comment (michaelwoerister) [reply src/librustc_codegen_utils/symbol_names.rs]: Good observation, @Mark-Simulacrum! I would even go a step further and remove `sess.opt.share_generics()` in favor of the local query provider.

**Review by michaelwoerister — COMMENTED** [review]
Thanks, @alexcrichton! The fix looks good. r=me with the comments addressed.

File: src/test/run-make-fulldeps/issue-64319/Makefile (hunk 2 above)
Comment (michaelwoerister) [reply src/test/run-make-fulldeps/issue-64319/Makefile]: Also, could you please add a comment saying that different optimization levels imply different settings for generics sharing?

**Comment by alexcrichton** [comment]
So it turns out the previous version of this PR was also incorrect (hence the test failure on CI). The problem was that it was testing whether the *defining* crate was in `share-generics` mode, but actually we want to query whether the *instantiating* crate is in `share-generics` mode. 

@michaelwoerister this actually I think poses an interesting question for everything in the standard library because the standard library is basically never built in `-Zshare-generics` mode (since it's optimized), but that's one of the biggest benefits which is to reuse crate monomorphizations of standard library symbols. I think this means that `-Zshare-generics=yes` (or just debug builds by default) will now actually share monomorphizations of standard library functions, whereas previously they didn't.

Still running the full test suite locally, but @michaelwoerister if you wouldn't mind giving another look at this I'm a bit hesitant to carry over the r+!

**Comment by alexcrichton** [comment]
Alright now I'm actually just hurting myself in my own confusion. Standard library generics are indeed shared today, my comment above was actually about a previous version of my patch. I'm basically throwing logic at the wall right now and seeing what sticks, and this definitely isn't great. 

Taking a step back it seems like there's logically some duplication between [this function](https://github.com/rust-lang/rust/blob/403c0def905c58f08e5a1ce48a430522df01abf1/src/librustc_mir/monomorphize/collector.rs#L798-L824) and [this deduction](https://github.com/rust-lang/rust/blob/403c0def905c58f08e5a1ce48a430522df01abf1/src/librustc_codegen_utils/symbol_names.rs#L185-L203). I'm confusing myself now as to why symbol names need to account for `share-generics` settings of upstream crates but the collector doesn't.

Thinking about this more I think that this is sort of a fundamental problem with how the linker is requesting symbol names today. For some crate types (like dylibs) the compiler needs to generate an [exhaustive symbol list](https://github.com/rust-lang/rust/blob/87b0c9036f0557568cfc939542508e9adf874b83/src/librustc_codegen_ssa/back/linker.rs#L1076-L1107) to export, and for dylibs this means exported upstream symbols as well. The problem here is that we're dynamically calculating the actual name of the symbol (via the `symbol_name` query). This means we have one of two situations:

* First, we're the linker. This means that we just want to figure out the name of the symbol from the context of the crate we're linking.
* Second, we're the compiler referencing another crate's symbol. This is where I'm confusing myself with `share_generics`, and it's also where I'm confusing myself with the collector. If `share_generics` is turned on then if we find a symbol that has an upstream monomorphization, that was actually only possible if the upstream crate had `share_generics` turned on, and we want to use that crate's. If `share_generics` is turned off, though, then we *always* want to use a local copy, and the collector always generated a local copy.

The problem here is that these two contexts are subtly different around how they're supposed to calculate the symbol name. The main piece of this boils down to what crate instantiated the symbol, where in the case of linked symbols we've always got it but today it's always inferred and is dependent on the `share_generics` setting. The inference runs the risk of being wrong for the linker case though if the `share_generics` settings are different. I'll need to think more about how to solve this...

Note that this patch is green on CI, but fails on Windows, because for whatever reason the test case I have passes on Linux but not on macOS or Windows.

**Comment by michaelwoerister** [comment]
I'm sorry this is giving you trouble, @alexcrichton. I remember fighting with the logic quite a bit during the initial implementation.

OK, so the problem is that 
- the list of exported symbols contains names that don't actually exits,
- which occurs if an upstream crate shares a generic instance and a downstream crate tries to create its own, private copy of the same instance.

Do we know if both symbols show up in the export list? Or just the upstream or downstream one? 
We do know that the upstream one should show up (because it is shared) while the upstream one should not show up. 

This is another problem that only exists because of Rust dylibs `:)`

**Comment by michaelwoerister** [comment]
Somewhat related: We might want to give using `weak_odr` linkage for generics a try again. That would simplify symbol name generation.

**Comment by michaelwoerister** [comment]
One thing that might be happening: 
- The linker script contains the symbol name of the upstream generic because it is added here: https://github.com/rust-lang/rust/blob/74d5c70b174f06843049af2d764ff57ddc81c81c/src/librustc_codegen_ssa/back/linker.rs#L1095-L1103

- but since the local crate has it's private copy of the generic, the upstream one is actually never referenced anywhere, and thus is never pulled out of the upstream archive.

I don't know if linkers actually work that way. But archives are treated more lazily than object files, right?

**Comment by michaelwoerister** [comment]
OK, I was able to reproduce the problem on Windows and here is my analysis (which I think is the same as yours, @alexcrichton):

- the compiler tries to generate the list of exported symbols for the downstream crate.
- because the downstream crate is a Rust dylib, this list should also contain the exported generics from upstream rlibs that are included in the dylib, so
- the compiler iterates the exported instances in the upstream rlib and tries to build the symbol name for each.
- the `symbol_name` query tries to infer the instantiating crate from the compiler's current settings and gets it wrong, because what we want to export is the upstream symbol, not the local, private copy in the downstream crate.

So in essence, there are two symbol names for the same instance, both of which the compiler needs in different contexts, but the `symbol_name` query has no parameter to disambiguate the two versions.

**Comment by alexcrichton** [comment]
Oh man believe me I'd be the first person to throw my weight behind any "remove rust dylibs once and for all" proposal, they do indeed seem to only cause endless effort and pain for not a lot of gain!

In any case, putting that aside, sounds like we're definitely on the same page. Agreed with everything you've said :)

I was thinking a bit about how to best solve this yesterday, but I wasn't really able to come up with something great. I'll look to see if there's a low-impact second query argument we could add or maybe a low-impact way to add a second query.

**Comment by michaelwoerister** [comment]
:+1:

**Comment by alexcrichton** [comment]
Ok I've edited the PR description and I've also pushed up a new commit, and I believe that this should address the issue.

**Comment by alexcrichton** [comment]
... or this strategy completely breaks sharing of generics in the first place. Still working!

**Comment by michaelwoerister** [comment]
Am I reading this right that the changes here store all symbol names as strings in metadata? That must be a lot of data. Let's do a perf run.

@bors try

**Comment by alexcrichton** [comment]
@rust-timer build fdcee83cffac506dea10f2826097bbcf9fc9fcce

**Comment by michaelwoerister** [comment]
It looks like performance regresses just a little bit for a handful of test cases while for the rest it stays the same. @alexcrichton, did you happen to compare rlib/rmeta sizes with and without the patch?

**Comment by alexcrichton** [comment]
Given a pretty unscientific measurement, I used Cargo as a test bed and got:

```
$ du -s before/debug/deps after/debug/deps
866792  before/debug/deps
889324  after/debug/deps
```

which is 2.5% larger overall.

However `libcargo-*.rmeta` increased from 9765824 to 14763317, a 34% increase.

That seems like it's probably not a great idea given the niche of the problem space this is fixing. 

I've got an idea of how to fix this entirely differently, so let me see if I can get that working.

**Comment by alexcrichton** [comment]
Ok here's another attempt, entirely new strategy. The first commit is a refactoring of dependency formats into a query, and the second leverages this to use dependency formats to inform symbol exports here and there. The tl;dr; is that `dylib` crate types no longer export generics, and so the `share_generics` setting is basically ignored there.

**Comment by michaelwoerister** [comment]
Yes, I'm not surprised that rmeta files grow quite a bit. I think at one point I had implemented the same solution (i.e. storing exported generics as symbol name strings instead of DefIds) and just felt bad about the amount of redundant data.

Regarding a different solution: I haven't actually tried this but might it be possible to just add a parameter for the instantiating crate to the query and then pull out the logic into a helper method? Something like:

```rust
// The query
fn symbol_name(tcx: TyCtxt<'tcx>, instance: Instance<'tcx>, instantiating_crate: Option<CrateNum>) -> InternedString {
    // ...
}

// Helper method
impl TyCtxt {
    // What an awesome method name!
    fn symbol_name_as_used_locally(self, instance: Instance) -> InternedString {
        // Do the deduction of the instantiating crate here.
        // This is moved out of the query provider above.
        let is_generic = substs.non_erasable_generics().next().is_some();
        let avoid_cross_crate_conflicts =
            // If this is an instance of a generic function, we also hash in
            // the ID of the instantiating crate. This avoids symbol conflicts
            // in case the same instances is emitted in two crates of the same
            // project.
            is_generic ||

            // If we're dealing with an instance of a function that's inlined from
            // another crate but we're marking it as globally shared to our
            // compliation (aka we're not making an internal copy in each of our
            // codegen units) then this symbol may become an exported (but hidden
            // visibility) symbol. This means that multiple crates may do the same
            // and we want to be sure to avoid any symbol conflicts here.
            match MonoItem::Fn(instance).instantiation_mode(tcx) {
                InstantiationMode::GloballyShared { may_conflict: true } => true,
                _ => false,
            };

        let instantiating_crate = if avoid_cross_crate_conflicts {
            Some(if is_generic {
                if !def_id.is_local() && tcx.sess.opts.share_generics() {
                    // If we are re-using a monomorphization from another crate,
                    // we have to compute the symbol hash accordingly.
                    let upstream_monomorphizations = tcx.upstream_monomorphizations_for(def_id);

                    upstream_monomorphizations
                        .and_then(|monos| monos.get(&substs).cloned())
                        .unwrap_or(LOCAL_CRATE)
                } else {
                    LOCAL_CRATE
                }
            } else {
                LOCAL_CRATE
            })
        } else {
            None
        };

        self.symbol_name(instance, instantiating_crate)
    }
}


/// and then in back/linker.rs

fn exported_symbols(tcx: TyCtxt<'_>, crate_type: CrateType) -> Vec<String> {

    // ...

    // For each dependency that we are linking to statically ... 
    if *dep_format == Linkage::Static { 
        // ... we add its symbol list to our export list. 
        for &(symbol, level) in tcx.exported_symbols(cnum).iter() { 
            if level.is_below_threshold(export_threshold) { 
                symbols.push(tcx.symbol_name(symbol, cnum).to_string());
            } 
        } 
    }

    // ...
}
```

That being said, if you have a clean solution that just makes dylibs not participate in the sharing, I'd be happy with that too.

**Comment by alexcrichton** [comment]
I was initially thinking that strategy too, but honestly I thought queries couldn't take more than one parameter so I didn't pursue it very far. I see now that the one parameter can be a tuple, and it probably works the way I would expect. d'oh!

In the end though I feel like this current strategy with dylibs ended up working alright and was relatively low-impact. I'm curious what you think though with regards to the implementation? I don't mind rewriting to use the two-argument method instead if this looks too hairy.

**Comment by michaelwoerister** [comment]
Yes, I'll take a look at your solution tomorrow.

File: src/librustc_metadata/dependency_format.rs [hunk 3]
```diff
@@ -0,0 +1,371 @@
...
+use rustc::ty::TyCtxt;
+use rustc::util::nodemap::FxHashMap;
+use rustc_target::spec::PanicStrategy;
+
+pub fn calculate(tcx: TyCtxt<'_>) -> Dependencies {
+    tcx.sess.crate_types.borrow().iter().map(|&ty| {
+        let linkage = calculate_type(tcx, ty);
+        verify_ok(tcx, &linkage);
+        (ty, linkage)
+    }).collect::<Vec<_>>()
```
Comment (michaelwoerister) [inline src/librustc_metadata/dependency_format.rs]: Since the output of queries should be as stable and deterministic as possible, could you sort these lists (at all nesting levels)?

File: src/librustc_metadata/cstore_impl.rs [hunk 4]
```diff
@@ -239,7 +241,30 @@ provide! { <'tcx> tcx, def_id, other, cdata,
...
+        let mut syms = cdata.exported_symbols(tcx);
+
+        // When linked into a dylib crates don't export their generic symbols,
+        // so if that's happening then we can't load upstream monomorphizations
+        // from this crate. As a result, if we're creating a dylib or this crate
+        // is being included from a different dynamic library, then we filter
+        // out all `Generic` symbols here.
+        let formats = tcx.dependency_formats(LOCAL_CRATE);
+        let remove_generics = formats.iter().any(|(ty, list)| {
+            *ty == CrateType::Dylib ||
```
Comment (michaelwoerister) [inline src/librustc_metadata/cstore_impl.rs]: This might be a bit more restrictive than necessary. If the current crate is a dylib, it can still link against upstream generics. It just shouldn't re-export them.

**Comment by michaelwoerister** [comment]
This solution looks good to me in general. It would be good to try and let dylibs still make use of shared generics (even though they don't contribute themselves).

File: src/librustc_metadata/dependency_format.rs (hunk 3 above)
Comment (alexcrichton) [reply src/librustc_metadata/dependency_format.rs]: I think that these are actually already sorted, although I could be wrong! The top-most layer of a vec of tuples is based on `tcx.sess.crate_types` which I'd assume is already sorted and/or deterministic, and the next layer of lists is sorted since it's a "map" from `CrateId` to a value (via a semi-weird indexing scheme)

File: src/librustc_metadata/cstore_impl.rs (hunk 4 above)
Comment (alexcrichton) [reply src/librustc_metadata/cstore_impl.rs]: True yeah, and I've added a commit now which is relatively low-impact which should solve this

**Comment by michaelwoerister** [comment]
Thank you, @alexcrichton! This looks good. Let's do one last perf run, so there are no surprises.

@bors try @rust-timer queue

**Comment by michaelwoerister** [comment]
Alright, looks like performance isn't affected.

@bors r+

**Comment by michaelwoerister** [comment]
🎉
