### PR TITLE
Replace custom trim_ascii_start with the standard library method

### LINKED ISSUE #53: Outreachy tracking issue for Rust whitespace check bugs
The Rust language specification (specifically, the lexer) [defines "whitespace"](https://doc.rust-lang.org/reference/whitespace.html) including the "vertical tab" character.

But some tools that process Rust use [the standard library's `is_ascii_whitespace`](https://doc.rust-lang.org/std/?search=is_ascii_whitespace) which doesn't include vertical tab. This is a bug.

This ticket is based on this [Zulip discussion](https://rust-lang.zulipchat.com/#narrow/channel/213817-t-lang/topic/broken.20and.20un-fixable.20parts.20of.20Rust/near/583617301)

### Impacted Functions

Any standard library (or crate) functions that call `is_ascii_whitespace` are also impacted:
- [`trim_ascii`*](https://doc.rust-lang.org/std/primitive.slice.html?search=trim_ascii)
- [`split_ascii_whitespace`](https://doc.rust-lang.org/std/primitive.str.html#method.split_ascii_whitespace)
- [`ascii::Char::is_whitespace`](https://doc.rust-lang.org/core/ascii/enum.Char.html#method.is_whitespace)
- TODO: are there any others?

### How to Fix this Bug

Unfortunately, there is no standard library method that matches on Unicode `Pattern_White_Space` (or the ASCII or `u8` subset). So the fix should call [the Rust compiler function](https://github.com/rust-lang/rust/blob/bcded331651b60a0383b3ff51db4f24c4495ac53/compiler/rustc_lexer/src/lib.rs#L341), or create a new function with the correct filters by escape or character code.

#### Steps to Fix these Bugs

You can use AI for your understanding, but don't use it to write messages, comments, or code. We want to talk to you, and we want you to contribute your own work!

You ***must*** have a code example PR merged for either the Overloading or Build System project. If you don't, open a PR for Overloading (Build System is closed to new applicants), or work on your open PR until it is finished.

1. Choose one bug from the list of bugs. There is a ***strict limit*** of one bug per Outreachy applicant. Claim the issue by commenting on this ticket. If someone else has claimed it, choose another bug. 
2. Read the contribution instructions for the Rust tool you're fixing.
3. Checkout the tool's git repository.
4. Create a commit with a test that shows the issue, this test should fail until you fix the bug.
5. Fix the issue in another commit, and update the tests or test outputs so they pass.
6. Open a PR for the Rust tool that explains the issue, and fixes it. Add a link to this issue (https://github.com/rustfoundation/interop-initiative/issues/53) in the PR description.

Unusual whitespace is deleted by `rustfmt`, so you might need to put `#[rustfmt::skip]` in your test code. (Or `#![rustfmt::skip]` at the top of the file.)

For more details, see the [Zulip discussion](https://rust-lang.zulipchat.com/#narrow/channel/213817-t-lang/topic/broken.20and.20un-fixable.20parts.20of.20Rust/near/583617301).

### List of Bugs that exclude Vertical Tab

These bugs don't include Vertical Tab. They also don't include Unicode `Pattern_White_Space`, but that might be intentional.

Extra steps for these bugs:
7. On the PR, ask if you should switch from checking ASCII to Unicode.

#### Clippy

- [x] [false negative in needless ifs](https://github.com/rust-lang/rust/blob/e0e95a71872dfe9e15d22bddea9ac45c85ddda1a/src/tools/clippy/clippy_lints/src/needless_ifs.rs#L58)
- [x] [short span in same match arms](https://github.com/rust-lang/rust/blob/e0e95a71872dfe9e15d22bddea9ac45c85ddda1a/src/tools/clippy/clippy_lints/src/matches/match_same_arms.rs#L180)
- [x] [incorrect whitespace check in collapsible_if](https://github.com/rust-lang/rust/blob/ad4b9354009cb6bd5a9ff1b5f5a63a13ec98ebc9/src/tools/clippy/clippy_lints/src/collapsible_if.rs#L144)

#### rustfmt

- [x] Only splitting on regex ASCII whitespace (including vertical tab), but not Unicode `Pattern_White_Space` in the [line splitting regex](https://github.com/rust-lang/rust/blob/bcded331651b60a0383b3ff51db4f24c4495ac53/src/tools/rustfmt/src/string.rs#L76) - [regex docs](https://docs.rs/regex/latest/regex/#ascii-character-classes)

#### Rust Analyzer

- [x] [panic in rust-analyzer whitespace token check](https://github.com/rust-lang/rust/blob/e0e95a71872dfe9e15d22bddea9ac45c85ddda1a/src/tools/rust-analyzer/crates/syntax/src/ast/make/quote.rs#L186)
- [x] [non-macro code miscompare](https://github.com/rust-lang/rust/blob/e0e95a71872dfe9e15d22bddea9ac45c85ddda1a/src/tools/rust-analyzer/crates/rust-analyzer/src/cli/analysis_stats.rs#L1648) - currently commented out

### List of Related Bugs

If all bugs above are claimed, you can do one of these related bugs or cleanups instead.

#### ~~Rust run-make-support~~

- ~~[implement shell whitespace splitting correctly](https://github.com/rust-lang/rust/blob/ad4b9354009cb6bd5a9ff1b5f5a63a13ec98ebc9/src/tools/run-make-support/src/run.rs#L96)~~

#### Rust Compiler

- [x] [Markdown code block parsing accepts trailing non-whitespace (but bans whitespace)](https://github.com/rust-lang/rust/blob/bcded331651b60a0383b3ff51db4f24c4495ac53/compiler/rustc_errors/src/markdown/parse.rs#L223)
    - Instead, it should accept trailing whitespace, and ban trailing non whitespace. This is roughly `!any(!u8::is_ascii_whitespace)`, or more simply, `all(u8::is_ascii_whitespace)`.

#### Rust Compiler

- [x] [Replace custom `trim_ascii_start` function with the standard library function](https://github.com/rust-lang/rust/blob/bcded331651b60a0383b3ff51db4f24c4495ac53/compiler/rustc_errors/src/markdown/parse.rs#L582)
    - this is markdown parsing, so the [check is correct](https://spec.commonmark.org/0.31.2/#preliminaries), but it doesn't need to duplicate standard library code
    - the Rust maintainers might tell you to fix the function to match its documentation instead - that's ok

### List of Bugs that include too much Unicode Whitespace

These bugs include all Unicode `White_Space` using `is_whitespace` methods. But the Rust language uses Unicode `Pattern_White_Space` as whitespace.

_No confirmed bugs, in most tools (except the lexer), ignoring more whitespace is not a significant bug._

If you think you've found a significant buggy use of `is_whitespace`, `trim` or similar in a Rust parser, please comment below.

### If there aren't any bugs left

Add tests for the rust compiler, clippy, rustfmt, or other Rust tools, which process Rust source code files containing:
- Unicode [Pattern_White_Space](https://www.unicode.org/reports/tr31/#R3a), which should be accepted
    - [WhatWG ASCII whitespace](https://infra.spec.whatwg.org/#ascii-whitespace) is a subset of this whitespace
- Non-Pattern Unicode [White_Space](https://www.unicode.org/Public/UCD/latest/ucd/PropList.txt), which should be rejected

You might need to use a character picker or Rust code to write the Unicode whitespace to the file.

List of tools:
- [x] rustfmt
- [ ] clippy
- [x] rustc (rust compiler)
- [ ] rust-analyzer
- [ ] TODO: other tools?

### PR DESCRIPTION
**Pull request by thebabalola**
The markdown parser in `rustc_errors` has a local `trim_ascii_start` function that strips leading ASCII whitespace from a byte slice. The standard library has had `<[u8]>::trim_ascii_start()` since Rust 1.80, which does the same thing.

This PR removes the custom function and calls the stdlib method directly in `parse_unordered_li` and `parse_ordered_li`. No behaviour change.

I also added a test covering the list item leading-whitespace trimming behaviour, including a tab case.

Fixes rustfoundation/interop-initiative#53

### CODE REVIEW

File: compiler/rustc_errors/src/markdown/tests/parse.rs [hunk 1]
```diff
@@ -377,3 +377,25 @@ fn test_codeblock_trailing_whitespace() {
...
+#[rustfmt::skip]
+#[test]
+fn test_list_item_leading_whitespace() {
+    // extra spaces after marker
+    let buf = "-   hello";
+    let (t, r) = parse_unordered_li(buf.as_bytes());
+    assert_eq!(t, MdTree::UnorderedListItem(vec![MdTree::PlainText("hello")].into()));
+    assert_eq!(r, b"");
+
+    // tab after the marker space — needs #[rustfmt::skip] or rustfmt removes it
```
Comment (mati865) [inline compiler/rustc_errors/src/markdown/tests/parse.rs]: *[View changes since the review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/rust/155134/02c7f9bec0fd583160f8bcccb830216023b07bee..2ac1c915504d353ab8fdbc6b1f816b7071c43069)*

I doubt rustfmt would rewrite string like that and I cannot reproduce the problem, how did you run into that?

Comment (thebabalola) [reply compiler/rustc_errors/src/markdown/tests/parse.rs]: You're right,  I actually added the #[rustfmt::skip] out of caution after seeing a note in the tracking issue about rustfmt removing unusual whitespace. But since the tab is written as \t in the string literal (not a literal tab character), rustfmt won't touch it. I'll just remove the attribute.

Comment (mati865) [reply compiler/rustc_errors/src/markdown/tests/parse.rs]: Please squash the commit and update the description.

Comment (teor2345) [reply compiler/rustc_errors/src/markdown/tests/parse.rs]: > Please squash the commit and update the description.

@thebabalola do you need help with squashing commits?

@rustbot author

Comment (thebabalola) [reply compiler/rustc_errors/src/markdown/tests/parse.rs]: @teor2345 ...  Already done, squashed to 2 commits and force pushed earlier. Thanks for checking..

**Comment by mati865** [comment]
Great, thanks!

@bors r+
