### PR TITLE
Fixes submit event of the search input

### LINKED ISSUE #79960: rustdoc help popup appears in every new tab when no web local storage
In current Rust nightly, the std docs search function does a very annoying thing for me: every time I open a new tab onto the rust std docs, I get once again the popup with the keybindings which I then have to dismiss.

I conjecture that this is because I am looking at locally built docs via a `file://` URL.  Presumably the same thing would occur for a user who has sensibly disabled cookies in their web browser, resulting in the same horrible "stupid popup" user experience.

Given that without web local storage it is not possible to make a thing that is shown to each user once, it would be better not to show this popup at all when local storage is not available.

I'm not sure if it is possible to determine easily whether local storage is available.  I think there may be browsers which silently discard local storage writes rather than explicitly saying it's not available.  Until we know the answer to this question, I suggest that the new popup should be disabled :-(.

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Fixes https://github.com/rust-lang/rust/issues/79960

It's a very funny corner case:

In HTML, when a button follows an input (in a `form`), if the enter keep is pressed on the input, instead of sending the submit event to the input, it'll create a click event on the button following it, which in this case made the help popup show up whenever "enter" was pressed.

cc @camelid 

r? @jyn514

### CODE REVIEW

File: src/librustdoc/html/layout.rs [hunk 1]
```diff
@@ -98,7 +98,7 @@ crate fn render<T: Print, S: Print>(
                            placeholder=\"Click or press ‘S’ to search, ‘?’ for more options…\" \
                            type=\"search\">\
                 </div>\
-                <button class=\"help-button\">?</button>
+                <a href=\"javascript:;\" class=\"help-button\">?</a>
```
Comment (camelid) [inline src/librustdoc/html/layout.rs:101]: Why not use `#`?

```suggestion
                <a href=\"#\" class=\"help-button\">?</a>
```

Comment (GuillaumeGomez) [reply src/librustdoc/html/layout.rs:101]: Because it updates the URL, which we don't want.

Comment (camelid) [reply src/librustdoc/html/layout.rs:101]: Ok, wasn't sure :)

Comment (GuillaumeGomez) [reply src/librustdoc/html/layout.rs:101]: You did well asking, like that if someone else comes across this PR and wonders about the same thing, there is an answer! :smile:

Comment (camelid) [inline src/librustdoc/html/layout.rs:101]: I just experimented a bit and you can keep the button. All you need to do is add `type="button"` and it works:

```suggestion
                <button type="button" class=\"help-button\">?</button>
```

Comment (camelid) [reply src/librustdoc/html/layout.rs:101]: > In HTML, when a button follows an input, if the enter keep is pressed on the input, instead of sending the submit event to the input, it'll create a click event on the button following it

I don't think that is what's happening here. Based on experimentation, reading the output of rustdoc, and looking at MDN it seems that this is the issue:

1. The button is inside a `<form>`:

   ```html
   <form class="search-form">
     <div class="search-container">
       <div>
         <select id="crate-search">
           <option value="All crates">
             All crates
           </option>
         </select><input class="search-input" name="search"
         autocomplete="off" spellcheck="false" placeholder=
         "Click or press &acirc;&euro;&tilde;S&acirc;&euro;&trade; to search, &acirc;&euro;&tilde;?&acirc;&euro;&trade; for more options&acirc;&euro;&brvbar;"
         type="search">
       </div><button class="help-button">?</button> <a id=
       "settings-menu" href="../settings.html" name=
       "settings-menu"><img src="../wheel.svg" alt="Change settings"
       width="18"></a>
     </div>
   </form>
   ```

2. [According to MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button#Attributes), the default button behavior will be `submit` if the button is inside a `<form>` and `type` is not specified:

   > `submit`: The button submits the form data to the server. This is the default if the attribute is not specified for buttons associated with a `<form>`, or if the attribute is an empty or invalid value.

So just adding `type="button"` solves the problem.

Comment (GuillaumeGomez) [reply src/librustdoc/html/layout.rs:101]: Yes it was one of the two solutions I came across. I just feel "less good" about this one. No strong feeling though, it just felt a "more obvious" to instead switch to a fake link.

Comment (camelid) [reply src/librustdoc/html/layout.rs:101]: Hmm, I think a *fake* link is worse ;)

Comment (camelid) [reply src/librustdoc/html/layout.rs:101]: Based on the thumbs-ups I've been getting, I think Joshua agrees with me.

Since you don't have strong feelings, and we both prefer the button, how about we go with the button? (I think it's likely more accessible to have a button too because it's more 'semantically-correct'.)

Comment (jyn514) [reply src/librustdoc/html/layout.rs:101]: Yes, I agree :laughing:

Comment (GuillaumeGomez) [reply src/librustdoc/html/layout.rs:101]: Then let's go for a button. :)

**Comment by GuillaumeGomez** [comment]
Switched back to button!

**Comment by jyn514** [comment]
r=me with CI passing

**Comment by jyn514** [comment]
Oh wait, there are no tests for the frontend :(

@bors r+ rollup

**Comment by GuillaumeGomez** [comment]
Not yet you mean! :p
