### PR TITLE
rustdoc: Add option to persist doc test executables

### LINKED ISSUE #37048: Option to generate and persist a test executable for documentation tests
I couldn't find an existing issue for this so I thought I would bring it up. Pardon me if this is a duplicate or in the wrong repository.

I wrote an [in depth guide about Rust code coverage](http://sunjay.ca/2016/07/25/rust-code-coverage) a few months ago based on the older guide that had been around for a while. One of the things I wrote about was that you can't currently get code coverage for documentation tests because `cargo test` or `cargo test --doc` doesn't output any test executable for documentation tests. The tool being used to generate coverage data, kcov, requires an executable that directly runs the code you want to measure.

It would be really helpful if there was a way not to just temporarily generate an executable for documentation tests, but also to have the option to store that executable somewhere (much like how the unit test executable is generated and stored in `target/debug`). That way we can manually run it using whatever tools we please.

I'm really surprised that I couldn't find an existing issue for this. There is a [StackOverflow question](http://stackoverflow.com/a/35669152/551904) about the issue but it doesn't lead anywhere. Hopefully this is a duplicate and it's been on your radar for some time.

### PR DESCRIPTION
**Pull request by repnop**
Fixes #37048.

This is the initial version of the code so the doctest executables can be used for stuff like code coverage (specifically https://github.com/xd009642/tarpaulin/issues/13) the folders it goes into were just a first idea, so any better ones are welcome.

Right now it creates a directory structure like:
```
  given_path/
          |_____ <filename>_rs_<linenum>/
          |_____ ...
          |_____ <filename>_rs_<linenum>/
                 |_____ rust_out

```
I couldn't figure out where it actually outputs the file w/ the name, I suspect its somewhere deeper in the compiler.

It also adds the unstable `--persist-doctests` flag to `rustdoc` that enables this behavior.

### CODE REVIEW

**Comment by rep-nop** [comment]
My local tidy isn't working correctly, it keeps spitting out stuff in jemalloc, any idea why that would be? :thinking:

**Comment by rep-nop** [comment]
Hm, I didn't noticed that somehow the `jemalloc` submodule got pulled in. Should I remove that?

**Comment by Dylan-DPC** [comment]
Pinging from triage, looking for a reviewer from @rust-lang/docs

**Comment by GuillaumeGomez** [comment]
This looks nice and I think it's good to go. However, since it touches rustdoc options and @QuietMisdreavus reworked it recently, I'll let them review this PR.

File: src/librustdoc/test.rs [hunk 1]
```diff
@@ -251,6 +253,42 @@ fn run_test(test: &str, cratename: &str, filename: &FileName, line: usize,
...
+                DirState::Perm(p) => p.as_path(),
+            }
+        }
+    }
+
+    let target_path = if persist_executable {
+        let mut target_path: PathBuf = env::var("OUT_DIR")
+                .expect("Rustdoc must be run with Cargo to persist doctest executables.").into();
+
+        while !target_path.ends_with("target") {
```
Comment (ehuss) [inline src/librustdoc/test.rs]: This doesn't seem safe.  The target directory is not necessarily named "target".  Also, cargo has a bit of an expectation of managing the directory layout.  Normally tools use something like `-o` to control their output.

File: src/librustdoc/test.rs [hunk 2]
```diff
@@ -251,6 +253,42 @@ fn run_test(test: &str, cratename: &str, filename: &FileName, line: usize,
...
+        fn path(&self) -> &std::path::Path {
+            match self {
+                DirState::Temp(t) => t.path(),
+                DirState::Perm(p) => p.as_path(),
+            }
+        }
+    }
+
+    let target_path = if persist_executable {
+        let mut target_path: PathBuf = env::var("OUT_DIR")
```
Comment (ehuss) [inline src/librustdoc/test.rs]: OUT_DIR is only set for build scripts.  How is this supposed to be used?

File: src/librustdoc/test.rs [hunk 3]
```diff
@@ -346,6 +391,17 @@ fn run_test(test: &str, cratename: &str, filename: &FileName, line: usize,
     };
     cmd.env(var, &newpath);
 
+    if persist_executable {
+        let mut target_path = target_path.unwrap();
+        target_path.push("path.txt");
+
+        std::fs::write(
+            target_path,
+            newpath.as_os_str().to_str().unwrap().as_bytes(),
```
Comment (QuietMisdreavus) [inline src/librustdoc/test.rs]: This seems a little awkward, because it's not always the same environment variable that's being set here. A better option would be to make this an environment file, and make the file output be the string "`{var}={newpath}`", to at least show that this should be setting something other than `PATH` ([on non-Windows platforms, at least](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_metadata/dynamic_lib/struct.DynamicLibrary.html#method.envvar)). (With these file contents, i'd probably also name it something like `test.env`, to make it more obvious what it's there for.)

One situation where this breaks down is if the doctests are being built for a different target than the host. It looks like the chosen environment variable will always be stuck to what the *host* expects, but if you're expecting to run the doctests on another target (say, some embedded platform), then that may be different. However, in this situation it's also possible that the dylib path extension may not be necessary. Still, i think the above suggestion should be good enough.

File: src/librustdoc/lib.rs [hunk 4]
```diff
@@ -338,6 +338,11 @@ fn opts() -> Vec<RustcOptGroup> {
                        "enable-index-page",
                        "To enable generation of the index page")
         }),
+        unstable("persist-executable", |o| {
```
Comment (QuietMisdreavus) [inline src/librustdoc/lib.rs]: Bikeshed alert: I feel like `--persist-doctests` is a better name, since the `executable` here feels a little ambiguous if there's a binary crate somewhere in the user's mind that could get confused with this.

**Review by QuietMisdreavus — COMMENTED** [review]
Thanks so much for this! Improvements like this are something i've wanted to work on for doctests, or at least see happen, so it's exciting to see! I've left a few suggestions, to make the feature fit better with the way rustdoc works in general, and one or two personal style preferences.

File: src/librustdoc/lib.rs (hunk 4 above)
Comment (rep-nop) [reply src/librustdoc/lib.rs]: Haha, no idea how I missed that. Definitely agree with you there.

File: src/librustdoc/test.rs (hunk 3 above)
Comment (rep-nop) [reply src/librustdoc/test.rs]: Huh, I never considered taking in the path, sounds like a much better idea! 👌

File: src/librustdoc/test.rs [hunk 5]
```diff
@@ -346,6 +391,17 @@ fn run_test(test: &str, cratename: &str, filename: &FileName, line: usize,
     };
     cmd.env(var, &newpath);
 
+    if persist_executable {
+        let mut target_path = target_path.unwrap();
```
[the remark this answers is not in the document]
Comment (rep-nop) [reply src/librustdoc/test.rs]: The reason I didn't was because it needs cloned, but that's solvable with `if let` too and I like that better also.

File: src/librustdoc/test.rs [hunk 6]
```diff
@@ -251,6 +253,42 @@ fn run_test(test: &str, cratename: &str, filename: &FileName, line: usize,
...
+            match self {
+                DirState::Temp(t) => t.path(),
+                DirState::Perm(p) => p.as_path(),
+            }
+        }
+    }
+
+    let target_path = if persist_executable {
+        let mut target_path: PathBuf = env::var("OUT_DIR")
+                .expect("Rustdoc must be run with Cargo to persist doctest executables.").into();
```
[the remark this answers is not in the document]
Comment (rep-nop) [reply src/librustdoc/test.rs]: Huh, I never considered taking in the path, sounds like a much better idea! 👌

File: src/librustdoc/test.rs (hunk 3 above)
Comment (rep-nop) [reply src/librustdoc/test.rs]: Ah, okay, yeah fair enough :)

File: src/librustdoc/test.rs (hunk 2 above)
Comment (rep-nop) [reply src/librustdoc/test.rs]: Is it? I don't believe the project I tested it on had one, but I could be remembering wrong. Regardless, I'll be taking @QuietMisdreavus's advice and taking a path in the cmd args :)

**Comment by rep-nop** [comment]
Thanks for the comments @ehuss and @QuietMisdreavus! I'll get the changes in soon:tm: (maybe even tonight or tomorrow night!)

File: src/librustdoc/test.rs (hunk 3 above)
Comment (ollie27) [reply src/librustdoc/test.rs]: I'm pretty sure we don't need any of this `newpath` stuff now that we're not compiling doctests with `prefer-dynamic` since #54939. I don't think we need a `path.txt` or `test.env` file at all.

Comment (frewsxcv) [inline src/librustdoc/test.rs]: `Path` has a `to_str` method, you souldn't need to go through `OsStr`

https://doc.rust-lang.org/nightly/std/path/struct.Path.html#method.to_str

Comment (rep-nop) [reply src/librustdoc/test.rs]: `newpath` is an `OsString`

Comment (frewsxcv) [reply src/librustdoc/test.rs]: Ah, well `OsString` coerces to an `OsStr`, so you should be able to call `to_str()` directly on the `OsString`, but not a big deal

Comment (ollie27) [reply src/librustdoc/test.rs]: I'm guessing you may have been using a version of rustdoc that didn't have #54939 applied yet. It'll be a good idea to rebase this PR and try again. Anyway I've submitted  #56514 to see if anything breaks.

**Comment by rep-nop** [comment]
@QuietMisdreavus unless you or anyone else has final thoughts on where its outputting the test files, looks like we're good to go whenever :+1:

**Comment by QuietMisdreavus** [comment]
> @QuietMisdreavus unless you or anyone else has final thoughts on where its outputting the test files, looks like we're good to go whenever :+1:

One option is to use something like the `generate_name` function that we use to name the test itself for libtest. This also tracks things like headings in markdown to make the test easier to locate:

https://github.com/rust-lang/rust/blob/e3b7222324f22d5f2f9fcf364d653fa7ed71bac7/src/librustdoc/test.rs#L634-L636

You could make another function like this (to make something that was easier to use as a directory name) and hand that to `run_test` to use as the folder name.

File: src/librustdoc/lib.rs [hunk 7]
```diff
@@ -338,6 +338,12 @@ fn opts() -> Vec<RustcOptGroup> {
                        "enable-index-page",
                        "To enable generation of the index page")
         }),
+        unstable("persist-doctests", |o| {
+             o.optopt("",
+                       "persist-doctests",
+                       "Persists the rustdoc test executables",
```
Comment (QuietMisdreavus) [inline src/librustdoc/lib.rs]:
```suggestion
                       "Directory to persist doctest executables into",
```

Makes it obvious what the path is for.

File: src/librustdoc/test.rs [hunk 8]
```diff
@@ -274,7 +290,25 @@ fn run_test(test: &str, cratename: &str, filename: &FileName, line: usize,
...
         let outdir = Mutex::new(
-            TempFileBuilder::new().prefix("rustdoctest").tempdir().expect("rustdoc needs a tempdir")
+            if let Some(mut path) = persist_doctests {
+                path.push(format!("{}_{}",
+                    filename
+                        .to_string()
+                        .rsplit('/')
+                        .next()
+                        .unwrap()
+                        .replace(".", "_"), line)
```
Comment (QuietMisdreavus) [inline src/librustdoc/test.rs]: The `, line` hanging on the end of this call looks awkward. Can you break it onto its own line?

**Review by QuietMisdreavus — COMMENTED** [review]
Just a couple comments, but otherwise this looks good to me!

**Comment by cramertj** [comment]
> Does anyone have any other suggestions for where to put the doctest executables themselves? The filename_rs_<line> seems to work but feels somewhat hacky.

Would it be possible to combine the doctests into a single binary? That'd make it much easier (slash possible) for external tools and build systems to consume the resulting files, since they could be pulled in via a single pre-determined name.

**Comment by rep-nop** [comment]
@cramertj that was my original hope, but I'm not experienced enough with the code base to actually implement that behavior without some additional guidance. After speaking with @QuietMisdreavus it seems that change would probably be quite large in scope -- certainly warranting its own PR I'd imagine. The question then I suppose is that do we consider that possible change in behavior down the line breaking? I would think not myself, but would like to hear input from others about that as well.

**Comment by QuietMisdreavus** [comment]
@cramertj Sadly, i think that's out of scope for this PR. The current model of rustdoc is to compile everything separately as its own standalone binary, so mirroring the compiler's model for unit tests (where the unit test functions are rolled together and there's a libtest entry point that calls them all) would need a bit of an overhaul to make sure that everything can still work.

**Comment by rep-nop** [comment]
whelp, something went horribly wrong there.

File: src/librustdoc/config.rs [hunk 9]
```diff
@@ -78,6 +78,8 @@ pub struct Options {
     pub should_test: bool,
     /// List of arguments to pass to the test harness, if running tests.
     pub test_args: Vec<String>,
+    /// Otional path to persist the doctest executables to.
```
Comment (QuietMisdreavus) [inline src/librustdoc/config.rs]: Typo on "Otional". I'd also want to add something like "If not set, uses a temporary directory."

**Review by QuietMisdreavus — COMMENTED** [review]
Looks like you accidentally re-added the `dlmalloc`, `libcompiler_builtins`, and `liblibc` submodules? They're gone on master.

File: src/librustdoc/config.rs (hunk 9 above)
Comment (rep-nop) [reply src/librustdoc/config.rs]: Ah shoot, I thought I checked for those submodules before committing, I'll try to get that stuff fixed tonight.

**Comment by cramertj** [comment]
@QuietMisdreavus 
> Sadly, i think that's out of scope for this PR.

Seems fine to me to hold off for a later PR, and since the flag is unstable we can change the behavior later. Is there a tracking issue for the unstable flag that I could note this on as a blocker to make sure we don't accidentally stabilize without addressing this?

**Comment by QuietMisdreavus** [comment]
Since this PR introduces the flag in the first place, i don't there there is a tracking issue for it, unless @rep-nop has made one already.

**Comment by rep-nop** [comment]
I have not, though I can create one if desired

**Comment by QuietMisdreavus** [comment]
I've opened https://github.com/rust-lang/rust/issues/56925 to track this feature and added some items for future work.

**Comment by rep-nop** [comment]
Awesome, thanks 👍

**Comment by QuietMisdreavus** [comment]
While we're checking boxes, can you add a little blurb to the Rustdoc Book about the flag? It's all in `src/doc/rustdoc`, there's a chapter for unstable features that it can go into.

**Comment by rep-nop** [comment]
Sure thing, I'll get to that when I have a chance this week

File: src/doc/rustdoc/src/unstable-features.md [hunk 10]
```diff
@@ -417,3 +417,7 @@ JavaScript, and font files in a single location, rather than duplicating it once
 (grouping of crate docs generated into the same output directory, like with `cargo doc`). Per-crate
 files like the search index will still load from the documentation root, but anything that gets
 renamed with `--resource-suffix` will load from the given path.
+
+### `--persist-doctests`: persist doctest executables after running
+
+This feature allows the persistence of the doctest executables to the specified path.
```
Comment (QuietMisdreavus) [inline src/doc/rustdoc/src/unstable-features.md]: Doc suggestion:

``````markdown
Using this flag looks like this:

```bash
$ rustdoc src/lib.rs --test -Z unstable-options --persist-doctests target/rustdoctest
```

This flag allows you to keep doctest executables around after they're compiled or run.
Usually, rustdoc will immediately discard a compiled doctest after it's been tested, but
with this option, you can keep those binaries around for farther testing.
``````

**Review by QuietMisdreavus — COMMENTED** [review]
Looks like the `libbacktrace` submodule got accidentally re-added?

**Review by QuietMisdreavus — APPROVED** [review]
Looks good! There's already some discussion on what we can build on top of this, so let's get this in! r=me when travis is green.

**Comment by QuietMisdreavus** [comment]
We *seriously* need to find a way to strip that panic message (and the line numbers) from the doctest failure output. It's causing a lot of problems.

@bors r+

**Comment by sunjay** [comment]
This is so awesome! Thank you for working on this feature! It's something people have been looking forward to for a while. :smile: 

This has really great implications for code coverage. I helped get Codecov.io to start supporting Rust and soon we will be able to remove the big note at the top of the [example-rust](https://github.com/codecov/example-rust) repo that says that doctests can't be used for coverage. :tada:

**Comment by rep-nop** [comment]
Yep! I'm friends with the author of https://github.com/xd009642/tarpaulin and this is one of the issues he had opened on his repo, so decided to take a stab at it to help him out 👍 There's some more plans in works for better doctest ergonomics now that this is merged so things should get even better in the future :D
