### PR TITLE
Normalize projections appearing in `impl Trait`

### LINKED ISSUE #60414: Using associated types in async fn type break typing
With the following code:
```rust
trait Trait {
    type Assoc;
}

async fn foo<T: Trait<Assoc = ()>>() -> T::Assoc {
    ()
}
```

comes the following error:
```
error[E0271]: type mismatch resolving `<impl std::future::Future as std::future::Future>::Output == <T as Trait>::Assoc`
 --> src/lib.rs:7:41
  |
7 | async fn foo<T: Trait<Assoc = ()>>() -> T::Assoc {
  |                                         ^^^^^^^^ expected (), found associated type
  |
  = note: expected type `()`
             found type `<T as Trait>::Assoc`
  = note: the return type of a function must have a statically known size

error: aborting due to previous error
```
[(playground link)](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=06fb8c16665b724d4ed97e9b99e856ad)

However, this function compiles correctly without the `async` keyword.

### PR DESCRIPTION
**Pull request by jonas-schievink**
Fixes #60414

This does not try to do the same for `existential type`s (which have the same bug), since that always seems to lead to cycle errors.

### CODE REVIEW

File: src/test/ui/impl-trait/bound-normalization.rs [hunk 1]
```diff
@@ -0,0 +1,102 @@
+// compile-fail
```
Comment (Centril) [inline src/test/ui/impl-trait/bound-normalization.rs]: Please split this test up into several files (at least in terms of OK/ERROR) and move at least the `async-await` part to `src/test/ui/async-await`.

File: src/test/ui/impl-trait/bound-normalization.rs [hunk 2]
```diff
@@ -0,0 +1,102 @@
...
+
+#![feature(async_await)]
+#![feature(existential_type)]
+#![feature(impl_trait_in_bindings)]
+//~^ WARNING the feature `impl_trait_in_bindings` is incomplete
+
+// See issue 60414
+
+/////////////////////////////////////////////
+// Original report
```
Comment (Centril) [inline src/test/ui/impl-trait/bound-normalization.rs]: E.g. because this section seems to be `// check-pass` and not `// compile-fail`.

File: src/librustc_typeck/collect.rs [hunk 3]
```diff
@@ -1978,10 +1980,19 @@ fn explicit_predicates_of<'tcx>(
...
+                        // An `impl Trait` type
+                        let bounds_predicates = tcx.infer_ctxt().enter(|infcx| {
+                            fully_normalize(
+                                &infcx,
+                                FulfillmentContext::new(),
+                                ObligationCause::dummy(),
+                                tcx.param_env(def_id),
+                                &bounds_predicates,
+                            ).expect("failed to normalize opaque type bounds")
+                        });
```
Comment (nikomatsakis) [inline src/librustc_typeck/collect.rs]: Hmm, I don't think this is the right place to do normalization.

Comment (nikomatsakis) [reply src/librustc_typeck/collect.rs]: In particular, the result of `explicit_predicates_of` is unnormalized; we normally do normalization after substitution has been performed.

Comment (nikomatsakis) [reply src/librustc_typeck/collect.rs]: The question then is where is the *right* place

**Review by nikomatsakis — CHANGES_REQUESTED** [review]

File: src/librustc_typeck/collect.rs (hunk 3 above)
Comment (jonas-schievink) [reply src/librustc_typeck/collect.rs]: I initially tried doing this somewhere in `rustc_typeck::check::check_fn`, but that only lead to ICEs later on (during MIR type checking I believe). If that's a better place I can do that again and try fixing the ICEs.

Comment (nikomatsakis) [reply src/librustc_typeck/collect.rs]: It might be -- perhaps push that version so I can see exactly where you mean?

Comment (nikomatsakis) [reply src/librustc_typeck/collect.rs]: See [my comment here](https://github.com/rust-lang/rust/issues/60414#issuecomment-508044135) =)

File: src/test/ui/impl-trait/bound-normalization-pass.rs [hunk 4]
```diff
@@ -0,0 +1,77 @@
+// compile-pass
```
Comment (JohnTitor) [inline src/test/ui/impl-trait/bound-normalization-pass.rs]: FYI the `compile-pass` annotation will be removed so we should use `run-pass` or something else.

Comment (Centril) [reply src/test/ui/impl-trait/bound-normalization-pass.rs]: It should probably be `// check-pass`.

**Comment by jonas-schievink** [comment]
So this now fails the test with lifetimes:

```
error[E0308]: mismatched types
  --> /home/jonas/dev/rust/src/test/ui/impl-trait/bound-normalization-pass.rs:46:56
   |
LL |     fn foo2_pass<'a, T: Trait<'a, Assoc=()> + 'a>() -> impl FooLike<Output=T::Assoc> + 'a {
   |                                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ lifetime mismatch
   |
   = note: expected type `lifetimes::Trait<'a>`
              found type `lifetimes::Trait<'static>`
note: the lifetime 'a as defined on the function body at 46:18...
  --> /home/jonas/dev/rust/src/test/ui/impl-trait/bound-normalization-pass.rs:46:18
   |
LL |     fn foo2_pass<'a, T: Trait<'a, Assoc=()> + 'a>() -> impl FooLike<Output=T::Assoc> + 'a {
   |                  ^^
   = note: ...does not necessarily outlive the static lifetime
```

Not sure whether this would be fixed by @nikomatsakis' first suggestion in https://github.com/rust-lang/rust/issues/60414#issuecomment-508044135...

File: src/test/ui/impl-trait/bound-normalization-fail.rs [hunk 5]
```diff
@@ -0,0 +1,53 @@
...
+
+mod lifetimes {
+    use super::*;
+
+    trait Trait<'a> {
+        type Assoc;
+    }
+
+    /// Missing bound constraining `Assoc`, `T::Assoc` can't be normalized further.
+    fn foo2_fail<'a, T: Trait<'a>>() -> impl FooLike<Output=T::Assoc> {
```
Comment (nikomatsakis) [inline src/test/ui/impl-trait/bound-normalization-fail.rs]: I think that this is similar to or the same as https://github.com/rust-lang/rust/issues/53613 -- i.e., if you write this as `<T as Trait<'a>>::Assoc`, does it work?

**Comment by nikomatsakis** [comment]
Hmm, I'm not able to build the compiler at all with these changes. (I have a local clone.) I'm trying a build now from HEAD^ to see which commit causes the problems.

**Comment by nikomatsakis** [comment]
OK, building from HEAD^ works. I'm going to take a look at that failing test, but my hunch is that we should cut if from the PR and leave it for "future work" :P

**Comment by nikomatsakis** [comment]
Applying this diff does indeed make the test pass:

```diff
modified   src/test/ui/impl-trait/bound-normalization-pass.rs
@@ -43,12 +43,14 @@ mod lifetimes {
     }

     /// Like above.
-    fn foo2_pass<'a, T: Trait<'a, Assoc=()> + 'a>() -> impl FooLike<Output=T::Assoc> + 'a {
+    fn foo2_pass<'a, T: Trait<'a, Assoc=()> + 'a>(
+    ) -> impl FooLike<Output=<T as Trait<'a>>::Assoc> + 'a {
         Foo(())
     }

     /// Normalization to type containing bound region.
-    fn foo2_pass2<'a, T: Trait<'a, Assoc=&'a ()> + 'a>() -> impl FooLike<Output=T::Assoc> + 'a {
+    fn foo2_pass2<'a, T: Trait<'a, Assoc=&'a ()> + 'a>(
+    ) -> impl FooLike<Output=<T as Trait<'a>>::Assoc> + 'a {
         Foo(&())
     }
 }
```

Still, I'm not entirely sure *why* that is needed, given the `+ 'a` that appears.

**Comment by nikomatsakis** [comment]
OK, I think I know the cause. It is indeed pretty unrelated to this PR and is basically just a bug in the way we are handling the impl trait desugaring. It arises from the hack where we use `'static` as the value for our parent's lifetime parameters, so that the `T: Trait<'a>` constraint in scope becomes `T: Trait<'static>`.

**Comment by nikomatsakis** [comment]
Ah dang it this is all explained in #51525 =)

**Comment by nikomatsakis** [comment]
@jonas-schievink forgive me, but I force pushed to your branch -- I think this PR though is ready to land now.

**Comment by jonas-schievink** [comment]
Okay, go ahead! I didn't have Internet since friday so couldn't do any work on this unfortunately.

**Comment by kpp** [comment]
Now this signature is allowed:

```
pub fn flatten_stream<Fut, St>(future: Fut) -> impl Stream<Item = Fut::Output>
    where Fut: Future<Output = St>,
          St: Stream<Item = Fut::Output>,
{
```

(https://github.com/kpp/futures-async-combinators/commit/06702ec781f921d4c7a207b0602a8413756076f3#diff-7afe74b649f99a176a8b54176b0859a8R105)

Whereas is was impossible in the previous releases.

**Comment by jonas-schievink** [comment]
@kpp On first glance, that looks like an expected outcome of this. Where do you see the bug?

This equivalent example fails to compile due to ICEs on stable and beta, which this PR fixes:

```rust
pub trait Stream {
    type Item;
}

pub trait Future {
    type Output;
}

struct MyStream<T> {
    v: Vec<T>,
}

impl<T> Stream for MyStream<T> {
    type Item = T;
}

pub fn flatten_stream<Fut, St>(future: Fut) -> impl Stream<Item = Fut::Output>
    where Fut: Future<Output = St>,
          St: Stream<Item = Fut::Output>,
{
    MyStream {
        v: Vec::new(),
    }
}
```

```
internal compiler error: broken MIR in DefId(0:22 ~ playground[abf7]::flatten_stream[0]) (Terminator { source_info: SourceInfo { span: src/lib.rs:22:12: 22:22, scope: scope[0] }, kind: _2 = const std::vec::Vec::<T>::new() -> [return: bb2, unwind: bb3] }): call dest mismatch (std::vec::Vec<<Fut as Future>::Output> <- std::vec::Vec<St>): NoSolution
```

In particular: `call dest mismatch (std::vec::Vec<<Fut as Future>::Output> <- std::vec::Vec<St>): NoSolution`. The added normalization fixes this mismatch.

**Comment by kpp** [comment]
> Where do you see the bug?

I got the following error on nightly-2019-07-06 with the signature above:

```
error[E0271]: type mismatch resolving `<impl core::future::future::Future as core::future::future::Future>::Output == std::option::Option<(<Fut as core::future::future::Future>::Output, (std::option::Option<Fut>, std::option::Option<std::pin::Pin<std::boxed::Box<St>>>))>`
  --> src/future.rs:99:48
   |
99 | pub fn flatten_stream<Fut, St>(future: Fut) -> impl Stream<Item = Fut::Output>
   |                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected type parameter, found associated type
   |
   = note: expected type `std::option::Option<(St, (std::option::Option<Fut>, std::option::Option<std::pin::Pin<std::boxed::Box<St>>>))>`
              found type `std::option::Option<(<Fut as core::future::future::Future>::Output, (std::option::Option<Fut>, std::option::Option<std::pin::Pin<std::boxed::Box<St>>>))>`
   = note: required because of the requirements on the impl of `futures_core::stream::Stream` for `futures_util::stream::unfold::Unfold<(std::option::Option<Fut>, std::option::Option<std::pin::Pin<std::boxed::Box<St>>>), [closure@src/future.rs:104:51: 118:6], impl core::future::future::Future>`
   = note: the return type of a function must have a statically known size

error: aborting due to previous error
```

**Comment by jonas-schievink** [comment]
That does look expected to me.

In the type mismatch error here you can see that the `<Fut as core::future::future::Future>::Output` did not get normalized to `St` properly, but now does ("expected" vs. "found" is swapped around here, that's another old bug with `impl Trait`).
```
   = note: expected type `std::option::Option<(St, (std::option::Option<Fut>, std::option::Option<std::pin::Pin<std::boxed::Box<St>>>))>`
              found type `std::option::Option<(<Fut as core::future::future::Future>::Output, (std::option::Option<Fut>, std::option::Option<std::pin::Pin<std::boxed::Box<St>>>))>`
```
