### PR TITLE
rustdoc: Fix invalid suggestions on ambiguous intra doc links v2

### LINKED ISSUE #108653: [rustdoc] Misleading error message for ambiguous link to associated type/const
### Code

```Rust
/// [`Trait::IDENT`]
trait Trait {
    type IDENT;
    const IDENT: usize;
}
```

### Current output

```Shell
warning: `Trait::IDENT` is both a trait and a trait
 --> src/main.rs:1:7
  |
1 | /// [`Trait::IDENT`]
  |       ^^^^^^^^^^^^ ambiguous link
  |
  = note: `#[warn(rustdoc::broken_intra_doc_links)]` on by default
help: to link to the trait, prefix with `trait@`
  |
1 | /// [`trait@Trait::IDENT`]
  |       ++++++
help: to link to the trait, prefix with `trait@`
  |
1 | /// [`trait@Trait::IDENT`]
  |       ++++++

warning: `doc_` (bin "doc_" doc) generated 1 warning
```

### Desired output

```Shell
warning: `Trait::IDENT` is both a const and a type
 --> src/main.rs:1:7
  |
1 | /// [`Trait::IDENT`]
  |       ^^^^^^^^^^^^ ambiguous link
  |
  = note: `#[warn(rustdoc::broken_intra_doc_links)]` on by default
help: to link to the const, prefix with `const@`
  |
1 | /// [`const@Trait::IDENT`]
  |       ++++++
help: to link to the type, prefix with `type@`
  |
1 | /// [`type@Trait::IDENT`]
  |       ++++++

warning: `doc_` (bin "doc_" doc) generated 1 warning
```

### Rationale and extra context

_No response_

### Other cases

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Fixes https://github.com/rust-lang/rust/issues/108653.

This is another approach to fixing the same issue. This time, we keep the computed information around instead of re-computing it.

Strangely enough, the order for ambiguities seem to have been changed. Not an issue but it creates a lot of diff...

So which version do you prefer?

r? @notriddle

### CODE REVIEW

**Comment by jyn514** [comment]
this seems better than before. you should probably get someone from t-compiler to review the change to `AssocItems`.

**Comment by GuillaumeGomez** [comment]
Let's ask to @oli-obk then if they think it looks ok.

File: src/librustdoc/passes/collect_intra_doc_links.rs [hunk 1]
```diff
@@ -768,15 +797,15 @@ fn trait_impls_for<'a>(
...
-        *ns,
-        PerNS {
-            type_ns: Ok((Res::Def(DefKind::Trait, _), _)),
-            macro_ns: Ok((Res::Def(DefKind::Macro(MacroKind::Derive), _), _)),
-            ..
-        }
-    )
+fn is_derive_trait_collision<T>(ns: &PerNS<Result<Vec<(Res, T)>, ResolutionFailure<'_>>>) -> bool {
+    if let (&Ok(ref type_ns), &Ok(ref macro_ns)) = (&ns.type_ns, &ns.macro_ns) {
+        type_ns.iter().any(|(res, _)| matches!(res, Res::Def(DefKind::Trait, _)))
```
[the remark this answers is not in the document]
Comment (GuillaumeGomez) [reply src/librustdoc/passes/collect_intra_doc_links.rs:802]: I think it's not an issue since we only want to check if there is a derive macro and a trait. In one case, we run this check if we have two elements which then allow to only return the types, and in the other case, we remove the macros from the candidates being returned.

File: compiler/rustc_middle/src/ty/assoc.rs [hunk 2]
```diff
@@ -185,16 +185,16 @@ impl AssocItems {
         kinds.iter().find_map(|kind| self.find_by_name_and_kind(tcx, ident, *kind, parent_def_id))
     }
 
-    /// Returns the associated item with the given name in the given `Namespace`, if one exists.
-    pub fn find_by_name_and_namespace(
-        &self,
-        tcx: TyCtxt<'_>,
+    /// Returns the associated items with the given name in the given `Namespace`.
```
Comment (oli-obk) [inline compiler/rustc_middle/src/ty/assoc.rs:188]: Please document under what circumstances this can return more than one element

**Review by oli-obk — CHANGES_REQUESTED** [review]
None of

* this PR
* the issue
* the other PR

explain what the problem on the impl side is and what is being changed. Please add some information to the main post of this PR.

If regular rustc will never encounter `filter_by_name_and_namespace` that return more than one element, it should stay as it is and you could make the filtering function a free function inside rustdoc.

**Comment by GuillaumeGomez** [comment]
@oli-obk Thanks to your comment, I realized the change in the compiler was unnecessary and thus completely removed it (and the commit as well).

The other thing I changed in the new added commit is in case we have multiple candidates with the same "kind". In such case, it's not possible to disambiguate so the function doesn't emit a warning and we handle the candidates as if we only had one. It seems to be what we had before this PR so I brought back this behaviour.

**Review by notriddle — APPROVED** [review]

File: src/librustdoc/passes/collect_intra_doc_links.rs [hunk 3]
```diff
@@ -48,7 +48,19 @@ fn collect_intra_doc_links(krate: Crate, cx: &mut DocContext<'_>) -> Crate {
...
 }
 
-#[derive(Copy, Clone, Debug, Hash)]
+fn filter_assoc_items_by_name_and_namespace<'a>(
+    tcx: TyCtxt<'a>,
+    assoc_items_of: DefId,
+    ident: Ident,
+    ns: Namespace,
+) -> impl Iterator<Item = &ty::AssocItem> + 'a {
+    let parent_def_id = assoc_items_of;
```
[the remark this answers is not in the document]
Comment (GuillaumeGomez) [reply src/librustdoc/passes/collect_intra_doc_links.rs:57]: No. Removing it.

**Comment by GuillaumeGomez** [comment]
Removed unnecessary variable.

File: tests/rustdoc-ui/intra-doc/issue-108653-associated-items-6.stderr [hunk 4]
```diff
@@ -0,0 +1,22 @@
...
+LL | #![deny(rustdoc::broken_intra_doc_links)]
+   |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
+help: to link to the associated constant, prefix with `const@`
+   |
+LL | /// [`const@u32::MAX`]
+   |       ++++++
+help: to link to the builtin type, prefix with `prim@`
+   |
+LL | /// [`prim@u32::MAX`]
+   |       +++++
```
Comment (jyn514) [inline tests/rustdoc-ui/intra-doc/issue-108653-associated-items-6.stderr:19]: This still doesn't seem right? One of these is a constant in a module, and the other is an associated constant to the `u32` primitive type (I think the error has those backwards as well and thinks the one in the module is an associated constant).

File: tests/rustdoc-ui/intra-doc/issue-108653-associated-items-8.stderr [hunk 5]
```diff
@@ -0,0 +1,22 @@
...
+LL | #![deny(rustdoc::broken_intra_doc_links)]
+   |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
+help: to link to the associated constant, prefix with `const@`
+   |
+LL | /// [`const@u32::MAX`]
+   |       ++++++
+help: to link to the associated type, prefix with `type@`
+   |
+LL | /// [`type@u32::MAX`]
+   |       +++++
```
Comment (jyn514) [inline tests/rustdoc-ui/intra-doc/issue-108653-associated-items-8.stderr:19]: unrelated to this pr, but I wonder if we could include the span of the definition in this suggestion? i.e. point to line 11 here.

File: src/librustdoc/passes/collect_intra_doc_links.rs [hunk 6]
```diff
@@ -324,14 +335,21 @@ impl<'a, 'tcx> LinkCollector<'a, 'tcx> {
         prim_ty: PrimitiveType,
         ns: Namespace,
         item_name: Symbol,
-    ) -> Option<(Res, DefId)> {
+    ) -> Vec<(Res, DefId)> {
```
Comment (jyn514) [inline src/librustdoc/passes/collect_intra_doc_links.rs:338]: Can you return a `PerNS` here instead to enforce at compile time that there's only one result per namespace?

File: src/librustdoc/passes/collect_intra_doc_links.rs [hunk 7]
```diff
@@ -545,24 +572,30 @@ impl<'a, 'tcx> LinkCollector<'a, 'tcx> {
...
         let tcx = self.cx.tcx;
 
         match root_res {
             Res::Primitive(prim) => {
-                self.resolve_primitive_associated_item(prim, ns, item_name).or_else(|| {
+                let items = self.resolve_primitive_associated_item(prim, ns, item_name);
+                if !items.is_empty() {
+                    items
+                } else {
```
Comment (jyn514) [inline src/librustdoc/passes/collect_intra_doc_links.rs:583]:
```suggestion
                // Inherent associated items take precedence over items that come from trait impls.
                if !items.is_empty() {
                    items
                } else {
```

File: src/librustdoc/passes/collect_intra_doc_links.rs [hunk 8]
```diff
@@ -674,27 +717,34 @@ fn resolve_associated_trait_item<'a>(
...
                     .unwrap_or(*trait_assoc)
             })
-    });
+        })
+        .collect::<Vec<_>>();
     // FIXME(#74563): warn about ambiguity
-    debug!("the candidates were {:?}", candidates.clone().collect::<Vec<_>>());
-    candidates.next()
+    debug!("the candidates were {:?}", candidates);
+    candidates
```
Comment (jyn514) [inline src/librustdoc/passes/collect_intra_doc_links.rs:747]: I don't think this behaves as expected when there are multiple traits with the same associated item. Consider:
```rust
//! [usize::Item]

pub trait Foo {
  type Item;
}

pub trait Bar {
  type Item;
}

impl Foo for usize { type Item = u32; }
impl Bar for usize { type Item = i32; }
```
Today that compiles without warning; after your change it gives an ambiguity error. That's *correct*, but we don't have a way to let users disambiguate it today (#74563), so I'm not sure the warning makes sense to emit.

File: src/librustdoc/passes/collect_intra_doc_links.rs [hunk 9]
```diff
@@ -768,15 +818,15 @@ fn trait_impls_for<'a>(
...
-fn is_derive_trait_collision<T>(ns: &PerNS<Result<(Res, T), ResolutionFailure<'_>>>) -> bool {
-    matches!(
-        *ns,
-        PerNS {
-            type_ns: Ok((Res::Def(DefKind::Trait, _), _)),
-            macro_ns: Ok((Res::Def(DefKind::Macro(MacroKind::Derive), _), _)),
-            ..
-        }
-    )
+fn is_derive_trait_collision<T>(ns: &PerNS<Result<Vec<(Res, T)>, ResolutionFailure<'_>>>) -> bool {
```
Comment (jyn514) [inline src/librustdoc/passes/collect_intra_doc_links.rs:821]: This change doesn't make sense to me. Why are we considering multiple items in the same namespace? At that point it's already ambiguous and the result of this function doesn't matter.

File: src/librustdoc/passes/collect_intra_doc_links.rs [hunk 10]
```diff
@@ -1202,7 +1242,27 @@ impl LinkCollector<'_, '_> {
...
+                self.report_rawptr_assoc_feature_gate(diag.dox, &diag.link_range, diag.item);
+                return None;
+            } else {
+                candidates = vec![candidates[0]];
+            }
+        }
+
+        if candidates.len() > 1 && !ambiguity_error(self.cx, &diag, &key.path_str, &candidates) {
+            candidates = vec![candidates[0]];
+        }
```
Comment (jyn514) [inline src/librustdoc/passes/collect_intra_doc_links.rs:1263]: I don't understand what's going on here. Why are you arbitrarily picking a candidate here? This happens too late, you can no longer be sure that all the candidates came from trait selection instead of from somewhere where you need to report the ambiguity.

**Review by jyn514 — CHANGES_REQUESTED** [review]
I don't really understand how this is supposed to work ...

File: src/librustdoc/passes/collect_intra_doc_links.rs (hunk 6 above)
Comment (GuillaumeGomez) [reply src/librustdoc/passes/collect_intra_doc_links.rs:338]: I don't get what you mean by "enforce at compile time". We'd need to construct a `PerNS` by calling `prim_ty.impls(tcx)` which is not a constant method and cannot be one since it makes allocations in `simplified_types`. Did you have something else in mind?

File: src/librustdoc/passes/collect_intra_doc_links.rs (hunk 1 above)
[the remark this answers is not in the document]
Comment (GuillaumeGomez) [reply src/librustdoc/passes/collect_intra_doc_links.rs:823]: It seems the function wasn't needed so I removed it completely.

File: tests/rustdoc-ui/intra-doc/issue-108653-associated-items-6.stderr (hunk 4 above)
Comment (GuillaumeGomez) [reply tests/rustdoc-ui/intra-doc/issue-108653-associated-items-6.stderr:19]: Ah interesting: it considers `MAX` as a primitive from the module and as an associated constant of `u32`. The naming isn't great though...

File: src/librustdoc/passes/collect_intra_doc_links.rs (hunk 10 above)
Comment (GuillaumeGomez) [reply src/librustdoc/passes/collect_intra_doc_links.rs:1263]: It allows to fix the following case (using the code example you provided):

```rust
//! [usize::Item]

pub trait Foo { type Item; }
pub trait Bar { type Item; }

impl Foo for usize { type Item = u32; }
impl Bar for usize { type Item = i32; }
```

Without the deduplication logic present in `ambiguity_error`, it would output:

```
error: `usize::Item` is both an associated type and an associated type
 --> tests/rustdoc-ui/intra-doc/issue-108653-associated-items-9.rs:5:6
  |
5 | //! [usize::Item]
  |      ^^^^^^^^^^^ ambiguous link
  |
note: the lint level is defined here
 --> tests/rustdoc-ui/intra-doc/issue-108653-associated-items-9.rs:3:9
  |
3 | #![deny(warnings)]
  |         ^^^^^^^^
  = note: `#[deny(rustdoc::broken_intra_doc_links)]` implied by `#[deny(warnings)]`
help: to link to the associated type, prefix with `type@`
  |
5 | //! [type@usize::Item]
  |      +++++
help: to link to the associated type, prefix with `type@`
  |
5 | //! [type@usize::Item]
  |      +++++

error: aborting due to previous error
```

I'll add a comment to explain why this is needed.

**Comment by jyn514** [comment]
I don't have time for reviews right now. Happy for @notriddle or @oli-obk to be in charge here.

**Comment by GuillaumeGomez** [comment]
So `is_derive_trait_collision` was actually useful.

File: src/librustdoc/passes/collect_intra_doc_links.rs (hunk 1 above)
[the remark this answers is not in the document]
Comment (GuillaumeGomez) [reply src/librustdoc/passes/collect_intra_doc_links.rs]: No, it was needed:

```
error: `PartialEq` is both a trait and a derive macro
  --> library/core/src/macros/mod.rs:65:71
   |
65 | /// Asserts that two expressions are not equal to each other (using [`PartialEq`]).
   |                                                                       ^^^^^^^^^ ambiguous link
   |
help: to link to the trait, prefix with `trait@`
   |
65 | /// Asserts that two expressions are not equal to each other (using [`trait@PartialEq`]).
   |                                                                       ++++++
help: to link to the derive macro, prefix with `derive@`
   |
65 | /// Asserts that two expressions are not equal to each other (using [`derive@PartialEq`]).
   |                                                                       +++++++
```

I'll add a regression test.

File: tests/rustdoc-ui/intra-doc/issue-108653-associated-items-6.stderr (hunk 4 above)
Comment (GuillaumeGomez) [reply tests/rustdoc-ui/intra-doc/issue-108653-associated-items-6.stderr]: Well I renamed it "primitive type" so that fixes this issue too. 😆

File: src/librustdoc/passes/collect_intra_doc_links.rs (hunk 6 above)
Comment (GuillaumeGomez) [reply src/librustdoc/passes/collect_intra_doc_links.rs:331]: It's only for primitive types. So normally, this method should never return more than one item. It's possible to create duplicates with trait impls on primitive though, hence why I did this change.

**Comment by oli-obk** [comment]
I only looked at filter_assoc_items_by_name_and_namespace and its uses, but those seemed fine to me

**Review by notriddle — APPROVED** [review]
