### PR TITLE
PhantomData: fix documentation wrt interaction with dropck

### LINKED ISSUE #70841: PhantomData<T> no longer dropck?
Consider this code:

```rust
use std::marker::PhantomData;

struct Pending<T> {
    phantom: PhantomData<T>,
}

fn pending<T>(value: T) -> Pending<T> {
    Pending {
        phantom: PhantomData,
    }
}

struct Inspector<'a> {
    value: &'a String,
}

impl Drop for Inspector<'_> {
    fn drop(&mut self) {
        eprintln!("drop inspector {}", self.value)
    }
}

fn main() {
    let p: Pending<Inspector>;
    let s = "hello".to_string();
    p = pending(Inspector { value: &s });
}
```
[Playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=95af90149cab494a9790177dc06dd547)

I believe it should not compile (by failing dropcheck). It, however, compiles and runs on 1.42 and 1.31. On 1.24 it indeed fails as I expect. 

The equivalent code, where `PhantomData<T>` is replaced with `T` rightfully fails to compiles: [Playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=0375b720f73fd4cfb43e06644216e9b7). So, dropchk somehow observes the difference between `T` and `PhantomData<T>`?

Either I misunderstand how `PhantomData<T>` is supposed to work, or this is a stable-to-stable regression and a soundless hole.

### LINKED ISSUE #102810: PhantomData behavior is very surprising w.r.t. lack of Drop implications
I tried this code:

```rust
use core::cell::Cell;
use core::marker::PhantomData as PDOrBox;
//use std::boxed::Box as PDOrBox;
struct Foo<'a> {
  selfref: Cell<Option<&'a Foo<'a>>>,
}
impl<'a> Drop for Foo<'a> {
  fn drop(&mut self) {
  }
}
fn make_selfref<'a>(x: &'a PDOrBox<Foo<'a>>) {}
fn make_pdorbox<'a>() -> PDOrBox<Foo<'a>> {
    unimplemented!()
}
fn main() {
  let x = make_pdorbox();
  make_selfref(&x);
}
```

https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=14dee41511095d6e940069db08cdc23f

I expected to see this happen: since a `PhantomData` claims to act like a `T` including for the purposes of borrowck/dropck then this should absolutely compile-fail. just as it does if you use a `Box`, or `T` directly!

Instead, this happened: it doesn't!

this is clearly unsound.

### Meta

`rustc --version --verbose`:
```
playground
```

<details><summary>Backtrace</summary>
<p>

```
<backtrace>
```

</p>
</details>

### PR DESCRIPTION
**Pull request by RalfJung**
As far as I could find out, the `PhantomData`-dropck interaction *only* affects code using `may_dangle`. The documentation in the standard library has not been updated for 8 years and thus stems from a time when Rust still used "parametric dropck", before [RFC 1238](https://rust-lang.github.io/rfcs/1238-nonparametric-dropck.html). Back then what the docs said was correct, but with `may_dangle` dropck it stopped being entirely accurate and these days, with NLL, it is actively misleading.

Fixes https://github.com/rust-lang/rust/issues/102810
Fixes https://github.com/rust-lang/rust/issues/70841
Cc @nikomatsakis I hope what I am saying here is right.^^

### CODE REVIEW

**Comment by RalfJung** [comment]
Looks like this was brought up more than 2 years ago already, in https://github.com/rust-lang/rust/issues/70841. @pnkfelix [pointed at](https://github.com/rust-lang/rust/issues/70841#issuecomment-611691130) the problematic docs paragraph that this PR is changing, and also raised the concern that

> I do worry a little bit about the user's mental model for this case, however. The claim "`PhantomData<T>` is just like a T" doesn't quite hold up. (not that it ever did ...)

**Comment by MU001999** [comment]
It seems that the `PhantomData`-dropck interaction not only affects code using `#[may_dangle]`. Considering the following [demo](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=c144f5f04cbb51539800ec2658ff609e):

```rust
use std::marker::PhantomData;

struct Foo<T>(Box<i32>, PhantomData<T>);

struct Bar<T>(T);
impl<T> Drop for Bar<T> {
    fn drop(&mut self) {}
}

fn main() {
    let _foo;
    let s = String::from("Hello, world!");
    _foo = helper(&*s);
}

fn helper<'a>(_: &'a str) -> Foo<Bar<&'a str>> {
    Foo(Box::new(1), PhantomData)
}
```

Without `impl<T> Drop for Foo<T>` and `#[may_dangle]`, the `PhantomData` introduces the dropck for `Bar<&'a str>`.

**Comment by SoniEx2** [comment]
our proposed MCP for dropck bounds might be useful to explain the PhantomData behaviour.

tho with our MCP's flexibility, we'd argue this should be changed in the future. so, don't rely on it.

**Comment by RalfJung** [comment]
@MU001999 Interesting example... I first thought this was not dropck, but [this compiles](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=56b52fdc5514f01a1fa0149477394f2e), indicating that it is indeed dropck.

Looks like we need a research project to even figure out our current dropck rules...

**Comment by TOETOE55** [comment]
I outlined the current drop check rules for myself:


1. Drop check occurs **only** on  "needs drop" variables in the current scope. 
2. Denote a dropping variable `t` and its type `T`, in the scope of `'t`. 

   `dropck(T, 't)` :=

   1. if `T` isn't a "needs drop" type expect `T == PhantomData`, skip the drop check
   2. if `T == PhantomData<P>`,  check `dropck(P, 't)`
   3. if `T` is `dyn trait` or `impl trait`, check `T: 't`
   4. if `T` is ADT with generics-params `<..., P, ...>`,(`P` could be lifetime or type)
      1. if `T` impl `Drop`, check `P: 't`, unless `P` was mark as `#[may_dangle]`
      2. drop check for all fields of `T` recursively.

NB: all `T: 't` in drop check means "strictly outlive".

*** 

`PhantomData<T>`, `ManuallyDrop<T>` or `Pending<T>` variables never "need drop", so they won't do the drop check

**Comment by danielhenrymantilla** [comment]
From all we've seen, I've been able to gather the following understanding of the dropck behavior. 

Given a `Wrapper<T>` (which could be a `struct Wrapper<T>`, or any `T`-dependent type (_e.g._, `(String, T)`).

To illustrate, consider `Wrapper<T> = Box<T>`, and `T` being `&'dangling_in_drop str` or `DisplayOnDrop<&'dangling_in_drop str>`

<details><summary>Code example</summary>

```rs
struct Box<T> {
    ptr: *const T,
    // … (e.g., should we `PhantomData<T>` or not)
}

impl<T> Drop for Box<T> { /* or:
unsafe impl<#[may_dangle] T> Drop for Box<T> { */
    fn drop(&mut self) {
        unsafe { ptr::drop_in_place::<T>(self.ptr); } // no-op if `T` has no drop glue (so `T` could dangle).
        unsafe { alloc::dealloc(self.ptr, …); } // does not use values of type `T`.
    }
}

/* e.g.
impl<'dangling_in_drop> for Box<&'dangling_in_drop str> {
// or
unsafe impl<#[may_dangle] 'dangling_in_drop> for Box<&'dangling_in_drop str> {

// as well as:
impl<'dangling_in_drop> for Box<DisplayOnDrop<&'dangling_in_drop str>> {
// or
unsafe impl<#[may_dangle] 'dangling_in_drop> for Box<DisplayOnDrop<&'dangling_in_drop str>> {
*/

// where
struct DisplayOnDrop<T : Display>(T);
impl<T : Display> Drop for DisplayOnDrop<T> {
    fn drop(&mut self) {
        println!("{}", self.0);
    }
}

fn main() {
    let (b1, b2);
    {
        let dropped_before_the_boxes = String::from("…");
        let thus_dangling_in_drop = &*dropped_before_the_boxes;

        b1 = Box::new(thus_dangling_in_drop);
        b2 = Box::new(DisplayOnDrop(thus_dangling_in_drop));
     } // `drop(dropped_before_the_boxes)`
     /* `thus_dangling_in_drop` is dangling here! */
} // `drop((b1, b2))`
```

 1. Ideally, we'd want `b1` to be accepted since `drop_in_place::<&str>()` does nothing and thus `&str` being a `&'dangling str` is fine.

 1. For soundness, we need `b2` to be rejected since `drop_in_place::<DisplayOnDrop<&str>>()` displays the given string, so it must not dangle.

The practical TL,DR with drop and `PhantomData` is that:

  - `impl<T> Drop for Box<T> {` achieves `2.`, but at the cost of breaking `1.`;
  - `unsafe impl<#[may_dangle] T> for Box<T> {`, alone, achieves `1.` but at the cost of breaking `2.` (unsound!);
  - `unsafe impl<#[may_dangle] T> for Box<T> {`, coupled with an "owning field" (even a `PhantomData` one) in `Box` preserves `1.` while bringing back `2.`, and thus, soundness.

But there are other edge cases which may require a more detailed exposition of the rules at play, here:

___

</details>

  - ### When does strict `dropck` (assume any use of `T` in drop) apply
    A.k.a., should `T : 'drop_point` have to hold? (this rejects both `T = &'dangling str` and `T = DisplayOnDrop<&'dangling str>`).

    This occurs when:
      - `impl<T> Drop for …`

    Since this property is more restrictive than `dropck(T, 'drop_point)`; the following dropck considerations do not matter in practice when we are in this case.

  - ### When does precise `dropck` (only use of `T` in drop is `drop_in_place::<T>`) apply
    A.k.a. should `dropck(T, 'drop_point)` have to hold? (this rejects `T = DisplayOnDrop<&'dangling str>` only, allowing `T = &'dangling str`).

    This occurs when both:
      - `Wrapper<T>` may have drop glue;
          - which happens when:
              - either `unsafe impl<#[may_dangle] T> for Wrapper<T> {` (or technically just `impl<T> Drop`, but as mentioned this does not matter / is not observable);
              - or when one of the fields of `Wrapper<T>` (which does not have to depend on `T`) has drop glue.
          - which is known **not** to happen when:
              - `Wrapper<T> : Copy` (_e.g._, `Wrapper<T> = PhantomData<T>`; this would be #70841 and #102810)
              - `Wrapper<T> = ManuallyDrop<…>`;

      - and `T` is structurally present in an owned fashion (_e.g._, `T`, `PhantomData<T>`, `ManuallyDrop<T>`) in `Wrapper<T>`

  - These properties become structural, unless we run into any of these "root rules" at any layer.

**Comment by SoniEx2** [comment]
nope, ManuallyDrop doesn't have drop glue, while PhantomData does. see also https://github.com/rust-lang/rust/issues/103318#issuecomment-1288209150

**Comment by danielhenrymantilla** [comment]
Ah, interesting, let me update the post. It does mean that "`PhantomData<T>` acts as `ManuallyDrop<T>`" (which I saw somewhere) is not accurate either 🥴

**Comment by MU001999** [comment]
> I outlined the current drop check rules for myself:
> 
>     1. Drop check occurs **only** on  "need drop" variables in the current scope when they are dropping.
> 
>     2. Denote a dropping variable `t` and its type `T`, in the scope of `'t`.
>        `dropck(T, 't)` :=
>        
>        1. if `T` isn't a "needs drop" type expect `T == PhantomData`, skip the drop check
>        2. if `T == PhantomData<P>`,  check `dropck(P, 't)`
>        3. if `T` is `dyn trait` or `impl trait`, check `T: 't`
>        4. if `T` is ADT with generic params `<..., P, ...>`,(`P` could be lifetime or type)
>           
>           1. if `T` impl `Drop`, check `P: 't`, unless `P` is marked as `#[may_dangle]`
>           2. drop check for all fields of `T` recursively.
> 
> 
> NB: all `T: 't` in drop check means "strictly outlive".
> 
> `PhantomData<T>`, `ManuallyDrop<T>` or `Pending<T>` variables never "need drop", so they won't do the drop check

Amazing! These rules are outlined very clearly!

With these rules, it can be said that `PhantomData<P>` assumes the field(data) of type `P` is dropped if `T` "needs drop", `impl<..., P, ...> Drop for T<..., P, ...>` assumes data of type `P` is accessed in the `T::drop`, and `#[may_dangle] P` assumes data of type `P` won't be accessed in the `T::drop`.

In turn, `PhantomData<P>` introduces dropck for `P` and means `T` "owns" the data of type `P` if and only if `T` "needs drop", `impl<..., P, ...> Drop for T<..., P, ...>` requires `P: 't`, and `#[may_dangle] P` discards the requirement `P: 't`.

Thus, `PhantomData<P>` only cares if `T` "needs drop" and does not care about if `#[may_dangle] P` or not. `#[may_dangle] P` + `PhantomData<P>` only means that `T::drop` does not accesses data of type `P` but drops data of type `P`, e.g., `T = Vec<P>`, `PhantomData<P>` works fine according to the previous rules.

**Comment by TOETOE55** [comment]
This is the “needs drop” what I said above.
https://doc.rust-lang.org/stable/std/mem/fn.needs_drop.html

**Comment by TOETOE55** [comment]
I’m still curious about this question, https://github.com/rust-lang/rust/issues/70841#issuecomment-1324486966

If the following `MyBox` unsound or not:

```rust
struct MyBox<T>(NonNull<T>);

impl<T> Drop for MyBox<T> { … }
```



> From my understanding of dropck, considering `MyBox<T>` impl no `#[may_dangle]` Drop:
> 
> If it construct
> 
> * without `PhantomData<T>`, the dropck would be:
> 
>   `dropck(MyBox<T>, 'scope) := T: 'scope` (strictly)
> 
> * with  `PhantomData<T>`:
> 
>   `dropck(MyBox<T>, 'scope) := T: 'scope & dropck(T, 'scope)` where `dropck(PhantomData<T>, 'scope) := dropck(T, 'scope)`
> 
> If you want to construct a ub from the former, it is equivalent to finding a `T` that satisfies `T: 'scope` but not `dropck(T, 'scope)`, and causes ub when it destructs.
> 
> But I tried to construct such a `T` and failed. I can't even find a counterexample for `T:' scope - > dropck(T, 'scope)`.

**Comment by MU001999** [comment]
@TOETOE55T From my understanding, `T: 't` is stricter than `dropck(T, 't)`, because the latter requires recursively at most all generic params of `T` outlives `'t`. This is also why we may need `PhantomData` if we have used `#[may_dangle]`.

**Comment by TOETOE55** [comment]
I just glanced at NLL's RFC, layer-3-accommodating-dropck section https://rust-lang.github.io/rfcs/2094-nll.html#layer-3-accommodating-dropck

>   This operation executes the destructor for variable, effectively "de-initializing" the memory in which the value resides (if the variable -- or parts of the variable -- have already been dropped, then drop has no effect; this is not relevant to the current analysis)


But the status quo still do the dropck on variables are dropped: https://play.rust-lang.org/?version=stable&mode=release&edition=2021&gist=caef1740c9b3f9ff35911202ecd6f68f

```rust
use std::marker::PhantomData;

struct Foo<T>(Box<i32>, PhantomData<T>);

struct Bar<T>(T);
impl<T> Drop for Bar<T> {
    fn drop(&mut self) {}
}

fn main() {
    let _foo;
    let s = String::from("Hello, world!");
    _foo = helper(&*s);
    std::mem::drop(_foo); // or `drop(_foo.0)
}

fn helper<'a>(_: &'a str) -> Foo<Bar<&'a str>> {
    Foo(Box::new(1), PhantomData)
}
```

**Comment by nikomatsakis** [comment]
I think the correct rules are:

* If the value's type has drop glue (needs proper definition) and a generic parameter T:
    * It is considered to drop a value of type T if...
        * the struct has a field which owns a T
        * there is phantom-data of type T
        * or the struct implements Drop
* Note that phantom-data by itself does not have drop-glue, so when dropped it is a no-op to borrow check

Another way to put it:

* The behavior of the DROP GLUE knows what gets dropped
    * but it also considers `PhantomData` values to be dropped

But I've not run any experiments, so maybe I'm missing something. Have to pull back in the examples we tried last time.

Per these rules:

* `PhantomData<T>` is not considered to drop T, it has no drop-glue
* a `struct Foo<T> { d: T, e: String }` *is* considered to drop `T` (because `String` has drop-glue)
* and so is `struct Foo<T> { d: PhantomData<T>, e: String }`
* but `struct Foo<'a, T> { d: &'a T, e: String }` is not (I think)
* not sure about `struct Foo<T> { d: *mut T, e: String }` ..?

If a struct actually implements Drop, then it is always assumed to drop all the things (modulo the unstable feature). So if there is a `impl Drop for Foo` for any such examples, it would always be assumed to drop `T`.

**Comment by RalfJung** [comment]
We don't need an RFC to document the existing analysis. We just need an RFC to change it.

**Comment by SoniEx2** [comment]
*nod*

we should probably have an RFC to remove the existing spooky action at a distance instead of documenting it.

**Comment by nikomatsakis** [comment]
@RalfJung did what I wrote make sense to you? Do you think you can update the docs you wrote ?

**Comment by nikomatsakis** [comment]
I would like to separate out the question of whether/how to change the behavior and just stick to documenting existing behavior here.

**Comment by RalfJung** [comment]
It's on my list, I need to find some time to get back to this and do some experiments.

**Comment by nikomatsakis** [comment]
@rustbot labels -I-lang-nominated

OK, I'm removing the nomination here, @RalfJung please re-nominate when you've had time for that.

**Comment by RalfJung** [comment]
@nikomatsakis what you wrote explains [this example](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=56b52fdc5514f01a1fa0149477394f2e), so -- sounds good.

One question is where the docs should even go... this PR was about adjusting PhantomData docs, but that's not the right place for a full dropck description. The question is, what *is* the right place? I would say the `Drop` trait, so if nobody says anything else that's where I am going to put this.

**Comment by SoniEx2** [comment]
what is this example trying to show?

**Comment by SoniEx2** [comment]
the way we'd describe it is

- If the value's type has drop glue (needs proper definition) and a generic parameter T:
    - It is considered to drop a value of type T if...
        - the struct has a field which has drop glue for T
        - or the struct implements Drop
- PhantomData has drop glue, but not needs_drop.
- ManuallyDrop explicitly does not have drop glue.
- The above conditions are only checked (as in dropck) if a value is actually dropped - needs_drop is checked first, by NLL.

**Comment by RalfJung** [comment]
PhantomData does not have drop glue though. I would say "has drop glue" == needs_drop.

**Comment by SoniEx2** [comment]
we disagree. we treat "has drop glue" as different from "requires drop glue to be called".

**Comment by RalfJung** [comment]
I don't see any reason why that would be helpful or a good idea. Introducing such a distinction seems to just make life more difficult for no benefit.

**Comment by SoniEx2** [comment]
it is more literal. "needs drop" = "requires drop glue to be called". and it fits.

it's also far easier to represent in the compiler, especially as bounds and/or traits.

**Comment by RalfJung** [comment]
Your rules are equivalent to, but more complicated than, what Niko said above. Also I am fairly sure rustc "has drop glue" == needs_drop, so what you say about things being easier for the compiler is just not right.

Saying that PhantomData has drop glue is also just plain confusing. Not sure in which sense it is "more literal", I would say it is the opposite.

**Comment by SoniEx2** [comment]
our rules align with rust 1.34(?) 2015 edition (where NLL didn't exist, so it always calls drop glue, regardless of whether it needs to), so we believe them to be more correct.

it's also more literal, in the sense that "needs drop" literally means "requires drop (glue) to be called".

**Comment by RalfJung** [comment]
You realize this PR is about describing *current* behavior, right? Please don't cause confusion by mixing in outdated/alternative rules.

**Comment by SoniEx2** [comment]
the "outdated" behaviour *explains* current behaviour. it lets us analyze what *changed* between then and now.

and what changed is whether needs_drop gets used to decide when drop glue gets called. our rules are at least historically accurate, they draw on language history to describe current behaviour, instead of ignoring the history. this makes them more likely to be more correct.

**Comment by RalfJung** [comment]
@nikomatsakis I have tried to incorporate the rules you listed into the docs. However, I am not entirely happy with what I currently got. In particular, we have to define more precisely what it means for a field to "own" a type. Somehow the analysis has to become recursive here, right?

I also reframed this from "which types are being dropped" to "what has to be live on dropping". I think this is necessary, since there are two different kinds of requirements that can arise:
- if the type has an `impl Drop`, then all generic parameters `U` and lifetimes need to be "fully live" since arbitrary methods may be called on them
- if the type just has a field of some type `U`, then we know that only the destructor of `U` will be called, not arbitrary other methods, so it might actually be okay for `U` to be not "fully live"

Therefore it wouldn't be correct to lump both of these together as "`U` is considered to be dropped", right? I think it is probably something like this:

- Otherwise, for all types `U` that are *owned* by any field of `T` (including inside `PhantomData`),   recursively add the types and lifetimes that need to be live when dropping `U`. Here, `Box<U>` (and `PhantomData<U>`) are considered to "own" `U`, but `&U`  or `*mut U` are not.

Is that correct? And where is "types owned by a type" defined?

> the "outdated" behaviour explains current behaviour. it lets us analyze what changed between then and now.

I disagree and I don't think this is helpful. Unless you think that the rules Niko wrote (or my attempt at documenting them) do not reflect the current implementation, this is off-topic and I ask you to take that discussion elsewhere.

**Review by nikomatsakis — APPROVED** [review]
This looks right to me. Thanks @RalfJung

**Comment by nikomatsakis** [comment]
r=me but I'll wait until lang team triage.

**Comment by SoniEx2** [comment]
> And I mean the _current_ rules, not the rules as of 3 years ago.

do the current rules, as implemented in the compiler, not use NLL to decide when to run dropck? we don't think dropck has changed; we think NLL has.

**Comment by RalfJung** [comment]
> do the current rules, as implemented in the compiler, not use NLL to decide when to run dropck? we don't think dropck has changed; we think NLL has.

It doesn't matter where the rules are implemented, and whether drop check is part of the borrow checker or a separate component. To my knowledge the two are closely entwined. What matters is the overall effect -- which programs are accepted, which are rejected. In that sense, the drop check behavior has changed.

The goal of this PR is to properly describe that behavior in its current form. I think NLL changed the effect here because the old borrow checker *always* considered a variable live for its entire scope, whereas NLL is able to use non-lexical lifetimes (hence its name) *for variables that do not need dropping*. Variables that do need dropping necessarily have a lexical lifetime since the dropping happens when they go out of scope.

**Comment by SoniEx2** [comment]
yes, hence it's the needsdropness that decides whether to run dropck, but it's not itself part of dropck. dropck only considers ownership, including PhantomData, so it makes no sense to special-case PhantomData in the docs if it's not special-cased in the language. (well it is special-cased in the language but we mean... eh meh we like to think of it as "PhantomData owns T" instead of "dropck also checks the T in a PhantomData" because the former is more akin to how PhantomData is intended to be, as per language docs.)

File: library/core/src/ops/drop.rs [hunk 1]
```diff
@@ -132,6 +132,73 @@
...
+///
+/// The Nomicon discusses the need for [drop check in more detail][drop check].
+///
+/// To reject such code, the "drop check" analysis determines which types and lifetimes need to
+/// still be live when `T` gets dropped:
+/// - If `T` has no drop glue, then trivially nothing is required to be live. This is the case if
+///   neither `T` nor any of its (recursive) fields have a destructor (`impl Drop`). [`PhantomData`]
+///   and [`ManuallyDrop`] are considered to not have a destructor.
+/// - Otherwise, for all types `U` that are *owned* by any field of `T` (including inside
+///   `PhantomData`), recursively add the types and lifetimes that need to be live when `U` gets
```
Comment (Mark-Simulacrum) [inline library/core/src/ops/drop.rs:176]: I'm trying to parse the "including inside `PhantomData`". Since this starts with "Otherwise", it seems like we *shouldn't* hit this case if the previous one applies, which (as it says) it does - PhantomData considered to not have a destructor.

It seems like part of the confusion is over whether `PhantomData<T>` owns `T` -- does it? (Or whether it "has a field of type `T`, which does not seem obvious).

FWIW, I think this gets into the question you posed in your comment to Niko ("Is that correct? And where is "types owned by a type" defined?"), and I feel like the current text isn't a precise reflection (yet).

I think at minimum removing "Otherwise" might help here but I don't think it's quite enough.

File: library/core/src/ops/drop.rs [hunk 2]
```diff
@@ -132,6 +132,73 @@
...
+///   dropped. The set of owned types is determined by recurisvely traversing `T`:
```
Comment (Mark-Simulacrum) [inline library/core/src/ops/drop.rs:177]:
```suggestion
///   dropped. The set of owned types is determined by recursively traversing `T`:
```

**Comment by Mark-Simulacrum** [comment]
T-lang discussed this and didn't have further desire to touch on this, so removing the nomination. If T-types wanted to weigh in though T-lang had no objections (but didn't require it).

File: library/core/src/ops/drop.rs (hunk 1 above)
Comment (RalfJung) [reply library/core/src/ops/drop.rs]: "Otherwise" is needed to clarify that this ownership analysis only happens if T has drop glue. That is the key confusion that caused https://github.com/rust-lang/rust/issues/70841.

I can replace it by explicitly stating "if T has drop glue" though. Is that better?

**Comment by RalfJung** [comment]
@rust-lang/types how does the nomination process work for your team? Do you want to weigh in on this PR?

Otherwise it is currently assigned to @scottmcm and @pnkfelix.

**Comment by lcnr** [comment]
going to probably talk about this next week at the types team meeting as part of our triage of nominated issues.

**Comment by lcnr** [comment]
https://rust-lang.zulipchat.com/#narrow/stream/326132-t-types.2Fmeetings/topic/2023-01-18.20meeting/near/322082760 intend to talk about this in-depth in a types team meeting next month

File: library/core/src/ops/drop.rs (hunk 1 above)
Comment (Mark-Simulacrum) [reply library/core/src/ops/drop.rs]: Yes, I think so.

**Comment by RalfJung** [comment]
I wonder if we should apply the following diff, which I think does not change the rules but means fewer special cases:
```diff
 ///     they do not own anything.
 ///   - Stop at non-composite types (type parameters that remain generic in the current context and
 ///     base types such as integers and `bool`); these types are owned.
-///   - When hitting an ADT with `impl Drop`, stop there; this type is owned.
-///   - When hitting an ADT without `impl Drop`, recursively descend to its fields. (For an `enum`,
-///     consider all fields of all variants.)
+///   - When hitting an ADT (`struct`/`enum`/`union`), stop there; this type is owned.
 /// - Furthermore, if `T` implements `Drop`, then all generic (lifetime and type) parameters of `T`
 ///   must be live.
 ///
```
Considering a non-`impl Drop` type owned should be the same as considering all its fields owned, right?
Probably it would be best to align this with the implementation -- where would I go looking for that?

File: library/core/src/ops/drop.rs [hunk 3]
```diff
@@ -132,6 +132,73 @@
...
+/// The Nomicon discusses the need for [drop check in more detail][drop check].
+///
+/// To reject such code, the "drop check" analysis determines which types and lifetimes need to
+/// still be live when `T` gets dropped:
+/// - If `T` has no drop glue, then trivially nothing is required to be live. This is the case if
+///   neither `T` nor any of its (recursive) fields have a destructor (`impl Drop`). [`PhantomData`]
+///   and [`ManuallyDrop`] are considered to never have a destructor, no matter their field type.
+/// - If `T` has drop glue, then, for all types `U` that are *owned* by any field of `T`,
+///   recursively add the types and lifetimes that need to be live when `U` gets dropped. The set of
+///   owned types is determined by recursively traversing `T`:
```
Comment (RalfJung) [inline library/core/src/ops/drop.rs:177]: Something extra subtle seems to be going on that I am not sure is captured by these rules yet... [this code compiles](https://github.com/rust-lang/rust/issues/99408#issuecomment-1187288078). But according to these rules, shouldn't it be the case that `S<T>` "owns" a `T`, and therefore `T` needs to be live when `S<T>` is dropped? Does "owns" not consider the contents of a `ManuallyDrop` owned?

Comment (RalfJung) [reply library/core/src/ops/drop.rs:177]: In particular, [this does not compile](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=a4aa6854eced73b4a45ccf9069b675ac). So there is clearly something that treats PhantomData different from ManuallyDrop here, and the rules @nikomatsakis suggested don't capture that I think.

**Comment by RalfJung** [comment]
@lcnr 
> https://rust-lang.zulipchat.com/#narrow/stream/326132-t-types.2Fmeetings/topic/2023-01-18.20meeting/near/322082760 intend to talk about this in-depth in a types team meeting next month

Did this discussion happen? What is the current status here?

File: library/core/src/ops/drop.rs [hunk 4]
```diff
@@ -132,6 +132,73 @@
...
+///   - Recursively descend through `PhantomData`, `Box`, tuples, and arrays (including arrays of
+///     length 0).
+///   - Stop at reference and raw pointer types as well as function pointers and function items;
+///     they do not own anything.
+///   - Stop at non-composite types (type parameters that remain generic in the current context and
+///     base types such as integers and `bool`); these types are owned.
+///   - When hitting an ADT with `impl Drop`, stop there; this type is owned.
+///   - When hitting an ADT without `impl Drop`, recursively descend to its fields. (For an `enum`,
+///     consider all fields of all variants.)
```
Comment (lcnr) [inline library/core/src/ops/drop.rs:186]:
```suggestion
///   - When hitting an ADT without `impl Drop`, recursively descend to its fields except for `ManuallyDrop`.
///     (For an `enum`, consider all fields of all variants.)
```
or sth like that

File: library/core/src/ops/drop.rs (hunk 3 above)
Comment (lcnr) [reply library/core/src/ops/drop.rs:177]: So yeah, feel like I understand `dropck` now. It is fairly involved.

`ManuallyDrop<T>` is always considered to be trivially droppable as it does not have any drop glue. This is only the case in `trivial_dropck_outlives` https://github.com/rust-lang/rust/blob/fab99073b01539ce2664366011c7f3e378e52b7e/compiler/rustc_trait_selection/src/traits/query/dropck_outlives.rs#L52-L55

We do not special case `ManuallyDrop` in the actual `dropck_outlives`/`adt_dtorck_constraint` which makes this pretty confusing.

the `adt_dtorck_constraint` for `PhantomData` data simply requires `T` to be live. `PhantomData` is unique as it has outlives requirements even though `needs_drop` for it is `false`. We only check the outlives requirements for variables which need to be dropped. This means the outlives requirements of `PhantomData` are only considered when it is used in a more complex variable where a different part actually `needs_drop`. This results in the following weird behavior https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=bc7ae38e8f0cfcda826ea8d35b69c0af

Comment (lcnr) [reply library/core/src/ops/drop.rs:177]: Can you add a check for `manually_drop` here: https://github.com/rust-lang/rust/blob/fab99073b01539ce2664366011c7f3e378e52b7e/compiler/rustc_traits/src/dropck_outlives.rs#L295

This should be unreachable because `ManuallyDrop` should be fully handled by the `trivial_dropck_outlives` fastpath in https://github.com/rust-lang/rust/blob/fab99073b01539ce2664366011c7f3e378e52b7e/compiler/rustc_traits/src/dropck_outlives.rs#L150-L152

**Review by lcnr — COMMENTED** [review]
looked through this and feel like I finally understand this code.

the behavior of `PhantomData` as something without `needs_drop` but with `adt_dtorck_constraint` can also affect code without `#[may_dangle]` and is pretty confusing. As `PhantomData` is `Copy` we cannot really change this I think.

I think it's good that `ManuallyDrop` does not add outlives requirements to dropck, so this behavior shouldn't be changed.

**Comment by lcnr** [comment]
all in all, I agree with the documentation added and while sadly pretty complex, I don't see how we'd change the behavior here going forward.

> `PhantomData` is unique as it has outlives requirements even though `needs_drop` for it is `false`.

This is wrong, the interaction of `PhantomData<T>` and dropck is equivalent to the interaction of `[T; 0]` and dropck. Both do not set `needs_drop` but add outlives constraints for `T`

**Comment by lcnr** [comment]
finally, I guess r=me on the PR after the nits, but lets go through an FCP

I believe this to correctly document the status quo. While the status quo is confusing, I don't believe that we're able to improve it. Because of that I propose merging this documentation even if this locks us into the current behavior.

One exception are the outlives requirements for `[T; 0]` which I would like to change, opening a separate issue for that.

@rfcbot fcp merge

File: library/core/src/ops/drop.rs (hunk 3 above)
Comment (RalfJung) [reply library/core/src/ops/drop.rs:177]: This was meant to be a docs-only change. I'm not at all familiar with that code.

> ManuallyDrop should be fully handled 

I am confused, the first code you referenced is about PhantomData, not ManuallyDrop?

**Comment by SoniEx2** [comment]
@lcnr 

> I guess a potential alternative is to make `PhantomData` even less impactful wrt to drop and actually only adding outlives requirements when used as a field of a type with a manual drop impl, i.e. `PhantomData` actually only impacts manual `Drop` impls when they have `#[may_dangle]`. I would like to explore that route more.

this is effectively what rust-lang/rfcs#3390 proposes - tho it tries to do so in a much more formalized way, basically defining some syntax and semantics and a whole system around it, as well as trying to explain how the current and desired behaviours fit into the proposed model (in other words: in a rather roundabout way). but for stable code, yeah, the observable result would be the same. maybe we should've leaned harder on spooky-dropck-at-a-distance as motivation, given that it (and being opposed to this very pull request) is what led us to write the RFC in the first place... but anyway!

we can try a sync meeting? uh we've never really done of those tho? so we're not sure what to expect or how to prepare for it? >.<

File: library/core/src/ops/drop.rs (hunk 3 above)
Comment (lcnr) [reply library/core/src/ops/drop.rs:177]: implemented my suggestion myself: #110323

**Comment by lcnr** [comment]
> we can try a sync meeting? uh we've never really done of those tho? so we're not sure what to expect or how to prepare for it? >.<

wouldn't have needed to prepare anything for it :grinning: mostly just wanted to have a quicker conversation because having conversations via github is a horrible experience in my opinion. going to instead use the existing zulip thread.  https://rust-lang.zulipchat.com/#narrow/stream/213817-t-lang/topic/deprecating.20spooky-dropck-at-a-distance

**Comment by RalfJung** [comment]
There's an argument in https://github.com/rust-lang/rfcs/pull/3417 that we shouldn't stably document this behavior, i.e. we shouldn't land this PR, because we want to change this behavior anyway. I guess alternatively we could add a preface saying that this is not guaranteed? That makes one wonder about the point of the docs though.

Either way I guess I won't spend time on this PR until that discussion is resolved. Seems like a waste of time if we're not going to document this anyway.

File: library/core/src/marker.rs [hunk 5]
```diff
@@ -668,24 +668,17 @@ impl<T: ?Sized> !Sync for *mut T {}
...
-/// `T`. This has bearing on the Rust compiler's [drop check]
-/// analysis.
-///
-/// If your struct does not in fact *own* the data of type `T`, it is
-/// better to use a reference type, like `PhantomData<&'a T>`
-/// (ideally) or `PhantomData<*const T>` (if no lifetime applies), so
-/// as not to indicate ownership.
+/// Adding a field of type `PhantomData<T>` indicates that your type *owns* data of type `T`. This
+/// in turn has effects on the Rust compiler's [drop check] analysis, but that only matters in very
+/// specific circumstances. For the exact rules, see the [drop check] documentation.
```
Comment (lcnr) [inline library/core/src/marker.rs:673]:
```suggestion
/// The exact interaction of `PhantomData` with drop check may change in the future.
///
/// Adding a field of type `PhantomData<T>` currently indicates that your type *owns* data of type
/// `T` in very rare circumstances. This in turn has effects on the Rust compiler's [drop check]
/// analysis. For the exact rules, see the [drop check] documentation.
```

File: library/core/src/ops/drop.rs [hunk 6]
```diff
@@ -132,6 +132,73 @@
...
+///     // Now they both get dropped. But whichever is the 2nd one
+///     // to be dropped will access the `Box` in the first one,
+///     // which is a use-after-free!
+/// }
+/// ```
+///
+/// The Nomicon discusses the need for [drop check in more detail][drop check].
+///
+/// To reject such code, the "drop check" analysis determines which types and lifetimes need to
+/// still be live when `T` gets dropped:
```
Comment (lcnr) [inline library/core/src/ops/drop.rs:171]: please state somewhere that these exact rules may change in the future.

**Review by lcnr — COMMENTED** [review]
we finally got to this issue in t-types triage: https://rust-lang.zulipchat.com/#narrow/stream/326132-t-types.2Fmeetings/topic/2023-05-08.20triage.20meeting/near/356728590

we intend to have a deep dive about the dropck rules and how to change them (https://github.com/rust-lang/types-team/issues/92), but are open (some of us were in favor) of merging this documentation until then with the expectation that this does not block us from changing the subtle details of dropck later.

lgtm on the current documentation, but please add a note that this is not a stability guarantee. after that r=me

**Comment by RalfJung** [comment]
I made it clear that these rules are not stably guaranteed.

Looks like we can finally land this. Thanks a lot to everyone involved!
@bors r=lcnr

File: library/core/src/marker.rs (hunk 5 above)
Comment (workingjubilee) [reply library/core/src/marker.rs]: I don't understand why you recommended this change, @lcnr. It seems to obscure the matter more from the user perspective: does PhantomData indicate you own its type parameter or not?

Comment (lcnr) [reply library/core/src/marker.rs]: well, currently it does, in the future it likely will stop doing so
