### PR TITLE
fix panic when rustc tries to reduce intermediate filenames len with utf8

### LINKED ISSUE #147975: regression: ICE byte index is not a char boundary
- https://crater-reports.s3.amazonaws.com/beta-1.91-2/beta-2025-09-21/gh/magicwenli.leetcode/log.txt
- https://crater-reports.s3.amazonaws.com/beta-1.91-2/beta-2025-09-21/gh/tbqjxmz.leetcode-rs/log.txt

```
[INFO] [stderr] thread 'rustc' (129) panicked at compiler/rustc_session/src/config.rs:1213:17:
[INFO] [stderr] byte index 17 is not a char boundary; it is inside '串' (bytes 15..18) of `28_找出字符串中第一个匹配项的下标-871c9ced96aae9c5.28_找出字符串中第一个匹配项的下标.54700393798b3d28-cgu.0.rcgu.o`
[INFO] [stderr] stack backtrace:
```

### PR DESCRIPTION
**Pull request by tardyp**
The issue cannot be reproduced with the former testcase of creating external crates because rust refuses to use "external crate 28_找出字符串中第一个匹配项的下标" because it is not a valid indentifier (starts with number, and contain non ascii chars)

But still using 28_找出字符串中第一个匹配项的下标.rs as a filename is accepted by previous rustc releases So we consider it valid, and add an integration test for it to catch any regression on other code related to non ascii filenames.

Fix rust-lang/rust#147975

### CODE REVIEW

**Comment by Noratrieb** [comment]
I've nominates this one for backport and will close the other PR to follow our standard process of nominating PRs against master and then letting the release team cherry pick approved backports. Thank you for the quick fix!

File: compiler/rustc_session/src/config.rs [hunk 1]
```diff
@@ -1211,13 +1211,26 @@ fn maybe_strip_file_name(mut path: PathBuf) -> PathBuf {
...
+
+        // number of bytes to remove from the start
+        let stripped_bytes = filename.len().saturating_sub(allowed_suffix);
+
+        // Find the next character boundary at or after `stripped_bytes` so slicing is valid.
+        let split_at = filename
+            .char_indices()
+            .find(|(i, _)| *i >= stripped_bytes)
+            .map(|(i, _)| i)
+            .unwrap_or(filename.len());
```
Comment (JonathanBrouwer) [inline compiler/rustc_session/src/config.rs]: I believe that the 5 lines above are equivalent to:
```rust
let split_at = filename.ceil_char_boundary(stripped_bytes);
```

**Review by JonathanBrouwer — CHANGES_REQUESTED** [review]

**Comment by tardyp** [comment]
@thanks @JonathanBrouwer for the thoughtful suggestion on this recently out of nightly api.

Note that I took the opportunity of this rework to replace the boring "28_找出字符串中第一个匹配项的下标" by more entertaining "ⴻⵎⵎⴻⵎ_ⴷⵉⵎⴰ_ⵖⴻⴼ_ⵢⵉⵙⴻⴽⴽⵉⵍⴻⵏ_ⵏ_ⵡⴰⵟⴰⵙ_ⵏ_ⵢⵉⴱⵢⵜⴻⵏ" which more adequately watches for multi byte character issues.

File: tests/run-make/lto-long-filenames_cn/rmake.rs [hunk 2]
```diff
@@ -0,0 +1,19 @@
...
+
+// This test make sure we don't crash when lto creates output files with long names.
+// cn characters can be multi-byte and thus trigger the long filename reduction code more easily.
+// we need to make sure that the code is properly generating names at char boundaries.
+// as reported in issue #147975
+fn main() {
+    let lto_flags = ["-Clto", "-Clto=yes", "-Clto=off", "-Clto=thin", "-Clto=fat"];
+    for prefix_len in 0..4 {
+        let prefix: String = std::iter::repeat("_").take(prefix_len).collect();
+        let main_file = format!("{}ⵅⴻⵎⵎⴻⵎ_ⴷⵉⵎⴰ_ⵖⴻⴼ_ⵢⵉⵙⴻⴽⴽⵉⵍⴻⵏ_ⵏ_ⵡⴰⵟⴰⵙ_ⵏ_ⵢⵉⴱⵢⵜⴻⵏ.rs", prefix);
```
Comment (JonathanBrouwer) [inline tests/run-make/lto-long-filenames_cn/rmake.rs:19]: Actually now that I'm looking at it again, I don't think this string is long enough to even trigger the `MAX_FILENAME_LENGTH` check

Comment (tardyp) [reply tests/run-make/lto-long-filenames_cn/rmake.rs:19]: yes, I've checked that the test is failing without the ceil_char_boundary call

 ```
thread 'coordinator' (3996871) panicked at compiler/rustc_session/src/config.rs:1226:17:
byte index 142 is not a char boundary; it is inside 'ⵉ' (bytes 141..144) of `ⵅⴻⵎⵎⴻⵎ_ⴷⵉⵎⴰ_ⵖⴻⴼ_ⵢⵉⵙⴻⴽⴽⵉⵍⴻⵏ_ⵏ_ⵡⴰⵟⴰⵙ_ⵏ_ⵢⵉⴱⵢⵜⴻⵏ.ⵅⴻⵎⵎⴻⵎ_ⴷⵉⵎⴰ_ⵖⴻⴼ_ⵢⵉⵙⴻⴽⴽⵉⵍⴻⵏ_ⵏ_ⵡⴰⵟⴰⵙ_ⵏ_ⵢⵉⴱⵢⵜⴻⵏ.d50c24c0c4ea93cc-c`[...]
stack backtrace:
   0: __rustc::rust_begin_unwind
             at /rustc/bb624dcb4c8ab987e10c0808d92d76f3b84dd117/library/std/src/panicking.rs:698:5
   1: core::panicking::panic_fmt
             at /rustc/bb624dcb4c8ab987e10c0808d92d76f3b84dd117/library/core/src/panicking.rs:75:14
   2: core::str::slice_error_fail_rt
   3: core::str::slice_error_fail
             at /rustc/bb624dcb4c8ab987e10c0808d92d76f3b84dd117/library/core/src/str/mod.rs:69:5
   4: maybe_strip_file_name
   5: temp_path_ext_for_cgu
             at /Users/az02096/dev/rust/rust/compiler/rustc_session/src/config.rs:1334:9
   6: codegen
             at /Users/az02096/dev/rust/rust/compiler/rustc_codegen_llvm/src/back/write.rs:812:44
   7: do_fat_lto<rustc_codegen_llvm::LlvmCodegenBackend>
             at /Users/az02096/dev/rust/rust/compiler/rustc_codegen_ssa/src/back/write.rs:1003:5
   8: {closure#4}<rustc_codegen_llvm::LlvmCodegenBackend>
             at /Users/az02096/dev/rust/rust/compiler/rustc_codegen_ssa/src/back/write.rs:1740:26
   9: {closure#0}<rustc_codegen_ssa::back::write::start_executing_work::{closure_env#4}<rustc_codegen_llvm::LlvmCodegenBackend>, core::result::Result<rustc_codegen_ssa::back::write::CompiledModules, ()>>
             at /Users/az02096/dev/rust/rust/compiler/rustc_codegen_llvm/src/lib.rs:150:13
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.


```

**Comment by tardyp** [comment]
Still this errors out on windows because of intermediate files are confusing mingw32's ld.exe

```
  === STDERR ===
  error: linking with `x86_64-w64-mingw32-gcc` failed: exit code: 1
    |
    = note: "x86_64-w64-mingw32-gcc" "-fno-use-linker-plugin" "-Wl,--dynamicbase" "-Wl,--disable-auto-image-base" "-m64" "-Wl,--high-entropy-va" "<1 object files omitted>" "-Wl,-Bstatic" "C:\\Users\\RUNNER~1\\AppData\\Local\\Temp\\rustcCysv9F/{libstd-a992d1b493a39173,libpanic_unwind-5227219e081de602,libobject-c2ce66c091f60d44,libmemchr-08b577be48673d68,libaddr2line-c414fa69168392cc,libgimli-4383c1445722b9e9,libcfg_if-91c461dc85a063c4,libwindows_targets-21e9cc148fe9b215,librustc_demangle-d228b746cabc6f47,libstd_detect-6b2458c5a505f319,libhashbrown-8ffe65380a33fbc7,librustc_std_workspace_alloc-74c749bd8b8d1d70,libminiz_oxide-e003dac593885fb1,libadler2-5498fbd71b721486,libunwind-3f18232a4935d0a7,liblibc-17b45909fdc41e03,librustc_std_workspace_core-6192bbfd291c5e47,liballoc-84f6dce3e0393c40,libcore-3de68c5f8670461d}.rlib" "<sysroot>\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib/libcompiler_builtins-*.rlib" "-Wl,-Bdynamic" "-lkernel32" "-lkernel32" "-lkernel32" "-lntdll" "-luserenv" "-lws2_32" "-ldbghelp" "-lgcc_eh" "-l:libpthread.a" "-lmsvcrt" "-lmingwex" "-lmingw32" "-lgcc" "-lmsvcrt" "-lmingwex" "-luser32" "-lkernel32" "-Wl,--nxcompat" "-L" "D:\\a\\rust\\rust\\build\\x86_64-pc-windows-gnu\\test\\run-make\\lto-long-filenames_cn\\rmake_out" "-o" "a.exe" "-Wl,--gc-sections" "-no-pie" "-nodefaultlibs"
    = note: some arguments are omitted. use `--verbose` to show all linker arguments
    = note: D:/a/rust/rust/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/14.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find f0d5ff18d6510ebc-???_???_??????????_?_?????_?_???????.d50c24c0c4ea93cc-cgu.0.rcgu.o: Invalid argument␍
            collect2.exe: error: ld returned 1 exit status
            
  ```

**Comment by tardyp** [comment]
@JonathanBrouwer I forgot the import in my commit from 5min ago. Forced pushed a fix after verifying it actually passes on my system. Will Need another try command.. 🙏

File: tests/run-make/lto-long-filenames_cn/rmake.rs [hunk 3]
```diff
@@ -0,0 +1,28 @@
...
+    if is_windows_gnu() {
+        // gnu ld is confused with intermediate files having multibytes characters in their names:
+        // = note: ld.exe: cannot find f0d5ff18d6510ebc-???_???_??????????_?_?????_?_???????.d50c2 \
+        // 4c0c4ea93cc-cgu.0.rcgu.o: Invalid argument
+        // as this is not something rustc can fix by itself,
+        // we just skip the test on windows-gnu for now.
+        return;
+    }
+    let lto_flags = ["-Clto", "-Clto=yes", "-Clto=off", "-Clto=thin", "-Clto=fat"];
+    let out = if is_windows() { "a.exe" } else { "a.out" };
```
Comment (JonathanBrouwer) [inline tests/run-make/lto-long-filenames_cn/rmake.rs]: Is this still needed now that we are not running this test on `windows_gnu`?

File: tests/run-make/lto-long-filenames_cn/rmake.rs [hunk 4]
```diff
@@ -0,0 +1,28 @@
+//@ ignore-cross-compile
+
+use run_make_support::{is_windows, is_windows_gnu, rfs, rustc};
+
+// This test make sure we don't crash when lto creates output files with long names.
+// cn characters can be multi-byte and thus trigger the long filename reduction code more easily.
+// we need to make sure that the code is properly generating names at char boundaries.
+// as reported in issue #147975
+fn main() {
+    if is_windows_gnu() {
```
Comment (JonathanBrouwer) [inline tests/run-make/lto-long-filenames_cn/rmake.rs]: We can use the `//@ ignore-windows-gnu` annotation instead of this check

File: tests/run-make/lto-long-filenames_cn/rmake.rs (hunk 3 above)
Comment (tardyp) [reply tests/run-make/lto-long-filenames_cn/rmake.rs]: It looks likve msvc did pass on the previous try, but it had this workaround. Lets try without indeed.

**Comment by JonathanBrouwer** [comment]
@bors try jobs=x86_64-mingw-*,i686-msvc-*
Would be really suprised if it fails now but lets run it anyways to be sure.
@tardyp Thanks so much for your quick fixes!

**Comment by tardyp** [comment]
I'll be in vacation tomorrow for a week, mostly afk, so I wouldn't be able to be so reactive. hopefully we can finish this today!

File: compiler/rustc_session/src/config.rs [hunk 5]
```diff
@@ -1211,13 +1211,22 @@ fn maybe_strip_file_name(mut path: PathBuf) -> PathBuf {
...
+        let hyphen_len = 1; // the '-' we insert between hash and suffix
+
+        // number of bytes of suffix we can keep so that "hash-<suffix>" fits
+        let allowed_suffix = MAX_FILENAME_LENGTH.saturating_sub(hash_len + hyphen_len);
+
+        // number of bytes to remove from the start
+        let stripped_bytes = filename.len().saturating_sub(allowed_suffix);
+
+        // ensure we don't cut in a middle of a char
+        let split_at = filename.ceil_char_boundary(stripped_bytes);
```
Comment (cuviper) [inline compiler/rustc_session/src/config.rs:1223]: FYI, I needed to bootstrap the `round_char_boundary` feature for this:
https://github.com/rust-lang/rust/pull/148075/commits/1e668e089dcc294fcc33daab6f0c4d40f0585aec#diff-a984c7e4fd6f10b956c673e00529f4f80cecdd5572d349ce1fda61b7ce63c5aa

(not a problem, just noting the difference in backport)
