### PR TITLE
Do not ICE on non-ADT rcvr type when looking for crate version collision

### LINKED ISSUE #129205: ICE: unexpected non-type Node::GenericParam
auto-reduced (treereduce-rust):
````rust
fn test_generic<T: Copy>(val: T) -> T {
    let _ = T::try_from(val).unwrap();
}


````

<details><summary><strong>original code</strong></summary>
<p>

original:
````rust
#![deny(clippy::useless_conversion)]
#![allow(
    clippy::needless_if,
    clippy::unnecessary_fallible_conversions,
    clippy::manual_unwrap_or_default
)]

fn test_generic<T: Copy>(val: T) -> T {
    let _ = T::try_from(val).unwrap();
    //~^ ERROR: useless conversion to the same type: `T`
    val.try_into().unwrap()
    //~^ ERROR: useless conversion to the same type: `T`
}

fn test_generic2<T: Copy + Into<i32> + Into<U>, U: From<T>>(val: T) {
    // ok
    let _: i32 = val.try_into().unwrap();
    let _: U = val.try_into().unwrap();
    let _ = U::try_from(val).unwrap();
}

fn main() {
    test_generic(10i32);
    test_generic2::<i32, i32>(10i32);

    let _: String = "foo".try_into().unwrap();
    let _: String = TryFrom::try_from("foo").unwrap();
    let _ = String::try_from("foo").unwrap();
    #[allow(clippy::useless_conversion)]
    {
        let _ = String::try_from("foo").unwrap();
        let _: String = "foo".try_into().unwrap();
    }
    let _: String = "foo".to_string().try_into().unwrap();
    //~^ ERROR: useless conversion to the same type: `std::string::String`
    let _: String = TryFrom::try_from("foo".to_string()).unwrap();
    //~^ ERROR: useless conversion to the same type: `std::string::String`
    let _ = String::try_from("foo".to_string()).unwrap();
    //~^ ERROR: useless conversion to the same type: `std::string::String`
    let _ = String::try_from(format!("A: {:04}", 123)).unwrap();
    //~^ ERROR: useless conversion to the same type: `std::string::String`
    let _: String = format!("Hello {}", "world").try_into().unwrap();
    //~^ ERROR: useless conversion to the same type: `std::string::String`
    let _: String = String::new().try_into().unwrap();
    //~^ ERROR: useless conversion to the same type: `std::string::String`
    let _: String = match String::from("_").try_into() {
        //~^ ERROR: useless conversion to the same type: `std::string::String`
        Ok(a) => a,
        Err(_) => String::new(),
    };
    // FIXME this is a false negative
    #[allow(clippy::cmp_owned)]
    if String::from("a") == TryInto::<String>::try_into(String::from("a")).unwrap() {}
}

````
</p>
</details>

Version information
````
rustc 1.82.0-nightly (9b318d2e9 2024-08-17)
binary: rustc
commit-hash: 9b318d2e93ce35e7ba32d8cfa96a1dbe63a7bed1
commit-date: 2024-08-17
host: x86_64-unknown-linux-gnu
release: 1.82.0-nightly
LLVM version: 19.1.0

````

Command:
`/home/matthias/.rustup/toolchains/master/bin/rustc `

<details><summary><strong>Program output</strong></summary>
<p>

```
error[E0601]: `main` function not found in crate `mvce`
 --> /tmp/icemaker_global_tempdir.sXqwjI7Mv8KU/rustc_testrunner_tmpdir_reporting.B11rGugxJB7Z/mvce.rs:3:2
  |
3 | }
  |  ^ consider adding a `main` function to `/tmp/icemaker_global_tempdir.sXqwjI7Mv8KU/rustc_testrunner_tmpdir_reporting.B11rGugxJB7Z/mvce.rs`

error: internal compiler error: compiler/rustc_hir_analysis/src/collect/type_of.rs:582:18: unexpected non-type Node::GenericParam: Type { default: None, synthetic: false }

thread 'rustc' panicked at compiler/rustc_hir_analysis/src/collect/type_of.rs:582:18:
Box<dyn Any>
stack backtrace:
   0:     0x73887d5b28dd - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::hbc01d7b608be4cd7
   1:     0x73887de05157 - core::fmt::write::hb357ae00ad9c5259
   2:     0x73887edbda51 - std::io::Write::write_fmt::h13a24ddc9a1fdb00
   3:     0x73887d5b4fbb - std::panicking::default_hook::{{closure}}::he90538c5db987e04
   4:     0x73887d5b4c2e - std::panicking::default_hook::ha1a531e9b99fa317
   5:     0x73887c747ba9 - std[6cb574a7e0954fac]::panicking::update_hook::<alloc[df4cc1a01d5b065d]::boxed::Box<rustc_driver_impl[8771d5e726c45cf8]::install_ice_hook::{closure#0}>>::{closure#0}
   6:     0x73887d5b58d7 - std::panicking::rust_panic_with_hook::h13cac42622f97635
   7:     0x73887c781f11 - std[6cb574a7e0954fac]::panicking::begin_panic::<rustc_errors[fd70399d2354dc26]::ExplicitBug>::{closure#0}
   8:     0x73887c774f56 - std[6cb574a7e0954fac]::sys::backtrace::__rust_end_short_backtrace::<std[6cb574a7e0954fac]::panicking::begin_panic<rustc_errors[fd70399d2354dc26]::ExplicitBug>::{closure#0}, !>
   9:     0x73887c770336 - std[6cb574a7e0954fac]::panicking::begin_panic::<rustc_errors[fd70399d2354dc26]::ExplicitBug>
  10:     0x73887c78aef1 - <rustc_errors[fd70399d2354dc26]::diagnostic::BugAbort as rustc_errors[fd70399d2354dc26]::diagnostic::EmissionGuarantee>::emit_producing_guarantee
  11:     0x73887cd4e994 - rustc_middle[c3682ad5e92f3c6c]::util::bug::opt_span_bug_fmt::<rustc_span[5d62fad87722a712]::span_encoding::Span>::{closure#0}
  12:     0x73887cd345aa - rustc_middle[c3682ad5e92f3c6c]::ty::context::tls::with_opt::<rustc_middle[c3682ad5e92f3c6c]::util::bug::opt_span_bug_fmt<rustc_span[5d62fad87722a712]::span_encoding::Span>::{closure#0}, !>::{closure#0}
  13:     0x73887cd3445b - rustc_middle[c3682ad5e92f3c6c]::ty::context::tls::with_context_opt::<rustc_middle[c3682ad5e92f3c6c]::ty::context::tls::with_opt<rustc_middle[c3682ad5e92f3c6c]::util::bug::opt_span_bug_fmt<rustc_span[5d62fad87722a712]::span_encoding::Span>::{closure#0}, !>::{closure#0}, !>
  14:     0x73887a823c10 - rustc_middle[c3682ad5e92f3c6c]::util::bug::bug_fmt
  15:     0x73887b2a73e4 - rustc_hir_analysis[25b7da8f6fe9ad06]::collect::type_of::type_of
  16:     0x73887de37530 - rustc_query_impl[f86d883d92ecf329]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[f86d883d92ecf329]::query_impl::type_of::dynamic_query::{closure#2}::{closure#0}, rustc_middle[c3682ad5e92f3c6c]::query::erase::Erased<[u8; 8usize]>>
  17:     0x73887de361e7 - rustc_query_system[bd3380b77d0fd58]::query::plumbing::try_execute_query::<rustc_query_impl[f86d883d92ecf329]::DynamicConfig<rustc_query_system[bd3380b77d0fd58]::query::caches::DefIdCache<rustc_middle[c3682ad5e92f3c6c]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[f86d883d92ecf329]::plumbing::QueryCtxt, false>
  18:     0x73887de35da7 - rustc_query_impl[f86d883d92ecf329]::query_impl::type_of::get_query_non_incr::__rust_end_short_backtrace
  19:     0x73887e2cab11 - rustc_middle[c3682ad5e92f3c6c]::query::plumbing::query_get_at::<rustc_query_system[bd3380b77d0fd58]::query::caches::DefIdCache<rustc_middle[c3682ad5e92f3c6c]::query::erase::Erased<[u8; 8usize]>>>
  20:     0x73887ca8d083 - <rustc_hir_typeck[12bf866448a1086e]::fn_ctxt::FnCtxt>::suggest_traits_to_import
  21:     0x73887ca7a19a - <rustc_hir_typeck[12bf866448a1086e]::fn_ctxt::FnCtxt>::report_no_match_method_error
  22:     0x73887caae2ba - <rustc_hir_typeck[12bf866448a1086e]::fn_ctxt::FnCtxt>::report_method_error
  23:     0x73887e848e90 - <rustc_hir_typeck[12bf866448a1086e]::fn_ctxt::FnCtxt>::check_expr_path
  24:     0x73887e7db898 - <rustc_hir_typeck[12bf866448a1086e]::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
  25:     0x73887e7dcfcd - <rustc_hir_typeck[12bf866448a1086e]::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
  26:     0x73887e7ddaea - <rustc_hir_typeck[12bf866448a1086e]::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
  27:     0x73887e7da304 - <rustc_hir_typeck[12bf866448a1086e]::fn_ctxt::FnCtxt>::check_decl
  28:     0x73887e7d7581 - <rustc_hir_typeck[12bf866448a1086e]::fn_ctxt::FnCtxt>::check_block_with_expected
  29:     0x73887e7dda88 - <rustc_hir_typeck[12bf866448a1086e]::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
  30:     0x73887e03a521 - rustc_hir_typeck[12bf866448a1086e]::check::check_fn
  31:     0x73887e16b41f - rustc_hir_typeck[12bf866448a1086e]::typeck
  32:     0x73887e16ae73 - rustc_query_impl[f86d883d92ecf329]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[f86d883d92ecf329]::query_impl::typeck::dynamic_query::{closure#2}::{closure#0}, rustc_middle[c3682ad5e92f3c6c]::query::erase::Erased<[u8; 8usize]>>
  33:     0x73887e0cb039 - rustc_query_system[bd3380b77d0fd58]::query::plumbing::try_execute_query::<rustc_query_impl[f86d883d92ecf329]::DynamicConfig<rustc_query_system[bd3380b77d0fd58]::query::caches::VecCache<rustc_span[5d62fad87722a712]::def_id::LocalDefId, rustc_middle[c3682ad5e92f3c6c]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[f86d883d92ecf329]::plumbing::QueryCtxt, false>
  34:     0x73887e0ca255 - rustc_query_impl[f86d883d92ecf329]::query_impl::typeck::get_query_non_incr::__rust_end_short_backtrace
  35:     0x73887e0c9edb - <rustc_middle[c3682ad5e92f3c6c]::hir::map::Map>::par_body_owners::<rustc_hir_analysis[25b7da8f6fe9ad06]::check_crate::{closure#4}>::{closure#0}
  36:     0x73887e0c7c24 - rustc_hir_analysis[25b7da8f6fe9ad06]::check_crate
  37:     0x73887e9279ff - rustc_interface[63d22841a2327cf2]::passes::run_required_analyses
  38:     0x73887e95dc9e - rustc_interface[63d22841a2327cf2]::passes::analysis
  39:     0x73887e95dc71 - rustc_query_impl[f86d883d92ecf329]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[f86d883d92ecf329]::query_impl::analysis::dynamic_query::{closure#2}::{closure#0}, rustc_middle[c3682ad5e92f3c6c]::query::erase::Erased<[u8; 1usize]>>
  40:     0x73887ed873ae - rustc_query_system[bd3380b77d0fd58]::query::plumbing::try_execute_query::<rustc_query_impl[f86d883d92ecf329]::DynamicConfig<rustc_query_system[bd3380b77d0fd58]::query::caches::SingleCache<rustc_middle[c3682ad5e92f3c6c]::query::erase::Erased<[u8; 1usize]>>, false, false, false>, rustc_query_impl[f86d883d92ecf329]::plumbing::QueryCtxt, false>
  41:     0x73887ed8710f - rustc_query_impl[f86d883d92ecf329]::query_impl::analysis::get_query_non_incr::__rust_end_short_backtrace
  42:     0x73887ebfa56a - rustc_interface[63d22841a2327cf2]::interface::run_compiler::<core[7c75989f65d16f38]::result::Result<(), rustc_span[5d62fad87722a712]::ErrorGuaranteed>, rustc_driver_impl[8771d5e726c45cf8]::run_compiler::{closure#0}>::{closure#1}
  43:     0x73887eb13690 - std[6cb574a7e0954fac]::sys::backtrace::__rust_begin_short_backtrace::<rustc_interface[63d22841a2327cf2]::util::run_in_thread_with_globals<rustc_interface[63d22841a2327cf2]::util::run_in_thread_pool_with_globals<rustc_interface[63d22841a2327cf2]::interface::run_compiler<core[7c75989f65d16f38]::result::Result<(), rustc_span[5d62fad87722a712]::ErrorGuaranteed>, rustc_driver_impl[8771d5e726c45cf8]::run_compiler::{closure#0}>::{closure#1}, core[7c75989f65d16f38]::result::Result<(), rustc_span[5d62fad87722a712]::ErrorGuaranteed>>::{closure#0}, core[7c75989f65d16f38]::result::Result<(), rustc_span[5d62fad87722a712]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[7c75989f65d16f38]::result::Result<(), rustc_span[5d62fad87722a712]::ErrorGuaranteed>>
  44:     0x73887eb13cfa - <<std[6cb574a7e0954fac]::thread::Builder>::spawn_unchecked_<rustc_interface[63d22841a2327cf2]::util::run_in_thread_with_globals<rustc_interface[63d22841a2327cf2]::util::run_in_thread_pool_with_globals<rustc_interface[63d22841a2327cf2]::interface::run_compiler<core[7c75989f65d16f38]::result::Result<(), rustc_span[5d62fad87722a712]::ErrorGuaranteed>, rustc_driver_impl[8771d5e726c45cf8]::run_compiler::{closure#0}>::{closure#1}, core[7c75989f65d16f38]::result::Result<(), rustc_span[5d62fad87722a712]::ErrorGuaranteed>>::{closure#0}, core[7c75989f65d16f38]::result::Result<(), rustc_span[5d62fad87722a712]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[7c75989f65d16f38]::result::Result<(), rustc_span[5d62fad87722a712]::ErrorGuaranteed>>::{closure#1} as core[7c75989f65d16f38]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  45:     0x73887eb1406b - std::sys::pal::unix::thread::Thread::new::thread_start::h683ced0bc52e6b8c
  46:     0x73888028c39d - <unknown>
  47:     0x73888031149c - <unknown>
  48:                0x0 - <unknown>

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: please make sure that you have updated to the latest nightly

note: rustc 1.82.0-nightly (9b318d2e9 2024-08-17) running on x86_64-unknown-linux-gnu

query stack during panic:
#0 [type_of] computing type of `test_generic::T`
#1 [typeck] type-checking `test_generic`
end of query stack
error: aborting due to 2 previous errors

For more information about this error, try `rustc --explain E0601`.

```

</p>
</details>

### LINKED ISSUE #129216: ICE: `associated type missing default`
auto-reduced (treereduce-rust):
````rust
trait Mirror {
    type Assoc;
}

struct Foo;

fn main() {
    <Foo as Mirror>::Assoc::new();
}


````

original:
````rust
// Check that we if we get ahold of an object unsafe trait
//@ check-pass

trait Mirror {
    type Assoc;
}
impl Priv<Pub> {
        pub fn f(arg: Priv) {} // OK
    }

struct Foo;
impl Foo {
    fn new() -> Self { Foo }
}

fn main() {
    <Foo as Mirror>::Assoc::new();
}

````

Version information
````
rustc 1.82.0-nightly (0f26ee4fd 2024-08-17)
binary: rustc
commit-hash: 0f26ee4fd95a1c046582dfb18892f520788e2c2c
commit-date: 2024-08-17
host: x86_64-unknown-linux-gnu
release: 1.82.0-nightly
LLVM version: 19.1.0

````

Command:
`/home/matthias/.rustup/toolchains/master/bin/rustc `

<details><summary><strong>Program output</strong></summary>
<p>

```
error: internal compiler error: compiler/rustc_hir_analysis/src/collect/type_of.rs:451:17: associated type missing default
 --> /tmp/icemaker_global_tempdir.thuP8tncCjle/rustc_testrunner_tmpdir_reporting.6TKvJE1HmZsD/mvce.rs:2:5
  |
2 |     type Assoc;
  |     ^^^^^^^^^^^

thread 'rustc' panicked at compiler/rustc_hir_analysis/src/collect/type_of.rs:451:17:
Box<dyn Any>
stack backtrace:
   0:     0x7ebe535c429d - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::hce35dec2bed7e8e1
   1:     0x7ebe53e05297 - core::fmt::write::haaf8a728f3019c12
   2:     0x7ebe550bbd91 - std::io::Write::write_fmt::hb0dc5188703aea0d
   3:     0x7ebe535c697b - std::panicking::default_hook::{{closure}}::h35c501ae74c82675
   4:     0x7ebe535c65ee - std::panicking::default_hook::hc1ddd62643c4c855
   5:     0x7ebe52758729 - std[54b021f941472252]::panicking::update_hook::<alloc[8840b3d3a55bb7af]::boxed::Box<rustc_driver_impl[ec4d44b725e7aa11]::install_ice_hook::{closure#0}>>::{closure#0}
   6:     0x7ebe535c7297 - std::panicking::rust_panic_with_hook::h7960ad04eaeb646d
   7:     0x7ebe52793111 - std[54b021f941472252]::panicking::begin_panic::<rustc_errors[2e519a482e3c741a]::ExplicitBug>::{closure#0}
   8:     0x7ebe52786156 - std[54b021f941472252]::sys::backtrace::__rust_end_short_backtrace::<std[54b021f941472252]::panicking::begin_panic<rustc_errors[2e519a482e3c741a]::ExplicitBug>::{closure#0}, !>
   9:     0x7ebe52781536 - std[54b021f941472252]::panicking::begin_panic::<rustc_errors[2e519a482e3c741a]::ExplicitBug>
  10:     0x7ebe5279c0f1 - <rustc_errors[2e519a482e3c741a]::diagnostic::BugAbort as rustc_errors[2e519a482e3c741a]::diagnostic::EmissionGuarantee>::emit_producing_guarantee
  11:     0x7ebe52820b1f - <rustc_errors[2e519a482e3c741a]::DiagCtxtHandle>::span_bug::<rustc_span[a5a4c6b08f7cf6f]::span_encoding::Span, alloc[8840b3d3a55bb7af]::string::String>
  12:     0x7ebe52881528 - rustc_middle[10ec7aec7d9fdda3]::util::bug::opt_span_bug_fmt::<rustc_span[a5a4c6b08f7cf6f]::span_encoding::Span>::{closure#0}
  13:     0x7ebe5288525a - rustc_middle[10ec7aec7d9fdda3]::ty::context::tls::with_opt::<rustc_middle[10ec7aec7d9fdda3]::util::bug::opt_span_bug_fmt<rustc_span[a5a4c6b08f7cf6f]::span_encoding::Span>::{closure#0}, !>::{closure#0}
  14:     0x7ebe52848f9b - rustc_middle[10ec7aec7d9fdda3]::ty::context::tls::with_context_opt::<rustc_middle[10ec7aec7d9fdda3]::ty::context::tls::with_opt<rustc_middle[10ec7aec7d9fdda3]::util::bug::opt_span_bug_fmt<rustc_span[a5a4c6b08f7cf6f]::span_encoding::Span>::{closure#0}, !>::{closure#0}, !>
  15:     0x7ebe52848807 - rustc_middle[10ec7aec7d9fdda3]::util::bug::span_bug_fmt::<rustc_span[a5a4c6b08f7cf6f]::span_encoding::Span>
  16:     0x7ebe5147fba4 - rustc_hir_analysis[c0d9d1e917b71b24]::collect::type_of::type_of
  17:     0x7ebe53e271f0 - rustc_query_impl[69287ea093d06d1d]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[69287ea093d06d1d]::query_impl::type_of::dynamic_query::{closure#2}::{closure#0}, rustc_middle[10ec7aec7d9fdda3]::query::erase::Erased<[u8; 8usize]>>
  18:     0x7ebe53e25ea7 - rustc_query_system[1449707d44461b06]::query::plumbing::try_execute_query::<rustc_query_impl[69287ea093d06d1d]::DynamicConfig<rustc_query_system[1449707d44461b06]::query::caches::DefIdCache<rustc_middle[10ec7aec7d9fdda3]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[69287ea093d06d1d]::plumbing::QueryCtxt, false>
  19:     0x7ebe53e25a67 - rustc_query_impl[69287ea093d06d1d]::query_impl::type_of::get_query_non_incr::__rust_end_short_backtrace
  20:     0x7ebe542f4751 - rustc_middle[10ec7aec7d9fdda3]::query::plumbing::query_get_at::<rustc_query_system[1449707d44461b06]::query::caches::DefIdCache<rustc_middle[10ec7aec7d9fdda3]::query::erase::Erased<[u8; 8usize]>>>
  21:     0x7ebe52a9e0f3 - <rustc_hir_typeck[cd6451a3b3fe12c4]::fn_ctxt::FnCtxt>::suggest_traits_to_import
  22:     0x7ebe52a8b20a - <rustc_hir_typeck[cd6451a3b3fe12c4]::fn_ctxt::FnCtxt>::report_no_match_method_error
  23:     0x7ebe52abf32a - <rustc_hir_typeck[cd6451a3b3fe12c4]::fn_ctxt::FnCtxt>::report_method_error
  24:     0x7ebe5480e190 - <rustc_hir_typeck[cd6451a3b3fe12c4]::fn_ctxt::FnCtxt>::check_expr_path
  25:     0x7ebe54900058 - <rustc_hir_typeck[cd6451a3b3fe12c4]::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
  26:     0x7ebe5490178d - <rustc_hir_typeck[cd6451a3b3fe12c4]::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
  27:     0x7ebe548fad7d - <rustc_hir_typeck[cd6451a3b3fe12c4]::fn_ctxt::FnCtxt>::check_block_with_expected
  28:     0x7ebe54902247 - <rustc_hir_typeck[cd6451a3b3fe12c4]::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
  29:     0x7ebe54043661 - rustc_hir_typeck[cd6451a3b3fe12c4]::check::check_fn
  30:     0x7ebe545fbf1f - rustc_hir_typeck[cd6451a3b3fe12c4]::typeck
  31:     0x7ebe545fb975 - rustc_query_impl[69287ea093d06d1d]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[69287ea093d06d1d]::query_impl::typeck::dynamic_query::{closure#2}::{closure#0}, rustc_middle[10ec7aec7d9fdda3]::query::erase::Erased<[u8; 8usize]>>
  32:     0x7ebe540d4bf9 - rustc_query_system[1449707d44461b06]::query::plumbing::try_execute_query::<rustc_query_impl[69287ea093d06d1d]::DynamicConfig<rustc_query_system[1449707d44461b06]::query::caches::VecCache<rustc_span[a5a4c6b08f7cf6f]::def_id::LocalDefId, rustc_middle[10ec7aec7d9fdda3]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[69287ea093d06d1d]::plumbing::QueryCtxt, false>
  33:     0x7ebe540d3e15 - rustc_query_impl[69287ea093d06d1d]::query_impl::typeck::get_query_non_incr::__rust_end_short_backtrace
  34:     0x7ebe540d3a9b - <rustc_middle[10ec7aec7d9fdda3]::hir::map::Map>::par_body_owners::<rustc_hir_analysis[c0d9d1e917b71b24]::check_crate::{closure#4}>::{closure#0}
  35:     0x7ebe540d17e4 - rustc_hir_analysis[c0d9d1e917b71b24]::check_crate
  36:     0x7ebe54584cbf - rustc_interface[f40e7651e6b02ea1]::passes::run_required_analyses
  37:     0x7ebe5495c49e - rustc_interface[f40e7651e6b02ea1]::passes::analysis
  38:     0x7ebe5495c471 - rustc_query_impl[69287ea093d06d1d]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[69287ea093d06d1d]::query_impl::analysis::dynamic_query::{closure#2}::{closure#0}, rustc_middle[10ec7aec7d9fdda3]::query::erase::Erased<[u8; 1usize]>>
  39:     0x7ebe54d867ee - rustc_query_system[1449707d44461b06]::query::plumbing::try_execute_query::<rustc_query_impl[69287ea093d06d1d]::DynamicConfig<rustc_query_system[1449707d44461b06]::query::caches::SingleCache<rustc_middle[10ec7aec7d9fdda3]::query::erase::Erased<[u8; 1usize]>>, false, false, false>, rustc_query_impl[69287ea093d06d1d]::plumbing::QueryCtxt, false>
  40:     0x7ebe54d8654f - rustc_query_impl[69287ea093d06d1d]::query_impl::analysis::get_query_non_incr::__rust_end_short_backtrace
  41:     0x7ebe54bd38ea - rustc_interface[f40e7651e6b02ea1]::interface::run_compiler::<core[5070cb7ec77c977]::result::Result<(), rustc_span[a5a4c6b08f7cf6f]::ErrorGuaranteed>, rustc_driver_impl[ec4d44b725e7aa11]::run_compiler::{closure#0}>::{closure#1}
  42:     0x7ebe54bb3210 - std[54b021f941472252]::sys::backtrace::__rust_begin_short_backtrace::<rustc_interface[f40e7651e6b02ea1]::util::run_in_thread_with_globals<rustc_interface[f40e7651e6b02ea1]::util::run_in_thread_pool_with_globals<rustc_interface[f40e7651e6b02ea1]::interface::run_compiler<core[5070cb7ec77c977]::result::Result<(), rustc_span[a5a4c6b08f7cf6f]::ErrorGuaranteed>, rustc_driver_impl[ec4d44b725e7aa11]::run_compiler::{closure#0}>::{closure#1}, core[5070cb7ec77c977]::result::Result<(), rustc_span[a5a4c6b08f7cf6f]::ErrorGuaranteed>>::{closure#0}, core[5070cb7ec77c977]::result::Result<(), rustc_span[a5a4c6b08f7cf6f]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[5070cb7ec77c977]::result::Result<(), rustc_span[a5a4c6b08f7cf6f]::ErrorGuaranteed>>
  43:     0x7ebe54bb387a - <<std[54b021f941472252]::thread::Builder>::spawn_unchecked_<rustc_interface[f40e7651e6b02ea1]::util::run_in_thread_with_globals<rustc_interface[f40e7651e6b02ea1]::util::run_in_thread_pool_with_globals<rustc_interface[f40e7651e6b02ea1]::interface::run_compiler<core[5070cb7ec77c977]::result::Result<(), rustc_span[a5a4c6b08f7cf6f]::ErrorGuaranteed>, rustc_driver_impl[ec4d44b725e7aa11]::run_compiler::{closure#0}>::{closure#1}, core[5070cb7ec77c977]::result::Result<(), rustc_span[a5a4c6b08f7cf6f]::ErrorGuaranteed>>::{closure#0}, core[5070cb7ec77c977]::result::Result<(), rustc_span[a5a4c6b08f7cf6f]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[5070cb7ec77c977]::result::Result<(), rustc_span[a5a4c6b08f7cf6f]::ErrorGuaranteed>>::{closure#1} as core[5070cb7ec77c977]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  44:     0x7ebe54bb3beb - std::sys::pal::unix::thread::Thread::new::thread_start::he8fde62ed04f9a93
  45:     0x7ebe5635e39d - <unknown>
  46:     0x7ebe563e349c - <unknown>
  47:                0x0 - <unknown>

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: please make sure that you have updated to the latest nightly

note: rustc 1.82.0-nightly (0f26ee4fd 2024-08-17) running on x86_64-unknown-linux-gnu

query stack during panic:
#0 [type_of] computing type of `Mirror::Assoc`
#1 [typeck] type-checking `main`
end of query stack
error: aborting due to 1 previous error


```

</p>
</details>

### PR DESCRIPTION
**Pull request by estebank**
When looking for multiple versions of the same crate, do not blindly construct the receiver type.

Follow up to #128786. 
Fixes #129205
Fixes #129216

### CODE REVIEW

File: tests/ui/methods/missing-method-on-type-parameter.rs [hunk 1]
```diff
@@ -0,0 +1,5 @@
+fn x<T: Copy>() {
```
Comment (jieyouxu) [inline tests/ui/methods/missing-method-on-type-parameter.rs:1]: Suggestion: this looks like a regression test minimized from the ICE issue. Could we link to it here?

**Comment by Nadrieril** [comment]
r? compiler

File: compiler/rustc_hir_typeck/src/method/suggest.rs [hunk 2]
```diff
@@ -3700,7 +3700,13 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
             // See if the `Type::function(val)` where `function` wasn't found corresponds to a
             // `Trait` that is imported directly, but `Type` came from a different version of the
             // same crate.
-            let rcvr_ty = self.tcx.type_of(def_id).instantiate_identity();
+
+            let rcvr_ty = match self.tcx.def_kind(def_id) {
```
Comment (compiler-errors) [inline compiler/rustc_hir_typeck/src/method/suggest.rs:3704]: Leave a comment explaining what kinds of `DefKind`s you're actually trying to avoid here. It makes it look less like you just forgot some special cases.

Comment (compiler-errors) [reply compiler/rustc_hir_typeck/src/method/suggest.rs:3704]: Also, why *are* we doing this? Why can't we just look at the `node_ty` of the `TyKind::Path` above? That would handle the non-ADT cases too, no?

**Review by compiler-errors — CHANGES_REQUESTED** [review]

File: compiler/rustc_hir_typeck/src/method/suggest.rs (hunk 2 above)
Comment (estebank) [reply compiler/rustc_hir_typeck/src/method/suggest.rs]: done

**Comment by jieyouxu** [comment]
Failed in https://github.com/rust-lang/rust/pull/129348#issuecomment-2301509118

```
[crashes] tests/crashes/129205.rs ... F
[crashes] tests/crashes/129216.rs ... F
```

Probably need to remove these tests or convert to ui tests.

@bors r-

**Comment by jieyouxu** [comment]
Maybe this PR also fixes https://github.com/rust-lang/rust/issues/129216?

**Comment by gurry** [comment]
> Maybe this PR also fixes #129216?

Yes, it should as the ICE in #129216 occurred inside the call to `type_of` and that call is removed now.

**Comment by compiler-errors** [comment]
I've rebased and removed the offending crashes. I don't think needs more tests, since they're exercising the same codepath (param has no type_of).

@bors r+ rollup

**Comment by matthiaskrgr** [comment]
(ive updated pr header to autotclose the other crashtest issue as well)
