### PR TITLE
Rustdoc-Json: Don't remove impls for items imported from private modules

### LINKED ISSUE #100242: rustdoc `--json` struct and enum impls are blank
running `	rustup run nightly cargo rustdoc -p glam --  -Zunstable-options --output-format json`

produces this record for the [glam](https://docs.rs/glam/latest/glam/f32/struct.Mat3.html) type `Mat3`:
```json
         "0:9614:1735": {
            "id": "0:9614:1735",
            "crate_id": 0,
            "name": "Mat3",
            "span": {
                "filename": "/home/makspll/.cargo/registry/src/github.com-1ecc6299db9ec823/glam-0.21.2/src/f32/mat3.rs",
                "begin": [
                    45,
                    0
                ],
                "end": [
                    49,
                    1
                ]
            },
            "visibility": "public",
            "docs": "A 3x3 column major matrix.\n\nThis 3x3 matrix type features convenience methods for creating and using linear and\naffine transformations. If you are primarily dealing with 2D affine transformations the\n[`Affine2`](crate::Affine2) type is much faster and more space efficient than\nusing a 3x3 matrix.\n\nLinear transformations including 3D rotation and scale can be created using methods\nsuch as [`Self::from_diagonal()`], [`Self::from_quat()`], [`Self::from_axis_angle()`],\n[`Self::from_rotation_x()`], [`Self::from_rotation_y()`], or\n[`Self::from_rotation_z()`].\n\nThe resulting matrices can be use to transform 3D vectors using regular vector\nmultiplication.\n\nAffine transformations including 2D translation, rotation and scale can be created\nusing methods such as [`Self::from_translation()`], [`Self::from_angle()`],\n[`Self::from_scale()`] and [`Self::from_scale_angle_translation()`].\n\nThe [`Self::transform_point2()`] and [`Self::transform_vector2()`] convenience methods\nare provided for performing affine transforms on 2D vectors and points. These multiply\n2D inputs as 3D vectors with an implicit `z` value of `1` for points and `0` for\nvectors respectively. These methods assume that `Self` contains a valid affine\ntransform.",
            "links": {
                "crate::Affine2": "0:9602:2046",
                "`Self::from_diagonal()`": "0:9614:1735",
                "`Self::from_axis_angle()`": "0:9614:1735",
                "`Self::from_scale()`": "0:9614:1735",
                "`Self::from_angle()`": "0:9614:1735",
                "`Self::from_quat()`": "0:9614:1735",
                "`Self::from_rotation_z()`": "0:9614:1735",
                "`Self::transform_vector2()`": "0:9614:1735",
                "`Self::from_rotation_y()`": "0:9614:1735",
                "`Self::from_scale_angle_translation()`": "0:9614:1735",
                "`Self::from_rotation_x()`": "0:9614:1735",
                "`Self::from_translation()`": "0:9614:1735",
                "`Self::transform_point2()`": "0:9614:1735"
            },
            "attrs": [
                "#[repr(C)]"
            ],
            "deprecation": null,
            "kind": "struct",
            "inner": {
                "struct_type": "plain",
                "generics": {
                    "params": [],
                    "where_predicates": []
                },
                "fields_stripped": false,
                "fields": [
                    "0:9615:1809",
                    "0:9616:1810",
                    "0:9617:1812"
                ],
                "impls": []
            }
        }
```

I would expect "impls" to not be blank, since the matrix implements many traits and has a non-trait implementation as well. The paths entry also does not contain `Mat3` as well as many other types exported by the crate, is this expected ? I know that these paths included all exported types before 

### Meta
`rustc --version --verbose`:
```
$ rustup run nightly rustc --version
rustc 1.65.0-nightly (2befdefdd 2022-08-06)
```
### Meta
`rustc --version --verbose`:
```
$ rustup run nightly rustc --version
rustc 1.65.0-nightly (2befdefdd 2022-08-06)
```

### LINKED ISSUE #100252: Rustdoc JSON might not report all implemented traits on a public type
Given a public type, I expected all traits implemented by that type to be part of rustdoc JSON output.

However, rustdoc JSON output sometimes does not include information about all the traits implemented by a type unless `--document-private-items` is specified.

For example, in this `clap` [semver regression](https://github.com/clap-rs/clap/issues/3876):
- The following invocation on v3.1.18 generates JSON stating that `UnwindSafe` is implemented for `ArgMatches`: `cargo rustdoc --lib --all-features -- --document-private-items -Zunstable-options --output-format json`
- However, the following invocation has no mention of `UnwindSafe` for `ArgMatches` at all: `cargo rustdoc --lib --all-features -- -Zunstable-options --output-format json`

Related to:
https://github.com/obi1kenobi/cargo-semver-check/issues/32

### Meta

`rustc --version --verbose`:
```
rustc 1.64.0-nightly (93ffde6f0 2022-07-23)
binary: rustc
commit-hash: 93ffde6f04d3d24327a4e17a2a2bf4f63c246235
commit-date: 2022-07-23
host: x86_64-unknown-linux-gnu
release: 1.64.0-nightly
LLVM version: 14.0.6
```

### PR DESCRIPTION
**Pull request by aDotInTheVoid**
After #99287, items in private modules may still be in the json output, if a public import accesses them. To reflect this, items that are imported need to be marked as retained in the `Stripper` pass, so their impls arn't removed by `ImplStripper`.

[More context on zulip](https://rust-lang.zulipchat.com/#narrow/stream/266220-rustdoc/topic/Populating.20cache.2Eimpls), thanks to @ jyn514 for helping debug this.

@rustbot modify labels: +A-rustdoc-json +T-rustdoc

r? @GuillaumeGomez 

Fixes #100252
Fixes #100242

### CODE REVIEW

**Review by jyn514 — APPROVED** [review]

File: src/librustdoc/passes/stripper.rs [hunk 1]
```diff
@@ -84,7 +84,14 @@ impl<'a> DocFolder for Stripper<'a> {
             }
 
             // handled in the `strip-priv-imports` pass
-            clean::ExternCrateItem { .. } | clean::ImportItem(..) => {}
+            clean::ExternCrateItem { .. } => {}
+            clean::ImportItem(ref imp) => {
+                // Because json doesn't inline imports from private modules, we need to mark
+                // the imported item as retained so it's impls won't be stripped.
+                if let Some(did) = imp.source.did {
+                    self.retained.insert(did.into());
```
[the remark this answers is not in the document]
Comment (aDotInTheVoid) [reply src/librustdoc/passes/stripper.rs:92]: I don't think so, as HTML shouldn't have imports to items that arn't retained at this point, due to the `strip-priv-imports` pass. It also passes all rustdoc html/ui/gui/js tests, but I'm not sure how comprehensive these are.

[the remark this answers is not in the document]
Comment (GuillaumeGomez) [reply src/librustdoc/passes/stripper.rs:92]: It's mostly testing that something exists. It's hard to confirm in prevision for something that doesn't and shouldn't exist.

[the remark this answers is not in the document]
Comment (GuillaumeGomez) [reply src/librustdoc/passes/stripper.rs:92]: I'd feel more at ease if you added a check for the JSON format. You already have this information in `self.is_json_output`.

File: src/librustdoc/passes/stripper.rs [hunk 2]
```diff
@@ -84,7 +84,17 @@ impl<'a> DocFolder for Stripper<'a> {
             }
 
             // handled in the `strip-priv-imports` pass
-            clean::ExternCrateItem { .. } | clean::ImportItem(..) => {}
+            clean::ExternCrateItem { .. } => {}
+            clean::ImportItem(ref imp) => {
+                // Because json doesn't inline imports from private modules, we need to mark
+                // the imported item as retained so it's impls won't be stripped.i
+                //
+                // FIXME: Is it nessessary to check for json output here: See
```
Comment (GuillaumeGomez) [inline src/librustdoc/passes/stripper.rs:92]: Nitpicking:

```suggestion
                // FIXME: Is it necessary to check for json output here: See
```

File: src/librustdoc/passes/stripper.rs [hunk 3]
```diff
@@ -84,7 +84,17 @@ impl<'a> DocFolder for Stripper<'a> {
...
+                // https://github.com/rust-lang/rust/pull/100325#discussion_r941495215
+                if let Some(did) = imp.source.did && self.is_json_output {
```
Comment (GuillaumeGomez) [inline src/librustdoc/passes/stripper.rs:94]: I didn't know you could do that. :o

**Review by GuillaumeGomez — APPROVED** [review]

**Comment by GuillaumeGomez** [comment]
Looks good to me, thanks! I'll r+ once CI pass.

File: src/librustdoc/passes/stripper.rs (hunk 3 above)
Comment (aDotInTheVoid) [reply src/librustdoc/passes/stripper.rs:94]: Not on stable yet, but `let_chains` are dope!

Comment (GuillaumeGomez) [reply src/librustdoc/passes/stripper.rs:94]: Indeed!
