### PR TITLE
Specify macro is invalid in certain contexts

### LINKED ISSUE #113766: Cannot use `=>` inside the body of a macro_rules for defining match arms
I tried this code:

```rust
enum MyEnum {
    A(i32),
    B(i32),
    C(i32)
}

macro_rules! broken {
    ($n:ident) => { MyEnum::$n(n) => n }
}

fn main() {
    let e = MyEnum::A(1);
    
    match e {
        broken!(A),
        broken!(B),
        broken!(C),
    }
}
```

<details><summary>Cargo expand output</summary>

```rs
#![feature(prelude_import)]
#[prelude_import]
use std::prelude::rust_2021::*;
#[macro_use]
extern crate std;
enum MyEnum {
    A(i32),
    B(i32),
    C(i32),
}
fn main() {
    let e = MyEnum::A(1);
    match e {}
}
```
</details>

I expected to see this happen: It compiles successfully, generating my match arms.

Instead, this happened: Match arms are eaten in macro expansion (according to intellij-rust, as cargo-expand doesn't even show anything) - if I wrap the arm in () within the macro definition (i.e. `(a => b)`), it works, but this is not a valid match arm.

My understanding is that the macro is getting confused with the pattern:
```rs
macro_rules! my_macro {
    () => { () => {} }
}
```
It appears to see `) => { (` as a pattern

### Meta

`rustc --version --verbose`:
```
rustc 1.71.0 (8ede3aae2 2023-07-12)
binary: rustc
commit-hash: 8ede3aae28fe6e4d52b38157d7bfe0d3bceef225
commit-date: 2023-07-12
host: x86_64-unknown-linux-gnu
release: 1.71.0
LLVM version: 16.0.5
```

<details><summary>Backtrace</summary>
<p>

```
❯ RUST_BACKTRACE=1 cargo build
   Compiling qwe v0.1.0 (/home/silvea/qwe)
error: unexpected `,` in pattern
  --> src/main.rs:15:19
   |
15 |         broken!(A),
   |                   ^
   |
help: try adding parentheses to match on a tuple...
   |
15 ~         (broken!(A),
16 |         broken!(B),
17 ~         broken!(C),)
   |
help: ...or a vertical bar to match on multiple alternatives
   |
15 ~         broken!(A) |
16 +         broken!(B) |
17 +         broken!(C) |
   |

warning: unused macro definition: `broken`
 --> src/main.rs:7:14
  |
7 | macro_rules! broken {
  |              ^^^^^^
  |
  = note: `#[warn(unused_macros)]` on by default

warning: `qwe` (bin "qwe") generated 1 warning
error: could not compile `qwe` (bin "qwe") due to previous error; 1 warning emitted
```

</p>
</details>

### PR DESCRIPTION
**Pull request by Centri3**
Adds a note when a macro is used where it really shouldn't be.

Closes #113766

### CODE REVIEW

File: tests/ui/parser/macro/macro-expand-to-field.rs [hunk 1]
```diff
@@ -0,0 +1,57 @@
...
+
+enum EnumVariant {
+    variant!(whoops), //~ NOTE macros cannot expand to enum variants
+    //~^ ERROR unexpected token: `!`
+    //~^^ NOTE unexpected token after this
+    U32,
+    F64,
+    variant!(recovers), //~ NOTE macros cannot expand to enum variants
+    //~^ ERROR unexpected token: `!`
+    //~^^ NOTE unexpected token after this
```
Comment (wesleywiser) [inline tests/ui/parser/macro/macro-expand-to-field.rs:34]: Maybe also add a test for

```
    Data {
        field!(x: u32),
    }
```

**Review by wesleywiser — APPROVED** [review]
