### PR TITLE
Don't copy llvm tools to sysroot when using download-ci-llvm

### LINKED ISSUE #91710: Missing tools in LLVM CI tarball
I've rebased this morning and I can't build the repo anymore since #91685 landed.

```
Copy "/Users/nox/src/rust/build/x86_64-apple-darwin/ci-llvm/bin/llvm-dwp" to "/Users/nox/src/rust/build/x86_64-apple-darwin/stage1/lib/rustlib/x86_64-apple-darwin/bin/rust-llvm-dwp"
Copy "/Users/nox/src/rust/build/x86_64-apple-darwin/ci-llvm/bin/llvm-cov" to "/Users/nox/src/rust/build/x86_64-apple-darwin/stage1/lib/rustlib/x86_64-apple-darwin/bin/llvm-cov"
Copy "/Users/nox/src/rust/build/x86_64-apple-darwin/ci-llvm/bin/llvm-nm" to "/Users/nox/src/rust/build/x86_64-apple-darwin/stage1/lib/rustlib/x86_64-apple-darwin/bin/llvm-nm"
thread 'main' panicked at 'src.symlink_metadata() failed with No such file or directory (os error 2)', src/bootstrap/lib.rs:1324:24
```

It seems there are missing tools in the LLVM CI tarball.

AFAICT, these are the tools CI copies in the tarball:

https://github.com/rust-lang/rust/blob/3b263ceb5cb89b6d53b5a03b47ec447c3a7f7765/src/bootstrap/dist.rs#L2077-L2087

And these are the tools bootstrap tries to install in `build/`:

https://github.com/rust-lang/rust/blob/3b263ceb5cb89b6d53b5a03b47ec447c3a7f7765/src/bootstrap/compile.rs#L1169-L1177

`LLVM_TOOLS` being defined as:

https://github.com/rust-lang/rust/blob/3b263ceb5cb89b6d53b5a03b47ec447c3a7f7765/src/bootstrap/lib.rs#L172-L186

As you can see, there are many tools in `LLVM_TOOLS` that are not included in that `dist` step shown above.

I'm on macOS, and here is the list of tools that I found in the downloaded LLVM CI tarball:

```
± tar tf build/cache/llvm-09d8a50ea26df391b58373e22f5891740efdd6cc-False/rust-dev-nightly-x86_64-apple-darwin.tar.xz 'rust-dev-nightly-*/rust-dev/bin/'
rust-dev-nightly-x86_64-apple-darwin/rust-dev/bin
rust-dev-nightly-x86_64-apple-darwin/rust-dev/bin/llvm-profdata
rust-dev-nightly-x86_64-apple-darwin/rust-dev/bin/lld
rust-dev-nightly-x86_64-apple-darwin/rust-dev/bin/llvm-config
rust-dev-nightly-x86_64-apple-darwin/rust-dev/bin/FileCheck
rust-dev-nightly-x86_64-apple-darwin/rust-dev/bin/llvm-objdump
rust-dev-nightly-x86_64-apple-darwin/rust-dev/bin/llvm-dwp
rust-dev-nightly-x86_64-apple-darwin/rust-dev/bin/llvm-ar
rust-dev-nightly-x86_64-apple-darwin/rust-dev/bin/llvm-bcanalyzer
rust-dev-nightly-x86_64-apple-darwin/rust-dev/bin/llvm-cov
```

Cc @Aaron1011 who authored #91685.

### PR DESCRIPTION
**Pull request by Aaron1011**
Fixes #91710

### CODE REVIEW

File: src/bootstrap/compile.rs [hunk 1]
```diff
@@ -1166,14 +1166,18 @@ impl Step for Assemble {
...
-                // Since we've already built the LLVM tools, install them to the sysroot.
-                // This is the equivalent of installing the `llvm-tools-preview` component via
-                // rustup, and lets developers use a locally built toolchain to
-                // build projects that expect llvm tools to be present in the sysroot
-                // (e.g. the `bootimage` crate).
-                for tool in LLVM_TOOLS {
-                    let tool_exe = exe(tool, target_compiler.host);
-                    builder.copy(&llvm_bin_dir.join(&tool_exe), &libdir_bin.join(&tool_exe));
+                // Not all LLVM tools are available when downloaded from CI,
+                // so don't try to copy them to the sysroot
```
Comment (Mark-Simulacrum) [inline src/bootstrap/compile.rs:1170]: Can we opportunistically copy the ones that are available instead? I would prefer to not have entirely differing behavior with llvm-from-ci, since that seems particularly inconvenient. (If we're missing a few tools that seems better!)

**Comment by Aaron1011** [comment]
@Mark-Simulacrum I've updated the PR to copy each tool that exists on disk.

File: src/bootstrap/compile.rs [hunk 2]
```diff
@@ -1173,7 +1173,12 @@ impl Step for Assemble {
                 // (e.g. the `bootimage` crate).
                 for tool in LLVM_TOOLS {
                     let tool_exe = exe(tool, target_compiler.host);
-                    builder.copy(&llvm_bin_dir.join(&tool_exe), &libdir_bin.join(&tool_exe));
+                    let src_path = llvm_bin_dir.join(&tool_exe);
+                    // When using `donwload-ci-llvm`, some of the tools
```
Comment (bjorn3) [inline src/bootstrap/compile.rs:1177]: *download
