### PR TITLE
fix pthread-based tls on apple targets

### LINKED ISSUE #127773: Unresolved imports when building std without thread local
Doing the following:
```
rustc --print target-spec-json --target aarch64-apple-darwin -Z unstable-options > t.json
change is-builtin and has-thread-local to false in the json
cargo b -Z build-std=std,core,panic_unwind --target t.json
```

I expected to see this happen: it compiles

Instead, this happened:
```
error[E0432]: unresolved imports `crate::sys::thread_local::key::get`, `crate::sys::thread_local::key::set`, `crate::sys::thread_local::key::Key`, `crate::sys::thread_local::key::LazyKey`
 --> /Users/x/.rustup/toolchains/nightly-aarch64-apple-darwin/lib/rustlib/src/rust/library/std/src/sys/thread_local/os.rs:5:37
  |
5 | use crate::sys::thread_local::key::{get, set, Key, LazyKey};
  |                                     ^^^  ^^^  ^^^  ^^^^^^^ no `LazyKey` in `sys::thread_local::key`
  |                                     |    |    |
  |                                     |    |    no `Key` in `sys::thread_local::key`
  |                                     |    no `set` in `sys::thread_local::key`
  |                                     no `get` in `sys::thread_local::key`
  |
note: module `crate::collections::hash::set` exists but is inaccessible
 --> /Users/x/.rustup/toolchains/nightly-aarch64-apple-darwin/lib/rustlib/src/rust/library/std/src/collections/hash/mod.rs:4:1
  |
4 | pub mod set;
  | ^^^^^^^^^^^^ not accessible
```

This used to work on nightly versions from last year.

### Meta

`rustc --version --verbose`:
```
rustc 1.81.0-nightly (d9284afea 2024-07-14)
binary: rustc
commit-hash: d9284afea99e0969a0e692b9e9fd61ea4ba21366
commit-date: 2024-07-14
host: aarch64-apple-darwin
release: 1.81.0-nightly
LLVM version: 18.1.7
```

### PR DESCRIPTION
**Pull request by xTachyon**
Tries to fix #127773.

### CODE REVIEW

**Comment by jieyouxu** [comment]
r? libs

File: tests/run-make/apple-slow-tls/rmake.rs [hunk 1]
```diff
@@ -0,0 +1,28 @@
...
+
+    cargo()
+        .current_dir("tls_test")
+        .args(["b", "--target", "../t.json", "-Zbuild-std=std,core,panic_abort"])
+        .run();
+
+    let output = cmd("nm").arg("tls_test/target/t/debug/tls_test").run().stdout_utf8();
+    // If a binary has any fast TLS variables, it should also contain the symbols
+    // __tlv_bootstrap and __tlv_atexit. We don't want them.
+    assert!(!output.contains("__tlv_bootstrap"));
```
Comment (jieyouxu) [inline tests/run-make/apple-slow-tls/rmake.rs:27]: Discussion: hm, this check is quite loose. Can the `__tlv_bootstrap` and `__tlv_atexit` symbols possibly get prepended by an *additional* `_`? You may want to use e.g. `object` and check for symbols that end with `tlv_{bootstrap,atexit}` instead.

File: tests/run-make/apple-slow-tls/rmake.rs [hunk 2]
```diff
@@ -0,0 +1,28 @@
...
+    assert!(output.contains(to_search));
+    let output = output.replace(to_search, r#""has-thread-local": false"#);
+
+    let out_path = "t.json";
+    rfs::write(out_path, output);
+
+    cargo()
+        .current_dir("tls_test")
+        .args(["b", "--target", "../t.json", "-Zbuild-std=std,core,panic_abort"])
+        .run();
```
Comment (jieyouxu) [inline tests/run-make/apple-slow-tls/rmake.rs:22]: Remark: this involves building the *full* std just for checking this specifically.

File: tests/run-make/apple-slow-tls/rmake.rs [hunk 3]
```diff
@@ -0,0 +1,28 @@
...
+
+    let output = cmd("nm").arg("tls_test/target/t/debug/tls_test").run().stdout_utf8();
```
Comment (jieyouxu) [inline tests/run-make/apple-slow-tls/rmake.rs:24]: Problem: please do not use system `nm`, use at least `run_make_support::llvm_nm` or better `object`-the-crate.

File: tests/run-make/apple-slow-tls/rmake.rs [hunk 4]
```diff
@@ -0,0 +1,28 @@
...
+    // If a binary has any fast TLS variables, it should also contain the symbols
+    // __tlv_bootstrap and __tlv_atexit. We don't want them.
```
Comment (jieyouxu) [inline tests/run-make/apple-slow-tls/rmake.rs:26]: Problem: note that the check below does *not* check for `__tlv_atexit`. Is that intentional?

File: tests/run-make/apple-slow-tls/rmake.rs (hunk 2 above)
Comment (jieyouxu) [inline tests/run-make/apple-slow-tls/rmake.rs:22]: Problem: please explicitly specify the `--manifest-path` to point to `tls_test/Cargo.toml`.

File: tests/run-make/apple-slow-tls/rmake.rs [hunk 5]
```diff
@@ -0,0 +1,28 @@
...
+
+use run_make_support::run::cmd;
+use run_make_support::{cargo, rfs, rustc};
+
+fn main() {
+    let output =
+        rustc().print("target-spec-json").args(["-Z", "unstable-options"]).run().stdout_utf8();
+    let to_search = r#""has-thread-local": true"#;
+    assert!(output.contains(to_search));
+    let output = output.replace(to_search, r#""has-thread-local": false"#);
```
Comment (jieyouxu) [inline tests/run-make/apple-slow-tls/rmake.rs:14]: Nit: I believe [`run_make_support` does re-export `serde_json`](https://doc.rust-lang.org/nightly/nightly-rustc/run_make_support/index.html), consider using structured JSON manipulation instead of plain-text replacement.

**Review by jieyouxu — CHANGES_REQUESTED** [review]
Not a libs reviewer, only looked at the test changes

**Comment by jieyouxu** [comment]
Re-rolling a libs reviewer since you may be busy, but feel free to take review back.
r? libs

File: tests/run-make/apple-slow-tls/rmake.rs (hunk 2 above)
Comment (xTachyon) [reply tests/run-make/apple-slow-tls/rmake.rs:22]: Is that a dealbreaker?

Comment (jieyouxu) [reply tests/run-make/apple-slow-tls/rmake.rs:22]: It is not, which is why the comment was a remark.

File: tests/run-make/apple-slow-tls/rmake.rs (hunk 1 above)
Comment (xTachyon) [reply tests/run-make/apple-slow-tls/rmake.rs]: I looked at the `object` crate, but it seemed a bit scary to use, so I went with `llvm_nm`, and searching for symbols with just one prefix underscore.

File: tests/run-make/apple-slow-tls/rmake.rs (hunk 5 above)
Comment (xTachyon) [reply tests/run-make/apple-slow-tls/rmake.rs]: I was expecting it also reexports `serde`, but it didn't :(

**Review by jieyouxu — APPROVED** [review]
The test looks fine to me. Since there might be some more apple perf discussions, I'll hand this review back.

**Comment by xTachyon** [comment]
r @Noratrieb
