### PR TITLE
MIR-borrowck: moves of prefixes invalidate uses too

### LINKED ISSUE #44833: MIR-borrowck: (unsound) fails to see error in borrowck-init-in-fru.rs
Many MIR-borrowck bugs have been categorized as either extra errors or poor diagnostics, but this is a case where MIR borrowck is simply failing to flag *the* main error in the code in question.

We see below that AST-borrowck is flagging the error while MIR-borrowck says nothing. (This is *atop* the mir-borrowck4 branch from https://github.com/rust-lang/rust/pull/44736 )

```
% ./objdir-dbgopt/build/x86_64-unknown-linux-gnu/stage1/bin/rustc -Z emit-end-regions \
    -Z borrowck-mir ./src/test/compile-fail/borrowck/borrowck-init-in-fru.rs
error[E0381]: use of possibly uninitialized variable: `origin.y` (Ast)
  --> ./src/test/compile-fail/borrowck/borrowck-init-in-fru.rs:19:30
   |
19 |     origin = point {x: 10,.. origin}; //~ ERROR use of possibly uninitialized variable: `origin.y`
   |                              ^^^^^^ use of possibly uninitialized `origin.y`

error: aborting due to previous error
```

### PR DESCRIPTION
**Pull request by pnkfelix**
I overlooked the fact that when we check if a path is moved, we need to check for interference between the (shallow) prefixes and the use in question.

~~Long term, we may want to revise how this computation is done. For example, it might be better to represent the set of invalidated prefixes in the dataflow computation (the `maybe_uninitialized` dataflow), and thus avoid one of the loops in the code here.~~
 * Update: I was wrong in my original recollection of the dataflow code, which actually does the right thing, in terms of precisely tracking substructure initialization and movement.

Fix #44833

----

Update: The initial version of this PR's description (and the code as well) erroneously focused on supporting prefixes. ~~But the two main cases of interest are: 1. the *shallow* prefixes, and 2. the deref-free prefix built off a local (if the lvalue is indeed built off a local)~~

Update 2: The main cases of interest are in fact: 1. the nearest prefix with a MovePath, and 2. the suffixes.

### CODE REVIEW

File: src/test/compile-fail/borrowck/borrowck-uninit-field-access.rs [hunk 1]
```diff
@@ -0,0 +1,49 @@
...
+fn main() {
+    let mut a: Point;
+    let _ = a.x + 1; //[ast]~ ERROR use of possibly uninitialized variable: `a.x`
+                     //[mir]~^ ERROR       [E0381]
+                     //[mir]~| ERROR (Mir) [E0381]
+
+    let mut line1 = Line::default();
+    let _moved = line1.origin;
+    let _ = line1.origin.x + 1; //[ast]~ ERROR use of collaterally moved value: `line1.origin.x`
+                                //[mir]~^       [E0382]
```
Comment (pnkfelix) [inline src/test/compile-fail/borrowck/borrowck-uninit-field-access.rs]: (yes, I do see that the error code here don't match. I also know that we're missing the "(Ast)" in the output from the ast-borrowcker when running under `-Z borrowck-mir`. I want to fix both of those things, but it need not be in this PR.)

**Comment by pnkfelix** [comment]
Muchas gracias to @mikhail-m1 for narrowing this down to such a small example! That really helped me quickly identify the cause.

**Comment by arielb1** [comment]
I'm not sure this is correct:
```Rust
        // A move of any *supporting prefix* of `lvalue` interferes
        // with an attempt to use `lvalue`. This is scenarios 1 and 2
        // above; and we are looking only at the supporting prefixes
        // because of scenario 5 above.
```

You shouldn't be able to write:
```Rust
let x: &&_;
let y= &**x;
```

@bors r-

I think the reason this patch is needed is because the move-path code does not try to handle things behind (non-`Box`) references. IIRC the right way to handle this is to use the mpi (possibly in a `LookupResult::Parent`) returned by `MovePathLookup::find` and to check all of its children using `on_all_children_bits`.

Of course, I should have added comments there when I first rewrote that code, but I wasn't sure how close MIR borrowck was then.

**Comment by pnkfelix** [comment]
@arielb1 wrote:

> I'm not sure this is correct:
> ```Rust
>         // A move of any *supporting prefix* of `lvalue` interferes
>         // with an attempt to use `lvalue`. This is scenarios 1 and 2
>         // above; and we are looking only at the supporting prefixes
>         // because of scenario 5 above.
> ```

Just to be clear: Am I correct that the part of that paragraph that you object to is the "we are looking only at the supporting prefixes because of scenario 5 above", right?

I.e., that you think there are reasons that we need to consider even the prefixes that are non-supporting, and that is why you have given your example of

```rust
let x: &&_;
let y= &**x;
``` 

Does that all sound correct?

(I'm not arguing with the example. I'm just wrapping my head around where that case was meant to fall in my mental model of the analysis.)

**Comment by arielb1** [comment]
> Just to be clear: Am I correct that the part of that paragraph that you object to is the "we are looking only at the supporting prefixes because of scenario 5 above", right?

Right

**Comment by pnkfelix** [comment]
After discussion with @arielb1, I am going to try to handle a generalization of the scenario he presented above. Namely, partial initialization like:

```rust
let x: S; x.a = 0; use(&x.a);
```
 
(where in general `S` does not implement `Drop` but may have fields beyond `a`)

File: src/librustc_mir/borrow_check.rs [hunk 2]
```diff
@@ -615,29 +615,106 @@ impl<'c, 'b, 'a: 'b+'c, 'gcx, 'tcx: 'a> MirBorrowckCtxt<'c, 'b, 'a, 'gcx, 'tcx>
...
+            // support partial (re)inits).
+            //
+            // (I.e. querying parents breaks scenario 8; but may want
+            // to do such a query based on partial-init feature-gate.)
+        }
+
+        // A move of any shallow suffix of `lvalue` also interferes
+        // with an attempt to use `lvalue`. This is scenario 3 above.
+        //
+        // (Distinct from previous loop because `lvalue` does not
```
Comment (pnkfelix) [inline src/librustc_mir/borrow_check.rs]: nit: "previous loop" is confusing here. (The code has been internally refactored so that there is no longer a loop immediately present above, because its been factored into a helper method.)

File: src/librustc_mir/borrow_check.rs [hunk 3]
```diff
@@ -615,29 +615,106 @@ impl<'c, 'b, 'a: 'b+'c, 'gcx, 'tcx: 'a> MirBorrowckCtxt<'c, 'b, 'a, 'gcx, 'tcx>
...
+                if maybe_uninits.curr_state.contains(&mpi) {
+                    // find and report move(s) that could cause this to be uninitialized
+                    self.report_use_of_moved(context, desired_action, lvalue_span);
+                    return; // don't bother finding other problems.
+                }
             }
         }
     }
 
+    fn move_path_closest_to(&mut self,
```
Comment (nikomatsakis) [inline src/librustc_mir/borrow_check.rs]: It would be helpful, I think, to explain what this does, and also to cover the cases in which it might return `None`. Not having read into this code recently, it's sort of not obvious to me -- for example -- why the code above can do

```rust
if let Some(mpi) = ... {
    report_error()
}
```

i.e., why is it that a `None` return value means "no error" and not "definite error"?

File: src/librustc_mir/borrow_check.rs [hunk 4]
```diff
@@ -615,29 +615,106 @@ impl<'c, 'b, 'a: 'b+'c, 'gcx, 'tcx: 'a> MirBorrowckCtxt<'c, 'b, 'a, 'gcx, 'tcx>
...
+        debug!("check_if_path_is_moved part3 lvalue: {:?}", lvalue);
+        if let Some(longest_deref_free) = max_deref_free_locally_rooted_prefix_of(lvalue) {
+            debug!("check_if_path_is_moved part3 longest_deref_free: {:?}", longest_deref_free);
+            if let Some(mpi) = self.move_path_closest_to(longest_deref_free, PrefixSet::All) {
+                if maybe_uninits.curr_state.contains(&mpi) {
+                    // find and report move(s) that could cause this to be uninitialized
+                    self.report_use_of_moved(context, desired_action, lvalue_span);
+                    return; // don't bother finding other problems.
+                }
             }
```
Comment (nikomatsakis) [inline src/librustc_mir/borrow_check.rs]: e.g. here, it seems weird that it's ok to not have a path -- how do we know it's initialized then?

File: src/librustc_mir/borrow_check.rs (hunk 3 above)
Comment (pnkfelix) [reply src/librustc_mir/borrow_check.rs]: good point. I will review (and perhaps add an error branch at the call-site when it returns `None`)

Comment (pnkfelix) [reply src/librustc_mir/borrow_check.rs]: (one case that kept arising, which may or may not be relevant here, are paths that are built off of a static variable; we don't put entries in the `MoveData` for those. But I've been musing that it would be better to be more explicit about the scenarios: i.e., if all the cases of `None` end up being due to a static variable at the root, we should be able to signal that explicitly in a result here, and then the client will have better info about why its sound to not issue an error.)

**Comment by pnkfelix** [comment]
At this point I think the time has come to bite the bullet and generalize the MoveData to track even `Copy`-able things. But I think we can land this PR without that, and then once that generalization lands, hopefully it will lead to my being able to remove things like the `fn move_path_closest_to` method.

**Comment by pnkfelix** [comment]
I wrote:

>  being able to remove things like the `fn move_path_closest_to` method

This may have been over-ambitious. In particular, cases like structs with destructors are ones where borrowck *wants* to map an lvalue like `tuple.has_drop.field` to `tuple.has_drop`, and it seems natural to express that via `move_path_closest_to`

File: src/librustc_mir/borrow_check.rs [hunk 5]
```diff
@@ -642,29 +642,143 @@ impl<'c, 'b, 'a: 'b+'c, 'gcx, 'tcx: 'a> MirBorrowckCtxt<'c, 'b, 'a, 'gcx, 'tcx>
...
+        //
+        // Therefore, it suffices to find the longest shallow prefix
+        // for which we have a MovePath (if any); the dataflow will
+        // take care of updating its state in response to
+        // super-structure moves and reinitializations.
+        //
+        // This is scenarios 1 and 2 above.
+
+        debug!("check_if_path_is_moved part1 lvalue: {:?}", lvalue);
+        match self.move_path_closest_to(lvalue, PrefixSet::Shallow) {
```
Comment (arielb1) [inline src/librustc_mir/borrow_check.rs]: Why is this considering only the shallow set of prefixes? This later does a `max_deref_free_locally_rooted_prefix_of` to consider deep prefixes, so I don't see why this is split into 2 parts.

**Comment by arielb1** [comment]
r=me with the shallow prefix thing fixed.

File: src/test/compile-fail/borrowck/borrowck-uninit-field-access.rs (hunk 1 above)
Comment (pnkfelix) [reply src/test/compile-fail/borrowck/borrowck-uninit-field-access.rs]: (BTW I think this will be fixed by #45167)
