### PR TITLE
Do not point at delim spans for complete correct blocks

### LINKED ISSUE #56834: Surprising error note "this delimiter might not be properly closed"
## STR

```Rust
fn main() {
    S { x: 4,
        y: 5 };
}
fn foo() {
```

## Expected Result

An error message pointing  to `foo`

## Actual Result

```
   Compiling playground v0.0.1 (/playground)
error: this file contains an un-closed delimiter
 --> src/main.rs:5:12
  |
2 |     S { x: 4,
  |       - this delimiter might not be properly closed...
3 |         y: 5 };
  |              - ...as it matches this but it has different indentation
4 | }
5 | fn foo() {
  |          - ^
  |          |
  |          un-closed delimiter
```

The heuristic feels incorrect to me - the delimiter on `S` looks perfectly well-closed.

### PR DESCRIPTION
**Pull request by estebank**
Fix #56834.

### CODE REVIEW

File: src/libsyntax/parse/lexer/tokentrees.rs [hunk 1]
```diff
@@ -97,7 +97,13 @@ impl<'a> StringReader<'a> {
                     // Correct delimiter.
                     token::CloseDelim(d) if d == delim => {
                         let (open_brace, open_brace_span) = self.open_braces.pop().unwrap();
-                        self.matching_delim_spans.push((open_brace, open_brace_span, self.span));
+                        if self.open_braces.len() == 0 {
+                            // Clear up these spans to avoid suggesting them as we've found
+                            // properly matched delimiters so far for an entire block.
+                            self.matching_delim_spans.clear();
+                        } else {
+                            self.matching_delim_spans.push((open_brace, open_brace_span, self.span));
```
Comment (oli-obk) [inline src/libsyntax/parse/lexer/tokentrees.rs]: line is too long

**Review by oli-obk — CHANGES_REQUESTED** [review]
r=me with tidy fixed
