### PR TITLE
Check that const parameters of trait methods have compatible types

### LINKED ISSUE #86820: int.rs:230:13: expected int of size 8, but got size 1
### Code

```Rust
use std::ops::BitAnd;

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn is_set() {
        assert!(0xffu8.bit::<0>());
    }
}

trait Bits {
    fn bit<const I: u8>(self) -> bool;
}

impl<T> Bits for T where
    T: Copy + BitAnd<T, Output=T> + From<u8> + Eq
{
    fn bit<const I: usize>(self) -> bool {
        let i = 1 << I;
        let mask = T::from(i);
        mask & self == mask
    }
}

```

### Meta

`rustc --version --verbose`:
```
rustc 1.52.1 (9bc8c42bb 2021-05-09)
binary: rustc
commit-hash: 9bc8c42bb2f19e745a63f3445f1ac248fb015e53
commit-date: 2021-05-09
host: x86_64-apple-darwin
release: 1.52.1
LLVM version: 12.0.0
```

### Error output

```
error: internal compiler error: /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/compiler/rustc_middle/src/ty/consts/int.rs:230:13: expected int of size 8, but got size 1

thread 'rustc' panicked at 'Box<Any>', /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panic.rs:59:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

note: the compiler unexpectedly panicked. this is a bug.
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
$ RUST_BACKTRACE=1 cargo test
```

```
thread 'rustc' panicked at 'Box<Any>', /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panic.rs:59:5
stack backtrace:
   0: std::panicking::begin_panic
   1: std::panic::panic_any
   2: rustc_errors::HandlerInner::bug
   3: rustc_errors::Handler::bug
   4: rustc_middle::util::bug::opt_span_bug_fmt::{{closure}}
   5: rustc_middle::ty::context::tls::with_opt::{{closure}}
   6: rustc_middle::ty::context::tls::with_opt
   7: rustc_middle::util::bug::opt_span_bug_fmt
   8: rustc_middle::util::bug::bug_fmt
   9: rustc_middle::ty::consts::int::ScalarInt::assert_bits::{{closure}}
  10: rustc_codegen_llvm::common::<impl rustc_codegen_ssa::traits::consts::ConstMethods for rustc_codegen_llvm::context::CodegenCx>::scalar_to_backend
  11: rustc_codegen_ssa::mir::operand::OperandRef<V>::from_const
  12: rustc_codegen_ssa::mir::operand::<impl rustc_codegen_ssa::mir::FunctionCx<Bx>>::codegen_operand
  13: rustc_codegen_ssa::mir::rvalue::<impl rustc_codegen_ssa::mir::FunctionCx<Bx>>::codegen_rvalue_operand
  14: rustc_codegen_ssa::mir::codegen_mir
  15: rustc_codegen_ssa::base::codegen_instance
  16: <rustc_middle::mir::mono::MonoItem as rustc_codegen_ssa::mono_item::MonoItemExt>::define
  17: rustc_codegen_llvm::base::compile_codegen_unit::module_codegen
  18: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task
  19: rustc_codegen_llvm::base::compile_codegen_unit
  20: <rustc_codegen_llvm::LlvmCodegenBackend as rustc_codegen_ssa::traits::backend::CodegenBackend>::codegen_crate
  21: rustc_interface::passes::QueryContext::enter
  22: rustc_interface::queries::Queries::ongoing_codegen
  23: rustc_interface::queries::<impl rustc_interface::interface::Compiler>::enter
  24: rustc_span::with_source_map
  25: rustc_interface::interface::create_compiler_and_run
  26: scoped_tls::ScopedKey<T>::set
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

</p>
</details>

### PR DESCRIPTION
**Pull request by FabianWolff**
This PR fixes #86820. The problem is that this currently passes the type checker:
```rust
trait Tr {
    fn foo<const N: u8>(self) -> u8;
}

impl Tr for f32 {
    fn foo<const N: bool>(self) -> u8 { 42 }
}
```
i.e. the type checker fails to check whether const parameters in `impl` methods have the same type as the corresponding declaration in the trait. With my changes, I get, for the above code:
```
error[E0053]: method `foo` has an incompatible const parameter type for trait
 --> test.rs:6:18
  |
6 |     fn foo<const N: bool>(self) -> u8 { 42 }
  |                  ^
  |
note: the const parameter `N` has type `bool`, but the declaration in trait `Tr::foo` has type `u8`
 --> test.rs:2:18
  |
2 |     fn foo<const N: u8>(self) -> u8;
  |                  ^

error: aborting due to previous error
```
This fixes #86820, where an ICE happens later on because the trait method is declared with a const parameter of type `u8`, but the `impl` uses one of type `usize`:
> `expected int of size 8, but got size 1`

### CODE REVIEW

**Comment by LeSeulArtichaut** [comment]
Maybe r? @jackh726

File: compiler/rustc_typeck/src/check/compare_method.rs [hunk 1]
```diff
@@ -929,6 +933,77 @@ fn compare_synthetic_generics<'tcx>(
     if error_found { Err(ErrorReported) } else { Ok(()) }
 }
 
+fn compare_const_generic_types<'tcx>(
```
Comment (lcnr) [inline compiler/rustc_typeck/src/check/compare_method.rs:936]: nit
```suggestion
fn compare_const_param_types<'tcx>(
```
or `parameter`

File: compiler/rustc_typeck/src/check/compare_method.rs [hunk 2]
```diff
@@ -929,6 +933,77 @@ fn compare_synthetic_generics<'tcx>(
...
+                        hir::ParamName::Plain(ident) => Some(ident),
+                        _ => None,
+                    },
+                ),
+                other => bug!(
+                    "expected GenericParam, found {:?}",
+                    other.map_or_else(|| "nothing".to_string(), |n| format!("{:?}", n))
+                ),
+            };
+            let trait_span = match const_param_trait.as_local() {
```
Comment (lcnr) [inline compiler/rustc_typeck/src/check/compare_method.rs:971]:
```suggestion
            let trait_span = match tcx.hir().get_if_local(const_param_trait) {
```

File: compiler/rustc_typeck/src/check/compare_method.rs [hunk 3]
```diff
@@ -929,6 +933,77 @@ fn compare_synthetic_generics<'tcx>(
...
+    let const_params_impl = const_params_of(impl_m.def_id);
+    let const_params_trait = const_params_of(trait_m.def_id);
+
+    for (const_param_impl, const_param_trait) in iter::zip(const_params_impl, const_params_trait) {
+        let impl_ty = tcx.type_of(const_param_impl);
+        let trait_ty = tcx.type_of(const_param_trait);
+        if impl_ty != trait_ty {
+            let (impl_span, impl_ident) = match tcx
+                .hir()
+                .find(tcx.hir().local_def_id_to_hir_id(const_param_impl.expect_local()))
```
Comment (lcnr) [inline compiler/rustc_typeck/src/check/compare_method.rs:957]:
```suggestion
                .get_if_local(const_param_impl)
```
or just `get(tcx.hir().local_def_id_to_hir_id(const_param_impl.expect_local()))`. I didn't know `get_if_local` existed and don't like that method too much but :shrug:

**Review by lcnr — APPROVED** [review]
this PR is looking good, some nits but after that r=me

File: compiler/rustc_typeck/src/check/compare_method.rs (hunk 3 above)
Comment (FabianWolff) [reply compiler/rustc_typeck/src/check/compare_method.rs]: Fixed. Thanks for the review!

**Comment by lcnr** [comment]
thx

@bors r+ rollup
