### PR TITLE
Turn moves into copies after copy propagation

### LINKED ISSUE #137936: CopyProp miscompilation when src is moved more than once
```rust
#![feature(custom_mir, core_intrinsics, freeze)]
#![allow(internal_features, unused_assignments)]
extern crate core;
use core::intrinsics::mir::*;
use core::mem::MaybeUninit;
use core::marker::Freeze;

#[custom_mir(dialect = "analysis", phase = "post-cleanup")]
fn f<T: Copy + Freeze>(a: MaybeUninit<T>) {
    mir! {
        {
            let b = Move(a);
            let c = Move(a);
            Call(RET = g(Move(b), Move(c)), ReturnTo(ret), UnwindContinue())
        }
        ret = {
            Return()
        }
    }
}

fn g<T: Copy + Freeze>(mut a: T, mut b: T) {
    assert_ne!(&mut a as *mut _ as usize, &mut b as *mut _ as usize);
}

fn main() {
    f(MaybeUninit::<[u8;  64]>::uninit());
}
```

The CopyProp introduces following changes:

```diff
--- a.f.005-021.CopyProp.before.mir	2025-03-03 13:42:20.628850669 +0100
+++ a.f.005-021.CopyProp.after.mir	2025-03-03 13:42:20.628850669 +0100
@@ -1,17 +1,15 @@
-// MIR for `f` before CopyProp
+// MIR for `f` after CopyProp
 
 fn f(_1: MaybeUninit<T>) -> () {
     let mut _0: ();
     let mut _2: std::mem::MaybeUninit<T>;
     let mut _3: std::mem::MaybeUninit<T>;
 
     bb0: {
-        _2 = move _1;
-        _3 = move _1;
-        _0 = g::<MaybeUninit<T>>(move _2, move _3) -> [return: bb1, unwind continue];
+        _0 = g::<MaybeUninit<T>>(move _1, move _1) -> [return: bb1, unwind continue];
     }
 
     bb1: {
         return;
     }
 }
```

```console
$ rustc a.rs -Zmir-opt-level=0 && ./a
$ rustc a.rs -Zmir-opt-level=1 && ./a

thread 'main' panicked at a.rs:23:5:
assertion `left != right` failed
  left: 140729201385720
 right: 140729201385720
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

### LINKED ISSUE #146423: Aliasing-related miscompile in CopyProp (use after Move of place)
Reduced example from rustlantis, which is accepted by Miri using Tree Borrows without optimizations enabled:

```rust
#![feature(custom_mir, core_intrinsics)]
#![allow(internal_features)]

use std::intrinsics::mir::*;

#[custom_mir(dialect = "runtime")]
fn main() {
    mir!{
        let _1;
        let _2;
        let _3;
        let _4;
        {
            _1 = core::ptr::addr_of_mut!(_2);
            _3 = Move(_1);
            _4 = Move(_1);
            Call(*_1 = fn1(Move(_3), _4), ReturnTo(bb1), UnwindUnreachable())
        }
        bb1 = {
            Return()
        }
    }
}

#[custom_mir(dialect = "runtime")]
fn fn1(_1: *mut *const u8, _2: *mut *const u8) -> *const u8 {
    mir!{
        let _3;
        {
            _3 = 0;
            RET = core::ptr::addr_of!(_3);
            Return()
        }
    }
}
```
This program is accepted without any optimizations, but with CopyProp enabled:
```
MIRIFLAGS="-Zmiri-tree-borrows -Zmir-enable-passes=+CopyProp" cargo +nightly miri run
```
Miri reports UB:
```
error: Undefined Behavior: read access through <264> (root of the allocation) at alloc126[0x0] is forbidden
  --> src/main.rs:17:13
   |
17 |             Call(*_1 = fn1(Move(_3), _4), ReturnTo(bb1), UnwindUnreachable())
   |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ Undefined Behavior occurred here
   |
   = help: this indicates a potential bug in the program: it performed an invalid operation, but the Tree Borrows rules it violated are still experimental
   = help: see https://github.com/rust-lang/unsafe-code-guidelines/blob/master/wip/tree-borrows.md for further information
   = help: the accessed tag <264> (root of the allocation) is foreign to the protected tag <265> (i.e., it is not a child)
   = help: this foreign read access would cause the protected tag <265> (currently Active) to become Disabled
   = help: protected tags must never be Disabled
help: the accessed tag <264> was created here
  --> src/main.rs:17:13
   |
17 |             Call(*_1 = fn1(Move(_3), _4), ReturnTo(bb1), UnwindUnreachable())
   |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
help: the protected tag <265> was created here, in the initial state Reserved
  --> src/main.rs:30:13
   |
30 |             _3 = 0;
   |             ^^^^^^
help: the protected tag <265> later transitioned to Active due to a child write access at offsets [0x0..0x8]
  --> src/main.rs:30:13
   |
30 |             _3 = 0;
   |             ^^^^^^
   = help: this transition corresponds to the first write to a 2-phase borrowed mutable reference
   = note: BACKTRACE (of the first span):
   = note: inside `main` at src/main.rs:17:13: 17:78
```
The errant transformation is this:
```diff
 fn main() -> () {
     let mut _0: ();
     let mut _1: *mut *const u8;
     let mut _2: *const u8;
     let mut _3: *mut *const u8;
     let mut _4: *mut *const u8;
 
     bb0: {
         _1 = &raw mut _2;
-        _3 = move _1;
-        _4 = move _1;
-        (*_1) = fn1(move _3, copy _4) -> [return: bb1, unwind unreachable];
+        (*_1) = fn1(move _1, copy _1) -> [return: bb1, unwind unreachable];
     }
 
     bb1: {
         return;
     }
 }
```

### PR DESCRIPTION
**Pull request by tmiasko**
Previously copy propagation presumed that there is further unspecified distinction between move operands and copy operands in assignments and propagated moves from assignments into terminators. This is inconsistent with current operational semantics.

Turn moves into copies after copy propagation to preserve existing behavior.

Fixes https://github.com/rust-lang/rust/issues/137936.
Fixes https://github.com/rust-lang/rust/issues/146423.

r? @cjgillot

### CODE REVIEW

File: tests/mir-opt/copy-prop/move_arg.rs [hunk 1]
```diff
@@ -1,17 +1,41 @@
...
-    f(5)
+#[custom_mir(dialect = "runtime", phase = "initial")]
+pub fn moved_twice<T: Copy>(_1: MaybeUninit<T>) {
+    // CHECK-LABEL: fn moved_twice(
+    // CHECK: _0 = f::<MaybeUninit<T>>(copy _1, copy _1)
+    mir! {
+        {
+            let _2 = Move(_1);
+            let _3 = Move(_1);
+            Call(RET = f(Move(_2), Move(_3)), ReturnTo(bb1), UnwindUnreachable())
```
Comment (bjorn3) [inline tests/mir-opt/copy-prop/move_arg.rs:37]: Why would this not be considered UB?

Comment (tmiasko) [reply tests/mir-opt/copy-prop/move_arg.rs:37]: In statements move behaves like copy, so there is no UB as can be verified in Miri (and previously copy propagation would introduce UB).

We would like to optimize some of those cases, but we don't have operational semantics to explain why this would be UB. Without operational semantics it is impossible to say whether this transformation is correct and consistent with other transformation we perform.

Comment (bjorn3) [reply tests/mir-opt/copy-prop/move_arg.rs:37]: Can you add a comment to this test that we want to make it UB in the future but that it is not UB under the current opsem rules?

File: compiler/rustc_mir_transform/src/copy_prop.rs [hunk 2]
```diff
@@ -134,7 +92,7 @@ impl<'tcx> MutVisitor<'tcx> for Replacer<'_, 'tcx> {
     fn visit_statement(&mut self, stmt: &mut Statement<'tcx>, loc: Location) {
         // When removing storage statements, we need to remove both (#107511).
         if let StatementKind::StorageLive(l) | StatementKind::StorageDead(l) = stmt.kind
-            && self.storage_to_remove.contains(l)
+            && self.unified.contains(l)
         {
             stmt.make_nop(true);
             return;
```
Comment (tmiasko) [inline compiler/rustc_mir_transform/src/copy_prop.rs]: Looks like this might cause issue similar to the one that was fixed in #147525.

**Comment by cjgillot** [comment]
Considering this fixes a miscompile, the perf regression is acceptable.
@bors r+

File: tests/codegen-llvm/align-byval.rs [hunk 3]
```diff
@@ -1,7 +1,7 @@
 // ignore-tidy-linelength
 //@ add-minicore
 //@ revisions:m68k x86_64-linux x86_64-windows i686-linux i686-windows
-
+//@ compile-flags: -Copt-level=1 -Cno-prepopulate-passes
```
Comment (tmiasko) [inline tests/codegen-llvm/align-byval.rs:4]: This test now relies on CopyProp + DeadStoreElimination, while it previously relied only on CopyProp.

Custom MIR would be a better alternative, if not for the fact that it is not available in minicore tests :-(.

Comment (saethlin) [reply tests/codegen-llvm/align-byval.rs:4]: Why is this opt-level=1 instead of enabling the specific MIR transforms?

Comment (tmiasko) [reply tests/codegen-llvm/align-byval.rs:4]: What would be a benefit of doing that? Test assumes that code generation is performed on fully optimized MIR. It doesn't matter which transforms are involved.

Comment (saethlin) [reply tests/codegen-llvm/align-byval.rs:4]: Ah I see. I'm just wary of the assumption that opt-level 1 is _fully_ optimized MIR. Currently it does map to -Zmir-opt-level=2 but I have a nagging feeling that enabling the same (with the exception of Inline) MIR opts at -Copt-level=3 and -Copt-level=1 can't be optimal.

But this isn't a serious reason to hold up this PR even more, it's an important fix so I'm delta-approving it.
