### PR TITLE
gvn: Invalid dereferences for all non-local mutations

### LINKED ISSUE #132353: Panic in nightly 1.83.0 and 1.84.0 with opt-level >= 1 when unwrapping Some variant
When calling an unwrap on a value that *should* be Some, i instead get an unwrap on None error. Attaching a debugger seems to show an invalid memory error.

This issue happens only when opt-level is set to at least 1, (aka in dev profile, no panic happens, and in release it does), and only happens in rust nightly 1.83.0 and 1.84.0, it does not happen on stable and nightly 1.82.0.

~~I'm not sure if the issue is in my code or in the sprs crate, i've filed [an issue](https://github.com/sparsemat/sprs/issues/370) there and also here just to make sure.~~
EDIT: managed to narrow down the bug by removing the sprs crate, this is only pure rust

Here is the [repo for minimum example](https://github.com/Specy/microlp/tree/panic-bug) or in [the playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=0b00575c9057e816cddce89d00a0d856), there is an even smaller reproduction in the [comments](https://github.com/rust-lang/rust/issues/132353#issuecomment-2446804777)

To reproduce, run `cargo run --release` which will panic, while if running `cargo run` it won't panic

I've tried to run this with miri, nothing there. Also tried to run the release mode with bounds checking turned on, but nothing changed
### Meta
`rustc --version --verbose`:
```
rustc 1.84.0-nightly (3f1be1ec7 2024-10-28)
binary: rustc
commit-hash: 3f1be1ec7ec3d8e80beb381ee82164a0aa3ca777
commit-date: 2024-10-28
host: x86_64-unknown-linux-gnu
release: 1.84.0-nightly
LLVM version: 19.1.1
```

<details><summary>Backtrace</summary>
<p>

```
thread 'main' panicked at src/main.rs:122:27:
called `Option::unwrap()` on a `None` value
stack backtrace:
   0: rust_begin_unwind
             at /rustc/3f1be1ec7ec3d8e80beb381ee82164a0aa3ca777/library/std/src/panicking.rs:665:5
   1: core::panicking::panic_fmt
             at /rustc/3f1be1ec7ec3d8e80beb381ee82164a0aa3ca777/library/core/src/panicking.rs:75:14
   2: core::panicking::panic
             at /rustc/3f1be1ec7ec3d8e80beb381ee82164a0aa3ca777/library/core/src/panicking.rs:152:5
   3: core::option::unwrap_failed
             at /rustc/3f1be1ec7ec3d8e80beb381ee82164a0aa3ca777/library/core/src/option.rs:2008:5
   4: microlp::order_simple
   5: microlp::main
             at ./src/main.rs:152:5
   6: core::ops::function::FnOnce::call_once
             at /home/specy/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:250:5
```

</p>
</details>

### PR DESCRIPTION
**Pull request by dianqk**
Fixes #132353.

This PR removes the computation value by traversing SSA locals through `for_each_assignment_mut`.

Because the `for_each_assignment_mut` traversal skips statements which have side effects, such as dereference assignments, the computation may be unsound. Instead of `for_each_assignment_mut`, we compute values by traversing in reverse postorder.

Because we compute and use the symbolic representation of values on the fly, I invalidate all old values when encountering a dereference assignment. The current approach does not prevent the optimization of a clone to a copy.

In the future, we may add an alias model, or dominance information for dereference assignments, or SSA form to help GVN.

r? cjgillot

cc @jieyouxu #132356
cc @RalfJung #133474

### CODE REVIEW

**Comment by DianQK** [comment]
I will update this after #132461.

**Comment by DianQK** [comment]
Oops, I forgot to revert #133474.

@bors try @rust-timer queue

**Comment by DianQK** [comment]
The failed test case should be fixed by #134073.

**Comment by DianQK** [comment]
I rebased.

**Comment by DianQK** [comment]
ping
I can put the last commit in a separated PR.

**Comment by DianQK** [comment]
cjgillot seems busy.

r? oli-obk

File: compiler/rustc_mir_transform/src/gvn.rs [hunk 1]
```diff
@@ -364,6 +367,21 @@ impl<'body, 'tcx> VnState<'body, 'tcx> {
...
+    fn insert_deref(&mut self, value: VnIndex) -> VnIndex {
+        let value = self.insert(Value::Projection(value, ProjectionElem::Deref));
+        self.derefs.push(value);
+        value
+    }
+
+    fn invalidate_derefs(&mut self) {
+        let mut derefs = Vec::new();
+        std::mem::swap(&mut derefs, &mut self.derefs);
+        for deref in derefs {
```
Comment (oli-obk) [inline compiler/rustc_mir_transform/src/gvn.rs:379]: Use

```rust
for deref in self.derefs.drain(..) {
```

There are no borrowing issues (if there were, `for deref in std::mem::take(&mut self.derefs)` would work), and it signals the intent here better.

**Review by oli-obk — APPROVED** [review]

File: compiler/rustc_mir_transform/src/gvn.rs (hunk 1 above)
Comment (DianQK) [reply compiler/rustc_mir_transform/src/gvn.rs]: Ah, thanks!

Comment (DianQK) [reply compiler/rustc_mir_transform/src/gvn.rs]: I used `std::mem::take(&mut self.derefs)`. `next_opaque`'s argument is `&mut self`.

**Comment by DianQK** [comment]
Flaky error?
 cc #132111

**Comment by DianQK** [comment]
> The job **`x86_64-mingw-1`** failed! Check out the build log: [(web)](https://github.com/rust-lang-ci/rust/actions/runs/12441737508/job/34739036559) [(plain)](https://github.com/rust-lang-ci/rust/commit/0754bc9ccf95da22a3203831f9312577a31ad56c/checks/34739036559/logs)
> Click to see the possible cause of the failure (guessed by this bot)

Should fix by  #134608.

**Comment by DianQK** [comment]
> ☔ The latest upstream changes (presumably #134330) made this pull request unmergeable. Please [resolve the merge conflicts](https://rustc-dev-guide.rust-lang.org/git.html#rebasing-and-conflicts).

I rebased.

File: compiler/rustc_mir_transform/src/gvn.rs [hunk 2]
```diff
@@ -1611,6 +1606,21 @@ impl<'tcx> MutVisitor<'tcx> for VnState<'_, 'tcx> {
...
+        if let Terminator { kind: TerminatorKind::Call { destination, .. }, .. } = terminator {
+            if let Some(local) = destination.as_local()
+                && self.ssa.is_ssa(local)
+            {
+                let opaque = self.new_opaque();
+                self.assign(local, opaque);
+            }
+            // Function calls maybe invalidate nested deref, and non-local assignments maybe invalidate deref.
+            // Currently, no distinction is made between these two cases.
+            self.invalidate_derefs();
```
Comment (cjgillot) [inline compiler/rustc_mir_transform/src/gvn.rs:1620]: I fear we are missing many cases of indirect writes. For example, inline asm.

Comment (DianQK) [reply compiler/rustc_mir_transform/src/gvn.rs:1626]: Instead of addressing to which terminator may write something, I adopted a more conservative approach, which terminator must not write anything.

**Comment by DianQK** [comment]
I have rebased. 

@oli-obk Since @cjgillot may be busy, would you like to review it again?
btw, I think you might have forgotten to update your GitHub profile status? :p

**Comment by oli-obk** [comment]
> would you like to review it again?

I think I'll leave it to the expert who keeps finding things I missed ;)

**Comment by dianqk** [comment]
The [latest commit](https://github.com/rust-lang/rust/pull/132527/commits/66e6d9d6af1cd6ab0b7ccc57d6df43241a07d69f) should complement other non-local mutations. This should also cover inline assembly, but limiting it to `SwitchInt` and `Goto` would likely make reviewing easier.

**Comment by oli-obk** [comment]
r=me

Gave it another review and we're just after beta cutoff, so we have 11 weeks for it to bake on nightly.

**Comment by dianqk** [comment]
Thanks! 🟩
r=oli-obk

**Comment by dianqk** [comment]
Hmm...
@bors r=oli-obk

**Comment by dianqk** [comment]
[diff](https://github.com/rust-lang/rust/compare/d9fbe5da7e85e8781d98234027415025100bda5a..7d44887374ee667bd5aeb5e861032b8ce4093b29)

@bors r=oli-obk

**Comment by rylev** [comment]
@dianqk @oli-obk this PR seems to have brought about a decent number of perf regressions. I didn't find any justification for perf in the PR history, but it seems like the perf results were to be predicted. What are your thoughts on the justification for perf here?

**Comment by dianqk** [comment]
> @dianqk @oli-obk this PR seems to have brought about a decent number of perf regressions. I didn't find any justification for perf in the PR history, but it seems like the perf results were to be predicted. What are your thoughts on the justification for perf here?

This is essentially a re-landing of #128299. It will change many clones into single copy statements, which will significantly affect MIR inlining and lead to a lot of data churn. Currently, it doesn't appear to be a regression.
