### PR TITLE
Fix missing diagnostic span for `impl Trait` with const generics, and add various tests for `min_const_generics` and `const_generics`

### LINKED ISSUE #61410: `impl Trait` and explicit const arguments
```rust
// run-pass

#![feature(const_generics)]
//~^ WARN the feature `const_generics` is incomplete and may cause the compiler to crash

trait Usizer {
    fn m(self) -> usize;
}

fn f<const N: usize>(u: impl Usizer) -> usize {
    N + u.m()
}

struct Usizable;

impl Usizer for Usizable {
    fn m(self) -> usize {
        16
    }
}

fn main() {
    assert_eq!(f::<4usize>(Usizable), 20usize);
}
```
results in:
```
error[E0282]: type annotations needed
  --> bug.rs:23:16
   |
23 |     assert_eq!(f::<4usize>(Usizable), 20usize);
   |                ^^^^^^^^^^^ cannot infer type for `fn(Usizable) -> usize {f::<Usizable, _: usize>}`
```

### PR DESCRIPTION
**Pull request by varkor**
Closes https://github.com/rust-lang/rust/issues/61410.

Adds `min_const_generics` tests for:
- https://github.com/rust-lang/rust/issues/73727
- https://github.com/rust-lang/rust/issues/72293
- https://github.com/rust-lang/rust/issues/67375
- https://github.com/rust-lang/rust/issues/75153
- https://github.com/rust-lang/rust/issues/71922
- https://github.com/rust-lang/rust/issues/69913
- https://github.com/rust-lang/rust/issues/67945
- https://github.com/rust-lang/rust/issues/69239

Adds `const_generics` tests for:
- https://github.com/rust-lang/rust/issues/67375
- https://github.com/rust-lang/rust/issues/75153
- https://github.com/rust-lang/rust/issues/71922
- https://github.com/rust-lang/rust/issues/69913
- https://github.com/rust-lang/rust/issues/67945
- https://github.com/rust-lang/rust/issues/69239

(I only added separate `min_const_generics` and `const_generics` tests if they were handled differently by the two features.)

We need to figure out how to deduplicate when `const_generics` is stabilised, but we can discuss that later. For now, we should be checking neither feature breaks, so require regression tests for both. I've given them identical names when I've added both, which should make it easier to spot them later.

r? @lcnr

### CODE REVIEW

**Comment by varkor** [comment]
I've also tweaked a diagnostic for consistency.

**Comment by estebank** [comment]
r=me after reblessing

File: src/test/ui/const-generics/min_const_generics/const-argument-if-length.rs [hunk 1]
```diff
@@ -0,0 +1,18 @@
+#![feature(min_const_generics)]
```
Comment (lcnr) [inline src/test/ui/const-generics/min_const_generics/const-argument-if-length.rs:1]: I think it's better to instead use revisions here :thinking: 

we already do this for most other tests

**Review by lcnr — APPROVED** [review]
lgtm,

I would prefer to merge the identical tests for `const_generics` and `min_const_generics` and instead use revisions here, as we otherwise probably end up with duplicates once `const_generics` is stable.

File: src/test/ui/const-generics/min_const_generics/const-argument-if-length.rs (hunk 1 above)
Comment (varkor) [reply src/test/ui/const-generics/min_const_generics/const-argument-if-length.rs:1]: Yes, you're completely right: for some reason this slipped my mind. I'll fix those up soon.

Comment (varkor) [reply src/test/ui/const-generics/min_const_generics/const-argument-if-length.rs]: I've switched to using revisions.

File: src/test/ui/const-generics/min_const_generics/const-argument-if-length.rs [hunk 2]
```diff
@@ -0,0 +1,24 @@
+// revisions: full min
```
Comment (lcnr) [inline src/test/ui/const-generics/min_const_generics/const-argument-if-length.rs:1]: do these tests make sense in the `min_const_generics` folder, considering that they now also apply to `const_generics`?

Comment (varkor) [reply src/test/ui/const-generics/min_const_generics/const-argument-if-length.rs:1]: I was wondering that, but I'm not sure I see the value of having the `min_const_generics` folder at all, since almost every test applying to `min_const_generics` also applies to `const_generics` (except where we currently ICE for `const_generics`). Do you think it's useful to separate them like this, or should we merge the folders?

Comment (lcnr) [reply src/test/ui/const-generics/min_const_generics/const-argument-if-length.rs:1]: The idea for the `min_const_generics` folder was to test the changes needed for `min_const_generics` when I started to implement it.

So I do think tests which explicitly check which param types are allowed and that only trivial expressions are allowed make some sense here.

But it would also be fine to just merge these tests with the remaining `const_generics` tests :shrug:

Comment (varkor) [reply src/test/ui/const-generics/min_const_generics/const-argument-if-length.rs:1]: I'll move these ones for now, and we can decide whether to merge the folders later.

File: src/test/ui/const-generics/min_const_generics/impl-trait-with-const-arguments.rs [hunk 3]
```diff
@@ -0,0 +1,22 @@
+#![feature(min_const_generics)]
```
Comment (lcnr) [inline src/test/ui/const-generics/min_const_generics/impl-trait-with-const-arguments.rs:1]: this test has the same output with `const_generics` afaict, was there a reason why you didn't use revisions for that one?

**Review by lcnr — APPROVED** [review]
r=me after the last nit

File: src/test/ui/const-generics/min_const_generics/impl-trait-with-const-arguments.rs (hunk 3 above)
Comment (varkor) [reply src/test/ui/const-generics/min_const_generics/impl-trait-with-const-arguments.rs:1]: Just an oversight; I'll correct it.
