### PR TITLE
rustdoc: add support for incoherent impls on structs and traits

### LINKED ISSUE #103170: `std::error::Error` docs don't mention `e.downcast()` (only `downcast_{ref,mut}`)
I didn't notice an issue on file for this already, feel free to dupe against it if one exists.

In https://github.com/rust-lang/rust/pull/99917 we landed support for error in core, and sadly one of the casualties was the docs got somewhat worse. Concretely, `Box<dyn Error + stuff>::downcast()` is no longer shown on the [docs page for Error](https://doc.rust-lang.org/nightly/std/error/trait.Error.html#method.request_ref), which is a bit of a bummer, since these methods do exist: https://doc.rust-lang.org/nightly/src/alloc/boxed.rs.html#2127

### PR DESCRIPTION
**Pull request by notriddle**
Fixes #103170

### CODE REVIEW

File: src/librustdoc/clean/inline.rs [hunk 1]
```diff
@@ -323,6 +323,21 @@ pub(crate) fn build_impls(
...
         build_impl(cx, parent_module, did, attrs, ret);
     }
+
+    // This pretty much exists expressly for `dyn Error` traits that exist in the `alloc` crate.
+    // See also:
+    //
+    // * https://github.com/rust-lang/rust/issues/103170 — where it didn't used to get documented
+    // * https://github.com/rust-lang/rust/pull/99917 — where the feature got used
+    // * https://github.com/rust-lang/rust/issues/53487 — overall tracking issue for Error
+    if tcx.has_attr(did, sym::rustc_has_incoherent_inherent_impls) {
```
Comment (GuillaumeGomez) [inline src/librustdoc/clean/inline.rs:333]: Then the issue will remain for the JSON output if we fix it in `inline`, no?

Comment (GuillaumeGomez) [reply src/librustdoc/clean/inline.rs:333]: Makes sense! So no need for it.

**Review by GuillaumeGomez — APPROVED** [review]

**Comment by GuillaumeGomez** [comment]
Thanks!

@bors r+ rollup

File: src/librustdoc/clean/inline.rs (hunk 1 above)
Comment (GuillaumeGomez) [reply src/librustdoc/clean/inline.rs:333]: Yes, totally fine.
