### PR TITLE
Fix ICEs on invalid vtable size/alignment const UB errors

### LINKED ISSUE #86193: ICE on invalid size/alignment in CTFE validation
The following code ICEs:
```rust
#[repr(transparent)]
struct W<T>(T);

// The drop fn is checked before size/align are, so get ourselves a "sufficiently valid" drop fn
fn drop_me(_: *mut usize) {}

const INVALID_VTABLE_SIZE: W<&dyn Send> =
    unsafe { std::mem::transmute((&92u8, &(drop_me as fn(*mut usize), usize::MAX, 1usize))) };
```
To fix this, this code here needs to properly catch the "invalid size/align" error and turn it into a validation failure:

https://github.com/rust-lang/rust/blob/563ab4a106928a9f9a27618ad6598fd255dc3555/compiler/rustc_mir/src/interpret/validity.rs#L356

But for this we first need to make these errors catchable by introducing separate variants into this enum:

https://github.com/rust-lang/rust/blob/2779fc1c4768567b74b757a8083db3c39765f071/compiler/rustc_middle/src/mir/interpret/error.rs#L211

You can use the existing `InvalidDropFn` variant as a model; it does the same job for invalid drop function pointers in the vtable.

Cc @lqd

### PR DESCRIPTION
**Pull request by lqd**
The invalid vtable size/alignment errors from `InterpCx::read_size_and_align_from_vtable` were "freeform const UB errors", causing ICEs when reaching validation. This PR turns them into const UB hard errors to catch them during validation and avoid that.

Fixes #86193

r? @RalfJung 

(It seemed cleaner to have 2 variants but they can be merged into one variant with a message payload if you prefer that ?)

### CODE REVIEW

File: compiler/rustc_middle/src/mir/interpret/error.rs [hunk 1]
```diff
@@ -228,6 +228,10 @@ pub enum UndefinedBehaviorInfo<'tcx> {
     InvalidMeta(&'static str),
     /// Invalid drop function in vtable.
     InvalidDropFn(FnSig<'tcx>),
+    /// Invalid size in a vtable: too large.
+    InvalidSize,
+    /// Invalid alignment in a vtable: too large, or not a power of 2.
+    InvalidAlignment(String),
```
Comment (RalfJung) [inline compiler/rustc_middle/src/mir/interpret/error.rs:234]: I feel like `InvalidVtable{Size,Alignment,DropFn}` would be clearer names for these variants. What do you think?

File: src/test/ui/consts/const-eval/ub-incorrect-vtable.rs [hunk 2]
```diff
@@ -3,6 +3,15 @@
 //   triggers an error
 // - a similar test that triggers a previously-untested const UB error: emitted close to the above
 //   error, it checks the correctness of the size
+//
+// As is, this code will only hard error when the constants are used, and the errors are emitted via
+// the `#[allow]`-able `const_err` lint. However, if the transparent wrapper technique to prevent
+// reborrows is used -- from `ub-wide-ptr.rs` -- these two errors reach validation and would trigger
+// ICEs as tracked by #86193. So we also use the transparent wrapper to verify actual const UB hard
+// errors are emitted now instead of ICEs.
```
Comment (RalfJung) [inline src/test/ui/consts/const-eval/ub-incorrect-vtable.rs:11]:
```suggestion
// ICEs as tracked by #86193. So we also use the transparent wrapper to verify proper validation
// errors are emitted instead of ICEs.
```

File: src/test/ui/consts/const-eval/ub-incorrect-vtable.64bit.stderr [hunk 3]
```diff
@@ -0,0 +1,52 @@
...
+   = note: the raw bytes of the constant (size: 16, align: 8) {
+               ╾───────allocN───────╼ ╾───────allocN───────╼ │ ╾──────╼╾──────╼
+           }
+
+error[E0080]: it is undefined behavior to use this value
+  --> $DIR/ub-incorrect-vtable.rs:41:1
+   |
+LL | / const INVALID_VTABLE_SIZE_UB: W<&dyn Trait> =
+LL | |     unsafe { std::mem::transmute((&92u8, &(drop_me as fn(*mut usize), usize::MAX, 1usize))) };
+   | |______________________________________________________________________________________________^ type validation failed: encountered invalid vtable: size is bigger than largest supported object at .0
```
Comment (RalfJung) [inline src/test/ui/consts/const-eval/ub-incorrect-vtable.64bit.stderr:43]: @oli-obk reading this, I feel like we should reorder these error messages a bit, and make them more like
> type validation failed at .0: encountered invalid vtable: size is bigger than largest supported object

What do you think? (@lqd certainly not for this PR though)

File: compiler/rustc_middle/src/mir/interpret/error.rs (hunk 1 above)
Comment (lqd) [reply compiler/rustc_middle/src/mir/interpret/error.rs:234]: sure, I'll do that ! I initially did name those specifically for vtables but then `InvalidDropFn` "convinced me" not to do so ^^

File: src/test/ui/consts/const-eval/ub-incorrect-vtable.64bit.stderr (hunk 3 above)
Comment (lqd) [reply src/test/ui/consts/const-eval/ub-incorrect-vtable.64bit.stderr:43]: if you and oli want this, I can certainly do that in this PR

Comment (RalfJung) [reply src/test/ui/consts/const-eval/ub-incorrect-vtable.64bit.stderr:43]: This will affect many tests, so it should be a separate PR. But sure, if you want to help wit this that'd be great. :)

Comment (lqd) [reply src/test/ui/consts/const-eval/ub-incorrect-vtable.64bit.stderr:43]: Agreed, I'll do that in another PR.

Would something like this work for you ? Changing `ValidationFailure`'s content from a String message to a `path: Option<String>, mesg: String` so that https://github.com/rust-lang/rust/blob/3e827cc21e0734edd26170e8d1481f0d66a1426b/compiler/rustc_mir/src/interpret/validity.rs#L27-L47 can handle the empty "where", and the formatting you want can be implemented at https://github.com/rust-lang/rust/blob/2779fc1c4768567b74b757a8083db3c39765f071/compiler/rustc_middle/src/mir/interpret/error.rs#L326

Comment (RalfJung) [reply src/test/ui/consts/const-eval/ub-incorrect-vtable.64bit.stderr:43]: Let's discuss the implementation details elsewhere (possibly on Zulip), if/when @oli-obk agrees that we even want to do this. :)

**Comment by RalfJung** [comment]
This looks great, thanks a lot. :-)
@bors r+

**Comment by lqd** [comment]
CI is green after actually calling rustfmt...

@bors r=RalfJung

File: src/test/ui/consts/const-eval/ub-incorrect-vtable.64bit.stderr (hunk 3 above)
Comment (oli-obk) [reply src/test/ui/consts/const-eval/ub-incorrect-vtable.64bit.stderr:43]: I agree that the proposed ordering is better than the current one
