### PR TITLE
Don't add a note for implementing a trait if its inner type is erroneous

### LINKED ISSUE #105138: `Into<[type error]>` in diagnostic
Given the following code: 

```rust
pub enum LabelText {
    Plain,
}
impl<T> From<T> for LabelText
where
    T: Into<Cow<'static, str>>,
{
    fn from(text: T) -> Self {
        LabelText::Plain(text.into())
    }
}
```

The current output is:

```
error[E0119]: conflicting implementations of trait `core::convert::From<error::LabelText>` for type `error::LabelText`
  --> src/error.rs:40:1
   |
40 | impl<T> From<T> for LabelText
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: conflicting implementation in crate `core`:
           - impl<T> core::convert::From<T> for T;
   = note: downstream crates may implement trait `core::convert::Into<[type error]>` for type `error::LabelText`
```

I doubt it's supposed to be `Into<[type error]>`

### PR DESCRIPTION
**Pull request by bhbs**
Fix #105138

### CODE REVIEW

File: compiler/rustc_trait_selection/src/traits/select/mod.rs [hunk 1]
```diff
@@ -371,23 +371,28 @@ impl<'cx, 'tcx> SelectionContext<'cx, 'tcx> {
 
                     if !candidate_set.ambiguous && no_candidates_apply {
                         let trait_ref = stack.obligation.predicate.skip_binder().trait_ref;
-                        let self_ty = trait_ref.self_ty();
-                        let (trait_desc, self_desc) = with_no_trimmed_paths!({
-                            let trait_desc = trait_ref.print_only_trait_path().to_string();
-                            let self_desc = if self_ty.has_concrete_skeleton() {
-                                Some(self_ty.to_string())
+                        if !trait_ref.references_error() {
```
Comment (bhbs) [inline compiler/rustc_trait_selection/src/traits/select/mod.rs:374]: Oops, I just added one conditional branch here, but the difference looks a little big.

File: src/test/ui/issues/issue-105138.rs [hunk 2]
```diff
@@ -0,0 +1,20 @@
+// Regression test for #105138.
```
Comment (compiler-errors) [inline src/test/ui/issues/issue-105138.rs:1]: Please move this to a better directory in `ui/` and give it a more descriptive name. Afterwards, this can be approved.

File: compiler/rustc_trait_selection/src/traits/select/mod.rs (hunk 1 above)
Comment (compiler-errors) [reply compiler/rustc_trait_selection/src/traits/select/mod.rs:374]: Looks better when whitespace is disabled.

File: src/test/ui/issues/issue-105138.rs (hunk 2 above)
Comment (bhbs) [reply src/test/ui/issues/issue-105138.rs]: Moved to `src/test/ui/trait-bounds/impl-bound-with-references-error.rs` 👍

File: compiler/rustc_trait_selection/src/traits/select/mod.rs (hunk 1 above)
Comment (bhbs) [reply compiler/rustc_trait_selection/src/traits/select/mod.rs:374]: Nice, thank you!
