### PR TITLE
Separate unsized locals

### LINKED ISSUE #71694: Separate `unsized_locals` into "sound" and "unsound" (i.e. incorrectly implemented) parts
Spawned off of #71416 

Here is the example from that issue's description:

This is a variant of https://github.com/rust-lang/rust/issues/68304 that was not fixed by https://github.com/rust-lang/rust/pull/71170:
```rust
#![feature(unsized_locals)]

use std::any::Any;

#[repr(align(256))]
#[allow(dead_code)]
struct A {
    v: u8
}

impl A {
    fn f(&self) -> *const A {
        assert_eq!(self as *const A as usize % 256, 0);
        self
    }
}

fn mk() -> Box<dyn Any> {
    Box::new(A { v: 4 })
}

fn main() {
    let x = *mk();
    let dwncst = x.downcast_ref::<A>().unwrap();
    let addr = dwncst.f();
    assert_eq!(addr as usize % 256, 0);
}
```

What we want is to factor `unsized_locals` into two features (either giving both fresh names or just allocating one fresh name, it doesn't matter all that much), where one of the two named features would *only* enable support for cases that we have actually implemented (correctly).

 * Specifically, we do not currently handle alignment of `dyn Value` because we would need to query that alignment dynamically and adjust the stack address accordingly (and allowing for such adjustment by allocating `size + (align  1)` ... which actually I guess would have to be done via `alloca` if we cannot put an upper-bound on `align` ... anyway I digress...)

Anyway, this issue is *just* about creating the new feature name(s), and splitting the current `unsized_locals` support accordingly, so that crates (specifically the internals of `libstd`) can opt into supporting *just* the construct that we know we have actually implemented properly.

### PR DESCRIPTION
**Pull request by spastorino**
Closes #71694

Takes over again #72029 and #74971

cc @RalfJung @oli-obk @pnkfelix @eddyb as they've participated in previous reviews of this PR.

### CODE REVIEW

File: compiler/rustc_typeck/src/check/gather_locals.rs [hunk 1]
```diff
@@ -6,15 +6,24 @@ use rustc_infer::infer::type_variable::{TypeVariableOrigin, TypeVariableOriginKi
...
 use rustc_span::Span;
 use rustc_trait_selection::traits;
+use std::mem;
 
 pub(super) struct GatherLocalsVisitor<'a, 'tcx> {
     fcx: &'a FnCtxt<'a, 'tcx>,
     parent_id: hir::HirId,
+    // params are special cases of pats, but we want to handle them as
+    // *distinct* cases. so track when we are hitting a pat *within* an fn
+    // param.
```
Comment (eddyb) [inline compiler/rustc_typeck/src/check/gather_locals.rs:16]: params -> parameters, pat -> pattern

File: compiler/rustc_mir/src/borrow_check/type_check/mod.rs [hunk 2]
```diff
@@ -1717,9 +1719,9 @@ impl<'a, 'tcx> TypeChecker<'a, 'tcx> {
                     );
                 }
 
-                // When `#![feature(unsized_locals)]` is not enabled,
+                // When `unsized_fn_params` or `unsized_locals` is not enabled,
```
Comment (RalfJung) [inline compiler/rustc_mir/src/borrow_check/type_check/mod.rs:1722]: Shouldn't this be "When X and Y are both not enabled"?

File: compiler/rustc_typeck/src/check/gather_locals.rs [hunk 3]
```diff
@@ -6,15 +6,24 @@ use rustc_infer::infer::type_variable::{TypeVariableOrigin, TypeVariableOriginKi
...
 
 impl<'a, 'tcx> GatherLocalsVisitor<'a, 'tcx> {
-    pub(super) fn new(fcx: &'a FnCtxt<'a, 'tcx>, parent_id: hir::HirId) -> Self {
-        Self { fcx, parent_id }
+    pub(super) fn new(
+        fcx: &'a FnCtxt<'a, 'tcx>,
+        parent_id: hir::HirId,
+        outermost_fn_param_pat: bool,
+    ) -> Self {
+        Self { fcx, parent_id, outermost_fn_param_pat }
```
Comment (RalfJung) [inline compiler/rustc_typeck/src/check/gather_locals.rs:26]: Wouldn't it make more sense to always set `outermost_fn_param_pat: false`? Seems like some internal tracking that we wouldn't want the outside world to control.

File: src/test/ui/unsized-locals/unsized-local-pat.rs [hunk 4]
```diff
@@ -0,0 +1,11 @@
+#![feature(box_patterns)]
+#![feature(unsized_fn_params)]
+
```
Comment (RalfJung) [inline src/test/ui/unsized-locals/unsized-local-pat.rs:3]:
```suggestion

// Ensure that even with unsized_fn_params, unsized types in parameter patterns are not accepted.

```

File: src/test/ui/unsized-locals/unsized-locals-using-unsized-fn-params.rs [hunk 5]
```diff
@@ -0,0 +1,7 @@
+#![feature(unsized_fn_params)]
+
```
Comment (RalfJung) [inline src/test/ui/unsized-locals/unsized-locals-using-unsized-fn-params.rs:2]:
```suggestion

// Ensure that even with unsized_fn_params, unsized locals are not accepted.

```
Though I peronally would have merged this test and unsized-local-pat into one -- the common theme is "make sure `unsized_fn_params` does not accept too many things".

**Comment by spastorino** [comment]
@RalfJung have addressed all your comments, let me know if there's something else to fix.

File: compiler/rustc_mir/src/borrow_check/type_check/mod.rs [hunk 6]
```diff
@@ -1717,9 +1719,9 @@ impl<'a, 'tcx> TypeChecker<'a, 'tcx> {
                     );
                 }
 
-                // When `#![feature(unsized_locals)]` is not enabled,
+                // When `unsized_fn_params` and `unsized_locals` is not enabled,
```
Comment (RalfJung) [inline compiler/rustc_mir/src/borrow_check/type_check/mod.rs:1722]:
```suggestion
                // When `unsized_fn_params` and `unsized_locals` are both not enabled,
```

File: compiler/rustc_mir/src/borrow_check/type_check/mod.rs [hunk 7]
```diff
@@ -1880,9 +1882,9 @@ impl<'a, 'tcx> TypeChecker<'a, 'tcx> {
             LocalKind::Var | LocalKind::Temp => {}
         }
 
-        // When `#![feature(unsized_locals)]` is enabled, only function calls
+        // When `unsized_fn_params` or `unsized_locals` is enabled, only function calls
         // and nullary ops are checked in `check_call_dest`.
-        if !self.tcx().features().unsized_locals {
+        if !(self.tcx().features().unsized_locals || self.tcx().features().unsized_fn_params) {
```
Comment (RalfJung) [inline compiler/rustc_mir/src/borrow_check/type_check/mod.rs:1887]: FWIW, I am a bit worried about how fragile this is, relying on 3 locations to use the same boolean condition. Can you move that condition into a helper function that is called in all 3 places to prevent that code from diverging?

**Comment by spastorino** [comment]
@RalfJung all your new comments are addressed

File: compiler/rustc_mir/src/borrow_check/type_check/mod.rs [hunk 8]
```diff
@@ -1456,9 +1456,7 @@ impl<'a, 'tcx> TypeChecker<'a, 'tcx> {
                 }
 
                 self.check_rvalue(body, rv, location);
-                if !(self.tcx().features().unsized_locals
-                    || self.tcx().features().unsized_fn_params)
-                {
+                if !self.tcx().features().is_unsized() {
```
Comment (RalfJung) [inline compiler/rustc_mir/src/borrow_check/type_check/mod.rs:1459]: IMO it would be better to add a private helper in this file, the function seems awfully specific otherwise.

Also, "is" is a weird prefix here -- that sounds like it tests whether some particular type/variable *is* unsized. Maybe more like `unsized_feature()` or `unsized_feature_enabled()` or so?

File: src/test/ui/unsized-locals/unsized-locals-using-unsized-fn-params.rs [hunk 9]
```diff
@@ -0,0 +1,9 @@
...
+// Ensure that even with unsized_fn_params, unsized locals are not accepted.
```
Comment (RalfJung) [inline src/test/ui/unsized-locals/unsized-locals-using-unsized-fn-params.rs:3]: What is the reason to have this in a separate test from unsized-local-pat.rs? The purpose seems to be the same -- make sure the feature gate does not accept too many things.

**Comment by RalfJung** [comment]
LGTM except for that question around the tests.

However, I cannot review the analysis changes here, I have no familiarity with that code. Hopefully @pnkfelix can take care of that. :)

File: src/test/ui/unsized-locals/unsized-locals-using-unsized-fn-params.rs (hunk 9 above)
Comment (spastorino) [reply src/test/ui/unsized-locals/unsized-locals-using-unsized-fn-params.rs]: :+1:, I've merged both tests.

File: src/test/ui/unsized-locals/unsized-local-pat.rs [hunk 10]
```diff
@@ -10,4 +10,8 @@ fn f1(box box _b: Box<Box<[u8]>>) {}
 fn f2((_x, _y): (i32, [i32])) {}
 //~^ ERROR: the size for values of type `[i32]` cannot be known at compilation time [E0277]
 
-fn main() {}
+fn main() {
+    let foo: Box<[u8]> = Box::new(*b"foo");
+    let _foo: [u8] = *foo;
+    //~^ ERROR: the size for values of type `[u8]` cannot be known at compilation time [E0277]
+}
```
Comment (RalfJung) [inline src/test/ui/unsized-locals/unsized-local-pat.rs:17]: Now the file name doesn't make much sense any more though, and the comment at the top of the file.^^
```
// Ensure that even with unsized_fn_params, we do not accept unsized types
// for other locals of parameter patterns.
```

Comment (spastorino) [reply src/test/ui/unsized-locals/unsized-local-pat.rs:17]: :+1:, force pushed again.

**Comment by spastorino** [comment]
Rebased again to solve conflicts.

**Comment by oli-obk** [comment]
I think Felix has his hands full this week. I went over the code one more time, can't see any reason not to merge now

@bors r+
