### PR TITLE
fix APITIT being treated as a normal generic parameter in suggestions

### LINKED ISSUE #126395: APITIT get treated as ordinary params in "not all trait impls implemented" error
```rust
// crate dep
pub trait Trait {
    fn foo(_: impl Sized);
    fn bar<T>(_: impl Sized);
}
// root
use dep::*;

struct Local;
impl Trait for Local {}
```
results in the following error:
```
error[E0046]: not all trait items implemented, missing: `foo`, `bar`
 --> src/main.rs:4:1
  |
4 | impl Trait for Local {}
  | ^^^^^^^^^^^^^^^^^^^^ missing `foo`, `bar` in implementation
  |
  = help: implement the missing item: `fn foo<impl Sized>(_: impl Sized) { todo!() }`
  = help: implement the missing item: `fn bar<T, impl Sized>(_: impl Sized) { todo!() }`
```
This wrongly includes the APITIT in the generic args. It should be
```
  = help: implement the missing item: `fn foo(_: impl Sized) { todo!() }`
  = help: implement the missing item: `fn bar<T>(_: impl Sized) { todo!() }`
```

### PR DESCRIPTION
**Pull request by Qelxiros**
closes rust-lang/rust#126395

### CODE REVIEW

File: compiler/rustc_hir_analysis/src/check/mod.rs [hunk 1]
```diff
@@ -356,6 +355,10 @@ fn bounds_from_generic_predicates<'tcx>(
     let mut types_str = vec![];
     for (ty, bounds) in types {
         if let ty::Param(_) = ty.kind() {
+            let ty_str = ty.to_string();
+            if ty_str.contains("impl ") {
```
Comment (hkBst) [inline compiler/rustc_hir_analysis/src/check/mod.rs]: This seems like a fragile way to do detection.

Comment (Qelxiros) [reply compiler/rustc_hir_analysis/src/check/mod.rs]: I agree, but (a) as far as I can tell, the `Interner`'s `ParamTy` only has to implement `ParamLike`, which doesn't expose whether the generic parameter came from an impl Trait (specifically across crate boundaries); and (b) I, for one, can't come up with a way (other than impl Trait) to create a generic parameter whose name contains a space. If I've overlooked something, please let me know.

Comment (hkBst) [reply compiler/rustc_hir_analysis/src/check/mod.rs]: Someone more knowledgeable than me will have to share the better way (if there is one).

Comment (fmease) [reply compiler/rustc_hir_analysis/src/check/mod.rs]: If you have access to the surrounding `generics` (e.g., via `generics_of(owner_def_id)`), you can instead check if `generics.param_at(param.index, tcx).kind.is_synthetic()`.

Comment (Qelxiros) [reply compiler/rustc_hir_analysis/src/check/mod.rs]: Thanks!

File: compiler/rustc_hir_analysis/src/check/mod.rs [hunk 2]
```diff
@@ -330,6 +329,7 @@ fn default_body_is_unstable(
 fn bounds_from_generic_predicates<'tcx>(
     tcx: TyCtxt<'tcx>,
     predicates: impl IntoIterator<Item = (ty::Clause<'tcx>, Span)>,
+    assoc: Option<ty::AssocItem>,
```
Comment (BoxyUwU) [inline compiler/rustc_hir_analysis/src/check/mod.rs]:
```suggestion
    assoc: ty::AssocItem,
```

File: compiler/rustc_hir_analysis/src/check/mod.rs [hunk 3]
```diff
@@ -354,8 +354,14 @@ fn bounds_from_generic_predicates<'tcx>(
 
     let mut where_clauses = vec![];
     let mut types_str = vec![];
```
Comment (BoxyUwU) [inline compiler/rustc_hir_analysis/src/check/mod.rs]:
```suggestion
    let types_str = {
        ...
        let param_strs = tcx.generics_of(a.def_id).own_params().iter().map(|param| /* logic for turning param into string repr, you can do `is_synthetic` filtering here */).collect();
        ...
      }
```

**Review by BoxyUwU — COMMENTED** [review]
I think this function fundamentally works the wrong way (not ur fault, it's prexisting).

It seems to:
1. Iterate over the list of where clauses on an item
2. Look at where clauses that are either `Type<...>: Trait<..>` or `Type<...>: Trait<..., Assoc<...> = ...>`
3. Collect a map (`types`) of all those `Type<...>` to the trait on the rhs of the `:`. e.g. if we have `where u32: Trait, u64: OtherTrait, T: Trait + OtherTrait`, we'd wind up with `[u32 => Trait, u64 => OtherTrait, T => { Trait, OtherTrait }]`
4. We then iterate that map filtering to only keys that are type parameters, and use that to reconstruct the list of generic parameters defined on the item.

this is *completely* incoherent. it assumes multiple things that aren't true:
- Type parameters are the only kind of generic parameters. You can't have `const N: usize` as the self type of a trait bound, so it never winds up in `types` so we'll never wind up putting const generics in the final `generics` string. [playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2024&gist=8a6c6789c3123f616aeca43dd7e0383e) (run `test`)
- Type parameters are *always* used in the self type of a trait bound. This was not true on stable until *very* recently when we made `T: ?Sized` be sugar for `T: MetaSized`. You can still observe this with the `rustc_no_implicit_bounds` attr: [playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2024&gist=01c4cb4acbb2d87af6a805e9d9fd3ba3) (run `test`). Also this means that right now `T: ?Sized` on stable gets re-sugared as `T: MetaSized` which is wrong

---

Instead, we should *unconditionally* accept an `AssocItem` so that we can *always* call `generics_of` to get the list of generic parameters defined on the item.

You can then independently construct the `types_str` by iterating over the generic parameters from `generics_of` and fetching any bounds on them from the `types` map.

The existing for loop over `types` can be left mostly as-is, just removing the parts of it that mutate types_str. 

*[View changes since this review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/rust/145929/94722cabf4983abcbe5088c1b8e81517ba2a7126..ac15a624b1c5a772fdb91af7a6e896625a086c2d)*
