### PR TITLE
Pass objcopy args for stripping on OSX

### LINKED ISSUE #135028: Rustc strips all symbols on MacOS when strip = "debuginfo" is specified, but not when strip = "symbols" is specified
Consider this basic example:

```rust
fn main() {
    std::thread::sleep(std::time::Duration::from_secs_f64(1.0));
}
```

When compiled with `cargo build` and the following `Cargo.toml`:

```toml
[profile.dev]
debug = false
strip = "symbols"
```

we see the following profile with `samply record`:

Image

That is, all symbols are still there. However, when we instead build with

```toml
[profile.dev]
debug = false
strip = "debuginfo"
```

we see the following profile:

Image

I believe this is a bug, as the documentation for `strip` specifies that `symbols` is supposed to be a more aggressive stripping than `debuginfo`, which is supposed to leave backtrace information *mostly* intact. We see the opposite behavior.

---

The following lines of code are suspect: https://github.com/rust-lang/rust/blob/bf6f8a4d328f7f3b0f6ea8205ad28591cc11aafd/compiler/rustc_codegen_ssa/src/back/link.rs#L1103-L1118

`-S` on `rust-objcopy` is documented as such:

```
  -S                      Alias for --strip-all
```

It does not seem appropriate to be used in the `Debuginfo` branch, but omitted in the `Symbols` branch.

### PR DESCRIPTION
**Pull request by Noratrieb**
When `-Cstrip` was changed in #131405 to use the bundled rust-objcopy instead of /usr/bin/strip on OSX, strip-like arguments were preserved.

But strip and objcopy are, while being the same binary, different, they have different defaults depending on which binary they are. Notably, strip strips everything by default, and objcopy doesn't strip anything by default.

Additionally, `-S` actually means `--strip-all`, so debuginfo stripped everything and symbols didn't strip anything.

We now correctly pass `--strip-debug` and `--strip-all`.

fixes #135028

try-job: aarch64-apple
try-job: dist-aarch64-apple

### CODE REVIEW

**Comment by klensy** [comment]
`We want to strip binaries, so we would use llvm-objcopy but not llvm-strip`. Can this use `llvm-strip` instead?

File: compiler/rustc_codegen_ssa/src/back/link.rs [hunk 1]
```diff
@@ -1104,14 +1104,14 @@ fn link_natively(
         let stripcmd = "rust-objcopy";
         match (strip, crate_type) {
             (Strip::Debuginfo, _) => {
-                strip_symbols_with_external_utility(sess, stripcmd, out_filename, &["-S"])
+                strip_with_external_utility(sess, stripcmd, out_filename, &["--strip-debug"])
             }
             // Per the manpage, `-x` is the maximum safe strip level for dynamic libraries. (#93988)
             (Strip::Symbols, CrateType::Dylib | CrateType::Cdylib | CrateType::ProcMacro) => {
-                strip_symbols_with_external_utility(sess, stripcmd, out_filename, &["-x"])
+                strip_with_external_utility(sess, stripcmd, out_filename, &["-x"])
```
Comment (jieyouxu) [inline compiler/rustc_codegen_ssa/src/back/link.rs:1111]: Suggestion [DISCARD-ALL 1/2]: can we spell out the full flag for this as well? `llvm-objcopy` docs say that `-x` is

> --discard-all, -x

>   Remove most local symbols from the output. Different file formats may limit this to a subset of the local symbols. For example, file and section symbols in ELF objects will not be discarded. Additionally, remove all debug sections.

This happens to align with `llvm-strip`, unlike `-S` or no-flag.

- https://llvm.org/docs/CommandGuide/llvm-strip.html#cmdoption-llvm-strip-discard-all
- https://llvm.org/docs/CommandGuide/llvm-objcopy.html#cmdoption-llvm-objcopy-discard-all

File: compiler/rustc_codegen_ssa/src/back/link.rs [hunk 2]
```diff
@@ -1127,9 +1127,7 @@ fn link_natively(
         let stripcmd = if !sess.host.is_like_solaris { "rust-objcopy" } else { "/usr/bin/strip" };
         match strip {
             // Always preserve the symbol table (-x).
-            Strip::Debuginfo => {
-                strip_symbols_with_external_utility(sess, stripcmd, out_filename, &["-x"])
-            }
+            Strip::Debuginfo => strip_with_external_utility(sess, stripcmd, out_filename, &["-x"]),
```
Comment (jieyouxu) [inline compiler/rustc_codegen_ssa/src/back/link.rs:1130]: Suggestion [DISCARD-ALL 2/2]: we should also be able to spell out `--discard-all`, AFAICT.

**Review by jieyouxu — APPROVED** [review]
Thanks, the changes LGTM with two nits. r=me if try job comes back green. I don't have access to a native macOS environment to try this locally though.

File: compiler/rustc_codegen_ssa/src/back/link.rs (hunk 2 above)
Comment (Noratrieb) [reply compiler/rustc_codegen_ssa/src/back/link.rs:1130]: I would prefer to not change the -x, to keep the changes minimal.

Comment (jieyouxu) [reply compiler/rustc_codegen_ssa/src/back/link.rs:1130]: That's fine (if this is intended for a fix-forward to potentially backport to address the regression)

Comment (jieyouxu) [reply compiler/rustc_codegen_ssa/src/back/link.rs:1130]: (Filed #135038 as an easy follow-up)

File: tests/run-make/strip/rmake.rs [hunk 3]
```diff
@@ -0,0 +1,42 @@
...
+    // We use DW_ (the start of any DWARF name) to check that some debuginfo is present.
+    let dwarf_indicator = "DW_";
+
+    let test_symbol = "hey_i_get_compiled";
+    let binary = &bin_name("hello");
+
+    // Avoid checking debuginfo on darwin, because it is not actually affected by strip.
+    // Darwin *never* puts debuginfo in the main binary (-Csplit-debuginfo=off just removes it),
+    // so we never actually have any debuginfo in there, so we can't check that it's present.
+    let do_debuginfo_check = !is_darwin();
```
Comment (jieyouxu) [inline tests/run-make/strip/rmake.rs:17]: Remark: this is observed in the `split-debuginfo` run-make test

**Comment by Noratrieb** [comment]
Okay, had some troubles with the test. Turns out MacOS never puts debuginfo inline into the binary, so checking it with `llvm-dwarfdump` will never work. I was able to run it successfully on my Mac now. Will produce some builds anyways to double-check that it works fine.

@bors try

**Comment by apiraino** [comment]
Beta backport accepted as per compiler team [on Zulip](https://rust-lang.zulipchat.com/#narrow/channel/131828-t-compiler/topic/potential.20emergency.20beta.20backport/near/491634902). A backport PR will be authored by the release team at the end of the current development cycle.

@rustbot label +beta-accepted

**Comment by cuviper** [comment]
This was already backported to 1.84 (#135162) and 1.85 (#135163).

@rustbot label -beta-nominated
