### PR TITLE
core: Support variety of atomic widths in width-agnostic functions

### LINKED ISSUE #106795: Building core::sync::atomic for BPF target fails
Starting from the following commit and PR, which enabled CAS for BPF target and got included in nightly:

https://github.com/rust-lang/rust/pull/105708
https://github.com/rust-lang/rust/commit/11331b1030fba551df4c7fc2babd44496040030f

building the rustc library with the following config:

```
[build]
target = ["x86_64-unknown-linux-gnu", "bpfel-unknown-none"]
```

fails with:

https://gist.github.com/vadorovsky/c9a3892a85ea4425082d91a729ffcfb2

A similar failure can be observed when building an eBPF program based on https://github.com/aya-rs/aya:

https://gist.github.com/vadorovsky/7aaf1bbbb78ab0c0371fe65d90105007

That error occurs, because all these macros and functions which "can't be found", are annotated with `#[cfg(target_has_atomic = "8")]` or `#[cfg(target_has_atomic_load_store = "8")]`.

Example:

https://github.com/rust-lang/rust/blob/bfffe406fbcabb37b95779f2d252c4a277191e0d/library/core/src/sync/atomic.rs#L3014-L3016

Those annotations prevent those macros and functions to be built for BPF, because we enable only 64-bit atomics for BPF:

https://github.com/rust-lang/rust/blob/bfffe406fbcabb37b95779f2d252c4a277191e0d/compiler/rustc_target/src/spec/bpf_base.rs#L25-L26

A quick fix to make the build fix successful is changing annotations to:

```rust
#[cfg(any(
    target_has_atomic = "8",
    target_has_atomic = "16",
    target_has_atomic = "32",
    target_has_atomic = "64",
    target_has_atomic = "128",
    target_has_atomic = "ptr"
))]
```

I made this change on my local branch:

https://github.com/vadorovsky/rust/commit/041978bde712998308203c02715f046e31bd2f47

It fixes the core library build, however, it doesn't make the most of atomic operations actually working. I made a test Aya-based project where I tried to use all atomic operations on `AtomicU64`:

https://github.com/vadorovsky/aya-examples/tree/main/atomic
https://github.com/vadorovsky/aya-examples/blob/main/atomic/atomic-ebpf/src/main.rs

But pretty much every atomic operation except `store`, `swap` and assigning to mutable raw pointer triggers various bpf-linker / LLVM errors like this one (when using `fetch_add`):

```
     Running `rustc --crate-name atomic --edition=2021 src/main.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --diagnostic-width=274 --crate-type bin --emit=dep-info,link -C opt-level=3 -C panic=abort -C lto -C codegen-units=1 -C metadata=0df4b88cd767cdfe -C extra-filename=-0df4b88cd767cdfe --out-dir /home/vadorovsky/repos/aya-examples/atomic/atomic-ebpf/../target/bpfel-unknown-none/debug/deps --target bpfel-unknown-none -L dependency=/home/vadorovsky/repos/aya-examples/atomic/atomic-ebpf/../target/bpfel-unknown-none/debug/deps -L dependency=/home/vadorovsky/repos/aya-examples/atomic/atomic-ebpf/../target/debug/deps --extern atomic_common=/home/vadorovsky/repos/aya-examples/atomic/atomic-ebpf/../target/bpfel-unknown-none/debug/deps/libatomic_common-9766a80d5f618b6a.rlib --extern aya_bpf=/home/vadorovsky/repos/aya-examples/atomic/atomic-ebpf/../target/bpfel-unknown-none/debug/deps/libaya_bpf-6a252bb26304b8e6.rlib --extern aya_log_ebpf=/home/vadorovsky/repos/aya-examples/atomic/atomic-ebpf/../target/bpfel-unknown-none/debug/deps/libaya_log_ebpf-5apf/../target/bpfel-unknown-none/debug/deps/libcore-88a9f41520fe0405.rlib' -Z unstable-options`
error: linking with `bpf-linker` failed: signal: 6 (SIGABRT) (core dumped)
  |
  = note: LC_ALL="C" PATH="/home/vadorovsky/repos/rust/build/x86_64-unknown-linux-gnu/stage1/lib/rustlib/x86_64-unknown-linux-gnu/bin:/home/vadorovsky/.npm-global/bin:/home/vadorovsky/solana/bin:/home/vadorovsky/.local/share/solana/install/active_release/bin:/home/vadorovsky/.local/llvm/bin:/home/vadorovsky/go/bin:/home/vadorovsky/.cargo/bin:/home/vadorovsky/miniconda3/bin:/home/vadorovsky/miniconda3/condabin:/home/vadorovsky/.cargo/bin:/home/vadorovsky/.local/bin:/home/vadorovsky/bin:/usr/local/bin:/usr/bin:/usr/bin" VSLANG="1033" "bpf-linker" "--export-symbols" "/tmp/rustcOxihKW/symbols" "/tmp/rustcOxihKW/symbols.o" "/home/vadorovsky/repos/aya-examples/atomic/atomic-ebpf/../target/bpfel-unknown-none/debug/deps/atomic-0df4b88cd767cdfe.atomic.9f2f50cf-cgu.0.rcgu.o" "-L" "/home/vadorovsky/repos/aya-examples/atomic/atomic-ebpf/../target/bpfel-unknown-none/debug/deps" "-L" "/home/vadorovsky/repos/aya-examples/atomic/atomic-ebpf/../target/debug/deps" "-L" "/home/vadorovsky/repos/rust/build/x86_64-unknown-linux-gnu/stage1/lib/rustlib/bpfel-unknown-none/lib" "--cpu" "generic" "--cpu-features" "" "-L" "/home/vadorovsky/repos/rust/build/x86_64-unknown-linux-gnu/stage1/lib/rustlib/bpfel-unknown-none/lib" "-o" "/home/vadorovsky/repos/aya-examples/atomic/atomic-ebpf/../target/bpfel-unknown-none/debug/deps/atomic-0df4b88cd767cdfe" "-O3" "--debug"
  = note: 06:08:59 [ERROR] fatal error: "Cannot select: t88: i64,ch = AtomicLoad<(dereferenceable load monotonic (s64) from %ir.7)> t1211, FrameIndex:i64<5>\n  t87: i64 = FrameIndex<5>\nIn function: atomic"
          PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace.
          Stack dump:
          0.    Running pass 'Function Pass Manager' on module 'atomic-0df4b88cd767cdfe'.
          1.    Running pass 'BPF DAG->DAG Pattern Instruction Selection' on function '@atomic'
          06:08:59 [ INFO] command line: "bpf-linker --export-symbols /tmp/rustcOxihKW/symbols /tmp/rustcOxihKW/symbols.o /home/vadorovsky/repos/aya-examples/atomic/atomic-ebpf/../target/bpfel-unknown-none/debug/deps/atomic-0df4b88cd767cdfe.atomic.9f2f50cf-cgu.0.rcgu.o -L /home/vadorovsky/repos/aya-examples/atomic/atomic-ebpf/../target/bpfel-unknown-none/debug/deps -L /home/vadorovsky/repos/aya-examples/atomic/atomic-ebpf/../target/debug/deps -L /home/vadorovsky/repos/rust/build/x86_64-unknown-linux-gnu/stage1/lib/rustlib/bpfel-unknown-none/lib --cpu generic --cpu-features  -L /home/vadorovsky/repos/rust/build/x86_64-unknown-linux-gnu/stage1/lib/rustlib/bpfel-unknown-none/lib -o /home/vadorovsky/repos/aya-examples/atomic/atomic-ebpf/../target/bpfel-unknown-none/debug/deps/atomic-0df4b88cd767cdfe -O3 --debug"
          06:08:59 [ INFO] LLVM command line: ["bpf-linker", "--bpf-expand-memcpy-in-order"]
          06:08:59 [ INFO] linking file "/tmp/rustcOxihKW/symbols.o" type elf
          06:08:59 [ WARN] ignoring file "/tmp/rustcOxihKW/symbols.o": no embedded bitcode
          06:08:59 [ INFO] linking file "/home/vadorovsky/repos/aya-examples/atomic/atomic-ebpf/../target/bpfel-unknown-none/debug/deps/atomic-0df4b88cd767cdfe.atomic.9f2f50cf-cgu.0.rcgu.o" type bitcode
          06:08:59 [ INFO] emitting LLVMObjectFile to "/home/vadorovsky/repos/aya-examples/atomic/atomic-ebpf/../target/bpfel-unknown-none/debug/deps/atomic-0df4b88cd767cdfe"
```

Or this one (when using `compare_exchange`):

```
     Running `rustc --crate-name atomic --edition=2021 src/main.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --diagnostic-width=274 --crate-type bin --emit=dep-info,link -C opt-level=3 -C panic=abort -C lto -C codegen-units=1 -C metadata=0df4b88cd767cdfe -C extra-filename=-0df4b88cd767cdfe --out-dir /home/vadorovsky/repos/aya-examples/atomic/atomic-ebpf/../target/bpfel-unknown-none/debug/deps --target bpfel-unknown-none -L dependency=/home/vadorovsky/repos/aya-examples/atomic/atomic-ebpf/../target/bpfel-unknown-none/debug/deps -L dependency=/home/vadorovsky/repos/aya-examples/atomic/atomic-ebpf/../target/debug/deps --extern atomic_common=/home/vadorovsky/repos/aya-examples/atomic/atomic-ebpf/../target/bpfel-unknown-none/debug/deps/libatomic_common-9766a80d5f618b6a.rlib --extern aya_bpf=/home/vadorovsky/repos/aya-examples/atomic/atomic-ebpf/../target/bpfel-unknown-none/debug/deps/libaya_bpf-6a252bb26304b8e6.rlib --extern aya_log_ebpf=/home/vadorovsky/repos/aya-examples/atomic/atomic-ebpf/../target/bpfel-unknown-none/debug/deps/libaya_log_ebpf-5apf/../target/bpfel-unknown-none/debug/deps/libcore-88a9f41520fe0405.rlib' -Z unstable-options`
error: linking with `bpf-linker` failed: signal: 6 (SIGABRT) (core dumped)
  |
  = note: LC_ALL="C" PATH="/home/vadorovsky/repos/rust/build/x86_64-unknown-linux-gnu/stage1/lib/rustlib/x86_64-unknown-linux-gnu/bin:/home/vadorovsky/.npm-global/bin:/home/vadorovsky/solana/bin:/home/vadorovsky/.local/share/solana/install/active_release/bin:/home/vadorovsky/.local/llvm/bin:/home/vadorovsky/go/bin:/home/vadorovsky/.cargo/bin:/home/vadorovsky/miniconda3/bin:/home/vadorovsky/miniconda3/condabin:/home/vadorovsky/.cargo/bin:/home/vadorovsky/.local/bin:/home/vadorovsky/bin:/usr/local/bin:/usr/bin:/usr/bin" VSLANG="1033" "bpf-linker" "--export-symbols" "/tmp/rustcAlOvk2/symbols" "/tmp/rustcAlOvk2/symbols.o" "/home/vadorovsky/repos/aya-examples/atomic/atomic-ebpf/../target/bpfel-unknown-none/debug/deps/atomic-0df4b88cd767cdfe.atomic.9f2f50cf-cgu.0.rcgu.o" "-L" "/home/vadorovsky/repos/aya-examples/atomic/atomic-ebpf/../target/bpfel-unknown-none/debug/deps" "-L" "/home/vadorovsky/repos/aya-examples/atomic/atomic-ebpf/../target/debug/deps" "-L" "/home/vadorovsky/repos/rust/build/x86_64-unknown-linux-gnu/stage1/lib/rustlib/bpfel-unknown-none/lib" "--cpu" "generic" "--cpu-features" "" "-L" "/home/vadorovsky/repos/rust/build/x86_64-unknown-linux-gnu/stage1/lib/rustlib/bpfel-unknown-none/lib" "-o" "/home/vadorovsky/repos/aya-examples/atomic/atomic-ebpf/../target/bpfel-unknown-none/debug/deps/atomic-0df4b88cd767cdfe" "-O3" "--debug"
  = note: 06:10:02 [ERROR] fatal error: "Cannot select: t88: i64,ch = AtomicLoad<(dereferenceable load monotonic (s64) from %ir.7)> t1211, FrameIndex:i64<5>\n  t87: i64 = FrameIndex<5>\nIn function: atomic"
          PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace.
          Stack dump:
          0.    Running pass 'Function Pass Manager' on module 'atomic-0df4b88cd767cdfe'.
          1.    Running pass 'BPF DAG->DAG Pattern Instruction Selection' on function '@atomic'
          06:10:02 [ INFO] command line: "bpf-linker --export-symbols /tmp/rustcAlOvk2/symbols /tmp/rustcAlOvk2/symbols.o /home/vadorovsky/repos/aya-examples/atomic/atomic-ebpf/../target/bpfel-unknown-none/debug/deps/atomic-0df4b88cd767cdfe.atomic.9f2f50cf-cgu.0.rcgu.o -L /home/vadorovsky/repos/aya-examples/atomic/atomic-ebpf/../target/bpfel-unknown-none/debug/deps -L /home/vadorovsky/repos/aya-examples/atomic/atomic-ebpf/../target/debug/deps -L /home/vadorovsky/repos/rust/build/x86_64-unknown-linux-gnu/stage1/lib/rustlib/bpfel-unknown-none/lib --cpu generic --cpu-features  -L /home/vadorovsky/repos/rust/build/x86_64-unknown-linux-gnu/stage1/lib/rustlib/bpfel-unknown-none/lib -o /home/vadorovsky/repos/aya-examples/atomic/atomic-ebpf/../target/bpfel-unknown-none/debug/deps/atomic-0df4b88cd767cdfe -O3 --debug"
          06:10:02 [ INFO] LLVM command line: ["bpf-linker", "--bpf-expand-memcpy-in-order"]
          06:10:02 [ INFO] linking file "/tmp/rustcAlOvk2/symbols.o" type elf
          06:10:02 [ WARN] ignoring file "/tmp/rustcAlOvk2/symbols.o": no embedded bitcode
          06:10:02 [ INFO] linking file "/home/vadorovsky/repos/aya-examples/atomic/atomic-ebpf/../target/bpfel-unknown-none/debug/deps/atomic-0df4b88cd767cdfe.atomic.9f2f50cf-cgu.0.rcgu.o" type bitcode
          06:10:02 [ INFO] emitting LLVMObjectFile to "/home/vadorovsky/repos/aya-examples/atomic/atomic-ebpf/../target/bpfel-unknown-none/debug/deps/atomic-0df4b88cd767cdfe"
```

I didn't investigate the bpf-linker / LLVM failures deeper yet. It might be related to the fact that BPF target is calling intrinsics manually and was written only with clang in mind. But again, I need more time to investigate.

But at this point I'm quite confident that we should just revert https://github.com/rust-lang/rust/pull/105708 and reconsider such change after we make sure it actually works and all the mentioned issues are fixed.

/cc @tomerze @alessandrod

### LINKED ISSUE #106845: Some functions in `core::sync` are annotated to only support targets with 8-bit atomic support
This issue was discussed at #106795 
and at https://github.com/rust-lang/rust/pull/106796#issuecomment-1382698625

Some functions in `core::sync` are defined to only compile if the target has 8-bit atomic support. While they should be compiled for all targets with atomic support.

This can cause unnecessary compilation issues when using a custom target json. 

This can probably be solved by changing the definitions to 
```rust
#[cfg(any(
    target_has_atomic = "8",
    target_has_atomic = "16",
    target_has_atomic = "32",
    target_has_atomic = "64",
    target_has_atomic = "128",
    target_has_atomic = "ptr"
))]
```
from
```rust
#[cfg(target_has_atomic = "8")]
```

like you can see at https://github.com/vadorovsky/rust/commit/041978bde712998308203c02715f046e31bd2f47

Examples:
https://github.com/rust-lang/rust/blob/bfffe406fbcabb37b95779f2d252c4a277191e0d/library/core/src/sync/atomic.rs#L3014-L3016
https://github.com/rust-lang/rust/blob/bfffe406fbcabb37b95779f2d252c4a277191e0d/library/core/src/sync/atomic.rs#L3047-L3049
https://github.com/rust-lang/rust/blob/bfffe406fbcabb37b95779f2d252c4a277191e0d/library/core/src/sync/atomic.rs#L3133-L3135

@vadorovsky  @alessandrod

### PR DESCRIPTION
**Pull request by vadorovsky**
Before this change, the following functions and macros were annotated with `#[cfg(target_has_atomic = "8")]` or
`#[cfg(target_has_atomic_load_store = "8")]`:

* `atomic_int`
* `strongest_failure_ordering`
* `atomic_swap`
* `atomic_add`
* `atomic_sub`
* `atomic_compare_exchange`
* `atomic_compare_exchange_weak`
* `atomic_and`
* `atomic_nand`
* `atomic_or`
* `atomic_xor`
* `atomic_max`
* `atomic_min`
* `atomic_umax`
* `atomic_umin`

However, none of those functions and macros actually depend on 8-bit width and they are needed for all atomic widths (16-bit, 32-bit, 64-bit etc.). Some targets might not support 8-bit atomics (i.e. BPF, if we would enable atomic CAS for it).

This change fixes that by removing the `"8"` argument from annotations, which results in accepting the whole variety of widths.

Fixes #106845
Fixes #106795

Signed-off-by: Michal Rostecki <vadorovsky@gmail.com>

### CODE REVIEW

**Comment by vadorovsky** [comment]
@alessandrod @tomerze

File: library/core/src/sync/atomic.rs [hunk 1]
```diff
@@ -3166,7 +3229,15 @@ unsafe fn atomic_and<T: Copy>(dst: *mut T, val: T, order: Ordering) -> T {
 }
 
 #[inline]
-#[cfg(target_has_atomic = "8")]
+// FIXME: Should be disabled for BPF
```
Comment (alessandrod) [inline library/core/src/sync/atomic.rs:3232]: I don't think this comment should be here

File: library/core/src/sync/atomic.rs [hunk 2]
```diff
@@ -2988,7 +3002,14 @@ atomic_int_ptr_sized! {
...
 #[inline]
-#[cfg(target_has_atomic = "8")]
+#[cfg(any(
+    target_has_atomic = "8",
+    target_has_atomic = "16",
+    target_has_atomic = "32",
+    target_has_atomic = "64",
+    target_has_atomic = "128",
+    target_has_atomic = "ptr"
+))]
```
Comment (alessandrod) [inline library/core/src/sync/atomic.rs:3012]: I think that here https://github.com/rust-lang/rust/blob/893938f64f7a9ff531b3968c9a9e79e0524606bd/compiler/rustc_session/src/config.rs#L942 you could add before the loop:

```rust
if atomic_cas {
    ret.insert((sym::target_has_atomic, None));
}
```

And then I think that would make `#[cfg(target_has_atomic))` work? And the same could be done for _load_store.

**Review by alessandrod — COMMENTED** [review]
Not really my place to review this, just my 2 cents

File: library/core/src/sync/atomic.rs (hunk 2 above)
Comment (vadorovsky) [reply library/core/src/sync/atomic.rs]: Done in a slightly different way (including `target_has_atomic_load_store` and doing that in the loop. PTAL

File: library/core/src/sync/atomic.rs [hunk 3]
```diff
@@ -565,7 +565,8 @@ impl AtomicBool {
         since = "1.50.0",
         note = "Use `compare_exchange` or `compare_exchange_weak` instead"
     )]
-    #[cfg(target_has_atomic = "8")]
+    #[cfg_attr(not(bootstrap), cfg(target_has_atomic))]
+    #[cfg_attr(bootstrap, cfg(target_has_atomic = "8"))]
```
Comment (bjorn3) [inline library/core/src/sync/atomic.rs:569]: Why is this necessary? If a target doesn't have 8bit atomics, it is impossible to do an AtomicBool compare_and_swap as AtomicBool is 8bit big, right? This change would add it anyway leading to either a compiler crash or miscompilation.

File: library/core/src/sync/atomic.rs [hunk 4]
```diff
@@ -3266,7 +3283,8 @@ unsafe fn atomic_umax<T: Copy>(dst: *mut T, val: T, order: Ordering) -> T {
 
 /// returns the min value (unsigned comparison)
 #[inline]
-#[cfg(target_has_atomic = "8")]
+#[cfg_attr(not(bootstrap), cfg(target_has_atomic))]
+#[cfg_attr(bootstrap, cfg(target_has_atomic = "8"))]
```
Comment (bjorn3) [inline library/core/src/sync/atomic.rs:3287]: This one makes sense though. It will only be codegened for sizes that are actually used and because it is private, this doesn't expose the ability to codegen an incorrect atomic size to the user.

File: compiler/rustc_session/src/config.rs [hunk 5]
```diff
@@ -963,6 +965,12 @@ fn default_configuration(sess: &Session) -> CrateConfig {
             }
         }
     }
+    if has_atomic {
+        ret.insert((sym::target_has_atomic_load_store, None));
+        if atomic_cas {
+            ret.insert((sym::target_has_atomic, None));
```
Comment (bjorn3) [inline compiler/rustc_session/src/config.rs:971]: This will likely need to be emitted only on nightly to avoid immediately stabilizing it.

File: library/core/src/sync/atomic.rs (hunk 3 above)
Comment (vadorovsky) [reply library/core/src/sync/atomic.rs]: Sorry, I got too aggressive with my `:%s` command. It should be fixed now - everything inside `AtomicBool` uses old annotations and I replaced them only in functions like the one below.

File: compiler/rustc_session/src/config.rs (hunk 5 above)
Comment (vadorovsky) [reply compiler/rustc_session/src/config.rs:971]: But then we will need to keep the `#[cfg(target_has_atomic]` annotations only for nightly as well, without stabilizing them? How do we do that?

And do you mean using

```rust
if sess.is_nightly_build() and has_atomic {
```

here?

Comment (vadorovsky) [reply compiler/rustc_session/src/config.rs:971]: > Libcore can use nightly features even on stable rustc.

Oh, I didn't know about that. I thought that adding the `target_has_atomic` symbol only for nightly would break the core build with stage0. But it seems like it works.

So I applied only that one line change. PTAL

**Comment by vadorovsky** [comment]
@bjorn3 ping. Does it look good for you now?

File: compiler/rustc_session/src/config.rs (hunk 5 above)
Comment (bjorn3) [reply compiler/rustc_session/src/config.rs:971]: Thanks!

**Comment by bjorn3** [comment]
LGTM. I will defer to `@scottmcm` for a final review as I'm not on the libs team.

**Comment by vadorovsky** [comment]
@scottmcm ping

Sorry for rushing, but it's quite urgent PR, we are trying to unblock BPF builds in Nightly.

**Comment by joshtriplett** [comment]
This seems fine to me for nightly.

I *think* this would probably be fine to stabilize, but I'd want to give some more detailed thought to the case of unsupported sizes on a given target. I *think* that works correctly, and the way @alessandrod explained it to me on Zulip made sense, but I'd want to doublecheck before stabilizing.

But for nightly:

@bors r+
