### PR TITLE
Fix bad intra-doc-link preprocessing

### LINKED ISSUE #147981: regression: ICE no resolution for ...
- https://crater-reports.s3.amazonaws.com/beta-rustdoc-1.91-2/beta-2025-09-21/gh/dybucc.randy-ng/log.txt
- https://crater-reports.s3.amazonaws.com/beta-rustdoc-1.91-2/beta-2025-09-21/reg/randy-ng-0.2.0/log.txt

```
[INFO] [stdout] error: internal compiler error: src/librustdoc/passes/collect_intra_doc_links.rs:454:17: no resolution for "Message::field@content" TypeNS DefId(0:128 ~ randy_ng[3fa0]::utils)
[INFO] [stdout]    --> src/utils.rs:160:5
[INFO] [stdout]     |
[INFO] [stdout] 160 |     pub(crate) const fn content(&self) -> &String {
[INFO] [stdout]     |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[INFO] [stdout] 
```

### PR DESCRIPTION
**Pull request by fmease**
How did rust-lang/rust#147981 happen?

1. We don't parse intra-doc links as Rust paths or qpaths. Instead they follow a very lenient bespoke grammar. We completely ignore Markdown links if they contain characters that don't match `/[a-zA-Z0-9_:<>, !*&;]/` (we don't even emit lint *broken-intra-doc-links* for these).
2. PR [#132748](https://github.com/rust-lang/rust/pull/132748) made rustdoc interpret more Markdown links as potential intra-doc links. Namely, if the link is surrounded by backticks (and some other conditions apply) then it doesn't matter if the (partially processed) link contains bad characters as defined above (cc `ignore_urllike && should_ignore_link(path_str)`).
3. However, rustdoc's `preprocess_link` must be kept in sync with a simplified counterpart in rustc. More specifically, whenever rustdoc's preprocessor returns a successful result then rustc's must yield the same result. Otherwise, rustc doesn't resolve the necessary links for rustdoc.
4. This uncovered a "dormant bug" / "mistake" in rustc's `preprocess_link`. Namely, when presented with a link like `struct@Type@suffix`, it didn't cut off the disambiguator if present (here: `struct@`). Instead it `rsplit('@')` which is incorrect if the "path" contains `@` itself (yielding `suffix` instead of `Type@suffix` here). Prior to PR [#132748](https://github.com/rust-lang/rust/pull/132748), a link like ``[`struct@Type@suffix`]`` was not considered a potential intra-doc link / worth querying rustc for. Now it is due to the backticks.
5. Finally, since rustc didn't record a resolution for `Type@suffix` (it only recorded `suffix` (to be `Res::Err`)), we triggered an assertion we have in place to catch cases like this.

Fixes rust-lang/rust#147981.

I didn't and still don't have the time to investigate if rust-lang/rust#132748 led to more rustc/rustdoc mismatches (after all, the PR made rustdoc's `preprocess_link` return `Some(Ok(_))` in more cases). I've at least added another much needed "warning banner" & made the existing one more flashy.

While this fixes a stable-to-beta regression, I don't think it's worth beta backporting, esp. since it's only P-medium and since the final 1.91 release steps commence today / the next days, so it would only be stressful to get it in on time. However, feel free to nominate.

<sub>(I've written such a verbose PR description since I tend to reread my old PR descriptions in the far future to fully freshen my memories when I have to work again in this area)</sub>

r? @lolbinarycat

### CODE REVIEW

File: src/librustdoc/passes/collect_intra_doc_links.rs [hunk 1]
```diff
@@ -938,23 +938,27 @@ pub(crate) struct PreprocessedMarkdownLink(
...
+/// - `Some(Ok(_))` if the link is valid
 ///
 /// `link_buffer` is needed for lifetime reasons; it will always be overwritten and the contents ignored.
 fn preprocess_link(
     ori_link: &MarkdownLink,
     dox: &str,
 ) -> Option<Result<PreprocessingInfo, PreprocessingError>> {
+    // IMPORTANT: To be kept in sync with the corresponding function in `rustc_resolve::rustdoc`.
+    // Namely, whenever this function successfully returns a `path_str` for a given input, the
+    // rustc counterpart *MUST* return the same result!
```
Comment (fmease) [inline src/librustdoc/passes/collect_intra_doc_links.rs]: Such a warning banner is clearly needed. They do get out of sync from time to time. Another older example: Issue https://github.com/rust-lang/rust/issues/110495 / PR https://github.com/rust-lang/rust/pull/110501.

File: src/librustdoc/passes/collect_intra_doc_links.rs [hunk 2]
```diff
@@ -938,23 +938,27 @@ pub(crate) struct PreprocessedMarkdownLink(
...
+
     // certain link kinds cannot have their path be urls,
     // so they should not be ignored, no matter how much they look like urls.
-    // e.g. [https://example.com/] is not a link to example.com.
+    // e.g. `[https://example.com/]` is not a link to example.com.
```
Comment (lolbinarycat) [inline src/librustdoc/passes/collect_intra_doc_links.rs]: I think this is confusing to use markdown syntax in a remark about markdown syntax, as `` `[https://example.com/]` `` and `[https://example.com/]` are different things, and we are talking about the latter, not the former.

Maybe we can just use `"` quotes?

File: src/librustdoc/passes/collect_intra_doc_links.rs [hunk 3]
```diff
@@ -938,23 +938,27 @@ pub(crate) struct PreprocessedMarkdownLink(
...
     let can_be_url = !matches!(
         ori_link.kind,
         LinkType::ShortcutUnknown | LinkType::CollapsedUnknown | LinkType::ReferenceUnknown
     );
 
-    // [] is mostly likely not supposed to be a link
+    // `[]` is mostly likely not supposed to be a link
```
Comment (lolbinarycat) [inline src/librustdoc/passes/collect_intra_doc_links.rs]: A bit less confusing than above, but I still am kinda meh on the idea of non-doc comments always using markdown syntax.  Maybe there's a valid reason for it I'm unaware of but idk.

File: compiler/rustc_resolve/src/rustdoc.rs [hunk 4]
```diff
@@ -393,19 +393,22 @@ pub fn has_primitive_or_keyword_or_attribute_docs(attrs: &[impl AttributeExt]) -
 }
 
 /// Simplified version of the corresponding function in rustdoc.
-/// If the rustdoc version returns a successful result, this function must return the same result.
-/// Otherwise this function may return anything.
 fn preprocess_link(link: &str) -> Box<str> {
+    // IMPORTANT: To be kept in sync with the corresponding function in rustdoc.
+    // Namely, whenever the rustdoc function returns a successful result for a
+    // given input, this function *MUST* return the same result!
```
Comment (lolbinarycat) [inline compiler/rustc_resolve/src/rustdoc.rs]: Somewhere in here we should mention that `path_str` is the field of `PreprocessingInfo` this return value corresponds to.

File: compiler/rustc_resolve/src/rustdoc.rs [hunk 5]
```diff
@@ -393,19 +393,22 @@ pub fn has_primitive_or_keyword_or_attribute_docs(attrs: &[impl AttributeExt]) -
...
+
     let link = link.replace('`', "");
     let link = link.split('#').next().unwrap();
     let link = link.trim();
-    let link = link.rsplit('@').next().unwrap();
+    let link = link.split_once('@').map_or(link, |(_, link)| link);
```
Comment (lolbinarycat) [inline compiler/rustc_resolve/src/rustdoc.rs]:
```suggestion
    let link = link.split_once('@').map_or(link, |(_, x)| x);
```

nit: 3 different variables named `link` all being referenced on the same line might be a bit much.

File: compiler/rustc_resolve/src/rustdoc.rs [hunk 6]
```diff
@@ -393,19 +393,22 @@ pub fn has_primitive_or_keyword_or_attribute_docs(attrs: &[impl AttributeExt]) -
...
     let link = link.strip_suffix("()").unwrap_or(link);
     let link = link.strip_suffix("{}").unwrap_or(link);
     let link = link.strip_suffix("[]").unwrap_or(link);
     let link = if link != "!" { link.strip_suffix('!').unwrap_or(link) } else { link };
     let link = link.trim();
-    strip_generics_from_path(link).unwrap_or_else(|_| link.into())
+    let link = strip_generics_from_path(link).unwrap_or_else(|_| link.into());
+    link
```
Comment (lolbinarycat) [inline compiler/rustc_resolve/src/rustdoc.rs]: Just curious: why?

**Review by lolbinarycat — COMMENTED** [review]
Seems like a simple fix, just a few nitpicks and questions

*[View changes since this review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/rust/148169/34a8c7368c84fc699fc83a8851a02f93fd655931..e18043b8c6699823457006232c802f109572803a)*

File: compiler/rustc_resolve/src/rustdoc.rs (hunk 5 above)
Comment (fmease) [reply compiler/rustc_resolve/src/rustdoc.rs]: I probably won't name it `x` since I'm not a fan of non-descriptive identifiers but I'll probably name it `right` or `suffix`.

File: compiler/rustc_resolve/src/rustdoc.rs (hunk 6 above)
Comment (fmease) [reply compiler/rustc_resolve/src/rustdoc.rs]: Leftover from printf dbg'ing, will revert

File: src/librustdoc/passes/collect_intra_doc_links.rs (hunk 2 above)
Comment (fmease) [reply src/librustdoc/passes/collect_intra_doc_links.rs]: I'll simply revert
