### PR TITLE
Suggest to create a new `const` item if the `fn` in the array is a `const fn`

### LINKED ISSUE #73734: Suggest creating a `const` when calling a `const` function in an array initializer
The following code:

```rust
fn main() {
    let strs: [String; 5] = [String::new(); 5];
}
```

gives the following error:

```
error[E0277]: the trait bound `std::string::String: std::marker::Copy` is not satisfied
 --> src/main.rs:2:29
  |
2 |     let strs: [String; 5] = [String::new(); 5];
  |                             ^^^^^^^^^^^^^^^^^^ the trait `std::marker::Copy` is not implemented for `std::string::String`
  |
  = note: the `Copy` trait is required because the repeated element will be copied

```

However, `String::new()` is a `const fn`, so this code can be made to compile by creating a new `const` item:

```rust
fn main() {
    const EMPTY: String = String::new();
    let strs: [String; 5] = [EMPTY; 5];
}
```

We should suggest this to user when a `const` function is being called in the array initializer.

<strike>Assuming that https://github.com/rust-lang/rfcs/pull/2920 is accepted, we could eventually suggest an inline `const` block.</strike>
On Nightly, we could suggest an inline `const` block.

### PR DESCRIPTION
**Pull request by henryboisdequin**
Fixes #73734. If the `fn` in the array repeat expression is a `const fn`, suggest creating a new `const` item. On nightly, suggest creating an inline `const` block. This PR also removes the `suggest_const_in_array_repeat_expressions` as it is no longer necessary. 

Example:

```rust
fn main() {
    // Should not compile but hint to create a new const item (stable) or an inline const block (nightly)
    let strings: [String; 5] = [String::new(); 5];
    println!("{:?}", strings);
}

```

Gives this error:

```
error[E0277]: the trait bound `std::string::String: std::marker::Copy` is not satisfied
 --> $DIR/const-fn-in-vec.rs:3:32
  |
2 |     let strings: [String; 5] = [String::new(); 5];
  |                             ^^^^^^^^^^^^^^^^^^ the trait `std::marker::Copy` is not implemented for `String`
  |
  = note: the `Copy` trait is required because the repeated element will be copied
```

With this change, this is the error message:

```
error[E0277]: the trait bound `String: Copy` is not satisfied
  --> $DIR/const-fn-in-vec.rs:3:32
   |
LL |     let strings: [String; 5] = [String::new(); 5];
   |                                ^^^^^^^^^^^^^^^^^^ the trait `Copy` is not implemented for `String`
   |
   = help: moving the function call to a new `const` item will resolve the error
```

### CODE REVIEW

**Comment by henryboisdequin** [comment]
I'm looking into the errors.

File: compiler/rustc_trait_selection/src/traits/error_reporting/suggestions.rs [hunk 1]
```diff
@@ -1868,22 +1868,18 @@ impl<'a, 'tcx> InferCtxtExt<'tcx> for InferCtxt<'a, 'tcx> {
             ObligationCauseCode::Coercion { source: _, target } => {
                 err.note(&format!("required by cast to type `{}`", self.ty_to_string(target)));
             }
-            ObligationCauseCode::RepeatVec(suggest_const_in_array_repeat_expressions) => {
-                err.note(
```
Comment (Aaron1011) [inline compiler/rustc_trait_selection/src/traits/error_reporting/suggestions.rs:1872]: It looks like you deleted this note by accident.

File: compiler/rustc_mir/src/transform/promote_consts.rs [hunk 2]
```diff
@@ -1268,26 +1268,49 @@ pub fn promote_candidates<'tcx>(
...
+        {
+            if let Operand::Constant(box Constant { literal: ty::Const { ty, .. }, .. }) = func {
+                if let ty::FnDef(def_id, _) = *ty.kind() {
+                    match destination {
+                        Some((destination_place, _)) => {
+                            if destination_place == place {
+                                if is_const_fn(ccx.tcx, def_id) {
+                                    return true;
+                                } else {
+                                    continue;
```
Comment (Aaron1011) [inline compiler/rustc_mir/src/transform/promote_consts.rs:1302]: You don't need any of these explicit `continue` expressions, since you don't need to skip anything in the loop body.

File: compiler/rustc_mir/src/transform/promote_consts.rs [hunk 3]
```diff
@@ -1268,26 +1268,49 @@ pub fn promote_candidates<'tcx>(
...
+    }
+
+    for block in body.basic_blocks() {
+        if let Some(Terminator { kind: TerminatorKind::Call { func, destination, .. }, .. }) =
+            &block.terminator
+        {
+            if let Operand::Constant(box Constant { literal: ty::Const { ty, .. }, .. }) = func {
+                if let ty::FnDef(def_id, _) = *ty.kind() {
+                    match destination {
+                        Some((destination_place, _)) => {
```
Comment (Aaron1011) [inline compiler/rustc_mir/src/transform/promote_consts.rs:1297]: This can be `if let Some((destination_place, _)) = destination`

File: compiler/rustc_trait_selection/src/traits/error_reporting/suggestions.rs (hunk 1 above)
Comment (henryboisdequin) [reply compiler/rustc_trait_selection/src/traits/error_reporting/suggestions.rs:1872]: Done

File: compiler/rustc_mir/src/transform/promote_consts.rs (hunk 2 above)
Comment (henryboisdequin) [reply compiler/rustc_mir/src/transform/promote_consts.rs]: Done

File: compiler/rustc_mir/src/transform/promote_consts.rs (hunk 3 above)
Comment (henryboisdequin) [reply compiler/rustc_mir/src/transform/promote_consts.rs]: Done

File: compiler/rustc_trait_selection/src/traits/error_reporting/suggestions.rs [hunk 4]
```diff
@@ -1868,22 +1868,21 @@ impl<'a, 'tcx> InferCtxtExt<'tcx> for InferCtxt<'a, 'tcx> {
...
                 err.note(
                     "the `Copy` trait is required because the repeated element will be copied",
                 );
-                if suggest_const_in_array_repeat_expressions {
-                    err.note(
-                        "this array initializer can be evaluated at compile-time, see issue \
-                         #49147 <https://github.com/rust-lang/rust/issues/49147> \
-                         for more information",
+                if is_const_fn {
+                    err.help("creating a new `const` item will resolve this error");
```
Comment (Aaron1011) [inline compiler/rustc_trait_selection/src/traits/error_reporting/suggestions.rs:1876]: I would say something like 'moving the function call to a new `const` item will resolve the error.'

**Comment by Aaron1011** [comment]
I helped with writing this PR, so let's get someone else to do a final review.

r? @estebank

File: compiler/rustc_trait_selection/src/traits/error_reporting/suggestions.rs (hunk 4 above)
Comment (henryboisdequin) [reply compiler/rustc_trait_selection/src/traits/error_reporting/suggestions.rs]: Done

**Comment by lzutao** [comment]
Does this PR conflict with #80404, which remove `const_in_array_repeat_expressions` feature ?

**Comment by Aaron1011** [comment]
They touch the same files, but this PR removes the specialized diagnostic fore that feature, so everything should be fine after a rebase.

File: compiler/rustc_middle/src/traits/mod.rs [hunk 5]
```diff
@@ -227,8 +227,7 @@ pub enum ObligationCauseCode<'tcx> {
     SizedYieldType,
     /// Inline asm operand type must be `Sized`.
     InlineAsmSized,
-    /// `[T, ..n]` implies that `T` must be `Copy`.
-    /// If `true`, suggest `const_in_array_repeat_expressions` feature flag.
+    /// If the function in the array repeat expression is a `const fn`
```
Comment (estebank) [inline compiler/rustc_middle/src/traits/mod.rs:230]: The docstring seems incomplete? Also, does the previous text no longer apply?

File: compiler/rustc_trait_selection/src/traits/error_reporting/suggestions.rs [hunk 6]
```diff
@@ -1868,22 +1868,23 @@ impl<'a, 'tcx> InferCtxtExt<'tcx> for InferCtxt<'a, 'tcx> {
...
                     "the `Copy` trait is required because the repeated element will be copied",
                 );
-                if suggest_const_in_array_repeat_expressions {
-                    err.note(
-                        "this array initializer can be evaluated at compile-time, see issue \
-                         #49147 <https://github.com/rust-lang/rust/issues/49147> \
-                         for more information",
+                if is_const_fn {
+                    err.help(
+                        "moving the function call to a new `const` item will resolve the error",
```
Comment (estebank) [inline compiler/rustc_trait_selection/src/traits/error_reporting/suggestions.rs:1877]:
```suggestion
                        "consider creating a new `const` item and initializing with the result of the function call to be used in the repeat position, like `const VAL: Type = const_fn();` and `let x = [VAL; 42];`",
```

Ideally we would want a structured suggestion, but I understand why that is harder than this :)

File: compiler/rustc_trait_selection/src/traits/error_reporting/suggestions.rs [hunk 7]
```diff
@@ -1868,22 +1868,23 @@ impl<'a, 'tcx> InferCtxtExt<'tcx> for InferCtxt<'a, 'tcx> {
...
-                             crate attributes to enable",
-                        );
-                    }
+                } else if self.tcx.sess.is_nightly_build() && is_const_fn {
+                    err.help(
+                        "create an inline `const` block, see PR \
+                        #2920 <https://github.com/rust-lang/rfcs/pull/2920> \
+                        for more information",
+                    );
+                } else {
```
Comment (estebank) [inline compiler/rustc_trait_selection/src/traits/error_reporting/suggestions.rs:1885]: Was the previous help incorrect?

Comment (estebank) [reply compiler/rustc_trait_selection/src/traits/error_reporting/suggestions.rs:1885]: Also, can we add a test to trigger this?

Comment (henryboisdequin) [reply compiler/rustc_trait_selection/src/traits/error_reporting/suggestions.rs:1885]: That's a good point. Both of these work on nightly, should I just not suggest an inline `const` block or suggest that both work?

File: compiler/rustc_mir/src/transform/promote_consts.rs [hunk 8]
```diff
@@ -1268,26 +1268,42 @@ pub fn promote_candidates<'tcx>(
...
-        "should_suggest_const_in_array_repeat_expressions_flag: def_id={:?} \
-            should_promote={:?} feature_flag={:?}",
-        validator.ccx.def_id(),
-        should_promote,
-        feature_flag
-    );
-    should_promote && !feature_flag
+    match place.as_local() {
+        Some(local) => {
+            if body.local_decls[local].is_user_variable() == true {
```
Comment (matsujika) [inline compiler/rustc_mir/src/transform/promote_consts.rs:1280]: I think this line can suffice without comparing.
```suggestion
            if body.local_decls[local].is_user_variable() {
```

File: compiler/rustc_mir/src/transform/promote_consts.rs [hunk 9]
```diff
@@ -1268,26 +1268,42 @@ pub fn promote_candidates<'tcx>(
...
+                // rule out cases such as: `let my_var = some_fn(); [my_var; N]`
+                return false;
+            }
+        }
+        None => {
+            return false;
+        }
+    }
```
Comment (lzutao) [inline compiler/rustc_mir/src/transform/promote_consts.rs:1288]:
```suggestion
    match place.as_local() {
        // rule out cases such as: `let my_var = some_fn(); [my_var; N]`
        Some(local) if body.local_decls[local].is_user_variable() => return false,
        None => return false,
        _ => {}
    }
```

File: compiler/rustc_mir/src/transform/promote_consts.rs [hunk 10]
```diff
@@ -1268,26 +1268,42 @@ pub fn promote_candidates<'tcx>(
...
+                                return true;
+                            }
+                        }
+                    }
+                }
+            }
+        }
+    }
+
+    return false;
```
Comment (lzutao) [inline compiler/rustc_mir/src/transform/promote_consts.rs:1308]:
```suggestion
    false
```

**Review by tesuji — COMMENTED** [review]
Some code style suggestions (non-functional changes).

**Comment by henryboisdequin** [comment]
### Update:

Addressed most comments, just need to test `const-fn-in-vec-nightly.rs`, will do that soon

**Comment by henryboisdequin** [comment]
@estebank This PR is ready for review again

File: src/test/ui/consts/const-fn-in-vec.rs [hunk 11]
```diff
@@ -0,0 +1,7 @@
+// run-fail
```
Comment (tesuji) [inline src/test/ui/consts/const-fn-in-vec.rs:1]: Is it run-fail or check-fail/build-fail ?

File: src/test/ui/consts/const-fn-in-vec-nightly.rs [hunk 12]
```diff
@@ -0,0 +1,7 @@
+// run-fail
```
Comment (tesuji) [inline src/test/ui/consts/const-fn-in-vec-nightly.rs:1]: also this ?

File: src/test/ui/consts/const-fn-in-vec.rs (hunk 11 above)
Comment (henryboisdequin) [reply src/test/ui/consts/const-fn-in-vec.rs:1]: In this case, I'm looking specifically for the error message. Which one do you think would be the best match?

Comment (tesuji) [reply src/test/ui/consts/const-fn-in-vec.rs:1]: It could be check-fail or build-fail, depends on test.
Some tests only fail in `build` mode (`cargo build`) so you could try check-fail first.

**Comment by estebank** [comment]
I noticed you have a merge commit in this branch now. I have yet to do a full review of the new state, but we _don't_ merge PRs with merges in them. Could you squash into a single commit (to make it easier to rebase) and rebase on top or a recent HEAD? There are some merge conflicts that are being introduced, which makes CI not run.

**Comment by tesuji** [comment]
@henryboisdequin Are you having troubles with git normal workflows, particularly in rebasing/squashing git history ?

**Comment by henryboisdequin** [comment]
> @henryboisdequin Are you having troubles with git normal workflows, particularly in rebasing/squashing git history ?
> You could ask here for help.

Definitely, @Aaron1011 has helped me a lot. Now I'm wondering while there are still conflicts after I "resolved them".

**Comment by tesuji** [comment]
You need to fetch from rust-lang master and rebase your branch on it.
```bash
git checkout master
git pull
git checkout <your branch>
git rebase master
```

**Comment by henryboisdequin** [comment]
@tesuji Thanks!

**Comment by estebank** [comment]
You'll need to do another rebase on top of the latest HEAD and run `./x.py test src/test/ui --stage 1 --bless` again. Apologies for the somewhat involved process. It's needed to make sure that the main branch is always buildable without issues.

**Comment by henryboisdequin** [comment]
@estebank This is ready for review again

**Comment by henryboisdequin** [comment]
@estebank Do I need to make any further changes?

**Comment by henryboisdequin** [comment]
Friendly ping @estebank :)

File: compiler/rustc_trait_selection/src/traits/error_reporting/suggestions.rs (hunk 7 above)
Comment (estebank) [reply compiler/rustc_trait_selection/src/traits/error_reporting/suggestions.rs:1900]: Ah! I see what you mean now. Normally we provide help that will work in stable on nightly as well.

File: compiler/rustc_trait_selection/src/traits/error_reporting/suggestions.rs [hunk 13]
```diff
@@ -1881,10 +1881,26 @@ impl<'a, 'tcx> InferCtxtExt<'tcx> for InferCtxt<'a, 'tcx> {
...
+            ObligationCauseCode::RepeatVec(is_const_fn) => {
                 err.note(
                     "the `Copy` trait is required because the repeated element will be copied",
                 );
+                if is_const_fn && !self.tcx.sess.is_nightly_build() {
+                    err.help(
+                        "consider creating a new `const` item and initializing with the result \
+                        of the function call to be used in the repeat position, like \
+                        `const VAL: Type = const_fn();` and `let x = [VAL; 42];`",
+                    );
```
Comment (estebank) [inline compiler/rustc_trait_selection/src/traits/error_reporting/suggestions.rs:1893]: If you don't mind, could we move this `help` to be _always_ emitted when `is_const_fn` is true? Beyond that, r=me. Just ping me when done and I'll approve.

Comment (henryboisdequin) [reply compiler/rustc_trait_selection/src/traits/error_reporting/suggestions.rs:1893]: I really need to install ninja 😅, building LLVM with make takes forever

**Comment by henryboisdequin** [comment]
@estebank Done ✅
