### PR TITLE
Use structured suggestion for restricting bounds

### LINKED ISSUE #24354: Confusing error "trait is not implemented for the type" on syntax error
This code:

```
pub trait A<T : B> { fn foo(self) -> T; }

pub struct AImpl;

impl<BImpl> A<BImpl> for AImpl {
    fn foo(self) -> BImpl { unimplemented!(); }
}

pub trait B { fn bar(self); }

pub struct BImpl;

impl B for BImpl {
    fn bar(self) { unimplemented!(); }
}
```

...give me this error:

```
   Compiling testproject v0.0.1 (file:///home/virtlink/projects/orion/testproject)
src/lib.rs:6:1: 8:2 error: the trait `B` is not implemented for the type `BImpl` [E0277]
src/lib.rs:6 impl<BImpl> A<BImpl> for AImpl {
src/lib.rs:7     fn foo(self) -> BImpl { unimplemented!(); }
src/lib.rs:8 }
error: aborting due to previous error
Could not compile `testproject`.
```

This is confusing. The trait `B` _is_ implemented for the type `BImpl`.

Instead, I have to change this:

```
impl<BImpl> A<BImpl> for AImpl
```

...into this:

```
impl A<BImpl> for AImpl
```

The error should make that clear.

```
rustc 1.0.0-nightly (c89de2c56 2015-03-28) (built 2015-03-29)
binary: rustc
commit-hash: c89de2c56baeb61e7cc434924dcc8bedd32b26b8
commit-date: 2015-03-28
build-date: 2015-03-29
host: x86_64-unknown-linux-gnu
release: 1.0.0-nightly
```

### LINKED ISSUE #37138: Constraint does not match because where clause hides blanket impl
[playground](https://is.gd/ld4Spk)

Sorry about the title gore, but I don't really know how to describe this:

``` rust
pub trait ProxiedBy<T> {}
impl<T> ProxiedBy<T> for T {}

pub trait SomeConstraint {}

struct Performer<OnT>(OnT);

impl<OnT> Performer<OnT> {
    fn perform<QueryT, ProxyT>(&self, query: QueryT)
        where QueryT: ProxiedBy<ProxyT>,
              OnT: ProxiedBy<ProxyT>,
              ProxyT: SomeConstraint {}
}

fn good<OnT, IrrelevantT>(performer: Performer<OnT>, on: OnT)
        where OnT: SomeConstraint
{
    performer.perform(on);
}

fn bad<OnT, IrrelevantT>(performer: Performer<OnT>, on: OnT)
        where OnT: SomeConstraint + ProxiedBy<IrrelevantT>
{
    performer.perform(on);
}

fn main() {}
```

Fails with (on both stable & nightliy):

``` rust
error[E0277]: the trait bound `IrrelevantT: SomeConstraint` is not satisfied
  --> y.rs:17:15
   |
17 |     performer.perform(on);
   |               ^^^^^^^ trait `IrrelevantT: SomeConstraint` not satisfied
   |
   = help: consider adding a `where IrrelevantT: SomeConstraint` bound

error: aborting due to previous error
```

The `ProxiedBy<IrrelevantT>` constraint is the only difference between `good` and `bad`. But `OnT: ProxiedBy<OnT> + HasConstraint`, therefore `ProxyT = OnT` should still be a valid substitution.

Since `IrrelevantT: !SomeConstraint` (as rustc helpfully explains) there also should be no problem.

### LINKED ISSUE #41817: The span for “trait bound not satisfied” is weird
For following code

```
pub trait Arbitrary: Sized + 'static {}

impl<'a, A> Arbitrary for ::std::borrow::Cow<'a, A> {}
```

The error is

```
error[E0277]: the trait bound `A: std::clone::Clone` is not satisfied
 --> <anon>:3:13
  |
3 | impl<'a, A> Arbitrary for ::std::borrow::Cow<'a, A> {}
  |             ^^^^^^^^^ the trait `std::clone::Clone` is not implemented for `A`
  |
  = help: consider adding a `where A: std::clone::Clone` bound
  = note: required because of the requirements on the impl of `std::borrow::ToOwned` for `A`
  = note: required because it appears within the type `std::borrow::Cow<'a, A>`
  = note: required by `Arbitrary`
```

Note the span is pointing at `Arbitrary`, despite error really being about the generic bound `A`. It should point at `A` instead.

### LINKED ISSUE #64565: Invalid bound suggestion for argument-position impl trait
The following code:

```rust
fn is_send<T: Send>(val: T) {}

fn use_impl_sync(val: impl Sync) {
    is_send(val);
}
```

gives the following error:

```
error[E0277]: `impl Sync` cannot be sent between threads safely
 --> src/lib.rs:4:5
  |
1 | fn is_send<T: Send>(val: T) {}
  | --------------------------- required by `is_send`
...
4 |     is_send(val);
  |     ^^^^^^^ `impl Sync` cannot be sent between threads safely
  |
  = help: the trait `std::marker::Send` is not implemented for `impl Sync`
  = help: consider adding a `where impl Sync: std::marker::Send` bound
```

The suggestion `where impl Sync: std::marker::Send` is invalid: it should be `impl Sync + Send`

### PR DESCRIPTION
**Pull request by estebank**
When a trait bound is not met and restricting a type parameter would
make the restriction hold, use a structured suggestion pointing at an
appropriate place (type param in param list or `where` clause).

Account for opaque parameters where instead of suggesting extending
the `where` clause, we suggest appending the new restriction:
`fn foo(impl Trait + UnmetTrait)`. Fix #64565, fix #41817, fix #24354,
cc #26026, cc #37808, cc #24159, fix #37138, fix #24354, cc #20671.

### CODE REVIEW

File: src/librustc/traits/error_reporting.rs [hunk 1]
```diff
@@ -955,6 +958,198 @@ impl<'a, 'tcx> InferCtxt<'a, 'tcx> {
...
+                hir::Node::Item(hir::Item {
+                    kind: hir::ItemKind::OpaqueTy(hir::OpaqueTy { generics, .. }), span, ..
+                }) |
+                hir::Node::TraitItem(hir::TraitItem { generics, span, .. }) |
+                hir::Node::ImplItem(hir::ImplItem { generics, span, .. })
+                if param_ty.is_some() => {
+                    let restrict_msg = "consider further restricting this bound";
+                    let param_name = param_ty.unwrap().name.as_str();
+                    for param in &generics.params {
+                        if param_name == param.name.ident().as_str() {
```
Comment (Centril) [inline src/librustc/traits/error_reporting.rs]: As I noted on Discord, I think this method is way too complicated not be be divided along the important match arms (or the places that involve early returns) (and it doesn't fit on a single page...). However, if you insist on keeping it all in one method then let's at least use a `.filter(...)` here to reduce the drift rightwards.

**Comment by estebank** [comment]
@Centril do you think there's any reasonable general suggestion we can give for the cases changed by https://github.com/rust-lang/rust/pull/65192/commits/f9742e22753e711e13c95477fcc18c62e403dec3? For the `==` case I think we should have a binop specific check somewhere else, so noone should miss the `help`. For the later case, I'm not sure what the message should/could be.

**Comment by Centril** [comment]
No idea, sorry :)

File: src/librustc/traits/error_reporting.rs [hunk 2]
```diff
@@ -960,6 +963,180 @@ impl<'a, 'tcx> InferCtxt<'a, 'tcx> {
...
+                hir::Node::Item(hir::Item {
+                    kind: hir::ItemKind::Fn(_, _, generics, _), ..
+                }) |
+                hir::Node::TraitItem(hir::TraitItem {
+                    generics,
+                    kind: hir::TraitItemKind::Method(..), ..
+                }) |
+                hir::Node::ImplItem(hir::ImplItem {
+                    generics,
+                    kind: hir::ImplItemKind::Method(..), ..
```
Comment (matthewjasper) [inline src/librustc/traits/error_reporting.rs]: Nor should this (`Self` is a type alias in `impl`s)

File: src/librustc/traits/error_reporting.rs [hunk 3]
```diff
@@ -960,6 +963,180 @@ impl<'a, 'tcx> InferCtxt<'a, 'tcx> {
...
+                            // `fn foo(x: impl Trait) {}` → `fn foo(t: impl Trait + Trait2) {}`
+                            err.span_suggestion(
+                                param.span,
+                                restrict_msg,
+                                // `impl CurrentTrait + MissingTrait`
+                                format!("{} + {}", param.name.ident(), trait_ref),
+                                Applicability::MachineApplicable,
+                            );
+                        } else {
+                            if generics.where_clause.predicates.is_empty() &&
```
Comment (matthewjasper) [inline src/librustc/traits/error_reporting.rs]: This can be an `else if`

File: src/librustc/traits/error_reporting.rs [hunk 4]
```diff
@@ -960,6 +963,180 @@ impl<'a, 'tcx> InferCtxt<'a, 'tcx> {
...
+                                err.span_suggestion(
+                                    param.span,
+                                    "consider restricting this bound",
+                                    format!("{}", trait_ref.to_predicate()),
+                                    Applicability::MachineApplicable,
+                                );
+                            } else if !generics.where_clause.predicates.is_empty() {
+                                // There is a `where` clause, so suggest expanding it:
+                                // `fn foo<T>(t: T) where T: Debug {}` →
+                                // `fn foo<T(t: T) where T: Debug, Trait {}`
```
Comment (matthewjasper) [inline src/librustc/traits/error_reporting.rs]:
```suggestion
                                // `fn foo<T>(t: T) where T: Debug, T: Trait {}`
```

**Comment by estebank** [comment]
@matthewjasper all your comments have been addressed.
