### PR TITLE
typeck: use NoExpectation to check return type of diverging fn

### LINKED ISSUE #35849: diverging function with wrapped diverging tail expression regression
Such code:

```
#[allow(dead_code)]
fn _assert_pointers_are_64bits() -> ! {
    unsafe {
        ::std::mem::transmute::<*const f64, [u8; 8]>(panic!())
    }
}

fn main() {
}
```

compiled just fine with stable(1.11.0 (9b21dcd6a 2016-08-15)),
but failed with beta(rustc 1.12.0-beta.1 (822166b84 2016-08-16)) and
nightly(rustc 1.13.0-nightly (499484f56 2016-08-18)) with such error:

```
error[E0308]: mismatched types
 --> bug.rs:4:9
  |
4 |         ::std::mem::transmute::<*const f64, [u8; 8]>(panic!())
  |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected !, found array of 8 elements
  |
  = note: expected type `!`
  = note:    found type `[u8; 8]`

error: aborting due to previous error
```

### PR DESCRIPTION
**Pull request by durka**
Fixes #35849.

Thanks @eddyb.

### CODE REVIEW

File: src/librustc_typeck/check/mod.rs [hunk 1]
```diff
@@ -708,7 +708,12 @@ fn check_fn<'a, 'gcx, 'tcx>(inherited: &'a Inherited<'a, 'gcx, 'tcx>,
 
     inherited.tables.borrow_mut().liberated_fn_sigs.insert(fn_id, fn_sig);
 
-    fcx.check_block_with_expected(body, ExpectHasType(fcx.ret_ty));
+    fcx.check_block_with_expected(body,
+                                  if fcx.ret_ty.is_never() {
+                                      NoExpectation
+                                  } else {
+                                      ExpectHasType(fcx.ret_ty)
+                                  });
```
Comment (eddyb) [inline src/librustc_typeck/check/mod.rs]: I'd put this in a variable or call a different version of `check_block` in the `TyNever` case.

File: src/test/run-pass/diverging-fn-tail-35849.rs [hunk 2]
```diff
@@ -0,0 +1,18 @@
+// Copyright 2016 The Rust Project Developers. See the COPYRIGHT
```
Comment (eddyb) [inline src/test/run-pass/diverging-fn-tail-35849.rs]: Nice test file naming scheme! cc @rust-lang/compiler Can we decide on something like this when the testcase comes from an issue but it has some kind of categorization otherwise?

**Comment by eddyb** [comment]
r=me with nit fixed.

**Comment by durka** [comment]
Nit fixed. This also needs to be `beta-nominated`.

**Comment by canndrew** [comment]
This won't allow something like `fn foo() -> ! { 3 }` to compile will it?

**Comment by eddyb** [comment]
@canndrew It's the same logic as before, I believe liveness is what prevents control-flow from exiting the function if the function is supposed to be divergent (in a more sound manner).

**Comment by durka** [comment]
@canndrew @eddyb yep we got a problem here:

    [root@li1424-173 gh35849]# build/x86_64-unknown-linux-gnu/stage1/bin/rustc - -o bad <<<'fn foo() -> ! { 42 } fn main() { foo(); }'
    warning: broken MIR (return = const 42i32): bad assignment (! = i32): Sorts(ExpectedFound { expected: !, found: i32 })
     --> <anon>:1:17
      |
    1 | fn foo() -> ! { 42 } fn main() { foo(); }
      |                 ^^
    
    [root@li1424-173 gh35849]# ./bad
    Segmentation fault (core dumped)

**Comment by eddyb** [comment]
Whoa how did that happen?! That's bad, because the code erroring before wasn't in typeck AFAIK.

@bors r-

**Comment by durka** [comment]
IRC investigation reveals that #35162 removed an important check from the liveness pass, which I will reinstate whenever LLVM finishes building. Now I'm wondering if that PR removed anything else important.

**Comment by canndrew** [comment]
Are you talking about the check in `check_ret` which was removed? If so, I think I was assuming that any block which diverges would get typed `!` (including ones ending in an expression). Would it better to fix that than to make a special case for `!` not having to be type-check correctly and then make another special case for it further down the pipeline?

**Comment by eddyb** [comment]
@canndrew Maybe that can work, but we'll *always* need a sanity check - if typeck ends up being able to handle divergence correctly, we'd just have a *proper* CFG-based check ICE instead of erroring.

**Comment by arielb1** [comment]
Maybe just add a "redundant" return type check always?

**Comment by canndrew** [comment]
I'm generally uncomfortable making special cases for `!` - part of the motivation for this RFC is that a lot of this sort of thing can be handled naturally by the type system. Plus `!` isn't the only diverging type.

**Comment by eddyb** [comment]
@canndrew The special cases need to be there until there's a RFC that says `[x: !]` is typed `!` instead of `[!; 1]` *or* that `[!; 1]` is-a-subtype-of/coerces-to `!`, and until the definition of "diverging function" changes.
We risk too much if we don't have sanity checks for the CFG of a diverging function - the MIR warning being one of them, we should probably make those warnings ICE now.

**Comment by durka** [comment]
> we should probably make those warnings ICE now

cf #35499

**Comment by canndrew** [comment]
I don't think that liveness should have special cases for `!` at all. As far as its is concerned `!` isn't a special case, it's just one of many uninhabited types. If liveness can handle `Void` it should be able to handle `!` as well. The only reason it can't is that we just added another special case for `!` which broke typechecking and allowed clear nonsense like `fn foo() -> ! { 3 }` to get through. It's one special case begetting another.

> The special cases need to be there until there's a RFC that says `[x: !]` is typed ! instead of `[!; 1]` or that `[!; 1]` is-a-subtype-of/coerces-to `!`

Why? This can get typechecked correctly:

```rust
fn foo() -> ! {
    [panic!()];
}
```

So there's some logic that can see the `!` in the middle of that expression. Can we make that logic run on the block's final expression as well and not just it's statements?

**Comment by eddyb** [comment]
@canndrew No, that doesn't get type-checked *either*. The error you get when the function is declared to return `T` and you have a semicolon and no divergence is `not all control paths return a value`, *also* from liveness.
That is, if you don't have a trailing expression, it's *not* checked at all, although this seems to only happen at the outermost level, a type error is produced if you nest blocks.

**Comment by durka** [comment]
Amended to restore the special case in `Liveness::check_ret`.

File: src/librustc/middle/liveness.rs [hunk 3]
```diff
@@ -1479,43 +1479,50 @@ impl<'a, 'tcx> Liveness<'a, 'tcx> {
...
-                        match body.stmts.last().unwrap().node {
-                            hir::StmtSemi(ref e, _) => {
-                                self.ir.tcx.expr_ty(&e) == fn_ret
+        if fn_ret.is_never() {
+            if self.live_on_entry(entry_ln, self.s.clean_exit_var).is_some() {
+                span_err!(self.ir.tcx.sess, sp, E0270,
+                        "computation may converge in a function marked as diverging");
+            }
+        } else {
+            if self.live_on_entry(entry_ln, self.s.no_ret_var).is_some() {
```
Comment (eddyb) [inline src/librustc/middle/liveness.rs]: This could be an `else-if` to make the diff simpler.

File: src/test/compile-fail/diverging-fn-tail-35849.rs [hunk 4]
```diff
@@ -0,0 +1,22 @@
...
+// http://www.apache.org/licenses/LICENSE-2.0> or the MIT license
+// <LICENSE-MIT or http://opensource.org/licenses/MIT>, at your
+// option. This file may not be copied, modified, or distributed
+// except according to those terms.
+
+fn assert_sizeof() -> ! {
+    unsafe {
+        ::std::mem::transmute::<f64, [u8; 8]>(panic!())
+    }
+}
```
Comment (eddyb) [inline src/test/compile-fail/diverging-fn-tail-35849.rs]: I think this should be in a different test, to make sure compiler pass ordering doesn't hide bugs.

**Comment by durka** [comment]
Nits knitted.

File: src/librustc/middle/liveness.rs [hunk 5]
```diff
@@ -1479,7 +1479,10 @@ impl<'a, 'tcx> Liveness<'a, 'tcx> {
                 self.ir.tcx.region_maps.call_site_extent(id, body.id),
                 &self.fn_ret(id));
 
-        if self.live_on_entry(entry_ln, self.s.no_ret_var).is_some() {
+        if fn_ret.is_never() && self.live_on_entry(entry_ln, self.s.clean_exit_var).is_some() {
```
Comment (eddyb) [inline src/librustc/middle/liveness.rs]: These should not be combined, i.e. the `else` below should be to `fn_ret.is_never()` alone, to match the old semantics.

**Comment by durka** [comment]
Knit nitted.

**Comment by durka** [comment]
Fixed the travis failure and added some FIXME comments.

We unfortunately needed to ignore a test added for `#![feature(never_type)]` because it can't be done with the current structure of the liveness code. A fix may be possible, but the consensus was that we shouldn't try to get it into this PR, to keep it backportable. I'll file separate bugs.

**Comment by alexcrichton** [comment]
@bors: retry force clean

* restarted buildbot
