### PR TITLE
reduce threads spawned by ui-tests

### LINKED ISSUE #81946: Safe code (ui/issues/issue-69225-SCEVAddExpr-wrap-flag.rs) miscompiles under llvm9 + codegen-units=1
```
---- [ui] ui/issues/issue-69225-SCEVAddExpr-wrap-flag.rs stdout ----

error: error pattern ' index out of bounds: the len is 0 but the index is 16777216' not found!
status: signal: 11
command: "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/issues/issue-69225-SCEVAddExpr-wrap-flag/a"
```

Current reproducer: #81945

Original issue: #69225. According to https://github.com/rust-lang/rust/issues/69225#issuecomment-590161333  the testcase originally did work fine for any number of codegen units. Seems like a regression.

### PR DESCRIPTION
**Pull request by the8472**
The test harness already spawns enough tests to keep all cores busy.
Individual tests should keep their own threading to a minimum to avoid context switch overhead.

When running ui tests with lld enabled this shaves about 10% off that testsuite on my machine.

Resolves #81946

### CODE REVIEW

File: src/tools/compiletest/src/runtest.rs [hunk 1]
```diff
@@ -2042,10 +2050,24 @@ impl<'test> TestCx<'test> {
...
+                        .unwrap_or(false);
                 }
             }
         }
 
+        // Use a single thread for efficiency and a deterministic error message order
+        rustc.arg("-Zthreads=1");
+
+        if lld {
+            rustc.arg("-Clink-arg=-Wl,--threads=1");
```
Comment (the8472) [inline src/tools/compiletest/src/runtest.rs:2068]: Not sure if this will work on all platforms. I onl the gcc + gold and gcc + lld combinations.

**Comment by the8472** [comment]
That failure is concerning.

The original issue #69225 reported an out of bounds access that *doesn't* happen when codegen-units < 4. That issue was fixed and the [reproducer at that time](https://github.com/rust-lang/rust/issues/69225#issuecomment-590161333) didn't depend on CGUs either. And yet here it is. 😕

File: src/test/ui/issues/issue-69225-SCEVAddExpr-wrap-flag.rs [hunk 2]
```diff
@@ -1,5 +1,5 @@
 // run-fail
-// compile-flags: -C opt-level=3
+// compile-flags: -C opt-level=3 -Ccodegen-units=2
```
Comment (the8472) [inline src/test/ui/issues/issue-69225-SCEVAddExpr-wrap-flag.rs:2]: Workaround for #81946

File: src/test/ui/asm/sym.rs [hunk 3]
```diff
@@ -1,3 +1,4 @@
+// compile-flags: -C codegen-units=2
```
Comment (the8472) [inline src/test/ui/asm/sym.rs:1]: Going from multiple to 1 CGU changed the output a bit. Adding that flag avoids that.

**Comment by Mark-Simulacrum** [comment]
I am worried about maintaining the complexity cost here, but the 10% does sound appealing. Could you see if we get similar effects from configuring a make jobserver (via the jobserver crate) with just 1 token?

**Comment by the8472** [comment]
As far as I can tell from documentation `lld.ld` does not support jobservers, only the `--threads` argument. Running `./x.py build compiler/rustc -j1` also results in that multi-threaded peak from lld. For compiletest that's significant because it's linking many small testcases.

**Comment by Mark-Simulacrum** [comment]
Huh, that's annoying. I'll think some more about the tradeoff here, I guess.

File: src/tools/compiletest/src/runtest.rs [hunk 4]
```diff
@@ -1911,9 +1911,6 @@ impl<'test> TestCx<'test> {
         // FIXME Why is -L here?
         rustc.arg(input_file); //.arg("-L").arg(&self.config.build_base);
 
-        // Use a single thread for efficiency and a deterministic error message order
-        rustc.arg("-Zthreads=1");
```
Comment (the8472) [inline src/tools/compiletest/src/runtest.rs:1915]: ... was limited here...

File: src/tools/compiletest/src/runtest.rs [hunk 5]
```diff
@@ -2042,10 +2050,24 @@ impl<'test> TestCx<'test> {
...
+                        .target_rustcflags
+                        .as_ref()
+                        .map(|f| f.contains("-fuse-ld=lld"))
+                        .unwrap_or(false);
                 }
             }
         }
 
+        // Use a single thread for efficiency and a deterministic error message order
+        rustc.arg("-Zthreads=1");
```
Comment (the8472) [inline src/tools/compiletest/src/runtest.rs:2065]: ... and still is limited here.

Together with lld not obeying jobservers I don't see how there would be any benefit to using them in this narrow case. I can see how using them could make bootstrap better at a higher level though.

**Review by the8472 — COMMENTED** [review]
Also note that in rustc the jobserver only restricts the number of concurent threads, it doesn't have an impact on codegen unit count. But the number of threads already...

**Comment by Mark-Simulacrum** [comment]
Hm, I'm not sure who might be able to check the linker flags will generally do the right thing. I'm not myself really that familiar with our linker story today. cc @nagisa perhaps?

**Comment by Mark-Simulacrum** [comment]
It also looks like -no-threads might be preferable to the threads=1 option? That communicates intent a bit more clearly, maybe they have different handling internally?

**Comment by Mark-Simulacrum** [comment]
Otherwise this seems good to me - I think I'd like some more eyes on it for the linker stuff, so I'll nominate for a T-compiler meeting, but I think we could land after that.

File: src/tools/compiletest/src/runtest.rs (hunk 1 above)
Comment (nagisa) [reply src/tools/compiletest/src/runtest.rs:2068]: `-Wl` won't work for any `-Clinker-flavor` other than `gcc`, and maybe a couple others. While this particular piece of code is not incorrect, because `-fuse-ld` is also a flag specific to `gcc`-like linkers, but its also true that this change is not inclusively supporting all the platforms where `linker-flavor` is not `gcc` by default.

File: src/test/ui/issues/issue-69225-SCEVAddExpr-wrap-flag.rs (hunk 2 above)
Comment (nagisa) [reply src/test/ui/issues/issue-69225-SCEVAddExpr-wrap-flag.rs:2]: I would prefer `// no-system-llvm` (can it be combined with min-llvm-version to make sure that if system llvm is >=11, we run this test anyway?) as the workaround here.

Comment (the8472) [reply src/test/ui/issues/issue-69225-SCEVAddExpr-wrap-flag.rs:2]: Those exclusions combine as OR, not AND. So we can set `min-llvm-version >= 11`, of course that means we lose some coverage, but it already was broken on vanilla 9 anyway.

**Comment by nagisa** [comment]
My only major concern here is that there may have been tests written for ICEs or soundness issues out there that relied on absence of `-Ccodegen-units` flag being equivalent to "many of them" rather than "1 CU". Of course the tests are pretty poor if they made assumptions like these, but :shrug:.

File: src/tools/compiletest/src/runtest.rs (hunk 1 above)
Comment (the8472) [reply src/tools/compiletest/src/runtest.rs:2068]: >  While this particular piece of code is not incorrect (because -fuse-ld is also a flag specific to gcc-like linkers)

Bootstrap configuration is not available in compiletest except for what gets mangled into `--target-rustcflags`. Should I add an explicit linker-type argument instead?

> -Wl won't work for any -Clinker-flavor other than gcc

Does rustc have any abstraction that handles linker args across compilers? I also tried `-Zpre-link-arg` but that also added it as a `cc` arg without compiler-specific mangling.


Or I could leave things as they are and only the gcc+ldd combo gets this particular performance optimization.

Comment (nagisa) [reply src/tools/compiletest/src/runtest.rs:2068]: I think its fine to leave as is.

There's no linker-flavor specific handling – in current rust setup a `gcc`-compatible tool itsself is itself considered a linker (without a consideration what it might invoke) and so the "linker arguments" are equivalent to gcc arguments in that mode.

**Comment by the8472** [comment]
> It also looks like -no-threads might be preferable to the threads=1 option?

That only seems to be available on lld 10. 11 only has the threads argument.

File: src/test/ui/asm/sym.rs (hunk 3 above)
Comment (tmiasko) [reply src/test/ui/asm/sym.rs:1]: Is this comment & change intended for this test, given that this is a run-pass without any output? The test probably should join the spawned thread to make assertions effective.

**Comment by the8472** [comment]
Can't reproduce the issue locally even with `./src/ci/docker/run.sh x86_64-gnu-llvm-9` and it didn't occur in 0e4d4d04636bce5b242accee74b0c95039957afd  either. Trying again...

File: src/test/ui/asm/sym.rs (hunk 3 above)
Comment (the8472) [reply src/test/ui/asm/sym.rs:1]: It's a build failure with 1CGU:

```
running 1 test
F
failures:

---- [ui] ui/asm/sym.rs stdout ----

error: test compilation failed although it shouldn't!
status: exit code: 1
command: "/home/the8472/workspace/rust/build/x86_64-unknown-linux-gnu/stage1/bin/rustc" "/home/the8472/workspace/rust/src/test/ui/asm/sym.rs" "--target=x86_64-unknown-linux-gnu" "--error-format" "json" "-Ccodegen-units=1" "-Zui-testing" "-Zdeduplicate-diagnostics=no" "-Zemit-future-incompat-report" "-C" "prefer-dynamic" "-o" "/home/the8472/workspace/rust/build/x86_64-unknown-linux-gnu/test/ui/asm/sym/a" "-Crpath" "-O" "-Cdebuginfo=0" "-Zunstable-options" "-Lnative=/home/the8472/workspace/rust/build/x86_64-unknown-linux-gnu/native/rust-test-helpers" "-Clink-args=-fuse-ld=lld" "-Zthreads=1" "-Clink-arg=-Wl,--threads=1" "-L" "/home/the8472/workspace/rust/build/x86_64-unknown-linux-gnu/test/ui/asm/sym/auxiliary"
stdout:
------------------------------------------

------------------------------------------
stderr:
------------------------------------------
error: linking with `cc` failed: exit code: 1
   |
   = note: "cc" "-Wl,--as-needed" "-Wl,-z,noexecstack" "-m64" "-Wl,--eh-frame-hdr" "-L" "/home/the8472/workspace/rust/build/x86_64-unknown-linux-gnu/stage1/lib/rustlib/x86_64-unknown-linux-gnu/lib" "/home/the8472/workspace/rust/build/x86_64-unknown-linux-gnu/test/ui/asm/sym/a.sym.7rcbfp3g-cgu.0.rcgu.o" "-o" "/home/the8472/workspace/rust/build/x86_64-unknown-linux-gnu/test/ui/asm/sym/a" "-Wl,--gc-sections" "-pie" "-Wl,-zrelro" "-Wl,-znow" "-Wl,-O1" "-nodefaultlibs" "-L" "/home/the8472/workspace/rust/build/x86_64-unknown-linux-gnu/native/rust-test-helpers" "-L" "/home/the8472/workspace/rust/build/x86_64-unknown-linux-gnu/test/ui/asm/sym/auxiliary" "-L" "/home/the8472/workspace/rust/build/x86_64-unknown-linux-gnu/stage1/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-Wl,--start-group" "-L" "/home/the8472/workspace/rust/build/x86_64-unknown-linux-gnu/stage1/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-lstd-4bcd3860df8b1104" "-Wl,--end-group" "-Wl,-Bstatic" "/home/the8472/workspace/rust/build/x86_64-unknown-linux-gnu/stage1/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcompiler_builtins-ce524fd723f2909f.rlib" "-Wl,-Bdynamic" "-lgcc_s" "-lutil" "-lrt" "-lpthread" "-lm" "-ldl" "-lc" "-Wl,-rpath,$ORIGIN/../../../../stage1/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-Wl,-rpath,/home/the8472/workspace/rust/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-Wl,--enable-new-dtags" "-fuse-ld=lld" "-Wl,--threads=1"
   = note: ld.lld: error: can't create dynamic relocation R_X86_64_TPOFF32 against local symbol in readonly segment; recompile object files with -fPIC or pass '-Wl,-z,notext' to allow text relocations in the output
           >>> defined in /home/the8472/workspace/rust/build/x86_64-unknown-linux-gnu/test/ui/asm/sym/a.sym.7rcbfp3g-cgu.0.rcgu.o
           >>> referenced by sym.7rcbfp3g-cgu.0
           >>>               /home/the8472/workspace/rust/build/x86_64-unknown-linux-gnu/test/ui/asm/sym/a.sym.7rcbfp3g-cgu.0.rcgu.o:(std::sys_common::backtrace::__rust_begin_short_backtrace::h780c366c76851b98)
           
           ld.lld: error: can't create dynamic relocation R_X86_64_TPOFF32 against local symbol in readonly segment; recompile object files with -fPIC or pass '-Wl,-z,notext' to allow text relocations in the output
           >>> defined in /home/the8472/workspace/rust/build/x86_64-unknown-linux-gnu/test/ui/asm/sym/a.sym.7rcbfp3g-cgu.0.rcgu.o
           >>> referenced by sym.7rcbfp3g-cgu.0
           >>>               /home/the8472/workspace/rust/build/x86_64-unknown-linux-gnu/test/ui/asm/sym/a.sym.7rcbfp3g-cgu.0.rcgu.o:(sym::main::h88865da8b3687b30)
           collect2: error: ld returned 1 exit status
           

error: aborting due to previous error
```

**Comment by the8472** [comment]
No idea why this is happening 😕. I guess this uncovered another buggy test?

It still passes locally and it passed in CI on the previous commit with the latest change only changing an unrelated test.

File: src/test/ui/issues/issue-69225-SCEVAddExpr-wrap-flag.rs (hunk 2 above)
Comment (the8472) [reply src/test/ui/issues/issue-69225-SCEVAddExpr-wrap-flag.rs]: Added the min version.

File: src/test/ui/linkage-attr/linkage-detect-extern-generated-name-collision.rs [hunk 6]
```diff
@@ -4,6 +4,7 @@
 
 // build-fail
 // aux-build:def_colliding_external.rs
+// compile-flags: -Ccodegen-units=2
```
Comment (the8472) [inline src/test/ui/linkage-attr/linkage-detect-extern-generated-name-collision.rs:7]: passed in https://github.com/rust-lang/rust/pull/81942/commits/0e4d4d04636bce5b242accee74b0c95039957afd
segfaulted in rustc 3x with https://github.com/rust-lang/rust/pull/81942/commits/9159029ee97846e8c71fcc7ef339f072f6d96119
passes again with https://github.com/rust-lang/rust/pull/81942/commits/4b3adcf38f28f60e10d83464a59d869ab13460b3

This test seems to be very sensitive to unrelated factors. That might indicate some hidden bug but possibly limited to llvm9. Should I file a bug for that?

**Comment by bjorn3** [comment]
Would it be possible to use the jobserver integration in rustc to limit the amount threads instead of of using `-Ccodegen-units`?

**Comment by the8472** [comment]
> Would it be possible to use the jobserver integration in rustc to limit the amount threads instead of of using `-Ccodegen-units`?

No, as explained in a [previous comment](https://github.com/rust-lang/rust/pull/81942#discussion_r575776692) rustc thread count was already restricted. Codegen units still result in tasks and each task is spawned as a new thread and probably has other overhead too. So restricting codegen units _and_ threads leads to additional speedup as long as cores are kept busy by multiple single-threaded compilers running as is the case in ui tests.

**Comment by bjorn3** [comment]
`-Zthreads=1` only limits the amount of spawned threads for the thread pool used for parallel rustc and doesn't have any effect for regular rustc. The jobserver integration also affects the amount of threads used for optimizing codegen units.

**Comment by the8472** [comment]
That's surprising. But if that's true then there may be some benefit to using jobservers, especially for tests that require multiple CGUs.

That said, it would not obsolete the changes in this PR, e.g. LLD does not obey jobservers. And CGUs=1 might still reduce overhead, but that would require new measurements to tell.

**Comment by the8472** [comment]
wall time of `x.py test src/test/ui --stage 1`

| commit | time | 
|-----|----|
| base  | 53.34s |
| base  + jobserver | 58.07s |
| this PR | 46.02s |
| this PR + jobserver |  51.38s |

**Comment by pnkfelix** [comment]
Discussed at T-compiler triage meeting.

There is some concern about introducing even more system-specific behavior, and also concern about whether we are making our tests more flaky (vs just exposing existing flakiness).

But I think I want to try to give merging this a shot. Or rather, I want people to register concrete concerns on the PR thread itself.

So

@rfcbot fcp merge

File: src/tools/compiletest/src/runtest.rs [hunk 7]
```diff
@@ -2029,11 +2029,19 @@ impl<'test> TestCx<'test> {
...
         if self.props.force_host {
             self.maybe_add_external_args(
                 &mut rustc,
                 self.split_maybe_args(&self.config.host_rustcflags),
             );
+            lld = self
+                .config
+                .host_rustcflags
+                .as_ref()
+                .map(|f| f.contains("-fuse-ld=lld"))
```
Comment (petrochenkov) [inline src/tools/compiletest/src/runtest.rs:2043]:
```suggestion
                .map_or(false, |f| f.contains("-fuse-ld=lld"))
```

File: src/tools/compiletest/src/runtest.rs [hunk 8]
```diff
@@ -2042,10 +2050,24 @@ impl<'test> TestCx<'test> {
             if !is_rustdoc {
                 if let Some(ref linker) = self.config.linker {
                     rustc.arg(format!("-Clinker={}", linker));
+                } else {
+                    lld = self
+                        .config
+                        .target_rustcflags
+                        .as_ref()
+                        .map(|f| f.contains("-fuse-ld=lld"))
```
Comment (petrochenkov) [inline src/tools/compiletest/src/runtest.rs:2058]:
```suggestion
                        .map_or(false, |f| f.contains("-fuse-ld=lld"))
```

File: src/tools/compiletest/src/runtest.rs [hunk 9]
```diff
@@ -2029,11 +2029,19 @@ impl<'test> TestCx<'test> {
             rustc.args(&["-A", "unused"]);
         }
 
+        let mut lld = false;
```
Comment (petrochenkov) [inline src/tools/compiletest/src/runtest.rs:2032]:
```suggestion
        let mut fuse_ld_lld= false;
```
You are specifically detecting a gcc-like linker using `-fuse-ld=lld` here, and also rely on it when passing `-Wl,--threads=1` which also needs a gcc-like linker.
LLD in general can be used in other ways, MSVC targets, for example, use `lld` directly as `-C linker`.

**Comment by petrochenkov** [comment]
Any reasons to put this logic to compiletest specifically where we need to recover the knowledge about using LLD from command line options?
`-Wl,--threads=1` could instead be added in `src\bootstrap\test.rs` where we directly know whether we are using LLD or not.

File: src/tools/compiletest/src/runtest.rs (hunk 8 above)
Comment (the8472) [reply src/tools/compiletest/src/runtest.rs:2058]: I'll change it but the GH suggestion is not directly applicable since you only highlighted 1 line to change (you can drag to mark more than one line).

Comment (petrochenkov) [reply src/tools/compiletest/src/runtest.rs:2058]: It may be better to remove this code entirely as suggested in https://github.com/rust-lang/rust/pull/81942#issuecomment-791943800, so this comment may be outdated.

**Comment by the8472** [comment]
> Any reasons to put this logic to compiletest specifically where we need to recover the knowledge about using LLD from command line options?

None other than tunnel vision. I'll give it a try.

File: src/tools/compiletest/src/runtest.rs (hunk 4 above)
Comment (petrochenkov) [inline src/tools/compiletest/src/runtest.rs:1915]: Nit: could you revert this unnecessary code move?

**Comment by petrochenkov** [comment]
Nice.
Ticked the box.

**Comment by apiraino** [comment]
I think this is reviewed and approved (minus some pending fixes).

@rustbot label -S-waiting-for-review

File: src/tools/compiletest/src/runtest.rs [hunk 10]
```diff
@@ -1951,6 +1951,9 @@ impl<'test> TestCx<'test> {
                 if !self.props.compile_flags.iter().any(|s| s.starts_with("--error-format")) {
                     rustc.args(&["--error-format", "json"]);
                 }
+                if !self.props.compile_flags.iter().any(|s| s.contains("codegen-units")) {
```
Comment (petrochenkov) [inline src/tools/compiletest/src/runtest.rs:1954]: This condition should be unnecessary because options passed later override options passed earlier, and options from `// compile-flags` are passed later to give individual tests chance to override defaults.

For example, `-Zdeduplicate-diagnostics=no` below is passed unconditionally, but some tests override it with `// compile-flags: -Zdeduplicate-diagnostics=yes`.

**Comment by nikomatsakis** [comment]
@rfcbot reviewed

**Comment by Mark-Simulacrum** [comment]
@bors r+ 

I don't think we need to wait for FCP to actually complete here.

**Comment by Dylan-DPC** [comment]
(potential) failure of [rollup](https://github.com/rust-lang/rust/pull/83562#issuecomment-808731022)

@bors r-

**Comment by the8472** [comment]
Modified the Dockerfile to only run UI tests and then executed `./src/ci/docker/run.sh x86_64-gnu-llvm-10` locally and can't reproduce the issue.

**Comment by the8472** [comment]
Rebased. The CI job which failed in the rollup passes here.

@rustbot +S-waiting-on-review -S-waiting-on-author

**Comment by the8472** [comment]
> Step 1/11 : FROM ubuntu:16.04
Head https://registry-1.docker.io/v2/library/ubuntu/manifests/16.04: Get https://auth.docker.io/token?account=githubactions&scope=repository%3Alibrary%2Fubuntu%3Apull&service=registry.docker.io: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
The command has failed after 5 attempts.

Network issue. Retry please.

**Comment by Mark-Simulacrum** [comment]
I'm wondering now if these LLVM asserts crop up in the wild in practice, but we don't notice as we ship llvm without asserts. cc @rust-lang/wg-llvm -- do you think we should be worried about these? Is there a chance our IR is malformed with some codegen-unit settings or something?

```
rustc: /checkout/src/llvm-project/llvm/include/llvm/Support/Casting.h:269: typename llvm::cast_retty<X, Y*>::ret_type llvm::cast(Y*) [with X = llvm::GlobalValue; Y = llvm::Value; typename llvm::cast_retty<X, Y*>::ret_type = llvm::GlobalValue*]: Assertion `isa<X>(Val) && "cast<Ty>() argument of incompatible type!"' failed.
```

**Comment by the8472** [comment]
Does a local config.toml affect the docker builds? differences in llvm configuration would at least explain why I'm not seeing it when running those locally.

The last rollup failed in the same test, albeit without showing that llvm assertion.

**Comment by Mark-Simulacrum** [comment]
I'm not sure, but I would suspect config.toml shouldn't affect it (we build in a different dir).

adding llvm-assertions = true to the config.toml in the docker builder (e.g., by adding --enable-llvm-assertions here https://github.com/Mark-Simulacrum/rust/blob/e423058751a2b098d3e469a8e6df1b7a8bbd67b6/src/ci/docker/host-x86_64/x86_64-gnu/Dockerfile#L27) may help reproduce locally. I'd expect the docker containers run locally to match CI environment including such args, though; not sure what's up. May need a rebase I suppose? But seems unlikely.

**Comment by the8472** [comment]
With `assertions = true` I can reproduce these failures reliably with low CGU counts (1-2) and mostly get them to pass with 16 CGUs

```
    [ui] ui/linkage-attr/linkage-detect-extern-generated-name-collision.rs
    [ui] ui/linkage-attr/linkage-detect-local-generated-name-collision.rs
```

**Comment by the8472** [comment]
> I'm wondering now if these LLVM asserts crop up in the wild in practice, but we don't notice as we ship llvm without asserts. cc @rust-lang/wg-llvm -- do you think we should be worried about these? Is there a chance our IR is malformed with some codegen-unit settings or something?
> 
> ```
> rustc: /checkout/src/llvm-project/llvm/include/llvm/Support/Casting.h:269: typename llvm::cast_retty<X, Y*>::ret_type llvm::cast(Y*) [with X = llvm::GlobalValue; Y = llvm::Value; typename llvm::cast_retty<X, Y*>::ret_type = llvm::GlobalValue*]: Assertion `isa<X>(Val) && "cast<Ty>() argument of incompatible type!"' failed.
> ```

I have bumped the CGU count in the tests to get them to pass and filed #83838 for those failures. You can close that if it's already tracked somewhere else or a non-issue.

**Comment by the8472** [comment]
I can reproduce it locally.

```
rustc: /checkout/src/llvm-project/llvm/lib/CodeGen/RegAllocFast.cpp:883: void {anonymous}::RegAllocFast::defineVirtReg(llvm::MachineInstr&, unsigned int, llvm::Register, bool): Assertion `PhysReg != 0 && "Register not assigned"' failed.
```

https://github.com/rust-lang/rust/pull/81825#issuecomment-808791588 ran into this issue too, in a different test but one that was also related to unwinding and lto.

Bumping it to 2CGUs helps here. Quite an elusive bug, this test has 12 revisions, only one of them fails with 1 CGU.

**Comment by the8472** [comment]
Bumped CGU count for the affected test, filed #83854

**Comment by Mark-Simulacrum** [comment]
@bors r+

I think if we see several more of these I'm inclined to reconsider the approach personally, and try to investigate the bugs causing these asserts to fire, trying to squash them before proceeding with landing this.

**Comment by the8472** [comment]
So far it's 5 tests out of 11716.

* 1 only occurs on old, unpatched LLVM versions and can soon be forgotten
* 1 probably is benign since it only changes test error output, affecting the diff
* 2 likely share the same root cause
* 1 additionally is conditional on i586

So 3 of 11716 tests that might have serious issues previously masked by CGU settings.

That's not too terrible. For the future it could make sense to have one or two of the homu jobs run with a different CGU default than the others.

**Comment by Mark-Simulacrum** [comment]
Sure, I'm not saying that there's a lot of tests, just if we get to ~15-20 having this kind of problem I'd rather start trying to squash the problems before trying to land the rest of the tests. I agree that these failures definitely point at our test suite lacking some codegen-unit based testing, which would be good to add.

**Comment by petrochenkov** [comment]
>1 probably is benign since it only changes test error output, affecting the diff

FWIW, in cases like this it's probably better to update the output.
Looking at a random unexplained `-Ccodegen-units` option in a test immediately brings confusion and questions "why is it here? is it necessary? can it be removed?", and "keeping some status quo output" is probably not a good answer to such questions.

**Comment by the8472** [comment]
Ok, I can do that in a followup PR so it can get proper review.

**Comment by the8472** [comment]
There now are 4 tests triggering register allocator asserts on i586/i686. Two in this PR and two in https://github.com/rust-lang/rust/pull/81825#issuecomment-808791291

**Comment by the8472** [comment]
`i686-gnu-nopt` UI tests pass locally with my latest changes.

**Comment by Mark-Simulacrum** [comment]
Looks like the commit message is a bit mangled:

# Conflicts:
#	src/test/ui/asm/sym.rs

**Comment by the8472** [comment]
Not sure what the correct way to solve this one is. Some stackoverflow answers suggest that passing `mcmodel=medium` or disabling PIE might help, but since that test requires hwsan which only works on aarch64 I can't test it.

Of course I can simply bump the codegen units again instead.

**Comment by the8472** [comment]
Couldn't reproduce it on godbolt either since it supports crosscompilation but not linking for other targets.

Filed #83989 and bumped CGUs.

**Comment by petrochenkov** [comment]
@the8472 
>Ok, I can do that in a followup PR so it can get proper review.

Could you at least leave FIXMEs (preferably referencing the opened issues) in tests to which this PR adds `-Ccodegen-units`?

**Comment by the8472** [comment]
> @the8472
> 
> > Ok, I can do that in a followup PR so it can get proper review.
> 
> Could you at least leave FIXMEs (preferably referencing the opened issues) in tests to which this PR adds `-Ccodegen-units`?

Will do. I have looked at the test which I thought failed with a stderr diff again and it turns out it actually is another linker error. I'll file an issue for that too.

**Comment by the8472** [comment]
Added FIXMEs, bumped CGUs further for the latest failing test.
