### PR TITLE
Set target-abi module flag for RISC-V targets

### LINKED ISSUE #121924: Cross-language LTO is broken for riscv64 lp64d
Cross-language LTO is broken for riscv64 lp64d (e.g. riscv64gc-unknown-linux-gnu).

I tried this code:

A minimal reproduction is available at https://github.com/kxxt/riscv-rust-cross-language-lto-reproducer

```bash
make
```

I expected to see this happen: code compiles and links successfully

Instead, this happened: `ld.lld: error: lto.tmp: cannot link object files with different floating-point ABI from /usr/riscv64-linux-gnu/usr/lib/Scrt1.o`

This is because the lack of `target-abi` in `llvm.module.flags` makes lld think that the rust generated bitcode is a soft float object file, contrary to the fact that `riscv64gc-unknown-linux-gnu` is `lp64d`.

```
$ llvm-dis main.o
$ grep target-abi main.o.ll
!1 = !{i32 1, !"target-abi", !"lp64d"}
$ ar x libreproducer.rlib
$ llvm-dis reproducer.reproducer.*.rcgu.o
$ grep target-abi reproducer.reproducer.*.rcgu.o.ll
(no output)
```

Relevant discussions: 
- [Encode target-abi into LLVM bitcode for LTO. - Project Infrastructure / LLVM Dev List Archives - LLVM Discussion Forums](https://discourse.llvm.org/t/encode-target-abi-into-llvm-bitcode-for-lto/54116)
- [Per-Target LLVM Module Flags - compiler - Rust Internals](https://internals.rust-lang.org/t/per-target-llvm-module-flags/12023)

I think rustc should encode the target-abi into LLVM bitcode as clang already does.

The real world use case for this feature is cross-compiling electron/chromium for riscv64. I attempted to fix this problem by myself but due to my unfamiliarity with llvm and the rustc code base, I only came up with this workaround: [embed riscv64 target abi in bc when plugin-lto is used · kxxt/rust@a599284 · GitHub](https://github.com/kxxt/rust/commit/a599284dbac82d272aac53a7ace524484b4bb4dc) . A rust toolchain including that commit can be found at https://github.com/riscv-forks/electron/releases/tag/rustc-cd6d8f2a04528f827ad3d399581c0f3502b15a72-1-llvmorg-18-init-17730-gf670112a . I believe someone from rust team could fix this problem in a better way than my patch.

### Meta

`rustc --version --verbose`:
```
rustc 1.78.0-nightly (878c8a2a6 2024-02-29)
binary: rustc
commit-hash: 878c8a2a62d49ca5c454547ad67290a1df746cb5
commit-date: 2024-02-29
host: x86_64-unknown-linux-gnu
release: 1.78.0-nightly
LLVM version: 18.1.0
```

### PR DESCRIPTION
**Pull request by kxxt**
Fixes cross-language LTO on RISC-V targets (Fixes #121924)

### CODE REVIEW

**Comment by jieyouxu** [comment]
Relevant LLVM patch: https://github.com/llvm/llvm-project/commit/227496dc09cf46df233aad041d6dc6113822e4bb

Some remarks (I'm not very familiar with LLVM + RISC-V + LTO):
- This will definitetly need a regression test to make sure we don't accidentally break things in the future, I believe your test case could be written as a ran-make test for the specific riscv target.
- Can you leave a FIXME for emitting RISC-V-specific target-abi metadata linking to the relevant LLVM issue? AFAICT this is still considered a workaround?
- Should we unconditionally emit target-abi metadata?

**Comment by jieyouxu** [comment]
Actually I just did a double take: are you sure this isn't a lld problem? What happens if your reproducer makefile specifies `-Wl,-plugin-opt=-target-abi=lp64d`?

**Comment by kxxt** [comment]
Hi @jieyouxu, Thanks for your quick review.

> Would a current workaround for the reproducer makefile be to specify `-Wl,-plugin-opt=-target-abi=lp64d`? For rustc it's something like `-Clink-args="-target-abi=lp64d"`

Yes, [that will work](https://github.com/kxxt/riscv-rust-cross-language-lto-reproducer/commit/ad619e4796bc04f6aaa1a0ff97dfe644585c5a62), but I still think this should be fixed in rustc.

> Should we unconditionally emit target-abi metadata?

I am not familiar with rustc or llvm. But from the code it does look like clang is emitting this metadata unconditionally: https://github.com/llvm/llvm-project/blob/llvmorg-19-init/clang/lib/CodeGen/CodeGenModule.cpp#L1057-L1062

> Can you leave a FIXME for emitting RISC-V-specific target-abi metadata linking to the relevant LLVM issue? AFAICT this is still considered a workaround?

I will do it.

> This will definitetly need a regression test to make sure we don't accidentally break things in the future, I believe your test case could be written as a run-make test for the specific riscv target to make sure it works across LTO, and maybe a codegen(?) test checking that we emit the target-abi metadata for the riscv target.

I will try to add tests.

**Comment by jieyouxu** [comment]
I personally think that emitting target-abi does make sense. But I'm far from familiar with the LLVM side of things to judge if this approach is what makes the most sense given the context, so I'll leave this to reviewers more well-versed in the LLVM side of things to give the final reviews.

**Comment by kxxt** [comment]
I have added a run-make test and a codegen test and fixed a bug that empty target-abi got emitted for targets that have llvm_abiname defined as an empty string.

**Review by jieyouxu — CHANGES_REQUESTED** [review]
Thanks for adding the tests. I left some reviews for the tests themselves. For the LLVM wrapper and LLVM codegen changes, another reviewer will look at them.

File: tests/run-make/cross-lang-lto-riscv-abi/Makefile [hunk 1]
```diff
@@ -0,0 +1,24 @@
+# needs-matching-clang
```
[the remark this answers is not in the document]
Comment (kxxt) [reply tests/run-make/cross-lang-lto-riscv-abi/Makefile:1]: > Please try to [write this test in rmake.rs](https://github.com/rust-lang/rust/issues/121876), we're trying to get rid of Makefiles in our run-make test suite.

Thanks! I don't know that beforehand.

File: tests/codegen/riscv-target-abi.rs [hunk 2]
```diff
@@ -0,0 +1,20 @@
+//@ revisions:riscv64gc riscv32gc riscv32imac
+
+//@[riscv64gc] compile-flags: --target=riscv64gc-unknown-linux-gnu
+//@[riscv64gc] needs-llvm-components: riscv
+// riscv64gc: !{i32 {{1}}, !"target-abi", !"lp64d"}
```
[the remark this answers is not in the document]
Comment (kxxt) [reply tests/codegen/riscv-target-abi.rs:5]: > I am almost certain `// riscv64gc: !{i32 {{1}}, !"target-abi", !"lp64d"}` doesn't check anything.

It works. If I change "lp64d" to "lp64" the test would fail.

[the remark this answers is not in the document]
Comment (jieyouxu) [reply tests/codegen/riscv-target-abi.rs:5]: https://github.com/rust-lang/rust/blob/75fd074338801fba74a8cf7f8c48c5c5be362d08/src/tools/compiletest/src/runtest.rs#L2883-L2892

You're right... that is... quite surprising 😓

File: tests/run-make/cross-lang-lto-riscv-abi/Makefile (hunk 1 above)
[the remark this answers is not in the document]
Comment (jieyouxu) [reply tests/run-make/cross-lang-lto-riscv-abi/Makefile:1]: No worries, the migration is still on-going and it's easy to following existing Makefiles and write new ones.

File: tests/run-make/cross-lang-lto-riscv-abi/Makefile [hunk 3]
```diff
@@ -0,0 +1,24 @@
...
+
+include ../tools.mk
+
+all: riscv64gc-unknown-linux-gnu riscv32imac-unknown-none-elf riscv32gc-unknown-linux-gnu
+
+define check-target =
+@echo "Testing target $(1)"
+$(RUSTC) --target $(1) -Clinker-plugin-lto=on -Cpanic=abort --crate-type=rlib -o $(TMPDIR)/libriscv-xlto.a ./riscv-xlto.rs
+$(CLANG) -target $(2) -march=$(3) -mabi=$(4) -flto=thin -fuse-ld=lld -L $(TMPDIR) -lriscv-xlto -nostdlib -o $(TMPDIR)/riscv-xlto ./cstart.c
+file $(TMPDIR)/riscv-xlto | $(CGREP) "$(5)"
```
[the remark this answers is not in the document]
Comment (kxxt) [reply tests/run-make/cross-lang-lto-riscv-abi/Makefile:13]: > I would encourage you to try to [edit PR CI](https://rustc-dev-guide.rust-lang.org/contributing.html?highlight=PR%20CI#ci) and try to run the rmake.rs version of this test with the riscv runner.

Could you share more details about how to edit PR CI? The linked doc doesn't tell how to do it.

> with the riscv runner.

Does this mean that the test runs on a riscv64 host? This test could run on regular x86_64 host as well.

[the remark this answers is not in the document]
Comment (jieyouxu) [reply tests/run-make/cross-lang-lto-riscv-abi/Makefile:13]: Ah wait, this is just checking if the library contains the string ABI? Sorry I thought for some reason you were running some executable.

[the remark this answers is not in the document]
Comment (jieyouxu) [reply tests/run-make/cross-lang-lto-riscv-abi/Makefile:13]: Ah, but:
> needs-matching-clang — ignores if the version of clang does not match the LLVM version of rustc. These tests are always ignored unless a special environment variable is set (which is only done in one CI job).
> -- <https://rustc-dev-guide.rust-lang.org/tests/headers.html?highlight=needs-matching-clang#ignoring-tests>

you may want to still edit PR CI to try run this specific CI job (I'll go ask around which one this is, lol) so if it fails, it doesn't fail in the full CI build.

See [Testing with CI](https://rustc-dev-guide.rust-lang.org/tests/ci.html?highlight=ci.yml#using-ci-to-test) for how to edit PR CI.

[the remark this answers is not in the document]
Comment (kxxt) [reply tests/run-make/cross-lang-lto-riscv-abi/Makefile:13]: > needs-matching-clang 
Actually I am testing locally with a non-matching-clang (clang16) and it works as well. But other cross-language LTO run-makes have this condition so I added it as well.

[the remark this answers is not in the document]
Comment (jieyouxu) [reply tests/run-make/cross-lang-lto-riscv-abi/Makefile:13]: Then it's probably fine.

File: src/tools/tidy/src/allowed_run_make_makefiles.txt [hunk 4]
```diff
@@ -36,6 +36,7 @@ run-make/crate-hash-rustc-version/Makefile
 run-make/crate-name-priority/Makefile
 run-make/cross-lang-lto-clang/Makefile
 run-make/cross-lang-lto-pgo-smoketest/Makefile
+run-make/cross-lang-lto-riscv-abi/Makefile
```
[the remark this answers is not in the document]
Comment (kxxt) [reply src/tools/tidy/src/allowed_run_make_makefiles.txt]: Now it's converted to a rmake test.

File: compiler/rustc_codegen_llvm/src/context.rs [hunk 5]
```diff
@@ -326,6 +327,23 @@ pub unsafe fn create_module<'ll>(
         llvm::LLVMMDNodeInContext(llcx, &name_metadata, 1),
     );
 
+    // Emit RISC-V specific target-abi metadata
+    // to workaround lld as the LTO plugin not
+    // correctly setting target-abi for the LTO object
+    // FIXME: https://github.com/llvm/llvm-project/issues/50591
+    // If llvm_abiname is empty, emit nothing.
+    if matches!(sess.target.arch.as_ref(), "riscv32" | "riscv64" | "riscv128")
```
Comment (nikic) [inline compiler/rustc_codegen_llvm/src/context.rs:335]: We don't have a riscv128 target. If you want to be forward compatible to that degree, I'd make this a starts_with.

File: tests/codegen/riscv-target-abi.rs (hunk 2 above)
Comment (nikic) [inline tests/codegen/riscv-target-abi.rs:5]:
```suggestion
// riscv64gc: !{i32 1, !"target-abi", !"lp64d"}
```
Why the `{{1}}`?

File: tests/codegen/riscv-target-abi.rs [hunk 6]
```diff
@@ -0,0 +1,20 @@
...
+
+//@[riscv32gc] compile-flags: --target=riscv32gc-unknown-linux-musl
+//@[riscv32gc] needs-llvm-components: riscv
+// riscv32gc: !{i32 {{1}}, !"target-abi", !"ilp32d"}
+
+//@[riscv32imac] compile-flags: --target=riscv32imac-unknown-none-elf
+//@[riscv32imac] needs-llvm-components: riscv
+// riscv32imac-NOT: !{i32 {{1}}, !"target-abi", !""}
```
Comment (nikic) [inline tests/codegen/riscv-target-abi.rs:13]:
```suggestion
// riscv32imac-NOT: !"target-abi"
```
I'd be more liberal with the CHECK-NOT, otherwise there is a risk it will not trigger due to some minor difference in the output.

**Review by nikic — COMMENTED** [review]
The LLVM changes look reasonable to me.

File: tests/codegen/riscv-target-abi.rs (hunk 2 above)
Comment (kxxt) [reply tests/codegen/riscv-target-abi.rs]: Fixed. I directly copied it from the output of `llvm-dis`.

File: compiler/rustc_codegen_llvm/src/context.rs (hunk 5 above)
Comment (kxxt) [reply compiler/rustc_codegen_llvm/src/context.rs]: Fixed. I removed `riscv128`. I am intentionally avoiding `starts_with` because another architecture might(possibly not) appear in the future that starts with `riscv`.

File: tests/codegen/riscv-target-abi.rs (hunk 6 above)
Comment (kxxt) [reply tests/codegen/riscv-target-abi.rs]: Fixed

File: tests/run-make/cross-lang-lto-riscv-abi/rmake.rs [hunk 7]
```diff
@@ -0,0 +1,75 @@
...
+                ^ dbg!(str::from_utf8(&output.stdout).unwrap())
+                    .contains("EF_RISCV_FLOAT_ABI_DOUBLE"))
+        )
+    } else {
+        handle_failed_output(output);
+    }
+}
+
+fn main() {
+    check_target("riscv64gc-unknown-linux-gnu", "riscv64-linux-gnu", "rv64gc", "lp64d", true);
```
Comment (DianQK) [inline tests/run-make/cross-lang-lto-riscv-abi/rmake.rs:71]: Can we add or just test the default values for `-mabi` and `-march`?

**Review by dianqk — COMMENTED** [review]
I think we can drop cffc0f5ce2470540578bf3d28a7cfd91f72a2166 now.

File: tests/run-make/cross-lang-lto-riscv-abi/rmake.rs (hunk 7 above)
Comment (kxxt) [reply tests/run-make/cross-lang-lto-riscv-abi/rmake.rs:71]: I think we can drop `-mabi` because probably clang could compute that from `-march`

File: tests/run-make/cross-lang-lto-riscv-abi/rmake.rs [hunk 8]
```diff
@@ -0,0 +1,75 @@
...
+        .arg("cstart.c")
+        .arg(tmp_dir().join("libriscv_xlto.rlib"));
+    eprintln!("{cmd:?}");
+    let output = cmd.output().unwrap();
+    if !output.status.success() {
+        handle_failed_output(output);
+    }
+    // Check that the built binary has correct float abi
+    let llvm_readobj =
+        PathBuf::from(env::var("LLVM_BIN_DIR").unwrap()).join(bin_name("llvm-readobj"));
```
Comment (DianQK) [inline tests/run-make/cross-lang-lto-riscv-abi/rmake.rs:54]: @jieyouxu 
Just a question, unrelated to this PR: Is putting this type of code into `run_make_support` part of the plan?

File: tests/run-make/cross-lang-lto-riscv-abi/rmake.rs (hunk 7 above)
Comment (DianQK) [reply tests/run-make/cross-lang-lto-riscv-abi/rmake.rs]: I can reproduce the issue when dropping `-march`. I'm not sure if we also need this parameter. It might not matter.

**Review by dianqk — APPROVED** [review]
I can reproduce the issue when dropping `-march`. I'm not sure if we also need this parameter. It might not matter.

For me, using `drop` instead of `revert` is better. This commit does not contribute to the history.

**Comment by kxxt** [comment]
> I can reproduce the issue when dropping `-march`. I'm not sure if we also need this parameter. It might not matter.

I don't think we should drop `-march`, because the clang target triple doesn't specify the extensions(especially if the d ext is available, which should be what causing the default float abi to be different)

> For me, using `drop` instead of `revert` is better. This commit does not contribute to the history.

Should I keep all the micro commits or squash them?

**Comment by DianQK** [comment]
> > For me, using `drop` instead of `revert` is better. This commit does not contribute to the history.
> 
> Should I keep all the micro commits or squash them?

As far as I know, the current rust repository has very liberal requirements for commits. I think it's fine to keep them as long as they are helpful for reviewing the commit history. :)

**Comment by kxxt** [comment]
> > > For me, using `drop` instead of `revert` is better. This commit does not contribute to the history.
> > 
> > 
> > Should I keep all the micro commits or squash them?
> 
> As far as I know, the current rust repository has very liberal requirements for commits. I think it's fine to keep them as long as they are helpful for reviewing the commit history. :)

Thanks for your review! I have rebased the history into two commits.

File: compiler/rustc_codegen_llvm/src/context.rs [hunk 9]
```diff
@@ -326,6 +327,23 @@ pub unsafe fn create_module<'ll>(
...
 
+    // Emit RISC-V specific target-abi metadata
+    // to workaround lld as the LTO plugin not
+    // correctly setting target-abi for the LTO object
+    // FIXME: https://github.com/llvm/llvm-project/issues/50591
+    // If llvm_abiname is empty, emit nothing.
+    if matches!(sess.target.arch.as_ref(), "riscv32" | "riscv64")
+        && !sess.target.options.llvm_abiname.is_empty()
+    {
+        let llvm_abiname = CString::new(sess.target.options.llvm_abiname.as_ref()).unwrap();
```
Comment (yujincheng08) [inline compiler/rustc_codegen_llvm/src/context.rs:338]: instead of creating a new `cstr`, I think we can follow other parts to pass `value` and `valueLen` to create a StringRef

File: compiler/rustc_codegen_llvm/src/context.rs [hunk 10]
```diff
@@ -326,6 +327,23 @@ pub unsafe fn create_module<'ll>(
...
+        llvm::LLVMRustAddModuleFlagString(
+            llmod,
+            llvm::LLVMModFlagBehavior::Error,
+            c"target-abi".as_ptr() as *const _,
+            llvm_abiname.as_ptr() as *const _,
```
Comment (yujincheng08) [inline compiler/rustc_codegen_llvm/src/context.rs:343]:
```suggestion
            c"target-abi".as_ptr(),
            sess.target.llvm_abiname.as_ptr().cast(),
            sess.target.llvm_abiname.len(),
```

File: compiler/rustc_codegen_llvm/src/llvm/ffi.rs [hunk 11]
```diff
@@ -1801,12 +1801,20 @@ extern "C" {
     ///
     /// In order for Rust-C LTO to work, module flags must be compatible with Clang. What
     /// "compatible" means depends on the merge behaviors involved.
-    pub fn LLVMRustAddModuleFlag(
+    pub fn LLVMRustAddModuleFlagU32(
```
Comment (yujincheng08) [inline compiler/rustc_codegen_llvm/src/llvm/ffi.rs:1804]: maybe we can keep its name so that the change can be smaller; consider only riscv needs to set a string flag.

File: compiler/rustc_codegen_llvm/src/llvm/ffi.rs [hunk 12]
```diff
@@ -1801,12 +1801,20 @@ extern "C" {
...
         merge_behavior: LLVMModFlagBehavior,
         name: *const c_char,
         value: u32,
     );
+
+    pub fn LLVMRustAddModuleFlagString(
+        M: &Module,
+        merge_behavior: LLVMModFlagBehavior,
+        name: *const c_char,
+        value: *const c_char,
```
Comment (yujincheng08) [inline compiler/rustc_codegen_llvm/src/llvm/ffi.rs:1815]:
```suggestion
        value: *const c_char,
        valueLen: size_t,
```

Comment (yujincheng08) [reply compiler/rustc_codegen_llvm/src/llvm/ffi.rs:1815]: sorry, I forgot this 🤦

File: compiler/rustc_codegen_llvm/src/context.rs (hunk 9 above)
Comment (kxxt) [reply compiler/rustc_codegen_llvm/src/context.rs]: Thanks for your review! This is clearly a better way.

File: compiler/rustc_codegen_llvm/src/llvm/ffi.rs (hunk 11 above)
Comment (kxxt) [reply compiler/rustc_codegen_llvm/src/llvm/ffi.rs:1804]: I think it doesn't hurt because the current naming scheme is more consistent(method name with a type suffix. And we don't have to care about patch size.

File: tests/run-make/cross-lang-lto-riscv-abi/rmake.rs [hunk 13]
```diff
@@ -0,0 +1,74 @@
...
+    // Rust part
+    rustc()
+        .input("riscv-xlto.rs")
+        .crate_type("rlib")
+        .target(target)
+        .panic("abort")
+        .linker_plugin_lto("on")
+        .run();
+    // C part
+    let clang = env::var("CLANG").unwrap();
```
Comment (jieyouxu) [inline tests/run-make/cross-lang-lto-riscv-abi/rmake.rs:33]: Probably also convert `clang` into a wrapper struct in `run_make_support` so other tests can use a helper from the support library.

File: tests/run-make/cross-lang-lto-riscv-abi/rmake.rs (hunk 8 above)
Comment (jieyouxu) [reply tests/run-make/cross-lang-lto-riscv-abi/rmake.rs:53]: If it feels like too much work, that is also okay. I'm happy to accept this PR as is without refactoring out the commands to helper structs in the support library, I can write a follow up PR to do the refactoring (there might be some API experimentation work).

File: tests/run-make/cross-lang-lto-riscv-abi/rmake.rs (hunk 13 above)
Comment (jieyouxu) [reply tests/run-make/cross-lang-lto-riscv-abi/rmake.rs:33]: It's also okay to leave the PR as is, I can follow it up with refactoring the helper structs out.

File: tests/run-make/cross-lang-lto-riscv-abi/rmake.rs (hunk 8 above)
Comment (jieyouxu) [reply tests/run-make/cross-lang-lto-riscv-abi/rmake.rs:53]: I thought about it some more: I'm happy with accepting this PR as is. I'll follow up with a refactor PR so kxxt doesn't have to do the support library work (which feels like unnecessary busy work for the intent of this PR).

**Comment by jieyouxu** [comment]
Thank you for the fix @kxxt! The changes for the intent of this PR looks good to me. I'll make sure to follow it up with the support library work.
@bors r+ rollup

**Comment by jieyouxu** [comment]
wtf is this parsing bors
@bors r-
