### PR TITLE
Note expr being cast when encounter NonScalar cast error

### LINKED ISSUE #140491: Function pointer primitive cast not working
When running the following Rust code:

```rust
fn on_event2(event: &EventA<'_>) {

}

struct EventA<'a>(&'a ());

fn main() {
    const ptr: &'static fn(&EventA<'_>) = &on_event2 as _;
}
```
https://play.rust-lang.org/?version=stable&mode=debug&edition=2024

The cast using `as _` should succeed, or the compiler should give a clearer reason for rejection if it is truly invalid. Since the types are compatible under HRLB, i guess this coercion should ideally be allowed.

However, the compiler currently emits the following error:
```
error[E0605]: non-primitive cast: `&for<'a, 'b> fn(&'a EventA<'b>) {on_event2}` as `&for<'a, 'b> fn(&'a EventA<'b>)`
 --> src/main.rs:8:43
  |
8 |     const ptr: &'static fn(&EventA<'_>) = &on_event2 as _;
  |                                           ^^^^^^^^^^^^^^^ an `as` expression can only be used to convert between primitive types or to coerce to a specific trait object

```
This happens on stable, beta, and nightly Rust.

**Workaround:**

```RUST
fn on_event2(event: &EventA<'_>) {

}

struct EventA<'a>(&'a ());

const fn force<F: Fn(&EventA<'_>)>(x: F) -> F {
    x
}

fn main() {
    const ptr: &'static fn(&EventA<'_>) = &force(|event| { on_event2(event) });
}
```

Thanks to @_madfrog on Discord for the help

### PR DESCRIPTION
**Pull request by xizheyin**
Fixes #140491 

I added note for `expr` so that it doesn't treat `&x as T` as `&(x as T)` but `(&x) as T`. But I'm not sure if I want to add note for all NonScalar, maybe for specific `expr_ty`?

r? compiler

### CODE REVIEW

File: compiler/rustc_hir_typeck/src/cast.rs [hunk 1]
```diff
@@ -408,6 +408,15 @@ impl<'a, 'tcx> CastCheck<'tcx> {
                     self.expr_ty,
                     fcx.ty_to_string(self.cast_ty)
                 );
+
+                if let Ok(snippet) = fcx.tcx.sess.source_map().span_to_snippet(self.expr_span) {
+                    err.note(format!(
+                        "casting expr `{}` as `{}`",
```
Comment (nnethercote) [inline compiler/rustc_hir_typeck/src/cast.rs:414]: Change `expr` to `expression`, please.

**Review by nnethercote — COMMENTED** [review]
Most of the time this results in a longer message but no extra information, e.g.:
```
LL | fn main() { let u = 0u32 as (); }
   |                     ^^^^^^^^^^ an `as` expression can only be used to convert between primitive types or to coerce to a specific trait object
   |
   = note: casting expr `0u32` as `()`
```
It's obvious that `0u32` is cast as `()`, it's right there above. Is it possible to only add the note when the type being cast to is partially/fully unspecified?

Also, in the `issue-73886.rs` we see some cases where the type is partially unspecified but the error message doesn't give any extra information:
```
   = note: casting expr `&&[0]` as `&[_]`
   = note: casting expr `7u32` as `Option<_>`
```
It would be nice if the `_` were actually expanded here.

BTW, two thumbs up for adding the new test in the first commit and then doing the rest of the changes in the second commit. That makes reviewing easier.

**Comment by xizheyin** [comment]
Thanks for review ：）

> It's obvious that 0u32 is cast as (), it's right there above. Is it possible to only add the note when the type being cast to is partially/fully unspecified?

Indeed, it doesn't seem necessary to add duplicate notes for some simple types, and we can add notes when expressions are composite types such as references, for example, are added. However, the type may not be what this PR needs to address, but rather should indicate which expression is being converted.

>error[E0605]: non-primitive cast: `&&[i32; 1]` as `&[_]`

In `issue-73886.rs`, the original message is here. I think this is a very good expansion to know what `_` is and needs a separate PR. this PR is specific to #140491 and we may just need to hint at the expression.

> BTW, two thumbs up for adding the new test in the first commit and then doing the rest of the changes in the second commit. That makes reviewing easier.

Yes, this was handed to me the last time you reviewed my PR, and I've been doing this ever since.

File: compiler/rustc_hir_typeck/src/cast.rs [hunk 2]
```diff
@@ -408,6 +408,13 @@ impl<'a, 'tcx> CastCheck<'tcx> {
                     self.expr_ty,
                     fcx.ty_to_string(self.cast_ty)
                 );
+
+                if let Ok(snippet) = fcx.tcx.sess.source_map().span_to_snippet(self.expr_span)
+                    && matches!(self.expr.kind, ExprKind::AddrOf(..))
+                {
+                    err.note(format!("casting reference expression `{}`", snippet));
+                }
+
```
Comment (xizheyin) [inline compiler/rustc_hir_typeck/src/cast.rs:417]: Now, it will emit note only when the expression is `&...`.

File: tests/ui/coercion/issue-73886.stderr [hunk 3]
```diff
@@ -3,6 +3,8 @@ error[E0605]: non-primitive cast: `&&[i32; 1]` as `&[_]`
    |
 LL |     let _ = &&[0] as &[_];
    |             ^^^^^^^^^^^^^ an `as` expression can only be used to convert between primitive types or to coerce to a specific trait object
+   |
+   = note: casting reference expression `&&[0]`
```
Comment (xizheyin) [inline tests/ui/coercion/issue-73886.stderr:7]: The explicit note looks like making sense, bacause some body would mistake it as `&(&[0] as &[_])` subconsciously.

**Review by xizheyin — COMMENTED** [review]
@rustbot ready

File: tests/ui/coercion/issue-73886.stderr (hunk 3 above)
Comment (nnethercote) [reply tests/ui/coercion/issue-73886.stderr:7]: Sorry for the slow response. This is looking much better. I wonder if the wording could be improved a little. Is it worth explaining that `&` binds tighter than `as`? It would be even better if it could suggest `&(&[0] as &[_])` as a fix, though it's no problem if that's too hard.

**Comment by xizheyin** [comment]
Never mind. 
> Is it worth explaining that & binds tighter than as?

I think it is a useful hint!

> It would be even better if it could suggest &(&[0] as &[_]) as a fix

I'm concerned that simply suggesting parentheses may be inconsistent with the original intent of the code writer. There are a variety of situations that trigger such hints, such as &[0] as &&[_], which may require further categorization to refine the suggestions.

The current use of NOTE seems to be sufficient without being unnecessarily intrusive. Specific suggestion information can be left to be enhanced later. :)

File: tests/ui/coercion/issue-73886.stderr [hunk 4]
```diff
@@ -3,6 +3,8 @@ error[E0605]: non-primitive cast: `&&[i32; 1]` as `&[_]`
    |
 LL |     let _ = &&[0] as &[_];
    |             ^^^^^^^^^^^^^ an `as` expression can only be used to convert between primitive types or to coerce to a specific trait object
+   |
+   = note: casting reference expression `&&[0]`, where `&` binds tighter than `as`
```
[the remark this answers is not in the document]
Comment (xizheyin) [reply tests/ui/coercion/issue-73886.stderr:7]: Good suggestion. I will revise it later.

File: tests/ui/cast/func-pointer-issue-140491.stderr [hunk 5]
```diff
@@ -0,0 +1,11 @@
+error[E0605]: non-primitive cast: `&for<'a, 'b> fn(&'a Event<'b>) {my_fn}` as `&for<'a, 'b> fn(&'a Event<'b>)`
+  --> $DIR/func-pointer-issue-140491.rs:6:34
+   |
+LL | ..._>) = &my_fn as _;
+   |          ^^^^^^^^^^^ an `as` expression can only be used to convert between primitive types or to coerce to a specific trait object
+   |
+   = note: casting reference expression `&my_fn` because `&` binds tighter than `as`
```
Comment (xizheyin) [inline tests/ui/cast/func-pointer-issue-140491.stderr:7]: `because` is indeed better.

**Review by xizheyin — COMMENTED** [review]
@rustbot ready
