### PR TITLE
Use serde for target spec json deserialize

### LINKED ISSUE #144153: custom target JSON fields do not error if they have an incorrect type
If you have a custom target JSON with an incorrect type, for example `"target-c-int-width": "16"`, the value will just be silently ignored instead of erroring.

this is because of the way the JSON parsing works:
https://github.com/rust-lang/rust/blob/6caa224a242d4c7b06c317969c51862815a4454b/compiler/rustc_target/src/spec/json.rs#L83-L136

It should be changed so that it emits an error.

### PR DESCRIPTION
**Pull request by Noratrieb**
The previous manual parsing of `serde_json::Value` was a lot of complicated code and extremely error-prone. It was full of janky behavior like sometimes ignoring type errors, sometimes erroring for type errors, sometimes warning for type errors, and sometimes just ICEing for type errors (the icing on the top).

Additionally, many of the error messages about allowed values were out of date because they were in a completely different place than the FromStr impls. Overall, the system caused confusion for users.

I also found the old deserialization code annoying to read. Whenever a `key!` invocation was found, one had to first look for the right macro arm, and no go to definition could help.

This PR replaces all this manual parsing with a 2-step process involving serde.
First, the string is parsed into a `TargetSpecJson` struct. This struct is a 1:1 representation of the spec JSON. It already parses all the enums and is very simple to read and write.
Then, the fields from this struct are copied into the actual `Target`. The reason for this two-step process instead of just serializing into a `Target` is because of a few reasons

 1. There are a few transformations performed between the two formats
 2. The default logic is implemented this way. Otherwise all the default field values would have to be spelled out again, which is suboptimal. With this logic, they fall out naturally, because everything in the json struct is an `Option`.

Overall, the mapping is pretty simple, with the vast majority of fields just doing a 1:1 mapping that is captured by two macros. I have deliberately avoided making the macros generic to keep them simple.

All the `FromStr` impls now have the error message right inside them, which increases the chance of it being up to date. Some "`from_str`" impls were turned into proper `FromStr` impls to support this.

The new code is much less involved, delegating all the JSON parsing logic to serde, without any manual type matching.

This change introduces a few breaking changes for consumers. While it is possible to use this format on stable, it is very much subject to change, so breaking changes are expected. The hope is also that because of the way stricter behavior, breaking changes are easier to deal with, as they come with clearer error messages.

1. Invalid types now always error, everywhere. Previously, they would sometimes error, and sometimes just be ignored (which meant the users JSON was still broken, just silently!)
2. This now makes use of `deny_unknown_fields` instead of just warning on unused fields, which was done previously. Serde doesn't make it easy to get such warning behavior, which was the primary reason that this now changed. But I think error behavior is very reasonable too. If someone has random stale fields in their JSON, it is likely because these fields did something at some point but no longer do, and the user likely wants to be informed of this so they can figure out what to do.

   This is also relevant for the future. If we remove a field but someone has it set, it probably makes sense for them to take a look whether they need this and should look for alternatives, or whether they can just delete it. Overall, the JSON is made more explicit.

This is the only expected breakage, but there could also be small breakage from small mistakes. All targets roundtrip though, so it can't be anything too major.

fixes rust-lang/rust#144153

### CODE REVIEW

File: compiler/rustc_target/src/spec/mod.rs [hunk 1]
```diff
@@ -573,19 +590,26 @@ pub enum LinkSelfContainedDefault {
...
         Ok(match s {
             "false" => LinkSelfContainedDefault::False,
             "true" | "wasm" => LinkSelfContainedDefault::True,
             "musl" => LinkSelfContainedDefault::InferredForMusl,
             "mingw" => LinkSelfContainedDefault::InferredForMingw,
-            _ => return Err(()),
+            _ => {
+                return Err(format!(
+                    "'{s}' is not a valid `-Clink-self-contained` default. \
+                        Use 'false', 'true', 'musl' or 'mingw'",
```
Comment (klensy) [inline compiler/rustc_target/src/spec/mod.rs]: 'wasm' missed

**Comment by Noratrieb** [comment]
I am finding a lot of target json specs with values that no longer exist, even an entire test case based on the assumption that it exists while it doesn't. I am getting a lot more confidence in the error behavior thanks to this.

File: compiler/rustc_target/src/spec/mod.rs [hunk 2]
```diff
@@ -198,18 +199,28 @@ impl LldFlavor {
...
+
+    fn from_str(s: &str) -> Result<Self, Self::Err> {
+        Ok(match s {
             "darwin" => LldFlavor::Ld64,
             "gnu" => LldFlavor::Ld,
             "link" => LldFlavor::Link,
             "wasm" => LldFlavor::Wasm,
-            _ => return None,
+            _ => {
+                return Err(format!(
```
Comment (aapoalas) [inline compiler/rustc_target/src/spec/mod.rs]: **nitpick:** Unnecessary use of a macro; did you perhaps mean to include `'{s}'` in the error output?

Also, would it be better if the lld flavor and linker flavor error messages matched one another? This one says "expected one of ...` while the other says `allowed values: ...`.

File: compiler/rustc_target/src/spec/mod.rs [hunk 3]
```diff
@@ -1685,19 +1817,24 @@ impl BinaryFormat {
...
+    type Err = String;
     fn from_str(s: &str) -> Result<Self, Self::Err> {
         match s {
             "coff" => Ok(Self::Coff),
             "elf" => Ok(Self::Elf),
             "mach-o" => Ok(Self::MachO),
             "wasm" => Ok(Self::Wasm),
             "xcoff" => Ok(Self::Xcoff),
-            _ => Err(()),
+            _ => Err(format!(
```
Comment (aapoalas) [inline compiler/rustc_target/src/spec/mod.rs:1829]: **thought:** The error formats are pretty repetitive; I wonder if a few helper methods wouldn't perhaps be an improvement? Something like

```rust
#[inline(never)]
pub(crate) fn s_is_not_a_valid_value_for(s: &str, field: &str, variants: &[&str]) -> String {
  format!("'{s}' is not a valid value for {field}. Use {}", format_to_list(variants))
}
```
and then the same for the "use command to print allowed values" etc.

This'd probably also reduce the slight drift between the error messages; some say "for field. Use 'a', 'b', or 'c'." while others say `for field, expected 'a', 'b', or 'c'" or such.

**Review by aapoalas — APPROVED** [review]
LGTM :)

File: compiler/rustc_target/Cargo.toml [hunk 4]
```diff
@@ -12,7 +12,9 @@ rustc_fs_util = { path = "../rustc_fs_util" }
 rustc_macros = { path = "../rustc_macros" }
 rustc_serialize = { path = "../rustc_serialize" }
 rustc_span = { path = "../rustc_span" }
+serde = { version = "1.0.219", features = ["derive"] }
```
Comment (ultrabear) [inline compiler/rustc_target/Cargo.toml]: using serde with the derive feature causes a hard dependency on syn/procmacro2 that leads to everything that uses serde but doesn't use derive needing to wait on these expensive crates to build
The current suggested way to pull serde derive (to increase build parallelization) is to just pull the derive crate separately and use serde_derive::Deseralize etc in code
```suggestion
serde = "1.0.219"
serde_derive = "1.0.219"
```

File: compiler/rustc_target/src/spec/mod.rs [hunk 5]
```diff
@@ -198,18 +199,28 @@ impl LldFlavor {
...
+    fn from_str(s: &str) -> Result<Self, Self::Err> {
+        Ok(match s {
             "darwin" => LldFlavor::Ld64,
             "gnu" => LldFlavor::Ld,
             "link" => LldFlavor::Link,
             "wasm" => LldFlavor::Wasm,
-            _ => return None,
+            _ => {
+                return Err(format!(
+                    "invalid value for lld flavor, expected one of 'darwin', 'gnu', 'link', 'wasm'"
```
Comment (fee1-dead) [inline compiler/rustc_target/src/spec/mod.rs]:
```suggestion
            _ => {
                return Err(format!(
                    "invalid value for lld flavor: '{s}', expected one of 'darwin', 'gnu', 'link', 'wasm'"
```

File: compiler/rustc_target/src/spec/mod.rs (hunk 3 above)
Comment (fee1-dead) [reply compiler/rustc_target/src/spec/mod.rs:1829]: I'm thinking of maybe using a macro that both generates the match with its arms and also formats the error message.

File: compiler/rustc_target/Cargo.toml (hunk 4 above)
Comment (fee1-dead) [reply compiler/rustc_target/Cargo.toml]: nice suggestion, yes please do this

**Review by fee1-dead — CHANGES_REQUESTED** [review]

File: compiler/rustc_target/src/spec/mod.rs (hunk 3 above)
Comment (Noratrieb) [reply compiler/rustc_target/src/spec/mod.rs:1829]: that'd be a neat improvement in the future, but I wouldn't want to refactor the enum parsing in this PR here
