### PR TITLE
Fix CFI: f32 and f64 are encoded incorrectly for cross-language CFI

### LINKED ISSUE #115150: CFI: f32 and f64 are encoded incorrectly for cross-language CFI
I missed changing the encoding for f32 and f64 when I introduced the integer normalization option in #105452 as integer normalization does not include floating point. `f32` and `f64` should be always encoded as `f` and `d` since they are both FFI safe when their representation are the same (i.e., IEEE 754) for both the Rust compiler and Clang.

### PR DESCRIPTION
**Pull request by rcvalle**
Fix #115150 by encoding f32 and f64 correctly for cross-language CFI. I missed changing the encoding for f32 and f64 when I introduced the integer normalization option in #105452 as integer normalization does not include floating point. `f32` and `f64` should be always encoded as `f` and `d` since they are both FFI safe when their representation are the same (i.e., IEEE 754) for both the Rust compiler and Clang.

### CODE REVIEW

File: compiler/rustc_symbol_mangling/src/typeid/typeid_itanium_cxx_abi.rs [hunk 1]
```diff
@@ -462,14 +462,25 @@ fn encode_ty<'tcx>(
...
             compress(dict, DictKey::Ty(ty, TyQ::None), &mut s);
             typeid.push_str(&s);
         }
 
+        // Rust's f32 and f64 single (32-bit) and double (64-bit) precision floating-point types
+        // have IEEE-754 binary32 and binary64 floating-point layouts, respectively.
+        //
+        // (See https://rust-lang.github.io/unsafe-code-guidelines/layout/scalars.html#fixed-width-floating-point-types.)
+        ty::Float(..) => {
+            let s = String::from(match ty.kind() {
```
Comment (compiler-errors) [inline compiler/rustc_symbol_mangling/src/typeid/typeid_itanium_cxx_abi.rs:476]: This `String::from` is unnecessary

File: compiler/rustc_symbol_mangling/src/typeid/typeid_itanium_cxx_abi.rs [hunk 2]
```diff
@@ -462,14 +462,25 @@ fn encode_ty<'tcx>(
...
+                ty::Float(FloatTy::F32) => "f",
+                ty::Float(FloatTy::F64) => "d",
+                _ => "",
```
Comment (compiler-errors) [inline compiler/rustc_symbol_mangling/src/typeid/typeid_itanium_cxx_abi.rs:479]: Please remove this arm, this is essentially asking to introduce a bug here by making it possible to forget future float types in the future.

File: compiler/rustc_symbol_mangling/src/typeid/typeid_itanium_cxx_abi.rs [hunk 3]
```diff
@@ -462,14 +462,25 @@ fn encode_ty<'tcx>(
...
                 _ => "",
             });
             compress(dict, DictKey::Ty(ty, TyQ::None), &mut s);
             typeid.push_str(&s);
         }
 
+        // Rust's f32 and f64 single (32-bit) and double (64-bit) precision floating-point types
+        // have IEEE-754 binary32 and binary64 floating-point layouts, respectively.
+        //
+        // (See https://rust-lang.github.io/unsafe-code-guidelines/layout/scalars.html#fixed-width-floating-point-types.)
```
Comment (compiler-errors) [inline compiler/rustc_symbol_mangling/src/typeid/typeid_itanium_cxx_abi.rs:474]: Would it be better to link to something describing the `f` and `d` prefixes that the encoding expects for IEEE-754 floats?

**Review by compiler-errors — CHANGES_REQUESTED** [review]

File: compiler/rustc_symbol_mangling/src/typeid/typeid_itanium_cxx_abi.rs (hunk 2 above)
Comment (compiler-errors) [reply compiler/rustc_symbol_mangling/src/typeid/typeid_itanium_cxx_abi.rs:479]: Bind the float kind above on line 475 and then match that `FloatTy` here rather than calling `Ty::kind` again here.

File: compiler/rustc_symbol_mangling/src/typeid/typeid_itanium_cxx_abi.rs (hunk 1 above)
Comment (rcvalle) [reply compiler/rustc_symbol_mangling/src/typeid/typeid_itanium_cxx_abi.rs]: Done. Thanks!

File: compiler/rustc_symbol_mangling/src/typeid/typeid_itanium_cxx_abi.rs (hunk 2 above)
Comment (rcvalle) [reply compiler/rustc_symbol_mangling/src/typeid/typeid_itanium_cxx_abi.rs]: Done. Thanks!

File: compiler/rustc_symbol_mangling/src/typeid/typeid_itanium_cxx_abi.rs (hunk 3 above)
Comment (rcvalle) [reply compiler/rustc_symbol_mangling/src/typeid/typeid_itanium_cxx_abi.rs:474]: Humm... those are just the Itanium C++ encoding for these builtin types (see https://itanium-cxx-abi.github.io/cxx-abi/abi.html#mangling-builtin). Instead of referencing it, I think it makes more sense to explain why they can be directly used here instead (similarly to how it's explained in line 446 for Bool). What do you think?

**Comment by rcvalle** [comment]
Thank you for your time, @compiler-errors! Much appreciated.
