### PR TITLE
change the strategy for diverging types

### LINKED ISSUE #39808: mac-0.1.0 fails test suite due to type inference regression in Rust 1.15
```
   Doc-tests mac

running 12 tests
test format_if_0 ... FAILED
test do_while_1 ... ok
test addrs_of_0 ... ok
test do_while_0 ... ok
test inspect_1 ... ignored
test if_cfg_0 ... ok
test if_cfg_1 ... ok
test match_cfg_0 ... ok
test inspect_0 ... ok
test matches_0 ... ok
test unwrap_or_return_0 ... ok
test test_eq_0 ... ok

failures:

---- format_if_0 stdout ----
        error[E0283]: type annotations required: cannot resolve `_: std::borrow::ToOwned`
  --> <anon>:11:21
   |
11 |   let not_formatted = format_if!(false, "Vague error", "Error code {:?}", {
   |  _____________________^ starting here...
12 | |     // Note that the argument is not evaluated.
13 | |     panic!("oops");
14 | | });
   | |__^ ...ending here
   |
   = note: required by `std::borrow::Cow::Owned`
   = note: this error originates in a macro outside of the current crate

error: aborting due to previous error(s)

thread 'format_if_0' panicked at 'Box<Any>', /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/librustc/session/mod.rs:201
note: Run with `RUST_BACKTRACE=1` for a backtrace.
https://github.com/reem/rust-mac dcc9155e9d23a81e92e325899d4b6bed098bcded

failures:
    format_if_0

test result: FAILED. 10 passed; 1 failed; 1 ignored; 0 measured

error: test failed
```

This is on 1.15. Not 1.14.

cc @reem

### LINKED ISSUE #39984: Type inference regression in recent nightly
https://play.rust-lang.org/?gist=188e52dc2ba423a8f78c6e381f278cf1&version=nightly&backtrace=1

source (copied by @pnkfelix from gist linked above):
```rust
fn main() {}

fn t() -> Result<(), String> {
    return Err("".into());
    Ok(())
}
```

Maybe it's because `Ok(())` is unreachable?

See https://github.com/brson/error-chain/issues/132 for the original report.

> The breakage happens between nightlies 668864d9e 2017-02-16 and 536a900c4 2017-02-17.

### PR DESCRIPTION
**Pull request by nikomatsakis**
The new strategy is as follows. First, the `!` type is assigned
in two cases:

- a block with a diverging statement and no tail expression (e.g.,
  `{return;}`);
- any expression with the type `!` is considered diverging.

Second, we track when we are in a diverging state, and we permit a value
of any type to be coerced **into** `!` if the expression that produced
it is diverging. This means that `fn foo() -> ! { panic!(); 22 }`
type-checks, even though the block has a type of `usize`.

Finally, coercions **from** the `!` type to any other are always
permitted.

Fixes #39808.
Fixes #39984.

### CODE REVIEW

**Comment by nikomatsakis** [comment]
cc @eddyb @canndrew

**Comment by nikomatsakis** [comment]
Still experimenting here but this shows promise. run-pass and compile-fail both basically pass, though there is one stubborn compile-fail test giving me a double warning for some reason I've not yet figured out. =)

**Comment by brson** [comment]
Thanks for fixing stable regressions @nikomatsakis!

**Comment by canndrew** [comment]
Thanks for this! I just encountered yet another package that was broken by the last `!` changes, so something like this is sorely needed.

> a block with a diverging statement and no tail expression (e.g.,
`{return;}`);

Do we need to assign `!` there or could we treat it the same as `{return; ()}`?

File: src/librustc_typeck/check/mod.rs [hunk 1]
```diff
@@ -4609,6 +4606,33 @@ impl<'a, 'gcx, 'tcx> FnCtxt<'a, 'gcx, 'tcx> {
             (enclosing_loops.stack.pop().expect("missing loop context"))
         }
     }
+
+    /// Computes the resulting type from a control-flow join where one
+    /// side produced `a` and one side produced `b`. If either of
+    /// these types is `!`, then the result is the other. Otherwise,
+    /// returns the LUB of the two types.
+    pub fn join_tys(&self,
```
Comment (eddyb) [inline src/librustc_typeck/check/mod.rs]: 😻

**Comment by nikomatsakis** [comment]
@canndrew 

> Do we need to assign ! there or could we treat it the same as {return; ()}?

I believe we have to treat it as `!` because otherwise stuff like this will not type check:

```rust
let x = if foo {
    22
} else {
    return bar;
};
```

That is, if you wrote the `()` **explicitly**, the RHS has type `()`, and we error out because we can't unify `()` and `usize`. (If you left *off* the semicolon, everything would work.) So propagating the `!` in this case is basically the hack that lets this code work with or without a semicolon (which I believe it should).

I agree it's a bit undisciplined, but only a bit. There seems to be no perfect answer in terms of "how much" to check in cases like these.

**Comment by nikomatsakis** [comment]
I did a crater run, though from an earlier revision (f63d9cc81c9ee3b9637b0d0343916371235967ea). There were 2 regressions and 1 timeout:

* [aurelius-0.1.13](https://crates.io/crates/aurelius) ([before](https://tools.taskcluster.net/task-inspector/#ucxNLozlRLyExKwfd1klbA)) ([after](https://tools.taskcluster.net/task-inspector/#SofTa4_PRyOwAig2axtrRw))
* [dbench-0.1.0](https://crates.io/crates/dbench) ([before](https://tools.taskcluster.net/task-inspector/#Y9DvMl24Rd2_6XTeXSmBbQ)) ([after](https://tools.taskcluster.net/task-inspector/#Z6MEv0xzRbWNjEz6hBrVOg))
* [typedopts-1.1.2](https://crates.io/crates/typedopts) ([before](https://tools.taskcluster.net/task-inspector/#nUNK8xJrRlCBZMDEzo7bHw)) ([after](https://tools.taskcluster.net/task-inspector/#RO2MsxytS-uiO17ZHgfz8A)) -- timeout

I haven't had time to investigate yet. I'll start a run in any case with the latest revision.

**Comment by nikomatsakis** [comment]
[New crater run gives the same two regressions.](https://gist.github.com/nikomatsakis/41c9d957255aba4441f53138409d60e7) I think these are also the same problem causing the build to die. In my newer code, I am basically never creating diverging type variables; this is intentional, I wanted to see how far we could get without any fallback. It works well but we are failing with an unresolved type variable in this doctest:

```rust
```rust
use std::thread;

let handle = thread::spawn(move || {
    panic!("oops!");
});

let result = handle.join();

assert!(result.is_err());
```

At the moment, I'm not interesting in spending my weekend time on this bug any further, so I'll investigate later...

File: src/librustc_typeck/check/coercion.rs [hunk 2]
```diff
@@ -720,12 +720,6 @@ impl<'a, 'gcx, 'tcx> FnCtxt<'a, 'gcx, 'tcx> {
             let adjustment = apply(&mut coerce, &|| Some(expr), source, target)?;
             if !adjustment.is_identity() {
                 debug!("Success, coerced with {:?}", adjustment);
-                // TODO this looks dubious, I think we can do without
-                // match self.tables.borrow().adjustments.get(&expr.id) {
-                //     None |
-                //     Some(&Adjustment { kind: Adjust::NeverToAny, .. }) => (),
-                //     _ => bug!("expr already has an adjustment on it!"),
-                // };
```
Comment (eddyb) [inline src/librustc_typeck/check/coercion.rs]: I think this used to be an assert ensuring coercions are not overwritten.

Comment (nikomatsakis) [inline src/librustc_typeck/check/coercion.rs]: er dang it, I meant to keep the `bug!`, but not the `match`

**Comment by nikomatsakis** [comment]
[Crater report](https://gist.github.com/nikomatsakis/e8871e482bad89c7b608029f14239588) shows zero regressions:

- 8350 crates tested: 6260 working / 2071 broken / 0 regressed / 0 fixed / 19 unknown.

I'm a little surprised not to see any "fixed" entries, but I think that's because many of the regressions were either "fixed" by adding explicit type annotations or occurred in tests etc.

File: src/librustc_typeck/check/mod.rs [hunk 3]
```diff
@@ -3311,6 +3347,20 @@ impl<'a, 'gcx, 'tcx> FnCtxt<'a, 'gcx, 'tcx> {
             _ => self.warn_if_unreachable(expr.id, expr.span, "expression")
         }
 
+        // Non-lvalues that produce values of type `!` indicate a
```
Comment (arielb1) [inline src/librustc_typeck/check/mod.rs]: The lvalue thing looks like a hack. For example, isn't a dereference of an `*const !` an lvalue, as in `let x = *(ptr: *const !);`?

**Comment by arielb1** [comment]
I should have looked at the code earlier, but, here am I.

The lvalue thing looks like a hack. For example, isn't a dereference of an `*const !` an lvalue, as in `let x = *(ptr: *const !);`?

I think the cleanest way to solve this is to have both "bottom up" divergence (if node is entered, will node exit?) and "top down" (can node be reached from the start) reachability, where reachability is only used for "unreachable code" warnings.

Because the main thing divergence affects is whether blocks that return into `!` can return any type (correct me if I'm wrong, but I think everybody else sets divergence to `Maybe` before going into a coercion), it should probably be passed "downwards" in the block code and returned everywhere else.

Reachability should probably be passed "by &mut" and cloned when you need a lattice join.  I'm not sure about whether the reachability lattice should be `Reachable < UnreachableWarned < Unreachable` or `Reachable < Unreachable < UnreachableWarned`. This affects how many warnings we get in a case such as

```Rust
let x = if cond {
    panic!()
} else {
    panic!();
    42 //~ WARNING unreachable code
};
42 //~ WARNING? unreachable code
```

Top down unreachability means we don't emit unreachable code warnings if the diverging statement was already unreachable (e.g. `panic!(); { panic!(); 42 }`), but I am not sure that's bad. It sounds less hacky than that lvalue thing.

File: src/librustc_typeck/check/coercion.rs [hunk 4]
```diff
@@ -162,6 +163,26 @@ impl<'f, 'gcx, 'tcx> Coerce<'f, 'gcx, 'tcx> {
...
+            // otherwise constrained. An example where this arises:
+            //
+            //     let _: Option<?T> = Some({ return; });
+            //
+            // here, we would coerce from `!` to `?T`. However, we do
+            // NOT want to do this in LUB mode, since we do not want
+            // this match to get the same treatment:
+            //
+            //     let _: Option<?T> = match x {
+            //         Ok(_) => Default::default(),
```
Comment (arielb1) [inline src/librustc_typeck/check/coercion.rs]: The `_match` code uses `try_coerce` for the first arm, so you still have this problem if the arms are reversed.

Comment (nikomatsakis) [inline src/librustc_typeck/check/coercion.rs]: Ah, good catch! I am not entirely happy with that bit of code, but it seemed like the most expedient way to get the correct behavior. I had hoped to revisit it after introducing subtyping obligations (`?T <: ?U`). In any case, I'll add some examples with the match arms reversed and see what happens...

File: src/librustc_typeck/check/mod.rs (hunk 3 above)
Comment (nikomatsakis) [inline src/librustc_typeck/check/mod.rs]: Yeah, that's interesting. I agree the lvalue rule may be a bit overly broad, although it's not obvious to me that this is wrong. For example, consider `x: &!` -- referencing `*x` does not *cause* divergence, rather it's supposed to just *never happen*. That is, the fact that `x` has type `&!` and you are able to access it reflects the fact that this code is supposed to be dead. The same is true of dereferencing a pointer of type `*const !`, I would argue. It does seem like it would make sense to issue *some* sort of warning here, though!

In any case, failing to set the "diverges!" flag then only affects unreachable code warnings and whether something like `let x: ! = Some(*(ptr: *const !));` is legal (it would not be). Put another way, the diverges flag is a conservative approximation, and it should always be safe to set it *less* (right?).

In any case, I have not yet understood your alternative proposal, so let me try to read and process that.

**Comment by nikomatsakis** [comment]
> The lvalue thing looks like a hack. For example, isn't a dereference of an *const ! an lvalue, as in let x = *(ptr: *const !);?

So, using `is_lvalue` was really supposed to be a convenient short-hand (aka a hack 😄) of sorts for narrowing down the kinds of expressions I care about, but I think the more interesting question is what I mean when I say *causes divergence* (and I'm not sure I am entirely consistent; in particular, I think I got `match x { }` wrong, and it does not "cause divergence").

In my view, accessing an lvalue of type `!` (including `*ptr` where `ptr: &const !`) is *undefined behavior*. This may indeed diverge, but it may also do many other things. Luckily, it's *supposed* to be impossible. 

In contrast, `return`, `break`, `panic!()` and `foo()` (where `fn foo() -> !`) *cause* divergence in the sense that is perfectly well-defined for control-flow to enter (and then it will, reliably, never exit normally).

In this light, `match x { }` does not cause divergence. A match with no arms is supposed to indicate a case where control-flow can't reach, but I am (incorrectly) setting the diverges flag here. I think that the right way to set the diverges flag is if there are >0 arms and all of them themselves diverge (this reflects the fact that match with no arms is a sort of special case, as we've seen elsewhere).

Anyway, I've got to run, so I'll try to do a better comparison to your proposal after I get my daughter out to school..

**Comment by nikomatsakis** [comment]
OK, I've thought more about this but not yet reached a firm conclusion. I started preparing a super-long gist with some thoughts, but I'm still churning on those, so I just wanted to post a more limited comment amending my previous one. =) In particular, I think everything I wrote about `match x { }` is *true* -- it does not "cause divergence" in the sense that I meant -- but I think I was correct to consider it as a "diverging expression" none-the-less.

This is because it essentially plays the role of a kind of *cast* -- a way for users to signal that they know the code is unreachable. Kind of a safer, statically proven form of `unreachable!()`. An example of where this might arise is something like this code from the `Void` crate:

```rust
pub fn unreachable(x: Void) -> ! {
    match x {}
}
```

But this still builds on this notion I was going for that the set of things we consider to be "diverging expressions" ought to be a largely static set, relatively isolated from type inference (it cannot be fully isolated, because of method dispatch). I think the set of diverging expressions would be as follows:

- `return` / `break` / `continue`
- `loop` (without a corresponding `break`, which we can statically see)
- invoking a fn that returns `!` (the tricky one, see below)
- a `match` where all the arms in `...` diverge (this also applies if there are zero arms)
- an `if` where both arms diverge (an `if` without an `else` cannot meet this definition, of course)

This property propagates upwards through enclosing expressions by default unless they join multiple control-flow paths (in which case it the upward propagation is included in the rules above). 

Making the set of expressions that the compiler considers to signal "unreachability" be relatively clear and syntactic seems to fit the Rust tradition to me (e.g., it is the reason we added `loop { }` rather than building on `while true { }`). But my other reason was that I want to avoid, to the extent we can, dependence on the vagaries of type inference.

However, I am beginning to question some of the constraints I was starting from. For example, I assumed that we wanted this to type-check (because a test exists, iirc):

```rust
fn foo() -> ! {
    panic!();
    22
}
```

But in retrospect I'm not sure we do. After all, I broke the unit-fallback test because it is wrong-headed, and I think this may well be wrong-headed too. It's kind of hard to make sense of type-checking dead-code, but I think that one reasonable interpretation is that "one could replace the diverging expression with **something** that would lead to a correct type-check". That seems to not be true in this case -- so why do we apply this dead tail expression? But there may well be a reasonable reason.

One thing that I definitely think we *do* want to work is guaranteeing that the `;` after a return is not significant. In other words, if `{ return }` type-checks in some context, then `{ return; }` ought to as well. This is a touch unfortunate since it means that `{ return; () }` is not necessarily equivalent. I can live with that. But I generalized this to **any** statement in the block diverging, which now seems stronger than necessary -- in other words, should `{ return; 22; }` also work? I don't think that's so important.

Anyway, this "short" comment grew to be nearly as long and disjoint as the other, but I'm going to post it anyhow. I'll probably iterate a bit more on this branch -- but I want to try and land something soon, even if we wind up tweaking it some more, since the current behavior really ought not to make it into a beta.

**Comment by nikomatsakis** [comment]
@arielb1 

> I think the cleanest way to solve this is to have both "bottom up" divergence (if node is entered, will node exit?) and "top down" (can node be reached from the start) reachability, where reachability is only used for "unreachable code" warnings.

I agree with this. The current diverges flag is sort of playing both of these rules, and it seems a bit confusing to me. I'd probably prefer to have two distinct flags, as you say, and also to thread using parameters and return values (but I've not tried to do this yet; it may be quite painful). The current system just seems a touch error-prone to me. I'm not sure I want to do this in this branch though. Maybe.

**Comment by nikomatsakis** [comment]
OK, I'm still going back and forth about how to treat `match x { }`. It is clearly a kind of coercion -- but I think I was perhaps right originally to say that it does not "cause divergence", rather it allows you to convert (e.g.) an empty enum -- or other uninhabited type -- into the `!` type, which in turn gives access to the various special coercions that values of type `!` permit. This does not necessarily imply you want an unreachable code warning though (and in fact the new warnings we were getting in the source seemed to mostly be a net negative -- the empty match was there to express that the code was ready for all cases).

**Comment by nikomatsakis** [comment]
Fixing the `match` bug that @arielb1 identified led to some more old code not compiling. One case seemed correct to me: in the parse, there was a call like `self.unreachable()?`, where `unreachable` returns `PResult<'a, T>` for any `T`. This `T` is, indeed, unconstrained.

One thing that annoys me though is this case:

```rust
    tls::with_opt(move |tcx| {
        let msg = format!("{}:{}: {}", file, line, args);
        match (tcx, span) {
            (Some(tcx), Some(span)) => tcx.sess.diagnostic().span_bug(span, &msg),
            (Some(tcx), None) => tcx.sess.diagnostic().bug(&msg),
            (None, _) => panic!(msg)
        }
    });
```

this is judged to have an unconstrained return type in my code, and it is because the way I am typing `match` is leaving its result as an unconstrained type variable. This is correct in a certain sense, but not really the result I want. I want the type to be `!`.

The easiest way to fix this would be to have the match code check if all the arms are known to have type `!` (as in this case) and then assign the `match` the type `!`. I am not thrilled about this but I guess it's not all that different from other such coercions that we do. This is the certainly the sort of "inference entanglements" I had hoped to avoid, though.

**Comment by nikomatsakis** [comment]
OK, so I've reached a sort of impasse and I'm sure how best to proceed. I'm eager to land something so as to fix the regressions, and thus considering trying to land the branch in its current state (after some cleanup). However, it still accepts some code that I don't think we should accept. I am not entirely sure what I want to do. So I thought I'd write up the scenario and some possibilities.

Note: the problem I've been struggling with is, for the most part, a separate question from the "reachability" thing that @arielb1 and I were discussing earlier, although some of the solutions I have in mind may intersect that question. The problem has to do with **diverging fallback**.

### The parts I am happy with

I am still relatively happy with:

- coercions from `!` to any type (but no other special treatment of other uninhabited types)
- coercions **into** `!` from expressions that diverge (for some suitable definition of diverge, see below)

The latter part was my mechanism to address 

### The challenge

I have a goal: I don't want any "fallback" to `!` to affect live code (with one tricky case around closures). In particular, I find cases like this very surprising. In the [current code](https://is.gd/viDMCv), it is accepted.

```rust
fn err1() {
    let x;
    
    if true {
        x = Default::default();
    } else {
        x = return;
    }
}

fn err2() {
    let x = match true {
        true => Default::default(),
        false => return,
    };
}

fn err3() {
    let x;
    
    if true {
        x = Some(Default::default());
    } else {
        x = Some(return);
    }
}
```

The problem is that the type of `return` is `!`; when we type `x = return`, we coerce this `!` to the type of `x`, which is an (hereto unresolved) type variable `?T`. This results in a fresh **divering** variable `?U` and the relation that `?U <: ?T`. Then, later on, we instantiate `?U` with `!`, which in turn forces `?T` to `!`. Bad.

On the other hand, code like **this** seems fairly natural and I would expect it to work:

```rust
fn ok1() -> ! {
    Some(panic!()) // the type of Option here that results would be `Option<!>`
}

fn ok2() -> ! {
    let x = Some(panic!());
}

fn ok3() -> ! {
    let x = Some(panic!()); // the type of Option here that results would be `Option<!>`
    let y: Option<i32> = x;
}

fn ok4() -> ! {
    let x = || panic!(); // the closure returns type `!`
    let y = Some(x()); // y could have type `Option<!>`
    let z: Option<i32> = y; // but here we want `Option<i32>`
}
```

The first example, `foo()`, is tricky because we are sort of partially ignoring types. In particular, we've got a `Option<_>` which we are coercing it to `!`. That's fine, but it leaves the `_` unconstrained. Similarly in the second example, we want to ensure that the type of `x` doesn't error out because of an unconstrained type variable. Finally, in the third example, we would ideally like type of `x` to get inferred to `Option<i32>`.

These three examples are all solved fairly elegantly by having `!` get coerced to a magic type variable that falls back to `!`. But taking that approach can lead to `errN()` being accepted. 

**The current approach I have incompletely solves this problem.** It gives the desired results in all of my examples but `err3()`, which it erroneously accepts.

### What the code is doing now

What I am doing now is trying, locally at the point of coercion, to decide if it is a "required" or "optional" coercion. The idea is that a coercion is *required* if the coercion must occur for the data in the destination to be used. So for example in `err1`, those coercions are **not** required, because there are multiple stores to the same local (in general, a coercion occuring on `x = ...` would be called "optional", which is stricter than needed). But in the `ok` examples, the coercions are taking an rvalue and "consuming" it, and that is a **required** coercion. Similarly, the coercions from match arms are optional (unless there is just one), etc.

The problem with the scheme is that the relationships between types are not quite so local. In particular, for the `err3()` example, let me give an annotated version with explicit type variables `?T`, `?U`, `?V`, and `?W`:

```rust
fn err3() {
    let x: ?T;
    
    if true {
        x = Some::<?U>(<?V as Default>::default());
    } else {
        x = Some::<?W>(return);
    }
}
```

Now here we have various coercions. For example, we have a required coercion from `?V` to `?U`:

    ?V -req-> ?U
    
This is because the value of type `?V` returned by `default()` must be consumed to produce the `Option<?U>` that results from calling `Some`. Similarly, for the second assignment, we have a required coercion from `!` to `?W`:

    ! -req-> ?W
    
And right here we see the problem. The coercion should not be considered *required*, exactly, because this entire store may not actually execute. But it is right now. This causes us to introduce a new diverging type variable (`?X`) that we unify with `?W`:

    ?X = ?W
    
At the very end of type-checking, all of the type variables are still unconstrained, and hence we default to `?X` to `!`. This leads to a chain reaction in which they all become `!`. Annoying.

How can we solve this? Here are some thoughts.

### Don't solve it

Maybe the current heuristics are good enough. Certainly they seem like they may be good enough to land this PR as a first step, just to stem the bleeding, and we can then iterate and improve them quickly on nightly. Certainly I seem to be getting more ambitious, trying to find a more complete solution to the problem than was my original goal.

### Try less hard

Something else I investigated was only allowing `!` to be coerced to another type `T` if that type was not a type variable (and doing away entirely with fallback). In other words, `!` to some other type is treated like other coercions, that only work when both types are known.  This led to some errors in our code. For example, some code like this errored out:

```rust
let (a, b, c) = match foo { };
```

This happened beacuse `match foo { }` has type `!`. The "expected type" here is a type variable, so we do no coercion, which winds up setting that type variable to `!`, effectively. Then the pattern matching code says "expected a tuple, found `!`". We could probably fix this with a special case around lets that will coerce from `!` to a type variable if the pattern is something other than a simple binding (i.e., if the pattern has some type constraints it will introduce). (Alternatively, you could imagine the `let` deriving a better expected type based on the pattern.) For now I worked around it by doing `let (a, b, c): (_, _, _) = match foo { }`.

This approach will not fix `ok3()` or `ok4()` because the variable `y` will be assigned `Option<!>` which will not coerce to `Option<i32>`. This *sort of* coercion problem occurs elsewhere in Rust  though and may be something we can improve orthogonally as we improve coercions.

I'm currently experimenting more with this approach. It definitely has appeal in its simplicity! Initial experiments showed a lot of broken code, but I've since cleaned up the code a bunch and my latest branches may work better.

### The "tracing" approach

The approach that I found most appealing at first was to say "oh forget diverging variables" and instead say that at the end, during writeback, if we find a node with a type that mentions an unresolved type variable, we will only give an error if that node is reachable from the fn start. Otherwise, we'll just replace said variable with `!`. So e.g. here:

```rust
fn ok_trace1() {
    return;
    let _x = Some(return); // _x has type Option<?T> where ?T is unconstrained
}
```

while the type of `_x` is `Option<?T>` and `?T` is unconstrained, we would not report an error because the `let` is unreachable. Instead we would convert the type of `?T` to `!` during writeback. The "principled" way to think about this is that it is as if, in dead code, we allow `!` types to be replaced with arbitrary types during typeck, or perhaps as if we just kind of ignore dead-code during typeck, not sure.

Anyway, that seemed at least unlikely to assign surprising types to live code, but I realized later it didn't account for pending trait obligations, which may have been incurred in dead-code but would still trigger errors:

```rust
fn foo<T: Debug>(t: T);

fn ok4() {
    return;
    let _x = Some(return); // _x has type Option<?T> where ?T is unconstrained
    foo(_x); // (Option<?T>: Debug) only if (?T: Debug), `?T: Debug` can never be solved
}
```

We might update the type of `_x` to `Option<!>`, but that still leaves `?T` unconstrianed, and so we still can't prove that `?T: Debug`. I imagine we'll have problems with implicit `?T: Sized` obligations or something for sure.

To fix that one might consider walking all code reachable from the fn entry and collect all type variables that appear in those expressions in some form. Let's call these the "live root variables". Then we can find the transitive set of type variables that are potentially related to a live variable because they appear in the same predicate. So e.g. if we have a live root variable `?T` and a pending trait obligation `?T: Borrow<?U>`, then both `?T` and `?U` would be considered "live" (all of this is of course taking place once we have fully resolved all pending trait obligations to the extent we are able). Now we can default all type variables that are not in this live set. In this case, `?T` would be defaulted to `!`.

This makes me somewhat nervous though for two reasons:

- if we adjust how our trait checker works (e.g., by not breaking down a complex `T: Foo<U...V>` predicate into simpler ones, as I plan to do), will we change the set of live variables (in particular, will we make it bigger?). I believe we would, which *could* cause regressions.
- it's a different notion of defaulting than we've had in the past, maybe we come to regret it somehow?

I still feel like the "right fix" lies somewhere down this path though.

### Incorporate reachability

Perhaps there's a way to instead improve the notion of "required" or "default" by incorporating reachability. But I feel like every scheme I've tried in this direction has led to a dead end in one form or another.

**Comment by nikomatsakis** [comment]
UPDATE: In my big comment I wrote, describing the "only coerce to a type we know" approach:

> I'm currently experimenting more with this approach. It definitely has appeal in its simplicity! Initial experiments showed a lot of broken code, but I've since cleaned up the code a bunch and my latest branches may work better.

Unfortunately, this [seems to break a lot of code](https://gist.github.com/nikomatsakis/5966f5d71cf9be076b84a0ad503b344f). The first example I looked at could be reduced to this pattern, which basically corresponds to the case where the correct type isn't known until later (and isn't propagated through the expectations with sufficient precision):

```rust
fn produce<T>() -> Result<&'static str, T> {
    Ok("22")
}

fn main() {
    let x: usize = produce()
        .and_then(|x| x.parse())
        .unwrap_or_else(|_| panic!());
    println!("{}", x);
}
```

this fails because the `unwrap_or_else!` produces a value of type `!` (exactly the closure challenge I highlighted in one of my examples...) which winds up then forcing `x.parse()` to the type `!`, but `!: FromStr` doesn't hold.

**Comment by tbu-** [comment]
Does this also fix #39984?

**Comment by nikomatsakis** [comment]
Hmm. So I also did a crater run of my current branch. This yields [34 regressions of its own](https://gist.github.com/nikomatsakis/82ff33afcf3790a9dbb14a0de5824857). They all fall into variations of the same pattern, interestingly one I had hoped to ban.

A number of them look like `try!(Err(...))`, from  the rustyline crate:

```rust
try!(Err(nix::Error::from_errno(ENOTTY)));
```

In this case, the type of `try!` is not restricted. In the older code, this desugars to a `match`, and the type is thus combined with a diverging type variable. This means that today it will fall back to `()` -- interestingly, under the `!` RFC, it will now fall back to `!`. In this case, I suppose, that is correct.

Here is a similar example, but where falling back to `!` seems wrong (from the `serde v0.9.11` crate, and specifically `src/decoder/serde.rs:364:17`), though I'd have to dig into it more deeply to be sure:

```rust
try!(Deserialize::deserialize(Decoder::new(val)));
```

This type will fallback to `()` today. I ... doubt falling back to `!` would be OK.

OK, don't have more time to categorize today. Perhaps the answer to preventing this sort of influence is just to give and not try to ban it (so as to avoid regressions). I still feel sort of unhappy with that, though. (Falling back to `!`, as opposed to `()`, is obviously not yet stable.)

**Comment by nikomatsakis** [comment]
Just one note. I spent some more time thinking about it. Looking at the `try!(Err(..))` examples makes me a bit less upset about the fallback from one match arm affecting the other. It seems to depend a bit on what traits get implemented for `!`. If we only implement traits for `!` when the type parameter plays an "input data" role, i.e., *not* `Default` but yes `Debug`, it seems harmless and maybe even desirable to fall back to `!`. We could integrate do some work to improve the error messages (so that they make it clear that `!` was chosen due to an absence of type annotations), but it feels unlikely to lead to surprise behavior at runtime.

On the other hand, if (e.g.) `serde` implements `Deserialize` for `!`, than something like this is kind of scary:

```rust
try!(Deserialize::deserialize(Decoder::new(val)));
```

**Comment by nikomatsakis** [comment]
I did “another crater run](https://gist.github.com/nikomatsakis/050dbd6a34f8e4f49a95b8eca1b2a251) where I give up on preventing `!` fallback in live code. This results in 9 "regressions", but they either look orthogonal to this PR (e.g., changes to syntax, channels) or they are false positives.

**Comment by eddyb** [comment]
@nikomatsakis That sounds great, but will this have to be backported since it missed beta?

**Comment by nikomatsakis** [comment]
@eddyb it will; I have to cleanup the history and stuff. 

I have to say I am still fairly unhappy with the idea that `match ... { _ => default(), _ => return }` falls back to `!`. This is certainly *mitigated* by the idea of not implementing `!` for traits that produce a `!` without a `!` coming in as input (I think that `Deserialize::deserialize` makes for an interesting thought experiment, since the "input" is that call to `Serialize::serialize`, presumably...). But ultimately it seems just...weird to fall back the result of one arm because **some other arm** might diverge.

In talking with @pnkfelix, we had an alternative idea that yields a similar result, but does so in a more tailored way. Specifically, we could say that when you instantiate one enum variant (say, `Err`), any type parameters which do not appear in the variant in question get a diverging fallback. So the type of `Err(x)` is `Result<?T, X>`, where `?T` falls back to `!`.

This would allow `Err(x)?` to work as expected, while making `Deserialize::deserialize()?` fail as requiring a type annotation.

It may be a good idea to try and land this PR, though, and then pursue these refactorings as a second step.

This result is not perfect. One can still write things like:

```rust
let mut x = Err(E);
x = Ok(Deserialize::deserialize()?);
```

and you get weird fallback again. This could perhaps be mitigated by a lint that local variables should not have types that fall back to `!` (i.e., one should label `x: Result<!, _>` explicitly, to prevent confusion).

I think right now this is still my preferred plan.

This implies that, to land, I have to:

- cleanup the code and land it;
- probably address the reachability warning concerns that @arielb1 had, although perhaps that could be deferred to a follow-up PR;
    - the question really is what set of expressions we allow to be coerced to `!`. The PR as implemented seems to permit a fairly conservative set of expressions in some respects, so I guess it can be made compatible with most things.
- do a follow-up PR experimenting with this alternative strategy I just outlined.

**Comment by nikomatsakis** [comment]
OK, I cleaned up the history. I definitely made a number of changes in this branch. I think that the major things were:

- Allow coercions **into** `!` if the expression "diverges".
- A block with no tail expression whose statements diverge has type `!`, not `()`.
- Propagate types upward as normal.
- Do not eagerly convert `!` into a diverging type variable, but do so as part of coercions.
- Encapsulate the "coerce many expressions into one common type" logic into `CoerceMany`:
    - this involved porting a number of bits of `rustc_typeck::check` to use that

I would like to do a follow-up PR to do two things:

- Experiment with changing how diverging type variables work, so that we source them when accessing enum variants and not due to control-flow, which would minimize the "surprising" results.
- Adjusting how we issue unreachable code warnings:
    - I think we should probably do a pass at the end, when types are fully inferred, to know what is reachable and what is not, and try to issue warnings in some minimal way. We could also check coercions *into* `!` at that time (because it could happen that some expression winds up having type `!`, even though we didn't know it during the initial type walk). But see below for a more thoughts.

These seem like fine work but work that can wait. There is one unknown:

- Should we consider a reference to a variable of type `!` as "diverging"?
    - Changing this results in more unreachable code warnings, as you can see in the last commit.  It also affects when the result of an expression can legally be coerced to `!`.
    - I *think* I've come around to the POV that we should just consider any expression whose type is `!` as diverging, but change how we issue unreachable code warnings, as described above. 
    - Because this affects what can be coerced into `!`, though, leaving the code as is (where lvalues of type `!` do not "cause" divergence) would be the more conservative thing to do for now.

Now the bigger question is:

- Should I try to isolate out the bare minimum of these changes for backport, and land that first?
- Or just land this code as is?

I'm not entirely sure which of those changes are needed just fix the bug, but I can experiment. It seems clear that the `CoerceMany` change is not *strictly needed*, for example. Probably it suffices to introduce the "into `!`" coercion and re-institute checking of types "upward", but I'd also like to remove the eager coercion from `!` into type variables, I think.

**Comment by nikomatsakis** [comment]
After some consideration, I think the thing to do is to first simply revert https://github.com/rust-lang/rust/pull/39485 -- this should fix the regressions. We can backport that change. Then I will try to land this PR (perhaps after some more changes) on nightly.

**Comment by nikomatsakis** [comment]
PR is up: https://github.com/rust-lang/rust/pull/40636

**Comment by nikomatsakis** [comment]
I just pushed a new "reachability" pass. This reworks how unreachable code warnings are issued. It basically moves the "diverges" code computation into its own pass at the end, along the lines that @arielb1 sketched out (pushing down reachability information and propagating divergence information back up). I haven't removed the "diverges" logic out of `typeck` yet, though that is my eventual plan.

**Comment by nikomatsakis** [comment]
r? @eddyb 

I've decided I was trying to get too ambitious with this PR and have backed out any attempts to revamp how unreachable warnings are issued. I also removed the special case around lvalues that @arielb1 didn't like, which just means we get an extra unreachable code warning but otherwise doesn't have much effect (I suppose it means more coercions to `!` are allowed, but not in a way that I am uncomfortable with). I will try to do a follow-up PR (or perhaps mentor someone) that considers tweaking how we issue unreachable code warnings (right now we issue more than perhaps we ought to, but that's harmless enough) and tries some different strategies around diverging type variables. Meanwhile, I'd still like to land the changes in this PR -- they fix #39808 if nothing else, and the strategy just seems to be overall more reasonable.

To review, the main user-facing changes in the PR are as follows:

- We allow coercions **into** `!` if the expression "diverges".
- A block with no tail expression whose statements diverge has type `!`, not `()`.
- Otherwise, we propagate types upward as normal (we no longer ignore types from dead code).

In terms of the implementation, there are some refactorings:

- Do not eagerly convert `!` into a diverging type variable, but do so as part of coercions.
- Encapsulate the "coerce many expressions into one common type" logic into `CoerceMany`:
    - this involved porting a number of bits of `rustc_typeck::check` to use that

The last crater run I did found no regressions.

File: configure [hunk 5]
```diff
@@ -772,3 +772,6 @@ fi
 
 msg "run \`python ${X_PY} --help\`"
 msg
+
+## HACK to fix crater
+git submodule update --init
```
Comment (eddyb) [inline configure]: Heh.

Comment (nikomatsakis) [inline configure]: oh, shoot, I should remove that commit. =)

File: src/librustc_typeck/check/coercion.rs [hunk 6]
```diff
@@ -837,3 +854,230 @@ impl<'a, 'gcx, 'tcx> FnCtxt<'a, 'gcx, 'tcx> {
...
+///     let expr_ty = fcx.check_expr_with_expectation(expr, expected);
+///     coerce.coerce(fcx, &cause, expr, expr_ty);
+/// }
+/// let final_ty = coerce.complete(fcx);
+/// ```
+#[derive(Clone)] // (*)
+pub struct CoerceMany<'gcx: 'tcx, 'tcx> {
+    expected_ty: Ty<'tcx>,
+    final_ty: Option<Ty<'tcx>>,
+    expressions: Vec<&'gcx hir::Expr>,
```
Comment (eddyb) [inline src/librustc_typeck/check/coercion.rs]: Noooo 😞 The reason for the weird closures I've used so far is no allocation required.

**Comment by nikomatsakis** [comment]
cc @rust-lang/lang -- I'd like to get some feedback on the lang changes here too. I've talked about this with a number of you in person, but I wanted to send a general heads-up.

To summarize:

**What we do now** is to ignore "upward propagating types" from dead-code in subtyping rules, for the most part. This makes some sense (those values will never wind up being used), but it leaves many type-variables underconstrained, causing regressions like #39808. It also [allows somewhat surprising things](https://is.gd/Z2XzJG) like `if true { return; 22 } else { 'a' }`.

**What I have implemented** is [described here](https://github.com/rust-lang/rust/pull/40224#issuecomment-288075549). 

Note that, in both systems, the typing judgement considers whether an expression "diverges". This is based on, for the most part, a fairly obvious derivation (`return`, `break`, and other expressions with type `!` diverge; `a; b` diverges if `a` or `b` diverges; a `match` or `if` diverges if all arms diverge).

One subtle point I came across is that a `loop` is considered to diverge if there are breaks targeting it (and they don't push a value of type `!`); this can be [mildly imprecise](https://is.gd/YoyNYk) if those breaks are actually dead (even when the compiler knows that). This could be refined easily enough.

File: src/librustc_typeck/check/coercion.rs (hunk 6 above)
Comment (nikomatsakis) [inline src/librustc_typeck/check/coercion.rs]: What's the point of avoiding allocation?

Comment (nikomatsakis) [inline src/librustc_typeck/check/coercion.rs]: More specifically, I would think that the size of these vectors will mostly be very small, although I guess that for an array it could grow large (but be short-lived).

Comment (nikomatsakis) [inline src/librustc_typeck/check/coercion.rs]: I'm trying to decide if there is a way to keep the core idea (pull this logic into one place, keep it simple...) while avoiding a vector. Probably I won't be able to do much better than your closure, I guess.

Comment (eddyb) [inline src/librustc_typeck/check/coercion.rs]: It seems so wasteful given that the expressions are already readily iterable.
If you don't think it's worth optimizing for (or if you have timings that don't show typeck being measurably slower on large crates), please replace the closure-which-returns-iterator pattern with plain slices.

**Comment by joshtriplett** [comment]
@nikomatsakis This looks reasonable to me.  Ignoring types from code the compiler detects as dead seems suboptimal, since we otherwise try to make sure that code compiles and works.  Allowing it to have inconsistent types would mean the surrounding code could change and break it without warning.  Your change, to take that code into account (and also take `!` into account) looks reasonable.

File: src/librustc_typeck/check/coercion.rs [hunk 7]
```diff
@@ -897,25 +896,61 @@ impl<'a, 'gcx, 'tcx> FnCtxt<'a, 'gcx, 'tcx> {
...
+
+#[derive(Clone)] // (*)
+enum Expressions<'gcx, 'exprs, E>
+    where E: 'exprs + AsCoercionSite,
+{
+    Dynamic(Vec<&'gcx hir::Expr>),
+    UpFront(&'exprs [E]),
 }
 
 // (*) this is clone because `FnCtxt` is clone, but it seems dubious -- nmatsakis
```
Comment (eddyb) [inline src/librustc_typeck/check/coercion.rs]: Can we remove `Clone` from `FnCtxt`? It's probably a mistake, we never clone contexts.

File: src/librustc_typeck/check/coercion.rs [hunk 8]
```diff
@@ -928,7 +927,6 @@ pub struct CoerceMany<'gcx, 'tcx, 'exprs, E>
 /// a buffer. We use this in `check/mod.rs` for things like `break`.
 pub type DynamicCoerceMany<'gcx, 'tcx> = CoerceMany<'gcx, 'tcx, 'gcx, P<hir::Expr>>;
 
-#[derive(Clone)] // (*)
```
Comment (eddyb) [inline src/librustc_typeck/check/coercion.rs]: You should also remove the comment below.

**Comment by nikomatsakis** [comment]
So I had some thoughts about this branch. First off, I realized I was misunderstanding what the `self.diverges` value was telling me -- after you invoke `check_expr(...)`, if I understand correctly, then what it is telling me is really "has evaluation the current expression diverged by this point" -- there is no convenient way to find out "did this particular expression diverge".

This is visible:

```rust
fn foo(x: usize, y: !) { }
foo(return, 22) // accepted
```

Originally, I had intended not to accept that code, because the argument of type `!` has the expression `22`, which neither has type `!` nor diverges. But the current code will (I believe...) accept it. 

I'd prefer to explore changing this in a follow-up PR for two reasons:

- I want to land this already and it's a relatively minor thing
- You can't actually observe it except through the (unstable) `!` type

The only existing coercions to `!` occur on function return, and there:

- for `return <expr>`, there is only one subexpression so the two definitions coincide;
- for `fn foo() { ...; tail }`, you can consider the functions definition to be the block `{ ...; tail }`, in which case again there is only one subexpression.

In particular, we *do* accept `fn foo() { return; 22 }`, but that was intentional.

**Comment by nikomatsakis** [comment]
@eddyb OK, FIXMEs are...fixed, branch is rebased, and the tests seem to pass *locally* (well, the ones I ran...). Let's see what travis says, but I'd appreciate if you can take a look. The new-ish stuff is at the end, though I did add in one [refactor commit](https://github.com/rust-lang/rust/pull/40224/commits/aa140753b00b78ceb986c2f9fe50e29ffbb5b3ef) that changes how we signal a block that may be targeted by a break (used by `do catch { }` desugaring).

**Comment by nikomatsakis** [comment]
Unfortunately many of the older commits I'm sure no longer build on their own :(

**Comment by eddyb** [comment]
r=me with the build fixed

**Comment by nikomatsakis** [comment]
The travis failures look spurious:

```
travis_time:end:08c5b980:start=1490400417092633491,finish=1490400418277101127,duration=1184467636
[0Ktravis_fold:end:after_failure.1
[0Ktravis_fold:start:after_failure.2
[0Ktravis_time:start:04382eda
[0K$ cat obj/tmp/sccache.log
cat: obj/tmp/sccache.log: No such file or directory

travis_time:end:04382eda:start=1490400418286709747,finish=1490400418295922658,duration=9212911
[0Ktravis_fold:end:after_failure.2
[0Ktravis_fold:start:after_failure.3
[0Ktravis_time:start:03d69470
[0K$ cat /tmp/sccache.log
cat: /tmp/sccache.log: No such file or directory

travis_time:end:03d69470:start=1490400418305775112,finish=1490400418313983731,duration=8208619
[0Ktravis_fold:end:after_failure.3
[0Ktravis_fold:start:after_failure.4
[0Ktravis_time:start:02d1ea64
[0K$ ls $HOME/Library/Logs/DiagnosticReports/
ls: cannot access /home/travis/Library/Logs/DiagnosticReports/: No such file or directory

travis_time:end:02d1ea64:start=1490400418324886671,finish=1490400418333770774,duration=8884103
[0Ktravis_fold:end:after_failure.4
[0Ktravis_fold:start:after_failure.5
[0Ktravis_time:start:02da6c8e
[0K$ dmesg | grep -i kill
[   13.221860] init: failsafe main process (1136) killed by TERM signal

travis_time:end:02da6c8e:start=1490400418343583043,finish=1490400418356739882,duration=13156839
[0Ktravis_fold:end:after_failure.5
[0K
Done. Your build exited with 1.
```

**Comment by eddyb** [comment]
@nikomatsakis If you log into travis you can redo PR builds, FWIW. Better safe than sorry.
(Doesn't matter now that you have to rebase anyway)

**Comment by nikomatsakis** [comment]
@eddyb 

By the way, on the topic of this introducing a dependency on divergence into coercion, I didn't fully elaborate on IRC. The short version is that I think that dependency was already there no matter how you slice it, and this branch just makes it more explicit. For example, if we opt not to propagate types "up and out" from diverging code, we're still required to classify code as **diverging** during type-checking so to as know whether or not to do coercion in the first place. 

In any case, this **can** all be accommodated while still "deferring" coercions in the cases where not all types are known, but it would require (presumably) making the knowledge about whether an expression diverges available as an obligation (but I would assume that we'd do that anyway as part of making type checking more "asynchronous").

Of course, it does mean that if we wanted to move **all** coercions into the **trait** system, the trait itself will not be the whole story -- i.e., the trait will say "if we are not doing the divergence coercion, then we apply the trait" or something like that -- but as I noted in the first paragraph that seems to be pretty similar to where we are today.

**Comment by nikomatsakis** [comment]
@bors retry

* failure to clone in appveyor -- is there an existing issue?

**Comment by arielb1** [comment]
Actual Failure:
```

[01:34:37] ---- [pretty] pretty\issue-39808.rs stdout ----
[01:34:37] 	
[01:34:37] error: pretty-printed source does not match expected source
[01:34:37] 
[01:34:37] expected:
[01:34:37] ------------------------------------------
[01:34:37] // Copyright 2016 The Rust Project Developers. See the COPYRIGHT
[01:34:37] // file at the top-level directory of this distribution and at
[01:34:37] // http://rust-lang.org/COPYRIGHT.
[01:34:37] //
[01:34:37] // Licensed under the Apache License, Version 2.0 <LICENSE-APACHE or
[01:34:37] // http://www.apache.org/licenses/LICENSE-2.0> or the MIT license
[01:34:37] // <LICENSE-MIT or http://opensource.org/licenses/MIT>, at your
[01:34:37] // option. This file may not be copied, modified, or distributed
[01:34:37] // except according to those terms.
[01:34:37] 
[01:34:37] #![allow(unreachable_code)]
[01:34:37] 
[01:34:37] // Regression test for #39808. The type parameter of `Owned` was
[01:34:37] // considered to be "unconstrained" because the type resulting from
[01:34:37] // `format!` (`String`) was not being propagated upward, owing to the
[01:34:37] // fact that the expression diverges.
[01:34:37] 
[01:34:37] use std::borrow::Cow;
[01:34:37] 
[01:34:37] fn main() {
[01:34:37]     let _ =
[01:34:37]         if false {
[01:34:37]             Cow::Owned(format!("{:?}" , panic ! (  )))
[01:34:37]             /* as Cow<str> */
[01:34:37]              // uncomment to fix
[01:34:37]         } else { Cow::Borrowed("") };
[01:34:37] }
[01:34:37] 
[01:34:37] ------------------------------------------
[01:34:37] actual:
[01:34:37] ------------------------------------------
[01:34:37] // Copyright 2016 The Rust Project Developers. See the COPYRIGHT
[01:34:37] // file at the top-level directory of this distribution and at
[01:34:37] // http://rust-lang.org/COPYRIGHT.
[01:34:37] //
[01:34:37] // Licensed under the Apache License, Version 2.0 <LICENSE-APACHE or
[01:34:37] // http://www.apache.org/licenses/LICENSE-2.0> or the MIT license
[01:34:37] // <LICENSE-MIT or http://opensource.org/licenses/MIT>, at your
[01:34:37] // option. This file may not be copied, modified, or distributed
[01:34:37] // except according to those terms.
[01:34:37] 
[01:34:37] #![allow(unreachable_code)]
[01:34:37] 
[01:34:37] // Regression test for #39808. The type parameter of `Owned` was
[01:34:37] // considered to be "unconstrained" because the type resulting from
[01:34:37] // `format!` (`String`) was not being propagated upward, owing to the
[01:34:37] // fact that the expression diverges.
[01:34:37] 
[01:34:37] use std::borrow::Cow;
[01:34:37] 
[01:34:37] fn main() {
[01:34:37]     let _ =
[01:34:37]         if false {
[01:34:37]             Cow::Owned(format!("{:?}" , panic ! (  )))
[01:34:37]             /* as Cow<str> */
[01:34:37]             // uncomment to fix
[01:34:37]         } else { Cow::Borrowed("") };
[01:34:37] }
[01:34:37] 
[01:34:37] ------------------------------------------
```

**Comment by nikomatsakis** [comment]
/me grumbles.

Why didn't I see this locally? Weird.

**Comment by alexcrichton** [comment]
Ah that's b/c the pretty test suite is an "auxiliary" test suite, not run by default on `./x.py test`. We've got bots dedicated to running just that test suite though.

**Comment by nikomatsakis** [comment]
@alexcrichton ah, ok.

**Comment by nikomatsakis** [comment]
The failure here also occurred on #40658, so I'm inclined to think it's spurious, but I didn't find an existing issue that was a perfect match:

```
DEBUG:sccache::compiler::compiler: [opt.cpp.o]: get_cached_or_compile: -DGTEST_HAS_RTTI=0 -D_DEBUG -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -I/checkout/obj/build/x86_64-unknown-linux-gnu/llvm/build/tools/opt -I/checkout/src/llvm/tools/opt -I/checkout/obj/build/x86_64-unknown-linux-gnu/llvm/build/include -I/checkout/src/llvm/include -ffunction-sections -fdata-sections -fPIC -m64 -fPIC -fvisibility-inlines-hidden -Wall -W -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wno-missing-field-initializers -pedantic -Wno-long-long -Wno-maybe-uninitialized -Wdelete-non-virtual-dtor -Wno-comment -Werror=date-time -std=c++11 -ffunction-sections -fdata-sections -O3 -UNDEBUG -fno-exceptions -fno-rtti -o CMakeFiles/opt.dir/opt.cpp.o -c /checkout/src/llvm/tools/opt/opt.cpp
DEBUG:sccache::compiler::compiler: [PrintSCC.cpp.o]: generate_hash_key took 0.367s
DEBUG:sccache::simples3::s3: GET http://rust-lang-ci-sccache.s3.amazonaws.com/1/2/6/126e0f22c8acd9bd36edc9f751a4acaf27c47637
DEBUG:sccache::compiler::compiler: [PrintSCC.cpp.o]: Cache hit in 0.063s
DEBUG:sccache::compiler::compiler: [llc.cpp.o]: generate_hash_key took 0.419s
DEBUG:sccache::simples3::s3: GET http://rust-lang-ci-sccache.s3.amazonaws.com/1/8/c/18c8dfbbd6c1e3447f36e33bd003f32630798f53
DEBUG:sccache::compiler::compiler: [opt.cpp.o]: generate_hash_key took 0.391s
DEBUG:sccache::simples3::s3: GET http://rust-lang-ci-sccache.s3.amazonaws.com/2/3/e/23e0f4a5ba1f5226357c1c5c0e4870d582ae62ca
DEBUG:sccache::compiler::compiler: [llc.cpp.o]: Cache hit in 0.172s
DEBUG:sccache::server: handle_client: compile
DEBUG:sccache::server: check_compiler: Supported compiler
DEBUG:sccache::server: parse_arguments: CannotCache
DEBUG:sccache::compiler::compiler: [opt.cpp.o]: Cache hit in 0.251s
DEBUG:sccache::server: handle_client: compile
DEBUG:sccache::server: check_compiler: Supported compiler
DEBUG:sccache::server: parse_arguments: CannotCache
INFO:sccache::server: shutting down due to being idle
INFO:sccache::server: moving into the shutdown phase now, waiting at most 10 seconds for all client requests to complete
INFO:sccache::server: ok, fully shutting down now

travis_time:end:0803dc6d:start=1490771155803193037,finish=1490771155836915395,duration=33722358
[0Ktravis_fold:end:after_failure.2
[0Ktravis_fold:start:after_failure.3
[0Ktravis_time:start:059c6d28
[0K$ cat /tmp/sccache.log
cat: /tmp/sccache.log: No such file or directory

travis_time:end:059c6d28:start=1490771155847296516,finish=1490771155855375590,duration=8079074
[0Ktravis_fold:end:after_failure.3
[0Ktravis_fold:start:after_failure.4
[0Ktravis_time:start:0c2efde0
[0K$ ls $HOME/Library/Logs/DiagnosticReports/
ls: cannot access /home/travis/Library/Logs/DiagnosticReports/: No such file or directory

travis_time:end:0c2efde0:start=1490771155863890829,finish=1490771155872203016,duration=8312187
[0Ktravis_fold:end:after_failure.4
[0Ktravis_fold:start:after_failure.5
[0Ktravis_time:start:1a068f87
[0K$ dmesg | grep -i kill
[   12.200172] init: failsafe main process (1140) killed by TERM signal
[   48.816203] init: plymouth-upstart-bridge main process (524) killed by TERM signal

travis_time:end:1a068f87:start=1490771155881189686,finish=1490771155893577765,duration=12388079
[0Ktravis_fold:end:after_failure.5
[0K
Done. Your build exited with 1.
```

**Comment by nikomatsakis** [comment]
@bors retry

* https://github.com/rust-lang/rust/issues/40240 - wedged in build logs ? ("shutting down due to being idle")

**Comment by frewsxcv** [comment]
@nikomatsakis This is the error message in the error log:

```
[00:29:54] error: `tupled_arguments` does not live long enough
[00:29:54]    --> /checkout/src/librustc_trans/abi.rs:378:13
[00:29:54]     |
[00:29:54] 372 |                     &tupled_arguments
[00:29:54]     |                      ---------------- borrow occurs here
[00:29:54] ...
[00:29:54] 378 |             }
[00:29:54]     |             ^ `tupled_arguments` dropped here while still borrowed
[00:29:54] 379 |         } else {
[00:29:54]     |         - borrowed value needs to live until here
[00:29:54] 
[00:29:55] error: aborting due to previous error
```

It's the same one I mentioned in [this comment](https://github.com/rust-lang/rust/pull/40886#issuecomment-289970105)

@bors r-

**Comment by nikomatsakis** [comment]
@frewsxcv oh, thanks, I missed that comment. (I also didn't see that in the logs...obviously.)

**Comment by nikomatsakis** [comment]
OK, so, here is the status. As @frewsxcv pointed out, this PR (specifically, the part that makes `if` arms into expressions) causes a regression, in that [the following test case currently builds but does not under this PR](https://is.gd/nzxpi3):

```rust
struct Foo {
    v: Vec<i32>
}

fn bar(f: &Foo, g: &[i32]) {
    let x = if true {
        match f {
            &Foo { ref v } => &v,
        }
    } else {
        g
    };

    println!("{:?}", x);
}

fn main() { }
```

I consider the fact that this test case builds a mildly pleasant surprise -- I haven't dug **deeply** into why it happens, but the reason that it **doesn't** work on my branch is fairly clear. The match produces a `&&Vec<i32>`; the result of the match is then coerced into `&[i32]`. However, the *initial* borrow still occurs inside the match, and it produces a result that is required to live until the coercion takes place, and by then the match arm binding has been dropped. 

Somehow, on master, we propagate the coercion **into** the match arm. @eddyb can confirm, but I think this is a somewhat accidental artifact of how the `if` code was working. For example, [this very similar test-case using a `match` does not compile](https://is.gd/6WawcF):

```rust
struct Foo {
    v: Vec<i32>
}

fn bar(f: &Foo, g: &[i32]) {
    let x = match true {
        true => {
            match f {
                &Foo { ref v } => &v,
            }
        }
        false => {
            g
        }
    };

    println!("{:?}", x);
}

fn main() { }
```

Now, I think it'd be nice to accept both of these test cases, but I'd like to do so in a principled way. Also, I'd **really like to land this branch** before we start uncovering more people relying on the current behavior. 

I did a [crater run](https://gist.github.com/nikomatsakis/14a33c0dfc930e6ab2f0905f883ab622) and found that none of the tested code is relying on this behavior. There are a few regressions (2 root, 4 total), but all of them are due to clippy code not compiling since I changed the HIR.

Therefore, assuming no objections, I'm going to land this branch as is, and file an enhancement issue regarding the "deep coercion" behavior. Might be a nice mentoring opportunity. I have to think about how straight-forward it would be to achieve
