### PR TITLE
Modifications to `std::io::Stdin` on Windows so that there is no longer a 4-byte buffer minimum in read().

### LINKED ISSUE #91722: read_to_end / read_to_string returns Invalid Input ("buffer too small") on Windows MSVC
I tried this code:

```rust
use std::io::{stdin, Read};

fn main() {
    let mut input = Vec::new();
    stdin().read_to_end(&mut input).unwrap();

    // Or:
    /*
    let mut input = String::new();
    stdin().read_to_string(&mut input).unwrap();
    */

    println!("{:?}", input);
}
```

This code can result in the error:

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { kind: InvalidInput, message: "Windows stdin in console mode does not support a buffer too small to guarantee holding one arbitrary UTF-8 character (4 bytes)" }', main.rs:5:37
```

This error is likely to happen when input is read in small chunks (e.g. a few characters per line, when line buffering is used), to slowly fill the string/vec close to its capacity. Currently, it is easily reproduceable by pressing return 15 times on the terminal input. 

This error is uncontrollable by me; when I call read_to_end, the actual read calls and the buffer sizes used are entirely controlled by code in `std`. I'd expect it to just do the right thing in this case and provide the correct size buffer, and not raise an error that the end user can't easily recover from.

### Meta

`rustc --version --verbose`:
```
rustc 1.57.0 (f1edd0429 2021-11-29)
binary: rustc
commit-hash: f1edd0429582dd29cccacaf50fd134b05593bd9c
commit-date: 2021-11-29
host: x86_64-pc-windows-msvc
release: 1.57.0
LLVM version: 13.0.0
```

Also reproducible on nightly:
```
rustc 1.59.0-nightly (efec54529 2021-12-04)
binary: rustc
commit-hash: efec545293b9263be9edfb283a7aa66350b3acbf
commit-date: 2021-12-04
host: x86_64-pc-windows-msvc
release: 1.59.0-nightly
LLVM version: 13.0.0
```

<details><summary>Backtrace</summary>
<p>
Pretty sure this isn't relevant, as the panic is from an `unwrap()` in my code because of an error value created in `std`. But here you go:

```
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/efec545293b9263be9edfb283a7aa66350b3acbf\/library\std\src\panicking.rs:498
   1: core::panicking::panic_fmt
             at /rustc/efec545293b9263be9edfb283a7aa66350b3acbf\/library\core\src\panicking.rs:107
   2: core::result::unwrap_failed
             at /rustc/efec545293b9263be9edfb283a7aa66350b3acbf\/library\core\src\result.rs:1660
   3: core::result::Result<T,E>::unwrap
   4: core::ptr::const_ptr::<impl *const T>::is_null
   5: core::ops::function::FnOnce::call_once
```

</p>
</details>

### PR DESCRIPTION
**Pull request by Patrick-Poitras**
This is an attempted fix of issue #91722, where a too-small buffer was passed to the read function of stdio on Windows. This caused an error to be returned when `read_to_end` or `read_to_string` were called. Both delegate to `std::io::default_read_to_end`, which creates a buffer that is of length >0, and forwards it to `std::io::Stdin::read()`. The latter method returns an error if the length of the buffer is less than 4, as there might not be enough space to allocate a UTF-16 character. This creates a problem when the buffer length is in `0 < N < 4`, causing the bug. 

The current modification creates an internal buffer, much like the one used for the write functions

I'd also like to acknowledge the help of @agausmann and @hkratz in detecting and isolating the bug, and for suggestions that made the fix possible. 

Couple disclaimers:

- Firstly, I didn't know where to put code to replicate the bug found in the issue. It would probably be wise to add that case to the testing suite, but I'm afraid that I don't know _where_ that test should be added.
- Secondly, the code is fairly fundamental to IO operations, so my fears are that this may cause some undesired side effects ~or performance loss in benchmarks.~ The testing suite runs on my computer, and it does fix the issue noted in #91722.
- Thirdly, I left the "surrogate" field in the Stdin struct, but from a cursory glance, it seems to be serving the same purpose for other functions. Perhaps merging the two would be appropriate.

Finally, this is my first pull request to the rust language, and as such some things may be weird/unidiomatic/plain out bad. If there are any obvious improvements I could do to the code, or any other suggestions, I would appreciate them.

Edit: Closes #91722

### CODE REVIEW

File: library/std/src/sys/windows/stdio.rs [hunk 1]
```diff
@@ -29,6 +31,32 @@ struct IncompleteUtf8 {
...
+            let new_len = self.len - (buf.len() as u8);
+            let mut new_bytes: [u8; 4] = [0; 4];
+            for (ind, val) in self.bytes[to_write..].iter().enumerate() {
+                new_bytes[ind] = *val;
+            }
+            self.bytes = new_bytes;
+            self.len = new_len;
+        } else {
+            self.len = 0;
+        }
```
Comment (agausmann) [inline library/std/src/sys/windows/stdio.rs:54]: This section can probably be simplified using [`[T]::copy_within`](https://doc.rust-lang.org/stable/std/primitive.slice.html#method.copy_within)

Comment (agausmann) [reply library/std/src/sys/windows/stdio.rs:54]: E.g.:
```rust
self.buf.copy_within(to_write.., 0)
```

File: library/std/src/sys/windows/stdio.rs [hunk 2]
```diff
@@ -29,6 +31,32 @@ struct IncompleteUtf8 {
...
 }
 
+impl IncompleteUtf8 {
+    // Implemented for use in Stdin::read.
+    fn read(&mut self, buf: &mut [u8]) -> usize {
+        // Write to buffer until the buffer is full or we run out of bytes.
+        let to_write = cmp::min(buf.len(), self.len as usize);
+        for (ind, val) in self.bytes[..to_write].iter().enumerate() {
+            buf[ind] = *val;
+        }
```
Comment (agausmann) [inline library/std/src/sys/windows/stdio.rs:41]: This can also be simplified using [`copy_from_slice`](https://doc.rust-lang.org/stable/std/primitive.slice.html#method.copy_from_slice
):

```rust
buf[..to_write].copy_from_slice(&self.bytes[..to_write])
```

**Comment by pitdicker** [comment]
I am not sure if there really is a bug here. Please see https://github.com/rust-lang/rust/pull/58454 for a bit of history.

See this comment as a note for the reviewer, I currently don't have the time to form a real opinion.

**Comment by Patrick-Poitras** [comment]
@agausmann I've made the two changes you requested above. Thanks so much! 

On a sidenote, I'm trying to write a test that replicates the behavior, but I think the code is going around any sort of testing by checking if console mode is enabled. This is probably why automated testing didn't catch it before. (They're all probably using pipes, or not console mode)

**Comment by agausmann** [comment]
@pitdicker 
> I am not sure if there really is a bug here. 

The current behavior makes `read_to_string` and `read_to_vec` non-portable in a non-intuitive and undocumented way - they have unreliable behavior in Windows console environments and will return an error for very specific forms of input (though not that uncommon) that would be fine on other platforms.

And I agree about what was said in https://github.com/rust-lang/rust/issues/91722#issuecomment-991032742 about windows stdio - it ought to be liberal in what it accepts, specifically it should be able to handle all buffer sizes:
> The `io::Read` implementation for `Stdin` should conform to the behavior specified in the [documentation of the Read trait](https://doc.rust-lang.org/std/io/trait.Read.html#tymethod.read). Essentially calling `read()` with a buf of 0 < length < 4 should work and return (at least) `Ok(1)` with one byte of the UTF-8 sequence if EOF has not been reached.

**Comment by Patrick-Poitras** [comment]
I agree that we should conform to the specifications of the Read function. 

I've also changed this from a draft to an open pull request, after doing enough manual testing that I've convinced myself that the behavior is correct. I've still been unable to find where in the code this path gets tested, or an alternative method for testing it. 

I've removed the request for a benchmark from the main post. Piped-in IO short circuits the modified of the code so I don't see this being a problem that would bench unfavorably on non-console mode path. The console mode path would only be slowed down if the length is less than 4, which currently returns an error, so I believe that that covers any potential performance decreases.

**Comment by agausmann** [comment]
> but I think the code is going around any sort of testing by checking if console mode is enabled

Yeah, this section of code is only used when the I/O device is a handle to a Windows ["console"](https://docs.microsoft.com/en-us/windows/console/consoles). I don't know much about this, but as I understand it, Rust converts the programmer's (UTF-8) sequence of bytes to/from a UTF-16 buffer which is needed by the low-level `ReadConsole`/`WriteConsole` calls.

 It seems like there has been difficulty making automated tests for this in the past - e.g. in #58454, they say they "did some _manual_ testing of reading and writing to console" (emphasis mine).

It may be possible to build a test harness for Windows consoles using [pseudoconsoles](https://docs.microsoft.com/en-us/windows/console/pseudoconsoles)? That probably deserves its own issue, but I think it is worth looking into.

**Review by Mark-Simulacrum — CHANGES_REQUESTED** [review]
Overall looks okay -- left a couple small comments to clean the code up a little.

Test-wise I suspect a run-pass test which looks something like https://github.com/rust-lang/rust/blob/master/src/test/ui/issues/issue-13304.rs might work well, though there's not currently access to raw stdin. Maybe we can expose a doc(hidden) and unstable helper to get access to the raw stdin to test it...

**Comment by ChrisDenton** [comment]
> Maybe we can expose a doc(hidden) and unstable helper to get access to the raw stdin to test it...

You can get the Windows console input handle by opening the special device `\\.\CONIN$`. See [CreateFileW#Consoles](https://docs.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-createfilew#consoles)

File: library/std/src/sys/windows/stdio.rs [hunk 3]
```diff
@@ -221,24 +242,48 @@ impl io::Read for Stdin {
...
-        let mut utf16_buf = [0u16; MAX_BUFFER_SIZE / 2];
-        // In the worst case, a UTF-8 string can take 3 bytes for every `u16` of a UTF-16. So
-        // we can read at most a third of `buf.len()` chars and uphold the guarantee no data gets
-        // lost.
-        let amount = cmp::min(buf.len() / 3, utf16_buf.len());
-        let read = read_u16s_fixup_surrogates(handle, &mut utf16_buf, amount, &mut self.surrogate)?;
+        // If there are bytes in the incomplete utf-8, start with those.
+        if self.incomplete_utf8.len > 0 {
+            bytes_copied += self.incomplete_utf8.read(buf);
+            buf_len -= bytes_copied;
```
[the remark this answers is not in the document]
Comment (Patrick-Poitras) [reply library/std/src/sys/windows/stdio.rs:251]: Once I made this change and the one with the self.incomplete_utf8.len, it allowed for further simplification into 

```rust
// If there are bytes in the incomplete utf-8, start with those.
// (No-op if there is nothing in the buffer.)
let mut bytes_copied = self.incomplete_utf8.read(buf);
```

File: library/std/src/sys/windows/stdio.rs [hunk 4]
```diff
@@ -221,24 +242,39 @@ impl io::Read for Stdin {
...
-                io::ErrorKind::InvalidInput,
-                &"Windows stdin in console mode does not support a buffer too small to \
-                 guarantee holding one arbitrary UTF-8 character (4 bytes)",
-            ));
+        // If there are bytes in the incomplete utf-8, start with those.
+        // (No-op if there is nothing in the buffer.)
+        let mut bytes_copied = self.incomplete_utf8.read(buf);
+
+        if bytes_copied == buf.len() {
+            return Ok(bytes_copied);
```
Comment (Mark-Simulacrum) [inline library/std/src/sys/windows/stdio.rs:250]: nit: can avoid the return keywords

**Comment by Mark-Simulacrum** [comment]
Please squash commits, and one more nit -- then we can move ahead.

> > Maybe we can expose a doc(hidden) and unstable helper to get access to the raw stdin to test it...
> 
> You can get the Windows console input handle by opening the special device `\\.\CONIN$`. See [CreateFileW#Consoles](https://docs.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-createfilew#consoles)

This'll be a good start to getting the stdin for the child process right, thanks!

We will need the raw wrapper provided by std, in a UI test or similar, which means externally from std so need something ~public. I can help out directly with plumbing the bits of std out if that would be helpful, or provide some additional instructions beyond what I previously said.

**Comment by Patrick-Poitras** [comment]
@Mark-Simulacrum All done!

**Comment by Mark-Simulacrum** [comment]
Alright. I'll try to throw together a UI test skeleton and push it up in the next few days, though I don't have easy access to a windows machine to test on right now.

Thanks!

**Comment by Mark-Simulacrum** [comment]
@ChrisDenton hm, is there a way to write to that windows console input so we can read to it from the child? My rough assumption is that this isn't necessarily the same as regular stdin for processes spawned through std::process, but maybe I'm wrong about that?

It's fairly easy to imagine exposing the read impl so we can directly test this, but to make that work well we'd need to manufacture a console handle with information to read from, which I'm not sure how to do.

FWIW, I'd be okay moving ahead here if we could verify manually that this works, even if a UI test is difficult to pull together.

**Comment by ChrisDenton** [comment]
Hm... well you can use [WriteConsoleInput](https://docs.microsoft.com/en-us/windows/console/writeconsoleinput) but it's a fairy involved API (you have to create each key event). It's also soft deprecated, but it should continue to work on a local console that's not in a restricted security context.

**Comment by Patrick-Poitras** [comment]
> FWIW, I'd be okay moving ahead here if we could verify manually that this works, even if a UI test is difficult to pull together.

I`ve also had a really hard time trying to make a test.

For the manual testing, I have manually confirmed that this works with repeated enters, random keyboard typing, weird characters in UTF-8 and UTF-16, and a series of random non-renderable unicode characters. All of the tests showed 100% byte-per-byte matching the input. No crashing/panics was observed, even with egregious nonsense being done.

**Comment by Mark-Simulacrum** [comment]
@Patrick-Poitras Is that testing the raw API being modified here? Or the regular io::stdin, which buffers it with BufReader?

> Hm... well you can use WriteConsoleInput but it's a fairy involved API (you have to create each key event). It's also soft deprecated, but it should continue to work on a local console that's not in a restricted security context.

Hm. Yeah, OK. Let's try to confirm functionality through manual testing of this, but not try to write a runnable test, then.

**Comment by Patrick-Poitras** [comment]
I did testing in-situ, using console mode in powershell and cmd. It was that way that the bug was found, so explicitly calling it through console mode. Another possibility for testing would be to write a flag that disables the console mode workaround, idk if that's permitted.

**Comment by Patrick-Poitras** [comment]
@Mark-Simulacrum Do you need me to do anything else before we get this rolling?

**Comment by Patrick-Poitras** [comment]
@matthiaskrgr Same runner on apple timed out. I checked the output while it was running and it was the last build remaining about 3 hours ago. The apple build is running significantly slower than other builds for no apparent reason. (Also this change is Windows-only, so unless something weird is happening, I don't think it's got anything to do with this PR)
