### PR TITLE
gvn: avoid creating overlapping assignments

### LINKED ISSUE #141038: GVN misunderstands aliasing, can create overlapping assignments
Reduced example from rustlantis, which is accepted by Miri without optimizations enabled:
```rust
#![feature(custom_mir, core_intrinsics)]

use std::intrinsics::mir::*;

#[custom_mir(dialect = "runtime")]
fn fn17() {
    mir!{
        let _17: Adt;
        let _33: *mut Adt;
        let _48: u32;
        let _73: &Adt;
        {
            _17 = Adt::Some(0);
            _33 = core::ptr::addr_of_mut!(_17);
            _73 = &(*_33);
            _48 = Field(Variant((*_73), 1), 0);
            (*_33) = Adt::Some(_48);
            Return()
        }
    }
}

fn main() {
    fn17();
}

enum Adt {
    None,
    Some(u32),
}
```

If I run this under Miri with `-Zmir-enable-passes=+GVN`, I see:
```
error: Undefined Behavior: `copy_nonoverlapping` called on overlapping ranges
  --> gvn-overlapping.rs:17:13
   |
17 |             (*_33) = Adt::Some(_48);
   |             ^^^^^^^^^^^^^^^^^^^^^^^ `copy_nonoverlapping` called on overlapping ranges
   |
   = help: this indicates a bug in the program: it performed an invalid operation, and caused Undefined Behavior
   = help: see https://doc.rust-lang.org/nightly/reference/behavior-considered-undefined.html for further information
   = note: BACKTRACE:
   = note: inside `fn17` at gvn-overlapping.rs:17:13: 17:36
```

The MIR diff for GVN is:
```diff
-// MIR for `fn17` before GVN
+// MIR for `fn17` after GVN
 
 fn fn17() -> () {
     let mut _0: ();
@@ -8,11 +8,15 @@ fn fn17() -> () {
     let mut _4: &Adt;
 
     bb0: {
-        _1 = Adt::Some(const 0_u32);
+        _1 = const Adt::Some(0_u32);
         _2 = &raw mut _1;
         _4 = &(*_2);
         _3 = copy (((*_4) as variant#1).0: u32);
-        (*_2) = Adt::Some(copy _3);
+        (*_2) = copy (*_4);
         return;
     }
 }
+
+alloc1 (size: 8, align: 4) {
+    01 00 00 00 00 00 00 00                         │ ........
+}
```

### PR DESCRIPTION
**Pull request by dianqk**
Quick fix #141038, as I couldn't find a way to avoid in-place modification. I'm considering handling all `rvalue` modifications within the `visit_statement` function.

r? mir-opt

### CODE REVIEW

File: compiler/rustc_mir_transform/src/gvn.rs [hunk 1]
```diff
@@ -982,19 +984,23 @@ impl<'body, 'tcx> VnState<'body, 'tcx> {
 
         // Allow introducing places with non-constant offsets, as those are still better than
         // reconstructing an aggregate.
-        if let Some(place) = self.try_as_place(copy_from_local_value, location, true) {
-            if rvalue.ty(self.local_decls, self.tcx) == place.ty(self.local_decls, self.tcx).ty {
+        if let Some(place) = self.try_as_place(copy_from_local_value, location, true)
+            && rvalue.ty(self.local_decls, self.tcx) == place.ty(self.local_decls, self.tcx).ty
+        {
+            // Avoid creating `*a = copy (*b)`, as they might be aliases resulting in overlapping assignments.
+            if lhs.as_local().is_some() {
```
Comment (oli-obk) [inline compiler/rustc_mir_transform/src/gvn.rs:991]: leave a FIXME saying that this also avoids any kind of projection, not just derefs

**Review by oli-obk — CHANGES_REQUESTED** [review]

**Comment by Kobzol** [comment]
@rust-timer build cabbe64191d448fec04fcf2c8deb3e2029454fc7
