### PR TITLE
Fix `x.py clippy`

### LINKED ISSUE #77309: `./x.py clippy` loads two different version of core
I am used to `cargo clippy` providing many good hints in other Rust projects. However, the equivalent here (`./x.py clippy`) does not complete after around 64,000 lines of output.

The output of a single [clippy](https://github.com/rust-lang/rust/files/5294718/clippy.txt) run.

### PR DESCRIPTION
**Pull request by jyn514**
I don't think this ever worked.

Fixes https://github.com/rust-lang/rust/issues/77309. `--fix` support is a work in progress, but works for a very small subset of `libtest`. 

This works by using the host `cargo-clippy` driver; it does not use `stage0.txt` at all. To mitigate confusion from this, it gives an error if you don't have `rustc +nightly` as the default rustc in `$PATH`. Additionally, it means that bootstrap can't set `RUSTC`; this makes it no longer possible for clippy to detect the sysroot itself. Instead, bootstrap passes the sysroot to cargo.

r? @ghost

### CODE REVIEW

**Comment by jyn514** [comment]
Update: the issue is that clippy was looking at `rustc`, not `$RUSTC`. It could be fixed on the clippy side and then bootstrap wouldn't need to hack around it.

**Comment by Mark-Simulacrum** [comment]
Hm

**Comment by Mark-Simulacrum** [comment]
Hm, so I think this should be fixed in clippy. If it's using the wrong rustc this is at best a temporary patch - eventually a more serious problem than just the sysroot will arise, though I'm not entirely sure why clippy is running rustc at all.

We might also want to have x.py download clippy on demand (when running clippy) so that there's less version problems.

**Comment by jyn514** [comment]
> We might also want to have x.py download clippy on demand (when running clippy) so that there's less version problems.

This isn't a _clippy_ version issue, this is a _rustc_ version issue. Clippy runs the rustc in $PATH when it should run `$RUSTC` instead.

> I'm not entirely sure why clippy is running rustc at all.

See https://github.com/rust-lang/rust-clippy/pull/3546

> I think this should be fixed in clippy

Ok, I'll do that here (cc @flip1995). I'm going to keep the bootstrap hack for now so I don't have to build rustc/clippy from source, but this is the fix:

```diff
diff --git a/src/tools/clippy/src/driver.rs b/src/tools/clippy/src/driver.rs
index f4f2259ce..5e688d72d 100644
--- a/src/driver.rs
+++ b/src/driver.rs
@@ -323,7 +323,7 @@ pub fn main() {
                 toolchain_path(home, toolchain)
             })
             .or_else(|| {
-                Command::new("rustc")
+                Command::new(env::var("RUSTC").unwrap_or("rustc"))
                     .arg("--print")
                     .arg("sysroot")
                     .output()
```

**Comment by flip1995** [comment]
> I'm not entirely sure why clippy is running rustc at all.

Clippy needs some `sysroot`, so that `clippy-driver` can be used without `cargo` (practically just like `rustc`). Clippy tries to get the sysroot in the following order:

```rust
        // Get the sysroot, looking from most specific to this invocation to the least:
        // - command line
        // - runtime environment
        //    - SYSROOT
        //    - RUSTUP_HOME, MULTIRUST_HOME, RUSTUP_TOOLCHAIN, MULTIRUST_TOOLCHAIN
        // - sysroot from rustc in the path
        // - compile-time environment
        //    - SYSROOT
        //    - RUSTUP_HOME, MULTIRUST_HOME, RUSTUP_TOOLCHAIN, MULTIRUST_TOOLCHAIN
```

For the "`- sysroot from rustc in the path`", Clippy executes `rustc --print sysroot`. This uses the `rustc` from `PATH`, which is reasonable for most environments, but makes problems, if there are multiple `rustc` binaries that could be executed. Since this doesn't really happen in the wild, we never noticed this from the Clippy side.

**Comment by Mark-Simulacrum** [comment]
> This isn't a clippy version issue, this is a rustc version issue. Clippy runs the rustc in $PATH when it should run $RUSTC instead.

Right now, yes, there's no version issue, but stable/nightly clippy isn't guaranteed to work.

Anyway, I'm fine with merging this for now, r=me.

**Comment by jyn514** [comment]
> Anyway, I'm fine with merging this for now, r=me.

Sorry, I didn't say - this does _not_ fix `x.py clippy`, just gets it part of the way. It runs into issues while compiling libstd dependencies like `cc`:

```
error[E0463]: can't find crate for `std`
error: could not compile `cc`
```

I think it might need more of the logic in `rustdoc.rs`? @ehuss had some suggestions in https://rust-lang.zulipchat.com/#narrow/stream/246057-t-cargo/topic/Does.20cargo.20pass.20--sysroot.3F but they sounded a little tricky to implement.

**Comment by jyn514** [comment]
Ok, this is actually working now :) Giant thank you to @ehuss for all the help with bootstrap!

**Comment by jyn514** [comment]
The current error for `--fix` is

```
error[E0463]: can't find crate for `test`
 --> library/test/src/stats/tests.rs:3:1
  |
3 | extern crate test;
  | ^^^^^^^^^^^^^^^^^^ can't find crate
```

I figure that can be fixed in a follow-up, though.

File: src/bootstrap/builder.rs [hunk 1]
```diff
@@ -330,7 +330,7 @@ impl<'a> ShouldRun<'a> {
 pub enum Kind {
     Build,
     Check,
-    Clippy,
+    Clippy { fix: bool },
```
Comment (Mark-Simulacrum) [inline src/bootstrap/builder.rs:333]: This seems wrong -- nothing else puts arguments here.

File: src/bootstrap/builder.rs [hunk 2]
```diff
@@ -832,7 +832,40 @@ impl<'a> Builder<'a> {
...
+                    if output.status.success()
+                        && t!(std::str::from_utf8(&output.stdout)).contains("nightly")
+                    {
+                        Ok(output)
+                    } else {
+                        Err(())
+                    }
+                }) {
+                    eprintln!(
+                        "error: `x.py clippy` requires a nightly host `rustc` toolchain with the `clippy` component"
```
Comment (Mark-Simulacrum) [inline src/bootstrap/builder.rs:861]: This seems like the wrong recommendation. Nightly clippy is not guaranteed to work; beta clippy is much more likely to.

Comment (flip1995) [reply src/bootstrap/builder.rs:861]: Nightly Clippy is always available, since we use `git subtree` for Clippy. It may have a few more FPs, but generally it should work. Or am I misunderstanding something?

Comment (Mark-Simulacrum) [reply src/bootstrap/builder.rs:861]: Nightly clippy is always available but may not work on the rustc tree -- it's usually outdated by several PRs (at most points in the day) which means that there's a pretty high likelihood of it not understanding some library feature or failing on stabilization etc. Beta clippy, like beta rustc, is something we're much more prepared for.

Comment (jyn514) [reply src/bootstrap/builder.rs:861]: I was not able to get this to work with a beta clippy.

```
error[E0522]: definition of an unknown language item: `array`
   --> library/core/src/array/mod.rs:379:1
    |
379 | #[lang = "array"]
    | ^^^^^^^^^^^^^^^^^ definition of unknown language item `array`
... various other E0522 errors ...
error[E0118]: no base type found for inherent implementation
   --> library/core/src/array/mod.rs:380:25
    |
380 | impl<T, const N: usize> [T; N] {
    |                         ^^^^^^ impl requires a base type
error: aborting due to 20 previous errors; 53 warnings emitted
```
This is with `cfg=bootstrap`. I think it's related to not setting `core` somehow.

File: src/bootstrap/builder.rs (hunk 1 above)
Comment (jyn514) [reply src/bootstrap/builder.rs:333]: Changing this requires putting `--fix -Zunstable-options` somewhere other than `args()`. Do you have a suggestion where it should go? This needs to be passed to `clippy-driver` itself so it can't be in `fn cargo()`, maybe I could change args() to take a full `Builder`?

Comment (jyn514) [reply src/bootstrap/builder.rs]: Ok, taking a full `Builder` worked fine.

File: src/bootstrap/builder.rs (hunk 2 above)
Comment (Mark-Simulacrum) [reply src/bootstrap/builder.rs:861]: So, I am okay with us merging fixes to nightly clippy working, but I am unwilling to actually actively *recommend* nightly. I think that RUSTC getting set just needs to get fixed.

Comment (jyn514) [reply src/bootstrap/builder.rs:861]: I tried setting RUSTC to no effect, I think because there's no CLIPPY analogue to RUSTC or CLIPPY.

I'm not sure exactly what needs to happen to get beta clippy to work. Why does `x.py check` work with beta rustc when `x.py clippy` doesn't? I don't know what's going wrong.

Comment (jyn514) [reply src/bootstrap/builder.rs]: This started working after the beta bump, although I'm not sure why ... maybe I had an old version of beta or something? Anyway, I tested with both nightly and beta and it seems to be working.

**Comment by jyn514** [comment]
This is ready for review. Both the latest nightly and beta clippy work, and the error message no longer suggests installing nightly.

**Comment by jyn514** [comment]
The outstanding comments are:

- `--fix` doesn't work: https://github.com/rust-lang/rust/pull/77351#issuecomment-701893783
- We might also want to have x.py download clippy on demand (when running clippy) so that there's less version problems: https://github.com/rust-lang/rust/pull/77351#issuecomment-701071012

I think both of these can be addressed in follow-ups, they're improvements more than bugfixes. But I'm happy to work on them here if you want.

**Comment by jyn514** [comment]
`--fix` now works for everything except rustdoc. See https://rust-lang.zulipchat.com/#narrow/stream/246057-t-cargo/topic/cargo.20check.20--no-tests.3F for why rustdoc is special. Note `x.py clippy` still works on everything, just not `clippy --fix`.

**Comment by jyn514** [comment]
ping @Mark-Simulacrum

File: src/bootstrap/builder.rs [hunk 3]
```diff
@@ -850,7 +850,42 @@ impl<'a> Builder<'a> {
...
+                        .to_str()
+                        .expect("sysroot must be valid UTF-8"),
+                );
+                // Only run clippy on a very limited subset of crates (in particular, not build scripts).
+                cargo.arg("-Zunstable-options");
+                // Explicitly does *not* set `--cfg=bootstrap`, since we're using a nightly clippy.
+                let host_version = Command::new("rustc").arg("--version").output().map_err(|_| ());
+                let output = host_version.and_then(|output| {
+                    if output.status.success()
+                    {
```
Comment (Mark-Simulacrum) [inline src/bootstrap/builder.rs:871]: This brace looks like it should be on the previous line (i.e., `if ... {\n`)

File: src/bootstrap/builder.rs [hunk 4]
```diff
@@ -850,7 +850,42 @@ impl<'a> Builder<'a> {
                 cargo.args(s.split_whitespace());
             }
             rustflags.env("RUSTFLAGS_BOOTSTRAP");
-            rustflags.arg("--cfg=bootstrap");
+            if cmd == "clippy" {
+                // clippy overwrites any sysroot we pass on the command line.
```
Comment (Mark-Simulacrum) [inline src/bootstrap/builder.rs:854]: I am confused, this sysroot *is* being passed on the command line? If that gets overwritten, then what's the point?

**Review by Mark-Simulacrum — COMMENTED** [review]
I am still pretty unhappy with this additional code being added to fix this, but it's not in the critical complicated pieces of bootstrap sufficiently for me to block it.

r=me with comments resolved (they're both nit-ish so I don't feel strongly about re-reviewing unless you think that's necessary)

File: src/bootstrap/builder.rs (hunk 4 above)
Comment (jyn514) [reply src/bootstrap/builder.rs]: The comment is wrong - it gets overwritten if we pass it to _cargo_, not if we pass it to clippy.

https://github.com/rust-lang/rust-clippy/blob/a771557ee92af5e313714f127bb48a1d787a1cff/src/driver.rs#L310

**Comment by jyn514** [comment]
err

@bors r-

@bors r=Mark-Simulacrum
