### PR TITLE
Fix up autoderef when reborrowing

### LINKED ISSUE #68590: rustc loosing track of DerefMut impl on nested type
The following code should compile but doesn't. With only 9 nesting levels, I wouldn't expect to be running into deref-limits yet.

```rust
use std::ops::{Deref, DerefMut};

trait DynTrait {
    fn f(&mut self);
}

struct Base<'a> {
    dyn_trait: &'a mut dyn DynTrait,
}

macro_rules! impl_type {
    ($derived:ident, $base:ident) => {
        struct $derived<'a> {
            base: $base<'a>,
        }
        
        impl<'a> Deref for $derived<'a> {
            type Target = $base<'a>;
            fn deref(&self) -> &$base<'a> {
                &self.base
            }
        }
        
        impl<'a> DerefMut for $derived<'a> {
            fn deref_mut(&mut self) -> &mut $base<'a> {
                &mut self.base
            }
        }
    };
}

impl_type!(Level1, Base);
impl_type!(Level2, Level1);
impl_type!(Level3, Level2);
impl_type!(Level4, Level3);
impl_type!(Level5, Level4);
impl_type!(Level6, Level5);
impl_type!(Level7, Level6);
impl_type!(Level8, Level7);
impl_type!(Level9, Level8);

fn take_dyn_trait(dyn_trait: &mut dyn DynTrait) {}

fn f<'a>(value: &mut Level9<'a>) {
    // uncomment following line to make compile
    //let value: &mut Base = value;
    take_dyn_trait(value.dyn_trait);
}
```

([Playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=9b028c992c41bf07271254ab2a3cc1c6))

Errors:

```
   Compiling playground v0.0.1 (/playground)
warning: unused variable: `dyn_trait`
  --> src/lib.rs:42:19
   |
42 | fn take_dyn_trait(dyn_trait: &mut dyn DynTrait) {}
   |                   ^^^^^^^^^ help: consider prefixing with an underscore: `_dyn_trait`
   |
   = note: `#[warn(unused_variables)]` on by default

error[E0596]: cannot borrow data in a dereference of `Level1<'_>` as mutable
  --> src/lib.rs:47:20
   |
47 |     take_dyn_trait(value.dyn_trait);
   |                    ^^^^^^^^^^^^^^^ cannot borrow as mutable
   |
   = help: trait `DerefMut` is required to modify through a dereference, but it is not implemented for `Level1<'_>`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0596`.
error: could not compile `playground`.

To learn more, run the command again with --verbose.

```

### LINKED ISSUE #72225: Confusing diagnostics when calling FnMut through DerefMut.
The following code 

```Rust
struct A {
    x: Box<dyn FnMut()>
}

fn test(a: &std::sync::Mutex<A>) {
    let mut guard = a.lock().unwrap();
    // This works: (&mut guard.x)();
    (guard.x)();
}
```

produces the following error

```
error[E0596]: cannot borrow data in a dereference of `std::sync::MutexGuard<'_, A>` as mutable
 --> src/lib.rs:7:5
  |
7 |     (guard.x)();
  |     ^^^^^^^^^ cannot borrow as mutable
  |
  = help: trait `DerefMut` is required to modify through a dereference, but it is not implemented for `std::sync::MutexGuard<'_, A>`
```

The help message is especially confusing, since `DerefMut` is clearly implemeneted for `std::sync::MutexGuard<'_, A>`. This might be related to #68590.

### PR DESCRIPTION
**Pull request by nbdd0121**
Currently `(f)()` and `f.call_mut()` behaves differently if expression `f` contains autoderef in it. This causes a weird error in #72225.

When `f` is type checked, `Deref` is used (this is expected as we can't yet determine if we should use `Fn` or `FnMut`). When subsequently we determine the actual trait to be used, when using the `f.call_mut()` syntax the `Deref` is patched to `DerefMut`, while for the `(f)()` syntax case it is not.

This PR replicates the fixup for the first case.

Fixes #72225
Fixes #68590

### CODE REVIEW

**Comment by nbdd0121** [comment]
It ended up that #68590 is caused by a similar issue. When a mutable reborrow happens, it is equivalent to `&mut *expr`, thus `expr` is ought to be typechecked with needs = `Needs::MutPlace`. The typechecker does not know this beforehand, so what we should do is to fix it up later with a similar method.

File: src/librustc_typeck/check/coercion.rs [hunk 1]
```diff
@@ -94,7 +94,22 @@ impl<'a, 'tcx> Deref for Coerce<'a, 'tcx> {
...
 
-type CoerceResult<'tcx> = InferResult<'tcx, (Vec<Adjustment<'tcx>>, Ty<'tcx>)>;
+struct CoerceOk<'tcx> {
+    adjustments: Vec<Adjustment<'tcx>>,
+    target: Ty<'tcx>,
+    /// Whether a mutable reborrow has happened during the coercion.
+    ///
+    /// When mutable reborrow happens, it is equivalent to `&mut *expr`, thus
+    /// `expr` is ought to be typechecked with needs = [`Needs::MutPlace`].
+    /// However in many cases it might not be checked this way origianlly. This
```
Comment (nikomatsakis) [inline src/librustc_typeck/check/coercion.rs:104]:
```suggestion
    /// However in many cases it might not be checked this way originally. This
```

**Review by nikomatsakis — COMMENTED** [review]
Gah, ran out of time for reviews today, but here is one tiny nit =)

**Comment by nbdd0121** [comment]
> Gah, ran out of time for reviews today, but here is one tiny nit =)

BTW it is recommended to review commit by commit, as I've intentionally separated the PR into individually meaningful commits.

File: src/librustc_typeck/check/reconciliation.rs [hunk 2]
```diff
@@ -0,0 +1,148 @@
+use crate::check::{FnCtxt, Needs, PlaceOp};
+use rustc_hir as hir;
+use rustc_middle::ty::adjustment::{Adjust, Adjustment, OverloadedDeref, PointerCast};
+use rustc_middle::ty::adjustment::{AllowTwoPhase, AutoBorrow, AutoBorrowMutability};
+use rustc_middle::ty::{self, Ty};
+
+impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
+    /// Convert auto-derefs, indices, etc of an expression from `Deref` and `Index`
```
Comment (nikomatsakis) [inline src/librustc_typeck/check/reconciliation.rs:8]: it'd be nice to expand this comment *just a bit* to explain that this is often done as a second pass because of the fact that we don't know whether the result is mutable or not until later

File: src/librustc_typeck/check/coercion.rs [hunk 3]
```diff
@@ -1011,9 +1044,13 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
...
             match result {
                 Ok(ok) => {
-                    let (adjustments, target) = self.register_infer_ok_obligations(ok);
-                    self.apply_adjustments(new, adjustments);
-                    return Ok(target);
+                    let coerce = self.register_infer_ok_obligations(ok);
+                    // If mutable reborrow happens, fix up autoderef to use DerefMut
+                    if coerce.reborrow_mut {
+                        self.convert_place_derefs_to_mutable(new);
+                    }
```
Comment (nikomatsakis) [inline src/librustc_typeck/check/coercion.rs:1051]: I'm wondering whether it is possible to figure out `reborrow_mut` just by examining the adjustments? I should think "probably yes". If so, could we remove the code that is computing `reborrow_mut` and instead modify `apply_adjustments` to figure out whether `reborrow_mut` *would have been true* -- and, if so, invoking `self.convert_place_derefs_to_mutable(new)`?

If that is not possible, then I'd still like to see the field moved into the adjustments and have this code be invoked by `apply_adjustments`, instead of having coercion return three things.

Comment (nikomatsakis) [reply src/librustc_typeck/check/coercion.rs:1051]: OK, I just spent a bit of time skimming the code for calls to `apply_adjustments` -- there are quite a few that have no connection to coercion -- but it still *feels* like a better spot to me.

File: src/librustc_typeck/check/callee.rs [hunk 4]
```diff
@@ -200,21 +201,34 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
...
-                                // deployment, conservatively omit
-                                // overloaded function call ops.
-                                allow_two_phase_borrow: AllowTwoPhase::No,
-                            },
-                        };
-                        autoref = Some(Adjustment {
-                            kind: Adjust::Borrow(AutoBorrow::Ref(region, mutbl)),
-                            target: method.sig.inputs()[0],
-                        });
+                    let (region, mutbl) = if let ty::Ref(r, _, mutbl) = method.sig.inputs()[0].kind
```
Comment (nikomatsakis) [inline src/librustc_typeck/check/callee.rs:204]: Comment:

// Check for `&self` vs `&mut self` in the method signature. Since this is either the `Fn` or `FnMut` trait, it should be one of those.

Took me longer than I care to admit to understand why that `span_bug` was valid ;)

File: src/librustc_typeck/check/coercion.rs (hunk 3 above)
Comment (nikomatsakis) [reply src/librustc_typeck/check/coercion.rs:1051]: But at least based on an *initial* read, this refactoring would likely subsume some of the earlier commits as well, no?

**Review by nikomatsakis — CHANGES_REQUESTED** [review]
What do you think of this refactoring idea I describe below?

**Comment by nikomatsakis** [comment]
@nbdd0121 Apologies for the slow review. Took me a bit to grok this PR. I'll try to be snappier from now on (I've gotten on top of my backlog)

File: src/librustc_typeck/check/coercion.rs (hunk 3 above)
Comment (nbdd0121) [reply src/librustc_typeck/check/coercion.rs:1051]: I think it's a good idea. I'll go through all callers to see if that's doable.

**Comment by nbdd0121** [comment]
I checked all callers of `apply_adjustments` and nothing seems problematic to me if we move the logic to `apply_adjustments`.

I also checked all construction of `Adjust::Borrow`:
* check/method/confirm.rs, check/callee.rs, check/coercion perform mutable reborrows that require fixups, so good.
* check/op.rs (LHS of op assign), check/expr.rs (unary deref), check/mod.rs (index step) can perform mutable reborrows, but the places are type checked with `Needs::MutPlace` already so we would be doing wasteful work trying to fix them again (will do be some further method resolutions that ends up as a no-op).

To avoid wasteful call into `convert_place_derefs_to_mutable`, we could just add additional argument to `apply_adjustments` to indicate if such a check is needed.

Alternatively, we can modify these three places to use `Needs::None` instead of `Needs::MutPlace` to save a little bit time when they do the the first pass, and have `apply_adjustments` fix them up to use mutable variants. Doing so have the benefit that all mutable reborrows are now handled in one single place, and we wouldn't have to worry about related bugs because `apply_adjustments` just magically have all Deref/Index mutability issues handled.

What do you think? @nikomatsakis

**Comment by nbdd0121** [comment]
Refactoring idea:
We might as well just remove all `Needs`, and typecheck all expressions with `Needs::None`. If an expression is used in assignment/mutable binding/(auto) borrow then use the fixup logic. This has an advantage that only one set of logic will lead to DerefMut/IndexMut and we don't need to pass `Needs` around anymore.

**Comment by nikomatsakis** [comment]
@nbdd0121 remind me, the `Needs` logic is the "top-down" logic that lets us first check things with mutable mode when it is "syntactically obvious"? (e.g., `&mut foo.bar`)

If so, I have indeed contemplating removing it and relying solely on the "fixup" path that we need to have anyway.

**Comment by nikomatsakis** [comment]
Regarding your other comments, I would prefer to not have an additional argument indicating whether the fixup is needed unless we have evidence that it's a performance hazard, just because I think it's better to keep things simple. If we can refactor away `Needs` altogether, so much the better!

**Comment by nbdd0121** [comment]
> @nbdd0121 remind me, the `Needs` logic is the "top-down" logic that lets us first check things with mutable mode when it is "syntactically obvious"? (e.g., `&mut foo.bar`)
> 
> If so, I have indeed contemplating removing it and relying solely on the "fixup" path that we need to have anyway.

Yes, `Needs` is top down. I am working on the refactoring right now, and we can do a try build and rust-timer queue to make sure nothing breaks and performance does not regress.

**Comment by nikomatsakis** [comment]
@nbdd0121 btw please leave a comment when it's ready for re-review / perf run

**Comment by nbdd0121** [comment]
It's ready.

File: src/librustc_typeck/check/place_op.rs [hunk 5]
```diff
@@ -0,0 +1,334 @@
...
+use rustc_infer::infer::type_variable::{TypeVariableOrigin, TypeVariableOriginKind};
+use rustc_infer::infer::InferOk;
+use rustc_middle::ty::adjustment::{Adjust, Adjustment, OverloadedDeref, PointerCast};
+use rustc_middle::ty::adjustment::{AllowTwoPhase, AutoBorrow, AutoBorrowMutability};
+use rustc_middle::ty::{self, Ty};
+use rustc_span::symbol::{sym, Ident};
+use rustc_span::Span;
+
+impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
+    pub(super) fn lookup_derefing(
```
Comment (nikomatsakis) [inline src/librustc_typeck/check/place_op.rs:14]: Pre-existing problem I know, but a comment would be nice -- what are these arguments? When is this called?

File: src/librustc_typeck/check/place_op.rs [hunk 6]
```diff
@@ -0,0 +1,334 @@
...
+            );
+        } else {
+            span_bug!(expr.span, "input to deref is not a ref?");
+        }
+        let ty = self.make_overloaded_place_return_type(method).ty;
+        self.write_method_call(expr.hir_id, method);
+        Some(ty)
+    }
+
+    pub(super) fn lookup_indexing(
```
Comment (nikomatsakis) [inline src/librustc_typeck/check/place_op.rs:42]: Same as above

**Review by nikomatsakis — APPROVED** [review]
Gave it a quick skim, seems like a massive simplification, but I want to re-review when considering the full PR -- I feel like I'm missing something, maybe it's almost too easy now. ;) Anyway let's look at the perf results.

**Comment by nikomatsakis** [comment]
OK, perf looks neutral, that's good.

File: src/librustc_typeck/check/mod.rs [hunk 7]
```diff
@@ -3211,6 +3218,14 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
                 *entry.get_mut() = adj;
             }
         }
+
+        // When there is an auto mutable borrow, it is equivalent to `&mut expr`,
+        // thus `expr` is ought to be typechecked with needs = [`Needs::MutPlace`].
+        // However in many cases it might not be checked this way originally, e.g.
+        // the receiver of a method call. We need to fix them up.
```
Comment (nikomatsakis) [inline src/librustc_typeck/check/mod.rs:3225]: This comments feels kinda sorta out of date? I guess `Needs` is still a thing, so never mind. But still, maybe we can say:

If there is an auto-mutable borrow, this is equivalent to adding `&mut <expr>`. This in turn may mean that some of the `Deref` or `Index` impls that appear in `<expr>` need to be rewritten to `DerefMut` or `IndexMut`. So go and fix those up.

**Review by nikomatsakis — CHANGES_REQUESTED** [review]
This looks great! I left a few comment nits (here, and in my [previous review](https://github.com/rust-lang/rust/pull/72280#pullrequestreview-431380180)), but r=me once those are satisfied!

**Review by nikomatsakis — APPROVED** [review]
