### PR TITLE
Verify that all crate sources are in sync

### LINKED ISSUE #114: Pitfall: some crates bork `bevy/dynamic`
Pulling in certain dependencies into your bevy project can cause dynamic linking with the `bevy/dynamic` feature to stop working when it previously was working.

Original discord thread https://discord.com/channels/691052431525675048/935350255321493566

Currently the only crate I know of with this problem is `hyper` (`reqwest` is probably the more common dependency that unsuspecting users will pull in). For this particular problem, you could recommend users to select a different http library that doesn't depend on `hyper`: https://lib.rs/web-programming/http-client

All signs point to a bug in rustc or cargo. It seems that this might be the cause of the issue: https://github.com/rust-lang/rust/issues/82151#issuecomment-779368017

Related links:
* https://github.com/rust-lang/rust/issues/82972
* https://github.com/rust-lang/rust/issues/82151
* https://github.com/alexkornitzer/hyper/commit/119904864b3dc91d77cf443af11f697821759336
* https://github.com/BGR360/brine/commit/fcc0b0b84cc26b87f44e4baf636c16c93afdcce3

### LINKED ISSUE #10786: Rustc does not warn when .so/.rlib files are not in sync
Right now the logic for reading metadata for a crate is to read it the first time the crate's dylib or rlib file is found. On the second file that's found, the metadata isn't read at all because metadata reading is one of the known slow portions of the compiler.

This implies that if an rlib file is regenerated, but the dylib isn't, then the two are out of sync and rustc will read the old metadata from the dylib and link to the rlib, resulting in linker errors.

I don't want to slow down rustc by reading metadata from all rlibs _and_ dylibs, but this situation is far less than optimal. Perhaps this is a job for a rustpkg-like tool?

### LINKED ISSUE #82151: `undefined reference to` linker error when using dylibs
When including `mongodb` (2.0.0-alpha) into a dylib'd crate that is included in an application, the linker is failing to resolve all references. It is fine when using `mongodb` (1.0) which makes me think this is something that tokio 1.0 is bringing to light.

This seems similar to #67276 except the workarounds it suggested at the time do not work.

### Code
Due to the nature of this making a truly small example is quite challenging, I assume isolating tokio 1.2 out might work? But anyway for now, an repo for the example is here:

https://github.com/alexkornitzer/dylib-errors/tree/error/mongodb

### Meta

`rustc --version --verbose`:
```
rustc 1.50.0 (cb75ad5db 2021-02-10)
binary: rustc
commit-hash: cb75ad5db02783e8b0222fee363c5f63f7e2cf5b
commit-date: 2021-02-10
host: x86_64-unknown-linux-gnu
release: 1.50.0
```

### Error output

<details>

<summary>Click to see (large) error output</summary>

```
error: linking with `cc` failed: exit code: 1
  |
  = note: "cc" "-Wl,--as-needed" "-Wl,-z,noexecstack" "-m64" "-Wl,--eh-frame-hdr" "-L" "/home/alex/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "/tmp/dylib-errors/target/debug/deps/serverctl-075ec1ba25a9db57.1itguawvaqi4tz09.rcgu.o" "/tmp/dylib-errors/target/debug/deps/serverctl-075ec1ba25a9db57.2e2vi1eic3cq1uv0.rcgu.o" "/tmp/dylib-errors/target/debug/deps/serverctl-075ec1ba25a9db57.2xnsa9e8fo0f3vfx.rcgu.o" "/tmp/dylib-errors/target/debug/deps/serverctl-075ec1ba25a9db57.381d3dpcz550aiga.rcgu.o" "/tmp/dylib-errors/target/debug/deps/serverctl-075ec1ba25a9db57.439rmo5cmtvxqijq.rcgu.o" "/tmp/dylib-errors/target/debug/deps/serverctl-075ec1ba25a9db57.m2w4nr06rairzye.rcgu.o" "-o" "/tmp/dylib-errors/target/debug/deps/serverctl-075ec1ba25a9db57" "-Wl,--gc-sections" "-pie" "-Wl,-zrelro" "-Wl,-znow" "-nodefaultlibs" "-L" "/tmp/dylib-errors/target/debug/deps" "-L" "/tmp/dylib-errors/target/debug/build/nng-sys-f3e266d23dd4e472/out/lib" "-L" "/tmp/dylib-errors/target/debug/build/nng-sys-f3e266d23dd4e472/out/lib64" "-L" "/tmp/dylib-errors/target/debug/build/ring-bb20fb99fa6aa7fb/out" "-L" "/home/alex/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-L" "/tmp/dylib-errors/target/debug/deps" "-lshared" "-L" "/tmp/dylib-errors/target/debug/deps" "-lhyper-76617ad6dff947a6" "-Wl,-Bstatic" "/tmp/dylib-errors/target/debug/deps/libenv_logger-a71078fee9c4b7c4.rlib" "/tmp/dylib-errors/target/debug/deps/libtermcolor-a5f039500e7d00fb.rlib" "/tmp/dylib-errors/target/debug/deps/libatty-19a75323732422a2.rlib" "/tmp/dylib-errors/target/debug/deps/libhumantime-96e834ce26cdaa11.rlib" "/tmp/dylib-errors/target/debug/deps/libregex-9283b86347eb36d1.rlib" "/tmp/dylib-errors/target/debug/deps/libthread_local-a7feb37262151fce.rlib" "/tmp/dylib-errors/target/debug/deps/libregex_syntax-a1379624b565cc38.rlib" "/tmp/dylib-errors/target/debug/deps/libaho_corasick-6617b386ca598d8a.rlib" "-Wl,--start-group" "-L" "/home/alex/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-Wl,-Bdynamic" "-lstd-6f77337c1826707d" "-Wl,--end-group" "-Wl,-Bstatic" "/home/alex/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcompiler_builtins-d36087076e1dd756.rlib" "-Wl,-Bdynamic" "-lgcc_s" "-lutil" "-lrt" "-lpthread" "-lm" "-ldl" "-lc"
  = note: /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `<hyper::proto::h2::client::ClientTask<B> as core::future::future::Future>::poll::CALLSITE'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `core::ptr::drop_in_place'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `hyper::headers::set_content_length_if_missing'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `hyper::error::Error::new_body_write_aborted'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `core::ptr::drop_in_place'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `hyper::body::body::Body::h2'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `hyper::proto::h1::conn::Conn<I,B,T>::poll_read_head::CALLSITE'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `hyper::proto::h1::role::parse_headers::CALLSITE'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `hyper::proto::h1::conn::Conn<I,B,T>::poll_shutdown::CALLSITE'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `core::ptr::drop_in_place'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `<hyper::client::pool::Checkout<T> as core::ops::drop::Drop>::drop::CALLSITE'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `hyper::error::Error::new_closed'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `alloc::vec::Vec<T>::with_capacity'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `hyper::client::pool::Expiration::expires'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `core::ptr::drop_in_place'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `core::option::Option<T>::is_some'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `<hashbrown::raw::RawIterHash<T> as core::iter::traits::iterator::Iterator>::next'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `<hyper::client::connect::http::ConnectError as core::fmt::Display>::fmt'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `hyper::client::connect::http::get_host_port'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `core::ptr::drop_in_place'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `core::ptr::drop_in_place'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `core::ptr::drop_in_place'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `hyper::error::Error::new_user_unsupported_request_method'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `hyper::proto::h1::dispatch::Dispatcher<D,Bs,I,T>::poll_write::CALLSITE'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `alloc::alloc::box_free'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `hyper::error::Error::new'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `hyper::proto::h1::io::ReadStrategy::next'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `<core::option::Option<T> as core::clone::Clone>::clone'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `core::result::Result<T,E>::expect'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `hyper::client::client::Client<C,B>::send_request::{{closure}}::CALLSITE'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `<core::result::Result<T,E> as core::ops::try::Try>::into_result'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `<hyper::proto::h2::PipeToSendStream<S> as core::future::future::Future>::poll::CALLSITE'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `hyper::proto::h1::encode::Encoder::encode::CALLSITE'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `core::any::TypeId::of'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `core::option::Option<T>::take'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `core::ptr::drop_in_place'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `hyper::client::pool::Pool<T>::reuse::CALLSITE'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `<hyper::body::length::DecodedLength as core::fmt::Display>::fmt'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `futures_channel::lock::Lock<T>::new'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `hyper::client::client::origin_form'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `<hyper::error::Error as core::fmt::Display>::fmt'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `hyper::client::pool::IdlePopper<T>::pop::CALLSITE'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `hyper::proto::h1::decode::Decoder::decode::CALLSITE'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `core::ptr::drop_in_place'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `hyper::proto::h1::conn::Conn<I,B,T>::maybe_notify::CALLSITE'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `hyper::client::client::Builder::pool_max_idle_per_host'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `http::header::map::HeaderMap<T>::len'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `<hyper::proto::h1::dispatch::Client<B> as hyper::proto::h1::dispatch::Dispatch>::poll_msg::CALLSITE'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `hashbrown::raw::Bucket<T>::as_ref'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `hashbrown::raw::calculate_layout'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `<hyper::proto::h2::PipeToSendStream<S> as core::future::future::Future>::poll::CALLSITE'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `hyper::proto::h1::io::Buffered<T,B>::poll_flush_flattened::CALLSITE'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `core::ptr::drop_in_place'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `core::ptr::drop_in_place'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `hyper::proto::h1::conn::State::is_read_closed'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `hyper::error::Error::with'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `<hyper::client::connect::http::ConnectError as std::error::Error>::source'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `alloc::sync::Arc<T>::inner'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `hyper::client::conn::Builder::handshake::{{closure}}::CALLSITE'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `hyper::error::Error::with'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `<hyper::body::body::Body as http_body::Body>::size_hint'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `hyper::client::connect::http::HttpInfo::remote_addr'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `hashbrown::raw::Bucket<T>::from_base_index'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `hyper::error::Error::new_unexpected_message'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `alloc::sync::Arc<T>::new'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `http::response::Response<T>::extensions_mut'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `hyper::proto::h1::conn::Conn<I,B,T>::poll_read_body::CALLSITE'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `hyper::client::pool::PoolInner<T>::put::CALLSITE'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `hyper::client::connect::http::ConnectingTcp::new'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `core::fmt::ArgumentV1::new'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `hyper::proto::h2::ping::Recorder::ensure_not_timed_out'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `<core::result::Result<T,E> as core::ops::try::Try>::from_error'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `<dyn core::any::Any>::is'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `core::result::Result<T,E>::ok'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `hyper::client::connect::Connected::negotiated_h2'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `hyper::proto::h1::conn::Conn<I,B,T>::poll_read_head::CALLSITE'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `<futures_channel::lock::TryLock<T> as core::ops::deref::DerefMut>::deref_mut'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `<hashbrown::raw::RawIter<T> as core::iter::traits::iterator::Iterator>::next'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `hyper::proto::h1::role::encode_headers::CALLSITE'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `hyper::proto::h1::conn::Conn<I,B,T>::poll_read_body::CALLSITE'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `hyper::client::client::Client<C,B>::connect_to::{{closure}}::{{closure}}::{{closure}}::CALLSITE'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `alloc::sync::Arc<T>::from_inner'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `hyper::proto::h2::ping::Config::is_enabled'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `<h2::share::SendStream<hyper::proto::h2::SendBuf<B>> as hyper::proto::h2::SendStreamExt>::on_user_err::CALLSITE'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `std::sync::mutex::Mutex<T>::new'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `hashbrown::raw::Bucket<T>::as_ptr'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `core::ptr::drop_in_place'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `hyper::proto::h1::dispatch::Dispatcher<D,Bs,I,T>::poll_read_head::CALLSITE'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `<alloc::sync::Arc<T> as core::clone::Clone>::clone'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `<hyper::body::body::Body as http_body::Body>::poll_data'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `core::ptr::drop_in_place'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `futures_channel::lock::Lock<T>::try_lock'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `hyper::proto::h1::io::Buffered<T,B>::parse::CALLSITE'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `hyper::client::connect::dns::Name::new'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `hyper::client::connect::http::HttpConnector::new'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `hyper::proto::h1::dispatch::Dispatcher<D,Bs,I,T>::poll_read_head::CALLSITE'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `hyper::client::client::extract_domain'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `core::ptr::drop_in_place'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `hyper::body::body::Sender::poll_ready'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `hashbrown::raw::Bucket<T>::drop'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `hyper::proto::h1::conn::Conn<I,B,T>::require_empty_read::CALLSITE'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `hyper::proto::h1::Wants::add'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `core::ptr::read'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `core::ptr::drop_in_place'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `hyper::proto::h1::conn::State::close_write'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `hyper::headers::connection_keep_alive'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `core::option::Option<T>::as_ref'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `hyper::error::Error::new_canceled'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `core::option::Option<T>::take'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `hyper::proto::h1::conn::State::is_idle'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `hyper::error::Error::new_shutdown'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `<std::collections::hash::map::HashMap<K,V,S> as core::default::Default>::default'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `core::ptr::drop_in_place'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `<hyper::proto::h1::decode::Kind as core::fmt::Debug>::fmt'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `core::ptr::drop_in_place'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `core::ptr::drop_in_place'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `core::ptr::drop_in_place'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `<hyper::client::conn::Proto as core::fmt::Debug>::fmt'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `hyper::proto::h1::conn::State::disable_keep_alive'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `hyper::proto::h2::client::handshake::{{closure}}::{{closure}}::CALLSITE'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `tokio::sync::oneshot::Sender<T>::send'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `hyper::error::Error::new_h2'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `<T as core::convert::Into<U>>::into'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `hyper::proto::h1::conn::Conn<I,B,T>::maybe_notify::CALLSITE'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `<hyper::client::connect::http::ConnectError as core::fmt::Debug>::fmt'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `http::header::map::HeaderMap<T>::remove'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `hyper::proto::h1::decode::ChunkedState::read_body::CALLSITE'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `http::uri::builder::Builder::authority'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `hyper::proto::h1::encode::Encoder::is_close_delimited'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `hyper::proto::h1::conn::Conn<I,B,T>::poll_read_body::CALLSITE'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `hyper::proto::h1::conn::Conn<I,B,T>::force_io_read::{{closure}}::CALLSITE'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `hyper::client::connect::http::ConnectingTcpRemote::connect'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `<hyper::client::client::ResponseFuture as core::future::future::Future>::poll'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `hyper::proto::h1::decode::ChunkedState::read_trailer::CALLSITE'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `hyper::client::pool::PoolInner<T>::put::CALLSITE'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `core::ptr::drop_in_place'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `futures_channel::mpsc::queue::Queue<T>::pop_spin'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `<core::task::poll::Poll<core::result::Result<T,E>> as core::ops::try::Try>::into_result'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `core::option::Option<T>::take'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `<hyper::body::body::Body as http_body::Body>::is_end_stream'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `hyper::proto::h1::conn::State::prepare_upgrade'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `core::ptr::drop_in_place'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `hyper::proto::h1::conn::Conn<I,B,T>::poll_shutdown::CALLSITE'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `hyper::proto::h1::conn::State::is_write_closed'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `core::fmt::ArgumentV1::new'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `<hyper::proto::h1::role::Client as hyper::proto::h1::Http1Transaction>::parse'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `core::ptr::drop_in_place'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `hyper::client::conn::Http2SendRequest<B>::send_request_retryable::CALLSITE'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `hyper::body::body::Sender::send_error'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `hyper::proto::h1::io::ReadStrategy::record'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `hyper::body::body::Body::delayed_eof'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `hyper::proto::h1::conn::Conn<I,B,T>::poll_read_body::CALLSITE'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `hyper::proto::h1::io::Buffered<T,B>::parse::CALLSITE'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `hyper::error::Error::is_canceled'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `<hyper::common::never::Never as std::error::Error>::description'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `<T as core::convert::From<T>>::from'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `hashbrown::raw::RawTable<T>::iter'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `<hyper::proto::h2::PipeToSendStream<S> as core::future::future::Future>::poll::CALLSITE'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `<hyper::proto::h1::role::Client as hyper::proto::h1::Http1Transaction>::encode'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `<hyper::proto::h1::dispatch::Client<B> as hyper::proto::h1::dispatch::Dispatch>::recv_msg::CALLSITE'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `hyper::client::pool::Checkout<T>::checkout::{{closure}}::CALLSITE'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `hyper::proto::h1::decode::Decoder::decode::CALLSITE'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `hyper::proto::h2::decode_content_length'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `http::header::map::HeaderMap<T>::insert_occupied'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `<hyper::proto::h1::dispatch::Client<B> as hyper::proto::h1::dispatch::Dispatch>::poll_ready::CALLSITE'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `hyper::client::conn::Builder::http2_only'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `core::ptr::drop_in_place'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `hyper::proto::h1::decode::ChunkedState::read_extension::CALLSITE'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `core::ptr::drop_in_place'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `core::mem::drop'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `<hyper::client::pool::Pooled<T> as core::ops::drop::Drop>::drop::CALLSITE'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `hyper::error::Error::with'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `hyper::proto::h1::io::ReadStrategy::max'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `<alloc::sync::Arc<T> as core::ops::deref::Deref>::deref'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `hyper::proto::h2::client::new_builder'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `core::ptr::drop_in_place'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `hyper::body::body::Body::new_channel'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `<hyper::proto::h2::client::ClientTask<B> as core::future::future::Future>::poll::CALLSITE'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `hashbrown::raw::RawTable<T>::data_end'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `<hyper::proto::h2::client::ClientTask<B> as core::future::future::Future>::poll::CALLSITE'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `core::ptr::drop_in_place'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `hyper::client::client::ResponseFuture::error_version'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `hyper::error::Error::h2_reason'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `http::uri::builder::Builder::scheme'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `hyper::proto::h1::conn::State::close_read'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `hyper::proto::h1::io::Buffered<T,B>::parse::CALLSITE'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `core::fmt::ArgumentV1::new'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `hyper::proto::h1::conn::Conn<I,B,T>::poll_read_head::CALLSITE'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `<hyper::error::Error as core::convert::From<hyper::error::Parse>>::from'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `hyper::client::connect::http::ConnectError::m'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `hyper::proto::h1::conn::Conn<I,B,T>::maybe_notify::CALLSITE'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `hashbrown::raw::RawTable<T>::buckets'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `hyper::client::client::ResponseFuture::new'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `<core::option::Option<T> as core::clone::Clone>::clone'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `hyper::proto::h1::io::Buffered<T,B>::poll_flush::CALLSITE'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `hyper::client::connect::Connected::clone'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `hyper::client::dispatch::Callback<T,U>::send_when::{{closure}}::CALLSITE'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `hyper::error::Error::new_too_large'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `hyper::upgrade::OnUpgrade::is_none'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `core::ptr::drop_in_place'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `hyper::proto::h1::conn::Conn<I,B,T>::require_empty_read::CALLSITE'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `alloc::vec::Vec<T,A>::reserve'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `hyper::proto::h1::dispatch::Dispatcher<D,Bs,I,T>::poll_flush::{{closure}}::CALLSITE'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `hashbrown::raw::RawTable<T>::is_empty_singleton'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `<hyper::proto::h1::role::Client as hyper::proto::h1::Http1Transaction>::is_client'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `<http::uri::scheme::Scheme2<T> as core::clone::Clone>::clone'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `<&mut T as core::ops::deref::DerefMut>::deref_mut'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `hyper::proto::h1::conn::KA::status'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `hyper::proto::h1::conn::State::try_keep_alive::CALLSITE'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `std::error::<impl core::convert::From<E> for alloc::boxed::Box<dyn std::error::Error+core::marker::Sync+core::marker::Send>>::from'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `<futures_util::future::ready::Ready<T> as core::future::future::Future>::poll'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `hyper::proto::h1::Wants::contains'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `hyper::upgrade::Pending::fulfill'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `core::ptr::drop_in_place'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `<futures_channel::oneshot::Receiver<T> as core::future::future::Future>::poll'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `hyper::proto::h1::dispatch::Dispatcher<D,Bs,I,T>::poll_write::CALLSITE'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `core::fmt::ArgumentV1::new'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `hyper::client::connect::http::HttpConnector<R>::config_mut'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `core::ptr::drop_in_place'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `hyper::client::pool::PoolInner<T>::put::CALLSITE'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `<T as core::borrow::Borrow<T>>::borrow'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `core::ptr::write'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `<hyper::client::connect::dns::GaiResolver as tower_service::Service<hyper::client::connect::dns::Name>>::poll_ready'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `hyper::client::pool::Checkout<T>::checkout::CALLSITE'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `<core::task::poll::Poll<core::result::Result<T,E>> as core::ops::try::Try>::from_error'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `hashbrown::raw::RawTable<T>::new'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `hyper::proto::h1::encode::Encoder::is_last'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `hyper::proto::h1::decode::ChunkedState::read_size_lws::CALLSITE'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `hyper::proto::h1::conn::Conn<I,B,T>::on_read_head_error::CALLSITE'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `hyper::proto::h1::io::Buffered<T,B>::poll_flush::CALLSITE'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `hyper::error::Error::is_parse'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `futures_channel::mpsc::queue::Queue<T>::new'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `hyper::proto::h2::client::conn_task::{{closure}}::CALLSITE'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `hyper::client::pool::Pool<T>::connecting::CALLSITE'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `hyper::client::client::Builder::http2_only'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `hyper::client::connect::Extra::set'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `<alloc::sync::Arc<T> as core::ops::deref::Deref>::deref'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `<core::slice::iter::Iter<T> as core::iter::traits::iterator::Iterator>::next'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `hyper::proto::h2::client::new_ping_config'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `core::ptr::drop_in_place'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `hyper::proto::h1::conn::State::close'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `http::header::map::HeaderMap<T>::remove'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `hyper::proto::h1::dispatch::Dispatcher<D,Bs,I,T>::poll_read::CALLSITE'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `<hyper::proto::h1::io::ReadStrategy as core::default::Default>::default'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `<core::option::Option<T> as core::cmp::PartialEq>::eq'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `<hyper::proto::h2::client::ClientTask<B> as core::future::future::Future>::poll::{{closure}}::CALLSITE'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `core::ptr::drop_in_place'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `hyper::proto::h1::encode::Encoder::encode_and_end::CALLSITE'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `hyper::client::client::Client<C,B>::connect_to::{{closure}}::{{closure}}::{{closure}}::{{closure}}::CALLSITE'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `hyper::proto::h1::conn::KA::idle'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `hyper::error::Error::new_io'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `hashbrown::map::make_hash'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `hyper::client::pool::Config::is_enabled'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `hyper::client::connect::Connected::proxy'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `<core::option::Option<T> as core::clone::Clone>::clone'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `hyper::client::pool::PoolInner<T>::put::CALLSITE'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `hyper::body::body::Sender::try_send_data'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `hyper::proto::h1::encode::ChunkSize::new'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `<hyper::proto::h1::dispatch::Client<B> as hyper::proto::h1::dispatch::Dispatch>::poll_msg::CALLSITE'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `core::mem::drop'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `<&T as core::fmt::Display>::fmt'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `<hyper::client::connect::dns::GaiResolver as tower_service::Service<hyper::client::connect::dns::Name>>::call'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `hashbrown::raw::RawTable<T>::free_buckets'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `hyper::client::pool::PoolInner<T>::put::CALLSITE'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `<T as core::convert::From<T>>::from'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `hyper::proto::h1::io::ReadStrategy::with_max'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `core::ptr::drop_in_place'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `hyper::proto::h1::encode::Encoder::encode::CALLSITE'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `hyper::proto::h1::dispatch::Dispatcher<D,Bs,I,T>::poll_loop::CALLSITE'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `hyper::proto::h2::ping::disabled'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `hyper::client::connect::http::connect'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `hyper::client::connect::dns::SocketAddrs::try_parse'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `hyper::proto::h1::conn::Conn<I,B,T>::mid_message_detect_eof::CALLSITE'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `http::header::map::HeaderMap<T>::remove'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `hyper::client::pool::Expiration::new'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `http::header::map::VacantEntry<T>::insert'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `hyper::proto::h2::ping::Recorder::record_non_data'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `hyper::proto::h1::conn::Conn<I,B,T>::require_empty_read::CALLSITE'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `http::header::map::HeaderMap<T>::entry'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `core::result::Result<T,E>::expect'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `hyper::proto::h1::encode::Encoder::danger_full_buf::CALLSITE'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `hyper::proto::h1::conn::Conn<I,B,T>::poll_flush::CALLSITE'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `hyper::body::body::Body::take_full_data'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `core::slice::raw::from_raw_parts_mut'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `hyper::client::connect::http::ConnectError::m::{{closure}}'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `hyper::proto::h1::io::Buffered<T,B>::poll_flush_flattened::CALLSITE'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `core::ptr::drop_in_place'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `core::ptr::drop_in_place'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `hyper::proto::h1::decode::ChunkedState::read_size_lf::CALLSITE'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `alloc::sync::Arc<T>::inner'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `std::collections::hash::map::HashMap<K,V,S>::insert'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `hyper::client::connect::http::ConnectingTcp::connect'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `<hyper::proto::h1::role::Client as hyper::proto::h1::Http1Transaction>::on_error'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `core::ptr::drop_in_place'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `<hyper::proto::h2::client::ClientTask<B> as core::future::future::Future>::poll::{{closure}}::CALLSITE'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `alloc::vec::Vec<T,A>::set_len'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `core::ptr::drop_in_place'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `tokio::loom::std::unsafe_cell::UnsafeCell<T>::new'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `alloc::boxed::Box<T,A>::into_raw_with_allocator'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `core::ptr::drop_in_place'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `hyper::client::connect::http::<impl hyper::client::connect::Connection for tokio::net::tcp::stream::TcpStream>::connected'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `hyper::error::Error::new_user'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `hyper::client::connect::dns::SocketAddrs::new'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `hyper::client::client::Client<C,B>::connect_to::{{closure}}::{{closure}}::CALLSITE'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `hyper::client::connect::http::ConnectingTcpRemote::connect::{{closure}}::CALLSITE'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `alloc::sync::Arc<T>::inner'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `hyper::proto::h1::conn::Conn<I,B,T>::on_read_head_error::CALLSITE'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `<hyper::common::never::Never as core::fmt::Display>::fmt'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `alloc::vec::Vec<T,A>::capacity'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `hyper::client::client::absolute_form'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `hyper::proto::h1::conn::Conn<I,B,T>::poll_drain_or_close_read::CALLSITE'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `<hyper::client::client::Builder as core::default::Default>::default'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `<hyper::proto::h1::decode::IncompleteBody as core::fmt::Debug>::fmt'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `core::ptr::drop_in_place'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `core::ptr::drop_in_place'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `std::collections::hash::set::HashSet<T>::new'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `hyper::client::pool::PoolInner<T>::put::CALLSITE'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `<hyper::common::never::Never as core::fmt::Debug>::fmt'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `hyper::proto::h2::ping::Ponger::poll'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `hyper::proto::h1::dispatch::Dispatcher<D,Bs,I,T>::poll_write::CALLSITE'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `<dyn core::any::Any>::is'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `core::any::TypeId::of'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `hyper::proto::h1::decode::Decoder::is_eof'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `<I as core::iter::traits::collect::IntoIterator>::into_iter'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `hyper::proto::h2::ping::Recorder::for_stream'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `<hyper::proto::h2::client::ClientTask<B> as core::future::future::Future>::poll::CALLSITE'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `hyper::client::pool::IdlePopper<T>::pop::CALLSITE'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `core::ptr::non_null::NonNull<T>::as_ptr'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `core::ptr::drop_in_place'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `hyper::proto::h1::conn::Conn<I,B,T>::require_empty_read::CALLSITE'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `hyper::client::client::authority_form'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `hyper::client::client::Client<C,B>::request::CALLSITE'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `alloc::vec::Vec<T>::new'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `<hyper::proto::h1::conn::KA as core::fmt::Debug>::fmt'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `core::ptr::drop_in_place'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `core::ptr::drop_in_place'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `hashbrown::raw::RawTable<T>::iter_hash'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `core::ptr::drop_in_place'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `hyper::error::Error::new_version_h2'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `core::ptr::drop_in_place'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `hyper::proto::h1::decode::ChunkedState::read_size_lf::CALLSITE'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `hyper::error::Error::is_connect'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `hyper::proto::h1::decode::Decoder::new'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `hyper::client::client::domain_as_uri'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `hyper::proto::h1::dispatch::Dispatcher<D,Bs,I,T>::poll_read::CALLSITE'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `hyper::proto::h1::io::Cursor<alloc::vec::Vec<u8>>::reset'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `hyper::client::connect::http::ConnectingTcpRemote::connect::{{closure}}::CALLSITE'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `hyper::client::pool::Checkout<T>::poll_waiter::CANCELED'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `tokio::sync::oneshot::Inner<T>::drop_tx_task'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `<std::sync::mutex::MutexGuard<T> as core::ops::deref::DerefMut>::deref_mut'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `core::ptr::drop_in_place'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `hyper::client::connect::http::ConnectingTcpRemote::connect::{{closure}}::CALLSITE'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `futures_util::future::ready::err'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `hyper::proto::h1::encode::Encoder::is_eof'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `hyper::proto::h1::decode::ChunkedState::read_size::CALLSITE'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `<alloc::boxed::Box<T,A> as core::fmt::Debug>::fmt'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `<hyper::proto::h1::conn::State as core::fmt::Debug>::fmt'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `hyper::common::task::yield_now'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `<hyper::error::Error as core::fmt::Debug>::fmt'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `core::ptr::drop_in_place'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `core::ptr::drop_in_place'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `<alloc::sync::Arc<T> as core::ops::deref::Deref>::deref'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `<hyper::proto::h1::conn::KA as core::ops::bit::BitAndAssign<bool>>::bitand_assign'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `core::slice::<impl [T]>::iter'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `hyper::client::connect::http::ConnectError::new'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `core::ptr::drop_in_place'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `<alloc::sync::Arc<T> as core::ops::deref::Deref>::deref'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `hyper::client::connect::http::HttpConnector<R>::set_keepalive'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `core::option::Option<T>::as_ref'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `hyper::client::conn::SendRequest<B>::send_request_retryable::CALLSITE'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `core::ptr::drop_in_place'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `<hyper::client::connect::dns::GaiFuture as core::future::future::Future>::poll'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `core::result::Result<T,E>::unwrap'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `hyper::client::client::Builder::http1_title_case_headers'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `hyper::body::body::Body::new'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `<core::option::Option<T> as core::default::Default>::default'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `<hyper::proto::h1::conn::Writing as core::fmt::Debug>::fmt'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `<alloc::sync::Arc<T> as core::clone::Clone>::clone'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `hyper::proto::h2::ping::channel'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `<hyper::proto::h2::client::ClientTask<B> as core::future::future::Future>::poll::CALLSITE'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `<I as core::iter::traits::collect::IntoIterator>::into_iter'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `<T as core::convert::Into<U>>::into'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `<h2::share::SendStream<hyper::proto::h2::SendBuf<B>> as hyper::proto::h2::SendStreamExt>::send_eos_frame::CALLSITE'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `hyper::client::connect::http::HttpConnector<R>::call_async::{{closure}}::CALLSITE'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `hyper::headers::method_has_defined_payload_semantics'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `hyper::client::client::Client<C,B>::connection_for::{{closure}}::{{closure}}::CALLSITE'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `<hyper::error::Error as std::error::Error>::source'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `core::option::Option<T>::map'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `core::ptr::drop_in_place'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `<hyper::proto::h1::conn::Reading as core::fmt::Debug>::fmt'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `<core::result::Result<T,E> as core::ops::try::Try>::into_result'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `hyper::proto::h1::conn::Conn<I,B,T>::on_upgrade::CALLSITE'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `std::sync::mutex::Mutex<T>::lock'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `hyper::client::client::Client<C,B>::retryably_send_request::{{closure}}::CALLSITE'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `core::ptr::drop_in_place'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `alloc::boxed::Box<dyn core::any::Any,A>::downcast'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `hyper::error::Error::new_incomplete'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `hyper::proto::h1::conn::State::wants_keep_alive'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `hyper::proto::h1::conn::State::busy'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `<hyper::proto::h1::decode::IncompleteBody as core::fmt::Display>::fmt'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `core::mem::needs_drop'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `http::header::map::OccupiedEntry<T>::into_mut'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `<hyper::client::connect::dns::GaiAddrs as core::iter::traits::iterator::Iterator>::next'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `hyper::proto::h1::encode::Encoder::encode_and_end::CALLSITE'
          /usr/bin/ld: /tmp/dylib-errors/target/debug/deps/libshared.so: undefined reference to `hyper::proto::h2::strip_connection_headers'
          collect2: error: ld returned 1 exit status


error: aborting due to previous error

error: could not compile `serverctl`

To learn more, run the command again with --verbose.
```

</details>

### LINKED ISSUE #82972: Link error when compiling reqwest with -C prefer-dynamic
I gather that prefer-dynamic isn't the preferred mode of compiling, but I use it in Evcxr to try and keep memory usage down when compiling and loading lots of .so files with similar dependencies.

Cargo.toml:

```toml
[package]
name = "foo"
version = "1.0.0"
edition = "2018"

[dependencies]
reqwest = "0.11"
tokio = {version = "1.2.0", features = ["full"]}
```

main.rs:

```rust
fn main() {
    let _ = tokio::runtime::Runtime::new()
        .unwrap()
        .block_on(async { reqwest::get("https://www.rust-lang.org") });
}
```

`cargo build` succeeds, however `cargo rustc -- -C prefer-dynamic` fails to link with lots of missing symbols. e.g.:

```
/usr/bin/ld: /home/david/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-channel-0.3.13/src/oneshot.rs:224: undefined reference to `core::mem::drop'
/usr/bin/ld: /home/david/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-channel-0.3.13/src/oneshot.rs:233: undefined reference to `core::ptr::drop_in_place<futures_channel::lock::TryLock<core::option::Option<core::task::wake::Waker>>>'
```

### Meta

Got this behavior on nightly 2021-03-09 as well as stable versions back as far as 1.44. Prior that the code doesn't compile due to missing features.

`rustc +nightly --version --verbose`:

rustc 1.52.0-nightly (3a5d45f68 2021-03-09)
binary: rustc
commit-hash: 3a5d45f68cadc8fff4fbb557780f92b403b19c19
commit-date: 2021-03-09
host: x86_64-unknown-linux-gnu
release: 1.52.0-nightly
LLVM version: 12.0.0

Original report: https://github.com/google/evcxr/issues/156

### PR DESCRIPTION
**Pull request by bjorn3**
This ensures that rustc will not attempt to link against a cdylib as if it is a rust dylib when an rlib for the same crate is available. Previously rustc didn't actually check if any further formats of a crate which has been loaded are of the same version and if they are actually valid. This caused a cdylib to be interpreted as rust dylib as soon as the corresponding rlib was loaded. As cdylibs don't export any rust symbols, linking would fail if rustc decides to link against the cdylib rather than the rlib.

Two crates depended on the previous behavior by separately compiling a test crate as both rlib and dylib. These have been changed to capture their original spirit to the best of my ability while still working when rustc verifies that all crates are in sync. It is unlikely that build systems depend on the current behavior and in any case we are taking a lot of measures to ensure that any change to either the source or the compilation options (including crate type) results in rustc rejecting it as incompatible. We merely didn't do this check here for now obsolete perf reasons.

Note: This increases the size of rust dylibs as their crate metadata is no longer compressed. Cdylibs don't have crate metadata and as such are unaffected.

Fixes https://github.com/rust-lang/rust/issues/10786
Fixes https://github.com/rust-lang/rust/issues/82151
Fixes https://github.com/rust-lang/rust/issues/82972
Closes https://github.com/bevy-cheatbook/bevy-cheatbook/issues/114

### CODE REVIEW

File: compiler/rustc_metadata/src/locator.rs [hunk 1]
```diff
@@ -550,16 +550,9 @@ impl<'a> CrateLocator<'a> {
...
-        //
-        // We currently do not verify that these other sources are even in sync,
-        // and this is arguably a bug (see #10786), but because reading metadata
-        // is quite slow (especially from dylibs) we currently do not read it
-        // from the other crate sources.
         if slot.is_some() {
             if m.is_empty() || !self.needs_crate_flavor(flavor) {
                 return Ok(None);
-            } else if m.len() == 1 {
-                return Ok(Some(m.into_iter().next().unwrap()));
```
Comment (bjorn3) [inline compiler/rustc_metadata/src/locator.rs:562]: This is the meat of the change. By removing this the rest of the function will check compatibility of the candidates with the slot which contains the svh of the rlib that has already been loaded by the call of `extract_one` for the rlib.

File: compiler/rustc_metadata/src/locator.rs [hunk 2]
```diff
@@ -602,16 +595,15 @@ impl<'a> CrateLocator<'a> {
...
                 if let Some(candidates) = err_data {
                     return Err(CrateError::MultipleCandidates(
                         self.crate_name,
                         flavor,
                         candidates,
                     ));
                 }
-                err_data = Some(vec![ret.as_ref().unwrap().0.clone()]);
-                *slot = None;
+                err_data = Some(vec![slot.take().unwrap().0]);
```
Comment (bjorn3) [inline compiler/rustc_metadata/src/locator.rs:606]: This change was necessary to prevent a crash when the first candidate has a mismatch with the slot. At that point `ret` wouldn't have been populated yet.

**Comment by bjorn3** [comment]
@bors try @rust-timer queue

This now loads crate metadata for libstd.so when linking, but not when compiling rlibs.

File: compiler/rustc_metadata/src/locator.rs (hunk 2 above)
Comment (pnkfelix) [reply compiler/rustc_metadata/src/locator.rs:606]: can you extend the doc-comment for this method to indicate that the PathBuf is solely for error diangostics, and should never have a semantic effect on the overall linking behavior?

**Comment by pnkfelix** [comment]
r=me assuming the perf run shows that this doesn't slow things down too much. (We should be willing to accept a performance hit here to get the benefits outlined, especially considering the kinds of problems people are hitting here in practice.)

**Comment by Mark-Simulacrum** [comment]
Does this help with https://github.com/rust-lang/rust/issues/10786? Should it?

**Comment by bjorn3** [comment]
> Does this help with https://github.com/rust-lang/rust/issues/10786? Should it?

Yes

**Comment by bjorn3** [comment]
Let's try with dylib metadata compression disabled to see how much of the perf loss is from dylib metadata decompression. This doubles the size of libstd.so from 6.4MB to 12MB which is not all that much compared to the total size of all standard library crates combined.

@bors try @rust-timer queue

**Comment by bjorn3** [comment]
Much better :)

**Comment by bjorn3** [comment]
Fixed the tests/ui/rmeta/rmeta-rpass.rs test.

@rustbot ready

**Comment by bjorn3** [comment]
Right, rust-analyzer doesn't handle the uncompressed proc macro crate metadata yet. Will need to implement that first.

@rustbot author

**Comment by bjorn3** [comment]
Blocked on https://github.com/rust-lang/rust-analyzer/pull/15301 and a subtree sync to fix rust-analyzer.

**Comment by bjorn3** [comment]
Rust-analyzer now supports uncompressed dylib metadata.

@rustbot ready

File: compiler/rustc_codegen_ssa/src/back/metadata.rs [hunk 3]
```diff
@@ -482,12 +480,8 @@ pub fn create_compressed_metadata_file(
...
 ) -> Vec<u8> {
     let mut compressed = rustc_metadata::METADATA_HEADER.to_vec();
-    // Our length will be backfilled once we're done writing
-    compressed.write_all(&[0; 4]).unwrap();
-    FrameEncoder::new(&mut compressed).write_all(metadata.raw_data()).unwrap();
-    let meta_len = rustc_metadata::METADATA_HEADER.len();
-    let data_len = (compressed.len() - meta_len - 4) as u32;
-    compressed[meta_len..meta_len + 4].copy_from_slice(&data_len.to_be_bytes());
+    compressed.write_all(&(metadata.raw_data().len() as u32).to_be_bytes()).unwrap();
+    compressed.extend(metadata.raw_data());
```
Comment (petrochenkov) [inline compiler/rustc_codegen_ssa/src/back/metadata.rs:484]: The metadata is no longer compressed, so it makes sense to rename the relevant functions and variables to not use "compressed".

File: compiler/rustc_metadata/src/locator.rs [hunk 4]
```diff
@@ -539,7 +539,7 @@ impl<'a> CrateLocator<'a> {
         &mut self,
         m: FxHashMap<PathBuf, PathKind>,
         flavor: CrateFlavor,
-        slot: &mut Option<(Svh, MetadataBlob)>,
+        slot: &mut Option<(PathBuf, Svh, MetadataBlob)>,
```
Comment (petrochenkov) [inline compiler/rustc_metadata/src/locator.rs:542]:
```suggestion
        slot: &mut Option<(Svh, MetadataBlob, PathBuf)>,
```
and also add the comment requested by pnkfelix in https://github.com/rust-lang/rust/pull/113695/files#r1263849608.
(To avoid unnecessary changes on use, and put the "least important" diagnostic-only field last.)

**Comment by bjorn3** [comment]
Fixed all review comments.

**Comment by klensy** [comment]
This should mention size increase somewhere in header: as i found size diff around 2x, bisected to here and found. that this was expected.

**Comment by bjorn3** [comment]
Done @klensy
