### PR TITLE
sugg: suggest the usage of boolean value when there is a typo in the keyword

### LINKED ISSUE #100686: If `True` is not in scope and is used, suggest the valid `true`
Given the following code: [link](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=131e3aa966bc4494cbffd42a313f0b35)

```rust
fn main() {
    let x = True;
}
```

The current output is:

```
Compiling playground v0.0.1 (/playground)
error[[E0425]](https://doc.rust-lang.org/nightly/error-index.html#E0425): cannot find value `True` in this scope
 --> src/main.rs:2:13
  |
2 |     let x = True;
  |             ^^^^ not found in this scope

For more information about this error, try `rustc --explain E0425`.
error: could not compile `playground` due to previous error
```

Ideally the output should suggest something like "if this is meant to be a boolean, consider changing it to `true`", since `True` is used for other languages.

### PR DESCRIPTION
**Pull request by vincenzopalazzo**
Fixes https://github.com/rust-lang/rust/issues/100686

This adds a new suggestion when there is a well-known typo

With the following program

```rust
fn main() {
    let x = True;
}
```

Now we have the following suggestion

```
error[E0425]: cannot find value `True` in this scope
 --> test.rs:2:13
  |
2 |     let x = True;
  |             ^^^^ not found in this scope
  |
help: you may want to use a bool value instead
  |
2 |     let x = true;
  |             ~~~~

error: aborting due to previous error
```

Signed-off-by: Vincenzo Palazzo <vincenzopalazzodev@gmail.com>

### CODE REVIEW

File: compiler/rustc_resolve/src/late/diagnostics.rs [hunk 1]
```diff
@@ -250,17 +250,34 @@ impl<'a: 'ast, 'ast> LateResolutionVisitor<'a, '_, 'ast> {
...
+            };
+
             BaseError {
                 msg: format!("cannot find {expected} `{item_str}` in {mod_prefix}{mod_str}"),
-                fallback_label: if path_str == "async" && expected.starts_with("struct") {
-                    "`async` blocks are only allowed in Rust 2018 or later".to_string()
-                } else {
-                    format!("not found in {mod_str}")
-                },
+                fallback_label: fallback_label,
```
Comment (TaKO8Ki) [inline compiler/rustc_resolve/src/late/diagnostics.rs:276]: nit: You can use a shorthand like the following 

```suggestion
                fallback_label,
```

File: compiler/rustc_resolve/src/late/diagnostics.rs [hunk 2]
```diff
@@ -250,17 +250,34 @@ impl<'a: 'ast, 'ast> LateResolutionVisitor<'a, '_, 'ast> {
...
             };
+
+            let (fallback_label, override_sugg) = if path_str == "async"
+                && expected.starts_with("struct")
+            {
+                ("`async` blocks are only allowed in Rust 2018 or later".to_string(), suggestion)
+            } else {
+                // check if we are in situation of typo like `True` instead of `true`.
+                let override_siggestion =
+                    if ["true", "false"].contains(&item_str.to_string().to_lowercase().as_str()) {
```
Comment (TaKO8Ki) [inline compiler/rustc_resolve/src/late/diagnostics.rs:261]: I think this would be true if `item_str` is like `tRue` or `trUE`. Could you change this to something like:

```suggestion
                    let sugg = match item_str.as_str() {
                        "True" => Some(kw::True),
                        "False" => Some(kw::False),
                        _ => None,
                    };
                    if let Some(sugg) = sugg {
```

Comment (vincenzopalazzo) [reply compiler/rustc_resolve/src/late/diagnostics.rs:261]: in this case, we do catch cases like "TRue" and "TruE"

Comment (vincenzopalazzo) [reply compiler/rustc_resolve/src/late/diagnostics.rs:261]: However, I can keep `.to_string().to_lowercase().as_str()` and us the match with the case in lower case.

I like your refactoring

Comment (TaKO8Ki) [reply compiler/rustc_resolve/src/late/diagnostics.rs:261]: Sorry. What I really mean is that this condition should not be true if `item_str` is like `tRue`, `trUE`, `TRue` or `TruE`.

Comment (vincenzopalazzo) [reply compiler/rustc_resolve/src/late/diagnostics.rs:261]: A wait! my screen reader jump a line, with this

> I think this would be true if item_str is like tRue or trUE. Could you change this to something like:

Do you think that it is not good normalize all the typo possibility? but just include `True` and `False`?

Comment (TaKO8Ki) [reply compiler/rustc_resolve/src/late/diagnostics.rs:261]: Yes, I do. I think rustc should suggest `true` or `false` when using `True` and `False` instead of `true` and `false` because they are used for other languages such as Python.

File: compiler/rustc_resolve/src/late/diagnostics.rs [hunk 3]
```diff
@@ -250,17 +250,34 @@ impl<'a: 'ast, 'ast> LateResolutionVisitor<'a, '_, 'ast> {
...
                 (mod_prefix, format!("`{}`", Segment::names_to_string(mod_path)), None)
             };
+
+            let (fallback_label, override_sugg) = if path_str == "async"
+                && expected.starts_with("struct")
+            {
+                ("`async` blocks are only allowed in Rust 2018 or later".to_string(), suggestion)
+            } else {
+                // check if we are in situation of typo like `True` instead of `true`.
+                let override_siggestion =
```
Comment (davidtwco) [inline compiler/rustc_resolve/src/late/diagnostics.rs:260]:
```suggestion
                let override_suggestion =
```
nit: typo

File: compiler/rustc_resolve/src/late/diagnostics.rs [hunk 4]
```diff
@@ -250,17 +250,34 @@ impl<'a: 'ast, 'ast> LateResolutionVisitor<'a, '_, 'ast> {
                 .map_or_else(String::new, |res| format!("{} ", res.descr()));
                 (mod_prefix, format!("`{}`", Segment::names_to_string(mod_path)), None)
             };
+
+            let (fallback_label, override_sugg) = if path_str == "async"
```
Comment (davidtwco) [inline compiler/rustc_resolve/src/late/diagnostics.rs:254]:
```suggestion
            let (fallback_label, suggestion) = if path_str == "async"
```
nit: I think it's fine to just shadow the name here.

File: compiler/rustc_resolve/src/late/diagnostics.rs (hunk 2 above)
Comment (davidtwco) [reply compiler/rustc_resolve/src/late/diagnostics.rs:261]: I think it's okay that this suggests using `true` for `tRue`/`truE`/`tRUE`/etc and not just `True` - the user might not have been trying to use another language's syntax, but it would still help fix what is likely to be a typo.

**Review by davidtwco — CHANGES_REQUESTED** [review]
LGTM, a couple comments

File: compiler/rustc_resolve/src/late/diagnostics.rs (hunk 2 above)
Comment (vincenzopalazzo) [reply compiler/rustc_resolve/src/late/diagnostics.rs:261]: I vote for keeping the typo fixing, this could also use in code generation, where the compiler generates rust and make a stupid typo into it.

File: compiler/rustc_resolve/src/late/diagnostics.rs (hunk 4 above)
Comment (vincenzopalazzo) [reply compiler/rustc_resolve/src/late/diagnostics.rs:254]: Smart think, yes!

**Review by davidtwco — APPROVED** [review]
