### PR TITLE
Output previous stable  error messaging when using stable build.

### LINKED ISSUE #65254: Confusing error now saying `let` (not `if let`) is an expression, rather than a statement, which contradicts the book
cc @Centril 

Code first. This code:

```
fn main() {
    let x = (let y = 6);
}
```

[on current stable Rust 1.38](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=db087215a59f29b6c19440c89ddb2484), gives this set of error messages:

```
error[E0658]: `let` expressions in this position are experimental
 --> src/main.rs:2:14
  |
2 |     let x = (let y = 6);
  |              ^^^^^^^^^
  |
  = note: for more information, see https://github.com/rust-lang/rust/issues/53667

error: `let` expressions are not supported here
 --> src/main.rs:2:14
  |
2 |     let x = (let y = 6);
  |              ^^^^^^^^^
  |
  = note: only supported directly in conditions of `if`- and `while`-expressions
  = note: as well as when nested within `&&` and parenthesis in those conditions

warning: unnecessary parentheses around assigned value
 --> src/main.rs:2:13
  |
2 |     let x = (let y = 6);
  |             ^^^^^^^^^^^ help: remove these parentheses
  |
  = note: `#[warn(unused_parens)]` on by default
``` 

The part that I'm most concerned about is:

```
error: `let` expressions are not supported here
```

Before eRFC *"if- and while-let-chains, take 2"* (rust-lang/rfcs#2497, https://github.com/rust-lang/rust/issues/53667, https://github.com/rust-lang/rust/issues/53668), this code USED to result in this error message:

```
error: expected expression, found statement (`let`)
 --> src/main.rs:2:14
  |
2 |     let x = (let y = 6);
  |              ^^^
  |
  = note: variable declaration using `let` is a statement
```

The reason I know this is because [we have the old error message in the book](https://doc.rust-lang.org/1.38.0/book/ch03-03-how-functions-work.html#function-bodies-contain-statements-and-expressions), in the section where we're trying to explain the difference between statements and expressions. The error message I'm seeing now is muddying the waters by saying "`let` expressions".

Based on my reading of the eRFC, it's only supposed to change `if let`, but as kind of a side effect `let` is now sort-of an expression? The [updates to the reference](https://github.com/rust-lang-nursery/reference/pull/437/files) don't clear it up for me, as they *only* describe `if let`, not plain `let`s.

What I expected is that even though the eRFC has been accepted and implemented, plain `let y = 6` would still be considered a statement and the error message wouldn't talk about "`let` expressions".

If my expectation is valid, then the compiler error message is a bug. If my expectation is invalid, please let me know so that I can work on updating the book. Thanks!

This issue has been assigned to @jafern14 via [this comment](https://github.com/rust-lang/rust/issues/65254#issuecomment-546919992).

### PR DESCRIPTION
**Pull request by jafern14**
Fixes #65254 

As I had mentioned previously there I have the logic running right now however I'm not getting the exact same syntax highlighting as there was originally for this error.

I'm currently getting the following:
```
error: expected expression, found statement (`let`)
 --> src/main.rs:2:14
  |
2 |     let x = (let y = 6);
  |              ^^^^^^^^^
  |
  = note: variable declaration using `let` is a statement
```

I'd like to get the following instead:

```
  |     let x = (let y = 6);
  |              ^^^
```

My current understanding is that the `span` being passed into `lower_expr_let` is coming from `lowering.rs`. I still don't know how the byte range is calculated for the erroneous syntax and need to look into it a bit more. In the meantime does anybody have any hints/tips regarding this??

### CODE REVIEW

**Comment by jafern14** [comment]
I forgot to undo the text change to the nightly feature error output which resulted in the majority of the test failures. At the time I was experimenting with building the compiler and figuring out how it came together. I removed that text to try and see _a change_ in the compiler output with the local crate I was compiling and running. 

I just put that text back in there. I'd like to add in a test to ensure nightly vs stable error output. You think this is worth it at all @Centril ? It would make the promoting process to fully stable a little bit more involved. Not sure what your best practices are here.

File: src/librustc/hir/lowering/expr.rs [hunk 1]
```diff
@@ -235,11 +235,20 @@ impl LoweringContext<'_> {
     /// ```
     fn lower_expr_let(&mut self, span: Span, pat: &Pat, scrutinee: &Expr) -> hir::ExprKind {
         // If we got here, the `let` expression is not allowed.
-        self.sess
-            .struct_span_err(span, "`let` expressions are not supported here")
-            .note("only supported directly in conditions of `if`- and `while`-expressions")
-            .note("as well as when nested within `&&` and parenthesis in those conditions")
-            .emit();
+
+        if self.sess.parse_sess.unstable_features.is_nightly_build() {
```
Comment (Centril) [inline src/librustc/hir/lowering/expr.rs]:
```suggestion
        if self.sess.opts.unstable_features.is_nightly_build() {
```
(Same thing but already public so you don't need to change the other one to `pub`... not sure why we have more than 1 of these tho; cc @estebank)

**Comment by Centril** [comment]
> I'm currently getting the following:

This is good; better actually! -- the old message only highlighted the `let` because it didn't perform proper parser recovery. :)

> Not sure what your best practices are here.

@estebank Do we have any way of forcing a compiler to believe it's a stable compiler for testing purposes via some command line flag or something? Otherwise I don't think we can test the difference.

File: src/librustc/hir/lowering/expr.rs (hunk 1 above)
Comment (Centril) [reply src/librustc/hir/lowering/expr.rs]: Thanks; Squashing the commits into one seems like a good idea.

**Comment by estebank** [comment]
@Centril, sadly I don't think we do. You can change the target of your build to test locally, but I haven't seen any tests actually testing what things look in stable (although we do have stable/nightly output differences which we _should_ test).

File: src/librustc/hir/lowering/expr.rs [hunk 2]
```diff
@@ -235,11 +235,20 @@ impl LoweringContext<'_> {
...
+            self.sess
+                .struct_span_err(span, "`let` expressions are not supported here")
+                .note("only supported directly in conditions of `if`- and `while`-expressions")
+                .note("as well as when nested within `&&` and parenthesis in those conditions")
+                .emit();
+        }
+        else {
+            self.sess
+                .struct_span_err(span, "expected expression, found statement (`let`)")
+                .note ("variable declaration using `let` is a statement")
```
Comment (estebank) [inline src/librustc/hir/lowering/expr.rs]: Remove the space between `.note` and `(`.

**Comment by Centril** [comment]
@estebank I guess there's not much we can do in this case then.

r=me rollup with @estebank's nit addressed and the commits squashed into one.

**Comment by jafern14** [comment]
Fixed the nit and squashed the commits.

**Comment by Centril** [comment]
Thanks! @bors r+ rollup
