### PR TITLE
Fixes #31229 fixes up BSD type mismatch errors and updates libc dependency part deux

### LINKED ISSUE #31229: bsd builds broken by libstd
some type mismatches.

### PR DESCRIPTION
**Pull request by dhuseby**
Something went haywire with github last night and the old PR https://github.com/rust-lang/rust/pull/31230 got closed somehow.  This new PR is to replace the old one.  This incorporates all of the feedback from the other PR.

@alexcrichton I incorporated the suggestion from @semarie and the result is cleaner and clearer.  I think this is ready to go.

### CODE REVIEW

File: src/libstd/sys/unix/stack_overflow.rs [hunk 1]
```diff
@@ -135,26 +135,44 @@ mod imp {
...
+        let stackp = mmap(ptr::null_mut(),
+                          SIGSTKSZ,
+                          PROT_READ | PROT_WRITE,
+                          MAP_PRIVATE | MAP_ANON,
+                          -1,
+                          0);
+        if stackp == MAP_FAILED {
+            panic!("failed to allocate an alternative stack");
+        }
+        libc::stack_t { ss_sp: stackp as *mut i8, ss_flags: 0, ss_size: SIGSTKSZ }
```
Comment (alexcrichton) [inline src/libstd/sys/unix/stack_overflow.rs]: I'd personally prefer to not duplicate these calls to `mmap` (they both return have the exact same call). I saw discussion about a `stack_t` on the other thread, but why's that done here?

**Comment by alexcrichton** [comment]
I think the merge conflict is from libc, which at this point should be fully upgraded, so that part can probably be backed out of this change

File: src/libstd/sys/unix/stack_overflow.rs (hunk 1 above)
Comment (dhuseby) [inline src/libstd/sys/unix/stack_overflow.rs]: The reason this is duplicated is because there is only one mmap and it always returns a *mut libc::c_void.  On FreeBSD and DragonflyBSD, the libc::stack_t.ss_sp member is a *mut i8.  Also, because we have compile flags that say treat all warnings as errors, the FreeBSD and DragonflyBSD builds were failing.

What is needed is a conditional compilation block that casts the result of mmap to a *mut i8 when building for FreeBSD and DragonflyBSD.  BUT, we don't have conditional compilation for general expressions yet.  We only have it for functions.  So I'm forced to wrap the mmap call and libc::stack_t initialization in a function that can be conditionally compiled based on OS.

**Comment by dhuseby** [comment]
@alexcrichton I backed out the libc update revision.  If you accept my explanation for duplicating the call to mmap, then this PR should be GTG.

File: src/libstd/sys/unix/stack_overflow.rs (hunk 1 above)
Comment (alexcrichton) [inline src/libstd/sys/unix/stack_overflow.rs]: I don't understand why we need this at all, though, doesn't this work on all platforms?

```rust
let stackp = mmap(...);
if stackp == MAP_FAILED { ... }
return stackp as *mut u8
```

Comment (dhuseby) [inline src/libstd/sys/unix/stack_overflow.rs]: No it doesn't.  There are compile flags that turn warnings into errors and this generates a warning.

Comment (alexcrichton) [inline src/libstd/sys/unix/stack_overflow.rs]: What flags are those? I thought we removed the lint for trivial casts... Either way a local `#[allow]` is better than all-out code duplication here I think

Comment (dhuseby) [inline src/libstd/sys/unix/stack_overflow.rs]: The errors on FreeBSD look like this:
```
../src/libstd/sys/unix/stack_overflow.rs:151:23: 151:32 error: mismatched types:
 expected `*mut i8`,
    found `*mut libc::c_void`
(expected i8,
    found enum `libc::c_void`) [E0308]
../src/libstd/sys/unix/stack_overflow.rs:151         stack.ss_sp = alt_stack;
                                                                   ^~~~~~~~~
```

Comment (dhuseby) [inline src/libstd/sys/unix/stack_overflow.rs]: oh wait, i see what you're saying.  maybe we get an error whenever we go from `*mut libc::c_void` to `*mut i8` but we may not get an error going the other way.  so if we have a get_stack() function that always return the stack pointer as `*mut i8` then we eliminate the error above on platforms that have an i8 stack pointer.  let me try that in the morning.

Comment (alexcrichton) [inline src/libstd/sys/unix/stack_overflow.rs]: Yeah if everything returns `*mut foo` then returning `bar as *mut foo` shouldn't warn

Comment (dhuseby) [inline src/libstd/sys/unix/stack_overflow.rs]: @alexcrichton it didn't work.  i changed the code to `get_stack() -> *mut i8` for all platforms and now on non-freebsd, i'm getting:
```
../src/libstd/sys/unix/stack_overflow.rs:152:44: 152:55 error: mismatched types:
 expected `*mut libc::c_void`,
    found `*mut i8`
(expected enum `libc::c_void`,
    found i8) [E0308]
../src/libstd/sys/unix/stack_overflow.rs:152         let stack = libc::stack_t { ss_sp: get_stack(), ss_flags: 0, ss_size: SIGSTKSZ };
```
i don't think your solution works.  we should go with this patch instead.

Comment (alexcrichton) [inline src/libstd/sys/unix/stack_overflow.rs]: Right it's not working because this is using `stack_t` (and I don't know why). If that's not used and only pointers are used it shouldn't require duplication of the calls to `mmap` (which needs to be prioritized)

**Comment by dhuseby** [comment]
@alexcrichton i rebased and rearranged the code so that there is only a single call to mmap.  this is simpler than previous solutions, but still relies on conditional compilation.
