### PR TITLE
Disable missing_copy_implementations lint on non_exhaustive types

### LINKED ISSUE #116766: Adding non_exhaustive should disable missing_copy_implementations
I have the following minimal example:

```rust
#![deny(missing_copy_implementations)]

#[derive(Clone)]
pub enum MyEnum {
    A,
}
```

It does as I expect and gives the error:

```
error: type could implement `Copy`; consider adding `impl Copy`
 --> src/lib.rs:4:1
  |
4 | / pub enum MyEnum {
5 | |     A,
6 | | }
  | |_^
  |
note: the lint level is defined here
 --> src/lib.rs:1:9
  |
1 | #![deny(missing_copy_implementations)]
  |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

However, since this enum is going to have more options added to it in the future, for example, `B(String),` I go ahead and label it as `non_exhaustive`:

```rust
#![deny(missing_copy_implementations)]

#[derive(Clone)]
#[non_exhaustive]
pub enum MyEnum {
    A,
}
```

I would expect that this would disable the `missing_copy_implementations` lint in this case. This is because, otherwise adding a `Copy` implementation, e.g.:

```rust
#![deny(missing_copy_implementations)]

#[derive(Clone, Copy)]
#[non_exhaustive]
pub enum MyEnum {
    A,
}
```

would then break when, in the future, I add my `B` variant:

```rust
#![deny(missing_copy_implementations)]

#[derive(Clone, Copy)]
#[non_exhaustive]
pub enum MyEnum {
    A,
    B(String),
}
```

with:

```
error[E0204]: the trait `Copy` cannot be implemented for this type
 --> src/lib.rs:3:17
  |
3 | #[derive(Clone, Copy)]
  |                 ^^^^
...
7 |     B(String),
  |       ------ this field does not implement `Copy`
  |
```

In short, I would expect that adding `non_exhaustive` would disable the `missing_copy_implementations` lint as it's not future-proof, and the whole point of the `non_exhaustive` attribute is to say "that a type or variant may have more fields or variants added in the future".

### PR DESCRIPTION
**Pull request by rmehri01**
Fixes #116766

### CODE REVIEW

File: compiler/rustc_lint/src/builtin.rs [hunk 1]
```diff
@@ -730,6 +734,14 @@ fn type_implements_negative_copy_modulo_regions<'tcx>(
     tcx.infer_ctxt().build().predicate_must_hold_modulo_regions(&obligation)
 }
 
+fn def_or_variant_marked_non_exhaustive<'tcx>(tcx: TyCtxt<'tcx>, def: ty::AdtDef<'tcx>) -> bool {
+    def.variants()
+        .iter()
+        .map(|variant| variant.def_id)
+        .chain(iter::once(def.did()))
+        .any(|did| tcx.has_attr(did, sym::non_exhaustive))
```
Comment (petrochenkov) [inline compiler/rustc_lint/src/builtin.rs:742]: It should be better to use `is_variant_list_non_exhaustive`/`is_field_list_non_exhaustive` here instead of inspecting attributes manually.

Comment (rmehri01) [reply compiler/rustc_lint/src/builtin.rs]: Ah, that is much nicer, thanks!

File: compiler/rustc_lint/src/builtin.rs [hunk 2]
```diff
@@ -730,6 +733,11 @@ fn type_implements_negative_copy_modulo_regions<'tcx>(
     tcx.infer_ctxt().build().predicate_must_hold_modulo_regions(&obligation)
 }
 
+fn def_or_variant_marked_non_exhaustive<'tcx>(def: ty::AdtDef<'tcx>) -> bool {
```
Comment (petrochenkov) [inline compiler/rustc_lint/src/builtin.rs:736]: Probably better to inline and remove this function now.

**Comment by petrochenkov** [comment]
r=me after addressing https://github.com/rust-lang/rust/pull/116812#discussion_r1362319228 and squashing commits.
