### PR TITLE
Fix invalid suggestion for mismatched types in closure arguments

### LINKED ISSUE #114180: Nonsensical suggestion on closure param type error
### Code

```Rust
// Minimal reproduction -- works on rust playground as of 7/28/23
fn main() {
    let mut v = vec![(1,)];
    let compare = |(a,), (e,)| todo!();
    v.sort_by(compare);
}
```

### Current output

```Shell
Compiling playground v0.0.1 (/playground)
error[E0631]: type mismatch in closure arguments
 --> src/main.rs:6:15
  |
5 |     let compare = |(a,), (e,)| todo!();
  |                   ------------ found signature defined here
6 |     v.sort_by(compare);
  |       ------- ^^^^^^^ expected due to this
  |       |
  |       required by a bound introduced by this call
  |
  = note: expected closure signature `for<'a, 'b> fn(&'a ({integer},), &'b ({integer},)) -> _`
             found closure signature `fn((_,), (_,)) -> _`
note: required by a bound in `slice::<impl [T]>::sort_by`
 --> /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/alloc/src/slice.rs:263:5
help: consider borrowing the argument
  |
5 |     let compare = |(a,&), (e,&)| todo!();
  |                       +      +

For more information about this error, try `rustc --explain E0631`.
error: could not compile `playground` (bin "playground") due to previous error
```

### Desired output

```Shell
I don't know. There is an HRTB involved here, and I'm not sure there is any simple suggestion that fixes this code.

But certainly the current suggestion should not be there.
```

### Rationale and extra context

Currently, the compiler outputs the following suggestion after the type error:

```
help: consider borrowing the argument
  |
5 |     let compare = |(a,&), (e,&)| todo!();
  |                       +      +
```

This is syntactically invalid code.

### Other cases

_No response_

### Anything else?

I'm using 1.70 stable and getting this. I also get it with 1.71 stable on the rust playground.

### PR DESCRIPTION
**Pull request by Urgau**
This PR fixes the invalid suggestion for mismatched types in closure arguments.

The invalid suggestion came from a wrongly created span in the parser for closure arguments that don't have a type specified. Specifically, the span in this case was the last token span, but in the case of tuples, the span represented the last parenthesis instead of the whole tuple, which is fixed by taking the more accurate span of the pattern.

There is one unfortunate downside of this fix, it worsens even more the diagnostic for mismatched types in closure args without an explicit type. This happens because there is no correct span for implied inferred type. I tried also fixing this but it's a rabbit hole.

Fixes https://github.com/rust-lang/rust/issues/114180

### CODE REVIEW

**Review by WaffleLapkin — APPROVED** [review]

File: tests/ui/mismatched_types/closure-ref-114180.rs [hunk 1]
```diff
@@ -0,0 +1,8 @@
+// check-fail
```
Comment (WaffleLapkin) [inline tests/ui/mismatched_types/closure-ref-114180.rs:1]: Wait, actually, can you make this into `// run-rustfix` test? (also `// check-fail` is the default iirc, you don't need it)

Comment (Urgau) [reply tests/ui/mismatched_types/closure-ref-114180.rs:1]: Unfortunately no, since the current suggestion is not enough to fix the issue; but applying it will lead to a another suggestion which fixes the issue.

Comment (WaffleLapkin) [reply tests/ui/mismatched_types/closure-ref-114180.rs:1]: oof, that's unfortunate
