### PR TITLE
HashMap is UnwindSafe

### LINKED ISSUE #62301: 1.36 changes the `UnwindSafe` impl precondition for HashMap
https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=0e5a528fc978a90aa15bbf01f68dd1bf

```rust
assert_unwind_safe::<HashMap<(), UnsafeCell<()>>>();
```

Successfully compiles on stable 1.35, fails on beta/pre 1.36.

### PR DESCRIPTION
**Pull request by SimonSapin**
Fixes https://github.com/rust-lang/rust/issues/62301, a regression in 1.36.0-pre which was caused by hashbrown using `NonZero<T>` where the older hashmap used `Unique<T>`.

### CODE REVIEW

**Comment by SimonSapin** [comment]
@rust-lang/release, is there time to squeeze this into 1.36.0?

**Comment by Mark-Simulacrum** [comment]
Most likely no, but I'm reaching out to folks and will try to update here if we decide to go ahead.

File: src/libstd/panic.rs [hunk 1]
```diff
@@ -285,6 +286,12 @@ impl RefUnwindSafe for atomic::AtomicBool {}
 #[stable(feature = "unwind_safe_atomic_refs", since = "1.14.0")]
 impl<T> RefUnwindSafe for atomic::AtomicPtr<T> {}
 
+// https://github.com/rust-lang/rust/issues/62301
+#[stable(feature = "hashbrown", since = "1.36.0")]
+impl<K, V, S> UnwindSafe for collections::HashMap<K, V, S> where K: UnwindSafe, V: UnwindSafe {}
```
Comment (cuviper) [inline src/libstd/panic.rs]: Should there be any constraint on `S`?

File: src/libstd/panic.rs [hunk 2]
```diff
@@ -285,6 +286,12 @@ impl RefUnwindSafe for atomic::AtomicBool {}
...
+#[stable(feature = "hashbrown", since = "1.36.0")]
+impl<T, S> UnwindSafe for collections::HashSet<T, S> where T: UnwindSafe {}
```
Comment (cuviper) [inline src/libstd/panic.rs]: I would expect the set's impl to be automatic from the map's, but that deserves a test.

File: src/libstd/panic.rs (hunk 1 above)
Comment (SimonSapin) [reply src/libstd/panic.rs]: Indeed.

File: src/libstd/panic.rs (hunk 2 above)
Comment (SimonSapin) [reply src/libstd/panic.rs]: Oh, I was expected `std::collections::HashSet` to be based on `hashbrown::HashSet` but it’s not. It’s based on `std::collections::HashMap`, so you’re right.

**Comment by SimonSapin** [comment]
Ideally this would be in hashbrown itself, but hashbrown is `#![no_std]` and `UnwindSafe` is defined in libstd.

**Comment by Mark-Simulacrum** [comment]
We've decided that we probably can go ahead with a stable CI build; I want this r+-ed before we go ahead fully though. I'll start preparing a stable-targeting PR in an hour or so.

**Comment by eddyb** [comment]
This seems good enough, we can change how we do this later, as long as `HashMap` remains `UnwindSafe`.

@bors r+

**Comment by pietroalbini** [comment]
Already backported.

**Comment by Mark-Simulacrum** [comment]
@rust-lang/libs -- as a process note, we backported this fix to beta and stable already, but I don't think it went through official confirmation by y'all, so just pinging you to make sure it doesn't get lost
