### PR TITLE
Handle remapped paths correctly when generating "Source" links

### LINKED ISSUE #150100: Add regression test for https://github.com/rust-lang/rust/pull/149919
In https://github.com/rust-lang/rust/pull/149919, we fix the issue in metadata generation for doc attributes, however I wasn't able to write a regression test, which is problematic to ensure it never happens again.

If anyone can come up with such a test, it'd be wonderful!

### PR DESCRIPTION
**Pull request by Urgau**
Fixes https://github.com/rust-lang/rust/issues/150100.

This PR fixes a regression introduced by [#149709](https://github.com/rust-lang/rust/issues/149709), I was overzealous in my changes (https://github.com/rust-lang/rust/pull/149709/changes#diff-e1cf7ef2fb411d24980cd4cbea1e867cc36029e9496e1ceca64cfb6a0e3510f6) and accidentally changed the behavior of `rustdoc` in the presence of remapped, to simply reject them instead of handling them.

With this PR remapped paths are handled correctly, in a similar way as it was before.

~~I added a run-make test to make sure we don't regress it again, a simple `rustdoc` test in not sufficient as `rustdoc` is not called on the auxiliary crate. It's not pretty but it works.~~ https://github.com/rust-lang/rust/pull/150172#issuecomment-3676762399

rustdoc doesn't have any handling for `--remap-path-scope`, so I used the `MACRO` scope (it was already used [elsewhere](https://github.com/rust-lang/rust/blob/b889870082dd0b0e3594bbfbebb4545d54710829/src/librustdoc/clean/types.rs#L154).

cf. https://rust-lang.zulipchat.com/#narrow/channel/266220-t-rustdoc/topic/source.20links.20missing.20for.20nightly.20std.20docs

r? @GuillaumeGomez

### CODE REVIEW

**Comment by Urgau** [comment]
> `//@ build-aux-docs` enables doc building for auxiliaries.

This almost work, except that the `compile-flags` of the auxiliary crate are also passed to rustdoc, and unfortunately it trips an assertion in `rustdoc`. EDIT: lol we trip the same assertion in another test.

<details>

```
thread 'rustc' (52267) panicked at src/librustdoc/html/sources.rs:349:14:
only local crates should have sources emitted
```

<details>

File: tests/run-make/rustdoc-remapped-paths/rmake.rs [hunk 1]
```diff
@@ -0,0 +1,23 @@
+use run_make_support::{cwd, rfs, rustc, rustdoc};
```
Comment (GuillaumeGomez) [inline tests/run-make/rustdoc-remapped-paths/rmake.rs]: Please add a comment explaining what this is testing (and link to https://github.com/rust-lang/rust/issues/150100 as well).

Comment (Urgau) [reply tests/run-make/rustdoc-remapped-paths/rmake.rs]: Added a comment and the link to https://github.com/rust-lang/rust/issues/150100.

File: tests/rustdoc/import-remapped-paths.rs [hunk 2]
```diff
@@ -0,0 +1,19 @@
+// This is a regression for `--remap-path-prefix` in an auxiliary dependency.
+//
+// We want to make sure that we can still have the "Source" links to the dependency
+// even if it's paths are remapped.
```
Comment (GuillaumeGomez) [inline tests/rustdoc/import-remapped-paths.rs]:
```suggestion
// even if its paths are remapped.
```

**Comment by GuillaumeGomez** [comment]
@urgau told me they would be able to update the PR until tomorrow and told me to push if I wanted it to be merged sooner. So considering it's a big regression, I pushed a commit (to not appear as co-author of a previous one considering it's such a small change...). Will need to nominate it for beta-backport once merged as well.

In any case.

@bors r+ rollup
