### PR TITLE
Avoid alignment mismatch between ABI and layout for unions.

### LINKED ISSUE #103634: Layout sanity failed check: "size mismatch between ABI and layout in TyAndLayout". Zero size array in union.
### Code

```Rust
#![crate_type = "lib"]
#![feature(transmutability)]
#![allow(dead_code)]

mod assert {
    use std::mem::{Assume, BikeshedIntrinsicFrom};
    pub struct Context;
    pub fn is_maybe_transmutable<Src, Dst>()
    where
        Dst: BikeshedIntrinsicFrom<Src, Context, {
            Assume {
                alignment: false,
                lifetimes: false,
                safety: false,
                validity: false,
            }
        }>
    {}
}

fn test() {
    pub union U {
        a: [u16; 0],
        b: u8,
    }

    #[repr(C)]
    struct S(
        U, 
        u8,
    );

    assert::is_maybe_transmutable::<S, u128>();
}
```

Found with a [modified fuzz-rustc](https://github.com/jruderman/fuzz-rustc)

<details><summary>About this testcase</summary>

Origin:

* Found by fuzzer mutating [src/test/ui/transmutability/unions/repr/should_handle_packed.rs](https://github.com/rust-lang/rust/blob/0da281b6068a7d889ae89a9bd8991284cc9b7535/src/test/ui/transmutability/unions/repr/should_handle_packed.rs)
* I tried to reduce the `test` function while keeping the `assert` module normal-ish

Elements that seem necessary:

* In the union, the zero-length array seems necessary
* In the union, `a` and `b` mentioning different size things (`u16` vs `u8`) seems necessary
* The union's lack of `#[repr(C)]` seems necessary

</details>

### ICE output

In a compiler _with debug assertions enabled_, this trips: "size mismatch between ABI and layout in TyAndLayout".

<details><summary>Output including layouts, backtraces, and query stack</summary>
<p>

```
thread 'rustc' panicked at 'assertion failed: `(left == right)`
  left: `Size(2 bytes)`,
 right: `Size(1 bytes)`: size mismatch between ABI and layout in TyAndLayout {
    ty: test::U,
    layout: Layout {
        size: Size(2 bytes),
        align: AbiAndPrefAlign {
            abi: Align(2 bytes),
            pref: Align(8 bytes),
        },
        abi: Scalar(
            Union {
                value: Int(
                    I8,
                    false,
                ),
            },
        ),
        fields: Union(
            2,
        ),
        largest_niche: None,
        variants: Single {
            index: 0,
        },
    },
}', compiler/rustc_ty_utils/src/layout_sanity_check.rs:72:21
stack backtrace:
   0:        0x1106b5291 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::ha861de675ede8b0c
   1:        0x110739448 - core::fmt::write::hda6b0e10b55724fb
   2:        0x1106c3f28 - std::io::Write::write_fmt::hdf206c4f52d49905
   3:        0x1106b5082 - std::sys_common::backtrace::print::h34f569a9c7a99a9f
   4:        0x1106ba405 - std::panicking::default_hook::{{closure}}::hda4eceb51b014a4b
   5:        0x1106ba1e7 - std::panicking::default_hook::he3b91b4302671d36
   6:        0x11fee8fa8 - rustc_driver[800c97195df9dd7a]::DEFAULT_HOOK::{closure#0}::{closure#0}
   7:        0x1106baac6 - std::panicking::rust_panic_with_hook::he8e29b5de756633a
   8:        0x1106c6dc3 - std::panicking::begin_panic_handler::{{closure}}::hdf4593bcdd333004
   9:        0x1106c6cf8 - std::sys_common::backtrace::__rust_end_short_backtrace::h574e2faa7e4a189e
  10:        0x1106ba4d8 - _rust_begin_unwind
  11:        0x110756ca3 - core::panicking::panic_fmt::h852bdf3f14372e73
  12:        0x110738325 - core::panicking::assert_failed_inner::h6aa04f268f2607ae
  13:        0x124f7363e - core[63810368375d8c35]::panicking::assert_failed::<rustc_target[44d477e4461259e2]::abi::Size, rustc_target[44d477e4461259e2]::abi::Size>
  14:        0x122730731 - rustc_ty_utils[335bf625919b7879]::layout_sanity_check::sanity_check_layout
  15:        0x1226e6341 - rustc_ty_utils[335bf625919b7879]::layout::layout_of
  16:        0x123b77537 - rustc_query_system[9c2b8b59a29958f0]::query::plumbing::get_query::<rustc_query_impl[e3f63d70ae94933f]::queries::layout_of, rustc_query_impl[e3f63d70ae94933f]::plumbing::QueryCtxt>
  17:        0x123e5c721 - <rustc_query_impl[e3f63d70ae94933f]::Queries as rustc_middle[8a1cca0694b55532]::ty::query::QueryEngine>::layout_of
  18:        0x122702dfb - <rustc_middle[8a1cca0694b55532]::ty::layout::LayoutCx<rustc_middle[8a1cca0694b55532]::ty::context::TyCtxt> as rustc_middle[8a1cca0694b55532]::ty::layout::LayoutOf>::layout_of
  19:        0x122701c71 - <core[63810368375d8c35]::iter::adapters::map::Map<core[63810368375d8c35]::slice::iter::Iter<rustc_middle[8a1cca0694b55532]::ty::FieldDef>, rustc_ty_utils[335bf625919b7879]::layout::layout_of_uncached::{closure#5}::{closure#0}> as core[63810368375d8c35]::iter::traits::iterator::Iterator>::try_fold::<(), <core[63810368375d8c35]::iter::adapters::GenericShunt<core[63810368375d8c35]::iter::adapters::map::Map<core[63810368375d8c35]::slice::iter::Iter<rustc_middle[8a1cca0694b55532]::ty::FieldDef>, rustc_ty_utils[335bf625919b7879]::layout::layout_of_uncached::{closure#5}::{closure#0}>, core[63810368375d8c35]::result::Result<core[63810368375d8c35]::convert::Infallible, rustc_middle[8a1cca0694b55532]::ty::layout::LayoutError>> as core[63810368375d8c35]::iter::traits::iterator::Iterator>::try_fold<(), core[63810368375d8c35]::iter::traits::iterator::Iterator::try_for_each::call<rustc_target[44d477e4461259e2]::abi::TyAndLayout<rustc_middle[8a1cca0694b55532]::ty::Ty>, core[63810368375d8c35]::ops::control_flow::ControlFlow<rustc_target[44d477e4461259e2]::abi::TyAndLayout<rustc_middle[8a1cca0694b55532]::ty::Ty>>, core[63810368375d8c35]::ops::control_flow::ControlFlow<rustc_target[44d477e4461259e2]::abi::TyAndLayout<rustc_middle[8a1cca0694b55532]::ty::Ty>>::Break>::{closure#0}, core[63810368375d8c35]::ops::control_flow::ControlFlow<rustc_target[44d477e4461259e2]::abi::TyAndLayout<rustc_middle[8a1cca0694b55532]::ty::Ty>>>::{closure#0}, core[63810368375d8c35]::ops::control_flow::ControlFlow<core[63810368375d8c35]::ops::control_flow::ControlFlow<rustc_target[44d477e4461259e2]::abi::TyAndLayout<rustc_middle[8a1cca0694b55532]::ty::Ty>>>>
  20:        0x1226cea5c - <core[63810368375d8c35]::iter::adapters::GenericShunt<core[63810368375d8c35]::iter::adapters::map::Map<core[63810368375d8c35]::slice::iter::Iter<rustc_middle[8a1cca0694b55532]::ty::FieldDef>, rustc_ty_utils[335bf625919b7879]::layout::layout_of_uncached::{closure#5}::{closure#0}>, core[63810368375d8c35]::result::Result<core[63810368375d8c35]::convert::Infallible, rustc_middle[8a1cca0694b55532]::ty::layout::LayoutError>> as core[63810368375d8c35]::iter::traits::iterator::Iterator>::next
  21:        0x12273929e - <alloc[9c4954bf8315fe26]::vec::Vec<rustc_target[44d477e4461259e2]::abi::TyAndLayout<rustc_middle[8a1cca0694b55532]::ty::Ty>> as alloc[9c4954bf8315fe26]::vec::spec_from_iter::SpecFromIter<rustc_target[44d477e4461259e2]::abi::TyAndLayout<rustc_middle[8a1cca0694b55532]::ty::Ty>, core[63810368375d8c35]::iter::adapters::GenericShunt<core[63810368375d8c35]::iter::adapters::map::Map<core[63810368375d8c35]::slice::iter::Iter<rustc_middle[8a1cca0694b55532]::ty::FieldDef>, rustc_ty_utils[335bf625919b7879]::layout::layout_of_uncached::{closure#5}::{closure#0}>, core[63810368375d8c35]::result::Result<core[63810368375d8c35]::convert::Infallible, rustc_middle[8a1cca0694b55532]::ty::layout::LayoutError>>>>::from_iter
  22:        0x1226ce089 - core[63810368375d8c35]::iter::adapters::try_process::<core[63810368375d8c35]::iter::adapters::map::Map<core[63810368375d8c35]::slice::iter::Iter<rustc_middle[8a1cca0694b55532]::ty::FieldDef>, rustc_ty_utils[335bf625919b7879]::layout::layout_of_uncached::{closure#5}::{closure#0}>, rustc_target[44d477e4461259e2]::abi::TyAndLayout<rustc_middle[8a1cca0694b55532]::ty::Ty>, core[63810368375d8c35]::result::Result<core[63810368375d8c35]::convert::Infallible, rustc_middle[8a1cca0694b55532]::ty::layout::LayoutError>, <core[63810368375d8c35]::result::Result<alloc[9c4954bf8315fe26]::vec::Vec<rustc_target[44d477e4461259e2]::abi::TyAndLayout<rustc_middle[8a1cca0694b55532]::ty::Ty>>, rustc_middle[8a1cca0694b55532]::ty::layout::LayoutError> as core[63810368375d8c35]::iter::traits::collect::FromIterator<core[63810368375d8c35]::result::Result<rustc_target[44d477e4461259e2]::abi::TyAndLayout<rustc_middle[8a1cca0694b55532]::ty::Ty>, rustc_middle[8a1cca0694b55532]::ty::layout::LayoutError>>>::from_iter<core[63810368375d8c35]::iter::adapters::map::Map<core[63810368375d8c35]::slice::iter::Iter<rustc_middle[8a1cca0694b55532]::ty::FieldDef>, rustc_ty_utils[335bf625919b7879]::layout::layout_of_uncached::{closure#5}::{closure#0}>>::{closure#0}, alloc[9c4954bf8315fe26]::vec::Vec<rustc_target[44d477e4461259e2]::abi::TyAndLayout<rustc_middle[8a1cca0694b55532]::ty::Ty>>>
  23:        0x122701b61 - <core[63810368375d8c35]::iter::adapters::map::Map<core[63810368375d8c35]::slice::iter::Iter<rustc_middle[8a1cca0694b55532]::ty::VariantDef>, rustc_ty_utils[335bf625919b7879]::layout::layout_of_uncached::{closure#5}> as core[63810368375d8c35]::iter::traits::iterator::Iterator>::try_fold::<(), <core[63810368375d8c35]::iter::adapters::GenericShunt<core[63810368375d8c35]::iter::adapters::map::Map<core[63810368375d8c35]::slice::iter::Iter<rustc_middle[8a1cca0694b55532]::ty::VariantDef>, rustc_ty_utils[335bf625919b7879]::layout::layout_of_uncached::{closure#5}>, core[63810368375d8c35]::result::Result<core[63810368375d8c35]::convert::Infallible, rustc_middle[8a1cca0694b55532]::ty::layout::LayoutError>> as core[63810368375d8c35]::iter::traits::iterator::Iterator>::try_fold<(), core[63810368375d8c35]::iter::traits::iterator::Iterator::try_for_each::call<alloc[9c4954bf8315fe26]::vec::Vec<rustc_target[44d477e4461259e2]::abi::TyAndLayout<rustc_middle[8a1cca0694b55532]::ty::Ty>>, core[63810368375d8c35]::ops::control_flow::ControlFlow<alloc[9c4954bf8315fe26]::vec::Vec<rustc_target[44d477e4461259e2]::abi::TyAndLayout<rustc_middle[8a1cca0694b55532]::ty::Ty>>>, core[63810368375d8c35]::ops::control_flow::ControlFlow<alloc[9c4954bf8315fe26]::vec::Vec<rustc_target[44d477e4461259e2]::abi::TyAndLayout<rustc_middle[8a1cca0694b55532]::ty::Ty>>>::Break>::{closure#0}, core[63810368375d8c35]::ops::control_flow::ControlFlow<alloc[9c4954bf8315fe26]::vec::Vec<rustc_target[44d477e4461259e2]::abi::TyAndLayout<rustc_middle[8a1cca0694b55532]::ty::Ty>>>>::{closure#0}, core[63810368375d8c35]::ops::control_flow::ControlFlow<core[63810368375d8c35]::ops::control_flow::ControlFlow<alloc[9c4954bf8315fe26]::vec::Vec<rustc_target[44d477e4461259e2]::abi::TyAndLayout<rustc_middle[8a1cca0694b55532]::ty::Ty>>>>>
  24:        0x1226ce9bd - <core[63810368375d8c35]::iter::adapters::GenericShunt<core[63810368375d8c35]::iter::adapters::map::Map<core[63810368375d8c35]::slice::iter::Iter<rustc_middle[8a1cca0694b55532]::ty::VariantDef>, rustc_ty_utils[335bf625919b7879]::layout::layout_of_uncached::{closure#5}>, core[63810368375d8c35]::result::Result<core[63810368375d8c35]::convert::Infallible, rustc_middle[8a1cca0694b55532]::ty::layout::LayoutError>> as core[63810368375d8c35]::iter::traits::iterator::Iterator>::next
  25:        0x1227387a8 - <alloc[9c4954bf8315fe26]::vec::Vec<alloc[9c4954bf8315fe26]::vec::Vec<rustc_target[44d477e4461259e2]::abi::TyAndLayout<rustc_middle[8a1cca0694b55532]::ty::Ty>>> as alloc[9c4954bf8315fe26]::vec::spec_from_iter::SpecFromIter<alloc[9c4954bf8315fe26]::vec::Vec<rustc_target[44d477e4461259e2]::abi::TyAndLayout<rustc_middle[8a1cca0694b55532]::ty::Ty>>, core[63810368375d8c35]::iter::adapters::GenericShunt<core[63810368375d8c35]::iter::adapters::map::Map<core[63810368375d8c35]::slice::iter::Iter<rustc_middle[8a1cca0694b55532]::ty::VariantDef>, rustc_ty_utils[335bf625919b7879]::layout::layout_of_uncached::{closure#5}>, core[63810368375d8c35]::result::Result<core[63810368375d8c35]::convert::Infallible, rustc_middle[8a1cca0694b55532]::ty::layout::LayoutError>>>>::from_iter
  26:        0x1226cdfb9 - core[63810368375d8c35]::iter::adapters::try_process::<core[63810368375d8c35]::iter::adapters::map::Map<core[63810368375d8c35]::slice::iter::Iter<rustc_middle[8a1cca0694b55532]::ty::VariantDef>, rustc_ty_utils[335bf625919b7879]::layout::layout_of_uncached::{closure#5}>, alloc[9c4954bf8315fe26]::vec::Vec<rustc_target[44d477e4461259e2]::abi::TyAndLayout<rustc_middle[8a1cca0694b55532]::ty::Ty>>, core[63810368375d8c35]::result::Result<core[63810368375d8c35]::convert::Infallible, rustc_middle[8a1cca0694b55532]::ty::layout::LayoutError>, <core[63810368375d8c35]::result::Result<rustc_index[79a26d8f822ca42d]::vec::IndexVec<rustc_target[44d477e4461259e2]::abi::VariantIdx, alloc[9c4954bf8315fe26]::vec::Vec<rustc_target[44d477e4461259e2]::abi::TyAndLayout<rustc_middle[8a1cca0694b55532]::ty::Ty>>>, rustc_middle[8a1cca0694b55532]::ty::layout::LayoutError> as core[63810368375d8c35]::iter::traits::collect::FromIterator<core[63810368375d8c35]::result::Result<alloc[9c4954bf8315fe26]::vec::Vec<rustc_target[44d477e4461259e2]::abi::TyAndLayout<rustc_middle[8a1cca0694b55532]::ty::Ty>>, rustc_middle[8a1cca0694b55532]::ty::layout::LayoutError>>>::from_iter<core[63810368375d8c35]::iter::adapters::map::Map<core[63810368375d8c35]::slice::iter::Iter<rustc_middle[8a1cca0694b55532]::ty::VariantDef>, rustc_ty_utils[335bf625919b7879]::layout::layout_of_uncached::{closure#5}>>::{closure#0}, rustc_index[79a26d8f822ca42d]::vec::IndexVec<rustc_target[44d477e4461259e2]::abi::VariantIdx, alloc[9c4954bf8315fe26]::vec::Vec<rustc_target[44d477e4461259e2]::abi::TyAndLayout<rustc_middle[8a1cca0694b55532]::ty::Ty>>>>
  27:        0x1226dc9cb - rustc_ty_utils[335bf625919b7879]::layout::layout_of_uncached
  28:        0x1226e6290 - rustc_ty_utils[335bf625919b7879]::layout::layout_of
  29:        0x123b77537 - rustc_query_system[9c2b8b59a29958f0]::query::plumbing::get_query::<rustc_query_impl[e3f63d70ae94933f]::queries::layout_of, rustc_query_impl[e3f63d70ae94933f]::plumbing::QueryCtxt>
  30:        0x123e5c721 - <rustc_query_impl[e3f63d70ae94933f]::Queries as rustc_middle[8a1cca0694b55532]::ty::query::QueryEngine>::layout_of
  31:        0x124854b58 - <rustc_transmute[32bd9b76539f9694]::layout::tree::rustc::LayoutSummary>::from_ty
  32:        0x124860ccd - <rustc_transmute[32bd9b76539f9694]::layout::tree::Tree<rustc_transmute[32bd9b76539f9694]::layout::rustc::Def, rustc_transmute[32bd9b76539f9694]::layout::rustc::Ref>>::from_ty
  33:        0x12486f9ae - <rustc_transmute[32bd9b76539f9694]::maybe_transmutable::MaybeTransmutableQuery<rustc_middle[8a1cca0694b55532]::ty::Ty, rustc_middle[8a1cca0694b55532]::ty::context::TyCtxt>>::map_layouts::<<rustc_transmute[32bd9b76539f9694]::maybe_transmutable::MaybeTransmutableQuery<rustc_middle[8a1cca0694b55532]::ty::Ty, rustc_middle[8a1cca0694b55532]::ty::context::TyCtxt>>::answer::{closure#0}, rustc_transmute[32bd9b76539f9694]::layout::tree::Tree<rustc_transmute[32bd9b76539f9694]::layout::rustc::Def, rustc_transmute[32bd9b76539f9694]::layout::rustc::Ref>>
  34:        0x124867f15 - <rustc_transmute[32bd9b76539f9694]::maybe_transmutable::MaybeTransmutableQuery<rustc_middle[8a1cca0694b55532]::ty::Ty, rustc_middle[8a1cca0694b55532]::ty::context::TyCtxt>>::answer
  35:        0x124864f01 - <rustc_transmute[32bd9b76539f9694]::rustc::TransmuteTypeEnv>::is_transmutable
  36:        0x1246a3416 - <rustc_trait_selection[96165f1221266323]::traits::select::SelectionContext>::confirm_candidate
  37:        0x1246674d5 - <rustc_infer[8f07edc99fd14f09]::infer::InferCtxt>::probe::<core[63810368375d8c35]::result::Result<rustc_middle[8a1cca0694b55532]::traits::select::EvaluationResult, rustc_middle[8a1cca0694b55532]::traits::select::OverflowError>, <rustc_trait_selection[96165f1221266323]::traits::select::SelectionContext>::evaluation_probe<<rustc_trait_selection[96165f1221266323]::traits::select::SelectionContext>::evaluate_candidate::{closure#0}::{closure#0}>::{closure#0}>
  38:        0x1247faed3 - <rustc_trait_selection[96165f1221266323]::traits::select::SelectionContext>::evaluation_probe::<<rustc_trait_selection[96165f1221266323]::traits::select::SelectionContext>::evaluate_candidate::{closure#0}::{closure#0}>
  39:        0x1246b438b - <rustc_trait_selection[96165f1221266323]::traits::select::SelectionContext>::evaluate_candidate
  40:        0x124699810 - <rustc_trait_selection[96165f1221266323]::traits::select::SelectionContext>::evaluate_stack
  41:        0x1247ad3a4 - <rustc_query_system[9c2b8b59a29958f0]::dep_graph::graph::DepGraph<rustc_middle[8a1cca0694b55532]::dep_graph::dep_node::DepKind>>::with_anon_task::<rustc_middle[8a1cca0694b55532]::ty::context::TyCtxt, <rustc_trait_selection[96165f1221266323]::traits::select::SelectionContext>::in_task<<rustc_trait_selection[96165f1221266323]::traits::select::SelectionContext>::evaluate_trait_predicate_recursively::{closure#0}::{closure#2}, core[63810368375d8c35]::result::Result<rustc_middle[8a1cca0694b55532]::traits::select::EvaluationResult, rustc_middle[8a1cca0694b55532]::traits::select::OverflowError>>::{closure#0}, core[63810368375d8c35]::result::Result<rustc_middle[8a1cca0694b55532]::traits::select::EvaluationResult, rustc_middle[8a1cca0694b55532]::traits::select::OverflowError>>
  42:        0x1247fb0cb - <rustc_trait_selection[96165f1221266323]::traits::select::SelectionContext>::in_task::<<rustc_trait_selection[96165f1221266323]::traits::select::SelectionContext>::evaluate_trait_predicate_recursively::{closure#0}::{closure#2}, core[63810368375d8c35]::result::Result<rustc_middle[8a1cca0694b55532]::traits::select::EvaluationResult, rustc_middle[8a1cca0694b55532]::traits::select::OverflowError>>
  43:        0x1246b210b - <rustc_trait_selection[96165f1221266323]::traits::select::SelectionContext>::evaluate_trait_predicate_recursively
  44:        0x1246af940 - <rustc_trait_selection[96165f1221266323]::traits::select::SelectionContext>::evaluate_predicate_recursively
  45:        0x124667f49 - <rustc_infer[8f07edc99fd14f09]::infer::InferCtxt>::probe::<core[63810368375d8c35]::result::Result<rustc_middle[8a1cca0694b55532]::traits::select::EvaluationResult, rustc_middle[8a1cca0694b55532]::traits::select::OverflowError>, <rustc_trait_selection[96165f1221266323]::traits::select::SelectionContext>::evaluation_probe<<rustc_trait_selection[96165f1221266323]::traits::select::SelectionContext>::evaluate_root_obligation::{closure#0}>::{closure#0}>
  46:        0x12469945f - <rustc_trait_selection[96165f1221266323]::traits::select::SelectionContext>::evaluate_root_obligation
  47:        0x1235a16ce - rustc_traits[16c39305a736ba01]::evaluate_obligation::evaluate_obligation
  48:        0x123ea5ae6 - <rustc_query_system[9c2b8b59a29958f0]::query::config::QueryVTable<rustc_query_impl[e3f63d70ae94933f]::plumbing::QueryCtxt, rustc_middle[8a1cca0694b55532]::infer::canonical::Canonical<rustc_middle[8a1cca0694b55532]::ty::ParamEnvAnd<rustc_middle[8a1cca0694b55532]::ty::Predicate>>, core[63810368375d8c35]::result::Result<rustc_middle[8a1cca0694b55532]::traits::select::EvaluationResult, rustc_middle[8a1cca0694b55532]::traits::select::OverflowError>>>::compute
  49:        0x123b3c971 - rustc_query_system[9c2b8b59a29958f0]::query::plumbing::get_query::<rustc_query_impl[e3f63d70ae94933f]::queries::evaluate_obligation, rustc_query_impl[e3f63d70ae94933f]::plumbing::QueryCtxt>
  50:        0x123e7f1a4 - <rustc_query_impl[e3f63d70ae94933f]::Queries as rustc_middle[8a1cca0694b55532]::ty::query::QueryEngine>::evaluate_obligation
  51:        0x124805917 - <rustc_infer[8f07edc99fd14f09]::infer::InferCtxt as rustc_trait_selection[96165f1221266323]::traits::query::evaluate_obligation::InferCtxtExt>::evaluate_obligation
  52:        0x124805a6f - <rustc_infer[8f07edc99fd14f09]::infer::InferCtxt as rustc_trait_selection[96165f1221266323]::traits::query::evaluate_obligation::InferCtxtExt>::evaluate_obligation_no_overflow
  53:        0x1247f64e8 - <rustc_trait_selection[96165f1221266323]::traits::fulfill::FulfillProcessor>::process_trait_obligation
  54:        0x1247f4e0f - <rustc_trait_selection[96165f1221266323]::traits::fulfill::FulfillProcessor as rustc_data_structures[8a51262431e07920]::obligation_forest::ObligationProcessor>::process_obligation
  55:        0x1246e69ed - <rustc_data_structures[8a51262431e07920]::obligation_forest::ObligationForest<rustc_trait_selection[96165f1221266323]::traits::fulfill::PendingPredicateObligation>>::process_obligations::<rustc_trait_selection[96165f1221266323]::traits::fulfill::FulfillProcessor>
  56:        0x1247f2e42 - <rustc_trait_selection[96165f1221266323]::traits::fulfill::FulfillmentContext as rustc_infer[8f07edc99fd14f09]::traits::engine::TraitEngine>::select_where_possible
  57:        0x1227b4e73 - <rustc_hir_typeck[5ebbf62125a398cb]::fn_ctxt::FnCtxt>::select_obligations_where_possible::<rustc_hir_typeck[5ebbf62125a398cb]::typeck_with_fallback<rustc_hir_typeck[5ebbf62125a398cb]::typeck_const_arg::{closure#0}>::{closure#1}::{closure#2}>
  58:        0x1228289ff - <rustc_hir_typeck[5ebbf62125a398cb]::fn_ctxt::FnCtxt>::check_argument_types
  59:        0x122807e58 - <rustc_hir_typeck[5ebbf62125a398cb]::fn_ctxt::FnCtxt>::confirm_builtin_call
  60:        0x1228058ad - <rustc_hir_typeck[5ebbf62125a398cb]::fn_ctxt::FnCtxt>::check_call
  61:        0x12286c65f - <rustc_hir_typeck[5ebbf62125a398cb]::fn_ctxt::FnCtxt>::check_expr_kind
  62:        0x12281564f - <rustc_hir_typeck[5ebbf62125a398cb]::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
  63:        0x12286b6e4 - <rustc_hir_typeck[5ebbf62125a398cb]::fn_ctxt::FnCtxt>::check_expr_with_expectation
  64:        0x12282ef02 - <rustc_hir_typeck[5ebbf62125a398cb]::fn_ctxt::FnCtxt>::check_stmt
  65:        0x1227b53df - <rustc_hir_typeck[5ebbf62125a398cb]::fn_ctxt::FnCtxt>::with_breakable_ctxt::<<rustc_hir_typeck[5ebbf62125a398cb]::fn_ctxt::FnCtxt>::check_block_with_expected::{closure#0}, ()>
  66:        0x12282f1e0 - <rustc_hir_typeck[5ebbf62125a398cb]::fn_ctxt::FnCtxt>::check_block_with_expected
  67:        0x12286ca41 - <rustc_hir_typeck[5ebbf62125a398cb]::fn_ctxt::FnCtxt>::check_expr_kind
  68:        0x12281564f - <rustc_hir_typeck[5ebbf62125a398cb]::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
  69:        0x12286b6e4 - <rustc_hir_typeck[5ebbf62125a398cb]::fn_ctxt::FnCtxt>::check_expr_with_expectation
  70:        0x122816997 - <rustc_hir_typeck[5ebbf62125a398cb]::fn_ctxt::FnCtxt>::check_return_expr
  71:        0x122777c47 - rustc_hir_typeck[5ebbf62125a398cb]::check::check_fn
  72:        0x1227c3710 - <rustc_hir_typeck[5ebbf62125a398cb]::inherited::InheritedBuilder>::enter::<rustc_hir_typeck[5ebbf62125a398cb]::typeck_with_fallback<rustc_hir_typeck[5ebbf62125a398cb]::typeck::{closure#0}>::{closure#1}, &rustc_middle[8a1cca0694b55532]::ty::context::TypeckResults>
  73:        0x1227c66c2 - rustc_hir_typeck[5ebbf62125a398cb]::typeck_with_fallback::<rustc_hir_typeck[5ebbf62125a398cb]::typeck::{closure#0}>
  74:        0x12292d3f9 - rustc_hir_typeck[5ebbf62125a398cb]::typeck
  75:        0x123a49bca - rustc_query_system[9c2b8b59a29958f0]::query::plumbing::try_execute_query::<rustc_query_impl[e3f63d70ae94933f]::plumbing::QueryCtxt, rustc_query_system[9c2b8b59a29958f0]::query::caches::DefaultCache<rustc_span[2af9326393a24b2a]::def_id::LocalDefId, &rustc_middle[8a1cca0694b55532]::ty::context::TypeckResults>>
  76:        0x123b75c7a - rustc_query_system[9c2b8b59a29958f0]::query::plumbing::get_query::<rustc_query_impl[e3f63d70ae94933f]::queries::typeck, rustc_query_impl[e3f63d70ae94933f]::plumbing::QueryCtxt>
  77:        0x123e4047f - <rustc_query_impl[e3f63d70ae94933f]::Queries as rustc_middle[8a1cca0694b55532]::ty::query::QueryEngine>::typeck
  78:        0x1228dd7df - <core[63810368375d8c35]::panic::unwind_safe::AssertUnwindSafe<rustc_data_structures[8a51262431e07920]::sync::par_for_each_in<&[rustc_span[2af9326393a24b2a]::def_id::LocalDefId], <rustc_middle[8a1cca0694b55532]::hir::map::Map>::par_body_owners<rustc_hir_typeck[5ebbf62125a398cb]::typeck_item_bodies::{closure#0}>::{closure#0}>::{closure#0}::{closure#0}> as core[63810368375d8c35]::ops::function::FnOnce<()>>::call_once
  79:        0x1227717e9 - std[6a7b9961a507fa09]::panicking::try::<(), core[63810368375d8c35]::panic::unwind_safe::AssertUnwindSafe<rustc_data_structures[8a51262431e07920]::sync::par_for_each_in<&[rustc_span[2af9326393a24b2a]::def_id::LocalDefId], <rustc_middle[8a1cca0694b55532]::hir::map::Map>::par_body_owners<rustc_hir_typeck[5ebbf62125a398cb]::typeck_item_bodies::{closure#0}>::{closure#0}>::{closure#0}::{closure#0}>>
  80:        0x12292e713 - rustc_data_structures[8a51262431e07920]::sync::par_for_each_in::<&[rustc_span[2af9326393a24b2a]::def_id::LocalDefId], <rustc_middle[8a1cca0694b55532]::hir::map::Map>::par_body_owners<rustc_hir_typeck[5ebbf62125a398cb]::typeck_item_bodies::{closure#0}>::{closure#0}>
  81:        0x12292d22f - rustc_hir_typeck[5ebbf62125a398cb]::typeck_item_bodies
  82:        0x123a9efe3 - rustc_query_system[9c2b8b59a29958f0]::query::plumbing::try_execute_query::<rustc_query_impl[e3f63d70ae94933f]::plumbing::QueryCtxt, rustc_query_system[9c2b8b59a29958f0]::query::caches::DefaultCache<(), ()>>
  83:        0x123b3b779 - rustc_query_system[9c2b8b59a29958f0]::query::plumbing::get_query::<rustc_query_impl[e3f63d70ae94933f]::queries::typeck_item_bodies, rustc_query_impl[e3f63d70ae94933f]::plumbing::QueryCtxt>
  84:        0x123e3fe17 - <rustc_query_impl[e3f63d70ae94933f]::Queries as rustc_middle[8a1cca0694b55532]::ty::query::QueryEngine>::typeck_item_bodies
  85:        0x122aa37a8 - <rustc_session[3422556dcb6df88d]::session::Session>::time::<(), rustc_hir_analysis[e4fb2be97854ccf3]::check_crate::{closure#7}>
  86:        0x122a53f7e - rustc_hir_analysis[e4fb2be97854ccf3]::check_crate
  87:        0x120093e6a - rustc_interface[2b9f011c4a1d6882]::passes::analysis
  88:        0x123a935cd - rustc_query_system[9c2b8b59a29958f0]::query::plumbing::try_execute_query::<rustc_query_impl[e3f63d70ae94933f]::plumbing::QueryCtxt, rustc_query_system[9c2b8b59a29958f0]::query::caches::DefaultCache<(), core[63810368375d8c35]::result::Result<(), rustc_errors[8c17e79fb1f0a5e4]::ErrorGuaranteed>>>
  89:        0x123b76029 - rustc_query_system[9c2b8b59a29958f0]::query::plumbing::get_query::<rustc_query_impl[e3f63d70ae94933f]::queries::analysis, rustc_query_impl[e3f63d70ae94933f]::plumbing::QueryCtxt>
  90:        0x123e1be17 - <rustc_query_impl[e3f63d70ae94933f]::Queries as rustc_middle[8a1cca0694b55532]::ty::query::QueryEngine>::analysis
  91:        0x11ff5f658 - <rustc_interface[2b9f011c4a1d6882]::passes::QueryContext>::enter::<rustc_driver[800c97195df9dd7a]::run_compiler::{closure#1}::{closure#2}::{closure#3}, core[63810368375d8c35]::result::Result<(), rustc_errors[8c17e79fb1f0a5e4]::ErrorGuaranteed>>
  92:        0x11ff52ff8 - <rustc_interface[2b9f011c4a1d6882]::interface::Compiler>::enter::<rustc_driver[800c97195df9dd7a]::run_compiler::{closure#1}::{closure#2}, core[63810368375d8c35]::result::Result<core[63810368375d8c35]::option::Option<rustc_interface[2b9f011c4a1d6882]::queries::Linker>, rustc_errors[8c17e79fb1f0a5e4]::ErrorGuaranteed>>
  93:        0x11ff4a7db - rustc_span[2af9326393a24b2a]::with_source_map::<core[63810368375d8c35]::result::Result<(), rustc_errors[8c17e79fb1f0a5e4]::ErrorGuaranteed>, rustc_interface[2b9f011c4a1d6882]::interface::run_compiler<core[63810368375d8c35]::result::Result<(), rustc_errors[8c17e79fb1f0a5e4]::ErrorGuaranteed>, rustc_driver[800c97195df9dd7a]::run_compiler::{closure#1}>::{closure#0}::{closure#1}>
  94:        0x11ff5109a - <scoped_tls[a4e3500caacc884c]::ScopedKey<rustc_span[2af9326393a24b2a]::SessionGlobals>>::set::<rustc_interface[2b9f011c4a1d6882]::interface::run_compiler<core[63810368375d8c35]::result::Result<(), rustc_errors[8c17e79fb1f0a5e4]::ErrorGuaranteed>, rustc_driver[800c97195df9dd7a]::run_compiler::{closure#1}>::{closure#0}, core[63810368375d8c35]::result::Result<(), rustc_errors[8c17e79fb1f0a5e4]::ErrorGuaranteed>>
  95:        0x11ff6b260 - std[6a7b9961a507fa09]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[2b9f011c4a1d6882]::util::run_in_thread_pool_with_globals<rustc_interface[2b9f011c4a1d6882]::interface::run_compiler<core[63810368375d8c35]::result::Result<(), rustc_errors[8c17e79fb1f0a5e4]::ErrorGuaranteed>, rustc_driver[800c97195df9dd7a]::run_compiler::{closure#1}>::{closure#0}, core[63810368375d8c35]::result::Result<(), rustc_errors[8c17e79fb1f0a5e4]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[63810368375d8c35]::result::Result<(), rustc_errors[8c17e79fb1f0a5e4]::ErrorGuaranteed>>
  96:        0x11ff4550d - std[6a7b9961a507fa09]::panicking::try::<core[63810368375d8c35]::result::Result<(), rustc_errors[8c17e79fb1f0a5e4]::ErrorGuaranteed>, core[63810368375d8c35]::panic::unwind_safe::AssertUnwindSafe<<std[6a7b9961a507fa09]::thread::Builder>::spawn_unchecked_<rustc_interface[2b9f011c4a1d6882]::util::run_in_thread_pool_with_globals<rustc_interface[2b9f011c4a1d6882]::interface::run_compiler<core[63810368375d8c35]::result::Result<(), rustc_errors[8c17e79fb1f0a5e4]::ErrorGuaranteed>, rustc_driver[800c97195df9dd7a]::run_compiler::{closure#1}>::{closure#0}, core[63810368375d8c35]::result::Result<(), rustc_errors[8c17e79fb1f0a5e4]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[63810368375d8c35]::result::Result<(), rustc_errors[8c17e79fb1f0a5e4]::ErrorGuaranteed>>::{closure#1}::{closure#0}>>
  97:        0x11ff6cd90 - <<std[6a7b9961a507fa09]::thread::Builder>::spawn_unchecked_<rustc_interface[2b9f011c4a1d6882]::util::run_in_thread_pool_with_globals<rustc_interface[2b9f011c4a1d6882]::interface::run_compiler<core[63810368375d8c35]::result::Result<(), rustc_errors[8c17e79fb1f0a5e4]::ErrorGuaranteed>, rustc_driver[800c97195df9dd7a]::run_compiler::{closure#1}>::{closure#0}, core[63810368375d8c35]::result::Result<(), rustc_errors[8c17e79fb1f0a5e4]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[63810368375d8c35]::result::Result<(), rustc_errors[8c17e79fb1f0a5e4]::ErrorGuaranteed>>::{closure#1} as core[63810368375d8c35]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  98:        0x110692adb - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hdf7bfd1e0a7b9c83
  99:        0x1106a7d5f - std::sys::unix::thread::Thread::new::thread_start::h5ad5524ac09352ab
 100:     0x7ff81000f4e1 - __pthread_start

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.66.0-dev running on x86_64-apple-darwin

query stack during panic:
#0 [layout_of] computing layout of `test::U`
#1 [layout_of] computing layout of `test::S`
#2 [evaluate_obligation] evaluating trait selection obligation `u128: core::mem::transmutability::BikeshedIntrinsicFrom<test::S, assert::Context, core::mem::transmutability::Assume { alignment: false, lifetimes: false, safety: false, validity: false }>`
#3 [typeck] type-checking `test`
#4 [typeck_item_bodies] type-checking all item bodies
#5 [analysis] running analysis passes on this crate
end of query stack
```

</p>
</details>

### Version

Built from 44fcfb0a9606fa08ea293a71f2e6d470227ef9df (master some time yesterday, 2022-10-26)

<details><summary>config.toml</summary>
<p>

```toml
# Includes one of the default files in src/bootstrap/defaults
profile = "compiler"
changelog-seen = 2

[llvm]
download-ci-llvm = true     # Download a pre-built LLVM?
assertions = true           # LLVM assertions on?

[rust]
incremental = true          # Build rustc with incremental compilation?
debug-assertions = true
```

</p>
</details>

CC @jswrenn, who might understand the `BikeshedIntrinsicFrom` parts of the testcase

CC @RalfJung, who [added the assertion](https://github.com/rust-lang/rust/commit/e0d5c19dbbecaabaa4f0fe802e8e4138178f38f9)

### LINKED ISSUE #104802: ICE with packed union: "alignment mismatch between ABI and layout"
Found with a [modified fuzz-rustc](https://github.com/jruderman/fuzz-rustc)

### Code

```Rust
#[repr(packed(1))]
union U {
    x: u32,
}

const B: U = U { x: 0 };

fn main() {}
```

### Error output with debug assertions enabled

alignment mismatch between ABI and layout in TyAndLayout { ... }, [compiler/rustc_ty_utils/src/layout_sanity_check.rs:77](https://github.com/rust-lang/rust/blob/604d52108e9272d75618ab6a7b5eb006857fce52/compiler/rustc_ty_utils/src/layout_sanity_check.rs#L77)

<details><summary><strong>Full output including backtrace</strong></summary>
<p>

```
thread 'rustc' panicked at 'assertion failed: `(left == right)`
  left: `Align(1 bytes)`,
 right: `Align(4 bytes)`: alignment mismatch between ABI and layout in TyAndLayout {
    ty: U,
    layout: Layout {
        size: Size(4 bytes),
        align: AbiAndPrefAlign {
            abi: Align(1 bytes),
            pref: Align(1 bytes),
        },
        abi: Scalar(
            Union {
                value: Int(
                    I32,
                    false,
                ),
            },
        ),
        fields: Union(
            1,
        ),
        largest_niche: None,
        variants: Single {
            index: 0,
        },
    },
}', compiler/rustc_ty_utils/src/layout_sanity_check.rs:77:21
stack backtrace:
   0:        0x10f448f21 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hcf5aac4d53eab431
   1:        0x10f506818 - core::fmt::write::hed31846cddb4e13c
   2:        0x10f4abec8 - std::io::Write::write_fmt::h01887004f97cedc7
   3:        0x10f448d12 - std::sys_common::backtrace::print::h2141c6543b5865e5
   4:        0x10f4ace45 - std::panicking::default_hook::{{closure}}::hfe93a58a10a72158
   5:        0x10f4acc2e - std::panicking::default_hook::hafca10424d622dfb
   6:        0x123176708 - rustc_driver[bfe6130b33d7dd9c]::DEFAULT_HOOK::{closure#0}::{closure#0}
   7:        0x10f4ad636 - std::panicking::rust_panic_with_hook::hafe3bb82e805c420
   8:        0x10f49a173 - std::panicking::begin_panic_handler::{{closure}}::h2797e20f8763cc3a
   9:        0x10f49a0a8 - std::sys_common::backtrace::__rust_end_short_backtrace::hde7c42687ab67a11
  10:        0x10f4acf18 - _rust_begin_unwind
  11:        0x10f52b443 - core::panicking::panic_fmt::h7ec57a9a63e6db71
  12:        0x10f51a125 - core::panicking::assert_failed_inner::hb961e0acdeb20af8
  13:        0x12860ee6e - core[95bb6d661b676f4d]::panicking::assert_failed::<rustc_target[b76a068d308f1d4a]::abi::Align, rustc_target[b76a068d308f1d4a]::abi::Align>
  14:        0x12594e82a - rustc_ty_utils[eaca7fb7b7a0869]::layout_sanity_check::sanity_check_layout
  15:        0x1259669c0 - rustc_ty_utils[eaca7fb7b7a0869]::layout::layout_of
  16:        0x127303ac1 - rustc_query_system[2c5b580ea3a12206]::query::plumbing::get_query::<rustc_query_impl[e5b327371ad57e64]::queries::layout_of, rustc_query_impl[e5b327371ad57e64]::plumbing::QueryCtxt>
  17:        0x126e9bcc1 - <rustc_query_impl[e5b327371ad57e64]::Queries as rustc_middle[42f89e9b8d5efbfa]::ty::query::QueryEngine>::layout_of
  18:        0x126b79f9e - rustc_const_eval[d19bca16da1661a0]::const_eval::eval_queries::eval_to_allocation_raw_provider
  19:        0x1272d223a - rustc_query_system[2c5b580ea3a12206]::query::plumbing::get_query::<rustc_query_impl[e5b327371ad57e64]::queries::eval_to_allocation_raw, rustc_query_impl[e5b327371ad57e64]::plumbing::QueryCtxt>
  20:        0x126e84f6c - <rustc_query_impl[e5b327371ad57e64]::Queries as rustc_middle[42f89e9b8d5efbfa]::ty::query::QueryEngine>::eval_to_allocation_raw
  21:        0x126b77d1f - rustc_const_eval[d19bca16da1661a0]::const_eval::eval_queries::eval_to_const_value_raw_provider
  22:        0x1272da487 - rustc_query_system[2c5b580ea3a12206]::query::plumbing::get_query::<rustc_query_impl[e5b327371ad57e64]::queries::eval_to_const_value_raw, rustc_query_impl[e5b327371ad57e64]::plumbing::QueryCtxt>
  23:        0x126e8568c - <rustc_query_impl[e5b327371ad57e64]::Queries as rustc_middle[42f89e9b8d5efbfa]::ty::query::QueryEngine>::eval_to_const_value_raw
  24:        0x126b778b7 - rustc_const_eval[d19bca16da1661a0]::const_eval::eval_queries::eval_to_const_value_raw_provider
  25:        0x1272da487 - rustc_query_system[2c5b580ea3a12206]::query::plumbing::get_query::<rustc_query_impl[e5b327371ad57e64]::queries::eval_to_const_value_raw, rustc_query_impl[e5b327371ad57e64]::plumbing::QueryCtxt>
  26:        0x126e8568c - <rustc_query_impl[e5b327371ad57e64]::Queries as rustc_middle[42f89e9b8d5efbfa]::ty::query::QueryEngine>::eval_to_const_value_raw
  27:        0x1281462c9 - <rustc_middle[42f89e9b8d5efbfa]::ty::query::TyCtxtEnsure>::const_eval_poly
  28:        0x127ac10f3 - <rustc_lint[8943d723f788f8fc]::BuiltinCombinedModuleLateLintPass as rustc_lint[8943d723f788f8fc]::passes::LateLintPass>::check_item
  29:        0x127ad9f0c - <rustc_lint[8943d723f788f8fc]::late::LateContextAndPass<rustc_lint[8943d723f788f8fc]::BuiltinCombinedModuleLateLintPass> as rustc_hir[112137b1c6e29e52]::intravisit::Visitor>::visit_nested_item
  30:        0x127b0ffbc - rustc_hir[112137b1c6e29e52]::intravisit::walk_mod::<rustc_lint[8943d723f788f8fc]::late::LateContextAndPass<rustc_lint[8943d723f788f8fc]::BuiltinCombinedModuleLateLintPass>>
  31:        0x127adf103 - rustc_lint[8943d723f788f8fc]::late::late_lint_mod::<rustc_lint[8943d723f788f8fc]::BuiltinCombinedModuleLateLintPass>
  32:        0x127abb610 - rustc_lint[8943d723f788f8fc]::lint_mod
  33:        0x1271cff1e - rustc_query_system[2c5b580ea3a12206]::query::plumbing::try_execute_query::<rustc_query_impl[e5b327371ad57e64]::plumbing::QueryCtxt, rustc_query_system[2c5b580ea3a12206]::query::caches::DefaultCache<rustc_span[7d7aa17bf13bea16]::def_id::LocalDefId, ()>>
  34:        0x127302a83 - rustc_query_system[2c5b580ea3a12206]::query::plumbing::get_query::<rustc_query_impl[e5b327371ad57e64]::queries::lint_mod, rustc_query_impl[e5b327371ad57e64]::plumbing::QueryCtxt>
  35:        0x126e7932f - <rustc_query_impl[e5b327371ad57e64]::Queries as rustc_middle[42f89e9b8d5efbfa]::ty::query::QueryEngine>::lint_mod
  36:        0x1232a4cbd - <core[95bb6d661b676f4d]::panic::unwind_safe::AssertUnwindSafe<rustc_data_structures[6f5f4852afd2a743]::sync::par_for_each_in<&[rustc_hir[112137b1c6e29e52]::hir_id::OwnerId], <rustc_middle[42f89e9b8d5efbfa]::hir::map::Map>::par_for_each_module<rustc_lint[8943d723f788f8fc]::late::check_crate<rustc_lint[8943d723f788f8fc]::BuiltinCombinedLateLintPass, rustc_interface[fb7297f02cc960f4]::passes::analysis::{closure#5}::{closure#1}::{closure#2}::{closure#0}::{closure#0}>::{closure#1}::{closure#0}::{closure#0}>::{closure#0}>::{closure#0}::{closure#0}> as core[95bb6d661b676f4d]::ops::function::FnOnce<()>>::call_once
  37:        0x123254040 - std[e4564114326e8c6]::panicking::try::<(), core[95bb6d661b676f4d]::panic::unwind_safe::AssertUnwindSafe<rustc_data_structures[6f5f4852afd2a743]::sync::par_for_each_in<&[rustc_hir[112137b1c6e29e52]::hir_id::OwnerId], <rustc_middle[42f89e9b8d5efbfa]::hir::map::Map>::par_for_each_module<rustc_lint[8943d723f788f8fc]::late::check_crate<rustc_lint[8943d723f788f8fc]::BuiltinCombinedLateLintPass, rustc_interface[fb7297f02cc960f4]::passes::analysis::{closure#5}::{closure#1}::{closure#2}::{closure#0}::{closure#0}>::{closure#1}::{closure#0}::{closure#0}>::{closure#0}>::{closure#0}::{closure#0}>>
  38:        0x123239183 - rustc_data_structures[6f5f4852afd2a743]::sync::par_for_each_in::<&[rustc_hir[112137b1c6e29e52]::hir_id::OwnerId], <rustc_middle[42f89e9b8d5efbfa]::hir::map::Map>::par_for_each_module<rustc_lint[8943d723f788f8fc]::late::check_crate<rustc_lint[8943d723f788f8fc]::BuiltinCombinedLateLintPass, rustc_interface[fb7297f02cc960f4]::passes::analysis::{closure#5}::{closure#1}::{closure#2}::{closure#0}::{closure#0}>::{closure#1}::{closure#0}::{closure#0}>::{closure#0}>
  39:        0x1232453ea - <rustc_session[6f273c4587eb1b50]::session::Session>::time::<(), rustc_lint[8943d723f788f8fc]::late::check_crate<rustc_lint[8943d723f788f8fc]::BuiltinCombinedLateLintPass, rustc_interface[fb7297f02cc960f4]::passes::analysis::{closure#5}::{closure#1}::{closure#2}::{closure#0}::{closure#0}>::{closure#1}::{closure#0}>
  40:        0x1232454cf - <rustc_session[6f273c4587eb1b50]::session::Session>::time::<(), rustc_interface[fb7297f02cc960f4]::passes::analysis::{closure#5}::{closure#1}::{closure#2}::{closure#0}>
  41:        0x12325433c - std[e4564114326e8c6]::panicking::try::<(), core[95bb6d661b676f4d]::panic::unwind_safe::AssertUnwindSafe<rustc_interface[fb7297f02cc960f4]::passes::analysis::{closure#5}::{closure#1}::{closure#2}>>
  42:        0x1232a5b50 - <core[95bb6d661b676f4d]::panic::unwind_safe::AssertUnwindSafe<rustc_interface[fb7297f02cc960f4]::passes::analysis::{closure#5}::{closure#1}> as core[95bb6d661b676f4d]::ops::function::FnOnce<()>>::call_once
  43:        0x1232545f0 - std[e4564114326e8c6]::panicking::try::<(), core[95bb6d661b676f4d]::panic::unwind_safe::AssertUnwindSafe<rustc_interface[fb7297f02cc960f4]::passes::analysis::{closure#5}::{closure#1}>>
  44:        0x123246d79 - <rustc_session[6f273c4587eb1b50]::session::Session>::time::<(), rustc_interface[fb7297f02cc960f4]::passes::analysis::{closure#5}>
  45:        0x1232a131c - rustc_interface[fb7297f02cc960f4]::passes::analysis
  46:        0x12721595f - rustc_query_system[2c5b580ea3a12206]::query::plumbing::try_execute_query::<rustc_query_impl[e5b327371ad57e64]::plumbing::QueryCtxt, rustc_query_system[2c5b580ea3a12206]::query::caches::DefaultCache<(), core[95bb6d661b676f4d]::result::Result<(), rustc_errors[48ad5d4ad3523473]::ErrorGuaranteed>>>
  47:        0x127302589 - rustc_query_system[2c5b580ea3a12206]::query::plumbing::get_query::<rustc_query_impl[e5b327371ad57e64]::queries::analysis, rustc_query_impl[e5b327371ad57e64]::plumbing::QueryCtxt>
  48:        0x126e5b3b7 - <rustc_query_impl[e5b327371ad57e64]::Queries as rustc_middle[42f89e9b8d5efbfa]::ty::query::QueryEngine>::analysis
  49:        0x12316a1db - <rustc_interface[fb7297f02cc960f4]::passes::QueryContext>::enter::<rustc_driver[bfe6130b33d7dd9c]::run_compiler::{closure#1}::{closure#2}::{closure#3}, core[95bb6d661b676f4d]::result::Result<(), rustc_errors[48ad5d4ad3523473]::ErrorGuaranteed>>
  50:        0x123164688 - <rustc_interface[fb7297f02cc960f4]::interface::Compiler>::enter::<rustc_driver[bfe6130b33d7dd9c]::run_compiler::{closure#1}::{closure#2}, core[95bb6d661b676f4d]::result::Result<core[95bb6d661b676f4d]::option::Option<rustc_interface[fb7297f02cc960f4]::queries::Linker>, rustc_errors[48ad5d4ad3523473]::ErrorGuaranteed>>
  51:        0x1231622bb - rustc_span[7d7aa17bf13bea16]::with_source_map::<core[95bb6d661b676f4d]::result::Result<(), rustc_errors[48ad5d4ad3523473]::ErrorGuaranteed>, rustc_interface[fb7297f02cc960f4]::interface::run_compiler<core[95bb6d661b676f4d]::result::Result<(), rustc_errors[48ad5d4ad3523473]::ErrorGuaranteed>, rustc_driver[bfe6130b33d7dd9c]::run_compiler::{closure#1}>::{closure#0}::{closure#1}>
  52:        0x123138acc - <scoped_tls[c451c38e2ed76225]::ScopedKey<rustc_span[7d7aa17bf13bea16]::SessionGlobals>>::set::<rustc_interface[fb7297f02cc960f4]::interface::run_compiler<core[95bb6d661b676f4d]::result::Result<(), rustc_errors[48ad5d4ad3523473]::ErrorGuaranteed>, rustc_driver[bfe6130b33d7dd9c]::run_compiler::{closure#1}>::{closure#0}, core[95bb6d661b676f4d]::result::Result<(), rustc_errors[48ad5d4ad3523473]::ErrorGuaranteed>>
  53:        0x12312f240 - std[e4564114326e8c6]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[fb7297f02cc960f4]::util::run_in_thread_pool_with_globals<rustc_interface[fb7297f02cc960f4]::interface::run_compiler<core[95bb6d661b676f4d]::result::Result<(), rustc_errors[48ad5d4ad3523473]::ErrorGuaranteed>, rustc_driver[bfe6130b33d7dd9c]::run_compiler::{closure#1}>::{closure#0}, core[95bb6d661b676f4d]::result::Result<(), rustc_errors[48ad5d4ad3523473]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[95bb6d661b676f4d]::result::Result<(), rustc_errors[48ad5d4ad3523473]::ErrorGuaranteed>>
  54:        0x123161d90 - std[e4564114326e8c6]::panicking::try::<core[95bb6d661b676f4d]::result::Result<(), rustc_errors[48ad5d4ad3523473]::ErrorGuaranteed>, core[95bb6d661b676f4d]::panic::unwind_safe::AssertUnwindSafe<<std[e4564114326e8c6]::thread::Builder>::spawn_unchecked_<rustc_interface[fb7297f02cc960f4]::util::run_in_thread_pool_with_globals<rustc_interface[fb7297f02cc960f4]::interface::run_compiler<core[95bb6d661b676f4d]::result::Result<(), rustc_errors[48ad5d4ad3523473]::ErrorGuaranteed>, rustc_driver[bfe6130b33d7dd9c]::run_compiler::{closure#1}>::{closure#0}, core[95bb6d661b676f4d]::result::Result<(), rustc_errors[48ad5d4ad3523473]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[95bb6d661b676f4d]::result::Result<(), rustc_errors[48ad5d4ad3523473]::ErrorGuaranteed>>::{closure#1}::{closure#0}>>
  55:        0x12315d141 - <<std[e4564114326e8c6]::thread::Builder>::spawn_unchecked_<rustc_interface[fb7297f02cc960f4]::util::run_in_thread_pool_with_globals<rustc_interface[fb7297f02cc960f4]::interface::run_compiler<core[95bb6d661b676f4d]::result::Result<(), rustc_errors[48ad5d4ad3523473]::ErrorGuaranteed>, rustc_driver[bfe6130b33d7dd9c]::run_compiler::{closure#1}>::{closure#0}, core[95bb6d661b676f4d]::result::Result<(), rustc_errors[48ad5d4ad3523473]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[95bb6d661b676f4d]::result::Result<(), rustc_errors[48ad5d4ad3523473]::ErrorGuaranteed>>::{closure#1} as core[95bb6d661b676f4d]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  56:        0x10f462b5b - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hd10a5c38d6c64916
  57:        0x10f44d19f - std::sys::unix::thread::Thread::new::thread_start::he793914283faf21a
  58:     0x7ff816f934e1 - __pthread_start

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.67.0-dev running on x86_64-apple-darwin

query stack during panic:
#0 [layout_of] computing layout of `U`
#1 [eval_to_allocation_raw] const-evaluating + checking `B`
#2 [eval_to_const_value_raw] simplifying constant for the type system `B`
#3 [eval_to_const_value_raw] simplifying constant for the type system `B`
#4 [lint_mod] linting top-level module
#5 [analysis] running analysis passes on this crate
end of query stack
warning: 2 warnings emitted
```

</p>
</details>

### Version

Built stage1 from 604d52108e9272d75618ab6a7b5eb006857fce52 on x86_64-apple-darwin

<details><summary>config.toml</summary>

```toml
# Includes one of the default files in src/bootstrap/defaults
profile = "compiler"
changelog-seen = 2

[llvm]
download-ci-llvm = true     # Download a pre-built LLVM?
assertions = true           # LLVM assertions on?

[rust]
incremental = true          # Build rustc with incremental compilation?
debug-assertions = true
overflow-checks = true
```

</details>

CC #99836 participants: @cuviper, @RalfJung @eddyb

@rustbot label +A-layout

### PR DESCRIPTION
**Pull request by luqmana**
Fixes #104802
Fixes #103634

r? @eddyb cc @RalfJung

### CODE REVIEW

File: compiler/rustc_abi/src/layout.rs [hunk 1]
```diff
@@ -935,6 +935,18 @@ pub trait LayoutCalculator {
...
+            Abi::Scalar(x) => x.align(dl).abi != align.abi,
+            Abi::ScalarPair(x, y) => align.abi < cmp::max(x.align(dl).abi, y.align(dl).abi),
+            Abi::Vector { element, .. } => align.abi < element.align(dl).abi,
+            Abi::Aggregate { .. } => false,
+            Abi::Uninhabited => unreachable!(),
+        };
+        if align_mismatch {
+            // mismatched alignment: reset to Aggregate
+            abi = Abi::Aggregate { sized: true };
+        }
```
Comment (RalfJung) [inline compiler/rustc_abi/src/layout.rs:948]: So this still first computes a bad layout but then later patches that up? That doesn't sound like a great approach to me... but I don't know this code. @oli-obk or @eddyb would know better.

Comment (luqmana) [reply compiler/rustc_abi/src/layout.rs:948]: Yea it's perhaps not ideal. on first pass I did try to do it iteratively but realized we only do the packed alignment adjustment after the fields loop new anyways.

Comment (oli-obk) [reply compiler/rustc_abi/src/layout.rs:948]: right above we do the `repr.pack` check. You could compare the existing alignment against the proposed one and pick the aggregate Abi if they mismatch in there. That way you don't have to look into the abi again, but can just rely on the computed alignment.

Comment (luqmana) [reply compiler/rustc_abi/src/layout.rs:948]: Yea, just comparing `pack != align.abi` would work there but that'd be stronger than necessary for `ScalarPair` & `Vector` right (at least going off of what `layout_sanity_check` looks for)

Comment (RalfJung) [reply compiler/rustc_abi/src/layout.rs:948]: `layout_sanity_check` is a crude approximation of what invariants we care about -- I wrote it, and I don't really know what the layout invariants are. I would caution against using it as the basis for such things. It is a baseline, guarding against some known invalid layouts, not a reference to hit as closely as possible.

**Comment by eddyb** [comment]
I would prefer if this was fixed by #103926 - specifically, this comment: https://github.com/rust-lang/rust/pull/103926#discussion_r1032645751.

If you can arrange with @oli-obk, you could take over in this PR - I don't care as long as both alignment sources are fixed at once *without special-casing them*.

Also, we need a test for `#[repr(packed)] union Foo { zst: [u16; 0], byte: u8 }`, which should, by virtue of `#[repr(packed)]` *reducing alignment back*, be able to be `Abi::Scalar` again!

**Comment by oli-obk** [comment]
> I'm ok with taking a stab at it or leaving it to @oli-obk

I won't get to it this week or next week, so feel free to take over!

File: compiler/rustc_abi/src/layout.rs [hunk 2]
```diff
@@ -897,42 +897,58 @@ pub trait LayoutCalculator {
...
 
         if let Some(pack) = repr.pack {
             align = align.min(AbiAndPrefAlign::new(pack));
         }
 
+        // If all non-ZST fields have the same ABI, we may forward that ABI
+        // for the union as a whole, unless otherwise inhibited.
+        let abi = match (optimize, common_non_zst_abi_and_align) {
+            (false, _) | (_, None) => Abi::Aggregate { sized: true },
+            (true, Some((abi, _))) => {
```
Comment (eddyb) [inline compiler/rustc_abi/src/layout.rs:942]: You're not using the `align` in `common_non_zst_abi_and_align`, so you can remove that and be left with just `common_non_zst_abi`, I think?

File: compiler/rustc_abi/src/lib.rs [hunk 3]
```diff
@@ -1241,6 +1241,31 @@ impl Abi {
     pub fn is_scalar(&self) -> bool {
         matches!(*self, Abi::Scalar(_))
     }
+
+    /// Returns the fixed alignment of this ABI, if any
+    pub fn inherent_align<C: HasDataLayout>(&self, cx: &C) -> Option<AbiAndPrefAlign> {
```
Comment (eddyb) [inline compiler/rustc_abi/src/lib.rs:1246]:
```suggestion
    /// Returns the fixed alignment of this ABI, if any is mandated.
    pub fn inherent_align<C: HasDataLayout>(&self, cx: &C) -> Option<AbiAndPrefAlign> {
```
(cc @RalfJung, it would be good to use this same method in the sanity check, right?)

File: compiler/rustc_abi/src/lib.rs [hunk 4]
```diff
@@ -1241,6 +1241,31 @@ impl Abi {
...
+        Some(match *self {
+            Abi::Scalar(s) => s.align(cx),
+            Abi::ScalarPair(s1, s2) => {
+                AbiAndPrefAlign::new(cmp::max(s1.align(cx).abi, s2.align(cx).abi))
```
Comment (eddyb) [inline compiler/rustc_abi/src/lib.rs:1250]:
```suggestion
                s1.align(cx).max(s2.align(cx))
```
(you don't want to disturb the preferred alignment - to test the effect this you'll sadly need a type with different abi-vs-pref alignment, like `u64` on a 32-bit target, so not the easiest thing)

File: compiler/rustc_abi/src/lib.rs [hunk 5]
```diff
@@ -1241,6 +1241,31 @@ impl Abi {
...
+            }
+            Abi::Vector { element, count } => {
+                cx.data_layout().vector_align(element.size(cx) * count)
+            }
+            Abi::Uninhabited | Abi::Aggregate { .. } => return None,
+        })
+    }
+
+    /// Discard valid range information and allow undef
```
Comment (eddyb) [inline compiler/rustc_abi/src/lib.rs:1259]:
```suggestion
    /// Discard validity range information and allow undef.
```
(I'm not sure, this does feel perfect, but also `Scalar::to_union` doesn't have any doc comment at all)

File: compiler/rustc_abi/src/layout.rs [hunk 6]
```diff
@@ -897,42 +897,58 @@ pub trait LayoutCalculator {
...
-                    Abi::Scalar(x) => Abi::Scalar(x.to_union()),
-                    Abi::ScalarPair(x, y) => Abi::ScalarPair(x.to_union(), y.to_union()),
-                    Abi::Vector { element: x, count } => {
-                        Abi::Vector { element: x.to_union(), count }
+                let field_abi = field.abi.to_union();
+
+                if let Some((abi, align)) = &mut common_non_zst_abi_and_align {
+                    if *abi != field_abi {
+                        // Different fields have different ABI: disable opt
+                        optimize = false;
```
Comment (eddyb) [inline compiler/rustc_abi/src/layout.rs:914]: Might be better to have a `common_non_zst_abi` be a `Result<Option<Abi>, AbiMismatch>`?
(with a locally defined `struct AbiMismatch;` - at least that's the kind of thing I tend to do to label those kinds of situations, I think?)

**Review by eddyb — CHANGES_REQUESTED** [review]

**Comment by apiraino** [comment]
Switching to waiting on author to incorporate changes. Feel free to request a review with `@rustbot ready`, thanks!

@rustbot author

File: compiler/rustc_abi/src/layout.rs (hunk 2 above)
Comment (luqmana) [reply compiler/rustc_abi/src/layout.rs]: Wasn't using it down here but above in the loop for the "non-Aggregate field with matching ABI but differing alignment" check. Renamed things to try to make it a little more clear.

File: compiler/rustc_abi/src/lib.rs (hunk 3 above)
Comment (luqmana) [reply compiler/rustc_abi/src/lib.rs]: Added & updated layout_sanity_check.

**Comment by wesleywiser** [comment]
Visited during the compiler team triage meeting. It looks like @eddyb's feedback has been taken into account and resolved. Reassigning to @oli-obk for review. Feel free to reroll if you would prefer!

r? @oli-obk

**Review by oli-obk — CHANGES_REQUESTED** [review]
just a nit, then this lgtm

**Comment by pnkfelix** [comment]
@rustbot label: +S-waiting-on-author -S-waiting-on-review

just needs a rebase according to @oli-obk

File: compiler/rustc_abi/src/layout.rs [hunk 7]
```diff
@@ -893,42 +893,68 @@ pub trait LayoutCalculator {
...
+            if !field.0.is_zst() && !common_non_zst_abi_and_align.is_err() {
                 // Discard valid range information and allow undef
-                let field_abi = match field.abi() {
-                    Abi::Scalar(x) => Abi::Scalar(x.to_union()),
-                    Abi::ScalarPair(x, y) => Abi::ScalarPair(x.to_union(), y.to_union()),
-                    Abi::Vector { element: x, count } => {
-                        Abi::Vector { element: x.to_union(), count }
+                let field_abi = field.abi().to_union();
+
+                if let Ok(Some((common_abi, common_align))) = &mut common_non_zst_abi_and_align {
```
[the remark this answers is not in the document]
Comment (luqmana) [reply compiler/rustc_abi/src/layout.rs]: Sure, reordered it a bit to remove the `is_err` check.
