### PR TITLE
Revert #103880 "Use non-ascribed type as field's type in mir"

### LINKED ISSUE #105809: Compile error 'failed to get layout for'
### Code

It's not failing in my project, but a dependency (but rocket).

### Meta

Fails the same in two environments:

```
rustc 1.68.0-nightly (9c07efe84 2022-12-16) running on aarch64-apple-darwin
compiler flags: --crate-type lib -C embed-bitcode=no -C split-debuginfo=unpacked -C debuginfo=2 -C incremental=[REDACTED]
```

AND

```
rustc 1.68.0-nightly (9c07efe84 2022-12-16) running on x86_64-unknown-linux-gnu
compiler flags: --crate-type lib -C embed-bitcode=no -C debuginfo=2 -C incremental=[REDACTED]
```

### Error output

```
   Compiling rocket_cors v0.6.0-alpha1 (https://github.com/lawliet89/rocket_cors?branch=master#c17e8145)
error: internal compiler error: compiler/rustc_codegen_llvm/src/context.rs:969:13: failed to get layout for `&mut Pin<&mut rocket::http::hyper::server::shutdown::Graceful<rocket::http::private::Incoming<rocket::ext::CancellableListener<rocket::Shutdown, L>>, service::make::MakeServiceFn<[closure@rocket::server::<impl Rocket<Orbit>>::http_server<L>::{closure#0}::{closure#2}]>, rocket::Shutdown, hyper::common::exec::Exec>>`: unable to determine layout for `&mut Pin<&mut rocket::http::hyper::server::shutdown::Graceful<rocket::http::private::Incoming<rocket::ext::CancellableListener<rocket::Shutdown, L>>, service::make::MakeServiceFn<[closure@rocket::server::<impl Rocket<Orbit>>::http_server<L>::{closure#0}::{closure#2}]>, rocket::Shutdown, hyper::common::exec::Exec>>` because `&mut Pin<&mut rocket::http::hyper::server::shutdown::Graceful<rocket::http::private::Incoming<rocket::ext::CancellableListener<rocket::Shutdown, L>>, service::make::MakeServiceFn<[closure@rocket::server::<impl Rocket<Orbit>>::http_server<L>::{closure#0}::{closure#2}]>, rocket::Shutdown, hyper::common::exec::Exec>>` cannot be normalized

thread 'rustc' panicked at 'Box<dyn Any>', /rustc/9c07efe84f28a44f3044237696acc295aa407ee5/compiler/rustc_errors/src/lib.rs:973:33
stack backtrace:
   0:        0x1033ae8e4 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hf05b923e3705aab6
   1:        0x1033ffb9c - core::fmt::write::h4d4011c40e30a20e
   2:        0x1033a1ea0 - std::io::Write::write_fmt::hac39cff9713a22a8
   3:        0x1033ae6f8 - std::sys_common::backtrace::print::h269f9d0fba6134d5
   4:        0x1033b11a8 - std::panicking::default_hook::{{closure}}::h1b64b947323e5455
   5:        0x1033b0f00 - std::panicking::default_hook::hd5000a9bd64dd6fe
   6:        0x10b602654 - rustc_driver[3bb78e66a26ba6d7]::DEFAULT_HOOK::{closure#0}::{closure#0}
   7:        0x1033b18a0 - std::panicking::rust_panic_with_hook::ha951c23f48d097e1
   8:        0x10b81bda4 - std[4a15b4f0527ee59b]::panicking::begin_panic::<rustc_errors[dfa53bcc3145749c]::ExplicitBug>::{closure#0}
   9:        0x10b81772c - std[4a15b4f0527ee59b]::sys_common::backtrace::__rust_end_short_backtrace::<std[4a15b4f0527ee59b]::panicking::begin_panic<rustc_errors[dfa53bcc3145749c]::ExplicitBug>::{closure#0}, !>
  10:        0x10f80f92c - std[4a15b4f0527ee59b]::panicking::begin_panic::<rustc_errors[dfa53bcc3145749c]::ExplicitBug>
  11:        0x10b81759c - std[4a15b4f0527ee59b]::panic::panic_any::<rustc_errors[dfa53bcc3145749c]::ExplicitBug>
  12:        0x10b80fe5c - <rustc_errors[dfa53bcc3145749c]::HandlerInner>::span_bug::<rustc_span[d14b04d350947fdd]::span_encoding::Span, &alloc[8854800cdb100ea]::string::String>
  13:        0x10b80fa00 - <rustc_errors[dfa53bcc3145749c]::Handler>::span_bug::<rustc_span[d14b04d350947fdd]::span_encoding::Span, &alloc[8854800cdb100ea]::string::String>
  14:        0x10b73fd9c - rustc_middle[f5dd9b07379f660d]::ty::context::tls::with_context_opt::<rustc_middle[f5dd9b07379f660d]::ty::context::tls::with_opt<rustc_middle[f5dd9b07379f660d]::util::bug::opt_span_bug_fmt<rustc_span[d14b04d350947fdd]::span_encoding::Span>::{closure#0}, ()>::{closure#0}, ()>
  15:        0x10b73fc68 - rustc_middle[f5dd9b07379f660d]::util::bug::opt_span_bug_fmt::<rustc_span[d14b04d350947fdd]::span_encoding::Span>
  16:        0x10f80f9a0 - rustc_middle[f5dd9b07379f660d]::util::bug::span_bug_fmt::<rustc_span[d14b04d350947fdd]::span_encoding::Span>
  17:        0x10b73b778 - <rustc_codegen_llvm[2f081aae4baaf7a2]::context::CodegenCx as rustc_middle[f5dd9b07379f660d]::ty::layout::LayoutOfHelpers>::handle_layout_err
  18:        0x10b734acc - <rustc_codegen_llvm[2f081aae4baaf7a2]::context::CodegenCx as rustc_middle[f5dd9b07379f660d]::ty::layout::LayoutOf>::spanned_layout_of::{closure#0}
  19:        0x10b73b0d0 - <rustc_codegen_llvm[2f081aae4baaf7a2]::context::CodegenCx as rustc_middle[f5dd9b07379f660d]::ty::layout::LayoutOf>::layout_of
  20:        0x10b72fe0c - <rustc_codegen_ssa[8d103e59afe8e517]::mir::place::PlaceRef<&rustc_codegen_llvm[2f081aae4baaf7a2]::llvm_::ffi::Value>>::project_type::<rustc_codegen_llvm[2f081aae4baaf7a2]::builder::Builder>
  21:        0x10b807e3c - <rustc_codegen_ssa[8d103e59afe8e517]::mir::FunctionCx<rustc_codegen_llvm[2f081aae4baaf7a2]::builder::Builder>>::codegen_place
  22:        0x10b7fe588 - <rustc_codegen_ssa[8d103e59afe8e517]::mir::FunctionCx<rustc_codegen_llvm[2f081aae4baaf7a2]::builder::Builder>>::codegen_rvalue_operand
  23:        0x10b804748 - <rustc_codegen_ssa[8d103e59afe8e517]::mir::FunctionCx<rustc_codegen_llvm[2f081aae4baaf7a2]::builder::Builder>>::codegen_block
  24:        0x10b7fb9c0 - rustc_codegen_ssa[8d103e59afe8e517]::mir::codegen_mir::<rustc_codegen_llvm[2f081aae4baaf7a2]::builder::Builder>
  25:        0x10b717a64 - rustc_codegen_ssa[8d103e59afe8e517]::base::codegen_instance::<rustc_codegen_llvm[2f081aae4baaf7a2]::builder::Builder>
  26:        0x10b7b65d8 - <rustc_middle[f5dd9b07379f660d]::mir::mono::MonoItem as rustc_codegen_ssa[8d103e59afe8e517]::mono_item::MonoItemExt>::define::<rustc_codegen_llvm[2f081aae4baaf7a2]::builder::Builder>
  27:        0x10b821e70 - rustc_codegen_llvm[2f081aae4baaf7a2]::base::compile_codegen_unit::module_codegen
  28:        0x10b780c40 - <rustc_query_system[22b17381a42b3400]::dep_graph::graph::DepGraph<rustc_middle[f5dd9b07379f660d]::dep_graph::dep_node::DepKind>>::with_task::<rustc_middle[f5dd9b07379f660d]::ty::context::TyCtxt, rustc_span[d14b04d350947fdd]::symbol::Symbol, rustc_codegen_ssa[8d103e59afe8e517]::ModuleCodegen<rustc_codegen_llvm[2f081aae4baaf7a2]::ModuleLlvm>>
  29:        0x10b826c10 - <rustc_codegen_llvm[2f081aae4baaf7a2]::LlvmCodegenBackend as rustc_codegen_ssa[8d103e59afe8e517]::traits::backend::ExtraBackendMethods>::compile_codegen_unit
  30:        0x10b717240 - rustc_codegen_ssa[8d103e59afe8e517]::base::codegen_crate::<rustc_codegen_llvm[2f081aae4baaf7a2]::LlvmCodegenBackend>
  31:        0x10b827d9c - <rustc_codegen_llvm[2f081aae4baaf7a2]::LlvmCodegenBackend as rustc_codegen_ssa[8d103e59afe8e517]::traits::backend::CodegenBackend>::codegen_crate
  32:        0x10b6793b8 - <rustc_session[4c9d27593fc597b6]::session::Session>::time::<alloc[8854800cdb100ea]::boxed::Box<dyn core[41fe635294967b39]::any::Any>, rustc_interface[cf09683c24aec831]::passes::start_codegen::{closure#0}>
  33:        0x10b6a6004 - rustc_interface[cf09683c24aec831]::passes::start_codegen
  34:        0x10b6a4fec - <rustc_interface[cf09683c24aec831]::passes::QueryContext>::enter::<<rustc_interface[cf09683c24aec831]::queries::Queries>::ongoing_codegen::{closure#0}::{closure#0}, core[41fe635294967b39]::result::Result<alloc[8854800cdb100ea]::boxed::Box<dyn core[41fe635294967b39]::any::Any>, rustc_errors[dfa53bcc3145749c]::ErrorGuaranteed>>
  35:        0x10b6f5f84 - <rustc_interface[cf09683c24aec831]::queries::Queries>::ongoing_codegen
  36:        0x10b5df0e8 - rustc_span[d14b04d350947fdd]::with_source_map::<core[41fe635294967b39]::result::Result<(), rustc_errors[dfa53bcc3145749c]::ErrorGuaranteed>, rustc_interface[cf09683c24aec831]::interface::run_compiler<core[41fe635294967b39]::result::Result<(), rustc_errors[dfa53bcc3145749c]::ErrorGuaranteed>, rustc_driver[3bb78e66a26ba6d7]::run_compiler::{closure#1}>::{closure#0}::{closure#0}>
  37:        0x10b5d2b5c - <scoped_tls[f45245cb1acfce05]::ScopedKey<rustc_span[d14b04d350947fdd]::SessionGlobals>>::set::<rustc_interface[cf09683c24aec831]::interface::run_compiler<core[41fe635294967b39]::result::Result<(), rustc_errors[dfa53bcc3145749c]::ErrorGuaranteed>, rustc_driver[3bb78e66a26ba6d7]::run_compiler::{closure#1}>::{closure#0}, core[41fe635294967b39]::result::Result<(), rustc_errors[dfa53bcc3145749c]::ErrorGuaranteed>>
  38:        0x10b5a7878 - std[4a15b4f0527ee59b]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[cf09683c24aec831]::util::run_in_thread_pool_with_globals<rustc_interface[cf09683c24aec831]::interface::run_compiler<core[41fe635294967b39]::result::Result<(), rustc_errors[dfa53bcc3145749c]::ErrorGuaranteed>, rustc_driver[3bb78e66a26ba6d7]::run_compiler::{closure#1}>::{closure#0}, core[41fe635294967b39]::result::Result<(), rustc_errors[dfa53bcc3145749c]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[41fe635294967b39]::result::Result<(), rustc_errors[dfa53bcc3145749c]::ErrorGuaranteed>>
  39:        0x10b58e490 - <<std[4a15b4f0527ee59b]::thread::Builder>::spawn_unchecked_<rustc_interface[cf09683c24aec831]::util::run_in_thread_pool_with_globals<rustc_interface[cf09683c24aec831]::interface::run_compiler<core[41fe635294967b39]::result::Result<(), rustc_errors[dfa53bcc3145749c]::ErrorGuaranteed>, rustc_driver[3bb78e66a26ba6d7]::run_compiler::{closure#1}>::{closure#0}, core[41fe635294967b39]::result::Result<(), rustc_errors[dfa53bcc3145749c]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[41fe635294967b39]::result::Result<(), rustc_errors[dfa53bcc3145749c]::ErrorGuaranteed>>::{closure#1} as core[41fe635294967b39]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  40:        0x1033b9cbc - std::sys::unix::thread::Thread::new::thread_start::ha67a48e73a2ba1c0
  41:        0x19b00c26c - __pthread_deallocate
```

<details><summary><strong>Backtrace</strong></summary>
<p>

As above.

</p>
</details>

### PR DESCRIPTION
**Pull request by lqd**
This PR prepares a revert for #103880 to fix #105809, #105881, #105886 and others (like the duplicates of the first one), in case an actual fix can't get done today. 

I've also added the MCVE from #105809. There is no MCVE for the #105881 and #105886 ICEs yet however, so there are no tests for them here, although we'll need one before relanding the original changes.

Were this PR to land, it would also reopen #96514 as it was fixed by the original PR.

Opening as draft to allow time for a possible fix.

r? @jackh726

### CODE REVIEW

**Comment by jackh726** [comment]
@bors p=1 rollup=never

r=me in 6-8 hours if no fix has been put up

File: src/test/ui/mir/issue-105809.rs [hunk 1]
```diff
@@ -0,0 +1,36 @@
+// Non-regression test ICE from issue #105809 and duplicates.
+
+// build-pass: the ICE is during codegen
+// compile-flags: --edition 2018
```
Comment (b-naber) [inline src/test/ui/mir/issue-105809.rs:4]: Can you add `-Zmir-opt-level=1` here? It was reported in one of the issues that this only ICE'd with that option.

Comment (lqd) [reply src/test/ui/mir/issue-105809.rs:4]: I can, but IIRC 1 is the default, and this test does ICE as is on master.

So I take it we'll land the revert and won't have time to do a fix ?

Comment (b-naber) [reply src/test/ui/mir/issue-105809.rs:4]: I'm looking into it right now, but am not sure whether I can fix it in the next couple of hours. If I don't open a PR in the next two hours we can revert it.

Comment (lqd) [reply src/test/ui/mir/issue-105809.rs]: Don't worry about it too much, it's perfectly fine, we can land the revert to buy us time to look into it without pressure.

I've now added `-Zmir-opt-level=1` to the test.

Comment (b-naber) [reply src/test/ui/mir/issue-105809.rs]: Getting somewhat closer to figuring out what is going wrong. Can you give me 30 more minutes?

Comment (lqd) [reply src/test/ui/mir/issue-105809.rs]: Ah but of course! #105881 and #105886 don't have MCVEs yet so hopefully these 3 issues all have the same underlying issue.

I've marked this PR as ready, and if you want it to land, either you or @jackh726 can tell bors that whenever you need. The time frame jack refers to here https://github.com/rust-lang/rust/pull/105905#issuecomment-1357914851 would be 2AM my time.

Comment (b-naber) [reply src/test/ui/mir/issue-105809.rs]: We add an additional `OpaqueCast` [here](https://github.com/rust-lang/rust/blob/7ab803891dd95a04f3b2143e40b26f03b608b4bc/compiler/rustc_mir_build/src/build/matches/util.rs#L109-L115) because `ty != pattern.ty`. This then later ICEs because we cannot get the layout for that type, I don't understand why getting the layout fails though. Will try to work more on this in the next few days.

Thanks for opening the revert PR @lqd.

**Comment by jackh726** [comment]
@bors delegate=b-naber

@b-naber From the comment thread, not sure if you're stuck. Feel free to r=me at any point. It's very easy to revert and fix later, so no stress.

**Comment by lqd** [comment]
Bumping the priority to 8, this is a P-critical fix that should land before the https://github.com/rust-lang/rust/pull/105918 rollup at p=7.

@bors p=8
