### PR TITLE
rustc: Tweak visibility of some lang items 

### LINKED ISSUE #51342: panic_implementation: no_mangle attribute needed?
When using the new [`panic_implementation` attribute](https://github.com/rust-lang/rust/pull/50338) I get a linker error:

```
  = note: lld: error: undefined symbol: rust_begin_unwind
          >>> referenced by core8-82115649ca0ebad190f7336e649e4ba4.rs
          >>>               core-4aa79020766f2e95.core8-82115649ca0ebad190f7336e649e4ba4.rs.rcgu.o:(core::panicking::panic_fmt::h73e9bd85b453f13d) in archive /…/target/sysroot/lib/rustlib/x86_64-blog_os/lib/libcore-4aa79020766f2e95.rlib
```

(I'm linking with LLD)

Adding the `#[no_mangle]` attribute seems to fix this linker error.

Is `no_mangle` required for the panic function or is this a bug?

### LINKED ISSUE #52795: `rust_begin_unwind` symbol doesn't have the right visibility
when emitted from a bin crate.

### STR

``` console
$ cat foo.rs
```

``` rust
#![feature(panic_implementation)]
#![no_main]
#![no_std]

use core::panic::PanicInfo;

#[panic_implementation]
fn panic(_info: &PanicInfo) -> ! {
    loop {}
}
```

``` console
$ rustc -C panic=abort --crate-type=bin --emit=obj foo.rs

$ nm -C foo.o
0000000000000000 t rust_begin_unwind

$ rustc -C panic=abort --crate-type=lib --emit=obj foo.rs

$ nm -C foo.o
0000000000000000 T rust_begin_unwind
```

`rust_begin_unwind` being an internal / private symbol (`t`) causes linker errors of the form "undefined reference to `rust_begin_unwind`".

### Meta

``` console
$ rustc -V
rustc 1.29.0-nightly (6a1c0637c 2018-07-23)
```

### PR DESCRIPTION
**Pull request by alexcrichton**
This commit tweaks the linker-level visibility of some lang items that rustc
uses and defines. Notably this means that `#[panic_implementation]` and
`#[alloc_error_handler]` functions are never marked as `internal`. It's up to
the linker to eliminate these, not rustc.

Additionally `#[global_allocator]` generated symbols are no longer forced to
`Default` visibility (fully exported), but rather they're relaxed to `Hidden`
visibility). This symbols are *not* needed across DLL boundaries, only as a
local implementation detail of the compiler-injected allocator symbols, so
`Hidden` should suffice.

Closes #51342
Closes #52795

### CODE REVIEW

**Comment by alexcrichton** [comment]
r? @michaelwoerister 

Note that the diff looks gnarly, but the second commit is much cleaner and the first commit should have no functional changes included, just a refactoring.

**Comment by alexcrichton** [comment]
The travis failure above pointed me to some more worrying bugs to fix, but they should be fixed here now as well. The bug was that we were defining the `__rg_alloc` symbol with "hidden" visibility but weren't referencing it with hidden visibility in the allocator CGU the compiler generates, causing a link error. In fixing this, though, it turned out this *also *cause problems.

We are, today, generating an allocator CGU for too many crates. If you link to the standard library dynamically, for example, you don't need an allocator CGU as libstd has already selected the allocator symbols for you, and you should reference those. This meant that the compiler failed to compile because it was generating allocator CGUs referencing hidden symbols defined in libstd's dynamic object, causing the link to fail.

So the solution here was to generate an allocator CGU less of the time. Basically if anything is a rust dylib there's no need for an allocator CGU because the allocator has already been selected. Otherwise everything should proceed as usual today (all static compilations will continue to generate an allocator CGU)

File: src/librustc_mir/monomorphize/partitioning.rs [hunk 1]
```diff
@@ -487,6 +373,176 @@ fn place_root_mono_items<'a, 'tcx, I>(tcx: TyCtxt<'a, 'tcx, 'tcx>,
     }
 }
 
+fn mono_item_linkage_and_visibility(
+    tcx: TyCtxt<'a, 'tcx, 'tcx>,
+    mono_item: &MonoItem<'tcx>,
+    can_be_internalized: &mut bool,
+    default: &dyn Fn(DefId, bool) -> Visibility,
```
Comment (michaelwoerister) [inline src/librustc_mir/monomorphize/partitioning.rs]: It seems like `default` could be just a regular function and doesn't need to be passed in as a closure.

File: src/librustc_mir/monomorphize/partitioning.rs [hunk 2]
```diff
@@ -487,6 +373,176 @@ fn place_root_mono_items<'a, 'tcx, I>(tcx: TyCtxt<'a, 'tcx, 'tcx>,
...
+    if tcx.lang_items().start_fn() == Some(def_id) {
+        *can_be_internalized = false;
+        return Visibility::Hidden
+    }
+
+    // Determine if monomorphizations instantiated in this crate will be made
+    // available to downstream crates. This depends on whether we are in
+    // share-generics mode and whether the current crate can even have
+    // downstream crates.
+    let export_generics = tcx.share_generics() &&
```
Comment (michaelwoerister) [inline src/librustc_mir/monomorphize/partitioning.rs]: It might be good to compute this value just once (because doesn't depend on the specific mono-item) and pass it in as a simple boolean parameter.

File: src/librustc_mir/monomorphize/partitioning.rs [hunk 3]
```diff
@@ -487,6 +373,176 @@ fn place_root_mono_items<'a, 'tcx, I>(tcx: TyCtxt<'a, 'tcx, 'tcx>,
...
+    // function in the standard library, used for the `main` function. We don't
+    // want to export it so we tag it with `Hidden` visibility but this symbol
+    // is only referenced from the actual `main` symbol which we unfortunately
+    // don't know anything about during partitioning/collection. As a result we
+    // forcibly keep this symbol out of the `internalization_candidates` set.
+    //
+    // FIXME: eventually we don't want to always force this symbol to have
+    //        hidden visibility, it should indeed be a candidate for
+    //        internalization, but we have to understand that it's referenced
+    //        from the `main` symbol we'll generate later.
```
Comment (michaelwoerister) [inline src/librustc_mir/monomorphize/partitioning.rs]: This might be solvable by have a special `InstanceDef` variant, like we have for all the shims...

Comment (michaelwoerister) [reply src/librustc_mir/monomorphize/partitioning.rs]: (Just thinking aloud, no action needed here)

**Review by michaelwoerister — COMMENTED** [review]
Looks great, thanks Alex! r=me with the nits addressed.

**Comment by nnethercote** [comment]
FWIW, this PR improved compile speed a bit on a couple of benchmarks, and regressed it on `unused-warnings` (which doesn't matter much):
https://perf.rust-lang.org/compare.html?start=3f4f18f098183bf60820e4304433c4c4d9cceaaa&end=26d7b64237c6daa66064c8583b7aecf534c2a9ae&stat=instructions:u

**Comment by alexcrichton** [comment]
Intersting! I have a hunch for where the slowdown came from, I'll try to test it out.

**Comment by alexcrichton** [comment]
My attempt in https://github.com/rust-lang/rust/pull/53499 to diagnose this unfortunately was unsuccessful

**Comment by pnkfelix** [comment]
This injected a bug that caused `rustdoc` to stop being able to test the `jemalloc-ctl` crate

**Comment by pnkfelix** [comment]
(BTW its certainly posslble that the correct fix here lies with `rustdoc` itself, or with the unit tests of the  `jemalloc-ctl` crate. Though the latter seems quite unlikely to me, since these unit tests appear to work fine when you run them outside the context of `rustdoc --test`...)
