### PR TITLE
Fix waiting on a query that panicked

### LINKED ISSUE #111528: ICE: parallel compiler: `value must be in cache after waiting`
### Code
You need parallel compiler config for this!
`rustc  -Zdump-mir-dir=dir  -Zthreads=306  --crate-type lib`
```Rust
// build-fail

//
#![crate_type="rlib"]
#![allow(warnings)]

#[export_name="fail"]
pub fn a() {
}

#[export_name="fail"]
pub fn b() {
//~^ symbol `fail` is already defined
}
```

### Meta

`rustc --version --verbose`:
```
4a59ba4d54a3ec0d8ea1e82b7eeb5c8b0162de04
```

### Error output

```
error: symbol `fail` is already defined
  --> /home/matthias/vcs/github/rust_debug_assertions/tests/ui/duplicate/dupe-symbols-1.rs:12:1
   |
12 | pub fn b() {
   | ^^^^^^^^^^
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
thread 'rustc' panicked at 'value must be in cache after waiting', /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_query_system/src/query/plumbing.rs:302:30
stack backtrace:
   0:     0x7f372030abf6 - std::backtrace_rs::backtrace::libunwind::trace::h74804ffdd8fa53e7
                               at /home/matthias/vcs/github/rust_debug_assertions/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x7f372030abf6 - std::backtrace_rs::backtrace::trace_unsynchronized::h7428ab2b67b36e0c
                               at /home/matthias/vcs/github/rust_debug_assertions/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7f372030abf6 - std::sys_common::backtrace::_print_fmt::h8de225fa5d864a16
                               at /home/matthias/vcs/github/rust_debug_assertions/library/std/src/sys_common/backtrace.rs:65:5
   3:     0x7f372030abf6 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hf186862c319ab6b0
                               at /home/matthias/vcs/github/rust_debug_assertions/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x7f37203af698 - core::fmt::rt::Argument::fmt::h6eb98e918eb80ebd
                               at /home/matthias/vcs/github/rust_debug_assertions/library/core/src/fmt/rt.rs:138:9
   5:     0x7f37203af698 - core::fmt::write::hfa7c5695b2a1784c
                               at /home/matthias/vcs/github/rust_debug_assertions/library/core/src/fmt/mod.rs:1094:21
   6:     0x7f37203151bf - std::io::Write::write_fmt::h8780fc8b700f7b89
                               at /home/matthias/vcs/github/rust_debug_assertions/library/std/src/io/mod.rs:1712:15
   7:     0x7f372030a9f5 - std::sys_common::backtrace::_print::h4ce540e460b36e22
                               at /home/matthias/vcs/github/rust_debug_assertions/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x7f372030a9f5 - std::sys_common::backtrace::print::h6954c2242c47d1db
                               at /home/matthias/vcs/github/rust_debug_assertions/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x7f372032bebc - std::panicking::default_hook::{{closure}}::h7efa3c73d7318a2f
  10:     0x7f372032bb92 - std::panicking::default_hook::h478ef42d51f84426
                               at /home/matthias/vcs/github/rust_debug_assertions/library/std/src/panicking.rs:288:9
  11:     0x7f3722cfe63b - <alloc[32b43e9536c01a3]::boxed::Box<dyn for<'a, 'b> core[c5d5d662f7508502]::ops::function::Fn<(&'a core[c5d5d662f7508502]::panic::panic_info::PanicInfo<'b>,), Output = ()> + core[c5d5d662f7508502]::marker::Send + core[c5d5d662f7508502]::marker::Sync> as core[c5d5d662f7508502]::ops::function::Fn<(&core[c5d5d662f7508502]::panic::panic_info::PanicInfo,)>>::call
                               at /home/matthias/vcs/github/rust_debug_assertions/library/alloc/src/boxed.rs:1999:9
  12:     0x7f3722cfe63b - rustc_driver_impl[fa47bdc6a12b5fac]::install_ice_hook::{closure#0}
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_driver_impl/src/lib.rs:1258:13
  13:     0x7f372032c75a - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::hfea6944ca11513b1
                               at /home/matthias/vcs/github/rust_debug_assertions/library/alloc/src/boxed.rs:1999:9
  14:     0x7f372032c75a - std::panicking::rust_panic_with_hook::h3d7c73761f67633f
                               at /home/matthias/vcs/github/rust_debug_assertions/library/std/src/panicking.rs:695:13
  15:     0x7f372030baa1 - std::panicking::begin_panic_handler::{{closure}}::h0004dd01860b01c3
                               at /home/matthias/vcs/github/rust_debug_assertions/library/std/src/panicking.rs:580:13
  16:     0x7f372030acd6 - std::sys_common::backtrace::__rust_end_short_backtrace::hccbfe31830e0f553
                               at /home/matthias/vcs/github/rust_debug_assertions/library/std/src/sys_common/backtrace.rs:150:18
  17:     0x7f372032c2c2 - rust_begin_unwind
                               at /home/matthias/vcs/github/rust_debug_assertions/library/std/src/panicking.rs:578:5
  18:     0x7f37203cb363 - core::panicking::panic_fmt::h98b1dd38c1edb68b
                               at /home/matthias/vcs/github/rust_debug_assertions/library/core/src/panicking.rs:67:14
  19:     0x7f3724a6ee01 - rustc_query_system[8ee2d68ce6f1a061]::query::plumbing::wait_for_query::<rustc_query_impl[6a8a86d109cc84e7]::queries::crate_hash, rustc_query_impl[6a8a86d109cc84e7]::plumbing::QueryCtxt>::{closure#0}
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_query_system/src/query/plumbing.rs:302:30
  20:     0x7f3724a6a6e6 - rustc_data_structures[1e2d979854fde302]::cold_path::<rustc_query_system[8ee2d68ce6f1a061]::query::plumbing::wait_for_query<rustc_query_impl[6a8a86d109cc84e7]::queries::crate_hash, rustc_query_impl[6a8a86d109cc84e7]::plumbing::QueryCtxt>::{closure#0}, !>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_data_structures/src/lib.rs:53:5
  21:     0x7f37248f5cb4 - rustc_query_system[8ee2d68ce6f1a061]::query::plumbing::wait_for_query::<rustc_query_impl[6a8a86d109cc84e7]::queries::exported_symbols, rustc_query_impl[6a8a86d109cc84e7]::plumbing::QueryCtxt>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_query_system/src/query/plumbing.rs:302:17
  22:     0x7f37248f5cb4 - rustc_query_system[8ee2d68ce6f1a061]::query::plumbing::try_execute_query::<rustc_query_impl[6a8a86d109cc84e7]::queries::exported_symbols, rustc_query_impl[6a8a86d109cc84e7]::plumbing::QueryCtxt>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_query_system/src/query/plumbing.rs:377:21
  23:     0x7f3724d49998 - rustc_query_system[8ee2d68ce6f1a061]::query::plumbing::get_query::<rustc_query_impl[6a8a86d109cc84e7]::queries::exported_symbols, rustc_query_impl[6a8a86d109cc84e7]::plumbing::QueryCtxt>::{closure#0}
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_query_system/src/query/plumbing.rs:824:36
  24:     0x7f3724d49998 - stacker[7db3bd1b0a5e56b0]::maybe_grow::<(rustc_middle[d62e0ab363fca640]::query::erase::Erased<[u8; 16usize]>, core[c5d5d662f7508502]::option::Option<rustc_query_system[8ee2d68ce6f1a061]::dep_graph::graph::DepNodeIndex>), rustc_query_system[8ee2d68ce6f1a061]::query::plumbing::get_query<rustc_query_impl[6a8a86d109cc84e7]::queries::exported_symbols, rustc_query_impl[6a8a86d109cc84e7]::plumbing::QueryCtxt>::{closure#0}>
                               at /home/matthias/.cargo/registry/src/index.crates.io-6f17d22bba15001f/stacker-0.1.15/src/lib.rs:55:9
  25:     0x7f3724d49998 - rustc_data_structures[1e2d979854fde302]::stack::ensure_sufficient_stack::<(rustc_middle[d62e0ab363fca640]::query::erase::Erased<[u8; 16usize]>, core[c5d5d662f7508502]::option::Option<rustc_query_system[8ee2d68ce6f1a061]::dep_graph::graph::DepNodeIndex>), rustc_query_system[8ee2d68ce6f1a061]::query::plumbing::get_query<rustc_query_impl[6a8a86d109cc84e7]::queries::exported_symbols, rustc_query_impl[6a8a86d109cc84e7]::plumbing::QueryCtxt>::{closure#0}>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_data_structures/src/stack.rs:17:5
  26:     0x7f3724d49998 - rustc_query_system[8ee2d68ce6f1a061]::query::plumbing::get_query::<rustc_query_impl[6a8a86d109cc84e7]::queries::exported_symbols, rustc_query_impl[6a8a86d109cc84e7]::plumbing::QueryCtxt>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_query_system/src/query/plumbing.rs:824:9
  27:     0x7f3724d49998 - rustc_query_impl[6a8a86d109cc84e7]::get_query::exported_symbols
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_query_impl/src/plumbing.rs:493:21
  28:     0x7f3723c0cd1e - rustc_middle[d62e0ab363fca640]::ty::query::query_get_at::<rustc_query_system[8ee2d68ce6f1a061]::query::caches::VecCache<rustc_span[9849ed9ca8d6c267]::def_id::CrateNum, rustc_middle[d62e0ab363fca640]::query::erase::Erased<[u8; 16usize]>>>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_middle/src/ty/query.rs:219:17
  29:     0x7f3723c1897c - <rustc_middle[d62e0ab363fca640]::ty::query::TyCtxtAt>::exported_symbols
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_middle/src/ty/query.rs:483:31
  30:     0x7f3723c1897c - <rustc_middle[d62e0ab363fca640]::ty::context::TyCtxt>::exported_symbols
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_middle/src/ty/query.rs:474:35
  31:     0x7f3723c1897c - <rustc_metadata[1b566562c0981a27]::rmeta::encoder::EncodeContext>::encode_crate_root::{closure#21}
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_metadata/src/rmeta/encoder.rs:646:47
  32:     0x7f3723c1897c - <rustc_metadata[1b566562c0981a27]::rmeta::encoder::EncodeContext>::encode_crate_root
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_metadata/src/rmeta/encoder.rs:645:32
  33:     0x7f3723c26c17 - rustc_metadata[1b566562c0981a27]::rmeta::encoder::encode_metadata_impl
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_metadata/src/rmeta/encoder.rs:2278:16
  34:     0x7f3723baa645 - rustc_metadata[1b566562c0981a27]::rmeta::encoder::encode_metadata::{closure#0}
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_metadata/src/rmeta/encoder.rs:2229:12
  35:     0x7f3723baa645 - rayon_core[f08dc397f011bb28]::join::join::call::<(), rustc_metadata[1b566562c0981a27]::rmeta::encoder::encode_metadata::{closure#0}>::{closure#0}
                               at /home/matthias/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rustc-rayon-core-0.5.0/src/join/mod.rs:103:18
  36:     0x7f3723baa645 - rayon_core[f08dc397f011bb28]::join::join_context::call_a::<(), rayon_core[f08dc397f011bb28]::join::join::call<(), rustc_metadata[1b566562c0981a27]::rmeta::encoder::encode_metadata::{closure#0}>::{closure#0}>::{closure#0}
                               at /home/matthias/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rustc-rayon-core-0.5.0/src/join/mod.rs:125:17
  37:     0x7f3723baa645 - <core[c5d5d662f7508502]::panic::unwind_safe::AssertUnwindSafe<rayon_core[f08dc397f011bb28]::join::join_context::call_a<(), rayon_core[f08dc397f011bb28]::join::join::call<(), rustc_metadata[1b566562c0981a27]::rmeta::encoder::encode_metadata::{closure#0}>::{closure#0}>::{closure#0}> as core[c5d5d662f7508502]::ops::function::FnOnce<()>>::call_once
                               at /home/matthias/vcs/github/rust_debug_assertions/library/core/src/panic/unwind_safe.rs:271:9
  38:     0x7f3723baa645 - std[68c29493de10bea]::panicking::try::do_call::<core[c5d5d662f7508502]::panic::unwind_safe::AssertUnwindSafe<rayon_core[f08dc397f011bb28]::join::join_context::call_a<(), rayon_core[f08dc397f011bb28]::join::join::call<(), rustc_metadata[1b566562c0981a27]::rmeta::encoder::encode_metadata::{closure#0}>::{closure#0}>::{closure#0}>, ()>
                               at /home/matthias/vcs/github/rust_debug_assertions/library/std/src/panicking.rs:485:40
  39:     0x7f3723baa645 - std[68c29493de10bea]::panicking::try::<(), core[c5d5d662f7508502]::panic::unwind_safe::AssertUnwindSafe<rayon_core[f08dc397f011bb28]::join::join_context::call_a<(), rayon_core[f08dc397f011bb28]::join::join::call<(), rustc_metadata[1b566562c0981a27]::rmeta::encoder::encode_metadata::{closure#0}>::{closure#0}>::{closure#0}>>
                               at /home/matthias/vcs/github/rust_debug_assertions/library/std/src/panicking.rs:449:19
  40:     0x7f3723baa645 - std[68c29493de10bea]::panic::catch_unwind::<core[c5d5d662f7508502]::panic::unwind_safe::AssertUnwindSafe<rayon_core[f08dc397f011bb28]::join::join_context::call_a<(), rayon_core[f08dc397f011bb28]::join::join::call<(), rustc_metadata[1b566562c0981a27]::rmeta::encoder::encode_metadata::{closure#0}>::{closure#0}>::{closure#0}>, ()>
                               at /home/matthias/vcs/github/rust_debug_assertions/library/std/src/panic.rs:140:14
  41:     0x7f3723baa645 - rayon_core[f08dc397f011bb28]::unwind::halt_unwinding::<rayon_core[f08dc397f011bb28]::join::join_context::call_a<(), rayon_core[f08dc397f011bb28]::join::join::call<(), rustc_metadata[1b566562c0981a27]::rmeta::encoder::encode_metadata::{closure#0}>::{closure#0}>::{closure#0}, ()>
                               at /home/matthias/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rustc-rayon-core-0.5.0/src/unwind.rs:17:5
  42:     0x7f3723baa645 - rayon_core[f08dc397f011bb28]::join::join_context::<rayon_core[f08dc397f011bb28]::join::join::call<(), rustc_metadata[1b566562c0981a27]::rmeta::encoder::encode_metadata::{closure#0}>::{closure#0}, rayon_core[f08dc397f011bb28]::join::join::call<(), rustc_metadata[1b566562c0981a27]::rmeta::encoder::encode_metadata::{closure#1}>::{closure#0}, (), ()>::{closure#0}
                               at /home/matthias/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rustc-rayon-core-0.5.0/src/join/mod.rs:144:24
  43:     0x7f3723b9c9f8 - rayon_core[f08dc397f011bb28]::registry::in_worker::<rayon_core[f08dc397f011bb28]::join::join_context<rayon_core[f08dc397f011bb28]::join::join::call<(), rustc_metadata[1b566562c0981a27]::rmeta::encoder::encode_metadata::{closure#0}>::{closure#0}, rayon_core[f08dc397f011bb28]::join::join::call<(), rustc_metadata[1b566562c0981a27]::rmeta::encoder::encode_metadata::{closure#1}>::{closure#0}, (), ()>::{closure#0}, ((), ())>
  44:     0x7f3723c25f82 - rayon_core[f08dc397f011bb28]::join::join_context::<rayon_core[f08dc397f011bb28]::join::join::call<(), rustc_metadata[1b566562c0981a27]::rmeta::encoder::encode_metadata::{closure#0}>::{closure#0}, rayon_core[f08dc397f011bb28]::join::join::call<(), rustc_metadata[1b566562c0981a27]::rmeta::encoder::encode_metadata::{closure#1}>::{closure#0}, (), ()>
                               at /home/matthias/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rustc-rayon-core-0.5.0/src/join/mod.rs:133:5
  45:     0x7f3723c25f82 - rayon_core[f08dc397f011bb28]::join::join::<rustc_metadata[1b566562c0981a27]::rmeta::encoder::encode_metadata::{closure#0}, rustc_metadata[1b566562c0981a27]::rmeta::encoder::encode_metadata::{closure#1}, (), ()>
                               at /home/matthias/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rustc-rayon-core-0.5.0/src/join/mod.rs:106:5
  46:     0x7f3723c25f82 - rustc_metadata[1b566562c0981a27]::rmeta::encoder::encode_metadata
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_metadata/src/rmeta/encoder.rs:2228:5
  47:     0x7f3723be95de - rustc_metadata[1b566562c0981a27]::fs::encode_and_write_metadata
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_metadata/src/fs.rs:66:13
  48:     0x7f37238793d7 - rustc_interface[f00717bbd5e2d5b3]::passes::start_codegen
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_interface/src/passes.rs:849:44
  49:     0x7f3723913922 - <rustc_interface[f00717bbd5e2d5b3]::queries::Queries>::ongoing_codegen::{closure#0}::{closure#0}
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_interface/src/queries.rs:260:20
  50:     0x7f3723913922 - <rustc_middle[d62e0ab363fca640]::ty::context::GlobalCtxt>::enter::<<rustc_interface[f00717bbd5e2d5b3]::queries::Queries>::ongoing_codegen::{closure#0}::{closure#0}, core[c5d5d662f7508502]::result::Result<alloc[32b43e9536c01a3]::boxed::Box<dyn core[c5d5d662f7508502]::any::Any>, rustc_span[9849ed9ca8d6c267]::ErrorGuaranteed>>::{closure#0}
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_middle/src/ty/context.rs:550:37
  51:     0x7f3723913922 - rustc_middle[d62e0ab363fca640]::ty::context::tls::enter_context::<<rustc_middle[d62e0ab363fca640]::ty::context::GlobalCtxt>::enter<<rustc_interface[f00717bbd5e2d5b3]::queries::Queries>::ongoing_codegen::{closure#0}::{closure#0}, core[c5d5d662f7508502]::result::Result<alloc[32b43e9536c01a3]::boxed::Box<dyn core[c5d5d662f7508502]::any::Any>, rustc_span[9849ed9ca8d6c267]::ErrorGuaranteed>>::{closure#0}, core[c5d5d662f7508502]::result::Result<alloc[32b43e9536c01a3]::boxed::Box<dyn core[c5d5d662f7508502]::any::Any>, rustc_span[9849ed9ca8d6c267]::ErrorGuaranteed>>::{closure#0}
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_middle/src/ty/context/tls.rs:82:9
  52:     0x7f3723913922 - <std[68c29493de10bea]::thread::local::LocalKey<core[c5d5d662f7508502]::cell::Cell<*const ()>>>::try_with::<rustc_middle[d62e0ab363fca640]::ty::context::tls::enter_context<<rustc_middle[d62e0ab363fca640]::ty::context::GlobalCtxt>::enter<<rustc_interface[f00717bbd5e2d5b3]::queries::Queries>::ongoing_codegen::{closure#0}::{closure#0}, core[c5d5d662f7508502]::result::Result<alloc[32b43e9536c01a3]::boxed::Box<dyn core[c5d5d662f7508502]::any::Any>, rustc_span[9849ed9ca8d6c267]::ErrorGuaranteed>>::{closure#0}, core[c5d5d662f7508502]::result::Result<alloc[32b43e9536c01a3]::boxed::Box<dyn core[c5d5d662f7508502]::any::Any>, rustc_span[9849ed9ca8d6c267]::ErrorGuaranteed>>::{closure#0}, core[c5d5d662f7508502]::result::Result<alloc[32b43e9536c01a3]::boxed::Box<dyn core[c5d5d662f7508502]::any::Any>, rustc_span[9849ed9ca8d6c267]::ErrorGuaranteed>>
                               at /home/matthias/vcs/github/rust_debug_assertions/library/std/src/thread/local.rs:270:16
  53:     0x7f3723913922 - <std[68c29493de10bea]::thread::local::LocalKey<core[c5d5d662f7508502]::cell::Cell<*const ()>>>::with::<rustc_middle[d62e0ab363fca640]::ty::context::tls::enter_context<<rustc_middle[d62e0ab363fca640]::ty::context::GlobalCtxt>::enter<<rustc_interface[f00717bbd5e2d5b3]::queries::Queries>::ongoing_codegen::{closure#0}::{closure#0}, core[c5d5d662f7508502]::result::Result<alloc[32b43e9536c01a3]::boxed::Box<dyn core[c5d5d662f7508502]::any::Any>, rustc_span[9849ed9ca8d6c267]::ErrorGuaranteed>>::{closure#0}, core[c5d5d662f7508502]::result::Result<alloc[32b43e9536c01a3]::boxed::Box<dyn core[c5d5d662f7508502]::any::Any>, rustc_span[9849ed9ca8d6c267]::ErrorGuaranteed>>::{closure#0}, core[c5d5d662f7508502]::result::Result<alloc[32b43e9536c01a3]::boxed::Box<dyn core[c5d5d662f7508502]::any::Any>, rustc_span[9849ed9ca8d6c267]::ErrorGuaranteed>>
                               at /home/matthias/vcs/github/rust_debug_assertions/library/std/src/thread/local.rs:246:9
  54:     0x7f3723913922 - rustc_middle[d62e0ab363fca640]::ty::context::tls::enter_context::<<rustc_middle[d62e0ab363fca640]::ty::context::GlobalCtxt>::enter<<rustc_interface[f00717bbd5e2d5b3]::queries::Queries>::ongoing_codegen::{closure#0}::{closure#0}, core[c5d5d662f7508502]::result::Result<alloc[32b43e9536c01a3]::boxed::Box<dyn core[c5d5d662f7508502]::any::Any>, rustc_span[9849ed9ca8d6c267]::ErrorGuaranteed>>::{closure#0}, core[c5d5d662f7508502]::result::Result<alloc[32b43e9536c01a3]::boxed::Box<dyn core[c5d5d662f7508502]::any::Any>, rustc_span[9849ed9ca8d6c267]::ErrorGuaranteed>>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_middle/src/ty/context/tls.rs:79:9
  55:     0x7f3723913922 - <rustc_middle[d62e0ab363fca640]::ty::context::GlobalCtxt>::enter::<<rustc_interface[f00717bbd5e2d5b3]::queries::Queries>::ongoing_codegen::{closure#0}::{closure#0}, core[c5d5d662f7508502]::result::Result<alloc[32b43e9536c01a3]::boxed::Box<dyn core[c5d5d662f7508502]::any::Any>, rustc_span[9849ed9ca8d6c267]::ErrorGuaranteed>>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_middle/src/ty/context.rs:550:9
  56:     0x7f37238549cd - <rustc_interface[f00717bbd5e2d5b3]::queries::QueryResult<&rustc_middle[d62e0ab363fca640]::ty::context::GlobalCtxt>>::enter::<core[c5d5d662f7508502]::result::Result<alloc[32b43e9536c01a3]::boxed::Box<dyn core[c5d5d662f7508502]::any::Any>, rustc_span[9849ed9ca8d6c267]::ErrorGuaranteed>, <rustc_interface[f00717bbd5e2d5b3]::queries::Queries>::ongoing_codegen::{closure#0}::{closure#0}>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_interface/src/queries.rs:70:9
  57:     0x7f37238549cd - <rustc_interface[f00717bbd5e2d5b3]::queries::Queries>::ongoing_codegen::{closure#0}
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_interface/src/queries.rs:247:13
  58:     0x7f37238549cd - <rustc_interface[f00717bbd5e2d5b3]::queries::Query<alloc[32b43e9536c01a3]::boxed::Box<dyn core[c5d5d662f7508502]::any::Any>>>::compute::<<rustc_interface[f00717bbd5e2d5b3]::queries::Queries>::ongoing_codegen::{closure#0}>::{closure#0}::{closure#0}
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_interface/src/queries.rs:44:41
  59:     0x7f37238549cd - <core[c5d5d662f7508502]::option::Option<core[c5d5d662f7508502]::result::Result<rustc_data_structures[1e2d979854fde302]::steal::Steal<alloc[32b43e9536c01a3]::boxed::Box<dyn core[c5d5d662f7508502]::any::Any>>, rustc_span[9849ed9ca8d6c267]::ErrorGuaranteed>>>::get_or_insert_with::<<rustc_interface[f00717bbd5e2d5b3]::queries::Query<alloc[32b43e9536c01a3]::boxed::Box<dyn core[c5d5d662f7508502]::any::Any>>>::compute<<rustc_interface[f00717bbd5e2d5b3]::queries::Queries>::ongoing_codegen::{closure#0}>::{closure#0}::{closure#0}>
                               at /home/matthias/vcs/github/rust_debug_assertions/library/core/src/option.rs:1645:26
  60:     0x7f37238549cd - <rustc_interface[f00717bbd5e2d5b3]::queries::Query<alloc[32b43e9536c01a3]::boxed::Box<dyn core[c5d5d662f7508502]::any::Any>>>::compute::<<rustc_interface[f00717bbd5e2d5b3]::queries::Queries>::ongoing_codegen::{closure#0}>::{closure#0}
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_interface/src/queries.rs:44:17
  61:     0x7f37238549cd - <core[c5d5d662f7508502]::cell::RefMut<core[c5d5d662f7508502]::option::Option<core[c5d5d662f7508502]::result::Result<rustc_data_structures[1e2d979854fde302]::steal::Steal<alloc[32b43e9536c01a3]::boxed::Box<dyn core[c5d5d662f7508502]::any::Any>>, rustc_span[9849ed9ca8d6c267]::ErrorGuaranteed>>>>::filter_map::<rustc_data_structures[1e2d979854fde302]::steal::Steal<alloc[32b43e9536c01a3]::boxed::Box<dyn core[c5d5d662f7508502]::any::Any>>, <rustc_interface[f00717bbd5e2d5b3]::queries::Query<alloc[32b43e9536c01a3]::boxed::Box<dyn core[c5d5d662f7508502]::any::Any>>>::compute<<rustc_interface[f00717bbd5e2d5b3]::queries::Queries>::ongoing_codegen::{closure#0}>::{closure#0}>
                               at /home/matthias/vcs/github/rust_debug_assertions/library/core/src/cell.rs:1635:15
  62:     0x7f37238549cd - <rustc_interface[f00717bbd5e2d5b3]::queries::Query<alloc[32b43e9536c01a3]::boxed::Box<dyn core[c5d5d662f7508502]::any::Any>>>::compute::<<rustc_interface[f00717bbd5e2d5b3]::queries::Queries>::ongoing_codegen::{closure#0}>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_interface/src/queries.rs:41:9
  63:     0x7f37238549cd - <rustc_interface[f00717bbd5e2d5b3]::queries::Queries>::ongoing_codegen
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_interface/src/queries.rs:246:9
  64:     0x7f3722ca1762 - rustc_driver_impl[fa47bdc6a12b5fac]::run_compiler::{closure#1}::{closure#2}
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_driver_impl/src/lib.rs:405:13
  65:     0x7f3722ca1762 - <rustc_interface[f00717bbd5e2d5b3]::interface::Compiler>::enter::<rustc_driver_impl[fa47bdc6a12b5fac]::run_compiler::{closure#1}::{closure#2}, core[c5d5d662f7508502]::result::Result<core[c5d5d662f7508502]::option::Option<rustc_interface[f00717bbd5e2d5b3]::queries::Linker>, rustc_span[9849ed9ca8d6c267]::ErrorGuaranteed>>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_interface/src/queries.rs:389:19
  66:     0x7f3722d49e80 - rustc_driver_impl[fa47bdc6a12b5fac]::run_compiler::{closure#1}
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_driver_impl/src/lib.rs:340:22
  67:     0x7f3722d49e80 - rustc_interface[f00717bbd5e2d5b3]::interface::run_compiler::<core[c5d5d662f7508502]::result::Result<(), rustc_span[9849ed9ca8d6c267]::ErrorGuaranteed>, rustc_driver_impl[fa47bdc6a12b5fac]::run_compiler::{closure#1}>::{closure#0}::{closure#0}
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_interface/src/interface.rs:331:21
  68:     0x7f3722d49e80 - rustc_span[9849ed9ca8d6c267]::set_source_map::<core[c5d5d662f7508502]::result::Result<(), rustc_span[9849ed9ca8d6c267]::ErrorGuaranteed>, rustc_interface[f00717bbd5e2d5b3]::interface::run_compiler<core[c5d5d662f7508502]::result::Result<(), rustc_span[9849ed9ca8d6c267]::ErrorGuaranteed>, rustc_driver_impl[fa47bdc6a12b5fac]::run_compiler::{closure#1}>::{closure#0}::{closure#0}>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_span/src/lib.rs:1039:5
  69:     0x7f3722d46be3 - rustc_interface[f00717bbd5e2d5b3]::interface::run_compiler::<core[c5d5d662f7508502]::result::Result<(), rustc_span[9849ed9ca8d6c267]::ErrorGuaranteed>, rustc_driver_impl[fa47bdc6a12b5fac]::run_compiler::{closure#1}>::{closure#0}
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_interface/src/interface.rs:325:13
  70:     0x7f3722d46be3 - <rayon_core[f08dc397f011bb28]::thread_pool::ThreadPool>::install::<rustc_interface[f00717bbd5e2d5b3]::interface::run_compiler<core[c5d5d662f7508502]::result::Result<(), rustc_span[9849ed9ca8d6c267]::ErrorGuaranteed>, rustc_driver_impl[fa47bdc6a12b5fac]::run_compiler::{closure#1}>::{closure#0}, core[c5d5d662f7508502]::result::Result<(), rustc_span[9849ed9ca8d6c267]::ErrorGuaranteed>>::{closure#0}
                               at /home/matthias/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rustc-rayon-core-0.5.0/src/thread_pool/mod.rs:110:40
  71:     0x7f3722d442f8 - <rayon_core[f08dc397f011bb28]::registry::Registry>::in_worker_cold::<<rayon_core[f08dc397f011bb28]::thread_pool::ThreadPool>::install<rustc_interface[f00717bbd5e2d5b3]::interface::run_compiler<core[c5d5d662f7508502]::result::Result<(), rustc_span[9849ed9ca8d6c267]::ErrorGuaranteed>, rustc_driver_impl[fa47bdc6a12b5fac]::run_compiler::{closure#1}>::{closure#0}, core[c5d5d662f7508502]::result::Result<(), rustc_span[9849ed9ca8d6c267]::ErrorGuaranteed>>::{closure#0}, core[c5d5d662f7508502]::result::Result<(), rustc_span[9849ed9ca8d6c267]::ErrorGuaranteed>>::{closure#0}::{closure#0}
                               at /home/matthias/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rustc-rayon-core-0.5.0/src/registry.rs:562:21
  72:     0x7f3722d442f8 - <rayon_core[f08dc397f011bb28]::job::JobResult<core[c5d5d662f7508502]::result::Result<(), rustc_span[9849ed9ca8d6c267]::ErrorGuaranteed>>>::call::<<rayon_core[f08dc397f011bb28]::registry::Registry>::in_worker_cold<<rayon_core[f08dc397f011bb28]::thread_pool::ThreadPool>::install<rustc_interface[f00717bbd5e2d5b3]::interface::run_compiler<core[c5d5d662f7508502]::result::Result<(), rustc_span[9849ed9ca8d6c267]::ErrorGuaranteed>, rustc_driver_impl[fa47bdc6a12b5fac]::run_compiler::{closure#1}>::{closure#0}, core[c5d5d662f7508502]::result::Result<(), rustc_span[9849ed9ca8d6c267]::ErrorGuaranteed>>::{closure#0}, core[c5d5d662f7508502]::result::Result<(), rustc_span[9849ed9ca8d6c267]::ErrorGuaranteed>>::{closure#0}::{closure#0}>::{closure#0}
                               at /home/matthias/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rustc-rayon-core-0.5.0/src/job.rs:225:41
  73:     0x7f3722d442f8 - <core[c5d5d662f7508502]::panic::unwind_safe::AssertUnwindSafe<<rayon_core[f08dc397f011bb28]::job::JobResult<core[c5d5d662f7508502]::result::Result<(), rustc_span[9849ed9ca8d6c267]::ErrorGuaranteed>>>::call<<rayon_core[f08dc397f011bb28]::registry::Registry>::in_worker_cold<<rayon_core[f08dc397f011bb28]::thread_pool::ThreadPool>::install<rustc_interface[f00717bbd5e2d5b3]::interface::run_compiler<core[c5d5d662f7508502]::result::Result<(), rustc_span[9849ed9ca8d6c267]::ErrorGuaranteed>, rustc_driver_impl[fa47bdc6a12b5fac]::run_compiler::{closure#1}>::{closure#0}, core[c5d5d662f7508502]::result::Result<(), rustc_span[9849ed9ca8d6c267]::ErrorGuaranteed>>::{closure#0}, core[c5d5d662f7508502]::result::Result<(), rustc_span[9849ed9ca8d6c267]::ErrorGuaranteed>>::{closure#0}::{closure#0}>::{closure#0}> as core[c5d5d662f7508502]::ops::function::FnOnce<()>>::call_once
                               at /home/matthias/vcs/github/rust_debug_assertions/library/core/src/panic/unwind_safe.rs:271:9
  74:     0x7f3722d442f8 - std[68c29493de10bea]::panicking::try::do_call::<core[c5d5d662f7508502]::panic::unwind_safe::AssertUnwindSafe<<rayon_core[f08dc397f011bb28]::job::JobResult<core[c5d5d662f7508502]::result::Result<(), rustc_span[9849ed9ca8d6c267]::ErrorGuaranteed>>>::call<<rayon_core[f08dc397f011bb28]::registry::Registry>::in_worker_cold<<rayon_core[f08dc397f011bb28]::thread_pool::ThreadPool>::install<rustc_interface[f00717bbd5e2d5b3]::interface::run_compiler<core[c5d5d662f7508502]::result::Result<(), rustc_span[9849ed9ca8d6c267]::ErrorGuaranteed>, rustc_driver_impl[fa47bdc6a12b5fac]::run_compiler::{closure#1}>::{closure#0}, core[c5d5d662f7508502]::result::Result<(), rustc_span[9849ed9ca8d6c267]::ErrorGuaranteed>>::{closure#0}, core[c5d5d662f7508502]::result::Result<(), rustc_span[9849ed9ca8d6c267]::ErrorGuaranteed>>::{closure#0}::{closure#0}>::{closure#0}>, core[c5d5d662f7508502]::result::Result<(), rustc_span[9849ed9ca8d6c267]::ErrorGuaranteed>>
                               at /home/matthias/vcs/github/rust_debug_assertions/library/std/src/panicking.rs:485:40
  75:     0x7f3722d442f8 - std[68c29493de10bea]::panicking::try::<core[c5d5d662f7508502]::result::Result<(), rustc_span[9849ed9ca8d6c267]::ErrorGuaranteed>, core[c5d5d662f7508502]::panic::unwind_safe::AssertUnwindSafe<<rayon_core[f08dc397f011bb28]::job::JobResult<core[c5d5d662f7508502]::result::Result<(), rustc_span[9849ed9ca8d6c267]::ErrorGuaranteed>>>::call<<rayon_core[f08dc397f011bb28]::registry::Registry>::in_worker_cold<<rayon_core[f08dc397f011bb28]::thread_pool::ThreadPool>::install<rustc_interface[f00717bbd5e2d5b3]::interface::run_compiler<core[c5d5d662f7508502]::result::Result<(), rustc_span[9849ed9ca8d6c267]::ErrorGuaranteed>, rustc_driver_impl[fa47bdc6a12b5fac]::run_compiler::{closure#1}>::{closure#0}, core[c5d5d662f7508502]::result::Result<(), rustc_span[9849ed9ca8d6c267]::ErrorGuaranteed>>::{closure#0}, core[c5d5d662f7508502]::result::Result<(), rustc_span[9849ed9ca8d6c267]::ErrorGuaranteed>>::{closure#0}::{closure#0}>::{closure#0}>>
                               at /home/matthias/vcs/github/rust_debug_assertions/library/std/src/panicking.rs:449:19
  76:     0x7f3722d56f2b - std[68c29493de10bea]::panic::catch_unwind::<core[c5d5d662f7508502]::panic::unwind_safe::AssertUnwindSafe<<rayon_core[f08dc397f011bb28]::job::JobResult<core[c5d5d662f7508502]::result::Result<(), rustc_span[9849ed9ca8d6c267]::ErrorGuaranteed>>>::call<<rayon_core[f08dc397f011bb28]::registry::Registry>::in_worker_cold<<rayon_core[f08dc397f011bb28]::thread_pool::ThreadPool>::install<rustc_interface[f00717bbd5e2d5b3]::interface::run_compiler<core[c5d5d662f7508502]::result::Result<(), rustc_span[9849ed9ca8d6c267]::ErrorGuaranteed>, rustc_driver_impl[fa47bdc6a12b5fac]::run_compiler::{closure#1}>::{closure#0}, core[c5d5d662f7508502]::result::Result<(), rustc_span[9849ed9ca8d6c267]::ErrorGuaranteed>>::{closure#0}, core[c5d5d662f7508502]::result::Result<(), rustc_span[9849ed9ca8d6c267]::ErrorGuaranteed>>::{closure#0}::{closure#0}>::{closure#0}>, core[c5d5d662f7508502]::result::Result<(), rustc_span[9849ed9ca8d6c267]::ErrorGuaranteed>>
                               at /home/matthias/vcs/github/rust_debug_assertions/library/std/src/panic.rs:140:14
  77:     0x7f3722d56f2b - rayon_core[f08dc397f011bb28]::unwind::halt_unwinding::<<rayon_core[f08dc397f011bb28]::job::JobResult<core[c5d5d662f7508502]::result::Result<(), rustc_span[9849ed9ca8d6c267]::ErrorGuaranteed>>>::call<<rayon_core[f08dc397f011bb28]::registry::Registry>::in_worker_cold<<rayon_core[f08dc397f011bb28]::thread_pool::ThreadPool>::install<rustc_interface[f00717bbd5e2d5b3]::interface::run_compiler<core[c5d5d662f7508502]::result::Result<(), rustc_span[9849ed9ca8d6c267]::ErrorGuaranteed>, rustc_driver_impl[fa47bdc6a12b5fac]::run_compiler::{closure#1}>::{closure#0}, core[c5d5d662f7508502]::result::Result<(), rustc_span[9849ed9ca8d6c267]::ErrorGuaranteed>>::{closure#0}, core[c5d5d662f7508502]::result::Result<(), rustc_span[9849ed9ca8d6c267]::ErrorGuaranteed>>::{closure#0}::{closure#0}>::{closure#0}, core[c5d5d662f7508502]::result::Result<(), rustc_span[9849ed9ca8d6c267]::ErrorGuaranteed>>
                               at /home/matthias/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rustc-rayon-core-0.5.0/src/unwind.rs:17:5
  78:     0x7f3722d56f2b - <rayon_core[f08dc397f011bb28]::job::JobResult<core[c5d5d662f7508502]::result::Result<(), rustc_span[9849ed9ca8d6c267]::ErrorGuaranteed>>>::call::<<rayon_core[f08dc397f011bb28]::registry::Registry>::in_worker_cold<<rayon_core[f08dc397f011bb28]::thread_pool::ThreadPool>::install<rustc_interface[f00717bbd5e2d5b3]::interface::run_compiler<core[c5d5d662f7508502]::result::Result<(), rustc_span[9849ed9ca8d6c267]::ErrorGuaranteed>, rustc_driver_impl[fa47bdc6a12b5fac]::run_compiler::{closure#1}>::{closure#0}, core[c5d5d662f7508502]::result::Result<(), rustc_span[9849ed9ca8d6c267]::ErrorGuaranteed>>::{closure#0}, core[c5d5d662f7508502]::result::Result<(), rustc_span[9849ed9ca8d6c267]::ErrorGuaranteed>>::{closure#0}::{closure#0}>
                               at /home/matthias/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rustc-rayon-core-0.5.0/src/job.rs:225:15
  79:     0x7f3722d56f2b - <rayon_core[f08dc397f011bb28]::job::StackJob<rayon_core[f08dc397f011bb28]::latch::LatchRef<rayon_core[f08dc397f011bb28]::latch::LockLatch>, <rayon_core[f08dc397f011bb28]::registry::Registry>::in_worker_cold<<rayon_core[f08dc397f011bb28]::thread_pool::ThreadPool>::install<rustc_interface[f00717bbd5e2d5b3]::interface::run_compiler<core[c5d5d662f7508502]::result::Result<(), rustc_span[9849ed9ca8d6c267]::ErrorGuaranteed>, rustc_driver_impl[fa47bdc6a12b5fac]::run_compiler::{closure#1}>::{closure#0}, core[c5d5d662f7508502]::result::Result<(), rustc_span[9849ed9ca8d6c267]::ErrorGuaranteed>>::{closure#0}, core[c5d5d662f7508502]::result::Result<(), rustc_span[9849ed9ca8d6c267]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[c5d5d662f7508502]::result::Result<(), rustc_span[9849ed9ca8d6c267]::ErrorGuaranteed>> as rayon_core[f08dc397f011bb28]::job::Job>::execute
                               at /home/matthias/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rustc-rayon-core-0.5.0/src/job.rs:125:32
  80:     0x7f3721f67730 - <rayon_core[f08dc397f011bb28]::job::JobRef>::execute
                               at /home/matthias/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rustc-rayon-core-0.5.0/src/job.rs:66:9
  81:     0x7f3721f67730 - <rayon_core[f08dc397f011bb28]::registry::WorkerThread>::execute
                               at /home/matthias/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rustc-rayon-core-0.5.0/src/registry.rs:916:13
  82:     0x7f3721f67730 - <rayon_core[f08dc397f011bb28]::registry::WorkerThread>::wait_until_cold
                               at /home/matthias/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rustc-rayon-core-0.5.0/src/registry.rs:862:22
  83:     0x7f3721f64afd - <rayon_core[f08dc397f011bb28]::registry::WorkerThread>::wait_until::<rayon_core[f08dc397f011bb28]::latch::CountLatch>
                               at /home/matthias/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rustc-rayon-core-0.5.0/src/registry.rs:845:13
  84:     0x7f3721f64afd - rayon_core[f08dc397f011bb28]::registry::main_loop
                               at /home/matthias/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rustc-rayon-core-0.5.0/src/registry.rs:991:5
  85:     0x7f3721f64afd - <rayon_core[f08dc397f011bb28]::registry::ThreadBuilder>::run
                               at /home/matthias/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rustc-rayon-core-0.5.0/src/registry.rs:55:18
  86:     0x7f3722c932e4 - rustc_interface[f00717bbd5e2d5b3]::util::run_in_thread_pool_with_globals::<rustc_interface[f00717bbd5e2d5b3]::interface::run_compiler<core[c5d5d662f7508502]::result::Result<(), rustc_span[9849ed9ca8d6c267]::ErrorGuaranteed>, rustc_driver_impl[fa47bdc6a12b5fac]::run_compiler::{closure#1}>::{closure#0}, core[c5d5d662f7508502]::result::Result<(), rustc_span[9849ed9ca8d6c267]::ErrorGuaranteed>>::{closure#2}::{closure#0}::{closure#0}::{closure#0}
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_interface/src/util.rs:210:82
  87:     0x7f3722c932e4 - <scoped_tls[c6512a5451dfceef]::ScopedKey<rustc_span[9849ed9ca8d6c267]::SessionGlobals>>::set::<rustc_interface[f00717bbd5e2d5b3]::util::run_in_thread_pool_with_globals<rustc_interface[f00717bbd5e2d5b3]::interface::run_compiler<core[c5d5d662f7508502]::result::Result<(), rustc_span[9849ed9ca8d6c267]::ErrorGuaranteed>, rustc_driver_impl[fa47bdc6a12b5fac]::run_compiler::{closure#1}>::{closure#0}, core[c5d5d662f7508502]::result::Result<(), rustc_span[9849ed9ca8d6c267]::ErrorGuaranteed>>::{closure#2}::{closure#0}::{closure#0}::{closure#0}, ()>
                               at /home/matthias/.cargo/registry/src/index.crates.io-6f17d22bba15001f/scoped-tls-1.0.0/src/lib.rs:137:9
  88:     0x7f3722c8e628 - rustc_span[9849ed9ca8d6c267]::set_session_globals_then::<(), rustc_interface[f00717bbd5e2d5b3]::util::run_in_thread_pool_with_globals<rustc_interface[f00717bbd5e2d5b3]::interface::run_compiler<core[c5d5d662f7508502]::result::Result<(), rustc_span[9849ed9ca8d6c267]::ErrorGuaranteed>, rustc_driver_impl[fa47bdc6a12b5fac]::run_compiler::{closure#1}>::{closure#0}, core[c5d5d662f7508502]::result::Result<(), rustc_span[9849ed9ca8d6c267]::ErrorGuaranteed>>::{closure#2}::{closure#0}::{closure#0}::{closure#0}>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_span/src/lib.rs:129:5
  89:     0x7f3722c8e628 - rustc_interface[f00717bbd5e2d5b3]::util::run_in_thread_pool_with_globals::<rustc_interface[f00717bbd5e2d5b3]::interface::run_compiler<core[c5d5d662f7508502]::result::Result<(), rustc_span[9849ed9ca8d6c267]::ErrorGuaranteed>, rustc_driver_impl[fa47bdc6a12b5fac]::run_compiler::{closure#1}>::{closure#0}, core[c5d5d662f7508502]::result::Result<(), rustc_span[9849ed9ca8d6c267]::ErrorGuaranteed>>::{closure#2}::{closure#0}::{closure#0}
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_interface/src/util.rs:210:25
  90:     0x7f3722c8e628 - <rayon_core[f08dc397f011bb28]::ThreadPoolBuilder>::build_scoped::<rustc_interface[f00717bbd5e2d5b3]::util::run_in_thread_pool_with_globals<rustc_interface[f00717bbd5e2d5b3]::interface::run_compiler<core[c5d5d662f7508502]::result::Result<(), rustc_span[9849ed9ca8d6c267]::ErrorGuaranteed>, rustc_driver_impl[fa47bdc6a12b5fac]::run_compiler::{closure#1}>::{closure#0}, core[c5d5d662f7508502]::result::Result<(), rustc_span[9849ed9ca8d6c267]::ErrorGuaranteed>>::{closure#2}::{closure#0}::{closure#0}, rustc_interface[f00717bbd5e2d5b3]::util::run_in_thread_pool_with_globals<rustc_interface[f00717bbd5e2d5b3]::interface::run_compiler<core[c5d5d662f7508502]::result::Result<(), rustc_span[9849ed9ca8d6c267]::ErrorGuaranteed>, rustc_driver_impl[fa47bdc6a12b5fac]::run_compiler::{closure#1}>::{closure#0}, core[c5d5d662f7508502]::result::Result<(), rustc_span[9849ed9ca8d6c267]::ErrorGuaranteed>>::{closure#2}::{closure#0}::{closure#1}, core[c5d5d662f7508502]::result::Result<(), rustc_span[9849ed9ca8d6c267]::ErrorGuaranteed>>::{closure#0}::{closure#0}::{closure#0}
                               at /home/matthias/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rustc-rayon-core-0.5.0/src/lib.rs:363:44
  91:     0x7f3722c8e628 - <crossbeam_utils[2907d21727e848bc]::thread::ScopedThreadBuilder>::spawn::<<rayon_core[f08dc397f011bb28]::ThreadPoolBuilder>::build_scoped<rustc_interface[f00717bbd5e2d5b3]::util::run_in_thread_pool_with_globals<rustc_interface[f00717bbd5e2d5b3]::interface::run_compiler<core[c5d5d662f7508502]::result::Result<(), rustc_span[9849ed9ca8d6c267]::ErrorGuaranteed>, rustc_driver_impl[fa47bdc6a12b5fac]::run_compiler::{closure#1}>::{closure#0}, core[c5d5d662f7508502]::result::Result<(), rustc_span[9849ed9ca8d6c267]::ErrorGuaranteed>>::{closure#2}::{closure#0}::{closure#0}, rustc_interface[f00717bbd5e2d5b3]::util::run_in_thread_pool_with_globals<rustc_interface[f00717bbd5e2d5b3]::interface::run_compiler<core[c5d5d662f7508502]::result::Result<(), rustc_span[9849ed9ca8d6c267]::ErrorGuaranteed>, rustc_driver_impl[fa47bdc6a12b5fac]::run_compiler::{closure#1}>::{closure#0}, core[c5d5d662f7508502]::result::Result<(), rustc_span[9849ed9ca8d6c267]::ErrorGuaranteed>>::{closure#2}::{closure#0}::{closure#1}, core[c5d5d662f7508502]::result::Result<(), rustc_span[9849ed9ca8d6c267]::ErrorGuaranteed>>::{closure#0}::{closure#0}::{closure#0}, ()>::{closure#0}
                               at /home/matthias/.cargo/registry/src/index.crates.io-6f17d22bba15001f/crossbeam-utils-0.8.14/src/thread.rs:438:31
  92:     0x7f3722c8e628 - <<crossbeam_utils[2907d21727e848bc]::thread::ScopedThreadBuilder>::spawn<<rayon_core[f08dc397f011bb28]::ThreadPoolBuilder>::build_scoped<rustc_interface[f00717bbd5e2d5b3]::util::run_in_thread_pool_with_globals<rustc_interface[f00717bbd5e2d5b3]::interface::run_compiler<core[c5d5d662f7508502]::result::Result<(), rustc_span[9849ed9ca8d6c267]::ErrorGuaranteed>, rustc_driver_impl[fa47bdc6a12b5fac]::run_compiler::{closure#1}>::{closure#0}, core[c5d5d662f7508502]::result::Result<(), rustc_span[9849ed9ca8d6c267]::ErrorGuaranteed>>::{closure#2}::{closure#0}::{closure#0}, rustc_interface[f00717bbd5e2d5b3]::util::run_in_thread_pool_with_globals<rustc_interface[f00717bbd5e2d5b3]::interface::run_compiler<core[c5d5d662f7508502]::result::Result<(), rustc_span[9849ed9ca8d6c267]::ErrorGuaranteed>, rustc_driver_impl[fa47bdc6a12b5fac]::run_compiler::{closure#1}>::{closure#0}, core[c5d5d662f7508502]::result::Result<(), rustc_span[9849ed9ca8d6c267]::ErrorGuaranteed>>::{closure#2}::{closure#0}::{closure#1}, core[c5d5d662f7508502]::result::Result<(), rustc_span[9849ed9ca8d6c267]::ErrorGuaranteed>>::{closure#0}::{closure#0}::{closure#0}, ()>::{closure#0} as core[c5d5d662f7508502]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
                               at /home/matthias/vcs/github/rust_debug_assertions/library/core/src/ops/function.rs:250:5
  93:     0x7f3722d44f1e - <alloc[32b43e9536c01a3]::boxed::Box<dyn core[c5d5d662f7508502]::ops::function::FnOnce<(), Output = ()> + core[c5d5d662f7508502]::marker::Send> as core[c5d5d662f7508502]::ops::function::FnOnce<()>>::call_once
                               at /home/matthias/vcs/github/rust_debug_assertions/library/alloc/src/boxed.rs:1985:9
  94:     0x7f3722d44f1e - std[68c29493de10bea]::sys_common::backtrace::__rust_begin_short_backtrace::<alloc[32b43e9536c01a3]::boxed::Box<dyn core[c5d5d662f7508502]::ops::function::FnOnce<(), Output = ()> + core[c5d5d662f7508502]::marker::Send>, ()>
                               at /home/matthias/vcs/github/rust_debug_assertions/library/std/src/sys_common/backtrace.rs:134:18
  95:     0x7f3722cee37f - <std[68c29493de10bea]::thread::Builder>::spawn_unchecked_::<alloc[32b43e9536c01a3]::boxed::Box<dyn core[c5d5d662f7508502]::ops::function::FnOnce<(), Output = ()> + core[c5d5d662f7508502]::marker::Send>, ()>::{closure#1}::{closure#0}
                               at /home/matthias/vcs/github/rust_debug_assertions/library/std/src/thread/mod.rs:529:17
  96:     0x7f3722cee37f - <core[c5d5d662f7508502]::panic::unwind_safe::AssertUnwindSafe<<std[68c29493de10bea]::thread::Builder>::spawn_unchecked_<alloc[32b43e9536c01a3]::boxed::Box<dyn core[c5d5d662f7508502]::ops::function::FnOnce<(), Output = ()> + core[c5d5d662f7508502]::marker::Send>, ()>::{closure#1}::{closure#0}> as core[c5d5d662f7508502]::ops::function::FnOnce<()>>::call_once
                               at /home/matthias/vcs/github/rust_debug_assertions/library/core/src/panic/unwind_safe.rs:271:9
  97:     0x7f3722cee37f - std[68c29493de10bea]::panicking::try::do_call::<core[c5d5d662f7508502]::panic::unwind_safe::AssertUnwindSafe<<std[68c29493de10bea]::thread::Builder>::spawn_unchecked_<alloc[32b43e9536c01a3]::boxed::Box<dyn core[c5d5d662f7508502]::ops::function::FnOnce<(), Output = ()> + core[c5d5d662f7508502]::marker::Send>, ()>::{closure#1}::{closure#0}>, ()>
                               at /home/matthias/vcs/github/rust_debug_assertions/library/std/src/panicking.rs:485:40
  98:     0x7f3722cee37f - std[68c29493de10bea]::panicking::try::<(), core[c5d5d662f7508502]::panic::unwind_safe::AssertUnwindSafe<<std[68c29493de10bea]::thread::Builder>::spawn_unchecked_<alloc[32b43e9536c01a3]::boxed::Box<dyn core[c5d5d662f7508502]::ops::function::FnOnce<(), Output = ()> + core[c5d5d662f7508502]::marker::Send>, ()>::{closure#1}::{closure#0}>>
                               at /home/matthias/vcs/github/rust_debug_assertions/library/std/src/panicking.rs:449:19
  99:     0x7f3722cee37f - std[68c29493de10bea]::panic::catch_unwind::<core[c5d5d662f7508502]::panic::unwind_safe::AssertUnwindSafe<<std[68c29493de10bea]::thread::Builder>::spawn_unchecked_<alloc[32b43e9536c01a3]::boxed::Box<dyn core[c5d5d662f7508502]::ops::function::FnOnce<(), Output = ()> + core[c5d5d662f7508502]::marker::Send>, ()>::{closure#1}::{closure#0}>, ()>
                               at /home/matthias/vcs/github/rust_debug_assertions/library/std/src/panic.rs:140:14
 100:     0x7f3722cee37f - <std[68c29493de10bea]::thread::Builder>::spawn_unchecked_::<alloc[32b43e9536c01a3]::boxed::Box<dyn core[c5d5d662f7508502]::ops::function::FnOnce<(), Output = ()> + core[c5d5d662f7508502]::marker::Send>, ()>::{closure#1}
                               at /home/matthias/vcs/github/rust_debug_assertions/library/std/src/thread/mod.rs:528:30
 101:     0x7f3722cee37f - <<std[68c29493de10bea]::thread::Builder>::spawn_unchecked_<alloc[32b43e9536c01a3]::boxed::Box<dyn core[c5d5d662f7508502]::ops::function::FnOnce<(), Output = ()> + core[c5d5d662f7508502]::marker::Send>, ()>::{closure#1} as core[c5d5d662f7508502]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
                               at /home/matthias/vcs/github/rust_debug_assertions/library/core/src/ops/function.rs:250:5
 102:     0x7f372031d69a - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h59b61553bfddebc8
                               at /home/matthias/vcs/github/rust_debug_assertions/library/alloc/src/boxed.rs:1985:9
 103:     0x7f372031d69a - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h0ce3d7a7bade6491
                               at /home/matthias/vcs/github/rust_debug_assertions/library/alloc/src/boxed.rs:1985:9
 104:     0x7f3720303b15 - std::sys::unix::thread::Thread::new::thread_start::h6e446945f062d041
                               at /home/matthias/vcs/github/rust_debug_assertions/library/std/src/sys/unix/thread.rs:108:17
 105:     0x7f37200a6bb5 - <unknown>
 106:     0x7f3720128d90 - <unknown>
 107:                0x0 - <unknown>

error: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.71.0-dev running on x86_64-unknown-linux-gnu

note: compiler flags: -Z dump-mir-dir=dir -Z threads=306 --crate-type lib

query stack during panic:
end of query stack
error: aborting due to previous error
```

</p>
</details>

### PR DESCRIPTION
**Pull request by Zoxc**
This fixes waiting on a query that panicked. The code now looks for `QueryResult::Poisoned` in the query state in addition to the query cache. This fixes https://github.com/rust-lang/rust/issues/111528.

r? @cjgillot

### CODE REVIEW

File: compiler/rustc_query_system/src/query/plumbing.rs [hunk 1]
```diff
@@ -300,7 +300,18 @@ where
...
+                    // We didn't find the query result in the query cache. Check if it was
+                    // poisoned due to a panic instead.
+                    let lock = query.query_state(qcx).active.get_shard_by_value(&key).lock();
+                    match lock.get(&key) {
+                        // The query we waited on panicked. Continue unwinding here.
+                        Some(QueryResult::Poisoned) => FatalError.raise(),
+                        _ => panic!(
+                            "query result must in the cache or the query must be poisoned after a wait"
+                        ),
+                    }
```
Comment (cjgillot) [inline compiler/rustc_query_system/src/query/plumbing.rs:313]: The only possible course of action is unwinding. Should we replace the match by an assertion?

```suggestion
                    // We didn't find the query result in the query cache. Check if it was
                    // poisoned due to a panic instead.
                    debug_assert!(
                        matches!(
                            query.query_state(qcx).active.get_shard_by_value(&key).lock().get(&key),
                            Some(QueryResult::Poisoned),
                        ),
                        "query result must in the cache or the query must be poisoned after a wait",
                    );
                    // The query we waited on panicked. Continue unwinding here.
                    FatalError.raise()
```

Comment (Zoxc) [reply compiler/rustc_query_system/src/query/plumbing.rs:313]: I feel like the current version makes it more clear that we should only call `FatalError.raise()` once we observe the `QueryResult::Poisoned` case. I don't think I want to downgrade to a `debug_assert` without some more testing of the parallel compiler. This path is also not terribly hot.
