### PR TITLE
const-eval: error when initializing a static writes to that static

### LINKED ISSUE #142404: Writing to a static is somehow allowed while initializing that same static
I tried this code:

```rust
#![allow(dead_code)]

struct Foo {
    x: i32,
    y: (),
}

static S: Foo = Foo {
    x: 0,
    y: unsafe {
        (&raw const S.x).cast_mut().write(1);  // Writing to an immutable static that's still being initialized!
    },
};

fn main() {
    println!("{}", S.x);
}
```

I expected to see this happen: An error of some sort, or Miri reports UB.

Instead, this happened: The program compiles and outputs `0`. Miri does not detect UB.

Note that writing to a static while initializing a *different* static is not allowed. For example,

```rust
static mut S: i32 = 0;

static T: () = unsafe {
    (&raw mut S).write(1);
};
```

this produces the following error

```
error[E0080]: could not evaluate static initializer
    --> src/lib.rs:4:5
     |
4    |     (&raw mut S).write(1);
     |     ^^^^^^^^^^^^^^^^^^^^^ modifying a static's initial value from another static's initializer
     |
note: inside `std::ptr::mut_ptr::<impl *mut i32>::write`
    --> /playground/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ptr/mut_ptr.rs:1507:18
     |
1507 |         unsafe { write(self, val) }
     |                  ^^^^^^^^^^^^^^^^
note: inside `std::ptr::write::<i32>`
    --> /playground/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ptr/mod.rs:1580:9
     |
1580 |         intrinsics::write_via_move(dst, src)
     |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the failure occurred here

For more information about this error, try `rustc --explain E0080`.
error: could not compile `playground` (lib) due to 1 previous error
```

### Meta

Reproducible on the playground with `1.89.0-nightly (2025-06-11 e703dff8fe220b78195c)`

@rustbot labels +A-const-eval

### PR DESCRIPTION
**Pull request by RalfJung**
Fixes https://github.com/rust-lang/rust/issues/142404 by also calling the relevant hook for writes, not just reads. To avoid erroring during the actual write of the initial value, we neuter the hook when popping the final stack frame.

Calling the hook during writes requires changing its signature since we cannot pass in the entire interpreter any more.

While doing this I also realized a gap in https://github.com/rust-lang/rust/pull/142575 for zero-sized copies on the read side, so I fixed that and added a test.

r? @oli-obk

### CODE REVIEW

File: compiler/rustc_const_eval/src/interpret/memory.rs [hunk 1]
```diff
@@ -1438,16 +1446,18 @@ impl<'tcx, M: Machine<'tcx>> InterpCx<'tcx, M> {
         let provenance = src_alloc
             .provenance()
             .prepare_copy(src_range, dest_offset, num_copies, self)
-            .map_err(|e| e.to_interp_error(dest_alloc_id))?;
+            .map_err(|e| e.to_interp_error(src_alloc_id))?;
```
Comment (RalfJung) [inline compiler/rustc_const_eval/src/interpret/memory.rs:1449]: This is another drive-by fix, I don't think it makes any sense to use the dest_alloc_id here -- the operation was invoked on the src_alloc, after all.

File: compiler/rustc_const_eval/src/const_eval/machine.rs [hunk 2]
```diff
@@ -705,24 +710,40 @@ impl<'tcx> interpret::Machine<'tcx> for CompileTimeMachine<'tcx> {
         interp_ok(())
     }
 
-    fn before_alloc_read(ecx: &InterpCx<'tcx, Self>, alloc_id: AllocId) -> InterpResult<'tcx> {
+    fn before_alloc_access(
+        tcx: TyCtxtAt<'tcx>,
+        machine: &Self,
+        alloc_id: AllocId,
+    ) -> InterpResult<'tcx> {
+        if machine.last_frame_popped {
```
Comment (oli-obk) [inline compiler/rustc_const_eval/src/const_eval/machine.rs]: you can just check `machine.stack().is_empty()`, instead of tracking `last_frame_popped` separately.

Comment (RalfJung) [reply compiler/rustc_const_eval/src/const_eval/machine.rs]: :facepalm: ah, of course...

**Comment by traviscross** [comment]
@rustbot labels +T-lang +relnotes

This is a breaking change, though I hope and expect it won't affect too much code.  Still, we should probably flag this in the compatibility section of the release notes.

Probably, as a process matter, we should have lang FCPed this (it would have been an easy call -- it's clearly a bug fix).  I don't feel strongly about perturbing anything here, though, (and I appreciate this having been fixed) so let's just...

cc @rust-lang/lang

Looking at it, the Reference is already correct.  It says:

> Writes to `static` items are not allowed in any constant evaluation context.

Can't be any more clear than that.

cc @ehuss

**Comment by RalfJung** [comment]
Ah fair, I thought of this as more of a bugfix but I should have gotten confirmation for that.
