### PR TITLE
rustc: Fix proc_macro expansions on trait methods

### LINKED ISSUE #42493: #[proc_macro_attribute] doesn't work on trait methods
Given this procedural macro:

```rust
#![feature(proc_macro)]

extern crate proc_macro;

use proc_macro::TokenStream;

#[proc_macro_attribute]
pub fn foo(attr: TokenStream, item: TokenStream) -> TokenStream {
    println!("attr: {}", attr);
    println!("item: {}", item);
    item
}
```

and this crate:

```rust
#![feature(proc_macro)]

extern crate foo;

use foo::foo;

trait Trait {
    #[foo]
    fn trait_function(&self);
    #[foo]
    fn trait_function_default(&self) {}
}

fn main() {}
```

Building:

```
$ cargo +nightly build
   Compiling foo v0.1.0 (file:///home/alex/code/foo)
    Finished dev [unoptimized + debuginfo] target(s) in 0.73 secs
```

I saw no output :(

I find that `#[foo]` is *resolved*, it just doesn't seem to get expanded!

### PR DESCRIPTION
**Pull request by alexcrichton**
This commit fixes procedural macro attributes being attached to trait methods,
ensuring that they get resolved and expanded as other procedural macro
attributes. The bug here was that `current_module` on the resolver was
accidentally set to be a trait when it's otherwise only ever expecting a
`mod`/block module. The actual fix here came from @jseyfried, I'm just helping
to land it in the compiler!

Closes #42493

### CODE REVIEW

File: src/librustc_resolve/macros.rs [hunk 1]
```diff
@@ -402,7 +402,7 @@ impl<'a> Resolver<'a> {
         let ast::Path { ref segments, span } = *path;
         let path: Vec<_> = segments.iter().map(|seg| respan(seg.span, seg.identifier)).collect();
         let invocation = self.invocations[&scope];
-        self.current_module = invocation.module.get();
+        self.current_module = self.module_map[&invocation.module.get().normal_ancestor_id];
```
Comment (jseyfried) [inline src/librustc_resolve/macros.rs]: Tests are failing; this should be:
```rust
let module = invocation.module.get();
self.current_module = if module.is_trait() { module.parent.unwrap() } else { module };
```

Comment (alexcrichton) [reply src/librustc_resolve/macros.rs]: Updated!

**Comment by alexcrichton** [comment]
@bors: retry

* https://github.com/rust-lang/rust/issues/38618
