### PR TITLE
core: Make `Debug` impl of raw pointers print metadata if present

### LINKED ISSUE #128684: Debug implementation of fat pointers doesn't show metadata
I tried this code:

```rust
fn main() {
    let mut x = *b"hello";
    let p: &mut [u8] = &mut x;
    let q: *mut [u8] = &mut p[..3];
    assert_eq!(p as *mut [u8], q);
}
```

I expected to see this happen:

```
assertion `left == right` failed
  left: { ptr: 0x7ffdd41d89f3, meta: 5 }
 right: { ptr: 0x7ffdd41d89f3, meta: 3 }
```

Instead, this happened:

```
assertion `left == right` failed
  left: 0x7ffdd41d89f3
 right: 0x7ffdd41d89f3
```

Note: The pointer address is non-deterministic, so the output may differ. What matters is that the pointer address is the same, only the metadata differ.

### Meta

`rustc --version --verbose`:

```
rustc 1.82.0-nightly (f8060d282 2024-07-30)
binary: rustc
commit-hash: f8060d282d42770fadd73905e3eefb85660d3278
commit-date: 2024-07-30
host: x86_64-unknown-linux-gnu
release: 1.82.0-nightly
LLVM version: 18.1.7
```

<details><summary>Backtrace</summary>
<p>

```
thread 'main' panicked at src/main.rs:5:5:
assertion `left == right` failed
  left: 0x7ffca57ef663
 right: 0x7ffca57ef663
stack backtrace:
   0: rust_begin_unwind
             at /rustc/f8060d282d42770fadd73905e3eefb85660d3278/library/std/src/panicking.rs:662:5
   1: core::panicking::panic_fmt
             at /rustc/f8060d282d42770fadd73905e3eefb85660d3278/library/core/src/panicking.rs:74:14
   2: core::panicking::assert_failed_inner
             at /rustc/f8060d282d42770fadd73905e3eefb85660d3278/library/core/src/panicking.rs:412:17
   3: core::panicking::assert_failed
             at /rustc/f8060d282d42770fadd73905e3eefb85660d3278/library/core/src/panicking.rs:367:5
   4: foo::main
             at ./src/main.rs:5:5
   5: core::ops::function::FnOnce::call_once
             at /rustc/f8060d282d42770fadd73905e3eefb85660d3278/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

</p>
</details>

### PR DESCRIPTION
**Pull request by Enselic**
Make Rust pointers appear less magic by including metadata information in their `Debug` output.

This does not break Rust stability guarantees because `Debug` impl are explicitly exempted from stability:
https://doc.rust-lang.org/std/fmt/trait.Debug.html#stability

> ## Stability
>
> Derived `Debug` formats are not stable, and so may change with future Rust versions. Additionally, `Debug` implementations of types provided by the standard library (`std`, `core`, `alloc`, etc.) are not stable, and may also change with future Rust versions.

Note that a regression test is added as a separate commit to make it clear what impact the last commit has on the output.

Closes #128684 because the output of that code now becomes:

```
thread 'main' panicked at src/main.rs:5:5:
assertion `left == right` failed
  left: Pointer { addr: 0x7ffd45c6fc6b, metadata: 5 }
 right: Pointer { addr: 0x7ffd45c6fc6b, metadata: 3 }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

### CODE REVIEW

File: tests/ui/fmt/ptr-metadata.rs [hunk 1]
```diff
@@ -0,0 +1,19 @@
+//@ run-pass
+//@ check-run-results
+//@ normalize-stdout-test: "0x[0-9a-fA-F]+" -> "$$HEX"
+
+use std::fmt::Display;
+
+fn main() {
```
Comment (Noratrieb) [inline tests/ui/fmt/ptr-metadata.rs:7]: can you make this a core unit test instead?

Comment (Enselic) [reply tests/ui/fmt/ptr-metadata.rs:7]: Sure no problem, I'll fix whatever my reviewer(s) ask me to do.

Would you mind elaborating a bit on why though? Do you prefer it as a core  unit test because then the test can be run with a stage0 compiler, maybe? What I like about having it as a UI test is that `--bless` works when the output change.

File: library/core/src/fmt/mod.rs [hunk 2]
```diff
@@ -2767,7 +2767,15 @@ impl Display for char {
...
     fn fmt(&self, f: &mut Formatter<'_>) -> Result {
-        pointer_fmt_inner(self.expose_provenance(), f)
+        if core::mem::size_of::<<T as core::ptr::Pointee>::Metadata>() == 0 {
+            pointer_fmt_inner(self.expose_provenance(), f)
+        } else {
+            f.write_str("Pointer { addr: ")?;
+            pointer_fmt_inner(self.expose_provenance(), f)?;
+            f.write_str(", metadata: ")?;
+            Debug::fmt(&core::ptr::metadata(*self), f)?;
+            f.write_str(" }")
```
Comment (lukas-code) [inline library/core/src/fmt/mod.rs:2777]:
```suggestion
            f.debug_struct("Pointer")
                .field_with("addr", |f| pointer_fmt_inner(self.expose_provenance(), f))
                .field("metadata", &core::ptr::metadata(*self))
                .finish()
```

File: tests/ui/fmt/ptr-metadata.rs (hunk 1 above)
Comment (Enselic) [reply tests/ui/fmt/ptr-metadata.rs]: Done. I had to (with the current test code) add "regex" as an allowed library dependency, but it is already present as an allowed rustc dependency, so it's fine I think.

**Comment by Enselic** [comment]
Amanieu seems busy. Re-rolling reviewer.

r? libs

**Comment by thomcc** [comment]
This needs an FCP.

@rustbot fcp merge

**Comment by thomcc** [comment]
Oh right, wrong bot.

@rfcbot fcp merge

File: library/core/src/fmt/mod.rs [hunk 3]
```diff
@@ -2776,7 +2776,14 @@ impl Display for char {
 #[stable(feature = "rust1", since = "1.0.0")]
 impl<T: ?Sized> Pointer for *const T {
     fn fmt(&self, f: &mut Formatter<'_>) -> Result {
-        pointer_fmt_inner(self.expose_provenance(), f)
+        if core::mem::size_of::<<T as core::ptr::Pointee>::Metadata>() == 0 {
```
Comment (Amanieu) [inline library/core/src/fmt/mod.rs:2779]: It seems a bit strange to check the size of the metadata. Could we instead explicitly check that the metadata type is `()`?

Comment (Enselic) [reply library/core/src/fmt/mod.rs:2779]: I tried doing that at first but couldn't figure out how. I tried a bit more now but without success. I can't find any other place in the compiler/libraries that does that either.

Maybe you had some particular technique in mind?

Personally I get peace of mind thinking of this logic as "if the metadata has no size there is nothing of interest to show".

Comment (cuviper) [reply library/core/src/fmt/mod.rs:2779]: If we added a `'static` requirement to `Pointee::Metadata`, then you could compare `TypeId`. I'm not sure if there's any good reason it doesn't have that already.

Comment (Enselic) [reply library/core/src/fmt/mod.rs:2779]: Thanks, that seems to work. I think I can push a commit for that to see if CI passes without disrupting the FCP?

File: library/core/src/ptr/metadata.rs [hunk 4]
```diff
@@ -61,7 +61,7 @@ pub trait Pointee {
     // NOTE: Keep trait bounds in `static_assert_expected_bounds_for_metadata`
```
Comment (Enselic) [inline library/core/src/ptr/metadata.rs:61]: and now I see this note to keep things in sync....

File: library/core/src/fmt/mod.rs (hunk 3 above)
Comment (lukas-code) [reply library/core/src/fmt/mod.rs]: `Pointee::Metadata` can't be `'static`, because the metadata of `dyn Trait + 'a` is `DynMetadata<dyn Trait + 'a>` which is not `'static`.

To me it seems safer to drop the `'static` bound from the `type_id` intrinsic rather than potentially causing a trait system unsoundness by adding a `'static` bound that isn't actually satisfied by the compiler-builtin impls.

Comment (Enselic) [reply library/core/src/fmt/mod.rs]: That makes sense. I'll let CI continue to see if it catches it, and then go back to the code I had when the FCP started.

Comment (cuviper) [reply library/core/src/fmt/mod.rs]: You could use a local specialization:

```rust
trait IsUnit {
    fn is_unit() -> bool;
}

impl<T: ?Sized> IsUnit for T {
    #[inline(always)]
    default fn is_unit() -> bool { false }
}

impl IsUnit for () {
    #[inline(always)]
    fn is_unit() -> bool { true }
}
```

(It would be better as an associated const, but I don't think `min_specialization` allows that.)

Comment (Enselic) [reply library/core/src/fmt/mod.rs]: Thanks. I have now
* rebased on master to resolve conflict
* added a comment for future adventurers explaining why `Pointee::Metadata` can't be `'static`
* check for `()` with `IsUnit` instead of `size_of() == 0`

**Comment by thomcc** [comment]
Sorry, forgot to merge this.

@bors r+
