### PR TITLE
Fix ICE-133117: multiple never-pattern arm doesn't have false_edge_start_block

### LINKED ISSUE #130779: ICE: `None` in `compiler/rustc_mir_build/src/build/matches/mod.rs` with `feature(never_patterns)`
### Code
(reduced)
```Rust
#![feature(never_patterns)]

enum E { A }

fn main() {
    match E::A {
        ! |
        if true => {}
    }
}
```

(original)
```Rust
// In this regression test we check that a trailing `|` in an or-pattern just
// before the `if` token of a `match` guard will receive parser recovery with
// an appropriate error message.

enum E { A, B }

fn main() {
    match E::A {
        ! | //~ ERROR a trailing `|` is not allowed in an or-pattern
        if true => {
            let recovery_witness: bool = 0; //~ ERROR mismatched types
        }
    }
}
```

Command: `rustc ./7FFF.rs`

### Meta

`rustc --version --verbose`:
```
rustc 1.83.0-nightly (7042c269c 2024-09-23)
binary: rustc
commit-hash: 7042c269c166191cd5d8daf0409890903df7af57
commit-date: 2024-09-23
host: x86_64-apple-darwin
release: 1.83.0-nightly
LLVM version: 19.1.0
```

### Error output

```
error: a trailing `|` is not allowed in an or-pattern
 --> ./7FFF.rs:7:11
  |
7 |         ! |
  |         - ^
  |         |
  |         while parsing this or-pattern starting here
  |
help: remove the `|`
  |
7 -         ! |
7 +         ! 
  |

warning: the feature `never_patterns` is incomplete and may not be safe to use and/or cause compiler crashes
 --> ./7FFF.rs:1:12
  |
1 | #![feature(never_patterns)]
  |            ^^^^^^^^^^^^^^
  |
  = note: see issue #118155 <https://github.com/rust-lang/rust/issues/118155> for more information
  = note: `#[warn(incomplete_features)]` on by default

error: a never pattern is always unreachable
 --> ./7FFF.rs:8:20
  |
8 |         if true => {}
  |                    ^^
  |                    |
  |                    this will never be executed
  |                    help: remove this expression

error: mismatched types
 --> ./7FFF.rs:7:9
  |
7 |         ! |
  |         ^ a never pattern must be used on an uninhabited type
  |
  = note: the matched value is of type `E`

```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
thread 'rustc' panicked at compiler/rustc_mir_build/src/build/matches/mod.rs:1425:56:
called `Option::unwrap()` on a `None` value
stack backtrace:
   0:        0x117eeb3a7 - std::backtrace::Backtrace::create::h20048774a7df5a42
   1:        0x117eeb2f5 - std::backtrace::Backtrace::force_capture::ha939d1bf254d9107
   2:        0x115d1610e - std[d09fc85cb84ad7b]::panicking::update_hook::<alloc[d02d8d2ad132a946]::boxed::Box<rustc_driver_impl[4d5b267f1f304c4d]::install_ice_hook::{closure#0}>>::{closure#0}
   3:        0x117f06958 - std::panicking::rust_panic_with_hook::he2dff332e785153d
   4:        0x117f06595 - std::panicking::begin_panic_handler::{{closure}}::h873e97cbcdcf63ab
   5:        0x117f03d29 - std::sys::backtrace::__rust_end_short_backtrace::h81ffb9aee4e709dc
   6:        0x117f0620c - _rust_begin_unwind
   7:        0x11ab2063f - core::panicking::panic_fmt::h5235a0c22d55122a
   8:        0x11ab206e4 - core::panicking::panic::h0adbbbe009b54c8c
   9:        0x11ab205b8 - core::option::unwrap_failed::h1124b7069689f6d9
  10:        0x116c21408 - rustc_mir_build[a43d6420dfdfbc61]::build::matches::traverse_candidate::<rustc_mir_build[a43d6420dfdfbc61]::build::matches::Candidate, alloc[d02d8d2ad132a946]::vec::Vec<rustc_mir_build[a43d6420dfdfbc61]::build::matches::PatternExtraData>, alloc[d02d8d2ad132a946]::vec::into_iter::IntoIter<rustc_mir_build[a43d6420dfdfbc61]::build::matches::Candidate>, <rustc_mir_build[a43d6420dfdfbc61]::build::matches::MatchTreeBranch>::from_candidate::{closure#0}, <rustc_mir_build[a43d6420dfdfbc61]::build::matches::MatchTreeBranch>::from_candidate::{closure#1}, <rustc_mir_build[a43d6420dfdfbc61]::build::matches::MatchTreeBranch>::from_candidate::{closure#2}>
  11:        0x116c22b41 - <rustc_mir_build[a43d6420dfdfbc61]::build::Builder>::lower_match_tree
  12:        0x116c67413 - <rustc_mir_build[a43d6420dfdfbc61]::build::Builder>::expr_into_dest
  13:        0x116c696c1 - <rustc_mir_build[a43d6420dfdfbc61]::build::Builder>::expr_into_dest::{closure#0}
  14:        0x116c64c02 - <rustc_mir_build[a43d6420dfdfbc61]::build::Builder>::expr_into_dest
  15:        0x116c0459c - <rustc_mir_build[a43d6420dfdfbc61]::build::Builder>::ast_block_stmts
  16:        0x116c6aed3 - <rustc_mir_build[a43d6420dfdfbc61]::build::Builder>::in_scope::<<rustc_mir_build[a43d6420dfdfbc61]::build::Builder>::ast_block::{closure#0}, ()>
  17:        0x116c65406 - <rustc_mir_build[a43d6420dfdfbc61]::build::Builder>::expr_into_dest
  18:        0x116c696c1 - <rustc_mir_build[a43d6420dfdfbc61]::build::Builder>::expr_into_dest::{closure#0}
  19:        0x116c64c02 - <rustc_mir_build[a43d6420dfdfbc61]::build::Builder>::expr_into_dest
  20:        0x116bf5e59 - rustc_mir_build[a43d6420dfdfbc61]::build::construct_fn
  21:        0x116bf12ad - rustc_mir_build[a43d6420dfdfbc61]::build::mir_build
  22:        0x116ee9f1c - rustc_mir_transform[5a9fb0fb7b7274f7]::mir_built
  23:        0x11755a7aa - rustc_query_impl[f79aee8be8e599e2]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[f79aee8be8e599e2]::query_impl::mir_built::dynamic_query::{closure#2}::{closure#0}, rustc_middle[5020b1062cd3ce07]::query::erase::Erased<[u8; 8usize]>>
  24:        0x1173b45ae - rustc_query_system[7eae2b3ce34a8ac8]::query::plumbing::try_execute_query::<rustc_query_impl[f79aee8be8e599e2]::DynamicConfig<rustc_query_system[7eae2b3ce34a8ac8]::query::caches::VecCache<rustc_span[89bbbdd941a6c1aa]::def_id::LocalDefId, rustc_middle[5020b1062cd3ce07]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[f79aee8be8e599e2]::plumbing::QueryCtxt, false>
  25:        0x11756f1ca - rustc_query_impl[f79aee8be8e599e2]::query_impl::mir_built::get_query_non_incr::__rust_end_short_backtrace
  26:        0x116c39daf - rustc_mir_build[a43d6420dfdfbc61]::check_unsafety::check_unsafety
  27:        0x11755606a - rustc_query_impl[f79aee8be8e599e2]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[f79aee8be8e599e2]::query_impl::check_unsafety::dynamic_query::{closure#2}::{closure#0}, rustc_middle[5020b1062cd3ce07]::query::erase::Erased<[u8; 0usize]>>
  28:        0x1173a46a8 - rustc_query_system[7eae2b3ce34a8ac8]::query::plumbing::try_execute_query::<rustc_query_impl[f79aee8be8e599e2]::DynamicConfig<rustc_query_system[7eae2b3ce34a8ac8]::query::caches::VecCache<rustc_span[89bbbdd941a6c1aa]::def_id::LocalDefId, rustc_middle[5020b1062cd3ce07]::query::erase::Erased<[u8; 0usize]>>, false, false, false>, rustc_query_impl[f79aee8be8e599e2]::plumbing::QueryCtxt, false>
  29:        0x117583cb0 - rustc_query_impl[f79aee8be8e599e2]::query_impl::check_unsafety::get_query_non_incr::__rust_end_short_backtrace
  30:        0x116638162 - <rustc_middle[5020b1062cd3ce07]::hir::map::Map>::par_body_owners::<rustc_interface[1a7e4363985fe64]::passes::run_required_analyses::{closure#2}::{closure#0}>::{closure#0}
  31:        0x1166e442c - rustc_interface[1a7e4363985fe64]::passes::run_required_analyses
  32:        0x1166e6e40 - rustc_interface[1a7e4363985fe64]::passes::analysis
  33:        0x11755a4aa - rustc_query_impl[f79aee8be8e599e2]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[f79aee8be8e599e2]::query_impl::analysis::dynamic_query::{closure#2}::{closure#0}, rustc_middle[5020b1062cd3ce07]::query::erase::Erased<[u8; 1usize]>>
  34:        0x117313f4e - rustc_query_system[7eae2b3ce34a8ac8]::query::plumbing::try_execute_query::<rustc_query_impl[f79aee8be8e599e2]::DynamicConfig<rustc_query_system[7eae2b3ce34a8ac8]::query::caches::SingleCache<rustc_middle[5020b1062cd3ce07]::query::erase::Erased<[u8; 1usize]>>, false, false, false>, rustc_query_impl[f79aee8be8e599e2]::plumbing::QueryCtxt, false>
  35:        0x117566b37 - rustc_query_impl[f79aee8be8e599e2]::query_impl::analysis::get_query_non_incr::__rust_end_short_backtrace
  36:        0x115cbf647 - <rustc_interface[1a7e4363985fe64]::queries::QueryResult<&rustc_middle[5020b1062cd3ce07]::ty::context::GlobalCtxt>>::enter::<core[43b28bbecb023e0a]::result::Result<(), rustc_span[89bbbdd941a6c1aa]::ErrorGuaranteed>, rustc_driver_impl[4d5b267f1f304c4d]::run_compiler::{closure#0}::{closure#1}::{closure#5}>
  37:        0x115d1d29d - rustc_interface[1a7e4363985fe64]::interface::run_compiler::<core[43b28bbecb023e0a]::result::Result<(), rustc_span[89bbbdd941a6c1aa]::ErrorGuaranteed>, rustc_driver_impl[4d5b267f1f304c4d]::run_compiler::{closure#0}>::{closure#1}
  38:        0x115d0825c - std[d09fc85cb84ad7b]::sys::backtrace::__rust_begin_short_backtrace::<rustc_interface[1a7e4363985fe64]::util::run_in_thread_with_globals<rustc_interface[1a7e4363985fe64]::util::run_in_thread_pool_with_globals<rustc_interface[1a7e4363985fe64]::interface::run_compiler<core[43b28bbecb023e0a]::result::Result<(), rustc_span[89bbbdd941a6c1aa]::ErrorGuaranteed>, rustc_driver_impl[4d5b267f1f304c4d]::run_compiler::{closure#0}>::{closure#1}, core[43b28bbecb023e0a]::result::Result<(), rustc_span[89bbbdd941a6c1aa]::ErrorGuaranteed>>::{closure#0}, core[43b28bbecb023e0a]::result::Result<(), rustc_span[89bbbdd941a6c1aa]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[43b28bbecb023e0a]::result::Result<(), rustc_span[89bbbdd941a6c1aa]::ErrorGuaranteed>>
  39:        0x115d1f85a - <<std[d09fc85cb84ad7b]::thread::Builder>::spawn_unchecked_<rustc_interface[1a7e4363985fe64]::util::run_in_thread_with_globals<rustc_interface[1a7e4363985fe64]::util::run_in_thread_pool_with_globals<rustc_interface[1a7e4363985fe64]::interface::run_compiler<core[43b28bbecb023e0a]::result::Result<(), rustc_span[89bbbdd941a6c1aa]::ErrorGuaranteed>, rustc_driver_impl[4d5b267f1f304c4d]::run_compiler::{closure#0}>::{closure#1}, core[43b28bbecb023e0a]::result::Result<(), rustc_span[89bbbdd941a6c1aa]::ErrorGuaranteed>>::{closure#0}, core[43b28bbecb023e0a]::result::Result<(), rustc_span[89bbbdd941a6c1aa]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[43b28bbecb023e0a]::result::Result<(), rustc_span[89bbbdd941a6c1aa]::ErrorGuaranteed>>::{closure#1} as core[43b28bbecb023e0a]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  40:        0x117f1182b - std::sys::pal::unix::thread::Thread::new::thread_start::h1828de8d8adf3dc7
  41:     0x7ff801f5318b - __pthread_start


rustc version: 1.83.0-nightly (7042c269c 2024-09-23)
platform: x86_64-apple-darwin

query stack during panic:
#0 [mir_built] building MIR for `main`
#1 [check_unsafety] unsafety-checking `main`
#2 [analysis] running analysis passes on this crate
end of query stack
```

</p>
</details>

### Note
<strong> ICE location: </strong>

https://github.com/rust-lang/rust/blob/7042c269c166191cd5d8daf0409890903df7af57/compiler/rustc_mir_build/src/build/matches/mod.rs#L1416-L1441

@rustbot label +F-never_patterns

### LINKED ISSUE #133063: ICE: compiler/rustc_mir_build/src/build/matches/mod.rs `None`
auto-reduced (treereduce-rust):
````rust




fn split_last(_: &()) -> Option<(&i32, &i32)> {
    None
}

fn assign_twice() {
    loop {
        match () {
            
            (! | !) if let _ = split_last(&()) => {}
            _ => {}
        }
    }
}



````

original:
````rust
//@ check-pass

#![feature(if_let_guard)]

fn split_last(_: &()) -> Option<(&i32, &i32)> {
    None
}

fn assign_twice() {
    loop {
        match () {
            #[allow(irrefutable_let_patterns)]
            (! | !) if let _ = split_last(&()) => {}
            _ => {}
        }
    }
}

fn main() {}

````

Version information
````
rustc 1.84.0-nightly (251dc8ad8 2024-11-15)
binary: rustc
commit-hash: 251dc8ad84492c792a7600d8c5fef2ec868a36a7
commit-date: 2024-11-15
host: x86_64-unknown-linux-gnu
release: 1.84.0-nightly
LLVM version: 19.1.3

````

Possibly related line of code:
https://github.com/rust-lang/rust/blob/251dc8ad84492c792a7600d8c5fef2ec868a36a7/compiler/rustc_mir_build/src/build/matches/mod.rs#L1534-L1546

Command:
`/home/matthias/.rustup/toolchains/master/bin/rustc `

<details><summary><strong>Program output</strong></summary>
<p>

```
error[E0658]: `if let` guards are experimental
  --> /tmp/icemaker_global_tempdir.FVFwJhAXzIYI/rustc_testrunner_tmpdir_reporting.RbOs5qNwMqij/mvce.rs:13:21
   |
13 |             (! | !) if let _ = split_last(&()) => {}
   |                     ^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: see issue #51114 <https://github.com/rust-lang/rust/issues/51114> for more information
   = help: add `#![feature(if_let_guard)]` to the crate attributes to enable
   = note: this compiler was built on 2024-11-15; consider upgrading it if it is out of date
   = help: you can write `if matches!(<expr>, <pattern>)` instead of `if let <pattern> = <expr>`

error[E0658]: `!` patterns are experimental
  --> /tmp/icemaker_global_tempdir.FVFwJhAXzIYI/rustc_testrunner_tmpdir_reporting.RbOs5qNwMqij/mvce.rs:13:14
   |
13 |             (! | !) if let _ = split_last(&()) => {}
   |              ^
   |
   = note: see issue #118155 <https://github.com/rust-lang/rust/issues/118155> for more information
   = help: add `#![feature(never_patterns)]` to the crate attributes to enable
   = note: this compiler was built on 2024-11-15; consider upgrading it if it is out of date

error[E0658]: `!` patterns are experimental
  --> /tmp/icemaker_global_tempdir.FVFwJhAXzIYI/rustc_testrunner_tmpdir_reporting.RbOs5qNwMqij/mvce.rs:13:18
   |
13 |             (! | !) if let _ = split_last(&()) => {}
   |                  ^
   |
   = note: see issue #118155 <https://github.com/rust-lang/rust/issues/118155> for more information
   = help: add `#![feature(never_patterns)]` to the crate attributes to enable
   = note: this compiler was built on 2024-11-15; consider upgrading it if it is out of date

warning: unnecessary parentheses around pattern
  --> /tmp/icemaker_global_tempdir.FVFwJhAXzIYI/rustc_testrunner_tmpdir_reporting.RbOs5qNwMqij/mvce.rs:13:13
   |
13 |             (! | !) if let _ = split_last(&()) => {}
   |             ^     ^
   |
   = note: `#[warn(unused_parens)]` on by default
help: remove these parentheses
   |
13 -             (! | !) if let _ = split_last(&()) => {}
13 +             ! | ! if let _ = split_last(&()) => {}
   |

error: a never pattern is always unreachable
  --> /tmp/icemaker_global_tempdir.FVFwJhAXzIYI/rustc_testrunner_tmpdir_reporting.RbOs5qNwMqij/mvce.rs:13:51
   |
13 |             (! | !) if let _ = split_last(&()) => {}
   |                                                   ^^
   |                                                   |
   |                                                   this will never be executed
   |                                                   help: remove this expression

error[E0601]: `main` function not found in crate `mvce`
  --> /tmp/icemaker_global_tempdir.FVFwJhAXzIYI/rustc_testrunner_tmpdir_reporting.RbOs5qNwMqij/mvce.rs:17:2
   |
17 | }
   |  ^ consider adding a `main` function to `/tmp/icemaker_global_tempdir.FVFwJhAXzIYI/rustc_testrunner_tmpdir_reporting.RbOs5qNwMqij/mvce.rs`

error: mismatched types
  --> /tmp/icemaker_global_tempdir.FVFwJhAXzIYI/rustc_testrunner_tmpdir_reporting.RbOs5qNwMqij/mvce.rs:13:14
   |
13 |             (! | !) if let _ = split_last(&()) => {}
   |              ^ a never pattern must be used on an uninhabited type
   |
   = note: the matched value is of type `()`

error: mismatched types
  --> /tmp/icemaker_global_tempdir.FVFwJhAXzIYI/rustc_testrunner_tmpdir_reporting.RbOs5qNwMqij/mvce.rs:13:18
   |
13 |             (! | !) if let _ = split_last(&()) => {}
   |                  ^ a never pattern must be used on an uninhabited type
   |
   = note: the matched value is of type `()`

warning: irrefutable `if let` guard pattern
  --> /tmp/icemaker_global_tempdir.FVFwJhAXzIYI/rustc_testrunner_tmpdir_reporting.RbOs5qNwMqij/mvce.rs:13:24
   |
13 |             (! | !) if let _ = split_last(&()) => {}
   |                        ^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: this pattern will always match, so the guard is useless
   = help: consider removing the guard and adding a `let` inside the match arm
   = note: `#[warn(irrefutable_let_patterns)]` on by default

thread 'rustc' panicked at compiler/rustc_mir_build/src/build/matches/mod.rs:1540:76:
called `Option::unwrap()` on a `None` value
stack backtrace:
   0:     0x79ade605a3ba - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::h3e8890c320687803
   1:     0x79ade680414a - core::fmt::write::h8e02e323e721d5d3
   2:     0x79ade7c2cc51 - std::io::Write::write_fmt::hfa5fc2d5ad51eab4
   3:     0x79ade605a212 - std::sys::backtrace::BacktraceLock::print::hef9ddff43c45c466
   4:     0x79ade605c716 - std::panicking::default_hook::{{closure}}::he4ae1ef11715c038
   5:     0x79ade605c560 - std::panicking::default_hook::h4571154760051e3a
   6:     0x79ade50e4281 - std[575dabc3fc23637d]::panicking::update_hook::<alloc[488fcebc54bee2fb]::boxed::Box<rustc_driver_impl[530468506af41d6d]::install_ice_hook::{closure#0}>>::{closure#0}
   7:     0x79ade605ce28 - std::panicking::rust_panic_with_hook::h99e29fee3fbc2974
   8:     0x79ade605cbc6 - std::panicking::begin_panic_handler::{{closure}}::h66e3972102a7eb3e
   9:     0x79ade605a869 - std::sys::backtrace::__rust_end_short_backtrace::ha9860e2cc56614c6
  10:     0x79ade605c8bc - rust_begin_unwind
  11:     0x79ade2adde30 - core::panicking::panic_fmt::h21ce4ecfcb0cf215
  12:     0x79ade2e52c6c - core::panicking::panic::h2175426ea9d4336d
  13:     0x79ade40982f9 - core::option::unwrap_failed::hb947bce75902c03c
  14:     0x79ade6b48ff7 - rustc_mir_build[ce774ae811bc940]::build::matches::traverse_candidate::<&mut rustc_mir_build[ce774ae811bc940]::build::matches::Candidate, (), core[678332cb0ee15b78]::iter::adapters::rev::Rev<core[678332cb0ee15b78]::slice::iter::IterMut<rustc_mir_build[ce774ae811bc940]::build::matches::Candidate>>, <rustc_mir_build[ce774ae811bc940]::build::matches::Candidate>::visit_leaves_rev<<rustc_mir_build[ce774ae811bc940]::build::Builder>::lower_match_tree::{closure#1}>::{closure#0}, <rustc_mir_build[ce774ae811bc940]::build::matches::Candidate>::visit_leaves_rev<<rustc_mir_build[ce774ae811bc940]::build::Builder>::lower_match_tree::{closure#1}>::{closure#1}, <rustc_mir_build[ce774ae811bc940]::build::matches::Candidate>::visit_leaves_rev<<rustc_mir_build[ce774ae811bc940]::build::Builder>::lower_match_tree::{closure#1}>::{closure#2}>
  15:     0x79ade6b485cb - <rustc_mir_build[ce774ae811bc940]::build::Builder>::lower_match_tree
  16:     0x79ade6b26bb2 - <rustc_mir_build[ce774ae811bc940]::build::Builder>::expr_into_dest
  17:     0x79ade6b2804a - <rustc_mir_build[ce774ae811bc940]::build::Builder>::expr_into_dest
  18:     0x79ade748d32b - <rustc_mir_build[ce774ae811bc940]::build::Builder>::ast_block_stmts
  19:     0x79ade748c28c - <rustc_mir_build[ce774ae811bc940]::build::Builder>::ast_block
  20:     0x79ade6b25f0e - <rustc_mir_build[ce774ae811bc940]::build::Builder>::expr_into_dest
  21:     0x79ade6b29dda - <rustc_mir_build[ce774ae811bc940]::build::Builder>::expr_into_dest
  22:     0x79ade6b1cb49 - <rustc_mir_build[ce774ae811bc940]::build::Builder>::as_temp::{closure#0}
  23:     0x79ade6b27dbd - <rustc_mir_build[ce774ae811bc940]::build::Builder>::expr_into_dest
  24:     0x79ade6b2804a - <rustc_mir_build[ce774ae811bc940]::build::Builder>::expr_into_dest
  25:     0x79ade748d32b - <rustc_mir_build[ce774ae811bc940]::build::Builder>::ast_block_stmts
  26:     0x79ade748c28c - <rustc_mir_build[ce774ae811bc940]::build::Builder>::ast_block
  27:     0x79ade6b25f0e - <rustc_mir_build[ce774ae811bc940]::build::Builder>::expr_into_dest
  28:     0x79ade6b2804a - <rustc_mir_build[ce774ae811bc940]::build::Builder>::expr_into_dest
  29:     0x79ade6b378e9 - rustc_mir_build[ce774ae811bc940]::build::mir_build
  30:     0x79ade6807f04 - rustc_mir_transform[b6a0096f646ee25e]::mir_built
  31:     0x79ade6807ec7 - rustc_query_impl[bf1c9f3baad9eabf]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[bf1c9f3baad9eabf]::query_impl::mir_built::dynamic_query::{closure#2}::{closure#0}, rustc_middle[c94631e3827a547d]::query::erase::Erased<[u8; 8usize]>>
  32:     0x79ade6f12001 - rustc_query_system[d5846f7a9cb2c23f]::query::plumbing::try_execute_query::<rustc_query_impl[bf1c9f3baad9eabf]::DynamicConfig<rustc_query_system[d5846f7a9cb2c23f]::query::caches::VecCache<rustc_span[9778d555244491c7]::def_id::LocalDefId, rustc_middle[c94631e3827a547d]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[bf1c9f3baad9eabf]::plumbing::QueryCtxt, false>
  33:     0x79ade6f11bcd - rustc_query_impl[bf1c9f3baad9eabf]::query_impl::mir_built::get_query_non_incr::__rust_end_short_backtrace
  34:     0x79ade2c7bd71 - rustc_mir_build[ce774ae811bc940]::check_unsafety::check_unsafety
  35:     0x79ade703eafd - rustc_query_impl[bf1c9f3baad9eabf]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[bf1c9f3baad9eabf]::query_impl::check_unsafety::dynamic_query::{closure#2}::{closure#0}, rustc_middle[c94631e3827a547d]::query::erase::Erased<[u8; 0usize]>>
  36:     0x79ade703ed9c - rustc_query_system[d5846f7a9cb2c23f]::query::plumbing::try_execute_query::<rustc_query_impl[bf1c9f3baad9eabf]::DynamicConfig<rustc_query_system[d5846f7a9cb2c23f]::query::caches::VecCache<rustc_span[9778d555244491c7]::def_id::LocalDefId, rustc_middle[c94631e3827a547d]::query::erase::Erased<[u8; 0usize]>>, false, false, false>, rustc_query_impl[bf1c9f3baad9eabf]::plumbing::QueryCtxt, false>
  37:     0x79ade703ea41 - rustc_query_impl[bf1c9f3baad9eabf]::query_impl::check_unsafety::get_query_non_incr::__rust_end_short_backtrace
  38:     0x79ade6d4562c - rustc_interface[c18496298df4cf52]::passes::run_required_analyses
  39:     0x79ade762961e - rustc_interface[c18496298df4cf52]::passes::analysis
  40:     0x79ade76295ef - rustc_query_impl[bf1c9f3baad9eabf]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[bf1c9f3baad9eabf]::query_impl::analysis::dynamic_query::{closure#2}::{closure#0}, rustc_middle[c94631e3827a547d]::query::erase::Erased<[u8; 1usize]>>
  41:     0x79ade77dee6e - rustc_query_system[d5846f7a9cb2c23f]::query::plumbing::try_execute_query::<rustc_query_impl[bf1c9f3baad9eabf]::DynamicConfig<rustc_query_system[d5846f7a9cb2c23f]::query::caches::SingleCache<rustc_middle[c94631e3827a547d]::query::erase::Erased<[u8; 1usize]>>, false, false, false>, rustc_query_impl[bf1c9f3baad9eabf]::plumbing::QueryCtxt, false>
  42:     0x79ade77deb4e - rustc_query_impl[bf1c9f3baad9eabf]::query_impl::analysis::get_query_non_incr::__rust_end_short_backtrace
  43:     0x79ade76d963a - rustc_interface[c18496298df4cf52]::interface::run_compiler::<core[678332cb0ee15b78]::result::Result<(), rustc_span[9778d555244491c7]::ErrorGuaranteed>, rustc_driver_impl[530468506af41d6d]::run_compiler::{closure#0}>::{closure#1}
  44:     0x79ade7732e50 - std[575dabc3fc23637d]::sys::backtrace::__rust_begin_short_backtrace::<rustc_interface[c18496298df4cf52]::util::run_in_thread_with_globals<rustc_interface[c18496298df4cf52]::util::run_in_thread_pool_with_globals<rustc_interface[c18496298df4cf52]::interface::run_compiler<core[678332cb0ee15b78]::result::Result<(), rustc_span[9778d555244491c7]::ErrorGuaranteed>, rustc_driver_impl[530468506af41d6d]::run_compiler::{closure#0}>::{closure#1}, core[678332cb0ee15b78]::result::Result<(), rustc_span[9778d555244491c7]::ErrorGuaranteed>>::{closure#0}, core[678332cb0ee15b78]::result::Result<(), rustc_span[9778d555244491c7]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[678332cb0ee15b78]::result::Result<(), rustc_span[9778d555244491c7]::ErrorGuaranteed>>
  45:     0x79ade773326b - <<std[575dabc3fc23637d]::thread::Builder>::spawn_unchecked_<rustc_interface[c18496298df4cf52]::util::run_in_thread_with_globals<rustc_interface[c18496298df4cf52]::util::run_in_thread_pool_with_globals<rustc_interface[c18496298df4cf52]::interface::run_compiler<core[678332cb0ee15b78]::result::Result<(), rustc_span[9778d555244491c7]::ErrorGuaranteed>, rustc_driver_impl[530468506af41d6d]::run_compiler::{closure#0}>::{closure#1}, core[678332cb0ee15b78]::result::Result<(), rustc_span[9778d555244491c7]::ErrorGuaranteed>>::{closure#0}, core[678332cb0ee15b78]::result::Result<(), rustc_span[9778d555244491c7]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[678332cb0ee15b78]::result::Result<(), rustc_span[9778d555244491c7]::ErrorGuaranteed>>::{closure#1} as core[678332cb0ee15b78]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  46:     0x79ade7733d39 - std::sys::pal::unix::thread::Thread::new::thread_start::h1176f996a4a1b888
  47:     0x79ade908f39d - <unknown>
  48:     0x79ade911449c - <unknown>
  49:                0x0 - <unknown>

error: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: please make sure that you have updated to the latest nightly

note: rustc 1.84.0-nightly (251dc8ad8 2024-11-15) running on x86_64-unknown-linux-gnu

query stack during panic:
#0 [mir_built] building MIR for `assign_twice`
#1 [check_unsafety] unsafety-checking `assign_twice`
end of query stack
error: aborting due to 7 previous errors; 2 warnings emitted

Some errors have detailed explanations: E0601, E0658.
For more information about an error, try `rustc --explain E0601`.

```

</p>
</details>

@rustbot label +F-if_let_guard

### LINKED ISSUE #133117: ICE: `leaf_candidate.false_edge_start_block.is_some()` duplicate match arm
### Code

```Rust
fn main() {
    match () {
        (!|!) if true => {}
        (!|!) if true => {}
    }
}

```

### Meta

`rustc --version --verbose`:
```
rustc 1.84.0-nightly (917a50a03 2024-11-15)
binary: rustc
commit-hash: 917a50a03931a9861c19a46f3e2a02a28f1da936
commit-date: 2024-11-15
host: x86_64-unknown-linux-gnu
release: 1.84.0-nightly
LLVM version: 19.1.3
```

### Error output

```
error[E0658]: `!` patterns are experimental
 --> f.rs:3:10
  |
3 |         (!|!) if true => {}
  |          ^
  |
  = note: see issue #118155 <https://github.com/rust-lang/rust/issues/118155> for more information
  = help: add `#![feature(never_patterns)]` to the crate attributes to enable
  = note: this compiler was built on 2024-11-15; consider upgrading it if it is out of date

error[E0658]: `!` patterns are experimental
 --> f.rs:3:12
  |
3 |         (!|!) if true => {}
  |            ^
  |
  = note: see issue #118155 <https://github.com/rust-lang/rust/issues/118155> for more information
  = help: add `#![feature(never_patterns)]` to the crate attributes to enable
  = note: this compiler was built on 2024-11-15; consider upgrading it if it is out of date

error[E0658]: `!` patterns are experimental
 --> f.rs:4:10
  |
4 |         (!|!) if true => {}
  |          ^
  |
  = note: see issue #118155 <https://github.com/rust-lang/rust/issues/118155> for more information
  = help: add `#![feature(never_patterns)]` to the crate attributes to enable
  = note: this compiler was built on 2024-11-15; consider upgrading it if it is out of date

error[E0658]: `!` patterns are experimental
 --> f.rs:4:12
  |
4 |         (!|!) if true => {}
  |            ^
  |
  = note: see issue #118155 <https://github.com/rust-lang/rust/issues/118155> for more information
  = help: add `#![feature(never_patterns)]` to the crate attributes to enable
  = note: this compiler was built on 2024-11-15; consider upgrading it if it is out of date

warning: unnecessary parentheses around pattern
 --> f.rs:3:9
  |
3 |         (!|!) if true => {}
  |         ^   ^
  |
  = note: `#[warn(unused_parens)]` on by default
help: remove these parentheses
  |
3 -         (!|!) if true => {}
3 +         !|! if true => {}
  |

warning: unnecessary parentheses around pattern
 --> f.rs:4:9
  |
4 |         (!|!) if true => {}
  |         ^   ^
  |
help: remove these parentheses
  |
4 -         (!|!) if true => {}
4 +         !|! if true => {}
  |

error: a never pattern is always unreachable
 --> f.rs:3:26
  |
3 |         (!|!) if true => {}
  |                          ^^
  |                          |
  |                          this will never be executed
  |                          help: remove this expression

error: a never pattern is always unreachable
 --> f.rs:4:26
  |
4 |         (!|!) if true => {}
  |                          ^^
  |                          |
  |                          this will never be executed
  |                          help: remove this expression

error: mismatched types
 --> f.rs:3:10
  |
3 |         (!|!) if true => {}
  |          ^ a never pattern must be used on an uninhabited type
  |
  = note: the matched value is of type `()`

error: mismatched types
 --> f.rs:3:12
  |
3 |         (!|!) if true => {}
  |            ^ a never pattern must be used on an uninhabited type
  |
  = note: the matched value is of type `()`
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
thread 'rustc' panicked at compiler/rustc_mir_build/src/build/matches/mod.rs:1550:17:
assertion failed: leaf_candidate.false_edge_start_block.is_some()
stack backtrace:
   0:     0x79de1e881b0a - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::hf209b603f512c5df
   1:     0x79de1f003f26 - core::fmt::write::hb7459499d17d36c1
   2:     0x79de2042e891 - std::io::Write::write_fmt::h4275802de0932d6f
   3:     0x79de1e881962 - std::sys::backtrace::BacktraceLock::print::hfbfa2f755b02b3d5
   4:     0x79de1e883e66 - std::panicking::default_hook::{{closure}}::h807768543f95a41b
   5:     0x79de1e883cb0 - std::panicking::default_hook::h7a17744703ed785c
   6:     0x79de1d909571 - std[7202c64df357eec]::panicking::update_hook::<alloc[27366bf968cf5613]::boxed::Box<rustc_driver_impl[45f2b7ecc3390aac]::install_ice_hook::{closure#0}>>::{closure#0}
   7:     0x79de1e884578 - std::panicking::rust_panic_with_hook::h4fba84c8b130fcc8
   8:     0x79de1e884316 - std::panicking::begin_panic_handler::{{closure}}::h9a05dc892413e069
   9:     0x79de1e881fb9 - std::sys::backtrace::__rust_end_short_backtrace::hb562433a6e41eea6
  10:     0x79de1e88400c - rust_begin_unwind
  11:     0x79de1b2e1030 - core::panicking::panic_fmt::hb2b4d3a454bfbc1d
  12:     0x79de1c2b14ec - core::panicking::panic::h4826b1ec2849648d
  13:     0x79de1f2fab32 - rustc_mir_build[7b3a9d387328b746]::build::matches::traverse_candidate::<&mut rustc_mir_build[7b3a9d387328b746]::build::matches::Candidate, (), core[426ecb0f3488faf5]::iter::adapters::rev::Rev<core[426ecb0f3488faf5]::slice::iter::IterMut<rustc_mir_build[7b3a9d387328b746]::build::matches::Candidate>>, <rustc_mir_build[7b3a9d387328b746]::build::matches::Candidate>::visit_leaves_rev<<rustc_mir_build[7b3a9d387328b746]::build::Builder>::lower_match_tree::{closure#1}>::{closure#0}, <rustc_mir_build[7b3a9d387328b746]::build::matches::Candidate>::visit_leaves_rev<<rustc_mir_build[7b3a9d387328b746]::build::Builder>::lower_match_tree::{closure#1}>::{closure#1}, <rustc_mir_build[7b3a9d387328b746]::build::matches::Candidate>::visit_leaves_rev<<rustc_mir_build[7b3a9d387328b746]::build::Builder>::lower_match_tree::{closure#1}>::{closure#2}>
  14:     0x79de1f2fa14b - <rustc_mir_build[7b3a9d387328b746]::build::Builder>::lower_match_tree
  15:     0x79de1f2d86f2 - <rustc_mir_build[7b3a9d387328b746]::build::Builder>::expr_into_dest
  16:     0x79de1f2d9b8a - <rustc_mir_build[7b3a9d387328b746]::build::Builder>::expr_into_dest
  17:     0x79de1fcca02b - <rustc_mir_build[7b3a9d387328b746]::build::Builder>::ast_block_stmts
  18:     0x79de1fcc8f8c - <rustc_mir_build[7b3a9d387328b746]::build::Builder>::ast_block
  19:     0x79de1f2d7a4e - <rustc_mir_build[7b3a9d387328b746]::build::Builder>::expr_into_dest
  20:     0x79de1f2d9b8a - <rustc_mir_build[7b3a9d387328b746]::build::Builder>::expr_into_dest
  21:     0x79de1f2e9469 - rustc_mir_build[7b3a9d387328b746]::build::mir_build
  22:     0x79de1f007d04 - rustc_mir_transform[270f2df9b7743285]::mir_built
  23:     0x79de1f007cc7 - rustc_query_impl[fea741c774525841]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[fea741c774525841]::query_impl::mir_built::dynamic_query::{closure#2}::{closure#0}, rustc_middle[19aa9677ff432410]::query::erase::Erased<[u8; 8usize]>>
  24:     0x79de1f537781 - rustc_query_system[4942b57954000236]::query::plumbing::try_execute_query::<rustc_query_impl[fea741c774525841]::DynamicConfig<rustc_query_system[4942b57954000236]::query::caches::VecCache<rustc_span[7bb8b1398364d9ae]::def_id::LocalDefId, rustc_middle[19aa9677ff432410]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[fea741c774525841]::plumbing::QueryCtxt, false>
  25:     0x79de1f53734d - rustc_query_impl[fea741c774525841]::query_impl::mir_built::get_query_non_incr::__rust_end_short_backtrace
  26:     0x79de1b47ef01 - rustc_mir_build[7b3a9d387328b746]::check_unsafety::check_unsafety
  27:     0x79de1f87a87d - rustc_query_impl[fea741c774525841]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[fea741c774525841]::query_impl::check_unsafety::dynamic_query::{closure#2}::{closure#0}, rustc_middle[19aa9677ff432410]::query::erase::Erased<[u8; 0usize]>>
  28:     0x79de1f87ab1c - rustc_query_system[4942b57954000236]::query::plumbing::try_execute_query::<rustc_query_impl[fea741c774525841]::DynamicConfig<rustc_query_system[4942b57954000236]::query::caches::VecCache<rustc_span[7bb8b1398364d9ae]::def_id::LocalDefId, rustc_middle[19aa9677ff432410]::query::erase::Erased<[u8; 0usize]>>, false, false, false>, rustc_query_impl[fea741c774525841]::plumbing::QueryCtxt, false>
  29:     0x79de1f87a7c1 - rustc_query_impl[fea741c774525841]::query_impl::check_unsafety::get_query_non_incr::__rust_end_short_backtrace
  30:     0x79de1f761c2c - rustc_interface[923321855aedf668]::passes::run_required_analyses
  31:     0x79de1ffae75e - rustc_interface[923321855aedf668]::passes::analysis
  32:     0x79de1ffae72f - rustc_query_impl[fea741c774525841]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[fea741c774525841]::query_impl::analysis::dynamic_query::{closure#2}::{closure#0}, rustc_middle[19aa9677ff432410]::query::erase::Erased<[u8; 1usize]>>
  33:     0x79de1ffd5cee - rustc_query_system[4942b57954000236]::query::plumbing::try_execute_query::<rustc_query_impl[fea741c774525841]::DynamicConfig<rustc_query_system[4942b57954000236]::query::caches::SingleCache<rustc_middle[19aa9677ff432410]::query::erase::Erased<[u8; 1usize]>>, false, false, false>, rustc_query_impl[fea741c774525841]::plumbing::QueryCtxt, false>
  34:     0x79de1ffd59ce - rustc_query_impl[fea741c774525841]::query_impl::analysis::get_query_non_incr::__rust_end_short_backtrace
  35:     0x79de1fee593a - rustc_interface[923321855aedf668]::interface::run_compiler::<core[426ecb0f3488faf5]::result::Result<(), rustc_span[7bb8b1398364d9ae]::ErrorGuaranteed>, rustc_driver_impl[45f2b7ecc3390aac]::run_compiler::{closure#0}>::{closure#1}
  36:     0x79de1ff887d0 - std[7202c64df357eec]::sys::backtrace::__rust_begin_short_backtrace::<rustc_interface[923321855aedf668]::util::run_in_thread_with_globals<rustc_interface[923321855aedf668]::util::run_in_thread_pool_with_globals<rustc_interface[923321855aedf668]::interface::run_compiler<core[426ecb0f3488faf5]::result::Result<(), rustc_span[7bb8b1398364d9ae]::ErrorGuaranteed>, rustc_driver_impl[45f2b7ecc3390aac]::run_compiler::{closure#0}>::{closure#1}, core[426ecb0f3488faf5]::result::Result<(), rustc_span[7bb8b1398364d9ae]::ErrorGuaranteed>>::{closure#0}, core[426ecb0f3488faf5]::result::Result<(), rustc_span[7bb8b1398364d9ae]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[426ecb0f3488faf5]::result::Result<(), rustc_span[7bb8b1398364d9ae]::ErrorGuaranteed>>
  37:     0x79de1ff88beb - <<std[7202c64df357eec]::thread::Builder>::spawn_unchecked_<rustc_interface[923321855aedf668]::util::run_in_thread_with_globals<rustc_interface[923321855aedf668]::util::run_in_thread_pool_with_globals<rustc_interface[923321855aedf668]::interface::run_compiler<core[426ecb0f3488faf5]::result::Result<(), rustc_span[7bb8b1398364d9ae]::ErrorGuaranteed>, rustc_driver_impl[45f2b7ecc3390aac]::run_compiler::{closure#0}>::{closure#1}, core[426ecb0f3488faf5]::result::Result<(), rustc_span[7bb8b1398364d9ae]::ErrorGuaranteed>>::{closure#0}, core[426ecb0f3488faf5]::result::Result<(), rustc_span[7bb8b1398364d9ae]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[426ecb0f3488faf5]::result::Result<(), rustc_span[7bb8b1398364d9ae]::ErrorGuaranteed>>::{closure#1} as core[426ecb0f3488faf5]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  38:     0x79de1ff896b9 - std::sys::pal::unix::thread::Thread::new::thread_start::h10999df32e8f1e96
  39:     0x79de217b139d - <unknown>
  40:     0x79de2183649c - <unknown>
  41:                0x0 - <unknown>

error: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: please make sure that you have updated to the latest nightly

note: please attach the file at `/tmp/im/rustc-ice-2024-11-16T18_50_02-873945.txt` to your bug report

query stack during panic:
#0 [mir_built] building MIR for `main`
#1 [check_unsafety] unsafety-checking `main`
end of query stack
error: aborting due to 8 previous errors; 2 warnings emitted

For more information about this error, try `rustc --explain E0658`.
```

</p>
</details>

### PR DESCRIPTION
**Pull request by Shunpoco**
Fixes #133117 , and close fixes #133063 , fixes #130779 

In order to fix ICE-133117, at first I needed to tackle to ICE-133063 (this fixed 130779 as well).

### ICE-133063 and ICE-130779
This ICE is caused by those steps:
1. An arm has or-pattern, and all of the sub-candidates are never-pattern
2. In that case, all sub-candidates are removed in remove_never_subcandidates(). So the arm (candidate) has no sub-candidate.
3. In the current implementation, if there is no sub-candidate, the function assigns `pre_binding_block` into the candidate ([here](https://github.com/rust-lang/rust/blob/master/compiler/rustc_mir_build/src/builder/matches/mod.rs#L2002-L2004)). However, otherwise_block should be assigned to the candidate as well, because the otherwise_block is unwrapped in multiple place (like in lower_match_tree()). As a result, it causes the panic.

I simply added the same block as pre_binding_block into otherwise_block, but I'm wondering if there is a better block to assign to otherwise_block (is it ok to assign the same block into pre_binding and otherwise?)

### ICE-133117
This is caused by those steps:
1. There are two arms, both are or-pattern and each has one match-pair (in the test code, both are `(!|!)`), and the second arm has a guard.
2. In match_candidate() for the first arm, it expands the second arm’s sub-candidates as well ([here](https://github.com/rust-lang/rust/blob/master/compiler/rustc_mir_build/src/builder/matches/mod.rs#L1800-L1805)). As a result, the root candidate of the second arm is not evaluated/modified in match_candidate(). So a false_edge_start_block is not assigned to the candidate.
3. merge_trivial_subcandidates() is called against the candidate for the second arm. It just returns immediately because the candidate has a guard. So a flase_edge_start_block is not assigned to the candidate also in this function.
4. remove_never_subcandidates() is called against the candidate. Since all sub-candidates are never-pattern. they are removed.
5. In lower_match_tree(), since there is no sub-candidate for the candidate, the candidate itself is evaluated in visit_leave_rev ([here](https://github.com/rust-lang/rust/blob/master/compiler/rustc_mir_build/src/builder/matches/mod.rs#L1532)). Because the candidate has no false_edge_start_block, it causes the panic.

So I modified the order of if blocks in merge_trivial_subcandidates() to assign a false_edge_start_block if the candidate doesn't have.

### CODE REVIEW

**Comment by compiler-errors** [comment]
cc @Nadrieril

**Comment by Nadrieril** [comment]
r? Nadrieril, thanks for doing this I'll have a look when I get a moment

File: tests/ui/rfcs/rfc-0000-never_patterns/ICE-133063-never-arm-no-otherwise-block.rs [hunk 1]
```diff
@@ -0,0 +1,21 @@
...
+    loop {
+        match () {
+            (!| //~ ERROR: mismatched types
+            !) if let _ = split_last(&()) => {} //~ ERROR a never pattern is always unreachable
+            //~^ ERROR: mismatched types
+            //~^^ WARNING: irrefutable `if let` guard pattern [irrefutable_let_patterns]
+            _ => {}
+        }
+    }
+}
```
Comment (Nadrieril) [inline tests/ui/rfcs/rfc-0000-never_patterns/ICE-133063-never-arm-no-otherwise-block.rs:19]: Could you replace this with a type-correct test, so this test keeps being useful in the future if the implementation changes? In particular we may skip MIR lowering in case of a type error, which would render the current test useless.
```rust
fn foo(x: !) {
	match x {
		(! | !) if false => {}
		_ => {}
	}
}
```

File: tests/ui/rfcs/rfc-0000-never_patterns/ICE-133117-duplicate-never-arm.rs [hunk 2]
```diff
@@ -0,0 +1,12 @@
...
+
+fn main() {
+    match () {
+        (!|
+        //~^ ERROR: mismatched types
+        !) if true => {} //~ ERROR a never pattern is always unreachable
+        //~^ ERROR: mismatched types
+        (!|!) if true => {} //~ ERROR a never pattern is always unreachable
+    }
+}
```
Comment (Nadrieril) [inline tests/ui/rfcs/rfc-0000-never_patterns/ICE-133117-duplicate-never-arm.rs:12]: Same here, could you make the test type-correct:
```rust
#![feature(never_type)]
#![feature(never_patterns)]
#![allow(incomplete_features)]

fn foo(x: !) {
    match x {
        (!|!) if true => {}
        (!|!) if true => {}
    }
}
```

File: compiler/rustc_mir_build/src/builder/matches/mod.rs [hunk 3]
```diff
@@ -1940,6 +1940,10 @@ impl<'a, 'tcx> Builder<'a, 'tcx> {
     /// in match tree lowering.
     fn merge_trivial_subcandidates(&mut self, candidate: &mut Candidate<'_, 'tcx>) {
         assert!(!candidate.subcandidates.is_empty());
+        if candidate.false_edge_start_block.is_none() {
+            candidate.false_edge_start_block = candidate.subcandidates[0].false_edge_start_block;
+        }
+
```
Comment (Nadrieril) [inline compiler/rustc_mir_build/src/builder/matches/mod.rs:1946]: I'd rather not do this here; the invariant is that candidates with subcandidates shouldn't have `pre_binding`/`otherwise`/`false_edge_start` blocks, so we should only assign that after merge. This should be assigned in `remove_never_subcandidates` instead I think.

**Review by Nadrieril — CHANGES_REQUESTED** [review]

File: tests/ui/rfcs/rfc-0000-never_patterns/ICE-133063-never-arm-no-otherwise-block.rs (hunk 1 above)
Comment (Shunpoco) [reply tests/ui/rfcs/rfc-0000-never_patterns/ICE-133063-never-arm-no-otherwise-block.rs]: Addressed in https://github.com/rust-lang/rust/pull/135409/commits/d8a216b866ff238589005fb1ea4c54644d8d24bf.

Note: `x: !` can't avoid mismatched types error. So I use enum Void {} instead of it (other test codes in the folder do so).

File: tests/ui/rfcs/rfc-0000-never_patterns/ICE-133117-duplicate-never-arm.rs (hunk 2 above)
Comment (Shunpoco) [reply tests/ui/rfcs/rfc-0000-never_patterns/ICE-133117-duplicate-never-arm.rs]: Fixed in https://github.com/rust-lang/rust/pull/135409/commits/e7db0925d1441990ceb8236b5d4015f9a2ba333c.

File: compiler/rustc_mir_build/src/builder/matches/mod.rs (hunk 3 above)
Comment (Shunpoco) [reply compiler/rustc_mir_build/src/builder/matches/mod.rs]: Thanks. I modified it in https://github.com/rust-lang/rust/pull/135409/commits/481ed2d9319a28b770da60f4567e55f5cc053835.

**Comment by Nadrieril** [comment]
Looks good, thank you for investigating and fixing this :)

@bors r+
