### PR TITLE
Suggest the right help message for as_ref

### LINKED ISSUE #100605: `rustc` suggests `&None.as_ref()` as well as `None`
Given the following code: https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=9d89810932e63366d4910a3d8cca200e

```rust
fn takes_option(_arg: Option<&String>) {}

fn main() {
    takes_option(&None)
}
```

The current output is:

```
Compiling playground v0.0.1 (/playground)
error[[E0308]](https://doc.rust-lang.org/stable/error-index.html#E0308): mismatched types
 --> src/main.rs:4:18
  |
4 |     takes_option(&None)
  |     ------------ ^^^^^ expected enum `Option`, found `&Option<_>`
  |     |
  |     arguments to this function are incorrect
  |
  = note:   expected enum `Option<&String>`
          found reference `&Option<_>`
note: function defined here
 --> src/main.rs:1:4
  |
1 | fn takes_option(_arg: Option<&String>) {}
  |    ^^^^^^^^^^^^ ---------------------
help: you can convert from `&Option<T>` to `Option<&T>` using `.as_ref()`
  |
4 |     takes_option(&None.as_ref())
  |                  ~~~~~~~~~~~~~~
help: consider removing the borrow
  |
4 -     takes_option(&None)
4 +     takes_option(None)
  |

For more information about this error, try `rustc --explain E0308`.
error: could not compile `playground` due to previous error
```

The error is correct, but I think the diagnostic is wrong. The second recommendation to call `takes_option(None)` is sound, but the first one (`&None.as_ref()`) seems like bad advice.

This reproduces on `rustc` 1.61 (on my workstation), as well as 1.63 (stable channel in playground), 1.64 (beta channel in playground), and 1.65 (nightly channel in playground).

### PR DESCRIPTION
**Pull request by chenyukang**
Fixes #100605

### CODE REVIEW

**Comment by chenyukang** [comment]
I thought will broke some our tests,
surprise that we don't have a unittest to cover this error message.

File: compiler/rustc_infer/src/infer/error_reporting/mod.rs [hunk 1]
```diff
@@ -2078,7 +2078,8 @@ impl<'a, 'tcx> InferCtxt<'a, 'tcx> {
                             diag.span_suggestion(
                                 span,
                                 *msg,
-                                format!("{}.as_ref()", snippet),
+                                // issue# 100605, suggesting convert from &Option<T> to Option<&T>, remove the extra `&`
```
Comment (compiler-errors) [inline compiler/rustc_infer/src/infer/error_reporting/mod.rs:2081]: Can you tag this with `// HACK:` or something? I would like to get rid of this eventually, but I am mostly ok with landing this now as a mitigation, since we do similar things other places (where we don't have access to HIR to get the real expressions)

**Comment by compiler-errors** [comment]
Thanks 

@bors r+ rollup

**Review by WaffleLapkin — COMMENTED** [review]
I don't think this fixes the problem fully. We have at least 3 other unary operators, namely `*`, `!` and `-` that can return arbitrary values and for them the diagnostic is [still broken](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=f32af8926384ebf9f4217a0bf322d85a). Maybe we should to do something more general with method suggestions?...

**Comment by chenyukang** [comment]
> I don't think this fixes the problem fully. We have at least 3 other unary operators, namely `*`, `!` and `-` that can return arbitrary values and for them the diagnostic is [still broken](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=f32af8926384ebf9f4217a0bf322d85a). Maybe we should to do something more general with method suggestions?...

Yes, I didn't consider these cases, this need some extra work.
Maybe we can remove this hard coded part:

```console
5 |     takes_option(*none.as_ref());    // Suggests `*none.as_ref()`
  |     ------------ ^^^^^^^^^^^^^^
  |     |            |
  |     |            expected enum `Option`, found `&Option<String>`
  |     |            help: you can convert from `&Option<T>` to `Option<&T>` using `.as_ref()`: **`*none.as_ref().as_ref()`**
  |     arguments to this function are incorrect
  |
  = note:   expected enum `Option<&String>`
          found reference `&Option<String>`
```
