### PR TITLE
provide thread name to OS for Solarish systems

### LINKED ISSUE #62302: provide thread name to OS for Solarish systems
Both Solaris 11 and recentish Illumos provide the same `pthread_setname_np()` API.
While libstd can't presume the existence of the symbol, it seems like using `weak!` works sufficiently to set the thread name when necessary.

While the implementation is different, the API is basically the same for the purposes of `set_name()`.

The Linux implementation of `set_name()` will silently truncate the thread name, while the NetBSD (and I think, FreeBSD) will return an error. Since the `std::thread` implementation has no way to return an error right now, we need to choose between silent truncation or silent failure. Given the risk of mis-identification in truncation (it's likely that the unique part of the name is the end), it seems best to fail silently instead. On the plus side, this API has significantly more space than Linux's.

### PR DESCRIPTION
**Pull request by jlevon**
Fixes #62302

Passes a Linux bootstrap build. python x.py test src/tools/tidy happy.
I tested this with a small test binary that spawns a few threads, and verified
that:

 - on an illumos system lacking the libc function, the binary runs but no OS-level
    thread names are set
 - on an illumos system with the feature, the binary runs, and the thread names are
    visible and correct under tools like MDB, pstack, core dump, etc.

### CODE REVIEW

File: src/libstd/sys/unix/thread.rs [hunk 1]
```diff
@@ -1,3 +1,5 @@
+// Copyright 2019 Joyent, Inc.
```
Comment (Centril) [inline src/libstd/sys/unix/thread.rs]: As far as I know, we want things added to the standard library and the compiler to be licensed under the general terms as found in `{git_root}/LICENSE-{MIT,APACHE}`.

Comment (jlevon) [reply src/libstd/sys/unix/thread.rs]: It is. As per COPYRIGHT:

```
Copyrights in the Rust project are retained by their contributors. No
copyright assignment is required to contribute to the Rust project.

Some files include explicit copyright notices and/or license notices.
For full authorship information, see the version control history or
https://thanks.rust-lang.org

Except as otherwise noted (below and/or in individual files), Rust is
licensed under the Apache License, Version 2.0 <LICENSE-APACHE> or
<http://www.apache.org/licenses/LICENSE-2.0> or the MIT license
<LICENSE-MIT> or <http://opensource.org/licenses/MIT>, at your option.
```

**Comment by Dylan-DPC** [comment]
ping from triage @jlevon can you fix the license/copyright stuff? thanks

**Comment by jlevon** [comment]
@Dylan-DPC I already answered there, that there is nothing to fix. The original commenter seems to have confused copyright with licensing. I marked the  conversation as Resolved, perhaps that what you were waiting for?

**Comment by Mark-Simulacrum** [comment]
We prefer to keep the tree without Copyright markers for anyone/any organization; I am not a lawyer so I can't personally say whether the copyright marker you've left is separate from licensing or such (I definitely see your point, though!). Is it possible for you to remove the "Copyright" header on that file?

**Comment by jlevon** [comment]
Hi Mark, is that policy written up somewhere? As I already mentioned, COPYRIGHT explicitly mentions files may contain Copyright markers, and I couldn't find any other mention. Is there some specific issue with the above?

Joyent corporate policy requires a copyright notice to present (see https://github.com/joyent/rfd/blob/master/rfd/0164/README.md for details). This is presumably for legal reasons way beyond my ken as just another engineer.

**Comment by papertigers** [comment]
@Mark-Simulacrum does @jlevon's response clear things up?  Would love to see this merged as setting thread names on illumos is currently a no-op, and having them would help with debugging.

**Comment by Mark-Simulacrum** [comment]
Ah, missed that previous comment. I'm not sure if the policy is specifically recorded anywhere, and suspect that it probably isn't. I'm going to somewhat blindly r? @alexcrichton who I believe might have better answers for what we can/can't do here, or at least know who to ask.

**Comment by alexcrichton** [comment]
Thanks for the cc here. I won't really pretend I know how best to handle this myself, but @jlevon there's probably two ways to go about this. One is as been mentioned it'll be easiest if you're ok removing the comment and we can r+/merge. That follows the pattern of all the other PRs we receive, so it's easy to put in the "yep this is fine" bucket. The other strategy is that if you'd prefer this is left in we'll probably need to double check with someone (probably lawyers of some form). The "most accessible" ones we know of are from Mozilla, and they often take months to get back to us on issues like this. 

From my perspective it'd be great if we could make this as standard as other PRs are, but if you'd like I can try to set things in motion to get a consulation on the legal side of things to see what the implications of a comment are like this for us and how we'd handle it. This isn't a situation we've encountered in rust-lang/rust before (contributors asking to place license headers in files they modify) AFAIK and may take some time to navigate.

In any case I leave it up to you to let me know how you'd like to proceed!

**Comment by jlevon** [comment]
Thanks for the reply Alex. FWIW it's a copyright notice not a license header - very different things. Of course I can understand you might want to check with someone knowledgeable on the legal side, so please do so.

This is our corporate policy as I mentioned, as an individual contributor I have no control over this. However, I will also re-raise this issue internally and report back.

**Comment by alexcrichton** [comment]
Ah sorry yeah my legalese is very imprecise and flat out wrong most of the time. The main point I wanted to convey is that this sort of comment in a PR to rust-lang/rust is something that's nonstandard for us and we do not have a process in place for handling it. It'd be easiest if this could be removed but if it can't it'll likely just block this from landing for a significant amount of time, and I'd hate to prevent improvements from happening sooner!

**Comment by jlevon** [comment]
Yep, understood, thanks.

**Comment by hdhoang** [comment]
ping from triage @jlevon, any updates on this?

**Comment by jlevon** [comment]
Yes, good news, we have permission to drop the Copyright attribution lines for Rust repositories.

File: src/libstd/sys/unix/thread.rs [hunk 2]
```diff
@@ -122,8 +122,21 @@ impl Thread {
                                      name.as_ptr() as *mut libc::c_void);
         }
     }
+
+    #[cfg(target_os = "solaris")]
+    pub fn set_name(name: &CStr) {
+        weak! {
+            fn pthread_setname_np(
```
Comment (lzutao) [inline src/libstd/sys/unix/thread.rs]: We could use oneline:
```rust
fn pthread_setname_np(libc::pthread_t, *const libc::c_char) -> libc::c_int
```

**Comment by alexcrichton** [comment]
@bors: r+

Ok thanks for checking on your end @jlevon!
