### PR TITLE
Fix an ICE observed with an explicit tail-call in a default trait method

### LINKED ISSUE #144985: ICE from explicit tail call in defaulted trait method
### Code

```Rust
#![feature(explicit_tail_calls)]
#![expect(incomplete_features)]

trait Trait {}

trait Trait {
    fn foo(&self) {
        become self.foo();
    }
}
```

@rustbot labels +F-explicit_tail_calls +requires-incomplete-features

### Meta

Reproducible on the playground with version `1.91.0-nightly (2025-08-05 ec7c02612527d185c379)`

### Error output

```
error[E0428]: the name `Trait` is defined multiple times
 --> src/lib.rs:6:1
  |
4 | trait Trait {}
  | ----------- previous definition of the trait `Trait` here
5 |
6 | trait Trait {
  | ^^^^^^^^^^^ `Trait` redefined here
  |
  = note: `Trait` must be defined only once in the type namespace of this module

error: internal compiler error: compiler/rustc_middle/src/ty/instance.rs:633:21: failed to resolve instance for <Self as Trait>::foo
 --> src/lib.rs:7:5
  |
7 |     fn foo(&self) {
  |     ^^^^^^^^^^^^^
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
thread 'rustc' panicked at compiler/rustc_middle/src/ty/instance.rs:633:21:
Box<dyn Any>
stack backtrace:
   0: std::panicking::begin_panic::<rustc_errors::ExplicitBug>
   1: <rustc_errors::diagnostic::BugAbort as rustc_errors::diagnostic::EmissionGuarantee>::emit_producing_guarantee
   2: <rustc_errors::DiagCtxtHandle>::span_bug::<rustc_span::span_encoding::Span, alloc::string::String>
   3: rustc_middle::util::bug::opt_span_bug_fmt::<rustc_span::span_encoding::Span>::{closure#0}
   4: rustc_middle::ty::context::tls::with_opt::<rustc_middle::util::bug::opt_span_bug_fmt<rustc_span::span_encoding::Span>::{closure#0}, !>::{closure#0}
   5: rustc_middle::ty::context::tls::with_context_opt::<rustc_middle::ty::context::tls::with_opt<rustc_middle::util::bug::opt_span_bug_fmt<rustc_span::span_encoding::Span>::{closure#0}, !>::{closure#0}, !>
   6: rustc_middle::util::bug::span_bug_fmt::<rustc_span::span_encoding::Span>
   7: <rustc_middle::ty::instance::Instance>::expect_resolve
   8: <rustc_mir_build::check_tail_calls::TailCallCkVisitor as rustc_middle::thir::visit::Visitor>::visit_expr
   9: <rustc_mir_build::check_tail_calls::TailCallCkVisitor as rustc_middle::thir::visit::Visitor>::visit_expr
  10: <rustc_mir_build::check_tail_calls::TailCallCkVisitor as rustc_middle::thir::visit::Visitor>::visit_block
  11: <rustc_mir_build::check_tail_calls::TailCallCkVisitor as rustc_middle::thir::visit::Visitor>::visit_expr
  12: <rustc_mir_build::check_tail_calls::TailCallCkVisitor as rustc_middle::thir::visit::Visitor>::visit_expr
  13: <rustc_mir_build::check_tail_calls::TailCallCkVisitor as rustc_middle::thir::visit::Visitor>::visit_expr
      [... omitted 1 frame ...]
  14: rustc_mir_build::builder::build_mir
  15: rustc_mir_transform::mir_built
      [... omitted 1 frame ...]
  16: rustc_mir_build::check_unsafety::check_unsafety
      [... omitted 1 frame ...]
  17: <rustc_middle::ty::context::TyCtxt>::par_hir_body_owners::<rustc_interface::passes::run_required_analyses::{closure#1}::{closure#0}>::{closure#0}
  18: rustc_interface::passes::analysis
      [... omitted 1 frame ...]
  19: rustc_interface::passes::create_and_enter_global_ctxt::<core::option::Option<rustc_interface::queries::Linker>, rustc_driver_impl::run_compiler::{closure#0}::{closure#2}>::{closure#2}::{closure#0}
  20: rustc_interface::interface::run_compiler::<(), rustc_driver_impl::run_compiler::{closure#0}>::{closure#1}
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: please make sure that you have updated to the latest nightly

note: please attach the file at `/playground/rustc-ice-2025-08-06T07_27_59-27.txt` to your bug report

note: compiler flags: --crate-type lib -C embed-bitcode=no -C codegen-units=1 -C debuginfo=2

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [check_tail_calls] tail-call-checking `Trait::foo`
#1 [mir_built] building MIR for `Trait::foo`
#2 [check_unsafety] unsafety-checking `Trait::foo`
#3 [analysis] running analysis passes on this crate
end of query stack
For more information about this error, try `rustc --explain E0428`.
```

</p>
</details>

### PR DESCRIPTION
**Pull request by jakubadamw**
*[View all comments](https://triagebot.infra.rust-lang.org/gh-comments/rust-lang/rust/pull/145270)*

tracking issue: https://github.com/rust-lang/rust/issues/112788

Right now, explicit tail-calls cannot be used in functions that hold the `#[track_caller]` attribute. This check is performed on a resolved concrete instance of a function, which would be absent for a tail-call performed from the body of a default trait method. This PR fixes the issue by checking for the relevant attribute in default trait methods separately, without expecting a specific resolved instance.

Closes https://github.com/rust-lang/rust/issues/144985.

### CODE REVIEW

**Review by compiler-errors — CHANGES_REQUESTED** [review]
I don't think this is the right approach. Frankly, using `caller_ty` seems a bit unnecessary throughout `check_tail_calls`, though that's preexisting.

I think it's better if we refactor `check_tail_calls` to no longer rely at all on `caller_ty` and instead just have a body def id which corresponds to the item that has the THIR. We shouldn't need substs either -- those are always identity. 

Then we shouldn't need to use `Instance::expect_resolve` at all here.

**Comment by jakubadamw** [comment]
> I don't think this is the right approach. Frankly, using `caller_ty` seems a bit unnecessary throughout `check_tail_calls`, though that's preexisting.
> 
> I think it's better if we refactor `check_tail_calls` to no longer rely at all on `caller_ty` and instead just have a body def id which corresponds to the item that has the THIR. We shouldn't need substs either -- those are always identity.
> 
> Then we shouldn't need to use `Instance::expect_resolve` at all here.

Thank you for your feedback! I addressed it. There's a test failing in LLVM codegen, but this may be a pre-existing issue.

**Comment by jakubadamw** [comment]
> Unfortunately, that's a legitimate bug.
> 
> I think the problem with `#[track_caller]` is deeper than this -- specifically, I think we actually need to disallow calling `#[track_caller]` functions altogether (which I think we can only check for during monomorphization), or at least we need to be adjusting such calls to a "reify shim" when monomorphizing those tail calls, though I think that ends up leading to us pushing a stack frame which seems not good.
> 
> I'm gonna mark this as blocked on #145321 (edit: actually #144755)
> 
> @rustbot blocked
> 
> As a side-note, please make sure your commits are squashed. It's not a requirement that you have 1 commit per PR, but this PR definitely shouldn't need 4 commits for a single change like this :)

Thanks for elaborating on this!

So, as I gather from https://github.com/rust-lang/rust/issues/145321 and https://github.com/rust-lang/rust/issues/144755, if this is a pre-existing issue, would it be okay for us to move forward with this PR if we change the relevant test to be `check-pass` rather than `run-pass`, and let the codegen issue be independently covered by https://github.com/rust-lang/rust/issues/145321?

As for commits, I tend to make a commit per a logical chunk of work, and then in the course of PR’s review, only add new commits to make it clear what new changes have been made. But, of course, I’ll adjust and squash this, if you can confirm that converting the test to `check-pass` would be a sensible change.

**Comment by WaffleLapkin** [comment]
@jakubadamw could you rebase this PR?

**Comment by folkertdev** [comment]
@jakubadamw looks like you've opened some PRs here again, any chance you can rebase this? We'd like to move forward here, so if you're not able to that's also fine and we'll take it from here.

I tried to rebase locally but keep running into some weird linting errors, but maybe I'm missing something.

**Comment by folkertdev** [comment]
Turns out the troublesome lint was not properly registered. I've got things working on this branch https://github.com/rust-lang/rust/compare/main...folkertdev:rust:tail-call-trait-method, feel free to take things from there, otherwise I'll force push at some point.

**Comment by jakubadamw** [comment]
@WaffleLapkin, oops, my apologies, this one has slipped my attention/notifications. 🙂 
@folkertdev, thank you for picking this up, I pushed the tree of your branch to this one. 🙂 
@rustbot ready

File: tests/ui/explicit-tail-calls/default-trait-method.rs [hunk 1]
```diff
@@ -0,0 +1,38 @@
...
+#![feature(explicit_tail_calls)]
+#![expect(incomplete_features)]
+
+trait Trait {
+    fn bar(&self) -> usize {
+        123
+    }
+
+    fn foo(&self) -> usize {
+        #[allow(tail_call_track_caller)]
```
Comment (WaffleLapkin) [inline tests/ui/explicit-tail-calls/default-trait-method.rs:17]:
```suggestion
        #[expect(tail_call_track_caller)]
```

**Review by WaffleLapkin — APPROVED** [review]
r=me with nit

*[View changes since this review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/rust/145270/17584a181979f04f2aaad867332c22db1caa511a..fdd5b0d202b760000796abbb454b41a99fbb18d0)*

**Comment by folkertdev** [comment]
Also you can after making that fix just squash everything together into one commit

File: tests/ui/explicit-tail-calls/default-trait-method.rs (hunk 1 above)
Comment (folkertdev) [reply tests/ui/explicit-tail-calls/default-trait-method.rs:17]: Turns out this does not work

```
error: 2 diagnostics reported in JSON output but not expected in test file
tests/ui/explicit-tail-calls/default-trait-method.rs:17:18: WARN: this lint expectation is unfulfilled [unfulfilled_lint_expectations]
tests/ui/explicit-tail-calls/default-trait-method.rs:17:18: WARN: this lint expectation is unfulfilled [unfulfilled_lint_expectations]
```

I _think_ that is because there is some inconsistency between which HIR id is used, I actually suspect that we can/should emit this lint earlier so that we have more HIR stuff available.

I suspect that's blocked on some of the other work moving tail call logic to earlier stages, and in any case doesn't seem that relevant to this PR.

**Review by folkertdev — COMMENTED** [review]
I'll just squash this and then we can get it merged

*[View changes since this review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/rust/145270/17584a181979f04f2aaad867332c22db1caa511a..fdd5b0d202b760000796abbb454b41a99fbb18d0)*

File: tests/ui/explicit-tail-calls/default-trait-method.rs (hunk 1 above)
Comment (folkertdev) [reply tests/ui/explicit-tail-calls/default-trait-method.rs:17]: Actually, at least part of the issue is that the instance on `Struct` does not use `track_caller`, so the `expect` fails on that monomorphization anyway.

**Comment by jakubadamw** [comment]
@folkertdev, hey, apologies for not having been responsive, it was a very hectic week, and I didn't find the time. Thank you for doing the rebase for me!

**Comment by folkertdev** [comment]
Thanks for your work here!

@bors r=WaffleLapkin
