### PR TITLE
Fix cycle when debug-printing opaque types

### LINKED ISSUE #61577: cycle error building rustc with debug logging
When using `RUSTC_LOG` to debug building rustc itself, I ran into this error:

```
error[E0391]: cycle detected when processing `hir::def::<impl at src/librustc/hir/def.rs:255:1: 270:2>::present_items::{{opaque}}#0`
   --> src/librustc/hir/def.rs:262:35
    |
262 |     pub fn present_items(self) -> impl Iterator<Item=T> {
    |                                   ^^^^^^^^^^^^^^^^^^^^^
    |                                   |
    |                                   in this expansion of `desugaring of `existential type``
    |                                   in this macro invocation
    |
note: ...which requires processing `hir::def::<impl at src/librustc/hir/def.rs:255:1: 270:2>::present_items::{{opaque}}#0`...
   --> src/librustc/hir/def.rs:262:35
    |
262 |     pub fn present_items(self) -> impl Iterator<Item=T> {
    |                                   ^^^^^^^^^^^^^^^^^^^^^
    |                                   |
    |                                   in this expansion of `desugaring of `existential type``
    |                                   in this macro invocation
note: ...which requires processing `hir::def::<impl at src/librustc/hir/def.rs:255:1: 270:2>::present_items::{{opaque}}#0`...
   --> src/librustc/hir/def.rs:262:35
    |
262 |     pub fn present_items(self) -> impl Iterator<Item=T> {
    |                                   ^^^^^^^^^^^^^^^^^^^^^
    |                                   |
    |                                   in this expansion of `desugaring of `existential type``
    |                                   in this macro invocation
    = note: ...which again requires processing `hir::def::<impl at src/librustc/hir/def.rs:255:1: 270:2>::present_items::{{opaque}}#0`, completing the cycle
note: cycle used when processing `hir::def::<impl at src/librustc/hir/def.rs:255:1: 270:2>::present_items`
   --> src/librustc/hir/def.rs:262:5
    |
262 |     pub fn present_items(self) -> impl Iterator<Item=T> {
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

Repro:
1. Set `debug = true` in `config.toml`.
2. `./x.py build` to get a debug compiler (and go through several steps in stage 1 we want to skip).
3. `touch src/librustc/lib.rs`
4. `RUSTC_LOG=rustc::ty=debug ./x.py build --stage=1 --keep-stage=0 > dlog 2>&1`

The last step should rebuild librustc using a compiler with debugging enabled.  I imagine there is a faster way to do this, but these are the simplest instructions I could think of.

Is this known/expected?  I have no idea what the error means, but it makes debugging more difficult.

Currently on master (7cdaffd7962c4aae0cadd82baa241901b03f9458).

### PR DESCRIPTION
**Pull request by Aaron1011**
Fixes #61577

When printing an opaque type in non-verbose mode, we use the
`tcx.predicates_of` query to retrieve the opaque type's bounds for
pretty-printing. However, the pervasiveness of logging within librustc
means that we may already be executing `tcx.predicates_of` for the
opaque type we're trying to print, leading to a cycle error.

This commit adds a new 'no queries' thread-local flag to the pretty
printer. This flag is enabled during the computation of `predicates_of`
for opaque types, and causes us to print the opaque type in 'verbose'
mode (which does not require computing any additinal queries). This
should only affect debug logging for highly nested log messages, not any
user-visible output.

### CODE REVIEW

File: src/librustc_typeck/collect.rs [hunk 1]
```diff
@@ -2124,7 +2128,7 @@ fn explicit_predicates_of(
                     } else {
                         // named opaque types
                         predicates.extend(bounds_predicates);
-                        generics
+                        generics.clone()
```
Comment (matthewjasper) [inline src/librustc_typeck/collect.rs]: Is this `clone`ing a reference. I can't see why this is now necessary.

**Review by matthewjasper — COMMENTED** [review]
r=me with comment addressed

**Comment by Aaron1011** [comment]
@matthewjasper: Fixed
