### PR TITLE
correctly normalize constants

### LINKED ISSUE #63695: ICE caused by using a const_generic fn from a trait or impl
A function that compiles and runs successfully outside of a trait causes an ICE when it's in a trait.  The expectation is that this should work similarly to other generics on trait functions--while they will prevent a trait object reference, they should otherwise be allowed.  (On [playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=72aa50cd4b32c1cc5bbf896e3fc3d44a))

```rust
#![feature(const_generics)]
fn test<const A: i32>() -> i32 { A }

trait T {
    fn test<const A: i32>(&self) -> i32 { A }
}

struct S();

impl T for S {}

fn main() {
  let foo = S();
  println!("{}", test::<{8i32}>());
  println!("{}", foo.test::<{16i32}>());  // <- Causes ICE
}
```

Error and relevant backtrace:

```
error: internal compiler error: src/librustc_codegen_ssa/mir/operand.rs:79: unevaluated constant in `OperandRef::from_const`

thread 'rustc' panicked at 'Box<Any>', src/librustc_errors/lib.rs:643:9
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.34/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.34/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:47
   3: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:36
   4: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:200
   5: std::panicking::default_hook
             at src/libstd/panicking.rs:214
   6: rustc::util::common::panic_hook
   7: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:481
   8: std::panicking::begin_panic
   9: rustc_errors::Handler::bug
  10: rustc::util::bug::opt_span_bug_fmt::{{closure}}
  11: rustc::ty::context::tls::with_opt::{{closure}}
  12: rustc::ty::context::tls::with_context_opt
  13: rustc::ty::context::tls::with_opt
  14: rustc::util::bug::opt_span_bug_fmt
  15: rustc::util::bug::bug_fmt
  16: rustc_codegen_ssa::mir::operand::OperandRef<V>::from_const
  17: rustc_codegen_ssa::mir::operand::<impl rustc_codegen_ssa::mir::FunctionCx<Bx>>::codegen_operand
  18: rustc_codegen_ssa::mir::rvalue::<impl rustc_codegen_ssa::mir::FunctionCx<Bx>>::codegen_rvalue_operand
  19: rustc_codegen_ssa::mir::codegen_mir
  20: rustc_codegen_ssa::base::codegen_instance
  21: <rustc::mir::mono::MonoItem as rustc_codegen_ssa::mono_item::MonoItemExt>::define
  22: rustc_codegen_llvm::base::compile_codegen_unit::module_codegen
  23: rustc::dep_graph::graph::DepGraph::with_task
  24: rustc_codegen_llvm::base::compile_codegen_unit
  25: rustc_codegen_ssa::base::codegen_crate
  26: <rustc_codegen_llvm::LlvmCodegenBackend as rustc_codegen_utils::codegen_backend::CodegenBackend>::codegen_crate
  27: rustc::util::common::time
  28: rustc_interface::passes::BoxedGlobalCtxt::access::{{closure}}
  29: rustc_interface::passes::create_global_ctxt::{{closure}}
  30: rustc_interface::passes::BoxedGlobalCtxt::enter
  31: rustc_interface::queries::Query<T>::compute
  32: rustc_interface::queries::<impl rustc_interface::interface::Compiler>::ongoing_codegen
  33: rustc_interface::interface::run_compiler_in_existing_thread_pool
  34: std::thread::local::LocalKey<T>::with
  35: scoped_tls::ScopedKey<T>::set
  36: syntax::with_globals
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
query stack during panic:
end of query stack
error: aborting due to previous error


note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.39.0-nightly (2111aed0a 2019-08-17) running on x86_64-unknown-linux-gnu

note: compiler flags: -C codegen-units=1 -C debuginfo=2 --crate-type bin
```

### LINKED ISSUE #70317: Missing visit_const/fold_const when visit_ty/fold_ty exists and consts are relevant.
For visiting, I've identified these two examples:
https://github.com/rust-lang/rust/blob/5aa8f199c398644d9fc2bb9ac8cffd14f985686d/src/librustc/traits/structural_impls.rs#L256-L274

https://github.com/rust-lang/rust/blob/5aa8f199c398644d9fc2bb9ac8cffd14f985686d/src/librustc/ty/fold.rs#L976-L990
(the latter would need to handle `ty::ConstKind::Unevaluated` the same way `ty::Projection` is handled, as "unevaluated" consts are effectively projections)

For folding, I've listed one missing `fold_const` and two which are missing some recursion, in https://github.com/rust-lang/rust/issues/70125#issuecomment-602133708.

cc @varkor @yodaldevoid

### PR DESCRIPTION
**Pull request by lcnr**
closes #70317

implements https://github.com/rust-lang/rust/issues/70125#issuecomment-602133708

r? eddyb cc @varkor

### CODE REVIEW

File: src/librustc/query/mod.rs [hunk 1]
```diff
@@ -1114,9 +1114,9 @@ rustc_queries! {
         }
 
         /// Do not call this query directly: invoke `normalize_erasing_regions` instead.
-        query normalize_ty_after_erasing_regions(
-            goal: ParamEnvAnd<'tcx, Ty<'tcx>>
-        ) -> Ty<'tcx> {
+        query normalize_generic_arg_after_erasing_regions(
+            goal: ParamEnvAnd<'tcx, crate::ty::subst::GenericArg<'tcx>>
```
Comment (lcnr) [inline src/librustc/query/mod.rs]: importing `GenericArg` seems to fail for whatever reason

**Comment by lcnr** [comment]
currently causes `compiler_builtins to fail at https://github.com/rust-lang/compiler-builtins/blob/3e6327aa59214133fa74b3c51743b5ebde39526f/src/int/mod.rs#L50
```
error: internal compiler error: src/librustc_mir/monomorphize/collector.rs:603: collection encountered polymorphic constant
  --> /home/programming/.cargo/registry/src/github.com-1ecc6299db9ec823/compiler_builtins-0.1.25/src/int/mod.rs:50:5
   |
50 |     const ONE: Self;
   |     ^^^^^^^^^^^^^^^^

thread 'rustc' panicked at 'Box<Any>', <::std::macros::panic macros>:2:4
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

note: the compiler unexpectedly panicked. this is a bug.
```
Which I don't quite understand...

File: src/librustc/query/mod.rs (hunk 1 above)
Comment (eddyb) [reply src/librustc/query/mod.rs]: You need to do it in `src/librustc/ty/query/mod.rs` I believe, there's some weird macro shenanigans going on.

File: src/librustc/ty/normalize_erasing_regions.rs [hunk 2]
```diff
@@ -94,6 +94,10 @@ impl TypeFolder<'tcx> for NormalizeAfterErasingRegionsFolder<'tcx> {
     }
 
     fn fold_ty(&mut self, ty: Ty<'tcx>) -> Ty<'tcx> {
-        self.tcx.normalize_ty_after_erasing_regions(self.param_env.and(ty))
+        self.tcx.normalize_generic_arg_after_erasing_regions(self.param_env.and(GenericArg::from(ty))).expect_ty()
```
Comment (eddyb) [inline src/librustc/ty/normalize_erasing_regions.rs]: You can write `ty.into()` instead of `GenericArg::from(ty)`.

File: src/librustc/ty/normalize_erasing_regions.rs [hunk 3]
```diff
@@ -94,6 +94,10 @@ impl TypeFolder<'tcx> for NormalizeAfterErasingRegionsFolder<'tcx> {
...
+    }
+
+    fn fold_const(&mut self, c: &'tcx ty::Const<'tcx>) -> &'tcx ty::Const<'tcx> {
+        self.tcx.normalize_generic_arg_after_erasing_regions(self.param_env.and(GenericArg::from(c))).expect_const()
```
Comment (eddyb) [inline src/librustc/ty/normalize_erasing_regions.rs]: You can write `c.into()` instead of `GenericArg::from(c)`.

File: src/librustc/ty/normalize_erasing_regions.rs [hunk 4]
```diff
@@ -4,11 +4,11 @@
 //!
 //! The methods in this file use a `TypeFolder` to recursively process
 //! contents, invoking the underlying
-//! `normalize_ty_after_erasing_regions` query for each type found
-//! within. (This underlying query is what is cached.)
+//! `normalize_generic_arg_after_erasing_regions` query for each type
+//! and constant found within. (This underlying query is what is cached.)
```
Comment (eddyb) [inline src/librustc/ty/normalize_erasing_regions.rs]: "type and constant" -> "type or constant"

File: src/librustc/ty/subst.rs [hunk 5]
```diff
@@ -125,7 +125,15 @@ impl<'tcx> GenericArg<'tcx> {
     pub fn expect_ty(self) -> Ty<'tcx> {
         match self.unpack() {
             GenericArgKind::Type(ty) => ty,
-            _ => bug!("expected a type, but found another kind"),
+            _ => bug!("expected a type, but found another kind: {:?}", self),
```
Comment (eddyb) [inline src/librustc/ty/subst.rs]: We'll have to benchmark this in case it slows down other things.

File: src/librustc_trait_selection/traits/query/normalize.rs [hunk 6]
```diff
@@ -128,8 +128,7 @@ impl<'cx, 'tcx> TypeFolder<'tcx> for QueryNormalizer<'cx, 'tcx> {
             }
 
             ty::Projection(ref data) if !data.has_escaping_bound_vars() => {
-                // (*)
-                // (*) This is kind of hacky -- we need to be able to
+                // This is kind of hacky -- we need to be able to
```
Comment (eddyb) [inline src/librustc_trait_selection/traits/query/normalize.rs]: Please avoid changing comments, this is some preexisting notation.

File: src/test/ui/__check/issue-63695-1.rs [hunk 7]
```diff
@@ -0,0 +1,19 @@
...
+}
+
+struct S();
+
+impl T for S {}
+
+fn main() {
+  let foo = S();
+  assert_eq!(test::<{8i32}>(), 8);
+  assert_eq!(foo.test::<{16i32}>(), 16);  // <- Causes ICE
```
Comment (eddyb) [inline src/test/ui/__check/issue-63695-1.rs]: This is a method call example, this is the kind of thing that's impossible to support for now, as I've mentioned in at least one issue.

File: src/librustc/ty/normalize_erasing_regions.rs (hunk 2 above)
Comment (lcnr) [reply src/librustc/ty/normalize_erasing_regions.rs]: I actually favor being explicit here. In case you have a strong opinion on this I will ofc comply :laughing:

File: src/librustc_trait_selection/traits/query/normalize.rs (hunk 6 above)
Comment (lcnr) [reply src/librustc_trait_selection/traits/query/normalize.rs]: so the (*) is not used as some kind of link/reference and was forgotten during a refactor? :scream:

File: src/librustc/ty/normalize_erasing_regions.rs (hunk 2 above)
Comment (eddyb) [reply src/librustc/ty/normalize_erasing_regions.rs]: We use `.into()` throughout the compiler for this. The type doesn't really matter, if we could make implicit coercion do the conversion, we would.

File: src/librustc_trait_selection/traits/query/normalize.rs (hunk 6 above)
Comment (eddyb) [reply src/librustc_trait_selection/traits/query/normalize.rs]: It's weirder than that, you'll have to ask @nikomatsakis

Comment (lcnr) [reply src/librustc_trait_selection/traits/query/normalize.rs]: aah, its meant for path match arms.

File: src/test/ui/__check/issue-63695.rs [hunk 8]
```diff
@@ -0,0 +1,14 @@
+// run-pass
```
Comment (Centril) [inline src/test/ui/__check/issue-63695.rs]: The directory this test is in seems odd; shouldn't it be in src/test/ui/const-generics?

Comment (lcnr) [reply src/test/ui/__check/issue-63695.rs]: will move it to const-generics one this test actually runs, this makes it simpler to only test
these tests while developing

**Comment by lcnr** [comment]
this now also implements `visit_const` in the two cases mentioned in #70317 in a separate first commit.

If desired I can move that commit into different PR

**Comment by lcnr** [comment]
@eddyb this should now close #70317 afaict. 

It still does not fix the following though. So we might just
merge this without actually having any new tests.
```rust
#![feature(const_generics)]

struct S;
impl S {
    fn test<const A: i32>() -> i32 {
        A
    }
}

fn main() {
    S::test::<{ 16i32 }>();
}
```

**Review by eddyb — APPROVED** [review]

**Comment by eddyb** [comment]
@lcnr That example shouldn't compile, it has a const param in a `QPath::TypeRelative` segment.

As far as tests go, this would've prevented #70249, but that's about it.

@bors r+ Thanks!

**Comment by eddyb** [comment]
(editing my comment would retrigger `bors`, but I wasn't clear enough)

> this would've prevented #70249

I meant that it would've prevented the problem (missing normalization) that #70249 worked around.

File: src/test/ui/associated-const/defaults-cyclic-fail.rs [hunk 9]
```diff
@@ -1,9 +1,9 @@
 // build-fail
+//~^ ERROR cycle detected when normalizing `<() as Tr>::A`
 
 // Cyclic assoc. const defaults don't error unless *used*
 trait Tr {
     const A: u8 = Self::B;
-    //~^ ERROR cycle detected when const-evaluating + checking `Tr::A`
 
     const B: u8 = Self::A;
 }
```
Comment (lcnr) [inline src/test/ui/associated-const/defaults-cyclic-fail.rs]: This probably needs to be improved.

Might try to either add a valid  `DefId` to every used `ParamEnv` or try to get a contained def id in the `Ty` or `Const`.
Not yet sure what works best

Comment (eddyb) [reply src/test/ui/associated-const/defaults-cyclic-fail.rs]: Neither is a great idea IMO, because they would impair caching.

File: src/test/ui/associated-const/defaults-cyclic-fail.stderr [hunk 10]
```diff
@@ -1,30 +1,42 @@
-error[E0391]: cycle detected when const-evaluating + checking `Tr::A`
-  --> $DIR/defaults-cyclic-fail.rs:5:5
+error[E0391]: cycle detected when normalizing `<() as Tr>::A`
```
Comment (eddyb) [inline src/test/ui/associated-const/defaults-cyclic-fail.stderr]: I don't think there's a problem with this, btw, not everything has to have a `Span`.
The important thing is that the const-eval queries listed below are shown.

**Comment by lcnr** [comment]
ui tests work now.

Seems like something prevents mir inlining now? :disappointed:

**Comment by wesleywiser** [comment]
@lcnr It looks to me like inlining is succeeding. What's changed is that before we seemed to have an unevaluated `const` in the program which is now being evaluated as a result of your changes. `nightly` shows this in the MIR dump:

```
((*_3).0: alloc::raw_vec::RawVec<u32>) = const alloc::raw_vec::RawVec::<u32>::NEW; // bb0[4]: scope 2 at /rustc/1edd389cc4c7b5be7a3dd4fe4b986f6017018e54\src\liballoc\vec.rs:323:9: 323:41
                                 // ty::Const
                                 // + ty: alloc::raw_vec::RawVec<u32>
                                 // + val: Unevaluated(DefId(5:2799 ~ alloc[5377]::raw_vec[0]::{{impl}}[1]::NEW[0]), [u32], None)
                                 // mir::Constant
                                 // + span: /rustc/1edd389cc4c7b5be7a3dd4fe4b986f6017018e54\src\liballoc\vec.rs:323:20: 323:31
                                 // + user_ty: UserType(0)
                                 // + literal: Const { ty: alloc::raw_vec::RawVec<u32>, val: Unevaluated(DefId(5:2799 ~ alloc[5377]::raw_vec[0]::{{impl}}[1]::NEW[0]), [u32], None) }

```

This test should just be updated with the correct value.

**Comment by lcnr** [comment]
Should now be ready for merge

File: src/test/mir-opt/inline/inline-into-box-place.rs [hunk 11]
```diff
@@ -55,7 +55,7 @@ fn main() {
 //   StorageLive(_2);
 //   _2 = Box(std::vec::Vec<u32>);
 //   _4 = &mut (*_2);
-//   ((*_4).0: alloc::raw_vec::RawVec<u32>) = const alloc::raw_vec::RawVec::<u32>::NEW;
+//   ((*_4).0: alloc::raw_vec::RawVec<u32>) = const ByRef { alloc: Allocation { bytes: [4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], relocations: Relocations(SortedMap { data: [] }), undef_mask: UndefMask { blocks: [65535], len: Size { raw: 16 } }, size: Size { raw: 16 }, align: Align { pow2: 3 }, mutability: Not, extra: () }, offset: Size { raw: 0 } }: alloc::raw_vec::RawVec::<u32>;
```
Comment (eddyb) [inline src/test/mir-opt/inline/inline-into-box-place.rs]: @oli-obk This would be a good reason to tell apart `&alloc123` (the pointer) from `alloc123` (the value).

**Review by eddyb — APPROVED** [review]

**Comment by Centril** [comment]
Failed in https://github.com/rust-lang/rust/pull/70363#issuecomment-603487765, @bors r-

**Comment by lcnr** [comment]
seems like the representation of RawVec in mir was changed in another PR.

Will wait for #70371 to get merged first

**Comment by wesleywiser** [comment]
I think the issue is differences between 32-bit and 64-bit platforms:

```
Actual Line: "        ((*_4).0: alloc::raw_vec::RawVec<u32>) = const ByRef { alloc: Allocation { bytes: [4, 0, 0, 0, 0, 0, 0, 0], relocations: Relocations(SortedMap { data: [] }), undef_mask: UndefMask { blocks: [255], len: Size { raw: 8 } }, size: Size { raw: 8 }, align: Align { pow2: 2 }, mutability: Not, extra: () }, offset: Size { raw: 0 } }: alloc::raw_vec::RawVec::<u32>;"
Expected Line: "  ((*_4).0: alloc::raw_vec::RawVec<u32>) = const ByRef { alloc: Allocation { bytes: [4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], relocations: Relocations(SortedMap { data: [] }), undef_mask: UndefMask { blocks: [65535], len: Size { raw: 16 } }, size: Size { raw: 16 }, align: Align { pow2: 3 }, mutability: Not, extra: () }, offset: Size { raw: 0 } }: alloc::raw_vec::RawVec::<u32>;"

```

The failure happened on `Linux dist-i586-gnu-i586-i686-musl`.

@oli-obk Is there a nice way to deal with differences like this on 32-vs-64 bit platforms in `mir-opt` tests? Or should we just make this a 64-bit only test?

**Comment by eddyb** [comment]
@wesleywiser see https://github.com/rust-lang/rust/pull/69916.

**Comment by oli-obk** [comment]
Make it 64 bit for now and when we move to `--bless` we can make it a test for both platforms

**Comment by lcnr** [comment]
updated to test to only run on 64 bit machines, should be ready for merge again. :sweat_smile:
