### PR TITLE
fix lint regression in `non_upper_case_globals`

### LINKED ISSUE #110573: Regression in non_upper_case_globals lint level attribute on associated item
```rust
#![deny(warnings)]

pub struct Struct;

impl Struct {
    #[allow(non_upper_case_globals)]
    pub const Const: () = ();
}
```

```console
$ cargo +nightly-2023-04-19 check
    Finished dev [unoptimized + debuginfo] target(s) in 0.01s
```

```console
$ cargo +nightly-2023-04-20 check
error: associated constant `Const` should have an upper case name
 --> src/main.rs:7:15
  |
7 |     pub const Const: () = ();
  |               ^^^^^ help: convert the identifier to upper case: `CONST`
  |
note: the lint level is defined here
 --> src/main.rs:1:9
  |
1 | #![deny(warnings)]
  |         ^^^^^^^^
  = note: `#[deny(non_upper_case_globals)]` implied by `#[deny(warnings)]`
```

I believe the old behavior from nightly-2023-04-19 is correct.

The repro has nothing to do with trait impls so I believe #110513 was not supposed to have affected it.

### PR DESCRIPTION
**Pull request by Ezrashaw**
Fixes #110573

The issue also exists for inherent associated types (where I copied my impl from). `EarlyContext` is more involved to fix in this way, so I'll leave it be for now (note it's unstable so that's not urgent).

r? @compiler-errors

### CODE REVIEW

**Review by compiler-errors — CHANGES_REQUESTED** [review]
Hm.. I think this is a bit too complicated for what it's worth.

Can you just revert your original PR, and just check the associate const's [container](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_middle/ty/struct.AssocItem.html#structfield.container) similarly to how [`method_context`](https://doc.rust-lang.org/nightly/nightly-rustc/src/rustc_lint/nonstandard_style.rs.html#25-34) does to make sure that the `NonSnakeCase` lint only fires on inherent methods?

File: compiler/rustc_lint/src/nonstandard_style.rs [hunk 1]
```diff
@@ -177,6 +182,7 @@ impl EarlyLintPass for NonCamelCaseTypes {
             // trait impls where we should have warned for the trait definition already.
             ast::ItemKind::Impl(box ast::Impl { of_trait: None, items, .. }) => {
                 for it in items {
+                    // FIXME: this doesn't respect `#[allow(..)]` on the item itself.
```
Comment (compiler-errors) [inline compiler/rustc_lint/src/nonstandard_style.rs:185]: why not fix this too? you have the right machinery to do it, right?

**Comment by Ezrashaw** [comment]
@compiler-errors I reverted and re-implemented. I haven't fixed it for inherent associated types, would you like that in this PR or a followup? (note that it's an early lint so we'd need to convert it to `LateContext`)

File: tests/ui/lint/issue-110573.rs [hunk 2]
```diff
@@ -0,0 +1,12 @@
+// build-pass
```
Comment (compiler-errors) [inline tests/ui/lint/issue-110573.rs:1]:
```suggestion
// check-pass
```

File: compiler/rustc_lint/src/nonstandard_style.rs (hunk 1 above)
Comment (Ezrashaw) [reply compiler/rustc_lint/src/nonstandard_style.rs:185]: Whoops, posted at the same time.

**Review by compiler-errors — APPROVED** [review]
please squash this into one commit, and preferably (but I guess not required) fix the `NonCamelCaseTypes` lint for associated types too?

**Comment by Ezrashaw** [comment]
@compiler-errors I've implemented your review comments. The inherent associated types part is too complex to do right now, unrelated parts of the lint stop working when I tried to make it a late lint. It is and unstable feature so we might just leave it as is for now?
