### PR TITLE
make rustdoc::invalid_html_tags more robust

### LINKED ISSUE #145529: Self-closing SVG elements spanning multiple lines emit warnings
# Code

```rust
//! The following syntax outputs an error, even though it is a valid SVG!
//! It thinks that `<rect />` is unclosed when it spans multiple lines.
//!
//! <svg width="512" height="512" viewBox="0 0 512" fill="none" xmlns="http://www.w3.org/2000/svg">
//!     <rect
//!         width="256"
//!         height="256"
//!         fill="#5064C8"
//!         stroke="black"
//!     />
//! </svg>
//!
//! However, putting it on a single line works like expected:
//!
//! <svg width="512" height="512" viewBox="0 0 512" fill="none" xmlns="http://www.w3.org/2000/svg">
//!     <rect width="256" height="256" fill="#5064C8" stroke="black" />
//! </svg>
//!
//! "Normal" HTML elements like `<img />` do work like normal, even if they span multiple lines,
//! both with and without an outer div.
//!
//! <div>
//!     <img
//!         src="https://github.com/rust-lang/rust-artwork/blob/master/logo/rust-logo-512x512.png?raw=true"
//!         width="512"
//!         height="512"
//!     />
//! </div>

fn main() {
    println!("Hello, world!");
}
```

# Reproduction Steps

1. Embed an SVG into rustdoc with a self-closing element like `<rect />` or `<path />`, formatted to span multiple lines.
2. Run `cargo doc`.
3. See the output.

# Expected Outcome

No warnings.

# Actual Output

```console
$ cargo doc
 Documenting rustdoc_bug v0.1.0 (/home/joona/Programming/rustdoc_bug)
warning: unclosed HTML tag `rect`
 --> src/main.rs:4:9
  |
4 | //!     <rect
  |         ^^^^^
  |
  = note: `#[warn(rustdoc::invalid_html_tags)]` on by default

warning: `rustdoc_bug` (bin "rustdoc_bug" doc) generated 1 warning
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.17s
   Generated /home/joona/Programming/rustdoc_bug/target/doc/rustdoc_bug/index.html
```

# Version

rustdoc 1.89.0

# Additional Details

It's possible that this applies to any non-HTML elements. In my case, I ran into it with SVGs. I store (small) SVGs in my `src` directory, and use `#[doc = include_str!("path/to/image.svg")]` to embed them in docs, but I get warnings unless I force self-closing elements to span only one line.

### PR DESCRIPTION
**Pull request by lolbinarycat**
best reviewed a commit at a time.

I kept finding more edge case so I ended up having to make quite significant changes to the parser in order to make it preserve state across events and handle multiline attributes correctly.

fixes rust-lang/rust#145529

### CODE REVIEW

**Comment by klensy** [comment]
> pulldown-cmark splits html blocks

Used pulldown-cmark is slightly old for reasons, this can be changed in more recent versions.

File: src/librustdoc/passes/lint/html_tags.rs [hunk 1]
```diff
@@ -126,22 +128,33 @@ pub(crate) fn visit_item(cx: &DocContext<'_>, item: &Item, hir_id: HirId, dox: &
     };
 
     let p = Parser::new_with_broken_link_callback(dox, main_body_opts(), Some(&mut replacer))
-        .into_offset_iter();
+        .into_offset_iter()
+        .coalesce(|a, b| {
+            // for some reason, pulldown-cmark splits html blocks into seperate events for each line.
+            // we undo this, in order to handle multi-line tags.
+            match (a, b) {
+                ((Event::Html(_), ra), (Event::Html(_), rb)) if ra.end == rb.start => {
```
Comment (notriddle) [inline src/librustdoc/passes/lint/html_tags.rs:136]: This won't work if you wrap an html block in a markdown blockquote.

```markdown
$ cargo run --release -- --events
    Finished `release` profile [optimized] target(s) in 0.06s
     Running `target/release/pulldown-cmark --events`
> <div
> class="foo">
0..22: Start(BlockQuote(None))
2..22: Start(HtmlBlock)
2..7: Html(Borrowed("<div\n"))
9..22: Html(Borrowed("class=\"foo\">\n"))
2..22: End(HtmlBlock)
0..22: End(BlockQuote(None))
EOF
```

Comment (lolbinarycat) [reply src/librustdoc/passes/lint/html_tags.rs:136]: What do you think should be done instead, then? Unconditionally coalesce adjacent Html events, using `Cow::Owned` if needed? That could potentially also break the check that looks for `>` within the range..

The other option would be fully refactoring the parser to move its state into a struct so that it can be passed multiple strings and doesn't need to have the strings concatenated.  If we're doing that we can also refactor the tag parsing a bit so unfinished tags (those missing `>`) are actually treated as a separate error case from unclosed tags.

The latter would be more robust, but also a fair bit more work.

Comment (notriddle) [reply src/librustdoc/passes/lint/html_tags.rs:136]: > Unconditionally coalesce adjacent Html events, using Cow::Owned if needed?

I think that's the easiest way to handle it.

```rust
    while let Some((event, range)) = p.next() {
        match event {
            Event::Start(Tag::CodeBlock(_)) => in_code_block = true,
            Event::Html(text) | Event::InlineHtml(text) if !in_code_block => {
                extract_tags(&mut tags, &text, range, dox, &mut is_in_comment, &report_diag)
            }
            // for some reason, pulldown-cmark splits html blocks into seperate events for each line.
            // we undo this, in order to handle multi-line tags.
            Event::Tag(Tag::HtmlBlock) if !in_code_block => {
                let mut html_text = String::new();
                while let Some((event_inner, _)) = p.next() {
                    match event_inner {
                        Event::Html(text) => {
                            html_text.push_str(&text[..]);
                        }
                        Event::End(TagEnd::HtmlBlock) => break,
                        _ => unreachable!("html is supposed to be a leaf block"),
                    }
                }
                extract_tags(&mut tags, &html_text, range, dox, &mut is_in_comment, &report_diag);
            }
            Event::End(TagEnd::CodeBlock) => in_code_block = false,
            _ => {}
        }
    }
```

Comment (lolbinarycat) [reply src/librustdoc/passes/lint/html_tags.rs:136]: That still doesn't solve the issue of `>` from backquotes.   I think refactoring the parser is probably the correct thing to do here.

**Review by GuillaumeGomez — APPROVED** [review]

**Comment by GuillaumeGomez** [comment]
Seems like it's already a big improvement over the existing so let's merge it.

@notriddle: Based on your comments, you're not completely satisfied with the current fix so I suggest we do iterative improvements in follow-up(s).

Thanks to both of you in any case!

@bors r+ rollup
