### PR TITLE
Fail nicely when copying artefacts fails

### LINKED ISSUE #22124: ICE when copying artifacts fails
```
Vieras-Air:hello_world vieraproulx$ rustc main.rs
error: internal compiler error: unexpected panic
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: http://doc.rust-lang.org/complement-bugreport.html
note: run with `RUST_BACKTRACE=1` for a backtrace
thread 'rustc' panicked at 'called `Result::unwrap()` on an `Err` value: IoError { kind: PermissionDenied, desc: "couldn\'t create file", detail: Some("permission denied (Permission denied); path=main.o; mode=truncate; access=write") }', /Users/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-mac/build/src/libcore/result.rs:743
Vieras-Air:hello_world vieraproulx$ ls -l
total 32
-rw-r--r--  1 vieraproulx  staff  1572 Feb  9 18:28 main.0.o
-rw-r--r--  1 vieraproulx  staff   184 Feb  9 18:28 main.metadata.o
-rw-r--r--  1 root         staff  1572 Feb  9 18:25 main.o
-rw-r--r--  1 vieraproulx  staff    43 Feb  9 18:25 main.rs
Vieras-Air:hello_world vieraproulx$ RUST_BACKTRACE=1
Vieras-Air:hello_world vieraproulx$ rustc main.rs RUST_BACKTRACE=1
error: multiple input filenames provided
Vieras-Air:hello_world vieraproulx$ 
```

I have no idea why this is happening.

### PR DESCRIPTION
**Pull request by nagisa**
Fixes #22124

### CODE REVIEW

File: src/librustc_trans/back/write.rs [hunk 1]
```diff
@@ -664,8 +665,12 @@ pub fn run_passes(sess: &Session,
         if sess.opts.cg.codegen_units == 1 {
             // 1) Only one codegen unit.  In this case it's no difficulty
             //    to copy `foo.0.x` to `foo.x`.
-            fs::copy(&crate_output.with_extension(ext),
-                     &crate_output.path(output_type)).unwrap();
+            let input_path = &crate_output.with_extension(ext);
+            let output_path = &crate_output.path(output_type);
+            if let Err(e) = fs::copy(input_path, output_path) {
+                sess.err(&format!("could not copy {:?} to {:?}: {}",
+                                  input_path, output_path, e.description()));
```
Comment (alexcrichton) [inline src/librustc_trans/back/write.rs]: I think this may wish to rather just print `e` itself rather than just the `description` (as it has more information)

**Comment by nagisa** [comment]
@alexcrichton updated

File: src/librustc_trans/back/write.rs [hunk 2]
```diff
@@ -22,6 +22,7 @@ use syntax::codemap;
 use syntax::diagnostic;
 use syntax::diagnostic::{Emitter, Handler, Level, mk_handler};
 
+use std::error::Error;
```
Comment (alexcrichton) [inline src/librustc_trans/back/write.rs]: I think that this may be an unused import now.

File: src/librustc_trans/back/write.rs [hunk 3]
```diff
@@ -687,8 +692,11 @@ pub fn run_passes(sess: &Session,
     let link_obj = |output_path: &Path| {
         // Running `ld -r` on a single input is kind of pointless.
         if sess.opts.cg.codegen_units == 1 {
-            fs::copy(&crate_output.with_extension("0.o"),
-                     output_path).unwrap();
+            let input_path = &crate_output.with_extension("0.o");
+            if let Err(e) = fs::copy(input_path, output_path) {
+                sess.err(&format!("could not copy {:?} to {:?}: {}",
+                                  input_path, output_path, e));
+            }
```
Comment (alexcrichton) [inline src/librustc_trans/back/write.rs]: Perhaps these two blocks could be refactored to a helper function?

Comment (nagisa) [inline src/librustc_trans/back/write.rs]: This duplication was nagging me in the back of my head as well, but I found the functions different enough for duplication to be passable. I extracted graceful copy function into its own for now.

**Comment by alexcrichton** [comment]
@bors: r+ a941fdb rollup

Thanks!
