### PR TITLE
shrinking the deprecated method span

### LINKED ISSUE #84637: rustc_deprecated suggestions don't always cargo fix correctly
Rust version: stable 1.51.0

Given [the following code](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=d2ca5441d3a7474ee44cde763a2dc8a4) that uses [the `std::str::trim_left` function that is marked `rustc_deprecated`](https://github.com/rust-lang/rust/blob/4137088d9da94f693b287f35e2b17782c0b1a283/library/core/src/str/mod.rs#L1835-L1840):

```rust
fn main() {
    let foo = str::trim_left("   aoeu");
    
    let bar = "   aoeu".trim_left();
}
```

The current output is:

```
warning: use of deprecated associated function `core::str::<impl str>::trim_left`: superseded by `trim_start`
 --> src/main.rs:2:15
  |
2 |     let foo = str::trim_left("   aoeu");
  |               ^^^^^^^^^^^^^^ help: replace the use of the deprecated associated function: `trim_start`
  |
  = note: `#[warn(deprecated)]` on by default

warning: use of deprecated associated function `core::str::<impl str>::trim_left`: superseded by `trim_start`
 --> src/main.rs:4:25
  |
4 |     let bar = "   aoeu".trim_left();
  |                         ^^^^^^^^^ help: replace the use of the deprecated associated function: `trim_start`
```

If I run `cargo fix` on this example, I get this output:

```
warning: failed to automatically apply fixes suggested by rustc to crate `foo`

after fixes were automatically applied the compiler reported errors within these files:

  * src/main.rs

This likely indicates a bug in either rustc or cargo itself,
and we would appreciate a bug report! You're likely to see
a number of compiler warnings after this message which cargo
attempted to fix but failed. If you could open an issue at
https://github.com/rust-lang/rust/issues
quoting the full output of this command we'd be very appreciative!
Note that you may be able to make some more progress in the near-term
fixing code with the `--broken-code` flag

The following errors were reported:
error[E0425]: cannot find function `trim_start` in this scope
 --> src/main.rs:2:16
  |
2 |     let _foo = trim_start("   aoeu");
  |                ^^^^^^^^^^ not found in this scope
```

The `suggestion` from the `rustc_deprecated` attribute applied correctly to the usage on line 4, but it replaced `str::trim_left` with just `trim_start` on line 2. I expected it to change this line to `let foo = str::trim_start("   aoeu");`.

I'm not sure if the solution is to change the `^^^^^^` span marking to the leaf item that's deprecated. It *seems* like perhaps if the warning instead was:

```
2 |     let foo = str::trim_left("   aoeu");
  |                    ^^^^^^^^^ help: replace the use of the deprecated associated function: `trim_start`
```

then perhaps only the `trim_left` in `str::trim_left` would be replaced by rustfix? If so, I'd like to try my hand at fixing this. I've read some `rustc_deprecated` related issues, however, and I'm getting a strong here-be-dragons vibe from them, so I wanted to check with someone more knowledgeable about if I'm on the right track before the yaks eat me.

### PR DESCRIPTION
**Pull request by 0xPoe**
close https://github.com/rust-lang/rust/issues/84637

### CODE REVIEW

**Comment by hi-rustin** [comment]
I don't know if passing method span is a good solution. 😆

File: compiler/rustc_typeck/src/check/method/mod.rs [hunk 1]
```diff
@@ -445,7 +445,7 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
                     // them as well. It's ok to use the variant's id as a ctor id since an
                     // error will be reported on any use of such resolution anyway.
                     let ctor_def_id = variant_def.ctor_def_id.unwrap_or(variant_def.def_id);
-                    tcx.check_stability(ctor_def_id, Some(expr_id), span);
+                    tcx.check_stability(ctor_def_id, Some(expr_id), span, Some(method_name.span));
```
Comment (estebank) [inline compiler/rustc_typeck/src/check/method/mod.rs:448]: What happens if you change this and the change below to pass `method_name.span` on the already existing `span` parameter?

File: compiler/rustc_middle/src/middle/stability.rs [hunk 2]
```diff
@@ -300,6 +306,10 @@ impl<'tcx> TyCtxt<'tcx> {
                     let path = &with_no_trimmed_paths(|| self.def_path_str(def_id));
                     let kind = self.def_kind(def_id).descr(def_id);
                     let (message, lint) = deprecation_message(&depr_entry.attr, kind, path);
+                    let span = match method_span {
+                        None => span,
+                        Some(method_span) => method_span,
+                    };
```
Comment (estebank) [inline compiler/rustc_middle/src/middle/stability.rs:312]: This can be
```suggestion
                    let span = method_span.unwrap_or(span);
```

**Review by estebank — COMMENTED** [review]
I'm happy with the changes, and it'd be fine to pass in a new param, but can't we use the existing `Span` parameter?

File: compiler/rustc_typeck/src/check/method/mod.rs (hunk 1 above)
Comment (hi-rustin) [reply compiler/rustc_typeck/src/check/method/mod.rs:448]: Will get an error:
```
error[E0658]: use of unstable library feature 'fmt_internals': internal to format_args!
   --> /Users/rustin/ClionProjects/rust/library/core/src/macros/mod.rs:473:49
    |
473 |     ($dst:expr, $($arg:tt)*) => ($dst.write_fmt($crate::format_args!($($arg)*)))
    |                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = help: add `#![feature(fmt_internals)]` to the crate attributes to enable

error: aborting due to previous error

For more information about this error, try `rustc --explain E0658`.
error: could not compile `rustc-demangle`

```

Comment (hi-rustin) [reply compiler/rustc_typeck/src/check/method/mod.rs:448]: I also tried #[allow_internal_unstable(format_args)], but it still reports an error.
```rust
#[macro_export]
#[stable(feature = "rust1", since = "1.0.0")]
#[allow_internal_unstable(format_args)]
macro_rules! write {
    ($dst:expr, $($arg:tt)*) => ($dst.write_fmt($crate::format_args!($($arg)*)))
}
```
```rust
error[E0658]: use of unstable library feature 'fmt_internals': internal to format_args!
   --> /Users/rustin/ClionProjects/rust/library/core/src/macros/mod.rs:474:49
    |
474 |     ($dst:expr, $($arg:tt)*) => ($dst.write_fmt($crate::format_args!($($arg)*)))
    |                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = help: add `#![feature(fmt_internals)]` to the crate attributes to enable

error: aborting due to previous error

For more information about this error, try `rustc --explain E0658`.
error: could not compile `rustc-demangle`

```

Comment (hi-rustin) [reply compiler/rustc_typeck/src/check/method/mod.rs:448]: It's reported in stage1.

Comment (hi-rustin) [reply compiler/rustc_typeck/src/check/method/mod.rs:448]: https://github.com/rust-lang/rust/blob/d6d028369be9eb02d219506c0dd662a2f863fc18/compiler/rustc_span/src/lib.rs#L512

It looks like this is because `allow_internal_unstable` is not recognized when we use method_span.
