### PR TITLE
fix(test): Expose '--no-capture' in favor of `--nocapture`

### LINKED ISSUE #133073: `--nocapture` doesn't follow common CLI conventions, making it a stumbling block to people debugging failures
By convention, users would expect to type in `--no-capture`.  The fact that the argument is `--nocapture` trips people up, especially as they have to wait for their test to compile before they see the failure.  Without spelling suggestions, they need to then consult the help to then remember its without the middle `-`.  Unless someone is doing this all the time to build up muscle memory to counteract intuition, this will trip people up each time.

See also
- #24451
- https://hachyderm.io/@wezm@mastodon.decentralised.social/113485301109871075
- https://rust-lang.zulipchat.com/#narrow/channel/404371-t-testing-devex/topic/--nocapture/near/482538793

### PR DESCRIPTION
**Pull request by epage**
This improves consistency with commonly expected CLI conventions,
avoiding a common stutter people make when running tests (trying what
they expect and then having to check the docs to then user whats
accepted).

An alternative could have been to take a value, like `--capture <value>` (e.g. `pytest` does this).
Overall, we're shifting focus for features to custom test harnesses (see #134283).
Most of `pytest`s modes will likely be irrelevant in that situation.
As for the rest, its too early to tell which, if any, may be relevant,
so we're sticking with this small, quality of life improvement.

I expect we'll warn about `--nocapture` being deprecated in the future after a sufficient transition period has been allowed.
By deprecating `--nocapture`, we intend that custom test harnesses do
not need to support it for reasons outside of their own compatibility
requirements, much like the deprecation in #134283

I'm punting for now on the naming of `RUST_TEST_NOCAPTURE`.
I feel like T-testing-devex should do a wider look at environment
variables role in lib`test` before evaluating whether to
- Deprecate it in favor of the user passing CLI flags or the test runner
  providing its own config
- Deprecate in favor of `RUST_TEST_NO_CAPTURE`
- Deprecate in favor of `RUST_TEST_CAPTURE`

Other CLI flags were evaluated for casing consistency:
- `--logfile` has the same problem but was deprecated in #134283

Regarding the implementation, I moved `--nocapture` out of `optgroups()`, into `parse_opts()`, out of an abundance of caution in passing the options without a deprecated value to the usage generation.  However, the usage does not actually show optional flags, so this could potentially be dropped, simplifying the PR.

Note: `compiletest` added `--no-capture` instead of `--nocapture` in #134809

T-testing-devex FCP: https://github.com/rust-lang/rust/issues/133073#issuecomment-2486921104

Fixes #133073

### CODE REVIEW

File: library/test/src/cli.rs [hunk 1]
```diff
@@ -199,7 +199,10 @@ Test Attributes:
 /// otherwise creates a `TestOpts` object and returns it.
 pub fn parse_opts(args: &[String]) -> Option<OptRes> {
     // Parse matches.
-    let opts = optgroups();
+    let mut opts = optgroups();
+    // Flags hidden from `usage`
+    opts.optflag("", "nocapture", "Deprecated, use `--no-capture`");
```
Comment (epage) [inline library/test/src/cli.rs:204]: From PR description:

> Regarding the implementation, I moved `--nocapture` out of `optgroups()`, into `parse_opts()`, out of an abundance of caution in passing the options without a deprecated value to the usage generation.  However, the usage does not actually show optional flags, so this could potentially be dropped, simplifying the PR.

**Comment by jieyouxu** [comment]
You'll probably also have to adjust `compiletest` to use the new field name.

File: library/test/src/cli.rs [hunk 2]
```diff
@@ -446,16 +449,22 @@ fn get_color_config(matches: &getopts::Matches) -> OptPartRes<ColorConfig> {
...
 
-fn get_nocapture(matches: &getopts::Matches) -> OptPartRes<bool> {
-    let mut nocapture = matches.opt_present("nocapture");
-    if !nocapture {
-        nocapture = match env::var("RUST_TEST_NOCAPTURE") {
+fn get_capture(matches: &getopts::Matches) -> OptPartRes<bool> {
+    let no_capture = matches.opt_present("no-capture");
+    let nocapture = matches.opt_present("nocapture");
+    if nocapture {
+        let _ = write!(io::stderr(), "warning: `--nocapture` is deprecated, use `--no-capture`");
```
Comment (Noratrieb) [inline library/test/src/cli.rs:456]: This makes it impossible to have a command support both latest Rust and one or two Rusts back without a warning. In the compiler we always try to avoid such situations, I think libtest should do the same. Add the new flag now, the deprecate the old one in two versions or something like that.

**Comment by joboet** [comment]
I think Thom is more familiar with `test`.
r? @thomcc

File: src/tools/compiletest/src/executor.rs [hunk 3]
```diff
@@ -141,7 +141,7 @@ fn test_opts(config: &Config) -> test::TestOpts {
         logfile: None,
         run_tests: true,
         bench_benchmarks: true,
-        nocapture: config.nocapture,
+        capture: !config.nocapture,
```
[the remark this answers is not in the document]
Comment (epage) [reply src/tools/compiletest/src/executor.rs]: I went ahead and removed the rename

**Comment by Amanieu** [comment]
@rfcbot merge
