### PR TITLE
fix data race in thread::scope

### LINKED ISSUE #98498: Data race in thread::scope
The following code sometimes causes a data race to be reported by Miri:
```rust
#![feature(atomic_from_mut, inline_const)]
use std::sync::atomic::{AtomicBool, Ordering};

fn main() {
let mut some_bools = [const { AtomicBool::new(false) }; 10];

let view: &mut [bool] = AtomicBool::get_mut_slice(&mut some_bools);
assert_eq!(view, [false; 10]);
view[..5].copy_from_slice(&[true; 5]);

std::thread::scope(|s| {
    for t in &some_bools[..5] {
        s.spawn(move || assert_eq!(t.load(Ordering::Relaxed), true));
    }

    for f in &some_bools[5..] {
        s.spawn(move || assert_eq!(f.load(Ordering::Relaxed), false));
    }
});
}
```
Miri reports:
```
note: tracking was triggered
   --> /home/r/.rustup/toolchains/miri/lib/rustlib/src/rust/library/std/src/thread/scoped.rs:133:17
    |
133 |       let scope = Scope {
    |  _________________^
134 | |         data: ScopeData {
135 | |             num_running_threads: AtomicUsize::new(0),
136 | |             main_thread: current(),
...   |
140 | |         scope: PhantomData,
141 | |     };
    | |_____^ created allocation with id 1082
    |
    = note: inside `std::thread::scope::<[closure@atomic.rs:12:20: 20:2], ()>` at /home/r/.rustup/toolchains/miri/lib/rustlib/src/rust/library/std/src/thread/scoped.rs:133:17
note: inside `main` at atomic.rs:12:1
   --> atomic.rs:12:1
    |
12  | / std::thread::scope(|s| {
13  | |     for t in &some_bools[..5] {
14  | |         s.spawn(move || assert_eq!(t.load(Ordering::Relaxed), true));
15  | |     }
...   |
19  | |     }
20  | | });
    | |__^

error: Undefined Behavior: Data race detected between Deallocate on Thread(id = 0, name = "main") and Read on Thread(id = 2) at alloc1082+0x8 (current vector clock = VClock([114, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8]), conflicting timestamp = VClock([113, 0, 9, 9, 9, 0, 0, 0, 0, 0, 9]))
  --> atomic.rs:12:1
   |
12 | / std::thread::scope(|s| {
13 | |     for t in &some_bools[..5] {
14 | |         s.spawn(move || assert_eq!(t.load(Ordering::Relaxed), true));
15 | |     }
...  |
19 | |     }
20 | | });
   | |__^ Data race detected between Deallocate on Thread(id = 0, name = "main") and Read on Thread(id = 2) at alloc1082+0x8 (current vector clock = VClock([114, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8]), conflicting timestamp = VClock([113, 0, 9, 9, 9, 0, 0, 0, 0, 0, 9]))
   |
   = help: this indicates a bug in the program: it performed an invalid operation, and caused Undefined Behavior
   = help: see https://doc.rust-lang.org/nightly/reference/behavior-considered-undefined.html for further information

   = note: inside `main` at atomic.rs:12:1
```
The deallocation occurs when `scope` returns and its local variable `scope` gets deallocated.

The read occurs here (I am fairly sure):

https://github.com/rust-lang/rust/blob/7098a714e8dffe32ae10a27a18a3d73b23431a55/library/std/src/thread/scoped.rs#L58-L59

This reads the contents of the field `self.main_thread` *after* the `fetch_sub`. But the moment the `fetch_sub` is done, the memory backing `self` might be deallocated. That makes the read a potential use-after-free, and a race with the deallocation.

Cc @m-ou-se

### PR DESCRIPTION
**Pull request by RalfJung**
*[View all comments](https://triagebot.infra.rust-lang.org/gh-comments/rust-lang/rust/pull/98503)*

Puts the `ScopeData` into an `Arc` so it sticks around as long as we need it.
This means one extra `Arc::clone` per spawned scoped thread, which I hope is fine.

Fixes https://github.com/rust-lang/rust/issues/98498
r? @m-ou-se

### CODE REVIEW

**Comment by danielhenrymantilla** [comment]
Hmm, I raced with your PR, @RalfJung 😅: https://github.com/rust-lang/rust/pull/98504. At least now we can freely pick between the `Arc` and the `UnsafeCell` approaches

File: library/std/src/thread/scoped.rs [hunk 1]
```diff
@@ -33,7 +33,7 @@ pub struct Scope<'scope, 'env: 'scope> {
 ///
 /// See [`Scope::spawn`] for details.
 #[stable(feature = "scoped_threads", since = "1.63.0")]
-pub struct ScopedJoinHandle<'scope, T>(JoinInner<'scope, T>);
+pub struct ScopedJoinHandle<T>(JoinInner<T>);
```
Comment (CAD97) [inline library/std/src/thread/scoped.rs:36]: Removing a lifetime parameter from a stable item is API breaking, is it not?

Comment (RalfJung) [reply library/std/src/thread/scoped.rs:36]: Oh, I didn't realize this is public. *oops*

Comment (CAD97) [reply library/std/src/thread/scoped.rs]: For my own confidence: `PhantomData<&'scope>` is the correct existing variance here. (The lifetime variances involved in this API is subtle and controlled by `PhantomData`, not just normal references.)

**Comment by m-ou-se** [comment]
This looks like a good fix for the issue. We could look into a solution without an Arc later, although I doubt it matters much.

Thanks!

@bors r+

**Comment by m-ou-se** [comment]
The `PhantomData<&'scope T>` in ScopedJoinHandle is not the right one. It's correct for the variance of `'a`, but it makes a difference for dropck.

This snippet errors before this change, but compiles after this change:

```rust
use std::thread::ScopedJoinHandle;

fn x<'a>(_: &'a i32, h: ScopedJoinHandle<'a, i32>) -> ScopedJoinHandle<'a, i32> {
    h
}

fn main() {
    std::thread::scope(|s| {
        let mut v = Vec::new();
        {
            let a = 1;
            v.push(x(&a, s.spawn(|| 1)));
        }
    });
}
```

**Comment by m-ou-se** [comment]
(Whether that's a real issue.. I'm not sure yet. But it's a publicly visible change, although an extremely subtle one.)

**Comment by RalfJung** [comment]
So, was it previously invariant? Or should I replace `T` by `()`?

**Comment by RalfJung** [comment]
Looking at the old type, the data under lifetime `'scope` is `ScopeData`. So I switched to that type in the `PhantomType`. I would think that means the old behavior is preserved?

**Comment by m-ou-se** [comment]
Yeah, that sounds right. Testing now..

**Comment by m-ou-se** [comment]
Nope. It still compiles.

**Comment by RalfJung** [comment]
That... doesn't make any sense, or does it?

**Comment by m-ou-se** [comment]
`&'scope ScopeData` doesn't have a Drop impl. We need something that has `'scope` and might use that lifetime in its Drop impl.

**Comment by RalfJung** [comment]
The old code doesn't have such a thing either, though?

**Comment by m-ou-se** [comment]
It did: JoinInner's drop glue could drop a `Packet<'scope, T>`, which has a Drop implementation without `#[may_dangle]`.

File: library/std/src/thread/mod.rs [hunk 2]
```diff
@@ -1417,7 +1416,7 @@ impl<'scope, T> JoinInner<'scope, T> {
 /// [`thread::Builder::spawn`]: Builder::spawn
 /// [`thread::spawn`]: spawn
 #[stable(feature = "rust1", since = "1.0.0")]
-pub struct JoinHandle<T>(JoinInner<'static, T>);
+pub struct JoinHandle<T>(JoinInner<T>);
```
Comment (RalfJung) [inline library/std/src/thread/mod.rs:1419]: Oh *oops* I have edited another public type

Comment (RalfJung) [reply library/std/src/thread/mod.rs:1419]: Ah no it used a static lifetime, never mind.

**Comment by RalfJung** [comment]
Ah, this should do it. The lifetime needs to be on `Packet` since that has a `impl Drop` without `may_dangle`.

**Comment by m-ou-se** [comment]
Works!

(After adding a missing `'scope: 'a,` and `'scope, `.)

**Comment by RalfJung** [comment]
All right, now. Finally. Hopefully.^^

**Comment by m-ou-se** [comment]
Dropck is always an endless source of ~~extremely subtle issues~~ fun. ^^'

@bors r+

**Comment by joshtriplett** [comment]
👍 for beta backport.

**Review by vincenzopalazzo — APPROVED** [review]
LGTM!

**Review by CAD97 — APPROVED** [review]
Just as another set of eyes: the current change looks like it should be trivially invisible to public API. The extent of potentially-public-visible changes are:

- `Packet` now additionally inherits autotrait constraints from `Arc<scoped::ScopeData>`.
- `Scope` now inherits autotrait constraints from `Arc<ScopeData>` instead of `ScopeData`.

`ScopeData` is `Send + Sync + Unpin + UnwindSafe + RefUnwindSafe`, thus no public change is visible.

-----

A potential note for the future, though: `Scope` uses `&'a mut &'a mut ()` to achieve invariance over `'a`. This does accomplish this, but it *also* makes `Scope` not `UnwindSafe`.

**Comment by bjorn3** [comment]
@rust-lang/mods
