### PR TITLE
Don't access a static just for its size and alignment

### LINKED ISSUE #62189: Static cyclic references not compiled in current nightly rust version
Let's tying to compile this code.This code compiled ok on stable and on nightly-2019-06-17 (for example at rust play site)

```
struct Foo {
    foo: Option<&'static Foo>
}

static FOO: Foo = Foo {
    foo: Some(&FOO),
};

fn main() {
    println!("Hello, world!");
}
```

But in current  rustc 1.37.0-nightly (d3e2cec29 2019-06-26) compilation fails with message:

```
error[E0391]: cycle detected when const-evaluating `FOO`
 --> src/main.rs:6:1
  |
6 | static FOO: Foo = Foo {
  | ^^^^^^^^^^^^^^^^^^^^^
  |
note: ...which requires const-evaluating `FOO`...
 --> src/main.rs:6:1
  |
6 | static FOO: Foo = Foo {
  | ^^^^^^^^^^^^^^^^^^^^^
  = note: ...which again requires const-evaluating `FOO`, completing the cycle
note: cycle used when const-evaluating + checking `FOO`
 --> src/main.rs:6:1
  |
6 | static FOO: Foo = Foo {
  | ^^^^^^^^^^^^^^^^^^^^^

error: aborting due to previous error

For more information about this error, try `rustc --explain E0391`.
```

### PR DESCRIPTION
**Pull request by oli-obk**
cc @RalfJung 	

fixes #62189

### CODE REVIEW

File: src/librustc_mir/interpret/memory.rs [hunk 1]
```diff
@@ -535,6 +535,19 @@ impl<'mir, 'tcx, M: Machine<'mir, 'tcx>> Memory<'mir, 'tcx, M> {
         id: AllocId,
         liveness: AllocCheck,
     ) -> InterpResult<'static, (Size, Align)> {
+        // Allocations of `static` items
+        // Can't do this in the match argument, we may get cycle errors since the lock would
+        // be held throughout the match.
+        let alloc = self.tcx.alloc_map.lock().get(id);
```
Comment (RalfJung) [inline src/librustc_mir/interpret/memory.rs]: Isn't it very expensive to always try to get this global lock?

Also a comment should explain why this is done first.

Comment (RalfJung) [reply src/librustc_mir/interpret/memory.rs]: Maybe a better ordering here is to first lookup directly in `alloc_map` (that will cover the vast majority of cases), then ask the global map, and only then proceed with `get`.

**Comment by estebank** [comment]
`tidy error: /checkout/src/librustc_mir/interpret/memory.rs:538: line longer than 100 chars`

**Review by estebank — APPROVED** [review]

File: src/librustc_mir/interpret/memory.rs [hunk 2]
```diff
@@ -535,41 +535,41 @@ impl<'mir, 'tcx, M: Machine<'mir, 'tcx>> Memory<'mir, 'tcx, M> {
...
-        }
-        // The rest must be dead.
-        if let AllocCheck::MaybeDead = liveness {
-            // Deallocated pointers are allowed, we should be able to find
-            // them in the map.
-            Ok(*self.dead_alloc_map.get(&id)
-                .expect("deallocated pointers should all be recorded in `dead_alloc_map`"))
-        } else {
-            err!(DanglingPointerDeref)
+        let alloc_or_size_align = self.alloc_map.get_or(id, || {
```
Comment (RalfJung) [inline src/librustc_mir/interpret/memory.rs]: The point of `get_or` is to insert something in the map if there's nothing there yet. In case you don't want that, please just do `get_or(id, || Err(())` to avoid the kind of convoluted code you are writing here.

It might make sense to add a `get` to `AllocMap` doing exactly that? It can be implemented in terms of the rest of the interface, after all.

Comment (RalfJung) [reply src/librustc_mir/interpret/memory.rs]: Also please add comments explaining why we check `self.alloc_map` instead of calling `self.get`.

Comment (oli-obk) [reply src/librustc_mir/interpret/memory.rs]: :man_facepalming: 	I should not be hacking after dinner

File: src/librustc_mir/interpret/memory.rs [hunk 3]
```diff
@@ -535,41 +535,44 @@ impl<'mir, 'tcx, M: Machine<'mir, 'tcx>> Memory<'mir, 'tcx, M> {
...
-                let ty = self.tcx.type_of(did);
-                let layout = self.tcx.layout_of(ParamEnv::empty().and(ty)).unwrap();
-                return Ok((layout.size, layout.align.abi));
+        // Don't use `self.get` here as that will
+        // a) cause cycles in case `id` refers to a static
+        // b) duplicate a static's allocation in miri
+        match self.alloc_map.get_or(id, || Err(())) {
+            Ok((_, alloc)) => Ok((Size::from_bytes(alloc.bytes.len() as u64), alloc.align)),
+            Err(()) => {
+                // Can't do this in the match argument, we may get cycle errors since the lock would
```
Comment (RalfJung) [inline src/librustc_mir/interpret/memory.rs]:
```suggestion
                // Not a local allocation, check the global `tcx.alloc_map`.

                // Can't do this in the match argument, we may get cycle errors since the lock would
```

File: src/librustc_mir/interpret/memory.rs [hunk 4]
```diff
@@ -535,41 +535,44 @@ impl<'mir, 'tcx, M: Machine<'mir, 'tcx>> Memory<'mir, 'tcx, M> {
...
+                // be held throughout the match.
+                let alloc = self.tcx.alloc_map.lock().get(id);
+                match alloc {
+                    Some(GlobalAlloc::Static(did)) => {
+                        // Use size and align of the type
+                        let ty = self.tcx.type_of(did);
+                        let layout = self.tcx.layout_of(ParamEnv::empty().and(ty)).unwrap();
+                        return Ok((layout.size, layout.align.abi));
```
Comment (RalfJung) [inline src/librustc_mir/interpret/memory.rs]: I think you can remove the `return` here and below.

File: src/librustc_mir/interpret/memory.rs [hunk 5]
```diff
@@ -535,41 +535,44 @@ impl<'mir, 'tcx, M: Machine<'mir, 'tcx>> Memory<'mir, 'tcx, M> {
...
+                    Some(GlobalAlloc::Memory(alloc)) =>
+                        // Need to duplicate the logic here, because the global allocations have
+                        // different associated types than the interpreter-local ones
+                        Ok((Size::from_bytes(alloc.bytes.len() as u64), alloc.align)),
+                    Some(GlobalAlloc::Function(_)) => if let AllocCheck::Dereferencable = liveness {
+                        // The caller requested no function pointers.
+                        return err!(DerefFunctionPointer);
+                    } else {
+                        return Ok((Size::ZERO, Align::from_bytes(1).unwrap()));
+                    },
```
Comment (RalfJung) [inline src/librustc_mir/interpret/memory.rs]: This indentation looks weird. The `if` is the match arm, so it should be one level indented.

File: src/librustc_mir/interpret/memory.rs [hunk 6]
```diff
@@ -535,41 +535,48 @@ impl<'mir, 'tcx, M: Machine<'mir, 'tcx>> Memory<'mir, 'tcx, M> {
...
+                match alloc {
+                    Some(GlobalAlloc::Static(did)) => {
+                        // Use size and align of the type
+                        let ty = self.tcx.type_of(did);
+                        let layout = self.tcx.layout_of(ParamEnv::empty().and(ty)).unwrap();
+                        Ok((layout.size, layout.align.abi))
+                    },
+                    Some(GlobalAlloc::Memory(alloc)) =>
+                        // Need to duplicate the logic here, because the global allocations have
+                        // different associated types than the interpreter-local ones
```
Comment (RalfJung) [inline src/librustc_mir/interpret/memory.rs]:
```suggestion
                        // different associated types than the interpreter-local ones.
```

File: src/librustc_mir/interpret/memory.rs [hunk 7]
```diff
@@ -535,41 +535,48 @@ impl<'mir, 'tcx, M: Machine<'mir, 'tcx>> Memory<'mir, 'tcx, M> {
...
+            Ok((_, alloc)) => Ok((Size::from_bytes(alloc.bytes.len() as u64), alloc.align)),
+            Err(()) => {
+                // Not a local allocation, check the global `tcx.alloc_map`.
+
+                // Can't do this in the match argument, we may get cycle errors since the lock would
+                // be held throughout the match.
+                let alloc = self.tcx.alloc_map.lock().get(id);
+                match alloc {
+                    Some(GlobalAlloc::Static(did)) => {
+                        // Use size and align of the type
```
Comment (RalfJung) [inline src/librustc_mir/interpret/memory.rs]:
```suggestion
                        // Use size and align of the type.
```

**Review by RalfJung — APPROVED** [review]
r=me with these nits fixed and CI green

**Comment by RalfJung** [comment]
Something in [this rollup](https://github.com/rust-lang/rust/pull/63043) [broke Miri on macOS](https://github.com/rust-lang/miri/pull/862), and it seems likely that it's this PR:
```
thread 'rustc' panicked at 'deallocated pointers should all be recorded in `dead_alloc_map`', src/libcore/option.rs:1166:5
```

File: src/librustc_mir/interpret/memory.rs [hunk 8]
```diff
@@ -535,41 +535,48 @@ impl<'mir, 'tcx, M: Machine<'mir, 'tcx>> Memory<'mir, 'tcx, M> {
         id: AllocId,
         liveness: AllocCheck,
     ) -> InterpResult<'static, (Size, Align)> {
-        // Regular allocations.
-        if let Ok(alloc) = self.get(id) {
-            return Ok((Size::from_bytes(alloc.bytes.len() as u64), alloc.align));
-        }
-        // Function pointers.
-        if let Ok(_) = self.get_fn_alloc(id) {
```
Comment (RalfJung) [inline src/librustc_mir/interpret/memory.rs]: Ah, this is the bug that I missed. We no longer check the "machine" function pointers.

**Comment by nikomatsakis** [comment]
Reviewed by the compiler team:

[Accepted for beta backport](https://rust-lang.zulipchat.com/#narrow/stream/131828-t-compiler/topic/weekly.20meeting.202019-08-29.20.2354818/near/174457170)

**Comment by RalfJung** [comment]
Didn't this land before the current beta branched?

**Comment by nikomatsakis** [comment]
I'm going to remove the beta nominated label. It seems like it either landed or got rolle up or *something*.

**Comment by RalfJung** [comment]
I also last-minute backported it to stable. Maybe that's where the confusion comes from.

**Comment by Mark-Simulacrum** [comment]
This indeed made it into (current) beta I believe as part of a5e7bb3e2bae3e8d31c10de66e91cdcea42a97df.
