### PR TITLE
const fn: Improve wording

### LINKED ISSUE #59611: Weird error message for non-const const fns
```
const fn foo() { panic!() }

fn main() { }
```

```
   Compiling playground v0.0.1 (/playground)
error: can only call other `min_const_fn` within a `min_const_fn`
 --> src/main.rs:1:18
  |
1 | const fn foo() { panic!() }
  |                  ^^^^^^^^
  |
  = note: this error originates in a macro outside of the current crate (in Nightly builds, run with -Z external-macro-backtrace for more info)
```

The name `min_const_fn` seems meaningless to an end user. It should say something like "only call `const` functions within `const` functions."

### PR DESCRIPTION
**Pull request by JohnTitor**
fixes #59611

This might need discussion. Feel free to close this PR if we don't need to fix.

### CODE REVIEW

File: src/librustc_mir/transform/qualify_min_const_fn.rs [hunk 1]
```diff
@@ -326,7 +326,7 @@ fn check_terminator(
                     abi::Abi::Rust if tcx.is_min_const_fn(def_id) => {},
                     abi::Abi::Rust => return Err((
                         span,
-                        "can only call other `min_const_fn` within a `min_const_fn`".into(),
+                        "can only call other `const` within a `const`".into(),
```
Comment (varkor) [inline src/librustc_mir/transform/qualify_min_const_fn.rs]: Something like ```can only call another `const fn` within a `const` block``` sounds more natural.

Comment (Centril) [reply src/librustc_mir/transform/qualify_min_const_fn.rs]: Neither this PR nor the suggestion is accurate. This is *not* a const block (and with https://github.com/rust-lang/rfcs/pull/2632 it will not always behave in a similar fashion).

Moreover, I think we lose out on the difference between *stable* `const fn`s and unstable ones. This is the main point of `min_const_fn`s... I think we should check whether the current compiler can use unstable features and tweak the message based on that. E.g. a stable compiler can just talk about `const fn`s but the nightly compiler should emphasize the difference between stable and unstable ones.

Comment (oli-obk) [reply src/librustc_mir/transform/qualify_min_const_fn.rs]: Maybe change it to

```
can only call other stable `const fn` within a stable `const fn`
```

?

Comment (varkor) [reply src/librustc_mir/transform/qualify_min_const_fn.rs]: Ah, in that case we should make the error more explicit and add a note to the unstable const fn pointing out that it is undertake.

Comment (varkor) [reply src/librustc_mir/transform/qualify_min_const_fn.rs]: That is, it's not clear whether it's the containing function or the called function that is the problem (or both).

Comment (JohnTitor) [reply src/librustc_mir/transform/qualify_min_const_fn.rs]: The problem is to be used same wording without distinction, I think. Should we try to work on this?

**Comment by Dylan-DPC** [comment]
ping from triage @oli-obk any updates?

File: src/librustc_mir/transform/qualify_min_const_fn.rs (hunk 1 above)
Comment (oli-obk) [reply src/librustc_mir/transform/qualify_min_const_fn.rs]: kinda both. I'm not sure how easy it is to point to the unstable `const fn`, since it might be in another crate. We can just use a more verbose wording like

> can only call other `const fn` within a `const fn`, but `insert_fn_name_here` is not stable as `const fn`

Comment (JohnTitor) [reply src/librustc_mir/transform/qualify_min_const_fn.rs]: @oli-obk I changed wording.
