### PR TITLE
Permit uninhabited enums to cast into ints

### LINKED ISSUE #75647: Can't `as` cast Void to usize
```rust
enum Void { }
fn void_as_usize(x: Void) -> usize { x as usize } // fails, non-primitive cast
```
As reported on Zulip: https://rust-lang.zulipchat.com/#narrow/stream/122651-general/topic/void.20as.20usize

This works for simple enums with one or more variants, but for zero it fails, possibly due to interaction with `#[repr(C)]`. This kind of code can come up in macro code.

cc @RalfJung

### PR DESCRIPTION
**Pull request by Mark-Simulacrum**
This essentially reverts part of #6204; it is unclear why that [commit](https://github.com/rust-lang/rust/pull/6204/commits/c0f587de34f30b060df8a88c4068740e587b9340) was introduced, and I suspect no one remembers.

The changed code was only called from casting checks and appears to not affect any callers of that code (other than permitting this one case).

Fixes #75647.

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
@rust-lang/lang, could someone kick off an fcp merge here?

This permits uninhabited enums to be `as` cast to integral types. This code is UB to execute due to the presence of the uninhabited value, so we do not need to specify the behavior of such a cast. The primary known use is for macros to not need to special-case this, though I believe we do not currently know of any macros which want this (likely due to no searching having been done).

**Comment by RalfJung** [comment]
Out of curiosity, what *does* such a cast compile to?

I'll certainly have to add a Miri test that actually reaches such a cast just to make sure it does not explode in horrible ways.^^

**Comment by joshtriplett** [comment]
@rfcbot merge

**Comment by Mark-Simulacrum** [comment]
Pushed up a commit fixing `--emit=mir` with this PR.

```rust
pub enum Void {}
#[no_mangle]
pub fn bar(v: Void) -> usize {
    v as usize
}
```

MIR:

```
fn bar(_1: Void) -> usize {
    debug v => _1;                       // in scope 0 at t.rs:3:12: 3:13
    let mut _0: usize;                   // return place in scope 0 at t.rs:3:24: 3:29
    let mut _2: Void;                    // in scope 0 at t.rs:4:5: 4:6

    bb0: {
        StorageLive(_2);                 // scope 0 at t.rs:4:5: 4:6
        _2 = move _1;                    // scope 0 at t.rs:4:5: 4:6
        _0 = move _2 as usize (Misc);    // scope 0 at t.rs:4:5: 4:15
        StorageDead(_2);                 // scope 0 at t.rs:4:14: 4:15
        return;                          // scope 0 at t.rs:5:2: 5:2
    }
}
```

LLVM IR:

```
define i64 @bar() unnamed_addr #0 {
start:
  ret i64 undef
}
```

File: compiler/rustc_mir/src/interpret/cast.rs [hunk 1]
```diff
@@ -142,6 +144,17 @@ impl<'mir, 'tcx: 'mir, M: Machine<'mir, 'tcx>> InterpCx<'mir, 'tcx, M> {
         // Handle cast from a univariant (ZST) enum.
         match src.layout.variants {
             Variants::Single { index } => {
+                // This is dead code, because an uninhabited enum is UB to
+                // instantiate. But we want to behave nicely, so just return a 0
+                // value for the discriminant.
+                if let ty::Adt(adt, _) = src.layout.ty.kind {
```
Comment (RalfJung) [inline compiler/rustc_mir/src/interpret/cast.rs:150]: Usually we prefer to test the layout instead of the type, so can you check `src.layout.abi.is_uninhabited()` instead?

File: compiler/rustc_mir/src/interpret/cast.rs [hunk 2]
```diff
@@ -142,6 +144,17 @@ impl<'mir, 'tcx: 'mir, M: Machine<'mir, 'tcx>> InterpCx<'mir, 'tcx, M> {
...
+                    if adt.variants.is_empty() {
+                        return Err(InterpError::UndefinedBehavior(
```
Comment (RalfJung) [inline compiler/rustc_mir/src/interpret/cast.rs:152]: This should be `throw_ub!(Unreachable)`.

File: compiler/rustc_mir/src/interpret/cast.rs [hunk 3]
```diff
@@ -142,6 +144,17 @@ impl<'mir, 'tcx: 'mir, M: Machine<'mir, 'tcx>> InterpCx<'mir, 'tcx, M> {
         // Handle cast from a univariant (ZST) enum.
```
Comment (RalfJung) [inline compiler/rustc_mir/src/interpret/cast.rs:144]:
```suggestion
        // Handle cast from a ZST enum (0 or 1 variants).
```

File: compiler/rustc_mir/src/interpret/cast.rs [hunk 4]
```diff
@@ -142,6 +144,17 @@ impl<'mir, 'tcx: 'mir, M: Machine<'mir, 'tcx>> InterpCx<'mir, 'tcx, M> {
...
         match src.layout.variants {
             Variants::Single { index } => {
```
Comment (RalfJung) [inline compiler/rustc_mir/src/interpret/cast.rs:146]: @eddyb is it expected that uninhabited enums have `Variants::Single` layout?

Comment (RalfJung) [reply compiler/rustc_mir/src/interpret/cast.rs:146]: Answering myself: yes it is, `Single` doesn't mean "enum with 1 variant" but it means "layout with one variant" (as in, fields are not overlapping), and the only alternative is a more-than-1-variant layout (which can have overlapping fields), which certainly makes even less sense for uninhabited types.

**Review by RalfJung — APPROVED** [review]
The Miri changes LGTM.
I cannot comment on the other effects `is_payloadfree` might have.

**Comment by nikomatsakis** [comment]
@rfcbot fcp reviewed

**Comment by pickfire** [comment]
Should we add a test based on the issue?

**Comment by Mark-Simulacrum** [comment]
The PR already updates a pre-existing test; did you have something else in mind?

**Comment by pickfire** [comment]
Test for https://github.com/rust-lang/rust/issues/75647?

**Comment by ctrl-z-9000-times** [comment]
> The primary known use is for macros to not need to special-case this, though I believe we do not currently know of any macros which want this (likely due to no searching having been done).

Can confirm, this is an annoying corner case for my macro which generates custom enums.
