### PR TITLE
fix rustdoc stack overflow on mutually recursive Deref

### LINKED ISSUE #85037: [regression] 1.52 and 1.53 link to recursive methods in the sidebar, but those methods are not documented
### Code

I don't have time to make an MCVE right now.

Stable and beta: image

Nightly and 1.51: 
image

1.50: 
image

Either the methods should be documented, or they shouldn't be linked to.

cc @pnkfelix I suspect this is regression from the backports of https://github.com/rust-lang/rust/pull/84867.

### LINKED ISSUE #85095: rustdoc stack overflow on mutually recusive Deref implementation
I tried this code:

```rust
use std::ops::Deref;

pub struct A;
pub struct B;

impl Deref for A {
    type Target = B;

    fn deref(&self) -> &Self::Target {
        panic!()
    }
}

impl Deref for B {
    type Target = A;

    fn deref(&self) -> &Self::Target {
        panic!()
    }
}
```
Trying to run rustdoc with `rustdoc lib.rs`

I expected to see this happen: I'm not sure actually, probably an ICE, but I'd prefer it either detect and accept recursion, or detect and reject with a proper error message.

Instead, this happened: I get a stack overflow
```
thread 'rustc' has overflowed its stack
fatal runtime error: stack overflow
```
GDB tells me `rustdoc::html::render::sidebar_deref_methods` is on the stack around 17 thousand times
(when running in GDB, it actually segfaulted at `<alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter` instead of stack-overflowing)

`impl Deref<Target=A> for A` does not seems to pose problems

### Meta

`rustc --version --verbose`:
```
rustc 1.52.0 (88f19c6da 2021-05-03)
binary: rustc
commit-hash: 88f19c6dab716c6281af7602e30f413e809c5974
commit-date: 2021-05-03
host: x86_64-unknown-linux-gnu
release: 1.52.0
LLVM version: 12.0.0
```

### PR DESCRIPTION
**Pull request by trinity-1686a**
fix #85095
fix #85037

### CODE REVIEW

File: src/librustdoc/html/render/mod.rs [hunk 1]
```diff
@@ -2032,7 +2038,15 @@ fn sidebar_deref_methods(cx: &Context<'_>, out: &mut Buffer, impl_: &Impl, v: &V
...
+                        sidebar_deref_methods(
+                            cx,
+                            out,
+                            target_deref_impl,
+                            target_impls,
+                            already_seen,
+                        );
+                    }
                 }
             }
```
Comment (jyn514) [inline src/librustdoc/html/render/mod.rs:2051]: Please instead just remove this whole block, rustdoc no longer renders recursive Deref after https://github.com/rust-lang/rust/pull/84867 and removing the block should fix https://github.com/rust-lang/rust/issues/85037. Please add a test for that issue too.

File: src/test/rustdoc/issue-85095.rs [hunk 2]
```diff
@@ -0,0 +1,22 @@
+use std::ops::Deref;
```
Comment (jyn514) [inline src/test/rustdoc/issue-85095.rs:1]: Can you give this file a descriptive name instead of the issue number? "recursive-deref" or something is fine.

File: src/test/rustdoc/issue-85037.rs [hunk 3]
```diff
@@ -0,0 +1,22 @@
+use std::ops::Deref;
```
Comment (jyn514) [inline src/test/rustdoc/issue-85037.rs:1]: Same thing here, can you use a descriptive name?

**Review by jyn514 — APPROVED** [review]
r=me with the test names updated

**Comment by pietroalbini** [comment]
@bors p=100 treeclosed=100

Closing the tree to run maintenance on the AArch64 CI runners.
