### PR TITLE
[NLL] Clean up handling of type annotations

### LINKED ISSUE #46702: figure out how to integrate constants and the MIR type checker
Currently the MIR type checker has some kind of hacky code to figure out what sorts of well-formedness constraints are present on a constant. The values of constants now are "post normalization" and don't give us ready access to what we need. As the comment from the code says:

```rust
                // FIXME(#46702) -- We need some way to get the predicates
                // associated with the "pre-evaluated" form of the
                // constant. For example, consider that the constant
                // may have associated constant projections (`<Foo as
                // Trait<'a, 'b>>::SOME_CONST`) that impose
                // constraints on `'a` and `'b`. These constraints
                // would be lost if we just look at the normalized
                // value.
```

### LINKED ISSUE #54943: NLL doesn't check that user type annotations are well-formed in unreachable code
#54942 checks well-formedness in the general case, but unreachable code is deleted before NLL can check it. 

For example, [this test](https://github.com/rust-lang/rust/blob/0e07c4281c343e9e15a0a8fca79538ad1a8eb513/src/test/ui/regions/regions-outlives-projection-container-wc.rs) still compiles with NLL enabled.

### LINKED ISSUE #57531: ICE when type checking partially annotated patterns
The following code causes an ICE

```rust
fn main() {
    let x = Some(Some(Some(1)));

    match x {
        Some::<Option<_>>(Some(Some(v))) => (),
        _ => (),
    }
}
```

Message:

```text
error: internal compiler error: src/librustc/mir/tcx.rs:139: cannot downcast non-ADT type: `Ty { ty: _ }`
thread 'rustc' panicked at 'Box<Any>', src/librustc_errors/lib.rs:588:9
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
error: aborting due to previous error
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
note: rustc 1.33.0-nightly (c2d381d39 2019-01-10) running on x86_64-unknown-linux-gnu
note: compiler flags: -C debuginfo=1 -C llvm-args=--x86-asm-syntax=intel --crate-type rlib
Compiler returned: 101
```

This is marked as A-NLL because the bug is in MIR type check, even though it occurs with or without NLL.

### LINKED ISSUE #57731: NLL may be mishandling `_` within type-ascription expression form
Adapted from examples given on #55748. Note that observing this bug requires use of `feature(type_ascription)` and therefore is not high priority.

consider the following code ([play](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=21fd53875eb61354f46c76088f983d62)):

```rust
#![feature(nll, type_ascription)]

#![allow(dead_code, unused_mut)]
type PairCoupledTypes<T> = (T, T);

#[cfg(this_is_just_here_for_comparison_it_behaves_same_with_and_without_nll)]
fn coupled_types_rhs<'a>(_x: &'a u32, s: &'static u32) -> &'static u32 {
    let ((y, _z),) = ((s, &_x),): (PairCoupledTypes<&u32>,);
    y //~ ERROR unsatisfied lifetime constraints
}

fn coupled_wilds_rhs<'a>(_x: &'a u32, s: &'static u32) -> &'static u32 {
    let ((y, _z),) = ((s, &_x),): (PairCoupledTypes<_>,);
    y //~ ERROR unsatisfied lifetime constraints
}

fn main() {}
```

Right now, as written, this compiles without error.  (Note that `fn coupled_types_rhs` is not included; that function will error with and without NLL.)

If you remove the `nll` in the feature declaration, the code for `fn coupled_wilds_rhs` is rejected.

This is an indication that either:
 1. NLL has a bug in how it is handling `_` in the type-ascription expression form `EXPR: TYPE`, or 
 2. there exists some argument that `fn coupled_wilds_rhs` should be accepted (and that NLL is correct in accepting it), but I do not see how such an argument exists that would not also imply that we should be seeing the same behavior in `fn coupled_types_rhs`.

### PR DESCRIPTION
**Pull request by matthewjasper**
* Renames (Canonical)?UserTypeAnnotation -> (Canonical)?UserType so that the name CanonicalUserTypeAnnotation is free.
* Keep the inferred type associated to user type annotations in the MIR, so that it can be compared against the annotated type, even when the annotated expression gets removed from the MIR. (#54943)
* Use the inferred type to allow infallible handling of user type projections (#57531)
* Uses revisions for the tests in #56993
* Check the types of `Unevaluated` constants with no annotations (#46702)
* Some drive-by cleanup

Closes #46702
Closes #54943
Closes #57531
Closes #57731
cc #56993 leaving this open to track the underlying issue: we are not running tests with full NLL enabled on CI at the moment

r? @nikomatsakis

### CODE REVIEW

File: src/librustc/traits/query/type_op/ascribe_user_type.rs [hunk 1]
```diff
@@ -1,28 +1,23 @@
...
 impl<'tcx> AscribeUserType<'tcx> {
     pub fn new(
         mir_ty: Ty<'tcx>,
-        variance: ty::Variance,
         def_id: DefId,
         user_substs: UserSubsts<'tcx>,
-        projs: &'tcx ty::List<ProjectionKind<'tcx>>,
     ) -> Self {
-        Self { mir_ty, variance, def_id, user_substs, projs }
+        Self { mir_ty,  def_id, user_substs }
```
Comment (pnkfelix) [inline src/librustc/traits/query/type_op/ascribe_user_type.rs]: hmm interesting that you have found a way to get rid of carrying the projections around as part of the `AscribeUserType`.

**Comment by pnkfelix** [comment]
This looks really good to me. I'm sort of flabbergasted that I spent all that time figuring out how to factor out the projections and apply them later on in the compiler's control flow ... when I guess I should have been trying to make a change more like this...?

**Comment by pnkfelix** [comment]
> we are not running tests with full NLL enabled on CI at the moment

I had forgotten about this detail.

If nothing else, *that* should be an argument for us to prioritize turning on NLL for all editions. Because right now we are leaving open a pretty big gap in our CI's testing.

**Comment by pnkfelix** [comment]
> > we are not running tests with full NLL enabled on CI at the moment
> 
> I had forgotten about this detail.
> 
> If nothing else, _that_ should be an argument for us to prioritize turning on NLL for all editions. Because right now we are leaving open a pretty big gap in our CI's testing.

Oh wait, I think I misunderstood this.

I thought that this was referring to the change to turn off compiletest's compare-mode by default (see #56391); but that didn't turn off NLL testing completely; it just restricted it to one builder.

After re-reading the comment, I think that it is in fact referring to the change introduced by PR #55134.
 * Which does still represent a gap in our testing.
 * But its not one that will be addressed by turning on NLL for all editions, at least not directly.
 * I suspect the way to go here might be to:
    * Turn on borrowck=migrate by default for 2015 edition (as described in #57804)
    * Once that is done, we can *repurpose* the compare mode testing to go back to testing `-Z  borrowck=mir -Z two-phase-borrows`. (i.e. undo PR #55134). That will hopefully ensure that we uncover any issues similar to  #56993 that are solely exposed when you go to full-blown NLL (and not just migrate mode).

**Comment by pnkfelix** [comment]
@petrochenkov I'll add that test now. (Maybe I'll change it to a `// compile-pass` test in drive by.)
