### PR TITLE
Robustify and genericize return-type-notation resolution in `resolve_bound_vars`

### LINKED ISSUE #132159: ICE when using RTN in the where clause of a trait
### Code

```Rust
#![feature(return_type_notation)]

trait LocalService {
    type Request;
    type Response;
    async fn call(&self, req: Self::Request) -> Self::Response;
}

trait Service: LocalService
where
    Self: Send,
    Self::call(..): Send,
{}
```

Note that rewriting the RTN to be an associated type bound like `trait Service: LocalService<call(..): Send>` fixes the ICE.

### Meta

`rustc --version --verbose`:
```
1.84.0-nightly

(2024-10-24 a93c1718c80b9f100056)
```

### Error output

```
thread 'rustc' panicked at compiler/rustc_infer/src/infer/mod.rs:1254:26:
index out of bounds: the len is 0 but the index is 0
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
thread 'rustc' panicked at compiler/rustc_infer/src/infer/mod.rs:1254:26:
index out of bounds: the len is 0 but the index is 0
stack backtrace:
   0:     0x78853889415a - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::hfa3da7a0a47f58c0
   1:     0x78853900450a - core::fmt::write::h296dad0cfcb67745
   2:     0x78853a2a41d1 - std::io::Write::write_fmt::hef438ecb526db8e0
   3:     0x788538893fb2 - std::sys::backtrace::BacktraceLock::print::he31a08709a1dab35
   4:     0x7885388964b6 - std::panicking::default_hook::{{closure}}::hbfce14987460eaad
   5:     0x788538896300 - std::panicking::default_hook::h8821a5ff84ae2b99
   6:     0x788537915f3f - std[2d280be5a6b2631c]::panicking::update_hook::<alloc[1fdcb98639ce29d2]::boxed::Box<rustc_driver_impl[1bdd46c67c0a8aed]::install_ice_hook::{closure#0}>>::{closure#0}
   7:     0x788538896bc8 - std::panicking::rust_panic_with_hook::h1de7232ce59c7e7a
   8:     0x78853889699a - std::panicking::begin_panic_handler::{{closure}}::h0395ab6273d8b929
   9:     0x788538894609 - std::sys::backtrace::__rust_end_short_backtrace::h02b232cfe8127d11
  10:     0x78853889665c - rust_begin_unwind
  11:     0x7885352e27f0 - core::panicking::panic_fmt::ha3c0e45386147034
  12:     0x788536f6eae2 - core::panicking::panic_bounds_check::h1b27f5189dae4738
  13:     0x7885398d13a2 - <&rustc_middle[92764f893bd3807b]::ty::list::RawList<(), rustc_middle[92764f893bd3807b]::ty::generic_args::GenericArg> as rustc_type_ir[f333f5ef0e2c17b]::fold::TypeFoldable<rustc_middle[92764f893bd3807b]::ty::context::TyCtxt>>::try_fold_with::<rustc_middle[92764f893bd3807b]::ty::fold::BoundVarReplacer<<rustc_infer[ab5197c00d32095c]::infer::InferCtxt>::instantiate_binder_with_fresh_vars::ToFreshVars>>
  14:     0x7885398d224a - <rustc_middle[92764f893bd3807b]::ty::fold::BoundVarReplacer<<rustc_infer[ab5197c00d32095c]::infer::InferCtxt>::instantiate_binder_with_fresh_vars::ToFreshVars> as rustc_type_ir[f333f5ef0e2c17b]::fold::TypeFolder<rustc_middle[92764f893bd3807b]::ty::context::TyCtxt>>::fold_ty
  15:     0x7885398d11fd - <&rustc_middle[92764f893bd3807b]::ty::list::RawList<(), rustc_middle[92764f893bd3807b]::ty::generic_args::GenericArg> as rustc_type_ir[f333f5ef0e2c17b]::fold::TypeFoldable<rustc_middle[92764f893bd3807b]::ty::context::TyCtxt>>::try_fold_with::<rustc_middle[92764f893bd3807b]::ty::fold::BoundVarReplacer<<rustc_infer[ab5197c00d32095c]::infer::InferCtxt>::instantiate_binder_with_fresh_vars::ToFreshVars>>
  16:     0x788535b80333 - <rustc_trait_selection[226e06cb330a59a7]::traits::select::SelectionContext>::candidate_from_obligation_no_cache
  17:     0x788539dbc09d - <rustc_trait_selection[226e06cb330a59a7]::traits::select::SelectionContext>::poly_select::{closure#0}
  18:     0x7885354740e4 - <rustc_trait_selection[226e06cb330a59a7]::traits::fulfill::FulfillProcessor as rustc_data_structures[bdd467982a3b0e57]::obligation_forest::ObligationProcessor>::process_obligation
  19:     0x7885391a8a97 - <rustc_data_structures[bdd467982a3b0e57]::obligation_forest::ObligationForest<rustc_trait_selection[226e06cb330a59a7]::traits::fulfill::PendingPredicateObligation>>::process_obligations::<rustc_trait_selection[226e06cb330a59a7]::traits::fulfill::FulfillProcessor>
  20:     0x7885391ad4ea - <rustc_trait_selection[226e06cb330a59a7]::traits::fulfill::FulfillmentContext<rustc_trait_selection[226e06cb330a59a7]::traits::FulfillmentError> as rustc_infer[ab5197c00d32095c]::traits::engine::TraitEngine<rustc_trait_selection[226e06cb330a59a7]::traits::FulfillmentError>>::select_all_or_error
  21:     0x78853962535d - rustc_hir_analysis[d6fd7796cbb235e8]::check::wfcheck::check_trait
  22:     0x788535fcbe73 - rustc_hir_analysis[d6fd7796cbb235e8]::check::wfcheck::check_well_formed
  23:     0x78853990d817 - rustc_query_impl[a6c366b0570fb3a7]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[a6c366b0570fb3a7]::query_impl::check_well_formed::dynamic_query::{closure#2}::{closure#0}, rustc_middle[92764f893bd3807b]::query::erase::Erased<[u8; 1usize]>>
  24:     0x78853990cf67 - rustc_query_system[56a0e954a54020d0]::query::plumbing::try_execute_query::<rustc_query_impl[a6c366b0570fb3a7]::DynamicConfig<rustc_query_system[56a0e954a54020d0]::query::caches::VecCache<rustc_span[32fd76c69516c13f]::def_id::LocalDefId, rustc_middle[92764f893bd3807b]::query::erase::Erased<[u8; 1usize]>>, false, false, false>, rustc_query_impl[a6c366b0570fb3a7]::plumbing::QueryCtxt, false>
  25:     0x78853990cbd0 - rustc_query_impl[a6c366b0570fb3a7]::query_impl::check_well_formed::get_query_non_incr::__rust_end_short_backtrace
  26:     0x78853990da90 - rustc_hir_analysis[d6fd7796cbb235e8]::check::wfcheck::check_mod_type_wf
  27:     0x78853990d8c7 - rustc_query_impl[a6c366b0570fb3a7]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[a6c366b0570fb3a7]::query_impl::check_mod_type_wf::dynamic_query::{closure#2}::{closure#0}, rustc_middle[92764f893bd3807b]::query::erase::Erased<[u8; 1usize]>>
  28:     0x788539f3f243 - rustc_query_system[56a0e954a54020d0]::query::plumbing::try_execute_query::<rustc_query_impl[a6c366b0570fb3a7]::DynamicConfig<rustc_query_system[56a0e954a54020d0]::query::caches::DefaultCache<rustc_span[32fd76c69516c13f]::def_id::LocalModDefId, rustc_middle[92764f893bd3807b]::query::erase::Erased<[u8; 1usize]>>, false, false, false>, rustc_query_impl[a6c366b0570fb3a7]::plumbing::QueryCtxt, false>
  29:     0x788539f3eff1 - rustc_query_impl[a6c366b0570fb3a7]::query_impl::check_mod_type_wf::get_query_non_incr::__rust_end_short_backtrace
  30:     0x78853920e4fb - rustc_hir_analysis[d6fd7796cbb235e8]::check_crate
  31:     0x788539882fd7 - rustc_interface[1bb6efe4f7692bf]::passes::run_required_analyses
  32:     0x788539d8485e - rustc_interface[1bb6efe4f7692bf]::passes::analysis
  33:     0x788539d84831 - rustc_query_impl[a6c366b0570fb3a7]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[a6c366b0570fb3a7]::query_impl::analysis::dynamic_query::{closure#2}::{closure#0}, rustc_middle[92764f893bd3807b]::query::erase::Erased<[u8; 1usize]>>
  34:     0x788539f469ee - rustc_query_system[56a0e954a54020d0]::query::plumbing::try_execute_query::<rustc_query_impl[a6c366b0570fb3a7]::DynamicConfig<rustc_query_system[56a0e954a54020d0]::query::caches::SingleCache<rustc_middle[92764f893bd3807b]::query::erase::Erased<[u8; 1usize]>>, false, false, false>, rustc_query_impl[a6c366b0570fb3a7]::plumbing::QueryCtxt, false>
  35:     0x788539f466cf - rustc_query_impl[a6c366b0570fb3a7]::query_impl::analysis::get_query_non_incr::__rust_end_short_backtrace
  36:     0x788539e19731 - rustc_interface[1bb6efe4f7692bf]::interface::run_compiler::<core[83415f1eb0db9702]::result::Result<(), rustc_span[32fd76c69516c13f]::ErrorGuaranteed>, rustc_driver_impl[1bdd46c67c0a8aed]::run_compiler::{closure#0}>::{closure#1}
  37:     0x788539e82e54 - std[2d280be5a6b2631c]::sys::backtrace::__rust_begin_short_backtrace::<rustc_interface[1bb6efe4f7692bf]::util::run_in_thread_with_globals<rustc_interface[1bb6efe4f7692bf]::util::run_in_thread_pool_with_globals<rustc_interface[1bb6efe4f7692bf]::interface::run_compiler<core[83415f1eb0db9702]::result::Result<(), rustc_span[32fd76c69516c13f]::ErrorGuaranteed>, rustc_driver_impl[1bdd46c67c0a8aed]::run_compiler::{closure#0}>::{closure#1}, core[83415f1eb0db9702]::result::Result<(), rustc_span[32fd76c69516c13f]::ErrorGuaranteed>>::{closure#0}, core[83415f1eb0db9702]::result::Result<(), rustc_span[32fd76c69516c13f]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[83415f1eb0db9702]::result::Result<(), rustc_span[32fd76c69516c13f]::ErrorGuaranteed>>
  38:     0x788539e8328d - <<std[2d280be5a6b2631c]::thread::Builder>::spawn_unchecked_<rustc_interface[1bb6efe4f7692bf]::util::run_in_thread_with_globals<rustc_interface[1bb6efe4f7692bf]::util::run_in_thread_pool_with_globals<rustc_interface[1bb6efe4f7692bf]::interface::run_compiler<core[83415f1eb0db9702]::result::Result<(), rustc_span[32fd76c69516c13f]::ErrorGuaranteed>, rustc_driver_impl[1bdd46c67c0a8aed]::run_compiler::{closure#0}>::{closure#1}, core[83415f1eb0db9702]::result::Result<(), rustc_span[32fd76c69516c13f]::ErrorGuaranteed>>::{closure#0}, core[83415f1eb0db9702]::result::Result<(), rustc_span[32fd76c69516c13f]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[83415f1eb0db9702]::result::Result<(), rustc_span[32fd76c69516c13f]::ErrorGuaranteed>>::{closure#1} as core[83415f1eb0db9702]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  39:     0x788539e83d2b - std::sys::pal::unix::thread::Thread::new::thread_start::h76e9ddc1a657d9a2
  40:     0x78853b5f4a94 - <unknown>
  41:     0x78853b681a34 - clone
  42:                0x0 - <unknown>

error: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: please make sure that you have updated to the latest nightly

note: please attach the file at `/playground/rustc-ice-2024-10-25T21_53_27-47.txt` to your bug report

note: compiler flags: --crate-type lib -C embed-bitcode=no -C codegen-units=1 -C debuginfo=2

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [check_well_formed] checking that `Service` is well-formed
#1 [check_mod_type_wf] checking that types are well-formed in top-level module
end of query stack
error: could not compile `playground` (lib)

Caused by:
  process didn't exit successfully: `/playground/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/rustc --crate-name playground --edition=2021 src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --crate-type lib --emit=dep-info,metadata,link -C embed-bitcode=no -C codegen-units=1 -C debuginfo=2 --check-cfg 'cfg(docsrs)' --check-cfg 'cfg(feature, values())' -C metadata=ae42ca123901b29d -C extra-filename=-ae42ca123901b29d --out-dir /playground/target/debug/deps -L dependency=/playground/target/debug/deps --extern addr2line=/playground/target/debug/deps/libaddr2line-663db7c2f6740a7f.rmeta --extern adler=/playground/target/debug/deps/libadler-3f09a6a29672e991.rmeta --extern adler2=/playground/target/debug/deps/libadler2-76f194e4bb5c744f.rmeta --extern ahash=/playground/target/debug/deps/libahash-849240a946d01fc0.rmeta --extern aho_corasick=/playground/target/debug/deps/libaho_corasick-9b605b5da44724d7.rmeta --extern aligned_vec=/playground/target/debug/deps/libaligned_vec-4040c93a23c712d8.rmeta --extern allocator_api2=/playground/target/debug/deps/liballocator_api2-e718a8c7e3ab25b4.rmeta --extern ansi_term=/playground/target/debug/deps/libansi_term-05a0059bfefa5637.rmeta --extern anstream=/playground/target/debug/deps/libanstream-c3e6d627a0829539.rmeta --extern anstyle=/playground/target/debug/deps/libanstyle-7c347f0997289ebc.rmeta --extern anstyle_parse=/playground/target/debug/deps/libanstyle_parse-2128cfb24c4c63ef.rmeta --extern anstyle_query=/playground/target/debug/deps/libanstyle_query-0fd1bd111e0ea51a.rmeta --extern anyhow=/playground/target/debug/deps/libanyhow-64786f9d2eef8443.rmeta --extern approx=/playground/target/debug/deps/libapprox-9fbaea411aba4124.rmeta --extern arc_swap=/playground/target/debug/deps/libarc_swap-63595da798af843e.rmeta --extern arg_enum_proc_macro=/playground/target/debug/deps/libarg_enum_proc_macro-f8d730491d42825c.so --extern arrayvec=/playground/target/debug/deps/libarrayvec-73d20a788d6d8b6d.rmeta --extern async_trait=/playground/target/debug/deps/libasync_trait-1449e9b3c3f4bdef.so --extern atomic=/playground/target/debug/deps/libatomic-36e8cd695846caf6.rmeta --extern atomic_waker=/playground/target/debug/deps/libatomic_waker-f4f217246ab9f6f1.rmeta --extern autocfg=/playground/target/debug/deps/libautocfg-e6abe02a0a359e3c.rmeta --extern av1_grain=/playground/target/debug/deps/libav1_grain-717c1bbd247b3c70.rmeta --extern avif_serialize=/playground/target/debug/deps/libavif_serialize-134f27004ef7744f.rmeta --extern backtrace=/playground/target/debug/deps/libbacktrace-f3ec48992ba79812.rmeta --extern base64=/playground/target/debug/deps/libbase64-ee0043206bfc53cf.rmeta --extern bit_set=/playground/target/debug/deps/libbit_set-8b78f1ed1a1d5a90.rmeta --extern bit_vec=/playground/target/debug/deps/libbit_vec-2d247e0a8ee0b1fd.rmeta --extern bit_field=/playground/target/debug/deps/libbit_field-59fcd3c19a5466e2.rmeta --extern bitflags_1_3_2=/playground/target/debug/deps/libbitflags-ad1920bfb419c0bc.rmeta --extern bitflags=/playground/target/debug/deps/libbitflags-adeefa1c078295b3.rmeta --extern bitstream_io=/playground/target/debug/deps/libbitstream_io-641bfdb2070522a5.rmeta --extern block_buffer=/playground/target/debug/deps/libblock_buffer-e97638cccbd2cab8.rmeta --extern built=/playground/target/debug/deps/libbuilt-7d8f993b77005988.rmeta --extern bumpalo=/playground/target/debug/deps/libbumpalo-a18e1280621168b7.rmeta --extern bytemuck=/playground/target/debug/deps/libbytemuck-7b3e4bf25917388c.rmeta --extern bytemuck_derive=/playground/target/debug/deps/libbytemuck_derive-2cbb441b8baffd45.so --extern byteorder=/playground/target/debug/deps/libbyteorder-e159530ef32e7331.rmeta --extern byteorder_lite=/playground/target/debug/deps/libbyteorder_lite-ac418e53dea7797e.rmeta --extern bytes_0_4_12=/playground/target/debug/deps/libbytes-54725bb0c169fa18.rmeta --extern bytes=/playground/target/debug/deps/libbytes-3a6f57e3025c6b53.rmeta --extern cc=/playground/target/debug/deps/libcc-5b3e4658e81a4a5e.rmeta --extern cfg_if=/playground/target/debug/deps/libcfg_if-59fd35abb8bea8be.rmeta --extern chrono=/playground/target/debug/deps/libchrono-978ad489d762ed4a.rmeta --extern clap=/playground/target/debug/deps/libclap-effdf5ab020b6cdf.rmeta --extern clap_builder=/playground/target/debug/deps/libclap_builder-4a076c10362fe69e.rmeta --extern clap_derive=/playground/target/debug/deps/libclap_derive-5d87b3cdcf9aff4f.so --extern clap_lex=/playground/target/debug/deps/libclap_lex-6754ed5bce72d9fc.rmeta --extern color_quant=/playground/target/debug/deps/libcolor_quant-e7403b9c068f2d68.rmeta --extern colorchoice=/playground/target/debug/deps/libcolorchoice-67d82edcba852e61.rmeta --extern const_default=/playground/target/debug/deps/libconst_default-8efd432a44ffdd2e.rmeta --extern cookie=/playground/target/debug/deps/libcookie-d5f251f310a336a2.rmeta --extern cookie_store=/playground/target/debug/deps/libcookie_store-15e31e4b58e919da.rmeta --extern cpufeatures=/playground/target/debug/deps/libcpufeatures-0badef4d09ae9679.rmeta --extern crc32fast=/playground/target/debug/deps/libcrc32fast-529b5b94aea41cde.rmeta --extern crossbeam=/playground/target/debug/deps/libcrossbeam-65e35073ea1e99c3.rmeta --extern crossbeam_channel=/playground/target/debug/deps/libcrossbeam_channel-55344e4a07623b8f.rmeta --extern crossbeam_deque=/playground/target/debug/deps/libcrossbeam_deque-c336f8b8dce477aa.rmeta --extern crossbeam_epoch=/playground/target/debug/deps/libcrossbeam_epoch-944a52cf02e5b9d2.rmeta --extern crossbeam_queue=/playground/target/debug/deps/libcrossbeam_queue-ea6ea8de998ecb33.rmeta --extern crossbeam_utils=/playground/target/debug/deps/libcrossbeam_utils-69cc502790cce516.rmeta --extern crypto_common=/playground/target/debug/deps/libcrypto_common-8548fa2219442650.rmeta --extern cssparser=/playground/target/debug/deps/libcssparser-52d07843b39a967d.rmeta --extern cssparser_macros=/playground/target/debug/deps/libcssparser_macros-4bd62242db259e69.so --extern csv=/playground/target/debug/deps/libcsv-721ef058a72929f1.rmeta --extern csv_core=/playground/target/debug/deps/libcsv_core-36a4f89ce5d8fdf0.rmeta --extern data_encoding=/playground/target/debug/deps/libdata_encoding-76212c157d552f2c.rmeta --extern deranged=/playground/target/debug/deps/libderanged-33479523b78ca0be.rmeta --extern derivative=/playground/target/debug/deps/libderivative-e1a4eddf838525a2.so --extern derive_more=/playground/target/debug/deps/libderive_more-a1e062bfb5d4abbf.so --extern destructure_traitobject=/playground/target/debug/deps/libdestructure_traitobject-b080bf825f241b55.rmeta --extern digest=/playground/target/debug/deps/libdigest-8826c4d4876f7bc6.rmeta --extern displaydoc=/playground/target/debug/deps/libdisplaydoc-8982b3f7991e2eb6.so --extern dtoa=/playground/target/debug/deps/libdtoa-a3e75f208e1fd1b7.rmeta --extern dtoa_short=/playground/target/debug/deps/libdtoa_short-964aac2ca54e6afa.rmeta --extern ego_tree=/playground/target/debug/deps/libego_tree-641dfcb0540d9314.rmeta --extern either=/playground/target/debug/deps/libeither-805003247fad1b2b.rmeta --extern encoding_rs=/playground/target/debug/deps/libencoding_rs-0bebf02fa985070a.rmeta --extern env_filter=/playground/target/debug/deps/libenv_filter-89c74666ee796758.rmeta --extern env_logger=/playground/target/debug/deps/libenv_logger-e3cc70709f9c5ce1.rmeta --extern equivalent=/playground/target/debug/deps/libequivalent-412bfd857fdec5e5.rmeta --extern errno=/playground/target/debug/deps/liberrno-f176037a4a6f1a57.rmeta --extern error_chain=/playground/target/debug/deps/liberror_chain-412f5716f223ad52.rmeta --extern exr=/playground/target/debug/deps/libexr-8d2eaa54b5d08bd3.rmeta --extern fallible_iterator_0_2_0=/playground/target/debug/deps/libfallible_iterator-4efe1a6224a45962.rmeta --extern fallible_iterator=/playground/target/debug/deps/libfallible_iterator-2e43403b7663c233.rmeta --extern fallible_streaming_iterator=/playground/target/debug/deps/libfallible_streaming_iterator-710dfcc86a75e434.rmeta --extern faster_hex=/playground/target/debug/deps/libfaster_hex-0af97615528c7b9e.rmeta --extern fastrand=/playground/target/debug/deps/libfastrand-7ab5f29b29251cb1.rmeta --extern fdeflate=/playground/target/debug/deps/libfdeflate-b8c4ff3ae7e76bb4.rmeta --extern filetime=/playground/target/debug/deps/libfiletime-025461ae865ee90a.rmeta --extern fixedbitset=/playground/target/debug/deps/libfixedbitset-56fdcb6d3120aa1c.rmeta --extern flate2=/playground/target/debug/deps/libflate2-2531746255f745f4.rmeta --extern flume=/playground/target/debug/deps/libflume-6be7dfc9fc0b1807.rmeta --extern fnv=/playground/target/debug/deps/libfnv-b87f391f84df4168.rmeta --extern foldhash=/playground/target/debug/deps/libfoldhash-178e39e4a84b8fbf.rmeta --extern foreign_types=/playground/target/debug/deps/libforeign_types-bf1014ffc62f0ae0.rmeta --extern foreign_types_shared=/playground/target/debug/deps/libforeign_types_shared-e8820102b4a82b58.rmeta --extern form_urlencoded=/playground/target/debug/deps/libform_urlencoded-1bdd9f06d2adc69d.rmeta --extern futf=/playground/target/debug/deps/libfutf-2ea1554fefb2e49e.rmeta --extern futures_0_1_31=/playground/target/debug/deps/libfutures-12ad2a82a5d3e695.rmeta --extern futures=/playground/target/debug/deps/libfutures-070609b71128d277.rmeta --extern futures_channel=/playground/target/debug/deps/libfutures_channel-5a070d86f78181cf.rmeta --extern futures_core=/playground/target/debug/deps/libfutures_core-ade5e7159d94df3e.rmeta --extern futures_executor=/playground/target/debug/deps/libfutures_executor-8a490590a06681da.rmeta --extern futures_io=/playground/target/debug/deps/libfutures_io-db26cc77f13da059.rmeta --extern futures_macro=/playground/target/debug/deps/libfutures_macro-4900adaafe7ff415.so --extern futures_sink=/playground/target/debug/deps/libfutures_sink-0ce0a82694aa2ad7.rmeta --extern futures_task=/playground/target/debug/deps/libfutures_task-563b37bc497c0b01.rmeta --extern futures_util=/playground/target/debug/deps/libfutures_util-44dcd9a6376d49e3.rmeta --extern fxhash=/playground/target/debug/deps/libfxhash-60a7f49f81ce4052.rmeta --extern generic_array_0_14_7=/playground/target/debug/deps/libgeneric_array-d7ed9cf72d6b705d.rmeta --extern generic_array=/playground/target/debug/deps/libgeneric_array-fdbc412513610959.rmeta --extern getopts=/playground/target/debug/deps/libgetopts-8cd941a37e074e59.rmeta --extern getrandom=/playground/target/debug/deps/libgetrandom-627e5a2dbf058a40.rmeta --extern gif=/playground/target/debug/deps/libgif-7b41a0d630389527.rmeta --extern gimli=/playground/target/debug/deps/libgimli-50f4b63a6fa6c677.rmeta --extern glob=/playground/target/debug/deps/libglob-1e2a4b0324293862.rmeta --extern h2=/playground/target/debug/deps/libh2-740d29560da2a2ed.rmeta --extern half=/playground/target/debug/deps/libhalf-84a67054715a6c20.rmeta --extern hashbrown_0_14_5=/playground/target/debug/deps/libhashbrown-ecd7b5ced3a842f1.rmeta --extern hashbrown=/playground/target/debug/deps/libhashbrown-0c4ea2c07ae4d43e.rmeta --extern hashlink=/playground/target/debug/deps/libhashlink-ce1daa8372716170.rmeta --extern heck=/playground/target/debug/deps/libheck-3726cb74edb52c42.rmeta --extern hmac=/playground/target/debug/deps/libhmac-7897b20b0a8dd2bd.rmeta --extern html5ever_0_26_0=/playground/target/debug/deps/libhtml5ever-a4429b1c710eb7e8.rmeta --extern html5ever=/playground/target/debug/deps/libhtml5ever-a5814f372d06e391.rmeta --extern http=/playground/target/debug/deps/libhttp-2b6e11be712be4ba.rmeta --extern http_body=/playground/target/debug/deps/libhttp_body-ab9122ebc0ed63df.rmeta --extern http_body_util=/playground/target/debug/deps/libhttp_body_util-ea404ca5c994da7d.rmeta --extern httparse=/playground/target/debug/deps/libhttparse-50ee3b897baea32e.rmeta --extern httpdate=/playground/target/debug/deps/libhttpdate-c240583034884b92.rmeta --extern humantime=/playground/target/debug/deps/libhumantime-dfd0f3ccc342d605.rmeta --extern hyper=/playground/target/debug/deps/libhyper-c60d5eda3f92848b.rmeta --extern hyper_rustls=/playground/target/debug/deps/libhyper_rustls-f6603b8f03997b80.rmeta --extern hyper_tls=/playground/target/debug/deps/libhyper_tls-2fe852cd03bbc7c6.rmeta --extern hyper_util=/playground/target/debug/deps/libhyper_util-f4fcafea0fb62940.rmeta --extern iana_time_zone=/playground/target/debug/deps/libiana_time_zone-609b050575be28ed.rmeta --extern icu_collections=/playground/target/debug/deps/libicu_collections-0699dbcb83ae6ec7.rmeta --extern icu_locid=/playground/target/debug/deps/libicu_locid-7bd3d7e06085b076.rmeta --extern icu_locid_transform=/playground/target/debug/deps/libicu_locid_transform-e4ebe56cf1f976ac.rmeta --extern icu_locid_transform_data=/playground/target/debug/deps/libicu_locid_transform_data-a4204e11e99ad5e9.rmeta --extern icu_normalizer=/playground/target/debug/deps/libicu_normalizer-b20222c58ab50487.rmeta --extern icu_normalizer_data=/playground/target/debug/deps/libicu_normalizer_data-248d668afc491381.rmeta --extern icu_properties=/playground/target/debug/deps/libicu_properties-9517af84661a6b12.rmeta --extern icu_properties_data=/playground/target/debug/deps/libicu_properties_data-d44a6f95b58c717b.rmeta --extern icu_provider=/playground/target/debug/deps/libicu_provider-abd060174498753b.rmeta --extern icu_provider_macros=/playground/target/debug/deps/libicu_provider_macros-16b38273683c62aa.so --extern idna_0_3_0=/playground/target/debug/deps/libidna-e62a3c4891036bd9.rmeta --extern idna_0_5_0=/playground/target/debug/deps/libidna-d6f4aa024eda2888.rmeta --extern idna=/playground/target/debug/deps/libidna-b13fba49047bdb75.rmeta --extern image=/playground/target/debug/deps/libimage-009d6c95df6595d6.rmeta --extern image_webp=/playground/target/debug/deps/libimage_webp-381b5c1774cc8248.rmeta --extern imgref=/playground/target/debug/deps/libimgref-14c3f6543a9943d6.rmeta --extern indexmap=/playground/target/debug/deps/libindexmap-543a73ac10a8a046.rmeta --extern iovec=/playground/target/debug/deps/libiovec-a597ca0e71f49b2a.rmeta --extern ipnet=/playground/target/debug/deps/libipnet-2ee1f498296703ff.rmeta --extern is_terminal_polyfill=/playground/target/debug/deps/libis_terminal_polyfill-e1bbd92ae5057e7f.rmeta --extern itertools_0_12_1=/playground/target/debug/deps/libitertools-3201f3756b9c6b7c.rmeta --extern itertools=/playground/target/debug/deps/libitertools-3e69e33fad39681b.rmeta --extern itoa=/playground/target/debug/deps/libitoa-95d99ed1b7c2d8bb.rmeta --extern jobserver=/playground/target/debug/deps/libjobserver-15c783da69ce6867.rmeta --extern jpeg_decoder=/playground/target/debug/deps/libjpeg_decoder-283d39bcc5f09e65.rmeta --extern lazy_static=/playground/target/debug/deps/liblazy_static-84db3878870a85d8.rmeta --extern lebe=/playground/target/debug/deps/liblebe-72f2d477d6c93f20.rmeta --extern libc=/playground/target/debug/deps/liblibc-5caa2c3007834e0c.rmeta --extern libm=/playground/target/debug/deps/liblibm-fc897264656bf591.rmeta --extern libsqlite3_sys=/playground/target/debug/deps/liblibsqlite3_sys-b891c15a1ab0f701.rmeta --extern linux_raw_sys_0_4_14=/playground/target/debug/deps/liblinux_raw_sys-816df20e9cde720c.rmeta --extern linux_raw_sys=/playground/target/debug/deps/liblinux_raw_sys-2eb2dfc3d6dcfe7a.rmeta --extern litemap=/playground/target/debug/deps/liblitemap-d981881f5d7f0857.rmeta --extern lock_api=/playground/target/debug/deps/liblock_api-d050eee0655d190e.rmeta --extern log=/playground/target/debug/deps/liblog-bfbaf44a59935629.rmeta --extern log_mdc=/playground/target/debug/deps/liblog_mdc-a4c23800e3e739b2.rmeta --extern log4rs=/playground/target/debug/deps/liblog4rs-e1353e616eea1f75.rmeta --extern loop9=/playground/target/debug/deps/libloop9-c79e3e985fed7500.rmeta --extern mac=/playground/target/debug/deps/libmac-dcc37a52a3bec462.rmeta --extern markup5ever_0_11_0=/playground/target/debug/deps/libmarkup5ever-446c09dce5df3d87.rmeta --extern markup5ever=/playground/target/debug/deps/libmarkup5ever-8a140975d74b556c.rmeta --extern markup5ever_rcdom=/playground/target/debug/deps/libmarkup5ever_rcdom-c1dfbaabe6bdc51e.rmeta --extern matrixmultiply=/playground/target/debug/deps/libmatrixmultiply-8e6aa901070b6caf.rmeta --extern maybe_rayon=/playground/target/debug/deps/libmaybe_rayon-b99efcb54e031f07.rmeta --extern md5=/playground/target/debug/deps/libmd5-a8c00386761b4579.rmeta --extern memchr=/playground/target/debug/deps/libmemchr-cf32634ccc5ae22a.rmeta --extern memmap=/playground/target/debug/deps/libmemmap-b007412239e9dfe6.rmeta --extern memoffset=/playground/target/debug/deps/libmemoffset-5c5f28878e8f3d6e.rmeta --extern mime=/playground/target/debug/deps/libmime-09780aa9afc6dfb4.rmeta --extern mime_guess=/playground/target/debug/deps/libmime_guess-ebe5babf069cf976.rmeta --extern minimal_lexical=/playground/target/debug/deps/libminimal_lexical-c9457124796fd7df.rmeta --extern miniz_oxide_0_7_4=/playground/target/debug/deps/libminiz_oxide-2de2e4587a326cb8.rmeta --extern miniz_oxide=/playground/target/debug/deps/libminiz_oxide-9725613fa5aa6157.rmeta --extern mio=/playground/target/debug/deps/libmio-beb6d11949b5d7e6.rmeta --extern nalgebra=/playground/target/debug/deps/libnalgebra-604160ea20b78d91.rmeta --extern nalgebra_macros=/playground/target/debug/deps/libnalgebra_macros-dd9a65734391feb0.so --extern native_tls=/playground/target/debug/deps/libnative_tls-e667286130f7071d.rmeta --extern ndarray=/playground/target/debug/deps/libndarray-b7fca98ab1b83490.rmeta --extern debug_unreachable=/playground/target/debug/deps/libdebug_unreachable-840d25d29f858f82.rmeta --extern nom=/playground/target/debug/deps/libnom-1149aa1de3defa8c.rmeta --extern noop_proc_macro=/playground/target/debug/deps/libnoop_proc_macro-ba5a81767f96b27f.so --extern num=/playground/target/debug/deps/libnum-08027ac347941c4c.rmeta --extern num_bigint=/playground/target/debug/deps/libnum_bigint-c667d5515f2967a1.rmeta --extern num_complex=/playground/target/debug/deps/libnum_complex-fda580d579918a1f.rmeta --extern num_conv=/playground/target/debug/deps/libnum_conv-8c9cbc0ac81ba02b.rmeta --extern num_derive=/playground/target/debug/deps/libnum_derive-1931ab415a4a13f7.so --extern num_integer=/playground/target/debug/deps/libnum_integer-27f67de385011477.rmeta --extern num_iter=/playground/target/debug/deps/libnum_iter-fc72316ba9640bf0.rmeta --extern num_rational=/playground/target/debug/deps/libnum_rational-3644e3ffed9d0610.rmeta --extern num_traits=/playground/target/debug/deps/libnum_traits-ca238b403edfd91b.rmeta --extern num_cpus=/playground/target/debug/deps/libnum_cpus-caf03633ec50d887.rmeta --extern object=/playground/target/debug/deps/libobject-ded34a2d6c1d62e2.rmeta --extern once_cell=/playground/target/debug/deps/libonce_cell-8099ad3ea85766d0.rmeta --extern openssl=/playground/target/debug/deps/libopenssl-edfd3c5961dbe999.rmeta --extern openssl_macros=/playground/target/debug/deps/libopenssl_macros-5d36eb0e913814a1.so --extern openssl_probe=/playground/target/debug/deps/libopenssl_probe-53373f83cce4ce19.rmeta --extern openssl_sys=/playground/target/debug/deps/libopenssl_sys-47fd3a4b06e2c11e.rmeta --extern ordered_float=/playground/target/debug/deps/libordered_float-5d51a3818964c670.rmeta --extern parking_lot=/playground/target/debug/deps/libparking_lot-e4abc391bc86b624.rmeta --extern parking_lot_core=/playground/target/debug/deps/libparking_lot_core-10ecbe067662eab0.rmeta --extern paste=/playground/target/debug/deps/libpaste-d57b4cb5f13d84ef.so --extern percent_encoding=/playground/target/debug/deps/libpercent_encoding-98dc5239e671d89b.rmeta --extern petgraph=/playground/target/debug/deps/libpetgraph-54584695e9433ab3.rmeta --extern phf_0_10_1=/playground/target/debug/deps/libphf-923a40d94bee4ab8.rmeta --extern phf=/playground/target/debug/deps/libphf-2627ac947263c0fc.rmeta --extern phf_codegen_0_10_0=/playground/target/debug/deps/libphf_codegen-d1b20c528212b42f.rmeta --extern phf_codegen=/playground/target/debug/deps/libphf_codegen-a9a8b846a2f543b6.rmeta --extern phf_generator_0_10_0=/playground/target/debug/deps/libphf_generator-707c4a64c43ebae2.rmeta --extern phf_generator=/playground/target/debug/deps/libphf_generator-346821ef4e974e66.rmeta --extern phf_macros=/playground/target/debug/deps/libphf_macros-908de7f43cf418e9.so --extern phf_shared_0_10_0=/playground/target/debug/deps/libphf_shared-445484f4dfe00074.rmeta --extern phf_shared=/playground/target/debug/deps/libphf_shared-831de1fff2cc985b.rmeta --extern pin_project_lite=/playground/target/debug/deps/libpin_project_lite-b42455a34bfaf72b.rmeta --extern pin_utils=/playground/target/debug/deps/libpin_utils-a8b22815580c0df9.rmeta --extern pkg_config=/playground/target/debug/deps/libpkg_config-7fc5661779f7a24b.rmeta --extern png=/playground/target/debug/deps/libpng-5c266ecd77d78cb0.rmeta --extern postgres=/playground/target/debug/deps/libpostgres-ee6ef87ec164109d.rmeta --extern postgres_protocol=/playground/target/debug/deps/libpostgres_protocol-5a15c62ea9218695.rmeta --extern postgres_types=/playground/target/debug/deps/libpostgres_types-52553b02026503a5.rmeta --extern powerfmt=/playground/target/debug/deps/libpowerfmt-20ed33c5eea869c6.rmeta --extern ppv_lite86=/playground/target/debug/deps/libppv_lite86-c190c35f0af0060c.rmeta --extern precomputed_hash=/playground/target/debug/deps/libprecomputed_hash-c8fddb01a9c4ef67.rmeta --extern proc_macro2=/playground/target/debug/deps/libproc_macro2-392315f3d99fa9a9.rmeta --extern profiling=/playground/target/debug/deps/libprofiling-857e799508d49fbe.rmeta --extern profiling_procmacros=/playground/target/debug/deps/libprofiling_procmacros-34e285592f5325c6.so --extern psl_types=/playground/target/debug/deps/libpsl_types-4612b0340e7c1853.rmeta --extern publicsuffix=/playground/target/debug/deps/libpublicsuffix-b3849e3a2386c741.rmeta --extern qoi=/playground/target/debug/deps/libqoi-9fd3372efc1e3a44.rmeta --extern quick_error=/playground/target/debug/deps/libquick_error-5674c48264a045c4.rmeta --extern quote=/playground/target/debug/deps/libquote-d66ddd2929ed6c5b.rmeta --extern rand=/playground/target/debug/deps/librand-4803b2d5105ba555.rmeta --extern rand_chacha=/playground/target/debug/deps/librand_chacha-9266de12cc385f8d.rmeta --extern rand_core=/playground/target/debug/deps/librand_core-66f1dba2a530c959.rmeta --extern rand_distr=/playground/target/debug/deps/librand_distr-78b50b414298942c.rmeta --extern rav1e=/playground/target/debug/deps/librav1e-1e7e6c0f496ffee5.rmeta --extern ravif=/playground/target/debug/deps/libravif-04aafdd96cf64d1d.rmeta --extern rawpointer=/playground/target/debug/deps/librawpointer-fa8d476f47f0aa20.rmeta --extern rayon=/playground/target/debug/deps/librayon-642f8ba2ab9d8cef.rmeta --extern rayon_core=/playground/target/debug/deps/librayon_core-3297163aefeb37aa.rmeta --extern regex=/playground/target/debug/deps/libregex-989d02b8067d50a5.rmeta --extern regex_automata=/playground/target/debug/deps/libregex_automata-c31ce4286eeda6d8.rmeta --extern regex_syntax=/playground/target/debug/deps/libregex_syntax-e5936fc21328abfb.rmeta --extern reqwest=/playground/target/debug/deps/libreqwest-d13b1c8f3b48e14e.rmeta --extern rgb=/playground/target/debug/deps/librgb-3eeb86d105db813c.rmeta --extern ring=/playground/target/debug/deps/libring-fc2b430e072435fc.rmeta --extern rusqlite=/playground/target/debug/deps/librusqlite-d310a69e4a037ae4.rmeta --extern rustc_demangle=/playground/target/debug/deps/librustc_demangle-8333a634c483b8d5.rmeta --extern rustc_version=/playground/target/debug/deps/librustc_version-c02c69a7f08a3ca3.rmeta --extern rustix=/playground/target/debug/deps/librustix-9558072bd125b6be.rmeta --extern rustls=/playground/target/debug/deps/librustls-bfe0cade53f329b2.rmeta --extern rustls_pemfile=/playground/target/debug/deps/librustls_pemfile-9b8ecd859e068f3b.rmeta --extern rustls_pki_types=/playground/target/debug/deps/librustls_pki_types-427b0117f41d47bb.rmeta --extern webpki=/playground/target/debug/deps/libwebpki-db98f5b8a8425208.rmeta --extern ryu=/playground/target/debug/deps/libryu-551d2ebce9ae8853.rmeta --extern safe_arch=/playground/target/debug/deps/libsafe_arch-a7755ba4f49a0cea.rmeta --extern same_file=/playground/target/debug/deps/libsame_file-cfa39741801edcf0.rmeta --extern scopeguard=/playground/target/debug/deps/libscopeguard-340b0cc7f24af35e.rmeta --extern scraper=/playground/target/debug/deps/libscraper-113d6a375ff0ba9c.rmeta --extern select=/playground/target/debug/deps/libselect-4e245751f5922f94.rmeta --extern selectors=/playground/target/debug/deps/libselectors-19cf7c381e15f040.rmeta --extern semver=/playground/target/debug/deps/libsemver-e4f77a7cd9313504.rmeta --extern serde=/playground/target/debug/deps/libserde-a4e7b22bafc6de76.rmeta --extern serde_value=/playground/target/debug/deps/libserde_value-2fba8fb6427e4954.rmeta --extern serde_derive=/playground/target/debug/deps/libserde_derive-6d7a5a843872e09b.so --extern serde_json=/playground/target/debug/deps/libserde_json-94bef5dfc99ff74d.rmeta --extern serde_spanned=/playground/target/debug/deps/libserde_spanned-3a6f4cb649c53d2b.rmeta --extern serde_urlencoded=/playground/target/debug/deps/libserde_urlencoded-fc3df751ecf53b33.rmeta --extern serde_yaml=/playground/target/debug/deps/libserde_yaml-454bd7630b4a9095.rmeta --extern servo_arc=/playground/target/debug/deps/libservo_arc-0be54459b06774a2.rmeta --extern sha1_smol=/playground/target/debug/deps/libsha1_smol-1e7d99282b441bf9.rmeta --extern sha2=/playground/target/debug/deps/libsha2-bb52e223df272e5c.rmeta --extern shlex=/playground/target/debug/deps/libshlex-de82d09077986144.rmeta --extern signal_hook_registry=/playground/target/debug/deps/libsignal_hook_registry-ee9b7bf7cd23cf85.rmeta --extern simba=/playground/target/debug/deps/libsimba-cf4ac14d11180722.rmeta --extern simd_adler32=/playground/target/debug/deps/libsimd_adler32-0b28677c728d9f9e.rmeta --extern simd_helpers=/playground/target/debug/deps/libsimd_helpers-b0d60fcb5f02f0ea.so --extern siphasher=/playground/target/debug/deps/libsiphasher-4ec58c711bad9322.rmeta --extern slab=/playground/target/debug/deps/libslab-7f77c852bd60c8d1.rmeta --extern smallvec=/playground/target/debug/deps/libsmallvec-76c61ed7b2259cd2.rmeta --extern socket2=/playground/target/debug/deps/libsocket2-ee3d87bb972934ef.rmeta --extern spin=/playground/target/debug/deps/libspin-18f0987f44f26ef9.rmeta --extern sptr=/playground/target/debug/deps/libsptr-4523619adaafff8b.rmeta --extern stable_deref_trait=/playground/target/debug/deps/libstable_deref_trait-8016b5831d479dba.rmeta --extern string_cache=/playground/target/debug/deps/libstring_cache-8fe8869186f19d50.rmeta --extern string_cache_codegen=/playground/target/debug/deps/libstring_cache_codegen-b20f73c289d1a5ab.rmeta --extern stringprep=/playground/target/debug/deps/libstringprep-f73b5554e84d8883.rmeta --extern strsim=/playground/target/debug/deps/libstrsim-57e723e1d275d2a2.rmeta --extern subtle=/playground/target/debug/deps/libsubtle-cdc086fa44cd23df.rmeta --extern syn_1_0_109=/playground/target/debug/deps/libsyn-012ecaeff9078afc.rmeta --extern syn=/playground/target/debug/deps/libsyn-23b8de69451c294e.rmeta --extern sync_wrapper=/playground/target/debug/deps/libsync_wrapper-d86f202f928f3af6.rmeta --extern synstructure=/playground/target/debug/deps/libsynstructure-ac7790b779cb6793.rmeta --extern tar=/playground/target/debug/deps/libtar-f364da67f1b8b0d5.rmeta --extern tempfile=/playground/target/debug/deps/libtempfile-7d28fdcc4804f085.rmeta --extern tendril=/playground/target/debug/deps/libtendril-1b90e8f5dbe3aed1.rmeta --extern termcolor=/playground/target/debug/deps/libtermcolor-ce7befebf7a1e656.rmeta --extern terminal_size=/playground/target/debug/deps/libterminal_size-0815b80b893bc2a1.rmeta --extern thiserror=/playground/target/debug/deps/libthiserror-12ddcf9c88bf38a4.rmeta --extern thiserror_impl=/playground/target/debug/deps/libthiserror_impl-e91676f9ab9be5bb.so --extern thread_id=/playground/target/debug/deps/libthread_id-3952a01eb2a4a350.rmeta --extern threadpool=/playground/target/debug/deps/libthreadpool-3f1d3ddce1c593c4.rmeta --extern tiff=/playground/target/debug/deps/libtiff-c15516e32f6b0c35.rmeta --extern time=/playground/target/debug/deps/libtime-40d5e75495f212b9.rmeta --extern time_core=/playground/target/debug/deps/libtime_core-c9eb71dd38667470.rmeta --extern time_macros=/playground/target/debug/deps/libtime_macros-e3b8ffedc7d8ef8e.so --extern tinystr=/playground/target/debug/deps/libtinystr-1254194f944abb83.rmeta --extern tinyvec=/playground/target/debug/deps/libtinyvec-8498574a75a78574.rmeta --extern tinyvec_macros=/playground/target/debug/deps/libtinyvec_macros-38d91b622583a154.rmeta --extern tokio=/playground/target/debug/deps/libtokio-ee1b75dbd67e6743.rmeta --extern tokio_io=/playground/target/debug/deps/libtokio_io-ecae0e4aa1dd1aa0.rmeta --extern tokio_macros=/playground/target/debug/deps/libtokio_macros-ea315bffd0646935.so --extern tokio_native_tls=/playground/target/debug/deps/libtokio_native_tls-079da5301deb5a89.rmeta --extern tokio_postgres=/playground/target/debug/deps/libtokio_postgres-968524bac875acd6.rmeta --extern tokio_rustls=/playground/target/debug/deps/libtokio_rustls-036d5bd8eaa26a44.rmeta --extern tokio_stream=/playground/target/debug/deps/libtokio_stream-bbe848370a8811c6.rmeta --extern tokio_util=/playground/target/debug/deps/libtokio_util-d11a8021c68aa4d2.rmeta --extern toml=/playground/target/debug/deps/libtoml-7cb55bb9b050cf80.rmeta --extern toml_datetime=/playground/target/debug/deps/libtoml_datetime-68a3f02033a441a4.rmeta --extern toml_edit=/playground/target/debug/deps/libtoml_edit-435fd8b0e49b840d.rmeta --extern tower_service=/playground/target/debug/deps/libtower_service-67f86bcdfe7f3737.rmeta --extern tracing=/playground/target/debug/deps/libtracing-4b3dfa166504988e.rmeta --extern tracing_attributes=/playground/target/debug/deps/libtracing_attributes-3a49f07640f019b5.so --extern tracing_core=/playground/target/debug/deps/libtracing_core-609799ac36ff7b7d.rmeta --extern trpl=/playground/target/debug/deps/libtrpl-26bd2f9d6813ef6a.rmeta --extern try_lock=/playground/target/debug/deps/libtry_lock-f73a7627d08d7047.rmeta --extern typemap_ors=/playground/target/debug/deps/libtypemap_ors-51c7ee1f9b2a5399.rmeta --extern typenum=/playground/target/debug/deps/libtypenum-603f08e78de3ce4b.rmeta --extern unicase=/playground/target/debug/deps/libunicase-f2cd69f771839cd3.rmeta --extern unicode_bidi=/playground/target/debug/deps/libunicode_bidi-8be75f6cd303557c.rmeta --extern unicode_ident=/playground/target/debug/deps/libunicode_ident-9a3c5b7b5d5de68f.rmeta --extern unicode_normalization=/playground/target/debug/deps/libunicode_normalization-cf1c4e22168faf7c.rmeta --extern unicode_properties=/playground/target/debug/deps/libunicode_properties-8ffc241302e1b4dc.rmeta --extern unicode_segmentation=/playground/target/debug/deps/libunicode_segmentation-b5caa71ac4ebf013.rmeta --extern unicode_width_0_1_14=/playground/target/debug/deps/libunicode_width-2f43b42225182ac7.rmeta --extern unicode_width=/playground/target/debug/deps/libunicode_width-457f1ce94dc2cdbf.rmeta --extern unicode_xid=/playground/target/debug/deps/libunicode_xid-9ce15e2aa1697488.rmeta --extern unsafe_any_ors=/playground/target/debug/deps/libunsafe_any_ors-4cd5a6568ea186a8.rmeta --extern unsafe_libyaml=/playground/target/debug/deps/libunsafe_libyaml-c1f60569d89702bc.rmeta --extern untrusted=/playground/target/debug/deps/libuntrusted-f32fc85046cdf3b5.rmeta --extern url=/playground/target/debug/deps/liburl-43ce21a5f370588b.rmeta --extern utf8=/playground/target/debug/deps/libutf8-fe4a0f906b99069f.rmeta --extern utf16_iter=/playground/target/debug/deps/libutf16_iter-a9319290c852e888.rmeta --extern utf8_iter=/playground/target/debug/deps/libutf8_iter-e356b5e074d8fbdf.rmeta --extern utf8parse=/playground/target/debug/deps/libutf8parse-e6bfae3e5f3a02ea.rmeta --extern uuid=/playground/target/debug/deps/libuuid-5111201875e88314.rmeta --extern v_frame=/playground/target/debug/deps/libv_frame-7260661dc72f81df.rmeta --extern vcpkg=/playground/target/debug/deps/libvcpkg-0c42e146e111ef9b.rmeta --extern version_check=/playground/target/debug/deps/libversion_check-cd8cba67fb70d9cf.rmeta --extern walkdir=/playground/target/debug/deps/libwalkdir-48fb32db35972a24.rmeta --extern want=/playground/target/debug/deps/libwant-ea61a245047a353e.rmeta --extern wasm_bindgen=/playground/target/debug/deps/libwasm_bindgen-22d2307c26e6c70d.rmeta --extern wasm_bindgen_backend=/playground/target/debug/deps/libwasm_bindgen_backend-fb866bc07738a504.rmeta --extern wasm_bindgen_macro=/playground/target/debug/deps/libwasm_bindgen_macro-efc1f11184687ae5.so --extern wasm_bindgen_macro_support=/playground/target/debug/deps/libwasm_bindgen_macro_support-c4715d6b68286472.rmeta --extern wasm_bindgen_shared=/playground/target/debug/deps/libwasm_bindgen_shared-b7a7ba990a58157c.rmeta --extern weezl=/playground/target/debug/deps/libweezl-ef83fd076c0c214d.rmeta --extern whoami=/playground/target/debug/deps/libwhoami-3eb1d83928907212.rmeta --extern wide=/playground/target/debug/deps/libwide-65d37a6c993d0785.rmeta --extern windows_x86_64_msvc=/playground/target/debug/deps/libwindows_x86_64_msvc-8238ddcf3c9ba6e7.rmeta --extern winnow=/playground/target/debug/deps/libwinnow-7d0e677d8d7b728c.rmeta --extern write16=/playground/target/debug/deps/libwrite16-5df432857f65960b.rmeta --extern writeable=/playground/target/debug/deps/libwriteable-c18f025431da77ee.rmeta --extern xattr=/playground/target/debug/deps/libxattr-ae46877938e85c3b.rmeta --extern xml5ever=/playground/target/debug/deps/libxml5ever-23f52533ff386d09.rmeta --extern yoke=/playground/target/debug/deps/libyoke-fce2dbeda1c03778.rmeta --extern yoke_derive=/playground/target/debug/deps/libyoke_derive-4b7943b3050b8571.so --extern zerocopy=/playground/target/debug/deps/libzerocopy-1fb642c52c8a6fa3.rmeta --extern zerocopy_derive=/playground/target/debug/deps/libzerocopy_derive-9be9e9320ceae71c.so --extern zerofrom=/playground/target/debug/deps/libzerofrom-d1214b7988545a9e.rmeta --extern zerofrom_derive=/playground/target/debug/deps/libzerofrom_derive-c6de84516857b8ce.so --extern zeroize=/playground/target/debug/deps/libzeroize-429d0fc444d8193b.rmeta --extern zerovec=/playground/target/debug/deps/libzerovec-a0d7ce905311d655.rmeta --extern zerovec_derive=/playground/target/debug/deps/libzerovec_derive-7f69b85edf8f2621.so --extern zune_core=/playground/target/debug/deps/libzune_core-067fe4b09cd8c8fd.rmeta --extern zune_inflate=/playground/target/debug/deps/libzune_inflate-26f56dc0fa212a11.rmeta --extern zune_jpeg=/playground/target/debug/deps/libzune_jpeg-45f9f57cf992e29e.rlib -L native=/playground/target/debug/build/libsqlite3-sys-4e5fb3685e92f2e7/out -L native=/playground/target/debug/build/ring-fb5f62804ed0a22c/out -L native=/playground/.cargo/registry/src/index.crates.io-6f17d22bba15001f/windows_x86_64_msvc-0.52.6/lib` (exit status: 101)
```

</p>
</details>

### PR DESCRIPTION
**Pull request by compiler-errors**
#129629 implemented return-type-notation (RTN) in its path form, like `where T::method(..): Bound`. As part of lowering, we must record the late-bound vars for the where clause introduced by the method (namely, its early- and late-bound lifetime arguments, since `where T::method(..)` turns into a higher-ranked where clause over all of the lifetimes according to [RFC 3654](https://rust-lang.github.io/rfcs/3654-return-type-notation.html#converting-to-higher-ranked-trait-bounds)). 

However, this logic was only looking at the where clauses of the parent item that the `T::method(..)` bound was written on, and not any parent items. This PR generalizes that logic to look at the parent item (i.e. the outer impl or trait) instead and fixes a (debug only) assertion as an effect.

This logic is also more general and likely easier to adapt to more interesting (though likely very far off) cases like non-lifetime binder `for<T: Trait> T::method(..): Send` bounds.

Tracking:

- https://github.com/rust-lang/rust/issues/109417

### CODE REVIEW

File: compiler/rustc_hir_analysis/src/collect/resolve_bound_vars.rs [hunk 1]
```diff
@@ -2001,6 +1986,75 @@ impl<'a, 'tcx> BoundVarContext<'a, 'tcx> {
...
+                        | Scope::TraitRefBoundary { s }
+                        | Scope::LateBoundary { s, .. } => {
+                            next_scope = Some(s);
+                            continue;
+                        }
+                        Scope::Root { opt_parent_item } => {
+                            if let Some(parent_id) = opt_parent_item {
+                                self.tcx.local_def_id_to_hir_id(parent_id)
+                            } else {
+                                continue;
```
Comment (pnkfelix) [inline compiler/rustc_hir_analysis/src/collect/resolve_bound_vars.rs:2019]: just to make sure I'm following the logic correctly ...

On this branch, `next_scope` is still `None` (right?), and therefore this `continue` will end up sending a `None` up into the `while let Some(current_scope)` condition, which means that this `continue` effectively ends up acting like ... a `break`?

(But then ... why not just write `break` here?)

**Comment by compiler-errors** [comment]
@rustbot ready

Could use another review for the commit on top. I forgot that we can have self type bounds not from the *supertraits*, but from the trait self, like:

```
trait Foo
where
    Self::method(..): Send
{
    async fn method();
}
```

The PR simplifies the logic a bit to account for that case.

**Comment by fee1-dead** [comment]
r? compiler

File: compiler/rustc_hir_analysis/src/collect/resolve_bound_vars.rs [hunk 2]
```diff
@@ -2051,47 +2051,37 @@ impl<'a, 'tcx> BoundVarContext<'a, 'tcx> {
...
+                                return;
+                            }
+                        }
+
                         let Some((bound_vars, assoc_item)) = one_bound else {
+                            self.tcx
+                                .dcx()
+                                .span_delayed_bug(path.span, "no resolution for RTN path");
                             return;
                         };
```
Comment (cjgillot) [inline compiler/rustc_hir_analysis/src/collect/resolve_bound_vars.rs:2083]: Could this be put before checking multiple bounds? That would avoid fusing the iterator.

File: compiler/rustc_hir_analysis/src/collect/resolve_bound_vars.rs (hunk 1 above)
Comment (cjgillot) [reply compiler/rustc_hir_analysis/src/collect/resolve_bound_vars.rs:2181]: In other methods, we prefer `scope` not being an option, and breaking when getting to `Root`. Do you mind making this a bit more uniform?

File: compiler/rustc_hir_analysis/src/collect/resolve_bound_vars.rs [hunk 3]
```diff
@@ -2157,6 +2147,86 @@ impl<'a, 'tcx> BoundVarContext<'a, 'tcx> {
...
+                        | Scope::ObjectLifetimeDefault { s, .. }
+                        | Scope::Supertrait { s, .. }
+                        | Scope::TraitRefBoundary { s }
+                        | Scope::LateBoundary { s, .. }
+                        | Scope::Opaque { s, .. } => {
+                            next_scope = Some(s);
+                            continue;
+                        }
+                        Scope::Root { opt_parent_item } => {
+                            if let Some(parent_id) = opt_parent_item {
```
Comment (cjgillot) [inline compiler/rustc_hir_analysis/src/collect/resolve_bound_vars.rs:2178]: Nit: do you mind splitting this into 2 match arms?

File: compiler/rustc_hir_analysis/src/collect/resolve_bound_vars.rs [hunk 4]
```diff
@@ -2051,47 +2051,37 @@ impl<'a, 'tcx> BoundVarContext<'a, 'tcx> {
...
+
+                        let one_bound = bounds.next();
+
+                        // Don't bail if we have identical bounds, which may be collected from
+                        // something like `T: Bound + Bound`, or via elaborating supertraits.
+                        for second_bound in bounds {
+                            if Some(&second_bound) != one_bound.as_ref() {
+                                self.tcx.dcx().span_delayed_bug(
+                                    path.span,
+                                    "ambiguous resolution for RTN path",
```
Comment (cjgillot) [inline compiler/rustc_hir_analysis/src/collect/resolve_bound_vars.rs:2072]: For my own culture, where should the proper error be emitted?

File: compiler/rustc_hir_analysis/src/collect/resolve_bound_vars.rs [hunk 5]
```diff
@@ -2051,47 +2051,37 @@ impl<'a, 'tcx> BoundVarContext<'a, 'tcx> {
...
+                                );
+                                return;
+                            }
+                        }
+
                         let Some((bound_vars, assoc_item)) = one_bound else {
+                            self.tcx
+                                .dcx()
+                                .span_delayed_bug(path.span, "no resolution for RTN path");
```
Comment (cjgillot) [inline compiler/rustc_hir_analysis/src/collect/resolve_bound_vars.rs:2081]: Likewise, where should this error?

File: compiler/rustc_hir_analysis/src/collect/resolve_bound_vars.rs [hunk 6]
```diff
@@ -2157,6 +2147,86 @@ impl<'a, 'tcx> BoundVarContext<'a, 'tcx> {
...
+                                    | hir::GenericBound::Use(_, _) => {}
+                                }
+                            }
+                        }
+                    }
+                }
+            },
+        )
+        .fuse()
+    }
```
Comment (cjgillot) [inline compiler/rustc_hir_analysis/src/collect/resolve_bound_vars.rs:2229]: I wonder how hard it would be to reuse the method probing code we have in rustc_hir_typeck.

File: compiler/rustc_hir_analysis/src/collect/resolve_bound_vars.rs (hunk 4 above)
Comment (compiler-errors) [reply compiler/rustc_hir_analysis/src/collect/resolve_bound_vars.rs:2072]: It will error when we probe for the bound in astconv (HIR -> middle).

File: compiler/rustc_hir_analysis/src/collect/resolve_bound_vars.rs (hunk 5 above)
Comment (compiler-errors) [reply compiler/rustc_hir_analysis/src/collect/resolve_bound_vars.rs:2081]: Likewise, it will error when we probe for the bound in astconv (HIR -> middle).

File: compiler/rustc_hir_analysis/src/collect/resolve_bound_vars.rs (hunk 6 above)
Comment (compiler-errors) [reply compiler/rustc_hir_analysis/src/collect/resolve_bound_vars.rs:2229]: I think it would be pretty difficult to do without inducing cycles, since the lowering code requires lowering trait refs.

**Comment by compiler-errors** [comment]
spurious

@bors retry
