### PR TITLE
don't drop arguments' temporaries in `dbg!`

### LINKED ISSUE #153850: 1.95 beta regression: "temporary value dropped while borrowed"
Regression found by the 1.95 beta crater run.

```
[INFO] [stdout] error[E0716]: temporary value dropped while borrowed
[INFO] [stdout]    --> src/lib.rs:229:34
[INFO] [stdout]     |
[INFO] [stdout] 227 | // ...                   dbg!(
[INFO] [stdout] 228 | || ...                       x.value().score / x.value().playouts as f32,
[INFO] [stdout] 229 | || ...                       &x.id(),
[INFO] [stdout]     | ||                            ^^^^^^ creates a temporary value which is freed while still in use
[INFO] [stdout] 230 | || ...                       x.value().playouts,
[INFO] [stdout] 231 | || ...                   )
[INFO] [stdout]     | ||_______________________- temporary value is freed at the end of this statement
[INFO] [stdout] 232 | |  ...                   .0,
[INFO] [stdout]     | |_________________________- borrow later used here
[INFO] [stdout]     |
[INFO] [stdout]     = note: consider using a `let` binding to create a longer lived value
[INFO] [stdout] 
[INFO] [stdout] 
[INFO] [stderr] error: could not compile `monte_carlo` (lib) due to 1 previous error; 2 warnings emitted
[INFO] [stdout] For more information about this error, try `rustc --explain E0716`.
```

https://crater-reports.s3.amazonaws.com/beta-1.95-3/1.95.0-beta.3/reg/monte_carlo-0.1.1/log.txt

### PR DESCRIPTION
**Pull request by dianne**
*[View all comments](https://triagebot.infra.rust-lang.org/gh-comments/rust-lang/rust/pull/154074)*

Fixes rust-lang/rust#153850

Credit to @theemathas for help with macro engineering ^^

r? libs

### CODE REVIEW

File: library/std/src/macros/tests.rs
Comment (dianne) [inline library/std/src/macros/tests.rs:1]: I'm not totally sure where this should go. Conceptually, it makes the most sense for it to be a `std` test, but I can't find where `dbg!` is actually tested. It also only needs to pass borrowck, not be built and executed, so we could maybe save CI time by making it a `//@ check-pass` ui test or such.

File: library/std/src/macros/tests.rs [hunk 1]
```diff
@@ -0,0 +1,13 @@
...
+/// Test for <https://github.com/rust-lang/rust/issues/153850>:
+/// `dbg!` shouldn't drop arguments' temporaries.
+#[test]
+fn no_dropping_temps() {
+    fn temp() {}
+
+    *dbg!(&temp());
+    *dbg!(&temp(), 1).0;
+    *dbg!(0, &temp()).1;
+    *dbg!(0, &temp(), 2).1;
```
Comment (dianne) [inline library/std/src/macros/tests.rs:12]: Only the last couple of these actually regressed, but I figure we may as well be resilient to changes in `dbg!`.

Also, the dereferences of the temporary aren't necessary to reproduce this and weren't present in the reproducer found by crater, but I feel like being explicit makes the intent of the test clearer.

File: library/std/src/macros.rs [hunk 2]
```diff
@@ -380,37 +377,41 @@ macro_rules! dbg {
...
+        // Always put the arguments in a tuple to avoid an unused parens lint on the pattern.
+        match ($($processed,)+) {
+            ($($bound,)+) => {
+                $crate::eprint!(
+                    $crate::concat!($($piece),+),
+                    $(
+                        $crate::stringify!($processed),
+                        // The `&T: Debug` check happens here (not in the format literal desugaring)
+                        // to avoid format literal related messages and suggestions.
+                        &&$bound as &dyn $crate::fmt::Debug
```
Comment (theemathas) [inline library/std/src/macros.rs:395]: Why do we need a double reference here? Is it to support some crazy code doing `impl Debug for &Thing` ?

Comment (dianne) [reply library/std/src/macros.rs:395]: I'm not sure! The double reference just coerces away as part of the cast, right? But it's been that way since #142594, so I figured I'd leave it be.

Comment (dianne) [reply library/std/src/macros.rs:395]: .. though on second thought, just removing the `&` would be a very small PR on its own, so maybe it could be bundled in here, especially if the decision is to backport a revert of #149869 instead of this.

Comment (theemathas) [reply library/std/src/macros.rs:395]: Huh. This code has compiled ever since the stabilization of `dbg!()` in 1.32.0.

```rust
use std::fmt::{self, Debug, Formatter};
struct Thing;
impl Debug for &Thing {
    fn fmt(&self, _: &mut Formatter) -> fmt::Result {
        Ok(())
    }
}
fn main() {
    dbg!(Thing);
}
```

Removing the double reference would break this code.

Comment (dianne) [reply library/std/src/macros.rs:395]: That feels probably accidental ^^ but it definitely shouldn't be changed as part of this, then.

Comment (mejrs) [reply library/std/src/macros.rs:395]: The `dbg!` macro has always done the equivalent of `println!("{:?}", &x)`. The double reference is necessary to keep those semantics.

You can do something like 
```rust
#![feature(impl_trait_in_bindings)]

fn main() {
    let x = 4_u8;
    let y: impl std::fmt::Debug = &x;
}
```
if you really want to get rid of the double reference/cast, though.

File: library/std/src/macros/tests.rs
Comment (Mark-Simulacrum) [reply library/std/src/macros/tests.rs:1]: I think this is OK. It probably doesn't need to be an integration test though? i.e., you could add it to macros/test.rs or so?

File: tests/ui/borrowck/dbg-issue-120327.stderr [hunk 3]
```diff
@@ -4,44 +4,44 @@ error[E0382]: use of moved value: `a`
 LL |     let a = String::new();
    |         - move occurs because `a` has type `String`, which does not implement the `Copy` trait
 LL |     dbg!(a);
-   |     ------- value moved here
+   |          - value moved here
 LL |     return a;
    |            ^ value used here after move
    |
-help: consider borrowing instead of transferring ownership
+help: consider cloning the value if the performance cost is acceptable
```
Comment (Mark-Simulacrum) [inline tests/ui/borrowck/dbg-issue-120327.stderr:11]: This feels like an unfortunate regression (fine for this PR but maybe file an issue for it)? It seems highly likely that borrowing is better here.

**Review by Mark-Simulacrum — APPROVED** [review]
Generally this looks fine to me. I'm also not sure where (or whether they exist) there's more tests, but I think as long as you confirmed the one you added fails CI if the changes are reverted it feels OK to me.

r=me, I think it would probably make sense to revert #149869 as the beta backport but I'll leave that up to T-libs backport decision making.

*[View changes since this review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/rust/154074/fd0c901b00ee1e08a250039cdb90258603497e20..aea73b583896b9057589c32e119601f476666d56)*

File: tests/ui/borrowck/dbg-issue-120327.stderr (hunk 3 above)
Comment (dianne) [reply tests/ui/borrowck/dbg-issue-120327.stderr:11]: Apparently that suggestion was actually specifically meant for `dbg!`; I'd assumed it was generic. Maybe it's worth handling it in this PR to keep its expectation of what `dbg!` looks like in sync with reality—same as the clippy lint change? That test is specifically for the diagnostic too; if I'd taken care to read the linked issue (or if the test was documented or tested for the suggestion message) I'd have updated the diagnostic from the start ^^

I've added a fix, but I can move it to its own PR if that'd be better.

File: compiler/rustc_borrowck/src/diagnostics/conflict_errors.rs
Comment (dianne) [inline compiler/rustc_borrowck/src/diagnostics/conflict_errors.rs:549]: This already only worked for expansions, so I'd like to keep its scope narrow for now. If a more general "borrow here" suggestion would be helpful, I think it should be designed intentionally.

Comment (dianne) [inline compiler/rustc_borrowck/src/diagnostics/conflict_errors.rs:577]: Here's why it only worked for expansions: `self.expr_span` was the `move_span`, which previously pointed to the match's pattern (specifically a by-move binding), which is normally separate from the match scrutinee (where `dbg!`'s args expand).

File: compiler/rustc_borrowck/src/diagnostics/conflict_errors.rs [hunk 4]
```diff
@@ -603,29 +558,41 @@ impl<'infcx, 'tcx> MirBorrowckCtxt<'_, 'infcx, 'tcx> {
...
+                    })
                 {
-                    self.match_arg_span = Some(path.span);
+                    for arg in args {
+                        if let hir::ExprKind::Path(hir::QPath::Resolved(
+                            _,
+                            path @ Path { segments: [seg], .. },
+                        )) = &arg.kind
+                            && seg.ident.name == self.arg_name
+                            && self.move_span.source_equal(arg.span)
```
Comment (dianne) [inline compiler/rustc_borrowck/src/diagnostics/conflict_errors.rs:584]: This incidentally fixes a minor bug: if given `dbg!(a, a); a;`, it would produce two suggestions to borrow the second argument rather than one for each. Now that the `move_span` points to the user-provided argument, we can check the scrutinee for it to find the correct argument for each suggestion.

File: compiler/rustc_borrowck/src/diagnostics/conflict_errors.rs [hunk 5]
```diff
@@ -603,29 +558,41 @@ impl<'infcx, 'tcx> MirBorrowckCtxt<'_, 'infcx, 'tcx> {
...
-                        path @ Path { segments: [seg], .. },
-                    )) = &expr.kind
-                    && seg.ident.name == self.arg_name
-                    && self.expr_span.source_callsite().contains(expr.span)
+                if let hir::ExprKind::Match(scrutinee, ..) = &e.kind
+                    && let hir::ExprKind::Tup(args) = scrutinee.kind
+                    && e.span.macro_backtrace().any(|expn| {
+                        expn.macro_def_id.is_some_and(|macro_def_id| {
+                            self.tcx.is_diagnostic_item(sym::dbg_macro, macro_def_id)
+                        })
```
Comment (dianne) [inline compiler/rustc_borrowck/src/diagnostics/conflict_errors.rs:575]: This could avoid iterating by making `dbg_internal!` a diagnostic item. I figured it'd be cleaner to reuse the `dbg_macro` diagnostic item instead since efficiency isn't a priority, but I'm not sure.

File: tests/ui/borrowck/dbg-issue-120327.rs [hunk 6]
```diff
@@ -1,67 +1,44 @@
...
+fn two_of_them(a: String) -> String {
+    dbg!(a, a); //~ ERROR use of moved value
+    //~| HELP consider borrowing instead of transferring ownership
+    //~| HELP consider borrowing instead of transferring ownership
+    return a; //~ ERROR use of moved value
 }
 
 fn get_expr(_s: String) {}
 
+// The suggestion is purely syntactic; applying it here will result in a type error.
```
Comment (dianne) [inline tests/ui/borrowck/dbg-issue-120327.rs:38]: This was a pre-existing issue; I consider fixing it out-of-scope. I think other suggestions to borrow often produce incorrect code, but if we want to be extra-safe, it could only fire when the `dbg!` invocation is on a statement of its own.

File: library/std/src/macros/tests.rs
Comment (dianne) [reply library/std/src/macros/tests.rs:1]: Oh, I wasn't aware there was a difference! Done.

File: compiler/rustc_borrowck/src/diagnostics/conflict_errors.rs (hunk 5 above)
Comment (Mark-Simulacrum) [reply compiler/rustc_borrowck/src/diagnostics/conflict_errors.rs:575]: I think as-is this will also apply to e.g. `dbg!(some_other_macro!(a))`, right? Not sure that's desirable. But I think it's probably fairly rare that someone does that, so we can go with this for now.

File: library/std/src/macros/tests.rs
Comment (Mark-Simulacrum) [reply library/std/src/macros/tests.rs:1]: Unit tests get compiled as part of the general crate whereas integ tests (in tests/ at the top level) each get compiled separately, so they're generally slower to compile (on a per-test amortized basis).

**Review by Mark-Simulacrum — APPROVED** [review]
@bors r+

I think my sense is that especially with compiler changes also involved we should land the revert on beta rather than trying to backport this.

*[View changes since this review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/rust/154074/584d32e3ee7a2051c9ec1338d259ed8ef16380ca..be31b0a232e2603862fce34241db00bd317113bd)*

File: compiler/rustc_borrowck/src/diagnostics/conflict_errors.rs (hunk 5 above)
Comment (dianne) [reply compiler/rustc_borrowck/src/diagnostics/conflict_errors.rs:575]: I don't think so? I could be wrong, but I don't think the argument to `dbg!` would have the `dbg!` expansion in its macro backtrace, since it's not part of `dbg!`. I tested the spans of the moved-from arguments to `dbg!` in `dbg-issue-120327.rs`; they all have empty macro backtraces.

**Comment by Amanieu** [comment]
For the beta backport, it would be useful to re-run crater to ensure this change doesn't cause any unexpected breakage.
