### PR TITLE
Suggest to add lifetime constraint at explicit ouput of functions

### LINKED ISSUE #62097: rustc suggests invalid syntax to fix lifetime inferring error
<short summary of the bug>

I tried this code:
```rust
#![feature(async_await)]

use futures::{stream, StreamExt};

struct Foo {}

impl Foo {
    async fn foo(&self) {}

    async fn bar(&self) {
        stream::iter(0..1)
            .then(|_| runtime::spawn(self.foo()))
            .collect::<()>()
            .await;
    }
}

fn main() {}
```

The code above does not compile, throwing an error with inferring lifetimes. `rustc` produces the following output: 
```
error: cannot infer an appropriate lifetime
  --> src/main.rs:10:18
   |
10 |     async fn bar(&self) {
   |                  ^^^^^ ...but this borrow...
11 |         stream::iter(0..1)
12 |             .then(|_| runtime::spawn(self.foo()))
   |                       -------------- this return type evaluates to the `'static` lifetime...
   |
note: ...can't outlive the lifetime '_ as defined on the method body at 10:18
  --> src/main.rs:10:18
   |
10 |     async fn bar(&self) {
   |                  ^
help: you can add a constraint to the return type to make it last less than `'static` and match the lifetime '_ as defined on the method body at 10:18
   |
12 |             .then(|_| runtime::spawn + '_(self.foo()))
   |                       ^^^^^^^^^^^^^^^^^^^

error: aborting due to previous error

error: Could not compile `report`.

To learn more, run the command again with --verbose.
```
This suggestion `rustc` makes however, is invalid syntax. Trying to apply it's suggestion causes a syntax error as seen below. 
```
error: expected `:`, found `(`
  --> src/main.rs:12:42
   |
12 |             .then(|_| runtime::spawn + '_(self.foo()))
   |                                          ^ expected `:`
```
## Meta

`rustc --version --verbose`:
```
rustc 1.37.0-nightly (de7c4e423 2019-06-23)
binary: rustc
commit-hash: de7c4e42314c56528640e3b663aa10e0caa6bd9b
commit-date: 2019-06-23
host: x86_64-unknown-linux-gnu
release: 1.37.0-nightly
LLVM version: 8.0
```

### PR DESCRIPTION
**Pull request by csmoe**
Closes #62097

### CODE REVIEW

File: src/librustc/infer/error_reporting/nice_region_error/static_impl_trait.rs [hunk 1]
```diff
@@ -52,17 +53,24 @@ impl<'a, 'tcx> NiceRegionError<'a, 'tcx> {
...
-                            return_sp,
-                            &format!(
-                                "you can add a constraint to the return type to make it last \
+                    let fn_return_span = return_ty.unwrap().1;
+                    if let Ok(snippet) =
+                        self.tcx().sess.source_map().span_to_snippet(fn_return_span) {
+                        // only apply this suggestion onto functions with
+                        // explicit `impl Trait` return.
+                        // e.g. `fn foo() -> impl Trait {}`
+                        if !fn_return_span.is_empty() {
```
Comment (nikomatsakis) [inline src/librustc/infer/error_reporting/nice_region_error/static_impl_trait.rs]: I think instead of `is_empty`, we should invoke [`is_desugaring`](https://doc.rust-lang.org/nightly/nightly-rustc/syntax_pos/span_encoding/struct.Span.html#method.is_desugaring) or perhaps [`desugaring_kind`](https://doc.rust-lang.org/nightly/nightly-rustc/syntax_pos/span_encoding/struct.Span.html#method.desugaring_kind) -- something like `fn_return_span.is_desugaring(DesugaringKind::Async)`?

Comment (nikomatsakis) [reply src/librustc/infer/error_reporting/nice_region_error/static_impl_trait.rs]: arguably we could be conservative and just avoid for *any* desugaring

**Review by nikomatsakis — CHANGES_REQUESTED** [review]
Looks good! One suggestion

**Review by nikomatsakis — APPROVED** [review]
Looks great!

**Comment by csmoe** [comment]
r=@nikomatsakis

**Comment by Centril** [comment]
Failed in https://github.com/rust-lang/rust/pull/66236#issuecomment-552065895, @bors r-

**Comment by csmoe** [comment]
I think another bad suggestion found here, https://github.com/rust-lang/rust/pull/65730#issuecomment-548867911 `move` won't help.
I'd like to fix this along with this PR.

**Comment by csmoe** [comment]
@estebank it's strange that the ui failure https://github.com/rust-lang/rust/pull/65730#issuecomment-548867911 only happens on roll-up, neither `x.py test src/test/ui` locally, nor this PR ci-test.

**Comment by memoryruins** [comment]
> ---- [ui (nll)] ui/async-await/issues/issue-62097.rs stdout ----

Try `./x.py test src/test/ui --compare-mode nll --bless` locally.

**Comment by estebank** [comment]
@csmoe: what @memoryruins said. That's the likely thing you're seeing.

**Comment by JohnCSimon** [comment]
Ping from triage:
@nikomatsakis @estebank  - This PR is approved, it is ready to merge?
cc: @csmoe
