### PR TITLE
Don't crash on error codes passed to `--explain` which exceed our internal limit of 9999 

### LINKED ISSUE #140647: rustc explain panics with error code longer than 4 digits
The following command line causes rustc to panic:

```
rustc --explain E10000
```

Based on the panic message, any error code above 9999 likely triggers this panic.
`rustc --version --verbose`:
```
rustc 1.88.0-nightly (d6a325d93 2025-05-03)
binary: rustc
commit-hash: d6a325d93a84077580c677f89affbe45682606c3
commit-date: 2025-05-03
host: x86_64-pc-windows-msvc
release: 1.88.0-nightly
LLVM version: 20.1.4
```

It appears that the panicking assertion assumes that code further up the stack does basic validation of the error code, when in fact that isn't happening.

### Error output

```
thread 'main' panicked at /rustc/d6a325d93a84077580c677f89affbe45682606c3\compiler\rustc_errors\src\codes.rs:9:1:
assertion failed: value <= 9999
stack backtrace:
   0:     0x7ff992ebd4c2 - std::backtrace_rs::backtrace::win64::trace
                               at /rustc/d6a325d93a84077580c677f89affbe45682606c3/library\std\src\..\..\backtrace\src\backtrace\win64.rs:85
   1:     0x7ff992ebd4c2 - std::backtrace_rs::backtrace::trace_unsynchronized
                               at /rustc/d6a325d93a84077580c677f89affbe45682606c3/library\std\src\..\..\backtrace\src\backtrace\mod.rs:66
   2:     0x7ff992ebd4c2 - std::sys::backtrace::_print_fmt
                               at /rustc/d6a325d93a84077580c677f89affbe45682606c3/library\std\src\sys\backtrace.rs:66
   3:     0x7ff992ebd4c2 - std::sys::backtrace::impl$0::print::impl$0::fmt
                               at /rustc/d6a325d93a84077580c677f89affbe45682606c3/library\std\src\sys\backtrace.rs:39
   4:     0x7ff992eefccb - core::fmt::rt::Argument::fmt
                               at /rustc/d6a325d93a84077580c677f89affbe45682606c3/library\core\src\fmt\rt.rs:181
   5:     0x7ff992eefccb - core::fmt::write
                               at /rustc/d6a325d93a84077580c677f89affbe45682606c3/library\core\src\fmt\mod.rs:1446
   6:     0x7ff992eb3577 - std::io::default_write_fmt
                               at /rustc/d6a325d93a84077580c677f89affbe45682606c3/library\std\src\io\mod.rs:639
   7:     0x7ff992eb3577 - std::io::Write::write_fmt<std::sys::stdio::windows::Stderr>
                               at /rustc/d6a325d93a84077580c677f89affbe45682606c3/library\std\src\io\mod.rs:1914
   8:     0x7ff992ebd305 - std::sys::backtrace::BacktraceLock::print
                               at /rustc/d6a325d93a84077580c677f89affbe45682606c3/library\std\src\sys\backtrace.rs:42
   9:     0x7ff992ec2faa - std::panicking::default_hook::closure$0
                               at /rustc/d6a325d93a84077580c677f89affbe45682606c3/library\std\src\panicking.rs:300
  10:     0x7ff992ec2d40 - std::panicking::default_hook
                               at /rustc/d6a325d93a84077580c677f89affbe45682606c3/library\std\src\panicking.rs:327
  11:     0x7ff9945c40c9 - core[87a27484b78f7475]::slice::sort::unstable::heapsort::heapsort::<((rustc_lint_defs[b0c94f99b9e7b658]::Level, &str), usize), <((rustc_lint_defs[b0c94f99b9e7b658]::Level, &str), usize) as core[87a27484b78f7475]::cmp::PartialOrd>::lt>
  12:     0x7ff992ec3c3e - std::panicking::rust_panic_with_hook
                               at /rustc/d6a325d93a84077580c677f89affbe45682606c3/library\std\src\panicking.rs:841
  13:     0x7ff992ec3962 - std::panicking::begin_panic_handler::closure$0
                               at /rustc/d6a325d93a84077580c677f89affbe45682606c3/library\std\src\panicking.rs:699
  14:     0x7ff992ebe28f - std::sys::backtrace::__rust_end_short_backtrace<std::panicking::begin_panic_handler::closure_env$0,never$>
                               at /rustc/d6a325d93a84077580c677f89affbe45682606c3/library\std\src\sys\backtrace.rs:168
  15:     0x7ff992ec359e - std::panicking::begin_panic_handler
                               at /rustc/d6a325d93a84077580c677f89affbe45682606c3/library\std\src\panicking.rs:697
  16:     0x7ff996030751 - core::panicking::panic_fmt
                               at /rustc/d6a325d93a84077580c677f89affbe45682606c3/library\core\src\panicking.rs:75
  17:     0x7ff99603080d - core::panicking::panic
                               at /rustc/d6a325d93a84077580c677f89affbe45682606c3/library\core\src\panicking.rs:145
  18:     0x7ff98f7f8387 - rustc_driver_impl[4bf9a847fe62d732]::run_compiler
  19:     0x7ff98f8039c7 - rustc_driver_impl[4bf9a847fe62d732]::main
  20:     0x7ff7bb711039 - _wctype
  21:     0x7ff7bb711006 - _wctype
  22:     0x7ff7bb71101c - _wctype
  23:     0x7ff992ea280c - std::rt::lang_start_internal::closure$0
                               at /rustc/d6a325d93a84077580c677f89affbe45682606c3/library\std\src\rt.rs:168
  24:     0x7ff992ea280c - std::panicking::try::do_call
                               at /rustc/d6a325d93a84077580c677f89affbe45682606c3/library\std\src\panicking.rs:589
  25:     0x7ff992ea280c - std::panicking::try
                               at /rustc/d6a325d93a84077580c677f89affbe45682606c3/library\std\src\panicking.rs:552
  26:     0x7ff992ea280c - std::panic::catch_unwind
                               at /rustc/d6a325d93a84077580c677f89affbe45682606c3/library\std\src\panic.rs:359
  27:     0x7ff992ea280c - std::rt::lang_start_internal
                               at /rustc/d6a325d93a84077580c677f89affbe45682606c3/library\std\src\rt.rs:164
  28:     0x7ff7bb71106a - main
  29:     0x7ff7bb71126c - invoke_main
                               at D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:78
  30:     0x7ff7bb71126c - __scrt_common_main_seh
                               at D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
  31:     0x7ffa7b61e8d7 - BaseThreadInitThunk
  32:     0x7ffa7c8114fc - RtlUserThreadStart

error: the compiler unexpectedly panicked. this is a bug.
```

### PR DESCRIPTION
**Pull request by Kivooeo**
removed panic in case where we do `--explain > 9999` and added check for it

now error looks like this instead of ICE
```
$ rustc.exe --explain E10000
error: E10000 is not a valid error code
```
fixes #140647
r? @fmease

### CODE REVIEW

**Comment by jieyouxu** [comment]
I feel like this is very arbitrary. The `9999` limit is just an internal implementation detail (an internal "this is obviously wrong" check) and shouldn't be exposed to the user. I would've just expected

```
$ rustc --explain E12345
error: E12345 is not a valid error code
```

to behave the same as

```
$ rustc --explain E4444
error: E4444 is not a valid error code
```

and

```
$ rustc --explain E{usize::MAX + 1}
error: E4444 is not a valid error code
```

to gracefully fail with the same error message.

**Comment by Kivooeo** [comment]
@jieyouxu any actual idea why tidy start fails here? 
```
tidy check
tidy error: Error code `E9999` is used in the compiler but not defined and documented in `compiler/rustc_error_codes/src/lib.rs`.
```
like... should I just add it here...?
and about your suggestion, you asking to merge both errors into one `error_code is not a valid error code` right?

**Comment by Kivooeo** [comment]
oh no, looks like adding E9999 was a miskate here
but it actually makes tidy pass, so idk, correct me here pls

File: compiler/rustc_error_codes/src/lib.rs [hunk 1]
```diff
@@ -547,6 +547,7 @@ E0801: 0801,
 E0802: 0802,
 E0803: 0803,
 E0804: 0804,
+E9999: 9999,
```
Comment (fmease) [inline compiler/rustc_error_codes/src/lib.rs:550]: No, this shouldn't be necessary now that you've removed the specialized error message.

**Review by fmease — COMMENTED** [review]
> any actual idea why tidy start fails here?

I'm pretty sure it's simply due to tidy (`src/tools/tidy/src/error_codes.rs:361`) grepping through ~all Rust compiler source files looking for `\bE\d{4}\b` and finding the `E9999` in your previous error message that you've since removed.

File: compiler/rustc_error_codes/src/lib.rs (hunk 1 above)
Comment (Kivooeo) [reply compiler/rustc_error_codes/src/lib.rs]: yeah i removed this custom message error for anything greater than 9999 and removed E9999 from error_codes, ran tidy locally and tidy said it's fine, let's see

File: compiler/rustc_errors/src/codes.rs [hunk 2]
```diff
@@ -7,7 +7,6 @@
 use std::fmt;
 
 rustc_index::newtype_index! {
-    #[max = 9999] // Because all error codes have four digits.
```
Comment (fmease) [inline compiler/rustc_errors/src/codes.rs:10]: While we obviously shouldn't crash for when the *user* enters error codes greater than E9999, the original purpose of this internal limit is to prevent rustc devs from introducing five-digit error codes without changing all other relevant parts of the compiler and docs to now pad all four-digit codes with an additional `0` to become fivie-digit codes, etc.

Comment (Kivooeo) [reply compiler/rustc_errors/src/codes.rs:10]: i was wondering how can i fix this to make not panicking here, and without changing NewType entirely, so this is only solution that worked fine that i came up with

Comment (ShE3py) [reply compiler/rustc_errors/src/codes.rs:10]: Running the ICE with debuginfo gives this line:
https://github.com/rust-lang/rust/blob/651e9cf327358b28db7e37a2ae61727f4a2ef232/compiler/rustc_driver_impl/src/lib.rs#L466
You probably want to manually add an `impl TryFrom<u32> for ErrCode`.

Comment (Kivooeo) [reply compiler/rustc_errors/src/codes.rs:10]: i believe that this panic here
https://github.com/rust-lang/rust/blob/651e9cf327358b28db7e37a2ae61727f4a2ef232/compiler/rustc_index_macros/src/newtype.rs#L183

because ICE was adressing to this line 
https://github.com/rust-lang/rust/blob/651e9cf327358b28db7e37a2ae61727f4a2ef232/compiler/rustc_errors/src/codes.rs#L9

Comment (Kivooeo) [reply compiler/rustc_errors/src/codes.rs:10]: so, as far as i concerned, we cannot really prevent this panic when having #[max = 9999] and pass something bigger than it, we should not let this error code (that is bigger than max value) get to this assertations because it'll panic is such cases

but i may missing something for sure, if so please let me know we'll brainstorm it together

Comment (ShE3py) [reply compiler/rustc_errors/src/codes.rs:10]: The idea is to return `Err(_)`/`None`, i.e. not constructing the newtype if code > 9999.

Alternativement, adding `impl Borrow<u32> for ErrCode` so this fn can directly being called with an `u32` (`try_find_description<C>(&self, code: C) where ErrCode: Borrow<C>`);
https://github.com/rust-lang/rust/blob/651e9cf327358b28db7e37a2ae61727f4a2ef232/compiler/rustc_errors/src/registry.rs#L18-L22

Comment (Kivooeo) [reply compiler/rustc_errors/src/codes.rs:10]: yep, currently playing around this ideas, this would time some time because of recompilling, thanks for ideas

Comment (Kivooeo) [reply compiler/rustc_errors/src/codes.rs:10]: ive tried this thing 
```rust
  pub fn try_find_description(&self, code: ErrCode) -> Result<&'static str, InvalidErrorCode> {
      if code > ErrCode::from_u32(9999) {
          return Err(InvalidErrorCode);
      }
      self.long_descriptions.get(&code).copied().ok_or(InvalidErrorCode)
  }
```
and its not worked for me
but this one `&& code <= ErrCode::MAX_AS_U32` runs like perfect, so we can stick with it

**Comment by Kivooeo** [comment]
@ShE3py oh, yes i want to add tests for it, didnt knew that there is some for `--explain`, i should create it separate tests or can do it in one file?

**Comment by ShE3py** [comment]
Yup, that's unfortunate but AFAIK you can only run `rustc` once per file.

Btw, `//~?` may be interesting to use:
<https://rustc-dev-guide.rust-lang.org/tests/ui.html#error-without-line-information>

**Comment by Kivooeo** [comment]
yep, `//~?` is a nice one
@fmease should be ready

File: tests/ui/explain-with-error.rs
Comment (fmease) [inline tests/ui/explain-with-error.rs:1]: We no longer want to add new top-level UI tests — `tests/ui/explain.rs` is at the top-level for historical reasons.

Could you either create directory `tests/ui/explain/` and move `tests/ui/explain.{rs,stdout}` to `tests/ui/explain/basic.{rs,stdout}` as well as this test (rename it to `tests/ui/explain/invalid-error-code.*` for clarity perhaps?).

(Alternatively, you could just move this test to `tests/ui/invalid-compile-flags/` and keep the existing `explain.rs` but er, it needs to move at point anyway so why not now?).

File: tests/ui/explain-with-error.rs [hunk 3]
```diff
@@ -0,0 +1,2 @@
+//@ compile-flags: --explain E10000
```
Comment (fmease) [inline tests/ui/explain-with-error.rs:1]:
```suggestion
// Check that we don't crash on error codes exceeding our internal limit.
// issue: <https://github.com/rust-lang/rust/issues/140647>
//@ compile-flags: --explain E10000
```

**Review by fmease — APPROVED** [review]
Two suggestions then we should be good to go!

**Comment by Kivooeo** [comment]
@fmease seems done, but check pls if i got you made all right

**Comment by fmease** [comment]
> i also may should add some tests for other cases like valid error code for error that not exists or just something weird like word instead of number etc

If you'd like to, go right ahead, sure sounds like a good idea.

**Comment by Kivooeo** [comment]
@fmease should be good to go, added few more test cases

**Review by davidtwco — APPROVED** [review]
