### PR TITLE
Suggest moving redundant generic args of an assoc fn to its trait

### LINKED ISSUE #89064: Suggest annotating traits rather than methods when appropriate
Given the following code: https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=d2a32fe1f3460b6583534eb53d045165

```rust
fn foo() {
    let _ = "foo".into::<Option<_>>();
}
```

The current output is:

```
Compiling playground v0.0.1 (/playground)
error[E0107]: this associated function takes 0 generic arguments but 1 generic argument was supplied
   --> src/lib.rs:2:19
    |
2   |     let _ = "foo".into::<Option<_>>();
    |                   ^^^^------------- help: remove these generics
    |                   |
    |                   expected 0 generic arguments
    |
note: associated function defined here, with 0 generic parameters

For more information about this error, try `rustc --explain E0107`.
error: could not compile `playground` due to previous error
```

Ideally the output should look like:

```
error[E0107]: this associated function takes 0 generic arguments but 1 generic argument was supplied
   --> src/lib.rs:2:19
    |
2   |     let _ = "foo".into::<Option<_>>();
    |                   ^^^^------------- help: remove these generics
    |                   |
    |                   expected 0 generic arguments
    |
note: associated function defined here, with 0 generic parameters
help: `Into` trait takes 1 generic argument, try annotating that instead: `Into::<Option<_>>::into("foo")
```

When a user called `into()` with an annotation, it's helpful to suggest `T::from(_)` too.

### PR DESCRIPTION
**Pull request by hkmatsumoto**
Closes #89064

### CODE REVIEW

File: compiler/rustc_typeck/src/structured_errors/wrong_number_of_generic_args.rs [hunk 1]
```diff
@@ -654,6 +655,64 @@ impl<'a, 'tcx> WrongNumberOfGenericArgs<'a, 'tcx> {
...
+        if let Some(trait_) = self.tcx.trait_of_item(self.def_id) {
+            // HACK(hkmatsumoto): Ugly way to tell "<trait>::<assoc fn>()" from "x.<assoc fn>()";
+            // we don't care the latter (for now).
+            if self.path_segment.res == Some(hir::def::Res::Err) {
+                return;
+            }
+
+            // Say, if the assoc fn takes `A`, `B` and `C` as generic arguments while expecting 1
+            // argument, and its trait expects 2 arguments. It is hard to "split" them right as
+            // there are too many cases to handle: `A` `B` | `C`, `A` `B` | `C`, `A` `C` | `B`, ...
```
Comment (davidtwco) [inline compiler/rustc_typeck/src/structured_errors/wrong_number_of_generic_args.rs:674]: I think this comment could be a little bit clearer, it took me a little bit to understand what it was trying to communicate, perhaps:

```suggestion
            // Skip suggestion when the associated function is itself generic, it is unclear
            // how to split the provided parameters between those to suggest to the trait and
            // those to remain on the associated type.
```

File: compiler/rustc_typeck/src/structured_errors/wrong_number_of_generic_args.rs [hunk 2]
```diff
@@ -654,6 +655,64 @@ impl<'a, 'tcx> WrongNumberOfGenericArgs<'a, 'tcx> {
...
+            let num_assoc_fn_excess_args =
+                self.num_excess_type_or_const_args() + self.num_excess_lifetime_args();
+
+            let trait_generics = self.tcx.generics_of(trait_);
+            let num_trait_generics_except_self =
+                trait_generics.count() - if trait_generics.has_self { 1 } else { 0 };
+
+            // FIXME(hkmatsumoto): RHS of this condition ideally should be
+            // `num_trait_generics_except_self` - "# of generic args already provided to trait"
+            // but unable to get that information with `self.def_id`.
```
Comment (davidtwco) [inline compiler/rustc_typeck/src/structured_errors/wrong_number_of_generic_args.rs:690]: Are you able to look at the HIR at all to work out what generics were provided to the trait?

File: src/test/ui/suggestions/issue-89064.stderr [hunk 3]
```diff
@@ -0,0 +1,69 @@
...
+   |        ^^^
+help: remove these generics
+   |
+LL -     let _ = A::<S>::foo::<S>();
+LL +     let _ = A::<S>::foo();
+   |
+help: consider moving this generic argument to the `A` trait, which takes up to 1 argument
+   |
+LL -     let _ = A::<S>::foo::<S>();
+LL +     let _ = A::<S>::<S>::foo();
```
Comment (davidtwco) [inline src/test/ui/suggestions/issue-89064.stderr:64]: This is a little unfortunate.

File: compiler/rustc_typeck/src/structured_errors/wrong_number_of_generic_args.rs [hunk 4]
```diff
@@ -654,6 +655,64 @@ impl<'a, 'tcx> WrongNumberOfGenericArgs<'a, 'tcx> {
...
+    /// trait it belongs to.
+    ///
+    /// ```compile_fail
+    /// Into::into::<Option<_>>(42) // suggests considering `Into::<Option<_>>::into(42)`
+    /// ```
+    fn suggest_moving_args(&self, err: &mut Diagnostic) {
+        if let Some(trait_) = self.tcx.trait_of_item(self.def_id) {
+            // HACK(hkmatsumoto): Ugly way to tell "<trait>::<assoc fn>()" from "x.<assoc fn>()";
+            // we don't care the latter (for now).
+            if self.path_segment.res == Some(hir::def::Res::Err) {
```
Comment (davidtwco) [inline compiler/rustc_typeck/src/structured_errors/wrong_number_of_generic_args.rs:668]: You might be able to look at the HIR here to determine this?

**Review by davidtwco — COMMENTED** [review]
Thanks for the pull request, I like this change, I've left some suggestions that might help in improving this a little.

File: compiler/rustc_typeck/src/structured_errors/wrong_number_of_generic_args.rs (hunk 1 above)
Comment (hkmatsumoto) [reply compiler/rustc_typeck/src/structured_errors/wrong_number_of_generic_args.rs:674]: This is more straight-to-the-point, and I like this. English is harder than any programming language I came across ;-)

File: compiler/rustc_typeck/src/structured_errors/wrong_number_of_generic_args.rs (hunk 2 above)
Comment (hkmatsumoto) [reply compiler/rustc_typeck/src/structured_errors/wrong_number_of_generic_args.rs]: Fixed by 2fd8577d8aeb24a9aed5a53cfd7606e4bd420342

File: src/test/ui/suggestions/issue-89064.stderr (hunk 3 above)
Comment (hkmatsumoto) [reply src/test/ui/suggestions/issue-89064.stderr]: 2fd8577d8aeb24a9aed5a53cfd7606e4bd420342

**Review by davidtwco — APPROVED** [review]
