### PR TITLE
Correct await span for async-await error reporting

### LINKED ISSUE #71137: Improve await error messaging for trait obligations
I tried this code:

```rust
use std::future::Future;
use std::sync::Mutex;

fn fake_spawn<F: Future + Send + 'static>(f: F) { }

async fn wrong_mutex() {
  let m = Mutex::new(1);
  {
    let mut guard = m.lock().unwrap();
    (async { "right"; }).await;
    *guard += 1;
  }

  (async { "wrong"; }).await;
}

fn main() {
  fake_spawn(wrong_mutex());
}

```

I expected to see this happen:

```
error: future cannot be sent between threads safely
  --> src/main.rs:18:3
   |
4  | fn fake_spawn<F: Future + Send + 'static>(f: F) { }
   |    ----------             ---- required by this bound in `fake_spawn`
...
18 |   fake_spawn(wrong_mutex());
   |   ^^^^^^^^^^ future returned by `wrong_mutex` is not `Send`
   |
   = help: within `impl std::future::Future`, the trait `std::marker::Send` is not implemented for `std::sync::MutexGuard<'_, i32>`
note: future is not `Send` as this value is used across an await
  --> src/main.rs:14:3
   |
9  |     let mut guard = m.lock().unwrap();
   |         --------- has type `std::sync::MutexGuard<'_, i32>`
...
12 |   }
   |   - `mut guard` is later dropped here
9  |     let mut guard = m.lock().unwrap();
10 |   (async { "right"; }).await;
   |   ^^^^^^^^^^^^^^^^^^^^^^^^^^ await occurs here, with `mut guard` maybe used later

error: aborting due to previous error
```

Instead, this happened:

```
error: future cannot be sent between threads safely
  --> src/main.rs:18:3
   |
4  | fn fake_spawn<F: Future + Send + 'static>(f: F) { }
   |    ----------             ---- required by this bound in `fake_spawn`
...
18 |   fake_spawn(wrong_mutex());
   |   ^^^^^^^^^^ future returned by `wrong_mutex` is not `Send`
   |
   = help: within `impl std::future::Future`, the trait `std::marker::Send` is not implemented for `std::sync::MutexGuard<'_, i32>`
note: future is not `Send` as this value is used across an await
  --> src/main.rs:14:3
   |
9  |     let mut guard = m.lock().unwrap();
   |         --------- has type `std::sync::MutexGuard<'_, i32>`
...
12 |   }
   |   - `mut guard` is later dropped here
13 |
14 |   (async { "wrong"; }).await;
   |   ^^^^^^^^^^^^^^^^^^^^^^^^^^ await occurs here, with `mut guard` maybe used later

error: aborting due to previous error
```

Note that the await pointed to be the error message is wrong.

The code that gets the span for the await is here https://github.com/rust-lang/rust/blob/32fb4dcdd7a57683a639a0959442711d0fd123bc/src/librustc_trait_selection/traits/error_reporting/suggestions.rs#L1340. The last span in generator_interior_types is not guaranteed to be the right await point.

### Meta

`rustc --version --verbose`:
```
rustc 1.42.0 (b8cedc004 2020-03-09)
binary: rustc
commit-hash: b8cedc00407a4c56a3bda1ed605c6fc166655447
commit-date: 2020-03-09
host: x86_64-apple-darwin
release: 1.42.0
LLVM version: 9.0
```

I also see the same behaviour with:

```
rustc 1.44.0-nightly (6dee5f112 2020-04-06)
binary: rustc
commit-hash: 6dee5f1126dfd5c9314ee5ae9d9eb010e35ef257
commit-date: 2020-04-06
host: x86_64-apple-darwin
release: 1.44.0-nightly
LLVM version: 9.0
```

### PR DESCRIPTION
**Pull request by csmoe**
Closes #71137
r? @tmandry

### CODE REVIEW

File: src/librustc_middle/ty/context.rs [hunk 1]
```diff
@@ -314,6 +314,8 @@ pub struct GeneratorInteriorTypeCause<'tcx> {
     pub span: Span,
     /// Span of the scope of the captured binding.
     pub scope_span: Option<Span>,
+    /// Span of `.await` statement.
+    pub await_span: Span,
```
Comment (tmandry) [inline src/librustc_middle/ty/context.rs:318]: Since this is more generally for generators, can you call it `yield_span` and comment with "Span of `yield` or `.await` expression"?

**Comment by tmandry** [comment]
@bors delegate=csmoe

Thanks for the fix! r=me after nit

**Comment by csmoe** [comment]
@bors r+
cc @tmandry
