### PR TITLE
extend stable hasher to support `CanonicalTy`

### LINKED ISSUE #49043: Compiler problem after upgrading the Nightly channel to 1.26.0-nightly (521d91c6b 2018-03-14), on x86_64-apple-darwin
# Action Done
Upgrading nightly channel (on Mac OS, x86_64).

# Error

error: internal compiler error: librustc/ich/impls_ty.rs:907: ty::TypeVariants::hash_stable() - Unexpected variant TyInfer(?0).

# Environment
rustc 1.26.0-nightly (521d91c6b 2018-03-14) running on x86_64-apple-darwin
compiler flags: -C debuginfo=2 -C incremental --crate-type lib

<details>
<summary>Full Trace</summary>

```
thread 'rustc' panicked at 'Box<Any>', librustc_errors/lib.rs:540:9
stack backtrace:
   0:        0x10ae4ccd3 - std::sys::unix::backtrace::tracing::imp::unwind_backtrace::h4f12297ed49ac32f
   1:        0x10ae43dd2 - std::sys_common::backtrace::_print::h213e0e54268e0593
   2:        0x10ae496cd - std::panicking::default_hook::{{closure}}::ha2d6c27d3ccb45fe
   3:        0x10ae49358 - std::panicking::default_hook::h05e34c08d7c0020c
   4:        0x10943ca40 - core::ops::function::Fn::call::h33445f89d9a18bf0
   5:        0x10ae49b90 - std::panicking::rust_panic_with_hook::h786d5042983c8bdd
   6:        0x10abdd33d - std::panicking::begin_panic::hbc36fe3fd409c901
   7:        0x10abfe6f8 - rustc_errors::Handler::bug::h6b903b69d6f4723b
   8:        0x10975d988 - rustc::session::opt_span_bug_fmt::{{closure}}::h7c0a304ef8c6532d
   9:        0x10981f2c0 - rustc::ty::context::tls::with_opt::{{closure}}::h3d2d9ce484fff7ea
  10:        0x109433d68 - <std::thread::local::LocalKey<T>>::try_with::h3c186cf53b87e91f
  11:        0x1094339c4 - <std::thread::local::LocalKey<T>>::with::h1e00bc547b6c14e5
  12:        0x10981f104 - rustc::ty::context::tls::with::h22abd2a67eff726d
  13:        0x10981f27f - rustc::ty::context::tls::with_opt::h2ae30e76357ed40a
  14:        0x10975d894 - rustc::session::opt_span_bug_fmt::h6e5624c321dff564
  15:        0x10975d7e1 - rustc::session::bug_fmt::hfd486ef4eb0c27f2
  16:        0x109690720 - rustc::ich::impls_ty::<impl rustc_data_structures::stable_hasher::HashStable<rustc::ich::hcx::StableHashingContext<'a>> for rustc::ty::sty::TypeVariants<'gcx>>::hash_stable::h0e6587b9a6d0d5ad
  17:        0x109841cbb - rustc::dep_graph::dep_node::DepNode::new::h4e54c5801157ea48
  18:        0x1099e796f - rustc::ty::maps::<impl rustc::ty::maps::queries::dropck_outlives<'tcx>>::try_get::h078dfc868290b2fa
  19:        0x1099fd6be - rustc::ty::maps::TyCtxtAt::dropck_outlives::h88b104672b4b7329
  20:        0x1097ac3c9 - rustc::traits::query::dropck_outlives::<impl rustc::infer::at::At<'cx, 'gcx, 'tcx>>::dropck_outlives::h66306048d6ba5805
  21:        0x1086b5eed - rustc_typeck::check::dropck::check_safety_of_destructor_if_necessary::h4e601f460f34e015
  22:        0x1086c24f3 - rustc_typeck::check::regionck::RegionCtxt::check_safety_of_rvalue_destructor_if_necessary::h99ebdbedfe415d3f
  23:        0x1086c077a - <rustc_typeck::check::regionck::RegionCtxt<'a, 'gcx, 'tcx> as rustc::hir::intravisit::Visitor<'gcx>>::visit_expr::he608f8ca4d917271
  24:        0x10868070e - rustc::hir::intravisit::walk_expr::h0397f9ae7f134d2a
  25:        0x1086c0f74 - <rustc_typeck::check::regionck::RegionCtxt<'a, 'gcx, 'tcx> as rustc::hir::intravisit::Visitor<'gcx>>::visit_expr::he608f8ca4d917271
  26:        0x1086c0439 - <rustc_typeck::check::regionck::RegionCtxt<'a, 'gcx, 'tcx> as rustc::hir::intravisit::Visitor<'gcx>>::visit_local::hfb7a8d29d91624dd
  27:        0x108680aa5 - rustc::hir::intravisit::walk_expr::h0397f9ae7f134d2a
  28:        0x1086c0e57 - <rustc_typeck::check::regionck::RegionCtxt<'a, 'gcx, 'tcx> as rustc::hir::intravisit::Visitor<'gcx>>::visit_expr::he608f8ca4d917271
  29:        0x108680962 - rustc::hir::intravisit::walk_expr::h0397f9ae7f134d2a
  30:        0x1086c112b - <rustc_typeck::check::regionck::RegionCtxt<'a, 'gcx, 'tcx> as rustc::hir::intravisit::Visitor<'gcx>>::visit_expr::he608f8ca4d917271
  31:        0x108680ac0 - rustc::hir::intravisit::walk_expr::h0397f9ae7f134d2a
  32:        0x1086c0e57 - <rustc_typeck::check::regionck::RegionCtxt<'a, 'gcx, 'tcx> as rustc::hir::intravisit::Visitor<'gcx>>::visit_expr::he608f8ca4d917271
  33:        0x108680962 - rustc::hir::intravisit::walk_expr::h0397f9ae7f134d2a
  34:        0x1086c112b - <rustc_typeck::check::regionck::RegionCtxt<'a, 'gcx, 'tcx> as rustc::hir::intravisit::Visitor<'gcx>>::visit_expr::he608f8ca4d917271
  35:        0x1086c0e57 - <rustc_typeck::check::regionck::RegionCtxt<'a, 'gcx, 'tcx> as rustc::hir::intravisit::Visitor<'gcx>>::visit_expr::he608f8ca4d917271
  36:        0x108680962 - rustc::hir::intravisit::walk_expr::h0397f9ae7f134d2a
  37:        0x1086c112b - <rustc_typeck::check::regionck::RegionCtxt<'a, 'gcx, 'tcx> as rustc::hir::intravisit::Visitor<'gcx>>::visit_expr::he608f8ca4d917271
  38:        0x108680ac0 - rustc::hir::intravisit::walk_expr::h0397f9ae7f134d2a
  39:        0x1086c0e57 - <rustc_typeck::check::regionck::RegionCtxt<'a, 'gcx, 'tcx> as rustc::hir::intravisit::Visitor<'gcx>>::visit_expr::he608f8ca4d917271
  40:        0x1086bf328 - rustc_typeck::check::regionck::RegionCtxt::visit_fn_body::h9383541c740ad04f
  41:        0x10871339c - rustc_typeck::check::typeck_tables_of::{{closure}}::h9a71412a06e16e09
  42:        0x10870f506 - rustc_typeck::check::typeck_tables_of::h4c89c6362ba4db84
  43:        0x1096008ba - rustc::dep_graph::graph::DepGraph::with_task_impl::hfaaa0e8dd4a0683a
  44:        0x1098ea519 - rustc::ty::maps::<impl rustc::ty::maps::queries::typeck_tables_of<'tcx>>::force::hecafdde183810b42
  45:        0x1098eb48f - rustc::ty::maps::<impl rustc::ty::maps::queries::typeck_tables_of<'tcx>>::try_get::hf32391a4fa1f99f3
  46:        0x1099f7230 - rustc::ty::maps::TyCtxtAt::typeck_tables_of::hee4782d933b10f61
  47:        0x1098ea170 - rustc::ty::maps::<impl rustc::ty::maps::queries::typeck_tables_of<'tcx>>::ensure::ha9294646c2164cb8
  48:        0x10870e93f - rustc_typeck::check::typeck_item_bodies::hb8730a2b77d5113b
  49:        0x1095dd79c - rustc::dep_graph::graph::DepGraph::with_task_impl::h544a1fc76fc91d26
  50:        0x1098e8297 - rustc::ty::maps::<impl rustc::ty::maps::queries::typeck_item_bodies<'tcx>>::force::hbf0e0dcc0f73b4d9
  51:        0x1098e90ff - rustc::ty::maps::<impl rustc::ty::maps::queries::typeck_item_bodies<'tcx>>::try_get::h9caadae2816555ce
  52:        0x1099f714b - rustc::ty::maps::TyCtxtAt::typeck_item_bodies::h32f9c1eb26d6a593
  53:        0x1099f3931 - rustc::ty::maps::<impl rustc::ty::context::TyCtxt<'a, 'tcx, 'lcx>>::typeck_item_bodies::h8ce9a5476cf40294
  54:        0x108761fe4 - rustc_typeck::check_crate::heab3b444e6275688
  55:        0x1080d7b53 - rustc::ty::context::TyCtxt::create_and_enter::h5f0cc76ebc317e07
  56:        0x108143404 - rustc_driver::driver::compile_input::h2094170bfafa48cd
  57:        0x10815fd26 - rustc_driver::run_compiler::hd4f50210430c210c
  58:        0x108087205 - std::sys_common::backtrace::__rust_begin_short_backtrace::h742c5f751224f94f
  59:        0x10ae6489e - __rust_maybe_catch_panic
  60:        0x1080c4935 - <F as alloc::boxed::FnBox<A>>::call_box::ha17229e1eb118d33
  61:        0x10ae5955b - std::sys::unix::thread::Thread::new::thread_start::heb1c5cf201612037
  62:     0x7fff57f8b6c0 - _pthread_body
  63:     0x7fff57f8b56c - _pthread_start
```
</details>

### PR DESCRIPTION
**Pull request by nikomatsakis**
Fixes #49043

r? @michaelwoerister

### CODE REVIEW

File: src/librustc/ich/impls_ty.rs [hunk 1]
```diff
@@ -902,13 +902,59 @@ for ty::TypeVariants<'gcx>
...
     }
 }
 
+impl_stable_hash_for!(enum ty::InferTy {
+    TyVar(a),
+    IntVar(a),
+    FloatVar(a),
+    FreshTy(a),
+    FreshIntTy(a),
+    FreshFloatTy(a),
```
Comment (michaelwoerister) [inline src/librustc/ich/impls_ty.rs]: The `Fresh*` variants are valid to hash?

Comment (nikomatsakis) [reply src/librustc/ich/impls_ty.rs]: Yes.

Comment (nikomatsakis) [reply src/librustc/ich/impls_ty.rs]: They are not confined to the local tcx:

https://github.com/rust-lang/rust/blob/3b6412b94324b10f698a18ea5766ef6ff8921ae8/src/librustc/ty/flags.rs#L112-L124

Comment (nikomatsakis) [reply src/librustc/ich/impls_ty.rs]: It just happens that we don't ever put them in query keys right now (and probably never will, but whatever).

Comment (nikomatsakis) [reply src/librustc/ich/impls_ty.rs]: (To be honest, even the `TyVar` and so forth would be ok to hash, it's just that it truly *ought* to be impossible... it would indicate some other problem if we did see them that would be worth knowing about.)

**Comment by michaelwoerister** [comment]
Thanks for the explanation!

@bors r+

**Comment by kennytm** [comment]
@bors retry 

`x86_64-gnu-incremental` 3-hour timeout, 39 minutes spent in compiling stage1-rustc.

<details>

```
make-prepare                	  72.13
stage0-tidy                 	  71.60
stage0-std                  	  13.79
stage0-rustc                	 989.30
llvm                        	 352.91
stage0-trans-llvm           	  79.50
stage1-std                  	 377.56
stage1-test                 	  29.36
stage1-rustc                	2331.73
stage1-trans-llvm           	 170.96
stage2-rustdoc              	 245.20
stage0-std                  	  58.85
stage0-rustbook             	 145.73
stage2-rustdoc              	 313.87
doc/compiler                	 148.92
stage2-error_index_generator	   6.30
stage0-std                  	  20.38
test/ui                     	 100.33
test/run-pass               	1255.39
test/compile-fail           	 276.29
test/parse-fail             	   6.46
test/run-fail               	  25.33
test/run-pass-valgrind      	   5.62
test/mir-opt                	  27.99
test/codegen                	   7.96
test/codegen-units          	   4.34
test/incremental            	  33.76
test/debuginfo              	  20.12
test/ui-fulldeps            	  32.87
test/run-pass-fulldeps      	 665.77
test/run-fail-fulldeps      	   7.78
test/compile-fail-fulldeps  	 145.30
test/incremental-fulldeps   	   5.47
stage2-rustdoc              	 322.52
test/run-make               	 126.27
...
```

</details>
