### PR TITLE
Fix autodiff debug builds

### LINKED ISSUE #139704: building rustc with autodiff and debug enabled fails.
I tried this code:

```bash
./configure --enable-llvm-link-shared --enable-llvm-plugins --enable-llvm-enzyme --release-channel=nightly --enable-llvm-assertions --enable-clang --enable-lld --enable-option-checking --enable-ninja --disable-docs --enable-debug
./x.py build --stage 1 library
```

I expected to see this happen: builds rustc

Instead, this happened: 
```bash
thread 'rustc' panicked at compiler/rustc_codegen_ssa/src/codegen_attrs.rs:57:9:
unexpected `def_kind` in `codegen_fn_attrs`: GlobalAsm

[...]

query stack during panic:
#0 [codegen_fn_attrs] computing codegen attributes of `probestack::{global_asm#0}`
#1 [collect_and_partition_mono_items] collect_and_partition_mono_items
... and 1 other queries... use `env RUST_BACKTRACE=1` to see the full query stack
error: could not compile `compiler_builtins` (lib)
```

### Meta

`rustc --version --verbose`:
```
build from source
```

I know that debug builds used to work a few months ago.
So one could try to debug this by looking at the code. A much simpler solution probably is just
to do some binary search by building some older PR from the [tracking issue](https://github.com/rust-lang/rust/issues/124509) with debug=true until finding one that builds. From there it should be easy to figure out which PR introduced the bug. Once that's clear it is hopefully easier to understand which change introduced the bug, and either directly fix it, or ask for help here or in the zulip channel. I'm marking it as easy, since it takes a bit of time to test multiple PRs but it isn't overly complex, and we had support for it and didn't introduce overly complex code changes in the last months. So the fix is likely also comparably simple.

This bug prevents us from enabling autodiff in CI and thus nightly, so any help would be appreciated!

<details><summary>Backtrace</summary>
<p>

```
<backtrace>
```

</p>
</details>

### PR DESCRIPTION
**Pull request by ZuseZ4**
r? @oli-obk 

closes: #139704

Tracking:

- https://github.com/rust-lang/rust/issues/124509

### CODE REVIEW

File: compiler/rustc_monomorphize/src/partitioning.rs [hunk 1]
```diff
@@ -254,8 +254,9 @@ where
             always_export_generics,
         );
 
-        // We can't differentiate something that got inlined.
+        // We can't differentiate a function that got inlined.
         let autodiff_active = cfg!(llvm_enzyme)
+            && matches!(mono_item, MonoItem::Fn(_))
```
Comment (jieyouxu) [inline compiler/rustc_monomorphize/src/partitioning.rs:259]: Discussion: this kinda feels backwards to me, I feel like if autodiff is applied to some fn it should inhibit inlining. Is there a small test case (synthetic or not) that can demonstrate this change?

Comment (ZuseZ4) [reply compiler/rustc_monomorphize/src/partitioning.rs:259]: I add inline(never) in my frontend macro to source and target function. However, those aren't guaranteed to prevent inlinung, so I additionally check it here in rustc_monomorphize. Every working codegen test shows that my logic here and in the frontend works. Adding additional must-fail tests would require building rustc with changes to the frontend (to not emit noinline) and the middle-end (to remove this code). That seems like a lot of effort to test. But I feel like I probably misunderstand your question?

The change btw. is needed since we currently also inspect non fn items like Asm, which triggers a debug assertion, causing bootstrap to fail. But you already mentioned that this looks reasonable to you

Comment (jieyouxu) [reply compiler/rustc_monomorphize/src/partitioning.rs:259]: > But I feel like I probably misunderstand your question?

I moreso meant if there's a smaller example that would fail without this PR, not changing the front-end/middle-end bits.

Comment (ZuseZ4) [reply compiler/rustc_monomorphize/src/partitioning.rs:259]: aah, yes now I get your question. I only mentioned it in the title, not the PR body, but you can find the panic stacktrace in the linked issue.

Comment (ZuseZ4) [reply compiler/rustc_monomorphize/src/partitioning.rs:259]: https://github.com/rust-lang/rust/pull/140064#issuecomment-2817989150

@jieyouxu since you already looked at it, it's a one line change, fixes bootstrap and eliminates the ad overhead, do you mind to rubberstamp it? Then I can drop it from my final enable-aitodiff PR.

Comment (jieyouxu) [reply compiler/rustc_monomorphize/src/partitioning.rs:259]: Yeah, at least this makes it possible to build, and I can't come up with a smaller test...

**Comment by jieyouxu** [comment]
r? jieyouxu @bors r+ rollup

**Review by jieyouxu — APPROVED** [review]
Thanks
