### PR TITLE
Fix handling of items inside a `doc(hidden)` block

### LINKED ISSUE #106373: Rustdoc reports non accessable items in blocks with `--document-private-items`, even with `#[doc(hidden)]`
```rust
#![allow(unused_macros, dead_code)]

#[doc(hidden)]
const _: () = {
    macro_rules! stry {
        () => {};
    }

    struct ShouldBeHidden;

    impl Bar for Foo {
        fn bar(&self) {
            struct SHouldAlsoBeHidden;
        }
    }
};

pub struct Foo;

pub trait Bar {
    fn bar(&self);
}
```

Produces with `rustdoc +nightly src/lib.rs --document-private-items`

image

which erroniously includes `stry`, `ShouldBeHidden`, and `ShouldAlsoBeHidden`.

Stable (1.66.0) gets this right

image

It's debatable what the semantics of `--document-private-items` should be for items in blocks without `#[doc(hidden)]` [^me], but here, we're just wrong.

We also can't just ignore all items in `#[doc(hidden)]` blocks, as this would break a load of users, eg serde.

[*Zulip Discussion*](https://rust-lang.zulipchat.com/#narrow/stream/266220-rustdoc/topic/Bad.20output.20for.20.60nightly_rustc.60.20crates)

[^me]: FWIW, I think they should still be hidden, as their not accessible outside the block.

Probably, caused by #104889, cc @GuillaumeGomez

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Fixes #106373.

cc @aDotInTheVoid 
r? @notriddle

### CODE REVIEW

File: src/librustdoc/clean/mod.rs [hunk 1]
```diff
@@ -2222,21 +2222,22 @@ fn clean_maybe_renamed_item<'tcx>(
...
+            Item::from_def_id_and_attrs_and_parts(def_id, Some(name), kind, Box::new(attrs), cfg)
         } else {
-            vec![Item::from_def_id_and_parts(def_id, Some(name), kind, cx)]
+            Item::from_def_id_and_parts(def_id, Some(name), kind, cx)
+        };
+        item.inline_stmt_id = import_id
+            .and_then(|id| cx.tcx.hir().opt_local_def_id(id))
+            .map(|def_id| def_id.to_def_id());
+        if std::env::var("LOL").is_ok() {
+            eprintln!("Setting inline_stmt_id from {:?} ===> {:?}", item.inline_stmt_id, import_id);
```
Comment (fmease) [inline src/librustdoc/clean/mod.rs:2238]:
```suggestion
```

😄

Comment (GuillaumeGomez) [reply src/librustdoc/clean/mod.rs:2238]: :laughing:

File: src/librustdoc/passes/strip_hidden.rs [hunk 2]
```diff
@@ -36,14 +44,37 @@ pub(crate) fn strip_hidden(krate: clean::Crate, cx: &mut DocContext<'_>) -> clea
...
+                        .or_else(|| i.item_id.as_def_id())
+                        .and_then(|def_id| def_id.as_local())
+                        .map(|def_id| {
+                            let hir_id = hir.local_def_id_to_hir_id(def_id);
+                            inherits_doc_hidden(self.tcx, hir_id)
+                        })
+                        .unwrap_or(false);
+                }
+                is_hidden
+            };
```
Comment (GuillaumeGomez) [inline src/librustdoc/passes/strip_hidden.rs:76]: This code now defines how `rustdoc` handles `doc(hidden)` item and its children. So to sum it up:

 If it's an impl item, then unless there is `doc(hidden)` directly on it, we still keep it, otherwise we discard everything.

There is a little twist: if it's an item that was reexported, then we use the reexport `DefId` to check if it's inside a `doc(hidden)` item.

File: tests/rustdoc/redirect.rs [hunk 3]
```diff
@@ -9,8 +9,11 @@ pub trait Foo {}
 // @has redirect/index.html
 // @has - '//code' 'pub use reexp_stripped::Bar'
 // @has - '//code/a' 'Bar'
-// @has reexp_stripped/hidden/struct.Bar.html
-// @has - '//p/a' '../../reexp_stripped/struct.Bar.html'
+// `Bar` is in a `doc(hidden)` module so the link should point to a non-existing file.
+// However, the struct is reexported at the root of the crate so we should point to it.
+// @has - '//a[@href="../reexp_stripped/struct.Bar.html"]' 'Bar'
```
Comment (GuillaumeGomez) [inline tests/rustdoc/redirect.rs:14]: Currently this test is failing. I need to find out why we generate a link to the original location of the item and not to the reexport directly.

File: src/librustdoc/passes/strip_hidden.rs (hunk 2 above)
Comment (fmease) [reply src/librustdoc/passes/strip_hidden.rs:76]: > If it's an impl item, then unless there is doc(hidden) directly on it, we still keep it

Even if either the implemented trait or the implementing type is hidden, too? That feels incorrect. Consider:

```rust
#[doc(hidden)]
const _: () = {
    pub trait Tr {}
    impl Tr for Ty {} // this impl should be hidden, right?
};

pub struct Ty;
```

```rust
#[doc(hidden)]
const _: () = {
    pub struct Ty;
    impl Tr for Ty {} // this impl should be hidden, right?
};

pub trait Tr {}
```

Comment (GuillaumeGomez) [reply src/librustdoc/passes/strip_hidden.rs:76]: So I remove this special case and make everyone happy? :)

Comment (GuillaumeGomez) [reply src/librustdoc/passes/strip_hidden.rs]: Simplified it then, no more exceptions.

**Comment by GuillaumeGomez** [comment]
So now just remains to fix the mystery of the bad item linking.

File: tests/rustdoc/hidden-private.rs [hunk 4]
```diff
@@ -0,0 +1,42 @@
...
+    // @!has - '//*[@class="code-header"]' 'impl Bar for Foo'
+    #[doc(hidden)]
+    impl Bar for Foo {
+        fn bar(&self) {
+            struct SHouldAlsoBeHidden;
+        }
+    }
+
+    // @has 'foo/struct.Private.html'
+    // @!has - '//*[@id="impl-Bar-for-Private"]/*[@class="code-header"]' 'impl Bar for Private'
```
Comment (aDotInTheVoid) [inline tests/rustdoc/hidden-private.rs:30]: Why is this hidden? It means that If have a private type, and use `#[derive(Serialize)]`, the impl won't appear with `--document-private-items`, which seems undesirable.

File: tests/rustdoc/hidden-private.rs [hunk 5]
```diff
@@ -0,0 +1,42 @@
...
+// compile-flags: --document-private-items
+
+#![crate_name = "foo"]
+
+// @has 'foo/index.html'
+// @count - '//*[@class="item-table"]//a[@class="struct"]' 2
+// @count - '//*[@class="item-table"]//a[@class="trait"]' 1
+#[doc(hidden)]
+const _: () = {
+    macro_rules! stry {
```
Comment (aDotInTheVoid) [inline tests/rustdoc/hidden-private.rs:14]: Nit: Can you add a check that this doesn't appear in output

File: tests/rustdoc/hidden-private.rs (hunk 4 above)
Comment (GuillaumeGomez) [reply tests/rustdoc/hidden-private.rs:30]: This is exactly the discussion we had [here](https://github.com/rust-lang/rust/pull/107000#discussion_r1072750801). If something is inside a hidden item's descendants, then it doesn't appear (not private, hidden).

File: tests/rustdoc/hidden-private.rs (hunk 5 above)
Comment (GuillaumeGomez) [reply tests/rustdoc/hidden-private.rs:14]: Good idea.

Comment (GuillaumeGomez) [reply tests/rustdoc/hidden-private.rs:15]: Done.

**Comment by GuillaumeGomez** [comment]
So I just pushed a new commit which changes a bit in case the item is reexported how its URL is computed. This is a change that needs to be very carefully reviewed. I'm not sure if this was the right approach to the problem so if someone has another idea in mind that allows to not change how some URLs are generated, it'd be really awesome!

**Comment by GuillaumeGomez** [comment]
Ok, I forgot to recurse into hidden children. Fixed that too.

**Comment by GuillaumeGomez** [comment]
Pushed to the wrong branch...

**Comment by GuillaumeGomez** [comment]
So actually, the last error we got is legit because the `FromStr` impl on float primitives is in a module with `#![doc(hidden)]`. Since we decided to not make an exception for trait implementations, it disappears. So based on this information, should I put back this exception for traits or should I change the `dec2flt/mod.rs` file?

**Comment by GuillaumeGomez** [comment]
I moved the trait implementations from the `doc(hidden)` module into its parent (with the other impls).

cc @notriddle

**Comment by GuillaumeGomez** [comment]
Since it's changing things around `doc(hidden)` items, you might want to take a look too @petrochenkov ?

**Comment by GuillaumeGomez** [comment]
This is a good question and I'm not sure how to check it with crater... Do we already have some number on the usage of `doc(hidden)` with docs.rs maybe?

cc @Nemo157

**Comment by petrochenkov** [comment]
>Since it's changing things around `doc(hidden)` items, you might want to take a look too @petrochenkov ?

TBH, I don't like this PR, didn't like https://github.com/rust-lang/rust/pull/104889, and didn't like what rustdoc had before that.
My ideal solution to this problem would be a from scratch rewrite of rustdoc frontend (which is more about HIR than about docs) by a qualified person, e.g. a compiler team member.

So I'm fine with merging this PR as long as it doesn't interfere with https://github.com/rust-lang/rust/pull/94857, which it doesn't seem to do.

**Comment by GuillaumeGomez** [comment]
> TBH, I don't like this PR, didn't like https://github.com/rust-lang/rust/pull/104889, and didn't like what rustdoc had before that.
> My ideal solution to this problem would be a from scratch rewrite of rustdoc frontend (which is more about HIR than about docs) by a qualified person, e.g. a compiler team member.

It'd be better indeed but it'll take a long time. At some point we will do it though. Until then, it allows to fix the current code base while adding more regression tests.

**Comment by GuillaumeGomez** [comment]
I'll r- for now as @Nemo157 made a pretty good argument in favor of having a special-case to keep implementations out of this logic. Let's take an example:

```rust
pub struct Foo;
pub trait Bar {}

#[doc(hidden)]
mod bar {
    use crate::{Foo, Bar};

    impl Bar for Foo {} // Is displayed in the docs.
    impl Foo {
        pub fn foo() {} // Is displayed in the docs.
    }
}
```

So to keep coherency with the rest, I'll special-case impl in the bodies as well.

@bors r-

**Comment by GuillaumeGomez** [comment]
The implementation is now in line with the rest of the implementation blocks handling in rustdoc.

Ready for new review round.

**Comment by GuillaumeGomez** [comment]
Forgot to change status...

@bors ready

**Comment by pnkfelix** [comment]
Agree with @notriddle

@rustbot label: +perf-regression-triaged
