### PR TITLE
linker: Implicitly link native libs as whole-archive in some more cases

### LINKED ISSUE #95561: native dependencies fail to link on nightly-2022-04-01
Sorry, I don't have a minimal reproduction repo. The error can be found at https://github.com/BusyJay/tirocks/runs/5784258424?check_suite_focus=true.

It doesn't seem to be able to resolve the required symbols somehow. I can verify that it compiles with the same code on nightly-2022-03-31.

### Meta

`rustc --version --verbose`:
```
rustc --version --verbose
rustc 1.61.0-nightly (0677edc86 2022-03-31)
binary: rustc
commit-hash: 0677edc86e342f333d4828b0ee1ef395a4e70fe5
commit-date: 2022-03-31
host: x86_64-unknown-linux-gnu
release: 1.61.0-nightly
LLVM version: 14.0.0
```

### PR DESCRIPTION
**Pull request by petrochenkov**
Partially revert changes from https://github.com/rust-lang/rust/pull/93901 to address regressions like https://github.com/rust-lang/rust/issues/95561.

Fixes https://github.com/rust-lang/rust/issues/95561
r? @wesleywiser

### CODE REVIEW

File: compiler/rustc_codegen_ssa/src/back/link.rs [hunk 1]
```diff
@@ -2079,9 +2079,14 @@ fn add_local_native_libraries(
             NativeLibKind::Framework { as_needed } => {
                 cmd.link_framework(name, as_needed.unwrap_or(true))
             }
-            NativeLibKind::Static { whole_archive, .. } => {
+            NativeLibKind::Static { whole_archive, bundle, .. } => {
                 if whole_archive == Some(true)
                     || (whole_archive == None && default_to_whole_archive(sess, crate_type, cmd))
+                    // Backward compatibility case: this can be a rlib (so `+whole-archive` cannot
+                    // be added explicitly if necessary, see the error in `fn link_rlib`) compiled
+                    // as an executable due to `--test`. Use whole-archive implicitly, like before
```
Comment (petrochenkov) [inline compiler/rustc_codegen_ssa/src/back/link.rs:2087]: Unfortunately we cannot determine whether it would be a rlib or not if `--test` weren't passed, because the rlib-ness is typically specified by cargo.
https://github.com/rust-lang/rust/issues/95561, for example still looks like an executable if we ignore `--test` in `fn collect_crate_types`.

**Comment by wesleywiser** [comment]
Thanks for jumping on this so quickly!

@bors r+ p=1

Fixing nightly regression
