### PR TITLE
self-contained linker: retry linking without `-fuse-ld=lld` on CCs that don't support it

### LINKED ISSUE #125330: Cross compilation fails on Rust nightly when using proc macro crates due to GCC not understanding `-fuse-ld=lld`
### Code

I tried this code:

```console
❯ cargo new hello_world
    Creating binary (application) `hello_world` package
cnote: see more `Cargo.toml` keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
❯ cd hello_world/
❯ cross +nightly build --target aarch64-unknown-linux-gnu
[cross] warning: using newer rustc `1.80.0-nightly (d84b90375 2024-05-19)` for the target. Current active rustc on the host is `rustc 1.78.0 (9b00956e5 2024-04-29)`.
 > Update with `rustup update`
   Compiling hello_world v0.1.0 (/project)
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.82s
❯ cargo add syn
    Updating crates.io index
      Adding syn v2.0.65 to dependencies
             Features:
             + clone-impls
             + derive
             + parsing
             + printing
             + proc-macro
             - extra-traits
             - fold
             - full
             - test
             - visit
             - visit-mut
    Updating crates.io index
❯ cross +nightly build --target aarch64-unknown-linux-gnu
[cross] warning: using newer rustc `1.80.0-nightly (d84b90375 2024-05-19)` for the target. Current active rustc on the host is `rustc 1.78.0 (9b00956e5 2024-04-29)`.
 > Update with `rustup update`
   Compiling proc-macro2 v1.0.83
   Compiling unicode-ident v1.0.12
error: linking with `cc` failed: exit status: 1
  |
  = note: LC_ALL="C" PATH="/rust/lib/rustlib/x86_64-unknown-linux-gnu/bin:/rust/lib/rustlib/x86_64-unknown-linux-gnu/bin/self-contained:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/rust/bin" VSLANG="1033" "cc" "-m64" "/tmp/rustcAyUfnb/symbols.o" "/target/debug/build/proc-macro2-b1e0569744dc7f5d/build_script_build-b1e0569744dc7f5d.build_script_build.48684d15272f5bdb-cgu.0.rcgu.o" "/target/debug/build/proc-macro2-b1e0569744dc7f5d/build_script_build-b1e0569744dc7f5d.build_script_build.48684d15272f5bdb-cgu.1.rcgu.o" "/target/debug/build/proc-macro2-b1e0569744dc7f5d/build_script_build-b1e0569744dc7f5d.crzselpkxut2yhaw0phvg3mu9.rcgu.o" "-Wl,--as-needed" "-L" "/target/debug/deps" "-L" "/rust/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-Wl,-Bstatic" "/rust/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd-de48b8168d6cf4fa.rlib" "/rust/lib/rustlib/x86_64-unknown-linux-gnu/lib/libpanic_unwind-9f3477fb95a0bba7.rlib" "/rust/lib/rustlib/x86_64-unknown-linux-gnu/lib/libobject-210d920812faea91.rlib" "/rust/lib/rustlib/x86_64-unknown-linux-gnu/lib/libmemchr-f3d3451767410a17.rlib" "/rust/lib/rustlib/x86_64-unknown-linux-gnu/lib/libaddr2line-1a79dd36d08251de.rlib" "/rust/lib/rustlib/x86_64-unknown-linux-gnu/lib/libgimli-886230e7120831b2.rlib" "/rust/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_demangle-2caea079085a58a2.rlib" "/rust/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd_detect-a9d7d97cdc65a449.rlib" "/rust/lib/rustlib/x86_64-unknown-linux-gnu/lib/libhashbrown-5727477b0a78105a.rlib" "/rust/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_std_workspace_alloc-7e555563aa211118.rlib" "/rust/lib/rustlib/x86_64-unknown-linux-gnu/lib/libminiz_oxide-c8f13465f1a795b2.rlib" "/rust/lib/rustlib/x86_64-unknown-linux-gnu/lib/libadler-ee5b5774583426df.rlib" "/rust/lib/rustlib/x86_64-unknown-linux-gnu/lib/libunwind-14df174c91007922.rlib" "/rust/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcfg_if-e8bfe52be756260a.rlib" "/rust/lib/rustlib/x86_64-unknown-linux-gnu/lib/liblibc-6275035a459b3ada.rlib" "/rust/lib/rustlib/x86_64-unknown-linux-gnu/lib/liballoc-b6892f3c52c68f01.rlib" "/rust/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_std_workspace_core-f72b956e24d1de70.rlib" "/rust/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcore-632ae0f28c5e55ff.rlib" "/rust/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcompiler_builtins-e8b7e96e438f08f6.rlib" "-Wl,-Bdynamic" "-lgcc_s" "-lutil" "-lrt" "-lpthread" "-lm" "-ldl" "-lc" "-B/rust/lib/rustlib/x86_64-unknown-linux-gnu/bin/gcc-ld" "-fuse-ld=lld" "-Wl,--eh-frame-hdr" "-Wl,-z,noexecstack" "-L" "/rust/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-L" "/rust/lib/rustlib/x86_64-unknown-linux-gnu/lib/self-contained" "-o" "/target/debug/build/proc-macro2-b1e0569744dc7f5d/build_script_build-b1e0569744dc7f5d" "-Wl,--gc-sections" "-pie" "-Wl,-z,relro,-z,now" "-nodefaultlibs"
  = note: cc: error: unrecognized command line option '-fuse-ld=lld'
          

error: could not compile `proc-macro2` (build script) due to 1 previous error
```

I expected to see this happen: Cross compilation should work fine

Instead, this happened: Cross compilation fails due to gcc not accepting `-fuse-ld=lld`

### Version it worked on

It most recently worked on: Nightly as of about a week ago, but it also works fine on stable.

### Version with regression

`rustc --version --verbose`:
```console
❯ rustc +nightly --version
rustc 1.80.0-nightly (d84b90375 2024-05-19)
```

### Backtrace

<details><summary>Backtrace</summary>
<p>

```
<backtrace>
```

</p>
</details>

@rustbot modify labels: +regression-from-stable-to-nightly -regression-untriaged

### PR DESCRIPTION
**Pull request by lqd**
For the self-contained linker, this PR applies [the strategy](https://github.com/rust-lang/rust/issues/125330#issuecomment-2125119838) of retrying the linking step when the driver doesn't support `-fuse-ld=lld`, but with the option removed. This is the same strategy we already use of retrying when e.g. `-no-pie` is not supported.

Fixes #125330 
r? @petrochenkov 

I have no idea how we could add a test here, much like we don't have one for `-no-pie` or `-static-pie` -- let me know if you have ideas -- but I tested on a CentOS7 image:

```console
[root@d25b38376ede tmp]# ../build/host/stage1/bin/rustc helloworld.rs
 WARN rustc_codegen_ssa::back::link The linker driver does not support `-fuse-ld=lld`. Retrying without it.

[root@d25b38376ede tmp]# readelf -p .comment helloworld

String dump of section '.comment':
  [     0]  GCC: (GNU) 4.8.5 20150623 (Red Hat 4.8.5-44)
  [    2d]  rustc version 1.80.0-dev
```

I wasn't able to test with `cross` as the issue describes: I wasn't able to reproduce that behavior locally.

### CODE REVIEW

**Comment by lqd** [comment]
@VorpalBlade I couldn't test with `cross` as you described in the description #125330, the issue doesn't reproduce for me locally. I'm not sure if cross' images may have changed in the last few days, but it doesn't look like so in the cross repository. 

Here, `cargo add syn && cross +nightly build --target aarch64-unknown-linux-gnu` succeeds. The binary's `.comment` looks like it used at least 1 GCC that supports `-fuse-ld=lld`, which could explain why it worked.

```console
$ readelf -p .comment target/aarch64-unknown-linux-gnu/debug/helloworld

String dump of section '.comment':
  [     0]  GCC: (Ubuntu 9.4.0-1ubuntu1~20.04.2) 9.4.0
  [    2b]  rustc version 1.80.0-nightly (b92758a9a 2024-05-20)
  [    5f]  GCC: (crosstool-NG UNKNOWN) 8.5.0
```

I don't know if you have another way to reproduce this issue that I could try?

I've tested on a CentOS7 image with gcc 4.5 and a helloworld worked there, so I have high hopes it will fix your use-case but I'd like to make sure with an actual reproduction.

---

Otherwise, I've asked CI to do a `try` build, which is similar to a rustup toolchain for this PR, and maybe you would be able to test it where nightly fails?

With [rustup-toolchain-install-master](https://github.com/kennytm/rustup-toolchain-install-master/), we can install CI artifacts and use them as regular rustup toolchains.

When CI completes (the bot will post a message that the build was successful), `rustup-toolchain-install-master 5572f385cb1b21326f0cf6672b3f74a172b5dcfa` will install the toolchain, and you'd be able to use it where you encountered the issue: with `+nightly` replaced by `+5572f385cb1b21326f0cf6672b3f74a172b5dcfa`.

To be honest I have a suspicion this might also fail, for unrelated reasons: I don't believe CI will build other std targets here, unfortunately. That seemed necessary in the cross-compilation use-case, but maybe cargo's `-Zbuild-std` could work here and build std. That's why I'm still mentioning this possibility.

**Comment by petrochenkov** [comment]
r=me after testing what you want to test.
@rustbot author

**Comment by lqd** [comment]
Let me try to cook something up with CI: @bors try

File: compiler/rustc_codegen_ssa/src/back/link.rs [hunk 1]
```diff
@@ -799,6 +799,27 @@ fn link_natively(
...
 
+        // Check if linking failed with an error message that indicates the driver didn't recognize
+        // the `-fuse-ld=lld` option. If so, re-perform the link step without it. This avoids having
+        // to spawn multiple instances on the happy path to do version checking, and ensures things
+        // keep working on the tier 1 baseline of GLIBC 2.17+. That is generally understood as GCCs
+        // circa RHEL/CentOS 7, 4.5 or so, whereas lld support was added in GCC 9.
+        if matches!(flavor, LinkerFlavor::Gnu(Cc::Yes, Lld::Yes))
+            && unknown_arg_regex.is_match(&out)
+            && out.contains("-fuse-ld=lld")
+            && cmd.get_args().iter().any(|e| e.to_string_lossy() == "-fuse-ld=lld")
```
Comment (tbu-) [inline compiler/rustc_codegen_ssa/src/back/link.rs:810]:
```suggestion
            && cmd.get_args().iter().any(|e| e.to_str() == Some("-fuse-ld=lld"))
```

File: compiler/rustc_codegen_ssa/src/back/link.rs [hunk 2]
```diff
@@ -799,6 +799,27 @@ fn link_natively(
...
+        {
+            info!("linker output: {:?}", out);
+            warn!("The linker driver does not support `-fuse-ld=lld`. Retrying without it.");
+            for arg in cmd.take_args() {
+                if arg.to_string_lossy() != "-fuse-ld=lld" {
```
Comment (tbu-) [inline compiler/rustc_codegen_ssa/src/back/link.rs:815]:
```suggestion
                if arg.to_str() != Some("-fuse-ld=lld") {
```

**Comment by VorpalBlade** [comment]
@lqd I will give this a try. As the build isn't done this evening and it is already pretty late, the next time I will have time to give this a try will be Friday evening, as tomorrow evening is DnD nights (well actually not DnD, a different pen and paper RPG, but you get the point).

File: compiler/rustc_codegen_ssa/src/back/link.rs (hunk 1 above)
Comment (lqd) [reply compiler/rustc_codegen_ssa/src/back/link.rs:810]: This code is taken from the same procedure above and below. Care to elaborate?

**Comment by lqd** [comment]
@VorpalBlade The previous build is done. I just queued a new one in case I'd be able to get enough artifacts for cross-compiling.

**Comment by VorpalBlade** [comment]
@lqd Apparently I misread your bot, try build and try commit being two different things? That is slightly confusing to an outsider.

So:

```console
❯ rustup-toolchain-install-master 5572f385cb1b21326f0cf6672b3f74a172b5dcfa
detecting the channel of the `5572f385cb1b21326f0cf6672b3f74a172b5dcfa` toolchain...
downloading <https://ci-artifacts.rust-lang.org/rustc-builds/5572f385cb1b21326f0cf6672b3f74a172b5dcfa/rustc-nightly-x86_64-unknown-linux-gnu.tar.xz>...
74.12 MB / 74.12 MB [=====================================================================================================================================================] 100.00 % 14.73 MB/s 
downloading <https://ci-artifacts.rust-lang.org/rustc-builds/5572f385cb1b21326f0cf6672b3f74a172b5dcfa/rust-std-nightly-x86_64-unknown-linux-gnu.tar.xz>...
27.49 MB / 27.49 MB [======================================================================================================================================================] 100.00 % 2.99 MB/s 
toolchain `5572f385cb1b21326f0cf6672b3f74a172b5dcfa` is successfully installed!
❯ cross +5572f385cb1b21326f0cf6672b3f74a172b5dcfa build --target aarch64-unknown-linux-gnu
error: error: invalid value '5572f385cb1b21326f0cf6672b3f74a172b5dcfa-x86_64-unknown-linux-gnu' for '<toolchain>...': invalid toolchain name: '5572f385cb1b21326f0cf6672b3f74a172b5dcfa-x86_64-unknown-linux-gnu'

For more information, try '--help'.
: invalid toolchain name: '5572f385cb1b21326f0cf6672b3f74a172b5dcfa-x86_64-unknown-linux-gnu'
Error: 
   0: couldn't install toolchain `5572f385cb1b21326f0cf6672b3f74a172b5dcfa-x86_64-unknown-linux-gnu`
   1: `rustup toolchain add 5572f385cb1b21326f0cf6672b3f74a172b5dcfa-x86_64-unknown-linux-gnu --profile minimal` failed with exit status: 1
❯ rustup-toolchain-install-master 5572f385cb1b21326f0cf6672b3f74a172b5dcfa -t aarch64-unknown-linux-gnu
toolchain `5572f385cb1b21326f0cf6672b3f74a172b5dcfa` is already installed
```

Expected? Any ideas on how to proceed? Would you would need the toolchain *inside* the docker image cross builds with? I'm not actually sure how cross works, I just used it as a tool.

File: compiler/rustc_codegen_ssa/src/back/link.rs (hunk 1 above)
Comment (tbu-) [reply compiler/rustc_codegen_ssa/src/back/link.rs:810]: It does a tiny bit less work in a corner case. But if the code above looks the same, I guess you don't need to adjust it. I just didn't see any use case for a lossy conversion.

**Comment by VorpalBlade** [comment]
```console
❯ cross +5572f385cb1b21326f0cf6672b3f74a172b5dcfa build --target aarch64-unknown-linux-gnu
Error: 
   0: `rustup target list --toolchain 5572f385cb1b21326f0cf6672b3f74a172b5dcfa-x86_64-unknown-linux-gnu` failed with exit status: 1

Stderr:
   error: error: invalid value '5572f385cb1b21326f0cf6672b3f74a172b5dcfa-x86_64-unknown-linux-gnu' for '--toolchain <toolchain>': invalid toolchain name: '5572f385cb1b21326f0cf6672b3f74a172b5dcfa-x86_64-unknown-linux-gnu'

   For more information, try '--help'.
   : invalid toolchain name: '5572f385cb1b21326f0cf6672b3f74a172b5dcfa-x86_64-unknown-linux-gnu'
```

Hm, not looking good, and a different error too. We could try pinging the the developer involved in https://github.com/cross-rs/cross/issues/1496 (the cross issue about the same thing), because a quick look through the wiki for cross didn't show any way to do this. @Emilgardis

**Comment by lqd** [comment]
I tested this on the same kind of gcc that the cross docker images should contain, so it's not the end of the world if you don't know how I can reproduce the issue, or if cross can't use the CI artifacts. We think it should work, and you'd be able to test once it lands on master as a real toolchain, with the expected std for cross compilation of course. 

If it doesn't then you'd let us know :)

**Comment by lqd** [comment]
(The invalid toolchain name is not from cross but from rustup)

**Comment by Emilgardis** [comment]
@VorpalBlade the way to use the custom toolchain would be `CROSS_CUSTOM_TOOLCHAIN=1`

**Comment by VorpalBlade** [comment]
@lqd 

```console
❯ rustup-toolchain-install-master 5572f385cb1b21326f0cf6672b3f74a172b5dcfa -n 78c8355821161d05841b58cd7c27ff0bb679847d -t aarch64-unknown-linux-gnu
detecting the channel of the `5572f385cb1b21326f0cf6672b3f74a172b5dcfa` toolchain...
downloading <https://ci-artifacts.rust-lang.org/rustc-builds/5572f385cb1b21326f0cf6672b3f74a172b5dcfa/rustc-nightly-x86_64-unknown-linux-gnu.tar.xz>...
74.12 MB / 74.12 MB [=====================================================================================================================================================] 100.00 % 18.31 MB/s 
downloading <https://ci-artifacts.rust-lang.org/rustc-builds/5572f385cb1b21326f0cf6672b3f74a172b5dcfa/rust-std-nightly-aarch64-unknown-linux-gnu.tar.xz>...
error: missing component `rust-std` on toolchain `5572f385cb1b21326f0cf6672b3f74a172b5dcfa` on channel `nightly` for target `aarch64-unknown-linux-gnu`
```

Well that didn't seem to work either.

File: compiler/rustc_codegen_ssa/src/back/link.rs (hunk 1 above)
Comment (lqd) [reply compiler/rustc_codegen_ssa/src/back/link.rs:810]: Yeah the utf8 conversion or allocation costs are not going to be super important in this error path. Let's keep things consistent for now in this PR where I'm trying to fix a p-high issue. But IMO, if you have time, feel free to open a PR changing this existing codepath, it will not hurt to discuss this with other people. 

I'll resolve this for now.

**Comment by Emilgardis** [comment]
nevermind, seems rustup-toolchain-master installs the toolchains a bit different to cargo-bisect-rusct, and doesn't really work with `cross +toolchain` handling. I'll try to make a fix for it.

Anyway, this pr should resolve the issue.

**Comment by lqd** [comment]
It seems `rustup-toolchain-install-master` installs toolchains that don't support components, so adding the target will fail anyways:

```console
$ rustup +78c8355821161d05841b58cd7c27ff0bb679847d target add aarch64-unknown-linux-gnu
error: toolchain '78c8355821161d05841b58cd7c27ff0bb679847d' does not support components
```

> Anyway, this pr should resolve the issue.

agreed

**Comment by lqd** [comment]
Alrighty. We can't test with cross until this lands, we know it works on CentOS7, and it should it fix it there too.

@bors r=petrochenkov

**Comment by VorpalBlade** [comment]
Works fine with nightly and cross now. Thanks!
