### PR TITLE
The embedded bitcode should always be prepared for LTO/ThinLTO

### LINKED ISSUE #115344: Failed to compile a project with LTO + PGO
In https://github.com/vectordotdev/vector/issues/15631#issuecomment-1694554798 I tried to optimize [Vector](https://vector.dev) with LTO + PGO enabled. But during the optimization phase (done with `cargo pgo optimize`) I get the following error: https://github.com/Kobzol/cargo-pgo/issues/32#issuecomment-1694445787 . I am not the only person with this error - https://github.com/llvm/llvm-project/issues/57501#issuecomment-1694392182 (@kevincox probably can provide more details about they project).

The only way to avoid the bug is disable LTO completely (switching from Fat to Thin mode does not help).

I expected to see this happen: Vector compiles successfully with LTO and PGO enabled.

Instead, this happened: Vector failed to compile with LTO + PGO.

### Meta
`rustc --version --verbose` (from https://github.com/vectordotdev/vector/blob/master/rust-toolchain.toml):
```
1.71.1
```
Other links:
* Possibly related bug in LLVM (but I am not sure): https://github.com/llvm/llvm-project/issues/57501
* A discussion in `cargo-pgo`: https://github.com/Kobzol/cargo-pgo/issues/32

### LINKED ISSUE #117220: Combining LTO + PGO + lib/cdylib crashes on LLVM assertion
When compiling a cargo project with:
- LTO enabled (`LTO=thin/fat`)
- PGO (`-Cprofile-use`)
- Both `lib` and `dylib` targets for its library

Reproducer
```rust
// src/main.rs
use clap::Command;

fn main() {
    Command::new("a").about("a");
}
```

```toml
# Cargo.toml
[package]
name = "hello"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.3.24" , default-features = false, features = ["std"]}

[profile.release]
lto = "thin"

[lib]
crate-type = ["lib", "cdylib"]
```

There also needs to be an empty `src/lib.rs` file. Here is a reproducer script for PGO:
```bash
#!/bin/bash

set -e

VERSION=${1:-1.71}

rustup install ${VERSION}
rustup component add llvm-tools-preview --toolchain ${VERSION}
rm -rf target
rm -rf /tmp/pgo
RUSTFLAGS="-Cprofile-generate=/tmp/pgo" cargo +${VERSION} build --release
./target/release/hello /tmp
`rustc +${VERSION} --print=sysroot`/lib/rustlib/x86_64-unknown-linux-gnu/bin/llvm-profdata merge -o merged-${VERSION}.profdata /tmp/pgo/*
RUSTFLAGS="-Cprofile-use=${PWD}/merged-${VERSION}.profdata" cargo +${VERSION} build --release
```

I expected to see this happen: the project compiles.

Instead, compilation fails with the following error:
```
module flag identifiers must be unique (or of 'require' type)
!"CG Profile"
LLVM ERROR: Broken module found, compilation aborted!
```

This was originally found in https://github.com/rust-lang/rust/issues/115344, which contains many examples of this problem in the wild. Here I sent a minimal example, I wasn't able to minimize it further (removing LTO, PGO, clap or lib/dylib) fixes the problem.

### Meta
`rustc --version --verbose`:
```
rustc 1.73.0 (cc66ad468 2023-10-03)
binary: rustc
commit-hash: cc66ad468955717ab92600c770da8c1601a4ff33
commit-date: 2023-10-03
host: x86_64-unknown-linux-gnu
release: 1.73.0
LLVM version: 17.0.2
```
I managed to reproduce this all the way back to `1.60.0` (although this specific example requires at least `1.70.0` due to `clap`).

### PR DESCRIPTION
**Pull request by dianqk**
Fixes #115344. Fixes #117220.

There are currently two methods for generating bitcode that used for LTO. One method involves using `-C linker-plugin-lto` to emit object files as bitcode, which is the typical setting used by cargo. The other method is through `-C embed-bitcode=yes`.

When using with `-C embed-bitcode=yes -C lto=no`, we run a complete non-LTO LLVM pipeline to obtain bitcode, then the bitcode is used for LTO. We run the Call Graph Profile Pass twice on the same module.

This PR is doing something similar to LLVM's `buildFatLTODefaultPipeline`, obtaining the bitcode for embedding after running `buildThinLTOPreLinkDefaultPipeline`.

r? nikic

### CODE REVIEW

**Review by nikic — COMMENTED** [review]
This focuses on the no-lto case, but don't we currently also embed post-link bitcode when using thin-local?

I'm a bit concerned that this is implemented by running by module cloning and a separate optimization pipeline. This is slow and cloning has correctness issues (though I think they're blockaddress related, so currently not relevant for Rust). The way LLVM itself does this (see buildFatLTODefaultPipeline) is to embed the bitcode post-ThinLTOPreLink and then run ModuleOptimization (on the same module) before codegen.

**Comment by DianQK** [comment]
I think this is basically ready for review. Some potential adjustments could be addressed in subsequent PRs:

- (Possibly in this PR) Rename `ThinBitcode` to `PreLtoBitcode`?
- Refactor the code related to `emit_pre_lto_bc`
- Reuse the embed bitcode for `--emit=llvm-bc` when using `-C linker-plugin-lto`?

@rustbot review

**Comment by DianQK** [comment]
> I think this is basically ready for review. Some potential adjustments could be addressed in subsequent PRs:
> 
> * (Possibly in this PR) Rename `ThinBitcode` to `PreLtoBitcode`?
> * Refactor the code related to `emit_pre_lto_bc`
> * Reuse the embed bitcode for `--emit=llvm-bc` when using `-C linker-plugin-lto`?
> 
> @rustbot review

Hmm, when passing `-Z emit-thin-lto=false`, it's different bitcode between the embed bitcode and the pre-LTO bitcode. I think all changes can be disussed later.

**Comment by DianQK** [comment]
Two weeks ping

**Comment by DianQK** [comment]
Two weeks ping again @nikic

**Comment by DianQK** [comment]
ping
If there's anything that needs to be changed, please don't hesitate to let me know.

File: compiler/rustc_session/src/config.rs
Comment (nikic) [inline compiler/rustc_session/src/config.rs:1]: Do the changes here also enable `--emit=thin-llvm-bc`? If yes, is it stable or unstable?

File: compiler/rustc_session/src/config.rs [hunk 1]
```diff
@@ -508,6 +508,7 @@ impl FromStr for SplitDwarfKind {
 pub enum OutputType {
     Bitcode,
     ThinLinkBitcode,
+    ThinBitcode,
```
Comment (nikic) [inline compiler/rustc_session/src/config.rs:511]: Please add doc comments to Bitcode, ThinLinkBitcode and ThinBitcode to explain what the difference between them is...

**Review by nikic — COMMENTED** [review]
This generally looks reasonable to me.

Is writing the bitcode out into the incremental directory the usual thing to do, as opposed to keeping it in memory until it is embedded?

File: compiler/rustc_codegen_llvm/src/back/write.rs [hunk 2]
```diff
@@ -714,61 +773,60 @@ pub(crate) unsafe fn codegen(
...
-                let _timer = cgcx.prof.generic_activity_with_arg(
-                    "LLVM_module_codegen_emit_bitcode_summary",
-                    &*module.name,
-                );
-                if let Err(err) = fs::write(&bc_summary_out, summary_data) {
-                    dcx.emit_err(WriteBytecode { path: &bc_summary_out, err });
-                }
-            }
-
+            // If the object file of the target spec is bitcode, what happens when performing LTO in Rust?
```
[the remark this answers is not in the document]
Comment (DianQK) [reply compiler/rustc_codegen_llvm/src/back/write.rs]: For myself, I intend to merge more pre-LTO bitcode code.

File: compiler/rustc_session/src/config.rs
Comment (DianQK) [reply compiler/rustc_session/src/config.rs:1]: I think we can only emit it under the `-Csave-temps` flag that I haven't implemented yet.

**Comment by DianQK** [comment]
I've rebased due to conflicts with #130060.

> Is writing the bitcode out into the incremental directory the usual thing to do, as opposed to keeping it in memory until it is embedded?

I can put `Option<ThinBuffer>` in `ModuleCodegen`, but this might be a significant change. Perhaps I could use `Option<Vec<u8>>` first?

@rustbot author

**Comment by DianQK** [comment]
Sorry for the late update. Pre-linked bitcode no longer needs to be saved to a file now.

@rustbot review

File: compiler/rustc_codegen_llvm/src/back/lto.rs [hunk 3]
```diff
@@ -712,11 +715,10 @@ pub(crate) unsafe fn optimize_thin_module(
...
     let module_llvm = ModuleLlvm::parse(cgcx, module_name, thin_module.data(), dcx)?;
-    let mut module = ModuleCodegen {
-        module_llvm,
-        name: thin_module.name().to_string(),
-        kind: ModuleKind::Regular,
-    };
+    let mut module = ModuleCodegen::new_regular(thin_module.name(), module_llvm);
+    if cgcx.config(ModuleKind::Regular).embed_bitcode() {
+        module.thin_lto_buffer = Some(thin_module.data().to_vec());
+    }
```
Comment (nikic) [inline compiler/rustc_codegen_llvm/src/back/lto.rs:721]: Why does the updated implementation need to change this code as well?

**Review by nikic — COMMENTED** [review]
Looks good to me, but needs a rebase.

File: compiler/rustc_codegen_llvm/src/back/lto.rs [hunk 4]
```diff
@@ -733,11 +738,11 @@ pub(crate) unsafe fn optimize_thin_module(
     // crates but for locally codegened modules we may be able to reuse
     // that LLVM Context and Module.
     let module_llvm = ModuleLlvm::parse(cgcx, module_name, thin_module.data(), dcx)?;
-    let mut module = ModuleCodegen {
-        module_llvm,
-        name: thin_module.name().to_string(),
-        kind: ModuleKind::Regular,
-    };
+    let mut module = ModuleCodegen::new_regular(thin_module.name(), module_llvm);
+    // Given that the newly created Model lacks a thinlto buffer for embedding, we need to re-add it here.
```
Comment (bjorn3) [inline compiler/rustc_codegen_llvm/src/back/lto.rs:742]: *Module

File: compiler/rustc_codegen_llvm/src/back/lto.rs (hunk 3 above)
Comment (DianQK) [reply compiler/rustc_codegen_llvm/src/back/lto.rs:745]: As the newly created Model lacks a thinlto buffer, I can conveniently use the existing thin module here.
Added comment.

**Comment by gulfemsavrun** [comment]
We hit this issue where we try to test and enable LTO + PGO in our project. What is the status on this fix?

**Comment by DianQK** [comment]
Any more comments? @nikic 
Or you want to wait for #135763 to be merged?

(LGTM should not mean`r=me`, I guess.)

**Comment by DianQK** [comment]
pinging ~ @nikic
in case you missed this.

**Comment by ehuss** [comment]
@bors p=4

Trying to keep some queue fairness since this PR is a bit older.
