### PR TITLE
Properly recover from parenthesized use-bounds (precise capturing lists) plus small cleanups

### LINKED ISSUE #145470: `(use<>` forgets to look for `)`
In the following code, after `(use<>`, while still inside parenthesized content, the parser successfully parses the function body and tuple struct, oblivious that these were supposed to have been outside `)`.

```rust
fn repro() -> impl (use<> {
    println!("?");
}

#[derive(Debug)]
struct Struct<F>(i32, F)
where
    T: Fn() -> i32;

)
```

```console
error: expected item, found `)`
  --> src/lib.rs:10:1
   |
10 | )
   | ^ expected item
   |
   = note: for a full list of items that can appear in modules, see <https://doc.rust-lang.org/reference/items.html>
```

It seems pretty clear to me that this is unintended behavior, not some kind of intentional parsing recovery. The same bug does not occur for a mismatched parenthesis around lifetime bound or trait bound.

```console
error: expected `)`, found `{`
 --> src/lib.rs:1:24
  |
1 | fn repro() -> impl ('a {
  |                        ^ expected `)`
```

```console
error: expected one of `(`, `)`, `::`, or `<`, found `{`
 --> src/lib.rs:1:27
  |
1 | fn repro() -> impl (Trait {
  |                           ^ expected one of `(`, `)`, `::`, or `<`
```

### PR DESCRIPTION
**Pull request by fmease**
Fixes https://github.com/rust-lang/rust/issues/145470.

First commit fixes the issue, second one performs some desperately needed cleanups.

The fix shouldn't be a breaking change because IINM the parser always ensures that all brackets are balanced (via a buffer of brackets). Meaning even though we used to accept `(use<>` as a valid precise capturing list, it was guaranteed that we would fail in the end.

### CODE REVIEW

File: compiler/rustc_parse/src/parser/ty.rs [hunk 1]
```diff
@@ -876,7 +877,22 @@ impl<'a> Parser<'a> {
...
         )?;
         self.expect_gt()?;
-        Ok((args, lo.to(self.prev_token.span)))
+
+        if let ast::Parens::Yes = parens {
+            self.expect(exp!(CloseParen))?;
+            let hi = self.prev_token.span;
+            let mut diag = self
+                .dcx()
+                .struct_span_err(lo.to(hi), "precise capturing lists may not be parenthesized");
```
Comment (fmease) [inline compiler/rustc_parse/src/parser/ty.rs]: First time that the term "precise capturing list" is used (in the compiler). In the AST validator, we emit diagnostics mentioning "precise capturing syntax" but "[…] syntax may not be parenthesized" feels super off to me (mixing of abstraction levels) but I'm L2, so.

The Reference and the AST use "use-bounds" essentially but the problem with that is the fact that later compiler stages (and the release blog post, GH issues & other documents) all use "precise capturing" when referring to this feature (in general or from a semantic standpoint specifically), so I was hesitant to deviate too far from this generally accepted terminology in user-facing output.

(Re. the phrasing "[…] not supported" for such things, I really don't like it; it should either be "not supported yet" + actual official proposal or it's plainly ungrammatical, no in-between.)
