### PR TITLE
Change std::panicking::try::Data into a union

### LINKED ISSUE #39432: thread::spawn with function with no return result type causes SIGSEGV
Messages are never printed, the program just crashes.

This only happens in release mode.

### What I did?

Ran following program in release mode.

```rust
use std::thread;

fn worker() -> ! {
    loop {
        println!("Printing messages");
    }
}

fn main() {
    thread::spawn(worker);
    loop {
        thread::park();
    }
}
```

### What was expected?

Flood of "Printing messages" messages.

### What happened instead.

SIGSEGV

## Meta

This was confirmed to happen on stable (on IRC and in playpen), however I don't have stable installed.

```
rustc 1.16.0-nightly (df8debf6d 2017-01-25)
binary: rustc
commit-hash: df8debf6d9afc431adbbd8311dcaf2b70eb9762e
commit-date: 2017-01-25
host: x86_64-unknown-linux-gnu
release: 1.16.0-nightly
LLVM version: 3.9
```

### PR DESCRIPTION
**Pull request by ghost**
No longer potentially call `mem::uninitialized::<!>()`

Fixes #39432

### CODE REVIEW

**Comment by jmesmon** [comment]
It's likely the large comment under the new `union` should be updated to match the new impl.

**Comment by whataloadofwhat** [comment]
I thought about that but it all still seemed mostly relevant, just that the implementation changed. I was supposed to get rid of the line about it never being valid, which isn't really true any more, but I forgot, whoops. Is there anything else that seems off?

**Comment by alexcrichton** [comment]
@bors: r+

Thanks!

**Comment by alexcrichton** [comment]
@bors: r-

Er actually yeah let's touch up that comment. I can probably just use minor tweaks here and there as it's mostly still applicable

**Comment by whataloadofwhat** [comment]
Is this any better?

File: src/libstd/panicking.rs [hunk 1]
```diff
@@ -396,34 +396,27 @@ pub unsafe fn try<R, F: FnOnce() -> R>(f: F) -> Result<R, Box<Any + Send>> {
...
     // * If the closure successfully returns, we write the return value into the
     //   data's return slot. Note that `ptr::write` is used as it's overwriting
     //   uninitialized data.
     // * Finally, when we come back out of the `__rust_maybe_catch_panic` we're
     //   in one of two states:
     //
     //      1. The closure didn't panic, in which case the return value was
-    //         filled in. We have to be careful to `forget` the closure,
-    //         however, as ownership was passed to the `do_call` function.
+    //         filled in.
```
Comment (jmesmon) [inline src/libstd/panicking.rs]: Could still mention why not dropping is ok.

File: src/libstd/panicking.rs [hunk 2]
```diff
@@ -396,34 +396,27 @@ pub unsafe fn try<R, F: FnOnce() -> R>(f: F) -> Result<R, Box<Any + Send>> {
...
     //      2. The closure panicked, in which case the return value wasn't
     //         filled in. In this case the entire `data` structure is invalid,
-    //         so we forget the entire thing.
+    //         so we ignore it because unions don't have drop glue.
```
Comment (jmesmon) [inline src/libstd/panicking.rs]: `In this case the entire `data` structure is invalid, so there is no need to drop` is more correct here. We don't ignore it "*because* unions don't have drop glue", it is ignored by taking advantage of that.

File: src/libstd/panicking.rs (hunk 1 above)
Comment (whataloadofwhat) [inline src/libstd/panicking.rs]: In this case, it is dropped like normal. Well `data.r` is moved out, but it's just a regular move, nothing special. Should I mention that?

Comment (jmesmon) [inline src/libstd/panicking.rs]: Ah, I think you're right here. Your deletion seems fine.

File: src/libstd/panicking.rs (hunk 2 above)
Comment (whataloadofwhat) [inline src/libstd/panicking.rs]: Thanks, that's a lot better

**Comment by alexcrichton** [comment]
Looks good to me! Want to squash the commits as well?

**Comment by whataloadofwhat** [comment]
Alright
