### PR TITLE
resolve: Scale back unloading of speculatively loaded crates

### LINKED ISSUE #120830: thread 'rustc' panicked at compiler/rustc_metadata/src/rmeta/encoder.rs:1888:17
### Code

 https://github.com/diesel-rs/diesel/commit/dfeec4bbeb3c80a4303b0b1d271cad26f137214b

Clone the repo and, set `RUSTFLAGS=-Zsanitizer=address` run `cargo test --manifest-path diesel_tests/Cargo.toml --no-default-features --features "sqlite libsqlite3-sys libsqlite3-sys/bundled libsqlite3-sys/with-asan" --target x86_64-unknown-linux-gnu` to reproduce the ICE

### Meta

`rustc --version --verbose`:
```
rustc 1.78.0-nightly (98aa3624b 2024-02-08)
binary: rustc
commit-hash: 98aa3624be70462d6a25ed5544333e3df62f4c66
commit-date: 2024-02-08
host: x86_64-unknown-linux-gnu
release: 1.78.0-nightly
LLVM version: 17.0.6
```

### Error output

```
thread 'rustc' panicked at compiler/rustc_metadata/src/rmeta/encoder.rs:1888:17:
assertion `left == right` failed
  left: crate29
 right: crate28
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
stack backtrace:
   0:     0x7f6d427f5dd6 - std::backtrace_rs::backtrace::libunwind::trace::hcf4842620364d535
                               at /rustc/98aa3624be70462d6a25ed5544333e3df62f4c66/library/std/src/../../backtrace/src/backtrace/libunwind.rs:104:5
   1:     0x7f6d427f5dd6 - std::backtrace_rs::backtrace::trace_unsynchronized::h615a7d3c4b72d07a
                               at /rustc/98aa3624be70462d6a25ed5544333e3df62f4c66/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7f6d427f5dd6 - std::sys_common::backtrace::_print_fmt::h777946980bbce9d4
                               at /rustc/98aa3624be70462d6a25ed5544333e3df62f4c66/library/std/src/sys_common/backtrace.rs:68:5
   3:     0x7f6d427f5dd6 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h0fdadf67cf82c3e5
                               at /rustc/98aa3624be70462d6a25ed5544333e3df62f4c66/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x7f6d42848830 - core::fmt::rt::Argument::fmt::h40bec717748a6a66
                               at /rustc/98aa3624be70462d6a25ed5544333e3df62f4c66/library/core/src/fmt/rt.rs:142:9
   5:     0x7f6d42848830 - core::fmt::write::hfb3923fb2f513fc0
                               at /rustc/98aa3624be70462d6a25ed5544333e3df62f4c66/library/core/src/fmt/mod.rs:1120:17
   6:     0x7f6d427e964f - std::io::Write::write_fmt::h7dd8ba1b7fdc9479
                               at /rustc/98aa3624be70462d6a25ed5544333e3df62f4c66/library/std/src/io/mod.rs:1854:15
   7:     0x7f6d427f5bb4 - std::sys_common::backtrace::_print::hffce9865d8ccd857
                               at /rustc/98aa3624be70462d6a25ed5544333e3df62f4c66/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x7f6d427f5bb4 - std::sys_common::backtrace::print::h532d3566cc4254d4
                               at /rustc/98aa3624be70462d6a25ed5544333e3df62f4c66/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x7f6d427f8947 - std::panicking::default_hook::{{closure}}::hfa7000b32c4e888b
  10:     0x7f6d427f86a9 - std::panicking::default_hook::haaf1b4b762fde1ac
                               at /rustc/98aa3624be70462d6a25ed5544333e3df62f4c66/library/std/src/panicking.rs:292:9
  11:     0x7f6d3f33b78c - std[5c40b41967587ec6]::panicking::update_hook::<alloc[5d4b954b8b3d7648]::boxed::Box<rustc_driver_impl[ab5bb327712dbf0b]::install_ice_hook::{closure#0}>>::{closure#0}
  12:     0x7f6d427f9096 - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h4c230f69fdc2df31
                               at /rustc/98aa3624be70462d6a25ed5544333e3df62f4c66/library/alloc/src/boxed.rs:2029:9
  13:     0x7f6d427f9096 - std::panicking::rust_panic_with_hook::h89e8d9a00153591c
                               at /rustc/98aa3624be70462d6a25ed5544333e3df62f4c66/library/std/src/panicking.rs:785:13
  14:     0x7f6d427f8de2 - std::panicking::begin_panic_handler::{{closure}}::h0fe7a7a11cf6b670
                               at /rustc/98aa3624be70462d6a25ed5544333e3df62f4c66/library/std/src/panicking.rs:659:13
  15:     0x7f6d427f62d6 - std::sys_common::backtrace::__rust_end_short_backtrace::h5875974741c16bab
                               at /rustc/98aa3624be70462d6a25ed5544333e3df62f4c66/library/std/src/sys_common/backtrace.rs:171:18
  16:     0x7f6d427f8b34 - rust_begin_unwind
                               at /rustc/98aa3624be70462d6a25ed5544333e3df62f4c66/library/std/src/panicking.rs:647:5
  17:     0x7f6d42844f35 - core::panicking::panic_fmt::h58288a9f4ffa83be
                               at /rustc/98aa3624be70462d6a25ed5544333e3df62f4c66/library/core/src/panicking.rs:72:14
  18:     0x7f6d428454cb - core::panicking::assert_failed_inner::h22c9753a230525e4
                               at /rustc/98aa3624be70462d6a25ed5544333e3df62f4c66/library/core/src/panicking.rs:342:17
  19:     0x7f6d3f6e5767 - core[2f2a284c56ca7af5]::panicking::assert_failed::<rustc_span[e69a7bbb34a31e54]::def_id::CrateNum, rustc_span[e69a7bbb34a31e54]::def_id::CrateNum>
  20:     0x7f6d415f9fc2 - <rustc_metadata[c819bf0142ad3cc8]::rmeta::encoder::EncodeContext>::encode_crate_root
  21:     0x7f6d41618f3b - rustc_metadata[c819bf0142ad3cc8]::rmeta::encoder::encode_metadata
  22:     0x7f6d41617568 - rustc_metadata[c819bf0142ad3cc8]::fs::encode_and_write_metadata
  23:     0x7f6d415a0bc3 - rustc_interface[f5c5c4389ec3cf3a]::passes::start_codegen
  24:     0x7f6d415a03b4 - <rustc_interface[f5c5c4389ec3cf3a]::queries::Queries>::codegen_and_build_linker
  25:     0x7f6d4131744c - rustc_interface[f5c5c4389ec3cf3a]::interface::run_compiler::<core[2f2a284c56ca7af5]::result::Result<(), rustc_span[e69a7bbb34a31e54]::ErrorGuaranteed>, rustc_driver_impl[ab5bb327712dbf0b]::run_compiler::{closure#0}>::{closure#0}
  26:     0x7f6d40fa9386 - std[5c40b41967587ec6]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[f5c5c4389ec3cf3a]::util::run_in_thread_with_globals<rustc_interface[f5c5c4389ec3cf3a]::util::run_in_thread_pool_with_globals<rustc_interface[f5c5c4389ec3cf3a]::interface::run_compiler<core[2f2a284c56ca7af5]::result::Result<(), rustc_span[e69a7bbb34a31e54]::ErrorGuaranteed>, rustc_driver_impl[ab5bb327712dbf0b]::run_compiler::{closure#0}>::{closure#0}, core[2f2a284c56ca7af5]::result::Result<(), rustc_span[e69a7bbb34a31e54]::ErrorGuaranteed>>::{closure#0}, core[2f2a284c56ca7af5]::result::Result<(), rustc_span[e69a7bbb34a31e54]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[2f2a284c56ca7af5]::result::Result<(), rustc_span[e69a7bbb34a31e54]::ErrorGuaranteed>>
  27:     0x7f6d40fa91b3 - <<std[5c40b41967587ec6]::thread::Builder>::spawn_unchecked_<rustc_interface[f5c5c4389ec3cf3a]::util::run_in_thread_with_globals<rustc_interface[f5c5c4389ec3cf3a]::util::run_in_thread_pool_with_globals<rustc_interface[f5c5c4389ec3cf3a]::interface::run_compiler<core[2f2a284c56ca7af5]::result::Result<(), rustc_span[e69a7bbb34a31e54]::ErrorGuaranteed>, rustc_driver_impl[ab5bb327712dbf0b]::run_compiler::{closure#0}>::{closure#0}, core[2f2a284c56ca7af5]::result::Result<(), rustc_span[e69a7bbb34a31e54]::ErrorGuaranteed>>::{closure#0}, core[2f2a284c56ca7af5]::result::Result<(), rustc_span[e69a7bbb34a31e54]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[2f2a284c56ca7af5]::result::Result<(), rustc_span[e69a7bbb34a31e54]::ErrorGuaranteed>>::{closure#1} as core[2f2a284c56ca7af5]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  28:     0x7f6d42802735 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hd35908ec403131f0
                               at /rustc/98aa3624be70462d6a25ed5544333e3df62f4c66/library/alloc/src/boxed.rs:2015:9
  29:     0x7f6d42802735 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h6d654616ee0757b9
                               at /rustc/98aa3624be70462d6a25ed5544333e3df62f4c66/library/alloc/src/boxed.rs:2015:9
  30:     0x7f6d42802735 - std::sys::pal::unix::thread::Thread::new::thread_start::h987e3b25a01ed571
                               at /rustc/98aa3624be70462d6a25ed5544333e3df62f4c66/library/std/src/sys/pal/unix/thread.rs:108:17
  31:     0x7f6d425bd897 - start_thread
  32:     0x7f6d4264480c - clone3

  33:                0x0 - <unknown>
```

</p>
</details>

[rustc-ice-2024-02-09T07_36_46-724311.txt](https://github.com/rust-lang/rust/files/14218567/rustc-ice-2024-02-09T07_36_46-724311.txt)

Running `cargo bisect-rustc` points to https://github.com/rust-lang/rust/pull/120767

searched nightlies: from nightly-2024-02-08 to nightly-2024-02-09
regressed nightly: nightly-2024-02-09
searched commit range: https://github.com/rust-lang/rust/compare/8ace7ea1f7cbba7b4f031e66c54ca237a0d65de6...98aa3624be70462d6a25ed5544333e3df62f4c66
regressed commit: https://github.com/rust-lang/rust/commit/1280928a99ad3ef2c5735b42dc8852456ae3b974

<details>
<summary>bisected with <a href='https://github.com/rust-lang/cargo-bisect-rustc'>cargo-bisect-rustc</a> v0.6.5</summary>

Host triple: x86_64-unknown-linux-gnu
Reproduce with:
```bash
RUSTFLAGS=-Zsanitizer=address cargo bisect-rustc --start=2024-02-08 --end=2024-02-09 --with-src -- test --manifest-path diesel_tests/Cargo.toml --no-default-features --features sqlite libsqlite3-sys libsqlite3-sys/bundled libsqlite3-sys/with-asan --target x86_64-unknown-linux-gnu --no-run 
```
</details>

### LINKED ISSUE #120909: ICE in nightly: "Failed to get crate data for crate15" when `proc-macro` references a dependency in a doc comment
### Code

Minimal repro: https://github.com/parasyte/crash-rustc

This ICE needs a specific project setup with a `proc-macro` that has a doc-comment referencing one of its crate dependencies. The git repo above is a full example, but this will work, too:

# Cargo.toml

```toml
[package]
name = "crash-rustc"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
base64 = "0.21"
```

# lib.rs

```rust
//! [`base64`]
```

The error only seems to happen with crates that do not contain hyphens in the name. I don't know, I haven't really dug into it. `base64` is a popular crate, it doesn't have any dependencies, and it exhibits the crash. The git repo above has a totally empty dependency named `crashy`, so it doesn't really matter what the dependency itself contains.

### Meta

`rustc --version --verbose`:
```
rustc 1.78.0-nightly (6cc484351 2024-02-10)
binary: rustc
commit-hash: 6cc4843512d613f51ec81aba689180c31b0b28b6
commit-date: 2024-02-10
host: x86_64-pc-windows-msvc
release: 1.78.0-nightly
LLVM version: 17.0.6
```

### Error output

```
thread 'rustc' panicked at compiler\rustc_metadata\src\creader.rs:195:32:
Failed to get crate data for crate15
stack backtrace:
   0:     0x7ff93f662972 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hc99197c9b2d6b3ef
   1:     0x7ff93f69563d - core::fmt::write::h2264ae2ff10f9d05
   2:     0x7ff93f658ff1 - <std::io::IoSliceMut as core::fmt::Debug>::fmt::h32e7988c01068207
   3:     0x7ff93f66279a - std::sys_common::backtrace::lock::h4ad46ad9c5ad405f
   4:     0x7ff93f665b59 - std::panicking::default_hook::h0ba92da552d0410c
   5:     0x7ff93f665815 - std::panicking::default_hook::h0ba92da552d0410c
   6:     0x7ff926429b15 - <tracing_subscriber[1a895b7d438f8c1d]::util::TryInitError as core[1a9ca60cf5f5707d]::fmt::Display>::fmt
   7:     0x7ff93f666163 - std::panicking::rust_panic_with_hook::haa5b2a955d6e9910
   8:     0x7ff93f666009 - <std::panicking::begin_panic_handler::StaticStrPayload as core::panic::PanicPayload>::take_box::h1fc7089d2c1f3293
   9:     0x7ff93f663279 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hc99197c9b2d6b3ef
  10:     0x7ff93f665cd6 - rust_begin_unwind
  11:     0x7ff93f6bb737 - core::panicking::panic_fmt::h3b76f05d3256bd9f
  12:     0x7ff92516a3db - <rustc_metadata[2f9ed4c92abfca28]::creader::CStore as rustc_session[3bf59b46651f552d]::cstore::CrateStore>::stable_crate_id
  13:     0x7ff9262656fd - <rustc_middle[9193cad70d79b3d1]::ty::visit::LateBoundRegionsCollector as rustc_type_ir[fbb395866ffc979a]::visit::TypeVisitor<rustc_middle[9193cad70d79b3d1]::ty::context::TyCtxt>>::visit_ty
  14:     0x7ff9252a6b00 - <rustc_middle[9193cad70d79b3d1]::query::on_disk_cache::OnDiskCache>::serialize
  15:     0x7ff9252d58a3 - <rustc_middle[9193cad70d79b3d1]::ty::context::TyCtxt>::serialize_query_result_cache
  16:     0x7ff925112dda - rustc_incremental[f90b8bd0ccf92d0f]::persist::save::save_work_product_index
  17:     0x7ff925116c73 - rustc_incremental[f90b8bd0ccf92d0f]::persist::save::save_work_product_index
  18:     0x7ff92510ff77 - rustc_incremental[f90b8bd0ccf92d0f]::persist::load::setup_dep_graph
  19:     0x7ff925119c52 - rustc_incremental[f90b8bd0ccf92d0f]::persist::save::save_work_product_index
  20:     0x7ff9251105b0 - rustc_incremental[f90b8bd0ccf92d0f]::persist::load::setup_dep_graph
  21:     0x7ff925119e0b - rustc_incremental[f90b8bd0ccf92d0f]::persist::save::save_work_product_index
  22:     0x7ff92511175f - rustc_incremental[f90b8bd0ccf92d0f]::persist::save::save_dep_graph
  23:     0x7ff9224601de - rustc_driver_impl[b32f8017ee93a888]::main
  24:     0x7ff9224699d1 - rustc_driver_impl[b32f8017ee93a888]::main
  25:     0x7ff92245c48d - rustc_driver_impl[b32f8017ee93a888]::main
  26:     0x7ff92245def8 - rustc_driver_impl[b32f8017ee93a888]::main
  27:     0x7ff92249b74f - rustc_driver_impl[b32f8017ee93a888]::main
  28:     0x7ff92249a678 - rustc_driver_impl[b32f8017ee93a888]::main
  29:     0x7ff93f676b1c - std::sys::pal::windows::thread::Thread::new::h12285e0320d9cc9c
  30:     0x7ff9d256257d - BaseThreadInitThunk
  31:     0x7ff9d420aa58 - RtlUserThreadStart

error: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: please attach the file at `C:\Users\jay\Desktop\crash-rustc\rustc-ice-2024-02-11T02_19_09-221228.txt` to your bug report

note: compiler flags: --crate-type proc-macro -C prefer-dynamic -C embed-bitcode=no -C debuginfo=2 -C incremental=[REDACTED]

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
stack backtrace:
   0:     0x7ff93f662972 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hc99197c9b2d6b3ef
   1:     0x7ff93f69563d - core::fmt::write::h2264ae2ff10f9d05
   2:     0x7ff93f658ff1 - <std::io::IoSliceMut as core::fmt::Debug>::fmt::h32e7988c01068207
   3:     0x7ff93f66279a - std::sys_common::backtrace::lock::h4ad46ad9c5ad405f
   4:     0x7ff93f665b59 - std::panicking::default_hook::h0ba92da552d0410c
   5:     0x7ff93f665815 - std::panicking::default_hook::h0ba92da552d0410c
   6:     0x7ff926429b15 - <tracing_subscriber[1a895b7d438f8c1d]::util::TryInitError as core[1a9ca60cf5f5707d]::fmt::Display>::fmt
   7:     0x7ff93f666163 - std::panicking::rust_panic_with_hook::haa5b2a955d6e9910
   8:     0x7ff93f666009 - <std::panicking::begin_panic_handler::StaticStrPayload as core::panic::PanicPayload>::take_box::h1fc7089d2c1f3293
   9:     0x7ff93f663279 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hc99197c9b2d6b3ef
  10:     0x7ff93f665cd6 - rust_begin_unwind
  11:     0x7ff93f6bb737 - core::panicking::panic_fmt::h3b76f05d3256bd9f
  12:     0x7ff92516a3db - <rustc_metadata[2f9ed4c92abfca28]::creader::CStore as rustc_session[3bf59b46651f552d]::cstore::CrateStore>::stable_crate_id
  13:     0x7ff9262656fd - <rustc_middle[9193cad70d79b3d1]::ty::visit::LateBoundRegionsCollector as rustc_type_ir[fbb395866ffc979a]::visit::TypeVisitor<rustc_middle[9193cad70d79b3d1]::ty::context::TyCtxt>>::visit_ty
  14:     0x7ff9252a6b00 - <rustc_middle[9193cad70d79b3d1]::query::on_disk_cache::OnDiskCache>::serialize
  15:     0x7ff9252d58a3 - <rustc_middle[9193cad70d79b3d1]::ty::context::TyCtxt>::serialize_query_result_cache
  16:     0x7ff925112dda - rustc_incremental[f90b8bd0ccf92d0f]::persist::save::save_work_product_index
  17:     0x7ff925116c73 - rustc_incremental[f90b8bd0ccf92d0f]::persist::save::save_work_product_index
  18:     0x7ff92510ff77 - rustc_incremental[f90b8bd0ccf92d0f]::persist::load::setup_dep_graph
  19:     0x7ff925119c52 - rustc_incremental[f90b8bd0ccf92d0f]::persist::save::save_work_product_index
  20:     0x7ff9251105b0 - rustc_incremental[f90b8bd0ccf92d0f]::persist::load::setup_dep_graph
  21:     0x7ff925119e0b - rustc_incremental[f90b8bd0ccf92d0f]::persist::save::save_work_product_index
  22:     0x7ff92511175f - rustc_incremental[f90b8bd0ccf92d0f]::persist::save::save_dep_graph
  23:     0x7ff9224601de - rustc_driver_impl[b32f8017ee93a888]::main
  24:     0x7ff9224699d1 - rustc_driver_impl[b32f8017ee93a888]::main
  25:     0x7ff92245c48d - rustc_driver_impl[b32f8017ee93a888]::main
  26:     0x7ff92245def8 - rustc_driver_impl[b32f8017ee93a888]::main
  27:     0x7ff92249b74f - rustc_driver_impl[b32f8017ee93a888]::main
  28:     0x7ff92249a678 - rustc_driver_impl[b32f8017ee93a888]::main
  29:     0x7ff93f676b1c - std::sys::pal::windows::thread::Thread::new::h12285e0320d9cc9c
  30:     0x7ff9d256257d - BaseThreadInitThunk
  31:     0x7ff9d420aa58 - RtlUserThreadStart
```

</p>
</details>

### PR DESCRIPTION
**Pull request by petrochenkov**
Fixes https://github.com/rust-lang/rust/issues/120830 and fixes https://github.com/rust-lang/rust/issues/120909 while still unblocking https://github.com/rust-lang/rust/pull/117772.

I cannot reproduce https://github.com/parasyte/crash-rustc as an UI test for some reason, but I tested all the cases linked above manually.

### CODE REVIEW

**Comment by petrochenkov** [comment]
Why https://github.com/rust-lang/rust/issues/120830 had issues:
- `CrateNum`s of unloaded crates are still remain in `SourceFile`s in source map, and we cannot unload source files (https://github.com/rust-lang/rust/pull/121038#issuecomment-1943693382).
- Holes in `CrateNum` list mess up crate num encoding/decoding in `encode_crate_deps`/`resolve_crate_deps`, which assumes that they are continuous between 1 and N.

Both issues are potentially fixable.
Uses of `SourceFile::cnum` can be updated to check for the presence of `CrateMetadata` (there are just 2 or 3 of them), and the encoding/decoding logic can be rewritten.
I just won't have time to do all this in the next couple of weeks.

There may be other issues though.
Any attempts to re-land the more radical version of crate unloading, resetting crate metadatas to `None`, will need to go through crater.

File: compiler/rustc_middle/src/query/mod.rs [hunk 1]
```diff
@@ -1872,6 +1872,13 @@ rustc_queries! {
         eval_always
         desc { "fetching all foreign CrateNum instances" }
     }
+    // Crates that are loaded non-speculatively (not for diagnostics or doc links).
+    // FIXME: This is currently only used for collecting lang items, but should be used instead of
+    // `crates` in most other cases too.
+    query used_crates(_: ()) -> &'tcx [CrateNum] {
+        eval_always
+        desc { "fetching `CrateNum`s for all crates loaded non-speculatively" }
+    }
```
Comment (cjgillot) [inline compiler/rustc_middle/src/query/mod.rs:1881]: Should we directly change the implementation of `crates`?

Comment (petrochenkov) [reply compiler/rustc_middle/src/query/mod.rs:1881]: In some cases the new version should not be used (e.g. in metadata encoding due to https://github.com/rust-lang/rust/pull/121167#issuecomment-1947413815), but I didn't audit in which exactly and switched only one case that is necessary for https://github.com/rust-lang/rust/pull/117772.

File: compiler/rustc_middle/src/query/mod.rs [hunk 2]
```diff
@@ -1872,6 +1872,13 @@ rustc_queries! {
         eval_always
         desc { "fetching all foreign CrateNum instances" }
     }
+    // Crates that are loaded non-speculatively (not for diagnostics or doc links).
+    // FIXME: This is currently only used for collecting lang items, but should be used instead of
+    // `crates` in most other cases too.
```
Comment (wesleywiser) [inline compiler/rustc_middle/src/query/mod.rs:1877]: Can we describe what situations would require using `crates` instead or is there not a common theme?

**Review by wesleywiser — APPROVED** [review]

File: compiler/rustc_middle/src/query/mod.rs (hunk 2 above)
Comment (petrochenkov) [reply compiler/rustc_middle/src/query/mod.rs:1877]: Metadata encoding at least, if the second item in https://github.com/rust-lang/rust/pull/121167#issuecomment-1947413815 is not fixed.
If metadata includes unused crates, then SVH and binary depinfo should probably include them either.

Any diagnostic logic, like `trimmed_def_paths` may include them as well, because why not.

**Review by wesleywiser — APPROVED** [review]

**Comment by wesleywiser** [comment]
Thanks for the quick fix @petrochenkov!

@bors r+
