### PR TITLE
Fix lifetime rules for 'if' conditions

### LINKED ISSUE #12033: tweak temporary lifetime rules for `if` and `while` conditions
I think that `if` and `while` conditions should free any temporaries that occur within them (for `while` conditions it's mandatory, actually, since the condition is evaluated many times).

That is, if I write:

    if my_set().borrow().contains(&key) { ... }

the temporary returned by `borrow()` should be freed once the condition is evaluated, before entering the body of the `if`.

The same holds for `whiles`.

What makes these expressions different from other compound forms is that the conditions are evaluated to scalar booleans, and hence can never create lasting aliases that might need to be preserved.

In the case of a while, this is needed because temporaries can never outlive conditional or repeated scopes, and the condition of a while is a repeated scope.

### PR DESCRIPTION
**Pull request by KiChjang**
Fixes #12033.

Changes the temporary scope rules to make the condition of an if-then-else a terminating scope. This is a [breaking-change].

### CODE REVIEW

File: src/test/run-pass/issue-12033.rs [hunk 1]
```diff
@@ -0,0 +1,21 @@
...
+// file at the top-level directory of this distribution and at
+// http://rust-lang.org/COPYRIGHT.
+//
+// Licensed under the Apache License, Version 2.0 <LICENSE-APACHE or
+// http://www.apache.org/licenses/LICENSE-2.0> or the MIT license
+// <LICENSE-MIT or http://opensource.org/licenses/MIT>, at your
+// option. This file may not be copied, modified, or distributed
+// except according to those terms.
+
+// Test an example where we fail to infer the type parameter H. This
```
Comment (rkruppe) [inline src/test/run-pass/issue-12033.rs]: This doesn't seem to belong here.

**Comment by nagisa** [comment]
The issue title refers to fixing both `if` and `while` but there seem to be no changes or tests pertaining to the `while` expression. Is it intentional?

**Comment by KiChjang** [comment]
Whoops, I made a couple of stupids, now it should look fine. Not sure if it _behaves_ fine though.

**Comment by eddyb** [comment]
To explain how this can be a breaking-change, we can look at the `RefCell`-based examples: with `if-else`, temporaries in the conditions can live longer than variables above the `if-else`, whereas with just `if`, the "terminating" aspect means that temporaries live shorter than the variables they borrow from.

The opposite can be produced by having a local variable borrow the temporary instead:
```rust
struct Foo;

impl Foo {
    fn save<'a>(&'a self, dest: &mut &'a Foo) -> bool {
        *dest = self;
        true
    }
}

fn main() {
    let mut dest = &Foo;
    if Foo.save(&mut dest) {} else {}
}
```

This example compiles before this PR, but not if we remove `else {}`. With this PR, the `if-else` case behaves like the `if` case, so neither will compile, the temporary being to short to be borrowed by `dest`.
