### PR TITLE
trans: Call `fmod` manually for 32-bit float rem

### LINKED ISSUE #27859: f32 "%" is broken on MSVC
```rust
fn main() {
  println!("{}", 1.5f32 % std::env::args().len() as f32);
}
```

This code doesn't link on MSVC targets.  (Sorry if I messed up the testcase; I don't have a Rust install on Windows to test with.)

### PR DESCRIPTION
**Pull request by alexcrichton**
Currently `f32 % f32` will generate a link error on 32-bit MSVC because LLVM
will lower the operation to a call to the nonexistent function `fmodf`. Work
around in this in the backend by lowering to a call to `fmod` instead with
necessary extension/truncation between floats/doubles.

Closes #27859

### CODE REVIEW

**Comment by alexcrichton** [comment]
r? @nrc 

This makes me a little sad, but I was unable to think of a cleaner way to do this :(

**Comment by huonw** [comment]
I wonder if we can just remove this branch? Theoretically the trait implementation itself should work fine... right? (At least, it seems it wouldn't be backwards incompatible to rely on the trait, based on https://github.com/rust-lang/rust/issues/27824#issuecomment-130904432)

**Comment by alexcrichton** [comment]
Unfortunately we do actually hit this branch, even though there's a trait implementation in scope. For example this code:

```rust
pub fn foo(a: f32, b: f32) -> f32 { a % b }
```

generates this IR at O0

```ir
define float @_ZN3foo20hc71bdc578cf276aaeaaE(float, float) unnamed_addr #0 {
entry-block:
  %dropflag_hint_6 = alloca i8
  %dropflag_hint_9 = alloca i8
  %a = alloca float
  %b = alloca float
  store i8 61, i8* %dropflag_hint_6
  store i8 61, i8* %dropflag_hint_9
  store float %0, float* %a, align 4
  store float %1, float* %b, align 4
  %2 = load float, float* %a, align 4
  %3 = load float, float* %b, align 4
  %4 = frem float %2, %3
  ret float %4
}
```

File: src/librustc_trans/trans/expr.rs [hunk 1]
```diff
@@ -1767,7 +1768,37 @@ fn trans_eager_binop<'blk, 'tcx>(bcx: Block<'blk, 'tcx>,
...
+            // to a call to `fmodf`, so to work around this we special case
+            // 32-bit MSVC 32-bit float rem instructions and instead do the call
+            // out to `fmod` ourselves.
+            //
+            // Note that this is currently duplicated with src/libcore/ops.rs
+            // which does the same thing, and it would be nice to perhaps unify
+            // these two implementations on day!
+            let use_trait = tcx.sess.target.target.options.is_like_msvc &&
+                            tcx.sess.target.target.arch == "x86" &&
+                            lhs_t == tcx.types.f32;
```
Comment (eefriedman) [inline src/librustc_trans/trans/expr.rs]: You can't make this conditional on the operand type: you'll run into trouble in optimized builds if someone writes:

```rust
#![crate_type="lib"]
pub fn foo(a: f32, b: f32) -> f32 {
    (a as f64 % b as f64) as f32
}
```

File: src/librustc_trans/trans/expr.rs [hunk 2]
```diff
@@ -1767,7 +1768,37 @@ fn trans_eager_binop<'blk, 'tcx>(bcx: Block<'blk, 'tcx>,
...
+            //
+            // Although LLVM knows that `fmodf` doesn't exist on MSVC, it will
+            // still unconditionally lower frem instructions over 32-bit floats
+            // to a call to `fmodf`, so to work around this we special case
+            // 32-bit MSVC 32-bit float rem instructions and instead do the call
+            // out to `fmod` ourselves.
+            //
+            // Note that this is currently duplicated with src/libcore/ops.rs
+            // which does the same thing, and it would be nice to perhaps unify
+            // these two implementations on day!
```
Comment (eefriedman) [inline src/librustc_trans/trans/expr.rs]: *one.

File: src/librustc_trans/trans/expr.rs (hunk 1 above)
Comment (alexcrichton) [inline src/librustc_trans/trans/expr.rs]: I believe `lhs_t` is the true type of the operation (e.g. with all types resolved), for example when I run this function through this patch on 32-bit Windows it generates a `frem` call with 64-bit doubles.

Comment (eefriedman) [inline src/librustc_trans/trans/expr.rs]: This is with optimization turned on?  (The problem is that instcombine narrows frem instructions.)

Comment (alexcrichton) [inline src/librustc_trans/trans/expr.rs]: Ah right of course, I'll have to poke around and see if I can't get something to work.

**Comment by alexcrichton** [comment]
Well it looks like @eefriedman's right and LLVM is too smart for it's own good, I'm not sure how to subvert its logic to get it to not generate frem instructions, so closing for now.

**Comment by eefriedman** [comment]
Well, you could change code generation so it *never* generates `frem`.  LLVM won't convert explicit calls to `fmod()` into an `frem` instruction.

**Comment by alexcrichton** [comment]
That does indeed seem to work! (pushed)

**Comment by dylanmckay** [comment]
I've just made a patch for LLVM which causes `f32` modulus operations to be promoted to `f64` modulus operations, but only on 32-bit MSVC. I am currently in the process of testing and upstreaming it.

**Comment by alexcrichton** [comment]
Awesome, thanks @dylanmckay! If that lands I'll see about updating possibly updating LLVM or I'll add a note here saying that this branch should be removed once upstream LLVM has been updated.

**Comment by dylanmckay** [comment]
No problem @alexcrichton!

With regards to updating LLVM - I am happy to do that. My AVR [fork](https://github.com/avr-rust/rust) of Rust is easiest to update right after an LLVM upgrade :)

**Comment by dylanmckay** [comment]
This was fixed upstream in [r246615](http://reviews.llvm.org/rL246615)
