### PR TITLE
Catch stray `{` in let-chains

### LINKED ISSUE #117766: let-chains parsing is not resilient to stray `{` between `let`s
### Code

```Rust
#![feature(let_chains)]
fn main() {
    if let () = ()
        && let () = () {
        && let () = ()
    {
    }
}
```

### Current output

```Shell
error: this file contains an unclosed delimiter
 --> src/main.rs:8:2
  |
2 | fn main() {
  |           - unclosed delimiter
3 |     if let () = ()
4 |         && let () = () {
  |                        - this delimiter might not be properly closed...
...
8 | }
  | -^
  | |
  | ...as it matches this but it has different indentation
```

### Desired output

```Shell
error: this file contains an unclosed delimiter
 --> src/main.rs:8:2
  |
2 | fn main() {
  |           - unclosed delimiter
3 |     if let () = ()
4 |         && let () = () {
  |                        - this delimiter might not be properly closed...
5 |         && let () = ()
  |         -------------- you likely meant to continue the let-chain
...
8 | }
  | -^
  | |
  | ...as it matches this but it has different indentation
help: remove the spurious block start
  |
4 -         && let () = () {
4 +         && let () = ()
  |
```

### Rationale and extra context

Unmatched delimiters are hard to deal with by taking consideration of surrounding code because they actually occur during lexing. Still, it'd be nice if we detected some common sources of issues like this one.

### Other cases

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by sjwang05**
Fixes #117766

### CODE REVIEW

File: compiler/rustc_parse/src/lexer/tokentrees.rs [hunk 1]
```diff
@@ -121,9 +122,44 @@ impl<'a> TokenTreesReader<'a> {
...
+                            parser.token.span,
+                            "consider removing this brace to parse the `let` as part of the same chain",
+                            "", Applicability::MachineApplicable
+                        );
+                        err.span_note(
+                            maybe_andand.span.to(maybe_let.span),
+                            "you might have meant to continue the let-chain here",
+                        );
+                        errs.push(err);
+                    }
```
Comment (estebank) [inline compiler/rustc_parse/src/lexer/tokentrees.rs:162]: Let's move this logic to a separate method to make it less difficult to read the happy path. Either the new logic or the whole parser loop.

File: compiler/rustc_parse/src/lexer/tokentrees.rs [hunk 2]
```diff
@@ -121,9 +122,44 @@ impl<'a> TokenTreesReader<'a> {
...
+                        let mut err = parser.struct_span_err(
+                            parser.token.span,
+                            "found a `{` in the middle of a let-chain",
+                        );
+                        err.span_suggestion(
+                            parser.token.span,
+                            "consider removing this brace to parse the `let` as part of the same chain",
+                            "", Applicability::MachineApplicable
+                        );
+                        err.span_note(
```
Comment (estebank) [inline compiler/rustc_parse/src/lexer/tokentrees.rs:157]:
```suggestion
                        err.span_label(
```

**Review by estebank — APPROVED** [review]
The approach is quite smart! Thank you for taking this on.

File: tests/ui/parser/brace-in-let-chain.stderr [hunk 3]
```diff
@@ -0,0 +1,71 @@
...
+LL | fn baz() {
+   |          - unclosed delimiter
+LL |     if false {
+LL |         {
+   |         - this delimiter might not be properly closed...
+LL |             && let () = ()
+LL |     }
+   |     - ...as it matches this but it has different indentation
+LL | }
+   |                                                      ^
```
Comment (estebank) [inline tests/ui/parser/brace-in-let-chain.stderr:34]: I'm trying to decide if it's better in general to silence this error (like we do for diff markers) or not is best for these cases... I would leave it as is for now, because I don't know if I can come up with a case where doing so would be detrimental, but suspect we can silence it.

**Comment by sjwang05** [comment]
Thanks for the feedback! I've moved all error handling logic into its separate method and replaced the `note` with a `label` as suggested.

> I'm trying to decide if it's better in general to silence this error (like we do for diff markers) or not is best for these cases

I just tried doing that, and strangely enough, all "found a `{` in the middle of a let-chain" errors except the first get silenced as well:
```
error: found a `{` in the middle of a let-chain
  --> $DIR/brace-in-let-chain.rs:6:24
   |
LL |         && let () = () {
   |                        ^
LL |         && let () = ()
   |         ------ you might have meant to continue the let-chain here
   |
help: consider removing this brace to parse the `let` as part of the same chain
   |
LL -         && let () = () {
LL +         && let () = ()
   |

error: aborting due to previous error
```
We should be getting 2 errors here, but we're only getting one 😕.

FWIW, here's what the silenced stderr would probably look like if I manage to get that problem sorted out:
```
error: found a `{` in the middle of a let-chain
  --> $DIR/brace-in-let-chain.rs:14:24
   |
LL |         && let () = () {
   |                        ^
LL |         && let () = ()
   |         ------ you might have meant to continue the let-chain here
   |
help: consider removing this brace to parse the `let` as part of the same chain
   |
LL -         && let () = () {
LL +         && let () = ()
   |

error: found a `{` in the middle of a let-chain
  --> $DIR/brace-in-let-chain.rs:6:24
   |
LL |         && let () = () {
   |                        ^
LL |         && let () = ()
   |         ------ you might have meant to continue the let-chain here
   |
help: consider removing this brace to parse the `let` as part of the same chain
   |
LL -         && let () = () {
LL +         && let () = ()
   |

error: aborting due to 2 previous errors
```
Though I feel like it's definitely easier to read, the unclosed delimiter errors aren't necessarily _wrong_ like they could be with diff markers, so silencing them might not be as helpful. The ideal solution is probably be something like the stderr you suggested in the original issue, where the label is printed inline with the unclosed delim error, though I have no clue how I'd go about doing that--the only way I can think of is modifying the errors in `report_suspicious_mismatch_block`, which would require somehow pairing up each erroneous let-chain with the correct `{`.

**Review by TaKO8Ki — COMMENTED** [review]
Thank you for the great work! I left one suggestion.

File: compiler/rustc_parse/src/parser/mod.rs [hunk 4]
```diff
@@ -1115,7 +1115,7 @@ impl<'a> Parser<'a> {
     }
 
     /// Returns whether any of the given keywords are `dist` tokens ahead of the current one.
-    fn is_keyword_ahead(&self, dist: usize, kws: &[Symbol]) -> bool {
+    pub fn is_keyword_ahead(&self, dist: usize, kws: &[Symbol]) -> bool {
```
[the remark this answers is not in the document]
Comment (sjwang05) [reply compiler/rustc_parse/src/parser/mod.rs]: Fixed, thanks!
