### PR TITLE
Short-cut `T: Sized` trait selection for ADTs

### LINKED ISSUE #32963: The trait object Foo+Copy implements the trait Copy
`select` considers the trait object type `Foo+Copy` to implement the trait `Copy`, and therefore its supertraits `Clone` and `Sized`. This is totally bogus, as the trait object type is *not* Sized.

For example:
```Rust
use std::{fmt, mem};

fn size_of_copy<T: Copy+?Sized>() -> usize { mem::size_of::<T>() }

fn main() {
    println!("{}", size_of_copy::<fmt::Debug+Copy>());
}
```

This obviously should not compile, but it does (and prints 16, because of the `size_of` unsized hack).

### LINKED ISSUE #33201: error: the trait `core::marker::Sized` is not implemented for the type `std::error::Error + Sized + 'static`
The error is not easy to understand for this code:

```rust
use std::error::Error;
use std::fmt;

#[derive(Debug, Clone)]
struct SomeError {
  cause: String
}

impl fmt::Display for SomeError {
  fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
    write!(f, "SomeError")
  }
}

impl Error for SomeError {
  fn description(&self) -> &str {
    "Some Error"
  }
  
  fn cause(&self) -> Option<&Error> {
    None
  }
}

#[derive(Debug, Clone)]
enum NewError {
  SomeCause(Error + Sized)
}

fn main() {
    let error = NewError::SomeCause(SomeError { cause: "some cause".to_string() });
    println!("{:?}", error);
}
```

(it's also in https://play.rust-lang.org/?gist=3d607f7ee08c09aa7eed9720712ee129&version=stable&backtrace=0)

If I understand properly, the issue is that I should have something like this instead:
```rust
enum NewError<T: Error> {
  SomeCause(T)
}
```
But the error is very misleading.

### PR DESCRIPTION
**Pull request by arielb1**
Basically avoids all nested obligations when checking whether an ADT is sized - this speeds up typeck by ~15%

The refactoring fixed #32963, but I also want to make `Copy` not object-safe (will commit that soon).

Fixes #33201

r? @nikomatsakis

### CODE REVIEW

File: src/librustc/traits/select.rs [hunk 1]
```diff
@@ -2100,18 +2091,18 @@ impl<'cx, 'tcx> SelectionContext<'cx, 'tcx> {
...
-            If(nested) => Ok(self.vtable_builtin_data(obligation, bound, nested)),
-            AmbiguousBuiltin | ParameterBuiltin => {
+        match self.builtin_bound(bound, obligation) {
+            BuiltinImplConditions::Where(nested) =>
+                self.vtable_builtin_data(obligation, bound, nested),
+            _ => {
                 span_bug!(
                     obligation.cause.span,
-                    "builtin bound for {:?} was ambig",
+                    "confiriming builtin impl for {:?} where none exists",
```
Comment (jonas-schievink) [inline src/librustc/traits/select.rs]: nit: `s/confiriming/confirming/`

**Comment by arielb1** [comment]
I rationalized the WF behaviour for tuples - this needs a crater run.

**Comment by nikomatsakis** [comment]
crater run launched

**Comment by nikomatsakis** [comment]
Crater run failed because building this branch failed: https://tools.taskcluster.net/task-inspector/#eqYUkXetSja7miFf4nXmeQ/0

File: src/librustc/ty/mod.rs [hunk 2]
```diff
@@ -1726,6 +1728,190 @@ impl<'tcx, 'container> AdtDefData<'tcx, 'container> {
...
+    ///
+    /// In fact, there are only a few options for the constraint:
+    ///     - `bool`, if the type is always Sized
+    ///     - an obviously-unsized type
+    ///     - a type parameter or projection whose Sizedness can't be known
+    ///     - a tuple of type parameters or projections, if there are multiple
+    ///       such.
+    ///     - a TyError, if a type contained itself. The representability
+    ///       check should catch this case.
+    fn calculate_sized_constraint_inner(&'tcx self, tcx: &ty::TyCtxt<'tcx>,
```
Comment (nikomatsakis) [inline src/librustc/ty/mod.rs]: Total nit: I personally prefer the "main method" to be listed first, and the auxiliary helper methods to be listed below it. I find it easier to read (and indeed I was confused reading this patch for a bit, since the "flow" of code was interrupted by helper fns.) But feel free to ignore me if you would rather keep the current ordering.

File: src/librustc/ty/mod.rs [hunk 3]
```diff
@@ -1726,6 +1728,190 @@ impl<'tcx, 'container> AdtDefData<'tcx, 'container> {
...
+
+        let dep_node = DepNode::SizedConstraint(self.did);
+
+        if self.sized_constraint.get(dep_node).is_some() {
+            return;
+        }
+
+        if stack.contains(&self) {
+            debug!("calculate_sized_constraint: {:?} is recursive", self);
+            self.sized_constraint.fulfill(dep_node, tcx.types.err);
```
Comment (nikomatsakis) [inline src/librustc/ty/mod.rs]: I feel mildly nervous to return `err` here when, in fact, no error has been reported. This has gotten us into some trouble before. I think this case is different, though, in that this is kind of a special function, and this type maybe doesn't escape into "general use" -- certainly it's somewhat reasonable to impose on the callers that they should report an error or handle `err` carefully. 

Another possible concern is that we may get false error reports -- perhaps the final type in the struct is actually `ty::err`? In that case, the return type would indicate recursion, potentially generating a false error report -- somewhat ironically, since `ty::err` is supposed to *suppress* error reports.

I guess what I'm getting as: maybe better to return `Result<Ty, Recursive>` (where `struct Recursive;`) instead of just `Ty` (or else `Option<Ty>`, as you prefer).

File: src/librustc/ty/mod.rs [hunk 4]
```diff
@@ -1726,6 +1728,190 @@ impl<'tcx, 'container> AdtDefData<'tcx, 'container> {
...
+        &'tcx self,
+        tcx: &ty::TyCtxt<'tcx>,
+        stack: &mut Vec<AdtDefMaster<'tcx>>,
+        ty: Ty<'tcx>
+    ) -> Ty<'tcx> {
+        let result = match ty.sty {
+            TyBool | TyChar | TyInt(..) | TyUint(..) | TyFloat(..) |
+            TyBox(..) | TyRawPtr(..) | TyRef(..) | TyFnDef(..) | TyFnPtr(_) |
+            TyArray(..) | TyClosure(..) => {
+                // these are always sized - return a primitive
```
Comment (nikomatsakis) [inline src/librustc/ty/mod.rs]: I assume part of the logic here is that, by always returning the *same* primitive, we help with caching, right? I think it's worth noting that explicitly in a comment.

File: src/test/run-pass/issue-31299.rs [hunk 5]
```diff
@@ -0,0 +1,36 @@
...
+// http://www.apache.org/licenses/LICENSE-2.0> or the MIT license
+// <LICENSE-MIT or http://opensource.org/licenses/MIT>, at your
+// option. This file may not be copied, modified, or distributed
+// except according to those terms.
+
+// Regression test for #31299. This was generating an overflow error
+// because of eager normalization:
+//
+// proving `M: Sized` requires
+// - proving `PtrBack<Vec<M>>: Sized` requis
```
Comment (nikomatsakis) [inline src/test/run-pass/issue-31299.rs]: Typo: s/requis/requires/

File: src/test/run-pass/issue-31299.rs [hunk 6]
```diff
@@ -0,0 +1,36 @@
...
+//   - normalizing `Vec<<Vec<M> as Front>::Back>>: Sized` requires
+//     - proving `Vec<M>: Front` requires
+//       - `M: Sized` <-- cycle!
+//
+// If we skip the normalization step, though, everything goes fine.
```
Comment (nikomatsakis) [inline src/test/run-pass/issue-31299.rs]: I would add to this comment to say:

"One fix would be lazy normalization. At the moment, we do still eagerly normalize, but we still skip the normalization step because, in PR #33138, we only consider the last field of `Vec`, which is a `usize`."

**Comment by nikomatsakis** [comment]
@arielb1 this is a beautiful patch.

I would r+ it, except that I think it violates my [proposed stability policy](https://gist.github.com/nikomatsakis/1268ef0457a376d8fc24bf55aa7fc15b). I think we ought to be making an effort to either issue warnings or *at least* issue targeted errors regarding the new changes. Moreover, this seems to be a case where we could readily do so.

I am happy to write up the "breaking change issue description" if you like.

In any case, you should fix the branch so we can do a crater run and test things.

File: src/librustc/ty/mod.rs (hunk 2 above)
Comment (arielb1) [inline src/librustc/ty/mod.rs]: I just rewrote this code about half-a-dozen times.

File: src/librustc/ty/mod.rs (hunk 3 above)
Comment (arielb1) [inline src/librustc/ty/mod.rs]: In this case, an error is reported (by `is_representable`), and the `TyErr` is treated as a Sized type for the rest of compilation.

File: src/librustc/ty/mod.rs (hunk 4 above)
Comment (arielb1) [inline src/librustc/ty/mod.rs]: No. We have special-casing for `bool` to avoid registering nested obligations. I guess this function should return something other than `Ty`.

**Comment by arielb1** [comment]
@nikomatsakis 

Are you talking about the tuple: Sized issue? I don't feel like introducing RFC1214 obligations again.

File: src/librustc/ty/mod.rs (hunk 3 above)
Comment (nikomatsakis) [inline src/librustc/ty/mod.rs]: @arielb1 

> In this case, an error is reported (by is_representable)

We've definitely had problems before where one piece of the code returns ty-err on the assumption that some later bit of code will report an error, but those two pieces are overly disconnected. Not clear if that's likely to happen here. Returning a boolean is an interesting thought: would definitely merit a comment. Why *not* return an `Option`? Just kind of annoying to thread around?

**Comment by nikomatsakis** [comment]
@arielb1 I am talking about the `Copy` and `Sized` trait object-safety change but also the `tuple: Sized` issue, yeah. It seems like we have a specific obligation cause for "tuple-sized" requirements -- we should be able to just issue a warning in that case, no?

**Comment by nikomatsakis** [comment]
Failing that, we could issue an error, but at least direct people to some place that explains the fix. That may be sufficient, and doesn't require as much precision, since it's ok to direct people unnecessarily.

**Comment by nikomatsakis** [comment]
(I'd like to see the crater impact; if it is zero or very minimal, issuing an error and trying to direct people is probably adequate.)

**Comment by arielb1** [comment]
@nikomatsakis 

Reporting a warning would put us in caching hell. I will improve the error message.

**Comment by nikomatsakis** [comment]
@arielb1 ok, but let's get the crater run going too.

**Comment by arielb1** [comment]
@nikomatsakis 

Done.

**Comment by nikomatsakis** [comment]
@arielb1 crater run started

File: src/librustc/ty/mod.rs (hunk 3 above)
Comment (arielb1) [inline src/librustc/ty/mod.rs]: What should I do with the Option?

**Comment by nikomatsakis** [comment]
Crater run results: https://gist.github.com/nikomatsakis/abb0ed492d3cb785af858b87ad3b95fd

-   4668 crates tested: 3047 working / 1528 broken / **35 regressed / 2 fixed** / 56 unknown.

I've not investigated these at all.

**Comment by jonas-schievink** [comment]
* `shapir` is using `Box<Error + Sized>`
* All other root regressions are due to trait methods returning `Self` in a tuple without a `Self: Sized` bound (I think)

**Comment by nikomatsakis** [comment]
Tricky. It seems like we can pull that change to tuples out into a distinct PR, and introduce as a warning first -- it may be that we can write some a kind of "warning post-pass" that checks all tuples types that occur in trait methods and issues warnings. This wouldn't cover *all* possible cases, but hopefully it would hit those that occur in practice (I think they are mostly tied to default methods?). Breaking 34 crates without a warning period seems ungood.

cc @rust-lang/core

**Comment by arielb1** [comment]
The problem is that allowing tuples with unsized elements to be sized is too much of a footgun.

**Comment by bluss** [comment]
@nikomatsakis Well fixing rayon cleans up a majority of that list, so it's not so bad. ndarray has been fixed with 0.5.1.

File: src/librustc/traits/error_reporting.rs [hunk 7]
```diff
@@ -75,31 +89,44 @@ fn report_fulfillment_error<'a, 'tcx>(infcx: &InferCtxt<'a, 'tcx>,
...
         }
         FulfillmentErrorCode::CodeProjectionError(ref e) => {
-            report_projection_error(infcx, &error.obligation, e);
+            report_projection_error(infcx, &error.obligation, e, warning_node_id);
         }
         FulfillmentErrorCode::CodeAmbiguity => {
-            maybe_report_ambiguity(infcx, &error.obligation);
+            if let None = warning_node_id {
+                maybe_report_ambiguity(infcx, &error.obligation);
+            }
```
Comment (nikomatsakis) [inline src/librustc/traits/error_reporting.rs]: Why do we not report ambiguities if we have a warning node-id?

File: src/librustc/traits/error_reporting.rs [hunk 8]
```diff
@@ -461,6 +500,7 @@ pub fn report_selection_error<'a, 'tcx>(infcx: &InferCtxt<'a, 'tcx>,
                     }
 
                     ty::Predicate::RegionOutlives(ref predicate) => {
+                        if warning_node_id.is_some() { return }
```
Comment (nikomatsakis) [inline src/librustc/traits/error_reporting.rs]: Similarly, it's not obvious to me why we ignore these cases.

File: src/librustc/traits/error_reporting.rs [hunk 9]
```diff
@@ -544,68 +597,84 @@ pub fn report_selection_error<'a, 'tcx>(infcx: &InferCtxt<'a, 'tcx>,
...
+                tcx.sess.add_lint(
+                    ::lint::builtin::OBJECT_UNSAFE_FRAGMENT,
+                    node_id,
                     span,
-                    &format!("method `{}` has generic type parameters",
-                             method.name));
+                    note.to_string());
             }
+            (None, &mut Some(ref mut err)) => {
+                err.fileline_note(span, note);
```
Comment (nikomatsakis) [inline src/librustc/traits/error_reporting.rs]: Now that https://github.com/rust-lang/rust/pull/32756 has landed, we'll want to change these to just calls to `err.note`

**Comment by nikomatsakis** [comment]
This looks good to me. Obviously it needs a rebase before it can land, and I'm curious about the answers to my questions above. Otherwise, the main thing is that I'd like to make a dedicated "migration issue" for these changes. I'll try to whip one up shortly (I'm about to head into the office, so I can do it then).

**Comment by arielb1** [comment]
@nikomatsakis 

I did not want to implement the logic for issuing warnings in these circumstances, given that I don't expect them to be easily reachable. I also don't want to ICE, so I just ignore these cases.

**Comment by arielb1** [comment]
rebased

File: src/librustc_lint/lib.rs [hunk 10]
```diff
@@ -190,6 +190,10 @@ pub fn register_builtins(store: &mut lint::LintStore, sess: Option<&Session>) {
             id: LintId::of(ILLEGAL_STRUCT_OR_ENUM_CONSTANT_PATTERN),
             reference: "RFC 1445 <https://github.com/rust-lang/rfcs/pull/1445>",
         },
+        FutureIncompatibleInfo {
+            id: LintId::of(UNSIZED_IN_TUPLE),
+            reference: "RFC PR 1592 <https://github.com/rust-lang/rfcs/pull/1592>",
+        }
```
Comment (nikomatsakis) [inline src/librustc_lint/lib.rs]: Should we add info for `OBJECT_UNSAFE_FRAGMENT` too?

Also, can you point this at the summary issue that I see you are drafting? (https://github.com/rust-lang/rust/issues/33242)
