### PR TITLE
std: fix `SplitPaths` regression

### LINKED ISSUE #146045: env::split_paths regression in nightly-2025-08-31
This code used to compile in previous stable releases and nightlies prior to nightly-2025-08-31. After https://github.com/rust-lang/rust/pull/145242, it no longer compiles, which seems unintended.

```rust
pub fn repro() -> Option<std::path::PathBuf> {
    let unparsed = std::ffi::OsString::new();
    std::env::split_paths(&unparsed).next()
}
```

`rustc --crate-type=lib --edition=2021 --target=x86_64-unknown-linux-gnu repro.rs`

```console
error[E0597]: `unparsed` does not live long enough
 --> repro.rs:3:27
  |
2 |     let unparsed = std::ffi::OsString::new();
  |         -------- binding `unparsed` declared here
3 |     std::env::split_paths(&unparsed).next()
  |     ----------------------^^^^^^^^^-
  |     |                     |
  |     |                     borrowed value does not live long enough
  |     a temporary with access to the borrow is created here ...
4 | }
  | -
  | |
  | `unparsed` dropped here while still borrowed
  | ... and the borrow might be used here, when that temporary is dropped and runs the destructor for type `SplitPaths<'_>`
  |
  = note: the temporary is part of an expression at the end of a block;
          consider forcing this temporary to be dropped sooner, before the block's local variables are dropped
help: for example, you could save the expression's value in a new local variable `x` and then make `x` be the expression at the end of the block
  |
3 |     let x = std::env::split_paths(&unparsed).next(); x
  |     +++++++                                        +++
```

The regression only occurs if building for **both** a unix target platforms **and** an edition older than 2024. It does not reproduce in non-unix platforms (`--target=x86_64-pc-windows-mscv`) nor 2024 edition (`--edition=2024`).

@joboet

### PR DESCRIPTION
**Pull request by joboet**
Fixes rust-lang/rust#146045 by defining the TAIT more precisely, ensuring that `'a` does not need to be live on drop.

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
r=me

File: library/std/src/sys/pal/unix/os.rs [hunk 1]
```diff
@@ -186,14 +186,24 @@ pub fn chdir(p: &path::Path) -> io::Result<()> {
     if result == 0 { Ok(()) } else { Err(io::Error::last_os_error()) }
 }
 
-pub type SplitPaths<'a> = impl Iterator<Item = PathBuf>;
+// This can't just be `impl Iterator` because that requires `'a` to be live on
+// drop (see #146045).
+pub type SplitPaths<'a> = iter::Map<
+    slice::Split<'a, u8, impl FnMut(&u8) -> bool + 'static>,
+    impl FnMut(&[u8]) -> PathBuf + 'static,
+>;
```
Comment (tgross35) [inline library/std/src/sys/pal/unix/os.rs:194]: Any reason not to wrap this in a struct, to match the existing stable `struct SplitPaths`? This technically exposes the inner workings a bit.

Comment (joboet) [reply library/std/src/sys/pal/unix/os.rs:194]: That would require implementing `Iterator` here, which I was trying to avoid in #145242. Note that this type alias is wrapped in the public `SplitPaths` `struct` rather than being exposed directly.

Comment (tgross35) [reply library/std/src/sys/pal/unix/os.rs:194]: Ah right, I was thinking this was the user-public `SplitPaths`. Makes sense.

**Review by dtolnay — APPROVED** [review]
