### PR TITLE
emit `.att_syntax` when global/naked asm use that option

### LINKED ISSUE #143542: `options(att_syntax)` doesn't do anything for `global_asm!` and `naked_asm!`
Edit(trevor): this doesn't need `compiler_builtins` to repro https://github.com/rust-lang/rust/issues/143542#issuecomment-3045848149

I tried this code:

```rust
cargo new x
cd x
RUSTFLAGS="--emit=asm -Cllvm-args=-x86-asm-syntax=intel" cargo +nightly build -Zbuild-std
```

I expected to see this happen: A successful build, with Intel-syntax assembly emitted. (as per #48011)

Instead, this happened:

<details><summary>A lot of inline assembly syntax errors</summary>

```
   Compiling compiler_builtins v0.1.160 (~/.local/share/rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/compiler-builtins/compiler-builtins)
   Compiling rustc-std-workspace-core v1.99.0 (~/.local/share/rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/rustc-std-workspace-core)
   Compiling alloc v0.0.0 (~/.local/share/rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc)
   Compiling panic_abort v0.0.0 (~/.local/share/rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/panic_abort)
   Compiling libc v0.2.174
   Compiling cfg-if v1.0.1
   Compiling memchr v2.7.5
   Compiling adler2 v2.0.1
   Compiling rustc-demangle v0.1.25
error: unknown token in expression
  |
note: instantiated into assembly here
 --> <inline asm>:8:20
  |
8 |             pushq  %rbp
  |                    ^

error: unknown token in expression
   |
note: instantiated into assembly here
  --> <inline asm>:11:20
   |
11 |             movq   %rsp, %rbp
   |                    ^

error: unknown token in expression
   |
note: instantiated into assembly here
  --> <inline asm>:14:20
   |
14 |             mov    %rax,%r11        // duplicate %rax as we're clobbering %r11
   |                    ^

error: unknown token in expression
   |
note: instantiated into assembly here
  --> <inline asm>:30:20
   |
30 |             cmp    $0x1000,%r11
   |                    ^

error: unknown token in expression
   |
note: instantiated into assembly here
  --> <inline asm>:33:20
   |
33 |             sub    $0x1000,%rsp
   |                    ^

error: unknown token in expression
   |
note: instantiated into assembly here
  --> <inline asm>:34:20
   |
34 |             test   %rsp,8(%rsp)
   |                    ^

error: unknown token in expression
   |
note: instantiated into assembly here
  --> <inline asm>:35:20
   |
35 |             sub    $0x1000,%r11
   |                    ^

error: unknown token in expression
   |
note: instantiated into assembly here
  --> <inline asm>:36:20
   |
36 |             cmp    $0x1000,%r11
   |                    ^

error: unknown token in expression
   |
note: instantiated into assembly here
  --> <inline asm>:42:20
   |
42 |             sub    %r11,%rsp
   |                    ^

error: unknown token in expression
   |
note: instantiated into assembly here
  --> <inline asm>:43:20
   |
43 |             test   %rsp,8(%rsp)
   |                    ^

error: unknown token in expression
   |
note: instantiated into assembly here
  --> <inline asm>:48:20
   |
48 |             add    %rax,%rsp
   |                    ^

   Compiling unwind v0.0.0 (~/.local/share/rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/unwind)
error: could not compile `compiler_builtins` (lib) due to 11 previous errors
warning: build failed, waiting for other jobs to finish...
```
</details>

### Meta

`rustc --version --verbose`:
```
rustc 1.90.0-nightly (667787527 2025-07-02)
binary: rustc
commit-hash: 6677875279b560442a07a08d5119b4cd6b3c5593
commit-date: 2025-07-02
host: x86_64-unknown-linux-gnu
release: 1.90.0-nightly
LLVM version: 20.1.7
```

### PR DESCRIPTION
**Pull request by folkertdev**
fixes https://github.com/rust-lang/rust/issues/143542

LLVM would error when using `-Cllvm-args=-x86-asm-syntax=intel` in combination with global/naked assembly with `att_syntax`. It turns out that for LLVM you do in this case need to emit `.att_syntax`.

r? @Amanieu

### CODE REVIEW

File: compiler/rustc_codegen_llvm/src/asm.rs [hunk 1]
```diff
@@ -431,9 +435,8 @@ impl<'tcx> AsmCodegenMethods<'tcx> for CodegenCx<'_, 'tcx> {
                 }
             }
         }
-        if intel_syntax {
-            template_str.push_str("\n.att_syntax\n");
-        }
+
+        // For LLVM we don't need to reset the assembly syntax here.
```
Comment (Amanieu) [inline compiler/rustc_codegen_llvm/src/asm.rs]: Is this correct for cases where we LTO with C code? If LLVM doesn't care then it should be relatively safe to just default back to `.att_syntax` here.

Comment (folkertdev) [reply compiler/rustc_codegen_llvm/src/asm.rs]: Sure, let's be a bit defensive here. Fixed.

File: compiler/rustc_codegen_llvm/src/asm.rs [hunk 2]
```diff
@@ -431,7 +435,11 @@ impl<'tcx> AsmCodegenMethods<'tcx> for CodegenCx<'_, 'tcx> {
                 }
             }
         }
-        if intel_syntax {
+
+        // Just to play it safe, reset the assembly syntax to att.
```
Comment (bjorn3) [inline compiler/rustc_codegen_llvm/src/asm.rs]: Wouldn't this cause issues when `-Cllvm-args=-x86-asm-syntax=intel` is used? LLVM might still be trying to emit intel syntax asm for functions it compiles.

Comment (Amanieu) [reply compiler/rustc_codegen_llvm/src/asm.rs]: LLVM doesn't emit asm as text, it emits the instructions directly and ignores the syntax. This only potentially affects inline asm in C code which would probably break anyways because most C code expects AT&T syntax for inline asm.

Comment (folkertdev) [reply compiler/rustc_codegen_llvm/src/asm.rs]: Well it works in the test? I believe what is really happening is that every asm block is isolated, given that LLVM parses the assembly anyway.

Comment (bjorn3) [reply compiler/rustc_codegen_llvm/src/asm.rs]: > LLVM doesn't emit asm as text, it emits the instructions directly and ignores the syntax.

I think it would also break `--emit asm` producing valid assembly. Or does LLVM parse the asm blocks and then emit them as strings in the other format again?

> Well it works in the test? I believe what is really happening is that every asm block is isolated, given that LLVM parses the assembly anyway.

LLVM definitively merges global asm blocks (unfortunately). For example assembler macros leak between global asm blocks.

Comment (folkertdev) [reply compiler/rustc_codegen_llvm/src/asm.rs]: The parsing at least seems to happen independently? Anyway this was already what we emitted, and the problem that got reported is that `.att_syntax` just got ignored, which this PR fixes.

File: compiler/rustc_codegen_llvm/src/asm.rs [hunk 3]
```diff
@@ -384,15 +384,19 @@ impl<'tcx> AsmCodegenMethods<'tcx> for CodegenCx<'_, 'tcx> {
...
-        // Default to Intel syntax on x86
-        let intel_syntax = matches!(asm_arch, InlineAsmArch::X86 | InlineAsmArch::X86_64)
-            && !options.contains(InlineAsmOptions::ATT_SYNTAX);
-
         // Build the template string
         let mut template_str = String::new();
-        if intel_syntax {
-            template_str.push_str(".intel_syntax\n");
+
+        // Select the assembly syntax. On non-X86 platforms att is used by default, on X86 we use
```
Comment (Amanieu) [inline compiler/rustc_codegen_llvm/src/asm.rs]: Slight correction to the comment: the name AT&T refers specifically to an x86 asm syntax. There is no such thing as AT&T syntax on non-x86 platforms.

Comment (folkertdev) [reply compiler/rustc_codegen_llvm/src/asm.rs]: Huh, I've always thought of it as intel and "the other one". At least s390x, powerpc, etc seem more inspired by AT&T.

Anyway, I rephrased that comment.

Comment (Amanieu) [reply compiler/rustc_codegen_llvm/src/asm.rs]: Intel syntax is closer to the standard asm syntax on most architectures with the destination register coming first. AT&T syntax is actually based on PDP-11 assembly since that was the original platform for UNIX and the x86 port adapted the existing assembler instead of using the standard syntax.
