### PR TITLE
De-duplicate and improve definition of core::ffi::c_char

### LINKED ISSUE #129945: c_char signedness doesn't match with Clang's default on various no-std and tier 3 targets
As an next step of #122985 ("c_char on AIX should be u8"), I checked all builtin targets' c_char (as of nightly-2024-09-03) using the following script.

<details><summary>check_c_char.sh</summary>

```bash
#!/usr/bin/env bash
set -euo pipefail
IFS=$'\n\t'

export RUSTC="${RUSTC:-rustc}"
CLANG="${CLANG:-clang}"

"${RUSTC}" -vV >&2
echo >&2
"${CLANG}" --version >&2
echo >&2

cargo new --lib tmp
cd tmp

failed=''
for target_spec in $("${RUSTC}" -Z unstable-options --print all-target-specs-json | jq -c '. | to_entries[]'); do
    eval "$(jq -r '@sh "RUST_TARGET=\(.key) LLVM_TARGET=\(.value."llvm-target")"' <<<"${target_spec}")"
    clang_defs=$("${CLANG}" -E -dM -x c /dev/null -target "${LLVM_TARGET}")
    clang_c_char=i8
    if grep -Fq '__CHAR_UNSIGNED__ 1' <<<"${clang_defs}"; then
        clang_c_char=u8
    fi
    cat >src/lib.rs <<EOF
#![no_std]
const _C: core::ffi::c_char = 0_${clang_c_char};
EOF
    if { cargo check -Z build-std=core --target "${RUST_TARGET}" -q 2>&1 || :; } | grep -Fq 'error[E0308]'; then
        echo "${RUST_TARGET}: should be ${clang_c_char}"
        failed=1
    fi
done

cd ..
rm -rf tmp

if [[ -n "${failed}" ]]; then
    exit 1
fi
```

</details>

The result (stdout of the script) is:

```
aarch64-kmc-solid_asp3: should be u8
aarch64-unknown-hermit: should be u8
aarch64-unknown-illumos: should be u8
aarch64-unknown-none: should be u8
aarch64-unknown-none-softfloat: should be u8
aarch64-unknown-redox: should be u8
aarch64-unknown-teeos: should be u8
aarch64-unknown-trusty: should be u8
armebv7r-none-eabi: should be u8
armebv7r-none-eabihf: should be u8
armv4t-none-eabi: should be u8
armv5te-none-eabi: should be u8
armv7-sony-vita-newlibeabihf: should be u8
armv7-unknown-trusty: should be u8
armv7a-kmc-solid_asp3-eabi: should be u8
armv7a-kmc-solid_asp3-eabihf: should be u8
armv7a-none-eabi: should be u8
armv7a-none-eabihf: should be u8
armv7r-none-eabi: should be u8
armv7r-none-eabihf: should be u8
armv8r-none-eabihf: should be u8
csky-unknown-linux-gnuabiv2: should be i8
csky-unknown-linux-gnuabiv2hf: should be i8
hexagon-unknown-none-elf: should be u8
riscv32i-unknown-none-elf: should be u8
riscv32im-risc0-zkvm-elf: should be u8
riscv32im-unknown-none-elf: should be u8
riscv32ima-unknown-none-elf: should be u8
riscv32imac-esp-espidf: should be u8
riscv32imac-unknown-none-elf: should be u8
riscv32imac-unknown-nuttx-elf: should be u8
riscv32imac-unknown-xous-elf: should be u8
riscv32imafc-esp-espidf: should be u8
riscv32imafc-unknown-none-elf: should be u8
riscv32imafc-unknown-nuttx-elf: should be u8
riscv32imc-esp-espidf: should be u8
riscv32imc-unknown-none-elf: should be u8
riscv32imc-unknown-nuttx-elf: should be u8
riscv64-linux-android: should be u8
riscv64gc-unknown-hermit: should be u8
riscv64gc-unknown-none-elf: should be u8
riscv64gc-unknown-nuttx-elf: should be u8
riscv64imac-unknown-none-elf: should be u8
riscv64imac-unknown-nuttx-elf: should be u8
thumbv4t-none-eabi: should be u8
thumbv5te-none-eabi: should be u8
thumbv6m-none-eabi: should be u8
thumbv6m-nuttx-eabi: should be u8
thumbv7em-none-eabi: should be u8
thumbv7em-none-eabihf: should be u8
thumbv7em-nuttx-eabi: should be u8
thumbv7em-nuttx-eabihf: should be u8
thumbv7m-none-eabi: should be u8
thumbv7m-nuttx-eabi: should be u8
thumbv8m.base-none-eabi: should be u8
thumbv8m.base-nuttx-eabi: should be u8
thumbv8m.main-none-eabi: should be u8
thumbv8m.main-none-eabihf: should be u8
thumbv8m.main-nuttx-eabi: should be u8
thumbv8m.main-nuttx-eabihf: should be u8
x86_64-unknown-l4re-uclibc: should be i8
```

<details><summary>stderr of the script (version info, etc.)</summary>

```
rustc 1.83.0-nightly (bd53aa3bf 2024-09-02)
binary: rustc
commit-hash: bd53aa3bf7a24a70d763182303bd75e5fc51a9af
commit-date: 2024-09-02
host: aarch64-apple-darwin
release: 1.83.0-nightly
LLVM version: 19.1.0

Homebrew clang version 18.1.8
Target: arm64-apple-darwin23.5.0
Thread model: posix
InstalledDir: /opt/homebrew/opt/llvm/bin

    Creating library `tmp` package
note: see more `Cargo.toml` keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
clang: warning: unknown platform, assuming -mfloat-abi=soft
clang: warning: unknown platform, assuming -mfloat-abi=soft
clang: warning: unknown platform, assuming -mfloat-abi=soft
clang: warning: no target microcontroller specified on command line, cannot link standard libraries, please pass -mmcu=<mcu name> [-Wavr-rtlib-linking-quirks]
error: unknown target triple 'xtensa-none-unknown-elf'
```

</details>

<details><summary>Note about the above script (potential false positive / false negative)</summary>

- Note that targets that broken and cannot build core (such as m68k: https://github.com/rust-lang/rust/issues/89498) are ignored in the above script. (potential false negative)
- The script passes llvm-target field of the target spec as a target for Clang, so if it does not match the Rust target, it may cause a false positive or false negative.

</details>

As stated in the title, there are many `target_os = "none" target` and tier3 targets that do not match.

- As for the `target_os = "none" target`, most of them probably do not match with Clang's default.
  - I guess this is because `c_char` was originally defined in `std` and this mismatch was missed [when it was moved to `core`](https://github.com/rust-lang/rust/pull/94503).
  - I don't think many people use `c_char` directly on these targets, but this includes a lot of tier 2 targets, so changing this to match Clang could have a not small impact on embedded ecosystem.
- All other targets seem to be tier 3, so I think changing them to match Clang's default should be no problem.
  - However, note that Clang's default may be wrong for minor architectures such as C-SKY. (see the reference below)

References:
- Apple:
  - Apple targets' c_char is signed by default even on arm ([arm64](https://developer.apple.com/documentation/xcode/writing-arm64-code-for-apple-platforms#Handle-data-types-and-data-alignment-properly), [armv6](https://developer.apple.com/documentation/xcode/writing-armv6-code-for-ios#Handle-data-types-and-data-alignment-properly))
- Windows:
  - [Windows MSVC C++ Language Reference says](https://learn.microsoft.com/en-us/cpp/cpp/fundamental-types-cpp?view=msvc-170#character-types) "Microsoft-specific: Variables of type char are promoted to int as if from type signed char by default, unless the [/J](https://learn.microsoft.com/en-us/cpp/build/reference/j-default-char-type-is-unsigned?view=msvc-170) compilation option is used."
- ARM:
  - [Section 8 "Arm C and C++ Language Mappings" in Procedure Call Standard for the Arm® Architecture](https://github.com/ARM-software/abi-aa/blob/2023Q3/aapcs32/aapcs32.rst#arm-c-and-c-language-mappings) says C/C++ char is unsigned byte
- AArch64:
  - [Section 10 "Arm C and C++ language mappings" in Procedure Call Standard for the Arm 64-bit Architecture (AArch64)](https://github.com/ARM-software/abi-aa/blob/2023Q3/aapcs64/aapcs64.rst#arm-c-and-c-language-mappings) says C/C++ char is unsigned byte
- RISC-V:
  - [C/C++ type representations section in RISC-V Calling Conventions page in RISC-V ELF psABI Document](https://github.com/riscv-non-isa/riscv-elf-psabi-doc/blob/draft-20240829-13bfa9f54634cb60d86b9b333e109f077805b4b3/riscv-cc.adoc#cc-type-representations) says "char is unsigned."
- PowerPC
  - Section 2.1.2.2 "Fundamental Types" in [64-Bit ELF V2 ABI Specification](https://openpowerfoundation.org/specifications/64bitelfabi/) says char is unsigned byte
  - [Section 3.1.4 "Fundamental Types" in 64-bit PowerPC ELF Application Binary Interface Supplement 1.9](https://refspecs.linuxfoundation.org/ELF/ppc64/PPC-elf64abi.html#FUND-TYPE) says ANSI C is unsigned byte
  - "Table 3-1 Scalar Types" in [SYSTEM V APPLICATION BINARY INTERFACE PowerPC Processor Supplement](https://refspecs.linuxfoundation.org/elf/elfspec_ppc.pdf) says ANSI C char is unsigned byte
  - [XL C for AIX  Language Reference](https://www.ibm.com/docs/en/xl-c-aix/13.1.3?topic=specifiers-character-types) says "By default, char behaves like an unsigned char."
- s390x
  - "Table 1.1.: Scalar types" in [ELF Application Binary Interface s390x Supplement Version 1.6.1](https://github.com/IBM/s390x-abi/releases/tag/v1.6.1) categorize ISO C char in unsigned integer
  - z/OS [XL C/C++ Language Reference](https://www.ibm.com/docs/en/zos/3.1.0?topic=specifiers-character-types) says "By default, char behaves like an unsigned char."
- Hexagon:
  - Section 3.1 "Basic data type" in [Qualcomm Hexagon™ Application Binary Interface User Guide](https://docs.qualcomm.com/bundle/publicresource/80-N2040-23_REV_K_Qualcomm_Hexagon_Application_Binary_Interface_User_Guide.pdf) says "By default, the `char` data type is unsigned."
- C-SKY:
  - Section 2.1.2 "Primary Data Type" in [C-SKY V2 CPU Applications Binary Interface Standards Manual](https://github.com/c-sky/csky-doc/blob/9f7121f7d40970ba5cc0f15716da033db2bb9d07/C-SKY_V2_CPU_Applications_Binary_Interface_Standards_Manual.pdf) says ANSI C char is unsigned byte
    - Note: this doesn't seem to match Clang's default (perhaps we need to fix Clang? cc @Dirreke)
      ```console
      $ clang -E -dM -x c /dev/null -target csky-unknown-linux-gnuabiv2 | grep __CHAR 
      #define __CHAR16_TYPE__ unsigned short
      #define __CHAR32_TYPE__ unsigned int
      #define __CHAR_BIT__ 8
      ```
- MSP430:
  - Section 2.1 "Basic Types" in [MSP430 Embedded Application Binary Interface](https://www.ti.com/lit/an/slaa534a/slaa534a.pdf) says "The char type is unsigned by default".
    - Note: this doesn't seem to match Clang's default (https://github.com/rust-lang/rust/issues/129945#issuecomment-2395227683)
- LoongArch:
  - ["Appendix: C data types and machine data types" in Procedure Call Standard for the LoongArch Architecture](https://github.com/loongson/la-abi-specs/blob/v2.30/lapcs.adoc#appendix-c-data-types-and-machine-data-types) says "For all base ABI types of LoongArch, the char data type in C is signed by default."
- AVR
  - https://gcc.gnu.org/wiki/avr-gcc#Type_Layout says char is signed
---

@rustbot label +A-abi +O-Arm +O-AArch64 +O-riscv +O-csky +O-bare-metal +O-android +O-illumos +O-hermit

### PR DESCRIPTION
**Pull request by arichardson**
Instead of having a list of unsigned char targets for each OS, follow the logic Clang uses and instead set the value based on architecture with a special case for Darwin and Windows operating systems. This makes it easier to support new operating systems targeting Arm/AArch64 without having to modify this config statement for each new OS. The new list does not quite match Clang since I noticed a few bugs in the Clang implementation (https://github.com/llvm/llvm-project/issues/115957).

Fixes https://github.com/rust-lang/rust/issues/129945
Closes https://github.com/rust-lang/rust/pull/131319

### CODE REVIEW

File: library/core/src/ffi/mod.rs [hunk 1]
```diff
@@ -92,56 +92,46 @@ pub type c_ssize_t = isize;
...
-                    target_arch = "arm",
-                    target_arch = "hexagon",
-                    target_arch = "powerpc",
-                    target_arch = "powerpc64",
-                    target_arch = "s390x",
-                    target_arch = "riscv64",
-                    target_arch = "riscv32",
-                    target_arch = "csky"
-                )
+        // See isSignedCharDefault() in clang/lib/Driver/ToolChains/Clang.cpp
```
Comment (maurer) [inline library/core/src/ffi/mod.rs:95]: The comment above is no longer correct - at the end of this `if` block, you put `i8`

File: library/core/src/ffi/mod.rs [hunk 2]
```diff
@@ -92,56 +92,46 @@ pub type c_ssize_t = isize;
...
-                    target_arch = "powerpc64",
-                    target_arch = "powerpc"
-                )
-            ),
-            all(
-                target_os = "fuchsia",
-                any(target_arch = "aarch64", target_arch = "riscv64")
+        ))] {
+            pub type c_char = i8;
+        } else if #[cfg(all(
```
Comment (maurer) [inline library/core/src/ffi/mod.rs:114]: We should probably only have one `if` and one `else`, one for `u8`, one for `i8`, having two `i8` branches should at worst be done by `any(`ing these two expressions together. We definitely shouldn't have 4 branches, 3 i8 and 1 u8.

**Review by maurer — CHANGES_REQUESTED** [review]
Some OSes are no longer conditioned on, for example, os=`nto` arch=`aarch64` or os=`l4re`, arch=`x86_64` are missing.

I didn't manually verify everything, but at least `l4re` and `x86_64` just got flipped from `u8`, which it appears to have been manually set to, to `i8`.

Can we get a summary of what changed in terms of supported target triples? I would expect disagreements with `clang` to be rare, but this patch looks like it accidentally changes obscure targets at a minimum. It might also be clearer what changed if we didn't have the 4-branch if statement for 2 results.

File: library/core/src/ffi/mod.rs (hunk 2 above)
Comment (arichardson) [reply library/core/src/ffi/mod.rs:114]: I did it this way to avoid duplicating the 5 darwin OS combinations but as you say it might be cleaner to do it that way. Let me try that

Comment (arichardson) [reply library/core/src/ffi/mod.rs:114]: I simplified this by relying on Apple operating systems other than macos only supporting Arm, so it's not too bad.

**Comment by maurer** [comment]
I'm pretty sure this still changes `l4re-x86_64` from unsigned to signed.

**Comment by arichardson** [comment]
> I'm pretty sure this still changes `l4re-x86_64` from unsigned to signed.

I'm trying to figure out if that value is intentional or not. It dates back to https://github.com/rust-lang/rust/commit/2cf0a4ad4690c587d755dc6e5383779dddb9b178, but I can't see anything in L4RE that changes the default - maybe this was actually indented to set it for aarch64? CC: @TobiasSchaffner

**Comment by arichardson** [comment]
Looks like l4re should be setting this for all architectures, I spotted `-funsigned-char` in https://github.com/kernkonzept/mk/blob/926afa93e32e64dbdb33cf9ae724924ee1fb16e0/tool/kconfig/Makefile#L550, so that suggests it's the case for all targets. Will update to handle that.

File: library/core/src/ffi/mod.rs (hunk 2 above)
Comment (arichardson) [reply library/core/src/ffi/mod.rs]: Thanks this is so much simpler!

**Comment by joshtriplett** [comment]
r? libs-api

**Comment by tgross35** [comment]
See also an open issue about this https://github.com/rust-lang/rust/issues/129945 (cc @taiki-e)

**Comment by arichardson** [comment]
I have validated the new c_char definitions against my build of clang that has fixes for MSP430, Xtensa (although printing the builtin defines fails with `error: unknown target triple 'xtensa-unknown-none-elf'`), and CSKY (which fails with `version 'abiv2' in target triple 'csky-unknown-linux-gnuabiv2' is invalid`).

Unlike https://github.com/rust-lang/rust/pull/131319 this PR does not have links to all the ABI docs, but it does have a correct definition for l4re (which clang does not support and treats as unknown OS).

**Comment by taiki-e** [comment]
As for L4Re:
I think L4Re code you are linking is config when building kernel. IIUC, userland uses signed for x86_64 and unsigned for aarch64 by default (i.e., same as ELF ABI's default).

```
$ ./toolchain-l4re-x86_64-gcc-14/bin/x86_64-l4re-gcc -E -dM -x c /dev/null | grep -F __CHAR_
#define __CHAR_BIT__ 8

$ ./toolchain-l4re-arm64-gcc-14/bin/aarch64-l4re-gcc -E -dM -x c /dev/null | grep -F __CHAR_
#define __CHAR_BIT__ 8
#define __CHAR_UNSIGNED__ 1
```

({x86_64,aarch64}-l4re-gcc are from https://l4re.org/download/snapshots/toolchain/.)

---

As for Xtensa:
Section 2.17.1 "Data Types and Alignment" of Xtensa LX Microprocessor Overview handbook <https://loboris.eu/ESP32/Xtensa_lx%20Overview%20handbook.pdf> says "`char` type is unsigned by default".


However, it appears that Xtensa has multiple ABIs. (Section 1.4 "Calling convention" of Overview of Xtensa ISA <https://dl.espressif.com/github_assets/espressif/xtensa-isa-doc/releases/download/latest/Xtensa.pdf>)

**Comment by arichardson** [comment]
Rebased and fixed the l4re issue.

> As for L4Re: I think [L4Re code you are linking](https://github.com/rust-lang/rust/pull/132975#issuecomment-2474547410) is config when building kernel. IIUC, userland uses signed for x86_64 and unsigned for aarch64 by default (i.e., same as ELF ABI's default).
> 
> ```
> $ ./toolchain-l4re-x86_64-gcc-14/bin/x86_64-l4re-gcc -E -dM -x c /dev/null | grep -F __CHAR_
> #define __CHAR_BIT__ 8
> 
> $ ./toolchain-l4re-arm64-gcc-14/bin/aarch64-l4re-gcc -E -dM -x c /dev/null | grep -F __CHAR_
> #define __CHAR_BIT__ 8
> #define __CHAR_UNSIGNED__ 1
> ```
> 
> ({x86_64,aarch64}-l4re-gcc are from https://l4re.org/download/snapshots/toolchain/.)
> 

Thanks for checking this, I've updated the change to remove l4re from the list. I've done this as a separate commit in case this needs to be reverted in the future.

> As for Xtensa: Section 2.17.1 "Data Types and Alignment" of Xtensa LX Microprocessor Overview handbook https://loboris.eu/ESP32/Xtensa_lx%20Overview%20handbook.pdf says "`char` type is unsigned by default".
> 
> However, it appears that Xtensa has multiple ABIs. (Section 1.4 "Calling convention" of Overview of Xtensa ISA https://dl.espressif.com/github_assets/espressif/xtensa-isa-doc/releases/download/latest/Xtensa.pdf) (I have not checked whether the defaults are consistent among those ABIs or not -- this is why my PR has done nothing about Xtensa.)

Regarding Xtensa, my Clang change to make it unsigned by default was approved by Xtensa developers and has been merged now: https://github.com/llvm/llvm-project/pull/115967.

**Comment by tgross35** [comment]
@rustbot label +I-libs-api-nominated

As noted in https://github.com/rust-lang/rust/issues/129945 there are a lot of tier 2 and 3 targets that disagree with Clang on the signedness of `c_char`, in particular the `-unknown-` targets. This PR changes Rust's logic to be more similar to Clang's and resolves most (all?) of the discrepancies. This is a correctness fix but it is breaking for the targets listed in the issue, so libs-api feedback is requested.

**Comment by tgross35** [comment]
Review notes: it is probably ideal to wait until https://github.com/rust-lang/rust/pull/133944 if that is ready in the near future, since it should give us a concrete list of what changed as part of this diff. Alternatively rerun @taiki-e's script from https://github.com/rust-lang/rust/issues/129945 before and after this change.

Could you pick up the long sources comment from https://github.com/rust-lang/rust/pull/131319/files#diff-92ac4f00ad02a9a9d7ebcd5337dec510097384904750feee32110bd614500050R95? Having somewhere specific to point to is probably good to preserve.

**Comment by arichardson** [comment]
> Review notes: it is probably ideal to wait until #133944 if that is ready in the near future, since it should give us a concrete list of what changed as part of this diff. Alternatively rerun @taiki-e's script from #129945 before and after this change.
> 
> Could you pick up the long sources comment from https://github.com/rust-lang/rust/pull/131319/files#diff-92ac4f00ad02a9a9d7ebcd5337dec510097384904750feee32110bd614500050R95? Having somewhere specific to point to is probably good to preserve.

Sure will update this and and the appropriate attribution to the commit message. I ran the script before and after but didn't save the output. Will rerun it and paste the output compared to LLVM HEAD.

**Comment by Amanieu** [comment]
We discussed this in the libs-api meeting and we are OK with the breaking change since:
- it is actually a correctness fix.
- it primarily affects embedded targets (-unknown-) which are less likely to interact with C code.

**Comment by arichardson** [comment]
I just finished running a slightly modified version of the test script from https://github.com/rust-lang/rust/issues/129945 

Summary:
- Fixes various aarch64/arm and powerpc results
  - I did have to fix a few incorrect PPC triples, will upload those fixes in a separate PR
- C codegen for XTensa is not enabled in upstream Clang yet (only LLVM and some parts of Clang have landed), but the rust value is correct.
- A few triples are not recognized by Clang: armv5te-unknown-linux-uclibcgnueabi, mips-unknown-linux-uclibc, mipsel-unknown-linux-uclibc, x86_64-unknown-l4re-uclibc, but the rust value has been validated against the sepcs.

Full output:

```
aarch64-apple-darwin: i8 correct
aarch64-apple-ios: i8 correct
aarch64-apple-ios-macabi: i8 correct
aarch64-apple-ios-sim: i8 correct
aarch64-apple-tvos: i8 correct
aarch64-apple-tvos-sim: i8 correct
aarch64-apple-visionos: i8 correct
aarch64-apple-visionos-sim: i8 correct
aarch64-apple-watchos: i8 correct
aarch64-apple-watchos-sim: i8 correct
aarch64-kmc-solid_asp3: u8 correct
aarch64-linux-android: u8 correct
aarch64-nintendo-switch-freestanding: u8 correct
aarch64-pc-windows-gnullvm: i8 correct
aarch64-pc-windows-msvc: i8 correct
aarch64-unknown-freebsd: u8 correct
aarch64-unknown-fuchsia: u8 correct
aarch64-unknown-hermit: u8 correct
aarch64-unknown-illumos: u8 correct
aarch64-unknown-linux-gnu: u8 correct
aarch64-unknown-linux-gnu_ilp32: u8 correct
aarch64-unknown-linux-musl: u8 correct
aarch64-unknown-linux-ohos: u8 correct
aarch64-unknown-netbsd: u8 correct
aarch64-unknown-none: u8 correct
aarch64-unknown-none-softfloat: u8 correct
aarch64-unknown-nto-qnx700: u8 correct
aarch64-unknown-nto-qnx710: u8 correct
aarch64-unknown-openbsd: u8 correct
aarch64-unknown-redox: u8 correct
aarch64-unknown-teeos: u8 correct
aarch64-unknown-trusty: u8 correct
aarch64-unknown-uefi: should be i8
aarch64-uwp-windows-msvc: i8 correct
aarch64-wrs-vxworks: u8 correct
aarch64_be-unknown-linux-gnu: u8 correct
aarch64_be-unknown-linux-gnu_ilp32: u8 correct
aarch64_be-unknown-netbsd: u8 correct
arm-linux-androideabi: u8 correct
arm-unknown-linux-gnueabi: u8 correct
arm-unknown-linux-gnueabihf: u8 correct
arm-unknown-linux-musleabi: u8 correct
arm-unknown-linux-musleabihf: u8 correct
arm64_32-apple-watchos: i8 correct
arm64e-apple-darwin: i8 correct
arm64e-apple-ios: i8 correct
arm64e-apple-tvos: i8 correct
arm64ec-pc-windows-msvc: i8 correct
armeb-unknown-linux-gnueabi: u8 correct
armebv7r-none-eabi: u8 correct
armebv7r-none-eabihf: u8 correct
armv4t-none-eabi: u8 correct
armv4t-unknown-linux-gnueabi: u8 correct
armv5te-none-eabi: u8 correct
armv5te-unknown-linux-gnueabi: u8 correct
armv5te-unknown-linux-musleabi: u8 correct
clang: error: version 'uclibcgnueabi' in target triple 'armv5te-unknown-linux-uclibcgnueabi' is invalid
clang: warning: unknown platform, assuming -mfloat-abi=soft
clang: warning: unknown platform, assuming -mfloat-abi=soft
clang: warning: unknown platform, assuming -mfloat-abi=soft
Failed to obtain builtin defines for armv5te-unknown-linux-uclibcgnueabi
armv5te-unknown-linux-uclibceabi: Unknown c_char
armv6-unknown-freebsd: u8 correct
armv6-unknown-netbsd-eabihf: u8 correct
armv6k-nintendo-3ds: u8 correct
armv7-linux-androideabi: u8 correct
armv7-rtems-eabihf: u8 correct
armv7-sony-vita-newlibeabihf: u8 correct
armv7-unknown-freebsd: u8 correct
armv7-unknown-linux-gnueabi: u8 correct
armv7-unknown-linux-gnueabihf: u8 correct
armv7-unknown-linux-musleabi: u8 correct
armv7-unknown-linux-musleabihf: u8 correct
armv7-unknown-linux-ohos: u8 correct
armv7-unknown-linux-uclibceabi: u8 correct
armv7-unknown-linux-uclibceabihf: u8 correct
armv7-unknown-netbsd-eabihf: u8 correct
armv7-unknown-trusty: u8 correct
armv7-wrs-vxworks-eabihf: u8 correct
armv7a-kmc-solid_asp3-eabi: u8 correct
armv7a-kmc-solid_asp3-eabihf: u8 correct
armv7a-none-eabi: u8 correct
armv7a-none-eabihf: u8 correct
armv7k-apple-watchos: i8 correct
armv7r-none-eabi: u8 correct
armv7r-none-eabihf: u8 correct
armv7s-apple-ios: i8 correct
armv8r-none-eabihf: u8 correct
clang: warning: no target microcontroller specified, please pass -mmcu=<mcu name> [-Wavr-rtlib-linking-quirks]
avr-unknown-gnu-atmega328: i8 correct
bpfeb-unknown-none: i8 correct
bpfel-unknown-none: i8 correct
clang: error: version 'abiv2' in target triple 'csky-unknown-linux-gnuabiv2' is invalid
Failed to obtain builtin defines for csky-unknown-linux-gnuabiv2
csky-unknown-linux-gnuabiv2: Unknown c_char
clang: error: version 'abiv2' in target triple 'csky-unknown-linux-gnuabiv2' is invalid
Failed to obtain builtin defines for csky-unknown-linux-gnuabiv2
csky-unknown-linux-gnuabiv2hf: Unknown c_char
hexagon-unknown-linux-musl: u8 correct
hexagon-unknown-none-elf: u8 correct
i386-apple-ios: i8 correct
i586-pc-nto-qnx700: i8 correct
i586-pc-windows-msvc: i8 correct
i586-unknown-linux-gnu: i8 correct
i586-unknown-linux-musl: i8 correct
i586-unknown-netbsd: i8 correct
i686-apple-darwin: i8 correct
i686-linux-android: i8 correct
i686-pc-windows-gnu: i8 correct
i686-pc-windows-gnullvm: i8 correct
i686-pc-windows-msvc: i8 correct
i686-unknown-freebsd: i8 correct
i686-unknown-haiku: i8 correct
i686-unknown-hurd-gnu: i8 correct
i686-unknown-linux-gnu: i8 correct
i686-unknown-linux-musl: i8 correct
i686-unknown-netbsd: i8 correct
i686-unknown-openbsd: i8 correct
i686-unknown-redox: i8 correct
i686-unknown-uefi: i8 correct
i686-uwp-windows-gnu: i8 correct
i686-uwp-windows-msvc: i8 correct
i686-win7-windows-msvc: i8 correct
i686-wrs-vxworks: i8 correct
loongarch64-unknown-linux-gnu: i8 correct
loongarch64-unknown-linux-musl: i8 correct
loongarch64-unknown-linux-ohos: i8 correct
loongarch64-unknown-none: i8 correct
loongarch64-unknown-none-softfloat: i8 correct
m68k-unknown-linux-gnu: i8 correct
mips-unknown-linux-gnu: i8 correct
mips-unknown-linux-musl: i8 correct
clang: error: version 'uclibc' in target triple 'mips-unknown-linux-uclibc' is invalid
Failed to obtain builtin defines for mips-unknown-linux-uclibc
mips-unknown-linux-uclibc: Unknown c_char
mips64-openwrt-linux-musl: i8 correct
mips64-unknown-linux-gnuabi64: i8 correct
mips64-unknown-linux-muslabi64: i8 correct
mips64el-unknown-linux-gnuabi64: i8 correct
mips64el-unknown-linux-muslabi64: i8 correct
mipsel-sony-psp: i8 correct
mipsel-sony-psx: i8 correct
mipsel-unknown-linux-gnu: i8 correct
mipsel-unknown-linux-musl: i8 correct
clang: error: version 'uclibc' in target triple 'mipsel-unknown-linux-uclibc' is invalid
Failed to obtain builtin defines for mipsel-unknown-linux-uclibc
mipsel-unknown-linux-uclibc: Unknown c_char
mipsel-unknown-netbsd: i8 correct
mipsel-unknown-none: i8 correct
mipsisa32r6-unknown-linux-gnu: i8 correct
mipsisa32r6el-unknown-linux-gnu: i8 correct
mipsisa64r6-unknown-linux-gnuabi64: i8 correct
mipsisa64r6el-unknown-linux-gnuabi64: i8 correct
msp430-none-elf: u8 correct
nvptx64-nvidia-cuda: i8 correct
powerpc-unknown-freebsd: u8 correct
powerpc-unknown-linux-gnu: u8 correct
powerpc-unknown-linux-gnuspe: u8 correct
powerpc-unknown-linux-musl: u8 correct
powerpc-unknown-linux-muslspe: u8 correct
powerpc-unknown-netbsd: u8 correct
powerpc-unknown-openbsd: u8 correct
powerpc-wrs-vxworks: u8 correct
powerpc-wrs-vxworks-spe: u8 correct
powerpc64-ibm-aix: u8 correct
powerpc64-unknown-freebsd: u8 correct
powerpc64-unknown-linux-gnu: u8 correct
powerpc64-unknown-linux-musl: u8 correct
powerpc64-unknown-openbsd: u8 correct
powerpc64-wrs-vxworks: u8 correct
powerpc64le-unknown-freebsd: u8 correct
powerpc64le-unknown-linux-gnu: u8 correct
powerpc64le-unknown-linux-musl: u8 correct
riscv32-wrs-vxworks: u8 correct
riscv32e-unknown-none-elf: u8 correct
riscv32em-unknown-none-elf: u8 correct
riscv32emc-unknown-none-elf: u8 correct
riscv32gc-unknown-linux-gnu: u8 correct
riscv32gc-unknown-linux-musl: u8 correct
riscv32i-unknown-none-elf: u8 correct
riscv32im-risc0-zkvm-elf: u8 correct
riscv32im-unknown-none-elf: u8 correct
riscv32ima-unknown-none-elf: u8 correct
riscv32imac-esp-espidf: u8 correct
riscv32imac-unknown-none-elf: u8 correct
riscv32imac-unknown-nuttx-elf: u8 correct
riscv32imac-unknown-xous-elf: u8 correct
riscv32imafc-esp-espidf: u8 correct
riscv32imafc-unknown-none-elf: u8 correct
riscv32imafc-unknown-nuttx-elf: u8 correct
riscv32imc-esp-espidf: u8 correct
riscv32imc-unknown-none-elf: u8 correct
riscv32imc-unknown-nuttx-elf: u8 correct
riscv64-linux-android: u8 correct
riscv64-wrs-vxworks: u8 correct
riscv64gc-unknown-freebsd: u8 correct
riscv64gc-unknown-fuchsia: u8 correct
riscv64gc-unknown-hermit: u8 correct
riscv64gc-unknown-linux-gnu: u8 correct
riscv64gc-unknown-linux-musl: u8 correct
riscv64gc-unknown-netbsd: u8 correct
riscv64gc-unknown-none-elf: u8 correct
riscv64gc-unknown-nuttx-elf: u8 correct
riscv64gc-unknown-openbsd: u8 correct
riscv64imac-unknown-none-elf: u8 correct
riscv64imac-unknown-nuttx-elf: u8 correct
s390x-unknown-linux-gnu: u8 correct
s390x-unknown-linux-musl: u8 correct
sparc-unknown-linux-gnu: i8 correct
sparc-unknown-none-elf: i8 correct
sparc64-unknown-linux-gnu: i8 correct
sparc64-unknown-netbsd: i8 correct
sparc64-unknown-openbsd: i8 correct
sparcv9-sun-solaris: i8 correct
thumbv4t-none-eabi: u8 correct
thumbv5te-none-eabi: u8 correct
thumbv6m-none-eabi: u8 correct
thumbv6m-nuttx-eabi: u8 correct
thumbv7a-pc-windows-msvc: i8 correct
thumbv7a-uwp-windows-msvc: i8 correct
thumbv7em-none-eabi: u8 correct
thumbv7em-none-eabihf: u8 correct
thumbv7em-nuttx-eabi: u8 correct
thumbv7em-nuttx-eabihf: u8 correct
thumbv7m-none-eabi: u8 correct
thumbv7m-nuttx-eabi: u8 correct
thumbv7neon-linux-androideabi: u8 correct
thumbv7neon-unknown-linux-gnueabihf: u8 correct
thumbv7neon-unknown-linux-musleabihf: u8 correct
thumbv8m.base-none-eabi: u8 correct
thumbv8m.base-nuttx-eabi: u8 correct
thumbv8m.main-none-eabi: u8 correct
thumbv8m.main-none-eabihf: u8 correct
thumbv8m.main-nuttx-eabi: u8 correct
thumbv8m.main-nuttx-eabihf: u8 correct
wasm32-unknown-emscripten: i8 correct
wasm32-unknown-unknown: i8 correct
wasm32-wasip1: i8 correct
wasm32-wasip1-threads: i8 correct
wasm32-wasip2: i8 correct
wasm32v1-none: i8 correct
wasm64-unknown-unknown: i8 correct
x86_64-apple-darwin: i8 correct
x86_64-apple-ios: i8 correct
x86_64-apple-ios-macabi: i8 correct
x86_64-apple-tvos: i8 correct
x86_64-apple-watchos-sim: i8 correct
x86_64-fortanix-unknown-sgx: i8 correct
x86_64-linux-android: i8 correct
x86_64-pc-nto-qnx710: i8 correct
x86_64-pc-solaris: i8 correct
x86_64-pc-windows-gnu: i8 correct
x86_64-pc-windows-gnullvm: i8 correct
x86_64-pc-windows-msvc: i8 correct
x86_64-unikraft-linux-musl: i8 correct
x86_64-unknown-dragonfly: i8 correct
x86_64-unknown-freebsd: i8 correct
x86_64-unknown-fuchsia: i8 correct
x86_64-unknown-haiku: i8 correct
x86_64-unknown-hermit: i8 correct
x86_64-unknown-hurd-gnu: i8 correct
x86_64-unknown-illumos: i8 correct
clang: error: version 'uclibc' in target triple 'x86_64-unknown-l4re-uclibc' is invalid
Failed to obtain builtin defines for x86_64-unknown-l4re-uclibc
x86_64-unknown-l4re-uclibc: Unknown c_char
x86_64-unknown-linux-gnu: i8 correct
x86_64-unknown-linux-gnux32: i8 correct
x86_64-unknown-linux-musl: i8 correct
x86_64-unknown-linux-none: i8 correct
x86_64-unknown-linux-ohos: i8 correct
x86_64-unknown-netbsd: i8 correct
x86_64-unknown-none: i8 correct
x86_64-unknown-openbsd: i8 correct
x86_64-unknown-redox: i8 correct
x86_64-unknown-trusty: i8 correct
x86_64-unknown-uefi: i8 correct
x86_64-uwp-windows-gnu: i8 correct
x86_64-uwp-windows-msvc: i8 correct
x86_64-win7-windows-msvc: i8 correct
x86_64-wrs-vxworks: i8 correct
x86_64h-apple-darwin: i8 correct
error: unknown target triple 'xtensa-unknown-none-elf'
Failed to obtain builtin defines for xtensa-none-elf
xtensa-esp32-espidf: Unknown c_char
error: unknown target triple 'xtensa-unknown-none-elf'
Failed to obtain builtin defines for xtensa-none-elf
xtensa-esp32-none-elf: Unknown c_char
error: unknown target triple 'xtensa-unknown-none-elf'
Failed to obtain builtin defines for xtensa-none-elf
xtensa-esp32s2-espidf: Unknown c_char
error: unknown target triple 'xtensa-unknown-none-elf'
Failed to obtain builtin defines for xtensa-none-elf
xtensa-esp32s2-none-elf: Unknown c_char
error: unknown target triple 'xtensa-unknown-none-elf'
Failed to obtain builtin defines for xtensa-none-elf
xtensa-esp32s3-espidf: Unknown c_char
error: unknown target triple 'xtensa-unknown-none-elf'
Failed to obtain builtin defines for xtensa-none-elf
xtensa-esp32s3-none-elf: Unknown c_char
```

**Comment by tgross35** [comment]
It looks like `aarch64-unknown-uefi: should be i8` is the last one that still has a mismatch, do you know why that would be?

**Comment by tgross35** [comment]
Pinging some target maintainers:

- Solid @kawadakk
- Hermit @stlankes @mkroening
- Illumos @jclulow @sunshowers 
- Redox @jackpot51 
- Trusty @randomPoison @ahomescu 
- Hexagon @androm3da
- RISC-V @robin-randhawa-sifive @raw-bin
- RISC-V Android @chriswalles @maurer 
- Xous @xobs
- ESP-IDF @ivmarkov @MabezDev
- Nuttx @no1wudi 

If you were pinged here, this PR will change one of your target's definition of `c_char` to be in line with Clang's, most from `i8` to `u8`. Not all targets change, this is pretty limited to Arm and RISC-V. The full list of changing targets is at https://github.com/rust-lang/rust/issues/129945 and the list after being fixed is https://github.com/rust-lang/rust/pull/132975#issuecomment-2532688643, let us know if you know something to be incorrect here.

**Comment by jclulow** [comment]
>     * it primarily affects embedded targets (-unknown-) which are less likely to interact with C code.

I don't think that's actually what **-unknown-** means, FWIW.  Looking at (the platform support list)[https://doc.rust-lang.org/nightly/rustc/platform-support.html] I see quite a lot of targets that contain the string **-unknown-** and are not embedded systems.

**Comment by jclulow** [comment]
I have confirmed with the folks working on the illumos ARM port that **char** is unsigned there to match the prevailing winds, so this makes sense to us, thanks!

**Comment by randomPoison** [comment]
This is correct for Trusty as far as I know, we expect `c_char` to be `u8` on both `aarch64` and `arm`.

**Comment by arichardson** [comment]
> aarch64-unknown-uefi

Interesting, it looks like this is probably a bug in the target definition, which means it uses the windows ABI in Clang:
`        llvm_target: "aarch64-unknown-windows".into(),`

This should be "aarch64-unknown-uefi" which Clang understands
```
❯ ~/upstream-llvm-project/cmake-build-debug/bin/clang -E -dM -x c /dev/null -target aarch64-unknown-uefi | grep __CHAR_UN
#define __CHAR_UNSIGNED__ 1
❯ ~/upstream-llvm-project/cmake-build-debug/bin/clang -E -dM -x c /dev/null -target aarch64-unknown-windows | grep __CHAR_UN
```

**Comment by jackpot51** [comment]
This is fine for Redox OS.

**Comment by tgross35** [comment]
> > aarch64-unknown-uefi
> 
> Interesting, it looks like this is probably a bug in the target definition, which means it uses the windows ABI in Clang: ` llvm_target: "aarch64-unknown-windows".into(),`
> 
> This should be "aarch64-unknown-uefi" which Clang understands

That is mildly amusing. Opened https://github.com/rust-lang/rust/pull/134156 to fix it.

**Comment by tgross35** [comment]
With the libs-api approval I don't think there is any reason to hold off, especially considering it was mentioned during the meeting that this is better to have toward the beginning of a release cycle (we are reasonably early now, next branch is January 3rd for stable on February 20th).

@bors r+

Thanks everyone who took a look at this.

**Comment by arichardson** [comment]
> > > aarch64-unknown-uefi
> > 
> > 
> > Interesting, it looks like this is probably a bug in the target definition, which means it uses the windows ABI in Clang: ` llvm_target: "aarch64-unknown-windows".into(),`
> > This should be "aarch64-unknown-uefi" which Clang understands
> 
> That is mildly amusing. Opened #134156 to fix it.

Digging deeper it looks like this is only partially supported in Clang (x86 supports the triple, aarch64 triggers assertions). I do wonder if Clang's output here is wrong and Rust is correct - I imagine UEFI follows the Windows ABIs since it is COFF-based? But I haven't found a spec for the UEFI AArch64 ABI.

**Comment by androm3da** [comment]
Confirmed: for `hexagon` targets, `c_char` should be unsigned. ✅

Thanks for the fix.

**Comment by ivmarkov** [comment]
> Pinging some target maintainers (checkbox = acked):
> 
> * [ ]  Solid @kawadakk
> * [ ]  Hermit @stlankes @mkroening
> * [x]  Illumos @jclulow @sunshowers
> * [x]  Redox @jackpot51
> * [x]  Trusty @randomPoison @ahomescu
> * [x]  Hexagon @androm3da
> * [ ]  RISC-V @robin-randhawa-sifive @raw-bin
> * [ ]  RISC-V Android @chriswalles @maurer
> * [x]  Xous @xobs
> * [ ]  ESP-IDF @ivmarkov @MabezDev
> * [ ]  Nuttx @no1wudi
> 
> If you were pinged here, this PR will change one of your target's definition of `c_char` to be in line with Clang's, most from `i8` to `u8`. Not all targets change, this is pretty limited to Arm and RISC-V. The full list of changing targets is at #129945 and the list after being fixed is [#132975 (comment)](https://github.com/rust-lang/rust/pull/132975#issuecomment-2532688643), let us know if you know something to be incorrect here.

It looks like indeed `c_char` should be unsigned for both xtensa and riscv ESP-IDF targets. Yet - we are likely to have downstream breakages because of this change, as I noticed there are (a few) places where we have frivolously used `c_char` and `i8` interchangeably, and obviously these places need to be fixed to only use `core::ffi::c_char` now.

With that said, I guess it is on us to fix this downstream, and we'll know the impact pretty soon, given the "bors +r" from a couple of hours ago.

**Comment by mkroening** [comment]
This aligns Hermit to its [definitions in `libc`](https://github.com/rust-lang/libc/blob/0.2.168/src/hermit.rs#L5-L11), so this is good from our side. Thanks! :)

**Comment by ivmarkov** [comment]
Hmm, looks like we need to fix then the ESP IDF [`c_char` definition in `libc`](https://github.com/rust-lang/libc/blob/e6082ef26096154e08ab0cb094d66d5ca116ee15/src/unix/newlib/espidf/mod.rs#L4), as it is `i8` and this would now be different from the `core::ffi::c_char` definition.

I also wonder (excuse my ignorance) what this change means with regards to interop with C code compiled with GCC, [as it seems GCC always treats `char` as a signed char, unless you tell it otherwise](https://stackoverflow.com/a/2054959)?

**Comment by tgross35** [comment]
> Hmm, looks like we need to fix then the ESP IDF [`c_char` definition in `libc`](https://github.com/rust-lang/libc/blob/e6082ef26096154e08ab0cb094d66d5ca116ee15/src/unix/newlib/espidf/mod.rs#L4), as it is `i8` and this would now be different from the `core::ffi::c_char` definition.

`libc` will need to be updated after this, most of the targets listed here probably have the same definition in `libc`.

> I also wonder (excuse my ignorance) what this change means with regards to interop with C code compiled with GCC, [as it seems GCC always treats `char` as a signed char, unless you tell it otherwise](https://stackoverflow.com/a/2054959)?

I think this answer might just be referring to x86, https://gcc.gnu.org/onlinedocs/gcc-4.2.2/gcc/C-Dialect-Options.html says:

> Each kind of machine has a default for what char should be. It is either like unsigned char by default or like signed char by default. 

And based on testing a few targets at https://godbolt.org/z/vxvY34W8b, at least the ARM and RISC-V targets seem to have __CHAR_UNSIGNED__ defined.

AVR GCC actually does not have this defined for the thumb targets so we might need to double check those https://godbolt.org/z/rdroc9fe9 (@Patryk27).

> It looks like indeed `c_char` should be unsigned for both xtensa and riscv ESP-IDF targets. Yet - we are likely to have downstream breakages because of this change, as I noticed there are (a few) places where we have frivolously used `c_char` and `i8` interchangeably, and obviously these places need to be fixed to only use `core::ffi::c_char` now.
> 
> With that said, I guess it is on us to fix this downstream, and we'll know the impact pretty soon, given the "bors +r" from a couple of hours ago.

To be clear, we can make followup changes to specific targets as needed, or if the fallout is especially bad in particular areas.

**Comment by taiki-e** [comment]
@tgross35 

> AVR GCC actually does not have this defined for the thumb targets so we might need to double check those

thumb is thumb mode of 32-bit Arm (`target_arch = "arm"`). AVR GCC is for AVR (`target_arch = "avr"`) and unrelated to thumb.

c_char of AVR is signed by default as mentioned in the references in https://github.com/rust-lang/rust/issues/129945.

>AVR
https://gcc.gnu.org/wiki/avr-gcc#Type_Layout says char is signed

**Comment by kawadakk** [comment]
The SOLID toolchain actually uses `-fsigned-char`, but we are planning to phase out this flag in a near feature, and the impact is limited due to the nature of embedded systems, so we are okay with this change.

**Comment by ids1024** [comment]
This also seems to break compilation for nuttx targets, since it doesn't match `libc`, but it probably is right and should be fixed there.

File: library/core/src/ffi/mod.rs [hunk 3]
```diff
@@ -91,59 +91,86 @@ pub type c_ssize_t = isize;
...
+        //   page in RISC-V ELF psABI Document says "char is unsigned."
+        //   https://github.com/riscv-non-isa/riscv-elf-psabi-doc/blob/draft-20240829-13bfa9f54634cb60d86b9b333e109f077805b4b3/riscv-cc.adoc#cc-type-representations
+        // s390x:
+        //   - ELF: "Table 1.1.: Scalar types" in ELF Application Binary Interface s390x Supplement
+        //     Version 1.6.1 categorize ISO C char in unsigned integer
+        //     https://github.com/IBM/s390x-abi/releases/tag/v1.6.1
+        //   - z/OS: XL C/C++ Language Reference says: "By default, char behaves like an unsigned char."
+        //     https://www.ibm.com/docs/en/zos/3.1.0?topic=specifiers-character-types
+        // Xtensa:
+        //   - "The char type is unsigned by default for Xtensa processors."
```
Comment (bugadani) [inline library/core/src/ffi/mod.rs:143]: Where is this information coming from?

**Comment by ivmarkov** [comment]
> To be clear, we can make followup changes to specific targets as needed, or if the fallout is especially bad in particular areas.

No need to. 
I've now checked the `ESP-IDF` checkbox in that `core::ffi::c_char` (and `libc`'s `c_char`) should indeed both be unsigned, as  per [these findings](https://github.com/rust-lang/libc/pull/4195#issuecomment-2543096509).

**Comment by nico** [comment]
This changed c_char on android/riscv from signed to unsinged. Was that intentional?

If so, https://github.com/rust-lang/libc/blob/main/src/unix/linux_like/android/b64/riscv64/mod.rs probably needs updating?

**Comment by arichardson** [comment]
> This changed c_char on android/riscv from signed to unsinged. Was that intentional?
> 
> If so, https://github.com/rust-lang/libc/blob/main/src/unix/linux_like/android/b64/riscv64/mod.rs probably needs updating?

Not explicitly intentional, but a correct change. Prior to this rust disagreed with clang, now it matches (see https://github.com/rust-lang/rust/pull/132975#issuecomment-2532688643)

**Comment by nico** [comment]
Thoughts on the second part of the question? c_char in https://github.com/rust-lang/libc/blob/main/src/unix/linux_like/android/b64/riscv64/mod.rs now doesn't match c_char here, which leads to build errors on android/riscv64 (e.g. https://crbug.com/384413087)

**Comment by arichardson** [comment]
> Thoughts on the second part of the question? c_char in https://github.com/rust-lang/libc/blob/main/src/unix/linux_like/android/b64/riscv64/mod.rs now doesn't match c_char here, which leads to build errors on android/riscv64 (e.g. https://crbug.com/384413087)

Yes, it looks like the other c_char needs to be updated to u8. Sorry about all the breakage this pr is causing...

**Comment by tgross35** [comment]
> Thoughts on the second part of the question? c_char in https://github.com/rust-lang/libc/blob/main/src/unix/linux_like/android/b64/riscv64/mod.rs now doesn't match c_char here, which leads to build errors on android/riscv64 (e.g. https://crbug.com/384413087)

Anything that changed here does need to be updated at `libc`. I'll try to make sure these are fixed and in a release next week.

As a temporary workaround, can your build patch an `as *const libc::c_char` in `stdarch` so it keeps building regardless of whether or not `libc` has been updated? I think `riscv64-linux-android` is the only affected target that needs the `linux` modules in `stdarch`.

(sorry, had a comment typed but forgot to submit)

**Comment by tgross35** [comment]
Updates to `libc` were released in https://github.com/rust-lang/libc/releases/tag/0.2.169.
