### PR TITLE
handle ConstValue::ByRef in relate

### LINKED ISSUE #68615: Instantiating a type that's const-generic over a custom type doesn't work
Code ([Playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=cacbacd3b806815e765094cc69842bcd)):

```rust
#![feature(const_generics)]

#[derive(PartialEq, Eq)]
struct MyType;
struct Const<const V: MyType> {}
type MyConst = Const<{ MyType }>;

fn main() {
    let _x = Const::<{ MyType }> {};
    let _y = MyConst {};
}
```

Error message:

```
error[E0308]: mismatched types
 --> src/main.rs:9:14
  |
9 |     let _x = Const::<{ MyType }> {};
  |              ^^^^^^^^^^^^^^^^^^^^^^ expected `ByRef { alloc: Allocation { bytes: [], relocations: Relocations(SortedMap { data: [] }), undef_mask: UndefMask { blocks: [], len: Size { raw: 0 } }, size: Size { raw: 0 }, align: Align { pow2: 0 }, mutability: Not, extra: () }, offset: Size { raw: 0 } }: MyType`, found `ByRef { alloc: Allocation { bytes: [], relocations: Relocations(SortedMap { data: [] }), undef_mask: UndefMask { blocks: [], len: Size { raw: 0 } }, size: Size { raw: 0 }, align: Align { pow2: 0 }, mutability: Not, extra: () }, offset: Size { raw: 0 } }: MyType`
  |
  = note: expected type `_`
           found struct `Const<ByRef { alloc: Allocation { bytes: [], relocations: Relocations(SortedMap { data: [] }), undef_mask: UndefMask { blocks: [], len: Size { raw: 0 } }, size: Size { raw: 0 }, align: Align { pow2: 0 }, mutability: Not, extra: () }, offset: Size { raw: 0 } }: MyType>`

error[E0308]: mismatched types
  --> src/main.rs:10:14
   |
10 |     let _y = MyConst {};
   |              ^^^^^^^^^^ expected `ByRef { alloc: Allocation { bytes: [], relocations: Relocations(SortedMap { data: [] }), undef_mask: UndefMask { blocks: [], len: Size { raw: 0 } }, size: Size { raw: 0 }, align: Align { pow2: 0 }, mutability: Not, extra: () }, offset: Size { raw: 0 } }: MyType`, found `ByRef { alloc: Allocation { bytes: [], relocations: Relocations(SortedMap { data: [] }), undef_mask: UndefMask { blocks: [], len: Size { raw: 0 } }, size: Size { raw: 0 }, align: Align { pow2: 0 }, mutability: Not, extra: () }, offset: Size { raw: 0 } }: MyType`
   |
   = note: expected type `_`
            found struct `Const<ByRef { alloc: Allocation { bytes: [], relocations: Relocations(SortedMap { data: [] }), undef_mask: UndefMask { blocks: [], len: Size { raw: 0 } }, size: Size { raw: 0 }, align: Align { pow2: 0 }, mutability: Not, extra: () }, offset: Size { raw: 0 } }: MyType>`
```

This issue has been assigned to @lcnr via [this comment](https://github.com/rust-lang/rust/issues/68615#issuecomment-612364365).

### PR DESCRIPTION
**Pull request by lcnr**
fixes #68615

r? @eddyb

### CODE REVIEW

File: src/librustc_middle/ty/relate.rs [hunk 1]
```diff
@@ -559,7 +560,27 @@ pub fn super_relate_consts<R: TypeRelation<'tcx>>(
                     }
                 }
 
-                // FIXME(const_generics): handle `ConstValue::ByRef`.
+                (ConstValue::ByRef { .. }, ConstValue::ByRef { .. }) => {
+                    // `a` and `b` are already fully resolved, so we can
+                    // use `reveal_all` here.
+                    let param_env = ty::ParamEnv::reveal_all();
```
Comment (eddyb) [inline src/librustc_middle/ty/relate.rs:566]: You need to check `if !(a.ty, b.ty).has_param_types_or_consts()`, otherwise the layout could depend on e.g. a `*mut T` layout where `T: SIzed` is in the `ParamEnv`.

Oh but you have a `param_env` here. So why not use that?

File: src/test/ui/const-generics/different_byref.stderr [hunk 2]
```diff
@@ -0,0 +1,20 @@
...
+   = note: `#[warn(incomplete_features)]` on by default
+
+error[E0308]: mismatched types
+  --> $DIR/different_byref.rs:8:9
+   |
+LL |     x = Const::<{ [4] }> {};
+   |         ^^^^^^^^^^^^^^^^^^^ expected `3usize`, found `4usize`
+   |
+   = note: expected struct `Const<ByRef { alloc: Allocation { bytes: [3, 0, 0, 0, 0, 0, 0, 0], relocations: Relocations(SortedMap { data: [] }), undef_mask: UndefMask { blocks: [255], len: Size { raw: 8 } }, size: Size { raw: 8 }, align: Align { pow2: 3 }, mutability: Not, extra: () }, offset: Size { raw: 0 } }: [usize; 1]>`
+              found struct `Const<ByRef { alloc: Allocation { bytes: [4, 0, 0, 0, 0, 0, 0, 0], relocations: Relocations(SortedMap { data: [] }), undef_mask: UndefMask { blocks: [255], len: Size { raw: 8 } }, size: Size { raw: 8 }, align: Align { pow2: 3 }, mutability: Not, extra: () }, offset: Size { raw: 0 } }: [usize; 1]>`
```
Comment (eddyb) [inline src/test/ui/const-generics/different_byref.stderr:16]: I have a WIP branch where I make this print the actual values, I think we should wait for that, so that we can actually see it in action.

File: src/librustc_middle/ty/relate.rs [hunk 3]
```diff
@@ -559,7 +560,27 @@ pub fn super_relate_consts<R: TypeRelation<'tcx>>(
...
+                    let a_destructured = tcx.destructure_const(param_env.and(a));
+                    let b_destructured = tcx.destructure_const(param_env.and(b));
+
+                    // Both the variant and each field have to be equal.
+                    if a_destructured.variant == b_destructured.variant {
+                        for (a_field, b_field) in
+                            a_destructured.fields.iter().zip(b_destructured.fields.iter())
+                        {
+                            relation.consts(a_field, b_field)?;
```
Comment (eddyb) [inline src/librustc_middle/ty/relate.rs:575]: @oli-obk @matthewjasper What do you think of this use of `destructure_const`?

Comment (matthewjasper) [reply src/librustc_middle/ty/relate.rs:575]: `destructure_const` panics if the type isn't an array, adt or tuple, so it looks incorrect to not have a check on the type.

Comment (lcnr) [reply src/librustc_middle/ty/relate.rs:575]: it is. breaks with https://github.com/rust-lang/rust/issues/63322

currently working on this

File: src/test/ui/const-generics/different_byref.stderr (hunk 2 above)
Comment (lcnr) [reply src/test/ui/const-generics/different_byref.stderr:16]: :man_shrugging: don't think that waiting is worth it if this is otherwise ready.

File: src/librustc_middle/ty/relate.rs (hunk 1 above)
Comment (lcnr) [reply src/librustc_middle/ty/relate.rs:566]: isn't this impossible? Afaik const args cannot have a generic type

Comment (lcnr) [reply src/librustc_middle/ty/relate.rs:566]: I also don't know how to use `ParamEnv::new` as I am missing a useable `DefId`

File: src/test/ui/const-generics/different_byref.stderr (hunk 2 above)
Comment (eddyb) [reply src/test/ui/const-generics/different_byref.stderr:16]: It's not ready, because we can't read the error message.

File: src/librustc_middle/ty/relate.rs (hunk 3 above)
Comment (eddyb) [reply src/librustc_middle/ty/relate.rs:575]: It should allow closures as well, IMO, although I'm not sure closures should be considered structurally matcheable...

File: src/test/ui/const-generics/different_byref.stderr (hunk 2 above)
Comment (lcnr) [reply src/test/ui/const-generics/different_byref.stderr:16]: We already emit this error message rn. This PR only prevents correct programs from failing with the given error message.

File: src/librustc_middle/ty/relate.rs (hunk 3 above)
Comment (lcnr) [reply src/librustc_middle/ty/relate.rs]: Should be fixed, don't know if there are other types which have `ConstValue::ByRef` and should work rn.

Comment (eddyb) [reply src/librustc_middle/ty/relate.rs]: Oh yeah you can't have closures in a `const` type, so you can mark closures as not structurally matcheable.

Comment (eddyb) [reply src/librustc_middle/ty/relate.rs]: Wait, hang on, it can't be `ty::Closure`, maybe you were still talking about `dyn Trait`.

File: src/librustc_middle/ty/relate.rs [hunk 4]
```diff
@@ -559,7 +560,32 @@ pub fn super_relate_consts<R: TypeRelation<'tcx>>(
...
+                                {
+                                    relation.consts(a_field, b_field)?;
+                                }
+
+                                Ok(a_val)
+                            } else {
+                                Err(TypeError::ConstMismatch(expected_found(relation, &a, &b)))
+                            }
+                        }
+                        ty::Array(..) => bug!("ConstValue::ByRef for ty::Array"),
```
Comment (eddyb) [inline src/librustc_middle/ty/relate.rs:582]: Why? `destructure_const` supports arrays.

File: src/librustc_middle/ty/relate.rs (hunk 3 above)
Comment (lcnr) [reply src/librustc_middle/ty/relate.rs]: both examples in #63322 end up relying on `&dyn Trait` afaict

File: src/librustc_middle/ty/relate.rs (hunk 4 above)
Comment (lcnr) [reply src/librustc_middle/ty/relate.rs:582]: I might have done a upsie

Comment (lcnr) [reply src/librustc_middle/ty/relate.rs:582]: I somehow thought `ty::Array` gets evaluated to `ConstValue::Slice` :facepalm: 
fixed it

File: src/librustc_typeck/check/coercion.rs [hunk 5]
```diff
@@ -108,6 +108,7 @@ fn coerce_mutbls<'tcx>(
     }
 }
 
+/// Do not require any adjustments, i.e. coerce `x -> x`.
```
Comment (eddyb) [inline src/librustc_typeck/check/coercion.rs:111]: cc @nikomatsakis (comments are great but I'm not sure of the accuracy)

File: src/librustc_middle/ty/relate.rs [hunk 6]
```diff
@@ -559,7 +560,31 @@ pub fn super_relate_consts<R: TypeRelation<'tcx>>(
...
+                                }
+
+                                Ok(a_val)
+                            } else {
+                                Err(TypeError::ConstMismatch(expected_found(relation, &a, &b)))
+                            }
+                        }
+                        // FIXME(const_generics): There are probably some `TyKind`s
+                        // which should be handled here.
+                        _ => Err(TypeError::ConstMismatch(expected_found(relation, &a, &b))),
```
Comment (eddyb) [inline src/librustc_middle/ty/relate.rs:584]: I can't think of any, at least out of the types we allow. You should use at least `delay_span_bug`, because returning `Err` indicates that they're *definitely* not equal (which may allow e.g. overlapping `impl`s).

**Comment by eddyb** [comment]
Blocking on https://github.com/rust-lang/rust/pull/71018#discussion_r407064412.

File: src/librustc_middle/ty/relate.rs (hunk 6 above)
Comment (lcnr) [reply src/librustc_middle/ty/relate.rs:584]: :ok_hand: should `relate_consts` only be called for types which are structural match?

Is structural match implemented for `&`?

i.e. should this work
```rust
#![feature(const_generics)]

struct A<const N: &'static ()>;

fn main() {
    let _ = A::<{&()}>;
}
```

Comment (eddyb) [reply src/librustc_middle/ty/relate.rs]: Yes, it should, but it's blocked on one of @oli-obk's PRs.

File: src/librustc_typeck/check/coercion.rs (hunk 5 above)
Comment (nikomatsakis) [reply src/librustc_typeck/check/coercion.rs:111]: This comment seems correct, anyway

File: src/test/ui/const-generics/different_byref.stderr (hunk 2 above)
Comment (oli-obk) [reply src/test/ui/const-generics/different_byref.stderr:16]: This shouldn't be `ByRef`. The layout is `Scalar` for single element arrays, and all `Scalar` constants become `ConstValue::Scalar` in https://github.com/rust-lang/rust/blob/ba72b15666b2491415aec703a02c2364fe5e2790/src/librustc_mir/const_eval/eval_queries.rs#L109

Does this `ty::Const` not come from const eval?

Comment (eddyb) [reply src/test/ui/const-generics/different_byref.stderr:16]: > The layout is `Scalar` for single element arrays

Is it though? I don't remember this.

Comment (oli-obk) [reply src/test/ui/const-generics/different_byref.stderr:16]: Ah no, we just do this for tuples and structs. Slightly inconsistent, but :shrug:

Comment (eddyb) [reply src/test/ui/const-generics/different_byref.stderr:16]: That branch I mentioned is now a PR: #71232.

**Comment by crlf0710** [comment]
I think this is unblocked now since the fore-mentioned PR has been merged, maybe this will need a rebase?

**Comment by lcnr** [comment]
Should be ready for merge :sparkles:

**Review by oli-obk — APPROVED** [review]

File: src/test/ui/const-generics/different_byref.stderr [hunk 7]
```diff
@@ -0,0 +1,20 @@
...
+LL | #![feature(const_generics)]
+   |            ^^^^^^^^^^^^^^
+   |
+   = note: `#[warn(incomplete_features)]` on by default
+
+error[E0308]: mismatched types
+  --> $DIR/different_byref.rs:8:9
+   |
+LL |     x = Const::<{ [4] }> {};
+   |         ^^^^^^^^^^^^^^^^^^^ expected `3usize`, found `4usize`
```
Comment (oli-obk) [inline src/test/ui/const-generics/different_byref.stderr:13]: Only mildly related to this PR

@rust-lang/wg-const-eval we could consider collecting all spans that lead to a value during const eval and thus allow each byte in the final constant to have its own spans for diagnostics. Then we can report a sort of backtrace for values. Though I fear that will cause quite some overhead, even if we only need to do it in the current crate and not serialize it to metadata (so `ClearCrossCrate`).

Comment (eddyb) [reply src/test/ui/const-generics/different_byref.stderr:13]: That would be more advanced than what we do for type aliases, heh.

**Review by eddyb — APPROVED** [review]
