### PR TITLE
Overlap inherent impls

### LINKED ISSUE #94526: Nightly regression for `#![feature(with_negative_coherence)]`
[This branch](https://github.com/yoshuawuyts/rust/tree/future-for-termination-3) used to compile, and now ICEs. It seems recent change to our negative coherence impl have broken the implementation, causing the compiler to fail. Thanks!

r? @spastorino 

# Stacktrace
<details><pre>
thread 'rustc' panicked at 'called `Option::unwrap()` on a `None` value', compiler\rustc_trait_selection\src\traits\coherence.rs:312:60
stack backtrace:
   0: rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::panicking::panic
   3: rustc_trait_selection::traits::coherence::overlap_within_probe    
   4: rustc_trait_selection::traits::coherence::overlap_within_probe    
   5: <rustc_infer::infer::InferCtxt>::probe_maybe_skip_leak_check::<core::option::Option<rustc_trait_selection::traits::coherence::OverlapResult>, rustc_trait_selection::traits::coherence::overlap::{closure#0}>     
   6: rustc_trait_selection::traits::coherence::overlap
   7: RINvMs3_NtCsbBF8kn6qBh0_11rustc_infer5inferNtB6_16InferCtxtBuilder5enterbNCINvNtNtCsjf3HF1vxQx1_21rustc_trait_selection6traits9coherence17overlapping_implsNCNvMNtNtCs2iWJnhcUJwZ_12rustc_typeck9coherence22inherent_impls_overlapNtB2y_22InherentOverlapChecke
   8: rustc_trait_selection::traits::coherence::overlapping_impls::<<rustc_typeck::coherence::inherent_impls_overlap::InherentOverlapChecker>::check_for_overlapping_inherent_impls::{closure#0}, <rustc_typeck::coherence::inherent_impls_overlap::InherentOverlapChecker>::check_for_overlapping_inherent_impls::{closure#1}, bool>
   9: <rustc_typeck::coherence::inherent_impls_overlap::InherentOverlapChecker as rustc_hir::itemlikevisit::ItemLikeVisitor>::visit_item        
  10: <rustc_middle::hir::map::Map>::visit_all_item_likes::<rustc_typeck::coherence::inherent_impls_overlap::InherentOverlapChecker>
  11: rustc_typeck::coherence::inherent_impls_overlap::crate_inherent_impls_overlap_check
  12: RINvXNtCsf05yCjQpQCP_12rustc_middle9dep_graphNtNtB3_8dep_node7DepKindNtNtCslXmC8lPkVEE_18rustc_query_system9dep_graph7DepKind9with_depsNCINvMs1_NtB17_5graphINtB2i_8DepGraphBH_E14with_task_implNtNtNtB5_2ty7context6TyCtxtuuE0uECs1oIwRMkvWkL_16rustc_query_im
  13: <rustc_query_system::dep_graph::graph::DepGraph<rustc_middle::dep_graph::dep_node::DepKind>>::with_task::<rustc_middle::ty::context::TyCtxt, (), ()>
  14: rustc_data_structures::stack::ensure_sufficient_stack::<((), rustc_query_system::dep_graph::graph::DepNodeIndex), rustc_query_system::query::plumbing::execute_job<rustc_query_impl::plumbing::QueryCtxt, (), ()>::{closure#3}>
  15: <rustc_query_system::query::plumbing::QueryState<()> as core::default::Default>::default
  16: rustc_query_system::query::plumbing::get_query::<rustc_query_impl::queries::crate_inherent_impls_overlap_check, rustc_query_impl::plumbing::QueryCtxt>
  17: rustc_typeck::coherence::check_coherence
  18: <rustc_session::session::Session>::track_errors::<rustc_typeck::check_crate::{closure#3}, ()>
  19: rustc_typeck::check_crate
  20: rustc_interface::passes::analysis
  21: RINvXNtCsf05yCjQpQCP_12rustc_middle9dep_graphNtNtB3_8dep_node7DepKindNtNtCslXmC8lPkVEE_18rustc_query_system9dep_graph7DepKind9with_depsNCINvMs1_NtB17_5graphINtB2i_8DepGraphBH_E14with_task_implNtNtNtB5_2ty7context6TyCtxtuINtNtCscfKlVaPrZ4r_4core6option6Opt
  22: RINvMs1_NtNtCslXmC8lPkVEE_18rustc_query_system9dep_graph5graphINtB6_8DepGraphNtNtNtCsf05yCjQpQCP_12rustc_middle9dep_graph8dep_node7DepKindE9with_taskNtNtNtB1j_2ty7context6TyCtxtuINtNtCscfKlVaPrZ4r_4core6option6OptionNtNtNtCs6msPCmpuZaS_9rustc_ast6expand9a
  23: RINvNtCsdpB6R9UgN9W_21rustc_data_structures5stack23ensure_sufficient_stackTINtNtCscfKlVaPrZ4r_4core6result6ResultuNtCsajfgejFs79X_12rustc_errors13ErrorReportedENtNtNtCslXmC8lPkVEE_18rustc_query_system9dep_graph5graph12DepNodeIndexENCINvNtNtB2E_5query8plum
  24: <rustc_query_system::query::plumbing::QueryState<()> as core::default::Default>::default
  25: rustc_query_system::query::plumbing::get_query::<rustc_query_impl::queries::analysis, rustc_query_impl::plumbing::QueryCtxt>
  26: <rustc_interface::passes::QueryContext>::enter::<rustc_driver::run_compiler::{closure#1}::{closure#2}::{closure#3}, core::result::Result<(), rustc_errors::ErrorReported>>
  27: RINvMs2_NtCsce66lXUDp1Q_15rustc_interface7queriesNtNtB8_9interface8Compiler5enterNCNCNvCs6X6MaZoVTzA_12rustc_driver12run_compilers_0s0_0INtNtCscfKlVaPrZ4r_4core6result6ResultINtNtB2f_6option6OptionNtB6_6LinkerENtCsajfgejFs79X_12rustc_errors13ErrorReported
  28: RINvCs73LUM3RqK1O_10rustc_span15with_source_mapINtNtCscfKlVaPrZ4r_4core6result6ResultuNtCsajfgejFs79X_12rustc_errors13ErrorReportedENCINvNtCsce66lXUDp1Q_15rustc_interface9interface23create_compiler_and_runBJ_NCNvCs6X6MaZoVTzA_12rustc_driver12run_compilers
  29: rustc_interface::interface::create_compiler_and_run::<core::result::Result<(), rustc_errors::ErrorReported>, rustc_driver::run_compiler::{closure#1}>
  30: RINvMs_CshzKkicZQPlJ_10scoped_tlsINtB5_9ScopedKeyNtCs73LUM3RqK1O_10rustc_span14SessionGlobalsE3setNCINvNtCsce66lXUDp1Q_15rustc_interface9interface12run_compilerINtNtCscfKlVaPrZ4r_4core6result6ResultuNtCsajfgejFs79X_12rustc_errors13ErrorReportedENCNvCs6X6M
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md        

note: rustc 1.60.0-dev running on x86_64-pc-windows-msvc

note: compiler flags: --crate-type lib -C opt-level=3 -C embed-bitcode=no -C debuginfo=0 -C incremental -C symbol-mangling-version=legacy -Z unstable-options -Z macro-backtrace -C target-feature=+crt-static -C prefer-dynamic -C llvm-args=-import-instr-limit=10 -C embed-bitcode=yes -Z crate-attr=doc(html_root_url="https://doc.rust-lang.org/nightly/") -Z binary-dep-depinfo -Z force-unstable-if-unmarked

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [crate_inherent_impls_overlap_check] check for overlap between inherent impls defined in this crate
#1 [analysis] running analysis passes on this crate
end of query stack
error: could not compile `core`

Caused by:
  process didn't exit successfully: `D:\Code\rust\build\bootstrap/debug/rustc --crate-name core --edition=2021 library\core\src\lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --crate-type lib --emit=dep-info,metadata,link -C opt-level=3 -C embed-bitcode=no -C debuginfo=0 -C metadata=a73f3dcab1ae4e39 -C extra-filename=-a73f3dcab1ae4e39 --out-dir D:\Code\rust\build\x86_64-pc-windows-msvc\stage1-std\x86_64-pc-windows-msvc\release\deps --target x86_64-pc-windows-msvc -C incremental=D:\Code\rust\build\x86_64-pc-windows-msvc\stage1-std\x86_64-pc-windows-msvc\release\incremental -L dependency=D:\Code\rust\build\x86_64-pc-windows-msvc\stage1-std\x86_64-pc-windows-msvc\release\deps 
-L dependency=D:\Code\rust\build\x86_64-pc-windows-msvc\stage1-std\release\deps -Csymbol-mangling-version=legacy -Zunstable-options -Zmacro-backtrace -Ctarget-feature=+crt-static -Cprefer-dynamic -Cllvm-args=-import-instr-limit=10 -Cembed-bitcode=yes "-Zcrate-attr=doc(html_root_url=\"https://doc.rust-lang.org/nightly/\")" -Z binary-dep-depinfo` (exit code: 0x80000003)
Build completed unsuccessfully in 0:05:35
</pre>
</details>

### PR DESCRIPTION
**Pull request by spastorino**
r? @nikomatsakis 

Closes #94526

### CODE REVIEW

File: compiler/rustc_trait_selection/src/traits/coherence.rs [hunk 1]
```diff
@@ -300,60 +302,84 @@ fn negative_impl<'cx, 'tcx>(
...
-        let impl2_substs = infcx.fresh_substs_for_item(DUMMY_SP, impl2_def_id);
-        let (impl2_trait_ref, obligations) =
-            impl_trait_ref_and_oblig(selcx, impl1_env, impl2_def_id, impl2_substs);
-
-        // do the impls unify? If not, not disjoint.
-        let Ok(InferOk { obligations: more_obligations, .. }) = infcx
-            .at(&ObligationCause::dummy(), impl1_env)
-            .eq(impl1_trait_ref, impl2_trait_ref)
-        else {
+fn obligations_satisfiable<'cx, 'tcx, T: Debug + ToTrace<'tcx>>(
```
Comment (spastorino) [inline compiler/rustc_trait_selection/src/traits/coherence.rs:349]: I kind of dislike this abstraction, the other thing I could do is kind of the opposite, have a function returning 2 `T: ToTrace` and obligations from traits or empty otherwise and then rollup all obligations_satisfiable code inside `negative_impl`.

File: compiler/rustc_trait_selection/src/traits/coherence.rs [hunk 2]
```diff
@@ -300,60 +302,84 @@ fn negative_impl<'cx, 'tcx>(
...
-        ) {
-            Ok(impl1_trait_ref) => impl1_trait_ref,
-            Err(err) => {
-                bug!("failed to fully normalize {:?}: {:?}", impl1_trait_ref, err);
-            }
-        };
+        // create a parameter environment corresponding to a (placeholder) instantiation of impl1
+        let impl1_env = tcx.param_env(impl1_def_id);
+
+        if let Some(impl1_trait_ref) = tcx.impl_trait_ref(impl1_def_id) {
```
Comment (nikomatsakis) [inline compiler/rustc_trait_selection/src/traits/coherence.rs:310]: I was suggesting on Zulip that we have

```rust
pub enum ImplHeader<'tcx> {
    Trait(TraitRef<'tcx>),
    Inherent(Ty<'tcx>)
}
```

and then a method on tcx that returns one or the other. You could then implement foldable and the like for that. This would allow you to just unify them.

Comment (spastorino) [reply compiler/rustc_trait_selection/src/traits/coherence.rs:310]: Yeah, that's a cool way to do what I was saying in https://github.com/rust-lang/rust/pull/95082#discussion_r830206485

Comment (spastorino) [reply compiler/rustc_trait_selection/src/traits/coherence.rs]: I've added an enum in https://github.com/rust-lang/rust/pull/95082/commits/0cd03c917cd728844048edb41a3d30d414214ad8 but I'm pretty sure that commit is not what you want. The problem is that we need to process those 2 def_ids and return `T: ToTrace` and an iter for obligations. I could have a function that returns those and then inline what right now lives in `equate`.

File: compiler/rustc_middle/src/hir/mod.rs [hunk 3]
```diff
@@ -54,6 +54,12 @@ impl<'tcx> TyCtxt<'tcx> {
     pub fn parent_module(self, id: HirId) -> LocalDefId {
         self.parent_module_from_def_id(id.owner)
     }
+
+    pub fn impl_header(self, def_id: DefId) -> ImplSubject<'tcx> {
```
Comment (nikomatsakis) [inline compiler/rustc_middle/src/hir/mod.rs:58]:
```suggestion
    pub fn impl_subject(self, def_id: DefId) -> ImplSubject<'tcx> {
```

File: compiler/rustc_trait_selection/src/traits/coherence.rs [hunk 4]
```diff
@@ -307,46 +307,47 @@ fn negative_impl<'cx, 'tcx>(
...
-                impl1_trait_ref,
-                impl2_trait_ref,
-                obligations,
-            )
-        } else {
-            let ty1 = tcx.type_of(impl1_def_id);
-            let ty2 = tcx.type_of(impl2_def_id);
-
-            !obligations_satisfiable(&infcx, impl1_env, impl1_def_id, ty1, ty2, iter::empty())
+        match tcx.impl_header(impl1_def_id) {
```
Comment (nikomatsakis) [inline compiler/rustc_trait_selection/src/traits/coherence.rs:310]:
```suggestion
        match tcx.impl_subject(impl1_def_id) {
```

File: compiler/rustc_trait_selection/src/traits/coherence.rs [hunk 5]
```diff
@@ -307,46 +307,47 @@ fn negative_impl<'cx, 'tcx>(
...
+            ImplSubject::Inherent(ty1) => {
+                let ty2 = tcx.type_of(impl2_def_id);
+                !equate(&infcx, impl1_env, impl1_def_id, ty1, ty2, iter::empty())
+            }
         }
     })
 }
 
-fn obligations_satisfiable<'cx, 'tcx, T: Debug + ToTrace<'tcx>>(
+fn equate<'cx, 'tcx, T: Debug + ToTrace<'tcx>>(
```
Comment (nikomatsakis) [inline compiler/rustc_trait_selection/src/traits/coherence.rs:350]: I was imagining this not taking a `T` but rather taking two `ImplSubject<'tcx>` arguments.

File: compiler/rustc_trait_selection/src/traits/coherence.rs [hunk 6]
```diff
@@ -307,46 +307,47 @@ fn negative_impl<'cx, 'tcx>(
...
-                impl2_trait_ref,
-                obligations,
-            )
-        } else {
-            let ty1 = tcx.type_of(impl1_def_id);
-            let ty2 = tcx.type_of(impl2_def_id);
-
-            !obligations_satisfiable(&infcx, impl1_env, impl1_def_id, ty1, ty2, iter::empty())
+        match tcx.impl_header(impl1_def_id) {
+            ImplSubject::Trait(impl1_trait_ref) => {
```
Comment (nikomatsakis) [inline compiler/rustc_trait_selection/src/traits/coherence.rs:311]: I was imagining this code being:

```rust
let subject1 = tcx.impl_subject(impl1_def_id);
let subject1 = match traits::fully_normalize(...);

let subject2 = tcx.impl_subject(impl2_def_id);
...

equate...
```

i.e., no more match etc

**Review by nikomatsakis — CHANGES_REQUESTED** [review]

File: compiler/rustc_trait_selection/src/traits/coherence.rs [hunk 7]
```diff
@@ -300,60 +301,85 @@ fn negative_impl<'cx, 'tcx>(
...
+                    impl1_trait_ref,
+                ) {
+                    Ok(impl1_trait_ref) => ImplSubject::Trait(impl1_trait_ref),
+                    Err(err) => {
+                        bug!("failed to fully normalize {:?}: {:?}", impl1_trait_ref, err);
+                    }
+                }
             }
+            subject @ ImplSubject::Inherent(_) => subject,
         };
```
Comment (nikomatsakis) [inline compiler/rustc_trait_selection/src/traits/coherence.rs:324]: Actually I suspect we want this:

```suggestion
        let subject1 = match match traits::fully_normalize(
                &infcx,
                FulfillmentContext::new(),
                ObligationCause::dummy(),
                impl_env,
                tcx.impl_subject(impl1_def_id),
        ) {
                Ok(s) => s,
                Err(err) => bug!("failed to fully normalize {:?}: {:?}", impl1_def_id, err),
        };
```

i.e., it can't hurt to normalize the "inherent" case too, in case there's something like `impl Foo<<vec::IntoIter<u32> as Iterator>::Item>`

File: compiler/rustc_trait_selection/src/traits/coherence.rs [hunk 8]
```diff
@@ -300,60 +301,85 @@ fn negative_impl<'cx, 'tcx>(
...
-        };
+            impl_trait_ref_and_oblig(selcx, impl_env, impl2_def_id, impl2_substs);
 
-        let opt_failing_obligation = obligations
-            .into_iter()
-            .chain(more_obligations)
-            .find(|o| negative_impl_exists(selcx, impl1_env, impl1_def_id, o));
+        (ImplSubject::Trait(impl2_trait_ref), Box::new(obligations))
+    } else {
+        (infcx.tcx.impl_subject(impl2_def_id), Box::new(iter::empty()))
```
Comment (nikomatsakis) [inline compiler/rustc_trait_selection/src/traits/coherence.rs:348]: hmm, I *think* it can have obligations, e.g.

```rust
impl<T> Vec<T>
where
    T: Ord,
```

would need `T: Ord`.

**Review by nikomatsakis — CHANGES_REQUESTED** [review]
Getting closer. Can be simpler still!

File: compiler/rustc_trait_selection/src/traits/coherence.rs (hunk 8 above)
Comment (spastorino) [reply compiler/rustc_trait_selection/src/traits/coherence.rs:348]: Aren't those filled in here https://github.com/rust-lang/rust/pull/95082/files#diff-8d9bb4ed968c5734cb6004b14afb6e7652d192f6db4a5fa9758c7d9abc05d7f8R371 ?

Comment (nikomatsakis) [reply compiler/rustc_trait_selection/src/traits/coherence.rs:341]: Actually, no, those are different. Those obligations are obligations that arise as a side-effect of equating two types, not the where clauses from the impl. But before you make any change here we should be able to create a test.

Comment (spastorino) [reply compiler/rustc_trait_selection/src/traits/coherence.rs]: Fixed.

**Review by nikomatsakis — APPROVED** [review]
