### PR TITLE
Fix incorrect suggestion for undeclared hrtb lifetimes in where clauses.

### LINKED ISSUE #122714: suggested fix for undeclared hrtb lifetimes in where clauses in produces error "[E0316] nested quantification of lifetimes" when specified just before the trait
### Code

```Rust
trait Trait<T>
  where T: for<'a> Trait<T> + 'b { }
```

### Current output

```Shell
error[E0261]: use of undeclared lifetime name `'b`
 --> src/lib.rs:2:31
  |
2 |   where T: for<'a> Trait<T> + 'b { }
  |                               ^^ undeclared lifetime
  |
  = note: for more information on higher-ranked polymorphism, visit https://doc.rust-lang.org/nomicon/hrtb.html
help: consider making the bound lifetime-generic with a new `'b` lifetime
  |
2 |   where for<'b> T: for<'a> Trait<T> + 'b { }
  |         +++++++
help: consider introducing lifetime `'b` here
  |
1 | trait Trait<'b, T>
  |             +++
```

### Desired output

```Shell
error[E0261]: use of undeclared lifetime name `'b`
 --> src/lib.rs:2:31
  |
2 |   where T: for<'a> Trait<T> + 'b { }
  |                               ^^ undeclared lifetime
  |
  = note: for more information on higher-ranked polymorphism, visit https://doc.rust-lang.org/nomicon/hrtb.html
help: consider making the bound lifetime-generic with a new `'b` lifetime
  |
2 |   where T: for<'a, 'b> Trait<T> + 'b { }
  |                  ++++
help: consider introducing lifetime `'b` here
  |
1 | trait Trait<'b, T>
  |             +++
```

### Rationale and extra context

HRTB lifetimes can be put not only before the constrained type (`for<...> T: ...`), but also just before the constraining trait (`T: for<...> Trait ...`). When in this position, compiler suggests code which produces error "[E0316] nested quantification of lifetimes" as it ignores the existing HRTB just before the trait and only looks at constraint HRTB.

### Other cases

_No response_

### Rust Version

```Shell
$ rustc --version --verbose
rustc 1.76.0 (07dca489a 2024-02-04)
binary: rustc
commit-hash: 07dca489ac2d933c78d3c5158e3f43beefeb02ce
commit-date: 2024-02-04
host: aarch64-apple-darwin
release: 1.76.0
LLVM version: 17.0.6
```

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by surechen**
For poly-trait-ref like `for<'a> Trait<T>`   in  `T: for<'a> Trait<T> + 'b { }`.
We should merge the hrtb lifetimes: existed `for<'a>` and suggestion `for<'b>` or will get err: [E0316] nested quantification of lifetimes

fixes #122714

### CODE REVIEW

File: compiler/rustc_resolve/src/late.rs [hunk 1]
```diff
@@ -693,6 +700,9 @@ struct LateResolutionVisitor<'a, 'b, 'ast, 'tcx> {
 
     /// Count the number of places a lifetime is used.
     lifetime_uses: FxHashMap<LocalDefId, LifetimeUseSet>,
+
+    /// Record poly-trait-ref, only used for diagnostic.
+    with_poly_trait_ref: FxHashMap<NodeId, RedundantPolyTraitRef>,
```
Comment (fmease) [inline compiler/rustc_resolve/src/late.rs:705]: Don't know if this is possible, I'm on mobile rn and don't remember the details of name resolution off the top of my head but instead of equipping the late resolution visitor with extra data can't we just look at the preexisting `lifetime_ribs` and find the innermost `LifetimeRib` whose kind is `LifetimeRibKind::Generics { kind: LifetimeBinderKind::WhereClause, ..}`? I'm assuming here that `WhereClause` refers to the “outer binder” / the binder arching over the entire bound (whereas `LifetimeBinderKind::PolyTrait` refers to the “inner binder” which isn't what we want as outlined in the issue).

File: compiler/rustc_resolve/src/late/diagnostics.rs [hunk 2]
```diff
@@ -2750,14 +2751,53 @@ impl<'a: 'ast, 'ast, 'tcx> LateResolutionVisitor<'a, '_, 'ast, 'tcx> {
...
+                                self.with_poly_trait_ref.get(&node_id)
+                                && higher_ranked
+                            {
+                                debug!("surechen1 with_poly_trait_ref:{:?}", with_poly_trait_ref);
+                                let mut generic_params = with_poly_trait_ref
+                                    .generic_param_idents
+                                    .iter()
+                                    .fold("".to_string(), |mut generic_params, x| {
+                                        generic_params += x.as_str();
+                                        generic_params += ",";
```
Comment (fmease) [inline compiler/rustc_resolve/src/late/diagnostics.rs:2767]:
```suggestion
                                        generic_params += ", ";
```

Comment (surechen) [reply compiler/rustc_resolve/src/late/diagnostics.rs]: > 

Done. Thank you.

File: compiler/rustc_resolve/src/late.rs [hunk 3]
```diff
@@ -4702,6 +4714,39 @@ impl<'a: 'ast, 'b, 'ast, 'tcx> LateResolutionVisitor<'a, 'b, 'ast, 'tcx> {
...
+            bounded_ty,
+            bounds,
+            ..
+        }) = p
+        {
+            for bound in bounds {
+                if let ast::GenericBound::Trait(
+                    ast::PolyTraitRef {
+                        span: poly_span,
+                        trait_ref: ast::TraitRef { path: ast::Path { span, .. }, .. },
```
Comment (oli-obk) [inline compiler/rustc_resolve/src/late.rs:4729]: style nit for the future: when you have a struct, prefer using `trait_ref.path.span` instead of destructuring one field

File: compiler/rustc_resolve/src/late/diagnostics.rs [hunk 4]
```diff
@@ -2750,14 +2751,43 @@ impl<'a: 'ast, 'ast, 'tcx> LateResolutionVisitor<'a, '_, 'ast, 'tcx> {
...
+                                )
+                            } else {
+                                ("".to_string(), DUMMY_SP, DUMMY_SP)
+                            };
+
+                        let rm_poly_trait_span = if generic_params.is_empty() {
+                            DUMMY_SP
+                        } else {
+                            poly_trait_span.with_hi(trait_ref_span.lo())
+                        };
```
Comment (oli-obk) [inline compiler/rustc_resolve/src/late/diagnostics.rs:2782]: if you use `rm_poly_trait_span` where you use `span` right now, you don't need to change any of the follow-up code, as you'd be replacing the old binder instead of generating a new one before the type.

File: compiler/rustc_resolve/src/late.rs (hunk 3 above)
Comment (surechen) [reply compiler/rustc_resolve/src/late.rs]: > style nit for the future: when you have a struct, prefer using `trait_ref.path.span` instead of destructuring one field

Done. Thank you.

File: compiler/rustc_resolve/src/late/diagnostics.rs (hunk 4 above)
Comment (surechen) [reply compiler/rustc_resolve/src/late/diagnostics.rs]: > if you use `rm_poly_trait_span` where you use `span` right now, you don't need to change any of the follow-up code, as you'd be replacing the old binder instead of generating a new one before the type.

Thank you. I need both rm_poly_trait_span and  span. But this code I wrote is indeed redundant and unclear. I simplified it.

File: compiler/rustc_resolve/src/late/diagnostics.rs [hunk 5]
```diff
@@ -2750,32 +2751,68 @@ impl<'a: 'ast, 'ast, 'tcx> LateResolutionVisitor<'a, '_, 'ast, 'tcx> {
...
                             kind.descr(),
                             name.unwrap_or("'a"),
                         ));
-                        should_continue = suggest(err, true, span, message, sugg);
+                        should_continue = if !rm_poly_trait_span.is_dummy() {
+                            // For poly-trait-ref like `for<'a> Trait<T>` in
+                            // `T: for<'a> Trait<T> + 'b { }`.
+                            // We should merge the higher-ranked lifetimes: existed `for<'a>` and suggestion `for<'b>`
+                            // or will get err:
+                            // `[E0316] nested quantification of lifetimes`.
```
Comment (oli-obk) [inline compiler/rustc_resolve/src/late/diagnostics.rs:2806]: Ah I see now. Because 

```
T: for<'b> Trait<T> + 'b
```

doesn't make sense, as the `+ 'b` is not part of the `for<'b> Trait<T>`

Please document what is being removed and what is being added.

Comment (surechen) [reply compiler/rustc_resolve/src/late/diagnostics.rs]: Done. Thank you.

File: compiler/rustc_resolve/src/late.rs [hunk 6]
```diff
@@ -4702,6 +4714,31 @@ impl<'a: 'ast, 'b, 'ast, 'tcx> LateResolutionVisitor<'a, 'b, 'ast, 'tcx> {
             });
         }
     }
+
+    fn record_where_bound_predicate_with_poly_trait(&mut self, p: &WherePredicate) {
+        if let ast::WherePredicate::BoundPredicate(ast::WhereBoundPredicate {
+            bounded_ty,
+            bounds,
+            ..
+        }) = p
```
Comment (fmease) [inline compiler/rustc_resolve/src/late.rs:4723]: you could use `let`/`else { return };` here to avoid rightward drift

File: compiler/rustc_resolve/src/late.rs [hunk 7]
```diff
@@ -4702,6 +4714,31 @@ impl<'a: 'ast, 'b, 'ast, 'tcx> LateResolutionVisitor<'a, 'b, 'ast, 'tcx> {
...
+        {
+            for bound in bounds {
+                if let ast::GenericBound::Trait(poly_trait_ref, _) = bound {
```
Comment (fmease) [inline compiler/rustc_resolve/src/late.rs:4726]: you could use `let`/`else { continue };` here to avoid rightward drift

File: compiler/rustc_resolve/src/late/diagnostics.rs [hunk 8]
```diff
@@ -2750,32 +2751,69 @@ impl<'a: 'ast, 'ast, 'tcx> LateResolutionVisitor<'a, '_, 'ast, 'tcx> {
...
+
                     if higher_ranked {
                         let message = Cow::from(format!(
                             "consider making the {} lifetime-generic with a new `{}` lifetime",
                             kind.descr(),
                             name.unwrap_or("'a"),
                         ));
-                        should_continue = suggest(err, true, span, message, sugg);
+                        should_continue = if !rm_poly_trait_span.is_dummy() {
+                            // We should merge the higher-ranked lifetimes in following situation:
```
Comment (fmease) [inline compiler/rustc_resolve/src/late/diagnostics.rs:2802]: Wording:

```suggestion
                            // We should merge binders in following situation:
```

Explanation: For me, “merging […] lifetimes” means replacing two previously distinct lifetimes with a single new one, so `'a, 'b => 'c`. Of course, it's relatively clear from context what's actually meant here but still I feel like we should use the more precise phrasing. Merging *binders* is `for<'a>, for<'b> => for<'a, 'b>`.

*Binder* is indeed jargon but so is higher-ranked lifetime.

File: compiler/rustc_resolve/src/late/diagnostics.rs [hunk 9]
```diff
@@ -2750,32 +2751,69 @@ impl<'a: 'ast, 'ast, 'tcx> LateResolutionVisitor<'a, '_, 'ast, 'tcx> {
...
+                            // Change `T: for<'a> Trait<T> + 'b` to `for<'a, 'b> T: Trait<T> + 'b`
+                            // T: for<'a> Trait<T> + 'b
+                            //    ^^^^^^^  remove existed `for<'a>`
```
Comment (fmease) [inline compiler/rustc_resolve/src/late/diagnostics.rs:2805]:
```suggestion
                            //    ^^^^^^^  remove existing `for<'a>`
```

Comment (fmease) [reply compiler/rustc_resolve/src/late/diagnostics.rs:2805]: or even

```suggestion
                            //    ^^^^^^^  remove existing inner binder `for<'a>`
```

File: compiler/rustc_resolve/src/late/diagnostics.rs [hunk 10]
```diff
@@ -2750,32 +2751,69 @@ impl<'a: 'ast, 'ast, 'tcx> LateResolutionVisitor<'a, '_, 'ast, 'tcx> {
...
+                            // for<'a, 'b> T: Trait<T> + 'b
+                            // ^^^^^^^^^^^  add suggestion `for<'a, 'b>`
```
Comment (fmease) [inline compiler/rustc_resolve/src/late/diagnostics.rs:2807]:
```suggestion
                            // ^^^^^^^^^^^  suggest outer binder `for<'a, 'b>`
```

**Review by fmease — CHANGES_REQUESTED** [review]

File: compiler/rustc_resolve/src/late/diagnostics.rs (hunk 8 above)
Comment (fmease) [reply compiler/rustc_resolve/src/late/diagnostics.rs:2802]: To make it more accessible we could clarify *binder* inline by saying `... binders (`for<>` param list) ...` or `... binders (list of higher-ranked generic params) ...`, dunno.

File: compiler/rustc_resolve/src/late/diagnostics.rs (hunk 9 above)
Comment (surechen) [reply compiler/rustc_resolve/src/late/diagnostics.rs]: > 

Done. Thank you.

File: compiler/rustc_resolve/src/late/diagnostics.rs (hunk 10 above)
Comment (surechen) [reply compiler/rustc_resolve/src/late/diagnostics.rs]: > or even “overarching outer binder”

Done. Thank you.

File: compiler/rustc_resolve/src/late.rs (hunk 1 above)
[the remark this answers is not in the document]
Comment (fmease) [reply compiler/rustc_resolve/src/late.rs:705]: More concretely, I'm wondering if instead of an extra field would it be possible to do something similar to https://github.com/rust-lang/rust/blob/b3bd7058c139e71bae0862ef8f8ac936208873e9/compiler/rustc_resolve/src/late/diagnostics.rs#L3161-L3163 where all the logic happens inside the `callback`. It might not be possible to do :thinking:

File: compiler/rustc_resolve/src/late/diagnostics.rs [hunk 11]
```diff
@@ -2750,32 +2751,69 @@ impl<'a: 'ast, 'ast, 'tcx> LateResolutionVisitor<'a, '_, 'ast, 'tcx> {
...
                             .sess
                             .source_map()
                             .span_through_char(span, '<')
                             .shrink_to_hi();
-                        let sugg = format!("{}, ", name.unwrap_or("'a"));
-                        (span, sugg)
-                    };
+                    }
+
                     if higher_ranked {
```
Comment (fmease) [inline compiler/rustc_resolve/src/late/diagnostics.rs:2795]: At the moment you add the suggestion if `higher_ranked` (etc.) but I *think* we should only do it if `kind` matches `WhereBound`. This might matter for code like:

```rs
trait Trait<T>
where
    T: B<'b> + for<'a> A<'a>,
{
}

trait A<'a> {}
trait B<'a> {}
```

Where we have 3 possible lifetime ribs to attach a lifetime to: `PolyTrait` followed by `WhereBound` followed by `Item`.

For reference, master emits the following 3 suggestions:

* `T: for<'b> B<'b> + for<'a> A<'a>,` OK (`PolyTrait`)
* `for<'b> T: B<'b> + for<'a> A<'a>,` BAD (nested quantifiers) (`WhereBound`)
* `trait Trait<'b, T>` OK (`Item`)

Could you check if your PR handles this code correctly? You likely only get a *single* suggestion (since you set `should_continue` to `false`), namely the `PolyTrait` one. I wonder if the `PolyTrait` one is still correct.

**Review by fmease — CHANGES_REQUESTED** [review]
Apologies for the delay! I've potentially found some smaller issues. Furthermore, I'm not super convinced by the current approach which adds an entirely new field to the resolver just to fix a niche diagnostic bug. I go into more detail in some of my review comments.

**Comment by surechen** [comment]
> Apologies for the delay! I've potentially found some smaller issues. Furthermore, I'm not super convinced by the current approach which adds an entirely new field to the resolver just to fix a niche diagnostic bug. I go into more detail in some of my review comments.

Thank you very much. Your review is very detailed and helps me a lot. I will spend some time processing it.

File: compiler/rustc_resolve/src/late.rs (hunk 1 above)
[the remark this answers is not in the document]
Comment (surechen) [reply compiler/rustc_resolve/src/late.rs]: Done. Thank you. I find self.diag_metadata.current_where_predicate has this information.

File: compiler/rustc_resolve/src/late/diagnostics.rs [hunk 12]
```diff
@@ -2750,32 +2751,69 @@ impl<'a: 'ast, 'ast, 'tcx> LateResolutionVisitor<'a, '_, 'ast, 'tcx> {
...
+                            // T: for<'a> Trait<T> + 'b
+                            //    ^^^^^^^  remove existing inner binder `for<'a>`
+                            // for<'a, 'b> T: Trait<T> + 'b
+                            // ^^^^^^^^^^^  suggest outer binder `for<'a, 'b>`
+                            err.multipart_suggestion_verbose(
+                                message,
+                                vec![(span, sugg), (rm_poly_trait_span, "".to_string())],
+                                Applicability::MaybeIncorrect,
+                            );
+                            false
```
[the remark this answers is not in the document]
Comment (surechen) [reply compiler/rustc_resolve/src/late/diagnostics.rs]: Done. Thank you.

[the remark this answers is not in the document]
Comment (surechen) [reply compiler/rustc_resolve/src/late/diagnostics.rs]: Done. Thank you.

File: compiler/rustc_resolve/src/late/diagnostics.rs [hunk 13]
```diff
@@ -2750,32 +2751,69 @@ impl<'a: 'ast, 'ast, 'tcx> LateResolutionVisitor<'a, '_, 'ast, 'tcx> {
...
+                                |mut generic_params, x| {
+                                    generic_params += x.as_str();
+                                    generic_params += ", ";
+                                    generic_params
+                                },
+                            );
+                            if !generic_params.is_empty() {
+                                rm_poly_trait_span = with_poly_trait_ref
+                                    .poly_trait
+                                    .with_hi(with_poly_trait_ref.trait_ref.lo());
```
[the remark this answers is not in the document]
Comment (surechen) [reply compiler/rustc_resolve/src/late/diagnostics.rs]: Done. Thank you.

File: compiler/rustc_resolve/src/late.rs [hunk 14]
```diff
@@ -4702,6 +4714,30 @@ impl<'a: 'ast, 'b, 'ast, 'tcx> LateResolutionVisitor<'a, 'b, 'ast, 'tcx> {
...
+            bounded_ty,
+            bounds,
+            ..
+        }) = p
+        else {
+            return;
+        };
+        for bound in bounds {
+            let ast::GenericBound::Trait(poly_trait_ref, _) = bound else { continue };
+            let names = poly_trait_ref.bound_generic_params.iter().map(|v| v.ident).collect();
```
[the remark this answers is not in the document]
Comment (surechen) [reply compiler/rustc_resolve/src/late.rs]: Done. Thank you.

File: compiler/rustc_resolve/src/late/diagnostics.rs [hunk 15]
```diff
@@ -2711,8 +2713,12 @@ impl<'a: 'ast, 'ast, 'tcx> LateResolutionVisitor<'a, '_, 'ast, 'tcx> {
...
             &mut err,
             Some(lifetime_ref.ident.name.as_str()),
-            |err, _, span, message, suggestion| {
-                err.span_suggestion(span, message, suggestion, Applicability::MaybeIncorrect);
+            |err, _, span, message, suggestion, span_suggs| {
+                err.multipart_suggestion_verbose(
+                    message,
+                    std::iter::once((span, suggestion)).chain(span_suggs.iter().cloned()).collect(),
+                    Applicability::MaybeIncorrect,
+                );
```
Comment (fmease) [inline compiler/rustc_resolve/src/late/diagnostics.rs:2721]: Since `span_suggestion` was changed to `multipart_suggestion_verbose`, this has lead to output changing in a lot of other scenarios that aren't strictly related to the inner/outer binder change as can be seen by all the UI tests you had to `--bless`.

Using the *verbose* style unconditionally isn't bad per se. However, I wonder if we could keep the non-verbose style if possible?

What happens if you just use `multipart_suggestion`? If the output isn't good in the inner/outer binder case, we could think about making the suggestion only verbose if we suggest removing inner binders:

```rs
let style = if span_suggs.is_empty() { SuggestionStyle::ShowCode } else { SuggestionStyle::ShowAlways };
err.multipart_suggestion_with_style(/*...*/, style);
```

**Review by fmease — APPROVED** [review]
Thanks a lot, that looks great! :heart: I apologize for taking so long (yet again!) :disappointed:.

Almost ready, I have a couple of small suggestions. Then I will put into the merge queue!

File: compiler/rustc_resolve/src/late/diagnostics.rs [hunk 16]
```diff
@@ -2758,11 +2771,58 @@ impl<'a: 'ast, 'ast, 'tcx> LateResolutionVisitor<'a, '_, 'ast, 'tcx> {
...
                     );
+
+                    let mut rm_inner_binders: FxIndexSet<Span> = Default::default();
                     let (span, sugg) = if span.is_empty() {
+                        let mut binder_idents: FxIndexSet<Ident> = Default::default();
+                        binder_idents.insert(if let Some(name) = name {
+                            Ident::from_str(name)
+                        } else {
+                            Ident::from_str("'a")
+                        });
```
[the remark this answers is not in the document]
Comment (surechen) [reply compiler/rustc_resolve/src/late/diagnostics.rs]: Done. Thank you.

File: compiler/rustc_resolve/src/late/diagnostics.rs [hunk 17]
```diff
@@ -2758,11 +2771,58 @@ impl<'a: 'ast, 'ast, 'tcx> LateResolutionVisitor<'a, '_, 'ast, 'tcx> {
...
+                        // Change `T: for<'a> Trait<T> + 'b` to `for<'a, 'b> T: Trait<T> + 'b`
+                        // T: for<'a> Trait<T> + 'b
+                        //    ^^^^^^^  remove existing inner binder `for<'a>`
+                        // for<'a, 'b> T: Trait<T> + 'b
+                        // ^^^^^^^^^^^  suggest outer binder `for<'a, 'b>`
+                        if let LifetimeBinderKind::WhereBound = kind
+                            && let Some(ast::WherePredicate::BoundPredicate(
+                                ast::WhereBoundPredicate { bounded_ty, bounds, .. },
+                            )) = self.diag_metadata.current_where_predicate
+                            && bounded_ty.node_id() == node_id
```
[the remark this answers is not in the document]
Comment (surechen) [reply compiler/rustc_resolve/src/late/diagnostics.rs]: Done. Thank you.

File: compiler/rustc_resolve/src/late/diagnostics.rs [hunk 18]
```diff
@@ -2758,11 +2771,58 @@ impl<'a: 'ast, 'ast, 'tcx> LateResolutionVisitor<'a, '_, 'ast, 'tcx> {
...
+                        let binders_sugg = binder_idents.into_iter().enumerate().fold(
+                            "".to_string(),
+                            |mut binders, (i, x)| {
+                                binders += x.as_str();
+                                if i != len - 1 {
+                                    binders += ", ";
+                                }
+                                binders
+                            },
+                        );
```
[the remark this answers is not in the document]
Comment (surechen) [reply compiler/rustc_resolve/src/late/diagnostics.rs]: Done. Thank you.

File: compiler/rustc_resolve/src/late/diagnostics.rs (hunk 15 above)
Comment (surechen) [reply compiler/rustc_resolve/src/late/diagnostics.rs]: Done. Thank you.

File: compiler/rustc_resolve/src/late/diagnostics.rs [hunk 19]
```diff
@@ -2777,24 +2837,39 @@ impl<'a: 'ast, 'ast, 'tcx> LateResolutionVisitor<'a, '_, 'ast, 'tcx> {
...
                             name.unwrap_or("'a"),
                         ));
-                        should_continue = suggest(err, true, span, message, sugg);
+                        should_continue = suggest(
+                            err,
+                            true,
+                            span,
+                            message,
+                            sugg,
+                            &if rm_inner_binders.len() > 0 {
```
[the remark this answers is not in the document]
Comment (surechen) [reply compiler/rustc_resolve/src/late/diagnostics.rs]: Done. Thank you.

File: compiler/rustc_resolve/src/late/diagnostics.rs [hunk 20]
```diff
@@ -2758,11 +2771,58 @@ impl<'a: 'ast, 'ast, 'tcx> LateResolutionVisitor<'a, '_, 'ast, 'tcx> {
...
+                                    binders += ", ";
+                                }
+                                binders
+                            },
+                        );
                         let sugg = format!(
                             "{}<{}>{}",
                             if higher_ranked { "for" } else { "" },
-                            name.unwrap_or("'a"),
+                            format!("{}", binders_sugg),
```
[the remark this answers is not in the document]
Comment (surechen) [reply compiler/rustc_resolve/src/late/diagnostics.rs]: Done. Thank you.

File: compiler/rustc_resolve/src/late/diagnostics.rs [hunk 21]
```diff
@@ -2723,13 +2729,20 @@ impl<'a: 'ast, 'ast, 'tcx> LateResolutionVisitor<'a, '_, 'ast, 'tcx> {
...
+            String,
+            &Vec<(Span, String)>,
+        ) -> bool,
     ) {
         let mut suggest_note = true;
         for rib in self.lifetime_ribs.iter().rev() {
             let mut should_continue = true;
             match rib.kind {
-                LifetimeRibKind::Generics { binder: _, span, kind } => {
+                LifetimeRibKind::Generics { binder: node_id, span, kind } => {
```
[the remark this answers is not in the document]
Comment (surechen) [reply compiler/rustc_resolve/src/late/diagnostics.rs]: Done. Thank you.

**Comment by surechen** [comment]
> Thanks a lot, that looks great! ❤️ I apologize for taking so long (yet again!) 😞.
> 
> Almost ready, I have a couple of small suggestions. Then I will put into the merge queue!

Thank you very much. Please help me review again.

**Review by fmease — APPROVED** [review]
Thanks a lot!
