### PR TITLE
Fix replacing supertrait aliases in `ReplaceProjectionWith`

### LINKED ISSUE #171: builtin object candidates: `ReplaceProjectionWith` relate failures
encountered during try builds when compiling `wasmparser`.
```rust
pub trait Trait: Super {}
pub trait Super {
    type Output;
}

fn bound<T: Trait + ?Sized>() {}
fn visit_simd_operator<V: Super + ?Sized>() {
    bound::<dyn Trait<Output = <V as Super>::Output>>();
}
```
compiles on stable, results in the following ICE with the new solver
```
thread 'rustc' panicked at /home/lcnr/rust/compiler/rustc_next_trait_solver/src/solve/assembly/structural_traits.rs:930:26:
expected to be able to unify goal projection with dyn's projection: NoSolution
```

### PR DESCRIPTION
**Pull request by compiler-errors**
The new solver has a procedure called `predicates_for_object_candidate`, which elaborates the super-bounds and item-bounds that are required to hold for a dyn trait to implement something via a built-in object impl.

In that procedure, there is a folder called `ReplaceProjectionWith` which is responsible for replacing projections that reference `Self`, so that we don't encounter cycles when we then go on to normalize those projections in the process of proving these super-bounds.

That folder had a few problems: Firstly, it wasn't actually checking that this was a super bound originating from `Self`. Secondly, it only accounted for a *single* projection type def id, but trait objects can have multiple (i.e. `trait Foo<A, B>: Bar<A, Assoc = A> + Bar<B, Assoc = B>`).

To fix the first, it's simple enough to just add an equality check for the self ty. To fix the second, I implemented a matching step that's very similar to the `projection_may_match` check we have for upcasting, since on top of having multiple choices, we need to deal with both non-structural matches and ambiguity.

This probably lacks a bit of documentation, but I think it works pretty well.

Fixes https://github.com/rust-lang/trait-system-refactor-initiative/issues/171

r? lcnr

### CODE REVIEW

File: compiler/rustc_next_trait_solver/src/solve/assembly/structural_traits.rs [hunk 1]
```diff
@@ -871,72 +872,125 @@ where
...
-struct ReplaceProjectionWith<'a, D: SolverDelegate<Interner = I>, I: Interner> {
-    ecx: &'a EvalCtxt<'a, D>,
+struct ReplaceProjectionWith<'a, 'b, I: Interner, D: SolverDelegate<Interner = I>> {
+    ecx: &'a mut EvalCtxt<'b, D>,
     param_env: I::ParamEnv,
-    mapping: HashMap<I::DefId, ty::Binder<I, ty::ProjectionPredicate<I>>>,
+    self_ty: I::Ty,
+    mapping: HashMap<I::DefId, Vec<ty::Binder<I, ty::ProjectionPredicate<I>>>>,
     nested: Vec<Goal<I, I::Predicate>>,
+    is_ambiguous: bool,
```
Comment (compiler-errors) [inline compiler/rustc_next_trait_solver/src/solve/assembly/structural_traits.rs:914]: Ideally we'd use a `FallibleTypeFolder` here rather than tracking ambiguity on the side. Unfortunately, I think it's impossible to implement a `FallibleTypeFolder` b/c of the blanket implementation:

```
impl FallibleTypeFolder<I> for F where F: TypeFolder<I> {}
```

...causing us to have impl overlap due to downstream impl ambiguity in coherence.

File: compiler/rustc_next_trait_solver/src/solve/assembly/structural_traits.rs [hunk 2]
```diff
@@ -871,72 +872,125 @@ where
...
+            };
+
+        let mut matching_projections = replacements.iter().filter(|source_projection| {
+            projection_may_match(self.ecx, **source_projection, alias_term)
+        });
+        let Some(replacement) = matching_projections.next() else {
+            // FIXME: This *shouldn't* happen.
+            return None;
+        };
+        if matching_projections.next().is_some() {
```
Comment (compiler-errors) [inline compiler/rustc_next_trait_solver/src/solve/assembly/structural_traits.rs:958]: We may have trouble deduplicating identical bounds here.

File: compiler/rustc_type_ir/src/solve/inspect.rs [hunk 3]
```diff
@@ -118,10 +118,12 @@ pub enum ProbeKind<I: Interner> {
...
-    /// During upcasting from some source object to target object type, used to
-    /// do a probe to find out what projection type(s) may be used to prove that
-    /// the source type upholds all of the target type's object bounds.
-    UpcastProjectionCompatibility,
+    /// Used to do a probe to find out what projection type(s) match a given
+    /// alias bound or projection predicate. For trait upcasting, this is used
+    /// to prove that the source type upholds all of the target type's object
+    /// bounds. For object type bounds, this is used when eagerly replacing
+    /// supertrait aliases.
+    ProjetionCompatibility,
```
Comment (compiler-errors) [inline compiler/rustc_type_ir/src/solve/inspect.rs:126]: typo

File: compiler/rustc_next_trait_solver/src/solve/assembly/structural_traits.rs (hunk 1 above)
Comment (lcnr) [reply compiler/rustc_next_trait_solver/src/solve/assembly/structural_traits.rs:914]: :skull_emoji:

**Comment by lcnr** [comment]
Want to familiarize myself with why exactly this folder is necessary again. A quick look at the comments and the link to https://github.com/lcnr/solver-woes/issues/9 / https://github.com/rust-lang/trait-system-refactor-initiative/issues/6 were not too unhelpful at getting this back into cache.

**Comment by compiler-errors** [comment]
Yeah, the documentation is lacking in the compiler. 

It mentions the need for this folder to prevent unsoundness due to aliases trivially proving their own item bounds, but it doesn't mention that this folder is also required to prevent trivial (in the future -- coinductive, I think) cycles due to the fact that we require alias bounds to hold in the built-in impl. 

This is made further interesting by the fact that aliases are allowed to be present in item bounds, for example see:

```
trait Foo {
    type Assoc: Baz<Self::Assoc>;
}

trait Baz<T> {}
impl Baz<()> for () {}

fn is_foo<T: Foo + ?Sized>() {}

fn main() {
    is_foo::<dyn Foo<Assoc = ()>>();
}
```

Such a built-in impl conceptually expands to something like:

```
impl Foo for dyn Foo
where
    <dyn Foo as Foo>::Assoc: Baz<<dyn Foo as Foo>::Assoc>
{}
```

Which I hope is clear that it'll lead to cycles :)

**Comment by compiler-errors** [comment]
> Yeah, the documentation is lacking in the compiler.

Actually, the documentation already mentions a very similar example to the one I gave above:

```
/// Assemble a list of predicates that would be present on a theoretical
/// user impl for an object type. These predicates must be checked any time
/// we assemble a built-in object candidate for an object type, since they
/// are not implied by the well-formedness of the type.
///
/// For example, given the following traits:
///
/// ```rust,ignore (theoretical code)
/// trait Foo: Baz {
///     type Bar: Copy;
/// }
///
/// trait Baz {}
/// ```
///
/// For the dyn type `dyn Foo<Item = Ty>`, we can imagine there being a
/// pair of theoretical impls:
///
/// ```rust,ignore (theoretical code)
/// impl Foo for dyn Foo<Item = Ty>
/// where
///     Self: Baz,
///     <Self as Foo>::Bar: Copy,
/// {
///     type Bar = Ty;
/// }
///
/// impl Baz for dyn Foo<Item = Ty> {}
/// ```
///
/// However, in order to make such impls non-cyclical, we need to do an
/// additional step of eagerly folding the associated types in the where
/// clauses of the impl. In this example, that means replacing
/// `<Self as Foo>::Bar` with `Ty` in the first impl.
```

I kinda feel like that is sufficient to motivate the existence of the folder, and I'll just remove the FIXME since it's not necessary anymore.

File: compiler/rustc_next_trait_solver/src/solve/assembly/structural_traits.rs (hunk 1 above)
Comment (lcnr) [reply compiler/rustc_next_trait_solver/src/solve/assembly/structural_traits.rs:908]: would like to block this on #139768 then

File: compiler/rustc_next_trait_solver/src/solve/assembly/structural_traits.rs [hunk 4]
```diff
@@ -871,72 +866,126 @@ where
...
+        nested: vec![],
+        is_ambiguous: false,
+    };
+
+    if folder.is_ambiguous {
+        return Err(Ambiguous);
+    }
 
-    folder
+    let requirements = requirements.fold_with(&mut folder);
```
Comment (lcnr) [inline compiler/rustc_next_trait_solver/src/solve/assembly/structural_traits.rs:894]: :thinking: 

i feel like the `if`  should be after the `fold_with` call :sweat_smile: 

is it possible to add a test where this ambiguity is actually relevant? I assume that ignoring `is_ambiguous` means we return the unnormalized alias and treat is as rigid here, encountering the solver cycle this folder wants to avoid :thinking:

File: compiler/rustc_next_trait_solver/src/solve/assembly/structural_traits.rs [hunk 5]
```diff
@@ -871,72 +866,126 @@ where
...
     param_env: I::ParamEnv,
-    mapping: HashMap<I::DefId, ty::Binder<I, ty::ProjectionPredicate<I>>>,
+    self_ty: I::Ty,
+    mapping: HashMap<I::DefId, Vec<ty::Binder<I, ty::ProjectionPredicate<I>>>>,
     nested: Vec<Goal<I, I::Predicate>>,
+    is_ambiguous: bool,
 }
 
+impl<D: SolverDelegate<Interner = I>, I: Interner> ReplaceProjectionWith<'_, '_, I, D> {
+    /// Try to replace an alias with
```
Comment (lcnr) [inline compiler/rustc_next_trait_solver/src/solve/assembly/structural_traits.rs:912]: with.

File: compiler/rustc_next_trait_solver/src/solve/assembly/structural_traits.rs [hunk 6]
```diff
@@ -871,72 +866,126 @@ where
...
+                                ecx.instantiate_binder_with_infer(source_projection);
+                            ecx.eq(
+                                self.param_env,
+                                source_projection.projection_term,
+                                target_projection,
+                            )?;
+                            ecx.try_evaluate_added_goals()
+                        })
+                        .is_ok()
+            };
```
Comment (lcnr) [inline compiler/rustc_next_trait_solver/src/solve/assembly/structural_traits.rs:943]: move this it a separate function

File: compiler/rustc_next_trait_solver/src/solve/assembly/structural_traits.rs [hunk 7]
```diff
@@ -871,72 +866,126 @@ where
...
+
+        let mut matching_projections = replacements.iter().filter(|source_projection| {
+            projection_may_match(self.ecx, **source_projection, alias_term)
+        });
+        let Some(replacement) = matching_projections.next() else {
+            // FIXME: This *shouldn't* happen.
```
Comment (lcnr) [inline compiler/rustc_next_trait_solver/src/solve/assembly/structural_traits.rs:949]: but does?

Comment (compiler-errors) [reply compiler/rustc_next_trait_solver/src/solve/assembly/structural_traits.rs:949]: but i dont wanna ice on it lol

Comment (compiler-errors) [reply compiler/rustc_next_trait_solver/src/solve/assembly/structural_traits.rs:949]: but i guess we could ice here

File: compiler/rustc_next_trait_solver/src/solve/assembly/structural_traits.rs (hunk 4 above)
Comment (compiler-errors) [reply compiler/rustc_next_trait_solver/src/solve/assembly/structural_traits.rs:894]: that is so funny, yeah it should happen before. my bad.

I'll try to think of a test where this matters -- perhaps something like `dyn Trait<?A, ?B>` where `Trait<A, B>: Sup<A, Assoc = A> + Sup<B, Assoc = B>` where we use need to replace `<Self as Sup<A>>::Assoc`, but then inference later constrains `?A` and `?B`.

**Comment by lcnr** [comment]
gamer

@bors r+ rollup
