### PR TITLE
error message when trying to move from an Rc or Arc is ungreat

### LINKED ISSUE #52086: error message when trying to move from an Rc or Arc is ungreat
This example

```rust
use std::rc::Rc;

struct Bar { field: Vec<i32> }

fn main() {
    let x = Rc::new(Bar { field: vec![] });
    drop(x.field);
}
```

gives this error:

```
error[E0507]: cannot move out of borrowed content
 --> src/main.rs:7:10
  |
7 |     drop(x.field);
  |          ^ cannot move out of borrowed content
```

That is confusing -- after all, `x` is not borrowed!

The problem is that `Rc` only implements `Deref`, and hence we wind up lowering to `Deref::deref(&x).field`, and `deref` returns a `&Bar`.

We should probably say:

```
error[E0507]: cannot move out of `Rc`
 --> src/main.rs:7:10
  |
7 |     drop(x.field);
  |          ^ cannot move out of an `Rc`
```

### PR DESCRIPTION
**Pull request by davidtwco**
Fixes #52086.

r? @nikomatsakis

### CODE REVIEW

**Comment by tmandry** [comment]
Nice! Just curious, was there any discussion of fixing this for smart pointer types other than Rc and Arc? (i.e. any type that used Deref along the path)

I have no idea if this is possible. This clearly fixes the most important error messages, but wonder if it could be done more generically at some point.

File: src/librustc_mir/borrow_check/move_errors.rs [hunk 1]
```diff
@@ -471,4 +494,94 @@ impl<'a, 'gcx, 'tcx> MirBorrowckCtxt<'a, 'gcx, 'tcx> {
...
+                        if ty.is_arc() {
+                            return BorrowedContentSource::Arc;
+                        } else if ty.is_rc() {
+                            return BorrowedContentSource::Rc;
+                        } else {
+                            queue.push(init.path);
+                        }
+                    }
+                } else if let Some(Terminator {
+                    kind: TerminatorKind::Call { args, .. },
```
Comment (nikomatsakis) [inline src/librustc_mir/borrow_check/move_errors.rs]: Hmm, if we did want to implement @tmandry's idea for a more general hint, it might be nice — we could probably avoid the `Rc` and `Arc` lang-items. The idea would be to look here to see if this terminator is a call to `Deref::deref`, basically.

That said, the error might be *slightly* misleading unless we phrase it carefully, since some types that impl DEref might have a way to move-out, just not via deref. Although, come to think of it, that is true for `Rc` and `Arc` too!

(e.g.,[ `Rc::try_unwrap`](https://doc.rust-lang.org/std/rc/struct.Rc.html#method.try_unwrap))

File: src/test/ui/borrowck/borrowck-move-out-of-overloaded-auto-deref.mir.stderr [hunk 2]
```diff
@@ -1,8 +1,8 @@
-error[E0507]: cannot move out of borrowed content
+error[E0507]: cannot move out of an `Rc`
   --> $DIR/borrowck-move-out-of-overloaded-auto-deref.rs:17:14
    |
 LL |     let _x = Rc::new(vec![1, 2]).into_iter();
-   |              ^^^^^^^^^^^^^^^^^^^ cannot move out of borrowed content
+   |              ^^^^^^^^^^^^^^^^^^^ cannot move out of an `Rc`
```
Comment (nikomatsakis) [inline src/test/ui/borrowck/borrowck-move-out-of-overloaded-auto-deref.mir.stderr]: so..much...nicer...

Comment (nikomatsakis) [reply src/test/ui/borrowck/borrowck-move-out-of-overloaded-auto-deref.mir.stderr]: I wonder, though: if we stay specialized, then we can offer a hint like "you might want to consider `Rc::try_unwrap`".

**Review by nikomatsakis — COMMENTED** [review]
Thoughts?

File: src/librustc_mir/borrow_check/move_errors.rs (hunk 1 above)
Comment (davidtwco) [reply src/librustc_mir/borrow_check/move_errors.rs]: Why not both? We could special case `Rc` and `Arc` like we do now, adding suggestions for `Rc::try_unwrap` and the like; but, if we detect a call to `Deref::deref` then we provide a more general error without the more specific suggestions. I'd lean toward filing an issue for the more general case and landing this as is (after I've added the `try_unwrap` suggestion) for now.

File: src/test/ui/borrowck/borrowck-move-out-of-overloaded-auto-deref.mir.stderr (hunk 2 above)
Comment (davidtwco) [reply src/test/ui/borrowck/borrowck-move-out-of-overloaded-auto-deref.mir.stderr]: I've added a `try_unwrap` suggestion - are you happy with the wording?

File: src/librustc_mir/borrow_check/move_errors.rs [hunk 3]
```diff
@@ -305,9 +314,29 @@ impl<'a, 'gcx, 'tcx> MirBorrowckCtxt<'a, 'gcx, 'tcx> {
...
+                                            BorrowedContentSource::Rc => "Rc",
+                                            BorrowedContentSource::Arc => "Arc",
+                                            _ => unreachable!(),
+                                        };
+
+                                        let mut diag = self.infcx.tcx.cannot_move_out_of(
+                                            span, &format!("an `{}`", name), origin
+                                        );
+                                        diag.help(&format!(
+                                            "did you mean to call `{}::try_unwrap`?", name
```
Comment (nikomatsakis) [inline src/librustc_mir/borrow_check/move_errors.rs]: it seems pretty unlikely that they were intending to call `try_unwrap` but "accidentally" wrote `foo.bar`. Maybe we should word it more like: "you may wish to consider `{}::try_unwrap`"?

**Review by nikomatsakis — CHANGES_REQUESTED** [review]
Thoughts?

**Comment by nikomatsakis** [comment]
(I'm ok with starting with the Rc-Arc error for now)

File: src/librustc_mir/borrow_check/move_errors.rs (hunk 1 above)
Comment (tmandry) [reply src/librustc_mir/borrow_check/move_errors.rs]: I like this idea, and doing it in a follow up is fine.

File: src/librustc_mir/borrow_check/move_errors.rs (hunk 3 above)
Comment (davidtwco) [reply src/librustc_mir/borrow_check/move_errors.rs]: I've updated the message.

File: src/test/ui/borrowck/borrowck-move-out-of-overloaded-auto-deref.mir.stderr [hunk 4]
```diff
@@ -1,8 +1,10 @@
...
+   |
+   = help: you may wish to consider `Rc::try_unwrap`?
```
Comment (nikomatsakis) [inline src/test/ui/borrowck/borrowck-move-out-of-overloaded-auto-deref.mir.stderr]: Sorry for the wild goose chase, but now I'm worrying that this will mislead "newcomers" — `try_unwrap` is probably *very rarely* the thing you actually want. I've heard time and time again feedback that having the compiler give "random" suggestions can be very misleading for people who are feeling their way through the system. Perhaps we should just remove this. 

r=me with `try_unwrap` removed

**Review by nikomatsakis — CHANGES_REQUESTED** [review]

File: src/test/ui/borrowck/borrowck-move-out-of-overloaded-auto-deref.mir.stderr (hunk 4 above)
Comment (davidtwco) [reply src/test/ui/borrowck/borrowck-move-out-of-overloaded-auto-deref.mir.stderr]: Removed that commit.
