### PR TITLE
Integrate miri into build-manifest

### LINKED ISSUE #57488: Can't install nightly-2019-01-10
Installing rust nightly with rustup returns this error:

```
info: syncing channel updates for 'nightly-x86_64-unknown-linux-gnu'
info: latest update on 2019-01-10, rust version 1.33.0-nightly (6ecad3383 2019-01-09)
info: downloading component 'rustc'
error: failed to parse url: nightly/2019-01-10/rustc-nightly-x86_64-unknown-linux-gnu.tar.xz
info: caused by: relative URL without a base
```

We're aware of this and a fix is pending in https://github.com/rust-lang/rust/pull/57484. Sorry for the trouble!

### PR DESCRIPTION
**Pull request by alexcrichton**
This fixes a mistake where miri was accidentally left out of the
build-manifest parsing, meaning that today's nightly generated a
manifest with invalid urls!

Fixes #57488.

### CODE REVIEW

**Comment by alexcrichton** [comment]
cc @oli-obk and https://github.com/rust-lang/rust/pull/57086 (just making sure y'all are aware!)

@bors: p=1000

(fixes nightly releases)

File: src/tools/build-manifest/src/main.rs [hunk 1]
```diff
@@ -297,6 +304,7 @@ impl Builder {
         self.llvm_tools_version = self.version("llvm-tools", "x86_64-unknown-linux-gnu");
         // lldb is only built for macOS.
         self.lldb_version = self.version("lldb", "x86_64-apple-darwin");
+        self.miri_version = self.version("miri", "x86_64-apple-darwin");
```
Comment (Mark-Simulacrum) [inline src/tools/build-manifest/src/main.rs]: Hm, this should probably be a Linux triple, not macOS?

**Comment by Mark-Simulacrum** [comment]
r=me modulo my comment

**Comment by dwijnand** [comment]
Fixes #57488.

**Comment by RalfJung** [comment]
@dwijnand thanks, I added that to the OP (GH doesn't seem to recognize it as a magic marker otherwise).
