### PR TITLE
Fix unused_parens issue for higher ranked function pointers

### LINKED ISSUE #105061: unused_parens: doesn't trigger for higher ranked function pointers
```rust
struct Inv<'a>(&'a mut &'a ());

trait Trait {}
impl Trait for (for<'a> fn(Inv<'a>),) {}


fn with_bound()
where
    ((for<'a> fn(Inv<'a>)),): Trait,
{}

fn main() {
    with_bound();
}
```
This should lint as the parens around the function pointer are unnecessary, but stopped doing so due to #104796.

Expected output:
```rust
warning: unnecessary parentheses around type
 --> src/main.rs:9:5
  |
9 |     (for<'a> fn(Inv<'a>)): Trait,
  |     ^                   ^
  |
  = note: `#[warn(unused_parens)]` on by default
help: remove these parentheses
  |
9 -     (for<'a> fn(Inv<'a>)): Trait,
9 +     for<'a> fn(Inv<'a>): Trait,
  |
```

### PR DESCRIPTION
**Pull request by chenyukang**
fixes #105061

r? @lcnr

### CODE REVIEW

**Comment by chenyukang** [comment]
I think #104397 is caused by the following `:`,
do you know any better solution for this? @lcnr

File: compiler/rustc_lint/src/unused.rs [hunk 1]
```diff
@@ -1038,7 +1038,20 @@ impl EarlyLintPass for UnusedParens {
...
+                ast::TyKind::BareFn(b) => {
+                    let spans = if let Some(r) = r.span.find_ancestor_inside(ty.span) {
+                        Some((ty.span.with_hi(r.lo()), ty.span.with_lo(r.hi())))
+                    } else {
+                        None
+                    };
+                    let sm = cx.sess().source_map();
+                    if let Some((_, r)) = spans &&
+                        b.generic_params.len() > 0 &&
+                        sm.span_followed_by(r, ":") {
```
Comment (cjgillot) [inline compiler/rustc_lint/src/unused.rs:1050]: This aims to check that we are in a where predicate, doesn't it?
Could you prefer a more explicit check, with a new `check_where_predicate` method or something like that?

Comment (chenyukang) [reply compiler/rustc_lint/src/unused.rs:1050]: You means add `check_where_predicate` in `EarlyLintPass`?
https://github.com/rust-lang/rust/blob/f206533fd40378da6e2a07567e8d7592edd13ee4/compiler/rustc_lint/src/early.rs#L249

Seems `walk_where_predicate` again will also call to `visit_ty`, then call to `check_ty`:

https://github.com/rust-lang/rust/blob/f206533fd40378da6e2a07567e8d7592edd13ee4/compiler/rustc_ast/src/visit.rs#L623

Comment (cjgillot) [reply compiler/rustc_lint/src/unused.rs:1050]: > You means add `check_where_predicate` in `EarlyLintPass`?
> 

Yes.

> https://github.com/rust-lang/rust/blob/f206533fd40378da6e2a07567e8d7592edd13ee4/compiler/rustc_lint/src/early.rs#L249
> 
> Seems `walk_where_predicate` again will also call to `visit_ty`, then call to `check_ty`:
> 
> https://github.com/rust-lang/rust/blob/f206533fd40378da6e2a07567e8d7592edd13ee4/compiler/rustc_ast/src/visit.rs#L623

You'll need to ensure that we don't lint on that case from `check_ty`, but from `check_where_predicate`.

Comment (chenyukang) [reply compiler/rustc_lint/src/unused.rs:1050]: How can we customize the behavior of `visit_where_predicate` for an specific lint? In this case, it's the lint for `UnusedParens`.

Comment (chenyukang) [reply compiler/rustc_lint/src/unused.rs:1050]: Seems we can not add a return value for `check_where_predicate`.

**Review by lcnr — COMMENTED** [review]
do you still want to look into the alternative approach suggested by @cjgillot? I am a bit uncomfortable with using spans for stuff like that as I can never get myself to be certain that we're correctly dealing with macros. 

Also, can you add a test for both: `(fn()): Trait` if we don't have one yet (this should lint), and `((for<'a> fn(&'a u32))): Trait` (this should lint for the inner brace).

**Comment by chenyukang** [comment]
> do you still want to look into the alternative approach suggested by @cjgillot? I am a bit uncomfortable with using spans for stuff like that as I can never get myself to be certain that we're correctly dealing with macros.
> 
> Also, can you add a test for both: `(fn()): Trait` if we don't have one yet (this should lint), and `((for<'a> fn(&'a u32))): Trait` (this should lint for the inner brace).

Yes, I met an issue last time I tried it, will reconsider it later.

File: compiler/rustc_lint/src/early.rs [hunk 2]
```diff
@@ -247,6 +247,12 @@ impl<'a, T: EarlyLintPass> ast_visit::Visitor<'a> for EarlyContextAndPass<'a, T>
     }
 
     fn visit_where_predicate(&mut self, p: &'a ast::WherePredicate) {
+        use rustc_ast::{WhereBoundPredicate, WherePredicate};
+        if let WherePredicate::BoundPredicate(WhereBoundPredicate { bounded_ty, .. }) = p &&
+            let ast::TyKind::BareFn(b) = &bounded_ty.kind &&
+            b.generic_params.len() > 0 {
+                return;
```
Comment (lcnr) [inline compiler/rustc_lint/src/early.rs:254]: shouldn't this check for `ast::TyKInd::Paren` containing a `BareFn`

I think the condition should also include the check `bound_generic_params.is_empty()`.

THis should lint as `for<'b> for<'a> fn(Inv<'a>): Trait<'b>` is also correct:
```rust
#![deny(warnings)]

struct Inv<'a>(&'a mut &'a ());

trait Trait<'a> {}
impl<'b> Trait<'b> for for<'a> fn(Inv<'a>) {}


fn with_bound()
where
    for<'b> (for<'a> fn(Inv<'a>)): Trait<'b>, //~ ERROR unnecessary parentheses around type
{}

fn main() {
    with_bound();
}
```

File: compiler/rustc_lint/src/unused.rs [hunk 3]
```diff
@@ -1033,7 +1033,6 @@ impl EarlyLintPass for UnusedParens {
         if let ast::TyKind::Paren(r) = &ty.kind {
             match &r.kind {
                 ast::TyKind::TraitObject(..) => {}
-                ast::TyKind::BareFn(b) if b.generic_params.len() > 0 => {}
                 ast::TyKind::ImplTrait(_, bounds) if bounds.len() > 1 => {}
                 ast::TyKind::Array(_, len) => {
                     self.check_unused_delims_expr(
```
Comment (lcnr) [inline compiler/rustc_lint/src/unused.rs:1038]: I just realized, that's a bug :grin: it causes us to not lint on 
```rust
fn main() {
    let _x: ([u32; 3]);
    //      ^^^^^^^^^^ should lint
    let _y: [u8; (3)];
    //           ^^^ should lint
    let _z: ([u8; (3)]);
    //            ^^^ does lint
}
```
may make sense as part of this PR. HAve to move the `ast::TyKind::Array` branch to the same level as the `if let ast::TyKind::Paren(r) = &ty.kind {`, not inside of `TyKind::Paren`.

If not I am going to open a separate issue for this.

File: compiler/rustc_lint/src/early.rs (hunk 2 above)
Comment (lcnr) [reply compiler/rustc_lint/src/early.rs:254]: ah, but instead of changing the visiting behavior for all lints, you should instead add a method like `fn enter_lint_where_bound` or something to `EarlyLintPass` where the `UnusedParens` lint has special behavior. Similar to https://doc.rust-lang.org/nightly/nightly-rustc/rustc_lint/trait.EarlyLintPass.html#method.enter_lint_attrs

File: compiler/rustc_lint/src/unused.rs (hunk 3 above)
Comment (chenyukang) [reply compiler/rustc_lint/src/unused.rs:1038]: Seems we find some lint error in `std` 😂:

```diff
error: unnecessary parentheses around const expression
   --> library/std/src/io/error/repr_bitpacked.rs:377:27
    |
377 | static_assert!(@usize_eq: (TAG_MASK & TAG_SIMPLE_MESSAGE), TAG_SIMPLE_MESSAGE);
    |                           ^                             ^
    |
    = note: `-D unused-parens` implied by `-D warnings`
help: remove these parentheses
    |
377 - static_assert!(@usize_eq: (TAG_MASK & TAG_SIMPLE_MESSAGE), TAG_SIMPLE_MESSAGE);
377 + static_assert!(@usize_eq: TAG_MASK & TAG_SIMPLE_MESSAGE, TAG_SIMPLE_MESSAGE);
    |

error: unnecessary parentheses around const expression
   --> library/std/src/io/error/repr_bitpacked.rs:378:27
    |
378 | static_assert!(@usize_eq: (TAG_MASK & TAG_CUSTOM), TAG_CUSTOM);
    |                           ^                     ^
    |
help: remove these parentheses
    |
378 - static_assert!(@usize_eq: (TAG_MASK & TAG_CUSTOM), TAG_CUSTOM);
378 + static_assert!(@usize_eq: TAG_MASK & TAG_CUSTOM, TAG_CUSTOM);
    |

```

File: compiler/rustc_lint/src/unused.rs [hunk 4]
```diff
@@ -1030,21 +1040,22 @@ impl EarlyLintPass for UnusedParens {
     }
 
     fn check_ty(&mut self, cx: &EarlyContext<'_>, ty: &ast::Ty) {
+        if let ast::TyKind::Array(_, len) = &ty.kind {
```
Comment (lcnr) [inline compiler/rustc_lint/src/unused.rs:1043]: style nit: can you use a `match' instead of 2 unrelated `if let`

File: compiler/rustc_lint/src/unused.rs [hunk 5]
```diff
@@ -1030,21 +1040,22 @@ impl EarlyLintPass for UnusedParens {
...
+            self.check_unused_delims_expr(
+                cx,
+                &len.value,
+                UnusedDelimsCtx::ArrayLenExpr,
+                false,
+                None,
+                None,
+            );
+        }
         if let ast::TyKind::Paren(r) = &ty.kind {
```
Comment (lcnr) [inline compiler/rustc_lint/src/unused.rs:1053]: can you set `self.with_self_ty_parens` to `false` at the end of this branch and instead assert that it is false in `exit_where_predicate`?

Because right now I think you don't lint for the inner paren in `(dyn Trait<(for<'a> fn(&'a ())>): Trait,` even though we should.

**Review by lcnr — COMMENTED** [review]
thanks :+1: 

r=me after nits

**Comment by chenyukang** [comment]
@rustbot 
r=lcnr
