### PR TITLE
[rustdoc] Ensure that temporary doctest folder is correctly removed even if doctests failed

### LINKED ISSUE #139899: Thousands of /tmp/rustdoctest* directories
While working on rustc, I often have:

```
$ ls /tmp/rustdoctest* | wc -l
6197
```

😬

Almost all these directories are completely empty.

We should probably do a better job at cleaning them up. Or move them into the build directory instead of littering all over /tmp.

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Fixes #139899.

The bug was due to the fact that if any doctest fails for any reason, we call `exit` (or it's called inside `libtest` if not edition 2024), meaning that `TempDir`'s destructor isn't called, and therefore the temporary folder isn't cleaned up.

Took me a while to figure out how to reproduce but finally I was able to reproduce the bug with:

`````rust
#![doc(test(attr(deny(warnings))))]

//! ```
//! let a = 12;
//! ```
`````

And then I ensured that panicking doctests were cleaned up as well:

`````rust
//! ```
//! panic!();
//! ```
`````

And finally I checked if it was fixed for merged doctests too (`--edition 2024`).

To make this work, I needed to add a new public function in `libtest` too which would call a function once all tests have been run.

So only issue is: I have absolutely no idea how we can add a regression test for this fix. If anyone has an idea...

r? @notriddle

### CODE REVIEW

File: src/librustdoc/doctest.rs [hunk 1]
```diff
@@ -382,9 +394,16 @@ pub(crate) fn run_tests(
...
     if ran_edition_tests == 0 || !standalone_tests.is_empty() {
         standalone_tests.sort_by(|a, b| a.desc.name.as_slice().cmp(b.desc.name.as_slice()));
-        test::test_main(&test_args, standalone_tests, None);
+        let temp_dir_path = temp_dir.as_ref().map(|t| t.path());
+        test::test_main_with_exit_callback(&test_args, standalone_tests, None, || {
+            // We cannot move `temp_dir` in this closure so instead we do its job manually.
+            if let Some(temp_dir_path) = temp_dir_path {
+                let _ = std::fs::remove_dir_all(temp_dir_path);
+            }
+        });
```
Comment (notriddle) [inline src/librustdoc/doctest.rs:403]: Can't you replace it with `None?

```suggestion
        test::test_main_with_exit_callback(&test_args, standalone_tests, None, || {
            // We need to drop 
            std::mem::drop(temp_dir.take());
        });
```

**Comment by GuillaumeGomez** [comment]
Applied suggestion.

**Comment by notriddle** [comment]
Okay, so what would it take to build a run-make test of this? I understand if it's too much trouble, but I'd at least like to have some rationale, because without a regression test, this seems like it could easily regress.

**Comment by GuillaumeGomez** [comment]
@lolbinarycat suggested a good way to test it so gonna write it.

**Comment by GuillaumeGomez** [comment]
Added the regression test. Since `tempfile` is using std's `tempdir` and `tempdir` is using `TMPDIR` environment variable, we can decide where to put the temp output of rustdoc, so I did.

**Comment by jieyouxu** [comment]
> Added the regression test. Since `tempfile` is using std's `tempdir` and `tempdir` is using `TMPDIR` environment variable, we can decide where to put the temp output of rustdoc, so I did.

Just a caveat, on Windows the env vars are slightly different (`TEMP`, `TMP`, and another fallback), not that this really matters, since we go through std `temp_dir()` the same. I think this should also be reproducible on Windows (as in this fix works), but you'd need to gate which env var is set.

**Comment by GuillaumeGomez** [comment]
Hence why for now it's only run on linux. :wink: 

I can write a follow-up though to extend the tests to other platforms, but I'd like to get this merged as soon as possible for this bug to disappear.

**Comment by jieyouxu** [comment]
Yeah, not blocking for sure :+1:

**Comment by cuviper** [comment]
This wasn't approved in time for 1.87.0. If it now needs stable consideration, that can be raised anew.

@rustbot label -beta-nominated
