### PR TITLE
Make all uses of ty::Error delay a span bug

### LINKED ISSUE #70866: Don't (ab)use `TyKind::Error` when not planning to emit error
cc https://github.com/rust-lang/rust/pull/70551 @eddyb 

Currently, it appears we are misusing `TyKind::Error` (and `Const::Error`) in these places, which we should refactor:

- [x] fixed by #70870 https://github.com/rust-lang/rust/blob/6dee5f1126dfd5c9314ee5ae9d9eb010e35ef257/src/librustc_typeck/check/wfcheck.rs#L710

- [x] fixed by #70870 https://github.com/rust-lang/rust/blob/6dee5f1126dfd5c9314ee5ae9d9eb010e35ef257/src/librustc_typeck/check/wfcheck.rs#L715

- [x] fixed by #70870 https://github.com/rust-lang/rust/blob/6dee5f1126dfd5c9314ee5ae9d9eb010e35ef257/src/librustc_typeck/lib.rs#L383

- [x] fixed by #70870 https://github.com/rust-lang/rust/blob/6dee5f1126dfd5c9314ee5ae9d9eb010e35ef257/src/librustc_typeck/variance/constraints.rs#L319

- [x] fixed by #70932 https://github.com/rust-lang/rust/blob/42abbd8878d3b67238f3611b0587c704ba94f39c/src/librustc_typeck/check/pat.rs#L1428-L1435

- [x] fixed by #71938 https://github.com/rust-lang/rust/blob/93dc97a85381cc52eb872d27e50e4d518926a27c/src/librustc_typeck/check/closure.rs#L180

- [x] fixed by #70164
    
    https://github.com/rust-lang/rust/blob/6dee5f1126dfd5c9314ee5ae9d9eb010e35ef257/src/librustc_trait_selection/traits/select.rs#L3079

- [x] fixed by #71930 https://github.com/rust-lang/rust/blob/9fed36055070168e5238d6bf6e58a36f519fe427/src/librustc_mir_build/hair/pattern/_match.rs#L900

### PR DESCRIPTION
**Pull request by mark-i-m**
r? @eddyb 

A second attempt at https://github.com/rust-lang/rust/pull/70245

resolves https://github.com/rust-lang/rust/issues/70866

### CODE REVIEW

**Comment by mark-i-m** [comment]
Currently, the following locations are producing delayed span bugs:

```
error: internal compiler error: TyKind::Error constructed but no error reported. src/librustc_typeck/check/wfcheck.rs:710:17

error: internal compiler error: TyKind::Error constructed but no error reported. src/librustc_typeck/lib.rs:384:9

error: internal compiler error: TyKind::Error constructed but no error reported. src/librustc_typeck/check/wfcheck.rs:710:17

error: internal compiler error: TyKind::Error constructed but no error reported. src/librustc_typeck/variance/constraints.rs:318:82

error: internal compiler error: ty::Const Error constructed but no error reported. src/librustc_typeck/check/wfcheck.rs:715:17

error: internal compiler error: TyKind::Error constructed but no error reported. src/librustc_typeck/check/wfcheck.rs:715:17

error: internal compiler error: TyKind::Error constructed but no error reported. src/librustc_trait_selection/traits/select.rs:3077:63

error: internal compiler error: TyKind::Error constructed but no error reported. src/librustc_typeck/lib.rs:384:9

```

**Comment by mark-i-m** [comment]
Blocked on #70866, which is itself blocked on #70866 and #70164 

@rustbot modify labels: +S-blocked

**Comment by mark-i-m** [comment]
Still blocked on resolution of #70866

**Comment by mark-i-m** [comment]
Still blocked on resolution of #70866, but we are getting closer...

**Comment by mark-i-m** [comment]
Rebased over #71930. Blocked on that merging.

@rustbot modify labels: -S-waiting-on-author

**Comment by mark-i-m** [comment]
@eddyb This is now ready for review :tada:

@rustbot modify labels: -S-blocked +S-waiting-on-review

File: src/librustc_trait_selection/traits/project.rs [hunk 1]
```diff
@@ -1483,7 +1483,7 @@ fn confirm_impl_candidate<'cx, 'tcx>(
     if substs.len() != tcx.generics_of(assoc_ty.item.def_id).count() {
         tcx.sess
             .delay_span_bug(DUMMY_SP, "impl item and trait item have different parameter counts");
```
Comment (matthewjasper) [inline src/librustc_trait_selection/traits/project.rs:1485]: Could there be another method on tcx that allows specifying a message to avoid the double `delay_span_bug` calls?

File: src/librustc_typeck/check/method/probe.rs [hunk 2]
```diff
@@ -400,7 +400,7 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
                     .probe_instantiate_query_response(span, &orig_values, ty)
                     .unwrap_or_else(|_| span_bug!(span, "instantiating {:?} failed?", ty));
                 let ty = self.structurally_resolved_type(span, ty.value);
-                assert_eq!(ty, self.tcx.types.err);
+                assert_eq!(ty, self.tcx.err());
```
Comment (matthewjasper) [inline src/librustc_typeck/check/method/probe.rs:403]: Could this compare `ty.kind` to `ty::Error`?

File: src/librustc_middle/ty/context.rs [hunk 3]
```diff
@@ -1181,6 +1179,32 @@ impl<'tcx> TyCtxt<'tcx> {
...
+    #[track_caller]
+    pub fn err(self) -> Ty<'tcx> {
+        self.sess.delay_span_bug(
+            DUMMY_SP,
+            &format!(
+                "TyKind::Error constructed but no error reported. {}",
+                std::panic::Location::caller()
+            ),
+        );
+        self.mk_ty(Error)
```
Comment (eddyb) [inline src/librustc_middle/ty/context.rs:1192]: Maybe you should add a publicly-unconstructible (outside of this module) `pub struct DelaySpanBugEmitted(());` field to `Error`, even before we change anything about `ErrorReported` itself.

If nothing else, it would catch code that does this (or the const thing, which is probably even more plausible) instead of calling the method.

File: src/librustc_middle/ty/context.rs [hunk 4]
```diff
@@ -1181,6 +1179,32 @@ impl<'tcx> TyCtxt<'tcx> {
...
     }
 
+    /// Constructs a `TyKind::Error` type and registers a `delay_span_bug` to ensure it gets used.
+    #[track_caller]
+    pub fn err(self) -> Ty<'tcx> {
+        self.sess.delay_span_bug(
+            DUMMY_SP,
+            &format!(
+                "TyKind::Error constructed but no error reported. {}",
+                std::panic::Location::caller()
```
Comment (eddyb) [inline src/librustc_middle/ty/context.rs:1189]: What if we add `#[track_caller]` to `delay_span_bug` as well and have *it* pull the location out? Since that would benefit every single `delay_span_bug` call, making it more like the `span_bug!` macro (modulo formatting).

Also it might be cool to use the `TyCxAt` helper to have `tcx.at(span).err()` use the span for the `delay_span_bug`, since I assume many of the callers of `tcx.err()` have a span around.

Comment (mark-i-m) [reply src/librustc_middle/ty/context.rs]: Perhaps I could open an issue for this? I'm not sure that I will have time to work on this a lot more.

File: src/librustc_middle/ty/context.rs [hunk 5]
```diff
@@ -1181,6 +1179,49 @@ impl<'tcx> TyCtxt<'tcx> {
         }
     }
 
+    /// Constructs a `TyKind::Error` type and registers a `delay_span_bug` to ensure it gets used.
+    #[track_caller]
+    pub fn err(self) -> Ty<'tcx> {
+        self.err_with_message_and_location(
```
Comment (Aaron1011) [inline src/librustc_middle/ty/context.rs:1185]: Note that `#[track_caller]` will propagate through all functions in the call chain, so you can just call `err_with_message`

File: src/librustc_middle/ty/context.rs (hunk 4 above)
Comment (eddyb) [reply src/librustc_middle/ty/context.rs]: Which part? Slapping `#[track_caller]` onto functions "just works". The span part I guess it's trickier and you can open an issue about.

File: src/librustc_middle/ty/context.rs (hunk 5 above)
Comment (mark-i-m) [reply src/librustc_middle/ty/context.rs:1185]: Ah, I didn't know that! Thanks. And now I think I understand @eddyb's comment above.

**Comment by nikomatsakis** [comment]
Hey @mark-i-m -- I don't think this necessarily requires an MCP, though doing one to advertise the new convention wouldn't hurt (I'd be inclined to say that @eddyb or whomever could just second it and skip the FCP period). That said, is the proper way to use `Error` documented in the rustc-dev-guide? Seems like it would be a good thing to document, but I'm guessing you're on top of that regardless.

File: src/librustc_middle/ty/context.rs (hunk 4 above)
Comment (mark-i-m) [reply src/librustc_middle/ty/context.rs]: Opened #72619

**Comment by eddyb** [comment]
Actually, is `err` a good name? The old convention would be `mk_err` or `mk_error`.

Maybe we should replace `mk_` with `ty_`? That would mean `tcx.ty_error()`, which is IMO better.

**Comment by mark-i-m** [comment]
@nikomatsakis I opened https://github.com/rust-lang/rustc-dev-guide/pull/715

**Comment by mark-i-m** [comment]
@eddyb Renamed.

**Comment by mark-i-m** [comment]
I filed the following MCP: https://github.com/rust-lang/compiler-team/issues/297

**Comment by mark-i-m** [comment]
Renamed `ty_error_const` to `const_error` as per @eddyb's request on zulip. Still waiting for MCP.

File: src/librustc_middle/ty/context.rs [hunk 6]
```diff
@@ -1143,6 +1141,31 @@ impl<'tcx> TyCtxt<'tcx> {
...
+
+    /// Constructs a `TyKind::Error` type and registers a `delay_span_bug` with the given `msg to
+    /// ensure it gets used.
+    #[track_caller]
+    pub fn ty_error_with_message<S: Into<MultiSpan>>(self, span: S, msg: &str) -> Ty<'tcx> {
+        self.sess.delay_span_bug(span, msg);
+        self.mk_ty(Error(super::sty::DelaySpanBugEmitted(())))
+    }
+
+    /// Like `err` but for constants.
```
Comment (lcnr) [inline src/librustc_middle/ty/context.rs:1158]:
```suggestion
    /// Like `ty_error` but for constants.
```

**Comment by nikomatsakis** [comment]
Note: MCP was accepted, no need to block on that.

**Comment by varkor** [comment]
r=me after rebasing.

**Comment by mark-i-m** [comment]
For some reason I'm having a bit of trouble with this rebase... going to squash some commits and try again...

**Comment by mark-i-m** [comment]
Ok, this should be ready I think. I squashed 4 of the original commits together into 
268decb

**Comment by mark-i-m** [comment]
Cool! CI is passing :)

File: src/librustc_middle/ty/sty.rs [hunk 7]
```diff
@@ -203,9 +203,26 @@ pub enum TyKind<'tcx> {
...
+    Debug,
+    Eq,
+    Hash,
+    PartialEq,
+    PartialOrd,
+    Ord,
+    RustcEncodable,
+    RustcDecodable,
+    HashStable
+)]
```
Comment (lzutao) [inline src/librustc_middle/ty/sty.rs:223]:
```suggestion
#[derive(Copy, Clone, Debug, Eq, Hash, PartialEq, PartialOrd, Ord)]
#[derive(RustcEncodable, RustcDecodable, HashStable)]
```

Comment (mark-i-m) [reply src/librustc_middle/ty/sty.rs:223]: Hmm... is this what we do elsewhere? personally i prefer the current version.

Comment (varkor) [reply src/librustc_middle/ty/sty.rs:223]: [Yes, we do.](https://github.com/rust-lang/rust/blob/a59264b01247836c70e24217e0d346b868387525/src/librustc_ast/ast.rs#L729-L730) Sorry, I forgot about this.
