### PR TITLE
Limit storage duration of inlined always live locals

### LINKED ISSUE #76375: Broken MIR: generator contains type ... after copy & destination propagation
x.rs:
```rust
#![crate_type = "lib"]

#[inline(always)]
pub fn f(s: bool) -> String {
    let a = "Hello world!".to_string();
    let b = a;
    let c = b;
    if s {
        c
    } else {
        String::new()
    }
}
```
y.rs
```rust
#![crate_type = "lib"]

pub async fn g() {
    x::f(true);
    h().await;
}

pub async fn h() {}
```

```console
$ rustc --edition=2018 -Zmir-opt-level=2 x.rs -Zunsound-mir-opts x.rs
$ rustc --edition=2018 -Zmir-opt-level=2 y.rs --extern x -L.
error: internal compiler error: src/librustc_mir/transform/generator.rs:752:13: Broken MIR: generator contains type std::string::String in MIR, but typeck only knows about {std::future::ResumeTy, impl std::future::Future, ()}
```

The copy propagation removes storage markers during optimization. Afterwards state transforms considers them to be always live across yield. Due to pass ordering, requires inliner to expose the issue.

### PR DESCRIPTION
**Pull request by tmiasko**
Closes #76375.

### CODE REVIEW

File: compiler/rustc_mir/src/transform/inline.rs [hunk 1]
```diff
@@ -492,6 +499,32 @@ impl Inliner<'tcx> {
...
+                        if integrator.always_live_locals.contains(local) {
+                            let new_local = integrator.map_local(local);
+                            caller_body[callsite.block].statements.push(Statement {
+                                source_info: callsite.source_info,
+                                kind: StatementKind::StorageLive(new_local),
+                            });
+                        }
+                    }
+                    if let Some(block) = callsite.target {
+                        let mut n = 0;
```
Comment (oli-obk) [inline compiler/rustc_mir/src/transform/inline.rs:513]: Leave a comment that these statements are added in the beginning of the block by adding them to the end and then rotating them to the front.

Alternatively use the [mir patch system](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_mir/util/patch/struct.MirPatch.html).

File: compiler/rustc_mir/src/transform/inline.rs [hunk 2]
```diff
@@ -70,6 +70,10 @@ fn inline(tcx: TyCtxt<'tcx>, body: &mut Body<'tcx>) -> bool {
     let mut this = Inliner {
         tcx,
         param_env: tcx.param_env_reveal_all_normalized(body.source.def_id()),
+        // FIXME: MIR optimization that run at mir-opt-level >= 2 might remove storage makers for
+        // some locals. This breaks compatibility with state transform that runs after inlining.
+        // As a workaround, we give such locals a storage for the duration of the call.
+        insert_storage_markers: tcx.sess.opts.debugging_opts.mir_opt_level >= 2,
```
Comment (oli-obk) [inline compiler/rustc_mir/src/transform/inline.rs:76]: So the real fix would be to make sure we do not lose storage markers? Are you sure it's lost storage markers and not simply "never added" ones? I was sure we have lots of locals without storage markers. 

Or maybe we should just go for full https://github.com/rust-lang/rust/issues/68622 anyway...

Comment (tmiasko) [reply compiler/rustc_mir/src/transform/inline.rs]: > So the real fix would be to make sure we do not lose storage markers?

This is what I had in mind originally, but we can also consider it to be a valid transformation even if it is suboptimal.

> I was sure we have lots of locals without storage markers.

Locals marked as internal do not participate in validation performed by the state transform. Though, In that context I think it makes sense to always limit storage of those locals simply to help stack space optimizations.

> maybe we should just go for full #68622 anyway...

It is unclear to me how the end of storage could be determined, especially for any local whose address escapes at some point.

Comment (oli-obk) [reply compiler/rustc_mir/src/transform/inline.rs]: > It is unclear to me how the end of storage could be determined, especially for any local whose address escapes at some point.

Ah, we'd still have a "StorageDead" of sorts: `InvalidateBorrows`. It's not quite the same thing, but it will allow us to figure out that if we manually computed a `StorageDead`, it could not be before an `InvalidateBorrows` of the same local.

File: compiler/rustc_mir/src/transform/inline.rs [hunk 3]
```diff
@@ -492,6 +493,34 @@ impl Inliner<'tcx> {
                     }
                 }
 
+                // If there are any locals without storage markers, give them storage only for the
+                // duration of the call.
+                for local in callee_body.vars_and_temps_iter() {
```
Comment (bjorn3) [inline compiler/rustc_mir/src/transform/inline.rs:498]: Locals without storage markers are often on the unwind path where they are deliberately not emitted.

**Comment by tmiasko** [comment]
Blocked on #78966 (tests need to be updated after it lands).

**Comment by tmiasko** [comment]
Updated tests. This is now unblocked.
