### PR TITLE
Populate effective visibilities in `rustc_privacy` (take 2)

### LINKED ISSUE #111359: Regression: missing_debug_implementations linting on private items  when used as parameter in trait impl
(As a lint regression it is not a true "breaking" regression, but it's still strange behavior, categorizing as a regression.)

### Code

(Also reproducible with `cargo check --no-default-features` in https://github.com/unicode-org/icu4x/tree/3a00b1efc12d8fac2aa84b04f85508e3b75bca4c/provider/datagen)

```rust
#[deny(missing_debug_implementations)]
#[allow(unused)]

pub mod foo {
    struct Bar;

    impl<'a> TryFrom<Bar> for u8 {
        type Error = ();
        fn try_from(o: Bar) -> Result<Self, ()> {
            unimplemented!()
        }
    }
}
```

```
[09:57:34] मanishearth@manishearth-glaptop2 ~/sand/crates/bar O_o 
$ cargo +nightly c
    Checking bar v0.1.0 (/home/manishearth/sand/crates/bar)
error: type does not implement `Debug`; consider adding `#[derive(Debug)]` or a manual implementation
 --> src/lib.rs:5:5
  |
5 |     struct Bar;
  |     ^^^^^^^^^^^
  |
note: the lint level is defined here
 --> src/lib.rs:1:8
  |
1 | #[deny(missing_debug_implementations)]
  |        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: could not compile `bar` (lib) due to previous error
```

### Version it worked on

It most recently worked on: nightly-2023-05-06

### Version with regression

`rustc --version`: nightly-2023-05-07

### PR DESCRIPTION
**Pull request by Bryanskiy**
Same as https://github.com/rust-lang/rust/pull/110907 + regressions fixes.
Fixes https://github.com/rust-lang/rust/issues/111359.

r? @petrochenkov

### CODE REVIEW

File: compiler/rustc_lint/src/builtin.rs [hunk 1]
```diff
@@ -766,7 +768,9 @@ impl_lint_pass!(MissingDebugImplementations => [MISSING_DEBUG_IMPLEMENTATIONS]);
 
 impl<'tcx> LateLintPass<'tcx> for MissingDebugImplementations {
     fn check_item(&mut self, cx: &LateContext<'_>, item: &hir::Item<'_>) {
-        if !cx.effective_visibilities.is_reachable(item.owner_id.def_id) {
+        if !(cx.effective_visibilities.is_reachable(item.owner_id.def_id)
+            && cx.tcx.local_visibility(item.owner_id.def_id).is_public())
+        {
```
Comment (petrochenkov) [inline compiler/rustc_lint/src/builtin.rs:773]: These fixes need a test .

File: tests/ui/resolve/auxiliary/foreign-priv-aux.rs [hunk 2]
```diff
@@ -0,0 +1,21 @@
...
+
+pub trait PubTrait {
+    fn pub_fn(&self);
+}
+
+impl<T: PrivTrait> PubTrait for Wrapper<T> {
+    fn pub_fn(&self) {
+        self.0.priv_fn()
+    }
+}
```
Comment (petrochenkov) [inline tests/ui/resolve/auxiliary/foreign-priv-aux.rs:21]: This test was already added in https://github.com/rust-lang/rust/pull/111371.

File: compiler/rustc_privacy/src/lib.rs [hunk 3]
```diff
@@ -739,7 +739,18 @@ impl<'tcx> Visitor<'tcx> for EmbargoVisitor<'tcx> {
...
+                    {
+                        self.update_eff_vis(
+                            impl_item_ref.id.owner_id.def_id,
+                            item_ev,
+                            None,
+                            Level::Direct,
+                        );
+                    } else {
+                        self.update(impl_item_ref.id.owner_id.def_id, item_ev, Level::Direct);
+                    }
```
Comment (petrochenkov) [inline compiler/rustc_privacy/src/lib.rs:753]: I'm still not sure how exactly, but monomorphization collector (compiler\rustc_monomorphize\src\collector.rs) requires that if the trait impl is reachable, then its items should be reachable as well.
So the condition here should be
```rust
let nominal_vis = if impl_.of_trait.is_none().then(|| self.tcx.local_visibility(def_id));
self.update_eff_vis(impl_item_ref.id.owner_id.def_id, item_ev, nominal_vis, Level::Direct);
```

**Comment by petrochenkov** [comment]
@craterbot check

**Comment by petrochenkov** [comment]
Not sure why the report wasn't generated.
Logs for regressed crates can be found in https://crater-reports.s3.amazonaws.com/pr-111425/logs-archives/regressed.tar.gz, all the regressions are spurious.
@bors r+

**Comment by petrochenkov** [comment]
Analysis of the perf regressions - https://github.com/rust-lang/rust/pull/110907#issuecomment-1536344039.

https://github.com/rust-lang/rust/pull/111260 should compensate for most of them.
