### PR TITLE
Move `Const::{from_anon_const,try_from_lit}` to hir_ty_lowering

### LINKED ISSUE #128176: ICE: `unexpected const arg parent in type_of()`
auto-reduced (treereduce-rust):
````rust
#![feature(generic_const_exprs)]
#![feature(object_safe_for_dispatch)]
trait X {
    type Y<const N: i16>;
}

const _: () = {
    fn f2<'a>(arg: Box<dyn X<Y<1> = &'a ()>>) {}
};

fn main() {}

````

original:
````rust
#![feature(generic_const_exprs)]
#![allow(bar_to, bar_from)]

trait X {
    type Y<const N: i16>;
}

const _: () = {
    fn f2<'a>(arg: Box<dyn X<Y<1> = &'a ()>>) {}
    //~^ ERROR associated type takes 1 lifetime argument but 0 lifetime arguments
    //~| ERROR associated type takes 0 generic arguments but 1 generic argument
    //~| ERROR associated type takes 1 lifetime argument but 0 lifetime arguments
    //~| ERROR associated type takes 0 generic arguments but 1 generic argument
    //~| ERROR associated type takes 1 lifetime argument but 0 lifetime arguments
    //~| ERROR associated type takes 0 generic arguments but 1 generic argument
    //~| ERROR `X` cannot be made into an object
};

fn main() {}

````

Version information
````
rustc 1.82.0-nightly (004e155c4 2024-07-25)
binary: rustc
commit-hash: 004e155c46a2083d4f73212cc47a6f7fb98fcbd1
commit-date: 2024-07-25
host: x86_64-unknown-linux-gnu
release: 1.82.0-nightly
LLVM version: 18.1.7

````

Command:
`/home/matthias/.rustup/toolchains/master/bin/rustc -Zcrate-attr=feature(object_safe_for_dispatch)`

<details><summary><strong>Program output</strong></summary>
<p>

```
warning: the feature `generic_const_exprs` is incomplete and may not be safe to use and/or cause compiler crashes
 --> /tmp/icemaker_global_tempdir.IthovrlrGpyV/rustc_testrunner_tmpdir_reporting.lRekHjsPjvYq/mvce.rs:1:12
  |
1 | #![feature(generic_const_exprs)]
  |            ^^^^^^^^^^^^^^^^^^^
  |
  = note: see issue #76560 <https://github.com/rust-lang/rust/issues/76560> for more information
  = note: `#[warn(incomplete_features)]` on by default

warning: unused variable: `arg`
 --> /tmp/icemaker_global_tempdir.IthovrlrGpyV/rustc_testrunner_tmpdir_reporting.lRekHjsPjvYq/mvce.rs:8:15
  |
8 |     fn f2<'a>(arg: Box<dyn X<Y<1> = &'a ()>>) {}
  |               ^^^ help: if this is intentional, prefix it with an underscore: `_arg`
  |
  = note: `#[warn(unused_variables)]` on by default

warning: trait `X` is never used
 --> /tmp/icemaker_global_tempdir.IthovrlrGpyV/rustc_testrunner_tmpdir_reporting.lRekHjsPjvYq/mvce.rs:3:7
  |
3 | trait X {
  |       ^
  |
  = note: `#[warn(dead_code)]` on by default

warning: 3 warnings emitted

note: no errors encountered even though delayed bugs were created

note: those delayed bugs will now be shown as internal compiler errors

error: internal compiler error: unexpected const arg parent in type_of(): AssocItemConstraint(AssocItemConstraint { hir_id: HirId(DefId(0:7 ~ mvce[807a]::_::f2).13), ident: Y#0, gen_args: GenericArgs { args: [Const(ConstArg { hir_id: HirId(DefId(0:7 ~ mvce[807a]::_::f2).9), kind: Anon(AnonConst { hir_id: HirId(DefId(0:7 ~ mvce[807a]::_::f2).7), def_id: DefId(0:9 ~ mvce[807a]::_::f2::{constant#0}), body: BodyId { hir_id: HirId(DefId(0:7 ~ mvce[807a]::_::f2).8) }, span: /tmp/icemaker_global_tempdir.IthovrlrGpyV/rustc_testrunner_tmpdir_reporting.lRekHjsPjvYq/mvce.rs:8:32: 8:33 (#0) }), is_desugared_from_effects: false })], constraints: [], parenthesized: No, span_ext: /tmp/icemaker_global_tempdir.IthovrlrGpyV/rustc_testrunner_tmpdir_reporting.lRekHjsPjvYq/mvce.rs:8:31: 8:34 (#0) }, kind: Equality { term: Ty(Ty { hir_id: HirId(DefId(0:7 ~ mvce[807a]::_::f2).12), kind: Ref(Lifetime { hir_id: HirId(DefId(0:7 ~ mvce[807a]::_::f2).10), ident: 'a#0, res: Param(DefId(0:8 ~ mvce[807a]::_::f2::'a)) }, MutTy { ty: Ty { hir_id: HirId(DefId(0:7 ~ mvce[807a]::_::f2).11), kind: Tup([]), span: /tmp/icemaker_global_tempdir.IthovrlrGpyV/rustc_testrunner_tmpdir_reporting.lRekHjsPjvYq/mvce.rs:8:41: 8:43 (#0) }, mutbl: Not }), span: /tmp/icemaker_global_tempdir.IthovrlrGpyV/rustc_testrunner_tmpdir_reporting.lRekHjsPjvYq/mvce.rs:8:37: 8:43 (#0) }) }, span: /tmp/icemaker_global_tempdir.IthovrlrGpyV/rustc_testrunner_tmpdir_reporting.lRekHjsPjvYq/mvce.rs:8:30: 8:43 (#0) })
 --> /tmp/icemaker_global_tempdir.IthovrlrGpyV/rustc_testrunner_tmpdir_reporting.lRekHjsPjvYq/mvce.rs:8:32
  |
8 |     fn f2<'a>(arg: Box<dyn X<Y<1> = &'a ()>>) {}
  |                                ^
  |
note: delayed at compiler/rustc_hir_analysis/src/collect/type_of.rs:276:20 - disabled backtrace
 --> /tmp/icemaker_global_tempdir.IthovrlrGpyV/rustc_testrunner_tmpdir_reporting.lRekHjsPjvYq/mvce.rs:8:32
  |
8 |     fn f2<'a>(arg: Box<dyn X<Y<1> = &'a ()>>) {}
  |                                ^

error: internal compiler error: Const::from_anon_const: couldn't lit_to_const TypeError
 --> /tmp/icemaker_global_tempdir.IthovrlrGpyV/rustc_testrunner_tmpdir_reporting.lRekHjsPjvYq/mvce.rs:8:32
  |
8 |     fn f2<'a>(arg: Box<dyn X<Y<1> = &'a ()>>) {}
  |                                ^
  |
note: delayed at compiler/rustc_middle/src/ty/consts.rs:309:31 - disabled backtrace
 --> /tmp/icemaker_global_tempdir.IthovrlrGpyV/rustc_testrunner_tmpdir_reporting.lRekHjsPjvYq/mvce.rs:8:32
  |
8 |     fn f2<'a>(arg: Box<dyn X<Y<1> = &'a ()>>) {}
  |                                ^

error: internal compiler error: Trying to feed an already recorded value for query type_of key=DefId(0:9 ~ mvce[807a]::_::f2::{constant#0}):
                                old value: EarlyBinder { value: {type error} }
                                new value: EarlyBinder { value: i16 }
  |
  = note: delayed at compiler/rustc_middle/src/query/mod.rs:2294:1 - disabled backtrace

error: internal compiler error: mir_const_qualif: MIR had errors
 --> /tmp/icemaker_global_tempdir.IthovrlrGpyV/rustc_testrunner_tmpdir_reporting.lRekHjsPjvYq/mvce.rs:8:32
  |
8 |     fn f2<'a>(arg: Box<dyn X<Y<1> = &'a ()>>) {}
  |                                ^
  |
note: delayed at compiler/rustc_mir_transform/src/lib.rs:271:19 - disabled backtrace
 --> /tmp/icemaker_global_tempdir.IthovrlrGpyV/rustc_testrunner_tmpdir_reporting.lRekHjsPjvYq/mvce.rs:8:32
  |
8 |     fn f2<'a>(arg: Box<dyn X<Y<1> = &'a ()>>) {}
  |                                ^

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: please make sure that you have updated to the latest nightly

note: rustc 1.82.0-nightly (004e155c4 2024-07-25) running on x86_64-unknown-linux-gnu

note: compiler flags: -Z crate-attr=feature(object_safe_for_dispatch) -Z dump-mir-dir=dir

query stack during panic:
end of query stack

```

</p>
</details>

@rustbot label +F-generic_const_exprs +F-object_safe_for_dispatch

### PR DESCRIPTION
**Pull request by camelid**
Fixes #128176.
This accomplishes one of the followup items from #131081.

These operations are much more about lowering the HIR than about
`Const`s themselves. They fit better in hir_ty_lowering with
`lower_const_arg` (formerly `Const::from_const_arg`) and the rest.

To accomplish this, `const_evaluatable_predicates_of` had to be changed
to not use `from_anon_const` anymore. Instead of visiting the HIR and
lowering anon consts on the fly, it now visits the `rustc_middle::ty`
data structures instead and directly looks for `UnevaluatedConst`s. This
approach was proposed in:
https://github.com/rust-lang/rust/pull/131081#discussion_r1821189257

r? @BoxyUwU

### CODE REVIEW

File: compiler/rustc_hir_analysis/src/collect/predicates_of.rs [hunk 1]
```diff
@@ -369,61 +370,81 @@ fn compute_bidirectional_outlives_predicates<'tcx>(
...
+            of_trait.instantiate_identity().visit_with(&mut collector);
         }
 
-        debug!("const_evaluatable_predicates_of({:?}): visit_self_ty", def_id);
-        collector.visit_ty(impl_.self_ty);
-    }
-
-    if let Some(generics) = node.generics() {
-        debug!("const_evaluatable_predicates_of({:?}): visit_generics", def_id);
-        collector.visit_generics(generics);
```
Comment (camelid) [inline compiler/rustc_hir_analysis/src/collect/predicates_of.rs:419]: I couldn't really think of anything that would need this, nor what the `rustc_middle::ty`-equivalent would be. All the tests passed though.

**Comment by camelid** [comment]
Curious if this improves performance since we no longer re-lower const args.

@bors try @rust-timer queue

File: compiler/rustc_hir_analysis/src/collect/predicates_of.rs (hunk 1 above)
Comment (BoxyUwU) [reply compiler/rustc_hir_analysis/src/collect/predicates_of.rs:419]: yeah its a bit weird, `hir::Generics` is some amalgamation of `generics_of`, and *some* `predicates_of` (inline written bounds, e.g. `<T: Trait>`). We don't really care about `generics_of` since we don't want to add const evaluatable bounds for const parameter defaults, and any const arguments in types of const parmeters (e.g. `<const N: Bar<{ 10 }>>`) must be fully concrete so there's no need to add const evaluatable bounds for them.

So yeah :+1: to removing this

File: tests/ui/const-generics/issues/cg-in-dyn-issue-128176.rs [hunk 2]
```diff
@@ -1,7 +1,11 @@
-//@ known-bug: rust-lang/rust#128176
+//@ check-pass
+
+// Regression test for #128176.
```
Comment (BoxyUwU) [inline tests/ui/const-generics/issues/cg-in-dyn-issue-128176.rs:3]:
```suggestion
// Regression test for #128176. Previously we would call `type_of` on the `1` anon const before the anon const had been lowered having `type_of` fed with a correct type.
```

**Review by BoxyUwU — COMMENTED** [review]
very cool! :3 small review + fixing the intra doc link that's now broken then should be good to go

**Comment by BoxyUwU** [comment]
I wouldn't have really expected any perf effects since most of this PR only has an effect under `generic_const_exprs` so good that it's neutral :3

File: compiler/rustc_hir_analysis/src/collect/predicates_of.rs [hunk 3]
```diff
@@ -369,61 +370,80 @@ fn compute_bidirectional_outlives_predicates<'tcx>(
...
-            // these get checked when they are actually instantiated.
-            //
-            // We do not want the following to error:
-            //
-            //     struct Foo<const N: usize, const M: usize = { N + 1 }>;
-            //     struct Bar<const N: usize>(Foo<N, 3>);
+    impl<'tcx> TypeVisitor<TyCtxt<'tcx>> for ConstCollector<'tcx> {
+        fn visit_const(&mut self, c: ty::Const<'tcx>) {
+            if let ty::ConstKind::Unevaluated(uv) = c.kind() {
+                if is_const_param_default(self.tcx, uv.def.expect_local()) {
```
[the remark this answers is not in the document]
Comment (camelid) [reply compiler/rustc_hir_analysis/src/collect/predicates_of.rs:401]: This was actually necessary to fix a test failure. We do visit generics of types within function signatures. E.g. if we have a struct `Foo<const N: usize, const M: usize = {N+1}>` and then a function returning `Foo<N1>`, this requires an explicit bound. If we don't do this check, we add it implicitly and don't require it from the user, which is a change from the nightly behavior.

[the remark this answers is not in the document]
Comment (BoxyUwU) [reply compiler/rustc_hir_analysis/src/collect/predicates_of.rs:401]: Oh that is very true, :3

**Comment by BoxyUwU** [comment]
@bors r+

don't need to block this PR on figuring out exactly why that test stopped ICEing since its gce only
