### PR TITLE
canonicalize consts before calling try_unify_abstract_consts query

### LINKED ISSUE #77708: StableHasher: unexpected region with impl trait for type with complex generic constant
### Code

Assuming the following header:
```Rust
#![feature(const_generics, const_evaluatable_checked)]
#![allow(incomplete_features)]
use core::{convert::TryFrom, num::NonZeroUsize};

struct A<const N: NonZeroUsize>([u8; N.get()]) where [u8; N.get()]: Sized;
```
The following example in trait impl causes an ICE:
```Rust
impl<'a, const N: NonZeroUsize> TryFrom<&'a [u8]> for A<N> where [u8; N.get()]: Sized {
	type Error = ();
	fn try_from(slice: &'a [u8]) -> Result<A<N>, ()> {
		let _x = <&[u8; N.get()] as TryFrom<&[u8]>>::try_from(slice);
		unimplemented!();
	}
}
```
The following without a trait implementation does not:
```Rust
fn try_from<'a, const N: NonZeroUsize>(slice: &'a [u8]) -> Result<A<N>, ()> where [u8; N.get()]: Sized {
	let x = <&[u8; N.get()] as TryFrom<&[u8]>>::try_from(slice);
	unimplemented!();
}
```
Neither does the equivalent implementation without `const_evaluatable_checked`:
```Rust
struct B<const N: usize>([u8; N]) where [u8; N]: Sized;

impl<'a, const N: usize> TryFrom<&'a [u8]> for B<N> where [u8; N]: Sized {
	type Error = ();
	fn try_from(slice: &'a [u8]) -> Result<B<N>, ()> {
		let _x = <&[u8; N] as TryFrom<&[u8]>>::try_from(slice);
		unimplemented!();
	}
}
```

### Meta

`rustc --version --verbose`:
```
rustc 1.49.0-nightly (91a79fb29 2020-10-07)
binary: rustc
commit-hash: 91a79fb29ac78d057d04dbe86be13d5dcc64309a
commit-date: 2020-10-07
host: x86_64-pc-windows-msvc
release: 1.49.0-nightly
LLVM version: 11.0
```

### Error output

`cargo check`
```
error: internal compiler error: compiler\rustc_middle\src\ich\impls_ty.rs:94:17: StableHasher: unexpected region '_#2r

thread 'rustc' panicked at 'Box<Any>', compiler\rustc_errors\src\lib.rs:945:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.49.0-nightly (91a79fb29 2020-10-07) running on x86_64-pc-windows-msvc

note: compiler flags: -C embed-bitcode=no -C debuginfo=2 -C incremental --crate-type lib

note: some of the compiler flags provided by cargo are hidden

error: aborting due to previous error; 2 warnings emitted
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
stack backtrace:
   0:     0x7ff947a09989 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hc20a26e0f7659afd
   1:     0x7ff947a370bb - core::fmt::write::h435be716304d26a1
   2:     0x7ff9479fb1d8 - <std::io::IoSlice as core::fmt::Debug>::fmt::h997d94c78f1ba97b
   3:     0x7ff947a0ed74 - std::panicking::take_hook::hbf7e33d26fc3ca30
   4:     0x7ff947a0e958 - std::panicking::take_hook::hbf7e33d26fc3ca30
   5:     0x7ff8fbdcf5a7 - rustc_driver::report_ice::h901ed469a4afd632
   6:     0x7ff947a0f7d0 - std::panicking::rust_panic_with_hook::h19068ccbe4b337a1
   7:     0x7ff900537870 - <rustc_errors::snippet::Style as core::fmt::Debug>::fmt::h154d3f8b7cc27034
   8:     0x7ff900537799 - <rustc_errors::snippet::Style as core::fmt::Debug>::fmt::h154d3f8b7cc27034
   9:     0x7ff9005377e1 - <rustc_errors::snippet::Style as core::fmt::Debug>::fmt::h154d3f8b7cc27034
  10:     0x7ff90056a80f - rustc_errors::HandlerInner::err_count::hc7ff30e58befa0c0
  11:     0x7ff900568ec2 - rustc_errors::Handler::bug::h9f679e586b05b709
  12:     0x7ff900043d4f - rustc_middle::util::bug::bug_fmt::h333e4a32fa9b0768
  13:     0x7ff90003fe70 - <rustc_middle::ty::consts::int::ConstInt as core::fmt::Debug>::fmt::he16df1c1cd9a0739
  14:     0x7ff90003fe13 - <rustc_middle::ty::consts::int::ConstInt as core::fmt::Debug>::fmt::he16df1c1cd9a0739
  15:     0x7ff900043c7c - rustc_middle::util::bug::bug_fmt::h333e4a32fa9b0768
  16:     0x7ff900043be0 - rustc_middle::util::bug::bug_fmt::h333e4a32fa9b0768
  17:     0x7ff90003bd54 - rustc_middle::ich::impls_ty::<impl rustc_data_structures::stable_hasher::HashStable<rustc_middle::ich::hcx::StableHashingContext> for rustc_middle::ty::sty::RegionKind>::hash_stable::h1b2fcdca26fe65c7
  18:     0x7ff8fe089e72 - rustc_ty::provide::h0935123a64901122
  19:     0x7ff8ffccce57 - <rustc_trait_selection::traits::fulfill::PendingPredicateObligation as core::fmt::Debug>::fmt::h193f29610c75bb2a
  20:     0x7ff8ffb69daf - <rustc_trait_selection::traits::TraitQueryMode as core::fmt::Debug>::fmt::h933d8945b4748b17
  21:     0x7ff8ffc24e3d - <rustc_trait_selection::traits::specialize::OverlapError as core::fmt::Debug>::fmt::hb9cecb2f776e6243
  22:     0x7ff8ffcca571 - rustc_trait_selection::traits::fulfill::FulfillProcessor::progress_changed_obligations::h6e0b9a7a32cf419d
  23:     0x7ff8ffcf7944 - <rustc_trait_selection::traits::fulfill::PendingPredicateObligation as core::fmt::Debug>::fmt::h193f29610c75bb2a
  24:     0x7ff8ffcc9b3f - <rustc_trait_selection::traits::fulfill::FulfillmentContext as rustc_infer::traits::engine::TraitEngine>::select_where_possible::h1148d87c05c2aec0
  25:     0x7ff8fe12fb9f - <rustc_middle::ty::sty::TraitRef as rustc_traits::chalk::lowering::LowerInto<chalk_solve::rust_ir::TraitBound<rustc_middle::traits::chalk::RustInterner>>>::lower_into::h8ff0d70e3d0188ac
  26:     0x7ff8fe1234e1 - <rustc_middle::ty::sty::TraitRef as rustc_traits::chalk::lowering::LowerInto<chalk_solve::rust_ir::TraitBound<rustc_middle::traits::chalk::RustInterner>>>::lower_into::h8ff0d70e3d0188ac
  27:     0x7ff8fe1f56da - <rustc_traits::chalk::db::RustIrDatabase as chalk_solve::RustIrDatabase<rustc_middle::traits::chalk::RustInterner>>::generator_witness_datum::h56e9b357d981663c
  28:     0x7ff8ffca08b2 - <rustc_trait_selection::traits::specialize::OverlapError as core::fmt::Debug>::fmt::hb9cecb2f776e6243
  29:     0x7ff8ffca476b - <rustc_trait_selection::traits::specialize::OverlapError as core::fmt::Debug>::fmt::hb9cecb2f776e6243
  30:     0x7ff8ffb34698 - <rustc_infer::infer::InferCtxt as rustc_trait_selection::traits::query::outlives_bounds::InferCtxtExt>::implied_outlives_bounds::h491f1d8abd137254
  31:     0x7ff8ffca8e4b - <rustc_trait_selection::traits::specialize::OverlapError as core::fmt::Debug>::fmt::hb9cecb2f776e6243
  32:     0x7ff8ffc536c3 - <rustc_trait_selection::traits::specialize::OverlapError as core::fmt::Debug>::fmt::hb9cecb2f776e6243
  33:     0x7ff8ffccc165 - rustc_trait_selection::traits::query::type_op::ascribe_user_type::<impl rustc_trait_selection::traits::query::type_op::QueryTypeOp for rustc_middle::traits::query::type_op::AscribeUserType>::perform_query::h79d7e0f340ea47eb
  34:     0x7ff8ff026445 - <rustc_mir::transform::dest_prop::CandidateAssignment as core::fmt::Debug>::fmt::h52c7195478494fc1
  35:     0x7ff8fec586c0 - <rustc_middle::mir::traversal::ReversePostorder as core::iter::traits::iterator::Iterator>::size_hint::h344f471fd1cfc36d
  36:     0x7ff8fef20f53 - <rustc_middle::ty::sty::RegionVid as rustc_mir::borrow_check::facts::FactRow>::write::h2cc1e203cd8b8d95
  37:     0x7ff8ff0c5d07 - rustc_mir::borrow_check::provide::hca974026c7954712
  38:     0x7ff8febc3d7b - <rustc_mir_build::thir::pattern::_match::split_grouped_constructors::Border as core::fmt::Debug>::fmt::h2468913b704d8b89
  39:     0x7ff8ff0c2e00 - rustc_mir::borrow_check::provide::hca974026c7954712
  40:     0x7ff8ff092e9f - <rustc_mir::util::spanview::SpanViewable as core::fmt::Debug>::fmt::h8fc74e5ad64e2a6b
  41:     0x7ff8fbfc9fae - rustc_interface::interface::parse_cfgspecs::hf1434c0a659b9ddd
  42:     0x7ff8fbfb7326 - <rls_span::serde_expanded::_IMPL_DESERIALIZE_FOR_OneIndexed::<impl serde::de::Deserialize for rls_span::OneIndexed>::deserialize::__Visitor as serde::de::Visitor>::expecting::h9a9b74719e191e7e
  43:     0x7ff8fbf7c877 - <rls_span::serde_expanded::_IMPL_DESERIALIZE_FOR_OneIndexed::<impl serde::de::Deserialize for rls_span::OneIndexed>::deserialize::__Visitor as serde::de::Visitor>::expecting::h9a9b74719e191e7e
  44:     0x7ff8fbfcc3dd - rustc_interface::interface::parse_cfgspecs::hf1434c0a659b9ddd
  45:     0x7ff8fbf69f5e - <rls_span::serde_expanded::_IMPL_DESERIALIZE_FOR_OneIndexed::<impl serde::de::Deserialize for rls_span::OneIndexed>::deserialize::__Visitor as serde::de::Visitor>::expecting::h9a9b74719e191e7e
  46:     0x7ff8fbf7566f - <rls_span::serde_expanded::_IMPL_DESERIALIZE_FOR_OneIndexed::<impl serde::de::Deserialize for rls_span::OneIndexed>::deserialize::__Visitor as serde::de::Visitor>::expecting::h9a9b74719e191e7e
  47:     0x7ff8fbfbc034 - <rls_span::serde_expanded::_IMPL_DESERIALIZE_FOR_OneIndexed::<impl serde::de::Deserialize for rls_span::OneIndexed>::deserialize::__Visitor as serde::de::Visitor>::expecting::h9a9b74719e191e7e
  48:     0x7ff8fbff5d3d - rustc_interface::passes::QueryContext::print_stats::hd29879a8b3af7832
  49:     0x7ff8fbe1957b - tracing_core::event::Event::metadata::h86572d73d587b6bd
  50:     0x7ff8fbe1ddb6 - tracing_core::event::Event::metadata::h86572d73d587b6bd
  51:     0x7ff8fbdddf02 - <rustc_driver::Compilation as core::fmt::Debug>::fmt::h234a3cece69c9eed
  52:     0x7ff8fbdf8ba6 - <rustc_driver::Compilation as core::fmt::Debug>::fmt::h234a3cece69c9eed
  53:     0x7ff8fbd81b26 - rustc_errors::snippet::MultilineAnnotation::increase_depth::h93baa802966d31ca
  54:     0x7ff8fbe1e53b - tracing_core::event::Event::metadata::h86572d73d587b6bd
  55:     0x7ff8fbdf4a34 - <rustc_driver::Compilation as core::fmt::Debug>::fmt::h234a3cece69c9eed
  56:     0x7ff8fbd9074c - <rustc_driver::args::Error as core::fmt::Debug>::fmt::h500583d00d12c2d9
  57:     0x7ff8fbdf6b28 - <rustc_driver::Compilation as core::fmt::Debug>::fmt::h234a3cece69c9eed
  58:     0x7ff8fbdd3a30 - <rustc_driver::Compilation as core::fmt::Debug>::fmt::h234a3cece69c9eed
  59:     0x7ff8fbdfa123 - <rustc_driver::Compilation as core::fmt::Debug>::fmt::h234a3cece69c9eed
  60:     0x7ff8fbd77523 - rustc_errors::snippet::MultilineAnnotation::increase_depth::h93baa802966d31ca
  61:     0x7ff947a1f6a7 - std::sys::windows::thread::Thread::new::h04914a10b014a9d7
  62:     0x7ff99b6c7bd4 - BaseThreadInitThunk
  63:     0x7ff99d2ace51 - RtlUserThreadStart
```

</p>
</details>
<details><summary><strong>Query Stack</strong></summary>
<p>

```
query stack during panic:
#0 [type_op_ascribe_user_type] evaluating `type_op_ascribe_user_type` `Canonical { max_universe: U0, variables: [CanonicalVarInfo { kind: Region(U0) }, CanonicalVarInfo { kind: Region(U0) }, CanonicalVarInfo { kind: Region(U0) }, CanonicalVarInfo { kind: Region(U0) }], value: ParamEnvAnd { param_env: ParamEnv { caller_bounds: [ConstEvaluatable(WithOptConstParam { did: DefId(0:15 ~ bugtest[35b2]::{impl#0}::{constant#0}), const_param_did: None }, [ReLateBound(DebruijnIndex(0), BrAnon(0)), Const { ty: std::num::NonZeroUsize, val: Param(N/#1) }]), TraitPredicate(<[u8; _] as std::marker::Sized>)], reveal: UserFacing }, value: AscribeUserType { mir_ty: fn(&[u8]) -> std::result::Result<&[u8; _], <&[u8; _] as std::convert::TryFrom<&[u8]>>::Error> {<&[u8; _] as std::convert::TryFrom<&[u8]>>::try_from}, def_id: DefId(2:1966 ~ core[5e46]::convert::TryFrom::try_from), user_substs: UserSubsts { substs: [&[u8; _], &[u8]], user_self_ty: None } } } }`
#1 [mir_borrowck] borrow-checking `<A<N> as std::convert::TryFrom<&'a [u8]>>::try_from`
#2 [analysis] running analysis passes on this crate
end of query stack
```

</p>
</details>

Possibly related to #77650

### LINKED ISSUE #82034: Panic in nightly rustc with type interference for const_generics
### Code

```Rust
#![feature(const_generics)]
#![feature(const_evaluatable_checked)]
#![allow(incomplete_features)]
pub trait IsTrue {}
pub trait IsFalse {}

pub struct Assert<const CHECK: bool> {}

impl IsTrue for Assert<true> {}
impl IsFalse for Assert<false> {}

pub struct SliceConstWriter<'a, const N: usize> {
    ptr: &'a mut [u8]
}
impl<'a, const N: usize> SliceConstWriter<'a, {N}> {
    pub fn from_slice(vec: &'a mut [u8]) -> Self {
        Self {
            ptr: vec
        }
    }

    pub fn convert<const NN: usize>(mut self) -> SliceConstWriter<'a, {NN}> {
        SliceConstWriter {
            ptr: self.ptr
        }
    }
}

impl<'a, const N: usize> SliceConstWriter<'a, {N}> where Assert::<{N >= 2}>: IsTrue {
    // broken
    pub fn write_u8(mut self) -> SliceConstWriter<'a, {N-2}> {
        self.convert()
    }
    
    //working
    // pub fn write_u8(mut self) -> SliceConstWriter<'a, {N-2}> {
    //     SliceConstWriter {
    //         ptr: self.ptr
    //     }
    // }
}


#[cfg(test)]
mod tests {
    use crate::SliceConstWriter;

    #[test]
    fn it_works() {
        let mut buff = [0u8; 128];
        let mut a = SliceConstWriter::<10>::from_slice(&mut buff);

        let mut a = a.write_u8().write_u8().write_u8().write_u8().write_u8();
    }
}
```

Reproduces in [playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=b8e87af706c05a8ebf4f1fed2f8712c8)

### Meta

`rustc --version --verbose`:
```
rustc 1.52.0-nightly (e9920ef77 2021-02-11)
binary: rustc
commit-hash: e9920ef7749d11fc71cc32ca4ba055bcfeaab945
commit-date: 2021-02-11
host: x86_64-pc-windows-gnu
release: 1.52.0-nightly
LLVM version: 11.0.1

```

### Error output

```
error: internal compiler error: compiler\rustc_middle\src\ich\impls_ty.rs:94:17: StableHasher: unexpected region '_#2r

thread 'rustc' panicked at 'Box<Any>', /rustc/e9920ef7749d11fc71cc32ca4ba055bcfeaab945\library\std\src\panic.rs:59:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.52.0-nightly (e9920ef77 2021-02-11) running on x86_64-pc-windows-gnu

note: compiler flags: -C embed-bitcode=no -C debuginfo=2 -C incremental --crate-type lib

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [type_op_ascribe_user_type] evaluating `type_op_ascribe_user_type` `Canonical { max_universe: U0, variables: [CanonicalVarInfo { kind: Region(U0) }, CanonicalVarInfo { kind: Region(U0) }, CanonicalVarInfo { kind: Region(U0) }, CanonicalVarInfo { kind: Region(U0) }, CanonicalVarInfo { kind: Const(U0) }, Canon
icalVarInfo { kind: Ty(General(U0)) }], value: ParamEnvAnd { param_env: ParamEnv { caller_bounds: [Binder(ConstEvaluatable(WithOptConstParam { did: DefId(0:29 ~ const_writer[f037]::{impl#3}::write_u8::{constant#0}), const_param_did: None }, [ReLateBound(DebruijnIndex(1), BoundRegion { kind: BrAnon(0) }), Const
{ ty: usize, val: Param(N/#1) }])), Binder(ConstEvaluatable(WithOptConstParam { did: DefId(0:26 ~ const_writer[f037]::{impl#3}::{constant#0}), const_param_did: None }, [ReLateBound(DebruijnIndex(1), BoundRegion { kind: BrAnon(0) }), Const { ty: usize, val: Param(N/#1) }])), Binder(TraitPredicate(<Assert<{N >= 2
}> as IsTrue>))], reveal: UserFacing }, value: AscribeUserType { mir_ty: fn(SliceConstWriter<'_, N>) -> SliceConstWriter<'_, {N-2}> {SliceConstWriter::<'_, N>::convert::<{N-2}>}, def_id: DefId(0:20 ~ const_writer[f037]::{impl#2}::convert), user_substs: UserSubsts { substs: [ReLateBound(DebruijnIndex(0), BoundRe
gion { kind: BrAnon(3) }), Const { ty: ^5, val: Bound(DebruijnIndex(0), 4) }, Const { ty: usize, val: Unevaluated(WithOptConstParam { did: DefId(0:30 ~ const_writer[f037]::{impl#3}::write_u8::{constant#1}), const_param_did: Some(DefId(0:21 ~ const_writer[f037]::{impl#2}::convert::NN)) }, [ReLateBound(DebruijnIn
dex(0), BoundRegion { kind: BrAnon(0) }), Const { ty: usize, val: Param(N/#1) }], None) }], user_self_ty: None } } } }`
#1 [mir_borrowck] borrow-checking `SliceConstWriter::<'a, N>::write_u8`
end of query stack
error: aborting due to previous error; 1 warning emitted

```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
error: internal compiler error: compiler\rustc_middle\src\ich\impls_ty.rs:94:17: StableHasher: unexpected region '_#2r

thread 'rustc' panicked at 'Box<Any>', /rustc/e9920ef7749d11fc71cc32ca4ba055bcfeaab945\library\std\src\panic.rs:59:5
stack backtrace:
   0: std::panicking::begin_panic
   1: std::panic::panic_any
   2: rustc_errors::HandlerInner::bug
   3: rustc_errors::Handler::bug
   4: rustc_middle::util::bug::opt_span_bug_fmt::{{closure}}
   5: rustc_middle::ty::context::tls::with_opt::{{closure}}
   6: rustc_middle::ty::context::tls::with_opt
   7: rustc_middle::util::bug::opt_span_bug_fmt
   8: rustc_middle::util::bug::bug_fmt
   9: rustc_middle::ich::impls_ty::<impl rustc_data_structures::stable_hasher::HashStable<rustc_middle::ich::hcx::StableHashingContext> for rustc_middle::ty::sty::RegionKind>::hash_stable
  10: std::thread::local::LocalKey<T>::with
  11: <T as rustc_query_system::dep_graph::dep_node::DepNodeParams<Ctxt>>::to_fingerprint
  12: rustc_query_system::query::plumbing::get_query_impl
  13: rustc_trait_selection::traits::fulfill::FulfillProcessor::progress_changed_obligations
  14: rustc_data_structures::obligation_forest::ObligationForest<O>::process_obligations
  15: <rustc_trait_selection::traits::fulfill::FulfillmentContext as rustc_infer::traits::engine::TraitEngine>::select_where_possible
  16: rustc_infer::infer::canonical::query_response::<impl rustc_infer::infer::InferCtxt>::make_canonicalized_query_response
  17: <rustc_infer::infer::InferCtxtBuilder as rustc_trait_selection::infer::InferCtxtBuilderExt>::enter_canonical_trait_query
  18: rustc_traits::type_op::type_op_ascribe_user_type
  19: rustc_middle::ty::query::<impl rustc_query_system::query::config::QueryAccessors<rustc_middle::ty::context::TyCtxt> for rustc_middle::ty::query::queries::type_op_ascribe_user_type>::compute
  20: rustc_middle::dep_graph::<impl rustc_query_system::dep_graph::DepKind for rustc_middle::dep_graph::dep_node::DepKind>::with_deps
  21: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl
  22: rustc_data_structures::stack::ensure_sufficient_stack
  23: rustc_query_system::query::plumbing::force_query_with_job
  24: rustc_query_system::query::plumbing::get_query_impl
  25: rustc_trait_selection::traits::query::type_op::ascribe_user_type::<impl rustc_trait_selection::traits::query::type_op::QueryTypeOp for rustc_middle::traits::query::type_op::AscribeUserType>::perform_query
  26: rustc_trait_selection::traits::query::type_op::QueryTypeOp::fully_perform_into
  27: <rustc_middle::ty::ParamEnvAnd<Q> as rustc_trait_selection::traits::query::type_op::TypeOp>::fully_perform
  28: rustc_mir::borrow_check::type_check::type_check
  29: rustc_mir::borrow_check::nll::compute_regions
  30: rustc_mir::borrow_check::do_mir_borrowck
  31: rustc_infer::infer::InferCtxtBuilder::enter
  32: rustc_mir::borrow_check::mir_borrowck
  33: rustc_middle::ty::query::<impl rustc_query_system::query::config::QueryAccessors<rustc_middle::ty::context::TyCtxt> for rustc_middle::ty::query::queries::mir_borrowck>::compute
  34: rustc_middle::dep_graph::<impl rustc_query_system::dep_graph::DepKind for rustc_middle::dep_graph::dep_node::DepKind>::with_deps
  35: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl
  36: rustc_data_structures::stack::ensure_sufficient_stack
  37: rustc_query_system::query::plumbing::force_query_with_job
  38: rustc_query_system::query::plumbing::get_query_impl
  39: rustc_query_system::query::plumbing::ensure_query_impl
  40: rustc_interface::passes::analysis
  41: rustc_middle::ty::query::<impl rustc_query_system::query::config::QueryAccessors<rustc_middle::ty::context::TyCtxt> for rustc_middle::ty::query::queries::analysis>::compute
  42: rustc_middle::dep_graph::<impl rustc_query_system::dep_graph::DepKind for rustc_middle::dep_graph::dep_node::DepKind>::with_deps
  43: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl
  44: rustc_data_structures::stack::ensure_sufficient_stack
  45: rustc_query_system::query::plumbing::force_query_with_job
  46: rustc_query_system::query::plumbing::get_query_impl
  47: rustc_interface::passes::QueryContext::enter
  48: rustc_interface::queries::<impl rustc_interface::interface::Compiler>::enter
  49: rustc_span::with_source_map
  50: rustc_interface::interface::create_compiler_and_run
  51: scoped_tls::ScopedKey<T>::set
```

</p>
</details>

### Description
Caught this error while playing with const generics.

After some experiments I concluded error caused by type inference for `SliceConstWriter::convert` method

Error very elusive. Even replacing test block with main function "fixed" it

### LINKED ISSUE #85031: ICE with `const_evaluatable_checked` and lifetime parameter
### Code

```Rust
#![allow(incomplete_features)]
#![feature(const_generics, const_evaluatable_checked)]

pub struct Ref<'a, const NUM: usize>(&'a i32);

impl<'a, const NUM: usize> Ref<'a, NUM> {
    pub fn foo<const A: usize>(r: Ref<'a, A>) -> Self
    where
        ([(); NUM - A], [(); A - NUM]): Sized,
    {
        Self::bar(r)
    }

    pub fn bar<const A: usize>(r: Ref<'a, A>) -> Self
    where
        ([(); NUM - A], [(); A - NUM]): Sized,
    {
        Self(r.0)
    }
}

```

### Meta

`rustc --version --verbose`:
```
rustc 1.54.0-nightly (676ee1472 2021-05-06)
binary: rustc
commit-hash: 676ee14729462585b969bbc52f32c307403f4126
commit-date: 2021-05-06
host: x86_64-unknown-linux-gnu
release: 1.54.0-nightly
LLVM version: 12.0.0
```

### Error output

```thread 'rustc' panicked at 'Box<Any>', /rustc/676ee14729462585b969bbc52f32c307403f4126/library/std/src/panic.rs:59:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.54.0-nightly (676ee1472 2021-05-06) running on x86_64-unknown-linux-gnu

note: compiler flags: -C embed-bitcode=no -C debuginfo=2 -C incremental --crate-type lib

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [typeck] type-checking `<impl at src/lib.rs:6:1: 20:2>::foo`
#1 [typeck_item_bodies] type-checking all item bodies
end of query stack
error: aborting due to previous error

error: could not compile `ice-minimal`

To learn more, run the command again with --verbose.
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```stack backtrace:
   0: std::panicking::begin_panic
   1: std::panic::panic_any
   2: rustc_errors::HandlerInner::bug
   3: rustc_errors::Handler::bug
   4: rustc_middle::ty::context::tls::with_opt
   5: rustc_middle::util::bug::opt_span_bug_fmt
   6: rustc_middle::util::bug::bug_fmt
   7: rustc_middle::ich::impls_ty::<impl rustc_data_structures::stable_hasher::HashStable<rustc_middle::ich::hcx::StableHashingContext> for rustc_middle::ty::sty::RegionKind>::hash_stable
   8: std::thread::local::LocalKey<T>::with
   9: rustc_query_system::dep_graph::dep_node::DepNode<K>::construct
  10: rustc_query_system::query::plumbing::get_query_impl
  11: rustc_query_system::query::plumbing::get_query
  12: <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::try_unify_abstract_consts
  13: rustc_trait_selection::traits::fulfill::FulfillProcessor::progress_changed_obligations
  14: rustc_data_structures::obligation_forest::ObligationForest<O>::process_obligations
  15: <rustc_trait_selection::traits::fulfill::FulfillmentContext as rustc_infer::traits::engine::TraitEngine>::select_where_possible
  16: rustc_typeck::check::fn_ctxt::_impl::<impl rustc_typeck::check::fn_ctxt::FnCtxt>::resolve_vars_with_obligations
  17: rustc_typeck::check::fn_ctxt::_impl::<impl rustc_typeck::check::fn_ctxt::FnCtxt>::structurally_resolved_type
  18: rustc_typeck::check::callee::<impl rustc_typeck::check::fn_ctxt::FnCtxt>::check_call
  19: rustc_typeck::check::expr::<impl rustc_typeck::check::fn_ctxt::FnCtxt>::check_expr_kind
  20: rustc_typeck::check::expr::<impl rustc_typeck::check::fn_ctxt::FnCtxt>::check_expr_with_expectation
  21: rustc_typeck::check::fn_ctxt::checks::<impl rustc_typeck::check::fn_ctxt::FnCtxt>::check_block_with_expected
  22: rustc_typeck::check::expr::<impl rustc_typeck::check::fn_ctxt::FnCtxt>::check_expr_with_expectation
  23: rustc_typeck::check::expr::<impl rustc_typeck::check::fn_ctxt::FnCtxt>::check_return_expr
  24: rustc_typeck::check::check::check_fn
  25: rustc_typeck::check::inherited::InheritedBuilder::enter
  26: rustc_typeck::check::typeck
  27: rustc_middle::dep_graph::<impl rustc_query_system::dep_graph::DepKind for rustc_middle::dep_graph::dep_node::DepKind>::with_deps
  28: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl
  29: rustc_data_structures::stack::ensure_sufficient_stack
  30: rustc_query_system::query::plumbing::force_query_with_job
  31: rustc_query_system::query::plumbing::get_query_impl
  32: <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::typeck
  33: rustc_middle::ty::<impl rustc_middle::ty::context::TyCtxt>::par_body_owners
  34: rustc_typeck::check::typeck_item_bodies
  35: rustc_middle::dep_graph::<impl rustc_query_system::dep_graph::DepKind for rustc_middle::dep_graph::dep_node::DepKind>::with_deps
  36: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl
  37: rustc_data_structures::stack::ensure_sufficient_stack
  38: rustc_query_system::query::plumbing::force_query_with_job
  39: rustc_query_system::query::plumbing::get_query_impl
  40: <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::typeck_item_bodies
  41: rustc_session::utils::<impl rustc_session::session::Session>::time
  42: rustc_typeck::check_crate
  43: rustc_interface::passes::analysis
  44: rustc_middle::dep_graph::<impl rustc_query_system::dep_graph::DepKind for rustc_middle::dep_graph::dep_node::DepKind>::with_deps
  45: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl
  46: rustc_data_structures::stack::ensure_sufficient_stack
  47: rustc_query_system::query::plumbing::force_query_with_job
  48: rustc_query_system::query::plumbing::get_query_impl
  49: <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::analysis
  50: rustc_interface::passes::QueryContext::enter
  51: rustc_interface::queries::<impl rustc_interface::interface::Compiler>::enter
  52: rustc_span::with_source_map
  53: rustc_interface::interface::create_compiler_and_run
  54: scoped_tls::ScopedKey<T>::set
```

</p>
</details>

### LINKED ISSUE #86953: Internal compiler error on implementation with 'complex' constant trait bounds
### Code

The code fragment is located here : [code](https://github.com/Sup3Legacy/stack-bitset/blob/0d5f9f2b6bcd452ab413c366a6035006eca4c1c6/src/lib.rs#L196)

I narrowed down the error to the following block : 

<details><summary><strong>Code fragment</strong></summary>
<p>

```rust
impl<const N: usize, const M: usize> Add<&StackBitSet<M>> for StackBitSet<N>
where
    [(); usize_count(N)]: Sized,
    [(); usize_count(M)]: Sized,
    [(); usize_count(const_min(N, M))]: Sized,
{
    type Output = StackBitSet<{ const_min(N, M) }>;

    fn add(self, other: &StackBitSet<M>) -> StackBitSet<{ const_min(N, M) }> {
        self.union(other)
    }
}
```

</p>
</details>

### Context

I am experimenting with a naive implementation of bitsets, relying heavily on some (as I discovered) unstable features : `const_evaluatable_checked` and `const_generics`. My implementation of the `Add` trait is probably terribly wrong!

**NB: I only get the error with the `Debug` preset. When building on the `Release` preset I don't get any error.**

### Meta

I only provide the data for the nightly compiler, as unstable features are not enabled on the release version.

`rustc --version --verbose`:
```
rustc 1.55.0-nightly (952fdf2a1 2021-07-05)
binary: rustc
commit-hash: 952fdf2a1119affa1b37bcacb0c49cf9f0168ac8
commit-date: 2021-07-05
host: x86_64-unknown-linux-gnu
release: 1.55.0-nightly
LLVM version: 12.0.1
```

### Error output

```
error: internal compiler error: compiler/rustc_middle/src/ich/impls_ty.rs:94:17: StableHasher: unexpected region '_#1r

thread 'rustc' panicked at 'Box<dyn Any>', compiler/rustc_errors/src/lib.rs:1006:9
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
stack backtrace:
   0: std::panicking::begin_panic
   1: std::panic::panic_any
   2: rustc_errors::HandlerInner::bug
   3: rustc_errors::Handler::bug
   4: rustc_middle::ty::context::tls::with_opt
   5: rustc_middle::util::bug::opt_span_bug_fmt
   6: rustc_middle::util::bug::bug_fmt
   7: rustc_middle::ich::impls_ty::<impl rustc_data_structures::stable_hasher::HashStable<rustc_middle::ich::hcx::StableHashingContext> for rustc_middle::ty::sty::RegionKind>::hash_stable
   8: std::thread::local::LocalKey<T>::with
   9: rustc_query_system::dep_graph::dep_node::DepNode<K>::construct
  10: rustc_query_system::query::plumbing::get_query_impl
  11: rustc_query_system::query::plumbing::get_query
  12: <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::try_unify_abstract_consts
  13: rustc_trait_selection::traits::fulfill::FulfillProcessor::progress_changed_obligations
  14: rustc_data_structures::obligation_forest::ObligationForest<O>::process_obligations
  15: <rustc_trait_selection::traits::fulfill::FulfillmentContext as rustc_infer::traits::engine::TraitEngine>::select_where_possible
  16: <rustc_trait_selection::traits::fulfill::FulfillmentContext as rustc_infer::traits::engine::TraitEngine>::select_all_or_error
  17: rustc_infer::infer::InferCtxtBuilder::enter
  18: rustc_typeck::check::compare_method::compare_impl_method
  19: rustc_typeck::check::check::check_item_type
  20: rustc_middle::hir::map::Map::visit_item_likes_in_module
  21: rustc_typeck::check::check::check_mod_item_types
  22: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl
  23: rustc_data_structures::stack::ensure_sufficient_stack
  24: rustc_query_system::query::plumbing::force_query_with_job
  25: rustc_query_system::query::plumbing::get_query_impl
  26: <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::check_mod_item_types
  27: rustc_session::utils::<impl rustc_session::session::Session>::time
  28: rustc_typeck::check_crate
  29: rustc_interface::passes::analysis
  30: rustc_middle::dep_graph::<impl rustc_query_system::dep_graph::DepKind for rustc_middle::dep_graph::dep_node::DepKind>::with_deps
  31: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl
  32: rustc_query_system::dep_graph::graph::DepGraph<K>::with_eval_always_task
  33: rustc_data_structures::stack::ensure_sufficient_stack
  34: rustc_query_system::query::plumbing::force_query_with_job
  35: rustc_query_system::query::plumbing::get_query_impl
  36: <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::analysis
  37: rustc_interface::queries::<impl rustc_interface::interface::Compiler>::enter
  38: rustc_span::with_source_map
  39: rustc_interface::interface::create_compiler_and_run
  40: scoped_tls::ScopedKey<T>::set
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

</p>
</details>

### LINKED ISSUE #88022: ICE const generic and iterator
```rust
#![feature(const_generics)]
#![feature(const_evaluatable_checked)]

struct Buffer<T, const S: usize>
where
    [(); {S * 2}]: Default,
{
    data:         [T; {S * 2}],
}

struct BufferIter<'a, T, const S: usize>(&'a Buffer<T, S>)
where
    [(); {S * 2}]: Default;

impl<'a, T, const S: usize> Iterator for BufferIter<'a, T, S> {
    type Item = &'a T;

    fn next(&mut self) -> Option<Self::Item> {
        None
    }
}
```

Compiler panics
`error: internal compiler error: compiler/rustc_middle/src/ich/impls_ty.rs:94:17: StableHasher: unexpected region '_#0r` 
`thread 'rustc' panicked at 'Box<dyn Any>', compiler/rustc_errors/src/lib.rs:1115:9`

It's the iterator impl that's causing it. 
`rustc 1.56.0-nightly (0fa319039 2021-08-12)`
`compiler flags: -C embed-bitcode=no -C debuginfo=2 -C incremental --crate-type bin`

### PR DESCRIPTION
**Pull request by BoxyUwU**
Fixes #88022
Fixes #86953
Fixes #77708
Fixes #82034
Fixes #85031

these ICEs were all caused by calling the `try_unify_abstract_consts` query with inference vars in substs

r? @lcnr

### CODE REVIEW

File: compiler/rustc_infer/src/infer/mod.rs [hunk 1]
```diff
@@ -670,6 +670,22 @@ pub struct CombinedSnapshot<'a, 'tcx> {
 }
 
 impl<'a, 'tcx> InferCtxt<'a, 'tcx> {
+    /// calls `tcx.try_unify_abstract_consts` after
+    /// canonicalizing the consts
+    pub fn canonical_try_unify_abstract_consts(
```
Comment (lcnr) [inline compiler/rustc_infer/src/infer/mod.rs:675]:
```suggestion
    pub fn try_unify_abstract_consts(
```
we already have the same pattern for `const_eval_resolve`

File: compiler/rustc_infer/src/infer/mod.rs [hunk 2]
```diff
@@ -670,6 +670,22 @@ pub struct CombinedSnapshot<'a, 'tcx> {
 }
 
 impl<'a, 'tcx> InferCtxt<'a, 'tcx> {
+    /// calls `tcx.try_unify_abstract_consts` after
+    /// canonicalizing the consts
```
Comment (lcnr) [inline compiler/rustc_infer/src/infer/mod.rs:674]:
```suggestion
    /// canonicalizing the consts.
```
