### PR TITLE
Warn on broken intra-doc links added to cross-crate re-exports

### LINKED ISSUE #77230: Rustdoc lints don't fire for pub re-exports
This is the general form of #77200, since it appears this was unintentional. It came up again in https://github.com/rust-lang/rust/pull/77119#issuecomment-699484891.

I tried this code:

```rust
#![deny(missing_doc_code_examples)]
pub use std::task::RawWakerVTable;
```

I expected to see this happen: Rustdoc gives an error that `RawWakerVTable` is missing examples.

Instead, this happened: Rustdoc ignores the re-export.

### Meta

`rustdoc --version`: rustdoc 1.48.0-nightly (8b4085359 2020-09-23)

### Possible Cause

@GuillaumeGomez and I found yesterday that rustdoc does _not_ generate an [`ImportItem`](https://doc.rust-lang.org/nightly/nightly-rustc/rustdoc/clean/types/enum.ItemEnum.html#variant.ImportItem) for pub re-exports. Instead it generates an [`StructItem`](https://doc.rust-lang.org/nightly/nightly-rustc/rustdoc/clean/types/enum.ItemEnum.html#variant.StructItem), which has the [`DefId`](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_hir/def_id/struct.DefId.html) of the original item, not the [`HirId`](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_hir/hir_id/struct.HirId.html) of an item in the current crate. This means that anywhere that needs a HirId, like lints, is out of luck.

Relevant pieces of code:

https://github.com/rust-lang/rust/blob/dadde88ebacd5e209922928206e0d85a99009203/src/librustdoc/passes/calculate_doc_coverage.rs#L184-L188
https://github.com/rust-lang/rust/blob/2e7ca7329966b9a86b4d35689cb719883dcda4e8/src/librustdoc/passes/doc_test_lints.rs#L76-L82
https://github.com/rust-lang/rust/blob/f9546afbe1300fa3780470db1d10eb60c2cd3bbc/src/librustdoc/passes/html_tags.rs#L106-L112

`check_code_block_syntax` doesn't have this issue, but only by sidestepping the lint machinery altogether and being impossible to silence.
https://github.com/rust-lang/rust/blob/2e7ca7329966b9a86b4d35689cb719883dcda4e8/src/librustdoc/passes/check_code_block_syntax.rs#L60

I'm not yet sure what's causing the issues in `clean` - it _looks_ like it should be making an `ImportItem` but it's not happening in practice.

https://github.com/rust-lang/rust/blob/0bcc96dd3d54d459f3ae9a178bac3e7e944a9102/src/librustdoc/clean/mod.rs#L2284-L2293

Below is some debug output from the original code sample. There are various other `RawWakerVTable` items being skipped but they're either fields or impls, so I didn't include them here. In particular there are no `ImportItem`s.

<details><summary>Debug output</summary>

```
Sep 26 10:09:35.580 DEBUG rustdoc::passes::doc_test_lints: skipping foreign item DefId(2:33796 ~ core[e6b8]::task[0]::wake[0]::RawWakerVTable[0]) with inner item StructItem(Struct { struct_type: Plain, generics: Generics { params: [], where_predicates: [] }, fields: [Item { source: Span { filename: Real(Named("/home/joshua/rustc/library/core/src/task/wake.rs")), cnum: crate2, loline: 67, locol: 4, hiline: 67, hicol: 43, original: /home/joshua/rustc/library/core/src/task/wake.rs:67:5: 67:44 (#0) }, name: Some("clone"), attrs: Attributes { doc_strings: [SugaredDoc(0, /home/joshua/rustc/library/core/src/task/wake.rs:60:5: 66:83 (#0), "This function will be called when the [`RawWaker`] gets cloned, e.g. when\nthe [`Waker`] in which the [`RawWaker`] is stored gets cloned.\n\nThe implementation of this function must retain all resources that are\nrequired for this additional instance of a [`RawWaker`] and associated\ntask. Calling `wake` on the resulting [`RawWaker`] should result in a wakeup\nof the same task that would have been awoken by the original [`RawWaker`].")], other_attrs: [], cfg: None, span: Some(/home/joshua/rustc/library/core/src/task/wake.rs:60:5: 60:82 (#0)), links: [], inner_docs: false }, inner: StructFieldItem(BareFunction(BareFunctionDecl { unsafety: Unsafe, generic_params: [], decl: FnDecl { inputs: Arguments { values: [Argument { type_: RawPointer(Not, Tuple([])), name: "" }] }, output: Return(ResolvedPath { path: Path { global: false, res: Err, segments: [PathSegment { name: "RawWaker", args: AngleBracketed { args: [], bindings: [] } }] }, param_names: None, did: DefId(2:33787 ~ core[e6b8]::task[0]::wake[0]::RawWaker[0]), is_generic: false }), c_variadic: false, attrs: Attributes { doc_strings: [], other_attrs: [], cfg: None, span: None, links: [], inner_docs: false } }, abi: Rust })), visibility: Inherited, def_id: DefId(2:33797 ~ core[e6b8]::task[0]::wake[0]::RawWakerVTable[0]::clone[0]), stability: None, deprecation: None }, Item { source: Span { filename: Real(Named("/home/joshua/rustc/library/core/src/task/wake.rs")), cnum: crate2, loline: 75, locol: 4, hiline: 75, hicol: 30, original: /home/joshua/rustc/library/core/src/task/wake.rs:75:5: 75:31 (#0) }, name: Some("wake"), attrs: Attributes { doc_strings: [SugaredDoc(0, /home/joshua/rustc/library/core/src/task/wake.rs:69:5: 74:25 (#0), "This function will be called when `wake` is called on the [`Waker`].\nIt must wake up the task associated with this [`RawWaker`].\n\nThe implementation of this function must make sure to release any\nresources that are associated with this instance of a [`RawWaker`] and\nassociated task.")], other_attrs: [], cfg: None, span: Some(/home/joshua/rustc/library/core/src/task/wake.rs:69:5: 69:77 (#0)), links: [], inner_docs: false }, inner: StructFieldItem(BareFunction(BareFunctionDecl { unsafety: Unsafe, generic_params: [], decl: FnDecl { inputs: Arguments { values: [Argument { type_: RawPointer(Not, Tuple([])), name: "" }] }, output: Return(Tuple([])), c_variadic: false, attrs: Attributes { doc_strings: [], other_attrs: [], cfg: None, span: None, links: [], inner_docs: false } }, abi: Rust })), visibility: Inherited, def_id: DefId(2:33798 ~ core[e6b8]::task[0]::wake[0]::RawWakerVTable[0]::wake[0]), stability: None, deprecation: None }, Item { source: Span { filename: Real(Named("/home/joshua/rustc/library/core/src/task/wake.rs")), cnum: crate2, loline: 82, locol: 4, hiline: 82, hicol: 37, original: /home/joshua/rustc/library/core/src/task/wake.rs:82:5: 82:38 (#0) }, name: Some("wake_by_ref"), attrs: Attributes { doc_strings: [SugaredDoc(0, /home/joshua/rustc/library/core/src/task/wake.rs:77:5: 81:17 (#0), "This function will be called when `wake_by_ref` is called on the [`Waker`].\nIt must wake up the task associated with this [`RawWaker`].\n\nThis function is similar to `wake`, but must not consume the provided data\npointer.")], other_attrs: [], cfg: None, span: Some(/home/joshua/rustc/library/core/src/task/wake.rs:77:5: 77:84 (#0)), links: [], inner_docs: false }, inner: StructFieldItem(BareFunction(BareFunctionDecl { unsafety: Unsafe, generic_params: [], decl: FnDecl { inputs: Arguments { values: [Argument { type_: RawPointer(Not, Tuple([])), name: "" }] }, output: Return(Tuple([])), c_variadic: false, attrs: Attributes { doc_strings: [], other_attrs: [], cfg: None, span: None, links: [], inner_docs: false } }, abi: Rust })), visibility: Inherited, def_id: DefId(2:33799 ~ core[e6b8]::task[0]::wake[0]::RawWakerVTable[0]::wake_by_ref[0]), stability: None, deprecation: None }, Item { source: Span { filename: Real(Named("/home/joshua/rustc/library/core/src/task/wake.rs")), cnum: crate2, loline: 89, locol: 4, hiline: 89, hicol: 30, original: /home/joshua/rustc/library/core/src/task/wake.rs:89:5: 89:31 (#0) }, name: Some("drop"), attrs: Attributes { doc_strings: [SugaredDoc(0, /home/joshua/rustc/library/core/src/task/wake.rs:84:5: 88:25 (#0), "This function gets called when a [`RawWaker`] gets dropped.\n\nThe implementation of this function must make sure to release any\nresources that are associated with this instance of a [`RawWaker`] and\nassociated task.")], other_attrs: [], cfg: None, span: Some(/home/joshua/rustc/library/core/src/task/wake.rs:84:5: 84:68 (#0)), links: [], inner_docs: false }, inner: StructFieldItem(BareFunction(BareFunctionDecl { unsafety: Unsafe, generic_params: [], decl: FnDecl { inputs: Arguments { values: [Argument { type_: RawPointer(Not, Tuple([])), name: "" }] }, output: Return(Tuple([])), c_variadic: false, attrs: Attributes { doc_strings: [], other_attrs: [], cfg: None, span: None, links: [], inner_docs: false } }, abi: Rust })), visibility: Inherited, def_id: DefId(2:33800 ~ core[e6b8]::task[0]::wake[0]::RawWakerVTable[0]::drop[0]), stability: None, deprecation: None }], fields_stripped: false })
```

</details>

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
This emits `broken_intra_doc_links` for docs applied to pub use statements that point to external items and are inlined.
Does not address #77200 - any existing broken links from the original crate will not show warnings.

r? @jyn514

### CODE REVIEW

**Comment by jyn514** [comment]
@GuillaumeGomez can you add an example with a broken link on the original docs, before it was re-exported? Like this:

```rust
// crate1
/// [not_found]
pub fn f() {}

// crate2
pub use crate1::f;
```

cc @rust-lang/rustdoc, this is a change in behavior and undoes https://github.com/rust-lang/rust/issues/56922
cc @euclio

**Comment by GuillaumeGomez** [comment]
Sure!

**Comment by jyn514** [comment]
I'm not sure that we do. Consider the examples from https://github.com/rust-lang/rust/issues/77200:

- `cfg(doc)` on an import, so that the link only fails when re-exported
- `crate::x` meant something different depending on the crate, so it only failed when re-exported (fixed in #77253)

As a library author I would want to know about those I think, instead of having them silently fail. At least then you could work around it somehow.

**Comment by jyn514** [comment]
That said, I'm fine with only reporting in on new documentation for now so we can get the fix in, this would unblock https://github.com/rust-lang/rust/issues/77254.

File: src/test/rustdoc-ui/intra-doc-broken-reexport.rs [hunk 1]
```diff
@@ -0,0 +1,11 @@
+// edition:2018
+// aux-build:intra-doc-broken.rs
+// compile-flags:--test --test-args=--test-threads=1
+// normalize-stdout-test: "src/test/rustdoc-ui" -> "$$DIR"
```
Comment (jyn514) [inline src/test/rustdoc-ui/intra-doc-broken-reexport.rs:4]: Any reason you ran doc-tests here?

File: src/test/rustdoc-ui/intra-doc-broken-reexport.rs [hunk 2]
```diff
@@ -0,0 +1,11 @@
+// edition:2018
```
Comment (jyn514) [inline src/test/rustdoc-ui/intra-doc-broken-reexport.rs:1]: This is redundant with `extern crate`, can you remove one or the other?

File: src/test/rustdoc-ui/intra-doc-broken-reexport.rs (hunk 1 above)
Comment (GuillaumeGomez) [reply src/test/rustdoc-ui/intra-doc-broken-reexport.rs:4]: No, it's mainly copy-paste.

File: src/librustdoc/clean/types.rs [hunk 3]
```diff
@@ -1624,9 +1624,20 @@ pub struct Impl {
 #[derive(Clone, Debug)]
 pub enum Import {
     // use source as str;
-    Simple(String, ImportSource),
+    // The bool indicates wether it imports a macro or not.
```
Comment (jyn514) [inline src/librustdoc/clean/types.rs:1627]:
```suggestion
    // The bool indicates whether it imports a macro or not.
```

File: src/librustdoc/clean/types.rs [hunk 4]
```diff
@@ -1624,9 +1624,20 @@ pub struct Impl {
...
+    Simple(String, ImportSource, bool),
     // use source::*;
-    Glob(ImportSource),
+    // The bool indicates wether this is from an import.
```
Comment (jyn514) [inline src/librustdoc/clean/types.rs:1630]: What do you mean by 'from an import'? Aren't all glob imports imports?

```suggestion
    // The bool indicates whether this is from an import.
```

File: src/librustdoc/clean/mod.rs [hunk 5]
```diff
@@ -2272,13 +2287,30 @@ impl Clean<Vec<Item>> for doctree::Import<'_> {
             }
             if !denied {
                 let mut visited = FxHashSet::default();
-                if let Some(items) =
+                if let Some(mut items) =
                     inline::try_inline(cx, path.res, name, Some(self.attrs), &mut visited)
                 {
+                    // In case this is a macro, we don't want to show the reexport, only the macro
+                    // itself.
```
Comment (jyn514) [inline src/librustdoc/clean/mod.rs:2294]: Can you give an example of the code this is describing? Is this like an import expanded from a macro?

Comment (GuillaumeGomez) [reply src/librustdoc/clean/mod.rs:2294]: When you reexport a macro, we don't show the reexport, just the macro. As simple as that. :)

**Comment by Manishearth** [comment]
> As a library author I would want to know about those I think, instead of having them silently fail. At least then you could work around it somehow.

I'm wary of reporting bugs that take updating a dependency to fix. As long as it gets reported in the dependency (which will show up in CI logs!) it should be fine IMO

**Comment by jyn514** [comment]
> I'm wary of reporting bugs that take updating a dependency to fix. As long as it gets reported in the dependency (which will show up in CI logs!) it should be fine IMO

Well that's the issue, some of these _won't_ show up in the dependency. So there's no way to see them other than warning on downstream crates, and we're currently silencing those warnings.

File: src/librustdoc/clean/mod.rs (hunk 5 above)
Comment (jyn514) [reply src/librustdoc/clean/mod.rs:2294]: Oh oh I see what you mean - the macro is being inlined, so we don't need to show both the `use` and the macro.

File: src/librustdoc/clean/types.rs (hunk 4 above)
Comment (jyn514) [reply src/librustdoc/clean/types.rs:1630]: After your explanation in https://github.com/rust-lang/rust/pull/77276#discussion_r495999459 I think you meant 'inlined'.

Comment (GuillaumeGomez) [reply src/librustdoc/clean/types.rs:1630]: No, this is exactly what I meant. ;)

**Comment by GuillaumeGomez** [comment]
Updated!

**Comment by jyn514** [comment]
@GuillaumeGomez just double checking - this only affects intra-doc links for now, right? Everywhere else ignores `use` statements? If so r=me and we can debate whether this should lint the original warning in re-exports later (currently it does not): https://github.com/rust-lang/rust/pull/77276#issuecomment-699679647

**Comment by GuillaumeGomez** [comment]
Only intra-doc links as far as I can tell. But all other lints are now able to run checks on them as well, as long as they want to.

@bors: r=jyn514

**Comment by ollie27** [comment]
This now displays re-exports for items even when they have been inlined. Here's `std` for example:

image

That can't be intentional, right?

**Comment by jyn514** [comment]
@bors r-

No, that wasn't intentional. @GuillaumeGomez can you fix that?

**Comment by GuillaumeGomez** [comment]
So I just need to check for `doc(inline)` I assume? I'll do that tomorrow then.

**Comment by jyn514** [comment]
> So I just need to check for doc(inline)

Well, I think the fix needs to happen in render, not in `clean`. Some parts of rustdoc (intra-doc links) are interested in the `use ` and some (render) are not. So each needs to decide on their own whether to ignore it or not.

**Comment by Manishearth** [comment]
> Well that's the issue, some of these _won't_ show up in the dependency. So there's no way to see them other than warning on downstream crates, and we're currently silencing those warnings.

Wait, why not? Can you give me an example?

**Comment by jyn514** [comment]
> Wait, why not? Can you give me an example?

https://github.com/rust-lang/rust/pull/77276#issuecomment-699678767: https://github.com/rust-lang/rust/issues/77193, https://github.com/rust-lang/rust/pull/75855. The second one is just a rustdoc bug, but it's possible there are more like it. The first one is a legitimate difference between documenting normally and documenting as a dependency.

**Comment by Manishearth** [comment]
Hmmm. I feel like there's a tradeoff here. The `cfg(doc)` thing is unfortunate, but is it really worth surfacing unfixable lints? I strongly believe that if a lint cannot be fixed in the current code it should probably not exist.

**Comment by GuillaumeGomez** [comment]
Fixed the issue. The extra-added `ImportItem`s are now ignored in the rendering, much simpler this way and gives the current output.

**Comment by jyn514** [comment]
@GuillaumeGomez can you add a test that the `use` imports are not shown in the docs so this doesn't regress again?

**Comment by jyn514** [comment]
> Hmmm. I feel like there's a tradeoff here. The cfg(doc) thing is unfortunate, but is it really worth surfacing unfixable lints? I strongly believe that if a lint cannot be fixed in the current code it should probably not exist.

I guess I disagree that `broken_intra_doc_links` is really a lint. In my mind it's not something that's _dubious_ and should be fixed, it's functionality that's not working. This sort of issue isn't 'maybe you should write it differently', it's just a bug:

image

Rustc gives errors for problems in dependencies and I think rustdoc should give warnings for problems in dependencies.

**Comment by jyn514** [comment]
Well, I did a quick informal poll on discord and people were pretty against it since they can't fix the issues themselves. So I guess it's better to keep it the way it is now.

File: src/librustdoc/html/render/mod.rs [hunk 6]
```diff
@@ -2074,12 +2074,14 @@ fn item_module(w: &mut Buffer, cx: &Context, item: &clean::Item, items: &[clean:
             }
 
             clean::ImportItem(ref import) => {
-                write!(
-                    w,
-                    "<tr><td><code>{}{}</code></td></tr>",
-                    myitem.visibility.print_with_space(),
-                    import.print()
-                );
+                if import.should_be_displayed {
```
Comment (ollie27) [inline src/librustdoc/html/render/mod.rs:2077]: This check isn't needs because items are already filtered with `is_stripped` above.

File: src/librustdoc/clean/mod.rs [hunk 7]
```diff
@@ -2231,6 +2231,12 @@ impl Clean<Vec<Item>> for doctree::ExternCrate<'_> {
 
 impl Clean<Vec<Item>> for doctree::Import<'_> {
     fn clean(&self, cx: &DocContext<'_>) -> Vec<Item> {
+        // We need this comparison because some imports (for std types for example)
+        // are "inserted" as well but directly by the compiler and they should not be
+        // taken into account.
+        if self.span.is_dummy() {
+            return Vec::new();
+        }
```
[the remark this answers is not in the document]
Comment (GuillaumeGomez) [reply src/librustdoc/clean/mod.rs:2239]: We can't test it. The compiler inserts some imports like `std` for example. So in case we receive an import with a dummy span, it means that it was inserted by the compiler and that we don't want to check it.

File: src/librustdoc/html/render/mod.rs (hunk 6 above)
Comment (GuillaumeGomez) [reply src/librustdoc/html/render/mod.rs:2077]: Good catch!

File: src/librustdoc/clean/mod.rs (hunk 7 above)
[the remark this answers is not in the document]
Comment (jyn514) [reply src/librustdoc/clean/mod.rs:2239]: Guillaume said that otherwise this includes the injected `use std::prelude::v1::*;` imports. I agree a test would be nice to have.

[the remark this answers is not in the document]
Comment (jyn514) [reply src/librustdoc/clean/mod.rs:2239]: > We can't test it

@GuillaumeGomez you could test that the item doesn't appear with `@has`. Or whatever issue you ran into originally that made you add this check.

[the remark this answers is not in the document]
Comment (GuillaumeGomez) [reply src/librustdoc/clean/mod.rs:2239]: The issue I had was simply that a weird error message appeared with missing doc example (when I was forcing the check to test it) with a span pointing to nowhere. So literally: we can't test it.

**Comment by GuillaumeGomez** [comment]
Updated!

**Comment by ollie27** [comment]
> Fixes #77230

This PR isn't actually doing anything related to #77230 so that should be removed from the PR comment. FWIW is disagree with emitting lints, including `broken_intra_doc_links`, for items in external crates like #77230 is suggesting.

What this PR is doing is emitting `broken_intra_doc_links` for docs applied to `pub use` statements that point to external items and are inlined. I think does this makes sense because these docs are only displayed in the current crate. However, the links will still be broken (#77254) so I think #77254 should be fixed first so after you fix the warnings you actually get working links.

**Comment by jyn514** [comment]
> However, the links will still be broken (#77254) so I think #77254 should be fixed first so after you fix the warnings you actually get working links.

It's not possible to fix #77254 until this is fixed. Rustdoc doesn't have enough information to tell what module the docs came from, all it has is the `CrateId` of the `Span`.

**Comment by jyn514** [comment]
If you want I can make a PR on top of this one fixing both at the same time, so that it's always possible to fix the warnings.

File: src/librustdoc/clean/mod.rs (hunk 7 above)
[the remark this answers is not in the document]
Comment (ollie27) [reply src/librustdoc/clean/mod.rs:2239]: `use std::prelude::v1::*;` imports are never inlined so I don't see what that has to do with this PR which is only changing behavior for imports that are inlined.

> The issue I had was simply that a weird error message appeared with missing doc example (when I was forcing the check to test it) with a span pointing to nowhere. So literally: we can't test it.

If you can't write a `rustdoc-ui` test or at least provide instructions on how to reproduce this issue then this code needs to be deleted.

File: src/librustdoc/clean/mod.rs [hunk 8]
```diff
@@ -2253,12 +2259,21 @@ impl Clean<Vec<Item>> for doctree::Import<'_> {
...
+                    items.push(Item {
+                        name: None,
+                        attrs: self.attrs.clean(cx),
+                        source: self.span.clean(cx),
+                        def_id: cx.tcx.hir().local_def_id(self.id).to_def_id(),
+                        visibility: self.vis.clean(cx),
+                        stability: None,
+                        deprecation: None,
+                        inner: ImportItem(Import::new_glob(resolve_use_source(cx, path), false)),
+                    });
```
Comment (ollie27) [inline src/librustdoc/clean/mod.rs:2272]: I've just noticed that the docs on glob imports are completely ignored so there is no need to do anything for globs.

**Comment by ollie27** [comment]
> It's not possible to fix #77254 until this is fixed. Rustdoc doesn't have enough information to tell what module the docs came from, all it has is the `CrateId` of the `Span`.

I don't really see how this PR is providing that information. This is creating separate `ImportItem`s but the actual attributes on the inlined item are still the same. I think what needs to be done is keep track of which items each attributes come from in https://github.com/rust-lang/rust/blob/4d52dc4790cfaf3f23ff219c9a9932be2bfcd53e/src/librustdoc/clean/inline.rs#L304 somehow. If we did that then we could use that to decide where to resolve links from and whether to emit `broken_intra_doc_links` for each line of the docs separately. Then we wouldn't need the extra `ImportItem`s.

> If you want I can make a PR on top of this one fixing both at the same time, so that it's always possible to fix the warnings.

That would be useful but if you think the changes in this PR are really needed then I guess it can get merged separately.

File: src/librustdoc/clean/mod.rs (hunk 8 above)
Comment (GuillaumeGomez) [reply src/librustdoc/clean/mod.rs:2272]: Ok!

File: src/librustdoc/clean/mod.rs (hunk 7 above)
[the remark this answers is not in the document]
Comment (GuillaumeGomez) [reply src/librustdoc/clean/mod.rs:2239]: To trigger it, you need to unable a check to be run on the import item doc comments from rustdoc, like `missing_doc_code_example`. Then you'll have a nice error showing up first, coming out from nowhere. So no, this code is necessary. Maybe we don't have the use for it right now, but who knows if we won't add a lint that will need to check import items later on? Then the bug would reappear and it would make the contributor lose time for something that could have been fixed earlier on. Dummy imports are added by the compiler and shouldn't be considered as rustdoc items and therefore should be ignored.

**Comment by GuillaumeGomez** [comment]
@ollie27 Since you have the `HirId` of the `ItemImport` element itself, then you can get its parent. Or did I miss something?

**Comment by Manishearth** [comment]
> I guess I disagree that `broken_intra_doc_links` is really a lint. In my mind it's not something that's _dubious_ and should be fixed, it's functionality that's not working. This sort of issue isn't 'maybe you should write it differently', it's just a bug:

I mean, this is actually _worse_, we should _never_ be reporting errors that cannot be fixed in the current crate. Rust's design, including things like the orphan rule, are explicitly engineered to avoid this situation.

**Comment by jyn514** [comment]
> This is creating separate ImportItems but the actual attributes on the inlined item are still the same. I think what needs to be done is keep track of which items each attributes come from

Oh I see what you mean - after this PR, the HirId will be available to find the module, but I won't be able to tell which attributes came from which module. Hmm, I think you're right. Let me take a closer look at `try_inline`.

**Comment by jyn514** [comment]
> I mean, this is actually worse, we should never be reporting errors that cannot be fixed in the current crate. Rust's design, including things like the orphan rule, are explicitly engineered to avoid this situation.

I mean, that's how things are currently with `cfg(doc)`. If you want to document dependencies with `cfg(doc)` I'm all in favor of it, but right now rustdoc sees two different versions of the code depending on whether or not it's a dependency or the main crate. So there fundamentally may be differences and errors in one but not the other.

**Comment by Manishearth** [comment]
> I mean, that's how things are currently with `cfg(doc)`. If you want to document dependencies with `cfg(doc)` I'm all in favor of it, but right now rustdoc sees two different versions of the code depending on whether or not it's a dependency or the main crate. So there fundamentally may be differences and errors in one but not the other.

Yes, as I said earlier, this is unfortunate, but I don't think it's worth surfacing a lint/error.

My point in that comment was saying that this is an error, "not just a lint", does not help your case, since if anything Rust is _very_ much a stickler about "no errors you can't fix".

**Comment by GuillaumeGomez** [comment]
Anything else to be done here?

**Comment by jyn514** [comment]
I think @ollie27 might still have questions about https://github.com/rust-lang/rust/pull/77276#discussion_r496847254, and it might be better for me to fix https://github.com/rust-lang/rust/issues/77254 at the same time. I don't have strong preferences on the second one though, if others are fine merging I'm happy to give these warnings since you can 'fix' them by removing the links.

**Comment by GuillaumeGomez** [comment]
I already answered https://github.com/rust-lang/rust/pull/77276#discussion_r496847254, or did I miss something maybe? Otherwise I think this PR is ready.

File: src/librustdoc/clean/mod.rs (hunk 7 above)
[the remark this answers is not in the document]
Comment (ollie27) [reply src/librustdoc/clean/mod.rs:2239]: Okay, I agree that rustdoc should ignore imports automatically added by rustc. However, that doesn't seem to have anything to do with the rest of this PR so it should be moved to a separate one although this could just be done if/when a lint is added that would actually need this.

[the remark this answers is not in the document]
Comment (GuillaumeGomez) [reply src/librustdoc/clean/mod.rs:2239]: Unfortunately, we add back the imports as items to be checked by the different passes. We need to filter them out in the same PR, otherwise it'll be problematic. So if not in this PR, I wonder we can do it. :-/

[the remark this answers is not in the document]
Comment (ollie27) [reply src/librustdoc/clean/mod.rs:2239]: The only `ImportItem`s this PR is adding are ones the have been inlined. The prelude imports are private and so are never inlined so this PR is not adding new `ImportItem`s for them.

There is actually a visible change from this. Currently, if you build docs with `--no-defaults` then `use std::prelude::v1::*;` shows up in the Re-exports section in the crate root. This change removes that line. That's something that could be tested assuming hiding that line is intentional. `extern crate std;` also shows up, should that also be hidden?

Again, please could you move this change to a different PR.

[the remark this answers is not in the document]
Comment (GuillaumeGomez) [reply src/librustdoc/clean/mod.rs:2239]: Ok, that seems fair. I opened https://github.com/rust-lang/rust/issues/77567.

**Comment by GuillaumeGomez** [comment]
@ollie27 I removed the filter on dummy imports as you asked and opened #77567. I'll fix it as soon as this PR is merged.

**Comment by GuillaumeGomez** [comment]
Just waiting on you then @ollie27. :)

**Comment by jyn514** [comment]
https://github.com/rust-lang/rust/issues/77254 is fixed so people can now fix the warnings they get from broken links :)

**Comment by GuillaumeGomez** [comment]
Since I removed the filter on compiler added imports, we can move on.

@bors: r=jyn514,ollie27
