### PR TITLE
Issue 72408 nested closures exponential

### LINKED ISSUE #72408: Nested closures result in exponential compilation time increase
Closures include captured types twice in a type tree.

Wrapping one closure with another leads to doubling the amount of types in the type tree.

With nested closures compile time increases exponentially and it's extremely easy to break the compiler. Obviously it's even easier if each level captures more than one closure.

I think I have a fix for this one ready, about to push it.

I tried this code:

```rust
fn dup<F: Fn(i32) -> i32>(f: F) -> impl Fn(i32) -> i32 {
    move |a| f(2*a)
}

fn main() {
    let f = |a| a;

    let f = dup(f);
    let f = dup(f);
    let f = dup(f);
    let f = dup(f);
    let f = dup(f);

    let f = dup(f);
    let f = dup(f);
    let f = dup(f);
    let f = dup(f);
    let f = dup(f);

    let f = dup(f);
    let f = dup(f);
    let f = dup(f);
    let f = dup(f);
    let f = dup(f);

    let f = dup(f);
    let f = dup(f);
    let f = dup(f);
    let f = dup(f);
    let f = dup(f);

    // Compiler dies around here if it tries
    // to walk the tree exhaustively.

    let f = dup(f);
    let f = dup(f);
    let f = dup(f);
    let f = dup(f);
    let f = dup(f);

    let f = dup(f);
    let f = dup(f);
    let f = dup(f);
    let f = dup(f);
    let f = dup(f);

    println!("Hello {}", f(1));
}
```

I expected to see this happen: no error.

Instead, this happened:

```
error: reached the type-length limit while instantiating `dup::<[closure@src/main.rs:2:5: ...rs:6:13: 6:18]]]]]]]]]]]]]]]]]]>`
 --> src/main.rs:1:1
  |
1 | / fn dup<F: Fn(i32) -> i32>(f: F) -> impl Fn(i32) -> i32 {
2 | |     move |a| f(2*a)
3 | | }
  | |_^
  |
  = note: consider adding a `#![type_length_limit="1835001"]` attribute to your crate
```

### Meta

I tried it both on stable and nightly rust:

```
$ rustc --version --verbose
rustc 1.45.0-nightly (7ebd87a7a 2020-05-08)
binary: rustc
commit-hash: 7ebd87a7a1e0e21767422e115c9455ef6e6d4bee
commit-date: 2020-05-08
host: x86_64-pc-windows-msvc
release: 1.45.0-nightly
LLVM version: 9.0
```

```
$ rustc --version --verbose
rustc 1.43.0 (4fb7144ed 2020-04-20)
binary: rustc
commit-hash: 4fb7144ed159f94491249e86d5bbd033b5d60550
commit-date: 2020-04-20
host: x86_64-pc-windows-msvc
release: 1.43.0
LLVM version: 9.0
```

### PR DESCRIPTION
**Pull request by VFLashM**
This fixes #72408.

Nested closures were resulting in exponential compilation time.

This PR is enhancing asymptotic complexity, but also increasing the constant, so I would love to see perf run results.

### CODE REVIEW

**Comment by petrochenkov** [comment]
Pretty noticeable regression.

**Comment by VFLashM** [comment]
Oh well, simple hashset didn't make it. I'll see what else I can do.

**Comment by jyn514** [comment]
You could try using a BTreeSet which has much lower constant factor and reasonable (log n) asymptomatic complexity.

**Comment by VFLashM** [comment]
Thanks for the hint, I'll check it out.

**Comment by VFLashM** [comment]
Some set benchmarks:

set_bench

Here `MiniSet` is a tiny custom small-storage-optimized set, using array for up to 64 elements and `FxHashSet` afterwards.

**Comment by VFLashM** [comment]
Let's have another perf run, shall we?

**Comment by VFLashM** [comment]
As for the benchmarks these graphs have current set size along x axis and cost `insert` operation along y axis.

**Comment by petrochenkov** [comment]
I suspect that any set will cause noticeable regressions if it's populated on *every* type walk, because many of the type walks are mostly empty otherwise.
@bors try @rust-timer queue

**Comment by VFLashM** [comment]
This walk only iterates generic arguments. Vast majority of types have zero or one generic arguments.
With small storage optimization storing first several items is almost free.

**Comment by VFLashM** [comment]
What happened to rust timer queue? Is it alive? I think it never got processed.

**Comment by Mark-Simulacrum** [comment]
We were having some trouble with perf yesterday/today, you can follow progress here: https://perf.rust-lang.org/status.html.

**Comment by VFLashM** [comment]
A bit better than before, but still worse than I hoped.
If it's still too expensive, let me know and I'll try to figure out another solution, probably avoiding unexpected type duplication for Closures specifically.

**Comment by petrochenkov** [comment]
@VFLashM 
You may want to find someone who actually maintains this part of the compiler, my work with this PR was limited to running perf bot so far.

r? @pnkfelix for review or reassignment

**Comment by petrochenkov** [comment]
cc @nnethercote

**Comment by VFLashM** [comment]
@petrochenkov just for the record, it probably should not be "waiting for author" anymore.

File: src/librustc_middle/ty/walk.rs [hunk 1]
```diff
@@ -3,7 +3,54 @@
...
+                } else {
+                    if !array.is_full() {
+                        unsafe {
+                            array.push_unchecked(elem);
+                        }
+                    } else {
+                        let mut set: FxHashSet<T> = array.iter().copied().collect();
+                        set.insert(elem);
+                        *self = MiniSet::Set(set);
+                    }
```
Comment (cynecx) [inline src/librustc_middle/ty/walk.rs:46]: Is it really worth using an unsafe operation here?

How about something like:

```suggestion
                    if let Err(cap_err) = array.try_push(elem) {
                        let elem = cap_err.element();
                        let mut set: FxHashSet<T> = array.iter().copied().collect();
                        set.insert(elem);
                        *self = MiniSet::Set(set);
                    }
```

**Comment by VFLashM** [comment]
@cynecx I considered that option. It would require another perf run. At the same time its surely not going to be faster and question right now is whether unsafe version is fast enough.

**Comment by Elinvynia** [comment]
Ping from triage:
@VFLashM Hello, could you please have a look at rebasing this PR? Thanks!

**Comment by VFLashM** [comment]
@cyndis @pnkfelix I don't really want to waste time rebasing this change if performance tradeoffs are not acceptable. Please let me know if they are. If not, I'll work on a different solution.

**Comment by crlf0710** [comment]
Ping from triage. I'm going to close this due to inactivity. Feel free to reopen or open a new PR when you're able to make progress. Also, if more technical discussions are needed, maybe you can consider opening a topic on zulip to settle down the overall direction first. Thanks!

**Comment by JohnTitor** [comment]
This shouldn't be closed as the author is waiting for help from the reviewer.
@pnkfelix The author left some thoughts, could you take a look?

**Comment by JohnCSimon** [comment]
@VFLashM 
Unfortunately, this PR has encountered another merge conflict so I'm bumping it back to the author. 
Can you please address this? Thanks.

**Comment by JohnTitor** [comment]
@JohnCSimon Did you read the author's comment? Please do not ping authors to resolve merge conflicts if they need a response from the reviewer. It's meaningless, I think.

**Comment by tmandry** [comment]
r? @tmandry 

Personally I think this cost is acceptable given that it fixes exponential compile time in a lot of cases that people are hitting (see #54540).

I'd be willing to r+ it once we have a new benchmark in https://github.com/rust-lang/rustc-perf that lets us demonstrate the savings and catch regressions.

File: src/librustc_middle/ty/walk.rs (hunk 1 above)
Comment (tmandry) [reply src/librustc_middle/ty/walk.rs:46]: Agreed, I'd prefer something like this as well.

Comment (VFLashM) [reply src/librustc_middle/ty/walk.rs:46]: Great change. Didn't know about try_push. Will update.

**Comment by jyn514** [comment]
@VFLashM let me know if you want help writing a benchmark for rustc-perf. There's [a zulip channel](https://rust-lang.zulipchat.com/#narrow/stream/247081-t-compiler.2Fperformance) and examples in https://github.com/rust-lang/rustc-perf/tree/master/collector/benchmarks.

**Comment by jyn514** [comment]
(also, this needs a rebase)

**Comment by VFLashM** [comment]
I rebased it.
Right now the issue is that some new tests were added that are failing with this change now.
The one remaining is infinite type recursion that was previously caught by type size limit.
Now that identical types are not traversed during type size calculation, this code passes further and hangs forever somewhere in infinite recursion.
I'm looking into that issue right now.

**Comment by VFLashM** [comment]
I pushed a new set of changes, rebased on top of master and with a couple of new fixes applied.
Looking into writing a new benchmark.

**Comment by VFLashM** [comment]
Actually, what kind of benchmark is it supposed to be?

This change is not exactly about making compilation faster.
It's more about making it possible at all.
Without it compiler simply can't handle deeply nested closures.

I can easily add a benchmark with a huge nested type in (quite like the unit test I added), but any regression won't be visible on a benchmark. Instead of that regression will simply make compiler hang.

**Comment by nnethercote** [comment]
Can you size the benchmark so that with the fix it's fast (e.g. < 1s to compile) and without the fix it's slow but not ridiculous (e.g. 30s to compile)? We have a few benchmarks like that, for things that used to be quadratic/exponential/whatever.

**Comment by VFLashM** [comment]
Ok, will do.

**Comment by tmandry** [comment]
I would think your example in #72408 or the one in #54540 would be sped up quite a bit by this change, yes? (Assuming the type length limit is high enough for it to compile both before and after the change)

**Comment by VFLashM** [comment]
I already added my example as a ui test here:
https://github.com/rust-lang/rust/pull/72412/commits/b64656a63ce7d3296ca3373508cfe58b13b44be9#diff-2608ce93d9cee274c502c19abc0b469d

I can surely use it as a bench test too.

**Comment by VFLashM** [comment]
Here's PR in rustc-perf: rust/rustc-perf#762

**Comment by tmandry** [comment]
@bors try
@rust-timer queue

**Comment by jyn514** [comment]
The 1% losses go on for a while below, I didn't screenshot them all.
image

**Comment by VFLashM** [comment]
This is noticeably worse than before. I wonder if that's because of FxHashMap I introduced in last commit. I'll have to double check it.

**Comment by VFLashM** [comment]
Yeah, FxHashMap was the culprit. Well, that's nothing you can't solve with one more SSO implementation.
I pushed one more commit replacing FxHashMap with a tiny SSO map.

Locally it brings performance back to below 1% of overhead.

Could someone please queue one more bench run?

**Comment by VFLashM** [comment]
On a side note, using SSO structures gives sizeable performance benefit. It might be a good idea to check if there are places where it's worth using them instead of FxHashSet/FxHashMap rust currently uses.

File: compiler/rustc_infer/src/infer/combine.rs [hunk 2]
```diff
@@ -535,13 +539,17 @@ impl TypeRelation<'tcx> for Generalizer<'_, 'tcx> {
     fn tys(&mut self, t: Ty<'tcx>, t2: Ty<'tcx>) -> RelateResult<'tcx, Ty<'tcx>> {
         assert_eq!(t, t2); // we are abusing TypeRelation here; both LHS and RHS ought to be ==
 
+        let cache_key = (t, t2);
```
Comment (tmandry) [inline compiler/rustc_infer/src/infer/combine.rs:601]: Actually there's no need to include both t and t2 in the key since they're both equal! (see above assertion)

This could help performance even more..

Comment (tmandry) [reply compiler/rustc_infer/src/infer/combine.rs]: Fixed in latest commit

**Comment by tmandry** [comment]
I took the liberty of pushing a final cleanup so we can get this in.

I think this fixes both #72408 and #54540. I just checked and while it does not fix #75992, I think a similar strategy can be applied there in a follow-up.

This is a great speedup, thanks for your diligent work!

@bors r+ rollup=never

**Comment by tmandry** [comment]
@rustbot modify labels: +beta-nominated

Nominating because it fixes part of the fallout from #75443, which was backported to appear in 1.46. While #72408 and #54540 predate this version of Rust, a lot of people weren't hitting these issues until then (see their comments).

Crucially, this was code that compiled fine prior to 1.46. As I understand it, people will still have to increase type length limits that they didn't have to before (already a pain), but as a result of this change fewer of them will _then_ be hit with an unmanageable compile time.

**Comment by andjo403** [comment]
is there some specific reason why MiniMap and MiniSet is not in rustc_data_structures so is can easier be reused?

**Comment by VFLashM** [comment]
No, no particular reason. It's just they were needed locally for a very
specific task. It's a good idea to move them there.

**Comment by ecstatic-morse** [comment]
Hi! This PR showed up in the weekly [perf triage](https://github.com/rust-lang/rustc-perf/tree/master/triage) report. As expected, it resulted in a very large improvement in [instruction counts](https://perf.rust-lang.org/compare.html?start=2c69266c0697b0c0b34abea62cba1a1d3c59c90c&end=fdc3405c20122fd0f077f5a77addabc873f20e4c&stat=instructions:u) on the newly added `deeply-nested-closures` benchmark, but caused slight regressions elsewhere.

Nice work!

**Comment by spastorino** [comment]
[discussed](https://zulip-archive.rust-lang.org/238009tcompilermeetings/97901weeklymeeting2020092454818.html#211136397) in T-compiler meeting, declined to backport.

@rustbot modify labels: -beta-nominated

**Comment by kornelski** [comment]
Is beta removing reverting change that caused this problem in the first place? I would be very unhappy about this bug being left in both 1.46 and 1.47, since it has broken multiple projects for me.

**Comment by tmandry** [comment]
@spastorino @pnkfelix @wesleywiser It's not true that the performance was always bad. There is code that worked fine up until the last stable release that now takes an unacceptably long time to compile. It was caused by another beta backport that happened just prior to a stable release, #75443.

**Comment by tmandry** [comment]
The reason for the confusion is that these issues pre-existed the breakage. It is true that there was code with bad build performance that also required increasing the type length limit; this change fixed those preexisting issues as well.

Another fix for similar regressions is in #76928. It doesn't look like we've fixed all of them yet, see #75992.

**Comment by Mark-Simulacrum** [comment]
Taking a look at this PR, it looks like the fairly large diff is *mostly* due to: introduction of a small-size optimized Map structure and threading through references to it into various pieces of code. It seems like it should be fairly harmless to backport and we've not seen serious regressions in nightly (it landed 2 weeks ago) as a result, to my knowledge.

I am inclined to backport this to beta, personally. I am also inclined to backport https://github.com/rust-lang/rust/pull/76928 which also looks like it mostly just adds some caching. @rust-lang/compiler -- given that this is indeed fixing regressions, even if the performance problem is pre-existing, is anyone opposed to a beta backport of this PR?

I will also be nominating #76928 shortly.

File: src/test/ui/recursion/recursion.stderr [hunk 3]
```diff
@@ -1,4 +1,4 @@
-error: reached the recursion limit while instantiating `test::<Cons<Cons<Cons<Cons<Cons<Cons<Cons<Cons<Cons<Cons<Cons<Cons<Cons<Cons<Cons<Cons<Cons<Cons<Cons<Cons<Cons<Cons<Cons<Cons<Cons<Cons<Cons<Cons<Cons<Cons<Cons<Cons<Cons<Cons<Cons<Cons<Cons<Cons<Cons<Cons<Cons<Cons<Cons<Cons<Cons<Cons<Cons<Cons<Cons<Cons<Cons<Cons<Cons<Cons<Cons<Cons<Cons<Cons<Cons<Cons<Cons<Cons<Cons<Cons<Cons<Cons<Cons<Cons<Cons<Cons<Cons<Cons<Cons<Cons<Cons<Cons<Cons<Cons<Cons<Cons<Cons<Cons<Cons<Cons<Cons<Cons<Cons<Cons<Cons<Cons<Cons<Cons<Cons<Cons<Cons<Cons<Cons<Cons<Cons<Cons<Cons<Cons<Cons<Cons<Cons<Cons<Cons<Cons<Cons<Cons<Cons<Cons<Cons<Cons<Cons<Cons<Cons<Cons<Cons<Cons<Cons<Cons<Cons<Cons<Cons<Cons<Cons<Cons<Cons<Nil>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>`
+error: reached the recursion limit while instantiating `test::<Cons<Cons<Cons<Cons<Cons<...>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>`
```
Comment (stjepang) [inline src/test/ui/recursion/recursion.stderr:1]: Apologies for the random drive-by comment, but aren't there too many `>`s? I was expecting this:

```
test::<Cons<Cons<Cons<Cons<Cons<...>>>>>>
```

Comment (kornelski) [reply src/test/ui/recursion/recursion.stderr:1]: Final truncation is based on number of characters (32 each side).

Comment (jyn514) [reply src/test/ui/recursion/recursion.stderr:1]: Maybe it should be smarter, though?

Comment (kornelski) [reply src/test/ui/recursion/recursion.stderr:1]: It's tricky, because the part of the code that understands type's structures doesn't track its printed length. The part that truncates the text length doesn't understand the type.
