### PR TITLE
Simplify and unify rustdoc sidebar styles

### LINKED ISSUE #59860: Simplify and unify rustdoc sidebar styles
Rustdoc's sidebar uses several visually heavyweight elements, and also has inconsistent styling between different sections.

This has been broken out of #59829 to provide smaller, actionable items that can be independently discussed and worked on. A review of rustdoc for accessibility, especially for dyslexia and attention disorders, finds that there are a number of visually distracting elements in rustdoc which can draw attention away from the main content. This should be considered along with the other issues mentioned in #59829 about the overall effect of a number of distracting elements on the page.

There are several heavyweight UI elements.

* The headings for the item in question, and the parent item, are enclosed in a black-bordered, white background box, contrasting with the background
* The crate name is bold in the parent item box
* There are high contrast horizontal rules on both sides delimiting the headings in the current page
* There are large, bold headings, with a lot of whitespace and low-contrast horizontal rules below in the parent item section
* Headings are centered, while items are left justified

In addition, the two sections have quite inconsistent styling.

* Headings in the top section are same size as individual items, but centered and delimited by heavy horizontal rules
* Headings in the bottom section are a large, bold font, with a lot of space and very light horizontal rules

Screenshot of current item section of sidebarScreenshot of parent item section of sidebar

We can compare that with the sidebar in mdBook; while they serve different purposes, it is useful to look at them together.

mdBook simply uses an outline view for nesting, without larger or bolder headings. It does have bold chapter/section numbers, which is slightly attention grabbing, but otherwise is both a simpler style and fits more content into the sidebar with less decoration.

Screen Shot 2019-04-10 at 4 42 17 PM

Specific recommendations:

* [ ] Drop the black bordered white boxes in the sidebar
* [ ] Drop the black horizontal rules in the sidebar
* [ ] Use at most two attributes to distinguish levels of headings and individual items. Those could include:
  - Indentation, as in an outline view like mdBook
  - Font size
  - Font boldness
  - Extra whitespace
  - Single light horizontal rule
* [ ] Prefer left-aligned text to centered

### PR DESCRIPTION
**Pull request by jsha**
Fixes #59860

This switches to just use size, weight, and spacing to distinguish headings in the sidebar. We no longer use boxes, horizontal bars, or centering to distinguish headings. This makes it much easier to understand the hierarchy of headings, and reduces visual noise.

I also refactored how the mobile topbar works. Previously, we tried to shift around elements from the sidebar to make the topbar. Now, the topbar gets its own elements, which can be styled on their own. This makes styling and reasoning about those elements simpler.

Because the heading font sizes are bigger, increase the sidebar width slightly.

As a very minor change, removed version from the "All types" page. It's now only on the crate page.

struct - https://rustdoc.crud.net/jsha/cool-sidebar/std/vec/struct.Vec.html
trait - https://rustdoc.crud.net/jsha/cool-sidebar/std/io/trait.Read.html
crate - https://rustdoc.crud.net/jsha/cool-sidebar/std/index.html
mod - https://rustdoc.crud.net/jsha/cool-sidebar/std/any/index.html
macro - https://rustdoc.crud.net/jsha/cool-sidebar/std/macro.panic.html
fn - https://rustdoc.crud.net/jsha/cool-sidebar/std/io/fn.stdin.html
type alias - https://rustdoc.crud.net/jsha/cool-sidebar/std/io/type.Result.html
keyword - https://rustdoc.crud.net/jsha/cool-sidebar/std/keyword.as.html
primitive - https://rustdoc.crud.net/jsha/cool-sidebar/std/primitive.pointer.html

r? @GuillaumeGomez 
cc @camelid 
[Discussed on Zulip](https://rust-lang.zulipchat.com/#narrow/stream/266220-rustdoc/topic/sidebar.20headings).

Note: This has a lot of smaller commits, but I plan to squash them before merging.

### CODE REVIEW

File: src/librustdoc/html/render/mod.rs [hunk 1]
```diff
@@ -1131,7 +1131,7 @@ fn render_assoc_items_inner(
             write!(
                 w,
                 "<h2 id=\"trait-implementations\" class=\"small-section-header\">\
-                     Trait Implementations<a href=\"#trait-implementations\" class=\"anchor\"></a>\
+                     Traits<a href=\"#trait-implementations\" class=\"anchor\"></a>\
```
Comment (GuillaumeGomez) [inline src/librustdoc/html/render/mod.rs:1134]: That's a bit weird when reading the sidebar because it doesn't make difference anymore between "traits implementation" and "traits in the same module" which is below.

**Comment by GuillaumeGomez** [comment]
Wouldn't it be better to have the current item name in the sidebar use the color of its type? Because it's currently difficult to make the difference between this one and the other titles. A screenshot:

Screenshot from 2022-01-09 16-16-41

**Comment by GuillaumeGomez** [comment]
It'd be nice to change the display of the version because currently it's absolutely the same as the other links in the sidebar:

Screenshot from 2022-01-09 16-19-06

File: src/librustdoc/html/render/mod.rs [hunk 2]
```diff
@@ -1744,45 +1744,26 @@ fn print_sidebar(cx: &Context<'_>, it: &clean::Item, buffer: &mut Buffer) {
...
-                clean::UnionItem(..) => "Union ",
-                clean::EnumItem(..) => "Enum ",
-                clean::TypedefItem(..) => "Type Definition ",
-                clean::ForeignTypeItem => "Foreign Type ",
                 clean::ModuleItem(..) =>
                     if it.is_crate() {
                         "Crate "
                     } else {
-                        "Module "
+                        "Mod "
```
Comment (GuillaumeGomez) [inline src/librustdoc/html/render/mod.rs:1751]: I'm not super fan of this simplification...

**Comment by GuillaumeGomez** [comment]
The burger button is displayed weirdly and is too small I think:
Screenshot from 2022-01-09 16-22-20

Also, the whole header now remains displayed all the time, which is a loss of space. Not sure it's a good idea...

**Comment by GuillaumeGomez** [comment]
Overall I really like the direction it's taking though. The sidebar looks much cleaner. I don't think you should unify it with the source file viewer sidebar though. They have both very different meaning after all.

**Comment by GuillaumeGomez** [comment]
When the item name is too long, the sidebar gets a "x scrollbar":

Screenshot from 2022-01-09 16-32-42

Also, If the name is too long, wouldn't it be better to break it instead? For methods I think it's fine, but for types it seems weird. Even more considering how little letters can be displayed otherwise...

File: src/librustdoc/html/render/mod.rs (hunk 1 above)
Comment (jsha) [reply src/librustdoc/html/render/mod.rs:1134]: They're differentiated by position in the hierarchy, though.

**Comment by jsha** [comment]
> [on mobile] Also, the whole header now remains displayed all the time, which is a loss of space. Not sure it's a good idea...

I think it's a distinctly good idea. The current design, where only the hamburger menu floats along with the page, feels very broken to me. And it doesn't make the top 45px usable because it overlaps with some of the body text. Also, the topbar provides useful context about where you are, and quick click targets to go to the root of the module (and, later, to the top of the page - which I'd like to add in a separate PR).

**Comment by jsha** [comment]
> The current design, where only the hamburger menu floats along with the page, feels very broken to me. And it doesn't make the top 45px usable because it overlaps with some of the body text.

To put this another way: We should either have a topbar that doesn't follow the scroll, or we should have a topbar where the whole width of it follows the scroll. The current situation, where just the hamburger part of the topbar follows the scroll, is unusual UI and doesn't actually get us more usable viewport.

> The source file viewer sidebar is completely broken currently too.

What platform, and what page? I checked on both mobile and desktop, and it looks right to me. Did you hard-reload?

> It'd be nice to change the display of the version because currently it's absolutely the same as the other links in the sidebar:

In dark mode and ayu, I had forgotten to change the display of links to get the link color. Now the version is distinguished from the links.

> Wouldn't it be better to have the current item name in the sidebar use the color of its type? Because it's currently difficult to make the difference between this one and the other titles.

I tried that earlier. It was cool, but in the end I found that it drew too much attention to the sidebar, when the attention should be on the main content. I'll try to distinguish this with better spacing.

> The sidebar looks much cleaner. I don't think you should unify it with the source file viewer sidebar though. They have both very different meaning after all.

Yes, my goal was not to touch the source view sidebar in this PR (though I think it could use some touch-ups too).

> The burger button is displayed weirdly and is too small I think:

I've confirmed this in Firefox and will fix.

File: src/librustdoc/html/render/mod.rs (hunk 1 above)
Comment (camelid) [reply src/librustdoc/html/render/mod.rs:1126]: What about writing "Trait Impls" instead? I think that'd be the most idiomatic.

**Comment by camelid** [comment]
@jsha please rebase instead of merging ;)

**Comment by jsha** [comment]
Alright, I've fixed the source sidebar and the hamburger menu in Firefox Mobile. I also made it so a long item name gets wrapped, and cleaned up some dead code. Updated the demo.

**Comment by camelid** [comment]
@jsha what do you think about https://github.com/rust-lang/rust/pull/92692#r780819896?

File: src/librustdoc/html/render/mod.rs (hunk 1 above)
Comment (jsha) [reply src/librustdoc/html/render/mod.rs:1126]: I think "Trait Impls" is idiomatic in the sense that jargon is usually idiomatic. But we should avoid jargon in the docs and prefer to match what's in The Book and The Reference where possible. So my preference order would be:

1. Traits
2. Trait Implementations // I'm totally fine with this one!
3. Trait Impls // less preferred

Comment (camelid) [reply src/librustdoc/html/render/mod.rs:1126]: `impl` is the actual keyword; in some ways, it seems clearer to me than "implementations", and it's certainly shorter.

"Traits" seems slightly confusing to me, especially since traits may be listed multiple times in that list (with different generics).

Comment (jsha) [reply src/librustdoc/html/render/mod.rs:1126]: It's the keyword, but the keyword is never plural (and is usually seen in monospace). I got no hits on "impls" in The Book, and just one hit in The Reference.

Comment (jsha) [reply src/librustdoc/html/render/mod.rs:1126]: Anyhow, I do see your point about "Traits" being confusing. How do you feel about switching this back to "Trait Implementations"?

Comment (camelid) [reply src/librustdoc/html/render/mod.rs:1126]: Yeah, I'd like to have more discussion about this at some point (I also feel that "Trait Implementations" is overly verbose), but in the interest of not making too many changes at once, let's leave it as-is.

**Comment by GuillaumeGomez** [comment]
> What platform, and what page? I checked on both mobile and desktop, and it looks right to me. Did you hard-reload?

All source pages on desktop firefox. It was very likely because of the interactions with the hamburger button. It's working fine now. I should have recorded a video, that would helped to see better the issue...

> Also, the topbar provides useful context about where you are, and quick click targets to go to the root of the module (and, later, to the top of the page - which I'd like to add in a separate PR).

I'm not sure what you by this but as always, very curious of what you have in mind. :)

Screenshot from 2022-01-12 10-17-33

Might be a good idea to add some space after the version number to make "all items" easier to see, no?

> In dark mode and ayu, I had forgotten to change the display of links to get the link color. Now the version is distinguished from the links.

:+1: 

> I tried that earlier. It was cool, but in the end I found that it drew too much attention to the sidebar, when the attention should be on the main content. I'll try to distinguish this with better spacing.

Much better indeed!

> Yes, my goal was not to touch the source view sidebar in this PR (though I think it could use some touch-ups too).

I confirm that the sidebar "header" was removed on the source pages. :+1: 

Once you're done with the changes, please add GUI tests for the following things:
 * colors of the items in the sidebar
 * That for long item name, it doesn't add a scrollbar
 * That the sidebar header is displayed (or not displayed in the case of source pages) and is working as expected on mobile.

And I think that's it? I really can't wait to have all these improvements merged! :D

**Comment by GuillaumeGomez** [comment]
The font size for the source code pages sidebar has been reduced:

On current nightly:
Screenshot from 2022-01-14 10-44-04

On your PR:
Screenshot from 2022-01-14 10-43-51

Is it expected? In any case, could you add a test to check the font size in the source code sidebar please?

There is margin on the right in mobile when a link is hovered/selected:

Screenshot from 2022-01-14 10-49-09

Is it voluntary?

File: src/librustdoc/html/static/js/main.js [hunk 3]
```diff
@@ -67,6 +67,11 @@ function resourcePath(basename, extension) {
             ty: sidebarVars.attributes["data-ty"].value,
             relpath: sidebarVars.attributes["data-relpath"].value,
         };
+        var mobileLocationTitle = document.querySelector(".mobile-topbar h2.location");
```
Comment (GuillaumeGomez) [inline src/librustdoc/html/static/js/main.js:70]: Why do you need JS for that? Wouldn't it be better to generate it as is directly?

File: src/test/rustdoc/cap-lints.rs [hunk 4]
```diff
@@ -3,7 +3,7 @@
 // therefore should not concern itself with the lints.
 #[deny(warnings)]
 
-// @has cap_lints/struct.Foo.html //* 'Struct Foo'
+// @has cap_lints/struct.Foo.html //* 'Foo'
```
Comment (GuillaumeGomez) [inline src/test/rustdoc/cap-lints.rs:6]: Just thought: could add a check for `module` and `crate` too please?

File: src/librustdoc/html/static/js/main.js (hunk 3 above)
Comment (jsha) [reply src/librustdoc/html/static/js/main.js:70]: I tried generating directly and it would have required a significant refactoring in what gets passed to page generation for the sidebar. I figure we can always refine that later if we want.

Comment (GuillaumeGomez) [reply src/librustdoc/html/static/js/main.js:70]: Can you add a fixme then please?

File: src/test/rustdoc-gui/sidebar-source-code.goml [hunk 5]
```diff
@@ -10,6 +10,7 @@ click: (10, 10)
 // We wait for the sidebar to be expanded (there is a 0.5s animation).
 wait-for: 600
 assert-css: ("nav.sidebar.expanded", {"width": "300px"})
+assert-css: ("nav.sidebar.expanded a", {"font-size": "14.4px"})
```
Comment (GuillaumeGomez) [inline src/test/rustdoc-gui/sidebar-source-code.goml:13]: Nice!

File: src/test/rustdoc-gui/sidebar-source-code.goml [hunk 6]
```diff
@@ -30,3 +31,6 @@ click: (10, 10)
 // We ensure that the class has been removed.
 assert-false: "nav.sidebar.expanded"
 assert: "nav.sidebar"
+
+// Check that the topbar is not visible
+assert-property: (".mobile-topbar", {"offsetParent": "null"})
```
Comment (GuillaumeGomez) [inline src/test/rustdoc-gui/sidebar-source-code.goml:36]: 👍

File: src/test/rustdoc-gui/sidebar.goml [hunk 7]
```diff
@@ -1,8 +1,10 @@
 goto: file://|DOC_PATH|/test_docs/index.html
+show-text: true
 assert-text: (".sidebar > .location", "Crate test_docs")
 // In modules, we only have one "location" element.
 assert-count: (".sidebar .location", 1)
-assert-text: (".sidebar-elems > #all-types", "See all test_docs's items")
+assert-text: ("#all-types", "All Items")
+assert-css: ("#all-types", {"color": "rgb(56, 115, 173)"})
```
Comment (GuillaumeGomez) [inline src/test/rustdoc-gui/sidebar.goml:7]: When you show text to check color, please set the theme as it might fail if someone has a different one on their computer.

**Comment by GuillaumeGomez** [comment]
> I don't think there's a reason for source sidebar to have a different font size than doc sidebar, right?

If it's voluntary then it's fine! 👍 

Overall it's really great and we're almost there! Just a fixme to add and to set the theme when checking the text color.

File: src/test/rustdoc-gui/sidebar.goml (hunk 7 above)
Comment (jsha) [reply src/test/rustdoc-gui/sidebar.goml:11]: Done! Note: the GUI tests should probably set the theme explicitly to light by default so they are never impacted by settings on the computer they're running on.

**Comment by jsha** [comment]
@bors try

Getting a CI build so I can try building with this inside a local docs.rs to test style interactions.

**Comment by jsha** [comment]
I pushed another small commit e0334f63c3f2a660fd8af077901b4f07a2007159 with some late-breaking fixes:

Set padding: 0 on buttons to fix display issue on Safari (hamburger menu had an unwanted left-padding of 32px.

Change selector from `body.rustdoc` to `.rustdoc` to accomodate docs.rs.

Move scroll-padding-top rule into .rustdoc selector.

File: src/test/rustdoc-gui/sidebar.goml (hunk 7 above)
Comment (GuillaumeGomez) [reply src/test/rustdoc-gui/sidebar.goml:11]: I thought they were impacted by the system theme settings. Maybe it was another bug. In any case, thanks for going along with it!

**Review by GuillaumeGomez — APPROVED** [review]

**Comment by GuillaumeGomez** [comment]
Just checked and it seems there is still some space on the right of the sidebar items on mobile:

Screenshot 2022-01-16 at 12 26 56

**Comment by jsha** [comment]
Thanks for spotting that! I fixed it, and the fix even allowed me to simplify the CSS (removed a `.sidebar-links>a { width: 100% }` rule that was interfering). Demo is updated.

File: src/test/rustdoc/crate-version-escape.rs [hunk 8]
```diff
@@ -2,5 +2,4 @@
 
 #![crate_name = "foo"]
 
-// @has 'foo/index.html' '//div[@class="block version"]/p' 'Version <script>alert("hi")</script>'
-// @has 'foo/all.html' '//div[@class="block version"]/p' 'Version <script>alert("hi")</script>'
```
Comment (GuillaumeGomez) [inline src/test/rustdoc/crate-version-escape.rs:6]: Just realized: why removing the display of the version on the `all items` page?

Comment (jsha) [reply src/test/rustdoc/crate-version-escape.rs:6]: It never really made any sense. The version is supposed to be only on the crate page - why add it to just one other page?

Comment (GuillaumeGomez) [reply src/test/rustdoc/crate-version-escape.rs:6]: The all items page is a bit on its but as long as it's a voluntary change, it's fine. :)

**Review by GuillaumeGomez — APPROVED** [review]

**Comment by GuillaumeGomez** [comment]
Thanks a lot for the improvements! Since it's very conflict-prone, I'll increase its priority a bit.

@bors: r+ p=

**Comment by GuillaumeGomez** [comment]
With the priority this time...

@bors: p=1

**Comment by marmeladema** [comment]
@jsha  @GuillaumeGomez maybe GitHub is showing a wrong diff, but is it expected that this rustdoc PR updates the llvm-project submodule?

**Comment by jsha** [comment]
@marmeladema thanks for catching that! Indeed that is not expected.

@bors r-

**Comment by jsha** [comment]
Pushed a new commit with the spurious diffs to llvm-project removed. Look good @marmeladema ?

**Comment by marmeladema** [comment]
Yeah much better :+1:

**Comment by GuillaumeGomez** [comment]
Seems like bors "forgot" about this PR. Let's try to close/re-open it.

**Comment by GuillaumeGomez** [comment]
Bingo!

**Comment by GuillaumeGomez** [comment]
Failure in tests.

@bors: r-

**Comment by jsha** [comment]
Fixed the test. :-)

**Review by GuillaumeGomez — APPROVED** [review]

**Comment by GuillaumeGomez** [comment]
Thanks!

r=me once CI pass

**Comment by jsha** [comment]
I also fixed a small late-breaking bug: The new sidebar width (250px) was being applied in `media(min-width: 700px)` only, causing the sidebar to be squished on some full-sized windows. I moved it to the main sidebar styles.

**Comment by camelid** [comment]
@bors r-

@jsha did you mean r=GuillaumeGomez?

**Comment by jsha** [comment]
Ah, thanks @camelid. Still getting the hang of bors.

@bors r=GuillaumeGomez

**Comment by workingjubilee** [comment]
Somehow, this got set to p=1.
It will likely get rolled up later, and it would be inconvenient if it skipped ahead of rollup=never PRs without being rolled up.

@bors p=0

**Comment by nbdd0121** [comment]
I have to say that I really dislike the new style, especially in dark mode. It is much less accessible than previous style.
* The biggest issue is contrast.
  
  In the dark theme, the foreground color is `#D2991D` and the background color of the sidebar is `#505050`. The computed contrast ratio (using https://webaim.org/resources/contrastchecker/) is 3.19:1 and this violates WCAG AA's requirement of >4.5:1 for normal-sized text.
* The section division is less clear than the previous style. Color and font size becomes the way to distinguish.
* The link color in dark mode really stands out, and having a whole sidebar full of the color made the situation worse.
* The added padding to the sidebar and warping reduces the information density of the sidebar.
* Not sure if this is introduced by this PR, but `[src]` is changed to `source`. This makes the page feel visually more crowded. Since this is there for all items instead of a link it should be treated as a button (like the run button of code snippets).

Overall for documentation I think accessibility, clarity and easiness to navigate is much more important than style discrepencies.

**Comment by GuillaumeGomez** [comment]
There is https://github.com/rust-lang/rust/pull/93231 open to reduce this issue. Does it improve your situation?

**Comment by nbdd0121** [comment]
It certainly helps with the contrast issue. But I still think the old UI style is much more usable and pragmatic.

I suggest that an user survey to be performed for such a major UI change.

**Comment by camelid** [comment]
Our goal with this change was to make the sidebar easier to use, but I agree that some changes may have made it worse. I do think that decreasing padding and finding a way to increase distinctions between different components of the sidebar would be good.

The `[src]` -> `source` change was made in a different PR: #92602

**Comment by jsha** [comment]
FYI, the vertical spacing is precisely the same before and after:

image

The left margin went from to 10px to 24px. However, the max width of the sidebar went from 200px to 250px. As a result, _more_ of the method names are visible than before.

There is indeed a bug with wrapping / ellipsis, which I think was introduced in a different change. I'll send a patch for that shortly.

**Comment by nbdd0121** [comment]
I use a vertically oriented display for doc viewing, so the added left margin means less horizontal space for the content. Perhaps the left margin should be adaptive to the screen width?

**Comment by RDambrosio016** [comment]
I personally think that changing the color to be yellow is fine (though i prefer white). However i really dislike the removal of the separator lines, i.e. the border around the struct name and the lines around `Methods` and similar. Without it it just looks all merged and without clear separation, i just think it looks worse overall.

**Comment by pravic** [comment]
> However i really dislike the removal of the separator lines, i.e. the border around the struct name and the lines around Methods and similar. Without it it just looks all merged and without clear separation, i just think it looks worse overall.

I confirm. The new UI looks as a regression, it's just plain flat. Not that the old UI was perfect, but it was consistent across Rust versions with gradual QOL improvements.

I've created #95816 as a regression report and then was pointed out to this PR.
