### PR TITLE
Warn about unused captured variables

### LINKED ISSUE #37707: Give a "modifying moved binding" or "unread value" warning in move-closures
Take a look at this logically wrong example:

```rust
fn main() {
    let mut x = 1;
    let y = (1..10).fold(0, move|acc, e| {
        x *= e; // should warn: new value of `x` never read
        acc + e
    });
    println!("{} {}", x, y); // outputs: `1 45`
}
```

It would be best if the compiler points out that "updating `x` inside the closure will not have an external effect." Though, I would be happy if the compiler at least pointed out that "the modified value in the new binding `x` is never read."

### LINKED ISSUE #47128: unused_mut lint improvement: warn when variable only copied into closure
Minimal example of the lint failure to fire:
```
fn foo() -> bool {
    let mut res = false;
    
    let mut do_thing = move || res = true;
    do_thing();
    
    res
}
```

`foo` unconditionally returns false, but the top-level binding of `res` doesn't get an `unused_mut` warning.

### LINKED ISSUE #63220: Move closure copies :Copy variables silently
## The Good

Given the following code:

```rust
fn main() {
    let mut x = 0;
    dbg!(x);
}
```
https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=19261742184207a4075885cae58680e1

I got a reasonable warning:

```
warning: variable does not need to be mutable
 --> src/main.rs:2:9
  |
2 |     let mut x = 0;
  |         ----^
  |         |
  |         help: remove this `mut`
```

## The Bad

Suggest we have the following code:

```rust
fn main() {
    let mut x = 0;
    let mut f = move || x = 42;
    f();
    dbg!(x);
}
```

https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=42c989cf63f57e5bad0f572bb705b69f

Neither rustc nor clippy gives me any warning. `x = 42` affects a local copy of `x`, not the outer one, that's why dbg prints `x=0`. This can result in a buggy code.

## The Ugly

`async move` closures are affected too. Replacing FnMut's with async move closures light-headedly will add unexpected bugs. Example from https://docs.rs/futures-preview/0.3.0-alpha.17/futures/stream/trait.StreamExt.html#method.for_each:

```diff
-let fut = stream::repeat(1).take(3).for_each(|item| {
+let fut = stream::repeat(1).take(3).for_each(async move |item| {
      x += item;
-     ready(())
 });
```

```rust
// futures 0.3
#![feature(async_await, async_closure)]
use futures::future;
use futures::stream::{self, StreamExt};

let mut x = 0;

{
    let fut = stream::repeat(1).take(3).for_each(async move |item| {
        x += item;
    });
    fut.await;
}

assert_eq!(x, 3); // BOOM! x = 0
```

### PR DESCRIPTION
**Pull request by tmiasko**
Include captured variables in liveness analysis. Warn when captured variables
are unused (but possibly read or written to). Warn about dead assignments to
captured variables.

Fixes #37707.
Fixes #47128.
Fixes #63220.

### CODE REVIEW

File: src/test/ui/liveness/liveness-upvars.rs [hunk 1]
```diff
@@ -0,0 +1,85 @@
+// check-pass
+#![crate_type = "lib"]
+#![warn(unused)]
+
+pub fn f0() {
+    let mut last = None;
+    let mut f = move |s| {
+        last = Some(s); //~  WARN value assigned to `last` is never read
+                        //~| WARN variable `last` is assigned to, but never used
```
Comment (nikomatsakis) [inline src/test/ui/liveness/liveness-upvars.rs:9]: isn't this... false? Oh, I guess it's true because of the `move`

File: src/test/ui/liveness/liveness-upvars.rs [hunk 2]
```diff
@@ -0,0 +1,85 @@
...
+
+pub fn f2() {
+    let mut c = 0;
+    let mut d = None;
+    let mut e = None;
+
+    || {
+        move || {
+            println!("{}", c);
+            c += 1;
```
Comment (nikomatsakis) [inline src/test/ui/liveness/liveness-upvars.rs:33]: Is the reason that we get no warning here because we assume the closure may be called again?

File: src/test/ui/liveness/liveness-upvars.rs (hunk 1 above)
Comment (nikomatsakis) [reply src/test/ui/liveness/liveness-upvars.rs:9]: I wonder if we can provide some 'help" text or something about that

Comment (nikomatsakis) [reply src/test/ui/liveness/liveness-upvars.rs:9]: can we add a test like this, except that the closure is *not* `move`?

**Review by nikomatsakis — CHANGES_REQUESTED** [review]
Did a quick skim, just of the test cases, and left a few comments. What would be really great is if there was some kind of write-up explaining how this extension to the new analysis works -- not so much the details of the impl, but the high-level idea of when I should expect warnings and so forth. e.g., does it assume closures might be called than once? Does it try to track which closures are *actually* called? If they are `FnOnce`, does it still assume that? etc

**Comment by tmiasko** [comment]
There is one longer comment trying to give high-level idea behind the analysis. The computation is still about what happens within a single function / closure. Whether closure is actually invoked is outside the consideration.

Analysis assumes that variables captured by reference will be used after leaving the closure. For variables captured by value it takes into account the closure kind. In FnOnce closures, variables captured by value are presumed dead after exit. In Fn / FnMut closures, it assumes that variables captured by value might be accessed again, but only by the closure itself on subsequent invocations.

For variables captured by value, is also presumes that the initial captured value should be used and warns otherwise.

File: src/test/ui/liveness/liveness-upvars.rs (hunk 1 above)
Comment (tmiasko) [reply src/test/ui/liveness/liveness-upvars.rs:9]: As for an additional explanation, maybe something along the lines of: "variable captured by value, did you mean to capture by reference instead?", possibly highlighting the "move" part of closure.

File: src/test/ui/liveness/liveness-upvars.rs (hunk 2 above)
Comment (tmiasko) [reply src/test/ui/liveness/liveness-upvars.rs]: Yes. The store is not dead because it might be read by the closure when called again. I added similar test cases for FnOnce and generators to show the difference.

File: src/librustc_passes/liveness.rs [hunk 3]
```diff
@@ -677,11 +667,8 @@ impl<'a, 'tcx> Liveness<'a, 'tcx> {
         // - exit_ln represents the end of the fn, either by return or panic
         // - implicit_ret_var is a pseudo-variable that represents
```
Comment (nikomatsakis) [inline src/librustc_passes/liveness.rs:668]: pre-existing, I guess, but these comments seem out of date

File: src/librustc_passes/liveness.rs [hunk 4]
```diff
@@ -647,9 +638,8 @@ impl RWUTable {
 
 #[derive(Copy, Clone)]
 struct Specials {
```
Comment (nikomatsakis) [inline src/librustc_passes/liveness.rs:640]: Pre-existing, but if we're going  to be extending this code, can we add a doc-comment explaining what a "special" is.

File: src/librustc_passes/liveness.rs [hunk 5]
```diff
@@ -903,30 +907,92 @@ impl<'a, 'tcx> Liveness<'a, 'tcx> {
...
+    fn compute(
+        &mut self,
+        fk: FnKind<'_>,
+        body: &hir::Body<'_>,
+        span: Span,
+        id: hir::HirId,
+    ) -> LiveNode {
+        debug!("compute: using id for body, {:?}", body.value);
+
+        let mut only_by_ref_upvars = true;
```
Comment (nikomatsakis) [inline src/librustc_passes/liveness.rs:919]: Comment here would be nice -- 

* why do we care if we only have by-ref upvars?
* what is the role of the `self.acc` below (presumably so that we assume that by-ref upvars are used after the closure completes)

File: src/librustc_passes/liveness.rs [hunk 6]
```diff
@@ -903,30 +907,92 @@ impl<'a, 'tcx> Liveness<'a, 'tcx> {
...
+                span_bug!(span, "type of closure expr {:?} is not a closure {:?}", id, ty,);
+            }
+        };
+
+        self.init_from_succ(self.s.entry_ln, succ);
+        for param in body.params {
+            param.pat.each_binding(|_bm, hir_id, _x, ident| {
+                let var = self.variable(hir_id, ident.span);
+                self.define(self.s.entry_ln, var);
+            })
```
Comment (nikomatsakis) [inline src/librustc_passes/liveness.rs:978]: can't we make this more dry by doing something like

```
let mut first_merge = true;
loop {
    self.init_from_succ(self.s.entry_ln, succ);
    for param in body.params {
            param.pat.each_binding(|_bm, hir_id, _x, ident| {
                let var = self.variable(hir_id, ident.span);
                self.define(self.s.entry_ln, var);
    })

    if !self.merge_from_succ(...) { break; }
    first_merge = false;
}
```

File: src/librustc_passes/liveness.rs [hunk 7]
```diff
@@ -903,30 +907,92 @@ impl<'a, 'tcx> Liveness<'a, 'tcx> {
...
-        // explicitly return:
-        let s = self.s;
-        self.init_from_succ(s.fallthrough_ln, s.exit_ln);
-        self.acc(s.fallthrough_ln, s.clean_exit_var, ACC_READ);
+        let succ = self.propagate_through_expr(&body.value, self.s.exit_ln);
 
-        let entry_ln = self.propagate_through_expr(body, s.fallthrough_ln);
+        // When computing the liveness for captured variables we take into
+        // account how variable is captured (ByRef vs ByValue) and what is the
+        // closure kind (Generator / FnOnce vs Fn / FnMut).
```
Comment (nikomatsakis) [inline src/librustc_passes/liveness.rs:942]: this comment captures some of  the points I raised above, it just came later so I wouldn't have seen it yet while reading the code

File: src/librustc_passes/liveness.rs [hunk 8]
```diff
@@ -903,30 +907,92 @@ impl<'a, 'tcx> Liveness<'a, 'tcx> {
...
+        //
+        // Variables captured by reference are assumed to be used on the exit
+        // from the closure.
+        //
+        // In FnOnce closures, variables captured by value are known to be dead
+        // on exit since it is impossible to invoke the closure again.
+        //
+        // In Fn / FnMut closures, variables captured by value are live on exit
+        // if they are live on the entry to the closure, since only the closure
+        // itself can access them on subsequent invocations.
```
Comment (nikomatsakis) [inline src/librustc_passes/liveness.rs:952]: where does this logic get setup, though?

Comment (nikomatsakis) [reply src/librustc_passes/liveness.rs:952]: (maybe mention it in the comment)

**Review by nikomatsakis — APPROVED** [review]
r=me with comment, nits fixed

File: src/librustc_passes/liveness.rs (hunk 7 above)
Comment (tmiasko) [reply src/librustc_passes/liveness.rs]: Moved comment to the start of the function.

**Comment by ltratt** [comment]
I might be doing something wrong, but this PR doesn't seem to produce a warning for the example I had in https://github.com/rust-lang/rust/issues/63220#issuecomment-558688508. Perhaps it's because the captured variable is used?

**Comment by tmiasko** [comment]
@ltratt println inside the closure uses the captured variable, so there will be no warning. It will warn when println is removed, or about the real bug linked from that comment.

**Comment by ltratt** [comment]
@tmiasko You're quite right! I tried the "real bug" link and it gives the "unused variable" warning. Thank much for fixing this problem *and* for pointing out that I'd checked the wrong thing :)
