### PR TITLE
Fix Rc/Arc allocation layout

### LINKED ISSUE #55747: Rc/Arc for DST compute layout incorrectly
https://github.com/rust-lang/rust/pull/54922 introduced a critical bug where the layout of an allocation is computed incorrectly, leading (at least) to a deallocation with a different size than the allocation.

This is easily demonstrated by cherry-picking https://github.com/RalfJung/rust/commit/c2e59333d94233f40952c75fff4cbc5fc63b11d1 and running `./x.py --stage 1 test src/liballoc` (left is the correct layout, right is what we compute):
```
---- rc::tests::test_clone_from_slice stdout ----
thread 'rc::tests::test_clone_from_slice' panicked at 'assertion failed: `(left == right)`
  left: `Layout { size_: 32, align_: 8 }`,
 right: `Layout { size_: 28, align_: 8 }`', liballoc/rc.rs:683:9

---- rc::tests::test_copy_from_slice stdout ----
thread 'rc::tests::test_copy_from_slice' panicked at 'assertion failed: `(left == right)`
  left: `Layout { size_: 32, align_: 8 }`,
 right: `Layout { size_: 28, align_: 8 }`', liballoc/rc.rs:683:9

---- rc::tests::test_from_box_slice stdout ----
thread 'rc::tests::test_from_box_slice' panicked at 'assertion failed: `(left == right)`
  left: `Layout { size_: 32, align_: 8 }`,
 right: `Layout { size_: 28, align_: 8 }`', liballoc/rc.rs:683:9

---- rc::tests::test_from_box stdout ----
thread 'rc::tests::test_from_box' panicked at 'assertion failed: `(left == right)`
  left: `Layout { size_: 24, align_: 8 }`,
 right: `Layout { size_: 20, align_: 8 }`', liballoc/rc.rs:683:9

---- rc::tests::test_from_box_str stdout ----
thread 'rc::tests::test_from_box_str' panicked at 'assertion failed: `(left == right)`
  left: `Layout { size_: 24, align_: 8 }`,
 right: `Layout { size_: 19, align_: 8 }`', liballoc/rc.rs:683:9

---- rc::tests::test_from_box_trait stdout ----
thread 'rc::tests::test_from_box_trait' panicked at 'assertion failed: `(left == right)`
  left: `Layout { size_: 24, align_: 8 }`,
 right: `Layout { size_: 20, align_: 8 }`', liballoc/rc.rs:683:9

---- rc::tests::test_from_vec stdout ----
thread 'rc::tests::test_from_vec' panicked at 'assertion failed: `(left == right)`
  left: `Layout { size_: 32, align_: 8 }`,
 right: `Layout { size_: 28, align_: 8 }`', liballoc/rc.rs:683:9

---- rc::tests::test_from_str stdout ----
thread 'rc::tests::test_from_str' panicked at 'assertion failed: `(left == right)`
  left: `Layout { size_: 24, align_: 8 }`,
 right: `Layout { size_: 19, align_: 8 }`', liballoc/rc.rs:683:9

---- rc::tests::test_into_from_raw_unsized stdout ----
thread 'rc::tests::test_into_from_raw_unsized' panicked at 'assertion failed: `(left == right)`
  left: `Layout { size_: 24, align_: 8 }`,
 right: `Layout { size_: 19, align_: 8 }`', liballoc/rc.rs:683:9

---- sync::tests::test_clone_from_slice stdout ----
thread 'sync::tests::test_clone_from_slice' panicked at 'assertion failed: `(left == right)`
  left: `Layout { size_: 32, align_: 8 }`,
 right: `Layout { size_: 28, align_: 8 }`', liballoc/sync.rs:586:9

---- sync::tests::test_copy_from_slice stdout ----
thread 'sync::tests::test_copy_from_slice' panicked at 'assertion failed: `(left == right)`
  left: `Layout { size_: 32, align_: 8 }`,
 right: `Layout { size_: 28, align_: 8 }`', liballoc/sync.rs:586:9

---- sync::tests::test_from_box stdout ----
thread 'sync::tests::test_from_box' panicked at 'assertion failed: `(left == right)`
  left: `Layout { size_: 24, align_: 8 }`,
 right: `Layout { size_: 20, align_: 8 }`', liballoc/sync.rs:586:9

---- sync::tests::test_from_box_slice stdout ----
thread 'sync::tests::test_from_box_slice' panicked at 'assertion failed: `(left == right)`
  left: `Layout { size_: 32, align_: 8 }`,
 right: `Layout { size_: 28, align_: 8 }`', liballoc/sync.rs:586:9

---- sync::tests::test_from_box_str stdout ----
thread 'sync::tests::test_from_box_str' panicked at 'assertion failed: `(left == right)`
  left: `Layout { size_: 24, align_: 8 }`,
 right: `Layout { size_: 19, align_: 8 }`', liballoc/sync.rs:586:9

---- sync::tests::test_from_box_trait stdout ----
thread 'sync::tests::test_from_box_trait' panicked at 'assertion failed: `(left == right)`
  left: `Layout { size_: 24, align_: 8 }`,
 right: `Layout { size_: 20, align_: 8 }`', liballoc/sync.rs:586:9

---- sync::tests::test_from_str stdout ----
thread 'sync::tests::test_from_str' panicked at 'assertion failed: `(left == right)`
  left: `Layout { size_: 24, align_: 8 }`,
 right: `Layout { size_: 19, align_: 8 }`', liballoc/sync.rs:586:9

---- sync::tests::test_from_vec stdout ----
thread 'sync::tests::test_from_vec' panicked at 'assertion failed: `(left == right)`
  left: `Layout { size_: 32, align_: 8 }`,
 right: `Layout { size_: 28, align_: 8 }`', liballoc/sync.rs:586:9

---- sync::tests::test_into_from_raw_unsized stdout ----
thread 'sync::tests::test_into_from_raw_unsized' panicked at 'assertion failed: `(left == right)`
  left: `Layout { size_: 24, align_: 8 }`,
 right: `Layout { size_: 19, align_: 8 }`', liballoc/sync.rs:586:9
```

Cc @murarth

### PR DESCRIPTION
**Pull request by murarth**
* Rounds allocation layout up to a multiple of alignment
* Adds a convenience method `Layout::pad_to_align` to perform rounding

Closes #55747 

cc #55724

### CODE REVIEW

**Comment by murarth** [comment]
This PR adds a new method `Layout::pad_to_align`, using the same feature gate as existing unstable methods: `#[unstable(feature = "allocator_api", issue = "32838")]`.

I'm not sure if this is acceptable or if futher discussion is required. That's why I've cc'd the relevant tracking issue for these methods.

**Comment by RalfJung** [comment]
The Rc/Arc part looks good to me.

Cc @Amanieu are you okay with the new unstable method on `Layout`? We can change this later; now it'd be good to get this bug fixed ASAP.

File: src/libcore/alloc.rs [hunk 1]
```diff
@@ -220,6 +220,23 @@ impl Layout {
...
     }
 
+    /// Creates a layout by rounding the size of this layout up to a multiple
+    /// of the layout's alignment.
+    ///
+    /// Returns `Err` if the padded size would overflow.
+    ///
+    /// This is equivalent to adding the result of `padding_needed_for`
+    /// to the layout's current size.
+    #[unstable(feature = "allocator_api", issue = "32838")]
```
Comment (Amanieu) [inline src/libcore/alloc.rs]: Can you change this to use the new feature name and tracking issue from #55366?

**Comment by murarth** [comment]
I've made the requested changes and the tests have passed.

**Comment by murarth** [comment]
@RalfJung Will do. Sorry about that. I thought amending was the expected convention.

File: src/libcore/alloc.rs [hunk 2]
```diff
@@ -218,6 +218,23 @@ impl Layout {
...
+    /// This is equivalent to adding the result of `padding_needed_for`
+    /// to the layout's current size.
+    #[unstable(feature = "alloc_layout_extra", issue = "55724")]
+    #[inline]
+    pub fn pad_to_align(&self) -> Result<Layout, LayoutErr> {
+        let pad = self.padding_needed_for(self.align());
+        let new_size = self.size().checked_add(pad)
+            .ok_or(LayoutErr { private: () })?;
+
+        Layout::from_size_align(new_size, self.align())
```
Comment (SimonSapin) [inline src/libcore/alloc.rs]: This could be `from_size_align_unchecked`, right?
