### PR TITLE
Rustdoc improvements

### LINKED ISSUE #50658: Missing results in rustdoc search
Results that differ in only the parent type are missing in the search results. For example searching `is_nan` misses `f64::is_nan`: https://doc.rust-lang.org/nightly/std/?search=is_nan. It also says there are 4 results but only shows 3.

This is a [stable](https://doc.rust-lang.org/stable/std/?search=is_nan) to [beta](https://doc.rust-lang.org/beta/std/?search=is_nan) regression caused by #49757. cc. @GuillaumeGomez

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Fixes #50658. (last commit)

A lot of small improvements.

r? @QuietMisdreavus

### CODE REVIEW

**Comment by QuietMisdreavus** [comment]
It looks like this includes the commit from https://github.com/rust-lang/rust/pull/50229. Does this require it to be merged first?

**Comment by GuillaumeGomez** [comment]
Oh sorry, forgot to precise: this PR depends on #50229.

**Comment by GuillaumeGomez** [comment]
Rebased.

**Comment by QuietMisdreavus** [comment]
This is a bit above my abstraction threshold for knowing what these are doing offhand. Can you give a quick description of your commits to say what they're supposed to be doing? Since there's no "Fixes (issue link)" i can't tell what you're trying to do here.

**Comment by GuillaumeGomez** [comment]
Sure:

 * first commit: avoid results duplicates when performing multiple queries at once
 * second commit: improve alias rendering (so users can easily see that it's not a "normal" result)
 * third commit: add description in aliases results (I noticed it wasn't there so I added it back)
 * fourth commit: now, the focus/blur on the themes switch buttons is way better (when clicking outside, the menu closes itself, etc...)

File: src/librustdoc/html/static/main.js [hunk 1]
```diff
@@ -1227,19 +1227,30 @@
...
         }
 
+        function escape(content) {
+            var h1 = document.createElement('h1');
+            h1.textContent = content;
+            return h1.innerHTML;
+        }
+
+        function pathSplitter(path) {
+            return '<span>' + path.replace(/::/g, '::</span><span>');
```
Comment (QuietMisdreavus) [inline src/librustdoc/html/static/main.js]: Is there a problem if this function opens a `<span>` tag without closing it?

File: src/librustdoc/html/static/main.js [hunk 2]
```diff
@@ -1362,19 +1381,23 @@
                 function mergeArrays(arrays) {
                     var ret = [];
                     var positions = [];
+                    var notDuplicates = {};
```
Comment (QuietMisdreavus) [inline src/librustdoc/html/static/main.js]: What's with the split between `duplicates` above and `notDuplicates` here?

**Review by QuietMisdreavus — COMMENTED** [review]
Looks good! Just have a couple clarifying questions.

File: src/librustdoc/html/static/main.js (hunk 1 above)
Comment (GuillaumeGomez) [reply src/librustdoc/html/static/main.js]: Good catch. It's an old bug in addition of that!

**Comment by GuillaumeGomez** [comment]
My two last commits reduce the size of `aliases.js` and `search-index.js` (for the second we go from 3458462 to  2493562).

File: src/librustdoc/html/static/main.js (hunk 2 above)
Comment (GuillaumeGomez) [reply src/librustdoc/html/static/main.js]: Explanation time! 😄 

`mergeArrays` is only used when we have multiple queries (for example: "str,[]"). The second one (the one using `duplicates`) allows to remove more global duplicates and is called on every search.

File: src/librustdoc/html/static/main.js [hunk 3]
```diff
@@ -1234,7 +1240,11 @@
         }
 
         function pathSplitter(path) {
-            return '<span>' + path.replace(/::/g, '::</span><span>');
+            var tmp = '<span>' + path.replace(/::/g, '::</span><span>');
+            if (tmp.endsWith("<span>")) {
+                return tmp.slice(0, tmp.length - 6);
+            }
+            return tmp;
```
Comment (QuietMisdreavus) [inline src/librustdoc/html/static/main.js]: What about situations where the string doesn't end in `<span>`? Doesn't that still have an unclosed span?

Comment (GuillaumeGomez) [reply src/librustdoc/html/static/main.js]: No, it always ends with `::`. This is on this string that we make the replacement.

File: src/librustdoc/html/static/main.js (hunk 2 above)
Comment (QuietMisdreavus) [reply src/librustdoc/html/static/main.js]: That makes sense, but why the inversion? Why is one `duplicates` and one `notDuplicates`?

Comment (GuillaumeGomez) [reply src/librustdoc/html/static/main.js]: I have no explanation for this... I didn't write the two functions at the same time so I wrote both without thinking to the other.

File: src/librustdoc/html/static/main.js [hunk 4]
```diff
@@ -1227,19 +1234,34 @@
...
+        }
+
         function addTab(array, query, display) {
             var extraStyle = '';
             if (display === false) {
                 extraStyle = ' style="display: none;"';
             }
 
             var output = '';
+            var duplicates = {};
```
Comment (ollie27) [inline src/librustdoc/html/static/main.js]: When can duplicates occur? Do you have some examples of when this is needed? The `shown` variable below is also trying to remove duplicates and I've tried to remove it in #50482 but if there are duplicates then we'll need to find a better way of dealing with them. `addTab` definitely isn't the correct place to be removing duplicates because it means the search result count will be incorrect: https://doc.rust-lang.org/nightly/std/?search=is_nan.

Comment (GuillaumeGomez) [reply src/librustdoc/html/static/main.js]: It can occurs in case you have aliases. I need to fix the count then.

File: src/librustdoc/html/render.rs [hunk 5]
```diff
@@ -879,8 +901,8 @@ themePicker.onclick = function() {{
     }
 
     fn show_item(item: &IndexItem, krate: &str) -> String {
-        format!("{{'crate':'{}','ty':{},'name':'{}','path':'{}'{}}}",
-                krate, item.ty as usize, item.name, item.path,
+        format!("{{'crate':'{}','ty':{},'name':'{}','desc':'{}','p':'{}'{}}}",
+                krate, item.ty as usize, item.name, item.desc.replace("'", "\\'"), item.path,
```
Comment (ollie27) [inline src/librustdoc/html/render.rs]: `.replace("'", "\\'")` isn't how you escape strings for javascript. You need to use something like `as_json`.

**Review by ollie27 — COMMENTED** [review]
I'd like to see tests for queries that could create duplicate results.

Do you plan to backport this PR to 1.27?

File: src/librustdoc/html/render.rs (hunk 5 above)
Comment (GuillaumeGomez) [reply src/librustdoc/html/render.rs]: Bad surprise, quotes aren't escaped when using `Json` object or json conversion functions so for now, it's the best solution.

**Comment by QuietMisdreavus** [comment]
@bors delegate=ollie27

There’s enough going on here that i’m not too sure what each part is doing, especially since new things have been added into the PR since it’s been opened. On its face, it all *seems* fine, but i’m way less comfortable with Javascript than Rust, so i could be missing something.

**Comment by ollie27** [comment]
Let's get this in.

@bors r+
