### PR TITLE
Generate correct suggestion with named arguments used positionally

### LINKED ISSUE #99265: Incorrect suggestion with `named_arguments_used_positionally` lint
Code:

```rust
fn main() {
    println!("{b} {}", a=1, b=2);
}
```

The current output is:

```
warning: named argument `a` is not used by name
 --> /home/michael/test.rs:2:24
  |
2 |     println!("{b} {}", a=1, b=2);
  |               ---      ^ this named argument is only referred to by position in formatting string
  |               |
  |               this formatting argument uses named argument `a` by position
  |
  = note: `#[warn(named_arguments_used_positionally)]` on by default
help: use the named argument by name to avoid ambiguity
  |
2 |     println!("{a} {}", a=1, b=2);
  |               ~~~
```

Ideally it would look like:

```
  = note: `#[warn(named_arguments_used_positionally)]` on by default
help: use the named argument by name to avoid ambiguity
  |
2 |     println!("{b} {a}", a=1, b=2);
  |                    +
```

1. The suggestion is not exactly correct. Instead of replacing the first named arg with the suggestion, we should replace the first implicitly positional argument.
2. It would also be nice if we could tighten the span on the structured suggestion (see `~~~` -> `+` in the before and after)

### LINKED ISSUE #99266: Investigate why named arguments in FormatSpec.precision seem to have indices that don't correspond to a span in Context.arg_spans
As noted int #99263, named arguments in FormatSpec.precision seem to have indices that don't correspond to a span in Context.arg_spans. This caused an ICE with the `named_arguments_used_positionally` lint, which assumed the index in the FxHashSet for named arguments would correspond to the index for `arg_spans` in context.

Determine if this is a bug or if some sort of translation is necessary and update accordingly.

### PR DESCRIPTION
**Pull request by PrestonFrom**
Address issue #99265 by checking each positionally used argument
to see if the argument is named and adding a lint to use the name
instead. This way, when named arguments are used positionally in a
different order than their argument order, the suggested lint is
correct.

For example:
```
println!("{b} {}", a=1, b=2);
```
This will now generate the suggestion:
```
println!("{b} {a}", a=1, b=2);
```

Additionally, this check now also correctly replaces or inserts
only where the positional argument is (or would be if implicit).
Also, width and precision are replaced with their argument names
when they exists.

Since the issues were so closely related, this fix for issue #99265
also fixes issue #99266.

Fixes #99265
Fixes #99266

### CODE REVIEW

**Comment by PrestonFrom** [comment]
@compiler-errors I just found a bug in how I'm getting the span for width and precision. Please hold off on reviewing!

**Comment by PrestonFrom** [comment]
@compiler-errors Figured out my bug! I think this is ready for a look now.

I am wondering if I should do a crater run to make avoid any issues like last time. Is there a way to do that in GitHub or do I need to do it locally?

File: compiler/rustc_builtin_macros/src/format.rs [hunk 1]
```diff
@@ -32,6 +32,105 @@ enum Position {
...
+    /// The span for the positional named argument (so the lint can point a message to it)
+    positional_named_arg_span: Span,
+}
+
+impl PositionalNamedArg {
+    /// Determines what span to replace with the name of the named argument
+    fn get_span_to_replace(&self, cx: &Context<'_, '_>) -> Option<Span> {
+        if let Some(inner_span) = &self.inner_span_to_replace {
+            return match self.ty {
+                PositionalNamedArgType::Arg | PositionalNamedArgType::Width => Some(Span::new(
```
Comment (compiler-errors) [inline compiler/rustc_builtin_macros/src/format.rs:68]: Can you use `Span::from_inner` instead of doing this math yourself?

File: compiler/rustc_builtin_macros/src/format.rs [hunk 2]
```diff
@@ -32,6 +32,105 @@ enum Position {
...
+                    cx.fmtsp.lo() + BytePos(inner_span.start.try_into().unwrap()),
+                    cx.fmtsp.lo() + BytePos(inner_span.end.try_into().unwrap()),
+                    self.positional_named_arg_span.ctxt(),
+                    self.positional_named_arg_span.parent(),
+                )),
+                PositionalNamedArgType::Precision => Some(Span::new(
```
Comment (compiler-errors) [inline compiler/rustc_builtin_macros/src/format.rs:74]: What's the reason for `+ BytePos(1)`? Leave a comment plz. Or better yet, it would be nice to adjust the place you're getting this from.

And it would also be nice if we could use `Span::from_inner` here too.

**Review by compiler-errors — COMMENTED** [review]
Couple of initial nits, I am still reading thru this to make sure all the logic is correct.

File: compiler/rustc_builtin_macros/src/format.rs (hunk 1 above)
Comment (PrestonFrom) [reply compiler/rustc_builtin_macros/src/format.rs]: I completely missed `from_inner`!

File: compiler/rustc_builtin_macros/src/format.rs (hunk 2 above)
Comment (PrestonFrom) [reply compiler/rustc_builtin_macros/src/format.rs]: Changed so the increment is done in `maybe_push` and added a big comment explaining why. Please let me know if comment is unclear.

And used `from_inner`!

**Comment by PrestonFrom** [comment]
@compiler-errors thanks for the initial comments! Great idea on both of them.

File: compiler/rustc_builtin_macros/src/format.rs [hunk 3]
```diff
@@ -32,6 +32,103 @@ enum Position {
...
+        &mut self,
+        format_argument_index: usize,
+        ty: PositionalNamedArgType,
+        cur_piece: usize,
+        mut inner_span_to_replace: Option<rustc_parse_format::InnerSpan>,
+        names: &FxHashMap<Symbol, (usize, Span)>,
+    ) {
+        let named_arg = names
+            .iter()
+            .find(|name| name.deref().1.0 == format_argument_index)
```
Comment (compiler-errors) [inline compiler/rustc_builtin_macros/src/format.rs:108]: nit: why is this deref call needed? can you destructure things here, e.g.

`.find(|(_, (idx, _))| idx == format_arg_idx)`

File: compiler/rustc_builtin_macros/src/format.rs [hunk 4]
```diff
@@ -32,6 +32,103 @@ enum Position {
...
+            );
+        } else if self.ty == PositionalNamedArgType::Arg {
+            // In the case of a named argument whose position is implicit, there will not be a span
+            // to replace. Instead, we insert the name after the `{`, which is the first character
+            // of arg_span.
+            if let Some(arg_span) = cx.arg_spans.get(self.cur_piece).copied() {
+                return Some(Span::new(
+                    arg_span.lo() + BytePos(1),
+                    arg_span.lo() + BytePos(1),
+                    self.positional_named_arg_span.ctxt(),
```
Comment (compiler-errors) [inline compiler/rustc_builtin_macros/src/format.rs:78]: Why are you using the ctxt and parent from `self.positional_named_arg_span`?

File: compiler/rustc_builtin_macros/src/format.rs [hunk 5]
```diff
@@ -32,6 +32,103 @@ enum Position {
...
+    fn get_span_to_replace(&self, cx: &Context<'_, '_>) -> Option<Span> {
+        if let Some(inner_span) = &self.inner_span_to_replace {
+            return Some(
+                cx.fmtsp.from_inner(InnerSpan { start: inner_span.start, end: inner_span.end }),
+            );
+        } else if self.ty == PositionalNamedArgType::Arg {
+            // In the case of a named argument whose position is implicit, there will not be a span
+            // to replace. Instead, we insert the name after the `{`, which is the first character
+            // of arg_span.
+            if let Some(arg_span) = cx.arg_spans.get(self.cur_piece).copied() {
```
Comment (compiler-errors) [inline compiler/rustc_builtin_macros/src/format.rs:74]: nit
```suggestion
            if let Some(arg_span) = cx.arg_spans.get(self.cur_piece) {
```

File: compiler/rustc_builtin_macros/src/format.rs (hunk 4 above)
Comment (compiler-errors) [reply compiler/rustc_builtin_macros/src/format.rs:78]: You can also probably just do `arg_span.with_lo(arg_span.lo() + BytePos(1)).shrink_to_lo()`

File: compiler/rustc_builtin_macros/src/format.rs [hunk 6]
```diff
@@ -32,6 +32,103 @@ enum Position {
...
+            .iter()
+            .find(|name| name.deref().1.0 == format_argument_index)
+            .map(|found| found.clone());
+
+        if let Some(named_arg) = named_arg {
+            // In FormatSpec, `precision_span` starts at the leading `.`, which we want to keep in
+            // the lint suggestion, so increment `start` by 1 when `PositionalArgumentType` is
+            // `Precision`.
+            if ty == PositionalNamedArgType::Precision {
+                inner_span_to_replace = inner_span_to_replace.map(|mut is| {
```
Comment (compiler-errors) [inline compiler/rustc_builtin_macros/src/format.rs:116]: tiny microscopic nit: can we do this without mutating, lol

File: compiler/rustc_builtin_macros/src/format.rs [hunk 7]
```diff
@@ -32,6 +32,103 @@ enum Position {
...
+                    is.start += 1;
+                    is
+                });
+            }
+            self.positional_named_args.push(PositionalNamedArg {
+                ty,
+                cur_piece,
+                inner_span_to_replace,
+                replacement: named_arg.0.clone(),
+                positional_named_arg_span: named_arg.1.1.clone(),
```
Comment (compiler-errors) [inline compiler/rustc_builtin_macros/src/format.rs:126]: same here re: destructuring

File: compiler/rustc_builtin_macros/src/format.rs [hunk 8]
```diff
@@ -349,10 +482,25 @@ impl<'a, 'b> Context<'a, 'b> {
...
         match c {
             parse::CountImplied | parse::CountIs(..) => {}
             parse::CountIsParam(i) => {
+                let start_of_named_args = self.args.len() - self.names.len();
+                if i >= start_of_named_args {
+                    self.unused_names_lint.maybe_push(
+                        i,
+                        named_arg_type,
+                        self.curpiece,
+                        inner_span.clone(),
```
Comment (compiler-errors) [inline compiler/rustc_builtin_macros/src/format.rs:500]: Is `inner_span` not `Copy`? If not, then it probably can be.

```suggestion
                        *inner_span,
```

File: compiler/rustc_builtin_macros/src/format.rs [hunk 9]
```diff
@@ -1316,11 +1442,10 @@ pub fn expand_preparsed_format_args(
         }
 
         diag.emit();
-    } else if cx.invalid_refs.is_empty() && !named_arguments.is_empty() {
+    } else if cx.invalid_refs.is_empty() && cx.ecx.sess.err_count() == 0 {
```
Comment (compiler-errors) [inline compiler/rustc_builtin_macros/src/format.rs:1445]: Don't we suppress lints if we have errors? Can you describe what case(s) this prevents erroneous lints from being fired?

**Review by compiler-errors — COMMENTED** [review]
a few more nits, still trying to wrap my head around all the logic here haha

File: compiler/rustc_builtin_macros/src/format.rs (hunk 3 above)
Comment (PrestonFrom) [reply compiler/rustc_builtin_macros/src/format.rs]: Done!

**Comment by PrestonFrom** [comment]
@compiler-errors Thank you for the comments! I think I go them all. I also added a new method with comment on the logic behind how it determines when a lint should be emitted. If the logic is still not making sense, please let me know!

**Comment by compiler-errors** [comment]
Thanks, this looks good for now. rollup=never so it's easier to bisect later just in case we have more ICEs, though from the look of this code we probably shouldn't have more errors.

@bors r+ rollup=never

File: src/test/ui/macros/issue-98466.stderr [hunk 10]
```diff
@@ -2,80 +2,80 @@ warning: named argument `_x` is not used by name
   --> $DIR/issue-98466.rs:7:26
    |
 LL |     println!("_x is {}", _x = 5);
-   |                     --   ^^ this named argument is only referred to by position in formatting string
-   |                     |
-   |                     this formatting argument uses named argument `_x` by position
+   |                      -   ^^ this named argument is only referred to by position in formatting string
```
Comment (lqd) [inline src/test/ui/macros/issue-98466.stderr:5]: is the span change only underlining the closing `}` expected ?

Comment (PrestonFrom) [reply src/test/ui/macros/issue-98466.stderr:5]: @lqd
Basically yes, because that's where the named argument gets inserted. But now that you've commented on it, I think it should probably underline both.

I think I will have time to fix this today.

Comment (PrestonFrom) [reply src/test/ui/macros/issue-98466.stderr:5]: Took a little longer than I expected!
https://github.com/rust-lang/rust/pull/99958
