### PR TITLE
Suggest remove redundant `$()?` around `vis`

### LINKED ISSUE #139480: `$($v: vis)?` should get suggestion to become `$v: vis`
### Code

```Rust
macro_rules! make_static {
    ($($v: vis)? $name: ident) => {
        $($v)? static $name: u32 = 0;
    };
}
```

### Current output

```Shell
error: repetition matches empty token tree
 --> src/lib.rs:2:7
  |
2 |     ($($v: vis)? $name: ident) => {
  |       ^^^^^^^^^
```

### Desired output

```Shell
error: repetition matches empty token tree
 --> src/lib.rs:2:7
  |
2 |     ($($v: vis)? $name: ident) => {
  |       ^^^^^^^^^
note: a `vis` fragment can already be empty
help: remove the `$(` and `)?`
```

### Rationale and extra context

The current error is not very helpful and had be confused for quite some time.
@rustbot label D-terse

### Other cases

```Rust

```

### Rust Version

```Shell
1.88.0-nightly

(2025-04-06 2fa8b11f0933dae9b4e5)
```

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by makai410**
Resolves: #139480 .

### CODE REVIEW

File: tests/ui/macros/remove-repetition-issue-139480.rs [hunk 1]
```diff
@@ -0,0 +1,28 @@
...
+
+macro_rules! meow {
+    ($name: ident $($v: vis)?) => {
+    //~^ error: repetition matches empty token tree
+    };
+}
+
+macro_rules! gbc {
+    ($name: ident $/*
+        It's MyGO!!!!!
```
Comment (compiler-errors) [inline tests/ui/macros/remove-repetition-issue-139480.rs:15]: ?

Comment (compiler-errors) [reply tests/ui/macros/remove-repetition-issue-139480.rs:15]: Can you remove the unnecessary comments? It's a bit distracting

**Comment by fee1-dead** [comment]
wrong PR!!!
@bors r-

File: tests/ui/macros/remove-repetition-issue-139480.rs (hunk 1 above)
Comment (makai410) [reply tests/ui/macros/remove-repetition-issue-139480.rs:15]:
```suggestion
        this comment gets removed by the suggestion
```
Sorry about that. Would this version be better in your opinion?

Comment (compiler-errors) [reply tests/ui/macros/remove-repetition-issue-139480.rs]: That's much easier to understand, yes

**Review by compiler-errors — APPROVED** [review]
