### PR TITLE
Work around missing code coverage data causing llvm-cov failures

### LINKED ISSUE #93054: LLVM coverage regression in nightly-2022-01-15
Between nightly versions 2022-01-14 and 2022-01-15, [grcov](https://github.com/mozilla/grcov) 0.8.2 lost track of 82% of the coverage of [BonsaiDb](https://github.com/khonsulabs/bonsaidb) when using the LLVM coverage option (`-Zinstrument-coverage`).

Other projects of mine continue to have code coverage correctly measured. I'm not where to start narrowing this down, as I'm not getting any errors or warnings printed.

Here are the steps to get good code coverage reports out of 2022-01-14:

```bash
git clone https://github.com/khonsulabs/bonsaidb.git
cd bonsaidb

rustup toolchain install nightly-2022-01-14 --component llvm-tools-preview
LLVM_PROFILE_FILE=%m.profraw RUSTFLAGS="-Zinstrument-coverage" cargo +nightly-2022-01-14 test --workspace --all-features --all-targets
RUST_TOOLCHAIN=nightly-2022-01-14 grcov . --binary-path ./target/debug/ -s . -t html --branch --ignore-not-existing --llvm -o coverage/ --ignore "target/*" --ignore "xtask/*"
```

If you look at the report in the coverage folder, the html report will show >80% coverage. Now, test with the next nightly:

```bash
# Clean up files
find . -name "*.profraw" -exec rm \{\} \;
rm -rf **/*.bonsaidb

rustup toolchain install nightly-2022-01-15 --component llvm-tools-preview
cargo clean
LLVM_PROFILE_FILE=%m.profraw RUSTFLAGS="-Zinstrument-coverage" cargo +nightly-2022-01-15 test --workspace --all-features --all-targets
RUST_TOOLCHAIN=nightly-2022-01-15 grcov . --binary-path ./target/debug/ -s . -t html --branch --ignore-not-existing --llvm -o coverage/ --ignore "target/*" --ignore "xtask/*"
```

If you look at the report again, the html report now shows < 1% coverage. 

The quantity of profraw files are the same, and the sizes of the files are more or less equivalent. I'm not quite sure where to start narrowing this down since it's a unique issue to this project of mine -- but the only unique part I'm aware of is its size :sweat_smile:.

For now I'll pin our CI to the last working nightly. Thank you in advance for any suggestions or help!

### PR DESCRIPTION
**Pull request by wesleywiser**
If we do not add code coverage instrumentation to the `Body` of a
function, then when we go to generate the function record for it, we
won't write any data and this later causes llvm-cov to fail when
processing data for the entire coverage report.

I've identified two main cases where we do not currently add code
coverage instrumentation to the `Body` of a function:

  1. If the function has a single `BasicBlock` and it ends with a
     `TerminatorKind::Unreachable`.

  2. If the function is created using a proc macro of some kind.

For case 1, this is typically not important as this most often occurs as
a result of function definitions that take or return uninhabited
types. These kinds of functions, by definition, cannot even be called so
they logically should not be counted in code coverage statistics.

For case 2, I haven't looked into this very much but I've noticed while
testing this patch that (other than functions which are covered by case
1) the skipped function coverage debug message is occasionally triggered
in large crate graphs by functions generated from a proc macro. This may
have something to do with weird spans being generated by the proc macro
but this is just a guess.

I think it's reasonable to land this change since currently, we fail to
generate *any* results from llvm-cov when a function has no coverage
instrumentation applied to it. With this change, we get coverage data
for all functions other than the two cases discussed above.

Fixes #93054 which occurs because of uncallable functions which shouldn't
have code coverage anyway.

I will open an issue for missing code coverage of proc macro generated
functions and leave a link here once I have a more minimal repro.

r? @tmandry 
cc @richkadel

### CODE REVIEW

**Comment by wesleywiser** [comment]
Just FYI, I spent a good chunk of today trying a different approach to resolve this issue which was to identify functions that are uncallable and filter them out before we call `define_unused_fn` on them. That change ended up being much more complex, didn't do anything for proc macro generated functions and caused an incremental compilation ICE that I wasn't able to track down. 

Given those factors, this seemed like the better approach to me as we shouldn't be generating invalid (empty) `coverage_mapping_buffer` values anyway which is what leads to `llvm-cov` failing with the "Truncated coverage data" error.

File: compiler/rustc_codegen_llvm/src/coverageinfo/mapgen.rs [hunk 1]
```diff
@@ -76,10 +76,11 @@ pub fn finalize<'ll, 'tcx>(cx: &CodegenCx<'ll, 'tcx>) {
         let coverage_mapping_buffer = llvm::build_byte_buffer(|coverage_mapping_buffer| {
             mapgen.write_coverage_mapping(expressions, counter_regions, coverage_mapping_buffer);
         });
-        debug_assert!(
-            !coverage_mapping_buffer.is_empty(),
-            "Every `FunctionCoverage` should have at least one counter"
-        );
+
```
Comment (richkadel) [inline compiler/rustc_codegen_llvm/src/coverageinfo/mapgen.rs:79]: When we talked about this yesterday, I suggested we keep the assert (but as `assert!`, not `debug_assert!`), and change `add_unused_functions()` to check for no coverage before adding an unused function stub:

```rust
if !tcx.covered_code_regions(def_id).is_empty() { 
        cx.define_unused_fn(non_codegenned_def_id);
} 
```

Your change will still define unused functions that you are ultimately not going to include in the coverage map. That is wasteful at the least, and possibly exposes us to other issues we're not yet aware of.

Your change also tries to permit functions that have no coverage counters but are still "used".

So far I'm not aware that we've ever run into that situation. I feel like we should not permit it, but the `assert!` will catch it if it ever happens in the future, and we can deal with it properly if it does.

**Review by richkadel — CHANGES_REQUESTED** [review]

File: compiler/rustc_codegen_llvm/src/coverageinfo/mapgen.rs (hunk 1 above)
Comment (wesleywiser) [reply compiler/rustc_codegen_llvm/src/coverageinfo/mapgen.rs:81]: Ah, yeah you're right. I was thinking just in terms of the coverage mapping data but we really shouldn't be defining the functions at all if we're not going to use them in code coverage. I've pushed a commit that fixes that.

File: compiler/rustc_codegen_llvm/src/coverageinfo/mapgen.rs [hunk 2]
```diff
@@ -319,6 +325,18 @@ fn add_unused_functions<'ll, 'tcx>(cx: &CodegenCx<'ll, 'tcx>) {
             continue;
         }
 
+        // If this function hasn't been instrumented with code coverage for some reason, then skip
+        // it so we don't try to instantiate the function and related statics improperly (#93054).
+        let coverageinfo =
+            tcx.coverageinfo(InstanceDef::Item(WithOptConstParam::unknown(non_codegenned_def_id)));
+        if coverageinfo.num_counters == 1 && coverageinfo.num_expressions == 0 {
```
Comment (wesleywiser) [inline compiler/rustc_codegen_llvm/src/coverageinfo/mapgen.rs:332]: @richkadel I tried to use your suggestion of `!tcx.covered_code_regions(non_codegenned_def_id).is_empty()` here but that doesn't actually catch the functions which triggers the assert. I had to use this check instead. Does that seem reasonable to you?

Comment (richkadel) [reply compiler/rustc_codegen_llvm/src/coverageinfo/mapgen.rs:332]: My bad. I forgot how complex it is to compute `counter_regions` passed into `write_coverage_mapping`.

In that case, I think your original solution is simpler. Sorry. 

Can I suggest, though, that you change it to (abbreviated):

```
if coverage_mapping_buffer.is_empty() {
  if function_coverage.is_used()) {
    bug!("used functions should have coverage, but {} had none", function_name);
  } else {
    debug!("unused function {} had no coverage", function_name);
  }
}

Comment (wesleywiser) [reply compiler/rustc_codegen_llvm/src/coverageinfo/mapgen.rs]: Ok, done!

**Review by richkadel — APPROVED** [review]
Looks good to me.

I guess we still have the side effect of adding the unused function stubs without including them in coverage; but as I said, the process for computing the counter_regions is somewhat complex, and not easily cacheable, so I think this should work for now.

I'll file and issue to see if I can improve it so we can avoid adding the function.

Thanks Wesley!
