### PR TITLE
Reorder nesting scopes and declare bindings without drop schedule

### LINKED ISSUE #99228: ICE: broken mir with let-else, -Zvalidate-mir
### Code
`./src/test/ui/let-else/let-else-source-expr-nomove-pass.rs`
```Rust
// run-pass
// issue #89688

#![feature(let_else)]

fn example_let_else(value: Option<String>) {
    let Some(inner) = value else {
        println!("other: {:?}", value); // OK
        return;
    };
    println!("inner: {}", inner);
}

fn main() {
    example_let_else(Some("foo".into()));
    example_let_else(None);
}
```

### Meta

`rustc --version --verbose`:
```
rustc 1.64.0-nightly (87588a2af 2022-07-13)
binary: rustc
commit-hash: 87588a2afd9ca903366f0deaf84d805f34469384
commit-date: 2022-07-13
host: x86_64-unknown-linux-gnu
release: 1.64.0-nightly
LLVM version: 14.0.6
```

### Error output
`rustc ./src/test/ui/let-else/let-else-source-expr-nomove-pass.rs -Zvalidate-mir`
```
error: internal compiler error: no errors encountered even though `delay_span_bug` issued

error: internal compiler error: broken MIR in Item(WithOptConstParam { did: DefId(0:3 ~ let_else_source_expr_nomove_pass[ed50]::example_let_else), const_param_did: None }) (start of phase transition from Built) at bb13[0]:
                                use of local _2, which has no storage here
  --> ./src/test/ui/let-else/let-else-source-expr-nomove-pass.rs:12:1
   |
12 | }
   | ^
   |
   = note: delayed at compiler/rustc_const_eval/src/transform/validate.rs:129:36

error: internal compiler error: broken MIR in Item(WithOptConstParam { did: DefId(0:3 ~ let_else_source_expr_nomove_pass[ed50]::example_let_else), const_param_did: None }) (after pass CheckPackedRef) at bb13[0]:
                                use of local _2, which has no storage here
  --> ./src/test/ui/let-else/let-else-source-expr-nomove-pass.rs:12:1
   |
12 | }
   | ^
   |
   = note: delayed at compiler/rustc_const_eval/src/transform/validate.rs:129:36

error: internal compiler error: broken MIR in Item(WithOptConstParam { did: DefId(0:3 ~ let_else_source_expr_nomove_pass[ed50]::example_let_else), const_param_did: None }) (after pass CheckConstItemMutation) at bb13[0]:
                                use of local _2, which has no storage here
  --> ./src/test/ui/let-else/let-else-source-expr-nomove-pass.rs:12:1
   |
12 | }
   | ^
   |
   = note: delayed at compiler/rustc_const_eval/src/transform/validate.rs:129:36

error: internal compiler error: broken MIR in Item(WithOptConstParam { did: DefId(0:3 ~ let_else_source_expr_nomove_pass[ed50]::example_let_else), const_param_did: None }) (after pass FunctionItemReferences) at bb13[0]:
                                use of local _2, which has no storage here
  --> ./src/test/ui/let-else/let-else-source-expr-nomove-pass.rs:12:1
   |
12 | }
   | ^
   |
   = note: delayed at compiler/rustc_const_eval/src/transform/validate.rs:129:36

error: internal compiler error: broken MIR in Item(WithOptConstParam { did: DefId(0:3 ~ let_else_source_expr_nomove_pass[ed50]::example_let_else), const_param_did: None }) (after pass SimplifyCfg-initial) at bb6[10]:
                                use of local _2, which has no storage here
  --> ./src/test/ui/let-else/let-else-source-expr-nomove-pass.rs:12:1
   |
12 | }
   | ^
   |
   = note: delayed at compiler/rustc_const_eval/src/transform/validate.rs:129:36

error: internal compiler error: broken MIR in Item(WithOptConstParam { did: DefId(0:3 ~ let_else_source_expr_nomove_pass[ed50]::example_let_else), const_param_did: None }) (after pass SanityCheck) at bb6[10]:
                                use of local _2, which has no storage here
  --> ./src/test/ui/let-else/let-else-source-expr-nomove-pass.rs:12:1
   |
12 | }
   | ^
   |
   = note: delayed at compiler/rustc_const_eval/src/transform/validate.rs:129:36

error: internal compiler error: broken MIR in Item(WithOptConstParam { did: DefId(0:3 ~ let_else_source_expr_nomove_pass[ed50]::example_let_else), const_param_did: None }) (after pass PhaseChange-Const) at bb6[10]:
                                use of local _2, which has no storage here
  --> ./src/test/ui/let-else/let-else-source-expr-nomove-pass.rs:12:1
   |
12 | }
   | ^
   |
   = note: delayed at compiler/rustc_const_eval/src/transform/validate.rs:129:36

error: internal compiler error: broken MIR in Item(WithOptConstParam { did: DefId(0:3 ~ let_else_source_expr_nomove_pass[ed50]::example_let_else), const_param_did: None }) (end of phase transition to Const) at bb6[10]:
                                use of local _2, which has no storage here
  --> ./src/test/ui/let-else/let-else-source-expr-nomove-pass.rs:12:1
   |
12 | }
   | ^
   |
   = note: delayed at compiler/rustc_const_eval/src/transform/validate.rs:129:36

error: internal compiler error: broken MIR in Item(WithOptConstParam { did: DefId(0:3 ~ let_else_source_expr_nomove_pass[ed50]::example_let_else), const_param_did: None }) (start of phase transition from Const) at bb6[10]:
                                use of local _2, which has no storage here
  --> ./src/test/ui/let-else/let-else-source-expr-nomove-pass.rs:12:1
   |
12 | }
   | ^
   |
   = note: delayed at compiler/rustc_const_eval/src/transform/validate.rs:129:36

error: internal compiler error: broken MIR in Item(WithOptConstParam { did: DefId(0:3 ~ let_else_source_expr_nomove_pass[ed50]::example_let_else), const_param_did: None }) (after pass PromoteTemps) at bb6[9]:
                                use of local _2, which has no storage here
  --> ./src/test/ui/let-else/let-else-source-expr-nomove-pass.rs:12:1
   |
12 | }
   | ^
   |
   = note: delayed at compiler/rustc_const_eval/src/transform/validate.rs:129:36

error: internal compiler error: broken MIR in Item(WithOptConstParam { did: DefId(0:3 ~ let_else_source_expr_nomove_pass[ed50]::example_let_else), const_param_did: None }) (after pass SimplifyCfg-promote-consts) at bb6[9]:
                                use of local _2, which has no storage here
  --> ./src/test/ui/let-else/let-else-source-expr-nomove-pass.rs:12:1
   |
12 | }
   | ^
   |
   = note: delayed at compiler/rustc_const_eval/src/transform/validate.rs:129:36

error: internal compiler error: broken MIR in Item(WithOptConstParam { did: DefId(0:3 ~ let_else_source_expr_nomove_pass[ed50]::example_let_else), const_param_did: None }) (end of phase transition to ConstsPromoted) at bb6[9]:
                                use of local _2, which has no storage here
  --> ./src/test/ui/let-else/let-else-source-expr-nomove-pass.rs:12:1
   |
12 | }
   | ^
   |
   = note: delayed at compiler/rustc_const_eval/src/transform/validate.rs:129:36

error: internal compiler error: broken MIR in Item(WithOptConstParam { did: DefId(0:3 ~ let_else_source_expr_nomove_pass[ed50]::example_let_else), const_param_did: None }) (start of phase transition from ConstsPromoted) at bb6[9]:
                                use of local _2, which has no storage here
  --> ./src/test/ui/let-else/let-else-source-expr-nomove-pass.rs:12:1
   |
12 | }
   | ^
   |
   = note: delayed at compiler/rustc_const_eval/src/transform/validate.rs:129:36

error: internal compiler error: broken MIR in Item(WithOptConstParam { did: DefId(0:3 ~ let_else_source_expr_nomove_pass[ed50]::example_let_else), const_param_did: None }) (after pass RemoveFalseEdges) at bb6[9]:
                                use of local _2, which has no storage here
  --> ./src/test/ui/let-else/let-else-source-expr-nomove-pass.rs:12:1
   |
12 | }
   | ^
   |
   = note: delayed at compiler/rustc_const_eval/src/transform/validate.rs:129:36

error: internal compiler error: broken MIR in Item(WithOptConstParam { did: DefId(0:3 ~ let_else_source_expr_nomove_pass[ed50]::example_let_else), const_param_did: None }) (after pass SimplifyConstCondition-initial) at bb6[9]:
                                use of local _2, which has no storage here
  --> ./src/test/ui/let-else/let-else-source-expr-nomove-pass.rs:12:1
   |
12 | }
   | ^
   |
   = note: delayed at compiler/rustc_const_eval/src/transform/validate.rs:129:36

error: internal compiler error: broken MIR in Item(WithOptConstParam { did: DefId(0:3 ~ let_else_source_expr_nomove_pass[ed50]::example_let_else), const_param_did: None }) (after pass RemoveNoopLandingPads) at bb6[9]:
                                use of local _2, which has no storage here
  --> ./src/test/ui/let-else/let-else-source-expr-nomove-pass.rs:12:1
   |
12 | }
   | ^
   |
   = note: delayed at compiler/rustc_const_eval/src/transform/validate.rs:129:36

error: internal compiler error: broken MIR in Item(WithOptConstParam { did: DefId(0:3 ~ let_else_source_expr_nomove_pass[ed50]::example_let_else), const_param_did: None }) (after pass CleanupNonCodegenStatements) at bb6[9]:
                                use of local _2, which has no storage here
  --> ./src/test/ui/let-else/let-else-source-expr-nomove-pass.rs:12:1
   |
12 | }
   | ^
   |
   = note: delayed at compiler/rustc_const_eval/src/transform/validate.rs:129:36

error: internal compiler error: broken MIR in Item(WithOptConstParam { did: DefId(0:3 ~ let_else_source_expr_nomove_pass[ed50]::example_let_else), const_param_did: None }) (after pass SimplifyCfg-early-opt) at bb5[9]:
                                use of local _2, which has no storage here
  --> ./src/test/ui/let-else/let-else-source-expr-nomove-pass.rs:12:1
   |
12 | }
   | ^
   |
   = note: delayed at compiler/rustc_const_eval/src/transform/validate.rs:129:36

error: internal compiler error: broken MIR in Item(WithOptConstParam { did: DefId(0:3 ~ let_else_source_expr_nomove_pass[ed50]::example_let_else), const_param_did: None }) (after pass Derefer) at bb5[9]:
                                use of local _2, which has no storage here
  --> ./src/test/ui/let-else/let-else-source-expr-nomove-pass.rs:12:1
   |
12 | }
   | ^
   |
   = note: delayed at compiler/rustc_const_eval/src/transform/validate.rs:129:36

error: internal compiler error: broken MIR in Item(WithOptConstParam { did: DefId(0:3 ~ let_else_source_expr_nomove_pass[ed50]::example_let_else), const_param_did: None }) (after pass AddCallGuards) at bb5[9]:
                                use of local _2, which has no storage here
  --> ./src/test/ui/let-else/let-else-source-expr-nomove-pass.rs:12:1
   |
12 | }
   | ^
   |
   = note: delayed at compiler/rustc_const_eval/src/transform/validate.rs:129:36
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```

thread 'rustc' panicked at 'Box<dyn Any>', compiler/rustc_errors/src/lib.rs:1425:13
stack backtrace:
   0:     0x7f3ab90a2850 - std::backtrace_rs::backtrace::libunwind::trace::h546e34b136647819
                               at /rustc/87588a2afd9ca903366f0deaf84d805f34469384/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   1:     0x7f3ab90a2850 - std::backtrace_rs::backtrace::trace_unsynchronized::h76e576fe0a1ec65e
                               at /rustc/87588a2afd9ca903366f0deaf84d805f34469384/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7f3ab90a2850 - std::sys_common::backtrace::_print_fmt::h3489fbb9d5d01094
                               at /rustc/87588a2afd9ca903366f0deaf84d805f34469384/library/std/src/sys_common/backtrace.rs:66:5
   3:     0x7f3ab90a2850 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h401cfc97a3c2f247
                               at /rustc/87588a2afd9ca903366f0deaf84d805f34469384/library/std/src/sys_common/backtrace.rs:45:22
   4:     0x7f3ab90fbe2c - core::fmt::write::h327c921ac5532dc9
                               at /rustc/87588a2afd9ca903366f0deaf84d805f34469384/library/core/src/fmt/mod.rs:1198:17
   5:     0x7f3ab9093e15 - std::io::Write::write_fmt::h334c1fe5d85b41a9
                               at /rustc/87588a2afd9ca903366f0deaf84d805f34469384/library/std/src/io/mod.rs:1672:15
   6:     0x7f3ab90a54e1 - std::sys_common::backtrace::_print::hddc5656bc817cc55
                               at /rustc/87588a2afd9ca903366f0deaf84d805f34469384/library/std/src/sys_common/backtrace.rs:48:5
   7:     0x7f3ab90a54e1 - std::sys_common::backtrace::print::h46adcb0dcb6fbe81
                               at /rustc/87588a2afd9ca903366f0deaf84d805f34469384/library/std/src/sys_common/backtrace.rs:35:9
   8:     0x7f3ab90a54e1 - std::panicking::default_hook::{{closure}}::h7e55301ce91fa17d
                               at /rustc/87588a2afd9ca903366f0deaf84d805f34469384/library/std/src/panicking.rs:295:22
   9:     0x7f3ab90a51b3 - std::panicking::default_hook::he24b412fa8dea167
                               at /rustc/87588a2afd9ca903366f0deaf84d805f34469384/library/std/src/panicking.rs:314:9
  10:     0x7f3ab9947e04 - rustc_driver[24990f24c5f9557a]::DEFAULT_HOOK::{closure#0}::{closure#0}
  11:     0x7f3ab90a5cb6 - std::panicking::rust_panic_with_hook::hd6be56b55800f278
                               at /rustc/87588a2afd9ca903366f0deaf84d805f34469384/library/std/src/panicking.rs:702:17
  12:     0x7f3abaaef0d1 - std[66dc708de7974585]::panicking::begin_panic::<rustc_errors[7a9b9cc96f052d83]::ExplicitBug>::{closure#0}
  13:     0x7f3abaaef046 - std[66dc708de7974585]::sys_common::backtrace::__rust_end_short_backtrace::<std[66dc708de7974585]::panicking::begin_panic<rustc_errors[7a9b9cc96f052d83]::ExplicitBug>::{closure#0}, !>
  14:     0x7f3abaae82f6 - std[66dc708de7974585]::panicking::begin_panic::<rustc_errors[7a9b9cc96f052d83]::ExplicitBug>
  15:     0x7f3abaaeb326 - std[66dc708de7974585]::panic::panic_any::<rustc_errors[7a9b9cc96f052d83]::ExplicitBug>
  16:     0x7f3abc3d9b93 - <rustc_errors[7a9b9cc96f052d83]::HandlerInner as core[734affb1a3eaf053]::ops::drop::Drop>::drop
  17:     0x7f3abbb0331b - core[734affb1a3eaf053]::ptr::drop_in_place::<rustc_session[214423f9b1c42db1]::parse::ParseSess>
  18:     0x7f3abbb05ed3 - <alloc[66d1c5d1fabcc843]::rc::Rc<rustc_session[214423f9b1c42db1]::session::Session> as core[734affb1a3eaf053]::ops::drop::Drop>::drop
  19:     0x7f3abbae88bd - core[734affb1a3eaf053]::ptr::drop_in_place::<rustc_interface[d9e16a24b5464548]::interface::Compiler>
  20:     0x7f3abbae6944 - rustc_span[b8cb56592c4d9b67]::with_source_map::<core[734affb1a3eaf053]::result::Result<(), rustc_errors[7a9b9cc96f052d83]::ErrorGuaranteed>, rustc_interface[d9e16a24b5464548]::interface::create_compiler_and_run<core[734affb1a3eaf053]::result::Result<(), rustc_errors[7a9b9cc96f052d83]::ErrorGuaranteed>, rustc_driver[24990f24c5f9557a]::run_compiler::{closure#1}>::{closure#1}>
  21:     0x7f3abbb02880 - rustc_interface[d9e16a24b5464548]::interface::create_compiler_and_run::<core[734affb1a3eaf053]::result::Result<(), rustc_errors[7a9b9cc96f052d83]::ErrorGuaranteed>, rustc_driver[24990f24c5f9557a]::run_compiler::{closure#1}>
  22:     0x7f3abbb16a02 - <scoped_tls[93927b52d599628f]::ScopedKey<rustc_span[b8cb56592c4d9b67]::SessionGlobals>>::set::<rustc_interface[d9e16a24b5464548]::interface::run_compiler<core[734affb1a3eaf053]::result::Result<(), rustc_errors[7a9b9cc96f052d83]::ErrorGuaranteed>, rustc_driver[24990f24c5f9557a]::run_compiler::{closure#1}>::{closure#0}, core[734affb1a3eaf053]::result::Result<(), rustc_errors[7a9b9cc96f052d83]::ErrorGuaranteed>>
  23:     0x7f3abbae8cff - std[66dc708de7974585]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[d9e16a24b5464548]::util::run_in_thread_pool_with_globals<rustc_interface[d9e16a24b5464548]::interface::run_compiler<core[734affb1a3eaf053]::result::Result<(), rustc_errors[7a9b9cc96f052d83]::ErrorGuaranteed>, rustc_driver[24990f24c5f9557a]::run_compiler::{closure#1}>::{closure#0}, core[734affb1a3eaf053]::result::Result<(), rustc_errors[7a9b9cc96f052d83]::ErrorGuaranteed>>::{closure#0}, core[734affb1a3eaf053]::result::Result<(), rustc_errors[7a9b9cc96f052d83]::ErrorGuaranteed>>
  24:     0x7f3abbb02cd9 - <<std[66dc708de7974585]::thread::Builder>::spawn_unchecked_<rustc_interface[d9e16a24b5464548]::util::run_in_thread_pool_with_globals<rustc_interface[d9e16a24b5464548]::interface::run_compiler<core[734affb1a3eaf053]::result::Result<(), rustc_errors[7a9b9cc96f052d83]::ErrorGuaranteed>, rustc_driver[24990f24c5f9557a]::run_compiler::{closure#1}>::{closure#0}, core[734affb1a3eaf053]::result::Result<(), rustc_errors[7a9b9cc96f052d83]::ErrorGuaranteed>>::{closure#0}, core[734affb1a3eaf053]::result::Result<(), rustc_errors[7a9b9cc96f052d83]::ErrorGuaranteed>>::{closure#1} as core[734affb1a3eaf053]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  25:     0x7f3ab90af703 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h332a3f23c5b3d8bc
                               at /rustc/87588a2afd9ca903366f0deaf84d805f34469384/library/alloc/src/boxed.rs:1934:9
  26:     0x7f3ab90af703 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h33b3da7f4496df00
                               at /rustc/87588a2afd9ca903366f0deaf84d805f34469384/library/alloc/src/boxed.rs:1934:9
  27:     0x7f3ab90af703 - std::sys::unix::thread::Thread::new::thread_start::hf48274d01b2ded65
                               at /rustc/87588a2afd9ca903366f0deaf84d805f34469384/library/std/src/sys/unix/thread.rs:108:17
  28:     0x7f3ab8e8054d - <unknown>
  29:     0x7f3ab8f05874 - clone
  30:                0x0 - <unknown>

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.64.0-nightly (87588a2af 2022-07-13) running on x86_64-unknown-linux-gnu

note: compiler flags: -Z validate-mir

query stack during panic:
end of query stack
```

</p>
</details>

### LINKED ISSUE #99975: Internal Compiler Error: Broken MIR in Item(...) With `let_else` Usage
### Code

```Rust
// https://github.com/HTG-YT/HarTex-rust-discord-bot/blob/nightly/discord-frontend/loadbal/bin/requests.rs
```

### Meta

`rustc --version --verbose`:
```
rustc 1.64.0-nightly (0f4bcadb4 2022-07-30)
binary: rustc
commit-hash: 0f4bcadb46006bc484dad85616b484f93879ca4e
commit-date: 2022-07-30
host: x86_64-pc-windows-msvc
release: 1.64.0-nightly
LLVM version: 14.0.6
```

### Error output

```
error: internal compiler error: no errors encountered even though `delay_span_bug` issued

error: internal compiler error: broken MIR in Item(WithOptConstParam { did: DefId(0:63 ~ loadbal[4911]::requests::handle_request::{closure#0}), const_param_did: None }) (end of phase transition to Optimized) at bb440[0]:
                                use of local _137, which has no storage here
  --> loadbal\bin\requests.rs:51:6
   |
51 |     };
   |      ^
   |
   = note: delayed at compiler\rustc_const_eval\src\transform\validate.rs:129:36

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.64.0-nightly (0f4bcadb4 2022-07-30) running on x86_64-pc-windows-msvc

note: compiler flags: --crate-type bin -C opt-level=3 -C embed-bitcode=no -C linker=rust-lld

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
error: could not compile `loadbal`
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
thread 'rustc' panicked at 'Box<dyn Any>', compiler\rustc_errors\src\lib.rs:1426:13
stack backtrace:
   0:     0x7ff8197a9f0f - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h4bb26926f73ff06f
   1:     0x7ff8197e581a - core::fmt::write::h0bf51c604bae69f0
   2:     0x7ff81979cc0a - <std::io::IoSliceMut as core::fmt::Debug>::fmt::h4afc997ba7d9bee5
   3:     0x7ff8197ad90b - std::panicking::default_hook::h551b08bc312fd345
   4:     0x7ff8197ad537 - std::panicking::default_hook::h551b08bc312fd345
   5:     0x7ff810d8d5a1 - <rustc_session[f5461e5ef6bca036]::options::WasiExecModel as rustc_session[f5461e5ef6bca036]::config::dep_tracking::DepTrackingHash>::hash
   6:     0x7ff8197ae2ec - std::panicking::rust_panic_with_hook::h261126bd899705d1
   7:     0x7ff813008f23 - <rustc_errors[f29bddad0e66874]::annotate_snippet_emitter_writer::AnnotateSnippetEmitterWriter>::ui_testing
   8:     0x7ff813008cc9 - <rustc_errors[f29bddad0e66874]::annotate_snippet_emitter_writer::AnnotateSnippetEmitterWriter>::ui_testing
   9:     0x7ff812ffe439 - <rustc_errors[f29bddad0e66874]::emitter::FileWithAnnotatedLines as core[ca4609741b1b5f3a]::fmt::Debug>::fmt
  10:     0x7ff812ff27f9 - <rustc_feature[e558fdc666ba5bc6]::builtin_attrs::AttributeType as core[ca4609741b1b5f3a]::fmt::Debug>::fmt
  11:     0x7ff80f5f268d - <rustc_errors[f29bddad0e66874]::HandlerInner as core[ca4609741b1b5f3a]::ops::drop::Drop>::drop
  12:     0x7ff80e728b0b - <rustc_middle[a33c72cff0257ad9]::ty::SymbolName as core[ca4609741b1b5f3a]::fmt::Display>::fmt
  13:     0x7ff80e72bb6f - <rustc_middle[a33c72cff0257ad9]::ty::SymbolName as core[ca4609741b1b5f3a]::fmt::Display>::fmt
  14:     0x7ff80e71ac9d - <unknown>
  15:     0x7ff80e7073a7 - <unknown>
  16:     0x7ff80e73e7a7 - rustc_driver[5ebc3829ae83a8ca]::args::arg_expand_all
  17:     0x7ff80e727ca9 - <unknown>
  18:     0x7ff80e72d45d - <rustc_middle[a33c72cff0257ad9]::ty::SymbolName as core[ca4609741b1b5f3a]::fmt::Display>::fmt
  19:     0x7ff8197bf3bc - std::sys::windows::thread::Thread::new::h38ada2124ce340db
  20:     0x7ff8b2a154e0 - BaseThreadInitThunk
  21:     0x7ff8b366485b - RtlUserThreadStart
```

</p>
</details>

### PR DESCRIPTION
**Pull request by dingxiangfei2009**
Fix #99228 
Fix #99975 

Storages are previously not declared before entering the `else` block of a `let .. else` statement. However, when breaking out of the pattern matching into the `else` block, those storages are recorded as scheduled for drops. This is not expected.

This MR fixes this issue by not scheduling the drops for those storages.

cc @est31

### CODE REVIEW

**Comment by est31** [comment]
The test for #99228 is good, but it should also have a test for #99975. Can you add a test with the file name `src/test/ui/let-else/issue-99975.rs` with the content from [my comment](https://github.com/rust-lang/rust/issues/99975#issuecomment-1231933741) in addition to `// compile-flags: -C opt-level=3` at the top of the file?

**Comment by dingxiangfei2009** [comment]
Right. A test is added for that issue now.

**Comment by est31** [comment]
@dingxiangfei2009 thanks! Looks good from the tests point of view now. For the implementation, I can't comment much on that.

**Comment by dingxiangfei2009** [comment]
@est31 I see. Which reviewer do you think has the capacity to review this work at the moment? Hopefully this is not blocking the stabilisation effort.

**Comment by est31** [comment]
Yes it is blocking stabilization. Depending on how quickly this PR gets merged it depends whether `let else` makes it into 1.65 or 1.66. Generally I like let else stable as quickly as possible, but one release give or take won't be the end of it, and rushing things is usually not worth it (little nudges are fine but only up till a limit, you shouldn't stress people or stuff). The train model was designed precisely to prevent such rushing/pressure.

For the reviewers, you might try @oli-obk who has approved your earlier let else PRs but according to their github activity, they don't seem to work on weekends, so a review will probably only happen on monday. The current reviewer `jackh726` is actually available as well, they have approved another PR 17 hours ago, but maybe it's not their area of expertise, idk.

**Comment by jackh726** [comment]
Yeah, not really my area of expertise, but I'll try to review this over the weekend.

File: compiler/rustc_mir_build/src/build/block.rs [hunk 1]
```diff
@@ -109,13 +109,102 @@ impl<'a, 'tcx> Builder<'a, 'tcx> {
...
                     );
                 }
+                StmtKind::Let {
+                    remainder_scope,
+                    init_scope,
+                    pattern,
+                    initializer: Some(initializer),
+                    lint_level,
+                    else_block: Some(else_block),
+                } => {
```
Comment (jackh726) [inline compiler/rustc_mir_build/src/build/block.rs:119]: It honestly would be helpful to either have a test with mir output that covers this, or an example with the expected mir output in comments here.

File: src/test/ui/async-await/async-await-let-else.stderr [hunk 2]
```diff
@@ -35,7 +35,8 @@ LL |         bar2(Rc::new(())).await
    |              |
    |              has type `Rc<()>` which is not `Send`
 LL |     };
-   |      - `Rc::new(())` is later dropped here
+LL | }
+   | - `Rc::new(())` is later dropped here
```
Comment (jackh726) [inline src/test/ui/async-await/async-await-let-else.stderr:39]: This seems weird to me. I would expect that `Rc::new(())` would get dropped at the end of the else block, not the end of the function?

Comment (dingxiangfei2009) [reply src/test/ui/async-await/async-await-let-else.stderr:39]: Sounds right. Indeed this is not expected as `Rc::new(())` should be a temporary value and its lifetime terminates at the end of the `else` block.

`else` block should be marked as enclosed in a terminating scope. This should fix this bug.

Comment (dingxiangfei2009) [reply src/test/ui/async-await/async-await-let-else.stderr]: Okay, now the temporaries are properly contained within the `else` block now.

File: compiler/rustc_mir_build/src/build/block.rs (hunk 1 above)
Comment (dingxiangfei2009) [reply compiler/rustc_mir_build/src/build/block.rs:119]: Let me try both. :smile:

Comment (dingxiangfei2009) [reply compiler/rustc_mir_build/src/build/block.rs:119]: Speeking too soon. It seems not possible to dump MIR in `ui` tests yet. I have added explanatory comments here instead.

Comment (est31) [reply compiler/rustc_mir_build/src/build/block.rs:119]: There is a list of MIR based tests in `src/test/mir-opt`. Despite the name of the directory, not all are about optimization. You can check out `src/test/mir-opt/storage_ranges.rs` for an example that just checks the generated MIR. It is also explained [here](https://rustc-dev-guide.rust-lang.org/tests/compiletest.html#mir-opt-tests).

**Review by jackh726 — APPROVED** [review]
Beautiful diagram :)

**Comment by dingxiangfei2009** [comment]
@jackh726 Rebased to resolve merge conflicts.

**Comment by jackh726** [comment]
It's [No Tools Breakage Week](https://forge.rust-lang.org/#no-tools-breakage-week) and this seems to have broken miri. So likely unlikely we can get a fix for miri *fast*, we'll need to revert this for now.

**Comment by jackh726** [comment]
@Mark-Simulacrum can you confirm the above?

**Comment by est31** [comment]
@jackh726 miri is a nightly only tool, no? And according to your link they are exempt?

**Comment by jackh726** [comment]
I'm not sure, maybe!

**Comment by saethlin** [comment]
This definitely breaks Miri. But the _way_ it breaks Miri is strange to me. Miri now reports this on any program:
```
error: Undefined Behavior: StorageLive on a local that was already live
    --> /home/ben/.rustup/toolchains/miri/lib/rustlib/src/rust/library/std/src/thread/mod.rs:1058:30
     |
1058 |                     let Some(id) = last.checked_add(1) else {
     |                              ^^ StorageLive on a local that was already live
     |
     = help: this indicates a bug in the program: it performed an invalid operation, and caused Undefined Behavior
     = help: see https://doc.rust-lang.org/nightly/reference/behavior-considered-undefined.html for further information
     = note: BACKTRACE:
     = note: inside `std::thread::ThreadId::new` at /home/ben/.rustup/toolchains/miri/lib/rustlib/src/rust/library/std/src/thread/mod.rs:1058:30
     = note: inside `std::thread::Thread::new` at /home/ben/.rustup/toolchains/miri/lib/rustlib/src/rust/library/std/src/thread/mod.rs:1159:43
     = note: inside `std::rt::init` at /home/ben/.rustup/toolchains/miri/lib/rustlib/src/rust/library/std/src/rt.rs:104:22
     = note: inside closure at /home/ben/.rustup/toolchains/miri/lib/rustlib/src/rust/library/std/src/rt.rs:147:42
     = note: inside `std::panicking::try::do_call::<[closure@std::rt::lang_start_internal::{closure#1}], ()>` at /home/ben/.rustup/toolchains/miri/lib/rustlib/src/rust/library/std/src/panicking.rs:492:40
     = note: inside `std::panicking::try::<(), [closure@std::rt::lang_start_internal::{closure#1}]>` at /home/ben/.rustup/toolchains/miri/lib/rustlib/src/rust/library/std/src/panicking.rs:456:19
     = note: inside `std::panic::catch_unwind::<[closure@std::rt::lang_start_internal::{closure#1}], ()>` at /home/ben/.rustup/toolchains/miri/lib/rustlib/src/rust/library/std/src/panic.rs:137:14
     = note: inside `std::rt::lang_start_internal` at /home/ben/.rustup/toolchains/miri/lib/rustlib/src/rust/library/std/src/rt.rs:147:5
     = note: inside `std::rt::lang_start::<()>` at /home/ben/.rustup/toolchains/miri/lib/rustlib/src/rust/library/std/src/rt.rs:165:17

error: aborting due to previous error
```

**Comment by est31** [comment]
Hmm that's interesting. I hope that it's miri being wrong and it's not UB...

**Comment by saethlin** [comment]
I'm pretty sure this is UB. Consider this program:
```rust
#![feature(let_else)]
fn main() {
    let x: Option<u8> = Some(1);
    let Some(y) = x else {
        panic!();
    };
}
```
After this PR, it compiles to this MIR:
```
fn main() -> () {
    let mut _0: ();                      // return place in scope 0 at main.rs:2:11: 2:11
    let _1: std::option::Option<u8>;     // in scope 0 at main.rs:3:9: 3:10
    let mut _2: !;                       // in scope 0 at main.rs:4:26: 6:6
    let _3: ();                          // in scope 0 at /home/ben/rust-master/library/std/src/panic.rs:19:9: 19:50
    let mut _4: !;                       // in scope 0 at /home/ben/rust-master/library/std/src/panic.rs:19:9: 19:50
    let mut _6: isize;                   // in scope 0 at main.rs:4:9: 4:16
    scope 1 {
        debug x => _1;                   // in scope 1 at main.rs:3:9: 3:10
        let _5: u8;                      // in scope 1 at main.rs:4:14: 4:15
        scope 2 {
            debug y => _5;               // in scope 2 at main.rs:4:14: 4:15
        }
    }

    bb0: {
        StorageLive(_1);                 // scope 0 at main.rs:3:9: 3:10
        Deinit(_1);                      // scope 0 at main.rs:3:25: 3:32
        ((_1 as Some).0: u8) = const 1_u8; // scope 0 at main.rs:3:25: 3:32
        discriminant(_1) = 1;            // scope 0 at main.rs:3:25: 3:32
        StorageLive(_5);                 // scope 1 at main.rs:4:14: 4:15
        _6 = discriminant(_1);           // scope 1 at main.rs:4:19: 4:20
        switchInt(move _6) -> [1_isize: bb1, otherwise: bb2]; // scope 1 at main.rs:4:9: 4:16
    }

    bb1: {
        StorageLive(_5);                 // scope 1 at main.rs:4:14: 4:15
        _5 = ((_1 as Some).0: u8);       // scope 1 at main.rs:4:14: 4:15
        _0 = const ();                   // scope 0 at main.rs:2:11: 7:2
        StorageDead(_5);                 // scope 1 at main.rs:7:1: 7:2
        StorageDead(_1);                 // scope 0 at main.rs:7:1: 7:2
        return;                          // scope 0 at main.rs:7:2: 7:2
    }

    bb2: {
        StorageDead(_5);                 // scope 1 at main.rs:7:1: 7:2
        StorageLive(_3);                 // scope 1 at /home/ben/rust-master/library/std/src/panic.rs:18:12: 20:6
        StorageLive(_4);                 // scope 1 at /home/ben/rust-master/library/std/src/panic.rs:19:9: 19:50
        _4 = begin_panic::<&str>(const "explicit panic"); // scope 1 at /home/ben/rust-master/library/std/src/panic.rs:19:9: 19:50
                                         // mir::Constant
                                         // + span: /home/ben/rust-master/library/std/src/panic.rs:19:9: 19:32
                                         // + literal: Const { ty: fn(&str) -> ! {begin_panic::<&str>}, val: Value(<ZST>) }
                                         // mir::Constant
                                         // + span: /home/ben/rust-master/library/std/src/panic.rs:19:33: 19:49
                                         // + literal: Const { ty: &str, val: Value(Slice(..)) }
    }
}
```
If we branch from `bb0` to `bb1`, we `StorageLive(_5)` twice, and that's UB.

**Comment by est31** [comment]
Mhh yeah that's convincing.

**Comment by thomcc** [comment]
Someone should probably cut a PR reverting this.

**Comment by est31** [comment]
I would revert only after there has been a more thorough look on the problem. Maybe the fix is simple. Such a simple fix can then be backported to beta. The revert, if needed, can also easily be backported.

**Comment by dingxiangfei2009** [comment]
@est31 Ah okay, I did not know that we cannot declare storages live twice. I have one idea, but it needs to touch the `declare_bindings`. I am taking a look.

**Comment by RalfJung** [comment]
>  I did not know that we cannot declare storages live twice.

See https://doc.rust-lang.org/nightly/nightly-rustc/rustc_middle/mir/enum.StatementKind.html#variant.StorageLive for more details, and https://github.com/rust-lang/rust/issues/99160 for further discussion.
