### PR TITLE
Parser: Recover error from named params while parse_path

### LINKED ISSUE #140169: `Fn(a: u8)` should get a clear diagnostic
### Code

```Rust
fn f(_: impl Fn(a: u8)) {}
```

### Current output

```Shell
error: expected one of `!`, `(`, `)`, `+`, `,`, `::`, or `<`, found `:`
 --> src/lib.rs:1:18
  |
1 | fn f(_: impl Fn(a: u8)) {}
  |                  ^ expected one of 7 possible tokens
```

### Desired output

```Shell
error: `Fn`-trait syntax does not allow named arguments
```

### Rationale and extra context

`fn f(_: fn(a: u8)) {}` is valid syntax, so the difference should get better diagnostics

### Other cases

```Rust

```

### Rust Version

```Shell
rustc 1.88.0-nightly (d6c1e454a 2025-04-21)
binary: rustc
commit-hash: d6c1e454aa8af5e7e59fbf5c4e7d3128d2f99582
commit-date: 2025-04-21
host: x86_64-unknown-linux-gnu
release: 1.88.0-nightly
LLVM version: 20.1.2
```

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by xizheyin**
Fixes #140169

I added test to the first commit and the second added the code and changes to test.

r? @petrochenkov

### CODE REVIEW

**Review by compiler-errors — CHANGES_REQUESTED** [review]

File: compiler/rustc_parse/src/parser/path.rs [hunk 1]
```diff
@@ -396,8 +396,21 @@ impl<'a> Parser<'a> {
...
+                                dcx.emit_err(FnPathFoundNamedParams {
+                                    named_param_span: param.pat.span,
+                                });
+                            }
+                            param.map(|param| param.ty)
+                        } else {
+                            p.parse_ty()
+                        }
+                    }) {
+                        Ok((output, trailing)) => (output, trailing),
```
Comment (xizheyin) [inline compiler/rustc_parse/src/parser/path.rs:413]: Now, I used parse_param_general instead of the original parse_ty, and report errors when encountering a named paramter. It seems to make sense.

**Review by xizheyin — COMMENTED** [review]
@rustbot ready

File: compiler/rustc_parse/src/parser/ty.rs [hunk 2]
```diff
@@ -1268,6 +1270,59 @@ impl<'a> Parser<'a> {
         }
     }
 
+    /// Recover Fn(usize) from Fn(x: usize)
```
[the remark this answers is not in the document]
Comment (xizheyin) [reply compiler/rustc_parse/src/parser/ty.rs]: I was going to add a patch without changing the original logic, but it seems that this introduces unnecessary overhead, equivalent to parsing twice. I changed the code as you suggested and it seems the original problem disappeared.

File: compiler/rustc_parse/messages.ftl [hunk 3]
```diff
@@ -702,6 +702,9 @@ parse_parenthesized_lifetime_suggestion = remove the parentheses
 parse_path_double_colon = path separator must be a double colon
     .suggestion = use a double colon instead
 
+parse_path_found_named_params = syntax does not allow named arguments
```
Comment (petrochenkov) [inline compiler/rustc_parse/messages.ftl:705]:
```suggestion
parse_path_found_named_params = `Trait(...)` syntax does not support named parameters
```

File: compiler/rustc_parse/messages.ftl [hunk 4]
```diff
@@ -702,6 +702,9 @@ parse_parenthesized_lifetime_suggestion = remove the parentheses
...
+    .suggestion = remove name of the param
```
Comment (petrochenkov) [inline compiler/rustc_parse/messages.ftl:706]:
```suggestion
    .suggestion = remove name of the parameter
```

File: compiler/rustc_parse/src/parser/path.rs [hunk 5]
```diff
@@ -396,8 +396,21 @@ impl<'a> Parser<'a> {
...
+                        if p.is_named_param() {
+                            let param = p.parse_param_general(|_| false, false);
+                            if let Ok(ref param) = param {
+                                dcx.emit_err(FnPathFoundNamedParams {
+                                    named_param_span: param.pat.span,
+                                });
+                            }
+                            param.map(|param| param.ty)
+                        } else {
+                            p.parse_ty()
```
Comment (petrochenkov) [inline compiler/rustc_parse/src/parser/path.rs:410]: I don't think this is necessary.
`parse_param_general` always does the right thing and produces a type inside the parsed parameter, we just need to report an error if the parameter contains a pattern or attributes in addition to the type.

Comment (petrochenkov) [reply compiler/rustc_parse/src/parser/path.rs:410]: >report an error if the parameter contains a pattern or attributes

Or C variadic (`...`).

Comment (xizheyin) [reply compiler/rustc_parse/src/parser/path.rs:410]: I tried but it introduced other regression error, for example
```
fn main() {
  foo::( //~ HELP: consider removing the `::` here to call the expression
    //~^ NOTE: while parsing this parenthesized list of type arguments starting
    bar(x, y, z),
    bar(x, y, z),
    bar(x, y, z),
    bar(x, y, z),
    bar(x, y, z),
    bar(x, y, z),
    bar(x, y, z),
    baz("test"), //~ ERROR: expected type, found `"test"`
    //~^ NOTE: expected type
  )
}
```
we parse all use `parse_param_general`, it reports
image
The problem occurs during the parsing of parameters, this may be another issue that PR needs to address. Do you have any suggestions? Should we merge the current version first, or improve it further?

File: tests/ui/fn/fn-trait-use-named-params-issue-140169.stderr [hunk 6]
```diff
@@ -0,0 +1,38 @@
...
+   |                      ^^^ help: remove c_variadic
+
+error: `Trait(...)` syntax does not support attributes in parameters
+  --> $DIR/fn-trait-use-named-params-issue-140169.rs:9:22
+   |
+LL | fn f6(_: impl Fn(u8, #[allow(unused_attributes)] u8)) {}
+   |                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: remove the attribute(s)
+
+error: aborting due to 6 previous errors
+
```
Comment (xizheyin) [inline tests/ui/fn/fn-trait-use-named-params-issue-140169.stderr:38]: I added `attribute` and `c_var` check.

File: compiler/rustc_parse/src/parser/item.rs [hunk 7]
```diff
@@ -2990,12 +2997,13 @@ impl<'a> Parser<'a> {
...
                     Err(err) if this.unmatched_angle_bracket_count > 0 => return Err(err),
-                    // Recover from attempting to parse the argument as a type without pattern.
-                    Err(err) => {
+                    Err(err) if recover_arg_parse => {
+                        // Recover from attempting to parse the argument as a type without pattern.
                         err.cancel();
                         this.restore_snapshot(parser_snapshot_before_ty);
                         this.recover_arg_parse()?
                     }
+                    Err(err) => return Err(err),
```
Comment (xizheyin) [inline compiler/rustc_parse/src/parser/item.rs:3006]: The problem arises when it automatically recovers to parsing a pattern when `is_named_param` and `is_named_required` both are false but can't be parsed to type.

I added a parameter `recover_arg_parse` to `parse_param_general` to control that. For our purposes, it doesn't need to error recovery to parsing as a pattern, but just `expect type`.

**Review by xizheyin — COMMENTED** [review]
@rustbot ready

File: compiler/rustc_parse/src/parser/path.rs [hunk 8]
```diff
@@ -396,8 +400,28 @@ impl<'a> Parser<'a> {
                         snapshot = Some(self.create_snapshot_for_diagnostic());
                     }
 
-                    let (inputs, _) = match self.parse_paren_comma_seq(|p| p.parse_ty()) {
-                        Ok(output) => output,
+                    let dcx = self.dcx();
+                    let (inputs, _) = match self.parse_paren_comma_seq(|p| {
```
Comment (petrochenkov) [inline compiler/rustc_parse/src/parser/path.rs:404]: Could you avoid placing a huge block of code into the `match` argument?

File: compiler/rustc_parse/src/parser/path.rs [hunk 9]
```diff
@@ -396,8 +400,28 @@ impl<'a> Parser<'a> {
...
+                        let param = p.parse_param_general(|_| false, false, false);
+                        if let Ok(ref param) = param {
```
Comment (petrochenkov) [inline compiler/rustc_parse/src/parser/path.rs:406]: This can be merged into the `map` below.

File: compiler/rustc_parse/src/parser/path.rs [hunk 10]
```diff
@@ -396,8 +400,28 @@ impl<'a> Parser<'a> {
...
+                            if !param.attrs.is_empty() {
+                                dcx.emit_err(PathFoundAttributeInParams {
+                                    span: param.attrs[0].span,
+                                });
+                            }
+                        }
+
+                        param.map(|param| param.ty)
+                    }) {
+                        Ok((output, trailing)) => (output, trailing),
```
Comment (petrochenkov) [inline compiler/rustc_parse/src/parser/path.rs:424]:
```suggestion
                        Ok(output) => output,
```
Unnecessary change.

File: compiler/rustc_parse/messages.ftl [hunk 11]
```diff
@@ -702,6 +702,16 @@ parse_parenthesized_lifetime_suggestion = remove the parentheses
...
 
+
+parse_path_found_attribute_in_params = `Trait(...)` syntax does not support attributes in parameters
+    .suggestion = remove the attribute(s)
+
+parse_path_found_c_variadic_params = `Trait(...)` syntax does not support c_variadic parameters
+    .suggestion = remove c_variadic
+
+parse_path_found_named_params = `Trait(...)` syntax does not support named parameters
+    .suggestion = remove name of the parameter
```
Comment (compiler-errors) [inline compiler/rustc_parse/messages.ftl:713]:
```suggestion
    .suggestion = remove the parameter name
```

File: compiler/rustc_parse/messages.ftl [hunk 12]
```diff
@@ -702,6 +702,16 @@ parse_parenthesized_lifetime_suggestion = remove the parentheses
 parse_path_double_colon = path separator must be a double colon
     .suggestion = use a double colon instead
 
+
+parse_path_found_attribute_in_params = `Trait(...)` syntax does not support attributes in parameters
+    .suggestion = remove the attribute(s)
+
+parse_path_found_c_variadic_params = `Trait(...)` syntax does not support c_variadic parameters
+    .suggestion = remove c_variadic
```
Comment (compiler-errors) [inline compiler/rustc_parse/messages.ftl:710]: remove the `...`

File: compiler/rustc_parse/messages.ftl [hunk 13]
```diff
@@ -702,6 +702,16 @@ parse_parenthesized_lifetime_suggestion = remove the parentheses
 parse_path_double_colon = path separator must be a double colon
     .suggestion = use a double colon instead
 
+
+parse_path_found_attribute_in_params = `Trait(...)` syntax does not support attributes in parameters
+    .suggestion = remove the attribute(s)
```
Comment (compiler-errors) [inline compiler/rustc_parse/messages.ftl:707]:
```suggestion
    .suggestion = remove the attributes
```

No need to use `(s)` here. I think keeping it plural is fine.

**Review by compiler-errors — CHANGES_REQUESTED** [review]

File: compiler/rustc_parse/src/parser/path.rs [hunk 14]
```diff
@@ -396,7 +400,31 @@ impl<'a> Parser<'a> {
                         snapshot = Some(self.create_snapshot_for_diagnostic());
                     }
 
-                    let (inputs, _) = match self.parse_paren_comma_seq(|p| p.parse_ty()) {
+                    let parse_type_params =
+                        |p: &mut Parser<'a>, dcx: &mut DiagCtxtHandle<'a>| -> PResult<'a, P<Ty>> {
```
Comment (petrochenkov) [inline compiler/rustc_parse/src/parser/path.rs:404]: Why using a closure, if it's only called once.

In https://github.com/rust-lang/rust/pull/140671#discussion_r2075434459 I meant just something like
```rust
let types = self.parse_paren_comma_seq(|p| {
    ......
});
let (inputs, _) = match types {
    ......
```

**Comment by petrochenkov** [comment]
Could you also squash commits after addressing https://github.com/rust-lang/rust/pull/140671#discussion_r2077328620?
@rustbot author

File: compiler/rustc_parse/src/parser/path.rs (hunk 14 above)
Comment (xizheyin) [reply compiler/rustc_parse/src/parser/path.rs:404]: Because there are too many things in the closure of `parse_paren_comma_seq`, I moved it outside for the sake of beauty. If this is not suitable, I'll readjust it.

Comment (petrochenkov) [reply compiler/rustc_parse/src/parser/path.rs:404]: But now those things are mostly just moved from one closure to another, I'd rather merge those two closures together.

**Comment by fmease** [comment]
Strictly speaking, this supposedly diagnostic-only PR represents a breaking change:

`dyn Fn(&self)` and `dyn Fn(&mut self)` for example used to be syntactically valid types. Now however, they get rejected with ``error: unexpected `self` parameter in function`` and `` `Trait(...)` syntax does not support named parameters ``.

However, it's not worth going back due to accepted [RFC 3955](https://github.com/rust-lang/rfcs/pull/3955) (CC https://github.com/rust-lang/rust/pull/158517, its impl).
