### PR TITLE
Properly restore snapshot when failing to recover parsing ternary

### LINKED ISSUE #117208: Bad recovery for `<expression> ? <statement> ;`
### Code

```Rust
pub fn foo() {
  let v = v?
  while let Ok(_) = v {};
}
```

### Current output

```Shell
error: expected one of `.`, `;`, `?`, `else`, or an operator, found `;`
 --> src/main.rs:4:25
  |
4 |   while let Ok(_) = v {};
  |                         ^ expected one of `.`, `;`, `?`, `else`, or an operator
```

### Desired output

```Shell
error: expected `;`, found `while`
 --> src/main.rs:4:25
  |
3 |  let v = v?
  |            ^ help: add ';' here
```

### Rationale and extra context

Confusing error

### Other cases

```Rust
Removing the semicolon as suggested causes

error: expected `;`, found `}`
 --> src/main.rs:4:25
  |
4 |   while let Ok(_) = v {}
  |                         ^ help: add `;` here
5 | }
  | - unexpected token

error[E0425]: cannot find value `v` in this scope
 --> src/main.rs:3:11
  |
3 |   let v = v?
  |           ^ not found in this scope

For more information about this error, try `rustc --explain E0425`.
```

### Anything else?

[Playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&code=pub+fn+foo%28%29+%7B%0A++let+v+%3D+v%3F%0A++while+let+Ok%28_%29+%3D+v+%7B%7D%3B%0A%7D%0Afn+main%28%29+%7B%7D)

### PR DESCRIPTION
**Pull request by clubby789**
If the recovery parsed an expression, then failed to eat a `:`, it would return `false` without restoring the snapshot. Fix this by always restoring the snapshot when returning `false`.

Draft for now because I'd like to try and improve this recovery further.

Fixes #117208

### CODE REVIEW

**Comment by clubby789** [comment]
Because the precedence doesn't match up and the expression gets parsed as a `Try`, recovering like this caused a lot of irrelevant spam. Return an Err instead to make the diagnostics more useful

File: compiler/rustc_parse/src/parser/diagnostics.rs [hunk 1]
```diff
@@ -1428,10 +1430,10 @@ impl<'a> Parser<'a> {
 
     /// Rust has no ternary operator (`cond ? then : else`). Parse it and try
     /// to recover from it if `then` and `else` are valid expressions. Returns
-    /// whether it was a ternary operator.
-    pub(super) fn maybe_recover_from_ternary_operator(&mut self) -> bool {
+    /// a [`PErr`] if this appears to be a ternary expression.
+    pub(super) fn maybe_recover_from_ternary_operator(&mut self) -> Option<PErr<'a>> {
```
Comment (compiler-errors) [inline compiler/rustc_parse/src/parser/diagnostics.rs:1434]: `PResult<'a, ()>`?
