### PR TITLE
fixed VecDeque::splice() not filling the buffer correctly when resizing the buffer on start = end range

### LINKED ISSUE #151758: new VecDeque::splice() method in nightly produce incorrect result
When I run the following code on the latest nightly channel, it prints incorrect result:

```rust
#![feature(deque_extend_front)]

use std::collections::VecDeque;
use itertools::join;


struct Point([i32; 2]);

fn main() {
    let mut vec_2 = VecDeque::with_capacity(10);
    vec_2.push_back(Point([0, 6]));
    vec_2.push_back(Point([4, 6]));
    vec_2.push_back(Point([4, 2]));
    vec_2.push_back(Point([2, 2]));
    vec_2.push_back(Point([2, 6]));
    vec_2.push_back(Point([0, 6]));

    let mut vec_3 = VecDeque::with_capacity(10);
    vec_3.push_back(Point([8, 6]));
    vec_3.push_back(Point([8, 4]));
    vec_3.push_back(Point([6, 4]));
    vec_3.push_back(Point([6, 6]));

    let mut vec = VecDeque::with_capacity(10);
    vec.push_front(Point([0, 0]));
    vec.push_back(Point([10, 0]));

    let mut points_str = join(
        vec.iter().map(|val| format!("({}, {})", val.0[0], val.0[1])),
            ", ",
    );
    println!("{}", points_str);

    vec.prepend(vec_2.drain(..));

    points_str = join(
        vec.iter().map(|val| format!("({}, {})", val.0[0], val.0[1])),
            ", ",
    );
    println!("{}", points_str);

    vec.splice(1..1, vec_3.drain(..));

    points_str = join(
        vec.iter().map(|val| format!("({}, {})", val.0[0], val.0[1])),
            ", ",
    );
    println!("{}", points_str);
}
```

I would expect the output of this simple program to be:
```
(0, 0), (10, 0)
(0, 6), (4, 6), (4, 2), (2, 2), (2, 6), (0, 6), (0, 0), (10, 0)
(0, 6), (8, 6), (8, 4), (6, 4), (6, 6), (4, 6), (4, 2), (2, 2), (2, 6), (0, 0), (10, 0)
```

but instead the following got print:
```
(0, 0), (10, 0)
(0, 6), (4, 6), (4, 2), (2, 2), (2, 6), (0, 6), (0, 0), (10, 0)
(0, 6), (8, 6), (8, 4), (6, 4), (6, 6), (4, 6), (4, 2), (2, 2), (2, 6), (0, 0), (0, 0), (0, 0)
```

As you can see, the last element got remvoed, and two extra elements got inserted.  In my actual application (not in this simple example), the extra elements contain random values instead of just zeros.

### PR DESCRIPTION
**Pull request by asder8215**
This PR fixes rust-lang/rust#151758. The issue came from `Splice::move_tail`, which as joboet pointed out:
> The issue is in move_tail, which resizes the buffer, but fails to account for the resulting hole.

The problem with reserving more space through `VecDeque`'s `buf.reserve()` is that it doesn't update `VecDeque`'s `head`, which means that this code in `move_tail`:
```rust
deque.wrap_copy(
    deque.to_physical_idx(tail_start),
    deque.to_physical_idx(new_tail_start),
    self.tail_len,
);
```
could move over the section of data that `tail_start..tail_start + self.tail_len` of the buffer is supposed to be held at to the incorrect destination since all `.to_physical_idx()` is doing is a wrapping add on the `VecDeque`'s head with the passed in `idx` value.

To avoid this I decided to use `VecDeque::reserve` to both allocate more space into the `VecDeque` if necessary and update head appropriately. However, `VecDeque::reserve` internally relies on the `VecDeque`'s `len` field. Earlier in `VecDeque::splice`, it modifies the `VecDeque`'s `len` constructing the drain via `Drain::new` (as it does a `mem::replace` on `deque.len` with the start bound of the passed in `range`). The `VecDeque`'s `len` can also be potentially modified in the earlier `Splice::fill()` call if it does any replacement towards elements within the passed in `range` value for `VecDeque::splice()`. I needed to temporarily restore the `VecDeque`'s `len` to its actual len, so that `VecDeque::reserve` can work properly. Afterward, you can bring back the `VecDeque`'s `len` to what its value was before and fill the gap appropriately with the rest of the `replace_with` content.

r? @joboet

### CODE REVIEW

File: library/alloc/src/collections/vec_deque/splice.rs [hunk 1]
```diff
@@ -138,8 +137,24 @@ impl<T, A: Allocator> Drain<'_, T, A> {
...
+        // `len` of the VecDeque and reassign VecDeque's len back to
+        // drain_start for the Drain struct to fill the gap on drop.
+
+        let drain_start = deque.len;
+        let tail_start = drain_start + self.drain_len;
+        // Actual VecDeque's len = drain_start + tail_len + drain_len (remaining)
+        deque.len += self.tail_len + self.remaining;
+        if deque.len + additional > deque.capacity() {
+            deque.reserve(additional);
+        }
```
Comment (joboet) [inline library/alloc/src/collections/vec_deque/splice.rs]: The check is not resilient against overflow. Also, `reserve` performs this check too, and panics if the capacity overflows. In that case, `Drain::drop` will cause undefined behaviour. Thus I'd still do the check here, but panic in here before updating the length.

**Review by joboet — CHANGES_REQUESTED** [review]
I'm working on a patch that is more clever about copying the elements, but this is certainly a good fix for the meantime. There's an issue though...

*[View changes since this review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/rust/152258/efc9e1b50cbf2cede7ebe25f0a1fc64fd8b3e942..2ecddd259b1682448639741c832d5bd4abd7a545)*

File: library/alloc/src/collections/vec_deque/splice.rs (hunk 1 above)
Comment (asder8215) [reply library/alloc/src/collections/vec_deque/splice.rs]: Oh true! I just pushed the change to cover overflow here. I put the same message as what `reserve()` would say underneath.

File: library/alloc/src/collections/vec_deque/splice.rs [hunk 2]
```diff
@@ -138,8 +137,25 @@ impl<T, A: Allocator> Drain<'_, T, A> {
...
+        // `len` of the VecDeque and reassign VecDeque's len back to
+        // drain_start for the Drain struct to fill the gap on drop.
+
+        let drain_start = deque.len;
+        let tail_start = drain_start + self.drain_len;
+        // Actual VecDeque's len = drain_start + tail_len + drain_len (remaining)
+        deque.len += self.tail_len + self.remaining;
+        if deque.len.checked_add(additional).expect("capacity overflow") > deque.capacity() {
+            deque.reserve(additional);
+        } else {
```
Comment (asder8215) [inline library/alloc/src/collections/vec_deque/splice.rs]: I didn't add this else statement here...

File: library/alloc/src/collections/vec_deque/splice.rs [hunk 3]
```diff
@@ -138,8 +137,24 @@ impl<T, A: Allocator> Drain<'_, T, A> {
...
+        // important to capture the physical index correctly. Therefore,
+        // we reserve additional space (if necessary) based on the actual
+        // `len` of the VecDeque and reassign VecDeque's len back to
+        // drain_start for the Drain struct to fill the gap on drop.
+
+        let drain_start = deque.len;
+        let tail_start = drain_start + self.drain_len;
+        // Actual VecDeque's len = drain_start + tail_len + drain_len (remaining)
+        deque.len += self.tail_len + self.remaining;
+        if deque.len.checked_add(additional).expect("capacity overflow") > deque.capacity() {
```
Comment (joboet) [inline library/alloc/src/collections/vec_deque/splice.rs]: If this panics, `deque.len` will still hold the wrong value, leading to undefined behaviour in `Drain::drop`. Just moving the `deque.len` adjustment past this point won't help either as the `reserve` call may panic in other cases as well. I think the best way would be to inline `reserve` here, and do the buffer resizing before the length adjustment and the `handle_capacity_increase` after.

**Review by joboet — CHANGES_REQUESTED** [review]

File: library/alloc/src/collections/vec_deque/splice.rs (hunk 3 above)
Comment (asder8215) [reply library/alloc/src/collections/vec_deque/splice.rs]: True. I'll inline it here. The alternative I think is to wrap this around a Drop handler that adds back into `deque.len` if dropped, but I think that just makes the code here a bit more complex and may not be as efficient as just inlining what `VecDeque::reserve` is doing

Comment (asder8215) [reply library/alloc/src/collections/vec_deque/splice.rs]: I inlined the `VecDeque::reserve` code. I think it should be good to go.

I also changed the `self.remaining` -> `self.drain_len` within `actual_len` because I realized that `self.drain_len` does get decremented earlier in `Drain::fill` (for replacement instead of insertion), so `self.remaining` may not be reflective with the leftover drain len.

File: library/alloc/src/collections/vec_deque/splice.rs [hunk 4]
```diff
@@ -138,8 +137,76 @@ impl<T, A: Allocator> Drain<'_, T, A> {
...
+                    let new_head = new_capacity - head_len;
+                    unsafe {
+                        // can't use copy_nonoverlapping here, because if e.g. head_len = 2
+                        // and new_capacity = old_capacity + 1, then the heads overlap.
+                        deque.copy(deque.head, new_head, head_len);
+                    }
+                    deque.head = new_head;
+                }
+            }
+            debug_assert!(deque.head < deque.capacity() || deque.capacity() == 0);
```
Comment (joboet) [inline library/alloc/src/collections/vec_deque/splice.rs]: I'd still reuse `handle_capacity_increase` here by temporarily setting `deque.len` to `actual_len` – contrary to the `deque.buf.reserve(..)` call `handle_capacity_increase` cannot panic.

**Review by joboet — CHANGES_REQUESTED** [review]

File: library/alloc/src/collections/vec_deque/splice.rs (hunk 4 above)
Comment (asder8215) [reply library/alloc/src/collections/vec_deque/splice.rs]: Done.

File: library/alloc/src/collections/vec_deque/splice.rs [hunk 5]
```diff
@@ -138,8 +137,36 @@ impl<T, A: Allocator> Drain<'_, T, A> {
...
         let deque = unsafe { self.deque.as_mut() };
-        let tail_start = deque.len + self.drain_len;
-        deque.buf.reserve(tail_start + self.tail_len, additional);
+
+        // `Drain::new` modifies the deque's len (so does `Drain::fill` here)
+        // directly with the start bound of the range passed into
+        // `VecDeque::splice`. This causes an issue with `VecDeque::reserve`
+        // because it depends on what its current `len` value is
+        // and on reserving more space, it updates the `head` of the `VecDeque`,
+        // which is important to capture the physical index correctly
```
Comment (joboet) [inline library/alloc/src/collections/vec_deque/splice.rs]: On second thought, this isn't exactly correct – the issue is mainly that it needs to fill the hole at the end of the buffer created by the resize in the case that the data part wraps around.

**Review by joboet — CHANGES_REQUESTED** [review]

File: library/alloc/src/collections/vec_deque/splice.rs (hunk 5 above)
Comment (asder8215) [reply library/alloc/src/collections/vec_deque/splice.rs]: Will update this comment soon

**Comment by asder8215** [comment]
Hope the new comment/rationale on the change is okay!
