### PR TITLE
fix broken type parameter indexing logic in wfcheck

### LINKED ISSUE #36075: Unused type parameter error regression with nightly-2016-08-28
The following code now fails to typecheck in latest nightly:

```rust
/// Provides an iterator for declaration list parsing.
pub struct DeclarationListParser<'i: 't, 't: 'a, 'a, I, P>
where P: DeclarationParser<Declaration = I> + AtRuleParser<AtRule = I> {
    /// The input given to `DeclarationListParser::new`
    pub input: &'a mut Parser<'i, 't>,

    /// The parser given to `DeclarationListParser::new`
    pub parser: P,
}

/// Provides an iterator for rule list parsing.
pub struct RuleListParser<'i: 't, 't: 'a, 'a, R, P>
where P: QualifiedRuleParser<QualifiedRule = R> + AtRuleParser<AtRule = R> {
    /// The input given to `RuleListParser::new`
    pub input: &'a mut Parser<'i, 't>,

    /// The parser given to `RuleListParser::new`
    pub parser: P,

    is_stylesheet: bool,
    any_rule_so_far: bool,
}
```

```
error[E0392]: parameter `I` is never used
   --> /Users/nox/src/servo/.cargo/registry/src/github.com-1ecc6299db9ec823/cssparser-0.5.7/src/rules_and_declarations.rs:188:54
    |
188 | pub struct DeclarationListParser<'i: 't, 't: 'a, 'a, I, P>
    |                                                      ^ unused type parameter
    |
    = help: consider removing `I` or using a marker such as `std::marker::PhantomData`

error[E0392]: parameter `R` is never used
   --> /Users/nox/src/servo/.cargo/registry/src/github.com-1ecc6299db9ec823/cssparser-0.5.7/src/rules_and_declarations.rs:258:47
    |
258 | pub struct RuleListParser<'i: 't, 't: 'a, 'a, R, P>
    |                                               ^ unused type parameter
    |
    = help: consider removing `R` or using a marker such as `std::marker::PhantomData`

error: aborting due to 2 previous errors
```

*[source](https://github.com/servo/rust-cssparser/blob/59835bc76add364a3bab2cc59ca2405b16728948/src/rules_and_declarations.rs#L189-L196)*

### PR DESCRIPTION
**Pull request by arielb1**
r? @eddyb 

Fixes #36075

### CODE REVIEW

File: src/librustc_typeck/constrained_type_params.rs [hunk 1]
```diff
@@ -13,9 +13,14 @@ use rustc::ty::fold::{TypeFoldable, TypeVisitor};
...
-    Region(ty::EarlyBoundRegion),
+pub struct Parameter(pub u32);
+
+impl From<ty::ParamTy> for Parameter {
+    fn from(param: ty::ParamTy) -> Self { Parameter(param.idx) }
+}
+
+impl From<ty::EarlyBoundRegion> for Parameter {
+    fn from(param: ty::EarlyBoundRegion) -> Self { Parameter(param.index) }
 }
```
Comment (eddyb) [inline src/librustc_typeck/constrained_type_params.rs]: Are these entirely needed? Seems to me like it's less work to just use the index from wherever it first is available.

File: src/librustc_typeck/check/wfcheck.rs [hunk 2]
```diff
@@ -457,44 +457,31 @@ impl<'ccx, 'gcx> CheckTypeWellFormedVisitor<'ccx, 'gcx> {
...
 
         let mut constrained_parameters: FnvHashSet<_> =
-            variances[ast_generics.lifetimes.len()..]
-                     .iter().enumerate()
+            variances.iter().enumerate()
                      .filter(|&(_, &variance)| variance != ty::Bivariant)
-                     .map(|(index, _)| self.param_ty(ast_generics, index))
-                     .map(|p| Parameter::Type(p))
+                     .map(|(index, _)| Parameter(index as u32))
                      .collect();
```
Comment (eddyb) [inline src/librustc_typeck/check/wfcheck.rs]: Could this just reuse a copy of the variances instead of having a (heavier) `FnvHashSet`?
Only in the case of errors do we have less `constrainted_parameters` than parameters, so using a set doesn't make sense.

Comment (arielb1) [inline src/librustc_typeck/check/wfcheck.rs]: I would prefer to use a strongly-typed `BitVector` everywhere.

File: src/librustc_typeck/constrained_type_params.rs (hunk 1 above)
Comment (arielb1) [inline src/librustc_typeck/constrained_type_params.rs]: I had enough index mixups.

File: src/librustc_typeck/constrained_type_params.rs [hunk 3]
```diff
@@ -141,13 +146,14 @@ pub fn setup_constraining_predicates<'tcx>(predicates: &mut [ty::Predicate<'tcx>
     //   * <U as Iterator>::Item = T
     //   * T: Debug
     //   * U: Iterator
+    debug!("setup_constraining_predicates: predicates={:?} impl_trait_ref={:?} input_parameters={:?}",
```
Comment (eddyb) [inline src/librustc_typeck/constrained_type_params.rs]: This and the other `debug!` below are > 100 columns, fails tidy.

File: src/librustc_typeck/constrained_type_params.rs [hunk 4]
```diff
@@ -13,9 +13,14 @@ use rustc::ty::fold::{TypeFoldable, TypeVisitor};
 use rustc::util::nodemap::FnvHashSet;
 
 #[derive(Clone, PartialEq, Eq, Hash, Debug)]
-pub enum Parameter {
-    Type(ty::ParamTy),
-    Region(ty::EarlyBoundRegion),
+pub struct Parameter(pub u32);
```
Comment (nikomatsakis) [inline src/librustc_typeck/constrained_type_params.rs]: Can you please leave a comment explaining what this field is? 

Also, I think the field should be private, and you should write `fn from_index(usize) -> Parameter`; it's always a shame when the public API doesn't expose `usize`, I think.

**Comment by nikomatsakis** [comment]
Left some nits. I won't stop bors since this fixes a regression, but @arielb1 if you get a chance to address them it'd be nice.

File: src/librustc_typeck/constrained_type_params.rs (hunk 4 above)
Comment (arielb1) [inline src/librustc_typeck/constrained_type_params.rs]: But `ParamTy` has this as a `u32`.

Comment (nikomatsakis) [inline src/librustc_typeck/constrained_type_params.rs]: Well, that's an internal conversion anyway...but I'd argue that's a problem with `ParamTy`. :)

Comment (nikomatsakis) [inline src/librustc_typeck/constrained_type_params.rs]: Anyway whatever. I don't care that much.
