### PR TITLE
Begin fixing all the broken doctests in `compiler/`

### LINKED ISSUE #95994: Nearly all compiler/ doctests are broken
[test-output.log](https://github.com/rust-lang/rust/files/8477746/test-output.log)

I haven't tried `--stage 2` but I don't expect it to matter; most of these aren't build errors, they're just because the tests aren't valid syntax.

Found while investigating https://github.com/rust-lang/rust/issues/95515.

@rustbot label +T-compiler +A-testsuite +C-bug

### PR DESCRIPTION
**Pull request by Elliot-Roberts**
Begins to fix #95994.
All of them pass now but 24 of them I've marked with `ignore HELP (<explanation>)` (asking for help) as I'm unsure how to get them to work / if we should leave them as they are.
There are also a few that I marked `ignore` that could maybe be made to work but seem less important.
Each `ignore` has a rough "reason" for ignoring after it parentheses, with 

- `(pseudo-rust)` meaning "mostly rust-like but contains foreign syntax" 
- `(illustrative)` a somewhat catchall for either a fragment of rust that doesn't stand on its own (like a lone type), or abbreviated rust with ellipses and undeclared types that would get too cluttered if made compile-worthy.
- `(not-rust)` stuff that isn't rust but benefits from the syntax highlighting, like MIR.
- `(internal)` uses `rustc_*` code which would be difficult to make work with the testing setup.

Those reason notes are a bit inconsistently applied and messy though. If that's important I can go through them again and try a more principled approach. When I run `rg '```ignore \(' .` on the repo, there look to be lots of different conventions other people have used for this sort of thing. I could try unifying them all if that would be helpful.

I'm not sure if there was a better existing way to do this but I wrote my own script to help me run all the doctests and wade through the output. If that would be useful to anyone else, I put it here: https://github.com/Elliot-Roberts/rust_doctest_fixing_tool

### CODE REVIEW

**Comment by Elliot-Roberts** [comment]
Here are some of the `ignore`s that I thought maybe could be fixed (the line numbers might be slightly off):
```
compiler/rustc_middle/src/ty/util.rs:970
compiler/rustc_middle/src/ty/walk.rs:37  
compiler/rustc_span/src/hygiene.rs:801  
compiler/rustc_typeck/src/collect/type_of.rs:533        
compiler/rustc_typeck/src/outlives/implicit_infer.rs:239
```

File: compiler/rustc_incremental/src/assert_dep_graph.rs [hunk 1]
```diff
@@ -22,7 +22,8 @@
 //!
 //! Example:
 //!
-//! ```
+//! ```ignore HELP (can this be made to work? (well, get the desired error instead of unrelated ones I mean))
+//! # #![feature(rustc_attrs)]
```
Comment (jyn514) [inline compiler/rustc_incremental/src/assert_dep_graph.rs:26]: hmm, I'm not aware of any way to pass custom flags to the rustc invoked by rustdoc unfortunately :(

File: compiler/rustc_infer/src/infer/opaque_types.rs [hunk 2]
```diff
@@ -309,14 +309,21 @@ impl<'a, 'tcx> InferCtxt<'a, 'tcx> {
     /// the same as generating an outlives constraint on `Tc` itself.
     /// For example, if we had a function like this:
     ///
-    /// ```rust
+    /// ```ignore HELP (why doesn't this work?)
```
Comment (jyn514) [inline compiler/rustc_infer/src/infer/opaque_types.rs:312]: https://github.com/rust-lang/rust/issues/85433
The workaround is to add `fn main() {}` to the top.
```suggestion
    /// ```
    /// # fn main() {}
```

File: compiler/rustc_infer/src/infer/opaque_types.rs [hunk 3]
```diff
@@ -602,17 +609,17 @@ impl<'a, 'tcx> InferCtxt<'a, 'tcx> {
 /// Returns `true` if `opaque_hir_id` is a sibling or a child of a sibling of `def_id`.
 ///
 /// Example:
-/// ```rust
+/// ```ignore HELP (why does this not work?)
```
Comment (jyn514) [inline compiler/rustc_infer/src/infer/opaque_types.rs:612]: this might just be a bug??
```
error[E0308]: mismatched types
  --> src/infer/opaque_types.rs:623:16
   |
7  |         pub type Baz = impl Bar;
   |                        -------- the expected opaque type
...
12 |     fn f2() -> bar::Baz { /* ... */ }
   |        --      ^^^^^^^^ expected opaque type, found `()`
   |        |
   |        implicitly returns `()` as its body has no tail or `return` expression
   |
   = note: expected opaque type `Baz`
                found unit type `()`
```

File: compiler/rustc_middle/src/mir/mod.rs [hunk 4]
```diff
@@ -746,27 +746,30 @@ pub enum BorrowKind {
...
     /// If we were to try to translate this closure into a more explicit
     /// form, we'd encounter an error with the code as written:
-    ///
-    ///     struct Env { x: & &mut isize }
-    ///     let x: &mut isize = ...;
-    ///     let y = (&mut Env { &x }, fn_ptr);  // Closure is pair of env and fn
-    ///     fn fn_ptr(env: &mut Env) { **env.x += 5; }
-    ///
+    /// ```ignore HELP (this does indeed error but I'm not sure it's the right one?)
+    /// struct Env { x: & &mut isize }
```
Comment (jyn514) [inline compiler/rustc_middle/src/mir/mod.rs:757]:
```suggestion
    /// ```compile_fail,E0594
    /// struct Env<'a> { x: &'a &'a mut isize }
```
and also change the initialization to `x: &x` on line 760.

File: compiler/rustc_middle/src/mir/mod.rs [hunk 5]
```diff
@@ -746,27 +746,30 @@ pub enum BorrowKind {
...
     /// This is then illegal because you cannot mutate an `&mut` found
     /// in an aliasable location. To solve, you'd have to translate with
     /// an `&mut` borrow:
-    ///
-    ///     struct Env { x: &mut &mut isize }
-    ///     let x: &mut isize = ...;
-    ///     let y = (&mut Env { &mut x }, fn_ptr); // changed from &x to &mut x
-    ///     fn fn_ptr(env: &mut Env) { **env.x += 5; }
-    ///
+    /// ```ignore HELP (it seems like it's a syntax issue but I don't understand what's going on well enough to say)
```
Comment (jyn514) [inline compiler/rustc_middle/src/mir/mod.rs:766]: same changes as above

File: compiler/rustc_middle/src/mir/mod.rs [hunk 6]
```diff
@@ -1004,7 +1007,7 @@ pub struct LocalDecl<'tcx> {
     /// However, from a name lookup point of view, the scopes look more like
     /// as if the let-statements were `match` expressions:
     ///
-    /// ```
+    /// ```ignore HELP (compiler suggests annotating the parse() with the type (u32). is that a good idea?)
```
Comment (jyn514) [inline compiler/rustc_middle/src/mir/mod.rs:1010]: yes, that seems fine

File: compiler/rustc_middle/src/traits/mod.rs [hunk 7]
```diff
@@ -47,7 +47,8 @@ pub enum Reveal {
     /// impl. Concretely, that means that the following example will
     /// fail to compile:
     ///
-    /// ```
+    /// ```ignore HELP (is E0575 the right error for this?)
+    /// #![feature(specialization)]
```
Comment (jyn514) [inline compiler/rustc_middle/src/traits/mod.rs:51]: no, the comment originally forgot a variable:
```diff
diff --git a/compiler/rustc_middle/src/traits/mod.rs b/compiler/rustc_middle/src/traits/mod.rs
index da418eb1355..ffde1294ec6 100644
--- a/compiler/rustc_middle/src/traits/mod.rs
+++ b/compiler/rustc_middle/src/traits/mod.rs
@@ -47,7 +47,7 @@ pub enum Reveal {
     /// impl. Concretely, that means that the following example will
     /// fail to compile:
     ///
-    /// ```ignore HELP (is E0575 the right error for this?)
+    /// ```compile_fail,E0308
     /// #![feature(specialization)]
     /// trait Assoc {
     ///     type Output;
@@ -58,7 +58,7 @@ pub enum Reveal {
     /// }
     ///
     /// fn main() {
-    ///     let <() as Assoc>::Output = true;
+    ///     let x: <() as Assoc>::Output = true;
     /// }
     /// ```
     UserFacing,
```

File: compiler/rustc_middle/src/ty/closure.rs [hunk 8]
```diff
@@ -373,16 +373,18 @@ pub enum BorrowKind {
...
+    /// let mut z = 3;
+    /// let x: &mut isize = &mut z;
     /// let y = || *x += 5;
     /// ```
     ///
     /// If we were to try to translate this closure into a more explicit
     /// form, we'd encounter an error with the code as written:
     ///
-    /// ```
+    /// ```ignore HELP (same as others, expected identifier, found & while parsing Env { &x })
```
Comment (jyn514) [inline compiler/rustc_middle/src/ty/closure.rs:384]: same fix as before

File: compiler/rustc_middle/src/ty/closure.rs [hunk 9]
```diff
@@ -391,9 +393,10 @@ pub enum BorrowKind {
     /// in an aliasable location. To solve, you'd have to translate with
     /// an `&mut` borrow:
     ///
-    /// ```
+    /// ```ignore HELP (same as others)
```
Comment (jyn514) [inline compiler/rustc_middle/src/ty/closure.rs:396]: same fix as before

File: compiler/rustc_middle/src/ty/inhabitedness/mod.rs [hunk 10]
```diff
@@ -56,7 +56,8 @@ impl<'tcx> TyCtxt<'tcx> {
     /// Checks whether a type is visibly uninhabited from a particular module.
     ///
     /// # Example
-    /// ```rust
+    /// ```ignore HELP (should I just add 'use super::Void;' to 'mod c' or does that defeat the point of the example?)
+    /// #![feature(never_type)]
```
Comment (jyn514) [inline compiler/rustc_middle/src/ty/inhabitedness/mod.rs:60]: "visibly" here is referring to exhaustiveness, not name resolution. `use super::Void` should be fine.

File: compiler/rustc_middle/src/ty/sty.rs [hunk 11]
```diff
@@ -187,12 +187,14 @@ pub enum TyKind<'tcx> {
     /// Looking at the following example, the witness for this generator
     /// may end up as something like `for<'a> [Vec<i32>, &'a Vec<i32>]`:
     ///
-    /// ```rust
+    /// ```ignore HELP (is this supposed to error? the code looks purpose built to trigger E0626 but I can't tell if that's what the doc wants?)
```
Comment (jyn514) [inline compiler/rustc_middle/src/ty/sty.rs:190]: no, I don't think it's supposed to error - moving the `yield a;` a line earlier seems fine. but @compiler-errors would probably know better than me.

File: compiler/rustc_mir_build/src/build/expr/as_operand.rs [hunk 12]
```diff
@@ -42,15 +42,16 @@ impl<'a, 'tcx> Builder<'a, 'tcx> {
     /// We tweak the handling of parameters of unsized type slightly to avoid the need to create a
     /// local variable of unsized type. For example, consider this program:
     ///
-    /// ```rust
-    /// fn foo(p: dyn Debug) { ... }
+    /// ```ignore HELP (should that p in bar be box_p?)
```
Comment (jyn514) [inline compiler/rustc_mir_build/src/build/expr/as_operand.rs:45]: yes. but it still fails to compile after - maybe the original code meant to use `foo(&*box_p)` instead? `dyn Debug` can't be passed to a function.

(either that, or this is left over from some pre-1.0 code.)

File: compiler/rustc_monomorphize/src/collector.rs [hunk 13]
```diff
@@ -91,7 +91,8 @@
 //! another function. It suffices to just take a reference in order to introduce
 //! an edge. Consider the following example:
 //!
-//! ```rust
+//! ```ignore HELP (the error suggests changing to f: &dyn Fn(i32), does that seem ok?)
```
Comment (jyn514) [inline compiler/rustc_monomorphize/src/collector.rs:94]: yes. This is a 2021 edition change, it's just syntactic.

File: compiler/rustc_resolve/src/late/lifetimes.rs [hunk 14]
```diff
@@ -406,7 +406,7 @@ pub fn provide(providers: &mut ty::query::Providers) {
 /// The reason for this separate call is to resolve what would otherwise
 /// be a cycle. Consider this example:
 ///
-/// ```rust
+/// ```ignore HELP (compiler suggests adding another lifetime variable to Sub. why?)
```
Comment (jyn514) [inline compiler/rustc_resolve/src/late/lifetimes.rs:409]: `Sub` is declared with a lifetime parameter, so it needs to be defined with one as well. Not sure what it should be. @jackh726 may know.

File: compiler/rustc_span/src/hygiene.rs [hunk 15]
```diff
@@ -756,7 +757,8 @@ impl SyntaxContext {
     /// via a glob import with the given `SyntaxContext`.
     /// For example:
     ///
-    /// ```rust
+    /// ```ignore HELP (this fails saying f cannot be found. is that intentional?)
```
Comment (jyn514) [inline compiler/rustc_span/src/hygiene.rs:760]: yes, see the comment "this is a resolution error" below.

File: compiler/rustc_typeck/src/check/mod.rs [hunk 16]
```diff
@@ -884,16 +884,19 @@ fn report_unexpected_variant_res(tcx: TyCtxt<'_>, res: Res, span: Span) {
...
-///     fn f(x: (isize, isize))
-///
+/// ```
+/// fn f(x: (isize, isize)) {}
+/// ```
 /// Can be called as:
-///
-///     f(1, 2);
-///
+/// ```ignore HELP (is there a way to set TupleArgumentsFlag so that this compiles?)
```
Comment (jyn514) [inline compiler/rustc_typeck/src/check/mod.rs:891]: I think this is used for `Fn*` traits. Not sure how to replicate in user code.

File: compiler/rustc_typeck/src/check/regionck.rs [hunk 17]
```diff
@@ -269,7 +269,7 @@ impl<'a, 'tcx> RegionCtxt<'a, 'tcx> {
     ///
     /// Consider this silly example:
     ///
-    /// ```
+    /// ```ignore HELP (is that @ intentional?)
```
Comment (jyn514) [inline compiler/rustc_typeck/src/check/regionck.rs:272]: `@` is *old* syntax for "garbage-collected pointer": https://pcwalton.github.io/2013/06/02/removing-garbage-collection-from-the-rust-language.html. Not sure how to keep the same semantics - maybe `Box<i32>` is close?

File: compiler/rustc_typeck/src/check/upvar.rs [hunk 18]
```diff
@@ -447,7 +447,8 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
     ///       the existing min_capture map that is stored in TypeckResults.
     ///
     /// Eg:
-    /// ```rust,no_run
+    /// ```ignore HELP ("could not find Display in fmt", is there any way to make this work? I assume we don't have std at this point?)
+    /// #[derive(std::fmt::Display)]
```
Comment (jyn514) [inline compiler/rustc_typeck/src/check/upvar.rs:451]: There is no `Display` derive macro. Only `Debug` can be derived.

File: compiler/rustc_typeck/src/check/upvar.rs [hunk 19]
```diff
@@ -1319,7 +1320,7 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
     ///
     /// Consider another example:
     ///
-    /// ```rust
+    /// ```ignore HELP (what is that move(y.0)?)
```
Comment (jyn514) [inline compiler/rustc_typeck/src/check/upvar.rs:1323]: I think that's MIR and can't be written in user code.

File: compiler/rustc_typeck/src/check/upvar.rs [hunk 20]
```diff
@@ -2213,7 +2214,10 @@ fn determine_place_ancestry_relation<'tcx>(
 ///
 /// Reason we only drop the last deref is because of the following edge case:
 ///
-/// ```rust
+/// ```ignore HELP (I feel like this can be made to work but I'm doing something wrong)
```
Comment (jyn514) [inline compiler/rustc_typeck/src/check/upvar.rs:2217]: try this:
```diff
diff --git a/compiler/rustc_typeck/src/check/upvar.rs b/compiler/rustc_typeck/src/check/upvar.rs
index aef6c2b68ab..d51588d2737 100644
--- a/compiler/rustc_typeck/src/check/upvar.rs
+++ b/compiler/rustc_typeck/src/check/upvar.rs
@@ -2214,8 +2214,8 @@ fn determine_place_ancestry_relation<'tcx>(
 ///
 /// Reason we only drop the last deref is because of the following edge case:
 ///
-/// ```ignore HELP (I feel like this can be made to work but I'm doing something wrong)
-/// # struct A { field_of_a: i32 }
+/// ```
+/// # struct A { field_of_a: Box<i32> }
 /// # struct B {}
 /// # struct C<'a>(&'a i32);
 /// struct MyStruct<'a> {
@@ -2225,7 +2225,7 @@ fn determine_place_ancestry_relation<'tcx>(
 /// }
 ///
 /// fn foo<'a, 'b>(m: &'a MyStruct<'b>) -> impl FnMut() + 'static {
-///     let c = || drop(&*m.a.field_of_a);
+///     || drop(&*m.a.field_of_a)
 ///     // Here we really do want to capture `*m.a` because that outlives `'static`
 ///
 ///     // If we capture `m`, then the closure no longer outlives `'static'
```

**Review by jyn514 — COMMENTED** [review]
> Those reason notes are a bit inconsistently applied and messy though. If that's important I can go through them again and try a more principled approach. When I run rg '```ignore \(' . on the repo, there look to be lots of different conventions other people have used for this sort of thing. I could try unifying them all if that would be helpful.

I don't think it's too important to clean these up, the categories you have seem fine :+1: no need to change existing tests.

I left suggestions for most of your `HELP` comments :)

> (internal) uses rustc_* code which would be difficult to make work with the testing setup.

In retrospect, I think I was wrong on the issue and this should work out of the box as long as it only uses crates that have previously been compiled (see also https://github.com/rust-lang/rust/pull/95445). Maybe try running these and see if they work?

File: compiler/rustc_data_structures/src/tagged_ptr.rs [hunk 21]
```diff
@@ -45,7 +45,8 @@ pub unsafe trait Pointer: Deref {
     /// case you'll need to manually figure out what the right type to pass to
     /// align_of is.
     ///
-    /// ```rust
+    /// ```ignore HELP (should we try to make this runnable? and why does this import not seem to work?)
+    /// # use std::ops::Deref;
```
[the remark this answers is not in the document]
Comment (Elliot-Roberts) [reply compiler/rustc_data_structures/src/tagged_ptr.rs:49]: I'll try that again. I might have somehow been looking at stale error messages (oops sorry).
I used `--stage 1` for the entire thing. Which are the stages we would want to run in CI?

[the remark this answers is not in the document]
Comment (jyn514) [reply compiler/rustc_data_structures/src/tagged_ptr.rs:49]: CI always uses --stage 2. At some point I want to test that other stages work, but those will be tests of bootstrap itself, not that the doctests are correct.

**Comment by Elliot-Roberts** [comment]
Thanks for all your help so far, @jyn514! I'm learning lots. 
I had hoped to fix more myself and leave less of the problem solving to you but with the iteration times so slow it probably would have taken me a while longer. (Some of them I should have just googled/rtfm for a little more though; sorry about that).

I'll have the straightforward fixes done soon and then we'll just have the handful that need expert input :)

**Comment by jyn514** [comment]
Thank you for tackling this!

> with the iteration times so slow it probably would have taken me a while longer

I highly recommend cherry-picking my fix for --stage 0 so the iteration time is faster. It was taking me about ~10 seconds to check each suggestion I made, I wouldn't have gone through them all one by one if it took me 10 minutes each time.

**Comment by Elliot-Roberts** [comment]
Oh ok wow haha. I luckily only had to recompile everything <10 times by working in batches but that sounds like a way better approach.

Oh and for the ones I marked `ignore (internal)`, I of course only marked them that because they fail and adding the obvious `use rustc_...;` suggested by the compiler didn't immediately fix the problem. I can go look at them again now. There are 29 of them with 19 identical seeming ones just in `compiler/rustc_data_structures/src/owning_ref/mod.rs`.

File: compiler/rustc_ast_lowering/src/lib.rs [hunk 22]
```diff
@@ -229,7 +229,7 @@ enum ImplTraitContext<'b, 'a> {
         /// them. This includes lifetimes bound since we entered this context.
         /// For example:
         ///
-        /// ```
+        /// ```ignore HELP (how would you make a stub trait for this?)
         /// type A<'b> = impl for<'a> Trait<'a, Out = impl Sized + 'a>;
```
[the remark this answers is not in the document]
Comment (Elliot-Roberts) [reply compiler/rustc_ast_lowering/src/lib.rs:233]: Should we ignore this one as just an "illustration" then? The original single line of code gets quite buried when we add all that. If we figure out how to make it compile we could just hide the extra lines, but it would still be harder to read the un-rendered source (is that at all a priority for us? I've been considering it moderately important as my vscode doesn't have built-in doc rendering unless I hover on an item which is tedious and doesn't work for everything, but if we expect most future readers to have rendering then I can see why we wouldn't bother with it.)

File: compiler/rustc_typeck/src/check/upvar.rs (hunk 18 above)
Comment (Elliot-Roberts) [reply compiler/rustc_typeck/src/check/upvar.rs:451]: Right :facepalm:

File: compiler/rustc_ast_lowering/src/lib.rs (hunk 22 above)
[the remark this answers is not in the document]
Comment (jyn514) [reply compiler/rustc_ast_lowering/src/lib.rs:233]: I think it's semi important to figure out what the comment is describing in the first place - it's unclear to me now even having read it several times and played around with the example, so it will almost certainly be unclear to whoever reads it next without that context. But I agree making it compile is probably not worth it.

File: compiler/rustc_resolve/src/late/lifetimes.rs (hunk 14 above)
Comment (jackh726) [reply compiler/rustc_resolve/src/late/lifetimes.rs:409]: I think would be
```rust
trait Sub<'b>: for<'a> Base<'a> {
    type SubItem: for<'a> Sub<'a, BaseItem = &'b u32>;
}
```

Comment (jackh726) [reply compiler/rustc_resolve/src/late/lifetimes.rs:409]: Or just
```rust
trait Sub<'b>: for<'a> Base<'a> {
    type SubItem: Sub<'b, BaseItem = &'b u32>;
}
```

Not sure, not entirely sure what this is supposed to be doing

**Comment by Elliot-Roberts** [comment]
Alright, I fixed the `HELP`s I could and also most of the `ignore (internal)`s.
Now left to address are:

- one `ignore LATER` I left in by accident with scratch code. I think that one might need to be an `ignore (illustrative)` because the objects we need to construct to make the example work look big. Are there easier ways than giant struct literals?
- one `ignore HELP` of a new problem (and continuation of the same problem in `ignore CONT`). Also for that one, I added a dev-dependency which might be undesirable?
- seven `ignore UNSOLVED`s for previous problems we don't have solutions for yet.

File: compiler/rustc_ast_lowering/src/lib.rs (hunk 22 above)
[the remark this answers is not in the document]
Comment (oli-obk) [reply compiler/rustc_ast_lowering/src/lib.rs:233]: It's unclear to me, too. Igot all the way to

```rust
#![feature(type_alias_impl_trait)]
trait Trait<'a> { type Out: 'a;}
impl<'a> Trait<'a> for i32 { type Out = String;}
type A = impl for<'a> Trait<'a, Out = impl Sized + 'a>;
fn foo() -> A {
    0_i32
}

```

which is just a bug that it ain't accepted.i'll openable issuefor it And try to figure out the details of what's going on with this field at the same time.

File: compiler/rustc_builtin_macros/src/deriving/encodable.rs [hunk 23]
```diff
@@ -5,14 +5,14 @@
 //!
 //! For example, a type like:
 //!
-//! ```
+//! ```ignore HELP (it says RustcEncodable and RustcEncodable are missing generic parameters? also it says these are deprecated and I can't find any instances of them outside these files. can we remove the whole thing?)
```
Comment (bjorn3) [inline compiler/rustc_builtin_macros/src/deriving/encodable.rs:8]: They are deprecated but stable and thus can't be removed. They need to be used in combination with the rustc-serialize crate on crates.io (a precursor to serde). Note that compiler/rustc_serialize in this repo has diverged significantly from what RustcEncodable and RustcDecodable need.

File: compiler/rustc_parse/src/parser/item.rs [hunk 24]
```diff
@@ -1629,7 +1629,7 @@ impl<'a> Parser<'a> {
 
     /// Parses a declarative macro 2.0 definition.
     /// The `macro` keyword has already been parsed.
-    /// ```
+    /// ```ignore (not-rust)
```
Comment (bjorn3) [inline compiler/rustc_parse/src/parser/item.rs:1632]: Maybe this should be `plain`? That way it won't get rust syntax highlighting either.

Comment (jyn514) [reply compiler/rustc_parse/src/parser/item.rs:1632]: Yeah, just `text` here is better than ignore.

Comment (Elliot-Roberts) [reply compiler/rustc_parse/src/parser/item.rs:1632]: Alright, so all the grammar ones should be `text`? I thought the syntax highlighting looked ok on them personally but I can see why you wouldn't want it.

File: compiler/rustc_mir_build/src/build/expr/as_operand.rs (hunk 12 above)
Comment (Elliot-Roberts) [reply compiler/rustc_mir_build/src/build/expr/as_operand.rs]: I added `#![feature(unsized_locals, unsized_fn_params)]` and it worked. Does that seem like a bad fix?

File: compiler/rustc_builtin_macros/src/deriving/encodable.rs (hunk 23 above)
Comment (Elliot-Roberts) [reply compiler/rustc_builtin_macros/src/deriving/encodable.rs:8]: Oh I didn't realize there was code in `compiler/` that made stability guarantees to code outside the rust repo.
So I should put the crates.io `rustc-serialize` in the [dev-dependencies]`?

Comment (bjorn3) [reply compiler/rustc_builtin_macros/src/deriving/encodable.rs:8]: I think ignoring it is fine. There are already some tests for it in `src/test` anyway.

File: compiler/rustc_parse/src/parser/item.rs (hunk 24 above)
Comment (jyn514) [reply compiler/rustc_parse/src/parser/item.rs:1632]: I don't think we should mark things that aren't rust as rust, no. Anything using EBNF should be `text` for now (rustdoc currently only supports syntax highlighting for rust: https://github.com/rust-lang/rust/issues/56213).

**Comment by jyn514** [comment]
> one ignore LATER I left in by accident with scratch code. I think that one might need to be an ignore (illustrative) because the objects we need to construct to make the example work look big. Are there easier ways than giant struct literals?

I think it's useful to have at least one example of what `TestDescAndFn` looks like. No need to have 3 separate struct literals. We should first confirm that's what the compiler actually expands `#[test]` function to, though.

File: compiler/rustc_parse/src/parser/item.rs (hunk 24 above)
Comment (Elliot-Roberts) [reply compiler/rustc_parse/src/parser/item.rs:1632]: Oh ok so we just shouldn't mark things that aren't rust as `ignore` just for the (correct-ish looking but technically incorrect) highlighting?
The main classes of things I did that for are:

- ebnf (which I'll go make ` ```ebnf ` now)
- MIR, which I marked as `ignore (MIR)` (forgot I separated those from the other `(not-rust)` ones)
- chalk style type stuff, e.g. 
```
forall (U: Trait + ?Sized) {
    if (Self: Unsize<U>) {
        Receiver: DispatchFromDyn<Receiver[Self => U]>
    }
}
```
and
```
for<...> <T as Trait>::U == V
```
- plus a few odd ones out (shall we make them all text? am I misunderstanding some of them?)
  - https://github.com/rust-lang/rust/pull/96094/files/cd7734e958a70641c9492aa2e33572a4de4a83be#diff-5e6fdd07e3ea2b5e20c9fdd3914d1e781ecb4ac4f5349cb2ce33732da8d8a597R173-R175
  - https://github.com/rust-lang/rust/pull/96094/files/cd7734e958a70641c9492aa2e33572a4de4a83be#diff-ee45792072b570212b473de3da83a965c3ce9b74a86109d27e818f7486d8180aR13-R16
  - https://github.com/rust-lang/rust/pull/96094/files/cd7734e958a70641c9492aa2e33572a4de4a83be#diff-a75cbce2712ef8e4b4013fc2189dcd0890974a11880e02ca16a493228add9619R1896
  - https://github.com/rust-lang/rust/pull/96094/files/cd7734e958a70641c9492aa2e33572a4de4a83be#diff-1677e6785e45881b13f3477c96f0e619c7ee07cd0fc54fb91b877cf82b3df22fR9

Should I make the MIR and chalk ones ` ```mir ` and ` ```chalk ` or ` ```text` or are they ok as-is because they're rust-y enough?

Comment (jyn514) [reply compiler/rustc_parse/src/parser/item.rs:1632]: Nah, I'd say just leave them as is. The main thing is to get the tests passing.

**Comment by Elliot-Roberts** [comment]
I think I've done most of what I know how to do and incorporated all the feedback given so far (thanks for the help everyone!).
Now there are just 7 `ignore UNSOLVED`s left to address. (ones we haven't decided how to fix yet). Each has a small explanation/question in parentheses by it.
I might try to investigate one that's a suspected bug, but at my current level of experience that could take a while haha.
If anyone has time to advise me in working on one, that would be great too. I'm not quite sure where to start.

**Comment by jyn514** [comment]
I think merging as-is is fine too, no need to do everything at once. We can keep the tracking issue open until we figure out how to get rid of the `ignore`.

**Comment by jyn514** [comment]
@compiler-errors I think this is ready for review - I don't have bors permissions.

**Comment by klensy** [comment]
Maybe squash? Some commits add\remove the same things.

**Comment by Elliot-Roberts** [comment]
Right, thanks for the reminder.
On a separate note, should the `ignore UNSOLVED`s stay as they are with the comments in parentheses? I had originally written them to be very temporary things.

**Comment by compiler-errors** [comment]
I agree with @jyn514 that this is fine to merge as-is.

@bors r+ rollup=iffy

**Comment by compiler-errors** [comment]
Apparently `ignore` blocks need to parse as valid Rust code, which is not the case for some of the examples here? Can you fix these @Elliot-Roberts? Thanks!

@bors r-
@bors rollup=never

**Comment by Elliot-Roberts** [comment]
Oh ok. I think I'll have to change a few older ignores too. Like this one from 5 years ago: https://github.com/rust-lang/rust/blob/74cea9fdb9ca77d4104df5c28124817004ead6a3/compiler/rustc_ast/src/ast.rs#L1479-L1487

**Comment by Elliot-Roberts** [comment]
Wait never mind, [rustdoc doesn't mind that one](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_ast/ast/struct.QSelf.html).
In the instance identified by CI, it appears the only problem was the un-closed curly brace??

So, given that the error message says 
> `ignore` code blocks require valid Rust code for syntax highlighting; mark blocks that do not contain Rust code as text

should I still mark everything that isn't valid rust as text, or should I keep the ones that rustdoc is OK with?

**Comment by Elliot-Roberts** [comment]
Looks like there were just a couple unmatched braces in one file that were causing rustdoc to fail to parse for syntax highlighting :sweat_smile:.

**Comment by Elliot-Roberts** [comment]
I suppose a number of them would be better as text though. I didn't realize rustdoc shows a warning saying the code isn't tested when you use ignore. That paired with rustdoc's syntax highlighting not actually doing much makes it not very worthwhile.
Here is, for example, some highlighting in my vscode:
image
versus in rustdoc:
image
I thought the highlighting was preferable when I saw it in vscode, but in rustdoc it seems worse than ` ```text`. Potentially even misleading?

I'd appreciate others' opinions.

**Comment by compiler-errors** [comment]
> should I still mark everything that isn't valid rust as text, or should I keep the ones that rustdoc is OK with?

@Elliot-Roberts: I think you should mark it as text, syntax highlighting may get messed up by stray tokens even if rustdoc doesn't get angry when parsing it, and yeah, that "this example is not tested" string is a bit misleading.

... though I have been less involved in this thread compared to e.g. @jyn514 who may have more of a opinion.

**Comment by jyn514** [comment]
We should use `text` unless we're actively looking for syntax highlighting, yeah.

See also https://github.com/rust-lang/rust/pull/96573 which tries to make this a little less confusing.

**Comment by Elliot-Roberts** [comment]
ok hm. reading #96573 and learning that it's expected to be *possible* to run doctests marked with `ignore` changes things a bit. So *everying* that can't compile should be text? including fragments that only fail for undeclared stuff?

I'll start by just using text for everything that wouldn't Parse. I expect there will be some grey area for even that, though.

**Comment by jyn514** [comment]
> ok hm. reading https://github.com/rust-lang/rust/pull/96573 and learning that it's expected to be possible to run doctests marked with ignore changes things a bit. So everying that can't compile should be text? including fragments that only fail for undeclared stuff?

Don't spend too much more time on this. If it passes CI and it looks vaguely right in the generated docs, it's fine :) no need to rewrite half your work.

**Comment by compiler-errors** [comment]
+1, don't waste too much time on it -- I can re-approve it as soon as you can locally confirm that the tests don't fail like they do in https://github.com/rust-lang-ci/rust/runs/6316344673?check_suite_focus=true

**Comment by Elliot-Roberts** [comment]
Ok thanks for the reassurance :)

@compiler-errors How do I test that locally? I have at least verified that rusdoc succeeds for everything in `compiler/` (https://github.com/rust-lang/rust/pull/96094/commits/647d0b6dd3008b2d9d3a57a914bd1487da9133cf was all that was needed)

And I can still go make more of them text as now it's bothering me. I have free time today to work on it.

**Comment by compiler-errors** [comment]
Frankly.... I don't actually know. Anywho, let's try to merge this now.

> And I can still go make more of them text as now it's bothering me

Feel free to open a new PR and `r? @compiler-errors` if you want me to review more follow-up changes.
