### PR TITLE
Canonicalize inputs to const eval where needed

### LINKED ISSUE #68477: ICE cause by tokio::spawn a async function return future opaque type
The ICE cause by `cargo check`, seems happened in multiple locations. One of the cause is when calling `tokio::spawn` function. 

I don't know how to reproduce this problem in minimal example,  but the faulty code in my project comes from here
https://github.com/ShisoftResearch/bifrost/blob/f67c57209dd15072a2868f46c1d26cd356caafae/src/raft/mod.rs#L631

Expecting the code to compile or providing reason for the failure. Instead, the compile just crashed.
This problem appears on both MacOS and Linux
## Meta

rustc 1.42.0-nightly (5e8897b7b 2020-01-21)
binary: rustc
commit-hash: 5e8897b7b51636f157630e6639b711d698e1d101
commit-date: 2020-01-21
host: x86_64-unknown-linux-gnu
release: 1.42.0-nightly
LLVM version: 9.0

tokio 0.2.10

Backtrace:
```
error: internal compiler error: src/librustc/ich/impls_ty.rs:96: StableHasher: unexpected region RePlaceholder(Placeholder { universe: U596, name: BrAnon(3) })

thread 'rustc' panicked at 'Box<Any>', src/librustc_errors/lib.rs:882:9
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:77
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1052
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1426
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:204
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:224
  10: rustc_driver::report_ice
  11: <alloc::boxed::Box<F> as core::ops::function::Fn<A>>::call
             at /rustc/5e8897b7b51636f157630e6639b711d698e1d101/src/liballoc/boxed.rs:1029
  12: proc_macro::bridge::client::<impl proc_macro::bridge::Bridge>::enter::{{closure}}::{{closure}}
             at /rustc/5e8897b7b51636f157630e6639b711d698e1d101/src/libproc_macro/bridge/client.rs:305
  13: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:476
  14: std::panicking::begin_panic
  15: rustc_errors::HandlerInner::bug
  16: rustc_errors::Handler::bug
  17: rustc::util::bug::opt_span_bug_fmt::{{closure}}
  18: rustc::ty::context::tls::with_opt::{{closure}}
  19: rustc::ty::context::tls::with_opt
  20: rustc::util::bug::opt_span_bug_fmt
  21: rustc::util::bug::bug_fmt
  22: rustc::ich::impls_ty::<impl rustc_data_structures::stable_hasher::HashStable<rustc::ich::hcx::StableHashingContext> for rustc::ty::sty::RegionKind>::hash_stable
  23: rustc::ty::sty::_DERIVE_rustc_data_structures_stable_hasher_HashStable_rustc_ich_StableHashingContext_ctx_FOR_TyKind::<impl rustc_data_structures::stable_hasher::HashStable<rustc::ich::hcx::StableHashingContext> for rustc::ty::sty::TyKind>::hash_stable
  24: std::thread::local::LocalKey<T>::with
  25: rustc::ty::sty::_DERIVE_rustc_data_structures_stable_hasher_HashStable_rustc_ich_StableHashingContext_ctx_FOR_TyKind::<impl rustc_data_structures::stable_hasher::HashStable<rustc::ich::hcx::StableHashingContext> for rustc::ty::sty::TyKind>::hash_stable
  26: std::thread::local::LocalKey<T>::with
  27: rustc::mir::interpret::_DERIVE_rustc_data_structures_stable_hasher_HashStable_rustc_ich_StableHashingContext_ctx_FOR_GlobalId::<impl rustc_data_structures::stable_hasher::HashStable<rustc::ich::hcx::StableHashingContext> for rustc::mir::interpret::GlobalId>::hash_stable
  28: <T as rustc::dep_graph::dep_node::DepNodeParams>::to_fingerprint
  29: rustc::dep_graph::dep_node::DepNode::new
  30: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt>::get_query
  31: rustc::mir::interpret::queries::<impl rustc::ty::context::TyCtxt>::const_eval_instance
  32: rustc::mir::interpret::queries::<impl rustc::ty::context::TyCtxt>::const_eval_resolve
  33: <rustc::traits::project::AssocTypeNormalizer as rustc::ty::fold::TypeFolder>::fold_const
  34: rustc::ty::structural_impls::<impl rustc::ty::fold::TypeFoldable for &rustc::ty::TyS>::super_fold_with
  35: <rustc::traits::project::AssocTypeNormalizer as rustc::ty::fold::TypeFolder>::fold_ty
  36: rustc::traits::project::normalize_with_depth
  37: rustc::infer::InferCtxt::commit_unconditionally
  38: <core::iter::adapters::flatten::FlatMap<I,U,F> as core::iter::traits::iterator::Iterator>::next
  39: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter
  40: rustc::traits::select::SelectionContext::collect_predicates_for_types
  41: rustc::traits::select::SelectionContext::confirm_candidate
  42: rustc::traits::select::SelectionContext::select
  43: rustc_data_structures::obligation_forest::ObligationForest<O>::process_obligations
  44: <rustc::traits::fulfill::FulfillmentContext as rustc::traits::engine::TraitEngine>::select_where_possible
  45: rustc_typeck::check::FnCtxt::check_argument_types
  46: rustc_typeck::check::callee::<impl rustc_typeck::check::FnCtxt>::confirm_builtin_call
  47: rustc_typeck::check::callee::<impl rustc_typeck::check::FnCtxt>::check_call
  48: rustc_typeck::check::expr::<impl rustc_typeck::check::FnCtxt>::check_expr_kind
  49: rustc_typeck::check::expr::<impl rustc_typeck::check::FnCtxt>::check_expr_with_expectation_and_needs
  50: rustc_typeck::check::FnCtxt::check_decl_initializer
  51: rustc_typeck::check::FnCtxt::check_decl_local
  52: rustc_typeck::check::FnCtxt::check_stmt
  53: rustc_typeck::check::FnCtxt::check_block_with_expected
  54: rustc_typeck::check::expr::<impl rustc_typeck::check::FnCtxt>::check_expr_kind
  55: rustc_typeck::check::expr::<impl rustc_typeck::check::FnCtxt>::check_expr_with_expectation_and_needs
  56: rustc_typeck::check::FnCtxt::check_stmt
  57: rustc_typeck::check::FnCtxt::check_block_with_expected
  58: rustc_typeck::check::expr::<impl rustc_typeck::check::FnCtxt>::check_expr_kind
  59: rustc_typeck::check::expr::<impl rustc_typeck::check::FnCtxt>::check_expr_with_expectation_and_needs
  60: rustc_typeck::check::_match::<impl rustc_typeck::check::FnCtxt>::check_match
  61: rustc_typeck::check::expr::<impl rustc_typeck::check::FnCtxt>::check_expr_kind
  62: rustc_typeck::check::expr::<impl rustc_typeck::check::FnCtxt>::check_expr_with_expectation_and_needs
  63: rustc_typeck::check::expr::<impl rustc_typeck::check::FnCtxt>::check_expr_kind
  64: rustc_typeck::check::expr::<impl rustc_typeck::check::FnCtxt>::check_expr_with_expectation_and_needs
  65: rustc_typeck::check::FnCtxt::check_stmt
  66: rustc_typeck::check::FnCtxt::check_block_with_expected
  67: rustc_typeck::check::expr::<impl rustc_typeck::check::FnCtxt>::check_expr_kind
  68: rustc_typeck::check::expr::<impl rustc_typeck::check::FnCtxt>::check_expr_with_expectation_and_needs
  69: rustc_typeck::check::_match::<impl rustc_typeck::check::FnCtxt>::check_match
  70: rustc_typeck::check::expr::<impl rustc_typeck::check::FnCtxt>::check_expr_kind
  71: rustc_typeck::check::expr::<impl rustc_typeck::check::FnCtxt>::check_expr_with_expectation_and_needs
  72: rustc_typeck::check::FnCtxt::check_block_with_expected
  73: rustc_typeck::check::expr::<impl rustc_typeck::check::FnCtxt>::check_expr_kind
  74: rustc_typeck::check::expr::<impl rustc_typeck::check::FnCtxt>::check_expr_with_expectation_and_needs
  75: rustc_typeck::check::expr::<impl rustc_typeck::check::FnCtxt>::check_expr_kind
  76: rustc_typeck::check::expr::<impl rustc_typeck::check::FnCtxt>::check_expr_with_expectation_and_needs
  77: rustc_typeck::check::FnCtxt::check_block_with_expected
  78: rustc_typeck::check::expr::<impl rustc_typeck::check::FnCtxt>::check_expr_kind
  79: rustc_typeck::check::expr::<impl rustc_typeck::check::FnCtxt>::check_expr_with_expectation_and_needs
  80: rustc_typeck::check::expr::<impl rustc_typeck::check::FnCtxt>::check_return_expr
  81: rustc_typeck::check::check_fn
  82: rustc_typeck::check::closure::<impl rustc_typeck::check::FnCtxt>::check_expr_closure
  83: rustc_typeck::check::expr::<impl rustc_typeck::check::FnCtxt>::check_expr_kind
  84: rustc_typeck::check::expr::<impl rustc_typeck::check::FnCtxt>::check_expr_with_expectation_and_needs
  85: rustc_typeck::check::FnCtxt::check_argument_types
  86: rustc_typeck::check::callee::<impl rustc_typeck::check::FnCtxt>::confirm_builtin_call
  87: rustc_typeck::check::callee::<impl rustc_typeck::check::FnCtxt>::check_call
  88: rustc_typeck::check::expr::<impl rustc_typeck::check::FnCtxt>::check_expr_kind
  89: rustc_typeck::check::expr::<impl rustc_typeck::check::FnCtxt>::check_expr_with_expectation_and_needs
  90: rustc_typeck::check::expr::<impl rustc_typeck::check::FnCtxt>::check_return_expr
  91: rustc_typeck::check::check_fn
  92: rustc::ty::context::tls::with_context::{{closure}}
  93: rustc_typeck::check::typeck_tables_of
  94: rustc::ty::query::__query_compute::typeck_tables_of
  95: rustc::ty::query::<impl rustc::ty::query::config::QueryAccessors for rustc::ty::query::queries::typeck_tables_of>::compute
  96: rustc::dep_graph::graph::DepGraph::with_task_impl
  97: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt>::get_query
  98: rustc_typeck::collect::type_of
  99: rustc::ty::query::<impl rustc::ty::query::config::QueryAccessors for rustc::ty::query::queries::type_of>::compute
 100: rustc::dep_graph::graph::DepGraph::with_task_impl
 101: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt>::get_query
 102: rustc::traits::select::SelectionContext::constituent_types_for_ty
 103: rustc::ty::sty::Binder<T>::map_bound
 104: rustc::traits::select::SelectionContext::confirm_candidate
 105: rustc::infer::InferCtxt::probe
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.42.0-nightly (5e8897b7b 2020-01-21) running on x86_64-unknown-linux-gnu

note: compiler flags: -C debuginfo=2 -C incremental --crate-type lib

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [typeck_tables_of] processing `raft::RaftService::send_followers_heartbeat`
#1 [type_of] processing `raft::RaftService::send_followers_heartbeat::{{opaque}}#0`
#2 [evaluate_obligation] evaluating trait selection obligation `for<'r, 's, 't0, 't1, 't2, 't3, 't4, 't5, 't6, 't7, 't8, 't9, 't10, 't11, 't12, 't13, 't14, 't15, 't16, 't17, 't18, 't19, 't20, 't21, 't22, 't23> {std::sync::Arc<raft::RaftService>, i64, i64, raft::RaftService, std::sync::Arc<raft::RaftService>, &'r utils::rwlock::RwLock<raft::RaftMeta>, utils::rwlock::RwLock<raft::RaftMeta>, utils::rwlock::RwLockWriteGuardFut<'s, raft::RaftMeta>, utils::rwlock::RwLockWriteGuardFut<'t0, raft::RaftMeta>, (), (), utils::rwlock::RwLockWriteGuard<'t1, raft::RaftMeta>, raft::CheckerAction, raft::CheckerAction, &'t2 raft::RaftService, std::sync::Arc<raft::RaftService>, utils::rwlock::RwLockWriteGuard<'t3, raft::RaftMeta>, &'t4 mut utils::rwlock::RwLockWriteGuard<'t5, raft::RaftMeta>, &'t6 mut utils::rwlock::RwLockWriteGuard<'t7, raft::RaftMeta>, std::option::Option<u64>, impl core::future::future::Future, impl core::future::future::Future, (), (), &'t14 raft::RaftService, std::sync::Arc<raft::RaftService>, utils::rwlock::RwLockWriteGuard<'t15, raft::RaftMeta>, &'t16 mut utils::rwlock::RwLockWriteGuard<'t17, raft::RaftMeta>, &'t18 mut utils::rwlock::RwLockWriteGuard<'t19, raft::RaftMeta>, impl core::future::future::Future, impl core::future::future::Future, (), (), i64, i64, bool, bool, i64, u64, std::time::Duration, tokio::time::delay::Delay, tokio::time::delay::Delay, (), ()}: std::marker::Send`
#3 [typeck_tables_of] processing `raft::RaftService::start`
#4 [typeck_tables_of] processing `raft::RaftService::start::{{closure}}#0`
#5 [type_of] processing `raft::RaftService::start::{{closure}}#0`
#6 [collect_mod_item_types] collecting item types in module `raft`
#7 [analysis] running analysis passes on this crate
end of query stack
error: aborting due to previous error

error: could not compile `bifrost`.

To learn more, run the command again with --verbose.
```

### PR DESCRIPTION
**Pull request by BenLewis-Seequent**
Canonicalize inputs to const eval, so that they can contain inference variables. Which enables invoking const eval queries even if the current param env has inference variable within it, which can occur during trait selection.

This is a reattempt of #67717, in a far less invasive way.

Fixes #68477

r? @nikomatsakis 
cc @eddyb

### CODE REVIEW

**Comment by skinny121** [comment]
Note this doesn't fix #68477, as that const evaluation is invoked through `Const::eval` which doesn't yet take an `InferCtxt` which would be required to fix that issue. I will fix that in a follow up PR.

**Review by eddyb — APPROVED** [review]
LGTM, but I'll leave the approval to @nikomatsakis.

File: src/librustc/mir/interpret/queries.rs [hunk 1]
```diff
@@ -76,3 +78,31 @@ impl<'tcx> TyCtxt<'tcx> {
...
+        param_env: ty::ParamEnv<'tcx>,
+        def_id: DefId,
+        substs: SubstsRef<'tcx>,
+        promoted: Option<mir::Promoted>,
+        span: Option<Span>,
+    ) -> ConstEvalResult<'tcx> {
+        let mut query_state = OriginalQueryValues::default();
+        let canonical = self.canonicalize_query(&(param_env, substs), &mut query_state);
+        let (param_env, substs) = canonical.value;
+        self.tcx.const_eval_resolve(param_env, def_id, substs, promoted, span)
```
Comment (eddyb) [inline src/librustc/mir/interpret/queries.rs]: Wait, I just remembered something: you need to replace the type with the original one, *if* you want to return the value (since it's not used, you could just opt to return `Result<(), ...>` for now).
This is because you don't want the canonical variables to stick around in the type.

There's also a related trick I've told @nikomatsakis about before:
The *value* produced by const-eval shouldn't depend on lifetimes, so we should probably always erase them in the input `substs` (and `param_env` even?).
But the type might have relevant lifetimes, which means we should (just like in the canonical case) use the original type along the new value.

I believe both canonicalizing and erasing lifetimes, would produce the correct value, but erasing them would result in perhaps better cache utilization.

Comment (nikomatsakis) [reply src/librustc/mir/interpret/queries.rs]: Ideally, canonicalization would replace *all* lifetimes and hence be the same, from a cache perspective, but we may not currently handle things that way (we may treat `'static` as special or something...)

**Comment by nikomatsakis** [comment]
Welp this is definitely shorter =) 

It seems like we should do a perf run, though, right?

**Comment by nikomatsakis** [comment]
@rust-timer queue

File: src/librustc/mir/interpret/queries.rs (hunk 1 above)
Comment (skinny121) [reply src/librustc/mir/interpret/queries.rs]: I would think erasing lifetimes would also be benefical for const eval queries which don't use canonicalization, i.e. the ones that don't use `InferCtxt::const_eval_reolve`, although in most cases they already probably have there regions erased. It does look like `canonicalize_query`, which i'm using, does replace `static lifetimes.

Comment (skinny121) [reply src/librustc/mir/interpret/queries.rs]: > But the type might have relevant lifetimes, which means we should (just like in the canonical case) use the original type along the new value.

Most usage of const-eval is by codegen or inside miri which doesn't need/want lifetimes, and in other cases the caller knows what type it's expecting, so I think it should be up to the callers to the replace the type if they need to. One place I'm unsure about is: https://github.com/skinny121/rust/blob/c8e35e3df4016e72bf7eb3a1508a592a80d1f3ae/src/librustc_mir_build/hair/pattern/mod.rs#L764

I'm not sure if lifetimes are important here or not, if they are I can replace the type with the node type retrieved above.

**Comment by skinny121** [comment]
Can I get another perf run to see if erasing lifetimes has any effect on performance?

**Comment by varkor** [comment]
@bors try
@rust-timer queue

**Comment by skinny121** [comment]
Perf numbers looks like just noise.

File: src/librustc/mir/interpret/queries.rs [hunk 2]
```diff
@@ -57,22 +55,50 @@ impl<'tcx> TyCtxt<'tcx> {
...
+    /// Evaluate a constant.
+    pub fn const_eval_global_id(
+        self,
+        param_env: ty::ParamEnv<'tcx>,
+        cid: GlobalId<'tcx>,
+        span: Option<Span>,
+    ) -> ConstEvalResult<'tcx> {
+        // Const-eval shouldn't depend on lifetimes at all, so we can erase them, which should
+        // improve caching of queries.
+        let inputs = self.erase_regions(&param_env.and(cid));
```
Comment (eddyb) [inline src/librustc/mir/interpret/queries.rs]: I'd argue that to make this impossible to misuse, this shouldn't return `Result<ty::Const<'tcx>, ...>` (which `ConstEvalResult<'tcx>` is presumably an alias for), but just the `val` field, in the `Ok` case.

Maybe even the query shouldn't return `ty::Const<'tcx>`, but @oli-obk might have had a good reason for that.

File: src/librustc/ty/sty.rs [hunk 3]
```diff
@@ -2387,8 +2387,11 @@ impl<'tcx> Const<'tcx> {
             let (param_env, substs) = param_env_and_substs.into_parts();
 
             // try to resolve e.g. associated constants to their definition on an impl, and then
-            // evaluate the const.
-            tcx.const_eval_resolve(param_env, did, substs, promoted, None).ok()
+            // evaluate the const. We don't use the type from the evaluated const as that has had it
+            // lifetimes erased.
+            tcx.const_eval_resolve(param_env, did, substs, promoted, None)
```
Comment (eddyb) [inline src/librustc/ty/sty.rs]: Btw, this code is in a closure called `try_const_eval` because it's used twice below, and one of those is a workaround for having inference variables in the `substs`.

So all uses of `ty::Const::eval` which are from an inference context, should probably be replaced with a version that is simpler (because none of the `has_local_value` checks would be necessary) and which goes through `InferCtxt::const_eval_resolve`.

File: src/librustc/mir/interpret/queries.rs (hunk 2 above)
Comment (oli-obk) [reply src/librustc/mir/interpret/queries.rs]: The idea was that we don't need to intern the result at every use site of the query. If perf says changing this to just the value, that's fine with me, but should be its own PR

Comment (eddyb) [reply src/librustc/mir/interpret/queries.rs]: > The idea was that we don't need to intern the result at every use site of the query.

But we have to if the type differs. Maybe we should reuse the interned result from the query if the type *doesn't* differ?

File: src/librustc/ty/sty.rs (hunk 3 above)
Comment (skinny121) [reply src/librustc/ty/sty.rs]: I'm going to do this in a follow up PR, as there is quite a few place that use `Const::eval` methods.

Comment (eddyb) [reply src/librustc/ty/sty.rs]: Makes sense, can you leave a FIXME comment somewhere in this code?

File: src/librustc/mir/interpret/queries.rs (hunk 2 above)
Comment (skinny121) [reply src/librustc/mir/interpret/queries.rs]: Looking at the usages of const-eval, most actually don't need to have the `Const` interned as they immediately us it. So maybe we should leave the interning of the `Const` to the caller as most of the time it doesn't actually need to be done.

**Comment by skinny121** [comment]
This actually now does fix #68477, as we are now erasing lifetimes of all inputs to const-eval, including region inference variables.

**Comment by Aaron1011** [comment]
What's the status of this PR?

**Comment by varkor** [comment]
This is waiting for a review by @nikomatsakis, who has been at the Mozilla All Hands this week, so I imagine it'll be reviewed next week.

**Review by nikomatsakis — COMMENTED** [review]
This seems good to me. My only hesitation is that I can't quite tell what was going on with the erase-regions question, I guess maybe I need to dig a bit deeper there to form an opinion?

File: src/librustc/mir/interpret/queries.rs (hunk 2 above)
Comment (eddyb) [reply src/librustc/mir/interpret/queries.rs]: `ty::Const` is interned, and the type is inside it (the `ty` field).

So if the query interned a `ty::Const` and we have to change the `ty` field (to put in the original, unerased, type) and re-intern, it's a bit wasteful.

This is why it would be nice if the query didn't return a `ty::Const` so you couldn't accidentally use an erased type.

**Comment by shisoft** [comment]
Hi, what's the status of this PR?

**Comment by nikomatsakis** [comment]
I think the status is that we are waiting for @skinny121 to do the following:

* rebase the PR
* potentially adjust the return type to [hide the erased regions](https://github.com/rust-lang/rust/pull/68505#discussion_r370956535)
* (optional) [refactor the `substitute_value` codepath](https://github.com/rust-lang/rust/pull/68505#discussion_r376113782)

**Comment by skinny121** [comment]
Should be ready for code review again. #69181 changed the return type of const eval queries to just the value as requested, as a result the changes to `substitute_value` are no longer needed as no canonical variables can exist in the resultant `ConstValue`.

**Comment by nikomatsakis** [comment]
@skinny121 if I understood correctly, this means my comments about refactoring the substitution code is no longer relevant, but @eddyb's [concern around erasing regions](https://github.com/rust-lang/rust/pull/68505/files#r370956535) is still relevant, right? Any thoughts on fixing that as they suggested?

**Comment by skinny121** [comment]
@nikomatsakis That concern isn't relevant any more as the erased regions don't escape that function, as `ConstEvalResult<'tcx>` is now `Result<ConstValue<'tcx>, ErrorHandled>`, which doesn't contain any types/regions.
