### PR TITLE
Fix rustdoc handling of primitive items

### LINKED ISSUE #73423: no_std crates do not link to primitives
```rust
#![no_std]

// Link to [u8]
pub fn foo() -> u8 {}

```

The link in `x()`'s return type does not work. The intra-doc link on `Foo` _does_ work, but that's because we hardcode the `std` in it, which should be fixed once this is.

Turns out that the "primitive type u8" only lives in std, see https://doc.rust-lang.org/nightly/std/index.html?search=u8

### LINKED ISSUE #79630: [intra-doc-links] primitives inconsistently point offline or online in std docs
I noticed with an offline copy of the Rust 1.47 docs from the package in the Debian Sid repo, that there is an undesirable inconsistency in where links to primitives point to within the `std` documentation.

Take for instance the documentation for the `std::ffi::CStr::to_string_lossy()` method, which I just happened to notice it on. All links except the one for the `str` type point to the offline pages, while the one for `str` points to the online nightly page. However contrastingly the other link to `str` just above that one, in the return type, points to the offline page. Essentially all links to `std` types point offline, except those to primatives, which point online when within the doc comments but offline if in the type/function description.

It seems that the handling of primatives for intra-doc-link processing makes an assumption that links should always point to the online page, without making any exception for the `std` crate itself, unlike what is done otherwise.

### LINKED ISSUE #83083: rustdoc: Can't use anchors in links to primitive types
rustdoc doesn't allow anchors in links to primitive types. For example, given this code:

```rust
//! [test](str#examples)
```

`cargo doc` produces this warning:

```
warning: `str#examples` contains an anchor, but links to builtin types are already anchored
 --> src/lib.rs:1:12
  |
1 | //! [test](str#examples)
  |            ^^^^^^^^^^^^ contains invalid anchor
  |
  = note: `#[warn(rustdoc::broken_intra_doc_links)]` on by default
```

and the resulting link doesn't point to any part of `str`'s documentation, but is rather treated as a normal URL relative to the current page.

The warning claims that “links to builtin types are already anchored”, but this does not appear to be correct. For example, this code:

```rust
//! [test](str)
```

produces a link to <https://doc.rust-lang.org/nightly/std/primitive.str.html>, which does not contain an anchor.

### Meta

```
rustc 1.52.0-nightly (b3e19a221 2021-03-12)
binary: rustc
commit-hash: b3e19a221e63dcffdef87e12eadf1f36a8b90295
commit-date: 2021-03-12
host: powerpc64le-unknown-linux-gnu
release: 1.52.0-nightly
LLVM version: 12.0.0
```

### PR DESCRIPTION
**Pull request by jyn514**
This is a complicated PR and does a lot of things. I'm willing to split it up a little more if it would help reviewing, but it would be tricky and I'd rather not unless it's necessary.

 ## What does this do?

- Fixes https://github.com/rust-lang/rust/issues/73423.
- Fixes https://github.com/rust-lang/rust/issues/79630. I'm not sure how to test this for the standard library explicitly, but you can see from some of the diffs from the `no_std` tests. I also tested it locally and it works correctly: image
- Fixes https://github.com/rust-lang/rust/issues/83083.

## Why are these changes interconnected?

- Allowing anchors (https://github.com/rust-lang/rust/issues/83083) without fixing the online/offline problem (https://github.com/rust-lang/rust/issues/79630) will actually just silently discard the anchors, that's not a fix. The online/offline problem is directly related to the fragment hack; links need to go through `fn href()` to be fixed.
- Technically I could fix the online/offline problem without removing the error on anchors; I am willing to separate that out if it would be helpful for reviewing. However I can't fix the anchor problem without adding docs to core, since rustdoc needs all those primitives to have docs to avoid a fallback, and currently `#![no_std]` crates don't have docs for primitives. I also can't fix the online/offline problem without removing the fragment hack, since otherwise diffs like this will be wrong for some primitives but not others:
```diff
@@ -385,7 +381,7 @@ fn resolve_primitive_associated_item(
                         ty::AssocKind::Const => "associatedconstant",
                         ty::AssocKind::Type => "associatedtype",
                     };
-                    let fragment = format!("{}#{}.{}", prim_ty.as_sym(), out, item_name);
+                    let fragment = format!("{}.{}", out, item_name);
                     (Res::Primitive(prim_ty), fragment, Some((kind.as_def_kind(), item.def_id)))
                 })
         })
```
- Adding primitive docs to core without making any other change will cause links to go to `core` instead of `std`, even for crates with `extern crate std`. See "Breaking changes to doc(primitive)" below for why this is the case. That said, I could add some special casing to rustdoc at the same time that would let me separate this change from the others (it would fix https://github.com/rust-lang/rust/issues/73423 but still special-case intra-doc links). I'm willing to separate that out if helpful for reviewing.

### Add primitive documentation to libcore

This works by reusing the same `include!("primitive_docs.rs")` file in both core and std, and then special-casing links in core to use relative links instead of intra-doc links. This doesn't use purely intra-doc links because some of the primitive docs links to items only in std; this doesn't use purely relative links because that introduces new broken links when the docs are re-exported (e.g. String's `&str` deref impl, or Vec's slice deref impl).

Note that this copies the whole file to core, to avoid anyone compiling core to have to set `CARGO_PKG_NAME`. See https://rust-lang.zulipchat.com/#narrow/stream/122651-general/topic/Who.20should.20review.20changes.20to.20linkchecker.3F/near/249939598 for more context. It also adds a tidy check to make sure the two files are kept in sync.

### Fix inconsistent online/offline primitive docs

This does four things:
- Records modules with `doc(primitive)` in `cache.external_paths`. This is necessary for `href()` to find them later.
- Makes `cache.primitive_locations` available to the intra-doc link pass, by refactoring out a `PrimitiveType::primitive_locations` function that only uses `TyCtxt`.
- Special cases modules with `doc(primitive)` to be treated as always public for the purpose of links.
- Removes the fragment hack. cc @notriddle, I know you added some comments about this in the code (thank you for that!)

### Breaking changes to `doc(primitive)`

"Breaking" is a little misleading here - these are changes in behavior, none of them will cause code to fail to compile.

Let me preface this by saying I think stabilizing `doc(primitive)` was a uniquely terrible idea. As far as I can tell, it was stabilized by oversight; it's been stable since 1.0. No one should have need to use it except the standard library, and a crater run shows that in fact no one is using it: https://github.com/rust-lang/rust/pull/87050#issuecomment-886166706. I hope to actually make `doc(primitive)` a no-op unless you opt-in with a nightly feature, which will keep crates compiling without forcing rustdoc into trying to keep somewhat arbitrary behavior guarantees; but for now, this just subtly changes some of the behavior if you use `doc(primitive)` in a dependency.

That said, here are the changes:
-  Refactoring out `primitive_locations()` is technically a change in behavior, since it no longer looks for primitives in crates that were passed through `--extern`, but not used by the crate; however, that seems like such an unlikely edge case it's not worth dealing with.
- The precedence given to primitive locations is no longer just arbitrary, it can also be inconsistent from run to run. Let me explain that more: previously, primitive locations were sorted by the `CrateNum`; the comment on that sort said "Favor linking to as local extern as possible, so iterate all crates in reverse topological order." Unfortunately, that's not actually what CrateNum tracks: it measures the order crates are loaded, not the number of intermediate crates between that dependency and the root crate. It happened to work as intended before because the compiler injects `extern crate std;` at the top of every crate, which ensured it would have the first CrateNum other than the current, but every other CrateNum was completely arbitrary (for example, `core` often had a later CrateNum than `std`). This now removes the sort on CrateNum completely and special-cases core instead. In particular, if you depend on both `std` and a crate which defines a `doc(primitive)` module, it's arbitrary whether rustdoc will use the docs from std or the ones from the other crate. cc @alexcrichton, you wrote this originally.

cc @rust-lang/rustdoc
cc @rust-lang/libs for the addition to `core` (the commit you're interested in is https://github.com/rust-lang/rust/pull/87073/commits/91346c8293bb5f41d8e1d2ec9336433664652c53)

### CODE REVIEW

File: src/librustdoc/clean/blanket_impl.rs [hunk 1]
```diff
@@ -17,7 +17,7 @@ impl<'a, 'tcx> BlanketImplFinder<'a, 'tcx> {
         let param_env = self.cx.tcx.param_env(item_def_id);
         let ty = self.cx.tcx.type_of(item_def_id);
 
-        debug!("get_blanket_impls({:?})", ty);
+        trace!("get_blanket_impls({:?})", ty);
```
Comment (jyn514) [inline src/librustdoc/clean/blanket_impl.rs:20]: I can drop this whole commit if you like, it's not necessary, just made debugging easier.

File: src/test/rustdoc/primitive/no_std.rs [hunk 2]
```diff
@@ -0,0 +1,5 @@
+#![no_std]
+
+// @has no_std/fn.foo.html '//a/[@href="{{channel}}/core/primitive.u8.html"]' 'u8'
+// Link to [u8]
```
Comment (camelid) [inline src/test/rustdoc/primitive/no_std.rs:4]: Is this supposed to be an intra-doc link rather than a comment?

**Comment by alexcrichton** [comment]
> cc @alexcrichton, you wrote this originally

Sorry, I don't really remember anything in this area so I don't think I'll be of much help

**Comment by jyn514** [comment]
@alexcrichton no worries, I got it working with roughly the same behavior :)

File: src/test/rustdoc/primitive/no_std.rs (hunk 2 above)
Comment (jyn514) [reply src/test/rustdoc/primitive/no_std.rs]: It was supposed to be a link, good catch!

File: src/librustdoc/passes/collect_intra_doc_links.rs [hunk 3]
```diff
@@ -95,14 +95,10 @@ impl Res {
...
-        self.opt_def_id().expect("called def_id() on a primitive")
-    }
-
-    fn opt_def_id(self) -> Option<DefId> {
+    fn def_id(self, tcx: TyCtxt<'_>) -> DefId {
         match self {
-            Res::Def(_, id) => Some(id),
-            Res::Primitive(_) => None,
+            Res::Def(_, id) => id,
+            Res::Primitive(prim) => *PrimitiveType::primitive_locations(tcx).get(&prim).unwrap(),
```
Comment (GuillaumeGomez) [inline src/librustdoc/passes/collect_intra_doc_links.rs:101]: Are we sure we always have all the primitives? I guess unless new primitives are added we're fine, but I'm still feeling a bit uneasy... Well, not a blocker in any case.

**Review by GuillaumeGomez — APPROVED** [review]

File: src/librustdoc/passes/collect_intra_doc_links.rs (hunk 3 above)
Comment (jyn514) [reply src/librustdoc/passes/collect_intra_doc_links.rs:101]: I can go through them one by one this afternoon, but they should all be there now that primitives are documented in core. This will cause an ICE if you use no_core and try to link to a primitive, but no_core isn't really supported anyway.

File: src/librustdoc/clean/types.rs [hunk 4]
```diff
@@ -1795,6 +1747,39 @@ impl PrimitiveType {
...
+            let mut primitive_locations = FxHashMap::default();
+            // NOTE: technically this misses crates that are only passed with `--extern` and not loaded when checking the crate.
+            // This is a degenerate case that I don't plan to support.
+            for &crate_num in tcx.crates(()) {
+                let e = ExternalCrate { crate_num };
+                let crate_name = e.name(tcx);
+                debug!(?crate_num, ?crate_name);
+                for &(def_id, prim) in &e.primitives(tcx) {
+                    // HACK: try to link to std instead where possible
+                    if crate_name == sym::core && primitive_locations.get(&prim).is_some() {
```
Comment (GuillaumeGomez) [inline src/librustdoc/clean/types.rs:1770]:
```suggestion
            if crate_name == sym::core && primitive_locations.contains_key(&prim) {
```

File: src/test/rustdoc/primitive/no_std.rs [hunk 5]
```diff
@@ -0,0 +1,16 @@
...
+#![deny(warnings)]
+#![deny(rustdoc::broken_intra_doc_links)]
+
+// @has no_std/fn.foo.html '//a/[@href="{{channel}}/core/primitive.u8.html"]' 'u8'
+// @has no_std/fn.foo.html '//a/[@href="{{channel}}/core/primitive.u8.html"]' 'primitive link'
+/// Link to [primitive link][u8]
+pub fn foo() -> u8 {}
+
+// Test that all primitives can be linked to.
+/// [isize] [i8] [i16] [i32] [i64] [i128]
```
Comment (GuillaumeGomez) [inline src/test/rustdoc/primitive/no_std.rs:11]: Thanks! That'll be useful to have. :)

**Review by GuillaumeGomez — APPROVED** [review]

**Comment by jyn514** [comment]
https://github.com/rust-lang/rust/pull/87050 just finished with absolutely no regressions :tada: so I think this is good to go :)

@rust-lang/libs did you want to look at the changes to core? https://github.com/rust-lang/rust/commit/36729b037f83dd2221835da29ea979c76d529ecb They are a bit of a maintenance burden - it will be easy to add new intra-doc links, but annoying to add links to `std` for primitives.

File: library/std/src/primitive_docs.rs [hunk 6]
```diff
@@ -100,7 +100,7 @@ mod prim_bool {}
 /// behaviour of the `!` type - expressions with type `!` will coerce into any other type.
 ///
 /// [`u32`]: prim@u32
-/// [`exit`]: process::exit
+#[doc = concat!("[`exit`]: ", include_str!(concat!("../../", env!("CARGO_PKG_NAME"), "/primitive_docs/process_exit.md")))]
```
Comment (jyn514) [inline library/std/src/primitive_docs.rs:103]: I tried a macro to make this simpler, but it doesn't let me emit single attributes without an item:

```
error: expected item after attributes
   --> library/core/src/../../std/src/primitive_docs.rs:3:3
    |
1   | / macro_rules! std_link {
2   | |     ($name: literal, $file: literal) => {
3   | |         #[doc = concat!("[", $name, "]: ", include_str!(concat!("../../", env!("CARGO_PKG_NAME"), "/primitive_docs/", $file, ".md")))]
    | |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
4   | |     }
5   | | }
    | |_- in this expansion of `std_link!`
...
109 |   std_link!("`exit`", "process_exit");
    |   ------------------------------------ in this macro invocation
```
and wrapping the whole thing in a macro seems like more trouble than it's worth.

Comment (GuillaumeGomez) [reply library/std/src/primitive_docs.rs:103]: It's fine as is.

File: src/librustdoc/clean/blanket_impl.rs (hunk 1 above)
Comment (GuillaumeGomez) [reply src/librustdoc/clean/blanket_impl.rs:20]: Debugging is always a good thing.

**Comment by GuillaumeGomez** [comment]
Sorry, forgot to r+ it for whatever reason... You did well. ;)

**Comment by camelid** [comment]
Huh, I wonder why this error is occurring:

```
 + ./build/x86_64-unknown-linux-gnu/stage2/bin/rustc --edition=2018 --crate-type=lib ../library/core/src/lib.rs
error: environment variable `CARGO_PKG_NAME` not defined
   --> ../library/core/src/../../std/src/primitive_docs.rs:103:62
    |
103 | #[doc = concat!("[`exit`]: ", include_str!(concat!("../../", env!("CARGO_PKG_NAME"), "/primitive_docs/process_exit.md")))]
    |                                                              ^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: this error originates in the macro `env` (in Nightly builds, run with -Z macro-backtrace for more info)
```

**Comment by jyn514** [comment]
The `+ ` looks like bash's `-x` mode, so this is probably coming from `pgo.sh`.

**Review by GuillaumeGomez — APPROVED** [review]

**Comment by GuillaumeGomez** [comment]
Thanks a lot for this!

@bors: r+

**Comment by camelid** [comment]
I think you need to rebase to get #87050 and then add `#![feature(doc_primitive)]` to `std` (and maybe `core` too, because of the change to `core`?).

**Comment by jyn514** [comment]
@camelid I'll try to get to it by this weekend - feel free to push to this branch if you want it done sooner :)

**Comment by camelid** [comment]
I _think_ a rebase is all that's necessary, since `feature(doc_primitive)` was already added by the feature-gating PR. r? @GuillaumeGomez

**Comment by camelid** [comment]
Hmm, actually, I think bors would have passed if the `#![feature(doc_primitive)]` was only needed in `std`. Let's see what CI says.

**Comment by Mark-Simulacrum** [comment]
Force-pushed per discussion on Zulip, seems the CARGO_PKG_NAME stuff isn't really necessary (or we don't know why it is).

@bors r=GuillaumeGomez,Mark-Simulacrum

**Comment by jyn514** [comment]
@bors r-

I don't have time to look at the failure right now - maybe it's picking up the wrong files for the links?

File: library/core/src/lib.rs [hunk 7]
```diff
@@ -354,3 +355,5 @@ pub mod arch {
         /* compiler built-in */
     }
 }
+
+include!(concat!("../../std/src/primitive_docs.rs"));
```
Comment (camelid) [inline library/core/src/lib.rs:359]: nit: unnecessary `concat!`:

```suggestion
include!("../../std/src/primitive_docs.rs");
```

File: library/std/primitive_docs/string_string.md [hunk 8]
```diff
@@ -0,0 +1 @@
+string::String
```
Comment (camelid) [inline library/std/primitive_docs/string_string.md:1]: Why not just use the raw HTML links for `std` as well?

File: library/std/src/primitive_docs.rs [hunk 9]
```diff
@@ -100,7 +100,7 @@ mod prim_bool {}
 /// behaviour of the `!` type - expressions with type `!` will coerce into any other type.
 ///
 /// [`u32`]: prim@u32
-/// [`exit`]: process::exit
```
Comment (camelid) [inline library/std/src/primitive_docs.rs:103]: I don't think this link should've worked before; `std::process` is never imported. It must be a bug in how primitives are/were implemented. I think switching to using the `../` style links for `std` too may fix the errors.

File: library/std/primitive_docs/string_string.md (hunk 8 above)
Comment (jyn514) [reply library/std/primitive_docs/string_string.md:1]: Switching to raw links breaks when the primitives are re-exported; take a look at all the new linkcheck exceptions I added for core. If we used raw links for std, they would be broken for std too.

File: library/std/src/primitive_docs.rs (hunk 9 above)
Comment (jyn514) [reply library/std/src/primitive_docs.rs:103]: This file isn't a module, it uses `include!` directly, which means it has the scope of the crate root. So since the crate root for libstd has `mod process`, process is in scope.

Comment (camelid) [reply library/std/src/primitive_docs.rs:103]: Are primitives resolved in the scope of the crate root rather than the module they're defined in?

Comment (jyn514) [reply library/std/src/primitive_docs.rs:103]: I think you misunderstood - this is included from the crate root. The module they're defined in *is* the crate root. https://github.com/rust-lang/rust/blob/6d64f7f695943541fe12bb960971403f440d7225/library/std/src/lib.rs#L572

Comment (camelid) [reply library/std/src/primitive_docs.rs:103]: Oh! I didn't realized that. I always assumed that primitives showed up at the crate root because of some special rustdoc behavior; I didn't realize that it was just an `include!`. Thanks :)

**Comment by jyn514** [comment]
I found why this broke - include_str! is relative to the current file, not the crate root, so ../primitive_docs will always include the std version, not core. I changed this to instead duplicate `primitive_docs` in both core and std, with a tidy check to keep them both in sync.

Personally, I would rather just use `CARGO_PKG_NAME`, but @Mark-Simulacrum asked me not to since it means people will have to start setting that if they don't use cargo.

File: library/core/src/lib.rs (hunk 7 above)
Comment (jyn514) [reply library/core/src/lib.rs]: Thanks, fixed.

**Comment by camelid** [comment]
Hmm, it does seem unfortunate to duplicate them. Could you add a comment to the top of both that says they are exactly identical and enforced by `tidy` to stay that way? Linking to this PR might be nice as well, but the other comment would be the most useful part.

File: src/tools/tidy/src/primitive_docs.rs [hunk 10]
```diff
@@ -0,0 +1,17 @@
+//! Tidy check to make sure `library/{std,core}/src/primitive_docs.rs` are the same file.  These are
+//! different files so that relative links work properly without having to have `CARGO_PKG_NAME`
+//! set, but conceptually they should always be the same.
```
Comment (camelid) [inline src/tools/tidy/src/primitive_docs.rs:3]: Something like this comment is what I was thinking for putting at the top of `primitive_docs.rs`.

**Comment by jyn514** [comment]
> Could you add a comment to the top of both that says they are exactly identical and enforced by tidy to stay that way?

Sure thing, done.

> Linking to this PR might be nice as well, but the other comment would be the most useful part.

People can always find it by running `git log`. (For posterity, the Zulip thread about this was https://rust-lang.zulipchat.com/#narrow/stream/122651-general/topic/Who.20should.20review.20changes.20to.20linkchecker.3F)

File: library/core/src/primitive_docs.rs [hunk 11]
```diff
@@ -0,0 +1,1294 @@
+// `library/{std,core}/src/primitive_docs.rs` should have the same contents.
```
Comment (GuillaumeGomez) [inline library/core/src/primitive_docs.rs:1]: This content comes from somewhere but I don't see the equivalent removed content. Is it normal?

Comment (jyn514) [reply library/core/src/primitive_docs.rs:1]: I don't understand the question. This is duplicated from `library/std/src/primitive_docs.rs`, like the comment says.

Comment (GuillaumeGomez) [reply library/core/src/primitive_docs.rs:1]: This was my question somehow: why is it duplicated and not simply moved?

Comment (GuillaumeGomez) [reply library/core/src/primitive_docs.rs:1]: Other question: if you need to have a file at this location, why not making a link instead?

Comment (jyn514) [reply library/core/src/primitive_docs.rs:1]: See https://github.com/rust-lang/rust/pull/87073#issuecomment-903155679 and https://rust-lang.zulipchat.com/#narrow/stream/122651-general/topic/Who.20should.20review.20changes.20to.20linkchecker.3F.

**Comment by Mark-Simulacrum** [comment]
r=me, but feel free to reassign if you'd like e.g. @GuillaumeGomez to weigh in first.

File: library/core/src/primitive_docs.rs (hunk 11 above)
Comment (jyn514) [reply library/core/src/primitive_docs.rs:1]: @GuillaumeGomez are you ok with this hack?

Comment (GuillaumeGomez) [reply library/core/src/primitive_docs.rs:1]: Not really but I couldn't find something better. The improvements compensate more than enough for this though. So let's go for it!

**Comment by GuillaumeGomez** [comment]
Doesn't seem related to this PR so just in case:

@bors: retry

**Comment by jyn514** [comment]
```

error: auxiliary build of "D:\\a\\rust\\rust\\src/test\\rustdoc\\auxiliary\\issue-15318.rs" failed to compile: 
status: exit code: 1
------------------------------------------

------------------------------------------
stderr:
------------------------------------------
warning: `doc(primitive)` should never have been stable
  --> D:\a\rust\rust\src/test\rustdoc\auxiliary\issue-15318.rs:14:7
   |
14 | #[doc(primitive = "pointer")]
   |
   = note: `#[warn(invalid_doc_attributes)]` on by default
   = warning: this was previously accepted by the compiler but is being phased out; it will become a hard error in a future release!
   = note: for more information, see issue #82730 <https://github.com/rust-lang/rust/issues/82730>
   = note: for more information, see issue #82730 <https://github.com/rust-lang/rust/issues/82730>

     [rustdoc] rustdoc\issue-15318.rs

 test result: FAILED. 453 passed; 3 failed; 6 ignored; 0 measured; 0 filtered out; finished in 55.31s
```

this looks very related, I doubt it's spurious.

@bors r-

**Comment by GuillaumeGomez** [comment]
Should be fixed on windows (urg...).

@bors: r+

**Comment by Mark-Simulacrum** [comment]
This PR adds code to src/test/rustdoc/auxiliary/issue-15318.rs that explictly asks for those two libraries to be linked - I don't really know why it does that, but those libraries don't seem to be present on this builder. My guess is that the right thing is to drop the addition to that test of linking in vcruntime and ucrt, but since I don't know why they were added not sure.

In fact, I sort of want to ask why there's several no_core rustdoc tests being added here -- that seems a little unnecessary? It looks like that's what motivated adding the linking to these libraries perhaps?

**Comment by jyn514** [comment]
> In fact, I sort of want to ask why there's several no_core rustdoc tests being added here -- that seems a little unnecessary? It looks like that's what motivated adding the linking to these libraries perhaps?

`src/test/rustdoc/cross-crate-primitive-doc.rs` tests what happens when you define a primitive in a user crate. Previously, it only used `no_std`, because there were no primitive docs in core. Now that there are primitives in core, it needs `no_core` to be sure it's testing the same thing.

I guess we could give up on testing this in a stand-alone case, and just check the standard library's docs somehow. But I kind of like that it's standalone, it makes it easier to debug issues.

**Comment by jyn514** [comment]
@GuillaumeGomez I still have the same comment as in https://github.com/rust-lang/rust/pull/87073#issuecomment-906512064, I think you're making this too hard.

> @GuillaumeGomez are you sure there's not an easier way to fix the Windows tests than playing wack-a-mole? There's got to be at least one no_std test, I can't imagine we're the first ... If there's really no existing code you can reuse I would almost rather make the test Linux only, since it should be platform independent.

**Comment by Mark-Simulacrum** [comment]
> src/test/rustdoc/cross-crate-primitive-doc.rs tests what happens when you define a primitive in a user crate. Previously, it only used no_std, because there were no primitive docs in core. Now that there are primitives in core, it needs no_core to be sure it's testing the same thing.
> 
> I guess we could give up on testing this in a stand-alone case, and just check the standard library's docs somehow. But I kind of like that it's standalone, it makes it easier to debug issues.

Why do we need to test these with no_core though? We can presumably either have a dummy primitive which isn't normally defined by core/std for testing or not use no_core tests. I don't think we should need to define `_DllMainCRTStartup` for sure, which seems to not exist in *any* current tests or code in rust-lang/rust -- and I don't see any links to vcruntime and ucvrt in user-land (e.g., tests or even core/std) either. So something about those being added seems really suspicious.

In principle a no_std or no_core library is not *that weird* -- there's actually quite a few of these tests in various src/test folders. None of them need link= directives for Windows-specific libraries, that shouldn't be necessary. Are you trying to do something odd with these particular tests? Can we drop them from this PR entirely perhaps and then submit a follow up? Part of the challenge for me is that navigating the diff here with all the commits and the ~1000 lines due to the duplicated file becomes a little complicated, plus the discussion is lost in all the CI and other comments on this PR that are really presumably unrelated to these particular tests in some sense.

**Comment by GuillaumeGomez** [comment]
So with this code:

```rust
#![crate_type = "lib"]
#![doc(html_root_url = "http://example.com/")]
#![no_std]

/// dox
#[doc(primitive = "pointer")]
pub mod ptr {}
```

I get:

```console
---- [rustdoc] rustdoc\issue-15318-2.rs stdout ----

error: auxiliary build of "C:\\Users\\g00600895\\rust\\src/test\\rustdoc\\auxiliary\\issue-15318.rs" failed to compile:
status: exit code: 1
command: PATH="C:\Users\g00600895\rust\build\x86_64-pc-windows-msvc\stage1\bin;C:\Program Files (x86)\Windows Kits\10\bin\x64;C:\Program Files (x86)\Windows Kits\10\bin\10.0.19041.0\x64;C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.28.29910\bin\HostX64\x64;C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.28.29910\bin\HostX64\x64;C:\Users\g00600895\rust\build\x86_64-pc-windows-msvc\stage0-bootstrap-tools\x86_64-pc-windows-msvc\release\deps;C:\Users\g00600895\rust\build\x86_64-pc-windows-msvc\stage0\bin;C:\Users\g00600895\bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\local\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\bin;C:\Users\g00600895\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0;C:\Windows\System32\OpenSSH;C:\Program Files\Git\cmd;C:\Users\g00600895\.cargo\bin;C:\Users\g00600895\AppData\Local\Programs\Python\Python36\Scripts;C:\Users\g00600895\AppData\Local\Programs\Python\Python36;C:\Users\g00600895\.cargo\bin;C:\Users\g00600895\AppData\Local\Microsoft\WindowsApps;C:\Program Files\Git\usr\bin\vendor_perl;C:\Program Files\Git\usr\bin\core_perl" "C:\\Users\\g00600895\\rust\\build\\x86_64-pc-windows-msvc\\stage1\\bin\\rustc.exe" "C:\\Users\\g00600895\\rust\\src/test\\rustdoc\\auxiliary\\issue-15318.rs" "-Zthreads=1" "--target=x86_64-pc-windows-msvc" "-C" "prefer-dynamic" "--out-dir" "C:\\Users\\g00600895\\rust\\build\\x86_64-pc-windows-msvc\\test\\rustdoc\\issue-15318-2\\auxiliary" "-Crpath" "-O" "-Cdebuginfo=0" "-Lnative=C:\\Users\\g00600895\\rust\\build\\x86_64-pc-windows-msvc\\native\\rust-test-helpers" "--crate-type" "dylib" "-L" "C:\\Users\\g00600895\\rust\\build\\x86_64-pc-windows-msvc\\test\\rustdoc\\issue-15318-2\\auxiliary"
stdout:
------------------------------------------

------------------------------------------
stderr:
------------------------------------------
warning: `doc(primitive)` should never have been stable
 --> C:\Users\g00600895\rust\src/test\rustdoc\auxiliary\issue-15318.rs:6:7
  |
6 | #[doc(primitive = "pointer")]
  |       ^^^^^^^^^^^^^^^^^^^^^
  |
  = note: `#[warn(invalid_doc_attributes)]` on by default
  = warning: this was previously accepted by the compiler but is being phased out; it will become a hard error in a future release!
  = note: for more information, see issue #82730 <https://github.com/rust-lang/rust/issues/82730>

error: language item required, but not found: `eh_personality`

error: `#[panic_handler]` function required, but not found

error: aborting due to 2 previous errors; 1 warning emitted
```

So extended version:

```rust
#![crate_type = "lib"]
#![doc(html_root_url = "http://example.com/")]
#![feature(lang_items)]
#![no_std]

#[lang = "eh_personality"]
fn foo() {}

#[panic_handler]
fn bar(_: &core::panic::PanicInfo) -> ! { loop {} }

/// dox
#[doc(primitive = "pointer")]
pub mod ptr {}
```

This time I get:

```console
warning: `doc(primitive)` should never have been stable
  --> C:\Users\g00600895\rust\src/test\rustdoc\auxiliary\issue-15318.rs:13:7
   |
13 | #[doc(primitive = "pointer")]
   |       ^^^^^^^^^^^^^^^^^^^^^
   |
   = note: `#[warn(invalid_doc_attributes)]` on by default
   = warning: this was previously accepted by the compiler but is being phased out; it will become a hard error in a future release!
   = note: for more information, see issue #82730 <https://github.com/rust-lang/rust/issues/82730>

error: linking with `link.exe` failed: exit code: 1120
  |
  = note: "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Tools\\MSVC\\14.28.29910\\bin\\HostX64\\x64\\link.exe" "/DEF:C:\\Users\\G00600~1\\AppData\\Local\\Temp\\rustcvvFE4A\\lib.def" "/NOLOGO" "C:\\Users\\g00600895\\rust\\build\\x86_64-pc-windows-msvc\\test\\rustdoc\\issue-15318\\auxiliary\\issue-15318.issue_15318.2e9a1d5e-cgu.0.rcgu.o" "C:\\Users\\g00600895\\rust\\build\\x86_64-pc-windows-msvc\\test\\rustdoc\\issue-15318\\auxiliary\\issue-15318.3v2z1n200otsjds6.rcgu.o" "/LIBPATH:C:\\Users\\g00600895\\rust\\build\\x86_64-pc-windows-msvc\\native\\rust-test-helpers" "/LIBPATH:C:\\Users\\g00600895\\rust\\build\\x86_64-pc-windows-msvc\\test\\rustdoc\\issue-15318\\auxiliary" "/LIBPATH:C:\\Users\\g00600895\\rust\\build\\x86_64-pc-windows-msvc\\stage1\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib" "/WHOLEARCHIVE:C:\\Users\\g00600895\\rust\\build\\x86_64-pc-windows-msvc\\stage1\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\librustc_std_workspace_core-f00442ccb84b2b8a.rlib" "/WHOLEARCHIVE:C:\\Users\\g00600895\\rust\\build\\x86_64-pc-windows-msvc\\stage1\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libcore-4a3650c0dd0340d3.rlib" "C:\\Users\\g00600895\\rust\\build\\x86_64-pc-windows-msvc\\stage1\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libcompiler_builtins-fbc3f6169a306256.rlib" "/NXCOMPAT" "/LIBPATH:C:\\Users\\g00600895\\rust\\build\\x86_64-pc-windows-msvc\\stage1\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib" "/OUT:C:\\Users\\g00600895\\rust\\build\\x86_64-pc-windows-msvc\\test\\rustdoc\\issue-15318\\auxiliary\\issue_15318.dll" "/OPT:REF,ICF" "/DLL" "/IMPLIB:C:\\Users\\g00600895\\rust\\build\\x86_64-pc-windows-msvc\\test\\rustdoc\\issue-15318\\auxiliary\\issue_15318.dll.lib" "/DEBUG"
  = note:    Creating library C:\Users\g00600895\rust\build\x86_64-pc-windows-msvc\test\rustdoc\issue-15318\auxiliary\issue_15318.dll.lib and object C:\Users\g00600895\rust\build\x86_64-pc-windows-msvc\test\rustdoc\issue-15318\auxiliary\issue_15318.dll.exp
          libcore-4a3650c0dd0340d3.rlib(core-4a3650c0dd0340d3.core.80c8ac74-cgu.6.rcgu.o) : error LNK2001: unresolved external symbol memset
          libcore-4a3650c0dd0340d3.rlib(core-4a3650c0dd0340d3.core.80c8ac74-cgu.8.rcgu.o) : error LNK2001: unresolved external symbol memset
          libcore-4a3650c0dd0340d3.rlib(core-4a3650c0dd0340d3.core.80c8ac74-cgu.1.rcgu.o) : error LNK2001: unresolved external symbol memset
          libcore-4a3650c0dd0340d3.rlib(core-4a3650c0dd0340d3.core.80c8ac74-cgu.13.rcgu.o) : error LNK2001: unresolved external symbol memset
          libcore-4a3650c0dd0340d3.rlib(core-4a3650c0dd0340d3.core.80c8ac74-cgu.3.rcgu.o) : error LNK2001: unresolved external symbol memset
          libcore-4a3650c0dd0340d3.rlib(core-4a3650c0dd0340d3.core.80c8ac74-cgu.4.rcgu.o) : error LNK2001: unresolved external symbol memset
          libcore-4a3650c0dd0340d3.rlib(core-4a3650c0dd0340d3.core.80c8ac74-cgu.10.rcgu.o) : error LNK2019: unresolved external symbol memcmp referenced in function _ZN4core3str7pattern11StrSearcher3new17h877025eee6d464f1E
          libcore-4a3650c0dd0340d3.rlib(core-4a3650c0dd0340d3.core.80c8ac74-cgu.14.rcgu.o) : error LNK2001: unresolved external symbol memcmp
          libcore-4a3650c0dd0340d3.rlib(core-4a3650c0dd0340d3.core.80c8ac74-cgu.6.rcgu.o) : error LNK2001: unresolved external symbol memcmp
          libcompiler_builtins-fbc3f6169a306256.rlib(compiler_builtins-fbc3f6169a306256.compiler_builtins.e8899a6d-cgu.105.rcgu.o) : error LNK2001: unresolved external symbol _fltused
          libcompiler_builtins-fbc3f6169a306256.rlib(compiler_builtins-fbc3f6169a306256.compiler_builtins.e8899a6d-cgu.112.rcgu.o) : error LNK2001: unresolved external symbol _fltused
          libcompiler_builtins-fbc3f6169a306256.rlib(compiler_builtins-fbc3f6169a306256.compiler_builtins.e8899a6d-cgu.113.rcgu.o) : error LNK2001: unresolved external symbol _fltused
          libcompiler_builtins-fbc3f6169a306256.rlib(compiler_builtins-fbc3f6169a306256.compiler_builtins.e8899a6d-cgu.35.rcgu.o) : error LNK2001: unresolved external symbol _fltused
          libcompiler_builtins-fbc3f6169a306256.rlib(compiler_builtins-fbc3f6169a306256.compiler_builtins.e8899a6d-cgu.47.rcgu.o) : error LNK2001: unresolved external symbol _fltused
          libcompiler_builtins-fbc3f6169a306256.rlib(compiler_builtins-fbc3f6169a306256.compiler_builtins.e8899a6d-cgu.61.rcgu.o) : error LNK2001: unresolved external symbol _fltused
          libcompiler_builtins-fbc3f6169a306256.rlib(compiler_builtins-fbc3f6169a306256.compiler_builtins.e8899a6d-cgu.109.rcgu.o) : error LNK2001: unresolved external symbol _fltused
          libcompiler_builtins-fbc3f6169a306256.rlib(compiler_builtins-fbc3f6169a306256.compiler_builtins.e8899a6d-cgu.4.rcgu.o) : error LNK2001: unresolved external symbol _fltused
          libcompiler_builtins-fbc3f6169a306256.rlib(compiler_builtins-fbc3f6169a306256.compiler_builtins.e8899a6d-cgu.115.rcgu.o) : error LNK2001: unresolved external symbol _fltused
          libcompiler_builtins-fbc3f6169a306256.rlib(compiler_builtins-fbc3f6169a306256.compiler_builtins.e8899a6d-cgu.21.rcgu.o) : error LNK2001: unresolved external symbol _fltused
          libcompiler_builtins-fbc3f6169a306256.rlib(compiler_builtins-fbc3f6169a306256.compiler_builtins.e8899a6d-cgu.20.rcgu.o) : error LNK2001: unresolved external symbol _fltused
          libcompiler_builtins-fbc3f6169a306256.rlib(compiler_builtins-fbc3f6169a306256.compiler_builtins.e8899a6d-cgu.90.rcgu.o) : error LNK2001: unresolved external symbol _fltused
          libcompiler_builtins-fbc3f6169a306256.rlib(compiler_builtins-fbc3f6169a306256.compiler_builtins.e8899a6d-cgu.63.rcgu.o) : error LNK2001: unresolved external symbol _fltused
          libcompiler_builtins-fbc3f6169a306256.rlib(compiler_builtins-fbc3f6169a306256.compiler_builtins.e8899a6d-cgu.111.rcgu.o) : error LNK2001: unresolved external symbol _fltused
          libcompiler_builtins-fbc3f6169a306256.rlib(compiler_builtins-fbc3f6169a306256.compiler_builtins.e8899a6d-cgu.25.rcgu.o) : error LNK2001: unresolved external symbol _fltused
          libcompiler_builtins-fbc3f6169a306256.rlib(compiler_builtins-fbc3f6169a306256.compiler_builtins.e8899a6d-cgu.11.rcgu.o) : error LNK2001: unresolved external symbol _fltused
          libcompiler_builtins-fbc3f6169a306256.rlib(compiler_builtins-fbc3f6169a306256.compiler_builtins.e8899a6d-cgu.36.rcgu.o) : error LNK2001: unresolved external symbol _fltused
          libcompiler_builtins-fbc3f6169a306256.rlib(compiler_builtins-fbc3f6169a306256.compiler_builtins.e8899a6d-cgu.57.rcgu.o) : error LNK2001: unresolved external symbol _fltused
          libcompiler_builtins-fbc3f6169a306256.rlib(compiler_builtins-fbc3f6169a306256.compiler_builtins.e8899a6d-cgu.78.rcgu.o) : error LNK2001: unresolved external symbol _fltused
          libcompiler_builtins-fbc3f6169a306256.rlib(compiler_builtins-fbc3f6169a306256.compiler_builtins.e8899a6d-cgu.14.rcgu.o) : error LNK2001: unresolved external symbol _fltused
          libcompiler_builtins-fbc3f6169a306256.rlib(compiler_builtins-fbc3f6169a306256.compiler_builtins.e8899a6d-cgu.16.rcgu.o) : error LNK2001: unresolved external symbol _fltused
          libcompiler_builtins-fbc3f6169a306256.rlib(compiler_builtins-fbc3f6169a306256.compiler_builtins.e8899a6d-cgu.118.rcgu.o) : error LNK2001: unresolved external symbol _fltused
          libcompiler_builtins-fbc3f6169a306256.rlib(compiler_builtins-fbc3f6169a306256.compiler_builtins.e8899a6d-cgu.85.rcgu.o) : error LNK2001: unresolved external symbol _fltused
          libcompiler_builtins-fbc3f6169a306256.rlib(compiler_builtins-fbc3f6169a306256.compiler_builtins.e8899a6d-cgu.104.rcgu.o) : error LNK2001: unresolved external symbol _fltused
          libcompiler_builtins-fbc3f6169a306256.rlib(compiler_builtins-fbc3f6169a306256.compiler_builtins.e8899a6d-cgu.72.rcgu.o) : error LNK2001: unresolved external symbol _fltused
          libcompiler_builtins-fbc3f6169a306256.rlib(compiler_builtins-fbc3f6169a306256.compiler_builtins.e8899a6d-cgu.64.rcgu.o) : error LNK2001: unresolved external symbol _fltused
          libcompiler_builtins-fbc3f6169a306256.rlib(compiler_builtins-fbc3f6169a306256.compiler_builtins.e8899a6d-cgu.18.rcgu.o) : error LNK2001: unresolved external symbol _fltused
          libcompiler_builtins-fbc3f6169a306256.rlib(compiler_builtins-fbc3f6169a306256.compiler_builtins.e8899a6d-cgu.117.rcgu.o) : error LNK2001: unresolved external symbol _fltused
          libcompiler_builtins-fbc3f6169a306256.rlib(compiler_builtins-fbc3f6169a306256.compiler_builtins.e8899a6d-cgu.93.rcgu.o) : error LNK2001: unresolved external symbol _fltused
          libcompiler_builtins-fbc3f6169a306256.rlib(compiler_builtins-fbc3f6169a306256.compiler_builtins.e8899a6d-cgu.33.rcgu.o) : error LNK2001: unresolved external symbol _fltused
          libcompiler_builtins-fbc3f6169a306256.rlib(compiler_builtins-fbc3f6169a306256.compiler_builtins.e8899a6d-cgu.48.rcgu.o) : error LNK2001: unresolved external symbol _fltused
          libcompiler_builtins-fbc3f6169a306256.rlib(compiler_builtins-fbc3f6169a306256.compiler_builtins.e8899a6d-cgu.34.rcgu.o) : error LNK2001: unresolved external symbol _fltused
          libcompiler_builtins-fbc3f6169a306256.rlib(compiler_builtins-fbc3f6169a306256.compiler_builtins.e8899a6d-cgu.59.rcgu.o) : error LNK2001: unresolved external symbol _fltused
          libcompiler_builtins-fbc3f6169a306256.rlib(compiler_builtins-fbc3f6169a306256.compiler_builtins.e8899a6d-cgu.49.rcgu.o) : error LNK2001: unresolved external symbol _fltused
          libcompiler_builtins-fbc3f6169a306256.rlib(compiler_builtins-fbc3f6169a306256.compiler_builtins.e8899a6d-cgu.10.rcgu.o) : error LNK2001: unresolved external symbol _fltused
          libcompiler_builtins-fbc3f6169a306256.rlib(compiler_builtins-fbc3f6169a306256.compiler_builtins.e8899a6d-cgu.41.rcgu.o) : error LNK2001: unresolved external symbol _fltused
          libcompiler_builtins-fbc3f6169a306256.rlib(compiler_builtins-fbc3f6169a306256.compiler_builtins.e8899a6d-cgu.37.rcgu.o) : error LNK2001: unresolved external symbol _fltused
          libcompiler_builtins-fbc3f6169a306256.rlib(compiler_builtins-fbc3f6169a306256.compiler_builtins.e8899a6d-cgu.55.rcgu.o) : error LNK2001: unresolved external symbol _fltused
          libcompiler_builtins-fbc3f6169a306256.rlib(compiler_builtins-fbc3f6169a306256.compiler_builtins.e8899a6d-cgu.52.rcgu.o) : error LNK2001: unresolved external symbol _fltused
          libcompiler_builtins-fbc3f6169a306256.rlib(compiler_builtins-fbc3f6169a306256.compiler_builtins.e8899a6d-cgu.80.rcgu.o) : error LNK2001: unresolved external symbol _fltused
          libcompiler_builtins-fbc3f6169a306256.rlib(compiler_builtins-fbc3f6169a306256.compiler_builtins.e8899a6d-cgu.120.rcgu.o) : error LNK2001: unresolved external symbol _fltused
          libcompiler_builtins-fbc3f6169a306256.rlib(compiler_builtins-fbc3f6169a306256.compiler_builtins.e8899a6d-cgu.32.rcgu.o) : error LNK2001: unresolved external symbol _fltused
          libcompiler_builtins-fbc3f6169a306256.rlib(compiler_builtins-fbc3f6169a306256.compiler_builtins.e8899a6d-cgu.119.rcgu.o) : error LNK2001: unresolved external symbol _fltused
          libcompiler_builtins-fbc3f6169a306256.rlib(compiler_builtins-fbc3f6169a306256.compiler_builtins.e8899a6d-cgu.92.rcgu.o) : error LNK2001: unresolved external symbol _fltused
          libcompiler_builtins-fbc3f6169a306256.rlib(compiler_builtins-fbc3f6169a306256.compiler_builtins.e8899a6d-cgu.30.rcgu.o) : error LNK2001: unresolved external symbol _fltused
          libcompiler_builtins-fbc3f6169a306256.rlib(compiler_builtins-fbc3f6169a306256.compiler_builtins.e8899a6d-cgu.100.rcgu.o) : error LNK2001: unresolved external symbol _fltused
          libcompiler_builtins-fbc3f6169a306256.rlib(compiler_builtins-fbc3f6169a306256.compiler_builtins.e8899a6d-cgu.51.rcgu.o) : error LNK2001: unresolved external symbol _fltused
          libcompiler_builtins-fbc3f6169a306256.rlib(compiler_builtins-fbc3f6169a306256.compiler_builtins.e8899a6d-cgu.122.rcgu.o) : error LNK2001: unresolved external symbol _fltused
          libcompiler_builtins-fbc3f6169a306256.rlib(compiler_builtins-fbc3f6169a306256.compiler_builtins.e8899a6d-cgu.5.rcgu.o) : error LNK2001: unresolved external symbol _fltused
          libcompiler_builtins-fbc3f6169a306256.rlib(compiler_builtins-fbc3f6169a306256.compiler_builtins.e8899a6d-cgu.42.rcgu.o) : error LNK2001: unresolved external symbol _fltused
          libcompiler_builtins-fbc3f6169a306256.rlib(compiler_builtins-fbc3f6169a306256.compiler_builtins.e8899a6d-cgu.91.rcgu.o) : error LNK2001: unresolved external symbol _fltused
          libcompiler_builtins-fbc3f6169a306256.rlib(compiler_builtins-fbc3f6169a306256.compiler_builtins.e8899a6d-cgu.69.rcgu.o) : error LNK2001: unresolved external symbol _fltused
          libcompiler_builtins-fbc3f6169a306256.rlib(compiler_builtins-fbc3f6169a306256.compiler_builtins.e8899a6d-cgu.83.rcgu.o) : error LNK2001: unresolved external symbol _fltused
          libcompiler_builtins-fbc3f6169a306256.rlib(compiler_builtins-fbc3f6169a306256.compiler_builtins.e8899a6d-cgu.17.rcgu.o) : error LNK2001: unresolved external symbol _fltused
          libcompiler_builtins-fbc3f6169a306256.rlib(compiler_builtins-fbc3f6169a306256.compiler_builtins.e8899a6d-cgu.70.rcgu.o) : error LNK2001: unresolved external symbol _fltused
          libcore-4a3650c0dd0340d3.rlib(core-4a3650c0dd0340d3.core.80c8ac74-cgu.9.rcgu.o) : error LNK2001: unresolved external symbol _fltused
          libcompiler_builtins-fbc3f6169a306256.rlib(compiler_builtins-fbc3f6169a306256.compiler_builtins.e8899a6d-cgu.81.rcgu.o) : error LNK2001: unresolved external symbol _fltused
          libcompiler_builtins-fbc3f6169a306256.rlib(compiler_builtins-fbc3f6169a306256.compiler_builtins.e8899a6d-cgu.53.rcgu.o) : error LNK2001: unresolved external symbol _fltused
          libcompiler_builtins-fbc3f6169a306256.rlib(compiler_builtins-fbc3f6169a306256.compiler_builtins.e8899a6d-cgu.43.rcgu.o) : error LNK2001: unresolved external symbol _fltused
          libcore-4a3650c0dd0340d3.rlib(core-4a3650c0dd0340d3.core.80c8ac74-cgu.10.rcgu.o) : error LNK2001: unresolved external symbol _fltused
          libcore-4a3650c0dd0340d3.rlib(core-4a3650c0dd0340d3.core.80c8ac74-cgu.15.rcgu.o) : error LNK2001: unresolved external symbol _fltused
          libcore-4a3650c0dd0340d3.rlib(core-4a3650c0dd0340d3.core.80c8ac74-cgu.3.rcgu.o) : error LNK2001: unresolved external symbol _fltused
          libcore-4a3650c0dd0340d3.rlib(core-4a3650c0dd0340d3.core.80c8ac74-cgu.5.rcgu.o) : error LNK2001: unresolved external symbol _fltused
          libcore-4a3650c0dd0340d3.rlib(core-4a3650c0dd0340d3.core.80c8ac74-cgu.13.rcgu.o) : error LNK2019: unresolved external symbol memcpy referenced in function _ZN4core5slice29_$LT$impl$u20$$u5b$T$u5d$$GT$15copy_from_slice17h761999bedea1fa76E
          libcore-4a3650c0dd0340d3.rlib(core-4a3650c0dd0340d3.core.80c8ac74-cgu.14.rcgu.o) : error LNK2001: unresolved external symbol memcpy
          libcore-4a3650c0dd0340d3.rlib(core-4a3650c0dd0340d3.core.80c8ac74-cgu.4.rcgu.o) : error LNK2001: unresolved external symbol memcpy
          libcore-4a3650c0dd0340d3.rlib(core-4a3650c0dd0340d3.core.80c8ac74-cgu.8.rcgu.o) : error LNK2001: unresolved external symbol memcpy
          LINK : error LNK2001: unresolved external symbol _DllMainCRTStartup
          C:\Users\g00600895\rust\build\x86_64-pc-windows-msvc\test\rustdoc\issue-15318\auxiliary\issue_15318.dll : fatal error LNK1120: 5 unresolved externals


error: aborting due to previous error; 1 warning emitted
```

So at this point, I think my choices kinda make sense. I just don't get why we get all that from `no_std`...

**Comment by GuillaumeGomez** [comment]
As for why `no_std`:

```rust
// compile-flags: -Cmetadata=aux

#![crate_type = "lib"]
#![doc(html_root_url = "http://example.com/")]

/// dox
#[doc(primitive = "pointer")]
pub mod ptr {}
```

Gives:

```console
8: @has check failed
        `XPATH PATTERN` did not match
        // @has issue_15318/fn.bar.html '//*[@href="http://example.com/issue_15318/primitive.pointer.html"]' '*mut T'

Encountered 1 errors
```

Because it targets `std` in priority, which is what @jyn514 was trying to test here.

**Comment by GuillaumeGomez** [comment]
Also, I'm completely fine dropping those tests and doing them in a separate PR.

**Comment by jyn514** [comment]
@GuillaumeGomez there's an existing `my-core.rs` file in `src/test/rustdoc/intra-doc/auxiliary/my-core.rs` - if you use that instead of adding a new one, does it work properly? It doesn't have any of the weird runtime functions.

**Comment by GuillaumeGomez** [comment]
@jyn514 I found out why `my-core.rs` works:

```rust
// ignore-windows
```

Let's go for that!

**Comment by GuillaumeGomez** [comment]
The tidy error was:

```console
tidy error: library/core/src/primitive_docs.rs and library/std/src/primitive_docs.rs have different contents
```

**Comment by camelid** [comment]
I think https://github.com/rust-lang/rust/pull/87073#issuecomment-915385321 is because of links that have been added to `primitive_docs.rs` since this PR was first opened. Probably this will need a rebase, a recopy of `std/primitive_docs.rs` to `core`, and new files that have link resolutions in them.

**Comment by GuillaumeGomez** [comment]
Oh no. T_T

I'm on it...

**Comment by GuillaumeGomez** [comment]
Seems like it's ready! Let's go again. :D

@bors: r+

File: library/core/src/bool.rs [hunk 12]
```diff
@@ -2,7 +2,7 @@
 
 #[lang = "bool"]
 impl bool {
-    /// Returns `Some(t)` if the `bool` is [`true`](keyword.true.html), or `None` otherwise.
+    /// Returns `Some(t)` if the `bool` is `true`, or `None` otherwise.
```
Comment (jyn514) [inline library/core/src/bool.rs:5]: This is not right, you should use relative links rather than removing the link altogether.

File: library/std/src/primitive_docs.rs [hunk 13]
```diff
@@ -1,31 +1,31 @@
...
+// having to have `CARGO_PKG_NAME` set, but conceptually they should always be the same.
 #[doc(primitive = "bool")]
 #[doc(alias = "true")]
 #[doc(alias = "false")]
 /// The boolean type.
 ///
-/// The `bool` represents a value, which could only be either [`true`] or [`false`]. If you cast
-/// a `bool` into an integer, [`true`] will be 1 and [`false`] will be 0.
+/// The `bool` represents a value, which could only be either `true` or `false`. If you cast
+/// a `bool` into an integer, `true` will be 1 and `false` will be 0.
```
Comment (jyn514) [inline library/std/src/primitive_docs.rs:10]: This is wrong, you shouldn't have removed the links (bad rebase maybe?)

Comment (GuillaumeGomez) [reply library/std/src/primitive_docs.rs:10]: Arf indeed!

**Comment by GuillaumeGomez** [comment]
Weird that tidy isn't happy:

```console
$ diff library/core/src/primitive_docs.rs library/std/src/primitive_docs.rs
$ git push -f jyn514 HEAD:primitive-docs 
Everything up-to-date
$ git status
HEAD detached from ef24ca9835c
Untracked files:
  (use "git add <file>..." to include in what will be committed)
	package.json

nothing added to commit but untracked files present (use "git add" to track)
```

Let's try rebasing on master branch...

**Comment by GuillaumeGomez** [comment]
Anyway, should be ready and I think I didn't mess the links once again so that should be fine.

@jyn514: I'll let you handle the r+ then.

**Comment by GuillaumeGomez** [comment]
Ok, mystery solved: it was because the CI was rebasing, making some content missing in libcore...

**Review by jyn514 — COMMENTED** [review]
Please don't fix these yourself, I'm going to fix them myself locally.

**Comment by GuillaumeGomez** [comment]
This error is very funny:

```console
error: `doc(primitive)` should never have been stable
 --> library/core/src/primitive_docs.rs:4:7
  |
4 | #[doc(primitive = "bool")]
  |       ^^^^^^^^^^^^^^^^^^
  |
```

I thought we added a check on the crate name for `core` and `std`?

**Comment by jyn514** [comment]
> I thought we added a check on the crate name for core and std?

No, they're not special-cased - it's a feature gate, which is enabled for both core and std: https://github.com/rust-lang/rust/pull/87073/files#diff-ea30f57e78f3b861b784ae315b3ac31358b7cea2aa14a668084ad412de12e586R136.

I wonder if something is setting `cfg(bootstrap)` for that target when it shouldn't? It seems weird it would only fail on arm.

**Comment by jyn514** [comment]
Oh! The bootstrap compiler just got bumped, it was literally the last PR to merge before this one was tested.

**Comment by GuillaumeGomez** [comment]
Doesn't seem related to our changes...

@bors retry

**Comment by jyn514** [comment]
This seems to have broken ... profiler_builtins?? @rust-lang/wg-llvm @richkadel do you understand this failure?

**Comment by ehuss** [comment]
@bors retry

Windows image update has broken things.

**Comment by richkadel** [comment]
@jyn514 - I don't have the context on what @ehuss has found regarding the Windows image, but hopefully they have a fix and the retry will work.

If not, I see the error happens in `aarch64` and I suppose it's possible it's related to rust-lang/compiler-builtins#429, or maybe not directly related to that patch, but the surrounding code has a lot of conditional compilation based on OS and architecture. If the retry doesn't work, I think @Amanieu will have more insights than I would.
