### PR TITLE
Suggest quoting unquoted idents in attrs

### LINKED ISSUE #58462: Diagnostic for #[cfg(ident=ident)] fails to suggest #[cfg(ident="string")]
Consider the following code ([play](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=7aba880da03c55d16c6d84b5557efb9e)):

```rust
fn main() {
    #[cfg(key=whoops)]
    println!("wont compile");
    
    #[cfg(key="correct syntax")]
    println!("lets make the diagnostic better");
}
```

On nightly today, this errors (correctly), but gives the diagnostic feedback:

```
error: expected unsuffixed literal or identifier, found whoops
 --> src/main.rs:2:11
  |
2 |     #[cfg(key=whoops)]
  |           ^^^

```

This highlight is totally misleading and the message is not great either. The problem in the above input is not the identifier `key` in the left-hand side of the predicate; it is the use of an identifier for the right-hand side of the predicate. We should be highlighting the right-hand side and probably also suggesting they turn it into a string.

Also, the fact that we say "expected unsuffixed literal or identifier, found whoops", where "whoops"  **is** an identifier, is also very confusing in the above.

I'll also note that the behavior here shifted between the current stable+beta and nightly; on beta the diagnostic is not quite as actively misleading as the above, but it isn't really helpful either: 

```
error: `cfg` is not a well-formed meta-item
 --> src/main.rs:2:5
  |
2 |     #[cfg(key=whoops)]
  |     ^^^^^^^^^^^^^^^^^^ help: expected syntax is: `#[cfg(/* predicate */)]`
```

It would probably also be a decent idea to stress the point that the right-hand side must be a string in the various docs that use this form of `#[cfg(...)]`. I am thinking in particular of the `#[cfg(feature = "this")]` syntax that integrates with [features on a crate](https://doc.rust-lang.org/cargo/reference/manifest.html#the-features-section)

### PR DESCRIPTION
**Pull request by sjwang05**
Closes #58462

### CODE REVIEW

File: tests/ui/parser/attribute/attr-unquoted-ident.rs [hunk 1]
```diff
@@ -0,0 +1,15 @@
+// compile-flags: -Zdeduplicate-diagnostics=yes
+// run-rustfix
+
+fn main() {
+    #[cfg(key=foo)]
+    //~^ ERROR expected unsuffixed literal or identifier, found `foo`
```
Comment (WaffleLapkin) [inline tests/ui/parser/attribute/attr-unquoted-ident.rs:6]: this error message is still confusing, `foo` *is* an identifier. can you change the error so that it mentions an identifier only of is really allowed?

**Review by WaffleLapkin — CHANGES_REQUESTED** [review]

File: tests/ui/parser/attribute/attr-unquoted-ident.rs (hunk 1 above)
Comment (sjwang05) [reply tests/ui/parser/attribute/attr-unquoted-ident.rs]: I changed the error so the "or identifier" part only gets shown when we don't try to suggest quoting the ident.

File: compiler/rustc_parse/messages.ftl [hunk 2]
```diff
@@ -406,7 +406,8 @@ parse_invalid_logical_operator = `{$incorrect}` is not a logical operator
     .use_amp_amp_for_conjunction = use `&&` to perform logical conjunction
     .use_pipe_pipe_for_disjunction = use `||` to perform logical disjunction
 
-parse_invalid_meta_item = expected unsuffixed literal or identifier, found `{$token}`
+parse_invalid_meta_item = expected unsuffixed literal{$or_ident}, found `{$token}`
```
Comment (WaffleLapkin) [inline compiler/rustc_parse/messages.ftl:409]: I forgot where this is documented, but please avoid using untranslatable strings like this.

Instead you should either have a flag and match it here (I'm not sure what the syntax is) or simply have two error texts — one with and the other without ` or identifier`.

File: compiler/rustc_parse/src/parser/attr.rs [hunk 3]
```diff
@@ -416,9 +416,20 @@ impl<'a> Parser<'a> {
             Err(err) => err.cancel(),
         }
 
-        Err(self
-            .dcx()
-            .create_err(InvalidMetaItem { span: self.token.span, token: self.token.clone() }))
+        let token = self.token.clone();
+        let (sugg, or_ident) = if self.prev_token == token::Eq && !self.token.span.from_expansion()
```
Comment (WaffleLapkin) [inline compiler/rustc_parse/src/parser/attr.rs:420]: Please add a comment about what this check does, exactly, and why we only accept identifiers in the `else` (I'm also pretty sure identifiers are unrelated to expansions?...)

**Review by WaffleLapkin — CHANGES_REQUESTED** [review]

File: compiler/rustc_parse/src/parser/attr.rs (hunk 3 above)
Comment (sjwang05) [reply compiler/rustc_parse/src/parser/attr.rs]: Added a comment explaining the check, including the `from_expansion()`.

> why we only accept identifiers in the `else`

From briefly glancing over attributes-related tests, it seemed like the "or identifier" would be valid for the remaining cases covered by the else branch, e.g. https://github.com/rust-lang/rust/blob/1a47f5b448f1e023e7ffd2eb57d473d619d2c04d/tests/ui/attributes/nonterminal-expansion.rs#L6

@rustbot review

**Review by WaffleLapkin — APPROVED** [review]
This looks good to me! 🙂

Please [rebase](https://rustc-dev-guide.rust-lang.org/git.html?highlight=rebase#rebasing) this PR to resolve conflicts.

Marking as https://github.com/rust-lang/rust/labels/S-waiting-on-author, once you've fixed the conflicts, please use `@rustbot review` ([learn more about rustbot commands](https://forge.rust-lang.org/triagebot/index.html)). @rustbot author.

**Comment by sjwang05** [comment]
Rebased, thanks for the help.

@rustbot review

**Review by WaffleLapkin — APPROVED** [review]
