### PR TITLE
Check that trait is exported or public before adding hint

### LINKED ISSUE #62194: Coherence hint wrong for a blanked implementation bounded by a private trait
Given code like this:

```rust
trait Private {
}

impl<T: Private> Send for T {
}
```

the diagnostic will read as such:

```
error[E0119]: conflicting implementations of trait `std::marker::Send` for type `&_`:
 --> src/lib.rs:4:1
  |
4 | impl<T: Private> Send for T {
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: conflicting implementation in crate `core`:
          - impl<T> std::marker::Send for &T
            where T: std::marker::Sync, T: ?Sized;
  = note: downstream crates may implement trait `Private` for type `&_`
```

the last note here is incorrect because the only thing that can implement this trait is the crate which declared the private `Private` trait.

### PR DESCRIPTION
**Pull request by fmckeogh**
Closes #62194.

This PR checks the `AccessLevels` of a trait to check whether adding the intercrate ambiguity hint is valid or not.

I am unsure of both the use of `.unwrap()` as well as removing hints for [downstream *and* [upstream](https://github.com/rust-lang/rust/blob/92b0f52584c9375505ecdefdd7855b93a5919d51/src/librustc/traits/select.rs#L112-L142).

### CODE REVIEW

File: src/librustc/traits/specialize/mod.rs [hunk 1]
```diff
@@ -366,8 +366,12 @@ pub(super) fn specialization_graph_provider(
                     }
                 }
 
-                for cause in &overlap.intercrate_ambiguity_causes {
-                    cause.add_intercrate_ambiguity_hint(&mut err);
+                let access_levels = tcx.privacy_access_levels(impl_def_id.krate);
+                let id = tcx.hir().as_local_hir_id(impl_def_id).unwrap();
```
Comment (estebank) [inline src/librustc/traits/specialize/mod.rs]: You should use `if let Some(id) =` instead of `unwrap()`. Every `unwrap` is a potential ICE.

**Review by estebank — APPROVED** [review]
Can you verify that there's at least one test with the note being emitted? (A quick search in my local repo showed that there might be 16 others, but I'd like confirmation.)

**Comment by chocol4te** [comment]
> Can you verify that there's at least one test with the note being emitted? (A quick search in my local repo showed that there might be 16 others, but I'd like confirmation.)

`coherence-projection-conflict-orphan` is correctly emitting the note (`pub trait Foo<P>`), as well as `coherence-overlap-upstream-inherent` for use of `pub trait Remote`.

File: src/librustc/traits/specialize/mod.rs (hunk 1 above)
Comment (chocol4te) [reply src/librustc/traits/specialize/mod.rs]: Will do, should I fix the other two `.unwrap()`s in the `specialization_graph_provider` function?

Comment (estebank) [reply src/librustc/traits/specialize/mod.rs]: Let's leave them for now.

Comment (jonas-schievink) [reply src/librustc/traits/specialize/mod.rs]: These are both fine to leave as-is (they can never fail, if they do, an ICE is appropriate). They could be turned into `.expect` with an explanation, but that's not that important (finding the source of the would-be ICEs would be easy even without).
