### PR TITLE
rustc_codegen: fix musttail returns for cast/indirect ABIs

### LINKED ISSUE #147865: Using `#[inline(always)]` and `become` together leads to LLVM failure
### Code

```Rust
Placeholder, I am trying to make a minimal example that reproduces the bug
```

A more messy example is here: https://github.com/InvalidPathException/wagmi/blob/tail/src/instance.rs
This code does not compile, at lines 315 or 1420, if you remove one of the #[inline(always)] it will compile.

**Edit: No, must remove line 1420.**

And this is not the entire problem, seems like we are having subtle ABI mismatches everywhere
```bash
60076:  musttail call void %handler.i(ptr noalias noundef nonnull readonly sret([24 x i8]) align 8 captures(address) dereferenceable(128) %spec.select, ptr noalias noundef nonnull readonly align 8 captures(address, read_provenance) dereferenceable(128) %28, i64 noundef %29, ptr noalias noundef nonnull align 8 dereferenceable(24) %func_bases, ptr noalias noundef nonnull align 8 dereferenceable(24) %ctrl_bases, ptr noalias noundef align 8 dereferenceable(24) @_ZN5wagmi8instance8dispatch17h278853d1093abebfE), !dbg !82182
60082:define internal void @_ZN5wagmi8instance6op_end17h1c3a38afc0fd5d58E(ptr dead_on_unwind noalias noundef writable writeonly sret([24 x i8]) align 8 captures(none) dereferenceable(24) %_0, ptr noalias readonly align 8 captures(none) %instance, i64 noundef %pc, ptr noalias noundef align 8 dereferenceable(24) %stack, ptr noalias noundef align 8 dereferenceable(24) %control, ptr noalias noundef align 8 dereferenceable(24) %func_bases, ptr noalias noundef align 8 dereferenceable(24) %ctrl_bases) unnamed_addr #18 personality ptr @rust_eh_personality !dbg !82183 {
```

My (not very educated) guess is that, tail call means handling the control to the callee, and it requires there to be no more code in the caller, but in-lining also means putting callee into the caller, perhaps this should be caught somewhere, instead of leading to an LLVM error.

### Meta
```
rustc 1.92.0-nightly (f46475914 2025-10-17)
binary: rustc
commit-hash: f46475914de626785090a05ae037578aaa119fc8
commit-date: 2025-10-17
host: aarch64-apple-darwin
release: 1.92.0-nightly
LLVM version: 21.1.3
```

### Error output
<details><summary><strong>Backtrace</strong></summary>
<p>

```
RUST_BACKTRACE=1 cargo +nightly build     
warning: `panic` setting is ignored for `bench` profile
   Compiling serde v1.0.219
   Compiling serde_json v1.0.143
   Compiling wagmi v0.1.0 (/Users/mark/Desktop/github/wagmi)
rustc-LLVM ERROR: failed to perform tail call elimination on a call site marked musttail
error: could not compile `wagmi` (lib)

Caused by:
  process didn't exit successfully: `/Users/mark/.rustup/toolchains/nightly-aarch64-apple-darwin/bin/rustc --crate-name wagmi --edition=2021 src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --diagnostic-width=104 --crate-type lib --emit=dep-info,metadata,link -C embed-bitcode=no -C debuginfo=2 -C split-debuginfo=unpacked --check-cfg 'cfg(docsrs,test)' --check-cfg 'cfg(feature, values("wasm_debug"))' -C metadata=cb10e3ba1b898985 -C extra-filename=-2131c9eb7e076518 --out-dir /Users/mark/Desktop/github/wagmi/target/debug/deps -C incremental=/Users/mark/Desktop/github/wagmi/target/debug/incremental -L dependency=/Users/mark/Desktop/github/wagmi/target/debug/deps --extern clap=/Users/mark/Desktop/github/wagmi/target/debug/deps/libclap-666d1a1cd0f4cc56.rmeta --extern paste=/Users/mark/Desktop/github/wagmi/target/debug/deps/libpaste-2bcbe54994a4a269.dylib --extern serde=/Users/mark/Desktop/github/wagmi/target/debug/deps/libserde-dedc72f5d8c9bae9.rmeta --extern serde_json=/Users/mark/Desktop/github/wagmi/target/debug/deps/libserde_json-34bf5d48446ff428.rmeta -C target-cpu=native` (exit status: 101)
```

</p>
</details>

Inspect IR:
<details>

```
cargo +nightly rustc --lib -- --emit=llvm-ir -Csave-temps
rg -n "define .*dispatch|define .*op_end|musttail" target/debug/deps/*.ll

warning: `panic` setting is ignored for `bench` profile
   Compiling wagmi v0.1.0 (/Users/mark/Desktop/github/wagmi)
rustc-LLVM ERROR: failed to perform tail call elimination on a call site marked musttail
error: could not compile `wagmi` (lib)

Caused by:
  process didn't exit successfully: `/Users/mark/.rustup/toolchains/nightly-aarch64-apple-darwin/bin/rustc --crate-name wagmi --edition=2021 src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --diagnostic-width=110 --crate-type lib --emit=dep-info,metadata,link -C embed-bitcode=no -C debuginfo=2 -C split-debuginfo=unpacked --check-cfg 'cfg(docsrs,test)' --check-cfg 'cfg(feature, values("wasm_debug"))' -C metadata=cb10e3ba1b898985 -C extra-filename=-6af3dee71c1e5379 --out-dir /Users/mark/Desktop/github/wagmi/target/debug/deps -C incremental=/Users/mark/Desktop/github/wagmi/target/debug/incremental -L dependency=/Users/mark/Desktop/github/wagmi/target/debug/deps --extern clap=/Users/mark/Desktop/github/wagmi/target/debug/deps/libclap-cf191cd05b25755d.rmeta --extern paste=/Users/mark/Desktop/github/wagmi/target/debug/deps/libpaste-a0ac70e445072a49.dylib --extern serde=/Users/mark/Desktop/github/wagmi/target/debug/deps/libserde-0dbbc4abf86d9a19.rmeta --extern serde_json=/Users/mark/Desktop/github/wagmi/target/debug/deps/libserde_json-6eb3feed6383e159.rmeta --emit=llvm-ir -Csave-temps -Ccodegen-units=1 -Cincremental=no -Clto=off -Copt-level=3 -Zmir-opt-level=4 -Csave-temps` (exit status: 101)
23433:  musttail call void %handler.i(ptr noalias noundef nonnull readonly sret([24 x i8]) align 8 captures(address) dereferenceable(128) %6, ptr noalias noundef nonnull readonly align 8 captures(address, read_provenance) dereferenceable(128) %14, i64 noundef %15, ptr noalias noundef nonnull align 8 dereferenceable(24) %func_bases, ptr noalias noundef nonnull align 8 dereferenceable(24) %ctrl_bases, ptr noalias noundef align 8 dereferenceable(24) @_ZN5wagmi8instance8dispatch17h278853d1093abebfE), !dbg !32193
23640:  musttail call void %handler.i(ptr noalias noundef nonnull readonly sret([24 x i8]) align 8 captures(address) dereferenceable(128) %9, ptr noalias noundef nonnull readonly align 8 captures(address, read_provenance) dereferenceable(128) %17, i64 noundef %18, ptr noalias noundef nonnull align 8 dereferenceable(24) %func_bases, ptr noalias noundef nonnull align 8 dereferenceable(24) %ctrl_bases, ptr noalias noundef align 8 dereferenceable(24) @_ZN5wagmi8instance8dispatch17h278853d1093abebfE), !dbg !32478
23847:  musttail call void %handler.i(ptr noalias noundef nonnull readonly sret([24 x i8]) align 8 captures(address) dereferenceable(128) %9, ptr noalias noundef nonnull readonly align 8 captures(address, read_provenance) dereferenceable(128) %17, i64 noundef %18, ptr noalias noundef nonnull align 8 dereferenceable(24) %func_bases, ptr noalias noundef nonnull align 8 dereferenceable(24) %ctrl_bases, ptr noalias noundef align 8 dereferenceable(24) @_ZN5wagmi8instance8dispatch17h278853d1093abebfE), !dbg !32763
24138:  musttail call void %handler.i(ptr noalias noundef nonnull readonly sret([24 x i8]) align 8 captures(address) dereferenceable(128) %15, ptr noalias noundef nonnull readonly align 8 captures(address, read_provenance) dereferenceable(128) %23, i64 noundef %24, ptr noalias noundef nonnull align 8 dereferenceable(24) %func_bases, ptr noalias noundef nonnull align 8 dereferenceable(24) %ctrl_bases, ptr noalias noundef align 8 dereferenceable(24) @_ZN5wagmi8instance8dispatch17h278853d1093abebfE), !dbg !33158
24429:  musttail call void %handler.i(ptr noalias noundef nonnull readonly sret([24 x i8]) align 8 captures(address) dereferenceable(128) %14, ptr noalias noundef nonnull readonly align 8 captures(address, read_provenance) dereferenceable(128) %22, i64 noundef %23, ptr noalias noundef nonnull align 8 dereferenceable(24) %func_bases, ptr noalias noundef nonnull align 8 dereferenceable(24) %ctrl_bases, ptr noalias noundef align 8 dereferenceable(24) @_ZN5wagmi8instance8dispatch17h278853d1093abebfE), !dbg !33514
24636:  musttail call void %handler.i(ptr noalias noundef nonnull readonly sret([24 x i8]) align 8 captures(address) dereferenceable(128) %9, ptr noalias noundef nonnull readonly align 8 captures(address, read_provenance) dereferenceable(128) %17, i64 noundef %18, ptr noalias noundef nonnull align 8 dereferenceable(24) %func_bases, ptr noalias noundef nonnull align 8 dereferenceable(24) %ctrl_bases, ptr noalias noundef align 8 dereferenceable(24) @_ZN5wagmi8instance8dispatch17h278853d1093abebfE), !dbg !33799
24775:  musttail call void %handler.i(ptr noalias noundef nonnull readonly sret([24 x i8]) align 8 captures(address) dereferenceable(128) %5, ptr noalias noundef nonnull readonly align 8 captures(address, read_provenance) dereferenceable(128) %13, i64 noundef %14, ptr noalias noundef nonnull align 8 dereferenceable(24) %func_bases, ptr noalias noundef nonnull align 8 dereferenceable(24) %ctrl_bases, ptr noalias noundef align 8 dereferenceable(24) @_ZN5wagmi8instance8dispatch17h278853d1093abebfE), !dbg !34024
24982:  musttail call void %handler.i(ptr noalias noundef nonnull readonly sret([24 x i8]) align 8 captures(address) dereferenceable(128) %9, ptr noalias noundef nonnull readonly align 8 captures(address, read_provenance) dereferenceable(128) %17, i64 noundef %18, ptr noalias noundef nonnull align 8 dereferenceable(24) %func_bases, ptr noalias noundef nonnull align 8 dereferenceable(24) %ctrl_bases, ptr noalias noundef align 8 dereferenceable(24) @_ZN5wagmi8instance8dispatch17h278853d1093abebfE), !dbg !34309
25112:  musttail call void %handler.i(ptr noalias noundef nonnull readonly sret([24 x i8]) align 8 captures(address) dereferenceable(128) %6, ptr noalias noundef nonnull readonly align 8 captures(address, read_provenance) dereferenceable(128) %14, i64 noundef %15, ptr noalias noundef nonnull align 8 dereferenceable(24) %func_bases, ptr noalias noundef nonnull align 8 dereferenceable(24) %ctrl_bases, ptr noalias noundef align 8 dereferenceable(24) @_ZN5wagmi8instance8dispatch17h278853d1093abebfE), !dbg !34511
25297:  musttail call void %handler.i(ptr noalias noundef nonnull readonly sret([24 x i8]) align 8 captures(address) dereferenceable(128) %9, ptr noalias noundef nonnull readonly align 8 captures(address, read_provenance) dereferenceable(128) %17, i64 noundef %18, ptr noalias noundef nonnull align 8 dereferenceable(24) %func_bases, ptr noalias noundef nonnull align 8 dereferenceable(24) %ctrl_bases, ptr noalias noundef align 8 dereferenceable(24) @_ZN5wagmi8instance8dispatch17h278853d1093abebfE), !dbg !34753
25482:  musttail call void %handler.i(ptr noalias noundef nonnull readonly sret([24 x i8]) align 8 captures(address) dereferenceable(128) %9, ptr noalias noundef nonnull readonly align 8 captures(address, read_provenance) dereferenceable(128) %17, i64 noundef %18, ptr noalias noundef nonnull align 8 dereferenceable(24) %func_bases, ptr noalias noundef nonnull align 8 dereferenceable(24) %ctrl_bases, ptr noalias noundef align 8 dereferenceable(24) @_ZN5wagmi8instance8dispatch17h278853d1093abebfE), !dbg !34995
25763:  musttail call void %handler.i(ptr noalias noundef nonnull readonly sret([24 x i8]) align 8 captures(address) dereferenceable(128) %15, ptr noalias noundef nonnull readonly align 8 captures(address, read_provenance) dereferenceable(128) %23, i64 noundef %24, ptr noalias noundef nonnull align 8 dereferenceable(24) %func_bases, ptr noalias noundef nonnull align 8 dereferenceable(24) %ctrl_bases, ptr noalias noundef align 8 dereferenceable(24) @_ZN5wagmi8instance8dispatch17h278853d1093abebfE), !dbg !35350
26044:  musttail call void %handler.i(ptr noalias noundef nonnull readonly sret([24 x i8]) align 8 captures(address) dereferenceable(128) %14, ptr noalias noundef nonnull readonly align 8 captures(address, read_provenance) dereferenceable(128) %22, i64 noundef %23, ptr noalias noundef nonnull align 8 dereferenceable(24) %func_bases, ptr noalias noundef nonnull align 8 dereferenceable(24) %ctrl_bases, ptr noalias noundef align 8 dereferenceable(24) @_ZN5wagmi8instance8dispatch17h278853d1093abebfE), !dbg !35691
26229:  musttail call void %handler.i(ptr noalias noundef nonnull readonly sret([24 x i8]) align 8 captures(address) dereferenceable(128) %9, ptr noalias noundef nonnull readonly align 8 captures(address, read_provenance) dereferenceable(128) %17, i64 noundef %18, ptr noalias noundef nonnull align 8 dereferenceable(24) %func_bases, ptr noalias noundef nonnull align 8 dereferenceable(24) %ctrl_bases, ptr noalias noundef align 8 dereferenceable(24) @_ZN5wagmi8instance8dispatch17h278853d1093abebfE), !dbg !35933
26358:  musttail call void %handler.i(ptr noalias noundef nonnull readonly sret([24 x i8]) align 8 captures(address) dereferenceable(128) %5, ptr noalias noundef nonnull readonly align 8 captures(address, read_provenance) dereferenceable(128) %13, i64 noundef %14, ptr noalias noundef nonnull align 8 dereferenceable(24) %func_bases, ptr noalias noundef nonnull align 8 dereferenceable(24) %ctrl_bases, ptr noalias noundef align 8 dereferenceable(24) @_ZN5wagmi8instance8dispatch17h278853d1093abebfE), !dbg !36124
26543:  musttail call void %handler.i(ptr noalias noundef nonnull readonly sret([24 x i8]) align 8 captures(address) dereferenceable(128) %9, ptr noalias noundef nonnull readonly align 8 captures(address, read_provenance) dereferenceable(128) %17, i64 noundef %18, ptr noalias noundef nonnull align 8 dereferenceable(24) %func_bases, ptr noalias noundef nonnull align 8 dereferenceable(24) %ctrl_bases, ptr noalias noundef align 8 dereferenceable(24) @_ZN5wagmi8instance8dispatch17h278853d1093abebfE), !dbg !36366
26734:  musttail call void %handler.i(ptr noalias noundef nonnull readonly sret([24 x i8]) align 8 captures(address) dereferenceable(128) %9, ptr noalias noundef nonnull readonly align 8 captures(address, read_provenance) dereferenceable(128) %17, i64 noundef %18, ptr noalias noundef nonnull align 8 dereferenceable(24) %func_bases, ptr noalias noundef nonnull align 8 dereferenceable(24) %ctrl_bases, ptr noalias noundef align 8 dereferenceable(24) @_ZN5wagmi8instance8dispatch17h278853d1093abebfE), !dbg !36621
26922:  musttail call void %handler.i(ptr noalias noundef nonnull readonly sret([24 x i8]) align 8 captures(address) dereferenceable(128) %9, ptr noalias noundef nonnull readonly align 8 captures(address, read_provenance) dereferenceable(128) %17, i64 noundef %18, ptr noalias noundef nonnull align 8 dereferenceable(24) %func_bases, ptr noalias noundef nonnull align 8 dereferenceable(24) %ctrl_bases, ptr noalias noundef align 8 dereferenceable(24) @_ZN5wagmi8instance8dispatch17h278853d1093abebfE), !dbg !36869
27056:  musttail call void %handler.i(ptr noalias noundef nonnull readonly sret([24 x i8]) align 8 captures(address) dereferenceable(128) %6, ptr noalias noundef nonnull readonly align 8 captures(address, read_provenance) dereferenceable(128) %14, i64 noundef %15, ptr noalias noundef nonnull align 8 dereferenceable(24) %func_bases, ptr noalias noundef nonnull align 8 dereferenceable(24) %ctrl_bases, ptr noalias noundef align 8 dereferenceable(24) @_ZN5wagmi8instance8dispatch17h278853d1093abebfE), !dbg !37080
27190:  musttail call void %handler.i(ptr noalias noundef nonnull readonly sret([24 x i8]) align 8 captures(address) dereferenceable(128) %6, ptr noalias noundef nonnull readonly align 8 captures(address, read_provenance) dereferenceable(128) %14, i64 noundef %15, ptr noalias noundef nonnull align 8 dereferenceable(24) %func_bases, ptr noalias noundef nonnull align 8 dereferenceable(24) %ctrl_bases, ptr noalias noundef align 8 dereferenceable(24) @_ZN5wagmi8instance8dispatch17h278853d1093abebfE), !dbg !37288
27322:  musttail call void %handler.i(ptr noalias noundef nonnull readonly sret([24 x i8]) align 8 captures(address) dereferenceable(128) %6, ptr noalias noundef nonnull readonly align 8 captures(address, read_provenance) dereferenceable(128) %14, i64 noundef %15, ptr noalias noundef nonnull align 8 dereferenceable(24) %func_bases, ptr noalias noundef nonnull align 8 dereferenceable(24) %ctrl_bases, ptr noalias noundef align 8 dereferenceable(24) @_ZN5wagmi8instance8dispatch17h278853d1093abebfE), !dbg !37485
27513:  musttail call void %handler.i(ptr noalias noundef nonnull readonly sret([24 x i8]) align 8 captures(address) dereferenceable(128) %9, ptr noalias noundef nonnull readonly align 8 captures(address, read_provenance) dereferenceable(128) %17, i64 noundef %18, ptr noalias noundef nonnull align 8 dereferenceable(24) %func_bases, ptr noalias noundef nonnull align 8 dereferenceable(24) %ctrl_bases, ptr noalias noundef align 8 dereferenceable(24) @_ZN5wagmi8instance8dispatch17h278853d1093abebfE), !dbg !37739
27706:  musttail call void %handler.i(ptr noalias noundef nonnull readonly sret([24 x i8]) align 8 captures(address) dereferenceable(128) %9, ptr noalias noundef nonnull readonly align 8 captures(address, read_provenance) dereferenceable(128) %17, i64 noundef %18, ptr noalias noundef nonnull align 8 dereferenceable(24) %func_bases, ptr noalias noundef nonnull align 8 dereferenceable(24) %ctrl_bases, ptr noalias noundef align 8 dereferenceable(24) @_ZN5wagmi8instance8dispatch17h278853d1093abebfE), !dbg !37993
27897:  musttail call void %handler.i(ptr noalias noundef nonnull readonly sret([24 x i8]) align 8 captures(address) dereferenceable(128) %9, ptr noalias noundef nonnull readonly align 8 captures(address, read_provenance) dereferenceable(128) %17, i64 noundef %18, ptr noalias noundef nonnull align 8 dereferenceable(24) %func_bases, ptr noalias noundef nonnull align 8 dereferenceable(24) %ctrl_bases, ptr noalias noundef align 8 dereferenceable(24) @_ZN5wagmi8instance8dispatch17h278853d1093abebfE), !dbg !38247
28085:  musttail call void %handler.i(ptr noalias noundef nonnull readonly sret([24 x i8]) align 8 captures(address) dereferenceable(128) %9, ptr noalias noundef nonnull readonly align 8 captures(address, read_provenance) dereferenceable(128) %17, i64 noundef %18, ptr noalias noundef nonnull align 8 dereferenceable(24) %func_bases, ptr noalias noundef nonnull align 8 dereferenceable(24) %ctrl_bases, ptr noalias noundef align 8 dereferenceable(24) @_ZN5wagmi8instance8dispatch17h278853d1093abebfE), !dbg !38495
28274:  musttail call void %handler.i(ptr noalias noundef nonnull readonly sret([24 x i8]) align 8 captures(address) dereferenceable(128) %9, ptr noalias noundef nonnull readonly align 8 captures(address, read_provenance) dereferenceable(128) %17, i64 noundef %18, ptr noalias noundef nonnull align 8 dereferenceable(24) %func_bases, ptr noalias noundef nonnull align 8 dereferenceable(24) %ctrl_bases, ptr noalias noundef align 8 dereferenceable(24) @_ZN5wagmi8instance8dispatch17h278853d1093abebfE), !dbg !38743
28460:  musttail call void %handler.i(ptr noalias noundef nonnull readonly sret([24 x i8]) align 8 captures(address) dereferenceable(128) %9, ptr noalias noundef nonnull readonly align 8 captures(address, read_provenance) dereferenceable(128) %17, i64 noundef %18, ptr noalias noundef nonnull align 8 dereferenceable(24) %func_bases, ptr noalias noundef nonnull align 8 dereferenceable(24) %ctrl_bases, ptr noalias noundef align 8 dereferenceable(24) @_ZN5wagmi8instance8dispatch17h278853d1093abebfE), !dbg !38985
28590:  musttail call void %handler.i(ptr noalias noundef nonnull readonly sret([24 x i8]) align 8 captures(address) dereferenceable(128) %6, ptr noalias noundef nonnull readonly align 8 captures(address, read_provenance) dereferenceable(128) %14, i64 noundef %15, ptr noalias noundef nonnull align 8 dereferenceable(24) %func_bases, ptr noalias noundef nonnull align 8 dereferenceable(24) %ctrl_bases, ptr noalias noundef align 8 dereferenceable(24) @_ZN5wagmi8instance8dispatch17h278853d1093abebfE), !dbg !39183
28720:  musttail call void %handler.i(ptr noalias noundef nonnull readonly sret([24 x i8]) align 8 captures(address) dereferenceable(128) %6, ptr noalias noundef nonnull readonly align 8 captures(address, read_provenance) dereferenceable(128) %14, i64 noundef %15, ptr noalias noundef nonnull align 8 dereferenceable(24) %func_bases, ptr noalias noundef nonnull align 8 dereferenceable(24) %ctrl_bases, ptr noalias noundef align 8 dereferenceable(24) @_ZN5wagmi8instance8dispatch17h278853d1093abebfE), !dbg !39379
28849:  musttail call void %handler.i(ptr noalias noundef nonnull readonly sret([24 x i8]) align 8 captures(address) dereferenceable(128) %5, ptr noalias noundef nonnull readonly align 8 captures(address, read_provenance) dereferenceable(128) %13, i64 noundef %14, ptr noalias noundef nonnull align 8 dereferenceable(24) %func_bases, ptr noalias noundef nonnull align 8 dereferenceable(24) %ctrl_bases, ptr noalias noundef align 8 dereferenceable(24) @_ZN5wagmi8instance8dispatch17h278853d1093abebfE), !dbg !39563
29038:  musttail call void %handler.i(ptr noalias noundef nonnull readonly sret([24 x i8]) align 8 captures(address) dereferenceable(128) %9, ptr noalias noundef nonnull readonly align 8 captures(address, read_provenance) dereferenceable(128) %17, i64 noundef %18, ptr noalias noundef nonnull align 8 dereferenceable(24) %func_bases, ptr noalias noundef nonnull align 8 dereferenceable(24) %ctrl_bases, ptr noalias noundef align 8 dereferenceable(24) @_ZN5wagmi8instance8dispatch17h278853d1093abebfE), !dbg !39811
29224:  musttail call void %handler.i(ptr noalias noundef nonnull readonly sret([24 x i8]) align 8 captures(address) dereferenceable(128) %9, ptr noalias noundef nonnull readonly align 8 captures(address, read_provenance) dereferenceable(128) %17, i64 noundef %18, ptr noalias noundef nonnull align 8 dereferenceable(24) %func_bases, ptr noalias noundef nonnull align 8 dereferenceable(24) %ctrl_bases, ptr noalias noundef align 8 dereferenceable(24) @_ZN5wagmi8instance8dispatch17h278853d1093abebfE), !dbg !40050
29413:  musttail call void %handler.i(ptr noalias noundef nonnull readonly sret([24 x i8]) align 8 captures(address) dereferenceable(128) %9, ptr noalias noundef nonnull readonly align 8 captures(address, read_provenance) dereferenceable(128) %17, i64 noundef %18, ptr noalias noundef nonnull align 8 dereferenceable(24) %func_bases, ptr noalias noundef nonnull align 8 dereferenceable(24) %ctrl_bases, ptr noalias noundef align 8 dereferenceable(24) @_ZN5wagmi8instance8dispatch17h278853d1093abebfE), !dbg !40298
29599:  musttail call void %handler.i(ptr noalias noundef nonnull readonly sret([24 x i8]) align 8 captures(address) dereferenceable(128) %9, ptr noalias noundef nonnull readonly align 8 captures(address, read_provenance) dereferenceable(128) %17, i64 noundef %18, ptr noalias noundef nonnull align 8 dereferenceable(24) %func_bases, ptr noalias noundef nonnull align 8 dereferenceable(24) %ctrl_bases, ptr noalias noundef align 8 dereferenceable(24) @_ZN5wagmi8instance8dispatch17h278853d1093abebfE), !dbg !40540
30044:  musttail call void %handler.i(ptr noalias noundef nonnull readonly sret([24 x i8]) align 8 captures(address) dereferenceable(128) %36, ptr noalias noundef nonnull readonly align 8 captures(address, read_provenance) dereferenceable(128) %44, i64 noundef %45, ptr noalias noundef nonnull align 8 dereferenceable(24) %func_bases, ptr noalias noundef nonnull align 8 dereferenceable(24) %ctrl_bases, ptr noalias noundef align 8 dereferenceable(24) @_ZN5wagmi8instance8dispatch17h278853d1093abebfE), !dbg !41230
30215:  musttail call void %handler.i(ptr noalias noundef nonnull readonly sret([24 x i8]) align 8 captures(address) dereferenceable(128) %6, ptr noalias noundef nonnull readonly align 8 captures(address, read_provenance) dereferenceable(128) %14, i64 noundef %15, ptr noalias noundef nonnull align 8 dereferenceable(24) %func_bases, ptr noalias noundef nonnull align 8 dereferenceable(24) %ctrl_bases, ptr noalias noundef align 8 dereferenceable(24) @_ZN5wagmi8instance8dispatch17h278853d1093abebfE), !dbg !41481
30702:  musttail call void %handler.i(ptr noalias noundef nonnull readonly sret([24 x i8]) align 8 captures(address) dereferenceable(128) %29, ptr noalias noundef nonnull readonly align 8 captures(address, read_provenance) dereferenceable(128) %37, i64 noundef %38, ptr noalias noundef nonnull align 8 dereferenceable(24) %func_bases, ptr noalias noundef nonnull align 8 dereferenceable(24) %ctrl_bases, ptr noalias noundef align 8 dereferenceable(24) @_ZN5wagmi8instance8dispatch17h278853d1093abebfE), !dbg !42412
30843:  musttail call void %handler.i(ptr noalias noundef nonnull readonly sret([24 x i8]) align 8 captures(address) dereferenceable(128) %6, ptr noalias noundef nonnull readonly align 8 captures(address, read_provenance) dereferenceable(128) %14, i64 noundef %15, ptr noalias noundef nonnull align 8 dereferenceable(24) %func_bases, ptr noalias noundef nonnull align 8 dereferenceable(24) %ctrl_bases, ptr noalias noundef align 8 dereferenceable(24) @_ZN5wagmi8instance8dispatch17h278853d1093abebfE), !dbg !42647
30974:  musttail call void %handler.i(ptr noalias noundef nonnull readonly sret([24 x i8]) align 8 captures(address) dereferenceable(128) %6, ptr noalias noundef nonnull readonly align 8 captures(address, read_provenance) dereferenceable(128) %14, i64 noundef %15, ptr noalias noundef nonnull align 8 dereferenceable(24) %func_bases, ptr noalias noundef nonnull align 8 dereferenceable(24) %ctrl_bases, ptr noalias noundef align 8 dereferenceable(24) @_ZN5wagmi8instance8dispatch17h278853d1093abebfE), !dbg !42852
31445:  musttail call void %handler.i(ptr noalias noundef nonnull readonly sret([24 x i8]) align 8 captures(address) dereferenceable(128) %31, ptr noalias noundef nonnull readonly align 8 captures(address, read_provenance) dereferenceable(128) %39, i64 noundef %40, ptr noalias noundef nonnull align 8 dereferenceable(24) %func_bases, ptr noalias noundef nonnull align 8 dereferenceable(24) %ctrl_bases, ptr noalias noundef align 8 dereferenceable(24) @_ZN5wagmi8instance8dispatch17h278853d1093abebfE), !dbg !43600
31576:  musttail call void %handler.i(ptr noalias noundef nonnull readonly sret([24 x i8]) align 8 captures(address) dereferenceable(128) %6, ptr noalias noundef nonnull readonly align 8 captures(address, read_provenance) dereferenceable(128) %14, i64 noundef %15, ptr noalias noundef nonnull align 8 dereferenceable(24) %func_bases, ptr noalias noundef nonnull align 8 dereferenceable(24) %ctrl_bases, ptr noalias noundef align 8 dereferenceable(24) @_ZN5wagmi8instance8dispatch17h278853d1093abebfE), !dbg !43801
31770:  musttail call void %handler.i(ptr noalias noundef nonnull readonly sret([24 x i8]) align 8 captures(address) dereferenceable(128) %9, ptr noalias noundef nonnull readonly align 8 captures(address, read_provenance) dereferenceable(128) %17, i64 noundef %18, ptr noalias noundef nonnull align 8 dereferenceable(24) %func_bases, ptr noalias noundef nonnull align 8 dereferenceable(24) %ctrl_bases, ptr noalias noundef align 8 dereferenceable(24) @_ZN5wagmi8instance8dispatch17h278853d1093abebfE), !dbg !44061
31964:  musttail call void %handler.i(ptr noalias noundef nonnull readonly sret([24 x i8]) align 8 captures(address) dereferenceable(128) %9, ptr noalias noundef nonnull readonly align 8 captures(address, read_provenance) dereferenceable(128) %17, i64 noundef %18, ptr noalias noundef nonnull align 8 dereferenceable(24) %func_bases, ptr noalias noundef nonnull align 8 dereferenceable(24) %ctrl_bases, ptr noalias noundef align 8 dereferenceable(24) @_ZN5wagmi8instance8dispatch17h278853d1093abebfE), !dbg !44318
32158:  musttail call void %handler.i(ptr noalias noundef nonnull readonly sret([24 x i8]) align 8 captures(address) dereferenceable(128) %9, ptr noalias noundef nonnull readonly align 8 captures(address, read_provenance) dereferenceable(128) %17, i64 noundef %18, ptr noalias noundef nonnull align 8 dereferenceable(24) %func_bases, ptr noalias noundef nonnull align 8 dereferenceable(24) %ctrl_bases, ptr noalias noundef align 8 dereferenceable(24) @_ZN5wagmi8instance8dispatch17h278853d1093abebfE), !dbg !44575
32352:  musttail call void %handler.i(ptr noalias noundef nonnull readonly sret([24 x i8]) align 8 captures(address) dereferenceable(128) %9, ptr noalias noundef nonnull readonly align 8 captures(address, read_provenance) dereferenceable(128) %17, i64 noundef %18, ptr noalias noundef nonnull align 8 dereferenceable(24) %func_bases, ptr noalias noundef nonnull align 8 dereferenceable(24) %ctrl_bases, ptr noalias noundef align 8 dereferenceable(24) @_ZN5wagmi8instance8dispatch17h278853d1093abebfE), !dbg !44832
32546:  musttail call void %handler.i(ptr noalias noundef nonnull readonly sret([24 x i8]) align 8 captures(address) dereferenceable(128) %9, ptr noalias noundef nonnull readonly align 8 captures(address, read_provenance) dereferenceable(128) %17, i64 noundef %18, ptr noalias noundef nonnull align 8 dereferenceable(24) %func_bases, ptr noalias noundef nonnull align 8 dereferenceable(24) %ctrl_bases, ptr noalias noundef align 8 dereferenceable(24) @_ZN5wagmi8instance8dispatch17h278853d1093abebfE), !dbg !45089
32740:  musttail call void %handler.i(ptr noalias noundef nonnull readonly sret([24 x i8]) align 8 captures(address) dereferenceable(128) %9, ptr noalias noundef nonnull readonly align 8 captures(address, read_provenance) dereferenceable(128) %17, i64 noundef %18, ptr noalias noundef nonnull align 8 dereferenceable(24) %func_bases, ptr noalias noundef nonnull align 8 dereferenceable(24) %ctrl_bases, ptr noalias noundef align 8 dereferenceable(24) @_ZN5wagmi8instance8dispatch17h278853d1093abebfE), !dbg !45346
33226:  musttail call void %handler.i(ptr noalias noundef nonnull readonly sret([24 x i8]) align 8 captures(address) dereferenceable(128) %29, ptr noalias noundef nonnull readonly align 8 captures(address, read_provenance) dereferenceable(128) %37, i64 noundef %38, ptr noalias noundef nonnull align 8 dereferenceable(24) %func_bases, ptr noalias noundef nonnull align 8 dereferenceable(24) %ctrl_bases, ptr noalias noundef align 8 dereferenceable(24) @_ZN5wagmi8instance8dispatch17h278853d1093abebfE), !dbg !46000
33420:  musttail call void %handler.i(ptr noalias noundef nonnull readonly sret([24 x i8]) align 8 captures(address) dereferenceable(128) %9, ptr noalias noundef nonnull readonly align 8 captures(address, read_provenance) dereferenceable(128) %17, i64 noundef %18, ptr noalias noundef nonnull align 8 dereferenceable(24) %func_bases, ptr noalias noundef nonnull align 8 dereferenceable(24) %ctrl_bases, ptr noalias noundef align 8 dereferenceable(24) @_ZN5wagmi8instance8dispatch17h278853d1093abebfE), !dbg !46257
33614:  musttail call void %handler.i(ptr noalias noundef nonnull readonly sret([24 x i8]) align 8 captures(address) dereferenceable(128) %9, ptr noalias noundef nonnull readonly align 8 captures(address, read_provenance) dereferenceable(128) %17, i64 noundef %18, ptr noalias noundef nonnull align 8 dereferenceable(24) %func_bases, ptr noalias noundef nonnull align 8 dereferenceable(24) %ctrl_bases, ptr noalias noundef align 8 dereferenceable(24) @_ZN5wagmi8instance8dispatch17h278853d1093abebfE), !dbg !46514
33809:  musttail call void %handler.i(ptr noalias noundef nonnull readonly sret([24 x i8]) align 8 captures(address) dereferenceable(128) %10, ptr noalias noundef nonnull readonly align 8 captures(address, read_provenance) dereferenceable(128) %18, i64 noundef %19, ptr noalias noundef nonnull align 8 dereferenceable(24) %func_bases, ptr noalias noundef nonnull align 8 dereferenceable(24) %ctrl_bases, ptr noalias noundef align 8 dereferenceable(24) @_ZN5wagmi8instance8dispatch17h278853d1093abebfE), !dbg !46774
34004:  musttail call void %handler.i(ptr noalias noundef nonnull readonly sret([24 x i8]) align 8 captures(address) dereferenceable(128) %10, ptr noalias noundef nonnull readonly align 8 captures(address, read_provenance) dereferenceable(128) %18, i64 noundef %19, ptr noalias noundef nonnull align 8 dereferenceable(24) %func_bases, ptr noalias noundef nonnull align 8 dereferenceable(24) %ctrl_bases, ptr noalias noundef align 8 dereferenceable(24) @_ZN5wagmi8instance8dispatch17h278853d1093abebfE), !dbg !47034
...
```

</details>

### LINKED ISSUE #148239: explicit_tail_calls misorders sret argument, breaking ABI for `become` calls
I am not sure if this is an ICE (the compilation is successful but running the code causes invalid memory access) I tried this code:

```rust
#![feature(explicit_tail_calls)]

#[derive(Default)]
struct Instance {
    bytes: Vec<u8>,
}

#[derive(Default)]
struct Stack;
#[derive(Default)]
struct Control;
#[derive(Default)]
struct Bases;

#[derive(Clone, Copy)]
struct Error([u8; 24]);

type Handler = fn(
    &Instance,
    usize,
    &mut Stack,
    &mut Control,
    &mut Bases,
    &mut Bases,
) -> Result<(), Error>;

#[inline(never)]
fn op_dummy(
    _instance: &Instance,
    _pc: usize,
    _stack: &mut Stack,
    _control: &mut Control,
    _func_bases: &mut Bases,
    _ctrl_bases: &mut Bases,
) -> Result<(), Error> {
    Err(Error([1; 24]))
}

static HANDLERS: [Handler; 1] = [op_dummy];

#[inline(never)]
fn dispatch(
    instance: &Instance,
    pc: usize,
    stack: &mut Stack,
    control: &mut Control,
    func_bases: &mut Bases,
    ctrl_bases: &mut Bases,
) -> Result<(), Error> {
    let opcode = 0u8;
    let next_pc = pc + opcode as usize;
    become HANDLERS[opcode as usize](instance, next_pc, stack, control, func_bases, ctrl_bases)
}

fn main() {
    let instance = Instance { bytes: vec![0] };
    let mut stack = Stack::default();
    let mut control = Control::default();
    let mut func_bases = Bases::default();
    let mut ctrl_bases = Bases::default();
    let result = dispatch(&instance, 0, &mut stack, &mut control, &mut func_bases, &mut ctrl_bases);
    eprintln!("dispatch returned: {:?}", result.is_ok());
}
```

I expected to see this happen: at the bare minimum, it should not crash.

Instead, this happened (other memory errors can happen, but this minimal reproduction has this): 
```
dispatch returned: true
minimal_tail_bin(44100,0x204b46140) malloc: *** error for object 0x101010101010101: pointer being freed was not allocated
minimal_tail_bin(44100,0x204b46140) malloc: *** set a breakpoint in malloc_error_break to debug
[1]    44100 abort      ./tmp/minimal_tail_bin
```

### Meta

`rustc +nightly --version --verbose`:
```
rustc 1.93.0-nightly (278a90913 2025-10-28)
binary: rustc
commit-hash: 278a90913daf7707791020a592d722dd7971f196
commit-date: 2025-10-28
host: aarch64-apple-darwin
release: 1.93.0-nightly
LLVM version: 21.1.3
```

<details><summary>Backtrace (no panic so using lldb)</summary>
<p>

```
➜  wagmi git:(tail) ✗ lldb ./tmp/minimal_tail_bin
(lldb) target create "./tmp/minimal_tail_bin"
Current executable set to '/Users/mark/Desktop/github/wagmi/tmp/minimal_tail_bin' (arm64).
(lldb) run
(lldb) bt
* thread #1, name = 'main', queue = 'com.apple.main-thread', stop reason = signal SIGABRT
  * frame #0: 0x0000000196bb2388 libsystem_kernel.dylib`__pthread_kill + 8
    frame #1: 0x0000000196beb848 libsystem_pthread.dylib`pthread_kill + 296
    frame #2: 0x0000000196af49e4 libsystem_c.dylib`abort + 124
    frame #3: 0x00000001969f8174 libsystem_malloc.dylib`malloc_vreport + 892
    frame #4: 0x00000001969fbc90 libsystem_malloc.dylib`malloc_report + 64
    frame #5: 0x0000000196a0021c libsystem_malloc.dylib`___BUG_IN_CLIENT_OF_LIBMALLOC_POINTER_BEING_FREED_WAS_NOT_ALLOCATED + 32
    frame #6: 0x0000000100000c5c minimal_tail_bin`core::ptr::drop_in_place$LT$alloc..raw_vec..RawVec$LT$u8$GT$$GT$::h4bd847816a4750fa + 12
    frame #7: 0x0000000100000c38 minimal_tail_bin`core::ptr::drop_in_place$LT$alloc..vec..Vec$LT$u8$GT$$GT$::h5f9070da464d00f0 + 60
    frame #8: 0x0000000100000bf4 minimal_tail_bin`core::ptr::drop_in_place$LT$minimal_tail..Instance$GT$::he8bdfbeda8fdd895 + 12
    frame #9: 0x00000001000009a8 minimal_tail_bin`minimal_tail::main::h50e25767feace6ee + 288
    frame #10: 0x0000000100000b90 minimal_tail_bin`core::ops::function::FnOnce::call_once::h5557aeb42d126e1f + 16
    frame #11: 0x0000000100000ae4 minimal_tail_bin`std::sys::backtrace::__rust_begin_short_backtrace::h48b7c738fea099aa + 12
    frame #12: 0x0000000100000ac8 minimal_tail_bin`std::rt::lang_start::_$u7b$$u7b$closure$u7d$$u7d$::hbcf70399e5365f1a + 16
    frame #13: 0x0000000100008d4c minimal_tail_bin`core::ops::function::impls::_$LT$impl$u20$core..ops..function..FnOnce$LT$A$GT$$u20$for$u20$$RF$F$GT$::call_once::h53a415d597411a63 at function.rs:287:21 [opt] [inlined]
    frame #14: 0x0000000100008d44 minimal_tail_bin`std::panicking::catch_unwind::do_call::hdf550c281fdcb7e4 at panicking.rs:590:40 [opt] [inlined]
    frame #15: 0x0000000100008d40 minimal_tail_bin`std::panicking::catch_unwind::h1357aa3b9f9f23d0 at panicking.rs:553:19 [opt] [inlined]
    frame #16: 0x0000000100008d40 minimal_tail_bin`std::panic::catch_unwind::h4f55fe568389ccc1 at panic.rs:359:14 [opt] [inlined]
    frame #17: 0x0000000100008d40 minimal_tail_bin`std::rt::lang_start_internal::_$u7b$$u7b$closure$u7d$$u7d$::hf4ba1b7953ccb8d3 at rt.rs:175:24 [opt] [inlined]
    frame #18: 0x0000000100008970 minimal_tail_bin`std::panicking::catch_unwind::do_call::h83012b9119ac28e0 at panicking.rs:590:40 [opt] [inlined]
    frame #19: 0x0000000100008970 minimal_tail_bin`std::panicking::catch_unwind::h857551789dca2cb6 at panicking.rs:553:19 [opt] [inlined]
    frame #20: 0x0000000100008970 minimal_tail_bin`std::panic::catch_unwind::hd425c1766906aced at panic.rs:359:14 [opt] [inlined]
    frame #21: 0x0000000100008970 minimal_tail_bin`std::rt::lang_start_internal::h5aea9edca65f5711 at rt.rs:171:5 [opt]
    frame #22: 0x0000000100000aac minimal_tail_bin`std::rt::lang_start::h372fdb6c50762ee6 + 60
    frame #23: 0x00000001000010ac minimal_tail_bin`main + 36
    frame #24: 0x000000019684ab98 dyld`start + 6076
```

</p>
</details>

More info: if you change `become` to `return` it behaves normally, IR:
```
  define internal void @_ZN19minimal_tail_return8dispatch17h5f0bc40cbbb7273fE(
      ptr sret([25 x i8]) align 1 %_0,
      ptr align 8 %instance,
      i64 %pc,
      ptr align 1 %stack,
      ptr align 1 %control,
      ptr align 1 %func_bases,
      ptr align 1 %ctrl_bases
  ) unnamed_addr #1 {
  start:
    %_10.0 = add i64 %pc, 0
    %_10.1 = icmp ult i64 %_10.0, %pc
    br i1 %_10.1, label %panic, label %bb1

  bb1:
    %_11 = load ptr, ptr @_ZN19minimal_tail_return8HANDLERS17h2eb1f46685216284E,
  align 8
    call void %_11(ptr sret([25 x i8]) align 1 %_0,
                   ptr align 8 %instance,
                   i64 %_10.0,
                   ptr align 1 %stack,
                   ptr align 1 %control,
                   ptr align 1 %func_bases,
                   ptr align 1 %ctrl_bases)
    ret void
```

But when you do `become` it is now an ABI mismatch (line 116-129):

```
; minimal_tail::dispatch
; Function Attrs: noinline uwtable
define internal void @_ZN12minimal_tail8dispatch17h0f2db7a170a13413E(ptr sret([25 x i8]) align 1 %_0, ptr align 8 %instance, i64 %pc, ptr align 1 %stack, ptr align 1 %control, ptr align 1 %func_bases, ptr align 1 %ctrl_bases) unnamed_addr #1 {
start:
  %_10.0 = add i64 %pc, 0
  %_10.1 = icmp ult i64 %_10.0, %pc
  br i1 %_10.1, label %panic, label %bb1

bb1:                                              ; preds = %start
  %_11 = load ptr, ptr @_ZN12minimal_tail8HANDLERS17h844a04c0bd8adf43E, align 8
  %0 = bitcast i64 %_10.0 to ptr
  %1 = bitcast ptr %stack to i64
  musttail call void %_11(ptr sret([25 x i8]) align 1 %instance, ptr align 8 %0, i64 %1, ptr align 1 %control, ptr align 1 %func_bases, ptr align 1 %ctrl_bases)
  ret void

```

[minimal_tail.ll.txt](https://github.com/user-attachments/files/23201108/minimal_tail.ll.txt)

### PR DESCRIPTION
**Pull request by InvalidPathException**
Fixes rust-lang/rust#148239 https://github.com/rust-lang/rust/issues/144986

Explicit tail calls trigger `bug!` for any callee whose ABI returns via `PassMode::Cast`, and we forgot to to forward the hidden `sret` out-pointer when the ABI requested an indirect return. The former causes ICE, the latter produced malformed IR (wrong codegen) if the return value is large enough to need `sret`. 

Updated the musttail helper to accept cast-mode returns, made it so that we pass the return pointer through the tail-call path.

Added two UI tests to demonstrate each case.

This is my first time contributing, please do check if I did it right.

r? theemathas

### CODE REVIEW

**Comment by WaffleLapkin** [comment]
The best practice I'm usually trying to follow is: add tests in a separate commit (and make them "pass" there, possibly with known bug annotations, etc). That way the second commit with the impl clearly shows how the behavior changed, in the tests' diff.

If you have time I'd recommend you do the same here (tip: [jj](https://jj-vcs.github.io) makes splitting/modifying commits easy).

And congrats on your first contribution! I'll try to review your PR shortly :)

File: tests/ui/explicit-tail-calls/become-cast-return.rs [hunk 1]
```diff
@@ -0,0 +1,19 @@
+//@ check-pass
+#![allow(incomplete_features)]
```
Comment (WaffleLapkin) [inline tests/ui/explicit-tail-calls/become-cast-return.rs]: please use `expect` instead, so that we remember to remoce this when the feature stops being incomplete.

File: compiler/rustc_codegen_ssa/src/mir/block.rs [hunk 2]
```diff
@@ -1055,6 +1055,15 @@ impl<'a, 'tcx, Bx: BuilderMethods<'a, 'tcx>> FunctionCx<'a, 'tcx, Bx> {
...
         let mut llargs = Vec::with_capacity(arg_count);
 
+        if kind == CallKind::Tail && fn_abi.ret.is_indirect() {
+            match self.make_return_dest(bx, destination, &fn_abi.ret, &mut llargs) {
+                ReturnDest::Nothing => {}
+                _ => bug!(
+                    "tail calls to functions with indirect returns cannot store into a destination"
+                ),
+            }
+        }
```
Comment (bjorn3) [inline compiler/rustc_codegen_ssa/src/mir/block.rs]: Any reason to not merge this into the `match kind` below that does `make_return_dest` for the non-tail call case already?

File: compiler/rustc_codegen_ssa/src/mir/block.rs [hunk 3]
```diff
@@ -1055,6 +1055,15 @@ impl<'a, 'tcx, Bx: BuilderMethods<'a, 'tcx>> FunctionCx<'a, 'tcx, Bx> {
 
         let mut llargs = Vec::with_capacity(arg_count);
 
+        if kind == CallKind::Tail && fn_abi.ret.is_indirect() {
+            match self.make_return_dest(bx, destination, &fn_abi.ret, &mut llargs) {
+                ReturnDest::Nothing => {}
+                _ => bug!(
+                    "tail calls to functions with indirect returns cannot store into a destination"
+                ),
```
Comment (bjorn3) [inline compiler/rustc_codegen_ssa/src/mir/block.rs]: I think this is correct. `make_return_dest` only returns something other than `ReturnDest::Nothing` for indirect returns when the destination is an `LocalRef::PendingOperand`, but `_0` should be a `LocalRef::Place` for indirect returns and tail calls shouldn't use any destination other than `_0`.

**Comment by InvalidPathException** [comment]
> The best practice I'm usually trying to follow is: add tests in a separate commit (and make them "pass" there, possibly with known bug annotations, etc). That way the second commit with the impl clearly shows how the behavior changed, in the tests' diff.
> 
> 
> 
> If you have time I'd recommend you do the same here (tip: [jj](https://jj-vcs.github.io) makes splitting/modifying commits easy).
> 
> 
> 
> And congrats on your first contribution! I'll try to review your PR shortly :)

How can we properly test this if `run-pass` causes gcc tests to fail? I cannot find an existing example on how to handle this (other than making the tests type check only).

**Review by WaffleLapkin — APPROVED** [review]

**Comment by WaffleLapkin** [comment]
@InvalidPathException I think you forgot to push the changes addressing CI failure.
@rustbot author

**Comment by InvalidPathException** [comment]
> @InvalidPathException I think you forgot to push the changes addressing CI failure. @rustbot author

[ 72c9762f500ec24b017506d01427594f34bce250 ](https://github.com/rust-lang/rust/pull/148240/commits/72c9762f500ec24b017506d01427594f34bce250) This should fix it, no?

**Comment by WaffleLapkin** [comment]
my bad, didn't notice the commit in all the backlinks 🤦🏻 
@bors r+
