### PR TITLE
Fix const deref methods display

### LINKED ISSUE #90855: Rustdoc: Methods from `Deref` should not be `const`
Screenshot:

image

Considering that rustdoc doesn't care about `const_trait_impl`, methods from `Deref` cannot be called in const contexts. Therefore it is best to hide the `const` modifiers when showing methods from `Deref`.

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Fixes https://github.com/rust-lang/rust/issues/90855 (more information in the issue).

r? @camelid

### CODE REVIEW

File: src/librustdoc/html/render/mod.rs [hunk 1]
```diff
@@ -869,6 +869,7 @@ fn render_assoc_item(
     link: AssocItemLink<'_>,
     parent: ItemType,
     cx: &Context<'_>,
+    render_mode: RenderMode,
```
Comment (GuillaumeGomez) [inline src/librustdoc/html/render/mod.rs:872]: To make the code easier to read, I decided to pass `RenderMode` instead of a boolean to have a continuity with the rest of the code.

File: src/test/rustdoc/deref-const-fn.rs [hunk 2]
```diff
@@ -0,0 +1,23 @@
...
+
+pub struct Foo {
+    value: Bar,
+}
+
+impl std::ops::Deref for Foo {
+    type Target = Bar;
+
+    // @has 'foo/struct.Foo.html'
+    // @has - '//*[@id="method.len"]' 'pub fn len(&self) -> usize'
```
Comment (camelid) [inline src/test/rustdoc/deref-const-fn.rs:19]: nit: Maybe move this to just before the `impl` since it's not directly connected to the `deref()` function?

File: src/librustdoc/html/render/mod.rs [hunk 3]
```diff
@@ -1646,16 +1654,27 @@ fn render_rightside(
...
 ) {
     let tcx = cx.tcx();
 
+    let const_stable_since;
+    // FIXME: Once https://github.com/rust-lang/rust/issues/67792 is merged, we can remove
+    // this condition.
+    let (const_stability, const_stable_since) = if render_mode == RenderMode::Normal {
+        const_stable_since = containing_item.const_stable_since(tcx);
+        (item.const_stability(tcx), const_stable_since.as_deref())
```
Comment (camelid) [inline src/librustdoc/html/render/mod.rs:1666]: Why the need for an `as_deref()` and the `const_stable_since` variable that is immediately shadowed? Can you just use the Symbol below instead of converting here?

File: src/librustdoc/html/render/mod.rs [hunk 4]
```diff
@@ -901,8 +903,13 @@ fn render_assoc_item(
             }
         };
         let vis = meth.visibility.print_with_space(meth.def_id, cx).to_string();
-        let constness =
-            print_constness_with_space(&header.constness, meth.const_stability(cx.tcx()));
+        // FIXME: Once https://github.com/rust-lang/rust/issues/67792 is merged, we can remove
+        // this condition.
+        let constness = if render_mode == RenderMode::Normal {
```
Comment (camelid) [inline src/librustdoc/html/render/mod.rs:908]: Please use an exhaustive pattern match here. It's unclear just from looking at the code why this conditional is here, and a pattern match would make it clearer.

Comment (GuillaumeGomez) [reply src/librustdoc/html/render/mod.rs:908]: Good point.

File: src/test/rustdoc/deref-const-fn.rs (hunk 2 above)
Comment (GuillaumeGomez) [reply src/test/rustdoc/deref-const-fn.rs:19]: :+1:

File: src/librustdoc/html/render/mod.rs (hunk 3 above)
Comment (GuillaumeGomez) [reply src/librustdoc/html/render/mod.rs:1666]: We need to convert it to `&str` in any in `render_stability_since_raw` because we need to compare it to another `&str`.

**Comment by GuillaumeGomez** [comment]
Updated!

File: src/librustdoc/html/render/mod.rs (hunk 3 above)
Comment (camelid) [reply src/librustdoc/html/render/mod.rs:1666]: Symbols are designed to be fast to compare to each other, and the other `&str` seems to be from a Symbol as well. So I think we should change that function, though probably in a different PR.

Anyway, can't you do `.map(|s| s.as_str())` at the call-site of `render_stability_since_raw` to avoid this messy code?

File: src/librustdoc/html/render/mod.rs [hunk 5]
```diff
@@ -901,8 +903,13 @@ fn render_assoc_item(
...
         let vis = meth.visibility.print_with_space(meth.def_id, cx).to_string();
-        let constness =
-            print_constness_with_space(&header.constness, meth.const_stability(cx.tcx()));
+        // FIXME: Once https://github.com/rust-lang/rust/issues/67792 is merged, we can remove
+        // this condition.
+        let constness = if render_mode.is_normal() {
+            print_constness_with_space(&header.constness, meth.const_stability(cx.tcx()))
+        } else {
+            ""
+        };
```
Comment (camelid) [inline src/librustdoc/html/render/mod.rs:912]: My whole point was that there should be an exhaustive pattern match *here*; it's still unclear what the `else` branch is referring to. Can you get rid of `is_normal` and inline the match please?

Comment (GuillaumeGomez) [reply src/librustdoc/html/render/mod.rs:912]: In the two locations?

Comment (camelid) [reply src/librustdoc/html/render/mod.rs:912]: Yes.

**Comment by GuillaumeGomez** [comment]
@camelid I think you had a great idea: replacing the `&str` with `Symbol` could be very interesting. Let's run a perf check.

@bors try @rust-timer queue

**Comment by camelid** [comment]
Some slight doc instructions improvements, and the cleanup is good anyway. The improvements reported in the summary are just deep-vector being spurious as usual.

File: src/librustdoc/clean/types.rs [hunk 6]
```diff
@@ -599,16 +599,16 @@ impl Item {
         })
     }
 
-    crate fn stable_since(&self, tcx: TyCtxt<'_>) -> Option<SymbolStr> {
+    crate fn stable_since(&self, tcx: TyCtxt<'_>) -> Option<Symbol> {
```
Comment (camelid) [inline src/librustdoc/clean/types.rs:602]: Perhaps at this point it's too late, but it'd be better to separate this refactor into a separate commit.

File: src/librustdoc/html/render/mod.rs [hunk 7]
```diff
@@ -812,17 +812,17 @@ fn assoc_type(
 
 fn render_stability_since_raw(
     w: &mut Buffer,
-    ver: Option<&str>,
+    ver: Option<Symbol>,
     const_stability: Option<&ConstStability>,
```
Comment (camelid) [inline src/librustdoc/html/render/mod.rs:816]: Can you remove the `&` here? `ConstStability` is Copy AFAICT. (But in a separate commit please.)

File: src/librustdoc/html/render/mod.rs [hunk 8]
```diff
@@ -1467,7 +1476,7 @@ fn render_impl(
                     "<div id=\"{}\" class=\"{}{} has-srclink\">",
                     id, item_type, in_trait_class
                 );
-                render_rightside(w, cx, item, containing_item);
+                render_rightside(w, cx, item, containing_item, RenderMode::Normal);
```
Comment (camelid) [inline src/librustdoc/html/render/mod.rs:1479]: Why doesn't this use `render_mode`?

File: src/librustdoc/html/render/mod.rs [hunk 9]
```diff
@@ -1691,7 +1708,7 @@ pub(crate) fn render_impl_summary(
         format!(" data-aliases=\"{}\"", aliases.join(","))
     };
     write!(w, "<div id=\"{}\" class=\"impl has-srclink\"{}>", id, aliases);
-    render_rightside(w, cx, &i.impl_item, containing_item);
+    render_rightside(w, cx, &i.impl_item, containing_item, RenderMode::Normal);
```
Comment (camelid) [inline src/librustdoc/html/render/mod.rs:1711]: Are we sure that this code is never used for rendering methods from Deref?

File: src/test/rustdoc/deref-const-fn.rs [hunk 10]
```diff
@@ -0,0 +1,23 @@
+#![crate_name = "foo"]
+
+// @has 'foo/struct.Bar.html'
+pub struct Bar;
+
+impl Bar {
+    // @has - '//*[@id="method.len"]' 'pub const fn len(&self) -> usize'
+    pub const fn len(&self) -> usize { 0 }
```
Comment (camelid) [inline src/test/rustdoc/deref-const-fn.rs:8]: Can you test const (in)stability in this test as well? (Using `#![feature(staged_api)]`.)

Comment (camelid) [reply src/test/rustdoc/deref-const-fn.rs:8]: And can you also add a comment to the top of this test explaining what it tests?

File: src/librustdoc/clean/types.rs (hunk 6 above)
Comment (GuillaumeGomez) [reply src/librustdoc/clean/types.rs:602]: I can make it into a separate commit.

File: src/librustdoc/html/render/mod.rs (hunk 8 above)
Comment (GuillaumeGomez) [reply src/librustdoc/html/render/mod.rs:1479]: Because an associated const will always be const (unless I missed something?).

File: src/librustdoc/html/render/mod.rs (hunk 9 above)
Comment (GuillaumeGomez) [reply src/librustdoc/html/render/mod.rs:1711]: This is for the impl summary (so before all the methods). So I don't expect it to be an issue.

File: src/librustdoc/html/render/mod.rs (hunk 7 above)
Comment (GuillaumeGomez) [reply src/librustdoc/html/render/mod.rs]: Done as well.

File: src/librustdoc/clean/types.rs [hunk 11]
```diff
@@ -373,8 +373,8 @@ impl Item {
         self.def_id.as_def_id().and_then(|did| tcx.lookup_stability(did))
     }
 
-    crate fn const_stability<'tcx>(&self, tcx: TyCtxt<'tcx>) -> Option<&'tcx ConstStability> {
-        self.def_id.as_def_id().and_then(|did| tcx.lookup_const_stability(did))
+    crate fn const_stability<'tcx>(&self, tcx: TyCtxt<'tcx>) -> Option<ConstStability> {
```
Comment (GuillaumeGomez) [inline src/librustdoc/clean/types.rs:376]: Do you want me to do the same for `stability`? (the method before this one.)

File: src/test/rustdoc/deref-const-fn.rs (hunk 10 above)
Comment (GuillaumeGomez) [reply src/test/rustdoc/deref-const-fn.rs:10]: > Can you test const (in)stability in this test as well? (Using `#![feature(staged_api)]`.)

I don't think rustdoc handles `~const` yet, so not sure how useful it would be (also there are a lot of things from https://internals.rust-lang.org/t/pre-rfc-revamped-const-trait-impl-aka-rfc-2632/15192...).

File: src/librustdoc/html/render/mod.rs (hunk 8 above)
Comment (camelid) [reply src/librustdoc/html/render/mod.rs:1479]: Hmm, but is an associated const ever rendered for "Methods from Deref"? I wouldn't think so, since a const isn't a method. I'd prefer this code to always pass the actual render mode so we don't get confused later.

File: src/test/rustdoc/deref-const-fn.rs (hunk 10 above)
Comment (camelid) [reply src/test/rustdoc/deref-const-fn.rs:10]: What do you mean? I'm talking about

```rust
#[rustc_const_stable(...)]
```

which is totally unrelated to `~const` (aside from them both being related to const evaluation).

Comment (GuillaumeGomez) [reply src/test/rustdoc/deref-const-fn.rs:10]: Oh sorry. Yes, you're absolutely right! I'll extend the test.

File: src/librustdoc/html/render/mod.rs (hunk 9 above)
Comment (GuillaumeGomez) [reply src/librustdoc/html/render/mod.rs:1711]: Makes sense.

Comment (GuillaumeGomez) [reply src/librustdoc/html/render/mod.rs:1711]: Hum actually, the function is called after [this check](https://github.com/rust-lang/rust/blob/master/src/librustdoc/html/render/mod.rs#L1581). Are you really sure you want me to add an extra argument to the function anyway?

File: src/librustdoc/clean/types.rs (hunk 11 above)
Comment (camelid) [reply src/librustdoc/clean/types.rs:376]: Hmm, I didn't realize the TyCtxt methods return `&'tcx {Const}Stability`. Maybe it'd be best to revert the change to `const_stability()` and instead open a separate PR that changes the TyCtxt methods? I'm not sure why they return references.

File: src/librustdoc/html/render/mod.rs (hunk 9 above)
Comment (camelid) [reply src/librustdoc/html/render/mod.rs:1711]: Did you comment on the wrong thread? I'm confused about what you mean.

File: src/librustdoc/clean/types.rs (hunk 11 above)
Comment (GuillaumeGomez) [reply src/librustdoc/clean/types.rs:376]: The query engine dark magic. :3

File: src/librustdoc/html/render/mod.rs (hunk 8 above)
Comment (GuillaumeGomez) [reply src/librustdoc/html/render/mod.rs:1479]: Makes sense, doing it!

File: src/librustdoc/html/render/mod.rs (hunk 9 above)
Comment (GuillaumeGomez) [reply src/librustdoc/html/render/mod.rs:1711]: I completely did, so it's why my answer doesn't make any sense. I was answering to another comment on the bad code...

File: src/librustdoc/clean/types.rs (hunk 11 above)
Comment (camelid) [reply src/librustdoc/clean/types.rs:376]: Hehe. Let's leave `stability` alone for now since it'd be a much bigger change. You can keep the `const_stability` change though.

Comment (GuillaumeGomez) [reply src/librustdoc/clean/types.rs:376]: Ok, will be interesting to see if we can change the query engine afterwards.

**Comment by GuillaumeGomez** [comment]
Updated!

File: src/librustdoc/html/render/mod.rs [hunk 12]
```diff
@@ -893,8 +895,14 @@ fn render_assoc_item(
             }
         };
         let vis = meth.visibility.print_with_space(meth.def_id, cx).to_string();
-        let constness =
-            print_constness_with_space(&header.constness, meth.const_stability(cx.tcx()));
+        // FIXME: Once https://github.com/rust-lang/rust/issues/67792 is merged, we can remove
+        // this condition.
```
Comment (jyn514) [inline src/librustdoc/html/render/mod.rs:899]: "merged" is confusing for issues, I think "closed" or "implemented" would be more clear.

File: src/librustdoc/html/render/mod.rs [hunk 13]
```diff
@@ -1638,16 +1647,28 @@ fn render_rightside(
     cx: &Context<'_>,
     item: &clean::Item,
     containing_item: &clean::Item,
+    render_mode: RenderMode,
 ) {
     let tcx = cx.tcx();
 
+    let const_stable_since;
+    // FIXME: Once https://github.com/rust-lang/rust/issues/67792 is merged, we can remove
+    // this condition.
```
Comment (jyn514) [inline src/librustdoc/html/render/mod.rs:1655]: ditto

File: src/test/rustdoc/deref-const-fn.rs [hunk 14]
```diff
@@ -0,0 +1,37 @@
+// This test ensures that the const methods from Deref aren't const anymore.
+// For more information, take a look at https://github.com/rust-lang/rust/issues/67792.
```
Comment (camelid) [inline src/test/rustdoc/deref-const-fn.rs:2]:
```suggestion
// This test ensures that the const methods from Deref aren't shown as const.
// For more information, see https://github.com/rust-lang/rust/issues/90855.

```

File: src/test/rustdoc/deref-const-fn.rs [hunk 15]
```diff
@@ -0,0 +1,37 @@
...
+}
+
+#[stable(feature = "rust1", since = "1.0.0")]
+pub struct Foo {
+    value: Bar,
+}
+
+// @has 'foo/struct.Foo.html'
+// @has - '//*[@id="method.len"]' 'pub fn len(&self) -> usize'
+// @!has - '//*[@id="method.len"]//span[@class="since"]' '1.0.0'
```
Comment (camelid) [inline src/test/rustdoc/deref-const-fn.rs:28]: Hmm, shouldn't stability be shown? Or I guess it depends on when the Deref impl was added too.

Weirdly, https://doc.rust-lang.org/nightly/std/string/struct.String.html#deref-methods-str shows regular and const stability, but https://doc.rust-lang.org/nightly/std/path/struct.PathBuf.html#deref-methods-Path shows neither. Something fishy's going on with re-exports, since https://doc.rust-lang.org/nightly/alloc/string/struct.String.html#deref-methods-str shows stability for some methods but not all and is missing many methods that the std version has. (I think I opened an issue for part of this at some point.)

File: src/librustdoc/html/render/mod.rs (hunk 12 above)
Comment (GuillaumeGomez) [reply src/librustdoc/html/render/mod.rs:899]: Let's go for implemented then.

File: src/test/rustdoc/deref-const-fn.rs (hunk 15 above)
Comment (GuillaumeGomez) [reply src/test/rustdoc/deref-const-fn.rs:29]: Since you already opened the issue, I'll mark this discussion as resolved.

**Comment by GuillaumeGomez** [comment]
Updated!

**Comment by GuillaumeGomez** [comment]
Updated!

File: src/test/rustdoc/deref-const-fn.rs (hunk 15 above)
Comment (camelid) [reply src/test/rustdoc/deref-const-fn.rs:29]: No, the issue I opened was just about the methods shown being different. But I guess this bug is unrelated to this PR?

**Review by camelid — APPROVED** [review]

File: src/test/rustdoc/deref-const-fn.rs (hunk 15 above)
Comment (fee1-dead) [reply src/test/rustdoc/deref-const-fn.rs:29]: I thought `1.0.0` without the const version is hidden. Maybe that's why? If there is a stable const version, then we show `1.0.0 (const: 1.xx.0)` or `const: unstable`.
