### PR TITLE
ast_passes: unsupported arch w/ scalable vectors

### LINKED ISSUE #153593: [rustc] ICE: scalable vectors are unsupported in x86_64 calling convention classifier when compiling AArch64 SVE intrinsic returning scalable vector type
**Description**

`rustc` panics with "scalable vectors are unsupported" when compiling a function that calls an AArch64 SVE LLVM intrinsic returning a scalable vector type (`svbool4_t`). The crash occurs in the x86_64 calling convention classifier (`callconv/x86_64.rs:62`) during ABI computation at monomorphization time, even though the type is an AArch64-specific scalable vector that should never reach the x86_64 ABI classifier.

**Reproducer**

```rust
#![crate_type = "lib"]
#![allow(internal_features)]
#![feature(rustc_attrs, link_llvm_intrinsics)]

#[rustc_scalable_vector(4)]
#[allow(non_camel_case_types)]
#[repr(transparent)]
pub struct svbool4_t(bool);

pub fn trigger() -> svbool4_t {
    unsafe extern "C" {
        #[link_name = "llvm.aarch64.sve.whilelo.nxv4i1.u64"]
        fn _svwhilelt_b32_u64(op1: u64, op2: u64) -> svbool4_t;
    }
    unsafe { _svwhilelt_b32_u64(0, 1) }
}
```

**Command**

```
rustc --edition=2021 -C opt-level=1 -C codegen-units=1 reproduce.rs
```

**Expected behavior**

Either a graceful error is emitted indicating that AArch64 SVE scalable vector types cannot be used in this context on x86_64, or the ABI classifier correctly skips or handles scalable vector types without panicking.

**Actual behavior**

```
thread 'rustc' panicked at compiler/rustc_target/src/callconv/x86_64.rs:62:51:
scalable vectors are unsupported
error: the compiler unexpectedly panicked. This is a bug
```

**Root cause**

The call chain is:

```
fn_abi_of_instance [computing call ABI of `svwhilelt_b32_u64::_svwhilelt_b32_u64`]
  → fn_abi_adjust_for_abi
    → compute_abi_info (x86_64.rs:256)
      → classify_arg (x86_64.rs:106)
        → classify (x86_64.rs:62)  ← panic: scalable vectors are unsupported
```

The x86_64 `classify` function encounters a scalable vector type and hits an unconditional `panic!` with no prior guard. The `#[rustc_scalable_vector]` attribute marks `svbool4_t` as a scalable vector, and when `_svwhilelt_b32_u64` is monomorphized, its ABI is computed through the x86_64 classifier which does not handle this case gracefully.

**Environment**
- Compiler: `rustc 1.95.0-nightly`
- Host target: `x86_64-unknown-linux-gnu`
- Flags: `-C opt-level=1 -C codegen-units=1`
- Requires: `#![feature(rustc_attrs, link_llvm_intrinsics)]`
- rustc commit: `9b1f8ff42d110b0ca138116745be921df5dc97e7`

### PR DESCRIPTION
**Pull request by davidtwco**
Fixes rust-lang/rust#153593

Emit an error when attempting to compile a `#[rustc_scalable_vector]` type for a architecture that fundamentally doesn't support scalable vectors. Ultimately this is just a diagnostic improvement for an internal attribute as users should never be doing this.

r? @lqd

### CODE REVIEW

File: tests/ui/scalable-vectors/bad-architectures.rs [hunk 1]
```diff
@@ -0,0 +1,14 @@
+// ignore-tidy-linelength
+//@ ignore-aarch64
+//@ ignore-riscv32
+//@ ignore-riscv64
+//@ check-fail
```
Comment (lqd) [inline tests/ui/scalable-vectors/bad-architectures.rs]:
```suggestion
```

File: tests/ui/scalable-vectors/bad-architectures.rs [hunk 2]
```diff
@@ -0,0 +1,14 @@
+// ignore-tidy-linelength
```
Comment (lqd) [inline tests/ui/scalable-vectors/bad-architectures.rs]: this test shouldn't need that

File: tests/ui/scalable-vectors/bad-architectures.rs [hunk 3]
```diff
@@ -0,0 +1,14 @@
...
+//@ ignore-aarch64
+//@ ignore-riscv32
+//@ ignore-riscv64
+//@ check-fail
+
+// Confirm that non-AArch64 and non-RISC-V targets error when compiling scalable vectors
```
Comment (lqd) [inline tests/ui/scalable-vectors/bad-architectures.rs:5]: maybe we just mention https://github.com/rust-lang/rust/issues/153593 here

**Review by lqd — COMMENTED** [review]
Checking whether a target spec supports the feature makes sense to me (though I haven't checked if we do that with other targets per se).

r=me with nits above

*[View changes since this review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/rust/153608/655a7d20fefe23757ca9ecbbea01e4fe80208aaf..d066c0060f05bd6726c569f36dea928a7577a289)*
