### PR TITLE
Fix regression: account for trait methods in arg count mismatch error

### LINKED ISSUE #47706: Compiler Unexpectedly Panicked, call function with wrong number of arguments
First of all, this only happens on nightly 

```
rustc --version --verbose
binary: rustc
commit-hash: 97520ccb101609af63f29919bb0a39115269c89e
commit-date: 2018-01-21
host: x86_64-unknown-linux-gnu
release: 1.25.0-nightly
LLVM version: 4.0
```

I tried to make the code as simple as possible, so it might look like something no sane person would write

```rust
pub struct Foo {
    foo: Option<i32>,
}

impl Foo {
    pub fn new(foo: Option<i32>, _: ()) -> Foo {
        Foo { foo }
    }

    pub fn map(self) -> Option<Foo> {
        self.foo.map(Foo::new)
    }
}
```

This is what i get as output
```
thread 'rustc' panicked at 'non-FnLike node found: NodeImplItem(ImplItem { id: NodeId(14), name: new, hir_id: HirId { owner: DefIndex(0:6), local_id: ItemLocalId(0) }, vis: Public, defaultness: Final, attrs: [], generics: Generics { params: [], where_clause: WhereClause { id: NodeId(15), predicates: [] }, span: src/lib.rs:1:1: 1:1 }, node: Method(MethodSig { unsafety: Normal, constness: NotConst, abi: Rust, decl: FnDecl { inputs: [type(Option<i32>), type(())], output: Return(type(Foo)), variadic: false, has_implicit_self: false } }, BodyId { node_id: NodeId(41) }), span: src/run_info.rs:6:5: 8:6 })', librustc/traits/error_reporting.rs:837:13
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

### PR DESCRIPTION
**Pull request by CAD97**
Fixed #47706 (https://github.com/rust-lang/rust/issues/47706#issuecomment-361161495)

Original PR #47747 missed methods on trait definitions.

This edit was done in GitHub. I think I got the signature of the variant right, going by the ICE debug output and the other cases above.

### CODE REVIEW

**Comment by CAD97** [comment]
cc @estebank

**Comment by CAD97** [comment]
I should probably add a test for this. I can do that about 17 hours from now when I hit the machine where I've got the repo checked out and set up already, or someone else is free to add the test case I posted in the linked issue comment.

**Comment by pnkfelix** [comment]
@CAD97 this looks great!

Please squash the commits you have added when you put up the test case.

r=me once the test case is added.

**Comment by estebank** [comment]
@CAD97 thank you for following up and adding a fix. I would prefer it if it had a test case in the same commit for easier historical tracking. We can wait another 8 hours for it :)

**Comment by CAD97** [comment]
Test added and squashed!

r? @pnkfelix

**Comment by estebank** [comment]
```
[00:04:11] tidy error: /checkout/src/test/ui/issue-47706-trait.rs:15: line longer than 100 chars
[00:04:12] some tidy checks failed
```

**Comment by CAD97** [comment]
Yeah, working on it

**Comment by CAD97** [comment]
That should fix the tidy issue.

File: src/test/ui/issue-47706-trait.rs [hunk 1]
```diff
@@ -0,0 +1,17 @@
...
+// <LICENSE-MIT or http://opensource.org/licenses/MIT>, at your
+// option. This file may not be copied, modified, or distributed
+// except according to those terms.
+
+trait T {
+    fn f(&self, _: ()) {
+        None::<()>.map(Self::f);
+    }
+    //~^^ ERROR function is expected to take a single 0-tuple as argument,
+    //~^^ but it takes 2 distinct arguments [E0593]
```
Comment (estebank) [inline src/test/ui/issue-47706-trait.rs]: Just remove line 16, line 15 will match the beginning and work as expected.

**Comment by CAD97** [comment]
That _should_ be everything.

File: src/test/ui/issue-47706-trait.rs (hunk 1 above)
Comment (CAD97) [reply src/test/ui/issue-47706-trait.rs]: Well, I did something wrong I guess (by putting on the tag?) https://travis-ci.org/rust-lang/rust/builds/334956316

Comment (estebank) [reply src/test/ui/issue-47706-trait.rs]: Yeah, just remove the `[E0593]`.

**Comment by CAD97** [comment]
Travis passed.
