### PR TITLE
Fix dyn -> param suggestion in struct ICEs

### LINKED ISSUE #138211: ICE: `$ident: found TraitItem(TraitItem `
auto-reduced (treereduce-rust):
````rust
//@compile-flags: --edition=2024
pub trait TraitWAssocConst {
    const A: TraitWAssocConst<A = 0>;
}

````

original:
````rust
#![feature(generic_const_exprs)]
pub trait TraitWAssocConst {
  const A: TraitWAssocConst<A=0>;
}

fn main<A: TraitWAssocConst<A=32>>() {
  TraitWAssocConst<A=0>:: TraitWAssocConst<A=32> ();
}

````

Version information
````
rustc 1.87.0-nightly (20f0108ad 2025-03-08)
binary: rustc
commit-hash: 20f0108ada90e37c2350ad68fdc6afe56f51539d
commit-date: 2025-03-08
host: x86_64-unknown-linux-gnu
release: 1.87.0-nightly
LLVM version: 20.1.0

````

Possibly related line of code:
https://github.com/rust-lang/rust/blob/20f0108ada90e37c2350ad68fdc6afe56f51539d/compiler/rustc_hir_analysis/src/hir_ty_lowering/lint.rs#L204-L216

Command:
`/home/matthias/.rustup/toolchains/master/bin/rustc --edition=2024`

<details><summary><strong>Program output</strong></summary>
<p>

```
error[E0658]: associated const equality is incomplete
 --> /tmp/icemaker_global_tempdir.xCmlSFx4hmpo/rustc_testrunner_tmpdir_reporting.tPdpsshuU7cG/mvce.rs:2:31
  |
2 |     const A: TraitWAssocConst<A = 0>;
  |                               ^^^^^
  |
  = note: see issue #92827 <https://github.com/rust-lang/rust/issues/92827> for more information
  = help: add `#![feature(associated_const_equality)]` to the crate attributes to enable
  = note: this compiler was built on 2025-03-08; consider upgrading it if it is out of date

error[E0601]: `main` function not found in crate `mvce`
 --> /tmp/icemaker_global_tempdir.xCmlSFx4hmpo/rustc_testrunner_tmpdir_reporting.tPdpsshuU7cG/mvce.rs:3:2
  |
3 | }
  |  ^ consider adding a `main` function to `/tmp/icemaker_global_tempdir.xCmlSFx4hmpo/rustc_testrunner_tmpdir_reporting.tPdpsshuU7cG/mvce.rs`


thread 'rustc' panicked at compiler/rustc_hir_analysis/src/hir_ty_lowering/lint.rs:210:61:
$ident: found TraitItem(TraitItem { ident: A#0, owner_id: DefId(0:4 ~ mvce[a2ab]::TraitWAssocConst::A), generics: Generics { params: [], predicates: [], has_where_clause_predicates: false, where_clause_span: /tmp/icemaker_global_tempdir.xCmlSFx4hmpo/rustc_testrunner_tmpdir_reporting.tPdpsshuU7cG/mvce.rs:2:37: 2:37 (#0), span: /tmp/icemaker_global_tempdir.xCmlSFx4hmpo/rustc_testrunner_tmpdir_reporting.tPdpsshuU7cG/mvce.rs:2:12: 2:12 (#0) }, kind: Const(Ty { hir_id: HirId(DefId(0:4 ~ mvce[a2ab]::TraitWAssocConst::A).8), span: /tmp/icemaker_global_tempdir.xCmlSFx4hmpo/rustc_testrunner_tmpdir_reporting.tPdpsshuU7cG/mvce.rs:2:14: 2:37 (#0), kind: TraitObject([PolyTraitRef { bound_generic_params: [], modifiers: TraitBoundModifiers { constness: Never, polarity: Positive }, trait_ref: TraitRef { path: Path { span: /tmp/icemaker_global_tempdir.xCmlSFx4hmpo/rustc_testrunner_tmpdir_reporting.tPdpsshuU7cG/mvce.rs:2:14: 2:37 (#0), res: Def(Trait, DefId(0:3 ~ mvce[a2ab]::TraitWAssocConst)), segments: [PathSegment { ident: TraitWAssocConst#0, hir_id: HirId(DefId(0:4 ~ mvce[a2ab]::TraitWAssocConst::A).5), res: Def(Trait, DefId(0:3 ~ mvce[a2ab]::TraitWAssocConst)), args: Some(GenericArgs { args: [], constraints: [AssocItemConstraint { hir_id: HirId(DefId(0:4 ~ mvce[a2ab]::TraitWAssocConst::A).4), ident: A#0, gen_args: GenericArgs { args: [], constraints: [], parenthesized: No, span_ext: no-location (#0) }, kind: Equality { term: Const(ConstArg { hir_id: HirId(DefId(0:4 ~ mvce[a2ab]::TraitWAssocConst::A).3), kind: Anon(AnonConst { hir_id: HirId(DefId(0:4 ~ mvce[a2ab]::TraitWAssocConst::A).1), def_id: DefId(0:5 ~ mvce[a2ab]::TraitWAssocConst::A::{constant#0}), body: BodyId { hir_id: HirId(DefId(0:4 ~ mvce[a2ab]::TraitWAssocConst::A).2) }, span: /tmp/icemaker_global_tempdir.xCmlSFx4hmpo/rustc_testrunner_tmpdir_reporting.tPdpsshuU7cG/mvce.rs:2:35: 2:36 (#0) }) }) }, span: /tmp/icemaker_global_tempdir.xCmlSFx4hmpo/rustc_testrunner_tmpdir_reporting.tPdpsshuU7cG/mvce.rs:2:31: 2:36 (#0) }], parenthesized: No, span_ext: /tmp/icemaker_global_tempdir.xCmlSFx4hmpo/rustc_testrunner_tmpdir_reporting.tPdpsshuU7cG/mvce.rs:2:30: 2:37 (#0) }), infer_args: false }] }, hir_ref_id: HirId(DefId(0:4 ~ mvce[a2ab]::TraitWAssocConst::A).6) }, span: /tmp/icemaker_global_tempdir.xCmlSFx4hmpo/rustc_testrunner_tmpdir_reporting.tPdpsshuU7cG/mvce.rs:2:14: 2:37 (#0) }], TaggedRef { pointer: Lifetime { hir_id: HirId(DefId(0:4 ~ mvce[a2ab]::TraitWAssocConst::A).7), ident: #0, res: ImplicitObjectLifetimeDefault }, tag: None }) }, None), span: /tmp/icemaker_global_tempdir.xCmlSFx4hmpo/rustc_testrunner_tmpdir_reporting.tPdpsshuU7cG/mvce.rs:2:5: 2:38 (#0), defaultness: Default { has_value: false } })
stack backtrace:
   0:     0x735d0f5c6f34 - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::h07b2089c80742ed5
   1:     0x735d0fe05aa2 - core::fmt::write::h332ae571ae4a9cc4
   2:     0x735d111e3a11 - std::io::Write::write_fmt::h0c761025205b813c
   3:     0x735d0f5c6d92 - std::sys::backtrace::BacktraceLock::print::hbba93a9383b9fa8a
   4:     0x735d0f5c9672 - std::panicking::default_hook::{{closure}}::h00e63950a63732af
   5:     0x735d0f5c9264 - std::panicking::default_hook::h400dc9bc1b724c37
   6:     0x735d0e7204e7 - std[c20316ad899fcaf5]::panicking::update_hook::<alloc[2db8fd01bd7ea837]::boxed::Box<rustc_driver_impl[153d3eccf0c7c750]::install_ice_hook::{closure#1}>>::{closure#0}
   7:     0x735d0f5c9ee3 - std::panicking::rust_panic_with_hook::he428532615a29ae4
   8:     0x735d0f5c9bda - std::panicking::begin_panic_handler::{{closure}}::h498acb37174be106
   9:     0x735d0f5c73f9 - std::sys::backtrace::__rust_end_short_backtrace::h2c0df5d26e60f09c
  10:     0x735d0f5c989d - rust_begin_unwind
  11:     0x735d0c25df10 - core::panicking::panic_fmt::h35b514d9ffb031f4
  12:     0x735d0e7ecf81 - rustc_hir[229de859651313c0]::hir::expect_failed::<&rustc_hir[229de859651313c0]::hir::Node>
  13:     0x735d1105f858 - <dyn rustc_hir_analysis[2ac45909935d36a1]::hir_ty_lowering::HirTyLowerer>::prohibit_or_lint_bare_trait_object_ty
  14:     0x735d10566736 - <dyn rustc_hir_analysis[2ac45909935d36a1]::hir_ty_lowering::HirTyLowerer>::lower_ty
  15:     0x735d103618cd - rustc_hir_analysis[2ac45909935d36a1]::collect::type_of::type_of
  16:     0x735d10359d2a - rustc_query_impl[824584145395502d]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[824584145395502d]::query_impl::type_of::dynamic_query::{closure#2}::{closure#0}, rustc_middle[b1dca1d1b343b3c]::query::erase::Erased<[u8; 8usize]>>
  17:     0x735d10161332 - rustc_query_system[75007086aa92bf3]::query::plumbing::try_execute_query::<rustc_query_impl[824584145395502d]::DynamicConfig<rustc_query_system[75007086aa92bf3]::query::caches::DefIdCache<rustc_middle[b1dca1d1b343b3c]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[824584145395502d]::plumbing::QueryCtxt, false>
  18:     0x735d10160edf - rustc_query_impl[824584145395502d]::query_impl::type_of::get_query_non_incr::__rust_end_short_backtrace
  19:     0x735d10597699 - <rustc_hir_analysis[2ac45909935d36a1]::collect::CollectItemTypesVisitor as rustc_hir[229de859651313c0]::intravisit::Visitor>::visit_trait_item
  20:     0x735d105899ef - rustc_hir_analysis[2ac45909935d36a1]::check::wfcheck::check_well_formed
  21:     0x735d1058754d - rustc_query_impl[824584145395502d]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[824584145395502d]::query_impl::check_well_formed::dynamic_query::{closure#2}::{closure#0}, rustc_middle[b1dca1d1b343b3c]::query::erase::Erased<[u8; 1usize]>>
  22:     0x735d10587004 - rustc_query_system[75007086aa92bf3]::query::plumbing::try_execute_query::<rustc_query_impl[824584145395502d]::DynamicConfig<rustc_data_structures[59c1b7daa758d1f8]::vec_cache::VecCache<rustc_span[268b27c29cacb432]::def_id::LocalDefId, rustc_middle[b1dca1d1b343b3c]::query::erase::Erased<[u8; 1usize]>, rustc_query_system[75007086aa92bf3]::dep_graph::graph::DepNodeIndex>, false, false, false>, rustc_query_impl[824584145395502d]::plumbing::QueryCtxt, false>
  23:     0x735d10586abf - rustc_query_impl[824584145395502d]::query_impl::check_well_formed::get_query_non_incr::__rust_end_short_backtrace
  24:     0x735d105845f0 - rustc_hir_analysis[2ac45909935d36a1]::check::wfcheck::check_mod_type_wf
  25:     0x735d105840df - rustc_query_impl[824584145395502d]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[824584145395502d]::query_impl::check_mod_type_wf::dynamic_query::{closure#2}::{closure#0}, rustc_middle[b1dca1d1b343b3c]::query::erase::Erased<[u8; 1usize]>>
  26:     0x735d10e96d56 - rustc_query_system[75007086aa92bf3]::query::plumbing::try_execute_query::<rustc_query_impl[824584145395502d]::DynamicConfig<rustc_query_system[75007086aa92bf3]::query::caches::DefaultCache<rustc_span[268b27c29cacb432]::def_id::LocalModDefId, rustc_middle[b1dca1d1b343b3c]::query::erase::Erased<[u8; 1usize]>>, false, false, false>, rustc_query_impl[824584145395502d]::plumbing::QueryCtxt, false>
  27:     0x735d10e96aff - rustc_query_impl[824584145395502d]::query_impl::check_mod_type_wf::get_query_non_incr::__rust_end_short_backtrace
  28:     0x735d1017f9cf - rustc_hir_analysis[2ac45909935d36a1]::check_crate
  29:     0x735d1032807a - rustc_interface[7e29b5e2b62c504d]::passes::run_required_analyses
  30:     0x735d10dc1b7a - rustc_interface[7e29b5e2b62c504d]::passes::analysis
  31:     0x735d10dc1b59 - rustc_query_impl[824584145395502d]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[824584145395502d]::query_impl::analysis::dynamic_query::{closure#2}::{closure#0}, rustc_middle[b1dca1d1b343b3c]::query::erase::Erased<[u8; 0usize]>>
  32:     0x735d10eda3cb - rustc_query_system[75007086aa92bf3]::query::plumbing::try_execute_query::<rustc_query_impl[824584145395502d]::DynamicConfig<rustc_query_system[75007086aa92bf3]::query::caches::SingleCache<rustc_middle[b1dca1d1b343b3c]::query::erase::Erased<[u8; 0usize]>>, false, false, false>, rustc_query_impl[824584145395502d]::plumbing::QueryCtxt, false>
  33:     0x735d10eda0b9 - rustc_query_impl[824584145395502d]::query_impl::analysis::get_query_non_incr::__rust_end_short_backtrace
  34:     0x735d10f1577d - rustc_interface[7e29b5e2b62c504d]::passes::create_and_enter_global_ctxt::<core[8e02e1de5014891c]::option::Option<rustc_interface[7e29b5e2b62c504d]::queries::Linker>, rustc_driver_impl[153d3eccf0c7c750]::run_compiler::{closure#0}::{closure#2}>::{closure#2}::{closure#0}
  35:     0x735d10f056a0 - rustc_interface[7e29b5e2b62c504d]::interface::run_compiler::<(), rustc_driver_impl[153d3eccf0c7c750]::run_compiler::{closure#0}>::{closure#1}
  36:     0x735d10dabe48 - std[c20316ad899fcaf5]::sys::backtrace::__rust_begin_short_backtrace::<rustc_interface[7e29b5e2b62c504d]::util::run_in_thread_with_globals<rustc_interface[7e29b5e2b62c504d]::util::run_in_thread_pool_with_globals<rustc_interface[7e29b5e2b62c504d]::interface::run_compiler<(), rustc_driver_impl[153d3eccf0c7c750]::run_compiler::{closure#0}>::{closure#1}, ()>::{closure#0}, ()>::{closure#0}::{closure#0}, ()>
  37:     0x735d10dac734 - <<std[c20316ad899fcaf5]::thread::Builder>::spawn_unchecked_<rustc_interface[7e29b5e2b62c504d]::util::run_in_thread_with_globals<rustc_interface[7e29b5e2b62c504d]::util::run_in_thread_pool_with_globals<rustc_interface[7e29b5e2b62c504d]::interface::run_compiler<(), rustc_driver_impl[153d3eccf0c7c750]::run_compiler::{closure#0}>::{closure#1}, ()>::{closure#0}, ()>::{closure#0}::{closure#0}, ()>::{closure#1} as core[8e02e1de5014891c]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  38:     0x735d10dadb2b - std::sys::pal::unix::thread::Thread::new::thread_start::h63137a35d539f669
  39:     0x735d0aea370a - <unknown>
  40:     0x735d0af27aac - <unknown>
  41:                0x0 - <unknown>

error: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: please make sure that you have updated to the latest nightly

note: rustc 1.87.0-nightly (20f0108ad 2025-03-08) running on x86_64-unknown-linux-gnu

note: compiler flags: -Z dump-mir-dir=dir

query stack during panic:
#0 [type_of] computing type of `TraitWAssocConst::A`
#1 [check_well_formed] checking that `TraitWAssocConst::A` is well-formed
#2 [check_mod_type_wf] checking that types are well-formed in top-level module
#3 [analysis] running analysis passes on this crate
end of query stack
error: aborting due to 2 previous errors

Some errors have detailed explanations: E0601, E0658.
For more information about an error, try `rustc --explain E0601`.

```

</p>
</details>

### LINKED ISSUE #138229: ICE: compiler/rustc_hir_analysis/src/hir_ty_lowering/lint.rs None
snippet:
````rust
//@compile-flags: --edition=2024
pub struct Flatten<I>
where
    Iterator<Item: >:, {}

````

Version information
````
rustc 1.87.0-nightly (cdd8af229 2025-03-08)
binary: rustc
commit-hash: cdd8af229960d05c8dfe5ca3e5f5e2066e676213
commit-date: 2025-03-08
host: x86_64-unknown-linux-gnu
release: 1.87.0-nightly
LLVM version: 20.1.0

````

Possibly related line of code:
https://github.com/rust-lang/rust/blob/cdd8af229960d05c8dfe5ca3e5f5e2066e676213/compiler/rustc_hir_analysis/src/hir_ty_lowering/lint.rs#L213-L225

Command:
`/home/matthias/.rustup/toolchains/master/bin/rustc --edition=2024`

<details><summary><strong>Program output</strong></summary>
<p>

```
error: associated type bounds are not allowed in `dyn` types
 --> /tmp/icemaker_global_tempdir.1fddo3thr4FG/rustc_testrunner_tmpdir_reporting.q7t4VPLdZITs/mvce.rs:3:14
  |
3 |     Iterator<Item: >:, {}
  |              ^^^^^

error[E0601]: `main` function not found in crate `mvce`
 --> /tmp/icemaker_global_tempdir.1fddo3thr4FG/rustc_testrunner_tmpdir_reporting.q7t4VPLdZITs/mvce.rs:3:26
  |
3 |     Iterator<Item: >:, {}
  |                          ^ consider adding a `main` function to `/tmp/icemaker_global_tempdir.1fddo3thr4FG/rustc_testrunner_tmpdir_reporting.q7t4VPLdZITs/mvce.rs`


thread 'rustc' panicked at compiler/rustc_hir_analysis/src/hir_ty_lowering/lint.rs:219:45:
called `Option::unwrap()` on a `None` value
stack backtrace:
   0:     0x74270adc79d4 - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::hd713c4d8f2a992f7
   1:     0x74270b605a62 - core::fmt::write::hd251c22aa3b08f95
   2:     0x74270c9af011 - std::io::Write::write_fmt::h9618bab13245ea22
   3:     0x74270adc7832 - std::sys::backtrace::BacktraceLock::print::ha3210e3903b3f60d
   4:     0x74270adca112 - std::panicking::default_hook::{{closure}}::h6ffc694d8b54cfbc
   5:     0x74270adc9d04 - std::panicking::default_hook::h18f17c54de83d745
   6:     0x742709f20d37 - std[ea1c415d91c3a3f3]::panicking::update_hook::<alloc[2e89a6e6a742d90a]::boxed::Box<rustc_driver_impl[6d217ad2d5c0cd23]::install_ice_hook::{closure#1}>>::{closure#0}
   7:     0x74270adca983 - std::panicking::rust_panic_with_hook::h671b37e3b2b9a0c6
   8:     0x74270adca646 - std::panicking::begin_panic_handler::{{closure}}::h274c9dfd04385a24
   9:     0x74270adc7e99 - std::sys::backtrace::__rust_end_short_backtrace::h23c8ca15e79f68ed
  10:     0x74270adca33d - rust_begin_unwind
  11:     0x742707a5ec80 - core::panicking::panic_fmt::hd63d1c0540a60bdc
  12:     0x74270854bd6c - core::panicking::panic::h56e792821a9251e2
  13:     0x742708aeb839 - core::option::unwrap_failed::hb932d1e707961bac
  14:     0x74270c86832a - <dyn rustc_hir_analysis[b5445f66d222153f]::hir_ty_lowering::HirTyLowerer>::prohibit_or_lint_bare_trait_object_ty
  15:     0x74270bd62ff6 - <dyn rustc_hir_analysis[b5445f66d222153f]::hir_ty_lowering::HirTyLowerer>::lower_ty
  16:     0x74270bb0ef87 - rustc_hir_analysis[b5445f66d222153f]::collect::predicates_of::gather_explicit_predicates_of
  17:     0x74270bb0d25f - rustc_query_impl[bdafc42a67792f6b]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[bdafc42a67792f6b]::query_impl::explicit_predicates_of::dynamic_query::{closure#2}::{closure#0}, rustc_middle[40f7eeb9b5af1651]::query::erase::Erased<[u8; 24usize]>>
  18:     0x74270bafe7eb - rustc_query_system[e28bb8395bb88072]::query::plumbing::try_execute_query::<rustc_query_impl[bdafc42a67792f6b]::DynamicConfig<rustc_query_system[e28bb8395bb88072]::query::caches::DefIdCache<rustc_middle[40f7eeb9b5af1651]::query::erase::Erased<[u8; 24usize]>>, false, false, false>, rustc_query_impl[bdafc42a67792f6b]::plumbing::QueryCtxt, false>
  19:     0x74270bafe124 - rustc_query_impl[bdafc42a67792f6b]::query_impl::explicit_predicates_of::get_query_non_incr::__rust_end_short_backtrace
  20:     0x74270bafc7bf - rustc_hir_analysis[b5445f66d222153f]::collect::predicates_of::predicates_of
  21:     0x74270bafc6e1 - rustc_query_impl[bdafc42a67792f6b]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[bdafc42a67792f6b]::query_impl::predicates_of::dynamic_query::{closure#2}::{closure#0}, rustc_middle[40f7eeb9b5af1651]::query::erase::Erased<[u8; 24usize]>>
  22:     0x74270bafe7cf - rustc_query_system[e28bb8395bb88072]::query::plumbing::try_execute_query::<rustc_query_impl[bdafc42a67792f6b]::DynamicConfig<rustc_query_system[e28bb8395bb88072]::query::caches::DefIdCache<rustc_middle[40f7eeb9b5af1651]::query::erase::Erased<[u8; 24usize]>>, false, false, false>, rustc_query_impl[bdafc42a67792f6b]::plumbing::QueryCtxt, false>
  23:     0x74270bafe024 - rustc_query_impl[bdafc42a67792f6b]::query_impl::predicates_of::get_query_non_incr::__rust_end_short_backtrace
  24:     0x74270bd9051a - <rustc_hir_analysis[b5445f66d222153f]::collect::CollectItemTypesVisitor as rustc_hir[7b5749dda82e61]::intravisit::Visitor>::visit_item
  25:     0x74270bd84005 - rustc_hir_analysis[b5445f66d222153f]::check::wfcheck::check_well_formed
  26:     0x74270bd83e11 - rustc_query_impl[bdafc42a67792f6b]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[bdafc42a67792f6b]::query_impl::check_well_formed::dynamic_query::{closure#2}::{closure#0}, rustc_middle[40f7eeb9b5af1651]::query::erase::Erased<[u8; 1usize]>>
  27:     0x74270bd838c8 - rustc_query_system[e28bb8395bb88072]::query::plumbing::try_execute_query::<rustc_query_impl[bdafc42a67792f6b]::DynamicConfig<rustc_data_structures[8222949f9d1c4f5]::vec_cache::VecCache<rustc_span[c79046a8f90eac9]::def_id::LocalDefId, rustc_middle[40f7eeb9b5af1651]::query::erase::Erased<[u8; 1usize]>, rustc_query_system[e28bb8395bb88072]::dep_graph::graph::DepNodeIndex>, false, false, false>, rustc_query_impl[bdafc42a67792f6b]::plumbing::QueryCtxt, false>
  28:     0x74270bd83383 - rustc_query_impl[bdafc42a67792f6b]::query_impl::check_well_formed::get_query_non_incr::__rust_end_short_backtrace
  29:     0x74270bd80b9d - rustc_hir_analysis[b5445f66d222153f]::check::wfcheck::check_mod_type_wf
  30:     0x74270bd8099f - rustc_query_impl[bdafc42a67792f6b]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[bdafc42a67792f6b]::query_impl::check_mod_type_wf::dynamic_query::{closure#2}::{closure#0}, rustc_middle[40f7eeb9b5af1651]::query::erase::Erased<[u8; 1usize]>>
  31:     0x74270c6a64d6 - rustc_query_system[e28bb8395bb88072]::query::plumbing::try_execute_query::<rustc_query_impl[bdafc42a67792f6b]::DynamicConfig<rustc_query_system[e28bb8395bb88072]::query::caches::DefaultCache<rustc_span[c79046a8f90eac9]::def_id::LocalModDefId, rustc_middle[40f7eeb9b5af1651]::query::erase::Erased<[u8; 1usize]>>, false, false, false>, rustc_query_impl[bdafc42a67792f6b]::plumbing::QueryCtxt, false>
  32:     0x74270c6a627f - rustc_query_impl[bdafc42a67792f6b]::query_impl::check_mod_type_wf::get_query_non_incr::__rust_end_short_backtrace
  33:     0x74270b95c34f - rustc_hir_analysis[b5445f66d222153f]::check_crate
  34:     0x74270ba2e8b4 - rustc_interface[82f631b64fcfc832]::passes::run_required_analyses
  35:     0x74270c5caafa - rustc_interface[82f631b64fcfc832]::passes::analysis
  36:     0x74270c5caad9 - rustc_query_impl[bdafc42a67792f6b]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[bdafc42a67792f6b]::query_impl::analysis::dynamic_query::{closure#2}::{closure#0}, rustc_middle[40f7eeb9b5af1651]::query::erase::Erased<[u8; 0usize]>>
  37:     0x74270c6c6d0b - rustc_query_system[e28bb8395bb88072]::query::plumbing::try_execute_query::<rustc_query_impl[bdafc42a67792f6b]::DynamicConfig<rustc_query_system[e28bb8395bb88072]::query::caches::SingleCache<rustc_middle[40f7eeb9b5af1651]::query::erase::Erased<[u8; 0usize]>>, false, false, false>, rustc_query_impl[bdafc42a67792f6b]::plumbing::QueryCtxt, false>
  38:     0x74270c6c69f9 - rustc_query_impl[bdafc42a67792f6b]::query_impl::analysis::get_query_non_incr::__rust_end_short_backtrace
  39:     0x74270c75bdfd - rustc_interface[82f631b64fcfc832]::passes::create_and_enter_global_ctxt::<core[146ed0f78261ee61]::option::Option<rustc_interface[82f631b64fcfc832]::queries::Linker>, rustc_driver_impl[6d217ad2d5c0cd23]::run_compiler::{closure#0}::{closure#2}>::{closure#2}::{closure#0}
  40:     0x74270c73d1e0 - rustc_interface[82f631b64fcfc832]::interface::run_compiler::<(), rustc_driver_impl[6d217ad2d5c0cd23]::run_compiler::{closure#0}>::{closure#1}
  41:     0x74270c5b4d88 - std[ea1c415d91c3a3f3]::sys::backtrace::__rust_begin_short_backtrace::<rustc_interface[82f631b64fcfc832]::util::run_in_thread_with_globals<rustc_interface[82f631b64fcfc832]::util::run_in_thread_pool_with_globals<rustc_interface[82f631b64fcfc832]::interface::run_compiler<(), rustc_driver_impl[6d217ad2d5c0cd23]::run_compiler::{closure#0}>::{closure#1}, ()>::{closure#0}, ()>::{closure#0}::{closure#0}, ()>
  42:     0x74270c5b5674 - <<std[ea1c415d91c3a3f3]::thread::Builder>::spawn_unchecked_<rustc_interface[82f631b64fcfc832]::util::run_in_thread_with_globals<rustc_interface[82f631b64fcfc832]::util::run_in_thread_pool_with_globals<rustc_interface[82f631b64fcfc832]::interface::run_compiler<(), rustc_driver_impl[6d217ad2d5c0cd23]::run_compiler::{closure#0}>::{closure#1}, ()>::{closure#0}, ()>::{closure#0}::{closure#0}, ()>::{closure#1} as core[146ed0f78261ee61]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  43:     0x74270c5b6a6b - std::sys::pal::unix::thread::Thread::new::thread_start::hf813d01f8068137e
  44:     0x74270665e70a - <unknown>
  45:     0x7427066e2aac - <unknown>
  46:                0x0 - <unknown>

error: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: please make sure that you have updated to the latest nightly

note: rustc 1.87.0-nightly (cdd8af229 2025-03-08) running on x86_64-unknown-linux-gnu

note: compiler flags: -Z dump-mir-dir=dir

query stack during panic:
#0 [explicit_predicates_of] computing explicit predicates of `Flatten`
#1 [predicates_of] computing predicates of `Flatten`
#2 [check_well_formed] checking that `Flatten` is well-formed
#3 [check_mod_type_wf] checking that types are well-formed in top-level module
#4 [analysis] running analysis passes on this crate
end of query stack
error: aborting due to 2 previous errors

For more information about this error, try `rustc --explain E0601`.

```

</p>
</details>

### PR DESCRIPTION
**Pull request by compiler-errors**
Makes the logic from #138042 a bit less ICEy and more clean. Also fixes an incorrect suggestion when the struct already has generics. I'll point out the major changes and observations in the code.

Fixes #138229 
Fixes #138211

r? nnethercote since you reviewed the original pr, or re-roll if you don't want to review this

### CODE REVIEW

File: compiler/rustc_hir_analysis/src/hir_ty_lowering/lint.rs [hunk 1]
```diff
@@ -123,31 +126,62 @@ impl<'tcx> dyn HirTyLowerer<'tcx> + '_ {
...
         &self,
         self_ty: &hir::Ty<'_>,
         diag: &mut Diag<'_>,
     ) -> bool {
         let tcx = self.tcx();
-        let msg = "you might be missing a type parameter";
-        let mut sugg = vec![];
 
-        let parent_id = tcx.hir_get_parent_item(self_ty.hir_id).def_id;
-        let parent_item = tcx.hir_node_by_def_id(parent_id).expect_item();
```
Comment (compiler-errors) [inline compiler/rustc_hir_analysis/src/hir_ty_lowering/lint.rs:136]: `expect_item` here is not valid, since there are other kinds of HIR parents that can own this `dyn Trait`, like extern items (or trait/impl items, closures, etc).

File: compiler/rustc_hir_analysis/src/hir_ty_lowering/lint.rs [hunk 2]
```diff
@@ -123,31 +126,62 @@ impl<'tcx> dyn HirTyLowerer<'tcx> + '_ {
...
-                    format!(
-                        "<T: {}>",
-                        self.tcx().sess.source_map().span_to_snippet(self_ty.span).unwrap()
-                    ),
-                ));
-                sugg.push((self_ty.span, "T".to_string()));
+        let parent_hir_id = tcx.parent_hir_id(self_ty.hir_id);
+        let parent_item = tcx.hir_get_parent_item(self_ty.hir_id).def_id;
+
+        let generics = match tcx.hir_node_by_def_id(parent_item) {
```
Comment (compiler-errors) [inline compiler/rustc_hir_analysis/src/hir_ty_lowering/lint.rs:141]: I added a check that we're suggesting this on a field directly. `dyn` may show up in other positions like in a where clause or in an expr on a default field value.

File: compiler/rustc_hir_analysis/src/hir_ty_lowering/lint.rs [hunk 3]
```diff
@@ -198,32 +232,59 @@ impl<'tcx> dyn HirTyLowerer<'tcx> + '_ {
...
     ) -> bool {
         let tcx = self.tcx();
-        let parent_id = tcx.hir_get_parent_item(self_ty.hir_id).def_id;
-        let parent_item = tcx.hir_node_by_def_id(parent_id).expect_item();
 
-        // If the parent item is an enum, don't suggest the dyn trait.
-        if let hir::ItemKind::Enum(..) = parent_item.kind {
-            return false;
-        }
+        // Look at the direct HIR parent, since we care about the relationship between
```
Comment (compiler-errors) [inline compiler/rustc_hir_analysis/src/hir_ty_lowering/lint.rs:250]: This was also `expect_item`ing unnecessarily. I took the logic and made it focus on the relationship between the ty and its parent *node*, so we don't suggest turning:

```
struct Foo { f: Box<Any>, /* more fields */ }
```

Into this:

```
struct Foo<T: Any> { f: Box<T>, /* more fields */ }
```

My general logic here is that if the ty's hir node parent is another ty, then it's probably just a misspelled `dyn Trait`. There is no perfect heuristic here, but I think it's *less* invasive to suggest the most naive thing here, which is just to insert `dyn`, unless we're very confident it will be wrong.

File: tests/ui/dyn-keyword/suggest-struct-or-union-add-generic-impl-trait.rs [hunk 4]
```diff
@@ -13,7 +13,6 @@ struct Foo2 {
     //~^ ERROR expected a type, found a trait
```
Comment (compiler-errors) [inline tests/ui/dyn-keyword/suggest-struct-or-union-add-generic-impl-trait.rs:13]: I moved this test out of `suggestions/` since that's a kitchen sink

File: compiler/rustc_hir_analysis/src/hir_ty_lowering/lint.rs [hunk 5]
```diff
@@ -198,32 +232,59 @@ impl<'tcx> dyn HirTyLowerer<'tcx> + '_ {
...
+            | hir::Node::PatExpr(_)
+            | hir::Node::PathSegment(_)
+            | hir::Node::AssocItemConstraint(_)
+            | hir::Node::TraitRef(_)
+            | hir::Node::Item(_)
+            | hir::Node::WherePredicate(_) => {}
 
-        // If the parent item is a struct, check if self_ty is the last field.
-        if let hir::ItemKind::Struct(variant_data, _) = parent_item.kind {
-            if variant_data.fields().last().unwrap().ty.span != self_ty.span {
```
Comment (compiler-errors) [inline compiler/rustc_hir_analysis/src/hir_ty_lowering/lint.rs:219]: We don't need to use span comparisons here, `hir_id` comparisons are more faithful.

File: compiler/rustc_hir_analysis/src/hir_ty_lowering/lint.rs [hunk 6]
```diff
@@ -123,31 +126,62 @@ impl<'tcx> dyn HirTyLowerer<'tcx> + '_ {
...
+        let Ok(rendered_ty) = tcx.sess.source_map().span_to_snippet(self_ty.span) else {
+            return false;
+        };
+
+        let param = "TUV"
+            .chars()
+            .map(|c| c.to_string())
+            .chain((0..).map(|i| format!("P{i}")))
+            .find(|s| !generics.params.iter().any(|param| param.name.ident().as_str() == s))
+            .expect("we definitely can find at least one param name to generate");
```
Comment (compiler-errors) [inline compiler/rustc_hir_analysis/src/hir_ty_lowering/lint.rs:173]: This logic didn't account for preexisting generic args, so this tries its best to suggest `T, U, V, P1, P2, ..`.

**Comment by nnethercote** [comment]
@bors r+

Thank for fixing the problems.

**Comment by nnethercote** [comment]
cc @xizheyin

**Comment by compiler-errors** [comment]
error path only so

 @bors rollup
