### PR TITLE
Fix -Zmeta-stats ICE by giving `FileEncoder` file read permissions

### LINKED ISSUE #101001: -Zmeta-stats ICE: with thread 'rustc' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 5, kind: PermissionDenied, message: "Access is denied." }
`-Zmeta-stats` started ICEing between nightly-2022-07-15 and nightly-2022-07-16, looking at diff https://github.com/rust-lang/rust/compare/c2f428d2f3340a0e7d995f4726223db91b93704c...23e21bdd25026e2839ebe946c2a937c1904887d2 it's probably https://github.com/rust-lang/rust/pull/96544, so @m-ysk ?

### Code

```
cargo new --lib hello
cd hello
RUSTFLAGS="-Zmeta-stats" cargo build
```

### Meta

`rustc --version --verbose`:
```
rustc 1.65.0-nightly (e1b28cd2f 2022-08-19)
binary: rustc
commit-hash: e1b28cd2f16bd5b832183d7968cae3bb9213e78d
commit-date: 2022-08-19
host: x86_64-pc-windows-msvc
release: 1.65.0-nightly
LLVM version: 15.0.0
```

### Error output

```
<output>
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
thread 'rustc' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 5, kind: PermissionDenied, message: "Access is denied." }', compiler\rustc_metadata\src\rmeta\encoder.rs:774:22
stack backtrace:
   0:     0x7fffb7e59982 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h6af6f9f3a4c35d3a
   1:     0x7fffb7e94c8b - core::fmt::write::he3f07bcff4ed6652
   2:     0x7fffb7e4c48a - <std::io::IoSliceMut as core::fmt::Debug>::fmt::hf6257fd727ae80d5
   3:     0x7fffb7e5d254 - std::panicking::default_hook::hb6687dad6f786ea1
   4:     0x7fffb7e5ce8a - std::panicking::default_hook::hb6687dad6f786ea1
   5:     0x7fff99b8a9f2 - rustc_driver[1d98c199491bd8cd]::describe_lints
   6:     0x7fffb7e5dc52 - std::panicking::rust_panic_with_hook::hf223e88fa60de009
   7:     0x7fffb7e5d9dd - <std::panicking::begin_panic_handler::StrPanicPayload as core::panic::BoxMeUp>::get::h230f1146d8ddd341
   8:     0x7fffb7e5a67f - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h6af6f9f3a4c35d3a
   9:     0x7fffb7e5d6a0 - rust_begin_unwind
  10:     0x7fffb7ec9f35 - core::panicking::panic_fmt::he533ea2e8c7ab1f5
  11:     0x7fffb7eca0b3 - core::result::unwrap_failed::ha67da4e5ef765d0c
  12:     0x7fff99665e50 - <rustc_metadata[24368a714c5ae756]::rmeta::encoder::EncodeContext as rustc_type_ir[15febabf03c45dc7]::codec::TyEncoder>::predicate_shorthands
  13:     0x7fff980fc525 - rustc_metadata[24368a714c5ae756]::rmeta::encoder::encode_metadata
  14:     0x7fff980fdd6c - <rustc_metadata[24368a714c5ae756]::rmeta::encoder::EncodeContext as rustc_serialize[3bf25e14274047cb]::serialize::Encoder>::emit_raw_bytes
  15:     0x7fff980fba6e - rustc_metadata[24368a714c5ae756]::rmeta::encoder::encode_metadata
  16:     0x7fff980f4711 - rustc_metadata[24368a714c5ae756]::fs::encode_and_write_metadata
  17:     0x7fff974c3b0c - <rustc_interface[3b6d288906cb4b04]::passes::LintStoreExpandImpl as rustc_expand[4331ab26a72f6383]::base::LintStoreExpand>::pre_expansion_lint
  18:     0x7fff974b00dc - <rustc_interface[3b6d288906cb4b04]::queries::Queries>::ongoing_codegen
  19:     0x7fff97466c69 - <unknown>
  20:     0x7fff974630eb - <unknown>
  21:     0x7fff97486532 - <unknown>
  22:     0x7fff9749d727 - rustc_driver[1d98c199491bd8cd]::args::arg_expand_all
  23:     0x7fff97466449 - <unknown>
  24:     0x7fff9748cbed - <unknown>
  25:     0x7fffb7e6e41c - std::sys::windows::thread::Thread::new::h5a05fdb6284bcf7c
  26:     0x7ff800497034 - BaseThreadInitThunk
  27:     0x7ff802e22651 - RtlUserThreadStart

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.65.0-nightly (e1b28cd2f 2022-08-19) running on x86_64-pc-windows-msvc

note: compiler flags: --crate-type lib -C embed-bitcode=no -C debuginfo=2 -Z meta-stats
```

</p>
</details>

### PR DESCRIPTION
**Pull request by isikkema**
Fixes #101001

As far as I can tell, #101001 is caused because the file is being created with write-only permissions here: https://github.com/rust-lang/rust/blob/master/compiler/rustc_serialize/src/opaque.rs#L196

but it is trying to be read here: https://github.com/rust-lang/rust/blob/master/compiler/rustc_metadata/src/rmeta/encoder.rs#L780

This PR attempts to fix this by creating/opening the file with the same permissions as `File::create()` with the addition of read.

### CODE REVIEW

File: compiler/rustc_serialize/src/opaque.rs [hunk 1]
```diff
@@ -193,7 +193,7 @@ impl FileEncoder {
         // shaves an instruction off those code paths (on x86 at least).
         assert!(capacity <= usize::MAX - max_leb128_len());
 
-        let file = File::create(path)?;
+        let file = File::options().read(true).write(true).create(true).truncate(true).open(path)?;
```
Comment (nnethercote) [inline compiler/rustc_serialize/src/opaque.rs:196]: Please add a comment explaining this. E.g. "Open the file for reading and writing, because some encoders do both (e.g. the metadata encoder when `-Zmeta-stats` is enabled)."

**Comment by nnethercote** [comment]
I hit this ICE today and I can confirm that this PR fixes it. Please add the suggested comment and then we are good to go.

(It would also be good to have a `src/test/ui/` test for this feature, to catch any obvious breakage in the future. But that might be tricky to do if the byte sizes vary on different platforms, so I won't block this PR on that.)

@bors delegate=isikkema

**Comment by isikkema** [comment]
@bor r+ rollup
