### PR TITLE
Use `track_errors` instead of hand rolling

### LINKED ISSUE #59215: Use `track_errors` instead of hand-rolling such a check
Const eval asserts that reporting an error for statics actually worked. This is not only done in a wrong way (checks for no error having happened in the entire compilation), it's also very fragile. We should instead use the `track_errors` method around the `report_as_error` call, and in case `track_errors` returns `Ok`, we need to do the `delay_span_bug`.

The relevant code that needs to be changed can be found in https://github.com/rust-lang/rust/blob/16e7e05e95a6a5a1e0dba54ae722274bd7d725f7/src/librustc_mir/const_eval.rs#L645-L654

### PR DESCRIPTION
**Pull request by JohnTitor**
Fixes #59215 

r? @oli-obk

### CODE REVIEW

File: src/librustc_mir/const_eval.rs [hunk 1]
```diff
@@ -647,10 +647,14 @@ pub fn const_eval_raw_provider<'a, 'tcx>(
                                                    "could not evaluate static initializer");
             // Ensure that if the above error was either `TooGeneric` or `Reported`
             // an error must be reported.
-            if tcx.sess.err_count() == 0 {
-                tcx.sess.delay_span_bug(err.span,
+            let errs = tcx.sess.track_errors(|| {
```
Comment (oli-obk) [inline src/librustc_mir/const_eval.rs]: You should put the `err.report_as_error(...)` call above into the closure. We don't need the `err_count` call anymore, it's done by `track_errors`.

The idea was to ensure that calling `report_as_error` actually reports any errors.

You should then be able to yield the values inside the `Err` and `Ok` variants instead of having to carry the `reported_err` variable around

Comment (JohnTitor) [reply src/librustc_mir/const_eval.rs]: I get the point, removed `err_count`.

File: src/librustc_mir/const_eval.rs [hunk 2]
```diff
@@ -647,10 +647,15 @@ pub fn const_eval_raw_provider<'a, 'tcx>(
                                                    "could not evaluate static initializer");
             // Ensure that if the above error was either `TooGeneric` or `Reported`
             // an error must be reported.
-            if tcx.sess.err_count() == 0 {
-                tcx.sess.delay_span_bug(err.span,
+            let tracked_err = tcx.sess.track_errors(|| {
+                err.report_as_error(ecx.tcx,
```
Comment (oli-obk) [inline src/librustc_mir/const_eval.rs]: You should remove the `report_as_error` call above. I'm not sure what types `tracked_err` has, but the `Ok` path should give you the same value that you got previously in `reported_err`. What's the value in the `Err` part?

Comment (JohnTitor) [reply src/librustc_mir/const_eval.rs]: Please let me ask you two questions.

1. What should I place instead of `report_as_error`?
2. How I check if `track_err` returns `Ok`?

Comment (oli-obk) [reply src/librustc_mir/const_eval.rs]: for 2. you are already checking that via the `match` below. You can pattern match on the `Ok` value via `Ok(reported_err)`.

for 1. nothing, you already are calling it inside of the `track_errors` call, so you are replacing it with the `tcx.sess.track_errors(|| { err.report_as_error ....`

Comment (JohnTitor) [reply src/librustc_mir/const_eval.rs]: Okay, thank you! And what should I do in the `Err` part?

Comment (oli-obk) [reply src/librustc_mir/const_eval.rs]: I'm not sure, that depends on what is returned there. Have a look at the return type and emit an apropriate `ErrorHandled` enum variant

Comment (JohnTitor) [reply src/librustc_mir/const_eval.rs]: I pushed WIP commit. Test will be failed because types are incompatible in `match`. 
But I want to know if my work is correct so far. Could you check this?

Comment (oli-obk) [reply src/librustc_mir/const_eval.rs]: Yes, this is correct so far.

In the `Ok` arm, the return value should be `v` I believe. The `Err` pattern can probably be `Err(ErrorReported)` and the arm value `ErrorHandled::Reported` (or whatever the correct variant is).

Comment (JohnTitor) [reply src/librustc_mir/const_eval.rs]: I modified as follows:

```Rust
match reported_err {
    Ok(v) => {
        tcx.sess.delay_span_bug(err.span,
                            &format!("static eval failure did not emit an error: {:#?}",
                            v));
        v
    },
    Err(ErrorReported) => ErrorReported,
}
```

but `()` is returned in the `Ok` arm and `rustc::util::common::ErrorReported` is returned in the `Err` arm, so the compile is failed. Any solutions?

File: src/librustc_mir/const_eval.rs [hunk 3]
```diff
@@ -643,14 +643,17 @@ pub fn const_eval_raw_provider<'a, 'tcx>(
...
         if tcx.is_static(def_id).is_some() {
-            let reported_err = err.report_as_error(ecx.tcx,
-                                                   "could not evaluate static initializer");
             // Ensure that if the above error was either `TooGeneric` or `Reported`
             // an error must be reported.
-            if tcx.sess.err_count() == 0 {
-                tcx.sess.delay_span_bug(err.span,
+            let reported_err = tcx.sess.track_errors(|| {
+                err.report_as_error(ecx.tcx,
+                                    "could not evaluate static initializer");
```
Comment (oli-obk) [inline src/librustc_mir/const_eval.rs]: The `;` here drops the value you'd get for `v` and makes it `()`.

Removing the `;` here should fix your problem

Comment (JohnTitor) [reply src/librustc_mir/const_eval.rs]: Thank you! I dropped `;` but the compile was failed. However, the error message was changed.

```
error[E0308]: mismatched types==================================>    ] 128/137: rustc_mir
   --> src/librustc_mir/const_eval.rs:657:21
    |
657 |                     v
    |                     ^ expected (), found enum `rustc::mir::interpret::ErrorHandled`
    |
    = note: expected type `()`
               found type `rustc::mir::interpret::ErrorHandled`
```

related code is here:

```Rust

if tcx.is_static(def_id).is_some() {
    // Ensure that if the above error was either `TooGeneric` or `Reported`
    // an error must be reported.
    let reported_err = tcx.sess.track_errors(|| {
        err.report_as_error(ecx.tcx,
                            "could not evaluate static initializer")
    });
    match reported_err {
        Ok(v) => {
            tcx.sess.delay_span_bug(err.span,
                                &format!("static eval failure did not emit an error: {:#?}",
                                v));
            v
        },
        Err(ErrorReported) => Err(ErrorHandled::Reported),
    }
    reported_err
}
```

Comment (oli-obk) [reply src/librustc_mir/const_eval.rs]: The match isn't returning the values written in it, because you have a trailing expression (`reported_err`) afterwards. Removing that will make the `match` the trailing expression

Comment (JohnTitor) [reply src/librustc_mir/const_eval.rs]: I got it, modified and pushed.

File: src/librustc_mir/const_eval.rs [hunk 4]
```diff
@@ -643,16 +643,21 @@ pub fn const_eval_raw_provider<'a, 'tcx>(
...
+            });
+            match reported_err {
+                Ok(v) => {
+                    tcx.sess.delay_span_bug(err.span,
                                         &format!("static eval failure did not emit an error: {:#?}",
-                                                 reported_err));
+                                        v));
+                    v
+                },
+                Err(ErrorReported) => ErrorHandled::Reported,
```
Comment (lzutao) [inline src/librustc_mir/const_eval.rs]: try `Err(_) => ...`

Comment (JohnTitor) [reply src/librustc_mir/const_eval.rs]: Thank you @lzutao, it seems good!

**Comment by JohnTitor** [comment]
@oli-obk Is there anything I can do?

File: src/librustc_mir/const_eval.rs [hunk 5]
```diff
@@ -643,16 +643,21 @@ pub fn const_eval_raw_provider<'a, 'tcx>(
...
+            });
+            match reported_err {
+                Ok(v) => {
+                    tcx.sess.delay_span_bug(err.span,
                                         &format!("static eval failure did not emit an error: {:#?}",
-                                                 reported_err));
+                                        v));
+                    v
+                },
+                Err(_) => ErrorHandled::Reported,
```
Comment (oli-obk) [inline src/librustc_mir/const_eval.rs]: Please import https://doc.rust-lang.org/nightly/nightly-rustc/rustc/util/common/struct.ErrorReported.html in this module and use `ErrorReported` instead of `_`, so future changes to `track_errors` will get noticed here

Comment (JohnTitor) [reply src/librustc_mir/const_eval.rs]: Hmm, commit 14b61f79d0c34899ed028b9dbcb5094d04078b26 couldn't be green because `ErrorReported` was unused. How do we use it?

Comment (oli-obk) [reply src/librustc_mir/const_eval.rs]: The problem was that you didn't have a `use` statement to import the type. Since it wasn't imported, the compiler thought you had a variable named `ErrorReported` instead of knowing that you meant the type. You can search in the rust source for existing `use` statements that mention `ErrorReported` and create one in this file.

**Comment by lzutao** [comment]
@JohnTitor You might need to rebase on master. Now we have 384 commits in this PR.

File: src/librustc_mir/const_eval.rs (hunk 5 above)
Comment (JohnTitor) [reply src/librustc_mir/const_eval.rs]: Oh, I got it! My fork is old so `ErrorReported` is already imported. But current Rust source doesn't have it. And I have mistake on Git, please wait...

**Comment by JohnTitor** [comment]
@lzutao yes, I'll fix.

**Comment by JohnTitor** [comment]
@oli-obk Uh, if you allow me, I'd like to delete this branch and re-open PR, sorry...

**Comment by oli-obk** [comment]
@bors r+

Thanks for doing this and seeing this through all the changes!
