### PR TITLE
Detect when method call on argument could be removed to fulfill failed trait bound

### LINKED ISSUE #71252: Calling `.into()` on argument that expects `Into<Type>` gives confusing error
When calling `(x: Type)::into()` in a fn that expects `Into<Type>` we currently emit:

```
error[E0283]: type annotations needed
    --> src/librustc_resolve/late/diagnostics.rs:1143:21
     |
1143 |                 err.span_note(spans.into(), "these named lifetimes are available to use");
     |                     ^^^^^^^^^ ------------ this method call resolves to `T`
     |                     |
     |                     cannot infer type for type parameter `S` declared on the method `span_note`
     |
     = note: cannot resolve `_: std::convert::Into<rustc_span::MultiSpan>`
```

We should check whether `T == MultiSpan` and suggest the removal of the `into()` call.

### PR DESCRIPTION
**Pull request by estebank**
When encountering

```rust
struct Foo;
struct Bar;
impl From<Bar> for Foo {
    fn from(_: Bar) -> Self { Foo }
}
fn qux(_: impl From<Bar>) {}
fn main() {
    qux(Bar.into());
}
```

Suggest removing `.into()`:

```
error[E0283]: type annotations needed
 --> f100.rs:8:13
  |
8 |     qux(Bar.into());
  |     ---     ^^^^
  |     |
  |     required by a bound introduced by this call
  |
  = note: cannot satisfy `_: From<Bar>`
note: required by a bound in `qux`
 --> f100.rs:6:16
  |
6 | fn qux(_: impl From<Bar>) {}
  |                ^^^^^^^^^ required by this bound in `qux`
help: try using a fully qualified path to specify the expected types
  |
8 |     qux(<Bar as Into<T>>::into(Bar));
  |         +++++++++++++++++++++++   ~
help: consider removing this method call, as the receiver has type `Bar` and `Bar: From<Bar>` trivially holds
  |
8 -     qux(Bar.into());
8 +     qux(Bar);
  |
```

Fix #71252

### CODE REVIEW

File: compiler/rustc_trait_selection/src/traits/error_reporting/suggestions.rs [hunk 1]
```diff
@@ -3961,6 +3961,26 @@ impl<'tcx> TypeErrCtxtExt<'tcx> for TypeErrCtxt<'_, 'tcx> {
...
+                    .evaluate_obligation_no_overflow(&Obligation::misc(
+                        tcx, expr.span, body_id, param_env, pred,
+                    ))
+                    .must_apply_modulo_regions()
+            {
+                err.span_suggestion_verbose(
+                    expr.span.with_lo(rcvr.span.hi()),
+                    format!(
+                        "consider removing this method call, as the receiver has type `{ty}` and \
+                         `{pred}` can be fulfilled",
```
Comment (compiler-errors) [inline compiler/rustc_trait_selection/src/traits/error_reporting/suggestions.rs:3978]:
```suggestion
                         `{pred}` is trivial",
```

or "trivially holds"

Comment (estebank) [reply compiler/rustc_trait_selection/src/traits/error_reporting/suggestions.rs:3978]: @compiler-errors do we ever use that wording in user-facing messages? AFAICT we only use that wording for other compiler devs.

Comment (compiler-errors) [reply compiler/rustc_trait_selection/src/traits/error_reporting/suggestions.rs:3978]: I could say the same about "fulfilled". I don't believe the original wording gets across the fact that the method call is *redundant*, which is what I think this should be pointing out.

Comment (compiler-errors) [reply compiler/rustc_trait_selection/src/traits/error_reporting/suggestions.rs:3978]: The point that I'm trying to make is that the wording should explain to the user *why* removing the method call is beneficial, which I don't believe it is doing right now; rn it's just stating facts

Comment (estebank) [reply compiler/rustc_trait_selection/src/traits/error_reporting/suggestions.rs]: @compiler-errors yeah, that makes sense. Initially I was thinking "well, there could be cases where the predicate is actually more complex and the `Self` is something like an assoc type or impl Trait", but thinking about it for just a minute was enough to realize that you're right and "yes, every case where this would work would be a trivial obligation".

Comment (wesleywiser) [reply compiler/rustc_trait_selection/src/traits/error_reporting/suggestions.rs]: I like "is trivial" better than "can be fulfilled" 👍 

I wonder if something even simpler would work ("is valid" or "is true" perhaps)?

File: compiler/rustc_trait_selection/src/traits/error_reporting/suggestions.rs [hunk 2]
```diff
@@ -3961,6 +3961,26 @@ impl<'tcx> TypeErrCtxtExt<'tcx> for TypeErrCtxt<'_, 'tcx> {
         if let Node::Expr(expr) = tcx.hir_node(arg_hir_id)
             && let Some(typeck_results) = &self.typeck_results
         {
+            if let hir::Expr { kind: hir::ExprKind::MethodCall(_, rcvr, _, _), .. } = expr
+                && let Some(ty) = typeck_results.node_type_opt(rcvr.hir_id)
+                && let Some(failed_pred) = failed_pred.to_opt_poly_trait_pred()
+                && let pred = failed_pred.skip_binder().with_self_ty(tcx, ty)
```
Comment (compiler-errors) [inline compiler/rustc_trait_selection/src/traits/error_reporting/suggestions.rs:3967]: use `map_bound` here. otherwise, it's gonna ICE because you're skipping binders.

File: compiler/rustc_trait_selection/src/traits/error_reporting/suggestions.rs [hunk 3]
```diff
@@ -3961,6 +3961,26 @@ impl<'tcx> TypeErrCtxtExt<'tcx> for TypeErrCtxt<'_, 'tcx> {
...
+                && self
+                    .evaluate_obligation_no_overflow(&Obligation::misc(
```
Comment (compiler-errors) [inline compiler/rustc_trait_selection/src/traits/error_reporting/suggestions.rs:3969]: why did you use `evaluate_obligation_no_overflow` here? please use `predicate_may_hold_modulo_regions`.

**Review by compiler-errors — CHANGES_REQUESTED** [review]
r=me after nits

**Comment by compiler-errors** [comment]
Why did you use predicate_may_hold? That can hold even if there is inference that still needs to be made. Could you use predicate_may_hold_modulo_regions? False positives here feel like they would be really confusing.

@bors r-

**Comment by compiler-errors** [comment]
Also, is there a reason why you left out the test from the PR description? None of the UI tests that were changed are trait ambiguity errors, just regular trait failures. Please add that test, too.

**Comment by estebank** [comment]
Updated 

@bors r=compiler-errors

**Comment by estebank** [comment]
> Why did you use predicate_may_hold? That can hold even if there is inference that still needs to be made. Could you use predicate_may_hold_modulo_regions?

I got confused between `predicate_may_hold` and `predicate_must_hold_modulo_regions`. That's what I get for multitasking paying half attention.
