### PR TITLE
Tweak impl signature mismatch errors involving `RegionKind::ReVar` lifetimes

### LINKED ISSUE #41343: Misleading error when a trait method implementation has explicit lifetime parameters but the trait signature does not.
Consider this example ([playground](https://play.rust-lang.org/?gist=f6e6314f04cbe19a3f30d1e03208a281&version=nightly&backtrace=0)):
```
use std::vec::Vec;
use std::option::Option;

trait MyTrait {
    fn bar(&self, vec: &Vec<u32>) -> Option<&u32>;
}

struct Foo;

impl MyTrait for Foo {
    fn bar<'a>(&self, vec: &'a Vec<u32>) -> Option<&'a u32> {
        vec.get(0)
    }
}
```

The error message is:

```
rustc 1.18.0-nightly (7627e3d31 2017-04-16)
error[E0495]: cannot infer an appropriate lifetime for lifetime parameter 'a in generic type due to conflicting requirements
  --> <anon>:11:5
   |
11 |       fn bar<'a>(&self, vec: &'a Vec<u32>) -> Option<&'a u32> {
   |  _____^ starting here...
12 | |         vec.get(0)
13 | |     }
   | |_____^ ...ending here
   |
note: first, the lifetime cannot outlive the anonymous lifetime #2 defined on the body at 11:60...
  --> <anon>:11:61
   |
11 |       fn bar<'a>(&self, vec: &'a Vec<u32>) -> Option<&'a u32> {
   |  _____________________________________________________________^ starting here...
12 | |         vec.get(0)
13 | |     }
   | |_____^ ...ending here
note: ...so that method type is compatible with trait (expected fn(&Foo, &std::vec::Vec<u32>) -> std::option::Option<&u32>, found fn(&Foo, &std::vec::Vec<u32>) -> std::option::Option<&u32>)
  --> <anon>:11:5
   |
11 |       fn bar<'a>(&self, vec: &'a Vec<u32>) -> Option<&'a u32> {
   |  _____^ starting here...
12 | |         vec.get(0)
13 | |     }
   | |_____^ ...ending here
note: but, the lifetime must be valid for the anonymous lifetime #1 defined on the body at 11:60...
  --> <anon>:11:61
   |
11 |       fn bar<'a>(&self, vec: &'a Vec<u32>) -> Option<&'a u32> {
   |  _____________________________________________________________^ starting here...
12 | |         vec.get(0)
13 | |     }
   | |_____^ ...ending here
note: ...so that method type is compatible with trait (expected fn(&Foo, &std::vec::Vec<u32>) -> std::option::Option<&u32>, found fn(&Foo, &std::vec::Vec<u32>) -> std::option::Option<&u32>)
  --> <anon>:11:5
   |
11 |       fn bar<'a>(&self, vec: &'a Vec<u32>) -> Option<&'a u32> {
   |  _____^ starting here...
12 | |         vec.get(0)
13 | |     }
   | |_____^ ...ending here

error: aborting due to previous error
```

All of the text of the error is focussed on the body of the function, even though there are no lifetime problems in the body with respect to the signature of the surrounding function. The actual error is that the signatures of the trait method and its implementation do not match.

### LINKED ISSUE #66406: Regression in helpful compiler error message when working with lifetimes
So I have the following code:
```
struct Article {
    proof_reader: ProofReader,
}

struct ProofReader {
    name: String,
}

pub trait HaveRelationship<To> {
    fn get_relation(&self) -> To;
}

impl HaveRelationship<&ProofReader> for Article {
    fn get_relation(&self) -> &ProofReader {
        &self.proof_reader
    }
}
```
Which on the stable compiler gives this helpful error message:
```
error[E0495]: cannot infer an appropriate lifetime for lifetime parameter in generic type due to conflicting requirements
  --> src/main.rs:14:5
   |
14 |     fn get_relation(&self) -> &ProofReader {
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
note: first, the lifetime cannot outlive the anonymous lifetime #1 defined on the method body at 14:5...
  --> src/main.rs:14:5
   |
14 | /     fn get_relation(&self) -> &ProofReader {
15 | |         &self.proof_reader
16 | |     }
   | |_____^
note: ...but the lifetime must also be valid for the lifetime '_ as defined on the impl at 13:23...
  --> src/main.rs:13:23
   |
13 | impl HaveRelationship<&ProofReader> for Article {
   |                       ^
   = note: ...so that the method type is compatible with trait:
           expected fn(&Article) -> &ProofReader
              found fn(&Article) -> &ProofReader
```
Yet on the nightly compiler the compiler error does not inform me about lifetimes, but tells me the signature needs to be what it already is:
```
error: `impl` item signature doesn't match `trait` item signature
  --> src/main.rs:14:5
   |
10 |     fn get_relation(&self) -> To;
   |     ----------------------------- expected fn(&Article) -> &ProofReader
...
14 |     fn get_relation(&self) -> &ProofReader {
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ found fn(&Article) -> &ProofReader
   |
   = note: expected `fn(&Article) -> &ProofReader`
              found `fn(&Article) -> &ProofReader`
```
[playground stable version](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=313facbea2943615fb338e2ddff03e07)
[playground nightly version](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=f62a2c2bf90b45390e20be345141ea52)

### LINKED ISSUE #72106: Unhelpful error messages for trait with unbound lifetime
I was trying to implement [FromSql](https://docs.rs/rusqlite/0.13.0/rusqlite/types/trait.FromSql.html) of `rusqlite` for my reference type (with lifetime). And I faced an unclear error message, later I was explained that the trait does not allow the return type to borrow from the value argument since it doesn't specify lifetime parameter explicitly.

However, I thought that it worth filing a bug report about unhelpful error message anyway.

Here is a simplified code:

```rust
use std::error::Error;
use std::fmt;

#[derive(Copy, Clone, Debug, PartialEq)]
pub enum ValueRef<'a> {
    Null,
    Integer(i64),
    Real(f64),
    Text(&'a [u8]),
    Blob(&'a [u8]),
}

impl<'a> ValueRef<'a> {
    pub fn as_str(&self) -> FromSqlResult<&'a str> {
        match *self {
            ValueRef::Text(t) => {
                std::str::from_utf8(t).map_err(|_| FromSqlError::InvalidType)
            }
            _ => Err(FromSqlError::InvalidType),
        }
    }
}

#[derive(Debug)]
#[non_exhaustive]
pub enum FromSqlError {
    InvalidType
}

impl fmt::Display for FromSqlError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "InvalidType")
    }
}

impl Error for FromSqlError {}

pub type FromSqlResult<T> = Result<T, FromSqlError>;

pub trait FromSql: Sized {
    fn column_result(value: ValueRef<'_>) -> FromSqlResult<Self>;
}

impl FromSql for &str {
    fn column_result(value: ValueRef<'_>) -> FromSqlResult<&str> {
        value.as_str()
    }
}

pub fn main() {
    println!("{}", "Hello World");
}
```

The error message I'm getting is:

```rust
error: `impl` item signature doesn't match `trait` item signature
  --> src/main.rs:45:5
   |
41 |     fn column_result(value: ValueRef<'_>) -> FromSqlResult<Self>;
   |     ------------------------------------------------------------- expected fn(ValueRef<'_>) -> std::result::Result<&str, FromSqlError>
...
45 |     fn column_result(value: ValueRef<'_>) -> FromSqlResult<&str> {
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ found fn(ValueRef<'_>) -> std::result::Result<&str, FromSqlError>
   |
   = note: expected `fn(ValueRef<'_>) -> std::result::Result<&str, FromSqlError>`
              found `fn(ValueRef<'_>) -> std::result::Result<&str, FromSqlError>`

error: aborting due to previous error

error: could not compile `playground`.

To learn more, run the command again with --verbose.
```

So basically it says that I have a wrong signature, even though the *expected* and *found* signatures are the same.

I'm not sure what would be the right error message to raise here since I don't know lifetime rules quite well.

Here is, just in case, a link to [playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=5a524f07d85f03edaec061f8610b2614)

The rust version I'm using is: `1.44.0-nightly`, but it also reproduces on `1.43.1`.

### PR DESCRIPTION
**Pull request by estebank**
Fix #66406, fix #72106.

```
error: `impl` item signature doesn't match `trait` item signature
  --> $DIR/trait-param-without-lifetime-constraint.rs:14:5
   |
LL |     fn get_relation(&self) -> To;
   |     ----------------------------- expected `fn(&Article) -> &ProofReader`
...
LL |     fn get_relation(&self) -> &ProofReader {
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ found `fn(&Article) -> &ProofReader`
   |
   = note: expected `fn(&Article) -> &ProofReader`
              found `fn(&Article) -> &ProofReader`
help: the lifetime requirements from the `impl` do not correspond to the requirements in the `trait`
  --> $DIR/trait-param-without-lifetime-constraint.rs:10:31
   |
LL |     fn get_relation(&self) -> To;
   |                               ^^ consider borrowing this type parameter in the trait
```

r? @nikomatsakis

### CODE REVIEW

**Comment by estebank** [comment]
CC @rust-lang/wg-diagnostics we should probably have a follow up to detect these cases in particular and explain that the `self` lifetime is not tied to the return type's lifetime in a clearer way.

**Comment by estebank** [comment]
Screen Shot 2019-12-20 at 12 11 06 PM

**Comment by estebank** [comment]
New output:
Screen Shot 2019-12-22 at 1 53 29 PM
Screen Shot 2019-12-22 at 1 53 34 PM

File: src/librustc/infer/error_reporting/nice_region_error/trait_impl_difference.rs [hunk 1]
```diff
@@ -46,14 +51,87 @@ impl<'a, 'tcx> NiceRegionError<'a, 'tcx> {
...
-        err.span_label(impl_sp, &format!("expected {:?}", expected));
+        err.span_label(trait_sp, &format!("expected {:?}", expected));
+        let trait_fn_sig = tcx.fn_sig(trait_def_id);
+
+        struct AssocTypeFinder(FxHashSet<ty::ParamTy>);
+        impl<'tcx> ty::fold::TypeVisitor<'tcx> for AssocTypeFinder {
+            fn visit_ty(&mut self, ty: Ty<'tcx>) -> bool {
+                debug!("assoc type finder ty {:?} {:?}", ty, ty.kind);
+                match ty.kind {
+                    ty::Param(param) => {
```
Comment (Centril) [inline src/librustc/infer/error_reporting/nice_region_error/trait_impl_difference.rs]: `if let`?

File: src/librustc/infer/error_reporting/nice_region_error/trait_impl_difference.rs [hunk 2]
```diff
@@ -46,14 +51,87 @@ impl<'a, 'tcx> NiceRegionError<'a, 'tcx> {
...
+            }
+        }
+        let mut visitor = AssocTypeFinder(FxHashSet::default());
+        trait_fn_sig.output().visit_with(&mut visitor);
+
+        if let Some(id) = tcx.hir().as_local_hir_id(trait_def_id) {
+            let parent_id = tcx.hir().get_parent_item(id);
+            let trait_item = tcx.hir().expect_item(parent_id);
+            if let hir::ItemKind::Trait(_, _, generics, _, _) =  &trait_item.kind {
+                for param_ty in visitor.0 {
```
Comment (Centril) [inline src/librustc/infer/error_reporting/nice_region_error/trait_impl_difference.rs]: Iterating a `FxHashMap` --> non-determinism in errors?

File: src/librustc/infer/error_reporting/nice_region_error/trait_impl_difference.rs [hunk 3]
```diff
@@ -46,14 +51,87 @@ impl<'a, 'tcx> NiceRegionError<'a, 'tcx> {
...
+                    if let Some(generic) = generics.get_named(param_ty.name) {
+                        err.span_label(generic.span, &format!(
+                            "in order for `impl` items to be able to implement the method, this \
```
Comment (Centril) [inline src/librustc/infer/error_reporting/nice_region_error/trait_impl_difference.rs]:
```suggestion
                            "for `impl` items to implement the method, this \
```

File: src/librustc/infer/error_reporting/nice_region_error/trait_impl_difference.rs [hunk 4]
```diff
@@ -46,14 +51,87 @@ impl<'a, 'tcx> NiceRegionError<'a, 'tcx> {
...
         let mut err = self.tcx().sess.struct_span_err(
             sp,
             "`impl` item signature doesn't match `trait` item signature",
         );
-        err.note(&format!("expected `{:?}`\n   found `{:?}`", expected, found));
         err.span_label(sp, &format!("found {:?}", found));
-        err.span_label(impl_sp, &format!("expected {:?}", expected));
+        err.span_label(trait_sp, &format!("expected {:?}", expected));
+        let trait_fn_sig = tcx.fn_sig(trait_def_id);
+
```
Comment (Centril) [inline src/librustc/infer/error_reporting/nice_region_error/trait_impl_difference.rs]: If you could sprinkle some more comments in the code below that'd be good. :)

File: src/librustc/infer/error_reporting/nice_region_error/trait_impl_difference.rs [hunk 5]
```diff
@@ -46,14 +51,87 @@ impl<'a, 'tcx> NiceRegionError<'a, 'tcx> {
...
+                found,
+            })
+        }) {
+            err.note_expected_found(&"", expected, &"", found);
+        } else {
+            // This fallback shouldn't be necessary, but let's keep it in just in case.
+            err.note(&format!("expected `{:?}`\n   found `{:?}`", expected, found));
+        }
+        if note {
+            err.note("the lifetime requirements from the `trait` could not be fulfilled by the \
```
Comment (Centril) [inline src/librustc/infer/error_reporting/nice_region_error/trait_impl_difference.rs]:
```suggestion
            err.note("the lifetime requirements from the `trait` could not be satisfied by the \
```
(We use "satisfied" for trait bounds so why not for lifetimes?)

File: src/librustc/infer/error_reporting/nice_region_error/trait_impl_difference.rs (hunk 2 above)
Comment (estebank) [reply src/librustc/infer/error_reporting/nice_region_error/trait_impl_difference.rs]: It's an `FxHashSet`, but the point stands. I think this is unlikely to cause any real issues in practice because we are just pointing at the spans, stderr tests do not care what order the labels got populated in.

Comment (Centril) [reply src/librustc/infer/error_reporting/nice_region_error/trait_impl_difference.rs]: It's unlikely yes, but `.stderr` tests not caring is something that might not hold forever, and this is an error path, so why not just use an `FxIndexSet` instead?

Comment (estebank) [reply src/librustc/infer/error_reporting/nice_region_error/trait_impl_difference.rs]: done

File: src/test/ui/traits/trait-param-without-lifetime-constraint.stderr [hunk 6]
```diff
@@ -0,0 +1,18 @@
+error: `impl` item signature doesn't match `trait` item signature
+  --> $DIR/trait-param-without-lifetime-constraint.rs:14:5
+   |
+LL | pub trait HaveRelationship<To> {
+   |                            -- for `impl` items to implement the method, this type parameter might need a lifetime restriction like `To: 'a`
```
Comment (nikomatsakis) [inline src/test/ui/traits/trait-param-without-lifetime-constraint.stderr]: this seems sort of misleading, no? 

That is, I think the proper fix here is

```rust
impl<'a> HaveRelationship<&'a ProofReader> for Article {
    fn get_relation(&self) -> &'a ProofReader {
    //~^ ERROR `impl` item signature doesn't match `trait` item signature
        &self.proof_reader
    }
}
```

but I'm not sure how the new error would lead me there....

Comment (estebank) [reply src/test/ui/traits/trait-param-without-lifetime-constraint.stderr]: But that [doesn't work](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=35c96eeb7efc21a652520c1572720cf3) either because `HaveRelationship` needs a lifetime so that `get_relation` takes a `&'a self` instead of `&self`. Shouldn't the correct [change be](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=a9952985c9126cfdc588c0429f8961fa)?:

```rust
pub trait HaveRelationship<'a, To: 'a> {
    fn get_relation(&'a self) -> To;
}

impl<'a> HaveRelationship<'a, &'a ProofReader> for Article {
    fn get_relation(&'a self) -> &'a ProofReader {
        &self.proof_reader
    }
}
```

Comment (nikomatsakis) [reply src/test/ui/traits/trait-param-without-lifetime-constraint.stderr]: Let's discuss this in the issue :)

**Comment by estebank** [comment]
@nikomatsakis let me know if the new output is closer to what you'd want.

**Comment by Centril** [comment]
Let's try r? @davidtwco

File: src/test/ui/traits/trait-param-without-lifetime-constraint.stderr [hunk 7]
```diff
@@ -0,0 +1,21 @@
+error: `impl` item signature doesn't match `trait` item signature
```
Comment (nikomatsakis) [inline src/test/ui/traits/trait-param-without-lifetime-constraint.stderr]: hmm, so I personally still find this fairly confusing :(

The current output is

```
error: `impl` item signature doesn't match `trait` item signature
  --> src/main.rs:14:5
   |
10 |     fn get_relation(&self) -> To;
   |     ----------------------------- expected fn(&Article) -> &ProofReader
...
14 |     fn get_relation(&self) -> &ProofReader {
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ found fn(&Article) -> &ProofReader
   |
   = note: expected `fn(&Article) -> &ProofReader`
              found `fn(&Article) -> &ProofReader`
```

the point here is to warn folks that they may have wanted `-> &To` in the trait, though if they do that, they also need to change the impl to `HaveRelationship<ProofReader>`, right? (which the new error doesn't hint at)

Hmm, this is tricky.

Comment (nikomatsakis) [reply src/test/ui/traits/trait-param-without-lifetime-constraint.stderr]: I think my ideal message might look something like this

```
error: `impl` item signature doesn't match `trait` item signature
  --> src/main.rs:14:5
   |
10 |     fn get_relation(&self) -> To;
   |                               -- maybe you want `&To` here instead?
...
13 |  impl HaveRelationship<&ProofReader> for Article { 
   |                        - let's call this lifetime `'1`
14 |     fn get_relation(&self) -> &ProofReader {
   |                     -         ^^^^^^^^^^^^ impl returns reference with lifetime `'2` but trait declares lifetime `'1`
   |                     |
   |                     let's call this lifetime `'2`
   |
   = note: expected `fn(&Article) -> &ProofReader`
              found `fn(&Article) -> &ProofReader`
```

(ignoring the fact that the "maybe you want" should ideally come as a separate chunk at the end)

**Comment by davidtwco** [comment]
I'll assign this back to @nikomatsakis since they've left a review in the time it took me to get to this.

r? @nikomatsakis

File: src/test/ui/traits/trait-param-without-lifetime-constraint.stderr (hunk 7 above)
Comment (estebank) [reply src/test/ui/traits/trait-param-without-lifetime-constraint.stderr]: I'm looking at this again. Right now the output is:

Screen Shot 2020-03-29 at 4 59 52 PM

I'm looking at what options I might have to approximate the suggested output, but it can quickly get tricky when more complex lifetime relationships are used.

Comment (estebank) [reply src/test/ui/traits/trait-param-without-lifetime-constraint.stderr]: I'm finding doing the same kind of fancy pointing of lifetimes as we do in `librustc_mir::borrowck` a bit hard to do for this. It seems like I might have to write the logic to associate HIR lifetimes to `ty::Region` myself, but most likely I'm just missing something obvious somewhere.

Comment (nikomatsakis) [reply src/test/ui/traits/trait-param-without-lifetime-constraint.stderr]: I'm not sure how easy it will be to repurpose that logic indeed. Let me see if I can give you any tips :)

Comment (nikomatsakis) [reply src/test/ui/traits/trait-param-without-lifetime-constraint.stderr:1]: Hmm, OK, so I am reminded that there are still some bits of the code that use the lexical region solver. I wonder if the "right fix" is to be moving those bits of code to use the NLL solver, which might then enable us to use the NLL rewriting routines more easily. This is work that has been very slowly proceeding, @matthewjasper was carrying it along to some extent.

**Comment by estebank** [comment]
@bors r=nikomatsakis

@nikomatsakis Approving based on https://rust-lang.zulipchat.com/#narrow/stream/147480-t-compiler.2Fwg-diagnostics/topic/impl.20signature.20mismatch.20errors.20PR.20.2367460/near/198499109

**Comment by estebank** [comment]
@bors r=nikomatsakis

@nikomatsakis made tiny tweak to account for `Self` and fix #72106.
