### PR TITLE
resolve: Fix doc links referring to other crates when documenting proc macro crates directly

### LINKED ISSUE #107950: rustdoc regression: intra-doc-links not working in proc-macro crate since nightly-2023-02-12
### Code

I ran `cargo doc` with this code:

```toml
# Cargo.toml
[package]
name = "repro"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true
```

```rust
/// [`Unpin`]
#[proc_macro_derive(F)]
pub fn derive_(t: proc_macro::TokenStream) -> proc_macro::TokenStream {
    t
}

/// [`Unpin`]
#[proc_macro_attribute]
pub fn attr(t: proc_macro::TokenStream, _: proc_macro::TokenStream) -> proc_macro::TokenStream {
    t
}

/// [`Unpin`]
#[proc_macro]
pub fn func(t: proc_macro::TokenStream) -> proc_macro::TokenStream {
    t
}
```

I expected to see this happen: intra-doc-links work and no warning

Instead, this happened:

intra-doc-links is not working in the generated docs.

doc

And I got broken_intra_doc_links warnings:

```
warning: unresolved link to `Unpin`
 --> src/lib.rs:1:7
  |
1 | /// [`Unpin`]
  |       ^^^^^ no item named `Unpin` in scope
  |
  = help: to escape `[` and `]` characters, add '\' before them like `\[` or `\]`
  = note: `#[warn(rustdoc::broken_intra_doc_links)]` on by default

warning: unresolved link to `Unpin`
 --> src/lib.rs:7:7
  |
7 | /// [`Unpin`]
  |       ^^^^^ no item named `Unpin` in scope
  |
  = help: to escape `[` and `]` characters, add '\' before them like `\[` or `\]`

warning: unresolved link to `Unpin`
  --> src/lib.rs:13:7
   |
13 | /// [`Unpin`]
   |       ^^^^^ no item named `Unpin` in scope
   |
   = help: to escape `[` and `]` characters, add '\' before them like `\[` or `\]`
```

### Version it worked on

It most recently worked on: nightly-2023-02-11

doc-old

### Version with regression

`rustc --version --verbose`:
```
rustc 1.69.0-nightly (585f3eef2 2023-02-11)
binary: rustc
commit-hash: 585f3eef26f04440bca726c29193af7b4fa90e54
commit-date: 2023-02-11
host: aarch64-apple-darwin
release: 1.69.0-nightly
LLVM version: 15.0.7
```

@rustbot modify labels: +regression-from-stable-to-nightly -regression-untriaged

### PR DESCRIPTION
**Pull request by petrochenkov**
Fixes https://github.com/rust-lang/rust/issues/107950

### CODE REVIEW

File: tests/rustdoc/intra-doc/proc-macro-doc.rs [hunk 1]
```diff
@@ -0,0 +1,27 @@
+// force-host
+// no-prefer-dynamic
+// compile-flags: --crate-type proc-macro
+
+extern crate proc_macro;
+use proc_macro::*;
+
+// has core/marker/trait.Unpin.html
```
Comment (petrochenkov) [inline tests/rustdoc/intra-doc/proc-macro-doc.rs:8]: I'm not sure what to write here,
```
// @has core/marker/trait.Unpin.html
```
doesn't work and reports
```
8: @has check failed
        File does not exist 'core\\marker\\trait.Unpin.html'
        // @has core/marker/trait.Unpin.html
```
because dependency crates like libcore are not documented in the test suite.

Comment (eggyal) [reply tests/rustdoc/intra-doc/proc-macro-doc.rs:8]: You could instead add an aux crate to the test (with `aux-build` and `build-aux-docs` completest headers), and use a link to that instead?  Or else perhaps just make it a `rustdoc-ui` test with `#![deny(rustdoc::broken_intra_doc_links)]` ?

Comment (petrochenkov) [reply tests/rustdoc/intra-doc/proc-macro-doc.rs]: Ok, moved to `rustdoc-ui`.
