### PR TITLE
diagnostics: Note capturing closures can't be coerced to fns

### LINKED ISSUE #71895: diagnostics for capturing closures that are coerced to fn pointers are not great
Given this program ([playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=b33d9cacfb6ed2818550b87e9b873845)):

```rust
fn main() {
    let y = 22;
    let x: fn() = || drop(y);
}
```

the error message is currently:

```
error[E0308]: mismatched types
 --> src/main.rs:3:19
  |
3 |     let x: fn() = || drop(y);
  |            ----   ^^^^^^^^^^ expected fn pointer, found closure
  |            |
  |            expected due to this
  |
  = note: expected fn pointer `fn()`
                found closure `[closure@src/main.rs:3:19: 3:29 y:_]`
```

The problem here is that closures can be coerced to `fn` types, but only if they don't capture any variables (and this one does capture `y`) -- see https://github.com/rust-lang/rust/issues/39817 for more details. I think that we ought to give an error like:

```
error[E0308]: closure cannot be forced to `fn()` type because it captures `y`
 --> src/main.rs:3:19
  |
3 |     let x: fn() = || drop(y);
  |            ----           ^ `y` captured due to use here
  |            |
  |            expected due to this
  |
  = note: closures can only be coerced to `fn` types if they do not capture any variables
```

### LINKED ISSUE #72457: Improve error message when coercing closures fails
After #71599, coercing `(FnDef | Closure) x (FnDef | Closure)` is possible. It fails when one of them is capturing closure. But currently the error message is not that good.
For example:
```rust
fn main() {
    // Good
    let _: fn(usize) -> usize = match true {
        true => |a| a + 1,
        false => |a| a - 1,
    };

    // Bad
    let b = 2;
    let _: fn(usize) -> usize = match true {
        true => |a| a + 1,
        false => |a| a - b,
    };
}
```
Emits:
```
error[E0308]: `match` arms have incompatible types
  --> src\main.rs:12:18
   |
10 |       let _: fn(usize) -> usize = match true {
   |  _________________________________-
11 | |         true => |a| a + 1,
   | |                 --------- this is found to be of type `fn(usize) -> usize`
12 | |         false => |a| a - b,
   | |                  ^^^^^^^^^ expected fn pointer, found closure
13 | |     };
   | |_____- `match` arms have incompatible types
   |
   = note: expected fn pointer `fn(usize) -> usize`
                 found closure `[closure@src\main.rs:12:18: 12:27 b:_]`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0308`.
```

We actually can hint user to use non-capturing closure here.
This is related to #71895

### PR DESCRIPTION
**Pull request by arora-aman**
Fixes #72457, fixes #71895

r? @estebank

### CODE REVIEW

File: compiler/rustc_typeck/src/check/fn_ctxt/suggestions.rs [hunk 1]
```diff
@@ -287,6 +287,32 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
...
+    /// When encountering a closure that captures variables, where a FnPtr is expected,
+    /// suggest a non-capturing closure
+    pub(in super::super) fn suggest_no_capture_closure(
+        &self,
+        err: &mut DiagnosticBuilder<'_>,
+        expected: Ty<'tcx>,
+        found: Ty<'tcx>,
+    ) {
+        if matches!(expected.kind(), ty::FnPtr(_)) {
+            if let ty::Closure(def_id, _) = found.kind() {
```
Comment (estebank) [inline compiler/rustc_typeck/src/check/fn_ctxt/suggestions.rs:299]: This can instead be as follows to remove one level of indentation:

```suggestion
        if let (ty::FnPtr(_), ty::Closure(def_id, _)) = (expected.kind(), found.kind()) {
```

File: compiler/rustc_typeck/src/check/fn_ctxt/suggestions.rs [hunk 2]
```diff
@@ -287,6 +287,32 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
         }
     }
 
+    /// When encountering a closure that captures variables, where a FnPtr is expected,
+    /// suggest a non-capturing closure
+    pub(in super::super) fn suggest_no_capture_closure(
```
Comment (estebank) [inline compiler/rustc_typeck/src/check/fn_ctxt/suggestions.rs:292]:
```suggestion
    crate fn suggest_no_capture_closure(
```

File: compiler/rustc_typeck/src/check/fn_ctxt/suggestions.rs [hunk 3]
```diff
@@ -287,6 +287,32 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
...
+                    err.note("closures can only be coerced to `fn` types if they do not capture any variables");
+
+                    // Report only one upvar being captured to reduce the amount error messages
+                    // reported back to the user.
+                    let first_upvar = upvars.get_index(0);
+                    if let Some((var_hir_id, upvar)) = first_upvar {
+                        let var_name = self.tcx.hir().name(*var_hir_id).to_string();
+                        let msg = format!("{} captured here", var_name);
+                        err.span_note(upvar.span, &msg);
+                    }
```
Comment (estebank) [inline compiler/rustc_typeck/src/check/fn_ctxt/suggestions.rs:310]: Doing the following (note, needs formatting):

```suggestion
                    let spans_and_labels: Vec<(Span, String)> = upvars.iter().map(|(var_hir_id, upvar)| {
                        let var_name = self.tcx.hir().name(*var_hir_id).to_string();
                        let msg = format!("{} captured here", var_name);
                        (upvar.span, msg)
                    }).collect();
                    let multi_span: MultiSpan = spans_and_labels.iter().map(|(sp, _)| *sp).collect::<Vec<_>>().into();
                    for (sp, label) in spans_and_labels {
                        multi_span.push_span_label(sp, label);
                    }
                    err.span_note(multi_span, "closures can only be coerced to `fn` types if they do not capture any variables");
```

would produce the following output:

```
note: closures can only be coerced to `fn` types if they do not capture any variables
  --> $DIR/closure-no-fn-1.rs:6:39
   |
LL |     let foo: fn(u8) -> u8 = |v: u8| { a += v; a };
   |                                       ^ `a` captured here
```

That code doesn't restrict itself to only one var (it would make sense to do maybe up to 4 or so), but in practice might not be terrible.

File: compiler/rustc_typeck/src/check/fn_ctxt/suggestions.rs (hunk 2 above)
Comment (estebank) [reply compiler/rustc_typeck/src/check/fn_ctxt/suggestions.rs:292]: Ah, I see that other methods here use this... It's fine to leave it as is then.

**Comment by camelid** [comment]
@arora-aman Could you address estebank's review?

**Comment by arora-aman** [comment]
Sorry I have been busy, will try to get to it over the weekend

**Comment by arora-aman** [comment]
@estebank sorry for the delay should be good now :)

@rustbot labels +S-waiting-on-review -S-waiting-on-author
