### PR TITLE
Don't run `everybody_loops` for rustdoc; instead ignore resolution errors

### LINKED ISSUE #65863: Rustdoc cannot infer type when using type_alias_impl_trait, while rustc works
```rust
#![feature(type_alias_impl_trait)]

pub trait Backend {}

impl Backend for () {}

pub struct Module<T>(T);

pub type BackendImpl = impl Backend;

pub fn make_module() -> Module<BackendImpl> {
    Module(())
}
```

```
$ rustc -V
rustc 1.38.0 (625451e37 2019-09-23)
$ cargo doc
error[E0282]: type annotations needed
  --> src/main.rs:13:1
   |
13 | pub type BackendImpl = impl Backend<Product: std::any::Any>;
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ cannot infer type

error: aborting due to previous error
$ cargo build
```

### LINKED ISSUE #71104: Some `NodeId`/`LocalDefId` don't have a corresponding `HirId`
During refactor work to remove `DUMMY_HIR_ID` (see https://github.com/rust-lang/rust/pull/71116), I noticed that some queries like `has_typeck_tables` are called for some `NodeId` or `DefId` that do not have a corresponding `HirId`.

Some specific helper functions have been introduced to overcome this bug and used in different places:
* https://github.com/rust-lang/rust/commit/b9161ab880cb4f58b2b2e74b7a8bed2514f8a753#diff-1bffadcc6a4ac0564af0f075eb094eb1R1129
* https://github.com/rust-lang/rust/commit/b9161ab880cb4f58b2b2e74b7a8bed2514f8a753#diff-f7c5ab0a133d5d59a6ce76d8c88ff203R931
* https://github.com/rust-lang/rust/commit/b9161ab880cb4f58b2b2e74b7a8bed2514f8a753#diff-426e1c382fc57abf697fdeee18e03ddeR228
* https://github.com/rust-lang/rust/commit/b9161ab880cb4f58b2b2e74b7a8bed2514f8a753#diff-1d1b0d29a2e8da97c6bfb6e364d920c7R841

Especially, the following tests failed when trying to use `as_local_hir_id`:
```
failures:
    [ui] ui/generator/async-generator-issue-67158.rs
    [ui] ui/save-analysis/issue-68621.rs
    [ui] ui/type-alias-impl-trait/issue-63279.rs
    [ui] ui/type-alias-impl-trait/issue-65679-inst-opaque-ty-from-val-twice.rs
```
For `ui/save-analysis/issue-68621.rs`, the query debug info is:
```
#0 [has_typeck_tables] processing `<Struct as Service>::Future::{{opaque}}#0`
```
and for `ui/type-alias-impl-trait/issue-63279.rs`:
```
#0 [has_typeck_tables] processing `Closure::{{opaque}}#0`
```

Example backtrace for `ui/save-analysis/issue-68621.rs`:
```
thread 'rustc' panicked at 'called `Option::unwrap()` on a `None` value', /home/adema/code/rust/src/librustc_hir/definitions.rs:368:9
stack backtrace:
   0:     0x7fba2ed1ebe4 - backtrace::backtrace::libunwind::trace::hf4e48ba64f80f3eb
                               at /home/adema/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
   1:     0x7fba2ed1ebe4 - backtrace::backtrace::trace_unsynchronized::hc05f5ae9bd82f888
                               at /home/adema/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
   2:     0x7fba2ed1ebe4 - std::sys_common::backtrace::_print_fmt::h6194c30153926243
                               at src/libstd/sys_common/backtrace.rs:78
   3:     0x7fba2ed1ebe4 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hdefc5db2589e7b2f
                               at src/libstd/sys_common/backtrace.rs:59
   4:     0x7fba2ed6610c - core::fmt::write::h5e80f79ba6cafaf2
                               at src/libcore/fmt/mod.rs:1069
   5:     0x7fba2ed0d665 - std::io::Write::write_fmt::he4f935868e47e3ba
                               at src/libstd/io/mod.rs:1504
   6:     0x7fba2ecf27e5 - std::sys_common::backtrace::_print::h3fc078a3aae1ebdf
                               at src/libstd/sys_common/backtrace.rs:62
   7:     0x7fba2ecf27e5 - std::sys_common::backtrace::print::h27137ce93aeba206
                               at src/libstd/sys_common/backtrace.rs:49
   8:     0x7fba2ecf27e5 - std::panicking::default_hook::{{closure}}::h466f8b9e45a47838
                               at src/libstd/panicking.rs:198
   9:     0x7fba2ecf24cf - std::panicking::default_hook::h7589bdd3a2ab152b
                               at src/libstd/panicking.rs:218
  10:     0x7fba2f3f5673 - <alloc::boxed::Box<F> as core::ops::function::Fn<A>>::call::h25fa7aa7eb2f6f06
                               at /home/adema/code/rust/src/liballoc/boxed.rs:1022
  11:     0x7fba2f3f5673 - rustc_driver::report_ice::he6496451e88ccee4
                               at src/librustc_driver/lib.rs:1172
  12:     0x7fba2ecf3015 - std::panicking::rust_panic_with_hook::h94399de650c4f4da
                               at src/libstd/panicking.rs:515
  13:     0x7fba2ecf2b2b - rust_begin_unwind
                               at src/libstd/panicking.rs:419
  14:     0x7fba2ed63e51 - core::panicking::panic_fmt::h5a23a1434eb19732
                               at src/libcore/panicking.rs:111
  15:     0x7fba2ed63d9d - core::panicking::panic::h1a56bed8578da5a8
                               at src/libcore/panicking.rs:56
  16:     0x7fba320e3fa2 - core::option::Option<T>::unwrap::h01ca14479a9f3380
                               at /home/adema/code/rust/src/libcore/macros/mod.rs:11
  17:     0x7fba320e3fa2 - rustc_hir::definitions::Definitions::local_def_id_to_hir_id::h3e942dc1a9cdcbe3
                               at /home/adema/code/rust/src/librustc_hir/definitions.rs:368
  18:     0x7fba320e3fa2 - rustc_hir::definitions::Definitions::as_local_hir_id::h5052ccdd1650b1de
                               at /home/adema/code/rust/src/librustc_hir/definitions.rs:348
  19:     0x7fba320e3fa2 - rustc_middle::hir::map::Map::as_local_hir_id::hcc7339a4abf77535
                               at /home/adema/code/rust/src/librustc_middle/hir/map/mod.rs:204
  20:     0x7fba320e3fa2 - rustc_typeck::check::has_typeck_tables::h51a84fff8ccfcc3e
                               at src/librustc_typeck/check/mod.rs:842
  21:     0x7fba2f5fe272 - rustc_middle::ty::query::<impl rustc_query_system::query::config::QueryAccessors<rustc_middle::ty::context::TyCtxt> for rustc_middle::ty::query::queries::has_typeck_tables>::compute::hcb61e0605089bcde
                               at /home/adema/code/rust/src/librustc_middle/ty/query/plumbing.rs:357
  22:     0x7fba2f5f8d34 - rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl::hab41ebbda3aa67f9
                               at /home/adema/code/rust/src/librustc_query_system/dep_graph/graph.rs:303
  23:     0x7fba2f60165d - rustc_query_system::dep_graph::graph::DepGraph<K>::with_task::h4369254ed57a7056
                               at /home/adema/code/rust/src/librustc_query_system/dep_graph/graph.rs:200
  24:     0x7fba2f60165d - rustc_query_system::query::plumbing::force_query_with_job::{{closure}}::{{closure}}::habdfeebee3f9cf45
                               at /home/adema/code/rust/src/librustc_query_system/query/plumbing.rs:593
  25:     0x7fba2f60165d - rustc_middle::ty::query::plumbing::<impl rustc_query_system::query::QueryContext for rustc_middle::ty::context::TyCtxt>::start_query::{{closure}}::{{closure}}::hd83318f92b9d7499
                               at /home/adema/code/rust/src/librustc_middle/ty/query/plumbing.rs:71
  26:     0x7fba2f60165d - rustc_middle::ty::context::tls::enter_context::{{closure}}::hdd4d49fc80d57c78
                               at /home/adema/code/rust/src/librustc_middle/ty/context.rs:1695
  27:     0x7fba2f60165d - rustc_middle::ty::context::tls::set_tlv::hc68046dd904eed8f
                               at /home/adema/code/rust/src/librustc_middle/ty/context.rs:1679
  28:     0x7fba2f60165d - rustc_middle::ty::context::tls::enter_context::h381621443cbb0e97
                               at /home/adema/code/rust/src/librustc_middle/ty/context.rs:1695
  29:     0x7fba2f60165d - rustc_middle::ty::query::plumbing::<impl rustc_query_system::query::QueryContext for rustc_middle::ty::context::TyCtxt>::start_query::{{closure}}::he843232fc1f45e72
                               at /home/adema/code/rust/src/librustc_middle/ty/query/plumbing.rs:71
  30:     0x7fba2f60165d - rustc_middle::ty::context::tls::with_related_context::{{closure}}::h4e7df0c52657e941
                               at /home/adema/code/rust/src/librustc_middle/ty/context.rs:1783
  31:     0x7fba2f60165d - rustc_middle::ty::context::tls::with_context::{{closure}}::h47a3fbb102fc828d
                               at /home/adema/code/rust/src/librustc_middle/ty/context.rs:1767
  32:     0x7fba2f60165d - rustc_middle::ty::context::tls::with_context_opt::ha6f845fb734f0a78
                               at /home/adema/code/rust/src/librustc_middle/ty/context.rs:1756
  33:     0x7fba2f60165d - rustc_middle::ty::context::tls::with_context::h757b8664d833e169
                               at /home/adema/code/rust/src/librustc_middle/ty/context.rs:1767
  34:     0x7fba2f60165d - rustc_middle::ty::context::tls::with_related_context::hcf3df7ef753f1f12
                               at /home/adema/code/rust/src/librustc_middle/ty/context.rs:1780
  35:     0x7fba2f60165d - rustc_middle::ty::query::plumbing::<impl rustc_query_system::query::QueryContext for rustc_middle::ty::context::TyCtxt>::start_query::h2f6dc24b8579de5f
                               at /home/adema/code/rust/src/librustc_middle/ty/query/plumbing.rs:60
  36:     0x7fba2f60165d - rustc_query_system::query::plumbing::force_query_with_job::{{closure}}::h8bf9e4bceef20544
                               at /home/adema/code/rust/src/librustc_query_system/query/plumbing.rs:583
  37:     0x7fba2f60165d - rustc_query_system::query::plumbing::with_diagnostics::haa016d7b51fce7cd
                               at /home/adema/code/rust/src/librustc_query_system/query/plumbing.rs:293
  38:     0x7fba2f60165d - rustc_query_system::query::plumbing::force_query_with_job::hb8bc1b278cc4ab1f
                               at /home/adema/code/rust/src/librustc_query_system/query/plumbing.rs:582
  39:     0x7fba2f60165d - rustc_query_system::query::plumbing::try_execute_query::h6d851fa650ee170a
                               at /home/adema/code/rust/src/librustc_query_system/query/plumbing.rs:410
  40:     0x7fba2f60165d - rustc_query_system::query::plumbing::get_query::{{closure}}::hd76e9b348ed430b5
                               at /home/adema/code/rust/src/librustc_query_system/query/plumbing.rs:627
  41:     0x7fba2f60165d - <rustc_query_system::query::caches::DefaultCache<K,V> as rustc_query_system::query::caches::QueryCache>::lookup::h65ee3022cd4fbc4b
                               at /home/adema/code/rust/src/librustc_query_system/query/caches.rs:91
  42:     0x7fba2f60165d - rustc_query_system::query::plumbing::try_get_cached::h458fe2f3c22a5ae0
                               at /home/adema/code/rust/src/librustc_query_system/query/plumbing.rs:368
  43:     0x7fba2f60165d - rustc_query_system::query::plumbing::get_query::h246763f6bd13604d
                               at /home/adema/code/rust/src/librustc_query_system/query/plumbing.rs:619
  44:     0x7fba2f5f57cf - rustc_middle::ty::query::TyCtxtAt::has_typeck_tables::ha54a24b2f1464e26
                               at /home/adema/code/rust/src/librustc_middle/ty/query/plumbing.rs:462
  45:     0x7fba2f5f57cf - rustc_middle::ty::query::<impl rustc_middle::ty::context::TyCtxt>::has_typeck_tables::h41d192875f061dea
                               at /home/adema/code/rust/src/librustc_middle/ty/query/plumbing.rs:425
  46:     0x7fba2f5f57cf - rustc_save_analysis::dump_visitor::DumpVisitor::nest_tables::h7bec618ccd6b7e9b
                               at src/librustc_save_analysis/dump_visitor.rs:112
  47:     0x7fba2f5f57cf - <rustc_save_analysis::dump_visitor::DumpVisitor as rustc_ast::visit::Visitor>::visit_ty::h24636c8a8e006b2e
                               at src/librustc_save_analysis/dump_visitor.rs:1419
  48:     0x7fba2f5f1efa - rustc_save_analysis::dump_visitor::DumpVisitor::process_impl_item::h3929b05aaef88a1b
                               at src/librustc_save_analysis/dump_visitor.rs:1107
  49:     0x7fba2f5f1efa - rustc_save_analysis::dump_visitor::DumpVisitor::process_impl::{{closure}}::hda1b88089e758a26
                               at src/librustc_save_analysis/dump_visitor.rs:675
  50:     0x7fba2f5f1efa - rustc_save_analysis::dump_visitor::DumpVisitor::nest_tables::he39ba8de26691545
                               at src/librustc_save_analysis/dump_visitor.rs:120
  51:     0x7fba2f5f1efa - rustc_save_analysis::dump_visitor::DumpVisitor::process_impl::h3357dee0ab6a675f
                               at src/librustc_save_analysis/dump_visitor.rs:668
  52:     0x7fba2f5f1efa - <rustc_save_analysis::dump_visitor::DumpVisitor as rustc_ast::visit::Visitor>::visit_item::hd1c32cd3f75a6e43
                               at src/librustc_save_analysis/dump_visitor.rs:1308
  53:     0x7fba2f5ee65a - rustc_ast::visit::walk_mod::h453232913b72f97a
                               at /home/adema/code/rust/src/librustc_ast/visit.rs:236
  54:     0x7fba2f5ee65a - <rustc_save_analysis::dump_visitor::DumpVisitor as rustc_ast::visit::Visitor>::visit_mod::hff0465a2c83a38d8
                               at src/librustc_save_analysis/dump_visitor.rs:1262
  55:     0x7fba2f3fbfa3 - rustc_ast::visit::walk_crate::hd16e58112689af6c
                               at /home/adema/code/rust/src/librustc_ast/visit.rs:251
  56:     0x7fba2f5480e1 - rustc_save_analysis::process_crate::{{closure}}::h81b39ee5fe417e3c
                               at /home/adema/code/rust/src/librustc_save_analysis/lib.rs:1043
  57:     0x7fba2f5480e1 - rustc_middle::dep_graph::<impl rustc_query_system::dep_graph::DepKind for rustc_middle::dep_graph::dep_node::DepKind>::with_deps::{{closure}}::{{closure}}::h4392b1dbdb581074
                               at /home/adema/code/rust/src/librustc_middle/dep_graph/mod.rs:71
  58:     0x7fba2f5480e1 - rustc_middle::ty::context::tls::enter_context::{{closure}}::h26a4f348a195ab40
                               at /home/adema/code/rust/src/librustc_middle/ty/context.rs:1695
  59:     0x7fba2f5480e1 - rustc_middle::ty::context::tls::set_tlv::hf112bb4733627b25
                               at /home/adema/code/rust/src/librustc_middle/ty/context.rs:1679
  60:     0x7fba2f5480e1 - rustc_middle::ty::context::tls::enter_context::h2205d6117dd7d657
                               at /home/adema/code/rust/src/librustc_middle/ty/context.rs:1695
  61:     0x7fba2f5480e1 - rustc_middle::dep_graph::<impl rustc_query_system::dep_graph::DepKind for rustc_middle::dep_graph::dep_node::DepKind>::with_deps::{{closure}}::h4825e2841f7105d4
                               at /home/adema/code/rust/src/librustc_middle/dep_graph/mod.rs:71
  62:     0x7fba2f5480e1 - rustc_middle::ty::context::tls::with_context::{{closure}}::h54a5c25daa6df37c
                               at /home/adema/code/rust/src/librustc_middle/ty/context.rs:1767
  63:     0x7fba2f5480e1 - rustc_middle::ty::context::tls::with_context_opt::h4955f6b417c79b08
                               at /home/adema/code/rust/src/librustc_middle/ty/context.rs:1756
  64:     0x7fba2f5480e1 - rustc_middle::ty::context::tls::with_context::h48976b8c37bd37ea
                               at /home/adema/code/rust/src/librustc_middle/ty/context.rs:1767
  65:     0x7fba2f5480e1 - rustc_middle::dep_graph::<impl rustc_query_system::dep_graph::DepKind for rustc_middle::dep_graph::dep_node::DepKind>::with_deps::ha925f2d79ea5ae7b
                               at /home/adema/code/rust/src/librustc_middle/dep_graph/mod.rs:68
  66:     0x7fba2f548bcd - rustc_query_system::dep_graph::graph::DepGraph<K>::with_ignore::heb8e89779bb2ee5c
                               at /home/adema/code/rust/src/librustc_query_system/dep_graph/graph.rs:162
  67:     0x7fba2f548bcd - rustc_save_analysis::process_crate::h261f0a0143c82a15
                               at /home/adema/code/rust/src/librustc_save_analysis/lib.rs:1019
  68:     0x7fba2f548bcd - rustc_driver::run_compiler::{{closure}}::{{closure}}::{{closure}}::{{closure}}::h8fbb56155e5868f0
                               at src/librustc_driver/lib.rs:360
  69:     0x7fba2f548bcd - rustc_data_structures::profiling::VerboseTimingGuard::run::he233753eb9d0f987
                               at /home/adema/code/rust/src/librustc_data_structures/profiling.rs:568
  70:     0x7fba2f548bcd - rustc_session::utils::<impl rustc_session::session::Session>::time::h3e44c1f80824bde6
                               at /home/adema/code/rust/src/librustc_session/utils.rs:9
  71:     0x7fba2f5791db - rustc_driver::run_compiler::{{closure}}::{{closure}}::{{closure}}::hc0a4eb6a93a6acbb
                               at src/librustc_driver/lib.rs:359
  72:     0x7fba2f5791db - rustc_middle::ty::context::tls::enter_global::{{closure}}::h4f772c7273d0b953
                               at /home/adema/code/rust/src/librustc_middle/ty/context.rs:1718
  73:     0x7fba2f5791db - rustc_middle::ty::context::tls::enter_context::{{closure}}::hc4091cfff8b06f9d
                               at /home/adema/code/rust/src/librustc_middle/ty/context.rs:1695
  74:     0x7fba2f5791db - rustc_middle::ty::context::tls::set_tlv::h9207087df904d098
                               at /home/adema/code/rust/src/librustc_middle/ty/context.rs:1679
  75:     0x7fba2f5791db - rustc_middle::ty::context::tls::enter_context::had72ad5eaff43ada
                               at /home/adema/code/rust/src/librustc_middle/ty/context.rs:1695
  76:     0x7fba2f5791db - rustc_middle::ty::context::tls::enter_global::h71995367196689c6
                               at /home/adema/code/rust/src/librustc_middle/ty/context.rs:1718
  77:     0x7fba2f549a54 - rustc_interface::passes::QueryContext::enter::h06663ee920c9b92d
                               at /home/adema/code/rust/src/librustc_interface/passes.rs:709
  78:     0x7fba2f549a54 - rustc_driver::run_compiler::{{closure}}::{{closure}}::he256573a74ae418a
                               at src/librustc_driver/lib.rs:356
  79:     0x7fba2f549a54 - rustc_interface::queries::<impl rustc_interface::interface::Compiler>::enter::h92c934d043260141
                               at /home/adema/code/rust/src/librustc_interface/queries.rs:385
  80:     0x7fba2f549a54 - rustc_driver::run_compiler::{{closure}}::hb4e87ee0015ffcea
                               at src/librustc_driver/lib.rs:283
  81:     0x7fba2f549a54 - rustc_interface::interface::run_compiler_in_existing_thread_pool::h0214c6d436249d75
                               at /home/adema/code/rust/src/librustc_interface/interface.rs:199
  82:     0x7fba2f3feffd - rustc_interface::interface::run_compiler::{{closure}}::h74859c046fb08e3f
                               at /home/adema/code/rust/src/librustc_interface/interface.rs:213
  83:     0x7fba2f3feffd - rustc_interface::util::spawn_thread_pool::{{closure}}::{{closure}}::{{closure}}::h79d111f3ae438d15
                               at /home/adema/code/rust/src/librustc_interface/util.rs:152
  84:     0x7fba2f3feffd - scoped_tls::ScopedKey<T>::set::h1cf2eba532202ed5
                               at /home/adema/.cargo/registry/src/github.com-1ecc6299db9ec823/scoped-tls-1.0.0/src/lib.rs:137
  85:     0x7fba2f3feffd - rustc_interface::util::spawn_thread_pool::{{closure}}::{{closure}}::hb845af3cf404145b
                               at /home/adema/code/rust/src/librustc_interface/util.rs:148
  86:     0x7fba2f3feffd - scoped_tls::ScopedKey<T>::set::ha94ad89e21750bf4
                               at /home/adema/.cargo/registry/src/github.com-1ecc6299db9ec823/scoped-tls-1.0.0/src/lib.rs:137
  87:     0x7fba2f3feffd - rustc_ast::attr::with_globals::{{closure}}::h925ca335cf988b3a
                               at /home/adema/code/rust/src/librustc_ast/attr/mod.rs:44
  88:     0x7fba2f3feffd - scoped_tls::ScopedKey<T>::set::h370e4876e5998364
                               at /home/adema/.cargo/registry/src/github.com-1ecc6299db9ec823/scoped-tls-1.0.0/src/lib.rs:137
  89:     0x7fba2f3fbd04 - rustc_ast::attr::with_globals::h2d1de10aeff62ecf
                               at /home/adema/code/rust/src/librustc_ast/attr/mod.rs:44
  90:     0x7fba2f407f64 - rustc_interface::util::spawn_thread_pool::{{closure}}::h0f507ae6322d57b0
                               at /home/adema/code/rust/src/librustc_interface/util.rs:147
  91:     0x7fba2f407f64 - rustc_interface::util::scoped_thread::{{closure}}::h37f638b7f6de2a83
                               at /home/adema/code/rust/src/librustc_interface/util.rs:122
  92:     0x7fba2f407f64 - std::sys_common::backtrace::__rust_begin_short_backtrace::hda4d986712102604
                               at /home/adema/code/rust/src/libstd/sys_common/backtrace.rs:130
  93:     0x7fba2ecf2954 - std::panicking::try::do_try::hed7a629852400b5f
                               at src/libstd/panicking.rs:298
  94:     0x7fba2f54d0fd - std::panicking::try::ha4e540c03fa2d4c0
                               at /home/adema/code/rust/src/libstd/panicking.rs:274
  95:     0x7fba2f54d0fd - std::panic::catch_unwind::h99519e6c997fe112
                               at /home/adema/code/rust/src/libstd/panic.rs:394
  96:     0x7fba2f54d0fd - std::thread::Builder::spawn_unchecked::{{closure}}::hc2d0ac9187f1dd6d
                               at /home/adema/code/rust/src/libstd/thread/mod.rs:474
  97:     0x7fba2f54d0fd - core::ops::function::FnOnce::call_once{{vtable.shim}}::h86e0f7111ce1cb62
                               at /home/adema/code/rust/src/libcore/ops/function.rs:232
  98:     0x7fba2ed1240f - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h7d8c0ce9bb9a9a7b
                               at /home/adema/code/rust/src/liballoc/boxed.rs:1008
  99:     0x7fba2ecfab23 - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::hfcf1edc22130327f
                               at /home/adema/code/rust/src/liballoc/boxed.rs:1008
 100:     0x7fba2ecfab23 - std::sys::unix::thread::Thread::new::thread_start::he3bd71071b1a178e
                               at src/libstd/sys/unix/thread.rs:87
 101:     0x7fba2ea98f27 - start_thread
                               at /builddir/glibc-2.30/nptl/pthread_create.c:479
 102:     0x7fba2ebb2e0f - __GI___clone
                               at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
 103:                0x0 - <unknown>
```
and for `ui/type-alias-impl-trait/issue-63279.rs`:
```
thread 'rustc' panicked at 'called `Option::unwrap()` on a `None` value', /home/adema/code/rust/src/librustc_hir/definitions.rs:368:9
stack backtrace:
   0:     0x7f59a4c6cbe4 - backtrace::backtrace::libunwind::trace::hf4e48ba64f80f3eb
                               at /home/adema/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
   1:     0x7f59a4c6cbe4 - backtrace::backtrace::trace_unsynchronized::hc05f5ae9bd82f888
                               at /home/adema/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
   2:     0x7f59a4c6cbe4 - std::sys_common::backtrace::_print_fmt::h6194c30153926243
                               at src/libstd/sys_common/backtrace.rs:78
   3:     0x7f59a4c6cbe4 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hdefc5db2589e7b2f
                               at src/libstd/sys_common/backtrace.rs:59
   4:     0x7f59a4cb410c - core::fmt::write::h5e80f79ba6cafaf2
                               at src/libcore/fmt/mod.rs:1069
   5:     0x7f59a4c5b665 - std::io::Write::write_fmt::he4f935868e47e3ba
                               at src/libstd/io/mod.rs:1504
   6:     0x7f59a4c407e5 - std::sys_common::backtrace::_print::h3fc078a3aae1ebdf
                               at src/libstd/sys_common/backtrace.rs:62
   7:     0x7f59a4c407e5 - std::sys_common::backtrace::print::h27137ce93aeba206
                               at src/libstd/sys_common/backtrace.rs:49
   8:     0x7f59a4c407e5 - std::panicking::default_hook::{{closure}}::h466f8b9e45a47838
                               at src/libstd/panicking.rs:198
   9:     0x7f59a4c404cf - std::panicking::default_hook::h7589bdd3a2ab152b
                               at src/libstd/panicking.rs:218
  10:     0x7f59a5343673 - <alloc::boxed::Box<F> as core::ops::function::Fn<A>>::call::h25fa7aa7eb2f6f06
                               at /home/adema/code/rust/src/liballoc/boxed.rs:1022
  11:     0x7f59a5343673 - rustc_driver::report_ice::he6496451e88ccee4
                               at src/librustc_driver/lib.rs:1172
  12:     0x7f59a4c41015 - std::panicking::rust_panic_with_hook::h94399de650c4f4da
                               at src/libstd/panicking.rs:515
  13:     0x7f59a4c40b2b - rust_begin_unwind
                               at src/libstd/panicking.rs:419
  14:     0x7f59a4cb1e51 - core::panicking::panic_fmt::h5a23a1434eb19732
                               at src/libcore/panicking.rs:111
  15:     0x7f59a4cb1d9d - core::panicking::panic::h1a56bed8578da5a8
                               at src/libcore/panicking.rs:56
  16:     0x7f59a8031fa2 - core::option::Option<T>::unwrap::h01ca14479a9f3380
                               at /home/adema/code/rust/src/libcore/macros/mod.rs:11
  17:     0x7f59a8031fa2 - rustc_hir::definitions::Definitions::local_def_id_to_hir_id::h3e942dc1a9cdcbe3
                               at /home/adema/code/rust/src/librustc_hir/definitions.rs:368
  18:     0x7f59a8031fa2 - rustc_hir::definitions::Definitions::as_local_hir_id::h5052ccdd1650b1de
                               at /home/adema/code/rust/src/librustc_hir/definitions.rs:348
  19:     0x7f59a8031fa2 - rustc_middle::hir::map::Map::as_local_hir_id::hcc7339a4abf77535
                               at /home/adema/code/rust/src/librustc_middle/hir/map/mod.rs:204
  20:     0x7f59a8031fa2 - rustc_typeck::check::has_typeck_tables::h51a84fff8ccfcc3e
                               at src/librustc_typeck/check/mod.rs:842
  21:     0x7f59a554c272 - rustc_middle::ty::query::<impl rustc_query_system::query::config::QueryAccessors<rustc_middle::ty::context::TyCtxt> for rustc_middle::ty::query::queries::has_typeck_tables>::compute::hcb61e0605089bcde
                               at /home/adema/code/rust/src/librustc_middle/ty/query/plumbing.rs:357
  22:     0x7f59a5546d34 - rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl::hab41ebbda3aa67f9
                               at /home/adema/code/rust/src/librustc_query_system/dep_graph/graph.rs:303
  23:     0x7f59a554f65d - rustc_query_system::dep_graph::graph::DepGraph<K>::with_task::h4369254ed57a7056
                               at /home/adema/code/rust/src/librustc_query_system/dep_graph/graph.rs:200
  24:     0x7f59a554f65d - rustc_query_system::query::plumbing::force_query_with_job::{{closure}}::{{closure}}::habdfeebee3f9cf45
                               at /home/adema/code/rust/src/librustc_query_system/query/plumbing.rs:593
  25:     0x7f59a554f65d - rustc_middle::ty::query::plumbing::<impl rustc_query_system::query::QueryContext for rustc_middle::ty::context::TyCtxt>::start_query::{{closure}}::{{closure}}::hd83318f92b9d7499
                               at /home/adema/code/rust/src/librustc_middle/ty/query/plumbing.rs:71
  26:     0x7f59a554f65d - rustc_middle::ty::context::tls::enter_context::{{closure}}::hdd4d49fc80d57c78
                               at /home/adema/code/rust/src/librustc_middle/ty/context.rs:1695
  27:     0x7f59a554f65d - rustc_middle::ty::context::tls::set_tlv::hc68046dd904eed8f
                               at /home/adema/code/rust/src/librustc_middle/ty/context.rs:1679
  28:     0x7f59a554f65d - rustc_middle::ty::context::tls::enter_context::h381621443cbb0e97
                               at /home/adema/code/rust/src/librustc_middle/ty/context.rs:1695
  29:     0x7f59a554f65d - rustc_middle::ty::query::plumbing::<impl rustc_query_system::query::QueryContext for rustc_middle::ty::context::TyCtxt>::start_query::{{closure}}::he843232fc1f45e72
                               at /home/adema/code/rust/src/librustc_middle/ty/query/plumbing.rs:71
  30:     0x7f59a554f65d - rustc_middle::ty::context::tls::with_related_context::{{closure}}::h4e7df0c52657e941
                               at /home/adema/code/rust/src/librustc_middle/ty/context.rs:1783
  31:     0x7f59a554f65d - rustc_middle::ty::context::tls::with_context::{{closure}}::h47a3fbb102fc828d
                               at /home/adema/code/rust/src/librustc_middle/ty/context.rs:1767
  32:     0x7f59a554f65d - rustc_middle::ty::context::tls::with_context_opt::ha6f845fb734f0a78
                               at /home/adema/code/rust/src/librustc_middle/ty/context.rs:1756
  33:     0x7f59a554f65d - rustc_middle::ty::context::tls::with_context::h757b8664d833e169
                               at /home/adema/code/rust/src/librustc_middle/ty/context.rs:1767
  34:     0x7f59a554f65d - rustc_middle::ty::context::tls::with_related_context::hcf3df7ef753f1f12
                               at /home/adema/code/rust/src/librustc_middle/ty/context.rs:1780
  35:     0x7f59a554f65d - rustc_middle::ty::query::plumbing::<impl rustc_query_system::query::QueryContext for rustc_middle::ty::context::TyCtxt>::start_query::h2f6dc24b8579de5f
                               at /home/adema/code/rust/src/librustc_middle/ty/query/plumbing.rs:60
  36:     0x7f59a554f65d - rustc_query_system::query::plumbing::force_query_with_job::{{closure}}::h8bf9e4bceef20544
                               at /home/adema/code/rust/src/librustc_query_system/query/plumbing.rs:583
  37:     0x7f59a554f65d - rustc_query_system::query::plumbing::with_diagnostics::haa016d7b51fce7cd
                               at /home/adema/code/rust/src/librustc_query_system/query/plumbing.rs:293
  38:     0x7f59a554f65d - rustc_query_system::query::plumbing::force_query_with_job::hb8bc1b278cc4ab1f
                               at /home/adema/code/rust/src/librustc_query_system/query/plumbing.rs:582
  39:     0x7f59a554f65d - rustc_query_system::query::plumbing::try_execute_query::h6d851fa650ee170a
                               at /home/adema/code/rust/src/librustc_query_system/query/plumbing.rs:410
  40:     0x7f59a554f65d - rustc_query_system::query::plumbing::get_query::{{closure}}::hd76e9b348ed430b5
                               at /home/adema/code/rust/src/librustc_query_system/query/plumbing.rs:627
  41:     0x7f59a554f65d - <rustc_query_system::query::caches::DefaultCache<K,V> as rustc_query_system::query::caches::QueryCache>::lookup::h65ee3022cd4fbc4b
                               at /home/adema/code/rust/src/librustc_query_system/query/caches.rs:91
  42:     0x7f59a554f65d - rustc_query_system::query::plumbing::try_get_cached::h458fe2f3c22a5ae0
                               at /home/adema/code/rust/src/librustc_query_system/query/plumbing.rs:368
  43:     0x7f59a554f65d - rustc_query_system::query::plumbing::get_query::h246763f6bd13604d
                               at /home/adema/code/rust/src/librustc_query_system/query/plumbing.rs:619
  44:     0x7f59a55437cf - rustc_middle::ty::query::TyCtxtAt::has_typeck_tables::ha54a24b2f1464e26
                               at /home/adema/code/rust/src/librustc_middle/ty/query/plumbing.rs:462
  45:     0x7f59a55437cf - rustc_middle::ty::query::<impl rustc_middle::ty::context::TyCtxt>::has_typeck_tables::h41d192875f061dea
                               at /home/adema/code/rust/src/librustc_middle/ty/query/plumbing.rs:425
  46:     0x7f59a55437cf - rustc_save_analysis::dump_visitor::DumpVisitor::nest_tables::h7bec618ccd6b7e9b
                               at src/librustc_save_analysis/dump_visitor.rs:112
  47:     0x7f59a55437cf - <rustc_save_analysis::dump_visitor::DumpVisitor as rustc_ast::visit::Visitor>::visit_ty::h24636c8a8e006b2e
                               at src/librustc_save_analysis/dump_visitor.rs:1419
  48:     0x7f59a554201f - <rustc_save_analysis::dump_visitor::DumpVisitor as rustc_ast::visit::Visitor>::visit_item::hd1c32cd3f75a6e43
                               at src/librustc_save_analysis/dump_visitor.rs:1352
  49:     0x7f59a553c65a - rustc_ast::visit::walk_mod::h453232913b72f97a
                               at /home/adema/code/rust/src/librustc_ast/visit.rs:236
  50:     0x7f59a553c65a - <rustc_save_analysis::dump_visitor::DumpVisitor as rustc_ast::visit::Visitor>::visit_mod::hff0465a2c83a38d8
                               at src/librustc_save_analysis/dump_visitor.rs:1262
  51:     0x7f59a5349fa3 - rustc_ast::visit::walk_crate::hd16e58112689af6c
                               at /home/adema/code/rust/src/librustc_ast/visit.rs:251
  52:     0x7f59a54960e1 - rustc_save_analysis::process_crate::{{closure}}::h81b39ee5fe417e3c
                               at /home/adema/code/rust/src/librustc_save_analysis/lib.rs:1043
  53:     0x7f59a54960e1 - rustc_middle::dep_graph::<impl rustc_query_system::dep_graph::DepKind for rustc_middle::dep_graph::dep_node::DepKind>::with_deps::{{closure}}::{{closure}}::h4392b1dbdb581074
                               at /home/adema/code/rust/src/librustc_middle/dep_graph/mod.rs:71
  54:     0x7f59a54960e1 - rustc_middle::ty::context::tls::enter_context::{{closure}}::h26a4f348a195ab40
                               at /home/adema/code/rust/src/librustc_middle/ty/context.rs:1695
  55:     0x7f59a54960e1 - rustc_middle::ty::context::tls::set_tlv::hf112bb4733627b25
                               at /home/adema/code/rust/src/librustc_middle/ty/context.rs:1679
  56:     0x7f59a54960e1 - rustc_middle::ty::context::tls::enter_context::h2205d6117dd7d657
                               at /home/adema/code/rust/src/librustc_middle/ty/context.rs:1695
  57:     0x7f59a54960e1 - rustc_middle::dep_graph::<impl rustc_query_system::dep_graph::DepKind for rustc_middle::dep_graph::dep_node::DepKind>::with_deps::{{closure}}::h4825e2841f7105d4
                               at /home/adema/code/rust/src/librustc_middle/dep_graph/mod.rs:71
  58:     0x7f59a54960e1 - rustc_middle::ty::context::tls::with_context::{{closure}}::h54a5c25daa6df37c
                               at /home/adema/code/rust/src/librustc_middle/ty/context.rs:1767
  59:     0x7f59a54960e1 - rustc_middle::ty::context::tls::with_context_opt::h4955f6b417c79b08
                               at /home/adema/code/rust/src/librustc_middle/ty/context.rs:1756
  60:     0x7f59a54960e1 - rustc_middle::ty::context::tls::with_context::h48976b8c37bd37ea
                               at /home/adema/code/rust/src/librustc_middle/ty/context.rs:1767
  61:     0x7f59a54960e1 - rustc_middle::dep_graph::<impl rustc_query_system::dep_graph::DepKind for rustc_middle::dep_graph::dep_node::DepKind>::with_deps::ha925f2d79ea5ae7b
                               at /home/adema/code/rust/src/librustc_middle/dep_graph/mod.rs:68
  62:     0x7f59a5496bcd - rustc_query_system::dep_graph::graph::DepGraph<K>::with_ignore::heb8e89779bb2ee5c
                               at /home/adema/code/rust/src/librustc_query_system/dep_graph/graph.rs:162
  63:     0x7f59a5496bcd - rustc_save_analysis::process_crate::h261f0a0143c82a15
                               at /home/adema/code/rust/src/librustc_save_analysis/lib.rs:1019
  64:     0x7f59a5496bcd - rustc_driver::run_compiler::{{closure}}::{{closure}}::{{closure}}::{{closure}}::h8fbb56155e5868f0
                               at src/librustc_driver/lib.rs:360
  65:     0x7f59a5496bcd - rustc_data_structures::profiling::VerboseTimingGuard::run::he233753eb9d0f987
                               at /home/adema/code/rust/src/librustc_data_structures/profiling.rs:568
  66:     0x7f59a5496bcd - rustc_session::utils::<impl rustc_session::session::Session>::time::h3e44c1f80824bde6
                               at /home/adema/code/rust/src/librustc_session/utils.rs:9
  67:     0x7f59a54c71db - rustc_driver::run_compiler::{{closure}}::{{closure}}::{{closure}}::hc0a4eb6a93a6acbb
                               at src/librustc_driver/lib.rs:359
  68:     0x7f59a54c71db - rustc_middle::ty::context::tls::enter_global::{{closure}}::h4f772c7273d0b953
                               at /home/adema/code/rust/src/librustc_middle/ty/context.rs:1718
  69:     0x7f59a54c71db - rustc_middle::ty::context::tls::enter_context::{{closure}}::hc4091cfff8b06f9d
                               at /home/adema/code/rust/src/librustc_middle/ty/context.rs:1695
  70:     0x7f59a54c71db - rustc_middle::ty::context::tls::set_tlv::h9207087df904d098
                               at /home/adema/code/rust/src/librustc_middle/ty/context.rs:1679
  71:     0x7f59a54c71db - rustc_middle::ty::context::tls::enter_context::had72ad5eaff43ada
                               at /home/adema/code/rust/src/librustc_middle/ty/context.rs:1695
  72:     0x7f59a54c71db - rustc_middle::ty::context::tls::enter_global::h71995367196689c6
                               at /home/adema/code/rust/src/librustc_middle/ty/context.rs:1718
  73:     0x7f59a5497a54 - rustc_interface::passes::QueryContext::enter::h06663ee920c9b92d
                               at /home/adema/code/rust/src/librustc_interface/passes.rs:709
  74:     0x7f59a5497a54 - rustc_driver::run_compiler::{{closure}}::{{closure}}::he256573a74ae418a
                               at src/librustc_driver/lib.rs:356
  75:     0x7f59a5497a54 - rustc_interface::queries::<impl rustc_interface::interface::Compiler>::enter::h92c934d043260141
                               at /home/adema/code/rust/src/librustc_interface/queries.rs:385
  76:     0x7f59a5497a54 - rustc_driver::run_compiler::{{closure}}::hb4e87ee0015ffcea
                               at src/librustc_driver/lib.rs:283
  77:     0x7f59a5497a54 - rustc_interface::interface::run_compiler_in_existing_thread_pool::h0214c6d436249d75
                               at /home/adema/code/rust/src/librustc_interface/interface.rs:199
  78:     0x7f59a534cffd - rustc_interface::interface::run_compiler::{{closure}}::h74859c046fb08e3f
                               at /home/adema/code/rust/src/librustc_interface/interface.rs:213
  79:     0x7f59a534cffd - rustc_interface::util::spawn_thread_pool::{{closure}}::{{closure}}::{{closure}}::h79d111f3ae438d15
                               at /home/adema/code/rust/src/librustc_interface/util.rs:152
  80:     0x7f59a534cffd - scoped_tls::ScopedKey<T>::set::h1cf2eba532202ed5
                               at /home/adema/.cargo/registry/src/github.com-1ecc6299db9ec823/scoped-tls-1.0.0/src/lib.rs:137
  81:     0x7f59a534cffd - rustc_interface::util::spawn_thread_pool::{{closure}}::{{closure}}::hb845af3cf404145b
                               at /home/adema/code/rust/src/librustc_interface/util.rs:148
  82:     0x7f59a534cffd - scoped_tls::ScopedKey<T>::set::ha94ad89e21750bf4
                               at /home/adema/.cargo/registry/src/github.com-1ecc6299db9ec823/scoped-tls-1.0.0/src/lib.rs:137
  83:     0x7f59a534cffd - rustc_ast::attr::with_globals::{{closure}}::h925ca335cf988b3a
                               at /home/adema/code/rust/src/librustc_ast/attr/mod.rs:44
  84:     0x7f59a534cffd - scoped_tls::ScopedKey<T>::set::h370e4876e5998364
                               at /home/adema/.cargo/registry/src/github.com-1ecc6299db9ec823/scoped-tls-1.0.0/src/lib.rs:137
  85:     0x7f59a5349d04 - rustc_ast::attr::with_globals::h2d1de10aeff62ecf
                               at /home/adema/code/rust/src/librustc_ast/attr/mod.rs:44
  86:     0x7f59a5355f64 - rustc_interface::util::spawn_thread_pool::{{closure}}::h0f507ae6322d57b0
                               at /home/adema/code/rust/src/librustc_interface/util.rs:147
  87:     0x7f59a5355f64 - rustc_interface::util::scoped_thread::{{closure}}::h37f638b7f6de2a83
                               at /home/adema/code/rust/src/librustc_interface/util.rs:122
  88:     0x7f59a5355f64 - std::sys_common::backtrace::__rust_begin_short_backtrace::hda4d986712102604
                               at /home/adema/code/rust/src/libstd/sys_common/backtrace.rs:130
  89:     0x7f59a4c40954 - std::panicking::try::do_try::hed7a629852400b5f
                               at src/libstd/panicking.rs:298
  90:     0x7f59a549b0fd - std::panicking::try::ha4e540c03fa2d4c0
                               at /home/adema/code/rust/src/libstd/panicking.rs:274
  91:     0x7f59a549b0fd - std::panic::catch_unwind::h99519e6c997fe112
                               at /home/adema/code/rust/src/libstd/panic.rs:394
  92:     0x7f59a549b0fd - std::thread::Builder::spawn_unchecked::{{closure}}::hc2d0ac9187f1dd6d
                               at /home/adema/code/rust/src/libstd/thread/mod.rs:474
  93:     0x7f59a549b0fd - core::ops::function::FnOnce::call_once{{vtable.shim}}::h86e0f7111ce1cb62
                               at /home/adema/code/rust/src/libcore/ops/function.rs:232
  94:     0x7f59a4c6040f - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h7d8c0ce9bb9a9a7b
                               at /home/adema/code/rust/src/liballoc/boxed.rs:1008
  95:     0x7f59a4c48b23 - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::hfcf1edc22130327f
                               at /home/adema/code/rust/src/liballoc/boxed.rs:1008
  96:     0x7f59a4c48b23 - std::sys::unix::thread::Thread::new::thread_start::he3bd71071b1a178e
                               at src/libstd/sys/unix/thread.rs:87
  97:     0x7f59a49e6f27 - start_thread
                               at /builddir/glibc-2.30/nptl/pthread_create.c:479
  98:     0x7f59a4b00e0f - __GI___clone
                               at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
  99:                0x0 - <unknown>
```

### LINKED ISSUE #71820: Invalid lowering of macro in closure
When trying to fix https://github.com/rust-lang/rust/issues/71104 I ended up fighting with some rustdoc test about declarative macro: https://github.com/rust-lang/rust/blob/master/src/test/rustdoc/macro-in-closure.rs

The problem is that the macro is properly lowered to hir because its exported but the parent item is not:
* Macro has def id `DefId(0:5 ~ macro_in_closure[317d]::main[0]::{{closure}}[0]::m[0])`
* Closure has def id `DefId(0:4 ~ macro_in_closure[317d]::main[0]::{{closure}}[0])`

The latter appears nowhere in the hir tree and when https://github.com/rust-lang/rust/blob/master/src/librustc_privacy/lib.rs#L945 tries to access its parent, it returns a `DefId` that has no associated `HirId`.

I don't know exactly how lowering of closure works, neither the details of declarative macro visibility, but i think the bug is either:
* the closure should have been lowered somehow
* the declarative macro should not have been lowered as it is probably not visible outside of the closure

Here is a hir dump of the test case:
```
warning: unused macro definition
 --> src/test/rustdoc/macro-in-closure.rs:7:9
  |
7 |         macro m() {}
  |         ^^^^^^^^^^^^
  |
  = note: `#[warn(unused_macros)]` on by default

Crate {
    item: CrateItem {
        module: Mod {
            inner: src/test/rustdoc/macro-in-closure.rs:3:1: 9:2,
            item_ids: [
                ItemId {
                    id: HirId {
                        owner: DefId(0:1 ~ macro_in_closure[317d]::{{misc}}[0]),
                        local_id: 0,
                    },
                },
                ItemId {
                    id: HirId {
                        owner: DefId(0:2 ~ macro_in_closure[317d]::std[0]),
                        local_id: 0,
                    },
                },
                ItemId {
                    id: HirId {
                        owner: DefId(0:3 ~ macro_in_closure[317d]::main[0]),
                        local_id: 0,
                    },
                },
            ],
        },
        attrs: [
            Attribute {
                kind: Normal(
                    AttrItem {
                        path: Path {
                            span: src/test/rustdoc/macro-in-closure.rs:3:4: 3:11,
                            segments: [
                                PathSegment {
                                    ident: feature#0,
                                    id: NodeId(2),
                                    args: None,
                                },
                            ],
                        },
                        args: Delimited(
                            DelimSpan {
                                open: src/test/rustdoc/macro-in-closure.rs:3:11: 3:12,
                                close: src/test/rustdoc/macro-in-closure.rs:3:22: 3:23,
                            },
                            Parenthesis,
                            TokenStream(
                                [
                                    (
                                        Token(
                                            Token {
                                                kind: Ident(
                                                    "decl_macro",
                                                    false,
                                                ),
                                                span: src/test/rustdoc/macro-in-closure.rs:3:12: 3:22,
                                            },
                                        ),
                                        NonJoint,
                                    ),
                                ],
                            ),
                        ),
                    },
                ),
                id: AttrId(0),
                style: Inner,
                span: src/test/rustdoc/macro-in-closure.rs:3:1: 3:24,
            },
        ],
        span: src/test/rustdoc/macro-in-closure.rs:3:1: 9:2,
    },
    exported_macros: [
        MacroDef {
            ident: m#0,
            vis: Spanned {
                node: Inherited,
                span: src/test/rustdoc/macro-in-closure.rs:7:9: 7:9,
            },
            attrs: [],
            hir_id: HirId {
                owner: DefId(0:5 ~ macro_in_closure[317d]::main[0]::{{closure}}[0]::m[0]),
                local_id: 0,
            },
            span: src/test/rustdoc/macro-in-closure.rs:7:9: 7:21,
            ast: MacroDef {
                body: Delimited(
                    DelimSpan {
                        open: src/test/rustdoc/macro-in-closure.rs:7:16: 7:16,
                        close: src/test/rustdoc/macro-in-closure.rs:7:21: 7:21,
                    },
                    Brace,
                    TokenStream(
                        [
                            (
                                Delimited(
                                    DelimSpan {
                                        open: src/test/rustdoc/macro-in-closure.rs:7:16: 7:17,
                                        close: src/test/rustdoc/macro-in-closure.rs:7:17: 7:18,
                                    },
                                    Paren,
                                    TokenStream(
                                        [],
                                    ),
                                ),
                                NonJoint,
                            ),
                            (
                                Token(
                                    Token {
                                        kind: FatArrow,
                                        span: src/test/rustdoc/macro-in-closure.rs:7:18: 7:19,
                                    },
                                ),
                                NonJoint,
                            ),
                            (
                                Delimited(
                                    DelimSpan {
                                        open: src/test/rustdoc/macro-in-closure.rs:7:19: 7:20,
                                        close: src/test/rustdoc/macro-in-closure.rs:7:20: 7:21,
                                    },
                                    Brace,
                                    TokenStream(
                                        [],
                                    ),
                                ),
                                NonJoint,
                            ),
                        ],
                    ),
                ),
                macro_rules: false,
            },
        },
    ],
    non_exported_macro_attrs: [],
    items: {
        HirId {
            owner: DefId(0:1 ~ macro_in_closure[317d]::{{misc}}[0]),
            local_id: 0,
        }: Item {
            ident: #0,
            hir_id: HirId {
                owner: DefId(0:1 ~ macro_in_closure[317d]::{{misc}}[0]),
                local_id: 0,
            },
            attrs: [
                Attribute {
                    kind: Normal(
                        AttrItem {
                            path: Path {
                                span: src/test/rustdoc/macro-in-closure.rs:1:1: 1:1,
                                segments: [
                                    PathSegment {
                                        ident: prelude_import#1,
                                        id: NodeId(4),
                                        args: None,
                                    },
                                ],
                            },
                            args: Empty,
                        },
                    ),
                    id: AttrId(2),
                    style: Outer,
                    span: src/test/rustdoc/macro-in-closure.rs:1:1: 1:1,
                },
            ],
            kind: Use(
                Path {
                    span: src/test/rustdoc/macro-in-closure.rs:1:1: 1:1,
                    res: Err,
                    segments: [
                        PathSegment {
                            ident: {{root}}#1,
                            hir_id: Some(
                                HirId {
                                    owner: DefId(0:1 ~ macro_in_closure[317d]::{{misc}}[0]),
                                    local_id: 1,
                                },
                            ),
                            res: Some(
                                Err,
                            ),
                            args: None,
                            infer_args: false,
                        },
                        PathSegment {
                            ident: std#1,
                            hir_id: Some(
                                HirId {
                                    owner: DefId(0:1 ~ macro_in_closure[317d]::{{misc}}[0]),
                                    local_id: 2,
                                },
                            ),
                            res: Some(
                                Def(
                                    Mod,
                                    DefId(1:0 ~ std[512e]),
                                ),
                            ),
                            args: None,
                            infer_args: false,
                        },
                        PathSegment {
                            ident: prelude#1,
                            hir_id: Some(
                                HirId {
                                    owner: DefId(0:1 ~ macro_in_closure[317d]::{{misc}}[0]),
                                    local_id: 3,
                                },
                            ),
                            res: Some(
                                Def(
                                    Mod,
                                    DefId(1:15 ~ std[512e]::prelude[0]),
                                ),
                            ),
                            args: None,
                            infer_args: false,
                        },
                        PathSegment {
                            ident: v1#1,
                            hir_id: Some(
                                HirId {
                                    owner: DefId(0:1 ~ macro_in_closure[317d]::{{misc}}[0]),
                                    local_id: 4,
                                },
                            ),
                            res: Some(
                                Def(
                                    Mod,
                                    DefId(1:16 ~ std[512e]::prelude[0]::v1[0]),
                                ),
                            ),
                            args: None,
                            infer_args: false,
                        },
                    ],
                },
                Glob,
            ),
            vis: Spanned {
                node: Inherited,
                span: src/test/rustdoc/macro-in-closure.rs:1:1: 1:1,
            },
            span: src/test/rustdoc/macro-in-closure.rs:1:1: 1:1,
        },
        HirId {
            owner: DefId(0:2 ~ macro_in_closure[317d]::std[0]),
            local_id: 0,
        }: Item {
            ident: std#2,
            hir_id: HirId {
                owner: DefId(0:2 ~ macro_in_closure[317d]::std[0]),
                local_id: 0,
            },
            attrs: [
                Attribute {
                    kind: Normal(
                        AttrItem {
                            path: Path {
                                span: src/test/rustdoc/macro-in-closure.rs:1:1: 1:1,
                                segments: [
                                    PathSegment {
                                        ident: macro_use#1,
                                        id: NodeId(10),
                                        args: None,
                                    },
                                ],
                            },
                            args: Empty,
                        },
                    ),
                    id: AttrId(1),
                    style: Outer,
                    span: src/test/rustdoc/macro-in-closure.rs:1:1: 1:1,
                },
            ],
            kind: ExternCrate(
                None,
            ),
            vis: Spanned {
                node: Inherited,
                span: src/test/rustdoc/macro-in-closure.rs:1:1: 1:1,
            },
            span: src/test/rustdoc/macro-in-closure.rs:1:1: 1:1,
        },
        HirId {
            owner: DefId(0:3 ~ macro_in_closure[317d]::main[0]),
            local_id: 0,
        }: Item {
            ident: main#0,
            hir_id: HirId {
                owner: DefId(0:3 ~ macro_in_closure[317d]::main[0]),
                local_id: 0,
            },
            attrs: [],
            kind: Fn(
                FnSig {
                    header: FnHeader {
                        unsafety: Normal,
                        constness: NotConst,
                        asyncness: NotAsync,
                        abi: Rust,
                    },
                    decl: FnDecl {
                        inputs: [],
                        output: DefaultReturn(
                            src/test/rustdoc/macro-in-closure.rs:5:11: 5:11,
                        ),
                        c_variadic: false,
                        implicit_self: None,
                    },
                },
                Generics {
                    params: [],
                    where_clause: WhereClause {
                        predicates: [],
                        span: src/test/rustdoc/macro-in-closure.rs:5:10: 5:10,
                    },
                    span: src/test/rustdoc/macro-in-closure.rs:5:8: 5:8,
                },
                BodyId {
                    hir_id: HirId {
                        owner: DefId(0:3 ~ macro_in_closure[317d]::main[0]),
                        local_id: 6,
                    },
                },
            ),
            vis: Spanned {
                node: Inherited,
                span: src/test/rustdoc/macro-in-closure.rs:5:1: 5:1,
            },
            span: src/test/rustdoc/macro-in-closure.rs:5:1: 9:2,
        },
    },
    trait_items: {},
    impl_items: {},
    bodies: {
        BodyId {
            hir_id: HirId {
                owner: DefId(0:3 ~ macro_in_closure[317d]::main[0]),
                local_id: 2,
            },
        }: Body {
            params: [],
            value: Expr {
                hir_id: HirId {
                    owner: DefId(0:3 ~ macro_in_closure[317d]::main[0]),
                    local_id: 2,
                },
                kind: Block(
                    Block {
                        stmts: [],
                        expr: None,
                        hir_id: HirId {
                            owner: DefId(0:3 ~ macro_in_closure[317d]::main[0]),
                            local_id: 1,
                        },
                        rules: DefaultBlock,
                        span: src/test/rustdoc/macro-in-closure.rs:6:8: 8:6,
                        targeted_by_break: false,
                    },
                    None,
                ),
                attrs: ThinVec(
                    None,
                ),
                span: src/test/rustdoc/macro-in-closure.rs:6:8: 8:6,
            },
            generator_kind: None,
        },
        BodyId {
            hir_id: HirId {
                owner: DefId(0:3 ~ macro_in_closure[317d]::main[0]),
                local_id: 6,
            },
        }: Body {
            params: [],
            value: Expr {
                hir_id: HirId {
                    owner: DefId(0:3 ~ macro_in_closure[317d]::main[0]),
                    local_id: 6,
                },
                kind: Block(
                    Block {
                        stmts: [
                            Stmt {
                                hir_id: HirId {
                                    owner: DefId(0:3 ~ macro_in_closure[317d]::main[0]),
                                    local_id: 4,
                                },
                                kind: Semi(
                                    Expr {
                                        hir_id: HirId {
                                            owner: DefId(0:3 ~ macro_in_closure[317d]::main[0]),
                                            local_id: 3,
                                        },
                                        kind: Closure(
                                            Ref,
                                            FnDecl {
                                                inputs: [],
                                                output: DefaultReturn(
                                                    src/test/rustdoc/macro-in-closure.rs:6:8: 6:8,
                                                ),
                                                c_variadic: false,
                                                implicit_self: None,
                                            },
                                            BodyId {
                                                hir_id: HirId {
                                                    owner: DefId(0:3 ~ macro_in_closure[317d]::main[0]),
                                                    local_id: 2,
                                                },
                                            },
                                            src/test/rustdoc/macro-in-closure.rs:6:5: 6:7,
                                            None,
                                        ),
                                        attrs: ThinVec(
                                            None,
                                        ),
                                        span: src/test/rustdoc/macro-in-closure.rs:6:5: 8:6,
                                    },
                                ),
                                span: src/test/rustdoc/macro-in-closure.rs:6:5: 8:7,
                            },
                        ],
                        expr: None,
                        hir_id: HirId {
                            owner: DefId(0:3 ~ macro_in_closure[317d]::main[0]),
                            local_id: 5,
                        },
                        rules: DefaultBlock,
                        span: src/test/rustdoc/macro-in-closure.rs:5:11: 9:2,
                        targeted_by_break: false,
                    },
                    None,
                ),
                attrs: ThinVec(
                    None,
                ),
                span: src/test/rustdoc/macro-in-closure.rs:5:11: 9:2,
            },
            generator_kind: None,
        },
    },
    trait_impls: {},
    body_ids: [
        BodyId {
            hir_id: HirId {
                owner: DefId(0:3 ~ macro_in_closure[317d]::main[0]),
                local_id: 6,
            },
        },
        BodyId {
            hir_id: HirId {
                owner: DefId(0:3 ~ macro_in_closure[317d]::main[0]),
                local_id: 2,
            },
        },
    ],
    modules: {
        HirId {
            owner: DefId(0:0 ~ macro_in_closure[317d]),
            local_id: 0,
        }: ModuleItems {
            items: {
                HirId {
                    owner: DefId(0:1 ~ macro_in_closure[317d]::{{misc}}[0]),
                    local_id: 0,
                },
                HirId {
                    owner: DefId(0:2 ~ macro_in_closure[317d]::std[0]),
                    local_id: 0,
                },
                HirId {
                    owner: DefId(0:3 ~ macro_in_closure[317d]::main[0]),
                    local_id: 0,
                },
            },
            trait_items: {},
            impl_items: {},
        },
    },
    proc_macros: [],
warning: 1 warning emitted
}
```

cc https://github.com/rust-lang/rust/issues/39412

### PR DESCRIPTION
**Pull request by jyn514**
r? @eddyb 
cc @petrochenkov, @GuillaumeGomez, @Manishearth, @ecstatic-morse, @marmeladema 

~~Blocked on https://github.com/rust-lang/rust/pull/73743~~ Merged.
~~Blocked on crater run.~~ Crater popped up some ICEs ([now fixed](https://github.com/rust-lang/rust/pull/73566#issuecomment-656934851)). See [crater run](https://crater-reports.s3.amazonaws.com/pr-73566/index.html), [ICEs](https://github.com/rust-lang/rust/pull/73566#issuecomment-653619212).
~~Blocked on #74070 so that we don't make typeck_tables_of public when it shouldn't be.~~ Merged.

Closes #71820, closes #71104, closes #65863.

## What is the motivation for this change?

As seen from a lengthy trail of PRs and issues (https://github.com/rust-lang/rust/pull/73532, https://github.com/rust-lang/rust/pull/73103, https://github.com/rust-lang/rust/issues/71820, https://github.com/rust-lang/rust/issues/71104), `everybody_loops` is causing bugs in rustdoc. The main issue is that it does not preserve the validity of the `DefId` tree, meaning that operations on DefIds may unexpectedly fail when called later. This is blocking intra-doc links (see https://github.com/rust-lang/rust/pull/73101).

This PR starts by removing `everybody_loops`, fixing #71104 and #71820. However, that brings back the bugs seen originally in https://github.com/rust-lang/rust/pull/43348: Since libstd documents items for all platforms, the function bodies sometimes do not type check. Here are the errors from documenting `libstd` with `everybody_loops` disabled and no other changes:

```rust
error[E0433]: failed to resolve: could not find `handle` in `sys`
  --> src/libstd/sys/windows/ext/process.rs:13:27
   |
13 |         let handle = sys::handle::Handle::new(handle as *mut _);
   |                           ^^^^^^ could not find `handle` in `sys`

error[E0425]: cannot find function `symlink_inner` in module `sys::fs`
   --> src/libstd/sys/windows/ext/fs.rs:544:14
    |
544 |     sys::fs::symlink_inner(src.as_ref(), dst.as_ref(), false)
    |              ^^^^^^^^^^^^^ not found in `sys::fs`

error[E0425]: cannot find function `symlink_inner` in module `sys::fs`
   --> src/libstd/sys/windows/ext/fs.rs:564:14
    |
564 |     sys::fs::symlink_inner(src.as_ref(), dst.as_ref(), true)
    |              ^^^^^^^^^^^^^ not found in `sys::fs`
```

## Why does this need changes to `rustc_resolve`?

Normally, this could be avoided by simply not calling the `typeck_item_bodies` pass. However, the errors above happen before type checking, in name resolution itself. Since name resolution is intermingled with macro expansion, and rustdoc needs expansion to happen before it knows all items to be documented, there needs to be someway to ignore _resolution_ errors in function bodies.

An alternative solution suggested by @petrochenkov was to not run `everybody_loops` on anything containing a nested `DefId`. This would solve some of the immediate issues, but isn't bullet-proof: the following functions still could not be documented if the items in the body failed to resolve:

- Functions containing a nested `DefId` (https://github.com/rust-lang/rust/issues/71104)
- ~~Functions returning `impl Trait` (https://github.com/rust-lang/rust/pull/43878)~~ These ended up not resolving anyway with this PR.
- ~~`const fn`, because `loop {}` in `const fn` is unstable (https://github.com/rust-lang/rust/issues/43636)~~ `const_loop` was just stabilized.

This also isn't exactly what rustdoc wants, which is to avoid looking at function bodies in the first place.

<a id="what-changes-were-made" href="#what-changes-were-made">

## What changes were made?

</a>

The hack implemented in this PR is to add an option to ignore all resolution errors in function bodies. This is enabled only for rustdoc. Since resolution errors are ignored, the MIR generated will be invalid, as can be seen in the following ICE:

```rust
error: internal compiler error: broken MIR in DefId(0:11 ~ doc_cfg[8787]::uses_target_feature[0]) ("return type"): bad type [type error]
  --> /home/joshua/src/rust/src/test/rustdoc/doc-cfg.rs:51:1
   |
51 | / pub unsafe fn uses_target_feature() {
52 | |     content::should::be::irrelevant();
53 | | }
   | |_^
```

Fortunately, rustdoc does not need to access MIR in order to generate documentation. Therefore this also removes the call to `analyze()` in `rustdoc::run_core`. This has the side effect of not generating all lints by default. Most lints are safe to ignore (does rustdoc really need to run liveness analysis?) but `missing_docs` in particular is disabled when it should not be. Re-running `missing_docs` specifically does not help, because it causes the typechecking pass to be run, bringing back the errors from #24658:

```
error[E0599]: no method named `into_handle` found for struct `sys::unix::pipe::AnonPipe` in the current scope
  --> src/libstd/sys/windows/ext/process.rs:71:27
   |
71 |         self.into_inner().into_handle().into_raw() as *mut _
   |                           ^^^^^^^^^^^ method not found in `sys::unix::pipe::AnonPipe`
   |
```

Because of #73743, we only run typeck on demand. So this only causes an issue for functions returning `impl Trait`, which were already special cased by `ReplaceFunctionWithBody`. However, it now considers `async fn f() -> T` to be considered `impl Future<Output = T>`, where before it was considered to have a concrete `T` type.

## How will this affect future changes to rustdoc?

- Any new changes to rustdoc will not be able to perform type checking without bringing back resolution errors in function bodies.
    + As a corollary, any new lints cannot require or perform type checking. In some cases this may require refactoring other parts of the compiler to perform type-checking only on-demand, see for example #73743.
    + As a corollary, rustdoc can never again call `tcx.analysis()` unless this PR is reverted altogether.

## Current status

- ~~I am not yet sure how to bring back `missing_docs` without running typeck. @eddyb suggested allowing lints to opt-out of type-checking, which would probably be another rabbit hole.~~ The opt-out was implemented in https://github.com/rust-lang/rust/pull/73743. However, of the rustc lints, now _only_ missing_docs is run and no other lints: https://github.com/rust-lang/rust/pull/73566#issuecomment-650213058. We need a team decision on whether that's an acceptable tradeoff. Note that all rustdoc lints are still run (`intra_doc_link_resolution_failure`, etc). **UPDATE**: This was deemed acceptable in https://github.com/rust-lang/rust/pull/73566#issuecomment-655750237
- ~~The implementation of optional errors in `rustc_resolve` is very brute force, it should probably be moved from `LateResolver` to `Resolver` to avoid duplicating the logic in many places.~~ I'm mostly happy with it now.

- This no longer allows errors in `async fn f() -> T`. This caused breakage in 50 crates out of a full crater run, all of which (that I looked at) didn't compile when run with rustc directly. In other words, it used to be that they could not be compiled but could still be documented; now they can't be documented either. This needs a decision from the rustdoc team on whether this is acceptable breakage. **UPDATE**: This was deemed acceptable in https://github.com/rust-lang/rust/pull/73566#issuecomment-655750237
- ~~This makes `fn typeck_tables_of` in `rustc_typeck` public. This is not desired behavior, but needs the changes from https://github.com/rust-lang/rust/pull/74070 in order to be fixed.~~ Reverted.

### CODE REVIEW

**Comment by jyn514** [comment]
I'm not sure if perf runs are a thing for rustdoc, but if so I would be very curious whether this helps or hurts performance.

**Review by Manishearth — APPROVED** [review]
This is a neat approach! Looks like there's still some work to be done for missing_docs, but I like this idea!

(I'd defer to eddy on the actual review)

**Comment by Manishearth** [comment]
> I am not yet sure how to bring back missing_docs without running typeck

Why do we need typeck for this lint? I'm confused: can we not run this lint on the HIR?

**Comment by jyn514** [comment]
> Why do we need typeck for this lint? I'm confused: can we not run this lint on the HIR?

We don't need typeck, but it's being run anyway. Currently typeck is run unconditionally for all lints: https://github.com/rust-lang/rust/blob/d4e143ed2f248a808fb5f1cf959f630d419cc01b/src/librustc_lint/late.rs#L107-L113 `body_tables` calls `typeck_tables_of`.

File: src/librustc_interface/passes.rs [hunk 1]
```diff
@@ -350,13 +350,12 @@ fn configure_and_expand_inner<'a>(
         )
     });
 
-    // If we're actually rustdoc then there's no need to actually compile
-    // anything, so switch everything to just looping
-    let mut should_loop = sess.opts.actually_rustdoc;
+    let mut should_loop = false;
```
Comment (pnkfelix) [inline src/librustc_interface/passes.rs:353]:
```suggestion
    let should_loop = match sess.opts.pretty { Some(PpMode::PpmSource(PpSourceMode::PpmEveryBodyLoops)) => true, _ => false };
```

(or use the `matches!` macro, if we use that elsewhere in this crate; I cannot recall whether the team has adopted that macro or not.)

File: src/librustc_resolve/late.rs [hunk 2]
```diff
@@ -1790,6 +1815,20 @@ impl<'a, 'b, 'ast> LateResolutionVisitor<'a, 'b, 'ast> {
         if let Some(LexicalScopeBinding::Res(res)) = binding { res != Res::Err } else { false }
     }
 
+    /// A wrapper around [`Resolver::report_error`].
+    ///
+    /// This doesn't emit errors for function bodies if `ignore_bodies` is set.
```
Comment (pnkfelix) [inline src/librustc_resolve/late.rs:1820]: This comment seems slightly misleading; its not as if the implementation of this helper *knows* that its being called from within the context of a function body or not, right? That is instead a property of the call sites. So I'd just write "This doesn't emit errors if` ignore_bodies` is set".

That then leads me to wonder; are all of the current call sites always within function bodies, or are there some that are reporting errors from name resolutions from e.g. type signatures? (Its an honest question; I don't know the answer one way or another.) If there's a simple way to re-enforce that expectation, such as naming this `report_error_within_fn_body`, that might help...

File: src/test/rustdoc/doc-cfg.rs [hunk 3]
```diff
@@ -57,5 +57,7 @@ pub unsafe fn uses_target_feature() {
 //        'This is supported with target feature avx only.'
 #[doc(cfg(target_feature = "avx"))]
 pub fn uses_cfg_target_feature() {
-    uses_target_feature();
```
Comment (pnkfelix) [inline src/test/rustdoc/doc-cfg.rs:60]: Is this change an expected outcome?

**Comment by Manishearth** [comment]
> We don't need typeck, but it's being run anyway. Currently typeck is run unconditionally for all lints: 

Wait, but, we want to run the missing_docs lint in rustc, not rustdoc, yes? So how does this matter? The only issue is that missing_docs won't complain about cross-platform docs, which seems okay

**Comment by pnkfelix** [comment]
> > We don't need typeck, but it's being run anyway. Currently typeck is run unconditionally for all lints:
> 
> Wait, but, we want to run the missing_docs lint in rustc, not rustdoc, yes? So how does this matter? The only issue is that missing_docs won't complain about cross-platform docs, which seems okay

To be clear: Are you suggesting that @jyn514 just revise their PR to disable the missing_docs lint *solely* when rustdoc is running (i.e. baseed on `sess.opts.actually_rustdoc`, as is done elsewhere)?

I just wanted to make sure I'm interpreting your feedback the right way.

**Comment by Manishearth** [comment]
> To be clear: Are you suggesting that @jyn514 just revise their PR to disable the missing_docs lint solely when rustdoc is running (i.e. baseed on sess.opts.actually_rustdoc, as is done elsewhere)?

So I was under the impression that rustdoc doesn't run normal lints. Turns out, it does, just some very whitelisted ones

https://github.com/rust-lang/rust/blob/1a4e2b6f9c75a0e21722c88a0e3b610d6ffc3ae3/src/librustdoc/core.rs#L306-L311

Given this mechanism it seems like this just disables the _reporting_ of some lints, it's not clear how this disables them from _running_, though. Maybe I'm misreading this.

Either way! It should be possible to write missing_docs as a builtin rustdoc pass if we so wish, so it relies on rustdoc's lint framework, not rustc's.

**Comment by jyn514** [comment]
> Given this mechanism it seems like this just disables the reporting of some lints, it's not clear how this disables them from running, though. Maybe I'm misreading this.

As far as I understand, all the lints were previously run by `analysis()`. Since [I removed the call to analysis()](https://github.com/rust-lang/rust/pull/73566/files#diff-0de644786a2f1fd88c7d7f44bc3fa4bbL412), that means that any lints from rustc that rustdoc wants have to be [opted-into explicitly](https://github.com/rust-lang/rust/pull/73566/files#diff-0de644786a2f1fd88c7d7f44bc3fa4bbR413).

> Either way! It should be possible to write missing_docs as a builtin rustdoc pass if we so wish, so it relies on rustdoc's lint framework, not rustc's. This would mean having two potentially different versions of the lint running, though.

That seems a lot more complicated than making `typeck` opt-out for lints 😅

**Comment by jyn514** [comment]
> To be clear: Are you suggesting that @jyn514 just revise their PR to disable the missing_docs lint solely when rustdoc is running (i.e. baseed on sess.opts.actually_rustdoc, as is done elsewhere)?

To remove the `missing_docs` lint I'd only have to remove the call to `rustc_lint::MissingDoc` (no special casing the compiler needed). I don't think that's desired behavior though.

File: src/librustc_resolve/late.rs (hunk 2 above)
Comment (jyn514) [reply src/librustc_resolve/late.rs:1820]: > its not as if the implementation of this helper knows that its being called from within the context of a function body or not, right?

It does know actually - if you look at `should_report_errs()` that checks whether `current_function.is_none()` and if so says the error should be reported.

I'm not sure what the behavior is if there is an impl nested inside a function - it should give an error if not resolved but that might not be the current behavior.

File: src/test/rustdoc/doc-cfg.rs (hunk 3 above)
Comment (jyn514) [reply src/test/rustdoc/doc-cfg.rs]: This change is not actually necessary, I noticed the `unsafe` error before removing the `analysis()` pass but now that pass is gone it will document without error. I undid the change.

File: src/librustc_resolve/late.rs (hunk 2 above)
Comment (jyn514) [reply src/librustc_resolve/late.rs:1820]: Ok yes this does not have the proper behavior for nested impls.
```rust
$ cat impl-fn-nesting.rs 
struct MyType;

fn f() {
    impl MyTrait for MyType {}
}
$ rustdoc +stable impl-fn-nesting.rs 
error[E0405]: cannot find trait `MyTrait` in this scope
 --> impl-fn-nesting.rs:4:10
  |
4 |     impl MyTrait for MyType {}
  |          ^^^^^^^ not found in this scope

error: Compilation failed, aborting rustdoc

error: aborting due to 2 previous errors

For more information about this error, try `rustc --explain E0405`.
$ rustdoc +stage1 impl-fn-nesting.rs 
$
```
Maybe errors about trait implementations and macros should be special cased so that they still give an error? The criteria here is whether the item is publicly visible.

**Comment by Manishearth** [comment]
> As far as I understand, all the lints were previously run by analysis()

aha! I see.



> That seems a lot more complicated than making `typeck` opt-out for lints sweat_smile

Right, but you still have the problem that _all_ lints are being run when you do this, not just the ones you care about.

What I'm trying to suggest is that we manually run the missing_docs pass, either by reusing the same code or rewriting it, as part of rustdoc directly.

**Comment by jyn514** [comment]
> Right, but you still have the problem that all lints are being run when you do this, not just the ones you care about.

I don't think that's the case? The `missing_doc` pass is only run [here](https://github.com/rust-lang/rust/pull/73566/files#diff-0de644786a2f1fd88c7d7f44bc3fa4bbR413), I would be very surprised if that caused the full suite of lints to be emitted. This is beyond my knowledge of the compiler though.

**Comment by Manishearth** [comment]
Oh, I see. Never mind.

I guess it's okayish to take that approach, I'm just concerned that it will make the lints more brittle. The missing docs lint pass is quite straightforward, it should be super easy to replicate it as a visitor or a doc pass.

File: src/librustc_resolve/late.rs (hunk 2 above)
Comment (jyn514) [reply src/librustc_resolve/late.rs:1825]: I added some special casing and this now correctly gives an error but I'm not sure how well the approach generalizes ... it certainly doesn't handle `fn -> impl -> fn` (test case in latest commit) and there may be more things I didn't think of.

Comment (jyn514) [reply src/librustc_resolve/late.rs:1825]: I think I need to look at `self.ribs` instead of blanket 'in trait' and 'in function' lookups, that might get me the inner-most scope.

Comment (jyn514) [reply src/librustc_resolve/late.rs:1825]: I added a commit which fixes this case. Not sure I thought of all the error cases, but getting closer.

Comment (jyn514) [reply src/librustc_resolve/late.rs:1843]: Ok, got it for real now. Instead of trying to reconstruct the state from whatever misc info was lying around at the time, I just added an explicit variable on `self` to keep track of it. This is ready for re-review (let me know if I should squash the commits, most are just me debugging).

> This comment seems slightly misleading; its not as if the implementation of this helper knows that its being called from within the context of a function body or not, right? That is instead a property of the call sites.

Exactly, so I added information to `self.ignore_bodies_state` to keep track of where this was being called from. It works as a stack but only needs to updated in a few select places.

File: src/librustc_resolve/late.rs [hunk 4]
```diff
@@ -368,6 +368,19 @@ struct DiagnosticMetadata<'ast> {
...
 
+/// Keeps track of whether errors should be reported.
+///
+/// Used by rustdoc to ignore errors in function bodies.
+#[derive(Copy, Clone, Debug)]
+enum IgnoreState {
+    /// We are at global scope and therefore all errors should be reported.
+    Global,
+    /// We are at function scope and therefore only errors from nested trait impls should be reported.
+    Function,
```
Comment (jyn514) [inline src/librustc_resolve/late.rs:379]: These states are redundant, this whole struct can be collapsed into a single boolean.

File: src/librustc_interface/passes.rs [hunk 5]
```diff
@@ -352,13 +352,7 @@ fn configure_and_expand_inner<'a>(
...
-    // If we're actually rustdoc then there's no need to actually compile
-    // anything, so switch everything to just looping
-    let mut should_loop = sess.opts.actually_rustdoc;
     if let Some(PpMode::PpmSource(PpSourceMode::PpmEveryBodyLoops)) = sess.opts.pretty {
-        should_loop |= true;
-    }
-    if should_loop {
         log::debug!("replacing bodies with loop {{}}");
         util::ReplaceBodyWithLoop::new(&mut resolver).visit_crate(&mut krate);
     }
```
Comment (bjorn3) [inline src/librustc_interface/passes.rs:358]: Why not completely remove this?

File: src/librustc_resolve/late.rs [hunk 6]
```diff
@@ -370,6 +370,19 @@ struct DiagnosticMetadata<'ast> {
...
+/// Keeps track of whether errors should be reported.
+///
+/// Used by rustdoc to ignore errors in function bodies.
+/// This is just a fancy boolean so it can have doc-comments.
+#[derive(Copy, Clone, Debug)]
+enum IgnoreState {
+    /// We are at global scope or in a trait implementation, so all errors should be reported.
+    Ignore,
+    /// We are in a function body, so errors shouldn't be reported.
+    Report,
```
Comment (bjorn3) [inline src/librustc_resolve/late.rs:382]: The doc comments seem to have been swapped.

File: src/librustc_interface/passes.rs (hunk 5 above)
Comment (jyn514) [reply src/librustc_interface/passes.rs:358]: This is still useful as a debugging option, originally it had nothing to do with rustdoc: https://github.com/rust-lang/rust/pull/19964.

I don't feel strongly about it but I don't think removing it should go in the same PR as fixing rustdoc bugs.

**Comment by jyn514** [comment]
This does have one difference from previously, the following no longer gives an error:

```rust
trait NeedsBody { fn g(); }
struct S;
fn f() {
   impl NeedsBody for S {
       fn g() {
           fn doubly_nested(a: UnknownType) {}
       }
   }
}
```
However `doubly_nested` can never be documented so I don't know that we need to worry about this change.

**Comment by jyn514** [comment]
https://github.com/rust-lang/rust/pull/73743#issuecomment-650142119 :( It's still running typeck on the bodies. Maybe it would make more sense to write `missing_docs` as a separate rustdoc pass after all.

**Comment by jyn514** [comment]
The issue is that rustdoc still _runs_ all lints even though it doesn't _report_ them: https://github.com/rust-lang/rust/blob/master/src/librustdoc/core.rs#L366

I tried not running the lints at all and that worked:
```diff
diff --git a/src/librustdoc/core.rs b/src/librustdoc/core.rs
index e18be549420..852f872205c 100644
--- a/src/librustdoc/core.rs
+++ b/src/librustdoc/core.rs
@@ -365,7 +365,10 @@ pub fn run_core(options: RustdocOptions) -> (clean::Crate, RenderInfo, RenderOpt
         crate_name,
         lint_caps,
         register_lints: None,
-        override_queries: None,
+        override_queries: Some(|_sess, local_providers, external_providers| {
+            local_providers.lint_mod = |_, _| {};
+            external_providers.lint_mod = |_, _| {};
+        }),
         registry: rustc_driver::diagnostics_registry(),
     };
```
but the issue then is that it's no longer possible to warn or deny those lints:
```
$ cat const.rs 
const i: i32 = {
    1 + 2;
    1
};
$ rustdoc +stable const.rs 
warning: constant `i` should have an upper case name
 --> const.rs:1:7
  |
1 | const i: i32 = {
  |       ^ help: convert the identifier to upper case (notice the capitalization): `I`
  |
  = note: `#[warn(non_upper_case_globals)]` on by default

warning: unused arithmetic operation that must be used
 --> const.rs:2:5
  |
2 |     1 + 2;
  |     ^^^^^
  |
  = note: `#[warn(unused_must_use)]` on by default
$ rustdoc +stage1 const.rs
// no output
$
```

This doesn't show up in the test suite because we don't test these warnings. Are these lints something we want to keep? If so, we'll have to only re-enable specific lints, running any lint that requires type checking will still give an ICE.

**Comment by Manishearth** [comment]
I personally am OK with only running rustdoc lints during rustdoc runs.

**Comment by jyn514** [comment]
@rustbot modify labels: I-needs-decision S-waiting-on-team T-rustdoc

Leaving S-waiting-on-review since this changed a fair bit between the last time @pnkfelix reviewed.

**Comment by jyn514** [comment]
@craterbot run mode=rustdoc

I'm not sure I caught everything, and this changes a lot of rustdoc internals, especially how it handles function bodies.

**Comment by Manishearth** [comment]
@bors try for crater

@Mark-Simulacrum would y'all be able to queue up a crater run for this? I know how, but I don't want to step on toes or get it wrong :smile:

**Comment by Manishearth** [comment]
I'm not actually sure if we should crater here: The fear is that this will ICE something unexpected, but perhaps we can just land this and revert it if we have problems in nightly or the beta crater run?

**Comment by jyn514** [comment]
I'm not as worried about ICEs as I am about unknowingly breaking code. As we saw from the tests I had to add, this part of rustdoc isn't tested very well.

**Comment by Manishearth** [comment]
@jyn514 Yeah, but the crater run won't tell us about this anyway?

**Comment by jyn514** [comment]
Crater wouldn't tell us about silently losing docs, but that's not the sort of bug I expect from this PR; I expect either name errors or ICEs, which crater will find. If we merge without crater, docs.rs will catch some of those but only if people report them, and at the cost of possibly breaking documentation across the ecosystem.

**Comment by Mark-Simulacrum** [comment]
@craterbot run mode=rustdoc

**Comment by Mark-Simulacrum** [comment]
@craterbot run mode=rustdoc start=master#394e1b40d264aa6928811919c1124fa248e7d802 end=try#66dfc4e010913fbed0c4ea91fc2c010004b0f441

**Comment by nikomatsakis** [comment]
@eddyb the recent PRs you've been doing that avoid "empty typeck tables" and the like, do they help us to avoid running typeck for lints in this case? Can we just run typeck lazilly when its results are actually *needed*?

**Comment by jyn514** [comment]
> @eddyb the recent PRs you've been doing that avoid "empty typeck tables" and the like, do they help us to avoid running typeck for lints in this case? Can we just run typeck lazilly when its results are actually _needed_?

Yes, this is what lets us run the `missing_docs` lint. Previously all lints ran typeck even if they didn't need it.

**Comment by jyn514** [comment]
Some failing test cases from the compiler meeting this morning:
```rust
pub fn f() -> impl std::fmt::Debug {
    content::doesnt::matter();
}
error: internal compiler error: TyKind::Error constructed but no error reported
```
No docs are emitted at all for the following:
```rust
/// debug type
pub type Foo = impl Debug;

pub fn foo() -> Foo {
    1
}
```

**Comment by bjorn3** [comment]
Some crash excerpts:

https://crater-reports.s3.amazonaws.com/pr-73566/try%2366dfc4e010913fbed0c4ea91fc2c010004b0f441/gh/Dizans.rust_book/log.txt

```
[INFO] [stdout] error: internal compiler error: TyKind::Error constructed but no error reported
[INFO] [stdout]   |
[INFO] [stdout]   = note: delayed at /rustc/66dfc4e010913fbed0c4ea91fc2c010004b0f441/src/librustc_session/session.rs:436:27
```

https://crater-reports.s3.amazonaws.com/pr-73566/try%2366dfc4e010913fbed0c4ea91fc2c010004b0f441/gh/robinmoussu.Pyrite/log.txt

```
[INFO] [stdout] error: internal compiler error[E0391]: cycle detected when computing `Sized` constraints for `BinaryExpression`
[INFO] [stdout]   --> src/main.rs:65:1
[INFO] [stdout]    |
[INFO] [stdout] 65 | struct BinaryExpression {
[INFO] [stdout]    | ^^^^^^^^^^^^^^^^^^^^^^^
[INFO] [stdout]    |
[INFO] [stdout] note: ...which requires computing `Sized` constraints for `Expression`...
[INFO] [stdout]   --> src/main.rs:72:1
[INFO] [stdout]    |
[INFO] [stdout] 72 | enum Expression {
[INFO] [stdout]    | ^^^^^^^^^^^^^^^
[INFO] [stdout]    = note: ...which again requires computing `Sized` constraints for `BinaryExpression`, completing the cycle
[INFO] [stdout]    = note: cycle used when evaluating trait selection obligation `BinaryExpression: std::convert::From<BinaryExpression>`
```

https://crater-reports.s3.amazonaws.com/pr-73566/try%2366dfc4e010913fbed0c4ea91fc2c010004b0f441/gh/maybeinit.airplay-rs/log.txt

```
[INFO] [stderr]  Documenting kosmos v0.1.0 (/opt/rustwide/workdir)
[INFO] [stdout] error[E0061]: this function takes 2 arguments but 4 arguments were supplied
[INFO] [stdout]    --> src/main.rs:106:10
[INFO] [stdout]     |
[INFO] [stdout] 106 |         .process_reply(&unique_id, &salt_u8, &x, &pk)
[INFO] [stdout]     |          ^^^^^^^^^^^^^ ----------  --------  --  --- supplied 4 arguments
[INFO] [stdout]     |          |
[INFO] [stdout]     |          expected 2 arguments
[INFO] [stdout] 
[INFO] [stdout] 
[INFO] [stdout] error[E0308]: mismatched types
[INFO] [stdout]    --> src/main.rs:150:30
[INFO] [stdout]     |
[INFO] [stdout] 150 |     (resp, Vec::from(proof), k)
[INFO] [stdout]     |                              ^
[INFO] [stdout]     |                              |
[INFO] [stdout]     |                              expected struct `std::vec::Vec`, found struct `generic_array::GenericArray`
[INFO] [stdout]     |                              help: try using a conversion method: `k.to_vec()`
[INFO] [stdout]     |
[INFO] [stdout]     = note: expected struct `std::vec::Vec<u8>`
[INFO] [stdout]                found struct `generic_array::GenericArray<u8, typenum::uint::UInt<typenum::uint::UInt<typenum::uint::UInt<typenum::uint::UInt<typenum::uint::UInt<typenum::uint::UTerm, typenum::bit::B1>, typenum::bit::B0>, typenum::bit::B1>, typenum::bit::B0>, typenum::bit::B0>>`
```

**Comment by jyn514** [comment]
The fixes are also interesting:
- build compiler-error(E0277) (60) 
- build compiler-error(E0635) (126) 
-  build compiler-error(E0658) (58) 

```
$ rustc --explain E0277 | head -n2
You tried to use a type which doesn't implement some trait in a place which
expected that trait.
$ rustc --explain E0635 | head -n1
The `#![feature]` attribute specified an unknown feature.
$ rustc --explain E0658 | head -n1
An unstable feature was used.
```

I guess since we're no longer running the `analysis` pass those errors are never checked.

**Comment by jyn514** [comment]
The first 4 ICEs are for name resolution errors with `fn f() -> impl Trait` (one of them is an `async fn` which I think desugars to `impl Future` internally). The 5th I have to look at more closely.

**Comment by Manishearth** [comment]
Type errors could come out of conditionally resolving to different types or signatures

**Comment by jyn514** [comment]
The `impl Trait` errors are because `privacy_access_levels` is typechecking the bodies while running the `missing_docs` pass. I'm not sure exactly why, apparently it's trying to decide whether things are reachable (??) I think it's trying to compute the type of the return value from the type of the function body, even though it doesn't need to for this pass.

Relevant parts of the backtrace:
```
 192: rustc_middle::ty::query::<impl rustc_query_system::query::config::QueryAccessor
s<rustc_middle::ty::context::TyCtxt> for rustc_middle::ty::query::queries::mir_borrow
ck>::compute
             at /home/joshua/src/rust/src/librustc_middle/ty/query/plumbing.rs:362
 221: rustc_middle::ty::query::<impl rustc_query_system::query::config::QueryAccessors<rustc_middle::ty::context::TyCtxt> for rustc_middle::ty::query::queries::type_of>::compute
 246: <rustc_privacy::EmbargoVisitor as rustc_hir::intravisit::Visitor>::visit_item
             at src/librustc_privacy/lib.rs:0
 250: rustc_hir::intravisit::walk_fn_ret_ty
             at /home/joshua/src/rust/src/librustc_hir/intravisit.rs:896
 261: rustc_privacy::privacy_access_levels
             at src/librustc_privacy/lib.rs:2068
 262: rustc_middle::ty::query::<impl rustc_query_system::query::config::QueryAccessor
s<rustc_middle::ty::context::TyCtxt> for rustc_middle::ty::query::queries::privacy_ac
cess_levels>::compute
             at /home/joshua/src/rust/src/librustc_middle/ty/query/plumbing.rs:362
 288: rustc_middle::ty::query::TyCtxtAt::privacy_access_levels
             at /home/joshua/src/rust/src/librustc_middle/ty/query/plumbing.rs:472
 289: rustc_middle::ty::query::<impl rustc_middle::ty::context::TyCtxt>::privacy_acce
ss_levels
             at /home/joshua/src/rust/src/librustc_middle/ty/query/plumbing.rs:433
 290: rustc_lint::late::late_lint_pass_crate
             at /home/joshua/src/rust/src/librustc_lint/late.rs:419
 297: rustc_lint::late::check_crate
             at /home/joshua/src/rust/src/librustc_lint/late.rs:483
 298: rustdoc::core::run_core::{{closure}}::{{closure}}::{{closure}}::{{closure}}
             at src/librustdoc/core.rs:423
```

[backtrace.log](https://github.com/rust-lang/rust/files/4871627/backtrace.log)

**Comment by jyn514** [comment]
Relevant code: https://github.com/rust-lang/rust/blob/780d6cb1408717f968a21d627cc34c8ffa7f6fe8/src/librustc_privacy/lib.rs#L796

File: src/librustc_resolve/lib.rs [hunk 7]
```diff
@@ -1441,13 +1441,13 @@ impl<'a> Resolver<'a> {
...
     /// Entry point to crate resolution.
-    pub fn resolve_crate(&mut self, krate: &Crate) {
+    pub fn resolve_crate(&mut self, krate: &Crate, ignore_bodies: bool) {
         let _prof_timer = self.session.prof.generic_activity("resolve_crate");
 
         ImportResolver { r: self }.finalize_imports();
         self.finalize_macro_resolutions();
 
-        self.late_resolve_crate(krate);
+        self.late_resolve_crate(krate, ignore_bodies);
```
Comment (eddyb) [inline src/librustc_resolve/lib.rs:1450]: This could be an `enum`, I was recently bitten by a ~~radioactive~~ `bool` function input that I thought was the opposite of what it was.

Also, this could be done in a couple other ways:
* detect `rustdoc` from the `Session` (probably not great?)
* set it when creating the `Resolver`, as opposed to customizing it here

Although, if `rustdoc` isn't in control of the creation of the `Resolver` then only the former is a viable alternative.

Comment (jyn514) [reply src/librustc_resolve/lib.rs:1450]: > detect rustdoc from the Session (probably not great?)

This is how it gets set in the first place: https://github.com/rust-lang/rust/pull/73566/files#diff-24c5c945888bb0d041e769bfb852de6cR413. Not sure it makes sense to move that further into `rustc_resolve`, but I can if you think it limits the scope of the hack.

> set it when creating the Resolver, as opposed to customizing it here

I thought resolvers were used for both early and late resolution? I want to only ignore late errors, macros need to resolve properly no matter what.

Comment (jyn514) [reply src/librustc_resolve/lib.rs]: I changed the boolean to an enum. It reuses the existing enum so the docs are a little iffy but the variant names make sense.

**Comment by jyn514** [comment]
Ok, so the current status is that this does not cause ICEs, but it does give errors in more places than `ReplaceBodyWithLoop` did before. In particular it no longer allows having resolution or type errors in the body of an async function ([example](https://crater-reports.s3.amazonaws.com/pr-73566/try%2366dfc4e010913fbed0c4ea91fc2c010004b0f441/gh/ZempTime.dadjoke/log.txt)), because it now considers those as `impl Future` where before it thought they were concrete types.

If anyone has ideas on how to fix that I'm happy to implement them. Otherwise I think this needs a decision from @rust-lang/rustdoc on whether it's ok to merge this despite those additional 50 errors in the wild.

**Comment by GuillaumeGomez** [comment]
It depends what it's breaking. 50 failures on all crates is very low though. But again, it depends on what it's breaking.

**Comment by jyn514** [comment]
I haven't looked at all the breakage, but the ones I've looked at were all errors without a cfg. So previously they could be documented but not compiled, now they can be neither documented nor compiled. This is not the same as std, which had errors because it documents _all_ platforms, which it doesn't do when compiled.

**Comment by GuillaumeGomez** [comment]
You mean it doesn't take `cfg`s into account anymore?

**Comment by jyn514** [comment]
> You mean it doesn't take `cfg`s into account anymore?

No, I mean that of the ones that broke, none of them had a `cfg`. I haven't changed the behavior around `cfg` at all, I'm just saying that the breakage happens to programs that _never_ compile.

**Comment by GuillaumeGomez** [comment]
Oh then it's actually *better*. If rustc doesn't compile it, I guess it's normal for rustdoc to not be able to document it.

**Comment by pnkfelix** [comment]
@GuillaumeGomez am I right in interpreting your feedback as a :+1: on the two items that are awaiting "needs-decision' from T-rustdoc?

**Comment by GuillaumeGomez** [comment]
> now only missing_docs is run and no other lints: #73566 (comment). We need a team decision on whether that's an acceptable tradeoff.

I thought this was fixed. It would be an issue if rustdoc's lints were removed.

> This caused breakage in 50 crates out of a full crater run, all of which (that I looked at) didn't compile when run with rustc directly

From @jyn514's explanations, it was actually strange that rustdoc didn't complain about them before. So it's an improvement in my point of view.

So in short, if `1.` isn't resolved, I'd prefer not to merge until it is fixed.

**Comment by Manishearth** [comment]
> I thought this was fixed. It would be an issue if rustdoc's lints were removed.

Rustdoc's lints are still present, it's non-rustdoc lints that no longer run.

**Comment by GuillaumeGomez** [comment]
Then it's even better! So the two points are actually improvements. Great news. Thanks for the clarification @Manishearth. All good for me then! Just worried about the `rustdoc-ui` failure though:

```
failures:

---- [ui] rustdoc-ui/error-in-impl-trait.rs stdout ----
normalized stderr:
error: could not parse edition




The actual stderr differed from the expected stderr.
```

File: src/librustdoc/core.rs [hunk 8]
```diff
@@ -570,6 +580,73 @@ pub fn run_core(options: RustdocOptions) -> (clean::Crate, RenderInfo, RenderOpt
...
 
+use rustc_hir::def::Res;
+use rustc_hir::{
+    intravisit::{NestedVisitorMap, Visitor},
+    Path,
+};
+use rustc_middle::hir::map::Map;
+
+/*
+thread_local!(static DEFAULT_TYPECK: for<'tcx> fn(rustc_middle::ty::TyCtxt<'tcx>, rustc_span::def_id::LocalDefId) -> &'tcx rustc_middle::ty::TypeckTables<'tcx> = {
```
Comment (GuillaumeGomez) [inline src/librustdoc/core.rs:591]: Maybe remove this code if it's not used anymore?

**Comment by Manishearth** [comment]
@GuillaumeGomez @jyn514  i believe the following is inaccurate:

> "now only missing_docs is run and no other lints: [#73566 (comment)](https://github.com/rust-lang/rust/pull/73566#issuecomment-650213058). We need a team decision on whether that's an acceptable tradeoff."

Out of the _normal rust lints_ only missing_docs is run. Builtin rustdoc lints are still run as of this PR (like the broken intra doc link one), if I understand correctly.

Basically, things like the `unused` lints no longer run. That's acceptable IMO

File: src/test/rustdoc-ui/error-in-impl-trait.rs [hunk 9]
```diff
@@ -0,0 +1,26 @@
+// edition: 2018
```
Comment (Manishearth) [inline src/test/rustdoc-ui/error-in-impl-trait.rs:1]:
```suggestion
// edition:2018
```

**Comment by jyn514** [comment]
> Out of the normal rust lints only missing_docs is run. Builtin rustdoc lints are still run as of this PR (like the broken intra doc link one), if I understand correctly.

Yes, that's correct. Sorry for the confusion.

I have to check whether any of the remaining rustdoc lints are run by rustc. If so, they'll need to be explicitly run the same way `missing_docs` was: https://github.com/rust-lang/rust/blob/master/src/librustc_lint/lib.rs#L305-L311

**Comment by jyn514** [comment]
INVALID_CODEBLOCK is run in rustdoc: https://github.com/rust-lang/rust/blob/b805f2c4dce9d9fb25ea48d6290d60f8546df64f/src/librustdoc/html/markdown.rs#L668
INTRA_DOC_LINK_RESOLUTION_FAILURE I know is in rustdoc.
MISSING_DOC_CODE_EXAMPLES we're running explicitly.
PRIVATE_DOC_TESTS is run in rustdoc: https://github.com/rust-lang/rust/blob/b805f2c4dce9d9fb25ea48d6290d60f8546df64f/src/librustdoc/passes/mod.rs#L353

So we should be good to go on that front. Let me know if there's any other rustdoc lints I'm missing.

**Comment by Manishearth** [comment]
Seems like we're r+ from the tools/rustdoc side (correct me if wrong). @pnkfelix, anything left to do from your side?

**Comment by Manishearth** [comment]
> I have to check whether any of the remaining rustdoc lints are run by rustc. If so, they'll need to be explicitly run the same way missing_docs was: 

All of the lints except missing_docs are only emitted from within rustdoc. missing_docs is special because you kinda want to be warned about it always, and it's easy enough to implement outside of rustdoc (the others require running part of rustdoc)

**Comment by jyn514** [comment]
@Manishearth we're still waiting on https://github.com/rust-lang/rust/pull/74070 so that we don't make `typeck_tables_of` public when it shouldn't be.

File: src/librustdoc/core.rs (hunk 8 above)
Comment (jyn514) [reply src/librustdoc/core.rs:591]: This is waiting on https://github.com/rust-lang/rust/pull/74070 and then it should be uncommented and the current code updated.

Comment (jyn514) [reply src/librustdoc/core.rs:591]: Right now it gives the following error:
```rust
error[E0308]: mismatched types
   --> src/librustdoc/core.rs:594:5
    |
591 | thread_local!(static DEFAULT_TYPECK: for<'tcx> fn(TyCtxt<'tcx>, LocalDefId) -> &rustc_middle::ty::TypeckTables<'tcx> = {
    |                                      ------------------------------------------------------------------------------- expected `for<'tcx> fn(rustc_middle::ty::TyCtxt<'tcx>, rustc_span::def_id::LocalDefId) -> &'tcx rustc_middle::ty::TypeckTables<'tcx>` because of return type
...
594 |     providers.typeck_tables_of
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^ expected concrete lifetime, found bound lifetime parameter 'tcx
```

File: src/librustdoc/lib.rs [hunk 10]
```diff
@@ -94,6 +94,7 @@ pub fn main() {
         32_000_000 // 32MB on other platforms
     };
     rustc_driver::set_sigpipe_handler();
+    rustc_driver::install_ice_hook();
```
Comment (jyn514) [inline src/librustdoc/lib.rs:97]: This will print a query stack on panic. Previously it would only print a backtrace, which made it really hard to figure out what queries were being executed.

**Review by jyn514 — COMMENTED** [review]
I added a short 'How will this affect future changes to rustdoc?' section to the PR description which might be helpful to read through. I also squashed the commits some which hopefully will make this easier to review/figure out when someone wants to know why the changes were made.

**Comment by jyn514** [comment]
Now that https://github.com/rust-lang/rust/pull/74070 has landed, I made `typeck_tables_of` private again.

RE team decisions, recall that we're deciding on https://github.com/rust-lang/rust/pull/73566#issuecomment-655734133:
- @GuillaumeGomez approved the changes in https://github.com/rust-lang/rust/pull/73566#issuecomment-653928184 and https://github.com/rust-lang/rust/pull/73566#issuecomment-655750237
- @Manishearth approved the changes in https://github.com/rust-lang/rust/pull/73566#issuecomment-655750669
- We haven't yet heard from @ollie27 and @kinnison. Not sure what the policy is here, do we need everybody to approve or a majority or what?

RE review: @pnkfelix reviewed a while ago but the implementation has changed a fair bit since then so it wouldn't hurt to re-review. I've also been talking with @eddyb a fair bit privately and he approves of the idea behind the changes (I don't think he's looked closely at the implementation though).

Once that's done I think this will be good to merge :) Shame that https://github.com/rust-lang/rustc-perf/pull/675 didn't land first but maybe I can sneak it in tomorrow while waiting for bors.

**Comment by Manishearth** [comment]
This isn't a major behavior change IMO (it is an architectural change, but it's one that multiple compiler team members are in favor of). I don't think we need whole team approval, but we can wait for it if @GuillaumeGomez feels like we do.

**Comment by Manishearth** [comment]
Yeah, I'd suspect this would take a day to land anyway, we can wait for the perf thing to land if you'd like.

@bors delegate+

You should feel free to `bors r=pnkfelix,Manishearth` when you feel this is ready to land. Wait for @GuillaumeGomez to mention if he wants to wait for all rustdoc team members to approve, though.

**Comment by petrochenkov** [comment]
@jyn514 
Could you assign me when this is ready?
This is as much about resolve as about rustdoc.

**Comment by GuillaumeGomez** [comment]
Like I said it looks good to me. However I'd like at least @ollie27 to check it.

**Comment by petrochenkov** [comment]
Does everybody-loops have any reasonable use beside rustdoc?
Perhaps it can be removed now? (Not necessarily in this PR.)

**Comment by Manishearth** [comment]
@petrochenkov it existed pre rustdoc as a debugging tool, IIRC

File: src/librustc_resolve/late.rs [hunk 11]
```diff
@@ -1843,6 +1898,24 @@ impl<'a, 'b, 'ast> LateResolutionVisitor<'a, 'b, 'ast> {
...
+        if self.should_report_errs() {
+            self.r.report_error(span, resolution_error);
+        }
+    }
+
+    #[inline]
+    fn should_report_errs(&self) -> bool {
+        debug!("should_report_errs(state={:?})", self.ignore_bodies);
+        match self.ignore_bodies {
+            None | Some(IgnoreState::Report) => true,
```
Comment (petrochenkov) [inline src/librustc_resolve/late.rs:1914]: The optional enum setup looks overcomplicated.
`fn should_report_errs` could return `self.sess.opts.actually_rustdoc && self.in_body` where `in_body` is a simple boolean flag.

**Comment by jyn514** [comment]
> Does everybody-loops have any reasonable use beside rustdoc? Perhaps it can be removed now? (Not necessarily in this PR.)

https://github.com/rust-lang/rust/pull/73566/files#r445603609

**Comment by petrochenkov** [comment]
Ok, this is unambiguously a hack, but not a larger hack than everybody-loops, and the end goal itself (ignoring `#[cfg]`s) is fundamentally hacky, so I guess there's not much choice.

File: src/librustc_interface/passes.rs (hunk 5 above)
Comment (petrochenkov) [reply src/librustc_interface/passes.rs:360]: I'm not too convinced by https://github.com/rust-lang/rust/pull/19964.
I'd suggest to open a PR removing it and poll people on whether anybody actually used it for debugging it since 2014.

File: src/librustc_resolve/late.rs (hunk 11 above)
Comment (jyn514) [reply src/librustc_resolve/late.rs:1914]: I guess no one will ever want to use this besides rustdoc, yeah. I'll get rid of the `ignore_bodies` parameter to `Visitor::new`, then it will be even more clear this is a hack.

File: src/librustc_interface/passes.rs (hunk 5 above)
Comment (jyn514) [reply src/librustc_interface/passes.rs:360]: cc @pnkfelix, I think they said they still use it.

File: src/librustdoc/core.rs [hunk 12]
```diff
@@ -570,6 +587,75 @@ pub fn run_core(options: RustdocOptions) -> (clean::Crate, RenderInfo, RenderOpt
...
+                E0433,
+                "failed to resolve: {}",
+                label
+            );
+            err.span_label(path.span, label);
+            err.note("this error was originally ignored because you are running `rustdoc`");
+            err.note("try running again with `rustc` and you may get a more detailed error");
+            err.emit();
+        }
+        // NOTE: this does _not_ visit the path segments
```
Comment (eddyb) [inline src/librustdoc/core.rs:655]: Doesn't this mean that it won't catch `Vec<DoesNotExist>`?

File: src/librustdoc/core.rs [hunk 13]
```diff
@@ -570,6 +587,75 @@ pub fn run_core(options: RustdocOptions) -> (clean::Crate, RenderInfo, RenderOpt
...
+            let mut err = rustc_errors::struct_span_err!(
+                self.session,
+                path.span,
+                E0433,
+                "failed to resolve: {}",
+                label
+            );
+            err.span_label(path.span, label);
+            err.note("this error was originally ignored because you are running `rustdoc`");
+            err.note("try running again with `rustc` and you may get a more detailed error");
```
Comment (eddyb) [inline src/librustdoc/core.rs:652]: I wonder if we could easily detect this is `cargo doc` and suggest `cargo check`. Or we can just say "`rustc` or `cargo check`"?

File: src/librustdoc/core.rs [hunk 14]
```diff
@@ -570,6 +587,75 @@ pub fn run_core(options: RustdocOptions) -> (clean::Crate, RenderInfo, RenderOpt
...
+    }
+
+    fn visit_path(&mut self, path: &'v Path<'v>, _id: HirId) {
+        log::debug!("visiting path {:?}", path);
+        if path.res == Res::Err {
+            // We have less context here than in rustc_resolve,
+            // so we can only emit the name and span.
+            // However we can give a hint that rustc_resolve will have more info.
+            // NOTE: this is a very rare case (only 4 out of several hundred thousand crates in a crater run)
+            // NOTE: so it's ok for it to be slow
```
Comment (eddyb) [inline src/librustdoc/core.rs:634]: Speed doesn't matter if you're producing errors, though, or does this refer to the visitor? The visitor should be pretty cheap.

File: src/librustdoc/core.rs [hunk 15]
```diff
@@ -570,6 +587,75 @@ pub fn run_core(options: RustdocOptions) -> (clean::Crate, RenderInfo, RenderOpt
...
+    providers.typeck_tables_of
+});
+
+/// Due to https://github.com/rust-lang/rust/pull/73566,
+/// the name resolution pass may find errors that are never emitted.
+/// If typeck is called after this happens, then we'll get an ICE:
+/// 'Res::Error found but not reported'. To avoid this, emit the errors now.
+struct EmitIgnoredResolutionErrors<'a, 'hir> {
+    session: &'a Session,
+    hir_map: Map<'hir>,
```
Comment (eddyb) [inline src/librustdoc/core.rs:609]: Simpler to just keep a `TyCtxt` in here.

File: src/librustdoc/core.rs [hunk 16]
```diff
@@ -570,6 +587,75 @@ pub fn run_core(options: RustdocOptions) -> (clean::Crate, RenderInfo, RenderOpt
...
+    type Map = Map<'hir>;
+
+    fn nested_visit_map(&mut self) -> NestedVisitorMap<Self::Map> {
+        // We need to recurse into nested closures,
+        // since those will fallback to the parent for type checking.
+        NestedVisitorMap::OnlyBodies(self.hir_map)
+    }
+
+    fn visit_path(&mut self, path: &'v Path<'v>, _id: HirId) {
+        log::debug!("visiting path {:?}", path);
```
Comment (eddyb) [inline src/librustdoc/core.rs:628]: I believe it's normal to use `debug!` across the codebase, unprefixed with `log::`.

File: src/librustdoc/core.rs [hunk 17]
```diff
@@ -570,6 +587,75 @@ pub fn run_core(options: RustdocOptions) -> (clean::Crate, RenderInfo, RenderOpt
...
+    intravisit::{NestedVisitorMap, Visitor},
+    Path,
+};
+use rustc_middle::hir::map::Map;
+
+thread_local!(static DEFAULT_TYPECK: for<'tcx> fn(rustc_middle::ty::TyCtxt<'tcx>, rustc_span::def_id::LocalDefId) -> &'tcx rustc_middle::ty::TypeckTables<'tcx> = {
+    let mut providers = rustc_middle::ty::query::Providers::default();
+    rustc_typeck::provide(&mut providers);
+    providers.typeck_tables_of
+});
```
Comment (eddyb) [inline src/librustdoc/core.rs:601]: Ideally don't refer to crate names if you can avoid it - `ty` should be imported directly, and so should `TyCtxt` and `LocalDefId`, I'm a bit surprised you're not getting internal lints.

File: src/librustdoc/core.rs [hunk 18]
```diff
@@ -570,6 +587,75 @@ pub fn run_core(options: RustdocOptions) -> (clean::Crate, RenderInfo, RenderOpt
     })
 }
 
+use rustc_hir::def::Res;
+use rustc_hir::{
+    intravisit::{NestedVisitorMap, Visitor},
+    Path,
+};
+use rustc_middle::hir::map::Map;
```
Comment (eddyb) [inline src/librustdoc/core.rs:595]: Imports should be at the top of the file.

File: src/librustdoc/core.rs (hunk 14 above)
Comment (jyn514) [reply src/librustdoc/core.rs:634]: It was referring to the `ident.as_str()`, the rustdocs said it was slow. Since this is only for errors I can just remove the comment altogether.

File: src/librustdoc/core.rs [hunk 19]
```diff
@@ -570,6 +587,75 @@ pub fn run_core(options: RustdocOptions) -> (clean::Crate, RenderInfo, RenderOpt
...
+                    .collect::<Vec<_>>()
+                    .join("::")
+            );
+            let mut err = rustc_errors::struct_span_err!(
+                self.session,
+                path.span,
+                E0433,
+                "failed to resolve: {}",
+                label
+            );
```
Comment (eddyb) [inline src/librustdoc/core.rs:649]: I wonder if you could actually check the per-segment resolution to figure out which segment failed, but I'm not sure we actually fill those in, so they might be `Res::Err` even when resolution succeeded.

File: src/librustdoc/core.rs (hunk 12 above)
Comment (jyn514) [reply src/librustdoc/core.rs:655]: Ahhh, good catch. That gave the delay_span_bug ICE. I'll fix it and add a test case.

```
error: internal compiler error: TyKind::Error constructed but no error reported
  |
  = note: delayed at /home/joshua/src/rust/src/librustc_session/session.rs:436:9
```

File: src/librustdoc/core.rs (hunk 19 above)
Comment (jyn514) [reply src/librustdoc/core.rs:649]: I'm not sure it makes sense to try too hard with error reporting here, you'll be able to get a much better error message just by running `cargo check`. Anything we put here is just trying to paper over the cracks.

File: src/librustdoc/core.rs (hunk 13 above)
Comment (jyn514) [reply src/librustdoc/core.rs]: I did the second, suggest "`rustc` or `cargo check`". I don't want to get too fancy since cargo might invoked by a shell script or something.

**Comment by jyn514** [comment]
I ran this again on the ICEs from crater.
- demo-bankid gives E0433 from `EmitIgnoredResolutionErrors`
- sixarm_rust_actix_echo gives E0433 from `EmitIgnoredResolutionErrors`
- mdfmt is fixed, no compile errors at all. Not sure what changed there.
- rust_book gives E0433 from `EmitIgnoredResolutionErrors`
- The ICE from `pyrite` went away when I rebased over master.

**Comment by jyn514** [comment]
Oh wait I take it back, the ICE from pyrite is still there. Does anyone understand this ICE/how it's related to this PR?

```
error: internal compiler error[E0391]: cycle detected when computing `Sized` constraints for `BinaryExpression`
  --> src/lib.rs:65:1
   |
65 | struct BinaryExpression {
   | ^^^^^^^^^^^^^^^^^^^^^^^
   |
note: ...which requires computing `Sized` constraints for `Expression`...
  --> src/lib.rs:72:1
   |
72 | enum Expression {
   | ^^^^^^^^^^^^^^^
   = note: ...which again requires computing `Sized` constraints for `BinaryExpression`, completing the cycle
   = note: cycle used when evaluating trait selection obligation `BinaryExpression: std::convert::From<BinaryExpression>`

error: internal compiler error: TyKind::Error constructed but no error reported
  |
  = note: delayed at /home/joshua/src/rust/src/librustc_session/session.rs:436:9

thread 'rustc' panicked at 'no errors encountered even though `delay_span_bug` issued', src/librustc_errors/lib.rs:367:17
```

For reference, here are the errors when compiled with nightly, none of which have resolution errors:

<details><summary>Nightly errors</summary>

```
(-bash@build-server) ~/.../rustdoc-ices/Pyrite ▶️ CARGO_TARGET_DIR=target cargo +nightly doc
 Documenting pyrite v0.1.0 (/home/joshua/src/rustdoc-ices/Pyrite)
error[E0072]: recursive type `BinaryExpression` has infinite size
  --> src/lib.rs:65:1
   |
65 | struct BinaryExpression {
   | ^^^^^^^^^^^^^^^^^^^^^^^ recursive type has infinite size
66 |     left: Expression,
   |           ---------- recursive without indirection
67 |     op: BinaryOperator,
68 |     right: Expression,
   |            ---------- recursive without indirection
   |
help: insert some indirection (e.g., a `Box`, `Rc`, or `&`) to make `BinaryExpression` representable
   |
66 |     left: Box<Expression>,
67 |     op: BinaryOperator,
68 |     right: Box<Expression>,
   |

error[E0072]: recursive type `Expression` has infinite size
  --> src/lib.rs:72:1
   |
72 | enum Expression {
   | ^^^^^^^^^^^^^^^ recursive type has infinite size
73 |     Parenthesis(Box<Parenthesis>),
74 |     BinaryExpression(BinaryExpression),
   |                      ---------------- recursive without indirection
   |
help: insert some indirection (e.g., a `Box`, `Rc`, or `&`) to make `Expression` representable
   |
74 |     BinaryExpression(Box<BinaryExpression>),
   |                      ^^^^                ^

error[E0391]: cycle detected when computing drop-check constraints for `BinaryExpression`
  --> src/lib.rs:65:1
   |
65 | struct BinaryExpression {
   | ^^^^^^^^^^^^^^^^^^^^^^^
   |
note: ...which requires computing drop-check constraints for `Expression`...
  --> src/lib.rs:72:1
   |
72 | enum Expression {
   | ^^^^^^^^^^^^^^^
   = note: ...which again requires computing drop-check constraints for `BinaryExpression`, completing the cycle
   = note: cycle used when computing dropck types for `Canonical { max_universe: U0, variables: [CanonicalVarInfo { kind: Region(U0) }], value: ParamEnvAnd { param_env: ParamEnv { caller_bounds: [], reveal: UserFacing, def_id: None }, value: std::result::Result<(BinaryExpression, &str), ParseError> } }`

error: aborting due to 3 previous errors
```

</details>

**Comment by jyn514** [comment]
Minimized:
```rust
enum E {
    V(E),
}
error: internal compiler error[E0391]: cycle detected when computing `Sized` constraints for `E`
 --> src/lib.rs:1:1
  |
1 | enum E {
  | ^^^^^^
  |
  = note: ...which again requires computing `Sized` constraints for `E`, completing the cycle
  = note: cycle used when evaluating trait selection obligation `E: std::convert::From<E>`

error: internal compiler error: TyKind::Error constructed but no error reported
  |
  = note: delayed at /home/joshua/src/rust/src/librustc_session/session.rs:436:9

thread 'rustc' panicked at 'no errors encountered even though `delay_span_bug` issued', src/librustc_errors/lib.rs:367:17
```

**Comment by jyn514** [comment]
Ok, after the latest commit all the ICEs from crater are fixed.

File: src/librustc_resolve/late.rs [hunk 20]
```diff
@@ -497,13 +504,18 @@ impl<'a, 'ast> Visitor<'ast> for LateResolutionVisitor<'a, '_, 'ast> {
 
                 visit::walk_fn_ret_ty(this, &declaration.output);
 
+                let previous_state = this.in_func_body;
+                // Ignore errors in function bodies if this is rustdoc
+                // Be sure not to set this until the function signature has been resolved.
+                this.in_func_body = true;
```
Comment (petrochenkov) [inline src/librustc_resolve/late.rs:510]:
```suggestion
                let previous_state = mem::replace(&mut this.in_func_body, true);
```

File: src/librustc_resolve/late.rs [hunk 21]
```diff
@@ -1157,6 +1175,9 @@ impl<'a, 'b, 'ast> LateResolutionVisitor<'a, 'b, 'ast> {
         impl_items: &'ast [P<AssocItem>],
     ) {
         debug!("resolve_implementation");
+        let old_ignore = self.in_func_body;
+        // Never ignore errors in trait implementations.
+        self.in_func_body = false;
```
Comment (petrochenkov) [inline src/librustc_resolve/late.rs:1180]:
```suggestion
        let old_ignore = mem::replace(&mut this.in_func_body, false);
```
Although I'm not sure why this special case exists.

**Review by petrochenkov — APPROVED** [review]

File: src/librustc_resolve/late.rs (hunk 21 above)
Comment (jyn514) [reply src/librustc_resolve/late.rs]: > I'm not sure why this special case exists.

Trait implementations are publicly visible outside the current scope. See https://github.com/rust-lang/rust/pull/73566/files#diff-f2b1241f9e58664507f0cc3a865bfb87R24 for an example - rustdoc can't document that trait impl unless name resolution succeeded.

File: src/librustdoc/core.rs [hunk 22]
```diff
@@ -359,6 +364,9 @@ pub fn run_core(options: RustdocOptions) -> (clean::Crate, RenderInfo, RenderOpt
         ..Options::default()
     };
 
+    lazy_static! {
+        static ref EMPTY_MAP: FxHashSet<LocalDefId> = FxHashSet::default();
```
Comment (eddyb) [inline src/librustdoc/core.rs:368]: `EMPTY_SET` would be more accurate. Also I suspect you can move this into the closure that returns it.

File: src/librustdoc/core.rs [hunk 23]
```diff
@@ -570,6 +607,68 @@ pub fn run_core(options: RustdocOptions) -> (clean::Crate, RenderInfo, RenderOpt
     })
 }
 
+thread_local!(static DEFAULT_TYPECK: for<'tcx> fn(TyCtxt<'tcx>, LocalDefId) -> &'tcx ty::TypeckTables<'tcx> = {
+    let mut providers = ty::query::Providers::default();
+    rustc_typeck::provide(&mut providers);
+    providers.typeck_tables_of
+});
```
Comment (eddyb) [inline src/librustdoc/core.rs:614]: This would probably fit better in `local_providers.typeck_tables_of = move |tcx, def_id| {`.

Unless you want to create a `fn hooked_typeck_tables_of` function or similar, instead of using a closure for it.

File: src/librustdoc/core.rs [hunk 24]
```diff
@@ -372,7 +377,33 @@ pub fn run_core(options: RustdocOptions) -> (clean::Crate, RenderInfo, RenderOpt
...
         lint_caps,
         register_lints: None,
-        override_queries: None,
+        override_queries: Some(|_sess, local_providers, external_providers| {
+            lazy_static! {
+                static ref EMPTY_SET: FxHashSet<LocalDefId> = FxHashSet::default();
+            }
+            // Most lints will require typechecking, so just don't run them.
+            local_providers.lint_mod = |_, _| {};
+            external_providers.lint_mod = |_, _| {};
```
Comment (eddyb) [inline src/librustdoc/core.rs:386]: This isn't necessary and you can just rename `local_providers` to `providers`.

File: src/librustdoc/core.rs [hunk 25]
```diff
@@ -372,7 +377,33 @@ pub fn run_core(options: RustdocOptions) -> (clean::Crate, RenderInfo, RenderOpt
         crate_name,
         lint_caps,
         register_lints: None,
-        override_queries: None,
+        override_queries: Some(|_sess, local_providers, external_providers| {
+            lazy_static! {
+                static ref EMPTY_SET: FxHashSet<LocalDefId> = FxHashSet::default();
+            }
```
Comment (eddyb) [inline src/librustdoc/core.rs:383]: To be clear, I meant the closure that does `&EMPTY_SET`.

File: src/librustdoc/core.rs [hunk 26]
```diff
@@ -372,7 +377,33 @@ pub fn run_core(options: RustdocOptions) -> (clean::Crate, RenderInfo, RenderOpt
...
+            // Most lints will require typechecking, so just don't run them.
+            local_providers.lint_mod = |_, _| {};
+            external_providers.lint_mod = |_, _| {};
+            local_providers.typeck_item_bodies = |_, _| {};
```
Comment (eddyb) [inline src/librustdoc/core.rs:387]: This needs a comment that it prevents `rustc_typeck::check_crate` from calling `typeck_tables_of` on all bodies.

File: src/librustdoc/core.rs [hunk 27]
```diff
@@ -416,10 +447,16 @@ pub fn run_core(options: RustdocOptions) -> (clean::Crate, RenderInfo, RenderOpt
...
             global_ctxt.enter(|tcx| {
-                tcx.analysis(LOCAL_CRATE).ok();
-
-                // Abort if there were any errors so far
-                sess.abort_if_errors();
+                // Some queries require that they only run on valid types:
+                // https://github.com/rust-lang/rust/pull/73566#issuecomment-656954425
+                // Therefore typecheck this crate before running lints.
+                // NOTE: this does not typeck item bodies or run the default rustc lints
+                // (see `override_queries` in the `config`)
```
Comment (eddyb) [inline src/librustdoc/core.rs:454]: `rustc_typeck::check_crate` would not run lints, so that part isn't relevant. Although you could say that you don't call `tcx.analysis()` in order to not run lints and other checks.

File: src/librustdoc/core.rs [hunk 28]
```diff
@@ -416,10 +447,16 @@ pub fn run_core(options: RustdocOptions) -> (clean::Crate, RenderInfo, RenderOpt
             let mut global_ctxt = abort_on_err(queries.global_ctxt(), sess).take();
 
             global_ctxt.enter(|tcx| {
-                tcx.analysis(LOCAL_CRATE).ok();
-
-                // Abort if there were any errors so far
-                sess.abort_if_errors();
+                // Some queries require that they only run on valid types:
+                // https://github.com/rust-lang/rust/pull/73566#issuecomment-656954425
+                // Therefore typecheck this crate before running lints.
```
Comment (eddyb) [inline src/librustdoc/core.rs:452]: Not sure if this phrasing is ideal. I'd say that "certain queries (in)directly used by `rustdoc` assume some checks were performed elsewhere, so we do as much as we can without type-checking bodies".

Comment (jyn514) [reply src/librustdoc/core.rs]: I cleaned up the wording a little, how does it look now?

File: src/librustc_resolve/late.rs (hunk 21 above)
Comment (eddyb) [reply src/librustc_resolve/late.rs]: @jyn514 I would expect this to set `in_func_body` to `false` for the duration of `visit_item` (and reset it back to the previous value afterwards).

**Comment by eddyb** [comment]
Blocked on #74347.

**Comment by jyn514** [comment]
Well, I don't know if it should be a blocker. That PR makes the memory usage slightly less but it doesn't have any features this needs.

File: src/librustc_resolve/late.rs (hunk 21 above)
Comment (jyn514) [reply src/librustc_resolve/late.rs]: Isn't that the current behavior? Or do you mean it should happen for _every_ item, not just trait implementations?

**Comment by Manishearth** [comment]
Yeah i'd rather land this as soon as possible so we can land the rest of the stack

**Comment by eddyb** [comment]
@Manishearth I'm fine with landing this by rebasing it on top of #74347, once the perf run there finishes.

**Comment by eddyb** [comment]
@rust-timer queue

**Comment by Mark-Simulacrum** [comment]
@rust-timer build 97f1e6ff90848792722f9636e4a11368bb3b14c2

**Comment by Manishearth** [comment]
Ah, much faster on documenting some things that contain a lot of things within bodies, it seems

**Comment by jyn514** [comment]
@ollie27 do you mind looking at this to see if the tradeoffs are acceptable? https://github.com/rust-lang/rust/pull/73566#issuecomment-655734133

1. This now only runs rustdoc lints (+ missing_docs), not rustc lints. So it's no longer to opt-in to e.g. `dead_code` with CLI arguments (it was already off by default before).
2. This breaks 50 crates out of a full crater run. However, all of the crates that broke also could not be compiled normally with rustc (no use of `cfg()` that I saw).

@rustbot modify labels: -S-blocked +S-waiting-on-team

**Comment by ollie27** [comment]
> @ollie27 do you mind looking at this to see if the tradeoffs are acceptable? [#73566 (comment)](https://github.com/rust-lang/rust/pull/73566#issuecomment-655734133)

Yeah that all looks good to me 👍.

**Comment by Manishearth** [comment]
@bors p=1 rollup=maybe

we understand the perf impact, we don't need to rollup-never it anymore IMO

**Comment by mati865** [comment]
@Manishearth including PRs like this one rollup could mask regressions/improvements from other PRs included in the rollup.

Let's say there are 2 PRs: 1 is clear 20% improvement, the other should not affect performance.
Perf result for the rollup says 12% improvement but really PR 1 improved performance by 20% and then PR 2 reduced it by 10%. That way everyone who tracks performance has missed accidental 10% regression.

**Comment by Manishearth** [comment]
@bors p=5

gonna see if we get the same error

File: src/librustc_interface/passes.rs (hunk 5 above)
Comment (pnkfelix) [reply src/librustc_interface/passes.rs:360]: I wrote a blog post in late 2019 that demonstrated use of `everybody_loops`. So yes, I do still use it.

http://blog.pnkfx.org/blog/2019/11/18/rust-bug-minimization-patterns/#L..loopification.....via.pretty-printer

**Comment by nnethercote** [comment]
This was overall a [perf win](https://perf.rust-lang.org/compare.html?start=6ee1b62c811a6eb68d6db6dfb91f66a49956749b&end=5c9e5df3a097e094641f16dab501ab1c4da10e9f&stat=instructions:u) for rustdoc builds, as expected. Some wins, some losses, but the wins were more frequent and larger. Nice work!

@jyn514: this landed in a rollup, which makes performance triage more difficult. Fortunately, in this case it was easy to work out the responsible PR. But in the future, for PRs that you know have a perf effect, please mark them with "rollup=never".

**Comment by nnethercote** [comment]
> we understand the perf impact, we don't need to rollup-never it anymore IMO

I'm going to second what @mati865 said, because it's important: we absolutely should rollup-never every PR that is known to have a perf effect, to avoid those effects masking other unintended perf effects.

**Comment by Manishearth** [comment]
Yep, I was under the incorrect impression that we didn't need rollup=never for PRs where we understand the perf impact already

**Comment by yoshuawuyts** [comment]
We suspect this patch may have broken the docs build for `async-std`. See: https://github.com/async-rs/async-std/pull/845

cc/ @dignifiedquire

**Comment by jyn514** [comment]
This is one of the known drawbacks of this PR - it no longer allows type errors in `async fn f() -> T`.

I don't know how crater didn't pick this up :(

**Comment by jyn514** [comment]
There's not a good way to fix this. We could revert, but then we lose the fixes to intra-doc links and they'd be permanently unstable again.

Maybe we could have a reachability pass for rustdoc that's separate from the one for rustc? https://github.com/rust-lang/rust/pull/73566#issuecomment-653689128 That's going to require a lot of work though, it's not a quick fix. And I don't know if it would actually work.

**Comment by Nemo157** [comment]
This was not picked up by crater as it only fails with the `docs` feature enabled on docs.rs (and in the `async-std` CI). It may be worth having crater's rustdoc mode look at the docs.rs metadata in order to more accurately test what will happen with documentation built there?

**Comment by GuillaumeGomez** [comment]
I'm more in favor of writing a specific pass rather than reverting this, too much benefits came from it and we're getting so close to have the intra-doc links stable! (I'm really excited about this feature!)
