### PR TITLE
Fix the bevy implied bounds hack for the next solver

### LINKED ISSUE #236: `bevy_ecs` implied bounds hack ICE
- tests/ui/implied-bounds/bevy_world_query.rs

with the new solver `fn compute_implied_outlives_bounds_inner` happens inside of a `probe` instead of a separate context. This causes `take_registered_region_obligations` to ICE.

### PR DESCRIPTION
**Pull request by jdonszelmann**
The diff is trivial, of course, and basically what you already suggested. Mostly dug around a bunch to learn. I hope this is roughly what you had in mind.

Fixes https://github.com/rust-lang/trait-system-refactor-initiative/issues/236.

r? @lcnr

### CODE REVIEW

File: compiler/rustc_trait_selection/src/traits/query/type_op/implied_outlives_bounds.rs [hunk 1]
```diff
@@ -55,6 +55,12 @@ pub fn compute_implied_outlives_bounds_inner<'tcx>(
     span: Span,
     disable_implied_bounds_hack: bool,
 ) -> Result<Vec<OutlivesBound<'tcx>>, NoSolution> {
+    // inside mir borrowck, each computation starts with an empty list
```
Comment (lcnr) [inline compiler/rustc_trait_selection/src/traits/query/type_op/implied_outlives_bounds.rs]:
```suggestion
    // Inside mir borrowck, each computation starts with an empty list.
```

File: tests/ui/implied-bounds/bevy_world_query.rs [hunk 2]
```diff
@@ -1,7 +1,9 @@
+//@check-pass
+//@revisions: current next
+//@ignore-compare-mode-next-solver (explicit revisions)
+//@[next] compile-flags: -Znext-solver
```
Comment (lcnr) [inline tests/ui/implied-bounds/bevy_world_query.rs]:
```suggestion
//@ check-pass
//@ revisions: current next
//@ ignore-compare-mode-next-solver (explicit revisions)
//@[next] compile-flags: -Znext-solver
```

**Review by lcnr — COMMENTED** [review]
r=me after nits

*[View changes since this review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/rust/147184/a2db9280539229a3b8a084a09886670a57bc7e9c..881a03501792214cf7765d0309bad85a21fee4dc)*

File: compiler/rustc_trait_selection/src/traits/query/type_op/implied_outlives_bounds.rs [hunk 3]
```diff
@@ -55,6 +55,12 @@ pub fn compute_implied_outlives_bounds_inner<'tcx>(
     span: Span,
     disable_implied_bounds_hack: bool,
 ) -> Result<Vec<OutlivesBound<'tcx>>, NoSolution> {
+    // Inside mir borrowck, each computation starts with an empty list
```
Comment (lcnr) [inline compiler/rustc_trait_selection/src/traits/query/type_op/implied_outlives_bounds.rs]:
```suggestion
    // Inside mir borrowck, each computation starts with an empty list.
```
You forgot the `.` :<

Comment (jdonszelmann) [reply compiler/rustc_trait_selection/src/traits/query/type_op/implied_outlives_bounds.rs]: Sigh, yea you're right thanks :)
