### PR TITLE
Skip suggestions pointing to macro def for assert_eq

### LINKED ISSUE #146204: Fix suggestion on assert! points into the macros definition
### Code

```Rust
fn main() {
    let buf = [0_u8; 4];
    assert_ne!(buf, b"----");
}
```

### Current output

```Shell
error[E0277]: can't compare `[u8; 4]` with `&[u8; 4]`
 --> src/main.rs:3:5
  |
3 |     assert_ne!(buf, b"----");
  |     ^^^^^^^^^^^^^^^^^^^^^^^^ no implementation for `[u8; 4] == &[u8; 4]`
  |
  = help: the trait `PartialEq<&[u8; 4]>` is not implemented for `[u8; 4]`
  = note: this error originates in the macro `assert_ne` (in Nightly builds, run with -Z macro-backtrace for more info)
help: consider dereferencing here
 --> /playground/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/macros/mod.rs:102:33
  |
10|                 if *left_val == **right_val {
  |                                 +
```

### Desired output

```Shell
error[E0277]: can't compare `[u8; 4]` with `&[u8; 4]`
 --> src/main.rs:3:5
  |
3 |     assert_ne!(buf, b"----");
  |     ^^^^^^^^^^^^^^^^^^^^^^^^ no implementation for `[u8; 4] == &[u8; 4]`
  |
  = help: the trait `PartialEq<&[u8; 4]>` is not implemented for `[u8; 4]`
  = note: this error originates in the macro `assert_ne` (in Nightly builds, run with -Z macro-backtrace for more info)
help: consider borrowing here
 --> src/main.rs:3:16
  |
 3|      assert_ne!(&buf, b"----");
  |                 +
```

### Rationale and extra context

The suggestion of fix should not point into internals of standard library.

### Other cases

```Rust

```

### Rust Version

```Shell
rustc 1.90.0-nightly (430d6eddf 2025-07-25)
binary: rustc
commit-hash: 430d6eddfc6a455ca4a0137c0822a982cccd3b2b
commit-date: 2025-07-25
host: x86_64-unknown-linux-gnu
release: 1.90.0-nightly
LLVM version: 20.1.8


Also reproduces on Playground on stable 1.89.0, on beta 1.90.0-beta.7, on nightly 1.91.0-nightly (2025-09-03 a1208bf765ba783ee4eb).
```

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by chenyukang**
Fixes rust-lang/rust#146204

It's better to suggest: 
```console
help: consider borrowing here
 --> src/main.rs:3:16
  |
 3|      assert_ne!(&buf, b"----");
  |                 +
```
but i don't want to give a too heuristic but not general enough fix, let suppress them.

### CODE REVIEW

File: compiler/rustc_trait_selection/src/error_reporting/traits/suggestions.rs [hunk 1]
```diff
@@ -547,6 +547,9 @@ impl<'a, 'tcx> TypeErrCtxt<'a, 'tcx> {
             {
                 let derefs = "*".repeat(steps);
                 let msg = "consider dereferencing here";
+                if !span.can_be_used_for_suggestions() {
```
Comment (JohnTitor) [inline compiler/rustc_trait_selection/src/error_reporting/traits/suggestions.rs]: I guess you can use `in_external_macro()`, suggestions on local macro should be still valid.

Comment (chenyukang) [reply compiler/rustc_trait_selection/src/error_reporting/traits/suggestions.rs]: yes, you are right. I added a local macro in test.

**Review by JohnTitor — APPROVED** [review]
Thanks a lot!
@bors r+ rollup

*[View changes since this review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/rust/154551/cf7da0b7277cad05b79f91b60c290aa08a17a6f0..6518de37d450f35e18fc49502ea6183fda065714)*
