### PR TITLE
Use fulfillment in method probe, not evaluation

### LINKED ISSUE #121643: Trait methods can't be found by method resolution if the `self` type involves projections
I tried this code:

```rust
pub type Id<T> = <T as IdTrait>::T;

pub trait IdTrait {
    type T: ?Sized;
}

impl<T: ?Sized> IdTrait for T {
    type T = T;
}

#[derive(Copy, Clone)]
struct Foo;
impl Foo {
    fn method(self: Id<Self>) {
        println!("hi!");
    }
}

trait FooTrait {
    fn method2(self: Id<Self>);
}
impl FooTrait for Foo {
    fn method2(self) { // or `: Id<Self>`, makes no difference here
        println!("hi!");
    }
}

pub fn main() {
    let foo = Foo;
    foo.method(); // works
    foo.method2(); // doesn't work
    Foo::method2(foo); // works
}
```
([playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=12f61030ea329de24f034279d33a93bf))

I expected to see this happen: Code compiles successfully

Instead, this happened:
```
error[E0599]: no method named `method2` found for struct `Foo` in the current scope
  --> <source>:31:9
   |
12 | struct Foo;
   | ---------- method `method2` not found for this struct
...
20 |     fn method2(self: Id<Self>);
   |                      -------- the method might not be found because of this arbitrary self type
...
31 |     foo.method2(); // doesn't work
   |         ^^^^^^^
   |
help: there is a method `method` with a similar name
   |
31 |     foo.method(); // doesn't work
   |         ~~~~~~

error: aborting due to 1 previous error

For more information about this error, try `rustc --explain E0599`.
Compiler returned: 1
```

This [is *technically*](https://rust.godbolt.org/z/de3os118G) an old regression in `1.22`, the code compiled fine up to Rust `1.21`.

### PR DESCRIPTION
**Pull request by compiler-errors**
This PR reworks method probing to use fulfillment instead of a `for`-loop of `evaluate_predicate` calls, and moves normalization from method candidate assembly into the `consider_probe`, where it's applied to *all* candidates. This last part coincidentally fixes https://github.com/rust-lang/rust/issues/121643#issuecomment-1975371248.

Regarding *why* this large rewrite is done: In general, it's an anti-pattern to do `for o in obligations { evaluate(o); }` because it's not compatible with the way that the new solver emits alias-relate obligations which constrain variables that may show up in other predicates.

r? lcnr

### CODE REVIEW

File: compiler/rustc_trait_selection/src/traits/engine.rs [hunk 1]
```diff
@@ -129,6 +129,19 @@ impl<'a, 'tcx> ObligationCtxt<'a, 'tcx> {
             .map(|infer_ok| self.register_infer_ok_obligations(infer_ok))
     }
 
+    pub fn eq_no_opaques<T: ToTrace<'tcx>>(
```
Comment (compiler-errors) [inline compiler/rustc_trait_selection/src/traits/engine.rs:132]: It's detrimental to use `eq(DefineOpaqueTypes::Yes, ..)` during method probe because it breaks some TAIT tests (and bootstrap!)

Could fix those in the compiler I guess and change the callsites back to `eq` if we're okay w/ it though

File: compiler/rustc_hir_typeck/src/method/probe.rs [hunk 2]
```diff
@@ -1545,118 +1401,79 @@ impl<'a, 'tcx> ProbeContext<'a, 'tcx> {
...
+
+                    let trait_ref = self.instantiate_binder_with_fresh_vars(
+                        self.span,
+                        infer::FnCall,
+                        poly_trait_ref,
+                    );
+                    (xform_self_ty, xform_ret_ty) =
+                        self.xform_self_ty(probe.item, trait_ref.self_ty(), trait_ref.args);
+                    xform_self_ty = ocx.normalize(cause, self.param_env, xform_self_ty);
+                    match ocx.eq_no_opaques(cause, self.param_env, xform_self_ty, self_ty) {
```
Comment (lcnr) [inline compiler/rustc_hir_typeck/src/method/probe.rs:1426]: please change this to instead use `at` and `ocx.register_infer_ok_obligations`. I do not want `fn eq_no_opaques` on the `ObligationCtxt`. Imo using it is always *wrong*.

I do accept that changing the behavior in this PR is undesirable given that it's already very much non-trivial, but I would prefer to make this slightly worse to read for the sake of keeping the `ObligationCtxt` API minimal.

File: compiler/rustc_hir_typeck/src/method/probe.rs [hunk 3]
```diff
@@ -1668,38 +1485,34 @@ impl<'a, 'tcx> ProbeContext<'a, 'tcx> {
...
+                        Some(error.root_obligation.predicate)
+                            .filter(|predicate| *predicate != error.obligation.predicate),
+                        Some(error.root_obligation.cause),
+                    ));
                 }
             }
 
+            if let Err(_) = self.leak_check(outer_universe, Some(snapshot)) {
+                result = ProbeResult::NoMatch;
+            }
```
Comment (lcnr) [inline compiler/rustc_hir_typeck/src/method/probe.rs:1514]: is that one new?

**Comment by compiler-errors** [comment]
@craterbot check

**Comment by compiler-errors** [comment]
@craterbot check crates=https://crater-reports.s3.amazonaws.com/pr-122317/retry-regressed-list.txt

**Comment by compiler-errors** [comment]
@craterbot edit p=1

**Comment by compiler-errors** [comment]
@craterbot p=1

**Comment by compiler-errors** [comment]
Figured out the problem with `wrend@0.3.6` -- we originally used `sup` instead of `eq` to equate the self types. Changed it back to use `sup` and added a test.

This should be ready tbh.

File: compiler/rustc_hir_typeck/src/method/probe.rs (hunk 3 above)
Comment (lcnr) [reply compiler/rustc_hir_typeck/src/method/probe.rs:1553]: talked about why it is needed, still needs to get added as a comment however. please link to a test which depends on it

File: compiler/rustc_hir_typeck/src/method/probe.rs [hunk 4]
```diff
@@ -1884,40 +1742,7 @@ impl<'a, 'tcx> ProbeContext<'a, 'tcx> {
...
-    /// Gets the type of an impl and generate generic parameters with inference vars.
-    fn impl_ty_and_args(
-        &self,
-        impl_def_id: DefId,
-    ) -> (ty::EarlyBinder<Ty<'tcx>>, GenericArgsRef<'tcx>) {
-        (self.tcx.type_of(impl_def_id), self.fresh_args_for_item(self.span, impl_def_id))
-    }
-
-    /// Replaces late-bound-regions bound by `value` with `'static` using
-    /// `ty::instantiate_bound_regions_with_erased`.
```
Comment (lcnr) [inline compiler/rustc_hir_typeck/src/method/probe.rs:1899]: this comment sure was questionable 😁

**Review by lcnr — COMMENTED** [review]
impl r=me, I would expect that to enable new code to compile if there are multiple impl candidates which are only disambiguated if inference flows from one nested goal to another.

I'd like to get a test for that and then FCP merge this

**Comment by lcnr** [comment]
This PR changes method probing to use a "fulfillment loop" for nested goals of candidates. We currently simply check whether evaluating any nested goal fails. By using a fulfillment loop we apply the constraints from nested goals until we reach a fixpoint which causes method selection to be more powerful:
```rust

#[derive(Default)]
struct W<A, B>(A, B);

trait Constrain {
    type Output;
}
impl Constrain for i32 {
    type Output = u32;
}

trait Impossible {}

impl<A, B> W<A, B> where A: Constrain<Output = B>, B: Impossible {
    fn method(&self) {}
}

impl W<i32, u32> {
    fn method(&self) {}
}

fn main() {
    let w: W<i32, _> = W::default();
    // Currently ambiguous because both `i32: Constrain<Output = ?0>`
    // and `?0: Impossible` don't result in an error by themselves.
    //
    // With this PR we successfully discard that generic impl because the
    // constraints from the first bound are now used by the second one, causing
    // it to definitely not hold.
    w.method(); 
}
```
This will be necessary for the new solver, as it only lazily relates aliases via nested `AliasRelate` goals. As mentioned in the PR description, it's also just generally an antipattern to check multiple nested goals in isolation without using fulfillment.

@rfcbot fcp merge

**Comment by Mark-Simulacrum** [comment]
Marking this as triaged -- looks like attempts were made to improve performance in #124303 but did not pan out. The regressions are mostly pretty small with the exception of a stress test for exactly(?) this code.
