### PR TITLE
Provide overlapping types for coherence errors

### LINKED ISSUE #23980: Coherence error messages can be inscrutable
In particular, when the overlap check fails, it doesn't give much clarity, particularly when the overlap is between impls in different crates. It should tell you:

1. Precisely what type overlaps
2. For each case of negative reasoning it was not able to make, why it was not able to make it.

#2 might be a bit tricky to do, not sure, but we can certainly improve on current state of affairs.

### PR DESCRIPTION
**Pull request by aturon**
Currently, a coherence error based on overlapping impls simply mentions
the trait, and points to the two conflicting impls:

```
error: conflicting implementations for trait `Foo`
```

With this commit, the error will include all input types to the
trait (including the `Self` type) after unification between the
overlapping impls. In other words, the error message will provide
feedback with full type details, like:

```
error: conflicting implementations of trait `Foo<u32>` for type `u8`:
```

When the `Self` type for the two impls unify to an inference variable,
it is elided in the output, since "for type `_`" is just noise in that
case.

Closes #23980

r? @nikomatsakis

### CODE REVIEW

File: src/librustc/middle/traits/coherence.rs [hunk 1]
```diff
@@ -27,11 +27,12 @@ use syntax::codemap::{DUMMY_SP, Span};
 #[derive(Copy, Clone)]
 struct InferIsLocal(bool);
 
-/// True if there exist types that satisfy both of the two given impls.
-pub fn overlapping_impls(infcx: &InferCtxt,
-                         impl1_def_id: DefId,
-                         impl2_def_id: DefId)
-                         -> bool
+/// If there are types that satisfy both impls, returns a `TraitRef`
+/// with those types substituted.
```
Comment (nikomatsakis) [inline src/librustc/middle/traits/coherence.rs]: So the thing that makes me wary here is that, because of the `probe`, this trait reference may include unresolved type variables that have since been popped. Basically, it's ok to print it out, but it's not ok to do much else with it, since it contains the equivalent of dangling references. I think instead of using `resolve_type_vars_if_possible`, we should consider using `infer::freshen`, which also resolves type variables, but which replaces unresolved type variables with a `FreshTy`. (Possibly not the best names...) One problem though is that freshen also replaces regions with `'static` which, at least if they are printed out, could be pretty confusing. 

I guess another, easier, option would be to move the `probe` call outside of `overlapping_impls` and into `check_if_impls_overlap`. Never mind, let's do that instead. :)

**Comment by nikomatsakis** [comment]
Also, we should add a test for the new message I think. I hate tests that encode error messages, but it seems like there is non-trivial logic here, so we'd like to test that the types we expect are being printed.

**Comment by aturon** [comment]
Test added. And it turned out the `probe` wasn't needed anyway, since each invocation was on a fresh infcx.

**Comment by nikomatsakis** [comment]
@aturon seems good, but travis is unhappy -- still, I see no clear reason why this is the case. Perhaps it is bogus.

**Comment by nikomatsakis** [comment]
@bors r+

let's see what bors thinks.

**Comment by sanxiyn** [comment]
Travis failure is due to `test [compile-fail] compile-fail/issue-28568.rs ... FAILED`.
