### PR TITLE
`let`'s not needed in struct field definitions

### LINKED ISSUE #101683: Recover from accidental usage of `let` in struct definition
Given the following code: [link](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=f96314249d209ba928390d7c211ca8e3)

```rust
struct Struct {
    let x: i32,
}

fn main() {

}
```

The current output is:

```
   Compiling playground v0.0.1 (/playground)
error: expected identifier, found keyword `let`
 --> src/main.rs:2:5
  |
2 |     let x: i32,
  |     ^^^ expected identifier, found keyword

error: could not compile `playground` due to previous error
```

Since normal variable declaration are done using a `let` or other keywords in front and I accidentally made that typo due to muscle memory from creating regular variables. I think the ideal output for such a typo will be to suggest removing the `let` and having a small note stating that `let` is not required for struct variable declarations. (Note: the small note can be omitted if not necessary). This may be useful for beginners first getting used to the language's syntax.

### PR DESCRIPTION
**Pull request by ghost**
Fixes #101683

### CODE REVIEW

**Comment by estebank** [comment]
You will have to run `./x.py test src/test/ui --bless` to update the checked test output.

File: compiler/rustc_parse/src/parser/item.rs [hunk 1]
```diff
@@ -1725,7 +1725,12 @@ impl<'a> Parser<'a> {
                 err.help("see https://doc.rust-lang.org/book/ch05-03-method-syntax.html for more information");
                 err
             } else {
-                self.expected_ident_found()
+                let mut err = self.expected_ident_found();
+                if ident.name == kw::Let {
```
Comment (estebank) [inline compiler/rustc_parse/src/parser/item.rs:1729]: Ideally we would do N=1 lookahead to check if the next element is an identifier, and then do `self.bump();` (to consume the `let`) and then get that ident, *emit the error* and return `Ok(ident)` (so that the parser can properly recover and continue creating the `struct` with the expected field name, and even emit errors if the mistyped field isn't included elsewhere). In all other cases, we keep the current behavior (returning `err`) and let the other parser recovery kick in.

Comment (estebank) [reply compiler/rustc_parse/src/parser/item.rs:1729]: We might want to extend the existing test to include something like

```rust
struct S {
    let s: (),
    y: (),
}
fn main() {
    let _ = S { // should complain about missing `y`
        s: (),
    };
    let _ = S {
        y: (),  // should complain about missing `s`
    };
    let _ = S {
        let s: (),  // should complain about missing `y` and the spurious `let`
    };
    let _ = S {
        let y: (), // should complain about missing `s` and the spurious `let`
    };
    let _ = S {
        let s = (),  // should complain about missing `y`, the `:` to `=` typo and the spurious `let`
    };
    let _ = S {
        let y = (), // should complain about missing `s`, the `:` to `=` typo and the spurious `let`
    };
}
```

Keep in mind that the later four recoveries are not included in this PR (but I would like to have it in the future).

**Comment by gimbles** [comment]
> You will have to run `./x.py test src/test/ui --bless` to update the checked test output.

Yah, will bless it a in a while. Currently struggling with git branches again... (why does github not allow multiple forks )😮‍💨

**Comment by gimbles** [comment]
@rustbot author

cc @estebank Finally got some time and implemented what you described. Currently it's borked though and a test breaks. Any idea why? 🤔

**Comment by Rageking8** [comment]
```
compiler/rustc_parse/src/parser/item.rs at line 1735:
                 err.help("unlike in C++, Java, and C#, functions are declared in `impl` blocks");
                 err.help("see https://doc.rust-lang.org/book/ch05-03-method-syntax.html for more information");
                 err
-            }
-
-            else {
+            } else {
                 let mut err = self.expected_ident_found();
                 if self.check_ident() {
                     self.bump();
```
(From CI logs)

CI seems to be complaining about the code formatting, maybe try blessing again with tidy.

**Comment by gimbles** [comment]
> ```
> compiler/rustc_parse/src/parser/item.rs at line 1735:
>                  err.help("unlike in C++, Java, and C#, functions are declared in `impl` blocks");
>                  err.help("see https://doc.rust-lang.org/book/ch05-03-method-syntax.html for more information");
>                  err
> -            }
> -
> -            else {
> +            } else {
>                  let mut err = self.expected_ident_found();
>                  if self.check_ident() {
>                      self.bump();
> ```
> 
> (From CI logs)
> 
> CI seems to be complaining about the code formatting, maybe try blessing again with tidy.

Oh ye, forgot to tidy, aside from that I meant the ICE causing test bork

File: compiler/rustc_parse/src/parser/item.rs [hunk 2]
```diff
@@ -1724,11 +1724,17 @@ impl<'a> Parser<'a> {
                 err.help("unlike in C++, Java, and C#, functions are declared in `impl` blocks");
                 err.help("see https://doc.rust-lang.org/book/ch05-03-method-syntax.html for more information");
                 err
-            } else {
+            }
+
+            else {
```
Comment (estebank) [inline compiler/rustc_parse/src/parser/item.rs]: Run fmt on this
```suggestion
            } else {
```

File: compiler/rustc_parse/src/parser/item.rs [hunk 3]
```diff
@@ -1725,7 +1725,16 @@ impl<'a> Parser<'a> {
...
+                let mut err = self.expected_ident_found();
+                if self.check_ident() {
+                    self.bump();
+                    let (ident, _) = self.ident_or_err()?;
+                    err.help("the let keyword is not allowed in struct field definitions");
+                    err.help("see https://doc.rust-lang.org/book/ch05-01-defining-structs.html for more information");
+                    err.emit();
+                    return Ok(ident);
+                }
+                err
```
Comment (estebank) [inline compiler/rustc_parse/src/parser/item.rs:1737]: I think it might be wrong because `ident_or_err` didn't `bump` (which is why there might be another `bump` below before returning `Ok`, so maybe you need to do yet another `bump` before returning here and that would fix things? The parser didn't advance as many tokens as you thought it had? I'll admit the current behavior is weird.

File: compiler/rustc_parse/src/parser/item.rs [hunk 4]
```diff
@@ -1725,7 +1725,16 @@ impl<'a> Parser<'a> {
                 err.help("see https://doc.rust-lang.org/book/ch05-03-method-syntax.html for more information");
                 err
             } else {
-                self.expected_ident_found()
+                let mut err = self.expected_ident_found();
+                if self.check_ident() {
+                    self.bump();
```
Comment (estebank) [inline compiler/rustc_parse/src/parser/item.rs:1730]:
```suggestion
                    self.bump(); // `let`
```

File: compiler/rustc_parse/src/parser/item.rs [hunk 5]
```diff
@@ -1725,7 +1725,16 @@ impl<'a> Parser<'a> {
...
+                    let (ident, _) = self.ident_or_err()?;
+                    err.help("the let keyword is not allowed in struct field definitions");
```
Comment (estebank) [inline compiler/rustc_parse/src/parser/item.rs:1732]: Surround keywords with backticks, and this could be a structured suggestion

```suggestion
                    err.span_suggestion_verbose(
                        self.prev_token.span.to(ident.span),
                        "the `let` keyword is not allowed in struct field definitions",
                        String::new(),
                        Applicability::MachineApplicable,
                    );
```

File: compiler/rustc_parse/src/parser/item.rs [hunk 6]
```diff
@@ -1725,7 +1725,16 @@ impl<'a> Parser<'a> {
...
+                    err.help("see https://doc.rust-lang.org/book/ch05-01-defining-structs.html for more information");
```
Comment (estebank) [inline compiler/rustc_parse/src/parser/item.rs:1733]:
```suggestion
                    err.help("see <https://doc.rust-lang.org/book/ch05-01-defining-structs.html> for more information");
```

File: compiler/rustc_parse/src/parser/item.rs (hunk 3 above)
Comment (gimbles) [reply compiler/rustc_parse/src/parser/item.rs]: Bumping before returning didn't seem to help, look at the latest commit CI logs when it finishes

File: compiler/rustc_parse/src/parser/item.rs [hunk 7]
```diff
@@ -1725,7 +1725,21 @@ impl<'a> Parser<'a> {
                 err.help("see https://doc.rust-lang.org/book/ch05-03-method-syntax.html for more information");
                 err
             } else {
-                self.expected_ident_found()
+                let mut err = self.expected_ident_found();
+                if let Some((ident, _)) = self.token.ident() {
```
Comment (estebank) [inline compiler/rustc_parse/src/parser/item.rs:1729]: You also need something like the following (I think that `ident` won't coerce to `&str`, so this exact code won't work, but I think there's an `as_str()` method):

```suggestion
                if let Some((ident, _)) = self.token.ident() && ident == "let" {
```

File: compiler/rustc_parse/src/parser/item.rs (hunk 3 above)
Comment (gimbles) [reply compiler/rustc_parse/src/parser/item.rs]: <FIXED>

File: src/test/ui/parser/removed-syntax-field-let.stderr [hunk 8]
```diff
@@ -1,10 +1,15 @@
...
-LL | struct S {
-   |        - while parsing this struct
 LL |     let foo: (),
    |     ^^^ expected identifier, found keyword
+   |
+   = help: see <https://doc.rust-lang.org/book/ch05-01-defining-structs.html> for more information
+help: remove the let, the `let` keyword is not allowed in struct field definitions
+   |
+LL -     let foo: (),
+LL +      foo: (),
```
Comment (Rageking8) [inline src/test/ui/parser/removed-syntax-field-let.stderr:11]: Is there one additional space character here in the generated help message (which should not be there) or am I missing something?

File: src/test/ui/parser/removed-syntax-field-let.stderr [hunk 9]
```diff
@@ -1,10 +1,15 @@
 error: expected identifier, found keyword `let`
   --> $DIR/removed-syntax-field-let.rs:2:5
    |
-LL | struct S {
-   |        - while parsing this struct
 LL |     let foo: (),
    |     ^^^ expected identifier, found keyword
+   |
+   = help: see <https://doc.rust-lang.org/book/ch05-01-defining-structs.html> for more information
+help: remove the let, the `let` keyword is not allowed in struct field definitions
```
Comment (Rageking8) [inline src/test/ui/parser/removed-syntax-field-let.stderr:8]: Not sure how to fix this but the formatting of these 2 help messages seems a little off and not uniform with other diagnostics IMO. Maybe the top line can be moved to the last line, below the suggested removal of `let`, if that is possible.

File: src/test/ui/parser/removed-syntax-field-let.stderr (hunk 8 above)
Comment (WaffleLapkin) [reply src/test/ui/parser/removed-syntax-field-let.stderr:11]: You are removing `"let"` from `"let foo: (),"`, so you get `" foo: (),"`. Replacing `self.prev_token.span` with `self.prev_token.span.until(self.token.span)` or something alike should help.

File: compiler/rustc_parse/src/parser/item.rs [hunk 10]
```diff
@@ -1788,7 +1788,23 @@ impl<'a> Parser<'a> {
...
+                    self.bump(); // `let`
+                    let span = self.prev_token.span.until(self.token.span);
+                    err.span_suggestion(
+                        span,
+                        "remove the let, the `let` keyword is not allowed in struct field definitions",
+                        String::new(),
+                        Applicability::MachineApplicable,
+                    );
+                    err.span_note(span, "the `let` keyword is not allowed");
+                    err.span_note(span, "see <https://doc.rust-lang.org/book/ch05-01-defining-structs.html> for more information");
```
Comment (estebank) [inline compiler/rustc_parse/src/parser/item.rs:1802]: Lets make these notes instead of span notes. If we look at the cli output, we are pointing at the `let` four times now, one in the main error, two in the notes and one in the suggestion.

```suggestion
                    err.note(span, "the `let` keyword is not allowed in `struct` fields");
                    err.note(span, "see <https://doc.rust-lang.org/book/ch05-01-defining-structs.html> for more information");
```

I'm not opposed to increasing verbosity when it adds more information, but in this case using notes the output would be


```
error: expected identifier, found keyword `let`
  --> $DIR/removed-syntax-field-let.rs:2:5
   |
LL |     let foo: (),
   |     ^^^ expected identifier, found keyword
   |
  = note: the `let` keyword is not allowed in `struct` fields
  = note: see <https://doc.rust-lang.org/book/ch05-01-defining-structs.html> for more information
help: remove the let, the `let` keyword is not allowed in struct field definitions
   |
LL -     let foo: (),
LL +     foo: (),
   |
```

which has better information density and personally think it doesn't look half bad. The only issue is the difference between `  = note:` and `help:` clashing slightly in the output, but that's how the formatting operates. If you believe we should improve it (and I'm not against that either!) we should tackle that in the diagnostic formatting logic, not in a specific diagnostic. Does this make sense?

r=me after addressing the nitpick and squashing the commits.

File: src/test/ui/parser/removed-syntax-field-let.stderr (hunk 9 above)
Comment (gimbles) [reply src/test/ui/parser/removed-syntax-field-let.stderr]: Take a peek at the simplification performed later on with Est's review.

File: compiler/rustc_parse/src/parser/item.rs [hunk 11]
```diff
@@ -1788,7 +1788,23 @@ impl<'a> Parser<'a> {
                     }
                 }
             } else {
-                self.expected_ident_found()
+                let mut err = self.expected_ident_found();
+                if let Some((ident, _)) = self.token.ident() && ident.as_str() == "let" {
```
Comment (compiler-errors) [inline compiler/rustc_parse/src/parser/item.rs:1792]: This probably could've been `self.token.is_keyword(kw::Let)`, see [`Token::is_keyword`](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_ast/token/struct.Token.html#method.is_keyword)

Comment (compiler-errors) [reply compiler/rustc_parse/src/parser/item.rs:1792]: Alternatively, this could've used [`Parser::eat_keyword_noexpect`](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_parse/parser/struct.Parser.html#method.eat_keyword_noexpect) to avoid the bump call below

File: compiler/rustc_parse/src/parser/item.rs [hunk 12]
```diff
@@ -1788,7 +1788,23 @@ impl<'a> Parser<'a> {
...
+                    self.bump(); // `let`
+                    let span = self.prev_token.span.until(self.token.span);
+                    err.span_suggestion(
```
Comment (compiler-errors) [inline compiler/rustc_parse/src/parser/item.rs:1795]: @Xiretza this is a good example of a `#[derive(Subdiagnostic)]` candidate that both emits notes and a suggestion!

File: compiler/rustc_parse/src/parser/item.rs [hunk 13]
```diff
@@ -1788,7 +1788,23 @@ impl<'a> Parser<'a> {
...
+                        span,
+                        "remove the let, the `let` keyword is not allowed in struct field definitions",
+                        String::new(),
+                        Applicability::MachineApplicable,
+                    );
+                    err.note("the `let` keyword is not allowed in `struct` fields");
+                    err.note("see <https://doc.rust-lang.org/book/ch05-01-defining-structs.html> for more information");
+                    err.emit();
+                    self.bump();
+                    return Ok(ident);
```
Comment (compiler-errors) [inline compiler/rustc_parse/src/parser/item.rs:1805]: @gimbles for future reference, why is this bumping twice? This should perhaps be:

```suggestion
                    let ident = self.expect_ident()?;
                    return Ok(ident);
```

Otherwise, it seems to me like it's returning `let` tas he struct field name?

Comment (gimbles) [reply compiler/rustc_parse/src/parser/item.rs:1805]: Look at the earlier reviews on wonky spans ^^

File: compiler/rustc_parse/src/parser/item.rs (hunk 11 above)
Comment (gimbles) [reply compiler/rustc_parse/src/parser/item.rs:1792]: Awesome, will send an improvement PR later on. 👍🏻
