### PR TITLE
Always build miri for the host in `x run miri`

### LINKED ISSUE #145839: "./x run miri" does not work with "--target"
### Summary

Miri can run things for arbitrary targets, so `./x run miri --target <foo>` should juts work. However, something does not seem to be wired up correctly:

```
$ ./x run miri --stage 1 --target aarch64-apple-darwin -- src/tools/miri/tests/pass/hello.rs
Building bootstrap
    Finished `dev` profile [unoptimized] target(s) in 0.07s

thread 'main' panicked at src/bootstrap/src/core/build_steps/compile.rs:1841:13:
assertion `left == right` failed: Cross-compiling is not yet supported with `download-rustc`
  left: x86_64-unknown-linux-gnu
 right: aarch64-apple-darwin
```
This shouldn't be cross-compiling anything so the error makes little sense. But okay, let's disable download-rustc:
```
$ ./x run miri --stage 1 --target aarch64-apple-darwin --set rust.download-rustc=false -- src/tools/miri/tests/pass/hello.rs
Building bootstrap
    Finished `dev` profile [unoptimized] target(s) in 0.11s

thread 'main' panicked at src/bootstrap/src/core/builder/mod.rs:1436:17:
It is not possible to build the standard library for `aarch64-apple-darwin` using the stage0 compiler.
You have to build a stage1 compiler for `x86_64-unknown-linux-gnu` first, and then use it to build a standard library for `aarch64-apple-darwin`.
```

### Operating system

Debian testing

### HEAD

6ba0ce40941eee1ca02e9ba49c791ada5158747a

### PR DESCRIPTION
**Pull request by Kobzol**
Previously we were building Miri for the passed `--target`, which was wrong.

Fixes: https://github.com/rust-lang/rust/issues/145839

r? @jieyouxu

### CODE REVIEW

**Comment by Kobzol** [comment]
@RalfJung Could you please check if this PR fixes the issue for you? With the changes from this PR, I was able to build miri, but the actual `x run miri` invocation fails (not sure if tha's expected):
```
thread 'rustc' panicked at /projects/personal/rust/rust/compiler/rustc_hir/src/hir.rs:1205:35:
invalid enum variant tag while decoding `Attribute`, expected 0..2, actual 161
```

**Comment by RalfJung** [comment]
That's definitely not expected, that indicates an invalid rlib so something got seriously mixed up.

**Comment by RalfJung** [comment]
That's just invoking a binary? Not sure what you mean.

`cargo miri` needs to invoke Miri which should be the Miri that has just been built.

**Comment by RalfJung** [comment]
FWIW `./x run miri --stage 1 --target aarch64-apple-darwin --set rust.download-rustc=false -- src/tools/miri/tests/pass/hello.rs` actually works for me with this PR.

File: src/bootstrap/src/core/build_steps/run.rs [hunk 1]
```diff
@@ -113,14 +123,9 @@ impl Step for Miri {
...
-        run.builder.ensure(Miri { target: run.target });
-    }
-
-    fn run(self, builder: &Builder<'_>) {
-        let host = builder.build.host_target;
-        let target = self.target;
+        let builder = run.builder;
 
-        // `x run` uses stage 0 by default but miri does not work well with stage 0.
+        // `x run` uses stage 0 by default, but miri does not work well with stage 0.
```
Comment (jieyouxu) [inline src/bootstrap/src/core/build_steps/run.rs:128]: Question: "does not work well", or "intentionally does not support"?

**Review by jieyouxu — APPROVED** [review]
Thanks, tiny doc question

*[View changes since this review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/rust/145841/d327d651e2583eb601978179f2ca9808f5e243bb..0781c47acf0c0de35450b81a67d4367ce4efc72d)*

**Comment by jieyouxu** [comment]
Feel free to r=me with or without the doc nit.

File: src/bootstrap/src/core/build_steps/run.rs (hunk 1 above)
Comment (Kobzol) [reply src/bootstrap/src/core/build_steps/run.rs:128]: No idea honestly. Since miri requires a libstd sysroot to be prepared, I would maybe say "is not supported".

Comment (RalfJung) [reply src/bootstrap/src/core/build_steps/run.rs:128]: Yeah, Miri needs rustc and we can't build against the beta rustc so a stage 0 Miri can't work.

**Comment by RalfJung** [comment]
Thanks :-)
