### PR TITLE
Avoid memory copy logic for zsts

### LINKED ISSUE #67539: rustc endless loop on some constant casts
I bisected nightlies to figure out when my [pull request's tests](https://github.com/antifuchs/nonzero_ext/pull/7) started breaking on nightly. The following is the template `cargo-bisect-rustc` gave me.

# Regression found in the compiler

searched nightlies: from nightly-2019-10-01 to nightly-2019-12-22
regressed nightly: nightly-2019-11-20
searched commits: from https://github.com/rust-lang/rust/commit/3e525e3f6d9e85d54fa4c49b52df85aa0c990100 to https://github.com/rust-lang/rust/commit/618b01f9fa0a6b4e7e2ce5b3409abe104b80c4a8
regressed commit: https://github.com/rust-lang/rust/commit/d1da8023dafd3e277b5a4c5475aa2cb199a176b9
source code: https://github.com/antifuchs/nonzero_ext/pull/7

## Instructions

I tried the following on macOS and linux (in CI):

1. Check out the repo & branch of that pull request
2. Run `cargo +nightly test --test=compiletest` with a nightly version later than d1da8023dafd3e277b5a4c5475aa2cb199a176b9, that is >= `nightly-2019-11-20`

## Error

The compile test (provided by trybuild) does not terminate - rustc seems to be running forever, consuming 99% of my CPU all the while.

Since the instructions to repro are a bit convoluted (and massive), I'll try and boil down the repro case a little bit.

### PR DESCRIPTION
**Pull request by spastorino**
r? @oli-obk 

One of the included commits is work done by @HeroicKatora in #62655

### CODE REVIEW

File: src/librustc_mir/interpret/memory.rs [hunk 1]
```diff
@@ -847,44 +847,49 @@ impl<'mir, 'tcx, M: Machine<'mir, 'tcx>> Memory<'mir, 'tcx, M> {
...
-            if src.alloc_id == dest.alloc_id {
-                if nonoverlapping {
-                    if (src.offset <= dest.offset && src.offset + size > dest.offset)
-                        || (dest.offset <= src.offset && dest.offset + size > src.offset)
-                    {
-                        throw_ub_format!("copy_nonoverlapping called on overlapping ranges")
+
+        // If `dest_bytes` is empty we just optimize to not run anything for zsts.
+        // See #67539
+        if !dest_bytes.is_empty() {
```
Comment (bjorn3) [inline src/librustc_mir/interpret/memory.rs]: Why not `if ... { return Ok(()); }`?

Comment (spastorino) [reply src/librustc_mir/interpret/memory.rs]: Done!

File: src/librustc_mir/interpret/memory.rs [hunk 2]
```diff
@@ -847,6 +847,12 @@ impl<'mir, 'tcx, M: Machine<'mir, 'tcx>> Memory<'mir, 'tcx, M> {
         let dest_bytes =
             self.get_raw_mut(dest.alloc_id)?.get_bytes_mut(&tcx, dest, size * length)?.as_mut_ptr();
 
+        // If `dest_bytes` is empty we just optimize to not run anything for zsts.
+        // See #67539
+        if dest_bytes.is_empty() {
```
Comment (oli-obk) [inline src/librustc_mir/interpret/memory.rs]: I guess you need to split `dest_bytes` into the slice part, then do the early abort, then do the `as_mut_ptr`

Comment (spastorino) [reply src/librustc_mir/interpret/memory.rs]: Yeah, was to fast to push :)

**Comment by oli-obk** [comment]
@rust-timer build d5da6a798d2c8b458a417747b9a77b048625569f

File: src/librustc_mir/interpret/memory.rs [hunk 3]
```diff
@@ -839,13 +839,40 @@ impl<'mir, 'tcx, M: Machine<'mir, 'tcx>> Memory<'mir, 'tcx, M> {
...
+            // Fast path: If all bytes are `undef` then there is nothing to copy. The target range
+            // is marked as undef but we otherwise omit changing the byte representation which may
+            // be arbitrary for undef bytes.
+            // This also avoids writing to the target bytes so that the backing allocation is never
+            // touched if the bytes stay undef for the whole interpreter execution. On contemporary
+            // operating system this can avoid physically allocating the page.
+            let dest_alloc = self.get_raw_mut(dest.alloc_id)?;
+            dest_alloc.mark_definedness(dest, size * length, false);
+            dest_alloc.mark_relocation_range(relocations);
+            return Ok(());
```
Comment (RalfJung) [inline src/librustc_mir/interpret/memory.rs]: Can you move the fast path to down below the `get_raw*` calls? Those do some checks that I am not sure we can skip...

File: src/librustc_mir/interpret/memory.rs [hunk 4]
```diff
@@ -839,13 +839,40 @@ impl<'mir, 'tcx, M: Machine<'mir, 'tcx>> Memory<'mir, 'tcx, M> {
...
         // This checks relocation edges on the src.
         let src_bytes =
             self.get_raw(src.alloc_id)?.get_bytes_with_undef_and_ptr(&tcx, src, size)?.as_ptr();
         let dest_bytes =
-            self.get_raw_mut(dest.alloc_id)?.get_bytes_mut(&tcx, dest, size * length)?.as_mut_ptr();
+            self.get_raw_mut(dest.alloc_id)?.get_bytes_mut(&tcx, dest, size * length)?;
+
+        // If `dest_bytes` is empty we just optimize to not run anything for zsts.
+        // See #67539
+        if dest_bytes.is_empty() {
```
Comment (RalfJung) [inline src/librustc_mir/interpret/memory.rs]: Is this even reachable? Shouldn't `all_bytes_undef` always be `true` for empty ranges?

File: src/librustc_mir/interpret/memory.rs [hunk 5]
```diff
@@ -881,38 +908,23 @@ impl<'mir, 'tcx, M: Machine<'mir, 'tcx>> Memory<'mir, 'tcx, M> {
             }
         }
 
-        // copy definedness to the destination
-        self.copy_undef_mask(src, dest, size, length)?;
+        // now copy over the undef data
```
Comment (RalfJung) [inline src/librustc_mir/interpret/memory.rs]: This doesn't copy any *data*, the comment is confusing.

File: src/librustc_mir/interpret/memory.rs (hunk 4 above)
Comment (bjorn3) [reply src/librustc_mir/interpret/memory.rs]: `compress_undef_range` sets `initial` to `self.undef_mask.get(src.offset)`. If the memory immediately following the range is defined, then it will return `true`, thus causing `all_bytes_undef` to return `false`.

File: src/librustc_mir/interpret/memory.rs (hunk 3 above)
Comment (spastorino) [reply src/librustc_mir/interpret/memory.rs]: Done!

File: src/librustc_mir/interpret/memory.rs (hunk 5 above)
Comment (spastorino) [reply src/librustc_mir/interpret/memory.rs]: Rolled it back to the comment we had before.
