### PR TITLE
Don't count variants/fields/consts/associated types in doc-coverage doc examples

### LINKED ISSUE #75374: 8.5% runtime performance degradation for GNU-toolchain 1.45.x vs. 1.44.x in Windows
Hello,

For some time now I've been writing a chess engine in Rust. I develop on Windows at this time, but because I wanted to use only open source software for this engine, the GNU toolchain has been my primary target. I've been using the MSVC toolchain for profiling. Generally, This was the speed ranking:

1. GNU toolchain
2. MSVC toolchain using the LLD linker (installed on MSYS2)
3. MSVC toolchain with it's normal MS linker

In version 1.45.x, I've seen a great performance drop for the GNU toolchain, when running the compiled program.

Steps to reproduce:

Clone this repository: https://github.com/mvanthoor/rustic
Install these toolchains:
stable-x86_64-pc-windows-gnu
stable-x86_64-pc-windows-msvc (default)
1.44.1-x86_64-pc-windows-gnu
1.44.1-x86_64-pc-windows-msvc*
Compile the engine; make sure you have RUSTFLAGS set for cpu-type=skylake
Run the engine "rustic.exe".

What it will do is a so called "perft": a performance test. It calculates moves in a given position to a given depth, and outputs the found move counts and speed per depth to the screen. The point of "perft" is to match the numbers known to be correct values, and to make it as fast as possible. You do this for a few hundred positions: if all the numbers match up to the known correct ones, move generation in your engine can be considered bug-free.

As said, in version 1.45, with the GNU toolchain, I have observed a great performance drop. The results on my computer are below. The values given are those for Perft 6, which in this case, the most interesting one, because it runs more thn three minutes. Everything below perft 6 is only a few seconds or fractions of seconds, so any deviation is within the margin of error on a modern CPU. The numbers for Perft 6 are always consistent, with a margin of +/- 0.5 seconds on my system.

As you can see, a compile made with the GNU 1.45.x toolchain rain in 217 seconds... slowest of the bunch, down from a class-leading performance of 200 seconds in version 1.44.x. The MSVC toolchain with the normal MS-linker did get a nice speed boost in version 1.45.

Therefore, to obtain maximum speed, I would either need to stick with version GNU 1.44.1. Even if I switch to version MSVC version 1.45.2 to be able to upgrade, this is still slower than GNU 1.44.1.

(Somewhere along the line during the last few versions, the MSVC/LLD combo first lost speed to 212 seconds, and then gained speed again to 207 seconds. I have seen compiles with this toolchain running at 203 seconds for Perft 6. From all the toolchains across versions, this is the least consistent.)

If you have any questions or need something tested, please ask. In the next Rust version, I'd very much like to see the GNU toolchain regain the speed it had with 1.44.1 and earlier.

===============================================================================

Summary

Perft 6 results:

1.	1.44.1 GNU		: 200.23 seconds
2.	1.45.2 MSVC 		: 202.88 seconds
3.	1.44.1 MSVC 		: 206.70 seconds
4.	1.45.2 MSVC/LLD    : 207.73 seconds
5.	1.44.1 MSVC/LLD    : 212.22 seconds
6.	1.45.2 GNU	       : 217.18 seconds

===============================================================================

1.44.1-x86_64-pc-windows-gnu
RUSTFLAGS=-C target-cpu=skylake

Perft 1: 48 (0 ms, inf leaves/sec)
Perft 2: 2039 (0 ms, inf leaves/sec)
Perft 3: 97862 (2 ms, 48931000 leaves/sec)
Perft 4: 4085603 (101 ms, 40451514 leaves/sec)
Perft 5: 193690690 (4706 ms, 41158242 leaves/sec)
Perft 6: 8031647685 (200227 ms, 40112710 leaves/sec)
Total time spent: 205036 ms
Execution speed: 40136970 leaves/second

===============================================================================

stable-x86_64-pc-windows-gnu
RUSTFLAGS=-C target-cpu=skylake

Perft 1: 48 (0 ms, inf leaves/sec)
Perft 2: 2039 (0 ms, inf leaves/sec)
Perft 3: 97862 (2 ms, 48931000 leaves/sec)
Perft 4: 4085603 (101 ms, 40451514 leaves/sec)
Perft 5: 193690690 (4668 ms, 41493292 leaves/sec)
Perft 6: 8031647685 (217176 ms, 36982206 leaves/sec)
Total time spent: 221947 ms
Execution speed: 37078779 leaves/second

===============================================================================

1.44.1-x86_64-pc-windows-msvc
RUSTFLAGS=-C target-cpu=skylake

Perft 1: 48 (0 ms, inf leaves/sec)
Perft 2: 2039 (0 ms, inf leaves/sec)
Perft 3: 97862 (2 ms, 48931000 leaves/sec)
Perft 4: 4085603 (105 ms, 38910504 leaves/sec)
Perft 5: 193690690 (4827 ms, 40126515 leaves/sec)
Perft 6: 8031647685 (206698 ms, 38856920 leaves/sec)
Total time spent: 211632 ms
Execution speed: 38886009 leaves/second

===============================================================================

stable-x86_64-pc-windows-msvc
RUSTFLAGS=-C target-cpu=skylake

Perft 1: 48 (0 ms, inf leaves/sec)
Perft 2: 2039 (0 ms, inf leaves/sec)
Perft 3: 97862 (2 ms, 48931000 leaves/sec)
Perft 4: 4085603 (102 ms, 40054931 leaves/sec)
Perft 5: 193690690 (4728 ms, 40966728 leaves/sec)
Perft 6: 8031647685 (202875 ms, 39589144 leaves/sec)
Total time spent: 207707 ms
Execution speed: 39620830 leaves/second

===============================================================================

1.44.1-x86_64-pc-windows-msvc
RUSTFLAGS=-C target-cpu=skylake
Using lld-link.exe through MSYS2

Perft 1: 48 (0 ms, inf leaves/sec)
Perft 2: 2039 (0 ms, inf leaves/sec)
Perft 3: 97862 (2 ms, 48931000 leaves/sec)
Perft 4: 4085603 (105 ms, 38910504 leaves/sec)
Perft 5: 193690690 (4839 ms, 40027007 leaves/sec)
Perft 6: 8031647685 (207272 ms, 38749313 leaves/sec)
Total time spent: 212218 ms
Execution speed: 38778632 leaves/second

===============================================================================

stable-x86_64-pc-windows-msvc
RUSTFLAGS=-C target-cpu=skylake
Using lld-link.exe through MSYS2

Perft 1: 48 (0 ms, inf leaves/sec)
Perft 2: 2039 (0 ms, inf leaves/sec)
Perft 3: 97862 (2 ms, 48931000 leaves/sec)
Perft 4: 4085603 (102 ms, 40054931 leaves/sec)
Perft 5: 193690690 (4729 ms, 40958065 leaves/sec)
Perft 6: 8031647685 (202895 ms, 39585242 leaves/sec)
Total time spent: 207728 ms
Execution speed: 39616825 leaves/second

===============================================================================

### LINKED ISSUE #75714: Don't count variants/fields/consts/associated types in doc-coverage doc examples
We shouldn't expect them to have one so it shouldn't be counted.

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Fixes #75714.

I think I'll need to update the equivalent lint too. Creating an issue for that!

r? @jyn514

### CODE REVIEW

**Comment by jyn514** [comment]
You linked to the wrong issue, I think you meant https://github.com/rust-lang/rust/issues/75714.

**Comment by GuillaumeGomez** [comment]
I've been failing to reference the correct issue a lot lately. I think something is wrong with my copy/paste skill...

File: src/librustdoc/passes/calculate_doc_coverage.rs [hunk 1]
```diff
@@ -31,18 +31,27 @@ fn calculate_doc_coverage(krate: clean::Crate, ctx: &DocContext<'_>) -> clean::C
...
         if has_docs {
             self.with_docs += 1;
         }
-        if has_doc_example {
-            self.with_examples += 1;
+        if should_have_doc_examples {
+            self.total_examples += 1;
+            if has_doc_example {
+                self.with_examples += 1;
+            }
```
Comment (jyn514) [inline src/librustdoc/passes/calculate_doc_coverage.rs:54]: This will ignore variants that have examples, which doesn't seem quite right. I'm not sure what the correct behavior is though, since we don't want to _require_ examples for coverage normally.

Comment (GuillaumeGomez) [reply src/librustdoc/passes/calculate_doc_coverage.rs:54]: I can count it in case there is a doc example?

Comment (jyn514) [reply src/librustdoc/passes/calculate_doc_coverage.rs:54]: That sounds good, although we should document that edge case since it's not intuitive.

Comment (GuillaumeGomez) [reply src/librustdoc/passes/calculate_doc_coverage.rs:54]: Agreed!

**Comment by GuillaumeGomez** [comment]
Updated!

File: src/doc/rustdoc/src/unstable-features.md [hunk 2]
```diff
@@ -467,3 +467,36 @@ $ rustdoc src/lib.rs -Z unstable-options --runtool valgrind
...
+```
+
+You can also use this option with the `--output-format` one:
+
+```bash
+$ rustdoc src/lib.rs -Z unstable-options --show-coverage --output-format json
+{"lib.rs":{"total":4,"with_docs":4,"total_examples":4,"with_examples":1}}
+```
+
+To be noted: the computation of code examples follows these rules:
```
Comment (jyn514) [inline src/doc/rustdoc/src/unstable-features.md:494]:
```suggestion
Calculating code examples follows these rules:
```

**Review by jyn514 — APPROVED** [review]
r=me once nit is fixed
