### PR TITLE
extract expected return type for async fn generators

### LINKED ISSUE #60424: type inference doesn't work in async fn that return Box<dyn SomeTrait>
i have following fn that works completly fine:
```rust
pub fn test1() -> Box<dyn Debug> {
    Box::new("asdf")
}
```
if i try trivialy make it async just by adding `async` keyword i get build error:
```
error[E0271]: type mismatch resolving `<impl core::future::future::Future as core::future::future::Future>::Output == std::boxed::Box<(dyn std::fmt::Debug + 'static)>`
  --> comix_downloader_lib_async/src/lib.rs:49:25
   |
49 | pub async fn test1() -> Box<dyn Debug> {
   |                         ^^^^^^^^^^^^^^ expected &str, found trait std::fmt::Debug
   |
   = note: expected type `std::boxed::Box<&str>`
              found type `std::boxed::Box<(dyn std::fmt::Debug + 'static)>`
   = note: the return type of a function must have a statically known size
```
i can work around this by defining types of variables explicitly:
```rust
pub async fn test3() -> Box<dyn Debug> {
    let tmp : Box<dyn Debug> = Box::new("asdf");
    tmp
}
``` 
but for obvious reasons this is not as nice as sync version
maybe related to #60414 ?

`rustc --version` : `rustc 1.36.0-nightly (00859e3e6 2019-04-29)`

### PR DESCRIPTION
**Pull request by nikomatsakis**
Fixes #60424 

cc @Centril, I know you've been eager to see this fixed.

r? @cramertj

### CODE REVIEW

File: src/test/ui/async-await/return-ty-raw-ptr-coercion.rs [hunk 1]
```diff
@@ -0,0 +1,25 @@
...
+// edition:2018
+// check-pass
+
+#![allow(warnings)]
+
+use std::fmt::Debug;
+
+const TMP: u32 = 22;
+
+// Coerce from `Box<"asdf">` to `Box<dyn Debug>`.
```
Comment (lqd) [inline src/test/ui/async-await/return-ty-raw-ptr-coercion.rs]: Maybe the comment should read "Coerce from `&u32` to `*const u32`" ?

File: src/librustc/hir/mod.rs [hunk 2]
```diff
@@ -1366,17 +1366,43 @@ impl Body {
...
+}
+
+impl fmt::Display for AsyncGeneratorKind {
     fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
         f.write_str(match self {
-            GeneratorKind::Async => "`async` object",
-            GeneratorKind::Gen => "generator",
+            AsyncGeneratorKind::Block => "`async` block",
+            AsyncGeneratorKind::Closure => "`async` closure body",
+            AsyncGeneratorKind::Fn => "`async` fn body",
```
Comment (Centril) [inline src/librustc/hir/mod.rs]:
```suggestion
            AsyncGeneratorKind::Fn => "`async fn` body",
```

File: src/librustc_typeck/check/closure.rs [hunk 3]
```diff
@@ -620,6 +637,104 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
         result
     }
 
+    /// Invoked when we are translating the generator that results
+    /// from desugaring an `async fn`. Returns the "sugared" return
+    /// type of the `async fn` -- that is, the return type that the
+    /// user specified. The "desugared" return type is a `impl
+    /// Future<Output = T>`, so we do this by searching through the
+    /// obligations to extract the `T`.
+    fn deduce_future_output_from_obligations(
```
Comment (Centril) [inline src/librustc_typeck/check/closure.rs]:
```suggestion
    fn ty_infer_future_output_from_obligations(
```

File: src/librustc_typeck/check/closure.rs [hunk 4]
```diff
@@ -620,6 +637,104 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
...
+        &self,
+        expr_def_id: DefId,
+    ) -> Ty<'tcx> {
+        debug!("deduce_future_output_from_obligations(expr_def_id={:?})", expr_def_id);
+
+        let ret_coercion =
+            self.ret_coercion
```
Comment (Centril) [inline src/librustc_typeck/check/closure.rs]: Drive-by: Could you add a doc-comment to `ret_coercion` (missing atm: https://doc.rust-lang.org/nightly/nightly-rustc/rustc_typeck/check/struct.FnCtxt.html#structfield.ret_coercion)?

File: src/librustc_typeck/check/closure.rs [hunk 5]
```diff
@@ -620,6 +637,104 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
...
+                self.tcx.def_span(expr_def_id),
+                "async fn generator outside of a fn"
+            ));
+
+        // In practice, the return type of the surrounding function is
+        // always a (not yet resolved) inference variable, because it
+        // is the hidden type for an `impl Trait` that we are going to
+        // be inferring.
+        let ret_ty = ret_coercion.borrow().expected_ty();
+        let ret_ty = self.inh.infcx.shallow_resolve(ret_ty);
```
Comment (Centril) [inline src/librustc_typeck/check/closure.rs]: Also missing a doc comment for `shallow_resolve`: https://doc.rust-lang.org/nightly/nightly-rustc/rustc/infer/struct.InferCtxt.html#method.shallow_resolve

File: src/librustc_typeck/check/closure.rs [hunk 6]
```diff
@@ -620,6 +637,104 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
...
+        output_ty
+    }
+
+    /// Given a projection like
+    ///
+    /// `<_ as Future>::Output = T`
+    ///
+    /// returns `Some(T)`. If the projection is for some other trait,
+    /// returns `None`.
+    fn deduce_future_output_from_projection(
```
Comment (Centril) [inline src/librustc_typeck/check/closure.rs]:
```suggestion
    fn ty_infer_future_output_from_projection(
```

File: src/librustc_typeck/check/closure.rs [hunk 7]
```diff
@@ -620,6 +637,104 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
...
+            span_bug!(
+                cause_span,
+                "projecting associated item `{:?}` from future, which is not Output `{:?}`",
+                projection.projection_def_id(),
+                output_assoc_item,
+            );
+        }
+
+        // Extract the type from the projection.
+        let output_ty = projection.skip_binder().ty;
```
Comment (Centril) [inline src/librustc_typeck/check/closure.rs]: Maybe add a note here re. why `.skip_binder()` is OK here.

File: src/test/ui/async-await/return-ty-unsize-coercion.rs [hunk 8]
```diff
@@ -0,0 +1,34 @@
...
+// Also serves as a regression test for #60424.
+//
+// edition:2018
+// check-pass
+
+#![allow(warnings)]
+
+use std::fmt::Debug;
+
+// Coerce from `Box<"asdf">` to `Box<dyn Debug>`.
```
Comment (Centril) [inline src/test/ui/async-await/return-ty-unsize-coercion.rs]:
```suggestion
// Coerce from `Box::new("asdf")` to `Box<dyn Debug>`.
```

File: src/test/ui/async-await/return-ty-unsize-coercion.rs [hunk 9]
```diff
@@ -0,0 +1,34 @@
+// Check that we apply unsizing coercions based on the return type.
```
Comment (Centril) [inline src/test/ui/async-await/return-ty-unsize-coercion.rs]: Can you also include the string slice based regression test?

**Comment by Centril** [comment]
r=me if you like with comments addressed.

File: src/librustc_typeck/check/closure.rs (hunk 3 above)
Comment (nikomatsakis) [reply src/librustc_typeck/check/closure.rs]: Hmm, I think I prefer the current name. For one thing, `ty_infer` is not a verb; to me, this name suggests that we return a `ty::Infer` value or something like that. For another, the `deduce_` is used throughout this file under its plain English meaning of "figure out". I think I deliberately did not use "infer" as the choice of verb there because this inference mechanism is not related to the inference variables and other techniques we typically use.

File: src/librustc_typeck/check/closure.rs (hunk 4 above)
Comment (nikomatsakis) [reply src/librustc_typeck/check/closure.rs]: Yep, I would've found that useful as well.

File: src/librustc_typeck/check/closure.rs (hunk 6 above)
Comment (nikomatsakis) [reply src/librustc_typeck/check/closure.rs]: (See above)

File: src/test/ui/async-await/return-ty-unsize-coercion.rs (hunk 9 above)
Comment (nikomatsakis) [reply src/test/ui/async-await/return-ty-unsize-coercion.rs]: I'm not sure what test you have in mind exactly? 

Note that this errors in both sequential *and* async functions:

```rust

// Unsizing coercion from `Box<String>` to `Box<str>`.
fn unsize_string_coercion() {
    fn sync_example() -> Box<str> {
        Box::new("".to_string())
    }

    async fn async_example() -> Box<str> {
        Box::new("".to_string())
    }
}
```

**Comment by nikomatsakis** [comment]
@Centril 

> r=me if you like with comments addressed.

(with respect, you're not presently a [compiler reviewer](https://www.rust-lang.org/governance/teams/compiler))

File: src/librustc_typeck/check/closure.rs (hunk 7 above)
Comment (nikomatsakis) [reply src/librustc_typeck/check/closure.rs]: I'll do you one better -- I refactored it away altogether.

File: src/test/ui/async-await/async-block-control-flow-static-semantics.stderr [hunk 10]
```diff
@@ -49,16 +65,6 @@ LL |     let _: &dyn Future<Output = ()> = &block;
               found type `()`
    = note: required for the cast to the object type `dyn std::future::Future<Output = ()>`
 
-error[E0271]: type mismatch resolving `<impl std::future::Future as std::future::Future>::Output == u8`
-  --> $DIR/async-block-control-flow-static-semantics.rs:22:55
-   |
-LL | async fn return_targets_async_block_not_async_fn() -> u8 {
```
Comment (cramertj) [inline src/test/ui/async-await/async-block-control-flow-static-semantics.stderr]: \o/

**Comment by cramertj** [comment]
r=me with travis.

File: src/test/ui/async-await/return-ty-unsize-coercion.rs (hunk 9 above)
Comment (Centril) [reply src/test/ui/async-await/return-ty-unsize-coercion.rs]: This one: https://github.com/rust-lang/rust/issues/60424#issuecomment-528938362

**Comment by nikomatsakis** [comment]
@bors r-

forgot to add test @Centril  requested

**Comment by Centril** [comment]
Failed in https://github.com/rust-lang/rust/pull/65032#issuecomment-537753904, @bors r- 

Please `--bless --compare-mode=nll`. :)

**Comment by nikomatsakis** [comment]
Should we p=1 this? (I wonder if p=1 should be general policy for beta-nominated PRs)

(My reasoning is that if we are considering a backport, we want it on nightly ASAP to know about possible complications.)

**Comment by Centril** [comment]
I'll just include it in the next rollup which is even faster than p=1. ;)

File: src/librustc_typeck/check/closure.rs [hunk 11]
```diff
@@ -620,6 +637,117 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
         result
     }
 
+    /// Invoked when we are translating the generator that results
+    /// from desugaring an `async fn`. Returns the "sugared" return
+    /// type of the `async fn` -- that is, the return type that the
+    /// user specified. The "desugared" return type is a `impl
+    /// Future<Output = T>`, so we do this by searching through the
+    /// obligations to extract the `T`.
```
Comment (eddyb) [inline src/librustc_typeck/check/closure.rs]: Maybe leave a FIXME/open an issue somewhere about generalizing this so it can rely entirely on the `impl`s involved and not have to know about the `Future` trait at all?

**Comment by pnkfelix** [comment]
[discussed](https://zulip-archive.rust-lang.org/131828tcompiler/86450weeklymeeting2019100354818.html#177247903) at rustc meeting. we're going to leave it beta-nominated for another week so that it gets exercised a bit on nightly before we jump in.

**Comment by Centril** [comment]
Seems this PR introduced https://github.com/rust-lang/rust/issues/65159.

**Comment by nikomatsakis** [comment]
If we do backport, we would want to backport https://github.com/rust-lang/rust/pull/65235 too

**Comment by pnkfelix** [comment]
T-compiler discussed. Decided to let this ride-the-trains.

declined for beta-backport.

(For future github readers: If you need a work-around, its documented in description on #60424)
