### PR TITLE
Do not leak type variables from opaque type relation

### LINKED ISSUE #99914: ICE: index out of bounds: the len is 323 but the index is 324, ena-0.14.0/src/snapshot_vec.rs:199:10
### Code

This was in a closed source codebase I don't have time to minimize right now. It happened when I called `.unwrap_or_else()` (or something like that, don't exactly remember) on a value with type `impl Future<Output = Result<T, E>>`. Don't remember what T or E were :(

### Meta

`rustc --version --verbose`:
```
rustc 1.64.0-nightly (2643b1646 2022-07-27)
```

### Error output

```
thread 'rustc' panicked at 'index out of bounds: the len is 323 but the index is 324', /cargo/registry/src/github.com-1ecc6299db9ec823/ena-0.14.0/src/snapshot_vec.rs:199:10
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
thread 'rustc' panicked at 'index out of bounds: the len is 323 but the index is 324', /cargo/registry/src/github.com-1ecc6299db9ec823/ena-0.14.0/src/snapshot_vec.rs:199:10
stack backtrace:
   0:     0x7fb84c72a2f0 - std::backtrace_rs::backtrace::libunwind::trace::hfde61216c3eb9aa2
                               at /rustc/2643b16468fda787470340890212591d8bc832b7/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   1:     0x7fb84c72a2f0 - std::backtrace_rs::backtrace::trace_unsynchronized::h0b75016d6e62613e
                               at /rustc/2643b16468fda787470340890212591d8bc832b7/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7fb84c72a2f0 - std::sys_common::backtrace::_print_fmt::hb881989378b0427a
                               at /rustc/2643b16468fda787470340890212591d8bc832b7/library/std/src/sys_common/backtrace.rs:66:5
   3:     0x7fb84c72a2f0 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hd3d0d57171db7305
                               at /rustc/2643b16468fda787470340890212591d8bc832b7/library/std/src/sys_common/backtrace.rs:45:22
   4:     0x7fb84c78570c - core::fmt::write::h27d3752df3a82c58
                               at /rustc/2643b16468fda787470340890212591d8bc832b7/library/core/src/fmt/mod.rs:1198:17
   5:     0x7fb84c71b325 - std::io::Write::write_fmt::h5c80c98739fc77ee
                               at /rustc/2643b16468fda787470340890212591d8bc832b7/library/std/src/io/mod.rs:1672:15
   6:     0x7fb84c72cfc1 - std::sys_common::backtrace::_print::haae4b9f0159881ee
                               at /rustc/2643b16468fda787470340890212591d8bc832b7/library/std/src/sys_common/backtrace.rs:48:5
   7:     0x7fb84c72cfc1 - std::sys_common::backtrace::print::h2ee3dba2d51e8a7c
                               at /rustc/2643b16468fda787470340890212591d8bc832b7/library/std/src/sys_common/backtrace.rs:35:9
   8:     0x7fb84c72cfc1 - std::panicking::default_hook::{{closure}}::h1b241d9ed5d4bf62
                               at /rustc/2643b16468fda787470340890212591d8bc832b7/library/std/src/panicking.rs:295:22
   9:     0x7fb84c72cc93 - std::panicking::default_hook::hbfcb9dc844ea015d
                               at /rustc/2643b16468fda787470340890212591d8bc832b7/library/std/src/panicking.rs:314:9
  10:     0x7fb84ef01114 - rustc_driver[65b554bd076cf949]::DEFAULT_HOOK::{closure#0}::{closure#0}
  11:     0x7fb84c72d7f6 - std::panicking::rust_panic_with_hook::ha922eb0926dfacd1
                               at /rustc/2643b16468fda787470340890212591d8bc832b7/library/std/src/panicking.rs:702:17
  12:     0x7fb84c72d647 - std::panicking::begin_panic_handler::{{closure}}::h755221379ec8b759
                               at /rustc/2643b16468fda787470340890212591d8bc832b7/library/std/src/panicking.rs:588:13
  13:     0x7fb84c72a814 - std::sys_common::backtrace::__rust_end_short_backtrace::hdaef891366623f57
                               at /rustc/2643b16468fda787470340890212591d8bc832b7/library/std/src/sys_common/backtrace.rs:138:18
  14:     0x7fb84c72d372 - rust_begin_unwind
                               at /rustc/2643b16468fda787470340890212591d8bc832b7/library/std/src/panicking.rs:584:5
  15:     0x7fb84c7821e3 - core::panicking::panic_fmt::hb3e01db1bb39d23b
                               at /rustc/2643b16468fda787470340890212591d8bc832b7/library/core/src/panicking.rs:142:14
  16:     0x7fb84c782122 - core::panicking::panic_bounds_check::hfa135c33a77c9e3c
                               at /rustc/2643b16468fda787470340890212591d8bc832b7/library/core/src/panicking.rs:84:5
  17:     0x7fb84d8502db - <&rustc_middle[bd19c556bfbde64d]::ty::list::List<rustc_middle[bd19c556bfbde64d]::ty::subst::GenericArg> as rustc_middle[bd19c556bfbde64d]::ty::fold::TypeFoldable>::try_fold_with::<rustc_infer[9fb44eec1c8d58c7]::infer::resolve::OpportunisticVarResolver>
  18:     0x7fb84d84f10d - <rustc_infer[9fb44eec1c8d58c7]::infer::resolve::OpportunisticVarResolver as rustc_middle[bd19c556bfbde64d]::ty::fold::FallibleTypeFolder>::try_fold_ty
  19:     0x7fb84fd4e7d6 - <(rustc_middle[bd19c556bfbde64d]::ty::Ty, rustc_middle[bd19c556bfbde64d]::ty::Ty) as rustc_middle[bd19c556bfbde64d]::ty::fold::TypeFoldable>::fold_with::<rustc_infer[9fb44eec1c8d58c7]::infer::resolve::OpportunisticVarResolver>
  20:     0x7fb84fd4153f - <rustc_infer[9fb44eec1c8d58c7]::infer::InferCtxt>::same_type_modulo_infer
  21:     0x7fb84fd46ab2 - <rustc_infer[9fb44eec1c8d58c7]::infer::InferCtxt>::note_type_err
  22:     0x7fb84fd3d3c7 - <rustc_infer[9fb44eec1c8d58c7]::infer::InferCtxt>::report_and_explain_type_error
  23:     0x7fb84da7d44b - <rustc_infer[9fb44eec1c8d58c7]::infer::InferCtxt>::report_mismatched_types
  24:     0x7fb84f350641 - <rustc_typeck[664e6494d36bc9f9]::check::coercion::CoerceMany<&rustc_hir[e63fe2e2ba61df9e]::hir::Expr>>::report_return_mismatched_types
  25:     0x7fb84da40ad5 - <rustc_typeck[664e6494d36bc9f9]::check::coercion::CoerceMany<&rustc_hir[e63fe2e2ba61df9e]::hir::Expr>>::coerce
  26:     0x7fb84dd75752 - rustc_typeck[664e6494d36bc9f9]::check::check::check_fn
  27:     0x7fb84daa087a - <rustc_typeck[664e6494d36bc9f9]::check::fn_ctxt::FnCtxt>::check_expr_closure
  28:     0x7fb84da347a3 - <rustc_typeck[664e6494d36bc9f9]::check::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
  29:     0x7fb84da2bd3f - <rustc_typeck[664e6494d36bc9f9]::check::fn_ctxt::FnCtxt>::check_argument_types
  30:     0x7fb84da3304c - <rustc_typeck[664e6494d36bc9f9]::check::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
  31:     0x7fb84da2bd3f - <rustc_typeck[664e6494d36bc9f9]::check::fn_ctxt::FnCtxt>::check_argument_types
  32:     0x7fb84d9e5b7e - <rustc_typeck[664e6494d36bc9f9]::check::fn_ctxt::FnCtxt>::check_call
  33:     0x7fb84da31b69 - <rustc_typeck[664e6494d36bc9f9]::check::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
  34:     0x7fb84da704ac - <rustc_typeck[664e6494d36bc9f9]::check::fn_ctxt::FnCtxt>::check_match
  35:     0x7fb84da33244 - <rustc_typeck[664e6494d36bc9f9]::check::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
  36:     0x7fb84da659a1 - <rustc_typeck[664e6494d36bc9f9]::check::fn_ctxt::FnCtxt>::check_decl
  37:     0x7fb84da3527b - <rustc_typeck[664e6494d36bc9f9]::check::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
  38:     0x7fb84da334cc - <rustc_typeck[664e6494d36bc9f9]::check::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
  39:     0x7fb84da4423e - <rustc_typeck[664e6494d36bc9f9]::check::fn_ctxt::FnCtxt>::check_block_with_expected
  40:     0x7fb84da31c96 - <rustc_typeck[664e6494d36bc9f9]::check::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
  41:     0x7fb84dd7566e - rustc_typeck[664e6494d36bc9f9]::check::check::check_fn
  42:     0x7fb84daa087a - <rustc_typeck[664e6494d36bc9f9]::check::fn_ctxt::FnCtxt>::check_expr_closure
  43:     0x7fb84da347a3 - <rustc_typeck[664e6494d36bc9f9]::check::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
  44:     0x7fb84da2bd3f - <rustc_typeck[664e6494d36bc9f9]::check::fn_ctxt::FnCtxt>::check_argument_types
  45:     0x7fb84d9e5b7e - <rustc_typeck[664e6494d36bc9f9]::check::fn_ctxt::FnCtxt>::check_call
  46:     0x7fb84da31b69 - <rustc_typeck[664e6494d36bc9f9]::check::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
  47:     0x7fb84da2bd3f - <rustc_typeck[664e6494d36bc9f9]::check::fn_ctxt::FnCtxt>::check_argument_types
  48:     0x7fb84d9e5b7e - <rustc_typeck[664e6494d36bc9f9]::check::fn_ctxt::FnCtxt>::check_call
  49:     0x7fb84da31b69 - <rustc_typeck[664e6494d36bc9f9]::check::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
  50:     0x7fb84da44033 - <rustc_typeck[664e6494d36bc9f9]::check::fn_ctxt::FnCtxt>::check_block_with_expected
  51:     0x7fb84da31c96 - <rustc_typeck[664e6494d36bc9f9]::check::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
  52:     0x7fb84dd7566e - rustc_typeck[664e6494d36bc9f9]::check::check::check_fn
  53:     0x7fb84daa087a - <rustc_typeck[664e6494d36bc9f9]::check::fn_ctxt::FnCtxt>::check_expr_closure
  54:     0x7fb84da347a3 - <rustc_typeck[664e6494d36bc9f9]::check::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
  55:     0x7fb84da2bd3f - <rustc_typeck[664e6494d36bc9f9]::check::fn_ctxt::FnCtxt>::check_argument_types
  56:     0x7fb84da3304c - <rustc_typeck[664e6494d36bc9f9]::check::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
  57:     0x7fb84da2bd3f - <rustc_typeck[664e6494d36bc9f9]::check::fn_ctxt::FnCtxt>::check_argument_types
  58:     0x7fb84d9e5b7e - <rustc_typeck[664e6494d36bc9f9]::check::fn_ctxt::FnCtxt>::check_call
  59:     0x7fb84da31b69 - <rustc_typeck[664e6494d36bc9f9]::check::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
  60:     0x7fb84da704ac - <rustc_typeck[664e6494d36bc9f9]::check::fn_ctxt::FnCtxt>::check_match
  61:     0x7fb84da33244 - <rustc_typeck[664e6494d36bc9f9]::check::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
  62:     0x7fb84da4423e - <rustc_typeck[664e6494d36bc9f9]::check::fn_ctxt::FnCtxt>::check_block_with_expected
  63:     0x7fb84da31c96 - <rustc_typeck[664e6494d36bc9f9]::check::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
  64:     0x7fb84da337a8 - <rustc_typeck[664e6494d36bc9f9]::check::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
  65:     0x7fb84da4423e - <rustc_typeck[664e6494d36bc9f9]::check::fn_ctxt::FnCtxt>::check_block_with_expected
  66:     0x7fb84da31c96 - <rustc_typeck[664e6494d36bc9f9]::check::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
  67:     0x7fb84dd7566e - rustc_typeck[664e6494d36bc9f9]::check::check::check_fn
  68:     0x7fb84daa087a - <rustc_typeck[664e6494d36bc9f9]::check::fn_ctxt::FnCtxt>::check_expr_closure
  69:     0x7fb84da347a3 - <rustc_typeck[664e6494d36bc9f9]::check::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
  70:     0x7fb84da2bd3f - <rustc_typeck[664e6494d36bc9f9]::check::fn_ctxt::FnCtxt>::check_argument_types
  71:     0x7fb84d9e5b7e - <rustc_typeck[664e6494d36bc9f9]::check::fn_ctxt::FnCtxt>::check_call
  72:     0x7fb84da31b69 - <rustc_typeck[664e6494d36bc9f9]::check::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
  73:     0x7fb84dd7566e - rustc_typeck[664e6494d36bc9f9]::check::check::check_fn
  74:     0x7fb84dd63147 - <rustc_infer[9fb44eec1c8d58c7]::infer::InferCtxtBuilder>::enter::<&rustc_middle[bd19c556bfbde64d]::ty::context::TypeckResults, <rustc_typeck[664e6494d36bc9f9]::check::inherited::InheritedBuilder>::enter<rustc_typeck[664e6494d36bc9f9]::check::typeck_with_fallback<rustc_typeck[664e6494d36bc9f9]::check::typeck::{closure#0}>::{closure#1}, &rustc_middle[bd19c556bfbde64d]::ty::context::TypeckResults>::{closure#0}>
  75:     0x7fb84e926ec6 - rustc_typeck[664e6494d36bc9f9]::check::typeck
  76:     0x7fb84e53406f - <rustc_query_system[8afb442a6454b51e]::dep_graph::graph::DepGraph<rustc_middle[bd19c556bfbde64d]::dep_graph::dep_node::DepKind>>::with_task::<rustc_middle[bd19c556bfbde64d]::ty::context::TyCtxt, rustc_span[c9cc50052627be11]::def_id::LocalDefId, &rustc_middle[bd19c556bfbde64d]::ty::context::TypeckResults>
  77:     0x7fb84e52c40a - rustc_query_system[8afb442a6454b51e]::query::plumbing::try_execute_query::<rustc_query_impl[7b7d1ce597391f7c]::plumbing::QueryCtxt, rustc_query_system[8afb442a6454b51e]::query::caches::DefaultCache<rustc_span[c9cc50052627be11]::def_id::LocalDefId, &rustc_middle[bd19c556bfbde64d]::ty::context::TypeckResults>>
  78:     0x7fb84eb6eff6 - rustc_query_system[8afb442a6454b51e]::query::plumbing::force_query::<rustc_query_impl[7b7d1ce597391f7c]::queries::typeck, rustc_query_impl[7b7d1ce597391f7c]::plumbing::QueryCtxt>
  79:     0x7fb84eb6ee3e - rustc_query_impl[7b7d1ce597391f7c]::query_callbacks::typeck::force_from_dep_node
  80:     0x7fb84d97bfe1 - <rustc_middle[bd19c556bfbde64d]::ty::context::TyCtxt as rustc_query_system[8afb442a6454b51e]::dep_graph::DepContext>::try_force_from_dep_node
  81:     0x7fb84d97b54a - <rustc_query_system[8afb442a6454b51e]::dep_graph::graph::DepGraph<rustc_middle[bd19c556bfbde64d]::dep_graph::dep_node::DepKind>>::try_mark_previous_green::<rustc_query_impl[7b7d1ce597391f7c]::plumbing::QueryCtxt>
  82:     0x7fb84d97adc6 - <rustc_query_system[8afb442a6454b51e]::dep_graph::graph::DepGraph<rustc_middle[bd19c556bfbde64d]::dep_graph::dep_node::DepKind>>::try_mark_previous_green::<rustc_query_impl[7b7d1ce597391f7c]::plumbing::QueryCtxt>
  83:     0x7fb84d97adc6 - <rustc_query_system[8afb442a6454b51e]::dep_graph::graph::DepGraph<rustc_middle[bd19c556bfbde64d]::dep_graph::dep_node::DepKind>>::try_mark_previous_green::<rustc_query_impl[7b7d1ce597391f7c]::plumbing::QueryCtxt>
  84:     0x7fb84d97adc6 - <rustc_query_system[8afb442a6454b51e]::dep_graph::graph::DepGraph<rustc_middle[bd19c556bfbde64d]::dep_graph::dep_node::DepKind>>::try_mark_previous_green::<rustc_query_impl[7b7d1ce597391f7c]::plumbing::QueryCtxt>
  85:     0x7fb84d97adc6 - <rustc_query_system[8afb442a6454b51e]::dep_graph::graph::DepGraph<rustc_middle[bd19c556bfbde64d]::dep_graph::dep_node::DepKind>>::try_mark_previous_green::<rustc_query_impl[7b7d1ce597391f7c]::plumbing::QueryCtxt>
  86:     0x7fb84d97adc6 - <rustc_query_system[8afb442a6454b51e]::dep_graph::graph::DepGraph<rustc_middle[bd19c556bfbde64d]::dep_graph::dep_node::DepKind>>::try_mark_previous_green::<rustc_query_impl[7b7d1ce597391f7c]::plumbing::QueryCtxt>
  87:     0x7fb84e3846e7 - rustc_query_system[8afb442a6454b51e]::query::plumbing::get_query::<rustc_query_impl[7b7d1ce597391f7c]::queries::type_of, rustc_query_impl[7b7d1ce597391f7c]::plumbing::QueryCtxt>
  88:     0x7fb84e828b98 - rustc_typeck[664e6494d36bc9f9]::check::check::check_item_type
  89:     0x7fb84e82505e - rustc_typeck[664e6494d36bc9f9]::check::check::check_mod_item_types
  90:     0x7fb84e1f5642 - <rustc_query_system[8afb442a6454b51e]::dep_graph::graph::DepGraph<rustc_middle[bd19c556bfbde64d]::dep_graph::dep_node::DepKind>>::with_task::<rustc_middle[bd19c556bfbde64d]::ty::context::TyCtxt, rustc_span[c9cc50052627be11]::def_id::LocalDefId, ()>
  91:     0x7fb84e1f47ce - rustc_query_system[8afb442a6454b51e]::query::plumbing::try_execute_query::<rustc_query_impl[7b7d1ce597391f7c]::plumbing::QueryCtxt, rustc_query_system[8afb442a6454b51e]::query::caches::DefaultCache<rustc_span[c9cc50052627be11]::def_id::LocalDefId, ()>>
  92:     0x7fb84e96df43 - rustc_query_system[8afb442a6454b51e]::query::plumbing::get_query::<rustc_query_impl[7b7d1ce597391f7c]::queries::check_mod_item_types, rustc_query_impl[7b7d1ce597391f7c]::plumbing::QueryCtxt>
  93:     0x7fb84ec0e0ef - <rustc_middle[bd19c556bfbde64d]::hir::map::Map>::for_each_module::<rustc_typeck[664e6494d36bc9f9]::check_crate::{closure#6}::{closure#0}>
  94:     0x7fb84e8eb795 - rustc_typeck[664e6494d36bc9f9]::check_crate
  95:     0x7fb84e8ead67 - rustc_interface[6c4ed5f5bcefca51]::passes::analysis
  96:     0x7fb84ecc273c - <rustc_query_system[8afb442a6454b51e]::dep_graph::graph::DepGraph<rustc_middle[bd19c556bfbde64d]::dep_graph::dep_node::DepKind>>::with_task::<rustc_middle[bd19c556bfbde64d]::ty::context::TyCtxt, (), core[985efce893a97efa]::result::Result<(), rustc_errors[4b4dc7f65bce4740]::ErrorGuaranteed>>
  97:     0x7fb84ecc1efb - rustc_query_system[8afb442a6454b51e]::query::plumbing::try_execute_query::<rustc_query_impl[7b7d1ce597391f7c]::plumbing::QueryCtxt, rustc_query_system[8afb442a6454b51e]::query::caches::DefaultCache<(), core[985efce893a97efa]::result::Result<(), rustc_errors[4b4dc7f65bce4740]::ErrorGuaranteed>>>
  98:     0x7fb84ecc1a4e - rustc_query_system[8afb442a6454b51e]::query::plumbing::get_query::<rustc_query_impl[7b7d1ce597391f7c]::queries::analysis, rustc_query_impl[7b7d1ce597391f7c]::plumbing::QueryCtxt>
  99:     0x7fb84e68ec5e - <rustc_interface[6c4ed5f5bcefca51]::passes::QueryContext>::enter::<rustc_driver[65b554bd076cf949]::run_compiler::{closure#1}::{closure#2}::{closure#3}, core[985efce893a97efa]::result::Result<(), rustc_errors[4b4dc7f65bce4740]::ErrorGuaranteed>>
 100:     0x7fb84e68908e - <rustc_interface[6c4ed5f5bcefca51]::interface::Compiler>::enter::<rustc_driver[65b554bd076cf949]::run_compiler::{closure#1}::{closure#2}, core[985efce893a97efa]::result::Result<core[985efce893a97efa]::option::Option<rustc_interface[6c4ed5f5bcefca51]::queries::Linker>, rustc_errors[4b4dc7f65bce4740]::ErrorGuaranteed>>
 101:     0x7fb84e6849da - rustc_span[c9cc50052627be11]::with_source_map::<core[985efce893a97efa]::result::Result<(), rustc_errors[4b4dc7f65bce4740]::ErrorGuaranteed>, rustc_interface[6c4ed5f5bcefca51]::interface::create_compiler_and_run<core[985efce893a97efa]::result::Result<(), rustc_errors[4b4dc7f65bce4740]::ErrorGuaranteed>, rustc_driver[65b554bd076cf949]::run_compiler::{closure#1}>::{closure#1}>
 102:     0x7fb84e684430 - rustc_interface[6c4ed5f5bcefca51]::interface::create_compiler_and_run::<core[985efce893a97efa]::result::Result<(), rustc_errors[4b4dc7f65bce4740]::ErrorGuaranteed>, rustc_driver[65b554bd076cf949]::run_compiler::{closure#1}>
 103:     0x7fb84e6826e2 - <scoped_tls[c96fdd959bf6d57b]::ScopedKey<rustc_span[c9cc50052627be11]::SessionGlobals>>::set::<rustc_interface[6c4ed5f5bcefca51]::interface::run_compiler<core[985efce893a97efa]::result::Result<(), rustc_errors[4b4dc7f65bce4740]::ErrorGuaranteed>, rustc_driver[65b554bd076cf949]::run_compiler::{closure#1}>::{closure#0}, core[985efce893a97efa]::result::Result<(), rustc_errors[4b4dc7f65bce4740]::ErrorGuaranteed>>
 104:     0x7fb84e6823cf - std[7b29f0aeec6d7a3b]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[6c4ed5f5bcefca51]::util::run_in_thread_pool_with_globals<rustc_interface[6c4ed5f5bcefca51]::interface::run_compiler<core[985efce893a97efa]::result::Result<(), rustc_errors[4b4dc7f65bce4740]::ErrorGuaranteed>, rustc_driver[65b554bd076cf949]::run_compiler::{closure#1}>::{closure#0}, core[985efce893a97efa]::result::Result<(), rustc_errors[4b4dc7f65bce4740]::ErrorGuaranteed>>::{closure#0}, core[985efce893a97efa]::result::Result<(), rustc_errors[4b4dc7f65bce4740]::ErrorGuaranteed>>
 105:     0x7fb84ed3f239 - <<std[7b29f0aeec6d7a3b]::thread::Builder>::spawn_unchecked_<rustc_interface[6c4ed5f5bcefca51]::util::run_in_thread_pool_with_globals<rustc_interface[6c4ed5f5bcefca51]::interface::run_compiler<core[985efce893a97efa]::result::Result<(), rustc_errors[4b4dc7f65bce4740]::ErrorGuaranteed>, rustc_driver[65b554bd076cf949]::run_compiler::{closure#1}>::{closure#0}, core[985efce893a97efa]::result::Result<(), rustc_errors[4b4dc7f65bce4740]::ErrorGuaranteed>>::{closure#0}, core[985efce893a97efa]::result::Result<(), rustc_errors[4b4dc7f65bce4740]::ErrorGuaranteed>>::{closure#1} as core[985efce893a97efa]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
 106:     0x7fb84c737293 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h5b4844b306fb76ba
                               at /rustc/2643b16468fda787470340890212591d8bc832b7/library/alloc/src/boxed.rs:1935:9
 107:     0x7fb84c737293 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h90126c2a440b419a
                               at /rustc/2643b16468fda787470340890212591d8bc832b7/library/alloc/src/boxed.rs:1935:9
 108:     0x7fb84c737293 - std::sys::unix::thread::Thread::new::thread_start::hfc37efb2513bd228
                               at /rustc/2643b16468fda787470340890212591d8bc832b7/library/std/src/sys/unix/thread.rs:108:17
 109:     0x7fb84c5f0609 - start_thread
                               at /build/glibc-SzIz7B/glibc-2.31/nptl/pthread_create.c:477:8
 110:     0x7fb84c513133 - clone
                               at /build/glibc-SzIz7B/glibc-2.31/misc/../sysdeps/unix/sysv/linux/x86_64/clone.S:95
 111:                0x0 - <unknown>

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.64.0-nightly (2643b1646 2022-07-27) running on x86_64-unknown-linux-gnu

note: compiler flags: --crate-type lib -C embed-bitcode=no -C debuginfo=2 -C incremental

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [typeck] type-checking `endpoints::serve::serve_udp`
#1 [type_of] computing type of `endpoints::serve::serve_udp::{opaque#0}`
#2 [check_mod_item_types] checking item types in module `endpoints::serve`
#3 [analysis] running analysis passes on this crate
end of query stack
```

</p>
</details>

### LINKED ISSUE #99970: ICE: index out of bounds: the len is 53 but the index is 54
### Code

I have this exact function in my code:

```Rust
    pub fn get_room_users(&self, uuid: Uuid) -> Result<HashMap<Uuid, UserDisplay>, FetchRoomError> {

    }
```

When I run `cargo check`, it prints the correct `mismatched types` compiler error.

However, when I made the function `async`:

```Rust
    pub async fn get_room_users(&self, uuid: Uuid) -> Result<HashMap<Uuid, UserDisplay>, FetchRoomError> {

    }
```

`cargo check` produces, apparently, two internal errors, shown below.

I can provide additional information if needed.

### Meta

`rustc --version --verbose`:
```
rustc 1.64.0-nightly (3924dac7b 2022-07-29)
binary: rustc
commit-hash: 3924dac7bb29bc8eb348059c901e8f912399c857
commit-date: 2022-07-29
host: x86_64-unknown-linux-gnu
release: 1.64.0-nightly
LLVM version: 14.0.6
```

### Error output

```
(error 1): thread 'rustc' panicked at 'index out of bounds: the len is 53 but the index is 54', /cargo/registry/src/github.com-1ecc6299db9ec823/ena-0.14.0/src/snapshot_vec.rs:199:10
(error 2): thread 'rustc' panicked at 'Box<dyn Any>', compiler/rustc_errors/src/lib.rs:1426:13
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
thread 'rustc' panicked at 'index out of bounds: the len is 53 but the index is 54', /cargo/registry/src/github.com-1ecc6299db9ec823/ena-0.14.0/src/snapshot_vec.rs:199:10
stack backtrace:
   0:     0x7feb2f732300 - std::backtrace_rs::backtrace::libunwind::trace::h6ddc9f9c210496ff
                               at /rustc/3924dac7bb29bc8eb348059c901e8f912399c857/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   1:     0x7feb2f732300 - std::backtrace_rs::backtrace::trace_unsynchronized::h9e468e888e8d9720
                               at /rustc/3924dac7bb29bc8eb348059c901e8f912399c857/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7feb2f732300 - std::sys_common::backtrace::_print_fmt::hd1881e9a19369fc2
                               at /rustc/3924dac7bb29bc8eb348059c901e8f912399c857/library/std/src/sys_common/backtrace.rs:66:5
   3:     0x7feb2f732300 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hc760c80094d12d0b
                               at /rustc/3924dac7bb29bc8eb348059c901e8f912399c857/library/std/src/sys_common/backtrace.rs:45:22
   4:     0x7feb2f78d71c - core::fmt::write::h9fa2d54393b34210
                               at /rustc/3924dac7bb29bc8eb348059c901e8f912399c857/library/core/src/fmt/mod.rs:1198:17
   5:     0x7feb2f723325 - std::io::Write::write_fmt::h6cb3511bb78b07fc
                               at /rustc/3924dac7bb29bc8eb348059c901e8f912399c857/library/std/src/io/mod.rs:1672:15
   6:     0x7feb2f734fd1 - std::sys_common::backtrace::_print::h82007c152e8a20f6
                               at /rustc/3924dac7bb29bc8eb348059c901e8f912399c857/library/std/src/sys_common/backtrace.rs:48:5
   7:     0x7feb2f734fd1 - std::sys_common::backtrace::print::hfd39d026c8fd7dc2
                               at /rustc/3924dac7bb29bc8eb348059c901e8f912399c857/library/std/src/sys_common/backtrace.rs:35:9
   8:     0x7feb2f734fd1 - std::panicking::default_hook::{{closure}}::h1d5c56ed0d43c6d2
                               at /rustc/3924dac7bb29bc8eb348059c901e8f912399c857/library/std/src/panicking.rs:295:22
   9:     0x7feb2f734ca3 - std::panicking::default_hook::hbd4b8c74f6bf2a75
                               at /rustc/3924dac7bb29bc8eb348059c901e8f912399c857/library/std/src/panicking.rs:314:9
  10:     0x7feb31f0b474 - rustc_driver[2f40008e0c6ae48d]::DEFAULT_HOOK::{closure#0}::{closure#0}
  11:     0x7feb2f735806 - std::panicking::rust_panic_with_hook::h1677c7be7e0853f1
                               at /rustc/3924dac7bb29bc8eb348059c901e8f912399c857/library/std/src/panicking.rs:702:17
  12:     0x7feb2f735657 - std::panicking::begin_panic_handler::{{closure}}::h76fcac37b48c7869
                               at /rustc/3924dac7bb29bc8eb348059c901e8f912399c857/library/std/src/panicking.rs:588:13
  13:     0x7feb2f732824 - std::sys_common::backtrace::__rust_end_short_backtrace::h6a9e5a007b51de2f
                               at /rustc/3924dac7bb29bc8eb348059c901e8f912399c857/library/std/src/sys_common/backtrace.rs:138:18
  14:     0x7feb2f735382 - rust_begin_unwind
                               at /rustc/3924dac7bb29bc8eb348059c901e8f912399c857/library/std/src/panicking.rs:584:5
  15:     0x7feb2f78a1f3 - core::panicking::panic_fmt::h90badf56b3321f8c
                               at /rustc/3924dac7bb29bc8eb348059c901e8f912399c857/library/core/src/panicking.rs:142:14
  16:     0x7feb2f78a132 - core::panicking::panic_bounds_check::h6c0973ef11d25713
                               at /rustc/3924dac7bb29bc8eb348059c901e8f912399c857/library/core/src/panicking.rs:84:5
  17:     0x7feb30859618 - <rustc_infer[d65445394da8795b]::infer::ShallowResolver as rustc_middle[b0361dc3b46faa41]::ty::fold::TypeFolder>::fold_ty
  18:     0x7feb3085938e - <rustc_infer[d65445394da8795b]::infer::InferCtxt>::shallow_resolve::<rustc_middle[b0361dc3b46faa41]::ty::Ty>
  19:     0x7feb3085926b - <&rustc_middle[b0361dc3b46faa41]::ty::list::List<rustc_middle[b0361dc3b46faa41]::ty::subst::GenericArg> as rustc_middle[b0361dc3b46faa41]::ty::fold::TypeFoldable>::try_fold_with::<rustc_infer[d65445394da8795b]::infer::resolve::OpportunisticVarResolver>
  20:     0x7feb3085893d - <rustc_infer[d65445394da8795b]::infer::resolve::OpportunisticVarResolver as rustc_middle[b0361dc3b46faa41]::ty::fold::FallibleTypeFolder>::try_fold_ty
  21:     0x7feb32d5e096 - <(rustc_middle[b0361dc3b46faa41]::ty::Ty, rustc_middle[b0361dc3b46faa41]::ty::Ty) as rustc_middle[b0361dc3b46faa41]::ty::fold::TypeFoldable>::fold_with::<rustc_infer[d65445394da8795b]::infer::resolve::OpportunisticVarResolver>
  22:     0x7feb32d50a5f - <rustc_infer[d65445394da8795b]::infer::InferCtxt>::same_type_modulo_infer
  23:     0x7feb32d55fd2 - <rustc_infer[d65445394da8795b]::infer::InferCtxt>::note_type_err
  24:     0x7feb32d4c8e7 - <rustc_infer[d65445394da8795b]::infer::InferCtxt>::report_and_explain_type_error
  25:     0x7feb3225404d - <rustc_typeck[3a6a9adc157696d2]::check::fn_ctxt::FnCtxt>::report_arg_errors
  26:     0x7feb30a2ca85 - <rustc_typeck[3a6a9adc157696d2]::check::fn_ctxt::FnCtxt>::check_argument_types
  27:     0x7feb309e27e3 - <rustc_typeck[3a6a9adc157696d2]::check::fn_ctxt::FnCtxt>::check_call
  28:     0x7feb30a2f488 - <rustc_typeck[3a6a9adc157696d2]::check::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
  29:     0x7feb30a415de - <rustc_typeck[3a6a9adc157696d2]::check::fn_ctxt::FnCtxt>::check_block_with_expected
  30:     0x7feb30a2f5f6 - <rustc_typeck[3a6a9adc157696d2]::check::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
  31:     0x7feb30a31108 - <rustc_typeck[3a6a9adc157696d2]::check::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
  32:     0x7feb30a415de - <rustc_typeck[3a6a9adc157696d2]::check::fn_ctxt::FnCtxt>::check_block_with_expected
  33:     0x7feb30a2f5f6 - <rustc_typeck[3a6a9adc157696d2]::check::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
  34:     0x7feb3101ed5e - rustc_typeck[3a6a9adc157696d2]::check::check::check_fn
  35:     0x7feb30a9edce - <rustc_typeck[3a6a9adc157696d2]::check::fn_ctxt::FnCtxt>::check_expr_closure
  36:     0x7feb30a32103 - <rustc_typeck[3a6a9adc157696d2]::check::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
  37:     0x7feb30a2968f - <rustc_typeck[3a6a9adc157696d2]::check::fn_ctxt::FnCtxt>::check_argument_types
  38:     0x7feb309e27e3 - <rustc_typeck[3a6a9adc157696d2]::check::fn_ctxt::FnCtxt>::check_call
  39:     0x7feb30a2f488 - <rustc_typeck[3a6a9adc157696d2]::check::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
  40:     0x7feb3101ed5e - rustc_typeck[3a6a9adc157696d2]::check::check::check_fn
  41:     0x7feb3100dce8 - <rustc_infer[d65445394da8795b]::infer::InferCtxtBuilder>::enter::<&rustc_middle[b0361dc3b46faa41]::ty::context::TypeckResults, <rustc_typeck[3a6a9adc157696d2]::check::inherited::InheritedBuilder>::enter<rustc_typeck[3a6a9adc157696d2]::check::typeck_with_fallback<rustc_typeck[3a6a9adc157696d2]::check::typeck::{closure#0}>::{closure#1}, &rustc_middle[b0361dc3b46faa41]::ty::context::TypeckResults>::{closure#0}>
  42:     0x7feb319351b6 - rustc_typeck[3a6a9adc157696d2]::check::typeck
  43:     0x7feb3153f87f - <rustc_query_system[c5b4090de70f61eb]::dep_graph::graph::DepGraph<rustc_middle[b0361dc3b46faa41]::dep_graph::dep_node::DepKind>>::with_task::<rustc_middle[b0361dc3b46faa41]::ty::context::TyCtxt, rustc_span[b55e3ed1d80ca2e1]::def_id::LocalDefId, &rustc_middle[b0361dc3b46faa41]::ty::context::TypeckResults>
  44:     0x7feb31537c1a - rustc_query_system[c5b4090de70f61eb]::query::plumbing::try_execute_query::<rustc_query_impl[6ebad19704c173d0]::plumbing::QueryCtxt, rustc_query_system[c5b4090de70f61eb]::query::caches::DefaultCache<rustc_span[b55e3ed1d80ca2e1]::def_id::LocalDefId, &rustc_middle[b0361dc3b46faa41]::ty::context::TypeckResults>>
  45:     0x7feb31e19688 - <rustc_query_impl[6ebad19704c173d0]::Queries as rustc_middle[b0361dc3b46faa41]::ty::query::QueryEngine>::typeck
  46:     0x7feb314e45a5 - <rustc_middle[b0361dc3b46faa41]::ty::context::TyCtxt>::typeck_opt_const_arg
  47:     0x7feb314e3055 - rustc_mir_build[b92cc536c41b166e]::build::mir_built
  48:     0x7feb3138206c - <rustc_query_system[c5b4090de70f61eb]::dep_graph::graph::DepGraph<rustc_middle[b0361dc3b46faa41]::dep_graph::dep_node::DepKind>>::with_task::<rustc_middle[b0361dc3b46faa41]::ty::context::TyCtxt, rustc_middle[b0361dc3b46faa41]::ty::WithOptConstParam<rustc_span[b55e3ed1d80ca2e1]::def_id::LocalDefId>, &rustc_data_structures[319dc9d7210783ce]::steal::Steal<rustc_middle[b0361dc3b46faa41]::mir::Body>>
  49:     0x7feb31380f2e - rustc_query_system[c5b4090de70f61eb]::query::plumbing::try_execute_query::<rustc_query_impl[6ebad19704c173d0]::plumbing::QueryCtxt, rustc_query_system[c5b4090de70f61eb]::query::caches::DefaultCache<rustc_middle[b0361dc3b46faa41]::ty::WithOptConstParam<rustc_span[b55e3ed1d80ca2e1]::def_id::LocalDefId>, &rustc_data_structures[319dc9d7210783ce]::steal::Steal<rustc_middle[b0361dc3b46faa41]::mir::Body>>>
  50:     0x7feb31e18085 - <rustc_query_impl[6ebad19704c173d0]::Queries as rustc_middle[b0361dc3b46faa41]::ty::query::QueryEngine>::mir_built
  51:     0x7feb30f4f780 - rustc_mir_transform[acd891945b11d676]::check_unsafety::unsafety_check_result
  52:     0x7feb30f4f19e - <rustc_mir_transform[acd891945b11d676]::check_unsafety::provide::{closure#0} as core[2e75634dfdf5101e]::ops::function::FnOnce<(rustc_middle[b0361dc3b46faa41]::ty::context::TyCtxt, rustc_span[b55e3ed1d80ca2e1]::def_id::LocalDefId)>>::call_once
  53:     0x7feb3149b43f - <rustc_query_system[c5b4090de70f61eb]::dep_graph::graph::DepGraph<rustc_middle[b0361dc3b46faa41]::dep_graph::dep_node::DepKind>>::with_task::<rustc_middle[b0361dc3b46faa41]::ty::context::TyCtxt, rustc_span[b55e3ed1d80ca2e1]::def_id::LocalDefId, &rustc_middle[b0361dc3b46faa41]::mir::query::UnsafetyCheckResult>
  54:     0x7feb31499baa - rustc_query_system[c5b4090de70f61eb]::query::plumbing::try_execute_query::<rustc_query_impl[6ebad19704c173d0]::plumbing::QueryCtxt, rustc_query_system[c5b4090de70f61eb]::query::caches::DefaultCache<rustc_span[b55e3ed1d80ca2e1]::def_id::LocalDefId, &rustc_middle[b0361dc3b46faa41]::mir::query::UnsafetyCheckResult>>
  55:     0x7feb31e1928e - <rustc_query_impl[6ebad19704c173d0]::Queries as rustc_middle[b0361dc3b46faa41]::ty::query::QueryEngine>::unsafety_check_result
  56:     0x7feb308fd6f0 - rustc_mir_transform[acd891945b11d676]::mir_const
  57:     0x7feb3138206c - <rustc_query_system[c5b4090de70f61eb]::dep_graph::graph::DepGraph<rustc_middle[b0361dc3b46faa41]::dep_graph::dep_node::DepKind>>::with_task::<rustc_middle[b0361dc3b46faa41]::ty::context::TyCtxt, rustc_middle[b0361dc3b46faa41]::ty::WithOptConstParam<rustc_span[b55e3ed1d80ca2e1]::def_id::LocalDefId>, &rustc_data_structures[319dc9d7210783ce]::steal::Steal<rustc_middle[b0361dc3b46faa41]::mir::Body>>
  58:     0x7feb31380f2e - rustc_query_system[c5b4090de70f61eb]::query::plumbing::try_execute_query::<rustc_query_impl[6ebad19704c173d0]::plumbing::QueryCtxt, rustc_query_system[c5b4090de70f61eb]::query::caches::DefaultCache<rustc_middle[b0361dc3b46faa41]::ty::WithOptConstParam<rustc_span[b55e3ed1d80ca2e1]::def_id::LocalDefId>, &rustc_data_structures[319dc9d7210783ce]::steal::Steal<rustc_middle[b0361dc3b46faa41]::mir::Body>>>
  59:     0x7feb31e181bc - <rustc_query_impl[6ebad19704c173d0]::Queries as rustc_middle[b0361dc3b46faa41]::ty::query::QueryEngine>::mir_const
  60:     0x7feb30fa7d9a - rustc_mir_transform[acd891945b11d676]::mir_promoted
  61:     0x7feb318c751c - <rustc_query_system[c5b4090de70f61eb]::dep_graph::graph::DepGraph<rustc_middle[b0361dc3b46faa41]::dep_graph::dep_node::DepKind>>::with_task::<rustc_middle[b0361dc3b46faa41]::ty::context::TyCtxt, rustc_middle[b0361dc3b46faa41]::ty::WithOptConstParam<rustc_span[b55e3ed1d80ca2e1]::def_id::LocalDefId>, (&rustc_data_structures[319dc9d7210783ce]::steal::Steal<rustc_middle[b0361dc3b46faa41]::mir::Body>, &rustc_data_structures[319dc9d7210783ce]::steal::Steal<rustc_index[171b1bc434640498]::vec::IndexVec<rustc_middle[b0361dc3b46faa41]::mir::Promoted, rustc_middle[b0361dc3b46faa41]::mir::Body>>)>
  62:     0x7feb318c632d - rustc_query_system[c5b4090de70f61eb]::query::plumbing::get_query::<rustc_query_impl[6ebad19704c173d0]::queries::mir_promoted, rustc_query_impl[6ebad19704c173d0]::plumbing::QueryCtxt>
  63:     0x7feb318c5907 - <rustc_query_impl[6ebad19704c173d0]::Queries as rustc_middle[b0361dc3b46faa41]::ty::query::QueryEngine>::mir_promoted
  64:     0x7feb31879def - rustc_borrowck[115c609014f28a88]::mir_borrowck
  65:     0x7feb318798fe - <rustc_borrowck[115c609014f28a88]::provide::{closure#0} as core[2e75634dfdf5101e]::ops::function::FnOnce<(rustc_middle[b0361dc3b46faa41]::ty::context::TyCtxt, rustc_span[b55e3ed1d80ca2e1]::def_id::LocalDefId)>>::call_once
  66:     0x7feb31334d7f - <rustc_query_system[c5b4090de70f61eb]::dep_graph::graph::DepGraph<rustc_middle[b0361dc3b46faa41]::dep_graph::dep_node::DepKind>>::with_task::<rustc_middle[b0361dc3b46faa41]::ty::context::TyCtxt, rustc_span[b55e3ed1d80ca2e1]::def_id::LocalDefId, &rustc_middle[b0361dc3b46faa41]::mir::query::BorrowCheckResult>
  67:     0x7feb31334034 - rustc_query_system[c5b4090de70f61eb]::query::plumbing::try_execute_query::<rustc_query_impl[6ebad19704c173d0]::plumbing::QueryCtxt, rustc_query_system[c5b4090de70f61eb]::query::caches::DefaultCache<rustc_span[b55e3ed1d80ca2e1]::def_id::LocalDefId, &rustc_middle[b0361dc3b46faa41]::mir::query::BorrowCheckResult>>
  68:     0x7feb31e198fa - <rustc_query_impl[6ebad19704c173d0]::Queries as rustc_middle[b0361dc3b46faa41]::ty::query::QueryEngine>::mir_borrowck
  69:     0x7feb31cfc382 - rustc_typeck[3a6a9adc157696d2]::collect::type_of::type_of
  70:     0x7feb3138f593 - <rustc_query_system[c5b4090de70f61eb]::dep_graph::graph::DepGraph<rustc_middle[b0361dc3b46faa41]::dep_graph::dep_node::DepKind>>::with_task::<rustc_middle[b0361dc3b46faa41]::ty::context::TyCtxt, rustc_span[b55e3ed1d80ca2e1]::def_id::DefId, rustc_middle[b0361dc3b46faa41]::ty::Ty>
  71:     0x7feb3138d59b - rustc_query_system[c5b4090de70f61eb]::query::plumbing::get_query::<rustc_query_impl[6ebad19704c173d0]::queries::type_of, rustc_query_impl[6ebad19704c173d0]::plumbing::QueryCtxt>
  72:     0x7feb318dcdc8 - rustc_typeck[3a6a9adc157696d2]::check::check::check_item_type
  73:     0x7feb318d928e - rustc_typeck[3a6a9adc157696d2]::check::check::check_mod_item_types
  74:     0x7feb312041b2 - <rustc_query_system[c5b4090de70f61eb]::dep_graph::graph::DepGraph<rustc_middle[b0361dc3b46faa41]::dep_graph::dep_node::DepKind>>::with_task::<rustc_middle[b0361dc3b46faa41]::ty::context::TyCtxt, rustc_span[b55e3ed1d80ca2e1]::def_id::LocalDefId, ()>
  75:     0x7feb3120333e - rustc_query_system[c5b4090de70f61eb]::query::plumbing::try_execute_query::<rustc_query_impl[6ebad19704c173d0]::plumbing::QueryCtxt, rustc_query_system[c5b4090de70f61eb]::query::caches::DefaultCache<rustc_span[b55e3ed1d80ca2e1]::def_id::LocalDefId, ()>>
  76:     0x7feb31979253 - rustc_query_system[c5b4090de70f61eb]::query::plumbing::get_query::<rustc_query_impl[6ebad19704c173d0]::queries::check_mod_item_types, rustc_query_impl[6ebad19704c173d0]::plumbing::QueryCtxt>
  77:     0x7feb31c1581f - <rustc_middle[b0361dc3b46faa41]::hir::map::Map>::for_each_module::<rustc_typeck[3a6a9adc157696d2]::check_crate::{closure#6}::{closure#0}>
  78:     0x7feb318cc705 - rustc_typeck[3a6a9adc157696d2]::check_crate
  79:     0x7feb318cbcd7 - rustc_interface[3d0382fca78af13d]::passes::analysis
  80:     0x7feb31ccc6fc - <rustc_query_system[c5b4090de70f61eb]::dep_graph::graph::DepGraph<rustc_middle[b0361dc3b46faa41]::dep_graph::dep_node::DepKind>>::with_task::<rustc_middle[b0361dc3b46faa41]::ty::context::TyCtxt, (), core[2e75634dfdf5101e]::result::Result<(), rustc_errors[4734e126a08a56c6]::ErrorGuaranteed>>
  81:     0x7feb31ccbebb - rustc_query_system[c5b4090de70f61eb]::query::plumbing::try_execute_query::<rustc_query_impl[6ebad19704c173d0]::plumbing::QueryCtxt, rustc_query_system[c5b4090de70f61eb]::query::caches::DefaultCache<(), core[2e75634dfdf5101e]::result::Result<(), rustc_errors[4734e126a08a56c6]::ErrorGuaranteed>>>
  82:     0x7feb31ccba0e - rustc_query_system[c5b4090de70f61eb]::query::plumbing::get_query::<rustc_query_impl[6ebad19704c173d0]::queries::analysis, rustc_query_impl[6ebad19704c173d0]::plumbing::QueryCtxt>
  83:     0x7feb3169584e - <rustc_interface[3d0382fca78af13d]::passes::QueryContext>::enter::<rustc_driver[2f40008e0c6ae48d]::run_compiler::{closure#1}::{closure#2}::{closure#3}, core[2e75634dfdf5101e]::result::Result<(), rustc_errors[4734e126a08a56c6]::ErrorGuaranteed>>
  84:     0x7feb3168fc7e - <rustc_interface[3d0382fca78af13d]::interface::Compiler>::enter::<rustc_driver[2f40008e0c6ae48d]::run_compiler::{closure#1}::{closure#2}, core[2e75634dfdf5101e]::result::Result<core[2e75634dfdf5101e]::option::Option<rustc_interface[3d0382fca78af13d]::queries::Linker>, rustc_errors[4734e126a08a56c6]::ErrorGuaranteed>>
  85:     0x7feb3168b5ca - rustc_span[b55e3ed1d80ca2e1]::with_source_map::<core[2e75634dfdf5101e]::result::Result<(), rustc_errors[4734e126a08a56c6]::ErrorGuaranteed>, rustc_interface[3d0382fca78af13d]::interface::create_compiler_and_run<core[2e75634dfdf5101e]::result::Result<(), rustc_errors[4734e126a08a56c6]::ErrorGuaranteed>, rustc_driver[2f40008e0c6ae48d]::run_compiler::{closure#1}>::{closure#1}>
  86:     0x7feb3168b020 - rustc_interface[3d0382fca78af13d]::interface::create_compiler_and_run::<core[2e75634dfdf5101e]::result::Result<(), rustc_errors[4734e126a08a56c6]::ErrorGuaranteed>, rustc_driver[2f40008e0c6ae48d]::run_compiler::{closure#1}>
  87:     0x7feb316892d2 - <scoped_tls[c64be2cd70b559ef]::ScopedKey<rustc_span[b55e3ed1d80ca2e1]::SessionGlobals>>::set::<rustc_interface[3d0382fca78af13d]::interface::run_compiler<core[2e75634dfdf5101e]::result::Result<(), rustc_errors[4734e126a08a56c6]::ErrorGuaranteed>, rustc_driver[2f40008e0c6ae48d]::run_compiler::{closure#1}>::{closure#0}, core[2e75634dfdf5101e]::result::Result<(), rustc_errors[4734e126a08a56c6]::ErrorGuaranteed>>
  88:     0x7feb31688fbf - std[60ff705250c65a84]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[3d0382fca78af13d]::util::run_in_thread_pool_with_globals<rustc_interface[3d0382fca78af13d]::interface::run_compiler<core[2e75634dfdf5101e]::result::Result<(), rustc_errors[4734e126a08a56c6]::ErrorGuaranteed>, rustc_driver[2f40008e0c6ae48d]::run_compiler::{closure#1}>::{closure#0}, core[2e75634dfdf5101e]::result::Result<(), rustc_errors[4734e126a08a56c6]::ErrorGuaranteed>>::{closure#0}, core[2e75634dfdf5101e]::result::Result<(), rustc_errors[4734e126a08a56c6]::ErrorGuaranteed>>
  89:     0x7feb31d4f299 - <<std[60ff705250c65a84]::thread::Builder>::spawn_unchecked_<rustc_interface[3d0382fca78af13d]::util::run_in_thread_pool_with_globals<rustc_interface[3d0382fca78af13d]::interface::run_compiler<core[2e75634dfdf5101e]::result::Result<(), rustc_errors[4734e126a08a56c6]::ErrorGuaranteed>, rustc_driver[2f40008e0c6ae48d]::run_compiler::{closure#1}>::{closure#0}, core[2e75634dfdf5101e]::result::Result<(), rustc_errors[4734e126a08a56c6]::ErrorGuaranteed>>::{closure#0}, core[2e75634dfdf5101e]::result::Result<(), rustc_errors[4734e126a08a56c6]::ErrorGuaranteed>>::{closure#1} as core[2e75634dfdf5101e]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  90:     0x7feb2f73f2a3 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h91e73c9cb18fd002
                               at /rustc/3924dac7bb29bc8eb348059c901e8f912399c857/library/alloc/src/boxed.rs:1935:9
  91:     0x7feb2f73f2a3 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h3f4e95b624150e02
                               at /rustc/3924dac7bb29bc8eb348059c901e8f912399c857/library/alloc/src/boxed.rs:1935:9
  92:     0x7feb2f73f2a3 - std::sys::unix::thread::Thread::new::thread_start::h02aeb3ebecf360d5
                               at /rustc/3924dac7bb29bc8eb348059c901e8f912399c857/library/std/src/sys/unix/thread.rs:108:17
  93:     0x7feb2f607609 - start_thread
  94:     0x7feb2f52a163 - clone
  95:                0x0 - <unknown>

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.64.0-nightly (3924dac7b 2022-07-29) running on x86_64-unknown-linux-gnu

note: compiler flags: --crate-type bin -C embed-bitcode=no -C debuginfo=2 -C incremental

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [typeck] type-checking `routes::<impl at src/routes.rs:310:1: 310:26>::register::room_users`
#1 [mir_built] building MIR for `routes::<impl at src/routes.rs:310:1: 310:26>::register::room_users`
#2 [unsafety_check_result] unsafety-checking `routes::<impl at src/routes.rs:310:1: 310:26>::register::room_users`
#3 [mir_const] processing MIR for `routes::<impl at src/routes.rs:310:1: 310:26>::register::room_users`
#4 [mir_promoted] processing `routes::<impl at src/routes.rs:310:1: 310:26>::register::room_users`
#5 [mir_borrowck] borrow-checking `routes::<impl at src/routes.rs:310:1: 310:26>::register::room_users`
#6 [type_of] computing type of `routes::<impl at src/routes.rs:310:1: 310:26>::register::room_users::{opaque#0}`
#7 [check_mod_item_types] checking item types in module `routes`
#8 [analysis] running analysis passes on this crate
end of query stack
error: internal compiler error: no errors encountered even though `delay_span_bug` issued

error: internal compiler error: VecMap([(OpaqueTypeKey { def_id: DefId(0:1504 ~ changed_the_crate_name[fdea]::routes::{impl#9}::register::room_users::{opaque#0}), substs: [] }, OpaqueTypeDecl { hidden_type: OpaqueHiddenType { span: src/routes.rs:311:60: 311:74 (#1871), ty: _ }, origin: AsyncFn(DefId(0:1503 ~ changed_the_crate_name[fdea]::routes::{impl#9}::register::room_users)) }), (OpaqueTypeKey { def_id: DefId(0:1505 ~ changed_the_crate_name[fdea]::routes::{impl#9}::register::room_users::{opaque#0}::{opaque#0}), substs: [] }, OpaqueTypeDecl { hidden_type: OpaqueHiddenType { span: src/routes.rs:311:75: 319:2 (#0), ty: _ }, origin: FnReturn(DefId(0:1503 ~ changed_the_crate_name[fdea]::routes::{impl#9}::register::room_users)) })])
  |
  = note: delayed at compiler/rustc_infer/src/infer/opaque_types/table.rs:50:26

thread 'rustc' panicked at 'Box<dyn Any>', compiler/rustc_errors/src/lib.rs:1426:13
stack backtrace:
   0:     0x7feb2f732300 - std::backtrace_rs::backtrace::libunwind::trace::h6ddc9f9c210496ff
                               at /rustc/3924dac7bb29bc8eb348059c901e8f912399c857/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   1:     0x7feb2f732300 - std::backtrace_rs::backtrace::trace_unsynchronized::h9e468e888e8d9720
                               at /rustc/3924dac7bb29bc8eb348059c901e8f912399c857/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7feb2f732300 - std::sys_common::backtrace::_print_fmt::hd1881e9a19369fc2
                               at /rustc/3924dac7bb29bc8eb348059c901e8f912399c857/library/std/src/sys_common/backtrace.rs:66:5
   3:     0x7feb2f732300 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hc760c80094d12d0b
                               at /rustc/3924dac7bb29bc8eb348059c901e8f912399c857/library/std/src/sys_common/backtrace.rs:45:22
   4:     0x7feb2f78d71c - core::fmt::write::h9fa2d54393b34210
                               at /rustc/3924dac7bb29bc8eb348059c901e8f912399c857/library/core/src/fmt/mod.rs:1198:17
   5:     0x7feb2f723325 - std::io::Write::write_fmt::h6cb3511bb78b07fc
                               at /rustc/3924dac7bb29bc8eb348059c901e8f912399c857/library/std/src/io/mod.rs:1672:15
   6:     0x7feb2f734fd1 - std::sys_common::backtrace::_print::h82007c152e8a20f6
                               at /rustc/3924dac7bb29bc8eb348059c901e8f912399c857/library/std/src/sys_common/backtrace.rs:48:5
   7:     0x7feb2f734fd1 - std::sys_common::backtrace::print::hfd39d026c8fd7dc2
                               at /rustc/3924dac7bb29bc8eb348059c901e8f912399c857/library/std/src/sys_common/backtrace.rs:35:9
   8:     0x7feb2f734fd1 - std::panicking::default_hook::{{closure}}::h1d5c56ed0d43c6d2
                               at /rustc/3924dac7bb29bc8eb348059c901e8f912399c857/library/std/src/panicking.rs:295:22
   9:     0x7feb2f734ca3 - std::panicking::default_hook::hbd4b8c74f6bf2a75
                               at /rustc/3924dac7bb29bc8eb348059c901e8f912399c857/library/std/src/panicking.rs:314:9
  10:     0x7feb31f0b474 - rustc_driver[2f40008e0c6ae48d]::DEFAULT_HOOK::{closure#0}::{closure#0}
  11:     0x7feb2f735806 - std::panicking::rust_panic_with_hook::h1677c7be7e0853f1
                               at /rustc/3924dac7bb29bc8eb348059c901e8f912399c857/library/std/src/panicking.rs:702:17
  12:     0x7feb32f50ca1 - std[60ff705250c65a84]::panicking::begin_panic::<rustc_errors[4734e126a08a56c6]::ExplicitBug>::{closure#0}
  13:     0x7feb32f50a86 - std[60ff705250c65a84]::sys_common::backtrace::__rust_end_short_backtrace::<std[60ff705250c65a84]::panicking::begin_panic<rustc_errors[4734e126a08a56c6]::ExplicitBug>::{closure#0}, !>
  14:     0x7feb32f4b076 - std[60ff705250c65a84]::panicking::begin_panic::<rustc_errors[4734e126a08a56c6]::ExplicitBug>
  15:     0x7feb32f4d846 - std[60ff705250c65a84]::panic::panic_any::<rustc_errors[4734e126a08a56c6]::ExplicitBug>
  16:     0x7feb31a3e473 - <rustc_errors[4734e126a08a56c6]::HandlerInner as core[2e75634dfdf5101e]::ops::drop::Drop>::drop
  17:     0x7feb316a3b88 - core[2e75634dfdf5101e]::ptr::drop_in_place::<rustc_session[5f2f641abeccbe84]::parse::ParseSess>
  18:     0x7feb3168cda3 - <alloc[90525ec53b615182]::rc::Rc<rustc_session[5f2f641abeccbe84]::session::Session> as core[2e75634dfdf5101e]::ops::drop::Drop>::drop
  19:     0x7feb3168bd6d - core[2e75634dfdf5101e]::ptr::drop_in_place::<rustc_interface[3d0382fca78af13d]::interface::Compiler>
  20:     0x7feb3168b99b - rustc_span[b55e3ed1d80ca2e1]::with_source_map::<core[2e75634dfdf5101e]::result::Result<(), rustc_errors[4734e126a08a56c6]::ErrorGuaranteed>, rustc_interface[3d0382fca78af13d]::interface::create_compiler_and_run<core[2e75634dfdf5101e]::result::Result<(), rustc_errors[4734e126a08a56c6]::ErrorGuaranteed>, rustc_driver[2f40008e0c6ae48d]::run_compiler::{closure#1}>::{closure#1}>
  21:     0x7feb3168b020 - rustc_interface[3d0382fca78af13d]::interface::create_compiler_and_run::<core[2e75634dfdf5101e]::result::Result<(), rustc_errors[4734e126a08a56c6]::ErrorGuaranteed>, rustc_driver[2f40008e0c6ae48d]::run_compiler::{closure#1}>
  22:     0x7feb316892d2 - <scoped_tls[c64be2cd70b559ef]::ScopedKey<rustc_span[b55e3ed1d80ca2e1]::SessionGlobals>>::set::<rustc_interface[3d0382fca78af13d]::interface::run_compiler<core[2e75634dfdf5101e]::result::Result<(), rustc_errors[4734e126a08a56c6]::ErrorGuaranteed>, rustc_driver[2f40008e0c6ae48d]::run_compiler::{closure#1}>::{closure#0}, core[2e75634dfdf5101e]::result::Result<(), rustc_errors[4734e126a08a56c6]::ErrorGuaranteed>>
  23:     0x7feb31688fbf - std[60ff705250c65a84]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[3d0382fca78af13d]::util::run_in_thread_pool_with_globals<rustc_interface[3d0382fca78af13d]::interface::run_compiler<core[2e75634dfdf5101e]::result::Result<(), rustc_errors[4734e126a08a56c6]::ErrorGuaranteed>, rustc_driver[2f40008e0c6ae48d]::run_compiler::{closure#1}>::{closure#0}, core[2e75634dfdf5101e]::result::Result<(), rustc_errors[4734e126a08a56c6]::ErrorGuaranteed>>::{closure#0}, core[2e75634dfdf5101e]::result::Result<(), rustc_errors[4734e126a08a56c6]::ErrorGuaranteed>>
  24:     0x7feb31d4f299 - <<std[60ff705250c65a84]::thread::Builder>::spawn_unchecked_<rustc_interface[3d0382fca78af13d]::util::run_in_thread_pool_with_globals<rustc_interface[3d0382fca78af13d]::interface::run_compiler<core[2e75634dfdf5101e]::result::Result<(), rustc_errors[4734e126a08a56c6]::ErrorGuaranteed>, rustc_driver[2f40008e0c6ae48d]::run_compiler::{closure#1}>::{closure#0}, core[2e75634dfdf5101e]::result::Result<(), rustc_errors[4734e126a08a56c6]::ErrorGuaranteed>>::{closure#0}, core[2e75634dfdf5101e]::result::Result<(), rustc_errors[4734e126a08a56c6]::ErrorGuaranteed>>::{closure#1} as core[2e75634dfdf5101e]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  25:     0x7feb2f73f2a3 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h91e73c9cb18fd002
                               at /rustc/3924dac7bb29bc8eb348059c901e8f912399c857/library/alloc/src/boxed.rs:1935:9
  26:     0x7feb2f73f2a3 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h3f4e95b624150e02
                               at /rustc/3924dac7bb29bc8eb348059c901e8f912399c857/library/alloc/src/boxed.rs:1935:9
  27:     0x7feb2f73f2a3 - std::sys::unix::thread::Thread::new::thread_start::h02aeb3ebecf360d5
                               at /rustc/3924dac7bb29bc8eb348059c901e8f912399c857/library/std/src/sys/unix/thread.rs:108:17
  28:     0x7feb2f607609 - start_thread
  29:     0x7feb2f52a163 - clone
  30:                0x0 - <unknown>

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.64.0-nightly (3924dac7b 2022-07-29) running on x86_64-unknown-linux-gnu

note: compiler flags: --crate-type bin -C embed-bitcode=no -C debuginfo=2 -C incremental

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
thread panicked while panicking. aborting.
error: could not compile `changed_the_crate_name`

Caused by:
  process didn't exit successfully: `rustc --crate-name changed_the_crate_name --edition=2021 src/main.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --crate-type bin --emit=dep-info,metadata -C embed-bitcode=no -C debuginfo=2 -C metadata=7d2fd1988fdb872d -C extra-filename=-7d2fd1988fdb872d --out-dir /home/me/changed_the_crate_name/target/debug/deps -C incremental=/home/me/changed_the_crate_name/target/debug/incremental -L dependency=/home/me/changed_the_crate_name/target/debug/deps --extern actix=/home/me/changed_the_crate_name/target/debug/deps/libactix-8c8b18fce5898181.rmeta --extern actix_codec=/home/me/changed_the_crate_name/target/debug/deps/libactix_codec-9a150114e8ac250e.rmeta --extern actix_files=/home/me/changed_the_crate_name/target/debug/deps/libactix_files-12a85e24ddaae582.rmeta --extern actix_http=/home/me/changed_the_crate_name/target/debug/deps/libactix_http-42aea80dfee6f6ae.rmeta --extern actix_web=/home/me/changed_the_crate_name/target/debug/deps/libactix_web-02169da8fb674bf9.rmeta --extern actix_web_actors=/home/me/changed_the_crate_name/target/debug/deps/libactix_web_actors-6bcaac7ec65efb18.rmeta --extern actix_web_httpauth=/home/me/changed_the_crate_name/target/debug/deps/libactix_web_httpauth-132ae4b1d99d2f10.rmeta --extern bimap=/home/me/changed_the_crate_name/target/debug/deps/libbimap-f013d7026c9e0204.rmeta --extern bytes=/home/me/changed_the_crate_name/target/debug/deps/libbytes-0b6620405fcf1713.rmeta --extern futures=/home/me/changed_the_crate_name/target/debug/deps/libfutures-747dd63180d094e0.rmeta --extern getrandom=/home/me/changed_the_crate_name/target/debug/deps/libgetrandom-b65841092888d45d.rmeta --extern mysql_async=/home/me/changed_the_crate_name/target/debug/deps/libmysql_async-fa47d0d607c79c37.rmeta --extern serde=/home/me/changed_the_crate_name/target/debug/deps/libserde-c855e67a61636f71.rmeta --extern serde_json=/home/me/changed_the_crate_name/target/debug/deps/libserde_json-0a79a02467bd3bed.rmeta --extern sha2=/home/me/changed_the_crate_name/target/debug/deps/libsha2-531d12c35fc93842.rmeta --extern tokio=/home/me/changed_the_crate_name/target/debug/deps/libtokio-6cf92077d09ccfd1.rmeta --extern tokio_stream=/home/me/changed_the_crate_name/target/debug/deps/libtokio_stream-da8897be1157c0f5.rmeta --extern uuid=/home/me/changed_the_crate_name/target/debug/deps/libuuid-c8c54ae5510f2ebf.rmeta -L native=/home/me/changed_the_crate_name/target/debug/build/zstd-sys-2a23807d1fec7622/out` (signal: 6, SIGABRT: process abort signal)
```

</p>
</details>

### LINKED ISSUE #100463: ICE when annotating the return type of a function returning `impl Iterator<Item = &T>` to be `Vec<_>`
(Originally triggered by omitting a `.collect()`.) I believe it happens when `Vec` is replaced with another type implementing `FromIterator` too.

### Code

Playground: <https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=7c8637620ed85592da2967a16e3445d8>

```Rust
struct Foo<T> {
    inner: Vec<T>,
}

impl<T> Foo<T> {
    fn get(&self) -> impl Iterator<Item = &T> {
        self.inner.iter()
    }
}

fn main() {
    let foo: Foo<()> = Foo { inner: Vec::new() };
    let vals: Vec<_> = foo.get();
}
```

### Meta

`rustc --version --verbose`:
```
rustc 1.65.0-nightly (20ffea693 2022-08-11)
binary: rustc
commit-hash: 20ffea6938b5839c390252e07940b99e3b6a889a
commit-date: 2022-08-11
host: x86_64-pc-windows-msvc
release: 1.65.0-nightly
LLVM version: 14.0.6
```

### Error output
(From playground.)

```
thread 'rustc' panicked at 'index out of bounds: the len is 8 but the index is 9', /cargo/registry/src/github.com-1ecc6299db9ec823/ena-0.14.0/src/snapshot_vec.rs:199:10
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
thread 'rustc' panicked at 'index out of bounds: the len is 8 but the index is 9', /cargo/registry/src/github.com-1ecc6299db9ec823/ena-0.14.0/src/snapshot_vec.rs:199:10
stack backtrace:
   0:     0x7f61062490d0 - std::backtrace_rs::backtrace::libunwind::trace::h46f41e0f2d44e0df
                               at /rustc/20ffea6938b5839c390252e07940b99e3b6a889a/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   1:     0x7f61062490d0 - std::backtrace_rs::backtrace::trace_unsynchronized::hb45d7b1a672e2835
                               at /rustc/20ffea6938b5839c390252e07940b99e3b6a889a/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7f61062490d0 - std::sys_common::backtrace::_print_fmt::h44f1a0e55aa91690
                               at /rustc/20ffea6938b5839c390252e07940b99e3b6a889a/library/std/src/sys_common/backtrace.rs:66:5
   3:     0x7f61062490d0 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h89b860a0d0350e75
                               at /rustc/20ffea6938b5839c390252e07940b99e3b6a889a/library/std/src/sys_common/backtrace.rs:45:22
   4:     0x7f61062a430c - core::fmt::write::h16624c1dc5171107
                               at /rustc/20ffea6938b5839c390252e07940b99e3b6a889a/library/core/src/fmt/mod.rs:1198:17
   5:     0x7f610623a275 - std::io::Write::write_fmt::h1dcadf024b636a9e
                               at /rustc/20ffea6938b5839c390252e07940b99e3b6a889a/library/std/src/io/mod.rs:1672:15
   6:     0x7f610624bd71 - std::sys_common::backtrace::_print::h9fee53c784ef6946
                               at /rustc/20ffea6938b5839c390252e07940b99e3b6a889a/library/std/src/sys_common/backtrace.rs:48:5
   7:     0x7f610624bd71 - std::sys_common::backtrace::print::h19a2bc8888cb2bc1
                               at /rustc/20ffea6938b5839c390252e07940b99e3b6a889a/library/std/src/sys_common/backtrace.rs:35:9
   8:     0x7f610624bd71 - std::panicking::default_hook::{{closure}}::h194412cb7d14b330
                               at /rustc/20ffea6938b5839c390252e07940b99e3b6a889a/library/std/src/panicking.rs:295:22
   9:     0x7f610624ba43 - std::panicking::default_hook::hc48f58f040c51443
                               at /rustc/20ffea6938b5839c390252e07940b99e3b6a889a/library/std/src/panicking.rs:314:9
  10:     0x7f6108ac5004 - rustc_driver[6462606d2c9a987c]::DEFAULT_HOOK::{closure#0}::{closure#0}
  11:     0x7f610624c5a6 - std::panicking::rust_panic_with_hook::h7b8bf93cc86c2ee9
                               at /rustc/20ffea6938b5839c390252e07940b99e3b6a889a/library/std/src/panicking.rs:702:17
  12:     0x7f610624c3f7 - std::panicking::begin_panic_handler::{{closure}}::h8e24a61887340e6c
                               at /rustc/20ffea6938b5839c390252e07940b99e3b6a889a/library/std/src/panicking.rs:588:13
  13:     0x7f61062495f4 - std::sys_common::backtrace::__rust_end_short_backtrace::h2a0703be1b2ade8c
                               at /rustc/20ffea6938b5839c390252e07940b99e3b6a889a/library/std/src/sys_common/backtrace.rs:138:18
  14:     0x7f610624c122 - rust_begin_unwind
                               at /rustc/20ffea6938b5839c390252e07940b99e3b6a889a/library/std/src/panicking.rs:584:5
  15:     0x7f61062a0de3 - core::panicking::panic_fmt::h0e9ea325b67b5e79
                               at /rustc/20ffea6938b5839c390252e07940b99e3b6a889a/library/core/src/panicking.rs:142:14
  16:     0x7f61062a0d22 - core::panicking::panic_bounds_check::h22cf49632f9e4dd5
                               at /rustc/20ffea6938b5839c390252e07940b99e3b6a889a/library/core/src/panicking.rs:84:5
  17:     0x7f61073865b8 - <rustc_infer[e4f9b283dd8bd5a5]::infer::ShallowResolver as rustc_middle[9488a41f251ac6af]::ty::fold::TypeFolder>::fold_ty
  18:     0x7f610738b626 - <&rustc_middle[9488a41f251ac6af]::ty::list::List<rustc_middle[9488a41f251ac6af]::ty::subst::GenericArg> as rustc_middle[9488a41f251ac6af]::ty::fold::TypeFoldable>::try_fold_with::<rustc_infer[e4f9b283dd8bd5a5]::infer::resolve::OpportunisticVarResolver>
  19:     0x7f610747015d - <rustc_infer[e4f9b283dd8bd5a5]::infer::resolve::OpportunisticVarResolver as rustc_middle[9488a41f251ac6af]::ty::fold::FallibleTypeFolder>::try_fold_ty
  20:     0x7f6109996da6 - <(rustc_middle[9488a41f251ac6af]::ty::Ty, rustc_middle[9488a41f251ac6af]::ty::Ty) as rustc_middle[9488a41f251ac6af]::ty::fold::TypeFoldable>::fold_with::<rustc_infer[e4f9b283dd8bd5a5]::infer::resolve::OpportunisticVarResolver>
  21:     0x7f6109979b5f - <rustc_infer[e4f9b283dd8bd5a5]::infer::InferCtxt>::same_type_modulo_infer
  22:     0x7f61099f2009 - <core[8b3f08585b10cf9f]::iter::adapters::map::Map<core[8b3f08585b10cf9f]::iter::adapters::filter::Filter<core[8b3f08585b10cf9f]::slice::iter::Iter<rustc_middle[9488a41f251ac6af]::ty::FieldDef>, <rustc_infer[e4f9b283dd8bd5a5]::infer::InferCtxt>::suggest_accessing_field_where_appropriate::{closure#0}>, <rustc_infer[e4f9b283dd8bd5a5]::infer::InferCtxt>::suggest_accessing_field_where_appropriate::{closure#1}> as core[8b3f08585b10cf9f]::iter::traits::iterator::Iterator>::try_fold::<(), core[8b3f08585b10cf9f]::iter::traits::iterator::Iterator::find::check<(rustc_span[6baa44c84a5ae740]::symbol::Symbol, rustc_middle[9488a41f251ac6af]::ty::Ty), <rustc_infer[e4f9b283dd8bd5a5]::infer::InferCtxt>::suggest_accessing_field_where_appropriate::{closure#2}>::{closure#0}, core[8b3f08585b10cf9f]::ops::control_flow::ControlFlow<(rustc_span[6baa44c84a5ae740]::symbol::Symbol, rustc_middle[9488a41f251ac6af]::ty::Ty)>>
  23:     0x7f610997f060 - <rustc_infer[e4f9b283dd8bd5a5]::infer::InferCtxt>::note_type_err
  24:     0x7f61099759e7 - <rustc_infer[e4f9b283dd8bd5a5]::infer::InferCtxt>::report_and_explain_type_error
  25:     0x7f61075cc7db - <rustc_infer[e4f9b283dd8bd5a5]::infer::InferCtxt>::report_mismatched_types
  26:     0x7f61075d15a6 - <rustc_typeck[7fa82c3999929913]::check::fn_ctxt::FnCtxt>::demand_coerce
  27:     0x7f610756fee0 - <rustc_typeck[7fa82c3999929913]::check::fn_ctxt::FnCtxt>::check_decl
  28:     0x7f61075504e3 - <rustc_typeck[7fa82c3999929913]::check::fn_ctxt::FnCtxt>::check_block_with_expected
  29:     0x7f610753a93c - <rustc_typeck[7fa82c3999929913]::check::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
  30:     0x7f6107669400 - rustc_typeck[7fa82c3999929913]::check::check::check_fn
  31:     0x7f610765b65e - <rustc_infer[e4f9b283dd8bd5a5]::infer::InferCtxtBuilder>::enter::<&rustc_middle[9488a41f251ac6af]::ty::context::TypeckResults, <rustc_typeck[7fa82c3999929913]::check::inherited::InheritedBuilder>::enter<rustc_typeck[7fa82c3999929913]::check::typeck_with_fallback<rustc_typeck[7fa82c3999929913]::check::typeck::{closure#0}>::{closure#1}, &rustc_middle[9488a41f251ac6af]::ty::context::TypeckResults>::{closure#0}>
  32:     0x7f610765903e - rustc_typeck[7fa82c3999929913]::check::typeck
  33:     0x7f61081145ff - rustc_query_system[df871d006d4f2582]::query::plumbing::try_execute_query::<rustc_query_impl[9fb22c7f6160ba14]::plumbing::QueryCtxt, rustc_query_system[df871d006d4f2582]::query::caches::DefaultCache<rustc_span[6baa44c84a5ae740]::def_id::LocalDefId, &rustc_middle[9488a41f251ac6af]::ty::context::TypeckResults>>
  34:     0x7f61089c0fe8 - <rustc_query_impl[9fb22c7f6160ba14]::Queries as rustc_middle[9488a41f251ac6af]::ty::query::QueryEngine>::typeck
  35:     0x7f61087af656 - rustc_data_structures[21c65b7fbdc3607d]::sync::par_for_each_in::<&[rustc_span[6baa44c84a5ae740]::def_id::LocalDefId], <rustc_middle[9488a41f251ac6af]::hir::map::Map>::par_body_owners<rustc_typeck[7fa82c3999929913]::check::typeck_item_bodies::{closure#0}>::{closure#0}>
  36:     0x7f61087af40b - <rustc_middle[9488a41f251ac6af]::hir::map::Map>::par_body_owners::<rustc_typeck[7fa82c3999929913]::check::typeck_item_bodies::{closure#0}>
  37:     0x7f61087af35c - rustc_typeck[7fa82c3999929913]::check::typeck_item_bodies
  38:     0x7f6108798de5 - rustc_query_system[df871d006d4f2582]::query::plumbing::try_execute_query::<rustc_query_impl[9fb22c7f6160ba14]::plumbing::QueryCtxt, rustc_query_system[df871d006d4f2582]::query::caches::DefaultCache<(), ()>>
  39:     0x7f6108798b71 - rustc_query_system[df871d006d4f2582]::query::plumbing::get_query::<rustc_query_impl[9fb22c7f6160ba14]::queries::typeck_item_bodies, rustc_query_impl[9fb22c7f6160ba14]::plumbing::QueryCtxt>
  40:     0x7f61084b758f - <rustc_session[f256fc542d90c8dc]::session::Session>::time::<(), rustc_typeck[7fa82c3999929913]::check_crate::{closure#7}>
  41:     0x7f61084b700f - rustc_typeck[7fa82c3999929913]::check_crate
  42:     0x7f61084b6617 - rustc_interface[a83772335cbd79ec]::passes::analysis
  43:     0x7f6108850705 - rustc_query_system[df871d006d4f2582]::query::plumbing::try_execute_query::<rustc_query_impl[9fb22c7f6160ba14]::plumbing::QueryCtxt, rustc_query_system[df871d006d4f2582]::query::caches::DefaultCache<(), core[8b3f08585b10cf9f]::result::Result<(), rustc_errors[be872642351498fa]::ErrorGuaranteed>>>
  44:     0x7f610885048e - rustc_query_system[df871d006d4f2582]::query::plumbing::get_query::<rustc_query_impl[9fb22c7f6160ba14]::queries::analysis, rustc_query_impl[9fb22c7f6160ba14]::plumbing::QueryCtxt>
  45:     0x7f61082d41ae - <rustc_interface[a83772335cbd79ec]::passes::QueryContext>::enter::<rustc_driver[6462606d2c9a987c]::run_compiler::{closure#1}::{closure#2}::{closure#3}, core[8b3f08585b10cf9f]::result::Result<(), rustc_errors[be872642351498fa]::ErrorGuaranteed>>
  46:     0x7f61082d04ae - <rustc_interface[a83772335cbd79ec]::interface::Compiler>::enter::<rustc_driver[6462606d2c9a987c]::run_compiler::{closure#1}::{closure#2}, core[8b3f08585b10cf9f]::result::Result<core[8b3f08585b10cf9f]::option::Option<rustc_interface[a83772335cbd79ec]::queries::Linker>, rustc_errors[be872642351498fa]::ErrorGuaranteed>>
  47:     0x7f61082cbeaa - rustc_span[6baa44c84a5ae740]::with_source_map::<core[8b3f08585b10cf9f]::result::Result<(), rustc_errors[be872642351498fa]::ErrorGuaranteed>, rustc_interface[a83772335cbd79ec]::interface::create_compiler_and_run<core[8b3f08585b10cf9f]::result::Result<(), rustc_errors[be872642351498fa]::ErrorGuaranteed>, rustc_driver[6462606d2c9a987c]::run_compiler::{closure#1}>::{closure#1}>
  48:     0x7f61082cb87d - rustc_interface[a83772335cbd79ec]::interface::create_compiler_and_run::<core[8b3f08585b10cf9f]::result::Result<(), rustc_errors[be872642351498fa]::ErrorGuaranteed>, rustc_driver[6462606d2c9a987c]::run_compiler::{closure#1}>
  49:     0x7f61082c9e71 - <scoped_tls[7a8b5a19ecd46bb2]::ScopedKey<rustc_span[6baa44c84a5ae740]::SessionGlobals>>::set::<rustc_interface[a83772335cbd79ec]::interface::run_compiler<core[8b3f08585b10cf9f]::result::Result<(), rustc_errors[be872642351498fa]::ErrorGuaranteed>, rustc_driver[6462606d2c9a987c]::run_compiler::{closure#1}>::{closure#0}, core[8b3f08585b10cf9f]::result::Result<(), rustc_errors[be872642351498fa]::ErrorGuaranteed>>
  50:     0x7f61082c9b5f - std[9556ac8b7e82a845]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[a83772335cbd79ec]::util::run_in_thread_pool_with_globals<rustc_interface[a83772335cbd79ec]::interface::run_compiler<core[8b3f08585b10cf9f]::result::Result<(), rustc_errors[be872642351498fa]::ErrorGuaranteed>, rustc_driver[6462606d2c9a987c]::run_compiler::{closure#1}>::{closure#0}, core[8b3f08585b10cf9f]::result::Result<(), rustc_errors[be872642351498fa]::ErrorGuaranteed>>::{closure#0}, core[8b3f08585b10cf9f]::result::Result<(), rustc_errors[be872642351498fa]::ErrorGuaranteed>>
  51:     0x7f61088e5059 - <<std[9556ac8b7e82a845]::thread::Builder>::spawn_unchecked_<rustc_interface[a83772335cbd79ec]::util::run_in_thread_pool_with_globals<rustc_interface[a83772335cbd79ec]::interface::run_compiler<core[8b3f08585b10cf9f]::result::Result<(), rustc_errors[be872642351498fa]::ErrorGuaranteed>, rustc_driver[6462606d2c9a987c]::run_compiler::{closure#1}>::{closure#0}, core[8b3f08585b10cf9f]::result::Result<(), rustc_errors[be872642351498fa]::ErrorGuaranteed>>::{closure#0}, core[8b3f08585b10cf9f]::result::Result<(), rustc_errors[be872642351498fa]::ErrorGuaranteed>>::{closure#1} as core[8b3f08585b10cf9f]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  52:     0x7f6106256133 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h7acd473393bd5609
                               at /rustc/20ffea6938b5839c390252e07940b99e3b6a889a/library/alloc/src/boxed.rs:1935:9
  53:     0x7f6106256133 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h293bb2d5ea258a12
                               at /rustc/20ffea6938b5839c390252e07940b99e3b6a889a/library/alloc/src/boxed.rs:1935:9
  54:     0x7f6106256133 - std::sys::unix::thread::Thread::new::thread_start::h6122deedc0e97cdf
                               at /rustc/20ffea6938b5839c390252e07940b99e3b6a889a/library/std/src/sys/unix/thread.rs:108:17
  55:     0x7f6106129609 - start_thread
  56:     0x7f610604c133 - clone
  57:                0x0 - <unknown>

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.65.0-nightly (20ffea693 2022-08-11) running on x86_64-unknown-linux-gnu

note: compiler flags: --crate-type bin -C embed-bitcode=no -C codegen-units=1 -C debuginfo=2

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [typeck] type-checking `main`
#1 [typeck_item_bodies] type-checking all item bodies
#2 [analysis] running analysis passes on this crate
end of query stack
error: internal compiler error: no warnings or errors encountered even though `delayed_good_path_bugs` issued

error: internal compiler error: trimmed_def_paths constructed
  |
  = note: delayed at    0: <rustc_errors::Handler>::delay_good_path_bug::<&str>
             1: rustc_middle::ty::print::pretty::trimmed_def_paths
             2: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::plumbing::QueryCtxt, rustc_query_system::query::caches::ArenaCache<(), std::collections::hash::map::HashMap<rustc_span::def_id::DefId, rustc_span::symbol::Symbol, core::hash::BuildHasherDefault<rustc_hash::FxHasher>>>>
             3: rustc_query_system::query::plumbing::get_query::<rustc_query_impl::queries::trimmed_def_paths, rustc_query_impl::plumbing::QueryCtxt>
             4: <rustc_middle::ty::print::pretty::FmtPrinter as rustc_middle::ty::print::Printer>::print_def_path
             5: <rustc_middle::ty::print::pretty::FmtPrinter as rustc_middle::ty::print::Printer>::print_def_path
             6: <rustc_middle::ty::print::pretty::FmtPrinter as rustc_middle::ty::print::pretty::PrettyPrinter>::pretty_print_type
             7: <rustc_middle::ty::Ty as core::fmt::Display>::fmt
             8: <rustc_infer::infer::InferCtxt>::cmp
             9: <rustc_infer::infer::InferCtxt>::values_str
            10: <rustc_infer::infer::InferCtxt>::note_type_err
            11: <rustc_infer::infer::InferCtxt>::report_and_explain_type_error
            12: <rustc_infer::infer::InferCtxt>::report_mismatched_types
            13: <rustc_typeck::check::fn_ctxt::FnCtxt>::demand_coerce
            14: <rustc_typeck::check::fn_ctxt::FnCtxt>::check_decl
            15: <rustc_typeck::check::fn_ctxt::FnCtxt>::check_block_with_expected
            16: <rustc_typeck::check::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
            17: rustc_typeck::check::check::check_fn
            18: <rustc_infer::infer::InferCtxtBuilder>::enter::<&rustc_middle::ty::context::TypeckResults, <rustc_typeck::check::inherited::InheritedBuilder>::enter<rustc_typeck::check::typeck_with_fallback<rustc_typeck::check::typeck::{closure#0}>::{closure#1}, &rustc_middle::ty::context::TypeckResults>::{closure#0}>
            19: rustc_typeck::check::typeck
            20: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::plumbing::QueryCtxt, rustc_query_system::query::caches::DefaultCache<rustc_span::def_id::LocalDefId, &rustc_middle::ty::context::TypeckResults>>
            21: <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::typeck
            22: rustc_data_structures::sync::par_for_each_in::<&[rustc_span::def_id::LocalDefId], <rustc_middle::hir::map::Map>::par_body_owners<rustc_typeck::check::typeck_item_bodies::{closure#0}>::{closure#0}>
            23: <rustc_middle::hir::map::Map>::par_body_owners::<rustc_typeck::check::typeck_item_bodies::{closure#0}>
            24: rustc_typeck::check::typeck_item_bodies
            25: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::plumbing::QueryCtxt, rustc_query_system::query::caches::DefaultCache<(), ()>>
            26: rustc_query_system::query::plumbing::get_query::<rustc_query_impl::queries::typeck_item_bodies, rustc_query_impl::plumbing::QueryCtxt>
            27: <rustc_session::session::Session>::time::<(), rustc_typeck::check_crate::{closure#7}>
            28: rustc_typeck::check_crate
            29: rustc_interface::passes::analysis
            30: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::plumbing::QueryCtxt, rustc_query_system::query::caches::DefaultCache<(), core::result::Result<(), rustc_errors::ErrorGuaranteed>>>
            31: rustc_query_system::query::plumbing::get_query::<rustc_query_impl::queries::analysis, rustc_query_impl::plumbing::QueryCtxt>
            32: <rustc_interface::passes::QueryContext>::enter::<rustc_driver::run_compiler::{closure#1}::{closure#2}::{closure#3}, core::result::Result<(), rustc_errors::ErrorGuaranteed>>
            33: <rustc_interface::interface::Compiler>::enter::<rustc_driver::run_compiler::{closure#1}::{closure#2}, core::result::Result<core::option::Option<rustc_interface::queries::Linker>, rustc_errors::ErrorGuaranteed>>
            34: rustc_span::with_source_map::<core::result::Result<(), rustc_errors::ErrorGuaranteed>, rustc_interface::interface::create_compiler_and_run<core::result::Result<(), rustc_errors::ErrorGuaranteed>, rustc_driver::run_compiler::{closure#1}>::{closure#1}>
            35: rustc_interface::interface::create_compiler_and_run::<core::result::Result<(), rustc_errors::ErrorGuaranteed>, rustc_driver::run_compiler::{closure#1}>
            36: <scoped_tls::ScopedKey<rustc_span::SessionGlobals>>::set::<rustc_interface::interface::run_compiler<core::result::Result<(), rustc_errors::ErrorGuaranteed>, rustc_driver::run_compiler::{closure#1}>::{closure#0}, core::result::Result<(), rustc_errors::ErrorGuaranteed>>
            37: std::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface::util::run_in_thread_pool_with_globals<rustc_interface::interface::run_compiler<core::result::Result<(), rustc_errors::ErrorGuaranteed>, rustc_driver::run_compiler::{closure#1}>::{closure#0}, core::result::Result<(), rustc_errors::ErrorGuaranteed>>::{closure#0}, core::result::Result<(), rustc_errors::ErrorGuaranteed>>
            38: <<std::thread::Builder>::spawn_unchecked_<rustc_interface::util::run_in_thread_pool_with_globals<rustc_interface::interface::run_compiler<core::result::Result<(), rustc_errors::ErrorGuaranteed>, rustc_driver::run_compiler::{closure#1}>::{closure#0}, core::result::Result<(), rustc_errors::ErrorGuaranteed>>::{closure#0}, core::result::Result<(), rustc_errors::ErrorGuaranteed>>::{closure#1} as core::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
            39: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
                       at /rustc/20ffea6938b5839c390252e07940b99e3b6a889a/library/alloc/src/boxed.rs:1935:9
            40: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
                       at /rustc/20ffea6938b5839c390252e07940b99e3b6a889a/library/alloc/src/boxed.rs:1935:9
            41: std::sys::unix::thread::Thread::new::thread_start
                       at /rustc/20ffea6938b5839c390252e07940b99e3b6a889a/library/std/src/sys/unix/thread.rs:108:17
            42: start_thread
            43: clone
          

thread 'rustc' panicked at 'Box<dyn Any>', compiler/rustc_errors/src/lib.rs:1425:13
stack backtrace:
   0:     0x7f61062490d0 - std::backtrace_rs::backtrace::libunwind::trace::h46f41e0f2d44e0df
                               at /rustc/20ffea6938b5839c390252e07940b99e3b6a889a/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   1:     0x7f61062490d0 - std::backtrace_rs::backtrace::trace_unsynchronized::hb45d7b1a672e2835
                               at /rustc/20ffea6938b5839c390252e07940b99e3b6a889a/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7f61062490d0 - std::sys_common::backtrace::_print_fmt::h44f1a0e55aa91690
                               at /rustc/20ffea6938b5839c390252e07940b99e3b6a889a/library/std/src/sys_common/backtrace.rs:66:5
   3:     0x7f61062490d0 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h89b860a0d0350e75
                               at /rustc/20ffea6938b5839c390252e07940b99e3b6a889a/library/std/src/sys_common/backtrace.rs:45:22
   4:     0x7f61062a430c - core::fmt::write::h16624c1dc5171107
                               at /rustc/20ffea6938b5839c390252e07940b99e3b6a889a/library/core/src/fmt/mod.rs:1198:17
   5:     0x7f610623a275 - std::io::Write::write_fmt::h1dcadf024b636a9e
                               at /rustc/20ffea6938b5839c390252e07940b99e3b6a889a/library/std/src/io/mod.rs:1672:15
   6:     0x7f610624bd71 - std::sys_common::backtrace::_print::h9fee53c784ef6946
                               at /rustc/20ffea6938b5839c390252e07940b99e3b6a889a/library/std/src/sys_common/backtrace.rs:48:5
   7:     0x7f610624bd71 - std::sys_common::backtrace::print::h19a2bc8888cb2bc1
                               at /rustc/20ffea6938b5839c390252e07940b99e3b6a889a/library/std/src/sys_common/backtrace.rs:35:9
   8:     0x7f610624bd71 - std::panicking::default_hook::{{closure}}::h194412cb7d14b330
                               at /rustc/20ffea6938b5839c390252e07940b99e3b6a889a/library/std/src/panicking.rs:295:22
   9:     0x7f610624ba43 - std::panicking::default_hook::hc48f58f040c51443
                               at /rustc/20ffea6938b5839c390252e07940b99e3b6a889a/library/std/src/panicking.rs:314:9
  10:     0x7f6108ac5004 - rustc_driver[6462606d2c9a987c]::DEFAULT_HOOK::{closure#0}::{closure#0}
  11:     0x7f610624c5a6 - std::panicking::rust_panic_with_hook::h7b8bf93cc86c2ee9
                               at /rustc/20ffea6938b5839c390252e07940b99e3b6a889a/library/std/src/panicking.rs:702:17
  12:     0x7f6109b99f21 - std[9556ac8b7e82a845]::panicking::begin_panic::<rustc_errors[be872642351498fa]::ExplicitBug>::{closure#0}
  13:     0x7f6109b99d06 - std[9556ac8b7e82a845]::sys_common::backtrace::__rust_end_short_backtrace::<std[9556ac8b7e82a845]::panicking::begin_panic<rustc_errors[be872642351498fa]::ExplicitBug>::{closure#0}, !>
  14:     0x7f6109b947d6 - std[9556ac8b7e82a845]::panicking::begin_panic::<rustc_errors[be872642351498fa]::ExplicitBug>
  15:     0x7f6109b96e96 - std[9556ac8b7e82a845]::panic::panic_any::<rustc_errors[be872642351498fa]::ExplicitBug>
  16:     0x7f61085d09bb - <rustc_errors[be872642351498fa]::HandlerInner as core[8b3f08585b10cf9f]::ops::drop::Drop>::drop
  17:     0x7f61082e3ff8 - core[8b3f08585b10cf9f]::ptr::drop_in_place::<rustc_session[f256fc542d90c8dc]::parse::ParseSess>
  18:     0x7f61082cd673 - <alloc[595f59d51fcbe319]::rc::Rc<rustc_session[f256fc542d90c8dc]::session::Session> as core[8b3f08585b10cf9f]::ops::drop::Drop>::drop
  19:     0x7f61082cc64d - core[8b3f08585b10cf9f]::ptr::drop_in_place::<rustc_interface[a83772335cbd79ec]::interface::Compiler>
  20:     0x7f61082cc27b - rustc_span[6baa44c84a5ae740]::with_source_map::<core[8b3f08585b10cf9f]::result::Result<(), rustc_errors[be872642351498fa]::ErrorGuaranteed>, rustc_interface[a83772335cbd79ec]::interface::create_compiler_and_run<core[8b3f08585b10cf9f]::result::Result<(), rustc_errors[be872642351498fa]::ErrorGuaranteed>, rustc_driver[6462606d2c9a987c]::run_compiler::{closure#1}>::{closure#1}>
  21:     0x7f61082cb87d - rustc_interface[a83772335cbd79ec]::interface::create_compiler_and_run::<core[8b3f08585b10cf9f]::result::Result<(), rustc_errors[be872642351498fa]::ErrorGuaranteed>, rustc_driver[6462606d2c9a987c]::run_compiler::{closure#1}>
  22:     0x7f61082c9e71 - <scoped_tls[7a8b5a19ecd46bb2]::ScopedKey<rustc_span[6baa44c84a5ae740]::SessionGlobals>>::set::<rustc_interface[a83772335cbd79ec]::interface::run_compiler<core[8b3f08585b10cf9f]::result::Result<(), rustc_errors[be872642351498fa]::ErrorGuaranteed>, rustc_driver[6462606d2c9a987c]::run_compiler::{closure#1}>::{closure#0}, core[8b3f08585b10cf9f]::result::Result<(), rustc_errors[be872642351498fa]::ErrorGuaranteed>>
  23:     0x7f61082c9b5f - std[9556ac8b7e82a845]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[a83772335cbd79ec]::util::run_in_thread_pool_with_globals<rustc_interface[a83772335cbd79ec]::interface::run_compiler<core[8b3f08585b10cf9f]::result::Result<(), rustc_errors[be872642351498fa]::ErrorGuaranteed>, rustc_driver[6462606d2c9a987c]::run_compiler::{closure#1}>::{closure#0}, core[8b3f08585b10cf9f]::result::Result<(), rustc_errors[be872642351498fa]::ErrorGuaranteed>>::{closure#0}, core[8b3f08585b10cf9f]::result::Result<(), rustc_errors[be872642351498fa]::ErrorGuaranteed>>
  24:     0x7f61088e5059 - <<std[9556ac8b7e82a845]::thread::Builder>::spawn_unchecked_<rustc_interface[a83772335cbd79ec]::util::run_in_thread_pool_with_globals<rustc_interface[a83772335cbd79ec]::interface::run_compiler<core[8b3f08585b10cf9f]::result::Result<(), rustc_errors[be872642351498fa]::ErrorGuaranteed>, rustc_driver[6462606d2c9a987c]::run_compiler::{closure#1}>::{closure#0}, core[8b3f08585b10cf9f]::result::Result<(), rustc_errors[be872642351498fa]::ErrorGuaranteed>>::{closure#0}, core[8b3f08585b10cf9f]::result::Result<(), rustc_errors[be872642351498fa]::ErrorGuaranteed>>::{closure#1} as core[8b3f08585b10cf9f]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  25:     0x7f6106256133 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h7acd473393bd5609
                               at /rustc/20ffea6938b5839c390252e07940b99e3b6a889a/library/alloc/src/boxed.rs:1935:9
  26:     0x7f6106256133 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h293bb2d5ea258a12
                               at /rustc/20ffea6938b5839c390252e07940b99e3b6a889a/library/alloc/src/boxed.rs:1935:9
  27:     0x7f6106256133 - std::sys::unix::thread::Thread::new::thread_start::h6122deedc0e97cdf
                               at /rustc/20ffea6938b5839c390252e07940b99e3b6a889a/library/std/src/sys/unix/thread.rs:108:17
  28:     0x7f6106129609 - start_thread
  29:     0x7f610604c133 - clone
  30:                0x0 - <unknown>

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.65.0-nightly (20ffea693 2022-08-11) running on x86_64-unknown-linux-gnu

note: compiler flags: --crate-type bin -C embed-bitcode=no -C codegen-units=1 -C debuginfo=2

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
thread panicked while panicking. aborting.
error: could not compile `playground`

Caused by:
  process didn't exit successfully: `rustc --crate-name playground --edition=2021 src/main.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --crate-type bin --emit=dep-info,link -C embed-bitcode=no -C codegen-units=1 -C debuginfo=2 -C metadata=f5f58752b5055057 -C extra-filename=-f5f58752b5055057 --out-dir /playground/target/debug/deps -L dependency=/playground/target/debug/deps --extern addr2line=/playground/target/debug/deps/libaddr2line-4622820bc8da0710.rlib --extern adler=/playground/target/debug/deps/libadler-a6755dfadabd895e.rlib --extern adler32=/playground/target/debug/deps/libadler32-88b3d863e553f12a.rlib --extern ahash=/playground/target/debug/deps/libahash-271cfab6b329de2e.rlib --extern aho_corasick=/playground/target/debug/deps/libaho_corasick-264ae4769fcfc70d.rlib --extern ansi_term=/playground/target/debug/deps/libansi_term-2159b79c7c03c33b.rlib --extern anyhow=/playground/target/debug/deps/libanyhow-83b91b98777a2181.rlib --extern approx=/playground/target/debug/deps/libapprox-f78cbbfbc5aba28a.rlib --extern arc_swap=/playground/target/debug/deps/libarc_swap-5e7a10b2d7e5fb7c.rlib --extern arrayvec=/playground/target/debug/deps/libarrayvec-3a1c12b84c4c35e6.rlib --extern async_recursion=/playground/target/debug/deps/libasync_recursion-d5a3a8ebb4e79c66.so --extern async_trait=/playground/target/debug/deps/libasync_trait-c52268b3ca084b86.so --extern atty=/playground/target/debug/deps/libatty-633a80a49cbd8f1e.rlib --extern autocfg=/playground/target/debug/deps/libautocfg-92b429196c196cd1.rlib --extern backtrace=/playground/target/debug/deps/libbacktrace-f3a960fb44538bb7.rlib --extern base64=/playground/target/debug/deps/libbase64-cfc95277467b3864.rlib --extern bit_set=/playground/target/debug/deps/libbit_set-f061bec672eea20c.rlib --extern bit_vec=/playground/target/debug/deps/libbit_vec-e0495be0df3dad6d.rlib --extern bit_field=/playground/target/debug/deps/libbit_field-162e58bc8aaf39fd.rlib --extern bitflags=/playground/target/debug/deps/libbitflags-de1f0b76046eea2a.rlib --extern block_buffer=/playground/target/debug/deps/libblock_buffer-cd87e17c56c5b7d1.rlib --extern bstr=/playground/target/debug/deps/libbstr-13f5a6062d35e7e3.rlib --extern bytemuck=/playground/target/debug/deps/libbytemuck-3ee22d96b099da45.rlib --extern bytemuck_derive=/playground/target/debug/deps/libbytemuck_derive-8adcb81ce8e30709.so --extern byteorder=/playground/target/debug/deps/libbyteorder-3386849127ec7437.rlib --extern bytes_0_4_12=/playground/target/debug/deps/libbytes-f56810ab3221ca9e.rlib --extern bytes=/playground/target/debug/deps/libbytes-6e05598c71bf2ce4.rlib --extern cc=/playground/target/debug/deps/libcc-54590ee4f75082e3.rlib --extern cfg_if=/playground/target/debug/deps/libcfg_if-5253e57569830399.rlib --extern chrono=/playground/target/debug/deps/libchrono-200643a61ca9ccf8.rlib --extern clap=/playground/target/debug/deps/libclap-4f82a4a3e5a99c32.rlib --extern clap_derive=/playground/target/debug/deps/libclap_derive-79360f04e200f117.so --extern clap_lex=/playground/target/debug/deps/libclap_lex-03c5a6972881bfd6.rlib --extern color_quant=/playground/target/debug/deps/libcolor_quant-aef1b2deff556d9b.rlib --extern cookie=/playground/target/debug/deps/libcookie-2b8c5841ab7c630d.rlib --extern cookie_store=/playground/target/debug/deps/libcookie_store-d0393134ed3225cd.rlib --extern cpufeatures=/playground/target/debug/deps/libcpufeatures-64356bf892265055.rlib --extern crc32fast=/playground/target/debug/deps/libcrc32fast-0c0c315b6647141a.rlib --extern crossbeam=/playground/target/debug/deps/libcrossbeam-4a83567da5bb5b0f.rlib --extern crossbeam_channel=/playground/target/debug/deps/libcrossbeam_channel-f42f2f6c8eb169a6.rlib --extern crossbeam_deque=/playground/target/debug/deps/libcrossbeam_deque-a0834a93a6fef557.rlib --extern crossbeam_epoch=/playground/target/debug/deps/libcrossbeam_epoch-57c9ae93ae0de535.rlib --extern crossbeam_queue=/playground/target/debug/deps/libcrossbeam_queue-ee47b7eaf2be45e8.rlib --extern crossbeam_utils=/playground/target/debug/deps/libcrossbeam_utils-8aaadcbeb5322e0a.rlib --extern crypto_common=/playground/target/debug/deps/libcrypto_common-9cd32161867c1a49.rlib --extern csv=/playground/target/debug/deps/libcsv-1992674806044306.rlib --extern csv_core=/playground/target/debug/deps/libcsv_core-ec211a530f024414.rlib --extern data_encoding=/playground/target/debug/deps/libdata_encoding-dc27914ccac23bde.rlib --extern deflate=/playground/target/debug/deps/libdeflate-7bc1827ecfd03f68.rlib --extern derivative=/playground/target/debug/deps/libderivative-e9bbfce761cbfdd7.so --extern digest=/playground/target/debug/deps/libdigest-5da9022e3c7a338e.rlib --extern either=/playground/target/debug/deps/libeither-f346a828932e9f5a.rlib --extern encoding_rs=/playground/target/debug/deps/libencoding_rs-1b37bb924e80cd4e.rlib --extern env_logger=/playground/target/debug/deps/libenv_logger-aaf5cf4389b032c2.rlib --extern error_chain=/playground/target/debug/deps/liberror_chain-cdf9387abe6d45e3.rlib --extern exr=/playground/target/debug/deps/libexr-f3c304eca0bafc57.rlib --extern fallible_iterator=/playground/target/debug/deps/libfallible_iterator-7f4fc8c0ad37dc9d.rlib --extern fallible_streaming_iterator=/playground/target/debug/deps/libfallible_streaming_iterator-baab7654e5e34d04.rlib --extern fastrand=/playground/target/debug/deps/libfastrand-dacfd4293675479e.rlib --extern filetime=/playground/target/debug/deps/libfiletime-a6b93118174555ef.rlib --extern fixedbitset=/playground/target/debug/deps/libfixedbitset-5c1762520b77630c.rlib --extern flate2=/playground/target/debug/deps/libflate2-d75c787bf7d341df.rlib --extern flume=/playground/target/debug/deps/libflume-150ae1826b04abdc.rlib --extern fnv=/playground/target/debug/deps/libfnv-0672b6da71ed834c.rlib --extern foreign_types=/playground/target/debug/deps/libforeign_types-e5d0ea207091f2ed.rlib --extern foreign_types_shared=/playground/target/debug/deps/libforeign_types_shared-e64cfaf7a202bcc7.rlib --extern form_urlencoded=/playground/target/debug/deps/libform_urlencoded-12649d381e2544ae.rlib --extern futf=/playground/target/debug/deps/libfutf-66f12e798eb4013d.rlib --extern futures_0_1_31=/playground/target/debug/deps/libfutures-559b4d2f77076e5b.rlib --extern futures=/playground/target/debug/deps/libfutures-1e3cf3b3fcfefaf4.rlib --extern futures_channel=/playground/target/debug/deps/libfutures_channel-a255c74496200362.rlib --extern futures_core=/playground/target/debug/deps/libfutures_core-8d97d4e81153b410.rlib --extern futures_executor=/playground/target/debug/deps/libfutures_executor-7ded8ee3fdb730e6.rlib --extern futures_io=/playground/target/debug/deps/libfutures_io-e618f64de8846573.rlib --extern futures_macro=/playground/target/debug/deps/libfutures_macro-40c489ebd52ce116.so --extern futures_sink=/playground/target/debug/deps/libfutures_sink-33c5800d6da7d85e.rlib --extern futures_task=/playground/target/debug/deps/libfutures_task-1ac788fb68375678.rlib --extern futures_util=/playground/target/debug/deps/libfutures_util-ca130c36e9dcde60.rlib --extern generic_array=/playground/target/debug/deps/libgeneric_array-c1d944b48ca6a881.rlib --extern getrandom_0_1_16=/playground/target/debug/deps/libgetrandom-8826dfbfec937325.rlib --extern getrandom=/playground/target/debug/deps/libgetrandom-d6665633fcf8414e.rlib --extern gif=/playground/target/debug/deps/libgif-622fd6aa85a56b11.rlib --extern gimli=/playground/target/debug/deps/libgimli-80a4a6052a0da982.rlib --extern glob=/playground/target/debug/deps/libglob-3e188ae16859c506.rlib --extern h2=/playground/target/debug/deps/libh2-5594dd3294d73e35.rlib --extern half=/playground/target/debug/deps/libhalf-886abc4065fa3cfd.rlib --extern hashbrown_0_11_2=/playground/target/debug/deps/libhashbrown-45fd56b26ed1f0c4.rlib --extern hashbrown=/playground/target/debug/deps/libhashbrown-97c98cb4f43bbc0e.rlib --extern hashlink=/playground/target/debug/deps/libhashlink-2a4d4a2f0ff01b84.rlib --extern heck=/playground/target/debug/deps/libheck-424a3df7d01d544f.rlib --extern hmac=/playground/target/debug/deps/libhmac-7d40ed6a0478a50c.rlib --extern html5ever=/playground/target/debug/deps/libhtml5ever-521da060c932d387.rlib --extern http=/playground/target/debug/deps/libhttp-ef61a4893de324c3.rlib --extern http_body=/playground/target/debug/deps/libhttp_body-956ffbd802d2fc44.rlib --extern httparse=/playground/target/debug/deps/libhttparse-d04e3147dbe7a08f.rlib --extern httpdate=/playground/target/debug/deps/libhttpdate-7c7fbb165bed6800.rlib --extern humantime=/playground/target/debug/deps/libhumantime-bcb137373d337ec0.rlib --extern hyper=/playground/target/debug/deps/libhyper-b5c216576c06f0bc.rlib --extern hyper_tls=/playground/target/debug/deps/libhyper_tls-2def24e0b1905b7e.rlib --extern idna=/playground/target/debug/deps/libidna-3374f7d530ed4dd5.rlib --extern image=/playground/target/debug/deps/libimage-07c1d8b737d244d4.rlib --extern indexmap=/playground/target/debug/deps/libindexmap-03f32e1afbff752c.rlib --extern inflate=/playground/target/debug/deps/libinflate-8cf9d3a2b1598f25.rlib --extern iovec=/playground/target/debug/deps/libiovec-83ec7f0e360bb23b.rlib --extern ipnet=/playground/target/debug/deps/libipnet-7d81997bc8687860.rlib --extern itertools=/playground/target/debug/deps/libitertools-8afb15a06e804707.rlib --extern itoa_0_4_8=/playground/target/debug/deps/libitoa-bda856047fedd8f8.rlib --extern itoa=/playground/target/debug/deps/libitoa-e8a2074e2ebd1a2e.rlib --extern jpeg_decoder=/playground/target/debug/deps/libjpeg_decoder-6eaae1499b07700a.rlib --extern lazy_static=/playground/target/debug/deps/liblazy_static-56f839fc5f97cc86.rlib --extern lebe=/playground/target/debug/deps/liblebe-658493c415292124.rlib --extern libc=/playground/target/debug/deps/liblibc-ddc894a4d9811fe6.rlib --extern libm=/playground/target/debug/deps/liblibm-d9d27b0264c75a74.rlib --extern libsqlite3_sys=/playground/target/debug/deps/liblibsqlite3_sys-e4393db0d6bb4ab7.rlib --extern linked_hash_map=/playground/target/debug/deps/liblinked_hash_map-11a9f42e529348d3.rlib --extern lock_api=/playground/target/debug/deps/liblock_api-81229d7d3e7147ee.rlib --extern log=/playground/target/debug/deps/liblog-3efd2601fe11d45c.rlib --extern log_mdc=/playground/target/debug/deps/liblog_mdc-8c9acbf18051a6d8.rlib --extern log4rs=/playground/target/debug/deps/liblog4rs-bc486e868780a4dc.rlib --extern mac=/playground/target/debug/deps/libmac-5ef46c35d1d60ae2.rlib --extern markup5ever=/playground/target/debug/deps/libmarkup5ever-2f08d0f5d21179fe.rlib --extern markup5ever_rcdom=/playground/target/debug/deps/libmarkup5ever_rcdom-f5c35832f94bc0a0.rlib --extern matches=/playground/target/debug/deps/libmatches-94fda48e5e4c1005.rlib --extern matrixmultiply=/playground/target/debug/deps/libmatrixmultiply-9caa3f033427a130.rlib --extern md5=/playground/target/debug/deps/libmd5-dbddac5eb0900f3f.rlib --extern memchr=/playground/target/debug/deps/libmemchr-eb1f3e221a710635.rlib --extern memmap=/playground/target/debug/deps/libmemmap-894a7ec22e7923fd.rlib --extern memoffset=/playground/target/debug/deps/libmemoffset-4b04207de0ea1bb9.rlib --extern mime=/playground/target/debug/deps/libmime-be254843d53468a4.rlib --extern mime_guess=/playground/target/debug/deps/libmime_guess-571817c641636617.rlib --extern miniz_oxide=/playground/target/debug/deps/libminiz_oxide-6c8dbad11bfbba6a.rlib --extern mio=/playground/target/debug/deps/libmio-f5b79636db581427.rlib --extern nalgebra=/playground/target/debug/deps/libnalgebra-b059118800d793ea.rlib --extern nalgebra_macros=/playground/target/debug/deps/libnalgebra_macros-d59e7d342089f825.so --extern nanorand=/playground/target/debug/deps/libnanorand-e1bdbd530c85a92a.rlib --extern native_tls=/playground/target/debug/deps/libnative_tls-bbe37f4ca0271782.rlib --extern ndarray=/playground/target/debug/deps/libndarray-bf085a6e8f1f0851.rlib --extern debug_unreachable=/playground/target/debug/deps/libdebug_unreachable-cc7ea61f7b47b527.rlib --extern num=/playground/target/debug/deps/libnum-0f0e8a1a64324190.rlib --extern num_bigint=/playground/target/debug/deps/libnum_bigint-57448c082e57f371.rlib --extern num_complex=/playground/target/debug/deps/libnum_complex-aecc97e44f46c3e8.rlib --extern num_integer=/playground/target/debug/deps/libnum_integer-3b0dd6fd79cbb74d.rlib --extern num_iter=/playground/target/debug/deps/libnum_iter-8361b8b149e7670f.rlib --extern num_rational=/playground/target/debug/deps/libnum_rational-c95febc26f3e9eb9.rlib --extern num_traits=/playground/target/debug/deps/libnum_traits-01181aee54365fe8.rlib --extern num_cpus=/playground/target/debug/deps/libnum_cpus-71e79e0d5c490f61.rlib --extern num_threads=/playground/target/debug/deps/libnum_threads-58f5879f94056fd1.rlib --extern object=/playground/target/debug/deps/libobject-54b407c61d3a8c66.rlib --extern once_cell=/playground/target/debug/deps/libonce_cell-7a35ecdc9f141a34.rlib --extern opaque_debug=/playground/target/debug/deps/libopaque_debug-ab9ddb0f69438328.rlib --extern openssl=/playground/target/debug/deps/libopenssl-9b290fc7afd1e307.rlib --extern openssl_macros=/playground/target/debug/deps/libopenssl_macros-7cec0af03c3d4025.so --extern openssl_probe=/playground/target/debug/deps/libopenssl_probe-94c713caf31880eb.rlib --extern openssl_sys=/playground/target/debug/deps/libopenssl_sys-b6b580bb0d3af1f2.rlib --extern ordered_float=/playground/target/debug/deps/libordered_float-b9874b73a973e19c.rlib --extern os_str_bytes=/playground/target/debug/deps/libos_str_bytes-148fb1e119364808.rlib --extern parking_lot=/playground/target/debug/deps/libparking_lot-9c2061d7681efbf9.rlib --extern parking_lot_core=/playground/target/debug/deps/libparking_lot_core-9ad4c414c39ef055.rlib --extern paste=/playground/target/debug/deps/libpaste-0f9b8675f573fc6b.so --extern percent_encoding=/playground/target/debug/deps/libpercent_encoding-431c76c01be24719.rlib --extern pest=/playground/target/debug/deps/libpest-304968d684b3b2a0.rlib --extern petgraph=/playground/target/debug/deps/libpetgraph-84e58b41a8a0a0e7.rlib --extern phf_0_8_0=/playground/target/debug/deps/libphf-fae1fb35b28a2359.rlib --extern phf=/playground/target/debug/deps/libphf-d7d77d4e472ed460.rlib --extern phf_codegen=/playground/target/debug/deps/libphf_codegen-58bef7b539d4a450.rlib --extern phf_generator_0_8_0=/playground/target/debug/deps/libphf_generator-600dc57d4e54c413.rlib --extern phf_generator=/playground/target/debug/deps/libphf_generator-72109cc192295f70.rlib --extern phf_shared_0_8_0=/playground/target/debug/deps/libphf_shared-e02d9191b9baf9b9.rlib --extern phf_shared=/playground/target/debug/deps/libphf_shared-2b39fa7fe3e04733.rlib --extern pin_project=/playground/target/debug/deps/libpin_project-56d61ccd984a8dc2.rlib --extern pin_project_internal=/playground/target/debug/deps/libpin_project_internal-1dda89a36f44d058.so --extern pin_project_lite=/playground/target/debug/deps/libpin_project_lite-f39210ec8aa22683.rlib --extern pin_utils=/playground/target/debug/deps/libpin_utils-b0bf3f0688139ba1.rlib --extern pkg_config=/playground/target/debug/deps/libpkg_config-e38945851503d517.rlib --extern png=/playground/target/debug/deps/libpng-89ddad962122e65a.rlib --extern postgres=/playground/target/debug/deps/libpostgres-2caf3a328921c685.rlib --extern postgres_protocol=/playground/target/debug/deps/libpostgres_protocol-bd6c2be074903b55.rlib --extern postgres_types=/playground/target/debug/deps/libpostgres_types-7f4895d4e4bc521b.rlib --extern ppv_lite86=/playground/target/debug/deps/libppv_lite86-8303bb68ceff8d83.rlib --extern precomputed_hash=/playground/target/debug/deps/libprecomputed_hash-1298520f088678de.rlib --extern proc_macro_error=/playground/target/debug/deps/libproc_macro_error-41183b18d08f76e7.rlib --extern proc_macro_error_attr=/playground/target/debug/deps/libproc_macro_error_attr-ead720c4631e653e.so --extern proc_macro_hack=/playground/target/debug/deps/libproc_macro_hack-92717a4671472a53.so --extern proc_macro2=/playground/target/debug/deps/libproc_macro2-860ae9ad5d4a35c6.rlib --extern psl_types=/playground/target/debug/deps/libpsl_types-1a8dd76c33951022.rlib --extern publicsuffix=/playground/target/debug/deps/libpublicsuffix-eb2d301c76b7bc2d.rlib --extern quote=/playground/target/debug/deps/libquote-0388d57a8169fe4b.rlib --extern rand_0_7_3=/playground/target/debug/deps/librand-17fd2d9ace524bf3.rlib --extern rand=/playground/target/debug/deps/librand-70a9c3ec1ed15371.rlib --extern rand_chacha_0_2_2=/playground/target/debug/deps/librand_chacha-a080f594c8327cf5.rlib --extern rand_chacha=/playground/target/debug/deps/librand_chacha-9f5aba1d504d0591.rlib --extern rand_core_0_5_1=/playground/target/debug/deps/librand_core-9c2169b95abc6da6.rlib --extern rand_core=/playground/target/debug/deps/librand_core-58dcb81429fd1b43.rlib --extern rand_distr=/playground/target/debug/deps/librand_distr-9c0e49365bbf3150.rlib --extern rand_pcg=/playground/target/debug/deps/librand_pcg-def086388c64c813.rlib --extern rawpointer=/playground/target/debug/deps/librawpointer-63eb1bba55566369.rlib --extern rayon=/playground/target/debug/deps/librayon-12b05f0026f40f43.rlib --extern rayon_core=/playground/target/debug/deps/librayon_core-1098e8d0d1a2036f.rlib --extern regex=/playground/target/debug/deps/libregex-ed0a83949168d5ea.rlib --extern regex_automata=/playground/target/debug/deps/libregex_automata-0aae4b45579b2f53.rlib --extern regex_syntax=/playground/target/debug/deps/libregex_syntax-76c8d77671269f0e.rlib --extern remove_dir_all=/playground/target/debug/deps/libremove_dir_all-6db8331ec1c4e72f.rlib --extern reqwest=/playground/target/debug/deps/libreqwest-7bc4ac7362168b1a.rlib --extern ring=/playground/target/debug/deps/libring-c62231eb5166ba10.rlib --extern rusqlite=/playground/target/debug/deps/librusqlite-527e6c8c4bd7fbc2.rlib --extern rustc_demangle=/playground/target/debug/deps/librustc_demangle-57fef8ec284fa01a.rlib --extern rustc_version=/playground/target/debug/deps/librustc_version-ec12ab4390faad26.rlib --extern ryu=/playground/target/debug/deps/libryu-645857563d078b8d.rlib --extern safe_arch=/playground/target/debug/deps/libsafe_arch-1de410545576349c.rlib --extern same_file=/playground/target/debug/deps/libsame_file-7a3f353776f43cdd.rlib --extern scoped_threadpool=/playground/target/debug/deps/libscoped_threadpool-14c0b9d1ec39c6a3.rlib --extern scopeguard=/playground/target/debug/deps/libscopeguard-866386222a022128.rlib --extern select=/playground/target/debug/deps/libselect-a0839f0d2649d677.rlib --extern semver=/playground/target/debug/deps/libsemver-3845d4b869b2ffeb.rlib --extern semver_parser=/playground/target/debug/deps/libsemver_parser-7efa6c4b919e6f1f.rlib --extern serde=/playground/target/debug/deps/libserde-3684e637bfa7d321.rlib --extern serde_value=/playground/target/debug/deps/libserde_value-63b56d3699511569.rlib --extern serde_derive=/playground/target/debug/deps/libserde_derive-c065d08584cc9db8.so --extern serde_json=/playground/target/debug/deps/libserde_json-4032a327e3d89ce9.rlib --extern serde_urlencoded=/playground/target/debug/deps/libserde_urlencoded-d8cfc4a20f41f11e.rlib --extern serde_yaml=/playground/target/debug/deps/libserde_yaml-8952969c50ab0e7a.rlib --extern sha1=/playground/target/debug/deps/libsha1-cbeda663e5798c25.rlib --extern sha1_smol=/playground/target/debug/deps/libsha1_smol-d45ade8d066501af.rlib --extern sha2=/playground/target/debug/deps/libsha2-c6bbdac1068b321a.rlib --extern signal_hook_registry=/playground/target/debug/deps/libsignal_hook_registry-bdc6341b828276a3.rlib --extern simba=/playground/target/debug/deps/libsimba-1a07e71d055e5dbd.rlib --extern siphasher=/playground/target/debug/deps/libsiphasher-84a2d6040737f0d8.rlib --extern slab=/playground/target/debug/deps/libslab-c520fbff169c4b44.rlib --extern smallvec=/playground/target/debug/deps/libsmallvec-fa8917f2c89b12f3.rlib --extern smawk=/playground/target/debug/deps/libsmawk-6ed7cfb7fa793e0c.rlib --extern socket2=/playground/target/debug/deps/libsocket2-fc132cb7957dde8c.rlib --extern spin_0_5_2=/playground/target/debug/deps/libspin-4d2c7b2ce1e7d317.rlib --extern spin=/playground/target/debug/deps/libspin-48d6d352f1bb0532.rlib --extern string_cache=/playground/target/debug/deps/libstring_cache-6d49a3ac64bc79fa.rlib --extern string_cache_codegen=/playground/target/debug/deps/libstring_cache_codegen-de65e049aabbba2d.rlib --extern stringprep=/playground/target/debug/deps/libstringprep-96ff0362f02b1fad.rlib --extern strsim=/playground/target/debug/deps/libstrsim-f8a23f77c73daaa0.rlib --extern subtle=/playground/target/debug/deps/libsubtle-7f658a021fbf8c09.rlib --extern syn=/playground/target/debug/deps/libsyn-dde7d2a6d9d6c849.rlib --extern tar=/playground/target/debug/deps/libtar-5c49385973a05408.rlib --extern tempfile=/playground/target/debug/deps/libtempfile-b5e8ab437410f24a.rlib --extern tendril=/playground/target/debug/deps/libtendril-21a5e8f6857fa604.rlib --extern termcolor=/playground/target/debug/deps/libtermcolor-be5ff8b1f3327763.rlib --extern terminal_size=/playground/target/debug/deps/libterminal_size-b0bb77bf5ace48e9.rlib --extern textwrap=/playground/target/debug/deps/libtextwrap-f939c05641f0df59.rlib --extern thiserror=/playground/target/debug/deps/libthiserror-a134c794e0a109a4.rlib --extern thiserror_impl=/playground/target/debug/deps/libthiserror_impl-e97bfcc32c63f2ad.so --extern thread_id=/playground/target/debug/deps/libthread_id-37d239b95c6a3ced.rlib --extern thread_local=/playground/target/debug/deps/libthread_local-c1d855f0df39de75.rlib --extern threadpool=/playground/target/debug/deps/libthreadpool-1b333e5239e5d363.rlib --extern tiff=/playground/target/debug/deps/libtiff-7a48d8f0882e75e7.rlib --extern time_0_1_44=/playground/target/debug/deps/libtime-e811b6cc5769c529.rlib --extern time=/playground/target/debug/deps/libtime-e184b040e295a605.rlib --extern time_macros=/playground/target/debug/deps/libtime_macros-7713ab67b11274b5.so --extern tinyvec=/playground/target/debug/deps/libtinyvec-dc4514b9dd61f4ff.rlib --extern tinyvec_macros=/playground/target/debug/deps/libtinyvec_macros-8f36f65da14d810a.rlib --extern tokio=/playground/target/debug/deps/libtokio-ef41e9eb3d7e224b.rlib --extern tokio_io=/playground/target/debug/deps/libtokio_io-cce0af20664fff78.rlib --extern tokio_macros=/playground/target/debug/deps/libtokio_macros-2ee8b77c8acce1c2.so --extern tokio_native_tls=/playground/target/debug/deps/libtokio_native_tls-dc06e0cdbb0412da.rlib --extern tokio_postgres=/playground/target/debug/deps/libtokio_postgres-8c0a6cad672af46e.rlib --extern tokio_util=/playground/target/debug/deps/libtokio_util-b09d73a6f1af20ef.rlib --extern toml=/playground/target/debug/deps/libtoml-35be2da798691577.rlib --extern tower_service=/playground/target/debug/deps/libtower_service-1acfe98d5d51417b.rlib --extern tracing=/playground/target/debug/deps/libtracing-019abeee57511229.rlib --extern tracing_core=/playground/target/debug/deps/libtracing_core-b2525e361153c0ad.rlib --extern traitobject=/playground/target/debug/deps/libtraitobject-ac408b27f7e01f65.rlib --extern try_lock=/playground/target/debug/deps/libtry_lock-849bac2fba98b76b.rlib --extern typemap=/playground/target/debug/deps/libtypemap-0e4274a17e401313.rlib --extern typenum=/playground/target/debug/deps/libtypenum-37db19a11d859610.rlib --extern ucd_trie=/playground/target/debug/deps/libucd_trie-2d4e8d499debe73d.rlib --extern unicase=/playground/target/debug/deps/libunicase-a9d514baad760bab.rlib --extern unicode_bidi=/playground/target/debug/deps/libunicode_bidi-876cf42c358ea953.rlib --extern unicode_ident=/playground/target/debug/deps/libunicode_ident-1fd5bb97f6763612.rlib --extern unicode_linebreak=/playground/target/debug/deps/libunicode_linebreak-c2550947826181ed.rlib --extern unicode_normalization=/playground/target/debug/deps/libunicode_normalization-b5fe20e16f4308b7.rlib --extern unicode_segmentation=/playground/target/debug/deps/libunicode_segmentation-f0157503fd36f1a8.rlib --extern unicode_width=/playground/target/debug/deps/libunicode_width-06f3e9124c42e8b3.rlib --extern unicode_xid=/playground/target/debug/deps/libunicode_xid-cdda0f5739040db0.rlib --extern unsafe_any=/playground/target/debug/deps/libunsafe_any-843b450d6d60d480.rlib --extern untrusted=/playground/target/debug/deps/libuntrusted-ecc06c34234b2716.rlib --extern url=/playground/target/debug/deps/liburl-f6d5e563d88828fe.rlib --extern utf8=/playground/target/debug/deps/libutf8-8dc7fb5a31151cba.rlib --extern uuid=/playground/target/debug/deps/libuuid-14e915a867eb1794.rlib --extern vcpkg=/playground/target/debug/deps/libvcpkg-ad2c320523f78ca3.rlib --extern vec_map=/playground/target/debug/deps/libvec_map-d4f07e9e0554b315.rlib --extern version_check=/playground/target/debug/deps/libversion_check-2dcd18eb3e92f0ef.rlib --extern walkdir=/playground/target/debug/deps/libwalkdir-5f8042bccd6ce967.rlib --extern want=/playground/target/debug/deps/libwant-b6d427a51e848a6e.rlib --extern weezl=/playground/target/debug/deps/libweezl-247556dd31aa46ac.rlib --extern wide=/playground/target/debug/deps/libwide-942cf06bc56c2a43.rlib --extern winapi=/playground/target/debug/deps/libwinapi-a44a1f0795359a1e.rlib --extern xattr=/playground/target/debug/deps/libxattr-219a4a84178e71d7.rlib --extern xml5ever=/playground/target/debug/deps/libxml5ever-7e0d60e66d3a11da.rlib --extern yaml_rust=/playground/target/debug/deps/libyaml_rust-630e276985e58fd0.rlib -L native=/playground/target/debug/build/libsqlite3-sys-c8242252090cbd4a/out -L native=/playground/target/debug/build/ring-bffb4b05604ef318/out` (signal: 6, SIGABRT: process abort signal)
```

</p>
</details>

### PR DESCRIPTION
**Pull request by compiler-errors**
The "root cause" is that we call `InferCtxt::resolve_vars_if_possible` (3d9dd681f520d1d59f38aed0056cf9474894cc74) on the types we get back in `TypeError::Sorts` since I added a call to it in `InferCtxt::same_type_modulo_infer`. However if this `TypeError` comes from a `InferCtxt::commit_if_ok`, then it may reference type variables that do not exist anymore, which is problematic.

We avoid this by substituting the `TypeError` with the types we had before being generalized while handling opaques.

This is kinda gross, and I feel like we can get the same issue from other places where we generalize type/const inference variables. Maybe not? I don't know.

Fixes #99914
Fixes #99970
Fixes #100463

### CODE REVIEW

**Comment by compiler-errors** [comment]
@oli-obk, do you mind taking a look at this? There are quite a repeated reports of this issue..

**Comment by oli-obk** [comment]
🙈 thanks for bumping it, it was too far back in the notification list and I haven't caught up yet

File: compiler/rustc_infer/src/infer/sub.rs [hunk 1]
```diff
@@ -141,17 +142,27 @@ impl<'tcx> TypeRelation<'tcx> for Sub<'_, '_, 'tcx> {
...
                     _ => unreachable!(),
                 };
                 self.fields.obligations.extend(
                     infcx
-                        .handle_opaque_type(a, b, true, &self.fields.trace.cause, self.param_env())?
+                        .handle_opaque_type(ga, gb, true, &self.fields.trace.cause, self.param_env())
+                        // Don't leak any generalized type variables out of this
+                        // subtyping relation in the case of a type error.
+                        .map_err(|err| {
+                            let (ga, gb) = self.fields.infcx.resolve_vars_if_possible((ga, gb));
```
Comment (compiler-errors) [inline compiler/rustc_infer/src/infer/sub.rs:156]: This is probably overkill, and we maybe should just do something like `.map_err(|_| TypeError::Sorts(ExpectedFound { expected: a, found: b }))` instead.

Comment (oli-obk) [reply compiler/rustc_infer/src/infer/sub.rs:156]: yea, I was just checking out all error sources in `handle_opaque_types`, and they all boil down to calling `infcx.at(...).eq(x, y)?` in some manner. The issue is that sometimes it's not `a` and `b` as passed, but another previously registered hidden type. Then you want to report the previous hidden type mismatching the new hidden type.

So I guess I'm saying there is a version of this issue where your change will actually not catch it. Trying to produce an example now

Comment (oli-obk) [reply compiler/rustc_infer/src/infer/sub.rs:156]: I was unable to reproduce the issue in the defining scope (that doesn't mean it's not possible, just that I gave up for now ^^). I found this absolutely useless diagnostic though: https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=b80473c86172959763c139535154c3f9

Did some more thinking and I'm wondering now if the `did.is_local()` check should actually be `infcx.opaque_type_origin(did).is_some()` so we only generate those generalized inference vars if we're actually able to handle the opaque type. I was kinda hoping to keep that isolated in `handle_opaque_type`, but that appears to have been a misplaced hope.

One more thing is that we're using `eq` inside `handle_opaque_types` when it should probably be using the relation that is calling `handle_opaque_types`. So maybe we could scrap the entire generalization logic and just always invoke `handle_opaque_types` by passing the relation as an argument and forwarding to that instead of using `eq`.

so many possibilities to try out. Let's merge this PR for now and I'm moving this comment to an issue so we can continue there.
