### PR TITLE
E0072 update error format

### LINKED ISSUE #35506: E0072 needs to be updated to new format
From: src/test/compile-fail/E0072.rs

Error E0072 needs a span_label, updating it from:

```
error[E0072]: recursive type `ListNode` has infinite size
  --> src/test/compile-fail/E0072.rs:11:1
   |
11 | struct ListNode { //~ ERROR E0072
   | ^
   |
   = help: insert indirection (e.g., a `Box`, `Rc`, or `&`) at some point to make `ListNode` representable

error: aborting due to previous error
```

To:

```
error[E0072]: recursive type `ListNode` has infinite size
  --> src/test/compile-fail/E0072.rs:11:1
   |
11 | struct ListNode { //~ ERROR E0072
   | ^ recursive type has infinite size
   |
   = help: insert indirection (e.g., a `Box`, `Rc`, or `&`) at some point to make `ListNode` representable

error: aborting due to previous error
```

Bonus: put the span on the name of the struct:

```
error[E0072]: recursive type `ListNode` has infinite size
  --> src/test/compile-fail/E0072.rs:11:1
   |
11 | struct ListNode { //~ ERROR E0072
   |        ^^^^^^^^ recursive type has infinite size
   |
   = help: insert indirection (e.g., a `Box`, `Rc`, or `&`) at some point to make `ListNode` representable

error: aborting due to previous error
```

### PR DESCRIPTION
**Pull request by circuitfox**
Part of  #35233 

Fixes #35506 

r? @jonathandturner 

The bonus for this issue currently seems to be impossible to do reliably, as the compiler seems to lack span information for item names alone, like `Foo` in `struct Foo { ... }`. It would be possible to hack something together by computing span offsets, but that seems like a solution that would be begging for trouble.

A proper solution to this would, of course, be to add span information to the right place (seems to be `rustc::hir::Item::name` but I may be wrong).

### CODE REVIEW

**Comment by jonathandturner** [comment]
Looks good!

@bors r+ rollup

File: src/librustc/traits/error_reporting.rs [hunk 1]
```diff
@@ -654,6 +654,7 @@ impl<'a, 'gcx, 'tcx> TyCtxt<'a, 'gcx, 'tcx> {
         let mut err = struct_span_err!(self.sess, span, E0072,
                                        "recursive type `{}` has infinite size",
                                        self.item_path_str(type_def_id));
+        err.span_label(span, &format!("recursive type has infinite size"));
```
Comment (aravind-pg) [inline src/librustc/traits/error_reporting.rs]: Seems like the call to `format!` is unnecessary?

Comment (jonathandturner) [inline src/librustc/traits/error_reporting.rs]: it's not technically required here, though harmless.
