### PR TITLE
Fix ICE caused by truncating a negative ZST enum discriminant

### LINKED ISSUE #70114: ICE when casting negative discriminant enum values to anything less than bit width
Compiling this code on [playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=5d837277ab57f55258ef488c9bd7d3b3):
``` rust
enum Nums {
    NegOne = -1,
}

fn main() {
    let kind = Nums::NegOne;
    let _v = kind as i32;
}
```
results in ICE. Casting to anything smaller than `usize`/`isize`(`u32`, `u16`, `i16`, `u8`, `i8`, etc) also results in ICE. Casting to anything same size or larger(`u128`, `i128`, `u64`, `i64`, etc) works fine. Positive discriminant values also work fine.
Version of rustc: `rustc 1.42.0 (b8cedc004 2020-03-09) running on x86_64-unknown-linux-gnu`(on rust playground)
Compiler flags listed as used: `-C codegen-units=1 -C debuginfo=2 --crate-type bin`

### PR DESCRIPTION
**Pull request by wesleywiser**
Fixes #70114 

r? @oli-obk or @RalfJung

### CODE REVIEW

File: src/test/ui/consts/issue-70114.rs [hunk 1]
```diff
@@ -0,0 +1,12 @@
+// build-pass
```
Comment (Centril) [inline src/test/ui/consts/issue-70114.rs]: Nit: if you could make the file name more descriptive that'd be great. :)

File: src/librustc_mir/interpret/cast.rs [hunk 2]
```diff
@@ -134,7 +134,7 @@ impl<'mir, 'tcx, M: Machine<'mir, 'tcx>> InterpCx<'mir, 'tcx, M> {
             layout::Variants::Single { index } => {
                 if let Some(discr) = src.layout.ty.discriminant_for_variant(*self.tcx, index) {
                     assert!(src.layout.is_zst());
-                    return Ok(Scalar::from_uint(discr.val, dest_layout.size).into());
+                    return Ok(self.cast_from_int(discr.val, src.layout, dest_layout)?.into());
```
Comment (RalfJung) [inline src/librustc_mir/interpret/cast.rs]: Hm this intuitively seems reasonable... @eddyb is this (more) correct?

File: src/test/ui/consts/issue-70114.rs [hunk 3]
```diff
@@ -0,0 +1,12 @@
...
+
+// Test a ZST enum whose dicriminant is ~0i128. This caused an ICE when casting to a i32.
+
+enum Nums {
+    NegOne = -1,
+}
+
+fn main() {
+    let kind = Nums::NegOne;
+    let _v = kind as i32;
```
Comment (RalfJung) [inline src/test/ui/consts/issue-70114.rs]: Could you `assert!` that the result of the conversion is correct?
Also, I think the reason this triggers here is const-prop. So it's probably best to just move this to a `const` explicitly so we can see it runs in const context.

Also the issue says shorter types are a problem, so maybe add a cast to `i8` as well?

File: src/librustc_mir/interpret/cast.rs (hunk 2 above)
Comment (eddyb) [reply src/librustc_mir/interpret/cast.rs]: Probably, but instead of `src.layout` this should use `self.layout_of(discr.ty)` or similar.

Judging by the `cast_from_int` code, the PR as-is would still produce the wrong value for casting to `i128`.

[And I just checked and it's broken for runtime code too](https://play.rust-lang.org/?version=nightly&mode=release&edition=2018&gist=2cfe79f47d7b241d9e0e745f7905ca0e).

Comment (eddyb) [reply src/librustc_mir/interpret/cast.rs]: For context, [this is with both univariant and regular `enum`](https://play.rust-lang.org/?version=nightly&mode=release&edition=2018&gist=9eb37ff88a11ae7a0b48c376ea0265e4).

File: src/test/ui/consts/issue-70114.rs (hunk 3 above)
Comment (eddyb) [reply src/test/ui/consts/issue-70114.rs]: I think this test should include every single type and they should all end up as `-1`.
Including `i128` which is currently broken even for runtime code (see my other comments).

File: src/librustc_mir/interpret/cast.rs (hunk 2 above)
Comment (RalfJung) [reply src/librustc_mir/interpret/cast.rs]: So the discriminant has a different layout that the enum, even though the enum consists only of the discriminant? Nasty.

> And I just checked and it's broken for runtime code too

oO

Comment (RalfJung) [reply src/librustc_mir/interpret/cast.rs]: >  this is with both univariant and regular enum.

So with regular enums it is working correctly, is what you are saying? ("This is" sounds like you are saying both are bugged.)

Comment (eddyb) [reply src/librustc_mir/interpret/cast.rs]: Maybe `ty::layout::Abi` having an `is_signed` method was a bad idea, `cast_from_int` should IMO ICE if `src_layout.abi` isn't `Abi::Scalar`.

Comment (RalfJung) [reply src/librustc_mir/interpret/cast.rs]: > cast_from_int should IMO ICE if src_layout.abi isn't Abi::Scalar

That sounds reasonable, yes.

> Maybe ty::layout::Abi having an is_signed method was a bad idea

We could make that method ICE if the abi isn't `Scalar`?

Comment (eddyb) [reply src/librustc_mir/interpret/cast.rs]: @RalfJung Sorry, "this is" just referred to the link, a non-univariant enum works fine as you can see if you run the test.

> So the discriminant has a different layout that the enum, even though the enum consists only of the discriminant? Nasty.

Univariant enums have no discriminant representation, be it tag or otherwise, and `discr` is the discriminant value of the type that it's type-checked as (`isize` by default, changes with `#[repr(iN)]`, but I believe `#[repr]` also disables ZST univariant `enum`s)

Comment (eddyb) [reply src/librustc_mir/interpret/cast.rs]: > We could make that method ICE if the `abi` isn't `Scalar`?

I just checked and only miri appears to use that method. Consider checking if the type is signed instead, I guess.

File: src/test/ui/consts/issue-70114.rs (hunk 3 above)
Comment (RalfJung) [reply src/test/ui/consts/issue-70114.rs]: So the test should probably cover const-time and run-time code then.
We can avoid const-prop by feeding values through a function like
```rust
#[inline(never)]
fn black_box<T>(x: T) -> T { x }
```

File: src/librustc_mir/interpret/cast.rs (hunk 2 above)
Comment (RalfJung) [reply src/librustc_mir/interpret/cast.rs]: > Consider checking if the type is signed instead, I guess.

What do you mean? Using [this](https://doc.rust-lang.org/nightly/nightly-rustc/rustc/ty/struct.TyS.html#method.is_signed)? Note that this also does not complain about use on non-integer types.

File: src/test/ui/consts/issue-70114.rs (hunk 3 above)
Comment (eddyb) [reply src/test/ui/consts/issue-70114.rs]: A problem there is you don't need the value of an univariant `enum` to compute the case, because it's ZST.

Comment (eddyb) [reply src/test/ui/consts/issue-70114.rs]: Also don't we just call that function `identity` in tests?

Comment (RalfJung) [reply src/test/ui/consts/issue-70114.rs]: We call it different things I think...^^

File: src/librustc_mir/interpret/cast.rs (hunk 2 above)
Comment (RalfJung) [reply src/librustc_mir/interpret/cast.rs]: @eddyb do you think we can make `TyS::is_signed` ICE on non-integer? It seems to have the exact same problem (and just switching to it here would not have prevented this bug).

Comment (eddyb) [reply src/librustc_mir/interpret/cast.rs]: Fair, `cast_from_int` should exhaustively match on `Ty::Int(_)` and `ty::UInt(_)` and not allow any other input types.

Comment (RalfJung) [reply src/librustc_mir/interpret/cast.rs]: And you are sure all the other users of that method are correct?^^

Comment (eddyb) [reply src/librustc_mir/interpret/cast.rs]: > And you are sure all the other users of that method are correct?^^

I haven't checked, no, an audit should probably be done.

Comment (wesleywiser) [reply src/librustc_mir/interpret/cast.rs]: I tried to add the cases mentioned above to the test ([here](https://github.com/rust-lang/rust/pull/70126/commits/14e7cf6d4e2699f1736f86e2c62084cf68d255d8)) but the test still passes. Am I missing a failing case or does this already handle them all?

File: src/test/ui/consts/issue-70114.rs [hunk 4]
```diff
@@ -1,12 +1,34 @@
...
+    assert_eq!(-1i64, kind as i64);
+    assert_eq!(-1i128, kind as i128);
+
+    assert_eq!(-1i8, identity(kind) as i8);
+    assert_eq!(-1i16, identity(kind) as i16);
+    assert_eq!(-1i32, identity(kind) as i32);
+    assert_eq!(-1i64, identity(kind) as i64);
+    assert_eq!(-1i128, identity(kind) as i128);
+
+    test_as_args(Nums::NegOne);
```
Comment (RalfJung) [inline src/test/ui/consts/issue-70114.rs]: Could you also have one that explicitly uses consts?
```rust
const NEG_ONE_I8: i8 = Nums::NegOne as i8;

assert_eq!(-1, NEG_ONE_I8);
```

Comment (wesleywiser) [reply src/test/ui/consts/issue-70114.rs]: [Yes, absolutely](https://github.com/rust-lang/rust/pull/70126/commits/61ab908df652d482d8ce4b5530229ffa293ae766). Sorry, I missed the earlier mention of this amongst the other comments.

File: src/librustc_mir/interpret/cast.rs (hunk 2 above)
Comment (RalfJung) [reply src/librustc_mir/interpret/cast.rs]: So maybe the run-time version of this is entirely unreachable now, and @eddyb was acutally still testing the Miri version above? As @eddyb said, the input here is a ZST so this can be const-prop'ed even if the input is "unknown".

Comment (RalfJung) [reply src/librustc_mir/interpret/cast.rs]: However, I am getting the wrong behavior even with `-Zmir-opt-level=0`, and in that case there should be no const-prop...

Comment (eddyb) [reply src/librustc_mir/interpret/cast.rs]: > As @eddyb said, the input here is a ZST so this can be const-prop'ed even if the input is "unknown".

It also means codegen could have the exact same bug.

Comment (RalfJung) [reply src/librustc_mir/interpret/cast.rs]: But if it did, then why would this test pass now after @wesleywiser only fixed Miri?

Comment (eddyb) [reply src/librustc_mir/interpret/cast.rs]: Uh oh, I missed the fact that #70114 affects stable, sorry.

Comment (wesleywiser) [reply src/librustc_mir/interpret/cast.rs]: Sorry, I just realized I was running an older version of the test locally which is why it kept passing. With that corrected, the casts to `i128` are failing.

Comment (wesleywiser) [reply src/librustc_mir/interpret/cast.rs]: The commit I just pushed fixes both miri and codegen and the new test passes on all cases.

I believe the conclusion from the rest of this thread was that `cast_from_int` should check the `src_layout.ty` and only allow `ty::Int(_) | ty::UInt(_)`. I tried that but the compiler ICEs during bootstrap unless I also allow `ty::Char | ty::Bool`. Even then, various tests fail because they call `cast_from_int` with sources like enums with explicit discriminants and pointer types. 

Is adding more validation to `cast_from_int` still the right thing to do?

**Review by eddyb — APPROVED** [review]

File: src/librustc_mir/interpret/cast.rs (hunk 2 above)
Comment (eddyb) [reply src/librustc_mir/interpret/cast.rs]: > various tests fail because they call `cast_from_int` with sources like enums with explicit discriminants and pointer types.

Both of those examples sound wrong, the `tag` field of an `enum` should have an appropriate type (from `#[repr]` or `isize` by default), and pointers are clearly not integers.

Comment (RalfJung) [reply src/librustc_mir/interpret/cast.rs]: Pointers behave exactly like ptr-sized unsigned integers in casts, so it makes a lot of sense to share that code path.

Comment (wesleywiser) [reply src/librustc_mir/interpret/cast.rs]: Should I investigate more or leave this alone for now? I personally didn't find this outcome to be very surprising given there are comments like this at some of the callsites:

https://github.com/rust-lang/rust/blob/f4c675c476c18b1a11041193f2f59d695b126bc8/src/librustc_mir/interpret/cast.rs#L169-L174

**Review by RalfJung — APPROVED** [review]
LGTM too

File: src/librustc_mir/interpret/cast.rs (hunk 2 above)
Comment (RalfJung) [reply src/librustc_mir/interpret/cast.rs]: I will experiment with some sanity checks in `Abi::is_signed`; I think this PR is good as-is.

Comment (wesleywiser) [reply src/librustc_mir/interpret/cast.rs]: Thanks @RalfJung and @eddyb! I'll fix the tidy error tonight and `r=RalfJung,eddyb`.

Comment (eddyb) [reply src/librustc_mir/interpret/cast.rs]: > Pointers behave exactly like ptr-sized unsigned integers in casts

Okay but why not pass `usize` to `cast_from_int` instead of the pointer type? To me the name is a lie. Maybe it could named `cast_from_int_like`.

Comment (RalfJung) [reply src/librustc_mir/interpret/cast.rs]: > Okay but why not pass usize to cast_from_int instead of the pointer type? 

I'd rather not lie about the source type.

> `cast_from_int_like`

That seems reasonable. @wesleywiser do you want to do that in this PR?

Comment (wesleywiser) [reply src/librustc_mir/interpret/cast.rs]: Yeah, I can do that.

File: src/librustc_codegen_ssa/mir/rvalue.rs [hunk 5]
```diff
@@ -293,12 +293,17 @@ impl<'a, 'tcx, Bx: BuilderMethods<'a, 'tcx>> FunctionCx<'a, 'tcx, Bx> {
...
+                                    let discr_val = bx.cx().const_uint_big(discr_t, discr.val);
+                                    let discr_val =
+                                        bx.intcast(discr_val, ll_t_out, discr.ty.is_signed());
+
                                     return (
                                         bx,
                                         OperandRef {
                                             val: OperandValue::Immediate(discr_val),
-                                            layout: cast,
+                                            layout: discr_layout,
```
Comment (RalfJung) [inline src/librustc_codegen_ssa/mir/rvalue.rs]: Is this correct? After all, you have cast `discr_val` to `ll_t_out` already, so why would we still use the `discr_layout` layout here?

Comment (wesleywiser) [reply src/librustc_codegen_ssa/mir/rvalue.rs]: No, I think you're right.

Comment (RalfJung) [reply src/librustc_codegen_ssa/mir/rvalue.rs]: @eddyb please check this (see above)

Comment (eddyb) [reply src/librustc_codegen_ssa/mir/rvalue.rs]: Look correct on the basis of Int -> Int casts (implemented below).

**Comment by pnkfelix** [comment]
Discussed in [T-compiler meeting](https://zulip-archive.rust-lang.org/131828tcompiler/40721weeklymeeting2020032654818.html#191890509). Declining to beta-backport.
