### PR TITLE
Infer async closure args from `Fn` bound even if there is no corresponding `Future` bound on return

### LINKED ISSUE #127781: Async closure argument inference is broken with functions taking `FnOnce() -> futures::TryFuture`
I'm writing this as a continuation of https://github.com/rust-lang/rust/issues/127425

While the problem from first message in issue seems to be fixed, there are still cases when this fails.

One of examples is when using `try_for_each` instead of `for_each`, when closure is expected to return `Result`:

```rust
#![feature(async_closure)]

use anyhow::Error;
use futures::{stream::repeat_with, StreamExt, TryStreamExt};

fn accept_str(_: &str) {}
fn accept_string(_: &String) {}

#[tokio::main(flavor = "current_thread")]
async fn main() -> Result<(), Error> {

    repeat_with(|| "foo".to_owned())
        .take(1)
        .map(Result::<_, Error>::Ok)
        .try_for_each(async move |value| {
            // error on whole closure, rust thinks that type of value is `str`
            accept_str(&value);

            // type annotations needed, cannot infer type
            accept_str(value.as_str());

            // this works
            accept_string(&value); // ok
            
            Ok(())
        })
        .await?;

    Ok(())
}
```

I expected to see this happen: All options used to work in past versions of rust

Instead, this happened: Without explicit type hint it fails

### Version it worked on
It most recently worked on: Not 100% sure, some explanations have been made in original issue 

### Version with regression
```
rustc 1.81.0-nightly (d9284afea 2024-07-14)
binary: rustc
commit-hash: d9284afea99e0969a0e692b9e9fd61ea4ba21366
commit-date: 2024-07-14
host: x86_64-pc-windows-msvc
release: 1.81.0-nightly
LLVM version: 18.1.7
```

### PR DESCRIPTION
**Pull request by compiler-errors**
In #127482, I implemented the functionality to infer an async closure signature when passed into a function that has `Fn` + `Future` where clauses that look like:

```
fn whatever(callback: F)
where
  F: Fn(Arg) -> Fut,
  Fut: Future<Output = Out>,
```

However, #127781 demonstrates that this is still incomplete to address the cases users care about. So let's not bail when we fail to find a `Future` bound, and try our best to just use the args from the `Fn` bound if we find it. This is *fine* since most users of closures only really care about the *argument* types for inference guidance, since we require the receiver of a `.` method call to be known in order to probe methods.

When I experimented with programmatically rewriting `|| async {}` to `async || {}` in #127827, this also seems to have fixed ~5000 regressions (probably all coming from usages `TryFuture`/`TryStream` from futures-rs): the [before](https://github.com/rust-lang/rust/pull/127827#issuecomment-2254061733) and [after](https://github.com/rust-lang/rust/pull/127827#issuecomment-2255470176) crater runs.

Fixes #127781.

### CODE REVIEW

**Comment by nnethercote** [comment]
I'm not a good person to review a PR involving types and a "SUBTLE" comment :)

r? @lcnr

File: compiler/rustc_hir_typeck/src/closure.rs [hunk 1]
```diff
@@ -564,24 +568,36 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
...
-        None
+        // SUBTLE: If we didn't find a `Future<Output = ...>` bound for the return
+        // vid, we still want to attempt to provide inference guidance for the async
+        // closure's arguments. Instantiate a new vid to plug into the output type.
+        //
+        // You may be wondering, what if it's higher-ranked? Well, given that we
+        // found a type variable for the `FnOnce::Output` projection above, we know
+        // that the output can't mention any of the vars.
+        let return_ty =
+            return_ty.unwrap_or_else(|| self.next_ty_var(cause_span.unwrap_or(DUMMY_SP)));
```
Comment (lcnr) [inline compiler/rustc_hir_typeck/src/closure.rs:590]: why directly use the `input_tys` but create a new infer var for the `return_type`?

**Review by lcnr — COMMENTED** [review]
sgtm

File: compiler/rustc_hir_typeck/src/closure.rs (hunk 1 above)
Comment (compiler-errors) [reply compiler/rustc_hir_typeck/src/closure.rs:590]: The return type vid that is in scope is the type of the future, but we want the type of the future's output. We don't have it, so we need to make a new type var here.

Comment (lcnr) [reply compiler/rustc_hir_typeck/src/closure.rs:590]: comment please :3
