### PR TITLE
compiler: Error on layout of enums with invalid reprs

### LINKED ISSUE #126966: ICE: `non-Aggregate field with matching ABI but differing alignment`
auto-reduced (treereduce-rust):
````rust
mod assert {
    use std::mem::{Assume, BikeshedIntrinsicFrom};

    pub fn is_transmutable<Src, Dst>()
    where
        Dst: BikeshedIntrinsicFrom<Src>,
    {
    }
}

#[repr(u32)]
enum Ox00 {
    V = 0x00,
}
enum Ox01 {
    V = 0x01,
}
#[repr(C, packed(2))]
enum OxFF {
    V = 0xFF,
}

fn test() {
    #[derive]

    union Superset {
        a: Ox00,
        b: OxFF,
        b: Ox01,
    }

    assert::is_transmutable::<Superset, Subset>();
}


````

original:
````rust
#![crate_type = "lib"]
#![feature(allow)]
#![allow(dead_code, incomplete_features, non_camel_case_types)]

mod assert {
    use std::mem::{Assume, BikeshedIntrinsicFrom};

    pub fn is_transmutable<Src, Dst>()
    where
        Dst: BikeshedIntrinsicFrom<Src, { Assume::SAFETY.and(Assume::VALIDITY) }>
    {}
}

#[derive(Clone, Copy)] #[repr(u32)] enum Ox00 { V = 0x00 }
#[derive(Clone, Copy)] #[repr(u8)] enum Ox01 { V = 0x01 }
#[derive(Clone, Copy)] #[repr(C, packed(2))] enum OxFF { V = 0xFF }

fn test() {
    #[derive]
    union Subset {
        a: (),
        b: V1u8,
    }

    #[packed(C)]
    union Superset {
        a: Ox00,
        b: OxFF,
        b: Ox01,
    }

    assert::is_transmutable::<Superset, Subset>(); //~ ERROR cannot be safely transmuted
}

````

Version information
````
rustc 1.81.0-nightly (d929a42a6 2024-06-25)
binary: rustc
commit-hash: d929a42a664c026167800801b26d734db925314f
commit-date: 2024-06-25
host: x86_64-unknown-linux-gnu
release: 1.81.0-nightly
LLVM version: 18.1.7

````

Command:
`/home/matthias/.rustup/toolchains/master/bin/rustc `

<details><summary><strong>Program output</strong></summary>
<p>

```
error: malformed `derive` attribute input
  --> /tmp/icemaker_global_tempdir.WonAMZI2vcAF/rustc_testrunner_tmpdir_reporting.xuyJdDymg62q/mvce.rs:24:5
   |
24 |     #[derive]
   |     ^^^^^^^^^ help: must be of the form: `#[derive(Trait1, Trait2, ...)]`

error[E0412]: cannot find type `Subset` in this scope
  --> /tmp/icemaker_global_tempdir.WonAMZI2vcAF/rustc_testrunner_tmpdir_reporting.xuyJdDymg62q/mvce.rs:32:41
   |
32 |     assert::is_transmutable::<Superset, Subset>();
   |                                         ^^^^^^ not found in this scope
   |
help: you might be missing a type parameter
   |
23 | fn test<Subset>() {
   |        ++++++++

warning: unused import: `Assume`
 --> /tmp/icemaker_global_tempdir.WonAMZI2vcAF/rustc_testrunner_tmpdir_reporting.xuyJdDymg62q/mvce.rs:2:20
  |
2 |     use std::mem::{Assume, BikeshedIntrinsicFrom};
  |                    ^^^^^^
  |
  = note: `#[warn(unused_imports)]` on by default

error[E0601]: `main` function not found in crate `mvce`
  --> /tmp/icemaker_global_tempdir.WonAMZI2vcAF/rustc_testrunner_tmpdir_reporting.xuyJdDymg62q/mvce.rs:33:2
   |
33 | }
   |  ^ consider adding a `main` function to `/tmp/icemaker_global_tempdir.WonAMZI2vcAF/rustc_testrunner_tmpdir_reporting.xuyJdDymg62q/mvce.rs`

error[E0517]: attribute should be applied to a struct or union
  --> /tmp/icemaker_global_tempdir.WonAMZI2vcAF/rustc_testrunner_tmpdir_reporting.xuyJdDymg62q/mvce.rs:18:11
   |
18 |   #[repr(C, packed(2))]
   |             ^^^^^^^^^
19 | / enum OxFF {
20 | |     V = 0xFF,
21 | | }
   | |_- not a struct or union

error[E0658]: use of unstable library feature 'transmutability'
 --> /tmp/icemaker_global_tempdir.WonAMZI2vcAF/rustc_testrunner_tmpdir_reporting.xuyJdDymg62q/mvce.rs:2:20
  |
2 |     use std::mem::{Assume, BikeshedIntrinsicFrom};
  |                    ^^^^^^
  |
  = note: see issue #99571 <https://github.com/rust-lang/rust/issues/99571> for more information
  = help: add `#![feature(transmutability)]` to the crate attributes to enable
  = note: this compiler was built on 2024-06-25; consider upgrading it if it is out of date

error[E0658]: use of unstable library feature 'transmutability'
 --> /tmp/icemaker_global_tempdir.WonAMZI2vcAF/rustc_testrunner_tmpdir_reporting.xuyJdDymg62q/mvce.rs:2:28
  |
2 |     use std::mem::{Assume, BikeshedIntrinsicFrom};
  |                            ^^^^^^^^^^^^^^^^^^^^^
  |
  = note: see issue #99571 <https://github.com/rust-lang/rust/issues/99571> for more information
  = help: add `#![feature(transmutability)]` to the crate attributes to enable
  = note: this compiler was built on 2024-06-25; consider upgrading it if it is out of date

error[E0658]: use of unstable library feature 'transmutability'
 --> /tmp/icemaker_global_tempdir.WonAMZI2vcAF/rustc_testrunner_tmpdir_reporting.xuyJdDymg62q/mvce.rs:6:14
  |
6 |         Dst: BikeshedIntrinsicFrom<Src>,
  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: see issue #99571 <https://github.com/rust-lang/rust/issues/99571> for more information
  = help: add `#![feature(transmutability)]` to the crate attributes to enable
  = note: this compiler was built on 2024-06-25; consider upgrading it if it is out of date

error[E0124]: field `b` is already declared
  --> /tmp/icemaker_global_tempdir.WonAMZI2vcAF/rustc_testrunner_tmpdir_reporting.xuyJdDymg62q/mvce.rs:29:9
   |
28 |         b: OxFF,
   |         ------- `b` first declared here
29 |         b: Ox01,
   |         ^^^^^^^ field already declared

error[E0740]: field must implement `Copy` or be wrapped in `ManuallyDrop<...>` to be used in a union
  --> /tmp/icemaker_global_tempdir.WonAMZI2vcAF/rustc_testrunner_tmpdir_reporting.xuyJdDymg62q/mvce.rs:27:9
   |
27 |         a: Ox00,
   |         ^^^^^^^
   |
   = note: union fields must not have drop side-effects, which is currently enforced via either `Copy` or `ManuallyDrop<...>`
help: wrap the field type in `ManuallyDrop<...>`
   |
27 |         a: std::mem::ManuallyDrop<Ox00>,
   |            +++++++++++++++++++++++    +

thread 'rustc' panicked at /rustc/d929a42a664c026167800801b26d734db925314f/compiler/rustc_abi/src/layout.rs:289:29:
assertion `left == right` failed: non-Aggregate field with matching ABI but differing alignment
  left: Align(4 bytes)
 right: Align(2 bytes)
stack backtrace:
   0:     0x777bc94142e5 - std::backtrace_rs::backtrace::libunwind::trace::h3816f17667167091
                               at /rustc/d929a42a664c026167800801b26d734db925314f/library/std/src/../../backtrace/src/backtrace/libunwind.rs:116:5
   1:     0x777bc94142e5 - std::backtrace_rs::backtrace::trace_unsynchronized::h05c1a74390e79138
                               at /rustc/d929a42a664c026167800801b26d734db925314f/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x777bc94142e5 - std::sys::backtrace::_print_fmt::hf9f67f450e2340b3
                               at /rustc/d929a42a664c026167800801b26d734db925314f/library/std/src/sys/backtrace.rs:68:5
   3:     0x777bc94142e5 - <std::sys::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hd0470f4740d6f066
                               at /rustc/d929a42a664c026167800801b26d734db925314f/library/std/src/sys/backtrace.rs:44:22
   4:     0x777bc9463ceb - core::fmt::rt::Argument::fmt::h70b8a6b09781c530
                               at /rustc/d929a42a664c026167800801b26d734db925314f/library/core/src/fmt/rt.rs:165:63
   5:     0x777bc9463ceb - core::fmt::write::hafea0839d2bbb3f2
                               at /rustc/d929a42a664c026167800801b26d734db925314f/library/core/src/fmt/mod.rs:1168:21
   6:     0x777bc9408f6f - std::io::Write::write_fmt::h781fa7911c53c2fa
                               at /rustc/d929a42a664c026167800801b26d734db925314f/library/std/src/io/mod.rs:1835:15
   7:     0x777bc94140be - std::sys::backtrace::_print::h864675b81ca0e917
                               at /rustc/d929a42a664c026167800801b26d734db925314f/library/std/src/sys/backtrace.rs:47:5
   8:     0x777bc94140be - std::sys::backtrace::print::h077604854516c949
                               at /rustc/d929a42a664c026167800801b26d734db925314f/library/std/src/sys/backtrace.rs:34:9
   9:     0x777bc9416a09 - std::panicking::default_hook::{{closure}}::h0655bbcac1b3559e
  10:     0x777bc94167ac - std::panicking::default_hook::ha9e013cc76e074dd
                               at /rustc/d929a42a664c026167800801b26d734db925314f/library/std/src/panicking.rs:292:9
  11:     0x777bc59eac90 - std[e6dd88f179d4d596]::panicking::update_hook::<alloc[7519215c1642967c]::boxed::Box<rustc_driver_impl[6d6094f07793e4a9]::install_ice_hook::{closure#0}>>::{closure#0}
  12:     0x777bc94172df - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::haac7baf64299a07d
                               at /rustc/d929a42a664c026167800801b26d734db925314f/library/alloc/src/boxed.rs:2078:9
  13:     0x777bc94172df - std::panicking::rust_panic_with_hook::h9bfa469549e655b8
                               at /rustc/d929a42a664c026167800801b26d734db925314f/library/std/src/panicking.rs:804:13
  14:     0x777bc9416f07 - std::panicking::begin_panic_handler::{{closure}}::h4a967f6ef7ab4640
                               at /rustc/d929a42a664c026167800801b26d734db925314f/library/std/src/panicking.rs:670:13
  15:     0x777bc94147a9 - std::sys::backtrace::__rust_end_short_backtrace::h6bde84250dc9cd8b
                               at /rustc/d929a42a664c026167800801b26d734db925314f/library/std/src/sys/backtrace.rs:171:18
  16:     0x777bc9416be4 - rust_begin_unwind
                               at /rustc/d929a42a664c026167800801b26d734db925314f/library/std/src/panicking.rs:661:5
  17:     0x777bc94602a3 - core::panicking::panic_fmt::h036234c821d91466
                               at /rustc/d929a42a664c026167800801b26d734db925314f/library/core/src/panicking.rs:74:14
  18:     0x777bc946087f - core::panicking::assert_failed_inner::h6886c5ce8b27c112
                               at /rustc/d929a42a664c026167800801b26d734db925314f/library/core/src/panicking.rs:405:23
  19:     0x777bc6742f17 - core[672c7616ff9a88f5]::panicking::assert_failed::<rustc_abi[75a4f7491f97790a]::Align, rustc_abi[75a4f7491f97790a]::Align>
  20:     0x777bc775ea4e - rustc_ty_utils[91a81cae3f51d4c]::layout::layout_of_uncached
  21:     0x777bc774ce0b - rustc_ty_utils[91a81cae3f51d4c]::layout::layout_of
  22:     0x777bc774cd91 - rustc_query_impl[b034b92d40b1d47d]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[b034b92d40b1d47d]::query_impl::layout_of::dynamic_query::{closure#2}::{closure#0}, rustc_middle[e321b4b4f2134162]::query::erase::Erased<[u8; 16usize]>>
  23:     0x777bc774c0b6 - rustc_query_system[4a94863d7e85f976]::query::plumbing::try_execute_query::<rustc_query_impl[b034b92d40b1d47d]::DynamicConfig<rustc_query_system[4a94863d7e85f976]::query::caches::DefaultCache<rustc_middle[e321b4b4f2134162]::ty::ParamEnvAnd<rustc_middle[e321b4b4f2134162]::ty::Ty>, rustc_middle[e321b4b4f2134162]::query::erase::Erased<[u8; 16usize]>>, false, true, false>, rustc_query_impl[b034b92d40b1d47d]::plumbing::QueryCtxt, false>
  24:     0x777bc774bd45 - rustc_query_impl[b034b92d40b1d47d]::query_impl::layout_of::get_query_non_incr::__rust_end_short_backtrace
  25:     0x777bc671d5cc - rustc_middle[e321b4b4f2134162]::query::plumbing::query_get_at::<rustc_query_system[4a94863d7e85f976]::query::caches::DefaultCache<rustc_middle[e321b4b4f2134162]::ty::ParamEnvAnd<rustc_middle[e321b4b4f2134162]::ty::Ty>, rustc_middle[e321b4b4f2134162]::query::erase::Erased<[u8; 16usize]>>>
  26:     0x777bc6734531 - <rustc_transmute[483028c4aa667a77]::rustc::TransmuteTypeEnv>::is_transmutable
  27:     0x777bc79db58f - <rustc_trait_selection[acad18ec578eab22]::traits::select::SelectionContext>::confirm_candidate
  28:     0x777bc7472f11 - <rustc_trait_selection[acad18ec578eab22]::traits::select::SelectionContext>::evaluate_trait_predicate_recursively
  29:     0x777bc746ce97 - <rustc_trait_selection[acad18ec578eab22]::traits::select::SelectionContext>::evaluate_root_obligation
  30:     0x777bc746b215 - rustc_traits[8a90ea068024d15f]::evaluate_obligation::evaluate_obligation
  31:     0x777bc746aba9 - rustc_query_impl[b034b92d40b1d47d]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[b034b92d40b1d47d]::query_impl::evaluate_obligation::dynamic_query::{closure#2}::{closure#0}, rustc_middle[e321b4b4f2134162]::query::erase::Erased<[u8; 2usize]>>
  32:     0x777bc746a10f - rustc_query_system[4a94863d7e85f976]::query::plumbing::try_execute_query::<rustc_query_impl[b034b92d40b1d47d]::DynamicConfig<rustc_query_system[4a94863d7e85f976]::query::caches::DefaultCache<rustc_type_ir[567596a8266d8233]::canonical::Canonical<rustc_middle[e321b4b4f2134162]::ty::context::TyCtxt, rustc_middle[e321b4b4f2134162]::ty::ParamEnvAnd<rustc_middle[e321b4b4f2134162]::ty::predicate::Predicate>>, rustc_middle[e321b4b4f2134162]::query::erase::Erased<[u8; 2usize]>>, false, false, false>, rustc_query_impl[b034b92d40b1d47d]::plumbing::QueryCtxt, false>
  33:     0x777bc7469d64 - rustc_query_impl[b034b92d40b1d47d]::query_impl::evaluate_obligation::get_query_non_incr::__rust_end_short_backtrace
  34:     0x777bc38caa92 - <rustc_trait_selection[acad18ec578eab22]::traits::fulfill::FulfillProcessor as rustc_data_structures[66d2db66d3aeea18]::obligation_forest::ObligationProcessor>::process_obligation
  35:     0x777bc70081e7 - <rustc_data_structures[66d2db66d3aeea18]::obligation_forest::ObligationForest<rustc_trait_selection[acad18ec578eab22]::traits::fulfill::PendingPredicateObligation>>::process_obligations::<rustc_trait_selection[acad18ec578eab22]::traits::fulfill::FulfillProcessor>
  36:     0x777bc3bbbfea - <rustc_hir_typeck[673ed4476fae1319]::fn_ctxt::FnCtxt>::confirm_builtin_call
  37:     0x777bc7bb4c5d - <rustc_hir_typeck[673ed4476fae1319]::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
  38:     0x777bc7baedf6 - <rustc_hir_typeck[673ed4476fae1319]::fn_ctxt::FnCtxt>::check_block_with_expected
  39:     0x777bc7bb5760 - <rustc_hir_typeck[673ed4476fae1319]::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
  40:     0x777bc72f91f6 - rustc_hir_typeck[673ed4476fae1319]::check::check_fn
  41:     0x777bc72ed054 - rustc_hir_typeck[673ed4476fae1319]::typeck
  42:     0x777bc72eca9d - rustc_query_impl[b034b92d40b1d47d]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[b034b92d40b1d47d]::query_impl::typeck::dynamic_query::{closure#2}::{closure#0}, rustc_middle[e321b4b4f2134162]::query::erase::Erased<[u8; 8usize]>>
  43:     0x777bc736a073 - rustc_query_system[4a94863d7e85f976]::query::plumbing::try_execute_query::<rustc_query_impl[b034b92d40b1d47d]::DynamicConfig<rustc_query_system[4a94863d7e85f976]::query::caches::VecCache<rustc_span[31538c27a715cd64]::def_id::LocalDefId, rustc_middle[e321b4b4f2134162]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[b034b92d40b1d47d]::plumbing::QueryCtxt, false>
  44:     0x777bc736924d - rustc_query_impl[b034b92d40b1d47d]::query_impl::typeck::get_query_non_incr::__rust_end_short_backtrace
  45:     0x777bc7368e44 - <rustc_middle[e321b4b4f2134162]::hir::map::Map>::par_body_owners::<rustc_hir_analysis[6239ffc5e5ec24c9]::check_crate::{closure#4}>::{closure#0}
  46:     0x777bc73671c1 - rustc_hir_analysis[6239ffc5e5ec24c9]::check_crate
  47:     0x777bc735cf15 - rustc_interface[73bd107be0165211]::passes::analysis
  48:     0x777bc735cad9 - rustc_query_impl[b034b92d40b1d47d]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[b034b92d40b1d47d]::query_impl::analysis::dynamic_query::{closure#2}::{closure#0}, rustc_middle[e321b4b4f2134162]::query::erase::Erased<[u8; 1usize]>>
  49:     0x777bc7e50825 - rustc_query_system[4a94863d7e85f976]::query::plumbing::try_execute_query::<rustc_query_impl[b034b92d40b1d47d]::DynamicConfig<rustc_query_system[4a94863d7e85f976]::query::caches::SingleCache<rustc_middle[e321b4b4f2134162]::query::erase::Erased<[u8; 1usize]>>, false, false, false>, rustc_query_impl[b034b92d40b1d47d]::plumbing::QueryCtxt, false>
  50:     0x777bc7e5058f - rustc_query_impl[b034b92d40b1d47d]::query_impl::analysis::get_query_non_incr::__rust_end_short_backtrace
  51:     0x777bc7d77e3f - rustc_interface[73bd107be0165211]::interface::run_compiler::<core[672c7616ff9a88f5]::result::Result<(), rustc_span[31538c27a715cd64]::ErrorGuaranteed>, rustc_driver_impl[6d6094f07793e4a9]::run_compiler::{closure#0}>::{closure#1}
  52:     0x777bc7c37e89 - std[e6dd88f179d4d596]::sys::backtrace::__rust_begin_short_backtrace::<rustc_interface[73bd107be0165211]::util::run_in_thread_with_globals<rustc_interface[73bd107be0165211]::util::run_in_thread_pool_with_globals<rustc_interface[73bd107be0165211]::interface::run_compiler<core[672c7616ff9a88f5]::result::Result<(), rustc_span[31538c27a715cd64]::ErrorGuaranteed>, rustc_driver_impl[6d6094f07793e4a9]::run_compiler::{closure#0}>::{closure#1}, core[672c7616ff9a88f5]::result::Result<(), rustc_span[31538c27a715cd64]::ErrorGuaranteed>>::{closure#0}, core[672c7616ff9a88f5]::result::Result<(), rustc_span[31538c27a715cd64]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[672c7616ff9a88f5]::result::Result<(), rustc_span[31538c27a715cd64]::ErrorGuaranteed>>
  53:     0x777bc7c37c3a - <<std[e6dd88f179d4d596]::thread::Builder>::spawn_unchecked_<rustc_interface[73bd107be0165211]::util::run_in_thread_with_globals<rustc_interface[73bd107be0165211]::util::run_in_thread_pool_with_globals<rustc_interface[73bd107be0165211]::interface::run_compiler<core[672c7616ff9a88f5]::result::Result<(), rustc_span[31538c27a715cd64]::ErrorGuaranteed>, rustc_driver_impl[6d6094f07793e4a9]::run_compiler::{closure#0}>::{closure#1}, core[672c7616ff9a88f5]::result::Result<(), rustc_span[31538c27a715cd64]::ErrorGuaranteed>>::{closure#0}, core[672c7616ff9a88f5]::result::Result<(), rustc_span[31538c27a715cd64]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[672c7616ff9a88f5]::result::Result<(), rustc_span[31538c27a715cd64]::ErrorGuaranteed>>::{closure#2} as core[672c7616ff9a88f5]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  54:     0x777bc942116b - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hcfcb27dcb2ebeeb7
                               at /rustc/d929a42a664c026167800801b26d734db925314f/library/alloc/src/boxed.rs:2064:9
  55:     0x777bc942116b - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h7d3cd9c06edd61cc
                               at /rustc/d929a42a664c026167800801b26d734db925314f/library/alloc/src/boxed.rs:2064:9
  56:     0x777bc942116b - std::sys::pal::unix::thread::Thread::new::thread_start::h082ffbd0fcdeae0d
                               at /rustc/d929a42a664c026167800801b26d734db925314f/library/std/src/sys/pal/unix/thread.rs:108:17
  57:     0x777bc24a6ded - <unknown>
  58:     0x777bc252a0dc - <unknown>
  59:                0x0 - <unknown>

error: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: please make sure that you have updated to the latest nightly

note: rustc 1.81.0-nightly (d929a42a6 2024-06-25) running on x86_64-unknown-linux-gnu

query stack during panic:
#0 [layout_of] computing layout of `test::Superset`
#1 [evaluate_obligation] evaluating trait selection obligation `{type error}: core::mem::transmutability::BikeshedIntrinsicFrom<test::Superset, core::mem::transmutability::Assume { alignment: false, lifetimes: false, safety: false, validity: false }>`
end of query stack
error: aborting due to 9 previous errors; 1 warning emitted

Some errors have detailed explanations: E0124, E0412, E0517, E0601, E0658, E0740.
For more information about an error, try `rustc --explain E0124`.

```

</p>
</details>

@rustbot label +F-allow

### LINKED ISSUE #128870: ICE `non-Aggregate field with matching ABI but differing alignment`
auto-reduced (treereduce-rust):
````rust
#[repr(packed)]
#[repr(u32)]
enum E {
    A,
    B,
    C,
}

fn main() {
    union InvalidTag {
        int: u32,
        e: E,
    }
    let _invalid_tag = InvalidTag { int: 4 };
}


````

original:
````rust
// Regression test for issue 123710.
// Tests that the we do not ICE in KnownPanicsLint
// when a union contains an enum with an repr(packed),
// which is a repr not supported for enums

#[repr(packed)]
//~^ ERROR attribute should be applied to a struct or union
#[repr(u32)]
enum E {
    A,
    B,
    C,
}

fn main() {
    union InvalidTag {
        int: u32,
        e: E,
//~^ ERROR field must implement `Copy` or be wrapped in `ManuallyDrop<...>` to be used in a union
    }
    let _invalid_tag = InvalidTag { int: 4 };
}

````

Version information
````
rustc 1.82.0-nightly (97e72524a 2024-08-09)
binary: rustc
commit-hash: 97e72524a34994541810438258115802f8b85543
commit-date: 2024-08-09
host: x86_64-unknown-linux-gnu
release: 1.82.0-nightly
LLVM version: 19.1.0

````

Command:
`/home/matthias/.rustup/toolchains/master/bin/rustc -Zvalidate-mir`

<details><summary><strong>Program output</strong></summary>
<p>

```
error[E0517]: attribute should be applied to a struct or union
 --> /tmp/icemaker_global_tempdir.iOHXDC03JcDS/rustc_testrunner_tmpdir_reporting.IwiBfGzE7qtZ/mvce.rs:1:8
  |
1 |   #[repr(packed)]
  |          ^^^^^^
2 |   #[repr(u32)]
3 | / enum E {
4 | |     A,
5 | |     B,
6 | |     C,
7 | | }
  | |_- not a struct or union

error[E0740]: field must implement `Copy` or be wrapped in `ManuallyDrop<...>` to be used in a union
  --> /tmp/icemaker_global_tempdir.iOHXDC03JcDS/rustc_testrunner_tmpdir_reporting.IwiBfGzE7qtZ/mvce.rs:12:9
   |
12 |         e: E,
   |         ^^^^
   |
   = note: union fields must not have drop side-effects, which is currently enforced via either `Copy` or `ManuallyDrop<...>`
help: wrap the field type in `ManuallyDrop<...>`
   |
12 |         e: std::mem::ManuallyDrop<E>,
   |            +++++++++++++++++++++++ +

thread 'rustc' panicked at /rustc/97e72524a34994541810438258115802f8b85543/compiler/rustc_abi/src/layout.rs:287:29:
assertion `left == right` failed: non-Aggregate field with matching ABI but differing alignment
  left: Align(4 bytes)
 right: Align(1 bytes)
stack backtrace:
   0:     0x7b1c4dc78c9d - std::backtrace_rs::backtrace::libunwind::trace::h6d8f9caaadd7fb58
                               at /rustc/97e72524a34994541810438258115802f8b85543/library/std/src/../../backtrace/src/backtrace/libunwind.rs:116:5
   1:     0x7b1c4dc78c9d - std::backtrace_rs::backtrace::trace_unsynchronized::h17be7deb44f4a166
                               at /rustc/97e72524a34994541810438258115802f8b85543/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7b1c4dc78c9d - std::sys::backtrace::_print_fmt::h9644a3e199661ff7
                               at /rustc/97e72524a34994541810438258115802f8b85543/library/std/src/sys/backtrace.rs:66:9
   3:     0x7b1c4dc78c9d - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::h19f5bb40323ef90a
                               at /rustc/97e72524a34994541810438258115802f8b85543/library/std/src/sys/backtrace.rs:39:26
   4:     0x7b1c4dcc942b - core::fmt::rt::Argument::fmt::h04004c0c7b9c8c68
                               at /rustc/97e72524a34994541810438258115802f8b85543/library/core/src/fmt/rt.rs:173:76
   5:     0x7b1c4dcc942b - core::fmt::write::h038b15e88d4c08dd
                               at /rustc/97e72524a34994541810438258115802f8b85543/library/core/src/fmt/mod.rs:1178:21
   6:     0x7b1c4dc6cb33 - std::io::Write::write_fmt::h336c1ed0f6805c7d
                               at /rustc/97e72524a34994541810438258115802f8b85543/library/std/src/io/mod.rs:1823:15
   7:     0x7b1c4dc7b492 - std::sys::backtrace::BacktraceLock::print::h32f152afdca981eb
                               at /rustc/97e72524a34994541810438258115802f8b85543/library/std/src/sys/backtrace.rs:42:9
   8:     0x7b1c4dc7b492 - std::panicking::default_hook::{{closure}}::h2a41f7f3fcf3abf5
                               at /rustc/97e72524a34994541810438258115802f8b85543/library/std/src/panicking.rs:266:22
   9:     0x7b1c4dc7b0fe - std::panicking::default_hook::h83a4d780a2fde4cb
                               at /rustc/97e72524a34994541810438258115802f8b85543/library/std/src/panicking.rs:293:9
  10:     0x7b1c4a0c0177 - std[8905f2cde1cc7662]::panicking::update_hook::<alloc[5e51d0ec9144a24f]::boxed::Box<rustc_driver_impl[409c18a6a244b347]::install_ice_hook::{closure#0}>>::{closure#0}
  11:     0x7b1c4dc7be82 - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::ha95e7459ace54ce3
                               at /rustc/97e72524a34994541810438258115802f8b85543/library/alloc/src/boxed.rs:2164:9
  12:     0x7b1c4dc7be82 - std::panicking::rust_panic_with_hook::h69861f8a9f68140e
                               at /rustc/97e72524a34994541810438258115802f8b85543/library/std/src/panicking.rs:805:13
  13:     0x7b1c4dc7bb37 - std::panicking::begin_panic_handler::{{closure}}::haee2c71d9d77450d
                               at /rustc/97e72524a34994541810438258115802f8b85543/library/std/src/panicking.rs:671:13
  14:     0x7b1c4dc79189 - std::sys::backtrace::__rust_end_short_backtrace::h13dd402901136d07
                               at /rustc/97e72524a34994541810438258115802f8b85543/library/std/src/sys/backtrace.rs:170:18
  15:     0x7b1c4dc7b7c4 - rust_begin_unwind
                               at /rustc/97e72524a34994541810438258115802f8b85543/library/std/src/panicking.rs:662:5
  16:     0x7b1c4dcc5a83 - core::panicking::panic_fmt::haa28ca6654179c80
                               at /rustc/97e72524a34994541810438258115802f8b85543/library/core/src/panicking.rs:74:14
  17:     0x7b1c4dcc605f - core::panicking::assert_failed_inner::hb8e7362e4cbedd62
                               at /rustc/97e72524a34994541810438258115802f8b85543/library/core/src/panicking.rs:407:23
  18:     0x7b1c4aeb9477 - core[ed2708e6dfab5976]::panicking::assert_failed::<rustc_abi[b00cdd2b010d33b3]::Align, rustc_abi[b00cdd2b010d33b3]::Align>
  19:     0x7b1c4bffeba5 - rustc_ty_utils[8fe1d6497c51be38]::layout::layout_of_uncached
  20:     0x7b1c4bff653d - rustc_ty_utils[8fe1d6497c51be38]::layout::layout_of
  21:     0x7b1c4bff64d1 - rustc_query_impl[a3ff9df8c87d6bf9]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[a3ff9df8c87d6bf9]::query_impl::layout_of::dynamic_query::{closure#2}::{closure#0}, rustc_middle[4c63caae2dc30deb]::query::erase::Erased<[u8; 16usize]>>
  22:     0x7b1c4bff57d2 - rustc_query_system[ae5d59fa4dc61faf]::query::plumbing::try_execute_query::<rustc_query_impl[a3ff9df8c87d6bf9]::DynamicConfig<rustc_query_system[ae5d59fa4dc61faf]::query::caches::DefaultCache<rustc_middle[4c63caae2dc30deb]::ty::ParamEnvAnd<rustc_middle[4c63caae2dc30deb]::ty::Ty>, rustc_middle[4c63caae2dc30deb]::query::erase::Erased<[u8; 16usize]>>, false, true, false>, rustc_query_impl[a3ff9df8c87d6bf9]::plumbing::QueryCtxt, false>
  23:     0x7b1c4bff546f - rustc_query_impl[a3ff9df8c87d6bf9]::query_impl::layout_of::get_query_non_incr::__rust_end_short_backtrace
  24:     0x7b1c48d498a8 - <rustc_mir_transform[eb83fea80f9dad86]::remove_zsts::RemoveZsts as rustc_middle[4c63caae2dc30deb]::mir::MirPass>::run_pass
  25:     0x7b1c4b601d35 - rustc_mir_transform[eb83fea80f9dad86]::pass_manager::run_passes_inner
  26:     0x7b1c4c180b61 - rustc_mir_transform[eb83fea80f9dad86]::optimized_mir
  27:     0x7b1c4c1649db - rustc_query_impl[a3ff9df8c87d6bf9]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[a3ff9df8c87d6bf9]::query_impl::optimized_mir::dynamic_query::{closure#2}::{closure#0}, rustc_middle[4c63caae2dc30deb]::query::erase::Erased<[u8; 8usize]>>
  28:     0x7b1c4b95a11f - rustc_query_system[ae5d59fa4dc61faf]::query::plumbing::try_execute_query::<rustc_query_impl[a3ff9df8c87d6bf9]::DynamicConfig<rustc_query_system[ae5d59fa4dc61faf]::query::caches::DefIdCache<rustc_middle[4c63caae2dc30deb]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[a3ff9df8c87d6bf9]::plumbing::QueryCtxt, false>
  29:     0x7b1c4b9598f3 - rustc_query_impl[a3ff9df8c87d6bf9]::query_impl::optimized_mir::get_query_non_incr::__rust_end_short_backtrace
  30:     0x7b1c485ba7a8 - <rustc_middle[4c63caae2dc30deb]::ty::context::TyCtxt>::instance_mir
  31:     0x7b1c4b977e55 - rustc_interface[69b3ddcd41152fad]::passes::run_required_analyses
  32:     0x7b1c4c21381e - rustc_interface[69b3ddcd41152fad]::passes::analysis
  33:     0x7b1c4c2137f1 - rustc_query_impl[a3ff9df8c87d6bf9]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[a3ff9df8c87d6bf9]::query_impl::analysis::dynamic_query::{closure#2}::{closure#0}, rustc_middle[4c63caae2dc30deb]::query::erase::Erased<[u8; 1usize]>>
  34:     0x7b1c4c5ec0ae - rustc_query_system[ae5d59fa4dc61faf]::query::plumbing::try_execute_query::<rustc_query_impl[a3ff9df8c87d6bf9]::DynamicConfig<rustc_query_system[ae5d59fa4dc61faf]::query::caches::SingleCache<rustc_middle[4c63caae2dc30deb]::query::erase::Erased<[u8; 1usize]>>, false, false, false>, rustc_query_impl[a3ff9df8c87d6bf9]::plumbing::QueryCtxt, false>
  35:     0x7b1c4c5ebe0f - rustc_query_impl[a3ff9df8c87d6bf9]::query_impl::analysis::get_query_non_incr::__rust_end_short_backtrace
  36:     0x7b1c4c46efe0 - rustc_interface[69b3ddcd41152fad]::interface::run_compiler::<core[ed2708e6dfab5976]::result::Result<(), rustc_span[b1343f73fcced4f1]::ErrorGuaranteed>, rustc_driver_impl[409c18a6a244b347]::run_compiler::{closure#0}>::{closure#1}
  37:     0x7b1c4c409509 - std[8905f2cde1cc7662]::sys::backtrace::__rust_begin_short_backtrace::<rustc_interface[69b3ddcd41152fad]::util::run_in_thread_with_globals<rustc_interface[69b3ddcd41152fad]::util::run_in_thread_pool_with_globals<rustc_interface[69b3ddcd41152fad]::interface::run_compiler<core[ed2708e6dfab5976]::result::Result<(), rustc_span[b1343f73fcced4f1]::ErrorGuaranteed>, rustc_driver_impl[409c18a6a244b347]::run_compiler::{closure#0}>::{closure#1}, core[ed2708e6dfab5976]::result::Result<(), rustc_span[b1343f73fcced4f1]::ErrorGuaranteed>>::{closure#0}, core[ed2708e6dfab5976]::result::Result<(), rustc_span[b1343f73fcced4f1]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[ed2708e6dfab5976]::result::Result<(), rustc_span[b1343f73fcced4f1]::ErrorGuaranteed>>
  38:     0x7b1c4c4092b2 - <<std[8905f2cde1cc7662]::thread::Builder>::spawn_unchecked_<rustc_interface[69b3ddcd41152fad]::util::run_in_thread_with_globals<rustc_interface[69b3ddcd41152fad]::util::run_in_thread_pool_with_globals<rustc_interface[69b3ddcd41152fad]::interface::run_compiler<core[ed2708e6dfab5976]::result::Result<(), rustc_span[b1343f73fcced4f1]::ErrorGuaranteed>, rustc_driver_impl[409c18a6a244b347]::run_compiler::{closure#0}>::{closure#1}, core[ed2708e6dfab5976]::result::Result<(), rustc_span[b1343f73fcced4f1]::ErrorGuaranteed>>::{closure#0}, core[ed2708e6dfab5976]::result::Result<(), rustc_span[b1343f73fcced4f1]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[ed2708e6dfab5976]::result::Result<(), rustc_span[b1343f73fcced4f1]::ErrorGuaranteed>>::{closure#1} as core[ed2708e6dfab5976]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  39:     0x7b1c4dc85b9b - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h706c4c27c8278947
                               at /rustc/97e72524a34994541810438258115802f8b85543/library/alloc/src/boxed.rs:2150:9
  40:     0x7b1c4dc85b9b - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h267b705fa7be0ba5
                               at /rustc/97e72524a34994541810438258115802f8b85543/library/alloc/src/boxed.rs:2150:9
  41:     0x7b1c4dc85b9b - std::sys::pal::unix::thread::Thread::new::thread_start::h109d3e899700b4bb
                               at /rustc/97e72524a34994541810438258115802f8b85543/library/std/src/sys/pal/unix/thread.rs:110:17
  42:     0x7b1c46aa6ded - <unknown>
  43:     0x7b1c46b2a0dc - <unknown>
  44:                0x0 - <unknown>

error: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: please make sure that you have updated to the latest nightly

note: rustc 1.82.0-nightly (97e72524a 2024-08-09) running on x86_64-unknown-linux-gnu

note: compiler flags: -Z validate-mir -Z dump-mir-dir=dir

query stack during panic:
#0 [layout_of] computing layout of `main::InvalidTag`
#1 [optimized_mir] optimizing MIR for `main`
end of query stack
error: aborting due to 2 previous errors

Some errors have detailed explanations: E0517, E0740.
For more information about an error, try `rustc --explain E0517`.

```

</p>
</details>

### PR DESCRIPTION
**Pull request by workingjubilee**
Surprising no one, the ICEs with the same message have the same root cause.

Invalid reprs can reach layout computation for various reasons. For instance, the compiler may want to use its layout computations to discern if a combination of layout-affecting attributes results in a valid type to begin with by e.g. computing its size. When the input is bad, return an error reflecting that the answer to the question is not a useful one.

- Closes #126966
- Closes #128870

### CODE REVIEW

File: src/tools/rust-analyzer/crates/hir-ty/src/layout.rs [hunk 1]
```diff
@@ -90,6 +92,7 @@ impl std::error::Error for LayoutError {}
 impl fmt::Display for LayoutError {
     fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
         match self {
+            LayoutError::BadCalc(err) => write!(f, "{}", err.fallback_fmt()),
```
Comment (lnicola) [inline src/tools/rust-analyzer/crates/hir-ty/src/layout.rs:95]:
```suggestion
            LayoutError::BadCalc(err) => err.fallback_fmt(f),
```

File: compiler/rustc_abi/src/layout.rs [hunk 2]
```diff
@@ -54,6 +54,36 @@ pub enum LayoutCalculatorError<F> {
...
+            LayoutCalculatorError::EmptyUnion => LayoutCalculatorError::EmptyUnion,
+            LayoutCalculatorError::ReprConflict => LayoutCalculatorError::ReprConflict,
+        }
+    }
+
+    /// Format an untranslated diagnostic for this type
+    ///
+    /// Intended for use by rust-analyzer, as neither it nor `rustc_abi` depend on fluent infra.
+    pub fn fallback_fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
+        f.write_str(match self.without_payload() {
```
Comment (lnicola) [inline compiler/rustc_abi/src/layout.rs:78]: There's no need to drop the payload here, is there?

Comment (workingjubilee) [reply compiler/rustc_abi/src/layout.rs:78]: I suppose not! There was some vague thought in my head mumbling about "but multiple monomorphization..." but I don't think that matters actually.

Comment (lnicola) [reply compiler/rustc_abi/src/layout.rs]: We're only going to call it with an empty payload, so it's probably fine. You could even implement it only for those, but 🤷.

**Review by lnicola — APPROVED** [review]

**Comment by workingjubilee** [comment]
No idea why my brain insisted it wasn't fully imported.

**Comment by workingjubilee** [comment]
oddly `./x.py build rust-analyzer` works but `./x.py test rust-analyzer` doesn't.

I'll take it, I guess!

File: compiler/rustc_abi/src/layout.rs [hunk 3]
```diff
@@ -39,7 +39,7 @@ enum NicheBias {
     End,
 }
 
-#[derive(Copy, Clone, Debug)]
+#[derive(Copy, Clone, Debug, PartialEq, Eq)]
```
Comment (workingjubilee) [inline compiler/rustc_abi/src/layout.rs:42]: I think rust-analyzer's derives of these are probably unnecessary but I'm not gonna fight that war today.

**Comment by lnicola** [comment]
Yeah, the r-a test suite doesn't get run (and probably doesn't pass, I think they're were some issues on i386).

**Comment by workingjubilee** [comment]
how bizarre.

File: compiler/rustc_abi/src/layout.rs (hunk 3 above)
Comment (lnicola) [reply compiler/rustc_abi/src/layout.rs:42]: I think they're needed because we store these into a `salsa` database.

**Comment by workingjubilee** [comment]
Hm I feel like this should go to
r? @lukas-code

**Comment by jieyouxu** [comment]
> oddly `./x.py build rust-analyzer` works but `./x.py test rust-analyzer` doesn't.

r-a isn't setup as a test step in boopstrap

**Comment by workingjubilee** [comment]
ah, is it finally time to promote it to its own directory?
`git mv ./src/bootstrap ./boopstrap`

File: compiler/rustc_ty_utils/src/layout/invariant.rs [hunk 4]
```diff
@@ -74,21 +84,19 @@ pub(super) fn sanity_check_layout<'tcx>(cx: &LayoutCx<'tcx>, layout: &TyAndLayou
...
-            return;
+            return Ok(());
         };
-        assert_eq!(
-            layout.layout.align().abi,
-            align,
-            "alignment mismatch between ABI and layout in {layout:#?}"
-        );
+        if layout.layout.align().abi != align {
+            return Err(LayoutCalculatorError::ReprConflict);
```
Comment (lukas-code) [inline compiler/rustc_ty_utils/src/layout/invariant.rs:90]: Making the `layout_of` query return different results depending on `cfg!(debug_assertions)` seems like a debugging nightmare. Ideally, we should bail before the invalid layout is ever created -- maybe checking for `repr(packed)` in `layout_of_enum` is enough?

File: compiler/rustc_abi/src/layout.rs [hunk 5]
```diff
@@ -307,12 +337,11 @@ impl<Cx: HasDataLayout> LayoutCalculator<Cx> {
                         common_non_zst_abi_and_align = Err(AbiMismatch);
                     } else {
                         // Fields with the same non-Aggregate ABI should also
-                        // have the same alignment
-                        if !matches!(common_abi, Abi::Aggregate { .. }) {
-                            assert_eq!(
-                                common_align, field.align.abi,
-                                "non-Aggregate field with matching ABI but differing alignment"
-                            );
```
Comment (lukas-code) [inline compiler/rustc_abi/src/layout.rs:315]: This assert is similar to the one in the sanity check: Hitting it means that an invalid layout was already created elsewhere.

Instead of trying to make the consumers of layouts work with invalid layouts, I think we should find the place where the invalid layouts are created to begin with and emit the `LayoutCalculatorError::ReprConflict` there.

File: compiler/rustc_abi/src/layout.rs (hunk 2 above)
Comment (lukas-code) [reply compiler/rustc_abi/src/layout.rs]: This method could be only on an `impl LayoutCalculatorError<()>` if you want to avoid multiple monomorphization.

File: compiler/rustc_ty_utils/src/layout/invariant.rs (hunk 4 above)
Comment (workingjubilee) [reply compiler/rustc_ty_utils/src/layout/invariant.rs:90]: Yes, but we already "return" an ICE based on `cfg!(debug_assertions)`, which I didn't realize was the reason for the ICE until I found the conditional.

Comment (workingjubilee) [reply compiler/rustc_ty_utils/src/layout/invariant.rs:90]: This code in practice is not really part of `rustc_ty_utils`, it is `rustc_abi` code that got lost somewhere, and my intent was to not immediately refactor everything before I moved it in there.

Comment (workingjubilee) [reply compiler/rustc_ty_utils/src/layout/invariant.rs:90]: Like, the problem inheres in the fact that we have "sanity checks" to begin with.

First, I've read that code. I can't call it sane with a straight face.

Second, the entire purpose of a "sanity check" is to attempt to do post-hoc checking of layout invariants, after we've created these invalid layouts. We _do_ have something for that, but it's called a `#[test]`.

Comment (lukas-code) [reply compiler/rustc_ty_utils/src/layout/invariant.rs:90]: > Yes, but we already "return" an ICE based on `cfg!(debug_assertions)`

Yeah that's how debug asserts work? If `debug_assertions` are enabled they sometimes "return" a panic rather than the wrong thing, but here you're making it so that if `debug_assertions` are enabled, we're suddenly starting to return the correct thing instead, which seems confusing to me.

> Like, the problem inheres in the fact that we have "sanity checks" to begin with.

I don't see the problem with sanity checks here or the advantage of moving this code to a `#[test]`. When the sanity check is enabled (by enabling debug assertions) it's like we're running the test for every layout that's computed by the compiler and that's how we're finding the bugs like the one you're fixing here in the first place. If we just `#[test]` some list of predefined layouts, then we would have never found this bug.

Comment (lukas-code) [reply compiler/rustc_ty_utils/src/layout/invariant.rs:90]: Like, running the sanity check should always be optional (like a test), and never affect the end result of `layout_of` modulo internal errors being reported (via ICEs).

File: compiler/rustc_abi/src/layout.rs (hunk 3 above)
Comment (workingjubilee) [reply compiler/rustc_abi/src/layout.rs:42]: Huh, interesting.

File: compiler/rustc_ty_utils/src/layout/invariant.rs (hunk 4 above)
Comment (workingjubilee) [reply compiler/rustc_ty_utils/src/layout/invariant.rs:90]: > I don't see the problem with sanity checks here or the advantage of moving this code to a `#[test]`. When the sanity check is enabled (by enabling debug assertions) it's like we're running the test for every layout that's computed by the compiler and that's how we're finding the bugs like the one you're fixing here in the first place. If we just `#[test]` some list of predefined layouts, then we would have never found this bug.

For the most part, we _do_ test it on predefined layouts, though: the ones we actually include in test-cases and run with debug assertions enabled on. If the asserts worked to catch all these cases in general, we would not have merged #123367 or #128612 in the condition they were merged in.

...well, actually it seems #128612 had bors-related errors surrounding its merging so I guess it would've. 😅

Comment (workingjubilee) [reply compiler/rustc_ty_utils/src/layout/invariant.rs:90]: i.e. The suite of check-fail tests doesn't really drive into the layout computing code without `-Zvalidate-mir` forcing it to, which is, er, why `-Zvalidate-mir` exists now.

Comment (workingjubilee) [reply compiler/rustc_ty_utils/src/layout/invariant.rs:90]: As far as tests go, real property testing at the source of the problem can actually exhaust a possibility space much faster than randomly mutating Rust source programs and then calling rustc on them with `-Zvalidate-mir`.

Comment (workingjubilee) [reply compiler/rustc_ty_utils/src/layout/invariant.rs:90]: anyways what I really mean is that having a sanity check post-hoc, and returning errors to begin with, means we've already conceded that layout computation will compute erroneous layouts, so the critique of "we shouldn't have the invariant check return different results if the layout is invalid, we should fix it at the source" is valid, but imo applies in a more general sense to having _any_ code that checks invariants "downstream" of `rustc_abi`.

Comment (lukas-code) [reply compiler/rustc_ty_utils/src/layout/invariant.rs:90]: These are all great points for moving the invariant check into `rustc_abi` (and creating a dedicated test suite), but forcing to run the check on every layout after it has been constructed to convert from a `Ok(layout)` into an `Err(something)` still seems post-hoc to me.

For this specific issue I believe the proper fix at the source would be to just check for `repr(packed)` before computing the layout of an enum and returning an error immediately rather than continue and then reject the computed layout later.

File: compiler/rustc_abi/src/layout.rs (hunk 2 above)
Comment (workingjubilee) [reply compiler/rustc_abi/src/layout.rs]: Doing that Feels Silly on some level, now that I've actually thought about it.

File: compiler/rustc_abi/src/layout.rs (hunk 5 above)
Comment (workingjubilee) [reply compiler/rustc_abi/src/layout.rs]: Philosophical discussion about the meaning of ICEs aside, that does result in a much smaller fix. I feel a bit silly for heading down that path as far as I did. Thanks!

**Review by lukas-code — APPROVED** [review]
Thanks!
