### PR TITLE
Not lint pub structs without pub constructors intentionally

### LINKED ISSUE #128053: dead-code false positive on named structs with a never field
### Code

```Rust
#![feature(never_type)]

pub struct JustEmpty(!);

pub struct FancyEmpty {
    _empty: !,
}
```

### Current output

```Shell
warning: struct `FancyEmpty` is never constructed
 --> src/lib.rs:5:12
  |
5 | pub struct FancyEmpty {
  |            ^^^^^^^^^^
  |
  = note: `#[warn(dead_code)]` on by default

warning: `playground` (lib) generated 1 warning
```

### Desired output

```Shell
Compiles without warnings.
```

### Rationale and extra context

The struct is meant to not be constructible. Also the behavior is incoherent between tuple structs (correct behavior) and named structs (incorrect behavior).

Also, this is a regression, this didn't use to be the case.

### Other cases

_No response_

### Rust Version

```Shell
rustc 1.82.0-nightly (92c6c0380 2024-07-21)
binary: rustc
commit-hash: 92c6c03805408a1a261b98013304e9bbf59ee428
commit-date: 2024-07-21
host: x86_64-unknown-linux-gnu
release: 1.82.0-nightly
LLVM version: 18.1.7
```

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by mu001999**
Fixes #128053

### CODE REVIEW

File: compiler/rustc_passes/src/dead.rs [hunk 1]
```diff
@@ -72,24 +72,26 @@ fn adt_of<'tcx>(ty: &hir::Ty<'tcx>) -> Option<(LocalDefId, DefKind)> {
...
-        if is_positional
-            && tcx
-                .layout_of(tcx.param_env(field.did).and(field_type))
-                .map_or(true, |layout| layout.is_zst())
-        {
-            return true;
-        }
-        field.vis.is_public()
-    })
+        field_type.is_unit() || field_type.is_never()
```
Comment (petrochenkov) [inline compiler/rustc_passes/src/dead.rs:81]:
```suggestion
        field_type.is_unit() || field_type.is_never() || field_type.is_phantom_data()
```
Could you merge the common logic for units, never types and phantom data?

Comment (mu001999) [reply compiler/rustc_passes/src/dead.rs:81]: I thought only one field of `PhantomData`  does not imply that the whole type does not require a pub constructor, so the logic is a little different for `PhantomData`.

For example, if the whole type only have one field of `PhantomData<T>` and other fields of normal types, `PhantomData` is used to represent that the type owns `T`. So that marking types whose fields are all of `PhantomData` is more precise. In such cases, the whole type is usually used to check things like well-formedness.

**Review by petrochenkov — APPROVED** [review]

**Comment by Kobzol** [comment]
@rust-timer build dc4683937e44793786466b971f4c40713ffd5f59

**Comment by Kobzol** [comment]
This PR seems to have introduced a non-trivial regression for structs with a lot of fields. Do you think that there is something that can be done here to win back the perf. loss?

**Comment by mu001999** [comment]
@Kobzol oh yes, I think I can open a new PR
