### PR TITLE
Recover from C++ style `enum struct`

### LINKED ISSUE #99625: Recover from C++-style "pub enum struct X"
Given the following code: 

```rust
pub enum struct Range {
    Valid {
        begin: u32,
        len: u32,
    }
    Out,
}

fn main() {
    println!("Hello, world!");
}
```

The current output is:

```
   Compiling playground v0.0.1 (/playground)
error: expected identifier, found keyword `struct`
 --> src/main.rs:1:10
  |
1 | pub enum struct Range {
  |          ^^^^^^ expected identifier, found keyword

error: expected one of `<`, `where`, or `{`, found `Range`
 --> src/main.rs:1:17
  |
1 | pub enum struct Range {
  |                 ^^^^^ expected one of `<`, `where`, or `{`

error: could not compile `playground` due to 2 previous errors
```

Ideally the output should look like:

Highlight to the user that the keywords `enum` and `struct` are mutually exclusive. Replace `enum struct` with `enum`.

### PR DESCRIPTION
**Pull request by obeis**
Closes #99625

### CODE REVIEW

File: compiler/rustc_parse/src/parser/diagnostics.rs [hunk 1]
```diff
@@ -411,6 +411,20 @@ impl<'a> Parser<'a> {
     }
 
     pub(super) fn expected_ident_found(&self) -> DiagnosticBuilder<'a, ErrorGuaranteed> {
+        if self.prev_token.is_keyword(kw::Enum) && self.token.is_keyword(kw::Struct) {
```
Comment (compiler-errors) [inline compiler/rustc_parse/src/parser/diagnostics.rs:414]: Consider moving this to `parse_item_enum`, since it's a bit specific to `enum`s to be located in `expected_ident_found` I think.

Comment (obeis) [reply compiler/rustc_parse/src/parser/diagnostics.rs:414]: Much better i think

File: compiler/rustc_parse/src/parser/item.rs [hunk 2]
```diff
@@ -1216,6 +1216,20 @@ impl<'a> Parser<'a> {
...
     fn parse_item_enum(&mut self) -> PResult<'a, ItemInfo> {
+        if self.prev_token.is_keyword(kw::Enum) && self.token.is_keyword(kw::Struct) {
+            let mut err = self.struct_span_err(
+                self.prev_token.span.to(self.token.span),
+                "`enum` and `struct` are mutually exclusive",
+            );
+            err.span_suggestion(
+                self.prev_token.span.to(self.token.span),
+                "replace `enum struct` with `enum`",
+                "",
```
Comment (compiler-errors) [inline compiler/rustc_parse/src/parser/item.rs:1227]:
```suggestion
                "enum",
```

File: compiler/rustc_parse/src/parser/item.rs [hunk 3]
```diff
@@ -1216,6 +1216,20 @@ impl<'a> Parser<'a> {
...
+                Applicability::MachineApplicable,
+            );
+            return Err(err);
```
Comment (compiler-errors) [inline compiler/rustc_parse/src/parser/item.rs:1230]: We should be able to recover from this if the next token is an identifier. If so, then just do `err.emit();` instead of `return Err(..);`

File: src/test/ui/parser/issue-99625-enum-struct-mutually-exclusive.rs [hunk 4]
```diff
@@ -0,0 +1,11 @@
+pub enum struct Range {
```
Comment (compiler-errors) [inline src/test/ui/parser/issue-99625-enum-struct-mutually-exclusive.rs:1]: This should have `// run-rustfix` on top.

File: compiler/rustc_parse/src/parser/item.rs [hunk 5]
```diff
@@ -1216,6 +1216,20 @@ impl<'a> Parser<'a> {
...
+                self.prev_token.span.to(self.token.span),
+                "`enum` and `struct` are mutually exclusive",
+            );
+            err.span_suggestion(
+                self.prev_token.span.to(self.token.span),
+                "replace `enum struct` with `enum`",
+                "enum",
+                Applicability::MachineApplicable,
+            );
+            err.emit();
```
Comment (compiler-errors) [inline compiler/rustc_parse/src/parser/item.rs:1230]: You need to check if the next token is an identifier. 

You can use the lookahead method on the parser to do this. If it is an identifier, then you need to eat the current token, _then_ call `.emit()`.

If not, then you need to just `return Err(err);`

File: src/test/ui/parser/issue-99625-enum-struct-mutually-exclusive.fixed [hunk 6]
```diff
@@ -0,0 +1,15 @@
+// run-rustfix
+
+pub enum Range {
+    //~^ ERROR `enum` and `struct` are mutually exclusive
+    //~^^ ERROR expected identifier, found keyword
+    //~^^^ ERROR expected one of `<`, `where`, or `{`, found `Range`
```
Comment (compiler-errors) [inline src/test/ui/parser/issue-99625-enum-struct-mutually-exclusive.fixed:6]: These errors are redundant. Fix the comment above and then it should just be one error.

File: compiler/rustc_parse/src/parser/item.rs [hunk 7]
```diff
@@ -1216,6 +1216,24 @@ impl<'a> Parser<'a> {
 
     /// Parses an enum declaration.
     fn parse_item_enum(&mut self) -> PResult<'a, ItemInfo> {
+        if self.prev_token.is_keyword(kw::Enum) && self.token.is_keyword(kw::Struct) {
```
Comment (compiler-errors) [inline compiler/rustc_parse/src/parser/item.rs:1219]: We don't need to check prev token

```suggestion
        if self.token.is_keyword(kw::Struct) {
```

File: compiler/rustc_parse/src/parser/item.rs [hunk 8]
```diff
@@ -1216,6 +1216,24 @@ impl<'a> Parser<'a> {
...
+                self.prev_token.span.to(self.token.span),
+                "`enum` and `struct` are mutually exclusive",
+            );
+            err.span_suggestion(
+                self.prev_token.span.to(self.token.span),
+                "replace `enum struct` with `enum`",
+                "enum",
+                Applicability::MachineApplicable,
+            );
+            if self.look_ahead(1, |t| t.is_ident()) && self.eat(&token::Ident(kw::Struct, false)) {
```
Comment (compiler-errors) [inline compiler/rustc_parse/src/parser/item.rs:1230]:
```suggestion
            if self.look_ahead(1, |t| t.is_ident()) {
                self.bump(); // We have already checked the next token is `struct`
```

**Review by compiler-errors — APPROVED** [review]
Looks good. 2 more nits.

File: src/test/ui/parser/issue-99625-enum-struct-mutually-exclusive.stderr [hunk 9]
```diff
@@ -0,0 +1,8 @@
+error: `enum` and `struct` are mutually exclusive
+  --> $DIR/issue-99625-enum-struct-mutually-exclusive.rs:3:5
+   |
+LL | pub enum struct Range {
+   |     ^^^^^^^^^^^ help: replace `enum struct` with `enum`: `enum`
```
Comment (lygstate) [inline src/test/ui/parser/issue-99625-enum-struct-mutually-exclusive.stderr:5]: Why `enum`: `enum`?

File: compiler/rustc_parse/src/parser/item.rs (hunk 7 above)
Comment (obeis) [reply compiler/rustc_parse/src/parser/item.rs:1219]: Okay, because that happened before calling `parse_item_enum`.

File: src/test/ui/parser/issue-99625-enum-struct-mutually-exclusive.stderr (hunk 9 above)
Comment (obeis) [reply src/test/ui/parser/issue-99625-enum-struct-mutually-exclusive.stderr:5]: I think "help: replace `enum struct` with: `enum`" or "help: replace with: `enum`" is much better
