### PR TITLE
Assert that pthread mutex initialization succeeded

### LINKED ISSUE #34966: Return codes of libc functions are checked for errors only in debug mode.
In libstd/sys/unix there are numerous cases where return code is checked for
error using following pattern:

```
let result = libc::pthread_mutexattr_init(&mut attr as *mut _);
debug_assert_eq!(result, 0);
```

That means, that error checking is performed only when compiled in
non-optimized mode or after explicitly enabling debug assertions.  This is a
little bit worrying, especially when used on platforms where those functions
can indeed fail and break safety.

### PR DESCRIPTION
**Pull request by tmiasko**
If pthread mutex initialization fails, the failure will go unnoticed unless
debug assertions are enabled. Any subsequent use of mutex will also silently
fail, since return values from lock & unlock operations are similarly checked
only through debug assertions.

In some implementations the mutex initialization requires a memory
allocation and so it does fail in practice.

Assert that initialization succeeds to ensure that mutex guarantees
mutual exclusion.

Fixes #34966.

### CODE REVIEW

**Comment by cuviper** [comment]
I think it's a good idea to enforce this, but the assertion will not be very meaningful to a user. Your change from `result` to `r` will be less meaningful in the panic message, and a user has to be a bit savvy to know that this is a POSIX error number.

Maybe they should use `cvt_nz` instead? Then we can `unwrap` it for a formatted error message, either directly here or from the next caller level up.

**Comment by tmiasko** [comment]
Replaced with cvt_nz and unwrap, this should be informative enough coming from Mutex::init, now that we have a track-caller. I intentionally limited this to initialization for now.

File: library/std/src/sys/unix/process/process_unix.rs [hunk 1]
```diff
@@ -3,8 +3,8 @@ use crate::fmt;
 use crate::io::{self, Error, ErrorKind};
 use crate::ptr;
 use crate::sys;
-use crate::sys::cvt;
 use crate::sys::process::process_common::*;
+use crate::sys::{cvt, cvt_nz};
```
Comment (cuviper) [inline library/std/src/sys/unix/process/process_unix.rs:7]: I think this will give an `unused` warning (denied) on some targets. Better to import it at the start of `posix_spawn` where you know it's used.

**Comment by cuviper** [comment]
LGTM, thanks!

@bors r+ rollup

**Comment by cuviper** [comment]
I think you miscalibrated your time machine...

image
