### PR TITLE
Only emit one error per unsized binding, instead of one per usage

### LINKED ISSUE #56607: Only emit one error per unsized binding, instead of one per usage
The following code

```
fn main() {
    let x = *"";
    println!("{}", x);
    println!("{}", x);
}
```

Produces the following output:

```
error[E0277]: the size for values of type `str` cannot be known at compilation time
 --> src/main.rs:2:9
  |
2 |     let x = *"";
  |         ^ doesn't have a size known at compile-time
  |
  = help: the trait `std::marker::Sized` is not implemented for `str`
  = note: to learn more, visit <https://doc.rust-lang.org/book/second-edition/ch19-04-advanced-types.html#dynamically-sized-types-and-the-sized-trait>
  = note: all local variables must have a statically known size
  = help: unsized locals are gated as an unstable feature

error[E0277]: the size for values of type `str` cannot be known at compilation time
 --> src/main.rs:3:5
  |
3 |     println!("{}", x);
  |     ^^^^^^^^^^^^^^^^^^ doesn't have a size known at compile-time
  |
  = help: the trait `std::marker::Sized` is not implemented for `str`
  = note: to learn more, visit <https://doc.rust-lang.org/book/second-edition/ch19-04-advanced-types.html#dynamically-sized-types-and-the-sized-trait>
  = note: required by `std::fmt::ArgumentV1::new`
  = note: this error originates in a macro outside of the current crate (in Nightly builds, run with -Z external-macro-backtrace for more info)

error[E0277]: the size for values of type `str` cannot be known at compilation time
 --> src/main.rs:4:5
  |
4 |     println!("{}", x);
  |     ^^^^^^^^^^^^^^^^^^ doesn't have a size known at compile-time
  |
  = help: the trait `std::marker::Sized` is not implemented for `str`
  = note: to learn more, visit <https://doc.rust-lang.org/book/second-edition/ch19-04-advanced-types.html#dynamically-sized-types-and-the-sized-trait>
  = note: required by `std::fmt::ArgumentV1::new`
  = note: this error originates in a macro outside of the current crate (in Nightly builds, run with -Z external-macro-backtrace for more info)

error: aborting due to 3 previous errors
```

The later two messages are not strictly necessary, since the unsized element being complained about is the same as the first one. Because of this, it should be unnecessary to complain about these as fixing the first problem fixes all three of them.

### PR DESCRIPTION
**Pull request by estebank**
Fix #56607.

### CODE REVIEW

File: compiler/rustc_trait_selection/src/traits/error_reporting/mod.rs [hunk 1]
```diff
@@ -691,6 +691,25 @@ impl<'tcx> TypeErrCtxtExt<'tcx> for TypeErrCtxt<'_, 'tcx> {
...
+                            && let Some(Node::Expr(arg)) = self.tcx.hir().find(*arg_hir_id)
+                            && let arg = arg.peel_borrows()
+                            && let hir::ExprKind::Path(hir::QPath::Resolved(
+                                None,
+                                hir::Path { res: hir::def::Res::Local(hir_id), .. },
+                            )) = arg.kind
+                            && let Some(Node::Pat(pat)) = self.tcx.hir().find(*hir_id)
+                            && let Some(preds) = self.reported_trait_errors.borrow().get(&pat.span)
+                            && preds.contains(&obligation.predicate)
+                            && self.tcx.sess.has_errors().is_some()
```
Comment (compiler-errors) [inline compiler/rustc_trait_selection/src/traits/error_reporting/mod.rs:707]: I think we want to move forward with depending on less global state, rather than more.

**Review by compiler-errors — COMMENTED** [review]
I think this is too fragile of a heuristic to be worth landing, and it introduces potential future headaches when queries interleave and for the parallel compiler. I'm not convinced this PR is worth landing :sweat: 

clarifying edit: Specifically the dependency on `self.tcx.sess.has_errors().is_some()`, which is global state that I think we want to eventually remove, or at least track a lot more delicately.

File: compiler/rustc_trait_selection/src/traits/error_reporting/mod.rs [hunk 2]
```diff
@@ -691,6 +691,25 @@ impl<'tcx> TypeErrCtxtExt<'tcx> for TypeErrCtxt<'_, 'tcx> {
                         {
                             return;
                         }
+                        if let ObligationCauseCode::FunctionArgumentObligation {
```
Comment (compiler-errors) [inline compiler/rustc_trait_selection/src/traits/error_reporting/mod.rs:694]: This doesn't deduplicate usages of unsized bindings in other positions that also require the expression to be sized, such as struct constructors, assignment, `as` coercions, returns, etc right?

File: compiler/rustc_trait_selection/src/traits/error_reporting/mod.rs (hunk 1 above)
Comment (estebank) [reply compiler/rustc_trait_selection/src/traits/error_reporting/mod.rs:707]: Note that a few lines above we already have a `has_errors` check. When we come up with an alternative for that one, this one can also go away. In this case this is to ensure that we don't unnecessarily silence obligations that happen to be in `reported_trait_errors` without actually having been emitted (I found a couple of examples in the test suite).

File: compiler/rustc_trait_selection/src/traits/error_reporting/mod.rs (hunk 2 above)
Comment (estebank) [reply compiler/rustc_trait_selection/src/traits/error_reporting/mod.rs:694]: Correct.

File: compiler/rustc_trait_selection/src/traits/error_reporting/mod.rs (hunk 1 above)
Comment (estebank) [reply compiler/rustc_trait_selection/src/traits/error_reporting/mod.rs:707]: @compiler-errors let me know if my rationale above is sufficient to land the PR as is, otherwise we can close this PR.

**Comment by compiler-errors** [comment]
I am still a bit skeptical whether this is worthwhile given the limitations (only fn calls) and introducing more dependency on global state, but I'd rather not unilaterally make that call.

r? diagnostics

**Comment by estebank** [comment]
> given the limitations (only fn calls)

I focused on dealing with the reported case, but would hope to extend this to more `ObligationCauseCode` cases, within reason.

**Comment by apiraino** [comment]
r? diagnostics

File: compiler/rustc_trait_selection/src/traits/error_reporting/mod.rs (hunk 1 above)
Comment (davidtwco) [reply compiler/rustc_trait_selection/src/traits/error_reporting/mod.rs:707]: Is `tcx.sess.has_errors().is_some()` required when we also check `self.reported_trait_errors.borrow().get(&pat.span)`?

File: compiler/rustc_trait_selection/src/traits/error_reporting/mod.rs [hunk 3]
```diff
@@ -691,6 +691,25 @@ impl<'tcx> TypeErrCtxtExt<'tcx> for TypeErrCtxt<'_, 'tcx> {
...
+                            arg_hir_id,
+                            ..
+                        } = obligation.cause.code()
+                            && let Some(Node::Expr(arg)) = self.tcx.hir().find(*arg_hir_id)
```
Comment (davidtwco) [inline compiler/rustc_trait_selection/src/traits/error_reporting/mod.rs:698]: I think I'd like to see the stuff inside the `if let` here put into a function, just to keep `report_selection_error` a bit simpler.

**Review by davidtwco — COMMENTED** [review]
I think this is a useful improvement, particularly if extended to other reasonable obligation causes as @estebank has said is his intention.

I agree with the concerns about `has_errors`, but given that the function already uses `has_errors` only a few lines above the diff here, I don't think this addition makes removing `has_errors` or changing it materially more difficult - however the usage above is replaced, this usage can replaced the same way.

I've left a comment/reply or two, but I think I'm happy to r=me this after those are resolved.

**Comment by apiraino** [comment]
@estebank by reading the [last comment](https://github.com/rust-lang/rust/pull/113183#pullrequestreview-1593299211), I think the review switch was left unchanged, when I think this is actually waiting on you.

@rustbot author

File: compiler/rustc_trait_selection/src/traits/error_reporting/mod.rs (hunk 1 above)
Comment (estebank) [reply compiler/rustc_trait_selection/src/traits/error_reporting/mod.rs:707]: The following tests ICE without that check

    [ui] tests/ui/derives/derives-span-Clone-enum-struct-variant.rs
    [ui] tests/ui/derives/derives-span-Clone-enum.rs
    [ui] tests/ui/derives/derives-span-Hash-enum-struct-variant.rs
    [ui] tests/ui/derives/derives-span-PartialOrd-enum-struct-variant.rs
    [ui] tests/ui/derives/derives-span-PartialOrd-enum.rs
    [ui] tests/ui/derives/derives-span-Hash-enum.rs

I think because `report_fulfillment_errors` inserts all the error predicates found in the global `reported_trait_errors`, but it *later* has suppression logic that avoids emitting some diagnostics. I'm sure we could change that logic instead, but will make the PR larger.

File: compiler/rustc_trait_selection/src/traits/error_reporting/mod.rs (hunk 3 above)
Comment (apiraino) [reply compiler/rustc_trait_selection/src/traits/error_reporting/mod.rs]: @estebank does this comment needs to be addressed?

Apart from this I think this PR can be r+'ed by @davidtwco (as per [comment](https://github.com/rust-lang/rust/pull/113183#pullrequestreview-1593299211))?

Comment (estebank) [reply compiler/rustc_trait_selection/src/traits/error_reporting/mod.rs]: This was already done
