### PR TITLE
Specialize infinite-type "insert some indirection" suggestion for Option

### LINKED ISSUE #91402: rustc suggests `Box<Option<T>>`, but could specialize to suggest `Option<Box<T>>` instead
Given the following code: [playground link](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=362a02b4692f3d53218ca4454e704e69)

```rust
struct X {
    x: Option<X>,
}
```

The current output is:

```
error[E0072]: recursive type `X` has infinite size
 --> src/lib.rs:1:1
  |
1 | struct X {
  | ^^^^^^^^ recursive type has infinite size
2 |     x: Option<X>,
  |        --------- recursive without indirection
  |
help: insert some indirection (e.g., a `Box`, `Rc`, or `&`) to make `X` representable
  |
2 |     x: Box<Option<X>>,
  |        ++++         +

For more information about this error, try `rustc --explain E0072`.
error: could not compile `playground` due to previous error
```

Ideally the output should look like:

```
error[E0072]: recursive type `X` has infinite size
 --> src/lib.rs:1:1
  |
1 | struct X {
  | ^^^^^^^^ recursive type has infinite size
2 |     x: Option<X>,
  |        --------- recursive without indirection
  |
help: insert some indirection (e.g., a `Box`, `Rc`, or `&`) to make `X` representable
  |
2 |     x: Option<Box<X>>,
  |               ++++ +

For more information about this error, try `rustc --explain E0072`.
error: could not compile `playground` due to previous error
```

This allows rustc to use the nullpointer niche optimization, and is also easier to handle, and what the user probably wants in general.

### PR DESCRIPTION
**Pull request by compiler-errors**
Suggest `Option<Box<_>>` instead of `Box<Option<_>>` for infinitely-recursive members of a struct. 

Not sure if I can get the span of the generic subty of the Option so I can make this a `+++`-style suggestion. The current output is a tiny bit less fancy looking than the original suggestion.

Should I limit the specialization to just `Option<Box<TheOuterStruct>>`? Because right now it applies to all `Option` members in the struct that are returned by `Representability::SelfRecursive`.

Fixes #91402 

r? @estebank 
(since you wrote the original suggestion and are definitely most familiar with it!)

### CODE REVIEW

File: compiler/rustc_trait_selection/src/traits/error_reporting/mod.rs [hunk 1]
```diff
@@ -2179,13 +2179,20 @@ pub fn recursive_type_with_infinite_size_error(
...
-                        (span.shrink_to_lo(), "Box<".to_string()),
-                        (span.shrink_to_hi(), ">".to_string()),
-                    ]
-                    .into_iter()
+                .into_iter()
+                .flat_map(|(ty, span)| match ty.kind() {
+                    ty::Adt(def, args) if Some(def.did) == tcx.get_diagnostic_item(sym::Option) => {
+                        vec![(
+                            span,
+                            format!("Option<Box<{}>>", args.iter().next().unwrap().expect_ty()),
```
Comment (estebank) [inline compiler/rustc_trait_selection/src/traits/error_reporting/mod.rs:2187]: The problem I see with this is that it will cause trouble with any situation where `Option` has been either shadowed or been locally renamed. Of course, we could make the same argument about `Box` in the original...

**Review by estebank — APPROVED** [review]
Regarding getting the right span, the *correct* thing to do would be to somehow get the appropriate `hir::Ty` node so that you can get the appropriate span. The *hacky* second option is to use the snippet and string manipulation to try and find the span edges manually. This final option is to do what you've done here. The last two will have trouble when it comes to macros modifying the user written token stream.

Can you add a `FIXME` comment above the special casing of the option to mention something along the lines of "figure out a way to get the correct span and be resilient to type renaming of both Option and Box"? r=me after that.

**Comment by compiler-errors** [comment]
Ugh borked a rebase. Let me fix that.

**Comment by compiler-errors** [comment]
Added `FIXME` per request.

**Comment by compiler-errors** [comment]
So I reformulated this to work with the HirId of the struct field, instead of it's spanless TyS. This gives us the right span information to turn an `Option<T>` into a `T` so we can suggest wrapping that in `Box`. The diagnostics should be much improved. 

Added a few other test cases as well.

@estebank, do you mind taking a look at this sometime? Thanks!

File: compiler/rustc_trait_selection/src/traits/error_reporting/mod.rs [hunk 2]
```diff
@@ -2262,6 +2271,38 @@ pub fn recursive_type_with_infinite_size_error(
...
+    let hir::def::Res::Def(_, did) = path.res
+        else { return None };
+
+    // Bail if this path doesn't describe `::core::option::Option`
+    if !tcx.is_diagnostic_item(sym::Option, did) {
+        return None;
+    }
+
+    // Match a single generic arg in the 0th path segment
+    let generic_arg = path.segments.get(0)?.args?.args.get(0);
```
Comment (estebank) [inline compiler/rustc_trait_selection/src/traits/error_reporting/mod.rs:2296]: What if `path.segments` is `::core::option::Option`? Wouldn't this be better as `path.segments.last()?.args?.args.get(0)?;

**Review by estebank — APPROVED** [review]
Apologies for the delay. r=me after rebasing.

File: compiler/rustc_trait_selection/src/traits/error_reporting/mod.rs (hunk 2 above)
Comment (compiler-errors) [reply compiler/rustc_trait_selection/src/traits/error_reporting/mod.rs:2296]: great point

**Comment by compiler-errors** [comment]
ready for an r+ i think!

@rustbot ready

**Comment by compiler-errors** [comment]
rebased and re-tested

@bors r=estebank rollup
