### PR TITLE
Make opaque types regular HIR nodes

### LINKED ISSUE #119716: unexpected bound var resolution for HirId(DefId(0:8 ~ test_3[ea46]::kind::{opaque#0}::{opaque#0}).1): None
### Code

```Rust
#![feature(non_lifetime_binders)]
trait v0<v1> {}
fn kind  :(v3main impl for<v4> v0<'_, v2 = impl v0<v4> + '_>) {}
```

### Meta

`rustc --version --verbose`:
```
rustc 1.77.0-nightly (d8b44d280 2024-01-07)
binary: rustc
commit-hash: d8b44d2802ab665b183dce06d527bf09175dd8cf
commit-date: 2024-01-07
host: x86_64-unknown-linux-gnu
release: 1.77.0-nightly
LLVM version: 17.0.6

```

### Error output

```
error: internal compiler error: compiler/rustc_hir_analysis/src/astconv/mod.rs:2296:20: unexpected bound var resolution for HirId(DefId(0:8 ~ test_3[ea46]::kind::{opaque#0}::{opaque#0}).1): None
```

```
Box<dyn Any>
stack backtrace:
   0:     0x7f7399548477 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h9b88b6f3ca46a608
   1:     0x7f73995a6470 - core::fmt::write::h006931418f3178a6
   2:     0x7f7399534f1f - std::io::Write::write_fmt::hef1b13539c871113
   3:     0x7f7399548244 - std::sys_common::backtrace::print::hdf04dd1e52b85090
   4:     0x7f739954914a - std::panicking::default_hook::{{closure}}::h38e3ca5d3417a132
   5:     0x7f7399548e73 - std::panicking::default_hook::h7c8bd090cc5c8cb1
   6:     0x7f7390ca0c37 - <alloc[ab03fe8b414083ab]::boxed::Box<rustc_driver_impl[2320baa211b147c5]::install_ice_hook::{closure#0}> as core[da5ff848ab5b9634]::ops::function::Fn<(&dyn for<'a, 'b> core[da5ff848ab5b9634]::ops::function::Fn<(&'a core[da5ff848ab5b9634]::panic::panic_info::PanicInfo<'b>,), Output = ()> + core[da5ff848ab5b9634]::marker::Sync + core[da5ff848ab5b9634]::marker::Send, &core[da5ff848ab5b9634]::panic::panic_info::PanicInfo)>>::call
   7:     0x7f7399549898 - std::panicking::rust_panic_with_hook::h39552955130d1e24
   8:     0x7f7395ee8786 - std[9295f5ecf1531c2a]::panicking::begin_panic::<rustc_errors[aa2fa569483a35a2]::ExplicitBug>::{closure#0}
   9:     0x7f7395ee3576 - std[9295f5ecf1531c2a]::sys_common::backtrace::__rust_end_short_backtrace::<std[9295f5ecf1531c2a]::panicking::begin_panic<rustc_errors[aa2fa569483a35a2]::ExplicitBug>::{closure#0}, !>
  10:     0x7f7390c10fd6 - std[9295f5ecf1531c2a]::panicking::begin_panic::<rustc_errors[aa2fa569483a35a2]::ExplicitBug>
  11:     0x7f7395edaf21 - <rustc_errors[aa2fa569483a35a2]::diagnostic_builder::BugAbort as rustc_errors[aa2fa569483a35a2]::diagnostic_builder::EmissionGuarantee>::emit_producing_guarantee
  12:     0x7f7395d532dd - <rustc_errors[aa2fa569483a35a2]::DiagCtxt>::bug::<alloc[ab03fe8b414083ab]::string::String>
  13:     0x7f7395d36115 - rustc_middle[712429aa67461ada]::util::bug::opt_span_bug_fmt::<rustc_span[7e71af783b1896b5]::span_encoding::Span>::{closure#0}
  14:     0x7f7395d2e59a - rustc_middle[712429aa67461ada]::ty::context::tls::with_opt::<rustc_middle[712429aa67461ada]::util::bug::opt_span_bug_fmt<rustc_span[7e71af783b1896b5]::span_encoding::Span>::{closure#0}, !>::{closure#0}
  15:     0x7f7395d2e548 - rustc_middle[712429aa67461ada]::ty::context::tls::with_context_opt::<rustc_middle[712429aa67461ada]::ty::context::tls::with_opt<rustc_middle[712429aa67461ada]::util::bug::opt_span_bug_fmt<rustc_span[7e71af783b1896b5]::span_encoding::Span>::{closure#0}, !>::{closure#0}, !>
  16:     0x7f7390be1422 - rustc_middle[712429aa67461ada]::util::bug::bug_fmt
  17:     0x7f7393cd8727 - <dyn rustc_hir_analysis[70120cffb8a4fd07]::astconv::AstConv>::hir_id_to_bound_ty
  18:     0x7f7393cd4bcf - <dyn rustc_hir_analysis[70120cffb8a4fd07]::astconv::AstConv>::res_to_ty
  19:     0x7f7393ce859b - <dyn rustc_hir_analysis[70120cffb8a4fd07]::astconv::AstConv>::ast_ty_to_ty_inner
  20:     0x7f7393cda267 - <<dyn rustc_hir_analysis[70120cffb8a4fd07]::astconv::AstConv>::create_args_for_ast_path::{closure#0}::SubstsForAstPathCtxt as rustc_hir_analysis[70120cffb8a4fd07]::astconv::CreateSubstsForGenericArgsCtxt>::provided_kind::{closure#0}
  21:     0x7f7393cd9f67 - <<dyn rustc_hir_analysis[70120cffb8a4fd07]::astconv::AstConv>::create_args_for_ast_path::{closure#0}::SubstsForAstPathCtxt as rustc_hir_analysis[70120cffb8a4fd07]::astconv::CreateSubstsForGenericArgsCtxt>::provided_kind
  22:     0x7f7393e1bb58 - rustc_hir_analysis[70120cffb8a4fd07]::astconv::generics::create_args_for_parent_generic_args::<<dyn rustc_hir_analysis[70120cffb8a4fd07]::astconv::AstConv>::create_args_for_ast_path::{closure#0}::SubstsForAstPathCtxt>
  23:     0x7f7393cd9cd3 - <dyn rustc_hir_analysis[70120cffb8a4fd07]::astconv::AstConv>::create_args_for_ast_path
  24:     0x7f7393cdb43a - <dyn rustc_hir_analysis[70120cffb8a4fd07]::astconv::AstConv>::instantiate_poly_trait_ref
  25:     0x7f7393cc34c3 - <dyn rustc_hir_analysis[70120cffb8a4fd07]::astconv::AstConv>::compute_bounds
  26:     0x7f7393d70713 - rustc_hir_analysis[70120cffb8a4fd07]::collect::item_bounds::opaque_type_bounds
  27:     0x7f7393d600b6 - rustc_hir_analysis[70120cffb8a4fd07]::collect::item_bounds::explicit_item_bounds
  28:     0x7f7394ba107e - rustc_query_impl[c09cc8fff495313c]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[c09cc8fff495313c]::query_impl::explicit_item_bounds::dynamic_query::{closure#2}::{closure#0}, rustc_middle[712429aa67461ada]::query::erase::Erased<[u8; 16usize]>>
  29:     0x7f7394c19a21 - <rustc_query_impl[c09cc8fff495313c]::query_impl::explicit_item_bounds::dynamic_query::{closure#2} as core[da5ff848ab5b9634]::ops::function::FnOnce<(rustc_middle[712429aa67461ada]::ty::context::TyCtxt, rustc_span[7e71af783b1896b5]::def_id::DefId)>>::call_once
  30:     0x7f7394e620ca - rustc_query_system[3a5b469aacd7ee53]::query::plumbing::try_execute_query::<rustc_query_impl[c09cc8fff495313c]::DynamicConfig<rustc_query_system[3a5b469aacd7ee53]::query::caches::DefaultCache<rustc_span[7e71af783b1896b5]::def_id::DefId, rustc_middle[712429aa67461ada]::query::erase::Erased<[u8; 16usize]>>, false, false, false>, rustc_query_impl[c09cc8fff495313c]::plumbing::QueryCtxt, false>
  31:     0x7f7394c3800c - rustc_query_impl[c09cc8fff495313c]::query_impl::explicit_item_bounds::get_query_non_incr::__rust_end_short_backtrace
  32:     0x7f7393d6974f - rustc_hir_analysis[70120cffb8a4fd07]::collect::convert_item
  33:     0x7f7393d616f2 - <rustc_hir_analysis[70120cffb8a4fd07]::collect::CollectItemTypesVisitor as rustc_hir[c5f0d571a76e7881]::intravisit::Visitor>::visit_item
  34:     0x7f7393dcf457 - <rustc_middle[712429aa67461ada]::hir::map::Map>::visit_item_likes_in_module::<rustc_hir_analysis[70120cffb8a4fd07]::collect::CollectItemTypesVisitor>
  35:     0x7f7393d60e7d - rustc_hir_analysis[70120cffb8a4fd07]::collect::collect_mod_item_types
  36:     0x7f7394ba147c - rustc_query_impl[c09cc8fff495313c]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[c09cc8fff495313c]::query_impl::collect_mod_item_types::dynamic_query::{closure#2}::{closure#0}, rustc_middle[712429aa67461ada]::query::erase::Erased<[u8; 0usize]>>
  37:     0x7f7394c08a3c - <rustc_query_impl[c09cc8fff495313c]::query_impl::collect_mod_item_types::dynamic_query::{closure#2} as core[da5ff848ab5b9634]::ops::function::FnOnce<(rustc_middle[712429aa67461ada]::ty::context::TyCtxt, rustc_span[7e71af783b1896b5]::def_id::LocalModDefId)>>::call_once
  38:     0x7f7394e5936b - rustc_query_system[3a5b469aacd7ee53]::query::plumbing::try_execute_query::<rustc_query_impl[c09cc8fff495313c]::DynamicConfig<rustc_query_system[3a5b469aacd7ee53]::query::caches::DefaultCache<rustc_span[7e71af783b1896b5]::def_id::LocalModDefId, rustc_middle[712429aa67461ada]::query::erase::Erased<[u8; 0usize]>>, false, false, false>, rustc_query_impl[c09cc8fff495313c]::plumbing::QueryCtxt, false>
  39:     0x7f7394c4712d - rustc_query_impl[c09cc8fff495313c]::query_impl::collect_mod_item_types::get_query_non_incr::__rust_end_short_backtrace
  40:     0x7f7393dceddd - <rustc_middle[712429aa67461ada]::hir::map::Map>::for_each_module::<rustc_hir_analysis[70120cffb8a4fd07]::check_crate::{closure#0}::{closure#0}::{closure#0}>
  41:     0x7f7393e68015 - <rustc_session[9285c94e3a71432f]::session::Session>::track_errors::<rustc_hir_analysis[70120cffb8a4fd07]::check_crate::{closure#0}, ()>
  42:     0x7f7393dce266 - rustc_hir_analysis[70120cffb8a4fd07]::check_crate
  43:     0x7f7390e6ccc0 - rustc_interface[b5ea119f6d9fba02]::passes::analysis
  44:     0x7f7394ba318a - rustc_query_impl[c09cc8fff495313c]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[c09cc8fff495313c]::query_impl::analysis::dynamic_query::{closure#2}::{closure#0}, rustc_middle[712429aa67461ada]::query::erase::Erased<[u8; 1usize]>>
  45:     0x7f7394d54708 - <rustc_query_impl[c09cc8fff495313c]::query_impl::analysis::dynamic_query::{closure#2} as core[da5ff848ab5b9634]::ops::function::FnOnce<(rustc_middle[712429aa67461ada]::ty::context::TyCtxt, ())>>::call_once
  46:     0x7f7394e11fac - rustc_query_system[3a5b469aacd7ee53]::query::plumbing::try_execute_query::<rustc_query_impl[c09cc8fff495313c]::DynamicConfig<rustc_query_system[3a5b469aacd7ee53]::query::caches::SingleCache<rustc_middle[712429aa67461ada]::query::erase::Erased<[u8; 1usize]>>, false, false, false>, rustc_query_impl[c09cc8fff495313c]::plumbing::QueryCtxt, false>
  47:     0x7f7394c37043 - rustc_query_impl[c09cc8fff495313c]::query_impl::analysis::get_query_non_incr::__rust_end_short_backtrace
  48:     0x7f7390c7f04b - <rustc_middle[712429aa67461ada]::ty::context::GlobalCtxt>::enter::<rustc_driver_impl[2320baa211b147c5]::run_compiler::{closure#0}::{closure#0}::{closure#3}, core[da5ff848ab5b9634]::result::Result<(), rustc_span[7e71af783b1896b5]::ErrorGuaranteed>>
  49:     0x7f7390d06869 - <rustc_interface[b5ea119f6d9fba02]::interface::Compiler>::enter::<rustc_driver_impl[2320baa211b147c5]::run_compiler::{closure#0}::{closure#0}, core[da5ff848ab5b9634]::result::Result<core[da5ff848ab5b9634]::option::Option<rustc_interface[b5ea119f6d9fba02]::queries::Linker>, rustc_span[7e71af783b1896b5]::ErrorGuaranteed>>
  50:     0x7f7390cc8469 - rustc_span[7e71af783b1896b5]::set_source_map::<core[da5ff848ab5b9634]::result::Result<(), rustc_span[7e71af783b1896b5]::ErrorGuaranteed>, rustc_interface[b5ea119f6d9fba02]::interface::run_compiler<core[da5ff848ab5b9634]::result::Result<(), rustc_span[7e71af783b1896b5]::ErrorGuaranteed>, rustc_driver_impl[2320baa211b147c5]::run_compiler::{closure#0}>::{closure#0}::{closure#0}>
  51:     0x7f7390cae7d3 - <scoped_tls[8787e17a3822f26a]::ScopedKey<rustc_span[7e71af783b1896b5]::SessionGlobals>>::set::<rustc_interface[b5ea119f6d9fba02]::util::run_in_thread_pool_with_globals<rustc_interface[b5ea119f6d9fba02]::interface::run_compiler<core[da5ff848ab5b9634]::result::Result<(), rustc_span[7e71af783b1896b5]::ErrorGuaranteed>, rustc_driver_impl[2320baa211b147c5]::run_compiler::{closure#0}>::{closure#0}, core[da5ff848ab5b9634]::result::Result<(), rustc_span[7e71af783b1896b5]::ErrorGuaranteed>>::{closure#0}, core[da5ff848ab5b9634]::result::Result<(), rustc_span[7e71af783b1896b5]::ErrorGuaranteed>>
  52:     0x7f7390cc8959 - rustc_span[7e71af783b1896b5]::create_session_globals_then::<core[da5ff848ab5b9634]::result::Result<(), rustc_span[7e71af783b1896b5]::ErrorGuaranteed>, rustc_interface[b5ea119f6d9fba02]::util::run_in_thread_pool_with_globals<rustc_interface[b5ea119f6d9fba02]::interface::run_compiler<core[da5ff848ab5b9634]::result::Result<(), rustc_span[7e71af783b1896b5]::ErrorGuaranteed>, rustc_driver_impl[2320baa211b147c5]::run_compiler::{closure#0}>::{closure#0}, core[da5ff848ab5b9634]::result::Result<(), rustc_span[7e71af783b1896b5]::ErrorGuaranteed>>::{closure#0}>
  53:     0x7f7390cb7cae - std[9295f5ecf1531c2a]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[b5ea119f6d9fba02]::util::run_in_thread_with_globals<rustc_interface[b5ea119f6d9fba02]::util::run_in_thread_pool_with_globals<rustc_interface[b5ea119f6d9fba02]::interface::run_compiler<core[da5ff848ab5b9634]::result::Result<(), rustc_span[7e71af783b1896b5]::ErrorGuaranteed>, rustc_driver_impl[2320baa211b147c5]::run_compiler::{closure#0}>::{closure#0}, core[da5ff848ab5b9634]::result::Result<(), rustc_span[7e71af783b1896b5]::ErrorGuaranteed>>::{closure#0}, core[da5ff848ab5b9634]::result::Result<(), rustc_span[7e71af783b1896b5]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[da5ff848ab5b9634]::result::Result<(), rustc_span[7e71af783b1896b5]::ErrorGuaranteed>>
  54:     0x7f7390cb8ad1 - <<std[9295f5ecf1531c2a]::thread::Builder>::spawn_unchecked_<rustc_interface[b5ea119f6d9fba02]::util::run_in_thread_with_globals<rustc_interface[b5ea119f6d9fba02]::util::run_in_thread_pool_with_globals<rustc_interface[b5ea119f6d9fba02]::interface::run_compiler<core[da5ff848ab5b9634]::result::Result<(), rustc_span[7e71af783b1896b5]::ErrorGuaranteed>, rustc_driver_impl[2320baa211b147c5]::run_compiler::{closure#0}>::{closure#0}, core[da5ff848ab5b9634]::result::Result<(), rustc_span[7e71af783b1896b5]::ErrorGuaranteed>>::{closure#0}, core[da5ff848ab5b9634]::result::Result<(), rustc_span[7e71af783b1896b5]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[da5ff848ab5b9634]::result::Result<(), rustc_span[7e71af783b1896b5]::ErrorGuaranteed>>::{closure#1} as core[da5ff848ab5b9634]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  55:     0x7f7399577685 - std::sys::unix::thread::Thread::new::thread_start::h0316d03ce42d35a5
  56:     0x7f738fe94ac3 - start_thread
                               at ./nptl/pthread_create.c:442:8
  57:     0x7f738ff26660 - clone3
                               at ./misc/../sysdeps/unix/sysv/linux/x86_64/clone3.S:81
  58:                0x0 - <unknown>

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

```

</p>
</details>

### LINKED ISSUE #121422: ICE: `could not resolve DefId`
auto-reduced (treereduce-rust):
````rust
#![feature(non_lifetime_binders)]

trait Trait<T: ?Sized> {}

fn produce() -> impl for<T> Trait<(), Assoc = impl Trait<T>> {
    16
}


````

original:
````rust
// check-pass

#![feature(non_lifetime_binders)]
//~^ WARN the feature `non_lifetime_binders` is incomplete

trait Trait<T: ?Sized> {}

impl<T: ?Sized> Trait<T> for i32 {}

fn produce() -> impl for<T> Trait<(), Assoc = impl Trait<T>> {
    16
}

fn main() {
    let _ = produce();
}

````

Version information
````
rustc 1.78.0-nightly (f8131a48a 2024-02-21)
binary: rustc
commit-hash: f8131a48a46ac3bc8a3d0fe0477055b132cffdc3
commit-date: 2024-02-21
host: x86_64-unknown-linux-gnu
release: 1.78.0-nightly
LLVM version: 18.1.0

````

Command:
`/home/matthias/.rustup/toolchains/master/bin/rustc `

<details><summary><strong>Program output</strong></summary>
<p>

```
warning: the feature `non_lifetime_binders` is incomplete and may not be safe to use and/or cause compiler crashes
 --> /tmp/icemaker_global_tempdir.0emJgmZ88e4H/rustc_testrunner_tmpdir_reporting.nzVpYvTIjOr1/mvce.rs:1:12
  |
1 | #![feature(non_lifetime_binders)]
  |            ^^^^^^^^^^^^^^^^^^^^
  |
  = note: see issue #108185 <https://github.com/rust-lang/rust/issues/108185> for more information
  = note: `#[warn(incomplete_features)]` on by default

error[E0601]: `main` function not found in crate `mvce`
 --> /tmp/icemaker_global_tempdir.0emJgmZ88e4H/rustc_testrunner_tmpdir_reporting.nzVpYvTIjOr1/mvce.rs:7:2
  |
7 | }
  |  ^ consider adding a `main` function to `/tmp/icemaker_global_tempdir.0emJgmZ88e4H/rustc_testrunner_tmpdir_reporting.nzVpYvTIjOr1/mvce.rs`

error[E0220]: associated type `Assoc` not found for `Trait`
 --> /tmp/icemaker_global_tempdir.0emJgmZ88e4H/rustc_testrunner_tmpdir_reporting.nzVpYvTIjOr1/mvce.rs:5:39
  |
5 | fn produce() -> impl for<T> Trait<(), Assoc = impl Trait<T>> {
  |                                       ^^^^^ associated type `Assoc` not found

error: internal compiler error: could not resolve DefId(0:6 ~ mvce[8c01]::produce::T)
 --> /tmp/icemaker_global_tempdir.0emJgmZ88e4H/rustc_testrunner_tmpdir_reporting.nzVpYvTIjOr1/mvce.rs:5:58
  |
5 | fn produce() -> impl for<T> Trait<(), Assoc = impl Trait<T>> {
  |                                                          ^

thread 'rustc' panicked at compiler/rustc_hir_analysis/src/collect/resolve_bound_vars.rs:1470:14:
Box<dyn Any>
stack backtrace:
   0:     0x7ffba3b8caf6 - std::backtrace_rs::backtrace::libunwind::trace::hbec2edc838b433e2
                               at /rustc/f8131a48a46ac3bc8a3d0fe0477055b132cffdc3/library/std/src/../../backtrace/src/backtrace/libunwind.rs:104:5
   1:     0x7ffba3b8caf6 - std::backtrace_rs::backtrace::trace_unsynchronized::h88c30257ee0dd166
                               at /rustc/f8131a48a46ac3bc8a3d0fe0477055b132cffdc3/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7ffba3b8caf6 - std::sys_common::backtrace::_print_fmt::h9176654d509e3088
                               at /rustc/f8131a48a46ac3bc8a3d0fe0477055b132cffdc3/library/std/src/sys_common/backtrace.rs:68:5
   3:     0x7ffba3b8caf6 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h671feaee1776bf19
                               at /rustc/f8131a48a46ac3bc8a3d0fe0477055b132cffdc3/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x7ffba3bdda7c - core::fmt::rt::Argument::fmt::h59605c83ae32d935
                               at /rustc/f8131a48a46ac3bc8a3d0fe0477055b132cffdc3/library/core/src/fmt/rt.rs:142:9
   5:     0x7ffba3bdda7c - core::fmt::write::hf7af8dfcfd20db5b
                               at /rustc/f8131a48a46ac3bc8a3d0fe0477055b132cffdc3/library/core/src/fmt/mod.rs:1120:17
   6:     0x7ffba3b814bf - std::io::Write::write_fmt::h92a5dbf489025e71
                               at /rustc/f8131a48a46ac3bc8a3d0fe0477055b132cffdc3/library/std/src/io/mod.rs:1846:15
   7:     0x7ffba3b8c8a4 - std::sys_common::backtrace::_print::h00080302d23998ae
                               at /rustc/f8131a48a46ac3bc8a3d0fe0477055b132cffdc3/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x7ffba3b8c8a4 - std::sys_common::backtrace::print::h6b23124445400245
                               at /rustc/f8131a48a46ac3bc8a3d0fe0477055b132cffdc3/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x7ffba3b8f5eb - std::panicking::default_hook::{{closure}}::hd67b2f9d36675a28
  10:     0x7ffba3b8f339 - std::panicking::default_hook::h10a39ef11c714e42
                               at /rustc/f8131a48a46ac3bc8a3d0fe0477055b132cffdc3/library/std/src/panicking.rs:292:9
  11:     0x7ffba6a7a94c - std[5a8e7f94216a9138]::panicking::update_hook::<alloc[e14ab1f516d287ab]::boxed::Box<rustc_driver_impl[e279e4f1fedd9109]::install_ice_hook::{closure#0}>>::{closure#0}
  12:     0x7ffba3b8fd50 - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h37ba37dc48823c1d
                               at /rustc/f8131a48a46ac3bc8a3d0fe0477055b132cffdc3/library/alloc/src/boxed.rs:2030:9
  13:     0x7ffba3b8fd50 - std::panicking::rust_panic_with_hook::he3e3bc7c345bf54b
                               at /rustc/f8131a48a46ac3bc8a3d0fe0477055b132cffdc3/library/std/src/panicking.rs:786:13
  14:     0x7ffba6aa7524 - std[5a8e7f94216a9138]::panicking::begin_panic::<rustc_errors[34364e5c712fab73]::ExplicitBug>::{closure#0}
  15:     0x7ffba6aa4176 - std[5a8e7f94216a9138]::sys_common::backtrace::__rust_end_short_backtrace::<std[5a8e7f94216a9138]::panicking::begin_panic<rustc_errors[34364e5c712fab73]::ExplicitBug>::{closure#0}, !>
  16:     0x7ffba6a9f936 - std[5a8e7f94216a9138]::panicking::begin_panic::<rustc_errors[34364e5c712fab73]::ExplicitBug>
  17:     0x7ffba5417631 - <rustc_errors[34364e5c712fab73]::diagnostic::BugAbort as rustc_errors[34364e5c712fab73]::diagnostic::EmissionGuarantee>::emit_producing_guarantee
  18:     0x7ffba871e027 - <rustc_hir_analysis[71d4294717f7f2b7]::collect::resolve_bound_vars::BoundVarContext>::resolve_type_ref
  19:     0x7ffba51b7b52 - rustc_hir[170b9793d794ea06]::intravisit::walk_qpath::<rustc_hir_analysis[71d4294717f7f2b7]::collect::resolve_bound_vars::BoundVarContext>
  20:     0x7ffba51bea74 - <rustc_hir_analysis[71d4294717f7f2b7]::collect::resolve_bound_vars::BoundVarContext as rustc_hir[170b9793d794ea06]::intravisit::Visitor>::visit_path
  21:     0x7ffba858faef - <rustc_hir_analysis[71d4294717f7f2b7]::collect::resolve_bound_vars::BoundVarContext>::visit_poly_trait_ref_inner
  22:     0x7ffba871c4ae - rustc_hir[170b9793d794ea06]::intravisit::walk_item::<rustc_hir_analysis[71d4294717f7f2b7]::collect::resolve_bound_vars::BoundVarContext>
  23:     0x7ffba871b5b8 - <rustc_hir_analysis[71d4294717f7f2b7]::collect::resolve_bound_vars::BoundVarContext as rustc_hir[170b9793d794ea06]::intravisit::Visitor>::visit_item
  24:     0x7ffba858cb8a - rustc_hir_analysis[71d4294717f7f2b7]::collect::resolve_bound_vars::resolve_bound_vars
  25:     0x7ffba858c731 - rustc_query_impl[9d4c51777e2bb749]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[9d4c51777e2bb749]::query_impl::resolve_bound_vars::dynamic_query::{closure#2}::{closure#0}, rustc_middle[446dd094ad85939e]::query::erase::Erased<[u8; 8usize]>>
  26:     0x7ffba80f6be3 - rustc_query_system[9b2ccfe41ae3bb1b]::query::plumbing::try_execute_query::<rustc_query_impl[9d4c51777e2bb749]::DynamicConfig<rustc_query_system[9b2ccfe41ae3bb1b]::query::caches::VecCache<rustc_hir[170b9793d794ea06]::hir_id::OwnerId, rustc_middle[446dd094ad85939e]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[9d4c51777e2bb749]::plumbing::QueryCtxt, false>
  27:     0x7ffba80f670c - rustc_query_impl[9d4c51777e2bb749]::query_impl::resolve_bound_vars::get_query_non_incr::__rust_end_short_backtrace
  28:     0x7ffba80f62a6 - rustc_query_impl[9d4c51777e2bb749]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[9d4c51777e2bb749]::query_impl::named_variable_map::dynamic_query::{closure#2}::{closure#0}, rustc_middle[446dd094ad85939e]::query::erase::Erased<[u8; 8usize]>>
  29:     0x7ffba80f6be3 - rustc_query_system[9b2ccfe41ae3bb1b]::query::plumbing::try_execute_query::<rustc_query_impl[9d4c51777e2bb749]::DynamicConfig<rustc_query_system[9b2ccfe41ae3bb1b]::query::caches::VecCache<rustc_hir[170b9793d794ea06]::hir_id::OwnerId, rustc_middle[446dd094ad85939e]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[9d4c51777e2bb749]::plumbing::QueryCtxt, false>
  30:     0x7ffba80f664c - rustc_query_impl[9d4c51777e2bb749]::query_impl::named_variable_map::get_query_non_incr::__rust_end_short_backtrace
  31:     0x7ffba5e39cd2 - <dyn rustc_hir_analysis[71d4294717f7f2b7]::astconv::AstConv>::res_to_ty
  32:     0x7ffba801b7c0 - <dyn rustc_hir_analysis[71d4294717f7f2b7]::astconv::AstConv>::ast_ty_to_ty_inner
  33:     0x7ffba8944b44 - <dyn rustc_hir_analysis[71d4294717f7f2b7]::astconv::AstConv>::create_args_for_ast_path
  34:     0x7ffba8a71b10 - <dyn rustc_hir_analysis[71d4294717f7f2b7]::astconv::AstConv>::instantiate_poly_trait_ref
  35:     0x7ffba8a6eafc - <dyn rustc_hir_analysis[71d4294717f7f2b7]::astconv::AstConv>::compute_bounds
  36:     0x7ffba8940fa2 - rustc_hir_analysis[71d4294717f7f2b7]::collect::item_bounds::opaque_type_bounds
  37:     0x7ffba893f8f1 - rustc_hir_analysis[71d4294717f7f2b7]::collect::item_bounds::explicit_item_bounds
  38:     0x7ffba893ea67 - rustc_query_impl[9d4c51777e2bb749]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[9d4c51777e2bb749]::query_impl::explicit_item_bounds::dynamic_query::{closure#2}::{closure#0}, rustc_middle[446dd094ad85939e]::query::erase::Erased<[u8; 16usize]>>
  39:     0x7ffba893ea31 - <rustc_query_impl[9d4c51777e2bb749]::query_impl::explicit_item_bounds::dynamic_query::{closure#2} as core[85b4fd477ce5bb21]::ops::function::FnOnce<(rustc_middle[446dd094ad85939e]::ty::context::TyCtxt, rustc_span[adb133ac03280fc1]::def_id::DefId)>>::call_once
  40:     0x7ffba8158a40 - rustc_query_system[9b2ccfe41ae3bb1b]::query::plumbing::try_execute_query::<rustc_query_impl[9d4c51777e2bb749]::DynamicConfig<rustc_query_system[9b2ccfe41ae3bb1b]::query::caches::DefIdCache<rustc_middle[446dd094ad85939e]::query::erase::Erased<[u8; 16usize]>>, false, false, false>, rustc_query_impl[9d4c51777e2bb749]::plumbing::QueryCtxt, false>
  41:     0x7ffba8157121 - rustc_query_impl[9d4c51777e2bb749]::query_impl::explicit_item_bounds::get_query_non_incr::__rust_end_short_backtrace
  42:     0x7ffba81f4c6a - <rustc_hir_analysis[71d4294717f7f2b7]::collect::CollectItemTypesVisitor as rustc_hir[170b9793d794ea06]::intravisit::Visitor>::visit_item
  43:     0x7ffba81f3176 - rustc_hir_analysis[71d4294717f7f2b7]::collect::collect_mod_item_types
  44:     0x7ffba81f3109 - rustc_query_impl[9d4c51777e2bb749]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[9d4c51777e2bb749]::query_impl::collect_mod_item_types::dynamic_query::{closure#2}::{closure#0}, rustc_middle[446dd094ad85939e]::query::erase::Erased<[u8; 0usize]>>
  45:     0x7ffba8a2b2ed - rustc_query_system[9b2ccfe41ae3bb1b]::query::plumbing::try_execute_query::<rustc_query_impl[9d4c51777e2bb749]::DynamicConfig<rustc_query_system[9b2ccfe41ae3bb1b]::query::caches::DefaultCache<rustc_span[adb133ac03280fc1]::def_id::LocalModDefId, rustc_middle[446dd094ad85939e]::query::erase::Erased<[u8; 0usize]>>, false, false, false>, rustc_query_impl[9d4c51777e2bb749]::plumbing::QueryCtxt, false>
  46:     0x7ffba8a2ae17 - rustc_query_impl[9d4c51777e2bb749]::query_impl::collect_mod_item_types::get_query_non_incr::__rust_end_short_backtrace
  47:     0x7ffba87ad4e8 - rustc_hir_analysis[71d4294717f7f2b7]::check_crate
  48:     0x7ffba88a2dd3 - rustc_interface[7ca501d7f8f3a34f]::passes::analysis
  49:     0x7ffba88a2a29 - rustc_query_impl[9d4c51777e2bb749]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[9d4c51777e2bb749]::query_impl::analysis::dynamic_query::{closure#2}::{closure#0}, rustc_middle[446dd094ad85939e]::query::erase::Erased<[u8; 1usize]>>
  50:     0x7ffba8b3d4a5 - rustc_query_system[9b2ccfe41ae3bb1b]::query::plumbing::try_execute_query::<rustc_query_impl[9d4c51777e2bb749]::DynamicConfig<rustc_query_system[9b2ccfe41ae3bb1b]::query::caches::SingleCache<rustc_middle[446dd094ad85939e]::query::erase::Erased<[u8; 1usize]>>, false, false, false>, rustc_query_impl[9d4c51777e2bb749]::plumbing::QueryCtxt, false>
  51:     0x7ffba8b3d209 - rustc_query_impl[9d4c51777e2bb749]::query_impl::analysis::get_query_non_incr::__rust_end_short_backtrace
  52:     0x7ffba8b4c719 - rustc_interface[7ca501d7f8f3a34f]::interface::run_compiler::<core[85b4fd477ce5bb21]::result::Result<(), rustc_span[adb133ac03280fc1]::ErrorGuaranteed>, rustc_driver_impl[e279e4f1fedd9109]::run_compiler::{closure#0}>::{closure#0}
  53:     0x7ffba8dbe705 - std[5a8e7f94216a9138]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[7ca501d7f8f3a34f]::util::run_in_thread_with_globals<rustc_interface[7ca501d7f8f3a34f]::util::run_in_thread_pool_with_globals<rustc_interface[7ca501d7f8f3a34f]::interface::run_compiler<core[85b4fd477ce5bb21]::result::Result<(), rustc_span[adb133ac03280fc1]::ErrorGuaranteed>, rustc_driver_impl[e279e4f1fedd9109]::run_compiler::{closure#0}>::{closure#0}, core[85b4fd477ce5bb21]::result::Result<(), rustc_span[adb133ac03280fc1]::ErrorGuaranteed>>::{closure#0}, core[85b4fd477ce5bb21]::result::Result<(), rustc_span[adb133ac03280fc1]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[85b4fd477ce5bb21]::result::Result<(), rustc_span[adb133ac03280fc1]::ErrorGuaranteed>>
  54:     0x7ffba8dbe532 - <<std[5a8e7f94216a9138]::thread::Builder>::spawn_unchecked_<rustc_interface[7ca501d7f8f3a34f]::util::run_in_thread_with_globals<rustc_interface[7ca501d7f8f3a34f]::util::run_in_thread_pool_with_globals<rustc_interface[7ca501d7f8f3a34f]::interface::run_compiler<core[85b4fd477ce5bb21]::result::Result<(), rustc_span[adb133ac03280fc1]::ErrorGuaranteed>, rustc_driver_impl[e279e4f1fedd9109]::run_compiler::{closure#0}>::{closure#0}, core[85b4fd477ce5bb21]::result::Result<(), rustc_span[adb133ac03280fc1]::ErrorGuaranteed>>::{closure#0}, core[85b4fd477ce5bb21]::result::Result<(), rustc_span[adb133ac03280fc1]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[85b4fd477ce5bb21]::result::Result<(), rustc_span[adb133ac03280fc1]::ErrorGuaranteed>>::{closure#1} as core[85b4fd477ce5bb21]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  55:     0x7ffba3b99725 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h1bff3efb61c3fa6b
                               at /rustc/f8131a48a46ac3bc8a3d0fe0477055b132cffdc3/library/alloc/src/boxed.rs:2016:9
  56:     0x7ffba3b99725 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h83141cf549dced8a
                               at /rustc/f8131a48a46ac3bc8a3d0fe0477055b132cffdc3/library/alloc/src/boxed.rs:2016:9
  57:     0x7ffba3b99725 - std::sys::pal::unix::thread::Thread::new::thread_start::hbe9287fdd7c325bc
                               at /rustc/f8131a48a46ac3bc8a3d0fe0477055b132cffdc3/library/std/src/sys/pal/unix/thread.rs:108:17
  58:     0x7ffba39819eb - <unknown>
  59:     0x7ffba3a057cc - <unknown>
  60:                0x0 - <unknown>

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.78.0-nightly (f8131a48a 2024-02-21) running on x86_64-unknown-linux-gnu

query stack during panic:
#0 [resolve_bound_vars] resolving lifetimes
#1 [named_variable_map] looking up a named region
#2 [explicit_item_bounds] finding item bounds for `produce::{opaque#0}::{opaque#0}`
#3 [collect_mod_item_types] collecting item types in top-level module
#4 [analysis] running analysis passes on this crate
end of query stack
error: aborting due to 3 previous errors; 1 warning emitted

Some errors have detailed explanations: E0220, E0601.
For more information about an error, try `rustc --explain E0220`.

```

</p>
</details>

### LINKED ISSUE #125843: ICE: `could not resolve DefId `
snippet:
````rust
#![feature(non_lifetime_binders)]
trait v0<> {}
fn kind  :(v3main impl for<v4> v0<'_, v2 = impl v0<v4> + '_>) {}


````

Version information
````
rustc 1.80.0-nightly (20be84a7e 2024-05-31)
binary: rustc
commit-hash: 20be84a7e62af0a623af4bfb75df6d30cb39d6d0
commit-date: 2024-05-31
host: x86_64-unknown-linux-gnu
release: 1.80.0-nightly
LLVM version: 18.1.6

````

Command:
`/home/matthias/.rustup/toolchains/master/bin/rustc `

<details><summary><strong>Program output</strong></summary>
<p>

```
error: missing parameters for function definition
 --> /tmp/icemaker_global_tempdir.yFJFzLnlbeHE/rustc_testrunner_tmpdir_reporting.BHN55D02MAM3/mvce.rs:3:8
  |
3 | fn kind  :(v3main impl for<v4> v0<'_, v2 = impl v0<v4> + '_>) {}
  |        ^ help: add a parameter list

error: return types are denoted using `->`
 --> /tmp/icemaker_global_tempdir.yFJFzLnlbeHE/rustc_testrunner_tmpdir_reporting.BHN55D02MAM3/mvce.rs:3:10
  |
3 | fn kind  :(v3main impl for<v4> v0<'_, v2 = impl v0<v4> + '_>) {}
  |          ^ help: use `->` instead

error: expected one of `!`, `(`, `)`, `+`, `,`, `::`, or `<`, found keyword `impl`
 --> /tmp/icemaker_global_tempdir.yFJFzLnlbeHE/rustc_testrunner_tmpdir_reporting.BHN55D02MAM3/mvce.rs:3:19
  |
3 | fn kind  :(v3main impl for<v4> v0<'_, v2 = impl v0<v4> + '_>) {}
  |                  -^^^^ expected one of 7 possible tokens
  |                  |
  |                  help: missing `,`

error[E0106]: missing lifetime specifiers
 --> /tmp/icemaker_global_tempdir.yFJFzLnlbeHE/rustc_testrunner_tmpdir_reporting.BHN55D02MAM3/mvce.rs:3:35
  |
3 | fn kind  :(v3main impl for<v4> v0<'_, v2 = impl v0<v4> + '_>) {}
  |                                   ^^                     ^^ expected named lifetime parameter
  |                                   |
  |                                   expected named lifetime parameter
  |
  = help: this function's return type contains a borrowed value, but there is no value for it to be borrowed from
help: consider using the `'static` lifetime, but this is uncommon unless you're returning a borrowed value from a `const` or a `static`
  |
3 | fn kind  :(v3main impl for<v4> v0<'static, v2 = impl v0<v4> + 'static>) {}
  |                                   ~~~~~~~                     ~~~~~~~

error[E0412]: cannot find type `v3main` in this scope
 --> /tmp/icemaker_global_tempdir.yFJFzLnlbeHE/rustc_testrunner_tmpdir_reporting.BHN55D02MAM3/mvce.rs:3:12
  |
3 | fn kind  :(v3main impl for<v4> v0<'_, v2 = impl v0<v4> + '_>) {}
  |            ^^^^^^ not found in this scope

warning: the feature `non_lifetime_binders` is incomplete and may not be safe to use and/or cause compiler crashes
 --> /tmp/icemaker_global_tempdir.yFJFzLnlbeHE/rustc_testrunner_tmpdir_reporting.BHN55D02MAM3/mvce.rs:1:12
  |
1 | #![feature(non_lifetime_binders)]
  |            ^^^^^^^^^^^^^^^^^^^^
  |
  = note: see issue #108185 <https://github.com/rust-lang/rust/issues/108185> for more information
  = note: `#[warn(incomplete_features)]` on by default

warning: trait `v0` should have an upper camel case name
 --> /tmp/icemaker_global_tempdir.yFJFzLnlbeHE/rustc_testrunner_tmpdir_reporting.BHN55D02MAM3/mvce.rs:2:7
  |
2 | trait v0<> {}
  |       ^^ help: convert the identifier to upper camel case (notice the capitalization): `V0`
  |
  = note: `#[warn(non_camel_case_types)]` on by default

warning: type parameter `v4` should have an upper camel case name
 --> /tmp/icemaker_global_tempdir.yFJFzLnlbeHE/rustc_testrunner_tmpdir_reporting.BHN55D02MAM3/mvce.rs:3:28
  |
3 | fn kind  :(v3main impl for<v4> v0<'_, v2 = impl v0<v4> + '_>) {}
  |                            ^^ help: convert the identifier to upper camel case (notice the capitalization): `V4`

error[E0601]: `main` function not found in crate `mvce`
 --> /tmp/icemaker_global_tempdir.yFJFzLnlbeHE/rustc_testrunner_tmpdir_reporting.BHN55D02MAM3/mvce.rs:3:65
  |
3 | fn kind  :(v3main impl for<v4> v0<'_, v2 = impl v0<v4> + '_>) {}
  |                                                                 ^ consider adding a `main` function to `/tmp/icemaker_global_tempdir.yFJFzLnlbeHE/rustc_testrunner_tmpdir_reporting.BHN55D02MAM3/mvce.rs`

error[E0107]: trait takes 0 lifetime arguments but 1 lifetime argument was supplied
 --> /tmp/icemaker_global_tempdir.yFJFzLnlbeHE/rustc_testrunner_tmpdir_reporting.BHN55D02MAM3/mvce.rs:3:32
  |
3 | fn kind  :(v3main impl for<v4> v0<'_, v2 = impl v0<v4> + '_>) {}
  |                                ^^--------------------------- help: remove these generics
  |                                |
  |                                expected 0 lifetime arguments
  |
note: trait defined here, with 0 lifetime parameters
 --> /tmp/icemaker_global_tempdir.yFJFzLnlbeHE/rustc_testrunner_tmpdir_reporting.BHN55D02MAM3/mvce.rs:2:7
  |
2 | trait v0<> {}
  |       ^^

error[E0220]: associated type `v2` not found for `v0`
 --> /tmp/icemaker_global_tempdir.yFJFzLnlbeHE/rustc_testrunner_tmpdir_reporting.BHN55D02MAM3/mvce.rs:3:39
  |
3 | fn kind  :(v3main impl for<v4> v0<'_, v2 = impl v0<v4> + '_>) {}
  |                                       ^^ associated type `v2` not found

error[E0107]: trait takes 0 generic arguments but 1 generic argument was supplied
 --> /tmp/icemaker_global_tempdir.yFJFzLnlbeHE/rustc_testrunner_tmpdir_reporting.BHN55D02MAM3/mvce.rs:3:49
  |
3 | fn kind  :(v3main impl for<v4> v0<'_, v2 = impl v0<v4> + '_>) {}
  |                                                 ^^---- help: remove these generics
  |                                                 |
  |                                                 expected 0 generic arguments
  |
note: trait defined here, with 0 generic parameters
 --> /tmp/icemaker_global_tempdir.yFJFzLnlbeHE/rustc_testrunner_tmpdir_reporting.BHN55D02MAM3/mvce.rs:2:7
  |
2 | trait v0<> {}
  |       ^^

error: internal compiler error: could not resolve DefId(0:5 ~ mvce[3fa6]::kind::v4)
 --> /tmp/icemaker_global_tempdir.yFJFzLnlbeHE/rustc_testrunner_tmpdir_reporting.BHN55D02MAM3/mvce.rs:3:52
  |
3 | fn kind  :(v3main impl for<v4> v0<'_, v2 = impl v0<v4> + '_>) {}
  |                                                    ^^

thread 'rustc' panicked at compiler/rustc_hir_analysis/src/collect/resolve_bound_vars.rs:1461:14:
Box<dyn Any>
stack backtrace:
   0:     0x71a645c53cc5 - std::backtrace_rs::backtrace::libunwind::trace::h9f3d70c9733d841d
                               at /rustc/20be84a7e62af0a623af4bfb75df6d30cb39d6d0/library/std/src/../../backtrace/src/backtrace/libunwind.rs:116:5
   1:     0x71a645c53cc5 - std::backtrace_rs::backtrace::trace_unsynchronized::h18a7c2b106fba01e
                               at /rustc/20be84a7e62af0a623af4bfb75df6d30cb39d6d0/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x71a645c53cc5 - std::sys_common::backtrace::_print_fmt::h51b9aab95f9337b6
                               at /rustc/20be84a7e62af0a623af4bfb75df6d30cb39d6d0/library/std/src/sys_common/backtrace.rs:68:5
   3:     0x71a645c53cc5 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h5962f96b03d62e09
                               at /rustc/20be84a7e62af0a623af4bfb75df6d30cb39d6d0/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x71a645ca46bb - core::fmt::rt::Argument::fmt::hf535dbee9d8bf491
                               at /rustc/20be84a7e62af0a623af4bfb75df6d30cb39d6d0/library/core/src/fmt/rt.rs:165:63
   5:     0x71a645ca46bb - core::fmt::write::h715ab647ff75b718
                               at /rustc/20be84a7e62af0a623af4bfb75df6d30cb39d6d0/library/core/src/fmt/mod.rs:1168:21
   6:     0x71a645c48a4f - std::io::Write::write_fmt::h51a61126f28423f0
                               at /rustc/20be84a7e62af0a623af4bfb75df6d30cb39d6d0/library/std/src/io/mod.rs:1835:15
   7:     0x71a645c53a9e - std::sys_common::backtrace::_print::hb5bb864cf394908c
                               at /rustc/20be84a7e62af0a623af4bfb75df6d30cb39d6d0/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x71a645c53a9e - std::sys_common::backtrace::print::h9808ce89dcfc167b
                               at /rustc/20be84a7e62af0a623af4bfb75df6d30cb39d6d0/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x71a645c564d9 - std::panicking::default_hook::{{closure}}::h8d21bb511b5c1e78
  10:     0x71a645c5627a - std::panicking::default_hook::h4b2c758dea5df587
                               at /rustc/20be84a7e62af0a623af4bfb75df6d30cb39d6d0/library/std/src/panicking.rs:298:9
  11:     0x71a64232ee6f - std[b00b182216382e6e]::panicking::update_hook::<alloc[7ffab2895a2c57d5]::boxed::Box<rustc_driver_impl[76688ae60f501fda]::install_ice_hook::{closure#0}>>::{closure#0}
  12:     0x71a645c56c0b - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h8924c01e9ca42ec1
                               at /rustc/20be84a7e62af0a623af4bfb75df6d30cb39d6d0/library/alloc/src/boxed.rs:2077:9
  13:     0x71a645c56c0b - std::panicking::rust_panic_with_hook::h0e8c82a619b41cae
                               at /rustc/20be84a7e62af0a623af4bfb75df6d30cb39d6d0/library/std/src/panicking.rs:799:13
  14:     0x71a64235ef34 - std[b00b182216382e6e]::panicking::begin_panic::<rustc_errors[f2240d3a83010696]::ExplicitBug>::{closure#0}
  15:     0x71a64235bb36 - std[b00b182216382e6e]::sys_common::backtrace::__rust_end_short_backtrace::<std[b00b182216382e6e]::panicking::begin_panic<rustc_errors[f2240d3a83010696]::ExplicitBug>::{closure#0}, !>
  16:     0x71a64235b816 - std[b00b182216382e6e]::panicking::begin_panic::<rustc_errors[f2240d3a83010696]::ExplicitBug>
  17:     0x71a6423683b1 - <rustc_errors[f2240d3a83010696]::diagnostic::BugAbort as rustc_errors[f2240d3a83010696]::diagnostic::EmissionGuarantee>::emit_producing_guarantee
  18:     0x71a6423e05a8 - <rustc_errors[f2240d3a83010696]::DiagCtxt>::span_bug::<rustc_span[56a58ca3bbf1d657]::span_encoding::Span, alloc[7ffab2895a2c57d5]::string::String>
  19:     0x71a64443a15d - <rustc_hir_analysis[3427582cd7078f06]::collect::resolve_bound_vars::BoundVarContext>::resolve_type_ref
  20:     0x71a640bd63c8 - rustc_hir[ee96af3dfdcd5f01]::intravisit::walk_qpath::<rustc_hir_analysis[3427582cd7078f06]::collect::resolve_bound_vars::BoundVarContext>
  21:     0x71a640bd0f49 - <rustc_hir_analysis[3427582cd7078f06]::collect::resolve_bound_vars::BoundVarContext as rustc_hir[ee96af3dfdcd5f01]::intravisit::Visitor>::visit_path
  22:     0x71a6444337af - <rustc_hir_analysis[3427582cd7078f06]::collect::resolve_bound_vars::BoundVarContext>::visit_poly_trait_ref_inner
  23:     0x71a644436a89 - rustc_hir[ee96af3dfdcd5f01]::intravisit::walk_item::<rustc_hir_analysis[3427582cd7078f06]::collect::resolve_bound_vars::BoundVarContext>
  24:     0x71a6444361af - <rustc_hir_analysis[3427582cd7078f06]::collect::resolve_bound_vars::BoundVarContext as rustc_hir[ee96af3dfdcd5f01]::intravisit::Visitor>::visit_item
  25:     0x71a644001d18 - rustc_hir_analysis[3427582cd7078f06]::collect::resolve_bound_vars::resolve_bound_vars
  26:     0x71a6440018b7 - rustc_query_impl[7198874a8352ad7b]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[7198874a8352ad7b]::query_impl::resolve_bound_vars::dynamic_query::{closure#2}::{closure#0}, rustc_middle[e126b53f3333d426]::query::erase::Erased<[u8; 8usize]>>
  27:     0x71a643ffc05b - rustc_query_system[2bc1932167c59c8e]::query::plumbing::try_execute_query::<rustc_query_impl[7198874a8352ad7b]::DynamicConfig<rustc_query_system[2bc1932167c59c8e]::query::caches::VecCache<rustc_hir[ee96af3dfdcd5f01]::hir_id::OwnerId, rustc_middle[e126b53f3333d426]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[7198874a8352ad7b]::plumbing::QueryCtxt, false>
  28:     0x71a643ffba19 - rustc_query_impl[7198874a8352ad7b]::query_impl::resolve_bound_vars::get_query_non_incr::__rust_end_short_backtrace
  29:     0x71a643ffb8cc - rustc_query_impl[7198874a8352ad7b]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[7198874a8352ad7b]::query_impl::late_bound_vars_map::dynamic_query::{closure#2}::{closure#0}, rustc_middle[e126b53f3333d426]::query::erase::Erased<[u8; 8usize]>>
  30:     0x71a643ffc05b - rustc_query_system[2bc1932167c59c8e]::query::plumbing::try_execute_query::<rustc_query_impl[7198874a8352ad7b]::DynamicConfig<rustc_query_system[2bc1932167c59c8e]::query::caches::VecCache<rustc_hir[ee96af3dfdcd5f01]::hir_id::OwnerId, rustc_middle[e126b53f3333d426]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[7198874a8352ad7b]::plumbing::QueryCtxt, false>
  31:     0x71a643ffbb8d - rustc_query_impl[7198874a8352ad7b]::query_impl::late_bound_vars_map::get_query_non_incr::__rust_end_short_backtrace
  32:     0x71a643ff8d8d - <rustc_middle[e126b53f3333d426]::ty::context::TyCtxt>::late_bound_vars
  33:     0x71a6445468f0 - <dyn rustc_hir_analysis[3427582cd7078f06]::hir_ty_lowering::HirTyLowerer>::lower_poly_trait_ref
  34:     0x71a644542db8 - <dyn rustc_hir_analysis[3427582cd7078f06]::hir_ty_lowering::HirTyLowerer>::lower_mono_bounds
  35:     0x71a6444fbc30 - rustc_hir_analysis[3427582cd7078f06]::collect::item_bounds::opaque_type_bounds
  36:     0x71a6444faaae - rustc_hir_analysis[3427582cd7078f06]::collect::item_bounds::explicit_item_bounds_with_filter
  37:     0x71a6444fa654 - rustc_hir_analysis[3427582cd7078f06]::collect::item_bounds::explicit_item_bounds
  38:     0x71a6444fa635 - rustc_query_impl[7198874a8352ad7b]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[7198874a8352ad7b]::query_impl::explicit_item_bounds::dynamic_query::{closure#2}::{closure#0}, rustc_middle[e126b53f3333d426]::query::erase::Erased<[u8; 16usize]>>
  39:     0x71a6444fa609 - <rustc_query_impl[7198874a8352ad7b]::query_impl::explicit_item_bounds::dynamic_query::{closure#2} as core[9b5a30cfc7641096]::ops::function::FnOnce<(rustc_middle[e126b53f3333d426]::ty::context::TyCtxt, rustc_span[56a58ca3bbf1d657]::def_id::DefId)>>::call_once
  40:     0x71a643e234dc - rustc_query_system[2bc1932167c59c8e]::query::plumbing::try_execute_query::<rustc_query_impl[7198874a8352ad7b]::DynamicConfig<rustc_query_system[2bc1932167c59c8e]::query::caches::DefIdCache<rustc_middle[e126b53f3333d426]::query::erase::Erased<[u8; 16usize]>>, false, false, false>, rustc_query_impl[7198874a8352ad7b]::plumbing::QueryCtxt, false>
  41:     0x71a643e27af9 - rustc_query_impl[7198874a8352ad7b]::query_impl::explicit_item_bounds::get_query_non_incr::__rust_end_short_backtrace
  42:     0x71a6443a500f - <rustc_hir_analysis[3427582cd7078f06]::collect::CollectItemTypesVisitor as rustc_hir[ee96af3dfdcd5f01]::intravisit::Visitor>::visit_item
  43:     0x71a64439ac44 - rustc_hir_analysis[3427582cd7078f06]::check::wfcheck::check_well_formed
  44:     0x71a64439ab47 - rustc_query_impl[7198874a8352ad7b]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[7198874a8352ad7b]::query_impl::check_well_formed::dynamic_query::{closure#2}::{closure#0}, rustc_middle[e126b53f3333d426]::query::erase::Erased<[u8; 1usize]>>
  45:     0x71a64439a2e6 - rustc_query_system[2bc1932167c59c8e]::query::plumbing::try_execute_query::<rustc_query_impl[7198874a8352ad7b]::DynamicConfig<rustc_query_system[2bc1932167c59c8e]::query::caches::VecCache<rustc_hir[ee96af3dfdcd5f01]::hir_id::OwnerId, rustc_middle[e126b53f3333d426]::query::erase::Erased<[u8; 1usize]>>, false, false, false>, rustc_query_impl[7198874a8352ad7b]::plumbing::QueryCtxt, false>
  46:     0x71a64439a064 - rustc_query_impl[7198874a8352ad7b]::query_impl::check_well_formed::get_query_non_incr::__rust_end_short_backtrace
  47:     0x71a644397f37 - rustc_hir_analysis[3427582cd7078f06]::check::wfcheck::check_mod_type_wf
  48:     0x71a644397d61 - rustc_query_impl[7198874a8352ad7b]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[7198874a8352ad7b]::query_impl::check_mod_type_wf::dynamic_query::{closure#2}::{closure#0}, rustc_middle[e126b53f3333d426]::query::erase::Erased<[u8; 1usize]>>
  49:     0x71a644289f30 - rustc_query_system[2bc1932167c59c8e]::query::plumbing::try_execute_query::<rustc_query_impl[7198874a8352ad7b]::DynamicConfig<rustc_query_system[2bc1932167c59c8e]::query::caches::DefaultCache<rustc_span[56a58ca3bbf1d657]::def_id::LocalModDefId, rustc_middle[e126b53f3333d426]::query::erase::Erased<[u8; 1usize]>>, false, false, false>, rustc_query_impl[7198874a8352ad7b]::plumbing::QueryCtxt, false>
  50:     0x71a644289cd9 - rustc_query_impl[7198874a8352ad7b]::query_impl::check_mod_type_wf::get_query_non_incr::__rust_end_short_backtrace
  51:     0x71a643e2d94c - rustc_hir_analysis[3427582cd7078f06]::check_crate
  52:     0x71a643e46d3e - rustc_interface[36e11d5fade2f9e3]::passes::analysis
  53:     0x71a643e4689b - rustc_query_impl[7198874a8352ad7b]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[7198874a8352ad7b]::query_impl::analysis::dynamic_query::{closure#2}::{closure#0}, rustc_middle[e126b53f3333d426]::query::erase::Erased<[u8; 1usize]>>
  54:     0x71a6445d43a5 - rustc_query_system[2bc1932167c59c8e]::query::plumbing::try_execute_query::<rustc_query_impl[7198874a8352ad7b]::DynamicConfig<rustc_query_system[2bc1932167c59c8e]::query::caches::SingleCache<rustc_middle[e126b53f3333d426]::query::erase::Erased<[u8; 1usize]>>, false, false, false>, rustc_query_impl[7198874a8352ad7b]::plumbing::QueryCtxt, false>
  55:     0x71a6445d410f - rustc_query_impl[7198874a8352ad7b]::query_impl::analysis::get_query_non_incr::__rust_end_short_backtrace
  56:     0x71a644444edc - rustc_interface[36e11d5fade2f9e3]::interface::run_compiler::<core[9b5a30cfc7641096]::result::Result<(), rustc_span[56a58ca3bbf1d657]::ErrorGuaranteed>, rustc_driver_impl[76688ae60f501fda]::run_compiler::{closure#0}>::{closure#1}
  57:     0x71a6444302c9 - std[b00b182216382e6e]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[36e11d5fade2f9e3]::util::run_in_thread_with_globals<rustc_interface[36e11d5fade2f9e3]::util::run_in_thread_pool_with_globals<rustc_interface[36e11d5fade2f9e3]::interface::run_compiler<core[9b5a30cfc7641096]::result::Result<(), rustc_span[56a58ca3bbf1d657]::ErrorGuaranteed>, rustc_driver_impl[76688ae60f501fda]::run_compiler::{closure#0}>::{closure#1}, core[9b5a30cfc7641096]::result::Result<(), rustc_span[56a58ca3bbf1d657]::ErrorGuaranteed>>::{closure#0}, core[9b5a30cfc7641096]::result::Result<(), rustc_span[56a58ca3bbf1d657]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[9b5a30cfc7641096]::result::Result<(), rustc_span[56a58ca3bbf1d657]::ErrorGuaranteed>>
  58:     0x71a644430080 - <<std[b00b182216382e6e]::thread::Builder>::spawn_unchecked_<rustc_interface[36e11d5fade2f9e3]::util::run_in_thread_with_globals<rustc_interface[36e11d5fade2f9e3]::util::run_in_thread_pool_with_globals<rustc_interface[36e11d5fade2f9e3]::interface::run_compiler<core[9b5a30cfc7641096]::result::Result<(), rustc_span[56a58ca3bbf1d657]::ErrorGuaranteed>, rustc_driver_impl[76688ae60f501fda]::run_compiler::{closure#0}>::{closure#1}, core[9b5a30cfc7641096]::result::Result<(), rustc_span[56a58ca3bbf1d657]::ErrorGuaranteed>>::{closure#0}, core[9b5a30cfc7641096]::result::Result<(), rustc_span[56a58ca3bbf1d657]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[9b5a30cfc7641096]::result::Result<(), rustc_span[56a58ca3bbf1d657]::ErrorGuaranteed>>::{closure#2} as core[9b5a30cfc7641096]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  59:     0x71a645c60bfb - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hcf19ff9fb573dd5c
                               at /rustc/20be84a7e62af0a623af4bfb75df6d30cb39d6d0/library/alloc/src/boxed.rs:2063:9
  60:     0x71a645c60bfb - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h911d5926b91dbfb2
                               at /rustc/20be84a7e62af0a623af4bfb75df6d30cb39d6d0/library/alloc/src/boxed.rs:2063:9
  61:     0x71a645c60bfb - std::sys::pal::unix::thread::Thread::new::thread_start::h763866eb5216580e
                               at /rustc/20be84a7e62af0a623af4bfb75df6d30cb39d6d0/library/std/src/sys/pal/unix/thread.rs:108:17
  62:     0x71a6459fd1cf - <unknown>
  63:     0x71a645a7e6ec - <unknown>
  64:                0x0 - <unknown>

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: please make sure that you have updated to the latest nightly

note: rustc 1.80.0-nightly (20be84a7e 2024-05-31) running on x86_64-unknown-linux-gnu

query stack during panic:
#0 [resolve_bound_vars] resolving lifetimes
#1 [late_bound_vars_map] looking up late bound vars
end of query stack
error: aborting due to 10 previous errors; 3 warnings emitted

Some errors have detailed explanations: E0106, E0107, E0220, E0412, E0601.
For more information about an error, try `rustc --explain E0106`.

```

</p>
</details>

@rustbot label +F-non_lifetime_binders

### LINKED ISSUE #129023: Opaque types should not be HIR items (and thus not be HIR owners)
### Summary

- Delete `hir::ItemKind::OpaqueTy`, add `hir::Node::OpaqueTy`
- Replace the `ItemId` in `hir::TyKind::OpaqueDef` with `&'hir OpaqueTy`
- Fix the fallout

A WIP version of much of this can be seen in 79a3e7a...dcb9e9a, but it's incomplete. The reason is that many parts of the compiler assume that opaques are items and handle them through implicit codepaths.

### Background

Currently, opaque types (e.g., return-position `impl Trait`) are lowered into a `hir::ItemKind::OpaqueTy` and then a `hir::TyKind::OpaqueDef` that references that item's ID. However, because opaques' `DefId`s are created in `rustc_ast_lowering`, yet opaques can contain nodes whose `DefId`s are created in `DefCollector` (such as anon consts, which may in turn contain arbitrary nested items), this causes an incorrect parenting structure. This issue was uncovered in #128844, and it impeded that change, which delayed creation of defs for all expression-like nodes (anon consts, closures, etc.) until `ast_lowering` to fix other issues relating to def parents. @BoxyUwU [summarized](https://github.com/rust-lang/rust/pull/128844#issuecomment-2282220453) the issue in that PR's thread, reproduced here:

> Context for why the `Item::OpaqueTy` changes since @cjgillot has started looking at this PR:
> 
> note: "this PR" indicates "this PR before the changes to opaques" as this was written from before those changes were made
> 
> Given the code example:
> 
> ```rust
> trait Trait<const N: usize> {}
> 
> #[rustfmt::skip]
> fn foo() -> impl Trait<{ struct Bar; 1 }> {}
> 
> impl Trait<1> for () {}
> ```
> 
> The `free_items` for this module are:
> 
> ```
> free_items: [
>   ItemId { owner_id: DefId(0:1 ~ playground_1[9aa8]::{use#0}) },
>   ItemId { owner_id: DefId(0:2 ~ playground_1[9aa8]::std) },
>   ItemId { owner_id: DefId(0:3 ~ playground_1[9aa8]::Trait) },
>   ItemId { owner_id: DefId(0:7 ~ playground_1[9aa8]::foo) },
>   ItemId { owner_id: DefId(0:11 ~ playground_1[9aa8]::foo::{opaque#0}) },
>   ItemId { owner_id: DefId(0:9 ~ playground_1[9aa8]::foo::{constant#0}::Bar) },
>   ItemId { owner_id: DefId(0:5 ~ playground_1[9aa8]::{impl#0}) }
> ]
> ```
> 
> so, `HirIdValidator` gets used on `foo,` `opaque#0` and `Bar,` but not the anon const
> 
>     * `foo` it will recurse and call `visit_nested_item` on the opaque which doesn't recurse, and just checks that the parent `DefId`'s hir's owner is `foo`
> 
>     * `opaque#0`it will recurse and... check the `HirId` of the anon const is right (for some definition of right, unrelated to any of this), then recurse inside it, then visit `Bar` as a nested item and check that: `Bar`'s def parent's hir's owner is `opaque#0`,
>       
>       * On nightly that def parent is the anon const, and the anon consts hir is indeed owned by opaque#0
>       * On this PR where items (that arent nested bodies) that are in anon consts are not parented to the anon const, `Bar`'s def parent is `foo`, so we attempt to check that `foo`'s hir's owner is `opaque#0` which it is not so we ICE
> 
> 
> On nightly: The def parent setup for `Bar` is `foo::{constant}::Bar`, `foo` and `opaque#0` are hir owners. When we validate `opaque`'s HirId's, it succeeds as we ignore anon consts, and the fact that `constant` exists means that `Bar`'s parent's hir is owned `opaque`. On this PR: The def parent setup for `bar` is `foo::Bar`, `foo` and `opaque#0` are hir owners. When we validate `opaque`s HirIds, it fails as `constant#0` is no longer the parent of `Bar` so it correctly detects that we have a nested thing in `opaque#0` with a parent that is "outside" of `opaque` in a different hir owner's hir
> 
> Conclusion: Opaque types either need to have their `DefId` created in `DefCollector` or needs to stop being a hir owner. Or, generally, if something is to be a hir owner node, the `DefId` for it should be created _before_ all children `DefId`s or else you cannot create the parent structure correctly.

As mentioned above, the alternative is to create `DefId`s for opaques ahead-of-time, in `DefCollector`, but that is unsatisfactory because lowering of opaque types is quite complicated and that logic exists in `rustc_ast_lowering`. IMO it also makes more intuitive sense to create defs for things that don't themselves participate in resolution, such as anon consts and opaque types, during `ast_lowering` rather than def collection.

### LINKED ISSUE #129099: ICE: type_alias_impl_trait: `panic in a destructor during cleanup`
### Code

```Rust
#![feature(type_alias_impl_trait)]

trait Trait {
    type Gat<'lt>;
}

fn dyn_hoops<T: Trait>(_: T) -> *const dyn for<'b> Iterator<Item = impl Sized + Captures<'a>> {
    loop {}
}

mod typeck {
    use super::*;
    type Opaque = impl Sized;
    fn define() -> Option<Opaque> {
        let _: Opaque = dyn_hoops::<u8>(0);
        None
    }
}

fn main() {}
```

### Meta

`rustc --version --verbose`:
```
rustc 1.82.0-nightly (80eb5a8e9 2024-08-13)
binary: rustc
commit-hash: 80eb5a8e910e5185d47cdefe3732d839c78a5e7e
commit-date: 2024-08-13
host: x86_64-unknown-linux-gnu
release: 1.82.0-nightly
LLVM version: 19.1.0
```

### Error output

```
error[E0261]: use of undeclared lifetime name `'a`
 --> a.rs:7:90
  |
7 | fn dyn_hoops<T: Trait>(_: T) -> *const dyn for<'b> Iterator<Item = impl Sized + Captures<'a>> {
  |                                                                                          ^^ undeclared lifetime
  |
  = note: for more information on higher-ranked polymorphism, visit https://doc.rust-lang.org/nomicon/hrtb.html
help: consider making the bound lifetime-generic with a new `'a` lifetime
  |
7 | fn dyn_hoops<T: Trait>(_: T) -> *const dyn for<'b> Iterator<Item = impl Sized + for<'a> Captures<'a>> {
  |                                                                                 +++++++
help: consider making the bound lifetime-generic with a new `'a` lifetime
  |
7 | fn dyn_hoops<T: Trait>(_: T) -> *const dyn for<'a, 'b> Iterator<Item = impl Sized + Captures<'a>> {
  |                                                +++
help: consider introducing lifetime `'a` here
  |
7 | fn dyn_hoops<'a, T: Trait>(_: T) -> *const dyn for<'b> Iterator<Item = impl Sized + Captures<'a>> {
  |              +++

error[E0405]: cannot find trait `Captures` in this scope
 --> a.rs:7:81
  |
7 | fn dyn_hoops<T: Trait>(_: T) -> *const dyn for<'b> Iterator<Item = impl Sized + Captures<'a>> {
  |                                                                                 ^^^^^^^^ not found in this scope
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
thread 'rustc' panicked at core/src/panicking.rs:229:5:
panic in a destructor during cleanup

error: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: please make sure that you have updated to the latest nightly

note: please attach the file at `/tmp/im/rustc-ice-2024-08-14T16_23_00-896091.txt` to your bug report

query stack during panic:
#0 [typeck] type-checking `typeck::define`
#1 [type_of_opaque] computing type of opaque `typeck::Opaque::{opaque#0}`
#2 [type_of] computing type of `typeck::Opaque::{opaque#0}`
#3 [check_well_formed] checking that `typeck::Opaque::{opaque#0}` is well-formed
#4 [check_mod_type_wf] checking that types are well-formed in module `typeck`
#5 [analysis] running analysis passes on this crate
end of query stack
thread caused non-unwinding panic. aborting.
[1]    896091 IOT instruction  RUST_BACKTRACE=full rustc a.rs
```

</p>
</details>

### PR DESCRIPTION
**Pull request by cjgillot**
Having opaque types as HIR owner introduces all sorts of complications. This PR proposes to make them regular HIR nodes instead.

I haven't gone through all the test changes yet, so there may be a few surprises.

Many thanks to @camelid for the first draft.
Fixes https://github.com/rust-lang/rust/issues/129023

Fixes #129099 
Fixes #125843 
Fixes #119716 
Fixes #121422

### CODE REVIEW

File: compiler/rustc_hir_analysis/src/collect.rs [hunk 1]
```diff
@@ -260,8 +260,8 @@ fn reject_placeholder_type_signatures_in_item<'tcx>(
         | hir::ItemKind::Trait(_, _, generics, ..)
         | hir::ItemKind::Impl(hir::Impl { generics, .. })
         | hir::ItemKind::Struct(_, generics) => (generics, true),
-        hir::ItemKind::OpaqueTy(hir::OpaqueTy { generics, .. })
-        | hir::ItemKind::TyAlias(_, generics) => (generics, false),
+        // FIXME: how to handle opaque types since no longer items
```
Comment (cjgillot) [inline compiler/rustc_hir_analysis/src/collect.rs:263]: Stray FIXME.

File: compiler/rustc_hir_analysis/src/collect.rs [hunk 2]
```diff
@@ -328,6 +328,19 @@ impl<'tcx> Visitor<'tcx> for CollectItemTypesVisitor<'tcx> {
...
+    fn visit_opaque_ty(&mut self, opaque: &'tcx hir::OpaqueTy<'tcx>) {
+        let def_id = opaque.def_id;
+        self.tcx.ensure().generics_of(def_id);
+        self.tcx.ensure().predicates_of(def_id);
+        self.tcx.ensure().explicit_item_bounds(def_id);
+        self.tcx.ensure().explicit_item_super_predicates(def_id);
+        self.tcx.ensure().item_bounds(def_id);
+        self.tcx.ensure().item_super_predicates(def_id);
+        intravisit::walk_opaque_ty(self, opaque);
+    }
```
Comment (cjgillot) [inline compiler/rustc_hir_analysis/src/collect.rs:342]: Is this really useful?

File: compiler/rustc_hir_analysis/src/collect.rs [hunk 3]
```diff
@@ -730,18 +743,8 @@ fn lower_item(tcx: TyCtxt<'_>, item_id: hir::ItemId) {
...
-            tcx.ensure().generics_of(def_id);
-            tcx.ensure().predicates_of(def_id);
-            tcx.ensure().explicit_item_bounds(def_id);
-            tcx.ensure().explicit_item_super_predicates(def_id);
-            tcx.ensure().item_bounds(def_id);
-            tcx.ensure().item_super_predicates(def_id);
-        }
-
+        // FIXME: ok to ignore opaque tys in collection?
+        //
```
Comment (cjgillot) [inline compiler/rustc_hir_analysis/src/collect.rs:747]: Stray FIXME.

File: compiler/rustc_privacy/src/lib.rs [hunk 4]
```diff
@@ -1723,19 +1706,34 @@ fn effective_visibilities(tcx: TyCtxt<'_>, (): ()) -> &EffectiveVisibilities {
...
+                visitor
+                    .reach_through_impl_trait(opaque.def_id, pub_ev)
+                    .generics()
+                    .predicates()
+                    .ty();
+            }
+        }
+
         visitor.changed = false;
     }
```
Comment (cjgillot) [inline compiler/rustc_privacy/src/lib.rs:1738]: @petrochenkov I'm not sure what I wrote is correct. Could you have a look?

File: tests/ui/async-await/in-trait/async-generics-and-bounds.stderr [hunk 5]
```diff
@@ -2,9 +2,9 @@ error[E0311]: the parameter type `T` may not live long enough
   --> $DIR/async-generics-and-bounds.rs:9:5
    |
 LL |     async fn foo(&self) -> &(T, U) where T: Debug + Sized, U: Hash;
-   |     ^^^^^^^^^^^^^-^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
-   |     |            |
-   |     |            the parameter type `T` must be valid for the anonymous lifetime as defined here...
+   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```
Comment (cjgillot) [inline tests/ui/async-await/in-trait/async-generics-and-bounds.stderr:5]: FIXME why did we lose the span?

File: tests/ui/async-await/multiple-lifetimes/ret-impl-trait-one.stderr [hunk 6]
```diff
@@ -30,6 +30,10 @@ help: to declare that `impl Trait<'a>` captures `'b`, you can add an explicit `'
    |
 LL | async fn async_ret_impl_trait1<'a, 'b>(a: &'a u8, b: &'b u8) -> impl Trait<'a> + 'b {
    |                                                                                ++++
+help: to declare that `impl Trait<'a>` captures `'b`, you can add an explicit `'b` lifetime bound
+   |
+LL | async fn async_ret_impl_trait1<'a, 'b>(a: &'a u8, b: &'b u8) -> impl Trait<'a> + 'b {
+   |                                                                                ++++
```
Comment (cjgillot) [inline tests/ui/async-await/multiple-lifetimes/ret-impl-trait-one.stderr:36]: FIXME why is this duplicated?

File: compiler/rustc_middle/src/hir/mod.rs [hunk 7]
```diff
@@ -28,6 +28,7 @@ pub struct ModuleItems {
     trait_items: Box<[TraitItemId]>,
     impl_items: Box<[ImplItemId]>,
     foreign_items: Box<[ForeignItemId]>,
+    opaques: Box<[LocalDefId]>,
```
Comment (petrochenkov) [inline compiler/rustc_middle/src/hir/mod.rs:31]: Why is it still necessary to "partially outline" opaques?
Is it a temporary measure to make migration easy, or it's actually useful to visit "all opaques in a module" sometimes?
We don't keep a similar list for closures for example.

File: compiler/rustc_middle/src/query/mod.rs [hunk 8]
```diff
@@ -1732,16 +1733,15 @@ rustc_queries! {
     /// Does lifetime resolution on items. Importantly, we can't resolve
     /// lifetimes directly on things like trait methods, because of trait params.
     /// See `rustc_resolve::late::lifetimes` for details.
-    query resolve_bound_vars(_: hir::OwnerId) -> &'tcx ResolveBoundVars {
+    query resolve_bound_vars(def_id: hir::OwnerId) -> &'tcx ResolveBoundVars {
```
Comment (petrochenkov) [inline compiler/rustc_middle/src/query/mod.rs:1736]:
```suggestion
    query resolve_bound_vars(owner_id: hir::OwnerId) -> &'tcx ResolveBoundVars {
```
Naming mismatch here an in a few other places below.

File: compiler/rustc_privacy/src/lib.rs (hunk 4 above)
Comment (petrochenkov) [reply compiler/rustc_privacy/src/lib.rs:1738]: Yep, everything looks correct.

**Comment by petrochenkov** [comment]
Ignoring all the ID parenting questions, the change looks reasonable to me because
- It reduces weirdness
  - We have some other nodes, like closures, that could could technically be "outlined" into items, but they are typically kept inline, and opaques not behave analogously to closures
- It doesn't complicate the compiler logic while reducing weirdness

Regarding DefIds, HirIds and parenting, the change is not strictly necessary (https://github.com/rust-lang/rust/issues/129023#issuecomment-2297559177) to fix the HIR ownership issues, and I'd like to discuss that topic separately (see my other messages in https://github.com/rust-lang/rust/issues/129023).

File: compiler/rustc_middle/src/hir/mod.rs (hunk 7 above)
Comment (cjgillot) [reply compiler/rustc_middle/src/hir/mod.rs:31]: We do have `body_owners`, which contains both fns, closures and coroutines.

Comment (petrochenkov) [reply compiler/rustc_middle/src/hir/mod.rs:31]: I finished reading the PR and saw the places where `opaques` are used, they are all reasonable.

**Comment by cjgillot** [comment]
Until I fix clippy:
@bors try @rust-timer queue

File: compiler/rustc_hir_analysis/src/collect/resolve_bound_vars.rs [hunk 9]
```diff
@@ -686,22 +678,19 @@ impl<'a, 'tcx> Visitor<'tcx> for BoundVarContext<'a, 'tcx> {
             hir::TyKind::Ref(lifetime_ref, ref mt) => {
                 self.visit_lifetime(lifetime_ref);
                 let scope = Scope::ObjectLifetimeDefault {
-                    lifetime: self.map.defs.get(&lifetime_ref.hir_id).cloned(),
+                    lifetime: self.map.defs.get(&lifetime_ref.hir_id.local_id).cloned(),
```
Comment (compiler-errors) [inline compiler/rustc_hir_analysis/src/collect/resolve_bound_vars.rs:681]: Is there any way we can assert that the lifetime's `OwnerId` is the same owner that we're resolving here?

Comment (compiler-errors) [reply compiler/rustc_hir_analysis/src/collect/resolve_bound_vars.rs:681]: And elsewhere throughout this file.

Comment (compiler-errors) [reply compiler/rustc_hir_analysis/src/collect/resolve_bound_vars.rs:681]: I'm possibly just being paranoid, though.

File: compiler/rustc_ast_lowering/src/index.rs [hunk 10]
```diff
@@ -228,6 +228,14 @@ impl<'a, 'hir> Visitor<'hir> for NodeCollector<'a, 'hir> {
         });
     }
 
+    fn visit_opaque_ty(&mut self, opaq: &'hir OpaqueTy<'hir>) {
+        self.insert(opaq.span, opaq.hir_id, Node::OpaqueTy(opaq));
+
+        self.with_parent(opaq.hir_id, |this| {
```
[the remark this answers is not in the document]
Comment (compiler-errors) [reply compiler/rustc_ast_lowering/src/index.rs:234]: Is this still a problem?

**Review by compiler-errors — APPROVED** [review]
This looks great to me. The fact that opaques were separate items was a constant source of annoyance and I'm glad to see this being settled.

I reviewed everything and only had a few questions. I am not totally caught up on the `DefId` mismatch problem, was that resolved?

This needs a rebase, and I'd like to take a quick look afterwards, so please ping me when that happens.

File: compiler/rustc_ast_lowering/src/index.rs (hunk 10 above)
[the remark this answers is not in the document]
Comment (cjgillot) [reply compiler/rustc_ast_lowering/src/index.rs:232]: https://github.com/rust-lang/rust/pull/129493 should have fixed this.

File: compiler/rustc_hir_analysis/src/collect/resolve_bound_vars.rs (hunk 9 above)
Comment (cjgillot) [reply compiler/rustc_hir_analysis/src/collect/resolve_bound_vars.rs:679]: I'm not convinced this is useful. We don't track the root `OwnerId`, so we'd need to add it, for limited benefit IMHO.
