### PR TITLE
Move `#![feature(const_precise_live_drops)]` checks earlier in the pipeline

### LINKED ISSUE #90770: Post-drop elaboration const-checking fails on ZSTs
Found by @nbdd0121 [here](https://github.com/rust-lang/rust/issues/73255#issuecomment-964832698), the following code compiles when it shouldn't:

```rust
#![feature(const_precise_live_drops)]

struct S;

impl Drop for S {
    fn drop(&mut self) {
        println!("Hello!");
    }
}

const fn foo() {
    let s = S;
}

fn main() {}
```

The final "post-borrowck cleanup" pass is the Deaggregator, which replaces the assignment _1 = S; with a nop because S has no fields. That means `_1` never gets initialized in the MIR before its `Drop` terminator, so the qualification logic doesn't assign it `NeedsDrop`.

### PR DESCRIPTION
**Pull request by ecstatic-morse**
Should mitigate the issues found during MCP on #73255.

Once this is done, we should clean up the queries a bit, since I think `mir_drops_elaborated_and_const_checked` can be merged back into `mir_promoted`.

Fixes #90770.

cc @rust-lang/wg-const-eval 
r? @nikomatsakis (since they reviewed #71824)

### CODE REVIEW

**Comment by ecstatic-morse** [comment]
Oh, actually Oli signed off on #71824, Niko just consulted.

r? @oli-obk

**Comment by oli-obk** [comment]
Does this affect the two newly opened issues from the MCP? If so, please add tests.

File: compiler/rustc_mir_transform/src/remove_uninit_drops.rs [hunk 1]
```diff
@@ -0,0 +1,171 @@
...
+use rustc_mir_dataflow::{self, move_path_children_matching, Analysis, MoveDataParamEnv};
+
+use crate::MirPass;
+
+/// Removes `Drop` and `DropAndReplace` terminators whose target is known to be uninitialized at
+/// that point.
+///
+/// This is redundant with drop elaboration, but we need to do it prior to const-checking, and
+/// running const-checking after drop elaboration makes it opimization dependent, causing issues
+/// like [#90770].
```
Comment (RalfJung) [inline compiler/rustc_mir_transform/src/remove_uninit_drops.rs:16]: Is it possible to move drop elaboration earlier, so we can still do const-checking after drop elaboration?

Also, isn't this *additionally* redundant with things done inside borrowck, which also knows to ignore those `Drop`/`DropAndReplace` terminators? It doesn't actually remove them, presumably it has an analysis to figure out that they are not needed. Is that the same analysis that is also used here?

Comment (ecstatic-morse) [reply compiler/rustc_mir_transform/src/remove_uninit_drops.rs:16]: > Is it possible to move drop elaboration earlier, so we can still do const-checking after drop elaboration?

How is that better than the status quo? To be clear, I think the status quo is perfectly valid, it just needed a stronger warning about what is allowed as part of `post_borrowck_cleanup`.

> Also, isn't this additionally redundant with things done inside borrowck, which also knows to ignore those Drop/DropAndReplace terminators? It doesn't actually remove them, presumably it has an analysis to figure out that they are not needed. Is that the same analysis that is also used here?

My long term goal ([as I stated in this comment](https://github.com/rust-lang/rust/issues/73255#issuecomment-961354314)) is to move `remove_uninit_drops` prior to borrow checking and remove the init logic in the borrow checker. I'm a little nervous about this, since I don't fully understand the purpose of the `FalseEdge`/`FalseUnwind` terminators, which the borrow checker requires . `FalseEdge`s seem to be used to connect distinct match arms to one another, which means we lose information about what the active variant is in a match arm body.

I requested some input about this idea from the MIR borrowck implementors as part of that comment. Perhaps you have some thoughts as well? It's trivial to (optionally) ignore `FalseEdge`s while computing `MaybeInitializedPlaces`, but I don't feel comfortable doing so unilaterally.

**Comment by ecstatic-morse** [comment]
@oli-obk I added a regression test for #90770. #91009 is not fixed by this PR.

Really fixing #91009 will require changes to promotion. `const_precise_live_drops` just makes it so the code we shouldn't be promoting actually compiles since we're no longer so dumb about what `Drop` terminators actually execute`. `const Drop` impls have a similar effect. I don't object to blocking stabilization until it's fixed, though.

**Comment by oli-obk** [comment]
Thanks! Yea, I think I need to have a closer look at promotion here before we stabilize precise drops

But that shouldn't block this PR. I already reviewed the logic and only the test was missing, so:

@bors r+

File: compiler/rustc_mir_transform/src/remove_uninit_drops.rs (hunk 1 above)
Comment (RalfJung) [reply compiler/rustc_mir_transform/src/remove_uninit_drops.rs:16]: > How is that better than the status quo?

My thinking was: if we can do drop elaboration early enough, maybe we don't have to redundantly also run remove_uninit_drops.

> I'm a little nervous about this, since I don't fully understand the purpose of the FalseEdge/FalseUnwind terminators, which the borrow checker requires . FalseEdges seem to be used to connect distinct match arms to one another, thus losing information about what the active variant is in a match arm body.

My rough idea for their purpose is that they make the borrow checker accept code that we do not want to accept -- the extra edges make variables 'more live', so that we do not accept code which depends on details such as the exact order in which disjoint match arms are being generated in the MIR. However, I do not have a good understanding of the borrow checker, so I hope you can get better info the the borrowck people -- @nikomatsakis might be able to help or at least say who should know these details. :)  @lqd and @matthewjasper  might also know more.
