### PR TITLE
Remove incorrect subtyping for `&mut Trait` and introduce coercion

### LINKED ISSUE #14985: Should bounds on mut trait objects be covariant?
Currently if `Trait1` and `Trait2` are traits, then `&mut Trait1+Trait2 <: &mut Trait1`. I.e., mutable trait objects are covariant. All other mutable references are invariant, that is `&mut T <: &mut T'` iff `T /equiv T'`.

Should trait objects also be invariant?

See also #12470, which is a similar issue but about lifetimes in the same situation (which must be invariant and not contravariant).

### PR DESCRIPTION
**Pull request by nikomatsakis**
Remove incorrect subtyping for `&mut Trait` and introduce coercion for `&mut (Trait+'a)` to `&mut (Trait+'b)` if `'a:'b`.

Fixes #14985.

r? @nrc

### CODE REVIEW

**Comment by eddyb** [comment]
I wish you'd cc me on these.

**Comment by nikomatsakis** [comment]
cc @eddyb :)

File: src/librustc/middle/infer/combine.rs [hunk 1]
```diff
@@ -557,18 +557,7 @@ pub fn super_tys<'tcx, C>(this: &C,
...
-            // used to use covariant subtyping. I have preserved this behaviour,
-            // even though it is probably incorrect. So don't go down the usual
-            // path which would require invariance.
-            let mt = match (&a_mt.ty.sty, &b_mt.ty.sty) {
-                (&ty::ty_trait(..), &ty::ty_trait(..)) if a_mt.mutbl == b_mt.mutbl => {
-                    let ty = try!(this.tys(a_mt.ty, b_mt.ty));
-                    ty::mt { ty: ty, mutbl: a_mt.mutbl }
-                }
-                _ => try!(this.mts(a_mt, b_mt))
-            };
```
Comment (nrc) [inline src/librustc/middle/infer/combine.rs]: \o/

File: src/librustc_typeck/check/coercion.rs [hunk 2]
```diff
@@ -340,21 +346,42 @@ impl<'f, 'tcx> Coerce<'f, 'tcx> {
...
+                    // Upcasts permit two things:
+                    //
+                    // 1. Dropping builtin bounds, e.g. `Foo+Send` to `Foo`
+                    // 2. Tightening the region bound, e.g. `Foo+'a` to `Foo+'b` if `'a : 'b`
+                    //
+                    // Note that neither of these changes requires any
+                    // change at runtime.  Eventually this will be
+                    // generalized.
+                    //
+                    // We always upcast when we can due because of
```
Comment (nrc) [inline src/librustc_typeck/check/coercion.rs]: typo?

File: src/librustc_typeck/check/coercion.rs [hunk 3]
```diff
@@ -340,21 +346,42 @@ impl<'f, 'tcx> Coerce<'f, 'tcx> {
...
+                    // reason #2 (region bounds).
+                    if
                         data_a.bounds.builtin_bounds.is_superset(&data_b.bounds.builtin_bounds)
```
Comment (nrc) [inline src/librustc_typeck/check/coercion.rs]: this formatting is upsetting

**Comment by nrc** [comment]
r+ modulo nits
