### PR TITLE
Tidy up miscellaneous bounds suggestions

### LINKED ISSUE #97677: Give helpful suggestions for code containing {integer} and other non-concrete types
Given the following initial code:  https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=37a16d044452d822d2e20198fe11f2bc

```rust
fn add_ten<N>(n: N) -> N {
    n + 10
}
```

The output of this code is acceptable and helpful.

```
error[[E0369]](https://doc.rust-lang.org/stable/error-index.html#E0369): cannot add `{integer}` to `N`
 --> src/lib.rs:2:7
  |
2 |     n + 10
  |     - ^ -- {integer}
  |     |
  |     N
  |
help: consider restricting type parameter `N`
  |
1 | fn add_ten<N: std::ops::Add<Output = {integer}>>(n: N) -> N {
  |             +++++++++++++++++++++++++++++++++++

For more information about this error, try `rustc --explain E0369`.
```

Ideally the compiler would suggest ``Output = N`` instead of ``Output = {integer}``, and infer that from the function body, i guess? I don't know, really, and it's not the main point of this issue

The problem is with the code that is suggested, which if copied verbatim, looks like this: https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=304fea0cb18adf21f14c2d39a327b652

```rust
fn add_ten<N: std::ops::Add<Output = {integer}>>(n: N) -> N {
    n + 10
}
```

And for this code, the current output is:

```
error[[E0425]](https://doc.rust-lang.org/stable/error-index.html#E0425): cannot find value `integer` in this scope
 --> src/lib.rs:1:39
  |
1 | fn add_ten<N: std::ops::Add<Output = {integer}>>(n: N) -> N {
  |                                       ^^^^^^^ not found in this scope

error[[E0658]](https://doc.rust-lang.org/stable/error-index.html#E0658): associated const equality is incomplete
 --> src/lib.rs:1:29
  |
1 | fn add_ten<N: std::ops::Add<Output = {integer}>>(n: N) -> N {
  |                             ^^^^^^^^^^^^^^^^^^
  |
  = note: [see issue #92827 <https://github.com/rust-lang/rust/issues/92827>](https://github.com/rust-lang/rust/issues/92827) for more information

error: mismatch in bind of associated type, got const
   --> src/lib.rs:1:29
    |
1   | fn add_ten<N: std::ops::Add<Output = {integer}>>(n: N) -> N {
    |                             ^^^^^^^^^^^^^^^^^^
    |
note: associated type defined here does not match const

Some errors have detailed explanations: E0425, E0658.
For more information about an error, try `rustc --explain E0425`.
```

Ideally the output should look like:

```diff
error[[E0425]](https://doc.rust-lang.org/stable/error-index.html#E0425): cannot find value `integer` in this scope
 --> src/lib.rs:1:39
  |
1 | fn add_ten<N: std::ops::Add<Output = {integer}>>(n: N) -> N {
  |                                       ^^^^^^^ not found in this scope

error[[E0658]](https://doc.rust-lang.org/stable/error-index.html#E0658): associated const equality is incomplete
 --> src/lib.rs:1:29
  |
1 | fn add_ten<N: std::ops::Add<Output = {integer}>>(n: N) -> N {
  |                             ^^^^^^^^^^^^^^^^^^
  |
  = note: [see issue #92827 <https://github.com/rust-lang/rust/issues/92827>](https://github.com/rust-lang/rust/issues/92827) for more information

error: mismatch in bind of associated type, got const
   --> src/lib.rs:1:29
    |
1   | fn add_ten<N: std::ops::Add<Output = {integer}>>(n: N) -> N {
    |                             ^^^^^^^^^^^^^^^^^^
    |
note: associated type defined here does not match const

+ help: consider replacing `{integer}` with a concrete integer type, such as `i32`
+    --> src/lib.rs:1:29
+     |
+ 1   | fn add_ten<N: std::ops::Add<Output = i32>>(n: N) -> N {
+     |                                      ^^^
+     |

Some errors have detailed explanations: E0425, E0658.
For more information about an error, try `rustc --explain E0425`.
```

Ideally, this help message should also appear if a constant ``{integer}`` does exist but causes an error.

### LINKED ISSUE #97760: Rust diagnostic for `impl Trait` suggests broken code
Given the following code:
https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=87a0987f6c8b7b1a67b03338e2a4ed09
The issues also reproduces with the nightly version on the playground.

```rust
pub fn print_values(values: &impl IntoIterator)
where
{
    for x in values.into_iter() {
        println!("{x}");
    }
}
```

The current output is:

```
error[[E0277]](https://doc.rust-lang.org/stable/error-index.html#E0277): `<impl IntoIterator as IntoIterator>::Item` doesn't implement `std::fmt::Display`
 --> src/lib.rs:5:20
  |
5 |         println!("{x}");
  |                    ^ `<impl IntoIterator as IntoIterator>::Item` cannot be formatted with the default formatter
  |
  = help: the trait `std::fmt::Display` is not implemented for `<impl IntoIterator as IntoIterator>::Item`
  = note: in format strings you may be able to use `{:?}` (or {:#?} for pretty-print) instead
  = note: this error originates in the macro `$crate::format_args_nl` (in Nightly builds, run with -Z macro-backtrace for more info)
help: introduce a type parameter with a trait bound instead of using `impl Trait`
  |
1 ~ pub fn print_values<I: IntoIterator>(values: &impl IntoIterator)
2 ~ where where <I as IntoIterator>::Item: std::fmt::Display
  |
```

The proposed code has multiple problems.
The code doubles the `where` leading to broken Rust.
The diagnostic correctly introduces the `I: IntoIterator`, but does not replace the `impl IntoIterator` in the function arguments.

If you remove the `where` from the initial example, the diagnostic changes to include `+++` markers for the added code. These seem helpful and to me it is not clear why they are missing initially.

```
help: introduce a type parameter with a trait bound instead of using `impl Trait`
  |
1 | pub fn print_values<I: IntoIterator>(values: &impl IntoIterator) where <I as IntoIterator>::Item: std::fmt::Display
  |                    +++++++++++++++++                             ++++++++++++++++++++++++++++++++++++++++++++++++++
```

### PR DESCRIPTION
**Pull request by compiler-errors**
Just some small fixes to suggestions

- Generalizes `Ty::is_suggestable` into a `TypeVisitor`, so that it can be called on things other than `Ty`
- Makes `impl Trait` in arg position no longer suggestible (generalizing the fix in #97640)
- Fixes `impl Trait` not being replaced with fresh type param when it's deeply nested in function signature (fixes #97760)
- Fixes some poor handling of `where` clauses with no predicates (also #97760)
- Uses `InferCtxt::resolve_numeric_literals_with_default` so we suggest `i32` instead of `{integer}` (fixes #97677)

Sorry there aren't many tests the fixes. Most of them would just be duplicates of other tests with empty `where` clauses or `impl Trait` in arg position instead of generic params. Let me know if you'd want more test coverage.

### CODE REVIEW

File: compiler/rustc_hir/src/hir.rs [hunk 1]
```diff
@@ -535,7 +535,8 @@ pub struct GenericParamCount {
 pub struct Generics<'hir> {
     pub params: &'hir [GenericParam<'hir>],
     pub predicates: &'hir [WherePredicate<'hir>],
-    pub has_where_clause: bool,
+    pub has_where_clause_predicates: bool,
+    pub has_where_clause_token: bool,
```
Comment (cjgillot) [inline compiler/rustc_hir/src/hir.rs:539]: Is this equivalent to `!where_clause_span.is_empty()`?

File: compiler/rustc_middle/src/ty/diagnostics.rs [hunk 2]
```diff
@@ -73,31 +73,53 @@ impl<'tcx> Ty<'tcx> {
             _ => self.is_simple_ty(),
         }
     }
+}
+
+pub trait IsSuggestable<'tcx> {
+    fn is_suggestable(self, tcx: TyCtxt<'tcx>) -> bool;
```
Comment (cjgillot) [inline compiler/rustc_middle/src/ty/diagnostics.rs:79]: Could you document what this does?

File: compiler/rustc_middle/src/ty/diagnostics.rs [hunk 3]
```diff
@@ -73,31 +73,53 @@ impl<'tcx> Ty<'tcx> {
...
 
-    /// Whether the type can be safely suggested during error recovery.
-    pub fn is_suggestable(self, tcx: TyCtxt<'tcx>) -> bool {
-        self.visit_with(&mut IsSuggestableVisitor { tcx }).is_continue()
+    fn is_suggestable_modulo_impl_trait(self, tcx: TyCtxt<'tcx>, bound_str: &str) -> bool;
```
Comment (cjgillot) [inline compiler/rustc_middle/src/ty/diagnostics.rs:81]: Could you document the difference with the other version?

File: compiler/rustc_trait_selection/src/traits/error_reporting/suggestions.rs [hunk 4]
```diff
@@ -572,6 +566,12 @@ impl<'a, 'tcx> InferCtxtExt<'tcx> for InferCtxt<'a, 'tcx> {
                 | hir::Node::ImplItem(hir::ImplItem { generics, .. })
                     if param_ty =>
                 {
+                    if !trait_pred.skip_binder().trait_ref.substs[1..]
```
Comment (cjgillot) [inline compiler/rustc_trait_selection/src/traits/error_reporting/suggestions.rs:584]: Why skip 0?

File: compiler/rustc_middle/src/ty/diagnostics.rs [hunk 5]
```diff
@@ -73,31 +73,53 @@ impl<'tcx> Ty<'tcx> {
...
-    constraint: &str,
+    trait_pred: PolyTraitPredicate<'tcx>,
 ) -> bool {
+    if !trait_pred.is_suggestable(tcx) {
+        return false;
+    }
+
+    let param_name = trait_pred.skip_binder().self_ty().to_string();
+    let constraint = trait_pred.print_modifiers_and_trait_path().to_string();
     let param = generics.params.iter().find(|p| p.name.ident().as_str() == param_name);
```
Comment (cjgillot) [inline compiler/rustc_middle/src/ty/diagnostics.rs:109]: Could we identify the parameter by DefId instead of string comparison?

File: compiler/rustc_middle/src/ty/diagnostics.rs [hunk 6]
```diff
@@ -463,3 +416,78 @@ impl<'v> hir::intravisit::Visitor<'v> for StaticLifetimeVisitor<'v> {
...
+                            // Okay
+                        }
+                        _ => return ControlFlow::Break(()),
+                    }
+                }
+            }
+
+            Param(param) => {
+                if let Some(found_bound_str) =
+                    param.name.as_str().strip_prefix("impl ").map(|s| s.trim_start())
```
Comment (cjgillot) [inline compiler/rustc_middle/src/ty/diagnostics.rs:466]: Could we rather work on the `DefId`?
There may be multiple `impl Trait` with the same string name.

File: compiler/rustc_trait_selection/src/traits/error_reporting/suggestions.rs [hunk 7]
```diff
@@ -368,21 +370,34 @@ fn suggest_restriction<'tcx>(
...
+                bound_str: &'a str,
+            }
+            impl<'a, 'hir> hir::intravisit::Visitor<'hir> for ReplaceImplTraitVisitor<'a> {
+                fn visit_ty(&mut self, t: &'hir hir::Ty<'hir>) {
+                    if let hir::TyKind::Path(hir::QPath::Resolved(
+                        None,
+                        hir::Path { segments: [segment], .. },
+                    )) = t.kind
+                    {
+                        if segment.ident.as_str().strip_prefix("impl ").map(|s| s.trim_start())
```
Comment (cjgillot) [inline compiler/rustc_trait_selection/src/traits/error_reporting/suggestions.rs:385]: Could be check the path's `res` instead of string content?

**Review by cjgillot — COMMENTED** [review]
This is a good improvement in diagnostics.
I have the impression we could get rid of the string comparisons, to avoid nonsense diagnostics if we have multiple impl trait with the same trait.

File: compiler/rustc_middle/src/ty/diagnostics.rs (hunk 6 above)
Comment (compiler-errors) [reply compiler/rustc_middle/src/ty/diagnostics.rs:466]: I would like to do this, but I was having trouble associating a `hir::GenericParam`, `ty::Param`, `DefId`... etc. I don't really know how to convert all of them to each other. Is there anywhere I should look to learn?

Comment (cjgillot) [reply compiler/rustc_middle/src/ty/diagnostics.rs:466]: `def_id == tcx.hir().local_def_id(hir_generic_param.hir_id) == tcx.generics_of(item).type_param(ty_param).def_id`
Does this help?

Comment (compiler-errors) [reply compiler/rustc_middle/src/ty/diagnostics.rs:466]: Yup, that probably works. I will try to refactor all of the string stuff to instead use the `DefId` of the generic instead.

**Comment by compiler-errors** [comment]
Addressed comments. I couldn't get rid of _all_ of the string manipulation, but I tried to use def-id where I could.

@rustbot ready

**Comment by Dylan-DPC** [comment]
failed in [rollup ci](https://github.com/rust-lang/rust/pull/97988#issuecomment-1152898481)

**Comment by compiler-errors** [comment]
Added `TypeSuperFoldable` import, which was apparently introduced sometime recently

@bors r=cjgillot
