### PR TITLE
Fix derive(PartialOrd) and optimise final field operation

### LINKED ISSUE #49505: Derive(PartialOrd) generates pretty bad code
```rust
#[automatically_derived]
#[allow(unused_qualifications)]
impl <T: ::std::cmp::PartialOrd> ::std::cmp::PartialOrd for Option<T> {
    #[inline]
    fn partial_cmp(&self, __arg_0: &Option<T>)
     -> ::std::option::Option<::std::cmp::Ordering> {
        {
            let __self_vi =
                unsafe { ::std::intrinsics::discriminant_value(&*self) } as
                    isize;
            let __arg_1_vi =
                unsafe { ::std::intrinsics::discriminant_value(&*__arg_0) } as
                    isize;
            if true && __self_vi == __arg_1_vi {
                match (&*self, &*__arg_0) {
                    (&Option::Some(ref __self_0),
                     &Option::Some(ref __arg_1_0)) =>
                    match ::std::cmp::PartialOrd::partial_cmp(&(*__self_0),
                                                              &(*__arg_1_0)) {
                        ::std::option::Option::Some(::std::cmp::Ordering::Equal)
                        =>
                        ::std::option::Option::Some(::std::cmp::Ordering::Equal),
                        __cmp => __cmp,
                    },
                    _ =>
                    ::std::option::Option::Some(::std::cmp::Ordering::Equal),
                }
            } else { __self_vi.partial_cmp(&__arg_1_vi) }
        }
    }
    #[inline]
    fn lt(&self, __arg_0: &Option<T>) -> bool {
        {
            let __self_vi =
                unsafe { ::std::intrinsics::discriminant_value(&*self) } as
                    isize;
            let __arg_1_vi =
                unsafe { ::std::intrinsics::discriminant_value(&*__arg_0) } as
                    isize;
            if true && __self_vi == __arg_1_vi {
                match (&*self, &*__arg_0) {
                    (&Option::Some(ref __self_0),
                     &Option::Some(ref __arg_1_0)) =>
                    (*__self_0) < (*__arg_1_0) ||
                        !((*__arg_1_0) < (*__self_0)) && false,
                    _ => false,
                }
            } else { __self_vi.lt(&__arg_1_vi) }
        }
    }
    #[inline]
    fn le(&self, __arg_0: &Option<T>) -> bool {
        {
            let __self_vi =
                unsafe { ::std::intrinsics::discriminant_value(&*self) } as
                    isize;
            let __arg_1_vi =
                unsafe { ::std::intrinsics::discriminant_value(&*__arg_0) } as
                    isize;
            if true && __self_vi == __arg_1_vi {
                match (&*self, &*__arg_0) {
                    (&Option::Some(ref __self_0),
                     &Option::Some(ref __arg_1_0)) =>
                    (*__self_0) < (*__arg_1_0) ||
                        !((*__arg_1_0) < (*__self_0)) && true,
                    _ => true,
                }
            } else { __self_vi.le(&__arg_1_vi) }
        }
    }
    #[inline]
    fn gt(&self, __arg_0: &Option<T>) -> bool {
        {
            let __self_vi =
                unsafe { ::std::intrinsics::discriminant_value(&*self) } as
                    isize;
            let __arg_1_vi =
                unsafe { ::std::intrinsics::discriminant_value(&*__arg_0) } as
                    isize;
            if true && __self_vi == __arg_1_vi {
                match (&*self, &*__arg_0) {
                    (&Option::Some(ref __self_0),
                     &Option::Some(ref __arg_1_0)) =>
                    (*__self_0) > (*__arg_1_0) ||
                        !((*__arg_1_0) > (*__self_0)) && false,
                    _ => false,
                }
            } else { __self_vi.gt(&__arg_1_vi) }
        }
    }
    #[inline]
    fn ge(&self, __arg_0: &Option<T>) -> bool {
        {
            let __self_vi =
                unsafe { ::std::intrinsics::discriminant_value(&*self) } as
                    isize;
            let __arg_1_vi =
                unsafe { ::std::intrinsics::discriminant_value(&*__arg_0) } as
                    isize;
            if true && __self_vi == __arg_1_vi {
                match (&*self, &*__arg_0) {
                    (&Option::Some(ref __self_0),
                     &Option::Some(ref __arg_1_0)) =>
                    (*__self_0) > (*__arg_1_0) ||
                        !((*__arg_1_0) > (*__self_0)) && true,
                    _ => true,
                }
            } else { __self_vi.ge(&__arg_1_vi) }
        }
    }
}
```

Instead of doing stuff such as `(a > b) || !(b > a) && true` in `ge`, rustc should probably just reuse the operator syntax by doing `a >= b`.

### LINKED ISSUE #49650: Error in derived `PartialOrd` for structs based on types with incomparable elements.
If a type deriving `PartialOrd` wraps another type which contains incomparable elements - and therefore only defines an implementation of `PartialOrd` and not a `Ord` - the derived implementations of the `le` and `ge` functions are flawed. 

The leads to a state where the internal type returns false as result of the expressions `a <= b` and `b >= a` for two incomparable elements `a` and `b` while the wrapper returns true. [[playground](https://play.rust-lang.org/?gist=e5a683321648f0df437ec9c861197e87&version=stable)]

If we look into the attached output of  `cargo-expand` it becomes clear that both implementations ignore the the underlying type only implements `PartialOrd` and may contain incomparable elements which can't be checked by `(a < b) || !(b < a)` or `(a > b) || !(a > b)`.

*Expanded: Less or Equal*
```rust
    #[inline]
    fn le(&self, __arg_0: &StructWithoutOrd) -> bool {
        match *__arg_0 {
            StructWithoutOrd(ref __self_1_0) => match *self {
                StructWithoutOrd(ref __self_0_0) => {
                    (*__self_0_0) < (*__self_1_0) || !((*__self_1_0) < (*__self_0_0)) && true
                }   
            },  
        }   
    }
```

*Expanded: Greater or Equal*
```rust
    #[inline]
    fn ge(&self, __arg_0: &StructWithoutOrd) -> bool {
        match *__arg_0 {
            StructWithoutOrd(ref __self_1_0) => match *self {
                StructWithoutOrd(ref __self_0_0) => {
                    (*__self_0_0) > (*__self_1_0) || !((*__self_1_0) > (*__self_0_0)) && true
                }   
            },  
        }   
    }
```

### PR DESCRIPTION
**Pull request by varkor**
```rust
// Before (`lt` on 2-field struct)
self.f1 < other.f1 || (!(other.f1 < self.f1) &&
(self.f2 < other.f2 || (!(other.f2 < self.f2) &&
(false)
))
)

// After
self.f1 < other.f1 || (!(other.f1 < self.f1) &&
self.f2 < other.f2
)

// Before (`le` on 2-field struct)
self.f1 < other.f1 || (!(other.f1 < self.f1) &&
(self.f2 < other.f2 || (!(other.f2 < self.f2) &&
(true)
))
)

// After
self.f1 < other.f1 || (self.f1 == other.f1 &&
self.f2 <= other.f2
)
```

(The big diff is mainly because of a past faulty rustfmt application that I corrected 😒)

Fixes #49650 and fixes #49505.

### CODE REVIEW

**Comment by TimNN** [comment]
Your PR [failed on Travis](https://travis-ci.org/rust-lang/rust/jobs/365177761) ([raw log](https://api.travis-ci.org/v3/job/365177761/log.txt)). Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.

<details><summary><i>Click to expand the log.</i></summary>

```plain
Resolving deltas: 100% (613662/613662), completed with 4881 local objects.
---
[00:00:47] configure: rust.quiet-tests     := True
---
[00:45:31] ..............................................................................i.....................
[00:45:37] .....................i..............................................................................
---
[00:46:20] i..........................................................................i........................
---
[00:47:17] .............................................i......................................................
---
[00:51:17] ..............................i.....................................................................
[00:51:32] ...............................................................i....................................
[00:51:48] ................................................i...................................................
[00:52:09] ....................................................................................................
[00:52:31] ....................................................................................................
[00:52:54] ....................................................................................................
[00:53:20] ....i...............................................................................................
[00:53:46] i.............................................................................test [run-pass] run-pass/mir_heavy_promoted.rs has been running for over 60 seconds
[00:53:57] ......................
[00:54:29] ....................................................................................................
[00:55:03] ..................................................................ii................................
[00:55:51] .............................i....................................................i.ii.test [run-pass] run-pass/saturating-float-casts.rs has been running for over 60 seconds
[00:55:58] .............
[00:56:41] ..........................................................................................iiiiiii...
---
[00:58:56] ...................i...................................................FF.FF....ii.iii..............
[00:59:04] ....................................................................................................
[00:59:12] .........i..............................i...........................................................
[00:59:19] ....................................................................................................
[00:59:26] .....................i..............................................................................
[00:59:34] ....................................................................................................
[00:59:44] ....................................................................................................
[00:59:55] ....................................................................................................
[01:00:06] ....................................................................................................
[01:00:20] ....................................................................................................
[01:00:28] ..............i.....................................................................................
[01:00:38] ..................i..ii.............................................................................
[01:00:48] ....................................................................................................
[01:00:58] .......................F............................................................................
[01:01:08] .....................................................................................i..............
[01:01:19] ...............................i....................................................................
---
[01:01:55] error: /checkout/src/test/compile-fail/derives-span-PartialOrd-enum-struct-variant.rs:19: unexpected error: '19:6: 19:14: binary operation `>` cannot be applied to type `Error` [E0369]'
[01:01:55]
[01:01:55] error: /checkout/src/test/compile-fail/derives-span-PartialOrd-enum-struct-variant.rs:19: unexpected error: '19:6: 19:14: binary operation `>=` cannot be applied to type `Error` [E0369]'
[01:01:55]
[01:01:55] error: 2 unexpected errors found, 0 expected errors not found
[01:01:55] status: exit code: 101
[01:01:55] command: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc" "/checkout/src/test/compile-fail/derives-span-PartialOrd-enum-struct-variant.rs" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/compile-fail" "--target=x86_64-unknown-linux-gnu" "--error-format" "json" "-Zui-testing" "-C" "prefer-dynamic" "-o" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/compile-fail/derives-span-PartialOrd-enum-struct-variant.stage2-x86_64-unknown-linux-gnu" "-Crpath" "-O" "-Zmiri" "-Zunstable-options" "-Lnative=/checkout/obj/build/x86_64-unknown-linux-gnu/native/rust-test-helpers" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/compile-fail/derives-span-PartialOrd-enum-struct-variant.stage2-x86_64-unknown-linux-gnu.aux" "-A" "unused"
[01:01:55] unexpected errors (from JSON output): [
[01:01:55]     Error {
[01:01:55]         line_num: 19,
[01:01:55]         kind: Some(
[01:01:55]             Error
[01:01:55]         ),
[01:01:55]         msg: "19:6: 19:14: binary operation `>` cannot be applied to type `Error` [E0369]"
---
[01:01:55]         msg: "19:6: 19:14: binary operation `>=` cannot be applied to type `Error` [E0369]"
---
[01:01:55] error: /checkout/src/test/compile-fail/derives-span-PartialOrd-enum.rs:19: unexpected error: '19:6: 22:7: binary operation `>` cannot be applied to type `Error` [E0369]'
[01:01:55]
[01:01:55] error: /checkout/src/test/compile-fail/derives-span-PartialOrd-enum.rs:19: unexpected error: '19:6: 22:7: binary operation `>=` cannot be applied to type `Error` [E0369]'
[01:01:55]
[01:01:55] error: 2 unexpected errors found, 0 expected errors not found
[01:01:55] status: exit code: 101
[01:01:55] command: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc" "/checkout/src/test/compile-fail/derives-span-PartialOrd-enum.rs" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/compile-fail" "--target=x86_64-unknown-linux-gnu" "--error-format" "json" "-Zui-testing" "-C" "prefer-dynamic" "-o" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/compile-fail/derives-span-PartialOrd-enum.stage2-x86_64-unknown-linux-gnu" "-Crpath" "-O" "-Zmiri" "-Zunstable-options" "-Lnative=/checkout/obj/build/x86_64-unknown-linux-gnu/native/rust-test-helpers" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/compile-fail/derives-span-PartialOrd-enum.stage2-x86_64-unknown-linux-gnu.aux" "-A" "unused"
[01:01:55] unexpected errors (from JSON output): [
[01:01:55]     Error {
[01:01:55]         line_num: 19,
[01:01:55]         kind: Some(
[01:01:55]             Error
[01:01:55]         ),
[01:01:55]         msg: "19:6: 22:7: binary operation `>` cannot be applied to type `Error` [E0369]"
---
[01:01:55]         msg: "19:6: 22:7: binary operation `>=` cannot be applied to type `Error` [E0369]"
[01:01:55]     }
[01:01:55] ]
[01:01:55]
[01:01:55] thread '[compile-fail] compile-fail/derives-span-PartialOrd-enum.rs' panicked at 'explicit panic', tools/compiletest/src/runtest.rs:1254:13
[01:01:55]
[01:01:55] ---- [compile-fail] compile-fail/derives-span-PartialOrd-tuple-struct.rs stdout ----
[01:01:55]
[01:01:55] error: /checkout/src/test/compile-fail/derives-span-PartialOrd-tuple-struct.rs:18: unexpected error: '18:5: 21:2: binary operation `>` cannot be applied to type `Error` [E0369]'
[01:01:55]
[01:01:55] error: /checkout/src/test/compile-fail/derives-span-PartialOrd-tuple-struct.rs:18: unexpected error: '18:5: 21:2: binary operation `>=` cannot be applied to type `Error` [E0369]'
[01:01:55]
[01:01:55] error: 2 unexpected errors found, 0 expected errors not found
[01:01:55] status: exit code: 101
[01:01:55] command: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc" "/checkout/src/test/compile-fail/derives-span-PartialOrd-tuple-struct.rs" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/compile-fail" "--target=x86_64-unknown-linux-gnu" "--error-format" "json" "-Zui-testing" "-C" "prefer-dynamic" "-o" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/compile-fail/derives-span-PartialOrd-tuple-struct.stage2-x86_64-unknown-linux-gnu" "-Crpath" "-O" "-Zmiri" "-Zunstable-options" "-Lnative=/checkout/obj/build/x86_64-unknown-linux-gnu/native/rust-test-helpers" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/compile-fail/derives-span-PartialOrd-tuple-struct.stage2-x86_64-unknown-linux-gnu.aux" "-A" "unused"
[01:01:55] unexpected errors (from JSON output): [
[01:01:55]     Error {
[01:01:55]         line_num: 18,
[01:01:55]         kind: Some(
[01:01:55]             Error
[01:01:55]         ),
[01:01:55]         msg: "18:5: 21:2: binary operation `>` cannot be applied to type `Error` [E0369]"
---
[01:01:55]         msg: "18:5: 21:2: binary operation `>=` cannot be applied to type `Error` [E0369]"
---
[01:01:55] error: /checkout/src/test/compile-fail/derives-span-PartialOrd-struct.rs:18: unexpected error: '18:5: 18:13: binary operation `>` cannot be applied to type `Error` [E0369]'
[01:01:55]
[01:01:55] error: /checkout/src/test/compile-fail/derives-span-PartialOrd-struct.rs:18: unexpected error: '18:5: 18:13: binary operation `>=` cannot be applied to type `Error` [E0369]'
[01:01:55]
[01:01:55] error: 2 unexpected errors found, 0 expected errors not found
[01:01:55] status: exit code: 101
[01:01:55] command: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc" "/checkout/src/test/compile-fail/derives-span-PartialOrd-struct.rs" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/compile-fail" "--target=x86_64-unknown-linux-gnu" "--error-format" "json" "-Zui-testing" "-C" "prefer-dynamic" "-o" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/compile-fail/derives-span-PartialOrd-struct.stage2-x86_64-unknown-linux-gnu" "-Crpath" "-O" "-Zmiri" "-Zunstable-options" "-Lnative=/checkout/obj/build/x86_64-unknown-linux-gnu/native/rust-test-helpers" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/compile-fail/derives-span-PartialOrd-struct.stage2-x86_64-unknown-linux-gnu.aux" "-A" "unused"
[01:01:55] unexpected errors (from JSON output): [
[01:01:55]     Error {
[01:01:55]         line_num: 18,
[01:01:55]         kind: Some(
[01:01:55]             Error
[01:01:55]         ),
[01:01:55]         msg: "18:5: 18:13: binary operation `>` cannot be applied to type `Error` [E0369]"
---
[01:01:55]         msg: "18:5: 18:13: binary operation `>=` cannot be applied to type `Error` [E0369]"
---
[01:01:55] error: /checkout/src/test/compile-fail/range_traits-1.rs:40: unexpected error: '40:5: 40:31: binary operation `<=` cannot be applied to type `std::ops::RangeToInclusive<usize>` [E0369]'
[01:01:55]
[01:01:55] error: /checkout/src/test/compile-fail/range_traits-1.rs:40: unexpected error: '40:5: 40:31: binary operation `>=` cannot be applied to type `std::ops::RangeToInclusive<usize>` [E0369]'
[01:01:55]
[01:01:55] error: 2 unexpected errors found, 0 expected errors not found
[01:01:55] status: exit code: 101
[01:01:55] command: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc" "/checkout/src/test/compile-fail/range_traits-1.rs" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/compile-fail" "--target=x86_64-unknown-linux-gnu" "--error-format" "json" "-Zui-testing" "-C" "prefer-dynamic" "-o" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/compile-fail/range_traits-1.stage2-x86_64-unknown-linux-gnu" "-Crpath" "-O" "-Zmiri" "-Zunstable-options" "-Lnative=/checkout/obj/build/x86_64-unknown-linux-gnu/native/rust-test-helpers" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/compile-fail/range_traits-1.stage2-x86_64-unknown-linux-gnu.aux" "-A" "unused"
[01:01:55] unexpected errors (from JSON output): [
[01:01:55]     Error {
[01:01:55]         line_num: 40,
[01:01:55]         kind: Some(
[01:01:55]             Error
[01:01:55]         ),
[01:01:55]         msg: "40:5: 40:31: binary operation `<=` cannot be applied to type `std::ops::RangeToInclusive<usize>` [E0369]"
---
[01:01:55]         msg: "40:5: 40:31: binary operation `>=` cannot be applied to type `std::ops::RangeToInclusive<usize>` [E0369]"
[01:01:55]     }
[01:01:55] ]
[01:01:55]
[01:01:55] thread '[compile-fail] compile-fail/range_traits-1.rs' panicked at 'explicit panic', tools/compiletest/src/runtest.rs:1254:13
---
[01:01:55] command did not execute successfully: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-tools-bin/compiletest" "--compile-lib-path" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/lib" "--run-lib-path" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/lib/rustlib/x86_64-unknown-linux-gnu/lib" "--rustc-path" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc" "--src-base" "/checkout/src/test/compile-fail" "--build-base" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/compile-fail" "--stage-id" "stage2-x86_64-unknown-linux-gnu" "--mode" "compile-fail" "--target" "x86_64-unknown-linux-gnu" "--host" "x86_64-unknown-linux-gnu" "--llvm-filecheck" "/usr/lib/llvm-3.9/bin/FileCheck" "--host-rustcflags" "-Crpath -O -Zmiri -Zunstable-options " "--target-rustcflags" "-Crpath -O -Zmiri -Zunstable-options  -Lnative=/checkout/obj/build/x86_64-unknown-linux-gnu/native/rust-test-helpers" "--docck-python" "/usr/bin/python2.7" "--lldb-python" "/usr/bin/python2.7" "--gdb" "/usr/bin/gdb" "--quiet" "--llvm-version" "3.9.1\n" "--system-llvm" "--cc" "" "--cxx" "" "--cflags" "" "--llvm-components" "" "--llvm-cxxflags" "" "--adb-path" "adb" "--adb-test-dir" "/data/tmp/work" "--android-cross-path" "" "--color" "always"
[01:01:55] expected success, got: exit code: 101
[01:01:55]
[01:01:55]
[01:01:55] failed to run: /checkout/obj/build/bootstrap/debug/bootstrap test
[01:01:55] Build completed unsuccessfully in 0:17:38
[01:01:55] Makefile:58: recipe for target 'check' failed
[01:01:55] make: *** [check] Error 1
---
$ ls -lat $HOME/Library/Logs/DiagnosticReports/
ls: cannot access /home/travis/Library/Logs/DiagnosticReports/: No such file or directory
travis_time:end:1e8057a7:start=1523464270820755611,finish=1523464270838160439,duration=17404828
travis_fold:end:after_failure.2
travis_fold:start:after_failure.3
travis_time:start:1082a680
$ find $HOME/Library/Logs/DiagnosticReports -type f -name '*.crash' -not -name '*.stage2-*.crash' -not -name 'com.apple.CoreSimulator.CoreSimulatorService-*.crash' -exec printf travis_fold":start:crashlog\n\033[31;1m%s\033[0m\n" {} \; -exec head -750 {} \; -exec echo travis_fold":"end:crashlog \; || true
find: `/home/travis/Library/Logs/DiagnosticReports': No such file or directory
travis_time:end:1082a680:start=1523464270844787522,finish=1523464270851898892,duration=7111370
travis_fold:end:after_failure.3
travis_fold:start:after_failure.4
travis_time:start:053ad3a6
$ dmesg | grep -i kill
[   10.585580] init: failsafe main process (1093) killed by TERM signal
```

</details><p></p>

[I'm a bot](https://github.com/rust-ops/rust-log-analyzer)! I can only do what humans tell me to, so if this was not helpful or you have suggestions for improvements, please ping or otherwise contact **`@TimNN`**. ([Feature Requests](https://github.com/rust-ops/rust-log-analyzer/issues?q=is%3Aopen+is%3Aissue+label%3Afeature-request))

**Comment by cramertj** [comment]
@aturon is on vacation, so r? @eddyb

**Comment by TimNN** [comment]
Your PR [failed on Travis](https://travis-ci.org/rust-lang/rust/jobs/365228975) ([raw log](https://api.travis-ci.org/v3/job/365228975/log.txt)). Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.

<details><summary><i>Click to expand the log.</i></summary>

```plain
Resolving deltas: 100% (614152/614152), completed with 4880 local objects.
---
[00:00:47] configure: rust.quiet-tests     := True
---
[00:46:39] ..............................................................................i.....................
[00:46:45] .....................i..............................................................................
---
[00:47:29] i..........................................................................i........................
---
[00:48:26] .............................................i......................................................
---
[00:52:30] ..............................i.....................................................................
[00:52:45] ...............................................................i....................................
[00:53:01] ................................................i...................................................
[00:53:21] ....................................................................................................
[00:53:44] ....................................................................................................
[00:54:06] ....................................................................................................
[00:54:32] ....i...............................................................................................
[00:54:59] i............................................................................test [run-pass] run-pass/mir_heavy_promoted.rs has been running for over 60 seconds
[00:55:10] .......................
[00:55:42] ....................................................................................................
[00:56:18] ..................................................................ii................................
[00:57:04] .............................i...............................................test [run-pass] run-pass/saturating-float-casts.rs has been running for over 60 seconds
[00:57:13] .....i.ii..............
[00:57:56] ..........................................................................................iiiiiii...
---
[01:00:13] ...................i.....................................................F.F....ii.iii..............
[01:00:20] ....................................................................................................
[01:00:28] .........i..............................i...........................................................
[01:00:36] ....................................................................................................
[01:00:42] .....................i..............................................................................
[01:00:51] ....................................................................................................
[01:01:01] ....................................................................................................
[01:01:11] ....................................................................................................
[01:01:22] ....................................................................................................
[01:01:36] ....................................................................................................
[01:01:45] ..............i.....................................................................................
[01:01:54] ..................i..ii.............................................................................
[01:02:04] ....................................................................................................
[01:02:15] .......................F............................................................................
[01:02:24] .....................................................................................i..............
[01:02:35] ...............................i....................................................................
---
[01:03:10] error: /checkout/src/test/compile-fail/derives-span-PartialOrd-struct.rs:18: unexpected error: '18:5: 18:13: binary operation `>` cannot be applied to type `Error` [E0369]'
[01:03:10]
[01:03:10] error: /checkout/src/test/compile-fail/derives-span-PartialOrd-struct.rs:18: unexpected error: '18:5: 18:13: binary operation `>=` cannot be applied to type `Error` [E0369]'
[01:03:10]
[01:03:10] error: 2 unexpected errors found, 0 expected errors not found
[01:03:10] status: exit code: 101
[01:03:10] command: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc" "/checkout/src/test/compile-fail/derives-span-PartialOrd-struct.rs" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/compile-fail" "--target=x86_64-unknown-linux-gnu" "--error-format" "json" "-Zui-testing" "-C" "prefer-dynamic" "-o" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/compile-fail/derives-span-PartialOrd-struct.stage2-x86_64-unknown-linux-gnu" "-Crpath" "-O" "-Zmiri" "-Zunstable-options" "-Lnative=/checkout/obj/build/x86_64-unknown-linux-gnu/native/rust-test-helpers" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/compile-fail/derives-span-PartialOrd-struct.stage2-x86_64-unknown-linux-gnu.aux" "-A" "unused"
[01:03:10] unexpected errors (from JSON output): [
[01:03:10]     Error {
[01:03:10]         line_num: 18,
[01:03:10]         kind: Some(
[01:03:10]             Error
[01:03:10]         ),
[01:03:10]         msg: "18:5: 18:13: binary operation `>` cannot be applied to type `Error` [E0369]"
---
[01:03:10]         msg: "18:5: 18:13: binary operation `>=` cannot be applied to type `Error` [E0369]"
---
[01:03:10] error: /checkout/src/test/compile-fail/derives-span-PartialOrd-tuple-struct.rs:18: unexpected error: '18:5: 21:2: binary operation `>` cannot be applied to type `Error` [E0369]'
[01:03:10]
[01:03:10] error: /checkout/src/test/compile-fail/derives-span-PartialOrd-tuple-struct.rs:18: unexpected error: '18:5: 21:2: binary operation `>=` cannot be applied to type `Error` [E0369]'
[01:03:10]
[01:03:10] error: 2 unexpected errors found, 0 expected errors not found
[01:03:10] status: exit code: 101
[01:03:10] command: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc" "/checkout/src/test/compile-fail/derives-span-PartialOrd-tuple-struct.rs" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/compile-fail" "--target=x86_64-unknown-linux-gnu" "--error-format" "json" "-Zui-testing" "-C" "prefer-dynamic" "-o" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/compile-fail/derives-span-PartialOrd-tuple-struct.stage2-x86_64-unknown-linux-gnu" "-Crpath" "-O" "-Zmiri" "-Zunstable-options" "-Lnative=/checkout/obj/build/x86_64-unknown-linux-gnu/native/rust-test-helpers" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/compile-fail/derives-span-PartialOrd-tuple-struct.stage2-x86_64-unknown-linux-gnu.aux" "-A" "unused"
[01:03:10] unexpected errors (from JSON output): [
[01:03:10]     Error {
[01:03:10]         line_num: 18,
[01:03:10]         kind: Some(
[01:03:10]             Error
[01:03:10]         ),
[01:03:10]         msg: "18:5: 21:2: binary operation `>` cannot be applied to type `Error` [E0369]"
---
[01:03:10]         msg: "18:5: 21:2: binary operation `>=` cannot be applied to type `Error` [E0369]"
---
[01:03:10] error: /checkout/src/test/compile-fail/range_traits-1.rs:40: unexpected error: '40:5: 40:31: binary operation `<=` cannot be applied to type `std::ops::RangeToInclusive<usize>` [E0369]'
[01:03:10]
[01:03:10] error: /checkout/src/test/compile-fail/range_traits-1.rs:40: unexpected error: '40:5: 40:31: binary operation `>=` cannot be applied to type `std::ops::RangeToInclusive<usize>` [E0369]'
[01:03:10]
[01:03:10] error: 2 unexpected errors found, 0 expected errors not found
[01:03:10] status: exit code: 101
[01:03:10] command: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc" "/checkout/src/test/compile-fail/range_traits-1.rs" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/compile-fail" "--target=x86_64-unknown-linux-gnu" "--error-format" "json" "-Zui-testing" "-C" "prefer-dynamic" "-o" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/compile-fail/range_traits-1.stage2-x86_64-unknown-linux-gnu" "-Crpath" "-O" "-Zmiri" "-Zunstable-options" "-Lnative=/checkout/obj/build/x86_64-unknown-linux-gnu/native/rust-test-helpers" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/compile-fail/range_traits-1.stage2-x86_64-unknown-linux-gnu.aux" "-A" "unused"
[01:03:10] unexpected errors (from JSON output): [
[01:03:10]     Error {
[01:03:10]         line_num: 40,
[01:03:10]         kind: Some(
[01:03:10]             Error
[01:03:10]         ),
[01:03:10]         msg: "40:5: 40:31: binary operation `<=` cannot be applied to type `std::ops::RangeToInclusive<usize>` [E0369]"
---
[01:03:10]         msg: "40:5: 40:31: binary operation `>=` cannot be applied to type `std::ops::RangeToInclusive<usize>` [E0369]"
[01:03:10]     }
[01:03:10] ]
[01:03:10]
[01:03:10] thread '[compile-fail] compile-fail/range_traits-1.rs' panicked at 'explicit panic', tools/compiletest/src/runtest.rs:1254:13
---
[01:03:10] command did not execute successfully: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-tools-bin/compiletest" "--compile-lib-path" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/lib" "--run-lib-path" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/lib/rustlib/x86_64-unknown-linux-gnu/lib" "--rustc-path" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc" "--src-base" "/checkout/src/test/compile-fail" "--build-base" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/compile-fail" "--stage-id" "stage2-x86_64-unknown-linux-gnu" "--mode" "compile-fail" "--target" "x86_64-unknown-linux-gnu" "--host" "x86_64-unknown-linux-gnu" "--llvm-filecheck" "/usr/lib/llvm-3.9/bin/FileCheck" "--host-rustcflags" "-Crpath -O -Zmiri -Zunstable-options " "--target-rustcflags" "-Crpath -O -Zmiri -Zunstable-options  -Lnative=/checkout/obj/build/x86_64-unknown-linux-gnu/native/rust-test-helpers" "--docck-python" "/usr/bin/python2.7" "--lldb-python" "/usr/bin/python2.7" "--gdb" "/usr/bin/gdb" "--quiet" "--llvm-version" "3.9.1\n" "--system-llvm" "--cc" "" "--cxx" "" "--cflags" "" "--llvm-components" "" "--llvm-cxxflags" "" "--adb-path" "adb" "--adb-test-dir" "/data/tmp/work" "--android-cross-path" "" "--color" "always"
[01:03:10] expected success, got: exit code: 101
[01:03:10]
[01:03:10]
[01:03:10] failed to run: /checkout/obj/build/bootstrap/debug/bootstrap test
[01:03:10] Build completed unsuccessfully in 0:17:47
[01:03:10] Makefile:58: recipe for target 'check' failed
[01:03:10] make: *** [check] Error 1
/build/bootstrap/debug/incremental/bootstrap-351vorei3hhuv/s-f00vd3ygp8-1q2ertq-30lh3aoqh35e1
110164 ./obj/build/x86_64-unknown-linux-gnu/stage0-tools/x86_64-unknown-linux-gnu
110160 ./obj/build/x86_64-unknown-linux-gnu/stage0-tools/x86_64-unknown-linux-gnu/release
106248 ./obj/build/x86_64-unknown-linux-gnu/stage0-tools/x86_64-unknown-linux-gnu/release/deps
102808 ./obj/build/x86_64-unknown-linux-gnu/stage0/lib/rustlib/x86_64-unknown-linux-gnu/codegen-backends
102472 ./obj/build/x86_64-unknown-linux-gnu/stage1-std/x86_64-unknown-linux-gnu/release/incremental/core-31lccp6wy7orz
102468 ./obj/build/x86_64-unknown-linux-gnu/stage1-std/x86_64-unknown-linux-gnu/release/incremental/core-31lccp6wy7orz/s-f00whrj2wz-1c7dqc2-3w56w3gn3qkpf
100716 ./obj/build/bootstrap/debug/incremental/bootstrap-zki88qpb4pjm
100712 ./obj/build/bootstrap/debug/incremental/bootstrap-zki88qpb4pjm/s-f00wk96w1w-1sw8cx8-ic3jtn8ifj03
---
78272 ./obj/build/x86_64-unknown-linux-gnu/e:start:24fd9903
$ find $HOME/Library/Logs/DiagnosticReports -type f -name '*.crash' -not -name '*.stage2-*.crash' -not -name 'com.apple.CoreSimulator.CoreSimulatorService-*.crash' -exec printf travis_fold":start:crashlog\n\033[31;1m%s\033[0m\n" {} \; -exec head -750 {} \; -exec echo travis_fold":"end:crashlog \; || true
find: `/home/travis/Library/Logs/DiagnosticReports': No such file or directory
travis_time:end:24fd9903:start=1523471286283624871,finish=1523471286289909350,duration=6284479
travis_fold:end:after_failure.3
travis_fold:start:after_failure.4
travis_time:start:10bf7970
$ dmesg | grep -i kill
[   10.891758] init: failsafe main process (1093) killed by TERM signal
```

</details><p></p>

[I'm a bot](https://github.com/rust-ops/rust-log-analyzer)! I can only do what humans tell me to, so if this was not helpful or you have suggestions for improvements, please ping or otherwise contact **`@TimNN`**. ([Feature Requests](https://github.com/rust-ops/rust-log-analyzer/issues?q=is%3Aopen+is%3Aissue+label%3Afeature-request))

**Comment by TimNN** [comment]
Your PR [failed on Travis](https://travis-ci.org/rust-lang/rust/jobs/365255379) ([raw log](https://api.travis-ci.org/v3/job/365255379/log.txt)). Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.

<details><summary><i>Click to expand the log.</i></summary>

```plain
Resolving deltas: 100% (613723/613723), completed with 4906 local objects.
---
[00:00:43] configure: rust.quiet-tests     := True
---
[00:42:11] ..............................................................................i.....................
[00:42:17] .....................i..............................................................................
---
[00:42:58] i..........................................................................i........................
---
[00:43:52] .............................................i......................................................
---
[00:47:37] ..............................i.....................................................................
[00:47:51] ...............................................................i....................................
[00:48:06] ................................................i...................................................
[00:48:25] ....................................................................................................
[00:48:47] ....................................................................................................
[00:49:07] ....................................................................................................
[00:49:31] ....i...............................................................................................
[00:50:00] i.......................................................................................test [run-pass] run-pass/mir_heavy_promoted.rs has been running for over 60 seconds
[00:50:06] ............
[00:50:36] ....................................................................................................
[00:51:09] ..................................................................ii................................
[00:51:57] .............................i....................................................i.ii........test [run-pass] run-pass/saturating-float-casts.rs has been running for over 60 seconds
[00:51:59] ......
[00:52:38] ..........................................................................................iiiiiii...
---
[00:54:48] ...................i............................................................ii.iii..............
[00:54:55] ....................................................................................................
[00:55:02] .........i..............................i...........................................................
[00:55:10] ....................................................................................................
[00:55:16] .....................i..............................................................................
[00:55:24] ....................................................................................................
[00:55:34] ....................................................................................................
[00:55:44] ....................................................................................................
[00:55:54] ....................................................................................................
[00:56:06] ....................................................................................................
[00:56:14] ..............i.....................................................................................
[00:56:23] ..................i..ii.............................................................................
[00:56:33] ....................................................................................................
[00:56:42] ......................F.............................................................................
[00:56:51] .....................................................................................i..............
[00:57:01] ...............................i....................................................................
---
[00:57:35] error: /checkout/src/test/compile-fail/range_traits-1.rs:40: unexpected error: '40:5: 40:31: binary operation `<=` cannot be applied to type `std::ops::RangeToInclusive<usize>` [E0369]'
[00:57:35]
[00:57:35] error: /checkout/src/test/compile-fail/range_traits-1.rs:40: unexpected error: '40:5: 40:31: binary operation `>=` cannot be applied to type `std::ops::RangeToInclusive<usize>` [E0369]'
[00:57:35]
[00:57:35] error: 2 unexpected errors found, 0 expected errors not found
[00:57:35] status: exit code: 101
[00:57:35] command: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc" "/checkout/src/test/compile-fail/range_traits-1.rs" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/compile-fail" "--target=x86_64-unknown-linux-gnu" "--error-format" "json" "-Zui-testing" "-C" "prefer-dynamic" "-o" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/compile-fail/range_traits-1.stage2-x86_64-unknown-linux-gnu" "-Crpath" "-O" "-Zmiri" "-Zunstable-options" "-Lnative=/checkout/obj/build/x86_64-unknown-linux-gnu/native/rust-test-helpers" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/compile-fail/range_traits-1.stage2-x86_64-unknown-linux-gnu.aux" "-A" "unused"
[00:57:35] unexpected errors (from JSON output): [
[00:57:35]     Error {
[00:57:35]         line_num: 40,
[00:57:35]         kind: Some(
[00:57:35]             Error
[00:57:35]         ),
[00:57:35]         msg: "40:5: 40:31: binary operation `<=` cannot be applied to type `std::ops::RangeToInclusive<usize>` [E0369]"
---
[00:57:35]         msg: "40:5: 40:31: binary operation `>=` cannot be applied to type `std::ops::RangeToInclusive<usize>` [E0369]"
[00:57:35]     }
[00:57:35] ]
[00:57:35]
[00:57:35] thread '[compile-fail] compile-fail/range_traits-1.rs' panicked at 'explicit panic', tools/compiletest/src/runtest.rs:1254:13
---
[00:57:35] command did not execute successfully: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-tools-bin/compiletest" "--compile-lib-path" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/lib" "--run-lib-path" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/lib/rustlib/x86_64-unknown-linux-gnu/lib" "--rustc-path" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc" "--src-base" "/checkout/src/test/compile-fail" "--build-base" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/compile-fail" "--stage-id" "stage2-x86_64-unknown-linux-gnu" "--mode" "compile-fail" "--target" "x86_64-unknown-linux-gnu" "--host" "x86_64-unknown-linux-gnu" "--llvm-filecheck" "/usr/lib/llvm-3.9/bin/FileCheck" "--host-rustcflags" "-Crpath -O -Zmiri -Zunstable-options " "--target-rustcflags" "-Crpath -O -Zmiri -Zunstable-options  -Lnative=/checkout/obj/build/x86_64-unknown-linux-gnu/native/rust-test-helpers" "--docck-python" "/usr/bin/python2.7" "--lldb-python" "/usr/bin/python2.7" "--gdb" "/usr/bin/gdb" "--quiet" "--llvm-version" "3.9.1\n" "--system-llvm" "--cc" "" "--cxx" "" "--cflags" "" "--llvm-components" "" "--llvm-cxxflags" "" "--adb-path" "adb" "--adb-test-dir" "/data/tmp/work" "--android-cross-path" "" "--color" "always"
[00:57:35] expected success, got: exit code: 101
[00:57:35]
[00:57:35]
[00:57:35] failed to run: /checkout/obj/build/bootstrap/debug/bootstrap test
[00:57:35] Build completed unsuccessfully in 0:16:35
[00:57:35] make: *** [check] Error 1
[00:57:35] Makefile:58: recipe for target 'check' failed
---
$ ls -lat $HOME/Library/Logs/DiagnosticReports/
ls: cannot access /home/travis/Library/Logs/DiagnosticReports/: No such file or directory
travis_time:end:0ffe701f:start=1523474785396328565,finish=1523474785416509653,duration=20181088
travis_fold:end:after_failure.2
travis_fold:start:after_failure.3
travis_time:start:19393ca0
$ find $HOME/Library/Logs/DiagnosticReports -type f -name '*.crash' -not -name '*.stage2-*.crash' -not -name 'com.apple.CoreSimulator.CoreSimulatorService-*.crash' -exec printf travis_fold":start:crashlog\n\033[31;1m%s\033[0m\n" {} \; -exec head -750 {} \; -exec echo travis_fold":"end:crashlog \; || true
find: `/home/travis/Library/Logs/DiagnosticReports': No such file or directory
travis_time:end:19393ca0:start=1523474785423049071,finish=1523474785430063389,duration=7014318
travis_fold:end:after_failure.3
travis_fold:start:after_failure.4
travis_time:start:182381a0
$ dmesg | grep -i kill
[   11.076014] init: failsafe main process (1093) killed by TERM signal
```

</details><p></p>

[I'm a bot](https://github.com/rust-ops/rust-log-analyzer)! I can only do what humans tell me to, so if this was not helpful or you have suggestions for improvements, please ping or otherwise contact **`@TimNN`**. ([Feature Requests](https://github.com/rust-ops/rust-log-analyzer/issues?q=is%3Aopen+is%3Aissue+label%3Afeature-request))

File: src/libsyntax_ext/deriving/cmp/partial_ord.rs [hunk 1]
```diff
@@ -214,14 +214,18 @@ fn cs_op(less: bool, equal: bool, cx: &mut ExtCtxt, span: Span, substr: &Substru
             _ => cx.span_bug(span, "not exactly 2 arguments in `derive(PartialOrd)`"),
         };
 
-        let cmp = cx.expr_binary(span, op, self_f.clone(), other_f.clone());
+        let strict_ineq = cx.expr_binary(span, op, self_f.clone(), other_f.clone());
 
-        let not_cmp = cx.expr_unary(span,
-                                    ast::UnOp::Not,
-                                    cx.expr_binary(span, op, other_f.clone(), self_f));
+        let deleg_cmp = if !equal {
```
Comment (Manishearth) [inline src/libsyntax_ext/deriving/cmp/partial_ord.rs]: Please update the comment above with the new generated code

File: src/libsyntax_ext/deriving/generic/mod.rs [hunk 2]
```diff
@@ -1691,26 +1734,58 @@ pub fn cs_fold<F>(use_foldl: bool,
...
+        StaticEnum(..) | StaticStruct(..) => {
+            cs_fold_static(cx, trait_span)
         }
-        StaticEnum(..) | StaticStruct(..) => cx.span_bug(trait_span, "static function in `derive`"),
     }
 }
 
+/// Special version of `cs_fold` that uses the result of a function call on the first field
+/// as the base case when is at least 1 field, and the usual base case when there are zero fields.
+pub fn cs_fold1<F, B>(use_foldl: bool,
```
Comment (Manishearth) [inline src/libsyntax_ext/deriving/generic/mod.rs]: This needs clearer documentation

File: src/libsyntax_ext/deriving/cmp/partial_eq.rs [hunk 3]
```diff
@@ -27,40 +27,70 @@ pub fn expand_deriving_partial_eq(cx: &mut ExtCtxt,
...
+                    (1, Some(o_f)) => o_f,
+                    _ => cx.span_bug(span, "not exactly 2 arguments in `derive(PartialEq)`"),
+                };
+
+                let eq = cx.expr_binary(span, BinOpKind::Ne, self_f, other_f.clone());
 
-            let eq = cx.expr_binary(span, BinOpKind::Ne, self_f, other_f.clone());
+                cx.expr_binary(span, BinOpKind::Or, subexpr, eq)
+            },
+            |cx, args| {
```
Comment (Manishearth) [inline src/libsyntax_ext/deriving/cmp/partial_eq.rs]: this and the previous closure can be factored out into a function

**Review by Manishearth — CHANGES_REQUESTED** [review]

**Comment by Manishearth** [comment]
Overall looks good, minor nits

File: src/libsyntax_ext/deriving/cmp/partial_eq.rs [hunk 4]
```diff
@@ -27,29 +27,25 @@ pub fn expand_deriving_partial_eq(cx: &mut ExtCtxt,
     // structures are equal if all fields are equal, and non equal, if
     // any fields are not equal or if the enum variants are different
     fn cs_eq(cx: &mut ExtCtxt, span: Span, substr: &Substructure) -> P<Expr> {
-        cs_fold1(true, // use foldl
-            |cx, span, subexpr, self_f, other_fs| {
-                let other_f = match (other_fs.len(), other_fs.get(0)) {
-                    (1, Some(o_f)) => o_f,
-                    _ => cx.span_bug(span, "not exactly 2 arguments in `derive(PartialEq)`"),
-                };
+        let eq = |cx: &mut ExtCtxt, span: Span, self_f: P<Expr>, other_fs: &[P<Expr>]| {
```
Comment (Manishearth) [inline src/libsyntax_ext/deriving/cmp/partial_eq.rs]: I meant splitting this out into a function such that it can be shared between the Eq and Neq code

Comment (varkor) [reply src/libsyntax_ext/deriving/cmp/partial_eq.rs]: Ahh... that's another good idea! 😅

**Review by Manishearth — APPROVED** [review]
