### PR TITLE
Fix cycle error with existential types

### LINKED ISSUE #61863: Trying to use same existential type for two functions cause cycle dependency
On a nightly rustup 1.18.3 (435397f48 2019-05-22)
Some code like this
```
#![feature(existential_type)]
pub trait T {
    fn bla() -> ();
}

pub struct S {
  v: u64
}

impl T for S {
    fn bla() -> () {}
}

existential type TE: T;
pub fn bla() -> TE {
    return S {v:1}
}

pub fn bla2() -> TE {
    bla()
}
```

cause error 

> Compiling playground v0.0.1 (/playground)
> error[E0391]: cycle detected when processing `TE`
>   --> src/lib.rs:14:1
>    |
> 14 | existential type TE: T;
>    | ^^^^^^^^^^^^^^^^^^^^^^^
>    |
> note: ...which requires processing `bla2`...
>   --> src/lib.rs:19:21
>    |
> 19 |   pub fn bla2() -> TE {
>    |  _____________________^
> 20 | |     bla()
> 21 | | }
>    | |_^
>    = note: ...which again requires processing `TE`, completing the cycle
> note: cycle used when collecting item types in top-level module
>   --> src/lib.rs:1:1
>    |
> 1  | / #![feature(existential_type)]
> 2  | | pub trait T {
> 3  | |     fn bla() -> ();
> 4  | | }
> ...  |
> 20 | |     bla()
> 21 | | }
>    | |_^
> 
> error: concrete type differs from previous defining existential type use
>   --> src/lib.rs:19:1
>    |
> 19 | / pub fn bla2() -> TE {
> 20 | |     bla()
> 21 | | }
>    | |_^ expected `S`, got `TE`
>    |
> note: previous use here
>   --> src/lib.rs:15:1
>    |
> 15 | / pub fn bla() -> TE {
> 16 | |     return S {v:1}
> 17 | | }
>    | |_^
> 
> error: aborting due to 2 previous errors

playground link: 
https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=71c724f92b074d0b6f355a6aaf8d3d1a

### PR DESCRIPTION
**Pull request by Aaron1011**
Fixes #61863

We now allow uses of `existential type`'s that aren't defining uses - that is, uses which don't constrain the underlying concrete type.

To make this work correctly, we also modify `eq_opaque_type_and_type` to not try to apply additional constraints to an opaque type. If we have code like this:

```rust
existential type Foo;
fn foo1() -> Foo { ... }
fn foo2() -> Foo { foo1() }
```

then `foo2` doesn't end up constraining `Foo`, which means that `foo2` will end up using the type `Foo` internally - that is, an actual `TyKind::Opaque`. We don't want to equate this to the underlying concrete type - we just need to enforce the basic equality constraint between the two types (here, the return type of `foo1` and the return type of `foo2`)

### CODE REVIEW

**Comment by Centril** [comment]
cc @rust-lang/lang

File: src/test/run-pass/existential_type_const.rs [hunk 1]
```diff
@@ -0,0 +1,17 @@
+#![feature(existential_type)]
+#![feature(impl_trait_in_bindings)]
```
Comment (Centril) [inline src/test/run-pass/existential_type_const.rs]: Why is `impl_trait_in_bindings` used here?

File: src/test/run-pass/existential_type_const.rs [hunk 2]
```diff
@@ -0,0 +1,17 @@
...
+//~^ WARN the feature `impl_trait_in_bindings` is incomplete and may cause the compiler to crash
+
+// Ensures that consts can constrain an existential type
```
Comment (Centril) [inline src/test/run-pass/existential_type_const.rs]:
```suggestion
// Ensures that `const` items can constrain an `existential type`.
```

File: src/test/run-pass/existential_type_const.rs [hunk 3]
```diff
@@ -0,0 +1,17 @@
+#![feature(existential_type)]
```
Comment (Centril) [inline src/test/run-pass/existential_type_const.rs]: Please move this to `ui/existential_types/` and use a `// check-pass` annotation since there are no dynamic semantics under test. The same should apply to the other new test as well.

File: src/librustc_mir/borrow_check/nll/type_check/mod.rs [hunk 4]
```diff
@@ -1253,17 +1253,38 @@ impl<'a, 'tcx> TypeChecker<'a, 'tcx> {
...
-                        output_ty, opaque_type_map, revealed_ty
+                         revealed_ty={:?} \
+                         revealed_ty_is_opaque={}",
+                        output_ty, opaque_type_map, revealed_ty, revealed_ty_is_opaque
                     );
                     obligations.add(infcx
                         .at(&ObligationCause::dummy(), param_env)
                         .eq(output_ty, revealed_ty)?);
 
+                    // This is 'true' when we're using an existential
```
Comment (Centril) [inline src/librustc_mir/borrow_check/nll/type_check/mod.rs]:
```suggestion
                    // This is `true` when we're using an existential
```

File: src/librustc_mir/borrow_check/nll/type_check/mod.rs [hunk 5]
```diff
@@ -1253,17 +1253,38 @@ impl<'a, 'tcx> TypeChecker<'a, 'tcx> {
...
+                    // type without 'revelaing' it. For example, code like this:
```
Comment (Centril) [inline src/librustc_mir/borrow_check/nll/type_check/mod.rs]:
```suggestion
                    // type without "revealing" it. For example, code like this:
```

File: src/librustc_mir/borrow_check/nll/type_check/mod.rs [hunk 6]
```diff
@@ -1253,17 +1253,38 @@ impl<'a, 'tcx> TypeChecker<'a, 'tcx> {
...
+                    //
+                    // existential type Foo: Debug;
+                    // fn foo1() -> Foo { ... }
+                    // fn foo2() -> Foo { foo1() }
+                    //
+                    // In 'foo2', we're not revealing the type of 'Foo' - we're
```
Comment (Centril) [inline src/librustc_mir/borrow_check/nll/type_check/mod.rs]:
```suggestion
                    // In `foo2`, we're not revealing the type of `Foo` - we're
```

File: src/librustc_mir/borrow_check/nll/type_check/mod.rs [hunk 7]
```diff
@@ -1253,17 +1253,38 @@ impl<'a, 'tcx> TypeChecker<'a, 'tcx> {
...
+                    // just treating it as the opaque type. All of the constraints
+                    // in our 'opaque_type_map' apply to the concrete type,
```
Comment (Centril) [inline src/librustc_mir/borrow_check/nll/type_check/mod.rs]:
```suggestion
                    // in our `opaque_type_map` apply to the concrete type,
```

**Comment by Aaron1011** [comment]
My initial solution didn't work properly when an existential type was used inside another type (e.g. `fn foo() -> (Foo, bool)` where `Foo` is an existential type). I've modified my fix to handle that properly, and added an additional test case.

File: src/librustc_mir/borrow_check/nll/type_check/mod.rs [hunk 8]
```diff
@@ -1253,17 +1253,38 @@ impl<'a, 'tcx> TypeChecker<'a, 'tcx> {
...
+                    // not to the opaque type itself. Therefore, it's enough
+                    // to simply equate the output and opque 'revealed_type',
```
Comment (Centril) [inline src/librustc_mir/borrow_check/nll/type_check/mod.rs]:
```suggestion
                    // to simply equate the output and opaque `revealed_type`,
```

File: src/librustc_mir/borrow_check/nll/type_check/mod.rs [hunk 9]
```diff
@@ -1253,17 +1253,38 @@ impl<'a, 'tcx> TypeChecker<'a, 'tcx> {
...
+                    // as we do above
```
Comment (Centril) [inline src/librustc_mir/borrow_check/nll/type_check/mod.rs]:
```suggestion
                    // as we do above.
```

File: src/librustc_typeck/check/writeback.rs [hunk 10]
```diff
@@ -576,36 +576,38 @@ impl<'cx, 'tcx> WritebackCx<'cx, 'tcx> {
...
-                        span_bug!(
-                            span,
-                            "visit_opaque_types tried to write \
-                            different types for the same existential type: {:?}, {:?}, {:?}, {:?}",
-                            def_id,
-                            definition_ty,
-                            opaque_defn,
-                            old,
-                        );
+                if !skip_add {
```
Comment (Centril) [inline src/librustc_typeck/check/writeback.rs]: Could use comments here?

**Comment by Centril** [comment]
Since you added a commit mid my review they are sorta outdated now but the basic idea isn't so you can "translate" the changes to the new location... ;)

File: src/test/run-pass/existential_type_const.rs (hunk 1 above)
Comment (Aaron1011) [reply src/test/run-pass/existential_type_const.rs]: `#![feature(existential_type)]` implicitly depends on `#![feature(impl_trait_in_bindings)]` to work properly - specifically, [this code](https://github.com/rust-lang/rust/blob/481068a707679257e2a738b40987246e0420e787/src/librustc_typeck/check/mod.rs#L856) needs to run, so that we properly visit all defining uses of an existential type. Should I add a comment explaining that?

Comment (Centril) [reply src/test/run-pass/existential_type_const.rs]: A comment would be helpful indeed. :)

**Comment by Aaron1011** [comment]
@Centril: I've addressed your comments

File: src/librustc_mir/borrow_check/nll/type_check/mod.rs [hunk 11]
```diff
@@ -1268,15 +1268,43 @@ impl<'a, 'tcx> TypeChecker<'a, 'tcx> {
                         let opaque_defn_ty = tcx.type_of(opaque_def_id);
                         let opaque_defn_ty = opaque_defn_ty.subst(tcx, opaque_decl.substs);
                         let opaque_defn_ty = renumber::renumber_regions(infcx, &opaque_defn_ty);
+                        let concrete_is_opaque = infcx
```
Comment (cramertj) [inline src/librustc_mir/borrow_check/nll/type_check/mod.rs]: I'm not sure if this is quite the right check, or at least it doesn't match the behavior specified by the RFC. In the RFC, it's expected that the following would compile:

```rust
existential type Foo: Debug;

fn foo() -> Foo {
    5u32
}

fn bar(cond: bool) -> Foo {
    if cond { foo() } else { 5u32 }
}
```

In this situation, the type of the variable returned by `foo` is an impl trait variable, but since the function is within the same module as the definition of the `existential type`, it can constrain the type further and itself become a defining use. The RFC says you can even do this:

```rust
existential type Foo: Debug;

fn foo() -> Foo {
    5u32
}

fn bar() -> Foo {
    let x: u32 = foo();
    x + 5
}
```

I realize this isn't at all what's implemented today, but it'd be good to talk about how the behavior being implemented here interacts with the desired behavior we want to end up with.

Comment (Aaron1011) [reply src/librustc_mir/borrow_check/nll/type_check/mod.rs]: I believe that this check is still compatible with implementing the full behavior specified in the RFC. This check occurs after we've attempted to instantiate the opaque type. If we're still left with an opaque type after instantiation, then there's nothing else we can do.

Once the rest of the RFC is implemented, this check should be hit only when the opaque type is being used outside the defining module.

Comment (cramertj) [reply src/librustc_mir/borrow_check/nll/type_check/mod.rs]: That makes sense-- thanks for the clarification!

**Review by nikomatsakis — COMMENTED** [review]
I've got a local build and I'm taking a look. I'm concerned that the current check doesn't feel sufficient -- i.e., just testing that you have *some* opaque type doesn't mean you have the *same* opaque type, for starters... and obviously this isn't as flexible as we might like, as @cramertj pointed out. I'd like to put a bit of thought into whether we can implement the "proper" semantics -- not necessarily in this PR, though. Once my build completes and I finish a few other things I'll do some testing and try to give a bit more detailed feedback! Thanks @Aaron1011 for looking into this!

**Comment by Aaron1011** [comment]
@nikomatsakis: We always check that the opaque type is equal to the 'output' type [here](https://github.com/rust-lang/rust/blob/8ba9b1019c6e6c514826c5466e84d93f665f975f/src/librustc_mir/borrow_check/nll/type_check/mod.rs#L1267-L1269). We only skip applying the obligations that should only apply to the underlying revealed type.

As I mentioned to @cramertj, I believe this change is fully forwards-compatible with 'revealing' opaque types under more circumstances (e.g. within the defining module). My checks runs during MIR typecheck - at this stage of compilation, any opauqe tyoe usages that have not been revelaed are never going to be reveled (i.e. usages outside the defining module). Future changes may affect under what circumstances my check is hit, but I believe that it's always correct to skip the 'revealed' obligations for an opaque type that we cannot reveal.

**Comment by Aaron1011** [comment]
@nikomatsakis: Are there any changes that you'd like me to make?

File: src/librustc_mir/borrow_check/nll/type_check/mod.rs [hunk 12]
```diff
@@ -1268,15 +1268,43 @@ impl<'a, 'tcx> TypeChecker<'a, 'tcx> {
...
+                        // the concrete type with the underlying defining type
+                        // of the existential type - this will always fail, since
+                        // the defining type of an existential type is always
+                        // some other type (e.g. not itself)
+                        // Essentially, none of the normal obligations apply here -
+                        // we're just passing around some unknown opaque type,
+                        // without actually looking at the underlying type it
+                        // gets 'revealed' into
+
+                        if !concrete_is_opaque {
```
Comment (oli-obk) [inline src/librustc_mir/borrow_check/nll/type_check/mod.rs]: if the concrete type is opaque, don't we need an additional check to figure out if the opaque types are equal? Essentially what I'm asking is whether

```rust
pub trait MyTrait {}

#[derive(Debug)]
pub struct MyStruct {
  v: u64
}

impl MyTrait for MyStruct {}

mod foo {
    pub fn bla() -> TE {
        return crate::MyStruct {v:1}
    }
    
    
    existential type TE: crate::MyTrait;
}

mod bar {
    pub fn bla2() -> TE2 {
        crate::foo::bla()
    }
    
    pub existential type TE2: crate::MyTrait;
}

pub fn bla2() -> bar::TE2 {
    crate::foo::bla()
}
```

still errors after your PR

Comment (Aaron1011) [reply src/librustc_mir/borrow_check/nll/type_check/mod.rs]: @oli-obk See my reply to @nikomatsakis above

Comment (oli-obk) [reply src/librustc_mir/borrow_check/nll/type_check/mod.rs]: The code you linked is to the master branch (or at least before your PR) right here. So we aren't always checking that as you wrote.

Comment (Aaron1011) [reply src/librustc_mir/borrow_check/nll/type_check/mod.rs]: Yes - that line is [unchanged]9https://github.com/Aaron1011/rust/blob/2f4196205336df8550a4bfb3045d3d1c350f02bf/src/librustc_mir/borrow_check/nll/type_check/mod.rs#L1263-L1265) in my PR - that is, we still equate the opaque types.

Comment (oli-obk) [reply src/librustc_mir/borrow_check/nll/type_check/mod.rs]: :man_facepalming: 	sorry, These two obligations looked so similar, I confused the two.
