### PR TITLE
slices: fix ZST slice iterators making up pointers; debug_assert alignment in from_raw_parts

### LINKED ISSUE #42789: Iterators over slices of ZST behave strange
The following test passes for slices over non-ZST-types, but fails for ZST:
```rust
fn slice_test<T>(x: &[T]) {
    let mut i = x.iter();
    i.next();
    let x1 = i.next().unwrap();
    let x2 = &x[1];
    let x3 = x.iter().nth(1).unwrap();
    assert_eq!(x1 as *const _, x2 as *const _);
    assert_eq!(x2 as *const _, x3 as *const _);
}

fn main() {
    slice_test(&[1,2,3]);
    slice_test(&[(),(),()]);
}
```
[Playpen](https://play.rust-lang.org/?gist=26734e16c654e5eafe2dcb4848e29d62&version=nightly&backtrace=0)

While pointers to ZSTs don't really matter as they will never be dereferenced, I think providing consistent addresses for *the same element* would still make sense.
Yet, `x2` turns out to be `0x55e742ee85dc`, no idea where that address is coming from. The LLVM IR contains some `undef`, but I am not sure if that always indicates a problem.

Generally, the iterator's treatment of ZST's seems a little fishy. Below <https://github.com/rust-lang/rust/blob/445077963c55297ef1e196a3525723090fe80b22/src/libcore/slice/mod.rs#L777>, the `get` methods defer to `.offset` to compute the address of an element of the slice. `offset` is only well-defined for in-bounds accesses, yet it is sued here on a dangling pointer-to-ZST, with some non-0 offset.

### PR DESCRIPTION
**Pull request by RalfJung**
This fixes the problem that we are fabricating pointers out of thin air. I also managed to share more code between the mutable and shared iterators, while reducing the amount of macros.

I am not sure how useful it really is to add a `debug_assert!` in libcore. Everybody gets a release version of that anyway, right? Is there at least a CI job that runs the test suite with a debug version?

Fixes #42789

### CODE REVIEW

File: src/libcore/slice/mod.rs [hunk 1]
```diff
@@ -581,7 +607,7 @@ impl<T> [T] {
     pub fn iter(&self) -> Iter<T> {
         unsafe {
             let p = if mem::size_of::<T>() == 0 {
-                1 as *const _
+                NonNull::dangling().as_ptr() as *const _
```
Comment (scottmcm) [inline src/libcore/slice/mod.rs]: This makes me think that [`Iter::ptr`](https://github.com/rust-lang/rust/blob/b3e7d70ce7730a929fd3d5094e8ad2eb71c3a399/src/libcore/slice/mod.rs#L2600) should be a `NonNull<T>` instead of a `*const T`...

**Comment by RalfJung** [comment]
I should add that -- given that ZST slices seem to have zero test coverage before my change -- I am somewhat worried I broke something somewhere...

File: src/libcore/slice/mod.rs (hunk 1 above)
Comment (RalfJung) [reply src/libcore/slice/mod.rs]: It could be. Same for `end`. (Though I have plans for #42789 that would need tweaking of `end` were to become a `NonNull`.)

Do you want me to change that in this PR?

Comment (scottmcm) [reply src/libcore/slice/mod.rs]: I have no strong feelings about it.  If it's easy and it's mostly lines that were changing anyway, might as well; if it's annoying or makes the PR a bunch longer, then probably not worth doing right now.  (`end` not being `NonNull` is also totally fine by me.)

File: src/libcore/slice/mod.rs [hunk 2]
```diff
@@ -80,7 +80,7 @@ macro_rules! slice_offset {
     ($ptr:expr, $by:expr) => {{
         let ptr = $ptr;
         if size_from_ptr(ptr) == 0 {
-            (ptr as *mut i8).wrapping_offset($by) as _
+            (ptr as *mut i8).wrapping_offset($by.wrapping_mul(align_from_ptr(ptr) as isize)) as _
```
Comment (scottmcm) [inline src/libcore/slice/mod.rs]: Is there enough address space to do this, given the capacities claimed by `RawVec`?  I can apparently make a `usize::MAX`-length `Vec` of a align-8 ZST: https://play.rust-lang.org/?gist=c0b3d266bfbd34448d97e00f1408c946&version=stable&mode=release&edition=2015

Should the following change to `!0 / mem::align_of::<T>()`?

https://github.com/rust-lang/rust/blob/2c1a715cbda1d6eba39625aca08f1f2ac7c0dcc8/src/liballoc/raw_vec.rs#L215-L221

File: src/libcore/slice/mod.rs (hunk 1 above)
Comment (RalfJung) [reply src/libcore/slice/mod.rs]: It's annoying because tons of code here does raw pointer operations, so there'd be a lot of `to_ptr` and `new_unchecked` and so on

File: src/libcore/slice/mod.rs (hunk 2 above)
Comment (RalfJung) [reply src/libcore/slice/mod.rs]: Ah, good point.

Is it enough to change that in `raw_vec` or are there other ways to create huge slices?

Comment (RalfJung) [reply src/libcore/slice/mod.rs]: Yes it does. In fact I am working on that next step already. I thought it would be easier for reviewers etc. to split this into two PRs, but if you prefer I can certainly finish that up and add it here (or make a new PR because there are going to be drastically more changes).

**Comment by RalfJung** [comment]
All right, I added "no longer make up pointers" to this PR. Instead of just putting the length into `end`, I put `ptr+len` into `end` so that `ptr == end` is uniformly the condition for the iterator being empty.

This is based on @bluss's work in <https://github.com/rust-lang/rust/pull/46223>. In that PR, quite a few benchmarks were done to make sure this does not regress performance. How would I run these benchmarks?

File: src/libcore/slice/mod.rs [hunk 3]
```diff
@@ -2405,8 +2421,21 @@ macro_rules! iterator {
...
             #[inline]
             fn nth(&mut self, n: usize) -> Option<$elem> {
-                // Call helper method. Can't put the definition here because mut versus const.
-                self.iter_nth(n)
+                if n >= self.len() {
+                    // This iterator is now empty.  The way we encode the length of a non-ZST
+                    // iterator, this works for both ZST and non-ZST.
+                    // For a ZST we would usually do `self.end = self.ptr`, but since
+                    // we will not give out an address any more after this there is no
+                    // way to observe the difference.
```
Comment (scottmcm) [inline src/libcore/slice/mod.rs]: Couldn't I still get an address from `.as_slice().as_ptr()`?

File: src/libcore/slice/mod.rs [hunk 4]
```diff
@@ -2364,14 +2328,66 @@ impl<'a, T> IntoIterator for &'a mut [T] {
...
+                unsafe { from_raw_parts(self.ptr, self.len()) }
+            }
+
+            // Helper function for moving the start of the iterator forwards by `offset` elements,
+            // returning the old start.
+            // Unsafe because the offset must be in-bounds or one-past-the-end.
+            #[inline(always)]
+            unsafe fn post_inc_start(&mut self, offset: isize) -> * $raw_mut T {
+                if mem::size_of::<T>() == 0 {
+                    self.end = (self.end as isize).wrapping_sub(offset) as * $raw_mut T;
```
Comment (scottmcm) [inline src/libcore/slice/mod.rs]: `wrapping_sub` looks like a typo in a method named `inc`?

Comment (rkruppe) [reply src/libcore/slice/mod.rs]: I thought so too at first, but no, for ZST slices the start pointer should not change as the iterator advances, and this wrapping_sub is decrementing *the length*. However, since it's apparently somewhat subtle, there should be a comment spelling this out.

Comment (RalfJung) [reply src/libcore/slice/mod.rs]: Yeah in fact I used `wrapping_add` at first and wondered why everything exploded. ;)

I'll add a comment.

File: src/libcore/slice/mod.rs (hunk 3 above)
Comment (RalfJung) [reply src/libcore/slice/mod.rs]: Hm... okay it is observable but only as a raw pointer, not as a reference. So there's no soundness problem.

I can still change it, if you prefer.

Comment (scottmcm) [reply src/libcore/slice/mod.rs]: Up to you; the comment tweak is probably fine since I'm not sure why anyone would be looking at the address of a post-iteration slice anyway.

**Comment by RalfJung** [comment]
I've not done benchmarking like it was done for https://github.com/rust-lang/rust/pull/46223 before (or any kind of benchmarking with Rust ever, really), so I'd seem some pointers for how to do that.

**Comment by Mark-Simulacrum** [comment]
Generally speaking you can probably write up some `#[bench]` tests and compare against last nightly if you don't want to rebuild. We can also run perf.rlo, but that's more opaque since any difference here is likely quite minor.

**Comment by RalfJung** [comment]
I don't have any experience coming up with bench tests, is there something I should be on the watch for?

I noticed there is some stuff in `libcore/benches/slice.rs`, but not much. That produces output like
```
test slice::binary_search_l1                               ... bench:          55 ns/iter (+/- 2)
test slice::binary_search_l1_with_dups                     ... bench:          44 ns/iter (+/- 1)
test slice::binary_search_l2                               ... bench:          74 ns/iter (+/- 3)
test slice::binary_search_l2_with_dups                     ... bench:          74 ns/iter (+/- 3)
test slice::binary_search_l3                               ... bench:         162 ns/iter (+/- 11)
test slice::binary_search_l3_with_dups                     ... bench:         160 ns/iter (+/- 11)
```
How do I get these tables with a "+/- %" column?

**Comment by alexcrichton** [comment]
@bors: try

Can't hurt at least to have a try build!

File: src/libcore/slice/mod.rs [hunk 5]
```diff
@@ -2405,8 +2422,21 @@ macro_rules! iterator {
...
             fn nth(&mut self, n: usize) -> Option<$elem> {
-                // Call helper method. Can't put the definition here because mut versus const.
-                self.iter_nth(n)
+                if n >= self.len() {
+                    // This iterator is now empty.  The way we encode the length of a non-ZST
+                    // iterator, this works for both ZST and non-ZST.
+                    // For a ZST we would usually do `self.end = self.ptr`, but since
+                    // we will not give out an reference any more after this there is no
+                    // way to observe the difference except for raw pointers.
+                    self.ptr = self.end;
```
Comment (alexcrichton) [inline src/libcore/slice/mod.rs]: Previously in `next` there's an `assume(!self.end.is_null())` but only if `T` has a nonzero size. That implies to me that if T is a ZST it's possible for `self.end` to be null (I think wraparound?). In this case, this is setting `self.ptr` to null, right? Wouldn't that break the in-memory representation of `Option<&[T]>` as well as the first `assume` above in the call to `next`?

File: src/libcore/slice/mod.rs [hunk 6]
```diff
@@ -611,17 +574,18 @@ impl<T> [T] {
     #[inline]
     pub fn iter_mut(&mut self) -> IterMut<T> {
         unsafe {
-            let p = if mem::size_of::<T>() == 0 {
-                1 as *mut _
+            let ptr = self.as_mut_ptr();
+            assume(!ptr.is_null());
+
+            let end = if mem::size_of::<T>() == 0 {
+                (ptr as usize).wrapping_add(self.len()) as *mut _
```
Comment (alexcrichton) [inline src/libcore/slice/mod.rs]: [Oh-so-long-ago](https://github.com/rust-lang/rust/pull/25434) the casting here between integers and pointers was found to inhibit optimizations when it comes to ZSTs, so would it be possible to use a similar strategy as that PR to avoid the pointer<->int conversions here?

**Comment by alexcrichton** [comment]
@rust-timer build 3e9fa0ba8d51c2a5fe7cf53be75b7e4bf1370bd4

**Comment by alexcrichton** [comment]
Oddly enough the perf run is sort of all over the place. For what should be a "no change intended" it's sort of odd to see one benchmark regress 10% and another improve 6%...

**Comment by Mark-Simulacrum** [comment]
Hm, that is rather unexpected -- perhaps it'd be helpful to compare the IR for a sample program? I'd expect little to no difference if I understood the PR correctly.

**Comment by RalfJung** [comment]
I wrote some benchmarks (and pushed them into this PR) before realizing that *liballoc* actually contains a bunch of slice benchmarks. So I ran both against the state with this PR, and the base commit this PR rests on (a80a610a4c30b6f5f60862afcb4588d03439f66c).

```
 name                                            control ns/iter        variable ns/iter        diff ns/iter   diff %  speedup 
 slice::binary_search_l1                         55                     55                                 0    0.00%   x 1.00 
 slice::binary_search_l1_with_dups               43                     51                                 8   18.60%   x 0.84 
 slice::binary_search_l2                         73                     73                                 0    0.00%   x 1.00 
 slice::binary_search_l2_with_dups               73                     74                                 1    1.37%   x 0.99 
 slice::binary_search_l3                         162                    169                                7    4.32%   x 0.96 
 slice::binary_search_l3_with_dups               161                    164                                3    1.86%   x 0.98 
 slice::concat                                   1,114                  1,120                              6    0.54%   x 0.99 
 slice::contains_last_element                    28                     28                                 0    0.00%   x 1.00 
 slice::ends_with_diff_one_element_at_beginning  2                      2                                  0    0.00%   x 1.00 
 slice::ends_with_same_vector                    0                      0                                  0     NaN%    x NaN 
 slice::ends_with_single_element                 0                      0                                  0     NaN%    x NaN 
 slice::iter_nth_usize                           948                    940                               -8   -0.84%   x 1.01 
 slice::iter_nth_zst                             719                    594                             -125  -17.39%   x 1.21 
 slice::iter_usize                               292                    292                                0    0.00%   x 1.00 
 slice::iter_zst                                 286                    385                               99   34.62%   x 0.74 
 slice::iterator                                 7                      7                                  0    0.00%   x 1.00 
 slice::join                                     1,218                  1,180                            -38   -3.12%   x 1.03 
 slice::mut_iterator                             8                      8                                  0    0.00%   x 1.00 
 slice::push                                     2                      2                                  0    0.00%   x 1.00 
 slice::random_inserts                           3,383                  3,431                             48    1.42%   x 0.99 
 slice::random_removes                           3,262                  3,310                             48    1.47%   x 0.99 
 slice::reverse_simd_f64x4                       31,368 (33428 MB/s)    34,479 (30411 MB/s)            3,111    9.92%   x 0.91 
 slice::reverse_u128                             30,879 (33957 MB/s)    30,486 (34395 MB/s)             -393   -1.27%   x 1.01 
 slice::reverse_u16                              85,969 (12197 MB/s)    86,840 (12074 MB/s)              871    1.01%   x 0.99 
 slice::reverse_u32                              84,347 (12431 MB/s)    85,098 (12321 MB/s)              751    0.89%   x 0.99 
 slice::reverse_u64                              47,860 (21909 MB/s)    48,253 (21730 MB/s)              393    0.82%   x 0.99 
 slice::reverse_u8                               52,618 (19928 MB/s)    52,066 (20139 MB/s)             -552   -1.05%   x 1.01 
 slice::reverse_u8x3                             206,757 (5071 MB/s)    215,208 (4872 MB/s)            8,451    4.09%   x 0.96 
 slice::rotate_huge_by1                          5,354,006 (7833 MB/s)  6,628,860 (6327 MB/s)      1,274,854   23.81%   x 0.81 
 slice::rotate_huge_by1234577_big                9,123,162 (4597 MB/s)  9,521,004 (4405 MB/s)        397,842    4.36%   x 0.96 
 slice::rotate_huge_by1234577_bytes              8,817,380 (4756 MB/s)  11,642,391 (3602 MB/s)     2,825,011   32.04%   x 0.76 
 slice::rotate_huge_by1234577_strings            9,354,997 (4483 MB/s)  10,555,414 (3973 MB/s)     1,200,417   12.83%   x 0.89 
 slice::rotate_huge_by1234577_u64                8,662,283 (4842 MB/s)  9,364,781 (4478 MB/s)        702,498    8.11%   x 0.92 
 slice::rotate_huge_by9199_big                   5,292,371 (7925 MB/s)  6,695,713 (6264 MB/s)      1,403,342   26.52%   x 0.79 
 slice::rotate_huge_by9199_bytes                 5,302,024 (7910 MB/s)  6,362,843 (6591 MB/s)      1,060,819   20.01%   x 0.83 
 slice::rotate_huge_by9199_strings               5,282,433 (7940 MB/s)  5,565,033 (7536 MB/s)        282,600    5.35%   x 0.95 
 slice::rotate_huge_by9199_u64                   5,439,123 (7711 MB/s)  5,337,006 (7858 MB/s)       -102,117   -1.88%   x 1.02 
 slice::rotate_huge_half                         5,908,147 (7099 MB/s)  5,312,889 (7894 MB/s)       -595,258  -10.08%   x 1.11 
 slice::rotate_huge_half_plus_one                8,336,232 (5031 MB/s)  7,743,591 (5416 MB/s)       -592,641   -7.11%   x 1.08 
 slice::rotate_medium_by1                        1,125 (65123 MB/s)     1,405 (52145 MB/s)               280   24.89%   x 0.80 
 slice::rotate_medium_by727_bytes                3,270 (22404 MB/s)     3,506 (20896 MB/s)               236    7.22%   x 0.93 
 slice::rotate_medium_by727_strings              3,226 (22705 MB/s)     3,322 (22049 MB/s)                96    2.98%   x 0.97 
 slice::rotate_medium_by727_u64                  3,201 (22887 MB/s)     3,278 (22350 MB/s)                77    2.41%   x 0.98 
 slice::rotate_medium_half                       2,231 (32839 MB/s)     2,279 (32147 MB/s)                48    2.15%   x 0.98 
 slice::rotate_medium_half_plus_one              2,380 (30783 MB/s)     2,367 (30952 MB/s)               -13   -0.55%   x 1.01 
 slice::rotate_tiny_by1                          17 (7529 MB/s)         17 (7529 MB/s)                     0    0.00%   x 1.00 
 slice::rotate_tiny_half                         16 (8000 MB/s)         17 (7529 MB/s)                     1    6.25%   x 0.94 
 slice::rotate_tiny_half_plus_one                17 (7529 MB/s)         18 (7111 MB/s)                     1    5.88%   x 0.94 
 slice::sort_by_cached_key_lexicographic         2,422,180 (33 MB/s)    2,626,632 (30 MB/s)          204,452    8.44%   x 0.92 
 slice::sort_by_key_lexicographic                16,280,240 (4 MB/s)    16,811,305 (4 MB/s)          531,065    3.26%   x 0.97 
 slice::sort_large_ascending                     6,036 (13253 MB/s)     7,437 (10757 MB/s)             1,401   23.21%   x 0.81 
 slice::sort_large_big                           882,470 (1450 MB/s)    897,715 (1425 MB/s)           15,245    1.73%   x 0.98 
 slice::sort_large_descending                    9,649 (8291 MB/s)      9,704 (8244 MB/s)                 55    0.57%   x 0.99 
 slice::sort_large_expensive                     20,612,173 (3 MB/s)    20,852,778 (3 MB/s)          240,605    1.17%   x 0.99 
 slice::sort_large_mostly_ascending              139,018 (575 MB/s)     131,333 (609 MB/s)            -7,685   -5.53%   x 1.06 
 slice::sort_large_mostly_descending             144,625 (553 MB/s)     135,915 (588 MB/s)            -8,710   -6.02%   x 1.06 
 slice::sort_large_random                        522,945 (152 MB/s)     581,100 (137 MB/s)            58,155   11.12%   x 0.90 
 slice::sort_large_strings                       1,639,057 (97 MB/s)    1,751,978 (91 MB/s)          112,921    6.89%   x 0.94 
 slice::sort_medium_random                       748 (1069 MB/s)        696 (1149 MB/s)                  -52   -6.95%   x 1.07 
 slice::sort_small_ascending                     28 (2857 MB/s)         30 (2666 MB/s)                     2    7.14%   x 0.93 
 slice::sort_small_big                           104 (12307 MB/s)       111 (11531 MB/s)                   7    6.73%   x 0.94 
 slice::sort_small_descending                    46 (1739 MB/s)         57 (1403 MB/s)                    11   23.91%   x 0.81 
 slice::sort_small_random                        34 (2352 MB/s)         35 (2285 MB/s)                     1    2.94%   x 0.97 
 slice::sort_unstable_by_key_lexicographic       17,735,897 (4 MB/s)    18,901,218 (4 MB/s)        1,165,321    6.57%   x 0.94 
 slice::sort_unstable_large_ascending            5,516 (14503 MB/s)     6,203 (12896 MB/s)               687   12.45%   x 0.89 
 slice::sort_unstable_large_big                  643,272 (1989 MB/s)    669,096 (1913 MB/s)           25,824    4.01%   x 0.96 
 slice::sort_unstable_large_descending           8,689 (9207 MB/s)      10,415 (7681 MB/s)             1,726   19.86%   x 0.83 
 slice::sort_unstable_large_expensive            14,603,530 (5 MB/s)    15,734,764 (5 MB/s)        1,131,234    7.75%   x 0.93 
 slice::sort_unstable_large_mostly_ascending     66,480 (1203 MB/s)     72,032 (1110 MB/s)             5,552    8.35%   x 0.92 
 slice::sort_unstable_large_mostly_descending    72,947 (1096 MB/s)     78,420 (1020 MB/s)             5,473    7.50%   x 0.93 
 slice::sort_unstable_large_random               210,033 (380 MB/s)     233,715 (342 MB/s)            23,682   11.28%   x 0.90 
 slice::sort_unstable_large_strings              1,354,090 (118 MB/s)   1,391,308 (114 MB/s)          37,218    2.75%   x 0.97 
 slice::sort_unstable_medium_random              595 (1344 MB/s)        597 (1340 MB/s)                    2    0.34%   x 1.00 
 slice::sort_unstable_small_ascending            26 (3076 MB/s)         29 (2758 MB/s)                     3   11.54%   x 0.90 
 slice::sort_unstable_small_big                  87 (14712 MB/s)        95 (13473 MB/s)                    8    9.20%   x 0.92 
 slice::sort_unstable_small_descending           48 (1666 MB/s)         50 (1600 MB/s)                     2    4.17%   x 0.96 
 slice::sort_unstable_small_random               29 (2758 MB/s)         32 (2500 MB/s)                     3   10.34%   x 0.91 
 slice::starts_with_diff_one_element_at_end      7                      7                                  0    0.00%   x 1.00 
 slice::starts_with_same_vector                  0                      0                                  0     NaN%    x NaN 
 slice::starts_with_single_element               0                      0                                  0     NaN%    x NaN 
 slice::zero_1kb_from_elem                       54                     60                                 6   11.11%   x 0.90 
 slice::zero_1kb_loop_set                        0                      0                                  0     NaN%    x NaN 
 slice::zero_1kb_mut_iter                        20                     27                                 7   35.00%   x 0.74 
 slice::zero_1kb_set_memory                      20                     27                                 7   35.00%   x 0.74 
 str::split_slice                                108                    115                                7    6.48%   x 0.94 
 vec::bench_from_slice_0000                      16                     16                                 0    0.00%   x 1.00 
 vec::bench_from_slice_0010                      40 (250 MB/s)          41 (243 MB/s)                      1    2.50%   x 0.98 
 vec::bench_from_slice_0100                      82 (1219 MB/s)         94 (1063 MB/s)                    12   14.63%   x 0.87 
 vec::bench_from_slice_1000                      593 (1686 MB/s)        652 (1533 MB/s)                   59    9.95%   x 0.91
```

**Comment by RalfJung** [comment]
> For what should be a "no change intended" it's sort of odd to see one benchmark regress 10% and another improve 6%...

Do we have data how much noise there is when we ask perfbot to just compare twice the same thing?

**Comment by alexcrichton** [comment]
The comparison URL above is comparing instructions executed as opposed to wall time which is generally *far* more stable than wall time, so in that sense the expected noise is very little. Now executing 6% instructions doesn't really mean much with respect to the amount of wall time passing. The wall time of the 10% instruction regression though regressed 12%, which is likely a significant data point

File: src/libcore/slice/mod.rs (hunk 6 above)
Comment (RalfJung) [reply src/libcore/slice/mod.rs]: I just tried that, and it makes the tests fail...?!?

File: src/libcore/slice/mod.rs (hunk 5 above)
Comment (RalfJung) [reply src/libcore/slice/mod.rs]: Oh good point, I don't think we can rule that out.

I guess I'll hope for the optimizer to remove the conditional here as well, then. :)

**Comment by RalfJung** [comment]
With the two nits fixed, I now get (for the alloc test suite):
```
 name                                            control2 ns/iter       variable2 ns/iter       diff ns/iter  diff %  speedup 
 slice::concat                                   1,114                  1,191                             77   6.91%   x 0.94 
 slice::contains_last_element                    28                     30                                 2   7.14%   x 0.93 
 slice::ends_with_diff_one_element_at_beginning  2                      2                                  0   0.00%   x 1.00 
 slice::ends_with_same_vector                    0                      0                                  0    NaN%    x NaN 
 slice::ends_with_single_element                 0                      0                                  0    NaN%    x NaN 
 slice::iterator                                 7                      7                                  0   0.00%   x 1.00 
 slice::join                                     1,218                  1,171                            -47  -3.86%   x 1.04 
 slice::mut_iterator                             8                      8                                  0   0.00%   x 1.00 
 slice::push                                     2                      2                                  0   0.00%   x 1.00 
 slice::random_inserts                           3,383                  3,616                            233   6.89%   x 0.94 
 slice::random_removes                           3,262                  3,321                             59   1.81%   x 0.98 
 slice::reverse_simd_f64x4                       31,368 (33428 MB/s)    32,043 (32723 MB/s)              675   2.15%   x 0.98 
 slice::reverse_u128                             30,879 (33957 MB/s)    30,533 (34342 MB/s)             -346  -1.12%   x 1.01 
 slice::reverse_u16                              85,969 (12197 MB/s)    86,437 (12131 MB/s)              468   0.54%   x 0.99 
 slice::reverse_u32                              84,347 (12431 MB/s)    83,742 (12521 MB/s)             -605  -0.72%   x 1.01 
 slice::reverse_u64                              47,860 (21909 MB/s)    49,457 (21201 MB/s)            1,597   3.34%   x 0.97 
 slice::reverse_u8                               52,618 (19928 MB/s)    60,732 (17265 MB/s)            8,114  15.42%   x 0.87 
 slice::reverse_u8x3                             206,757 (5071 MB/s)    210,920 (4971 MB/s)            4,163   2.01%   x 0.98 
 slice::rotate_huge_by1                          5,354,006 (7833 MB/s)  5,199,106 (8067 MB/s)       -154,900  -2.89%   x 1.03 
 slice::rotate_huge_by1234577_big                9,123,162 (4597 MB/s)  8,641,313 (4853 MB/s)       -481,849  -5.28%   x 1.06 
 slice::rotate_huge_by1234577_bytes              8,817,380 (4756 MB/s)  8,724,509 (4807 MB/s)        -92,871  -1.05%   x 1.01 
 slice::rotate_huge_by1234577_strings            9,354,997 (4483 MB/s)  8,792,301 (4770 MB/s)       -562,696  -6.01%   x 1.06 
 slice::rotate_huge_by1234577_u64                8,662,283 (4842 MB/s)  13,311,606 (3150 MB/s)     4,649,323  53.67%   x 0.65 
 slice::rotate_huge_by9199_big                   5,292,371 (7925 MB/s)  5,440,271 (7709 MB/s)        147,900   2.79%   x 0.97 
 slice::rotate_huge_by9199_bytes                 5,302,024 (7910 MB/s)  5,274,796 (7951 MB/s)        -27,228  -0.51%   x 1.01 
 slice::rotate_huge_by9199_strings               5,282,433 (7940 MB/s)  5,281,289 (7941 MB/s)         -1,144  -0.02%   x 1.00 
 slice::rotate_huge_by9199_u64                   5,439,123 (7711 MB/s)  5,251,565 (7986 MB/s)       -187,558  -3.45%   x 1.04 
 slice::rotate_huge_half                         5,908,147 (7099 MB/s)  5,378,122 (7798 MB/s)       -530,025  -8.97%   x 1.10 
 slice::rotate_huge_half_plus_one                8,336,232 (5031 MB/s)  7,992,677 (5247 MB/s)       -343,555  -4.12%   x 1.04 
 slice::rotate_medium_by1                        1,125 (65123 MB/s)     1,321 (55461 MB/s)               196  17.42%   x 0.85 
 slice::rotate_medium_by727_bytes                3,270 (22404 MB/s)     3,250 (22542 MB/s)               -20  -0.61%   x 1.01 
 slice::rotate_medium_by727_strings              3,226 (22705 MB/s)     3,349 (21871 MB/s)               123   3.81%   x 0.96 
 slice::rotate_medium_by727_u64                  3,201 (22887 MB/s)     3,308 (22147 MB/s)               107   3.34%   x 0.97 
 slice::rotate_medium_half                       2,231 (32839 MB/s)     2,226 (32912 MB/s)                -5  -0.22%   x 1.00 
 slice::rotate_medium_half_plus_one              2,380 (30783 MB/s)     2,406 (30450 MB/s)                26   1.09%   x 0.99 
 slice::rotate_tiny_by1                          17 (7529 MB/s)         17 (7529 MB/s)                     0   0.00%   x 1.00 
 slice::rotate_tiny_half                         16 (8000 MB/s)         16 (8000 MB/s)                     0   0.00%   x 1.00 
 slice::rotate_tiny_half_plus_one                17 (7529 MB/s)         17 (7529 MB/s)                     0   0.00%   x 1.00 
 slice::sort_by_cached_key_lexicographic         2,422,180 (33 MB/s)    2,430,887 (32 MB/s)            8,707   0.36%   x 1.00 
 slice::sort_by_key_lexicographic                16,280,240 (4 MB/s)    15,702,589 (5 MB/s)         -577,651  -3.55%   x 1.04 
 slice::sort_large_ascending                     6,036 (13253 MB/s)     7,546 (10601 MB/s)             1,510  25.02%   x 0.80 
 slice::sort_large_big                           882,470 (1450 MB/s)    867,494 (1475 MB/s)          -14,976  -1.70%   x 1.02 
 slice::sort_large_descending                    9,649 (8291 MB/s)      9,522 (8401 MB/s)               -127  -1.32%   x 1.01 
 slice::sort_large_expensive                     20,612,173 (3 MB/s)    20,447,440 (3 MB/s)         -164,733  -0.80%   x 1.01 
 slice::sort_large_mostly_ascending              139,018 (575 MB/s)     129,340 (618 MB/s)            -9,678  -6.96%   x 1.07 
 slice::sort_large_mostly_descending             144,625 (553 MB/s)     141,640 (564 MB/s)            -2,985  -2.06%   x 1.02 
 slice::sort_large_random                        522,945 (152 MB/s)     511,354 (156 MB/s)           -11,591  -2.22%   x 1.02 
 slice::sort_large_strings                       1,639,057 (97 MB/s)    1,611,141 (99 MB/s)          -27,916  -1.70%   x 1.02 
 slice::sort_medium_random                       748 (1069 MB/s)        686 (1166 MB/s)                  -62  -8.29%   x 1.09 
 slice::sort_small_ascending                     28 (2857 MB/s)         27 (2962 MB/s)                    -1  -3.57%   x 1.04 
 slice::sort_small_big                           104 (12307 MB/s)       103 (12427 MB/s)                  -1  -0.96%   x 1.01 
 slice::sort_small_descending                    46 (1739 MB/s)         51 (1568 MB/s)                     5  10.87%   x 0.90 
 slice::sort_small_random                        34 (2352 MB/s)         32 (2500 MB/s)                    -2  -5.88%   x 1.06 
 slice::sort_unstable_by_key_lexicographic       17,735,897 (4 MB/s)    17,216,278 (4 MB/s)         -519,619  -2.93%   x 1.03 
 slice::sort_unstable_large_ascending            5,516 (14503 MB/s)     5,555 (14401 MB/s)                39   0.71%   x 0.99 
 slice::sort_unstable_large_big                  643,272 (1989 MB/s)    634,969 (2015 MB/s)           -8,303  -1.29%   x 1.01 
 slice::sort_unstable_large_descending           8,689 (9207 MB/s)      8,755 (9137 MB/s)                 66   0.76%   x 0.99 
 slice::sort_unstable_large_expensive            14,603,530 (5 MB/s)    14,462,198 (5 MB/s)         -141,332  -0.97%   x 1.01 
 slice::sort_unstable_large_mostly_ascending     66,480 (1203 MB/s)     66,717 (1199 MB/s)               237   0.36%   x 1.00 
 slice::sort_unstable_large_mostly_descending    72,947 (1096 MB/s)     70,074 (1141 MB/s)            -2,873  -3.94%   x 1.04 
 slice::sort_unstable_large_random               210,033 (380 MB/s)     215,013 (372 MB/s)             4,980   2.37%   x 0.98 
 slice::sort_unstable_large_strings              1,354,090 (118 MB/s)   1,322,046 (121 MB/s)         -32,044  -2.37%   x 1.02 
 slice::sort_unstable_medium_random              595 (1344 MB/s)        537 (1489 MB/s)                  -58  -9.75%   x 1.11 
 slice::sort_unstable_small_ascending            26 (3076 MB/s)         27 (2962 MB/s)                     1   3.85%   x 0.96 
 slice::sort_unstable_small_big                  87 (14712 MB/s)        93 (13763 MB/s)                    6   6.90%   x 0.94 
 slice::sort_unstable_small_descending           48 (1666 MB/s)         44 (1818 MB/s)                    -4  -8.33%   x 1.09 
 slice::sort_unstable_small_random               29 (2758 MB/s)         30 (2666 MB/s)                     1   3.45%   x 0.97 
 slice::starts_with_diff_one_element_at_end      7                      7                                  0   0.00%   x 1.00 
 slice::starts_with_same_vector                  0                      0                                  0    NaN%    x NaN 
 slice::starts_with_single_element               0                      0                                  0    NaN%    x NaN 
 slice::zero_1kb_from_elem                       54                     51                                -3  -5.56%   x 1.06 
 slice::zero_1kb_loop_set                        0                      0                                  0    NaN%    x NaN 
 slice::zero_1kb_mut_iter                        20                     19                                -1  -5.00%   x 1.05 
 slice::zero_1kb_set_memory                      20                     19                                -1  -5.00%   x 1.05 
 str::split_slice                                108                    109                                1   0.93%   x 0.99 
 vec::bench_from_slice_0000                      16                     15                                -1  -6.25%   x 1.07 
 vec::bench_from_slice_0010                      40 (250 MB/s)          40 (250 MB/s)                      0   0.00%   x 1.00 
 vec::bench_from_slice_0100                      82 (1219 MB/s)         84 (1190 MB/s)                     2   2.44%   x 0.98 
 vec::bench_from_slice_1000                      593 (1686 MB/s)        638 (1567 MB/s)                   45   7.59%   x 0.93 
```

**Comment by RalfJung** [comment]
> perhaps it'd be helpful to compare the IR for a sample program? I'd expect little to no difference if I understood the PR correctly.

Certainly no difference for the non-ZST case.
I can try to obtain some IR with old and new libcore, but I expect the result to be large and (as far as I am concerned) entirely unreadable.^^

**Comment by RalfJung** [comment]
Also, I don't trust these numbers. The biggest slowdown in the second measurement is `rotate_huge_by1234577_u64` with >50%. However, that only had 8% slowdown in the first measurement -- and looking at the code, it doesn't even involve iterators!

Maybe there is something one has to do to this machine to get good numbers, but I don't feel like my numbers mean anything.

**Comment by alexcrichton** [comment]
@bors: try

well, we can always try perf again!

**Comment by alexcrichton** [comment]
@rust-timer build 6ed20673c3cd10f0eef17895295188d43ecdb5ca

**Comment by RalfJung** [comment]
I assume that doesn't do anything with ZST? A simple iterator loops has the same IR on nightly and my PR, but when `nth` is involved the IR changed. However, `inflate` does not seem to use `nth`.

IR generated with `--emit llvm-ir -O`. Source:
```rust
pub fn nth(slice: &mut [u32], f: fn(u32)) {
    let mut it = slice.iter();
    for _i in 0..slice.len() {
        f(*it.nth(0).unwrap());
    }
}
```
On nightly:
```
; sample::nth
; Function Attrs: uwtable
define void @_ZN6sample3nth17h5c90215fc3e9ef80E([0 x i32]* noalias nonnull %slice.0, i64 %slice.1, void (i32)* nocapture nonnull %f) unnamed_addr #0 personality i32 (i32, i32, i64, %"unwind::libunwind::_Unwind_Exception"*, %"unwind::libunwind::_Unwind_Context"*)* @rust_eh_personality {
start:
  %0 = getelementptr inbounds [0 x i32], [0 x i32]* %slice.0, i64 0, i64 %slice.1
  %1 = ptrtoint i32* %0 to i64
  %2 = icmp eq i64 %slice.1, 0
  br i1 %2, label %bb6, label %bb8.preheader

bb8.preheader:                                    ; preds = %start
  %3 = ptrtoint [0 x i32]* %slice.0 to i64
  br label %bb8

bb6:                                              ; preds = %"_ZN38_$LT$core..option..Option$LT$T$GT$$GT$6unwrap17hb4e4d2d3d0768f5eE.exit", %start
  ret void

bb8:                                              ; preds = %bb8.preheader, %"_ZN38_$LT$core..option..Option$LT$T$GT$$GT$6unwrap17hb4e4d2d3d0768f5eE.exit"
  %it.sroa.0.025 = phi i64 [ %9, %"_ZN38_$LT$core..option..Option$LT$T$GT$$GT$6unwrap17hb4e4d2d3d0768f5eE.exit" ], [ %3, %bb8.preheader ]
  %iter.sroa.0.024 = phi i64 [ %4, %"_ZN38_$LT$core..option..Option$LT$T$GT$$GT$6unwrap17hb4e4d2d3d0768f5eE.exit" ], [ 0, %bb8.preheader ]
  %4 = add nuw i64 %iter.sroa.0.024, 1
  %5 = inttoptr i64 %it.sroa.0.025 to i32*
  %6 = sub i64 %1, %it.sroa.0.025
  %7 = icmp ult i64 %6, 4
  br i1 %7, label %bb2.i, label %"_ZN38_$LT$core..option..Option$LT$T$GT$$GT$6unwrap17hb4e4d2d3d0768f5eE.exit"

bb2.i:                                            ; preds = %bb8
; call core::panicking::panic
  tail call void @_ZN4core9panicking5panic17h9ff9e1335c8dccfaE({ [0 x i64], { [0 x i8]*, i64 }, [0 x i64], { [0 x i8]*, i64 }, [0 x i32], i32, [0 x i32], i32, [0 x i32] }* noalias readonly dereferenceable(40) bitcast (<{ i8*, [8 x i8], i8*, [16 x i8] }>* @byte_str.2 to { [0 x i64], { [0 x i8]*, i64 }, [0 x i64], { [0 x i8]*, i64 }, [0 x i32], i32, [0 x i32], i32, [0 x i32] }*))
  unreachable

"_ZN38_$LT$core..option..Option$LT$T$GT$$GT$6unwrap17hb4e4d2d3d0768f5eE.exit": ; preds = %bb8
  %8 = getelementptr inbounds i32, i32* %5, i64 1
  %9 = ptrtoint i32* %8 to i64
  %10 = load i32, i32* %5, align 4
  tail call void %f(i32 %10)
  %11 = icmp ult i64 %4, %slice.1
  br i1 %11, label %bb8, label %bb6
}
```
With my PR:
```
; sample::nth
; Function Attrs: uwtable
define void @_ZN6sample3nth17h23fbddb00ad8e6ffE([0 x i32]* noalias nonnull %slice.0, i64 %slice.1, void (i32)* nocapture nonnull %f) unnamed_addr #0 personality i32 (i32, i32, i64, %"unwind::libunwind::_Unwind_Exception"*, %"unwind::libunwind::_Unwind_Context"*)* @rust_eh_personality {
start:
  %0 = getelementptr inbounds [0 x i32], [0 x i32]* %slice.0, i64 0, i64 %slice.1
  %1 = ptrtoint i32* %0 to i64
  %2 = icmp eq i64 %slice.1, 0
  br i1 %2, label %bb6, label %bb8.preheader

bb8.preheader:                                    ; preds = %start
  %3 = ptrtoint [0 x i32]* %slice.0 to i64
  br label %bb8

bb6:                                              ; preds = %"_ZN38_$LT$core..option..Option$LT$T$GT$$GT$6unwrap17h698ff1cb0932f9a5E.exit", %start
  ret void

bb8:                                              ; preds = %bb8.preheader, %"_ZN38_$LT$core..option..Option$LT$T$GT$$GT$6unwrap17h698ff1cb0932f9a5E.exit"
  %it.sroa.0.026 = phi i64 [ %8, %"_ZN38_$LT$core..option..Option$LT$T$GT$$GT$6unwrap17h698ff1cb0932f9a5E.exit" ], [ %3, %bb8.preheader ]
  %iter.sroa.0.025 = phi i64 [ %4, %"_ZN38_$LT$core..option..Option$LT$T$GT$$GT$6unwrap17h698ff1cb0932f9a5E.exit" ], [ 0, %bb8.preheader ]
  %4 = add nuw i64 %iter.sroa.0.025, 1
  %5 = icmp eq i64 %it.sroa.0.026, %1
  %6 = inttoptr i64 %it.sroa.0.026 to i32*
  br i1 %5, label %bb2.i, label %"_ZN38_$LT$core..option..Option$LT$T$GT$$GT$6unwrap17h698ff1cb0932f9a5E.exit"

bb2.i:                                            ; preds = %bb8
; call core::panicking::panic
  tail call void @_ZN4core9panicking5panic17ha8d376de661f96f3E({ [0 x i64], { [0 x i8]*, i64 }, [0 x i64], { [0 x i8]*, i64 }, [0 x i32], i32, [0 x i32], i32, [0 x i32] }* noalias readonly dereferenceable(40) bitcast (<{ i8*, [8 x i8], i8*, [16 x i8] }>* @byte_str.2 to { [0 x i64], { [0 x i8]*, i64 }, [0 x i64], { [0 x i8]*, i64 }, [0 x i32], i32, [0 x i32], i32, [0 x i32] }*))
  unreachable

"_ZN38_$LT$core..option..Option$LT$T$GT$$GT$6unwrap17h698ff1cb0932f9a5E.exit": ; preds = %bb8
  %7 = getelementptr inbounds i32, i32* %6, i64 1
  %8 = ptrtoint i32* %7 to i64
  %9 = load i32, i32* %6, align 4
  tail call void %f(i32 %9)
  %10 = icmp ult i64 %4, %slice.1
  br i1 %10, label %bb8, label %bb6
}
```

However, I think an LLVM update happened in the mean time, so I will rebase.

**Comment by RalfJung** [comment]
I rebased. Doesn't seem to change anything though. The only actual difference is in `bb8`:
```diff
-  %4 = add nuw i64 %iter.sroa.0.024, 1
-  %5 = inttoptr i64 %it.sroa.0.025 to i32*
-  %6 = sub i64 %1, %it.sroa.0.025
-  %7 = icmp ult i64 %6, 4
+  %4 = add nuw i64 %iter.sroa.0.025, 1
+  %5 = icmp eq i64 %it.sroa.0.026, %1
+  %6 = inttoptr i64 %it.sroa.0.026 to i32*
```

**Comment by RalfJung** [comment]
I pushed a change which makes `len()` work more like it worked before. That aligns the IR of my `nth` test very well now:
```diff
-bb8:                                              ; preds = %bb8.preheader, %"_ZN38_$LT$core..option..Option$LT$T$GT$$GT$6unwrap17hbbb5b48ac958f586E.exit"
-  %it.sroa.0.025 = phi i64 [ %9, %"_ZN38_$LT$core..option..Option$LT$T$GT$$GT$6unwrap17hbbb5b48ac958f586E.exit" ], [ %3, %bb8.preheader ]
-  %iter.sroa.0.024 = phi i64 [ %4, %"_ZN38_$LT$core..option..Option$LT$T$GT$$GT$6unwrap17hbbb5b48ac958f586E.exit" ], [ 0, %bb8.preheader ]
-  %4 = add nuw i64 %iter.sroa.0.024, 1
-  %5 = inttoptr i64 %it.sroa.0.025 to i32*
-  %6 = sub i64 %1, %it.sroa.0.025
-  %7 = icmp ult i64 %6, 4
-  br i1 %7, label %bb2.i, label %"_ZN38_$LT$core..option..Option$LT$T$GT$$GT$6unwrap17hbbb5b48ac958f586E.exit"
+bb8:                                              ; preds = %bb8.preheader, %"_ZN38_$LT$core..option..Option$LT$T$GT$$GT$6unwrap17h31f46b755811ef8fE.exit"
+  %it.sroa.0.026 = phi i64 [ %9, %"_ZN38_$LT$core..option..Option$LT$T$GT$$GT$6unwrap17h31f46b755811ef8fE.exit" ], [ %3, %bb8.preheader ]
+  %iter.sroa.0.025 = phi i64 [ %4, %"_ZN38_$LT$core..option..Option$LT$T$GT$$GT$6unwrap17h31f46b755811ef8fE.exit" ], [ 0, %bb8.preheader ]
+  %4 = add nuw i64 %iter.sroa.0.025, 1
+  %5 = sub i64 %1, %it.sroa.0.026
+  %6 = icmp ult i64 %5, 4
+  %7 = inttoptr i64 %it.sroa.0.026 to i32*
+  br i1 %6, label %bb2.i, label %"_ZN38_$LT$core..option..Option$LT$T$GT$$GT$6unwrap17h31f46b755811ef8fE.exit"
```
For some reason the `inttoptr` moved up, the rest is the same.

**Comment by RalfJung** [comment]
`len` is used a lot, so maybe this makes a difference for perf?

@bors try

**Comment by kennytm** [comment]
@rust-timer build 03935103f724ead6d9e1d218e769b40632c09e13

**Comment by RalfJung** [comment]
`inflate` still down 7.5% (and `syn` 3%).

Any ideas which other methods I should compare the IR of...?

**Comment by RalfJung** [comment]
So the funny thing is that on my machine, rustc with the patch is *faster* than rustc without the patch...

`perf diff without-patch with-patch` shows
```
# Baseline  Delta Abs  Shared Object                                 Symbol                                                                                                                                        
# ........  .........  ............................................  ..............................................................................................................................................
#
    10.35%     -0.58%  librustc-6d0cd7a1d558f5af.so                  [.] rustc::infer::InferCtxt::shallow_resolve
     5.53%     +0.31%  librustc-6d0cd7a1d558f5af.so                  [.] <ena::unify::UnificationTable<S>>::get_root_key
     2.00%     +0.24%  libc-2.27.so                                  [.] __memmove_avx_unaligned_erms
     4.21%     +0.21%  librustc-6d0cd7a1d558f5af.so                  [.] <rustc_data_structures::obligation_forest::ObligationForest<O>>::compress
     0.30%     -0.21%  librustc_mir-1f1ee9043108f859.so              [.] <rustc_mir::dataflow::DataflowAnalysis<'a, 'tcx, BD>>::propagate
    12.45%     -0.21%  librustc-6d0cd7a1d558f5af.so                  [.] <rustc_data_structures::obligation_forest::ObligationForest<O>>::process_obligations
     1.32%     +0.15%  librustc-6d0cd7a1d558f5af.so                  [.] rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt<'a, 'gcx, 'tcx>>::get_query
               +0.15%  librustc-6d0cd7a1d558f5af.so                  [.] <rustc_data_structures::array_vec::ArrayVec<A> as core::iter::traits::Extend<<A as rustc_data_structures::array_vec::Array>::Element>>::ex
     0.19%     -0.15%  librustc-6d0cd7a1d558f5af.so                  [.] rustc::ty::context::tls::with_related_context
     0.36%     +0.14%  libstd-5fd27a9c989d76ae.so                    [.] free
     1.10%     -0.14%  librustc_codegen_llvm-llvm.so                 [.] llvm::SelectionDAG::Combine
     0.58%     -0.14%  librustc-6d0cd7a1d558f5af.so                  [.] <std::collections::hash::map::HashMap<K, V, S>>::insert
     0.41%     +0.13%  librustc_codegen_llvm-llvm.so                 [.] llvm::SmallPtrSetImplBase::FindBucketFor
     0.11%     +0.12%  librustc_codegen_llvm-llvm.so                 [.] (anonymous namespace)::Verifier::visitInstruction
     1.11%     +0.11%  librustc_mir-1f1ee9043108f859.so              [.] rustc_data_structures::bitslice::bitwise
     0.16%     -0.10%  librustc_codegen_llvm-llvm.so                 [.] llvm::SelectionDAG::MorphNodeTo
     0.01%     +0.10%  librustc_codegen_llvm-llvm.so                 [.] llvm::MachineFunction::getOrCreateLandingPadInfo
     0.06%     +0.10%  librustc_codegen_llvm-llvm.so                 [.] llvm::DenseMapBase<llvm::DenseMap<llvm::BasicBlock*, llvm::DomTreeBuilder::SemiNCAInfo<llvm::DominatorTreeBase<llvm::BasicBlock, false> >:
     0.16%     +0.09%  libc-2.27.so                                  [.] __memset_avx2_unaligned_erms
     0.11%     +0.09%  librustc-6d0cd7a1d558f5af.so                  [.] rustc::ty::fold::TypeFoldable::fold_with
     0.19%     -0.09%  librustc_codegen_llvm-llvm.so                 [.] llvm::DebugLoc::get
     0.13%     -0.09%  librustc_codegen_llvm-llvm.so                 [.] llvm::MachineRegisterInfo::addRegOperandToUseList
     0.76%     -0.09%  librustc_mir-1f1ee9043108f859.so              [.] <rustc_mir::dataflow::DataflowAnalysis<'a, 'tcx, D>>::propagate_bits_into_entry_set_for
     0.19%     -0.09%  librustc_codegen_llvm-llvm.so                 [.] llvm::SelectionDAG::AssignTopologicalOrder
     0.02%     +0.09%  librustc_typeck-7d15052dd0f265e9.so           [.] rustc_typeck::check::FnCtxt::check_expr_kind
     0.14%     -0.08%  librustc_codegen_llvm-llvm.so                 [.] llvm::Attribute::hasAttribute
     0.11%     -0.08%  librustc-6d0cd7a1d558f5af.so                  [.] <std::collections::hash::table::RawTable<K, V>>::new_internal
     0.23%     +0.08%  librustc_borrowck-58df19fa96434653.so         [.] <rustc::middle::dataflow::DataFlowContext<'a, 'tcx, O>>::apply_gen_kill
     0.38%     +0.08%  libstd-5fd27a9c989d76ae.so                    [.] sdallocx
     0.07%     +0.08%  librustc_codegen_llvm-llvm.so                 [.] (anonymous namespace)::X86MCInstLower::Lower
     0.05%     +0.08%  librustc_codegen_llvm-llvm.so                 [.] llvm::SelectionDAG::getConstant
     0.17%     -0.07%  librustc_codegen_llvm-llvm.so                 [.] llvm::FunctionLoweringInfo::set
     0.62%     +0.07%  librustc_codegen_llvm-llvm.so                 [.] llvm::SelectionDAGISel::SelectCodeCommon
     0.11%     -0.07%  librustc-6d0cd7a1d558f5af.so                  [.] rustc::ty::flags::FlagComputation::for_sty
     0.22%     -0.07%  librustc_codegen_llvm-llvm.so                 [.] llvm::InstrEmitter::EmitMachineNode
     0.08%     -0.07%  librustc-6d0cd7a1d558f5af.so                  [.] <rustc::ty::subst::SubstFolder<'a, 'gcx, 'tcx> as rustc::ty::fold::TypeFolder<'gcx, 'tcx>>::fold_ty
     0.12%     -0.07%  librustc-6d0cd7a1d558f5af.so                  [.] rustc::mir::BasicBlockData::terminator
     0.01%     +0.07%  librustc_codegen_llvm-llvm.so                 [.] llvm::MetadataTracking::untrack
     0.18%     -0.07%  librustc_metadata-906dec89bd6c2a40.so         [.] rustc_metadata::decoder::__ty_decoder_impl::<impl serialize::serialize::Decoder for rustc_metadata::decoder::DecodeContext<'a, 'tcx>>::rea
     0.07%     -0.07%  librustc_codegen_llvm-llvm.so                 [.] rustc_codegen_llvm::mir::FunctionCx::debug_loc
     0.03%     +0.07%  librustc_codegen_llvm-llvm.so                 [.] llvm::SDNode::Profile
     0.11%     -0.07%  librustc_codegen_llvm-llvm.so                 [.] AddNodeIDCustom
     0.18%     -0.06%  librustc_codegen_llvm-llvm.so                 [.] llvm::ValueEnumerator::ValueEnumerator
     0.01%     +0.06%  librustc_codegen_llvm-llvm.so                 [.] llvm::PseudoSourceValueManager::getFixedStack
     0.04%     +0.06%  librustc_codegen_llvm-llvm.so                 [.] llvm::ValueEnumerator::getValueID
     0.04%     +0.06%  librustc_codegen_llvm-llvm.so                 [.] llvm::ScheduleDAGSDNodes::ClusterNeighboringLoads
     0.08%     +0.06%  librustc_codegen_llvm-llvm.so                 [.] findRefEdges
```

**Comment by RalfJung** [comment]
Compiling against master (the one my patch is based on):

```
Benchmark #1: rm target -rf && cargo +stage2 rustc

  Time (mean ± σ):      3.149 s ±  0.037 s    [User: 3.246 s, System: 0.144 s]
 
  Range (min … max):    3.105 s …  3.218 s
```

Compiling against my patch:

```
Benchmark #1: rm target -rf && cargo +stage2.2 rustc

  Time (mean ± σ):      3.066 s ±  0.023 s    [User: 3.160 s, System: 0.140 s]
 
  Range (min … max):    3.029 s …  3.098 s
```

**Comment by RalfJung** [comment]
`perf report` said something about `try_fold` so I figured I'd look at that... IR looks different, but is that meaningful?

```rust
pub fn try_fold(slice: &mut [u32], init: u32, f: fn(u32, u32) -> Result<u32, ()>) -> Result<u32, ()> {
    slice.iter().try_fold(init, |x, y| f(x, *y))
}
```

```diff
   %1 = getelementptr inbounds [0 x i32], [0 x i32]* %slice.0, i64 0, i64 0
   %2 = getelementptr inbounds [0 x i32], [0 x i32]* %slice.0, i64 0, i64 %slice.1
   %3 = ptrtoint i32* %2 to i64
-  %.idx = shl nuw i64 %slice.1, 2
-  %4 = ashr exact i64 %.idx, 2
-  %5 = icmp ugt i64 %4, 3
-  br i1 %5, label %bb11.i, label %bb59.preheader.i
-
-bb59.preheader.i:                                 ; preds = %bb55.i, %start
-  %6 = phi i32* [ %1, %start ], [ %18, %bb55.i ]
-  %accum.0.lcssa.i = phi i32 [ %init, %start ], [ %.fca.1.extract89.i, %bb55.i ]
-  %7 = icmp eq i32* %6, %2
-  br i1 %7, label %"_ZN91_$LT$core..slice..Iter$LT$$u27$a$C$$u20$T$GT$$u20$as$u20$core..iter..iterator..Iterator$GT$8try_fold17hd1119a379b22d70fE.exit", label %bb66.i
-
-bb11.i:                                           ; preds = %start, %bb55.i
-  %8 = phi i32* [ %18, %bb55.i ], [ %1, %start ]
-  %accum.0178.i = phi i32 [ %.fca.1.extract89.i, %bb55.i ], [ %init, %start ]
-  %9 = getelementptr inbounds i32, i32* %8, i64 1
-  %10 = load i32, i32* %8, align 4, !alias.scope !0, !noalias !3
-  %11 = call { i32, i32 } %0(i32 %accum.0178.i, i32 %10)
-  %.fca.0.extract44.i = extractvalue { i32, i32 } %11, 0
-  %switch.i = icmp eq i32 %.fca.0.extract44.i, 0
-  br i1 %switch.i, label %bb27.i, label %"_ZN91_$LT$core..slice..Iter$LT$$u27$a$C$$u20$T$GT$$u20$as$u20$core..iter..iterator..Iterator$GT$8try_fold17hd1119a379b22d70fE.exit"
-
-bb27.i:                                           ; preds = %bb11.i
-  %.fca.1.extract45.i = extractvalue { i32, i32 } %11, 1
-  %12 = getelementptr inbounds i32, i32* %8, i64 2
-  %13 = load i32, i32* %9, align 4, !alias.scope !8, !noalias !11
-  %14 = call { i32, i32 } %0(i32 %.fca.1.extract45.i, i32 %13)
-  %.fca.0.extract56.i = extractvalue { i32, i32 } %14, 0
-  %switch13.i = icmp eq i32 %.fca.0.extract56.i, 0
-  br i1 %switch13.i, label %bb39.i, label %"_ZN91_$LT$core..slice..Iter$LT$$u27$a$C$$u20$T$GT$$u20$as$u20$core..iter..iterator..Iterator$GT$8try_fold17hd1119a379b22d70fE.exit"
-
-bb39.i:                                           ; preds = %bb27.i
-  %.fca.1.extract57.i = extractvalue { i32, i32 } %14, 1
-  %15 = getelementptr inbounds i32, i32* %8, i64 3
-  %16 = load i32, i32* %12, align 4, !alias.scope !13, !noalias !16
-  %17 = call { i32, i32 } %0(i32 %.fca.1.extract57.i, i32 %16)
-  %.fca.0.extract72.i = extractvalue { i32, i32 } %17, 0
-  %switch14.i = icmp eq i32 %.fca.0.extract72.i, 0
-  br i1 %switch14.i, label %bb51.i, label %"_ZN91_$LT$core..slice..Iter$LT$$u27$a$C$$u20$T$GT$$u20$as$u20$core..iter..iterator..Iterator$GT$8try_fold17hd1119a379b22d70fE.exit"
-
-bb51.i:                                           ; preds = %bb39.i
-  %.fca.1.extract73.i = extractvalue { i32, i32 } %17, 1
-  %18 = getelementptr inbounds i32, i32* %8, i64 4
-  %19 = load i32, i32* %15, align 4, !alias.scope !18, !noalias !21
-  %20 = call { i32, i32 } %0(i32 %.fca.1.extract73.i, i32 %19)
-  %.fca.0.extract88.i = extractvalue { i32, i32 } %20, 0
-  %switch15.i = icmp eq i32 %.fca.0.extract88.i, 0
-  br i1 %switch15.i, label %bb55.i, label %"_ZN91_$LT$core..slice..Iter$LT$$u27$a$C$$u20$T$GT$$u20$as$u20$core..iter..iterator..Iterator$GT$8try_fold17hd1119a379b22d70fE.exit"
-
-bb55.i:                                           ; preds = %bb51.i
-  %.fca.1.extract89.i = extractvalue { i32, i32 } %20, 1
-  %21 = ptrtoint i32* %18 to i64
-  %22 = sub i64 %3, %21
-  %23 = ashr exact i64 %22, 2
-  %24 = icmp ugt i64 %23, 3
-  br i1 %24, label %bb11.i, label %bb59.preheader.i
-
-bb66.i:                                           ; preds = %bb59.preheader.i, %bb70.i
-  %25 = phi i32* [ %26, %bb70.i ], [ %6, %bb59.preheader.i ]
-  %accum.1174.i = phi i32 [ %.fca.1.extract105.i, %bb70.i ], [ %accum.0.lcssa.i, %bb59.preheader.i ]
-  %26 = getelementptr inbounds i32, i32* %25, i64 1
-  %27 = load i32, i32* %25, align 4, !alias.scope !23, !noalias !26
-  %28 = call { i32, i32 } %0(i32 %accum.1174.i, i32 %27)
-  %.fca.0.extract104.i = extractvalue { i32, i32 } %28, 0
-  %switch16.i = icmp eq i32 %.fca.0.extract104.i, 0
-  br i1 %switch16.i, label %bb70.i, label %"_ZN91_$LT$core..slice..Iter$LT$$u27$a$C$$u20$T$GT$$u20$as$u20$core..iter..iterator..Iterator$GT$8try_fold17hd1119a379b22d70fE.exit"
-
-bb70.i:                                           ; preds = %bb66.i
-  %.fca.1.extract105.i = extractvalue { i32, i32 } %28, 1
-  %29 = icmp eq i32* %26, %2
-  br i1 %29, label %"_ZN91_$LT$core..slice..Iter$LT$$u27$a$C$$u20$T$GT$$u20$as$u20$core..iter..iterator..Iterator$GT$8try_fold17hd1119a379b22d70fE.exit", label %bb66.i
-
-"_ZN91_$LT$core..slice..Iter$LT$$u27$a$C$$u20$T$GT$$u20$as$u20$core..iter..iterator..Iterator$GT$8try_fold17hd1119a379b22d70fE.exit": ; preds = %bb11.i, %bb27.i, %bb39.i, %bb51.i, %bb66.i, %bb70.i, %bb59.preheader.i
-  %_0.sroa.7.0.i = phi i32 [ %accum.0.lcssa.i, %bb59.preheader.i ], [ undef, %bb66.i ], [ %.fca.1.extract105.i, %bb70.i ], [ undef, %bb51.i ], [ undef, %bb39.i ], [ undef, %bb27.i ], [ undef, %bb11.i ]
-  %_0.sroa.0.0.i = phi i32 [ 0, %bb59.preheader.i ], [ 1, %bb66.i ], [ 0, %bb70.i ], [ 1, %bb51.i ], [ 1, %bb39.i ], [ 1, %bb27.i ], [ 1, %bb11.i ]
-  %30 = insertvalue { i32, i32 } undef, i32 %_0.sroa.0.0.i, 0
-  %31 = insertvalue { i32, i32 } %30, i32 %_0.sroa.7.0.i, 1
-  ret { i32, i32 } %31
+  %4 = icmp ugt i64 %slice.1, 3
+  br i1 %4, label %bb7.i, label %bb45.preheader.i
+
+bb45.preheader.i:                                 ; preds = %bb39.i, %start
+  %5 = phi i32* [ %1, %start ], [ %17, %bb39.i ]
+  %accum.0.lcssa.i = phi i32 [ %init, %start ], [ %.fca.1.extract84.i, %bb39.i ]
+  %6 = icmp eq i32* %5, %2
+  br i1 %6, label %"_ZN91_$LT$core..slice..Iter$LT$$u27$a$C$$u20$T$GT$$u20$as$u20$core..iter..iterator..Iterator$GT$8try_fold17hb904259ba4085b95E.exit", label %bb47.i
+
+bb7.i:                                            ; preds = %start, %bb39.i
+  %7 = phi i32* [ %17, %bb39.i ], [ %1, %start ]
+  %accum.0171.i = phi i32 [ %.fca.1.extract84.i, %bb39.i ], [ %init, %start ]
+  %8 = getelementptr inbounds i32, i32* %7, i64 1
+  %9 = load i32, i32* %7, align 4, !alias.scope !0, !noalias !3
+  %10 = call { i32, i32 } %0(i32 %accum.0171.i, i32 %9)
+  %.fca.0.extract42.i = extractvalue { i32, i32 } %10, 0
+  %switch.i = icmp eq i32 %.fca.0.extract42.i, 0
+  br i1 %switch.i, label %bb19.i, label %"_ZN91_$LT$core..slice..Iter$LT$$u27$a$C$$u20$T$GT$$u20$as$u20$core..iter..iterator..Iterator$GT$8try_fold17hb904259ba4085b95E.exit"
+
+bb19.i:                                           ; preds = %bb7.i
+  %.fca.1.extract43.i = extractvalue { i32, i32 } %10, 1
+  %11 = getelementptr inbounds i32, i32* %7, i64 2
+  %12 = load i32, i32* %8, align 4, !alias.scope !8, !noalias !11
+  %13 = call { i32, i32 } %0(i32 %.fca.1.extract43.i, i32 %12)
+  %.fca.0.extract53.i = extractvalue { i32, i32 } %13, 0
+  %switch11.i = icmp eq i32 %.fca.0.extract53.i, 0
+  br i1 %switch11.i, label %bb27.i, label %"_ZN91_$LT$core..slice..Iter$LT$$u27$a$C$$u20$T$GT$$u20$as$u20$core..iter..iterator..Iterator$GT$8try_fold17hb904259ba4085b95E.exit"
+
+bb27.i:                                           ; preds = %bb19.i
+  %.fca.1.extract54.i = extractvalue { i32, i32 } %13, 1
+  %14 = getelementptr inbounds i32, i32* %7, i64 3
+  %15 = load i32, i32* %11, align 4, !alias.scope !13, !noalias !16
+  %16 = call { i32, i32 } %0(i32 %.fca.1.extract54.i, i32 %15)
+  %.fca.0.extract68.i = extractvalue { i32, i32 } %16, 0
+  %switch12.i = icmp eq i32 %.fca.0.extract68.i, 0
+  br i1 %switch12.i, label %bb35.i, label %"_ZN91_$LT$core..slice..Iter$LT$$u27$a$C$$u20$T$GT$$u20$as$u20$core..iter..iterator..Iterator$GT$8try_fold17hb904259ba4085b95E.exit"
+
+bb35.i:                                           ; preds = %bb27.i
+  %.fca.1.extract69.i = extractvalue { i32, i32 } %16, 1
+  %17 = getelementptr inbounds i32, i32* %7, i64 4
+  %18 = load i32, i32* %14, align 4, !alias.scope !18, !noalias !21
+  %19 = ptrtoint i32* %17 to i64
+  %20 = call { i32, i32 } %0(i32 %.fca.1.extract69.i, i32 %18)
+  %.fca.0.extract83.i = extractvalue { i32, i32 } %20, 0
+  %switch13.i = icmp eq i32 %.fca.0.extract83.i, 0
+  br i1 %switch13.i, label %bb39.i, label %"_ZN91_$LT$core..slice..Iter$LT$$u27$a$C$$u20$T$GT$$u20$as$u20$core..iter..iterator..Iterator$GT$8try_fold17hb904259ba4085b95E.exit"
+
+bb39.i:                                           ; preds = %bb35.i
+  %.fca.1.extract84.i = extractvalue { i32, i32 } %20, 1
+  %21 = sub i64 %3, %19
+  %22 = icmp ugt i64 %21, 15
+  br i1 %22, label %bb7.i, label %bb45.preheader.i
+
+bb47.i:                                           ; preds = %bb45.preheader.i, %bb51.i
+  %23 = phi i32* [ %24, %bb51.i ], [ %5, %bb45.preheader.i ]
+  %accum.1167.i = phi i32 [ %.fca.1.extract99.i, %bb51.i ], [ %accum.0.lcssa.i, %bb45.preheader.i ]
+  %24 = getelementptr inbounds i32, i32* %23, i64 1
+  %25 = load i32, i32* %23, align 4, !alias.scope !23, !noalias !26
+  %26 = call { i32, i32 } %0(i32 %accum.1167.i, i32 %25)
+  %.fca.0.extract98.i = extractvalue { i32, i32 } %26, 0
+  %switch14.i = icmp eq i32 %.fca.0.extract98.i, 0
+  br i1 %switch14.i, label %bb51.i, label %"_ZN91_$LT$core..slice..Iter$LT$$u27$a$C$$u20$T$GT$$u20$as$u20$core..iter..iterator..Iterator$GT$8try_fold17hb904259ba4085b95E.exit"
+
+bb51.i:                                           ; preds = %bb47.i
+  %.fca.1.extract99.i = extractvalue { i32, i32 } %26, 1
+  %27 = icmp eq i32* %24, %2
+  br i1 %27, label %"_ZN91_$LT$core..slice..Iter$LT$$u27$a$C$$u20$T$GT$$u20$as$u20$core..iter..iterator..Iterator$GT$8try_fold17hb904259ba4085b95E.exit", label %bb47.i
+
+"_ZN91_$LT$core..slice..Iter$LT$$u27$a$C$$u20$T$GT$$u20$as$u20$core..iter..iterator..Iterator$GT$8try_fold17hb904259ba4085b95E.exit": ; preds = %bb7.i, %bb19.i, %bb27.i, %bb35.i, %bb47.i, %bb51.i, %bb45.preheader.i
+  %_0.sroa.7.0.i = phi i32 [ %accum.0.lcssa.i, %bb45.preheader.i ], [ undef, %bb47.i ], [ %.fca.1.extract99.i, %bb51.i ], [ undef, %bb35.i ], [ undef, %bb27.i ], [ undef, %bb19.i ], [ undef, %bb7.i ]
+  %_0.sroa.0.0.i = phi i32 [ 0, %bb45.preheader.i ], [ 1, %bb47.i ], [ 0, %bb51.i ], [ 1, %bb35.i ], [ 1, %bb27.i ], [ 1, %bb19.i ], [ 1, %bb7.i ]
+  %28 = insertvalue { i32, i32 } undef, i32 %_0.sroa.0.0.i, 0
+  %29 = insertvalue { i32, i32 } %28, i32 %_0.sroa.7.0.i, 1
+  ret { i32, i32 } %29
```

**Comment by RalfJung** [comment]
Funny thing is, `try_from` *did* compute the length I did before the last commit. So I now have two length functions, matching the old code. Now the IR for `try_from` is more similar -- the diff is long but mostly not changing anything:
```diff
   %.idx = shl nuw i64 %slice.1, 2
   %4 = ashr exact i64 %.idx, 2
   %5 = icmp ugt i64 %4, 3
-  br i1 %5, label %bb11.i, label %bb59.preheader.i
+  br i1 %5, label %bb7.i, label %bb45.preheader.i
 
-bb59.preheader.i:                                 ; preds = %bb55.i, %start
-  %6 = phi i32* [ %1, %start ], [ %18, %bb55.i ]
-  %accum.0.lcssa.i = phi i32 [ %init, %start ], [ %.fca.1.extract89.i, %bb55.i ]
+bb45.preheader.i:                                 ; preds = %bb39.i, %start
+  %6 = phi i32* [ %1, %start ], [ %18, %bb39.i ]
+  %accum.0.lcssa.i = phi i32 [ %init, %start ], [ %.fca.1.extract84.i, %bb39.i ]
   %7 = icmp eq i32* %6, %2
-  br i1 %7, label %"_ZN91_$LT$core..slice..Iter$LT$$u27$a$C$$u20$T$GT$$u20$as$u20$core..iter..iterator..Iterator$GT$8try_fold17hd1119a379b22d70fE.exit", label %bb66.i
+  br i1 %7, label %"_ZN91_$LT$core..slice..Iter$LT$$u27$a$C$$u20$T$GT$$u20$as$u20$core..iter..iterator..Iterator$GT$8try_fold17hb904259ba4085b95E.exit", label %bb47.i
 
-bb11.i:                                           ; preds = %start, %bb55.i
-  %8 = phi i32* [ %18, %bb55.i ], [ %1, %start ]
-  %accum.0178.i = phi i32 [ %.fca.1.extract89.i, %bb55.i ], [ %init, %start ]
+bb7.i:                                            ; preds = %start, %bb39.i
+  %8 = phi i32* [ %18, %bb39.i ], [ %1, %start ]
+  %accum.0171.i = phi i32 [ %.fca.1.extract84.i, %bb39.i ], [ %init, %start ]
   %9 = getelementptr inbounds i32, i32* %8, i64 1
   %10 = load i32, i32* %8, align 4, !alias.scope !0, !noalias !3
-  %11 = call { i32, i32 } %0(i32 %accum.0178.i, i32 %10)
-  %.fca.0.extract44.i = extractvalue { i32, i32 } %11, 0
-  %switch.i = icmp eq i32 %.fca.0.extract44.i, 0
-  br i1 %switch.i, label %bb27.i, label %"_ZN91_$LT$core..slice..Iter$LT$$u27$a$C$$u20$T$GT$$u20$as$u20$core..iter..iterator..Iterator$GT$8try_fold17hd1119a379b22d70fE.exit"
+  %11 = call { i32, i32 } %0(i32 %accum.0171.i, i32 %10)
+  %.fca.0.extract42.i = extractvalue { i32, i32 } %11, 0
+  %switch.i = icmp eq i32 %.fca.0.extract42.i, 0
+  br i1 %switch.i, label %bb19.i, label %"_ZN91_$LT$core..slice..Iter$LT$$u27$a$C$$u20$T$GT$$u20$as$u20$core..iter..iterator..Iterator$GT$8try_fold17hb904259ba4085b95E.exit"
 
-bb27.i:                                           ; preds = %bb11.i
-  %.fca.1.extract45.i = extractvalue { i32, i32 } %11, 1
+bb19.i:                                           ; preds = %bb7.i
+  %.fca.1.extract43.i = extractvalue { i32, i32 } %11, 1
   %12 = getelementptr inbounds i32, i32* %8, i64 2
   %13 = load i32, i32* %9, align 4, !alias.scope !8, !noalias !11
-  %14 = call { i32, i32 } %0(i32 %.fca.1.extract45.i, i32 %13)
-  %.fca.0.extract56.i = extractvalue { i32, i32 } %14, 0
-  %switch13.i = icmp eq i32 %.fca.0.extract56.i, 0
-  br i1 %switch13.i, label %bb39.i, label %"_ZN91_$LT$core..slice..Iter$LT$$u27$a$C$$u20$T$GT$$u20$as$u20$core..iter..iterator..Iterator$GT$8try_fold17hd1119a379b22d70fE.exit"
+  %14 = call { i32, i32 } %0(i32 %.fca.1.extract43.i, i32 %13)
+  %.fca.0.extract53.i = extractvalue { i32, i32 } %14, 0
+  %switch11.i = icmp eq i32 %.fca.0.extract53.i, 0
+  br i1 %switch11.i, label %bb27.i, label %"_ZN91_$LT$core..slice..Iter$LT$$u27$a$C$$u20$T$GT$$u20$as$u20$core..iter..iterator..Iterator$GT$8try_fold17hb904259ba4085b95E.exit"
 
-bb39.i:                                           ; preds = %bb27.i
-  %.fca.1.extract57.i = extractvalue { i32, i32 } %14, 1
+bb27.i:                                           ; preds = %bb19.i
+  %.fca.1.extract54.i = extractvalue { i32, i32 } %14, 1
   %15 = getelementptr inbounds i32, i32* %8, i64 3
   %16 = load i32, i32* %12, align 4, !alias.scope !13, !noalias !16
-  %17 = call { i32, i32 } %0(i32 %.fca.1.extract57.i, i32 %16)
-  %.fca.0.extract72.i = extractvalue { i32, i32 } %17, 0
-  %switch14.i = icmp eq i32 %.fca.0.extract72.i, 0
-  br i1 %switch14.i, label %bb51.i, label %"_ZN91_$LT$core..slice..Iter$LT$$u27$a$C$$u20$T$GT$$u20$as$u20$core..iter..iterator..Iterator$GT$8try_fold17hd1119a379b22d70fE.exit"
+  %17 = call { i32, i32 } %0(i32 %.fca.1.extract54.i, i32 %16)
+  %.fca.0.extract68.i = extractvalue { i32, i32 } %17, 0
+  %switch12.i = icmp eq i32 %.fca.0.extract68.i, 0
+  br i1 %switch12.i, label %bb35.i, label %"_ZN91_$LT$core..slice..Iter$LT$$u27$a$C$$u20$T$GT$$u20$as$u20$core..iter..iterator..Iterator$GT$8try_fold17hb904259ba4085b95E.exit"
 
-bb51.i:                                           ; preds = %bb39.i
-  %.fca.1.extract73.i = extractvalue { i32, i32 } %17, 1
+bb35.i:                                           ; preds = %bb27.i
+  %.fca.1.extract69.i = extractvalue { i32, i32 } %17, 1
   %18 = getelementptr inbounds i32, i32* %8, i64 4
   %19 = load i32, i32* %15, align 4, !alias.scope !18, !noalias !21
-  %20 = call { i32, i32 } %0(i32 %.fca.1.extract73.i, i32 %19)
-  %.fca.0.extract88.i = extractvalue { i32, i32 } %20, 0
-  %switch15.i = icmp eq i32 %.fca.0.extract88.i, 0
-  br i1 %switch15.i, label %bb55.i, label %"_ZN91_$LT$core..slice..Iter$LT$$u27$a$C$$u20$T$GT$$u20$as$u20$core..iter..iterator..Iterator$GT$8try_fold17hd1119a379b22d70fE.exit"
-
-bb55.i:                                           ; preds = %bb51.i
-  %.fca.1.extract89.i = extractvalue { i32, i32 } %20, 1
-  %21 = ptrtoint i32* %18 to i64
-  %22 = sub i64 %3, %21
+  %20 = ptrtoint i32* %18 to i64
+  %21 = call { i32, i32 } %0(i32 %.fca.1.extract69.i, i32 %19)
+  %.fca.0.extract83.i = extractvalue { i32, i32 } %21, 0
+  %switch13.i = icmp eq i32 %.fca.0.extract83.i, 0
+  br i1 %switch13.i, label %bb39.i, label %"_ZN91_$LT$core..slice..Iter$LT$$u27$a$C$$u20$T$GT$$u20$as$u20$core..iter..iterator..Iterator$GT$8try_fold17hb904259ba4085b95E.exit"
+
+bb39.i:                                           ; preds = %bb35.i
+  %.fca.1.extract84.i = extractvalue { i32, i32 } %21, 1
+  %22 = sub i64 %3, %20
   %23 = ashr exact i64 %22, 2
   %24 = icmp ugt i64 %23, 3
-  br i1 %24, label %bb11.i, label %bb59.preheader.i
+  br i1 %24, label %bb7.i, label %bb45.preheader.i
 
-bb66.i:                                           ; preds = %bb59.preheader.i, %bb70.i
-  %25 = phi i32* [ %26, %bb70.i ], [ %6, %bb59.preheader.i ]
-  %accum.1174.i = phi i32 [ %.fca.1.extract105.i, %bb70.i ], [ %accum.0.lcssa.i, %bb59.preheader.i ]
+bb47.i:                                           ; preds = %bb45.preheader.i, %bb51.i
+  %25 = phi i32* [ %26, %bb51.i ], [ %6, %bb45.preheader.i ]
+  %accum.1167.i = phi i32 [ %.fca.1.extract99.i, %bb51.i ], [ %accum.0.lcssa.i, %bb45.preheader.i ]
   %26 = getelementptr inbounds i32, i32* %25, i64 1
   %27 = load i32, i32* %25, align 4, !alias.scope !23, !noalias !26
-  %28 = call { i32, i32 } %0(i32 %accum.1174.i, i32 %27)
-  %.fca.0.extract104.i = extractvalue { i32, i32 } %28, 0
-  %switch16.i = icmp eq i32 %.fca.0.extract104.i, 0
-  br i1 %switch16.i, label %bb70.i, label %"_ZN91_$LT$core..slice..Iter$LT$$u27$a$C$$u20$T$GT$$u20$as$u20$core..iter..iterator..Iterator$GT$8try_fold17hd1119a379b22d70fE.exit"
+  %28 = call { i32, i32 } %0(i32 %accum.1167.i, i32 %27)
+  %.fca.0.extract98.i = extractvalue { i32, i32 } %28, 0
+  %switch14.i = icmp eq i32 %.fca.0.extract98.i, 0
+  br i1 %switch14.i, label %bb51.i, label %"_ZN91_$LT$core..slice..Iter$LT$$u27$a$C$$u20$T$GT$$u20$as$u20$core..iter..iterator..Iterator$GT$8try_fold17hb904259ba4085b95E.exit"
 
-bb70.i:                                           ; preds = %bb66.i
-  %.fca.1.extract105.i = extractvalue { i32, i32 } %28, 1
+bb51.i:                                           ; preds = %bb47.i
+  %.fca.1.extract99.i = extractvalue { i32, i32 } %28, 1
   %29 = icmp eq i32* %26, %2
-  br i1 %29, label %"_ZN91_$LT$core..slice..Iter$LT$$u27$a$C$$u20$T$GT$$u20$as$u20$core..iter..iterator..Iterator$GT$8try_fold17hd1119a379b22d70fE.exit", label %bb66.i
+  br i1 %29, label %"_ZN91_$LT$core..slice..Iter$LT$$u27$a$C$$u20$T$GT$$u20$as$u20$core..iter..iterator..Iterator$GT$8try_fold17hb904259ba4085b95E.exit", label %bb47.i
 
-"_ZN91_$LT$core..slice..Iter$LT$$u27$a$C$$u20$T$GT$$u20$as$u20$core..iter..iterator..Iterator$GT$8try_fold17hd1119a379b22d70fE.exit": ; preds = %bb11.i, %bb27.i, %bb39.i, %bb51.i, %bb66.i, %bb70.i, %bb59.preheader.i
-  %_0.sroa.7.0.i = phi i32 [ %accum.0.lcssa.i, %bb59.preheader.i ], [ undef, %bb66.i ], [ %.fca.1.extract105.i, %bb70.i ], [ undef, %bb51.i ], [ undef, %bb39.i ], [ undef, %bb27.i ], [ undef, %bb11.i ]
-  %_0.sroa.0.0.i = phi i32 [ 0, %bb59.preheader.i ], [ 1, %bb66.i ], [ 0, %bb70.i ], [ 1, %bb51.i ], [ 1, %bb39.i ], [ 1, %bb27.i ], [ 1, %bb11.i ]
+"_ZN91_$LT$core..slice..Iter$LT$$u27$a$C$$u20$T$GT$$u20$as$u20$core..iter..iterator..Iterator$GT$8try_fold17hb904259ba4085b95E.exit": ; preds = %bb7.i, %bb19.i, %bb27.i, %bb35.i, %bb47.i, %bb51.i, %bb45.preheader.i
+  %_0.sroa.7.0.i = phi i32 [ %accum.0.lcssa.i, %bb45.preheader.i ], [ undef, %bb47.i ], [ %.fca.1.extract99.i, %bb51.i ], [ undef, %bb35.i ], [ undef, %bb27.i ], [ undef, %bb19.i ], [ undef, %bb7.i ]
+  %_0.sroa.0.0.i = phi i32 [ 0, %bb45.preheader.i ], [ 1, %bb47.i ], [ 0, %bb51.i ], [ 1, %bb35.i ], [ 1, %bb27.i ], [ 1, %bb19.i ], [ 1, %bb7.i ]
   %30 = insertvalue { i32, i32 } undef, i32 %_0.sroa.0.0.i, 0
   %31 = insertvalue { i32, i32 } %30, i32 %_0.sroa.7.0.i, 1
   ret { i32, i32 } %31
```
Only one `ptrtoint` seems to actually move around. Not sure why it does that...

But this means `try_from` actually should have already had this PR on the second-last perf run. :/

**Comment by kennytm** [comment]
(I've collapsed the diff to make the comments shorter)

**Comment by RalfJung** [comment]
Thanks.

I have been staring at the code and the IR to figure out why this `ptrtoint` moved. This is part of the length computation (the result is then subtracted from something and divided by 4). For some reason, with my PR it moves the `ptrtoint` to above the last call to `f`. I see no reason why it might do that. I also do not see a problem with that; this makes the result of `ptrtoint` live across the call to `f` but one of its inputs then is no longer live, so the live set has the same size.

Not sure if it is worth doing another perf run. I am otherwise out of ideas: I cannot reproduce the perf loss (it's a perf win for me!), and I cannot get any hint out of the remaining IR differences either.

**Comment by RalfJung** [comment]
Now both `nth` and `try_fold` are as similar as I could get them to the original IR. (This is pure cargo culting, I have no idea what I am doing. Help would really be much appreciated.)

Maybe this makes a difference? @bors try

**Comment by RalfJung** [comment]
D'oh I measured the wrong thing. I measured debug builds. With release builds, I do see a timing difference as well:
```
$ hyperfine -p 'rm -rf target' 'cargo +stage2 rustc --release' 'cargo +stage2.2 rustc --release'
Benchmark #1: cargo +stage2 rustc --release

  Time (mean ± σ):     17.482 s ±  0.414 s    [User: 17.610 s, System: 0.184 s]
 
  Range (min … max):   17.033 s … 18.285 s
 
Benchmark #2: cargo +stage2.2 rustc --release

  Time (mean ± σ):     19.083 s ±  0.322 s    [User: 19.219 s, System: 0.171 s]
 
  Range (min … max):   18.781 s … 19.567 s
 
Summary

  'cargo +stage2 rustc --release' ran
    1.09x faster than 'cargo +stage2.2 rustc --release'
```

**Comment by RalfJung** [comment]
All right, here's another perf diff. This time for the thing we really want to measure...

<details><summary>perf diff</summary>

```
# Event 'cycles:uppp'
#
# Baseline  Delta Abs  Shared Object                                 Symbol                                                                                                                                        
# ........  .........  ............................................  ..............................................................................................................................................
#
     1.50%     +1.93%  librustc_codegen_llvm-llvm.so                 [.] llvm::BasicBlock::getTerminator
     4.77%     -1.54%  librustc_codegen_llvm-llvm.so                 [.] llvm::DenseMapBase<llvm::DenseMap<llvm::BasicBlock*, std::unique_ptr<llvm::DomTreeNodeBase<llvm::BasicBlock>, std::default_delete<llvm::Do
     3.16%     -1.11%  librustc_codegen_llvm-llvm.so                 [.] llvm::DenseMapBase<llvm::DenseMap<llvm::BasicBlock*, llvm::DomTreeBuilder::SemiNCAInfo<llvm::DominatorTreeBase<llvm::BasicBlock, false> >:
     0.20%     +1.06%  libstd-5fd27a9c989d76ae.so                    [.] je_arena_dalloc_bin_junked_locked
     0.21%     +1.00%  librustc_codegen_llvm-llvm.so                 [.] llvm::isInstructionTriviallyDead
               +0.85%  librustc_codegen_llvm-llvm.so                 [.] llvm::PMDataManager::emitInstrCountChangedRemark
               +0.80%  librustc_codegen_llvm-llvm.so                 [.] (anonymous namespace)::DAGCombiner::visitSTORE
               +0.78%  librustc_codegen_llvm-llvm.so                 [.] llvm::BitstreamCursor::readRecord
     2.15%     -0.78%  librustc_codegen_llvm-llvm.so                 [.] llvm::DominatorTreeBase<llvm::BasicBlock, false>::dominates
               +0.77%  librustc_codegen_llvm-llvm.so                 [.] llvm::GlobalDCEPass::run
     0.05%     +0.77%  librustc_codegen_llvm-llvm.so                 [.] llvm::MachineRegisterInfo::defusechain_iterator<true, true, true, true, false, false>::defusechain_iterator
     0.79%     -0.77%  librustc_codegen_llvm-llvm.so                 [.] llvm::PMTopLevelManager::setLastUser
     1.51%     -0.75%  librustc_codegen_llvm-llvm.so                 [.] llvm::PMDataManager::findAnalysisPass
     0.15%     +0.75%  librustc_codegen_llvm-llvm.so                 [.] llvm::SelectionDAGISel::SelectCodeCommon
     2.06%     -0.72%  librustc-6d0cd7a1d558f5af.so                  [.] <rustc_data_structures::obligation_forest::ObligationForest<O>>::process_obligations
     2.10%     -0.70%  libstd-5fd27a9c989d76ae.so                    [.] malloc
     0.62%     +0.68%  librustc_codegen_llvm-llvm.so                 [.] llvm::TerminatorInst::getSuccessor
               +0.67%  librustc_codegen_llvm-llvm.so                 [.] llvm::Constant::getAllOnesValue
               +0.65%  librustc_codegen_llvm-llvm.so                 [.] llvm::FPPassManager::runOnFunction
     1.07%     -0.58%  librustc_codegen_llvm-llvm.so                 [.] llvm::Use::getImpliedUser
     0.74%     +0.58%  librustc_codegen_llvm-llvm.so                 [.] llvm::DenseMapBase<llvm::DenseMap<llvm::BasicBlock*, std::unique_ptr<llvm::DomTreeNodeBase<llvm::BasicBlock>, std::default_delete<llvm::Do
     0.47%     +0.57%  librustc_codegen_llvm-llvm.so                 [.] (anonymous namespace)::CallAnalyzer::analyzeBlock
     2.07%     -0.53%  librustc_codegen_llvm-llvm.so                 [.] llvm::DomTreeBuilder::SemiNCAInfo<llvm::DominatorTreeBase<llvm::BasicBlock, false> >::runSemiNCA
     7.17%     +0.50%  librustc_codegen_llvm-llvm.so                 [.] llvm::DenseMapBase<llvm::DenseMap<llvm::BasicBlock*, llvm::DomTreeBuilder::SemiNCAInfo<llvm::DominatorTreeBase<llvm::BasicBlock, false> >:
     0.83%     -0.50%  librustc_codegen_llvm-llvm.so                 [.] llvm::DomTreeBuilder::SemiNCAInfo<llvm::DominatorTreeBase<llvm::BasicBlock, false> >::ChildrenGetter<false>::Get
     0.15%     +0.49%  librustc_codegen_llvm-llvm.so                 [.] computeKnownBitsFromAssume
     0.92%     -0.46%  libstd-5fd27a9c989d76ae.so                    [.] free
     0.48%     -0.44%  librustc_codegen_llvm-llvm.so                 [.] llvm::ConstantFoldTerminator
               +0.40%  librustc_codegen_llvm-llvm.so                 [.] llvm::Module::getModuleFlagsMetadata
     0.21%     +0.40%  librustc_codegen_llvm-llvm.so                 [.] llvm::DomTreeBuilder::SemiNCAInfo<llvm::DominatorTreeBase<llvm::BasicBlock, false> >::runDFS<false, llvm::DomTreeBuilder::SemiNCAInfo<llvm
     1.32%     -0.38%  librustc_codegen_llvm-llvm.so                 [.] (anonymous namespace)::JoinVals::computeAssignment
               +0.38%  librustc_codegen_llvm-llvm.so                 [.] llvm::LazyValueInfo::enableDT@plt
     1.68%     -0.37%  librustc_codegen_llvm-llvm.so                 [.] llvm::LiveVariables::addNewBlock
     0.88%     +0.35%  librustc_codegen_llvm-llvm.so                 [.] llvm::DenseMap<llvm::BasicBlock*, llvm::DomTreeBuilder::SemiNCAInfo<llvm::DominatorTreeBase<llvm::BasicBlock, false> >::InfoRec, llvm::Den
     0.62%     -0.34%  librustc_codegen_llvm-llvm.so                 [.] llvm::SmallVectorTemplateBase<llvm::BasicBlock*, true>::push_back
     0.53%     -0.34%  librustc_codegen_llvm-llvm.so                 [.] (anonymous namespace)::CallAnalyzer::visitUnaryInstruction
     1.34%     +0.33%  librustc_codegen_llvm-llvm.so                 [.] llvm::SmallPtrSetImplBase::FindBucketFor
     0.42%     +0.32%  librustc_codegen_llvm-llvm.so                 [.] computeKnownBits
     0.87%     -0.31%  librustc_codegen_llvm-llvm.so                 [.] llvm::DenseMapBase<llvm::DenseMap<llvm::BasicBlock*, llvm::SmallVector<llvm::PointerIntPair<llvm::BasicBlock*, 1u, llvm::DomTreeBuilder::U
     0.08%     +0.31%  libstd-5fd27a9c989d76ae.so                    [.] je_arena_tcache_fill_small
     0.31%     +0.30%  librustc_codegen_llvm-llvm.so                 [.] llvm::LiveVariables::getVarInfo
               +0.29%  librustc_codegen_llvm-llvm.so                 [.] llvm::TargetLoweringBase::computeRegisterProperties
     0.47%     +0.28%  librustc_codegen_llvm-llvm.so                 [.] llvm::DomTreeBuilder::SemiNCAInfo<llvm::DominatorTreeBase<llvm::BasicBlock, false> >::runDFS<false, llvm::DomTreeBuilder::SemiNCAInfo<llvm
               +0.28%  librustc_codegen_llvm-llvm.so                 [.] llvm::BasicAAResult::aliasCheck
     1.57%     +0.28%  librustc-6d0cd7a1d558f5af.so                  [.] rustc::infer::InferCtxt::shallow_resolve
               +0.27%  cargo                                         [.] sk_push
     0.52%     -0.25%  librustc_codegen_llvm-llvm.so                 [.] llvm::TerminatorInst::getNumSuccessors
```

</details>

**Comment by RalfJung** [comment]
So the biggest increase is in `llvm::BasicBlock::getTerminator`... that's not a Rust function, is it?

If I filter out non-Rust functions, nothing sticks out any more.

**Comment by kennytm** [comment]
@rust-timer build 12bd850ff10bfc553362f022f8a6c1dbf9f0892b

**Comment by wesleywiser** [comment]
Yeah, you're right. Those are all LLVM functions. I don't know much about this area unfortunately. 

Perhaps somebody from @rust-lang/wg-codegen could tell us if [the changes in codegen](https://github.com/rust-lang/rust/pull/52206#issuecomment-407902090) look problematic?

**Comment by nagisa** [comment]
`ptrtoint` moved to a preceding block, which will cause extra analysis about the value to get gathered, I think? IIRC it is common to optimise in LLVM for when SSA values are in the same block as the code that’s operating on the value at that point.

**Comment by RalfJung** [comment]
@nagisa I managed to change the IR for `try_fold` so that (except for block names) it is exactly the same as before this PR. I will push that after a bit of cleanup.

Still 9% slower in local benchmarks.

**Comment by RalfJung** [comment]
It was suggested on IRC that maybe it's some annoying pass-ordering thing because more stuff is in functions now instead of macros.

**Comment by RalfJung** [comment]
I inlined `is_empty` and `len` as macros. Those were not macros before, but `self.len()` was often called as `ptrdistance(self.ptr, self.end)`, and moving the field loads out of the call seems to make a big difference.

On my system, this fixes the inflate compile time regression.

@bors try

**Comment by RalfJung** [comment]
Note that we still have
```
                // Use the len of the slice to hint optimizer to remove result index bounds check.
                let n = self.make_slice().len();
```
which used to be `make_slice!(...).len()`. Should I try to measure the difference? Or maybe just use `len!`? Cc @arthurprs who introduced this in https://github.com/rust-lang/rust/pull/47772

**Comment by kennytm** [comment]
@rust-timer build 5f82a6fe51833576e3568dffa2ac9ee91c864a34

**Comment by RalfJung** [comment]
Looking at the assembly. it seems like indeed bounds checks have crept back in.

**Comment by RalfJung** [comment]
Yeah the bounds check have re-appeared with this PR: :/

I have changed `make_slice` back to a macro, but that did not help. Any ideas?

**Comment by RalfJung** [comment]
Perf seems to be back up.

@rust-timer build 5f82a6f

**Comment by Mark-Simulacrum** [comment]
@rust-timer build 5f82a6fe51833576e3568dffa2ac9ee91c864a34

**Comment by RalfJung** [comment]
I think I found a way to both fix the codegen regression (see #52825) and not regress `inflate´. :)

Now if I just could also avoid that code duplication...

**Comment by RalfJung** [comment]
Yay, I think I found something. :D  No code duplication, codegen tests pass, and infer is just 1% slower than master on my machine (which I guess is within noise, though it does show 1% fairly consistently).

**Comment by kennytm** [comment]
@rust-timer build 77cedc9f602596cb632a817793abd593367be7c9

**Comment by RalfJung** [comment]
Well, that is looking pretty good, is it not?

**Comment by RalfJung** [comment]
However, https://github.com/rust-lang/rust/pull/52825 is making problems (which should be merged before this).

**Comment by alexcrichton** [comment]
That perf run indeed does look good! I think it's safe to say there's no obvious slowdown at least, so we can likely merge when ready.

**Comment by RalfJung** [comment]
#52825 landed. I rebased this PR. codegen tests still pass, I cannot run libcore tests (due to https://github.com/rust-lang/rust/issues/52943).

I think this is ready to go!

**Comment by gnzlbg** [comment]
>  Is there at least a CI job that runs the test suite with a debug version?

So what's the answer to this? If there isn't there should be one.

**Comment by kennytm** [comment]
We could run some tests (up to 30 minutes) in the `x86_64-gnu-debug` job.

**Comment by RalfJung** [comment]
Give that I got a CI failure when I previously tried to land this, *something* is tested with `debug` enabled. `ripgrep`, at least. I'd assume then that this also runs the usual libcore, libstd, run-pass tests?

**Comment by kennytm** [comment]
Ah right. We do *test* with `debug_assertions` enabled, but  they are disabled in *dist*. https://github.com/rust-lang/rust/blob/40e4b6ee3dd70a05007915bd1c15c150a7b7899f/src/ci/run.sh#L55-L76. The `x86_64-gnu-debug` job enables debug symbols in additional to debug assertions.

**Comment by nnethercote** [comment]
This turned out to be a clear win on a few benchmarks, of up to 3.9%:
https://perf.rust-lang.org/compare.html?start=97085f9fb0736b322dc216db3655da780b4d8041&end=1d9405fb6caa5eac18e5a28685e4f30dcbde6d45&stat=instructions:u

Nice job!

**Comment by RalfJung** [comment]
Thanks! No idea how that happened, though. ;)
