### PR TITLE
Modify existing bounds if they exist

### LINKED ISSUE #107335: Suggested bounds restriction suggests duplicate trait
### Code

```Rust
pub trait TryAdd<Rhs = Self> {
    type Error;
    type Output;

    fn try_add(self, rhs: Rhs) -> Result<Self::Output, Self::Error>;
}

impl<T: TryAdd> TryAdd for Option<T> {
    type Error = <T as TryAdd>::Error;
    type Output = Option<<T as TryAdd>::Output>;

    fn try_add(self, rhs: Self) -> Result<Self::Output, Self::Error> {
        Ok(self.or(rhs))
    }
}
```

### Current output

```Shell
error[E0308]: mismatched types
  --> src/lib.rs:14:12
   |
9  | impl<T: TryAdd> TryAdd for Option<T> {
   |      - this type parameter
...
14 |         Ok(self.or(rhs))
   |         -- ^^^^^^^^^^^^ expected associated type, found type parameter `T`
   |         |
   |         arguments to this enum variant are incorrect
   |
   = note: expected enum `Option<<T as TryAdd>::Output>`
              found enum `Option<T>`
help: the type constructed contains `Option<T>` due to the type of the argument passed
  --> src/lib.rs:14:9
   |
14 |         Ok(self.or(rhs))
   |         ^^^------------^
   |            |
   |            this argument influences the type of `Ok`
note: tuple variant defined here
  --> /rustc/c18a5e8a5b1afb0d7a582fe9ebad4c1996c90da3/library/core/src/result.rs:507:5
help: consider further restricting this bound
   |
9  | impl<T: TryAdd + TryAdd<Output = T>> TryAdd for Option<T> {
   |                ++++++++++++++++++++

For more information about this error, try `rustc --explain E0308`.
error: could not compile `playground` due to previous error
```

### Desired output

```Shell
error[E0308]: mismatched types
  --> src/lib.rs:14:12
   |
9  | impl<T: TryAdd> TryAdd for Option<T> {
   |      - this type parameter
...
14 |         Ok(self.or(rhs))
   |         -- ^^^^^^^^^^^^ expected associated type, found type parameter `T`
   |         |
   |         arguments to this enum variant are incorrect
   |
   = note: expected enum `Option<<T as TryAdd>::Output>`
              found enum `Option<T>`
help: the type constructed contains `Option<T>` due to the type of the argument passed
  --> src/lib.rs:14:9
   |
14 |         Ok(self.or(rhs))
   |         ^^^------------^
   |            |
   |            this argument influences the type of `Ok`
note: tuple variant defined here
  --> /rustc/c18a5e8a5b1afb0d7a582fe9ebad4c1996c90da3/library/core/src/result.rs:507:5
help: consider further restricting this bound
   |
9  | impl<T: TryAdd<Output = T>> TryAdd for Option<T> {
   |         ++++++++++++++++++

For more information about this error, try `rustc --explain E0308`.
error: could not compile `playground` due to previous error
```

### Rationale and extra context

While the diagnostic produces valid code, I think this diagnostic could be improved. I don't think there's ever a valid scenario where a human would write `MyTrait + MyTrait<Output = T>` over `MyTrait<Output = T>`.

### Other cases

_No response_

### Anything else?

Reproduces on [playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=10ecd4fc67c7e39d15ac8b8586f4996c).

Tested on stable 1.66.1 and nightly 1.69.0-nightly (2023-01-25 c18a5e8a5b1afb0d7a58)

### PR DESCRIPTION
**Pull request by edward-shen**
Fixes #107335.

This implementation is kinda gross but I don't really see a better way to do it.

This primarily does two things: Modifies `suggest_constraining_type_param` to accept a new parameter that indicates a span to be replaced instead of added, if presented, and limit the additive suggestions to either suggest a new bound on an existing bound (see newly added unit test) or add the generics argument if a generics argument wasn't found.

The former change is required to retain the capability to add an entirely new bounds if it was entirely omitted.

r? @compiler-errors

### CODE REVIEW

File: compiler/rustc_infer/src/infer/error_reporting/note_and_explain.rs [hunk 1]
```diff
@@ -78,48 +78,82 @@ impl<'tcx> TypeErrCtxt<'_, 'tcx> {
...
+                        let parent = p_def_id
                             .as_local()
-                            .map(|id| hir.local_def_id_to_hir_id(id))
-                            .and_then(|id| tcx.hir().find_parent(id))
-                            .as_ref()
-                            .and_then(|node| node.generics())
+                            .map(|id| (id, hir.local_def_id_to_hir_id(id)))
+                            .and_then(|(local_id, hir_id)| tcx.hir().find_parent(hir_id).map(|node| (local_id, node)));
+                        if let Some((local_id, generics)) = parent.as_ref()
+                            .and_then(|(local_id, node)| node.generics().map(|generics| (local_id, generics)))
```
Comment (compiler-errors) [inline compiler/rustc_infer/src/infer/error_reporting/note_and_explain.rs:93]: There's gotta be a way to simplify this, perhaps by avoiding these combinators... Could you maybe make this logic a bit simpler?

**Review by compiler-errors — APPROVED** [review]
This looks good other than perhaps some of the logic can be simplified. Could you do that? Otherwise r=me, should be fine to land regardless. 

Ping me if you give up on trying to simplify stuff and I can approve.

File: compiler/rustc_infer/src/infer/error_reporting/note_and_explain.rs (hunk 1 above)
Comment (edward-shen) [reply compiler/rustc_infer/src/infer/error_reporting/note_and_explain.rs]: Couldn't get rid of an `and_then`, but does this look cleaner to you?

File: compiler/rustc_infer/src/infer/error_reporting/note_and_explain.rs [hunk 2]
```diff
@@ -77,49 +77,87 @@ impl<'tcx> TypeErrCtxt<'_, 'tcx> {
...
-                            .type_param(p, tcx)
-                            .def_id
+                        let parent = p_def_id
                             .as_local()
-                            .map(|id| hir.local_def_id_to_hir_id(id))
-                            .and_then(|id| tcx.hir().find_parent(id))
-                            .as_ref()
-                            .and_then(|node| node.generics())
+                            .and_then(|id| {
+                                let local_id= hir.local_def_id_to_hir_id(id);
```
Comment (compiler-errors) [inline compiler/rustc_infer/src/infer/error_reporting/note_and_explain.rs:93]:
```suggestion
                                let local_id = hir.local_def_id_to_hir_id(id);
```

File: compiler/rustc_infer/src/infer/error_reporting/note_and_explain.rs [hunk 3]
```diff
@@ -77,49 +77,87 @@ impl<'tcx> TypeErrCtxt<'_, 'tcx> {
...
+                                    .filter_map(|bound| {
+                                        let bound_trait_path = bound.trait_ref()?.path;
+                                        let def_id = bound_trait_path.res.opt_def_id()?;
+                                        let generic_args = bound_trait_path.segments.iter().last().map(|path| path.args());
+                                        (def_id == trait_ref.def_id).then_some((bound_trait_path.span, generic_args))
+                                    })
+                                    .next();
+
+                                if let Some((end_of_trait, end_of_args)) = potential_spans {
+                                    let args_span = end_of_args.map(|args| args.span()).flatten();
```
Comment (compiler-errors) [inline compiler/rustc_infer/src/infer/error_reporting/note_and_explain.rs:125]:
```suggestion
                                    let args_span = end_of_args.and_then(|args| args.span());
```

File: compiler/rustc_infer/src/infer/error_reporting/note_and_explain.rs [hunk 4]
```diff
@@ -77,49 +77,87 @@ impl<'tcx> TypeErrCtxt<'_, 'tcx> {
...
+                            for bound in generics.bounds_for_param(local_id) {
+                                let potential_spans = bound
+                                    .bounds
+                                    .iter()
+                                    .filter_map(|bound| {
+                                        let bound_trait_path = bound.trait_ref()?.path;
+                                        let def_id = bound_trait_path.res.opt_def_id()?;
+                                        let generic_args = bound_trait_path.segments.iter().last().map(|path| path.args());
+                                        (def_id == trait_ref.def_id).then_some((bound_trait_path.span, generic_args))
+                                    })
```
Comment (compiler-errors) [inline compiler/rustc_infer/src/infer/error_reporting/note_and_explain.rs:121]: What happens if we have like...

```
T: Trait<A> + Trait<B>
```

and then we suggest to restrict `T: Trait<B, Output = C>`

What will that do?

File: compiler/rustc_infer/src/infer/error_reporting/note_and_explain.rs [hunk 5]
```diff
@@ -77,49 +77,87 @@ impl<'tcx> TypeErrCtxt<'_, 'tcx> {
...
+                                    .next();
```
[the remark this answers is not in the document]
Comment (edward-shen) [reply compiler/rustc_infer/src/infer/error_reporting/note_and_explain.rs]: TIL, thanks

File: compiler/rustc_infer/src/infer/error_reporting/note_and_explain.rs (hunk 4 above)
Comment (edward-shen) [reply compiler/rustc_infer/src/infer/error_reporting/note_and_explain.rs]: Wouldn't the associated type prevent multiple trait impls on the same type anyways? So `Trait<A> + Trait<B>` would error for other reasons before suggesting to constrain the bounds?

**Comment by edward-shen** [comment]
Changes:
 - Applied better combinators per feedback from Michael

File: compiler/rustc_infer/src/infer/error_reporting/note_and_explain.rs (hunk 4 above)
Comment (compiler-errors) [reply compiler/rustc_infer/src/infer/error_reporting/note_and_explain.rs]: e.g.

```
trait Foo<T> {
    type Output;

    fn bar() -> Self::Output;
}

fn test<T>() -> i32 where T: Foo<()>, T: Foo<i32> {
    <T as Foo<()>>::bar()
}
```

Comment (compiler-errors) [reply compiler/rustc_infer/src/infer/error_reporting/note_and_explain.rs]: But I guess that already suggests `.. , Output = i32>` correctly

**Comment by compiler-errors** [comment]
Anywho

@bors r+ rollup
