### PR TITLE
Change environment variable getters to error recoverably

### LINKED ISSUE #86082: ICE: 'failed to get environment variable `"\u{103ff}¿\u{1a}\u{0}j\'"`: data provided contains a nul byte', library/std/src/env.rs:252:29
### Code

```Rust
fn main() {
    option_env!(
        "𐏿¿\0j\'\
 
"
    )
}
```

### Meta

`rustc --version --verbose`:
```
rustc 1.54.0-nightly (dbe459ded 2021-06-02)
binary: rustc
commit-hash: dbe459dedd33470f2cb28101157de316caaffa66
commit-date: 2021-06-02
host: x86_64-unknown-linux-gnu
release: 1.54.0-nightly
LLVM version: 12.0.1
```

### Error output

```
thread 'rustc' panicked at 'failed to get environment variable `"\u{103ff}¿\u{1a}\u{0}j\'"`: data provided contains a nul byte', library/std/src/env.rs:252:29
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.54.0-nightly (dbe459ded 2021-06-02) running on x86_64-unknown-linux-gnu

note: compiler flags: -Z mir-opt-level=3 -Z new-llvm-pass-manager=yes -Z unsound-mir-opts=yes -Z polonius=yes -Z polymorphize=yes -C debuginfo=2 -C opt-level=3 --crate-type staticlib

query stack during panic:
end of query stack
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
thread 'rustc' panicked at 'failed to get environment variable `"\u{103ff}¿\u{1a}\u{0}j\'"`: data provided contains a nul byte', library/std/src/env.rs:252:29
stack backtrace:
   0: rust_begin_unwind
             at /rustc/dbe459dedd33470f2cb28101157de316caaffa66/library/std/src/panicking.rs:515:5
   1: std::panicking::begin_panic_fmt
             at /rustc/dbe459dedd33470f2cb28101157de316caaffa66/library/std/src/panicking.rs:457:5
   2: std::env::_var_os::{{closure}}
             at /rustc/dbe459dedd33470f2cb28101157de316caaffa66/library/std/src/env.rs:252:29
   3: core::result::Result<T,E>::unwrap_or_else
             at /rustc/dbe459dedd33470f2cb28101157de316caaffa66/library/core/src/result.rs:821:23
   4: std::env::_var_os
             at /rustc/dbe459dedd33470f2cb28101157de316caaffa66/library/std/src/env.rs:251:5
   5: std::env::var_os
             at /rustc/dbe459dedd33470f2cb28101157de316caaffa66/library/std/src/env.rs:247:5
   6: std::env::_var
             at /rustc/dbe459dedd33470f2cb28101157de316caaffa66/library/std/src/env.rs:215:11
   7: rustc_builtin_macros::env::expand_option_env
   8: rustc_expand::expand::MacroExpander::fully_expand_fragment
   9: rustc_expand::expand::MacroExpander::expand_crate
  10: rustc_interface::passes::configure_and_expand_inner
  11: rustc_interface::passes::configure_and_expand::{{closure}}
  12: rustc_data_structures::box_region::PinnedGenerator<I,A,R>::new
  13: rustc_interface::passes::configure_and_expand
  14: rustc_interface::queries::Queries::expansion
  15: rustc_span::with_session_globals
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.54.0-nightly (dbe459ded 2021-06-02) running on x86_64-unknown-linux-gnu

note: compiler flags: -Z mir-opt-level=3 -Z new-llvm-pass-manager=yes -Z unsound-mir-opts=yes -Z polonius=yes -Z polymorphize=yes -C debuginfo=2 -C opt-level=3 --crate-type staticlib

query stack during panic:
end of query stack
```

</p>
</details>

### PR DESCRIPTION
**Pull request by inquisitivecrystal**
This PR changes the standard library environment variable getter functions to error recoverably (i.e. not panic) when given an invalid value.

On some platforms, it is invalid for environment variable names to contain `'\0'` or `'='`, or for their values to contain `'\0'`. Currently, the standard library panics when manipulating environment variables with names or values that violate these invariants. However, this behavior doesn't make a lot of sense, at least in the case of getters. If the environment variable is missing, the standard library just returns an error value, rather than panicking. It doesn't make sense to treat the case where the variable is invalid any differently from that. See the [internals thread](https://internals.rust-lang.org/t/why-should-std-var-panic/14847) for discussion. Thus, this PR changes the functions to error recoverably in this case as well.

If desired, I could change the functions that manipulate environment variables in other ways as well. I didn't do that here because it wasn't entirely clear what to change them to. Should they error silently or do something else? If someone tells me how to change them, I'm happy to implement the changes.

This fixes #86082, an ICE that arises from the current behavior. It also adds a regression test to make sure the ICE does not occur again in the future.

@rustbot label +T-libs
r? @joshtriplett

### CODE REVIEW

**Comment by joshtriplett** [comment]
I can see the argument for failing more gracefully. On the other hand, this *seems* more like an internal assertion, and an entirely avoidable one: it'll only happen if you pass an invalid environment variable name. Silently turning that into a `None` as though the environment variable simply doesn't exist seems questionable.

On the other other hand, it is in a sense *accurate* that no variable named `varname=morevarname\0yetmorename` exists. :slightly_smiling_face:

**Comment by inquisitivecrystal** [comment]
> On the other other hand, it is in a sense accurate that no variable named varname=morevarname\0yetmorename exists. 🙂

This would be my view. I wouldn't even say "in a sense". If you look for the variable in the environment, is it there? It wouldn't be. Thus, it's arguably somewhat irrelevant that it *couldn't* exist.

That said, if you would prefer to keep the library unchanged, that's an entirely fair call. How would you like to proceed on this?

**Comment by ChrisDenton** [comment]
I can see the argument for informing the programmer that a constant key name will always be invalid (i.e. never be set). However a panic at runtime seems very heavy headed considering there's no good way to recover (except for `catch_unwind` if not aborting on panic).

**Comment by inquisitivecrystal** [comment]
> I can see the argument for informing the programmer that a constant key name will always be invalid (i.e. never be set). However a panic at runtime seems very heavy handed considering there's no good way to recover (except for `catch_unwind` if not aborting on panic).

Also, what if the end user is the one who provides the environment variable name, like in #86082 (in that case, the end user of rustc)? Then it's not the programmer's fault, and we're making them check specifically for a weird special case that only happens on certain platforms. Worse, there are platforms where this would be valid, so then they have to implement platform specific logic to handle information we already have available.

I don't really think the status quo is tenable. However, one could consider introducing a new API is a better course.

**Comment by m-ou-se** [comment]
We discussed this yesterday in the libs team meetings.

From an API perspective, we think it's perfectly reasonable to treat things like `=` or `\0` as any other environment variable that doesn't exist, since we are sure that no such environment variable can exist.

For the implementation: Instead of having `os_imp::getenv` return an `io::Error` and ignoring it in `_var_os`, it'd be better to make `getenv` just return an Option and not a Result. Then it's clear at the implementation of `getenv` that errors are not going to be handled.

File: library/std/src/env.rs [hunk 1]
```diff
@@ -188,12 +188,8 @@ impl fmt::Debug for VarsOs {
...
 /// Errors if the environment variable is not valid Unicode. If this is not desired, consider using
 /// [`var_os`].
-///
-/// # Panics
-///
-/// This function may panic if `key` is empty, contains an ASCII equals sign
-/// `'='` or the NUL character `'\0'`, or when the value contains the NUL
-/// character.
+/// May error if the `key` is empty, contains an ASCII equals sign `'='`, or contains the NUL character `'\0'`.
+/// May error when the value contains the NUL character.
```
Comment (m-ou-se) [inline library/std/src/env.rs:192]: Are there any platforms where this is possible?

Comment (ChrisDenton) [reply library/std/src/env.rs:192]: On Windows nulls aren't allowed but it is technically possible for a key to begin with an `=` (e.g. `=key=value`). However this is essentially a backwards compatibility hack used only by `cmd.exe` so as to have hidden variables for internal use. It is not documented and is not meant to be set or used by other code. That said, nothing actually prevents a program from doing so.

File: library/std/src/env.rs [hunk 2]
```diff
@@ -219,18 +215,18 @@ fn _var(key: &OsStr) -> Result<String, VarError> {
...
+/// [`None`] if the variable isn't set or there's another error.
 ///
 /// Note that the method will not check if the environment variable
 /// is valid Unicode. If you want to have an error on invalid UTF-8,
 /// use the [`var`] function instead.
 ///
+/// # Errors
+///
+/// Errors if the variable isn't set.
+/// May error if the `key` is empty, contains an ASCII equals sign `'='`, or contains the NUL character `'\0'`.
```
Comment (ChrisDenton) [inline library/std/src/env.rs:227]: Btw, I think lowercase "null" is now the preferred term? See #84842.

File: library/std/src/env.rs (hunk 1 above)
Comment (inquisitivecrystal) [reply library/std/src/env.rs:192]: There are also some targets where the env is literally a hashmap. Sgx, for example. I'm not sure in what sense it's an environment at that point, but perhaps I'm missing something.

File: library/std/src/env.rs (hunk 2 above)
Comment (inquisitivecrystal) [reply library/std/src/env.rs:227]: I think that's for null, as in the pointer. This is for the character. I could type it nul, but I would think we would want to match EOF (which is admittedly a pseudocharacter) and DEL, which I usually see in upper case?

Comment (ChrisDenton) [reply library/std/src/env.rs:227]: Fair enough!

**Comment by inquisitivecrystal** [comment]
Is there anything I should do about the documentation? I was just rereading it, and it doesn't feel like "errors" or "may error" is the clearest way to put things. I don't really know how to fix improve on that though..

**Comment by inquisitivecrystal** [comment]
I fixed up the docs. 

@m-ou-se As far as I know, this is ready to merge.

**Comment by m-ou-se** [comment]
Thanks!

@bors r+

File: library/std/src/env.rs [hunk 3]
```diff
@@ -185,15 +185,9 @@ impl fmt::Debug for VarsOs {
...
-/// [`var_os`].
-///
-/// # Panics
-///
-/// This function may panic if `key` is empty, contains an ASCII equals sign
-/// `'='` or the NUL character `'\0'`, or when the value contains the NUL
-/// character.
+/// Returns `[None]` if the environment variable isn't set.
+/// Returns `[None]` if the environment variable is not valid Unicode. If this is not
+/// desired, consider using [`var_os`].
```
Comment (RalfJung) [inline library/std/src/env.rs:190]: The function returns a `Result` -- how can it return `None`? I think you meant `Err`.

File: library/std/src/env.rs [hunk 4]
```diff
@@ -185,15 +185,9 @@ impl fmt::Debug for VarsOs {
...
 ///
-/// Errors if the environment variable is not present.
-/// Errors if the environment variable is not valid Unicode. If this is not desired, consider using
-/// [`var_os`].
-///
-/// # Panics
-///
-/// This function may panic if `key` is empty, contains an ASCII equals sign
-/// `'='` or the NUL character `'\0'`, or when the value contains the NUL
-/// character.
```
Comment (RalfJung) [inline library/std/src/env.rs:196]: Wouldn't it be better to still say what happens for these cases?

Comment (inquisitivecrystal) [reply library/std/src/env.rs:196]: The error section (which you commented on) should cover it? The theory is that "if the environment variable isn't set" applies to the equals sign and NUL character being in the key, since we should only be erroring on platforms where those *can't* be in the key. The value containing the NUL character is explicitly covered.

File: library/std/src/env.rs (hunk 3 above)
Comment (inquisitivecrystal) [reply library/std/src/env.rs:190]: Good catch. That's just plain wrong. I'll send a fix PR as soon after we figure out what, if anything, I need to do about your other comment.

File: library/std/src/env.rs (hunk 4 above)
Comment (RalfJung) [reply library/std/src/env.rs:196]: > The theory is that "if the environment variable isn't set" applies to the equals sign and NUL character being in the key, since we should only be erroring on platforms where those can't be in the key.

That seems awfully implicit, doesn't it? I don't have a strong opinion, but given in particular that behavior changed here, I think it is worth saying explicitly that empty, `=` or NUL are considered "not set".

> The value containing the NUL character is explicitly covered.

Is it? I don't see it. It talks about invalid unicode, but NULL is not invalid unicode AFAIK.

Comment (inquisitivecrystal) [reply library/std/src/env.rs:196]: > That seems awfully implicit, doesn't it? I don't have a strong opinion, but given in particular that behavior changed here, I think it is worth saying explicitly that empty, = or NUL are considered "not set".

The thing is that they're not always considered not set. They're considered not set (hopefully, if I understand things right) on platforms where they could never have been set in the first place. There are platforms on which it is valid to have an = or a NUL. At that point, I'd basically be saying "If the environment variable isn't set (including if it isn't set because it contains an `=` or NUL character and that is invalid for the current platform)". Of course, I could say it more nicely than that, but it doesn't seem like the reason why we think environment variable isn't set should matter?

> Is it? I don't see it. It talks about invalid unicode, but NULL is not invalid unicode AFAIK.

Uhhh. Whoops. Will fix.

Comment (RalfJung) [reply library/std/src/env.rs:196]: > At that point, I'd basically be saying "If the environment variable isn't set (including if it isn't set because it contains an = or NUL character and that is invalid for the current platform)". Of course, I could say it more nicely than that, but it doesn't seem like the reason why we think the environment variable isn't set should matter?

I think this is worth saying explicitly, given in particular that future Rust versions will behave different from older Rust versions here. I am sure some people will wonder what happens in this case, so the text should answer their question. The docs are very short currently so I am not worried about adding a sentence or two.

Btw, looking at https://doc.rust-lang.org/nightly/std/env/fn.var.html the text renders this as `[None]`, which also doesn't seem right -- we don't want those brackets to show.

Comment (inquisitivecrystal) [reply library/std/src/env.rs:196]: I think I flipped the brackets and the quotes. *sighs*

**Comment by lopopolo** [comment]
With this change, how does a user of `env::var_os` distinguish between an env variable name not existing and the underlying platform returning `EINVAL`?

I'm interested in being able to distinguish this behavior since I'm implementing Ruby's `ENV` which raises on invalid names:

- https://ruby-doc.org/core-3.0.2/ENV.html#method-c-5B-5D
- https://ruby-doc.org/core-3.0.2/ENV.html#class-ENV-label-Invalid+Names+and+Values

I think in my ideal world, there'd a fallible version of `env::var_os` that doesn't squash to `None` or `panic`.

With the panicking behavior prior to this PR being merged, I had to pull the `EINVAL` checking into my own code above the call to `std::env::var_os`: https://github.com/artichoke/artichoke/blob/daf01d7fa995ab42e21444f3834c49f4563d7301/spinoso-env/src/env/system.rs#L97-L127.

Additionally, I think this PR should be tagged with `relnotes`.

**Comment by lopopolo** [comment]
Is it not a breaking change to turn documented panics into something else?

I reported the undocumented panics here https://github.com/rust-lang/rust/issues/63456 and they were added to the docs as part of the API contract here https://github.com/rust-lang/rust/pull/63461.

**Comment by RalfJung** [comment]
Cc @rust-lang/libs-api for the questions raised above -- though this was approved by a team member.

**Comment by lopopolo** [comment]
Python has a similar behavior to Ruby.


```console
root@e8db2cec4f95:/# python3 -c "import os; os.environ['a'] = 'abc\0xyz'"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3.8/os.py", line 681, in __setitem__
    self.putenv(key, value)
ValueError: embedded null byte
root@e8db2cec4f95:/# python3 -c "import os; os.environ['a\0b'] = 'e'"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3.8/os.py", line 681, in __setitem__
    self.putenv(key, value)
ValueError: embedded null byte
root@e8db2cec4f95:/# python3 -c "import os; os.environ['a=b'] = 'e'"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3.8/os.py", line 681, in __setitem__
    self.putenv(key, value)
ValueError: illegal environment variable name
```

How would one implement this API with the existing APIs in `std`?

For APIs in `std` that call into libc functions that set `errno`, I would expect a fallible version. For APIs in `std` that call into libc functions that have different preconditions on their inputs than encoded in `OsStr`, I would expect a fallible version.

The previous behavior with panics was not ideal, but it did callers to observe failures and recover from them with `catch_unwind`.

**Comment by inquisitivecrystal** [comment]
> Is it not a breaking change to turn documented panics into something else?


I'm definitely not an expert, but I would think that making something that didn't work start working would be allowed. Of course, if it broke a lot of people's use cases, it's somewhat irrelevant...

**Comment by lopopolo** [comment]
This change alters the semantics of the `env::var_os` API to mask a previously documented and observable panic due to a limitation of the underlying platform. This may be the right change to make for `env::var_os`, but without a replacement API, maybe `env::try_var_os`, less information is available to callers than before.

**Comment by joshtriplett** [comment]
We reviewed this in today's @rust-lang/libs-api meeting.

We appreciate the specific use case of needing to provide more nuanced validation for the purposes of implementing another API. However, we feel like the changes previously made here will be what the majority of users will expect; in particular, it looks like from the implementation of Artichoke that you're actually using the same semantic for keys containing `=` (returning the same result as if they didn't exist). Given that, we generally felt like doing this kind of validation separately in advance (or afterward iff the result is None) seems reasonable.

That said, we'd also be sympathetic to improving the convenience of working with OsStr (cc @dtolnay). And if there's an additional semantic here that's OS-specific (rather than something reasonably easy to check for all platforms such as containing `=` or `\0`), we'd be willing to consider a method for that, if such a method would actually provide meaningful value.

**Comment by lopopolo** [comment]
Thanks @joshtriplett and Rust Libs API team for taking a look. I do agree that the changes made here better serve most users and what I'm hoping to do is a bit niche.

I'd be super excited to see improvements for the ergonomics of `OsStr`. I think I've seen an idea for getting something like the pattern API implemented for `OsStr` on internals a couple of times. Being able to do `contains` checks (like for this env var name and value case) and `starts_with` checks (like for checking for `-` and `--` flags and switches in parsing command line arguments) would go a long way to avoiding round tripping through `&str` or `&[u8]`.
