### PR TITLE
add hint to fix error for immutable ref in arg

### LINKED ISSUE #36412: Possible improvement in mutability error message
Talking to some folks at RustConf one particularly confusing case was "where do I put `mut`?" to get mutability. We've got a few locations, to place it (e.g. on the binding or in the type of a reference), and this can be confusing when you're just starting out. As a specific case, consider:

``` rust
pub fn foo(mut a: &String)  {
    a.push_str("foo");
}
```

which when compiled yields the error message:

```
error: cannot borrow immutable borrowed content `*a` as mutable
 --> foo.rs:2:5
  |
2 |     a.push_str("foo");
  |     ^

error: aborting due to previous error
```

To a beginner this can be quite confusing because `a` _is_ mutable, but the fix here is to take `&mut String`, not `&String`. Perhaps we can detect this and provide a more tailored error message for cases like this?

cc @jonathandturner

### PR DESCRIPTION
**Pull request by mikhail-m1**
fix  #36412 part of #35233
r? @jonathandturner

### CODE REVIEW

**Comment by mikhail-m1** [comment]
error: the lock file needs to be updated but --locked was passed to prevent this

**Comment by mikhail-m1** [comment]
@jonathandturner How to rerun checks?

**Comment by jonathandturner** [comment]
The errors look pretty good.

r? @nikomatsakis to take a look at the implementation side

I don't think you need to worry about travis, as long as it passes bors.

File: src/librustc_borrowck/borrowck/mod.rs [hunk 1]
```diff
@@ -1135,6 +1093,102 @@ impl<'a, 'tcx> BorrowckCtxt<'a, 'tcx> {
...
+                        if let Some(ref arg) = function.inputs.iter()
+                            .find(|ref arg| arg.pat.id == local_id && arg.to_self().is_none()) {
+                            if let hir::TyRptr(Some(lifetime), hir::MutTy { ref ty, ..}) = arg.ty
+                                .node {
+                                if let Ok(snippet) = self.tcx.sess.codemap()
+                                    .span_to_snippet(ty.span) {
+                                    if let Ok(lifetime_snippet) = self.tcx.sess.codemap()
+                                        .span_to_snippet(lifetime.span) {
+                                            db.span_label(arg.ty.span,
+                                                          &format!("use `{} mut {}`",
```
Comment (nikomatsakis) [inline src/librustc_borrowck/borrowck/mod.rs]: Nit: I think this should be `&{} mut {}`, not `{} mut {}`, so that the final message is "use `&'a mut Foo`, not "use `'a mut Foo`". The latter seems confusing. Also, the message seems incomplete: maybe "use `&{} mut {}` here to make mutable"?

File: src/librustc_borrowck/borrowck/mod.rs [hunk 2]
```diff
@@ -1135,6 +1093,102 @@ impl<'a, 'tcx> BorrowckCtxt<'a, 'tcx> {
...
+                }
+            }
+            _ => {
+                let mut cmt = &err.cmt;
+                while let Categorization::Deref(ref inner_cmt, ..) = cmt.cat {
+                    cmt = inner_cmt;
+                }
+                if let Categorization::Local(local_id) = cmt.cat {
+                    let parent = self.tcx.map.get_parent_node(local_id);
+                    let may_be_function = match self.tcx.map.get(parent) {
```
Comment (nikomatsakis) [inline src/librustc_borrowck/borrowck/mod.rs]: I think you can use this funky `FnLikeNode` thing. Something like this instead of that big match:

```rust
use rustc::hir::map::blocks::FnLikeNode;
let opt_function =
    FnLikeNode::from_node(self.tcx.map.get(parent))
    .map(|fn_like| fn_like.decl());
```

I also changed the name of `may_be_function` to `opt_function`, which I find a bit more obvious (since in Rust the type is `Option`, not `Maybe`).

File: src/librustc_borrowck/borrowck/mod.rs [hunk 3]
```diff
@@ -1135,6 +1093,102 @@ impl<'a, 'tcx> BorrowckCtxt<'a, 'tcx> {
...
+                        hir::map::NodeTraitItem(item) =>
+                            if let hir::MethodTraitItem(ref sig, ..) = item.node {
+                                Some(&sig.decl)
+                            } else {
+                                None
+                            },
+                        _ => None
+                    };
+
+                    if let Some(function) = may_be_function {
```
Comment (nikomatsakis) [inline src/librustc_borrowck/borrowck/mod.rs]: Nit: variables of this type are usually called `fn_decl` or `decl`, not `function`, at least by me (since they are a `FnDecl`)

File: src/librustc_borrowck/borrowck/mod.rs [hunk 4]
```diff
@@ -1135,6 +1093,102 @@ impl<'a, 'tcx> BorrowckCtxt<'a, 'tcx> {
...
+                                if snippet.starts_with("&") {
+                                    db.span_label(arg.ty.span,
+                                                  &format!( "use `{}` here to make mutable",
+                                                            snippet.replace("&", "&mut ")));
+                                }
+                            }
+                        }
+                    }
+                }
+                if let Categorization::Local(local_id) = err.cmt.cat {
```
Comment (nikomatsakis) [inline src/librustc_borrowck/borrowck/mod.rs]: It seems to me that we only want to execute one of these two ifs -- but I'm not clear on why we never wind up executing both of them. For example, what would this test do?

```rust
fn foo(x: &'static i32, y: &'static i32) {
    x = y;
}
```

Comment (nikomatsakis) [inline src/librustc_borrowck/borrowck/mod.rs]: Basically the first if says "if you are mutating something like `x`, `*x`, or `*****x` where `x` is a varibale of type `&T`" and the second if says "if you are mutating somthing like `x`", but since the first does not require at least one `*` these are not mutually exclusive, right?

Comment (nikomatsakis) [inline src/librustc_borrowck/borrowck/mod.rs]: As an aside, I think it would be to pull the bodies of these ifs into helper methods with a nice name, like `fn give_suggestion_to_make_referent_mutable()` (for the first one) and `fn give_suggestion_to_make_binding_mutable()` (for the second one). Also some comments, ideally with code examples, is also helpful in these kinds of situations (or at least links to test cases) -- basically explaining "if the input program is this, we want this error"

**Review by nikomatsakis — CHANGES_REQUESTED** [review]
This is an awesome error message! I left some comments -- I'm particularly interested in whether we can wind up producing multiple errors for a single input with the code structured the way it is, as well as improving the message for the case where a named lifetime is used.

File: src/librustc_borrowck/borrowck/mod.rs (hunk 4 above)
Comment (mikhail-m1) [inline src/librustc_borrowck/borrowck/mod.rs]: for x=y  other error produced and note_and_explain_mutbl_error is not called, output is 
```
1 | fn foo(x: &'static i32, y: &'static i32) {
  |        - first assignment to `x`
2 |     x = y;
  |     ^^^^^ re-assignment of immutable variable
```

You right the ifs are not mutually exclusive, but I cannot find example executes both of them. May be I should prevent match first of them with x. Actually I'm going to support cases with local variables by first case too, but it's more complicated and now matching with *x is enough.

Comment (mikhail-m1) [inline src/librustc_borrowck/borrowck/mod.rs]: example for **x
```
fn main() {
    let mut foo = &"a".to_string();
    let mut bar = &mut foo;
    bar.push_str("foo2");
}
```

**Comment by mikhail-m1** [comment]
@nikomatsakis I fixed nits and leave only *x case, you can find some comments in review. I don't create separate functions for now, and made cases mutually exclusive

**Review by nikomatsakis — APPROVED** [review]

**Comment by nikomatsakis** [comment]
@mikhail-m1 looks great :)
