### PR TITLE
Fix late-bound lifetime closure ICEs in HIR typeck and MIR borrowck

### LINKED ISSUE #103736: ICE when using `closure_lifetime_binder` lifetime inside closure body
### Code

```Rust
#![feature(closure_lifetime_binder)]

fn main() {
    let _ = for<'a> || -> () {
        let _: &'a bool = &true;
    };
}
```

### Meta

`rustc --version --verbose`:
```
rustc 1.66.0-nightly (9565dfeb4 2022-10-28)
binary: rustc
commit-hash: 9565dfeb4e6225177bbe78f18cd48a7982f34401
commit-date: 2022-10-28
host: x86_64-unknown-linux-gnu
release: 1.66.0-nightly
LLVM version: 15.0.2
```

### Error output

```
thread '<unnamed>' panicked at 'assertion failed: !value.has_escaping_bound_vars()', /rustc/9565dfeb4e6225177bbe78f18cd48a7982f34401/compiler/rustc_middle/src/ty/sty.rs:982:9
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
stack backtrace:
   0:     0x7facd5781850 - std::backtrace_rs::backtrace::libunwind::trace::hcb08f530cff40cca
                               at /rustc/9565dfeb4e6225177bbe78f18cd48a7982f34401/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x7facd5781850 - std::backtrace_rs::backtrace::trace_unsynchronized::hddb2a2d491e7ca18
                               at /rustc/9565dfeb4e6225177bbe78f18cd48a7982f34401/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7facd5781850 - std::sys_common::backtrace::_print_fmt::h7bfa3f787e3397d9
                               at /rustc/9565dfeb4e6225177bbe78f18cd48a7982f34401/library/std/src/sys_common/backtrace.rs:65:5
   3:     0x7facd5781850 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hb44d7c7e3209d54f
                               at /rustc/9565dfeb4e6225177bbe78f18cd48a7982f34401/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x7facd57dd7ae - core::fmt::write::heff7f33d40f68a07
                               at /rustc/9565dfeb4e6225177bbe78f18cd48a7982f34401/library/core/src/fmt/mod.rs:1209:17
   5:     0x7facd57719c5 - std::io::Write::write_fmt::h481263232c739287
                               at /rustc/9565dfeb4e6225177bbe78f18cd48a7982f34401/library/std/src/io/mod.rs:1682:15
   6:     0x7facd5781615 - std::sys_common::backtrace::_print::hbb3318f3b9d95c27
                               at /rustc/9565dfeb4e6225177bbe78f18cd48a7982f34401/library/std/src/sys_common/backtrace.rs:47:5
   7:     0x7facd5781615 - std::sys_common::backtrace::print::h09b2314a2aa0e962
                               at /rustc/9565dfeb4e6225177bbe78f18cd48a7982f34401/library/std/src/sys_common/backtrace.rs:34:9
   8:     0x7facd578441f - std::panicking::default_hook::{{closure}}::ha4a56aab942e9c60
                               at /rustc/9565dfeb4e6225177bbe78f18cd48a7982f34401/library/std/src/panicking.rs:267:22
   9:     0x7facd578415a - std::panicking::default_hook::h100359da3e3d3584
                               at /rustc/9565dfeb4e6225177bbe78f18cd48a7982f34401/library/std/src/panicking.rs:286:9
  10:     0x7facd5784c28 - std::panicking::rust_panic_with_hook::h25048bbf4fde4742
                               at /rustc/9565dfeb4e6225177bbe78f18cd48a7982f34401/library/std/src/panicking.rs:688:13
  11:     0x7facd5784981 - std::panicking::begin_panic_handler::{{closure}}::h41565a90d0d6688d
                               at /rustc/9565dfeb4e6225177bbe78f18cd48a7982f34401/library/std/src/panicking.rs:577:13
  12:     0x7facd5781cfc - std::sys_common::backtrace::__rust_end_short_backtrace::h8f85f375182a95c1
                               at /rustc/9565dfeb4e6225177bbe78f18cd48a7982f34401/library/std/src/sys_common/backtrace.rs:137:18
  13:     0x7facd57846e2 - rust_begin_unwind
                               at /rustc/9565dfeb4e6225177bbe78f18cd48a7982f34401/library/std/src/panicking.rs:575:5
  14:     0x7facd57da193 - core::panicking::panic_fmt::h68463fb299862f1f
                               at /rustc/9565dfeb4e6225177bbe78f18cd48a7982f34401/library/core/src/panicking.rs:65:14
  15:     0x7facd57da26d - core::panicking::panic::hf3ad889fdb69a756
                               at /rustc/9565dfeb4e6225177bbe78f18cd48a7982f34401/library/core/src/panicking.rs:115:5
  16:     0x7facd6e6c7f5 - <rustc_hir_typeck[5921ba7e3d7ef2c]::fn_ctxt::FnCtxt>::register_wf_obligation
  17:     0x7facd6a8b570 - <rustc_hir_typeck[5921ba7e3d7ef2c]::gather_locals::GatherLocalsVisitor>::declare
  18:     0x7facd6a8af67 - <rustc_hir_typeck[5921ba7e3d7ef2c]::gather_locals::GatherLocalsVisitor as rustc_hir[4c69b9408057528b]::intravisit::Visitor>::visit_expr
  19:     0x7facd787b5eb - rustc_hir_typeck[5921ba7e3d7ef2c]::check::check_fn
  20:     0x7facd6eee226 - <rustc_hir_typeck[5921ba7e3d7ef2c]::fn_ctxt::FnCtxt>::check_expr_closure
  21:     0x7facd6e536f1 - <rustc_hir_typeck[5921ba7e3d7ef2c]::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
  22:     0x7facd6e92a62 - <rustc_hir_typeck[5921ba7e3d7ef2c]::fn_ctxt::FnCtxt>::check_decl
  23:     0x7facd6e8fada - <rustc_hir_typeck[5921ba7e3d7ef2c]::fn_ctxt::FnCtxt>::check_block_with_expected
  24:     0x7facd6e4fac0 - <rustc_hir_typeck[5921ba7e3d7ef2c]::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
  25:     0x7facd787e246 - <rustc_hir_typeck[5921ba7e3d7ef2c]::fn_ctxt::FnCtxt>::check_return_expr
  26:     0x7facd787bb4a - rustc_hir_typeck[5921ba7e3d7ef2c]::check::check_fn
  27:     0x7facd786726d - rustc_hir_typeck[5921ba7e3d7ef2c]::typeck
  28:     0x7facd6e198d3 - <rustc_query_system[6a6350e27c5a6f25]::dep_graph::graph::DepGraph<rustc_middle[f64f4db409ba5abd]::dep_graph::dep_node::DepKind>>::with_task::<rustc_middle[f64f4db409ba5abd]::ty::context::TyCtxt, rustc_span[4a20dfc976afaa8c]::def_id::LocalDefId, &rustc_middle[f64f4db409ba5abd]::ty::context::TypeckResults>
  29:     0x7facd6e11f61 - rustc_query_system[6a6350e27c5a6f25]::query::plumbing::try_execute_query::<rustc_query_impl[1405fd9b45468ea]::plumbing::QueryCtxt, rustc_query_system[6a6350e27c5a6f25]::query::caches::DefaultCache<rustc_span[4a20dfc976afaa8c]::def_id::LocalDefId, &rustc_middle[f64f4db409ba5abd]::ty::context::TypeckResults>>
  30:     0x7facd8106ec8 - rustc_data_structures[e5a688f0adb11ef5]::sync::par_for_each_in::<&[rustc_span[4a20dfc976afaa8c]::def_id::LocalDefId], <rustc_middle[f64f4db409ba5abd]::hir::map::Map>::par_body_owners<rustc_hir_typeck[5921ba7e3d7ef2c]::typeck_item_bodies::{closure#0}>::{closure#0}>
  31:     0x7facd8106ba3 - rustc_hir_typeck[5921ba7e3d7ef2c]::typeck_item_bodies
  32:     0x7facd80018a9 - <rustc_query_system[6a6350e27c5a6f25]::dep_graph::graph::DepGraph<rustc_middle[f64f4db409ba5abd]::dep_graph::dep_node::DepKind>>::with_task::<rustc_middle[f64f4db409ba5abd]::ty::context::TyCtxt, (), ()>
  33:     0x7facd800084d - rustc_query_system[6a6350e27c5a6f25]::query::plumbing::try_execute_query::<rustc_query_impl[1405fd9b45468ea]::plumbing::QueryCtxt, rustc_query_system[6a6350e27c5a6f25]::query::caches::DefaultCache<(), ()>>
  34:     0x7facd80001d7 - rustc_query_system[6a6350e27c5a6f25]::query::plumbing::get_query::<rustc_query_impl[1405fd9b45468ea]::queries::typeck_item_bodies, rustc_query_impl[1405fd9b45468ea]::plumbing::QueryCtxt>
  35:     0x7facd6d13c8a - <rustc_session[86f59dd04d0dca5e]::session::Session>::time::<(), rustc_hir_analysis[2c96763b7984a461]::check_crate::{closure#7}>
  36:     0x7facd6d12e3b - rustc_hir_analysis[2c96763b7984a461]::check_crate
  37:     0x7facd6d12a6b - rustc_interface[1b8cc14ea0a1d58e]::passes::analysis
  38:     0x7facd815ce4e - <rustc_query_system[6a6350e27c5a6f25]::dep_graph::graph::DepGraph<rustc_middle[f64f4db409ba5abd]::dep_graph::dep_node::DepKind>>::with_task::<rustc_middle[f64f4db409ba5abd]::ty::context::TyCtxt, (), core[a97f803d89ea326c]::result::Result<(), rustc_errors[ab181c9b86d7e982]::ErrorGuaranteed>>
  39:     0x7facd815c1c4 - rustc_query_system[6a6350e27c5a6f25]::query::plumbing::try_execute_query::<rustc_query_impl[1405fd9b45468ea]::plumbing::QueryCtxt, rustc_query_system[6a6350e27c5a6f25]::query::caches::DefaultCache<(), core[a97f803d89ea326c]::result::Result<(), rustc_errors[ab181c9b86d7e982]::ErrorGuaranteed>>>
  40:     0x7facd815bc47 - rustc_query_system[6a6350e27c5a6f25]::query::plumbing::get_query::<rustc_query_impl[1405fd9b45468ea]::queries::analysis, rustc_query_impl[1405fd9b45468ea]::plumbing::QueryCtxt>
  41:     0x7facd7c9e22d - <rustc_interface[1b8cc14ea0a1d58e]::passes::QueryContext>::enter::<rustc_driver[ac8a6fe4a2afd1b]::run_compiler::{closure#1}::{closure#2}::{closure#3}, core[a97f803d89ea326c]::result::Result<(), rustc_errors[ab181c9b86d7e982]::ErrorGuaranteed>>
  42:     0x7facd7c9a6df - <rustc_interface[1b8cc14ea0a1d58e]::interface::Compiler>::enter::<rustc_driver[ac8a6fe4a2afd1b]::run_compiler::{closure#1}::{closure#2}, core[a97f803d89ea326c]::result::Result<core[a97f803d89ea326c]::option::Option<rustc_interface[1b8cc14ea0a1d58e]::queries::Linker>, rustc_errors[ab181c9b86d7e982]::ErrorGuaranteed>>
  43:     0x7facd7c92222 - rustc_span[4a20dfc976afaa8c]::with_source_map::<core[a97f803d89ea326c]::result::Result<(), rustc_errors[ab181c9b86d7e982]::ErrorGuaranteed>, rustc_interface[1b8cc14ea0a1d58e]::interface::run_compiler<core[a97f803d89ea326c]::result::Result<(), rustc_errors[ab181c9b86d7e982]::ErrorGuaranteed>, rustc_driver[ac8a6fe4a2afd1b]::run_compiler::{closure#1}>::{closure#0}::{closure#1}>
  44:     0x7facd7c91d19 - <scoped_tls[ce0abc247ca248a0]::ScopedKey<rustc_span[4a20dfc976afaa8c]::SessionGlobals>>::set::<rustc_interface[1b8cc14ea0a1d58e]::interface::run_compiler<core[a97f803d89ea326c]::result::Result<(), rustc_errors[ab181c9b86d7e982]::ErrorGuaranteed>, rustc_driver[ac8a6fe4a2afd1b]::run_compiler::{closure#1}>::{closure#0}, core[a97f803d89ea326c]::result::Result<(), rustc_errors[ab181c9b86d7e982]::ErrorGuaranteed>>
  45:     0x7facd7c91328 - std[e720b13db21e6030]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[1b8cc14ea0a1d58e]::util::run_in_thread_pool_with_globals<rustc_interface[1b8cc14ea0a1d58e]::interface::run_compiler<core[a97f803d89ea326c]::result::Result<(), rustc_errors[ab181c9b86d7e982]::ErrorGuaranteed>, rustc_driver[ac8a6fe4a2afd1b]::run_compiler::{closure#1}>::{closure#0}, core[a97f803d89ea326c]::result::Result<(), rustc_errors[ab181c9b86d7e982]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[a97f803d89ea326c]::result::Result<(), rustc_errors[ab181c9b86d7e982]::ErrorGuaranteed>>
  46:     0x7facd7c9104c - <<std[e720b13db21e6030]::thread::Builder>::spawn_unchecked_<rustc_interface[1b8cc14ea0a1d58e]::util::run_in_thread_pool_with_globals<rustc_interface[1b8cc14ea0a1d58e]::interface::run_compiler<core[a97f803d89ea326c]::result::Result<(), rustc_errors[ab181c9b86d7e982]::ErrorGuaranteed>, rustc_driver[ac8a6fe4a2afd1b]::run_compiler::{closure#1}>::{closure#0}, core[a97f803d89ea326c]::result::Result<(), rustc_errors[ab181c9b86d7e982]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[a97f803d89ea326c]::result::Result<(), rustc_errors[ab181c9b86d7e982]::ErrorGuaranteed>>::{closure#1} as core[a97f803d89ea326c]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  47:     0x7facd96444f3 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h777accc1e1ec51f4
                               at /rustc/9565dfeb4e6225177bbe78f18cd48a7982f34401/library/alloc/src/boxed.rs:1987:9
  48:     0x7facd96444f3 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h95dfcec2e5bf9e0f
                               at /rustc/9565dfeb4e6225177bbe78f18cd48a7982f34401/library/alloc/src/boxed.rs:1987:9
  49:     0x7facd96444f3 - std::sys::unix::thread::Thread::new::thread_start::hb399bf19376dd98b
                               at /rustc/9565dfeb4e6225177bbe78f18cd48a7982f34401/library/std/src/sys/unix/thread.rs:108:17
  50:     0x7facd54dde2d - start_thread
  51:     0x7facd55631b0 - __clone3
  52:                0x0 - <unknown>
```

</p>
</details>

### LINKED ISSUE #103771: ICE normalizing binder for closure
### Code

```Rust
#![feature(closure_lifetime_binder)]
fn main() {
    for<'a> || -> () {
        for<'c> |_: &'a ()| -> () {
        }
    };
}
```

### Error output

```
thread 'rustc' panicked at 'Normalizing Binder(([&'a ()]; c_variadic: false)->(), [Region(BrNamed(DefId(0:7 ~ amina[00f1]::main::{closure#0}::{closure#0}::'c), 'c))]) without wrapping in a `Binder`', /rustc/0da281b6068a7d889ae89a9bd8991284cc9b7535/compiler/rustc_trait_selection/src/traits/project.rs:450:9
```

<details><summary><strong>Full output including backtrace</strong></summary>
<p>

```
thread 'rustc' panicked at 'Normalizing Binder(([&'a ()]; c_variadic: false)->(), [Region(BrNamed(DefId(0:7 ~ amina[00f1]::main::{closure#0}::{closure#0}::'c), 'c))]) without wrapping in a `Binder`', /rustc/0da281b6068a7d889ae89a9bd8991284cc9b7535/compiler/rustc_trait_selection/src/traits/project.rs:450:9
stack backtrace:
   0:        0x108f348a2 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h98e7719cdb057d8f
   1:        0x108f8c74a - core::fmt::write::he324e6f3a7ef7ed0
   2:        0x108f2697c - std::io::Write::write_fmt::h295c914c323e508a
   3:        0x108f3466a - std::sys_common::backtrace::print::hb2f2bd76d0a1d9b2
   4:        0x108f37a76 - std::panicking::default_hook::{{closure}}::h7f2a23a911934152
   5:        0x108f377c7 - std::panicking::default_hook::h576cf5867894044c
   6:        0x11755262d - rustc_driver[ba5c792b9438c2b]::DEFAULT_HOOK::{closure#0}::{closure#0}
   7:        0x108f38271 - std::panicking::rust_panic_with_hook::hf0781b554a936fbf
   8:        0x108f38003 - std::panicking::begin_panic_handler::{{closure}}::h8d2525e276d552d8
   9:        0x108f34d38 - std::sys_common::backtrace::__rust_end_short_backtrace::hf3badbbd5492e2d6
  10:        0x108f37ccd - _rust_begin_unwind
  11:        0x108fb91b3 - core::panicking::panic_fmt::h15d4409e62dc090a
  12:        0x119e69dab - <rustc_trait_selection[9c2b695c7caa8425]::traits::project::AssocTypeNormalizer>::fold::<rustc_middle[298407787cc28eff]::ty::sty::Binder<rustc_middle[298407787cc28eff]::ty::sty::FnSig>>
  13:        0x119e80346 - rustc_trait_selection[9c2b695c7caa8425]::traits::project::normalize::<rustc_middle[298407787cc28eff]::ty::sty::Binder<rustc_middle[298407787cc28eff]::ty::sty::FnSig>>
  14:        0x119ee32b6 - <rustc_infer[b40902abbc4e8850]::infer::InferCtxt as rustc_trait_selection[9c2b695c7caa8425]::infer::InferCtxtExt>::partially_normalize_associated_types_in::<rustc_middle[298407787cc28eff]::ty::sty::Binder<rustc_middle[298407787cc28eff]::ty::sty::FnSig>>
  15:        0x119e8e808 - <rustc_hir_typeck[82128e1af9fabaca]::inherited::Inherited>::normalize_associated_types_in::<rustc_middle[298407787cc28eff]::ty::sty::Binder<rustc_middle[298407787cc28eff]::ty::sty::FnSig>>
  16:        0x119daed4b - <rustc_hir_typeck[82128e1af9fabaca]::fn_ctxt::FnCtxt>::supplied_sig_of_closure
  17:        0x119dac8cb - <rustc_hir_typeck[82128e1af9fabaca]::fn_ctxt::FnCtxt>::check_expr_closure
  18:        0x119dafe14 - <rustc_hir_typeck[82128e1af9fabaca]::fn_ctxt::FnCtxt>::check_expr_kind
  19:        0x119d59556 - <rustc_hir_typeck[82128e1af9fabaca]::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
  20:        0x119d6f655 - <rustc_hir_typeck[82128e1af9fabaca]::fn_ctxt::FnCtxt>::check_block_with_expected
  21:        0x119db07a8 - <rustc_hir_typeck[82128e1af9fabaca]::fn_ctxt::FnCtxt>::check_expr_kind
  22:        0x119d59556 - <rustc_hir_typeck[82128e1af9fabaca]::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
  23:        0x119d5a59a - <rustc_hir_typeck[82128e1af9fabaca]::fn_ctxt::FnCtxt>::check_return_expr
  24:        0x119ecbd6e - rustc_hir_typeck[82128e1af9fabaca]::check::check_fn
  25:        0x119dacdda - <rustc_hir_typeck[82128e1af9fabaca]::fn_ctxt::FnCtxt>::check_expr_closure
  26:        0x119dafe14 - <rustc_hir_typeck[82128e1af9fabaca]::fn_ctxt::FnCtxt>::check_expr_kind
  27:        0x119d59556 - <rustc_hir_typeck[82128e1af9fabaca]::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
  28:        0x119d6eeb5 - <rustc_hir_typeck[82128e1af9fabaca]::fn_ctxt::FnCtxt>::check_stmt
  29:        0x119d6f5ff - <rustc_hir_typeck[82128e1af9fabaca]::fn_ctxt::FnCtxt>::check_block_with_expected
  30:        0x119db07a8 - <rustc_hir_typeck[82128e1af9fabaca]::fn_ctxt::FnCtxt>::check_expr_kind
  31:        0x119d59556 - <rustc_hir_typeck[82128e1af9fabaca]::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
  32:        0x119d5a59a - <rustc_hir_typeck[82128e1af9fabaca]::fn_ctxt::FnCtxt>::check_return_expr
  33:        0x119ecbd6e - rustc_hir_typeck[82128e1af9fabaca]::check::check_fn
  34:        0x119e9265c - rustc_hir_typeck[82128e1af9fabaca]::typeck
  35:        0x11ad3bfb9 - rustc_query_system[fd3d689380a50de4]::query::plumbing::try_execute_query::<rustc_query_impl[f77634870212a75e]::plumbing::QueryCtxt, rustc_query_system[fd3d689380a50de4]::query::caches::DefaultCache<rustc_span[73e074df7cba0abf]::def_id::LocalDefId, &rustc_middle[298407787cc28eff]::ty::context::TypeckResults>>
  36:        0x11ae3d04c - rustc_query_system[fd3d689380a50de4]::query::plumbing::get_query::<rustc_query_impl[f77634870212a75e]::queries::typeck, rustc_query_impl[f77634870212a75e]::plumbing::QueryCtxt>
  37:        0x119ebbb6b - rustc_data_structures[445d045225b5bae3]::sync::par_for_each_in::<&[rustc_span[73e074df7cba0abf]::def_id::LocalDefId], <rustc_middle[298407787cc28eff]::hir::map::Map>::par_body_owners<rustc_hir_typeck[82128e1af9fabaca]::typeck_item_bodies::{closure#0}>::{closure#0}>
  38:        0x119e8fb8d - rustc_hir_typeck[82128e1af9fabaca]::typeck_item_bodies
  39:        0x11add14a9 - rustc_query_system[fd3d689380a50de4]::query::plumbing::try_execute_query::<rustc_query_impl[f77634870212a75e]::plumbing::QueryCtxt, rustc_query_system[fd3d689380a50de4]::query::caches::DefaultCache<(), ()>>
  40:        0x11ae31a39 - rustc_query_system[fd3d689380a50de4]::query::plumbing::get_query::<rustc_query_impl[f77634870212a75e]::queries::typeck_item_bodies, rustc_query_impl[f77634870212a75e]::plumbing::QueryCtxt>
  41:        0x119fb4ed4 - <rustc_session[43d2d941ace548e5]::session::Session>::time::<(), rustc_hir_analysis[3f5a3f8b91adb05]::check_crate::{closure#7}>
  42:        0x119f6546f - rustc_hir_analysis[3f5a3f8b91adb05]::check_crate
  43:        0x11762afda - rustc_interface[a666f6d755ed9279]::passes::analysis
  44:        0x11adc326c - rustc_query_system[fd3d689380a50de4]::query::plumbing::try_execute_query::<rustc_query_impl[f77634870212a75e]::plumbing::QueryCtxt, rustc_query_system[fd3d689380a50de4]::query::caches::DefaultCache<(), core[13371b8ce97f01bb]::result::Result<(), rustc_errors[b0e16a209d58ca7d]::ErrorGuaranteed>>>
  45:        0x11ae3d3f9 - rustc_query_system[fd3d689380a50de4]::query::plumbing::get_query::<rustc_query_impl[f77634870212a75e]::queries::analysis, rustc_query_impl[f77634870212a75e]::plumbing::QueryCtxt>
  46:        0x1174e1296 - <rustc_interface[a666f6d755ed9279]::passes::QueryContext>::enter::<rustc_driver[ba5c792b9438c2b]::run_compiler::{closure#1}::{closure#2}::{closure#3}, core[13371b8ce97f01bb]::result::Result<(), rustc_errors[b0e16a209d58ca7d]::ErrorGuaranteed>>
  47:        0x117525a4d - rustc_span[73e074df7cba0abf]::with_source_map::<core[13371b8ce97f01bb]::result::Result<(), rustc_errors[b0e16a209d58ca7d]::ErrorGuaranteed>, rustc_interface[a666f6d755ed9279]::interface::run_compiler<core[13371b8ce97f01bb]::result::Result<(), rustc_errors[b0e16a209d58ca7d]::ErrorGuaranteed>, rustc_driver[ba5c792b9438c2b]::run_compiler::{closure#1}>::{closure#0}::{closure#1}>
  48:        0x11751534c - <scoped_tls[c17fceff1b2b43d8]::ScopedKey<rustc_span[73e074df7cba0abf]::SessionGlobals>>::set::<rustc_interface[a666f6d755ed9279]::interface::run_compiler<core[13371b8ce97f01bb]::result::Result<(), rustc_errors[b0e16a209d58ca7d]::ErrorGuaranteed>, rustc_driver[ba5c792b9438c2b]::run_compiler::{closure#1}>::{closure#0}, core[13371b8ce97f01bb]::result::Result<(), rustc_errors[b0e16a209d58ca7d]::ErrorGuaranteed>>
  49:        0x1174e4e5a - std[8878bd7dd366d71b]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[a666f6d755ed9279]::util::run_in_thread_pool_with_globals<rustc_interface[a666f6d755ed9279]::interface::run_compiler<core[13371b8ce97f01bb]::result::Result<(), rustc_errors[b0e16a209d58ca7d]::ErrorGuaranteed>, rustc_driver[ba5c792b9438c2b]::run_compiler::{closure#1}>::{closure#0}, core[13371b8ce97f01bb]::result::Result<(), rustc_errors[b0e16a209d58ca7d]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[13371b8ce97f01bb]::result::Result<(), rustc_errors[b0e16a209d58ca7d]::ErrorGuaranteed>>
  50:        0x1174caf7b - <<std[8878bd7dd366d71b]::thread::Builder>::spawn_unchecked_<rustc_interface[a666f6d755ed9279]::util::run_in_thread_pool_with_globals<rustc_interface[a666f6d755ed9279]::interface::run_compiler<core[13371b8ce97f01bb]::result::Result<(), rustc_errors[b0e16a209d58ca7d]::ErrorGuaranteed>, rustc_driver[ba5c792b9438c2b]::run_compiler::{closure#1}>::{closure#0}, core[13371b8ce97f01bb]::result::Result<(), rustc_errors[b0e16a209d58ca7d]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[13371b8ce97f01bb]::result::Result<(), rustc_errors[b0e16a209d58ca7d]::ErrorGuaranteed>>::{closure#1} as core[13371b8ce97f01bb]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  51:        0x108f41387 - std::sys::unix::thread::Thread::new::thread_start::hfd54df40dd14130e
  52:     0x7ff814d514e1 - __pthread_start

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.66.0-nightly (0da281b60 2022-10-27) running on x86_64-apple-darwin

query stack during panic:
#0 [typeck] type-checking `main`
#1 [typeck_item_bodies] type-checking all item bodies
#2 [analysis] running analysis passes on this crate
end of query stack
```

</p>
</details>

### Version

```
rustc 1.66.0-nightly (0da281b60 2022-10-27)
binary: rustc
commit-hash: 0da281b6068a7d889ae89a9bd8991284cc9b7535
commit-date: 2022-10-27
host: x86_64-apple-darwin
release: 1.66.0-nightly
LLVM version: 15.0.2
```

### Bisect results

This goes all the way back to f1a8854f9be2e5cad764d630a53d26c7b72f8162, when #98705 enabled this syntax for closures (tracking issue: #97362).

### PR DESCRIPTION
**Pull request by compiler-errors**
During HIR typeck, we need to teach astconv to treat late-bound regions within a closure body as free, fixing escaping bound vars ICEs in both of the issues below. 

However, this then gets us to MIR borrowck, which itself needs to be taught how to instantiate free region vids for late-bound regions that come from items that _aren't_ the typeck root (for now, just closures).

Fixes #103771
Fixes #103736

### CODE REVIEW

**Comment by cjgillot** [comment]
@compiler-errors are you missing part of the first commit?  The diff is unrelated to the message.

**Comment by compiler-errors** [comment]
@cjgillot I didn't forget anything, though I could've named it better.

File: compiler/rustc_borrowck/src/universal_regions.rs [hunk 1]
```diff
@@ -444,12 +450,9 @@ impl<'cx, 'tcx> UniversalRegionsBuilder<'cx, 'tcx> {
...
         );
-        // Converse of above, if this is a function then the late-bound regions declared on its
-        // signature are local to the fn.
-        if self.mir_def.did.to_def_id() == typeck_root_def_id {
-            self.infcx
-                .replace_late_bound_regions_with_nll_infer_vars(self.mir_def.did, &mut indices);
-        }
+        // Converse of above, if this is a function/closure then the late-bound regions declared on its
+        // signature are local.
+        self.infcx.replace_late_bound_regions_with_nll_infer_vars(self.mir_def.did, &mut indices);
```
Comment (cjgillot) [inline compiler/rustc_borrowck/src/universal_regions.rs:455]: This may register free regions that come from outer bodies as "local". Is this correct?
The comment probably needs to be updated.

File: compiler/rustc_borrowck/src/universal_regions.rs [hunk 2]
```diff
@@ -803,21 +805,31 @@ impl<'tcx> UniversalRegionIndices<'tcx> {
...
+fn for_each_late_bound_region_in_scope<'tcx>(
     tcx: TyCtxt<'tcx>,
-    fn_def_id: DefId,
+    mut mir_def_id: LocalDefId,
     mut f: impl FnMut(ty::Region<'tcx>),
 ) {
-    if let Some(late_bounds) = tcx.is_late_bound_map(fn_def_id.expect_local()) {
-        for &region_def_id in late_bounds.iter() {
-            let name = tcx.item_name(region_def_id.to_def_id());
+    let typeck_root_def_id = tcx.typeck_root_def_id(mir_def_id.to_def_id());
```
[the remark this answers is not in the document]
Comment (compiler-errors) [reply compiler/rustc_borrowck/src/universal_regions.rs:816]: That doesn't loop over the root def id, but stops one def id before it -- I'm not sure if I understand?

File: compiler/rustc_middle/src/ty/context.rs [hunk 3]
```diff
@@ -2895,9 +2895,7 @@ impl<'tcx> TyCtxt<'tcx> {
         self.mk_bound_variable_kinds(
             self.late_bound_vars_map(id.owner)
                 .and_then(|map| map.get(&id.local_id).cloned())
-                .unwrap_or_else(|| {
-                    bug!("No bound vars found for {:?} ({:?})", self.hir().node_to_string(id), id)
-                })
+                .unwrap_or_default()
```
[the remark this answers is not in the document]
Comment (compiler-errors) [reply compiler/rustc_middle/src/ty/context.rs:2898]: Because we're now walking up the whole def-id tree from the MIR body we're checking up to its typeck root, collecting all of the late-bound items, we are now calling `late_bound_vars` on intermediate items that don't have late-bound vars collected. 

I guess I could also check the def kind before calling `late_bound_vars`.

File: compiler/rustc_borrowck/src/universal_regions.rs (hunk 1 above)
Comment (compiler-errors) [reply compiler/rustc_borrowck/src/universal_regions.rs:455]: It doesn't, but only because we call `replace_late_bound_regions_with_nll_infer_vars` once before, but with the parent def-id, and we filter out infer vars that have already been added. This is somewhat confusing behavior -- I will change this call to be clearer.

Comment (compiler-errors) [reply compiler/rustc_borrowck/src/universal_regions.rs]: Replaced with a check on the def_kind for is_fn_like

File: compiler/rustc_middle/src/ty/context.rs (hunk 3 above)
[the remark this answers is not in the document]
Comment (compiler-errors) [reply compiler/rustc_middle/src/ty/context.rs]: Replaced with a check on the def_kind for is_fn_like

File: compiler/rustc_borrowck/src/universal_regions.rs (hunk 1 above)
Comment (compiler-errors) [reply compiler/rustc_borrowck/src/universal_regions.rs]: I made this a bit clearer in a subsequent commit

File: compiler/rustc_borrowck/src/universal_regions.rs [hunk 4]
```diff
@@ -241,15 +243,15 @@ impl<'tcx> UniversalRegions<'tcx> {
...
+        closure_def_id: LocalDefId,
     ) -> IndexVec<RegionVid, ty::Region<'tcx>> {
         let mut region_mapping = IndexVec::with_capacity(expected_num_vars);
         region_mapping.push(tcx.lifetimes.re_static);
         tcx.for_each_free_region(&closure_substs, |fr| {
             region_mapping.push(fr);
         });
 
-        for_each_late_bound_region_defined_on(tcx, typeck_root_def_id, |r| {
+        for_each_late_bound_region_in_recursive_scope(tcx, tcx.local_parent(closure_def_id), |r| {
```
Comment (aliemjay) [inline compiler/rustc_borrowck/src/universal_regions.rs:254]: Nit: This functions now assumes being called from the strict parent of the closure, not any higher parent. Can we make it a method on UniversalRegions and add `assert_eq!(self.len(), expected_num_vars)` and `assert_eq!(self.defining_ty.def_id(), tcx.parent(closure_def_id)`

**Review by aliemjay — APPROVED** [review]

**Comment by jackh726** [comment]
r=me with or without @aliemjay's comment

File: compiler/rustc_borrowck/src/universal_regions.rs (hunk 4 above)
Comment (compiler-errors) [reply compiler/rustc_borrowck/src/universal_regions.rs:254]: > Can we make it a method on UniversalRegions

Make what a method? `for_each_late_bound_region_in_recursive_scope`?

> and add assert_eq!(self.len(), expected_num_vars)

What's the difference between this assertion and the one that happens below?

Comment (aliemjay) [reply compiler/rustc_borrowck/src/universal_regions.rs:254]: > Make what a method?

I meant `closure_mapping`.

> What's the difference between this assertion and the one that happens below?

Oops, I missed that. I guess it is sufficient then.
