### PR TITLE
add a couple tests for fixed ICEs.

### LINKED ISSUE #114463: ICE caused by using feature(generic_const_exprs)
### Code
The code runs as expected until we introduce the `generic_const_exprs` attribute and the compiler encounters an ICE error.
```Rust
#![feature(generic_const_exprs)]
fn bug<'a>() {
    [(); (|_: &'a u8| (), 0).1];
}
```

### Meta

`rustc --version --verbose`:
```
$ rustc --version --verbose
rustc 1.73.0-nightly (474709a9a 2023-08-03)
binary: rustc
commit-hash: 474709a9a2a74a8bcf0055fadb335d0ca0d2d939
commit-date: 2023-08-03
host: x86_64-unknown-linux-gnu
release: 1.73.0-nightly
LLVM version: 16.0.5
```

### Error output

```
warning: the feature `generic_const_exprs` is incomplete and may not be safe to use and/or cause compiler crashes
 --> file1.rs:1:12
  |
1 | #![feature(generic_const_exprs)]
  |            ^^^^^^^^^^^^^^^^^^^
  |
  = note: see issue #76560 <https://github.com/rust-lang/rust/issues/76560> for more information
  = note: `#[warn(incomplete_features)]` on by default

error[E0601]: `main` function not found in crate `file1`
 --> file1.rs:4:2
  |
4 | }
  |  ^ consider adding a `main` function to `file1.rs`

error: internal compiler error: compiler/rustc_borrowck/src/universal_regions.rs:880:36: cannot convert `ReFree(DefId(0:3 ~ file1[e613]::bug), BrNamed(DefId(0:4 ~ file1[e613]::bug::'a), 'a))` to a region vid

thread 'rustc' panicked at /rustc/474709a9a2a74a8bcf0055fadb335d0ca0d2d939/compiler/rustc_errors/src/lib.rs:1645:9:
Box<dyn Any>
stack backtrace:
   0:     0x7f7803f3c19c - std::backtrace_rs::backtrace::libunwind::trace::haf256adafafbe58d
                               at /rustc/474709a9a2a74a8bcf0055fadb335d0ca0d2d939/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x7f7803f3c19c - std::backtrace_rs::backtrace::trace_unsynchronized::hfe1951132ff691c0
                               at /rustc/474709a9a2a74a8bcf0055fadb335d0ca0d2d939/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7f7803f3c19c - std::sys_common::backtrace::_print_fmt::h9a0fe52434930c36
                               at /rustc/474709a9a2a74a8bcf0055fadb335d0ca0d2d939/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x7f7803f3c19c - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h24adccbf3e1ada83
                               at /rustc/474709a9a2a74a8bcf0055fadb335d0ca0d2d939/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x7f7803fa289c - core::fmt::rt::Argument::fmt::h18ba555e398addfe
                               at /rustc/474709a9a2a74a8bcf0055fadb335d0ca0d2d939/library/core/src/fmt/rt.rs:138:9
   5:     0x7f7803fa289c - core::fmt::write::hbf3ee2d80be74759
                               at /rustc/474709a9a2a74a8bcf0055fadb335d0ca0d2d939/library/core/src/fmt/mod.rs:1094:21
   6:     0x7f7803f2e90e - std::io::Write::write_fmt::hfc2b3251522ff943
                               at /rustc/474709a9a2a74a8bcf0055fadb335d0ca0d2d939/library/std/src/io/mod.rs:1714:15
   7:     0x7f7803f3bf85 - std::sys_common::backtrace::_print::hfdc8ddb5f3ddee36
                               at /rustc/474709a9a2a74a8bcf0055fadb335d0ca0d2d939/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x7f7803f3bf85 - std::sys_common::backtrace::print::h316f264b298c7a30
                               at /rustc/474709a9a2a74a8bcf0055fadb335d0ca0d2d939/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x7f7803f3f0da - std::panicking::panic_hook_with_disk_dump::{{closure}}::h136bbb963feeea4a
                               at /rustc/474709a9a2a74a8bcf0055fadb335d0ca0d2d939/library/std/src/panicking.rs:278:22
  10:     0x7f7803f3ed73 - std::panicking::panic_hook_with_disk_dump::hd91a018a982a84f7
                               at /rustc/474709a9a2a74a8bcf0055fadb335d0ca0d2d939/library/std/src/panicking.rs:312:9
  11:     0x7f7802d0d799 - rustc_driver_impl[2c2bb0da6cfb3826]::install_ice_hook::{closure#0}
  12:     0x7f7803f3f980 - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::hd99b1fe24ccd07b5
                               at /rustc/474709a9a2a74a8bcf0055fadb335d0ca0d2d939/library/alloc/src/boxed.rs:2021:9
  13:     0x7f7803f3f980 - std::panicking::rust_panic_with_hook::h1593161995c9c003
                               at /rustc/474709a9a2a74a8bcf0055fadb335d0ca0d2d939/library/std/src/panicking.rs:733:13
  14:     0x7f78032971f1 - std[b7e5a9c79ea9fbed]::panicking::begin_panic::<rustc_errors[4345527545ed2164]::ExplicitBug>::{closure#0}
  15:     0x7f7803296096 - std[b7e5a9c79ea9fbed]::sys_common::backtrace::__rust_end_short_backtrace::<std[b7e5a9c79ea9fbed]::panicking::begin_panic<rustc_errors[4345527545ed2164]::ExplicitBug>::{closure#0}, !>
  16:     0x7f780322afc6 - std[b7e5a9c79ea9fbed]::panicking::begin_panic::<rustc_errors[4345527545ed2164]::ExplicitBug>
  17:     0x7f780320b344 - <rustc_errors[4345527545ed2164]::HandlerInner>::bug::<alloc[b2a4fa84f81d55c8]::string::String>
  18:     0x7f780320b1d6 - <rustc_errors[4345527545ed2164]::Handler>::bug::<alloc[b2a4fa84f81d55c8]::string::String>
  19:     0x7f780328b20c - rustc_middle[32728bc096d751c7]::util::bug::opt_span_bug_fmt::<rustc_span[9abd768efbccd329]::span_encoding::Span>::{closure#0}
  20:     0x7f780328a00a - rustc_middle[32728bc096d751c7]::ty::context::tls::with_opt::<rustc_middle[32728bc096d751c7]::util::bug::opt_span_bug_fmt<rustc_span[9abd768efbccd329]::span_encoding::Span>::{closure#0}, !>::{closure#0}
  21:     0x7f7803289fd8 - rustc_middle[32728bc096d751c7]::ty::context::tls::with_context_opt::<rustc_middle[32728bc096d751c7]::ty::context::tls::with_opt<rustc_middle[32728bc096d751c7]::util::bug::opt_span_bug_fmt<rustc_span[9abd768efbccd329]::span_encoding::Span>::{closure#0}, !>::{closure#0}, !>
  22:     0x7f780165a400 - rustc_middle[32728bc096d751c7]::util::bug::bug_fmt
  23:     0x7f7801e8d860 - <rustc_borrowck[36619a147d0794a8]::type_check::constraint_conversion::ConstraintConversion>::convert_all
  24:     0x7f7801e8e1c6 - <rustc_borrowck[36619a147d0794a8]::type_check::TypeChecker>::push_region_constraints
  25:     0x7f7801a5ab80 - <rustc_borrowck[36619a147d0794a8]::type_check::TypeChecker>::ascribe_user_type_skip_wf
  26:     0x7f7801a53c90 - rustc_borrowck[36619a147d0794a8]::type_check::type_check
  27:     0x7f7801a4a34f - rustc_borrowck[36619a147d0794a8]::nll::compute_regions
  28:     0x7f7801a24ed5 - rustc_borrowck[36619a147d0794a8]::do_mir_borrowck
  29:     0x7f7801a231e5 - rustc_borrowck[36619a147d0794a8]::mir_borrowck
  30:     0x7f7800d3976e - rustc_query_impl[c311561e1f786c65]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[c311561e1f786c65]::query_impl::mir_borrowck::dynamic_query::{closure#2}::{closure#0}, rustc_middle[32728bc096d751c7]::query::erase::Erased<[u8; 8usize]>>
  31:     0x7f7800d3973e - <rustc_query_impl[c311561e1f786c65]::query_impl::mir_borrowck::dynamic_query::{closure#2} as core[8e2a8f22f3da315]::ops::function::FnOnce<(rustc_middle[32728bc096d751c7]::ty::context::TyCtxt, rustc_span[9abd768efbccd329]::def_id::LocalDefId)>>::call_once
  32:     0x7f7800e80c3d - rustc_query_system[1215f1fc07ea991a]::query::plumbing::try_execute_query::<rustc_query_impl[c311561e1f786c65]::DynamicConfig<rustc_query_system[1215f1fc07ea991a]::query::caches::VecCache<rustc_span[9abd768efbccd329]::def_id::LocalDefId, rustc_middle[32728bc096d751c7]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[c311561e1f786c65]::plumbing::QueryCtxt, false>
  33:     0x7f780269094f - rustc_query_impl[c311561e1f786c65]::query_impl::mir_borrowck::get_query_non_incr::__rust_end_short_backtrace
  34:     0x7f7801e9cb9f - <rustc_borrowck[36619a147d0794a8]::type_check::TypeChecker>::prove_closure_bounds
  35:     0x7f7801e6b39d - <rustc_borrowck[36619a147d0794a8]::type_check::TypeChecker>::typeck_mir
  36:     0x7f7801a52a01 - rustc_borrowck[36619a147d0794a8]::type_check::type_check
  37:     0x7f7801a4a34f - rustc_borrowck[36619a147d0794a8]::nll::compute_regions
  38:     0x7f7801a24ed5 - rustc_borrowck[36619a147d0794a8]::do_mir_borrowck
  39:     0x7f7801a231e5 - rustc_borrowck[36619a147d0794a8]::mir_borrowck
  40:     0x7f7800d3976e - rustc_query_impl[c311561e1f786c65]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[c311561e1f786c65]::query_impl::mir_borrowck::dynamic_query::{closure#2}::{closure#0}, rustc_middle[32728bc096d751c7]::query::erase::Erased<[u8; 8usize]>>
  41:     0x7f7800d3973e - <rustc_query_impl[c311561e1f786c65]::query_impl::mir_borrowck::dynamic_query::{closure#2} as core[8e2a8f22f3da315]::ops::function::FnOnce<(rustc_middle[32728bc096d751c7]::ty::context::TyCtxt, rustc_span[9abd768efbccd329]::def_id::LocalDefId)>>::call_once
  42:     0x7f7800e80c3d - rustc_query_system[1215f1fc07ea991a]::query::plumbing::try_execute_query::<rustc_query_impl[c311561e1f786c65]::DynamicConfig<rustc_query_system[1215f1fc07ea991a]::query::caches::VecCache<rustc_span[9abd768efbccd329]::def_id::LocalDefId, rustc_middle[32728bc096d751c7]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[c311561e1f786c65]::plumbing::QueryCtxt, false>
  43:     0x7f780269094f - rustc_query_impl[c311561e1f786c65]::query_impl::mir_borrowck::get_query_non_incr::__rust_end_short_backtrace
  44:     0x7f780137344e - rustc_mir_transform[2797bcf166cffb39]::mir_drops_elaborated_and_const_checked
  45:     0x7f7800d42a3e - rustc_query_impl[c311561e1f786c65]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[c311561e1f786c65]::query_impl::mir_drops_elaborated_and_const_checked::dynamic_query::{closure#2}::{closure#0}, rustc_middle[32728bc096d751c7]::query::erase::Erased<[u8; 8usize]>>
  46:     0x7f7800d42a0e - <rustc_query_impl[c311561e1f786c65]::query_impl::mir_drops_elaborated_and_const_checked::dynamic_query::{closure#2} as core[8e2a8f22f3da315]::ops::function::FnOnce<(rustc_middle[32728bc096d751c7]::ty::context::TyCtxt, rustc_span[9abd768efbccd329]::def_id::LocalDefId)>>::call_once
  47:     0x7f7800e80c3d - rustc_query_system[1215f1fc07ea991a]::query::plumbing::try_execute_query::<rustc_query_impl[c311561e1f786c65]::DynamicConfig<rustc_query_system[1215f1fc07ea991a]::query::caches::VecCache<rustc_span[9abd768efbccd329]::def_id::LocalDefId, rustc_middle[32728bc096d751c7]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[c311561e1f786c65]::plumbing::QueryCtxt, false>
  48:     0x7f780268752f - rustc_query_impl[c311561e1f786c65]::query_impl::mir_drops_elaborated_and_const_checked::get_query_non_incr::__rust_end_short_backtrace
  49:     0x7f7801bf4b63 - rustc_mir_transform[2797bcf166cffb39]::mir_for_ctfe
  50:     0x7f7800dabe4e - rustc_query_impl[c311561e1f786c65]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[c311561e1f786c65]::query_impl::mir_for_ctfe::dynamic_query::{closure#2}::{closure#0}, rustc_middle[32728bc096d751c7]::query::erase::Erased<[u8; 8usize]>>
  51:     0x7f7800dabe21 - <rustc_query_impl[c311561e1f786c65]::query_impl::mir_for_ctfe::dynamic_query::{closure#2} as core[8e2a8f22f3da315]::ops::function::FnOnce<(rustc_middle[32728bc096d751c7]::ty::context::TyCtxt, rustc_span[9abd768efbccd329]::def_id::DefId)>>::call_once
  52:     0x7f7800d38145 - rustc_query_system[1215f1fc07ea991a]::query::plumbing::try_execute_query::<rustc_query_impl[c311561e1f786c65]::DynamicConfig<rustc_query_system[1215f1fc07ea991a]::query::caches::DefaultCache<rustc_span[9abd768efbccd329]::def_id::DefId, rustc_middle[32728bc096d751c7]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[c311561e1f786c65]::plumbing::QueryCtxt, false>
  53:     0x7f7802687680 - rustc_query_impl[c311561e1f786c65]::query_impl::mir_for_ctfe::get_query_non_incr::__rust_end_short_backtrace
  54:     0x7f7801279c60 - <rustc_const_eval[9e95d3ca9e32f8a5]::interpret::eval_context::InterpCx<rustc_const_eval[9e95d3ca9e32f8a5]::const_eval::machine::CompileTimeInterpreter>>::load_mir
  55:     0x7f780117f901 - rustc_const_eval[9e95d3ca9e32f8a5]::const_eval::eval_queries::eval_to_allocation_raw_provider
  56:     0x7f7800d8a427 - rustc_query_impl[c311561e1f786c65]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[c311561e1f786c65]::query_impl::eval_to_allocation_raw::dynamic_query::{closure#2}::{closure#0}, rustc_middle[32728bc096d751c7]::query::erase::Erased<[u8; 16usize]>>
  57:     0x7f7801c219f7 - rustc_query_system[1215f1fc07ea991a]::query::plumbing::try_execute_query::<rustc_query_impl[c311561e1f786c65]::DynamicConfig<rustc_query_system[1215f1fc07ea991a]::query::caches::DefaultCache<rustc_middle[32728bc096d751c7]::ty::ParamEnvAnd<rustc_middle[32728bc096d751c7]::mir::interpret::GlobalId>, rustc_middle[32728bc096d751c7]::query::erase::Erased<[u8; 16usize]>>, false, false, false>, rustc_query_impl[c311561e1f786c65]::plumbing::QueryCtxt, false>
  58:     0x7f7801c21679 - rustc_query_impl[c311561e1f786c65]::query_impl::eval_to_allocation_raw::get_query_non_incr::__rust_end_short_backtrace
  59:     0x7f780117fe67 - rustc_const_eval[9e95d3ca9e32f8a5]::const_eval::eval_queries::eval_to_allocation_raw_provider
  60:     0x7f7800d8a427 - rustc_query_impl[c311561e1f786c65]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[c311561e1f786c65]::query_impl::eval_to_allocation_raw::dynamic_query::{closure#2}::{closure#0}, rustc_middle[32728bc096d751c7]::query::erase::Erased<[u8; 16usize]>>
  61:     0x7f7801c219f7 - rustc_query_system[1215f1fc07ea991a]::query::plumbing::try_execute_query::<rustc_query_impl[c311561e1f786c65]::DynamicConfig<rustc_query_system[1215f1fc07ea991a]::query::caches::DefaultCache<rustc_middle[32728bc096d751c7]::ty::ParamEnvAnd<rustc_middle[32728bc096d751c7]::mir::interpret::GlobalId>, rustc_middle[32728bc096d751c7]::query::erase::Erased<[u8; 16usize]>>, false, false, false>, rustc_query_impl[c311561e1f786c65]::plumbing::QueryCtxt, false>
  62:     0x7f7801c21679 - rustc_query_impl[c311561e1f786c65]::query_impl::eval_to_allocation_raw::get_query_non_incr::__rust_end_short_backtrace
  63:     0x7f780246503a - <rustc_const_eval[9e95d3ca9e32f8a5]::provide::{closure#0} as core[8e2a8f22f3da315]::ops::function::FnOnce<(rustc_middle[32728bc096d751c7]::ty::context::TyCtxt, rustc_middle[32728bc096d751c7]::ty::ParamEnvAnd<rustc_middle[32728bc096d751c7]::mir::interpret::GlobalId>)>>::call_once
  64:     0x7f780217a459 - rustc_query_impl[c311561e1f786c65]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[c311561e1f786c65]::query_impl::eval_to_valtree::dynamic_query::{closure#2}::{closure#0}, rustc_middle[32728bc096d751c7]::query::erase::Erased<[u8; 24usize]>>
  65:     0x7f780217a408 - <rustc_query_impl[c311561e1f786c65]::query_impl::eval_to_valtree::dynamic_query::{closure#2} as core[8e2a8f22f3da315]::ops::function::FnOnce<(rustc_middle[32728bc096d751c7]::ty::context::TyCtxt, rustc_middle[32728bc096d751c7]::ty::ParamEnvAnd<rustc_middle[32728bc096d751c7]::mir::interpret::GlobalId>)>>::call_once
  66:     0x7f78022fa0c8 - rustc_query_system[1215f1fc07ea991a]::query::plumbing::try_execute_query::<rustc_query_impl[c311561e1f786c65]::DynamicConfig<rustc_query_system[1215f1fc07ea991a]::query::caches::DefaultCache<rustc_middle[32728bc096d751c7]::ty::ParamEnvAnd<rustc_middle[32728bc096d751c7]::mir::interpret::GlobalId>, rustc_middle[32728bc096d751c7]::query::erase::Erased<[u8; 24usize]>>, false, false, false>, rustc_query_impl[c311561e1f786c65]::plumbing::QueryCtxt, false>
  67:     0x7f78022f9d5e - rustc_query_impl[c311561e1f786c65]::query_impl::eval_to_valtree::get_query_non_incr::__rust_end_short_backtrace
  68:     0x7f78012eab4c - rustc_middle[32728bc096d751c7]::query::plumbing::query_get_at::<rustc_query_system[1215f1fc07ea991a]::query::caches::DefaultCache<rustc_middle[32728bc096d751c7]::ty::ParamEnvAnd<rustc_middle[32728bc096d751c7]::mir::interpret::GlobalId>, rustc_middle[32728bc096d751c7]::query::erase::Erased<[u8; 24usize]>>>
  69:     0x7f78012ea8eb - <rustc_middle[32728bc096d751c7]::ty::context::TyCtxt>::const_eval_global_id_for_typeck
  70:     0x7f78012ea3c4 - <rustc_middle[32728bc096d751c7]::ty::context::TyCtxt>::const_eval_resolve_for_typeck
  71:     0x7f780145ca87 - <rustc_middle[32728bc096d751c7]::ty::consts::Const>::eval
  72:     0x7f78013e71ff - <rustc_hir_typeck[a1aa762a977bcd63]::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
  73:     0x7f7801425d54 - <rustc_hir_typeck[a1aa762a977bcd63]::fn_ctxt::FnCtxt>::check_block_with_expected
  74:     0x7f78013e3433 - <rustc_hir_typeck[a1aa762a977bcd63]::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
  75:     0x7f780156899b - <rustc_hir_typeck[a1aa762a977bcd63]::fn_ctxt::FnCtxt>::check_return_expr
  76:     0x7f780156704c - rustc_hir_typeck[a1aa762a977bcd63]::check::check_fn
  77:     0x7f7801555b55 - rustc_hir_typeck[a1aa762a977bcd63]::typeck
  78:     0x7f7800d0b08c - rustc_query_impl[c311561e1f786c65]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[c311561e1f786c65]::query_impl::typeck::dynamic_query::{closure#2}::{closure#0}, rustc_middle[32728bc096d751c7]::query::erase::Erased<[u8; 8usize]>>
  79:     0x7f7800d0b06e - <rustc_query_impl[c311561e1f786c65]::query_impl::typeck::dynamic_query::{closure#2} as core[8e2a8f22f3da315]::ops::function::FnOnce<(rustc_middle[32728bc096d751c7]::ty::context::TyCtxt, rustc_span[9abd768efbccd329]::def_id::LocalDefId)>>::call_once
  80:     0x7f7800e80c3d - rustc_query_system[1215f1fc07ea991a]::query::plumbing::try_execute_query::<rustc_query_impl[c311561e1f786c65]::DynamicConfig<rustc_query_system[1215f1fc07ea991a]::query::caches::VecCache<rustc_span[9abd768efbccd329]::def_id::LocalDefId, rustc_middle[32728bc096d751c7]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[c311561e1f786c65]::plumbing::QueryCtxt, false>
  81:     0x7f78026906cf - rustc_query_impl[c311561e1f786c65]::query_impl::typeck::get_query_non_incr::__rust_end_short_backtrace
  82:     0x7f780219be22 - rustc_data_structures[e5ddef51fa833839]::sync::par_for_each_in::<&[rustc_span[9abd768efbccd329]::def_id::LocalDefId], <rustc_middle[32728bc096d751c7]::hir::map::Map>::par_body_owners<rustc_hir_analysis[505bd014cb0020b8]::check_crate::{closure#7}>::{closure#0}>
  83:     0x7f780219ae2a - rustc_hir_analysis[505bd014cb0020b8]::check_crate
  84:     0x7f78021955ca - rustc_interface[b10bd5cb1b971de9]::passes::analysis
  85:     0x7f78021ffd8a - rustc_query_impl[c311561e1f786c65]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[c311561e1f786c65]::query_impl::analysis::dynamic_query::{closure#2}::{closure#0}, rustc_middle[32728bc096d751c7]::query::erase::Erased<[u8; 1usize]>>
  86:     0x7f78021ffd79 - <rustc_query_impl[c311561e1f786c65]::query_impl::analysis::dynamic_query::{closure#2} as core[8e2a8f22f3da315]::ops::function::FnOnce<(rustc_middle[32728bc096d751c7]::ty::context::TyCtxt, ())>>::call_once
  87:     0x7f780239b368 - rustc_query_system[1215f1fc07ea991a]::query::plumbing::try_execute_query::<rustc_query_impl[c311561e1f786c65]::DynamicConfig<rustc_query_system[1215f1fc07ea991a]::query::caches::SingleCache<rustc_middle[32728bc096d751c7]::query::erase::Erased<[u8; 1usize]>>, false, false, false>, rustc_query_impl[c311561e1f786c65]::plumbing::QueryCtxt, false>
  88:     0x7f780239b0f7 - rustc_query_impl[c311561e1f786c65]::query_impl::analysis::get_query_non_incr::__rust_end_short_backtrace
  89:     0x7f7801f798c5 - <rustc_middle[32728bc096d751c7]::ty::context::GlobalCtxt>::enter::<rustc_driver_impl[2c2bb0da6cfb3826]::run_compiler::{closure#1}::{closure#2}::{closure#4}, core[8e2a8f22f3da315]::result::Result<(), rustc_span[9abd768efbccd329]::ErrorGuaranteed>>
  90:     0x7f7801f78ef2 - <rustc_interface[b10bd5cb1b971de9]::interface::Compiler>::enter::<rustc_driver_impl[2c2bb0da6cfb3826]::run_compiler::{closure#1}::{closure#2}, core[8e2a8f22f3da315]::result::Result<core[8e2a8f22f3da315]::option::Option<rustc_interface[b10bd5cb1b971de9]::queries::Linker>, rustc_span[9abd768efbccd329]::ErrorGuaranteed>>
  91:     0x7f7801f71fc8 - std[b7e5a9c79ea9fbed]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[b10bd5cb1b971de9]::util::run_in_thread_pool_with_globals<rustc_interface[b10bd5cb1b971de9]::interface::run_compiler<core[8e2a8f22f3da315]::result::Result<(), rustc_span[9abd768efbccd329]::ErrorGuaranteed>, rustc_driver_impl[2c2bb0da6cfb3826]::run_compiler::{closure#1}>::{closure#0}, core[8e2a8f22f3da315]::result::Result<(), rustc_span[9abd768efbccd329]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[8e2a8f22f3da315]::result::Result<(), rustc_span[9abd768efbccd329]::ErrorGuaranteed>>
  92:     0x7f7801f7174e - <<std[b7e5a9c79ea9fbed]::thread::Builder>::spawn_unchecked_<rustc_interface[b10bd5cb1b971de9]::util::run_in_thread_pool_with_globals<rustc_interface[b10bd5cb1b971de9]::interface::run_compiler<core[8e2a8f22f3da315]::result::Result<(), rustc_span[9abd768efbccd329]::ErrorGuaranteed>, rustc_driver_impl[2c2bb0da6cfb3826]::run_compiler::{closure#1}>::{closure#0}, core[8e2a8f22f3da315]::result::Result<(), rustc_span[9abd768efbccd329]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[8e2a8f22f3da315]::result::Result<(), rustc_span[9abd768efbccd329]::ErrorGuaranteed>>::{closure#1} as core[8e2a8f22f3da315]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  93:     0x7f7803f4a125 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hb18992c0c074fb04
                               at /rustc/474709a9a2a74a8bcf0055fadb335d0ca0d2d939/library/alloc/src/boxed.rs:2007:9
  94:     0x7f7803f4a125 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::ha4998f5f9033c44e
                               at /rustc/474709a9a2a74a8bcf0055fadb335d0ca0d2d939/library/alloc/src/boxed.rs:2007:9
  95:     0x7f7803f4a125 - std::sys::unix::thread::Thread::new::thread_start::h3370231efa79af31
                               at /rustc/474709a9a2a74a8bcf0055fadb335d0ca0d2d939/library/std/src/sys/unix/thread.rs:108:17
  96:     0x7f77ff4c76db - start_thread
  97:     0x7f77ff1f061f - clone
  98:                0x0 - <unknown>

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: please attach the file at `/home/coding/rustc-ice-2023-08-04T08:42:06.45358537Z-23008.txt` to your bug report

query stack during panic:
#0 [mir_borrowck] borrow-checking `bug::{constant#0}::{closure#0}`
#1 [mir_borrowck] borrow-checking `bug::{constant#0}`
#2 [mir_drops_elaborated_and_const_checked] elaborating drops for `bug::{constant#0}`
#3 [mir_for_ctfe] caching mir of `bug::{constant#0}` for CTFE
#4 [eval_to_allocation_raw] const-evaluating + checking `bug::{constant#0}`
#5 [eval_to_allocation_raw] const-evaluating + checking `bug::{constant#0}`
#6 [eval_to_valtree] evaluating type-level constant
#7 [typeck] type-checking `bug`
#8 [analysis] running analysis passes on this crate
end of query stack
error: aborting due to 2 previous errors; 1 warning emitted

For more information about this error, try `rustc --explain E0601`.


```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
thread 'rustc' panicked at /rustc/474709a9a2a74a8bcf0055fadb335d0ca0d2d939/compiler/rustc_errors/src/lib.rs:1645:9:
Box<dyn Any>
stack backtrace:
   0:     0x7f7803f3c19c - std::backtrace_rs::backtrace::libunwind::trace::haf256adafafbe58d
                               at /rustc/474709a9a2a74a8bcf0055fadb335d0ca0d2d939/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x7f7803f3c19c - std::backtrace_rs::backtrace::trace_unsynchronized::hfe1951132ff691c0
                               at /rustc/474709a9a2a74a8bcf0055fadb335d0ca0d2d939/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7f7803f3c19c - std::sys_common::backtrace::_print_fmt::h9a0fe52434930c36
                               at /rustc/474709a9a2a74a8bcf0055fadb335d0ca0d2d939/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x7f7803f3c19c - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h24adccbf3e1ada83
                               at /rustc/474709a9a2a74a8bcf0055fadb335d0ca0d2d939/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x7f7803fa289c - core::fmt::rt::Argument::fmt::h18ba555e398addfe
                               at /rustc/474709a9a2a74a8bcf0055fadb335d0ca0d2d939/library/core/src/fmt/rt.rs:138:9
   5:     0x7f7803fa289c - core::fmt::write::hbf3ee2d80be74759
                               at /rustc/474709a9a2a74a8bcf0055fadb335d0ca0d2d939/library/core/src/fmt/mod.rs:1094:21
   6:     0x7f7803f2e72e - std::io::Write::write_fmt::h095206be3c257ac2
                               at /rustc/474709a9a2a74a8bcf0055fadb335d0ca0d2d939/library/std/src/io/mod.rs:1714:15
   7:     0x7f7803f3bf85 - std::sys_common::backtrace::_print::hfdc8ddb5f3ddee36
                               at /rustc/474709a9a2a74a8bcf0055fadb335d0ca0d2d939/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x7f7803f3bf85 - std::sys_common::backtrace::print::h316f264b298c7a30
                               at /rustc/474709a9a2a74a8bcf0055fadb335d0ca0d2d939/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x7f7803f3f0da - std::panicking::panic_hook_with_disk_dump::{{closure}}::h136bbb963feeea4a
                               at /rustc/474709a9a2a74a8bcf0055fadb335d0ca0d2d939/library/std/src/panicking.rs:278:22
  10:     0x7f7803f3ec46 - std::panicking::panic_hook_with_disk_dump::hd91a018a982a84f7
                               at /rustc/474709a9a2a74a8bcf0055fadb335d0ca0d2d939/library/std/src/panicking.rs:305:9
  11:     0x7f7802d0d799 - rustc_driver_impl[2c2bb0da6cfb3826]::install_ice_hook::{closure#0}
  12:     0x7f7803f3f980 - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::hd99b1fe24ccd07b5
                               at /rustc/474709a9a2a74a8bcf0055fadb335d0ca0d2d939/library/alloc/src/boxed.rs:2021:9
  13:     0x7f7803f3f980 - std::panicking::rust_panic_with_hook::h1593161995c9c003
                               at /rustc/474709a9a2a74a8bcf0055fadb335d0ca0d2d939/library/std/src/panicking.rs:733:13
  14:     0x7f78032971f1 - std[b7e5a9c79ea9fbed]::panicking::begin_panic::<rustc_errors[4345527545ed2164]::ExplicitBug>::{closure#0}
  15:     0x7f7803296096 - std[b7e5a9c79ea9fbed]::sys_common::backtrace::__rust_end_short_backtrace::<std[b7e5a9c79ea9fbed]::panicking::begin_panic<rustc_errors[4345527545ed2164]::ExplicitBug>::{closure#0}, !>
  16:     0x7f780322afc6 - std[b7e5a9c79ea9fbed]::panicking::begin_panic::<rustc_errors[4345527545ed2164]::ExplicitBug>
  17:     0x7f780320b344 - <rustc_errors[4345527545ed2164]::HandlerInner>::bug::<alloc[b2a4fa84f81d55c8]::string::String>
  18:     0x7f780320b1d6 - <rustc_errors[4345527545ed2164]::Handler>::bug::<alloc[b2a4fa84f81d55c8]::string::String>
  19:     0x7f780328b20c - rustc_middle[32728bc096d751c7]::util::bug::opt_span_bug_fmt::<rustc_span[9abd768efbccd329]::span_encoding::Span>::{closure#0}
  20:     0x7f780328a00a - rustc_middle[32728bc096d751c7]::ty::context::tls::with_opt::<rustc_middle[32728bc096d751c7]::util::bug::opt_span_bug_fmt<rustc_span[9abd768efbccd329]::span_encoding::Span>::{closure#0}, !>::{closure#0}
  21:     0x7f7803289fd8 - rustc_middle[32728bc096d751c7]::ty::context::tls::with_context_opt::<rustc_middle[32728bc096d751c7]::ty::context::tls::with_opt<rustc_middle[32728bc096d751c7]::util::bug::opt_span_bug_fmt<rustc_span[9abd768efbccd329]::span_encoding::Span>::{closure#0}, !>::{closure#0}, !>
  22:     0x7f780165a400 - rustc_middle[32728bc096d751c7]::util::bug::bug_fmt
  23:     0x7f7801e8d860 - <rustc_borrowck[36619a147d0794a8]::type_check::constraint_conversion::ConstraintConversion>::convert_all
  24:     0x7f7801e8e1c6 - <rustc_borrowck[36619a147d0794a8]::type_check::TypeChecker>::push_region_constraints
  25:     0x7f7801a5ab80 - <rustc_borrowck[36619a147d0794a8]::type_check::TypeChecker>::ascribe_user_type_skip_wf
  26:     0x7f7801a53c90 - rustc_borrowck[36619a147d0794a8]::type_check::type_check
  27:     0x7f7801a4a34f - rustc_borrowck[36619a147d0794a8]::nll::compute_regions
  28:     0x7f7801a24ed5 - rustc_borrowck[36619a147d0794a8]::do_mir_borrowck
  29:     0x7f7801a231e5 - rustc_borrowck[36619a147d0794a8]::mir_borrowck
  30:     0x7f7800d3976e - rustc_query_impl[c311561e1f786c65]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[c311561e1f786c65]::query_impl::mir_borrowck::dynamic_query::{closure#2}::{closure#0}, rustc_middle[32728bc096d751c7]::query::erase::Erased<[u8; 8usize]>>
  31:     0x7f7800d3973e - <rustc_query_impl[c311561e1f786c65]::query_impl::mir_borrowck::dynamic_query::{closure#2} as core[8e2a8f22f3da315]::ops::function::FnOnce<(rustc_middle[32728bc096d751c7]::ty::context::TyCtxt, rustc_span[9abd768efbccd329]::def_id::LocalDefId)>>::call_once
  32:     0x7f7800e80c3d - rustc_query_system[1215f1fc07ea991a]::query::plumbing::try_execute_query::<rustc_query_impl[c311561e1f786c65]::DynamicConfig<rustc_query_system[1215f1fc07ea991a]::query::caches::VecCache<rustc_span[9abd768efbccd329]::def_id::LocalDefId, rustc_middle[32728bc096d751c7]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[c311561e1f786c65]::plumbing::QueryCtxt, false>
  33:     0x7f780269094f - rustc_query_impl[c311561e1f786c65]::query_impl::mir_borrowck::get_query_non_incr::__rust_end_short_backtrace
  34:     0x7f7801e9cb9f - <rustc_borrowck[36619a147d0794a8]::type_check::TypeChecker>::prove_closure_bounds
  35:     0x7f7801e6b39d - <rustc_borrowck[36619a147d0794a8]::type_check::TypeChecker>::typeck_mir
  36:     0x7f7801a52a01 - rustc_borrowck[36619a147d0794a8]::type_check::type_check
  37:     0x7f7801a4a34f - rustc_borrowck[36619a147d0794a8]::nll::compute_regions
  38:     0x7f7801a24ed5 - rustc_borrowck[36619a147d0794a8]::do_mir_borrowck
  39:     0x7f7801a231e5 - rustc_borrowck[36619a147d0794a8]::mir_borrowck
  40:     0x7f7800d3976e - rustc_query_impl[c311561e1f786c65]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[c311561e1f786c65]::query_impl::mir_borrowck::dynamic_query::{closure#2}::{closure#0}, rustc_middle[32728bc096d751c7]::query::erase::Erased<[u8; 8usize]>>
  41:     0x7f7800d3973e - <rustc_query_impl[c311561e1f786c65]::query_impl::mir_borrowck::dynamic_query::{closure#2} as core[8e2a8f22f3da315]::ops::function::FnOnce<(rustc_middle[32728bc096d751c7]::ty::context::TyCtxt, rustc_span[9abd768efbccd329]::def_id::LocalDefId)>>::call_once
  42:     0x7f7800e80c3d - rustc_query_system[1215f1fc07ea991a]::query::plumbing::try_execute_query::<rustc_query_impl[c311561e1f786c65]::DynamicConfig<rustc_query_system[1215f1fc07ea991a]::query::caches::VecCache<rustc_span[9abd768efbccd329]::def_id::LocalDefId, rustc_middle[32728bc096d751c7]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[c311561e1f786c65]::plumbing::QueryCtxt, false>
  43:     0x7f780269094f - rustc_query_impl[c311561e1f786c65]::query_impl::mir_borrowck::get_query_non_incr::__rust_end_short_backtrace
  44:     0x7f780137344e - rustc_mir_transform[2797bcf166cffb39]::mir_drops_elaborated_and_const_checked
  45:     0x7f7800d42a3e - rustc_query_impl[c311561e1f786c65]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[c311561e1f786c65]::query_impl::mir_drops_elaborated_and_const_checked::dynamic_query::{closure#2}::{closure#0}, rustc_middle[32728bc096d751c7]::query::erase::Erased<[u8; 8usize]>>
  46:     0x7f7800d42a0e - <rustc_query_impl[c311561e1f786c65]::query_impl::mir_drops_elaborated_and_const_checked::dynamic_query::{closure#2} as core[8e2a8f22f3da315]::ops::function::FnOnce<(rustc_middle[32728bc096d751c7]::ty::context::TyCtxt, rustc_span[9abd768efbccd329]::def_id::LocalDefId)>>::call_once
  47:     0x7f7800e80c3d - rustc_query_system[1215f1fc07ea991a]::query::plumbing::try_execute_query::<rustc_query_impl[c311561e1f786c65]::DynamicConfig<rustc_query_system[1215f1fc07ea991a]::query::caches::VecCache<rustc_span[9abd768efbccd329]::def_id::LocalDefId, rustc_middle[32728bc096d751c7]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[c311561e1f786c65]::plumbing::QueryCtxt, false>
  48:     0x7f780268752f - rustc_query_impl[c311561e1f786c65]::query_impl::mir_drops_elaborated_and_const_checked::get_query_non_incr::__rust_end_short_backtrace
  49:     0x7f7801bf4b63 - rustc_mir_transform[2797bcf166cffb39]::mir_for_ctfe
  50:     0x7f7800dabe4e - rustc_query_impl[c311561e1f786c65]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[c311561e1f786c65]::query_impl::mir_for_ctfe::dynamic_query::{closure#2}::{closure#0}, rustc_middle[32728bc096d751c7]::query::erase::Erased<[u8; 8usize]>>
  51:     0x7f7800dabe21 - <rustc_query_impl[c311561e1f786c65]::query_impl::mir_for_ctfe::dynamic_query::{closure#2} as core[8e2a8f22f3da315]::ops::function::FnOnce<(rustc_middle[32728bc096d751c7]::ty::context::TyCtxt, rustc_span[9abd768efbccd329]::def_id::DefId)>>::call_once
  52:     0x7f7800d38145 - rustc_query_system[1215f1fc07ea991a]::query::plumbing::try_execute_query::<rustc_query_impl[c311561e1f786c65]::DynamicConfig<rustc_query_system[1215f1fc07ea991a]::query::caches::DefaultCache<rustc_span[9abd768efbccd329]::def_id::DefId, rustc_middle[32728bc096d751c7]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[c311561e1f786c65]::plumbing::QueryCtxt, false>
  53:     0x7f7802687680 - rustc_query_impl[c311561e1f786c65]::query_impl::mir_for_ctfe::get_query_non_incr::__rust_end_short_backtrace
  54:     0x7f7801279c60 - <rustc_const_eval[9e95d3ca9e32f8a5]::interpret::eval_context::InterpCx<rustc_const_eval[9e95d3ca9e32f8a5]::const_eval::machine::CompileTimeInterpreter>>::load_mir
  55:     0x7f780117f901 - rustc_const_eval[9e95d3ca9e32f8a5]::const_eval::eval_queries::eval_to_allocation_raw_provider
  56:     0x7f7800d8a427 - rustc_query_impl[c311561e1f786c65]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[c311561e1f786c65]::query_impl::eval_to_allocation_raw::dynamic_query::{closure#2}::{closure#0}, rustc_middle[32728bc096d751c7]::query::erase::Erased<[u8; 16usize]>>
  57:     0x7f7801c219f7 - rustc_query_system[1215f1fc07ea991a]::query::plumbing::try_execute_query::<rustc_query_impl[c311561e1f786c65]::DynamicConfig<rustc_query_system[1215f1fc07ea991a]::query::caches::DefaultCache<rustc_middle[32728bc096d751c7]::ty::ParamEnvAnd<rustc_middle[32728bc096d751c7]::mir::interpret::GlobalId>, rustc_middle[32728bc096d751c7]::query::erase::Erased<[u8; 16usize]>>, false, false, false>, rustc_query_impl[c311561e1f786c65]::plumbing::QueryCtxt, false>
  58:     0x7f7801c21679 - rustc_query_impl[c311561e1f786c65]::query_impl::eval_to_allocation_raw::get_query_non_incr::__rust_end_short_backtrace
  59:     0x7f780117fe67 - rustc_const_eval[9e95d3ca9e32f8a5]::const_eval::eval_queries::eval_to_allocation_raw_provider
  60:     0x7f7800d8a427 - rustc_query_impl[c311561e1f786c65]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[c311561e1f786c65]::query_impl::eval_to_allocation_raw::dynamic_query::{closure#2}::{closure#0}, rustc_middle[32728bc096d751c7]::query::erase::Erased<[u8; 16usize]>>
  61:     0x7f7801c219f7 - rustc_query_system[1215f1fc07ea991a]::query::plumbing::try_execute_query::<rustc_query_impl[c311561e1f786c65]::DynamicConfig<rustc_query_system[1215f1fc07ea991a]::query::caches::DefaultCache<rustc_middle[32728bc096d751c7]::ty::ParamEnvAnd<rustc_middle[32728bc096d751c7]::mir::interpret::GlobalId>, rustc_middle[32728bc096d751c7]::query::erase::Erased<[u8; 16usize]>>, false, false, false>, rustc_query_impl[c311561e1f786c65]::plumbing::QueryCtxt, false>
  62:     0x7f7801c21679 - rustc_query_impl[c311561e1f786c65]::query_impl::eval_to_allocation_raw::get_query_non_incr::__rust_end_short_backtrace
  63:     0x7f780246503a - <rustc_const_eval[9e95d3ca9e32f8a5]::provide::{closure#0} as core[8e2a8f22f3da315]::ops::function::FnOnce<(rustc_middle[32728bc096d751c7]::ty::context::TyCtxt, rustc_middle[32728bc096d751c7]::ty::ParamEnvAnd<rustc_middle[32728bc096d751c7]::mir::interpret::GlobalId>)>>::call_once
  64:     0x7f780217a459 - rustc_query_impl[c311561e1f786c65]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[c311561e1f786c65]::query_impl::eval_to_valtree::dynamic_query::{closure#2}::{closure#0}, rustc_middle[32728bc096d751c7]::query::erase::Erased<[u8; 24usize]>>
  65:     0x7f780217a408 - <rustc_query_impl[c311561e1f786c65]::query_impl::eval_to_valtree::dynamic_query::{closure#2} as core[8e2a8f22f3da315]::ops::function::FnOnce<(rustc_middle[32728bc096d751c7]::ty::context::TyCtxt, rustc_middle[32728bc096d751c7]::ty::ParamEnvAnd<rustc_middle[32728bc096d751c7]::mir::interpret::GlobalId>)>>::call_once
  66:     0x7f78022fa0c8 - rustc_query_system[1215f1fc07ea991a]::query::plumbing::try_execute_query::<rustc_query_impl[c311561e1f786c65]::DynamicConfig<rustc_query_system[1215f1fc07ea991a]::query::caches::DefaultCache<rustc_middle[32728bc096d751c7]::ty::ParamEnvAnd<rustc_middle[32728bc096d751c7]::mir::interpret::GlobalId>, rustc_middle[32728bc096d751c7]::query::erase::Erased<[u8; 24usize]>>, false, false, false>, rustc_query_impl[c311561e1f786c65]::plumbing::QueryCtxt, false>
  67:     0x7f78022f9d5e - rustc_query_impl[c311561e1f786c65]::query_impl::eval_to_valtree::get_query_non_incr::__rust_end_short_backtrace
  68:     0x7f78012eab4c - rustc_middle[32728bc096d751c7]::query::plumbing::query_get_at::<rustc_query_system[1215f1fc07ea991a]::query::caches::DefaultCache<rustc_middle[32728bc096d751c7]::ty::ParamEnvAnd<rustc_middle[32728bc096d751c7]::mir::interpret::GlobalId>, rustc_middle[32728bc096d751c7]::query::erase::Erased<[u8; 24usize]>>>
  69:     0x7f78012ea8eb - <rustc_middle[32728bc096d751c7]::ty::context::TyCtxt>::const_eval_global_id_for_typeck
  70:     0x7f78012ea3c4 - <rustc_middle[32728bc096d751c7]::ty::context::TyCtxt>::const_eval_resolve_for_typeck
  71:     0x7f780145ca87 - <rustc_middle[32728bc096d751c7]::ty::consts::Const>::eval
  72:     0x7f78013e71ff - <rustc_hir_typeck[a1aa762a977bcd63]::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
  73:     0x7f7801425d54 - <rustc_hir_typeck[a1aa762a977bcd63]::fn_ctxt::FnCtxt>::check_block_with_expected
  74:     0x7f78013e3433 - <rustc_hir_typeck[a1aa762a977bcd63]::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
  75:     0x7f780156899b - <rustc_hir_typeck[a1aa762a977bcd63]::fn_ctxt::FnCtxt>::check_return_expr
  76:     0x7f780156704c - rustc_hir_typeck[a1aa762a977bcd63]::check::check_fn
  77:     0x7f7801555b55 - rustc_hir_typeck[a1aa762a977bcd63]::typeck
  78:     0x7f7800d0b08c - rustc_query_impl[c311561e1f786c65]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[c311561e1f786c65]::query_impl::typeck::dynamic_query::{closure#2}::{closure#0}, rustc_middle[32728bc096d751c7]::query::erase::Erased<[u8; 8usize]>>
  79:     0x7f7800d0b06e - <rustc_query_impl[c311561e1f786c65]::query_impl::typeck::dynamic_query::{closure#2} as core[8e2a8f22f3da315]::ops::function::FnOnce<(rustc_middle[32728bc096d751c7]::ty::context::TyCtxt, rustc_span[9abd768efbccd329]::def_id::LocalDefId)>>::call_once
  80:     0x7f7800e80c3d - rustc_query_system[1215f1fc07ea991a]::query::plumbing::try_execute_query::<rustc_query_impl[c311561e1f786c65]::DynamicConfig<rustc_query_system[1215f1fc07ea991a]::query::caches::VecCache<rustc_span[9abd768efbccd329]::def_id::LocalDefId, rustc_middle[32728bc096d751c7]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[c311561e1f786c65]::plumbing::QueryCtxt, false>
  81:     0x7f78026906cf - rustc_query_impl[c311561e1f786c65]::query_impl::typeck::get_query_non_incr::__rust_end_short_backtrace
  82:     0x7f780219be22 - rustc_data_structures[e5ddef51fa833839]::sync::par_for_each_in::<&[rustc_span[9abd768efbccd329]::def_id::LocalDefId], <rustc_middle[32728bc096d751c7]::hir::map::Map>::par_body_owners<rustc_hir_analysis[505bd014cb0020b8]::check_crate::{closure#7}>::{closure#0}>
  83:     0x7f780219ae2a - rustc_hir_analysis[505bd014cb0020b8]::check_crate
  84:     0x7f78021955ca - rustc_interface[b10bd5cb1b971de9]::passes::analysis
  85:     0x7f78021ffd8a - rustc_query_impl[c311561e1f786c65]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[c311561e1f786c65]::query_impl::analysis::dynamic_query::{closure#2}::{closure#0}, rustc_middle[32728bc096d751c7]::query::erase::Erased<[u8; 1usize]>>
  86:     0x7f78021ffd79 - <rustc_query_impl[c311561e1f786c65]::query_impl::analysis::dynamic_query::{closure#2} as core[8e2a8f22f3da315]::ops::function::FnOnce<(rustc_middle[32728bc096d751c7]::ty::context::TyCtxt, ())>>::call_once
  87:     0x7f780239b368 - rustc_query_system[1215f1fc07ea991a]::query::plumbing::try_execute_query::<rustc_query_impl[c311561e1f786c65]::DynamicConfig<rustc_query_system[1215f1fc07ea991a]::query::caches::SingleCache<rustc_middle[32728bc096d751c7]::query::erase::Erased<[u8; 1usize]>>, false, false, false>, rustc_query_impl[c311561e1f786c65]::plumbing::QueryCtxt, false>
  88:     0x7f780239b0f7 - rustc_query_impl[c311561e1f786c65]::query_impl::analysis::get_query_non_incr::__rust_end_short_backtrace
  89:     0x7f7801f798c5 - <rustc_middle[32728bc096d751c7]::ty::context::GlobalCtxt>::enter::<rustc_driver_impl[2c2bb0da6cfb3826]::run_compiler::{closure#1}::{closure#2}::{closure#4}, core[8e2a8f22f3da315]::result::Result<(), rustc_span[9abd768efbccd329]::ErrorGuaranteed>>
  90:     0x7f7801f78ef2 - <rustc_interface[b10bd5cb1b971de9]::interface::Compiler>::enter::<rustc_driver_impl[2c2bb0da6cfb3826]::run_compiler::{closure#1}::{closure#2}, core[8e2a8f22f3da315]::result::Result<core[8e2a8f22f3da315]::option::Option<rustc_interface[b10bd5cb1b971de9]::queries::Linker>, rustc_span[9abd768efbccd329]::ErrorGuaranteed>>
  91:     0x7f7801f71fc8 - std[b7e5a9c79ea9fbed]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[b10bd5cb1b971de9]::util::run_in_thread_pool_with_globals<rustc_interface[b10bd5cb1b971de9]::interface::run_compiler<core[8e2a8f22f3da315]::result::Result<(), rustc_span[9abd768efbccd329]::ErrorGuaranteed>, rustc_driver_impl[2c2bb0da6cfb3826]::run_compiler::{closure#1}>::{closure#0}, core[8e2a8f22f3da315]::result::Result<(), rustc_span[9abd768efbccd329]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[8e2a8f22f3da315]::result::Result<(), rustc_span[9abd768efbccd329]::ErrorGuaranteed>>
  92:     0x7f7801f7174e - <<std[b7e5a9c79ea9fbed]::thread::Builder>::spawn_unchecked_<rustc_interface[b10bd5cb1b971de9]::util::run_in_thread_pool_with_globals<rustc_interface[b10bd5cb1b971de9]::interface::run_compiler<core[8e2a8f22f3da315]::result::Result<(), rustc_span[9abd768efbccd329]::ErrorGuaranteed>, rustc_driver_impl[2c2bb0da6cfb3826]::run_compiler::{closure#1}>::{closure#0}, core[8e2a8f22f3da315]::result::Result<(), rustc_span[9abd768efbccd329]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[8e2a8f22f3da315]::result::Result<(), rustc_span[9abd768efbccd329]::ErrorGuaranteed>>::{closure#1} as core[8e2a8f22f3da315]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  93:     0x7f7803f4a125 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hb18992c0c074fb04
                               at /rustc/474709a9a2a74a8bcf0055fadb335d0ca0d2d939/library/alloc/src/boxed.rs:2007:9
  94:     0x7f7803f4a125 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::ha4998f5f9033c44e
                               at /rustc/474709a9a2a74a8bcf0055fadb335d0ca0d2d939/library/alloc/src/boxed.rs:2007:9
  95:     0x7f7803f4a125 - std::sys::unix::thread::Thread::new::thread_start::h3370231efa79af31
                               at /rustc/474709a9a2a74a8bcf0055fadb335d0ca0d2d939/library/std/src/sys/unix/thread.rs:108:17
  96:     0x7f77ff4c76db - start_thread
  97:     0x7f77ff1f061f - clone
  98:                0x0 - <unknown>


rustc version: 1.73.0-nightly (474709a9a 2023-08-03)
platform: x86_64-unknown-linux-gnu

query stack during panic:
#0 [mir_borrowck] borrow-checking `bug::{constant#0}::{closure#0}`
#1 [mir_borrowck] borrow-checking `bug::{constant#0}`
#2 [mir_drops_elaborated_and_const_checked] elaborating drops for `bug::{constant#0}`
#3 [mir_for_ctfe] caching mir of `bug::{constant#0}` for CTFE
#4 [eval_to_allocation_raw] const-evaluating + checking `bug::{constant#0}`
#5 [eval_to_allocation_raw] const-evaluating + checking `bug::{constant#0}`
#6 [eval_to_valtree] evaluating type-level constant
#7 [typeck] type-checking `bug`
#8 [analysis] running analysis passes on this crate
end of query stack

```

</p>
</details>

### LINKED ISSUE #121413: ICE: `ImmTy { imm: Scalar(alloc1), ty: *const dyn Sync } input to a fat-to-thin cast (*const dyn Sync -> *const usize`
auto-reduced (treereduce-rust):
````rust
#![feature(const_refs_to_static)]
const REF_INTERIOR_MUT: &usize = {
    static FOO: Sync = AtomicUsize::new(0);
    unsafe { &*(&FOO as *const _ as *const usize) }
};

````

<details><summary><strong>original code</strong></summary>
<p>

original:
````rust
//@ compile-flags: -Zunleash-the-miri-inside-of-you
//@ normalize-stderr-test "(the raw bytes of the constant) \(size: [0-9]*, align: [0-9]*\)" -> "$1 (size: $$SIZE, align: $$ALIGN)"
//@ normalize-stderr-test "([0-9a-f][0-9a-f] |╾─*ALLOC[0-9]+(\+[a-z0-9]+)?(<imm>)?─*╼ )+ *│.*" -> "HEX_DUMP"

use std::sync::atomic::AtomicUsize;
use std::sync::atomic::Ordering;

const MUTATE_INTERIOR_MUT: usize = {
    static FOO: AtomicUsize = EMPTY_SLICE.as_ptr().guaranteed_eq(&[] as *const _);
    FOO.fetch_add(1, Ordering::Relaxed) //~ERROR evaluation of constant value failed
};

const READ_INTERIOR_MUT: usize = {
    static FOO: AtomicUsize = AtomicUsize::new(0);
    unsafe { *(&FOO as *const _ as *const usize) } // These pass the lifetime checks because of the "tail expression" / "outer scope" rule.
};

static mut MUTABLE: u32 = 0;
const READ_MUT: u32 = unsafe { MUTABLE }; //~ERROR evaluation of constant value failed

// Evaluating this does not read anything mutable, but validation does, so this should error.
const REF_INTERIOR_MUT: &usize = { //~ ERROR undefined behavior
    //~| encountered reference to mutable memory
    static FOO: Sync = AtomicUsize::new(0);
    unsafe { &*(&FOO as *const _ as *const usize) }
};

// Not actually reading from anything mutable, so these are fine.
static MY_STATIC: u8 = 4;
const REF_IMMUT: &u8 = &MY_STATIC;
const READ_IMMUT: u8 = *REF_IMMUT;

fn main() {}

````
</p>
</details>

Version information
````
rustc 1.78.0-nightly (f8131a48a 2024-02-21)
binary: rustc
commit-hash: f8131a48a46ac3bc8a3d0fe0477055b132cffdc3
commit-date: 2024-02-21
host: x86_64-unknown-linux-gnu
release: 1.78.0-nightly
LLVM version: 18.1.0

````

Command:
`/home/matthias/.rustup/toolchains/master/bin/rustc -Zcrate-attr=feature(const_refs_to_static)`

<details><summary><strong>Program output</strong></summary>
<p>

```
error[E0433]: failed to resolve: use of undeclared type `AtomicUsize`
 --> /tmp/icemaker_global_tempdir.d8C7FanUdfBa/rustc_testrunner_tmpdir_reporting.T2pxA13oISa0/mvce.rs:2:24
  |
2 |     static FOO: Sync = AtomicUsize::new(0);
  |                        ^^^^^^^^^^^ use of undeclared type `AtomicUsize`
  |
help: consider importing this struct
  |
1 + use std::sync::atomic::AtomicUsize;
  |

error[E0601]: `main` function not found in crate `mvce`
 --> /tmp/icemaker_global_tempdir.d8C7FanUdfBa/rustc_testrunner_tmpdir_reporting.T2pxA13oISa0/mvce.rs:4:3
  |
4 | };
  |   ^ consider adding a `main` function to `/tmp/icemaker_global_tempdir.d8C7FanUdfBa/rustc_testrunner_tmpdir_reporting.T2pxA13oISa0/mvce.rs`

warning: trait objects without an explicit `dyn` are deprecated
 --> /tmp/icemaker_global_tempdir.d8C7FanUdfBa/rustc_testrunner_tmpdir_reporting.T2pxA13oISa0/mvce.rs:2:17
  |
2 |     static FOO: Sync = AtomicUsize::new(0);
  |                 ^^^^
  |
  = warning: this is accepted in the current edition (Rust 2015) but is a hard error in Rust 2021!
  = note: for more information, see <https://doc.rust-lang.org/nightly/edition-guide/rust-2021/warnings-promoted-to-error.html>
  = note: `#[warn(bare_trait_objects)]` on by default
help: if this is an object-safe trait, use `dyn`
  |
2 |     static FOO: dyn Sync = AtomicUsize::new(0);
  |                 +++

error[E0277]: the size for values of type `(dyn Sync + 'static)` cannot be known at compilation time
 --> /tmp/icemaker_global_tempdir.d8C7FanUdfBa/rustc_testrunner_tmpdir_reporting.T2pxA13oISa0/mvce.rs:2:17
  |
2 |     static FOO: Sync = AtomicUsize::new(0);
  |                 ^^^^ doesn't have a size known at compile-time
  |
  = help: the trait `Sized` is not implemented for `(dyn Sync + 'static)`

error[E0277]: the size for values of type `(dyn Sync + 'static)` cannot be known at compilation time
 --> /tmp/icemaker_global_tempdir.d8C7FanUdfBa/rustc_testrunner_tmpdir_reporting.T2pxA13oISa0/mvce.rs:2:24
  |
2 |     static FOO: Sync = AtomicUsize::new(0);
  |                        ^^^^^^^^^^^^^^^^^^^ doesn't have a size known at compile-time
  |
  = help: the trait `Sized` is not implemented for `(dyn Sync + 'static)`
  = note: constant expressions must have a statically known size

error: internal compiler error: compiler/rustc_const_eval/src/interpret/cast.rs:215:42: ImmTy { imm: Scalar(alloc1), ty: *const dyn Sync } input to a fat-to-thin cast (*const dyn Sync -> *const usize)
 --> /tmp/icemaker_global_tempdir.d8C7FanUdfBa/rustc_testrunner_tmpdir_reporting.T2pxA13oISa0/mvce.rs:3:16
  |
3 |     unsafe { &*(&FOO as *const _ as *const usize) }
  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

thread 'rustc' panicked at /rustc/f8131a48a46ac3bc8a3d0fe0477055b132cffdc3/compiler/rustc_middle/src/util/bug.rs:34:50:
Box<dyn Any>
stack backtrace:
   0:     0x7fc94378caf6 - std::backtrace_rs::backtrace::libunwind::trace::hbec2edc838b433e2
                               at /rustc/f8131a48a46ac3bc8a3d0fe0477055b132cffdc3/library/std/src/../../backtrace/src/backtrace/libunwind.rs:104:5
   1:     0x7fc94378caf6 - std::backtrace_rs::backtrace::trace_unsynchronized::h88c30257ee0dd166
                               at /rustc/f8131a48a46ac3bc8a3d0fe0477055b132cffdc3/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7fc94378caf6 - std::sys_common::backtrace::_print_fmt::h9176654d509e3088
                               at /rustc/f8131a48a46ac3bc8a3d0fe0477055b132cffdc3/library/std/src/sys_common/backtrace.rs:68:5
   3:     0x7fc94378caf6 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h671feaee1776bf19
                               at /rustc/f8131a48a46ac3bc8a3d0fe0477055b132cffdc3/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x7fc9437dda7c - core::fmt::rt::Argument::fmt::h59605c83ae32d935
                               at /rustc/f8131a48a46ac3bc8a3d0fe0477055b132cffdc3/library/core/src/fmt/rt.rs:142:9
   5:     0x7fc9437dda7c - core::fmt::write::hf7af8dfcfd20db5b
                               at /rustc/f8131a48a46ac3bc8a3d0fe0477055b132cffdc3/library/core/src/fmt/mod.rs:1120:17
   6:     0x7fc9437814bf - std::io::Write::write_fmt::h92a5dbf489025e71
                               at /rustc/f8131a48a46ac3bc8a3d0fe0477055b132cffdc3/library/std/src/io/mod.rs:1846:15
   7:     0x7fc94378c8a4 - std::sys_common::backtrace::_print::h00080302d23998ae
                               at /rustc/f8131a48a46ac3bc8a3d0fe0477055b132cffdc3/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x7fc94378c8a4 - std::sys_common::backtrace::print::h6b23124445400245
                               at /rustc/f8131a48a46ac3bc8a3d0fe0477055b132cffdc3/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x7fc94378f5eb - std::panicking::default_hook::{{closure}}::hd67b2f9d36675a28
  10:     0x7fc94378f339 - std::panicking::default_hook::h10a39ef11c714e42
                               at /rustc/f8131a48a46ac3bc8a3d0fe0477055b132cffdc3/library/std/src/panicking.rs:292:9
  11:     0x7fc94667a94c - std[5a8e7f94216a9138]::panicking::update_hook::<alloc[e14ab1f516d287ab]::boxed::Box<rustc_driver_impl[e279e4f1fedd9109]::install_ice_hook::{closure#0}>>::{closure#0}
  12:     0x7fc94378fd50 - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h37ba37dc48823c1d
                               at /rustc/f8131a48a46ac3bc8a3d0fe0477055b132cffdc3/library/alloc/src/boxed.rs:2030:9
  13:     0x7fc94378fd50 - std::panicking::rust_panic_with_hook::he3e3bc7c345bf54b
                               at /rustc/f8131a48a46ac3bc8a3d0fe0477055b132cffdc3/library/std/src/panicking.rs:786:13
  14:     0x7fc9466a7524 - std[5a8e7f94216a9138]::panicking::begin_panic::<rustc_errors[34364e5c712fab73]::ExplicitBug>::{closure#0}
  15:     0x7fc9466a4176 - std[5a8e7f94216a9138]::sys_common::backtrace::__rust_end_short_backtrace::<std[5a8e7f94216a9138]::panicking::begin_panic<rustc_errors[34364e5c712fab73]::ExplicitBug>::{closure#0}, !>
  16:     0x7fc94669f936 - std[5a8e7f94216a9138]::panicking::begin_panic::<rustc_errors[34364e5c712fab73]::ExplicitBug>
  17:     0x7fc945017631 - <rustc_errors[34364e5c712fab73]::diagnostic::BugAbort as rustc_errors[34364e5c712fab73]::diagnostic::EmissionGuarantee>::emit_producing_guarantee
  18:     0x7fc946601f60 - rustc_middle[446dd094ad85939e]::util::bug::opt_span_bug_fmt::<rustc_span[adb133ac03280fc1]::span_encoding::Span>::{closure#0}
  19:     0x7fc94660217a - rustc_middle[446dd094ad85939e]::ty::context::tls::with_opt::<rustc_middle[446dd094ad85939e]::util::bug::opt_span_bug_fmt<rustc_span[adb133ac03280fc1]::span_encoding::Span>::{closure#0}, !>::{closure#0}
  20:     0x7fc9465f8e48 - rustc_middle[446dd094ad85939e]::ty::context::tls::with_context_opt::<rustc_middle[446dd094ad85939e]::ty::context::tls::with_opt<rustc_middle[446dd094ad85939e]::util::bug::opt_span_bug_fmt<rustc_span[adb133ac03280fc1]::span_encoding::Span>::{closure#0}, !>::{closure#0}, !>
  21:     0x7fc945c50f54 - rustc_middle[446dd094ad85939e]::util::bug::span_bug_fmt::<rustc_span[adb133ac03280fc1]::span_encoding::Span>
  22:     0x7fc94891a7e0 - rustc_const_eval[b7e9a6566b8f5ff6]::const_eval::eval_queries::eval_body_using_ecx::{closure#0}
  23:     0x7fc948876f23 - rustc_const_eval[b7e9a6566b8f5ff6]::const_eval::eval_queries::eval_in_interpreter
  24:     0x7fc947dfa938 - rustc_const_eval[b7e9a6566b8f5ff6]::const_eval::eval_queries::eval_to_allocation_raw_provider
  25:     0x7fc947dfa706 - rustc_query_impl[9d4c51777e2bb749]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[9d4c51777e2bb749]::query_impl::eval_to_allocation_raw::dynamic_query::{closure#2}::{closure#0}, rustc_middle[446dd094ad85939e]::query::erase::Erased<[u8; 24usize]>>
  26:     0x7fc94840ba51 - rustc_query_system[9b2ccfe41ae3bb1b]::query::plumbing::try_execute_query::<rustc_query_impl[9d4c51777e2bb749]::DynamicConfig<rustc_query_system[9b2ccfe41ae3bb1b]::query::caches::DefaultCache<rustc_middle[446dd094ad85939e]::ty::ParamEnvAnd<rustc_middle[446dd094ad85939e]::mir::interpret::GlobalId>, rustc_middle[446dd094ad85939e]::query::erase::Erased<[u8; 24usize]>>, false, false, false>, rustc_query_impl[9d4c51777e2bb749]::plumbing::QueryCtxt, false>
  27:     0x7fc94840b62c - rustc_query_impl[9d4c51777e2bb749]::query_impl::eval_to_allocation_raw::get_query_non_incr::__rust_end_short_backtrace
  28:     0x7fc947dfb60d - rustc_const_eval[b7e9a6566b8f5ff6]::const_eval::eval_queries::eval_to_const_value_raw_provider
  29:     0x7fc947dfb40c - rustc_query_impl[9d4c51777e2bb749]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[9d4c51777e2bb749]::query_impl::eval_to_const_value_raw::dynamic_query::{closure#2}::{closure#0}, rustc_middle[446dd094ad85939e]::query::erase::Erased<[u8; 24usize]>>
  30:     0x7fc94840ba14 - rustc_query_system[9b2ccfe41ae3bb1b]::query::plumbing::try_execute_query::<rustc_query_impl[9d4c51777e2bb749]::DynamicConfig<rustc_query_system[9b2ccfe41ae3bb1b]::query::caches::DefaultCache<rustc_middle[446dd094ad85939e]::ty::ParamEnvAnd<rustc_middle[446dd094ad85939e]::mir::interpret::GlobalId>, rustc_middle[446dd094ad85939e]::query::erase::Erased<[u8; 24usize]>>, false, false, false>, rustc_query_impl[9d4c51777e2bb749]::plumbing::QueryCtxt, false>
  31:     0x7fc94840b530 - rustc_query_impl[9d4c51777e2bb749]::query_impl::eval_to_const_value_raw::get_query_non_incr::__rust_end_short_backtrace
  32:     0x7fc9483afe6b - <rustc_middle[446dd094ad85939e]::query::plumbing::TyCtxtEnsure>::const_eval_poly
  33:     0x7fc9483adbd3 - rustc_hir_analysis[71d4294717f7f2b7]::check_crate
  34:     0x7fc9484a2dd3 - rustc_interface[7ca501d7f8f3a34f]::passes::analysis
  35:     0x7fc9484a2a29 - rustc_query_impl[9d4c51777e2bb749]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[9d4c51777e2bb749]::query_impl::analysis::dynamic_query::{closure#2}::{closure#0}, rustc_middle[446dd094ad85939e]::query::erase::Erased<[u8; 1usize]>>
  36:     0x7fc94873d4a5 - rustc_query_system[9b2ccfe41ae3bb1b]::query::plumbing::try_execute_query::<rustc_query_impl[9d4c51777e2bb749]::DynamicConfig<rustc_query_system[9b2ccfe41ae3bb1b]::query::caches::SingleCache<rustc_middle[446dd094ad85939e]::query::erase::Erased<[u8; 1usize]>>, false, false, false>, rustc_query_impl[9d4c51777e2bb749]::plumbing::QueryCtxt, false>
  37:     0x7fc94873d209 - rustc_query_impl[9d4c51777e2bb749]::query_impl::analysis::get_query_non_incr::__rust_end_short_backtrace
  38:     0x7fc94874c719 - rustc_interface[7ca501d7f8f3a34f]::interface::run_compiler::<core[85b4fd477ce5bb21]::result::Result<(), rustc_span[adb133ac03280fc1]::ErrorGuaranteed>, rustc_driver_impl[e279e4f1fedd9109]::run_compiler::{closure#0}>::{closure#0}
  39:     0x7fc9489be705 - std[5a8e7f94216a9138]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[7ca501d7f8f3a34f]::util::run_in_thread_with_globals<rustc_interface[7ca501d7f8f3a34f]::util::run_in_thread_pool_with_globals<rustc_interface[7ca501d7f8f3a34f]::interface::run_compiler<core[85b4fd477ce5bb21]::result::Result<(), rustc_span[adb133ac03280fc1]::ErrorGuaranteed>, rustc_driver_impl[e279e4f1fedd9109]::run_compiler::{closure#0}>::{closure#0}, core[85b4fd477ce5bb21]::result::Result<(), rustc_span[adb133ac03280fc1]::ErrorGuaranteed>>::{closure#0}, core[85b4fd477ce5bb21]::result::Result<(), rustc_span[adb133ac03280fc1]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[85b4fd477ce5bb21]::result::Result<(), rustc_span[adb133ac03280fc1]::ErrorGuaranteed>>
  40:     0x7fc9489be532 - <<std[5a8e7f94216a9138]::thread::Builder>::spawn_unchecked_<rustc_interface[7ca501d7f8f3a34f]::util::run_in_thread_with_globals<rustc_interface[7ca501d7f8f3a34f]::util::run_in_thread_pool_with_globals<rustc_interface[7ca501d7f8f3a34f]::interface::run_compiler<core[85b4fd477ce5bb21]::result::Result<(), rustc_span[adb133ac03280fc1]::ErrorGuaranteed>, rustc_driver_impl[e279e4f1fedd9109]::run_compiler::{closure#0}>::{closure#0}, core[85b4fd477ce5bb21]::result::Result<(), rustc_span[adb133ac03280fc1]::ErrorGuaranteed>>::{closure#0}, core[85b4fd477ce5bb21]::result::Result<(), rustc_span[adb133ac03280fc1]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[85b4fd477ce5bb21]::result::Result<(), rustc_span[adb133ac03280fc1]::ErrorGuaranteed>>::{closure#1} as core[85b4fd477ce5bb21]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  41:     0x7fc943799725 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h1bff3efb61c3fa6b
                               at /rustc/f8131a48a46ac3bc8a3d0fe0477055b132cffdc3/library/alloc/src/boxed.rs:2016:9
  42:     0x7fc943799725 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h83141cf549dced8a
                               at /rustc/f8131a48a46ac3bc8a3d0fe0477055b132cffdc3/library/alloc/src/boxed.rs:2016:9
  43:     0x7fc943799725 - std::sys::pal::unix::thread::Thread::new::thread_start::hbe9287fdd7c325bc
                               at /rustc/f8131a48a46ac3bc8a3d0fe0477055b132cffdc3/library/std/src/sys/pal/unix/thread.rs:108:17
  44:     0x7fc9435819eb - <unknown>
  45:     0x7fc9436057cc - <unknown>
  46:                0x0 - <unknown>

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.78.0-nightly (f8131a48a 2024-02-21) running on x86_64-unknown-linux-gnu

note: compiler flags: -Z crate-attr=feature(const_refs_to_static) -Z dump-mir-dir=dir

query stack during panic:
#0 [eval_to_allocation_raw] const-evaluating + checking `REF_INTERIOR_MUT`
#1 [eval_to_const_value_raw] simplifying constant for the type system `REF_INTERIOR_MUT`
#2 [analysis] running analysis passes on this crate
end of query stack
error: aborting due to 5 previous errors; 1 warning emitted

Some errors have detailed explanations: E0277, E0433, E0601.
For more information about an error, try `rustc --explain E0277`.

```

</p>
</details>

### LINKED ISSUE #121463: ICE: `non-ADT in struct pattern`
### Code

```Rust
#![feature(box_patterns)]

fn main() {
    // Test matching each shorthand notation for field patterns.
    let mut a = E::StructVar { boxed: Box::new(5_i32) };
    match a {
        E::StructVar { box boxed } => { }
    }
}
```

### Meta

`rustc --version --verbose`:
```
rustc 1.78.0-nightly (1bb3a9f67 2024-02-22)
binary: rustc
commit-hash: 1bb3a9f67a2ff6bd49c513ca1b8954237298c4b3
commit-date: 2024-02-22
host: x86_64-unknown-linux-gnu
release: 1.78.0-nightly
LLVM version: 18.1.0
```

### Error output

```
<output>
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
error: internal compiler error: compiler/rustc_passes/src/dead.rs:220:18: non-ADT in struct pattern
 --> 8B8ABEDF34D920D746BDE642A198548A323B94B40DDFECD48BC009BEC24F1745.rs:7:9
  |
7 |         E::StructVar { box boxed } => { }
  |         ^^^^^^^^^^^^^^^^^^^^^^^^^^

thread 'rustc' panicked at /rustc/1bb3a9f67a2ff6bd49c513ca1b8954237298c4b3/compiler/rustc_middle/src/util/bug.rs:34:50:
Box<dyn Any>
stack backtrace:
   0:     0x7fd77d98caf6 - std::backtrace_rs::backtrace::libunwind::trace::h78343d613c85aaed
                               at /rustc/1bb3a9f67a2ff6bd49c513ca1b8954237298c4b3/library/std/src/../../backtrace/src/backtrace/libunwind.rs:104:5
   1:     0x7fd77d98caf6 - std::backtrace_rs::backtrace::trace_unsynchronized::hcb93ce9229fc04d1
                               at /rustc/1bb3a9f67a2ff6bd49c513ca1b8954237298c4b3/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7fd77d98caf6 - std::sys_common::backtrace::_print_fmt::hd1deae191b645ce3
                               at /rustc/1bb3a9f67a2ff6bd49c513ca1b8954237298c4b3/library/std/src/sys_common/backtrace.rs:68:5
   3:     0x7fd77d98caf6 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h70c1692dc58e0c3d
                               at /rustc/1bb3a9f67a2ff6bd49c513ca1b8954237298c4b3/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x7fd77d9dda7c - core::fmt::rt::Argument::fmt::h3f3d607439a9453a
                               at /rustc/1bb3a9f67a2ff6bd49c513ca1b8954237298c4b3/library/core/src/fmt/rt.rs:142:9
   5:     0x7fd77d9dda7c - core::fmt::write::hfd04ed51dd5b9740
                               at /rustc/1bb3a9f67a2ff6bd49c513ca1b8954237298c4b3/library/core/src/fmt/mod.rs:1120:17
   6:     0x7fd77d98142f - std::io::Write::write_fmt::h61b6e15e92363464
                               at /rustc/1bb3a9f67a2ff6bd49c513ca1b8954237298c4b3/library/std/src/io/mod.rs:1846:15
   7:     0x7fd77d98c8a4 - std::sys_common::backtrace::_print::h864105160a5448a9
                               at /rustc/1bb3a9f67a2ff6bd49c513ca1b8954237298c4b3/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x7fd77d98c8a4 - std::sys_common::backtrace::print::ha7c3095d0e2711d4
                               at /rustc/1bb3a9f67a2ff6bd49c513ca1b8954237298c4b3/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x7fd77d98f5eb - std::panicking::default_hook::{{closure}}::hea9282e63bea107d
  10:     0x7fd77d98f339 - std::panicking::default_hook::h7450394991cabc1f
                               at /rustc/1bb3a9f67a2ff6bd49c513ca1b8954237298c4b3/library/std/src/panicking.rs:292:9
  11:     0x7fd78087122c - std[98ba4a421780dced]::panicking::update_hook::<alloc[d493190abddc557e]::boxed::Box<rustc_driver_impl[43b21fa76f9f6a29]::install_ice_hook::{closure#0}>>::{closure#0}
  12:     0x7fd77d98fd50 - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::hf5f4decde06499d8
                               at /rustc/1bb3a9f67a2ff6bd49c513ca1b8954237298c4b3/library/alloc/src/boxed.rs:2030:9
  13:     0x7fd77d98fd50 - std::panicking::rust_panic_with_hook::h4f5747f949537183
                               at /rustc/1bb3a9f67a2ff6bd49c513ca1b8954237298c4b3/library/std/src/panicking.rs:786:13
  14:     0x7fd78089d8d4 - std[98ba4a421780dced]::panicking::begin_panic::<rustc_errors[ae248042d377cb04]::ExplicitBug>::{closure#0}
  15:     0x7fd78089a7f6 - std[98ba4a421780dced]::sys_common::backtrace::__rust_end_short_backtrace::<std[98ba4a421780dced]::panicking::begin_panic<rustc_errors[ae248042d377cb04]::ExplicitBug>::{closure#0}, !>
  16:     0x7fd78089a4d6 - std[98ba4a421780dced]::panicking::begin_panic::<rustc_errors[ae248042d377cb04]::ExplicitBug>
  17:     0x7fd77f21c141 - <rustc_errors[ae248042d377cb04]::diagnostic::BugAbort as rustc_errors[ae248042d377cb04]::diagnostic::EmissionGuarantee>::emit_producing_guarantee
  18:     0x7fd780f5616d - rustc_middle[45b09470b66e946b]::util::bug::opt_span_bug_fmt::<rustc_span[e413bf6cc1fe2f31]::span_encoding::Span>::{closure#0}
  19:     0x7fd780f5619a - rustc_middle[45b09470b66e946b]::ty::context::tls::with_opt::<rustc_middle[45b09470b66e946b]::util::bug::opt_span_bug_fmt<rustc_span[e413bf6cc1fe2f31]::span_encoding::Span>::{closure#0}, !>::{closure#0}
  20:     0x7fd780f511f8 - rustc_middle[45b09470b66e946b]::ty::context::tls::with_context_opt::<rustc_middle[45b09470b66e946b]::ty::context::tls::with_opt<rustc_middle[45b09470b66e946b]::util::bug::opt_span_bug_fmt<rustc_span[e413bf6cc1fe2f31]::span_encoding::Span>::{closure#0}, !>::{closure#0}, !>
  21:     0x7fd780f4fcb4 - rustc_middle[45b09470b66e946b]::util::bug::span_bug_fmt::<rustc_span[e413bf6cc1fe2f31]::span_encoding::Span>
  22:     0x7fd781f40648 - <rustc_passes[d8b4d4ae9293dc75]::dead::MarkSymbolVisitor as rustc_hir[8a1acb4dd3fb9914]::intravisit::Visitor>::visit_pat
  23:     0x7fd781cf5b7d - <rustc_passes[d8b4d4ae9293dc75]::dead::MarkSymbolVisitor as rustc_hir[8a1acb4dd3fb9914]::intravisit::Visitor>::visit_expr
  24:     0x7fd781f3d849 - rustc_hir[8a1acb4dd3fb9914]::intravisit::walk_item::<rustc_passes[d8b4d4ae9293dc75]::dead::MarkSymbolVisitor>
  25:     0x7fd782c346b7 - rustc_passes[d8b4d4ae9293dc75]::dead::live_symbols_and_ignored_derived_traits
  26:     0x7fd782c33854 - rustc_query_impl[b82009bdbcc4b375]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[b82009bdbcc4b375]::query_impl::live_symbols_and_ignored_derived_traits::dynamic_query::{closure#2}::{closure#0}, rustc_middle[45b09470b66e946b]::query::erase::Erased<[u8; 8usize]>>
  27:     0x7fd7828f240e - rustc_query_system[8095494ab80f3bc1]::query::plumbing::try_execute_query::<rustc_query_impl[b82009bdbcc4b375]::DynamicConfig<rustc_query_system[8095494ab80f3bc1]::query::caches::SingleCache<rustc_middle[45b09470b66e946b]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[b82009bdbcc4b375]::plumbing::QueryCtxt, false>
  28:     0x7fd7826d86c2 - rustc_query_impl[b82009bdbcc4b375]::query_impl::live_symbols_and_ignored_derived_traits::get_query_non_incr::__rust_end_short_backtrace
  29:     0x7fd7826d8863 - rustc_passes[d8b4d4ae9293dc75]::dead::check_mod_deathness
  30:     0x7fd7826d86e7 - rustc_query_impl[b82009bdbcc4b375]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[b82009bdbcc4b375]::query_impl::check_mod_deathness::dynamic_query::{closure#2}::{closure#0}, rustc_middle[45b09470b66e946b]::query::erase::Erased<[u8; 0usize]>>
  31:     0x7fd78281c76d - rustc_query_system[8095494ab80f3bc1]::query::plumbing::try_execute_query::<rustc_query_impl[b82009bdbcc4b375]::DynamicConfig<rustc_query_system[8095494ab80f3bc1]::query::caches::DefaultCache<rustc_span[e413bf6cc1fe2f31]::def_id::LocalModDefId, rustc_middle[45b09470b66e946b]::query::erase::Erased<[u8; 0usize]>>, false, false, false>, rustc_query_impl[b82009bdbcc4b375]::plumbing::QueryCtxt, false>
  32:     0x7fd7828183ff - rustc_query_impl[b82009bdbcc4b375]::query_impl::check_mod_deathness::get_query_non_incr::__rust_end_short_backtrace
  33:     0x7fd7828144cb - rustc_interface[8570b1b09719190c]::passes::analysis
  34:     0x7fd782813219 - rustc_query_impl[b82009bdbcc4b375]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[b82009bdbcc4b375]::query_impl::analysis::dynamic_query::{closure#2}::{closure#0}, rustc_middle[45b09470b66e946b]::query::erase::Erased<[u8; 1usize]>>
  35:     0x7fd7829d4665 - rustc_query_system[8095494ab80f3bc1]::query::plumbing::try_execute_query::<rustc_query_impl[b82009bdbcc4b375]::DynamicConfig<rustc_query_system[8095494ab80f3bc1]::query::caches::SingleCache<rustc_middle[45b09470b66e946b]::query::erase::Erased<[u8; 1usize]>>, false, false, false>, rustc_query_impl[b82009bdbcc4b375]::plumbing::QueryCtxt, false>
  36:     0x7fd7829d43c9 - rustc_query_impl[b82009bdbcc4b375]::query_impl::analysis::get_query_non_incr::__rust_end_short_backtrace
  37:     0x7fd782901816 - rustc_interface[8570b1b09719190c]::interface::run_compiler::<core[661a54f044942911]::result::Result<(), rustc_span[e413bf6cc1fe2f31]::ErrorGuaranteed>, rustc_driver_impl[43b21fa76f9f6a29]::run_compiler::{closure#0}>::{closure#0}
  38:     0x7fd782bc37cd - std[98ba4a421780dced]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[8570b1b09719190c]::util::run_in_thread_with_globals<rustc_interface[8570b1b09719190c]::util::run_in_thread_pool_with_globals<rustc_interface[8570b1b09719190c]::interface::run_compiler<core[661a54f044942911]::result::Result<(), rustc_span[e413bf6cc1fe2f31]::ErrorGuaranteed>, rustc_driver_impl[43b21fa76f9f6a29]::run_compiler::{closure#0}>::{closure#0}, core[661a54f044942911]::result::Result<(), rustc_span[e413bf6cc1fe2f31]::ErrorGuaranteed>>::{closure#0}, core[661a54f044942911]::result::Result<(), rustc_span[e413bf6cc1fe2f31]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[661a54f044942911]::result::Result<(), rustc_span[e413bf6cc1fe2f31]::ErrorGuaranteed>>
  39:     0x7fd782bc35fa - <<std[98ba4a421780dced]::thread::Builder>::spawn_unchecked_<rustc_interface[8570b1b09719190c]::util::run_in_thread_with_globals<rustc_interface[8570b1b09719190c]::util::run_in_thread_pool_with_globals<rustc_interface[8570b1b09719190c]::interface::run_compiler<core[661a54f044942911]::result::Result<(), rustc_span[e413bf6cc1fe2f31]::ErrorGuaranteed>, rustc_driver_impl[43b21fa76f9f6a29]::run_compiler::{closure#0}>::{closure#0}, core[661a54f044942911]::result::Result<(), rustc_span[e413bf6cc1fe2f31]::ErrorGuaranteed>>::{closure#0}, core[661a54f044942911]::result::Result<(), rustc_span[e413bf6cc1fe2f31]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[661a54f044942911]::result::Result<(), rustc_span[e413bf6cc1fe2f31]::ErrorGuaranteed>>::{closure#1} as core[661a54f044942911]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  40:     0x7fd77d999725 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hd65baaf671f21b42
                               at /rustc/1bb3a9f67a2ff6bd49c513ca1b8954237298c4b3/library/alloc/src/boxed.rs:2016:9
  41:     0x7fd77d999725 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h62863cb5d3d6dd44
                               at /rustc/1bb3a9f67a2ff6bd49c513ca1b8954237298c4b3/library/alloc/src/boxed.rs:2016:9
  42:     0x7fd77d999725 - std::sys::pal::unix::thread::Thread::new::thread_start::h59a3dc623978ddf5
                               at /rustc/1bb3a9f67a2ff6bd49c513ca1b8954237298c4b3/library/std/src/sys/pal/unix/thread.rs:108:17
  43:     0x7fd77d694ac3 - start_thread
                               at ./nptl/pthread_create.c:442:8
  44:     0x7fd77d726850 - __GI___clone3
                               at ./misc/../sysdeps/unix/sysv/linux/x86_64/clone3.S:81
  45:                0x0 - <unknown>

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: please attach the file at `/home/gh-matthiaskrgr/im/rustc-ice-2024-02-22T16_09_14-2465108.txt` to your bug report

query stack during panic:
#0 [live_symbols_and_ignored_derived_traits] finding live symbols in crate
#1 [check_mod_deathness] checking deathness of variables in top-level module
#2 [analysis] running analysis passes on this crate
end of query stack
thread 'rustc' panicked at compiler/rustc_lint/src/builtin.rs:252:18:
struct pattern type is not an ADT
stack backtrace:
   0:     0x7fd77d98caf6 - std::backtrace_rs::backtrace::libunwind::trace::h78343d613c85aaed
                               at /rustc/1bb3a9f67a2ff6bd49c513ca1b8954237298c4b3/library/std/src/../../backtrace/src/backtrace/libunwind.rs:104:5
   1:     0x7fd77d98caf6 - std::backtrace_rs::backtrace::trace_unsynchronized::hcb93ce9229fc04d1
                               at /rustc/1bb3a9f67a2ff6bd49c513ca1b8954237298c4b3/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7fd77d98caf6 - std::sys_common::backtrace::_print_fmt::hd1deae191b645ce3
                               at /rustc/1bb3a9f67a2ff6bd49c513ca1b8954237298c4b3/library/std/src/sys_common/backtrace.rs:68:5
   3:     0x7fd77d98caf6 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h70c1692dc58e0c3d
                               at /rustc/1bb3a9f67a2ff6bd49c513ca1b8954237298c4b3/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x7fd77d9dda7c - core::fmt::rt::Argument::fmt::h3f3d607439a9453a
                               at /rustc/1bb3a9f67a2ff6bd49c513ca1b8954237298c4b3/library/core/src/fmt/rt.rs:142:9
   5:     0x7fd77d9dda7c - core::fmt::write::hfd04ed51dd5b9740
                               at /rustc/1bb3a9f67a2ff6bd49c513ca1b8954237298c4b3/library/core/src/fmt/mod.rs:1120:17
   6:     0x7fd77d98142f - std::io::Write::write_fmt::h61b6e15e92363464
                               at /rustc/1bb3a9f67a2ff6bd49c513ca1b8954237298c4b3/library/std/src/io/mod.rs:1846:15
   7:     0x7fd77d98c8a4 - std::sys_common::backtrace::_print::h864105160a5448a9
                               at /rustc/1bb3a9f67a2ff6bd49c513ca1b8954237298c4b3/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x7fd77d98c8a4 - std::sys_common::backtrace::print::ha7c3095d0e2711d4
                               at /rustc/1bb3a9f67a2ff6bd49c513ca1b8954237298c4b3/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x7fd77d98f5eb - std::panicking::default_hook::{{closure}}::hea9282e63bea107d
  10:     0x7fd77d98f339 - std::panicking::default_hook::h7450394991cabc1f
                               at /rustc/1bb3a9f67a2ff6bd49c513ca1b8954237298c4b3/library/std/src/panicking.rs:292:9
  11:     0x7fd78087122c - std[98ba4a421780dced]::panicking::update_hook::<alloc[d493190abddc557e]::boxed::Box<rustc_driver_impl[43b21fa76f9f6a29]::install_ice_hook::{closure#0}>>::{closure#0}
  12:     0x7fd77d98fd50 - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::hf5f4decde06499d8
                               at /rustc/1bb3a9f67a2ff6bd49c513ca1b8954237298c4b3/library/alloc/src/boxed.rs:2030:9
  13:     0x7fd77d98fd50 - std::panicking::rust_panic_with_hook::h4f5747f949537183
                               at /rustc/1bb3a9f67a2ff6bd49c513ca1b8954237298c4b3/library/std/src/panicking.rs:786:13
  14:     0x7fd77d98fa92 - std::panicking::begin_panic_handler::{{closure}}::h2bf422a8e9958832
                               at /rustc/1bb3a9f67a2ff6bd49c513ca1b8954237298c4b3/library/std/src/panicking.rs:660:13
  15:     0x7fd77d98cfd6 - std::sys_common::backtrace::__rust_end_short_backtrace::hdd8f30de5eecf779
                               at /rustc/1bb3a9f67a2ff6bd49c513ca1b8954237298c4b3/library/std/src/sys_common/backtrace.rs:171:18
  16:     0x7fd77d98f7c4 - rust_begin_unwind
                               at /rustc/1bb3a9f67a2ff6bd49c513ca1b8954237298c4b3/library/std/src/panicking.rs:648:5
  17:     0x7fd77d9d9f95 - core::panicking::panic_fmt::h1acf842fb807f6d2
                               at /rustc/1bb3a9f67a2ff6bd49c513ca1b8954237298c4b3/library/core/src/panicking.rs:72:14
  18:     0x7fd77d9da161 - core::panicking::panic_display::h849dd7a88e7c18d3
                               at /rustc/1bb3a9f67a2ff6bd49c513ca1b8954237298c4b3/library/core/src/panicking.rs:196:5
  19:     0x7fd77d9d9d4b - core::panicking::panic_str::h32e8f6136e6a9754
                               at /rustc/1bb3a9f67a2ff6bd49c513ca1b8954237298c4b3/library/core/src/panicking.rs:171:5
  20:     0x7fd77d9d9d4b - core::option::expect_failed::hd7b050aef2f2dc00
                               at /rustc/1bb3a9f67a2ff6bd49c513ca1b8954237298c4b3/library/core/src/option.rs:1993:5
  21:     0x7fd781f414b2 - <rustc_lint[5f8b1185717f607]::late::LateContextAndPass<rustc_lint[5f8b1185717f607]::BuiltinCombinedModuleLateLintPass> as rustc_hir[8a1acb4dd3fb9914]::intravisit::Visitor>::visit_pat
  22:     0x7fd781e03919 - <rustc_lint[5f8b1185717f607]::late::LateContextAndPass<rustc_lint[5f8b1185717f607]::BuiltinCombinedModuleLateLintPass> as rustc_hir[8a1acb4dd3fb9914]::intravisit::Visitor>::visit_expr
  23:     0x7fd781e020fa - <rustc_lint[5f8b1185717f607]::late::LateContextAndPass<rustc_lint[5f8b1185717f607]::BuiltinCombinedModuleLateLintPass> as rustc_hir[8a1acb4dd3fb9914]::intravisit::Visitor>::visit_block
  24:     0x7fd781e02f73 - <rustc_lint[5f8b1185717f607]::late::LateContextAndPass<rustc_lint[5f8b1185717f607]::BuiltinCombinedModuleLateLintPass> as rustc_hir[8a1acb4dd3fb9914]::intravisit::Visitor>::visit_expr::{closure#0}
  25:     0x7fd781ffd211 - <rustc_lint[5f8b1185717f607]::late::LateContextAndPass<rustc_lint[5f8b1185717f607]::BuiltinCombinedModuleLateLintPass> as rustc_hir[8a1acb4dd3fb9914]::intravisit::Visitor>::visit_nested_body
  26:     0x7fd781fa86a5 - <rustc_lint[5f8b1185717f607]::late::LateContextAndPass<rustc_lint[5f8b1185717f607]::BuiltinCombinedModuleLateLintPass> as rustc_hir[8a1acb4dd3fb9914]::intravisit::Visitor>::visit_nested_item
  27:     0x7fd781fa6a7f - rustc_lint[5f8b1185717f607]::lint_mod
  28:     0x7fd781fa6867 - rustc_query_impl[b82009bdbcc4b375]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[b82009bdbcc4b375]::query_impl::lint_mod::dynamic_query::{closure#2}::{closure#0}, rustc_middle[45b09470b66e946b]::query::erase::Erased<[u8; 0usize]>>
  29:     0x7fd78281c76d - rustc_query_system[8095494ab80f3bc1]::query::plumbing::try_execute_query::<rustc_query_impl[b82009bdbcc4b375]::DynamicConfig<rustc_query_system[8095494ab80f3bc1]::query::caches::DefaultCache<rustc_span[e413bf6cc1fe2f31]::def_id::LocalModDefId, rustc_middle[45b09470b66e946b]::query::erase::Erased<[u8; 0usize]>>, false, false, false>, rustc_query_impl[b82009bdbcc4b375]::plumbing::QueryCtxt, false>
  30:     0x7fd78281b07f - rustc_query_impl[b82009bdbcc4b375]::query_impl::lint_mod::get_query_non_incr::__rust_end_short_backtrace
  31:     0x7fd78281ac1f - rustc_lint[5f8b1185717f607]::late::check_crate::{closure#1}
  32:     0x7fd78281a61e - rustc_lint[5f8b1185717f607]::late::check_crate
  33:     0x7fd782814525 - rustc_interface[8570b1b09719190c]::passes::analysis
  34:     0x7fd782813219 - rustc_query_impl[b82009bdbcc4b375]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[b82009bdbcc4b375]::query_impl::analysis::dynamic_query::{closure#2}::{closure#0}, rustc_middle[45b09470b66e946b]::query::erase::Erased<[u8; 1usize]>>
  35:     0x7fd7829d4665 - rustc_query_system[8095494ab80f3bc1]::query::plumbing::try_execute_query::<rustc_query_impl[b82009bdbcc4b375]::DynamicConfig<rustc_query_system[8095494ab80f3bc1]::query::caches::SingleCache<rustc_middle[45b09470b66e946b]::query::erase::Erased<[u8; 1usize]>>, false, false, false>, rustc_query_impl[b82009bdbcc4b375]::plumbing::QueryCtxt, false>
  36:     0x7fd7829d43c9 - rustc_query_impl[b82009bdbcc4b375]::query_impl::analysis::get_query_non_incr::__rust_end_short_backtrace
  37:     0x7fd782901816 - rustc_interface[8570b1b09719190c]::interface::run_compiler::<core[661a54f044942911]::result::Result<(), rustc_span[e413bf6cc1fe2f31]::ErrorGuaranteed>, rustc_driver_impl[43b21fa76f9f6a29]::run_compiler::{closure#0}>::{closure#0}
  38:     0x7fd782bc37cd - std[98ba4a421780dced]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[8570b1b09719190c]::util::run_in_thread_with_globals<rustc_interface[8570b1b09719190c]::util::run_in_thread_pool_with_globals<rustc_interface[8570b1b09719190c]::interface::run_compiler<core[661a54f044942911]::result::Result<(), rustc_span[e413bf6cc1fe2f31]::ErrorGuaranteed>, rustc_driver_impl[43b21fa76f9f6a29]::run_compiler::{closure#0}>::{closure#0}, core[661a54f044942911]::result::Result<(), rustc_span[e413bf6cc1fe2f31]::ErrorGuaranteed>>::{closure#0}, core[661a54f044942911]::result::Result<(), rustc_span[e413bf6cc1fe2f31]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[661a54f044942911]::result::Result<(), rustc_span[e413bf6cc1fe2f31]::ErrorGuaranteed>>
  39:     0x7fd782bc35fa - <<std[98ba4a421780dced]::thread::Builder>::spawn_unchecked_<rustc_interface[8570b1b09719190c]::util::run_in_thread_with_globals<rustc_interface[8570b1b09719190c]::util::run_in_thread_pool_with_globals<rustc_interface[8570b1b09719190c]::interface::run_compiler<core[661a54f044942911]::result::Result<(), rustc_span[e413bf6cc1fe2f31]::ErrorGuaranteed>, rustc_driver_impl[43b21fa76f9f6a29]::run_compiler::{closure#0}>::{closure#0}, core[661a54f044942911]::result::Result<(), rustc_span[e413bf6cc1fe2f31]::ErrorGuaranteed>>::{closure#0}, core[661a54f044942911]::result::Result<(), rustc_span[e413bf6cc1fe2f31]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[661a54f044942911]::result::Result<(), rustc_span[e413bf6cc1fe2f31]::ErrorGuaranteed>>::{closure#1} as core[661a54f044942911]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  40:     0x7fd77d999725 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hd65baaf671f21b42
                               at /rustc/1bb3a9f67a2ff6bd49c513ca1b8954237298c4b3/library/alloc/src/boxed.rs:2016:9
  41:     0x7fd77d999725 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h62863cb5d3d6dd44
                               at /rustc/1bb3a9f67a2ff6bd49c513ca1b8954237298c4b3/library/alloc/src/boxed.rs:2016:9
  42:     0x7fd77d999725 - std::sys::pal::unix::thread::Thread::new::thread_start::h59a3dc623978ddf5
                               at /rustc/1bb3a9f67a2ff6bd49c513ca1b8954237298c4b3/library/std/src/sys/pal/unix/thread.rs:108:17
  43:     0x7fd77d694ac3 - start_thread
                               at ./nptl/pthread_create.c:442:8
  44:     0x7fd77d726850 - __GI___clone3
                               at ./misc/../sysdeps/unix/sysv/linux/x86_64/clone3.S:81
  45:                0x0 - <unknown>

error: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: please attach the file at `/home/gh-matthiaskrgr/im/rustc-ice-2024-02-22T16_09_14-2465108.txt` to your bug report

query stack during panic:
#0 [lint_mod] linting top-level module
#1 [analysis] running analysis passes on this crate
end of query stack
thread 'rustc' panicked at compiler/rustc_privacy/src/lib.rs:991:72:
called `Option::unwrap()` on a `None` value
stack backtrace:
   0:     0x7fd77d98caf6 - std::backtrace_rs::backtrace::libunwind::trace::h78343d613c85aaed
                               at /rustc/1bb3a9f67a2ff6bd49c513ca1b8954237298c4b3/library/std/src/../../backtrace/src/backtrace/libunwind.rs:104:5
   1:     0x7fd77d98caf6 - std::backtrace_rs::backtrace::trace_unsynchronized::hcb93ce9229fc04d1
                               at /rustc/1bb3a9f67a2ff6bd49c513ca1b8954237298c4b3/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7fd77d98caf6 - std::sys_common::backtrace::_print_fmt::hd1deae191b645ce3
                               at /rustc/1bb3a9f67a2ff6bd49c513ca1b8954237298c4b3/library/std/src/sys_common/backtrace.rs:68:5
   3:     0x7fd77d98caf6 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h70c1692dc58e0c3d
                               at /rustc/1bb3a9f67a2ff6bd49c513ca1b8954237298c4b3/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x7fd77d9dda7c - core::fmt::rt::Argument::fmt::h3f3d607439a9453a
                               at /rustc/1bb3a9f67a2ff6bd49c513ca1b8954237298c4b3/library/core/src/fmt/rt.rs:142:9
   5:     0x7fd77d9dda7c - core::fmt::write::hfd04ed51dd5b9740
                               at /rustc/1bb3a9f67a2ff6bd49c513ca1b8954237298c4b3/library/core/src/fmt/mod.rs:1120:17
   6:     0x7fd77d98142f - std::io::Write::write_fmt::h61b6e15e92363464
                               at /rustc/1bb3a9f67a2ff6bd49c513ca1b8954237298c4b3/library/std/src/io/mod.rs:1846:15
   7:     0x7fd77d98c8a4 - std::sys_common::backtrace::_print::h864105160a5448a9
                               at /rustc/1bb3a9f67a2ff6bd49c513ca1b8954237298c4b3/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x7fd77d98c8a4 - std::sys_common::backtrace::print::ha7c3095d0e2711d4
                               at /rustc/1bb3a9f67a2ff6bd49c513ca1b8954237298c4b3/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x7fd77d98f5eb - std::panicking::default_hook::{{closure}}::hea9282e63bea107d
  10:     0x7fd77d98f339 - std::panicking::default_hook::h7450394991cabc1f
                               at /rustc/1bb3a9f67a2ff6bd49c513ca1b8954237298c4b3/library/std/src/panicking.rs:292:9
  11:     0x7fd78087122c - std[98ba4a421780dced]::panicking::update_hook::<alloc[d493190abddc557e]::boxed::Box<rustc_driver_impl[43b21fa76f9f6a29]::install_ice_hook::{closure#0}>>::{closure#0}
  12:     0x7fd77d98fd50 - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::hf5f4decde06499d8
                               at /rustc/1bb3a9f67a2ff6bd49c513ca1b8954237298c4b3/library/alloc/src/boxed.rs:2030:9
  13:     0x7fd77d98fd50 - std::panicking::rust_panic_with_hook::h4f5747f949537183
                               at /rustc/1bb3a9f67a2ff6bd49c513ca1b8954237298c4b3/library/std/src/panicking.rs:786:13
  14:     0x7fd77d98fa59 - std::panicking::begin_panic_handler::{{closure}}::h2bf422a8e9958832
                               at /rustc/1bb3a9f67a2ff6bd49c513ca1b8954237298c4b3/library/std/src/panicking.rs:652:13
  15:     0x7fd77d98cfd6 - std::sys_common::backtrace::__rust_end_short_backtrace::hdd8f30de5eecf779
                               at /rustc/1bb3a9f67a2ff6bd49c513ca1b8954237298c4b3/library/std/src/sys_common/backtrace.rs:171:18
  16:     0x7fd77d98f7c4 - rust_begin_unwind
                               at /rustc/1bb3a9f67a2ff6bd49c513ca1b8954237298c4b3/library/std/src/panicking.rs:648:5
  17:     0x7fd77d9d9f95 - core::panicking::panic_fmt::h1acf842fb807f6d2
                               at /rustc/1bb3a9f67a2ff6bd49c513ca1b8954237298c4b3/library/core/src/panicking.rs:72:14
  18:     0x7fd77d9da053 - core::panicking::panic::h3862563359bfda52
                               at /rustc/1bb3a9f67a2ff6bd49c513ca1b8954237298c4b3/library/core/src/panicking.rs:144:5
  19:     0x7fd77d9d9d26 - core::option::unwrap_failed::hd5db12df658732a1
                               at /rustc/1bb3a9f67a2ff6bd49c513ca1b8954237298c4b3/library/core/src/option.rs:1983:5
  20:     0x7fd781c6a6ff - <rustc_privacy[af9ea50042ee2161]::NamePrivacyVisitor as rustc_hir[8a1acb4dd3fb9914]::intravisit::Visitor>::visit_expr
  21:     0x7fd781c69a15 - <rustc_privacy[af9ea50042ee2161]::NamePrivacyVisitor as rustc_hir[8a1acb4dd3fb9914]::intravisit::Visitor>::visit_block
  22:     0x7fd781c69ae2 - <rustc_privacy[af9ea50042ee2161]::NamePrivacyVisitor as rustc_hir[8a1acb4dd3fb9914]::intravisit::Visitor>::visit_expr
  23:     0x7fd7821c184e - rustc_privacy[af9ea50042ee2161]::check_mod_privacy
  24:     0x7fd7821c1633 - rustc_query_impl[b82009bdbcc4b375]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[b82009bdbcc4b375]::query_impl::check_mod_privacy::dynamic_query::{closure#2}::{closure#0}, rustc_middle[45b09470b66e946b]::query::erase::Erased<[u8; 0usize]>>
  25:     0x7fd78281c76d - rustc_query_system[8095494ab80f3bc1]::query::plumbing::try_execute_query::<rustc_query_impl[b82009bdbcc4b375]::DynamicConfig<rustc_query_system[8095494ab80f3bc1]::query::caches::DefaultCache<rustc_span[e413bf6cc1fe2f31]::def_id::LocalModDefId, rustc_middle[45b09470b66e946b]::query::erase::Erased<[u8; 0usize]>>, false, false, false>, rustc_query_impl[b82009bdbcc4b375]::plumbing::QueryCtxt, false>
  26:     0x7fd78281823f - rustc_query_impl[b82009bdbcc4b375]::query_impl::check_mod_privacy::get_query_non_incr::__rust_end_short_backtrace
  27:     0x7fd78281463c - rustc_interface[8570b1b09719190c]::passes::analysis
  28:     0x7fd782813219 - rustc_query_impl[b82009bdbcc4b375]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[b82009bdbcc4b375]::query_impl::analysis::dynamic_query::{closure#2}::{closure#0}, rustc_middle[45b09470b66e946b]::query::erase::Erased<[u8; 1usize]>>
  29:     0x7fd7829d4665 - rustc_query_system[8095494ab80f3bc1]::query::plumbing::try_execute_query::<rustc_query_impl[b82009bdbcc4b375]::DynamicConfig<rustc_query_system[8095494ab80f3bc1]::query::caches::SingleCache<rustc_middle[45b09470b66e946b]::query::erase::Erased<[u8; 1usize]>>, false, false, false>, rustc_query_impl[b82009bdbcc4b375]::plumbing::QueryCtxt, false>
  30:     0x7fd7829d43c9 - rustc_query_impl[b82009bdbcc4b375]::query_impl::analysis::get_query_non_incr::__rust_end_short_backtrace
  31:     0x7fd782901816 - rustc_interface[8570b1b09719190c]::interface::run_compiler::<core[661a54f044942911]::result::Result<(), rustc_span[e413bf6cc1fe2f31]::ErrorGuaranteed>, rustc_driver_impl[43b21fa76f9f6a29]::run_compiler::{closure#0}>::{closure#0}
  32:     0x7fd782bc37cd - std[98ba4a421780dced]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[8570b1b09719190c]::util::run_in_thread_with_globals<rustc_interface[8570b1b09719190c]::util::run_in_thread_pool_with_globals<rustc_interface[8570b1b09719190c]::interface::run_compiler<core[661a54f044942911]::result::Result<(), rustc_span[e413bf6cc1fe2f31]::ErrorGuaranteed>, rustc_driver_impl[43b21fa76f9f6a29]::run_compiler::{closure#0}>::{closure#0}, core[661a54f044942911]::result::Result<(), rustc_span[e413bf6cc1fe2f31]::ErrorGuaranteed>>::{closure#0}, core[661a54f044942911]::result::Result<(), rustc_span[e413bf6cc1fe2f31]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[661a54f044942911]::result::Result<(), rustc_span[e413bf6cc1fe2f31]::ErrorGuaranteed>>
  33:     0x7fd782bc35fa - <<std[98ba4a421780dced]::thread::Builder>::spawn_unchecked_<rustc_interface[8570b1b09719190c]::util::run_in_thread_with_globals<rustc_interface[8570b1b09719190c]::util::run_in_thread_pool_with_globals<rustc_interface[8570b1b09719190c]::interface::run_compiler<core[661a54f044942911]::result::Result<(), rustc_span[e413bf6cc1fe2f31]::ErrorGuaranteed>, rustc_driver_impl[43b21fa76f9f6a29]::run_compiler::{closure#0}>::{closure#0}, core[661a54f044942911]::result::Result<(), rustc_span[e413bf6cc1fe2f31]::ErrorGuaranteed>>::{closure#0}, core[661a54f044942911]::result::Result<(), rustc_span[e413bf6cc1fe2f31]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[661a54f044942911]::result::Result<(), rustc_span[e413bf6cc1fe2f31]::ErrorGuaranteed>>::{closure#1} as core[661a54f044942911]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  34:     0x7fd77d999725 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hd65baaf671f21b42
                               at /rustc/1bb3a9f67a2ff6bd49c513ca1b8954237298c4b3/library/alloc/src/boxed.rs:2016:9
  35:     0x7fd77d999725 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h62863cb5d3d6dd44
                               at /rustc/1bb3a9f67a2ff6bd49c513ca1b8954237298c4b3/library/alloc/src/boxed.rs:2016:9
  36:     0x7fd77d999725 - std::sys::pal::unix::thread::Thread::new::thread_start::h59a3dc623978ddf5
                               at /rustc/1bb3a9f67a2ff6bd49c513ca1b8954237298c4b3/library/std/src/sys/pal/unix/thread.rs:108:17
  37:     0x7fd77d694ac3 - start_thread
                               at ./nptl/pthread_create.c:442:8
  38:     0x7fd77d726850 - __GI___clone3
                               at ./misc/../sysdeps/unix/sysv/linux/x86_64/clone3.S:81
  39:                0x0 - <unknown>

error: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: please attach the file at `/home/gh-matthiaskrgr/im/rustc-ice-2024-02-22T16_09_14-2465108.txt` to your bug report

query stack during panic:
#0 [check_mod_privacy] checking privacy in top-level module
#1 [analysis] running analysis passes on this crate
end of query stack
error[E0433]: failed to resolve: use of undeclared type `E`
 --> 8B8ABEDF34D920D746BDE642A198548A323B94B40DDFECD48BC009BEC24F1745.rs:5:17
  |
5 |     let mut a = E::StructVar { boxed: Box::new(5_i32) };
  |                 ^
  |                 |
  |                 use of undeclared type `E`
  |                 help: a trait with a similar name exists: `Eq`

error[E0433]: failed to resolve: use of undeclared type `E`
 --> 8B8ABEDF34D920D746BDE642A198548A323B94B40DDFECD48BC009BEC24F1745.rs:7:9
  |
7 |         E::StructVar { box boxed } => { }
  |         ^
  |         |
  |         use of undeclared type `E`
  |         help: a trait with a similar name exists: `Eq`

error: aborting due to 3 previous errors

For more information about this error, try `rustc --explain E0433`.
```

</p>
</details>

### PR DESCRIPTION
**Pull request by matthiaskrgr**
Fixes https://github.com/rust-lang/rust/issues/121413
Fixes https://github.com/rust-lang/rust/issues/121463
Fixes https://github.com/rust-lang/rust/issues/114463

### CODE REVIEW

File: tests/ui/async-await/lifetime-name-annotation-2021-ice-123420.rs [hunk 1]
```diff
@@ -0,0 +1,18 @@
+// issue rust-lang/rust#123420
+// ICE assertion failed: i32 != &'{erased} mut i32
+//@ edition:2021
+#![feature(async_closure)]
```
Comment (compiler-errors) [inline tests/ui/async-await/lifetime-name-annotation-2021-ice-123420.rs:4]: this should go into `async-await/async-closures`

**Review by compiler-errors — CHANGES_REQUESTED** [review]

File: tests/ui/async-await/lifetime-name-annotation-2021-ice-123420.rs (hunk 1 above)
Comment (compiler-errors) [reply tests/ui/async-await/lifetime-name-annotation-2021-ice-123420.rs:4]: also, i don't think we even need this test. I added enough tests in #123660.

Comment (matthiaskrgr) [reply tests/ui/async-await/lifetime-name-annotation-2021-ice-123420.rs:4]: ah neat; I'll boot this one then :)
