### PR TITLE
Suppress fallback and ambiguity errors

### LINKED ISSUE #31997: Resolve failures cause too many typechecking failures
I noticed that on https://github.com/rust-lang/rust/pull/31618 there was a [resolve failure](https://gist.github.com/alexcrichton/f8ac0ed0b8a7f5c55be5) from [this line](https://github.com/alexcrichton/rust/blob/58e96a897252ffb78f810722272106bb4bdefb1c/src/libstd/sys/unix/pipe.rs#L94), specifically:

```
../src/libstd/sys/unix/pipe.rs:94:13: 94:25 error: unresolved name `libc::select` [E0425]
../src/libstd/sys/unix/pipe.rs:94             libc::select(max + 1, &mut read, 0 as *mut _, 0 as *mut _,
                                              ^~~~~~~~~~~~
../src/libstd/sys/unix/pipe.rs:90:9: 96:13 note: in this expansion of try! (defined in <core macros>)
../src/libstd/sys/unix/pipe.rs:94:13: 94:25 help: run `rustc --explain E0425` to see a detailed explanation
../src/libstd/sys/unix/pipe.rs:90:14: 90:19 error: the trait `core::num::One` is not implemented for the type `()` [E0277]
../src/libstd/sys/unix/pipe.rs:90         try!(cvt_r(|| unsafe {
                                               ^~~~~
../src/libstd/sys/unix/pipe.rs:90:9: 96:13 note: in this expansion of try! (defined in <core macros>)
../src/libstd/sys/unix/pipe.rs:90:14: 90:19 help: run `rustc --explain E0277` to see a detailed explanation
../src/libstd/sys/unix/pipe.rs:90:14: 90:19 note: required by `sys::cvt_r`
../src/libstd/sys/unix/pipe.rs:90:14: 90:19 error: the trait `core::ops::Neg` is not implemented for the type `()` [E0277]
../src/libstd/sys/unix/pipe.rs:90         try!(cvt_r(|| unsafe {
                                               ^~~~~
../src/libstd/sys/unix/pipe.rs:90:9: 96:13 note: in this expansion of try! (defined in <core macros>)
../src/libstd/sys/unix/pipe.rs:90:14: 90:19 help: run `rustc --explain E0277` to see a detailed explanation
../src/libstd/sys/unix/pipe.rs:90:14: 90:19 note: required by `sys::cvt_r`
../src/libstd/sys/unix/pipe.rs:94:46: 94:57 error: casting `usize` as `*mut _` is invalid
../src/libstd/sys/unix/pipe.rs:94             libc::select(max + 1, &mut read, 0 as *mut _, 0 as *mut _,
                                                                               ^~~~~~~~~~~
../src/libstd/sys/unix/pipe.rs:90:9: 96:13 note: in this expansion of try! (defined in <core macros>)
../src/libstd/sys/unix/pipe.rs:94:59: 94:70 error: casting `usize` as `*mut _` is invalid
../src/libstd/sys/unix/pipe.rs:94             libc::select(max + 1, &mut read, 0 as *mut _, 0 as *mut _,
                                                                                            ^~~~~~~~~~~
../src/libstd/sys/unix/pipe.rs:90:9: 96:13 note: in this expansion of try! (defined in <core macros>)
../src/libstd/sys/unix/pipe.rs:95:26: 95:37 error: casting `usize` as `*mut _` is invalid
../src/libstd/sys/unix/pipe.rs:95                          0 as *mut _)
                                                           ^~~~~~~~~~~
../src/libstd/sys/unix/pipe.rs:90:9: 96:13 note: in this expansion of try! (defined in <core macros>)
```

The only real error here is that `libc::select` doesn't exist. All other errors are spawned off of this. This unfortunately makes it pretty hard to hunt through errors and figure out which ones need to get fixed, and at this point I'm just training myself to *only* look at the first error as all others are likely not too useful.

I attempted to minimize this as well:

```rust
mod foo {}

fn bar<T: Clone>() {}

fn main() {
    bar(foo::bar());
}
```

But this yielded a different error message:

```
foo.rs:6:9: 6:17 error: unresolved name `foo::bar` [E0425]
foo.rs:6     bar(foo::bar());
                 ^~~~~~~~
foo.rs:6:9: 6:17 help: run `rustc --explain E0425` to see a detailed explanation
foo.rs:6:5: 6:20 error: this function takes 0 parameters but 1 parameter was supplied [E0061]
foo.rs:6     bar(foo::bar());
             ^~~~~~~~~~~~~~~
foo.rs:6:5: 6:20 help: run `rustc --explain E0061` to see a detailed explanation
error: aborting due to previous error
```

Note that on stable this yields a message which is actionable and concise:

```
foo.rs:6:9: 6:17 error: unresolved name `foo::bar` [E0425]
foo.rs:6     bar(foo::bar());
                 ^~~~~~~~
foo.rs:6:9: 6:17 help: run `rustc --explain E0425` to see a detailed explanation
error: aborting due to previous error
```

### PR DESCRIPTION
**Pull request by nikomatsakis**
If the infcx has observed other errors, then suppress both default type
parameter fallback (which can be unreliable, as the full constraint set
is not available) and errors related to unresovled
variables (annoyingly, integer type variables cannot currently be
unified with error, so that has to be a separate mechanism). Also add a
flag to `infcx` to allow us to independently indicate when we have
observed an error and hence should trigger this suppression mode.

Fixes #31997 

cc @alexcrichton 
r? @arielb1

### CODE REVIEW

File: src/librustc/middle/infer/sub.rs [hunk 1]
```diff
@@ -86,6 +86,7 @@ impl<'a, 'tcx> TypeRelation<'a, 'tcx> for Sub<'a, 'tcx> {
             }
 
             (&ty::TyError, _) | (_, &ty::TyError) => {
+                infcx.set_tainted_by_errors();
```
Comment (arielb1) [inline src/librustc/middle/infer/sub.rs]: When should this be hit?

File: src/librustc_typeck/check/cast.rs [hunk 2]
```diff
@@ -121,8 +121,27 @@ impl<'tcx> CastCheck<'tcx> {
...
+        // inference variables floating around AND we've already
+        // reported some errors in this fn. It happens often that those
+        // inference variables are unresolved precisely *because* of
+        // the errors we've already reported. See #31997.
+        //
+        // Note: it's kind of annoying that we need this. Fallback is
+        // modified to push all unresolved inference variables to
+        // ty-err, but it's STILL possible to see fallback for
+        // integral/float variables, because those cannot be unified
+        // with ty-error.
```
Comment (arielb1) [inline src/librustc_typeck/check/cast.rs]: Casts *can* resolve types. I would rather change the `type_is_known_to_be_sized` path (both here and in the other place) to be less violent.

File: src/librustc_typeck/check/mod.rs [hunk 3]
```diff
@@ -1771,16 +1775,37 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
     fn default_type_parameters(&self) {
         use middle::ty::error::UnconstrainedNumeric::Neither;
         use middle::ty::error::UnconstrainedNumeric::{UnconstrainedInt, UnconstrainedFloat};
+
+        // Defaulting inference variables becomes very dubious if we have
+        // encountered type-checking errors. Therefore, if we think we saw
+        // some errors in this function, just resolve all uninstanted type
+        // varibles to TyError.
+        if self.infcx().is_tainted_by_errors() {
```
Comment (arielb1) [inline src/librustc_typeck/check/mod.rs]: If you are doing your best attempt to break out of inference, why not *just do it*?

**Comment by alexcrichton** [comment]
:mahjong:

File: src/librustc_typeck/check/mod.rs (hunk 3 above)
Comment (nikomatsakis) [inline src/librustc_typeck/check/mod.rs]: @arielb1 

> If you are doing your best attempt to break out of inference, why not just do it?

You mean why unify with error? The idea was to taint these variables in a way that would cause other errors to be suppressed if they should refer to them. Annoyingly, it didn't entirely work because of integral variables, so I still needed a few tests elsewhere.

**Comment by nikomatsakis** [comment]
@arielb1 

> Casts can resolve types.

Do you see this as a problem for this patch? Can you elaborate?

> I would rather change the type_is_known_to_be_sized path (both here and in the other place) to be less violent.

Hmm, ok. What would you like it to do? Just assume true?

> Why are integer variables a problem here (maybe we can change ty::cast to be more allowing?).

Because I can't unify them with ty-error.

File: src/librustc/middle/infer/sub.rs (hunk 1 above)
Comment (nikomatsakis) [inline src/librustc/middle/infer/sub.rs]: @arielb1 

> "causing damage"

Yes, we could remove it. I don't think it's needed -- rather, we should set the flag at the *source* of the errors, as I later did. (I could also assert when setting the flag that we are not in a snapshot, just to be safe.)

**Comment by nikomatsakis** [comment]
@arielb1 I'm not really sure where you are in your review here. Do you think I should change something? If so, what you would you prefer? (Or if you're just busy, that's fine too.)

**Comment by arielb1** [comment]
@nikomatsakis 

I would prefer to just treat `type_is_known_to_be_sized` as true if we are checking whether `_: Sized` and there are errors (for example, `() as *const _` should still be an error) and to have `ty::cast` treat integer/float variables as actual integer/floats.

> If you are doing your best attempt to break out of inference, why not *just do it*?

I was working on a patch that didn't do `select_all_obligations_or_error` but rather tried to report more specific errors if there were unresolved type variables. That's it, before I became somewhat busy.

Isn't cast checking the only thing downstream of default obligation? And I think we can solve it by being more careful with `type_is_known_to_be_sized`. And then we can figure out how much undefined-variable-error-reporting we want to do.

**Comment by arielb1** [comment]
I was also thinking about propagating `TyErr`, at least in method selection and for closure arguments to invalid methods.

**Comment by nikomatsakis** [comment]
@arielb1 so I removed that error suppression logic out of the casts. It didn't seem to cause any new spurious errors. I decided against modifying the logic for when a type is considered sized since it didn't seem necessary. I've also gotten make check passing and rebased. Take another look and tell me what you think. Given the changes to the errors (lots of duplicates removed) this seems like a positive step to me, and I *think* it no longer has the invasive quality you were concerned about.

**Comment by arielb1** [comment]
Does this fix `let x: *const u32 = 0 as _;`? If so, add an rpass test.

**Comment by arielb1** [comment]
Eh, it shouldn't. Maybe put that fix in a separate PR instead?

File: src/librustc_typeck/check/cast.rs [hunk 4]
```diff
@@ -111,17 +113,34 @@ enum CastError {
...
             expr_ty: expr_ty,
             cast_ty: cast_ty,
+            cast_span: cast_span,
             span: span,
+        };
+
+        // For better error messages, we try to check whether the
+        // target type is known to be sized now (we will also check
+        // later, once inference is more complete done).
+        if !fcx.type_is_known_to_be_sized(cast_ty, span) {
```
Comment (arielb1) [inline src/librustc_typeck/check/cast.rs]: What is *constructor* doing randomly emitting error messages?

BTW, why do we need the early error message? It causes compilation errors in some cases.

Comment (nikomatsakis) [inline src/librustc_typeck/check/cast.rs]: @arielb1 

> What is constructor doing randomly emitting error messages?

As you well know, a constructor is just another function... seems like as good a time as any. And the return type (in particular, the `Result` with `ErrorReported`) clearly indicates that an error is reported. 

My thinking was basically that instantiating a cast check does some checks and returns, potentially, further checks that may need to be done later. I'm happy to rename.

> BTW, why do we need the early error message? It causes compilation errors in some cases.

Yes, this doesn't seem optimal, I agree. I was just preserving the existing behavior -- but it seems like it could go wrong, if only in unusual situations like `x as _` or `x as Bar<_>`

I originally moved this check to be done at the end, but then you get derived errors later. For example:

    let x = foo as SomeTrait;

will give an error because the type of `x` is `SomeTrait`, which is not `Sized`. (Actually, it then later gives a error about "cast to unsized type".)

Probably the best thing would be to rewrite `type_is_known_to_be_sized` to return "yes, no, maybe" and only error out on *no*. (Or, for simplicity, just check specifically for casts to traits or slices, and leave the more general function for the end.)

**Comment by nikomatsakis** [comment]
@arielb1 pushed a new commit that tweaks the approach. Unfortunately, this doesn't seem to be quite enough to make that test work. I didn't dig into why, but you get a "type must be known" error.

**Comment by nikomatsakis** [comment]
oh, I see, because it calls `structurally_resolved_type`

**Comment by nikomatsakis** [comment]
OK, @arielb1, pushed a new version that fixes the case you mentioned.

**Comment by arielb1** [comment]
@bors retry

What the **** is going with our windows bots?

**Comment by nagisa** [comment]
Tagging this as relnotes because of https://github.com/rust-lang/rust/issues/33657
