### PR TITLE
Warn about unreachable code following an expression with an uninhabited type

### LINKED ISSUE #85071: Unused variable warning for used variable.
When trying to compile the following code I get an unused variable warning despite the variable is being used:

https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=66167b96f0e14d53616abbd0e6b3d12c

The current output is:
```
warning: unused variable: `typ`
  --> src/lib.rs:62:17
   |
62 |             let typ = T::infer_type(self);
   |                 ^^^ help: if this is intentional, prefix it with an underscore: `_typ`
   |
   = note: `#[warn(unused_variables)]` on by default
```

Ideally the output should not produce such a warning.

`cargo fix` produces the following output:

```
warning: failed to automatically apply fixes suggested by rustc to crate `rust_playground`

after fixes were automatically applied the compiler reported errors within these files:

  * src\lib.rs

This likely indicates a bug in either rustc or cargo itself,
and we would appreciate a bug report! You're likely to see
a number of compiler warnings after this message which cargo
attempted to fix but failed. If you could open an issue at
https://github.com/rust-lang/rust/issues
quoting the full output of this command we'd be very appreciative!
Note that you may be able to make some more progress in the near-term
fixing code with the `--broken-code` flag

The following errors were reported:
error[E0425]: cannot find value `typ` in this scope
  --> src\lib.rs:64:30
   |
64 |             info.typ.replace(typ);
   |                              ^^^ help: a local variable with a similar name exists: `_typ`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0425`.
Original diagnostics will follow.

warning: unused variable: `typ`
  --> src\lib.rs:62:17
   |
62 |             let typ = T::infer_type(self);
   |                 ^^^ help: if this is intentional, prefix it with an underscore: `_typ`
   |
   = note: `#[warn(unused_variables)]` on by default

warning: 1 warning emitted

warning: unused variable: `typ`
  --> src\lib.rs:62:17
   |
62 |             let typ = T::infer_type(self);
   |                 ^^^ help: if this is intentional, prefix it with an underscore: `_typ`
   |
   = note: `#[warn(unused_variables)]` on by default

warning: 1 warning emitted

    Finished dev [unoptimized + debuginfo] target(s) in 1.04s
```

### PR DESCRIPTION
**Pull request by FabianWolff**
This pull request fixes #85071. The issue is that liveness analysis currently is "smarter" than reachability analysis when it comes to detecting uninhabited types: Unreachable code is detected during type checking, where full type information is not yet available. Therefore, the check for type inhabitedness is quite crude:
https://github.com/rust-lang/rust/blob/fc81ad22c453776de16acf9938976930cf8c9401/compiler/rustc_typeck/src/check/expr.rs#L202-L205

i.e. it only checks for `!`, but not other, non-trivially uninhabited types, such as empty enums, structs containing an uninhabited type, etc. By contrast, liveness analysis, which runs after type checking, can benefit from the more sophisticated `tcx.is_ty_uninhabited_from()`:
https://github.com/rust-lang/rust/blob/fc81ad22c453776de16acf9938976930cf8c9401/compiler/rustc_passes/src/liveness.rs#L981
https://github.com/rust-lang/rust/blob/fc81ad22c453776de16acf9938976930cf8c9401/compiler/rustc_passes/src/liveness.rs#L996

This can lead to confusing warnings when a variable is reported as unused, but the use of the variable is not reported as unreachable. For instance:
```rust
enum Foo {}
fn f() -> Foo {todo!()}

fn main() {
    let x = f();
    let _ = x;
}
```
currently leads to
```
warning: unused variable: `x`
 --> t1.rs:5:9
  |
5 |     let x = f();
  |         ^ help: if this is intentional, prefix it with an underscore: `_x`
  |
  = note: `#[warn(unused_variables)]` on by default

warning: 1 warning emitted
```
which is confusing, because `x` _appears_ to be used in line 6. With my changes, I get:
```
warning: unreachable expression
 --> t1.rs:6:13
  |
5 |     let x = f();
  |             --- any code following this expression is unreachable
6 |     let _ = x;
  |             ^ unreachable expression
  |
  = note: `#[warn(unreachable_code)]` on by default
note: this expression has type `Foo`, which is uninhabited
 --> t1.rs:5:13
  |
5 |     let x = f();
  |             ^^^

warning: unused variable: `x`
 --> t1.rs:5:9
  |
5 |     let x = f();
  |         ^ help: if this is intentional, prefix it with an underscore: `_x`
  |
  = note: `#[warn(unused_variables)]` on by default

warning: 2 warnings emitted
```
My implementation is slightly inelegant because unreachable code warnings can now be issued in two different places (during type checking and during liveness analysis), but I think it is the solution with the least amount of unnecessary code duplication, given that the new warning integrates nicely with liveness analysis, where unreachable code is already implicitly detected for the purpose of finding unused variables.

### CODE REVIEW

File: compiler/rustc_passes/src/liveness.rs [hunk 1]
```diff
@@ -978,11 +978,26 @@ impl<'a, 'tcx> Liveness<'a, 'tcx> {
...
+                    } else if let LiveNodeKind::VarDefNode(succ_span, succ_id) = self.ir.lnks[succ]
+                    {
+                        self.warn_about_unreachable(
+                            expr.span,
+                            ty,
+                            succ_span,
+                            succ_id,
+                            "definition",
+                        );
+                    }
```
Comment (estebank) [inline compiler/rustc_passes/src/liveness.rs:1000]:
```suggestion
                    match self.ir.lnks[succ] {
                        LiveNodeKind::ExprNode(succ_span, succ_id) => {
                        self.warn_about_unreachable(
                            expr.span,
                            ty,
                            succ_span,
                            succ_id,
                            "expression",
                        );
                    }
                    LiveNodeKind::VarDefNode(succ_span, succ_id) => {
                        self.warn_about_unreachable(
                            expr.span,
                            ty,
                            succ_span,
                            succ_id,
                            "definition",
                        );
                    }
                    _ => {}
```

File: compiler/rustc_passes/src/liveness.rs [hunk 2]
```diff
@@ -993,11 +1008,26 @@ impl<'a, 'tcx> Liveness<'a, 'tcx> {
...
             hir::ExprKind::MethodCall(.., ref args, _) => {
                 let m = self.ir.tcx.parent_module(expr.hir_id).to_def_id();
-                let succ = if self.ir.tcx.is_ty_uninhabited_from(
-                    m,
-                    self.typeck_results.expr_ty(expr),
-                    self.param_env,
-                ) {
+                let ty = self.typeck_results.expr_ty(expr);
+                let succ = if self.ir.tcx.is_ty_uninhabited_from(m, ty, self.param_env) {
+                    if let LiveNodeKind::ExprNode(succ_span, succ_id) = self.ir.lnks[succ] {
```
Comment (estebank) [inline compiler/rustc_passes/src/liveness.rs:1013]: Same as above, and given this is the second time you're doing this, maybe adding a method to `LiveNodeKind` might be warranted?

File: compiler/rustc_passes/src/liveness.rs [hunk 3]
```diff
@@ -1274,6 +1304,47 @@ impl<'a, 'tcx> Liveness<'a, 'tcx> {
...
+        if !orig_ty.is_never() {
+            // Unreachable code warnings are already emitted during type checking.
+            // However, during type checking, full type information is being
+            // calculated but not yet available, so the check for diverging
+            // expressions due to uninhabited result types is pretty crude and
+            // only checks whether ty.is_never(). Here, we have full type
+            // information available and can issue warnings for less obviously
+            // uninhabited types (e.g. empty enums). The check above is used so
+            // that we do not emit the same warning twice if the uninhabited type
+            // is indeed `!`.
```
Comment (estebank) [inline compiler/rustc_passes/src/liveness.rs:1325]: Is there a reason _not_ to remove the current, existing, crude check in favor of this one?

**Review by estebank — APPROVED** [review]
I'm ok with the code changes, but left some questions.

File: compiler/rustc_passes/src/liveness.rs (hunk 3 above)
Comment (FabianWolff) [reply compiler/rustc_passes/src/liveness.rs:1325]: Yes, because type inference makes use of the crude divergence information available, e.g. here:
https://github.com/rust-lang/rust/blob/5dc8789e300930751a78996da0fa906be5a344a2/compiler/rustc_typeck/src/check/fn_ctxt/checks.rs#L654-L660
The crude check is here:
https://github.com/rust-lang/rust/blob/5dc8789e300930751a78996da0fa906be5a344a2/compiler/rustc_typeck/src/check/expr.rs#L202-L205
Unfortunately, we can't replace it with `tcx.is_ty_uninhabited_from()` because type information has not been committed to `tcx` yet at this point.

**Comment by FabianWolff** [comment]
Thanks for your review and suggestions! I have slightly refactored the code now to implement your suggestions.

**Comment by Dylan-DPC** [comment]
@estebank this seems ready for a final review

**Comment by rylev** [comment]
This change casued a very large regression in [instruction counts](https://perf.rust-lang.org/compare.html?start=de42550d0ac525f44ec79300a1cb349ade181c1a&end=5ca596f486707ac1362edad717ad0e9f5b71d0a3&stat=instructions:u). It seems to only be happening in one benchmark `webrender-wrench` and is consistently affecting the `extern_crate`, `incr_comp_intern_dep_graph_node`, and `metadata_decode_entry_extern_crate` queries in multiple test case variants of that benchmark. Given the nature of the change which only impacts liveness checking, I'm unsure why this might be the case. I was tempted to not report this, but given that the regressions are fairly large, I do think additional investigation is worth looking into.

As part of the performance triage process, I'm marking this as a performance regression. If you believe this performance regression to be justifiable or once you have an issue or PR that addresses this regression, please mark this PR with the label perf-regression-triaged.

@rustbot label +perf-regression

**Comment by Mark-Simulacrum** [comment]
This regression comes from a new unreachable expression warning specifically in webrender-wrench, which triggers the standard diagnostic infra. That infrastructure is pretty expensive, in this case loading up information from disk in order to trim paths being the most expensive bit.

As such, marking as triaged -- we expect performance to be worse when emitting extra diagnostics.

@rustbot label +perf-regression-triaged
