### PR TITLE
rustc: Fix `crate` lint for single-item paths 

### LINKED ISSUE #50660: 2018 compatibility lint isn't firing for all imports that need to be rewritten
This code:

```rust
#![feature(rust_2018_preview)]
#![warn(rust_2018_breakage)]

mod m {
    use foo;

    crate fn bar() {
        foo();
    }
}

fn foo() {}

fn main() {
    m::bar();
}
```

on nightly produces no warnings, but to compile in the 2018 edition the `use` statement needs to be rewritten to `crate::`.

### PR DESCRIPTION
**Pull request by alexcrichton**
This commit fixes recommending the `crate` prefix when migrating to 2018 for
paths that look like `use foo;` or `use {bar, baz}`

Closes #50660

### CODE REVIEW

**Comment by alexcrichton** [comment]
@bors: p=1

(affects upcoming edition preview)

File: src/librustc_resolve/lib.rs [hunk 1]
```diff
@@ -3334,13 +3335,22 @@ impl<'a> Resolver<'a> {
...
+                        second_binding = Some(binding);
+                    }
                     let def = binding.def();
                     let maybe_assoc = opt_ns != Some(MacroNS) && PathSource::Type.is_expected(def);
                     if let Some(next_module) = binding.module() {
                         module = Some(next_module);
                     } else if def == Def::Err {
                         return PathResult::NonModule(err_path_resolution());
                     } else if opt_ns.is_some() && (is_last || maybe_assoc) {
+                        self.lint_if_path_starts_with_module(
```
Comment (Manishearth) [inline src/librustc_resolve/lib.rs]: we should do this above as well, yes? After `resolve_ident_in_lexical_scope`? I'm not sure

**Review by Manishearth — APPROVED** [review]

**Comment by alexcrichton** [comment]
@bors: r-

I've found an issue with this that needs to be tweaked

**Comment by alexcrichton** [comment]
Ok the bug that I found was that the previous changes would lint for imports like `use libc;` and rewrite those to `use crate::libc;`. While that works in the 2015 edition it's not something we want to lint for. Once `extern crate libc;` is removed it breaks `use crate::libc;`. 

I've done what I hope is a thorough review of librustc_resolve for where 2015/2018 diverge and have added a lint to the appropriate locations (hopefully). Now `use libc;` is not linted for and will continue to work in both the 2015 and 2018 editions.

re-r? @Manishearth

File: src/librustc_resolve/resolve_imports.rs [hunk 2]
```diff
@@ -653,6 +654,9 @@ impl<'a, 'b:'a> ImportResolver<'a, 'b> {
                     return Some((directive.span,
                                  "cannot glob-import all possible crates".to_string()));
                 }
+                GlobImport { .. } if self.session.features_untracked().extern_absolute_paths => {
```
Comment (alexcrichton) [inline src/librustc_resolve/resolve_imports.rs]: This is something that was accidentally omitted from the lint entirely before, where `use *` is completely forbidden in 2018 and so this starts to lint about that in 2015.

Note that there's still a "bug" in the lint for "remove `extern crate`", I'll file a bug for that shortly

**Review by oli-obk — APPROVED** [review]
r=me with either action taken

**Comment by alexcrichton** [comment]
er,

@bors: r=oli-obk

**Comment by alexcrichton** [comment]
@bors: p=1

relevant for the edition preview, so prioritizing
