### PR TITLE
Suggest using `map_or` when `Option<&T>::unwrap_or where T: Deref` fails

### LINKED ISSUE #127545: Improve compile errors for type mismatch when encoutering `unwrap_or`
Given [this code](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=7aa9ddf279169346dc73a1a1f4a84d43):
```rust
use std::collections::HashMap;

pub fn get(index: &HashMap<usize, Vec<i32>>, id: usize) -> &[i32] {
    index.get(&id).unwrap_or(&[])
}
```

Current error, for the motivating use case above:

```console
error[E0308]: mismatched types
   --> src/lib.rs:5:30
    |
5   |     index.get(&id).unwrap_or(&[])
    |                    --------- ^^^ expected `&Vec<i32>`, found `&[_; 0]`
    |                    |
    |                    arguments to this method are incorrect
    |
    = note: expected reference `&Vec<i32>`
               found reference `&[_; 0]`
help: the return type of this call is `&[_; 0]` due to the type of the argument passed
   --> src/lib.rs:5:5
    |
5   |     index.get(&id).unwrap_or(&[])
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^---^
    |                              |
    |                              this argument influences the return type of `unwrap_or`
```

It should be possible for rustc to suggest replacing this specific instantiation of `unwrap_or` with `map_or(&[], Vec::as_slice)`. Maybe similarly for some other common cases: `map_or("", String::as_str)`.

_Originally posted by `@dtolnay` in https://github.com/rust-lang/libs-team/issues/407#issuecomment-2218677110_

@rustbot label -T-rustdoc T-compiler

### PR DESCRIPTION
**Pull request by tesuji**
Fix #127545

Split from https://github.com/rust-lang/rust/pull/127596#pullrequestreview-2171898588

### CODE REVIEW

File: compiler/rustc_hir_typeck/src/fn_ctxt/suggestions.rs [hunk 1]
```diff
@@ -1407,6 +1407,71 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
...
+        if !is_method {
+            return;
+        }
+        let Some(callee_ty) = callee_ty else {
+            return;
+        };
+        let ty::Adt(callee_adt, _) = callee_ty.peel_refs().kind() else {
+            return;
+        };
+        if !self.tcx.is_diagnostic_item(sym::Option, callee_adt.did()) {
```
Comment (tesuji) [inline compiler/rustc_hir_typeck/src/fn_ctxt/suggestions.rs:1432]: We could take Result also, I think.

Comment (estebank) [reply compiler/rustc_hir_typeck/src/fn_ctxt/suggestions.rs:1454]: Yes, we should support both.

File: compiler/rustc_hir_typeck/src/fn_ctxt/suggestions.rs [hunk 2]
```diff
@@ -1429,6 +1429,71 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
...
+            provided_ty
+        };
+
+        if !self.can_coerce(expected_ty, dummy_ty) {
+            return;
+        }
+        let (provided_snip, applicability) =
+            match self.tcx.sess.source_map().span_to_snippet(provided_expr.span) {
+                Ok(snip) => (snip, Applicability::MachineApplicable),
+                Err(_) => ("/* _ */".to_owned(), Applicability::MaybeIncorrect),
```
Comment (estebank) [inline compiler/rustc_hir_typeck/src/fn_ctxt/suggestions.rs:1485]:
```suggestion
                Err(_) => ("/* _ */".to_owned(), Applicability::HasPlaceholders),
```

File: compiler/rustc_hir_typeck/src/fn_ctxt/suggestions.rs [hunk 3]
```diff
@@ -1429,6 +1429,71 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
...
+            };
+        let sugg = &format!("map_or({provided_snip}, |v| v)");
+        err.span_suggestion_verbose(
+            error_span,
+            "use `Option::map_or` to deref inner value of `Option`",
+            sugg,
+            applicability,
+        );
```
Comment (estebank) [inline compiler/rustc_hir_typeck/src/fn_ctxt/suggestions.rs:1493]: Instead of `span_suggestion_verbose` we can use `multipart_suggestion_verbose` for this, as there are effectively multiple things to change. You can take the `call_ident.span` to replace it with `map_or` and then `provided_expr.span.shrink_to_hi()`:

```suggestion
        err.multipart_suggestion_verbose(
            "use `Option::map_or` to deref the inner value of the `Option`",
            vec![
                (call_ident.span, "map_or".to_string()),
                (provided_expr.span.shrink_to_hi(), "|v| v".to_string()),
            ],
            applicability,
        );
```

File: compiler/rustc_hir_typeck/src/fn_ctxt/suggestions.rs [hunk 4]
```diff
@@ -1429,6 +1429,71 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
...
+        return;
```
Comment (estebank) [inline compiler/rustc_hir_typeck/src/fn_ctxt/suggestions.rs:1494]: Remove this left over `return`
```suggestion
```

File: compiler/rustc_hir_typeck/src/fn_ctxt/suggestions.rs [hunk 5]
```diff
@@ -1429,6 +1429,71 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
...
+
+        if !self.can_coerce(expected_ty, dummy_ty) {
+            return;
+        }
+        let (provided_snip, applicability) =
+            match self.tcx.sess.source_map().span_to_snippet(provided_expr.span) {
+                Ok(snip) => (snip, Applicability::MachineApplicable),
+                Err(_) => ("/* _ */".to_owned(), Applicability::MaybeIncorrect),
+            };
+        let sugg = &format!("map_or({provided_snip}, |v| v)");
```
Comment (estebank) [inline compiler/rustc_hir_typeck/src/fn_ctxt/suggestions.rs:1487]: If you make it a multipart suggestion, then all of this is no longer necessary.
