### PR TITLE
Suggest correct cast for struct fields with shorthand syntax

### LINKED ISSUE #52497: Misleading error message: Type mismatch when initializing struct fields with shorthand
The following code has a misleading proposed fix:

```rust
struct RGB { r: f64, g: f64, b: f64 }
fn main() {
  let (r, g, b): (f32, f32, f32) = (0., 0., 0.);
  let _ = RGB { r, g, b };
}
```

The reported error message is:

```rust
error[E0308]: mismatched types
 --> src/main.rs:4:17
  |
4 |   let _ = RGB { r, g, b };
  |                 ^ expected f64, found f32
help: you can cast an `f32` to `f64` in a lossless way
  |
4 |   let _ = RGB { r.into(), g, b };
  |                 ^^^^^^^^
```

Trying to apply the suggestion fails and causes a syntax error, the correct fix would be `r: r.into()`.

### PR DESCRIPTION
**Pull request by estebank**
```
error[E0308]: mismatched types
  --> $DIR/type-mismatch-struct-field-shorthand.rs:8:19
   |
LL |     let _ = RGB { r, g, b };
   |                   ^ expected f64, found f32
help: you can cast an `f32` to `f64` in a lossless way
   |
LL |     let _ = RGB { r: r.into(), g, b };
   |                   ^^^^^^^^^^^
```

Fix #52497.

### CODE REVIEW

File: src/librustc_typeck/check/demand.rs [hunk 1]
```diff
@@ -487,17 +488,40 @@ impl<'a, 'gcx, 'tcx> FnCtxt<'a, 'gcx, 'tcx> {
         // For now, don't suggest casting with `as`.
         let can_cast = false;
 
+        let mut prefix = String::new();
+        if let Some(hir::Node::Expr(hir::Expr {
+            node: hir::ExprKind::Struct(_, fields, _),
+            ..
+        })) = self.tcx.hir().find(self.tcx.hir().get_parent_node(expr.id)) {
+            // `expr` is a literal field for a struct, only suggest if appropriate
+            for field in fields {
```
Comment (matthewjasper) [inline src/librustc_typeck/check/demand.rs]: Should this also check `field.is_shorthand`?

Comment (estebank) [reply src/librustc_typeck/check/demand.rs]: @matthewjasper good idea.
