### PR TITLE
Be more precise when suggesting removal of parens on unit ctor

### LINKED ISSUE #99240: Diagnostic misclassifies a complex expression as a unit enum variant when flagging an attempt to call a non-function
Given the following code:

```rust
fn fmt(it: &(std::cell::Cell<Option<impl FnOnce()>>,)) {
    (it.0.take())()
}
```

The current output is:

```
error[E0618]: expected function, found enum variant `(it.0.take())`
  --> src/lib.rs:22:5
   |
22 |     (it.0.take())()
   |     ^^^^^^^^^^^^^--
   |     |
   |     call expression requires function
   |
help: `(it.0.take())` is a unit variant, you need to write it without the parentheses
   |
22 -     (it.0.take())()
22 +     (it.0.take())
   |

```

* It classifies the complex expression `(it.0.take())` as a (unit) enum variant in both the message and the note which is obviously incorrect.
* It does not mention anywhere that the expression is of type `Option<_>` which would've been really helpful. Looking at the current output, it's really hard to see why the expression is not callable.

( As an aside, one actual fix for the given code is the following: `it.0.take().unwrap()()` )

[Link to the playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=ae41c503a92de9d8008ce3281e3fdfbf) containing the reproducer, an even smaller reproducer and the original code for context.
I decided to select the slightly larger reproducer (containing the 1-tuple) for this issue instead of the smaller one from the playground (which can probably still be shrunk further) to really highlight the complex expression: `(it.0.take())` over just `it.take()`.

Reproduces on stable and on nightly.

@rustbot label C-bug D-incorrect D-confusing

### PR DESCRIPTION
**Pull request by compiler-errors**
* Fixes #99240 by only suggesting to remove parens on path exprs, not arbitrary expressions with enum type
* Generalizes by suggesting removal of parens on unit struct, too, because why not?

### CODE REVIEW

File: compiler/rustc_typeck/src/check/callee.rs [hunk 1]
```diff
@@ -390,17 +390,23 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
...
-                let mut removal_span = call_expr.span;
-                if let ty::Adt(adt_def, ..) = t
-                    && adt_def.is_enum()
-                    && let hir::ExprKind::Call(expr, _) = call_expr.kind
+                if let hir::ExprKind::Path(qpath) = &callee_expr.kind
+                    && let Res::Def(def::DefKind::Ctor(kind, def::CtorKind::Const), _)
+                        = self.typeck_results.borrow().qpath_res(qpath, callee_expr.hir_id)
+                    // Only suggest removing parens if there are no arguments
+                    && arg_exprs.is_empty()
+                    && let Ok(path) = self.tcx.sess.source_map().span_to_snippet(callee_expr.span)
```
Comment (compiler-errors) [inline compiler/rustc_typeck/src/check/callee.rs:400]: I would like to use `tcx.def_path_str` instead of `span_to_snippet`, but that does not preserve aliases, and causes regressions in `src/test/ui/type-alias-enum-variants/incorrect-variant-form-through-alias-caught.rs` by changing `Alias::Unit` to `Enum::Unit` :cry:

Comment (compiler-errors) [reply compiler/rustc_typeck/src/check/callee.rs:400]: I could possibly find a way to format `qpath` into a string by joining all of its segments, but that's a bit overkill and this PR does not represent a regression in the status quo.

Comment (fee1-dead) [reply compiler/rustc_typeck/src/check/callee.rs:400]: It wouldn't work well with improperly formatted code, right? If the path is a macro expansion what would happen..? To me I don't think they should preserve the alias path.

Comment (compiler-errors) [reply compiler/rustc_typeck/src/check/callee.rs:400]: Hm, you're right. If we had like

```
path::
split::
up::
over_many_lines
```

then we shouldn't use that in diagnostics.

Comment (compiler-errors) [reply compiler/rustc_typeck/src/check/callee.rs]: I just used `rustc_hir_pretty` which does that for us. Avoids weirdness like:

```rust
enum Enum { Braced {} }
type Alias = Enum;

fn main() {
    Alias::
    Braced;
}
```

```
error[[E0533]](https://doc.rust-lang.org/stable/error-index.html#E0533): expected unit struct, unit variant or constant, found struct variant `Alias::
                  Braced`
 --> src/main.rs:5:5
  |
5 | /     Alias::
6 | |     Braced;
  | |__________^
```

Comment (fee1-dead) [reply compiler/rustc_typeck/src/check/callee.rs]: Nice, please add that as a test.

Comment (compiler-errors) [reply compiler/rustc_typeck/src/check/callee.rs]: Done

**Review by fee1-dead — APPROVED** [review]
