### PR TITLE
Make `std::os::darwin` public

### LINKED ISSUE #121640: Failed to build aarch64-apple-tvos target
I tried to build `aarch64-apple-tvos`, `x86_64-apple-tvos`, `aarch64-apple-tvos-sim` targets.
Unfortunately, I got

<details><summary>the following errors:</summary>
<p>

```
  error: methods `as_raw_stat`, `st_birthtime`, `st_birthtime_nsec`, `st_flags`, `st_gen`, and `st_lspare` are never used
    --> library/std/src/os/ios/fs.rs:29:8
     |
  15 | pub trait MetadataExt {
     |           ----------- methods in this trait
  ...
  29 |     fn as_raw_stat(&self) -> &raw::stat;
     |        ^^^^^^^^^^^
  ...
  60 |     fn st_birthtime(&self) -> i64;
     |        ^^^^^^^^^^^^
  61 |     #[stable(feature = "metadata_ext2", since = "1.8.0")]
  62 |     fn st_birthtime_nsec(&self) -> i64;
     |        ^^^^^^^^^^^^^^^^^
  ...
  68 |     fn st_flags(&self) -> u32;
     |        ^^^^^^^^
  69 |     #[stable(feature = "metadata_ext2", since = "1.8.0")]
  70 |     fn st_gen(&self) -> u32;
     |        ^^^^^^
  71 |     #[stable(feature = "metadata_ext2", since = "1.8.0")]
  72 |     fn st_lspare(&self) -> u32;
     |        ^^^^^^^^^
     |
     = note: `-D dead-code` implied by `-D warnings`
     = help: to override `-D warnings` add `#[allow(dead_code)]`
  
  error: method `set_created` is never used
     --> library/std/src/os/ios/fs.rs:151:8
      |
  148 | pub trait FileTimesExt: Sealed {
      |           ------------ method in this trait
  ...
  151 |     fn set_created(self, t: SystemTime) -> Self;
      |        ^^^^^^^^^^^
  
  
  Did not run successfully: exit status: 1
```

</p>
</details>

### How to reproduce

```
./configure \
		--enable-option-checking \
		--tools=cargo,clippy,rustdoc,rustfmt,rust-analyzer,analysis,src \
		--target=aarch64-apple-tvos,x86_64-apple-tvos,aarch64-apple-tvos-sim \
		--set llvm.download-ci-llvm=true \
		--set build.verbose=1 \
		--set rust.channel=dev \
		--dist-compression-formats=xz \
		--prefix=install
```

According to the [docs](https://doc.rust-lang.org/rustc/platform-support/apple-tvos.html), the target maintainer is [@thomcc](https://github.com/thomcc)

### PR DESCRIPTION
**Pull request by madsmtm**
I'm not sure of the reasoning behind them not being public before, but I think they should be, just like `std::os::ios` and `std::os::macos` are public.

Additionally, I've merged their source code, as it was otherwise just a bunch of unnecessary duplication.

Ultimately, I've done this PR to fix `./x build library --target=aarch64-apple-tvos,aarch64-apple-watchos,aarch64-apple-visionos`, as that currently fails because of dead code warnings.

Since you reviewed https://github.com/rust-lang/rust/pull/121419
r? davidtwco

Fixes https://github.com/rust-lang/rust/issues/121640.

@rustbot label O-tvos O-watchos O-visionos

EDIT: Link to FCP summary: https://github.com/rust-lang/rust/pull/123723#issuecomment-2287276599

### CODE REVIEW

**Comment by davidtwco** [comment]
r? libs

File: library/std/src/os/mod.rs
Comment (simlay) [inline library/std/src/os/mod.rs:1]: I think all these `#[cfg(target_os = "ios/watchos/etc")]` could be one `#[cfg(target_vendor = "apple")]` and it would be a lot more readable.

Comment (madsmtm) [reply library/std/src/os/mod.rs:1]: Hmm, but we still want to export them as separate modules `std::os::tvos` vs. `std::os::macos`?

Comment (simlay) [reply library/std/src/os/mod.rs:1]: Ah yes, you're right I missed that.

**Comment by madsmtm** [comment]
r? libs-api

**Review by dtolnay — CHANGES_REQUESTED** [review]
Thanks for the PR!

I am open to adding these modules, but not the deprecated contents being exposed by this PR. `std::os::macos::raw` has been deprecated since more than 8 years ago and I don't think we should be adding more of that API for new targets.

File: triagebot.toml [hunk 1]
```diff
@@ -227,7 +222,7 @@ trigger_files = [
 
 [autolabel."O-macos"]
 trigger_files = [
-    "library/std/src/os/macos"
+    "library/std/src/os/apple"
 ]
```
Comment (madsmtm) [inline triagebot.toml:226]: Creating a more appropriate label for Apple-specific stuff is tracked in https://github.com/rust-lang/rust/pull/124146.

**Review by madsmtm — COMMENTED** [review]
Hmm, the issue is that most of the `std::os::[os]::raw` definitions are re-exported in `std::os::unix::raw`, I think it's only the `stat` struct that isn't.

I've cfg-guarded that in the last commit, though I disagree that it's a good idea; the reason we'd remove it is to simplify `std` maintenance, but this actually only complicates it ;)

@rustbot ready

**Comment by dtolnay** [comment]
@rust-lang/libs-api:

The `std::os::macos` module, which is available only on `cfg(target_os = "macos")`, contains:

<p align="center"><br><br><br><br></p>

This PR proposed exposing the same contents also under `std::os::tvos` for target_os="tvos", `std::os::visionos` for target_os="visionos", and `std::os::watchos` for target_os="watchos".

I propose that we accept instantly stabilizing these additions, with the following modifications:

- Do not expose `std::os::{tvos, visionos, watchos}::raw` &mdash; those modules will be changed to `pub(crate)`. For `macos`, `raw` has been deprecated since more than 8 years ago and I think it's worth avoiding adding that deprecated API in yet another place. Note that the 9 type aliases will continue to be accessible as re-exports in [`std::os::unix::raw`](https://doc.rust-lang.org/std/os/unix/raw/index.html), where they have been stably accessible on tvos, visionos, and watchos since the original introduction of these targets. For future unix targets, we may wish to avoid re-exporting raw deprecated types for them in `std::os::unix::raw` in the first place.

- Do not include `as_raw_stat` in the `MetadataExt` trait of the new targets.

- Seal the `MetadataExt` trait of the new targets.

Please register a concern if you would prefer that any of these modifications not be applied.

@rfcbot fcp merge

**Comment by BurntSushi** [comment]
Is it possible to get a review/recommendation from the @rust-lang/apple team? I see that there are some folks [from that team](https://github.com/BurntSushi/team.git/blob/e1d15f97432ea3191ff114608260a06e44a17854/teams/apple.toml#L8-L13) involved here, but I don't see any sort of official consensus from that team. Basically, I don't have a ton of insight on whether this is the "right" organization for the Apple ecosystem (although I have no specific alternative suggestion), and I'd like to hear from _domain experts_ on this.

**Comment by BurntSushi** [comment]
I think the were recently renamed to `apple`? I assumed `@rust-lang/apple` would work, but I guess not.

@rustbot ping apple

**Comment by BurntSushi** [comment]
OK, when in doubt, use brute force:

cc @hkratz @inflation @shepmaster @thomcc @nvzqz @madsmtm

libs-api is seeking you're opinion about stabilizing Apple specific APIs.

**Comment by dtolnay** [comment]
Looks like "rustbot ping apple" is broken until https://github.com/rust-lang/rust/pull/124146 gets merged.

**Comment by madsmtm** [comment]
I'm fine with implementing the proposed changes if that's what the decision ends up being, though I still disagree that it's a good idea - reiterating, the reason we'd remove it is to simplify `std` maintenance, but this only complicates it (as we have to keep the support for macOS/iOS anyhow).

Concrete example of an issue is that `MetadataExt::st_qspare` was added back in the day only on macOS, even though it is also available on the other platforms. Merging the files allowed us to see this, splitting them up or adding more `cfg`s will just lead to similar inconsistencies in the future.

**Comment by inflation** [comment]
There could be an umbrella namespace for these common stuffs, e.g. `apple` like `cfg(target_vendor="apple")`.

**Comment by joshtriplett** [comment]
That'd be my preference as well, here. If we have tvOS-specific APIs, by all means let's put them in `std::os::tvos`, but to the extent they're *identical* to macOS APIs, could we put them in the same place?

**Comment by Amanieu** [comment]
`std::os::apple` would make sense since it is a `target_family` in the same way that `std::os::unix` is.

**Comment by madsmtm** [comment]
> There could be an umbrella namespace for these common stuffs, e.g. `apple` like `cfg(target_vendor="apple")`.

I think `std::os::apple` is a good idea, but I think it's somewhat separate from this proposal; even if we have `std::os::apple`, I think I'd still want `std::os::tvos`/`std::os::watchos`/`std::os::visionos` for consistency with `std::os::macos`/`std::os::ios` (unless we fully deprecate the latter).

Implementation-wise, it could just be `pub use apple as ios;`.

**Comment by Amanieu** [comment]
I would rather avoid having to include a new submodule every time apple designs a new device and instead centralize everything under a single submodule. For backwards-compatibility, `std::os::macos` can be a re-export of `std::os::apple`, but I don't think we should add more.

**Comment by workingjubilee** [comment]
Hello,

I was there for some of the discussion of this nature because I reviewed the tvos PR and a few others. It basically went exactly like this discussion. There is no point in having all these different APIs exposed when they introduce a somewhat-pointless risk for additional variance.

It may be prudent to use the kernel name... i.e. `mod darwin`... that AIUI they all share, because there is The Other MacOS from long ago. Apple is clearly willing to have epochal breaking changes that risk redefining what `mod apple` would mean. Rosetta 2 implies its own sequel, a Rosetta III: Translator's Revenge.

**Comment by madsmtm** [comment]
I opened https://github.com/rust-lang/rust/pull/125935 to do the refactor and fixing the compilation errors separately, so that this PR can be focused on the public API. Will rebase once that lands.

> It may be prudent to use the kernel name... i.e. `mod darwin`

Well, the kernel name is technically XNU, it's the broader core OS that's named Darwin, but your point still stands. I think it could be a pretty good name to use, were it not for the fact that the macOS targets use it in their names as well (e.g. `aarch64-apple-darwin`), which might be confusing?

A bit of prior art:
- Swift has `import Darwin` for Apple-specific stuff, and `#if os(Darwin) ... #endif` for Apple-specific configs.
- C/Objective-C has `TargetConditionals.h` which defines `TARGET_OS_MAC` for this purpose (`TARGET_OS_OSX` is the one for macOS-specific code).
- Python's `platform.system()` returns `Darwin` on macOS and `iOS` on iOS, while `os.uname()` returns `Darwin` on both.

---

In an ideal world, I think I'd want:
1. `cfg(target_family = "darwin")` (or just `cfg(darwin)`).
2. The macOS targets to be named `*-apple-macos`.
3. `std::os::darwin`.

So if we can agree that plan is to move in this direction (i.e. at _some_ point slowly rename the targets, and at _some_ point add `target_family = "darwin"`), then I think `std::os::darwin` makes sense; if not, then we should probably go with `std::os::apple`.

**Comment by workingjubilee** [comment]
> In an ideal world, I think I'd want:
> 1. `cfg(target_family = "darwin")` (or just `cfg(darwin)`).
> 2. The macOS targets to be named `*-apple-macos`.
> 3. `std::os::darwin`.
>
> So if we can agree that plan is to move in this direction (i.e. at _some_ point slowly rename the targets, and at _some_ point add `target_family = "darwin"`), then I think `std::os::darwin` makes sense; if not, then we should probably go with `std::os::apple`.

Yes, I was in particular thinking that [the `target_family` cfg proposed for the phase out of `target_vendor`](https://github.com/rust-lang/rust/issues/100343) should be named thus in accord with this, and that ideally we would get `aarch64-apple-macos` as a target tuple (since the `target_os` is `"macos"` anyways).

**Comment by joshtriplett** [comment]
We discussed this in today's @rust-lang/libs-api meeting. Our consensus was that we don't want to provide a different module for every Apple OS, and that we should only provide distinct modules if they have distinct functions that don't exist on the other OSes. Please *just* provide the `std::os::apple` module with the common functionality across all Apple OSes.

`macos` should re-export `apple` and also provide the deprecated items; `apple` shouldn't have the deprecated items.

**Comment by joshtriplett** [comment]
It looks like https://github.com/rust-lang/rust/pull/125935 performed the merge we asked for; thank you!

Is there anything else that needs to happen here?

**Comment by madsmtm** [comment]
I have updated this PR to instead make `std::os::darwin::fs` public. Since the exposed API surface here isn't really new, I propose to just make this insta-stable [^1].

[^1]: I considered going through the normal feature gate lifecycle, and making a tracking issue and whatnot, but from what I read in [here](https://rustc-dev-guide.rust-lang.org/stability.html#unstable), it seems like re-exporting `std::os::darwin::fs::*` under `std::os::macos::fs::*` with the old stability attributes might still end up making it stably accessible anyhow.

## Summary

`std::os::darwin` is available on `cfg(target_vendor = "apple")` (macOS, iOS, tvOS, visionOS and watchOS), and contains functionality specific to those operating systems. It is named "Darwin" because that's the name of the underlying operating system that all of these are built upon. This follows the naming convention in Swift (`import Darwin`), so while it's a little bit unknown, it should be fairly familiar to developers for Apple platforms.

The API for `std::os::darwin` is:

<p align="center">
darwin
darwin_fs
darwin_fs_MetadataExt
darwin_fs_FileTimesExt
</p>

The API for `std::os::macos` and `std::os::ios` is now:

<p align="center">
macos_raw
macos_fs
</p>

Note: The images here doesn't show it, but `MetadataExt::as_raw_stat` is only available on macOS and iOS.

In the future, we can consider deprecating `std::os::macos` and `std::os::ios`, but this PR does not propose that.

@rustbot ready

**Comment by madsmtm** [comment]
Responding to https://github.com/rust-lang/rust/pull/123723#issuecomment-2094885394:

> * Do not expose `std::os::{tvos, visionos, watchos}::raw` — those modules will be changed to `pub(crate)`. For `macos`, `raw` has been deprecated since more than 8 years ago and I think it's worth avoiding adding that deprecated API in yet another place. Note that the 9 type aliases will continue to be accessible as re-exports in [`std::os::unix::raw`](https://doc.rust-lang.org/std/os/unix/raw/index.html), where they have been stably accessible on tvos, visionos, and watchos since the original introduction of these targets. For future unix targets, we may wish to avoid re-exporting raw deprecated types for them in `std::os::unix::raw` in the first place.

Only `std::os::darwin::fs` is exposed, `std::os::darwin::raw` is `pub(crate)` and instead exposed publicly in `std::os::unix::raw`, `std::os::macos::raw` and `std::os::ios::raw`.

> * Do not include `as_raw_stat` in the `MetadataExt` trait of the new targets. On macos this trait method has been deprecated since Rust 1.8.

This is cfg-gated to only be available on macOS and iOS.

> * Seal the `MetadataExt` trait of the new targets.

I'm not entirely sure of a good way to do this without macros? `trait MetadataExt: #[cfg(...)] Sealed` doesn't work.

**Comment by madsmtm** [comment]
r? libs-api

**Comment by workingjubilee** [comment]
FCP checkboxes are back in this now-hidden comment, in case you're wondering why you can't find them: https://github.com/rust-lang/rust/pull/123723#issuecomment-2094885414

**Comment by Dylan-DPC** [comment]
@joshtriplett @m-ou-se @BurntSushi this is waiting on you to vote/raise concerns on the [fcp](https://github.com/rust-lang/rust/pull/123723#issuecomment-2094885414). Thanks

**Review by dtolnay — APPROVED** [review]
Thank you!
