### PR TITLE
Use RelocModel::Pic for UEFI targets

### LINKED ISSUE #101377: [Regression] GlobalValue with DLLImport Storage is dso_local!
Hello,

I was trying to compile the [uefi crate](https://github.com/rust-osdev/uefi-rs), but I can't compile it with nightly-2022-09-02. The previous nightly works fine.

I get: 
GlobalValue with DLLImport Storage is dso_local!
ptr @_ZN4core7unicode12unicode_data11white_space14WHITESPACE_MAP17h76c794c1a16111d0E
LLVM ERROR: Broken module found, compilation aborted!

Maybe, the pr that broke it is #100537.

### PR DESCRIPTION
**Pull request by nicholasbishop**
In https://github.com/rust-lang/rust/pull/100537, the relocation model for UEFI targets was changed from PIC (the default value) to
static. There was some dicussion of this change here: https://github.com/rust-lang/rust/pull/100537#discussion_r952363012

It turns out that this can cause compilation to fail as described in https://github.com/rust-lang/rust/issues/101377, so switch back to PIC.

Fixes https://github.com/rust-lang/rust/issues/101377

### CODE REVIEW

**Comment by nicholasbishop** [comment]
CCing some folks from #100537: @petrochenkov @dvdhrm @oli-obk

**Comment by petrochenkov** [comment]
>GlobalValue with DLLImport Storage is dso_local!

I wonder why is there a DLLImport if dynamic linking is not supported on this target.
(I'm ok with partially reverting https://github.com/rust-lang/rust/pull/100537 if this needs to be fixed fast.)

File: compiler/rustc_target/src/spec/uefi_msvc_base.rs [hunk 1]
```diff
@@ -47,7 +47,7 @@ pub fn opts() -> TargetOptions {
         stack_probes: StackProbeType::Call,
         singlethread: true,
         linker: Some("rust-lld".into()),
-        relocation_model: RelocModel::Static,
+        relocation_model: RelocModel::Pic,
```
Comment (petrochenkov) [inline compiler/rustc_target/src/spec/uefi_msvc_base.rs:50]: `Pic` is the default mode so this line can be just removed.

Comment (nicholasbishop) [reply compiler/rustc_target/src/spec/uefi_msvc_base.rs]: done

File: compiler/rustc_target/src/spec/tests/tests_impl.rs [hunk 2]
```diff
@@ -146,9 +146,6 @@ impl Target {
         if self.position_independent_executables && !triple.ends_with("-linuxkernel") {
             assert_eq!(self.relocation_model, RelocModel::Pic);
         }
-        if self.relocation_model == RelocModel::Pic {
-            assert!(self.dynamic_linking || self.position_independent_executables);
-        }
```
Comment (petrochenkov) [inline compiler/rustc_target/src/spec/tests/tests_impl.rs:151]: This assert should not be removed in general, you can add an exception for UEFI with an explanation instead.

Comment (nicholasbishop) [reply compiler/rustc_target/src/spec/tests/tests_impl.rs:151]: done

Comment (bjorn3) [reply compiler/rustc_target/src/spec/tests/tests_impl.rs:151]: Should uefi set position_independent_executables and static_position_independent_executables?

**Comment by dvdhrm** [comment]
Looks good to me! As mentioned on the linked bug-report, I think we need to investigate why we end up with `DLLImport`, though. This should not happen as EFI loaders will ignore `.idata` sections.

File: compiler/rustc_target/src/spec/tests/tests_impl.rs (hunk 2 above)
Comment (dvdhrm) [reply compiler/rustc_target/src/spec/tests/tests_impl.rs:151]: > Should uefi set position_independent_executables and static_position_independent_executables?

Hard to tell by reading the in-code docs what these exactly control. But I think codegen_ssa is the only user and it simply causes PIC output requests to be silently converted to NoPIC output requests. In that case, I think UEFI should set both since PIC is technically supported, though not required nor used by anyone I know.

Comment (dvdhrm) [reply compiler/rustc_target/src/spec/tests/tests_impl.rs:151]: I think this assertion is misleading. UEFI does not support dynamic linking, nor are PIC-executables really necessary. However, it still *requires* a PIC'ish-reloc-model to allow the custom UEFI loaders to relocate the images during load.

I already mentioned this in https://github.com/rust-lang/rust/pull/100537, it is not clear to me what effect `RelocModel::Static` has. The LLVM docs are basically non-existant. If it causes `.reloc` to be stripped from PE32 binaries, then it is not applicable to UEFI.

Comment (bjorn3) [reply compiler/rustc_target/src/spec/tests/tests_impl.rs:151]: static_position_independent_executables is for when there is no dynamic linker.

> it is not clear to me what effect RelocModel::Static has.

AFAIK it fixes a specific load location at link time (eg 0x10000, depends on the linker) as opposed to allowing it to be loaded anywhere at runtime as with RelocModel::Pic.

Comment (dvdhrm) [reply compiler/rustc_target/src/spec/tests/tests_impl.rs:151]: > static_position_independent_executables is for when there is no dynamic linker.

Well, yeah, sure, but my question was rather what exactly it controls? Does it make rustc refuse compilation of non-pic? does it enforce static-pic regardless of what the caller chose? Does it mean pic is mandatory, or just supported?

Maybe there is no clear definition like this, and it just controls the one knob we currently have in codegen_ssa. That would be fine with me. In that case, UEFI should probably set this to `true`.

> > it is not clear to me what effect RelocModel::Static has.
> 
> AFAIK it fixes a specific load location at link time (eg 0x10000, depends on the linker) as opposed to allowing it to be loaded anywhere at runtime as with RelocModel::Pic.

I see. This likely means on PE32 `.reloc` is stripped and relocation is not supported? In that case, I think the assertion is wrong and needs to go. A relocatable binary should not imply dynamic-linking or position-independen-code. Since reloc and PIC are different things on UEFI (and also on Windows).

Comment (bjorn3) [reply compiler/rustc_target/src/spec/tests/tests_impl.rs:151]: > Well, yeah, sure, but my question was rather what exactly it controls? Does it make rustc refuse compilation of non-pic? does it enforce static-pic regardless of what the caller chose? Does it mean pic is mandatory, or just supported?

It controls if pic compilation is supported or not. It doesn't make it mandatory. In the linker code for the msvc linker it doesn't distinguish between pic and non-pic executables.

Comment (nicholasbishop) [reply compiler/rustc_target/src/spec/tests/tests_impl.rs:151]: I tested adding this into `uefi_msvc_base`:
```
position_independent_executables: true,
static_position_independent_executables: true,
```
and it doesn't seem to cause any problem, at least in the simple test I did. Do you want me to add that to this PR?

Comment (nicholasbishop) [reply compiler/rustc_target/src/spec/tests/tests_impl.rs:151]: Friendly ping -- should I add the above lines to this PR? Or should we stick to the existing changes?

Comment (bjorn3) [reply compiler/rustc_target/src/spec/tests/tests_impl.rs:151]: Not sure.

File: compiler/rustc_target/src/spec/tests/tests_impl.rs [hunk 3]
```diff
@@ -146,7 +146,8 @@ impl Target {
         if self.position_independent_executables && !triple.ends_with("-linuxkernel") {
             assert_eq!(self.relocation_model, RelocModel::Pic);
         }
-        if self.relocation_model == RelocModel::Pic {
+        // The UEFI targets do not support dynamic linking but still require PIC (#101377).
+        if self.relocation_model == RelocModel::Pic && !triple.ends_with("-uefi") {
```
Comment (petrochenkov) [inline compiler/rustc_target/src/spec/tests/tests_impl.rs:150]:
```suggestion
        if self.relocation_model == RelocModel::Pic && self.os != "uefi" {
```

**Comment by petrochenkov** [comment]
r? @petrochenkov 
r=me after small cleanup (https://github.com/rust-lang/rust/pull/101413#discussion_r967368511).
@rustbot author

File: compiler/rustc_target/src/spec/tests/tests_impl.rs (hunk 3 above)
Comment (nicholasbishop) [reply compiler/rustc_target/src/spec/tests/tests_impl.rs]: done

**Comment by nicholasbishop** [comment]
FYI I've filed a followup ticket here: https://github.com/rust-lang/rust/issues/101656
