### PR TITLE
Say "this enum variant takes"/"this struct takes" instead of "this function takes"

### LINKED ISSUE #86481: Missing parenthesis for tuple in enum variant
Given the following code: 

```rust
fn main() {
    let s = Some("hello", "world");
}
```

The current output is:

```
   Compiling playground v0.0.1 (/playground)
error[E0061]: this function takes 1 argument but 2 arguments were supplied
 --> src/main.rs:2:13
  |
2 |     let s = Some("hello", "world");
  |             ^^^^ -------  ------- supplied 2 arguments
  |             |
  |             expected 1 argument

error: aborting due to previous error

For more information about this error, try `rustc --explain E0061`.
error: could not compile `playground`
```

Ideally the output should should say "struct" rather than function or better, suggest adding the missing `(` instead since it is a tuple.

https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=418656a98e80500393928f9833e15d3d

### PR DESCRIPTION
**Pull request by syvb**
This makes error messages for functions with incorrect argument counts adapt if they refer to a struct or enum variant:
```
error[E0061]: this enum variant takes 1 argument but 0 arguments were supplied
  --> $DIR/struct-enum-wrong-args.rs:7:13
   |
LL |     let _ = Ok();
   |             ^^-- supplied 0 arguments
   |             |
   |             expected 1 argument

error[E0061]: this struct takes 1 argument but 0 arguments were supplied
  --> $DIR/struct-enum-wrong-args.rs:8:13
   |
LL |     let _ = Wrapper();
   |             ^^^^^^^-- supplied 0 arguments
   |             |
   |             expected 1 argument
```

Fixes #86481.

### CODE REVIEW

File: src/test/ui/typeck/struct-enum-wrong-args.rs [hunk 1]
```diff
@@ -0,0 +1,13 @@
+struct Wrapper(i32);
```
Comment (JohnTitor) [inline src/test/ui/typeck/struct-enum-wrong-args.rs:1]: Could you add a reference to the issue as a comment? This will make it easier to understand what the problem was and what this is testing.

```suggestion
// Regression test of #86481.

struct Wrapper(i32);
```

**Review by JohnTitor — APPROVED** [review]

**Review by davidtwco — APPROVED** [review]
Looks good to me, r=me after resolving existing review comments.
