### PR TITLE
Detect unused structs which implement private traits

### LINKED ISSUE #122361: Improve dead_code lint to detect unused structs which implement private traits
### Code

```Rust
#![deny(dead_code)]

struct T;
struct UnusedT1;
struct UnusedT2;

pub trait PubTrait {
    fn foo(&self) -> Self;
}

impl PubTrait for T {
    fn foo(&self) -> Self { T }
}

impl PubTrait for UnusedT1 {
    fn foo(&self) -> Self { UnusedT1 }
}


trait PriTrait {
    fn foo(&self) -> Self;
}

impl PriTrait for T {
    fn foo(&self) -> Self { T }
}

impl PriTrait for UnusedT2 {
    fn foo(&self) -> Self { UnusedT2 }
}

fn main() {
    let t = T;
    let _t = <T as PubTrait>::foo(&t);
    let _t = <T as PriTrait>::foo(&t);
}
```

### Current output

```Shell
error: struct `UnusedT1` is never constructed
 --> src/main.rs:4:8
  |
4 | struct UnusedT1;
  |        ^^^^^^^^
  |
note: the lint level is defined here
 --> src/main.rs:1:9
  |
1 | #![deny(dead_code)]
  |         ^^^^^^^^^

error: could not compile `playground` (bin "playground") due to 1 previous error
```

### Desired output

```Shell
error: struct `UnusedT1` is never constructed
 --> src/main.rs:4:8
  |
4 | struct UnusedT1;
  |        ^^^^^^^^
  |
note: the lint level is defined here
 --> src/main.rs:1:9
  |
1 | #![deny(dead_code)]
  |         ^^^^^^^^^

error: struct `UnusedT2` is never constructed
 --> src/main.rs:5:8
  |
5 | struct UnusedT2;
  |        ^^^^^^^^

error: could not compile `playground` (bin "playground") due to 2 previous errors
```

### Rationale and extra context

_No response_

### Other cases

_No response_

### Rust Version

```Shell
Rustc 1.78.0-nightly (2024-03-11 4a0cc881dcc4d800f106)
```

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by mu001999**
Fixes #122361

### CODE REVIEW

**Comment by mu001999** [comment]
r? compiler

**Comment by fmease** [comment]
Sorry for the delay, I will try to get to this today!

**Comment by mu001999** [comment]
@fmease hello. do you have time? it's okay if not. I can roll the dice again ;)

**Comment by fmease** [comment]
r? compiler

**Comment by fmease** [comment]
Actually,

r? petrochenkov

File: tests/ui/lint/dead-code/unused-adt-impls-trait.rs [hunk 1]
```diff
@@ -0,0 +1,34 @@
...
+impl PriTrait for Used {
+    fn foo(&self) -> Self { Used }
+}
+
+impl PriTrait for Unused {
+    fn foo(&self) -> Self { Unused }
+}
+
+fn main() {
+    let t = Used;
```
Comment (petrochenkov) [inline tests/ui/lint/dead-code/unused-adt-impls-trait.rs:31]: `Used` is used because this variable is constructed (at least).
If the `foo` methods didn't take `self`, then it would be more clear that `Used` is used due to trait impls.

File: compiler/rustc_middle/src/query/mod.rs [hunk 2]
```diff
@@ -819,6 +819,32 @@ rustc_queries! {
...
+    ///
+    /// impl Trait for Type {   // impl_id
+    ///     fn f() {}           // impl_f
+    ///     fn g() {}           // impl_g
+    /// }
+    /// ```
+    ///
+    /// The map returned for `tcx.impl_item_trait_item_ids(impl_id)` would be
+    ///`{ impl_f: trait_f, impl_g: trait_g }`
+    query impl_item_trait_item_ids(impl_id: DefId) -> &'tcx DefIdMap<DefId> {
```
Comment (petrochenkov) [inline compiler/rustc_middle/src/query/mod.rs:843]: Why is this a query, and not just a helper function in dead.rs?

File: compiler/rustc_ty_utils/src/assoc.rs [hunk 3]
```diff
@@ -92,6 +93,13 @@ fn impl_item_implementor_ids(tcx: TyCtxt<'_>, impl_id: DefId) -> DefIdMap<DefId>
         .collect()
 }
 
+fn impl_item_trait_item_ids(tcx: TyCtxt<'_>, impl_id: DefId) -> DefIdMap<DefId> {
+    tcx.associated_items(impl_id)
+        .in_definition_order()
+        .filter_map(|item| item.trait_item_def_id.map(|trait_item| (item.def_id, trait_item)))
```
Comment (petrochenkov) [inline compiler/rustc_ty_utils/src/assoc.rs:99]: All associated items in an impl has the same `trait_item_def_id`, also this is called only for trait impls, so it's always `Some`.

File: compiler/rustc_passes/src/dead.rs [hunk 4]
```diff
@@ -487,32 +488,51 @@ impl<'tcx> MarkSymbolVisitor<'tcx> {
...
+                // for the public method, we don't know the trait item is used or not,
+                // so we mark the method live if the self is used
+                return self.live_symbols.contains(&local_def_id);
+            } else if let Some(trait_item_id) = self
+                .tcx
+                .impl_item_trait_item_ids(impl_id.owner_id.to_def_id())
+                .get(&impl_item_id.to_def_id())
+                && let Some(local_id) = trait_item_id.as_local()
+            {
+                // for the private method, we can know the trait item is ued or not,
```
Comment (petrochenkov) [inline compiler/rustc_passes/src/dead.rs:529]:
```suggestion
                // for the private method, we can know the trait item is used or not,
```

File: compiler/rustc_passes/src/dead.rs [hunk 5]
```diff
@@ -487,32 +488,51 @@ impl<'tcx> MarkSymbolVisitor<'tcx> {
...
-                .partition(|&(impl_id, _)| self.impl_item_with_used_self(impl_id));
+            (ready, unsolved_impl_items) =
+                unsolved_impl_items.into_iter().partition(|&(impl_id, impl_item_id)| {
+                    self.impl_item_with_used_self_and_trait_term(impl_id, impl_item_id)
+                });
         }
     }
 
-    fn impl_item_with_used_self(&mut self, impl_id: hir::ItemId) -> bool {
+    fn impl_item_with_used_self_and_trait_term(
```
Comment (petrochenkov) [inline compiler/rustc_passes/src/dead.rs:508]: What is "trait term"?

Comment (mu001999) [reply compiler/rustc_passes/src/dead.rs:508]: this should be "trait item"

File: tests/ui/lint/dead-code/unused-adt-impls-trait.rs (hunk 1 above)
Comment (mu001999) [reply tests/ui/lint/dead-code/unused-adt-impls-trait.rs:31]: In this implementation, if the `foo` methods didn't take `self`, it will be marked alive when the `foo` is used. Because if it only return `Self`, we can only know the trait item `foo` is used and it may construct the `Unused`, then we can only assume `Unused` is used because we are not sure whether the impl item is not used.

File: compiler/rustc_middle/src/query/mod.rs (hunk 2 above)
Comment (petrochenkov) [reply compiler/rustc_middle/src/query/mod.rs:843]: I suggest using a local cache in dead.rs (in `MarkSymbolVisitor`?), and only after a perf run proving that it is necessary (preferably in a separate PR).

File: tests/ui/lint/dead-code/unused-adt-impls-trait.rs (hunk 1 above)
Comment (petrochenkov) [reply tests/ui/lint/dead-code/unused-adt-impls-trait.rs:31]: Then `let t2 = Unused;` should also be added, because right now the test is not actually testing the difference.

Comment (mu001999) [reply tests/ui/lint/dead-code/unused-adt-impls-trait.rs:31]: I think not, if `let t2 = Unused` is added, then `Unused` is constructed. The difference in this test is the two traits are both used, but we will only lint the struct which is constructed. Without this change, we cannot lint `Unused`.

File: compiler/rustc_passes/src/dead.rs [hunk 6]
```diff
@@ -487,32 +488,51 @@ impl<'tcx> MarkSymbolVisitor<'tcx> {
...
-        } else {
-            false
+            if self.tcx.visibility(impl_item_id).is_public() {
+                // for the public method, we don't know the trait item is used or not,
+                // so we mark the method live if the self is used
+                return self.live_symbols.contains(&local_def_id);
+            } else if let Some(trait_item_id) = self
+                .tcx
+                .impl_item_trait_item_ids(impl_id.owner_id.to_def_id())
+                .get(&impl_item_id.to_def_id())
```
[the remark this answers is not in the document]
Comment (mu001999) [reply compiler/rustc_passes/src/dead.rs:526]: It's trying to find the corresponding trait item id of the give impl item id. So it will return `Some(trait_item_id)` if the `impl_item_id` has the corresponding `trait_item_id`.

File: compiler/rustc_ty_utils/src/assoc.rs (hunk 3 above)
Comment (mu001999) [reply compiler/rustc_ty_utils/src/assoc.rs:99]: We just collect all unsolved impl items firstly, and try to check them after solve other items. One impl item is considered to be used when the self type is used and the corresponding trait item is used. So, getting `trait_item_id` from `impl_item_id` is required to check whether the trait item is used or not.

File: compiler/rustc_passes/src/dead.rs (hunk 6 above)
[the remark this answers is not in the document]
Comment (petrochenkov) [reply compiler/rustc_passes/src/dead.rs:526]: I'd expect something like `tcx.associated_item(impl_item_id)` to be used for this.

[the remark this answers is not in the document]
Comment (mu001999) [reply compiler/rustc_passes/src/dead.rs:526]: I write this because there are only ways to get `impl_item_id` from `trait_item_id`, but no reverse way from `impl_item_id` to `trait_item_id`.

**Comment by mu001999** [comment]
@petrochenkov friendly ping

File: compiler/rustc_passes/src/dead.rs [hunk 7]
```diff
@@ -487,32 +489,63 @@ impl<'tcx> MarkSymbolVisitor<'tcx> {
...
+                return self.live_symbols.contains(&local_def_id);
+            }
+
+            let impl_id = impl_id.owner_id.to_def_id();
+            let impl_item_trait_item_ids = self
+                .impl_item_trait_item_ids_cache
+                .entry(impl_id)
+                .or_insert_with(|| Self::impl_item_trait_item_ids(self.tcx, impl_id));
+
+            if let Some(trait_item_id) = impl_item_trait_item_ids.get(&impl_item_id.to_def_id())
```
Comment (petrochenkov) [inline compiler/rustc_passes/src/dead.rs:532]:
```suggestion
            if let Some(trait_item_id) = self.tcx.associated_item(impl_item_id).trait_item_def_id
```

File: compiler/rustc_passes/src/dead.rs [hunk 8]
```diff
@@ -487,32 +489,63 @@ impl<'tcx> MarkSymbolVisitor<'tcx> {
...
-                .partition(|&(impl_id, _)| self.impl_item_with_used_self(impl_id));
+            (ready, unsolved_impl_items) =
+                unsolved_impl_items.into_iter().partition(|&(impl_id, impl_item_id)| {
+                    self.impl_item_with_used_self_and_trait_item(impl_id, impl_item_id)
+                });
         }
     }
 
-    fn impl_item_with_used_self(&mut self, impl_id: hir::ItemId) -> bool {
+    fn impl_item_with_used_self_and_trait_item(
```
Comment (petrochenkov) [inline compiler/rustc_passes/src/dead.rs:509]:
```suggestion
    fn impl_item_with_used_self(
```
Not sure why this was renamed.
The function name doesn't list its parameters, it says which impl items it applies to (from what I understand).

**Comment by petrochenkov** [comment]
Sorry for the delay, I was either away or busy for quite some time.
@rustbot author

File: compiler/rustc_passes/src/dead.rs (hunk 7 above)
Comment (mu001999) [reply compiler/rustc_passes/src/dead.rs]: Great! I think the description of this method is a bit confused, I skipped it cause it said "Maps from a trait item to the trait item “descriptor”", I thought it only works for trait items.

Comment (mu001999) [reply compiler/rustc_passes/src/dead.rs]: Maybe this doc can be updated?

Comment (petrochenkov) [reply compiler/rustc_passes/src/dead.rs]: Yes, if the doc is unclear then it's better to updated it.

**Comment by Soveu** [comment]
Hey, I stumbled upon this weird edge case after updating to 1.81 nightly (but this also applies to 1.80 beta).
When compiling my hobby OS (https://github.com/Soveu/sovos) I get this warning:

```
warning: struct `GraphicsOutput` is never constructed
 --> uefi/src/protocols/gop.rs:4:12
  |
4 | pub struct GraphicsOutput {
  |            ^^^^^^^^^^^^^^
  |
  = note: `#[warn(dead_code)]` on by default

warning: `uefi` (lib) generated 1 warning
```

I thought it came from the binary, which would be extremely weird, because I definitely use this structure to initialize the framebuffer (https://github.com/Soveu/sovos/blob/3b0505cb6dbdc0ac1e7983309100b2d2bd240617/uefi_wrapper/src/main.rs#L55), but upon closer inspection it comes from the library itself:

```
soveu: ~/git/sovos/libs/uefi $ cargo check
warning: struct `GraphicsOutput` is never constructed
 --> uefi/src/protocols/gop.rs:4:12
  |
4 | pub struct GraphicsOutput {
  |            ^^^^^^^^^^^^^^
  |
  = note: `#[warn(dead_code)]` on by default

warning: `uefi` (lib) generated 1 warning
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.01s
soveu: ~/git/sovos/libs/uefi $
```

I assume the "is never constructed" comes from the fact, that this structure doesn't have all the fields public, so it can't be constructed from outside library, so it must be constructed somewhere inside. That is true, I don't construct the structure, but I cast a pointer to this type in the binary, so it definitely is not dead code. I definitely could refactor the code, so that `locate_protocol` could take `GraphicsOutput` as a template parameter and return a pointer to it, but, well, that is not the case here and now, and it is pretty confusing.

cc @BoxyUwU since we started discussing this PR on discord
