### PR TITLE
Suggests turbofish in patterns

### LINKED ISSUE #114112: Type specifiers with generic args in certain positions should generate errors that reference the turbofish
### Code

```Rust
I'm having trouble creating a concise example, but perhaps the error below is enough. If the error at least mentioned turbofish it'd have saved a bunch of heartache for a noob.
```

### Current output

```Shell
error: expected one of `)`, `,`, `@`, or `|`, found `<`
   --> ....
    |
143 |             Ok(SomeEnum<STRICT>::SomeVariant { result, .. }) => { ... },
    |                           ^
    |                           |
    |                           expected one of `)`, `,`, `@`, or `|`
    |                           help: missing `,`
```

### Desired output

```Shell
" if SomeEnum<STRICT> is a type reference, use SomeEnum::<STRICT> instead"
```

### Rationale and extra context

Rust is elsewhere good about suggesting the turbofish.

### Other cases

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by mu001999**
Fixes #114112

r? @estebank

### CODE REVIEW

File: compiler/rustc_parse/src/parser/pat.rs [hunk 1]
```diff
@@ -804,7 +804,8 @@ impl<'a> Parser<'a> {
             | token::OpenDelim(Delimiter::Brace) // A struct pattern.
             | token::DotDotDot | token::DotDotEq | token::DotDot // A range pattern.
             | token::ModSep // A tuple / struct variant pattern.
-            | token::Not)) // A macro expanding to a pattern.
+            | token::Not // A macro expanding to a pattern.
+            | token::Lt))
```
Comment (compiler-errors) [inline compiler/rustc_parse/src/parser/pat.rs:808]: This needs a comment explaining that this is only valid for recoveries

File: compiler/rustc_parse/src/parser/path.rs [hunk 2]
```diff
@@ -383,6 +383,16 @@ impl<'a> Parser<'a> {
...
             } else {
+                if style == PathStyle::Pat
+                    && self.check_noexpect(&token::Lt)
+                    && self.look_ahead(1, |t| t.can_begin_type())
+                {
+                    self.sess.emit_err(GenericArgsInPatRequireTurbofishSyntax {
+                        span: self.token.span,
+                        suggest_turbofish: self.token.span.shrink_to_lo(),
+                    });
+                }
```
Comment (estebank) [inline compiler/rustc_parse/src/parser/path.rs:394]: Note that by emitting the error but continuing the parse state as is, we are producing multiple spurious parse errors after this. Ideally, we would generate a snapshot, attempt to continue parsing as if this was a path, and if so continue from there.

Comment (MU001999) [reply compiler/rustc_parse/src/parser/path.rs:394]: How about returning the error directly? I have no idea when to generate and restore a snapshot. IMO, we do not need to continue parsing when encountering this error. But this would make the suggestion for anonymous parameters disappear.

File: tests/ui/suggestions/issue-64252-self-type.stderr [hunk 3]
```diff
@@ -1,34 +1,24 @@
...
-   = note: anonymous parameters are removed in the 2018 edition (see RFC 1685)
-help: if this is a `self` type, give it a parameter name
+help: use `::<...>` instead of `<...>` to specify lifetime, type, or const arguments
    |
-LL | pub fn foo(self: Box<Self>) { }
-   |            +++++
-help: if this is a type, explicitly ignore the parameter name
-   |
-LL | pub fn foo(_: Box<Self>) { }
-   |            ++
```
Comment (estebank) [inline tests/ui/suggestions/issue-64252-self-type.stderr:15]: Can you see if we can somehow keep these suggestions around?

**Review by estebank — APPROVED** [review]
If we can manage to keep the suggestion for wrong arbitrary self types that I highlighted, the current approach should work.

**Comment by MU001999** [comment]
@estebank The new commit keeps the suggestions for wrong arbitrary self types that you highlighted. Please review again! ;)

File: compiler/rustc_parse/src/parser/pat.rs [hunk 4]
```diff
@@ -133,7 +139,7 @@ impl<'a> Parser<'a> {
         };
 
         // Parse the first pattern (`p_0`).
-        let mut first_pat = self.parse_pat_no_top_alt(expected)?;
+        let mut first_pat = self.parse_pat_no_top_alt(expected, syntax_loc.clone())?;
```
Comment (estebank) [inline compiler/rustc_parse/src/parser/pat.rs:142]: It's now `Copy`, right?
```suggestion
        let mut first_pat = self.parse_pat_no_top_alt(expected, syntax_loc)?;
```

File: compiler/rustc_parse/src/parser/pat.rs [hunk 5]
```diff
@@ -805,6 +813,7 @@ impl<'a> Parser<'a> {
             | token::DotDotDot | token::DotDotEq | token::DotDot // A range pattern.
             | token::ModSep // A tuple / struct variant pattern.
             | token::Not)) // A macro expanding to a pattern.
+        && !(self.look_ahead(1, |t| t.kind == token::Lt) && self.look_ahead(2, |t| t.can_begin_type())) // May suggest the turbofish syntax for generics, only valid for recoveries.
```
Comment (estebank) [inline compiler/rustc_parse/src/parser/pat.rs:816]: Can we format this line to keep it under 100 lines?
```suggestion
        // May suggest the turbofish syntax for generics, only valid for recoveries.
        && !(self.look_ahead(1, |t| t.kind == token::Lt)
            && self.look_ahead(2, |t| t.can_begin_type())) 
```

File: tests/ui/anon-params/anon-params-denied-2018.stderr [hunk 6]
```diff
@@ -45,10 +45,14 @@ LL |     fn foo_with_qualified_path(<Bar as T>::Baz);
    |                                               ^ expected one of 8 possible tokens
    |
    = note: anonymous parameters are removed in the 2018 edition (see RFC 1685)
-help: explicitly ignore the parameter name
+help: if this is a `self` type, give it a parameter name
+   |
+LL |     fn foo_with_qualified_path(self: <Bar as T>::Baz);
+   |                                +++++
```
Comment (estebank) [inline tests/ui/anon-params/anon-params-denied-2018.stderr:51]: Mmm... Arbitrary self types only support a handful of pointer types (`Box`, `Arc`, `Rc`). General arbitrary self types are unlikely to be supported any time soon, so adding this suggestion would be confusing to users. (I know, I know, but we have to try to minimize confusion to users, the only thing worse than an error without a suggestion is an error with a wrong suggestion.)

File: tests/ui/parser/issues/issue-22647.rs [hunk 7]
```diff
@@ -1,5 +1,5 @@
 fn main() {
-    let caller<F> = |f: F|  //~ ERROR expected one of `:`, `;`, `=`, `@`, or `|`, found `<`
+    let caller<F> = |f: F|  //~ ERROR generic args in patterns require the turbofish syntax
```
Comment (estebank) [inline tests/ui/parser/issues/issue-22647.rs:2]: Looking at this error, the suggestion we should be giving is to add a type, but don't know how hard it would be to change.

File: tests/ui/span/issue-34264.stderr [hunk 8]
```diff
@@ -1,8 +1,8 @@
-error: expected one of `:`, `@`, or `|`, found `<`
+error: expected one of `!`, `(`, `...`, `..=`, `..`, `::`, `:`, `{`, or `|`, found `<`
   --> $DIR/issue-34264.rs:1:14
    |
 LL | fn foo(Option<i32>, String) {}
-   |              ^ expected one of `:`, `@`, or `|`
+   |              ^ expected one of 9 possible tokens
    |
    = note: anonymous parameters are removed in the 2018 edition (see RFC 1685)
 help: if this is a `self` type, give it a parameter name
```
Comment (estebank) [inline tests/ui/span/issue-34264.stderr:8]: Oh, I see that we already provide a bad arbitrary self type suggestion :-/

File: compiler/rustc_parse/src/parser/diagnostics.rs [hunk 9]
```diff
@@ -1579,7 +1579,7 @@ impl<'a> Parser<'a> {
         self.expect(&token::ModSep)?;
 
         let mut path = ast::Path { segments: ThinVec::new(), span: DUMMY_SP, tokens: None };
-        self.parse_path_segments(&mut path.segments, T::PATH_STYLE, None)?;
+        self.parse_path_segments(&mut path.segments, T::PATH_STYLE, None, None)?;
```
Comment (estebank) [inline compiler/rustc_parse/src/parser/diagnostics.rs:1582]: I'm not super happy with the proliferation of `None`s this causes, but I also don't have much of a better proposal (short of having a `*_with_pat_location` family of methods).

File: tests/ui/span/issue-34264.stderr [hunk 10]
```diff
@@ -1,8 +1,8 @@
-error: expected one of `:`, `@`, or `|`, found `<`
+error: expected one of `!`, `(`, `...`, `..=`, `..`, `::`, `:`, `{`, or `|`, found `<`
```
Comment (estebank) [inline tests/ui/span/issue-34264.stderr:1]: If we can, I'd like to revert whatever causes this message change, as I feel the previous one did a good job leading people towards the problem of a missing `:`

File: tests/ui/span/issue-34264.stderr (hunk 8 above)
Comment (MU001999) [reply tests/ui/span/issue-34264.stderr:8]: Yes, and I think we can't just emit suggestions for pointer types in the parsing stage, since we can use type alias `type P<T> = Box<T>`. So I think this is acceptable and the current behaviour extends the old arbitrary self type suggestions.

File: compiler/rustc_parse/src/parser/diagnostics.rs (hunk 9 above)
Comment (MU001999) [reply compiler/rustc_parse/src/parser/diagnostics.rs]: The new changes reduce the `None`s, but there are still some (seemingly unavoidable at the moment)

File: tests/ui/span/issue-34264.stderr (hunk 10 above)
Comment (MU001999) [reply tests/ui/span/issue-34264.stderr]: This is reverted now! ;)

File: tests/ui/anon-params/anon-params-denied-2018.stderr (hunk 6 above)
Comment (MU001999) [reply tests/ui/anon-params/anon-params-denied-2018.stderr]: As mentioned below (https://github.com/rust-lang/rust/pull/114300#discussion_r1282661709)

File: tests/ui/parser/issues/issue-22647.rs (hunk 7 above)
Comment (MU001999) [reply tests/ui/parser/issues/issue-22647.rs:2]: Like function parameters, maybe we can also suggest `name: caller<F>` or `_: caller<F>`? I think it may be more general, because `caller<F>` is more like a type.

Comment (estebank) [reply tests/ui/parser/issues/issue-22647.rs:2]: Yeah, I think the later is the better suggestion (particularly if the rest can be parsed as a type until `;` or `=` is reached).

File: compiler/rustc_parse/src/parser/pat.rs [hunk 11]
```diff
@@ -208,6 +215,7 @@ impl<'a> Parser<'a> {
             rc,
             RecoverColon::No,
             CommaRecoveryMode::LikelyTuple,
+            Some(syntax_loc),
```
Comment (estebank) [inline compiler/rustc_parse/src/parser/pat.rs:218]: making this None would make all the `let` suggestions go away, right?
