### PR TITLE
Only match a fragment specifier if it starts with certain tokens.

### LINKED ISSUE #24189: $( #[$attr:meta] )* $var:ident → error: local ambiguity: multiple parsing options
I’m writing a [macro that parses `enum` declarations](https://github.com/andersk/enum_primitive-rs) to work around #16920, and I’ve discovered that it can’t handle attributes on the `enum` variants like I thought it would. Specifically, the matcher `$( #[$attr:meta] )* $var:ident` fails to match `#[doc = "Bar"] Baz`, complaining “error: local ambiguity: multiple parsing options: built-in NTs ident ('var') or 1 other options.”

This doesn’t seem to make sense, since an `ident` cannot start with `#`.

Small test case:

``` rust
#![crate_type = "lib"]

macro_rules! foo {
    (
        pub enum $name:ident {
            $( #[$attr:meta] )* $var:ident
        }
    ) => {
        pub enum $name {
            $( #[$attr] )* $var
        }
    };
}

foo! {
    pub enum Foo {
        #[doc = "Bar"] Baz
    }
}
```

``` console
$ rustc --version --verbose
rustc 1.0.0-beta (9854143cb 2015-04-02) (built 2015-04-02)
binary: rustc
commit-hash: 9854143cba679834bc4ef932858cd5303f015a0e
commit-date: 2015-04-02
build-date: 2015-04-02
host: x86_64-unknown-linux-gnu
release: 1.0.0-beta
$ rustc r.rs
r.rs:17:9: 17:10 error: local ambiguity: multiple parsing options: built-in NTs ident ('var') or 1 other options.
r.rs:17         #[doc = "Bar"] Baz
                ^
```

### LINKED ISSUE #26444: macro_rules treating ';' as an ident
This [playpen](https://play.rust-lang.org/?gist=bcaf5028ccb692e25803&version=stable) contains a macro with two *-repeating arguments, plus a non-repeating argument sandwiched between them. It works fine when the repeating arguments are supplied, but when I try to leave out the first one, rustc claims the syntax is ambiguous. But I can't see why.

### LINKED ISSUE #27832: Macro matchers only match when they feel like it
...or at least that's how much I currently understand, since macros are really counterintuitive sometimes.

``` rust
macro_rules! m {
    ( $i:ident ) => ();
    ( $t:tt $j:tt ) => ();
}

fn main() {
    m!(c);
    m!(t 9);  // why does this work, but not the next case?

    m!(0 9);
    // ^ error: expected ident, found 0
}
```

I don't think this is supposed to happen. Even if it is, the exact rules used for macro matching should definitely be documented somewhere (I think there's not even an RFC).

### LINKED ISSUE #34030: Spurious local ambiguity error after empty $($ident),*
``` rust
macro_rules! foo {
    ($($t:ident),*/) => {()};
}

fn main() {
    foo!(a, b/);  // works fine
    foo!(a/);     // works fine
    foo!(/);      // local ambiguity error ☹
}
```

```
error: local ambiguity: multiple parsing options: built-in NTs ident ('t') or 1 other option.
 --> <anon>:8:10
8 |>     foo!(/);
  |>          ^
```

In this case, it should be looking for an ident or a `/`, in which there is no ambiguity.

All channels are affected.

This is affecting my ability to write macros accepting generics using angle brackets, e.g. `$ty:ident<$($x:ident),*>`, with a supporting pattern to turn `Foo` into `Foo<>`.

May be related to #24827.

### LINKED ISSUE #35650: Fragment specifiers in macro are not taken into account
Here is a minimum example of the problem.

``` rust
macro_rules! size    {
    ($ty:ty) => {
        std::mem::size_of::<$ty>()
    };
    ($size:tt) => {
        $size
    };
}

fn main()   {
    println!("{}", size!(u32));
    println!("{}", size!(4));
}
```

Compilation fails with following error.

> temp.rs:12:26: 12:27 error: expected type, found `4` 
> temp.rs:12     println!("{}", size!(4));

Which means that the fragment qualifier is not taken into account to choose which variant of the macro is to be used.

### LINKED ISSUE #39964: Strange order dependency for macro that matches _ and ident
A `macro_rules!` macro with two cases that match `_` and `ident` might not match `_` depending on the order of the cases. This works:

```
macro_rules! foo {
    (_) => {};
    ($a:ident) => {};
}

fn main() {
    foo!(_);
}
```

But this doesn't:

```
macro_rules! foo {
    ($a:ident) => {};
    (_) => {};
}

fn main() {
    foo!(_);
}
```

...giving the error message:

```
rustc 1.17.0-nightly (306035c21 2017-02-18)
error: expected ident, found _
 --> <anon>:8:10
  |
8 |     foo!(_);
  |          ^
```

Why would it expect an `ident` there? If `_` isn't an `ident`, shouldn't it just move on to the second macro case and match that?

### PR DESCRIPTION
**Pull request by kennytm**
When trying to match a fragment specifier, we first predict whether the current token can be matched at all. If it cannot be matched, don't bother to push the Earley item to `bb_eis`. This can fix a lot of issues which otherwise requires full backtracking (#42838). 

In this PR the prediction treatment is not done for `:item`, `:stmt` and `:tt`, but it could be expanded in the future.

Fixes #24189.
Fixes #26444.
Fixes #27832.
Fixes #34030.
Fixes #35650.
Fixes #39964.
Fixes the 4th comment in #40569.
Fixes the issue blocking #40984.

### CODE REVIEW

**Comment by kennytm** [comment]
Note that this PR will cause a diagnostic quality degradation, e.g. `vec![,]`, previously:

```rust
error: expected expression, found `,`
  --> 1.rs:12:18
   |
12 |     let v = vec![,];
   |                  ^
```

After this PR:

```rust
error: no rules expected the token `,`
  --> 1.rs:12:18
   |
12 |     let v = vec![,];
   |                  ^
```

**Comment by nikomatsakis** [comment]
So, this is probably a good idea, *but* -- @LeoTestard had actually implemented a *full* fullback mechanism, but we backed off because of the increased potential for problems when the grammar changes. It seems likely that this approach has some the same concerns, although I guess greatly mitigated. (I'd be curious to get @LeoTestard's thoughts.)

**Comment by durka** [comment]
I think the existence of the explicit token lists ("prefix sets"?) is a
mitigation.

**Comment by nikomatsakis** [comment]
Yes, that's true.

**Comment by kennytm** [comment]
Looks like "prefix set" has been proposed before in rust-lang/rfcs#1746. I'm not sure if this PR is exactly the same as 1746 since the RFC looks much more complicated than this PR. 

RFC 1746 was closed expecting matching in macro 2.0 will decouple from the actual grammar, so e.g. `$x:expr` will be equivalent to AFAIK `[^FOLLOW(expr)]+` (such improvement [has not been implemented yet](https://github.com/rust-lang/rust/issues/39412#issuecomment-277867338)). This PR is compatible with that position by viewing an `:expr` still as an opaque regular expression `[FIRST(expr)][^FOLLOW(expr)]*`. For sure macro 2.0 likely won't use `bb_eis` at all, making this PR unnecessary if we restrict the improvement to macro 2.0.

Fixing `FIRST(expr)` would still have an impact on grammar change, but this should be a much less issue than #33840 which is sensitive to the exact grammar. Maybe we need an RFC on this (which is needed for macro 2.0 anyway).

This PR is necessary for `:vis` to work correctly in macro 1.0 (i.e. able to parse `$(#[$attr:meta])* $vis:vis struct ...` — `:vis` needs to know it cannot match `'#'` outside `bb_eis`). Otherwise `:vis` will need to be coupled to macro 2.0 matcher improvement and things like supporting `pub(restricted)` in `thread_local!` (#40984) and `bitflags!` (rust-lang-nursery/bitflags#72) will need to wait a bit longer.

**Review by jseyfried — COMMENTED** [review]
Reviewed, LGTM modulo comment.

File: src/libsyntax/ext/tt/macro_parser.rs [hunk 1]
```diff
@@ -499,6 +498,75 @@ pub fn parse(sess: &ParseSess,
...
+            Token::DotDotDot |                  // range pattern (future compat)
+            Token::ModSep |                     // path
+            Token::Lt |                         // path (UFCS constant)
+            Token::BinOp(token::Shl) |          // path (double UFCS)
+            Token::Underscore => true,          // placeholder
+            Token::Interpolated(ref nt) => may_be_ident(nt),
+            _ => false,
+        },
+        "meta" => match *token {
+            Token::Ident(_) => true,
```
Comment (kennytm) [inline src/libsyntax/ext/tt/macro_parser.rs]: Thanks, added `ModSep` and `NtPath`.

**Comment by aidanhs** [comment]
Pinged @nikomatsakis on IRC for review.

**Comment by aidanhs** [comment]
No I didn't, I pinged @jseyfried. Sorry @nikomatsakis!

**Comment by kennytm** [comment]
@jseyfried Fixed build break from #40939 in 6008004. Currently ignoring the `LazyTokenStream` part of the `Token::Interpolated`.

**Comment by jseyfried** [comment]
Thanks! @bors r+

> Currently ignoring the `LazyTokenStream` part of the `Token::Interpolated`

That's fine, the `LazyTokenStream` only adds more information that isn't relevant to these checks anyway.

**Comment by durka** [comment]
Relnotes? This will release in 1.20, right? I know this is the old macro system, but it seems like a pretty big win for macro writing based on the laundry list of closed issues...
