### PR TITLE
std: Stabilize fixed-width integer atomics

### LINKED ISSUE #32976: Tracking issue for #[cfg(target_has_atomic = ...)]
Tracking https://github.com/rust-lang/rfcs/pull/1543

### LINKED ISSUE #56753: Stabilize the `integer_atomics` feature: Atomic{I,U}{8,16,32,64}
Tracking issue: https://github.com/rust-lang/rust/issues/32976
Documentation: https://doc.rust-lang.org/nightly/std/sync/atomic/

This issue is a proposal to stabilize the `integer_atomics` feature as-is on nightly, modulo some documentation updates. Specifically, for each atomic type, this is proposed:

```rust
impl AtomicU8 {
    pub const fn new(x: u8) -> AtomicU8;
    pub fn get_mut(&mut self) -> &mut u8;
    pub fn into_inner(self) -> u8;
    pub fn load(&self, Ordering) -> u8;
    pub fn store(&self, Ordering) -> u8;
    pub fn swap(&self, val: u8, Ordering) -> u8;
    pub fn compare_and_swap(&self, u8, u8, Ordering) -> u8;
    pub fn compare_exchange(&self, u8, u8, Ordering, Ordering) -> Result<u8, u8>;
    pub fn compare_exchange_weak(&self, u8, u8, Ordering, Ordering) -> Result<u8, u8>;
    pub fn fetch_add(&self, u8, Ordering) -> u8;
    pub fn fetch_sub(&self, u8, Ordering) -> u8;
    pub fn fetch_and(&self, u8, Ordering) -> u8;
    pub fn fetch_nand(&self, u8, Ordering) -> u8;
    pub fn fetch_or(&self, u8, Ordering) -> u8;
    pub fn fetch_xor(&self, u8, Ordering) -> u8;
}
```

## Portability

One of the main points on the [RFC](https://github.com/rust-lang/rfcs/pull/1543) and [tracking issue](https://github.com/rust-lang/rust/issues/32976) is the portability of these types. @alexcrichton has compiled [this table](https://gist.github.com/alexcrichton/516f26c8ce8d832630afdbf22ecda75f) of known platform support, and the conclusions we've drawn with the libs team are:

* The `AtomicUsize` type is already "sketchily" supported. It's not present on armv5te (non-linux) and has a stripped down API on thumv6m
* LLVM emulates small-size atomics with larger atomics (aka 1 byte atomics with 4 byte atomics) on platforms like MIPS. We're unclear on whether it's even possible to safely define these same operations on crates.io, as LLVM might deduce it's undefined behavior. It's sound, however, for LLVM's codegen backend to implement atomics like this.
* AtomicU32 and below are basically universally supported across all platforms that have any atomics at all.
* AtomicU64 actually has a good showing for support as well, except on mips/powerpc platforms.

It's proposed in this stabilization that we stabilize all APIs as-is, knowing that these apis are in a "portable location" yet are not as maximally portable as, say, `Add for u8`. It's intended that platforms which don't support these types simply won't provide the types, as they do today. For example armv5te will continue to have none of these types. (for those following these issues, **it's not proposed that `target_has_atomic` is stabilized as part of this proposal).

While this is a departure from the norms of the rest of the standard library, it's hopefully the most pragmatic decision here.

## What about u128?

Some very recent (aka 20 minutes before this issue was opened) shows that `AtomicU128` can be supported on x86_64 with the LLVM `cx16` feature activated and aarch64 platforms. All other platforms look to require intrinsics one way or another. This proposal doesn't propose stabilizing these just yet, but the thinking is that a stable/safe `std::arch::aarch64::AtomicU128` could be provided while a stable/unsafe `std::arch::x86_64::AtomicU128` could be provided documenting the requirement of the target feature (exact name of the target feature TBD)

## TODO checklist before stabilization:

* [ ] FCP
* [ ] Update documentation to reflect that AtomicU8/16/etc may be implemented in terms of 4-byte atomics
* [ ] Update documentation to reflect that these types are not maximally portable. Architectures that want to be supported should be tested. MIPS and PowerPC do not support AtomicU64, and "more esoteric" platforms like armv5te, thumv6m, etc, have little-to-no support.

### PR DESCRIPTION
**Pull request by alexcrichton**
This commit stabilizes the `Atomic{I,U}{8,16,32,64}` APIs in the
`std::sync::atomic` and `core::sync::atomic` modules. Proposed in #56753
and tracked in #32976 this feature has been unstable for quite some time
and is hopefully ready to go over the finish line now!

The API is being stabilized as-is. The API of `AtomicU8` and friends
mirrors that of `AtomicUsize`. A list of changes made here are:

* A portability documentation section has been added to describe the
  current state of affairs.
* Emulation of smaller-size atomics with larger-size atomics has been
  documented.
* As an added bonus, `ATOMIC_*_INIT` is now scheduled for deprecation
  across the board in 1.34.0 now that `const` functions can be invoked
  in statics.

Note that the 128-bit atomic types are omitted from this stabilization
explicitly. They have far less platform support than the other atomic
types, and will likely require further discussion about their best
location.

Closes #32976
Closes #56753

### CODE REVIEW

**Comment by alexcrichton** [comment]
Note that this is currently still blocked on the FCP in https://github.com/rust-lang/rust/issues/56753, so this shouldn't be approved until that FCP has finished.

File: src/libcore/sync/atomic.rs [hunk 1]
```diff
@@ -31,11 +34,44 @@
...
+//! * PowerPC and MIPS platforms with 32-bit pointers do not have `AtomicU64` or
+//!   `AtomicI64` types.
+//! * ARM platforms like `armv5te` that aren't for Linux do not have any atomics
+//!   at all.
+//! * ARM targets with `thumbv6m` do not have atomic operations at all.
+//!
+//! Note that future platforms may be added that also do not have support for
+//! some atomic operations. Maximally portable code will want to be careful
+//! about which atomic types are used. `AtomicUsize` and `AtomicIsize` are
+//! generally the most portable, but even then they're not available everywhere.
```
Comment (Amanieu) [inline src/libcore/sync/atomic.rs]: Should we explicitly say libstd requires pointer-sized atomics, so only `#![no_std]` code needs to worry about atomic types being absent?

Comment (alexcrichton) [reply src/libcore/sync/atomic.rs]: 👍

**Comment by alexcrichton** [comment]
r? @sfackler 

(for eventual stabilization)

File: src/libcore/sync/atomic.rs [hunk 2]
```diff
@@ -1931,12 +1972,12 @@ atomic_int! {
...
-    unstable(feature = "integer_atomics", issue = "32976"),
-    unstable(feature = "integer_atomics", issue = "32976"),
-    unstable(feature = "integer_atomics", issue = "32976"),
-    unstable(feature = "integer_atomics", issue = "32976"),
+    stable(feature = "integer_atomics_stable", since = "1.33.0"),
+    stable(feature = "integer_atomics_stable", since = "1.33.0"),
+    stable(feature = "integer_atomics_stable", since = "1.33.0"),
+    stable(feature = "integer_atomics_stable", since = "1.33.0"),
+    stable(feature = "integer_atomics_stable", since = "1.33.0"),
+    stable(feature = "integer_atomics_stable", since = "1.33.0"),
```
Comment (Centril) [inline src/libcore/sync/atomic.rs]: If you want to wait out the full FCP duration (10 days) then this will miss the 1.33 master=>beta promotion date which is on the 15th of January (FCP completes around 18-19th).

Comment (hellow554) [reply src/libcore/sync/atomic.rs]: I guess this needs to be changed to 1.34.0 then ;)

**Comment by Centril** [comment]
Ping from triage @alexcrichton and @sfackler :)

**Comment by alexcrichton** [comment]
Oops, thanks for the ping!

@bors: r=sfackler
