### PR TITLE
windows-gnu: prefer system crt libraries if they are available

### LINKED ISSUE #47048: under latest MinGW, cannot link with C code using stdout
I'm having an issue under MinGW and I'm not sure if it's a MinGW issue or a rustc issue. On the one hand the bug crops up after an update to two MinGW packages, but on the other hand I cannot reproduce with only C, and I don't know if rustc is using MinGW in some undocumented unsupported way.

say_hi.c:
```c
#include <stdio.h>
void say_hi(void) {
    fprintf(stdout, "hi!\n");
}
```
c_main.c
```c
void say_hi(void);
int main(void) {
    say_hi();
    return 0;
}
```
r_main.rs:
```rust
extern "C" {
    fn say_hi();
}
fn main() {
    unsafe {
        say_hi();
    }
}
```

Under the latest MinGW, specifically with packages

* `mingw-w64-x86_64-crt-git-6.0.0.5066.61efe559-1` and
* `mingw-w64-x86_64-headers-git-6.0.0.5066.61efe559-1`,

using only gcc like this works:
```
$ gcc -c say_hi.c
$ ar cr libsay_hi.a say_hi.o
$ gcc c_main.c -L. -lsay_hi -o c_main.exe && ./c_main.exe
hi!
```
But it doesn't work with rustc:
```
$ gcc -c say_hi.c
$ ar cr libsay_hi.a say_hi.o
$ rustc r_main.rs -L. -lsay_hi -o r_main.exe && ./r_main.exe
error: linking with `gcc` failed: exit code: 1
  |
  = note: "gcc" "-Wl,--enable-long-section-names" "-fno-use-linker-plugin" "-Wl,--nxcompat" "-nostdlib" "-m64" "C:\\Users\\Trevor\\.rustup\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\crt2.o" "C:\\Users\\Trevor\\.rustup\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\rsbegin.o" "-L" "C:\\Users\\Trevor\\.rustup\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib" "r_main.r_main0.rust-cgu.o" "-o" "r_main.exe" "r_main.crate.allocator.rust-cgu.o" "-Wl,--gc-sections" "-nodefaultlibs" "-L" "." "-L" "C:\\Users\\Trevor\\.rustup\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib" "-l" "say_hi" "-Wl,-Bstatic" "C:\\Users\\Trevor\\.rustup\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\libstd-60d4a252bdda9250.rlib" "C:\\Users\\Trevor\\.rustup\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\liballoc_system-a05404e5e059417a.rlib" "C:\\Users\\Trevor\\.rustup\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\librand-81cbf6f1d5a19206.rlib" "C:\\Users\\Trevor\\.rustup\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\libpanic_unwind-0b63e20460046692.rlib" "C:\\Users\\Trevor\\.rustup\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\liballoc-f824a78e715239af.rlib" "C:\\Users\\Trevor\\.rustup\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\libstd_unicode-2abaea46f194a6e1.rlib" "C:\\Users\\Trevor\\.rustup\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\libunwind-7daa32005d584d8a.rlib" "C:\\Users\\Trevor\\.rustup\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\liblibc-49ff25caaa6e945f.rlib" "C:\\Users\\Trevor\\.rustup\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\libcore-f2bd2d524c6ace24.rlib" "C:\\Users\\Trevor\\.rustup\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\libcompiler_builtins-c6139fac5e899293.rlib" "-Wl,-Bdynamic" "-l" "advapi32" "-l" "ws2_32" "-l" "userenv" "-l" "shell32" "-Wl,-Bstatic" "-l" "gcc_eh" "-l" "pthread" "-Wl,-Bdynamic" "-lmingwex" "-lmingw32" "-lgcc" "-lmsvcrt" "-luser32" "-lkernel32" "C:\\Users\\Trevor\\.rustup\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\rsend.o"
  = note: ./libsay_hi.a(say_hi.o):say_hi.c:(.text+0x10): undefined reference to `__imp___acrt_iob_func'
          

error: aborting due to previous error
```

If I downgrade those two packages to

* `mingw-w64-x86_64-crt-git-5.0.0.5002.34a7c1c0-1` and
* `mingw-w64-x86_64-headers-git-5.0.0.5002.34a7c1c0-1`,

it works with rustc too:
```
$ gcc -c say_hi.c
$ ar cr libsay_hi.a say_hi.o
$ rustc r_main.rs -L. -lsay_hi -o r_main.exe && ./r_main.exe
hi!
```

One last thing, if I compile the library using the old packages, and then upgrade the packages, both `gcc c_main.c ...` and `rustc r_main.rs ...` work. If I compile the library using the new packages, and then downgrade the packages, both `gcc c_main.c ...` and `rustc r_main.rs ...` fail.

### LINKED ISSUE #49078: build an empty project failed (undefined reference to `__onexitbegin')
toolchain:  

```
nightly-x86_64-pc-windows-msvc (default)
rustc 1.26.0-nightly (521d91c6b 2018-03-14)
```

build command: `cargo run --target x86_64-pc-windows-gnu`

error message:

```
.rustup\toolchains\nightly-x86_64-pc-windows-msvc\lib\rustlib\x86_64-pc-windows-gnu\lib\crt2.o:crtexe.c:(.rdata$.refptr.__onexitbegin[.refptr.__onexitbegin]+0x0): undefined reference to `__onexitbegin'

.rustup\toolchains\nightly-x86_64-pc-windows-msvc\lib\rustlib\x86_64-pc-windows-gnu\lib\crt2.o:crtexe.c:(.rdata$.refptr.__onexitend[.refptr.__onexitend]+0x0): undefined reference to `__onexitend'
          collect2.exe: error: ld returned 1 exit status
```

possible reason:

1. rustc bug?

2. rustlib bug?

3. msys2 gcc issues?

### LINKED ISSUE #53454: Issues with crt2.o and dllcrt2.o from mingw.
Those crt2.o and dllcrt2.o files have to match the gcc.exe used. So for example when i use win-gnu target in a msvc toolchain, I'll install my own copy of MINGW, and it should provide gcc.exe and those .o files, and i shouldn't use the rust-provided one.

So I suggest:
1. We package these files in "rust-mingw" component instead of current "rust-std" component in win-gnu builds.
2. Make people able to use an environment variable or something to specify where to pick these .o files in the linker command.

### LINKED ISSUE #60912: MinGW: undefined reference to _imp___wassert
There is a very particular set of circumstances that leads to the following error when compiling some C++ files and linking them into a Rust executable targeted at `stable-i686-pc-windows-gnu`:

```
$ cargo run -vv
[...]
  = note: C:\...\out\libval.a(val.o): In function `ZN3val9do_assertEv':
          C:\....\src\val.h:8: undefined reference to `_imp___wassert'
```

**Summary**: I believe the Rust MinGW toolchain needs to be rebuilt or updated to include `_imp___wassert` (which I believe is the dynamically linked [`_wassert`](https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/assert-macro-assert-wassert?view=vs-2019)).

I used the repository https://github.com/spl/rust-assert-unicode-test on a [Windows VM](https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/) with MSYS2 and MingW32 installed. Unfortunately, I could not reproduce the issue on [Travis-CI](https://travis-ci.com/spl/rust-assert-unicode-test/builds/112196125) or [AppVeyor](https://ci.appveyor.com/project/spl/rust-assert-unicode-test/builds/24614839), but it happens reliably on my VM. (I don't have MSVC installed, but I don't know if that's the reason.)

These are the key files:

`src/val.h`:

```c++
#include <cassert>
class val {
    int mv;
public:
    val(int v) : mv(v) { }
    void do_assert() { assert(mv > 0); }
};
```

`src/val.cpp`:

```c++
#include "val.h"
void use_val() {
    val v(42);
    v.do_assert();
}
```

`build.rs`:

```rust
extern crate cc;
fn main() {
    println!("cargo:rerun-if-env-changed=UNICODE");
    let mut cfg = cc::Build::new();
    if std::env::var_os("UNICODE").is_some() {
        cfg.define("UNICODE", None);
    }
    cfg.file("src/val.cpp").cpp(true).compile("libval.a");
}
```

For context, here is the snippet that defines `assert()` in [`assert.h`](https://github.com/Alexpux/mingw-w64/blob/c7d4925fd55972ea5e71010888951db0fb35bdeb/mingw-w64-headers/crt/assert.h) from mingw-w64:

```c
#ifdef NDEBUG
#if defined(_UNICODE) || defined(UNICODE)
#define assert(_Expression) \
  (void) \
  ((!!(_Expression)) || \
    (_wassert(_CRT_WIDE(#_Expression),_CRT_WIDE(__FILE__),__LINE__),0))
#else /* not unicode */
#define assert(_Expression) \
  (void) \
  ((!!(_Expression)) || \
    (_assert(#_Expression,__FILE__,__LINE__),0))
#endif /* _UNICODE||UNICODE */
#endif /* !defined (NDEBUG) */
```

With nothing in the environment, the build succeeds:

```
$ cargo build -vv
[...]
[rust-assert-unicode-test 0.1.0] running: "g++.exe" "-O0" "-ffunction-sections" "-fdata-sections" "-g" "-fno-omit-frame-pointer" "-m32" "-Wall" "-Wextra" "-o" "C:\\...\\rust-assert-unicode-test\\target\\debug\\build\\rust-assert-unicode-test-...\\out\\src\\val.o" "-c" "src/val.cpp"
[...]
```

It's useful to look at the symbols in the library:

```
$ nm target/debug/build/rust-assert-unicode-test-.../out/libval.a | grep assert
00000000 r .eh_frame$_ZN3val9do_assertEv
00000000 t .text$_ZN3val9do_assertEv
         U __imp___assert
00000000 T __ZN3val9do_assertEv
```

With `-DUNICODE`, the build fails:

```
$ export UNICODE=-DUNICODE
$ cargo build -vv
error: linking with `gcc` failed: exit code: 1
  |
  = note: "gcc" "-Wl,--enable-long-section-names" "-fno-use-linker-plugin" "-Wl,--nxcompat" "-nostdlib" "-Wl,--large-address-aware" "C:\\...\\.rustup\\toolchains\\stable-i686-pc-windows-gnu\\lib\\rustlib\\i686-pc-windows-gnu\\lib\\crt2.o" "C:\\...\\.rustup\\toolchains\\stable-i686-pc-windows-gnu\\lib\\rustlib\\i686-pc-windows-gnu\\lib\\rsbegin.o" "-L" "C:\\...\\.rustup\\toolchains\\stable-i686-pc-windows-gnu\\lib\\rustlib\\i686-pc-windows-gnu\\lib" "C:\\...\\rust-assert-unicode-test\\target\\debug\\deps\\rust_assert_unicode_test-....1y0whtr9r0u7l2ur.rcgu.o" "C:\\...\\rust-assert-unicode-test\\target\\debug\\deps\\rust_assert_unicode_test-....24fzsbft0yc0w6fe.rcgu.o" "C:\\...\\rust-assert-unicode-test\\target\\debug\\deps\\rust_assert_unicode_test-....2b0sh6ymgfums8kn.rcgu.o" "C:\\...\\rust-assert-unicode-test\\target\\debug\\deps\\rust_assert_unicode_test-....3vrz8j8szp1mh8k8.rcgu.o" "C:\\...\\rust-assert-unicode-test\\target\\debug\\deps\\rust_assert_unicode_test-....4mut1jzgau8wqplt.rcgu.o" "C:\\...\\rust-assert-unicode-test\\target\\debug\\deps\\rust_assert_unicode_test-....599jfg9iyzg2frg1.rcgu.o" "-o" "C:\\...\\rust-assert-unicode-test\\target\\debug\\deps\\rust_assert_unicode_test-....exe" "C:\\...\\rust-assert-unicode-test\\target\\debug\\deps\\rust_assert_unicode_test-....phl7t4fk0vvdm4y.rcgu.o" "-Wl,--gc-sections" "-nodefaultlibs" "-L" "C:\\...\\rust-assert-unicode-test\\target\\debug\\deps" "-L" "C:\\...\\rust-assert-unicode-test\\target\\debug\\build\\rust-assert-unicode-test-...\\out" "-L" "C:\\...\\.rustup\\toolchains\\stable-i686-pc-windows-gnu\\lib\\rustlib\\i686-pc-windows-gnu\\lib" "-Wl,-Bstatic" "-Wl,--whole-archive" "-lval" "-Wl,--no-whole-archive" "-Wl,-Bdynamic" "-lstdc++" "-Wl,--start-group" "-Wl,-Bstatic" "C:\\...\\.rustup\\toolchains\\stable-i686-pc-windows-gnu\\lib\\rustlib\\i686-pc-windows-gnu\\lib\\libstd-352224e4f0f52495.rlib" "C:\\...\\.rustup\\toolchains\\stable-i686-pc-windows-gnu\\lib\\rustlib\\i686-pc-windows-gnu\\lib\\libpanic_unwind-1df48bb698babe0f.rlib" "C:\\...\\.rustup\\toolchains\\stable-i686-pc-windows-gnu\\lib\\rustlib\\i686-pc-windows-gnu\\lib\\libbacktrace_sys-e33d2aecefe6e52a.rlib" "C:\\...\\.rustup\\toolchains\\stable-i686-pc-windows-gnu\\lib\\rustlib\\i686-pc-windows-gnu\\lib\\libunwind-6cd6f50b682d440b.rlib" "C:\\...\\.rustup\\toolchains\\stable-i686-pc-windows-gnu\\lib\\rustlib\\i686-pc-windows-gnu\\lib\\librustc_demangle-f70dc1fec692eefd.rlib" "C:\\...\\.rustup\\toolchains\\stable-i686-pc-windows-gnu\\lib\\rustlib\\i686-pc-windows-gnu\\lib\\liblibc-659fb6a5c340607f.rlib" "C:\\...\\.rustup\\toolchains\\stable-i686-pc-windows-gnu\\lib\\rustlib\\i686-pc-windows-gnu\\lib\\liballoc-9d1d98d6712272cf.rlib" "C:\\...\\.rustup\\toolchains\\stable-i686-pc-windows-gnu\\lib\\rustlib\\i686-pc-windows-gnu\\lib\\librustc_std_workspace_core-899502000089d7f2.rlib" "C:\\...\\.rustup\\toolchains\\stable-i686-pc-windows-gnu\\lib\\rustlib\\i686-pc-windows-gnu\\lib\\libcore-dcb03e66209691e3.rlib" "-Wl,--end-group" "C:\\...\\.rustup\\toolchains\\stable-i686-pc-windows-gnu\\lib\\rustlib\\i686-pc-windows-gnu\\lib\\libcompiler_builtins-d3bba173fb7c9a29.rlib" "-Wl,-Bdynamic" "-ladvapi32" "-lws2_32" "-luserenv" "-Wl,-Bstatic" "-lgcc_eh" "-lpthread" "-Wl,-Bdynamic" "-lmingwex" "-lmingw32" "-lgcc" "-lmsvcrt" "-lmsvcrt" "-luser32" "-lkernel32" "C:\\...\\.rustup\\toolchains\\stable-i686-pc-windows-gnu\\lib\\rustlib\\i686-pc-windows-gnu\\lib\\rsend.o"
  = note: C:\...\rust-assert-unicode-test\target\debug\build\rust-assert-unicode-test-...\out\libval.a(val.o): In function `ZN3val9do_assertEv':
          C:\...\rust-assert-unicode-test/src/val.h:8: undefined reference to `_imp___wassert'
```

Looking at the symbols in the library confirms that `_imp___wassert` is there (and that `__imp___assert` is not, as would be expected):

```
$ nm target/debug/build/rust-assert-unicode-test-.../out/libval.a | grep assert
00000000 r .eh_frame$_ZN3val9do_assertEv
00000000 t .text$_ZN3val9do_assertEv
         U __imp___wassert
00000000 T __ZN3val9do_assertEv
```

One way to work around this issue is to link directly to the MinGW `msvcrt` library:

```
$ RUSTFLAGS="-Clink-arg=C:/msys32/mingw32/i686-w64-mingw32/lib/libmsvcrt.a" cargo build -vv
```

Looking at what was linked with [Process Monitor](https://docs.microsoft.com/en-us/sysinternals/downloads/procmon), I found that the bundled `msvcrt` library was being used. And, indeed, that library is missing `__imp___wassert`:

```
$ nm C:/.../.rustup/toolchains/stable-i686-pc-windows-gnu/lib/rustlib/i686-pc-windows-gnu/lib/libmsvcrt.a | grep assert
00000000 I __imp___assert
```

Looking at the symbols in MinGW's `msvcrt`, I can now see why linking to it works:

```
$ nm C:/msys32/mingw32/i686-w64-mingw32/lib/libmsvcrt.a | grep assert
00000000 T __assert
00000000 I __imp___assert
lib32_libmsvcrt_os_a-wassert.o:
         U __assert
00000000 D __imp___wassert
000000d0 t _init_wassert
00000000 t _mingw_wassert
```

There are no definitions of the `__imp___wassert` symbol in `C:/.../.rustup/toolchains/stable-i686-pc-windows-gnu/lib/rustlib/i686-pc-windows-gnu/lib/*.a`.

### PR DESCRIPTION
**Pull request by mati865**
The origin of the issue is the fact Rust ships mingw-w64 libraries but no headers and prefers own libraries over the system ones.
This leads to situation when headers aren't compatible with libraries (mingw-w64 doesn't provide any forward compatibility and AFAIK backwards compatibility is guaranteed only within major release series).

It's easier to understand how this PR works when looking at the linker invocation before and with this PR: https://www.diffchecker.com/GEuYFmzo
It adds system libraries path before Rust libraries so the linker will prefer them.
It has potential issue when system has files with the same names as Rust but that could be avoided by moving Rust shipped mingw-w64 libraries from `lib/rustlib/x86_64-pc-windows-gnu/lib` to say `lib/rustlib/x86_64-pc-windows-gnu/lib/mingw`. Then adding linker paths in this order: Rust libraries, system libraries, Rust shipped mingw-w64 libraries.

Fixes #47048
Fixes #49078
Fixes #53454
Fixes #60912

### CODE REVIEW

**Comment by mati865** [comment]
CC developers who seem interested in this: @Amanieu @Mark-Simulacrum @nikomatsakis @pnkfelix

File: src/librustc_codegen_ssa/back/link.rs [hunk 1]
```diff
@@ -899,7 +906,47 @@ pub fn print_native_static_libs(sess: &Session, all_native_libs: &[NativeLibrary
...
+                *SYSTEM_LIBS.lock().unwrap() = Some(compiler_libs_path.clone());
+                return Some(compiler_libs_path);
+            }
+        }
+    }
+    None
+}
+
 pub fn get_file_path(sess: &Session, name: &str) -> PathBuf {
+    #[cfg(all(windows, target_env = "gnu"))]
```
Comment (retep998) [inline src/librustc_codegen_ssa/back/link.rs]: This applies to when the *host* is `pc-windows-gnu` and not when the *target* is `pc-windows-gnu`.

Comment (mati865) [reply src/librustc_codegen_ssa/back/link.rs]: That's the problem I mentioned in the PR.
It's also required when cross compiling but it doesn't work yet.

**Comment by mati865** [comment]
I think this won't work for cross compiling but let's see.

Can somebody give it `@bors try`?

**Comment by mati865** [comment]
Tested and confirmed that this PR works well on Windows but when cross compiling it still picks bundled `crt2.o`.

I don't have idea how to modify all those `#[cfg(all(windows, target_env = "gnu"))]` so they do work when cross compiling from and could use some help.

**Comment by jonas-schievink** [comment]
The Session object should contain info about the target platform

**Comment by mati865** [comment]
@jonas-schievink it does but how can I make it work with `lazy_static`?
https://github.com/rust-lang/rust/pull/67429/files#diff-9ca19d99192e8dfc0cb4f0b90eb82c46R44-R47

**Comment by jonas-schievink** [comment]
I don't think you need a lazy_static there, a regular (function-scoped) static should suffice. Then the function can fill in the data when called for the first time.

**Comment by mati865** [comment]
@jonas-schievink wouldn't that involve `static mut` which is "bad"(https://github.com/rust-lang/rust/issues/53639)?

**Comment by jonas-schievink** [comment]
Ah, right. If you can use the `parking_lot` Mutex you can const-construct it and don't need a `static mut`.

I think you can do the same with the current code though, by removing the `#[cfg]`s from most stuff. Then you can make use of the `Session` to detect the target platform.

**Comment by mati865** [comment]
Okay, this works fine on native Windows.

I'd like to test cross compilation so can somebody do @bors try?

**Comment by mati865** [comment]
Updated description.

**Comment by nikomatsakis** [comment]
@retep998 can I interpret [your review here](https://github.com/rust-lang/rust/pull/67429#pullrequestreview-335595535) as approving of this overall approach?

**Comment by retep998** [comment]
If the user has MinGW already on the system then preferring that over the bundled MinGW is definitely the right approach.

**Review by retep998 — APPROVED** [review]

File: src/librustc_codegen_ssa/back/link.rs [hunk 2]
```diff
@@ -918,7 +918,53 @@ pub fn print_native_static_libs(sess: &Session, all_native_libs: &[NativeLibrary
...
+    let system_libs = SYSTEM_LIBS.lock().unwrap().clone();
+    if let Some(compiler_libs_path) = system_libs {
+        println!("cache: hit");
+        return Some(compiler_libs_path);
+    } else {
+        println!("cache: miss");
+        let compiler = if let Some(linker) = &sess.opts.cg.linker {
+            linker.clone().into_os_string()
+        } else if let Some(linker) = &sess.target.target.options.linker {
+            linker.into()
```
Comment (alexcrichton) [inline src/librustc_codegen_ssa/back/link.rs]: IIRC there's a dedicated function to getting the linker program, could that be used rather than inspecting the various options manually?

File: src/librustc_codegen_ssa/back/link.rs [hunk 3]
```diff
@@ -918,7 +918,53 @@ pub fn print_native_static_libs(sess: &Session, all_native_libs: &[NativeLibrary
...
+fn get_crt_libs_path(sess: &Session) -> Option<PathBuf> {
+    use std::sync::Mutex;
+
+    lazy_static::lazy_static! {
+        static ref SYSTEM_LIBS: Mutex<Option<PathBuf>> = Mutex::new(None);
+    }
+
+    let system_libs = SYSTEM_LIBS.lock().unwrap().clone();
+    if let Some(compiler_libs_path) = system_libs {
+        println!("cache: hit");
```
Comment (alexcrichton) [inline src/librustc_codegen_ssa/back/link.rs]: As a note these will want removal before landing (the prints)

File: src/librustc_codegen_ssa/back/link.rs [hunk 4]
```diff
@@ -918,7 +918,53 @@ pub fn print_native_static_libs(sess: &Session, all_native_libs: &[NativeLibrary
...
+        let compiler = if let Some(linker) = &sess.opts.cg.linker {
+            linker.clone().into_os_string()
+        } else if let Some(linker) = &sess.target.target.options.linker {
+            linker.into()
+        } else {
+            return None;
+        };
+        if let Ok(output) = Command::new(compiler).arg("-print-file-name=crt2.o").output() {
+            if let Some(compiler_libs_path) =
+                PathBuf::from(std::str::from_utf8(&output.stdout).unwrap()).parent()
```
Comment (alexcrichton) [inline src/librustc_codegen_ssa/back/link.rs]: This'll want to avoid the `.unwrap()`

File: src/librustc_codegen_ssa/back/link.rs [hunk 5]
```diff
@@ -918,7 +918,53 @@ pub fn print_native_static_libs(sess: &Session, all_native_libs: &[NativeLibrary
...
+    lazy_static::lazy_static! {
+        static ref SYSTEM_LIBS: Mutex<Option<PathBuf>> = Mutex::new(None);
+    }
+
+    let system_libs = SYSTEM_LIBS.lock().unwrap().clone();
+    if let Some(compiler_libs_path) = system_libs {
+        println!("cache: hit");
+        return Some(compiler_libs_path);
+    } else {
+        println!("cache: miss");
```
Comment (alexcrichton) [inline src/librustc_codegen_ssa/back/link.rs]: I think that we're going to want to cache a `None` value as well if we're caching anything at all, because if spawning a process fails we don't want to fail to spawn the process each time.

File: src/librustc_codegen_ssa/back/link.rs (hunk 2 above)
Comment (alexcrichton) [reply src/librustc_codegen_ssa/back/link.rs]: Additionally, can this only execute when the linker flavor is gcc?

**Review by alexcrichton — COMMENTED** [review]
Is it possible to do this any faster without spawning a process? Spawning processes on Windows is notoriously slow and doing it one extra time per compiler invocation can be quite bad. For example this will be a huge amount more processes in the compiletest test suite.

Is it possible to detect that we're invoking the system linker (perhaps by looking at `PATH`) and then invoking the linker with different flags? That way we wouldn't have to do any sort of pre-probing or anything like that.

File: src/librustc_codegen_ssa/back/link.rs (hunk 2 above)
Comment (mati865) [reply src/librustc_codegen_ssa/back/link.rs]: > IIRC there's a dedicated function to getting the linker program

I wasn't aware, will take a look next week.

> Additionally, can this only execute when the linker flavor is gcc?

Great idea!

File: src/librustc_codegen_ssa/back/link.rs (hunk 3 above)
Comment (mati865) [reply src/librustc_codegen_ssa/back/link.rs]: Ofc, I left it for now so the reviewer can take a look at https://pastebin.com/kGEQZGWP and see what is going on.

File: src/librustc_codegen_ssa/back/link.rs (hunk 5 above)
Comment (mati865) [reply src/librustc_codegen_ssa/back/link.rs]: I haven't thought about it, sounds good!

**Comment by mati865** [comment]
> Spawning processes on Windows is notoriously slow

True

> doing it one extra time per compiler invocation can be quite bad.

Only during linking but yeah.

> Is it possible to do this any faster without spawning a process?

IIRC clang has a list of all common mingw-w64 headers/crt locations relative to it's path (and maybe `gcc.exe`?). Is it much cheaper to only find executable path?

**Comment by mati865** [comment]
If Clang cannot find MinGW on [it's own](https://github.com/llvm-mirror/clang/blob/7823560840f75b2a59347a03c422783d0dd913f4/lib/Driver/ToolChains/MinGW.cpp#L381), it will [look for GCC inside `PATH`](https://github.com/llvm/llvm-project/blob/75eacbf1a9fbc29432a6e0c5627e6c8e95683956/llvm/lib/Support/Windows/Program.inc#L36) and then add relative lib path.

---

> Is it possible to detect that we're invoking the system linker (perhaps by looking at PATH) and then invoking the linker with different flags? That way we wouldn't have to do any sort of pre-probing or anything like that.

I've got an untested idea when looking at `-Z print-link-args` on Linux.
We can move all MinGW stuff to subdirectory and add that directory as the last PATH location.

For cross-compilation one requires system MinGW anyway so not installing `{,dll}crt2.o` as part of stdlib is all we need to fix it.

On Windows that would make system toolchain always preferred if available and GCC shipped by Rust can easily find it's libraries as long as they are in proper relative location:
```
$ /c/Users/mateusz/.rustup/toolchains/beta-x86_64-pc-windows-gnu/lib/rustlib/x86_64-pc-windows-gnu/bin/gcc.exe -print-file-name=crt2.o
C:/Users/mateusz/.rustup/toolchains/beta-x86_64-pc-windows-gnu/lib/rustlib/x86_64-pc-windows-gnu/bin/../lib/gcc/x86_64-w64-mingw32/6.3.0/../../../../lib/crt2.o
```
So we don't have to add any paths via `-L`.

**Comment by cup** [comment]
https://github.com/rust-lang/rust/issues/47048
https://github.com/rust-lang/rust/issues/49078
https://github.com/rust-lang/rust/issues/53454
https://github.com/rust-lang/rust/issues/59604
https://github.com/rust-lang/rust/issues/60912
https://github.com/rust-lang/rust/issues/67483

https://github.com/rust-lang/rust/pull/67429

**Comment by mati865** [comment]
> I've got an untested idea when looking at `-Z print-link-args` on Linux.
We can move all MinGW stuff to subdirectory and add that directory as the last PATH location.

Okay, played a bit and this is not going to work because `pre_link_objects` must be passed by full path.

> Is it possible to do this any faster without spawning a process?

@alexcrichton what do you think would be better, ask GCC for the location or iterate through `PATH` looking for the linker (gcc or clang) and probe usual MinGW locations similarly to how [clang does it](https://github.com/llvm-mirror/clang/blob/7823560840f75b2a59347a03c422783d0dd913f4/lib/Driver/ToolChains/MinGW.cpp#L392-L396).

**Comment by alexcrichton** [comment]
Ah yeah I don't really have too much of a preference of how to fix this, but I would love to see favoring a system toolchain wherever we can. 

I do think it's faster to check `PATH` rather than spawning a process (since spawning a process checks `PATH` anyway). I think mirroring clang in this respect should be good to implement here too.

**Comment by mati865** [comment]
Can I have @bors try?

Local dist builds fail with the error for some time for me (probably Python update caused it):
```
Dist mingw (x86_64-pc-windows-gnu)
thread 'main' panicked at 'fs::remove_dir_all(&image) failed with Access Denied. (os error 5)', src\bootstrap\dist.rs:381:9
```

File: src/librustc_codegen_ssa/back/link.rs [hunk 6]
```diff
@@ -968,7 +968,80 @@ pub fn print_native_static_libs(sess: &Session, all_native_libs: &[NativeLibrary
...
+// own mingw-w64 libraries. These libraries are often not compatible with mingw-w64
+// installed in the system. This breaks many cases where Rust is mixed with other languages
+// (e.g. *-sys crates).
+// We prefer system mingw-w64 libraries if they are available to avoid this issue.
+fn get_crt_libs_path(sess: &Session) -> Option<PathBuf> {
+    fn find_exe_in_path<P>(exe_name: P) -> Option<PathBuf>
+    where
+        P: AsRef<Path>,
+    {
+        env::var_os("PATH").and_then(|paths| {
```
Comment (alexcrichton) [inline src/librustc_codegen_ssa/back/link.rs]: Instead of `.and_then`, this can probably use `?` I think?

File: src/librustc_codegen_ssa/back/link.rs [hunk 7]
```diff
@@ -968,7 +968,80 @@ pub fn print_native_static_libs(sess: &Session, all_native_libs: &[NativeLibrary
...
+            env::split_paths(&paths)
```
Comment (alexcrichton) [inline src/librustc_codegen_ssa/back/link.rs]: This might be best expressed as a `for` loop since we can simply return `Some` as soon as we find a match

File: src/librustc_codegen_ssa/back/link.rs [hunk 8]
```diff
@@ -968,7 +968,80 @@ pub fn print_native_static_libs(sess: &Session, all_native_libs: &[NativeLibrary
...
+        static ref SYSTEM_LIBS: Mutex<Option<Result<PathBuf, ()>>> = Mutex::new(None);
+    }
+
+    let system_libs = SYSTEM_LIBS.lock().unwrap().clone();
+    match system_libs {
+        Some(Ok(compiler_libs_path)) => Some(compiler_libs_path),
+        Some(Err(_)) => None,
+        _ => {
+            if let (linker, LinkerFlavor::Gcc) = linker_and_flavor(&sess) {
+                let linker_path = if cfg!(windows) { linker.with_extension("exe") } else { linker };
```
Comment (alexcrichton) [inline src/librustc_codegen_ssa/back/link.rs]: I'm not sure that the `with_extension` here may be right, since this could run the risk of, for example, overriding `*.bat` inputs or something like that? Is there perhaps a `"gcc"` strings elsewhere in the compiler which should instead be `gcc.exe`? Or could this `with_extension` get placed more closely to wherever the string `"gcc"` comes from?

File: src/librustc_codegen_ssa/back/link.rs [hunk 9]
```diff
@@ -968,7 +968,80 @@ pub fn print_native_static_libs(sess: &Session, all_native_libs: &[NativeLibrary
...
+                if let Some(linker_path) = find_exe_in_path(linker_path) {
+                    let mingw_arch = match &sess.target.target.arch {
+                        x if x == "x86" => "i686",
+                        x => x,
+                    };
+                    let mingw_dir = [mingw_arch, "-w64-mingw32"].concat();
```
Comment (alexcrichton) [inline src/librustc_codegen_ssa/back/link.rs]: I think it's probably more clear to use `format!("{}-...", mingw_arch)` here perhaps? (random stylistic nit)

File: src/librustc_codegen_ssa/back/link.rs [hunk 10]
```diff
@@ -968,7 +968,80 @@ pub fn print_native_static_libs(sess: &Session, all_native_libs: &[NativeLibrary
...
+                    // Here we have path/bin/gcc but we need path/
+                    let mut path = linker_path;
+                    path.pop();
+                    path.pop();
+                    // Based on Clang MinGW driver
+                    let probe_path = path.join([&mingw_dir, "lib"].concat());
```
Comment (alexcrichton) [inline src/librustc_codegen_ssa/back/link.rs]: The `.concat` here looks a little suspicious, could this be two different `.join` calls to be a bit more clear?

File: src/librustc_codegen_ssa/back/link.rs [hunk 11]
```diff
@@ -968,7 +968,80 @@ pub fn print_native_static_libs(sess: &Session, all_native_libs: &[NativeLibrary
...
+    lazy_static::lazy_static! {
+        static ref SYSTEM_LIBS: Mutex<Option<Result<PathBuf, ()>>> = Mutex::new(None);
+    }
+
+    let system_libs = SYSTEM_LIBS.lock().unwrap().clone();
+    match system_libs {
+        Some(Ok(compiler_libs_path)) => Some(compiler_libs_path),
+        Some(Err(_)) => None,
+        _ => {
+            if let (linker, LinkerFlavor::Gcc) = linker_and_flavor(&sess) {
```
Comment (alexcrichton) [inline src/librustc_codegen_ssa/back/link.rs]: Could the logic in this branch of the `match` be factored into its own function? Something like:

```
fn probe(sess: &Session) -> Option<PathBuf> { .. }
```

and that way this function would be a simple memoization of that `probe` function where we'd have `Mutex<Option<Option<PathBuf>>>` and if it's `None` we call `probe` and otherwise just clone/unwrap the result to return `Option<PathBuf>`

File: src/librustc_codegen_ssa/back/link.rs (hunk 8 above)
Comment (mati865) [reply src/librustc_codegen_ssa/back/link.rs]: It comes from https://github.com/rust-lang/rust/blob/67fae2241ba7d07f455754dcca2c90327b16c098/src/librustc_target/spec/windows_base.rs#L44 which is returned by `linker_and_flavor` without changes. Changing it to `gcc.exe` in the spec would be wrong for cross compilation.

Comment (alexcrichton) [reply src/librustc_codegen_ssa/back/link.rs]: That makes sense, yeah, but I think that we should only use `with_extension` in a way that doesn't override user inputs.

File: src/librustc_codegen_ssa/back/link.rs (hunk 9 above)
Comment (mati865) [reply src/librustc_codegen_ssa/back/link.rs]: Unnecessary micro-optimisation 🤷‍♂

File: src/librustc_codegen_ssa/back/link.rs (hunk 10 above)
Comment (mati865) [reply src/librustc_codegen_ssa/back/link.rs]: Another unnecessary micro-optimisation 🤷‍♂

**Comment by mati865** [comment]
Dist builds still fail for me (as described in https://github.com/rust-lang/rust/pull/67429#issuecomment-578955172) so I'll need @bors try to test if everything still works.

**Comment by mati865** [comment]
Seems to work well unless user adds linker wrapper to unusual place which is expected with this method.

You can inspect `crt2.o` paths as confirmation:

<details>
<summary>Ubuntu</summary>

```
 ~  rustc +3392cc9d0bc7b79899a7ea5713b07bef0b68ffea -Z print-link-args --target x86_64-pc-windows-gnu -C linker=x86_64-w64-mingw32-gcc hello.rs
"x86_64-w64-mingw32-gcc" "-fno-use-linker-plugin" "-Wl,--nxcompat" "-nostdlib" "-m64" "/usr/x86_64-w64-mingw32/lib/crt2.o" "/home/mateusz/.rustup/toolchains/3392cc9d0bc7b79899a7ea5713b07bef0b68ffea/lib/rustlib/x86_64-pc-windows-gnu/lib/rsbegin.o" "-L" "/usr/x86_64-w64-mingw32/lib" "-L" "/home/mateusz/.rustup/toolchains/3392cc9d0bc7b79899a7ea5713b07bef0b68ffea/lib/rustlib/x86_64-pc-windows-gnu/lib" "hello.hello.7rcbfp3g-cgu.0.rcgu.o" "hello.hello.7rcbfp3g-cgu.1.rcgu.o" "hello.hello.7rcbfp3g-cgu.2.rcgu.o" "hello.hello.7rcbfp3g-cgu.3.rcgu.o" "hello.hello.7rcbfp3g-cgu.4.rcgu.o" "hello.hello.7rcbfp3g-cgu.5.rcgu.o" "-o" "hello.exe" "hello.1nxjf9so94czdgcz.rcgu.o" "-Wl,--gc-sections" "-nodefaultlibs" "-L" "/home/mateusz/.rustup/toolchains/3392cc9d0bc7b79899a7ea5713b07bef0b68ffea/lib/rustlib/x86_64-pc-windows-gnu/lib" "-Wl,--start-group" "-Wl,-Bstatic" "/home/mateusz/.rustup/toolchains/3392cc9d0bc7b79899a7ea5713b07bef0b68ffea/lib/rustlib/x86_64-pc-windows-gnu/lib/libstd-6ca50196e8ddd38c.rlib" "/home/mateusz/.rustup/toolchains/3392cc9d0bc7b79899a7ea5713b07bef0b68ffea/lib/rustlib/x86_64-pc-windows-gnu/lib/libpanic_unwind-ce83b3f77c537672.rlib" "/home/mateusz/.rustup/toolchains/3392cc9d0bc7b79899a7ea5713b07bef0b68ffea/lib/rustlib/x86_64-pc-windows-gnu/lib/libhashbrown-d6a7a6013891a538.rlib" "/home/mateusz/.rustup/toolchains/3392cc9d0bc7b79899a7ea5713b07bef0b68ffea/lib/rustlib/x86_64-pc-windows-gnu/lib/librustc_std_workspace_alloc-af6e7625fcce7c4c.rlib" "/home/mateusz/.rustup/toolchains/3392cc9d0bc7b79899a7ea5713b07bef0b68ffea/lib/rustlib/x86_64-pc-windows-gnu/lib/libbacktrace-ca9e27a5cbfa379f.rlib" "/home/mateusz/.rustup/toolchains/3392cc9d0bc7b79899a7ea5713b07bef0b68ffea/lib/rustlib/x86_64-pc-windows-gnu/lib/libbacktrace_sys-604d7530c129703c.rlib" "/home/mateusz/.rustup/toolchains/3392cc9d0bc7b79899a7ea5713b07bef0b68ffea/lib/rustlib/x86_64-pc-windows-gnu/lib/librustc_demangle-9dd4ad358f3e17cc.rlib" "/home/mateusz/.rustup/toolchains/3392cc9d0bc7b79899a7ea5713b07bef0b68ffea/lib/rustlib/x86_64-pc-windows-gnu/lib/libunwind-47d352770f3c5346.rlib" "/home/mateusz/.rustup/toolchains/3392cc9d0bc7b79899a7ea5713b07bef0b68ffea/lib/rustlib/x86_64-pc-windows-gnu/lib/libcfg_if-7a41c2b92d503113.rlib" "/home/mateusz/.rustup/toolchains/3392cc9d0bc7b79899a7ea5713b07bef0b68ffea/lib/rustlib/x86_64-pc-windows-gnu/lib/liblibc-7401dde66f6d810c.rlib" "/home/mateusz/.rustup/toolchains/3392cc9d0bc7b79899a7ea5713b07bef0b68ffea/lib/rustlib/x86_64-pc-windows-gnu/lib/liballoc-450102315de833af.rlib" "/home/mateusz/.rustup/toolchains/3392cc9d0bc7b79899a7ea5713b07bef0b68ffea/lib/rustlib/x86_64-pc-windows-gnu/lib/librustc_std_workspace_core-2353d3567ed6c85e.rlib" "/home/mateusz/.rustup/toolchains/3392cc9d0bc7b79899a7ea5713b07bef0b68ffea/lib/rustlib/x86_64-pc-windows-gnu/lib/libcore-aaad085afadf73bf.rlib" "-Wl,--end-group" "/home/mateusz/.rustup/toolchains/3392cc9d0bc7b79899a7ea5713b07bef0b68ffea/lib/rustlib/x86_64-pc-windows-gnu/lib/libcompiler_builtins-bc5c4821b877b8d9.rlib" "-Wl,-Bdynamic" "-ladvapi32" "-lws2_32" "-luserenv" "-Wl,-Bstatic" "-lgcc_eh" "-lpthread" "-Wl,-Bdynamic" "-lmingwex" "-lmingw32" "-lgcc" "-lmsvcrt" "-lmsvcrt" "-luser32" "-lkernel32" "/home/mateusz/.rustup/toolchains/3392cc9d0bc7b79899a7ea5713b07bef0b68ffea/lib/rustlib/x86_64-pc-windows-gnu/lib/rsend.o"
```

</details>

<details>
<summary>MSYS2 GCC in PATH</summary>

```
$ rustc +3392cc9d0bc7b79899a7ea5713b07bef0b68ffea -Z print-link-args hello.rs
"gcc" "-fno-use-linker-plugin" "-Wl,--nxcompat" "-nostdlib" "-m64" "D:\\msys64\\mingw64\\x86_64-w64-mingw32\\lib\\crt2.o" "C:\\Users\\mateusz\\.rustup\\toolchains\\3392cc9d0bc7b79899a7ea5713b07bef0b68ffea\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\rsbegin.o" "-L" "D:\\msys64\\mingw64\\x86_64-w64-mingw32\\lib" "-L" "C:\\Users\\mateusz\\.rustup\\toolchains\\3392cc9d0bc7b79899a7ea5713b07bef0b68ffea\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib" "hello.hello.7rcbfp3g-cgu.0.rcgu.o" "hello.hello.7rcbfp3g-cgu.1.rcgu.o" "hello.hello.7rcbfp3g-cgu.2.rcgu.o" "hello.hello.7rcbfp3g-cgu.3.rcgu.o" "hello.hello.7rcbfp3g-cgu.4.rcgu.o" "hello.hello.7rcbfp3g-cgu.5.rcgu.o" "-o" "hello.exe" "hello.1nxjf9so94czdgcz.rcgu.o" "-Wl,--gc-sections" "-nodefaultlibs" "-L" "C:\\Users\\mateusz\\.rustup\\toolchains\\3392cc9d0bc7b79899a7ea5713b07bef0b68ffea\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib" "-Wl,--start-group" "-Wl,-Bstatic" "C:\\Users\\mateusz\\.rustup\\toolchains\\3392cc9d0bc7b79899a7ea5713b07bef0b68ffea\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\libstd-6ca50196e8ddd38c.rlib" "C:\\Users\\mateusz\\.rustup\\toolchains\\3392cc9d0bc7b79899a7ea5713b07bef0b68ffea\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\libpanic_unwind-ce83b3f77c537672.rlib" "C:\\Users\\mateusz\\.rustup\\toolchains\\3392cc9d0bc7b79899a7ea5713b07bef0b68ffea\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\libhashbrown-d6a7a6013891a538.rlib" "C:\\Users\\mateusz\\.rustup\\toolchains\\3392cc9d0bc7b79899a7ea5713b07bef0b68ffea\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\librustc_std_workspace_alloc-af6e7625fcce7c4c.rlib" "C:\\Users\\mateusz\\.rustup\\toolchains\\3392cc9d0bc7b79899a7ea5713b07bef0b68ffea\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\libbacktrace-ca9e27a5cbfa379f.rlib" "C:\\Users\\mateusz\\.rustup\\toolchains\\3392cc9d0bc7b79899a7ea5713b07bef0b68ffea\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\libbacktrace_sys-604d7530c129703c.rlib" "C:\\Users\\mateusz\\.rustup\\toolchains\\3392cc9d0bc7b79899a7ea5713b07bef0b68ffea\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\librustc_demangle-9dd4ad358f3e17cc.rlib" "C:\\Users\\mateusz\\.rustup\\toolchains\\3392cc9d0bc7b79899a7ea5713b07bef0b68ffea\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\libunwind-47d352770f3c5346.rlib" "C:\\Users\\mateusz\\.rustup\\toolchains\\3392cc9d0bc7b79899a7ea5713b07bef0b68ffea\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\libcfg_if-7a41c2b92d503113.rlib" "C:\\Users\\mateusz\\.rustup\\toolchains\\3392cc9d0bc7b79899a7ea5713b07bef0b68ffea\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\liblibc-7401dde66f6d810c.rlib" "C:\\Users\\mateusz\\.rustup\\toolchains\\3392cc9d0bc7b79899a7ea5713b07bef0b68ffea\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\liballoc-450102315de833af.rlib" "C:\\Users\\mateusz\\.rustup\\toolchains\\3392cc9d0bc7b79899a7ea5713b07bef0b68ffea\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\librustc_std_workspace_core-2353d3567ed6c85e.rlib" "C:\\Users\\mateusz\\.rustup\\toolchains\\3392cc9d0bc7b79899a7ea5713b07bef0b68ffea\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\libcore-aaad085afadf73bf.rlib" "-Wl,--end-group" "C:\\Users\\mateusz\\.rustup\\toolchains\\3392cc9d0bc7b79899a7ea5713b07bef0b68ffea\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\libcompiler_builtins-bc5c4821b877b8d9.rlib" "-Wl,-Bdynamic" "-ladvapi32" "-lws2_32" "-luserenv" "-Wl,-Bstatic" "-lgcc_eh" "-lpthread" "-Wl,-Bdynamic" "-lmingwex" "-lmingw32" "-lgcc" "-lmsvcrt" "-lmsvcrt" "-luser32" "-lkernel32" "C:\\Users\\mateusz\\.rustup\\toolchains\\3392cc9d0bc7b79899a7ea5713b07bef0b68ffea\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\rsend.o"
```

</details>

<details>
<summary>MSYS2 no GCC in PATH</summary>

```
$ rustc +3392cc9d0bc7b79899a7ea5713b07bef0b68ffea -Z print-link-args hello.rs
"gcc" "-fno-use-linker-plugin" "-Wl,--nxcompat" "-nostdlib" "-m64" "C:\\Users\\mateusz\\.rustup\\toolchains\\3392cc9d0bc7b79899a7ea5713b07bef0b68ffea\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\crt2.o" "C:\\Users\\mateusz\\.rustup\\toolchains\\3392cc9d0bc7b79899a7ea5713b07bef0b68ffea\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\rsbegin.o" "-L" "C:\\Users\\mateusz\\.rustup\\toolchains\\3392cc9d0bc7b79899a7ea5713b07bef0b68ffea\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib" "hello.hello.7rcbfp3g-cgu.0.rcgu.o" "hello.hello.7rcbfp3g-cgu.1.rcgu.o" "hello.hello.7rcbfp3g-cgu.2.rcgu.o" "hello.hello.7rcbfp3g-cgu.3.rcgu.o" "hello.hello.7rcbfp3g-cgu.4.rcgu.o" "hello.hello.7rcbfp3g-cgu.5.rcgu.o" "-o" "hello.exe" "hello.1nxjf9so94czdgcz.rcgu.o" "-Wl,--gc-sections" "-nodefaultlibs" "-L" "C:\\Users\\mateusz\\.rustup\\toolchains\\3392cc9d0bc7b79899a7ea5713b07bef0b68ffea\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib" "-Wl,--start-group" "-Wl,-Bstatic" "C:\\Users\\mateusz\\.rustup\\toolchains\\3392cc9d0bc7b79899a7ea5713b07bef0b68ffea\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\libstd-6ca50196e8ddd38c.rlib" "C:\\Users\\mateusz\\.rustup\\toolchains\\3392cc9d0bc7b79899a7ea5713b07bef0b68ffea\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\libpanic_unwind-ce83b3f77c537672.rlib" "C:\\Users\\mateusz\\.rustup\\toolchains\\3392cc9d0bc7b79899a7ea5713b07bef0b68ffea\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\libhashbrown-d6a7a6013891a538.rlib" "C:\\Users\\mateusz\\.rustup\\toolchains\\3392cc9d0bc7b79899a7ea5713b07bef0b68ffea\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\librustc_std_workspace_alloc-af6e7625fcce7c4c.rlib" "C:\\Users\\mateusz\\.rustup\\toolchains\\3392cc9d0bc7b79899a7ea5713b07bef0b68ffea\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\libbacktrace-ca9e27a5cbfa379f.rlib" "C:\\Users\\mateusz\\.rustup\\toolchains\\3392cc9d0bc7b79899a7ea5713b07bef0b68ffea\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\libbacktrace_sys-604d7530c129703c.rlib" "C:\\Users\\mateusz\\.rustup\\toolchains\\3392cc9d0bc7b79899a7ea5713b07bef0b68ffea\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\librustc_demangle-9dd4ad358f3e17cc.rlib" "C:\\Users\\mateusz\\.rustup\\toolchains\\3392cc9d0bc7b79899a7ea5713b07bef0b68ffea\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\libunwind-47d352770f3c5346.rlib" "C:\\Users\\mateusz\\.rustup\\toolchains\\3392cc9d0bc7b79899a7ea5713b07bef0b68ffea\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\libcfg_if-7a41c2b92d503113.rlib" "C:\\Users\\mateusz\\.rustup\\toolchains\\3392cc9d0bc7b79899a7ea5713b07bef0b68ffea\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\liblibc-7401dde66f6d810c.rlib" "C:\\Users\\mateusz\\.rustup\\toolchains\\3392cc9d0bc7b79899a7ea5713b07bef0b68ffea\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\liballoc-450102315de833af.rlib" "C:\\Users\\mateusz\\.rustup\\toolchains\\3392cc9d0bc7b79899a7ea5713b07bef0b68ffea\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\librustc_std_workspace_core-2353d3567ed6c85e.rlib" "C:\\Users\\mateusz\\.rustup\\toolchains\\3392cc9d0bc7b79899a7ea5713b07bef0b68ffea\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\libcore-aaad085afadf73bf.rlib" "-Wl,--end-group" "C:\\Users\\mateusz\\.rustup\\toolchains\\3392cc9d0bc7b79899a7ea5713b07bef0b68ffea\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\libcompiler_builtins-bc5c4821b877b8d9.rlib" "-Wl,-Bdynamic" "-ladvapi32" "-lws2_32" "-luserenv" "-Wl,-Bstatic" "-lgcc_eh" "-lpthread" "-Wl,-Bdynamic" "-lmingwex" "-lmingw32" "-lgcc" "-lmsvcrt" "-lmsvcrt" "-luser32" "-lkernel32" "C:\\Users\\mateusz\\.rustup\\toolchains\\3392cc9d0bc7b79899a7ea5713b07bef0b68ffea\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\rsend.o"
```

</details>

It just hit me https://github.com/rust-lang/rust/pull/67429/files#diff-9ca19d99192e8dfc0cb4f0b90eb82c46R1227-R1232 is almost certainly unnecessary for Linux. Pushed small change to disable it on non Windows platforms.

---

Once everyone is happy I'll squash commits and drop CI changes.

File: src/librustc_codegen_ssa/back/link.rs [hunk 12]
```diff
@@ -968,7 +968,81 @@ pub fn print_native_static_libs(sess: &Session, all_native_libs: &[NativeLibrary
     }
 }
 
+// Because windows-gnu target is meant to be self-contained for pure Rust code it bundles
+// own mingw-w64 libraries. These libraries are often not compatible with mingw-w64
+// installed in the system. This breaks many cases where Rust is mixed with other languages
+// (e.g. *-sys crates).
+// We prefer system mingw-w64 libraries if they are available to avoid this issue.
+fn get_crt_libs_path(sess: &Session) -> Option<PathBuf> {
```
Comment (alexcrichton) [inline src/librustc_codegen_ssa/back/link.rs]: Sorry probably should have commented on this earlier, but since `Session` is passed in here can `lazy_static` be avoided? This could presumably be some sort of `Cell` inside of `Session` to cache the value we're interested in

File: src/librustc_codegen_ssa/back/link.rs [hunk 13]
```diff
@@ -968,7 +968,81 @@ pub fn print_native_static_libs(sess: &Session, all_native_libs: &[NativeLibrary
...
+            if full_path.is_file() {
+                return Some(fix_windows_verbatim_for_gcc(&full_path));
+            }
+        }
+        None
+    }
+
+    fn probe(sess: &Session) -> Option<PathBuf> {
+        if let (linker, LinkerFlavor::Gcc) = linker_and_flavor(&sess) {
+            let linker_path = if cfg!(windows) && !linker.extension().is_some() {
```
Comment (alexcrichton) [inline src/librustc_codegen_ssa/back/link.rs]: Could `!foo.is_some()` be changed to `foo.is_none()`?

File: src/librustc_codegen_ssa/back/link.rs [hunk 14]
```diff
@@ -1150,6 +1224,12 @@ fn link_args<'a, B: ArchiveBuilder<'a>>(
     // target descriptor
     let t = &sess.target.target;
 
+    if cfg!(windows) && sess.target.target.llvm_target.contains("windows-gnu") {
```
Comment (alexcrichton) [inline src/librustc_codegen_ssa/back/link.rs]: Could this `if` have some comments as to what it's doing?

File: src/librustc_codegen_ssa/back/link.rs [hunk 15]
```diff
@@ -968,7 +968,81 @@ pub fn print_native_static_libs(sess: &Session, all_native_libs: &[NativeLibrary
...
+    let system_libs = SYSTEM_LIBS.lock().unwrap().clone();
+    match system_libs {
+        Some(Some(compiler_libs_path)) => Some(compiler_libs_path),
+        Some(None) => None,
+        None => probe(sess),
+    }
+}
+
 pub fn get_file_path(sess: &Session, name: &str) -> PathBuf {
+    if sess.target.target.llvm_target.contains("windows-gnu") {
```
Comment (alexcrichton) [inline src/librustc_codegen_ssa/back/link.rs]: Could this `if` have some comments as to what it's doing?

**Comment by mati865** [comment]
Not sure how threading inside rustc works (and whether I should wrap it in `OneThread`) but tested locally Windows build and it works fine with default config (non parallel).

File: src/librustc_codegen_ssa/back/link.rs [hunk 16]
```diff
@@ -968,7 +968,77 @@ pub fn print_native_static_libs(sess: &Session, all_native_libs: &[NativeLibrary
...
+                    return Some(probe_path);
+                };
+                let probe_path = path.join(&mingw_dir).join("sys-root/mingw/lib");
+                if probe_path.exists() {
+                    *system_library_path = Some(Some(probe_path.clone()));
+                    return Some(probe_path);
+                };
+            };
+        };
+        *system_library_path = Some(None);
```
Comment (alexcrichton) [inline src/librustc_codegen_ssa/back/link.rs]: As one final comment, I think this store of the return value should happen outside of the `probe` function so we don't have to remember to set it on every control flow path within the function.

**Comment by alexcrichton** [comment]
Thanks for the changes! I don't know about the `OneThread` thing here, but if it works we can always fix it later with parallel rustc if necessary.

r=me with the last nit applied and the CI changes rolled back.

**Comment by mati865** [comment]
Judging by https://github.com/rust-lang/rust/pull/67429#issuecomment-581149320 `OneThread` seems necessary.

I haven't tested last changes but they should be straightforward enough: https://github.com/rust-lang/rust/compare/785018c4be5229a9f5db62bafec24ef9be60a779..1fad337f79a6a554ae947def38ec2db0e91d864c

**Comment by tanriol** [comment]
What's the proper way to make this work for systems that do not match this pattern? For example, on my Gentoo Linux system the cross-compiler `/usr/bin/x86_64-w64-mingw32-gcc` is a symlink to `/usr/x86_64-pc-linux-gnu/x86_64-w64-mingw32/gcc-bin/9.2.0/x86_64-w64-mingw32-gcc`, while the mingw libs live at `/usr/x86_64-w64-mingw32/usr/lib/`.

**Comment by mati865** [comment]
@tanriol that's good question.
I don't think it's neither possible or good idea to cover all possible variants.
Maybe it'd be possible to reuse one of [Cargo configuration](https://doc.rust-lang.org/cargo/reference/config.html) fields or add new one.
Could you open new issue to track this?
