### PR TITLE
Use weak_odr linkage when reusing definitions across codegen units

### LINKED ISSUE #32518: multiple definition link error when using multiple codegen units
I wanted to use @dotdash's LLVM assertions patch but now my stage1 libstd fails to link. Probably unrelated but here it is:

 ```go
rustc: arm-unknown-linux-gnueabihf/stage1/lib/rustlib/arm-unknown-linux-gnueabihf/lib/libstd
error: linking with `cc` failed: exit code: 1
note: "cc" "-Wl,--as-needed" "-Wl,-z,noexecstack" "-L" "/rust-master/arm-unknown-linux-gnueabihf/stage1/lib/rustlib/arm-unknown-linux-gnueabihf/lib" "arm-unknown-linux-gnueabihf/stage1/lib/rustlib/arm-unknown-linux-gnueabihf/lib/std-9026086f.0.o" "arm-unknown-linux-gnueabihf/stage1/lib/rustlib/arm-unknown-linux-gnueabihf/lib/std-9026086f.1.o" "arm-unknown-linux-gnueabihf/stage1/lib/rustlib/arm-unknown-linux-gnueabihf/lib/std-9026086f.2.o" "arm-unknown-linux-gnueabihf/stage1/lib/rustlib/arm-unknown-linux-gnueabihf/lib/std-9026086f.3.o" "-o" "arm-unknown-linux-gnueabihf/stage1/lib/rustlib/arm-unknown-linux-gnueabihf/lib/libstd-9026086f.so" "arm-unknown-linux-gnueabihf/stage1/lib/rustlib/arm-unknown-linux-gnueabihf/lib/std-9026086f.metadata.o" "-Wl,-O1" "-nodefaultlibs" "-L" "arm-unknown-linux-gnueabihf/rt" "-L" "/rust-master/arm-unknown-linux-gnueabihf/llvm/Release+Asserts/lib" "-L" "/rust-master/arm-unknown-linux-gnueabihf/stage1/lib/rustlib/arm-unknown-linux-gnueabihf/lib" "-Wl,-Bstatic" "-Wl,--whole-archive" "-l" "backtrace" "-Wl,--no-whole-archive" "-Wl,-Bdynamic" "-l" "dl" "-l" "pthread" "-l" "gcc_s" "-Wl,--whole-archive" "/tmp/rustc.FHfUQVlQsuoG/libcollections-9026086f.rlib" "-Wl,--no-whole-archive" "-Wl,--whole-archive" "/tmp/rustc.FHfUQVlQsuoG/liballoc-9026086f.rlib" "-Wl,--no-whole-archive" "-Wl,--whole-archive" "/tmp/rustc.FHfUQVlQsuoG/librustc_unicode-9026086f.rlib" "-Wl,--no-whole-archive" "-Wl,--whole-archive" "/tmp/rustc.FHfUQVlQsuoG/liballoc_system-9026086f.rlib" "-Wl,--no-whole-archive" "-Wl,--whole-archive" "/tmp/rustc.FHfUQVlQsuoG/liblibc-9026086f.rlib" "-Wl,--no-whole-archive" "-Wl,--whole-archive" "/tmp/rustc.FHfUQVlQsuoG/librand-9026086f.rlib" "-Wl,--no-whole-archive" "-Wl,--whole-archive" "/tmp/rustc.FHfUQVlQsuoG/libcore-9026086f.rlib" "-Wl,--no-whole-archive" "-l" "c" "-l" "m" "-l" "rt" "-shared" "-Wl,-rpath,/home/odroid/rust-nightly-sysalloc-assert/lib/rustlib/arm-unknown-linux-gnueabihf/lib" "-Wl,--enable-new-dtags" "-s" "-l" "compiler-rt"
````
```shell
note: /tmp/rustc.FHfUQVlQsuoG/libcollections-9026086f.rlib(collections-9026086f.0.o): In function `_$LT$core..option..Option$LT$T$GT$$GT$::map::h58518f67af9bf04e':
collections.0.rs:(.text._ZN38_$LT$core..option..Option$LT$T$GT$$GT$3map17h58518f67af9bf04eE+0x0): multiple definition of `_$LT$core..option..Option$LT$T$GT$$GT$::map::h58518f67af9bf04e'
arm-unknown-linux-gnueabihf/stage1/lib/rustlib/arm-unknown-linux-gnueabihf/lib/std-9026086f.0.o:std.0.rs:(.text._ZN38_$LT$core..option..Option$LT$T$GT$$GT$3map17h58518f67af9bf04eE+0x0): first defined here
/tmp/rustc.FHfUQVlQsuoG/libcollections-9026086f.rlib(collections-9026086f.0.o): In function `_$LT$alloc..raw_vec..RawVec$LT$T$GT$$GT$::new::h0c1cdac7fb2b416c':
collections.0.rs:(.text._ZN40_$LT$alloc..raw_vec..RawVec$LT$T$GT$$GT$3new17h0c1cdac7fb2b416cE+0x0): multiple definition of `_$LT$alloc..raw_vec..RawVec$LT$T$GT$$GT$::new::h0c1cdac7fb2b416c'
arm-unknown-linux-gnueabihf/stage1/lib/rustlib/arm-unknown-linux-gnueabihf/lib/std-9026086f.3.o:std.3.rs:(.text._ZN40_$LT$alloc..raw_vec..RawVec$LT$T$GT$$GT$3new17h0c1cdac7fb2b416cE+0x0): first defined here
/tmp/rustc.FHfUQVlQsuoG/libcollections-9026086f.rlib(collections-9026086f.0.o): In function `_$LT$alloc..raw_vec..RawVec$LT$T$GT$$GT$::ptr::h4e14ee1392d1411e':
collections.0.rs:(.text._ZN40_$LT$alloc..raw_vec..RawVec$LT$T$GT$$GT$3ptr17h4e14ee1392d1411eE+0x0): multiple definition of `_$LT$alloc..raw_vec..RawVec$LT$T$GT$$GT$::ptr::h4e14ee1392d1411e'
arm-unknown-linux-gnueabihf/stage1/lib/rustlib/arm-unknown-linux-gnueabihf/lib/std-9026086f.0.o:std.0.rs:(.text._ZN40_$LT$alloc..raw_vec..RawVec$LT$T$GT$$GT$3ptr17h4e14ee1392d1411eE+0x0): first defined here
/tmp/rustc.FHfUQVlQsuoG/libcollections-9026086f.rlib(collections-9026086f.0.o): In function `_$LT$alloc..raw_vec..RawVec$LT$T$GT$$GT$::double::heaf5b97a8495eb9e':
collections.0.rs:(.text._ZN40_$LT$alloc..raw_vec..RawVec$LT$T$GT$$GT$6double17heaf5b97a8495eb9eE+0x0): multiple definition of `_$LT$alloc..raw_vec..RawVec$LT$T$GT$$GT$::double::heaf5b97a8495eb9e'
arm-unknown-linux-gnueabihf/stage1/lib/rustlib/arm-unknown-linux-gnueabihf/lib/std-9026086f.3.o:std.3.rs:(.text._ZN40_$LT$alloc..raw_vec..RawVec$LT$T$GT$$GT$6double17heaf5b97a8495eb9eE+0x0): first defined here
/tmp/rustc.FHfUQVlQsuoG/libcollections-9026086f.rlib(collections-9026086f.0.o): In function `core::mem::uninitialized::he8ba150ad18eedcf':
collections.0.rs:(.text._ZN4core3mem13uninitialized17he8ba150ad18eedcfE+0x0): multiple definition of `core::mem::uninitialized::he8ba150ad18eedcf'
arm-unknown-linux-gnueabihf/stage1/lib/rustlib/arm-unknown-linux-gnueabihf/lib/std-9026086f.0.o:std.0.rs:(.text._ZN4core3mem13uninitialized17he8ba150ad18eedcfE+0x0): first defined here
/tmp/rustc.FHfUQVlQsuoG/libcollections-9026086f.rlib(collections-9026086f.0.o): In function `core::mem::uninitialized::hfa1a47f766d26f10':
collections.0.rs:(.text._ZN4core3mem13uninitialized17hfa1a47f766d26f10E+0x0): multiple definition of `core::mem::uninitialized::hfa1a47f766d26f10'
arm-unknown-linux-gnueabihf/stage1/lib/rustlib/arm-unknown-linux-gnueabihf/lib/std-9026086f.3.o:std.3.rs:(.text._ZN4core3mem13uninitialized17hfa1a47f766d26f10E+0x0): first defined here
/tmp/rustc.FHfUQVlQsuoG/libcollections-9026086f.rlib(collections-9026086f.0.o): In function `core::mem::transmute_copy::h5f22bd4094d00101':
collections.0.rs:(.text._ZN4core3mem14transmute_copy17h5f22bd4094d00101E+0x0): multiple definition of `core::mem::transmute_copy::h5f22bd4094d00101'
arm-unknown-linux-gnueabihf/stage1/lib/rustlib/arm-unknown-linux-gnueabihf/lib/std-9026086f.0.o:std.0.rs:(.text._ZN4core3mem14transmute_copy17h5f22bd4094d00101E+0x0): first defined here
/tmp/rustc.FHfUQVlQsuoG/libcollections-9026086f.rlib(collections-9026086f.0.o): In function `core::mem::transmute_copy::h75f84324b8ee3166':
collections.0.rs:(.text._ZN4core3mem14transmute_copy17h75f84324b8ee3166E+0x0): multiple definition of `core::mem::transmute_copy::h75f84324b8ee3166'
arm-unknown-linux-gnueabihf/stage1/lib/rustlib/arm-unknown-linux-gnueabihf/lib/std-9026086f.3.o:std.3.rs:(.text._ZN4core3mem14transmute_copy17h75f84324b8ee3166E+0x0): first defined here
/tmp/rustc.FHfUQVlQsuoG/libcollections-9026086f.rlib(collections-9026086f.0.o): In function `core::mem::forget::h502109c553961f51':
collections.0.rs:(.text._ZN4core3mem6forget17h502109c553961f51E+0x0): multiple definition of `core::mem::forget::h502109c553961f51'
arm-unknown-linux-gnueabihf/stage1/lib/rustlib/arm-unknown-linux-gnueabihf/lib/std-9026086f.0.o:std.0.rs:(.text._ZN4core3mem6forget17h502109c553961f51E+0x0): first defined here
/tmp/rustc.FHfUQVlQsuoG/libcollections-9026086f.rlib(collections-9026086f.0.o): In function `core::mem::size_of::hfb509be3c362d215':
collections.0.rs:(.text._ZN4core3mem7size_of17hfb509be3c362d215E+0x0): multiple definition of `core::mem::size_of::hfb509be3c362d215'
arm-unknown-linux-gnueabihf/stage1/lib/rustlib/arm-unknown-linux-gnueabihf/lib/std-9026086f.0.o:std.0.rs:(.text._ZN4core3mem7size_of17hfb509be3c362d215E+0x0): first defined here
/tmp/rustc.FHfUQVlQsuoG/libcollections-9026086f.rlib(collections-9026086f.0.o): In function `core::mem::align_of::h2a452ce69533a17c':
collections.0.rs:(.text._ZN4core3mem8align_of17h2a452ce69533a17cE+0x0): multiple definition of `core::mem::align_of::h2a452ce69533a17c'
arm-unknown-linux-gnueabihf/stage1/lib/rustlib/arm-unknown-linux-gnueabihf/lib/std-9026086f.0.o:std.0.rs:(.text._ZN4core3mem8align_of17h2a452ce69533a17cE+0x0): first defined here
/tmp/rustc.FHfUQVlQsuoG/libcollections-9026086f.rlib(collections-9026086f.0.o): In function `core::ptr::_$LT$impl$u20$$BP$mut$u20$T$GT$::is_null::h3fe8e4e4a8815d84':
collections.0.rs:(.text._ZN4core3ptr31_$LT$impl$u20$$BP$mut$u20$T$GT$7is_null17h3fe8e4e4a8815d84E+0x0): multiple definition of `core::ptr::_$LT$impl$u20$$BP$mut$u20$T$GT$::is_null::h3fe8e4e4a8815d84'
arm-unknown-linux-gnueabihf/stage1/lib/rustlib/arm-unknown-linux-gnueabihf/lib/std-9026086f.0.o:std.0.rs:(.text._ZN4core3ptr31_$LT$impl$u20$$BP$mut$u20$T$GT$7is_null17h3fe8e4e4a8815d84E+0x0): first defined here
/tmp/rustc.FHfUQVlQsuoG/libcollections-9026086f.rlib(collections-9026086f.0.o): In function `core::ptr::_$LT$impl$u20$$BP$const$u20$T$GT$::offset::he051aa5e5b8f8bfb':
collections.0.rs:(.text._ZN4core3ptr33_$LT$impl$u20$$BP$const$u20$T$GT$6offset17he051aa5e5b8f8bfbE+0x0): multiple definition of `core::ptr::_$LT$impl$u20$$BP$const$u20$T$GT$::offset::he051aa5e5b8f8bfb'
arm-unknown-linux-gnueabihf/stage1/lib/rustlib/arm-unknown-linux-gnueabihf/lib/std-9026086f.0.o:std.0.rs:(.text._ZN4core3ptr33_$LT$impl$u20$$BP$const$u20$T$GT$6offset17he051aa5e5b8f8bfbE+0x0): first defined here
/tmp/rustc.FHfUQVlQsuoG/libcollections-9026086f.rlib(collections-9026086f.0.o): In function `core::ptr::_$LT$impl$u20$$BP$const$u20$T$GT$::is_null::h630d425861f40502':
collections.0.rs:(.text._ZN4core3ptr33_$LT$impl$u20$$BP$const$u20$T$GT$7is_null17h630d425861f40502E+0x0): multiple definition of `core::ptr::_$LT$impl$u20$$BP$const$u20$T$GT$::is_null::h630d425861f40502'
````

and so on. Configured with `--enable-optimize --disable-jemalloc --enable-llvm-assertions` and `RUSTFLAGS='-C codegen-units=4 -C link-args=-s'`

Are all these errors about memory management  functions? (`--disable-jemalloc` broken again?)

### PR DESCRIPTION
**Pull request by dotdash**
When reuing a definition across codegen units, we obviously cannot use
internal linkage, but using external linkage means that we can end up
with multiple conflicting definitions of a single symbol across
multiple crates. Since the definitions should all be equal
semantically, we can use weak_odr linkage to resolve the situation.

Fixes #32518

r? @nikomatsakis

### CODE REVIEW

File: src/librustc_trans/monomorphize.rs [hunk 1]
```diff
@@ -139,6 +139,8 @@ pub fn monomorphic_fn<'a, 'tcx>(ccx: &CrateContext<'a, 'tcx>,
 
             if trans_everywhere || is_first {
                 trans_fn(ccx, decl, body, lldecl, psubsts, fn_node_id);
+            } else {
+                llvm::SetLinkage(lldecl, llvm::ExternalLinkage);
```
Comment (nikomatsakis) [inline src/librustc_trans/monomorphize.rs]: as we said on IRC, this is subtle -- comment would be good

**Comment by nikomatsakis** [comment]
r=me w/ comment

**Comment by nikomatsakis** [comment]
can't really see what travis is complaing about; looks spurious

**Comment by michaelwoerister** [comment]
The LLVM document says
>  Unreferenced linkonce globals are allowed to be discarded. 

Could that be the problem for these `undefined reference` errors?

**Comment by michaelwoerister** [comment]
`weak_odr` linkage might be a better fit then...

**Comment by dotdash** [comment]
No, it's probably just that linkonce_odr must only be used for things that are actually translated in every crate, not everything. IOW update_linkage was the wrong place to do this.

**Comment by michaelwoerister** [comment]
[base::internalize_symbols](https://dxr.mozilla.org/rust/rev/a5d1e7a59a2a3413c377b003075349f854304b5e/src/librustc_trans/trans/base.rs#2937) might also be something to look at.

**Comment by dotdash** [comment]
Actually, you're right about using weak_odr. The whole point is that with codegen units, we're not even translating generics in every unit. D'oh!

And I should adjust `base::internalize_symbols` as well. I already had that and thought I had undone it for a reason, but I can't think of anything, so probably an accident.

**Comment by nikomatsakis** [comment]
@bors r-

per conversation on IRC, this should have some sort of comment, since the boolean logic is pretty subtle, and the meaning of these flags not 100% obvious

**Comment by nikomatsakis** [comment]
much better :)

**Comment by alexcrichton** [comment]
Hm I wonder if the weak odr linkage isn't supported on all platforms? It sounds like something that'd be Linux only unfortunately :(

**Comment by dotdash** [comment]
weak_odr linkage is used in `MicrosoftCXXABI.cpp` in Clang, so I assume that it's supported. Maybe we're missing something else...

**Comment by dotdash** [comment]
Turns out that you need to use comdat sections to make this work.

http://www.airs.com/blog/archives/52 has some details.

**Comment by michaelwoerister** [comment]
From the LLVM documentation on comdat sections:
> Note that the Mach-O platform doesn’t support COMDATs

Do you know how this affects us? How do they do C++ templates there?

**Comment by dotdash** [comment]
@michaelwoerister The check in the SetComdat function takes care not to set comdat for Mach-O. Weak/Linkonce_ODR + Comdat is what Clang does. I suppose that weak_odr already does the trick for Mach-O as it does for ELF.

File: src/librustc_llvm/lib.rs [hunk 2]
```diff
@@ -2149,6 +2151,12 @@ pub fn SetLinkage(global: ValueRef, link: Linkage) {
     }
 }
 
+pub fn SetUniqueComdat(llmod: ModuleRef, val: ValueRef) {
+    unsafe {
+        LLVMRustSetComdat(llmod, val, LLVMGetValueName(val));
```
Comment (nikomatsakis) [inline src/librustc_llvm/lib.rs]: this function needs a comment; at minimum, it should link to that blog post, but also: why does it make sense to use `LLVMGetValueName` here? 

I would expect the string to be the symbol name or something similar -- does that happen to be what `LLVMGetValueName` is returning here?

Comment (dotdash) [inline src/librustc_llvm/lib.rs]: Yes, the returned string is the name of the function.

**Comment by michaelwoerister** [comment]
@dotdash OK, sounds good then!

**Comment by alexcrichton** [comment]
Nice find! I've always wondered what comdats are...

**Comment by michaelwoerister** [comment]
:sparkling_heart:

**Comment by nikomatsakis** [comment]
@dotdash you suggested on IRC that there may still be further problems in this area -- any update on that?

**Comment by dotdash** [comment]
I think that was just about not unsetting the comdat section when
internalizing after trans has finished.

I didn't notify about the fix for that on IRC, but it's on the merged
commit.
Am 30.03.2016 00:40 schrieb "Niko Matsakis" <notifications@github.com>:

**Comment by brson** [comment]
In my previous experiments weak_odr functions didn't optimize as well as internal functions so this may be a perf regression.
