### PR TITLE
Fix injected errors when running doctests on a crate named after a keyword

### LINKED ISSUE #79771: Rustdoc creates doctests with `extern crate mod;`
In #79770 I tried to create a new `rustdoc-ui` testcase that runs doctests. However having the `mod` substring in a doctest comment injected an invalid `extern crate mod;` into the code generated for the doctest.

Turns out this here is a bit too aggressive:

https://github.com/rust-lang/rust/blob/0f6f2d681b39c5f95459cd09cb936b6ceb27cd82/src/librustdoc/doctest.rs#L533-L534

It looks like compiletest actually gave the crate the name `mod`, perhaps because it was defined in a `issue-XXX/mod.rs` file, and having a doctest such as this triggers the this auto-injection, resulting in a failed doctest run:

````rust
/// ```
/// // ^ mod.rs line 10
/// assert_eq!(1, 1);
/// ```
````

### PR DESCRIPTION
**Pull request by jyn514**
Closes https://github.com/rust-lang/rust/issues/79771

### CODE REVIEW

File: src/test/rustdoc/doctest-keyword.rs [hunk 1]
```diff
@@ -0,0 +1,6 @@
+#![crate_name = "mod"]
+//! ```
+//! // NOTE: requires that the literal string 'mod' appears in the doctest for
+//! // the bug to appear
+//! assert_eq!(1, 1);
+//! ```
```
Comment (jyn514) [inline src/test/rustdoc/doctest-keyword.rs:6]: I don't know how to test this. Currently the test does nothing because it isn't running rustdoc with `--test`; if I add `// compile-flags: --test` it errors regardless of the fix because the aux metadata isn't built:

```
running 1 test
test src/test/rustdoc/doctest-keyword.rs - (line 3) ... FAILED

failures:

---- src/test/rustdoc/doctest-keyword.rs - (line 3) stdout ----
error[E0463]: can't find crate for `mod`
 --> src/test/rustdoc/doctest-keyword.rs:4:1
  |
4 | extern crate r#mod;
  | ^^^^^^^^^^^^^^^^^^^ can't find crate
```

I can't seem to find any other tests for this? @GuillaumeGomez do you have ideas?

File: src/librustdoc/doctest.rs [hunk 2]
```diff
@@ -531,7 +531,7 @@ crate fn make_test(
         if let Some(cratename) = cratename {
             // Make sure its actually used if not included.
```
Comment (camelid) [inline src/librustdoc/doctest.rs:532]: I know this was pre-existing, but while you're at it do you want to fix this?

```suggestion
            // Make sure it's actually used if not included.
```

Comment (camelid) [reply src/librustdoc/doctest.rs:532]: Also, I'm not quite sure what this comment means.

File: src/test/rustdoc/doctest-keyword.rs (hunk 1 above)
Comment (GuillaumeGomez) [reply src/test/rustdoc/doctest-keyword.rs:6]: You can use `aux-build` to achieve that I think, no?

Comment (jyn514) [reply src/test/rustdoc/doctest-keyword.rs:6]: Hmm, I'm not sure how. Normally `aux-build` looks in the `auxiliary` directory, so I tried using `// aux-build:../doctest-keyword.rs` to trick it into building the current file. But it still seems to be breaking :/

<details>

```
running 6 tests
iiiiiF
failures:

---- [rustdoc] rustdoc/doctest-keyword.rs stdout ----


executing "/home/joshua/rustc/build/x86_64-unknown-linux-gnu/stage1/bin/rustc" "/home/joshua/rustc/src/test/rustdoc/auxiliary/../doctest-keyword.rs" "-Zthreads=1" "--target=x86_64-unknown-linux-gnu" "-C" "prefer-dynamic" "--out-dir" "/home/joshua/rustc/build/x86_64-unknown-linux-gnu/test/rustdoc/doctest-keyword/auxiliary" "-Crpath" "-O" "-Cdebuginfo=0" "-Zunstable-options" "-Lnative=/home/joshua/rustc/build/x86_64-unknown-linux-gnu/native/rust-test-helpers" "--test" "--crate-type" "dylib" "-L" "/home/joshua/rustc/build/x86_64-unknown-linux-gnu/test/rustdoc/doctest-keyword/auxiliary"
------stdout------------------------------

------stderr------------------------------

------------------------------------------
executing "/home/joshua/rustc/build/x86_64-unknown-linux-gnu/stage1/bin/rustdoc" "-L" "/home/joshua/rustc/build/x86_64-unknown-linux-gnu/stage1/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-L" "/home/joshua/rustc/build/x86_64-unknown-linux-gnu/test/rustdoc/doctest-keyword/auxiliary" "-o" "/home/joshua/rustc/build/x86_64-unknown-linux-gnu/test/rustdoc/doctest-keyword" "/home/joshua/rustc/src/test/rustdoc/doctest-keyword.rs" "--test"
------stdout------------------------------

running 1 test
test src/test/rustdoc/doctest-keyword.rs - (line 7) ... FAILED

failures:

---- src/test/rustdoc/doctest-keyword.rs - (line 7) stdout ----
error[E0463]: can't find crate for `mod`
 --> src/test/rustdoc/doctest-keyword.rs:8:1
  |
4 | extern crate r#mod;
  | ^^^^^^^^^^^^^^^^^^^ can't find crate

error: aborting due to previous error

For more information about this error, try `rustc --explain E0463`.
Couldn't compile the test.

failures:
    src/test/rustdoc/doctest-keyword.rs - (line 7)

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.02s
```

</details>

I did confirm that the aux file exists, but it doesn't seem to be picking up on it for some reason.

```
$ file /home/joshua/rustc/build/x86_64-unknown-linux-gnu/test/rustdoc/doctest-keyword/auxiliary/mod
/home/joshua/rustc/build/x86_64-unknown-linux-gnu/test/rustdoc/doctest-keyword/auxiliary/mod: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 3.2.0, BuildID[sha1]=df3038c014cbf237c458cb19f7571c62aa8b96f9, not stripped
```

@Mark-Simulacrum do you have ideas maybe?

Comment (GuillaumeGomez) [reply src/test/rustdoc/doctest-keyword.rs]: The problem here might coming from the `.rs` file generated by rustdoc containing the test, no?

File: src/librustdoc/doctest.rs (hunk 2 above)
Comment (jyn514) [reply src/librustdoc/doctest.rs]: Does https://github.com/rust-lang/rust/pull/79775/commits/a7c197d773dd18affb2443e0ace5c2b9c7b0a44c help?

Comment (camelid) [reply src/librustdoc/doctest.rs]: Yes, thanks!

File: src/test/rustdoc/doctest-keyword.rs (hunk 1 above)
Comment (jyn514) [reply src/test/rustdoc/doctest-keyword.rs]: I think it's unlikely this will regress, since someone would have to change it intentionally. Do you think it makes sense to add the fix before figuring out how to test it?

**Comment by jyn514** [comment]
@JohnCSimon this is waiting on review, not me.

ping @GuillaumeGomez do you have ideas for how to test this? If not, are you ok with merging the fix even without tests?

**Comment by GuillaumeGomez** [comment]
This isn't a bug with high priority, so I'd prefer to add the test alongside it if possible. We can take a look together if the aux-build isn't working for you if you want?

**Comment by jyn514** [comment]
If you can take a look, I'd appreciate it. I don't know how to do this.

**Comment by GuillaumeGomez** [comment]
Sure! Taking a look then. ;)

**Comment by GuillaumeGomez** [comment]
Ok, so the problem here with the test is that we need the file to be compiled first to then be used as dependency, which cannot be done currently unfortunately in the rustdoc test suites... Example:

```rust
// name this file "foo.rs"

/// ```
/// let x = foo::foo();
/// ```
pub fn foo() {}
```

If you run `rustdoc --test foo.rs`, you'll get:

```
running 1 test
test foo.rs - foo (line 1) ... FAILED

failures:

---- foo.rs - foo (line 1) stdout ----
error[E0463]: can't find crate for `foo`
 --> foo.rs:0:1
  |
2 | extern crate foo;
  | ^^^^^^^^^^^^^^^^^ can't find crate
```

We need `foo` to be compiled so that it can be used as a dependency by rustdoc, which is currently not possible in any of the rustdoc test suites. So unfortunately, I don't see any easy way to test it...

So if you're fine with it @jyn514, please just remove the test and we'll r+ it.

**Review by GuillaumeGomez — APPROVED** [review]

**Comment by GuillaumeGomez** [comment]
Thanks! r=me once CI is green.

**Comment by jyn514** [comment]
Oh, well, after all that it turns out it gets tested anyway because we hard-code the generated code in a test lol

**Comment by GuillaumeGomez** [comment]
Nice surprise haha!

**Comment by GuillaumeGomez** [comment]
Seems like it's ready to go. Thanks!

@bors: r+
