### PR TITLE
Make debug_triple depend on target json file content rather than file path

### LINKED ISSUE #792: Out-of-tree module failed to build if the kernel source path is different
As most of the Linux distribution install the kernel with their package (.deb, .rpm, ...). I also tried to do the same thing to test Linux kernel with Rust support. However, when I build some out-of-tree Rust kernel module, it failed to compile with the following message:
```
error[E0461]: couldn't find crate `core` with expected target triple target-13637732820183936185
  |
  = note: the following crate versions were found:
          crate `core`, target triple target-4719486650351723570: /usr/src/linux-headers-5.18.0-rc2-2-rust/rust/libcore.rmeta

error[E0461]: couldn't find crate `compiler_builtins` with expected target triple target-13637732820183936185
  |
  = note: the following crate versions were found:
          crate `compiler_builtins`, target triple target-4719486650351723570: /usr/src/linux-headers-5.18.0-rc2-2-rust/rust/libcompiler_builtins
.rmeta

error[E0461]: couldn't find crate `kernel` with expected target triple target-13637732820183936185
  --> /home/leo/rust-kernel-modules/rust-random/rust_random.rs:11:5
   |
11 | use kernel::{
   |     ^^^^^^
   |
   = note: the following crate versions were found:
           crate `kernel`, target triple target-4719486650351723570: /usr/src/linux-headers-5.18.0-rc2-2-rust/rust/libkernel.rmeta
```

After digging some codes, I found that rustc record the target triple as the path of target.json file.
https://doc.rust-lang.org/stable/nightly-rustc/rustc_target/spec/enum.TargetTriple.html

And the target triple appears in the error messages can be calculated with the following codes:
```rust
use std::collections::hash_map::DefaultHasher;
use std::hash::{Hash, Hasher};
use std::path::PathBuf;

#[allow(unused_variables)]
fn main() {
    let mut hasher = DefaultHasher::new();
    // target-4719486650351723570
    let path = PathBuf::from("/home/leo/linux-rust/src/build/rust/target.json");
    // target-13637732820183936185
    let path = PathBuf::from("/usr/src/linux-headers-5.18.0-rc2-2-rust/rust/target.json");
    path.hash(&mut hasher);
    let hash = hasher.finish();
    println!("target-{}", hash)
}
```
https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=aa52d204a7d4167cfd84076776ab957a

The above codes is reference from [rust-lang/rust/compiler/rustc_target/src/spec/mod.rs:2445](https://github.com/rust-lang/rust/blob/4f372b14dea58cbff1dd76bb651f9c035d3f6e7b/compiler/rustc_target/src/spec/mod.rs#L2445)

P.s. I think that this is the problem of the compiler, however, this issue must be resolved if we want to support out-of-tree Rust kernel module in the future.

### PR DESCRIPTION
**Pull request by bjorn3**
This ensures that changes to target json files will force a recompilation. And more importantly that moving the files doesn't force a recompilation.

This should fix https://github.com/Rust-for-Linux/linux/issues/792 (cc @ojeda)

### CODE REVIEW

File: compiler/rustc_target/src/spec/mod.rs [hunk 1]
```diff
@@ -2436,20 +2434,28 @@ impl TargetTriple {
     /// Creates a target triple from the passed target path.
     pub fn from_path(path: &Path) -> Result<Self, io::Error> {
         let canonicalized_path = path.canonicalize()?;
```
Comment (bjorn3) [inline compiler/rustc_target/src/spec/mod.rs:2436]: It should be fine to remove this canonicalize operation now I think. The only difference would be that the triple would be the original file stem rather than the canonicalized one. This may be preferred in case of content addressed storage as the canonicalized name would be a non human readable hash.

File: compiler/rustc_target/src/spec/mod.rs [hunk 2]
```diff
@@ -2421,10 +2421,77 @@ impl ToJson for Target {
...
+
+// Use a manual implementation to ignore the path field
+impl PartialEq for TargetTriple {
+    fn eq(&self, other: &Self) -> bool {
+        match (self, other) {
+            (Self::TargetTriple(l0), Self::TargetTriple(r0)) => l0 == r0,
+            (
+                Self::TargetJson { path_for_rustdoc: _, triple: l_triple, contents: l_contents },
+                Self::TargetJson { path_for_rustdoc: _, triple: r_triple, contents: r_contents },
+            ) => l_triple == r_triple && l_contents == r_contents,
```
Comment (nagisa) [inline compiler/rustc_target/src/spec/mod.rs:2444]: Minor style nit, consider:

```suggestion
            (l@Self::TargetJson { .. }, r@Self::TargetJson { .. }) => {
                l.triple == r.triple && l.contents == r.contents
            }
```

or, if the intent was to have this an exhaustive match, maybe something like this (though there isn’t much value in this…):


```suggestion
            (Self::TargetJson { path_for_rustdoc: _, triple, contents }, r@Self::TargetJson { .. }) => {
                triple == r.triple && contents == r.contents
            }
```
```

File: compiler/rustc_target/src/spec/mod.rs [hunk 3]
```diff
@@ -2421,10 +2421,77 @@ impl ToJson for Target {
...
+            _ => false,
+        }
+    }
+}
+
+// Use a manual implementation to ignore the path field
+impl Hash for TargetTriple {
+    fn hash<H: Hasher>(&self, state: &mut H) -> () {
+        match (&*self,) {
```
Comment (nagisa) [inline compiler/rustc_target/src/spec/mod.rs:2453]: Is the tuple at all necessary here anymore? Similarly the reborrow and `&` + `ref` in the patterns?

File: compiler/rustc_target/src/spec/mod.rs [hunk 4]
```diff
@@ -2421,10 +2421,77 @@ impl ToJson for Target {
...
+                    s.emit_str(triple);
+                    s.emit_str(contents)
+                }),
+        }
+    }
+}
+
+impl<D: Decoder> Decodable<D> for TargetTriple {
+    fn decode(d: &mut D) -> Self {
+        match d.read_usize() {
```
Comment (nagisa) [inline compiler/rustc_target/src/spec/mod.rs:2483]: This is a little sketchy. This could fail if the implementation of the encoder has overriden `emit_enum_variant` to output something else than usize… Though of course `Decoder` does not provide a better way :shrug:

File: compiler/rustc_target/src/spec/mod.rs [hunk 5]
```diff
@@ -2436,20 +2503,28 @@ impl TargetTriple {
     /// Creates a target triple from the passed target path.
     pub fn from_path(path: &Path) -> Result<Self, io::Error> {
         let canonicalized_path = path.canonicalize()?;
-        Ok(TargetTriple::TargetPath(canonicalized_path))
+        let contents = std::fs::read_to_string(&canonicalized_path).map_err(|err| {
+            io::Error::new(
+                io::ErrorKind::InvalidInput,
+                format!("Target path {:?} is not a valid file: {}", canonicalized_path, err),
```
Comment (nagisa) [inline compiler/rustc_target/src/spec/mod.rs:2509]:
```suggestion
                format!("target path {:?} is not a valid file: {}", canonicalized_path, err),
```

This string if and when it does occur is probably going to be prefixed with an `error: ...` so making this is a proper sentence is probably not quite right.

**Review by nagisa — COMMENTED** [review]
+1 on the general direction. r=me, up to you what to do with the nits inline.

File: compiler/rustc_target/src/spec/mod.rs (hunk 3 above)
Comment (bjorn3) [reply compiler/rustc_target/src/spec/mod.rs:2453]: Looks like it isn't. I copied the derived version and changed it a bit.

File: compiler/rustc_target/src/spec/mod.rs (hunk 2 above)
Comment (bjorn3) [reply compiler/rustc_target/src/spec/mod.rs:2444]: > or, if the intent was to have this an exhaustive match

Indeed

> maybe something like this

Rustfmt puts that suggestion on four lines too.

**Comment by bjorn3** [comment]
Fixed all review comments apart from https://github.com/rust-lang/rust/pull/98225#discussion_r901112479

**Comment by nagisa** [comment]
consider squashing the history somewhat before `bors r=nagisa`ing this ^^
