### PR TITLE
fix broken build cache caused by rustdoc builds

### LINKED ISSUE #123177: Running `./x.py test miri --stage 0` twice rebuilds miri, cargo-miri, and rustdoc
This is fairly easy to reproduce:
```
./x.py test miri --stage 0 --test-args hello
./x.py test miri --stage 0 --test-args hello
```
(The `--test-args` just serves to make this take less long.)

The second command shouldn't have to build anything, just run the tests. But somehow it actually rebuilds miri, cargo-miri, and rustdoc.

This is a recent regression introduced by https://github.com/rust-lang/rust/issues/123028. Somehow building rustdoc seems to destroy the build cache for miri and cargo-miri, and vice versa.
Cc @onur-ozkan

### PR DESCRIPTION
**Pull request by onur-ozkan**
Currently rustdoc breaks the build cache (due to having different rustflags) when building rustdoc before building another tool (e.g., `x test miri && x test rustdoc && x test miri`).

This change fixes that by moving `on-broken-pipe` into `prepare_cargo_tool` so it is set for all tools.

cc @RalfJung 

Fixes #123177

### CODE REVIEW

**Comment by onur-ozkan** [comment]
@clubby789 is not active these days and this is a contributor roadblock.

So, r? @Kobzol

**Comment by RalfJung** [comment]
The flag is also set here, is that expected duplication?

https://github.com/rust-lang/rust/blob/521e707d7acf3f85389bbcfe53670638ef00c32a/src/bootstrap/src/core/build_steps/compile.rs#L1009-L1011

File: src/bootstrap/src/core/build_steps/tool.rs [hunk 1]
```diff
@@ -586,11 +590,6 @@ impl Step for Rustdoc {
             features.as_slice(),
         );
 
-        // If the rustdoc output is piped to e.g. `head -n1` we want the process
-        // to be killed, rather than having an error bubble up and cause a
-        // panic.
-        cargo.rustflag("-Zon-broken-pipe=kill");
```
Comment (RalfJung) [inline src/bootstrap/src/core/build_steps/tool.rs:592]: Looks like this was added in https://github.com/rust-lang/rust/commit/cde0cde151f30e07170d0f3caa721c92bebd7afe, regressing the fix I made in https://github.com/rust-lang/rust/pull/123192. Seems likely this will regress again.

Can you add a comment here saying to *not* add any rustflags, as that will cause undesired rebuilds?

**Comment by onur-ozkan** [comment]
> The flag is also set here, is that expected duplication?
> 
> https://github.com/rust-lang/rust/blob/521e707d7acf3f85389bbcfe53670638ef00c32a/src/bootstrap/src/core/build_steps/compile.rs#L1009-L1011

This PR changes rustflags for tools and the one you linked is for rustc builds. So, it is expected.

File: src/bootstrap/src/core/build_steps/tool.rs (hunk 1 above)
Comment (onur-ozkan) [reply src/bootstrap/src/core/build_steps/tool.rs:592]: > Looks like this was added in https://github.com/rust-lang/rust/commit/cde0cde151f30e07170d0f3caa721c92bebd7afe, regressing the fix I made in https://github.com/rust-lang/rust/pull/123192. Seems likely this will regress again.

It shouldn't regress. We still set `-Zon-broken-pipe=kill` for rustdoc.

> Can you add a comment here saying to not add any rustflags, as that will cause undesired rebuilds?

We need to duplicate that comment for every `impl Step for $tool` to make it clear, which wouldn't be not good enough either (because people can miss comments sometimes). As I mentioned in https://github.com/rust-lang/rust/issues/123177#issuecomment-2188335301, I will create a follow-up PR later this week to have this automatically checked. So the test can ensure tools never break the build cache again.

Comment (RalfJung) [reply src/bootstrap/src/core/build_steps/tool.rs:592]: :shrug: IMO one can't have too many comments (or at least, that is very hard). Tests are nice but they only catch things after someone already made their PR, when CI runs. And tests can't cover all combinations of tools either.

**Comment by Kobzol** [comment]
I wonder if we could return some "sealed" variant of `CargoCommand` from `prepare_tool_cargo`, so that it is not possible to modify its rustflags after creation anymore, to prevent issues like this. But it's probably only a problem for tools that are actually a part of a sysroot, like `rustdoc`, `lld-wrapper` etc. Maybe we could somehow mark these (in the type system) to make sure that it is not possible to break the cache.

But in any case, that's a more of a long-term goal, this PR looks reasonable as a hotfix.

File: src/bootstrap/src/core/build_steps/tool.rs (hunk 1 above)
Comment (onur-ozkan) [reply src/bootstrap/src/core/build_steps/tool.rs:592]: We definitely need a change that ensures we never end up breaking the cache again (for any tool not just rustdoc).

Added a comment for rustdoc as it's harmless to have.

**Comment by matthiaskrgr** [comment]
failed in https://github.com/rust-lang/rust/pull/126950
@bors r-
