### PR TITLE
prefer alias candidates for sizedness + auto trait goals 

### LINKED ISSUE #143992: where bounds regression in beta+nightly
### Code

```rust
pub trait Trait {
    type Assoc<G>: OtherTrait<G>;
}

pub trait OtherTrait<R> {
    fn new(r: R) -> R {
        r
    }
}

pub fn function<T: Trait>()
where
    T::Assoc<[u32; 1]>: Clone, // comment out to let it compile
{
    let _x = T::Assoc::new(());
}

```

### Version it worked on

It most recently worked on:  Stable (1.88)

### Version with regression

Beta (1.89), nightly (1.90) produces 
```
   Compiling playground v0.0.1 (/playground)
error[E0308]: mismatched types
  --> src/lib.rs:15:28
   |
15 |     let _x = T::Assoc::new(());
   |              ------------- ^^ expected `[u32; 1]`, found `()`
   |              |
   |              arguments to this function are incorrect
   |
note: associated function defined here
  --> src/lib.rs:6:8
   |
6  |     fn new(r: R) -> R {
   |        ^^^ ----

For more information about this error, try `rustc --explain E0308`.
```

Originally found in https://github.com/phimuemue/openschafkopf/blob/dacfecc50338443955998a074c0901d989b7a553/lib/src/game_analysis/determine_best_card_table.rs#L51 

```
error[E0308]: mismatched types
  --> lib/src/game_analysis/determine_best_card_table.rs:70:9
   |
70 | /         SFormatInfo {
71 | |             f_min: f32::MAX,
72 | |             f_max: f32::MIN,
73 | |             n_width: 0,
74 | |         };
   | |_________^ expected `(String, f32)`, found `SFormatInfo`
   |
   = note: expected tuple `(std::string::String, f32)`
             found struct `SFormatInfo`
```

@rustbot modify labels: +regression-from-stable-to-beta +regression-from-stable-to-nightly -regression-untriaged

### PR DESCRIPTION
**Pull request by davidtwco**
Fixes rust-lang/rust#143992

- abd07dec44437554520453f929c2b12d4eb8b11e: Reverts rust-lang/rust#144016 so that `MetaSized` bounds are checked properly, and updates all the tests accordingly, including making `tests/ui/sized-hierarchy/incomplete-inference-issue-143992.rs` fail when it shouldn't
- 90e61db9745f53d9aef21e3ebce0df19cc1389d7: Prefer alias candidates over parameter environment candidates for sizedness, auto and default traits. `tests/ui/sized-hierarchy/incomplete-inference-issue-143992.rs` passes again, but `tests/ui/generic-associated-types/issue-93262.rs` starts failing when it shouldn't
- e412062171925d0b40fdbeb5765c45087bdf0fe7: No longer require that predicates of aliases hold in well-formedness checking of the alias. `tests/ui/generic-associated-types/issue-93262.rs` passes again

Each commit updates all the tests to their new output so it should be easy enough to see what the impact of each change individually is. After all of the changes, tests that pass when they didn't before or vice versa: 

- `tests/ui/extern/extern-types-size_of_val.rs`
    - Previously passing, but only because of rust-lang/rust#144016, now correctly errors
- `tests/ui/sized-hierarchy/incomplete-inference-issue-143992.rs`
    - Previously failing on next solver, only because rust-lang/rust#144016 only applied to the old solver, passing now with 90e61db9745f53d9aef21e3ebce0df19cc1389d7
- `tests/ui/sized-hierarchy/overflow.rs`
    - Previously passing, but only because of rust-lang/rust#144016, now correctly errors
- `tests/ui/generic-associated-types/issue-92096.rs`
    - Previously passing, due to e412062171925d0b40fdbeb5765c45087bdf0fe7
    - Fails to prove `C::Connecting<'placeholder>: Send` which is required when proving that the generator is `Send`. This is an instance of rust-lang/rust#110338.
- `tests/ui/higher-ranked/trait-bounds/normalize-under-binder/norm-before-method-resolution-opaque-type.rs`
    - Previously passing, now failing in the next solver, due to 03e0fdab6196e81b44356f42f03b6a0a224cf451
    - Expected that this test now fails as ambigious, see [Zulip](https://rust-lang.zulipchat.com/#narrow/channel/144729-t-types/topic/sizedness.20bounds.20in.20explicit_implied_predicates_of.20.28.23142712.29/near/526987384)

This had a crater run in https://github.com/rust-lang/rust/pull/142712#issuecomment-3050358772 alongside some other changes.

r? @lcnr
cc rust-lang/rust#142712 (this extracts part of that change)

### CODE REVIEW

File: compiler/rustc_trait_selection/src/traits/select/mod.rs [hunk 1]
```diff
@@ -473,7 +473,15 @@ impl<'cx, 'tcx> SelectionContext<'cx, 'tcx> {
             }
         } else {
             let has_non_region_infer = stack.obligation.predicate.has_non_region_infer();
-            if let Some(candidate) = self.winnow_candidates(has_non_region_infer, candidates) {
+            let did = stack.obligation.predicate.def_id();
+            let is_sizedness_or_auto_or_default_predicate = self.tcx().is_sizedness_trait(did)
+                || self.tcx().trait_is_auto(did)
+                || self.tcx().is_default_trait(did);
```
Comment (lcnr) [inline compiler/rustc_trait_selection/src/traits/select/mod.rs]: I dislike this as is :thinking: maybe have a shared used by both old and new solver (with comments)
```rust
enum CandidatePreferenceMode {
    Default,
    Marker,
}

impl CandidatePreferenceMode {
    fn compute<I: Interner>(cx: I, trait_def_id: I::DefId) -> CandidatePreferenceMode;
}
```

**Comment by lcnr** [comment]
wrt 6aa37325c337b8bfbe9b4434fb7d12ba29ecaf8c it's not that we stop to normalize the predicates of projections, it's that when comfirming alias-bound/`Projection` candidates, we required that the alias is well-formed. While we need to normalize these obligations before proving them, the normalize isn't the relevant part, the "we need to prove them at all" is.

wrt `tests/ui/higher-ranked/trait-bounds/normalize-under-binder/norm-before-method-resolution-opaque-type.rs` see https://rust-lang.zulipchat.com/#narrow/channel/144729-t-types/topic/sizedness.20bounds.20in.20explicit_implied_predicates_of.20.28.23142712.29/near/526987384. It's intended that this test changes to be ambiguous.

`tests/ui/generic-associated-types/issue-92096.rs` fails to prove `C::Connecting<'placeholder>: Send` which is required when proving that the generator is `Send`. This is 'just' an instance of https://github.com/rust-lang/rust/issues/110338

Did you already crater run this behavior?

**Comment by davidtwco** [comment]
> Did you already crater run this behavior?

We did a crater run in https://github.com/rust-lang/rust/pull/142712#issuecomment-3050358772, which had all of these changes and included implying `MetaSized` on associated types.

File: compiler/rustc_trait_selection/src/traits/select/mod.rs (hunk 1 above)
Comment (davidtwco) [reply compiler/rustc_trait_selection/src/traits/select/mod.rs]: Fixed this, introduced a `CandidatePreferenceMode` and used it in both solvers

**Comment by davidtwco** [comment]
Updated the README and corrected the descriptions of everything per your comment

**Comment by davidtwco** [comment]
Rebased following #143545

**Comment by davidtwco** [comment]
Nominated as per [#t-types/nominated > #143992: where bounds regression in beta+nightly @ 💬](https://rust-lang.zulipchat.com/#narrow/channel/326866-t-types.2Fnominated/topic/.23143992.3A.20where.20bounds.20regression.20in.20beta.2Bnightly/near/529238515)

**Comment by lcnr** [comment]
This PR does two relevant changes we need to FCP. We've already tried the first change before in https://github.com/rust-lang/rust/pull/92191 and then reverted the PR as this caused a regression. The second change is necessary to avoid this regression and is also generally desirable. 

### `Sized` and auto trait goals now prefer alias-bound candidates over where-bounds

See https://github.com/rust-lang/rust/pull/132325 for our existing candidate preference rules. We currently prefer where-bounds over alias-bounds for all candidates. This preference (like all preference) is arbitrary to some degree.

We need to do this for the following example:
```rust
trait Bound<'a> {}
trait Trait<'a> {
    type Assoc: Bound<'a>;
}

fn impls_bound<'b, T: Bound<'b>>() {}
fn foo<'a, 'b, 'c, T>()
where
    T: Trait<'a>,
    for<'hr> T::Assoc: Bound<'hr>,
{
    impls_bound::<'b, T::Assoc>();
    impls_bound::<'c, T::Assoc>();
}
```
We need to do so when normalizing:
```rust
trait Iterator {
    type Item;
}
trait IntoIterator {
    type Item;
    type IntoIter: Iterator<Item = Self::Item>;
}

fn normalize<I: Iterator<Item = ()>>() {}
fn foo<I>()
where
    I: IntoIterator,
    I::IntoIter: Iterator<Item = ()>,
{
    // normalizing `<I::IntoIter as Iterator>::Item` has two candidates:
    // - alias-bound normalizing to `<I as IntoIterator>::Item`
    // - where-bound normalizing to `()`
    normalize::<I::IntoIter>();
}
```
However, arbitrary candidate preference is a mess, so this is sometimes incorrect, either if the where-bound actually talks about a *different alias*, or different *trait arguments*:
```rust
trait Bound<'a> {}
trait Trait<'a> {
    type Assoc: Bound<'a>;
}

fn impls_bound<'b, T: Bound<'b>>() {}
fn foo<'a, 'b, T>()
where
    T: for<'hr> Trait<'hr>,
    <T as Trait<'b>>::Assoc: Bound<'a>,
{
    // Using the where-bound for `<T as Trait<'a>>::Assoc: Bound<'a>`
    // unnecessarily equates `<T as Trait<'a>>::Assoc` with the
    // `<T as Trait<'b>>::Assoc` from the env.
    impls_bound::<'a, <T as Trait<'a>>::Assoc>();
    // For a `<T as Trait<'b>>::Assoc: Bound<'b>` the self type of the
    // where-bound matches, but the arguments of the trait bound don't.
    impls_bound::<'b, <T as Trait<'b>>::Assoc>();
}
```
While figuring out whether where-bounds or alias-bounds have correct trait arguments isn't possible in general, we do know that alias-bound candidates always apply to exactly the right self type - the alias itself.

This means that in cases where the trait doesn't have any non-self parameters, prefering alias-bound candidates over where-bounds is **always** correct.

There is one edge case here, since https://github.com/rust-lang/rust/pull/120752 we may also get alias-bound candidates from a nested self-type, so prefering alias-bound over where-bound candidates can be incorrect:
```rust
trait OtherTrait<'a> {
    type Assoc: ?Sized;
}

trait Trait
where
    <Self::Assoc as OtherTrait<'static>>::Assoc: Sized,
{
    type Assoc: for<'a> OtherTrait<'a>;
}

fn impls_sized<T: Sized>() {}
fn foo<'a, T>()
where
    T: Trait,
    for<'hr> <T::Assoc as OtherTrait<'hr>>::Assoc: Sized
{
    impls_sized::<<T::Assoc as OtherTrait<'a>>::Assoc>();
}
```
To avoid this issue, I propose limiting the preference of alias-bound over where-bound candidates only to the alias self-bounds, not indirect ones.

It also feels weird to me to implicitly change candidate preference depending on whether your trait has any generic arguments, so I propose to only change the preference rules for traits which are already special and guaranteed to not have any non-self arguments: `Sized` and auto traits.

To sum it up: we change our candidate preference rules to prefer alias self-bound candidates over where-bounds for `Sized` and auto traits. We continue to prefer where-bounds over alias bounds from nested self types and for all other traits. 

## Stop proving alias where-bounds when using alias-bounds

We currently prove the where-bounds of aliases when using an alias-bound candidate. This is generally redundant. We should have already proven these when checking whether the alias is well-formed.

However, we may have only ever proven well-formedness while the alias was still higher-ranked. If we then prove their where-bounds after instantiating this binder with placeholders, we get spurious errors due to missing implied bounds.

```rust
trait Bound {}
impl<'a, T> Bound for &'a T {}
trait Trait {
    type Assoc<'a>: Bound
    where
        Self: 'a;
}
impl<T> Trait for T {
    type Assoc<'a>
        = &'a T
    where
        Self: 'a;
}

// Using a higher ranked where-bound to prove itself succeeds,
// we don't check does not check whether it's WF after we've
// instantiated it. However, as normalizing an alias also requires
// proving its where-bounds, this function can only be called
// with types which are `'static`.
fn prove_hr<T: Trait>()
where
    for<'a> T::Assoc<'a>: Bound,
{
    prove_hr::<T>(); // ok
}
fn via_alias_bound<T: Trait>() {
    prove_hr::<T>(); // err, requires `T: 'static`, will compile with this PR
}
// Normalizing an associated item always checks its where-bounds.
fn via_impl_err<T>() {
    prove_hr::<T>(); // err, requires `T: 'static`
}
```

Ignoring the implied bounds of binders is generally unsound, e.g. https://github.com/rust-lang/rust/issues/25860 and https://github.com/rust-lang/rust/issues/84591.

The question is whether ignoring these implied bounds when using alias-bound candidates introduces any additional exploitable unsoundnesses:
- This only enables us to prove a where-bound whose self type is a higher-ranked alias
- To actually use this higher-ranked where-bound we need to instantiate the alias, at which point we should end up proving WF. As trait and alias parameters are all invariant, we can't hide erase the implied bound as in https://github.com/rust-lang/rust/issues/25860.
- I cannot think of an alternative way to use this alias-bound in a bad way. I've spent a few hours playing with this and wasn't able to come up with an exploit

cc @steffahn would love for you to also take a look at this if you're interested. We already have the behavior of this PR with `-Znext-solver`.

I am not totally confident that it's impossible to exploit this in theory, even though it feels unlikely to me. However, I do feel quite confident that any such exploit will be highly artificial and will get fixed once we properly support implied bounds for the existing unsoundnesses without requiring any additional effort or consideration.

I personally think that checking WF of the alias when using its implied bounds feels somewhat arbitrary and am in favor of removing this check.

@rfcbot fcp merge

File: tests/ui/sized-hierarchy/incomplete-inference-issue-143992.next_sized_hierarchy.stderr [hunk 2]
```diff
@@ -1,17 +1,122 @@
...
+
+error: unknown start of token: `
+  --> $DIR/incomplete-inference-issue-143992.rs:11:41
+   |
+LL | >>>>>>> 7faf6cf1c12 (revert: PR144016 - `MetaSized` does not always hold)
+   |                                         ^
+   |
+help: Unicode character '`' (Grave Accent) looks like ''' (Single Quote), but it is not
+   |
+LL - >>>>>>> 7faf6cf1c12 (revert: PR144016 - `MetaSized` does not always hold)
```
Comment (jackh726) [inline tests/ui/sized-hierarchy/incomplete-inference-issue-143992.next_sized_hierarchy.stderr]: Just FYI there are merge conflicts here.

File: tests/ui/higher-ranked/trait-bounds/normalize-under-binder/norm-before-method-resolution-opaque-type.rs [hunk 3]
```diff
@@ -20,6 +19,7 @@ where
     for<'a> <X as Trait<'a>>::Out<()>: Copy,
 {
     let x = *x; //[old]~ ERROR: cannot move out of `*x`
+//[next]~^ ERROR: type annotations needed
```
Comment (jackh726) [inline tests/ui/higher-ranked/trait-bounds/normalize-under-binder/norm-before-method-resolution-opaque-type.rs]: This is certainly a weird change :) I assume they both arise from being unable to normalize under the `for<'a>` binder?

File: tests/ui/generic-associated-types/higher-ranked-coroutine-param-outlives.rs [hunk 4]
```diff
@@ -2,7 +2,7 @@
 //@ revisions: assumptions no_assumptions
 //@[assumptions] compile-flags: -Zhigher-ranked-assumptions
 //@[assumptions] check-pass
-//@[no_assumptions] known-bug: #110338
+//@[no_assumptions] check-pass
```
Comment (jackh726) [inline tests/ui/generic-associated-types/higher-ranked-coroutine-param-outlives.rs]: So, #110338 has a bunch of issues. Are *all* of these fixed?

If so, then this PR should *close* that and other linked issue.

If not, is there other test coverage for that linked issue?

**Comment by davidtwco** [comment]
Thanks for the comments @jackh726, I'll address them once the FCP discussions have concluded and this is looking like it could be merged.

**Comment by davidtwco** [comment]
@rust-lang/types a small nudge to have a look at the FCP above - https://github.com/rust-lang/rust/pull/144064#issuecomment-3127365714

File: tests/ui/extern/extern-types-size_of_val.rs
Comment (oli-obk) [inline tests/ui/extern/extern-types-size_of_val.rs:1]: give this test a doc comment. I don't know why it was added, but it's good it's erroring now. And weird it wasn't even checking the runtime behaviour

**Review by oli-obk — APPROVED** [review]

File: tests/ui/sized-hierarchy/incomplete-inference-issue-143992.next_sized_hierarchy.stderr (hunk 2 above)
Comment (davidtwco) [reply tests/ui/sized-hierarchy/incomplete-inference-issue-143992.next_sized_hierarchy.stderr]: Oops, fixed

File: tests/ui/generic-associated-types/higher-ranked-coroutine-param-outlives.rs (hunk 4 above)
Comment (davidtwco) [reply tests/ui/generic-associated-types/higher-ranked-coroutine-param-outlives.rs]: I tried a handful of the reproductions for these and some of them are fixed but some aren't (though some of them had external dependencies so aren't all easily added as tests here). I don't know if there is other test coverage for the linked issue, but that would have been the case prior to this patch too.

File: tests/ui/higher-ranked/trait-bounds/normalize-under-binder/norm-before-method-resolution-opaque-type.rs (hunk 3 above)
Comment (davidtwco) [reply tests/ui/higher-ranked/trait-bounds/normalize-under-binder/norm-before-method-resolution-opaque-type.rs]: It's been a while since I wrote this patch, but I think so.

File: compiler/rustc_next_trait_solver/src/solve/trait_goals.rs [hunk 5]
```diff
@@ -1380,6 +1381,24 @@ where
             return Ok((candidate.result, Some(TraitGoalProvenVia::Misc)));
         }
 
+        let potential_alias_bound_response =
```
Comment (lcnr) [inline compiler/rustc_next_trait_solver/src/solve/trait_goals.rs]: comment please 😁

Comment (lcnr) [reply compiler/rustc_next_trait_solver/src/solve/trait_goals.rs]: also, I don't want us to apply this preference to nested alias bound candidates, only to shallow ones

Comment (davidtwco) [reply compiler/rustc_next_trait_solver/src/solve/trait_goals.rs]: Fixed both

File: compiler/rustc_middle/src/traits/select.rs [hunk 6]
```diff
@@ -116,8 +116,9 @@ pub enum SelectionCandidate<'tcx> {
 
     /// This is a trait matching with a projected type as `Self`, and we found
     /// an applicable bound in the trait definition. The `usize` is an index
-    /// into the list returned by `tcx.item_bounds`.
-    ProjectionCandidate(usize),
+    /// into the list returned by `tcx.item_bounds` and the `bool` is whether
+    /// this is candidate from recursion on the self type of a projection.
+    ProjectionCandidate(usize, bool),
```
Comment (lcnr) [inline compiler/rustc_middle/src/traits/select.rs]: please use named fields here 🤔 this feels a bit too subtle this way

File: compiler/rustc_next_trait_solver/src/solve/assembly/mod.rs [hunk 7]
```diff
@@ -651,6 +651,7 @@ where
                 goal,
                 candidates,
                 AliasBoundKind::SelfBounds,
+                AliasBoundSource::NonNested,
```
Comment (lcnr) [inline compiler/rustc_next_trait_solver/src/solve/assembly/mod.rs]: maybe use `AliasBoundSource` in both solvers? also, isn't this redundant with `AliasBoundKind`?

File: compiler/rustc_next_trait_solver/src/solve/trait_goals.rs [hunk 8]
```diff
@@ -1380,6 +1383,25 @@ where
...
+        // Extract non-nested alias bound candidates, will be preferred over where bounds if
+        // `candidate_preference_mode == CandidatePreferenceMode::Marker`.
+        if matches!(candidate_preference_mode, CandidatePreferenceMode::Marker)
+            && candidates.iter().any(|c| {
+                matches!(c.source, CandidateSource::AliasBound(AliasBoundSource::NonNested))
+            })
+        {
+            let alias_bounds: Vec<_> = candidates
+                .extract_if(.., |c| {
+                    matches!(c.source, CandidateSource::AliasBound(AliasBoundSource::NonNested))
```
Comment (lcnr) [inline compiler/rustc_next_trait_solver/src/solve/trait_goals.rs]:
```suggestion
                    matches!(c.source, CandidateSource::AliasBound(_))
```
i think we can always merge all alias bound candidates, we should only have `AliasBoundSource::NonNested` in the `Marker` case without any constraints

File: compiler/rustc_next_trait_solver/src/solve/trait_goals.rs [hunk 9]
```diff
@@ -1380,6 +1383,25 @@ where
             return Ok((candidate.result, Some(TraitGoalProvenVia::Misc)));
         }
 
+        // Extract non-nested alias bound candidates, will be preferred over where bounds if
+        // `candidate_preference_mode == CandidatePreferenceMode::Marker`.
```
Comment (lcnr) [inline compiler/rustc_next_trait_solver/src/solve/trait_goals.rs]:
```suggestion
        // we're proving an auto-trait or `Sized`.
```

File: compiler/rustc_next_trait_solver/src/solve/trait_goals.rs [hunk 10]
```diff
@@ -1427,9 +1449,10 @@ where
             };
         }
 
-        if candidates.iter().any(|c| matches!(c.source, CandidateSource::AliasBound)) {
+        // Next, prefer any alias bound (nested or otherwise)..
```
Comment (lcnr) [inline compiler/rustc_next_trait_solver/src/solve/trait_goals.rs]:
```suggestion
        // Next, prefer any alias bound (nested or otherwise).
```

File: compiler/rustc_trait_selection/src/traits/select/mod.rs [hunk 11]
```diff
@@ -1874,6 +1880,23 @@ impl<'tcx> SelectionContext<'_, 'tcx> {
             break;
         }
 
+        let mut alias_bounds = candidates.iter().filter_map(|c| {
+            if let ProjectionCandidate(i, nested) = c.candidate { Some((i, nested)) } else { None }
+        });
+        // Extract non-nested alias bound candidates, will be preferred over where bounds if
+        // `candidate_preference_mode == CandidatePreferenceMode::Marker`.
```
Comment (lcnr) [inline compiler/rustc_trait_selection/src/traits/select/mod.rs]: same as above, pls explain when this matches is true, not restate this condition

**Review by lcnr — COMMENTED** [review]
nits

*[View changes since this review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/rust/144064/956f47c32f1bd97b22cd702d7ccf78f0f0d42c34..306cf28083c974c26a7e6808e1eac72ef19891c6)*

File: compiler/rustc_middle/src/traits/select.rs (hunk 6 above)
Comment (davidtwco) [reply compiler/rustc_middle/src/traits/select.rs]: Fixed

File: compiler/rustc_next_trait_solver/src/solve/assembly/mod.rs (hunk 7 above)
Comment (davidtwco) [reply compiler/rustc_next_trait_solver/src/solve/assembly/mod.rs]: Fixed, using `AliasBoundKind` in both, hadn't noticed that type was just doing the same thing

File: compiler/rustc_next_trait_solver/src/solve/trait_goals.rs (hunk 8 above)
Comment (davidtwco) [reply compiler/rustc_next_trait_solver/src/solve/trait_goals.rs]: Fixed

File: compiler/rustc_next_trait_solver/src/solve/trait_goals.rs (hunk 9 above)
Comment (davidtwco) [reply compiler/rustc_next_trait_solver/src/solve/trait_goals.rs]: Fixed

File: compiler/rustc_next_trait_solver/src/solve/trait_goals.rs (hunk 10 above)
Comment (davidtwco) [reply compiler/rustc_next_trait_solver/src/solve/trait_goals.rs]: Fixed

File: compiler/rustc_trait_selection/src/traits/select/mod.rs (hunk 11 above)
Comment (davidtwco) [reply compiler/rustc_trait_selection/src/traits/select/mod.rs]: Fixed

File: compiler/rustc_next_trait_solver/src/solve/assembly/mod.rs [hunk 12]
```diff
@@ -473,10 +468,7 @@ where
         // fails to reach a fixpoint but ends up getting an error after
         // running for some additional step.
         //
-        // FIXME(@lcnr): While I believe an error here to be possible, we
-        // currently don't have any test which actually triggers it. @lqd
-        // created a minimization for an ICE in typenum, but that one no
-        // longer fails here. cc trait-system-refactor-initiative#105.
```
Comment (lcnr) [inline compiler/rustc_next_trait_solver/src/solve/assembly/mod.rs:479]: this is a spurious revert

File: compiler/rustc_trait_selection/src/traits/select/candidate_assembly.rs [hunk 13]
```diff
@@ -224,18 +225,23 @@ impl<'cx, 'tcx> SelectionContext<'cx, 'tcx> {
                         );
 
                         // We checked the polarity already
+                        let kind = if nested {
+                            AliasBoundKind::NonSelfBounds
+                        } else {
+                            AliasBoundKind::SelfBounds
```
Comment (lcnr) [inline compiler/rustc_trait_selection/src/traits/select/candidate_assembly.rs]: can you uplift this if/use `AliasBoundKind` consistently in `for_each_item_bound` as well?

File: tests/ui/async-await/higher-ranked-auto-trait-14.rs [hunk 14]
```diff
@@ -3,7 +3,7 @@
 //@ revisions: assumptions no_assumptions
 //@[assumptions] compile-flags: -Zhigher-ranked-assumptions
 //@[assumptions] check-pass
-//@[no_assumptions] known-bug: #110338
+//@[no_assumptions] check-pass
```
Comment (lcnr) [inline tests/ui/async-await/higher-ranked-auto-trait-14.rs]:
```suggestion
//@ check-pass
```

File: tests/ui/async-await/higher-ranked-auto-trait-2.rs [hunk 15]
```diff
@@ -3,7 +3,7 @@
 //@ revisions: assumptions no_assumptions
 //@[assumptions] compile-flags: -Zhigher-ranked-assumptions
 //@[assumptions] check-pass
-//@[no_assumptions] known-bug: #110338
+//@[no_assumptions] check-pass
```
Comment (lcnr) [inline tests/ui/async-await/higher-ranked-auto-trait-2.rs]:
```suggestion
//@ check-pass
```

File: tests/ui/async-await/higher-ranked-auto-trait-3.rs [hunk 16]
```diff
@@ -3,7 +3,7 @@
 //@ revisions: assumptions no_assumptions
 //@[assumptions] compile-flags: -Zhigher-ranked-assumptions
 //@[assumptions] check-pass
-//@[no_assumptions] known-bug: #110338
+//@[no_assumptions] check-pass
```
Comment (lcnr) [inline tests/ui/async-await/higher-ranked-auto-trait-3.rs]: etc

**Review by lcnr — COMMENTED** [review]
final nits, then r=me

*[View changes since this review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/rust/144064/ed1d94311e7ed53eabb5667ef577802d88d1aaee..4dedfb78f3679564554320f5c815175b49ae85d1)*

File: compiler/rustc_next_trait_solver/src/solve/assembly/mod.rs (hunk 12 above)
Comment (davidtwco) [reply compiler/rustc_next_trait_solver/src/solve/assembly/mod.rs:479]: Oops, not sure how I managed this, still getting used to spotting things like this with Jujutsu

File: compiler/rustc_trait_selection/src/traits/select/candidate_assembly.rs (hunk 13 above)
Comment (davidtwco) [reply compiler/rustc_trait_selection/src/traits/select/candidate_assembly.rs]: Fixed

File: tests/ui/async-await/higher-ranked-auto-trait-2.rs (hunk 15 above)
Comment (davidtwco) [reply tests/ui/async-await/higher-ranked-auto-trait-2.rs]: Fixed

File: tests/ui/async-await/higher-ranked-auto-trait-3.rs (hunk 16 above)
Comment (davidtwco) [reply tests/ui/async-await/higher-ranked-auto-trait-3.rs]: Fixed

File: tests/ui/async-await/higher-ranked-auto-trait-14.rs (hunk 14 above)
Comment (davidtwco) [reply tests/ui/async-await/higher-ranked-auto-trait-14.rs]: Fixed

File: compiler/rustc_trait_selection/src/traits/select/mod.rs [hunk 17]
```diff
@@ -1650,7 +1661,16 @@ impl<'cx, 'tcx> SelectionContext<'cx, 'tcx> {
...
-                for_each(self, bound, idx)?;
+                for_each(
+                    self,
+                    bound,
+                    idx,
+                    if in_parent_alias_type {
+                        AliasBoundKind::NonSelfBounds
+                    } else {
+                        AliasBoundKind::SelfBounds
+                    },
```
Comment (lcnr) [inline compiler/rustc_trait_selection/src/traits/select/mod.rs]: use `let mut alias_bound_kind = AliasBoundKind::SelfBounds;` without a `bool` at all? 🤔 and then the if to match

File: tests/ui/async-await/higher-ranked-auto-trait-7.rs [hunk 18]
```diff
@@ -3,7 +3,7 @@
 //@ revisions: assumptions no_assumptions
 //@[assumptions] compile-flags: -Zhigher-ranked-assumptions
 //@[assumptions] check-pass
-//@[no_assumptions] known-bug: #110338
+//@[no_assumptions] check-pass
```
Comment (lcnr) [inline tests/ui/async-await/higher-ranked-auto-trait-7.rs]: :<

File: tests/ui/generic-associated-types/higher-ranked-coroutine-param-outlives-2.rs [hunk 19]
```diff
@@ -2,7 +2,7 @@
 //@ revisions: assumptions no_assumptions
 //@[assumptions] compile-flags: -Zhigher-ranked-assumptions
 //@[assumptions] check-pass
-//@[no_assumptions] known-bug: #110338
+//@[no_assumptions] check-pass
```
Comment (lcnr) [inline tests/ui/generic-associated-types/higher-ranked-coroutine-param-outlives-2.rs]: :< 2 etc

File: tests/ui/higher-ranked/trait-bounds/normalize-under-binder/norm-before-method-resolution-opaque-type.rs (hunk 3 above)
Comment (lcnr) [reply tests/ui/higher-ranked/trait-bounds/normalize-under-binder/norm-before-method-resolution-opaque-type.rs]: What's going on is that we've previously defined the opaque by using the where-bound when checking whether the alias is `Sized`. This constrained the opaque. We now use the alias-bound instead, which means we never constrain the opaque.

CAn you add this as a comment

File: tests/ui/sized-hierarchy/incomplete-inference-issue-143992.rs [hunk 20]
```diff
@@ -1,12 +1,9 @@
 //@ compile-flags: --crate-type=lib
-//@ revisions: current next current_sized_hierarchy next_sized_hierarchy
+//@ revisions: current next
 //@ ignore-compare-mode-next-solver (explicit revisions)
 //@[current] check-pass
 //@[next] check-pass
```
Comment (lcnr) [inline tests/ui/sized-hierarchy/incomplete-inference-issue-143992.rs]:
```suggestion
//@ check-pass
```

File: tests/ui/sized-hierarchy/prefer-non-nested-alias-bound.rs [hunk 21]
```diff
@@ -0,0 +1,25 @@
+//@ check-pass
+//@ compile-flags: --crate-type=lib
+//@ revisions: current next
+//@ ignore-compare-mode-next-solver (explicit revisions)
+//@[next] compile-flags: -Znext-solver
+
+trait OtherTrait<'a> {
```
Comment (lcnr) [inline tests/ui/sized-hierarchy/prefer-non-nested-alias-bound.rs:12]: please add comment. and it's the fact that we *should not* prefernested alias bounds over where-bounds.

**Review by lcnr — COMMENTED** [review]
final nits 😅 r=me after

*[View changes since this review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/rust/144064/4b94758d2ba7d0ef71ccf5fde29ce4bc5d6fe2a4..081c14d032f089fba8fb227ba64bcd5ad1b0488e)*

File: tests/ui/sized-hierarchy/prefer-non-nested-alias-bound.rs (hunk 21 above)
Comment (davidtwco) [reply tests/ui/sized-hierarchy/prefer-non-nested-alias-bound.rs:12]: Fixed

File: tests/ui/async-await/higher-ranked-auto-trait-7.rs (hunk 18 above)
Comment (davidtwco) [reply tests/ui/async-await/higher-ranked-auto-trait-7.rs]: Oops, sorry, should have checked the other tests too.

File: tests/ui/generic-associated-types/higher-ranked-coroutine-param-outlives-2.rs (hunk 19 above)
Comment (davidtwco) [reply tests/ui/generic-associated-types/higher-ranked-coroutine-param-outlives-2.rs]: Fixed

File: tests/ui/sized-hierarchy/incomplete-inference-issue-143992.rs (hunk 20 above)
Comment (davidtwco) [reply tests/ui/sized-hierarchy/incomplete-inference-issue-143992.rs]: Fixed

File: compiler/rustc_trait_selection/src/traits/select/mod.rs (hunk 17 above)
Comment (davidtwco) [reply compiler/rustc_trait_selection/src/traits/select/mod.rs]: Fixed
