### PR TITLE
Fix double warning about illegal floating-point literal pattern

### LINKED ISSUE #86600: illegal_floating_point_literal_pattern warns twice
With the following code [(playground)](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=3d8d20c7f65bc6699b47419f26e8095f):

```rust
fn main() {
    let x = 42.0;

    match x {
        5.0 => {}
        _ => {}
    }
}
```

I expected to see one warning.

Instead, this happened:

```
warning: floating-point types cannot be used in patterns
 --> src/main.rs:5:9
  |
5 |         5.0 => {}
  |         ^^^
  |
  = note: `#[warn(illegal_floating_point_literal_pattern)]` on by default
  = warning: this was previously accepted by the compiler but is being phased out; it will become a hard error in a future release!
  = note: for more information, see issue #41620 <https://github.com/rust-lang/rust/issues/41620>

warning: floating-point types cannot be used in patterns
 --> src/main.rs:5:9
  |
5 |         5.0 => {}
  |         ^^^
  |
  = warning: this was previously accepted by the compiler but is being phased out; it will become a hard error in a future release!
  = note: for more information, see issue #41620 <https://github.com/rust-lang/rust/issues/41620>

warning: 2 warnings emitted
```

### Meta

```
1.55.0-nightly

(2021-06-23 5a7834050f3a0ebcd117)
```

### PR DESCRIPTION
**Pull request by FabianWolff**
This PR fixes #86600. The problem is that the `ConstToPat` struct contains a field `include_lint_checks`, which determines whether lints should be emitted or not, but this field is currently not obeyed at one point, leading to a warning being emitted more than once. I have fixed this behavior here.

### CODE REVIEW

File: compiler/rustc_mir_build/src/thir/pattern/const_to_pat.rs [hunk 1]
```diff
@@ -272,12 +272,14 @@ impl<'a, 'tcx> ConstToPat<'a, 'tcx> {
 
         let kind = match cv.ty.kind() {
             ty::Float(_) => {
-                tcx.struct_span_lint_hir(
-                    lint::builtin::ILLEGAL_FLOATING_POINT_LITERAL_PATTERN,
-                    id,
-                    span,
-                    |lint| lint.build("floating-point types cannot be used in patterns").emit(),
-                );
+                if self.include_lint_checks {
```
Comment (rylev) [inline compiler/rustc_mir_build/src/thir/pattern/const_to_pat.rs:275]: This isn't really new to this PR, but it would be nice if `include_lint_checks` had some documentation on when it's enabled and when not. Currently it seems to be enabled in `rustc_mir_build::thir::pattern::MatchVisitor::lower_pattern` but not in `rustc_mir_build::thir::pattern::pat_from_hir`. `lower_pattern` happens when checking the validity of matches and `pat_from_hir` happens when actually constructing mir. It might be nice to mention at the field definition site that `include_lint_checks` will be true when checking validity and false when building mir.

Comment (FabianWolff) [reply compiler/rustc_mir_build/src/thir/pattern/const_to_pat.rs:275]: It seems somewhat wasteful that the `ConstToPat` lowering even has to run twice (if it didn't, we wouldn't need the `include_lint_checks` field). However, I don't know the broader design considerations behind all of this, I just developed a targeted fix for the issue you reported, so I'm not the right person to ask for additional documentation here...

**Review by davidtwco — APPROVED** [review]
LGTM
