### PR TITLE
Parser: Suggest Placing the Return Type After Function Parameters

### LINKED ISSUE #126311: Bad diagnostic for misplaced where clause
### Code

```Rust
trait Service {
    type Output;
    type Error;
}

fn takes_service<S: Service>(s: S) where S::Error: Debug -> S::Output { loop {} }
```

### Current output

```Shell
Compiling playground v0.0.1 (/playground)
error: expected one of `(`, `+`, `,`, `::`, `<`, or `{`, found `->`
  --> src/main.rs:31:58
   |
31 | fn takes_service<S: Service>(s: S) where S::Error: Debug -> S::Output {
   |                                                    ------^^ expected one of `(`, `+`, `,`, `::`, `<`, or `{`
   |                                                    |    |
   |                                                    |    help: try adding parentheses
   |                                                    `Fn` bounds require arguments in parentheses

error: could not compile `playground` (bin "playground") due to 1 previous error
```

### Desired output

```Shell
Something about misplaced where clause, directing me to place it _after_ the return type
```

### Rationale and extra context

_No response_

### Other cases

_No response_

### Rust Version

```Shell
Build using the Nightly version: 1.81.0-nightly

(2024-06-11 d0227c6a19c2d6e8dceb)
```

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by veera-sivarajan**
Fixes #126311 

This PR suggests placing the return type after the function parameters when it's misplaced after a `where` clause.

This also tangentially improves diagnostics for cases like [this](https://github.com/veera-sivarajan/rust/blob/86d6f1312a77997ef994240e716288d61a343a6d/tests/ui/parser/issues/misplaced-return-type-without-where-issue-126311.rs#L1C1-L1C28) and adds doc comments for `parser::AllowPlus`.

### CODE REVIEW

File: compiler/rustc_parse/src/parser/item.rs [hunk 1]
```diff
@@ -2332,10 +2332,20 @@ impl<'a> Parser<'a> {
...
         generics.where_clause = self.parse_where_clause()?; // `where T: Ord`
 
+        // `fn_params_end` is needed only when it's followed by a where clause.
+        let fn_params_end =
+            if generics.where_clause.has_where_token { Some(fn_params_end) } else { None };
+
         let mut sig_hi = self.prev_token.span;
-        let body = self.parse_fn_body(attrs, &ident, &mut sig_hi, fn_parse_mode.req_body)?; // `;` or `{ ... }`.
+        let body =
+            self.parse_fn_body(attrs, &ident, &mut sig_hi, fn_parse_mode.req_body, fn_params_end)?; // `;` or `{ ... }`.
```
Comment (lcnr) [inline compiler/rustc_parse/src/parser/item.rs:2348]:
```suggestion
        // Either `;` or `{ ... }`.
        let body =
            self.parse_fn_body(attrs, &ident, &mut sig_hi, fn_parse_mode.req_body, fn_params_end)?;
```
existing

**Comment by lcnr** [comment]
r? compiler

File: compiler/rustc_parse/src/parser/item.rs [hunk 2]
```diff
@@ -2332,10 +2332,20 @@ impl<'a> Parser<'a> {
...
+
+        // Store the end of function parameters to give better diagnostics
+        // inside `parse_fn_body()`.
+        let fn_params_end = self.prev_token.span.shrink_to_hi();
+
         generics.where_clause = self.parse_where_clause()?; // `where T: Ord`
 
+        // `fn_params_end` is needed only when it's followed by a where clause.
+        let fn_params_end =
+            if generics.where_clause.has_where_token { Some(fn_params_end) } else { None };
```
Comment (lcnr) [inline compiler/rustc_parse/src/parser/item.rs:2344]: what's the harm of always passing in that span?

Comment (veera-sivarajan) [reply compiler/rustc_parse/src/parser/item.rs:2344]: Checking if a where clause exists makes sure we don't incorrectly suggest to place the second return type after function parameters for code like `fn fun<T>() -> u8 -> u8 {}`.

**Review by lcnr — COMMENTED** [review]
I guess this makes sense :thinking: can you split the error handling out of `fn parse_fn_body` and always return `ErrorGuaranteed` from that function?

**Comment by veera-sivarajan** [comment]
Sure, thank you for the suggestion. I moved the error handling to a separate function.

But, it's not possible to return an `ErrorGuaranteed` because a couple of cases are irrecoverable errors that return a `Diag`.

File: compiler/rustc_parse/src/parser/item.rs [hunk 3]
```diff
@@ -2332,14 +2332,105 @@ impl<'a> Parser<'a> {
...
+                        snippet,
+                        ret_ty_span,
+                    });
+                }
+                Err(err)
+            } else {
+                Err(err)
+            }
+        } else {
+            Ok(())
```
Comment (lcnr) [inline compiler/rustc_parse/src/parser/item.rs:2430]: that `Ok(())` is very questionable :thinking: I would expect that this is unreachable?

Comment (veera-sivarajan) [reply compiler/rustc_parse/src/parser/item.rs:2430]: Replacing the `Ok(())` with `unreachable!()` fails on this UI test:
``` rust
extern "C" {
  fn foo() //~ERROR expected `;`
}
```
It's because `expected_one_of_not_found()` returns an `Ok()` when it's able to recover from an error.

Comment (lcnr) [reply compiler/rustc_parse/src/parser/item.rs:2430]: :+1: two more requests in that case. `expected_one_of_not_found` currently always returns `Recovered::Yes(ErrorGuaranteed)` in that case afaict. Please change it's return type to `PResult<'a, ErrorGuaranteed>` and then use a match with `Err::<_; ErrorGuaranteed>(_guar) => Ok(()),` or sth to make sure we only return `Ok(())` without an error if we've already emitted one

Comment (veera-sivarajan) [reply compiler/rustc_parse/src/parser/item.rs]: Sure, changed the return type of those two functions to `PResult<'a, ErrorGuaranteed>`. Also, made some small changes to `expect_one_of` to map `ErrorGuaranteed` to `Recovered::Yes(ErrorGuaranteed)`.

Thank you for the suggestions.
