### PR TITLE
Fix race condition in Arc's get_mut and make_unqiue

### LINKED ISSUE #24880: arc::get_mut/Arc::make_unique are racy
Both of these essentially check that ```inner().strong == 1 && inner().weak == 1``` to check that ```&mut self``` is the only reference to the Arc's data. However in between the checks a Weak pointer could be promoted and the Weak pointer dropped, resulting in both checks succeeding. Adding an additional strong check afterwards won't help as the second strong pointer could then be demoted again.

I don't see an obvious way without a two-word atomic read or a generation counter or something of that sort. On 64-bit splitting an atomic64 into two 32-bit sections /might/ be ok, but on 32-bit only allowing 16 bits of refcount seems bad. (There might be something with using a high bit as a lock bit or such?)

### PR DESCRIPTION
**Pull request by aturon**
This commit resolves the race condition in the `get_mut` and
`make_unique` functions, which arose through interaction with weak
pointers. The basic strategy is to "lock" the weak pointer count when
trying to establish uniqueness, by reusing the field as a simple
spinlock. The overhead for normal use of `Arc` is expected to be minimal
-- it will be _none_ when only strong pointers are used, and only
requires a move from atomic increment to CAS for usage of weak pointers.

The commit also removes the `unsafe` and deprecated status of these functions.

Closes #24880

r? @alexcrichton 

cc @metajack @SimonSapin @Ms2ger

### CODE REVIEW

**Comment by alexcrichton** [comment]
Could this also move the methods to `Arc::{get_mut, make_unique}`? Other than that I'd like to get another pair of eyes or two to check this out, but I believe that this is safe.

File: src/liballoc/arc.rs [hunk 1]
```diff
@@ -352,39 +373,40 @@ impl<T: Clone> Arc<T> {
...
+        // The use of usize::MAX here acts as a "lock" while we try to determine
+        // whether this thread is the unique owner.
+        if self.inner().weak.compare_and_swap(1, usize::MAX, SeqCst) != 1 {
             *self = Arc::new((**self).clone())
+        } else {
+            let need_clone = self.inner().strong.load(SeqCst) != 1;
+            self.inner().weak.store(1, Relaxed); // release lock immediately;
+                                                 // we don't need to hold it while cloning
+            if need_clone { *self = Arc::new((**self).clone()); }
         }
```
Comment (eefriedman) [inline src/liballoc/arc.rs]: We should only clone if there are other live strong references; the correct implementation is something like the following (untested, possibly buggy):

```
if self.inner().strong.compare_and_swap(1, 0, Release) != 1 {
    // Another strong pointer exists; clone.
    *self = Arc::new((**self).clone());
} else if self.inner().weak.load(SeqCst) != 1 {
    // There are no strong pointers left, but there are remaining weak
    // pointers; steal the contents.
    // FIXME: Is there a better way to write this?
    let weak = Weak { _ptr: self._ptr };
    self._ptr = 0;
    let stolen_data = ptr::read(&(*weak._ptr).data);
    *self = Arc::new(stolen_data);
} else {
    // No other strong or weak pointers; just revive this Arc.
    self.inner().strong = 1;
}
```
No spinlock necessary.

**Comment by talchas** [comment]
Clone/Drop for Weak<T> and Arc::weak_count also need to be CAS loops. I would also suggest using weak.CAS(acquire); strong.load(Relaxed); weak.store(Release);, as I believe that is sufficient and will remove an unnecessary fence on x86 (and maybe pull it out into a private is_unique() to reduce code duplication?)

**Comment by eefriedman** [comment]
An argument could be made that get_mut() on an Arc with no other strong references should kill all weak pointers and memcpy the data if necessary instead of failing.  Not sure how get_mut() is used in practice.  Either way, it needs documentation which explicitly states what happens in the presence of weak pointers.

IIRC, we need to move from atomic increment to CAS anyway to avoid unsafety from overflowing the counter, so any overhead involved in that is irrelevant.

File: src/liballoc/arc.rs (hunk 1 above)
Comment (talchas) [inline src/liballoc/arc.rs]: This would not work for get_mut though, so the spinlock would still need to exist, just not for make_unique?

Comment (eefriedman) [inline src/liballoc/arc.rs]: Yes.  Granted, we could change the semantics of get_mut so it kills weak pointers rather than failing, which would allow removing the spinlock, but that's probably not a decision we should make based on implementation details.

File: src/liballoc/arc.rs [hunk 2]
```diff
@@ -201,9 +207,21 @@ impl<T: ?Sized> Arc<T> {
...
-        Weak { _ptr: self._ptr }
+        loop {
+            let cur = self.inner().weak.load(Relaxed);
+
+            // check if the weak counter is currently "locked"; if so, spin.
+            if cur == usize::MAX { continue }
+
+            // NOTE: this code currently ignores the possibility of overflow
+            // into usize::MAX; in general both Rc and Arc need to be adjusted
+            // to deal with overflow.
```
Comment (eddyb) [inline src/liballoc/arc.rs]: Since references take up memory, I don't think `usize` can be overflowed by them... except we now have safe `mem::forget` which makes it trivial. `RefCell` is also affected.

Comment (bluss) [inline src/liballoc/arc.rs]: There's a loong discussion about it [(internals)](https://internals.rust-lang.org/t/rc-is-unsafe-mostly-on-32-bit-targets-due-to-overflow/2120)

File: src/liballoc/arc.rs [hunk 3]
```diff
@@ -282,22 +296,29 @@ pub fn strong_count<T: ?Sized>(this: &Arc<T>) -> usize { Arc::strong_count(this)
...
-        // returned is the *only* pointer that will ever be returned to T. Our
-        // reference count is guaranteed to be 1 at this point, and we required
-        // the Arc itself to be `mut`, so we're returning the only possible
-        // reference to the inner data.
-        let inner = &mut **this._ptr;
-        Some(&mut inner.data)
+pub fn get_mut<T: ?Sized>(this: &mut Arc<T>) -> Option<&mut T> {
+    // lock the weak pointer count if we appear to be the sole weak pointer
+    // holder.
+    if this.inner().weak.compare_and_swap(1, usize::MAX, SeqCst) != 1 {
```
Comment (nagisa) [inline src/liballoc/arc.rs]: Shouldn’t this read `this.inner().weak.compare_and_swap(1, usize::MAX, SeqCst) == 1`?

Comment (nagisa) [inline src/liballoc/arc.rs]: Or rather `this.inner().weak.compare_and_swap(0, usize::MAX, SeqCst) == 0`.

File: src/liballoc/arc.rs (hunk 2 above)
Comment (eddyb) [inline src/liballoc/arc.rs]: Actually, scratch that, `RefCell` overflows into a "deadlock" state - mutably locked by too many immutable references, which denies any further borrows.

File: src/liballoc/arc.rs (hunk 3 above)
Comment (talchas) [inline src/liballoc/arc.rs]: I believe you were correct the first time due to the start-at-1 behavior of the weak refcount (logically the strong references collectively hold a weak reference). But yes, the condition is backwards.

**Comment by aturon** [comment]
Thanks everyone for the feedback, especially @eefriedman for the insight about the semantics of `make_unique` with respect to weak refs. I've updated the impl and am testing now.

File: src/liballoc/arc.rs [hunk 4]
```diff
@@ -361,33 +334,114 @@ impl<T: Clone> Arc<T> {
...
+    /// *get_mut(&mut x).unwrap() = 4;
+    /// assert_eq!(*x, 4);
+    ///
+    /// let _y = x.clone();
+    /// assert!(get_mut(&mut x).is_none());
+    /// # }
+    /// ```
+    #[inline]
+    #[unstable(feature = "arc_unique")]
+    pub fn get_mut(this: &mut Arc<T>) -> Option<&mut T> {
```
Comment (nagisa) [inline src/liballoc/arc.rs]: Why not `&mut self`?

File: src/liballoc/arc.rs [hunk 5]
```diff
@@ -346,14 +320,13 @@ impl<T: ?Sized> Deref for Arc<T> {
     }
 }
 
-impl<T: Clone> Arc<T> {
+impl<T: ?Sized + Clone> Arc<T> {
```
Comment (eefriedman) [inline src/liballoc/arc.rs]: I don't think the `?Sized` actually does anything here; Clone implies Sized.

File: src/liballoc/arc.rs (hunk 4 above)
Comment (Ms2ger) [inline src/liballoc/arc.rs]: That could interfere with any `get_mut()` on `T`. (The doc comment still thinks it's a free function, though.)

Comment (nagisa) [inline src/liballoc/arc.rs]: I don’t see how that’s a problem given we have UFCS.

File: src/liballoc/arc.rs [hunk 6]
```diff
@@ -361,33 +334,114 @@ impl<T: Clone> Arc<T> {
...
-    pub unsafe fn make_unique(&mut self) -> &mut T {
-        // FIXME(#24880) potential race with upgraded weak pointers here
-        //
-        // Note that we hold a strong reference, which also counts as a weak
-        // reference, so we only clone if there is an additional reference of
-        // either kind.
-        if self.inner().strong.load(SeqCst) != 1 ||
-           self.inner().weak.load(SeqCst) != 1 {
-            *self = Arc::new((**self).clone())
+    pub fn make_unique(this: &mut Arc<T>) -> &mut T {
```
Comment (nagisa) [inline src/liballoc/arc.rs]: Again, why `this` instead of `&mut self`? If this change is here to stay, documentation needs to be updated as well.

File: src/liballoc/arc.rs [hunk 7]
```diff
@@ -361,33 +334,114 @@ impl<T: Clone> Arc<T> {
...
+
+            // Note that it is not possible for the read of `weak` to yield
+            // usize::MAX (i.e., locked), since the weak count can only be
+            // locked by a thread with a strong reference.
+
+            // Materializae our own implicit weak pointer, so that it can clean
+            // up the ArcInner as needed.
+            let weak = Weak { _ptr: this._ptr };
+            // mark the data itself as already deallocated
+            this._ptr = unsafe { NonZero::new(0 as *mut _) };
```
Comment (eefriedman) [inline src/liballoc/arc.rs]: `NonZero::new(0)` is a bit suspect.

File: src/liballoc/arc.rs (hunk 4 above)
Comment (bluss) [inline src/liballoc/arc.rs]: It follows the new convention for smart pointer methods.

File: src/liballoc/arc.rs (hunk 7 above)
Comment (eddyb) [inline src/liballoc/arc.rs]: Yeah, that's not the right value for not running the destructor (I guess we handle both in the `Drop` impl, manually).

**Comment by aturon** [comment]
Additional nits addressed. I switched to a swap + mem::forget to avoid manual zeroing.

File: src/liballoc/arc.rs [hunk 8]
```diff
@@ -361,33 +334,115 @@ impl<T: Clone> Arc<T> {
...
-        // reference, so we only clone if there is an additional reference of
-        // either kind.
-        if self.inner().strong.load(SeqCst) != 1 ||
-           self.inner().weak.load(SeqCst) != 1 {
-            *self = Arc::new((**self).clone())
+    pub fn make_unique(this: &mut Arc<T>) -> &mut T {
+        // Note that we hold both a strong reference and a weak reference.
+        // Thus, releasing our strong reference only will not, by itself, cause
+        // the memory to be deallocated.
+        if this.inner().strong.compare_and_swap(1, 0, Release) != 1 {
```
Comment (alexcrichton) [inline src/liballoc/arc.rs]: Can you add some comments here to the effect of the memory orderings? It's not immediately clear to me why this is Release and the one below is SeqCst. Also, can't the one at the bottom be relaxed b/c this is the only pointer in existence? (e.g. single threaded)

File: src/liballoc/arc.rs [hunk 9]
```diff
@@ -361,33 +334,115 @@ impl<T: Clone> Arc<T> {
...
+        } else if this.inner().weak.load(SeqCst) != 1 {
+            // We removed the last strong ref, but there are additional weak
+            // refs remaining. We'll move the contents to a new Arc, and
+            // invalidate the other weak refs.
+
+            // Note that it is not possible for the read of `weak` to yield
+            // usize::MAX (i.e., locked), since the weak count can only be
+            // locked by a thread with a strong reference.
+
+            // Materializae our own implicit weak pointer, so that it can clean
```
Comment (alexcrichton) [inline src/liballoc/arc.rs]: Materialize

Also, can you clarify in the sentence above what "invalidate the other weak refs" means? I feel like they're not actually being invalidated, we've just already given up our strong reference by this point.

File: src/liballoc/arc.rs [hunk 10]
```diff
@@ -361,33 +334,115 @@ impl<T: Clone> Arc<T> {
...
+            // up the ArcInner as needed.
+            let weak = Weak { _ptr: this._ptr };
+            // mark the data itself as already deallocated
+            unsafe {
+                let mut swap = Arc::new(ptr::read(&(**weak._ptr).data));
+                mem::swap(this, &mut swap);
+                mem::forget(swap);
```
Comment (alexcrichton) [inline src/liballoc/arc.rs]: If I'm reading this right, I think that this may leak the previous `Arc`? All strong references have an implicit weak reference, and we've determined that we're the last strong reference (and we gave that up), so we need to relinquish our weak ref here as well, right? This basically looks like it needs to run the second half of the `drop_slow` method.

File: src/liballoc/arc.rs [hunk 11]
```diff
@@ -361,33 +334,115 @@ impl<T: Clone> Arc<T> {
...
+    }
+
+    /// Determine whether this is the unique reference (including weak refs) to
+    /// the underlying data.
+    ///
+    /// Note that this requires locking the weak ref count.
+    fn is_unique(&mut self) -> bool {
+        // lock the weak pointer count if we appear to be the sole weak pointer
+        // holder.
+        if self.inner().weak.compare_and_swap(1, usize::MAX, Acquire) == 1 {
```
Comment (alexcrichton) [inline src/liballoc/arc.rs]: Could you add some comments for why these are acquire/relaxed/release? From our discussion today I *think* this is ok.

File: src/liballoc/arc.rs (hunk 10 above)
Comment (alexcrichton) [inline src/liballoc/arc.rs]: Oh wait, you've got `let weak = ...` above, carry on!

**Comment by alexcrichton** [comment]
A few minor nits here and there, but otherwise looks good to me. Tricky stuff!

r=me

**Comment by boghison** [comment]
Any news on this? It would be awesome to get rid of those Servo warnings :)

**Comment by aturon** [comment]
@boghison Sorry, got tied up with other things after sorting out the memory orderings with @alexcrichton. Just running tests locally, and then it's ready for bors.

File: src/liballoc/arc.rs [hunk 12]
```diff
@@ -154,7 +156,12 @@ impl<T: ?Sized + fmt::Debug> fmt::Debug for Weak<T> {
 
 struct ArcInner<T: ?Sized> {
     strong: atomic::AtomicUsize,
+
+    // the value usize::MAX acts as a sentinel for temporarily "locking" the
+    // ability to upgrade weak pointers or downgrade strong ones; this is used
+    // to avoid races in `make_unique` and `get_mut`.
```
Comment (alexcrichton) [inline src/liballoc/arc.rs]: I think this comment is slightly out of date now, I believe the only race is between `get_mut` and `downgrade`, right?

File: src/liballoc/arc.rs [hunk 13]
```diff
@@ -201,9 +208,25 @@ impl<T: ?Sized> Arc<T> {
     #[unstable(feature = "arc_weak",
                reason = "Weak pointers may not belong in this module.")]
     pub fn downgrade(&self) -> Weak<T> {
-        // See the clone() impl for why this is relaxed
-        self.inner().weak.fetch_add(1, Relaxed);
-        Weak { _ptr: self._ptr }
+        loop {
+            // This Relaaxed is OK because we're checking the value in the CAS
```
Comment (alexcrichton) [inline src/liballoc/arc.rs]: Relaaxed

File: src/liballoc/arc.rs [hunk 14]
```diff
@@ -201,9 +208,25 @@ impl<T: ?Sized> Arc<T> {
...
+            // below.
+            let cur = self.inner().weak.load(Relaxed);
+
+            // check if the weak counter is currently "locked"; if so, spin.
```
Comment (alexcrichton) [inline src/liballoc/arc.rs]: Can you clarify that we're locking against `get_mut`?

File: src/liballoc/arc.rs [hunk 15]
```diff
@@ -361,33 +338,140 @@ impl<T: Clone> Arc<T> {
...
-        // Note that we hold a strong reference, which also counts as a weak
-        // reference, so we only clone if there is an additional reference of
-        // either kind.
-        if self.inner().strong.load(SeqCst) != 1 ||
-           self.inner().weak.load(SeqCst) != 1 {
-            *self = Arc::new((**self).clone())
+        // Use Acquire to ensure that we see any writes to `weak` that happen
+        // before release writes (i.e., decrements) to `strong`. Since we hold a
+        // weak count, there's no chance the ArcInner itself could be
+        // deallocated.
```
Comment (alexcrichton) [inline src/liballoc/arc.rs]: Overall it might be nice to have a giant doc comment at the top of this module talking about the memory orderings (this can happen later). The "aha" moment here was that this *only* needs to synchronize with decrements to strong because otherwise it doesn't matter as we're gonna do the clone anyway.

Basically if we're tweaking arcs, it'd be nice to have one block to read at the top of the file which gives an overview of what's synchronizing with that as there's quite a bit of synchronization going on now...

File: src/liballoc/arc.rs [hunk 16]
```diff
@@ -361,33 +338,140 @@ impl<T: Clone> Arc<T> {
...
+            // locked by a thread with a strong reference.
+
+            // Materialize our own implicit weak pointer, so that it can clean
+            // up the ArcInner as needed.
+            let weak = Weak { _ptr: this._ptr };
+
+            // mark the data itself as already deallocated
+            unsafe {
+                // there is no data race in the implicit write caused by `read`
+                // here (due to zeroing) because data is no longer accessed by
```
Comment (alexcrichton) [inline src/liballoc/arc.rs]: I believe `ptr::read` doesn't actually zero (e.g. that's what `ptr::read_and_zero` does)

File: src/liballoc/arc.rs [hunk 17]
```diff
@@ -361,33 +338,140 @@ impl<T: Clone> Arc<T> {
...
+                // other threads (due to there being no more strong refs at this
+                // point).
+                let mut swap = Arc::new(ptr::read(&(**weak._ptr).data));
+                mem::swap(this, &mut swap);
+                mem::forget(swap);
+            }
+        } else {
+            // We were the sole reference of either kind; bump back up the
+            // strong ref count.
```
Comment (alexcrichton) [inline src/liballoc/arc.rs]: Could you clarify why this is a `Release`? It seems like this may be able to be relaxed?

Comment (alexcrichton) [inline src/liballoc/arc.rs]: No scratch the "this may be able to be relaxed", I feel like this is similar to `is_unique` where want to ensure that this doesn't happen before the load of the weak count.

**Comment by alexcrichton** [comment]
Some final nits about comments, but I have no objections to any literal code written down, so I'm fine landing soon to help servo and following up with a comment heavy PR.

@bors: r+ d77c4b0fa63d420b2f995e37ee07402f9a243361
