### PR TITLE
[rustdoc] Move line numbers into the `<code>` directly

### LINKED ISSUE #84242: rustdoc: [src] view is broken in lynx
I tried this: Opening https://rust-for-linux.github.io/docs/src/kernel/sync/condvar.rs.html#19-23 in `lynx`.

I expected to see this happen: Either the source code is shown side-by-side with the line numbers, or the line numbers aren't shown at all.

Instead, this happened: image

I think there's a very old issue about this that was fixed for newer browsers, but I can't seem to find it. This has definitely happened on ancient docs in docs.rs before. cc @ojeda - is this something you care about? I saw someone mentioned it in https://lkml.org/lkml/2021/4/16/49 but I don't know if that was actually serious.

### Meta

Not sure what rust-for-linux is using, but I can replicate the issue with rustdoc 1.53.0-nightly (d0695c908 2021-04-12).

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Fixes #84242.

This is the first for adding support for https://github.com/rust-lang/rust/issues/127334 and also for another feature I'm working on.

A side-effect of this change is that it also fixes source code pages display in lynx since they're not directly in the source code.

To allow having code wrapping, the grid approach doesn't work as the line numbers are in their own container, so we need to move them into the code. Now with this, it becomes much simpler to do what we want (with CSS mostly). One downside: the highlighting became more complex and slow as we need to generate some extra HTML tags directly into the highlighting process. However that also allows to not have a huge HTML size increase.

You can test the result [here](https://rustdoc.crud.net/imperio/move-line-numbers-into-code/scrape_examples/fn.test_many.html) and [here](https://rustdoc.crud.net/imperio/move-line-numbers-into-code/src/scrape_examples/lib.rs.html#10).

The appearance should have close to no changes.

r? @notriddle

### CODE REVIEW

File: src/librustdoc/html/highlight.rs [hunk 1]
```diff
@@ -226,6 +240,43 @@ impl<F: Write> Drop for TokenHandler<'_, '_, F> {
...
+fn write_scraped_line_number(out: &mut impl Write, line: u32, extra: &'static str) {
+    // https://developers.google.com/search/docs/crawling-indexing/robots-meta-tag#data-nosnippet-attr
+    // Do not show "1 2 3 4 5 ..." in web search results.
+    write!(out, "{extra}<span data-nosnippet>{line}</span>",).unwrap();
+}
+
+fn write_line_number(out: &mut impl Write, line: u32, extra: &'static str) {
+    // https://developers.google.com/search/docs/crawling-indexing/robots-meta-tag#data-nosnippet-attr
+    // Do not show "1 2 3 4 5 ..." in web search results.
+    write!(out, "{extra}<a href=\"#{line}\" id={line} data-nosnippet>{line}</a>",).unwrap();
```
Comment (yotamofek) [inline src/librustdoc/html/highlight.rs:252]: ... I think?

```suggestion
    write!(out, "{extra}<a href=\"#{line}\" id=\"{line}\" data-nosnippet>{line}</a>",).unwrap();
```

File: src/librustdoc/html/static/css/rustdoc.css [hunk 2]
```diff
@@ -908,22 +907,46 @@ both the code example and the line numbers, so we need to remove the radius in t
...
+	width: calc(9ch + var(--line-number-padding) * 2);
+}
+
+.example-wrap [data-nosnippet] {
 	color: var(--src-line-numbers-span-color);
-	padding: 0 8px;
+	text-align: right;
+	display: inline-block;
+	margin-right: 20px;
+	user-select: none;
```
Comment (TimNN) [inline src/librustdoc/html/static/css/rustdoc.css:943]: According to https://caniuse.com/?search=user-select, this needs prefixes for Safari and IE.

(I have confirmed that on Safari, for the two linked examples, the line numbers get selected).

File: src/librustdoc/html/highlight.rs (hunk 1 above)
Comment (GuillaumeGomez) [reply src/librustdoc/html/highlight.rs:252]: It's a number so I'm cheating here. That allows to get 2 characters x number of lines, so it becomes interesting for big crates.

File: src/librustdoc/html/static/css/rustdoc.css (hunk 2 above)
Comment (GuillaumeGomez) [reply src/librustdoc/html/static/css/rustdoc.css:943]: Didn't know, thanks for that!

File: src/librustdoc/html/highlight.rs (hunk 1 above)
Comment (yotamofek) [reply src/librustdoc/html/highlight.rs:252]: Cool, didn't know that was valid in HTML5!

Comment (GuillaumeGomez) [reply src/librustdoc/html/highlight.rs:252]: It's valid in all HTML as far as I know. ^^'

**Comment by GuillaumeGomez** [comment]
Finally fixed the tests and made tidy happy. ^^'

**Review by notriddle — APPROVED** [review]
This look really nice. It fixes the problem, and it also fixes https://github.com/rust-lang/rust/issues/84242

```text
                                                                 lib.rs - source
Files

   scrape_examples/
   lib.rs

1//@ run-flags:-Zrustdoc-scrape-examples
2/// # Examples
3///
4/// ```
5/// test();
6/// test();
7/// ```
8pub fn test() {}
9
10pub fn test_many() {}





Commands: Use arrow keys to move, '?' for help, 'q' to quit, '<-' to go back.
  Arrow keys: Up and Down to move.  Right to follow a link; Left to go back.
 H)elp O)ptions P)rint G)o M)ain screen Q)uit /=search [delete]=history list 
```


You can mention that in the PR description and we can finally close that issue out.

**Comment by notriddle** [comment]
r=me after removing the quotes from the href attribute (assuming there's not some reason I wasn't aware of to keep them).

**Comment by GuillaumeGomez** [comment]
Wow nice, didn't know about the hashtag in the attributes. Thanks!

**Comment by Kobzol** [comment]
@rust-timer build 60306e7eec6370a07164779d0732664879526f38

**Comment by Kobzol** [comment]
This PR caused a number of `doc` regressions. I'll let you judge if it was fine, just wasn't sure if it was expected or not.

**Comment by notriddle** [comment]
I knew it would happen. The underlying cause is that this new format pushes more bytes of HTML than the old one. It's a hack that's imperfect both for producing non-bloated HTML and for a11y. This change also makes #136991 possible (which is ultimately what pushed it over the edge).

<details>

- We want small HTML. To reduce HTML bloat to zero, we could have used JavaScript to add line numbers, but that would require JS to make line-number-anchored URLs work
- We want to produce correct results in as many browsers as possible (including browsers with JS disabled, text browsers with no CSS support, and screen readers). To achieve perfect results, we could have used tables, but that would require syntax highlighting regions that span multiple lines to be declared separately on each line

The new version pushed in this PR does an imperfect job of making HTML both small and accessible at the same time. This is vividly shown in these Lynx screenshots:

<table><thead><tr><th>Before<th>After</tr></thead><tbody><tr><td>

````
1
2
3
4
5
6
7
8
9
10
//@ run-flags:-Zrustdoc-scrape-examples
/// # Examples
///
/// ```
/// test();
/// test();
/// ```
pub fn test() {}

pub fn test_many() {}
````

</td><td>

````
1//@ run-flags:-Zrustdoc-scrape-examples
2/// # Examples
3///
4/// ```
5/// test();
6/// test();
7/// ```
8pub fn test() {}
9
10pub fn test_many() {}
````

</td></tr></tbody></table>

First of all, the visible-on-screen line numbers are also where the anchors for links are found, so if someone shares a URL pointing at a particular line, the "After" version will jump you to that line. So that's much better than what we did before. Too bad there isn't any way to fix this without making the HTML bigger, because we have to mark up each line separately instead of doing it all at once.

The "Before" screenshot is clearly busted, but the "After" screenshot is also imperfect. Notice how the word `pub` on line 10 isn't in the same on-screen column as line 8? They're aligned in the actual source file, but Lynx doesn't know that.

</details>
