### PR TITLE
ignore {std,fast,vector,this}call on non-x86 windows

### LINKED ISSUE #54569: aarch64-pc-windows-msvc target needs to treat `extern "stdcall"` like `extern "C"`
Compiling code like:

https://github.com/jcjones/u2f-hid-rs/blob/ea7244febb010bb8e02c5e01dd6f2b9a0082884a/src/windows/winapi.rs#L22-L49

results in:

```
LLVM ERROR: Unsupported calling convention
```

presumably because `rustc` attempts to translate it into an x86-specific ABI, which the AArch64 backend rightly rejects.

`clang` already ignores `__stdcall` for non-x86 targets:

https://reviews.llvm.org/D36105

I'm not completely sure what the right answer for Rust is.  I think `Target::adjust_abi` is the rough equivalent of the above clang bit and needs to take a few more cases into account for non-x86 Windows:

https://github.com/rust-lang/rust/blob/31789a658bb6b6c78da1f2b99a5f169e4e8b983b/src/librustc_target/spec/mod.rs#L764-L776

@alexcrichton does that sound right?  If so, I'll code up a patch.

### PR DESCRIPTION
**Pull request by froydnj**
MSVC ignores these keywords for C/C++ and uses the standard system
calling convention.  Rust should do so as well.

Fixes #54569.

### CODE REVIEW

**Comment by froydnj** [comment]
I made the test x86-only.  There were other failures, e.g.

```
thread '[ui] ui\issues\issue-19100.rs' panicked at 'explicit panic', tools\compiletest\src\runtest.rs:3238:9
note: Run with `RUST_BACKTRACE=1` for a backtrace.
failures:
    [ui] ui\issues\issue-19100.rs
test result: FAILED. 6797 passed; 1 failed; 45 ignored; 0 measured; 0 filtered out
thread 'main' panicked at 'Some tests failed', tools\compiletest\src\main.rs:496:22
```

But that test does not look related to this change.  Intermittent?

r? @alexcrichton

File: src/test/codegen/issue-32364.rs [hunk 1]
```diff
@@ -8,8 +8,49 @@
...
+// ignore-amdgcn
+// ignore-sparc
+// ignore-sparc64
+// ignore-sparcv9
+// ignore-sparcel
+// ignore-s390x
+// ignore-tce
+// ignore-thumb
+// ignore-thumbeb
+// ignore-x86_64
```
Comment (alexcrichton) [inline src/test/codegen/issue-32364.rs]: Oh dear sorry about this! I think nowadays we support `// only-x86` or something like that

**Comment by alexcrichton** [comment]
Hm so `issue-19100.rs` does indeed look intermittent, and to confirm about @kennytm's failure the `x86_stdcallcc` only makes sense on the `i686-*` targets we have, *not* `x86_64-*`?

**Comment by froydnj** [comment]
> Hm so `issue-19100.rs` does indeed look intermittent, and to confirm about @kennytm's failure the `x86_stdcallcc` only makes sense on the `i686-*` targets we have, _not_ `x86_64-*`?

I believe that's correct.  x86-64 MSVC ignores `stdcall`; I suppose LLVM's x86-64 backend must accept it, but ignore it?

> Oh dear sorry about this! I think nowadays we support `// only-x86` or something like that

Indeed, thanks for pointing that out!
