### PR TITLE
When encountering unclosed delimiters during lexing, check for diff markers

### LINKED ISSUE #116252: Make diff conflict marker error higher priority than unclosed delimeter
I tried this code:

```rust
mod tests {
    #[test]
<<<<<<< HEAD
    fn test1() {
=======
    fn test2() {
>>>>>>> 7a4f13c blah blah blah
    }
}
```

I expected to see this happen: *explanation*
`error: encountered diff marker`

Instead, this happened: *explanation*
`error: this file contains an unclosed delimiter`

### Meta

`rustc --version --verbose`:
```
rustc 1.72.1 (d5c2e9c34 2023-09-13)
binary: rustc
commit-hash: d5c2e9c342b358556da91d61ed4133f6f50fc0c3
commit-date: 2023-09-13
host: aarch64-apple-darwin
release: 1.72.1
LLVM version: 16.0.5
```

### PR DESCRIPTION
**Pull request by estebank**
Fix #116252.

### CODE REVIEW

**Comment by compiler-errors** [comment]
Sorry I didn't get to this. Don't have much time to study this for correctness -- would've appreciated if the PR description described what this PR is doing, though.

r? compiler

**Comment by estebank** [comment]
@compiler-errors sorry, I thought that the PR name was enough context for this change:

Some time back, the compiler continued past unmatched delimiter and attempted to execute later stages. Later, a change was made to make unmatched delimiters during lexer be a hard error which stopped execution of later stages. That made it so that unmatched delimiters caused by diff markers would only complain about the delimiters and not the diff markers. This change detects the unmatched delimiters during lexer, and if so creates a new parser with the token stream gotten so far, in order to look for diff markers. If found, we emit an appropriate error. Either way, after doing that we continue as we are now (not get past lexing after emitting these errors).

File: compiler/rustc_parse/src/lexer/tokentrees.rs [hunk 1]
```diff
@@ -18,36 +18,39 @@ pub(super) struct TokenTreesReader<'a> {
...
 
     // Parse a stream of tokens into a list of `TokenTree`s.
-    fn parse_token_trees(&mut self, is_delimited: bool) -> PResult<'a, TokenStream> {
+    fn parse_token_trees(&mut self, is_delimited: bool) -> (TokenStream, PResult<'a, ()>) {
         self.token = self.string_reader.next_token().0;
         let mut buf = Vec::new();
         loop {
             match self.token.kind {
-                token::OpenDelim(delim) => buf.push(self.parse_token_tree_open_delim(delim)?),
+                token::OpenDelim(delim) => {
```
Comment (petrochenkov) [inline compiler/rustc_parse/src/lexer/tokentrees.rs:37]:
```suggestion
                token::OpenDelim(delim) => buf.push(self.parse_token_tree_open_delim(delim).map_err(....)?),
```

File: compiler/rustc_parse/src/lexer/mod.rs [hunk 2]
```diff
@@ -64,28 +64,34 @@ pub(crate) fn parse_token_trees<'a>(
...
+        // Return error if there are unmatched delimiters or unclosed delimiters.
+        // We emit delimiter mismatch errors first, then emit the unclosing delimiter mismatch
+        // because the delimiter mismatch is more likely to be the root cause of error
+
+        let mut buffer = Vec::with_capacity(1);
+        let mut parser = crate::stream_to_parser(sess, stream.clone(), None);
+        while parser.token != token::Eof {
+            // There were unmatched delims, see if there were diff markers that caused it.
+            if let Err(err) = parser.err_diff_marker() {
+                err.buffer(&mut buffer);
```
Comment (petrochenkov) [inline compiler/rustc_parse/src/lexer/mod.rs:79]: So the logic here is that errors are buffered for later and not emitted immediately.
But `parse_token_tree_open_delim` is eventually called from here and emits the diff marker immediately.

I think `parse_token_tree_open_delim` should return the diff marker error instead of the unclosed delimiter error, if it occurs. Then it will be buffered here normally.

Also this piece of code
```rust
let mut parser = crate::stream_to_parser(...);
while parser.token != token::Eof { ... }
```
is better factored out and reused between this place and `parse_token_tree_open_delim`.

File: compiler/rustc_parse/src/lexer/tokentrees.rs [hunk 3]
```diff
@@ -106,7 +109,20 @@ impl<'a> TokenTreesReader<'a> {
...
         // We stop at any delimiter so we can try to recover if the user
         // uses an incorrect delimiter.
-        let tts = self.parse_token_trees(/* is_delimited */ true)?;
+        let (tts, res) = self.parse_token_trees(/* is_delimited */ true);
+        if let Err(mut err) = res {
+            // If there are unclosed delims, see if there are diff markers and if so, point them
+            // out instead of complaining about the unclosed delims.
+            let mut parser = crate::stream_to_parser(self.string_reader.sess, tts, None);
+            while parser.token != token::Eof {
+                if let Err(mut diff_err) = parser.err_diff_marker() {
```
Comment (petrochenkov) [inline compiler/rustc_parse/src/lexer/tokentrees.rs:118]: This case is not covered by a test.

File: compiler/rustc_parse/src/lexer/tokentrees.rs (hunk 1 above)
Comment (estebank) [reply compiler/rustc_parse/src/lexer/tokentrees.rs:37]: The parent item does not return `Result`, it returns `(TokenStream, PResult<'a, ()>, Vec<UnmatchedDelim>)`. I can write an `impl Try` but that seems to be much more code than the somewhat annoying match. Can also use let else instead.

File: compiler/rustc_parse/src/lexer/mod.rs (hunk 2 above)
Comment (estebank) [reply compiler/rustc_parse/src/lexer/mod.rs]: This part actually was unneded, because the code in parse_token_tree_open_delim was sufficient. I must have needed it during development but can't trigger it now.

File: compiler/rustc_parse/src/lexer/tokentrees.rs [hunk 4]
```diff
@@ -106,7 +109,20 @@ impl<'a> TokenTreesReader<'a> {
...
+                    diff_err.emit();
+                    err.delay_as_bug();
```
Comment (petrochenkov) [inline compiler/rustc_parse/src/lexer/tokentrees.rs:120]: As I mentioned in the neighbor comment https://github.com/rust-lang/rust/pull/116712#discussion_r1374432093 the upper level logic here expects errors to be buffered, and not emitted immediately, but here the error is emitted immediately.

I also don't understand the purpose of `delay_as_bug` here.

Comment (estebank) [reply compiler/rustc_parse/src/lexer/tokentrees.rs:120]: > I also don't understand the purpose of delay_as_bug here.

It is so that only the diff errors are emitted, silencing the unclosed delim errors because they would be unnecessary noise.

I'll address the rest of the comment.

Comment (estebank) [reply compiler/rustc_parse/src/lexer/tokentrees.rs]: Changed to bubble the errors as a Vec.
