### PR TITLE
Zero the `REPARSE_MOUNTPOINT_DATA_BUFFER` header

### LINKED ISSUE #107884: Windows' `symlink_junction_inner` mysteriously fails
I think [`symlink_junction_inner`](https://github.com/rust-lang/rust/blob/a6975734632c4771edd45ef10e7d4753541d0f3a/library/std/src/sys/windows/fs.rs#L1382) sometimes isn't writing to the buffer properly which can cause the `DeviceIoControl` to fail and thus tests that use it. This function isn't great and is only used in tests. I can reproduce this consistently locally on current master but in CI most PRs seem to test ok (though [not all](https://github.com/rust-lang/rust/pull/107167)).

I've not really investigated yet but on a hunch I added the following which seems to fix it locally, I don't know why or if it's a fluke:

```diff
diff --git a/library/std/src/sys/windows/fs.rs b/library/std/src/sys/windows/fs.rs
index 37809803828..d7f1a44bdf4 100644
--- a/library/std/src/sys/windows/fs.rs
+++ b/library/std/src/sys/windows/fs.rs
@@ -1409,6 +1409,8 @@ fn symlink_junction_inner(original: &Path, junction: &Path) -> io::Result<()> {
         (*db).ReparseTargetLength = ((i - 1) * 2) as c::WORD;
         (*db).ReparseDataLength = (*db).ReparseTargetLength as c::DWORD + 12;

+        crate::hint::black_box(slice::from_raw_parts(buf, i));
+
         let mut ret = 0;
         cvt(c::DeviceIoControl(
             h as *mut _,
```

### PR DESCRIPTION
**Pull request by ChrisDenton**
Makes sure the full header is correctly initialized.

Fixes #107884

### CODE REVIEW

File: library/std/src/sys/windows/fs.rs [hunk 1]
```diff
@@ -1393,6 +1393,8 @@ fn symlink_junction_inner(original: &Path, junction: &Path) -> io::Result<()> {
         let mut data = Align8([MaybeUninit::<u8>::uninit(); c::MAXIMUM_REPARSE_DATA_BUFFER_SIZE]);
```
Comment (clubby789) [inline library/std/src/sys/windows/fs.rs:1393]: Might [`MU::zeroed`](https://doc.rust-lang.org/std/mem/union.MaybeUninit.html#method.zeroed) be clearer here?
```suggestion
        let mut data = Align8([MaybeUninit::<u8>::zeroed(); c::MAXIMUM_REPARSE_DATA_BUFFER_SIZE]);
```

Comment (ChrisDenton) [reply library/std/src/sys/windows/fs.rs:1393]: Hm, that would zero the entire buffer tho. Which I assume we're trying to avoid because it's large. Otherwise `[0_u8, c::MAXIMUM_REPARSE_DATA_BUFFER_SIZE]` would probably be ok because it's a plain old data struct.

Comment (clubby789) [reply library/std/src/sys/windows/fs.rs:1393]: It probably doesn't matter too much if it's only used in tests but good point.

Comment (workingjubilee) [reply library/std/src/sys/windows/fs.rs:1393]: It's apparently 16KB for the buffer, so we'd be touching 4 pages on x86. That doesn't thrash all of a standard 32KB cache but it's still a lot when compared to simply zeroing a few shorts and longs.

otoh, "just tests".

**Comment by thomcc** [comment]
Oof...

@bors r+

**Comment by ChrisDenton** [comment]
Btw, as @clubby789 has said, the struct definition for `REPARSE_MOUNTPOINT_DATA_BUFFER` is actually very wrong. But things just so happen to line up enough that it works (at least for our usage). I guess it was reverse engineered at some point before the docs were made public.

I think I need to stop complaining about how bad this function is and actually do the rewrite already. I'll try some time this weekend. It would also be nice to add as a public API at some point.
