### PR TITLE
Tweak `suggest_constraining_type_param`

### LINKED ISSUE #69983: help text for `Send` trait bound mismatch is misleading
This is a small issue but it cost me a fair bit of time and I thought an improvement here could help other new users.

Summary: when a caller tries to invoke a function with a trait bound that includes `Send`, but the caller's value is not `Send`, the error message says:

> "error[E0277]: `T` cannot be sent between threads safely"

The problem here isn't (necessarily) that `T` cannot be sent between threads safely, but more precisely that the function expected `T: Send` and got plain `T`.

It might not be obvious how this can be so misleading, but as a relatively new user, I thought Rust was telling me that something in my code was trying to send a value between threads and additionally that the value actually couldn't be sent between threads safely.  Often times neither of those was the case.  You can easily generate this error with single-threaded code and concrete types that all implement `Send`.   In my case, often I'd forgotten to put `Send` on a trait bounds of the caller, or I'd erroneously put `Send` on a trait bound of the callee.  Really, this error is just a simple trait bound mismatch.  Just from my experience, it looks like this message is special-cased for `Send` in order to provide more useful information for someone who might not be familiar with `Send` -- which is great.  I think that information probably belongs in a "note" though, and the error should be precise about what actually happened instead of inferring too much (incorrectly, in some cases).

For trait bound mismatches involving types other than `Send`, the message is more precise:

```
use std::fmt::Debug;

trait TheTrait: Debug  {}
trait OtherTrait: Debug {}

#[derive(Debug)]
struct TheStruct {}
impl TheTrait for TheStruct {}

fn func1<T: TheTrait>(t: T)
{
    func2(t);
}

fn func2<T: OtherTrait>(t: T)
{
    eprintln!("{:?}", t);
}

fn main()
{
    let instance = TheStruct {};
    func1(instance);
}
```

Here's that example [in the playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=18b7138f639edba237b1295c5e7f615e).  The error message is:

```
error[E0277]: the trait bound `T: OtherTrait` is not satisfied
  --> src/main.rs:12:11
   |
10 | fn func1<T: TheTrait>(t: T)
   |          -- help: consider further restricting this bound: `T: OtherTrait +`
11 | {
12 |     func2(t);
   |           ^ the trait `OtherTrait` is not implemented for `T`
...
15 | fn func2<T: OtherTrait>(t: T)
   |    -----    ---------- required by this bound in `func2`
```

which is pretty clear and precise about the problem.  Here's a similar example where the trait bound is `Send`:

```
use std::fmt::Debug;

trait TheTrait: Debug  {}

#[derive(Debug)]
struct TheStruct {}
impl TheTrait for TheStruct {}

fn func1<T: TheTrait>(t: T)
{
    func2(t);
}

fn func2<T: TheTrait + Send>(t: T)
{
    eprintln!("{:?}", t);
}

fn main()
{
    let instance = TheStruct {};
    func1(instance);
}
```

Here's that one [on the playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=ff324fd5cf68b629b32e5490de6b7246).

Now the error message is:

```
error[E0277]: `T` cannot be sent between threads safely
  --> src/main.rs:11:11
   |
9  | fn func1<T: TheTrait>(t: T)
   |          -- help: consider further restricting this bound: `T: std::marker::Send +`
10 | {
11 |     func2(t);
   |           ^ `T` cannot be sent between threads safely
...
14 | fn func2<T: TheTrait + Send>(t: T)
   |    -----               ---- required by this bound in `func2`
   |
   = help: the trait `std::marker::Send` is not implemented for `T`
```

This is the same error code (E0277) and the "help" text is right but the summary message isn't.

### PR DESCRIPTION
**Pull request by estebank**
Some of the bound restriction structured suggestions were incorrect while others had subpar output.

The only issue left is a suggestion for an already present bound when dealing with `const`s that should be handled independently.

Fix #69983.

### CODE REVIEW

File: src/librustc_trait_selection/traits/error_reporting/mod.rs [hunk 1]
```diff
@@ -1840,55 +1824,44 @@ pub fn suggest_constraining_type_param(
...
 
-        let where_clause_span =
-            generics.where_clause.span_for_predicates_or_empty_place().shrink_to_hi();
+        let where_clause_span = generics.where_clause.span_for_predicates_or_empty_place();
+        // Account for `fn foo<T>(t: T) where T: Foo,` so we don't suggest two trailing commas.
+        let mut trailing_comma = false;
+        if let Ok(snippet) = tcx.sess.source_map().span_to_snippet(where_clause_span) {
+            if snippet.ends_with(",") {
+                trailing_comma = true;
+            }
```
Comment (Centril) [inline src/librustc_trait_selection/traits/error_reporting/mod.rs]:
```suggestion
                trailing_comma = snippet.ends_with(",");
```

File: src/librustc_trait_selection/traits/error_reporting/mod.rs [hunk 2]
```diff
@@ -1840,55 +1824,44 @@ pub fn suggest_constraining_type_param(
...
+        }
+        let where_clause_span = if trailing_comma {
+            let hi = where_clause_span.hi();
+            Span::new(hi - BytePos(1), hi, where_clause_span.ctxt())
```
Comment (Centril) [inline src/librustc_trait_selection/traits/error_reporting/mod.rs]: It would be good if we could write this as `span.offset_sub(1)` instead. Also, have you considered utf8 and stuff wrt. ICEs?

File: src/librustc_trait_selection/traits/error_reporting/suggestions.rs [hunk 3]
```diff
@@ -218,51 +218,29 @@ impl<'a, 'tcx> InferCtxtExt<'tcx> for InferCtxt<'a, 'tcx> {
...
                 })
                 | hir::Node::Item(hir::Item {
                     kind: hir::ItemKind::OpaqueTy(hir::OpaqueTy { generics, .. }),
-                    span,
                     ..
                 })
-                | hir::Node::TraitItem(hir::TraitItem { generics, span, .. })
-                | hir::Node::ImplItem(hir::ImplItem { generics, span, .. })
+                | hir::Node::TraitItem(hir::TraitItem { generics, .. })
+                | hir::Node::ImplItem(hir::ImplItem { generics, .. })
```
Comment (Centril) [inline src/librustc_trait_selection/traits/error_reporting/suggestions.rs]: Let's simplify this further with `#![feature(or_patterns)]` by moving the `|`s as much inwards as possible.

File: src/test/ui/associated-const/associated-const-type-parameter-arrays-2.stderr [hunk 4]
```diff
@@ -7,11 +7,10 @@ LL |     const Y: usize;
 LL |     let _array = [4; <A as Foo>::Y];
    |                      ^^^^^^^^^^^^^ the trait `Foo` is not implemented for `A`
    |
-help: consider further restricting this bound with `+ Foo`
-  --> $DIR/associated-const-type-parameter-arrays-2.rs:15:16
+help: consider further restricting this bound
    |
-LL | pub fn test<A: Foo, B: Foo>() {
-   |                ^^^
+LL | pub fn test<A: Foo + Foo, B: Foo>() {
```
Comment (Centril) [inline src/test/ui/associated-const/associated-const-type-parameter-arrays-2.stderr]: What's up with this duplicate bound here and below?

File: src/test/ui/closures/closure-bounds-subtype.stderr [hunk 5]
```diff
@@ -8,11 +8,10 @@ LL |     take_const_owned(f);
    |                      ^ `F` cannot be shared between threads safely
    |
    = help: the trait `std::marker::Sync` is not implemented for `F`
-help: consider further restricting this bound with `+ std::marker::Sync`
-  --> $DIR/closure-bounds-subtype.rs:11:30
+help: consider further restricting this bound
    |
-LL | fn give_owned<F>(f: F) where F: FnOnce() + Send {
-   |                              ^^^^^^^^^^^^^^^^^^
+LL | fn give_owned<F>(f: F) where F: FnOnce() + Send + std::marker::Sync {
```
Comment (Centril) [inline src/test/ui/closures/closure-bounds-subtype.stderr]: Could we check whether the path is in scope and strip the `std::marker::` bit? Happy to defer that to a follow up though!

File: src/librustc_trait_selection/traits/error_reporting/mod.rs (hunk 2 above)
Comment (estebank) [reply src/librustc_trait_selection/traits/error_reporting/mod.rs]: > Also, have you considered utf8 and stuff wrt. ICEs?

The only thing that could push that span is a `,` char, so this should never fail. (Famous last words.)

File: src/test/ui/associated-const/associated-const-type-parameter-arrays-2.stderr (hunk 4 above)
Comment (estebank) [reply src/test/ui/associated-const/associated-const-type-parameter-arrays-2.stderr]: This is a known issue when it comes to const context, particularly around array lenghts. I think it needs to be handled elsewhere in a general way and shouldn't be part of this PR.

File: src/test/ui/closures/closure-bounds-subtype.stderr (hunk 5 above)
Comment (estebank) [reply src/test/ui/closures/closure-bounds-subtype.stderr]: I would prefer to leave that for a different PR addressing referring to types with their locally known ident instead of adhoc for these suggestions only.

File: src/test/ui/associated-const/associated-const-type-parameter-arrays-2.stderr (hunk 4 above)
Comment (Centril) [reply src/test/ui/associated-const/associated-const-type-parameter-arrays-2.stderr]: Ah its that one... 👍

File: src/test/ui/closures/closure-bounds-subtype.stderr (hunk 5 above)
Comment (Centril) [reply src/test/ui/closures/closure-bounds-subtype.stderr]: Fair :)

File: src/librustc_trait_selection/traits/error_reporting/suggestions.rs [hunk 6]
```diff
@@ -206,63 +205,31 @@ impl<'a, 'tcx> InferCtxtExt<'tcx> for InferCtxt<'a, 'tcx> {
...
+                    | hir::Item { kind: hir::ItemKind::Enum(_, generics), .. }
+                    | hir::Item { kind: hir::ItemKind::Union(_, generics), .. }
+                    | hir::Item { kind: hir::ItemKind::Trait(_, _, generics, ..), .. }
+                    | hir::Item { kind: hir::ItemKind::Impl { generics, .. }, .. }
+                    | hir::Item { kind: hir::ItemKind::Fn(_, generics, _), .. }
+                    | hir::Item { kind: hir::ItemKind::TyAlias(_, generics), .. }
+                    | hir::Item { kind: hir::ItemKind::TraitAlias(generics, _), .. }
+                    | hir::Item {
+                        kind: hir::ItemKind::OpaqueTy(hir::OpaqueTy { generics, .. }), ..
+                    },
```
Comment (Centril) [inline src/librustc_trait_selection/traits/error_reporting/suggestions.rs]: nit: you can further simplify this by moving the or-pattern all the way into the `kind:` field-pattern (same above).

**Comment by Centril** [comment]
r=me with final nit addressed. :)

File: src/librustc_trait_selection/traits/error_reporting/suggestions.rs (hunk 6 above)
Comment (estebank) [reply src/librustc_trait_selection/traits/error_reporting/suggestions.rs]: I tried that first but I got a syntax error so I assumed it wasn't possible.

Comment (Centril) [reply src/librustc_trait_selection/traits/error_reporting/suggestions.rs]: Huh, that shouldn't happen... Let's merge this without and I'll see what's up with this myself.

**Comment by Centril** [comment]
Failed in https://github.com/rust-lang/rust/pull/70481#issuecomment-605325649, @bors r-

**Comment by estebank** [comment]
It seems like `--compare-mode=nll` discrepancy. Rebasing and fixing.
