### PR TITLE
Delay formatting trimmed path until lint/error is emitted

### LINKED ISSUE #99387: ICE: delayed_good_path_bugs: trimmed_def_paths constructed
### Code
code from glacier/fixed/70121.rs
```Rust
#![feature(type_alias_impl_trait)]
#![allow(private_in_public)]

pub type Successors<'a> = impl Iterator<Item = &'a ()>;

pub fn f<'a>() -> Successors<'a> {
    None.into_iter()
}

trait Tr {
    type Item;
}

impl<'a> Tr for &'a () {
    type Item = Successors<'a>;
}

pub fn ohno<'a>() -> <&'a () as Tr>::Item {
    None.into_iter()
}

fn main() {}
```

### Meta

`rustc --version --verbose`:
```
c2ecd3af87477147695aa3f6e1237e3185044e62 built with debug assertions
```

### Error output
`rustc ./70121.rs`
```

```
backtrace does not fit into a single comment :|

### PR DESCRIPTION
**Pull request by compiler-errors**
Fixes #99387

r? @davidtwco

### CODE REVIEW

File: compiler/rustc_privacy/src/errors.rs [hunk 1]
```diff
@@ -87,5 +90,13 @@ pub struct FromPrivateDependencyInPublicInterface<'a> {
 pub struct PrivateInPublicLint<'a> {
     pub vis_descr: &'static str,
     pub kind: &'a str,
-    pub descr: String,
+    pub descr: FromDisplay<'a>,
+}
+
+pub struct FromDisplay<'a>(pub &'a dyn Display);
```
Comment (davidtwco) [inline compiler/rustc_privacy/src/errors.rs:96]: We could put this in `rustc_errors` or wherever the other `IntoDiagnosticArg` impls are, it could be used more widely than just in `rustc_privacy`.

Comment (davidtwco) [inline compiler/rustc_privacy/src/errors.rs:96]: Do you think it would make sense to have an `Into` impl for anything that implements `Display`, and doing `field.into()` rather than using the constructor?

**Review by davidtwco — APPROVED** [review]
LGTM, one or two comments then feel free to r=me

File: compiler/rustc_privacy/src/errors.rs (hunk 1 above)
Comment (compiler-errors) [reply compiler/rustc_privacy/src/errors.rs:96]: That makes sense, yeah
