### PR TITLE
miri: lift restriction on extern types being the only field in a struct

### LINKED ISSUE #91827: ICE: Fields cannot be extern types, unless they are at offset 0
### Code

```Rust
#![feature(extern_types)]

extern "C" {
    type Content;
}

pub struct List {
    len: usize,
    _opaque: Content,
}

pub fn main() {
    let _len = match Option::<&List>::None {
        Some(a) => a.len,
        None => 0,
    };
}
```

### Meta

```
rustc 1.59.0-nightly (928783de6 2021-12-11)
```

### Error output

```
error: internal compiler error: /rustc/928783de663bd855a96f14b2d38c1061603587c6/compiler/rustc_const_eval/src/interpret/eval_context.rs:627:33: Fields cannot be extern types, unless they are at offset 0
  --> a.rs:13:22
   |
13 |     let _len = match Option::<&List>::None {
   |                      ^^^^^^^^^^^^^^^^^^^^^

thread 'rustc' panicked at 'Box<dyn Any>', /rustc/928783de663bd855a96f14b2d38c1061603587c6/compiler/rustc_errors/src/lib.rs:1116:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.59.0-nightly (928783de6 2021-12-11) running on x86_64-unknown-linux-gnu

query stack during panic:
#0 [optimized_mir] optimizing MIR for `main`
#1 [collect_and_partition_mono_items] collect_and_partition_mono_items
end of query stack
error: aborting due to previous error
```

### PR DESCRIPTION
**Pull request by tmiasko**
Fixes #91827.

r? @RalfJung

### CODE REVIEW

File: compiler/rustc_const_eval/src/interpret/eval_context.rs [hunk 1]
```diff
@@ -616,19 +616,11 @@ impl<'mir, 'tcx: 'mir, M: Machine<'mir, 'tcx>> InterpCx<'mir, 'tcx, M> {
                     match self.size_and_align_of(metadata, &field)? {
                         Some(size_and_align) => size_and_align,
                         None => {
-                            // A field with extern type.  If this field is at offset 0, we behave
-                            // like the underlying extern type.
+                            // A field with extern type. We behave like the underlying type.
```
Comment (RalfJung) [inline compiler/rustc_const_eval/src/interpret/eval_context.rs:619]: This comment certainly does not apply any more -- this referred to the fact that newtypes around extern type should work, but now with non-ZST fields that is not enough any more.

File: compiler/rustc_const_eval/src/interpret/place.rs [hunk 2]
```diff
@@ -364,17 +364,13 @@ where
             // happens at run-time so that's okay.
             let align = match self.size_and_align_of(&base.meta, &field_layout)? {
                 Some((_, align)) => align,
-                None if offset == Size::ZERO => {
-                    // An extern type at offset 0, we fall back to its static alignment.
+                None => {
+                    // An extern type, we fall back to its static alignment.
```
Comment (RalfJung) [inline compiler/rustc_const_eval/src/interpret/place.rs:368]: I have no idea if this is correct. Would be good to have a link to the equivalent code in codegen to make sure at least both sides are consistent here (and maybe add cross-references to ensure they remain consistent).

File: src/test/ui/consts/const-eval/issue-91827-extern-types.rs [hunk 3]
```diff
@@ -0,0 +1,58 @@
...
+pub static A_TAIL_OFFSET: isize = tail_offset(A.as_list());
+
+const fn tail_offset<T>(list: &'static List<T>) -> isize {
+    unsafe { (addr_of!(list.tail) as *const u8).offset_from(list as *const List<T> as *const u8) }
+}
+
+fn main() {
+    assert_eq!(A_REF.as_slice(), &[5, 6, 7]);
+    // Check that interpreter and code generation agree about the position of the tail field.
+    assert_eq!(A_TAIL_OFFSET, tail_offset(A_REF));
```
Comment (RalfJung) [inline src/test/ui/consts/const-eval/issue-91827-extern-types.rs:57]: Nice test. :)

I wonder if there are corner cases that make it more challenging, like newtype-wrapping `Opaque` in a `repr(align)` type to ensure it has alignment larger than `usize`?

File: compiler/rustc_const_eval/src/interpret/place.rs (hunk 2 above)
Comment (tmiasko) [reply compiler/rustc_const_eval/src/interpret/place.rs]: Oh, I thought I could just leave the existing fall back to the static alignment, presuming it would be effectively no-op, but that wouldn't be correct for packed representation. Fixed now.

The code generation implementation is in `PlaceRef::project_field`. It checks for the extra metadata first and when metadata is absent it performs no additional adjustments.

File: compiler/rustc_const_eval/src/interpret/eval_context.rs [hunk 4]
```diff
@@ -616,19 +616,12 @@ impl<'mir, 'tcx: 'mir, M: Machine<'mir, 'tcx>> InterpCx<'mir, 'tcx, M> {
                     match self.size_and_align_of(metadata, &field)? {
                         Some(size_and_align) => size_and_align,
                         None => {
-                            // A field with extern type.  If this field is at offset 0, we behave
-                            // like the underlying extern type.
+                            // A field with an extern type. We don't know the actual dynamic size
+                            // or the alignment.
                             // FIXME: Once we have made decisions for how to handle size and alignment
                             // of `extern type`, this should be adapted.  It is just a temporary hack
                             // to get some code to work that probably ought to work.
```
Comment (RalfJung) [inline compiler/rustc_const_eval/src/interpret/eval_context.rs:623]:
```suggestion
```

File: compiler/rustc_const_eval/src/interpret/place.rs [hunk 5]
```diff
@@ -362,21 +362,16 @@ where
...
-                Some((_, align)) => align,
-                None if offset == Size::ZERO => {
-                    // An extern type at offset 0, we fall back to its static alignment.
+            match self.size_and_align_of(&base.meta, &field_layout)? {
+                Some((_, align)) => (base.meta, offset.align_to(align)),
+                None => {
+                    // For unsized types with an extern type tail we perform no adjustments.
                     // FIXME: Once we have made decisions for how to handle size and alignment
                     // of `extern type`, this should be adapted.  It is just a temporary hack
                     // to get some code to work that probably ought to work.
```
Comment (RalfJung) [inline compiler/rustc_const_eval/src/interpret/place.rs:371]:
```suggestion
                    // NOTE: keep this in sync with `PlaceRef::project_field` in the codegen backend.
```

File: compiler/rustc_const_eval/src/interpret/place.rs [hunk 6]
```diff
@@ -362,21 +362,16 @@ where
...
-                    field_layout.align.abi
+                    (base.meta, offset)
```
Comment (RalfJung) [inline compiler/rustc_const_eval/src/interpret/place.rs:372]: If we repeat the `base.meta` thing, we might as well add an assertion here that in the `None` arm, `matches!(base.meta, MemPlaceMeta::None)`

**Comment by RalfJung** [comment]
Thanks!
@bors r+
