### PR TITLE
Use `next_point` to avoid ICE

### LINKED ISSUE #68730: assertion failed: bpos.to_u32() >= mbc.pos.to_u32() + mbc.bytes as u32
I'm seeing an internal compiler error on the following input (found by [fuzz-rustc](https://github.com/dwrensha/fuzz-rustc)):

```
$ echo ZW51bQBlbQDLgsuC | base64 --decode > main.rs
$ rustc main.rs
error: unknown start of token: \u{0}
 --> main.rs:1:5
  |
1 | enumem˂˂
  |     ^

error: unknown start of token: \u{0}
 --> main.rs:1:8
  |
1 | enumem˂˂
  |       ^

error: unknown start of token: \u{2c2}
 --> main.rs:1:9
  |
1 | enumem˂˂
  |       ^
  |
help: Unicode character '˂' (Modifier Letter Left Arrowhead) looks like '<' (Less-Than Sign), but it is not
  |
1 | enumem<˂
  |       ^

error: unknown start of token: \u{2c2}
 --> main.rs:1:10
  |
1 | enumem˂˂
  |        ^
  |
help: Unicode character '˂' (Modifier Letter Left Arrowhead) looks like '<' (Less-Than Sign), but it is not
  |
1 | enumem˂<
  |        ^

thread 'rustc' panicked at 'assertion failed: bpos.to_u32() >= mbc.pos.to_u32() + mbc.bytes as u32', src/librustc_span/source_map.rs:840:17
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.42.0-nightly (cd1ef390e 2020-01-31) running on x86_64-unknown-linux-gnu

error: aborting due to 4 previous errors
```

The same error happens on `stable`, `beta`, and `nightly`.

### PR DESCRIPTION
**Pull request by JohnTitor**
Fixes #68730

r? @estebank (I think you're familiar with that)

### CODE REVIEW

File: src/librustc_parse/parser/mod.rs [hunk 1]
```diff
@@ -671,12 +671,12 @@ impl<'a> Parser<'a> {
                 true
             }
             token::BinOp(token::Shl) => {
-                let span = self.token.span.with_lo(self.token.span.lo() + BytePos(1));
```
Comment (dwrensha) [inline src/librustc_parse/parser/mod.rs]: I see a bunch of other instances of `self.token.span.lo() + BytePos(1)` in this file. Should they be updated too?

Comment (JohnTitor) [reply src/librustc_parse/parser/mod.rs]: I'm fine to do so if @estebank also agrees with that.

Comment (JohnTitor) [reply src/librustc_parse/parser/mod.rs]: Uhm, I found out it shouldn't, it'll break many spans.

Comment (estebank) [reply src/librustc_parse/parser/mod.rs]: What kind of breakage occurs?

**Comment by estebank** [comment]
I'm +1 r=me on the change as is, but if we can avoid the other `+ BytePos(1)` usages throughout we'll get ahead of any potential lurking ICEs.

File: src/librustc_parse/parser/mod.rs (hunk 1 above)
Comment (JohnTitor) [reply src/librustc_parse/parser/mod.rs]: Indeed we can use `next_ponit` for `eat_plus` but it seems to cause breakage in other places (`expect_and`, `expect_or`, and `expect_gt`). It will expand or reduce current span size.

Comment (JohnTitor) [reply src/librustc_parse/parser/mod.rs]: I guess we should also tweak later `bump_with`s?

Comment (estebank) [reply src/librustc_parse/parser/mod.rs]: Can you file a ticket to follow up on this?

Comment (JohnTitor) [reply src/librustc_parse/parser/mod.rs]: Filed as #68783.
