### PR TITLE
Ensure that THIR unsafety check is done before stealing it

### LINKED ISSUE #111520: ICE: parallel compiler: `attempted to read from stolen value: rustc_middle::thir::Thir` : `-Zthir-unsafeck=yes`
### Code
you need parallel compiler config  to reproduce this!

`rustc -Zthreads=300  -ooutputfile   -Zthir-unsafeck=yes -Zdump-mir-dir=a file.rs`

```Rust
// FamilyType (GAT workaround)
pub trait FamilyLt<'a> {
    type Out;
}

struct RefMutFamily<T>(std::marker::PhantomData<T>, ());
impl<'a, T: 'a> FamilyLt<'a> for RefMutFamily<T> {
    type Out = &'a mut T;
}

pub trait Execute {
    type E: Inject;
    fn execute(self, value: <<Self::E as Inject>::I as FamilyLt>::Out);
}

pub trait Inject
where
    Self: Sized,
{
    type I: for<'a> FamilyLt<'a>;
    fn inject(_: &()) -> <Self::I as FamilyLt>::Out;
}

impl<T: 'static> Inject for RefMutFamily<T> {
    type I = Self;
    fn inject(_: &()) -> <Self::I as FamilyLt>::Out {
        unimplemented!()
    }
}

// This struct is only used to give a hint to the compiler about the type `Q`
struct Annotate<Q>(std::marker::PhantomData<Q>);
impl<Q> Annotate<Q> {
    fn new() -> Self {
        Self(std::marker::PhantomData)
    }
}

// This function annotate a closure so it can have Higher-Rank Lifetime Bounds
//
// See 'annotate' workaround: https://github.com/rust-lang/rust/issues/58052
fn annotate<F, Q>(_q: Annotate<Q>, func: F) -> impl Execute + 'static
where
    F: for<'r> FnOnce(<<Q as Inject>::I as FamilyLt<'r>>::Out) + 'static,
    Q: Inject + 'static,
{
    let wrapper: Wrapper<Q, F> = Wrapper(std::marker::PhantomData, func);
    wrapper
}

struct Wrapper<Q, F>(std::marker::PhantomData<Q>, F);
impl<Q, F> Execute for Wrapper<Q, F>
    where
        Q: Inject,
        F: for<'r> FnOnce(<<Q as Inject>::I as FamilyLt<'r>>::Out),
{
    type E = Q;

    fn execute(self, value: <<Self::E as Inject>::I as FamilyLt>::Out) {
        (self.1)(value)
    }
}

struct Task {
    _processor: Box<dyn FnOnce()>,
}

// This function consume the closure
fn task<P>(processor: P) -> Task
where P: Execute + 'static {
    Task {
        _processor: Box::new(move || {
            let q = P::E::inject(&());
            processor.execute(q);
        })
    }
}

fn main() {
    task(annotate(
        Annotate::<RefMutFamily<usize>>::new(),
        |value: &mut usize| {
            *value = 2;
        }
    ));
}
```

### Meta

`rustc --version --verbose`:
```
<version>
```

### Error output

```
4a59ba4d54a3ec0d8ea1e82b7eeb5c8b0162de04
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
<backtrace>
```

</p>
</details>

### PR DESCRIPTION
**Pull request by Zoxc**
This ensures that THIR unsafety check is done before stealing it by running it on the typeck root instead of on a closure, which does nothing.

Fixes https://github.com/rust-lang/rust/issues/111520

### CODE REVIEW

File: compiler/rustc_mir_build/src/build/mod.rs [hunk 1]
```diff
@@ -56,7 +56,8 @@ pub(crate) fn closure_saved_names_of_captured_variables<'tcx>(
 /// Construct the MIR for a given `DefId`.
 fn mir_build(tcx: TyCtxt<'_>, def: LocalDefId) -> Body<'_> {
     // Ensure unsafeck and abstract const building is ran before we steal the THIR.
-    tcx.ensure_with_value().thir_check_unsafety(def);
+    tcx.ensure_with_value()
```
Comment (compiler-errors) [inline compiler/rustc_mir_build/src/build/mod.rs:59]: Unrelated to this PR, but why is this `ensure_with_value` :thinking:

File: compiler/rustc_mir_build/src/build/mod.rs [hunk 2]
```diff
@@ -56,7 +56,8 @@ pub(crate) fn closure_saved_names_of_captured_variables<'tcx>(
...
+        .thir_check_unsafety(tcx.typeck_root_def_id(def.to_def_id()).as_local().unwrap());
```
Comment (compiler-errors) [inline compiler/rustc_mir_build/src/build/mod.rs:60]: nit:

```suggestion
        .thir_check_unsafety(tcx.typeck_root_def_id(def.to_def_id()).expect_local());
```

File: compiler/rustc_mir_build/src/build/mod.rs (hunk 1 above)
Comment (cjgillot) [reply compiler/rustc_mir_build/src/build/mod.rs:59]: `ensure` verifies that the dependency is green, without computing anything if not required.
This means that a query that is `ensure`d may need to be computed later if some code needs the result value.

`ensure_with_value` verifies that the result is available, computed or loadable from on-disk cache.

Comment (Zoxc) [reply compiler/rustc_mir_build/src/build/mod.rs:59]: Hm.. this means that query side effects can be emitted twice? Once when marking a query green and once when executing the query later to recover the value. I guess we need to make sure that's benign.

Comment (cjgillot) [reply compiler/rustc_mir_build/src/build/mod.rs:59]: This is ok for diagnostics, as they are deduplicated. But this is a blocker for replaying any other side-effect. I've been trying to fix this to re-create DefId, but I'm not satisfied by my design.

File: compiler/rustc_mir_build/src/build/mod.rs (hunk 2 above)
Comment (Zoxc) [reply compiler/rustc_mir_build/src/build/mod.rs]: Applied.

File: compiler/rustc_mir_build/src/build/mod.rs (hunk 1 above)
Comment (Zoxc) [reply compiler/rustc_mir_build/src/build/mod.rs:59]: There's an option to turn it off though. There's also extra logic for the parallel compiler to avoid emitting side effects multiple times, which is kind of unnecessary then.

How does DefId relate to this?

Representing side effects as forcible queries would avoid this issue, but does require work to support forcing arbitrary keys.

**Comment by Zoxc** [comment]
Retry? Looks to be some CI issue?
