### PR TITLE
Store the type of each GVN value

### LINKED ISSUE #128094: `Result::unwrap()` on an `Err` value: ReferencesError(ErrorGuaranteed(()))
auto-reduced (treereduce-rust):
````rust
pub enum Request {
    TestSome(T),
}

pub async fn handle_event(event: Request) {
    async move {
        static instance: Request = Request { bar: 17 };
        &instance
    }
    .await;
}


````

original:
````rust
pub enum Request {
    TestSome(T),
}

pub async fn handle_event(
    event: Request,
)  {
    async move {
    static instance: Request = Request { bar: 17 };
    &instance
}.await;
}

pub fn main() {}

````

Version information
````
rustc 1.82.0-nightly (49649bf3c 2024-07-23)
binary: rustc
commit-hash: 49649bf3c5538531ade6834b9b308a6c8a5f3e8e
commit-date: 2024-07-23
host: x86_64-unknown-linux-gnu
release: 1.82.0-nightly
LLVM version: 18.1.7

````

Command:
`/home/matthias/.rustup/toolchains/master/bin/rustc -Zmir-opt-level=5 --edition=2018`

<details><summary><strong>Program output</strong></summary>
<p>

```
error[E0412]: cannot find type `T` in this scope
 --> /tmp/icemaker_global_tempdir.7wIEjd0lKecw/rustc_testrunner_tmpdir_reporting.168IfbM3nYxW/mvce.rs:2:14
  |
2 |     TestSome(T),
  |              ^ not found in this scope
  |
help: you might be missing a type parameter
  |
1 | pub enum Request<T> {
  |                 +++

error[E0574]: expected struct, variant or union type, found enum `Request`
 --> /tmp/icemaker_global_tempdir.7wIEjd0lKecw/rustc_testrunner_tmpdir_reporting.168IfbM3nYxW/mvce.rs:7:36
  |
7 |         static instance: Request = Request { bar: 17 };
  |                                    ^^^^^^^ not a struct, variant or union type
  |
help: consider importing this struct instead
  |
1 + use std::error::Request;
  |

error[E0601]: `main` function not found in crate `mvce`
  --> /tmp/icemaker_global_tempdir.7wIEjd0lKecw/rustc_testrunner_tmpdir_reporting.168IfbM3nYxW/mvce.rs:11:2
   |
11 | }
   |  ^ consider adding a `main` function to `/tmp/icemaker_global_tempdir.7wIEjd0lKecw/rustc_testrunner_tmpdir_reporting.168IfbM3nYxW/mvce.rs`

warning: unused variable: `event`
 --> /tmp/icemaker_global_tempdir.7wIEjd0lKecw/rustc_testrunner_tmpdir_reporting.168IfbM3nYxW/mvce.rs:5:27
  |
5 | pub async fn handle_event(event: Request) {
  |                           ^^^^^ help: if this is intentional, prefix it with an underscore: `_event`
  |
  = note: `#[warn(unused_variables)]` on by default

thread 'rustc' panicked at /rustc/49649bf3c5538531ade6834b9b308a6c8a5f3e8e/compiler/rustc_const_eval/src/interpret/memory.rs:819:80:
called `Result::unwrap()` on an `Err` value: ReferencesError(ErrorGuaranteed(()))
stack backtrace:
   0:     0x7aca857e8215 - std::backtrace_rs::backtrace::libunwind::trace::h2d3a238147fe4644
                               at /rustc/49649bf3c5538531ade6834b9b308a6c8a5f3e8e/library/std/src/../../backtrace/src/backtrace/libunwind.rs:116:5
   1:     0x7aca857e8215 - std::backtrace_rs::backtrace::trace_unsynchronized::h62ccd1746707818d
                               at /rustc/49649bf3c5538531ade6834b9b308a6c8a5f3e8e/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7aca857e8215 - std::sys::backtrace::_print_fmt::h198764e2cd3756f6
                               at /rustc/49649bf3c5538531ade6834b9b308a6c8a5f3e8e/library/std/src/sys/backtrace.rs:65:5
   3:     0x7aca857e8215 - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::h8efb4db36089f8d1
                               at /rustc/49649bf3c5538531ade6834b9b308a6c8a5f3e8e/library/std/src/sys/backtrace.rs:40:26
   4:     0x7aca85837c8b - core::fmt::rt::Argument::fmt::h32cf5a418db2846f
                               at /rustc/49649bf3c5538531ade6834b9b308a6c8a5f3e8e/library/core/src/fmt/rt.rs:173:76
   5:     0x7aca85837c8b - core::fmt::write::hd634bfe95aa2d191
                               at /rustc/49649bf3c5538531ade6834b9b308a6c8a5f3e8e/library/core/src/fmt/mod.rs:1182:21
   6:     0x7aca857dccef - std::io::Write::write_fmt::h18d00a47d2edb63e
                               at /rustc/49649bf3c5538531ade6834b9b308a6c8a5f3e8e/library/std/src/io/mod.rs:1827:15
   7:     0x7aca857eaa01 - std::sys::backtrace::BacktraceLock::print::hdf53fb28966ef7ad
                               at /rustc/49649bf3c5538531ade6834b9b308a6c8a5f3e8e/library/std/src/sys/backtrace.rs:43:9
   8:     0x7aca857eaa01 - std::panicking::default_hook::{{closure}}::h6dc27f9ba326a601
                               at /rustc/49649bf3c5538531ade6834b9b308a6c8a5f3e8e/library/std/src/panicking.rs:269:22
   9:     0x7aca857ea6dc - std::panicking::default_hook::h9dbf01c0a905b2fb
                               at /rustc/49649bf3c5538531ade6834b9b308a6c8a5f3e8e/library/std/src/panicking.rs:296:9
  10:     0x7aca81c1e709 - std[84685e2f5e49534c]::panicking::update_hook::<alloc[69d17d5c7a222efa]::boxed::Box<rustc_driver_impl[2ca809430a6bb1db]::install_ice_hook::{closure#0}>>::{closure#0}
  11:     0x7aca857eb3cf - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h2926931e5fae8e54
                               at /rustc/49649bf3c5538531ade6834b9b308a6c8a5f3e8e/library/alloc/src/boxed.rs:2163:9
  12:     0x7aca857eb3cf - std::panicking::rust_panic_with_hook::ha943b79683377534
                               at /rustc/49649bf3c5538531ade6834b9b308a6c8a5f3e8e/library/std/src/panicking.rs:808:13
  13:     0x7aca857eaff7 - std::panicking::begin_panic_handler::{{closure}}::hb948fc2cd41a6d5c
                               at /rustc/49649bf3c5538531ade6834b9b308a6c8a5f3e8e/library/std/src/panicking.rs:674:13
  14:     0x7aca857e86d9 - std::sys::backtrace::__rust_end_short_backtrace::h82feed5209c926ba
                               at /rustc/49649bf3c5538531ade6834b9b308a6c8a5f3e8e/library/std/src/sys/backtrace.rs:168:18
  15:     0x7aca857eac84 - rust_begin_unwind
                               at /rustc/49649bf3c5538531ade6834b9b308a6c8a5f3e8e/library/std/src/panicking.rs:665:5
  16:     0x7aca85834243 - core::panicking::panic_fmt::ha0806b6370825159
                               at /rustc/49649bf3c5538531ade6834b9b308a6c8a5f3e8e/library/core/src/panicking.rs:74:14
  17:     0x7aca85834896 - core::result::unwrap_failed::h4fc72d8e11c69246
                               at /rustc/49649bf3c5538531ade6834b9b308a6c8a5f3e8e/library/core/src/result.rs:1679:5
  18:     0x7aca84a6478f - <rustc_const_eval[bdbbaff3c31c13f6]::interpret::eval_context::InterpCx<rustc_const_eval[bdbbaff3c31c13f6]::const_eval::dummy_machine::DummyMachine>>::get_alloc_info.cold
  19:     0x7aca83cf0dfa - <rustc_const_eval[bdbbaff3c31c13f6]::interpret::eval_context::InterpCx<rustc_const_eval[bdbbaff3c31c13f6]::const_eval::dummy_machine::DummyMachine>>::scalar_may_be_null
  20:     0x7aca83cf08a4 - <rustc_const_eval[bdbbaff3c31c13f6]::interpret::eval_context::InterpCx<rustc_const_eval[bdbbaff3c31c13f6]::const_eval::dummy_machine::DummyMachine>>::read_discriminant::<rustc_const_eval[bdbbaff3c31c13f6]::interpret::operand::OpTy>
  21:     0x7aca83ce8cee - <rustc_mir_transform[48c5b07b6fa30cb7]::gvn::VnState>::insert
  22:     0x7aca83ce2524 - <rustc_mir_transform[48c5b07b6fa30cb7]::gvn::VnState>::simplify_rvalue
  23:     0x7aca80d2d468 - <rustc_mir_transform[48c5b07b6fa30cb7]::gvn::GVN as rustc_middle[f06a2f49cb923fa3]::mir::MirPass>::run_pass
  24:     0x7aca83201c7b - rustc_mir_transform[48c5b07b6fa30cb7]::pass_manager::run_passes_inner
  25:     0x7aca837d9256 - rustc_mir_transform[48c5b07b6fa30cb7]::optimized_mir
  26:     0x7aca8409185d - rustc_query_impl[3f261a864a124585]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[3f261a864a124585]::query_impl::optimized_mir::dynamic_query::{closure#2}::{closure#0}, rustc_middle[f06a2f49cb923fa3]::query::erase::Erased<[u8; 8usize]>>
  27:     0x7aca8348a857 - rustc_query_system[85f7d4985ebc0774]::query::plumbing::try_execute_query::<rustc_query_impl[3f261a864a124585]::DynamicConfig<rustc_query_system[85f7d4985ebc0774]::query::caches::DefIdCache<rustc_middle[f06a2f49cb923fa3]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[3f261a864a124585]::plumbing::QueryCtxt, false>
  28:     0x7aca8348a034 - rustc_query_impl[3f261a864a124585]::query_impl::optimized_mir::get_query_non_incr::__rust_end_short_backtrace
  29:     0x7aca833b2457 - rustc_middle[f06a2f49cb923fa3]::query::plumbing::query_get_at::<rustc_query_system[85f7d4985ebc0774]::query::caches::DefIdCache<rustc_middle[f06a2f49cb923fa3]::query::erase::Erased<[u8; 8usize]>>>
  30:     0x7aca82209fc0 - <rustc_middle[f06a2f49cb923fa3]::ty::context::TyCtxt>::coroutine_layout
  31:     0x7aca838254e2 - rustc_ty_utils[4b3be0d27c5e9905]::layout::layout_of_uncached
  32:     0x7aca8381444b - rustc_ty_utils[4b3be0d27c5e9905]::layout::layout_of
  33:     0x7aca838143d1 - rustc_query_impl[3f261a864a124585]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[3f261a864a124585]::query_impl::layout_of::dynamic_query::{closure#2}::{closure#0}, rustc_middle[f06a2f49cb923fa3]::query::erase::Erased<[u8; 16usize]>>
  34:     0x7aca838136d0 - rustc_query_system[85f7d4985ebc0774]::query::plumbing::try_execute_query::<rustc_query_impl[3f261a864a124585]::DynamicConfig<rustc_query_system[85f7d4985ebc0774]::query::caches::DefaultCache<rustc_middle[f06a2f49cb923fa3]::ty::ParamEnvAnd<rustc_middle[f06a2f49cb923fa3]::ty::Ty>, rustc_middle[f06a2f49cb923fa3]::query::erase::Erased<[u8; 16usize]>>, false, true, false>, rustc_query_impl[3f261a864a124585]::plumbing::QueryCtxt, false>
  35:     0x7aca8381336f - rustc_query_impl[3f261a864a124585]::query_impl::layout_of::get_query_non_incr::__rust_end_short_backtrace
  36:     0x7aca83ce6a56 - rustc_middle[f06a2f49cb923fa3]::query::plumbing::query_get_at::<rustc_query_system[85f7d4985ebc0774]::query::caches::DefaultCache<rustc_middle[f06a2f49cb923fa3]::ty::ParamEnvAnd<rustc_middle[f06a2f49cb923fa3]::ty::Ty>, rustc_middle[f06a2f49cb923fa3]::query::erase::Erased<[u8; 16usize]>>>
  37:     0x7aca83ce824e - <rustc_mir_transform[48c5b07b6fa30cb7]::gvn::VnState>::insert
  38:     0x7aca83ce2524 - <rustc_mir_transform[48c5b07b6fa30cb7]::gvn::VnState>::simplify_rvalue
  39:     0x7aca80d2d468 - <rustc_mir_transform[48c5b07b6fa30cb7]::gvn::GVN as rustc_middle[f06a2f49cb923fa3]::mir::MirPass>::run_pass
  40:     0x7aca83201c7b - rustc_mir_transform[48c5b07b6fa30cb7]::pass_manager::run_passes_inner
  41:     0x7aca837d9256 - rustc_mir_transform[48c5b07b6fa30cb7]::optimized_mir
  42:     0x7aca8409185d - rustc_query_impl[3f261a864a124585]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[3f261a864a124585]::query_impl::optimized_mir::dynamic_query::{closure#2}::{closure#0}, rustc_middle[f06a2f49cb923fa3]::query::erase::Erased<[u8; 8usize]>>
  43:     0x7aca8348a857 - rustc_query_system[85f7d4985ebc0774]::query::plumbing::try_execute_query::<rustc_query_impl[3f261a864a124585]::DynamicConfig<rustc_query_system[85f7d4985ebc0774]::query::caches::DefIdCache<rustc_middle[f06a2f49cb923fa3]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[3f261a864a124585]::plumbing::QueryCtxt, false>
  44:     0x7aca8348a034 - rustc_query_impl[3f261a864a124585]::query_impl::optimized_mir::get_query_non_incr::__rust_end_short_backtrace
  45:     0x7aca833b2457 - rustc_middle[f06a2f49cb923fa3]::query::plumbing::query_get_at::<rustc_query_system[85f7d4985ebc0774]::query::caches::DefIdCache<rustc_middle[f06a2f49cb923fa3]::query::erase::Erased<[u8; 8usize]>>>
  46:     0x7aca82209fc0 - <rustc_middle[f06a2f49cb923fa3]::ty::context::TyCtxt>::coroutine_layout
  47:     0x7aca838254e2 - rustc_ty_utils[4b3be0d27c5e9905]::layout::layout_of_uncached
  48:     0x7aca8381444b - rustc_ty_utils[4b3be0d27c5e9905]::layout::layout_of
  49:     0x7aca838143d1 - rustc_query_impl[3f261a864a124585]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[3f261a864a124585]::query_impl::layout_of::dynamic_query::{closure#2}::{closure#0}, rustc_middle[f06a2f49cb923fa3]::query::erase::Erased<[u8; 16usize]>>
  50:     0x7aca838136d0 - rustc_query_system[85f7d4985ebc0774]::query::plumbing::try_execute_query::<rustc_query_impl[3f261a864a124585]::DynamicConfig<rustc_query_system[85f7d4985ebc0774]::query::caches::DefaultCache<rustc_middle[f06a2f49cb923fa3]::ty::ParamEnvAnd<rustc_middle[f06a2f49cb923fa3]::ty::Ty>, rustc_middle[f06a2f49cb923fa3]::query::erase::Erased<[u8; 16usize]>>, false, true, false>, rustc_query_impl[3f261a864a124585]::plumbing::QueryCtxt, false>
  51:     0x7aca8381336f - rustc_query_impl[3f261a864a124585]::query_impl::layout_of::get_query_non_incr::__rust_end_short_backtrace
  52:     0x7aca808e0b67 - <rustc_mir_transform[48c5b07b6fa30cb7]::known_panics_lint::KnownPanicsLint as rustc_mir_transform[48c5b07b6fa30cb7]::pass_manager::MirLint>::run_lint
  53:     0x7aca83201c7b - rustc_mir_transform[48c5b07b6fa30cb7]::pass_manager::run_passes_inner
  54:     0x7aca83a13f29 - rustc_mir_transform[48c5b07b6fa30cb7]::mir_drops_elaborated_and_const_checked
  55:     0x7aca83a137fd - rustc_query_impl[3f261a864a124585]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[3f261a864a124585]::query_impl::mir_drops_elaborated_and_const_checked::dynamic_query::{closure#2}::{closure#0}, rustc_middle[f06a2f49cb923fa3]::query::erase::Erased<[u8; 8usize]>>
  56:     0x7aca834b0eb3 - rustc_query_system[85f7d4985ebc0774]::query::plumbing::try_execute_query::<rustc_query_impl[3f261a864a124585]::DynamicConfig<rustc_query_system[85f7d4985ebc0774]::query::caches::VecCache<rustc_span[b5058cd9cdbacc64]::def_id::LocalDefId, rustc_middle[f06a2f49cb923fa3]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[3f261a864a124585]::plumbing::QueryCtxt, false>
  57:     0x7aca834b0859 - rustc_query_impl[3f261a864a124585]::query_impl::mir_drops_elaborated_and_const_checked::get_query_non_incr::__rust_end_short_backtrace
  58:     0x7aca83a20318 - rustc_interface[4a5f03b368ced297]::passes::analysis
  59:     0x7aca83a1f21b - rustc_query_impl[3f261a864a124585]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[3f261a864a124585]::query_impl::analysis::dynamic_query::{closure#2}::{closure#0}, rustc_middle[f06a2f49cb923fa3]::query::erase::Erased<[u8; 1usize]>>
  60:     0x7aca840d96a5 - rustc_query_system[85f7d4985ebc0774]::query::plumbing::try_execute_query::<rustc_query_impl[3f261a864a124585]::DynamicConfig<rustc_query_system[85f7d4985ebc0774]::query::caches::SingleCache<rustc_middle[f06a2f49cb923fa3]::query::erase::Erased<[u8; 1usize]>>, false, false, false>, rustc_query_impl[3f261a864a124585]::plumbing::QueryCtxt, false>
  61:     0x7aca840d940f - rustc_query_impl[3f261a864a124585]::query_impl::analysis::get_query_non_incr::__rust_end_short_backtrace
  62:     0x7aca83fce6c5 - rustc_interface[4a5f03b368ced297]::interface::run_compiler::<core[c37d915429d9bf38]::result::Result<(), rustc_span[b5058cd9cdbacc64]::ErrorGuaranteed>, rustc_driver_impl[2ca809430a6bb1db]::run_compiler::{closure#0}>::{closure#1}
  63:     0x7aca83fb51c9 - std[84685e2f5e49534c]::sys::backtrace::__rust_begin_short_backtrace::<rustc_interface[4a5f03b368ced297]::util::run_in_thread_with_globals<rustc_interface[4a5f03b368ced297]::util::run_in_thread_pool_with_globals<rustc_interface[4a5f03b368ced297]::interface::run_compiler<core[c37d915429d9bf38]::result::Result<(), rustc_span[b5058cd9cdbacc64]::ErrorGuaranteed>, rustc_driver_impl[2ca809430a6bb1db]::run_compiler::{closure#0}>::{closure#1}, core[c37d915429d9bf38]::result::Result<(), rustc_span[b5058cd9cdbacc64]::ErrorGuaranteed>>::{closure#0}, core[c37d915429d9bf38]::result::Result<(), rustc_span[b5058cd9cdbacc64]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[c37d915429d9bf38]::result::Result<(), rustc_span[b5058cd9cdbacc64]::ErrorGuaranteed>>
  64:     0x7aca83fb4f7a - <<std[84685e2f5e49534c]::thread::Builder>::spawn_unchecked_<rustc_interface[4a5f03b368ced297]::util::run_in_thread_with_globals<rustc_interface[4a5f03b368ced297]::util::run_in_thread_pool_with_globals<rustc_interface[4a5f03b368ced297]::interface::run_compiler<core[c37d915429d9bf38]::result::Result<(), rustc_span[b5058cd9cdbacc64]::ErrorGuaranteed>, rustc_driver_impl[2ca809430a6bb1db]::run_compiler::{closure#0}>::{closure#1}, core[c37d915429d9bf38]::result::Result<(), rustc_span[b5058cd9cdbacc64]::ErrorGuaranteed>>::{closure#0}, core[c37d915429d9bf38]::result::Result<(), rustc_span[b5058cd9cdbacc64]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[c37d915429d9bf38]::result::Result<(), rustc_span[b5058cd9cdbacc64]::ErrorGuaranteed>>::{closure#1} as core[c37d915429d9bf38]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  65:     0x7aca857f542b - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hb5e78d42d6801749
                               at /rustc/49649bf3c5538531ade6834b9b308a6c8a5f3e8e/library/alloc/src/boxed.rs:2149:9
  66:     0x7aca857f542b - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hd9416e19f44d968d
                               at /rustc/49649bf3c5538531ade6834b9b308a6c8a5f3e8e/library/alloc/src/boxed.rs:2149:9
  67:     0x7aca857f542b - std::sys::pal::unix::thread::Thread::new::thread_start::he0388d99656ed7ca
                               at /rustc/49649bf3c5538531ade6834b9b308a6c8a5f3e8e/library/std/src/sys/pal/unix/thread.rs:108:17
  68:     0x7aca7e6a6ded - <unknown>
  69:     0x7aca7e72a0dc - <unknown>
  70:                0x0 - <unknown>

error: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: please make sure that you have updated to the latest nightly

note: rustc 1.82.0-nightly (49649bf3c 2024-07-23) running on x86_64-unknown-linux-gnu

note: compiler flags: -Z mir-opt-level=5 -Z dump-mir-dir=dir

query stack during panic:
#0 [optimized_mir] optimizing MIR for `handle_event::{closure#0}::{closure#0}`
#1 [layout_of] computing layout of `{async block@/tmp/icemaker_global_tempdir.7wIEjd0lKecw/rustc_testrunner_tmpdir_reporting.168IfbM3nYxW/mvce.rs:6:5: 6:15}`
end of query stack
error: aborting due to 3 previous errors; 1 warning emitted

Some errors have detailed explanations: E0412, E0574, E0601.
For more information about an error, try `rustc --explain E0412`.

```

</p>
</details>

### LINKED ISSUE #135128: [ICE]: Both stable and nightly crash at `compiler/rustc_const_eval/src/interpret/operand.rs:84:42` on the invalid code under `opt-level=3`
### Code

```Rust
#![allow(unused)]
#![allow(type_alias_bounds)]
pub trait Foo {
    fn test(&self);
}
async fn generic_function<'g, X: Foo>(x: &'g X) {}
enum E
where
    i32: Foo,
{
    V,
}
struct S
where
    i32: Foo;
trait T where
    i32: Foo,
{
}
union U
where
    i32: Foo,
{
    f: i32,
}
type Y
where
    i32: Foo,
= ();
impl Foo for ()
where
    i32: Foo,
{
    fn test(&self) {
        3i32.test();
        Foo::test(&4i32);
        generic_function(5i32);
    }
}
async fn f()
where
    i32: Foo,
{
    let s = S;
    3i32.test();
    Foo::test(&4i32);
    generic_function(5i32);
}
async fn use_op<'g>(s: &'g String) -> String
where
    String: ::std::ops::Neg<Output = String>,
{
    -s
}
async fn use_for()
where
    i32: Iterator,
{
    for _ in 2i32 {}
}
trait A {}
impl A for i32 {}
struct Dst {
    x: X,
}
struct TwoStrs(str, str)
where
    str: Sized;
async fn unsized_local()
where
    Dst<dyn A>: Sized,
{
    let x: Dst<dyn A> = *(Box::new(Dst { x: 1 }) as Box<Dst<dyn A>>);
}
async fn return_str() -> str
where
    str: Sized,
{
    *"Sized".to_string().into_boxed_str()
}
async fn global_hr<'g>(x: &'g fn(&()))
where
    fn(&()): Foo,
{
    x.test();
}
fn main() {}
```

### Affected release channels

- [ ] Previous Stable
- [x] Current Stable
- [ ] Current Beta
- [x] Current Nightly

### Rust Version

```Shell
$ rustc --version --verbose
rustc 1.83.0 (90b35a623 2024-11-26)
binary: rustc
commit-hash: 90b35a6239c3d8bdabc530a6a0816f7ff89a0aaf
commit-date: 2024-11-26
host: x86_64-unknown-linux-gnu
release: 1.83.0
LLVM version: 19.1.1
```

### Current error output

```Shell
$ rustc -C opt-level=3 --edition=2021 1.rs 
error[E0412]: cannot find type `X` in this scope
  --> 1.rs:64:8
   |
61 | trait A {}
   | ------- similarly named trait `A` defined here
...
64 |     x: X,
   |        ^
   |
help: a trait with a similar name exists
   |
64 |     x: A,
   |        ~
help: you might be missing a type parameter
   |
63 | struct Dst<X> {
   |           +++

error[E0277]: the trait bound `i32: Foo` is not satisfied
 --> 1.rs:9:5
  |
9 |     i32: Foo,
  |     ^^^^^^^^ the trait `Foo` is not implemented for `i32`
  |
  = help: the trait `Foo` is implemented for `()`
  = help: see issue #48214

error[E0277]: the trait bound `i32: Foo` is not satisfied
  --> 1.rs:15:5
   |
15 |     i32: Foo;
   |     ^^^^^^^^ the trait `Foo` is not implemented for `i32`
   |
   = help: the trait `Foo` is implemented for `()`
   = help: see issue #48214

error[E0277]: the trait bound `i32: Foo` is not satisfied
  --> 1.rs:17:5
   |
17 |     i32: Foo,
   |     ^^^^^^^^ the trait `Foo` is not implemented for `i32`
   |
   = help: the trait `Foo` is implemented for `()`
   = help: see issue #48214

error[E0277]: the trait bound `i32: Foo` is not satisfied
  --> 1.rs:22:5
   |
22 |     i32: Foo,
   |     ^^^^^^^^ the trait `Foo` is not implemented for `i32`
   |
   = help: the trait `Foo` is implemented for `()`
   = help: see issue #48214

error[E0277]: the trait bound `i32: Foo` is not satisfied
  --> 1.rs:32:5
   |
32 |     i32: Foo,
   |     ^^^^^^^^ the trait `Foo` is not implemented for `i32`
   |
   = help: the trait `Foo` is implemented for `()`
   = help: see issue #48214

error[E0277]: the trait bound `i32: Foo` is not satisfied
  --> 1.rs:42:5
   |
42 |     i32: Foo,
   |     ^^^^^^^^ the trait `Foo` is not implemented for `i32`
   |
   = help: the trait `Foo` is implemented for `()`
   = help: see issue #48214

error[E0277]: the trait bound `String: Neg` is not satisfied
  --> 1.rs:51:5
   |
51 |     String: ::std::ops::Neg<Output = String>,
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `Neg` is not implemented for `String`
   |
   = help: see issue #48214

error[E0277]: `i32` is not an iterator
  --> 1.rs:57:5
   |
57 |     i32: Iterator,
   |     ^^^^^^^^^^^^^ `i32` is not an iterator
   |
   = help: the trait `Iterator` is not implemented for `i32`
   = help: see issue #48214

error[E0277]: the size for values of type `str` cannot be known at compilation time
  --> 1.rs:68:5
   |
68 |     str: Sized;
   |     ^^^^^^^^^^ doesn't have a size known at compile-time
   |
   = help: the trait `Sized` is not implemented for `str`
   = help: see issue #48214

error[E0107]: struct takes 0 generic arguments but 1 generic argument was supplied
  --> 1.rs:71:5
   |
71 |     Dst<dyn A>: Sized,
   |     ^^^------- help: remove the unnecessary generics
   |     |
   |     expected 0 generic arguments
   |
note: struct defined here, with 0 generic parameters
  --> 1.rs:63:8
   |
63 | struct Dst {
   |        ^^^

error[E0277]: the size for values of type `str` cannot be known at compilation time
  --> 1.rs:77:5
   |
77 |     str: Sized,
   |     ^^^^^^^^^^ doesn't have a size known at compile-time
   |
   = help: the trait `Sized` is not implemented for `str`
   = help: see issue #48214

error[E0308]: mismatched types
  --> 1.rs:47:22
   |
47 |     generic_function(5i32);
   |     ---------------- ^^^^ expected `&_`, found `i32`
   |     |
   |     arguments to this function are incorrect
   |
   = note: expected reference `&_`
                   found type `i32`
note: function defined here
  --> 1.rs:6:10
   |
6  | async fn generic_function<'g, X: Foo>(x: &'g X) {}
   |          ^^^^^^^^^^^^^^^^             --------
help: consider borrowing here
   |
47 |     generic_function(&5i32);
   |                      +

error[E0600]: cannot apply unary operator `-` to type `&String`
  --> 1.rs:53:5
   |
53 |     -s
   |     ^^ cannot apply unary operator `-`

error[E0107]: struct takes 0 generic arguments but 1 generic argument was supplied
  --> 1.rs:73:12
   |
73 |     let x: Dst<dyn A> = *(Box::new(Dst { x: 1 }) as Box<Dst<dyn A>>);
   |            ^^^------- help: remove the unnecessary generics
   |            |
   |            expected 0 generic arguments
   |
note: struct defined here, with 0 generic parameters
  --> 1.rs:63:8
   |
63 | struct Dst {
   |        ^^^

error[E0107]: struct takes 0 generic arguments but 1 generic argument was supplied
  --> 1.rs:73:57
   |
73 |     let x: Dst<dyn A> = *(Box::new(Dst { x: 1 }) as Box<Dst<dyn A>>);
   |                                                         ^^^------- help: remove the unnecessary generics
   |                                                         |
   |                                                         expected 0 generic arguments
   |
note: struct defined here, with 0 generic parameters
  --> 1.rs:63:8
   |
63 | struct Dst {
   |        ^^^

error[E0308]: mismatched types
  --> 1.rs:37:26
   |
37 |         generic_function(5i32);
   |         ---------------- ^^^^ expected `&_`, found `i32`
   |         |
   |         arguments to this function are incorrect
   |
   = note: expected reference `&_`
                   found type `i32`
note: function defined here
  --> 1.rs:6:10
   |
6  | async fn generic_function<'g, X: Foo>(x: &'g X) {}
   |          ^^^^^^^^^^^^^^^^             --------
help: consider borrowing here
   |
37 |         generic_function(&5i32);
   |                          +
```

### Backtrace

```Shell
error: internal compiler error: /rustc/90b35a6239c3d8bdabc530a6a0816f7ff89a0aaf/compiler/rustc_const_eval/src/interpret/operand.rs:84:42: Got a scalar pair where a scalar was expected

thread 'rustc' panicked at /rustc/90b35a6239c3d8bdabc530a6a0816f7ff89a0aaf/compiler/rustc_const_eval/src/interpret/operand.rs:84:42:
Box<dyn Any>
stack backtrace:
   0:     0x7f57f8acb12a - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::h5b6bd5631a6d1f6b
   1:     0x7f57f92ac8f8 - core::fmt::write::h7550c97b06c86515
   2:     0x7f57fa4e3b91 - std::io::Write::write_fmt::h7b09c64fe0be9c84
   3:     0x7f57f8acaf82 - std::sys::backtrace::BacktraceLock::print::h2395ccd2c84ba3aa
   4:     0x7f57f8acd456 - std::panicking::default_hook::{{closure}}::he19d4c7230e07961
   5:     0x7f57f8acd2a0 - std::panicking::default_hook::hf614597d3c67bbdb
   6:     0x7f57f7b8f556 - std[c6eb78587944e35c]::panicking::update_hook::<alloc[148a978a4a62f5d]::boxed::Box<rustc_driver_impl[4c2d2ad79fb810ac]::install_ice_hook::{closure#0}>>::{closure#0}
   7:     0x7f57f8acdb68 - std::panicking::rust_panic_with_hook::h8942133a8b252070
   8:     0x7f57f7bc6371 - std[c6eb78587944e35c]::panicking::begin_panic::<rustc_errors[7f4c80274b6ccf5]::ExplicitBug>::{closure#0}
   9:     0x7f57f7bb9976 - std[c6eb78587944e35c]::sys::backtrace::__rust_end_short_backtrace::<std[c6eb78587944e35c]::panicking::begin_panic<rustc_errors[7f4c80274b6ccf5]::ExplicitBug>::{closure#0}, !>
  10:     0x7f57f7bb9933 - std[c6eb78587944e35c]::panicking::begin_panic::<rustc_errors[7f4c80274b6ccf5]::ExplicitBug>
  11:     0x7f57f7bcfa31 - <rustc_errors[7f4c80274b6ccf5]::diagnostic::BugAbort as rustc_errors[7f4c80274b6ccf5]::diagnostic::EmissionGuarantee>::emit_producing_guarantee
  12:     0x7f57f81f9e74 - rustc_middle[a886f61dbc61428a]::util::bug::opt_span_bug_fmt::<rustc_span[3e5cf3424d44936d]::span_encoding::Span>::{closure#0}
  13:     0x7f57f81dff6a - rustc_middle[a886f61dbc61428a]::ty::context::tls::with_opt::<rustc_middle[a886f61dbc61428a]::util::bug::opt_span_bug_fmt<rustc_span[3e5cf3424d44936d]::span_encoding::Span>::{closure#0}, !>::{closure#0}
  14:     0x7f57f81dfdfb - rustc_middle[a886f61dbc61428a]::ty::context::tls::with_context_opt::<rustc_middle[a886f61dbc61428a]::ty::context::tls::with_opt<rustc_middle[a886f61dbc61428a]::util::bug::opt_span_bug_fmt<rustc_span[3e5cf3424d44936d]::span_encoding::Span>::{closure#0}, !>::{closure#0}, !>
  15:     0x7f57f6b0e9a0 - rustc_middle[a886f61dbc61428a]::util::bug::bug_fmt
  16:     0x7f57fab8f291 - <rustc_mir_transform[b36c87ceb4bb9a8e]::gvn::VnState>::simplify_operand.cold
  17:     0x7f57f6bcb95b - <rustc_mir_transform[b36c87ceb4bb9a8e]::gvn::GVN as rustc_mir_transform[b36c87ceb4bb9a8e]::pass_manager::MirPass>::run_pass
  18:     0x7f57f92963dd - rustc_mir_transform[b36c87ceb4bb9a8e]::pass_manager::run_passes_inner
  19:     0x7f57f97959fa - rustc_mir_transform[b36c87ceb4bb9a8e]::optimized_mir
  20:     0x7f57f9793369 - rustc_query_impl[db795c774d495014]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[db795c774d495014]::query_impl::optimized_mir::dynamic_query::{closure#2}::{closure#0}, rustc_middle[a886f61dbc61428a]::query::erase::Erased<[u8; 8usize]>>
  21:     0x7f57f92afb2d - rustc_query_system[b2bb6e43dd6b7fda]::query::plumbing::try_execute_query::<rustc_query_impl[db795c774d495014]::DynamicConfig<rustc_query_system[b2bb6e43dd6b7fda]::query::caches::DefIdCache<rustc_middle[a886f61dbc61428a]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[db795c774d495014]::plumbing::QueryCtxt, false>
  22:     0x7f57f92af1b3 - rustc_query_impl[db795c774d495014]::query_impl::optimized_mir::get_query_non_incr::__rust_end_short_backtrace
  23:     0x7f57f9d5939f - rustc_middle[a886f61dbc61428a]::query::plumbing::query_get_at::<rustc_query_system[b2bb6e43dd6b7fda]::query::caches::DefIdCache<rustc_middle[a886f61dbc61428a]::query::erase::Erased<[u8; 8usize]>>>
  24:     0x7f57f81f98b5 - <rustc_middle[a886f61dbc61428a]::ty::context::TyCtxt>::coroutine_layout
  25:     0x7f57f98fec28 - rustc_ty_utils[45bf0f8bee683616]::layout::layout_of_uncached
  26:     0x7f57f98efa46 - rustc_ty_utils[45bf0f8bee683616]::layout::layout_of
  27:     0x7f57f98ef9d1 - rustc_query_impl[db795c774d495014]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[db795c774d495014]::query_impl::layout_of::dynamic_query::{closure#2}::{closure#0}, rustc_middle[a886f61dbc61428a]::query::erase::Erased<[u8; 16usize]>>
  28:     0x7f57f98ef0b2 - rustc_query_system[b2bb6e43dd6b7fda]::query::plumbing::try_execute_query::<rustc_query_impl[db795c774d495014]::DynamicConfig<rustc_query_system[b2bb6e43dd6b7fda]::query::caches::DefaultCache<rustc_middle[a886f61dbc61428a]::ty::ParamEnvAnd<rustc_middle[a886f61dbc61428a]::ty::Ty>, rustc_middle[a886f61dbc61428a]::query::erase::Erased<[u8; 16usize]>>, false, true, false>, rustc_query_impl[db795c774d495014]::plumbing::QueryCtxt, false>
  29:     0x7f57f98eeda9 - rustc_query_impl[db795c774d495014]::query_impl::layout_of::get_query_non_incr::__rust_end_short_backtrace
  30:     0x7f57f689e0da - <rustc_mir_transform[b36c87ceb4bb9a8e]::known_panics_lint::KnownPanicsLint as rustc_mir_transform[b36c87ceb4bb9a8e]::pass_manager::MirLint>::run_lint
  31:     0x7f57f92916b9 - rustc_mir_transform[b36c87ceb4bb9a8e]::run_analysis_to_runtime_passes
  32:     0x7f57f94812de - rustc_mir_transform[b36c87ceb4bb9a8e]::mir_drops_elaborated_and_const_checked
  33:     0x7f57f9480cfd - rustc_query_impl[db795c774d495014]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[db795c774d495014]::query_impl::mir_drops_elaborated_and_const_checked::dynamic_query::{closure#2}::{closure#0}, rustc_middle[a886f61dbc61428a]::query::erase::Erased<[u8; 8usize]>>
  34:     0x7f57f957ee68 - rustc_query_system[b2bb6e43dd6b7fda]::query::plumbing::try_execute_query::<rustc_query_impl[db795c774d495014]::DynamicConfig<rustc_query_system[b2bb6e43dd6b7fda]::query::caches::VecCache<rustc_span[3e5cf3424d44936d]::def_id::LocalDefId, rustc_middle[a886f61dbc61428a]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[db795c774d495014]::plumbing::QueryCtxt, false>
  35:     0x7f57f957e6cd - rustc_query_impl[db795c774d495014]::query_impl::mir_drops_elaborated_and_const_checked::get_query_non_incr::__rust_end_short_backtrace
  36:     0x7f57f9b7b705 - rustc_interface[88a02114bbdb2383]::passes::run_required_analyses
  37:     0x7f57f9b722e5 - rustc_interface[88a02114bbdb2383]::passes::analysis
  38:     0x7f57f9b722c9 - rustc_query_impl[db795c774d495014]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[db795c774d495014]::query_impl::analysis::dynamic_query::{closure#2}::{closure#0}, rustc_middle[a886f61dbc61428a]::query::erase::Erased<[u8; 1usize]>>
  39:     0x7f57fa07d662 - rustc_query_system[b2bb6e43dd6b7fda]::query::plumbing::try_execute_query::<rustc_query_impl[db795c774d495014]::DynamicConfig<rustc_query_system[b2bb6e43dd6b7fda]::query::caches::SingleCache<rustc_middle[a886f61dbc61428a]::query::erase::Erased<[u8; 1usize]>>, false, false, false>, rustc_query_impl[db795c774d495014]::plumbing::QueryCtxt, false>
  40:     0x7f57fa07d38f - rustc_query_impl[db795c774d495014]::query_impl::analysis::get_query_non_incr::__rust_end_short_backtrace
  41:     0x7f57f9fed0bb - rustc_interface[88a02114bbdb2383]::interface::run_compiler::<core[c06ff78fa456ca03]::result::Result<(), rustc_span[3e5cf3424d44936d]::ErrorGuaranteed>, rustc_driver_impl[4c2d2ad79fb810ac]::run_compiler::{closure#0}>::{closure#1}
  42:     0x7f57f9fde3d9 - std[c6eb78587944e35c]::sys::backtrace::__rust_begin_short_backtrace::<rustc_interface[88a02114bbdb2383]::util::run_in_thread_with_globals<rustc_interface[88a02114bbdb2383]::interface::run_compiler<core[c06ff78fa456ca03]::result::Result<(), rustc_span[3e5cf3424d44936d]::ErrorGuaranteed>, rustc_driver_impl[4c2d2ad79fb810ac]::run_compiler::{closure#0}>::{closure#1}, core[c06ff78fa456ca03]::result::Result<(), rustc_span[3e5cf3424d44936d]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[c06ff78fa456ca03]::result::Result<(), rustc_span[3e5cf3424d44936d]::ErrorGuaranteed>>
  43:     0x7f57fa0adfac - <<std[c6eb78587944e35c]::thread::Builder>::spawn_unchecked_<rustc_interface[88a02114bbdb2383]::util::run_in_thread_with_globals<rustc_interface[88a02114bbdb2383]::interface::run_compiler<core[c06ff78fa456ca03]::result::Result<(), rustc_span[3e5cf3424d44936d]::ErrorGuaranteed>, rustc_driver_impl[4c2d2ad79fb810ac]::run_compiler::{closure#0}>::{closure#1}, core[c06ff78fa456ca03]::result::Result<(), rustc_span[3e5cf3424d44936d]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[c06ff78fa456ca03]::result::Result<(), rustc_span[3e5cf3424d44936d]::ErrorGuaranteed>>::{closure#1} as core[c06ff78fa456ca03]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  44:     0x7f57fa0aea6b - std::sys::pal::unix::thread::Thread::new::thread_start::hcc78f3943333fa94
  45:     0x7f57f4649609 - start_thread
                               at /build/glibc-LcI20x/glibc-2.31/nptl/pthread_create.c:477:8
  46:     0x7f57f456e353 - clone
                               at /build/glibc-LcI20x/glibc-2.31/misc/../sysdeps/unix/sysv/linux/x86_64/clone.S:95
  47:                0x0 - <unknown>

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.83.0 (90b35a623 2024-11-26) running on x86_64-unknown-linux-gnu

note: compiler flags: -C opt-level=3

query stack during panic:
#0 [optimized_mir] optimizing MIR for `return_str::{closure#0}`
#1 [layout_of] computing layout of `{async fn body of return_str()}`
end of query stack
error: aborting due to 18 previous errors

Some errors have detailed explanations: E0107, E0277, E0308, E0412, E0600.
For more information about an error, try `rustc --explain E0107`.
```

### Anything else?

Note that the bug can only be reproduced by `rustc -C opt-level=3 --edition=2021 1.rs `.
If we remove `-C opt-level=3`, the ICE disappears.

### PR DESCRIPTION
**Pull request by cjgillot**
MIR is fully typed, so type information is an integral part of what defines a value. GVN currently tries to circumvent storing types, which creates all sorts of complexities.

This PR stores the type along with the enum `Value` when defining a value index. This allows to simplify a lot of code.

Fixes rust-lang/rust#128094
Fixes rust-lang/rust#135128

r? @ghost for perf

### CODE REVIEW

**Comment by Kobzol** [comment]
Note: this benchmark will be delayed a bit, because we just switched to a new benchmarking machine and I need to backfill stable benchmark results. Sorry for that! It should be done sometime tomorrow, hopefully.

**Comment by cjgillot** [comment]
r? compiler

**Comment by SparrowLii** [comment]
Thanks for the great work!
r? @rust-lang/wg-mir-opt 
since they should be more familar with this

**Comment by SparrowLii** [comment]
r? @oli-obk 
I think you know about GVN or can figure out who are available to review this work?

File: compiler/rustc_mir_transform/src/gvn.rs [hunk 1]
```diff
@@ -346,76 +359,63 @@ impl<'body, 'tcx> VnState<'body, 'tcx> {
...
         }
     }
 
     #[instrument(level = "trace", skip(self), ret)]
     fn eval_to_const(&mut self, value: VnIndex) -> Option<OpTy<'tcx>> {
         use Value::*;
+        let ty = self.ty(value);
+        let ty = self.ecx.layout_of(ty).ok()?;
         let op = match *self.get(value) {
+            _ if ty.is_zst() => ImmTy::uninit(ty).into(),
```
Comment (oli-obk) [inline compiler/rustc_mir_transform/src/gvn.rs]: Mostly keeping notes to myself: this is why we get a test change from this PR. It is otherwise a transparent change that just tracks more data

File: compiler/rustc_mir_transform/src/gvn.rs [hunk 2]
```diff
@@ -346,76 +359,63 @@ impl<'body, 'tcx> VnState<'body, 'tcx> {
...
-                };
-                let variant = if ty.is_enum() { Some(variant) } else { None };
-                let ty = self.ecx.layout_of(ty).ok()?;
-                if ty.is_zst() {
-                    ImmTy::uninit(ty).into()
-                } else if matches!(
-                    ty.backend_repr,
-                    BackendRepr::Scalar(..) | BackendRepr::ScalarPair(..)
-                ) {
+                let variant = if ty.ty.is_enum() { Some(variant) } else { None };
```
Comment (oli-obk) [inline compiler/rustc_mir_transform/src/gvn.rs:406]: orthogonal, but this check seems like it could just be removed and the `if let Some(variant) =variant` below could do the enum check instead.

**Review by oli-obk — APPROVED** [review]
