### PR TITLE
rustc: Upgrade to LLVM 6

### LINKED ISSUE #157: `stdsimd` fails to build with `target_cpu=skylake-avx512`
When compiling `stdsimd` with `rustc 1.22.0-nightly (b7960878b 2017-10-18)` and `-C target_cpu=skylake-avx512`, the build fails:

```
$ RUSTFLAGS="-C target_cpu=skylake-avx512" cargo build --release
   Compiling stdsimd v0.0.2 (file:///<stripped>/stdsimd)
LLVM ERROR: Cannot select: t83: v32i16 = X86ISD::VINSERT t82, t78, Constant:i64<0>
  t82: v32i16 = bitcast t81
    t81: v16i32 = BUILD_VECTOR Constant:i32<0>, Constant:i32<0>, Constant:i32<0>, Constant:i32<0>, Constant:i32<0>, Constant:i32<0>, Constant:i32<0>, Constant:i32<0>, Constant:i32<0>, Constant:i32<0>, Constant:i32<0>, Constant:i32<0>, Constant:i32<0>, Constant:i32<0>, Constant:i32<0>, Constant:i32<0>
      t80: i32 = Constant<0>
      t80: i32 = Constant<0>
      t80: i32 = Constant<0>
      t80: i32 = Constant<0>
      t80: i32 = Constant<0>
      t80: i32 = Constant<0>
      t80: i32 = Constant<0>
      t80: i32 = Constant<0>
      t80: i32 = Constant<0>
      t80: i32 = Constant<0>
      t80: i32 = Constant<0>
      t80: i32 = Constant<0>
      t80: i32 = Constant<0>
      t80: i32 = Constant<0>
      t80: i32 = Constant<0>
      t80: i32 = Constant<0>
  t78: i16 = truncate t5
    t5: i64,ch = CopyFromReg t0, Register:i64 %vreg2
      t4: i64 = Register %vreg2
  t79: i64 = Constant<0>
In function: _ZN61_$LT$stdsimd..v512..u16x32$u20$as$u20$core..fmt..LowerHex$GT$3fmt17h59e1149cebeaa07fE
error: Could not compile `stdsimd`.

To learn more, run the command again with --verbose.
```

### LINKED ISSUE #43370: LLVM 5.0 Tracking Issue
The time has come again, LLVM is releasing 5.0 soon and Rust wants to / needs to follow.

I have started work on the upgrade in these branches:

* `rust-lang/rust`: https://github.com/TimNN/rust/tree/llvm50
* `rust-lang/llvm`: https://github.com/rust-lang/llvm/tree/rust-llvm-2017-07-20
* `rust-lang/compiler-rt`: https://github.com/rust-lang/compiler-rt/tree/rust-2017-07-20
* `rust-lang-nursery/compiler-builtins`: https://github.com/TimNN/compiler-builtins/tree/llvm50

*Note: you may need to manually check out the `libcompiler_builtins` in `rust-lang/rust`.*

Next steps:
* [ ] Get `rustllvm` to compile ([error log](https://gist.github.com/aabb658aaf2460e94a46630b20e7db81))

Current issues:
* [ ] A lot changed around [attributes](https://github.com/llvm-mirror/llvm/blob/release_50/include/llvm/IR/Attributes.h)
* [ ] `SynchronizationScope` [changed / was renamed?](https://github.com/llvm-mirror/llvm/commit/8f85685860c0f6018a83b804f33e47f8122a9eba)
* [ ] `LLVMMetadataRef` was added, this can / should likely replace `LLVMRustMetadataRef`
* [ ] `createPointerType` [gained a new parameter](https://github.com/llvm-mirror/llvm/commit/2cee5cc825969057f8d23b507a4861e606216aed)
* [ ] `createNameSpace` [lost some parameters](https://github.com/llvm-mirror/llvm/commit/841400b968059a98f58ad258552692c7a4bd0bad)
* [ ] `DebugLoc` was replaced by `DiagnosticLocation` in [LLVM `DiagnosticInfo`](https://github.com/llvm-mirror/llvm/commit/787e150ebea15e81dbd497846388c8c5dc855fb6)

All but the first issues seem straight forward to fix, so I'll try to send PRs soon.

### LINKED ISSUE #43418: Compiler runs forever at opt-level=3
When I switch from opt-level=1 to opt-level=3 my program goes from compiling instantly to rustc running at 100% cpu and never finishing(many hours....).

The code can be found at:
  https://github.com/jcriddle4/rust_cry

### LINKED ISSUE #47015: Bad native codegen (2017-12-25 Nightly)
Given this small program:

```
#[inline(never)]
fn e97() -> u64 {
    // Input.
    const BASE: f64 = 28_433.0;
    const EXP: u64 = 7_830_457;
    const BIG: f64 = 1e10;

    let mut b = EXP.next_power_of_two();

    let mut n = 1.0;
    while b > 0 {
        if EXP & b != 0 {
            n = (n * n * 2.0) % BIG;
        } else {
            n = (n * n) % BIG;
        }
        b >>= 1;
    }

    ((n * BASE + 1.0) % BIG) as u64
}

fn main() {
    assert_eq!(e97(), 8_739_992_577);
}
```

I am using:
```
rustc 1.24.0-nightly (4a7c072fa 2017-12-25)
commit-hash: 4a7c072fa61b42f96d8b75c37fc1edfd71172695
host: x86_64-pc-windows-gnu
```

If I compile that program with this it works correctly:
`rustc -C opt-level=1 test.rs`

If I compile it with a native CPU target it asserts:
`rustc -C opt-level=1 -C target-cpu=native test.rs`

The llvm-ir of the e97 function produced with a default CPU target:

```
; test::e97
; Function Attrs: noinline norecurse nounwind readnone uwtable
define internal fastcc i64 @_ZN4test3e9717h2a230e2896608cc2E() unnamed_addr #3 {
start:
  br label %bb4

bb3:                                              ; preds = %bb4
  %0 = fmul double %n.1.1, 2.843300e+04
  %1 = fadd double %0, 1.000000e+00
  %2 = frem double %1, 1.000000e+10
  %3 = fptoui double %2 to i64
  ret i64 %3

bb4:                                              ; preds = %bb4, %start
  %b.08 = phi i64 [ 8388608, %start ], [ %12, %bb4 ]
  %n.07 = phi double [ 1.000000e+00, %start ], [ %n.1.1, %bb4 ]
  %4 = and i64 %b.08, 7830457
  %5 = icmp eq i64 %4, 0
  %6 = fmul double %n.07, %n.07
  %7 = fmul double %6, 2.000000e+00
  %n.1.in = select i1 %5, double %6, double %7
  %n.1 = frem double %n.1.in, 1.000000e+10
  %8 = and i64 %b.08, 15660914
  %9 = icmp eq i64 %8, 0
  %10 = fmul double %n.1, %n.1
  %11 = fmul double %10, 2.000000e+00
  %n.1.in.1 = select i1 %9, double %10, double %11
  %n.1.1 = frem double %n.1.in.1, 1.000000e+10
  %12 = lshr i64 %b.08, 2
  %13 = icmp eq i64 %12, 0
  br i1 %13, label %bb3, label %bb4
}
```

And the llvm-ir using the native CPU target:

```
; test::e97
; Function Attrs: noinline norecurse nounwind readnone uwtable
define internal fastcc i64 @_ZN4test3e9717h2a230e2896608cc2E() unnamed_addr #3 {
start:
  br label %bb4

bb3:                                              ; preds = %bb4
  %0 = fmul double %n.1.3, 2.843300e+04
  %1 = fadd double %0, 1.000000e+00
  %2 = frem double %1, 1.000000e+10
  %3 = fptoui double %2 to i64
  ret i64 %3

bb4:                                              ; preds = %bb4, %start
  %b.08 = phi i64 [ 8388608, %start ], [ %20, %bb4 ]
  %n.07 = phi double [ 1.000000e+00, %start ], [ %n.1.3, %bb4 ]
  %4 = and i64 %b.08, 7830457
  %5 = icmp eq i64 %4, 0
  %6 = fmul double %n.07, %n.07
  %7 = fmul double %6, 2.000000e+00
  %n.1.in = select i1 %5, double %6, double %7
  %n.1 = frem double %n.1.in, 1.000000e+10
  %8 = and i64 %b.08, 15660914
  %9 = icmp eq i64 %8, 0
  %10 = fmul double %n.1, %n.1
  %11 = fmul double %10, 2.000000e+00
  %n.1.in.1 = select i1 %9, double %10, double %11
  %n.1.1 = frem double %n.1.in.1, 1.000000e+10
  %12 = and i64 %b.08, 31321828
  %13 = icmp eq i64 %12, 0
  %14 = fmul double %n.1.1, %n.1.1
  %15 = fmul double %14, 2.000000e+00
  %n.1.in.2 = select i1 %13, double %14, double %15
  %n.1.2 = frem double %n.1.in.2, 1.000000e+10
  %16 = and i64 %b.08, 62643656
  %17 = icmp eq i64 %16, 0
  %18 = fmul double %n.1.2, %n.1.2
  %19 = fmul double %18, 2.000000e+00
  %n.1.in.3 = select i1 %17, double %18, double %19
  %n.1.3 = frem double %n.1.in.3, 1.000000e+10
  %20 = lshr i64 %b.08, 4
  %21 = icmp eq i64 %20, 0
  br i1 %21, label %bb3, label %bb4
}
```

Their diff:

```
8c8
<   %0 = fmul double %n.1.1, 2.843300e+04
---
>   %0 = fmul double %n.1.3, 2.843300e+04
15,16c15,16
<   %b.08 = phi i64 [ 8388608, %start ], [ %12, %bb4 ]
<   %n.07 = phi double [ 1.000000e+00, %start ], [ %n.1.1, %bb4 ]
---
>   %b.08 = phi i64 [ 8388608, %start ], [ %20, %bb4 ]
>   %n.07 = phi double [ 1.000000e+00, %start ], [ %n.1.3, %bb4 ]
29,31c29,43
<   %12 = lshr i64 %b.08, 2
<   %13 = icmp eq i64 %12, 0
<   br i1 %13, label %bb3, label %bb4
---
>   %12 = and i64 %b.08, 31321828
>   %13 = icmp eq i64 %12, 0
>   %14 = fmul double %n.1.1, %n.1.1
>   %15 = fmul double %14, 2.000000e+00
>   %n.1.in.2 = select i1 %13, double %14, double %15
>   %n.1.2 = frem double %n.1.in.2, 1.000000e+10
>   %16 = and i64 %b.08, 62643656
>   %17 = icmp eq i64 %16, 0
>   %18 = fmul double %n.1.2, %n.1.2
>   %19 = fmul double %18, 2.000000e+00
>   %n.1.in.3 = select i1 %17, double %18, double %19
>   %n.1.3 = frem double %n.1.in.3, 1.000000e+10
>   %20 = lshr i64 %b.08, 4
>   %21 = icmp eq i64 %20, 0
>   br i1 %21, label %bb3, label %bb4
```

### LINKED ISSUE #47683: Tracking issue for LLVM 6 upgrade
An LLVM release candidate for 6.0.0 has been tagged, and despite [not having upgraded to LLVM 5](https://github.com/rust-lang/rust/issues/43370) we should start weeding out bugs for LLVM 6!

* https://github.com/alexcrichton/rust/tree/llvm-6
* https://github.com/alexcrichton/llvm/tree/rust-llvm-release-6-0-0
* https://github.com/alexcrichton/compiler-builtins/tree/llvm-60
* https://github.com/rust-lang/compiler-rt/tree/rust-llvm-release-6-0-0

test results:

* [Second Travis Run](https://travis-ci.org/rust-lang/rust/builds/333128237)
* [First Travis Run](https://travis-ci.org/rust-lang/rust/builds/332843472) 

Issues with no diagnosis/resolution

* None!

I'm sure this list will expand over time! I'll try to keep it updated.

Issues with a diagnosis/resolution that hasn't landed

* [x] i686 MSVC is showing a corrupt rlib when linking, something about archive writing changed maybe?
  * appears to be an [LLVM regression](https://bugs.llvm.org/show_bug.cgi?id=36096)
  * local hack reverting the line in that linked commit seems to fix the issue
* [x] Emscripten needs an upgrade 
  * hopefully obviated by https://github.com/rust-lang/rust/issues/46819

Fixed issues:

* [x] LLVM [removed `CodeModel::Default`](https://github.com/llvm-mirror/llvm/commit/9aafb854c), it's now optional - #47710
* [x] The `MIPS64` archive variant [was renamed](https://github.com/llvm-mirror/llvm/commit/f45adc29de8aa80ac22b28ab421a92aaced80a97) - #47710
* [x] `UnsafeAlgebra` support [has been refactored](https://github.com/llvm-mirror/llvm/commit/00e900afd) - #47710
* [x] Return value of `writeArchive` [has changed](https://github.com/llvm-mirror/llvm/commit/203c90ba) - #47710
* [x] wasm32-unknown is showing `DICompileUnit` assertions, we probably need to apply the same fix that ThinLTO has already. - #47710
* [x] wasm32's dlmalloc needs updating as an intrinsic changed (there's an llvm5 branch in the dlmalloc repo)
* [x] Sanitizers need updating as x86_64-gnu is failing (compiler-builtins has an llvm6 branch)
* [x] Our FreeBSD x86_64 image fails to compile LLVM 6 - #47710
* [x] Lingering [debuginfo failure](https://github.com/rust-lang/rust/issues/47611) affects LLVM 5 as well - #47688
* [x] Our FreeBSD i686 image fails to compile LLVM - for now [hack around this](https://github.com/alexcrichton/llvm/commit/346b7d61b8a1dffc083245470ddd3120deda78a1)
* [x] arm-android has weird [floating point failures](https://travis-ci.org/rust-lang/rust/jobs/332843476) that suggests a compiler-rt mismatch
  * looks like this isn't caused by LLVM updates, but rather https://github.com/rust-lang-nursery/compiler-builtins/pull/222
  * that'll get resolved by either backing it out or fixing it to land locally
  * fixed in https://github.com/rust-lang-nursery/compiler-builtins/pull/224
* [x] x86_64/i686 linux dist builders can't compile newer compiler-rt (sanitizers presumably)
  * [random hack to fix this](https://github.com/rust-lang/compiler-rt/commit/dfd960b5f1a1751b22738fa34fd27b583f4618db)

* [x] armhf-gnu has a few SIGSEGV in the test suite of run-fail, something about unwinding may be busted
  * appears to be an [LLVM regression](https://bugs.llvm.org/show_bug.cgi?id=36073)
  * fix proposed at https://reviews.llvm.org/D42509

PRs:

* [x] ~~[Initial pass for upgrading in-tree support for LLVM 6](https://github.com/rust-lang/rust/pull/47681)~~
* [x] [First round of compat](https://github.com/rust-lang/rust/pull/47710)
* [x] [Fix DW_OP_deref support](https://github.com/rust-lang/rust/pull/47688) (affects LLVM 5 as well)

### PR DESCRIPTION
**Pull request by alexcrichton**
The following submodules have been updated for a new version of LLVM:

- `src/llvm`
- `src/libcompiler_builtins` - transitively contains compiler-rt
- `src/dlmalloc`

This also updates the docker container for dist-i686-freebsd as the old 16.04
container is no longer capable of building LLVM. The
compiler-rt/compiler-builtins and dlmalloc updates are pretty routine without
much interesting happening, but the LLVM update here is of particular note.
Unlike previous updates I haven't cherry-picked all existing patches we had on
top of our LLVM branch as we have a [huge amount][patches4] and have at this
point forgotten what most of them are for. Instead I started from the current
`release_60` branch in LLVM and only applied patches that were necessary to get
our tests working and building.

The [current set of custom rustc-specific patches](https://github.com/rust-lang/llvm/compare/f1286127b73c0d81ced8595af62e78ed703ced8b...rust-llvm-release-6-0-0) included in this LLVM update are:

* rust-lang/llvm@1187443 - this is how we actually implement
  `cfg(target_feature)` for now and continues to not be upstreamed. While a
  hazard for SIMD stabilization this commit is otherwise keeping the status
  quo of a small rustc-specific feature.
* rust-lang/llvm@013f2ec - this is a rustc-specific optimization that we haven't
  upstreamed, notably teaching LLVM about our allocation-related routines (which
  aren't malloc/free). Once we stabilize the global allocator routines we will
  likely want to upstream this patch, but for now it seems reasonable to keep it
  on our fork.
* rust-lang/llvm@a65bbfd - I found this necessary to fix compilation of LLVM in
  our 32-bit linux container. I'm not really sure why it's necessary but my
  guess is that it's because of the absolutely ancient glibc that we're using.
  In any case it's only updating pieces we're not actually using in LLVM so I'm
  hoping it'll turn out alright. This doesn't seem like something we'll want to
  upstream.c
* rust-lang/llvm@77ab1f0 - this is what's actually enabling LLVM to build in our
  i686-freebsd container, I'm not really sure what's going on but we for sure
  probably don't want to upstream this and otherwise it seems not too bad for
  now at least.
* rust-lang/llvm@9eb9267 - we currently suffer on MSVC from an [upstream bug]
  which although diagnosed to a particular revision isn't currently fixed
  upstream (and the bug itself doesn't seem too active). This commit is a
  partial revert of the suspected cause of this regression (found via a
  bisection). I'm sort of hoping that this eventually gets fixed upstream with a
  similar fix (which we can replace in our branch), but for now I'm also hoping
  it's a relatively harmless change to have.

After applying these patches (plus one [backport] which should be [backported
upstream][llvm-back]) I believe we should have all tests working on all
platforms in our current test suite. I'm like 99% sure that we'll need some more
backports as issues are reported for LLVM 6 when this propagates through
nightlies, but that's sort of just par for the course nowadays!

In any case though some extra scrutiny of the patches here would definitely be
welcome, along with scrutiny of the "missing patches" like a [change to pass
manager order](rust-lang/llvm@2717444), [another change to pass manager
order](rust-lang/llvm@c782feb), some [compile fixes for
sparc](rust-lang/llvm@1a83de6), and some [fixes for
solaris](rust-lang/llvm@c2bfe0a).

[patches4]: rust-lang/llvm@5401fdf...rust-llvm-release-4-0-1
[backport]: rust-lang/llvm@5c54c25
[llvm-back]: https://bugs.llvm.org/show_bug.cgi?id=36114
[upstream bug]: https://bugs.llvm.org/show_bug.cgi?id=36096

---

The update to LLVM 6 is desirable for a number of reasons, notably:

* This'll allow us to keep up with the upstream wasm backend, picking up new
  features as they start landing.
* Upstream LLVM has fixed a number of SIMD-related compilation errors,
  especially around AVX-512 and such.
* There's a few assorted known bugs which are fixed in LLVM 5 and aren't fixed
  in the LLVM 4 branch we're using.
* Overall it's not a great idea to stagnate with our codegen backend!

This update is mostly powered by #47730 which is allowing us to update LLVM
*independent* of the version of LLVM that Emscripten is locked to. This means
that when compiling code for Emscripten we'll still be using the old LLVM 4
backend, but when compiling code for any other target we'll be using the new
LLVM 6 target. Once Emscripten updates we may no longer need this distinction,
but we're not sure when that will happen!

Closes #43370
Closes #43418
Closes #47015
Closes #47683
Closes rust-lang-nursery/stdsimd#157
Closes rust-lang-nursery/rust-wasm#3

### CODE REVIEW

**Comment by alexcrichton** [comment]
Note that this is currently based on https://github.com/rust-lang/rust/pull/47730 which I'll rebase out once that lands. Also @rust-lang/infra could this get a perf run and a crater run? (to hopefully head of anything massive!)

@bors: try

cc @rust-lang/compiler

**Comment by alexcrichton** [comment]
[Perf comparison](https://perf.rust-lang.org/compare.html?start=771873c84137842c78cfc39625613b95867d21ef&end=38bd38147d2fa21f8a684b019fc0763adf8fd436&stat=wall-time) shows that nothing is too bad!

**Comment by est31** [comment]
Up to 13.5% improvement... wow.

**Comment by nikomatsakis** [comment]
@bors r+

Let's do it.

**Comment by cuviper** [comment]
> rust-lang/llvm@1187443 - this is how we actually implement
> cfg(target_feature) for now and continues to not be upstreamed. While a
> hazard for SIMD stabilization this commit is otherwise keeping the status
> quo of a small rustc-specific feature.

Maybe update run-pass/sse2 to `// min-llvm-version 6.0`?  But really that needs a `rustllvm` flag.

Apart from that, testing on this branch also looks good with external LLVM 5.

**Comment by mattico** [comment]
I did some investigation on the FreeBSD issue. [FreeBSD 10 uses Clang 3.0](https://wiki.freebsd.org/WhatsNew/FreeBSD10). [Clang didn't support std::atomic until 3.3](https://clang.llvm.org/cxx_status.html). I think that's all the issue is. FreeBSD 10 is only supported until Oct 31 of this year, so it should be safe to update that soon enough.

**Comment by alexcrichton** [comment]
@cuviper ah yes that test should definitely have a `// no-system-llvm` flag. Otherwise though this is an existing issue, I just wanted to highlight it again :)

@mattico ok cool, thanks!

**Comment by Zoxc** [comment]
I see access violations all the time when building on Windows using master, rebuilding makes it go away, so this error might be spurious.

**Comment by alexcrichton** [comment]
@bors: retry

hm ok, let's see then!

**Comment by Zoxc** [comment]
It doesn't seem to be spurious. I get the error on a local build too.
```
Unhandled exception at 0x00007FF9418BFC6D (rustc_trans-llvm.dll) in rustc.exe: 0xC0000005: Access violation reading location 0xFFFFFFFFFFFFFFFF.

 	rustc_trans-llvm.dll!llvm::initializeLegacyLICMPassPass(class llvm::PassRegistry &)	C++	Non-user code. Symbols loaded.
 	rustc_trans-llvm.dll!llvm::sinkRegion(class llvm::DomTreeNodeBase<class llvm::BasicBlock> *,class llvm::AAResults *,class llvm::LoopInfo *,class llvm::DominatorTree *,class llvm::TargetLibraryInfo *,class llvm::TargetTransformInfo *,class llvm::Loop *,class llvm::AliasSetTracker *,struct llvm::LoopSafetyInfo *,class llvm::OptimizationRemarkEmitter *)	C++	Non-user code. Symbols loaded.
 	rustc_trans-llvm.dll!llvm::promoteLoopAccessesToScalars(class llvm::SmallSetVector<class llvm::Value *,8> const &,class llvm::SmallVectorImpl<class llvm::BasicBlock *> &,class llvm::SmallVectorImpl<class llvm::Instruction *> &,class llvm::PredIteratorCache &,class llvm::LoopInfo *,class llvm::DominatorTree *,class llvm::TargetLibraryInfo const *,class llvm::Loop *,class llvm::AliasSetTracker *,struct llvm::LoopSafetyInfo *,class llvm::OptimizationRemarkEmitter *)	C++	Non-user code. Symbols loaded.
 	rustc_trans-llvm.dll!llvm::promoteLoopAccessesToScalars(class llvm::SmallSetVector<class llvm::Value *,8> const &,class llvm::SmallVectorImpl<class llvm::BasicBlock *> &,class llvm::SmallVectorImpl<class llvm::Instruction *> &,class llvm::PredIteratorCache &,class llvm::LoopInfo *,class llvm::DominatorTree *,class llvm::TargetLibraryInfo const *,class llvm::Loop *,class llvm::AliasSetTracker *,struct llvm::LoopSafetyInfo *,class llvm::OptimizationRemarkEmitter *)	C++	Non-user code. Symbols loaded.
 	rustc_trans-llvm.dll!llvm::LPPassManager::runOnFunction(class llvm::Function &)	C++	Non-user code. Symbols loaded.
 	rustc_trans-llvm.dll!llvm::FPPassManager::runOnFunction(class llvm::Function &)	C++	Non-user code. Symbols loaded.
 	rustc_trans-llvm.dll!llvm::CallGraphSCC::ReplaceNode(class llvm::CallGraphNode *,class llvm::CallGraphNode *)	C++	Non-user code. Symbols loaded.
 	rustc_trans-llvm.dll!llvm::CallGraphSCC::ReplaceNode(class llvm::CallGraphNode *,class llvm::CallGraphNode *)	C++	Non-user code. Symbols loaded.
 	rustc_trans-llvm.dll!llvm::initializeDummyCGSCCPassPass(class llvm::PassRegistry &)	C++	Non-user code. Symbols loaded.
 	rustc_trans-llvm.dll!llvm::FPPassManager::runOnModule(class llvm::Module &)	C++	Non-user code. Symbols loaded.
 	rustc_trans-llvm.dll!llvm::legacy::PassManagerImpl::run(class llvm::Module &)	C++	Non-user code. Symbols loaded.
 	rustc_trans-llvm.dll!LLVMRunPassManager()	C++	Non-user code. Symbols loaded.
>	rustc_trans-llvm.dll!rustc_trans::back::write::execute_work_item(rustc_trans::back::write::CodegenContext * cgcx, rustc_trans::back::write::WorkItem work_item, rustc_trans::time_graph::Timeline * timeline) Line 1341	Unknown	Symbols loaded.
 	[Inline Frame] rustc_trans-llvm.dll!rustc_trans::back::write::spawn_work::{{closure}}(closure) Line 1960	Unknown	Symbols loaded.
 	rustc_trans-llvm.dll!std::sys_common::backtrace::__rust_begin_short_backtrace<closure,()>(closure f) Line 136	Unknown	Symbols loaded.
 	[Inline Frame] rustc_trans-llvm.dll!std::thread::{{impl}}::spawn::{{closure}}::{{closure}}(closure) Line 406	Unknown	Symbols loaded.
 	[Inline Frame] rustc_trans-llvm.dll!std::panic::{{impl}}::call_once(std::panic::AssertUnwindSafe<closure>) Line 293	Unknown	Symbols loaded.
 	rustc_trans-llvm.dll!std::panicking::try::do_call<std::panic::AssertUnwindSafe<closure>,()>(unsigned char * data) Line 481	Unknown	Symbols loaded.
 	std-21038300f4bf6803.dll!panic_unwind::__rust_maybe_catch_panic(void(*)(unsigned char *) f, unsigned char * data, unsigned __int64 * data_ptr, unsigned __int64 * vtable_ptr) Line 102	Unknown	Symbols loaded.
 	[Inline Frame] rustc_trans-llvm.dll!std::panicking::try(std::panic::AssertUnwindSafe<closure>) Line 458	Unknown	Symbols loaded.
 	[Inline Frame] rustc_trans-llvm.dll!std::panic::catch_unwind(std::panic::AssertUnwindSafe<closure>) Line 358	Unknown	Symbols loaded.
 	[Inline Frame] rustc_trans-llvm.dll!std::thread::{{impl}}::spawn::{{closure}}(closure) Line 405	Unknown	Symbols loaded.
 	rustc_trans-llvm.dll!alloc::boxed::{{impl}}::call_box<(),closure>(closure * self, ...) Line 788	Unknown	Symbols loaded.
 	[Inline Frame] std-21038300f4bf6803.dll!alloc::boxed::{{impl}}::call_once(alloc::boxed::Box<FnBox<()>> self) Line 798	Unknown	Symbols loaded.
 	std-21038300f4bf6803.dll!std::sys_common::thread::start_thread(unsigned char * main) Line 24	Unknown	Symbols loaded.
 	std-21038300f4bf6803.dll!std::sys::windows::thread::{{impl}}::new::thread_start(libc::c_void * main) Line 57	Unknown	Symbols loaded.
```

**Comment by alexcrichton** [comment]
@Zoxc are you able to reliably reproduce? Which crate's being compiled as well?

If you've got debuginfo for llvm available, is there anythis suspect around where the segfault happened?

I can't seem to reproduce reliably at all...

**Comment by Zoxc** [comment]
I've been able to reliably reproduce it so far. It happens in the stage1 build of rustc_errors. I built llvm in debug mode, but Visual Studio doesn't pick up symbols for it :/

**Comment by kennytm** [comment]
@Zoxc could you enable llvm assertions to check?

**Comment by Zoxc** [comment]
My build was with LLVM assertions enabled and I didn't hit any.

**Comment by alexcrichton** [comment]
@Zoxc I was unable to reproduce with a debug build of LLVM or a `RelWithDebInfo` build of LLVM, can you gist your `config.toml` that you're using to reproduce this?

**Comment by alexcrichton** [comment]
@bors: r=nikomatsakis

I've been running local builds all night and haven't come up with anything, and I've also rebased on LLVM's current `release_60` branch which appeared to have at least one more segfault fix. Gonna try again.

**Comment by Zoxc** [comment]
Here is my [config.toml](https://gist.github.com/Zoxc/7c4a288fa4143385efcdadfd16638a75).

I made one build succeed changing it to:
```
[llvm]

# Indicates whether the LLVM build is a Release or Debug build
optimize = true

# Indicates whether an LLVM Release build should include debug info
release-debuginfo = true

# Indicates whether the LLVM assertions are enabled or not
assertions = true
```

**Comment by kennytm** [comment]
Huh `B:\` drive. 

@Zoxc Do you mean it can be built successfully only if you set all 3 flags to `true`, or setting any one `true` will cause the segfault go away?

**Comment by Zoxc** [comment]
> @Zoxc Do you mean it can be built successfully only if you set all 3 flags to true, or setting any one true will cause the segfault go away?

Neither. The `config.toml` I linked have resulted in the segfault. The changes to it in my post resulted in the build succeeding.

> Huh B:\ drive.

I have a large floppy drive.

**Comment by Zoxc** [comment]
Well I rebuilt using my linked `config.toml` and now the error disappeared :/

**Comment by Zoxc** [comment]
I can reproduce it by building a stage1 compiler and then using that inside `src/librustc_errors` with `cargo build --release`. I still have no LLVM debug information though.

**Comment by Zoxc** [comment]
It seems like the `cmake` crate overwrites compiler flags, but it does not include any flags to generate debug information.

**Comment by alexcrichton** [comment]
Ok thanks for the pointers @Zoxc, I've also reproduced now. It seems nondeterministic as well from initial testing.

Also the cmake crate overwriting flags sounds bad!

**Comment by alexcrichton** [comment]
Ok I've isolated the crash with a debug build of LLVM to one LLVM IR file, using bugpoint to reduce it...

**Comment by alexcrichton** [comment]
The segfault happens on [these lines](https://github.com/rust-lang/llvm/blob/483464d91779a09aa059baaf7ae63affbdc88f04/lib/Transforms/Scalar/LICM.cpp#L764-L765)

**Comment by alexcrichton** [comment]
[Upstream bug report](https://bugs.llvm.org/show_bug.cgi?id=36184)

**Comment by Zoxc** [comment]
The instruction which causes the access violation cannot access the address `0xFFFFFFFFFFFFFFFF`. Hopefully the error you got on Linux is more reasonable.

**Comment by alexcrichton** [comment]
I've bisected this to https://github.com/llvm-mirror/llvm/commit/7c2eb4e and [left a new comment](https://bugs.llvm.org/show_bug.cgi?id=36184#c2)

**Comment by PaulGrandperrin** [comment]
Hi, compiling this branch with this config.toml makes the compilation panic:
```
[llvm]
optimize = true
release-debuginfo = true
assertions = true
[build]
extended = true
sanitizers = true
[install]
[rust]
optimize = true
debug-assertions = true
debuginfo = true
debuginfo-lines = true
use-jemalloc = true
backtrace = true
optimize-tests = true
debuginfo-tests = true
[target.x86_64-unknown-linux-gnu]
[dist]
```

backtrace:
```
...
Assembling stage1 compiler (x86_64-unknown-linux-gnu)
Building stage1 std artifacts (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
   Compiling core v0.0.0 (file:///home/paulg/Projets/rust-lang/rust-alexcrichton/src/libcore)
error: internal compiler error: librustc/ty/context.rs:263: node unknown node (id=1) with HirId::owner DefId(0/0:0 ~ core[d915]) cannot be placed in TypeckTables with local_id_root DefId(0/0:1640 ~ core[d915]::panicking[0]::panic_fmt[0])

thread 'rustc' panicked at 'Box<Any>', librustc_errors/lib.rs:535:9
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
   1: std::sys_common::backtrace::print
   2: std::panicking::default_hook::{{closure}}
   3: std::panicking::default_hook
   4: std::panicking::rust_panic_with_hook
   5: std::panicking::begin_panic
   6: rustc_errors::Handler::bug
   7: <std::thread::local::LocalKey<T>>::with
   8: rustc::ty::context::tls::with_opt
   9: rustc::session::opt_span_bug_fmt
  10: rustc::session::bug_fmt
  11: <std::thread::local::LocalKey<T>>::with
  12: rustc::ty::context::tls::with
  13: rustc::ty::context::TypeckTables::node_id_to_type_opt
  14: <rustc_save_analysis::dump_visitor::DumpVisitor<'l, 'tcx, 'll, O>>::process_formals
  15: <rustc_save_analysis::dump_visitor::DumpVisitor<'l, 'tcx, 'll, O> as syntax::visit::Visitor<'l>>::visit_foreign_item
  16: syntax::visit::walk_item
  17: <rustc_save_analysis::dump_visitor::DumpVisitor<'l, 'tcx, 'll, O> as syntax::visit::Visitor<'l>>::visit_item
  18: <rustc_save_analysis::dump_visitor::DumpVisitor<'l, 'tcx, 'll, O> as syntax::visit::Visitor<'l>>::visit_item
  19: <rustc_save_analysis::dump_visitor::DumpVisitor<'l, 'tcx, 'll, O> as syntax::visit::Visitor<'l>>::visit_mod
  20: <rustc_save_analysis::DumpHandler<'a> as rustc_save_analysis::SaveHandler>::save
  21: rustc::dep_graph::graph::DepGraph::with_ignore
  22: rustc_driver::enable_save_analysis::{{closure}}::{{closure}}
  23: rustc_driver::enable_save_analysis::{{closure}}
  24: rustc::dep_graph::graph::DepGraph::with_ignore
  25: rustc_driver::driver::compile_input::{{closure}}
  26: <std::thread::local::LocalKey<T>>::with
  27: <std::thread::local::LocalKey<T>>::with
  28: rustc_driver::driver::compile_input
  29: rustc_driver::run_compiler

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.25.0-dev running on x86_64-unknown-linux-gnu

error: Could not compile `core`.

Caused by:
  process didn't exit successfully: `/home/paulg/Projets/rust-lang/rust-alexcrichton/build/bootstrap/debug/rustc --crate-name core libcore/lib.rs --error-format json --crate-type lib --emit=dep-info,link -C opt-level=2 -C metadata=40f5c600e4b14118 -C extra-filename=-40f5c600e4b14118 --out-dir /home/paulg/Projets/rust-lang/rust-alexcrichton/build/x86_64-unknown-linux-gnu/stage1-std/x86_64-unknown-linux-gnu/release/deps --target x86_64-unknown-linux-gnu -L dependency=/home/paulg/Projets/rust-lang/rust-alexcrichton/build/x86_64-unknown-linux-gnu/stage1-std/x86_64-unknown-linux-gnu/release/deps -L dependency=/home/paulg/Projets/rust-lang/rust-alexcrichton/build/x86_64-unknown-linux-gnu/stage1-std/release/deps` (exit code: 101)
thread 'main' panicked at 'command did not execute successfully: "/home/paulg/Projets/rust-lang/rust-alexcrichton/build/x86_64-unknown-linux-gnu/stage0/bin/cargo" "build" "--target" "x86_64-unknown-linux-gnu" "-j" "8" "--release" "--features" "panic-unwind jemalloc backtrace" "--manifest-path" "/home/paulg/Projets/rust-lang/rust-alexcrichton/src/libstd/Cargo.toml" "--message-format" "json"
expected success, got: exit code: 101', bootstrap/compile.rs:1061:9
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at /checkout/src/libstd/sys_common/backtrace.rs:68
             at /checkout/src/libstd/sys_common/backtrace.rs:57
   2: std::panicking::default_hook::{{closure}}
             at /checkout/src/libstd/panicking.rs:381
   3: std::panicking::default_hook
             at /checkout/src/libstd/panicking.rs:397
   4: std::panicking::rust_panic_with_hook
             at /checkout/src/libstd/panicking.rs:577
   5: std::panicking::begin_panic
             at /checkout/src/libstd/panicking.rs:538
   6: std::panicking::begin_panic_fmt
             at /checkout/src/libstd/panicking.rs:522
   7: bootstrap::compile::run_cargo
             at bootstrap/compile.rs:1061
   8: <bootstrap::compile::Std as bootstrap::builder::Step>::run
             at bootstrap/compile.rs:109
   9: bootstrap::builder::Builder::ensure
             at bootstrap/builder.rs:732
  10: <bootstrap::compile::Test as bootstrap::builder::Step>::run
             at bootstrap/compile.rs:343
  11: bootstrap::builder::Builder::ensure
             at bootstrap/builder.rs:732
  12: <bootstrap::compile::Rustc as bootstrap::builder::Step>::run
             at bootstrap/compile.rs:459
  13: bootstrap::builder::Builder::ensure
             at bootstrap/builder.rs:732
  14: <bootstrap::compile::Assemble as bootstrap::builder::Step>::run
             at bootstrap/compile.rs:885
  15: bootstrap::builder::Builder::ensure
             at bootstrap/builder.rs:732
  16: bootstrap::builder::Builder::compiler
             at bootstrap/builder.rs:339
  17: <bootstrap::compile::Std as bootstrap::builder::Step>::make_run
             at bootstrap/compile.rs:56
  18: bootstrap::builder::StepDescription::maybe_run
             at bootstrap/builder.rs:151
  19: bootstrap::builder::StepDescription::run
             at bootstrap/builder.rs:163
  20: bootstrap::builder::Builder::run
             at bootstrap/builder.rs:326
  21: bootstrap::Build::build
             at bootstrap/lib.rs:378
  22: bootstrap::main
             at bootstrap/bin/main.rs:29
  23: std::rt::lang_start::{{closure}}
             at /checkout/src/libstd/rt.rs:74
  24: std::panicking::try::do_call
             at /checkout/src/libstd/rt.rs:59
             at /checkout/src/libstd/panicking.rs:480
  25: __rust_maybe_catch_panic
             at /checkout/src/libpanic_unwind/lib.rs:101
  26: std::rt::lang_start_internal
             at /checkout/src/libstd/panicking.rs:459
             at /checkout/src/libstd/panic.rs:365
             at /checkout/src/libstd/rt.rs:58
  27: std::rt::lang_start
             at /checkout/src/libstd/rt.rs:74
  28: main
  29: __libc_start_main
  30: _start
failed to run: /home/paulg/Projets/rust-lang/rust-alexcrichton/build/bootstrap/debug/bootstrap build
Build completed unsuccessfully in 0:00:18
```

**Comment by alexcrichton** [comment]
@PaulGrandperrin unfortunately that may be an existing bug, it looks unrelated to this branch :(

**Comment by PaulGrandperrin** [comment]
Ops sorry, I didn't even check against a master. I'll try to find if it's already reported.

**Comment by kennytm** [comment]
The `run-pass\backtrace-debuginfo.rs` test failed on x86_64-pc-windows-msvc.

<details>

```
[02:02:30] ---- [run-pass] run-pass\backtrace-debuginfo.rs stdout ----
[02:02:30] 	
[02:02:30] error: test run failed!
[02:02:30] status: exit code: 101
[02:02:30] command: PATH="C:\projects\rust\build\x86_64-pc-windows-msvc\stage2\lib\rustlib\x86_64-pc-windows-msvc\lib;C:\Program Files (x86)\Windows Kits\10\bin\x64;C:\Program Files (x86)\Windows Kits\10\bin\10.0.14393.0\x64;C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\amd64;C:\projects\rust\build\x86_64-pc-windows-msvc\stage0-tools\x86_64-pc-windows-msvc\release\deps;C:\projects\rust\build\x86_64-pc-windows-msvc\stage0-sysroot\lib\rustlib\x86_64-pc-windows-msvc\lib;C:\Program Files (x86)\Inno Setup 5;C:\Python27;C:\msys64\mingw64\bin;C:\msys64\usr\bin;C:\Perl\site\bin;C:\Perl\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0;C:\Program Files\7-Zip;C:\Program Files\Microsoft\Web Platform Installer;C:\Tools\GitVersion;C:\Tools\PsTools;C:\Program Files\Git LFS;C:\Program Files (x86)\Subversion\bin;C:\Program Files\Microsoft SQL Server\120\Tools\Binn;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\110\Tools\Binn;C:\Program Files (x86)\Microsoft SQL Server\120\Tools\Binn;C:\Program Files\Microsoft SQL Server\120\DTS\Binn;C:\Program Files (x86)\Microsoft SQL Server\120\Tools\Binn\ManagementStudio;C:\Tools\WebDriver;C:\Program Files (x86)\Microsoft SDKs\TypeScript\1.4;C:\Program Files (x86)\Microsoft Visual Studio 12.0\Common7\IDE\PrivateAssemblies;C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\wbin;C:\Ruby193\bin;C:\Tools\NUnit\bin;C:\Tools\xUnit;C:\Tools\MSpec;C:\Tools\Coverity\bin;C:\Program Files (x86)\CMake\bin;C:\go\bin;C:\Program Files\Java\jdk1.8.0\bin;C:\Python27;C:\Program Files\nodejs;C:\Program Files (x86)\iojs;C:\Program Files\iojs;C:\Users\appveyor\AppData\Roaming\npm;C:\Program Files\Microsoft SQL Server\130\Tools\Binn;C:\Program Files (x86)\MSBuild\14.0\Bin;C:\Tools\NuGet;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\CommonExtensions\Microsoft\TestWindow;C:\Program Files\Microsoft DNX\Dnvm;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\130\Tools\Binn;C:\Program Files (x86)\Microsoft SQL Server\130\Tools\Binn;C:\Program Files (x86)\Microsoft SQL Server\130\DTS\Binn;C:\Program Files\Microsoft SQL Server\130\DTS\Binn;C:\Program Files (x86)\Microsoft SQL Server\110\DTS\Binn;C:\Program Files (x86)\Microsoft SQL Server\120\DTS\Binn;C:\Program Files (x86)\Apache\Maven\bin;C:\Python27\Scripts;C:\Tools\NUnit3;C:\Program Files\Mercurial;C:\Program Files\LLVM\bin;C:\Program Files\dotnet;C:\Tools\curl\bin;C:\Program Files\Amazon\AWSCLI;C:\Program Files (x86)\Microsoft SQL Server\140\DTS\Binn;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions\Microsoft\SQLDB\DAC\140;C:\Program Files\Git\cmd;C:\Program Files\Git\usr\bin;C:\Tools\vcpkg;C:\Program Files\Microsoft Service Fabric\bin\Fabric\Fabric.Code;C:\Program Files\Microsoft SDKs\Service Fabric\Tools\ServiceFabricLocalClusterManager;C:\Program Files (x86)\Yarn\bin;C:\Program Files (x86)\Microsoft SQL Server\140\Tools\Binn;C:\Program Files\Microsoft SQL Server\140\Tools\Binn;C:\Program Files\Microsoft SQL Server\140\DTS\Binn;C:\Program Files (x86)\nodejs;C:\ProgramData\chocolatey\bin;C:\Program Files\PowerShell\6.0.0;C:\Program Files\erl9.2\bin;C:\Users\appveyor\AppData\Local\Yarn\bin;C:\Users\appveyor\AppData\Roaming\npm;C:\Program Files\AppVeyor\BuildAgent;C:\projects\rust;C:\projects\rust\handle" "C:\\projects\\rust\\build\\x86_64-pc-windows-msvc\\test\\run-pass\\backtrace-debuginfo.stage2-x86_64-pc-windows-msvc.exe"
[02:02:30] stdout:
[02:02:30] ------------------------------------------
[02:02:30] 
[02:02:30] ------------------------------------------
[02:02:30] stderr:
[02:02:30] ------------------------------------------
[02:02:30] thread 'main' panicked at 'trace does not match position list: test case 2
[02:02:30] thread 'main' panicked at 'explicit panic', C:\projects\rust\src/test\run-pass\backtrace-debuginfo.rs:77:9
[02:02:30] stack backtrace:
[02:02:30]    0:     0x7ffc2ee46bdf - std::sys::windows::backtrace::unwind_backtrace::h1bd77506a1e99a28
[02:02:30]    1:     0x7ffc2ee4d0ff - std::sys_common::backtrace::print::hccea3e7798754719
[02:02:30]    2:     0x7ffc2ee4b69e - std::panicking::Location::column::h2fad3991e027b46c
[02:02:30]    3:     0x7ffc2ee4b349 - std::panicking::Location::column::h2fad3991e027b46c
[02:02:30]    4:     0x7ffc2ee4be38 - std::panicking::rust_panic_with_hook::h5cb0c051fc3317c4
[02:02:30]    5:     0x7ff753782b31 - std::panicking::begin_panic<str*>
[02:02:30]                                at C:\projects\rust\src\libstd\panicking.rs:537
[02:02:30]    6:     0x7ff75378291a - backtrace_debuginfo::inner::{{closure}}
[02:02:30]                                at C:\projects\rust\src\test\run-pass\backtrace-debuginfo.rs:77
[02:02:30]    7:     0x7ff75378291a - backtrace_debuginfo::aux::callback<closure>
[02:02:30]                                at C:\projects\rust\src\test\run-pass\backtrace-debuginfo-aux.rs:16
[02:02:30]    8:     0x7ff753783785 - backtrace_debuginfo::inner
[02:02:30]                                at C:\projects\rust\src\test\run-pass\backtrace-debuginfo.rs:76
[02:02:30]    9:     0x7ff753783aff - backtrace_debuginfo::outer
[02:02:30]                                at C:\projects\rust\src\test\run-pass\backtrace-debuginfo.rs:113
[02:02:30]   10:     0x7ff753783c6d - backtrace_debuginfo::main
[02:02:30]                                at C:\projects\rust\src\test\run-pass\backtrace-debuginfo.rs:158
[02:02:30]   11:     0x7ff75378265b - std::rt::lang_start::{{closure}}<()>
[02:02:30]                                at C:\projects\rust\src\libstd\rt.rs:74
[02:02:30]   12:     0x7ffc2ee4ba06 - std::panicking::try::do_call::hae5e98b351398502
[02:02:30]   13:     0x7ffc2ee7f421 - _rust_maybe_catch_panic
[02:02:30]   14:     0x7ffc2ee4b899 - std::panicking::try::hfd233a2115442da3
[02:02:30]   15:     0x7ffc2ee46926 - std::rt::lang_start_internal::h3e8d6fcb01d4a1dd
[02:02:30]   16:     0x7ff75378494d - main
[02:02:30]   17:     0x7ff753786940 - invoke_main
[02:02:30]                                at f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl:64
[02:02:30]   18:     0x7ff753786940 - __scrt_common_main_seh
[02:02:30]                                at f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl:253
[02:02:30]   19:     0x7ffc38a713d1 - BaseThreadInitThunk
[02:02:30]   20:     0x7ffc39c554f3 - RtlUserThreadStart
[02:02:30] 
[02:02:30] ---
[02:02:30] backtrace-debuginfo-aux.rs:15
[02:02:30] backtrace-debuginfo.rs:76
[02:02:30] backtrace-debuginfo.rs:113
[02:02:30] backtrace-debuginfo.rs:158
[02:02:30] ', C:\projects\rust\src/test\run-pass\backtrace-debuginfo.rs:127:5
[02:02:30] note: Run with `RUST_BACKTRACE=1` for a backtrace.
[02:02:30] 
[02:02:30] ------------------------------------------
[02:02:30] 
[02:02:30] thread '[run-pass] run-pass\backtrace-debuginfo.rs' panicked at 'explicit panic', tools\compiletest\src\runtest.rs:2883:9
[02:02:30] note: Run with `RUST_BACKTRACE=1` for a backtrace.
[02:02:30] 
[02:02:30] 
[02:02:30] failures:
[02:02:30]     [run-pass] run-pass\backtrace-debuginfo.rs
[02:02:30] 
[02:02:30] test result: FAILED. 2895 passed; 1 failed; 22 ignored; 0 measured; 0 filtered out
```

</details>

File: src/test/run-pass/backtrace-debuginfo.rs [hunk 1]
```diff
@@ -143,10 +155,20 @@ fn run_test(me: &str) {
...
             break;
         } else {
-            check_trace(output, error);
+            if let Err(e) = check_trace(output, error) {
+                errors.push(e);
+            }
         }
         i += 1;
     }
+    if errors.len() > 0 {
```
Comment (shepmaster) [inline src/test/run-pass/backtrace-debuginfo.rs]: I think clippy would say to use `!errors.is_empty()` ;-)

**Comment by estebank** [comment]
https://ci.appveyor.com/project/rust-lang/rust/build/1.0.6249/job/k7fthu23den40uef#L9116
```
Building stage2 tool cargo (x86_64-pc-windows-msvc)
   Compiling rustc-serialize v0.3.24
   Compiling num-traits v0.1.41
   Compiling glob v0.2.11
   Compiling hex v0.2.0
   Compiling dtoa v0.4.2
   Compiling winapi v0.2.8
   Compiling winapi-build v0.1.1
   Compiling scoped-tls v0.1.0
   Compiling percent-encoding v1.0.1
   Compiling winapi v0.3.4
   Compiling vcpkg v0.2.2
   Compiling unicode-normalization v0.1.5
   Compiling crossbeam v0.3.2
   Compiling semver-parser v0.7.0
   Compiling strsim v0.6.0
   Compiling shell-escape v0.1.3
   Compiling pkg-config v0.3.9
   Compiling rustc-demangle v0.1.5
   Compiling regex-syntax v0.4.2
   Compiling utf8-ranges v1.0.0
   Compiling hex v0.3.1
   Compiling scopeguard v0.1.2
   Compiling itoa v0.3.4
   Compiling crossbeam v0.2.12
   Compiling lazy_static v1.0.0
   Compiling unreachable v1.0.0
   Compiling toml v0.4.5
   Compiling serde_ignored v0.0.4
   Compiling num-integer v0.1.35
   Compiling num_cpus v1.8.0
   Compiling memchr v2.0.1
   Compiling num-complex v0.1.41
   Compiling advapi32-sys v0.2.0
   Compiling ws2_32-sys v0.2.1
   Compiling userenv-sys v0.2.0
   Compiling kernel32-sys v0.2.2
   Compiling filetime v0.1.15
   Compiling unicode-bidi v0.3.4
   Compiling semver v0.9.0
error: Could not compile `semver`.
warning: build failed, waiting for other jobs to finish...
error: build failed
command did not execute successfully: "C:\\projects\\rust\\build\\x86_64-pc-windows-msvc\\stage0/bin\\cargo.exe" "build" "--target" "x86_64-pc-windows-msvc" "--release" "--locked" "--color" "always" "--manifest-path" "C:\\projects\\rust\\src/tools/cargo\\Cargo.toml"
expected success, got: exit code: 101
failed to run: C:\projects\rust\build\bootstrap\debug\bootstrap test src/tools/cargo src/tools/cargotest src/test/pretty src/test/run-pass/pretty src/test/run-fail/pretty src/test/run-pass-valgrind/pretty src/test/run-pass-fulldeps/pretty src/test/run-fail-fulldeps/pretty
Build completed unsuccessfully in 0:01:32
make: *** [Makefile:54: check-aux] Error 1
Command exited with code 2
cat %CD%\sccache.log || exit 0
WARN:sccache::cache::s3: Got AWS error: Error(BadHTTPStatus(NotFound), State { next_error: None })
WARN:sccache::cache::s3: Got AWS error: Error(BadHTTPStatus(NotFound), State { next_error: None })
WARN:sccache::cache::s3: Got AWS error: Error(BadHTTPStatus(NotFound), State { next_error: None })
WARN:sccache::cache::s3: Got AWS error: Error(BadHTTPStatus(NotFound), State { next_error: None })
WARN:sccache::cache::s3: Got AWS error: Error(BadHTTPStatus(NotFound), State { next_error: None })
WARN:sccache::cache::s3: Got AWS error: Error(BadHTTPStatus(NotFound), State { next_error: None })
WARN:sccache::cache::s3: Got AWS error: Error(BadHTTPStatus(NotFound), State { next_error: None })
WARN:sccache::cache::s3: Got AWS error: Error(BadHTTPStatus(NotFound), State { next_error: None })
```

**Comment by alexcrichton** [comment]
For those following this PR, can anyone reproduce that failure? It should just be `./x.py build src/tools/cargo` in theory. @Zoxc maybe?

I've been compiling Cargo all day on my machine and have seen no segfaults yet...

**Comment by kennytm** [comment]
Segfault when compiling rustc_errors

<details>

```
   Compiling rustc_errors v0.0.0 (file:///C:/projects/rust/src/librustc_errors)
error: Could not compile `rustc_errors`.
Caused by:
  process didn't exit successfully: `C:\projects\rust\build\bootstrap/debug/rustc --crate-name rustc_errors librustc_errors\lib.rs --color always --error-format json --crate-type dylib --emit=dep-info,link -C prefer-dynamic -C opt-level=2 -C metadata=eda22672e0466ca3 -C extra-filename=-eda22672e0466ca3 --out-dir C:\projects\rust\build\x86_64-pc-windows-msvc\stage1-rustc\x86_64-pc-windows-msvc\release\deps --target x86_64-pc-windows-msvc -L dependency=C:\projects\rust\build\x86_64-pc-windows-msvc\stage1-rustc\x86_64-pc-windows-msvc\release\deps -L dependency=C:\projects\rust\build\x86_64-pc-windows-msvc\stage1-rustc\release\deps --extern syntax_pos=C:\projects\rust\build\x86_64-pc-windows-msvc\stage1-rustc\x86_64-pc-windows-msvc\release\deps\syntax_pos-f6df28a228fb1841.dll --extern serialize=C:\projects\rust\build\x86_64-pc-windows-msvc\stage1-rustc\x86_64-pc-windows-msvc\release\deps\serialize-45b43c6d4c0b56dc.dll --extern serialize=C:\projects\rust\build\x86_64-pc-windows-msvc\stage1-rustc\x86_64-pc-windows-msvc\release\deps\libserialize-45b43c6d4c0b56dc.rlib --extern unicode_width=C:\projects\rust\build\x86_64-pc-windows-msvc\stage1-rustc\x86_64-pc-windows-msvc\release\deps\libunicode_width-a47638fdb6149e19.rlib --extern rustc_data_structures=C:\projects\rust\build\x86_64-pc-windows-msvc\stage1-rustc\x86_64-pc-windows-msvc\release\deps\rustc_data_structures-cecf11680064ca3d.dll` (exit code: 3221225477)
```

</details>

**Comment by alexcrichton** [comment]
@bors: r=nikomatsakis

Juggling too many submodules...

**Comment by kennytm** [comment]
I guess you need to rebase?

<details>

```
[02:07:51] ---- [compile-fail] compile-fail\rfc-2126-extern-in-paths\single-segment.rs stdout ----
[02:07:51] 	
[02:07:51] error: C:/projects/rust/src/test/compile-fail/rfc-2126-extern-in-paths/single-segment.rs:15: unexpected error: '15:5: 15:11: unresolved import `::extern` [E0432]'
[02:07:51] 
[02:07:51] error: C:/projects/rust/src/test/compile-fail/rfc-2126-extern-in-paths/single-segment.rs:15: expected error not found: unresolved import `extern`
<snip>
[02:07:51] ---- [compile-fail] compile-fail\use-keyword.rs stdout ----
[02:07:51] 	
[02:07:51] error: C:/projects/rust/src/test/compile-fail/use-keyword.rs:18: unexpected error: '18:13: 18:23: unresolved import `::super` [E0432]'
[02:07:51] 
[02:07:51] error: C:/projects/rust/src/test/compile-fail/use-keyword.rs:21: unexpected error: '21:21: 21:30: unresolved import `::super` [E0432]'
[02:07:51] 
[02:07:51] error: C:/projects/rust/src/test/compile-fail/use-keyword.rs:18: expected error not found: unresolved import `super` [E0432]
[02:07:51] 
[02:07:51] error: C:/projects/rust/src/test/compile-fail/use-keyword.rs:21: expected error not found: unresolved import `super` [E0432]
<snip>
[02:07:51] ---- [compile-fail] compile-fail\use-mod-2.rs stdout ----
[02:07:51] 	
[02:07:51] error: C:/projects/rust/src/test/compile-fail/use-mod-2.rs:12: unexpected error: '12:16: 12:20: unresolved import `::self` [E0432]'
[02:07:51] 
[02:07:51] error: C:/projects/rust/src/test/compile-fail/use-mod-2.rs:16: unexpected error: '16:17: 16:21: unresolved import `::super` [E0432]'
[02:07:51] 
[02:07:51] error: C:/projects/rust/src/test/compile-fail/use-mod-2.rs:12: expected error not found: unresolved import `self` [E0432]
[02:07:51] 
[02:07:51] error: C:/projects/rust/src/test/compile-fail/use-mod-2.rs:16: expected error not found: unresolved import `super` [E0432]
<snip>
[02:07:51] failures:
[02:07:51]     [compile-fail] compile-fail\rfc-2126-extern-in-paths\single-segment.rs
[02:07:51]     [compile-fail] compile-fail\use-keyword.rs
[02:07:51]     [compile-fail] compile-fail\use-mod-2.rs
```

</details>

**Comment by alexcrichton** [comment]
Urgh. I doubt it'll actualy fix anything, but can't hurt...

@bors: r=nikomatsakis

**Comment by kennytm** [comment]
Same error 🤔

**Comment by alexcrichton** [comment]
**nothing** I've seen here came up when I was testing locally, and I can't reproduce just about any of the failures we're seeing. Gah!

I'm running a full [travis](https://travis-ci.org/rust-lang/rust/builds/338762591) and [appveyor](https://ci.appveyor.com/project/rust-lang/rust/build/1.0.6271) build that won't get canceled so we can hopefully see the full set of failures.

Help debugging these would also be greatly appreciated!

**Comment by kennytm** [comment]
AppVeyor is all green. Travis is also all green except `dist-i686-linux` has a 3-hour timeout. Very strange.

**Comment by kennytm** [comment]
`dist-i686-linux` linker error when building `cargo-vendor` when creating the plain-source tarball, no suitable C libraries (libssl, libcrypto, etc.) can be found.

<details>

```
[01:26:04]    Compiling cargo-vendor v0.1.4
[01:26:07] error: linking with `cc` failed: exit code: 1
[01:26:07]   |
[01:26:07]   = note: "cc" "-Wl,--as-needed" "-Wl,-z,noexecstack" "-m32" "-L" "/checkout/obj/build/i686-unknown-linux-gnu/stage0/lib/rustlib/i686-unknown-linux-gnu/lib" "/tmp/cargo-install.hVmoB6WRCMkz/debug/deps/cargo_vendor-52b6306fb2932454.cargo_vendor0.rcgu.o" "/tmp/cargo-install.hVmoB6WRCMkz/debug/deps/cargo_vendor-52b6306fb2932454.cargo_vendor1.rcgu.o" "/tmp/cargo-install.hVmoB6WRCMkz/debug/deps/cargo_vendor-52b6306fb2932454.cargo_vendor10.rcgu.o" "/tmp/cargo-install.hVmoB6WRCMkz/debug/deps/cargo_vendor-52b6306fb2932454.cargo_vendor11.rcgu.o" "/tmp/cargo-install.hVmoB6WRCMkz/debug/deps/cargo_vendor-52b6306fb2932454.cargo_vendor12.rcgu.o" "/tmp/cargo-install.hVmoB6WRCMkz/debug/deps/cargo_vendor-52b6306fb2932454.cargo_vendor13.rcgu.o" "/tmp/cargo-install.hVmoB6WRCMkz/debug/deps/cargo_vendor-52b6306fb2932454.cargo_vendor14.rcgu.o" "/tmp/cargo-install.hVmoB6WRCMkz/debug/deps/cargo_vendor-52b6306fb2932454.cargo_vendor15.rcgu.o" "/tmp/cargo-install.hVmoB6WRCMkz/debug/deps/cargo_vendor-52b6306fb2932454.cargo_vendor2.rcgu.o" "/tmp/cargo-install.hVmoB6WRCMkz/debug/deps/cargo_vendor-52b6306fb2932454.cargo_vendor3.rcgu.o" "/tmp/cargo-install.hVmoB6WRCMkz/debug/deps/cargo_vendor-52b6306fb2932454.cargo_vendor4.rcgu.o" "/tmp/cargo-install.hVmoB6WRCMkz/debug/deps/cargo_vendor-52b6306fb2932454.cargo_vendor5.rcgu.o" "/tmp/cargo-install.hVmoB6WRCMkz/debug/deps/cargo_vendor-52b6306fb2932454.cargo_vendor6.rcgu.o" "/tmp/cargo-install.hVmoB6WRCMkz/debug/deps/cargo_vendor-52b6306fb2932454.cargo_vendor7.rcgu.o" "/tmp/cargo-install.hVmoB6WRCMkz/debug/deps/cargo_vendor-52b6306fb2932454.cargo_vendor8.rcgu.o" "/tmp/cargo-install.hVmoB6WRCMkz/debug/deps/cargo_vendor-52b6306fb2932454.cargo_vendor9.rcgu.o" "-o" "/tmp/cargo-install.hVmoB6WRCMkz/debug/deps/cargo_vendor-52b6306fb2932454" "/tmp/cargo-install.hVmoB6WRCMkz/debug/deps/cargo_vendor-52b6306fb2932454.crate.allocator.rcgu.o" "-Wl,--gc-sections" "-pie" "-Wl,-z,relro,-z,now" "-nodefaultlibs" "-L" "/tmp/cargo-install.hVmoB6WRCMkz/debug/deps" "-L" "/tmp/cargo-install.hVmoB6WRCMkz/debug/build/curl-sys-21419d054e789bed/out/lib" "-L" "/usr/lib64" "-L" "/rustroot/lib" "-L" "/tmp/cargo-install.hVmoB6WRCMkz/debug/build/miniz-sys-6a6c7739f512d5ff/out" "-L" "/tmp/cargo-install.hVmoB6WRCMkz/debug/build/libgit2-sys-07aede3c2a157d99/out/lib" "-L" "/tmp/cargo-install.hVmoB6WRCMkz/debug/build/libssh2-sys-7ca0cc7c33e09949/out/lib" "-L" "/checkout/obj/build/i686-unknown-linux-gnu/stage0/lib/rustlib/i686-unknown-linux-gnu/lib" "-Wl,-Bstatic" "/tmp/cargo-install.hVmoB6WRCMkz/debug/deps/libcargo-150c90ffdf0dd9df.rlib" "/tmp/cargo-install.hVmoB6WRCMkz/debug/deps/libglob-b7d0cd6d68efe240.rlib" "/tmp/cargo-install.hVmoB6WRCMkz/debug/deps/libdocopt-151587842abaa70d.rlib" "/tmp/cargo-install.hVmoB6WRCMkz/debug/deps/libstrsim-0ce6d259442989ca.rlib" "/tmp/cargo-install.hVmoB6WRCMkz/debug/deps/libtoml-19a7b4335b1bb67c.rlib" "/tmp/cargo-install.hVmoB6WRCMkz/debug/deps/libsemver-60c198af02ebd311.rlib" "/tmp/cargo-install.hVmoB6WRCMkz/debug/deps/libflate2-a25d9108ba0ab006.rlib" "/tmp/cargo-install.hVmoB6WRCMkz/debug/deps/libcrates_io-27b381c2766de218.rlib" "/tmp/cargo-install.hVmoB6WRCMkz/debug/deps/librustc_serialize-b9312b96ad55ac9c.rlib" "/tmp/cargo-install.hVmoB6WRCMkz/debug/deps/libtar-cc3fa763c83ae7c9.rlib" "/tmp/cargo-install.hVmoB6WRCMkz/debug/deps/libfs2-e99f96d998821d55.rlib" "/tmp/cargo-install.hVmoB6WRCMkz/debug/deps/libcrossbeam-4ecdabb9c088f411.rlib" "/tmp/cargo-install.hVmoB6WRCMkz/debug/deps/liblog-a3e4ab12e48da7cc.rlib" "/tmp/cargo-install.hVmoB6WRCMkz/debug/deps/liblog-f09e1ef19fa14621.rlib" "/tmp/cargo-install.hVmoB6WRCMkz/debug/deps/libterm-6540250d3d606927.rlib" "/tmp/cargo-install.hVmoB6WRCMkz/debug/deps/libnum_cpus-30276abd71850c2b.rlib" "/tmp/cargo-install.hVmoB6WRCMkz/debug/deps/libfiletime-4d567f5e8c3d5c51.rlib" "/tmp/cargo-install.hVmoB6WRCMkz/debug/deps/libopenssl-3472106bf86c643e.rlib" "/tmp/cargo-install.hVmoB6WRCMkz/debug/deps/liblazy_static-e37a02a3f7a019ff.rlib" "/tmp/cargo-install.hVmoB6WRCMkz/debug/deps/libforeign_types-61ffa34387ff11d6.rlib" "/tmp/cargo-install.hVmoB6WRCMkz/debug/deps/libsemver_parser-cf238ec4a12856bc.rlib" "/tmp/cargo-install.hVmoB6WRCMkz/debug/deps/liblazy_static-af898616b5896f54.rlib" "/tmp/cargo-install.hVmoB6WRCMkz/debug/deps/libregex-d63908eb0daa42c4.rlib" "/tmp/cargo-install.hVmoB6WRCMkz/debug/deps/libutf8_ranges-53304ce48dffad98.rlib" "/tmp/cargo-install.hVmoB6WRCMkz/debug/deps/libregex_syntax-9b923eeefaf0e542.rlib" "/tmp/cargo-install.hVmoB6WRCMkz/debug/deps/libminiz_sys-5064659309cef5c8.rlib" "/tmp/cargo-install.hVmoB6WRCMkz/debug/deps/libaho_corasick-d999b726eae0772c.rlib" "/tmp/cargo-install.hVmoB6WRCMkz/debug/deps/libmemchr-3285c9315ce8e957.rlib" "/tmp/cargo-install.hVmoB6WRCMkz/debug/deps/libcurl-6d4b955eeb4ae353.rlib" "/tmp/cargo-install.hVmoB6WRCMkz/debug/deps/libsocket2-bc1506c3ae9b7391.rlib" "/tmp/cargo-install.hVmoB6WRCMkz/debug/deps/libcfg_if-bf3e253f5a946040.rlib" "/tmp/cargo-install.hVmoB6WRCMkz/debug/deps/libforeign_types_shared-6f684913d763aa2e.rlib" "/tmp/cargo-install.hVmoB6WRCMkz/debug/deps/libtempdir-3b62a7c0f71bb8b0.rlib" "/tmp/cargo-install.hVmoB6WRCMkz/debug/deps/libremove_dir_all-57549ab0ac6ca5b4.rlib" "/tmp/cargo-install.hVmoB6WRCMkz/debug/deps/libkernel32-3309f574e4bd2de7.rlib" "/tmp/cargo-install.hVmoB6WRCMkz/debug/deps/libwinapi-59cc3311b855aceb.rlib" "/tmp/cargo-install.hVmoB6WRCMkz/debug/deps/librand-5c31e65e4d78a721.rlib" "/tmp/cargo-install.hVmoB6WRCMkz/debug/deps/libgit2-9250183aab5b4be3.rlib" "/tmp/cargo-install.hVmoB6WRCMkz/debug/deps/libopenssl_probe-1eaa4e3d610ec7de.rlib" "/tmp/cargo-install.hVmoB6WRCMkz/debug/deps/libbitflags-1dae7ec6f58e35db.rlib" "/tmp/cargo-install.hVmoB6WRCMkz/debug/deps/liblibgit2_sys-71b83eb1c39bebfc.rlib" "/tmp/cargo-install.hVmoB6WRCMkz/debug/deps/libcurl_sys-8be80aa2ad58f2fc.rlib" "/tmp/cargo-install.hVmoB6WRCMkz/debug/deps/liblibssh2_sys-8800a257148c5850.rlib" "/tmp/cargo-install.hVmoB6WRCMkz/debug/deps/libopenssl_sys-450d76212dd1ee7e.rlib" "/tmp/cargo-install.hVmoB6WRCMkz/debug/deps/liblibz_sys-0a577a678807b8ca.rlib" "/tmp/cargo-install.hVmoB6WRCMkz/debug/deps/liburl-87e99267efd3c167.rlib" "/tmp/cargo-install.hVmoB6WRCMkz/debug/deps/libpercent_encoding-3944581bf4201a7b.rlib" "/tmp/cargo-install.hVmoB6WRCMkz/debug/deps/libidna-eeb84a3a65b23ae5.rlib" "/tmp/cargo-install.hVmoB6WRCMkz/debug/deps/libunicode_bidi-6740f37be99023e4.rlib" "/tmp/cargo-install.hVmoB6WRCMkz/debug/deps/libmatches-9cab137596b6324d.rlib" "/tmp/cargo-install.hVmoB6WRCMkz/debug/deps/libthread_local-faeb36104c28579f.rlib" "/tmp/cargo-install.hVmoB6WRCMkz/debug/deps/libthread_id-da0db74c14b49a0b.rlib" "/tmp/cargo-install.hVmoB6WRCMkz/debug/deps/libunicode_normalization-1c57b2cd1938cb99.rlib" "/tmp/cargo-install.hVmoB6WRCMkz/debug/deps/liblibc-cdb15e6309ae60c8.rlib" "/checkout/obj/build/i686-unknown-linux-gnu/stage0/lib/rustlib/i686-unknown-linux-gnu/lib/libstd-938dda056ad13111.rlib" "/checkout/obj/build/i686-unknown-linux-gnu/stage0/lib/rustlib/i686-unknown-linux-gnu/lib/libpanic_unwind-f5dd1ef098a5c8f8.rlib" "/checkout/obj/build/i686-unknown-linux-gnu/stage0/lib/rustlib/i686-unknown-linux-gnu/lib/libunwind-bb5acb9df7e498f3.rlib" "/checkout/obj/build/i686-unknown-linux-gnu/stage0/lib/rustlib/i686-unknown-linux-gnu/lib/liballoc_jemalloc-0ebe3fd131845c28.rlib" "/checkout/obj/build/i686-unknown-linux-gnu/stage0/lib/rustlib/i686-unknown-linux-gnu/lib/liballoc_system-df57dc7cc025dcf1.rlib" "/checkout/obj/build/i686-unknown-linux-gnu/stage0/lib/rustlib/i686-unknown-linux-gnu/lib/liblibc-2e3f740fdefd6639.rlib" "/checkout/obj/build/i686-unknown-linux-gnu/stage0/lib/rustlib/i686-unknown-linux-gnu/lib/liballoc-bececa3f06d7b952.rlib" "/checkout/obj/build/i686-unknown-linux-gnu/stage0/lib/rustlib/i686-unknown-linux-gnu/lib/libstd_unicode-0bf35aa9cf3c7736.rlib" "/checkout/obj/build/i686-unknown-linux-gnu/stage0/lib/rustlib/i686-unknown-linux-gnu/lib/libcore-a1c8e46ff2626be7.rlib" "/checkout/obj/build/i686-unknown-linux-gnu/stage0/lib/rustlib/i686-unknown-linux-gnu/lib/libcompiler_builtins-fa998ab3a8b22fdf.rlib" "-Wl,-Bdynamic" "-l" "ssl" "-l" "crypto" "-l" "z" "-l" "util" "-l" "util" "-l" "dl" "-l" "rt" "-l" "pthread" "-l" "gcc_s" "-l" "pthread" "-l" "c" "-l" "m" "-l" "rt" "-l" "pthread" "-l" "util" "-l" "util"
[01:26:07]   = note: /rustroot/lib/gcc/x86_64-unknown-linux-gnu/4.8.5/../../../../x86_64-unknown-linux-gnu/bin/ld: skipping incompatible /rustroot/lib/libssl.so when searching for -lssl
[01:26:07]           /rustroot/lib/gcc/x86_64-unknown-linux-gnu/4.8.5/../../../../x86_64-unknown-linux-gnu/bin/ld: skipping incompatible /rustroot/lib/libssl.a when searching for -lssl
[01:26:07]           /rustroot/lib/gcc/x86_64-unknown-linux-gnu/4.8.5/../../../../x86_64-unknown-linux-gnu/bin/ld: skipping incompatible /rustroot/lib/gcc/x86_64-unknown-linux-gnu/4.8.5/../../../../lib/libssl.so when searching for -lssl
[01:26:07]           /rustroot/lib/gcc/x86_64-unknown-linux-gnu/4.8.5/../../../../x86_64-unknown-linux-gnu/bin/ld: skipping incompatible /rustroot/lib/gcc/x86_64-unknown-linux-gnu/4.8.5/../../../../lib/libssl.a when searching for -lssl
[01:26:07]           /rustroot/lib/gcc/x86_64-unknown-linux-gnu/4.8.5/../../../../x86_64-unknown-linux-gnu/bin/ld: skipping incompatible /rustroot/lib/gcc/x86_64-unknown-linux-gnu/4.8.5/../../../libssl.so when searching for -lssl
[01:26:07]           /rustroot/lib/gcc/x86_64-unknown-linux-gnu/4.8.5/../../../../x86_64-unknown-linux-gnu/bin/ld: skipping incompatible /rustroot/lib/gcc/x86_64-unknown-linux-gnu/4.8.5/../../../libssl.a when searching for -lssl
[01:26:07]           /rustroot/lib/gcc/x86_64-unknown-linux-gnu/4.8.5/../../../../x86_64-unknown-linux-gnu/bin/ld: skipping incompatible /rustroot/lib/libssl.so when searching for -lssl
[01:26:07]           /rustroot/lib/gcc/x86_64-unknown-linux-gnu/4.8.5/../../../../x86_64-unknown-linux-gnu/bin/ld: skipping incompatible /rustroot/lib/libssl.a when searching for -lssl
[01:26:07]           /rustroot/lib/gcc/x86_64-unknown-linux-gnu/4.8.5/../../../../x86_64-unknown-linux-gnu/bin/ld: cannot find -lssl
[01:26:07]           /rustroot/lib/gcc/x86_64-unknown-linux-gnu/4.8.5/../../../../x86_64-unknown-linux-gnu/bin/ld: skipping incompatible /rustroot/lib/libcrypto.so when searching for -lcrypto
[01:26:07]           /rustroot/lib/gcc/x86_64-unknown-linux-gnu/4.8.5/../../../../x86_64-unknown-linux-gnu/bin/ld: skipping incompatible /rustroot/lib/libcrypto.a when searching for -lcrypto
[01:26:07]           /rustroot/lib/gcc/x86_64-unknown-linux-gnu/4.8.5/../../../../x86_64-unknown-linux-gnu/bin/ld: skipping incompatible /rustroot/lib/gcc/x86_64-unknown-linux-gnu/4.8.5/../../../../lib/libcrypto.so when searching for -lcrypto
[01:26:07]           /rustroot/lib/gcc/x86_64-unknown-linux-gnu/4.8.5/../../../../x86_64-unknown-linux-gnu/bin/ld: skipping incompatible /rustroot/lib/gcc/x86_64-unknown-linux-gnu/4.8.5/../../../../lib/libcrypto.a when searching for -lcrypto
[01:26:07]           /rustroot/lib/gcc/x86_64-unknown-linux-gnu/4.8.5/../../../../x86_64-unknown-linux-gnu/bin/ld: skipping incompatible /rustroot/lib/gcc/x86_64-unknown-linux-gnu/4.8.5/../../../libcrypto.so when searching for -lcrypto
[01:26:07]           /rustroot/lib/gcc/x86_64-unknown-linux-gnu/4.8.5/../../../../x86_64-unknown-linux-gnu/bin/ld: skipping incompatible /rustroot/lib/gcc/x86_64-unknown-linux-gnu/4.8.5/../../../libcrypto.a when searching for -lcrypto
[01:26:07]           /rustroot/lib/gcc/x86_64-unknown-linux-gnu/4.8.5/../../../../x86_64-unknown-linux-gnu/bin/ld: skipping incompatible /rustroot/lib/libcrypto.so when searching for -lcrypto
[01:26:07]           /rustroot/lib/gcc/x86_64-unknown-linux-gnu/4.8.5/../../../../x86_64-unknown-linux-gnu/bin/ld: skipping incompatible /rustroot/lib/libcrypto.a when searching for -lcrypto
[01:26:07]           /rustroot/lib/gcc/x86_64-unknown-linux-gnu/4.8.5/../../../../x86_64-unknown-linux-gnu/bin/ld: cannot find -lcrypto
[01:26:07]           /rustroot/lib/gcc/x86_64-unknown-linux-gnu/4.8.5/../../../../x86_64-unknown-linux-gnu/bin/ld: skipping incompatible /usr/lib64/libz.so when searching for -lz
[01:26:07]           /rustroot/lib/gcc/x86_64-unknown-linux-gnu/4.8.5/../../../../x86_64-unknown-linux-gnu/bin/ld: skipping incompatible /usr/lib64/libz.a when searching for -lz
[01:26:07]           /rustroot/lib/gcc/x86_64-unknown-linux-gnu/4.8.5/../../../../x86_64-unknown-linux-gnu/bin/ld: skipping incompatible /usr/lib64/libutil.so when searching for -lutil
[01:26:07]           /rustroot/lib/gcc/x86_64-unknown-linux-gnu/4.8.5/../../../../x86_64-unknown-linux-gnu/bin/ld: skipping incompatible /usr/lib64/libutil.a when searching for -lutil
[01:26:07]           /rustroot/lib/gcc/x86_64-unknown-linux-gnu/4.8.5/../../../../x86_64-unknown-linux-gnu/bin/ld: skipping incompatible /usr/lib64/libutil.so when searching for -lutil
[01:26:07]           /rustroot/lib/gcc/x86_64-unknown-linux-gnu/4.8.5/../../../../x86_64-unknown-linux-gnu/bin/ld: skipping incompatible /usr/lib64/libutil.a when searching for -lutil
[01:26:07]           /rustroot/lib/gcc/x86_64-unknown-linux-gnu/4.8.5/../../../../x86_64-unknown-linux-gnu/bin/ld: skipping incompatible /usr/lib64/libdl.so when searching for -ldl
[01:26:07]           /rustroot/lib/gcc/x86_64-unknown-linux-gnu/4.8.5/../../../../x86_64-unknown-linux-gnu/bin/ld: skipping incompatible /usr/lib64/libdl.a when searching for -ldl
[01:26:07]           /rustroot/lib/gcc/x86_64-unknown-linux-gnu/4.8.5/../../../../x86_64-unknown-linux-gnu/bin/ld: skipping incompatible /usr/lib64/librt.so when searching for -lrt
[01:26:07]           /rustroot/lib/gcc/x86_64-unknown-linux-gnu/4.8.5/../../../../x86_64-unknown-linux-gnu/bin/ld: skipping incompatible /usr/lib64/librt.a when searching for -lrt
[01:26:07]           /rustroot/lib/gcc/x86_64-unknown-linux-gnu/4.8.5/../../../../x86_64-unknown-linux-gnu/bin/ld: skipping incompatible /usr/lib64/libpthread.so when searching for -lpthread
[01:26:07]           /rustroot/lib/gcc/x86_64-unknown-linux-gnu/4.8.5/../../../../x86_64-unknown-linux-gnu/bin/ld: skipping incompatible /usr/lib64/libpthread.a when searching for -lpthread
[01:26:07]           collect2: error: ld returned 1 exit status
[01:26:07]           
[01:26:07] 
[01:26:07] error: aborting due to previous error
[01:26:07] 
[01:26:07] error: failed to compile `cargo-vendor v0.1.4`, intermediate artifacts can be found at `/tmp/cargo-install.hVmoB6WRCMkz`
[01:26:07] 
[01:26:07] Caused by:
[01:26:07]   Could not compile `cargo-vendor`.
[01:26:07] 
[01:26:07] To learn more, run the command again with --verbose.
```

</details>

**Comment by alexcrichton** [comment]
I guess we'll have to figure that out another day...

**Comment by estebank** [comment]
https://ci.appveyor.com/project/rust-lang/rust/build/1.0.6280/job/qf0j6abuio645if4#L12009

<details>

```
failures:
---- [compile-fail] compile-fail\rfc-2126-extern-in-paths\single-segment.rs stdout ----
	
error: C:/projects/rust/src/test/compile-fail/rfc-2126-extern-in-paths/single-segment.rs:15: unexpected error: '15:5: 15:11: unresolved import `::extern` [E0432]'
error: C:/projects/rust/src/test/compile-fail/rfc-2126-extern-in-paths/single-segment.rs:15: expected error not found: unresolved import `extern`
error: 1 unexpected errors found, 1 expected errors not found
status: exit code: 101
command: PATH="C:\projects\rust\build\i686-pc-windows-gnu\stage2\bin;C:\projects\rust\build\i686-pc-windows-gnu\stage0-tools\i686-pc-windows-gnu\release\deps;C:\projects\rust\build\i686-pc-windows-gnu\stage0-sysroot\lib\rustlib\i686-pc-windows-gnu\lib;C:\Program Files (x86)\Inno Setup 5;C:\Python27;C:\projects\rust\mingw32\bin;C:\msys64\usr\bin;C:\Perl\site\bin;C:\Perl\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0;C:\Program Files\7-Zip;C:\Program Files\Microsoft\Web Platform Installer;C:\Tools\GitVersion;C:\Tools\PsTools;C:\Program Files\Git LFS;C:\Program Files (x86)\Subversion\bin;C:\Program Files\Microsoft SQL Server\120\Tools\Binn;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\110\Tools\Binn;C:\Program Files (x86)\Microsoft SQL Server\120\Tools\Binn;C:\Program Files\Microsoft SQL Server\120\DTS\Binn;C:\Program Files (x86)\Microsoft SQL Server\120\Tools\Binn\ManagementStudio;C:\Tools\WebDriver;C:\Program Files (x86)\Microsoft SDKs\TypeScript\1.4;C:\Program Files (x86)\Microsoft Visual Studio 12.0\Common7\IDE\PrivateAssemblies;C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\wbin;C:\Ruby193\bin;C:\Tools\NUnit\bin;C:\Tools\xUnit;C:\Tools\MSpec;C:\Tools\Coverity\bin;C:\Program Files (x86)\CMake\bin;C:\go\bin;C:\Program Files\Java\jdk1.8.0\bin;C:\Python27;C:\Program Files\nodejs;C:\Program Files (x86)\iojs;C:\Program Files\iojs;C:\Users\appveyor\AppData\Roaming\npm;C:\Program Files\Microsoft SQL Server\130\Tools\Binn;C:\Program Files (x86)\MSBuild\14.0\Bin;C:\Tools\NuGet;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\CommonExtensions\Microsoft\TestWindow;C:\Program Files\Microsoft DNX\Dnvm;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\130\Tools\Binn;C:\Program Files (x86)\Microsoft SQL Server\130\Tools\Binn;C:\Program Files (x86)\Microsoft SQL Server\130\DTS\Binn;C:\Program Files\Microsoft SQL Server\130\DTS\Binn;C:\Program Files (x86)\Microsoft SQL Server\110\DTS\Binn;C:\Program Files (x86)\Microsoft SQL Server\120\DTS\Binn;C:\Program Files (x86)\Apache\Maven\bin;C:\Python27\Scripts;C:\Tools\NUnit3;C:\Program Files\Mercurial;C:\Program Files\LLVM\bin;C:\Program Files\dotnet;C:\Tools\curl\bin;C:\Program Files\Amazon\AWSCLI;C:\Program Files (x86)\Microsoft SQL Server\140\DTS\Binn;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions\Microsoft\SQLDB\DAC\140;C:\Program Files\Git\cmd;C:\Program Files\Git\usr\bin;C:\Tools\vcpkg;C:\Program Files\Microsoft Service Fabric\bin\Fabric\Fabric.Code;C:\Program Files\Microsoft SDKs\Service Fabric\Tools\ServiceFabricLocalClusterManager;C:\Program Files (x86)\Yarn\bin;C:\Program Files (x86)\Microsoft SQL Server\140\Tools\Binn;C:\Program Files\Microsoft SQL Server\140\Tools\Binn;C:\Program Files\Microsoft SQL Server\140\DTS\Binn;C:\Program Files (x86)\nodejs;C:\ProgramData\chocolatey\bin;C:\Program Files\PowerShell\6.0.0;C:\Program Files\erl9.2\bin;C:\Users\appveyor\AppData\Local\Yarn\bin;C:\Users\appveyor\AppData\Roaming\npm;C:\Program Files\AppVeyor\BuildAgent;C:\projects\rust;C:\projects\rust\handle" "C:\\projects\\rust\\build\\i686-pc-windows-gnu\\stage2\\bin\\rustc.exe" "C:\\projects\\rust\\src/test\\compile-fail\\rfc-2126-extern-in-paths\\single-segment.rs" "-L" "C:\\projects\\rust\\build\\i686-pc-windows-gnu\\test\\compile-fail" "--target=i686-pc-windows-gnu" "--error-format" "json" "-C" "prefer-dynamic" "-o" "C:\\projects\\rust\\build\\i686-pc-windows-gnu\\test\\compile-fail\\rfc-2126-extern-in-paths\\single-segment.stage2-i686-pc-windows-gnu.exe" "-Crpath" "-O" "-Zmiri" "-Zunstable-options" "-Lnative=C:\\projects\\rust\\build\\i686-pc-windows-gnu\\native\\rust-test-helpers" "-L" "C:\\projects\\rust\\build\\i686-pc-windows-gnu\\test\\compile-fail\\rfc-2126-extern-in-paths\\single-segment.stage2-i686-pc-windows-gnu.aux" "-A" "unused"
unexpected errors (from JSON output): [
    Error {
        line_num: 15,
        kind: Some(
            Error
        ),
        msg: "15:5: 15:11: unresolved import `::extern` [E0432]"
    }
]
not found errors (from test file): [
    Error {
        line_num: 15,
        kind: Some(
            Error
        ),
        msg: "unresolved import `extern`"
    }
]
thread '[compile-fail] compile-fail\rfc-2126-extern-in-paths\single-segment.rs' panicked at 'explicit panic', tools\compiletest\src\runtest.rs:1252:13
---- [compile-fail] compile-fail\use-keyword.rs stdout ----
	
error: C:/projects/rust/src/test/compile-fail/use-keyword.rs:18: unexpected error: '18:13: 18:23: unresolved import `::super` [E0432]'
error: C:/projects/rust/src/test/compile-fail/use-keyword.rs:21: unexpected error: '21:21: 21:30: unresolved import `::super` [E0432]'
error: C:/projects/rust/src/test/compile-fail/use-keyword.rs:18: expected error not found: unresolved import `super` [E0432]
error: C:/projects/rust/src/test/compile-fail/use-keyword.rs:21: expected error not found: unresolved import `super` [E0432]
error: 2 unexpected errors found, 2 expected errors not found
status: exit code: 101
command: PATH="C:\projects\rust\build\i686-pc-windows-gnu\stage2\bin;C:\projects\rust\build\i686-pc-windows-gnu\stage0-tools\i686-pc-windows-gnu\release\deps;C:\projects\rust\build\i686-pc-windows-gnu\stage0-sysroot\lib\rustlib\i686-pc-windows-gnu\lib;C:\Program Files (x86)\Inno Setup 5;C:\Python27;C:\projects\rust\mingw32\bin;C:\msys64\usr\bin;C:\Perl\site\bin;C:\Perl\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0;C:\Program Files\7-Zip;C:\Program Files\Microsoft\Web Platform Installer;C:\Tools\GitVersion;C:\Tools\PsTools;C:\Program Files\Git LFS;C:\Program Files (x86)\Subversion\bin;C:\Program Files\Microsoft SQL Server\120\Tools\Binn;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\110\Tools\Binn;C:\Program Files (x86)\Microsoft SQL Server\120\Tools\Binn;C:\Program Files\Microsoft SQL Server\120\DTS\Binn;C:\Program Files (x86)\Microsoft SQL Server\120\Tools\Binn\ManagementStudio;C:\Tools\WebDriver;C:\Program Files (x86)\Microsoft SDKs\TypeScript\1.4;C:\Program Files (x86)\Microsoft Visual Studio 12.0\Common7\IDE\PrivateAssemblies;C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\wbin;C:\Ruby193\bin;C:\Tools\NUnit\bin;C:\Tools\xUnit;C:\Tools\MSpec;C:\Tools\Coverity\bin;C:\Program Files (x86)\CMake\bin;C:\go\bin;C:\Program Files\Java\jdk1.8.0\bin;C:\Python27;C:\Program Files\nodejs;C:\Program Files (x86)\iojs;C:\Program Files\iojs;C:\Users\appveyor\AppData\Roaming\npm;C:\Program Files\Microsoft SQL Server\130\Tools\Binn;C:\Program Files (x86)\MSBuild\14.0\Bin;C:\Tools\NuGet;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\CommonExtensions\Microsoft\TestWindow;C:\Program Files\Microsoft DNX\Dnvm;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\130\Tools\Binn;C:\Program Files (x86)\Microsoft SQL Server\130\Tools\Binn;C:\Program Files (x86)\Microsoft SQL Server\130\DTS\Binn;C:\Program Files\Microsoft SQL Server\130\DTS\Binn;C:\Program Files (x86)\Microsoft SQL Server\110\DTS\Binn;C:\Program Files (x86)\Microsoft SQL Server\120\DTS\Binn;C:\Program Files (x86)\Apache\Maven\bin;C:\Python27\Scripts;C:\Tools\NUnit3;C:\Program Files\Mercurial;C:\Program Files\LLVM\bin;C:\Program Files\dotnet;C:\Tools\curl\bin;C:\Program Files\Amazon\AWSCLI;C:\Program Files (x86)\Microsoft SQL Server\140\DTS\Binn;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions\Microsoft\SQLDB\DAC\140;C:\Program Files\Git\cmd;C:\Program Files\Git\usr\bin;C:\Tools\vcpkg;C:\Program Files\Microsoft Service Fabric\bin\Fabric\Fabric.Code;C:\Program Files\Microsoft SDKs\Service Fabric\Tools\ServiceFabricLocalClusterManager;C:\Program Files (x86)\Yarn\bin;C:\Program Files (x86)\Microsoft SQL Server\140\Tools\Binn;C:\Program Files\Microsoft SQL Server\140\Tools\Binn;C:\Program Files\Microsoft SQL Server\140\DTS\Binn;C:\Program Files (x86)\nodejs;C:\ProgramData\chocolatey\bin;C:\Program Files\PowerShell\6.0.0;C:\Program Files\erl9.2\bin;C:\Users\appveyor\AppData\Local\Yarn\bin;C:\Users\appveyor\AppData\Roaming\npm;C:\Program Files\AppVeyor\BuildAgent;C:\projects\rust;C:\projects\rust\handle" "C:\\projects\\rust\\build\\i686-pc-windows-gnu\\stage2\\bin\\rustc.exe" "C:\\projects\\rust\\src/test\\compile-fail\\use-keyword.rs" "-L" "C:\\projects\\rust\\build\\i686-pc-windows-gnu\\test\\compile-fail" "--target=i686-pc-windows-gnu" "--error-format" "json" "-C" "prefer-dynamic" "-o" "C:\\projects\\rust\\build\\i686-pc-windows-gnu\\test\\compile-fail\\use-keyword.stage2-i686-pc-windows-gnu.exe" "-Crpath" "-O" "-Zmiri" "-Zunstable-options" "-Lnative=C:\\projects\\rust\\build\\i686-pc-windows-gnu\\native\\rust-test-helpers" "-L" "C:\\projects\\rust\\build\\i686-pc-windows-gnu\\test\\compile-fail\\use-keyword.stage2-i686-pc-windows-gnu.aux" "-A" "unused"
unexpected errors (from JSON output): [
    Error {
        line_num: 18,
        kind: Some(
            Error
        ),
        msg: "18:13: 18:23: unresolved import `::super` [E0432]"
    },
    Error {
        line_num: 21,
        kind: Some(
            Error
        ),
        msg: "21:21: 21:30: unresolved import `::super` [E0432]"
    }
]
not found errors (from test file): [
    Error {
        line_num: 18,
        kind: Some(
            Error
        ),
        msg: "unresolved import `super` [E0432]"
    },
    Error {
        line_num: 21,
        kind: Some(
            Error
        ),
        msg: "unresolved import `super` [E0432]"
    }
]
thread '[compile-fail] compile-fail\use-keyword.rs' panicked at 'explicit panic', tools\compiletest\src\runtest.rs:1252:13
---- [compile-fail] compile-fail\use-mod-2.rs stdout ----
	
error: C:/projects/rust/src/test/compile-fail/use-mod-2.rs:12: unexpected error: '12:16: 12:20: unresolved import `::self` [E0432]'
error: C:/projects/rust/src/test/compile-fail/use-mod-2.rs:16: unexpected error: '16:17: 16:21: unresolved import `::super` [E0432]'
error: C:/projects/rust/src/test/compile-fail/use-mod-2.rs:12: expected error not found: unresolved import `self` [E0432]
error: C:/projects/rust/src/test/compile-fail/use-mod-2.rs:16: expected error not found: unresolved import `super` [E0432]
error: 2 unexpected errors found, 2 expected errors not found
status: exit code: 101
command: PATH="C:\projects\rust\build\i686-pc-windows-gnu\stage2\bin;C:\projects\rust\build\i686-pc-windows-gnu\stage0-tools\i686-pc-windows-gnu\release\deps;C:\projects\rust\build\i686-pc-windows-gnu\stage0-sysroot\lib\rustlib\i686-pc-windows-gnu\lib;C:\Program Files (x86)\Inno Setup 5;C:\Python27;C:\projects\rust\mingw32\bin;C:\msys64\usr\bin;C:\Perl\site\bin;C:\Perl\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0;C:\Program Files\7-Zip;C:\Program Files\Microsoft\Web Platform Installer;C:\Tools\GitVersion;C:\Tools\PsTools;C:\Program Files\Git LFS;C:\Program Files (x86)\Subversion\bin;C:\Program Files\Microsoft SQL Server\120\Tools\Binn;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\110\Tools\Binn;C:\Program Files (x86)\Microsoft SQL Server\120\Tools\Binn;C:\Program Files\Microsoft SQL Server\120\DTS\Binn;C:\Program Files (x86)\Microsoft SQL Server\120\Tools\Binn\ManagementStudio;C:\Tools\WebDriver;C:\Program Files (x86)\Microsoft SDKs\TypeScript\1.4;C:\Program Files (x86)\Microsoft Visual Studio 12.0\Common7\IDE\PrivateAssemblies;C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\wbin;C:\Ruby193\bin;C:\Tools\NUnit\bin;C:\Tools\xUnit;C:\Tools\MSpec;C:\Tools\Coverity\bin;C:\Program Files (x86)\CMake\bin;C:\go\bin;C:\Program Files\Java\jdk1.8.0\bin;C:\Python27;C:\Program Files\nodejs;C:\Program Files (x86)\iojs;C:\Program Files\iojs;C:\Users\appveyor\AppData\Roaming\npm;C:\Program Files\Microsoft SQL Server\130\Tools\Binn;C:\Program Files (x86)\MSBuild\14.0\Bin;C:\Tools\NuGet;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\CommonExtensions\Microsoft\TestWindow;C:\Program Files\Microsoft DNX\Dnvm;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\130\Tools\Binn;C:\Program Files (x86)\Microsoft SQL Server\130\Tools\Binn;C:\Program Files (x86)\Microsoft SQL Server\130\DTS\Binn;C:\Program Files\Microsoft SQL Server\130\DTS\Binn;C:\Program Files (x86)\Microsoft SQL Server\110\DTS\Binn;C:\Program Files (x86)\Microsoft SQL Server\120\DTS\Binn;C:\Program Files (x86)\Apache\Maven\bin;C:\Python27\Scripts;C:\Tools\NUnit3;C:\Program Files\Mercurial;C:\Program Files\LLVM\bin;C:\Program Files\dotnet;C:\Tools\curl\bin;C:\Program Files\Amazon\AWSCLI;C:\Program Files (x86)\Microsoft SQL Server\140\DTS\Binn;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions\Microsoft\SQLDB\DAC\140;C:\Program Files\Git\cmd;C:\Program Files\Git\usr\bin;C:\Tools\vcpkg;C:\Program Files\Microsoft Service Fabric\bin\Fabric\Fabric.Code;C:\Program Files\Microsoft SDKs\Service Fabric\Tools\ServiceFabricLocalClusterManager;C:\Program Files (x86)\Yarn\bin;C:\Program Files (x86)\Microsoft SQL Server\140\Tools\Binn;C:\Program Files\Microsoft SQL Server\140\Tools\Binn;C:\Program Files\Microsoft SQL Server\140\DTS\Binn;C:\Program Files (x86)\nodejs;C:\ProgramData\chocolatey\bin;C:\Program Files\PowerShell\6.0.0;C:\Program Files\erl9.2\bin;C:\Users\appveyor\AppData\Local\Yarn\bin;C:\Users\appveyor\AppData\Roaming\npm;C:\Program Files\AppVeyor\BuildAgent;C:\projects\rust;C:\projects\rust\handle" "C:\\projects\\rust\\build\\i686-pc-windows-gnu\\stage2\\bin\\rustc.exe" "C:\\projects\\rust\\src/test\\compile-fail\\use-mod-2.rs" "-L" "C:\\projects\\rust\\build\\i686-pc-windows-gnu\\test\\compile-fail" "--target=i686-pc-windows-gnu" "--error-format" "json" "-C" "prefer-dynamic" "-o" "C:\\projects\\rust\\build\\i686-pc-windows-gnu\\test\\compile-fail\\use-mod-2.stage2-i686-pc-windows-gnu.exe" "-Crpath" "-O" "-Zmiri" "-Zunstable-options" "-Lnative=C:\\projects\\rust\\build\\i686-pc-windows-gnu\\native\\rust-test-helpers" "-L" "C:\\projects\\rust\\build\\i686-pc-windows-gnu\\test\\compile-fail\\use-mod-2.stage2-i686-pc-windows-gnu.aux" "-A" "unused"
unexpected errors (from JSON output): [
    Error {
        line_num: 12,
        kind: Some(
            Error
        ),
        msg: "12:16: 12:20: unresolved import `::self` [E0432]"
    },
    Error {
        line_num: 16,
        kind: Some(
            Error
        ),
        msg: "16:17: 16:21: unresolved import `::super` [E0432]"
    }
]
not found errors (from test file): [
    Error {
        line_num: 12,
        kind: Some(
            Error
        ),
        msg: "unresolved import `self` [E0432]"
    },
    Error {
        line_num: 16,
        kind: Some(
            Error
        ),
        msg: "unresolved import `super` [E0432]"
    }
]
thread '[compile-fail] compile-fail\use-mod-2.rs' panicked at 'explicit panic', tools\compiletest\src\runtest.rs:1252:13
failures:
    [compile-fail] compile-fail\rfc-2126-extern-in-paths\single-segment.rs
    [compile-fail] compile-fail\use-keyword.rs
    [compile-fail] compile-fail\use-mod-2.rs
test result: FAILED. 2529 passed; 3 failed; 15 ignored; 0 measured; 0 filtered out
```

</details>

**Comment by alexcrichton** [comment]
No idea what's happening. 

## Undiagnosed failures so far

**Wrong error message in compile-fail tests**

* https://ci.appveyor.com/project/rust-lang/rust/build/1.0.6263/job/74yea2qqd4fyjexh - i686-pc-windows-gnu
* https://ci.appveyor.com/project/rust-lang/rust/build/1.0.6280/job/qf0j6abuio645if4 - i686-pc-windows-gnu
* https://travis-ci.org/rust-lang/rust/jobs/338698482 - x86_64-apple-darwin

**Failed to compile `semver`, presumably segfault**

* https://ci.appveyor.com/project/rust-lang/rust/build/1.0.6249/job/k7fthu23den40uef - x86_64-pc-windows-msvc

## Fixed failures so far 

**Failed to cross-compiled emscripten LLVM** - fixed by not triggering cross-compile logic for Emscripten LLVM

* https://travis-ci.org/rust-lang/rust/jobs/338236422 - i686-unknown-linux-gnu dist

**Segfault compiling `rustc_errors** - fixed by cherry-picking fix for https://bugs.llvm.org/show_bug.cgi?id=36184

* https://ci.appveyor.com/project/rust-lang/rust/build/1.0.6258/job/7xsshsx7a86y8eqy - x86_64-pc-windows-msvc
* https://ci.appveyor.com/project/rust-lang/rust/build/1.0.6198/job/f165dj70uwt23d2n - x86_64-pc-windows-msvc
* https://ci.appveyor.com/project/rust-lang/rust/build/1.0.6191/job/ut2hoej8hp46pnrg - x86_64-pc-windows-msvc

**backtrace-debuginfo test fails on MSVC** - fixed by force disabling optimizations in the test

* https://ci.appveyor.com/project/rust-lang/rust/build/1.0.6245/job/oakhf2wcm6842lc5 - x86_64-pc-windows-msvc

**failed to install cargo-vendor in i686-unknown-linux-gnu dist** - fixed by avoiding updating the image

* https://travis-ci.org/rust-lang/rust/jobs/339148361 - i686-unknown-linux-gnu

**Comment by cuviper** [comment]
Maybe it's time to step back to LLVM 5? That will still be a worthwhile upgrade...

**Comment by alexcrichton** [comment]
@cuviper I'm personally gunning for LLVM 6 b/c of the wasm benefits (most notably enabling us to use LLD), but if you'd like to spearhead an LLVM 5 upgrade please do!

**Comment by kennytm** [comment]
@alexcrichton I still can't reproduce any of the errors, but I noted that `src/rustllvm/llvm-rebuild-trigger` is not updated, so people with an old build won't automatically get the new LLVM (this doesn't affect the CI for sure).

**Comment by alexcrichton** [comment]
@bors: r=nikomatsakis

Inserting some debugging code recommended by @eddyb, let's see what happens

**Comment by alexcrichton** [comment]
@bors: r=nikomatsakis

This is likely going to fail, no changes here. When it starts testing though I'm doing to disable the bots that cancel PRs. I'm curious how far this gets on the rest of AppVeyor/Travis on the `auto` branch (as apparently it's special from other branches ???)

**Comment by kennytm** [comment]
@alexcrichton why not use the `try` branch? (Assuming `auto` isn't really magical)

**Comment by alexcrichton** [comment]
@kennytm this unfortunately already passed on the `try` branch...

While true that in theory `auto` is special in no way, my [previous test](https://github.com/rust-lang/rust/pull/47828#issuecomment-363949265) seems to refute this claim. I ran **everything** on AppVeyor/Travis in the exact same configuration as `auto` with the only deviation being a different branch name. And everything passed ;_;

**Comment by kennytm** [comment]
@alexcrichton Your previous test uses the `llvm-6-try` branch though; what I mean is edit the `.travis.yml`/`appveyor.yml` and start a `@bors try`.

**Comment by alexcrichton** [comment]
@kennytm hm but wouldn't that be the same thing? In that the branch name shouldn't actually matter, and `@bors: try` I think would mostly just trigger it before "real bors" comes along, right? (although I may be misunderstanding)

**Comment by kennytm** [comment]
@alexcrichton in `@bors try` and `@bors r+`, the bot will create a merge commit with the latest master, which *might* introduce some difference 🙃

**Comment by alexcrichton** [comment]
True! Guess it can't hurt..

**Comment by alexcrichton** [comment]
@kennytm also this has such a high chance of failing feel free to steal the position in the queue w/ a rollup whenever! This'll stick around..

**Comment by alexcrichton** [comment]
[Travis](https://travis-ci.org/rust-lang/rust/builds/339650076) and [AppVeyor](https://ci.appveyor.com/project/rust-lang/rust/build/1.0.6289) should fill in over time for the try run.

**Comment by kennytm** [comment]
Ok I’ll deprioritize this then 😉

@bors p=1

**Comment by shepmaster** [comment]
> The job exceeded the maximum time limit for jobs, and has been terminated.

**Comment by alexcrichton** [comment]
Good lord this is infurating. AppVeyor is all green and Travis just timed out as its caches weren't primed.

@bors: r=nikomatsakis

Added more debugging code, but this is quickly becoming hopeless.

**Comment by estebank** [comment]
Is it possible to increase the 3hs timeout?

**Comment by alexcrichton** [comment]
Unfortunately no but https://github.com/rust-lang/rust/pull/48098 will make the builder finish faster (I hope)

**Comment by kennytm** [comment]
o_O The debugging code seems harmless, but is this supposed to be get actually merged now?

**Comment by alexcrichton** [comment]
@kennytm I'm sort of just glad to have this done with, but I'll send a follow-up to clean up that code. With https://github.com/rust-lang/rust/pull/47657#issuecomment-364632724 though it seems like it's not helping anyway...

**Comment by shepmaster** [comment]
> With #47657 (comment) though it seems like it's not helping anyway...

I think you meant to refer to #48116?

**Comment by alexcrichton** [comment]
@shepmaster oh I was just linking to the failure on #47657, but yeah #48116 is in general tracking the failure.

**Comment by fzzr-** [comment]
Now really looking forward to the [bitcode](https://llvm.org/docs/BitCodeFormat.html) feature of LLVM7. Today - LLVM6, tomorrow - LLVM7!

**Comment by martell** [comment]
@alexcrichton 
Author of https://reviews.llvm.org/D29892 here

```rust-lang/llvm@9eb9267 - we currently suffer on MSVC from an upstream bug
which although diagnosed to a particular revision isn't currently fixed
upstream (and the bug itself doesn't seem too active). This commit is a
partial revert of the suspected cause of this regression (found via a
bisection). I'm sort of hoping that this eventually gets fixed upstream with a
similar fix (which we can replace in our branch), but for now I'm also hoping
it's a relatively harmless change to have.
```

Let's make this bug report a little more active and see if we can find the correct fix. :)

**Comment by gaming-hacker** [comment]
Not to nag but has this issue with llvm-60 been resolved on OSX/Linux and merged into master?

**Comment by shepmaster** [comment]
@gaming-hacker 

Yes it has been merged. You can tell by scrolling to the top of the page and checking out the header:

image

If you click through [to the commit](https://github.com/rust-lang/rust/commit/6b7b6b63a928479a29d9fc1282e553e409c66934), you can see which tags the commit is part of:

image

You can also check out the [1.25 release notes](https://blog.rust-lang.org/2018/03/29/Rust-1.25.html) which lists this (emphasis mine):

> The last few releases have been relatively minor, but Rust 1.25 contains a bunch of stuff! The first one is straightforward: **we’ve upgraded to LLVM 6 from LLVM 4**

**Comment by gaming-hacker** [comment]
Ah thanks, i use source tree as a gui to display the status of the commits and it shows these as unmerged, i'll report a bug to source tree.
