### PR TITLE
For [E0308]: mismatched types, when expr is in an arm's body, not add semicolon ';' at the end of it.

### LINKED ISSUE #126222: "you might have meant to return this value" suggests invalid syntax
### Code

```Rust
fn dothing() -> i32 {
    match 5 {
        x => dbg!(x),
    }
    todo!()
}
```

### Current output

```Shell
Compiling playground v0.0.1 (/playground)
error[E0308]: mismatched types
 --> src/lib.rs:3:14
  |
3 |         x => dbg!(x),
  |              ^^^^^^^ expected `()`, found integer
  |
  = note: this error originates in the macro `dbg` (in Nightly builds, run with -Z macro-backtrace for more info)
help: you might have meant to return this value
  |
3 |         x => return dbg!(x);,
  |              ++++++        +

For more information about this error, try `rustc --explain E0308`.
error: could not compile `playground` (lib) due to 1 previous error
```

### Desired output

```Shell
Compiling playground v0.0.1 (/playground)
error[E0308]: mismatched types
 --> src/lib.rs:3:14
  |
3 |         x => dbg!(x),
  |              ^^^^^^^ expected `()`, found integer
  |
  = note: this error originates in the macro `dbg` (in Nightly builds, run with -Z macro-backtrace for more info)
help: you might have meant to return this value
  |
3 |         x => return dbg!(x),
  |              ++++++        

For more information about this error, try `rustc --explain E0308`.
error: could not compile `playground` (lib) due to 1 previous error
```

### Rationale and extra context

when using `#![feature(rustc_private)]` i even got this suggestion recommending i return DefKind from the GlobalCtxt::enter closure, which isn't even remotely the right type.  it also seems to only show up when using macros?  all around quite strange. 

### Other cases

_No response_

### Rust Version

```Shell
rustc 1.81.0-nightly (a70b2ae57 2024-06-09)
binary: rustc
commit-hash: a70b2ae57713ed0e7411c059d582ab382fc4166a
commit-date: 2024-06-09
host: x86_64-unknown-linux-gnu
release: 1.81.0-nightly
LLVM version: 18.1.7
```

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by surechen**
For [E0308]: mismatched types, when expr is in an arm's body, and it is the end expr without a semicolon of the block, not add semicolon ';' at the end of it.

fixes #126222

### CODE REVIEW

File: compiler/rustc_hir_typeck/src/fn_ctxt/suggestions.rs [hunk 1]
```diff
@@ -1125,11 +1123,59 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
...
+
             err.multipart_suggestion(
                 "you might have meant to return this value",
                 vec![
                     (span.shrink_to_lo(), "return ".to_string()),
-                    (span.shrink_to_hi(), ";".to_string()),
+                    if !is_in_arm(expr, self.tcx) {
+                        (span.shrink_to_hi(), ";".to_string())
+                    } else {
+                        (span.shrink_to_hi(), "".to_string())
```
Comment (compiler-errors) [inline compiler/rustc_hir_typeck/src/fn_ctxt/suggestions.rs:1177]: You can't add an empty suggestion. I would pull this `vec![]` into a separate, and only `suggestions.push()` if the `if` statement is true.

Comment (surechen) [reply compiler/rustc_hir_typeck/src/fn_ctxt/suggestions.rs]: > You can't add an empty suggestion. I would pull this `vec![]` into a separate, and only `suggestions.push()` if the `if` statement is true.

Done. Thank you.

File: tests/ui/mismatched_types/mismatched-types-issue-126222.stderr [hunk 2]
```diff
@@ -0,0 +1,51 @@
...
+  --> $DIR/mismatched-types-issue-126222.rs:15:17
+   |
+LL |                 dbg!(x)
+   |                 ^^^^^^^ expected `()`, found integer
+   |
+   = note: this error originates in the macro `dbg` (in Nightly builds, run with -Z macro-backtrace for more info)
+help: you might have meant to return this value
+   |
+LL |                 return dbg!(x)
+   |                 ++++++
```
Comment (estebank) [inline tests/ui/mismatched_types/mismatched-types-issue-126222.stderr:23]: I'm somewhat surprised: shouldn't these suggestions include a trailing `;`?

File: compiler/rustc_hir_typeck/src/fn_ctxt/suggestions.rs [hunk 3]
```diff
@@ -1125,12 +1123,56 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
...
+            // When the expr is in an `arm node`'s body, we shouldn't add semicolon ';' at the end.
+            // For example:
+            // fn mismatch_types() -> i32 {
+            //     match 1 {
+            //         x => dbg!(x),
+            //     }
+            //     todo!()
+            // }
+            // -------------^^^^^^^-
+            // Not add semicolon ';' at the end of expr 'dbg!(x)'
```
Comment (estebank) [inline compiler/rustc_hir_typeck/src/fn_ctxt/suggestions.rs:1135]:
```suggestion
            // Don't add semicolon `;` at the end of `dbg!(x)` expr
```

File: compiler/rustc_hir_typeck/src/fn_ctxt/suggestions.rs [hunk 4]
```diff
@@ -1125,12 +1123,56 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
                 self.tcx.hir().span_with_body(self.tcx.local_def_id_to_hir_id(fn_id)),
             )
         {
-            err.multipart_suggestion(
+            // When the expr is in an `arm node`'s body, we shouldn't add semicolon ';' at the end.
```
Comment (estebank) [inline compiler/rustc_hir_typeck/src/fn_ctxt/suggestions.rs:1126]:
```suggestion
            // When the expr is in a match arm's body, we shouldn't add semicolon ';' at the end.
```

File: tests/ui/mismatched_types/mismatched-types-issue-126222.stderr (hunk 2 above)
Comment (estebank) [reply tests/ui/mismatched_types/mismatched-types-issue-126222.stderr:23]: I'm assuming this is because `dbg` expands to a block expression, right?

Comment (surechen) [reply tests/ui/mismatched_types/mismatched-types-issue-126222.stderr:23]: > I'm somewhat surprised: shouldn't these suggestions include a trailing `;`?

Thank you.
Here I think because in the return expression after match arm the "; " is unnecessary, and the diagnostic suggestion may make error expr like "return something; ,", so in this case, I recommend using the `return something` without semicolon `;`.

Comment (estebank) [reply tests/ui/mismatched_types/mismatched-types-issue-126222.stderr:23]: It is *idiomatic* for statements like `return` to be ended with a `;`, regardless of whether it is *valid code* or not. That being said, it doesn't matter as much, as long as the suggestions produce valid code.
