### PR TITLE
Fix clashing_extern_declarations stack overflow for recursive types.

### LINKED ISSUE #75512: Stack overflow in rustc frontend on Windows
It seems rustc can no longer handle how much is defined in these two binding files. If I comment out either module, it will successfully build. It was previously building on `rustc 1.45.2 (d3fb005a3 2020-07-31)`.

### Code

Building this project on Windows:
https://github.com/gamozolabs/applepie/tree/master/whvp_bindings

### Meta

`rustc --version --verbose`:
```
rustc 1.47.0-nightly (81dc88f88 2020-08-13)
binary: rustc
commit-hash: 81dc88f88f92ba8ad7465f9cba10c12d3a7b70f1
commit-date: 2020-08-13
host: x86_64-pc-windows-msvc
release: 1.47.0-nightly
LLVM version: 10.0
```

### Error output

```
thread 'rustc' has overflowed its stack
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
2020-08-14T02:29:59.465476Z  INFO rustc_mir::interpret::eval_context: LEAVING(0) winhvemulation::COMPARTMENT_ID_DEFAULT_COMPARTMENT_ID (unwinding = false)
2020-08-14T02:29:59.469195Z  INFO rustc_mir::interpret::eval_context: ENTERING(0) winhvemulation::_EXCEPTION_DISPOSITION_ExceptionContinueExecution
2020-08-14T02:29:59.469231Z  INFO rustc_mir::interpret::step: _0 = const 0_i32
2020-08-14T02:29:59.469251Z  INFO rustc_mir::interpret::step: return
2020-08-14T02:29:59.469260Z  INFO rustc_mir::interpret::eval_context: LEAVING(0) winhvemulation::_EXCEPTION_DISPOSITION_ExceptionContinueExecution (unwinding = false)
2020-08-14T02:29:59.469373Z  INFO rustc_mir::interpret::eval_context: ENTERING(0) winhvemulation::_EXCEPTION_DISPOSITION_ExceptionContinueSearch
2020-08-14T02:29:59.469391Z  INFO rustc_mir::interpret::step: _0 = const 1_i32
2020-08-14T02:29:59.469404Z  INFO rustc_mir::interpret::step: return
2020-08-14T02:29:59.469412Z  INFO rustc_mir::interpret::eval_context: LEAVING(0) winhvemulation::_EXCEPTION_DISPOSITION_ExceptionContinueSearch (unwinding = false)
2020-08-14T02:29:59.469493Z  INFO rustc_mir::interpret::eval_context: ENTERING(0) winhvemulation::_EXCEPTION_DISPOSITION_ExceptionNestedException
2020-08-14T02:29:59.469506Z  INFO rustc_mir::interpret::step: _0 = const 2_i32
2020-08-14T02:29:59.469518Z  INFO rustc_mir::interpret::step: return
2020-08-14T02:29:59.469525Z  INFO rustc_mir::interpret::eval_context: LEAVING(0) winhvemulation::_EXCEPTION_DISPOSITION_ExceptionNestedException (unwinding = false)
2020-08-14T02:29:59.469587Z  INFO rustc_mir::interpret::eval_context: ENTERING(0) winhvemulation::_EXCEPTION_DISPOSITION_ExceptionCollidedUnwind
2020-08-14T02:29:59.469597Z  INFO rustc_mir::interpret::step: _0 = const 3_i32
2020-08-14T02:29:59.475783Z  INFO rustc_mir::interpret::step: return
2020-08-14T02:29:59.475808Z  INFO rustc_mir::interpret::eval_context: LEAVING(0) winhvemulation::_EXCEPTION_DISPOSITION_ExceptionCollidedUnwind (unwinding = false)

thread 'rustc' has overflowed its stack
```

</p>
</details>

### PR DESCRIPTION
**Pull request by jumbatm**
Fixes #75512.

Adds a seen set to `structurally_same_type` to avoid recursing indefinitely for types which contain values of the same type through a pointer or reference.

### CODE REVIEW

**Comment by petrochenkov** [comment]
Could someone else review this? I don't have the capacity.
r? @lcnr for example

File: src/test/ui/lint/clashing-extern-fn-recursion.rs [hunk 1]
```diff
@@ -0,0 +1,117 @@
...
+mod ref_recursion_once_removed {
+    mod a {
+        #[repr(C)]
+        struct Reffy1<'a> {
+            reffy: &'a Reffy1<'a>,
+        }
+
+        struct Reffy2<'a> {
+            reffy: &'a Reffy2<'a>,
+        }
```
Comment (lcnr) [inline src/test/ui/lint/clashing-extern-fn-recursion.rs:97]: did you make a typo here? you currently have a `Reffy1 -> Reffy1` cycle

File: src/librustc_lint/builtin.rs [hunk 2]
```diff
@@ -2153,123 +2153,208 @@ impl ClashingExternDeclarations {
...
-                        let a_fields = a_def.variants.iter().flat_map(|v| v.fields.iter());
-                        let b_fields = b_def.variants.iter().flat_map(|v| v.fields.iter());
-                        compare_layouts(a, b)
+                        match (a_kind, b_kind) {
+                            (Adt(_, a_substs), Adt(_, b_substs)) => {
+                                let a = a.subst(cx.tcx, a_substs);
+                                let b = b.subst(cx.tcx, b_substs);
+                                debug!("Comparing {:?} and {:?}", a, b);
+
+                                if let (Adt(a_def, ..), Adt(b_def, ..)) = (&a.kind, &b.kind) {
```
Comment (lcnr) [inline src/librustc_lint/builtin.rs:2236]: why aren't you directly taking the def from the match statement here? `subst` doesn't change `DefId`s, does it?

File: src/librustc_lint/builtin.rs [hunk 3]
```diff
@@ -2153,123 +2153,208 @@ impl ClashingExternDeclarations {
...
+                                } else {
+                                    unreachable!()
+                                }
+                            }
+                            (Array(a_ty, a_const), Array(b_ty, b_const)) => {
+                                // For arrays, we also check the constness of the type.
+                                a_const.val == b_const.val
+                                    && structurally_same_type_impl(
+                                        seen_types, cx, a_const.ty, b_const.ty, ckind,
+                                    )
```
Comment (lcnr) [inline src/librustc_lint/builtin.rs:2265]:
```suggestion
```

Considering that this runs after analysis and only if there are no errors, this check really shouldn't be needed afaict.

File: src/librustc_lint/builtin.rs [hunk 4]
```diff
@@ -2153,123 +2153,208 @@ impl ClashingExternDeclarations {
...
+                                    && structurally_same_type_impl(
+                                        seen_types, cx, a_ty, b_ty, ckind,
+                                    )
+                            }
+                            (Slice(a_ty), Slice(b_ty)) => {
+                                structurally_same_type_impl(seen_types, cx, a_ty, b_ty, ckind)
+                            }
+                            (RawPtr(a_tymut), RawPtr(b_tymut)) => {
+                                a_tymut.mutbl == b_tymut.mutbl
```
Comment (lcnr) [inline src/librustc_lint/builtin.rs:2274]: while not part of this PR I would expect `*const T` and `*mut T` to be structurally equal.

To my knowledge they only differ in variance

File: src/librustc_lint/builtin.rs [hunk 5]
```diff
@@ -2153,123 +2153,208 @@ impl ClashingExternDeclarations {
...
+        ) -> bool {
+            debug!("structurally_same_type_impl(cx, a = {:?}, b = {:?})", a, b);
+            match seen_types.get(a, b) {
+                // If we've already computed the result, just return the memoized result.
+                SeenSetResult::Computed(result) => result,
+                // We are already in the process of computing structural sameness for this type,
+                // meaning we've found a cycle. The types are structurally same, then.
+                SeenSetResult::Computing => true,
+                // We haven't seen this combination of types at all -- compute their sameness.
+                SeenSetResult::Unseen => {
```
Comment (lcnr) [inline src/librustc_lint/builtin.rs:2206]:
```suggestion
            match seen_types.get(a, b) {
                // If we've already computed the result, just return the memoized result.
                SeenSetResult::Computed(result) => return result,
                // We are already in the process of computing structural sameness for this type,
                // meaning we've found a cycle. The types are structurally same, then.
                SeenSetResult::Computing => return true,
                // We haven't seen this combination of types at all -- compute their sameness.
                SeenSetResult::Unseen => (),
            }
```
nit: This function has a fairly large indentation, so using this match as an early exit would be cleaner imo

File: src/librustc_lint/builtin.rs [hunk 6]
```diff
@@ -2153,123 +2153,208 @@ impl ClashingExternDeclarations {
...
+        // the result.
+        struct SeenSet<'tcx>(FxHashMap<(Ty<'tcx>, Ty<'tcx>), Option<bool>>);
+
+        enum SeenSetResult {
+            /// We've never seen this combination of types.
+            Unseen,
+            /// We've seen this combination of types, but are still computing the result.
+            Computing,
+            /// We've seen this combination of types, and have already computed the result.
+            Computed(bool),
```
Comment (lcnr) [inline src/librustc_lint/builtin.rs:2167]: Do we need a `HashMap` here? Afaict a hashset would be enough.

`Computed(true)` does the same as `Computing` and `Computed(false)` should have already caused an early exit.

I think it's enough to only store if we already visited a type.

Comment (lcnr) [reply src/librustc_lint/builtin.rs:2167]: (at this point using a new struct here might even be slightly too complex, so we could "just" use `FxHashSet<(Ty<'tcx>, Ty<'tcx>)>` directly here)

Comment (jumbatm) [reply src/librustc_lint/builtin.rs:2167]: HashSet would definitely suffice. I've only gone with a map here because I figured if I'm needing to store every combination of types encountered anyway, I might as well also store the result once I know it. 

To be fair, though, now that I think about it, it's probably unlikely that this cache gets a hit within a single invocation of structurally_same_type... Yeah, I'll get rid of it.

File: src/librustc_lint/builtin.rs (hunk 4 above)
Comment (jumbatm) [reply src/librustc_lint/builtin.rs:2274]: I see. My reasoning for having them not equal is because I want this case to clash:

```rust
mod a {
    extern "C" {
        fn take(_: *const S);
    }
}
mod b {
    extern "C" {
        fn take(_: *mut S);
    }
}
```
Specifically, I want to guard against the case where `take` actually mutates the data underneath, but  `a::take` is called with data that was supposed to be immutable -- a conflicting declaration of the mutability of some data should ring some alarm bells.

File: src/librustc_lint/builtin.rs [hunk 7]
```diff
@@ -2153,35 +2153,47 @@ impl ClashingExternDeclarations {
...
-            };
+        fn structurally_same_type_impl<'tcx>(
+            seen_types: &mut FxHashSet<(Ty<'tcx>, Ty<'tcx>)>,
+            cx: &LateContext<'tcx>,
+            a: Ty<'tcx>,
+            b: Ty<'tcx>,
+            ckind: CItemKind,
+        ) -> bool {
+            debug!("structurally_same_type_impl(cx, a = {:?}, b = {:?})", a, b);
+            if seen_types.contains(&(a, b)) {
```
Comment (lcnr) [inline src/librustc_lint/builtin.rs:2164]:
```suggestion
            if !seen_types.insert((a, b)) {
```
nit: we currently do 2 hashmap lookups here but 1 should be enough

File: src/librustc_lint/builtin.rs [hunk 8]
```diff
@@ -2153,35 +2153,47 @@ impl ClashingExternDeclarations {
...
+                    debug!("{:?} == {:?} = {}", a_layout, b_layout, a_layout == b_layout);
+                    a_layout == b_layout
+                };
 
-            #[allow(rustc::usage_of_ty_tykind)]
-            let is_primitive_or_pointer =
-                |kind: &ty::TyKind<'_>| kind.is_primitive() || matches!(kind, RawPtr(..));
+                #[allow(rustc::usage_of_ty_tykind)]
+                let is_primitive_or_pointer =
+                    |kind: &ty::TyKind<'_>| kind.is_primitive() || matches!(kind, RawPtr(..));
```
Comment (lcnr) [inline src/librustc_lint/builtin.rs:2189]: Why does this only allow `RawPtr` and no ordinary references?

**Review by lcnr — APPROVED** [review]
small nits, otherwise this is looking good :+1:

**Comment by jumbatm** [comment]
Cool, this is good to go.

@rustbot modify labels to -S-waiting-on-author, +S-waiting-on-review

File: src/librustc_lint/builtin.rs [hunk 9]
```diff
@@ -2190,86 +2202,101 @@ impl ClashingExternDeclarations {
...
+                                seen_types,
+                                cx,
+                                a_sig.output(),
+                                b_sig.output(),
+                                ckind,
+                            )
+                    }
+                    (Tuple(a_substs), Tuple(b_substs)) => {
+                        a_substs.types().eq_by(b_substs.types(), |a_ty, b_ty| {
+                            structurally_same_type_impl(seen_types, cx, a_ty, b_ty, ckind)
```
Comment (nagisa) [inline src/librustc_lint/builtin.rs:2261]: you may still want to use `ensure_sufficient_stack` when recursing.

**Review by lcnr — APPROVED** [review]
Looks good to me, r=me after the comment by @nagisa is resolved

**Comment by lcnr** [comment]
perf looks neutral to me

@bors r+ rollup=always
