### PR TITLE
align_offset, align_to: no longer allow implementations to spuriously fail to align

### LINKED ISSUE #62420: align_offset guarantees
The [documentation for `align_offset`](https://doc.rust-lang.org/nightly/std/primitive.pointer.html#method.align_offset) says

> If it is not possible to align the pointer, the implementation returns usize::max_value().

It does not give any details of when it might not be possible to perform the alignment. My reading of that is that the user must always be prepared for failure to happen. In accordance with that, a while ago I adjusted the [docs for `align_to`](https://doc.rust-lang.org/nightly/std/primitive.slice.html#method.align_to) (the preferred way to use `align_offset`) to say

> This method splits the slice into three distinct slices: prefix, correctly aligned middle slice of a new type, and the suffix slice. The method does a best effort to make the middle slice the greatest length possible for a given type and input slice, but only your algorithm's performance should depend on that, not its correctness.

In practice, returning `max_value` happens when `p as usize & (gcd - 1) != 0` (whatever exactly this means, this is taken from the implementation) -- and when running in Miri, which will always return `max_value`.

Historically, Miri did this because it had no notion of the "integer address" of an allocation, so there literally was no way to offset a pointer to get a particular alignment. This is changing now, Miri is getting the support for this. So maybe we should note some conditions under which `align_offset` will definitely succeed. A motivation for this is https://github.com/rust-lang/rust/pull/61339, which implicitly made the assumption that aligning with `size_of::<T>() == 1` will always succeed.

On the other hand, the current contract for `align_offset` lets Miri do more reliable alignment checking. This is off-by-default but can be enabled with `-Zmiri-symbolic-alignment-check`: when checking whether some pointer `p` that points to offset `o` inside an allocation with alignment `a`, we have the option to consider only `a` and `o` and *not* the integer value of `p`. This allows us to reliably detect alignment problems in code such as:
```rust
fn main() {
    let x = &mut [0u8; 3];
    let base_addr = x as *mut _ as usize;
    let u16_ref = &mut *(base_addr as *mut u16);
    *u16_ref = 2;
    println!("{:?}", x);
}
```
If we were to take the actual integer value of `p` into account, the program might get "lucky" and actually run successfully in Miri because `base_addr` happens to be even. In contrast, by *not* doing this, Miri can offer a flag where the bug in the program above is definitely caught. With this flag, the user can be *sure* that none of the accesses in the program are aligned "by chance".

However, this also means that when this flag is set, the following code will *not* pass:
```rust
fn main() {
    let x = &mut [0u8; 3];
    let base_addr = x as *mut _ as usize;
    let u16_ref = unsafe { if base_addr % 2 == 0 {
        &mut *(base_addr as *mut u16)
    } else {
        &mut *((base_addr+1) as *mut u16)
    } };
    *u16_ref = 2;
    println!("{:?}", x);
}
```
Miri cannot know that you actually did your homework and checked the integer address. This program is basically indistinguishable from the bad program above.

Currently there does not seem to be much code that operates like the last example above -- code will instead use `align_to`, which will (when run in Miri with symbolic alignment checking) make the middle part empty, and thus the "higher-aligned" accesses just don't happen. This means the vast majority of code works fine in the better-alignment-checking mode. If we force `align_offset` to not fail like https://github.com/rust-lang/rust/pull/61339 expects, then suddenly `align_to` will return non-empty middle parts in Miri as well, and `-Zmiri-symbolic-alignment-check` will basically be useless. There will be false positives when any method using `align_to` is called, which includes a few fundamental methods in libcore.

So, here's the trade-off: either Miri has a mode that can reliably detect alignment problems, or `align_offset` guarantees success under certain conditions. I don't think we can have both. Which one do we pick?

(The particular PR https://github.com/rust-lang/rust/pull/61339 that triggered this might be fixable to work with the contract Miri needs, I don't know. But this discussion will probably come up again.)

Cc @rust-lang/libs @rust-lang/wg-unsafe-code-guidelines

### PR DESCRIPTION
**Pull request by RalfJung**
For a long time, we have allowed `align_offset` to fail to compute a properly aligned offset, and `align_to` to return a smaller-than-maximal "middle slice". This was done to cover the implementation of `align_offset` in const-eval and Miri. See https://github.com/rust-lang/rust/issues/62420 for more background. For about the same amount of time, this has caused confusion and surprise, where people didn't realize they have to write their code to be defensive against `align_offset` failures.

Another way to put this is: the specification is effectively non-deterministic, and non-determinism is hard to test for -- in particular if the implementation everyone uses to test always produces the same reliable result, and nobody expects it to be non-deterministic to begin with.

With https://github.com/rust-lang/rust/pull/117840, Miri has stopped making use of this liberty in the spec; it now always behaves like rustc. That only leaves const-eval as potential motivation for this behavior. I do not think this is sufficient motivation. Currently, none of the relevant functions are stably const: `align_offset` is unstably const, `align_to` is not const at all. I propose that if we ever want to make these const-stable, we just accept the fact that they can behave differently at compile-time vs at run-time. This is not the end of the world, and it seems to be much less surprising to programmers than unexpected non-determinism. (Related: https://github.com/rust-lang/rfcs/pull/3352.)

@thomcc has repeatedly made it clear that they strongly dislike the non-determinism in align_offset, so I expect they will support this. @oli-obk, what do you think? Also, whom else should we involve? The primary team responsible is clearly libs-api, so I will nominate this for them. However, allowing const-evaluated code to behave different from run-time code is t-lang territory. The thing is, this is not stabilizing anything t-lang-worthy immediately, but it still does make a decision we will be bound to: if we accept this change, then
- either `align_offset`/`align_to` can never be called in const fn,
- or we allow compile-time behavior to differ from run-time behavior.

So I will nominate for t-lang as well, with the question being: are you okay with accepting either of these outcomes (without committing to which one, just accepting that it has to be one of them)? This closes the door to "have `align_offset` and `align_to` at compile-time and also always have compile-time behavior match run-time behavior".

Closes https://github.com/rust-lang/rust/issues/62420

### CODE REVIEW

**Comment by oli-obk** [comment]
Note that the opposite of this PR exists at https://github.com/rust-lang/rust/pull/105296

**Comment by RalfJung** [comment]
Not sure in which sense that is the "opposite". I think having these APIs you propose is a good idea no matter what we do with `align_to`. But I also think having those APIs does not stop us from removing a footgun in `align_to` if we don't have sufficient motivation to keep the footgun.

**Comment by oli-obk** [comment]
> But I also think having those APIs does not stop us from removing a footgun in `align_to` if we don't have sufficient motivation to keep the footgun.

those were only ever added to support making `str::from_utf8` const at some point. That was their original motivation. If we close the door for that, it'll just mean we have to add the same function, but fallible, again.

I guess public usage of the functions does show what people want out of these APIs, so 🤷 let's just do it and figure things out when we're ready to make more stuff const

**Comment by RalfJung** [comment]
> those were only ever added to support making str::from_utf8 const at some point. That was their original motivation. If we close the door for that, it'll just mean we have to add the same function, but fallible, again.

We're not closing the door on that though. `from_utf8` can use `align_offset` and it will be correct
- at run-time, for obvious reasons
- at compile-time, because `from_utf8` is written in a way to be robust to this difference in behavior

**Comment by m-ou-se** [comment]
We discussed this in the libs-api meeting, and those present were happy with this change.

@rfcbot merge

**Comment by joshtriplett** [comment]
With my lang hat on:

If I'm understanding correctly, these can differ at compile time precisely because the concept of *addresses* and them having *alignment* isn't the same at compile-time and runtime. That seems fine. We will still have options at compile-time; for instance, if we *want* to track the concept of "sufficiently aligned" at compile time, we could decide to do so in an abstract way.

**Comment by RalfJung** [comment]
> If I'm understanding correctly, these can differ at compile time precisely because the concept of addresses and them having alignment isn't the same at compile-time and runtime.

Yes. The only time compile-time would give a "weird" answer is when the information required to give the expected answer is inherently unavailable at compile-time.

> We will still have options at compile-time; for instance, if we want to track the concept of "sufficiently aligned" at compile time, we could decide to do so in an abstract way.

I think that might be tricky, e.g. if one crate declares a `[u8; N]` buffer stored somewhere then even tracking abstract alignment means downstream crates could be adding alignment constraints to that, e.g. deciding that it must be 4-aligned. I also don't think we actually want `align_to` to *change* the alignment of these static global objects.

**Comment by RalfJung** [comment]
@cuviper this is now waiting for your review. :)

File: library/core/src/ptr/const_ptr.rs [hunk 1]
```diff
@@ -1333,6 +1331,14 @@ impl<T: ?Sized> *const T {
     /// beyond the allocation that the pointer points into. It is up to the caller to ensure that
     /// the returned offset is correct in all terms other than alignment.
     ///
+    /// When this is called during compile-time evaluation (which is unstable), the implementation
+    /// may return `usize::MAX` in cases where that can never happen at runtime. This is because the
```
Comment (cuviper) [inline library/core/src/ptr/const_ptr.rs:1335]: I'm happy to see that there's a question about this on the tracking issue (#90962), even if that resolves as-is.

**Comment by cuviper** [comment]
Wait, hold on -- should the docs for `<*mut>::align_offset` be updated too?

@bors r-

**Comment by traviscross** [comment]
@rustbot labels -I-lang-nominated

We discussed this in the lang call on 2024-03-13 and agreed that we were OK with this having been merged and the consequences of that noted in the original nomination.

**Comment by RalfJung** [comment]
Sorry, I hadn't realized the T-lang discussion was still open when this got approved.
