### PR TITLE
Make the computation of `coroutine_captures_by_ref_ty` more sophisticated

### LINKED ISSUE #123241: Async closures are not allowed to reference all captured lifetimes if one of them is invariant
[Full example](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=6738bf50bccfd1eb8bf30107c41b1f40)

```rust
async fn go<'a>(value: &'a i32) {
    let closure = async |scope: ScopeRef<'_, 'a>| {
        let _future1 = scope.spawn(async {
            let _v = *value;
        });
    };
}
```

yields

```
error: lifetime may not live long enough
  --> examples/repro.rs:52:63
   |
52 |       let closure = async |scope: ScopeRef<'_, 'a, i32>| -> i32 {
   |  ___________________-------------------------------------------_^
   | |                   |                      |
   | |                   |                      let's call the lifetime of this reference `'2`
   | |                   lifetime `'1` represents this closure's body
53 | |         let _future1 = scope.spawn(async { value });
54 | |         22
55 | |     };
   | |_____^ closure was supposed to return data with lifetime `'2` but it is returning data with lifetime `'1`
   |
   = note: closure implements `Fn`, so references to captured variables can't escape the closure
   = note: requirement occurs because of the type `Scope<'_, '_, i32>`, which makes the generic argument `'_` invariant
   = note: the struct `Scope<'scope, 'env, R>` is invariant over the parameter `'scope`
```

> closure was supposed to return data with lifetime `'2` (`'scope`) but it is returning data with lifetime `'1` (closure body)

It's reasonable that we would create a lifetime representing the closure body, but naturally, the future should be allowed to reference it. The invariant lifetime must be mucking things up somehow.

(`spawn` has no lifetime params so I would not expect there to be a new lifetime created when it is called.)

> note: closure implements `Fn`, so references to captured variables can't escape the closure

The closure definitely shouldn't try to implement `Fn` in this case, I don't know why it does.

> note: requirement occurs because of the type `Scope<'_, '_, i32>`, which makes the generic argument `'_` invariant
> note: the struct `Scope<'scope, 'env, R>` is invariant over the parameter `'scope`

It's correct that this lifetime is invariant. We must write to a vec of futures that outlive `'scope`, so any variance would be unsound.

cc @compiler-errors

### PR DESCRIPTION
**Pull request by compiler-errors**
Currently, we treat all the by-(mut/)ref borrows of a coroutine-closure as having a "closure env" borrowed lifetime.

When we have the given code:
```rust
let x: &'a i32 = ...;
let c = async || {
    let _x = *x;
};
```

Then when we call:
```rust
c()
// which, because `AsyncFn` takes a `&self`, we insert an autoref:
(&c /* &'env {coroutine-closure} */)()
```

We will return a future whose captures contain `&'env i32` instead of `&'a i32`, which is way more restrictive than necessary. We should be able to drop `c` while the future is alive since it's not actually borrowing any data *originating from within* the closure's captures, but since the capture has that `'env` lifetime, this is not possible.

This wouldn't be true, for example, if the closure captured `i32` instead of `&'a i32`, because the `'env` lifetime is actually *necessary* since the data (`i32`) is owned by the closure.

This PR identifies two criteria where we *need* to take the borrow with the closure env lifetime:
1. If the closure borrows data from inside the closure's captures. This is not true if the parent capture is by-ref, OR if the parent capture is by-move and the child capture begins with a deref projection. This is the example described above.
2. If we're dealing with mutable references, since we cannot reborrow `&'env mut &'a mut i32` into `&'a mut i32`, *only* `&'env mut i32`.

See the documentation on `should_reborrow_from_env_of_parent_coroutine_closure` for more info.

**important:** As disclaimer states on that function, luckily, if this heuristic is not correct, then the program is not unsound, since we still borrowck and validate the choices made from this function -- the only side-effect is that the user may receive unnecessary borrowck errors.

Fixes #123241

### CODE REVIEW

File: compiler/rustc_middle/src/ty/closure.rs [hunk 1]
```diff
@@ -415,6 +416,52 @@ impl BorrowKind {
...
+                    "we captured {parent_capture:#?} but it was not used in the child coroutine?"
+                );
+                field_used_at_least_once = false;
+                // Skip this field.
+                let _ = parent_captures.next().unwrap();
+                continue;
+            }
+
+            field_used_at_least_once = true;
+            break for_each((parent_field_idx, parent_capture), (child_field_idx, child_capture));
```
Comment (compiler-errors) [inline compiler/rustc_middle/src/ty/closure.rs:460]: The only thing this fails to do is assert that the parents captures are all used at least once. I'm tempted to use a coroutine for this and just use [`iter::from_coroutine`](https://doc.rust-lang.org/std/iter/fn.from_coroutine.html)...

**Comment by compiler-errors** [comment]
r? oli-obk

**Comment by oli-obk** [comment]
Nice (and great docs, thanks!)

@bors r+ rollup
