### PR TITLE
Fix pretty-printing of lifetime bound

### LINKED ISSUE #34527: where clauses in --pretty printer mishandle >1 lifetime bound
Consider the following:

```rust
fn f1<'a, 'b, 'c>(_x: &'a u32, _y: &'b u32, _z: &'c u32) where 'c: 'a + 'b { }

fn f2<'a, 'b, 'c: 'a + 'b>(_x: &'a u32, _y: &'b u32, _z:&'c u32) { }

fn f3<'a, 'b, T: 'a + 'b>(_x: &'a u32, _y: &'b u32, _z: T) { }

fn f4<'a, 'b, T>(_x: &'a u32, _y: &'b u32, _z: T) where T: 'a + 'b { }

struct S1<'a, 'b, 'c: 'a + 'b>(&'a u32, &'b u32, &'c u32);

struct S2<'a, 'b, T: 'a + 'b>(&'a u32, &'b u32, T);

struct S3<'a, 'b, T>(&'a u32, &'b u32, T) where T: 'a + 'b;

fn main() { }

struct S4<'a, 'b, 'c>(&'a u32, &'b u32, &'c u32) where 'c: 'a + 'b;
```

If I feed the above to `rustc --pretty -Z unstable-options`, it prints out (note the first and last lines in particular):

```rust
fn f1<'a, 'b, 'c>(_x: &'a u32, _y: &'b u32, _z: &'c u32) where 'c:'a'b: { }

fn f2<'a, 'b, 'c:'a+'b>(_x: &'a u32, _y: &'b u32, _z: &'c u32) { }

fn f3<'a, 'b, T: 'a + 'b>(_x: &'a u32, _y: &'b u32, _z: T) { }

fn f4<'a, 'b, T>(_x: &'a u32, _y: &'b u32, _z: T) where T: 'a + 'b { }

struct S1<'a, 'b, 'c:'a+'b>(&'a u32, &'b u32, &'c u32);

struct S2<'a, 'b, T: 'a + 'b>(&'a u32, &'b u32, T);

struct S3<'a, 'b, T>(&'a u32, &'b u32, T) where T: 'a + 'b;

fn main() { }

struct S4<'a, 'b, 'c>(&'a u32, &'b u32, &'c u32) where 'c:'a'b:;
```

In the first and last lines, we are printing out `'c: 'a'b:`, when we should be printing `'c: 'a + 'b`.

So we are:

  1. Missing an infix `+`, and
  2. Adding an erroneous `:` to the end.

### PR DESCRIPTION
**Pull request by sanxiyn**
Fix #34527.

### CODE REVIEW

**Comment by pnkfelix** [comment]
@sanxiyn Thanks for taking this on!

I would prefer if we factored the code a bit more so that we didn't duplicate the lifetime-bound printing loop; you can see the other loop in the `fn print_lifetime_def` method; I'd just pull that out into a `fn print_lifetime_bounds` method.

Can you try doing that instead?

**Comment by sanxiyn** [comment]
Done.

File: src/test/pretty/lifetime.rs [hunk 1]
```diff
@@ -0,0 +1,15 @@
...
+//
+// Licensed under the Apache License, Version 2.0 <LICENSE-APACHE or
+// http://www.apache.org/licenses/LICENSE-2.0> or the MIT license
+// <LICENSE-MIT or http://opensource.org/licenses/MIT>, at your
+// option. This file may not be copied, modified, or distributed
+// except according to those terms.
+
+// pp-exact
+
+fn f1<'a, 'b, 'c>(_x: &'a u32, _y: &'b u32, _z: &'c u32) where 'c: 'a + 'b { }
```
Comment (pnkfelix) [inline src/test/pretty/lifetime.rs]: (now that I look at it, I wonder if the right convention would be to print `'c: 'a+'b` instead of `'c: 'a + 'b`. But I'm not going to let that question hold up this PR.)
