### PR TITLE
Suggest coercion of `Result` using `?`

### LINKED ISSUE #47560: Add suggestion when returning `Result<_, A>` when `Result<_, B>` is expected
When returning `Result<_, A>` but `Result<_, B>` is expected and `A: Into<B>`, provide a suggestion to return `Ok(x?)` instead:

```
error[E0308]: mismatched types
  --> src/bin/ruby-stacktrace.rs:86:20
   |
86 |             return version;
   |                    ^^^^^^^ expected struct `failure::Error`, found enum `ruby_stacktrace::address_finder::AddressFinderError`
   |
   = note: expected type `std::result::Result<_, failure::Error>`
              found type `std::result::Result<_, ruby_stacktrace::address_finder::AddressFinderError>`
   = help: because `ruby_stacktrace::address_finder::AddressFinderError` implements `failure::Error`, you can use `?` to coerce it:
   |
86 |             return Ok(version?);
   |                    ^^^^^^^^^^^^
```

Case taken from https://jvns.ca/blog/2018/01/13/rust-in-2018--way-easier-to-use/

### PR DESCRIPTION
**Pull request by estebank**
Fix #47560.

### CODE REVIEW

File: compiler/rustc_hir_typeck/src/coercion.rs [hunk 1]
```diff
@@ -1619,6 +1625,47 @@ impl<'tcx, 'exprs, E: AsCoercionSite> CoerceMany<'tcx, 'exprs, E> {
...
+        }
+        if Some(e.did()) != fcx.tcx.get_diagnostic_item(sym::Result) {
+            return;
+        }
+        let e = substs_e.type_at(1);
+        let f = substs_f.type_at(1);
+        if fcx
+            .tcx
+            .infer_ctxt()
+            .build()
```
Comment (compiler-errors) [inline compiler/rustc_hir_typeck/src/coercion.rs:1650]: Why aren't you using the inference context in `fcx`?

File: compiler/rustc_hir_typeck/src/coercion.rs [hunk 2]
```diff
@@ -1565,6 +1565,9 @@ impl<'tcx, 'exprs, E: AsCoercionSite> CoerceMany<'tcx, 'exprs, E> {
                             && let hir::ExprKind::Loop(loop_blk, ..) = expression.kind {
                               intravisit::walk_block(& mut visitor, loop_blk);
                         }
+                        if let Some(expr) = expression {
+                            self.note_result_coercion(fcx, &mut err, expr, expected, found);
```
Comment (compiler-errors) [inline compiler/rustc_hir_typeck/src/coercion.rs:1569]: Ideally we'd put this on `FnCtxt` and add it to `emit_type_mismatch_suggestions` too, for non-`CoerceMany` type mismatches.

Comment (estebank) [reply compiler/rustc_hir_typeck/src/coercion.rs]: Done. I do have some concerns about this triggering when it shouldn't, like in `let _: Result<(), A> = Err(B);` telling you to write `Ok(Err(B)?)`, which wouldn't work. (It doesn't, but I don't know if it is only because of a lower priority.)

File: compiler/rustc_hir_typeck/src/demand.rs [hunk 3]
```diff
@@ -693,6 +694,45 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
...
+        if Some(e.did()) != self.tcx.get_diagnostic_item(sym::Result) {
+            return false;
+        }
+        let e = substs_e.type_at(1);
+        let f = substs_f.type_at(1);
+        if self
+            .infcx
+            .type_implements_trait(
+                self.tcx.get_diagnostic_item(sym::Into).unwrap(),
+                [self.tcx.erase_regions(f), self.tcx.erase_regions(e)],
```
Comment (compiler-errors) [inline compiler/rustc_hir_typeck/src/demand.rs:718]: you should no longer need to erase regions here.

File: compiler/rustc_hir_typeck/src/demand.rs [hunk 4]
```diff
@@ -693,6 +694,45 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
...
+                self.param_env,
+            )
+            .must_apply_modulo_regions()
+        {
+            err.multipart_suggestion(
+                "you can rely on the implicit conversion that `?` does to transform the error type",
```
Comment (compiler-errors) [inline compiler/rustc_hir_typeck/src/demand.rs:724]: This phrasing feels a bit roundabout... Also, it should really mention that it's doing control flow, since it's not equivalent to `.map_err(Into::into)`, which is what this currently reads like.

Comment (compiler-errors) [reply compiler/rustc_hir_typeck/src/demand.rs:724]: In return position, it's fine to ignore the fact that this is doing control flow, but even if you hadn't applied my suggestion to extend this, it's still happening on any block-tail usage of `CoerceMany`, which is not always in the return of an fn.

Comment (estebank) [reply compiler/rustc_hir_typeck/src/demand.rs:724]: Before the requested change, this *was* checking the obligation cause code explicitly for the cases where this was happening in `return` statements and function tails exclusively :-/

Comment (compiler-errors) [reply compiler/rustc_hir_typeck/src/demand.rs:724]: > where this was happening in return statements and function tails exclusively :-/

Wait, like I said in:

> but even if you hadn't applied my suggestion to extend this to all type mismatch suggestions, it's still happening on any block-tail usage of CoerceMany, which is not always in the return of an fn.

This concern still applies to the old code too. 

The original commit bb0f8c1098d7191f1c27ce7ee3ee2bafcf99c6ca used the `BlockTailExpression` obligation to gate this suggestion, which isn't equivalent to checking if something is in the function tail exclusively. For example:

```
struct A;
struct B;

impl From<A> for B {
    fn from(_: A) -> Self { B }
}

fn foo() -> Result<(), B> {
    let y = Err(A);
    let z: Result<(), B> = { y };
}
```

Gives:

```
help: you can rely on the implicit conversion that `?` does to transform the error type
   |
10 |     let z: Result<(), B> = { Ok(y?) };
   |                              +++ ++
```

On that earlier commit, which still really deserves either fixing (making the suggestion *only* apply in tail position), or mentioning control flow.

Comment (estebank) [reply compiler/rustc_hir_typeck/src/demand.rs:724]: Fixed

Comment (estebank) [reply compiler/rustc_hir_typeck/src/demand.rs:734]: Regarding the wording, do you have one in mind? I'm somewhat relying on prior understanding of what `?` does, but because the suggestion is always for returned values, it should never affect behavior, regardless of understanding.

File: compiler/rustc_hir_typeck/src/demand.rs [hunk 5]
```diff
@@ -693,6 +694,55 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
...
+            .infcx
+            .type_implements_trait(
+                self.tcx.get_diagnostic_item(sym::Into).unwrap(),
+                [f, e],
+                self.param_env,
+            )
+            .must_apply_modulo_regions()
+        {
+            err.multipart_suggestion(
+                "you can rely on the implicit conversion that `?` does to transform the error type",
```
Comment (compiler-errors) [inline compiler/rustc_hir_typeck/src/demand.rs:734]: Maybe something like

```suggestion
                "use `?` then wrap the value in `Ok` to return an `Err` result and coerce the `Ok` variant into the right `Result` type",
```

?? no idea if that's clearer 😅

Comment (estebank) [reply compiler/rustc_hir_typeck/src/demand.rs:734]: I'm not too happy with that explanation because I feel it is too much. I want us to take into consideration the context we are in: we have some `Result<_, A>` and we expected `Result<_, B>` where `B: Into<A>`. Because of that I want to focus on "writing the following you can turn the value you have into the expected type". Maybe "you can use `?` to coerce return an appropriate `Err`, and wrap the resulting value in `Ok` so it remains a `Result`"?

Comment (compiler-errors) [reply compiler/rustc_hir_typeck/src/demand.rs:734]: I'm fine with that wording minus the "you can". I personally prefer suggestions worded in the imperative mood, but r=me either way.

**Review by compiler-errors — APPROVED** [review]

File: tests/ui/type/type-check/coerce-result-return-value-2.stderr [hunk 6]
```diff
@@ -0,0 +1,47 @@
...
+   |
+LL |         true => return Ok(x?),
+   |                        +++ ++
+
+error[E0308]: mismatched types
+  --> $DIR/coerce-result-return-value-2.rs:21:28
+   |
+LL |       let _: Result<(), B> = {
+   |  ____________________________^
+LL | |         Err(A);
```
Comment (riking) [inline tests/ui/type/type-check/coerce-result-return-value-2.stderr:38]: This test case has a mistake - you meant to test `Err(A)` not `Err(A);`.

Comment (estebank) [reply tests/ui/type/type-check/coerce-result-return-value-2.stderr:38]: It works as a negative test :)

I don't recall now if I *intended* for that to be the case, which is likely not.
