### PR TITLE
Do not assert that a change in global cache only happens when concurrent

### LINKED ISSUE #234: `search_graph` incorrectly overwrites existing cache entry
```rust
#![feature(fn_delegation)]
#![allow(incomplete_features)]

mod opaque {
    trait Trait {}
    impl Trait for () {}

    mod to_reuse {
        use super::Trait;
        pub fn opaque_ret() -> impl Trait { () }
    }

    trait ToReuse {
        fn opaque_ret() -> impl Trait { () }
    }

    // FIXME: Inherited `impl Trait`s create query cycles when used inside trait impls.
    impl ToReuse for u8 {
        reuse to_reuse::opaque_ret; //~ ERROR cycle detected when computing type
    }
}
```
```rust
error[E0391]: cycle detected when computing type of `opaque::<impl at src/main.rs:18:5: 18:24>::opaque_ret::{anon_assoc#0}`
  --> src/main.rs:19:25
   |
19 |         reuse to_reuse::opaque_ret; //~ ERROR cycle detected when computing type
   |                         ^^^^^^^^^^
   |
note: ...which requires comparing an impl and trait method signature, inferring any hidden `impl Trait` types in the process...
  --> src/main.rs:19:25
   |
19 |         reuse to_reuse::opaque_ret; //~ ERROR cycle detected when computing type
   |                         ^^^^^^^^^^
   = note: ...which again requires computing type of `opaque::<impl at src/main.rs:18:5: 18:24>::opaque_ret::{anon_assoc#0}`, completing the cycle
   = note: cycle used when computing implied outlives bounds for `<u8 as opaque::ToReuse>::opaque_ret::{anon_assoc#0}` (hack disabled = false)
   = note: see https://rustc-dev-guide.rust-lang.org/overview.html#queries and https://rustc-dev-guide.rust-lang.org/query.html for more information


thread 'rustc' panicked at /home/lcnr/rust/compiler/rustc_type_ir/src/search_graph/global_cache.rs:65:17:
assertion failed: cx.evaluation_is_concurrent()
```

### PR DESCRIPTION
**Pull request by jackh726**
Fixes rust-lang/trait-system-refactor-initiative#234

I think it should just be safe to remove this assert (rather than delaying a bug). If the previous and current result are the same, I wouldn't expect issues.

r? lcnr

### CODE REVIEW

**Comment by lcnr** [comment]
it's really useful when fuzzing as it's a case where the detection mechanism for "should I use the global cache" is broken.

you could make it a method on the search graph delegate trait and make it a noop in rustc? I do want to keep something here for fuzzing

**Comment by jackh726** [comment]
I changed `evaluation_is_concurrent` to `assert_evaluation_is_concurrent` and just made it a no-op.

File: compiler/rustc_type_ir/src/interner.rs [hunk 1]
```diff
@@ -183,7 +185,9 @@ pub trait Interner:
         from_entry: impl FnOnce(&CanonicalParamEnvCacheEntry<Self>) -> R,
     ) -> R;
 
-    fn evaluation_is_concurrent(&self) -> bool;
+    // Useful for testing. If a cache entry is replaced, this should
+    // (in theory) only happen when concurrent.
```
Comment (lcnr) [inline compiler/rustc_type_ir/src/interner.rs]:
```suggestion
    /// Useful for testing. If a cache entry is replaced, this should
    /// (in theory) only happen when concurrent.
```

**Review by lcnr — COMMENTED** [review]
r=me after nit

*[View changes since this review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/rust/147251/5c7ae0c7ed184c603e5224604a9f33ca0e8e0b36..39b36ead8313509b039a32b149e011246837f5bf)*

File: tests/ui/traits/next-solver/fn-delegation-opaque-cycle.rs [hunk 2]
```diff
@@ -0,0 +1,30 @@
+//@ revisions: current next
+//@ ignore-compare-mode-next-solver (explicit revisions)
+//@[next] compile-flags: -Znext-solver
+//@ check-fail
+
+// Regression test for trait-system-refactor-initiative#234. If we end up in a
+// query cycle, it should be okay as long as results are the same.
```
Comment (lcnr) [inline tests/ui/traits/next-solver/fn-delegation-opaque-cycle.rs]: woops, this is an existing ui test. Please add a revision to the existing test instead
