### PR TITLE
resolve: mark binding is determined after all macros had been expanded

### LINKED ISSUE #113834: Incorrect reference to the glob binding caused by the macro expansion
I tried this code:

```rust
pub mod a {
    pub use crate::b::*;
}

mod b {
    pub mod http {
        pub struct HeaderMap;
    }

    pub use self::http::*;
    #[derive(Debug)]
    pub struct HeaderMap;
}

use crate::a::HeaderMap;

fn main() {
    let h: crate::b::http::HeaderMap = HeaderMap;
}
```

I expected to see this happen: `h` should refer to `crate::b::HeaderMap`.

Instead, this happened: `h` refers to `crate::b::http::HeaderMap`.

If you remove the `#[derive(Debug)]` attribute, then `h` will refer to `crate::b::HeaderMap`.

And there is also another example(https://github.com/rust-lang/rust/issues/56593#issuecomment-1133174514):

```rs
use thing::*;

#[derive(Debug)]
pub enum Thing {
    Foo
}

mod tests {
    use super::*;

    fn test_thing() {
        let thing: crate::thing::Thing = Thing::Bar; // should refer to `crate::Thing`
    }
}

mod thing {
    pub enum Thing {
        Bar
    }
}
```

### Meta

`rustc --version --verbose`:

```
rustc 1.73.0-nightly (0e8e857b1 2023-07-16)
binary: rustc
commit-hash: 0e8e857b11f60a785aea24a84f280f6dad7a4d42
commit-date: 2023-07-16
host: aarch64-apple-darwin
release: 1.73.0-nightly
LLVM version: 16.0.5
```

### LINKED ISSUE #115377: Adding `#[derive()]` changes blob import semantics
image

I tried this code:

```rust
use module::*;
mod module {
    pub enum B {}
    impl B { pub const ASSOC: bool = true; } // used to distinguish the `B`s
}

#[derive()]
pub enum B {}
impl B { pub const ASSOC: bool = false; }

fn main() {
    let it = {
        use self::*;
        B::ASSOC
    };
    assert_eq!(
        it,
        {
            use self::*;
            B::ASSOC
        },
    );
}
```

I expected to see this happen: the assertion passing, since `{ use self::*; B::ASSOC }` should have a consistent value/meaning within `main`'s `fn body` where no other items are defined.

Instead, this happened: **the assertion fails!**

### Meta

[This regressed in `1.52.0`](https://rust.godbolt.org/z/6q9v7b87s)

### Extra comments

  - The key element playing a role here, beyond the blob imports, is the **`#[derive()]` slapped onto `B`**. This seems to allow for the blob-imported `module::B` to somehow gain priority over the clearly-defined `crate::B` type within `fn main`'s blob import.

  - I did not expect the "moving of `{ use self::*; B::ASSOC }` block" to alter this quirk (I was initially writing the MRE as `assert_eq!(B::ASSSOC, { use … })` when I ran into this extra bug).

  - ~~Could https://github.com/rust-lang/rust/pull/112086/ be relevant? cc @petrochenkov~~

  - Initially discovered [on Discord by user `@kyuuhachi`](https://discord.com/channels/442252698964721669/443150878111694848/1146395878391816202)

@rustbot modify labels: +regression-from-stable-to-stable

### PR DESCRIPTION
**Pull request by bvanjoi**
Fixes #113834
Fixes #115377

r? @petrochenkov

### CODE REVIEW

**Comment by bvanjoi** [comment]
ci is failed, thus mark it as draft

**Comment by bvanjoi** [comment]
reduced for https://github.com/rust-lang/rust/pull/115269#issuecomment-1694652695: 

```rs
macro_rules! types {
    () => {};
}

mod x {
    types!();

    mod a {
        macro_rules! m {
            () => {
                "nop"
            };
        }
        pub(crate) use m;
    }

    mod b {
        use crate::x::*;
        use std::arch::asm;

        pub unsafe fn bbbb() {
            asm!(m!());
        }
    }

    pub use self::a::*;
    pub use self::b::*;
}

fn main() {}
```

File: compiler/rustc_resolve/src/lib.rs [hunk 1]
```diff
@@ -542,7 +542,7 @@ impl<'a> ModuleData<'a> {
             populate_on_access: Cell::new(is_foreign),
             unexpanded_invocations: Default::default(),
             no_implicit_prelude,
-            glob_importers: RefCell::new(Vec::new()),
+            glob_importers: RefCell::new(Default::default()),
```
Comment (petrochenkov) [inline compiler/rustc_resolve/src/lib.rs:545]:
```suggestion
            glob_importers: Default::default(),
```

File: compiler/rustc_resolve/src/imports.rs [hunk 2]
```diff
@@ -1367,27 +1346,31 @@ impl<'a, 'tcx> Resolver<'a, 'tcx> {
...
+            return 0;
+        } else if module.unexpanded_invocations.borrow().len() > 0 {
+            return 3;
         }
 
         // Add to module's glob_importers
-        module.glob_importers.borrow_mut().push(import);
+        let prev = module.glob_importers.borrow_mut().insert(import);
+        // Ensure that it's inserted only once.
+        assert!(prev);
```
Comment (petrochenkov) [inline compiler/rustc_resolve/src/imports.rs:1373]: I don't understand why this assert isn't hit, perhaps we are missing a test?

`resolve_import` can now return a non-zero for a glob import, so it can return into the `indeterminate_imports` queue and be resolved again later.

The logic behind the existing code is that `resolve_glob_import` is called only once for a glob import (when its module is initially resolved) and performs initial setup - does initial update and fills `glob_importers` for further updates.
All further updates then go through `update_resolution` when something in other modules changes.
It think this is the right setup, and don't think it needs to be changed.

Comment (bvanjoi) [reply compiler/rustc_resolve/src/imports.rs:1373]: > It think this is the right setup, and don't think it needs to be changed.

Yes, I will revert it

**Comment by petrochenkov** [comment]
I still think it would be nice to make some refactorings mentioned in https://rust-lang.zulipchat.com/#narrow/stream/182449-t-compiler.2Fhelp/topic/Is.20this.20an.20appropriate.20solution.20for.20issue.20.23113834.3F/near/386775859 before proceeding to further fixes.
(Changing `glob_importers` to a  set can also be included into refactorings.)

**Comment by bvanjoi** [comment]
I have updated the algorithm as follows: the glob binding is marked as 'undetermined' if there are unexpended macros in its parent module. Then, it is marked as 'determined' once all macros have been expanded. This flag can be used to update the resolution for it.

> I think a good refactoring would be factor out this logic and just call something like `update_resolution` from `resolve_glob_import`.

I'm not entirely sure if this is what you're seeking, but I think it comes close.

@rustbot ready

File: tests/ui/imports/import-after-macro-expand-13.rs [hunk 3]
```diff
@@ -0,0 +1,22 @@
...
+    #[derive(Debug)]
+    pub struct HeaderMap;
+}
+
+mod a {
+    pub use crate::b::*;
+}
+
+fn main() {
+    let h: crate::b::HeaderMap = HeaderMap;
```
Comment (bvanjoi) [inline tests/ui/imports/import-after-macro-expand-13.rs:21]: This is a breaking change for `actix-http`, should we add a lint for the back compat?

File: compiler/rustc_resolve/src/lib.rs [hunk 4]
```diff
@@ -685,7 +685,16 @@ impl<'a> ToNameBinding<'a> for NameBinding<'a> {
...
-    Import { binding: NameBinding<'a>, import: Import<'a>, used: Cell<bool> },
+    Import {
+        binding: NameBinding<'a>,
+        import: Import<'a>,
+        used: Cell<bool>,
+        /// A binding is determined:
+        /// - when there are no unexpanded macros within
+        /// the `import.parent_scope.module`.
+        /// - or it's defined during build graph.
+        determined: Cell<bool>,
```
[the remark this answers is not in the document]
Comment (petrochenkov) [reply compiler/rustc_resolve/src/lib.rs:696]: Also for glob imports the value is always equal to `import.module.unexpanded_invocations.borrow().is_empty()`, right?
In that case it doesn't need to be kept separately and can always be evaluated on demand?

[the remark this answers is not in the document]
Comment (bvanjoi) [reply compiler/rustc_resolve/src/lib.rs:696]: > In that case it doesn't need to be kept separately and can always be evaluated on demand?

I think it can be accomplished, but I'm not certain if it's appropriate because a determined binding also requires the chain to be determined. see https://github.com/rust-lang/rust/pull/115269/files#diff-54ebaa0715c94a2acf974077e838aa584186e187f3d01edb1791fd71c78408caR1430

> If this flag is only relevant to glob imports, then maybe it's better to move the cell to `ImportKind::Glob`

That's a good point, I will give it a try.

[the remark this answers is not in the document]
Comment (petrochenkov) [reply compiler/rustc_resolve/src/lib.rs:696]: Is the `NameBindingKind::Import::determined` flag "local" or it accumulates information from the whole chain somehow?

The logic in `fn resolve_imports` tells that it's local (one module is enough to make the flag determined).
If it's local the I don't see problems from using the `import.import.module.unexpanded_invocations.borrow().is_empty()` chain instead of `import.determined`.

[the remark this answers is not in the document]
Comment (bvanjoi) [reply compiler/rustc_resolve/src/lib.rs]: Thanks for your tips, things are now more succinct.

File: compiler/rustc_resolve/src/ident.rs [hunk 5]
```diff
@@ -974,7 +974,8 @@ impl<'a, 'tcx> Resolver<'a, 'tcx> {
         // shadowing is enabled, see `macro_expanded_macro_export_errors`).
         let unexpanded_macros = !module.unexpanded_invocations.borrow().is_empty();
         if let Some(binding) = binding {
-            if !unexpanded_macros || ns == MacroNS || restricted_shadowing {
+            let determined = !unexpanded_macros && binding.determined();
+            if determined || ns == MacroNS || restricted_shadowing {
```
Comment (petrochenkov) [inline compiler/rustc_resolve/src/ident.rs:978]:
```suggestion
            if binding.determined() || ns == MacroNS || restricted_shadowing {
```
`module` above is the `binding`'s module, so the `!unexpanded_macros` should be already included and this should be equivalent.

File: compiler/rustc_resolve/src/imports.rs [hunk 6]
```diff
@@ -313,16 +313,14 @@ impl<'a, 'tcx> Resolver<'a, 'tcx> {
                     (true, true) => {
                         // FIXME: remove `!binding.is_ambiguity()` after delete the warning ambiguity.
                         if !binding.is_ambiguity()
+                            && !old_binding.determined()
```
Comment (petrochenkov) [inline compiler/rustc_resolve/src/imports.rs:316]: Is this change orthogonal to the change in `ident.rs`?
What does it mean?
The condition on this branch feels increasingly more random.

Comment (petrochenkov) [reply compiler/rustc_resolve/src/imports.rs:316]: How would this code look like if we didn't care about backward compatibility?

Comment (bvanjoi) [reply compiler/rustc_resolve/src/imports.rs:316]: > Is this change orthogonal to the change in ident.rs?

I don't think it's orthogonal, and removing `!old_binding.determined()` all the tests run through it as well. It's only written this way to be a bit stricter, as I'm not sure if there are any boundary cases.

> The condition on this branch feels increasingly more random.

I also want to remove this branch, but I haven't found a better way than overwriting the binding...

> How would this code look like if we didn't care about backward compatibility?

I think can only remove `binding.is_ambiguity()`.

**Comment by petrochenkov** [comment]
@craterbot check

**Comment by bvanjoi** [comment]
It appears that there have been regressions only in ﻿`egglog` and `﻿nmap-analyze`. Is this acceptable?

File: compiler/rustc_resolve/src/lib.rs [hunk 7]
```diff
@@ -881,6 +881,16 @@ impl<'a> NameBindingData<'a> {
             invoc_parent_expansion.is_descendant_of(self_parent_expansion);
         !(certainly_before_other_or_simultaneously || certainly_before_invoc_or_simultaneously)
     }
+
+    fn determined(&self) -> bool {
```
Comment (petrochenkov) [inline compiler/rustc_resolve/src/lib.rs:885]: This function needs a comment describing its purpose and its relations with `NameResolution::binding`.

Maybe also a FIXME saying that the logic in `NameResolution::binding` and here should be merged/unified.

File: compiler/rustc_resolve/src/lib.rs [hunk 8]
```diff
@@ -881,6 +881,16 @@ impl<'a> NameBindingData<'a> {
...
+        match &self.kind {
+            NameBindingKind::Import { binding, import, .. } => {
+                import.parent_scope.module.unexpanded_invocations.borrow().is_empty()
```
Comment (petrochenkov) [inline compiler/rustc_resolve/src/lib.rs:888]: Could you add an assert ensuring that this import is a glob import?

**Comment by petrochenkov** [comment]
> It appears that there have been regressions only in ﻿`egglog` and `﻿nmap-analyze`. Is this acceptable?

I think it's acceptable, we can merge this PR if you send PRs with fixes to the affected crates.

File: compiler/rustc_resolve/src/lib.rs (hunk 8 above)
Comment (petrochenkov) [reply compiler/rustc_resolve/src/lib.rs:891]: The only non-recursive use of this function is in `fn resolve_ident_in_module_unadjusted_ext` where it's a glob import.

Comment (petrochenkov) [reply compiler/rustc_resolve/src/lib.rs:891]: The second use is in `fn determined` itself, and it that case it doesn't seem to work correctly.

For single imports it doesn't matter whether `unexpanded_invocations` is empty or not, for them if the binding is set once it cannot be overridden later by an expanded macro.
If the function is called for non-glob imports, then it should return `true` for them without checking `unexpanded_invocations`.

**Comment by bvanjoi** [comment]
I removed this test in https://github.com/rust-lang/rust/pull/115269#issuecomment-1717063890 as there has a similar struct on ﻿﻿`stdarch`

@rustbot ready
