### PR TITLE
Mention functions pointers in the documentation

### LINKED ISSUE #51615: Unexpected undefined behavior when assigning a function pointer to std::mem::zeroed()
Note: the following behavior only exists when compiling ***with optimizations*** (a.k.a. release mode).

### Example 1:
```rust
pub fn bar() -> usize {
    let foo: fn() = unsafe { ::std::mem::zeroed() };
    foo as usize
}
```

This emits (as of 1.26.0):
```asm
  push rbp
  mov rbp, rsp
  ud2
```

Whereas it used to have expected behavior up until 1.19.0:
```asm
  push rbp
  mov rbp, rsp
  xor eax, eax
  pop rbp
  ret
```

### Example 2:

A bit of an odd case I discovered, which results in what seems to be some stack corruption:
```rust
pub struct Foo<T: Copy> {
    map_keys: [u64; 64],
    map_vals: T,
}

impl<T: Copy> Foo<T> {
    pub fn new() -> Self {
        Foo {
            map_keys: [!0; 64],
            map_vals: unsafe { ::std::mem::zeroed() }
        }
    }
}

fn main() {
    Foo::<fn()>::new();
}
```
[Playground link](https://play.rust-lang.org/?gist=16467ab7ba367b172472f6270d4efb9f&version=stable&mode=release)

---

What I think is striking here is that this behavior occurs while *never even dereferencing the pointer!*. This allows one to shoot oneself in the foot when trying to, for example, set a default value for a function pointer member.

### PR DESCRIPTION
**Pull request by poliorcetics**
Fixes #51615.

This mentions function pointers in the documentation for `core::mem::zeroed`, adding them to the list of types that are **always** wrong when zeroed, with `&T` and `&mut T`.

@rustbot modify labels: T-doc, C-enhancement, T-libs

### CODE REVIEW

File: src/libcore/mem/mod.rs [hunk 1]
```diff
@@ -581,11 +581,12 @@ pub const fn needs_drop<T>() -> bool {
...
 /// necessarily zeroed.
 ///
-/// There is no guarantee that an all-zero byte-pattern represents a valid value of
-/// some type `T`. For example, the all-zero byte-pattern is not a valid value
-/// for reference types (`&T` and `&mut T`). Using `zeroed` on such types
-/// causes immediate [undefined behavior][ub] because [the Rust compiler assumes][inv]
-/// that there always is a valid value in a variable it considers initialized.
+/// There is no guarantee that an all-zero byte-pattern represents a valid value
+/// of some type `T`. For example, the all-zero byte-pattern is not a valid value
+/// for reference types (`&T`, `&mut T` and functions pointers). Using `zeroed` on
```
Comment (dtolnay) [inline src/libcore/mem/mod.rs:586]: Function pointers are not typically presented in terms of references because you can't "dereference" them. Any resemblance to references is restricted to the compiler.

```suggestion
/// for reference types (`&T`, `&mut T`) and functions pointers. Using `zeroed` on
```

**Review by dtolnay — CHANGES_REQUESTED** [review]

**Review by dtolnay — APPROVED** [review]
Thanks!
