### PR TITLE
Account for bad placeholder types in where clauses

### LINKED ISSUE #70291: "bad placeholder type" ICE regression
[Playground link](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=a847e6a14f3f751d2897d674434f4a9d)
```rust
fn foo<F>(_: F) where F: FnOnce() -> _ {}
```
On stable this produces an error that "the type placeholder `_` is not allowed within types on item signatures".

On nightly (current version on play.rust-lang.org), however, it produces an ICE:
```
error: internal compiler error: bad placeholder type
 --> src/main.rs:3:38
  |
3 | fn foo<F>(_: F) where F: FnOnce() -> _ {}
  |                                      ^

thread 'rustc' panicked at 'no errors encountered even though `delay_span_bug` issued', src/librustc_errors/lib.rs:360:17
```
Attempting to call the function results in a different ICE:
```
error: internal compiler error: src/librustc_codegen_llvm/context.rs:854: failed to get layout for `[type error]`: the type `[type error]` has an unknown layout

thread 'rustc' panicked at 'Box<Any>', src/librustc_errors/lib.rs:880:9
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.45/src/backtrace/libunwind.rs:86
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.45/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:78
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1069
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1427
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:198
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:218
  10: rustc_driver::report_ice
  11: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:515
  12: std::panicking::begin_panic
  13: rustc_errors::HandlerInner::bug
  14: rustc_errors::Handler::bug
  15: rustc::util::bug::opt_span_bug_fmt::{{closure}}
  16: rustc::ty::context::tls::with_opt::{{closure}}
  17: rustc::ty::context::tls::with_opt
  18: rustc::util::bug::opt_span_bug_fmt
  19: rustc::util::bug::bug_fmt
  20: <rustc_codegen_llvm::context::CodegenCx as rustc_target::abi::LayoutOf>::spanned_layout_of::{{closure}}
  21: <rustc_codegen_llvm::context::CodegenCx as rustc_target::abi::LayoutOf>::spanned_layout_of
  22: rustc_codegen_ssa::mir::analyze::non_ssa_locals
  23: rustc_codegen_ssa::mir::codegen_mir
  24: <rustc::mir::mono::MonoItem as rustc_codegen_ssa::mono_item::MonoItemExt>::define
  25: rustc_codegen_llvm::base::compile_codegen_unit::module_codegen
  26: rustc::dep_graph::graph::DepGraph::with_task
  27: rustc_codegen_llvm::base::compile_codegen_unit
  28: rustc_codegen_ssa::base::codegen_crate
  29: <rustc_codegen_llvm::LlvmCodegenBackend as rustc_codegen_ssa::traits::backend::CodegenBackend>::codegen_crate
  30: rustc_interface::passes::start_codegen
  31: rustc::ty::context::tls::enter_global
  32: rustc_interface::queries::Queries::ongoing_codegen
  33: rustc_interface::interface::run_compiler_in_existing_thread_pool
```

### PR DESCRIPTION
**Pull request by estebank**
Fix #70291. Follow up to #69148.

### CODE REVIEW

File: src/librustc_typeck/collect.rs [hunk 1]
```diff
@@ -1519,6 +1520,7 @@ fn fn_sig(tcx: TyCtxt<'_>, def_id: DefId) -> ty::PolyFnSig<'_> {
             header.abi,
             decl,
             &generics.params[..],
+            &generics.where_clause.predicates[..],
```
Comment (Centril) [inline src/librustc_typeck/collect.rs]: Might as well pass in `&generics`?

File: src/librustc_typeck/astconv.rs [hunk 2]
```diff
@@ -2934,6 +2935,21 @@ impl<'o, 'tcx> dyn AstConv<'tcx> + 'o {
...
+            }) = predicate
+            {
+                visitor.visit_ty(bounded_ty);
+                for bound in *bounds {
+                    if let hir::GenericBound::Trait(ptr, tbm) = bound {
+                        visitor.visit_poly_trait_ref(&ptr, *tbm);
+                    }
+                }
+            }
+        }
```
Comment (Centril) [inline src/librustc_typeck/astconv.rs]: Any reason not to use `walk_list!(visitor, walk_where_predicate, predicates);` here?

Comment (estebank) [reply src/librustc_typeck/astconv.rs]: Changed it to `walk_generics(&mut visitor, generics);`

File: src/test/ui/did_you_mean/bad-assoc-ty.stderr [hunk 3]
```diff
@@ -130,7 +143,97 @@ LL | fn foo<X: K<_, _>>(x: X) {}
...
+   |
+LL | fn foo<X: K<_, _>>(x: X) {}
+   |             ^  ^ not allowed in type signatures
+   |             |
+   |             not allowed in type signatures
+   |
+help: use type parameters instead
+   |
+LL | fn foo<X, T: K<T, T>>(x: X) {}
+   |         ^^^    ^  ^
```
Comment (estebank) [inline src/test/ui/did_you_mean/bad-assoc-ty.stderr]: This is now duplicated, sadly.

Comment (Centril) [reply src/test/ui/did_you_mean/bad-assoc-ty.stderr]: As a result of addressing review comments?

File: src/librustc_typeck/astconv.rs [hunk 4]
```diff
@@ -2739,7 +2739,7 @@ impl<'o, 'tcx> dyn AstConv<'tcx> + 'o {
             }
             hir::TyKind::BareFn(ref bf) => {
                 require_c_abi_if_c_variadic(tcx, &bf.decl, bf.abi, ast_ty.span);
-                tcx.mk_fn_ptr(self.ty_of_fn(bf.unsafety, bf.abi, &bf.decl, &[], None))
+                tcx.mk_fn_ptr(self.ty_of_fn(bf.unsafety, bf.abi, &bf.decl, None, None))
```
Comment (Centril) [inline src/librustc_typeck/astconv.rs]: You can use `Generics::empty()` instead.

**Comment by estebank** [comment]
This as it stands doesn't handle `fn foo<F: Fn() -> _>(_: F) {}`. I'll fix that.

**Comment by Centril** [comment]
@estebank does it ICE in that case? If not, then let's not fix it in this PR.

**Comment by estebank** [comment]
It does ICE.

**Comment by Centril** [comment]
@estebank Could we do the simple thing in this PR for backportability reasons and follow up with possible de-dup improvements?

**Comment by estebank** [comment]
I'm comfortable with the current state of the PR.

File: src/librustc_typeck/astconv.rs [hunk 5]
```diff
@@ -838,18 +838,6 @@ impl<'o, 'tcx> dyn AstConv<'tcx> + 'o {
...
-            // only want to emit an error complaining about them if infer types (`_`) are not
-            // allowed. `allow_ty_infer` gates this behavior.
-            crate::collect::placeholder_type_error(
-                tcx,
-                inferred_params[0],
-                &[],
-                inferred_params,
-                false,
-            );
-        }
```
Comment (estebank) [inline src/librustc_typeck/astconv.rs]: Removing this got rid of the duplicated errors.

**Comment by Centril** [comment]
I am too, let's :shipit: 

@bors r+

**Comment by estebank** [comment]
rustfmt an import 🤦‍♂️

@bors r=Centril

**Comment by pnkfelix** [comment]
Discussed in [T-compiler meeting](https://zulip-archive.rust-lang.org/131828tcompiler/40721weeklymeeting2020032654818.html#191890146). Accepted for beta-backport.
