### PR TITLE
fix built-in target detection

### LINKED ISSUE #33329: validate target triples before resolving crates
I stared at this for a while

```
$ rustc --target=x86_64_unknown-linux-musl src/main.rs
error: can't find crate for `std` [E0463]
error: aborting due to previous error
```

before realizing I had typod the target triple. If the target had been validated earlier the error would be more obvious.

### PR DESCRIPTION
**Pull request by japaric**
previously the logic was accepting wrong triples (like
`x86_64_unknown-linux-musl`) as valid ones (like `x86_64-unknown-linux-musl`) if
they contained an underscore instead of a dash.

fixes #33329

---

r? @brson 

I wanted to use a compile-fail test at first. But, you can't pass an extra `--target` flag to `rustc` for those because they already call `rustc --target $HOST` so you get a `error: Option 'target' given more than once.`. The run-make test used here works fine though.

### CODE REVIEW

File: src/librustc_back/target/mod.rs [hunk 1]
```diff
@@ -71,10 +71,9 @@ macro_rules! supported_targets {
 
         // this would use a match if stringify! were allowed in pattern position
```
Comment (durka) [inline src/librustc_back/target/mod.rs]: is this comment stale now?

Comment (durka) [inline src/librustc_back/target/mod.rs]: (it wasn't [true](http://is.gd/zaSiqX) anyway)

Comment (japaric) [inline src/librustc_back/target/mod.rs]: > (it wasn't true anyway)

Actually it would look like this: http://is.gd/ot9Ta2

Now that we are using `$triple` instead of `$module` we can change this into a match. I'll send a follow up PR because this one already got pulled into the rollup.

Comment (tamird) [inline src/librustc_back/target/mod.rs]: looks like no longer in the rollup

**Comment by japaric** [comment]
Pushed a commit with the if -> match refactor

@bors r=brson

**Comment by japaric** [comment]
I had forgotten about this PR :sweat_smile:. Hmm, I guess this failed because there is no `grep` on windows? What's a cross platform way to `grep` files? cc @alexcrichton

**Comment by alexcrichton** [comment]
Oh I think that Windows has `grep` (part of MinGW), but the grep looks like it may have just failed. Maybe an error string difference?

**Comment by japaric** [comment]
@alexcrichton Does the **msvc** bot also have grep installed? And does it run the tests under the mingw shell? AFAICT my grep string has no special characters... just alphanum chars and `':'`.

**Comment by alexcrichton** [comment]
They should yeah, currently all those bots run in a MinGW shell

**Comment by brson** [comment]
@bors retry

Just retrying to see the error again.

**Comment by brson** [comment]
Error was:

```

---- [run-make] run-make\issue-33329 stdout ----
	
error: make failed
status: exit code: 2
command: "make"
stdout:
------------------------------------------
make[1]: Entering directory '/c/bot/slave/auto-win-msvc-64-opt-rustbuild/build/src/test/run-make/issue-33329'
C:\bot\slave\auto-win-msvc-64-opt-rustbuild\build\obj\build\x86_64-pc-windows-msvc\stage2\bin\rustc.exe --target x86_64_unknown-linux-musl main.rs 2>&1 | \
	grep "error: Error loading target specification: Could not find specification for target"
Makefile:2: recipe for target 'all' failed
make[1]: Leaving directory '/c/bot/slave/auto-win-msvc-64-opt-rustbuild/build/src/test/run-make/issue-33329'

------------------------------------------
stderr:
------------------------------------------
make[1]: *** [all] Error 1

------------------------------------------

thread '[run-make] run-make\issue-33329' panicked at 'explicit panic', C:\bot\slave\auto-win-msvc-64-opt-rustbuild\build\src\tools\compiletest\src\runtest.rs:2243
note: Run with `RUST_BACKTRACE=1` for a backtrace.


failures:
    [run-make] run-make\issue-33329

test result: FAILED. 129 passed; 1 failed; 0 ignored; 0 measured



command did not execute successfully: "C:\\bot\\slave\\auto-win-msvc-64-opt-rustbuild\\build\\obj\\build\\x86_64-pc-windows-msvc\\stage2-tools\\x86_64-pc-windows-msvc\\release\\compiletest.exe" "--compile-lib-path" "C:\\bot\\slave\\auto-win-msvc-64-opt-rustbuild\\build\\obj\\build\\x86_64-pc-windows-msvc\\stage2\\bin" "--run-lib-path" "C:\\bot\\slave\\auto-win-msvc-64-opt-rustbuild\\build\\obj\\build\\x86_64-pc-windows-msvc\\stage2\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib" "--rustc-path" "C:\\bot\\slave\\auto-win-msvc-64-opt-rustbuild\\build\\obj\\build\\x86_64-pc-windows-msvc\\stage2\\bin\\rustc.exe" "--rustdoc-path" "C:\\bot\\slave\\auto-win-msvc-64-opt-rustbuild\\build\\obj\\build\\x86_64-pc-windows-msvc\\stage2\\bin\\rustdoc.exe" "--src-base" "C:\\bot\\slave\\auto-win-msvc-64-opt-rustbuild\\build\\src/test\\run-make" "--build-base" "C:\\bot\\slave\\auto-win-msvc-64-opt-rustbuild\\build\\obj\\build\\x86_64-pc-windows-msvc\\test\\run-make" "--stage-id" "stage2-x86_64-pc-windows-msvc" "--mode" "run-make" "--target" "x86_64-pc-windows-msvc" "--host" "x86_64-pc-windows-msvc" "--llvm-filecheck" "C:\\bot\\slave\\auto-win-msvc-64-opt-rustbuild\\build\\obj\\build\\x86_64-pc-windows-msvc\\llvm\\build\\Release/bin\\FileCheck.exe" "--host-rustcflags" "-Crpath -O" "--target-rustcflags" "-Crpath -O -Lnative=C:\\bot\\slave\\auto-win-msvc-64-opt-rustbuild\\build\\obj\\build\\x86_64-pc-windows-msvc\\rust-test-helpers" "--docck-python" "python" "--lldb-python" "python" "--gdb-version" "GNU gdb (GDB) 7.8" "--cc" "C:\\Program Files (x86)\\Microsoft Visual Studio 12.0\\VC/bin\\amd64\\cl.exe" "--cxx" "C:\\Program Files (x86)\\Microsoft Visual Studio 12.0\\VC/bin\\amd64\\cl.exe" "--cflags" "/nologo /MD" "--llvm-components" "aarch64 aarch64asmparser aarch64asmprinter aarch64codegen aarch64desc aarch64disassembler aarch64info aarch64utils all all-targets analysis arm armasmparser armasmprinter armcodegen armdesc armdisassembler arminfo asmparser asmprinter bitreader bitwriter codegen core debuginfocodeview debuginfodwarf debuginfopdb engine executionengine instcombine instrumentation interpreter ipo irreader libdriver lineeditor linker lto mc mcdisassembler mcjit mcparser mips mipsasmparser mipsasmprinter mipscodegen mipsdesc mipsdisassembler mipsinfo mirparser native nativecodegen objcarcopts object option orcjit passes powerpc powerpcasmparser powerpcasmprinter powerpccodegen powerpcdesc powerpcdisassembler powerpcinfo profiledata runtimedyld scalaropts selectiondag support symbolize tablegen target transformutils vectorize x86 x86asmparser x86asmprinter x86codegen x86desc x86disassembler x86info x86utils" "--llvm-cxxflags" "-IC:\\bot\\slave\\auto-win-msvc-64-opt-rustbuild\\build\\obj\\build\\x86_64-pc-windows-msvc\\llvm/include  /nologo /MD /W4 -wd4141 -wd4146 -wd4180 -wd4244 -wd4258 -wd4267 -wd4291 -wd4345 -wd4351 -wd4355 -wd4456 -wd4457 -wd4458 -wd4459 -wd4503 -wd4624 -wd4722 -wd4800 -wd4100 -wd4127 -wd4512 -wd4505 -wd4610 -wd4510 -wd4702 -wd4245 -wd4706 -wd4310 -wd4701 -wd4703 -wd4389 -wd4611 -wd4805 -wd4204 -wd4577 -wd4091 -wd4592 -wd4324 -w14062 -we4238 /Zc:inline /MD /O2 /Ob2 /D NDEBUG  /EHs-c- /GR- /MP -D_DEBUG_POINTER_IMPL= -D_CRT_SECURE_NO_DEPRECATE -D_CRT_SECURE_NO_WARNINGS -D_CRT_NONSTDC_NO_DEPRECATE -D_CRT_NONSTDC_NO_WARNINGS -D_SCL_SECURE_NO_DEPRECATE -D_SCL_SECURE_NO_WARNINGS -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS" "--adb-path" "adb" "--adb-test-dir" "/data/tmp" "--android-cross-path" ""
thread 'main' panicked at 'Some tests failed', C:\bot\slave\auto-win-msvc-64-opt-rustbuild\build\src\tools\compiletest\src\main.rs:293
expected success, got: exit code: 101
```

**Comment by brson** [comment]
@japaric Can we just xfail this on windows and push it through?

**Comment by japaric** [comment]
@brson By "xfail" do you mean ignoring this test on windows? That would be fine by me. Is [this] the standard way to do that?

[this]: https://github.com/rust-lang/rust/blob/75886537858530447051b9c1ef595c4ba59017c5/src/test/run-make/unicode-input/Makefile#L7

**Comment by brson** [comment]
@japaric Yep, and that snippet looks ok to me (but I've never ignored a run-make test before).

**Comment by japaric** [comment]
I just realized my Makefile is missing the `-include ../tools.mk` that all the other run-make Makefiles have ... so I'm going to first check if that was the problem.

@bors try

**Comment by alexcrichton** [comment]
Ah unfortunately `@bors: try` doesn't actually work, but let's see if 94ae8bb3d99a5162f6ac159c29caa9006e560169 works on bors

@bors: r+ 94ae8bb3d99a5162f6ac159c29caa9006e560169

**Comment by japaric** [comment]
This was stuck in the queue as failed (because of the previous try). Rebased so I can r+ it again.

@bors: r+

**Comment by alexcrichton** [comment]
@bors: retry force clean

* restarted buildbot
