### PR TITLE
Fix compile_fail tag

### LINKED ISSUE #33780: compile_fail tags seems broken
For example, the following tests shouldn't pass since they compile:

* [E0074](https://github.com/rust-lang/rust/blob/da41920919ef4164c91541b8da501e36e9544c0f/src/librustc_typeck/diagnostics.rs#L980)
* [E0082-1](https://github.com/rust-lang/rust/blob/da41920919ef4164c91541b8da501e36e9544c0f/src/librustc_typeck/diagnostics.rs#L1171)
* [E0082-2](https://github.com/rust-lang/rust/blob/da41920919ef4164c91541b8da501e36e9544c0f/src/librustc_typeck/diagnostics.rs#L1182)

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Fixes #33780

r? @steveklabnik

### CODE REVIEW

File: src/librustc/diagnostics.rs [hunk 1]
```diff
@@ -66,7 +68,7 @@ this restriction.
 
 This happens when a trait has a method like the following:
 
-```compile_fail
+```ignore
```
Comment (jonathandturner) [inline src/librustc/diagnostics.rs]: I'm not clear on why we're ignoring these

**Comment by steveklabnik** [comment]
So, this patch seems sensible, but because of the lack of description, it took me a while to figure out exactly what it was doing, and what the problem is. Could you maybe amend the commit message to describe exactly what's going on here, and squash? Thanks

File: src/librustdoc/test.rs [hunk 2]
```diff
@@ -262,17 +262,19 @@ fn runtest(test: &str, cratename: &str, cfgs: Vec<String>, libs: SearchPaths,
         control.after_analysis.stop = Compilation::Stop;
     }
 
-    let res = panic::catch_unwind(AssertUnwindSafe(|| {
```
Comment (jonathandturner) [inline src/librustdoc/test.rs]: I think this reads better having the panic + closure in a variable and then later matching the variable rather than doing both at once.

Comment (GuillaumeGomez) [inline src/librustdoc/test.rs]: I guess it's a question of point of view? For me it's better this way but if someone else agrees with you, then I'll do it again in two steps.

File: src/librustc/diagnostics.rs (hunk 1 above)
Comment (GuillaumeGomez) [inline src/librustc/diagnostics.rs]: It shouldn't. Thanks for noticing!

**Comment by GuillaumeGomez** [comment]
@steveklabnik: I splitted the two commits to make the review easier. I guess it wasn't a good idea. So just in case, the first commit was to fix cases where the compilation went fine when it was expecting that it'd fail. Second case just update the cases where it now fails because of this change.

File: src/librustdoc/test.rs (hunk 2 above)
Comment (GuillaumeGomez) [inline src/librustdoc/test.rs]: cc @steveklabnik

**Comment by GuillaumeGomez** [comment]
Ok, so now commits have been squashed and commit message has been rewritten. It just remains the little syntax issue @jonathandturner reported (but I need another confirmation before removing it).

File: src/librustdoc/test.rs (hunk 2 above)
Comment (steveklabnik) [inline src/librustdoc/test.rs]: I am not sure, personally. I can see it both ways.

Comment (GuillaumeGomez) [inline src/librustdoc/test.rs]: Well... Thanks? :laughing:

**Comment by GuillaumeGomez** [comment]
Updated.

**Comment by GuillaumeGomez** [comment]
@ bors: r+ rollup
