### PR TITLE
Bring back suggestion for splitting `<-` into `< -`

### LINKED ISSUE #62632: Bring back suggestion for splitting `<-` in a comparison
```rust
fn main() {
    if x<-1 {
    }
}
```
produces:
```
error: expected `{`, found `<-`
```
It would be nice if it produced a suggestion to split it up:
```rust
if x < -1 {
```
(This [used to happen](https://github.com/rust-lang/rust/pull/60803#discussion_r303081575), but was broken in a previous change.)

### PR DESCRIPTION
**Pull request by iluuu1994**
Closes #62632

### CODE REVIEW

File: src/libsyntax/parse/parser.rs [hunk 1]
```diff
@@ -2936,6 +2936,18 @@ impl<'a> Parser<'a> {
                 self.err_dotdotdot_syntax(self.token.span);
             }
 
+            if self.token == token::LArrow {
+                self.diagnostic().struct_span_err(self.token.span, {
```
Comment (Centril) [inline src/libsyntax/parse/parser.rs]:
```suggestion
                self.struct_span_err(self.token.span,
```

File: src/libsyntax/parse/parser.rs [hunk 2]
```diff
@@ -2936,6 +2936,18 @@ impl<'a> Parser<'a> {
                 self.err_dotdotdot_syntax(self.token.span);
             }
 
+            if self.token == token::LArrow {
```
Comment (Centril) [inline src/libsyntax/parse/parser.rs]: To avoid cluttering this method, I would prefer to put this in its own method:
```rust
self.maybe_ban_placement_suggest_comparison();
```

File: src/libsyntax/parse/parser.rs (hunk 1 above)
Comment (iluuu1994) [reply src/libsyntax/parse/parser.rs]: I moved the error portion to a function called `err_larrow_operator` analogous to `err_dotdotdot_syntax`. I hope that's ok.

File: src/libsyntax/parse/parser.rs (hunk 2 above)
Comment (iluuu1994) [reply src/libsyntax/parse/parser.rs]: I moved the error portion to a function called `err_larrow_operator` analogous to `err_dotdotdot_syntax`. I hope that's ok.

Comment (Centril) [reply src/libsyntax/parse/parser.rs]: Sure :)

**Comment by iluuu1994** [comment]
r? @Centril 

@eddyb Since he already did the reviewing 🙂

**Comment by iluuu1994** [comment]
Thanks @Centril!
