### PR TITLE
Emit error instead of delayed bug when meeting mismatch type for const tuple

### LINKED ISSUE #150841: ICE `const tuple must have a tuple type`
### Code

```Rust
#![feature(min_generic_const_args)]
fn takes_nested_tuple<const N: u32>() {
    takes_nested_tuple::<{ () }>
}
fn main() {}

```

### Meta

`rustc --version --verbose`:
```
rustc 1.94.0-nightly (4586feb99 2026-01-08)
binary: rustc
commit-hash: 4586feb998521343b91c554adbb11ba30547d67a
commit-date: 2026-01-08
host: x86_64-unknown-linux-gnu
release: 1.94.0-nightly
LLVM version: 21.1.8
```

### Error output

```
warning: the feature `min_generic_const_args` is incomplete and may not be safe to use and/or cause compiler crashes
 --> code.rs:1:12
  |
1 | #![feature(min_generic_const_args)]
  |            ^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: see issue #132980 <https://github.com/rust-lang/rust/issues/132980> for more information
  = note: `#[warn(incomplete_features)]` on by default

warning: function `takes_nested_tuple` is never used
 --> code.rs:2:4
  |
2 | fn takes_nested_tuple<const N: u32>() {
  |    ^^^^^^^^^^^^^^^^^^
  |
  = note: `#[warn(dead_code)]` (part of `#[warn(unused)]`) on by default

warning: 2 warnings emitted

note: no errors encountered even though delayed bugs were created

note: those delayed bugs will now be shown as internal compiler errors
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
error: internal compiler error: const tuple must have a tuple type
 --> code.rs:3:28
  |
3 |     takes_nested_tuple::<{ () }>
  |                            ^^
  |
note: delayed at /rustc-dev/4586feb998521343b91c554adbb11ba30547d67a/compiler/rustc_hir_analysis/src/hir_ty_lowering/mod.rs:2501:20
         0: <rustc_errors::DiagCtxtInner>::emit_diagnostic
         1: <rustc_errors::DiagCtxtHandle>::emit_diagnostic
         2: <rustc_span::ErrorGuaranteed as rustc_errors::diagnostic::EmissionGuarantee>::emit_producing_guarantee
         3: <rustc_errors::DiagCtxtHandle>::span_delayed_bug::<rustc_span::span_encoding::Span, &str>
         4: <dyn rustc_hir_analysis::hir_ty_lowering::HirTyLowerer>::lower_const_arg
         5: <<rustc_hir_typeck::fn_ctxt::FnCtxt>::instantiate_value_path::CtorGenericArgsCtxt as rustc_hir_analysis::hir_ty_lowering::GenericArgsLowerer>::provided_kind
         6: <rustc_hir_typeck::fn_ctxt::FnCtxt>::instantiate_value_path
         7: <rustc_hir_typeck::fn_ctxt::FnCtxt>::check_expr_path
         8: <rustc_hir_typeck::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
         9: <rustc_hir_typeck::fn_ctxt::FnCtxt>::check_expr_block
        10: <rustc_hir_typeck::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
        11: rustc_hir_typeck::check::check_fn
        12: rustc_hir_typeck::typeck_with_inspect::{closure#0}
        13: rustc_query_impl::plumbing::__rust_begin_short_backtrace::<rustc_query_impl::query_impl::typeck::dynamic_query::{closure#2}::{closure#0}, rustc_middle::query::erase::Erased<[u8; 8]>>
        14: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::DynamicConfig<rustc_data_structures::vec_cache::VecCache<rustc_span::def_id::LocalDefId, rustc_middle::query::erase::Erased<[u8; 8]>, rustc_query_system::dep_graph::graph::DepNodeIndex>, false, false, false>, rustc_query_impl::plumbing::QueryCtxt, false>
        15: rustc_query_impl::query_impl::typeck::get_query_non_incr::__rust_end_short_backtrace
        16: <rustc_middle::ty::context::TyCtxt>::par_hir_body_owners::<rustc_hir_analysis::check_crate::{closure#2}>::{closure#0}
        17: rustc_hir_analysis::check_crate
        18: rustc_interface::passes::analysis
        19: rustc_query_impl::plumbing::__rust_begin_short_backtrace::<rustc_query_impl::query_impl::analysis::dynamic_query::{closure#2}::{closure#0}, rustc_middle::query::erase::Erased<[u8; 0]>>
        20: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::DynamicConfig<rustc_query_system::query::caches::SingleCache<rustc_middle::query::erase::Erased<[u8; 0]>>, false, false, false>, rustc_query_impl::plumbing::QueryCtxt, false>
        21: rustc_query_impl::query_impl::analysis::get_query_non_incr::__rust_end_short_backtrace
        22: <rustc_interface::passes::create_and_enter_global_ctxt<core::option::Option<rustc_interface::queries::Linker>, rustc_driver_impl::run_compiler::{closure#0}::{closure#2}>::{closure#2} as core::ops::function::FnOnce<(&rustc_session::session::Session, rustc_middle::ty::context::CurrentGcx, alloc::sync::Arc<rustc_data_structures::jobserver::Proxy>, &std::sync::once_lock::OnceLock<rustc_middle::ty::context::GlobalCtxt>, &rustc_data_structures::sync::worker_local::WorkerLocal<rustc_middle::arena::Arena>, &rustc_data_structures::sync::worker_local::WorkerLocal<rustc_hir::Arena>, rustc_driver_impl::run_compiler::{closure#0}::{closure#2})>>::call_once::{shim:vtable#0}
        23: rustc_interface::interface::run_compiler::<(), rustc_driver_impl::run_compiler::{closure#0}>::{closure#1}
        24: std::sys::backtrace::__rust_begin_short_backtrace::<rustc_interface::util::run_in_thread_with_globals<rustc_interface::util::run_in_thread_pool_with_globals<rustc_interface::interface::run_compiler<(), rustc_driver_impl::run_compiler::{closure#0}>::{closure#1}, ()>::{closure#0}, ()>::{closure#0}::{closure#0}, ()>
        25: <std::thread::lifecycle::spawn_unchecked<rustc_interface::util::run_in_thread_with_globals<rustc_interface::util::run_in_thread_pool_with_globals<rustc_interface::interface::run_compiler<(), rustc_driver_impl::run_compiler::{closure#0}>::{closure#1}, ()>::{closure#0}, ()>::{closure#0}::{closure#0}, ()>::{closure#1} as core::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
        26: <std::sys::thread::unix::Thread>::new::thread_start
        27: <unknown>
        28: <unknown>

 --> code.rs:3:28
  |
3 |     takes_nested_tuple::<{ () }>
  |                            ^^

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: please make sure that you have updated to the latest nightly

note: please attach the file at `/home/matthias/vcs/github/CRED/rustc-ice-2026-01-08T21_45_17-975808.txt` to your bug report

note: rustc 1.94.0-nightly (4586feb99 2026-01-08) running on x86_64-unknown-linux-gnu

query stack during panic:
end of query stack
```

</p>
</details>

### PR DESCRIPTION
**Pull request by mu001999**
And rename some tests

Fixes rust-lang/rust#150841

r? @BoxyUwU

### CODE REVIEW

File: compiler/rustc_hir_analysis/src/hir_ty_lowering/mod.rs [hunk 1]
```diff
@@ -2502,11 +2502,12 @@ impl<'tcx> dyn HirTyLowerer<'tcx> + '_ {
         let tcx = self.tcx();
 
         let FeedConstTy::WithTy(ty) = feed else {
-            return Const::new_error_with_message(tcx, span, "unsupported const tuple");
+            return Const::new_error_with_message(tcx, span, "const tuple lack type information");
         };
 
         let ty::Tuple(tys) = ty.kind() else {
-            return Const::new_error_with_message(tcx, span, "const tuple must have a tuple type");
+            let e = tcx.dcx().span_err(span, format!("expected {}, found const tuple", ty));
```
Comment (fmease) [inline compiler/rustc_hir_analysis/src/hir_ty_lowering/mod.rs]:
```suggestion
            let e = tcx.dcx().span_err(span, format!("expected `{}`, found const tuple", ty));
```
