### PR TITLE
Fix suggestion when there were a colon already in generics

### LINKED ISSUE #144215: invalid suggestion `<T: 'static:>`
### Code

```Rust
struct S<T: >(&'static T);
```

### Current output

```Shell
error[E0310]: the parameter type `T` may not live long enough
 --> src/lib.rs:1:15
  |
1 | struct S<T: >(&'static T);
  |               ^^^^^^^^^^
  |               |
  |               the parameter type `T` must be valid for the static lifetime...
  |               ...so that the reference type `&'static T` does not outlive the data it points at
  |
help: consider adding an explicit lifetime bound
  |
1 | struct S<T: 'static: >(&'static T);
  |           +++++++++
```

### Desired output

```Shell
error[E0310]: the parameter type `T` may not live long enough
 --> src/lib.rs:1:15
  |
1 | struct S<T: >(&'static T);
  |               ^^^^^^^^^^
  |               |
  |               the parameter type `T` must be valid for the static lifetime...
  |               ...so that the reference type `&'static T` does not outlive the data it points at
  |
help: consider adding an explicit lifetime bound
  |
1 | struct S<T: 'static>(&'static T);
  |             +++++++
```

### Rationale and extra context

_No response_

### Other cases

unfulfilled trait bounds are less problematic:

```rust
struct S<T: >(C<T>);
struct C<T: Copy>(T);
```

gives

```
error[E0277]: the trait bound `T: Copy` is not satisfied
 --> src/lib.rs:1:15
  |
1 | struct S<T: >(C<T>);
  |               ^^^^ the trait `Copy` is not implemented for `T`
  |
note: required by a bound in `C`
 --> src/lib.rs:2:13
  |
2 | struct C<T: Copy>(T);
  |             ^^^^ required by this bound in `C`
help: consider restricting type parameter `T` with trait `Copy`
  |
1 | struct S<T: std::marker::Copy >(C<T>);
  |             +++++++++++++++++
```

which has an extra space but is correct syntax.

### Rust Version

```Shell
1.90.0-nightly

(2025-07-19 0d9592026226f5a667a0)
```

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by Kivooeo**
Finally found time to fix https://github.com/rust-lang/rust/issues/144215

I don't feel like this `colon_flag` is perfect solution and that it can be refactored, but I'd say that this is pretty good as it, I was tried to refactor this a little, but the thing is the scope where `param.colon_span` lives is very limited, so there is not much time to check was there colon or not, I tried to rewrite this into more functional style to address this, but it becomes way more unreadable than this one or even less performant, maybe some comments could push readability of this fix further, maybe a comment for enum or `colon_flag`?

### CODE REVIEW

File: compiler/rustc_trait_selection/src/error_reporting/infer/region.rs [hunk 1]
```diff
@@ -774,20 +774,31 @@ impl<'a, 'tcx> TypeErrCtxt<'a, 'tcx> {
                     // instead we suggest `T: 'a + 'b` in that case.
                     let hir_generics = self.tcx.hir_get_generics(scope).unwrap();
                     let sugg_span = match hir_generics.bounds_span_for_suggestions(def_id) {
-                        Some((span, open_paren_sp)) => Some((span, true, open_paren_sp)),
+                        Some((span, open_paren_sp)) => {
+                            Some((span, LifetimeSuggestion::NeedsPlus, open_paren_sp))
```
Comment (JonathanBrouwer) [inline compiler/rustc_trait_selection/src/error_reporting/infer/region.rs]: I think the `open_paren_sp` can only be `Some` in the `NeedsPlus` case, so it is nice to add that as a field to the variant

**Review by JonathanBrouwer — CHANGES_REQUESTED** [review]

File: compiler/rustc_trait_selection/src/error_reporting/infer/region.rs (hunk 1 above)
Comment (Kivooeo) [reply compiler/rustc_trait_selection/src/error_reporting/infer/region.rs]: Nice catch, but btw, I cant use bors yet, so you'd need to r+ it yourself later on
