### PR TITLE
mir_build: consider privacy when checking for irrefutable patterns

### LINKED ISSUE #137999: Privately uninhabited types can affect how pattern matches are borrow-checked
The following code compiles:

```rust
mod m {
    enum Void {}
    
    pub struct Internal {
        _v: Void,
    }

    pub enum Test {
        A(u32, u32),
        B(Internal),
    }
}

use m::Test;

pub fn meow(x: &mut Test) {
    let r1: &mut u32 = match x {
        Test::A(a, _) => a,
        _ => todo!(),
    };

    let r2: &mut u32 = match x {
        Test::A(_, b) => b,
        _ => todo!(),
    };

    let _ = *r1;
    let _ = *r2;
}
```

However, it only compiles because the `_v` private field is uninhabited – changing its type to `()` makes it fail compilation with the following error:

```
error[E0503]: cannot use `*x` because it was mutably borrowed
  --> src/lib.rs:22:30
   |
18 |         Test::A(a, _) => a,
   |                 - `x.0` is borrowed here
...
22 |     let r2: &mut u32 = match x {
   |                              ^ use of borrowed `x.0`
...
27 |     let _ = *r1;
   |             --- borrow later used here
```

As discussed [on Zulip](https://rust-lang.zulipchat.com/#narrow/channel/131828-t-compiler/topic/Is.20this.20a.20bug.3F.20Code.20can.20depend.20on.20private.20field.20of.20struct), the compiler makes efforts to not make it possible to observe a type being privately uninhabited, and so this is a bug.

### Meta

`rustc --version --verbose`:
```
rustc 1.87.0-nightly (f4a216d28 2025-03-02)
binary: rustc
commit-hash: f4a216d28ee635afce685b4206e713579f66e130
commit-date: 2025-03-02
host: x86_64-unknown-linux-gnu
release: 1.87.0-nightly
LLVM version: 20.1.0
```

As I discovered this bug while reading rustc sources, I am working on a PR to fix this.

@rustbot claim

### PR DESCRIPTION
**Pull request by meithecatte**
This PR fixes #137999.

Note that, since this makes the compiler reject code that was previously accepted, it will probably need a crater run.

I include a commit that factors out a common code pattern into a helper function, purely because the fact that this was repeated all over the place was bothering me. Let me know if I should split that into a separate PR instead.

### CODE REVIEW

File: compiler/rustc_mir_build/src/builder/matches/match_pair.rs [hunk 1]
```diff
@@ -219,10 +219,11 @@ impl<'tcx> MatchPairTree<'tcx> {
 
                 let irrefutable = adt_def.variants().iter_enumerated().all(|(i, v)| {
                     i == variant_index
-                        || !v
-                            .inhabited_predicate(cx.tcx, adt_def)
-                            .instantiate(cx.tcx, args)
-                            .apply_ignore_module(cx.tcx, cx.infcx.typing_env(cx.param_env))
+                        || !v.inhabited_predicate(cx.tcx, adt_def).instantiate(cx.tcx, args).apply(
```
Comment (compiler-errors) [inline compiler/rustc_mir_build/src/builder/matches/match_pair.rs:222]: 👍

**Comment by compiler-errors** [comment]
@craterbot check

**Comment by Skgland** [comment]
The crater run appears to be running extremely slow. The estimated end is up to 534 hours (22 days) and still increasing. Recent runs took 1-2 days.

**Comment by lqd** [comment]
@rust-timer build 5785402183672f7786e9dc343d7b435bdaf4a4bc

(perf.rlo handles timeouts on benchmarks, it should be thus fine to check if this PR causes slowdowns)

**Comment by Skgland** [comment]
As it doesn't appear to be a perf problem of the PR maybe its related to rust-lang/rustwide#94 and rustup 1.28 breaking rustwide also affects crater. Tough I would have expected a speedup in the crater run, as I would expect everything to fail immediately, rather than a slow down.

**Comment by Skgland** [comment]
The Crater Agent has apparently lost contact since ~2 hours ago
image

**Comment by compiler-errors** [comment]
@craterbot cancel

**Comment by compiler-errors** [comment]
Let's try again 🙏 otherwise I'll open a T-infra thread to investigate.

@craterbot check

**Comment by meithecatte** [comment]
The crater run is not starting. The agent is still unreachable.

**Comment by compiler-errors** [comment]
https://rust-lang.zulipchat.com/#narrow/channel/242791-t-infra/topic/crater.20dead

**Comment by meithecatte** [comment]
I might be misreading this, but it seems like there's a bunch of spurious errors, and no legitimate failures.

**Comment by compiler-errors** [comment]
No regressions, yup

**Comment by compiler-errors** [comment]
I'm inclined to treat this as a bugfix. This probably wouldn't have been committed if we knew the consequence.

**Comment by meithecatte** [comment]
I rebased the PR onto latest master and resolved the merge conflicts.

**Comment by compiler-errors** [comment]
r? nadrieril for a final review, though looks fine to me

**Comment by Nadrieril** [comment]
Looks good, agreed that it qualifies as bugfix.

@bors r+

**Comment by Nadrieril** [comment]
Disabling rollup to make it easier to find by bisection, just in case.

@bors rollup=never

**Comment by compiler-errors** [comment]
cargo bisect-rustc handles rollups totally fine, and i don't expect this to have any fallout, so let's compromise and mark it as rollup=maybe :)

@bors rollup=maybe
