### PR TITLE
Test slice patterns more

### LINKED ISSUE #66934: ICE when using slice patterns in const fn.
The following code ICEs

```rust
#![feature(slice_patterns)]

const fn f() {
    let x = [()];
    let [y @ ..] = x;
}
```

[Playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=3b54cb9afc7b610788162cfa034c3d1a)

<details>

<summary>Backtrace</summary>

```text
   Compiling playground v0.0.1 (/playground)
warning: unused variable: `y`
 --> src/lib.rs:5:10
  |
5 |     let [y @ ..] = x;
  |          ^ help: consider prefixing with an underscore: `_y`
  |
  = note: `#[warn(unused_variables)]` on by default

warning: function is never used: `f`
 --> src/lib.rs:3:10
  |
3 | const fn f() {
  |          ^
  |
  = note: `#[warn(dead_code)]` on by default

thread 'rustc' panicked at 'Layout mismatch when copying!
src: OpTy {
    op: Immediate(
        Scalar(
            <ZST>,
        ),
    ),
    layout: TyLayout {
        ty: (),
        details: LayoutDetails {
            variants: Single {
                index: 0,
            },
            fields: Arbitrary {
                offsets: [],
                memory_index: [],
            },
            abi: Aggregate {
                sized: true,
            },
            largest_niche: None,
            align: AbiAndPrefAlign {
                abi: Align {
                    pow2: 0,
                },
                pref: Align {
                    pow2: 3,
                },
            },
            size: Size {
                raw: 0,
            },
        },
    },
}
dest: PlaceTy {
    place: Local {
        frame: 0,
        local: _3,
    },
    layout: TyLayout {
        ty: [(); 1],
        details: LayoutDetails {
            variants: Single {
                index: 0,
            },
            fields: Array {
                stride: Size {
                    raw: 0,
                },
                count: 1,
            },
            abi: Aggregate {
                sized: true,
            },
            largest_niche: None,
            align: AbiAndPrefAlign {
                abi: Align {
                    pow2: 0,
                },
                pref: Align {
                    pow2: 3,
                },
            },
            size: Size {
                raw: 0,
            },
        },
    },
}', src/librustc_mir/interpret/place.rs:872:9
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:84
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:61
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1024
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1428
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:65
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:50
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:193
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:210
  10: rustc_driver::report_ice
  11: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:475
  12: rust_begin_unwind
             at src/libstd/panicking.rs:375
  13: std::panicking::begin_panic_fmt
             at src/libstd/panicking.rs:326
  14: rustc_mir::interpret::step::<impl rustc_mir::interpret::eval_context::InterpCx<M>>::eval_rvalue_into_place
  15: <rustc_mir::transform::const_prop::ConstPropagator as rustc::mir::visit::MutVisitor>::visit_statement
  16: <rustc_mir::transform::const_prop::ConstProp as rustc_mir::transform::MirPass>::run_pass
  17: rustc_mir::transform::run_passes
  18: rustc_mir::transform::run_optimization_passes
  19: rustc_mir::transform::optimized_mir
  20: rustc::ty::query::__query_compute::optimized_mir
  21: rustc::ty::query::<impl rustc::ty::query::config::QueryAccessors for rustc::ty::query::queries::optimized_mir>::compute
  22: rustc::dep_graph::graph::DepGraph::with_task_impl
  23: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt>::get_query
  24: rustc_metadata::rmeta::encoder::EncodeContext::encode_optimized_mir
  25: <rustc_metadata::rmeta::encoder::EncodeContext as rustc::hir::intravisit::Visitor>::visit_item
  26: rustc::hir::Crate::visit_all_item_likes
  27: rustc_metadata::rmeta::encoder::EncodeContext::encode_crate_root
  28: rustc::ty::context::tls::with_context::{{closure}}
  29: rustc_metadata::rmeta::encoder::encode_metadata
  30: rustc_metadata::rmeta::decoder::cstore_impl::<impl rustc::middle::cstore::CrateStore for rustc_metadata::creader::CStore>::encode_metadata
  31: rustc::ty::context::TyCtxt::encode_metadata
  32: rustc_interface::passes::start_codegen::{{closure}}
  33: rustc_interface::passes::start_codegen
  34: rustc::ty::context::tls::enter_global
  35: rustc_interface::queries::Queries::ongoing_codegen
  36: rustc_interface::interface::run_compiler_in_existing_thread_pool
  37: std::thread::local::LocalKey<T>::with
  38: scoped_tls::ScopedKey<T>::set
  39: syntax::with_globals
```

</details>

### PR DESCRIPTION
**Pull request by matthewjasper**
Adds tests for const evaluation and some more borrow checking tests.

Fixes some bugs in const eval for subslice patterns.
closes #66934

r? @oli-obk 
cc @Centril

### CODE REVIEW

**Comment by matthewjasper** [comment]
Test list for stabilization report (without links, sorry)

### Parsing

* `@ ..` isn't allowed outside of slice patterns and is only allowed once in each slice pattern
    * rest-pat-semantic-disallowed.rs
* Mulitple `..` patterns are not allowed
    * match-vec-invalid.rs

### Type checking

* Default binding modes apply to slice patterns
    * rfc-2005-default-binding-mode/slice.rs
* Array patterns cannot have more elements in the pattern than in the array
    * match-vec-mismatch.rs
    * E0528.rs
* Array subslice patterns have array types:
    * subslice-patterns-pass.rs

### Exhaustiveness and usefulness checking

* Array patterns with subslices are irrefutable:
    * issue-7784.rs
* `[xs @ ..]` slice patterns are irrefutable:
    * irrefutable-slice-patterns.rs
* Subslice patterns can match zero-length slices:
    * issue-15080.rs
    * issue-15104.rs
* General tests:
    * issue-12369.rs
    * issue-37598.rs
    * match-vec-unreachable.rs
    * non-exhaustive-match.rs
    * non-exhaustive-pattern-witness.rs

### Borrow checking

* Slice patterns can only move from owned, fixed-length arrays
    * borrowck-move-out-of-vec-tail.rs
    * move-out-of-slice-2.rs
    * move-out-of-array-ref.rs
* Moves from arrays are tracked by element:
    * borrowck-move-out-from-array-no-overlap.rs
    * borrowck-move-out-from-array-use-no-overlap.rs
* Slice patterns cannot be used on moved-from slices/arrays
    * borrowck-move-out-from-array.rs
    * borrowck-move-out-from-array-use.rs
* Slice patterns cannot be used with conflicting borrows
    * borrowck-describe-lvalue.rs
    * borrowck-slice-pattern-element-loan-array.rs
    * borrowck-slice-pattern-element-loan-slice.rs
* Borrows from slice patterns are tracked and only conflict when there is possible overlap:
    * borrowck-slice-pattern-element-loan-array-no-overlap.rs
    * borrowck-slice-pattern-element-loan-slice-no-overlap.rs
    * borrowck-slice-pattern-element-loan-slice-rpass.rs
    * borrowck-vec-pattern-element-loan.rs
    * borrowck-vec-pattern-loan-from-mut.rs
    * borrowck-vec-pattern-tail-element-loan.rs
* Slice patterns correctly affect inference of closure captures
    * borrowck-closure-slice-patterns.rs
    * borrowck-closure-slice-patterns-ok.rs

### Evaluation

* Slice patterns don't cause leaks or double drops:
    * dynamic-drop.rs
    * dynamic-drop-async.rs
* General run-pass tests:
    * subslice-patterns-pass.rs
    * vec-mathing-fold.rs
    * vec-matching-legal-tail-element-borrow.rs
    * vec-matching.rs
    * vec-tail-matching.rs
* Zero-sized elements:
    * zero_size_subslice_match.rs
    * subslice-patterns-const-eval.rs
    * subslice-patterns-const-eval-match.rs
* Evaluation in const contexts:
    * subslice-patterns-const-eval.rs
    * subslice-patterns-const-eval-match.rs

**Comment by oli-obk** [comment]
cc @RalfJung

File: src/test/ui/array-slice-vec/subslice-patterns-const-eval-match.rs [hunk 1]
```diff
@@ -0,0 +1,110 @@
...
+        [$(zed!($e)),*]
+    }
+}
+
+macro_rules! compare_evaluation {
+    ($e:expr, $t:ty $(,)?) => {{
+        const CONST_EVAL: $t = $e;
+        const fn const_eval() -> $t { $e }
+        const CONST_EVAL2: $t = const_eval();
+        assert_eq!(CONST_EVAL, $e);
```
Comment (oli-obk) [inline src/test/ui/array-slice-vec/subslice-patterns-const-eval-match.rs]: You should do `let x = $e;` and then use that value in `assert_eq`, because otherwise it may get promoted and const evaluated (not happening here due to the `if let`, but still.

File: src/test/ui/array-slice-vec/subslice-patterns-const-eval-match.rs [hunk 2]
```diff
@@ -0,0 +1,110 @@
...
+    ($($e:expr),* $(,)?) => {
+        [$(N($e)),*]
+    }
+}
+
+macro_rules! zed {
+    ($e:expr) => { Z }
+}
+
+macro_rules! z {
```
Comment (Centril) [inline src/test/ui/array-slice-vec/subslice-patterns-const-eval-match.rs]: The test this is derived from is so dense and lacking of comments, but in the spirit of not repeating my mistakes.. it would be useful to have a few comments (e.g. here because `zed` doesn't use `$e`, which is interesting).

**Review by oli-obk — APPROVED** [review]
impl and tests look sound to me

File: src/test/ui/array-slice-vec/subslice-patterns-const-eval-match.rs [hunk 3]
```diff
@@ -0,0 +1,110 @@
...
+        single!(n, N);
+        single!(z, Z);
+    }
+}
+
+fn main() {
+    repeat! {
+        $ arr Ty;
+        compare_evaluation!(
+            if let [_, x @ .., _] = &$arr!(1, 2, 3, 4) as &[_] { Some(x) } else { None },
```
Comment (Centril) [inline src/test/ui/array-slice-vec/subslice-patterns-const-eval-match.rs]: `if let` might not desugar to a `match` in the future, so it would be good to use `match` explicitly in some of these cases to future-proof things. (same in next test)

File: src/test/ui/moves/move-out-of-slice-2.rs [hunk 4]
```diff
@@ -0,0 +1,18 @@
+#![feature(slice_patterns, unsized_locals)]
+
+struct A;
```
Comment (Centril) [inline src/test/ui/moves/move-out-of-slice-2.rs]: Do we have a test where `impl Copy for A {}`?

File: src/test/ui/array-slice-vec/subslice-patterns-const-eval-match.rs [hunk 5]
```diff
@@ -0,0 +1,82 @@
...
+// Compare the result of matching `$e` against `$p` using both `if let` and
+// `match`.
+macro_rules! compare_evaluation {
+    ($p:pat, $e:expr, $matches:expr, $t:ty $(,)?) => {{
+        compare_evaluation_inner!(if let $p = $e as &[_] { $matches } else { None }, $t);
+        compare_evaluation_inner!(match $e as &[_] { $p => $matches, _ => None }, $t);
+    }}
+}
+
+macro_rules! repeat {
```
Comment (Centril) [inline src/test/ui/array-slice-vec/subslice-patterns-const-eval-match.rs]: The "higher order" stuff, in particular the `$arr!(...)` stuff, probably bears a comment as well; it was the part that took most focus when reading the test as it's not something you see every day. :)

**Review by Centril — APPROVED** [review]
Tests look *great* -- thanks so much!

File: src/librustc_mir/interpret/operand.rs [hunk 6]
```diff
@@ -444,13 +444,27 @@ impl<'mir, 'tcx, M: Machine<'mir, 'tcx>> InterpCx<'mir, 'tcx, M> {
...
-            Subslice { .. } | ConstantIndex { .. } | Index(_) => if base.layout.is_zst() {
+            ConstantIndex { .. } | Index(_) if base.layout.is_zst() => {
                 OpTy {
                     op: Operand::Immediate(Scalar::zst().into()),
                     // the actual index doesn't matter, so we just pick a convenient one like 0
                     layout: base.layout.field(self, 0)?,
                 }
-            } else {
+            }
+            Subslice { from, to, from_end } if base.layout.is_zst() => {
```
Comment (RalfJung) [inline src/librustc_mir/interpret/operand.rs]: I am kind of surprised that we have a special path here for ZST anyway. I don't remember seeing that. Why would the main code path not work for that?

Comment (RalfJung) [reply src/librustc_mir/interpret/operand.rs]: Looks like we do this since https://github.com/rust-lang/rust/pull/54032... @oli-obk this looks just wrong to me. The usual place arithmetic should work for slices. Unfortunately the comments don't explain what was wrong with the old code, do you remember?

Comment (RalfJung) [reply src/librustc_mir/interpret/operand.rs]: Oh wow that PR was a subtle change of Miri engine semantics in the middle for a PR about something entirely different... in the future I think we should avoid mixing concerns like that.

File: src/librustc_mir/interpret/place.rs [hunk 7]
```diff
@@ -455,7 +455,10 @@ where
     ) -> InterpResult<'tcx, MPlaceTy<'tcx, M::PointerTag>> {
         let len = base.len(self)?; // also asserts that we have a type where this makes sense
         let actual_to = if from_end {
-            assert!(from <= len - to);
+            if from + to > len {
```
Comment (RalfJung) [inline src/librustc_mir/interpret/place.rs]: Can `from+to` overflow here?

File: src/librustc_mir/interpret/operand.rs (hunk 6 above)
Comment (oli-obk) [reply src/librustc_mir/interpret/operand.rs]: :innocent:

Comment (oli-obk) [reply src/librustc_mir/interpret/operand.rs]: I'm opening a branch right now to look at this in more detail

File: src/librustc_mir/interpret/place.rs (hunk 7 above)
Comment (oli-obk) [reply src/librustc_mir/interpret/place.rs]: Even though the function is public, it's only called for `SubSlice`, which would require the user to specify more than 2^32 sub-patterns in a slice (`[x, y, z, subslice @ .., a, b, c]`),

so...

*probably not*, but there may be creative code generators out there

File: src/librustc_mir/interpret/operand.rs (hunk 6 above)
Comment (oli-obk) [reply src/librustc_mir/interpret/operand.rs]: > Why would the main code path not work for that? ZST should only very rarely need any special-casing.

The reason we need this is this assert
https://github.com/rust-lang/rust/blob/c64eecf4d0907095928fb36fd3a1dd5fb2d9ff06/src/librustc_mir/interpret/operand.rs#L454-L456
triggering for ZSTs. The comment above the assert is wrong, we can reach this for empty arrays and arrays of ZSTs.

I can either fix this here by replacing the `assert_mem_place` with a match that produces a `MemPlace::dangling()` for ZSTs, or I can change https://github.com/rust-lang/rust/blob/de0abf7599023b71dd72b44f0165e86c040ee7ea/src/librustc_mir/interpret/place.rs#L224-L229 to do this, which seems strictly more ICE avoiding and looking at the use sites would actually help choose the better code path in a few situations.

Comment (oli-obk) [reply src/librustc_mir/interpret/operand.rs]: I opened a PR with the solution that changes `try_as_mplace` because it allows nice cleanups: https://github.com/rust-lang/rust/pull/67501

Comment (RalfJung) [reply src/librustc_mir/interpret/operand.rs]: Oh, this is `operand.rs`, not `place.rs`. Yeah that changes things.^^

Let's discuss in the new PR; thanks for opening that!
