### PR TITLE
Give name if anonymous region appears in impl signature

### LINKED ISSUE #98170: rustc panic
### Code

```Rust
pub struct MyStruct<'a> {
    field: &'a [u32],
}

impl MyStruct<'_> {
    pub fn new<'a>(field: &'a[u32]) -> MyStruct<'a> {
	Self{field}
    }
}

fn main() {
}
```

### Meta

```
rustc 1.63.0-nightly (b31f9cc22 2022-06-15)
binary: rustc
commit-hash: b31f9cc22bcd720b37ddf927afe378108a5b9a54
commit-date: 2022-06-15
host: x86_64-unknown-linux-gnu
release: 1.63.0-nightly
LLVM version: 14.0.5
```

### Error output

```
Compiling crash_repro v0.1.0 (/home/rickard/repro)
thread 'rustc' panicked at 'called `Option::unwrap()` on a `None` value', compiler/rustc_borrowck/src/diagnostics/region_errors.rs:683:52
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.63.0-nightly (b31f9cc22 2022-06-15) running on x86_64-unknown-linux-gnu

note: compiler flags: --crate-type bin -C embed-bitcode=no -C debuginfo=2 -C incremental

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [mir_borrowck] borrow-checking `<impl at src/main.rs:5:1: 9:2>::new`
#1 [analysis] running analysis passes on this crate
end of query stack
error: could not compile `crash_repro`
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
stack backtrace:
   0: rust_begin_unwind
             at /rustc/b31f9cc22bcd720b37ddf927afe378108a5b9a54/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/b31f9cc22bcd720b37ddf927afe378108a5b9a54/library/core/src/panicking.rs:142:14
   2: core::panicking::panic
             at /rustc/b31f9cc22bcd720b37ddf927afe378108a5b9a54/library/core/src/panicking.rs:48:5
   3: <rustc_borrowck::MirBorrowckCtxt>::report_general_error
   4: rustc_borrowck::do_mir_borrowck
   5: rustc_borrowck::mir_borrowck
   6: <rustc_borrowck::provide::{closure#0} as core::ops::function::FnOnce<(rustc_middle::ty::context::TyCtxt, rustc_span::def_id::LocalDefId)>>::call_once
   7: <rustc_query_system::dep_graph::graph::DepGraph<rustc_middle::dep_graph::dep_node::DepKind>>::with_task::<rustc_middle::ty::context::TyCtxt, rustc_span::def_id::LocalDefId, &rustc_middle::mir::query::BorrowCheckResult>
   8: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::plumbing::QueryCtxt, rustc_query_system::query::caches::DefaultCache<rustc_span::def_id::LocalDefId, &rustc_middle::mir::query::BorrowCheckResult>>
   9: <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::mir_borrowck
  10: <rustc_middle::hir::map::Map>::par_body_owners::<rustc_interface::passes::analysis::{closure#2}::{closure#0}>
  11: <rustc_session::session::Session>::time::<(), rustc_interface::passes::analysis::{closure#2}>
  12: rustc_interface::passes::analysis
  13: <rustc_query_system::dep_graph::graph::DepGraph<rustc_middle::dep_graph::dep_node::DepKind>>::with_task::<rustc_middle::ty::context::TyCtxt, (), core::result::Result<(), rustc_errors::ErrorGuaranteed>>
  14: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::plumbing::QueryCtxt, rustc_query_system::query::caches::DefaultCache<(), core::result::Result<(), rustc_errors::ErrorGuaranteed>>>
  15: rustc_query_system::query::plumbing::get_query::<rustc_query_impl::queries::analysis, rustc_query_impl::plumbing::QueryCtxt>
  16: <rustc_interface::passes::QueryContext>::enter::<rustc_driver::run_compiler::{closure#1}::{closure#2}::{closure#3}, core::result::Result<(), rustc_errors::ErrorGuaranteed>>
  17: <rustc_interface::interface::Compiler>::enter::<rustc_driver::run_compiler::{closure#1}::{closure#2}, core::result::Result<core::option::Option<rustc_interface::queries::Linker>, rustc_errors::ErrorGuaranteed>>
  18: rustc_span::with_source_map::<core::result::Result<(), rustc_errors::ErrorGuaranteed>, rustc_interface::interface::create_compiler_and_run<core::result::Result<(), rustc_errors::ErrorGuaranteed>, rustc_driver::run_compiler::{closure#1}>::{closure#1}>
  19: <scoped_tls::ScopedKey<rustc_span::SessionGlobals>>::set::<rustc_interface::interface::run_compiler<core::result::Result<(), rustc_errors::ErrorGuaranteed>, rustc_driver::run_compiler::{closure#1}>::{closure#0}, core::result::Result<(), rustc_errors::ErrorGuaranteed>>
```

</p>
</details>

### PR DESCRIPTION
**Pull request by compiler-errors**
Fixes #98170

We probably should remove the two unwraps in [`report_general_error`](https://doc.rust-lang.org/nightly/nightly-rustc/src/rustc_borrowck/diagnostics/region_errors.rs.html#683-685), but I have no idea what to provide if those regions are missing, so I've kept those in. Let me know if I should try harder to remove those.

### CODE REVIEW

File: compiler/rustc_middle/src/hir/mod.rs [hunk 1]
```diff
@@ -154,4 +154,6 @@ pub fn provide(providers: &mut Providers) {
     };
     providers.in_scope_traits_map =
         |tcx, id| tcx.hir_crate(()).owners[id].as_owner().map(|owner_info| &owner_info.trait_map);
+    providers.impl_parent =
+        |tcx, def_id| tcx.hir().impl_parent(def_id.expect_local()).map(|def_id| def_id.to_def_id());
```
Comment (cjgillot) [inline compiler/rustc_middle/src/hir/mod.rs:158]: IIUC, `impl_parent` is about specialization, not about finding which impl block an item corresponds to.

File: compiler/rustc_middle/src/hir/map/mod.rs [hunk 2]
```diff
@@ -1043,6 +1043,15 @@ impl<'hir> Map<'hir> {
             _ => None,
         }
     }
+
+    pub fn impl_parent(self, did: LocalDefId) -> Option<LocalDefId> {
+        let parent = self.find_parent_node(self.local_def_id_to_hir_id(did))?;
```
Comment (cjgillot) [inline compiler/rustc_middle/src/hir/map/mod.rs:1048]: This function can be implemented as
```suggestion
        let parent = self.tcx.local_parent(did);
        if let DefKind::Impl = self.tcx.def_kind(parent) {
            Some(parent)
        } else {
            None
        }
```

This implementation does not look at the HIR, so is friendlier to incremental compilation.

File: compiler/rustc_middle/src/hir/map/mod.rs [hunk 3]
```diff
@@ -1043,6 +1043,15 @@ impl<'hir> Map<'hir> {
             _ => None,
         }
     }
+
+    pub fn impl_parent(self, did: LocalDefId) -> Option<LocalDefId> {
```
Comment (cjgillot) [inline compiler/rustc_middle/src/hir/map/mod.rs:1047]: Should this get another name to avoid the confusion with the `impl_parent` query? Or better: rename the `impl_parent` query?

File: compiler/rustc_borrowck/src/diagnostics/region_name.rs [hunk 4]
```diff
@@ -840,4 +851,41 @@ impl<'tcx> MirBorrowckCtxt<'_, 'tcx> {
...
+            r
+        });
+
+        Some(RegionName {
+            name: self.synthesize_region_name(),
+            source: RegionNameSource::AnonRegionFromImplSignature(
+                tcx.def_span(region.def_id),
+                // FIXME(compiler-errors): Does this ever actually show up
+                // anywhere other than the self type? I couldn't create an
+                // example of a `'_` in the impl's trait being referenceable.
```
Comment (cjgillot) [inline compiler/rustc_borrowck/src/diagnostics/region_name.rs:886]: It can appear in the trait:
```rust
impl Foo<'_> for () {}
```

File: src/test/ui/nll/issue-98170.rs [hunk 5]
```diff
@@ -0,0 +1,13 @@
...
+    field: &'a [u32],
+}
+
+impl MyStruct<'_> {
+    pub fn new<'a>(field: &'a [u32]) -> MyStruct<'a> {
+        Self { field }
+        //~^ ERROR lifetime may not live long enough
+        //~| ERROR lifetime may not live long enough
+    }
+}
```
Comment (cjgillot) [inline src/test/ui/nll/issue-98170.rs:11]: Could you also add a test with a trait impl?

**Review by cjgillot — COMMENTED** [review]
Thanks @compiler-errors.  I have an issue with the the `impl_parent` query.  reusing the query to do something else may be confusing.

**Comment by compiler-errors** [comment]
@cjgillot oh is it? that's embarrassing, I misunderstood it's purpose. Yeah, I can do this by just looking at hir directly.

@rustbot author

File: compiler/rustc_middle/src/hir/map/mod.rs (hunk 3 above)
Comment (compiler-errors) [reply compiler/rustc_middle/src/hir/map/mod.rs:1047]: we probably don't need it, I was just misunderstanding impl_parent and was curious why there was no local provider, only a provider for external crates.

File: compiler/rustc_borrowck/src/diagnostics/region_name.rs (hunk 4 above)
Comment (compiler-errors) [reply compiler/rustc_borrowck/src/diagnostics/region_name.rs:886]: I know that elided lifetimes show up in that position, but I had trouble recreating this ICE using an elided lifetime in the trait generics. 

In order to use that lifetime to produce an error, it needs to show up somewhere as an input or output in the method signature as well, which means we are able to give the lifetime a name and never hit this function.

File: src/test/ui/nll/issue-98170.rs (hunk 5 above)
Comment (compiler-errors) [reply src/test/ui/nll/issue-98170.rs:11]: sure, but it'll be mostly similar to the existing one, see above comment about difficulty of reproducing this error with an elided lifetime in the trait generics

File: compiler/rustc_borrowck/src/diagnostics/region_name.rs (hunk 4 above)
Comment (cjgillot) [reply compiler/rustc_borrowck/src/diagnostics/region_name.rs:886]: This implementation would give a name if it's ever needed.  Let's keep it as such, and wait for somebody to ask for a better message with an example.

**Comment by lcnr** [comment]
r? @cjgillot maybe, considering that you've already reviewed this pr

skimming over this pr it looks alright :+1:
