### PR TITLE
[generator] Special cases for match guard when analyzing interior types in generators

### LINKED ISSUE #72651: ICE: Broken MIR
**EDIT: Here's MCVE: https://github.com/rust-lang/rust/issues/72651#issuecomment-636485820**

Error:
```
error: internal compiler error: src/librustc_mir/transform/generator.rs:722: Broken MIR: generator contains type &util::human_version::HumanVersionReq in MIR, but typeck only knows about for<'r, 's, 't0, 't1, 't2, 't3, 't4, 't5, 't6, 't7, 't8, 't9, 't10, 't11, 't12, 't13, 't14> {std::future::ResumeTy, &'r factorio::mods::Mods<P>, &'s mod_common::Mod, std::vec::Vec<std::string::String>, impl std::future::Future, (), std::result::Result<std::vec::Vec<mod_common::dependency::Dependency>, anyhow::Error>, std::vec::Vec<mod_common::dependency::Dependency>, std::vec::IntoIter<mod_common::dependency::Dependency>, mod_common::dependency::Dependency, &'t1 mod_common::dependency::Dependency, mod_common::dependency::Requirement, &'t2 str, std::result::Result<&'t3 mod_common::Mod, anyhow::Error>, std::option::Option<util::human_version::HumanVersionReq>, util::human_version::HumanVersionReq, impl std::future::Future, log::Level, bool, [&'t5 str; 4], &'t6 [&'t7 str], &'t8 [&'t9 str; 4], impl std::future::Future, std::string::String, &'t11 std::string::String, [&'t12 str; 3], &'t13 [&'t14 str; 3]}
   --> crates/modtorio/src/factorio/mods.rs:266:38
    |
266 |       ) -> anyhow::Result<Vec<String>> {
    |  ______________________________________^
267 | |         let mut missing = Vec::new();
268 | |
269 | |         for dep in target_mod.dependencies().await? {
...   |
317 | |         Ok(missing)
318 | |     }
    | |_____^

thread 'rustc' panicked at 'Box<Any>', /rustc/a74d1862d4d87a56244958416fd05976c58ca1a8/src/libstd/macros.rs:13:23
```

Reproduce:
```
git clone https://github.com/Spanfile/Modtorio.git
cd Modtorio
git checkout bf757a3f710dd7af60b82e322790dddd77680483
cargo clippy
```

```
$ cargo clippy -V
clippy 0.0.212 (a74d186 2020-05-14)
$ cargo -V
cargo 1.45.0-nightly (cb06cb269 2020-05-08)
$ rustc -V
rustc 1.45.0-nightly (a74d1862d 2020-05-14)
```

### PR DESCRIPTION
**Pull request by dingxiangfei2009**
Fix #72651 

This proposes one of ways to fix the mentioned issue. One cause of #72651 is that the interior type analysis misses out types of match pattern locals. Those locals are manifested as temporary borrows in the scopes of match arm guards. If uses of these locals appear after yield points, the borrows from them were not considered live across the yield points. However, this is not the case since the borrowing always happens at the very beginning of the match guard.

This calls for special treatment to analysis of types appearing in the match guard. Those borrows are recorded as the HIR tree is walked by `InteriorVisitor` and their uses are recorded whenever a yield point is crossed.

### CODE REVIEW

**Comment by dingxiangfei2009** [comment]
@eddyb I just know that reviewers are randomly assigned. Would you mind suggesting another reviewer if you find the current assignment is not suitable?

**Comment by eddyb** [comment]
Sorry! I should've asked someone to remove me from the list of reviewers, as I'm really behind.

r? @matthewjasper

File: src/test/ui/generator/yielding-in-match-guards.rs [hunk 1]
```diff
@@ -0,0 +1,29 @@
+// check-pass
```
Comment (tmandry) [inline src/test/ui/generator/yielding-in-match-guards.rs:1]: This MVCE no longer ICEs for me, whereas this one does: https://github.com/rust-lang/rust/issues/72651#issuecomment-668720468. No need to leave credit, just an issue number is enough.

(Feel free to also include this one if you can confirm it did ICE at one point, though).

Comment (dingxiangfei2009) [reply src/test/ui/generator/yielding-in-match-guards.rs:1]: The test case has been updated to refer to the said MVCE.

Comment (dingxiangfei2009) [reply src/test/ui/generator/yielding-in-match-guards.rs:1]: @tmandry Forgot to mention this. This test case compiles if the async functions are not used in `fn main`. As you can see, as soon as async function `g` is called in `main`, broken MIR ICE can be reproduced. It only found this out recently.

**Comment by dingxiangfei2009** [comment]
Hi @matthewjasper would you mind a comment or feedback on this change?

File: src/test/ui/generator/yielding-in-match-guards.rs (hunk 1 above)
Comment (tmandry) [reply src/test/ui/generator/yielding-in-match-guards.rs:1]: Ah, in that case let's put both test cases in!

**Comment by tmandry** [comment]
@rust-lang/wg-async-foundations has a meeting tomorrow focused on how this code works; after that would be a natural time for one of us to review this change.

File: compiler/rustc_typeck/src/check/generator_interior.rs [hunk 2]
```diff
@@ -210,19 +226,49 @@ impl<'a, 'tcx> Visitor<'tcx> for InteriorVisitor<'a, 'tcx> {
         NestedVisitorMap::None
     }
 
+    fn visit_arm(&mut self, arm: &'tcx Arm<'tcx>) {
+        if arm.guard.is_some() {
+            self.nested_scope_of_guards.push(<_>::default());
+            self.arm_has_guard = true;
```
Comment (tmandry) [inline compiler/rustc_typeck/src/check/generator_interior.rs:232]: It seems like we'd only want to set this while visiting the guard if expression, not the pattern.

File: compiler/rustc_typeck/src/check/generator_interior.rs [hunk 3]
```diff
@@ -210,19 +226,49 @@ impl<'a, 'tcx> Visitor<'tcx> for InteriorVisitor<'a, 'tcx> {
...
+            }
+            let mut scope_var_ids =
+                self.nested_scope_of_guards.pop().expect("should have pushed at least one earlier");
+            for var_id in scope_var_ids.drain(..) {
+                assert!(
+                    self.current_scope_of_guards.remove(&var_id),
+                    "variable should be placed in scope earlier"
+                );
+            }
+            self.arm_has_guard = false;
```
Comment (tmandry) [inline compiler/rustc_typeck/src/check/generator_interior.rs:249]: We should reset back to the original value, which won't always be false (if there were a match nested inside the guard). Here's a (very contrived) example..

```
match x {
  Some(y) if match y.len() { 0 => false, l if l % 2 == 0 => true, _ => false } => (),
  _ => (),
}
```

In fact, I'm tempted to say this flag is redundant and we should remove it. We can query `current_scope_of_guards` every time, and only find a way to optimize that if it's slow.

File: compiler/rustc_typeck/src/check/generator_interior.rs [hunk 4]
```diff
@@ -210,19 +226,49 @@ impl<'a, 'tcx> Visitor<'tcx> for InteriorVisitor<'a, 'tcx> {
...
 
         self.expr_count += 1;
 
-        if let PatKind::Binding(..) = pat.kind {
+        if let PatKind::Binding(_, id, ..) = pat.kind {
             let scope = self.region_scope_tree.var_scope(pat.hir_id.local_id);
             let ty = self.fcx.typeck_results.borrow().pat_ty(pat);
-            self.record(ty, Some(scope), None, pat.span);
+            self.record(ty, Some(scope), None, pat.span, false);
+            if self.arm_has_guard {
```
Comment (tmandry) [inline compiler/rustc_typeck/src/check/generator_interior.rs:263]: We may want to check that this binding is _actually_ introduced by the if guard, instead of by some arbitrary expression inside it.

That said, it's okay if we overapproximate the set of types inside our generator. Since it's very rare to have other bindings introduced inside a match guard, we could leave this as is. If we do that we should leave a comment explaining that this is an overapproximation.

File: compiler/rustc_typeck/src/check/generator_interior.rs [hunk 5]
```diff
@@ -134,6 +147,9 @@ pub fn resolve_interior<'a, 'tcx>(
         expr_count: 0,
         kind,
         prev_unresolved_span: None,
+        nested_scope_of_guards: <_>::default(),
+        current_scope_of_guards: <_>::default(),
```
Comment (tmandry) [inline compiler/rustc_typeck/src/check/generator_interior.rs:151]: naming suggestion: `guard_bindings_set`

File: compiler/rustc_typeck/src/check/generator_interior.rs [hunk 6]
```diff
@@ -134,6 +147,9 @@ pub fn resolve_interior<'a, 'tcx>(
         expr_count: 0,
         kind,
         prev_unresolved_span: None,
+        nested_scope_of_guards: <_>::default(),
```
Comment (tmandry) [inline compiler/rustc_typeck/src/check/generator_interior.rs:150]: naming suggestion: `guard_bindings`

File: compiler/rustc_typeck/src/check/generator_interior.rs [hunk 7]
```diff
@@ -21,6 +23,14 @@ struct InteriorVisitor<'a, 'tcx> {
     expr_count: usize,
     kind: hir::GeneratorKind,
     prev_unresolved_span: Option<Span>,
+    /// Match arm guards have temporary borrows from the pattern bindings.
+    /// In case there is a yield point in a guard with a reference to such bindings,
+    /// such borrows can span across this yield point.
+    /// As such, we need to track these borrows and record them despite of the fact
+    /// that they may succeed the said yield point in the post-order.
+    nested_scope_of_guards: SmallVec<[SmallVec<[HirId; 4]>; 4]>,
```
Comment (tmandry) [inline compiler/rustc_typeck/src/check/generator_interior.rs:31]: The outer SmallVec could probably be of len 1, since nesting these would be extremely rare in practice.

**Comment by tmandry** [comment]
Friendly ping @dingxiangfei2009, are you still able to work on this?

**Comment by dingxiangfei2009** [comment]
Sorry for keeping you waiting, @tmandry , I will apply your suggestions this morning.

File: compiler/rustc_typeck/src/check/generator_interior.rs (hunk 4 above)
Comment (dingxiangfei2009) [reply compiler/rustc_typeck/src/check/generator_interior.rs]: I gave some thoughts about it. I think a better way is to use a separate and simple visitor that only walks the patterns in the arm, given that the arm has a guard. Most part of the original `visit_pat` will be kept the same.

**Comment by tmandry** [comment]
Sorry, I was on call last week but am taking a look now.

File: compiler/rustc_typeck/src/check/generator_interior.rs [hunk 8]
```diff
@@ -210,6 +224,40 @@ impl<'a, 'tcx> Visitor<'tcx> for InteriorVisitor<'a, 'tcx> {
         NestedVisitorMap::None
     }
 
+    fn visit_arm(&mut self, arm: &'tcx Arm<'tcx>) {
+        if arm.guard.is_some() {
+            self.guard_bindings.push(<_>::default());
+        }
+        self.visit_pat(&arm.pat);
+        if let Some(ref g) = arm.guard {
```
Comment (tmandry) [inline compiler/rustc_typeck/src/check/generator_interior.rs:232]: instead of accessing the arm's fields directly, could you destructure it so if new fields are added, this gets updated? e.g. `let Arm { guard, pat } = arm;`

This code is duplicating what normally goes in `super_visit_arm()` so it's helpful to have static checks like this.

File: compiler/rustc_typeck/src/check/generator_interior.rs [hunk 9]
```diff
@@ -210,6 +224,40 @@ impl<'a, 'tcx> Visitor<'tcx> for InteriorVisitor<'a, 'tcx> {
         NestedVisitorMap::None
     }
 
+    fn visit_arm(&mut self, arm: &'tcx Arm<'tcx>) {
+        if arm.guard.is_some() {
+            self.guard_bindings.push(<_>::default());
+        }
```
Comment (tmandry) [inline compiler/rustc_typeck/src/check/generator_interior.rs:230]: This is duplicated below, I think maybe you meant to take it out?

**Review by tmandry — COMMENTED** [review]
Okay, after my comments I think this is good to go. Thanks for doing this!

File: compiler/rustc_typeck/src/check/generator_interior.rs (hunk 8 above)
Comment (dingxiangfei2009) [reply compiler/rustc_typeck/src/check/generator_interior.rs]: That is a good idea. I also updated other field accesses to `arm` towards the end of this function. There are other fields in `arm` such as `hir_id`, but I am going to elide them for now.

File: compiler/rustc_typeck/src/check/generator_interior.rs (hunk 9 above)
Comment (dingxiangfei2009) [reply compiler/rustc_typeck/src/check/generator_interior.rs]: Yes. I need to remove it.

File: compiler/rustc_typeck/src/check/generator_interior.rs (hunk 8 above)
Comment (tmandry) [reply compiler/rustc_typeck/src/check/generator_interior.rs]: If you use `..` it sort of defeats the purpose of what I was suggesting. I'd rather list out all fields and assign them to `_`.
