### PR TITLE
Replace `#[rustc_do_not_implement_via_object]` with `#[rustc_dyn_incompatible_trait]`

### LINKED ISSUE #148089: Segfault on nightly with feature Pointer Metadata
Using the [Pointer Metadata](https://github.com/rust-lang/rust/issues/81513#top) feature on nightly, the following code will segfault. This is as much as I managed to minimize the issue over the last hours. 

```rust
#![feature(ptr_metadata)]
use std::ptr::{Thin};
use std::{fmt::Debug};

trait Parent{}
trait Blanket: Parent + Thin{} //mind the + Thin which causes the SegFault

impl<T: Parent> Blanket for T{}

trait WithDebug: Blanket+Debug {}
impl<T: Blanket + Debug> WithDebug for T {}

#[derive(Debug)]
struct ZST;
impl Parent for ZST{}

fn main() {
    let dyn_ref: &dyn WithDebug = &ZST;
    println!("segfault {:?}", dyn_ref);
}
```
[Rust Playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2024&gist=ef80a1a4951525380e06d340f70f9394)

`rustc --version --verbose`:
```
rustc 1.92.0-nightly (6501e64fc 2025-10-23)
binary: rustc
commit-hash: 6501e64fcb02d22b49d6e59d10a7692ec8095619
commit-date: 2025-10-23
host: x86_64-unknown-linux-gnu
release: 1.92.0-nightly
LLVM version: 21.1.3

```

### LINKED ISSUE #148615: `dyn Pointee` should be prohibited?
`dyn Pointee` is a weird type, because it (rightly!) implements `Pointee` for itself and not the erased concrete type: 

```rust
#![feature(ptr_metadata)]
use std::ptr;
fn check<T: ?Sized + ptr::Pointee>(x: &T) {
    println!(
        "meta of {} is {}",
        std::any::type_name_of_val(x),
        std::any::type_name_of_val(&ptr::metadata(x)),
    );
}
fn main() {
    check(&100);
    check(&100 as &dyn ptr::Pointee<Metadata = ()>);
}
```

```rust
meta of i32 is ()
meta of dyn core::ptr::metadata::Pointee<Metadata = ()> is core::ptr::metadata::DynMetadata<dyn core::ptr::metadata::Pointee<Metadata = ()>>
```

This is internally consistent, but means that `dyn Pointee` is basically `dyn EmptyTrait`, despite what it claims.

Furthermore, there have been ICEs and unsoundness resulting from `dyn Pointee` or `dyn HasPointeeAsSupertrait`:

* https://github.com/rust-lang/rust/issues/112737
* https://github.com/rust-lang/rust/issues/131891
* https://github.com/rust-lang/rust/issues/148089 (via https://github.com/rust-lang/rust/issues/148615#issuecomment-3500351311)
* https://github.com/rust-lang/rust/issues/148203

I therefore propose that, at least for the time being, the `Pointee` trait should be considered *not dyn compatible.* (As a precedent, consider that `dyn Pointee<Metadata = ()>` is basically the same meaning as `dyn Sized`, which is prohibited.) This restriction can be relaxed in the future if uses for it are found and the bugs are fixed.

@rustbot label +C-bug +A-dyn-trait +A-dyn-compatibility +T-lang
cc #81513

### PR DESCRIPTION
**Pull request by zachs18**
Background: `#[rustc_do_not_implement_via_object]` on a trait currently still allows `dyn Trait` to exist (if the trait is otherwise dyn-compatible), it just means that `dyn Trait` does not automatically implement `Trait` via the normal object candidate. For some traits, this means that `dyn Trait` does not implement `Trait` at all (e.g. `Unsize` and `Tuple`). For some traits, this means that `dyn Trait` implements `Trait`, but with different associated types (e.g. `Pointee`, `DiscriminantKind`). Both of these cases can can cause issues with codegen , as seen in https://github.com/rust-lang/rust/issues/148089 (and https://github.com/rust-lang/rust/issues/148089#issuecomment-3447803823 ), because codegen assumes that if `dyn Trait` does not implement `Trait` (including if `dyn Trait<Assoc = T>` does not implement `Trait` with `Assoc == T`), then `dyn Trait` cannot be constructed, so vtable accesses on `dyn Trait` are unreachable, but this is not the case if `dyn Trait` has multiple supertraits: one which is `#[rustc_do_not_implement_via_object]`, and one which we are doing the vtable access to call a method from.

This PR replaces `#[rustc_do_not_implement_via_object]` with `#[rustc_dyn_incompatible_trait]`, which makes the marked trait dyn-incompatible, making `dyn Trait` not well-formed, instead of it being well-formed but not implementing `Trait`. This resolves rust-lang/rust#148089 by making it not compile.

May fix rust-lang/rust#148615 

The traits that are currently marked `#[rustc_do_not_implement_via_object]` are: `Sized`, `MetaSized`, `PointeeSized`, `TransmuteFrom`, `Unsize`, `BikeshedGuaranteedNoDrop`, `DiscriminantKind`, `Destruct`, `Tuple`, `FnPtr`, `Pointee`. Of these:
* `Sized` and `FnPtr` are already not dyn-compatible (`FnPtr: Copy`, which implies `Sized`)
* `MetaSized`
    * Removed `#[rustc_do_not_implement_via_object]`. Still dyn-compatible after this change. (Has a special-case in the trait solvers to ignore the object candidate for `dyn MetaSized`, since it `dyn MetaSized: MetSized` comes from the sized candidate that all `dyn Trait` get.)
* `PointeeSized`
    * Removed `#[rustc_do_not_implement_via_object]`. It doesn't seem to have been doing anything anyway ([playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2024&gist=a395626c8bef791b87a2d371777b7841)), since `PointeeSized` is removed before trait solving(?).
* `Pointee`, `DiscriminantKind`, `Unsize`, and `Tuple` being dyn-compatible without having `dyn Trait: Trait` (with same assoc tys) can be observed to cause codegen issues (https://github.com/rust-lang/rust/issues/148089) so should be made dyn-incompatible
* `Destruct`, `TransmuteFrom`, and `BikeshedGuaranteedNoDrop` I'm not sure if would be useful as object types, but they can be relaxed to being dyn-compatible later if it is determined they should be.

-----

<details> <summary> resolved </summary>

Questions before merge:

1. `dyn MetaSized: MetaSized` having both `SizedCandidate` and `ObjectCandidate`
    1. I'm not sure if the checks in compiler/rustc_trait_selection/src/traits/project.rs and compiler/rustc_next_trait_solver/src/solve/assembly/mod.rs were "load-bearing" for `MetaSized` (which is the only trait that was previously `#[rustc_do_not_implement_via_object]` that is still dyn-compatible after this change). Is it fine to just remove them? Removing them (as I did in the second commit) doesn't change any UI test results.
    3. IIUC, `dyn MetaSized` could get its `MetaSized` implementation in two ways: the object candidate (the normal `dyn Trait: Trait`) that was supressed by `#[rustc_do_not_implement_via_object]`, and the `SizedCandidate` (that all `dyn Trait` get for `dyn Trait: MetaSized`). Given that `MetaSized` has no associated types or methods, is it fine that these both exist now? Or is it better to only have the `SizedCandidate` and leave these checks in (i.e. drop the second commit, and remove the FIXMEs)?
    4. Resolved: the trait solvers special-case `dyn MetaSized` to ignore the object candidate in preference to the sizedness candidate (technically the check is for any `is_sizedness_trait`, but only `MetaSized` gets this far (`Sized` is inherently dyn-incompatible, and `dyn PointeeSized` is ill-formed for other reasons)
4. Diagnostics improvements?
    1. The diagnostics are kinda bad. If you have a `trait Foo: Pointee {}`, you now get a note that reads like *Foo* "opted out of dyn-compatbility", when really `Pointee` did that.
    2. Resolved: can be improved later
  
  <details> <summary>diagnostic example</summary>
  
```rs
#![feature(ptr_metadata)]

trait C: std::ptr::Pointee {}

fn main() {
    let y: &dyn C;
}
```
  
```rs
error[E0038]: the trait `C` is not dyn compatible
  --> c.rs:6:17
   |
 6 |     let y: &dyn C;
   |                 ^ `C` is not dyn compatible
   |
note: for a trait to be dyn compatible it needs to allow building a vtable
      for more information, visit <https://doc.rust-lang.org/reference/items/traits.html#dyn-compatibility>
  --> /home/zachary/opt_mount/zachary/Programming/rust-compiler-2/library/core/src/ptr/metadata.rs:57:1
   |
57 | #[rustc_dyn_incompatible_trait]
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ ...because it opted out of dyn-compatbility
   |
  ::: c.rs:3:7
   |
 3 | trait C: std::ptr::Pointee {}
   |       - this trait is not dyn compatible...

error: aborting due to 1 previous error

For more information about this error, try `rustc --explain E0038`.
  ```
  
  </details> </details>
  
  Still investigating "3. `compiler/rustc_hir/src/attrs/encode_cross_crate.rs`: Should `DynIncompatibleTrait` attribute be encoded cross crate?"

### CODE REVIEW

**Comment by theemathas** [comment]
Making `Destruct` be dyn-incompatible seems iffy to me...

**Comment by compiler-errors** [comment]
r? types probably is a better assignment

**Comment by zachs18** [comment]
I added some background information about why #148089 happens and how this fixes it (by making it not compile), and a list of traits that will be affected by this change.

**Comment by zachs18** [comment]
```rs
#[rustc_do_not_implement_via_object]
trait NonObjectBase {}

trait ObjectBase {}

trait Foo: NonObjectBase + ObjectBase {}
```
> would an alternative way to fix this be to also disable the builtin trait object impl for traits with a `#[rustc_do_not_implement_via_object]` super trait?

So, in the example above, we would have that `dyn Foo` now doesn't implement `ObjectBase`? (it already doesn't implement `Foo` or `NonObjectBase`.) That might work, though I think we would also need to change some stuff about dyn upcasting (i.e. disallow dyn upcasting from `dyn Trait` if it doesn't implement `Trait`, as the codegen issues are reproducible with dyn upcasting as well ([playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2024&gist=11fcd46d2eb178ba6350bb842cf7bd94)))[^1]



[^1]: We might also have codegen issues if `dyn Trait` has a manual impl of `Trait`, and then has subtraits, I'm not sure. But there is no case where that is possible at the moment since all `#[rustc_do_not_implement_via_object]` traits are also `#[rustc_deny_explicit_impl]`, so it's probably not important. In fact, it seems like the only trait that used to be `#[rustc_do_not_implement_via_object]` and allow user impls, `PointerLike`, [was the reason the two attributes were separated to begin with](https://github.com/rust-lang/rust/pull/134573), but [has since been removed](https://github.com/rust-lang/rust/pull/143308).

**Comment by lcnr** [comment]
Hmmm, this change feels somewhat iffy to me and I can't quite put my finger on why. I feel like ideally I would spend a few hours to think about all of this myself to get a clear understanding.

As an alternative, would you be up to meet in sync to talk this through?

**Comment by zachs18** [comment]
I've rebased, and added comments explaining the special-case for `dyn MetaSized` to ignore the object candidate and only have the sizedness candidate, instead of having both.

I'm still looking in to "should it be encoded cross crate", but I'm leaning towards no since `#[rustc_do_not_implement_via_object]` was no, so that's what I have update it to now.

File: compiler/rustc_trait_selection/src/traits/dyn_compatibility.rs [hunk 1]
```diff
@@ -89,11 +89,18 @@ fn dyn_compatibility_violations_for_trait(
...
         // We don't want to include the requirement from `Sized` itself to be `Sized` in the list.
         let spans = get_sized_bounds(tcx, trait_def_id);
         violations.push(DynCompatibilityViolation::SizedSelf(spans));
     }
+    // only report dyn-incompatible supertraits if there is no `Self: Sized`,
+    // to avoid duplicate notes about `Sized`.
+    let trait_def = tcx.trait_def(trait_def_id);
+    if !has_sized_self && let Some(span) = trait_def.force_dyn_incompatible {
+        violations.push(DynCompatibilityViolation::ExplicitlyDynIncompatible([span].into()));
+    }
```
Comment (lcnr) [inline compiler/rustc_trait_selection/src/traits/dyn_compatibility.rs]:
```suggestion
    if trait_has_sized_self(tcx, trait_def_id) {
        // We don't want to include the requirement from `Sized` itself to be `Sized` in the list.
        let spans = get_sized_bounds(tcx, trait_def_id);
        violations.push(DynCompatibilityViolation::SizedSelf(spans));
    } else if Some(span) = tcx.trait_def(trait_def_id).force_dyn_incompatible {
            violations.push(DynCompatibilityViolation::ExplicitlyDynIncompatible([span].into()));
    }

```
🤔

File: tests/ui/dyn-compatibility/metasized.rs [hunk 2]
```diff
@@ -0,0 +1,23 @@
+//@ run-pass
```
Comment (lcnr) [inline tests/ui/dyn-compatibility/metasized.rs:1]: please add comment explaining this test. maybe also move the tests out of `traits` and something more specific. We should have a trait object folder? :thinking:

File: tests/ui/dyn-compatibility/pointeesized.rs [hunk 3]
```diff
@@ -0,0 +1,14 @@
+//@ run-pass
```
Comment (lcnr) [inline tests/ui/dyn-compatibility/pointeesized.rs:1]: same with this test

**Review by lcnr — COMMENTED** [review]
r=me after nits. Is this in any way user-facing? I don't think it is. All the `#[rustc_do_not_implement_via_object]` traits are stable I think

*[View changes since this review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/rust/148637/22c74ba91873dd013479f86eac3e9ea10593bff9..10328b3e0c4cf30fc36175fcfa029f7c1e78d52d)*

File: tests/ui/dyn-compatibility/metasized.rs (hunk 2 above)
Comment (zachs18) [reply tests/ui/dyn-compatibility/metasized.rs:1]: We have `traits/object`? I moved them to `traits/object/sizedness` (new subdir), does that sound good?

Comment (zachs18) [reply tests/ui/dyn-compatibility/metasized.rs:1]: Oh we also have `tests/ui/dyn-compatibility` which might be better. And it already has some tests for `Sized`. I'll move them there.

File: tests/ui/dyn-compatibility/pointeesized.rs [hunk 4]
```diff
@@ -0,0 +1,17 @@
...
+//! This test and `sized-*.rs` and `metaesized.rs` test that dyn-compatibility correctly
```
Comment (lcnr) [inline tests/ui/dyn-compatibility/pointeesized.rs]:
```suggestion
//! This test and `sized-*.rs` and `metasized.rs` test that dyn-compatibility correctly
```

**Review by lcnr — COMMENTED** [review]
r=me after final nit

*[View changes since this review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/rust/148637/d940e56841ddcc05671ead99290e35ff2e98369f..1774dd89a574ecf758b4fd59d7dc3e006502994c)*
