### PR TITLE
Do not emit ConstEvaluatable goals if type-const

### LINKED ISSUE #151477: ICE: "can't type-check body of DefId" when using #[type_const] with nested generics.
I tried this code:

```rust
#![feature(min_generic_const_args)]
#![expect(incomplete_features)]

trait Hidden {const VAL: usize;}
trait Mirror {const IMAGE: usize;}

impl<T: Hidden + ?Sized> Mirror for T {
    const IMAGE: usize = T::VAL;
}
struct Wrapper<T: ?Sized>(T);

impl<T: ?Sized> Hidden for Wrapper<T> {
    const VAL: usize = {
        #[type_const]
        const A: usize = <Wrapper<T> as Mirror>::IMAGE;
        A
    };
}
trait Sanity {
    const IS_OK: bool;
}

impl<T: Hidden + ?Sized> Sanity for T {
    const IS_OK: bool = T::VAL == 0;
}

trait Service {
    fn start(&self);
}

impl<T> Service for Wrapper<T> {
    fn start(&self) where Self: Sanity, 
    {}
}
fn main() {
    let service = Wrapper(());
    service.start();
}
```

I expected to see this happen: The compiler should emit error E0401

Instead, this happened:  panics with: error: internal compiler error: .../compiler/rustc_hir_typeck/src/lib.rs:124:9: can't type-check body of DefId(...)

| Release channel                    | Result |
|-----------------------------------|--------|
| current Stable                             | error  |
| current Nightly (default solver)          | ICE  |
| Nightly + `-Znext-solver=globally`        | ICE |

### Meta

`rustc --version --verbose`:
```
rustc 1.94.0-nightly (f57eac1bf 2026-01-10)
binary: rustc
commit-hash: f57eac1bf98cb5d578e3364b64365ec398c137df
commit-date: 2026-01-10
host: x86_64-unknown-linux-gnu
release: 1.94.0-nightly
LLVM version: 21.1.8
```

<details><summary>Backtrace</summary>
<p>

```

error: expressions must be enclosed in braces to be used as const generic arguments
  --> Traitor/trait-fuzzer/results/fate/case_iter_10010_var_21/after.rs:15:26
   |
15 |         const A: usize = <Wrapper<T> as Mirror>::IMAGE;
   |                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
help: enclose the `const` expression in braces
   |
15 |         const A: usize = { <Wrapper<T> as Mirror>::IMAGE };
   |                          +                               +

error[E0401]: can't use generic parameters from outer item
  --> Traitor/trait-fuzzer/results/fate/case_iter_10010_var_21/after.rs:15:35
   |
12 | impl<T: ?Sized> Hidden for Wrapper<T> {
   |      - type parameter from outer item
...
15 |         const A: usize = <Wrapper<T> as Mirror>::IMAGE;
   |               -                   ^ use of generic parameter from outer item
   |               |
   |               generic parameter used in this inner constant item
   |
   = note: nested items are independent from their parent item for everything except for privacy and name resolution
   = note: a `const` is a separate item from the item that contains it

error: use of `const` in the type system without `#[type_const]`
  --> Traitor/trait-fuzzer/results/fate/case_iter_10010_var_21/after.rs:15:26
   |
15 |         const A: usize = <Wrapper<T> as Mirror>::IMAGE;
   |                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: the declaration must be marked with `#[type_const]`

error: internal compiler error: /rustc-dev/f57eac1bf98cb5d578e3364b64365ec398c137df/compiler/rustc_hir_typeck/src/lib.rs:124:9: can't type-check body of DefId(0:17 ~ after[9715]::{impl#1}::VAL::A)
  --> Traitor/trait-fuzzer/results/fate/case_iter_10010_var_21/after.rs:15:9
   |
15 |         const A: usize = <Wrapper<T> as Mirror>::IMAGE;
   |         ^^^^^^^^^^^^^^


thread 'rustc' (1353527) panicked at /rustc-dev/f57eac1bf98cb5d578e3364b64365ec398c137df/compiler/rustc_hir_typeck/src/lib.rs:124:9:
Box<dyn Any>
stack backtrace:
   0:     0x7fbdee0404f3 - <<std[14974c2a6d31bd09]::sys::backtrace::BacktraceLock>::print::DisplayBacktrace as core[75fca27d79ab979d]::fmt::Display>::fmt
   1:     0x7fbdee60fac8 - core[75fca27d79ab979d]::fmt::write
   2:     0x7fbdee056776 - <std[14974c2a6d31bd09]::sys::stdio::unix::Stderr as std[14974c2a6d31bd09]::io::Write>::write_fmt
   3:     0x7fbdee0160e8 - std[14974c2a6d31bd09]::panicking::default_hook::{closure#0}
   4:     0x7fbdee033d83 - std[14974c2a6d31bd09]::panicking::default_hook
   5:     0x7fbded015eaa - std[14974c2a6d31bd09]::panicking::update_hook::<alloc[97bcaa3c9f42b50c]::boxed::Box<rustc_driver_impl[8626402415690959]::install_ice_hook::{closure#1}>>::{closure#0}
   6:     0x7fbdee034062 - std[14974c2a6d31bd09]::panicking::panic_with_hook
   7:     0x7fbded053251 - std[14974c2a6d31bd09]::panicking::begin_panic::<rustc_errors[cacf81fbc0306139]::ExplicitBug>::{closure#0}
   8:     0x7fbded043506 - std[14974c2a6d31bd09]::sys::backtrace::__rust_end_short_backtrace::<std[14974c2a6d31bd09]::panicking::begin_panic<rustc_errors[cacf81fbc0306139]::ExplicitBug>::{closure#0}, !>
   9:     0x7fbded040b49 - std[14974c2a6d31bd09]::panicking::begin_panic::<rustc_errors[cacf81fbc0306139]::ExplicitBug>
  10:     0x7fbded070f91 - <rustc_errors[cacf81fbc0306139]::diagnostic::BugAbort as rustc_errors[cacf81fbc0306139]::diagnostic::EmissionGuarantee>::emit_producing_guarantee
  11:     0x7fbded5ff73c - <rustc_errors[cacf81fbc0306139]::DiagCtxtHandle>::span_bug::<rustc_span[ea6610cf11a1023c]::span_encoding::Span, alloc[97bcaa3c9f42b50c]::string::String>
  12:     0x7fbded622266 - rustc_middle[42069f076602ef26]::util::bug::opt_span_bug_fmt::<rustc_span[ea6610cf11a1023c]::span_encoding::Span>::{closure#0}
  13:     0x7fbded622412 - rustc_middle[42069f076602ef26]::ty::context::tls::with_opt::<rustc_middle[42069f076602ef26]::util::bug::opt_span_bug_fmt<rustc_span[ea6610cf11a1023c]::span_encoding::Span>::{closure#0}, !>::{closure#0}
  14:     0x7fbded61352b - rustc_middle[42069f076602ef26]::ty::context::tls::with_context_opt::<rustc_middle[42069f076602ef26]::ty::context::tls::with_opt<rustc_middle[42069f076602ef26]::util::bug::opt_span_bug_fmt<rustc_span[ea6610cf11a1023c]::span_encoding::Span>::{closure#0}, !>::{closure#0}, !>
  15:     0x7fbdeb6917d8 - rustc_middle[42069f076602ef26]::util::bug::span_bug_fmt::<rustc_span[ea6610cf11a1023c]::span_encoding::Span>
  16:     0x7fbdebb6942b - rustc_hir_typeck[f46337d5327ab94d]::typeck_with_inspect::{closure#0}::{closure#0}
  17:     0x7fbdef369738 - rustc_hir_typeck[f46337d5327ab94d]::typeck_with_inspect::{closure#0}
  18:     0x7fbdef363ef4 - rustc_query_impl[7762d22649c04fd8]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[7762d22649c04fd8]::query_impl::typeck::dynamic_query::{closure#2}::{closure#0}, rustc_middle[42069f076602ef26]::query::erase::Erased<[u8; 8usize]>>
  19:     0x7fbdee83ddf7 - rustc_query_system[4067c90f9d31d9ad]::query::plumbing::try_execute_query::<rustc_query_impl[7762d22649c04fd8]::DynamicConfig<rustc_data_structures[5b2e5bcce01f3ea3]::vec_cache::VecCache<rustc_span[ea6610cf11a1023c]::def_id::LocalDefId, rustc_middle[42069f076602ef26]::query::erase::Erased<[u8; 8usize]>, rustc_query_system[4067c90f9d31d9ad]::dep_graph::graph::DepNodeIndex>, false, false, false>, rustc_query_impl[7762d22649c04fd8]::plumbing::QueryCtxt, false>
  20:     0x7fbdee83d6c9 - rustc_query_impl[7762d22649c04fd8]::query_impl::typeck::get_query_non_incr::__rust_end_short_backtrace
  21:     0x7fbdeea81e19 - rustc_mir_build[c2fac1714b0df487]::thir::pattern::check_match::check_match
  22:     0x7fbdeea811db - rustc_query_impl[7762d22649c04fd8]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[7762d22649c04fd8]::query_impl::check_match::dynamic_query::{closure#2}::{closure#0}, rustc_middle[42069f076602ef26]::query::erase::Erased<[u8; 1usize]>>
  23:     0x7fbdeebe40ed - rustc_query_system[4067c90f9d31d9ad]::query::plumbing::try_execute_query::<rustc_query_impl[7762d22649c04fd8]::DynamicConfig<rustc_data_structures[5b2e5bcce01f3ea3]::vec_cache::VecCache<rustc_span[ea6610cf11a1023c]::def_id::LocalDefId, rustc_middle[42069f076602ef26]::query::erase::Erased<[u8; 1usize]>, rustc_query_system[4067c90f9d31d9ad]::dep_graph::graph::DepNodeIndex>, false, false, false>, rustc_query_impl[7762d22649c04fd8]::plumbing::QueryCtxt, false>
  24:     0x7fbdeebe3dbd - rustc_query_impl[7762d22649c04fd8]::query_impl::check_match::get_query_non_incr::__rust_end_short_backtrace
  25:     0x7fbdef107ee5 - rustc_mir_build[c2fac1714b0df487]::builder::build_mir
  26:     0x7fbdee60a5e9 - rustc_mir_transform[959ce5525355527d]::mir_built
  27:     0x7fbdee60a5b3 - rustc_query_impl[7762d22649c04fd8]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[7762d22649c04fd8]::query_impl::mir_built::dynamic_query::{closure#2}::{closure#0}, rustc_middle[42069f076602ef26]::query::erase::Erased<[u8; 8usize]>>
  28:     0x7fbdee83ddf7 - rustc_query_system[4067c90f9d31d9ad]::query::plumbing::try_execute_query::<rustc_query_impl[7762d22649c04fd8]::DynamicConfig<rustc_data_structures[5b2e5bcce01f3ea3]::vec_cache::VecCache<rustc_span[ea6610cf11a1023c]::def_id::LocalDefId, rustc_middle[42069f076602ef26]::query::erase::Erased<[u8; 8usize]>, rustc_query_system[4067c90f9d31d9ad]::dep_graph::graph::DepNodeIndex>, false, false, false>, rustc_query_impl[7762d22649c04fd8]::plumbing::QueryCtxt, false>
  29:     0x7fbdee83d849 - rustc_query_impl[7762d22649c04fd8]::query_impl::mir_built::get_query_non_incr::__rust_end_short_backtrace
  30:     0x7fbdee79d481 - rustc_query_impl[7762d22649c04fd8]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[7762d22649c04fd8]::query_impl::trivial_const::dynamic_query::{closure#2}::{closure#0}, rustc_middle[42069f076602ef26]::query::erase::Erased<[u8; 32usize]>>
  31:     0x7fbdee79ab2c - rustc_query_system[4067c90f9d31d9ad]::query::plumbing::try_execute_query::<rustc_query_impl[7762d22649c04fd8]::DynamicConfig<rustc_query_system[4067c90f9d31d9ad]::query::caches::DefIdCache<rustc_middle[42069f076602ef26]::query::erase::Erased<[u8; 32usize]>>, false, false, false>, rustc_query_impl[7762d22649c04fd8]::plumbing::QueryCtxt, false>
  32:     0x7fbdee79a3a0 - rustc_query_impl[7762d22649c04fd8]::query_impl::trivial_const::get_query_non_incr::__rust_end_short_backtrace
  33:     0x7fbdee60acc3 - rustc_mir_transform[959ce5525355527d]::mir_built
  34:     0x7fbdee60a5b3 - rustc_query_impl[7762d22649c04fd8]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[7762d22649c04fd8]::query_impl::mir_built::dynamic_query::{closure#2}::{closure#0}, rustc_middle[42069f076602ef26]::query::erase::Erased<[u8; 8usize]>>
  35:     0x7fbdee83ddf7 - rustc_query_system[4067c90f9d31d9ad]::query::plumbing::try_execute_query::<rustc_query_impl[7762d22649c04fd8]::DynamicConfig<rustc_data_structures[5b2e5bcce01f3ea3]::vec_cache::VecCache<rustc_span[ea6610cf11a1023c]::def_id::LocalDefId, rustc_middle[42069f076602ef26]::query::erase::Erased<[u8; 8usize]>, rustc_query_system[4067c90f9d31d9ad]::dep_graph::graph::DepNodeIndex>, false, false, false>, rustc_query_impl[7762d22649c04fd8]::plumbing::QueryCtxt, false>
  36:     0x7fbdee83d849 - rustc_query_impl[7762d22649c04fd8]::query_impl::mir_built::get_query_non_incr::__rust_end_short_backtrace
  37:     0x7fbdef46392d - rustc_mir_build[c2fac1714b0df487]::check_unsafety::check_unsafety
  38:     0x7fbdef4636ab - rustc_query_impl[7762d22649c04fd8]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[7762d22649c04fd8]::query_impl::check_unsafety::dynamic_query::{closure#2}::{closure#0}, rustc_middle[42069f076602ef26]::query::erase::Erased<[u8; 0usize]>>
  39:     0x7fbdee83bdbf - rustc_query_system[4067c90f9d31d9ad]::query::plumbing::try_execute_query::<rustc_query_impl[7762d22649c04fd8]::DynamicConfig<rustc_data_structures[5b2e5bcce01f3ea3]::vec_cache::VecCache<rustc_span[ea6610cf11a1023c]::def_id::LocalDefId, rustc_middle[42069f076602ef26]::query::erase::Erased<[u8; 0usize]>, rustc_query_system[4067c90f9d31d9ad]::dep_graph::graph::DepNodeIndex>, false, false, false>, rustc_query_impl[7762d22649c04fd8]::plumbing::QueryCtxt, false>
  40:     0x7fbdee83bb3d - rustc_query_impl[7762d22649c04fd8]::query_impl::check_unsafety::get_query_non_incr::__rust_end_short_backtrace
  41:     0x7fbdee83ac66 - <rustc_middle[42069f076602ef26]::ty::context::TyCtxt>::par_hir_body_owners::<rustc_interface[90afb413dadbe4f1]::passes::run_required_analyses::{closure#1}::{closure#0}>::{closure#0}
  42:     0x7fbdee83878a - rustc_interface[90afb413dadbe4f1]::passes::analysis
  43:     0x7fbdee837ba7 - rustc_query_impl[7762d22649c04fd8]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[7762d22649c04fd8]::query_impl::analysis::dynamic_query::{closure#2}::{closure#0}, rustc_middle[42069f076602ef26]::query::erase::Erased<[u8; 0usize]>>
  44:     0x7fbdef75cbe6 - rustc_query_system[4067c90f9d31d9ad]::query::plumbing::try_execute_query::<rustc_query_impl[7762d22649c04fd8]::DynamicConfig<rustc_query_system[4067c90f9d31d9ad]::query::caches::SingleCache<rustc_middle[42069f076602ef26]::query::erase::Erased<[u8; 0usize]>>, false, false, false>, rustc_query_impl[7762d22649c04fd8]::plumbing::QueryCtxt, false>
  45:     0x7fbdef75c948 - rustc_query_impl[7762d22649c04fd8]::query_impl::analysis::get_query_non_incr::__rust_end_short_backtrace
  46:     0x7fbdef924754 - <rustc_interface[90afb413dadbe4f1]::passes::create_and_enter_global_ctxt<core[75fca27d79ab979d]::option::Option<rustc_interface[90afb413dadbe4f1]::queries::Linker>, rustc_driver_impl[8626402415690959]::run_compiler::{closure#0}::{closure#2}>::{closure#2} as core[75fca27d79ab979d]::ops::function::FnOnce<(&rustc_session[7c34b462142e1273]::session::Session, rustc_middle[42069f076602ef26]::ty::context::CurrentGcx, alloc[97bcaa3c9f42b50c]::sync::Arc<rustc_data_structures[5b2e5bcce01f3ea3]::jobserver::Proxy>, &std[14974c2a6d31bd09]::sync::once_lock::OnceLock<rustc_middle[42069f076602ef26]::ty::context::GlobalCtxt>, &rustc_data_structures[5b2e5bcce01f3ea3]::sync::worker_local::WorkerLocal<rustc_middle[42069f076602ef26]::arena::Arena>, &rustc_data_structures[5b2e5bcce01f3ea3]::sync::worker_local::WorkerLocal<rustc_hir[a6c28dd0effa383c]::Arena>, rustc_driver_impl[8626402415690959]::run_compiler::{closure#0}::{closure#2})>>::call_once::{shim:vtable#0}
  47:     0x7fbdef81cf98 - rustc_interface[90afb413dadbe4f1]::interface::run_compiler::<(), rustc_driver_impl[8626402415690959]::run_compiler::{closure#0}>::{closure#1}
  48:     0x7fbdef665f4e - std[14974c2a6d31bd09]::sys::backtrace::__rust_begin_short_backtrace::<rustc_interface[90afb413dadbe4f1]::util::run_in_thread_with_globals<rustc_interface[90afb413dadbe4f1]::util::run_in_thread_pool_with_globals<rustc_interface[90afb413dadbe4f1]::interface::run_compiler<(), rustc_driver_impl[8626402415690959]::run_compiler::{closure#0}>::{closure#1}, ()>::{closure#0}, ()>::{closure#0}::{closure#0}, ()>
  49:     0x7fbdef665d20 - <std[14974c2a6d31bd09]::thread::lifecycle::spawn_unchecked<rustc_interface[90afb413dadbe4f1]::util::run_in_thread_with_globals<rustc_interface[90afb413dadbe4f1]::util::run_in_thread_pool_with_globals<rustc_interface[90afb413dadbe4f1]::interface::run_compiler<(), rustc_driver_impl[8626402415690959]::run_compiler::{closure#0}>::{closure#1}, ()>::{closure#0}, ()>::{closure#0}::{closure#0}, ()>::{closure#1} as core[75fca27d79ab979d]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  50:     0x7fbdef668438 - <std[14974c2a6d31bd09]::sys::thread::unix::Thread>::new::thread_start
  51:     0x7fbde9094ac3 - start_thread
                               at ./nptl/pthread_create.c:442:8
  52:     0x7fbde91268c0 - __GI___clone3
                               at ./misc/../sysdeps/unix/sysv/linux/x86_64/clone3.S:81:0
  53:                0x0 - <unknown>

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: please make sure that you have updated to the latest nightly

note: please attach the file at `/home/laix/Study/rustc-ice-2026-01-22T03_17_07-1353406.txt` to your bug report

note: rustc 1.94.0-nightly (f57eac1bf 2026-01-10) running on x86_64-unknown-linux-gnu

note: compiler flags: -Z next-solver=globally

query stack during panic:
#0 [typeck] type-checking `<impl at Traitor/trait-fuzzer/results/fate/case_iter_10010_var_21/after.rs:12:1: 12:38>::VAL::A`
#1 [check_match] match-checking `<impl at Traitor/trait-fuzzer/results/fate/case_iter_10010_var_21/after.rs:12:1: 12:38>::VAL::A`
... and 5 other queries... use `env RUST_BACKTRACE=1` to see the full query stack
error: aborting due to 4 previous errors

For more information about this error, try `rustc --explain E0401`.
```

</p>
</details>

### PR DESCRIPTION
**Pull request by JohnTitor**
Fixes rust-lang/rust#151631, fixes rust-lang/rust#151477
r? @fmease 

I'd recommend reviewing commit-by-commit, the diff is less-readable to address a cyclic issue.

### CODE REVIEW

File: compiler/rustc_trait_selection/src/traits/mod.rs [hunk 1]
```diff
@@ -592,145 +593,192 @@ pub fn try_evaluate_const<'tcx>(
...
+                        (uv.args, typing_env)
+                    }
+                };
+
+                if tcx.is_type_const(uv.def) {
+                    // Guard against self-referential type consts which would otherwise recurse.
+                    if !type_const_stack.insert(uv.def) {
+                        let guar = tcx.dcx().span_err(
+                            tcx.def_span(uv.def),
+                            "cycle detected when evaluating type-level constant",
```
Comment (JohnTitor) [inline compiler/rustc_trait_selection/src/traits/mod.rs]: I'm not sure if we should detect a cyclic error in this place though, maybe we can handle it better?

**Comment by JohnTitor** [comment]
@Human9000-bit Yeah, it should. Added a rev so that we can make sure it.

File: tests/ui/const-generics/type-const-ice-issue-151631.rs [hunk 2]
```diff
@@ -0,0 +1,38 @@
...
+trait Owner: NewTrait {
+    #[type_const]
+    const C<const N: u32>: u32;
+    #[type_const]
+    const K<const N: u32>: u32;
+}
+
+trait NewTrait {}
+
+impl NewTrait for () {}
```
Comment (fmease) [inline tests/ui/const-generics/type-const-ice-issue-151631.rs]: By adding this impl, this test doesn't reproduce the ICE on nightly/main.

```suggestion
```

File: tests/ui/const-generics/type-const-ice-issue-151631.rs [hunk 3]
```diff
@@ -0,0 +1,38 @@
+//@ compile-flags: -Znext-solver=globally
+#![feature(generic_const_items, min_generic_const_args)]
+#![feature(adt_const_params)]
+#![allow(incomplete_features)]
+#![allow(dead_code)]
```
Comment (fmease) [inline tests/ui/const-generics/type-const-ice-issue-151631.rs]: This is implied in UI tests.

```suggestion
```

File: tests/ui/const-generics/type-const-ice-issue-151631.rs
Comment (fmease) [inline tests/ui/const-generics/type-const-ice-issue-151631.rs:1]: This test isn't minimized and contains a lot of unrelated elements. Here's a smaller one:

```rs
// issue: <https://github.com/rust-lang/rust/issues/151631>
//@ compile-flags: -Znext-solver
#![feature(min_generic_const_args)]
#![expect(incomplete_features)]

trait SuperTrait {}
trait Trait: SuperTrait {
    type const K: u32;
}
impl Trait for () {
    type const K: u32 = const { 1 };
}

fn check(_: impl Trait<K = 0>) {}

fn main() {
    check(());
}
```

File: compiler/rustc_trait_selection/src/traits/mod.rs [hunk 4]
```diff
@@ -706,6 +706,25 @@ pub fn try_evaluate_const<'tcx>(
                 }
             };
 
+            if tcx.is_type_const(uv.def) {
```
Comment (fmease) [inline compiler/rustc_trait_selection/src/traits/mod.rs]: I don't know if this change makes sense, I'm not an expert in mGCA. Therefore I'll assign @BoxyUwU instead.

File: tests/ui/const-generics/type-const-cycle.rs [hunk 5]
```diff
@@ -0,0 +1,18 @@
+//@ compile-flags: -Znext-solver=globally
+#![feature(generic_const_items, min_generic_const_args)]
+#![allow(incomplete_features)]
+
+trait Owner {
+    #[type_const]
+    const C<const N: u32>: u32;
+    //~^ ERROR cycle detected when evaluating type-level constant
```
Comment (fmease) [inline tests/ui/const-generics/type-const-cycle.rs]: Ideally this error would point to the `C` in the trait impl.

File: compiler/rustc_trait_selection/src/traits/mod.rs (hunk 1 above)
Comment (fmease) [reply compiler/rustc_trait_selection/src/traits/mod.rs]: I'm don't know how/where/when we invoke `try_evaluate_const` (during normalization of course, but …) but ideally (?) either the query system would detect cycles / overflows for us (but I guess no queries are involved here) or we have a simple `depth` param similar to what type normalization does instead of storing visited definitions. idk, imma wait for Boxy

**Review by fmease — COMMENTED** [review]
Some preliminary comments & suggestions. I'm now gonna pass the assignment to Boxy since I don't feel comfortable with this part of the code (yet).

*[View changes since this review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/rust/152040/56aaf58ec02b6ac974e8364269fbb33a8a806e28..e853189de7654c9b28eb3e73a287b6aa1d5549f1)*

File: tests/ui/const-generics/type-const-ice-issue-151631.rs
Comment (JohnTitor) [reply tests/ui/const-generics/type-const-ice-issue-151631.rs:1]: Ah, I tweaked during developing then forgot to revert. Thank you! Fixed in https://github.com/rust-lang/rust/pull/152040/changes/1641602f611ebb7a91b89858a9b263432cdb287c.

File: compiler/rustc_trait_selection/src/traits/mod.rs [hunk 6]
```diff
@@ -592,159 +593,206 @@ pub fn try_evaluate_const<'tcx>(
...
-                Ok(Err(_)) => {
-                    let e = tcx.dcx().delayed_bug(
-                        "Type system constant with non valtree'able type evaluated but no error emitted",
-                    );
-                    Err(EvaluateConstErr::InvalidConstParamTy(e))
+                        (uv.args, typing_env)
+                    }
+                };
+
+                if tcx.is_type_const(uv.def) {
```
Comment (BoxyUwU) [inline compiler/rustc_trait_selection/src/traits/mod.rs]: We're not supposed to be calling `try_evaluate_const` on a type const in the first place 🤔 Whatever code is causing this to be reachable is the problematic place.

Can you look into that a bit and then explain to me what's going on there?

Comment (JohnTitor) [reply compiler/rustc_trait_selection/src/traits/mod.rs]: I see!

> Can you look into that a bit and then explain to me what's going on there?

IIUC:
1. we generate `ConstEvaluatable` obligation in `const_evaluatable_predicates_of`, including type consts.
2. the next solver handles that in `compute_const_evaluatable_goal`  by calling `delegate.evaluate_const`, which forwards to `try_evaluate_const`.

Do you have any idea for proper fix?

Comment (BoxyUwU) [reply compiler/rustc_trait_selection/src/traits/mod.rs]: Ah interesting, follow up question: Where does the `ConstEvaluatable` obligation come from? I'm not sure why `const_evaluatable_predicates_of` would be returning anything here

Comment (JohnTitor) [reply compiler/rustc_trait_selection/src/traits/mod.rs]: Sorry, I misunderstood.

`WfPredicates::visit_const` emits `ClauseKind::ConstEvaluatable(c)` for `ConstKind::Unevaluated`:

https://github.com/rust-lang/rust/blob/fbd6934114e905d3cc61adbbd7e4a355eac5d0d7/compiler/rustc_trait_selection/src/traits/wf.rs#L1019-L1021

There, IIUC  we don't have a check for type const.

And delegate calls `unnormalized_obligations`:

https://github.com/rust-lang/rust/blob/fbd6934114e905d3cc61adbbd7e4a355eac5d0d7/compiler/rustc_trait_selection/src/solve/delegate.rs#L197

This place should register `ConstEvaluatable` obligations as goals (right? sorry if I'm wrong).

Then `compute_const_evaluatable_goal` calls `evaluate_const` -> `try_evaluate_const`

Comment (BoxyUwU) [reply compiler/rustc_trait_selection/src/traits/mod.rs]: Ah okay yeah this makes sense to me now. I think the right fix would be to not emit ConstEvaluatable goals if they're for a type_const item

Comment (JohnTitor) [reply compiler/rustc_trait_selection/src/traits/mod.rs]: 👍, addressed in https://github.com/rust-lang/rust/pull/152040/changes/7602e53835b199d9809bc1b800e173f93f231d2b.

File: compiler/rustc_hir_analysis/src/collect/predicates_of.rs [hunk 7]
```diff
@@ -438,6 +438,11 @@ fn const_evaluatable_predicates_of<'tcx>(
                     return;
                 }
 
+                // Skip type consts as it isn't supposed to be calling `try_evaluate_const`.
```
Comment (BoxyUwU) [inline compiler/rustc_hir_analysis/src/collect/predicates_of.rs]:
```suggestion
                // Skip type consts as mGCA doesn't support evaluatable clauses
```

File: compiler/rustc_trait_selection/src/traits/wf.rs [hunk 8]
```diff
@@ -1016,17 +1016,20 @@ impl<'a, 'tcx> TypeVisitor<TyCtxt<'tcx>> for WfPredicates<'a, 'tcx> {
...
-                    ));
-                    let cause = self.cause(ObligationCauseCode::WellFormed(None));
-                    self.out.push(traits::Obligation::with_depth(
-                        tcx,
-                        cause,
-                        self.recursion_depth,
-                        self.param_env,
-                        predicate,
-                    ));
+                    // Skip type consts as it isn't supposed to be calling `try_evaluate_const`.
```
Comment (BoxyUwU) [inline compiler/rustc_trait_selection/src/traits/wf.rs]:
```suggestion
                    // Skip type consts as mGCA doesn't support evaluatable clauses
```

**Review by BoxyUwU — APPROVED** [review]
r=me with comment nits

*[View changes since this review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/rust/152040/d933cf483edf1605142ac6899ff32536c0ad8b22..7602e53835b199d9809bc1b800e173f93f231d2b)*
