### PR TITLE
Ignore but do not assume region obligations from unifying headers in negative coherence

### LINKED ISSUE #117986: `with_negative_coherence` fails to prevent `coherence_leak_check` overlap error
[I tried this code:](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=3f62218287dfa3226f8edb64124eca5c)

```rust
#![forbid(coherence_leak_check)]
#![feature(negative_impls, with_negative_coherence)]

pub trait Marker {}

impl<'a, T: ?Sized> !Marker for &'a T {}

trait FnMarker {}

impl<T: ?Sized + Marker> FnMarker for fn(T) {}
impl<T: ?Sized> FnMarker for fn(&T) {}
```

I expected to see this happen: *Compiles successfully*

Instead, this happened:

```
error: conflicting implementations of trait `FnMarker` for type `fn(&_)`
  --> src/lib.rs:11:1
   |
10 | impl<T: ?Sized + Marker> FnMarker for fn(T) {}
   | ------------------------------------------- first implementation here
11 | impl<T: ?Sized> FnMarker for fn(&T) {}
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ conflicting implementation for `fn(&_)`
   |
   = warning: this was previously accepted by the compiler but is being phased out; it will become a hard error in a future release!
   = note: for more information, see issue #56105 <https://github.com/rust-lang/rust/issues/56105>
   = note: this behavior recently changed as a result of a bug fix; see rust-lang/rust#56105 for details
note: the lint level is defined here
  --> src/lib.rs:1:11
   |
1  | #![forbid(coherence_leak_check)]
   |           ^^^^^^^^^^^^^^^^^^^^
```

### Meta

`rustc --version`:
```
1.76.0-nightly (2023-11-15 6b771f6b5a6c8b03b632)
```
@rustbot label A-coherence F-negative_impls requires-nightly T-compiler

### PR DESCRIPTION
**Pull request by compiler-errors**
Partly addresses a FIXME that was added in #112875. Just as we can throw away the nested trait/projection obligations from unifying two impl headers, we can also just throw away the region obligations too.

I removed part of the FIXME that was incorrect, namely:
> Given that the only region constraints we get are involving inference regions in the root, it shouldn't matter, but still sus.

This is not true when unifying `fn(A)` and `for<'b> fn(&'b B)` which ends up with placeholder region outlives from non-root universes. I'm pretty sure this is okay, though it would be nice if we were to use them as assumptions. See the `explicit` revision of the test I committed, which still fails.

Fixes #117986

r? lcnr, feel free to reassign tho.

### CODE REVIEW

**Comment by TaKO8Ki** [comment]
This pull request may have caused this error.

https://github.com/rust-lang/rust/pull/118041#issuecomment-1817581354

**Comment by compiler-errors** [comment]
This PR conflicts with #117992. I will re-approve and land each separately, I think.

@bors r-

File: compiler/rustc_trait_selection/src/traits/coherence.rs [hunk 1]
```diff
@@ -542,14 +542,14 @@ fn try_prove_negated_where_clause<'tcx>(
...
+    // the impl headers as requirements.
     //
-    // We probably should just throw away the region obligations registered up until
-    // now, or ideally use them as assumptions when proving the region obligations
-    // that we get from proving the negative predicate below.
+    // We ideally should use these region constraints as assumptions when proving
+    // the region obligations that we get from proving the negative predicate below.
     let ref infcx = root_infcx.fork();
+    let _ = infcx.take_registered_region_obligations();
+    let _ = infcx.take_and_reset_region_constraints();
```
Comment (aliemjay) [inline compiler/rustc_trait_selection/src/traits/coherence.rs:551]: I think it would more more clear if they are explicitly dropped along with `equate_obligations` before forking in `impl_intersection_has_negative_obligation`.
```rust
drop(equate_obligations);
drop(infcx.take_registered_region_obligations());
drop(infcx.take_and_reset_region_constraints());
```

**Comment by compiler-errors** [comment]
@bors r=lcnr

Updated to use `drop` explicitly, and to drop the region obligations only once.
