### PR TITLE
Warn when rustc output conflicts with existing directories

### LINKED ISSUE #13098: rustc fails in the linker when compiling `foo.rs` with a sibling directory called `foo`
```
$ echo 'fn main() {}' > foo.rs
$ mkdir foo
$ rustc foo.rs
error: linking with `cc` failed: exit code: 1
note: cc arguments: '-m64' '-L/usr/local/lib/rustlib/x86_64-unknown-linux-gnu/lib' '-o' 'foo' 'foo.o' '-lmorestack' '-nodefaultlibs' '-Wl,--as-needed' '/usr/local/lib/rustlib/x86_64-unknown-linux-gnu/lib/libgreen-2892ff35-0.10-pre.rlib' '/usr/local/lib/rustlib/x86_64-unknown-linux-gnu/lib/librand-413a5926-0.10-pre.rlib' '/usr/local/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustuv-0d450bab-0.10-pre.rlib' '/usr/local/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd-31b43f22-0.10-pre.rlib' '-L/home/huon/tmp/.rust' '-L/home/huon/tmp' '-L/home/huon/.rust' '-lpthread' '-lrt' '-lc' '-ldl' '-lm' '-lpthread' '-lgcc_s' '-Wl,-rpath,$ORIGIN/../../../usr/local/lib/rustlib/x86_64-unknown-linux-gnu/lib' '-Wl,-rpath,/usr/local/lib/rustlib/x86_64-unknown-linux-gnu/lib' '-lcompiler-rt'
note: /usr/bin/ld: cannot open output file foo: Is a directory
collect2: error: ld returned 1 exit status

error: aborting due to previous error
```

### PR DESCRIPTION
**Pull request by varkor**
When the compiled executable would conflict with a directory, display a
rustc error instead of a verbose and potentially-confusing linker
error. This is a usability improvement, and doesn’t actually change
behaviour with regards to compilation success. This addresses the
concern in #35887. Fixes #13098.

### CODE REVIEW

File: src/librustc_driver/driver.rs [hunk 1]
```diff
@@ -146,11 +146,21 @@ pub fn compile_input(sess: &Session,
...
+                        sess.err(&format!(
+                            "the input file \"{}\" would be overwritten by the generated \
+                            executable",
+                            input_path.display()));
+                        return Err(CompileIncomplete::Stopped);
+                    }
+                    if let Some(dir_path) = outputs.conflicts_with_dir() {
+                        sess.err(&format!(
+                            "the generated executable for the input file \"{}\" conflicts with the \
+                            existing directory \"{}\'",
```
Comment (kennytm) [inline src/librustc_driver/driver.rs]: OK so why the existing directory parts end with a single quote?

Comment (varkor) [reply src/librustc_driver/driver.rs]: An inadvertent stylistic experiment... Fixed.

**Comment by kennytm** [comment]
The `run-make/compiler-lookup-paths-2` test is still failing.

**Comment by pnkfelix** [comment]
As @kennytm notes, the `run-make/compiler-lookup-paths-2` is failing.

From what I can tell, this is happening because your code is (reasonably?) assuming that the paths enumerated by the `contains_path` (aka `check_output` after your changes) represent the exact set of paths that we will try to write to in this compilation attempt.

However, from what I can tell, when the `OutputType` is `OutputType::Exe`, we may apply target-dependent transformations to find the actual file path. See `rustc_trans_utils::link::out_filename` for more details here.

**Comment by pnkfelix** [comment]
However you decide to resolve this, it would probably be good to ensure that `driver::write_out_deps` and your routine share code as appropriate to enumerate the output filenames, perhaps via similar generalization as you did when you generalized `contains_path` to `check_output`. (I again ask that you add documentation when doing such generalization.)

**Comment by varkor** [comment]
Thanks for the pointers @pnkfelix — they were helpful in getting on the right track. I've only got a line or so of documentation for the two new functions at the moment — let me know if you think it's still too sparse! This uncovered (the same) bug in the "don't overwrite the input file" check too, so it was helpful to run into it here.

File: src/librustc_driver/driver.rs [hunk 2]
```diff
@@ -177,7 +163,32 @@ pub fn compile_input(sess: &Session,
             )?
         };
 
-        write_out_deps(sess, &outputs, &crate_name);
+        let output_paths = generated_output_paths(sess, &outputs, &crate_name);
+
+        // Ensure the source file isn't accidentally overwritten during compilation.
+        match *input_path {
```
Comment (pnkfelix) [inline src/librustc_driver/driver.rs]: I'd personally use `if let Some(ref input_path) = *input_path { ... }` here, especially since the `None` branch is empty.

Comment (pnkfelix) [reply src/librustc_driver/driver.rs]: (oh but I guess the pre-existing code that you're refactoring used `match`. Fine to leave it as is to ease reading the diff here, I guess.)

**Comment by kennytm** [comment]
What a rare sight.

@bors retry #42693

**Comment by kennytm** [comment]
Likely legit error on `x86_64-pc-windows-msvc`. The output is empty in the new tests `run-make\output-filename-conflicts-with-directory` and `run-make\output-filename-overwrites-input`.

**Comment by varkor** [comment]
I guess `generated_output_paths` is not returning the actual output files on `x86_64-pc-windows-msvc`. It's going to be a little hard to test without access to a machine, but I'll try looking into it.

File: src/librustc_driver/driver.rs (hunk 2 above)
Comment (varkor) [reply src/librustc_driver/driver.rs]: It turns out the diffing algorithm doesn't catch on anyway, so I'll change it (considering the change is currently breaking on `x86_64-pc-windows-msvc`).

**Comment by kennytm** [comment]
Hi @varkor,

> I guess `generated_output_paths` is not returning the actual output files on `x86_64-pc-windows-msvc`. It's going to be a little hard to test without access to a machine, but I'll try looking into it.

Have you checked the problem, or is it ready to be r+'ed again?

**Comment by varkor** [comment]
@kennytm: I wasn't able to spot anything just by eye, so I'm trying to get access to a relevant machine. I am intending to fix this, but I haven't made much progress yet. It'd be useful if there was some way to find people who can test locally for each target, for co-op debugging in these situations...

**Comment by shepmaster** [comment]
Ping from triage, @varkor ! Are you still searching for a Windows machine? 

One thing I've done is use the [IE VMs from Microsoft](https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/) — it appears they have a x64 Windows 10 variant available.

**Comment by varkor** [comment]
Thanks @shepmaster: I'll try that!

**Comment by varkor** [comment]
Okay, so the problem is that, on Windows, compiling appends a `.exe` suffix, which means there's no conflict when compiling a file without an extension. There seems to be another issue with manually specifying the output filename with `-o`, so I'm currently looking into that.

**Comment by varkor** [comment]
@pnkfelix: I think the latest changes should fix the issues on Windows! Do you think you could have a quick look over?

**Comment by pietroalbini** [comment]
@pnkfelix and @rust-lang/compiler, ping from triage! This PR needs a review.

**Comment by kennytm** [comment]
@bors retry 

The macs were not scheduled to start.
