### PR TITLE
Recover upon mistyped error on typo'd `const` in const param def

### LINKED ISSUE #111941: missing recover for typo'd `const` in const parameter definition
### Code

```Rust
pub fn bar<Const N: u8>() {}
```

### Current output

```Shell
error: expected one of `,`, `:`, `=`, or `>`, found `N`
 --> src/lib.rs:1:18
  |
1 | pub fn bar<Const N: u8>() {}
  |                  ^ expected one of `,`, `:`, `=`, or `>`
```

### Desired output

```Shell
It should say that the `const` was typo'd as `Const` and should be `Const` preferably with a `help:` thing that shows the diff (and probably should be auto-fixable?)
```

### Rationale and extra context

_No response_

### Other cases

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by jieyouxu**
And add machine-applicable fix for the typo'd `const` keyword.

### Before

```
error: expected one of `,`, `:`, `=`, or `>`, found `N`
 --> src/lib.rs:1:18
  |
1 | pub fn bar<Const N: u8>() {}
  |                  ^ expected one of `,`, `:`, `=`, or `>`
```

### After This PR

```
error: `const` keyword was mistyped as `Const`
 --> test.rs:1:8
  |
1 | fn bar<Const N: u8>() {}
  |        ^^^^^
  |
help: use the `const` keyword
  |
1 | fn bar<const N: u8>() {}
  |        ~~~~~

```

Fixes #111941.

### CODE REVIEW

File: compiler/rustc_parse/src/parser/generics.rs [hunk 1]
```diff
@@ -235,7 +235,28 @@ impl<'a> Parser<'a> {
...
+                    span,
+                    "use the `const` keyword",
+                    kw::Const.as_str(),
+                    Applicability::MachineApplicable,
+                );
+                err.emit();
+                return Err(err);
+            } else {
+                self.expect_gt()?;
+            }
```
Comment (cjgillot) [inline compiler/rustc_parse/src/parser/generics.rs:258]: Should this suggestion happen inside `parse_generic_params` or `parse_ty_param`?
Can it be made an actual recovery = if `self.may_recover()`, find a way to return `Ok` with a sensible AST?

Comment (jieyouxu) [reply compiler/rustc_parse/src/parser/generics.rs]: I *think* I got the recovery as `GenericParam` working

Comment (jieyouxu) [reply compiler/rustc_parse/src/parser/generics.rs]: Had to `attrs.clone()` a few places, not sure if I can avoid it

File: compiler/rustc_parse/src/parser/generics.rs [hunk 2]
```diff
@@ -208,6 +243,18 @@ impl<'a> Parser<'a> {
                         return Ok((None, TrailingToken::None));
                     };
 
+                    if let Some(ref mistyped_const_param) = param
+                        && mistyped_const_param.ident.name.as_str().to_ascii_lowercase() == kw::Const.as_str()
+                        && matches!(mistyped_const_param.kind, GenericParamKind::Type {..})
+                        && this.check_ident() // `Const` followed by IDENT
+                    {
+                        // We might have a typo'd `Const` that was parsed as a type parameter.
+                        if this.may_recover() {
```
Comment (cjgillot) [inline compiler/rustc_parse/src/parser/generics.rs:252]: You should call this first, to avoid needless work.

File: compiler/rustc_parse/src/parser/generics.rs [hunk 3]
```diff
@@ -208,6 +243,18 @@ impl<'a> Parser<'a> {
...
+                            let recovered_const_param = this.recover_const_param_with_mistyped_const(attrs, mistyped_const_param)?;
+                            param = Some(recovered_const_param)
+                        }
+                    }
```
Comment (cjgillot) [inline compiler/rustc_parse/src/parser/generics.rs:256]: This will be even simpler from inside `parse_ty_param`, won't it?

**Comment by cjgillot** [comment]
Thanks!
@bors r+
