### PR TITLE
Replace fcntl-based file lock with flock

### LINKED ISSUE #72157: Rustc file lock not working on WSL
WSL1 does not support `fcntl`-based advisory locks, therefore the current [src/librustc_data_structures/flock.rs](https://github.com/rust-lang/rust/blob/master/src/librustc_data_structures/flock.rs) implementation does not work.

This issue can be observed by running `cargo doc` on a repository with many crates. The `search-index.js` can miss crates.

According to my test `libc::flock` is working on WSL. We could replace `fcntl` based lock with `flock` based lock for Linux. However this will break lock over NFS for Linux 2.6.11 or earlier, I can author a PR if that's okay.

Related WSL issue: microsoft/WSL#1927

### PR DESCRIPTION
**Pull request by nbdd0121**
WSL1 does not support `fcntl`-based lock and will always report success,
therefore creating a race condition when multiple rustc processes are
modifying shared data such as `search-index.js`. WSL1 does however
support `flock`.

`flock` is supported by all unix-like platforms. The only caveat is that
Linux 2.6.11 or earlier does not support `flock` on NFS mounts, but as
the minimum supported Linux version is 2.6.18, it is not an issue.

Fixes #72157

### CODE REVIEW

**Comment by cuviper** [comment]
> `flock` is supported by all unix-like platforms.

I think this is overstated -- it's a syscall of BSD origin, and my Linux man-page says it appears on _most_ UNIX systems, but in particular it seems Solaris still does not have it.

- no `flock` here: https://docs.oracle.com/cd/E88353_01/html/E37841/makehtml-id-6.html
- noted for portability here: https://www.perkin.org.uk/posts/solaris-portability-flock.html

Since there's nothing really wrong with the current `fcntl` approach, and it's POSIX functionality, I suggest we keep using that on _most_ `unix` targets. We can change to `flock` for `linux` alone, and specifically comment that we're doing this for WSL1's sake.

(I know I suggested switching all `unix` in #72157, but now I know it is a portability hazard.)

**Comment by cuviper** [comment]
I found that Cargo uses `flock`, but it has a caution about blocking on NFS:

https://github.com/rust-lang/cargo/blob/13bded9a335a855a15b95f54779d7f8a889404dd/src/cargo/util/flock.rs#L284-L291

```rust
    // File locking on Unix is currently implemented via `flock`, which is known
    // to be broken on NFS. We could in theory just ignore errors that happen on
    // NFS, but apparently the failure mode [1] for `flock` on NFS is **blocking
    // forever**, even if the "non-blocking" flag is passed!
    //
    // As a result, we just skip all file locks entirely on NFS mounts. That
    // should avoid calling any `flock` functions at all, and it wouldn't work
    // there anyway.
    //
    // [1]: https://github.com/rust-lang/cargo/issues/2615
```

They use this for all `unix`, except on Solaris they just ignore locking:

https://github.com/rust-lang/cargo/blob/13bded9a335a855a15b95f54779d7f8a889404dd/src/cargo/util/flock.rs#L284-L291
```rust
    #[cfg(target_os = "solaris")]
    fn flock(file: &File, flag: libc::c_int) -> Result<()> {
        // Solaris lacks flock(), so simply succeed with a no-op
        Ok(())
    }
```

cc @pfmooney who rewrote that recently.

**Comment by cuviper** [comment]
cc @alexcrichton too, who reviewed that cargo change.

**Comment by pfmooney** [comment]
> cc @pfmooney who rewrote that recently.

Much of that locking code was lifted out of [fs2](https://github.com/danburkert/fs2-rs), which had become unsuitable due to maintenance concerns (not accepting patches to support new systems/targets).  Porting over the `fcntl()`-based locking for Solaris targets was considered, but was skipped for the sake of simplicity since concurrent (and conflicting) cargo operations were identified as infrequent and not a high priority.

A `flock()` implementation was [prioritized](https://smartos.org/bugview/OS-2868) in illumos (drawing its lineage back to OpenSolaris) due to the differing semantics between `flock()` and `fcntl()`-based locks, specifically around `fork()` behavior.  I'm not sure how much those differences would relate to your change here.

**Comment by nbdd0121** [comment]
> > `flock` is supported by all unix-like platforms.
> 
> I think this is overstated -- it's a syscall of BSD origin, and my Linux man-page says it appears on _most_ UNIX systems, but in particular it seems Solaris still does not have it.

Ah indeed. So here is what I originally do to ensure it's okay:
* Linux man page says its available on most UNIX systems as you pointed out.
* I checked `libc`, and `flock` is unconditionally available on all unix platforms https://github.com/rust-lang/libc/blob/0.2.70/src/unix/mod.rs#L1062.
* I checked all UNIX systems where rustc is currently supported https://forge.rust-lang.org/release/platform-support.html, to make sure it indeed have `flock`.

I should probably framed it as "all unix-like platforms" supported by rustc.

> * no `flock` here: https://docs.oracle.com/cd/E88353_01/html/E37841/makehtml-id-6.html
> * noted for portability here: https://www.perkin.org.uk/posts/solaris-portability-flock.html

Solaris isn't supported by rustc currently. I am not sure if that is a convincing enough reason to not keep the fcntl version?

> I found that Cargo uses `flock`, but it has a caution about blocking on NFS:
> 
> https://github.com/rust-lang/cargo/blob/13bded9a335a855a15b95f54779d7f8a889404dd/src/cargo/util/flock.rs#L284-L291
> 
> ```rust
>     // File locking on Unix is currently implemented via `flock`, which is known
>     // to be broken on NFS. We could in theory just ignore errors that happen on
>     // NFS, but apparently the failure mode [1] for `flock` on NFS is **blocking
>     // forever**, even if the "non-blocking" flag is passed!
>     //
>     // As a result, we just skip all file locks entirely on NFS mounts. That
>     // should avoid calling any `flock` functions at all, and it wouldn't work
>     // there anyway.
>     //
>     // [1]: https://github.com/rust-lang/cargo/issues/2615
> ```
> 

This is interesting. However Linux man page suggested that on Linux, `flock` is emulated by `fcntl` lock on NFS drives (I double checked Linux source and it is true). So the "hang" would happen with the current implementation as well. That particular issue is likely a misconfiguration which enabled lock feature on non-NFSv4 drives.

**Comment by nbdd0121** [comment]
I tested `flock`-based implementation on NFSv4 and it works fine.

BTW the current approach used in Cargo does affect people as well by not locking on NFS, see rust-lang/cargo#4629.

**Comment by alexcrichton** [comment]
FWIW we treat locking as quite optional in Cargo due to it being too restrictive if we require it everywhere. We try to use it everywhere we can but it's empirically had a lot of bugs and had to adjust a lot over time. I doubt Cargo is doing "the best thing" for all platforms under the sun still, and it probably still has issues that need to be worked through.

**Comment by nbdd0121** [comment]
@cuviper Is Solaris a platform that rustc ever intends to run on? If so I can bring back `fcntl` version and use it only for Solaris/Illumos. For other Unices I personally would use `flock` version because its nicer semantics but I'm okay with either method.

**Comment by pfmooney** [comment]
> @cuviper Is Solaris a platform that rustc ever intends to run on? If so I can bring back `fcntl` version and use it only for Solaris/Illumos. For other Unices I personally would use `flock` version because its nicer semantics but I'm okay with either method.

`flock()` is present on illumos, so the `fcntl()`-based locking is not necessary there.  The `solaris` target is currently being used by illumos systems as they transition over to the somewhat recently created `illumos` target.  (We're still waiting on it to be [enabled as a CI build](https://github.com/rust-lang/rust/pull/71272))

**Comment by cuviper** [comment]
> I tested `flock`-based implementation on NFSv4 and it works fine.

The thing I'm worried about from that comment is the "failure mode" aspect, which I inferred to mean the behavior when the network disappears. But maybe it's also problematic for NFSv3?

> @cuviper Is Solaris a platform that rustc ever intends to run on?

I don't know -- it seems the present folks really care about illumos, not solaris proper, which will be getting an independent target as mentioned.

My feeling is that we should be really careful about changing this, given the known hazards. We do need to care about it more than Cargo does itself, because `rustc` and `rustdoc` are definitely going to be called in parallel on a regular basis. In the extreme, we'd only change at all for WSL where we know `fcntl` doesn't work right -- can we tell from `uname` or something?

**Comment by nbdd0121** [comment]
> The thing I'm worried about from that comment is the "failure mode" aspect, which I inferred to mean the behavior when the network disappears. But maybe it's also problematic for NFSv3?

It's up to the configuration of NFS. If NFS is configured to be uninterruptable, then a network disconnection will cause everything to hang. In that case it does not matter how locks behave, because we will run into issues when doing other IOs as well. Most NFS-related issues are actually poor configuration.

If anything can break `flock` on Linux it'll be NFS. But Linux essentially emulates flock using fcntl on NFS drives, so if `flock` breaks, `fcntl` would break as well.

> My feeling is that we should be really careful about changing this, given the known hazards. We do need to care about it more than Cargo does itself, because `rustc` and `rustdoc` are definitely going to be called in parallel on a regular basis. In the extreme, we'd only change at all for WSL where we know `fcntl` doesn't work right -- can we tell from `uname` or something?

We could check if uname contains `Microsoft`.

File: src/librustc_data_structures/flock.rs [hunk 1]
```diff
@@ -7,18 +7,17 @@
...
 
+use std::fs::{File, OpenOptions};
 use std::io;
 use std::path::Path;
 
 cfg_if! {
-    if #[cfg(unix)] {
-        use std::ffi::{CString, OsStr};
-        use std::mem;
+    if #[cfg(target_os = "linux")] {
```
Comment (cuviper) [inline src/librustc_data_structures/flock.rs:15]: Please add a comment here about WSL, so we remember why Linux is using something different. Then I think we're good to go!
