### PR TITLE
codegen `#[naked]` functions using global asm

### LINKED ISSUE #124375: ICE: codegen: `index out of bounds: the len is 3 but the index is 4`
auto-reduced (treereduce-rust):
````rust
#![crate_type = "lib"]
#![feature(naked_functions)]
use std::arch::asm;

#[naked]
pub unsafe extern "C" fn naked_with_args_and_return(a: isize, b: isize) -> isize {
    asm!("lea rax, [rdi + rsi]", "ret", options(noreturn));
}


````

original:
````rust
// compile-flags: -C no-prepopulate-passes
// needs-asm-support
// only-x86_64

#![crate_type = "lib"]
#![feature(naked_functions)]
use std::arch::asm;

// CHECK: Function Attrs: naked
// CHECK-NEXT: define{{.*}}void @naked_empty()
#[no_mangle]
#[naked]
pub unsafe extern "C" fn asm() {
    // CHECK-NEXT: {{.+}}:
    // CHECK-NEXT: call void asm
    // CHECK-NEXT: unreachable
    asm!("ret",
         options(noreturn));
}

// CHECK: Function Attrs: naked
// CHECK-NEXT: define{{.*}}i{{[0-9]+}} @naked_with_args_and_return(i64 %a, i64 %b)
#[no_mangle]
#[naked]
pub unsafe extern "C" fn naked_with_args_and_return(a: isize, b: isize) -> isize {
    // CHECK-NEXT: {{.+}}:
    // CHECK-NEXT: call void asm
    // CHECK-NEXT: unreachable
    asm!("lea rax, [rdi + rsi]",
         "ret",
         options(noreturn));
}

````

Version information
````
rustc 1.79.0-nightly (cb3752d20 2024-04-25)
binary: rustc
commit-hash: cb3752d20e0f5d24348062211102a08d46fbecff
commit-date: 2024-04-25
host: x86_64-unknown-linux-gnu
release: 1.79.0-nightly
LLVM version: 18.1.4

````

Command:
`/home/matthias/.rustup/toolchains/master/bin/rustc -Zmir-opt-level=0`

<details><summary><strong>Program output</strong></summary>
<p>

```
warning: unused attribute
 --> /tmp/icemaker_global_tempdir.eKkYCL3DP8Cd/rustc_testrunner_tmpdir_reporting.YGEGx2f1RK8i/mvce.rs:6:1
  |
6 | #[naked]
  | ^^^^^^^^ help: remove this attribute
  |
note: attribute also specified here
 --> /tmp/icemaker_global_tempdir.eKkYCL3DP8Cd/rustc_testrunner_tmpdir_reporting.YGEGx2f1RK8i/mvce.rs:5:1
  |
5 | #[naked]
  | ^^^^^^^^
  = note: `#[warn(unused_attributes)]` on by default

WARN rustc_codegen_ssa::mir::locals Unexpected initial operand type: expected isize, found !.See <https://github.com/rust-lang/rust/issues/114858>.
WARN rustc_codegen_ssa::mir::locals Unexpected initial operand type: expected isize, found !.See <https://github.com/rust-lang/rust/issues/114858>.
thread 'rustc' panicked at /rustc/cb3752d20e0f5d24348062211102a08d46fbecff/compiler/rustc_codegen_ssa/src/mir/statement.rs:54:63:
index out of bounds: the len is 3 but the index is 4
stack backtrace:
   0:     0x7b37f3f16145 - std::backtrace_rs::backtrace::libunwind::trace::h5605728a39057d84
                               at /rustc/cb3752d20e0f5d24348062211102a08d46fbecff/library/std/src/../../backtrace/src/backtrace/libunwind.rs:105:5
   1:     0x7b37f3f16145 - std::backtrace_rs::backtrace::trace_unsynchronized::h26b02d645a74e0ae
                               at /rustc/cb3752d20e0f5d24348062211102a08d46fbecff/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7b37f3f16145 - std::sys_common::backtrace::_print_fmt::h068d097fdd201426
                               at /rustc/cb3752d20e0f5d24348062211102a08d46fbecff/library/std/src/sys_common/backtrace.rs:68:5
   3:     0x7b37f3f16145 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hdbb63c7c16d10ece
                               at /rustc/cb3752d20e0f5d24348062211102a08d46fbecff/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x7b37f3f6521b - core::fmt::rt::Argument::fmt::h67dd1b13c2f2f60d
                               at /rustc/cb3752d20e0f5d24348062211102a08d46fbecff/library/core/src/fmt/rt.rs:165:63
   5:     0x7b37f3f6521b - core::fmt::write::h7132c149ac34da54
                               at /rustc/cb3752d20e0f5d24348062211102a08d46fbecff/library/core/src/fmt/mod.rs:1157:21
   6:     0x7b37f3f0accf - std::io::Write::write_fmt::h323f8c8c2c83029d
                               at /rustc/cb3752d20e0f5d24348062211102a08d46fbecff/library/std/src/io/mod.rs:1832:15
   7:     0x7b37f3f15f1e - std::sys_common::backtrace::_print::hbbc04e79982f59bb
                               at /rustc/cb3752d20e0f5d24348062211102a08d46fbecff/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x7b37f3f15f1e - std::sys_common::backtrace::print::h30e4ba3a749f53ca
                               at /rustc/cb3752d20e0f5d24348062211102a08d46fbecff/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x7b37f3f18889 - std::panicking::default_hook::{{closure}}::h8a178c9d6b0b94e7
  10:     0x7b37f3f185cd - std::panicking::default_hook::hdd8156d952193739
                               at /rustc/cb3752d20e0f5d24348062211102a08d46fbecff/library/std/src/panicking.rs:298:9
  11:     0x7b37f084e3dc - std[8bf3ba7b94ed234c]::panicking::update_hook::<alloc[a86d15d3d60259f5]::boxed::Box<rustc_driver_impl[ff0ca504bb3c8cda]::install_ice_hook::{closure#0}>>::{closure#0}
  12:     0x7b37f3f18f86 - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::ha3edf74e61015c1d
                               at /rustc/cb3752d20e0f5d24348062211102a08d46fbecff/library/alloc/src/boxed.rs:2036:9
  13:     0x7b37f3f18f86 - std::panicking::rust_panic_with_hook::hb81630742c93e4ac
                               at /rustc/cb3752d20e0f5d24348062211102a08d46fbecff/library/std/src/panicking.rs:799:13
  14:     0x7b37f3f18d34 - std::panicking::begin_panic_handler::{{closure}}::hae457da9026d20e4
                               at /rustc/cb3752d20e0f5d24348062211102a08d46fbecff/library/std/src/panicking.rs:664:13
  15:     0x7b37f3f16609 - std::sys_common::backtrace::__rust_end_short_backtrace::h21495a629a302214
                               at /rustc/cb3752d20e0f5d24348062211102a08d46fbecff/library/std/src/sys_common/backtrace.rs:171:18
  16:     0x7b37f3f18a67 - rust_begin_unwind
                               at /rustc/cb3752d20e0f5d24348062211102a08d46fbecff/library/std/src/panicking.rs:652:5
  17:     0x7b37f3f616e3 - core::panicking::panic_fmt::h935fb4d00ba2a2fa
                               at /rustc/cb3752d20e0f5d24348062211102a08d46fbecff/library/core/src/panicking.rs:72:14
  18:     0x7b37f3f61907 - core::panicking::panic_bounds_check::h52ccb5f2347221e6
                               at /rustc/cb3752d20e0f5d24348062211102a08d46fbecff/library/core/src/panicking.rs:275:5
  19:     0x7b37f288f5b5 - rustc_codegen_ssa[1b654a979dd64848]::mir::codegen_mir::<rustc_codegen_llvm[6449e36ab917380]::builder::Builder>
  20:     0x7b37f28759d0 - rustc_codegen_llvm[6449e36ab917380]::base::compile_codegen_unit::module_codegen
  21:     0x7b37f2871c96 - <rustc_codegen_llvm[6449e36ab917380]::LlvmCodegenBackend as rustc_codegen_ssa[1b654a979dd64848]::traits::backend::ExtraBackendMethods>::compile_codegen_unit
  22:     0x7b37f29fd9a9 - rustc_codegen_ssa[1b654a979dd64848]::base::codegen_crate::<rustc_codegen_llvm[6449e36ab917380]::LlvmCodegenBackend>
  23:     0x7b37f2ab3a0c - <rustc_codegen_llvm[6449e36ab917380]::LlvmCodegenBackend as rustc_codegen_ssa[1b654a979dd64848]::traits::backend::CodegenBackend>::codegen_crate
  24:     0x7b37f2ab339f - rustc_interface[79bb94ccf3e33350]::passes::start_codegen
  25:     0x7b37f2ab2a1a - <rustc_interface[79bb94ccf3e33350]::queries::Queries>::codegen_and_build_linker
  26:     0x7b37f27dd736 - rustc_interface[79bb94ccf3e33350]::interface::run_compiler::<core[69fef399d12a0664]::result::Result<(), rustc_span[fd9590449ede6f6]::ErrorGuaranteed>, rustc_driver_impl[ff0ca504bb3c8cda]::run_compiler::{closure#0}>::{closure#1}
  27:     0x7b37f27c7727 - std[8bf3ba7b94ed234c]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[79bb94ccf3e33350]::util::run_in_thread_with_globals<rustc_interface[79bb94ccf3e33350]::util::run_in_thread_pool_with_globals<rustc_interface[79bb94ccf3e33350]::interface::run_compiler<core[69fef399d12a0664]::result::Result<(), rustc_span[fd9590449ede6f6]::ErrorGuaranteed>, rustc_driver_impl[ff0ca504bb3c8cda]::run_compiler::{closure#0}>::{closure#1}, core[69fef399d12a0664]::result::Result<(), rustc_span[fd9590449ede6f6]::ErrorGuaranteed>>::{closure#0}, core[69fef399d12a0664]::result::Result<(), rustc_span[fd9590449ede6f6]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[69fef399d12a0664]::result::Result<(), rustc_span[fd9590449ede6f6]::ErrorGuaranteed>>
  28:     0x7b37f27c74ea - <<std[8bf3ba7b94ed234c]::thread::Builder>::spawn_unchecked_<rustc_interface[79bb94ccf3e33350]::util::run_in_thread_with_globals<rustc_interface[79bb94ccf3e33350]::util::run_in_thread_pool_with_globals<rustc_interface[79bb94ccf3e33350]::interface::run_compiler<core[69fef399d12a0664]::result::Result<(), rustc_span[fd9590449ede6f6]::ErrorGuaranteed>, rustc_driver_impl[ff0ca504bb3c8cda]::run_compiler::{closure#0}>::{closure#1}, core[69fef399d12a0664]::result::Result<(), rustc_span[fd9590449ede6f6]::ErrorGuaranteed>>::{closure#0}, core[69fef399d12a0664]::result::Result<(), rustc_span[fd9590449ede6f6]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[69fef399d12a0664]::result::Result<(), rustc_span[fd9590449ede6f6]::ErrorGuaranteed>>::{closure#2} as core[69fef399d12a0664]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  29:     0x7b37f3f22e1b - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h5acff674129337c4
                               at /rustc/cb3752d20e0f5d24348062211102a08d46fbecff/library/alloc/src/boxed.rs:2022:9
  30:     0x7b37f3f22e1b - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h8aabd62c8ccb0918
                               at /rustc/cb3752d20e0f5d24348062211102a08d46fbecff/library/alloc/src/boxed.rs:2022:9
  31:     0x7b37f3f22e1b - std::sys::pal::unix::thread::Thread::new::thread_start::h65e97bc238441a51
                               at /rustc/cb3752d20e0f5d24348062211102a08d46fbecff/library/std/src/sys/pal/unix/thread.rs:108:17
  32:     0x7b37f3cc155a - <unknown>
  33:     0x7b37f3d3ea3c - <unknown>
  34:                0x0 - <unknown>

error: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: please make sure that you have updated to the latest nightly

note: rustc 1.79.0-nightly (cb3752d20 2024-04-25) running on x86_64-unknown-linux-gnu

note: compiler flags: -Z mir-opt-level=0 -Z dump-mir-dir=dir

query stack during panic:
end of query stack
warning: 1 warning emitted


```

</p>
</details>

@rustbot label +F-naked_functions

### PR DESCRIPTION
**Pull request by folkertdev**
*[View all comments](https://triagebot.infra.rust-lang.org/gh-comments/rust-lang/rust/pull/128004)*

tracking issue: https://github.com/rust-lang/rust/issues/90957

Fixes rust-lang/rust#124375

This implements the approach suggested in the tracking issue: use the existing global assembly infrastructure to emit the body of `#[naked]` functions. The main advantage is that we now have full control over what gets generated, and are no longer dependent on LLVM not sneakily messing with our output (inlining, adding extra instructions, etc).

I discussed this approach with @Amanieu and while I think the general direction is correct, there is probably a bunch of stuff that needs to change or move around here. I'll leave some inline comments on things that I'm not sure about.

Combined with https://github.com/rust-lang/rust/pull/127853, if both accepted, I think that resolves all steps from the tracking issue.

r? @Amanieu

### CODE REVIEW

File: compiler/rustc_codegen_ssa/src/codegen_attrs.rs [hunk 1]
```diff
@@ -644,7 +647,11 @@ fn codegen_fn_attrs(tcx: TyCtxt<'_>, did: LocalDefId) -> CodegenFnAttrs {
     }
 
     if codegen_fn_attrs.flags.contains(CodegenFnAttrFlags::NAKED) {
-        codegen_fn_attrs.inline = InlineAttr::Never;
+        // naked functions are generated using an extern function and global assembly. To
+        // make sure that these can be linked together by LLVM, the linkage should be external,
+        // unless the user explicitly configured something else (in which case any linker errors
+        // they encounter are their responsibility).
+        codegen_fn_attrs.linkage = codegen_fn_attrs.linkage.or(Some(Linkage::External));
```
Comment (folkertdev) [inline compiler/rustc_codegen_ssa/src/codegen_attrs.rs:654]: this is ugly of course, but appears necessary. Specifying no linkage or weak linkage causes llvm errors

File: compiler/rustc_codegen_ssa/src/mir/mod.rs [hunk 2]
```diff
@@ -171,6 +172,32 @@ pub fn codegen_mir<'a, 'tcx, Bx: BuilderMethods<'a, 'tcx>>(
...
+            funclets: IndexVec::from_fn_n(|_| None, mir.basic_blocks.len()),
+            locals: locals::Locals::empty(),
+            debug_context: None,
+            per_local_var_debug_info: None,
+            caller_location: None,
+        };
+
+        fx.codegen_naked_asm(instance);
+        return;
+    }
```
Comment (folkertdev) [inline compiler/rustc_codegen_ssa/src/mir/mod.rs:199]: this branch is weird of course. We could add an extra `NakedAsm` variant to `MonoItem` to make this a bit nicer maybe?

File: compiler/rustc_codegen_ssa/src/mir/naked_asm.rs [hunk 3]
```diff
@@ -0,0 +1,247 @@
...
+        let operands: Vec<_> =
+            operands.iter().map(|op| self.inline_to_global_operand(op)).collect();
+
+        let item_data = cx.codegen_unit().items().get(&MonoItem::Fn(instance)).unwrap();
+        let (begin, end) = crate::mir::naked_asm::prefix_and_suffix(cx.tcx(), instance, item_data);
+
+        let mut template_vec = Vec::new();
+        template_vec.push(rustc_ast::ast::InlineAsmTemplatePiece::String(begin));
+        template_vec.extend(template.iter().cloned());
+        template_vec.push(rustc_ast::ast::InlineAsmTemplatePiece::String(end));
```
Comment (folkertdev) [inline compiler/rustc_codegen_ssa/src/mir/naked_asm.rs:40]: this performs a bunch of allocations. Not sure how big a deal that is.

File: compiler/rustc_codegen_ssa/src/mir/naked_asm.rs [hunk 4]
```diff
@@ -0,0 +1,247 @@
...
+
+fn linkage_directive(linkage: Linkage) -> Option<&'static str> {
+    if true {
+        // this is required. emitting nothing or .weak will emit
+        //
+        // > Global is external, but doesn't have external or weak linkage!
+        //
+        // and then aborts compilation
+        return Some(".globl");
+    }
```
Comment (folkertdev) [inline compiler/rustc_codegen_ssa/src/mir/naked_asm.rs:104]: again, ugly, but anything other than `.globl` (so emitting nothing or `.weak`) causes LLVM errors.

File: compiler/rustc_codegen_ssa/src/mir/naked_asm.rs [hunk 5]
```diff
@@ -0,0 +1,247 @@
...
+            writeln!(begin, ".balign 4").unwrap();
+            if let Some(linkage) = linkage_directive(item_data.linkage) {
+                writeln!(begin, "{linkage} {asm_name}").unwrap();
+            }
+            if let Visibility::Hidden = item_data.visibility {
+                writeln!(begin, ".private_extern {asm_name}").unwrap();
+            }
+            if let Some(instruction_set) = attrs.instruction_set {
+                writeln!(begin, "{}", instruction_set.as_str()).unwrap();
+            }
```
Comment (folkertdev) [inline compiler/rustc_codegen_ssa/src/mir/naked_asm.rs:213]: currently instruction sets are only relevant for elf binaries (specifically arm ones). So we could remove this here, or leave them as future-proofing maybe. This same code occurs below for Coff, and is similarly not (currently) needed.

File: tests/codegen/naked-fn/x86_64-linux.rs [hunk 6]
```diff
@@ -0,0 +1,43 @@
+//@ compile-flags: -C no-prepopulate-passes -Copt-level=0
+//@ needs-asm-support
+//@ only-linux
+//@ only-x86_64
```
Comment (folkertdev) [inline tests/codegen/naked-fn/x86_64-linux.rs:4]: the output is only currently tested on x86_64 linux. How should we test other targets? I think the test runner skips any tests that don't run on the current platform. Maybe CI runs on more targets, but specifically embedded targets appear untestable here, because we do actually need `core::arch::asm` and hence cannot use `#[no_core]`.

**Comment by tgross35** [comment]
On the tracking issue a `naked_asm!` macro was proposed that would closer follow `global_asm!` (cc @Lokathor since you liked this idea). It sounds like this PR effectively turns `#[naked]` + `asm!` into exactly what `naked_asm` would do, so that would no longer be necessary?

The changes in this PR seem like good direction.

**Comment by Lokathor** [comment]
I think that separately from any internal implementation change, the surface syntax of rust should use `naked_asm` separately from `asm`, because the two have different enough user interface and semantics.

**Comment by folkertdev** [comment]
I agree that it is still a good idea to add `naked_asm!` as a public api, if only because it makes the documentation much more straightforward: instead of having to explain the interaction between `#[naked]` and `asm!`, we just mandate that `#[naked]` must use a `naked_asm!` block and the `naked_asm!` docs can give the exact details and restrictions.

But that is separate from how the codegen works, which is what this PR is for.

File: compiler/rustc_codegen_ssa/src/mir/naked_asm.rs (hunk 3 above)
Comment (tgross35) [reply compiler/rustc_codegen_ssa/src/mir/naked_asm.rs:40]: Duplicating the template seems unlikely to be a bottleneck anywhere. And you would probably have to touch areas of codegen used for stable `global_asm`, better not to worry about it unless this is shown to be a problem.

File: tests/codegen/naked-fn/x86_64-linux.rs (hunk 6 above)
Comment (tgross35) [reply tests/codegen/naked-fn/x86_64-linux.rs:4]: What exactly do you want to test? If you want to use the entire same test on different architectures you can set the check prefix

```rust
//@ revisions: x86 aarch64

//@[x86] compile-flags: --target x86_64-unknown-linux-gnu
//@[x86] filecheck-flags: --check-prefix CHECK-X86

//@[aarch64] compile-flags: --target aarch64-unknown-linux-gnu
//@[aarch64] filecheck-flags: --check-prefix CHECK-AARCH64
```

Then unspecified like `CHECK-LABEL` get tested on all platforms, but `CHECK-X86` `CHECK-X86-NEXT` only get tested on one architecture.

File: compiler/rustc_codegen_ssa/src/mir/mod.rs (hunk 2 above)
Comment (folkertdev) [reply compiler/rustc_codegen_ssa/src/mir/mod.rs:199]: This `cx.tcx().has_attr(instance.def.def_id(), rustc_span::sym::naked)` panics, apparently because the `naked` attribute is `EncodeCrossCrate::No`. I'm not sure why that is relevant here. 

```
12:     0x7f173a21e691 - <rustc_middle[ac0ad9b6bcaf7b38]::ty::context::TyCtxt>::get_attrs::<rustc_span[2f17d50bcbc9f57a]::def_id::DefId>
13:     0x7f173a3ac676 - rustc_codegen_ssa[4c7413a1cf9b9a7e]::mir::codegen_mir::<rustc_codegen_llvm[12d34c80ef723660]::builder::Builder>
14:     0x7f173a257d28 - rustc_codegen_ssa[4c7413a1cf9b9a7e]::base::codegen_instance::<rustc_codegen_llvm[12d34c80ef723660]::builder::Builder>
15:     0x7f173a2d8dd9 - <rustc_middle[ac0ad9b6bcaf7b38]::mir::mono::MonoItem as rustc_codegen_ssa[4c7413a1cf9b9a7e]::mono_item::MonoItemExt>::define::<rustc_codegen_llvm[12d34c80ef723660]::builder::Builder>
```

so, is a fundamentally different approach needed here, or would e.g. a check on

```rust
let attrs = tcx.hir().attrs(tcx.local_def_id_to_hir_id(did));
```

be OK and circumvent the assert?

File: tests/codegen/naked-fn/x86_64-linux.rs (hunk 6 above)
Comment (folkertdev) [reply tests/codegen/naked-fn/x86_64-linux.rs:4]: I think different files are needed, because the assembly is also different. 

What I'd like to check here is that for all architectures (so elf, macos, coff and then thumb too because it has some special logic) the right directives are emitted.

The problem I have is that I don't know what to put in those files if I can't run the tests locally.

Comment (tgross35) [reply tests/codegen/naked-fn/x86_64-linux.rs:4]: One file is fine. If you do compiler-flags with `--target` then it should run those all regardless of host, whereas `only-x86_64` or `only-aarch64` only run if the host is that platform. So I think you could do:

- Add revisions (as mentioned above) for all platforms you want to check on, one for each target
- Make one function that only has a simple `nop` or `ret`, something that works on multiple platforms
- For that one function use all of `CHECK-X86_64` `CHECK-AARCH64` `CHECK-X86-MACOS` etc to verify the LLVM directives. A plain `CHECK` should work on all platforms
- Have a `#[cfg(target_arch = "x86_64")]` function that has a more complete example and `CHECK-X86_64` that
- If there are any platforms you believe have specialized behavior just add a function, `cfg` it for that platform, and only use `CHECK-ARCH.

Comment (tgross35) [reply tests/codegen/naked-fn/x86_64-linux.rs:4]: LLVM has some better examples of what this looks like than we do, e.g. https://github.com/llvm/llvm-project/blob/639560353408f82ca101e12cf4edafa9a492116b/llvm/test/CodeGen/ARM/half.ll

Comment (tgross35) [reply tests/codegen/naked-fn/x86_64-linux.rs:4]: I guess you can also use the revision directly rather than setting `--check-prefix` yourself. See e.g. https://github.com/rust-lang/rust/blob/73a228116ae8c8ce73e309eee8c730ce90feac78/tests/codegen/cast-target-abi.rs

Comment (folkertdev) [reply tests/codegen/naked-fn/x86_64-linux.rs:4]: cool, that is very powerful. So can I actually run these locally? it complains

```
//@ revisions: linux windows macos thumb
//
//@[linux] compile-flags: --target x86_64-unknown-linux-gnu
//@[linux] filecheck-flags: --check-prefix CHECK-LINUX
//
//@[macos] compile-flags: --target aarch64-apple-darwin
//@[macos] filecheck-flags: --check-prefix CHECK-MACOS
//
//@[windows] compile-flags: --target x86_64-pc-windows-gnu
//@[windows] filecheck-flags: --check-prefix CHECK-WINDOWS
//
//@[thumb] compile-flags: --target thumbv7em-none-eabi
//@[thumb] filecheck-flags: --check-prefix CHECK-THUMB
```

```
error[E0463]: can't find crate for `std`
  |
  = note: the `aarch64-apple-darwin` target may not be installed
  = help: consider adding the standard library to the sysroot with `x build library --target aarch64-apple-darwin`
  = help: consider building the standard library from source with `cargo build -Zbuild-std`

error: aborting due to 1 previous error

For more information about this error, try `rustc --explain E0463`.
------------------------------------------



failures:
    [codegen] tests/codegen/naked-fn/naked-functions.rs#thumb
    [codegen] tests/codegen/naked-fn/naked-functions.rs#windows
    [codegen] tests/codegen/naked-fn/naked-functions.rs#macos
```

Comment (tgross35) [reply tests/codegen/naked-fn/x86_64-linux.rs:4]: It's running them for all targets, but it doesn't built `core` for all targets. Most cross-platform assembly tests are `#![no_core]` for that reason, but obviously you can't use `core::asm` that way.

I haven't actually tried this myself but it looks like you should be able to mark `#![no_core]` and then use `#[rustc_builtin_macro]` to redefine `asm!` and test what you want. See https://github.com/rust-lang/rust/blob/73a228116ae8c8ce73e309eee8c730ce90feac78/tests/codegen/asm-sanitize-llvm.rs#L2 as an example

Comment (folkertdev) [reply tests/codegen/naked-fn/x86_64-linux.rs]: thanks that was very helpful! There are now tests for 4 interesting targets (where the logic does something meaningfully different) plus a separate test for the `#[instruction_set]` attribute (that uses a weird old version of arm, so that got too messy in the one file).

File: compiler/rustc_codegen_ssa/src/mir/naked_asm.rs [hunk 7]
```diff
@@ -0,0 +1,247 @@
...
+            };
+
+            writeln!(begin, ".pushsection {section},\"ax\", {progbits}").unwrap();
+            writeln!(begin, ".balign 4").unwrap();
+            if let Some(linkage) = linkage_directive(item_data.linkage) {
+                writeln!(begin, "{linkage} {asm_name}").unwrap();
+            }
+            if let Visibility::Hidden = item_data.visibility {
+                writeln!(begin, ".hidden {asm_name}").unwrap();
+            }
```
Comment (folkertdev) [inline compiler/rustc_codegen_ssa/src/mir/naked_asm.rs:184]: I've not been able to actually generate code that triggers this if. Visibility just seems to always be `Default`. So this is entirely untested at the moment.

Comment (tgross35) [reply compiler/rustc_codegen_ssa/src/mir/naked_asm.rs:179]: For anything like this, drop a question on Zulip https://rust-lang.zulipchat.com/#narrow/stream/182449-t-compiler.2Fhelp. Unfortunately that enum doesn't seem to be very well documented

File: compiler/rustc_codegen_ssa/src/mir/naked_asm.rs [hunk 8]
```diff
@@ -0,0 +1,242 @@
...
+
+    match linkage {
+        Linkage::External => Some(".globl"),
+        Linkage::WeakAny | Linkage::WeakODR => Some(".weak"),
+        Linkage::LinkOnceAny | Linkage::LinkOnceODR => Some(".weak"),
+        Linkage::Internal | Linkage::Private => None, // just doesn't emit any attribute
+        Linkage::ExternalWeak => None,                // terminates with sigill on godbolt
+        Linkage::AvailableExternally => None,         // does not even emit the definition
+        Linkage::Appending => None,                   // only valid on global variables
+        Linkage::Common => None,                      // function may not have common linkage
```
Comment (bjorn3) [inline compiler/rustc_codegen_ssa/src/mir/naked_asm.rs:112]: These should probably just panic as they should be unreachable.

File: compiler/rustc_codegen_ssa/src/mir/naked_asm.rs [hunk 9]
```diff
@@ -0,0 +1,242 @@
...
+        //
+        // and then aborts compilation
+        return Some(".globl");
+    }
+
+    match linkage {
+        Linkage::External => Some(".globl"),
+        Linkage::WeakAny | Linkage::WeakODR => Some(".weak"),
+        Linkage::LinkOnceAny | Linkage::LinkOnceODR => Some(".weak"),
+        Linkage::Internal | Linkage::Private => None, // just doesn't emit any attribute
```
Comment (bjorn3) [inline compiler/rustc_codegen_ssa/src/mir/naked_asm.rs:108]: cg_clif emits assembly in a separate object file, so everything define in assembly that can be called from rust needs to be exported from the assembly object file.

Comment (bjorn3) [reply compiler/rustc_codegen_ssa/src/mir/naked_asm.rs:108]: By the way this is what cg_clif uses for translating naked functions to `global_asm!`: https://github.com/rust-lang/rustc_codegen_cranelift/blob/b929b68a5ba4570e15637b12d9e687a2ba6673d8/src/inline_asm.rs#L208-L315

File: compiler/rustc_codegen_ssa/src/mir/mod.rs [hunk 10]
```diff
@@ -171,6 +172,32 @@ pub fn codegen_mir<'a, 'tcx, Bx: BuilderMethods<'a, 'tcx>>(
...
+            unreachable_block: None,
+            terminate_block: None,
+            cleanup_kinds: None,
+            landing_pads: IndexVec::from_elem(None, &mir.basic_blocks),
+            funclets: IndexVec::from_fn_n(|_| None, mir.basic_blocks.len()),
+            locals: locals::Locals::empty(),
+            debug_context: None,
+            per_local_var_debug_info: None,
+            caller_location: None,
+        };
```
Comment (bjorn3) [inline compiler/rustc_codegen_ssa/src/mir/mod.rs:195]: Why do you need to create an entire FunctionCx for this? You can generate `String` containing assembly and then pass this to the codegen backend, right? That may allow reusing that function in cg_clif to replace it's existing naked function implementation, which doesn't use `FunctionCx`.

Comment (folkertdev) [reply compiler/rustc_codegen_ssa/src/mir/mod.rs:195]: I added it to support `asm_const` https://github.com/rust-lang/rust/issues/93332. specifically some constants were not evaluated by the time they were needed to insert them into the template. I'm open to other solutions of course, but some amount of evaluation is apparently needed at this point.

File: compiler/rustc_codegen_ssa/src/mir/naked_asm.rs (hunk 9 above)
Comment (folkertdev) [reply compiler/rustc_codegen_ssa/src/mir/naked_asm.rs:108]: yes, that code was very helpful. What is generated here is based on https://github.com/Amanieu/naked-function which is more complicated, but also supports more architectures. it would be nice of course if these could be merged.

File: compiler/rustc_codegen_ssa/src/mir/mod.rs (hunk 10 above)
Comment (bjorn3) [reply compiler/rustc_codegen_ssa/src/mir/mod.rs:195]: You don't need `FunctionCx` to do evaluation of constants. The full implementation of `eval_mir_constant` is https://github.com/rust-lang/rust/blob/2e6fc425411280c658d852813de01c5157255088/compiler/rustc_codegen_ssa/src/mir/constant.rs#L27-L29 Where `self.monomorphize()` is: https://github.com/rust-lang/rust/blob/2e6fc425411280c658d852813de01c5157255088/compiler/rustc_codegen_ssa/src/mir/mod.rs#L124-L128 You can inline both functions to get rid of the `FunctionCx` dependency.

File: compiler/rustc_codegen_ssa/src/mir/naked_asm.rs [hunk 11]
```diff
@@ -0,0 +1,253 @@
...
+            let string = common::asm_const_to_str(
+                cx.tcx(),
+                value.span,
+                const_value,
+                cx.layout_of(value.ty()),
+            );
+            GlobalAsmOperandRef::Const { string }
+        }
+        InlineAsmOperand::SymFn { value } => {
+            let instance = match value.ty().kind() {
```
Comment (bjorn3) [inline compiler/rustc_codegen_ssa/src/mir/naked_asm.rs:68]: You need to monomorphize the type first.

File: compiler/rustc_codegen_ssa/src/mir/naked_asm.rs [hunk 12]
```diff
@@ -0,0 +1,253 @@
...
+    let mut template_vec = Vec::new();
+    template_vec.push(rustc_ast::ast::InlineAsmTemplatePiece::String(begin));
+    template_vec.extend(template.iter().cloned());
+    template_vec.push(rustc_ast::ast::InlineAsmTemplatePiece::String(end));
+
+    cx.codegen_global_asm(&template_vec, &operands, options, line_spans);
+}
+
+fn inline_to_global_operand<'a, 'tcx, Bx: BuilderMethods<'a, 'tcx>>(
+    cx: &'a Bx::CodegenCx,
```
Comment (bjorn3) [inline compiler/rustc_codegen_ssa/src/mir/naked_asm.rs:45]: This function can probably just take `TyCtxt`.

File: compiler/rustc_codegen_ssa/src/mir/naked_asm.rs [hunk 13]
```diff
@@ -0,0 +1,253 @@
...
+                    ty::ParamEnv::reveal_all(),
+                    ty::EarlyBinder::bind(value.const_),
+                )
+                .eval(cx.tcx(), ty::ParamEnv::reveal_all(), value.span)
+                .expect("erroneous constant missed by mono item collection");
+            let string = common::asm_const_to_str(
+                cx.tcx(),
+                value.span,
+                const_value,
+                cx.layout_of(value.ty()),
```
Comment (bjorn3) [inline compiler/rustc_codegen_ssa/src/mir/naked_asm.rs:63]: Ah, this layout_of call uses the `CodegenCx`. This is during codegen though, so `RevealAllLayoutCx` (a wrapper around `TyCtxt`) is enough: https://github.com/rust-lang/rustc_codegen_cranelift/blob/b70ad2defd4bb5fba6af7958893e22be0f33dfdd/src/common.rs#L450-L518 Maybe it should be uplifted out of cg_clif?

File: compiler/rustc_codegen_ssa/src/mir/naked_asm.rs (hunk 11 above)
Comment (folkertdev) [reply compiler/rustc_codegen_ssa/src/mir/naked_asm.rs:68]: good to know. is the same true a couple lines up where the `layout_of(value.ty())` happens, or will evaluating the constant force monomorphization of that type?

File: compiler/rustc_codegen_ssa/src/mir/naked_asm.rs (hunk 8 above)
Comment (folkertdev) [reply compiler/rustc_codegen_ssa/src/mir/naked_asm.rs:123]: but is this function even meaningful now that we effectively force `Linkage::External` with `InstantiationMode::GloballyShared`? A user can manually override with`#[linkage = "weak"]`, but that will just crate llvm errors like this

```rust
#[naked]
#[linkage = "weak"]
extern "C" fn generic_naked<const N: u64>() -> u64 {
    unsafe {
        asm!(
            "mov rax, {}",
            "ret",
            const N,
            options(noreturn)
        );
    }
}
```

```
Global is external, but doesn't have external or weak linkage!
ptr @_ZN14naked_function13generic_naked17h0027c5bd3c9adc32E
Global is external, but doesn't have external or weak linkage!
ptr @_ZN14naked_function13generic_naked17h97e15019324bc8d7E
rustc-LLVM ERROR: Broken module found, compilation aborted!
```

Comment (folkertdev) [reply compiler/rustc_codegen_ssa/src/mir/naked_asm.rs:123]: actually my other PR https://github.com/rust-lang/rust/pull/127853 considers `#[naked]` incompatible with `#[linkage]`, so this function can just go.

File: compiler/rustc_codegen_ssa/src/mir/naked_asm.rs (hunk 11 above)
Comment (bjorn3) [reply compiler/rustc_codegen_ssa/src/mir/naked_asm.rs:68]: That neds to be monomorphized too.

File: compiler/rustc_codegen_ssa/src/mir/naked_asm.rs (hunk 8 above)
Comment (folkertdev) [reply compiler/rustc_codegen_ssa/src/mir/naked_asm.rs:123]: also the llvm errors only occur when running `cargo +stage1 rustc -- --emit=llvm-ir`, `cargo run` works just fine.

**Comment by folkertdev** [comment]
I ran into an issue where it appears that naked (const) generic functions get incorrectly inlined at some earlier point

```rust
//@ only-x86_64

#![crate_type = "lib"]
#![feature(naked_functions, asm_const, linkage)]

#[no_mangle]
fn test_const_generics(x: u64) -> u64 {
    using_const_generics::<1>(x);
    using_const_generics::<2>(x)
}

// CHECK-LABEL: using_const_generics

#[naked]
pub extern "C" fn using_const_generics<const N: u64>(x: u64) -> u64 {
    const M: u64 = 42;

    unsafe {
        core::arch::asm!(
            "xor rax, rax",
            "add rax, rdi",
            "add rax, {}",
            "add rax, {}",
            "ret",
            const N,
            const M,
            options(noreturn),
        )
    }
}
```

somehow still generates LLVM with an inline asm block

```llvm
; Function Attrs: nonlazybind uwtable
define noundef i64 @test_const_generics(i64 noundef %x) unnamed_addr #0 {
start:
  call void asm sideeffect alignstack inteldialect "xor rax, rax\0Aadd rax, rdi\0Aadd rax, 1\0Aadd rax, 42\0Aret", "~{dirflag},~{fpsr},~{flags},~{memory}"(), !srcloc !3
  unreachable
}
```

I think what's happening here is that at some earlier point the `using_const_generics` function is inlined, and because the asm block is marked as `noreturn`, the second call to `using_const_generics` is just dropped.

I tried setting `codegen_fn_attrs.inline = InlineAttr::Never` in `compiler/rustc_codegen_ssa/src/codegen_attrs.rs` but that is somehow not enough to guarantee that this generic funciont doesn't get inlined?! Weirdly, removing the `#[naked]` and replacing it with `#[inline(never)]` does generate the expected code, with 2 specializations of the generic function (this is weird because I think setting `codegen_fn_attrs.inline = InlineAttr::Never` should have the same effect as a `#[inline(never)]` in the source code). Also, this is specific somehow to (const) generics: using plain functions does not run into this issue.

File: compiler/rustc_codegen_ssa/src/mir/naked_asm.rs (hunk 13 above)
Comment (folkertdev) [reply compiler/rustc_codegen_ssa/src/mir/naked_asm.rs]: seems useful, should that be part of this PR though?

File: compiler/rustc_codegen_ssa/src/mir/naked_asm.rs (hunk 8 above)
Comment (folkertdev) [reply compiler/rustc_codegen_ssa/src/mir/naked_asm.rs]: external linkage and emitting `.globl` will now always happen. I believe it is the only way to make linking the extern function with the global asm block work reliably.

File: compiler/rustc_codegen_llvm/src/mono_item.rs [hunk 14]
```diff
@@ -62,8 +63,15 @@ impl<'tcx> PreDefineMethods<'tcx> for CodegenCx<'_, 'tcx> {
...
-        unsafe { llvm::LLVMRustSetLinkage(lldecl, base::linkage_to_llvm(linkage)) };
         let attrs = self.tcx.codegen_fn_attrs(instance.def_id());
+        let llvm_linkage =
+            if attrs.flags.contains(CodegenFnAttrFlags::NAKED) && linkage == Linkage::Internal {
+                // this is effectively an extern fn, and must have external linkage
+                llvm::Linkage::ExternalLinkage
+            } else {
+                base::linkage_to_llvm(linkage)
+            };
+        unsafe { llvm::LLVMRustSetLinkage(lldecl, llvm_linkage) };
```
Comment (folkertdev) [inline compiler/rustc_codegen_llvm/src/mono_item.rs:74]: this is very ugly, but required to link the extern fn with the global asm block. In practice, the value for `linkage` is used for both actual linkage as used here, and some form of visibility for the symbol. Setting the linkage to external earlier (e.g. in codegen_ssa when attributes are processed) is meaningfully different from doing so here (in that if it's set earlier, naked functions symbols are in the dynamic symbol table when they should not be). 

I suspect there is some better refactor/abstraction/idea here, but am not familiar enough with any of this code to see it.

**Comment by workingjubilee** [comment]
appears to be getting more work done on it? which is fine but should probably be

@rustbot author

File: compiler/rustc_middle/src/mir/mono.rs [hunk 15]
```diff
@@ -273,13 +276,38 @@ pub struct MonoItemData {
...
+/// Specifies the linkage type for a `MonoItem`, and how we know that linkage to use
+#[derive(Copy, Clone, PartialEq, Debug, TyEncodable, TyDecodable, HashStable)]
+pub enum LinkageKind {
+    /// The linkage was specified explicitly (e.g. using #[linkage = "..."])
+    Explicit(Linkage),
+    /// Assume the symbol may be used from other CGUs, a safe default
+    ImplicitExternal,
+    /// We did not find any uses from other CGUs, so it's fine to make this internal
+    ImplicitInternal,
+}
```
Comment (folkertdev) [inline compiler/rustc_middle/src/mir/mono.rs:295]: can I get a vibe-check on this type (introduced in https://github.com/rust-lang/rust/pull/128004/commits/6b8141d1165d27b6e714fed60b0bf96db2e76216). This keeps a bit more information about how we decide what linkage to use around, so the backend can be flexible and still use external linkage when the linkage is undefined (and could safely default to internal). That is required for our naked function approach to connect the extern fn declaration and the global asm body.

I'll probably pull this out into its own PR if this approach seems promising, because this one is getting large

**Comment by folkertdev** [comment]
I think this is as far as I can take it without some external feedback

@rustbot ready

**Review by Amanieu — COMMENTED** [review]
Overall LGTM. I'm still not 100% sure about the linkage-related things, but I think it's good enough to merge. We can handle any issues that are discovered later.

File: tests/codegen/naked-fn/instruction-set.rs
[the remark this answers is not in the document]
Comment (folkertdev) [reply tests/codegen/naked-fn/instruction-set.rs:1]: this is confusing, the assert is triggered in this example

```rust
    let is_thumb = tcx.sess.unstable_target_features.contains(&sym::thumb_mode);

    let attrs = tcx.codegen_fn_attrs(instance.def_id());
    let link_section = attrs.link_section.map(|symbol| symbol.as_str().to_string());
    let align = attrs.alignment.map(|a| a.bytes()).unwrap_or(4);

    let (arch_prefix, arch_suffix) = if is_arm {
        (
            match attrs.instruction_set {
                None => match is_thumb {
                    true => ".thumb\n.thumb_func",
                    false => ".arm",
                },
                Some(InstructionSetAttr::ArmT32) => {
                    assert!(is_thumb);
                    ".thumb\n.thumb_func"
                }
```

that conflicts with

```rust
/// Computes the set of target features used in a function for the purposes of
/// inline assembly.
fn asm_target_features(tcx: TyCtxt<'_>, did: DefId) -> &FxIndexSet<Symbol> {
    let mut target_features = tcx.sess.unstable_target_features.clone();
    if tcx.def_kind(did).has_codegen_attrs() {
        let attrs = tcx.codegen_fn_attrs(did);
        target_features.extend(attrs.target_features.iter().map(|feature| feature.name));
        match attrs.instruction_set {
            None => {}
            Some(InstructionSetAttr::ArmA32) => {
                // FIXME(#120456) - is `swap_remove` correct?
                target_features.swap_remove(&sym::thumb_mode);
            }
            Some(InstructionSetAttr::ArmT32) => {
                target_features.insert(sym::thumb_mode);
            }
        }
    }

    tcx.arena.alloc(target_features)
}
```

so information is getting lost somewhere I think?

File: compiler/rustc_codegen_ssa/src/mir/naked_asm.rs [hunk 16]
```diff
@@ -0,0 +1,229 @@
...
+) -> (String, String) {
+    use std::fmt::Write;
+
+    let target = &tcx.sess.target;
+    let target_arch = tcx.sess.asm_arch;
+
+    let is_arm = target.arch == "arm";
+    let is_thumb = is_arm && target.llvm_target.contains("thumb");
+
+    let mangle = (target.is_like_windows && matches!(target_arch, Some(InlineAsmArch::X86)))
```
[the remark this answers is not in the document]
Comment (folkertdev) [reply compiler/rustc_codegen_ssa/src/mir/naked_asm.rs]: that LLVM function is now used. Although because the gcc backend must do something similar, maybe the mangling logic should be pulled into rustc?

File: tests/codegen/naked-fn/instruction-set.rs
[the remark this answers is not in the document]
Comment (diondokter) [reply tests/codegen/naked-fn/instruction-set.rs:1]: I don't have deep assembly knowledge, but I do know a little bit about the hardware.

It's good to separate out two things:
- There is the hardware that is machine code
- Then there is the instructions making up that machine code

The hardware can run in two modes: Arm mode and Thumb mode. Some cpus can run both and some can only run one, but they all behave the same way. The cpus can switch which mode they're running in at runtime on the fly.
But important to know is that the hardware does not know what machine code it is running. It must be told when to switch.

Afaik, this can only be done in branch (`b`) instructions that also have the `x` (for eXchange) in them, like `bx` and `blx`. All functions (and I guess labels) are 16-bit aligned. So the lowest bit has no significance in determining the address to jump to. Instead the lowest bit is known as the 'thumb' bit. On a `bx` instruction, if the thumb bit is **not** set then the cpu will switch to (or remain in) Arm mode. If the thumb bit is set, then the cpu will switch to Thumb mode.

This is where `.thumb_func` comes in. It implies a `.thumb` directive and gives information to the assembler and linker that this is a thumb symbol and as such the thumb bit must be set when branching to it. This is called 'interworking' and there's a bit more to it because the cpu must also possibly switch modes when returning from a functions.

Then over to the instructions themselves. They can be compiled to machine code and are done so either using Arm or Thumb representation. In the assembly you can tell the assembler which one is to be used.

When adding `.arm` or `.code 32`, it means the instructions after it are to be assembled using the Arm mode.
When adding `.thumb` or `.code 16`, then the instructions will be encoded as Thumb.

Then another thing is which syntax is used. It can be `.syntax [unified | divided]`. When unified is used, then a newer assembly is used that can specify both Arm and Thumb instructions. The older divided has slightly different syntax for the two modes. I'm not sure what the default is when you don't specify it. But I believe that when looking at the instructions using e.g. objdump it's always shown with the unified syntax. I don't know... I also don't know if it's relevant for you now.

I found this nice page with directives with some short explanations:
https://sourceware.org/binutils/docs/as/ARM-Directives.html

Note though that for `.thumb_func` it says: "This directive is not necessary when generating EABI objects. On these targets the encoding is implicit when generating Thumb code."
I think that may not be true for the assembly we put into LLVM and that `.thumb_func` is required. But I've not tested that.

TLDR:

- `.arm` or `.code 32` switch the instruction encoding to Arm mode
- `.thumb` or `.code 16` switch the instruction encoding to Thumb mode
- Use `.thumb_func` to mark a symbol as a Thumb symbol. It sets up the 'interworking' so the cpu will switch to thumb mode when branching to the symbol or returning to it. It also implies `.thumb`

I hope this helps understanding! (Or at least didn't make it worse)

[the remark this answers is not in the document]
Comment (folkertdev) [reply tests/codegen/naked-fn/instruction-set.rs:1]: nice, I've just added two 


```rust
//@ revisions: arm-mode thumb-mode
//@ [arm-mode] compile-flags: --target armv5te-none-eabi
//@ [thumb-mode] compile-flags: --target thumbv5te-none-eabi

// <snip>

// CHECK: .arm
// CHECK-LABEL: test_unspecified:
// CHECK: bx lr
// CHECK: .popsection
// arm-mode: .arm
// thumb-mode: .thumb
```

i.e., on both arm and thumb mode, the `.code` value is reset to the default for the target at the end of the global asm block

That seems to fix the final open question?

**Review by Amanieu — APPROVED** [review]

**Comment by Amanieu** [comment]
r=me once conflicts are resolved.

File: compiler/rustc_middle/src/mir/mono.rs [hunk 17]
```diff
@@ -274,13 +277,60 @@ pub struct MonoItemData {
...
+    /// Naked functions are generated as a separate declaration (effectively an extern fn) and
+    /// definition (using global assembly). To link them together, some flavor of external linkage
+    /// must be used.
+    ///
+    /// This should be just an implementation detail of the backend, which is why this translation
+    /// is made at the final moment.
+    pub const fn into_naked_linkage(self) -> Linkage {
+        match self {
+            // promote Weak linkage to ExternalWeak
+            Self::Explicit(Linkage::WeakAny | Linkage::WeakODR) => Linkage::ExternalWeak,
```
[the remark this answers is not in the document]
Comment (folkertdev) [reply compiler/rustc_middle/src/mir/mono.rs:322]: yeah, well, when we don't translate to `ExternalWeak`, the llvm validation fails in the `tests/run-make/naked-symbol-visibility` test:

```
Global is external, but doesn't have external or weak linkage!
ptr @_ZN12a_rust_dylib18naked_weak_linkage17h0826a2715adfb302E
```

Searching in the llvm source for that error eventually leads to

https://github.com/llvm/llvm-project/blob/39209724e66a20080bdebc609a051dfa0eb6b49f/llvm/include/llvm/IR/GlobalValue.h#L419

```cpp
  static bool isValidDeclarationLinkage(LinkageTypes Linkage) {
    return isExternalWeakLinkage(Linkage) || isExternalLinkage(Linkage);
  }
```

so, only `ExternalWeak` and `External` are valid linkages for global values. That could be an artificial LLVM limitation, but that is the status quo.

[the remark this answers is not in the document]
Comment (folkertdev) [reply compiler/rustc_middle/src/mir/mono.rs:322]: We could of course generate an error when `linkage = "weak"` is used on a naked function, and suggest `extern_weak` instead? But I'll admit I don't fully understand the nuances of the linkage attribute (e.g. is using `extern_weak` a valid suggestion to make in that scenario; it'll compile then, but does it have the behavior you'd want?)

[the remark this answers is not in the document]
Comment (bjorn3) [reply compiler/rustc_middle/src/mir/mono.rs:314]: I think the solution for that would be to skip `predefine_fn()` when a mono item is a naked function. `predefine_fn()` is supposed to be called in the codegen unit that will define the function using regular LLVM IR. If you call an extern function (as a naked function will effectively become with this PR), `get_fn` will declare the function as `Linkage::External` already to handle it as import rather than definition.

File: compiler/rustc_codegen_ssa/src/mir/naked_asm.rs [hunk 18]
```diff
@@ -0,0 +1,248 @@
...
+            // this would make the function equal an extern definition
+            bug!("Functions may not have available_externally linkage")
+        }
+        Linkage::Appending => bug!("Only global variables can have appending linkage!"),
+        Linkage::Common => bug!("Functions may not have common linkage"),
+        Linkage::ExternalWeak => {
+            // FIXME: actually this causes a SIGILL in LLVM
+            bug!("Functions may not have external weak linkage")
+        }
+    };
```
Comment (folkertdev) [inline compiler/rustc_codegen_ssa/src/mir/naked_asm.rs:175]: @bjorn3 that worked out well, thanks for that hint!

It does reintroduce this match. I plan to make a separate PR that limits the usage of the linkage attribute so that at least e.g. common linkage on a function gets rejected nicely earlier on.

Comment (bjorn3) [reply compiler/rustc_codegen_ssa/src/mir/naked_asm.rs:175]: For the cases where we don't yet check that it isn't used, I think emitting a fatal error rather than a `bug!()` would be nicer, but then again `#[linkage]` can be abused in many ways already (some likely causing an ICE or LLVM crash), so it isn't all that important to avoid an ICE here IMO.

File: compiler/rustc_codegen_llvm/src/mono_item.rs [hunk 19]
```diff
@@ -58,8 +58,8 @@ impl<'tcx> PreDefineCodegenMethods<'tcx> for CodegenCx<'_, 'tcx> {
 
         let fn_abi = self.fn_abi_of_instance(instance, ty::List::empty());
         let lldecl = self.declare_fn(symbol_name, fn_abi, Some(instance));
-        llvm::set_linkage(lldecl, base::linkage_to_llvm(linkage));
         let attrs = self.tcx.codegen_fn_attrs(instance.def_id());
+        llvm::set_linkage(lldecl, base::linkage_to_llvm(linkage));
```
Comment (bjorn3) [inline compiler/rustc_codegen_llvm/src/mono_item.rs:62]: This change doesn't have any effect, right?

File: compiler/rustc_codegen_ssa/src/codegen_attrs.rs [hunk 20]
```diff
@@ -542,6 +542,13 @@ fn codegen_fn_attrs(tcx: TyCtxt<'_>, did: LocalDefId) -> CodegenFnAttrs {
         }
     });
 
+    // naked function MUST NOT be inlined! This attribute is required for the rust compiler itself,
+    // but not for the code generation backend because at that point the naked function will just be
+    // a declaration, with a definition provided in global assembly.
+    if codegen_fn_attrs.flags.contains(CodegenFnAttrFlags::NAKED) {
+        codegen_fn_attrs.inline = InlineAttr::Never;
+    }
```
Comment (bjorn3) [inline compiler/rustc_codegen_ssa/src/codegen_attrs.rs:550]: Does this change have an effect?

File: compiler/rustc_codegen_ssa/src/mir/naked_asm.rs [hunk 21]
```diff
@@ -0,0 +1,248 @@
...
+
+    // see https://godbolt.org/z/cPK4sxKor
+    let linkage = match item_data.linkage {
+        Linkage::External => ".globl",
+        Linkage::LinkOnceAny => ".weak",
+        Linkage::LinkOnceODR => ".weak",
+        Linkage::WeakAny => ".weak",
+        Linkage::WeakODR => ".weak",
+        Linkage::Internal => ".local",
+        Linkage::Private => ".local",
```
Comment (bjorn3) [inline compiler/rustc_codegen_ssa/src/mir/naked_asm.rs:164]: I can't find `.local` documented anywhere. And the compiler explorer link doesn't use it either.

**Comment by folkertdev** [comment]
doesn't bors normally report that the PR is now in the queue etc? Did something break?

**Comment by matthiaskrgr** [comment]
@bors r-  
failed in https://github.com/rust-lang/rust/pull/133697#issuecomment-2509761705 I guess

**Comment by folkertdev** [comment]
Yes, the build fails for the `x86_64-gnu-nopt` configuration, because this regex does not match:

```rust
// CHECK: declare x86_intrcc void @page_fault_handler(ptr {{.*}}, i64 {{.*}}){{.*}}#[[ATTRS:[0-9]+]]
// CHECK-NOT: memcpy
#[naked]
#[no_mangle]
pub extern "x86-interrupt" fn page_fault_handler(_: u64, _: u64) {
    unsafe {
        core::arch::naked_asm!("ud2");
    }
}
```

we get these declarations

```
; opt level 0
declare x86_intrcc void @page_fault_handler(ptr byval([8 x i8]) align 8, i64) unnamed_addr #1
; opt level != 0
declare x86_intrcc void @page_fault_handler(ptr noalias nocapture noundef byval([8 x i8]) align 8 dereferenceable(8), i64 noundef) unnamed_addr #1
```

The space after `i64` in the original regex made the regex not match for opt level 0. Removing the space fixes the issue.

@rustbot ready

**Comment by folkertdev** [comment]
fixed another issue in the naked-asan test when compiled without optimizations. I haven't found a way to run that test locally, so the feedback loop here is kind of terrible (especially because this PR was in the queue for a week).

Can we run some try jobs here? I suspect that folks are cautious to include these PRs that touch assembly in rollups: they often fail in CI because it's just kind of impossible to thoroughly test locally. I think if we pass the x86_64 and aarch64 CI tests we can be pretty confident it'll succeed.

@rustbot ready

**Comment by fmease** [comment]
https://github.com/rust-lang/rust/pull/134069#issuecomment-2529594594
@bors r-

**Comment by fmease** [comment]
https://github.com/rust-lang/rust/pull/128004/commits/10faf24a6144c849e7380b87f77465139facb8c2

@bors try

**Comment by folkertdev** [comment]
something with x86_64 apple this time.

The `generics.rs` test failed; I suspect the reason is that something gets reordered in the file, in combination with the CHECKs being subly incorrect, trying to match something that comes after the label that is now emitted before
the label (I suspect that was not true in an earlier version of this branch).

Hopefully that try job will tell if that commit actually fixes the issue. On my x86_64 linux it's always worked fine, and apple is hard to test if you don't have the hardware.

**Comment by folkertdev** [comment]
for my information, this is marked as `rollup=never` so that rollups don't fail because of this? or is there some inherent reason to not include this PR in a rollup?

I'll try to clean up the commit history further; this has been a lot of experimentation getting the corner cases right, so it's gotten messy.

let's see if this works now given the delegation

@bors try

**Comment by folkertdev** [comment]
@bors try

(typo'd x86_64...)

**Comment by tgross35** [comment]
> for my information, this is marked as `rollup=never` so that rollups don't fail because of this? or is there some inherent reason to not include this PR in a rollup?

Nothing specific, anything that has a higher chance of failure usually gets excluded from rollups. This one is is just is target-sensitive and has gone through a couple of rounds already.

**Comment by folkertdev** [comment]
is i686-mingw just flaky? its failure seems pretty arbitrary, not anything to do with this PR? If it is flaky then I think this is ready (tested locally on aarch64-apple, the try builds cover most other cases). But if the try failure is real that needs to be debugged.

**Comment by tgross35** [comment]
> is i686-mingw just flaky? its failure seems pretty arbitrary, not anything to do with this PR? If it is flaky then I think this is ready (tested locally on aarch64-apple, the try builds cover most other cases). But if the try failure is real that needs to be debugged.

I was about to retry only that job to verify, but looks like the answer is yes 🙂 https://github.com/rust-lang/rust/pulls?q=is%3Apr+label%3ACI-spurious-fail-mingw+.

@bors r=Amanieu

**Comment by tgross35** [comment]
That looks spurious, I don't think this touched anything that test covers.

@bors retry

**Comment by Lokathor** [comment]
Question: My understanding of global_asm is that it can't be culled during linking, even if the global_asm is never called. Does `#[naked]` now also prevent a function from being cut from the final binary even when it's not called?

**Comment by Amanieu** [comment]
> Question: My understanding of global_asm is that it can't be culled during linking, even if the global_asm is never called. Does `#[naked]` now also prevent a function from being cut from the final binary even when it's not called?

That's not true, global_asm absolutely can be culled during linking. It usually isn't because it emits to `.text` by default, but naked functions are emitted to a separate section which can be excluded from linking if they are not used.

**Comment by nbdd0121** [comment]
This breaks use of CFI instructions in unwinding crate: https://github.com/nbdd0121/unwinding/issues/41

**Comment by folkertdev** [comment]
@bjorn3 is this related to the `.eh_frame`? that is, should the code author write the `.cfg_startproc`/`.cfi_endproc` directives in this case, or is that actually the responsibility of the compiler?

We certainly can emit those directives, but I don't know whether we should, or leave it to the assembly author.

**Comment by Amanieu** [comment]
These directives need to be provided by the assembly author. It is up to them to declare that the naked function has valid unwind info.

**Comment by nbdd0121** [comment]
Before this change the CFI instructions are emitted by LLVM and it's illegal to have `.cfi_startproc` inside naked asm.

**Comment by Amanieu** [comment]
The previous behavior was actually context-dependent: the compiler may or may not insert `cfi_startproc` depending on various factors such as whether the panic mode is unwind or abort, whether unwind info is force-enabled, etc.

This makes writing code that uses CFI directives quite brittle and it's a problem I've hit before in libfringe (the predecessor of corosensei). It's much better to let users provide `.cfi_startproc` when they are providing unwind info for a naked function.
