### PR TITLE
Fix in-place collection leak when remaining element destructor panic

### LINKED ISSUE #101628: In-place optimisation in IntoIterator can lead to memory leak
I tried this code:

```rust
fn main() {
    #[derive(Debug)]
    struct Old(i32);

    impl Drop for Old {
        fn drop(&mut self) {
            if self.0 == 44 {
                panic!();
            }

            println!("Dropped Old: {}", self.0);
        }
    }

    #[derive(Debug)]
    struct New(i32);

    impl Drop for New {
        fn drop(&mut self) {
            println!("Dropped New: {}", self.0);
        }
    }

    let vec: Vec<Old> = vec![Old(11), Old(22), Old(33), Old(44), Old(55)];
    let vec_ptr = vec.as_ptr();

    let mapped_vec: Vec<New> = vec.into_iter().map(|x| New(x.0)).take(2).collect();
    let mapped_vec_ptr = mapped_vec.as_ptr();

    println!("vec_ptr:    {vec_ptr:?}");
    println!("mapped_vec: {mapped_vec_ptr:?}");
    println!("{mapped_vec:?}");
}
```

I expected to see this happen:

The drop implementation for `New(11)` and `New(22)` is called.

Instead, this happened:

Everything that was mapped and the allocation was leaked.

### Meta

`rustc --version --verbose`:

```
rustc 1.63.0 (4b91a6ea7 2022-08-08)
binary: rustc
commit-hash: 4b91a6ea7258a947e59c6522cd5898e7c0a6a88f
commit-date: 2022-08-08
host: aarch64-apple-darwin
release: 1.63.0
LLVM version: 14.0.5
```

I discovered this issue when I learned that `IntoIterator` re-uses a `Vec` allocation if possible. Which prompted me to read the code. Running the example with `cargo miri run` also reports the memory leak. And changing `New(i32)` to `New(i64)` no longer displays the memory leak. This is what I think happens:

```
[ 11| 22| 33| 44| 55] Values
[ 0 | 1 | 2 | 3 | 4 ] Indices

[Old|Old|Old|Old|Old] Start (default fn from_iter)

[New|Old|Old|Old|Old] Map [0] (fn collect_in_place)
[New|New|Old|Old|Old] Map [1] (fn collect_in_place)

[New|New|Drp|Old|Old] Drop [2] (fn forget_allocation_drop_remaining)
[New|New|Drp|Old|Old] Drop [3] (fn forget_allocation_drop_remaining) PANIC
```

While dropping `[3]` the `ptr::drop_in_place(remaining)` call in `forget_allocation_drop_remaining` panics.

Then `[4]` is being dropped, but honestly I don't really understand why. My understanding is that `ptr::drop_in_place(remaining)` should unwind. If anyone can explain this, please do so.

Then as part of unwinding `collect_in_place` `IntoIter` is dropped, but it has its fields set to an empty buffer of len 0, so it does nothing. Note, I suspect more optimal code gen could be achieved by using `mem::forget` to avoid generating code for the `IntoIter` drop that will never do anything after we cleared the fields.

The two created `New` will never get dropped, thus leading to the memory leak. Plus the main `Vec` allocation, previously owned by `IntoIterator` as stored in `dst_buf` will be leaked too. Because it was cleared in `forget_allocation_drop_remaining` and assumed to be taken over by `let vec = unsafe { Vec::from_raw_parts(dst_buf, len, cap) };` but we never reached that point.

---

Proposed solution, a drop guard in `collect_in_place` that guards the `forget_allocation_drop_remaining` call and would drop the head in this case `0..2` and the backing allocation if `forget_allocation_drop_remaining` panics.

### PR DESCRIPTION
**Pull request by SkiFire13**
Fixes #101628

cc @the8472

I went for the drop guard route, placing it immediately before the `forget_allocation_drop_remaining` call and after the comment, as to signal they are closely related. 

I also updated the test to check for the leak, though the only change really needed was removing the leak clean up for miri since now that's no longer leaked.

### CODE REVIEW

File: library/alloc/tests/vec.rs [hunk 1]
```diff
@@ -1110,23 +1110,31 @@ fn test_from_iter_specialization_panic_during_iteration_drops() {
 }
 
 #[test]
-fn test_from_iter_specialization_panic_during_drop_leaks() {
-    static mut DROP_COUNTER: usize = 0;
+fn test_from_iter_specialization_panic_during_drop_doesnt_leak() {
+    static mut DROP_COUNTER_SHOULD_BE_DROPPED: usize = 0;
+    static mut DROP_COUNTER_DROPPED_TWICE: usize = 0;
```
Comment (the8472) [inline library/alloc/tests/vec.rs:1115]: the name is quite confusing. nothing should be dropped twice

File: library/alloc/src/vec/in_place_collect.rs [hunk 2]
```diff
@@ -193,12 +193,16 @@ where
 
         // Drop any remaining values at the tail of the source but prevent drop of the allocation
         // itself once IntoIter goes out of scope.
-        // If the drop panics then we also leak any elements collected into dst_buf.
+        // If the drop panics then we also try to drop the destination buffer and its elements.
+        // This is safe because `forget_allocation_drop_remaining` forgets the allocation *before*
+        // trying to drop the remaining elements.
```
Comment (the8472) [inline library/alloc/src/vec/in_place_collect.rs:198]: This relies on a guarantee that `forget_allocation_drop_remaining` _will not panic_ before having relinquished the allocation. The panic behavior should be added to the method docs.

File: library/alloc/tests/vec.rs [hunk 3]
```diff
@@ -1137,21 +1145,17 @@ fn test_from_iter_specialization_panic_during_drop_leaks() {
...
-        let mut v = vec![Droppable::DroppedTwice(Box::new(123)), Droppable::PanicOnDrop];
-        to_free = v.as_mut_ptr();
-        cap = v.capacity();
-        let _ = v.into_iter().take(0).collect::<Vec<_>>();
+        let v = vec![
+            Droppable::ShouldBeDropped,
+            Droppable::DroppedTwice(Box::new(123)),
+            Droppable::PanicOnDrop,
+        ];
+        let _ = v.into_iter().take(1).collect::<Vec<_>>();
```
Comment (the8472) [inline library/alloc/tests/vec.rs:1154]: maybe add a map() here that only creates a `ShouldBeDropped` variant when things logically get moved into the output vec?

The New/Old distinction from #101628 is helpful.

**Review by the8472 — COMMENTED** [review]
I assume this passes miri?

File: library/alloc/tests/vec.rs (hunk 1 above)
Comment (SkiFire13) [reply library/alloc/tests/vec.rs:1115]: I copied the variant name, but that also had a weird name.

**Comment by the8472** [comment]
You should also update the `Drop- and panic-safety` section in the module docs.

**Comment by SkiFire13** [comment]
> I assume this passes miri?

I'm having a bit of trouble running miri tests with the modified stdlib since I'm on windows, but I think I'm getting there.

**Comment by SkiFire13** [comment]
Ok I managed to run it after some problems with invalid language items but in the end it worked and the test passes.

File: library/alloc/tests/vec.rs [hunk 4]
```diff
@@ -1110,48 +1110,53 @@ fn test_from_iter_specialization_panic_during_iteration_drops() {
...
+            println!("Dropped New: {}", self.0);
+        }
+    }
 
     let _ = std::panic::catch_unwind(AssertUnwindSafe(|| {
-        let mut v = vec![Droppable::DroppedTwice(Box::new(123)), Droppable::PanicOnDrop];
-        to_free = v.as_mut_ptr();
-        cap = v.capacity();
-        let _ = v.into_iter().take(0).collect::<Vec<_>>();
+        let v = vec![Old(0), Old(1), Old(2), Old(3), Old(4)];
```
Comment (Voultapher) [inline library/alloc/tests/vec.rs:1148]: Not important, just as a note I went with 11 etc. as numbers, because they are les easy to confuse for indices.

File: library/alloc/tests/vec.rs [hunk 5]
```diff
@@ -1110,48 +1110,53 @@ fn test_from_iter_specialization_panic_during_iteration_drops() {
 }
 
 #[test]
-fn test_from_iter_specialization_panic_during_drop_leaks() {
-    static mut DROP_COUNTER: usize = 0;
+fn test_from_iter_specialization_panic_during_drop_doesnt_leak() {
```
Comment (Voultapher) [inline library/alloc/tests/vec.rs:1113]: +1 for adding/adjusting a test.

File: library/alloc/src/vec/in_place_collect.rs [hunk 6]
```diff
@@ -193,12 +196,16 @@ where
...
         // itself once IntoIter goes out of scope.
-        // If the drop panics then we also leak any elements collected into dst_buf.
+        // If the drop panics then we also try to drop the destination buffer and its elements.
+        // This is safe because `forget_allocation_drop_remaining` immediately forgets the allocation
+        // and won't panic before that.
         //
         // Note: This access to the source wouldn't be allowed by the TrustedRandomIteratorNoCoerce
         // contract (used by SpecInPlaceCollect below). But see the "O(1) collect" section in the
         // module documenttation why this is ok anyway.
+        let dst_guard = InPlaceDstBufDrop { ptr: dst_buf, len, cap };
```
Comment (Voultapher) [inline library/alloc/src/vec/in_place_collect.rs:206]: I'm afraid this will lead to type confusion.`dst_buf` is `T` aka `New` but we ought to drop them as `Old`.

**Review by Voultapher — CHANGES_REQUESTED** [review]

File: library/alloc/src/vec/in_place_collect.rs (hunk 6 above)
Comment (SkiFire13) [reply library/alloc/src/vec/in_place_collect.rs:206]: `src.forget_allocation_drop_remaining()` is the one that drops the old elements.
`dst_guard` is meant to drop the new elements (and the allocation) in case dropping an old element panics.

I see however the potential for confusion since the original docs were meant to annotate just the `src.forget_allocation_drop_remaining()`

File: library/alloc/tests/vec.rs (hunk 4 above)
Comment (SkiFire13) [reply library/alloc/tests/vec.rs:1148]: I went for 0-4 exactly because they're indices, which makes indexing into the `DROP_COUNT_{OLD,NEW}` easier

Comment (Voultapher) [reply library/alloc/tests/vec.rs:1148]: That makes sense, didn't notice it.

**Review by Voultapher — APPROVED** [review]

**Comment by Voultapher** [comment]
I'm not too familiar with the PR process for this repository. I marked the changes as approved, because from my perspective they are good and complete.

File: library/alloc/src/vec/in_place_collect.rs [hunk 7]
```diff
@@ -191,14 +194,19 @@ where
             );
         }
 
-        // Drop any remaining values at the tail of the source but prevent drop of the allocation
-        // itself once IntoIter goes out of scope.
-        // If the drop panics then we also leak any elements collected into dst_buf.
+        // `forget_allocation_drop_remaining` drops any remaining values at the tail of the source
+        // but prevent drop of the allocation itself once `IntoIter` goes out of scope.
```
Comment (the8472) [inline library/alloc/src/vec/in_place_collect.rs:198]: There's some grammar issue here. "drops" vs "but prevent"

File: library/alloc/src/vec/in_place_collect.rs [hunk 8]
```diff
@@ -191,14 +194,19 @@ where
...
+        // `dst_guard` takes care of dropping the allocation and the new values if and only if
+        // `forget_allocation_drop_remaining` panics while dropping any of the old values.
+        // This is safe because `forget_allocation_drop_remaining` immediately forgets the allocation
+        // and won't panic before that.
```
Comment (the8472) [inline library/alloc/src/vec/in_place_collect.rs:202]: This section could be shortened by saying that allocation ownership is transferred to `InPlaceDstBufDrop` before any panic can happen and then point to the docs of `forget_allocation_drop_remaining`.

**Review by the8472 — COMMENTED** [review]
I ran some vec benches locally and didn't see any changes, so this should be good. Plus there are some codegen tests covering primitives (but not U: Drop) that ensure it optimizes in the ideal case so from a perspective this should be fine.

With the test and miri passing it should be fine too from the safety perspective.
It seems pretty straight-forward.

1. pass ownership from IntoIter to InPlaceDstBufDrop
2. drop src (can panic)
3. drop sink (on panic) (can panic)
4. if not panic: pass ownership to final vec

So at no time there's duplicate ownership while things can panic.

So there are only a few minor things left about the comments

File: library/alloc/src/vec/in_place_collect.rs (hunk 8 above)
Comment (SkiFire13) [reply library/alloc/src/vec/in_place_collect.rs]: I tried rewording the comment with ownership in mind. I'm not sure how I could have pointed to `forget_allocation_drop_remaining`'s docs while still shortening the comment.
