### PR TITLE
Make call suggestions more general and more accurate

### LINKED ISSUE #101054: Suggest calling `size_of` when it is missing parens in a comparison
Given the following code: 

```rust
fn is_one_byte<T>() -> bool {
    if std::mem::size_of::<T> == 1 {
        true
    } else {
        false
    }
}
```

The current output is:

```
Compiling playground v0.0.1 (/playground)
error[[E0369]](https://doc.rust-lang.org/stable/error-index.html#E0369): binary operation `==` cannot be applied to type `fn() -> usize {std::mem::size_of::<T>}`
 --> src/lib.rs:2:31
  |
2 |     if std::mem::size_of::<T> == 1 {
  |        ---------------------- ^^ - {integer}
  |        |
  |        fn() -> usize {std::mem::size_of::<T>}

error[[E0308]](https://doc.rust-lang.org/stable/error-index.html#E0308): mismatched types
 --> src/lib.rs:2:34
  |
2 |     if std::mem::size_of::<T> == 1 {
  |                                  ^ expected fn item, found integer
  |
  = note: expected fn item `fn() -> usize {std::mem::size_of::<T>}`
                found type `{integer}`

Some errors have detailed explanations: E0308, E0369.
For more information about an error, try `rustc --explain E0308`.
error: could not compile `playground` due to 2 previous errors
```

Ideally the output should look like:

```
Try calling the `size_of` function:

    std::mem::size_of::<T>()
                          ^^ try calling the `size_of` function        
```

-------------------------

Probably worth not making this diagnostic suggestion specific to `size_of` but to any type error where there is a comparison of a function and the return type of that function.

### PR DESCRIPTION
**Pull request by compiler-errors**
Cleans up some suggestions that have to do with adding `()` to make typeck happy. 

1. Drive-by rename of `expr_t` to `base_ty` since it's the type of the `base_expr`
1. Autoderef until we get to a callable type in `suggest_fn_call`.
1. Don't erroneously suggest calling constructor when a method/field does not exist on it.
1. Suggest calling a method receiver if its function output has a method (e.g. `fn.method()` => `fn().method()`)
1. Extend call suggestions to type parameters, fn pointers, trait objects where possible
1. Suggest calling in operators too (fixes #101054)
1. Use `/* {ty} */` as argument placeholder instead of just `_`, which is confusing and makes suggestions look less like `if let` syntax.

### CODE REVIEW

File: src/test/ui/functions-closures/fn-help-with-err.rs [hunk 1]
```diff
@@ -1,16 +1,28 @@
 // This test case checks the behavior of typeck::check::method::suggest::is_fn on Ty::Error.
+
+struct Foo;
```
Comment (compiler-errors) [inline src/test/ui/functions-closures/fn-help-with-err.rs:3]: Had to fix this test since we no longer say "perhaps you wish to call it" on a method that doesn't exist.

File: src/test/ui/typeck/issue-87181/enum-variant.rs [hunk 2]
```diff
@@ -6,7 +6,7 @@ enum Foo{
     Tup()
 }
 impl Foo {
-    fn foo() { }
+    fn foo(&self) { }
```
Comment (compiler-errors) [inline src/test/ui/typeck/issue-87181/enum-variant.rs:9]: Had to fix this test because the suggestion makes no sense without it

File: compiler/rustc_errors/src/lib.rs [hunk 3]
```diff
@@ -1248,9 +1248,13 @@ impl HandlerInner {
     }
 
     fn treat_err_as_bug(&self) -> bool {
-        self.flags
-            .treat_err_as_bug
-            .map_or(false, |c| self.err_count() + self.lint_err_count >= c.get())
+        self.flags.treat_err_as_bug.map_or(false, |c| {
```
Comment (compiler-errors) [inline compiler/rustc_errors/src/lib.rs:1251]: Well, I didn't mean to include this, but this is a fix to `-Ztreat-err-as-bug` which doesn't count delayed span bugs correctly. I can remove it and put it into another PR if needed.

--

detailed explanation: If we emit an error A, delay a bug B, then emit error C. Then:
1. running `-Ztreat-err-as-bug=1` will make it ICE on A.
2. running `-Ztreat-err-as-bug=2` will make it ICE on B.
3. running `-Ztreat-err-as-bug=3` will skip over B and will make rust _skip_ over C.

So there's literally no value `N` such that `-Ztreat-err-as-bug=N` will properly work to catch C. We add the delayed good path and span bugs into the count here so this works properly now.
