### PR TITLE
Retire ast::TyAliasWhereClauses.

### LINKED ISSUE #138010: ICE: `mid > len` on leading assoc ty / lazy type alias where clause with attributes
auto-reduced (treereduce-rust):
````rust
#![feature(lazy_type_alias)]

fn needs_copy<T>()  {

type F<T>
where
    #[cfg(a)] T: TraitA,
    #[cfg(b)] T: TraitB,
     
     
     ():,
    
    
     ():, 
= T;
    this(&x);
}

````

original:
````rust
//~ ERROR: cannot find type `Foo`
#![allow(non_upper_case_globals)]


trait TheTrait { fn dummy(&self) { } } // should require *all* lifetimes.

impl TheTrait for &'static isize { }

fn foo<'a, F>(b) where &'a T : TheTrait {
    }

fn needs_copy<T>(_: &'static T) where &'static T : TheTrait {

fn main() {
    static x: isize = 1;
    foo(PhantomData<T>),
}

#[allow(type_alias_bounds)]
type F<T>
where
    #[cfg(a)] T: TraitA,
    #[cfg(b)] T: TraitB,
    #[cfg_attr(a, cfg(a))] T: TraitAA,
    #[cfg_attr(b, cfg(b))] T: TraitBB,
    #[derive(Clone)] ():,
    //~^ ERROR most attributes are not supported in `where` clauses
    //~| ERROR expected non-macro attribute, found attribute macro `derive`
    #[rustfmt::skip] ():, //~ ERROR most attributes are not supported in `where` clauses
= T;
    this(&x);
}

````

Version information
````
rustc 1.87.0-nightly (fd17deacc 2025-03-04)
binary: rustc
commit-hash: fd17deacce374a4185c882795be162e17b557050
commit-date: 2025-03-04
host: x86_64-unknown-linux-gnu
release: 1.87.0-nightly
LLVM version: 20.1.0

````

Possibly related line of code:
https://github.com/rust-lang/rust/blob/fd17deacce374a4185c882795be162e17b557050/compiler/rustc_ast_passes/src/ast_validation.rs#L134-L146

Command:
`/home/matthias/.rustup/toolchains/master/bin/rustc -Zcrate-attr=feature(lazy_type_alias)`

<details><summary><strong>Program output</strong></summary>
<p>

```

thread 'rustc' panicked at compiler/rustc_ast_passes/src/ast_validation.rs:140:55:
mid > len
stack backtrace:
   0:     0x7550207dad94 - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::h38d103f25b5fc9da
   1:     0x7550210057e2 - core::fmt::write::h51e5c982d87d838d
   2:     0x7550222d4511 - std::io::Write::write_fmt::h24e7c9ef42bcecab
   3:     0x7550207dabf2 - std::sys::backtrace::BacktraceLock::print::h2f36236a0c89f5ad
   4:     0x7550207dd4d2 - std::panicking::default_hook::{{closure}}::hfa3a01d30bf38a16
   5:     0x7550207dd0c4 - std::panicking::default_hook::h73a43ec84dfb2d2e
   6:     0x75501f92bdd7 - std[5b59e6f68f39e4a3]::panicking::update_hook::<alloc[a5cfa563521ef073]::boxed::Box<rustc_driver_impl[3a7877a37badcc56]::install_ice_hook::{closure#1}>>::{closure#0}
   7:     0x7550207ddd43 - std::panicking::rust_panic_with_hook::h7086c047409dd55a
   8:     0x7550207dda06 - std::panicking::begin_panic_handler::{{closure}}::hbcc7938463cd12bd
   9:     0x7550207db259 - std::sys::backtrace::__rust_end_short_backtrace::hf8fc633b7853f6d2
  10:     0x7550207dd6fd - rust_begin_unwind
  11:     0x75501d45e500 - core::panicking::panic_fmt::h416190ca0b61f92d
  12:     0x7550215a8be3 - <rustc_ast_passes[e09985d241b551c4]::ast_validation::AstValidator>::check_type_alias_where_clause_location
  13:     0x7550215aca53 - <rustc_ast_passes[e09985d241b551c4]::ast_validation::AstValidator as rustc_ast[8d12759f5817a2f9]::visit::Visitor>::visit_item
  14:     0x7550215b2c9f - <rustc_ast_passes[e09985d241b551c4]::ast_validation::AstValidator as rustc_ast[8d12759f5817a2f9]::visit::Visitor>::visit_fn
  15:     0x7550215aa474 - <rustc_ast_passes[e09985d241b551c4]::ast_validation::AstValidator as rustc_ast[8d12759f5817a2f9]::visit::Visitor>::visit_item
  16:     0x7550215a5694 - rustc_interface[2148282fb0834f58]::passes::resolver_for_lowering_raw
  17:     0x7550215a480d - rustc_query_impl[d10ddfe12c3a8e74]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[d10ddfe12c3a8e74]::query_impl::resolver_for_lowering_raw::dynamic_query::{closure#2}::{closure#0}, rustc_middle[20fb34f80dd5af75]::query::erase::Erased<[u8; 16usize]>>
  18:     0x7550215a47eb - <rustc_query_impl[d10ddfe12c3a8e74]::query_impl::resolver_for_lowering_raw::dynamic_query::{closure#2} as core[436ac50667b45076]::ops::function::FnOnce<(rustc_middle[20fb34f80dd5af75]::ty::context::TyCtxt, ())>>::call_once
  19:     0x755022054ed8 - rustc_query_system[3033f91d22641c6f]::query::plumbing::try_execute_query::<rustc_query_impl[d10ddfe12c3a8e74]::DynamicConfig<rustc_query_system[3033f91d22641c6f]::query::caches::SingleCache<rustc_middle[20fb34f80dd5af75]::query::erase::Erased<[u8; 16usize]>>, false, false, false>, rustc_query_impl[d10ddfe12c3a8e74]::plumbing::QueryCtxt, false>
  20:     0x755022054a47 - rustc_query_impl[d10ddfe12c3a8e74]::query_impl::resolver_for_lowering_raw::get_query_non_incr::__rust_end_short_backtrace
  21:     0x755022079a2d - rustc_interface[2148282fb0834f58]::passes::create_and_enter_global_ctxt::<core[436ac50667b45076]::option::Option<rustc_interface[2148282fb0834f58]::queries::Linker>, rustc_driver_impl[3a7877a37badcc56]::run_compiler::{closure#0}::{closure#2}>::{closure#2}::{closure#0}
  22:     0x7550220f19e0 - rustc_interface[2148282fb0834f58]::interface::run_compiler::<(), rustc_driver_impl[3a7877a37badcc56]::run_compiler::{closure#0}>::{closure#1}
  23:     0x755021f20608 - std[5b59e6f68f39e4a3]::sys::backtrace::__rust_begin_short_backtrace::<rustc_interface[2148282fb0834f58]::util::run_in_thread_with_globals<rustc_interface[2148282fb0834f58]::util::run_in_thread_pool_with_globals<rustc_interface[2148282fb0834f58]::interface::run_compiler<(), rustc_driver_impl[3a7877a37badcc56]::run_compiler::{closure#0}>::{closure#1}, ()>::{closure#0}, ()>::{closure#0}::{closure#0}, ()>
  24:     0x755021f20ef4 - <<std[5b59e6f68f39e4a3]::thread::Builder>::spawn_unchecked_<rustc_interface[2148282fb0834f58]::util::run_in_thread_with_globals<rustc_interface[2148282fb0834f58]::util::run_in_thread_pool_with_globals<rustc_interface[2148282fb0834f58]::interface::run_compiler<(), rustc_driver_impl[3a7877a37badcc56]::run_compiler::{closure#0}>::{closure#1}, ()>::{closure#0}, ()>::{closure#0}::{closure#0}, ()>::{closure#1} as core[436ac50667b45076]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  25:     0x755021f222f7 - std::sys::pal::unix::thread::Thread::new::thread_start::hbb5e0f14d5ca8b98
  26:     0x75501c0a370a - <unknown>
  27:     0x75501c127aac - <unknown>
  28:                0x0 - <unknown>

error: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: please make sure that you have updated to the latest nightly

note: rustc 1.87.0-nightly (fd17deacc 2025-03-04) running on x86_64-unknown-linux-gnu

note: compiler flags: -Z crate-attr=feature(lazy_type_alias) -Z dump-mir-dir=dir

query stack during panic:
#0 [resolver_for_lowering_raw] getting the resolver for lowering
end of query stack

```

</p>
</details>

@rustbot label +F-lazy_type_alias

### PR DESCRIPTION
**Pull request by cjgillot**
`ast::TyAliasWhereClauses` is a tentative to avoid forgetting predicates when manipulating the AST.
It is incompatible with `cfg` attributes on where clauses.

This PR uses a regular `WhereClause` for the "second" clause.

Fixes https://github.com/rust-lang/rust/issues/138010
cc https://github.com/rust-lang/rust/pull/138037

### CODE REVIEW

File: tests/ui/where-clauses/cfg-attr-issue-138010-1.rs
Comment (fmease) [inline tests/ui/where-clauses/cfg-attr-issue-138010-1.rs:1]: Could you use the more minimal reproducers, https://github.com/rust-lang/rust/issues/138010#issuecomment-2698305052 and/or https://github.com/rust-lang/rust/issues/138010#issuecomment-3084754765 which are less obfuscated. Moreover, https://github.com/rust-lang/rust/issues/138010#issuecomment-3084754765 wouldn't require any extra unstable features.

File: compiler/rustc_ast_lowering/src/item.rs [hunk 1]
```diff
@@ -282,7 +279,8 @@ impl<'hir> LoweringContext<'_, 'hir> {
                 // opaque type Foo1: Trait
                 let ident = self.lower_ident(*ident);
                 let mut generics = generics.clone();
-                add_ty_alias_where_clause(&mut generics, *where_clauses, true);
+                generics.where_clause.predicates.extend_from_slice(&after_where_clause.predicates);
```
Comment (fmease) [inline compiler/rustc_ast_lowering/src/item.rs]: Could you move the `extend_from_slice` bit into `add_ty_alias_where_clause`?

File: compiler/rustc_ast_lowering/src/item.rs [hunk 2]
```diff
@@ -36,20 +36,17 @@ pub(super) struct ItemLowerer<'a, 'hir> {
...
-        if where_clauses.before.has_where_token || !where_clauses.after.has_where_token {
-            where_clauses.before
-        } else {
-            where_clauses.after
-        };
-    generics.where_clause.has_where_token = where_clause.has_where_token;
-    generics.where_clause.span = where_clause.span;
+    let where_clause = if before.0 || !after.0 { before } else { after };
+    generics.where_clause.has_where_token = where_clause.0;
+    generics.where_clause.span = where_clause.1;
```
Comment (fmease) [inline compiler/rustc_ast_lowering/src/item.rs]:
```suggestion
    (generics.where_clause.has_where_token, generics.where_clause.span) =
        if before.0 || !after.0 { before } else { after };
```

**Comment by jackh726** [comment]
IIRC adding the purpose of adding this type was never to avoid allocating vecs, but rather to maintain the two separate Span locations and the predicates derived for them, and also unify the handling of the where clauses (with the idea that we may remove the ability to remove the before where clauses at some point, I also don't remember if there was some specific motivating reason for this or if it was just a general decision).

I'm a little surprised we don't regress any test outputs, but I guess all the info is still there, but now less well-defined.

I have mixed feelings here. I worry that this could lead to places checking the where clauses in `generics` but not in `after_where_clauses`, that was perhaps the motivating reason for this. Them being in the same place means that nobody can forget about them anywhere.

File: tests/ui/where-clauses/cfg-attr-issue-138010-2.rs [hunk 3]
```diff
@@ -0,0 +1,35 @@
...
+where
+    (): Sized;
+
+type MixedWhereBounds3
+where
+    //~^ ERROR: where clauses are not allowed before the type for type aliases
+    Foo: Trait,
+= Foo
+where
+    (): Sized;
```
Comment (fmease) [inline tests/ui/where-clauses/cfg-attr-issue-138010-2.rs]:
```suggestion
```

This doesn't contain any attributes, so it's not a reproducer and it's also superfluous because it's already covered by `tests/ui/lazy-type-alias/leading-where-clause.rs`.

File: tests/ui/where-clauses/cfg-attr-issue-138010-1.rs
Comment (fmease) [reply tests/ui/where-clauses/cfg-attr-issue-138010-1.rs:1]: With my comment above I meant removing any of the redundant and distracting bits of `cfg-attr-issue-138010-1.rs` given it's a fuzzer-produced file (extra functions, check-cfg warnings, a useless `let` binding, useless `():` bounds, etc.).

It can be distilled to:

```rs
#![feature(lazy_type_alias)]
#![expect(incomplete_features)]

type Type
where
    #[cfg(false)]
    String: Copy,
= ();

fn main() {}
```

… which just shows that it's just `cfg-attr-issue-138010-2.rs`.

So could you please throw out the `*-1.rs` or replace `*-1.rs` with the MCVE above and remove the `*-2.rs` (I don't really care about the `#[cfg(true)]` case but whatever).

**Review by fmease — APPROVED** [review]

**Comment by fmease** [comment]
Thanks! Some final nits (+ optional squash), then r=me

@bors rollup
