### PR TITLE
When using value after move, point at span of local

### LINKED ISSUE #34721: mismatches types [E0308] doesn't offer enough information to fix the error
I get an error message like this:

``` shell
src/x86/bmi2/mod.rs:51:35: 51:36 error: mismatched types [E0308]
src/x86/bmi2/mod.rs:51         unsafe { intrinsics::bzhi(x, bit_position) }
                                                         ^
src/x86/bmi2/mod.rs:51:35: 51:36 help: run `rustc --explain E0308` to see a detailed explanation
src/x86/bmi2/mod.rs:51:35: 51:36 note: expected type `()`
src/x86/bmi2/mod.rs:51:35: 51:36 note:    found type `T`
```

This tells me "what the error is", but gives me too little context (or no context at all) to actually solve it: I have to go to the `intrinsics` module, find the `bzhi` function, read its signature, and in my case, I end up baffled because it actually takes a `T` (so the `expected type ()` makes no sense). 

I still haven't figured out what is going on, but it would be good if when rustc detects a type error when calling a function, it would not only tell me where the error is, which type i am passing, and what type is expected, but where exactly the function is and what's its complete signature so that if needed I know where to go to read up the comments. Probably the real error here is that I am calling a function with the same name but from a different module, so it might be even better if rustc would check all functions in all modules in scope for functions with the same name and the type signature I am passing it and make a suggestion like "did you meant to call the `bzhi` function from the `bar` module instead?".

In particular the next error is a type error on the second function argument, so it would be even better if rustc could collapse these two errors into one.

---

EDIT: An example of the error is given here:

https://play.rust-lang.org/?gist=841b50e5845c61f2a1ebfd141673c151&version=nightly&backtrace=0

where the following error message is not very helpful:

```shell
error[E0308]: mismatched types
  --> src/main.rs:21:14
   |
21 |     bar::bar(x.zero())
   |              ^^^^^^^^ expected (), found type parameter
   |
   = note: expected type `()`
              found type `T`
   = help: here are some functions which might fulfill your needs:
           - .zero()

```

In particular the ` expected (), found type parameter T` is very misleading.

### PR DESCRIPTION
**Pull request by estebank**
When trying to use a value after move, instead of using a note, point
at the local declaration that has a type that doesn't implement `Copy`
trait.

```
error[E0382]: use of moved value: `x`
  --> $DIR/issue-34721.rs:27:9
   |
LL |     pub fn baz<T: Foo>(x: T) -> T {
   |                -       - move occurs because `x` has type `T`, which does not implement the `Copy` trait
   |                |
   |                consider adding a `Copy` constraint to this type argument
LL |         if 0 == 1 {
LL |             bar::bar(x.zero())
   |                      - value moved here
LL |         } else {
LL |             x.zero()
   |             - value moved here
LL |         };
LL |         x.zero()
   |         ^ value used here after move
```

Fix #34721.

### CODE REVIEW

**Comment by estebank** [comment]
If there's a way to get the current scope's type arguments, we could add an appropriate suggestion (and close the linked ticket):

```
error[E0382]: use of moved value: `x`
  --> src/main.rs:25:3
   |
   | pub fn baz<T: Foo>(x: T) -> T {
   |            ------  - move occurs because `x` has type `T`, which does not implement the `Copy` trait
   |            |
   |            help: consider adding a `Copy` constraint here: `T: Foo + Copy`
   |   if 0 == 1 {
21 |     bar::bar(x.zero())
   |              - value moved here
...
25 |   x.zero()
   |   ^ value used here after move
```

File: src/librustc_mir/borrow_check/error_reporting.rs [hunk 1]
```diff
@@ -198,19 +198,43 @@ impl<'cx, 'gcx, 'tcx> MirBorrowckCtxt<'cx, 'gcx, 'tcx> {
...
                     None => "value".to_owned(),
                 };
-
-                err.note(&format!(
-                    "move occurs because {} has type `{}`, \
-                     which does not implement the `Copy` trait",
-                    note_msg, ty
-                ));
+                let mut note = true;
+                for decl in &self.mir.local_decls {
```
Comment (estebank) [inline src/librustc_mir/borrow_check/error_reporting.rs]: This is not very efficient, but 1) will only happen in case there's an error being emitted (no performance impact in happy path) 2) should be a short `n` to get to the appropriate `decl` and 3) it could be safely be removed while keeping the code at line 220.

If we wanted to modify this, we could introduce a `HashMap` for this, but would be a memory use increase in _all_ cases.

**Comment by estebank** [comment]
@nikomatsakis, you might also be interested in taking a look at this.

File: src/librustc_mir/borrow_check/error_reporting.rs [hunk 2]
```diff
@@ -198,19 +198,43 @@ impl<'cx, 'gcx, 'tcx> MirBorrowckCtxt<'cx, 'gcx, 'tcx> {
...
+                    }
+                }
+                if let ty::TyKind::Param(param_ty) = ty.sty {
+                    let tcx = self.infcx.tcx;
+                    let generics = tcx.generics_of(self.mir_def_id);
+                    let def_id = generics.type_param(&param_ty, tcx).def_id;
+                    if let Some(sp) = tcx.hir().span_if_local(def_id) {
+                        err.span_label(
+                            sp,
+                            "consider adding a `Copy` constraint to this type argument",
```
Comment (nikomatsakis) [inline src/librustc_mir/borrow_check/error_reporting.rs]: did you intend to include the note in this case?

**Review by nikomatsakis — APPROVED** [review]
I think this looks nice

File: src/librustc_mir/borrow_check/error_reporting.rs (hunk 2 above)
Comment (estebank) [reply src/librustc_mir/borrow_check/error_reporting.rs]: @nikomatsakis No, because if the non-`Copy` type is not a type argument then we can't safely suggest adding a type constraint. At best we could suggest giving it a different type or cloning at the use lines (but that could cause logic errors, depending on the code).

Comment (estebank) [reply src/librustc_mir/borrow_check/error_reporting.rs]: Oh, rereading that question, did you mean wether I wanted to show the "move occurs because `x` has type `T`" note/label when suggesting "consider adding a `Copy` constraint"? If so, I did, but it might make sense not to... I would like to keep it just for context, as it teaches that type arguments are not `Copy` by default and also points at the appropriate argument.

Comment (estebank) [reply src/librustc_mir/borrow_check/error_reporting.rs]: I was intrigued, and this is the output if you assign `let y = x` in the case above, which seems reasonable and useful to me:

```
error[E0382]: use of moved value: `y`
  --> file.rs:28:9
   |
21 |     pub fn baz<T: Foo>(x: T) -> T {
   |                - consider adding a `Copy` constraint to this type argument
22 |     let y = x;
   |         - move occurs because `y` has type `T`, which does not implement the `Copy` trait
23 |         if 0 == 1 {
24 |             bar::bar(y.zero())
   |                      - value moved here
25 |         } else {
26 |             y.zero()
   |             - value moved here
27 |         };
28 |         y.zero()
   |         ^ value used here after move
```

File: src/librustc_mir/borrow_check/error_reporting.rs [hunk 3]
```diff
@@ -198,19 +198,43 @@ impl<'cx, 'gcx, 'tcx> MirBorrowckCtxt<'cx, 'gcx, 'tcx> {
...
                 };
-
-                err.note(&format!(
-                    "move occurs because {} has type `{}`, \
-                     which does not implement the `Copy` trait",
-                    note_msg, ty
-                ));
+                let mut note = true;
+                for decl in &self.mir.local_decls {
+                    if decl.ty == ty && decl.name.map(|x| x.to_string()) == opt_name {
```
Comment (nikomatsakis) [inline src/librustc_mir/borrow_check/error_reporting.rs]: I think we can do this much more efficiently. The variable `place` contains the, well, *place* which was moved -- in this case, we are specifically interested in moves from a local variable, right? So we can just do something like:

```rust
if let Place::Local(local) = place {
  let decl = &self.mir.local_decls[local];
}
```

Besides being inefficient, this check is imprecise. If you for example have a shadow of a variable, there could be a bug I think (maybe worth adding a test):

```rust
fn main() {
    let x: Vec<u32> = vec![1, 2, 3];
    drop(x);

    let x: Vec<u32> = vec![1, 2, 3];
    drop(x);
    drop(x);
}
```

I think that will highlight the wrong variable.

**Review by nikomatsakis — CHANGES_REQUESTED** [review]

File: src/librustc_mir/borrow_check/error_reporting.rs (hunk 3 above)
Comment (estebank) [reply src/librustc_mir/borrow_check/error_reporting.rs]: Fixed.

**Comment by nikomatsakis** [comment]
@bors r-

@estebank I never actually r+'d :)

**Review by nikomatsakis — APPROVED** [review]

**Comment by nikomatsakis** [comment]
@bors r+ 

However, it does seem fine. 😛

**Comment by estebank** [comment]
@nikomatsakis I though I had seen green checkmark gated on fixing feedback, but looking now I must have gotten confused with a different PR, sorry about that 😬
