### PR TITLE
rustdoc: Fix source-links for files with absolute-paths

### LINKED ISSUE #26995: 404 for rustdoc [src] links for files with absolute paths
When the path to a source file as known to the compiler is absolute (which can happen with `#[path = "/…"] mod foo;` or `include!`), rustdoc fails to include the source of these files in its output.

For example, the [src] link on http://doc.servo.org/script/dom/bindings/codegen/Bindings/DOMParserBinding/enum.SupportedType.html goes to http://doc.servo.org/src/script///home/servo/buildbot/slave/doc/build/target/debug/build/script-49135cd7c70c0a0f/out/Bindings/DOMParserBinding.rs.html#99-102 which is a 404.

A simpler test case is `hello.rs` in http://doc.crates.io/build-script.html#case-study:-code-generation

### PR DESCRIPTION
**Pull request by mitaa**
fixes #26995

r? @alexcrichton

### CODE REVIEW

File: src/test/run-make/issue-26995/Makefile [hunk 1]
```diff
@@ -0,0 +1,6 @@
+-include ../tools.mk
+
+all:
+	printf "#[path=\"%s/%s\"] pub mod baz;\n" `pwd` "bar/baz.rs" > foo.rs
```
Comment (alexcrichton) [inline src/test/run-make/issue-26995/Makefile]: Perhaps this could be a unix-only rustdoc test which has a module with the path as `/dev/null`? That would avoid run-make and you could still check for the module page, right?

Comment (mitaa) [inline src/test/run-make/issue-26995/Makefile]: Didn't think of that, but it seems like rustdoc doesn't generate files for empty public modules.

That did make another bug clear though, namely that absolute paths not contained in the root directory are still broken just like before.
(I'm gonna try to put these in a `src/__root__` directory; for example `/dev/null` -> `src/__root__/dev/null.html`)

Comment (alexcrichton) [inline src/test/run-make/issue-26995/Makefile]: Hm ok, I just try to avoid run-make like the plague as makefiles are basically impossible to get right on both windows and unix...

**Comment by mitaa** [comment]
I pushed an update so that this also works for absolute paths not contained in the root directory.

That would unfortunately be even worse to test, so I didn't include one.

File: src/librustdoc/html/render.rs [hunk 2]
```diff
@@ -808,7 +808,16 @@ fn clean_srcpath<F>(src_root: &Path, p: &Path, keep_filename: bool, mut f: F) wh
...
+    let p = match p.strip_prefix(src_root) {
+        Ok(p) => p.to_path_buf(),
+        Err(_) => {
+            if p.is_absolute() {
+                Path::new("__root__").join(&p.strip_prefix(Path::new("/")).unwrap())
+            } else {
+                p.to_path_buf()
+            }
+        }
+    };
```
Comment (alexcrichton) [inline src/librustdoc/html/render.rs]: This seems kinda sketchy, perhaps the iterator below could use `components` on `Path` to only look at the `Component::Normal` parts?

**Comment by mitaa** [comment]
(updated)

I've preserved the `Component::ParentDir` -> "up" renaming, so this does not look only at `Component::Normal`. (maybe this can be dropped?)

**Comment by mitaa** [comment]
I think I've made your `/dev/null` suggestion work, removing the run-make test.

This has required commit https://github.com/mitaa/rust/commit/27ca2507defe13c5c989a9aa64d138645a7db65e, because `.is_file()` returns `false` for `/dev/null`.
(the utility of this aside from this test seems questionable, but I hope that's okay..)
(also the same check for extern macros has been used in the same file before[ here][0], when emitting source files)

[0]: https://github.com/rust-lang/rust/blob/81f673d3bc6828acefd548df3f4733f330259c4c/src/librustdoc/html/render.rs#L904-L905
