### PR TITLE
LLVM 15 compatibility fixes

### LINKED ISSUE #99432: rustc `master` has a flaky failure when compiled against LLVM `main`
LLVM commit [ede600377cb6df1bef71f070130d8cfe734cc5b7](https://github.com/llvm/llvm-project/commit/ede600377cb6df1bef71f070130d8cfe734cc5b7) moved some stuff from being `ManagedStatic` to just thread-local static, and it seems we're not correctly blocking on LLVM threads being complete. If I apply this:

```diff
diff --git a/compiler/rustc_driver/src/lib.rs b/compiler/rustc_driver/src/lib.rs
index b71cdad718a..96f34c9ec3b 100644
--- a/compiler/rustc_driver/src/lib.rs
+++ b/compiler/rustc_driver/src/lib.rs
@@ -1336,6 +1336,10 @@ pub fn main() -> ! {
         let end_rss = get_resident_set_size();
         print_time_passes_entry("total", start_time.elapsed(), start_rss, end_rss);
     }
-
-    process::exit(exit_code)
+    if 1 == 200 {
+        process::exit(exit_code)
+    }
+    unsafe {
+    libc::_exit(exit_code)
+    }
 }
```

then I no longer see the failure in 10,000 attempts, which [always looks like this when it happens](https://buildkite.com/llvm-project/rust-llvm-integrate-prototype/builds/11871#0181e78f-2ce6-4ee3-8508-21556f4f7ef4):
```
---- [ui] src/test/ui/cmse-nonsecure/cmse-nonsecure-call/params-on-stack.rs stdout ----
 
error: Error: expected failure status (Some(1)) but received status Some(101).
status: exit status: 101
command: "/var/lib/buildkite-agent/builds/rust-llvm-integrate/llvm-project/rust-llvm-integrate-prototype/build/x86_64-unknown-linux-gnu/stage1/bin/rustc" "/var/lib/buildkite-agent/builds/rust-llvm-integrate/llvm-project/rust-llvm-integrate-prototype/src/test/ui/cmse-nonsecure/cmse-nonsecure-call/params-on-stack.rs" "-Zthreads=1" "--error-format" "json" "--json" "future-incompat" "-Ccodegen-units=1" "-Zui-testing" "-Zdeduplicate-diagnostics=no" "-Cstrip=debuginfo" "-C" "prefer-dynamic" "--out-dir" "/var/lib/buildkite-agent/builds/rust-llvm-integrate/llvm-project/rust-llvm-integrate-prototype/build/x86_64-unknown-linux-gnu/test/ui/cmse-nonsecure/cmse-nonsecure-call/params-on-stack" "-A" "unused" "-Crpath" "-Cdebuginfo=0" "-Lnative=/var/lib/buildkite-agent/builds/rust-llvm-integrate/llvm-project/rust-llvm-integrate-prototype/build/x86_64-unknown-linux-gnu/native/rust-test-helpers" "-Clinker=/usr/bin/clang-13" "--target" "thumbv8m.main-none-eabi" "--crate-type" "lib" "-L" "/var/lib/buildkite-agent/builds/rust-llvm-integrate/llvm-project/rust-llvm-integrate-prototype/build/x86_64-unknown-linux-gnu/test/ui/cmse-nonsecure/cmse-nonsecure-call/params-on-stack/auxiliary"
stdout: none
--- stderr -------------------------------
error: <unknown>:0:0: in function test i32 (i32, i32, i32, i32, i32): call to non-secure function would require passing arguments on stack
 
error: aborting due to previous error
 
LLVM ERROR: Do not know how to split the result of this operator!
------------------------------------------
 
 
 
failures:
[ui] src/test/ui/cmse-nonsecure/cmse-nonsecure-call/params-on-stack.rs
```

On our CI VM (which is fairly small) this appears to happen roughly a third or half the time. On my workstation it's less than 1% of the time, best guess about 0.3% of the time, so 10k runs is necessary to reliably see the issue.

I'll hopefully have time to fix this in the near future, but wanted to record this ASAP so we don't forget when the LLVM upgrade is due.

### PR DESCRIPTION
**Pull request by nikic**
These are LLVM 15 compatibility fixes split out from #99464. There are three changes here:

 * Emit elementtype attribtue for ldrex/strex intrinsics. This is requires as part of the opaque pointers migration.
 * Make more tests compatible with opaque pointers. These are either new or aren't run on x86.
 * Remove a test for `#[rustc_allocator]`. Since #99574 there are more requirement on the function signature. I dropped the test entirely, since we already test the effect of the attribute elsewhere.
 * The main change: When a worker thread emits an error, wait for other threads to finish before unwinding the main thread and exiting. Otherwise workers may end up using globals for which destructors have already been run. This was probably never quite correct, but became an active problem with LLVM 15, because it started using global dtors in critical places, as part of ManagedStatic removal.

Fixes #99432 (and probably also #95679).

r? @cuviper

### CODE REVIEW

File: compiler/rustc_codegen_ssa/src/back/write.rs [hunk 1]
```diff
@@ -1412,16 +1413,45 @@ fn start_executing_work<B: ExtraBackendMethods>(
             // re-acquire a token to continue running more work. We may also not
             // actually drop a token here if the worker was running with an
             // "ephemeral token"
-            let mut free_worker = |worker_id| {
-                if main_thread_worker_state == MainThreadWorkerState::LLVMing {
-                    main_thread_worker_state = MainThreadWorkerState::Idle;
+            let free_worker = |worker_id,
+                               running: &mut _,
+                               main_thread_worker_state: &mut _,
+                               free_worker_ids: &mut Vec<_>| {
```
Comment (nikic) [inline compiler/rustc_codegen_ssa/src/back/write.rs:1419]: This awkward change is because we can't have two closures over the same mutable state, even if they won't be used at the same time :(

**Comment by nikic** [comment]
I ended up completely rewriting the fix for the global dtor issue. The new implementation drops the AbortCodegenOnDrop wrapper, and instead integrates the functionality into OngoingCodegen (or rather a separate Coordinator struct, to limit drop scope). This ensures that all panics during codegen will result in a CodegenAborted message + thread join. Previously, panics generated as part of join_codegen() were not handled, which is really the root issue here. Similarly, WorkerFatalError handling is switched to do the same thing as CodegenAborted.

I think this makes for a nicer and more consistent solution. The main casualty are various asserts that no longer hold, as codegen can now be aborted at more different points.

**Comment by cuviper** [comment]
LGTM! I'm blocking rollup to be careful about the thread change, although I don't know if CI hits such errors anyway.

@bors r+ rollup=never
