### PR TITLE
Make compressed rmeta contain compressed data length after header

### LINKED ISSUE #90056: -Clink-dead-code causes `extern crate failure_derive` to not be found on Windows
_For context, this issue comes up when trying to collect code coverage metrics for projects that depend on certain crates. It was previously reported about a year ago here https://github.com/intellij-rust/intellij-rust/issues/6325 and here https://github.com/mozilla/grcov/issues/502, but the root issue is in `rustc`. What follows is a minimal reproduction._

For some reason a crate that depends on `failure` fails to compile when `-Clink-dead-code` is set, but only on Windows. It works fine when `RUSTFLAGS` is empty, or on Linux.

To reproduce, run the following commands in Powershell on Windows, in an empty folder:

```ps1
cargo init
echo 'failure="0.1.8"' >> Cargo.toml
$env:RUSTFLAGS="-Clink-dead-code"
cargo build
```

The error printed is:

```
error[E0463]: can't find crate for `failure_derive`
  --> C:\Users\Karel\.cargo\registry\src\github.com-1ecc6299db9ec823\failure-0.1.8\src\lib.rs:56:1
   |
56 | extern crate failure_derive;
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ can't find crate

For more information about this error, try `rustc --explain E0463`.
```

Running `cargo clean` followed by `cargo build -vv` has this output: https://gist.githubusercontent.com/KarelPeeters/e5436e18e618dc23a55b9e77ed3c9279/raw/1f4bc3bc76a8e4e52175138a01ee51a1046c4387/gistfile1.txt

This doesn't happen for most crates, I have about 20 dependencies and this issue only comes up with `failure`/`failure_derive` for me. In the first issue someone else had the same problem with `const_fn = "0.4.2"`, but I cannot reproduce that.

I tried my own issue on today's stable `rustc 1.55.0 (c8dfcfe04 2021-09-06)` and nightly `rustc 1.58.0-nightly (bd41e09da 2021-10-18)` and both Windows and Linux, and this happens for both versions on Windows and for neither version on Linux.

### PR DESCRIPTION
**Pull request by CraftSpider**
Fixes #90056, which is caused by link.exe introducing padding to the `.rustc` section, since it assumes this will have no effect besides allowing it to possibly use the extra space in future links.

### CODE REVIEW

**Comment by fee1-dead** [comment]
r? rust-lang/rust

**Comment by fee1-dead** [comment]
r? rust-lang/compiler

**Comment by CraftSpider** [comment]
It may be possible to do that, but I'm not sure it's the best path forwards - I imagine it would effectively be removing some sanity checks on the length of the compressed data, and instead just decompressing the first N bytes. This is only a guess though, as I'm not actually incredibly familiar with how rustc does its compressed metadata writing.

**Comment by CraftSpider** [comment]
I also feel I should note that, as far as I'm aware, either only the Windows linker does this, or we already tell other linkers not to. I wouldn't consider this change to be working against linker expectations in general, just disabling a slightly odd behavior on Windows (I wouldn't think adding extra null bytes to unrecognized sections is, in general, a safe thing to do)

**Comment by bjorn3** [comment]
Maybe only disable it for the dylib and proc-macro crate types? bin and cdylib don't have crate metadata.

**Comment by bjorn3** [comment]
On the other hand there are crates which use custom sections that will likely break with padding too. For example inventory.

**Comment by ehuss** [comment]
I am almost certainly not the right person to review this. I do not know what the implications are of disabling incremental linking.  Is there anyone on the compiler team familiar with linking (`link.exe` especifically) and rust's metadata?

I also wonder if a better solution would be to track the length of the compressed data instead of assuming the section data length is correct?  The `METADATA_HEADER` already lives outside of the compressed stream. It could be extended to include the metadata length (it already has a position offset which gets filled in after encoding).

It also seems a little surprising that the linker is padding a section. I wonder if it is related to this:

> The size of this data in the file is indicated by the SizeOfRawData field. If SizeOfRawData is less than VirtualSize, the remainder is padded with zeros.

Perhaps they always feel at liberty to pad things?

**Comment by bjorn3** [comment]
>  The METADATA_HEADER already lives outside of the compressed stream. It could be extended to include the metadata length (it already has a position offset which gets filled in after encoding).

Only the literal represented by `METADATA_HEADER` (`rust\0x00\0x00\0x00\0x06`) has a copy outside of the compressed stream. No other part of the header is outside of the compressed stream. That includes the crate root offset and the rustc version. Both are inside the compressed stream after another copy of `METADATA_HEADER`.

https://github.com/rust-lang/rust/blob/addacb5878b9970ebc1665768a05cb601e7aea15/compiler/rustc_codegen_ssa/src/back/metadata.rs#L281-L282

```
Hex dump of section '.rustc':
  0x00000000 72757374 00000006 ff060000 734e6150 rust........sNaP
  0x00000010 7059000d 9f00e4dc e1798080 04307275 pY.......y...0ru
```

**Comment by ehuss** [comment]
Ah, I misread that about the position. But I assume those lines could be changed to something like:

```rust
let mut compressed = rustc_metadata::METADATA_HEADER.to_vec(); 
compressed.write_all(length).unwrap();
FrameEncoder::new(&mut compressed).write_all(metadata.raw_data()).unwrap(); 
```

where `length` is the length of `metadata.raw_data()` encoded in some format (like a 32-bit big endian or something)?

**Comment by bjorn3** [comment]
That should work. Rust-analyzer will need to be updated to reflect this in the proc macro loading code though.

**Comment by CraftSpider** [comment]
I'll work on making the necessary changes, since it seems like consensus is that supporting this is worth the change. Should I make a PR to rust-analyzer in sync with this change?

**Comment by bjorn3** [comment]
Rust-analyzer is now a subtree, so you could make the changes in the same PR to this repo. Make sure to keep support for the current format though.

**Comment by apiraino** [comment]
By reading the latest comments it seems this PR will be waiting on work happening on rust-analyzer. I'll signal this with `s-waiting-on-author` - feel free to request a review of his PR again with `@rustbot ready`, thanks!

@rustbot author

**Comment by eddyb** [comment]
> Ah, I misread that about the position. But I assume those lines could be changed to something like:
> 
> ```rust
> let mut compressed = rustc_metadata::METADATA_HEADER.to_vec(); 
> compressed.write_all(length).unwrap();
> FrameEncoder::new(&mut compressed).write_all(metadata.raw_data()).unwrap(); 
> ```
> 
> where `length` is the length of `metadata.raw_data()` encoded in some format (like a 32-bit big endian or something)?

@ehuss @CraftSpider If you do this change, don't forget to bump the (small) version number in `METADATA_HEADER`, otherwise the two encodings will get confused for one another (i.e. we try to guarantee that mixing versions of `rustc`, say stable and nightly, in the same build dir, will not cause unpredictable failure modes due to format mixing - that's why we have a "major" format version in `METADATA_HEADER` on top of the "`rustc` version" string later on, because the version string couldn't be correctly found if we change fundamental aspects of the encoding).

**Comment by CraftSpider** [comment]
I'll make sure to do so, I did start on implementing this change. I'll push an update once I have something working hopefully.

**Comment by Dylan-DPC** [comment]
@craftspider any updates on this?

**Comment by CraftSpider** [comment]
Sorry for the delay - I started working on this, then got distracted by other projects. I'm going to try to actually implement the metadata changes within the next couple days, or close the PR as beyond my familiarity with the compiler.

**Comment by wesleywiser** [comment]
No problem @CraftSpider, thanks for the update! 🙂

File: compiler/rustc_metadata/src/locator.rs [hunk 1]
```diff
@@ -798,8 +798,15 @@ fn get_metadata_section<'p>(
...
+            // Length of the compressed stream - this allows linkers to pad the section if they want
+            let usize_len = core::mem::size_of::<u32>();
+            let Ok(len_bytes) = <[u8; 4]>::try_from(&buf[header_len..cmp::min(header_len + usize_len, buf.len())]) else {
+                return Err(MetadataError::LoadFailure("invalid metadata length found".to_string()));
+            };
+            let compressed_len = u32::from_be_bytes(len_bytes) as usize;
+
             // Header is okay -> inflate the actual metadata
-            let compressed_bytes = &buf[header_len..];
+            let compressed_bytes = &buf[header_len..compressed_len + header_len];
```
Comment (bjorn3) [inline compiler/rustc_metadata/src/locator.rs:809]:
```suggestion
            let compressed_bytes = &buf[header_len..header_len + compressed_len];
```
I think this is a bit clearer.

Comment (bjorn3) [reply compiler/rustc_metadata/src/locator.rs:809]: By the way this needs to add another 4 bytes on both sides of the range to cover the length field.

**Comment by CraftSpider** [comment]
Assuming tests pass, I'll drop the initial commit from history

**Comment by lnicola** [comment]
@CraftSpider while we do sync the changes here back upstream, it's not as often or as easy as we'd like to. So feel free to also submit this to our side so RA doesn't break when using nightlies.

File: src/tools/rust-analyzer/crates/proc-macro-api/src/version.rs [hunk 2]
```diff
@@ -120,17 +120,20 @@ pub fn read_version(dylib_path: &AbsPath) -> io::Result<String> {
...
     // https://github.com/rust-lang/rust/commit/0696e79f2740ad89309269b460579e548a5cd632
-    match version {
-        5 | 6 => {}
+    let snappy_portion = match version {
+        5 | 6 => &dot_rustc[8..],
+        7 => {
+            let len_bytes = &dot_rustc[8..12];
+            let data_len = u32::from_be_bytes(len_bytes.try_into().unwrap()) as usize;
+            &dot_rustc[12..data_len + 12]
+        },
```
Comment (lnicola) [inline src/tools/rust-analyzer/crates/proc-macro-api/src/version.rs:129]: Does `rustc` use a nightly `rustfmt`? As tiny as this is, I feel this is going to cause us a lot of pain (cf https://github.com/rust-lang/rust-analyzer/pull/14153).

Comment (bjorn3) [reply src/tools/rust-analyzer/crates/proc-macro-api/src/version.rs:129]: Yes, rustc uses a nightly rustfmt. Rust-analyzer shouldn't be formatted though: https://github.com/rust-lang/rust/blob/9bb6e60d1f1360234aae90c97964c0fa5524f141/rustfmt.toml#L35

Comment (lnicola) [reply src/tools/rust-analyzer/crates/proc-macro-api/src/version.rs:129]:
```suggestion
        }
```

Comment (Veykril) [reply src/tools/rust-analyzer/crates/proc-macro-api/src/version.rs:129]: Note that r-a will happily format this since rustfmt doesn't know about file paths when invoked by r-a currently

Comment (CraftSpider) [reply src/tools/rust-analyzer/crates/proc-macro-api/src/version.rs:129]: I can remove the comma here to hopefully sidestep conflicts, if desired. Or rebase, or try to pull the commits I made to r-a in here? I'm not super familiar with git subtrees like this.

Comment (lnicola) [reply src/tools/rust-analyzer/crates/proc-macro-api/src/version.rs:129]: > Note that r-a will happily format this since rustfmt doesn't know about file paths when invoked by r-a currently

Great, another reason for me to be anxious on subtree syncs 😵‍💫.

I think you can drop it here in a new commit (and optionally squash them).

File: compiler/rustc_metadata/src/rmeta/mod.rs [hunk 3]
```diff
@@ -55,7 +55,7 @@ pub(crate) fn rustc_version() -> String {
 /// Metadata encoding version.
 /// N.B., increment this if you change the format of metadata such that
 /// the rustc version can't be found to compare with `rustc_version()`.
-const METADATA_VERSION: u8 = 6;
+const METADATA_VERSION: u8 = 7;
```
Comment (wesleywiser) [inline compiler/rustc_metadata/src/rmeta/mod.rs:58]: Nit: The comment on line 64 should be updated to mention the metadata length.

**Review by wesleywiser — APPROVED** [review]
Compiler changes look good to me!

**Comment by wesleywiser** [comment]
@Veykril or @lnicola, would you mind double checking that the r-a changes are ok? Thanks! 🙂

**Comment by lnicola** [comment]
The rust-analyzer changes were merged in https://github.com/rust-lang/rust-analyzer/pull/14153, but we'll double-check once this hits nightly.

**Review by wesleywiser — APPROVED** [review]

**Comment by wesleywiser** [comment]
Thanks @CraftSpider! 

@bors r+
