### PR TITLE
rust-lld: fallback to rustc's sysroot if there's no path to the linker in the target sysroot

### LINKED ISSUE #125246: rustc can't find the linker when `--sysroot` is set to a local build of the sysroot
This is a recent regression, starting with https://github.com/rust-lang/rust/pull/124129: when `--sysroot` is set, in my case to `/home/r/.cache/cargo-careful` where I have prepared a locally built sysroot (that's https://github.com/RalfJung/cargo-careful), then rustc now assumes it can find the linker in the sysroot, which does not work. See https://github.com/RalfJung/cargo-careful/issues/31 for some more details.

It is new to me that the sysroot is supposed to contain the linker as well, is that expected behavior?

Also the error message in that case is really unhelpful.^^
```
  = note: collect2: fatal error: cannot find 'ld'
          compilation terminated.
```
Maybe rustc should check that the path it sets for `-B` actually exists before starting `cc`?

### PR DESCRIPTION
**Pull request by lqd**
As seen in #125246, some sysroots don't expect to contain `rust-lld` and want to keep it that way, so we fallback to the default rustc sysroot if there is no path to the linker in any of the sysroot tools search paths. This is how we locate codegen-backends' dylibs already.

People also have requested an error if none of these search paths contain the self-contained linker directory, so there's also an error in that case.

r? @petrochenkov cc @ehuss @RalfJung 

I'm not sure where we check for `rust-lld`'s existence on the targets where we use it by default, and if we just ignore it when missing or emit a warning (as I assume we don't emit an error), so I just checked for the existence of `gcc-ld`, where `cc` will look for the lld-wrapper binaries.

<sub>*Feel free to point out better ways to do this, it's the middle of the night here.*</sub>

Fixes #125246

### CODE REVIEW

**Comment by bjorn3** [comment]
For the codegen backends we search in the sysroot containing rustc itself in addition to the sysroot specified using `--sysroot`.

**Comment by lqd** [comment]
> For the codegen backends we search in the sysroot containing rustc itself in addition to the sysroot specified using `--sysroot`.

Is that an FYI, or what you are asking me to do?

**Comment by bjorn3** [comment]
I feel like doing the same sysroot fallback method here would be nicer than falling back to the default linker, but if you prefer falling back to the default linker that is fine by me too.

**Comment by Kobzol** [comment]
I would personally prefer erroring out if `lld` was not found, rather than silently dropping back to the default linker. If the target uses `lld` by default, and it is not available, it should be an error, and the user should use the corresponding linker features flag to explicitly opt out of `lld`.

**Comment by RalfJung** [comment]
So like this?
- first search `--sysroot`
- then search the rustc location
- then error

**Comment by lqd** [comment]
I agree an error would be preferable if we were talking about an opt-in flag; for a change of default values with an opt-out, however, it probably would be less desirable than a fallback to "things work like they used to when they can't work like we now want them too": an unwanted error from `cc` is what happened to Ralf and Eric, and it seems unlikely that just having a different error message would have made it acceptable.

**Comment by Kobzol** [comment]
Defaults might eventually change, and this is hardly the last one, e.g. I can imagine us switching to Cranelift in the future by default for debug builds, and in such case it will also start being required in the toolchain.

I don't like silent fallbacks, because they can make it more difficult to debug issues ("wait, how are you hitting this issue..? oh, your rustc silently fell back to a completely different linker/codegen backend/etc.").

Of course, we should make sure that the default case works for the *default* toolchain, but if someone does something custom, then it might be needed for them to e.g. configure the compilation of `rustc` to add the required stuff to the toolchain, or opt out of this functionality.

**Comment by RalfJung** [comment]
> an unwanted error from cc is what happened to Ralf and Eric, and it seems unlikely that just having a different error message would have made it acceptable.

The proposed search order would fix the error for my case, and I think also for Erik's case.

**Comment by lqd** [comment]
> > an unwanted error from cc is what happened to Ralf and Eric, and it seems unlikely that just having a different error message would have made it acceptable.
> 
> The proposed search order would fix the error for my case, and I think also for Erik's case.

Right, because *in this case* we can mitigate the error. Asking for an error, for rust-lld now or cg-clif in the future, in the general case would have applied here if we weren't able to do the mitigation, getting us back to square 1. There are too many trade-offs and unknowns for us to completely figure this out a random PR ^^.

**Comment by bjorn3** [comment]
> I can imagine us switching to Cranelift in the future by default for debug builds, and in such case it will also start being required in the toolchain.

That already works fine with custom sysroots as we fallback to the default sysroot of rustc for locating codegen backends if the custom sysroot doesn't have the specified codegen backend.

**Comment by lqd** [comment]
@RalfJung I was editing https://github.com/rust-lang/rust/pull/125263#issuecomment-2123240400 while you were reading it I think. I was adding my results with cargo-careful 0.4.1 that I'm not sure you saw?

**Comment by RalfJung** [comment]
Yes that looks right, the crate is deliberately buggy and the bug is detected by the debug assertions.

**Comment by lqd** [comment]
Cool, thank you.

File: compiler/rustc_codegen_ssa/src/back/link.rs [hunk 1]
```diff
@@ -3116,12 +3116,31 @@ fn add_lld_args(
...
-                arg
-            });
+        // We tell `cc` where to find the lld wrappers, in a similar way to how we locate
+        // codegen-backends dylibs:
+        // - in the tool search paths: the sysroot's `rustlib` bin path,
+        // - and as a fallback for cases where `--sysroot` only contains a target std: in the
+        //   default host sysroot where rustc is currently located.
+        let fallback_sysroot_paths = filesearch::sysroot_candidates()
+            .into_iter()
+            .map(|sysroot| filesearch::make_target_bin_path(&sysroot, config::host_triple()));
```
Comment (petrochenkov) [inline compiler/rustc_codegen_ssa/src/back/link.rs:3126]: Maybe this logic should go directly into `get_tools_search_paths`?

File: compiler/rustc_codegen_ssa/src/back/link.rs [hunk 2]
```diff
@@ -3116,12 +3116,31 @@ fn add_lld_args(
...
+                    let mut arg = OsString::from("-B");
+                    arg.push(linker_path);
+                    arg
+                });
+            }
+        }
+        if !linker_path_exists {
+            // As a sanity check, we emit an error if none of these paths exist: we want
+            // self-contained linking and have no linker.
+            sess.dcx().emit_fatal(errors::SelfContainedLinkerMissing);
```
Comment (petrochenkov) [inline compiler/rustc_codegen_ssa/src/back/link.rs:3143]: What if a distro wants to drop Rust lld binaries and rely on system lld?

Then the corresponding `self-contained` directories either won't exist or will be empty.
If we just push the `-B` options without checking then gcc will go through them and then proceed searching and finding lld on the system without errors.

If we report an error here, then such distros will also need to reset self-contained flags in target specs to false, probably through env vars like the current `CFG_USE_SELF_CONTAINED_LINKER`.
This will have a negative effect on portability of options like `-Clink-self-contained=+linker` between distros (if we need such portability).

Comment (petrochenkov) [reply compiler/rustc_codegen_ssa/src/back/link.rs:3143]: But I'm fine with reporting a conservative error here for now, it can always be relaxed later.
At least we'll be able see what breaks.

Comment (lqd) [reply compiler/rustc_codegen_ssa/src/back/link.rs:3143]: Another reason why I preferred the fallback compared to the error :3, because falling back to system lld is what we currently do in the case you mention of course.

But one can also say having the self-contained linker enabled is an opt-in for the toolchain maker, it goes hand in hand with bootstrap building lld and putting in the sysroot. Not having both can be seen as a mismatch, and that situation would be properly modeled as `-Clink-self-contained=-linker -Clinker-features=+lld`.

Comment (lqd) [reply compiler/rustc_codegen_ssa/src/back/link.rs:3143]: Note that I only check for the existence of the `gcc-ld` folder, so in theory an empty directory with no lld binaries would pass this test 🤡

File: compiler/rustc_codegen_ssa/src/back/link.rs (hunk 1 above)
Comment (lqd) [reply compiler/rustc_codegen_ssa/src/back/link.rs:3126]: I debated that as well, but didn't know if we wanted such a fallback in all cases, but it could be useful for other host tools and `--sysroot`. 

I'll move it there.

File: compiler/rustc_codegen_ssa/src/back/link.rs (hunk 2 above)
Comment (RalfJung) [reply compiler/rustc_codegen_ssa/src/back/link.rs:3143]: One problem with the fallback is that if there is no system lld and we try to use it anyway, the error is *really bad*:
```
  = note: collect2: fatal error: cannot find 'ld'
          compilation terminated.
```
It doesn't even say that it was trying to find `lld`, mentioning `ld` instead which is not what it was looking for.

Comment (RalfJung) [reply compiler/rustc_codegen_ssa/src/back/link.rs:3143]: > What if a distro wants to drop Rust lld binaries and rely on system lld?

Sounds to me like they should then disable self-contained linking in their rustc builds.

Comment (lqd) [reply compiler/rustc_codegen_ssa/src/back/link.rs:3143]: It's definitely not going to be an oscar of the best error message, but also it's in gcc, people are used to it, and look for the `-fuse-ld` option that is in the command just above that note.

File: compiler/rustc_codegen_ssa/src/back/link.rs (hunk 1 above)
Comment (lqd) [reply compiler/rustc_codegen_ssa/src/back/link.rs]: Done. The fallback search paths will also added to the msvc paths, I guess that's fine. 

@rustbot ready

File: compiler/rustc_codegen_ssa/src/back/link.rs (hunk 2 above)
Comment (RalfJung) [reply compiler/rustc_codegen_ssa/src/back/link.rs:3139]: > a non-zero number of people are used to it, and look for the -fuse-ld option that is in the command just above that note. (Maybe it also depends on the gcc version and newer ones have improved it 🤔)

I dare say most Rust users are not used to it. I certainly was entirely flabbergasted, and I know more than the average Rust programmer about how the compiler works. If an error is too obscure for me I think we can safely assume that it is useless-or-worse for the majority of our users.

That should obviously be reported against gcc, I just didn't have the time for that. But in general we try to work around weaknesses of other tools we employ when we are aware of them.

But as you say indeed for this PR this isn't relevant. I was just replying to @petrochenkov's arguments.

File: compiler/rustc_codegen_ssa/src/back/link.rs [hunk 3]
```diff
@@ -3116,12 +3116,27 @@ fn add_lld_args(
 
     let self_contained_linker = self_contained_cli || self_contained_target;
     if self_contained_linker && !sess.opts.cg.link_self_contained.is_linker_disabled() {
+        // We tell `cc` where to find the lld wrappers, in a similar way to how we locate
+        // codegen-backends dylibs, in the tools search paths, which contain:
+        // - the sysroot's `rustlib` bin path,
+        // - and as a fallback for cases using `--sysroot` without tools: in the default host
+        //   sysroot where rustc is currently located.
```
Comment (petrochenkov) [inline compiler/rustc_codegen_ssa/src/back/link.rs:3123]: These comments are outdated now (or at least misplaced).

File: compiler/rustc_codegen_ssa/src/back/link.rs [hunk 4]
```diff
@@ -3116,12 +3116,27 @@ fn add_lld_args(
...
-                let mut arg = OsString::from("-B");
-                arg.push(path.join("gcc-ld"));
-                arg
-            });
+            let linker_path = path.join("gcc-ld");
+            if linker_path.exists() {
+                linker_path_exists = true;
+                cmd.arg({
+                    let mut arg = OsString::from("-B");
+                    arg.push(linker_path);
```
Comment (petrochenkov) [inline compiler/rustc_codegen_ssa/src/back/link.rs:3131]: Nit: the push can be done unconditionally, then the logic will be simplified to `linker_path_exists &= linker_path.exists()`.

File: compiler/rustc_session/src/session.rs [hunk 5]
```diff
@@ -449,15 +449,29 @@ impl Session {
...
-        if self_contained { vec![p.clone(), p.join("self-contained")] } else { vec![p] }
+
+        let fallback_sysroot_paths = filesearch::sysroot_candidates()
+            .into_iter()
+            .map(|sysroot| filesearch::make_target_bin_path(&sysroot, config::host_triple()));
+
+        if self_contained {
+            [p.clone(), p.join("self-contained")]
+                .into_iter()
+                .chain(fallback_sysroot_paths)
```
Comment (petrochenkov) [inline compiler/rustc_session/src/session.rs:470]: Hmm, I think the `self-contained` subdirectory should be added to all higher-level directories, including those from the fallback sysroot.

File: compiler/rustc_codegen_ssa/src/back/link.rs (hunk 3 above)
Comment (lqd) [reply compiler/rustc_codegen_ssa/src/back/link.rs:3123]: They're just a summary of what happens, they're also in `get_tools_search_paths`. I guess I can remove them.

File: compiler/rustc_session/src/session.rs (hunk 5 above)
Comment (lqd) [reply compiler/rustc_session/src/session.rs:470]: There probably won't be any tools in these folders now, but at least it'll work when we move everything there.

Comment (lqd) [reply compiler/rustc_session/src/session.rs]: Done. I also used the new helper as a slight cleanup I had forgotten to do.

File: compiler/rustc_codegen_ssa/src/back/link.rs (hunk 4 above)
Comment (lqd) [reply compiler/rustc_codegen_ssa/src/back/link.rs]: Done

File: compiler/rustc_codegen_ssa/src/back/link.rs (hunk 3 above)
Comment (lqd) [reply compiler/rustc_codegen_ssa/src/back/link.rs]: Done
