### PR TITLE
Make `TooGeneric` error in WF checking a proper error

### LINKED ISSUE #66962: Const generic ICE: constant in type had an ignored error: TooGeneric
Environment:
```
note: rustc 1.41.0-nightly (4007d4ef2 2019-12-01) running on x86_64-unknown-linux-gnu
note: compiler flags: -C codegen-units=1 -C debuginfo=2 --crate-type bin
```

The code:
```
#![feature(const_generics)]

#[derive(PartialEq, Eq)]
struct Config {
    arr_size: usize
}

struct B<const CFG: Config> {
    arr: [u8; {CFG.arr_size}]
}

fn main() {
}
```
gives ICE:
```
error: internal compiler error: constant in type had an ignored error: TooGeneric
```

[Playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=65de0456c6982ba362efa1fbc8b0446b)

### PR DESCRIPTION
**Pull request by varkor**
`TooGeneric` is encountered during WF checking when we cannot determine that a constant involving a generic parameter will always be evaluated successfully (rather than resulting in an error). In these cases, the burden of proof should be with the caller, so that we can avoid post-monomorphisation time errors (which was the previous previous behaviour). This commit ensures that this situation produces a proper compiler error, rather than silently ignoring it or ICEing.

Fixes https://github.com/rust-lang/rust/issues/66962.

r? @eddyb

### CODE REVIEW

File: src/librustc/traits/error_reporting/mod.rs [hunk 1]
```diff
@@ -917,14 +917,27 @@ impl<'a, 'tcx> InferCtxt<'a, 'tcx> {
...
+                    self.tcx.sess.delay_span_bug(
+                        span,
+                        &format!("constant in type had an ignored error: {:?}", err),
+                    );
                 }
-                self.tcx.sess.delay_span_bug(
-                    span,
-                    &format!("constant in type had an ignored error: {:?}", err),
-                );
                 return;
```
Comment (eddyb) [inline src/librustc/traits/error_reporting/mod.rs]: Please turn this into an exhaustive match, because then it would make sense (since the other variant explicitly indicates an error has already been reported).

File: src/librustc/traits/error_reporting/mod.rs [hunk 2]
```diff
@@ -917,14 +917,27 @@ impl<'a, 'tcx> InferCtxt<'a, 'tcx> {
...
-                    return;
+                    // In this instance, we have a const expression containing an unevaluated
+                    // generic parameter. We have no idea whether this expression is valid or
+                    // not (e.g. it might result in an error), but we don't want to just assume
+                    // that it's okay, because that might result in post-monomorphisation time
+                    // errors. The onus is really on the caller to provide values that it can
+                    // prove are well-formed.
+                    let mut err = self.tcx.sess.struct_span_err(
+                        span,
+                        "cannot determine that constant is always well-formed",
```
Comment (eddyb) [inline src/librustc/traits/error_reporting/mod.rs]: We probably shouldn't talk about WF in diagnostics.

The way I was initially approaching this (see variant names, like `ConstEvaluatable` in `Predicate` and `ConstEvalFailure` here) would suggest something more like:
> constant expression depends on generic parameters

followed by explaining that it may fail to evaluate depending on the choice of generics.

Comment (eddyb) [reply src/librustc/traits/error_reporting/mod.rs]: Oh and you can bypass the problem of explaining to the user how to make it work, by linking to a `rust-lang/rust` issue (ideally a new one without any preexisting discussion) titled something like "Constant expressions using generic params require weird `where` clauses." with a "canonical" example.

Note that the "canonical" example doesn't work yet, because `ConstEvaluatable` requirements from bounds aren't implied in the body (maybe they need to be added to `ParamEnv`, and then looked up in there?).

I'm not even sure we can (ab)use the `where TyAlias<T, {N}>:,` pattern like that, usually WF semantics would require that the definition that `where` is attached to proves the WF, instead of deferring that to users of that definition.
I would want a @rust-lang/wg-traits confirmation that we want to implement that behavior (as it's not limited to const generics, it applies to any constant expressions using generic parameters, e.g. `[u8; size_of::<T>()]`, so it might impact stable).

File: src/librustc/traits/error_reporting/mod.rs [hunk 3]
```diff
@@ -914,17 +914,29 @@ impl<'a, 'tcx> InferCtxt<'a, 'tcx> {
...
+                // that it's okay, because that might result in post-monomorphisation time
+                // errors. The onus is really on the caller to provide values that it can
+                // prove are well-formed.
+                let mut err = self
+                    .tcx
+                    .sess
+                    .struct_span_err(span, "constant expression depends on a generic parameter");
+                // FIXME(const_generics): this is not always possible at the moment.
+                // When it is, we should give more specific suggestions, like exactly
+                // what sort of bound needs to be added.
```
Comment (eddyb) [inline src/librustc/traits/error_reporting/mod.rs]: This comment seems to be meant for a `help` message that's not added anymore?

Comment (varkor) [reply src/librustc/traits/error_reporting/mod.rs]: I made the comment a little more relevant.

**Review by eddyb — APPROVED** [review]
I don't like leaving this an error with no workaround, but I think it's better to properly decide how to approach it.
