### PR TITLE
Use more specific panic message for &str slicing errors

### LINKED ISSUE #38052: Awkward wording of char slicing error message
```rust
fn slice_not_on_char_boundaries() {
    let s = "Здравствуйте";
    &s[0..1];
}
```

gives

```text
thread 'main' panicked at 'index 0 and/or 3 in `Здравствуйте` do not lie on character boundary'
```

To me, "index do not lie" feels weird, should be "does not lie".

### PR DESCRIPTION
**Pull request by bluss**
Separate out of bounds errors from character boundary errors, and print
more details for character boundary errors.

It reports the first error it finds in:

1. begin out of bounds
2. end out of bounds
3. begin <= end violated
3. begin not char boundary
5. end not char boundary.

Example:

    &"abcαβγ"[..4]

    thread 'str::test_slice_fail_boundary_1' panicked at 'byte index 4 is not
    a char boundary; it is inside 'α' (bytes 3..5) of `abcαβγ`'

Fixes #38052

### CODE REVIEW

**Comment by durka** [comment]
Should we show all the problems instead of just the first one?

File: src/libcore/str/mod.rs [hunk 1]
```diff
@@ -1741,13 +1741,29 @@ fn truncate_to_char_boundary(s: &str, mut max: usize) -> (bool, &str) {
 #[cold]
 fn slice_error_fail(s: &str, begin: usize, end: usize) -> ! {
     const MAX_DISPLAY_LENGTH: usize = 256;
-    let (truncated, s) = truncate_to_char_boundary(s, MAX_DISPLAY_LENGTH);
+    let (truncated, s_trunc) = truncate_to_char_boundary(s, MAX_DISPLAY_LENGTH);
     let ellipsis = if truncated { "[...]" } else { "" };
 
+    // 1. out of bounds
+    let index = if !s.is_char_boundary(begin) { begin } else { end };
```
Comment (durka) [inline src/libcore/str/mod.rs]: This is confusing to me. It seems like you choose which index is going to be in the message before checking which one is out of bounds.

File: src/libcore/str/mod.rs [hunk 2]
```diff
@@ -1741,13 +1741,29 @@ fn truncate_to_char_boundary(s: &str, mut max: usize) -> (bool, &str) {
...
-          begin, end, s, ellipsis);
+            begin, end, s_trunc, ellipsis);
+
+    // 3. character boundary
+    // find the character
+    let mut char_start = index;
+    while !s.is_char_boundary(char_start) {
+        char_start -= 1;
+    }
+    let ch = s[char_start..].chars().next().unwrap();
```
Comment (durka) [inline src/libcore/str/mod.rs]: This can panic if the string is empty or if `char_start` is at the end. I think I've convinced myself this can't happen, but at least a comment would help, or just to be defensive

```rust
if let Some(ch) = s[char_start..].chars().next() {
    let char_range = char_start .. char_start + ch.len_utf8();
    panic!("index {} is not a char boundary; it is inside {:?} (bytes {:?}) of `{}`{}",
           index, ch, char_range, s_trunc, ellipsis);
} else {
    panic!("index {} is not a char boundary in `{}`{}", index, s_trunc, ellipsis);
}
```

Comment (durka) [inline src/libcore/str/mod.rs]: Also, if the problematic index is beyond `MAX_DISPLAY_LENGTH`, the preview isn't going to be very useful. It could instead show the region of the string from `max(0, index - MAX_DISPLAY_LENGTH/2) .. min(s.len(), index + MAX_DISPLAY_LENGTH/2)` with ellipses.

**Review by durka — APPROVED** [review]

File: src/libcore/str/mod.rs (hunk 1 above)
Comment (bluss) [inline src/libcore/str/mod.rs]: `is_char_boundary` is false if the index is out of bounds.

File: src/libcore/str/mod.rs (hunk 2 above)
Comment (bluss) [inline src/libcore/str/mod.rs]: char_start is a character boundary, and then using it for slicing is ok. It could not be larger than len, that case has already been handled. It could not be equal to len, then it would not be an error in the first place.

Comment (bluss) [inline src/libcore/str/mod.rs]: I feel like this is unnecessary, it just wants to identify the string somehow.

File: src/libcore/str/mod.rs (hunk 1 above)
Comment (bluss) [inline src/libcore/str/mod.rs]: ok, it should be confusing, because it's not really right.

File: src/libcore/str/mod.rs [hunk 3]
```diff
@@ -1741,13 +1741,31 @@ fn truncate_to_char_boundary(s: &str, mut max: usize) -> (bool, &str) {
...
 fn slice_error_fail(s: &str, begin: usize, end: usize) -> ! {
     const MAX_DISPLAY_LENGTH: usize = 256;
-    let (truncated, s) = truncate_to_char_boundary(s, MAX_DISPLAY_LENGTH);
+    let (truncated, s_trunc) = truncate_to_char_boundary(s, MAX_DISPLAY_LENGTH);
     let ellipsis = if truncated { "[...]" } else { "" };
 
+    // 1. out of bounds
+    if begin > s.len() || end > s.len() {
+        let oob_index = if begin > s.len() { begin } else { end };
+        panic!("index {} is out of bounds of `{}`{}", oob_index, s_trunc, ellipsis);
```
Comment (killercup) [inline src/libcore/str/mod.rs]: Can you add a test for this as well?

**Review by killercup — COMMENTED** [review]
Nice work! Handling the different cases with custom messages makes this much better.

As mentioned in #38052 I'd like to try and convey that indexing a string (slice) is done using _byte_ offsets -- and not character offsets. I think this is one of those messages people will see this in failing tests and then have a hard time recognizing why this went wrong; and then have an even harder time to find a solution like the [unicode-segmentation](https://crates.io/crates/unicode-segmentation) crate. UTF-8 is hard when people don't think about it.

I know putting all that in the panic message is not a solution; but maybe you can change it to "slicing at byte 4 which is not a char boundary" or something like that?

(By the way, is there a lint to catch statically known wrong string slices?)

File: src/libcore/str/mod.rs (hunk 3 above)
Comment (bluss) [inline src/libcore/str/mod.rs]: I'll change the existing test to match more of the panic message

**Comment by durka** [comment]
@killercup maybe just s/index/byte index/ in the panic messages.

**Comment by bluss** [comment]
I like `byte index` or something like that. I've gotten into the habit of saying byte offset too, but don't know which is best. `char_indices` says indices, and other docs say .. what? :smile:

**Comment by steveklabnik** [comment]
ping @sfackler ; you're the reviewer on this PR but haven't commented. Should we move it to someone else?

**Comment by bluss** [comment]
Oh sorry, I also forgot about this. Thank you steveklabnik!

**Comment by sfackler** [comment]
Oops, missed this!

I'm a bit worried about including the entire string in the panic message. I can see that getting pretty incomprehensible for larger strings. Maybe just 20 or 30 characters of context around the index?

**Comment by bluss** [comment]
This PR keeps the previous behaviour that the string piece shown is truncated to 256 bytes or less. That was just some arbitrary limit that I picked in a previous that PR introduced some truncation at all.

**Comment by sfackler** [comment]
Oh great, my mistake!

**Comment by alexcrichton** [comment]
@bors: retry

* android timeout
