### PR TITLE
Fix `--skip-std-check-if-no-download-rustc`

### LINKED ISSUE #143705: `./x check library --stage 1 --skip-std-check-if-no-download-rustc` builds rustc
It seems some (very) recent change broke the `--skip-std-check-if-no-download-rustc` flag: if I invoke the command `./x check library --stage 1 --skip-std-check-if-no-download-rustc` in a checkout where I changed rustc, I would expect that to do nothing. That's kind of the entire point: I do *not* want an expensive rustc build. But I want a cheap library check if that's possible.

Instead, I see this:
```
$ ./x check library --stage 1 --skip-std-check-if-no-download-rustc
Building bootstrap
    Finished `dev` profile [unoptimized] target(s) in 0.03s
WARNING: `--skip-std-check-if-no-download-rustc` flag was passed and `rust.download-rustc` is not available. Skipping.
/home/r/src/rust/rustc.2/build/x86_64-unknown-linux-gnu/ci-llvm/bin/llvm-strip does not exist; skipping copy
Building compiler artifacts (stage0 -> stage1, x86_64-unknown-linux-gnu)
   Compiling rustc_span v0.0.0 (/home/r/src/rust/rustc.2/compiler/rustc_span)
   Compiling rustc_llvm v0.0.0 (/home/r/src/rust/rustc.2/compiler/rustc_llvm)
   Compiling rustc_abi v0.0.0 (/home/r/src/rust/rustc.2/compiler/rustc_abi)
   Compiling rustc_ast v0.0.0 (/home/r/src/rust/rustc.2/compiler/rustc_ast)
   Compiling rustc_type_ir v0.0.0 (/home/r/src/rust/rustc.2/compiler/rustc_type_ir)
   Compiling rustc_error_messages v0.0.0 (/home/r/src/rust/rustc.2/compiler/rustc_error_messages)
```
It even says that it's skipping, but then it doesn't skip.

Cc @Kobzol

### PR DESCRIPTION
**Pull request by Kobzol**
Since https://github.com/rust-lang/rust/pull/143048, we now explicitly set the build compiler for `check::Std`, which caused it to be built before we checked `--skip-std-check-if-no-download-rustc`. So I moved the check earlier to `make_run`, which resolves it.

I also added a regression test for this. Sadly we can't really test for the positive case easily (when download-ci-rustc is enabled), but we can test the negative cases, where it is disabled.

Fixes: https://github.com/rust-lang/rust/issues/143705

r? @RalfJung

### CODE REVIEW

**Comment by RalfJung** [comment]
Thanks a lot for the quick fix. :)
However, sorry, I can't review this code, I don't understand any of it.^^

r? bootstrap

File: src/bootstrap/src/core/builder/tests.rs [hunk 1]
```diff
@@ -1439,6 +1439,30 @@ mod snapshot {
         ");
     }
 
+    /// Make sure that we don't check library when download-rustc-ci is disabled
```
Comment (jieyouxu) [inline src/bootstrap/src/core/builder/tests.rs]: Nit: `download-rustc`

**Review by jieyouxu — APPROVED** [review]
Thanks, r=me after nit
