### PR TITLE
driver: Disallow predicates in --cfg specs

### LINKED ISSUE #31495: --cfg accepts invalid cfgs
List meta items are not allowed in `cfg` specs because the compiler reserves them for built-in predicates like `any`.

So for example you can't write

```
foo.rs:1:7: 1:16 error: invalid predicate `foo`
foo.rs:1 #[cfg(foo(bar))]
               ^~~~~~~~~
```

You *can* though write `rustc --cfg "foo(bar))". This should be similarly rejected.

cc https://github.com/rust-lang/rust/pull/31278

### PR DESCRIPTION
**Pull request by kamalmarhubi**
A spec like `#[cfg(foo(bar))]` is not allowed as an attribute. This
makes the same spec be rejected by the compiler if passed in as a
`--cfg` argument.

Fixes #31495

### CODE REVIEW

File: src/librustc_driver/lib.rs [hunk 1]
```diff
@@ -324,34 +325,53 @@ pub trait CompilerCalls<'a> {
...
+             output: ErrorOutputType) {
+    fn is_meta_list(item: &ast::MetaItem) -> bool {
+        match item.node {
+            ast::MetaItem_::MetaList(..) => true,
+            _ => false,
+        }
+    }
+
+    if sopts.cfg.iter().any(|item| is_meta_list(&*item)) {
+        early_error(output, "predicates are not allowed in --cfg");
```
Comment (kamalmarhubi) [inline src/librustc_driver/lib.rs]: Not sure about error message, or if we should print the offending flags as well. Input welcome!

Comment (brson) [inline src/librustc_driver/lib.rs]: How about something "invalid predicate in --cfg command line argument: foo(whatever)", printing the actual argument. That mirrors the in-source error a little better and says where the error is.

Comment (kamalmarhubi) [inline src/librustc_driver/lib.rs]: Sounds good. I'll make the change after finding out how to print more than one error, since the user could have passed multiple offending flags. (This is my first time in the compiler's code.)

**Comment by kamalmarhubi** [comment]
@brson any thoughts on whether the check should be in the `early_callback` or the `late_callback`?

File: src/librustc_driver/lib.rs (hunk 1 above)
Comment (kamalmarhubi) [inline src/librustc_driver/lib.rs]: Done in https://github.com/kamalmarhubi/rust/commit/c32c7c24860eb6ed65bdec2491ba99b6eb5550b8

**Comment by brson** [comment]
@kamalmarhubi early.

@bors r+ Thanks!
