### PR TITLE
Report line number of test when should_panic test failed

### LINKED ISSUE #137405: Tests marked as should_panic should report the line number of the test
It would be useful for being able to easily navigate to failing tests if the tests don't panic when they should. Specifically, providing the file and line number of the failing test allows a user to use the mouse to navigate directly in one step from a test run in a vscode terminal window to the location of the failing test.

Given:
```rust
#[test]
#[should_panic]
fn dont_panic() {
    // DON'T PANIC
}
```
This reports:
```
running 1 test
test dont_panic - should panic ... FAILED

successes:

successes:

failures:

---- dont_panic stdout ----
note: test did not panic as expected

failures:
    dont_panic

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s
```
Compare this with:
```rust
#[test]
fn do_panic() {
    panic!("Panic!");
}
```
which gives:
```
---- do_panic stdout ----

thread 'do_panic' panicked at src/lib.rs:9:5:
Panic!
stack backtrace:
...
```

Which in a vscode terminal looks like:

Image

Implementation Constraints:
Use filename:line:column format - don't use a custom formate like "file at line x". Noted specifically This has happened in some parts of the rust ecosystem in the past (in rustfmt IIRC), and it makes the automatic navigation not work right.

### PR DESCRIPTION
**Pull request by xizheyin**
Closes #137405 

---

try-job: x86_64-gnu-llvm-19-3
try-job: test-various

### CODE REVIEW

File: tests/ui/test-should-panic-failed-show-span.rs [hunk 1]
```diff
@@ -0,0 +1,30 @@
...
+#[test]
+#[should_panic]
+fn do_panic1() {
+    panic!("Panic!");
+}
+
+#[test]
+#[should_panic = "SubString"]
+fn do_panic2() {
+    // DON'T PANIC
```
Comment (joshka) [inline tests/ui/test-should-panic-failed-show-span.rs:15]:
```suggestion
```

File: tests/ui/test-should-panic-failed-show-span.rs [hunk 2]
```diff
@@ -0,0 +1,30 @@
+//@ run-fail
+//@ check-run-results
+//@ compile-flags: --test
+
+
+#[test]
+#[should_panic]
+fn do_panic1() {
```
Comment (joshka) [inline tests/ui/test-should-panic-failed-show-span.rs:8]:
```suggestion
fn should_panic_with_any_message() {
```

File: tests/ui/test-should-panic-failed-show-span.rs [hunk 3]
```diff
@@ -0,0 +1,30 @@
...
+    panic!("Panic!");
+}
+
+#[test]
+#[should_panic = "SubString"]
+fn do_panic2() {
```
Comment (joshka) [inline tests/ui/test-should-panic-failed-show-span.rs:14]:
```suggestion
fn should_panic_with_substring() {
```

File: tests/ui/test-should-panic-failed-show-span.rs [hunk 4]
```diff
@@ -0,0 +1,30 @@
...
+    // DON'T PANIC
+    panic!("SubString");
+}
+
+#[test]
+#[should_panic]
+fn dont_panic1() {
```
Comment (joshka) [inline tests/ui/test-should-panic-failed-show-span.rs:21]:
```suggestion
fn should_panic_with_any_message_does_not_panic() {
```

File: tests/ui/test-should-panic-failed-show-span.rs [hunk 5]
```diff
@@ -0,0 +1,30 @@
...
+    // DON'T PANIC
+}
+
+
+#[test]
+#[should_panic = "SubString"]
+fn dont_panic2() {
```
Comment (joshka) [inline tests/ui/test-should-panic-failed-show-span.rs:28]:
```suggestion
fn should_panic_with_substring_does_not_panic() {
```

File: tests/ui/test-should-panic-failed-show-span.rs
Comment (joshka) [inline tests/ui/test-should-panic-failed-show-span.rs:1]: Do you need to add a test for panicking with the wrong string?

```rust
#[test]
#[should_panic = "Substring"]
fn should_panic_with_substring_panics_with_incorrect_string() {
    panic!("ZOMGWTFBBQ");
}
```

File: library/test/src/test_result.rs
Comment (joshka) [inline library/test/src/test_result.rs:1]: Do the parts on line 58 to 68 also need to have the span added (and be tested). Not covered in the linked issue, but seems like these would be also good to fix in this PR if they're currently incorrect.

**Review by joshka — COMMENTED** [review]
Test names are nits, but make the reason for each test self describing.

I think it probably makes sense to also fix the substring tests if they're also broken (I haven't manually checked those messages to see if there's span info coming from elsewhere in the stack, but these seem like they should be tested with the same tests as are introduced here).

File: tests/ui/test-should-panic-failed-show-span.run.stdout [hunk 6]
```diff
@@ -0,0 +1,40 @@
...
+
+---- should_panic_with_any_message_does_not_panic stdout ----
+note: test did not panic as expected at $DIR/test-should-panic-failed-show-span.rs:20:4
+---- should_panic_with_message_does_not_panic stdout ----
+note: test did not panic as expected at $DIR/test-should-panic-failed-show-span.rs:27:4
+---- should_panic_with_substring_panics_with_incorrect_string stdout ----
+
+thread 'should_panic_with_substring_panics_with_incorrect_string' panicked at $DIR/test-should-panic-failed-show-span.rs:34:5:
+ZOMGWTFBBQ
+note: should panic with message at $DIR/test-should-panic-failed-show-span.rs:33:4
```
Comment (xizheyin) [inline tests/ui/test-should-panic-failed-show-span.run.stdout:20]: Now, I add support for cases that should panic with message but panic with incorrect string or non-string value.

File: library/test/src/test_result.rs [hunk 7]
```diff
@@ -45,6 +45,18 @@ pub(crate) fn calc_result<'a>(
     time_opts: Option<&time::TestTimeOptions>,
     exec_time: Option<&time::TestExecTime>,
 ) -> TestResult {
+    let span_str = if desc.source_file != "" {
```
Comment (joshka) [inline library/test/src/test_result.rs:48]: Nit: what about using a name like?
```suggestion
    let at_location = if desc.source_file != "" {
```

File: library/test/src/test_result.rs [hunk 8]
```diff
@@ -45,6 +45,18 @@ pub(crate) fn calc_result<'a>(
...
+        format!(" at {}:{}:{}", desc.source_file, desc.start_line, desc.start_col)
+    } else {
+        "".to_string()
+    };
+
+    let span_should_panic_with_message_didnot_panic = if desc.source_file != "" {
```
Comment (joshka) [inline library/test/src/test_result.rs:54]: Nit: Given this is a local variable, I'd generally choose a bit of a shorter name. It's also only applicable to one of the match arms, so move it within that block below (at line 63)

**Review by joshka — APPROVED** [review]
Generally LGTM - small nits

(Note: I'm not a member of the rust project, so this likely still requires approval from someone who is)

**Comment by jieyouxu** [comment]
> (Note: I'm not a member of the rust project, so this likely still requires approval from someone who is)

Though reviews are still very much appreciated 😁

**Review by joshka — APPROVED** [review]

**Comment by joboet** [comment]
I've never touched the `test` crate before so I don't feel qualified to review this.
r? @thomcc 
as you are a member of testing-devex

File: library/test/src/test_result.rs [hunk 9]
```diff
@@ -53,26 +59,32 @@ pub(crate) fn calc_result<'a>(
                 .map(|e| &**e)
                 .or_else(|| err.downcast_ref::<&'static str>().copied());
 
+            let shoud_panic_location = if desc.source_file != "" {
```
Comment (thomcc) [inline library/test/src/test_result.rs:62]: Typo nit: `should_panic_location`.

Comment (xizheyin) [reply library/test/src/test_result.rs]: Thanks

**Comment by Kobzol** [comment]
> @bors try
> 
> Before the change fails snapshots in Cargo's test testsuite

(Just noting that this doesn't run any Cargo tests, in fact it doesn't run any tests at all :) ).

File: library/test/src/test_result.rs [hunk 10]
```diff
@@ -53,26 +59,32 @@ pub(crate) fn calc_result<'a>(
                 .map(|e| &**e)
                 .or_else(|| err.downcast_ref::<&'static str>().copied());
 
+            let should_panic_location = if desc.source_file != "" {
```
Comment (epage) [inline library/test/src/test_result.rs:62]: Should we instead check for `!at_location.is_empty()`?

File: library/test/src/test_result.rs [hunk 11]
```diff
@@ -53,26 +59,32 @@ pub(crate) fn calc_result<'a>(
...
+
             if maybe_panic_str.map(|e| e.contains(msg)).unwrap_or(false) {
                 TestResult::TrOk
             } else if let Some(panic_str) = maybe_panic_str {
                 TestResult::TrFailedMsg(format!(
-                    r#"panic did not contain expected string
+                    r#"{should_panic_location}panic did not contain expected string
       panic message: `{panic_str:?}`,
- expected substring: `{msg:?}`"#
+      expected substring: `{msg:?}`"#
```
Comment (epage) [inline library/test/src/test_result.rs:74]: This is an unrelated change and should be split out to a different commit, maybe even a different PR.

Also, unsure if we should do it.

File: library/test/src/test_result.rs [hunk 12]
```diff
@@ -53,26 +59,32 @@ pub(crate) fn calc_result<'a>(
...
                 ))
             } else {
                 TestResult::TrFailedMsg(format!(
-                    r#"expected panic with string value,
- found non-string value: `{:?}`
-     expected substring: `{:?}`"#,
+                    r#"{should_panic_location}expected panic with string value,
+      found non-string value: `{:?}`
+      expected substring: `{:?}`"#,
```
Comment (epage) [inline library/test/src/test_result.rs:80]: ditto about alignment changes

File: library/test/src/test_result.rs [hunk 13]
```diff
@@ -45,6 +45,12 @@ pub(crate) fn calc_result<'a>(
     time_opts: Option<&time::TestTimeOptions>,
     exec_time: Option<&time::TestExecTime>,
 ) -> TestResult {
+    let at_location = if desc.source_file != "" {
```
Comment (epage) [inline library/test/src/test_result.rs:48]: For myself, I'd be a bit more specific, like `fn_location` or `test_location`

**Review by epage — APPROVED** [review]

**Review by joshka — APPROVED** [review]

**Comment by chenyukang** [comment]
All comment feedbacks were resolved, LGTM, thanks!
@bors r=chenyukang

**Comment by xizheyin** [comment]
Why did it cause a failure? I noticed that the failed stdout seems to have extra backtrace inside it.

**Comment by chenyukang** [comment]
> Why did it cause a failure? I noticed that the failed stdout seems to have extra backtrace inside it.

maybe caused by some other changes from upstream, can you rebase this PR and have a testing on local, which may can reproduce the error.

**Comment by Zalathar** [comment]
It looks like other run-fail tests for test attributes use `//@ exec-env:RUST_BACKTRACE=0` to explicitly disable backtraces.

File: tests/ui/test-should-panic-failed-show-span.rs
Comment (Zalathar) [inline tests/ui/test-should-panic-failed-show-span.rs:1]: Suggestion: There are other tests for the `#[test]` and `#[should_fail]` attributes in the `tests/ui/test-attrs/` directory, so I think this test should be in that subdirectory instead of the very crowded `tests/ui/` directory.

**Comment by xizheyin** [comment]
What's werid is that when I updated the latest code, it didn't fail in the local test, so I suspect that the PR that happened to rollup together had content that conflicted with this.

However that's ok, I've added `//@ exec-env: RUST_BACKTRACE=0` to avoid backtrace.

Thank both of you, @chenyukang @Zalathar

**Comment by xizheyin** [comment]
It seems that there are too many (6) functions in the test, causing the execution time to become 0.01s sometimes, I deleted the tests that have nothing to do with the change, and only kept the two tests that “should be panic but are not”.

**Comment by Zalathar** [comment]
You will also need this to prevent the test time from causing unpredictable failures:

```rust
//@ normalize-stdout: "finished in \d+\.\d+s" -> "finished in $$TIME"
```

**Comment by xizheyin** [comment]
Oops, still failed.

**Comment by xizheyin** [comment]
```
//@ run-fail
//@ check-run-results
//@ compile-flags: --test
//@ exec-env:RUST_BACKTRACE=0
//@ normalize-stdout: "finished in \d+\.\d+s" -> "finished in $$TIME"
//@ run-flags: --test-threads=1
```
Now maybe it's okay. I learned a lot and next time I can look for the appropriate directives in similar tests.

File: tests/ui/test-attrs/test-should-panic-failed-show-span.rs [hunk 14]
```diff
@@ -1,9 +1,11 @@
+//@ no-prefer-dynamic
```
Comment (jieyouxu) [inline tests/ui/test-attrs/test-should-panic-failed-show-span.rs:1]: Suggestion: I think this isn't needed

File: tests/ui/test-attrs/test-should-panic-failed-show-span.rs [hunk 15]
```diff
@@ -1,9 +1,11 @@
...
+//@ compile-flags: --test
+//@ run-flags: --test-threads=1
 //@ run-fail
 //@ check-run-results
-//@ compile-flags: --test
 //@ exec-env:RUST_BACKTRACE=0
 //@ normalize-stdout: "finished in \d+\.\d+s" -> "finished in $$TIME"
-//@ run-flags: --test-threads=1
+//@ needs-threads
```
Comment (jieyouxu) [inline tests/ui/test-attrs/test-should-panic-failed-show-span.rs:8]: Suggestion: I *think* for libtest unwinding you might need sth like

```
//@ needs-unwind (panic)
```

Comment (Zalathar) [reply tests/ui/test-attrs/test-should-panic-failed-show-span.rs:8]: I think `--test-threads=1` might still be needed for deterministic ordering of test results.

Comment (jieyouxu) [reply tests/ui/test-attrs/test-should-panic-failed-show-span.rs:8]: Oh I didn't notice that being removed. Yes, `--test-threads=1` has to be used for determinism.

File: tests/ui/test-attrs/test-should-panic-failed-show-span.rs [hunk 16]
```diff
@@ -0,0 +1,44 @@
...
+#[should_panic = "message"]
+fn should_panic_with_substring_panics_with_incorrect_string() {
+    panic!("ZOMGWTFBBQ");
+}
+
+#[test]
+#[should_panic = "message"]
+fn should_panic_with_substring_panics_with_non_string_value() {
+    panic!(123); //~ WARNING panic message is not a string literal
+}
```
Comment (Zalathar) [inline tests/ui/test-attrs/test-should-panic-failed-show-span.rs:44]: We can add `#[expect(non_fmt_panics)]` to this function to get rid of the compiler warning and simplify the output snapshots, since the warning isn't important to the test.

File: tests/ui/test-attrs/test-should-panic-failed-show-span.rs (hunk 15 above)
Comment (xizheyin) [reply tests/ui/test-attrs/test-should-panic-failed-show-span.rs:8]: Now, I added it.

File: tests/ui/test-attrs/test-should-panic-failed-show-span.rs (hunk 14 above)
Comment (xizheyin) [reply tests/ui/test-attrs/test-should-panic-failed-show-span.rs]: I removed it, I was more curious at what point it would be useful.

File: tests/ui/test-attrs/test-should-panic-failed-show-span.rs (hunk 16 above)
Comment (xizheyin) [reply tests/ui/test-attrs/test-should-panic-failed-show-span.rs]: Yeah, I added it.

File: tests/ui/test-attrs/test-should-panic-failed-show-span.run.stdout [hunk 17]
```diff
@@ -0,0 +1,32 @@
...
+note: test did not panic as expected at $DIR/test-should-panic-failed-show-span.rs:24:4
+---- should_panic_with_message_does_not_panic stdout ----
+note: test did not panic as expected at $DIR/test-should-panic-failed-show-span.rs:30:4
+---- should_panic_with_substring_panics_with_incorrect_string stdout ----
+note: panic did not contain expected string
+      panic message: `"ZOMGWTFBBQ"`,
+ expected substring: `"message"`
+---- should_panic_with_substring_panics_with_non_string_value stdout ----
+note: expected panic with string value,
+ found non-string value: `TypeId(0x56ced5e4a15bd89050bb9674fa2df013)`
```
[the remark this answers is not in the document]
Comment (xizheyin) [reply tests/ui/test-attrs/test-should-panic-failed-show-span.run.stdout]: Now, it is like
```
 found non-string value: `TypeId($HEX)`
```
