### PR TITLE
Make GATs less ICE-prone.

### LINKED ISSUE #47206: where clause in generic associated types causes no output
I'm working on implementing generic associated types in the compiler with mentoring by @nikomatsakis. He recently discovered an interesting issue that we're haven't found the source of yet. It seems that having a where clause like the one below results in a compilation error but no output.

**The feature isn't actually fully finished yet, so we expect a compilation error. It just isn't clear why the compiler isn't actually reporting any specific problems. The message says that it failed due to a previous error but doesn't list any errors at all.**

Here's the code that reproduces the issue: ([Playground link](https://play.rust-lang.org/?gist=0ecb7409a3690e31d73363800c905324&version=nightly))

```rust
#![feature(generic_associated_types)]

trait Foo {
    type Assoc3<T>;
}

struct Bar;

impl Foo for Bar {
    type Assoc3<T> where T: Iterator = Vec<T>;
}

fn main() {}
```

Here's the output:

```
   Compiling playground v0.0.1 (file:///playground)
error: cannot continue compilation due to previous error

error: Could not compile `playground`.

To learn more, run the command again with --verbose.
```

This is on the nightly compiler because the feature is gated while we're still working on it. If you try to run this on stable or beta, you get a normal error message.

If you delete the `where T: Iterator` you get an ICE which I think is expected given what I still have left to implement for the generic associated types feature.

It might be that this gets fixed while we keep implementing generic associated types. Creating this issue will make sure that this doesn't get forgotten along the way.

### LINKED ISSUE #49362: ICE: Region parameter out of range when substituting in region...
```rust
#![feature(generic_associated_types)]

struct S;

trait Trait {
    type Associated<'a>;
}

impl Trait for S {
    type Associated<'a> = &'a ();
}

fn main() {}
```

```
error: internal compiler error: librustc/ty/subst.rs:439: Region parameter out of range when substituting in region 'a (root type=Some(TestIterItem<'a>)) (index=0)

thread 'rustc' panicked at 'Box<Any>', librustc_errors/lib.rs:488:9
note: Run with `RUST_BACKTRACE=1` for a backtrace.
error: aborting due to 2 previous errors
```

[Rust playground](https://play.rust-lang.org/?gist=755945d9d30e59068194aebe6b9fdf3a&version=nightly&mode=debug)

Probably related: https://github.com/rust-lang/rust/issues/47309

I can reproduce this with `rustc 1.26.0-nightly (f5631d9ac 2018-03-24)`.

### LINKED ISSUE #62521: lifetime-parametric GATs cause ICEs (with feature(generic_associated_types))
Many people playing with `#[feature(generic_associated_types)]` have noticed that they break very easily when you attempt to use a lifetime formal parameter.

Examples follow

## ICE: Region parameter out of range

#62326 ([play](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=1f746eb41c0bf5be7e9257e988955aed)):

```rust
#![feature(generic_associated_types)]
trait Iterator {
    type Item<'a>: 'a;
}
```

#58694 ([play](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=b68503853a25ca17e4977a8bb9a98d17))

```rust
#![feature(generic_associated_types)]
trait Foo {
  type PublicKey<'a> : From<&'a [u8]>;     
}
```
#49362 ([play](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=3327573fdbd07347d0d9af9e46060e5d))

```rust
#![feature(generic_associated_types)]

trait Trait {
    type Associated<'a>;
}

impl Trait for () {
    type Associated<'a> = &'a ();
}
```

## ICE: cannot convert `ReEarlyBound(0, 'b)` to a region vid

#60654 ([play](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=953cda8237dac3b12d848576be095e6a))

```rust
#![feature(generic_associated_types)]
struct Foo;

impl Iterator for Foo {
    type Item<'b> = &'b Foo;

    fn next(&mut self) -> Option<Self::Item> {
        None
    }
}
```

----

This obviously blocks stabilization of GATs (#44265).

### LINKED ISSUE #63300: ICE on generic associated type with a bound referencing the quantified type
I was reading https://varkor.github.io/blog/2019/03/28/idiomatic-monads-in-rust.html and decided to try some of the code samples, but the compiler panicked!

```rust
trait Functor<A> {
    type HigherSelf<T>: Functor<T>;
}
```

Crashes with `error: internal compiler error: src/librustc/ty/subst.rs:570: type parameter `T/#2` (T/2) out of range when substituting (root type=Some(T)) substs=[<Self as Functor<A>>::HigherSelf, T]`

The compiler mentions that 'generic associated types are unstable', but the crash occurs even with the feature gate turned off. This happens on both `stable` and `nightly`.

## Traceback

```
thread 'rustc' panicked at 'Box<Any>', src/librustc_errors/lib.rs:572:9
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
   1: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:59
             at src/libstd/panicking.rs:197
   3: std::panicking::default_hook
             at src/libstd/panicking.rs:211
   4: rustc::util::common::panic_hook
   5: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:478
   6: std::panicking::begin_panic
   7: rustc_errors::Handler::span_bug
   8: rustc::util::bug::opt_span_bug_fmt::{{closure}}
   9: rustc::ty::context::tls::with_opt::{{closure}}
  10: rustc::ty::context::tls::with_context_opt
  11: rustc::ty::context::tls::with_opt
  12: rustc::util::bug::opt_span_bug_fmt
  13: rustc::util::bug::span_bug_fmt
  14: <rustc::ty::subst::SubstFolder as rustc::ty::fold::TypeFolder>::fold_ty
  15: <smallvec::SmallVec<A> as core::iter::traits::collect::FromIterator<<A as smallvec::Array>::Item>>::from_iter
  16: rustc::ty::fold::TypeFoldable::fold_with
  17: rustc::ty::subst::Subst::subst
  18: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::fold
  19: rustc::ty::GenericPredicates::instantiate_into
  20: rustc::ty::wf::WfPredicates::nominal_obligations
  21: rustc::ty::wf::WfPredicates::compute_trait_ref
  22: rustc::ty::wf::predicate_obligations
  23: <core::iter::adapters::flatten::FlatMap<I,U,F> as core::iter::traits::iterator::Iterator>::next
  24: rustc_typeck::check::wfcheck::check_where_clauses
  25: rustc::ty::context::GlobalCtxt::enter_local
  26: rustc_typeck::check::wfcheck::check_trait
  27: rustc_typeck::check::wfcheck::check_item_well_formed
  28: rustc::ty::query::__query_compute::check_item_well_formed
  29: rustc::ty::query::<impl rustc::ty::query::config::QueryAccessors for rustc::ty::query::queries::check_item_well_formed>::compute
  30: rustc::dep_graph::graph::DepGraph::with_task_impl
  31: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt>::get_query
  32: <rustc_typeck::check::wfcheck::CheckTypeWellFormedVisitor as rustc::hir::itemlikevisit::ParItemLikeVisitor>::visit_item
  33: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:85
  34: rustc_data_structures::sync::par_for_each_in
  35: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:85
  36: rustc::hir::Crate::par_visit_all_item_likes
  37: rustc::util::common::time
  38: rustc_typeck::check_crate
  39: rustc_interface::passes::analysis
  40: rustc::ty::query::__query_compute::analysis
  41: rustc::ty::query::<impl rustc::ty::query::config::QueryAccessors for rustc::ty::query::queries::analysis>::compute
  42: rustc::dep_graph::graph::DepGraph::with_task_impl
  43: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt>::get_query
  44: rustc::ty::context::tls::enter_global
  45: rustc_interface::passes::BoxedGlobalCtxt::access::{{closure}}
  46: rustc_interface::passes::create_global_ctxt::{{closure}}
  47: rustc_interface::interface::run_compiler_in_existing_thread_pool
  48: std::thread::local::LocalKey<T>::with
  49: scoped_tls::ScopedKey<T>::set
  50: syntax::with_globals
query stack during panic:
#0 [check_item_well_formed] processing `Functor`
#1 [analysis] running analysis passes on this crate
end of query stack
```

## Version

```
$ rustc --version -v
rustc 1.36.0 (a53f9df32 2019-07-03)
binary: rustc
commit-hash: a53f9df32fbb0b5f4382caaad8f1a46f36ea887c
commit-date: 2019-07-03
host: x86_64-unknown-linux-gnu
release: 1.36.0
LLVM version: 8.0
```

This issue has been assigned to @doctorn via [this comment](https://github.com/rust-lang/rust/issues/63300#issuecomment-520165135).

### LINKED ISSUE #64755: GAT impl with type parameter causes ICE, even without feature enabled
This also applies to stable rust, since it still ICEs without the feature gate, though of course on stable there's no way to encounter it without having another error due to the feature not being enabled. It's similar to #60654 but with type parameters instead of lifetime parameters. Here's an example ([playground link](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=347f9ee275c62d7350bc08010a3f36d3)):
```rust
struct Foo;

trait MyTrait {
    type Item<T>;
}

impl MyTrait for Foo {
    type Item<T> = T;
}
```
This is a bit easier to encounter than that example shows, since type cohesion isn't checked for GATs yet, meaning that you can reproduce this by implementing the normal Iterator trait but still placing a type parameter on the Item type (note for whoever implements that: almost all of the code in rustc_typeck::check::compare_method is reusable there).

### LINKED ISSUE #67089: GAT: Constructing associated types parameterised by lifetime
Uses generic associated types - https://github.com/rust-lang/rust/issues/44265

As I understand it, the following should be legal:
```rust
trait A {
    type B<'a>;
    
    fn make_b<'a>(&'a self) -> Self::B<'a>;
}
```
I simply get an error:
```
error[E0109]: lifetime arguments are not allowed for this type
 --> src/lib.rs:6:40
  |
6 |     fn make_b<'a>(&'a self) -> Self::B<'a>;
  |                                        ^^ lifetime argument not allowed
```

Playground: https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=a4a05477f9f0f529277707801ffd0297

### PR DESCRIPTION
**Pull request by matthewjasper**
After this PR simple lifetime-generic associated types can now be used in a compiling program. There are two big limitations:

* #30472 has not been addressed in any way (see src/test/ui/generic-associated-types/iterable.rs)
* Using type- and const-generic associated types errors because bound types and constants aren't handled by trait solving.
    * The errors are technically non-fatal, but they happen in a [part of the compiler](https://github.com/rust-lang/rust/blob/4abb0ad2731e9ac6fd5d64d4cf15b7c82e4b5a81/src/librustc_typeck/lib.rs#L298) that fairly aggressively stops compiling on errors.

closes #47206
closes #49362
closes #62521
closes #63300
closes #64755
closes #67089

### CODE REVIEW

**Comment by matthewjasper** [comment]
Does anyone from @rust-lang/compiler want to review this?

File: src/librustc/traits/error_reporting.rs [hunk 1]
```diff
@@ -2440,6 +2442,12 @@ impl<'a, 'tcx> InferCtxt<'a, 'tcx> {
                               but not on the corresponding trait method",
                              predicate));
             }
+            ObligationCauseCode::CompareImplTypeObligation { .. } => {
+                err.note(&format!(
+                    "the requirement `{}` appears on the associated impl type\
```
Comment (estebank) [inline src/librustc/traits/error_reporting.rs]:
```suggestion
                    "the requirement `{}` appears on the associated impl type \
```

File: src/librustc/ty/subst.rs [hunk 2]
```diff
@@ -533,8 +533,7 @@ impl<'a, 'tcx> TypeFolder<'tcx> for SubstFolder<'a, 'tcx> {
                             data.name,
                             self.root_ty,
                             data.index);
-                        self.tcx.sess.delay_span_bug(span, &msg);
-                        r
+                        span_bug!(span, "{}", msg);
```
Comment (estebank) [inline src/librustc/ty/subst.rs]: What's the need for this change? The `delay_span_bug` approach hides bugs elsewhere from us, but also safely lets the compiler continue for the users' sake.

Comment (matthewjasper) [reply src/librustc/ty/subst.rs]: Indeed, it hides bugs.

File: src/librustc_resolve/late.rs [hunk 3]
```diff
@@ -1119,15 +1119,15 @@ impl<'a, 'b> LateResolutionVisitor<'a, '_> {
...
+                                            ImplItemKind::TyAlias(_) => {
                                                 // If this is a trait impl, ensure the type
                                                 // exists in trait
                                                 this.check_trait_item(impl_item.ident,
                                                                       TypeNS,
                                                                       impl_item.span,
                                                     |n, s| TypeNotMemberOfTrait(n, s));
 
-                                                this.visit_ty(ty);
+                                                visit::walk_impl_item(this, impl_item);
```
Comment (estebank) [inline src/librustc_resolve/late.rs]: This change is effectively a noop, right?

Comment (matthewjasper) [reply src/librustc_resolve/late.rs]: It's not. It wasn't visiting the where clause before.

File: src/librustc_typeck/check/compare_method.rs [hunk 4]
```diff
@@ -1059,3 +1065,131 @@ pub fn compare_const_impl<'tcx>(
...
+    tcx: TyCtxt<'tcx>,
+    impl_ty: &ty::AssocItem,
+    impl_ty_span: Span,
+    trait_ty: &ty::AssocItem,
+    impl_trait_ref: ty::TraitRef<'tcx>,
+) -> Result<(), ErrorReported> {
+    let impl_substs = InternalSubsts::identity_for_item(tcx, impl_ty.def_id);
+    let trait_to_impl_substs = impl_substs.rebase_onto(tcx,
+                                                       impl_ty.container.id(),
+                                                       impl_trait_ref.substs);
```
Comment (estebank) [inline src/librustc_typeck/check/compare_method.rs]: Formatting.

File: src/librustc_typeck/check/compare_method.rs [hunk 5]
```diff
@@ -1059,3 +1065,131 @@ pub fn compare_const_impl<'tcx>(
...
+    })
+}
+
+fn assoc_item_kind_str(impl_item: &ty::AssocItem) -> &'static str {
+    match impl_item.kind {
+        ty::AssocKind::Const => "const",
+        ty::AssocKind::Method => "method",
+        ty::AssocKind::Type | ty::AssocKind::OpaqueTy => "type",
+    }
+}
```
Comment (estebank) [inline src/librustc_typeck/check/compare_method.rs]: Funnily enough, I recently had to write something similar https://github.com/rust-lang/rust/pull/67127/files#diff-c888afeccd78f53e5ea3eb04089e46dd but it hasn't been merged yet. Should we make this a method of the enum instead of a function?

File: src/test/ui/feature-gates/feature-gate-generic_associated_types.stderr [hunk 6]
```diff
@@ -53,14 +53,30 @@ LL |     type Assoc where Self: Sized;
...
    |
    = note: for more information, see https://github.com/rust-lang/rust/issues/44265
    = help: add `#![feature(generic_associated_types)]` to the crate attributes to enable
 
-error: aborting due to 7 previous errors
+error: type-generic associated types are not yet implemented
+  --> $DIR/feature-gate-generic_associated_types.rs:4:5
+   |
+LL |     type Pointer<T>: Deref<Target = T>;
+   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```
Comment (estebank) [inline src/test/ui/feature-gates/feature-gate-generic_associated_types.stderr]: It'd be nice if the error had secondary spans pointing at `T` in both sides, but it's not a blocker.

File: src/test/ui/generic-associated-types/impl_bounds.stderr [hunk 7]
```diff
@@ -0,0 +1,46 @@
...
+LL | impl<T> Foo for Fooy<T> {
+   |      - help: consider restricting this bound: `T: std::marker::Copy`
+...
+LL |     type C where Self: Copy = String;
+   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `std::marker::Copy` is not implemented for `T`
+   |
+   = note: required because of the requirements on the impl of `std::marker::Copy` for `Fooy<T>`
+   = note: the requirement `Fooy<T>: std::marker::Copy` appears on the associated impl typebut not on the corresponding associated trait type
+
+error: aborting due to 3 previous errors
```
Comment (estebank) [inline src/test/ui/generic-associated-types/impl_bounds.stderr]: Could you show us what this looks like with `#![feature(nll)]`, maybe in a different test? This test might actually fail when doing the full CI run if the output differs. You can see that for yourself if you run with `borrowck=compare`, IIRC.

File: src/test/ui/generic-associated-types/issue-62326-parameter-out-of-range.stderr [hunk 8]
```diff
@@ -0,0 +1,15 @@
...
+   |
+LL |   trait Iterator {
+   |   ^-------------
+   |   |
+   |  _required by `Iterator`
+   | |
+LL | |
+LL | |     type Item<'a>: 'a;
+LL | | }
+   | |_^
```
Comment (estebank) [inline src/test/ui/generic-associated-types/issue-62326-parameter-out-of-range.stderr]: Once this PR lands, can you file a ticket to make this output more visually appealing? The generic handling of spans, not E0280.

File: src/test/ui/generic-associated-types/shadowing.rs [hunk 9]
```diff
@@ -16,15 +16,19 @@ impl<'a> NoShadow<'a> for &'a u32 {
...
 
 trait ShadowT<T> {
-    type Bar<T>; //~ ERROR the name `T` is already used
+    type Bar<T>;
+    //~^ ERROR the name `T` is already used
+    //~| ERROR type-generic associated types are not yet implemented
 }
 
 trait NoShadowT<T> {
     type Bar<U>; // OK
```
Comment (estebank) [inline src/test/ui/generic-associated-types/shadowing.rs]:
```suggestion
    type Bar<U>;
```

**Comment by estebank** [comment]
The approach looks good, but I'd like other members of the team to take a look at the logic, given the subtlety involved.

File: src/test/ui/generic-associated-types/impl_bounds.stderr (hunk 7 above)
Comment (matthewjasper) [reply src/test/ui/generic-associated-types/impl_bounds.stderr]: The output is the same.

**Review by nikomatsakis — APPROVED** [review]
I reviewed the code and apart from some nits below, it looks great. What I wanted to do was to create a matrix of tests I'd like to see and compare the tests against that (and perhaps move it to the tracking issue). Not sure @matthewjasper if you did anything like that?
