### PR TITLE
Fix redundant semicolon lint interaction with proc macro attributes

### LINKED ISSUE #63947: Excess semicolon lint produces wrong diagnostics with async main and derive macro
The new lint for excess semicolons (https://github.com/rust-lang/rust/pull/62984) has some weird behaviour when the lint is triggered inside an async function that is transformed using a procedural macro.

Rustc version: 1.39.0-nightly (9b91b9c10 2019-08-26)

Compiling this:
```rust
#[tokio::main]
async fn main() -> Result<(), ()> {
    let mut workers = 5;;
    Ok(())
}
```
gives this output:
```
warning: unused variable: `workers`
 --> examples/test.rs:1:1
  |
1 | #[tokio::main]
  | ^ help: consider prefixing with an underscore: `_workers`
  |
  = note: `#[warn(unused_variables)]` on by default

warning: variable does not need to be mutable
 --> examples/test.rs:1:1
  |
1 | #[tokio::main]
  | ^ help: remove this `mut`
  |
  = note: `#[warn(unused_mut)]` on by default
```
note how the spans are all targeting the procedural macro instead of the correct line.

If I remove the procedural macro or if I remove the excess semicolon, the spans are fine. This leads me to believe that it's an error in the lint, not in the macro, but maybe I'm wrong.

### LINKED ISSUE #63967: redundant_semicolon and clippy::no_effect tripped without emitting line numbers
Using nightly-2019-08-26.

In [this TiKV PR](https://github.com/tikv/tikv/pull/5261#issuecomment-525569617) we upgraded the compiler. Our tidb_query component tripped the redundant_semicolon lint (and seemingly in turn clippy::no_effect) but rustc/clippy did not tell us the line number.

I couldn't find the code that triggered the lint and had to just allow both for the whole crate.

This issue has been assigned to @nathanwhit via [this comment](https://github.com/rust-lang/rust/issues/63967#issuecomment-528487292).

### PR DESCRIPTION
**Pull request by nathanwhit**
Fixes #63967 and fixes #63947, both of which were caused by the lint's changes to the parser interacting poorly with proc macro attributes and causing span information to be lost

r? @varkor

### CODE REVIEW

File: src/libsyntax/print/pprust.rs [hunk 1]
```diff
@@ -1651,9 +1651,17 @@ impl<'a> State<'a> {
...
             }
             ast::StmtKind::Semi(ref expr) => {
-                self.space_if_not_bol();
-                self.print_expr_outer_attr_style(expr, false);
-                self.s.word(";");
+                match expr.node {
+                    // Filter out empty Tup exprs created for the redundant_semicolon
+                    // lint, as they shouldn't be visible and interact poorly
+                    // with proc macros
+                    ast::ExprKind::Tup(ref exprs) if exprs.is_empty() => (),
```
Comment (Centril) [inline src/libsyntax/print/pprust.rs]: We can use a slice pattern instead to express this more succinctly:
```suggestion
                    ast::ExprKind::Tup([]) => {}
```

File: src/libsyntax/print/pprust.rs [hunk 2]
```diff
@@ -1651,9 +1651,17 @@ impl<'a> State<'a> {
                 }
             }
             ast::StmtKind::Semi(ref expr) => {
-                self.space_if_not_bol();
-                self.print_expr_outer_attr_style(expr, false);
-                self.s.word(";");
+                match expr.node {
+                    // Filter out empty Tup exprs created for the redundant_semicolon
```
Comment (Centril) [inline src/libsyntax/print/pprust.rs]:
```suggestion
                    // Filter out empty `Tup` exprs created for the `redundant_semicolon`
```

File: src/libsyntax/print/pprust.rs [hunk 3]
```diff
@@ -1651,9 +1651,17 @@ impl<'a> State<'a> {
...
+                    // lint, as they shouldn't be visible and interact poorly
+                    // with proc macros
```
Comment (Centril) [inline src/libsyntax/print/pprust.rs]:
```suggestion
                    // with proc macros.
```

File: src/test/ui/lint/redundant-semicolon/redundant-semi-proc-macro.rs [hunk 4]
```diff
@@ -0,0 +1,20 @@
+// check-fail
```
Comment (Centril) [inline src/test/ui/lint/redundant-semicolon/redundant-semi-proc-macro.rs]: Redundant/Wrong annotation. UI tests are "check-fail" by default.

File: src/test/ui/lint/redundant-semicolon/redundant-semi-proc-macro.rs [hunk 5]
```diff
@@ -0,0 +1,20 @@
...
+
+#![deny(redundant_semicolon)]
+extern crate redundant_semi_proc_macro;
+use redundant_semi_proc_macro::should_preserve_spans;
+
+#[should_preserve_spans]
+fn span_preservation()  {
+    let tst = 123;; //~ ERROR unnecessary trailing semicolon
+    match tst {
+        // redundant semicolons are parsed as empty tuple exprs
```
Comment (Centril) [inline src/test/ui/lint/redundant-semicolon/redundant-semi-proc-macro.rs]:
```suggestion
        // Redundant semicolons are parsed as empty tuple exprs
```

File: src/test/ui/lint/redundant-semicolon/redundant-semi-proc-macro.rs [hunk 6]
```diff
@@ -0,0 +1,20 @@
...
+        // for the lint, so ensure the lint doesn't affect
+        // empty tuple exprs explicitly in source
```
Comment (Centril) [inline src/test/ui/lint/redundant-semicolon/redundant-semi-proc-macro.rs]:
```suggestion
        // empty tuple exprs explicitly in source.
```

**Comment by nathanwhit** [comment]
@varkor No rush, but if you could look this over whenever you have the time that would be much appreciated.

**Comment by varkor** [comment]
@nathanwhit: sorry, I let this slip by me! Thanks for figuring this one out!

@bors r+ rollup

**Comment by mati865** [comment]
Failed in https://github.com/rust-lang/rust/pull/64626

Failures like that have been observed multiple times but AFAIK cause remains unknown.
.
cc @estebank @oli-obk This PR seems be minimal enough to allow (easier) investigation.

**Comment by tmandry** [comment]
Failed in #64646 
@bors r-

**Comment by JohnCSimon** [comment]
Ping from triage 
@nabeelomer @varkor @nathanwhit @mati865 this has sat idle for the last eight days - I see all the checks have passed, is this ready to go to review?

Thanks!

**Comment by nathanwhit** [comment]
@JohnCSimon @pnkfelix Sorry about the delay, it's been a busy week. The PR was approved but failed in rollup –– I can't replicate the error but I've got some changes that I think will fix it, should be able to push them in the next few hours, just waiting on a test build.

**Comment by nathanwhit** [comment]
Should be ready to go now I believe

**Comment by varkor** [comment]
@nathanwhit: what did you change?

**Comment by nathanwhit** [comment]
@varkor I just added the `force-host` compiletest header to the test proc_macro definition. I noticed the rollup failed on the first cross-compiled test –– I assume because proc_macro crates always have to be built be the host system. I also saw that every other test proc_macro definition included that header, which was a guiding factor.

I'm not totally sure though, so any insight is welcome!

**Comment by varkor** [comment]
@nathanwhit: ah, that sounds right to me. Thanks!

@bors r+

**Comment by pnkfelix** [comment]
[discussed](https://zulip-archive.rust-lang.org/131828tcompiler/86450weeklymeeting2019100354818.html#177250222) at rustc mtg. accepted for beta backport.
