### PR TITLE
macros: fix inert attributes from `proc_macro_derives` with `#![feature(proc_macro)]`

### LINKED ISSUE #39347: feature(proc_macro) breaks attributes on custom derive
Using `#![feature(proc_macro)]` in combination with attributes enabled by `#[proc_macro_derive(MyTrait, attributes(mycrate))]` (e.g. `#[mycrate(some_option = "something")]`) fails to compile on the current nightly with `error: macro undefined: 'mycrate!'`.

#### Definition of custom derive:
```rust
#![feature(proc_macro)]

use std::str::FromStr;

extern crate proc_macro;
use proc_macro::TokenStream;

#[proc_macro_derive(MyTrait, attributes(mycrate))]
pub fn my_macro(_: TokenStream) -> TokenStream {
    TokenStream::from_str("").unwrap()
}
```

#### Use which fails:
```rust
#![feature(proc_macro)]

#[macro_use]
extern crate proc_macro_collision;

#[derive(MyTrait)]
#[mycrate(some_option = "something")]
struct Foo;

fn main() {
}
```
If `#![feature(proc_macro)]` is removed, compilation succeeds.

Compiling the above fails with the following output:
```
error: macro undefined: 'mycrate!'
 --> examples/with.rs:7:1
  |
7 | #[mycrate(some_option = "something")]
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

Compilation fails on current nightly:
```sh
$ rustc --version --verbose
rustc 1.16.0-nightly (df8debf6d 2017-01-25)
binary: rustc
commit-hash: df8debf6d9afc431adbbd8311dcaf2b70eb9762e
commit-date: 2017-01-25
host: x86_64-apple-darwin
release: 1.16.0-nightly
LLVM version: 3.9
```

However, compilation succeeds on a week old nightly:
```sh
$ rustc --version --verbose
rustc 1.16.0-nightly (c07a6ae77 2017-01-17)
binary: rustc
commit-hash: c07a6ae77cd4ceb3cf591d34c5608ca91d1f75d4
commit-date: 2017-01-17
host: x86_64-apple-darwin
release: 1.16.0-nightly
LLVM version: 3.9
```

This is probably connected to `#[proc_macro_attribute]` which was merged in this timeframe ([PR](https://github.com/rust-lang/rust/pull/38842)), and not the feature flag itself.

<details><summary>serde_derive-based example failing the same way:</summary><p>

```rust
#![feature(proc_macro)]

#[macro_use]
extern crate serde_derive;

extern crate serde_json;

#[derive(Serialize, Deserialize, Debug)]
#[serde(deny_unknown_fields)]
struct Point {
    x: i32,
    y: i32,
}

fn main() {
    let point = Point { x: 1, y: 2 };

    // Convert the Point to a JSON string.
    let serialized = serde_json::to_string(&point).unwrap();

    // Prints serialized = {"x":1,"y":2}
    println!("serialized = {}", serialized);

    // Convert the JSON string back to a Point.
    let deserialized: Point = serde_json::from_str(&serialized).unwrap();

    // Prints deserialized = Point { x: 1, y: 2 }
    println!("deserialized = {:?}", deserialized);
}
```

</p></details>

### PR DESCRIPTION
**Pull request by jseyfried**
This PR refactors collection of `proc_macro_derive` invocations to fix #39347.

After this PR, the input to a `#[proc_macro_derive]` function no longer sees `#[derive]`s on the underlying item. For example, consider:
```rust
extern crate my_derives;
use my_derives::{Trait, Trait2};

#[derive(Copy, Clone)]
#[derive(Trait)]
#[derive(Trait2)]
struct S;
```

Today, the input to the `Trait` derive is `#[derive(Copy, Clone, Trait2)] struct S;`, and the input to the `Trait2` derive is `#[derive(Copy, Clone)] struct S;`. More generally, a `proc_macro_derive` sees all builtin derives, as well as all `proc_macro_derive`s listed *after* the one being invoked.

After this PR, both `Trait` and `Trait2` will see `struct S;`.
This is a [breaking-change], but I believe it is highly unlikely to cause breakage in practice.

r? @nrc

### CODE REVIEW

**Comment by jseyfried** [comment]
An alternative would be for `proc_macro_derive`s to see *all* builtin derives and `proc_macro_derive`s applied to the item, e.g. both `Trait` and `Trait2` would see `#[derive(Copy, Clone)] #[derive(Trait)] #[derive(Trait2)] struct S;`.

**Comment by jseyfried** [comment]
cc @keeper @abonander

File: src/libsyntax/ext/expand.rs [hunk 1]
```diff
@@ -278,13 +266,48 @@ impl<'a, 'b> MacroExpander<'a, 'b> {
             self.cx.current_expansion = invoc.expansion_data.clone();
 
             self.cx.current_expansion.mark = scope;
-            let expansion = match ext {
-                Some(ext) => self.expand_invoc(invoc, ext),
-                None => invoc.expansion_kind.dummy(invoc.span()),
+            let (expansion, new_invocations) = if let Some(ext) = ext {
```
Comment (keeperofdakeys) [inline src/libsyntax/ext/expand.rs]: This seems a bit complex, should there be a separate expand_derives function? (Two `Some(ext)`'s?)

File: src/libsyntax/ext/expand.rs [hunk 2]
```diff
@@ -672,34 +746,46 @@ impl<'a, 'b> InvocationCollector<'a, 'b> {
...
         item = item.map_attrs(|mut attrs| {
-            attr = self.cx.resolver.find_attr_invoc(&mut attrs).or_else(|| {
-                find_derive_attr(self.cx, &mut attrs)
-            });
+            if let Some(legacy_attr_invoc) = self.cx.resolver.find_legacy_attr_invoc(&mut attrs) {
+                attr = Some(legacy_attr_invoc);
+                return attrs;
+            }
+
+            traits = collect_derives(&mut self.cx, &attrs);
```
Comment (keeperofdakeys) [inline src/libsyntax/ext/expand.rs]: If there are multiple inert attributes, will `collect_derives` be called multiple times? If so, multiple derive warnings may occur.

File: src/libsyntax/ext/expand.rs [hunk 3]
```diff
@@ -332,13 +357,66 @@ impl<'a, 'b> MacroExpander<'a, 'b> {
...
+
+        let mut determined = true;
+        match self.cx.resolver.resolve_macro(scope, &path, force) {
+            Ok(ext) => return Ok(Some(ext)),
+            Err(Determinacy::Undetermined) => determined = false,
+            Err(Determinacy::Determined) if force => return Err(Determinacy::Determined),
+            _ => {}
+        }
+
+        for &(name, span) in traits {
```
Comment (keeperofdakeys) [inline src/libsyntax/ext/expand.rs]: I don't quite understand what's happening here. For each InvocKind::Attr, we have a possible instance of an insert attribute, then we loop through the traits seeing if it belongs to any invocation? And if it does, we simply add it to a dummy item, and mark it as used?

File: src/librustc_metadata/creader.rs [hunk 4]
```diff
@@ -615,10 +615,9 @@ impl<'a> CrateLoader<'a> {
                                       trait_name: &str,
                                       expand: fn(TokenStream) -> TokenStream,
                                       attributes: &[&'static str]) {
-                let attrs = attributes.iter().cloned().map(Symbol::intern).collect();
-                let derive = SyntaxExtension::ProcMacroDerive(
-                    Box::new(ProcMacroDerive::new(expand, attrs))
-                );
+                let attrs = attributes.iter().cloned().map(Symbol::intern).collect::<Vec<_>>();
+                let derive = ProcMacroDerive::new(expand, attrs.clone());
+                let derive = SyntaxExtension::ProcMacroDerive(Box::new(derive), attrs);
```
Comment (jseyfried) [inline src/librustc_metadata/creader.rs]: I could, but it would require moving more code from `libsyntax_ext` into `libsyntax`. Still might be worth it, but probably best for another PR (perf. impact is negligible).

File: src/librustc_resolve/macros.rs [hunk 5]
```diff
@@ -172,7 +176,8 @@ impl<'a> base::Resolver for Resolver<'a> {
         ImportResolver { resolver: self }.resolve_imports()
     }
 
-    fn find_attr_invoc(&mut self, attrs: &mut Vec<ast::Attribute>) -> Option<ast::Attribute> {
+    fn find_legacy_attr_invoc(&mut self, attrs: &mut Vec<ast::Attribute>)
```
Comment (jseyfried) [inline src/librustc_resolve/macros.rs]: It only resolves legacy attribute macro invocations and legacy derive invocations (i.e. attributes and derives from `#![plugin(...)]`).

File: src/librustc_resolve/macros.rs [hunk 6]
```diff
@@ -183,11 +188,50 @@ impl<'a> base::Resolver for Resolver<'a> {
...
+                        Some(..) => format!("derive_{}", traits[j].name().unwrap()),
+                        None => continue,
+                    });
+                    if !self.builtin_macros.contains_key(&legacy_name) {
+                        continue
+                    }
+                    let span = traits.remove(j).span;
+                    self.gate_legacy_custom_derive(legacy_name, span);
+                    if traits.is_empty() {
+                        attrs.remove(i);
```
Comment (jseyfried) [inline src/librustc_resolve/macros.rs]: It gets marked as used during expansion ([here](https://github.com/rust-lang/rust/blob/master/src/libsyntax/ext/expand.rs#L357)).

File: src/librustc_resolve/macros.rs [hunk 7]
```diff
@@ -183,11 +188,50 @@ impl<'a> base::Resolver for Resolver<'a> {
...
+                    } else {
+                        attrs[i].value = ast::MetaItem {
+                            name: attrs[i].name(),
+                            span: span,
```
Comment (jseyfried) [inline src/librustc_resolve/macros.rs]: Yeah, good point -- will do.

File: src/libsyntax/ext/expand.rs (hunk 1 above)
Comment (jseyfried) [inline src/libsyntax/ext/expand.rs]: Probably -- I was thinking maybe a separate `collect_derives`. I was thinking once we implement inert attribute vs macro attribute ambiguity errors (i.e. scope (b) from https://github.com/rust-lang/rust/issues/39347#issuecomment-275828264) and expanding items before derives, we'll have a better idea of how best to abstract / refactor out.

Comment (keeperofdakeys) [inline src/libsyntax/ext/expand.rs]: Ah, makes sense. I think it still deserves a comment for now at least.

File: src/libsyntax/ext/expand.rs (hunk 3 above)
Comment (jseyfried) [inline src/libsyntax/ext/expand.rs]: Yeah -- if it is an inert attribute, we mark it as known (so that it won't get collected as a `proc_macro_attribute` invocation again), add it back to underlying item (the dummy item is just a workaround for lack of easy mutable access an `Expansion`'s attributes), and put the invocation back on the work list.

File: src/libsyntax/ext/expand.rs (hunk 2 above)
Comment (jseyfried) [inline src/libsyntax/ext/expand.rs]: No -- we don't call `classify_item` again after we collect a potential `proc_macro_attribute` invocation.
If the potential `proc_macro_attribute` invocation ends up being an inert attribute, we just mutate the invocation and re-resolve it (separate from this code-path).

File: src/libsyntax/ext/expand.rs (hunk 1 above)
Comment (jseyfried) [inline src/libsyntax/ext/expand.rs]: Will do.

File: src/libsyntax/ext/expand.rs (hunk 2 above)
Comment (keeperofdakeys) [inline src/libsyntax/ext/expand.rs]: I don't think I quite understand. What's the final `for` loop needed for?

**Comment by nrc** [comment]
cc @alexcrichton I feel like this discussion has come up before in the macros 1.1 process.

**Comment by jseyfried** [comment]
Yeah, c.f. https://github.com/rust-lang/rust/issues/35900#issuecomment-252430957 and #37067.

File: src/libsyntax/ext/base.rs [hunk 8]
```diff
@@ -514,7 +514,7 @@ pub enum SyntaxExtension {
     /// The input is the annotated item.
     /// Allows generating code to implement a Trait for a given struct
     /// or enum item.
-    ProcMacroDerive(Box<MultiItemModifier>),
+    ProcMacroDerive(Box<MultiItemModifier>, Vec<Symbol>),
```
Comment (nrc) [inline src/libsyntax/ext/base.rs]: Could you comment on the additional arg please?

**Review by nrc — APPROVED** [review]
r=me with the added comment, but I'd like to give Alex a chance to see this before merging

**Comment by jseyfried** [comment]
IIRC, #37067 was written when `proc_macro_derive`s could modify the underlying item, so neither the current solution in this PR nor the solution from https://github.com/rust-lang/rust/pull/39572#issuecomment-277559539 were possible.

File: src/libsyntax/ext/base.rs (hunk 8 above)
Comment (jseyfried) [inline src/libsyntax/ext/base.rs]: Will do.

**Comment by alexcrichton** [comment]
Yeah I think that the current behavior made more sense when custom derive could alter the item itself, but nowadays where it can't then this looks good to me!

(I can't think of any problems at least)

**Comment by keeperofdakeys** [comment]
Did you fix the span issue in  `find_legacy_attr_invoc`?

**Comment by jseyfried** [comment]
@keeperofdakeys [Yeah](https://github.com/rust-lang/rust/pull/39572/files#diff-65e622b139849f973138aa676f421f3bR217).
@bors r=nrc

**Comment by nikomatsakis** [comment]
I'm tagging this as relnotes since the there is certainly a change in behavior here.
