### PR TITLE
Fix automatic urls with backticks

### LINKED ISSUE #49164: Backticked Implied Shortcut Reference Links don't render correctly
```Rust
pub struct Foo;

/// Reference to [Foo]. Code-styled reference to [`Foo`].
pub struct Bar;

```

renders as:

`rustdoc 1.26.0-nightly (5508b2714 2018-03-18)`

Ref #43466 , https://github.com/rust-lang/rust/pull/48335#issuecomment-369147071

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Fixes #49164.

r? @QuietMisdreavus

### CODE REVIEW

File: src/librustdoc/clean/mod.rs [hunk 1]
```diff
@@ -1091,12 +1092,13 @@ impl Clean<Attributes> for [ast::Attribute] {
...
             let dox = attrs.collapsed_doc_value().unwrap_or_else(String::new);
-            for link in markdown_links(&dox) {
+            for ori_link in markdown_links(&dox) {
                 // bail early for real links
-                if link.contains('/') {
+                if ori_link.contains('/') {
                     continue;
                 }
-                let (def, fragment)  = {
+                let link = ori_link.replace("`", "");
```
Comment (QuietMisdreavus) [inline src/librustdoc/clean/mod.rs]: Some part of me wants this to be a `trim_matches` instead of a `replace`, but in practice it won't matter.

**Review by QuietMisdreavus — APPROVED** [review]
