### PR TITLE
ensure compiler existance of tools on the dist step

### LINKED ISSUE #138778: `./x dist --stage 2 $tool` broken after #138224
Creating distribution tarballs of tools with `./x dist --stage 2 $tool` broke after #138224. We (Ferrocene) know it fails at least with rustfmt and clippy. From what I can see, it stopped building the stage1 library, causing that failure.

<details><summary>Build log before the PR got merged:</summary>

```
Building bootstrap
    Finished `dev` profile [unoptimized] target(s) in 0.07s
Building stage0 library artifacts (x86_64-unknown-linux-gnu)
    Finished `release` profile [optimized] target(s) in 0.05s
Building compiler artifacts (stage0 -> stage1, x86_64-unknown-linux-gnu)
    Finished `release` profile [optimized] target(s) in 0.26s
Creating a sysroot for stage1 compiler (use `rustup toolchain link 'name' build/host/stage1`)
Building stage0 tool lld-wrapper (x86_64-unknown-linux-gnu)
    Finished `release` profile [optimized] target(s) in 0.12s
Building stage1 library artifacts (x86_64-unknown-linux-gnu)
    Finished `release` profile [optimized] target(s) in 0.03s
Building compiler artifacts (stage1 -> stage2, x86_64-unknown-linux-gnu)
    Finished `release` profile [optimized] target(s) in 0.24s
Building tool clippy-driver (stage1 -> stage2, x86_64-unknown-linux-gnu)
   Compiling clippy v0.1.87 (/home/pietro/r/github/rust-lang/rust/master/src/tools/clippy)
   Compiling clippy_lints v0.1.87 (/home/pietro/r/github/rust-lang/rust/master/src/tools/clippy/clippy_lints)
```

</details>

<details><summary>Build log after the PR got merged:</summary>

```
Building bootstrap
   Compiling bootstrap v0.0.0 (/home/pietro/r/github/rust-lang/rust/master/src/bootstrap)
    Finished `dev` profile [unoptimized] target(s) in 5.83s
Building stage0 library artifacts (x86_64-unknown-linux-gnu)
    Finished `release` profile [optimized] target(s) in 0.10s
Building compiler artifacts (stage0 -> stage1, x86_64-unknown-linux-gnu)
    Finished `release` profile [optimized] target(s) in 0.33s
Creating a sysroot for stage1 compiler (use `rustup toolchain link 'name' build/host/stage1`)
Building stage0 tool lld-wrapper (x86_64-unknown-linux-gnu)
    Finished `release` profile [optimized] target(s) in 0.20s
Building tool clippy-driver (stage1 -> stage2, x86_64-unknown-linux-gnu)
   Compiling proc-macro2 v1.0.93
   Compiling unicode-ident v1.0.14
   Compiling serde v1.0.217
   Compiling stable_deref_trait v1.2.0
   Compiling litemap v0.7.4
   Compiling writeable v0.5.5
   Compiling smallvec v1.13.2
   Compiling icu_locid_transform_data v1.5.0
   Compiling icu_properties_data v1.5.0
   Compiling utf8_iter v1.0.4
   Compiling equivalent v1.0.1
   Compiling write16 v1.0.0
   Compiling icu_normalizer_data v1.5.0
   Compiling utf16_iter v1.0.5
   Compiling hashbrown v0.15.2
   Compiling rustc_apfloat v0.2.2+llvm-462a31f5a5ab
error[E0463]: can't find crate for `std`
  |
  = note: the `x86_64-unknown-linux-gnu` target may not be installed
  = help: consider adding the standard library to the sysroot with `x build library --target x86_64-unknown-linux-gnu`
  = help: consider building the standard library from source with `cargo build -Zbuild-std`

For more information about this error, try `rustc --explain E0463`.
error[E0463]: can't find crate for `core`
  |
  = note: the `x86_64-unknown-linux-gnu` target may not be installed
  = help: consider adding the standard library to the sysroot with `x build library --target x86_64-unknown-linux-gnu`
  = help: consider building the standard library from source with `cargo build -Zbuild-std`

error: could not compile `proc-macro2` (build script) due to 1 previous error
warning: build failed, waiting for other jobs to finish...
error: could not compile `unicode-ident` (lib) due to 1 previous error
error: could not compile `serde` (build script) due to 1 previous error
error: could not compile `icu_locid_transform_data` (lib) due to 1 previous error
error: could not compile `litemap` (lib) due to 1 previous error
error: could not compile `stable_deref_trait` (lib) due to 1 previous error
error: could not compile `icu_properties_data` (lib) due to 1 previous error
error: could not compile `write16` (lib) due to 1 previous error
error: could not compile `equivalent` (lib) due to 1 previous error
error: could not compile `utf8_iter` (lib) due to 1 previous error
error: could not compile `writeable` (lib) due to 1 previous error
error: could not compile `smallvec` (lib) due to 1 previous error
error: could not compile `icu_normalizer_data` (lib) due to 1 previous error
error: could not compile `utf16_iter` (lib) due to 1 previous error
error: could not compile `rustc_apfloat` (build script) due to 1 previous error
error: could not compile `hashbrown` (lib) due to 1 previous error
Build completed unsuccessfully in 0:00:08
```
</details>

### PR DESCRIPTION
**Pull request by onur-ozkan**
Fixes https://github.com/rust-lang/rust/issues/138778 with a coverage on https://github.com/rust-lang/rust/issues/138123 and https://github.com/rust-lang/rust/issues/138004.

try-job: dist-powerpc64le-linux

### CODE REVIEW

File: src/bootstrap/src/core/build_steps/dist.rs [hunk 1]
```diff
@@ -421,13 +421,13 @@ impl Step for Rustc {
                 builder.install(&rustdoc, &image.join("bin"), FileType::Executable);
             }
 
+            let ra_proc_macro_srv_compiler =
+                builder.compiler_for(compiler.stage, builder.config.build, compiler.host);
+            builder.ensure(compile::Rustc::new(ra_proc_macro_srv_compiler, compiler.host));
```
Comment (Kobzol) [inline src/bootstrap/src/core/build_steps/dist.rs:426]: Doesn't this now build the compiler for the proc macro server even if `tool::RustAnalyzerProcMacroSrv` should not actually be built? :thinking: It's not always enabled.

Comment (onur-ozkan) [reply src/bootstrap/src/core/build_steps/dist.rs:426]: Compiler is passed before the condition here so I'm not sure how to guard against that without applying ugly hacks. Also, in practice, I don't think we ever hit the case of "trying to build `RustAnalyzerProcMacroSrv` while the compiler isn't compiled/ready for use".

Comment (Kobzol) [reply src/bootstrap/src/core/build_steps/dist.rs:426]: Ok, fair enough.

**Comment by Kobzol** [comment]
@borstry

**Comment by onur-ozkan** [comment]
Why do you expect this PR to reduce executed steps? It's not the goal here.

**Comment by Kobzol** [comment]
I thought that this was also a fix for https://github.com/rust-lang/rust/issues/138123. So this PR adds a test to make sure that the fix for https://github.com/rust-lang/rust/issues/138778 doesn't regress https://github.com/rust-lang/rust/issues/138123?

**Comment by onur-ozkan** [comment]
Yeah.

**Comment by Kobzol** [comment]
I see. Hmm, I don't like this approach though, it's super brittle. The fact that we have to sprinkle these ensure calls sucks. Could we instead move the `Rustc` build into `ToolBuild::run` to solve this at a single place?

**Comment by onur-ozkan** [comment]
There is no simple solution we can do in `ToolBuild::run`. Steps with `ensure(Rustc...)` rely on `compiler_for`, which sets `forced_compiler` to true. When `forced_compiler` is true, we expect that compiler to be available. We could try something to handle this in `ToolBuild::run` but it would be a magical hack/workaround instead of a solution. The reason I didn't go to that path was because this change makes it obvious and we do a lot of `ensure` stuff almost every part of bootstrap.

**Comment by Kobzol** [comment]
> magical hack/workaround instead of a solution

Well, I would argue that adding `ensure` at a bunch of places in bootstrap is a hack, rather than solving this at a single location (it's fine as a hotfix though, ofc). Maybe I'm missing something, but it seems like the `ensure` is always called with the same `compiler` and `target` parameters that are then passed to the tool being built. Why can't the tool build step invoke `ensure(Rustc)` with these same parameters? It already does ensure `Rustc/Std` in various ways based on the tool mode.

So why are these specific tools for which you added `ensure` in this PR special and we cannot handle them through the usual code in `ToolBuild`? Requiring `ensure` for only some tools or under some conditions, without at least documenting why is it needed, is brittle, and is likely to break in the future, IMO.

**Comment by Kobzol** [comment]
> If you want to fix this in a different way, you would either re-write/remove compiler_for functions, or change the forced_compiler conditions, and to me both have potential of breaking things in the future or even now (like doing extra calls unnecessarily and stuff).

Yeah, I have that in my TODO list, because the current system makes it too easy to make a mistake. But it will be quite hard to modify. And it shouldn't happen before the stage 0 redesign lands anyway :)

Anyway, you can r=me, there's no need to block this fix PR on a larger refactoring.
