### PR TITLE
fix dynamic size/align computation logic for packed types with dyn trait tail

### LINKED ISSUE #80925: Accessing DST field of packed struct calculates the wrong field address
Execute with Miri:

https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=7e7d31feebbea4c3caceaccff1fa6bac

The problem is that https://github.com/rust-lang/rust/blob/6526e5c772f2da07db745c94ca6bb0a591a39ba4/compiler/rustc_codegen_ssa/src/mir/place.rs#L181-L182 and https://github.com/rust-lang/rust/blob/6526e5c772f2da07db745c94ca6bb0a591a39ba4/compiler/rustc_mir/src/interpret/place.rs#L413 do not take the reduced field alignment into account and calculate the offset as-if the standard alignment was in place.

### PR DESCRIPTION
**Pull request by RalfJung**
This logic was never updated to support `packed(N)` where `N > 1`, and it turns out to be wrong for that case.

Fixes https://github.com/rust-lang/rust/issues/80925

@bjorn3 I have not looked at cranelift; I assume it basically copied the size-of-val logic and hence could use much the same patch.

### CODE REVIEW

**Comment by petrochenkov** [comment]
r? compiler
I'm overloaded with reviews.

**Comment by petrochenkov** [comment]
r? compiler
b-naber doesn't do reviews.

File: compiler/rustc_codegen_ssa/src/glue.rs [hunk 1]
```diff
@@ -59,37 +59,41 @@ pub fn size_and_align_of_dst<'a, 'tcx, Bx: BuilderMethods<'a, 'tcx>>(
...
-
-            // Packed types ignore the alignment of their fields.
+            // Packed type alignment would have to be capped, but their tails always have known alignment.
+            // Therefore, their alignment has already been taken into account when computing `sized_align`
+            // and `unsized_offset_unadjusted`, so no further adjustment is needed.
             if let ty::Adt(def, _) = t.kind() {
                 if def.repr().packed() {
+                    let unsized_tail =
+                        bx.tcx().struct_tail_with_normalize(field_ty, |ty| ty, || {});
+                    assert!(matches!(unsized_tail.kind(), ty::Slice(..) | ty::Str));
```
Comment (WaffleLapkin) [inline compiler/rustc_codegen_ssa/src/glue.rs:85]: I think this is not right. Won't this ICE for code like [this](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=17cef827f7b733af4d0eb7e9cab0ccf1):

```rust
#[repr(C, packed)]
struct Packed<T: ?Sized>(u8, core::mem::ManuallyDrop<T>);

let p = Packed(0, core::mem::ManuallyDrop::new(1));
let p: &Packed<usize> = &p;
let p: &Packed<dyn Send> = p;
dbg!(core::mem::size_of_val(p), core::mem::align_of_val(p));
```
?

Comment (RalfJung) [reply compiler/rustc_codegen_ssa/src/glue.rs:85]: Hm, if such code is accepted then it would currently just compute the wrong offset for that code. An ICE would still be an improvement. ;)

I'll play around with examples that involve `ManuallyDrop` to see if there's a bug here, thanks!

Comment (WaffleLapkin) [reply compiler/rustc_codegen_ssa/src/glue.rs:85]: > - There is no justification for why packed types ignore the alignment of their fields. This is correct only because it is impossible to write a packed struct with `dyn Trait` tail, i.e., unsized packed structs always have statically known alignment. (With slices, the size is dynamic but the alignment is static; only with `dyn Trait` do we have both dynamic size and alignment.)

I don't think that's correct, given the example above? And either way, packed structs always ignore the alignment of their fields, don't they? I don't think `Packed<dyn Send>`'s size (or alignment) depends on the alignment of `.0`.

Comment (RalfJung) [reply compiler/rustc_codegen_ssa/src/glue.rs:85]: > packed structs always ignore the alignment of their fields, don't they? 

No they don't. Remember we have `#[packed(4)]`. The alignment of the fields in that struct is  `min(natural_field_align, 4)`.

Comment (WaffleLapkin) [reply compiler/rustc_codegen_ssa/src/glue.rs:85]: Right, the alignment should only be ignored if `packedness = 1`. The bug is trivial to trigger then, yikes: https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=80f13045af7f1dd52cf6c79ee2897829

Comment (RalfJung) [reply compiler/rustc_codegen_ssa/src/glue.rs:85]: Yes indeed.

We also forgot to fixup the offset computation logic, I fixed that recently in https://github.com/rust-lang/rust/pull/118540. I thought size computation wouldn't be affected since I was unable to construct a packed struct with a dyn-typed tail, but you managed to bring in that missing piece.

Comment (WaffleLapkin) [reply compiler/rustc_codegen_ssa/src/glue.rs:85]: I was also made aware of https://github.com/rust-lang/rust/issues/80925, did https://github.com/rust-lang/rust/pull/118540 fix that one? (I can't reproduce miri failure anymore)

Comment (RalfJung) [reply compiler/rustc_codegen_ssa/src/glue.rs]: Yeah for offsets, https://github.com/rust-lang/rust/pull/118540 removed all special cases for packed types, so they are now handled properly.

Comment (RalfJung) [reply compiler/rustc_codegen_ssa/src/glue.rs]: I updated the PR to fix this, and added tests.

**Review by WaffleLapkin — APPROVED** [review]
Thanks!
