### PR TITLE
Detect tuple variants used as struct pattern and suggest correct pattern

### LINKED ISSUE #61326: Handle `Foo { a: usize, b: usize }` used as `Foo(1, 2)` gracefully
Given the code

https://github.com/rust-lang/rust/blob/3592079765d4d76f19b3a9501de5f8cc47f11a04/src/test/ui/parser/recover-from-bad-variant.rs#L1-L14

we emit

https://github.com/rust-lang/rust/blob/3592079765d4d76f19b3a9501de5f8cc47f11a04/src/test/ui/parser/recover-from-bad-variant.stderr#L1-L21

We should emit something closer to

```
error: expected type, found `3`
  --> $DIR/recover-from-bad-variant.rs:7:26
   |
LL |     let x = Enum::Foo(a: 3, b: 4);
   |                          ^ expecting a type here because of type ascription

error[E0532]: expected tuple struct/variant, found struct variant `Enum::Foo`
  --> $DIR/recover-from-bad-variant.rs:10:9
   |
LL |         Enum::Foo(a, b) => {}
   |         ^^^^^^^^^ did you mean `Enum::Foo { a, b }`?

error: aborting due to 2 previous errors
```

### PR DESCRIPTION
**Pull request by estebank**
Fix #61326

r? @petrochenkov

### CODE REVIEW

File: src/librustc_resolve/late/diagnostics.rs [hunk 1]
```diff
@@ -683,7 +683,16 @@ impl<'a> LateResolutionVisitor<'a, '_, '_> {
                 if let Some(span) = self.r.opt_span(def_id) {
                     err.span_label(span, &format!("`{}` defined here", path_str));
                 }
-                err.span_label(span, format!("did you mean `{}( /* fields */ )`?", path_str));
+                let fields = match self.r.field_names.get(&def_id) {
```
Comment (petrochenkov) [inline src/librustc_resolve/late/diagnostics.rs:686]:
```suggestion
                let fields = self.r.field_names.get(&def_id).map_or("/* fields */", |fields| vec!["_", fields.len()].join(", "));
```

**Comment by petrochenkov** [comment]
r=me with the cleanup applied.

**Comment by estebank** [comment]
@petrochenkov Will do, but I am at a loss of an alternate way to accomplish [this following change](https://github.com/rust-lang/rust/pull/74005/commits/3b56e915fc0f3ef7b7bce7901ee253e0ae49ab64).

File: src/librustc_resolve/late/diagnostics.rs (hunk 1 above)
Comment (estebank) [reply src/librustc_resolve/late/diagnostics.rs:686]: I had to do `.map_or("/* fields */".to_string(), ..` because `join` gives back a `String`, but otherwise applied.

**Comment by petrochenkov** [comment]
Two tests failed on CI.

**Comment by petrochenkov** [comment]
Failed due to https://github.com/rust-lang/rust/pull/75450.
@bors retry

File: src/librustc_resolve/late/diagnostics.rs [hunk 2]
```diff
@@ -701,7 +701,16 @@ impl<'a> LateResolutionVisitor<'a, '_, '_> {
                 if let Some(span) = self.def_span(def_id) {
                     err.span_label(span, &format!("`{}` defined here", path_str));
                 }
-                err.span_label(span, format!("did you mean `{}( /* fields */ )`?", path_str));
+                let fields =
+                    self.r.field_names.get(&def_id).map_or("/* fields */".to_string(), |fields| {
```
Comment (lzutao) [inline src/librustc_resolve/late/diagnostics.rs:705]:
```diff
-.map_or("/* fields */".to_string()
+.map_or_else(|| "/* fields */".to_string()
```
