### PR TITLE
various clippy fixes

### LINKED ISSUE #121481: x.py clippy argument passing broken, order no loger preserved
https://github.com/rust-lang/rust/blob/master/src/bootstrap/src/core/build_steps/check.rs#L66

apparently we now  group the args passed to `x.py clippy` by lint level (allow, deny, etc) and then send group by group to the clippy command.

This is bad because you can no longer turn on/off single lints, for example `x.py clippy -Aclippy:all -Wclippy::style -Aclippy::foo1 -Aclippy::foo2` used to only  turn on style lints with the exception of `foo1` and `foo2`.

The order is no longer preserved
```rust
        args.extend(strings(&["--", "--cap-lints", "warn"]));
        args.extend(ignored_lints.iter().map(|lint| format!("-Aclippy::{}", lint)));
        let mut clippy_lint_levels: Vec<String> = Vec::new();
        allow.iter().for_each(|v| clippy_lint_levels.push(format!("-A{}", v)));
        deny.iter().for_each(|v| clippy_lint_levels.push(format!("-D{}", v)));
        warn.iter().for_each(|v| clippy_lint_levels.push(format!("-W{}", v)));
        forbid.iter().for_each(|v| clippy_lint_levels.push(format!("-F{}", v)));
        args.extend(clippy_lint_levels);
        args.extend(builder.config.free_args.clone());
 ```
 which would now become `-Aclippy::all -Aclippy::foo1 -Aclippy::foo2 -Wclippy::style` which kind of defeats the purpose of being able to setting specific lints to allow/warn.

### PR DESCRIPTION
**Pull request by onur-ozkan**
We need to keep the order of the given clippy lint rules before passing them.
Since clap doesn't offer any useful interface for this purpose out of the box,
we have to handle it manually.

Additionally, this PR makes `-D` rules work as expected. Previously, lint rules were limited to `-W`. By enabling `-D`, clippy began to complain numerous lines in the tree, all of which have been resolved in this PR as well.

Fixes #121481
cc @matthiaskrgr

### CODE REVIEW

**Comment by matthiaskrgr** [comment]
Looks good so far :) thanks!
Side note: it seems that -D and -F do not have any effect, probably due to `--cap-lints warn` which we also pass?

**Comment by onur-ozkan** [comment]
Now clippy complains a lot of stuff because the `-D` rules has never been functional before. I will switch back this PR to `S-waiting-on-review` label once I resolve the lint errors in the tree.

File: compiler/rustc_metadata/src/rmeta/encoder.rs [hunk 1]
```diff
@@ -2200,10 +2200,12 @@ impl<D: Decoder> Decodable<D> for EncodedMetadata {
         let len = d.read_usize();
         let mmap = if len > 0 {
             let mut mmap = MmapMut::map_anon(len).unwrap();
+            let mut num_bytes = 0;
             for _ in 0..len {
-                (&mut mmap[..]).write(&[d.read_u8()]).unwrap();
+                num_bytes += (&mut mmap[..]).write(&[d.read_u8()]).unwrap();
             }
             mmap.flush().unwrap();
+            debug_assert!(len == num_bytes);
```
Comment (onur-ozkan) [inline compiler/rustc_metadata/src/rmeta/encoder.rs:2208]: Does this seem useful? Should I keep it or revert it? :thinking:

File: compiler/rustc_const_eval/src/interpret/intern.rs [hunk 2]
```diff
@@ -287,7 +287,9 @@ pub fn intern_const_alloc_for_constprop<
         return Ok(());
     }
     // Move allocation to `tcx`.
-    for _ in intern_shallow(ecx, alloc_id, Mutability::Not).map_err(|()| err_ub!(DeadLocal))? {
+    if let Some(_) =
+        (intern_shallow(ecx, alloc_id, Mutability::Not).map_err(|()| err_ub!(DeadLocal))?).next()
+    {
```
Comment (oli-obk) [inline compiler/rustc_const_eval/src/interpret/intern.rs:292]: This is wrong. We don't check all elements anymore, only the first one

File: compiler/rustc_metadata/src/rmeta/encoder.rs (hunk 1 above)
Comment (oli-obk) [reply compiler/rustc_metadata/src/rmeta/encoder.rs:2208]: Can we use write_all instead (or whatever that was called that ensures the entire slice is written)

File: compiler/rustc_middle/src/hir/map/mod.rs [hunk 3]
```diff
@@ -114,20 +114,19 @@ impl<'hir> Iterator for ParentOwnerIterator<'hir> {
         if self.current_id == CRATE_HIR_ID {
             return None;
         }
-        loop {
-            // There are nodes that do not have entries, so we need to skip them.
-            let parent_id = self.map.def_key(self.current_id.owner.def_id).parent;
```
Comment (oli-obk) [inline compiler/rustc_middle/src/hir/map/mod.rs:117]: Something is fishy here. At minimum comments need updating

File: compiler/rustc_const_eval/src/interpret/intern.rs (hunk 2 above)
Comment (onur-ozkan) [reply compiler/rustc_const_eval/src/interpret/intern.rs:292]: > We don't check all elements anymore, only the first one

That's what we do here.

File: compiler/rustc_middle/src/hir/map/mod.rs (hunk 3 above)
Comment (onur-ozkan) [reply compiler/rustc_middle/src/hir/map/mod.rs:117]: Since https://github.com/onur-ozkan/rust/commit/667d5d325f7657e5cdf1cade84e2602c5ebb9a8d, we no longer skip nodes. Removing the comments should be fine I guess?

File: compiler/rustc_const_eval/src/interpret/intern.rs (hunk 2 above)
Comment (oli-obk) [reply compiler/rustc_const_eval/src/interpret/intern.rs:296]: Yea, what I mean is that before this PR we checked all elements

Comment (onur-ozkan) [reply compiler/rustc_const_eval/src/interpret/intern.rs:296]: Isn't [this panic](https://github.com/onur-ozkan/rust/blob/774ae599aba35f7b323e77be88923b8f476ee783/compiler/rustc_const_eval/src/interpret/intern.rs#L294-L298) stop the iteration at the first element?

Comment (oli-obk) [reply compiler/rustc_const_eval/src/interpret/intern.rs:296]: Oh.. I somehow hallucinated a different behaviour.

File: compiler/rustc_middle/src/mir/interpret/mod.rs [hunk 4]
```diff
@@ -671,11 +671,11 @@ pub fn read_target_uint(endianness: Endian, mut source: &[u8]) -> Result<u128, i
     // So we do not read exactly 16 bytes into the u128, just the "payload".
     let uint = match endianness {
         Endian::Little => {
-            source.read(&mut buf)?;
+            let _ = source.read(&mut buf)?;
```
Comment (oli-obk) [inline compiler/rustc_middle/src/mir/interpret/mod.rs:674]: read_exact here, too?

File: compiler/stable_mir/src/mir/alloc.rs [hunk 5]
```diff
@@ -57,11 +57,11 @@ pub(crate) fn read_target_uint(mut bytes: &[u8]) -> Result<u128, Error> {
     let mut buf = [0u8; std::mem::size_of::<u128>()];
     match MachineInfo::target_endianess() {
         Endian::Little => {
-            bytes.read(&mut buf)?;
+            let _ = bytes.read(&mut buf)?;
```
Comment (oli-obk) [inline compiler/stable_mir/src/mir/alloc.rs:60]: And here

File: compiler/stable_mir/src/mir/alloc.rs [hunk 6]
```diff
@@ -72,11 +72,11 @@ pub(crate) fn read_target_int(mut bytes: &[u8]) -> Result<i128, Error> {
     let mut buf = [0u8; std::mem::size_of::<i128>()];
     match MachineInfo::target_endianess() {
         Endian::Little => {
-            bytes.read(&mut buf)?;
+            let _ = bytes.read(&mut buf)?;
```
Comment (oli-obk) [inline compiler/stable_mir/src/mir/alloc.rs:75]: And here

File: compiler/rustc_middle/src/mir/interpret/mod.rs (hunk 4 above)
Comment (onur-ozkan) [reply compiler/rustc_middle/src/mir/interpret/mod.rs:674]: I already tried that and got failures in CI https://github.com/rust-lang/rust/actions/runs/8307751008/job/22737303335#step:27:1679. And that actually makes sense as trying to fill entire `[0u8; std::mem::size_of::<u128>()]` will fail for most cases.

Comment (oli-obk) [reply compiler/rustc_middle/src/mir/interpret/mod.rs:674]: right, you need to use the same `[16 - source.len()..]` logic used in the `Endian::Big` branch (or even better, move that logic before the `match endianess`

Comment (onur-ozkan) [reply compiler/rustc_middle/src/mir/interpret/mod.rs:674]: I believe this is to cover the logic for the "most significant byte" and we shouldn't do the same in `Little` branch.

Comment (oli-obk) [reply compiler/rustc_middle/src/mir/interpret/mod.rs:674]: Ah makes sense. Then you need to slice `..source.len()` before using `read_exact`

Tho maybe we should just use one of the slice copying functions instead of using the Read trait

File: compiler/rustc_middle/src/mir/interpret/mod.rs [hunk 7]
```diff
@@ -668,14 +668,15 @@ pub fn write_target_uint(
 pub fn read_target_uint(endianness: Endian, mut source: &[u8]) -> Result<u128, io::Error> {
     // This u128 holds an "any-size uint" (since smaller uints can fits in it)
     let mut buf = [0u8; std::mem::size_of::<u128>()];
+    let start_position = 16 - source.len();
     // So we do not read exactly 16 bytes into the u128, just the "payload".
     let uint = match endianness {
         Endian::Little => {
-            let _ = source.read(&mut buf)?;
+            source.read_exact(&mut buf[..start_position])?;
```
Comment (oli-obk) [inline compiler/rustc_middle/src/mir/interpret/mod.rs:675]: Shouldn't it be

```suggestion
            source.read_exact(&mut buf[..source.len()])?;
```

Comment (onur-ozkan) [reply compiler/rustc_middle/src/mir/interpret/mod.rs]: yeah was my bad, corrected it
