### PR TITLE
Deny const auto traits

### LINKED ISSUE #149285: We don't reject const auto traits
Auto traits are just markers, mere flags. Marking them const doesn't serve much purpose. If you're longing for `AutoBound` vs. `const AutoBound`, just introduce another auto trait: `AutoBound` vs. `AnotherAutoBound`. The utility of `[const] AutoBound` is also questionable to me.

Moreover, today, the constness of auto traits doesn't "propagate" (i.e., built-in auto trait impl candidates are always non-const), so one can't actually benefit from the autoness of the const trait. We should keep it that way IMO, not sure if anybody would disagree.

As an aside, we currently intentionally panic in the next-gen solver when trying to prove a host effect predicate where the corresp. trait is auto:

```rs
// -Znext-solver
#![feature(auto_traits, const_trait_impl)]

const auto trait Marker {}

fn scope() {
    fn check<T: const Marker>() {}
    check::<()>();
}
```

```
thread 'rustc' (6486) panicked at /rustc-dev/c23ed3ef28b3cc30658310f771ddc66e5b687cf4/compiler/rustc_next_trait_solver/src/solve/effect_goals.rs:195:9:
internal error: entered unreachable code: auto traits are never const
```

Just opening this so we don't lose track of this.

### PR DESCRIPTION
**Pull request by lapla-cogito**
close rust-lang/rust#149285

The AST validation now detects and rejects const auto traits. Additionally, I updated an existing test that was using `const unsafe auto trait`.

r? fmease

### CODE REVIEW

File: tests/ui/traits/const-traits/parse-const-unsafe-trait.rs
Comment (fmease) [inline tests/ui/traits/const-traits/parse-const-unsafe-trait.rs:1]: This test is meant to exercise the parser ensuring that we correctly detect trait declarations even if the "frontmatter" (the list of qualifiers) is large (since qualifier parsing is quite intricate, cc https://github.com/rust-lang/rust/issues/146122).

Strictly speaking, the `const-auto-trait.rs` you've added doesn't ensure that const auto traits remain syntactically valid.

So IMO we should keep the `const … auto` traits but add the following:

```diff
+ //@ compile-flags: -Zparse-crate-root-only
  //@ check-pass
```

Alternatively, you could make the following change:

```diff
- pub const unsafe auto trait UwU {}
- const unsafe auto trait Uwu {}
+ #[cfg(false)] pub const unsafe auto trait UwU {}
+ #[cfg(false)] const unsafe auto trait Uwu {}
```

Both options would make rustc only *parse* these items skipping semantic analysis incl. AST validation entirely.

File: compiler/rustc_ast_passes/src/ast_validation.rs [hunk 1]
```diff
@@ -820,6 +820,12 @@ impl<'a> AstValidator<'a> {
         self.dcx().emit_err(errors::ModuleNonAscii { span: ident.span, name: ident.name });
     }
 
+    fn deny_const_auto_traits(&self, constness: &Const) {
+        if let Const::Yes(span) = constness {
+            self.dcx().emit_err(errors::ConstAutoTrait { span: *span });
```
Comment (fmease) [inline compiler/rustc_ast_passes/src/ast_validation.rs]: (minor) `ast::Const` is `Copy`

```suggestion
    fn deny_const_auto_traits(&self, constness: Const) {
        if let Const::Yes(span) = constness {
            self.dcx().emit_err(errors::ConstAutoTrait { span });
```

File: tests/ui/traits/const-traits/const-auto-trait.stderr [hunk 2]
```diff
@@ -0,0 +1,10 @@
+error: auto traits cannot be const
+  --> $DIR/const-auto-trait.rs:3:1
+   |
+LL | const auto trait Marker {}
+   | ^^^^^
+   |
+   = help: remove the `const` keyword
```
Comment (fmease) [inline tests/ui/traits/const-traits/const-auto-trait.stderr:7]: We could provide a structured suggestion but yeah, it's not really worth the effort.

**Review by fmease — APPROVED** [review]

**Comment by fmease** [comment]
Thanks! Two small nitpicks

File: tests/ui/traits/const-traits/parse-const-unsafe-trait.rs
Comment (lapla-cogito) [reply tests/ui/traits/const-traits/parse-const-unsafe-trait.rs:1]: Thanks! Since the test file name clearly indicates parsing as the primary purpose of the test, I adopted the former one.

File: compiler/rustc_ast_passes/src/ast_validation.rs (hunk 1 above)
Comment (lapla-cogito) [reply compiler/rustc_ast_passes/src/ast_validation.rs]: Fixed.

File: tests/ui/traits/const-traits/const-auto-trait.stderr (hunk 2 above)
Comment (lapla-cogito) [reply tests/ui/traits/const-traits/const-auto-trait.stderr:7]: I initially thought about that, but decided not to, mainly because not every suggestion can be fixed automatically with rustfix, for example the code sample in the original issue that triggers a panic in next-gen solvers, and because we don't really have anything meaningful to add beyond what the current message already communicates.

Comment (fmease) [reply tests/ui/traits/const-traits/const-auto-trait.stderr:7]: Ah, the next-gen solver still crashes despite this change? Right, of course.

I guess we should replace the `unreachable!(…)` in `consider_auto_trait_candidate` of `HostEffectPredicate` with a `cx.delay_bug`. Sorry, I forgot about that.

Comment (lapla-cogito) [reply tests/ui/traits/const-traits/const-auto-trait.stderr:7]: Ah, that’s a bit different from what I was aiming to accomplish in this PR, so I had planned to handle it in a follow-up PR instead (though I should have mentioned that). But since integrating the tests is straightforward, I’ve decided to include it in this PR as well: https://github.com/rust-lang/rust/pull/149307/commits/c80ab42ee6e95cf6ebe3b692b804eca314a2cd26
