### PR TITLE
linker: Create GNU_EH_FRAME header by default when producing ELFs

### LINKED ISSUE #73451: Panic aborts under rust-lld + musl
This aborts when built with rust-lld + musl on stable and nightly:

```rust
fn main() {
    panic!();
}
```

```text
$ rustc --target x86_64-unknown-linux-musl main.rs && ./main
thread 'main' panicked at 'explicit panic', main.rs:2:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

```text
$ rustc --target x86_64-unknown-linux-musl -C linker=rust-lld main.rs && ./main
thread 'main' panicked at 'explicit panic', main.rs:2:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
fatal runtime error: failed to initiate panic, error 5
Aborted (core dumped)
```

### PR DESCRIPTION
**Pull request by petrochenkov**
Do it in a centralized way in `link.rs` instead of individual target specs.

The opt-out is `-Clink-arg=(-Wl,)--no-eh-frame-hdr` if necessary.

Fixes https://github.com/rust-lang/rust/issues/73451
cc https://github.com/rust-lang/rust/pull/73483

### CODE REVIEW

**Comment by petrochenkov** [comment]
Some questions:
- Can we skip creating this header in panic=abort mode?
(Can we link to non-Rust libraries that unwind in panic=abort mode?)
- If the answer to the first question is "no", then the header will be created for embedded targets as well. Whether they want it?

File: src/librustc_codegen_ssa/back/linker.rs [hunk 1]
```diff
@@ -614,6 +615,18 @@ impl<'a> Linker for GccLinker<'a> {
             }
         }
     }
+
+    // Add the `GNU_EH_FRAME` program header which is required to locate unwinding information.
+    // Some versions of `gcc` add it implicitly, some (e.g. `musl-gcc`) don't,
+    // so we just always add it.
+    fn add_eh_frame_header(&mut self) {
+        // The condition here is "uses ELF" basically.
```
Comment (Amanieu) [inline src/librustc_codegen_ssa/back/linker.rs:623]: What about mach-o?

**Comment by Amanieu** [comment]
We still need it with unwind=abort because backtraces need unwind info.

File: src/librustc_codegen_ssa/back/linker.rs (hunk 1 above)
Comment (petrochenkov) [reply src/librustc_codegen_ssa/back/linker.rs:623]: Ah, right, always forget that macos & friends exist.
That would be `self.sess.target.target.options.is_like_osx`.

Comment (cuviper) [reply src/librustc_codegen_ssa/back/linker.rs:623]: What's the resolution here? Mention macos in the comment, or filter `is_like_osx` from the `if`-condition too?

Comment (petrochenkov) [reply src/librustc_codegen_ssa/back/linker.rs:623]: Filter `is_like_osx` (I need to update the PR).

Comment (petrochenkov) [reply src/librustc_codegen_ssa/back/linker.rs:624]: Updated.

**Comment by diodesign** [comment]
FYI: This breaks, at least, bare-metal Rust RISC-V projects. GNU Binutils doesn't support `--eh-frame-hdr` nor `--no-eh-frame-hdr` for RISC-V bare-metal targets, so the opt-out doesn't work. The workaround for bare-metal Rust RISC-V projects is to use Binutils recompiled for `riscv32-linux` and `riscv64-linux` targets, and ensure your project's linker script overrides the toolchain's defaults.

I'm commenting here in case anyone else finds their Rust-RISC-V-Binutils toolchain suddenly breaks. I was previously using `riscv32-elf` and `riscv64-elf` as a Binutils bare-metal target. I've switched to `riscv32-linux` and `riscv32-linux`, and my project builds as expected. If anyone needs any more info, let me know -- happy to help.

**Comment by petrochenkov** [comment]
@diodesign 
The bare-metal RISC-V targets are fixed in https://github.com/rust-lang/rust/pull/74631.
