### PR TITLE
On `format!()` arg count mismatch provide extra info

### LINKED ISSUE #49384: Confusing error message if you forget the width of the * format specifier
Playground link: https://play.rust-lang.org/?gist=fea3e7d4c4151751bb66b69ba906ea88&version=stable

If the `*` formatting specifier is used, it expects an additional argument. But it does not account for this when printing an error message, so in the above example where an argument was forgotten, the error is "error: 1 positional argument in format string, but there is 1 argument". It should indicate that there are in fact 2 positional arguments in the format string, due to `*`.

### PR DESCRIPTION
**Pull request by estebank**
When positional width and precision formatting flags are present in a
formatting string that has an argument count mismatch, provide extra
information pointing at them making it easiser to understand where the
problem may lay:

```
error: 4 positional arguments in format string, but there are 3 arguments
  --> $DIR/ifmt-bad-arg.rs:78:15
   |
LL |     println!("{} {:.*} {}", 1, 3.2, 4);
   |               ^^ ^^--^ ^^      --- this parameter corresponds to the precision flag
   |                    |
   |                    this precision flag adds an extra required argument at position 1, which is why there are 4 arguments expected
   |
   = note: positional arguments are zero-based
   = note: for information about formatting flags, visit https://doc.rust-lang.org/std/fmt/index.html

error: 4 positional arguments in format string, but there are 3 arguments
  --> $DIR/ifmt-bad-arg.rs:81:15
   |
LL |     println!("{} {:07$.*} {}", 1, 3.2, 4);
   |               ^^ ^^-----^ ^^      --- this parameter corresponds to the precision flag
   |                    |  |
   |                    |  this precision flag adds an extra required argument at position 1, which is why there are 4 arguments expected
   |                    this width flag expects an `usize` argument at position 7, but there are 3 arguments
   |
   = note: positional arguments are zero-based
   = note: for information about formatting flags, visit https://doc.rust-lang.org/std/fmt/index.html

error: invalid reference to positional argument 7 (there are 3 arguments)
  --> $DIR/ifmt-bad-arg.rs:84:18
   |
LL |     println!("{} {:07$} {}", 1, 3.2, 4);
   |                  ^^^--^
   |                     |
   |                     this width flag expects an `usize` argument at position 7, but there are 3 arguments
   |
   = note: positional arguments are zero-based
   = note: for information about formatting flags, visit https://doc.rust-lang.org/std/fmt/index.html
```

Fix #49384.

### CODE REVIEW

File: src/libfmt_macros/lib.rs [hunk 1]
```diff
@@ -285,19 +289,24 @@ impl<'a> Parser<'a> {
...
-        if let Some(&(_, maybe)) = self.cur.peek() {
+        self.consume_pos(c).is_some()
+    }
+
+    /// Optionally consumes the specified character. If the character is not at
+    /// the current position, then the current iterator isn't moved and `None` is
+    /// returned, otherwise the character is consumed and the current position is
+    /// returned.
+    fn consume_pos(&mut self, c: char) -> Option<usize> {
+        if let Some(&(pos, maybe)) = self.cur.peek() {
```
Comment (Centril) [inline src/libfmt_macros/lib.rs]: Consider rewriting as:
```rust
    fn consume_pos(&mut self, c: char) -> Option<usize> {
        self.cur.peek()
            .filter(|&(pos, maybe)| c == maybe)
            .map(|(pos, _)| {
                self.cur.next();
                pos
            })
```

File: src/libfmt_macros/lib.rs [hunk 2]
```diff
@@ -59,16 +59,20 @@ pub struct Argument<'a> {
...
     pub align: Alignment,
-    /// Packed version of various flags provided
+    /// Packed version of various flags provided.
     pub flags: u32,
-    /// The integer precision to use
+    /// The integer precision to use.
     pub precision: Count,
-    /// The string width requested for the resulting format
+    /// The span of the precision formatting flag (for diagnostics).
+    pub precision_span: Option<InnerSpan>,
```
Comment (Centril) [inline src/libfmt_macros/lib.rs]: Seems https://doc.rust-lang.org/nightly/nightly-rustc/syntax/source_map/struct.InnerSpan.html is lacking some docs which would have been useful context in this review. :)

File: src/libsyntax_ext/format.rs [hunk 3]
```diff
@@ -506,6 +578,9 @@ impl<'a, 'b> Context<'a, 'b> {
                 let pos_simple =
                     arg.position.index() == simple_arg.position.index();
 
+                if arg.format.precision_span.is_some() || arg.format.width_span.is_some() {
+                    self.arg_with_formatting.push(arg.format); //'liself.fmtsp.from_inner(span));
```
Comment (Centril) [inline src/libsyntax_ext/format.rs]: What's up with the comment here?

File: src/libfmt_macros/lib.rs [hunk 4]
```diff
@@ -502,6 +513,11 @@ impl<'a> Parser<'a> {
         }
         // Width and precision
         let mut havewidth = false;
+
+        let mut width_span_start = 0;
+        if let Some((pos, '0')) = self.cur.peek() {
```
Comment (Centril) [inline src/libfmt_macros/lib.rs]: The `'0'` could use a comment?

**Comment by Centril** [comment]
Unfortunately I'm not really familiar with this part of the compiler so I don't feel comfortable doing the main review but I left some comments above.

r? @alexcrichton cc @Mark-Simulacrum

File: src/libfmt_macros/lib.rs (hunk 1 above)
Comment (estebank) [reply src/libfmt_macros/lib.rs]: Can't borrow `self.cur` twice in this case.

Comment (Centril) [reply src/libfmt_macros/lib.rs]: Ah; use `.cloned()` + a let binding or something to make the first borrow end early then... or maybe this is not important. idk :)

File: src/libfmt_macros/lib.rs [hunk 5]
```diff
@@ -554,24 +577,25 @@ impl<'a> Parser<'a> {
     /// Parses a Count parameter at the current position. This does not check
     /// for 'CountIsNextParam' because that is only used in precision, not
     /// width.
-    fn count(&mut self) -> Count {
+    fn count(&mut self, start: usize) -> (Count, Option<InnerSpan>) {
```
Comment (alexcrichton) [inline src/libfmt_macros/lib.rs]: This seems like it's pretty tailored in the implementation, but perhaps this could be somewhat more generalized? For example instead of modifying existing methods and having some which return a span and some which don't (in addition to passing around start spans and such) could one new function be added liek:

```rust
fn span<R>(&mut self, f: impl FnOnce(&mut Self) -> R) -> (R, Span) {
    // ...
}
```

and that's called like `let (count, span) = self.span(|me| me.count());` or something like that?

File: src/libsyntax_ext/format.rs [hunk 6]
```diff
@@ -273,31 +275,44 @@ impl<'a, 'b> Context<'a, 'b> {
...
                 ),
             );
         } else {
-            let (arg_list, mut sp) = if refs_len == 1 {
-                let (reg, pos) = refs.next().unwrap();
+            let (mut refs, spans): (Vec<_>, Vec<_>) = refs.unzip();
+            // Avoid `invalid reference to positional arguments 7 and 7 (there is 1 argument)`
+            // for `println!("{7:7$}", 1);`
+            refs.dedup();
+            refs.sort();
```
Comment (alexcrichton) [inline src/libsyntax_ext/format.rs]: I think for `dedup` to work the sort/dedup here need to be swapped?

**Review by alexcrichton — COMMENTED** [review]
Looks reasonable to me! I tend to not review the error-generation code too too carefully, but the error messages look fantastic and I've largely just got one stylistic request on the fmt_macros crate

File: src/libfmt_macros/lib.rs (hunk 5 above)
Comment (estebank) [reply src/libfmt_macros/lib.rs]: The thing is that the actual span for the thing being composed requires some passing of location between different methods. `count` in particular is only used in two places and both care about the span. These methods are meant to only be used from a single module, which is why I didn't bother with an externally pleasing api surface for them.

File: src/libfmt_macros/lib.rs (hunk 1 above)
Comment (estebank) [reply src/libfmt_macros/lib.rs]: At that point I feel that the plain for loop ends up being easier on the eyes of the next person reading this code :)

**Comment by alexcrichton** [comment]
@bors: r+

Ok, sounds reasonable to me!
