### PR TITLE
bootstrap: Always build for host, even when target is given

### LINKED ISSUE #76990: x.py install does nothing when `target` is set but `host` is not
With a valid install prefix under `install.prefix` in config.toml, I see this:

```
./x.py install
Updating only changed submodules
Submodules updated in 0.04 seconds
    Finished dev [unoptimized + debuginfo] target(s) in 0.17s
Build completed successfully in 0:00:00
```

But nothing is installed. This is a recent regression. At first I thought it had to do with the default stages changing, but passing `--stage` doesn't seem to have an effect.

### PR DESCRIPTION
**Pull request by tmandry**
This changes the behavior from *not* building for host whenever an
explicit target is specified. I find this much less confusing.

You can still disable host steps by passing an explicit empty list for
host.

Fixes #76990.

r? @Mark-Simulacrum

### CODE REVIEW

File: src/bootstrap/config.rs [hunk 1]
```diff
@@ -548,18 +548,15 @@ impl Config {
...
-
         config.hosts = if let Some(arg_host) = flags.host {
             arg_host
         } else if let Some(file_host) = build.host {
             file_host.iter().map(|h| TargetSelection::from_user(h)).collect()
         } else {
             vec![config.build]
         };
+        // If host was explicitly given an empty list, don't run any host-only steps.
+        config.skip_only_host_steps = config.hosts.is_empty();
```
Comment (Mark-Simulacrum) [inline src/bootstrap/config.rs:559]: This shouldn't be necessary anymore, the field should be removable with no effect.

Comment (tmandry) [reply src/bootstrap/config.rs:559]: I tried that at first but it changed the dist behavior in the test: it causes us to distribute a rustc for the build target ("A" in the test) as well as sources. Is that desirable?

Comment (Mark-Simulacrum) [reply src/bootstrap/config.rs:559]: I think that's probably because the tests are always configuring the build triple as part of the host triples, whereas here that's not the case -- https://github.com/Mark-Simulacrum/rust/blob/4de836e2141c418d37e556bc80c4ad0127d74b71/src/bootstrap/builder/tests.rs#L23-L26.

We should, I think, remove this field and update the tests to avoid that buggy behavior (probably by explicitly adding the build triple to all of the tests that need it, i.e., those that don't explicitly override skip_only_host_steps.

Comment (tmandry) [reply src/bootstrap/config.rs]: Ah that makes sense, done. I also made them list all their targets explicitly for consistency.

**Comment by Mark-Simulacrum** [comment]
Could you also add a note to the CHANGELOG? https://github.com/rust-lang/rust/blob/master/src/bootstrap/CHANGELOG.md

No need to add a new version, just append to the list of changes.

r=me with that done.

**Comment by Mark-Simulacrum** [comment]
Hm, actually, no -- I think this probably also means that we need to go and update a bunch of our builders to explicitly pass `--host ''` or `--host '[]'` or something like that if they're *only* passing target right now, otherwise we'll bump build times and all up. I'm not sure what the best way to do that is, though -- maybe just `rg '\-\-target' src/ci/` and trying to catch all of those cases?

I'm not sure if this is a sign we're "doing the wrong thing" or not -- I think probably no, because in most cases you do want to test or distribute for both targets and hosts, just in our CI the way we parallelize things we want to avoid that because we're taking care of the host part in one place and then spreading the targets out.

**Comment by tmandry** [comment]
> No need to add a new version, just append to the list of changes.

Should we consider it a breaking change though?

**Comment by Mark-Simulacrum** [comment]
Hm, it's a good question. I guess the answer is probably yes. It should be relatively easy to bump the version number -- I think just https://github.com/rust-lang/rust/blob/master/src/bootstrap/bin/main.rs#L30 needs to change but not 100% sure.

cc @jyn514 as well

**Comment by jyn514** [comment]
You also need to add it to the changelog itself: https://github.com/rust-lang/rust/blob/master/src/bootstrap/CHANGELOG.md. Those should be the only two places I think.

**Comment by jyn514** [comment]
> Hm, actually, no -- I think this probably also means that we need to go and update a bunch of our builders to explicitly pass --host '' or --host '[]' or something like that if they're only passing target right now, otherwise we'll bump build times and all up. I'm not sure what the best way to do that is, though -- maybe just rg '\-\-target' src/ci/ and trying to catch all of those cases?

Another use case for https://rust-lang.zulipchat.com/#narrow/stream/242791-t-infra/topic/x.2Epy.20CI.20defaults ;)

**Comment by Mark-Simulacrum** [comment]
I don't think defaults would be a good fit here, they would probably confuse things more than help - better to have both overriden in the same place.

**Comment by tmandry** [comment]
Hmm, thinking about this more and I'm pretty on the fence about what to do.

For config.toml it seems like we're reverting back to what we had 1-2 weeks ago, so having people bump `changelog-seen` feels like overkill.

For the command line we could consider it a breaking change, but we could also say that building _more_ than we used to in some cases isn't actually breaking. Still, we do want people who might be impacted to know about it.

**Comment by jyn514** [comment]
Would it help if instead of a binary breaking/not-breaking you printed a short description of the change?

**Comment by tmandry** [comment]
Do you mean in the changelog? Or in `check_version()`?

A changelog entry would probably look something like:

> `host` now defaults to the value of `build` in all cases. Previously we defaulted `host` to an empty list when `target` was overridden and to `build` otherwise.

**Comment by jyn514** [comment]
I meant in check_version.

In general I think nagging more is better than nagging less. The thing to avoid is people changing the number without reading the changelog, and I don't think we have enough changes for that yet.

**Comment by tmandry** [comment]
Right, and because these changes are "live" as soon as they merge, I think we're always going to have the issue of there being only a single change for each version. Which means we might want to tweak the changelog format a bit. Maybe grouping them by month would make sense?

I do like the idea of sticking the change text in `check_version()`, i.e. a programmatic changelog to match the text one. One other idea: it would be nice if there were a flag or command to bump the version in your config.toml for you =)

**Comment by tmandry** [comment]
Okay, updated the changelog and bumped the version. Outputting breaking changes from x.py and adding an "ack" feature would be good for a follow up change.

**Comment by tmandry** [comment]
@Mark-Simulacrum I'll let you take a final look since I updated all the CI scripts

**Comment by tmandry** [comment]
Rebased.

File: src/ci/docker/host-x86_64/x86_64-gnu-llvm-8/Dockerfile [hunk 2]
```diff
@@ -45,7 +45,7 @@ ENV SCRIPT python2.7 ../x.py --stage 2 test --exclude src/tools/tidy && \
            # on the `x86_64` host when they're built as `armv5te` binaries.
            # (we're only interested in the MIR output, so this doesn't matter)
            python2.7 ../x.py --stage 2 test src/test/mir-opt --pass=build \
-                                  --target=armv5te-unknown-linux-gnueabi && \
+                             --host= --target=armv5te-unknown-linux-gnueabi && \
```
Comment (Mark-Simulacrum) [inline src/ci/docker/host-x86_64/x86_64-gnu-llvm-8/Dockerfile:48]: For consistency can we pass `''` here too?

**Review by Mark-Simulacrum — COMMENTED** [review]
r=me with nit fixed

**Comment by jyn514** [comment]
```
thread 'main' panicked at 'error: no rules matched i586-unknown-linux-gnu,i686-unknown-linux-musl', src/bootstrap/builder.rs:224:21
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
failed to run: /checkout/obj/build/bootstrap/debug/bootstrap --stage 2 test --host --target i586-unknown-linux-gnu,i686-unknown-linux-musl
```

**Comment by jyn514** [comment]
Looks like you need `--host=""` instead of `--host` somewhere.

**Comment by tmandry** [comment]
Strange, maybe some version of Docker wasn't passing through empty `''` args? I changed everything to use `--host=''` to see if that fixes things.

@bors r=Mark-Simulacrum rollup=never

**Comment by tmandry** [comment]
```
thread 'main' panicked at '

couldn't find required command: "arm-linux-gnueabihf-g++"

', src/bootstrap/sanity.rs:59:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
failed to run: /checkout/obj/build/bootstrap/debug/bootstrap --stage 2 test --host= --target arm-unknown-linux-gnueabihf
```

I want this to be a spurious error but it probably isn't. Maybe there's a subtle change in the behavior that we haven't accounted for.

**Comment by Mark-Simulacrum** [comment]
Well, one immediate problem is that `--host=''` appears to configure an empty string as the triple, at least based on some quick dbg!ing locally.

```
[src/bootstrap/flags.rs:577] split(&matches.opt_strs("host")).into_iter().map(|x|
                                                     TargetSelection::from_user(&x)).collect::<Vec<_>>() = [
    TargetSelection {
        triple: "",
        file: None,
    },
]
```

We should probably just filter out empty strings in the split function in flags.rs, that seems to have fixed that failure locally for me at least.

**Comment by tmandry** [comment]
Nice catch! I seem to have forgotten that I can reproduce these locally with Docker.

**Comment by tmandry** [comment]
Pushed a change with your suggestion.

**Comment by Mark-Simulacrum** [comment]
That said the build still fails for me locally with zlib.h header missing, but not sure if that's related to this PR. I think it might be changes to the docker environment or something like that, because adding zlib1g-dev to the armhf-gnu docker container does seem to fix things. Maybe an upstream change to 16.04? Seems unlikely, but not entirely implausible, and I'm fine with hitting CI to find out.

**Comment by Mark-Simulacrum** [comment]
TIL about carp streamer, https://codepoints.net/U+1F38F, though how that relates to "flags" beyond some visual similarity I'm not sure.

Anyway, @bors r+ rollup=never
