### PR TITLE
Suggest `into` instead of `try_into` if possible with int types

### LINKED ISSUE #71580: Suboptimal hint about converting numeric types: Suggests `try_into().unwrap()` when `into()` is possible.
```rust
fn main() {
    let a = 1u8;
    let _: i64 = a;
}
```

([Playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=45961bca32186db6d4918d8c610315e9))

Errors:

```
   Compiling playground v0.0.1 (/playground)
error[E0308]: mismatched types
 --> src/main.rs:3:18
  |
3 |     let _: i64 = a;
  |            ---   ^ expected `i64`, found `u8`
  |            |
  |            expected due to this
  |
help: you can convert an `u8` to `i64` and panic if the converted value wouldn't fit
  |
3 |     let _: i64 = a.try_into().unwrap();
  |                  ^^^^^^^^^^^^^^^^^^^^^

error: aborting due to previous error

For more information about this error, try `rustc --explain E0308`.
error: could not compile `playground`.

To learn more, run the command again with --verbose.

```

I would’ve expected something like: 
```
help: you can convert an `u8` to `i64`
  |
3 |     let _: i64 = a.into();
  |                  ^^^^^^^^
```
_Edit:_ What actually should happen is the same as currently already with `_: u64`, i.e. it would look like
```
error[E0308]: mismatched types
 --> src/main.rs:3:18
  |
3 |     let _: i64 = a;
  |            ---   ^
  |            |     |
  |            |     expected `i64`, found `u8`
  |            |     help: you can convert an `u8` to `i64`: `a.into()`
  |            expected due to this
```

@rustbot modify labels: A-diagnostics, T-compiler, D-papercut, C-enhancement, E-easy

This issue has been assigned to @samrat via [this comment](https://github.com/rust-lang/rust/issues/71580#issuecomment-620088274).

### PR DESCRIPTION
**Pull request by samrat**
If it is possible to convert an integer type into another using `into`, don't suggest `try_into`. This commit changes the suggested method to convert from one integer type to another for the following cases:

- u{n} -> i{m} where n < m
- u8 -> isize
- i{n} -> isize where n <= 16
- u{n} -> usize where n <= 16

Fixes #71580

### CODE REVIEW

File: src/test/ui/suggestions/integer-into.rs [hunk 1]
```diff
@@ -0,0 +1,17 @@
+fn main() {
```
Comment (ecstatic-morse) [inline src/test/ui/suggestions/integer-into.rs:1]: Is there an existing test with int -> int conversions that these naturally belong to? If not, can you add a comment with the rationale for the test? A link to the issue would suffice.

```suggestion
// https://github.com/rust-lang/rust/issues/71580

fn main() {
```

**Review by ecstatic-morse — APPROVED** [review]
As Jonas noted on the issue, this suggestion would probably be better implemented by looking for an `Into` impl for the target type. Since this PR just extends the existing approach to be more complete, however, I'm fine merging it as-is.

@samrat You need to run `./x.py fmt`. If it helps, I like to run `./x.py test src/tools/tidy` as part of a [pre-push hook](https://git-scm.com/book/en/v2/Customizing-Git-Git-Hooks) to catch formatting errors locally.
