### PR TITLE
Mir Borrowck: Parity with Ast for E0384 (Cannot assign twice to immutable)

### LINKED ISSUE #45199: MIR-borrowck: ICE during diagnostic search for assignment (unwrap of None)
PR #44806 added some code to search for the lexically first assignment in order to report an illegal assignment.

However, oddly enough, for some tests this search, which ends in an `unwrap`, is causing the compiler to ICE.

For example:

```
%  build/x86_64-apple-darwin/stage1/bin/rustc  -Z borrowck-mir \
     ../src/test/compile-fail/borrowck/borrowck-for-loop-head-linkage.rs
[...]
error[E0384]: re-assignment of immutable variable `val` (Mir)
  --> ../src/test/compile-fail/borrowck/borrowck-for-loop-head-linkage.rs:15:5
   |
15 |        for &x in &vector {
   |   _____^
   |  |_____|
   | ||
16 | ||         let cap = vector.capacity();
17 | ||         vector.extend(repeat(0));      //~ ERROR cannot borrow
18 | ||         vector[1] = 5;   //~ ERROR cannot borrow
19 | ||     }
   | ||     ^
   | ||_____|
   | |______re-assignment of immutable variable
   |        first assignment to `val`

error[E0384]: re-assignment of immutable variable `x` (Mir)
  --> ../src/test/compile-fail/borrowck/borrowck-for-loop-head-linkage.rs:15:10
   |
15 |     for &x in &vector {
   |          ^
   |          |
   |          re-assignment of immutable variable
   |          first assignment to `x`

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.22.0-dev running on x86_64-apple-darwin

thread 'rustc' panicked at 'called `Option::unwrap()` on a `None` value', /Users/fklock/Dev/Mozilla/rust.git/src/libcore/option.rs:335:20
```

### PR DESCRIPTION
**Pull request by matthewjasper**
- Closes #45199 
- Don't allow assigning to dropped immutable variables
- Show the "first assignment" note on the first assignment that can actually come before the second assignment.
- Make "first assignment" notes point to function parameters if needed.
- Don't show a "first assignment" note if the first and second assignment have the same span (in a loop). This matches ast borrowck for now, but maybe this we should add "in previous loop iteration" as with some other borrowck errors. (Commit 2)
- Use revisions to check mir borrowck for the existing tests for this error. (Commit 3)

~~Still working on a less ad-hoc way to get 'first assignment' notes to show on the correct assignment. Also need to check mutating function arguments.~~ Now using a new dataflow pass.

### CODE REVIEW

**Comment by arielb1** [comment]
@matthewjasper 

I don't think `StorageDead` kills move-out status, so I think this will break situations such as:
```Rust
loop {
    let x = String::new();
    drop(x);
}
```

You probably want to create a separate dataflow for "propagating initializations" (basically the opposite of the `MoveOut` analysis, that is killed by a `StorageDead`, but not by moves) and use that instead of using a combination of moveout + maybe-uninitialized.

**Comment by arielb1** [comment]
@matthewjasper 

Nice PR. However, I think we are getting quite a bit of separate move-in implementation sprawl - there are already 2, and now we're getting another one. I think we can merge them - that would imply changing the 
code so that [MovingOutStatements] and [drop_flag_effects_for_location] use the `init_loc_map`.

For that, you'll need to have some sort of flag on the `init_loc_map` so that you won't initialize the return value of calls on the panic path, because that will cause bugs. I think adding a `non_panic_path_only` flag to `Init` and checking it where needed would be enough.

[MovingOutStatements]: https://github.com/rust-lang/rust/blob/c5c70ef72369b00870d9fc67b99853b0681e17e2/src/librustc_mir/dataflow/impls/mod.rs#L211
[drop_flag_effects_for_location]: https://github.com/rust-lang/rust/blob/c5c70ef72369b00870d9fc67b99853b0681e17e2/src/librustc_mir/dataflow/drop_flag_effects.rs#L179

File: src/librustc_mir/dataflow/move_paths/builder.rs [hunk 1]
```diff
@@ -337,6 +369,7 @@ impl<'b, 'a, 'gcx, 'tcx> Gatherer<'b, 'a, 'gcx, 'tcx> {
                 }
                 if let Some((ref destination, _bb)) = *destination {
                     self.create_move_path(destination);
```
Comment (arielb1) [inline src/librustc_mir/dataflow/move_paths/builder.rs]: This only initializes the destination on the non-panic-path, so you'll probably want some label on the `Init` you create to indicate that.

File: src/librustc_mir/dataflow/impls/mod.rs [hunk 2]
```diff
@@ -562,11 +612,94 @@ impl<'a, 'gcx, 'tcx> BitDenotation for MovingOutStatements<'a, 'gcx, 'tcx> {
...
+                             dest_lval: &mir::Lvalue) {
+        let move_data = self.move_data();
+        let bits_per_block = self.bits_per_block();
+        let init_path_map = &move_data.init_path_map;
+
+        on_lookup_result_bits(self.tcx,
+                              self.mir,
+                              move_data,
+                              move_data.rev_lookup.find(dest_lval),
+                              |mpi| for ii in &init_path_map[mpi] {
```
Comment (arielb1) [inline src/librustc_mir/dataflow/impls/mod.rs]: This looks wrong - you don't want to "christmas tree" every initialization for this lvalue, you want just the initialization for the call.

e.g. in a code like
```Rust
let x;
if true {
    x = 2;
} else {
    x = get();
    x = 3;
}
```

You want to highlight just the `get`, not the other assignment to `x`.

If you want to do this correctly, you could just do
```Rust
let call_loc = Location { // why doesn't MIR have a terminator_loc method?
    block: call_bb,       // feel free to add one
    statement_index: self.mir[call_bb].statements.len()
};
for init_index in &init_loc_map[call_loc] {
    zero_to_one(sets.gen_set.words_mut(), *init_index);
}
```

**Comment by arielb1** [comment]
r=me with the initialization sprawl bought under control.

**Comment by shepmaster** [comment]
@matthewjasper the title of this PR still says "[WIP]", but it looks like your review is close to finished. Please make sure to remove that if you feel this PR should be merged.

**Comment by arielb1** [comment]
@matthewjasper 

How are you doing with this PR? Could you address the nits so we can move forward?

**Comment by matthewjasper** [comment]
Comments addressed.

File: src/librustc_mir/borrow_check.rs [hunk 3]
```diff
@@ -719,22 +728,14 @@ impl<'cx, 'gcx, 'tcx> MirBorrowckCtxt<'cx, 'gcx, 'tcx> {
...
-                            *lv == *assigned_lvalue
-                        } else {
-                            false
-                        }
-                    })
-                }).next().unwrap();
-                self.report_illegal_reassignment(
-                    context, (lvalue, span), assignment_stmt.source_info.span);
+            for ii in &move_data.init_path_map[mpi] {
+                if flow_state.ever_inits.curr_state.contains(ii)
```
Comment (arielb1) [inline src/librustc_mir/borrow_check.rs]: style: opening brace for `if`s is in the same line as the `if`:
```
                if flow_state.ever_inits.curr_state.contains(ii) {
```

File: src/librustc_mir/dataflow/drop_flag_effects.rs [hunk 4]
```diff
@@ -197,47 +197,40 @@ pub(crate) fn drop_flag_effects_for_location<'a, 'gcx, 'tcx, F>(
...
+            },
+            InitKind::Shallow => {
+                let mpi = init.path;
+                callback(mpi);
             }
+            InitKind::NonPanicPathOnly => (),
         }
     }
-}
+}
```
Comment (arielb1) [inline src/librustc_mir/dataflow/drop_flag_effects.rs]: style: no newline at end of file

File: src/librustc_mir/dataflow/impls/mod.rs [hunk 5]
```diff
@@ -562,11 +577,96 @@ impl<'a, 'gcx, 'tcx> BitDenotation for MovingOutStatements<'a, 'gcx, 'tcx> {
...
+    {
+        let (mir, move_data) = (self.mir, self.move_data());
+        let term = mir[location.block].terminator();
+        let init_loc_map = &move_data.init_loc_map;
+        debug!("terminator {:?} at loc {:?} initializes move_indexes {:?}",
+               term, location, &init_loc_map[location]);
+        let bits_per_block = self.bits_per_block();
+        for init_index in &init_loc_map[location] {
+            assert!(init_index.index() < bits_per_block);
+            zero_to_one(sets.gen_set.words_mut(), *init_index);
```
Comment (arielb1) [inline src/librustc_mir/dataflow/impls/mod.rs]: I would prefer to use a `in_out.add` rather than a `zero_to_one` here - I'm not sure of a good reason for this to always be for an uninitialized variable.

Comment (arielb1) [reply src/librustc_mir/dataflow/impls/mod.rs]: Also, even if it doesn't matter for borrow-check (because you can't have assignments in the panic path) you should not mark call destinations as uninitialized if the call unwinds (i.e. if the init loc map entry is a NonPanicPathOnly).

File: src/librustc_mir/dataflow/move_paths/builder.rs [hunk 6]
```diff
@@ -221,6 +239,22 @@ pub(super) fn gather_moves<'a, 'gcx, 'tcx>(mir: &Mir<'tcx>,
 }
 
 impl<'a, 'gcx, 'tcx> MoveDataBuilder<'a, 'gcx, 'tcx> {
+    fn gather_args(&mut self) {
+        for arg in self.mir.args_iter() {
+            let path = self.data.rev_lookup.locals[arg];
+            let span = self.mir.local_decls[arg].source_info.span;
+
+            let init = self.data.inits.push(Init {
```
Comment (arielb1) [inline src/librustc_mir/dataflow/move_paths/builder.rs]: You want to have arguments assigned before the first statement, to avoid edge cases such as
```Rust
fn foo(x: u8) {
    x=2; // this should be an error, even if we translate the arg in-place.
}
```

File: src/librustc_mir/dataflow/move_paths/builder.rs (hunk 1 above)
Comment (arielb1) [reply src/librustc_mir/dataflow/move_paths/builder.rs]: fixed.

File: src/librustc_mir/dataflow/impls/mod.rs (hunk 5 above)
Comment (matthewjasper) [reply src/librustc_mir/dataflow/impls/mod.rs]: You mean as _initialized_?

Comment (arielb1) [reply src/librustc_mir/dataflow/impls/mod.rs]: Yea my bad

**Comment by matthewjasper** [comment]
Nits addressed
