### PR TITLE
Don't show suggestion if slice pattern is not top-level

### LINKED ISSUE #120605: Incorrect "consider slicing" suggestion with `Vec` inside a struct
### Code

```Rust
pub struct Struct {
    a: Vec<Struct>,
}

impl Struct {
    pub fn test(&self) {
        if let [Struct { a: [] }] = &self.a[..] {
            println!("matches!")   
        }
    }
}
```

### Current output

```Shell
error[E0529]: expected an array or slice, found `Vec<Struct>`
  --> src/main.rs:47:29
   |
47 |         if let [Struct { a: [] }] = &self.a[..] {
   |                             ^^      ----------- help: consider slicing here: `&self.a[..][..]`
   |                             |
   |                             pattern cannot match with input type `Vec<Struct>`
```

### Desired output

```Shell
error[E0529]: expected an array or slice, found `Vec<Struct>`
  --> src/main.rs:47:29
   |
47 |         if let [Struct { a: [] }] = &self.a[..] {
   |                             ^^
   |                             |
   |                             pattern cannot match with input type `Vec<Struct>`
```

### Rationale and extra context

The suggestion to try `&self.a[..][..]` does not work, and should not be included. If you do try to follow this suggestion, the error then suggests `&self.a[..][..][..]`, then `&self.a[..][..][..][..]`, and so on.

### Other cases

_No response_

### Rust Version

```Shell
rustc 1.77.0-nightly (88189a71e 2024-01-19)
binary: rustc
commit-hash: 88189a71e4e4376eea82ac61db6a539612eb200a
commit-date: 2024-01-19
host: aarch64-apple-darwin
release: 1.77.0-nightly
LLVM version: 17.0.6
```

(Also repros on latest nightly using the Playground)

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by long-long-float**
Close #120605

Don't show suggestion to add slicing (`[..]`) if the slice pattern is enclosed by struct like `Struct { a: [] }`.

For example, current rustc makes a suggestion as a comment. However, the pattern `a: []` is wrong, not scrutinee `&self.a`.
In this case, the structure type `a: Vec<Struct>` and the pattern `a: []` are different so I think the pattern should be fixed, not the scrutinee.
If the parent of the pattern that was the target of the error is a structure, I made the compiler not show a suggestion.

```rs
pub struct Struct {
    a: Vec<Struct>,
}

impl Struct {
    pub fn test(&self) {
        if let [Struct { a: [] }] = &self.a {
//             ^^^^^^^^^^^^^^^^^^   ------- help: consider slicing here: `&self.a[..]`
            println!("matches!")   
        }
    }
}
```

Note:

* ~~I created `PatInfo.history` to store parent-child relationships for patterns, but this may be inefficient.~~
  * I use two fields `parent_kind` and `current_kind` instead of vec. It may not performance issue.
* Currently only looking at direct parents, but may need to look at deeper ancestry.

### CODE REVIEW

**Comment by Nadrieril** [comment]
Hi! Thanks for your contribution.

Let me know with `@rustbot ready` when you've found a solution that doesn't overflow or if you need help.

@rustbot author

**Comment by Nadrieril** [comment]
My first question is: the example you show gives a correct suggestion: to match on `self.a` with a slice pattern you really do need to use `self.a[..]` or `self.a.as_slice()`. This is different from https://github.com/rust-lang/rust/issues/120605.

Could you add two tests: one with the example you mention, and one with the example in https://github.com/rust-lang/rust/issues/120605?

**Comment by long-long-float** [comment]
I added a test for the issue. Could you review?

@rustbot ready

File: compiler/rustc_hir_typeck/src/pat.rs [hunk 1]
```diff
@@ -2309,7 +2340,11 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
                 }
                 _ => (),
             }
-            if is_slice_or_array_or_vector.0 {
+
+            let enclosure_is_struct =
+                parent_kind.map_or(false, |enclosure| matches!(enclosure, PatKind::Struct(..)));
```
Comment (Nadrieril) [inline compiler/rustc_hir_typeck/src/pat.rs:2345]: Can you try `let enclosure_is_struct = parent_kind.is_some()` instead? I feel like any non-top-level pattern would cause issues. Can you think or a counter-example?

Comment (long-long-float) [reply compiler/rustc_hir_typeck/src/pat.rs]: I agree with you and fixed.

Comment (Nadrieril) [reply compiler/rustc_hir_typeck/src/pat.rs]: Nice, thank you! I think this is good, I only have a few more comments

File: compiler/rustc_hir_typeck/src/pat.rs [hunk 2]
```diff
@@ -83,6 +83,9 @@ struct PatInfo<'tcx, 'a> {
     binding_mode: BindingMode,
     top_info: TopInfo<'tcx>,
     decl_origin: Option<DeclOrigin<'a>>,
+
+    parent_kind: Option<PatKind<'tcx>>,
+    current_kind: Option<PatKind<'tcx>>,
```
Comment (Nadrieril) [inline compiler/rustc_hir_typeck/src/pat.rs:88]: Since you only care whether the parent exists and not its kind, you could store a single boolean here, names `has_parent` or `is_top_level` or something like that.

Comment (long-long-float) [reply compiler/rustc_hir_typeck/src/pat.rs]: I used a counter `current_depth` to distinct three states:

* Initial state: 0
* The first call of `check_pat`: 1
* Second and subsequent calls of `check_pat`: >1

If `current_depth` is less than or equal to 1, the pattern is top level.

**Comment by Nadrieril** [comment]
Thank you!

@bors r+ rollup

**Comment by Nadrieril** [comment]
Oops wait, could you squash all commits into one actually?

@bors r-

**Comment by long-long-float** [comment]
I squashed all commits. Thank you for reviewing.

**Comment by Nadrieril** [comment]
:+1: 

@bors r+ rollup
