### PR TITLE
Fix normalization involving bound regions

### LINKED ISSUE #21750: ICE in `region_inference/mod.rs`
Attempting to compile https://github.com/reem/rust-traverse with `cargo 0.0.1-pre-nightly (453ae9f 2015-01-29 00:56:56 +0000)` and `rustc 1.0.0-nightly (c5961ad06 2015-01-28 21:49:38 +0000)` yields the following ICE:
```
thread 'rustc' panicked at 'index out of bounds: the len is 0 but the index is 0', /home/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/librustc/middle/infer/region_inference/mod.rs:1015

stack backtrace:
   1:     0x7f8da355a880 - sys::backtrace::write::h471f2f26c91df096Q8t
   2:     0x7f8da357df80 - failure::on_fail::h389257f46ebc50afikB
   3:     0x7f8da34ea220 - rt::unwind::begin_unwind_inner::haa1ac937607e9179jZA
   4:     0x7f8da34ead50 - rt::unwind::begin_unwind_fmt::ha84452bff441c4ffPXA
   5:     0x7f8da357dde0 - rust_begin_unwind
   6:     0x7f8da35c6ef0 - panicking::panic_fmt::ha791a233597f33dbBRv
   7:     0x7f8da35cf5c0 - panicking::panic_bounds_check::h7964adf489703576CQv
   8:     0x7f8da16d6ce0 - middle::infer::region_inference::RegionVarBindings<'a, 'tcx>::infer_variable_values::hdb795f883c676391mJw
   9:     0x7f8da16d6970 - middle::infer::region_inference::RegionVarBindings<'a, 'tcx>::resolve_regions::h2570f98c1810a795Ymw
  10:     0x7f8da16fc020 - middle::infer::InferCtxt<'a, 'tcx>::resolve_regions_and_report_errors::ha6a986062307cc873YA
  11:     0x7f8da2cc9b70 - check::compare_method::compare_impl_method::h33ae495a649fd66cIgk
  12:     0x7f8da2cd21a0 - check::check_item::hf11061a9881d4ad88ll
  13:     0x7f8da2cd87f0 - visit::walk_item::h17525548578187088888
  14:     0x7f8da2cd87f0 - visit::walk_item::h17525548578187088888
  15:     0x7f8da2da1ee0 - check_crate::closure.32081
  16:     0x7f8da2d9c9c0 - check_crate::he229bdeb8fdc745cDNy
  17:     0x7f8da3ae5d80 - driver::phase_3_run_analysis_passes::h2272be7454e1eb80NFa
  18:     0x7f8da3acd130 - driver::compile_input::hb694f278d4428f99Bba
  19:     0x7f8da3b91940 - run_compiler::hc3e25a8f6c4a1b50n9b
  20:     0x7f8da3b90050 - thunk::F.Invoke<A, R>::invoke::h8035325489603501466
  21:     0x7f8da3b8efb0 - rt::unwind::try::try_fn::h9312387582241745294
  22:     0x7f8da35e9320 - rust_try_inner
  23:     0x7f8da35e9310 - rust_try
  24:     0x7f8da3b8f260 - thunk::F.Invoke<A, R>::invoke::h8464768559817507673
  25:     0x7f8da356a770 - sys::thread::thread_start::he52b8673a3629881W3w
  26:     0x7f8d9d767fe0 - start_thread
  27:     0x7f8da316c859 - __clone
  28:                0x0 - <unknown>
```

### PR DESCRIPTION
**Pull request by nikomatsakis**
Two changes:
1. Make traits with assoc types invariant w/r/t their inputs.
2. Fully normalize parameter environments, including any region variables (which were being overlooked).

The former supports the latter, but also just seems like a reasonably good idea.

Fixes #21750

cc @edwardw
r? @pnkfelix

### CODE REVIEW

File: src/librustc_typeck/variance.rs [hunk 1]
```diff
@@ -203,6 +203,56 @@
...
+//!
+//! ### Associated types
+//!
+//! Any trait with an associated type is invariant with respect to all
+//! of its inputs. To see why this makes sense, consider what
+//! subtyping for a trait reference means:
+//!
+//!    <T as Trait> <: <U as Trait>
+//!
+//! means that if I know that `T as Trait`,
```
Comment (pnkfelix) [inline src/librustc_typeck/variance.rs]: heh, what the heck happened to your emacs `fill-paragraph` settings here...

Comment (nikomatsakis) [inline src/librustc_typeck/variance.rs]: oh, I originally wrote that in a different location. I tried to refill all the paragraphs but I guess I missed one :)
